### ISSUE TITLE
Documentation for MTLLoader.MaterialCreator

### ISSUE THREAD

**Issue by positlabs** [mrdoob/three.js#10003]
pinging @angelxuanchang 

##### Description of the problem 
Missing docs for [`MTLLoader.MaterialCreator`](https://threejs.org/docs/?q=mtll#Reference/Loaders/MTLLoader)

There used to be some classes that implemented this, but they seem to have disappeared.

> A loader for loading an .mtl resource, used internaly by OBJMTLLoader and UTF8Loader.

https://github.com/mrdoob/three.js/issues/8085

@mrdoob, you suggest using MTLLoader in conjunction with OBJLoader, but what if I want to load the OBJ and MTL resources in parallel?

##### Three.js version
r82

**Comment by mrdoob** [comment]
> @mrdoob, you suggest using MTLLoader in conjunction with OBJLoader, but what if I want to load the OBJ and MTL resources in parallel?

No idea... 😇

**Comment by positlabs** [comment]
Ehh well the mtl files are usually pretty small. I suppose it's not a big deal to load them synchronously. I'll just rely on the OBJLoader's implementation of `MTLLoader.MaterialCreator`
