### ISSUE TITLE
glTF Loader issue again - pumpkin is dark

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#10026]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

This is a problem similar to #8381

http://jsdo.it/cx20/mZld
![image](https://cloud.githubusercontent.com/assets/1833979/20031900/94bcac5e-a3c2-11e6-9501-eb94fd2089a1.png)

![image](https://cloud.githubusercontent.com/assets/1833979/20031743/c08e4638-a3bf-11e6-871d-624266bd9f59.png)

if shininess value is 0 then u_shininess is undefined.

I propose that the fix as below.

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js#L1083-L1087

```javascript
//if ( value ) {
if ( value !== undfined ) {
    uvalue = value;
}
```

##### Three.js version

- [x] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

NG : ThinkPad X201 (Intel HD Graphics) + Windows 10 + Chrome 54.0.2840.87 m
NG : ThinkPad X201 (Intel HD Graphics) + Windows 10 + Firefox 49.0.2
NG : ThinkPad X201 (Intel HD Graphics) + Windows 10 + Edge/14.14393

**Comment by makc** [comment]
It takes like 10 seconds to create PR.
