### ISSUE TITLE
WebGLRenderer.supportsVertexTextures() does not output console.warn

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10029]
The function WebGLRenderer.supportsVertexTextures() is in Three.legacy.js but does not give a warning when used.

As far as I can see every other function in this gives a warning when used, is this one supposed to as well?

##### Three.js version

- [x] Dev
- [x] r82
- [ ] ...

**Comment by mrdoob** [comment]
Yeah, this should have a warning 👍
