### ISSUE TITLE
Showcase: Water with Flow Maps

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#10036]
I've developed this water effect some time ago. Not for a specific app but just for fun :wink:. Now i've updated the showcase to a recent `three.js` version and want to share the code in this issue.

[**DEMO**](https://yume.human-interactive.org/examples/water/)

The special feature of this water effect is the usage of a so called `flow map`. This texture is used to control the direction of the water flow. The following example of Valve ([Source](https://developer.valvesoftware.com/wiki/Water_(shader))) shows how such a texture is constructed. In the demo the water flows to north direction because the flow map has the respective green color.

![water_0_m_flow_sample](https://cloud.githubusercontent.com/assets/12612165/20037569/76753df0-a422-11e6-9efb-e6f7c4e69cc2.png)

The fragment shader will sample this texture and convert the color values to 2D flow vectors. These are used to distort the normal values in the direction of flow. With this approach you can effectively create more realistic and detailed water effects for e.g. rivers or streams.

Although the demo code is part of a bigger `three.js` project, you can extract the relevant files for your own projects. 

- [Shader code](https://github.com/Mugen87/yume/blob/water/src/javascript/engine/shader/WaterShader.js)
- [Water entity](https://github.com/Mugen87/yume/blob/water/src/javascript/engine/etc/Water.js)
- [Reflector](https://github.com/Mugen87/yume/blob/water/src/javascript/engine/etc/Reflector.js) and [Refractor](https://github.com/Mugen87/yume/blob/water/src/javascript/engine/etc/Refractor.js) are entities used for real-time reflections and refractions

ToDo's:

- Bugfixing
- It would be cool if this water effect would support all basic light entities of `three.js`. The current implementation only reacts on a single directional light source
- I'm sure there is some potential to improve the shader source code. It would be great if you can share your ideas in this issue!

For more background information read this publication: [Water Flow in Portal 2](http://www.valvesoftware.com/publications/2010/siggraph2010_vlachos_waterflow.pdf)

**Comment by user972611** [comment]
Hi, thank you for share this interesting feature!

I'm looking to use it with Three.js r84 but it doesn't work, please see in this fiddle: https://jsfiddle.net/k313cwtx/

Much appreciated!

**Comment by Mugen87** [comment]
Here is the updated version: https://jsfiddle.net/k313cwtx/4

Some things were missing in your first fiddle:

- You need to update the water in the animation loop with `water.update( delta );`
- The textures were not loaded correctly. My demo didn't consider the same origin policy. They are now loaded from `imgur`.
- You need to pass the scene within a `world` object. That's an instance of a special prototype that does not exists in your demo and `three.js` (it's from [YUME](https://github.com/Mugen87/yume)). So i just wrapped your scene in a simple proxy object.

**Comment by user972611** [comment]
Thanks a lot!

I'm trying to make the direction flow and air flow like this example: https://animagraffs.com/supercharger-vs-turbo/

I don't understand how to make the air flow moving to correct direction on a complex surface like that. Do you have any idea?

(I didn't see any flow map got downloaded in network tab, I'm thinking they might use some uv unwrap technique combine with animate the UV offset of texture)

**Comment by Mugen87** [comment]
I'm not sure if the code is suitable for this use case. It's primarily intended for flowing water surface effects like described in this blog post: http://graphicsrunner.blogspot.de/2010/08/water-using-flow-maps.html

So i actually don't know how to apply a comparable effect on a more complex surface, sry. You maybe need a totally different approach.

And yes, the new fiddle uses the flow map (https://i.imgur.com/Eu0MQrk.jpg). You can try other colors or variations like mentioned in the blog post.

BTW: The blog post and my implementation are based on the same technique that was initially presented by Valve. The corresponding presentation is linked in my first post.
