### ISSUE TITLE
Raycaster hits BackSide

### ISSUE THREAD

**Issue by knlyknly** [mrdoob/three.js#10058]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

The method 'checkIntersection' hits no FrontSide but BackSide.
Probably because I reversed the whole coordinate by:
`scene.scale.y = -1; // to left-handed coordinate system`

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

None

**Comment by WestLangley** [comment]
Right. Don't do that.

three.js does not support reflections in the object matrix, which is what you are doing by setting a single negative scale component.

**Comment by knlyknly** [comment]
I still consider this as a bug, even it seems not easy to fix. Raycaster should hits 'visible faces' rather that 'positive faces'.

I'm playing with canvas-2d and SVG, so left-handed coordinate system is much more convenient. To keep `scene.scale.y=-1` is much easier than reverse everything. I prefer to keep until `renderer.resetCoordinate(matrix4)` supported.

**Comment by mrdoob** [comment]
Sorry, we can't support `scene.scale.y=-1`...
