### ISSUE TITLE
glTF and Blender export : corrupted normals + vertices data

### ISSUE THREAD

**Issue by feiss** [mrdoob/three.js#10056]
I'm trying to load **a single triangle** exported to glTF directly from Blender, using [Daniel Stokes' exporter](https://github.com/Kupoman/blendergltf). 

`.blend` file can be downloaded [here](http://www.filedropper.com/triangle)

![image](https://cloud.githubusercontent.com/assets/359872/20081444/007d5040-a550-11e6-8af9-5adf788a7028.png)

Vertices at `(1, 0, 0)`, `(0, 1, 0)` and `(0, 0, 1)`. The equivalent JSON is this (removed the metadata):

```
{
    "faces":[32,0,2,1,0,0,0],
    "name":"PlaneGeometry.2",
    "vertices":[0,-0,-1,0,1,-0,1,0,0],
    "normals":[-0.57735,0.57735,0.57735]
}
```

[**This is the `triangle.gltf` file exported from Blender**](https://gist.github.com/feiss/1e503b585e61384a451c82aa4fd1f25e). 

I slightly modified the exporter for printing out the vertices and normals, and they were correct. (I put a `print(co[j])` and `print(normal[j])` in `blendergltf.py:518`)

I have to export with **selection only** checked. If it is unchecked, nothing appears on the scene.

Result: the mesh is corrupted. Normals are wrong and one vertex is bad -- Something get mixed in the bufferViews/accessors/whatever that it mixes some values from normals and vertex positions. If you try to import the `triangle.gltf` in the threejs editor, it looks like this:

![image](https://cloud.githubusercontent.com/assets/359872/20081711/9095a3fc-a551-11e6-8453-e1243826208c.png)

(the red dot is where that stranded vertex is supposed to be)

I also used `aframe-gltf.js` loader from @richtr and same happens. If I use developer tools to debug the loaded mesh, it shows:

![image](https://cloud.githubusercontent.com/assets/359872/20081862/750b960e-a552-11e6-87d8-d582ff9f59f2.png)

I guess @Kupoman , @richtr or @xirvr may want to take a look. I hope this is not a trivial problem caused for something I did wrong, the scenario is so simple I cannot grasp what I could have done wrong..

**Comment by mrdoob** [comment]
I suspect the exporter is the one failing here...

**Comment by pjcozzi** [comment]
I agree it could be the exporter, the model doesn't load here: http://cesiumjs.org/convertmodel.html

You could also try the validator (but it is for the glTF 1.1 spec work-in-progress): https://github.com/KhronosGroup/glTF-Validator

@feiss if you confirm this is an exporter issue, can you please submit an issue or PR to that repo?  A solid Blender glTF exporter will be super valuable to the community.

**Comment by mrdoob** [comment]
One could argue that the main reason glTF hasn't taken off yet is because of the lack of exporters...

**Comment by feiss** [comment]
I'll try to verify if it's an exporter problem, ask in their repo, and keep you informed. Thanks.

**Comment by yrns** [comment]
@feiss I've been hacking on the glTF exporter and loader. I believe the issue you're facing is that the exporter is exporting interleaved buffers. Three supports these, but the importer does not (yet). I can submit a PR.
