### ISSUE TITLE
Superfluous DataTextureLoader

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10050]
There is a loader defined inside the BinaryTextureLoader.js file:
https://github.com/mrdoob/three.js/blob/dev/src/loaders/BinaryTextureLoader.js#L12

    var DataTextureLoader = BinaryTextureLoader;

It's also exported from 
https://github.com/mrdoob/three.js/blob/dev/src/Three.js#L35

However other than that it doesn't seem to be used anywhere. 
Is there any reason to have two names for this class? Or can it be deleted?

**Comment by mrdoob** [comment]
I think I would prefer to deprecate `BinaryTextureLoader` in favour of `DataTextureLoader` as it produces a `DataTexture`.
