### ISSUE TITLE
can not load collada files with animation exported from blender

### ISSUE THREAD

**Issue by hartsantler** [mrdoob/three.js#10052]
##### Description of the problem 
collada files exported from blender work fine, but break when they have bone animation.
`loader.parse(...)` fails with no error.

##### Three.js version
pulled latest from the git repo.

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by MichaelHazani** [comment]
I've done this successfully in the past but have run into a lot of finicky animation-handling code with breaking changes in recent versions (so a lot of online info is no longer relevant). Can you post the relevant excerpt from your code? (And ideally the FBX as well, if you can.)

**Comment by Mugen87** [comment]
The current version of `ColladaLoader` should handle skeletal animation better than before.
