### ISSUE TITLE
Blender produces an error on the windows when exporting

### ISSUE THREAD

**Issue by webmarkelov** [mrdoob/three.js#10075]
Blender produces an error on the windows when exporting:
![untitled-1](https://cloud.githubusercontent.com/assets/12942199/20150643/f66dccb4-a6c7-11e6-9226-049a160ae58d.jpg)

##### Three.js version
- [x] 0.82.1

##### Blender

- [x] 2.78a

##### OS
- [x] Windows 10

**Comment by MichaelHazani** [comment]
Could you provide a link to the mesh in question? I'll try to repro.

**Comment by webmarkelov** [comment]
[file](https://s3-us-west-2.amazonaws.com/electronic-armory/blender-export.zip)

**Comment by MichaelHazani** [comment]
I was able to export the scene from Blender without any issues - see this [Clara.io](https://clara.io/view/c3feacc4-236b-42fd-9cd8-183a3bebeefc) link. I'm on 2.78, Win 10, threejs .82, same as you... If it's not a settings issue (see mine [here](http://imgur.com/a/sfxRN)) Perhaps try re-downloading and installing the importer add-on?

**Comment by webmarkelov** [comment]
I put it again as it is written in readme:

1) copy io_three to  C:\Program Files\Blender Foundation\Blender\2.7X\scripts\addons
2) Activate the Import-Export addon under "User Preferences" > "Addons" and then use the regular Export menu within Blender, select `Three.js (json)`.
3) To enable msgpack compression copy the msgpack to scripts/modules.

When I export with the same settings as you have again and get the same error.
Installed on a different machine windows 7 when you export the same error.

**Comment by webmarkelov** [comment]
810 line
```python
 from io_three import exporter
        if settings[constants.SCENE]:
            exporter.export_scene(filepath, settings)
        else:
            exporter.export_geometry(filepath, settings)

        return {'FINISHED'}
```
I do not understand such as exported with the same settings in the screenshot above that but got the same error

**Comment by MichaelHazani** [comment]
Very very weird. As that segments executes the export function, it's not deep enough in the call stack to give any useful info... 

Are you able to export simple primitives? Just the default cube, or something like that?

**Comment by webmarkelov** [comment]
Yes I tried all the same error

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/37dbb1751e7fdad26b58346dd3b3f3dfc665a1fd
