### ISSUE TITLE
The "Function.prototype.name" polyfill sometimes gives an incorrect name

### ISSUE THREAD

**Issue by Ikalou** [mrdoob/three.js#10071]
##### Description of the problem 
The polyfill for `Function.prototype.name` defined in https://github.com/mrdoob/three.js/blob/6c7f000734f8579da37fb39e5c2e9e5e2dfb14f8/src/polyfills.js#L23 can give an incorrect result if the function body starts on the same line as the function name. This sometimes break minified code for me. This happens specifically in IE 9 thought 11.

Here's an example:

This code...
``` javascript
function myFunction() {
  doSomething();
}
```
... gets the name `myFunction`.

But this code...
``` javascript
function myFunction(){doSomething();}
```
... gets the name `myFunction(){doSomething`, which is obviously wrong.

##### Three.js version

- [x] Dev
- [x] r82
- [x] r81

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer (9 through 11)

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
None.

**Comment by mrdoob** [comment]
Uh oh... I guess this would be a better regex?

```js
return this.toString().match( /^\s*function\s*([^\(\s]*)/ )[ 1 ];
```

**Comment by Ikalou** [comment]
It certainly works better for me. Thanks!
