### ISSUE TITLE
Documentation - menu sections suggestion

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10089]
Currently the Reference section of the documentation mainly documents the API, which I'm taking to mean anything that can be accessed via THREE.XXX.

There are a couple of things documented there that aren't part of the API though, such as:

Renderers / WebGL
- WebGLProgram
- WebGLShader
- WebGLState

Polyfills

And maybe a couple of other things, I haven't checked thoroughly. Also there are quite a few additional things that need documenting here. They are mainly useful to people developing Three rather than just using it though, so having them listed along with the API may be confusing.

Therefore I'd suggest separating these into two sections:
API and Reference
although I don't think those headings are entirely clear. 

Maybe API Reference and something else? Perhaps Developer Reference?

**Comment by aardgoose** [comment]
Internals for Developers? Indicates what they are and target audience...

**Comment by mrdoob** [comment]
How about documenting them but not adding them to the list? So you can link them from `WebGLRenderer`.

**Comment by looeee** [comment]
OK, here are the things that need documenting that would be part of the developer reference:

renderers / webgl
- WebGLBufferRenderer
- WebGLCapabilities
- WebGLClipping
- WebGLExtensions
- WebGLGeometries
- WebGLIndexedBufferRenderer
- WebGLLights
- WebGLObjects
- WebGLProgram
- WebGLPrograms
- WebGLProperties
- WebGLShader
- WebGLShadowMap
- WebGLState
- WebGLTextures
- WebGLUniforms

GLSL files in the renderers / shaders / shaderChunk & shaderLib

**Comment by looeee** [comment]
All these relate to the WebGL renderer so it would make sense linking them from there. But on the other hand for people that just want to use the renderer it would make it more confusing. 

Additionally if there was to be a developer reference section, it would be a useful place to put any instructions such as how to's for building a loader / exporter or other things such as lights / geometries. Which would be great additions to the docs.
