### ISSUE TITLE
CSS3D renderer bugs in Safari (Y lookAt)

### ISSUE THREAD

**Issue by jocabola** [mrdoob/three.js#10085]
Setting a lookAt target for a camera in a Y coordinate other than 0 breaks CSS3D Renderer in Safari. Using an older CSS3DRenderer.js fixes the issue but I am not sure when exactly this started happening and where exactly is the problem. The one I used to fix the issue is from quite a few versions back I think.

See example with the bug here: http://tmp.jocabola.com/threejs-css3d-safari-bug/
This one works correctly (using older CSS3D Renderer): http://tmp.jocabola.com/threejs-css3d-safari-ok/

If you open that link in Safari it will run correctly until you check "animateY" which will break the CSS3D renderer which will get stuck (no longer altering the matrix transformations).

Tested on latest Safari in OS X El Capitan (10.11.6)

Thank you so much for your amazing work guys!!

**Comment by Mugen87** [comment]
I assume this problem is caused by the a well know webkit bug, see #7802
