### ISSUE TITLE
OBJLoader/MTLLoader black render

### ISSUE THREAD

**Issue by Cale-92** [mrdoob/three.js#10090]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

Hi, i'm trying to import a .obj file and a .mtl file in my application.

```
var mtlLoader = new THREE.MTLLoader();

       mtlLoader.load( 'models/Tree/Tree.mtl', function( materials ) {

		materials.preload();

		var objLoader = new THREE.OBJLoader();

                    objLoader.setMaterials(materials);

                    objLoader.load( 'models/Tree/Tree.obj', function ( object ) {

                        object.scale.x = 75.0;

                        object.scale.y = 75.0;

                        object.scale.z = 75.0;

                        object.position.x = step/2;

                        object.position.z = step/2;

                        scene.add( object );
                    });
		});
```
The object is added correctly to the scene but the material is not showed although i have imported successfully the .mtl file.
Any suggestions?

##### Three.js version
- [ ] Dev
- [x] r82
- [x] r77.1

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by makc** [comment]
did you turn the lights on?

**Comment by Cale-92** [comment]
I was trying to find a solution to the problem an by changing the value of some properties in my .mtl file i have discovered that the material shows up.

```
 newmtl Trank_bark 

 illum 4 

  Kd 0.00 0.00 0.00 

  Ka 0.00 0.00 0.00

  Tf 1.00 1.00 1.00 

  map_Kd bark_0021.jpg
```
For example, by changing the values of the line starting with Kd to 0,5 the material shows up. Now i'm wondering where the problem might be and how it can be resolved. It is just a problem of my code, of the .mtl file or a problem of the MTLLoader itself?
