### ISSUE TITLE
Documentation for IDCount functions

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10095]
There are four IDCount functions:

- THREE.GeometryIdCount()
- THREE.MaterialIdCount()
- THREE.Object3DIdCount()
- THREE.TextureIdCount()

They are part of the API (can be accessed via THREE.GeometryIdCount() etc. ) so they should be documented. 

The question is, where? Should they get a separate page, or be included in the Geometry, Material... pages?

**Comment by aardgoose** [comment]
Note GeometryIdCount is also used by BufferGeometry which may influence your choice, which would tend to indicate a separate page, to avoid duplication.  Not sure how useful they are though.

**Comment by mrdoob** [comment]
These are not supposed to be accessible to the user. Now that we're using modules it's easier to hide those. I'll see if I can work this out.

**Comment by mrdoob** [comment]
GeometryIdCount is still pending to be removed. Will leave it for the next cycle though.

**Comment by looeee** [comment]
OK, I'll leave this open for now

**Comment by Mugen87** [comment]
We can't remove `GeometryIdCount()` like the other functions because both `BufferGeometry` and `Geometry` need to share the same ID generation. Should we agree to keep the function and close the issue?

**Comment by looeee** [comment]
I'm OK with this, although the functions should be documented if they are exposed

**Comment by Mugen87** [comment]
Then i would suggest to document `GeometryIdCount()` for now and note that the function is intended for internal usage only.

**Comment by dubejf** [comment]
You use even/odd Ids for `BufferGeometry` and `Geometry` and increment by two to get rid `GeometryIdCount()`.

**Comment by mrdoob** [comment]
> You could use even/odd Ids for `BufferGeometry` and `Geometry` and increment by two to get rid `GeometryIdCount()`.

Interesting! 😀

**Comment by Mugen87** [comment]
Indeed! :blush: We should give this a try!

**Comment by mrdoob** [comment]
Actually, I don't know why `GeometryIdCount` was public...

**Comment by mrdoob** [comment]
Okay. This can be closed now.
Thanks @dubejf!
