### ISSUE TITLE
Add deviceorientation control as  part of the THREE module

### ISSUE THREAD

**Issue by leomeloxp** [mrdoob/three.js#10106]
##### Description of the problem 
I just recently started playing with mobile device orientation API for controlling the camera and found that three already has an implementation for this on one of the example [pages](https://threejs.org/examples/misc_controls_deviceorientation.html)/[code](https://github.com/mrdoob/three.js/blob/6c7f000734f8579da37fb39e5c2e9e5e2dfb14f8/examples/js/controls/DeviceOrientationControls.js).

My question is: are there any plans to add this to the core library? I'm currently using three with a React app and having it as part of the core library would make things easier.

PS: Obviously I don't mind working on a PR to help pushing this forward but thought I better ask here first as someone could have tried this in the past or maybe there are legitimate reasons for deviceorientation API to not be included on core.

Cheers guys 🙂

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them

##### OS

- [x] All of them

##### Hardware Requirements (graphics card, VR Device, ...)

N/A

**Comment by mrdoob** [comment]
#9562
