### ISSUE TITLE
Very odd that browser said webgl not supported when loading three.js pages from local server?

### ISSUE THREAD

**Issue by georgeou2003** [mrdoob/three.js#10109]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

I try to load an example webpage (e.g webgl_materials_cubemap.html )from my local apache server , the mobile browser said it doesn't support webgl, however, when I load the exact webpage (https://threejs.org/examples/webgl_materials_cubemap.html )from three.js, the mobile browser loads it perfectly without any warning.

I wonder if it is the server problem or did i miss something important regarding to three.js

My browser is X5 based kernerl from micro msg. 

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by georgeou2003** [comment]
plus, if i  comment the detector code in the files, it cann't be loaded but it takes long time ti load.

**Comment by georgeou2003** [comment]
plus, if i comment the detector code in the files, it can be loaded but it takes long time ti load

**Comment by mrdoob** [comment]
Sounds like it's a web server issue...
