### ISSUE TITLE
Are "type" properties still needed?

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10105]
As per #7291, the type property was added to objects because the closure compiler was anonymizing constructors. Since switching to a modular build this should no longer be a problem, and indeed running the following:

```js
for(let p in THREE){
    if(typeof THREE[p] === 'function'){
	try{
	    console.log((new THREE[p]()).constructor.name);
        }
	catch(e){
	    // console.log(e);
	}
    }
}
```

outputs the correct names:
FogExp2
Fog
Scene
LensFlare
Sprite
LOD
Skeleton
Bone
Mesh
LineSegments
...

and so on. 

Is this property still needed? Or can it be refactored out?

**Comment by tentone** [comment]
I would probably keep them, the ones i think can go away are the ones like "isFont" or "isMaterial", the types can be useful sometimes for inheritance when creating modified versions of objects.

**Comment by makc** [comment]
why not `this.type = this.constructor.name` in all base classes then?

**Comment by tentone** [comment]
That is pretty much the way it is already, probably there is no benefit to change that.

**Comment by looeee** [comment]
It seems that .isThing properties are used quite a bit, for defining superclasses of objects (cameras, materials etc). A quick search through the code suggests there are over a 100 - 200 places where these functions are used, especially in the renderer. 

The type property on the other hand, as far as I can see is only used 2 or 3 places, in loaders, and whats  more textures also have an unrelated "type" property (UnsignedByteType, ByteType, ShortType etc), which means that this .type = constructor.name can't be used for textures.

**Comment by looeee** [comment]
The only downside as far as I'm aware is that constructor.name doesn't work for IE as it was not standard until ES6 - there is a polyfill though. 
http://matt.scharley.me/2012/03/monkey-patch-name-ie.html

**Comment by mrdoob** [comment]
> The only downside as far as I'm aware is that constructor.name doesn't work for IE as it was not standard until ES6 - there is a polyfill though. 
http://matt.scharley.me/2012/03/monkey-patch-name-ie.html

That's why we have this polyfill:

https://github.com/mrdoob/three.js/blob/dev/src/polyfills.js#L23-L38

**Comment by mrdoob** [comment]
I'll take a look at this! 👍

**Comment by mrdoob** [comment]
Seems like we still need these... It's true that the new modular structure retains the function names, but that only works with `three.js` and `three.modules.js`. `three.min.js` still obfuscates the function names...

![screen shot 2016-11-21 at 10 10 08](https://cloud.githubusercontent.com/assets/97088/20494675/eb95de62-afd2-11e6-8dc5-69a20f1666d9.png)

**Comment by looeee** [comment]
Ah, good catch! Thanks for investigating :)
