### ISSUE TITLE
Please consider using version number in build filenames

### ISSUE THREAD

**Issue by birgersp** [mrdoob/three.js#10102]
##### Description of the problem 

We're sewing togheter some projects using threejs. It would be really helpful if the threejs files had the build version in the filenames. That way, we know what threejs version a build is just by looking at the filename. This is especially helpful for the minimalized files, where the version number is sometimes hidden in "obfuscated" code.

If nothing else, it could be solved with a simplistic script processing the files when building...

##### Three.js version

- [ ] Dev
- [x] r82

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Have you tried doing `console.log( THREE.REVISION )`?

**Comment by birgersp** [comment]
Thanks for the tip. But I was hoping I wouldn't have to load the different threejs versions before identifying them.

**Comment by Mugen87** [comment]
It's quite uncommon for a library to do this. I refer at this point to `npm` or `bower`. These tools allow a clear management of your project dependencies.
