### ISSUE TITLE
Better animation documentation

### ISSUE THREAD

**Issue by majimboo** [mrdoob/three.js#10103]
I think we should have a better animation documentation. Like what kind of matrices should be entered to create the actions, specially for us who has custom file formats for 3d objects, bones and animation. 

The documentation could temporary even just link to the source code that does the transformation of the bones based on the frame matrices provided and the developer could understand for himself.

This things wouldn't be needed though for people who use the exporter from blender and the likes.

I also noticed some documentation templates are in the source but can't be found on the docs site. Any reasons for this?

Great work on Three.js! Cheers

##### Description of the problem 
Missing documentation.

##### Three.js version

- [x] Dev
- [x] r82

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by looeee** [comment]
I recently updated the animation documentation, it's on the dev branch but not r82. Have you seen it? 

It's quite basic though as yet, I agree it definitely needs more detail.

**Comment by majimboo** [comment]
Any idea what kind of bone matrices the animation system accepts: local, model, or world?

**Comment by majimboo** [comment]
Found out, you need to provide local to hierarchy matrices.

**Comment by looeee** [comment]
Stub documentation has been added for all Animation classes. Unfortunately this part of the code is considerably more complex than anything else (except for the renderer and shaders) and I haven't had time to understand it well enough to write documentation... and don't have much inclination to either as I use GSAP for animation. 

@tschw, @bhouston, it looks like you guys wrote most of it (along with David Sarno, but I can't find his github handle) - do you think you might be able to write some documentation? I'd be happy to go over formatting/add links so on if the basic property/method/usage descriptions were in place.

As it stands, I think most people will not use this system as it is hard to understand from the code and provided examples.

**Comment by Mugen87** [comment]
@mrdoob I think we can close this issue. @looeee, @jostschmithals, @donmccurdy and others did a great job in improving the documentation over the last month 👍

**Comment by jostschmithals** [comment]
@majimboo The new articles are not yet published, but they can already be seen in the dev branch; for example https://rawgit.com/mrdoob/three.js/dev/docs/#Manual/Next_Steps/Animation_System, https://rawgit.com/mrdoob/three.js/dev/docs/#Reference/Animation/AnimationAction and so on.
