### ISSUE TITLE
Outline and Unreal Bloom examples are broken

### ISSUE THREAD

**Issue by fazeaction** [mrdoob/three.js#10113]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

With the last update, "gaussianPdf" function is declared in common.glsl file. The problem is that "outline pass" (examples/js/postprocessing/OutlinePass.js) and "unreal bloom" have this function too. Just removing them, solve the problem.

**Comment by WestLangley** [comment]
>With the last update, "gaussianPdf" function is declared in common.glsl file. 

/ping @sam-g-steel 

I'd remove the function from `common.glsl`, and leave the postprocessing code as-is.

**Comment by mrdoob** [comment]
Thanks!
