### ISSUE TITLE
Please add the feature of glowing edges.

### ISSUE THREAD

**Issue by digiperfect-sandeep-kumar** [mrdoob/three.js#10125]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
Hi Mr.Doob,

Could you please add the feature of glowing edges of 3d object in three.js. For example : In this code [link](https://jsfiddle.net/bo7vj4rm/1/) could you add a API in three.js to glow the red edges of the cube.

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by looeee** [comment]
There are several ways of doing this already in Three - have you seen the THREE.EdgesGeometry?

It's used in this example: https://threejs.org/examples/?q=help#webgl_helpers

**Comment by digiperfect-sandeep-kumar** [comment]
I am trying to add glowing edges like this : [link](http://66.media.tumblr.com/c0c1816a06895886be55b208d468c934/tumblr_inline_myfyi1OXKt1rf8gv8.jpg)

**Comment by mrdumb** [comment]
> I am trying to add glowing edges like this link

Those are not glowing edges.
That's a post processing effect (Bloom).
Example: https://docs.unrealengine.com/udk/Three/Bloom.html

**Comment by makc** [comment]
the shittiest glow I could do in 15 minutes: https://jsfiddle.net/bo7vj4rm/3/ because I'm slow typer

**Comment by makc** [comment]
slightly better glow: https://jsfiddle.net/bo7vj4rm/4/

**Comment by mrdoob** [comment]
> > I am trying to add glowing edges like this link

> Those are not glowing edges.
That's a post processing effect (Bloom).
Example: https://docs.unrealengine.com/udk/Three/Bloom.html 

And we have it already ✌️

https://threejs.org/examples/?q=bloom#webgl_postprocessing_unreal_bloom

**Comment by digiperfect-sandeep-kumar** [comment]
Hi mrdoob,

I tried to change my [code](https://jsfiddle.net/bo7vj4rm/5/) as per your previous comment. But I didn't get glowing edges even after using THREE.UnrealBloomPass.

**Comment by digiperfect-sandeep-kumar** [comment]
Hi

**Comment by makc** [comment]
try var bloomPass = new THREE.UnrealBloomPass(new THREE.Vector2(window.innerWidth, window.innerHeight), 3, 0, 0.1)

**Comment by digiperfect-sandeep-kumar** [comment]
Thanks makc !

But by using FXAAShader and EffectComposer rather than renderer I am not getting very good antialiasing effect. Here is the [code](https://jsfiddle.net/bo7vj4rm/8/).

**Comment by makc** [comment]
lol, just add it twice 😝
![screen shot 2016-11-23 at 14 49 34](https://cloud.githubusercontent.com/assets/242577/20564156/2a6f23b8-b18c-11e6-8ce1-6b68f1140474.png)
![screen shot 2016-11-23 at 14 48 06](https://cloud.githubusercontent.com/assets/242577/20564165/3688b24a-b18c-11e6-93a9-acfd11c679f3.png)
