### ISSUE TITLE
cannot import name 'AREA'

### ISSUE THREAD

**Issue by jaysnanavati** [mrdoob/three.js#10126]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
Hi - I have followed the instructions to install and activate the blender-three.js exporter addon, however when trying to export, I get ImportError: cannot import name 'AREA', why is this happening? 

##### Three.js version

- [x] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/37dbb1751e7fdad26b58346dd3b3f3dfc665a1fd
