### ISSUE TITLE
setFaceCulling not working for the renderer

### ISSUE THREAD

**Issue by boyravikumar** [mrdoob/three.js#10120]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] IOS

**Comment by takahirox** [comment]
Maybe because `material.map` overrides cull_face setting in rendering.

https://github.com/mrdoob/three.js/blob/6404d18493e9d75bd12bf5f7ae787d0ea51dac2b/src/renderers/WebGLRenderer.js#L1645-L1663

I'm wondering what `WebGLRenderer.setFaceCulling()` is for...

**Comment by Mugen87** [comment]
I would say we can remove `WebGLRenderer.setFaceCulling()`.

@mrdoob @WestLangley What do you think about this issue?

**Comment by WestLangley** [comment]
It is OK to remove it. Users can directly call the methods it calls -- if they dare to do so...
