### ISSUE TITLE
Clip meshes with caps

### ISSUE THREAD

**Issue by rwirz** [mrdoob/three.js#10135]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Three.js version

- [x] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

Since Clip has been released in the latest version, What about to put caps?

Something like this project, done using three.js

https://github.com/daign/clipping-with-caps

Thanks

**Comment by WestLangley** [comment]
See [this stackoverflow post](http://stackoverflow.com/questions/37090942/how-to-render-clipped-surfaces-as-solid-objects) for simple work-arounds.

Also see [this stackoverflow answer](http://stackoverflow.com/questions/36557486/three-js-object-clipping/37593904#37593904).

**Comment by rwirz** [comment]
Hi,

Checked both approaches.

The first one only works with one mesh. If you have various meshes (one inside another, for example), the approach doesn't work.

The second approach is the same than my link and I was asking if it is possible to have it in three.js by default.

**Comment by WestLangley** [comment]
The second approach requires multiple render passes, and is more appropriate for the application layer. Plus, it does not work on all geometries, so it is use-case specific.
