### ISSUE TITLE
Issue with postprocessing outline example

### ISSUE THREAD

**Issue by rwirz** [mrdoob/three.js#10134]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Three.js version

- [X] Dev
- [ ] r82
- [ ] ...

##### Browser

- [] All of them
- [X] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

I download the source code as in this page said:
https://github.com/mrdoob/three.js/wiki/Build-instructions

And in Chrome, I use this URL:
http://localhost/lib/three.js/examples/?q=pos#webgl_postprocessing_outline

When the example is loaded, I click in one object and....(see image). Something is wrong.
![untitled](https://cloud.githubusercontent.com/assets/8203181/20324713/36590e50-ab47-11e6-9bf7-0fdbf29c2f2c.png)

**Comment by takahirox** [comment]
It seems like this issue has been already fixed. #10113

**Comment by rwirz** [comment]
Resolved as takahirox said.

**Comment by rwirz** [comment]
I checked the code of common.glsl and the function gaussinPdf is not definned.

https://github.com/mrdoob/three.js/commit/e9122654d2803577f96bbf75b72a7555d3c2bf59

But I am having the same issue

**Comment by rwirz** [comment]
Opening since is not resolved in the lastest version of Dev

**Comment by mrdoob** [comment]
> Opening since is not resolved in the lastest version of Dev

It really is fixed in the latest version of `dev`.
