### ISSUE TITLE
I hope Threejs's Editor can support MultiMaterial

### ISSUE THREAD

**Issue by zhoushijie163** [mrdoob/three.js#10137]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
Threejs's Editor currently does not support MultiMaterial. I think this is very important for a 3D Model Editor.

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/10931#issuecomment-290742976, but edit option is not yet implemented

**Comment by TyLindberg** [comment]
I think this is fixed as of #11835
