### ISSUE TITLE
BoundingBoxHelper and BoxHelper

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10143]
Is there a reason why both of these exist? 

BoxHelper internally uses a LineSegments like most Helpers.

BoundingBoxHelper  uses a BoxGeometry with a wireframe material and thus has diagonals, which are probably not what people want from a helper. 

They are identical in function otherwise so having both seems redundant. 

If there is a reason for both that I haven't spotted, fine. Otherwise I'll submit a PR to deprecate BoundingBoxHelper.

**Comment by WestLangley** [comment]
`BoxHelper` has morphed over time to acquire features of `BoundingBoxHelper`, which has always computed the bounding box of an object and its children -- not just the object's geometry bounding box.

I think `BoxHelper` is the better implementation at this point, so you deprecate `BoundingBoxHelper`.

Please note in the documentation that the helper shows the world-axis-aligned bounding box for an object (including its children), accounting for both the object's, and children's, world transforms.

`BoxHelper` also supports `Box3` as an argument, apparently.

@looeee Thanks for your efforts on clarifying this.

**Comment by looeee** [comment]
@WestLangley Ok, great. I'll get onto that.
