### ISSUE TITLE
Doesn't sorting the objects based on Material.Transparency contradicts with onBeforeRender of Object3D? 

### ISSUE THREAD

**Issue by swomack** [mrdoob/three.js#10150]
I have 100 meshes and only one material for all the meshes. I have to make the objects transparent  based on user interaction. What i have done is, i changed the material transparency in `onBeforeRender` of the mesh and changed it again in `onAfterRender`. But since objects gets sorted based on the `Material.Transparent`, it does not work properly.

So if we can change the transparency in `onBeforeRender`, shouldn't we sort the object based on something other than `Material.Transparent`? 

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
How about just doing `material.visible = false;`?

**Comment by swomack** [comment]
@mrdoob  Can you please explain it further? I need to make one of my meshes transparent, not invisible. I dont understand how doing `material.visible = false;` would help.

Thanks.

**Comment by mrdoob** [comment]
Then do `mesh.material.transparent = true`?

**Comment by WestLangley** [comment]
Why not set `material.transparent = true` and `material.opacity = 1` to begin with?

**Comment by WestLangley** [comment]
Hehe. You beat me by 8 sec...
