### ISSUE TITLE
Can we have 2 texture images on a single face of a cube.

### ISSUE THREAD

**Issue by mohitmunjal2801** [mrdoob/three.js#10153]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Usnul** [comment]
First of all, please consider what it is you are asking. If i draw a triangle with a red texture, and then i draw a triangle with a green texture, I end up with a green triangle. What you are asking is not meaningful.

**Comment by WestLangley** [comment]
Here is a related SO answer: http://stackoverflow.com/questions/12368200/displaying-background-colour-through-transparent-png-on-material/13547817#13547817
