### ISSUE TITLE
BoxHelper does not work on Sprites

### ISSUE THREAD

**Issue by gadlol** [mrdoob/three.js#10152]
After the version r74 the BoxHelper does not work for sprites - ( Sprite & SpriteMaterial) because the BoxHelper uses the function Box3 and that function needs geometry to calculate the min, max....

Before and r74 the Sprite had:

geometry: THREE.BufferGeometry
geometry.type: "BufferGeometry"

But after r74 the geometry property in the object created with new THREE.Sprite does not exist AND so the Box3 does not work and so the BoxHelper does not work.

- [x] Dev
- [x] r82
- [x] r81
- [x] ...
- [ ] r74
- [ ] r73

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by gadlol** [comment]
A solution can be adding geometry for sprites just like before and r74.

Find the:

`   function Sprite( material ) {`

and add:

```
    var indices = new Uint16Array( [ 0, 1, 2,  0, 2, 3 ] );
    var vertices = new Float32Array( [ - 0.5, - 0.5, 0,   0.5, - 0.5, 0,   0.5, 0.5, 0,   - 0.5, 0.5, 0 ] );
    var uvs = new Float32Array( [ 0, 0,   1, 0,   1, 1,   0, 1 ] );

    var geometry = new THREE.BufferGeometry();
    geometry.setIndex( new THREE.BufferAttribute( indices, 1 ) );
    geometry.addAttribute( 'position', new THREE.BufferAttribute( vertices, 3 ) );
    geometry.addAttribute( 'uv', new THREE.BufferAttribute( uvs, 2 ) );

    this.geometry = geometry;
```

after the:

`   Object3D.call( this );`

**Comment by looeee** [comment]
Does it make sense for BoxHelper to work for sprites though? By definition they are 2D so a box is unnecessary to visualize them. 

Adding a geometry to every sprite purely for the purpose of making this helper work doesn't seem like a good idea - what about situations where you have thousands of sprites? 

An alternative solution is to create a square red texture and apply that to any sprites that need to be positioned.

**Comment by gadlol** [comment]
@looeee It does not make sense for BoxHelper to work with sprites because I guess that the boxhelper is for 3d objects that have geometry and so if apply to an object it will create a square box.

But in the sprite the square box does not make sense because the Sprite is 2d.

So if we wanted to use the boxhelper in sprites we need to display a square box side only.

Check the attached image so to see what i mean....

![sprite_withgeomtry_and_boxhelper](https://cloud.githubusercontent.com/assets/518451/20390909/9154e69c-acd9-11e6-96a7-dd90d605d36f.png)

**Comment by mrdumb** [comment]
> So if we wanted to use the boxhelper in sprites we need to display a square box side only.
> Check the image below so to see what i mean..

For sprites you don't need BoxHelper.
If you really need something, that's SquareHelper !
LOL

**Comment by looeee** [comment]
Perhaps there should be a spriteHelper? It would be easy to implement I think. 

Again though a simple alternative is to create a texture with a green border and transparent centre, duplicate your sprite and apply that texture to it. You should see something similar to your image.

**Comment by gadlol** [comment]
@mrdumb Yes SquareHelper would be nice or SpriteHelper as @looeee suggests. I ll try to create that...

**Comment by aardgoose** [comment]
Sprites may be 2d but they have position in the 3d space, points which are also just 2d are handled by Box3, 
should sprites be treated in the same way?

**Comment by gadlol** [comment]
@aardgoose you have a point....

**Comment by aardgoose** [comment]
Added this PR #10198, doesn't bloat the Sprite() object, tested with webgl_sprites example, which is a good example of sprites in a 3D setting.

**Comment by Mugen87** [comment]
Closing see https://github.com/mrdoob/three.js/pull/10198#issuecomment-273793266

Like noted in the [docs](https://threejs.org/docs/index.html#api/helpers/BoxHelper), `Box3` is not compatible with `Sprites`.
