### ISSUE TITLE
Blender Exporter currently broken on osx for three.js dev

### ISSUE THREAD

**Issue by alvinsight** [mrdoob/three.js#10158]
##### Description of the problem 

Hi, I see you are doing some work on the blender exporter, which is great! So this might not be relevant at the moment, but I'll throw it out there.

On OSX El Capitan, and the latest version of Blender (2.78) the exporter is not currently working, this the error that I'm getting: 
![screen shot 2016-11-17 at 18 23 44](https://cloud.githubusercontent.com/assets/4254030/20403320/654e1fb8-acf8-11e6-8370-73c30cc00d86.png)

The exporter that is currently on the master branch works fine.

##### Three.js version

- [x] Dev

##### OS

- [x] OSX El Capitan

**Comment by mrdoob** [comment]
Hmm... That sounds familiar... #10126

**Comment by mrdoob** [comment]
Ok, do you mind testing with the latest in `dev`?
