### ISSUE TITLE
ExtrudeBufferGeometry: Brainstorming

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#10160]
`ExtrudeGeometry` and `TextGeometry` are the last geometry entities of the core that are based on `Geometry`.  Because `ExtrudeBufferGeometry` will be the most complicated port, i'd like to gather some ideas and opinions.

I've developed a very basic prototype to get a better understanding of the implementation. This [demo](https://jsfiddle.net/qkftq331/3/) shows an `ExtrudeBufferGeometry` without bevel and uv support. Shapes with holes are initially not supported, too. Some things to consider:

- The implementation uses `computeVertexNormals` to provide smooth vertex normals to address issues like #9862. This behavior is different compared to `ExtrudeGeometry` that only provides face normals. Unfortunately, the result of `computeVertexNormals` is not satisfying in all cases. You can see an exemplary error on the side of the mesh. Maybe we can use a different approach for calculating the vertex normal via the tangent of the corresponding point on the shape curve. Currently, there is no API to retrieve the tangents in `ExtrudeBufferGeometry` so we would need some additional methods in `Shape` and  `CurvePath`. 

1. Does anyone have an idea how we could use the tangents of a curve to retrieve normal vectors? 
2. Besides, is this a valid approach at all?
3. Is it generally okay to provide smooth normals? Users need to apply `THREE.FlatShading` to achieve the same visual appearance like `ExtrudeGeometry`. 

![image](https://cloud.githubusercontent.com/assets/12612165/20404698/4d946b8a-ad06-11e6-860f-776e67c3a392.png)

- I wonder if we can transfer the entire bevel logic in a separate `BevelModifier`. This generic entity could be then used for all geometries (like `BoxBufferGeometry`). But i'm afraid, that this code will be way more complex than the current implementation in `ExtrudeGeometry`. Does anyone have experience in this area?

- I've renamed the parameters `steps` to `depthSegments` and `amount` to `depth`. This is more consistent compared to `BoxBufferGeometry`.

**Comment by makc** [comment]
> calculating the vertex normal via the tangent of the corresponding point on the shape curve

for S-shaped curves this flips.

**Comment by Mugen87** [comment]
@makc If we know the movement direction of the contour (or the point sequence), we should be able to solve this problem, right? 

Besides, can you show me an example of an S-shaped curve? Just to be sure we have the same understanding :wink:

**Comment by makc** [comment]
I was just thinking [this](https://en.wikipedia.org/wiki/Frenet%E2%80%93Serret_formulas):
![TNB](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Frenet.png/300px-Frenet.png)
See, the N points sort of "inwards" there, so for "C"-shaped curve it would point right, for "Ↄ"-shaped curve it would point left, and if you join them together into "S"-shaped curver, it has to flip at the joint point. For "I"-shaped curve (line segment) only T vector is well-defined, and N would be zero (a math's way of saying "I have no way to pick direction, they are all the same"). Of course, it's not a problem if you just set curve's TNB vectors manually or using some parameterized expression but, if it's just some bezier path through a bunch of points the user just selected at random, you would be in trouble.

**Comment by makc** [comment]
In fact, how do you even get a vertex position in that case? Because to offset a vertex from the curve point, you first need specific direction? And that direction is pretty much the best estimate of vertex normal that can be there.

**Comment by makc** [comment]
ok, I did now check the actual source - the last thing we do, right - and it uses [different calculation](https://github.com/mrdoob/three.js/blob/1835f8a06bce0cc3bf3807d258705a3cf445d1cd/src/extras/core/Curve.js#L268-L270) precisely so that there would be no flip. we're safe here :)

**Comment by Mugen87** [comment]
Phew! I knew in advance that implementing `ExtrudeBufferGeometry` won't be easy. I hope i have more time for this in the next weeks. There are a lot of little pieces to get going...

**Comment by mflux** [comment]
+1 on separating extrude from bevel -- I always thought it was weird to combine the two features.

Bevel should really be a modifier, which you pass specific faces to as selection surface in which to bevel.

There are other arguments to be made though, bevel really is just another extrude with offset, so the ultimate feature should be just an extrude geometry modifier that takes either a whole geometry or faces as its selection (a'la Maya, 3DstudioMax, basically how every 3d package does it).
