### ISSUE TITLE
how to install on web server for utilization?

### ISSUE THREAD

**Issue by amitsavla** [mrdoob/three.js#10163]
hi my self Amit Savla,
am new at 3D printing web development.
please suggest me for,  how to install three.js on web server for utilization? (Purpose : Quick Quotation)

Some Steps. or web source file can i get from somewhere?

Thank you. ;)

**Comment by MrOpposite** [comment]
First off, read what's in the textbox when creating issues.
```This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow.```

Second, for examples on how to use this library, look in the examples folder.

I'm sorry, but this issue tracker is for problems with the implementation/new features only. There are other sites available for help with usage of the library (such as stackoverflow). This is a rather popular library and I'm sure someone will be able to help you!
