### ISSUE TITLE
Blender Exporter never forgets animations

### ISSUE THREAD

**Issue by brunoimbrizi** [mrdoob/three.js#10182]
##### Description of the problem 
Blender Exporter `three.js/utils/exporters/blender/addons/io_three` seems to be storing animation information even after it was cleared from Blender.

Here is a screen capture showing the problem: https://www.youtube.com/watch?v=Kf6ybeomp0A

Steps:
- Open a rigged model in Blender
- With Makehuman, load and retarget a .bvh file
- Export > Three.js (.json)
- .json file `animation` array now contains 1 animation
- So far, so good

_Issue 1_
- Back to Blender, clear animation data, all key frames are gone
- Export > Three.js (.json)
- All key frames are back
- .json file `animation` array **still** contains 1 animation

_Issue 2_
- Back to Blender, clear animation data again
- With Makehuman, load and retarget different .bvh file
- Export > Three.js (.json)
- .json file `animation` array now contains **2 animations**

##### Three.js version

- [x] Dev
- [x] r82

##### OS

- [x] Windows - Blender 2.78
- [x] Mac OS - Blender 2.77

**Comment by brunoimbrizi** [comment]
Found it...
![image](https://cloud.githubusercontent.com/assets/880280/20466696/8f7d1716-af6f-11e6-9dbd-e0e6f6ebd314.png)

Even if the animations (actions) are not used in the scene, they still exist in the Blender File. The exporter seems to be using those instead of the one currently active on the armature.

**Comment by manthrax** [comment]
@brunoimbrizi Even though they aren't used, they are still in the .blend, and won't go away until their references have been manually freed.

To remove them, you have to remove all references, save, and then re-open the blend file.

This is a known issue with blender.

https://www.blender.org/forum/viewtopic.php?t=4778

and also try googling "blender cant remove actions from scene"
