### ISSUE TITLE
LineMaterial clipping and Slow FPS on Chrome

### ISSUE THREAD

**Issue by chrsmlls333** [mrdoob/three.js#10184]
##### Description of the problem 
On Chrome Version 54.0.2840.99 m

Don't know at what point it started but approx 3 weeks ago, an update in Chrome disrupted efficient processing and LineBasicMaterial display, you can check here at [ 3js Example: webgl_loader_collada_keyframe](https://threejs.org/examples/#webgl_loader_collada_keyframe). The gridlines below the animation selectively render, depending on distance to the camera. Processing is notably slower than usual. I know its Chrome only because Firefox still reacts as usual.

![2016-11-20](https://cloud.githubusercontent.com/assets/7692426/20474851/77974b7c-af7d-11e6-8af9-b25b13f97a59.png)

Is anyone else having this bug? It seems relatively critical if so, as it applies to all current/past Threejs versions I think.

##### Three.js version

- [ ] Dev
- [x] r82
- [x] r80
- [x] r73

##### Browser

- [ ] All of them
- [x] Chrome 54.0.2840.99 m
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Win 10 Pro
Intel i7 i74510U
AMD Radeon R9 M275

**Comment by mrdoob** [comment]
Can you see the issue on Firefox and Internet Explorer too? Otherwise you may want to report this to Chrome instead.

**Comment by aardgoose** [comment]
No problem here on same Chrome version (64bit)  (Windows 10, Nvidia GTX 960M) stable 60fps and lines rendered fine.

**Comment by chrsmlls333** [comment]
Reference to Chromium Issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=674092

**Comment by looeee** [comment]
Looks fine to me, tested on Chrome 54.0.2840.99 m (64-bit) and 55.0.2883.87 m (64-bit), windows 10 gtx 970m, also 60fps and all lines rendering.
