### ISSUE TITLE
Materials class missing alias for MeshFaceMaterial to MultiMatieral

### ISSUE THREAD

**Issue by jayjlawrence** [mrdoob/three.js#10193]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

An alias for MeshFaceMaterial is being exported at the main class level:

 	exports.MeshFaceMaterial = MeshFaceMaterial;

However the Objectloader uses the Materials class to instantiate an object like this:

   material = new Materials["MeshFaceMaterial"]();

Unfortunately the Materials class is missing a reference for MeshFaceMaterial to point to MultiMaterial

	var Materials = Object.freeze({
		ShadowMaterial: ShadowMaterial,
		SpriteMaterial: SpriteMaterial,
		RawShaderMaterial: RawShaderMaterial,
		ShaderMaterial: ShaderMaterial,
		PointsMaterial: PointsMaterial,
		MultiMaterial: MultiMaterial,
		MeshFaceMaterial: MeshFaceMaterial,
		MeshPhysicalMaterial: MeshPhysicalMaterial,
		MeshStandardMaterial: MeshStandardMaterial,
		MeshPhongMaterial: MeshPhongMaterial,
		MeshNormalMaterial: MeshNormalMaterial,
		MeshLambertMaterial: MeshLambertMaterial,
		MeshDepthMaterial: MeshDepthMaterial,
		MeshBasicMaterial: MeshBasicMaterial,
		LineDashedMaterial: LineDashedMaterial,
		LineBasicMaterial: LineBasicMaterial,
		Material: Material
	});
 
What is needed is to add a line that says MeshFaceMaterial: MultiMatierial,

I just don't know how to do that otherwise I'd submit a patch. Sorry!

##### Three.js version

- [X] Dev
- [X] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Hectate** [comment]
This link will let you edit Materials.js:
https://github.com/mrdoob/three.js/edit/dev/src/materials/Materials.js

I see that Three.Legacy.js includes an [export for this though](https://github.com/mrdoob/three.js/blob/dev/src/Three.Legacy.js#L76); are you sure it's needed? (I can't say myself, too new).

**Comment by looeee** [comment]
The MeshFaceMaterial has been renamed to MultiMaterial - you should use that instead. The alias is defined in Three.Legacy.js and should probably have a warning when creating a MeshFaceMaterial

I'll submit a pull request to add one.
