### ISSUE TITLE
Misleading name "ManualMSAARenderPass" in Examples

### ISSUE THREAD

**Issue by NickGerleman** [mrdoob/three.js#10196]
##### Description of the problem 
When looking through post-processing code I came across ManualMSAARenderPass. To my understanding it looks like this does simple supersampling instead of multisampling since it is re-rendering the entire scene for each sample taken. If I'm not missing something I think it may make sense to modify the name to something like "Manual**SSAA**RenderPass" instead of "Manual**MSAA**RenderPass" as well as update the comments in code and the example.

##### Three.js version

- [x] Dev
- [x] r82

**Comment by bhouston** [comment]
You are right, it should be SSAARenderPass.  Might as well remove the Manual part from the name as well.  If you can make this correct via a PR @NickGerleman , it would be useful. :)

**Comment by NickGerleman** [comment]
Can do :)
