### ISSUE TITLE
SSAO not working with logarithmic depth buffer

### ISSUE THREAD

**Issue by Avocher** [mrdoob/three.js#10199]
##### Description of the problem 
At the moment SSAO only works with linear depth buffer. It would be nice if we could use it with logarithmic depth buffers too.

##### Three.js version

- [x] Dev
- [ ] r82
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

N/A

**Comment by jbaicoianu** [comment]
I've created pull request #10213 which fixes this, but note that because of the math involved, logarithmic depth buffer significantly decreases the precision of the depth buffer for closely-placed objects, leading to decreased SSAO quality.

**Comment by jbaicoianu** [comment]
This was fixed a while back but never got closed, I don't have permission to close it though
