### ISSUE TITLE
sorting for isMultiMaterial is not always stable

### ISSUE THREAD

**Issue by mikearmstrong001** [mrdoob/three.js#10201]
##### Description of the problem 

sorting for isMultiMaterial render items is not stable.

Chrome's array sort is not stable and as there is no guaranteed ordering in the compare the sorted order of groups will not be stable.

The input parameters for the osrt are solely based on the object, could an additional param be added that is based on the ground index ?

https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1424

##### Three.js version

- [X] Dev
- [ ] r82
- [ ] ...

##### Browser

- [ ] All of them
- [X] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Hmm, I can imagine yeah... Any chance you can provide a jsfiddle we can test with?

**Comment by mikearmstrong001** [comment]
here you go

https://jsfiddle.net/t40qvg9L/

FYI I added a groupIndex to make the sort stable should the the z compare be equal

**Comment by WestLangley** [comment]
Closing due to age. If there is an issue in a recent three.js revision, please file a new issue.
