### ISSUE TITLE
Document what lights effect what materials

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10200]
Several of the light docs state:

**Affects objects using MeshLambertMaterial or MeshPhongMaterial.**

in their description. Obviously this is out of date now as at the very least there are Standard and Physical materials. 

Does anybody know which materials are affected by which lights? If not I'll run some tests.

Also, would it be sufficient to add this information just once at the base Light doc? Or should it be stated per light?

**Comment by Hectate** [comment]
As someone who has recently started learning three.js, having the material types noted on each light subclass is super helpful. It's basic-usage information that should be immediately available when reading about the class.

Perhaps there's a way to include a template statement that can be referenced in each light doc file, and then if it ever needs updated we just have to touch the template and all the files update?
