### ISSUE TITLE
Bug when binding a SkinnedMesh while animation is active

### ISSUE THREAD

**Issue by majimboo** [mrdoob/three.js#10208]
Binding a new mesh while an animation is active deforms the (mesh) animation. (multiple mesh sharing a skeleton)

##### Description of the problem 

Take for example a character where you can replace an article of clothing at run-time. While walking around you change an equipment. When you do this with the current dev (updated 10 hours ago) the animation or deform gets bugged, 

Current work-around:

    // play walk animation while moving around
    mixer.existingAction("walk").play();
    // change an article of clothing
    mixer.stopAllAction(); // stop action first
    changeArmorMeshAndRebind();
    // now re activate the action (won't work if you `changeArmor` before `stopAllAction`
    mixer.existingAction("walk").play();

Doing the work-around gives ugly results as the animation isn't smooth, it will look like it skipped.

I have tried replacing the geometry and material of the existing mesh, instead of creating a new mesh and disposing of the old one. But it gives the same bugged result.

Replacing the mesh approach (bugged):

    var original = character.getObjectByName("armor");
    character.remove(original);
    original.geometry.dispose();
    original.material.dispose();
    original = null;
    // then create the new mesh to be used as armor
    createNewMeshAndBind();

Replacing geometry/material approach (bugged):

    var original = character.getObjectByName("armor");
    original.geometry = geo;
    original.material = mat;

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by majimboo** [comment]
Is it true that replacing the geometry and material of a mesh is a lot more expensive than creating a new mesh and disposing of the old one?

**Comment by makc** [comment]
I suppose if you put old geometry into new mesh, it is not expensive at all. even creating the very same material should reuse existing shader program, I think.

**Comment by Mugen87** [comment]
> even creating the very same material should reuse existing shader program, I think.

Correct.

In any event, a live example is required here for investigation. The issue can be reopened if the OP or another user share a demo for testing and debugging.
