### ISSUE TITLE
Keep the an object static with respect to the another object

### ISSUE THREAD

**Issue by digiperfect-sandeep-kumar** [mrdoob/three.js#10219]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

Hi 

Can you please tell me the method to keep an object static with respect to the another object. Like in this [example](http://gamingjs.com/ice/#) mars Label is static with planet mars.

[explanation](https://japhr.blogspot.in/2013/03/fun-with-threejs-camera-orientation.html)

Similarly in this [code](https://jsfiddle.net/k1mcLro6/2/) would like to keep the cube static as a label with respect to the cone. So that cube is always static at even I keep rotating the cone.

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by makc** [comment]
anotherObject.add(object) 😎

but, in your example mars label is not 3d thing, it's just an overlayed div, and its placement is controlled by http://gamingjs.com/Label.js script - you can see they do it by hacking into WebGLRenderer (you could check http://jsdo.it/makc/hw0L for less intrusive method).

**Comment by makc** [comment]
> in this code would like to keep the cube static as a label with respect to the cone.

but, cube is perfectly static with respect to the cone there?
