### ISSUE TITLE
pointer lock demo does not have to request full screen in firefox

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#10217]
[here](https://github.com/mrdoob/three.js/blob/master/examples/misc_controls_pointerlock.html#L141) it tests for "firefox" and forces full screen. however, as you can see [here](http://media.tojicode.com/q3bsp/), it works in normal mode as well (corresponding code is [here](https://github.com/toji/webgl-quake3/blob/af84e2247055a3d7c94e39e5e51e26ef358596c8/js/main.js#L500-L502)).

**Comment by mrdumb** [comment]
http://necromanthus.com/Test/html5/testA_disco.html 
Press "F" for full screen.

**Comment by makc** [comment]
that rifle fires blanks.

**Comment by mrdumb** [comment]
> that rifle fires blanks.

Do you like to kill girls and dogs?

**Comment by Mugen87** [comment]
> here it tests for "firefox" and forces full screen. however, as you can see here, it works in normal mode as well (corresponding code is here).

You're correct. It's not necessary to be in fullscreen mode to request a pointer lock. The API changed over time in Firefox.

**Comment by makc** [comment]
> Do you like to kill girls and dogs?

what if they are Irma Grese kind of girs and dogs

**Comment by mrdoob** [comment]
Fixed. Thanks!
