### ISSUE TITLE
how to change axis position?

### ISSUE THREAD

**Issue by shizhidi** [mrdoob/three.js#10215]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Three.js version

- [ ] Dev
- [x ] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

![qq 20161124151018](https://cloud.githubusercontent.com/assets/7605007/20589594/7006e4d4-b258-11e6-9b89-5f58f12e472f.png)

**Comment by mrdumb** [comment]
You don't want to change the axis position.
You want to change the model PIVOT position.

		model.geometry.translate( shiftX, shiftY, shiftZ );

p.s.
This is NOT a help site.
Do not ask help questions here.
