### ISSUE TITLE
Mesh.position.set() Bug?

### ISSUE THREAD

**Issue by GryffindorZz** [mrdoob/three.js#10214]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
When I used PlyLoader to load lucy model:"./three/examples/models/ply/binary/Lucy100k.ply", and used Mesh.position.set(0,0.0), then I found it's actually not in the center of world. Because I zoom in or zoom out the orbit control camera, the model is not in the center of screen and when I roate the model, the model center is not in the center of screen.(but it should in center, right?) I also tried other models, same did. the camera.lookAt(0,0,0) and cameraControls.target.set( 0, 0, 0 ) I have set. But when I used the BoxGeometry or ohter simple geometry, it restore normal.

So I think Mesh.position.set() may have bugs(or actually computing of the center of boundingbox is not right?), when I load a model, first I will computer the center of BoundBox, and translate the model to the origin of world coordinates, right?

bugs like this picture:
![lucy](https://cloud.githubusercontent.com/assets/18241063/20588417/e26a1aea-b24f-11e6-86be-75a5dfd9323e.PNG)

main code:
   function init() {

        container = document.createElement('div');
        document.body.appendChild(container);

        scene = new THREE.Scene();

        camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 1, 10000);
        camera.lookAt(0,0,0);
        camera.position.z = 1000;

        var loader = new THREE.PLYLoader();
        loader.load( './three/examples/models/ply/binary/Lucy100k.ply', function ( geometry ) {
            geometry.computeVertexNormals();
            var material = new THREE.MeshStandardMaterial( { color: 0xffff00, shading: THREE.SmoothShading } );
            var mesh = new THREE.Mesh( geometry, material );
            mesh.scale.multiplyScalar(0.5);
            mesh.rotation.x = - Math.PI / 2;
            mesh.position.set(0,0,0);
            scene.add( mesh );
        } );

        var light = new THREE.HemisphereLight(0xffffff, 0x4d74b1,1.0);
        scene.add(light);

        renderer = new THREE.WebGLRenderer();
        renderer.setSize(window.innerWidth, window.innerHeight);
        renderer.setClearColor(0x4d74b1,1.0);
        container.appendChild(renderer.domElement);

        //orbit controls
        cameraControls = new THREE.OrbitControls( camera, renderer.domElement );
        cameraControls.addEventListener( 'change', animate );
        cameraControls.target.set( 0, 0, 0 );
        cameraControls.update();

        window.addEventListener( 'resize', onWindowResize, false );
    }

##### Three.js version

- [x] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
The lucy model has currently some weird transformations. This should be fixed with this PR #9999.

As a workaround, you can call `geometry.center()` in your `onLoad` callback function.

**Comment by GryffindorZz** [comment]
@Mugen87  Very helpful! After adding geometry.center(), it worked. Thanks a lot!

**Comment by Mugen87** [comment]
You're welcome! :blush:

Don't forget to close the issue if your problem is solved. Thanks!
