### ISSUE TITLE
Object3D - matrices do not auto update

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10218]
##### Description of the problem 
With Object3D.matrixAutoUpdate = true (as it is by default)
the docs say that the Object3D.matrix and Object3D.matrixWorld should be updated every frame. 

However this doesn't happen, and Object3D.updateMatrixWorld() needs to be called manually
Check the console output of this [fiddle](http://jsfiddle.net/looeee/cjftx1oL/14/).
Warning: it logs the matrices every frame to see if they update so your console will fill up fast! 

```js
  var x = new THREE.Object3D()
  
  //Set to true
  console.log(x.matrixAutoUpdate)
  
  x.position.set(100, 0, 0);
  console.log(x.position); //position has been updated 
  
  x.scale.set(2, 2, 2);
  console.log(x.scale); //scale has been updated 
  
  x.rotation.set(Math.PI / 2, 0, 0);
  console.log(x.rotation); //rotation has been updated 
  
  console.log('matrix', x.matrix); //identity matrix
  console.log('matrixWorld', x.matrixWorld); //identity matrix
  
  x.updateMatrix();  //calling this updates .matrix
  x.updateMatrixWorld(); //Calling this updated both matrices
```

##### Three.js version

- [x ] Dev
- [x ] r82

**Comment by mrdumb** [comment]
> With Object3D.matrixAutoUpdate = true (as it is by default)
the docs say that the Object3D.matrix and Object3D.matrixWorld should be updated every frame.
> However this doesn't happen, and Object3D.updateMatrixWorld() needs to be called manually 

Don't mix them up.
Bt default, matrixWorldNeedsUpdate is set to false.

**Comment by looeee** [comment]
Hmm, setting matrixWorldNeedsUpdate to true doesn't seem to make the matrices update either - added it to the fiddle [here](http://jsfiddle.net/looeee/cjftx1oL/16/), check the console output.

**Comment by looeee** [comment]
Ah, I found the problem - the object needs to be added to the scene.

    scene.add(x);

did the trick! I'll update the docs.
