### ISSUE TITLE
Raycasting intesectObjects() Android 6 issue

### ISSUE THREAD

**Issue by MCP33** [mrdoob/three.js#10227]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
I'm having an issue with raycasting .intersectObjects(). It seems to be happening on Android 6.*, 5.0 and 7.* are working fine.

I have a 3D dragable / rotating cube with clickable sides; the raycaster is set up to listen for which side is clicked but on Android 6.* the 'clickable area' is being rendered above where it needs to be therefore making it unusable. Is this a known issue with the OpenGL Drivers on that OS as I have seen tickets for other things pertaining to the equations for raycasting.

This is what I have code wise

    var vector = new THREE.Vector3(
                ( event.clientX / window.innerWidth ) * 2 - 1,
              - ( event.clientY / window.innerHeight ) * 2 + 1,
                1 );

            vector.unproject(camera);
            var raycaster = new THREE.Raycaster( camera.position, vector.sub( camera.position ).normalize() );

            // create an array containing all objects in the scene with which the ray intersects
            var intersects = raycaster.intersectObjects( scene.children );
            if (intersects.length>0){
                var index = Math.floor( intersects[0].faceIndex / 2 );
               //Do something
            }

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [ ] IOS

**Comment by WestLangley** [comment]
See if [this stackoverflow answer](http://stackoverflow.com/questions/13542175/three-js-ray-intersect-fails-by-adding-div/13544277#13544277) is helpful.
