### ISSUE TITLE
Cube Camera not supporting reflection textures after r67?

### ISSUE THREAD

**Issue by rkwright** [mrdoob/three.js#10221]
I BELIEVE this is a bug (and/or missing documentation). I did post this to stackoverflow [here](http://stackoverflow.com/questions/40750371/errors-warnings-being-reported-by-three-js-for-non-working-cubecamera-example)  with zero response.  If this issue is deemed out of line, I apologize and please close it.

##### Description of the problem 
I have a very simple CubeCamera/reflection example (lifted largely from Stemkoski's [reflection example](https://stemkoski.github.io/Three.js/Reflection.html)). Code looks like this:

    var sphereGeom =  new THREE.SphereGeometry( 2, 32, 32 ); 
    mirrorSphereCamera = new THREE.CubeCamera( 0.1, 5000, 512 );
    scene.add( mirrorSphereCamera );

    var mirrorSphereMaterial = new THREE.MeshBasicMaterial( { envMap:     mirrorSphereCamera.renderTarget } );    
    mirrorSphere = new THREE.Mesh( sphereGeom, mirrorSphereMaterial );
    mirrorSphere.position.set(0, 2, 0);
    mirrorSphereCamera.position = mirrorSphere.position;
    scene.add(mirrorSphere)
The render code looks like this

    mirrorSphere.visible = false;
    mirrorSphereCamera.updateCubeMap( renderer, scene );
    mirrorSphere.visible = true;
    renderer.render( scene, camera );
Up until r67 it works fine though I get these warnings:

    [.Offscreen-For-WebGL-0x7f80b4013200]RENDER WARNING: there is no texture bound to the unit 0
    [.Offscreen-For-WebGL-0x7f80b4013200]RENDER WARNING: there is no texture bound to the unit 0
    [.Offscreen-For-WebGL-0x7f80b4013200]RENDER WARNING: there is no texture bound to the unit 0
But after r67  I get this error:

    WebGL: INVALID_OPERATION: bindTexture: textures can not be used with multiple targets
 And with the latest build 82, I get these warnings:

    THREE.WebGLPrograms.getTextureEncodingFromMap: don't use render targets as textures. Use their .texture property instead.
    THREE.WebGLRenderer.setTextureCube: don't use cube render targets as textures. Use their .texture property instead.
After r67 the reflection does not work.The sphere appears transparent (clear color). And despite the warning from r82, [the example at threejs.org](https://threejs.org/docs/#Reference/Cameras/CubeCamera) still uses the renderTarget (AFAICT):

I have added a jsFiddle for this [here](https://jsfiddle.net/richardylewright/ejuofnye/14/)

And I did read through all the release notes 67-68 and can't see any relevant mentions (at least to me).
##### Three.js version

- [ ] Dev
- [x ] r82
- [ x] >r67

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows 10
- [x] OSX 10.10
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
None

**Comment by carstenschwede** [comment]
The floor is probably not visible to the ```THREE.CubeCamera``` because it is positioned within the floor. Try moving it to the same position as the Sphere.

**Comment by rkwright** [comment]
Thanks for the feedback, but isn't this code:

     mirrorSphere.position.set(0, 2, 0);
     sphereCamera.position = mirrorSphere.position;
Doing exactly that?  Putting it in the same position as the sphere? And as you say, why would it have worked up until r68?

**Comment by WestLangley** [comment]
>sphereCamera.position = mirrorSphere.position;

This is no longer valid code. See the [stackoverflow post](http://stackoverflow.com/questions/26905929/three-js-2xmeshes-using-same-vector-as-position/26916159#26916159).
