### ISSUE TITLE
CSS3DObject (of CSS3DRenderer) scales 1.5 times bigger consistently on Chrome

### ISSUE THREAD

**Issue by TheNavigateur** [mrdoob/three.js#10226]
##### Description of the problem 

CSS3DObject scales 1.5 times bigger (consistently) on Chrome (Version 54.0.2840.99 m) than on Firefox (50.0).

I have to scale by 2/3 if browser is Chrome to work around this problem.

Example to try on Chrome vs Firefox:

https://threejs.org/examples/#css3d_youtube

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by looeee** [comment]
They look the same to me, using the same version of Chrome and FF on Windows 10

![untitled-1](https://cloud.githubusercontent.com/assets/5307958/20632671/35db91ee-b337-11e6-8373-4fcdfd4be2e3.jpg)

**Comment by TheNavigateur** [comment]
Can you confirm your Chrome version number? I will post screenshots of the
same page on my chrome when I get home in a few hrs, where it's definitely
exactly 1.5 times bigger in both axes. I will also let you know my chrome
zoom settings and let you know the results.

**Comment by looeee** [comment]
FF v50.0
Chrome 54.0.2840.99 m (64-bit)

**Comment by looeee** [comment]
Silly question perhaps, but have you checked your zoom settings in FF and Chrome?

**Comment by TheNavigateur** [comment]
Here are my results, and I am using Windows 10 Home, 64-bit, Version 1607, Build number 14393.447. You can quite clearly see that the zoom settings are 100% in each browser, and that the other content on the page is rendering the same in both browsers:

Chrome (Version 54.0.2840.99 m):

![chromecss3d](https://cloud.githubusercontent.com/assets/387061/20635810/3d6a603e-b35a-11e6-96cb-905a312783dd.png)

Firefox (50.0):

![firefoxcss3d](https://cloud.githubusercontent.com/assets/387061/20635814/4c24ad8c-b35a-11e6-964b-63fae67aa031.png)

I'll try uninstalling some extensions and seeing what happens.

**Comment by TheNavigateur** [comment]
I can confirm that even after uninstalling all extensions and restarting my computer, the behavior discrepancy persists. I can also confirm that ordinary CSS 3D perspective transformations look the same in each browser, so it's just apparently something related to how CSS3DRenderer/Object is producing its output:

![chromeandfirefoxperspective](https://cloud.githubusercontent.com/assets/387061/20636183/3e40dcc6-b360-11e6-84e1-7dd1f90b192f.png)

**Comment by TheNavigateur** [comment]
I can confirm that, after inspecting the elements produced, I can re-produce the bug without three.js and with matrix3d transformation in Chrome itself:

![chromeandfirefoxmatrix3d](https://cloud.githubusercontent.com/assets/387061/20636413/74ebd420-b364-11e6-87ad-7d01b6ed6d50.png)

https://jsfiddle.net/rztuy9g6/6/

**Comment by mrdumb** [comment]
> I can confirm that, after inspecting the elements produced, I can re-produce the bug without three.js and with matrix3d transformation in Chrome itself (on the left, Firefox on the right)

I cannot reproduce it, but this is a Google Chome bug.

**Comment by TheNavigateur** [comment]
Yes, I have filed a bug report for Chrome here: https://bugs.chromium.org/p/chromium/issues/detail?id=668753.

**Comment by jbaicoianu** [comment]
I believe that this is related to devicePixelRatio.  I bet that if you check the value of devicePixelRatio on that browser, it will be 1.5.

I had similar problems when mixing CSS3D objects with a WebGL scene, I think it should be possible to use devicePixelRatio in the calculations that CSS3DRenderer makes, but I wasn't able to get it working 100%.

**Comment by TheNavigateur** [comment]
Yes, my device pixel ratio is 1.5, according to http://mydevice.io/ .

Fortunately, this is [fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=668753) in the upcoming Chrome version 56.

**Comment by jbaicoianu** [comment]
Excellent, I always love it when bugs fix themselves :)
