### ISSUE TITLE
Incurred CPU-side conversion, which is very slow

### ISSUE THREAD

**Issue by zhoushijie163** [mrdoob/three.js#10231]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
Error: WebGL: texImage2D: Incurred CPU-side conversion, which is very slow.  three.js:19017:5
Error: WebGL: texImage2D: Incurred CPU pixel conversion, which is very slow.  three.js:19017:5
Error: WebGL: texImage2D: Chosen format/type incurred an expensive reformat: 0x1907/0x1401  three.js:19017:5

##### Three.js version

- [X] Dev
- [X] r82
- [ ] ...

##### Browser

- [ ] All of them
- [X] Chrome
- [X] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [X] Linux
- [ ] Android
- [ ] IOS
![2016-11-26_10-03-29](https://cloud.githubusercontent.com/assets/18611035/20637331/a4879100-b3bf-11e6-9798-c77b6c0d4461.png)

##### Hardware Requirements (graphics card, VR Device, ...)
GTX1080 graphics card

**Comment by looeee** [comment]
I get the same errors in Firefox 50.0 on Windows 10, but not in Chrome 54.0.2840.99 m (64-bit)

**Comment by Mugen87** [comment]
Duplicate #9109

**Comment by mrdumb** [comment]
> Duplicate #9109

An old issue, but still not fixed ...
