### ISSUE TITLE
Path.toShapes() removed from v81 in threejs

### ISSUE THREAD

**Issue by digiperfect-sandeep-kumar** [mrdoob/three.js#10237]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
Hi,
Path.toShapes() removed from v81 in threejs, can you please advice any alternative or reverse compatibility option.

As a note threejs doc still shows that its there [link](https://threejs.org/docs/?q=path#Reference/Extras.Core/Path).
 

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by looeee** [comment]
@digiperfect-sandeep-kumar I think that is an error in the docs.

The toShapes method is a part of ShapePath, not Path. This should work:

    var shapePath = new THREE.ShapePath();
    shapePath.toShapes();
