### ISSUE TITLE
Error when serializing non-three.js object that contains three.js objects

### ISSUE THREAD

**Issue by JaredHays** [mrdoob/three.js#10236]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

I have a graph structure (created with graphlib: https://github.com/cpettitt/graphlib) containing multiple objects as nodes, each of which contains a THREE.Mesh as a value; each Mesh references a shared TorusGeometry and MeshPhongMaterial.

Attempting to serialize the graph object using JSON.stringify (both with and without using graphlib's serialization functionality first) results in an error similar to this:

`three.js:11083 Uncaught TypeError: Cannot read property '6D3A1274-77BB-4ED2-A74D-B088157E1021' of undefined(…)`

The property string appears to be a geometry UUID being passed to:

`if ( meta.geometries[ this.geometry.uuid ] === undefined ) {...}`

However, meta is undefined, because toJSON is being passed in a meta value of "mesh" rather than the expected empty string (ref. https://github.com/mrdoob/three.js/issues/8428 and the comment on three.js line 11038). JSON.stringify immediately jumps into toJSON, so I cannot figure out where this string is being created/passed. The graph object has the structure described below. The only place where "mesh" is used is as a property name for a THREE.Mesh value, but it's still unclear to me why toJSON would receive the string "mesh" rather than the appropriate meta object.

Attempting to serialize a single Ring object (which contains a THREE.Mesh as a property) results in the same error. Serializing only the Mesh object succeeds with no error, so it appears to only be an issue when the Mesh is held by another object.

`
graph: Object
    edges: Array[1344]
        [0 … 99]
		    0: Object
			    name: "top-left"
				v: "ring-0"
				value: "top-left"
				w: "ring-1"
				__proto__: Object
			...
			[100 … 199]
			[200 … 299]
			[300 … 399]
			[400 … 499]
			[500 … 599]
			[600 … 699]
			[700 … 799]
			[800 … 899]
			[900 … 999]
			[1000 … 1099]
			[1100 … 1199]
			[1200 … 1299]
			[1300 … 1343]
		length: 1344
		__proto__: Array[0]
	nodes: Array[379]
		[0 … 99]
			0: Object
				v: "ring-0"
				value: Ring
					geometryIndex: 0
					isInCamera: (frustum)
					mesh: Mesh
					nodeID: "ring-0"
					nodeIndex: 0
					ringIndex: 0
					updated: false
					__proto__: Object
				__proto__: Object
			...
			[100 … 199]
			[200 … 299]
			[300 … 378]
			length: 379
			__proto__: Array[0]
	options: Object
		compound: false
		directed: true
		multigraph: true
		__proto__: Object
	__proto__: Object
`

##### Three.js version

- [ ] Dev
- [ ] r82
- [x] r81 (checked r82 release notes, did not see any changes that appeared related)

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by JaredHays** [comment]
I'm happy to go ask on SO, but how is failing to serialize three.js objects when they're owned by a parent object _not_ a bug?

**Comment by mrdoob** [comment]
That's a longer conversation. A conversation I'm happy to have when it's not framed as a bug.

**Comment by JaredHays** [comment]
I would love to have that conversation with you somewhere.

In the meantime, I managed to get around the issue by implementing toJSON in the containing object so that it could call toJSON on the mesh with no parameters. I'm not sure if that's the intended solution, but it appears to work.

**Comment by makc** [comment]
@JaredHays 
> it's still unclear to me why toJSON would receive the string "mesh" rather than the appropriate meta object.

because stupid browser passes key name to value.toJSON.

> JSON.stringify immediately jumps into toJSON

that's true, not even replacer has a chance to run before it.

@mrdoob this behavior is (poorly, but) documented [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior):
> If an object being stringified has a property named toJSON whose value is a function, then the toJSON() method customizes JSON stringification behavior: instead of the object being serialized, the value returned by the toJSON() method when called will be serialized.

so people are in their right to rely on it. what @JaredHays asks here is for toJSON to validate its input. simply adding [here](https://github.com/mrdoob/three.js/blob/9b6bc2556d5851a0a12c4ab4ad8e7575d8e00917/src/core/Object3D.js#L587) the code like
```javascript
} else {
    // not root object
    if (typeOf(meta) == 'string') {
        meta = undefined;
    }
}
```
would solve this issue.

**Comment by makc** [comment]
...or maybe it should still be root object in this case? then you change
> var isRootObject = ( meta === undefined || meta === '' );

to
> var isRootObject = ( meta === undefined || typeOf (meta) == 'string' );

**Comment by makc** [comment]
@mrdoob > A conversation I'm happy to have when it's not framed as a bug.

what if it's framed as a PR + test case?

**Comment by mrdoob** [comment]
> what if it's framed as a PR + test case?

Even better!
