### ISSUE TITLE
Change documentation to reflect changes made to THREE.GridHelper in r79.

### ISSUE THREAD

**Issue by carlosanunes** [mrdoob/three.js#10247]
##### Description of the problem 

Documentation does not reflect changes to THREE.GridHelper made in revision 79. 

> GridHelper
> 
> Changed step to divisions. #9193 (@mrdoob)
> 

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
I think this has already been changed in `dev`.

58b5ccee679f89f67074308f3d1d9c12b8da3fb6, b239ead534bddff6a81da9fe416fefc1837b8afa, 9b108b0eb056cdfe52574b31d156a34916c9057a

**Comment by Hectate** [comment]
Yes, as @Mugen87 points out, this is fixed in _dev_ (So it _is_ wrong for r82 but presumably r83 will be fine, whenever that comes out).
Reference to current: https://github.com/mrdoob/three.js/blob/dev/docs/api/extras/helpers/GridHelper.html

**Comment by carlosanunes** [comment]
Confirmed.

Will close
