### ISSUE TITLE
DirectionalLight parameter naming convention.

### ISSUE THREAD

**Issue by chimpxx** [mrdoob/three.js#10249]
Why is it so that THREE.DirectionalLight does not allow me to set direction? instead it allows me to set position which acts as the direction of the directional light? 

IMO DirectionalLight should only have a direction and it should not have a position.

**Comment by tentone** [comment]
We need the DirectionalLight to have a position because of shadow mapping. Its usual for them (even in other frameworks) to have a position ;)
