### ISSUE TITLE
WebGL blacklisted on FireFox on a Mac

### ISSUE THREAD

**Issue by j-christopher** [mrdoob/three.js#10258]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
When using a 3D video viewer (VideoJS-Panorama) on FireFox on a Mac the following error occurs, preventing video playback.

Error: WebGL: Disallowing antialiased backbuffers due to blacklist 

##### Three.js version

- [ ] Dev
- [X] r82
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [X] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [X] OSX

**Comment by mrdoob** [comment]
I think you should report this to Mozilla instead.
