### ISSUE TITLE
example webgl / math / spherical distribution doesn't work

### ISSUE THREAD

**Issue by aardgoose** [mrdoob/three.js#10250]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Three.js version

- [x ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

Example examples/webgl_math_spherical_distribution.html doesn't work because the object
THREE.CosineSphericalDistribution doesn't exist.

Does this need fixing or should it just be removed?

**Comment by Mugen87** [comment]
I think we can delete this file. `THREE .CosineSphericalDistribution` is not the only dependency thats missing...

**Comment by mrdoob** [comment]
@Mugen87 Yep!

**Comment by aardgoose** [comment]
ok #10256 removes it.
