### ISSUE TITLE
Support for glTF 1.1

### ISSUE THREAD

**Issue by pjcozzi** [mrdoob/three.js#10257]
The pull request for the draft glTF 1.1 spec is now open: https://github.com/KhronosGroup/glTF/pull/784

We'd like a few engines and tools to implement it and provide feedback before we submit it for Khronos ratification.  It would be awesome if three.js could be one of them.

There are several changes but they are small and almost always straightforward, see https://github.com/KhronosGroup/glTF/issues/605

CC @tparisi @richtr

**Comment by takahirox** [comment]
simple sample models for glTF 1.1

https://twitter.com/pjcozzi/status/813507833828429824
https://github.com/javagl/gltfTutorialModels/blob/master/README.md

**Comment by cx20** [comment]
I tried the glTF 1.1 sample with some glTF Loader.
https://github.com/cx20/gltf-test#gltf-11-tutorial-models
https://cx20.github.io/gltf-test/

I would like each library to be all green.

**Comment by donmccurdy** [comment]
We're all green for 1.1, excluding a [known animation bug](https://github.com/mrdoob/three.js/issues/10366). This can be closed.

Next up, 2.0!

**Comment by takahirox** [comment]
Agreed with setting our target 2.0.

But just in case, I'm not sure if we're all green for 1.1.
At least I haven't checked yet.
Just `GLTFLoader` can load all glTF 1.1 public sample models.
https://github.com/javagl/gltfTutorialModels/blob/master/README.md

**Comment by donmccurdy** [comment]
Yes; I think supporting [all of the 1.1 sample models](https://github.com/cx20/gltf-test/blob/ce22b9cef483cd0d43b610bcd8fad240bc042a4a/README.md#gltf-11-tutorial-models) is probably good enough to close this issue and open another for 2.0. Certainly "all green" was an overstatement. 😅 But any future 1.1 bugs we can file separately when we discover them.

**Comment by takahirox** [comment]
I see, that sounds good to me!

**Comment by cx20** [comment]
I confirmed that it became all green.
https://github.com/cx20/gltf-test
