### ISSUE TITLE
Transparent surfaces

### ISSUE THREAD

**Issue by occultations** [mrdoob/three.js#10263]
##### Description of the problem 
Viewing a partially transparent surface through another partially transparent surface doesn't seem to work. http://threejs.org/docs/scenes/material-browser.html#MeshLambertMaterial demonstrates the problem. If you open the controls, tick the transparent checkbox, and set opacity to 0.8, then some of the distant surfaces are visible through the nearer surfaces, but some aren't. Unticking the depthTest or the depthWrite checkbox makes the distant surfaces appear, but they are in front of the nearer surfaces instead of behind them.

##### Three.js version

- [ ] Dev
- [ ] r82
- [x] Latest version at https://threejs.org

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox version 50.0
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows XP
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
This is a limitation of WebGL itself.
