### ISSUE TITLE
Add the possibility to the JSON loader to reference custom ShaderMaterials

### ISSUE THREAD

**Issue by jgsacris** [mrdoob/three.js#10261]
##### Description of the problem 
 I think that it would be very helpful if, in addition to the standard material types, specified in the WebGLPrograms function (MeshDepthMaterial, MeshNormalMaterial, etc.), it would be possible to reference a custom ShaderMaterial from within the JSON Object Scene file. 

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
That should work already...
