### ISSUE TITLE
3d racing game with three.js

### ISSUE THREAD

**Issue by Sebnemm** [mrdoob/three.js#10279]
Hi Mrdoob.
I'm senior in computer engineering.My gradution project about 3d game with three.js and webGL.We also designed the game in blender.We want to transfer the 3d design to the web environment using three.js.We imported it into Blender as yo can see.
https://github.com/mrdoob/three.js/tree/master/utils/exporters/blender#importer
But 
![15369730_1296322940419990_187432992_o](https://cloud.githubusercontent.com/assets/12737088/20865522/a88fe9aa-ba1d-11e6-9de4-d5cbd96af93a.png) We got the error in the image.Why do we get the error?How can we fix it?

**Comment by Mugen87** [comment]
This warning means that you can't import 3D objects based on `three.js` JSON format into Blender.  The plugin only supports an export operation right now.

**Comment by Sebnemm** [comment]
thank you Mugen87

**Comment by Mugen87** [comment]
@Sebnemm Can you please close the issue if your problem is solved?

**Comment by Sebnemm** [comment]
my problem is not solved...ı m waiting to reply still

2016-12-04 17:01 GMT+03:00 Michael Herzog <notifications@github.com>:
