### ISSUE TITLE
Blender export bones rotation pivot

### ISSUE THREAD

**Issue by hesselbom** [mrdoob/three.js#10273]
##### Description of the problem 

In Blender I've created a mesh, attached armature and a simple rotation animation on one of the bones, called "head" (connected to another, named "stomach").

When exporting to Three.js I get two issues. The first is that for position yz are flipped, similar for rotation. This was easy to solve by hacking the exported animationKeys to flip them to work with threejs. How I did that was inside the `parseAnimation` function, under the comment `// ...assume skeletal animation` I added this:

```
for (let i = 0; i < animationKeys.length; i++) {
  let keys = animationKeys[i]
  let diff = [keys.pos[0] - bones[h].pos[0], keys.pos[1] - bones[h].pos[1], keys.pos[2] - bones[h].pos[2]]
  keys.pos = bones[h].pos.slice()
  keys.pos[0] += diff[0]
  keys.pos[1] += -diff[2]
  keys.pos[2] += diff[1]

  diff = [keys.rot[0] - bones[h].rotq[0], keys.rot[1] - bones[h].rotq[1], keys.rot[2] - bones[h].rotq[2], keys.rot[3] - bones[h].rotq[3]]
  keys.rot = bones[h].rotq.slice()
  keys.rot[0] += diff[0]
  keys.rot[1] += -diff[2]
  keys.rot[2] += diff[1]
  keys.rot[3] += diff[3]
}
```

I suppose that is mostly a hack to get it to work for me, it should really be in the exporter python script, I'll look into that later. That was just the context, the second issue is what this post is about.

When running the animation the pivot point for the "head" bone's rotation looks to be at 0,0,0 while in Blender it's relative to it's position (parent?). The result is the following:

<img width="1108" alt="blender1" src="https://cloud.githubusercontent.com/assets/628641/20834647/bdc851aa-b896-11e6-98b8-f9d1b437e71d.png">
<img width="1111" alt="blender2" src="https://cloud.githubusercontent.com/assets/628641/20834648/bdc8ab00-b896-11e6-92f3-0259a26cf9a1.png">
<img width="387" alt="real1" src="https://cloud.githubusercontent.com/assets/628641/20834650/bdc9303e-b896-11e6-8de6-7ff77f4cfffe.png">
<img width="557" alt="real2" src="https://cloud.githubusercontent.com/assets/628641/20834649/bdc92472-b896-11e6-8e4f-065b105d87a5.png">

I tried to "hack" in a way to set pivot point myself, just to see if I could get it to work, but I couldn't find how.

The export settings I use are the following (although I've tried pretty much every variation of settings I could think of):
![exportsettings](https://cloud.githubusercontent.com/assets/628641/20834765/3cd86084-b897-11e6-94b1-76417e2420c4.png)

This is an issue but I'm not 100% sure how it's supposed to work (regarding pivot points for bones).

##### Three.js version

0.82.1 (latest from npm at time of writing)

**Comment by survivol** [comment]
skeletal sounds cool but the blender snap shot looks like a shit bird.

**Comment by arturitu** [comment]
@hesselbom 

About the yz are flipped perhaps you need to reset all of these data before export your model >
![image](https://cloud.githubusercontent.com/assets/5744112/20856959/5df2bfda-b91e-11e6-9ae9-40aa9b9c5b96.png)

And about pivot point, I use this settings to export timeline based animation (where Morph animation isn't selected, is selected 'Keyframe animation' and on 'Skeletal animation' is selected 'Pose' not 'Rest'>
![image](https://cloud.githubusercontent.com/assets/5744112/20856919/5eb9cd1a-b91d-11e6-91ee-678d97f45b97.png)

Anyway, this is a link with a tutorial step by step to export a bone animated model with all the source code and blender files if you want to compare >[http://unboring.net/workflows/animation.html](http://unboring.net/workflows/animation.html)

I hope with this you don't have any problem.

**Comment by hesselbom** [comment]
Interesting! Looks like both animations and flipped values work well when just exporting the model and **not** the scene.

That's good enough for me. I would still consider it a bug that it gets wrong when exporting scene/hierarchy but for my purposes I can get it to work like this.

Thanks!

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
