### ISSUE TITLE
Linewidth on NWjs/MacOS

### ISSUE THREAD

**Issue by ThAlmighty** [mrdoob/three.js#10278]
##### Description of the problem 
Linewidth does work in a Chrome on MacOS, however when packing as a nw.js application this feature seems broken. I tried the `-use-gl=dekstop` switch to no effect (was not expecting that to work anyway)

##### Three.js version

- [ ] Dev
- [x] r82

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] MacOS
- [ ] Linux

##### Hardware Requirements (graphics card, VR Device, ...)
Standard Macbook Pro 13" (2016)

**Comment by tentone** [comment]
This is a known WebGL when running on most browsers in Windows (Angle problem), this doesn't seems related to three.js

**Comment by tildebyte** [comment]
Is this also an issue on OSX?

**Comment by ThAlmighty** [comment]
I know its a Windows / Angle problem, but I stated very clearly that for some reason it is also happening on MacOS when building a nw.js application (in browser everything runs fine). I don't know why this issue is so easily regarded and dismissed or am I missing something here?

**Comment by tentone** [comment]
If it runs well inside a normal browser probably its not threejs fault, open an issue at nwjs repo, (my nunuStudio projet runs on top of nwjs as well and i have noticed that before on osx)

**Comment by ThAlmighty** [comment]
@tentone thank you for clarifying

**Comment by tildebyte** [comment]
@ThAlmighty I wasn't trying to dismiss, I simply wasn't sure where you were seeing the problem; I'd not heard of it as an issue on OSX before.

**Comment by ThAlmighty** [comment]
@tildebyte On OSX this isn't an issue in-browser, but for some reason when you pack you app as a nw.js app the linwidth will always become 1 (like with Windows/Angle).

**Comment by tildebyte** [comment]
@ThAlmighty Whoa, weird one.
@ThAlmighty, @tentone If one of you opens an issue, it'd probably be a good idea to cross-link here.

**Comment by leniel** [comment]
I'm just experiencing this o Mac OS Sierra 10.12.2 and Chrome 55.0.2883.95. In development having a line width greater than 1 does nothing.

**Comment by mrdoob** [comment]
Seems to be a regression in Chrome 55... #10357
