### ISSUE TITLE
Bumpmaps not working on Edge Mobile

### ISSUE THREAD

**Issue by goforcode-com** [mrdoob/three.js#10275]
Most of your examples are rendered properly in Microsoft Edge, but this might be a bigger bug in Edge Mobile. Scene containing bump map materials are not rendered at all. Tested in r82 on Edge Mobile 38.14393.448 with the materials / bumpmap examples.

**Comment by mrdoob** [comment]
I think you should report this to Microsoft Edge instead.

**Comment by goforcode-com** [comment]
Edge Mobile does support bump mapping. Tested in current version.

**Comment by mrdoob** [comment]
Can you share screenshots and a code samples that work and don't work?

**Comment by goforcode-com** [comment]
1. http://felixpalmer.github.io/webgl-tombstone/
If you switch via "Toggle vertices" the left image disappears on Edge mobile

2. http://math.hws.edu/graphicsbook/source/webgl/bumpmap.html
Does the job on mobile.

3. A minimal three js example could be:
var bump = [TextureLoader] 
var geometry = new THREE.BoxGeometry( 1, 1, 1 );
var material = new THREE.MeshPhongMaterial( { color: 0x00ff00, bumpMap: bump } );
var cube = new THREE.Mesh( geometry, material );
scene.add( cube );
This works fine in Edge Desktop but not in Edge Mobile.

Hope this help. Thank you for your work!

**Comment by mrdoob** [comment]
> 1. http://felixpalmer.github.io/webgl-tombstone/
If you switch via "Toggle vertices" the left image disappears on Edge mobile

That project uses r62 which is 3 years old version of the library.

Any chance you can provide a jsfiddle using the latest version?

**Comment by goforcode-com** [comment]
https://jsfiddle.net/p93v38py/2/

Black screen on Edge Mobile.

**Comment by mrdoob** [comment]
Are you able to see console errors somehow? I don't have one of those phones.

**Comment by goforcode-com** [comment]
Hope to find more information. The jsfiddle sample works on Edge's integrated emulator for Edge Mobile.

**Comment by goforcode-com** [comment]
https://jsfiddle.net/p93v38py/3 : Console object -> div box

Edge desktop output:
THREE.ImageUtils.loadTexture has been deprecated. Use THREE.TextureLoader() instead.
THREE.WebGLRenderer82
THREE.WebGLRenderer: OES_texture_half_float extension not supported.
THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.
THREE.WebGLRenderer: image is not power of two (602x600). Resized to 512x512{}

Edge mobile:
THREE.ImageUtils.loadTexture has been deprecated. Use THREE.TextureLoader() instead.
THREE.WebGLRenderer82
THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.
THREE.WebGLRenderer: OES_texture_float extension not supported.
THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
THREE.WebGLRenderer: OES_standard_derivatives extension not supported.
THREE.WebGLRenderer: ANGLE_instanced_arrays extension not supported.
THREE.WebGLShader: Shader couldn't compile.
THREE.WebGLShader: gl.getShaderInfoLog()fragment
THREE.WebGLProgram: shader error: 0

**Comment by mrdoob** [comment]
Seems like that device doesn't support `OES_standard_derivatives` which three.js bump mapping relies on.

**Comment by goforcode-com** [comment]
Thank you for your help. To make it a bit more complete, tests were done using a Lumia 930.
