### ISSUE TITLE
Error when merging geometries and using MeshFaceMaterial

### ISSUE THREAD

**Issue by arpo** [mrdoob/three.js#10271]
I'm trying to merge geometries and keeping it's materials. My code goes here
http://codepen.io/arpo/pen/aBEPGL?editors=0010

This gives me the error:
three.js:20822 Uncaught TypeError: Cannot read property 'visible' of undefined

It's on line 20821

	if ( groupMaterial.visible === true ) {

		pushRenderItem( object, geometry, groupMaterial, _vector3.z, group );

	}

If I change this to this it works:

	if ( groupMaterial && groupMaterial.visible === true ) {

		pushRenderItem( object, geometry, groupMaterial, _vector3.z, group );

	}

##### Three.js version

- [ ] Dev
- [x ] r82
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ x] Mac
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by spirulence** [comment]
I can't comment on the intended behavior, but you can fix this issue by manually assigning a zero `materialIndex` for each face.

```javascript
var pine_geometry_1 = new THREE.CylinderGeometry(25, 25, 50, 6);
pine_geometry_1.faces.forEach(function(face) {face.materialIndex = 0});
```
