### ISSUE TITLE
Add callbacks for JSONLoader.parse

### ISSUE THREAD

**Issue by zillemarco** [mrdoob/three.js#10286]
I'm working on a project where I need to use JSONLoader.parse since the service I'm interfacing to sends me a JSON that contains the objects of the scene as well as other informations that ThreeJS doesn't need.

The problem is that since I'm not running an animation loop to update the scene (through *requestAnimationFrame*) the objects that are added to the scene that have a texture connected Always result black (until I force a redraw).

What I'd like is to add an additional parameter to the JSONLoader.parse method in order to add a callback for when a texture has been loaded. This obviously means that Loader.initMaterials has to be changed as well.

I'm planning to make the change by myself and then pull a request as soon as I have it working.

**Comment by Mugen87** [comment]
`JSONLoader` has been removed from core. Please use `BufferGeometry` instead.
