### ISSUE TITLE
Add the possibility of loading textures with ShaderMaterials

### ISSUE THREAD

**Issue by jgsacris** [mrdoob/three.js#10288]
##### Description of the problem 
I have a custom ShaderMaterial that requires a texture map and currently this doesn't seem to be supported. I would need the following code added to the MaterialLoader.js inside the parse function:
```js              
// for ShaderMaterials
if(material.uniforms !== undefined){ 

	for ( var u in material.uniforms ){

		if ( u === "textureMap" && material.uniforms[u].value ){

			material.uniforms[u].value = getTexture( material.uniforms[u].value );

		}

	}
}
```
I this this could be very useful and offer a lot of possibilities with custom shaders

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
This example uses a `ShaderMaterial` with textures and seems to work fine:
https://threejs.org/examples/#webgl_terrain_dynamic

**Comment by jgsacris** [comment]
Sorry, I think I didn't explain myself correctly. I am aware that you can load textures into the ShaderMaterial which is incredible useful. That is why I am talking about getting the **JSONLoader** to be able to parse an object that uses a ShaderMaterial with a texture. 
That is: you would be able to store an object using the JSON Object Scene format 4 and inside specify an image using base64, then a texture that points to that image and finally reference that texture from a property, called for example, textureMap inside the uniforms property in your ShaderMaterial. 
As far as I can tell the MaterialLoader, when parsing the json object just sets the uniforms property as is:
`if ( json.uniforms !== undefined ) material.uniforms = json.uniforms;` 

The relevant part of the JSON object is something like this:

```
{
  "images":[
    {
        "name":"matcap1.png",
        "url":"data:image/png;base64,iVBORw0KGgoAAAA...",
        "uuid":"777FBD78-6BFE-4AD7-934D-DA0EB2500777"
      }
  ],
  "textures":[
    {
        "name":"MatcapTexture",
        "magFilter":1006,
        "image":"777FBD78-6BFE-4AD7-934D-DA0EB2500777",
        "repeat":[1,1],
        "minFilter":1008,
        "mapping":300,
        "anisotropy":1,
        "uuid":"77788D24-4EB1-4BE7-9073-A8F35E6FE777",
        "wrap":[1000,1000]
    }
  ],
  "materials":[
    {
        "name":"mat_lacquer",
        "uuid":"87AACFC7-902F-4664-A3E7-CBF12B270FD1",
        "type":"ShaderMaterial","side":2,"depthFunc":3,"depthTest":true,
        "depthWrite":true,"skinning":false,"morphTargets":false,
		    "uniforms":{
      		          "textureMap":{"type":"t","value": "77788D24-4EB1-4BE7-9073-A8F35E6FE777" },
       		          "normalScale":{"type":"f","value":0},
      		          "texScale":{"type":"f","value":10},
      		          "useSSS":{"type":"f","value":0},
       		          "useScreen":{"type":"f","value":0}
 		    },
        "vertexShader":"\n\n\tvarying vec3 vNormal;\n    varying vec4 vPosition;\n ..",
        "fragmentShader":"\n\t\n\t \n\tvarying vec3 vReflect;"
      }
  ],
  ...
}
```

The code above allows to add this functionality and we think it would be great if it could be part of the core. It is similar to how other attributes with maps like the map, alphaMap, bumpMap, etc., work right now, just inside the "uniforms" property.

**Comment by mrdoob** [comment]
Ah, I see... Yeah, `ObjectLoader`/`MaterialLoader` may not be able to handle that yet...

**Comment by SimonDanisch** [comment]
Is this still true? So no custom shader + custom textures via the json interface possible?

**Comment by mrdoob** [comment]
@SimonDanisch I don't know. Doesn't work for you?

**Comment by SimonDanisch** [comment]
Well, I have an example that works with `MeshLambertMaterial` and the texture comes out fine. It get's lowered to JSON like this:
```Julia
function lower(material::GenericMaterial)
    data = Dict{String, Any}(
        "uuid" => string(uuid1()),
        "type" => "MeshBasicMaterial",
         ... # blablabla
        "vertexColors" => material.vertexColors,
    )
    if material.map !== nothing
        data["map"] = lower(material.map)
    end
    data
end
```
https://github.com/rdeits/MeshCat.jl/blob/master/src/lowering.jl#L173

I adapted this for a custom shader material with fragment + vertex shader like this:
```Julia
function lower(material::CustomMaterial)
    data = Dict{String, Any}(
        "uuid" => string(uuid1()),
        "type" => "ShaderMaterial",
        ... # other fields
        "fragmentShader" => material.fragmentShader,
        "vertexShader" => material.vertexShader,
        "defines" => Dict("USE_MAP" => "")
    )
    if material.map !== nothing
        # 1)
# this one seems to make me refer to the sky map (or that's just the last bound texture?)
        data["map"] = lower(material.map)
        # other variants i tried (all turned out black/uninitialized memory):
        # 2)
        data["uniforms"] = Dict(
            "map" => Dict(
                "value" => lower(material.map)
            ),
        )

        # 3)
        data["uniforms"] = Dict(
            "map" => lower(material.map)
        )

        # 4)
        data["uniforms"] = Dict(
            "map" => Dict(
               "type" => "t",
                "value" => lower(material.map)
            ),
        )
    end
    data
end
```

Other uniforms come through fine, and the textures also appear in the javascript object - but they actually don't seem to be fully loaded compared to the `MeshBasicMaterial`... The `MeshBasicMaterial` comes through with many more fields - and after investigating the JSON Material loader code, i can't really find any code that actually materializes textures from uniforms or a custom material.
