### ISSUE TITLE
Error using Uint8Array index in WebGLBufferGeometry

### ISSUE THREAD

**Issue by Coburn37** [mrdoob/three.js#10297]
I am getting a `GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer` when my `BufferGeometry`s `index` attribute is a `Uint8Array`. It does however work with `Uint16Array`. 

I created [this jsfiddle](https://jsfiddle.net/1avv71q0/21/) which demonstrates the problem. Go down to the line noted and change the type from `Uint16Array` to `Uint8Array` to see the issue.

#8358 seems similar but was resolved.

The offending code looks to be [these lines in WebGLIndexedBufferRenderer](https://github.com/mrdoob/three.js/blob/6c7f000734f8579da37fb39e5c2e9e5e2dfb14f8/src/renderers/webgl/WebGLIndexedBufferRenderer.js#L19-L29) such that when it encounters `Uint8Array` it does not set the size to 1 but 2 instead. It seems as though THREE.js just doesn't support it. Is it intentional or is there some other reason?

Tested 
* r82 and r83dev
* Chrome and Firefox
* Windows
* Intel Integrated Graphics

**Comment by Coburn37** [comment]
Yeah, seems the only problem was that one conditional. Here's the [fixed JSFiddle](https://jsfiddle.net/1avv71q0/24/).

Pull request: #10300

**Comment by WestLangley** [comment]
Sweet.

I do not think the docs make it clear what `BufferGeometry.index` is, or what values it takes.

@looeee Would you be willing to have a look?

**Comment by looeee** [comment]
@WestLangley sure, it'll be about a week before I have time but I'll make a note of it :)

**Comment by WestLangley** [comment]
Bug fixed by #10300.
