### ISSUE TITLE
Common "constant" materials should use emission channel, not diffuse

### ISSUE THREAD

**Issue by stevenvergenz** [mrdoob/three.js#10299]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem

According to the [COLLADA](https://www.khronos.org/files/collada_spec_1_4.pdf) and [glTF](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_common#constant) specs, "constant" materials, i.e. MeshBasicMaterials, should use the "emission" field to describe the color/texture of the material. Instead, the respective Three.js loaders use the "diffuse" field to determine the `color`/`map` properties of the material. I request that these loaders be changed over to use the emission field, but for compatibility, continue to use diffuse as a fallback if emission is undefined.

##### Three.js version

- [x] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdumb** [comment]
> According to the COLLADA and glTF specs, "constant" materials, i.e. MeshBasicMaterials,
> should use the "emission" field to describe the color/texture of the material.

I'm not so sure if they're entitled to define "standards".
In any case, most of the materials are not "emissive" at all.
That doesn't mean they're black.

> Three.js loaders use the "diffuse" field to determine the color/map properties of the material.

It looks ok to me.

**Comment by donmccurdy** [comment]
@stevenvergenz Can you share a model that exhibits this problem? To me it looks like [THREE.GLTFLoader is able to accept emission fields](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js#L1087-L1091) as you're asking. Perhaps an older version of the loader had this wrong.

**Comment by stevenvergenz** [comment]
It can take emission fields, but not emission textures. The link in OP says that the only fields CONSTANT materials are supposed to allow are `ambient`, `emission`, and `transparency`, and the loader doesn't parse emission textures.

[visor_cap.zip](https://github.com/mrdoob/three.js/files/638019/visor_cap.zip)
