### ISSUE TITLE
Envmap intensity, uniform mispelling

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#10298]
the uniform envMapIntensity is unusable in shader because it is mispelled here :

https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/envmap_pars_fragment.glsl#L3

uniform float envMapIntenstiy;  => uniform float envMapIntensity

(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
Oops. This was mentioned [previously](https://github.com/mrdoob/three.js/commit/3f679f7878f639f041b131fb1a795d2c79dd8d2b#commitcomment-18581399).

I do not think the misspelled variable is used, so `material.envMapIntensity` should work properly.

**Comment by mrdoob** [comment]
Fixed!

**Comment by WestLangley** [comment]
Thank you, @mrdoob.
