### ISSUE TITLE
Error upon selecting Scene on empty Editor

### ISSUE THREAD

**Issue by user1713952** [mrdoob/three.js#10305]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

1. Open the THREE.js Editor 
2. Click: File > New
3. On the right hand side under the 'SCENE' tab, select the 'Scene' from the list of children
4. Click on the center of the set of axes. 

This triggers a "paused in debugger" and the following error message appears in the console in Chrome:
`TransformControls.js:889 Uncaught TypeError: Cannot read property 'matrixWorld' of null
    at HTMLDivElement.onPointerDown (TransformControls.js:889)
onPointerDown @ TransformControls.js:889`

In Firefox:
`TypeError: scope.object.parent is null
onPointerDown()`

##### Three.js version

- [ ] Dev
- [x] r82
- [x] r81

##### Browser

- [ ] All of them
- [x] Chrome v55.0.2883.75 beta (64-bit)
- [x] Firefox 47.0.1
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Geforce GTX 750Ti

**Comment by Mugen87** [comment]
I can confirm this error. Does it actually make sense that users can select and transform the scene object in the editor?

**Comment by mrdoob** [comment]
Fixed. Thanks!
