### ISSUE TITLE
Support Nvidia MDL in three.js

### ISSUE THREAD

**Issue by pascalbayer** [mrdoob/three.js#10309]
Is there any plan to support Nvidia MDL (http://www.nvidia.com/object/material-definition-language.html) within three.js in the near future?

This would be great to share a common material definition language for all different kind of output formats.

**Comment by bhouston** [comment]
I looked at this.  You need to use a node-based material definition in order to do this properly.  I think it is doable but it is not a small project.

**Comment by timknip** [comment]
This might be a good starter https://github.com/nvpro-pipeline/pipeline/tree/master/media/dpfx/mdl

**Comment by donmccurdy** [comment]
Related:

- #24707 

I think a similar approach would let us support MDL, if someone is looking for that support and would like to work on it.

**Comment by mrdoob** [comment]
For now we're focusing on MaterialX, but if someone wants to contribute a `MDLLoader` we would be open to it 👍
