### ISSUE TITLE
Support adding names to textures and renderTargets

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#10301]
##### Description of the problem 

In my fork of ThreeJS I added optional names to textures and renderTargets.  This was a god send when debugging because it would tell me the name of the texture or the name of the render target when there was an error.  Right now ThreeJS just says that a render target is bad or has a settings issue but it just has a uuid.  It is incredibly hard to figure out where these render targets or textures came from if you have a lot flying around.

I would like to add optional names and the correct propagation of names to ThreeJS to aid in debuging and tracing issues related to textures and render targets.

It will add a dozen or so lines to ThreeJS.  But it will save many many hours of debugging time for many users.

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by mrdoob** [comment]
Sounds good to me! 👍
