### ISSUE TITLE
THREE.AudioListener control audio as a group

### ISSUE THREAD

**Issue by Bigmacbook** [mrdoob/three.js#10321]
##### Description of the problem 
In THREE.Audio there are a bunch of audio controls one of them being setVolume, but it is very inefficient if you want to control the audio for a group of sound files using the same THREE.AudioListener.

##### Solution
I proposing adding the same controls to the THREE.AudioListener so you can control all the audio of a single listener at once.

Example Use Case: User changing volume of audio groups in settings with slider.

##### Three.js version

Using Version 82r

##### Browser

Using Chrome

##### OS

Using Windows

**Comment by mrdoob** [comment]
Maybe `THREE.AudioGroup`? 😊
