### ISSUE TITLE
THREE.js forum

### ISSUE THREAD

**Issue by lekxi** [mrdoob/three.js#10325]
Some people including me missing a forum for general discussion. Someone in the IRC stated mrdoob wouldn't have the time to maintain one. If some could help for moderation it should work i guess.

I've used SMF some time ago, but MyBB seems the most widespread software today, so i've setup one today just for test purposes and get familiar with it. I've also made a theme based on a responsive one, just for a raw layout and contrast.

I've put together a simple structure as a start, doesn't include what is covered by github:
```
THREE.js
	News
	Getting started
		- basic questions, setup issues..
	General Discussion
	Feedback and discussion
	
Development
	Examples & Tutorials
		- demos, examples and tutorials
	Coding questions
		- asking for help
	Concept & ideas
		- Ideas, brainstorming and discuss solutions.
	WebGL
		- bare API related
	Shader programming
		- GLSL related
	Tools
		- software for assets etc.
	Libraries and extensions
	
Community
	Projects
		- announcement, collaboration, team up...
	Spotlight
		- showcase what you've done with THREE.js
	Offtopic
```

Here's the prototyped simple theme
![bright](https://cloud.githubusercontent.com/assets/19984823/21065887/f46d196c-be62-11e6-9a2b-9ccf1f009ab3.png)

But only if it get's @mrdoob approved. I would also want suggestions from you, about structure, design and moderation. I also thought about a categorized depot for libraries, codes and assets, similar to a "asset store".

**Comment by satori99** [comment]
I think this is great idea. Somewhere to discuss broader 3D graphics techniques, relevant to three.js specifically, would be very neat

**Comment by Hectate** [comment]
I'll note that the subreddit for three.js seems mildly active and I wonder how active a forum would be. In my experience while it's a nice idea to have all the organization in a forum (as opposed to reddit's flat, timeline/rank structure) you need to have content to fill in those spaces.

**Comment by mrdoob** [comment]
For context: https://www.reddit.com/r/threejs/
Hmm... maybe I should add a link to the subreddit on http://threejs.org/?

**Comment by looeee** [comment]
@Hectate just as a counterpoint I'm in Indonesia and Reddit is blocked here. Not sure how many countries block it, but it may not be accessible to everyone. 

Aside from that, when I do access it using nefarious means it seems pretty dead really, not to mention that the flat structure of a subreddit, while great in it's own way, is not really a substitute for a categorised discussion forum. 

It's a fair point though  that a dead forum is a not that useful, but the only way to see if it gets used is to create it! 

If nothing else it would serve as a place to send people asking for help via raising issues here, aside from Stackoverflow which doesn't suit every question.

**Comment by Hectate** [comment]
@looeee Sorry; my short message may have come across as being negative toward the idea of a forum, which was not the intent. It was more about the over-structuring of a forum that is just getting started. My concern of a dead forum is simply that it gives a poor impression to potential users (and thus, growing the community). The best mitigation toward that would be to not overdo the number of sections initially; more can be added as they are needed later. I would say a simple 3-4 areas would be all that's required. One for Official News, one for Help/Tutorials, one for Projects, and a simple Everything Else/Off-topic.

Regarding reddit; being "mildly active" just meant that while it's not completely dead there's not a lot of daily activity right now. My own opinion of reddit is that it might be a useful community site for sharing projects, but the flat structure is definitely non-ideal for more organization or storage of things like tutorials, etc for future reference. Reddit tends to direct focus to "what's new and popular" for the subreddits. Additionally, none of that addresses the ramifications of hosting your community on an entirely third-party site either. Caution is advised when doing so because you are at the mercy of their longevity and agreeableness to your purposes. We've all been around long enough to see places come and go on the Internet...

**Comment by looeee** [comment]
@hectate great! And yes, I do agree that a few less categories is probably a good idea, at least at first.

@lekxi what do you think of these? 

THREE.js
- General Discussion
- Showcase
- Offtopic
	
Development
- Getting started (basic questions, setup issues)
- More advanced questions
- Importing and exporting assets
- Examples & Tutorials
- WebGL
    - WebGL API
    - GLSL language
- Tools (software for assets creation etc)
- Libraries and plugins

**Comment by lekxi** [comment]
@Hectate i prefer to avoid reddit, it looks a bit messy to me to be honest. For me a forum feels better. You're right, it'll be empty for a while, but it needs to start somewhere i guess. It shouldn't prevent people from asking and discussing.
@looeee looks good, i just thought that community category would make sense for:

- Offtopic - not tied to 3js or dev specifically
- Projects - introducing stuff to team up
- Showcase - well that fits both

@mrdoob My concern about a more extensive software is to not limit it in the first place, that it provides an active community, both comes together mostly and it would be easier to use supported out-of-the-box modules, if there's a need anytime. Another good experience i've made besides SMF is Drupal. It has a strong community, different forum modules and would therefore provide enough space for extension (had a forum and that kind of depot before), but it's more demanding to host.  But tell me if you have something other on mind, just suggestions i used before.

I could also simply open the forum so far when categories and stuff is fine tuned, if there's need for more we could also add/write it separately, using the mybb accounts.

**Comment by Formatter** [comment]
Would be interested to work on the forum, let me know if any help is needed

**Comment by lekxi** [comment]
@Formatter we definitely would need moderation. I know most doesn't have much time, but it'll already suffice checking once or each second/third day in a week, whenever there's some time for it. When a few people do this, we've got a working moderation already.

**Comment by looeee** [comment]
@lekxi you can put me down for a bit of moderation too :)

**Comment by looeee** [comment]
@lekxi any further developments on this?

**Comment by lekxi** [comment]
@looeee 
After some more investigations into other available forum and CMS software packages providing forum-modules, i've setup a new environment based on Drupal, as it is active maintained and well designed. Besides all basic features required for the board, it is highly flexible to extend to any needs as it is a popular CMS, not tied to a specific use case.

But it seems another one launched a forum now.

**Comment by sasha240100** [comment]
@looeee @lekxi @mrdoob How about making an open **slack/discord**? We can make those sections as channels and pin important information.

**Comment by Hectate** [comment]
I'm on discord constantly, and slack rarely. I'm up for discord if we want a server. I admin a few myself, in fact.

**Comment by sasha240100** [comment]
@Hectate Same here. Discord doesn't limit messages so having a discord server for three.js would be nice. What do you think if i'll create one?

**Comment by Hectate** [comment]
@sasha240100 sure send me an invite. As I said, I'm online all the time anyway (if I'm at my pc)

**Comment by fraguada** [comment]
We use http://www.discourse.org/ for discourse.mcneel.com.  We've gone from a newsgroup (?-> 2008) to nings (2009 -> 2012) to discourse (2012 -> ?).  I have to say, without a doubt, discourse has been the most agile and useful tool to support our community of Rhino users and developers.  The discourse dev team is great and attentive.  I highly recommend going for discourse.

**Comment by jbjw** [comment]
I'd be interested in a three.js Discord, any news?

**Comment by sasha240100** [comment]
@jbjw For now you can join Whitestormjs server in discord. There are already 300 people and we always discuss Three.js: https://discordapp.com/invite/frNetGE

**Comment by looeee** [comment]
@lekxi  

>But it seems another one launched a forum now. 

I don't think that forum is going to fly due to being hosted on an ad supported platform. I guess it would need to be something that can be added as a part of the threejs.org site at some point. 

@sasha240100 just going over your discourse server now - actually I think that is a really good format for a discussion board. I would vote for creating a three.js discourse server. 

@mrdoob if you like, I can set up a discourse server for three.js?

**Comment by fraguada** [comment]
@looeee [Discord](https://discordapp.com/) != [Discourse](https://www.discourse.org/)

I've used discourse with a large community, and I can highly recommend it.

**Comment by fraguada** [comment]
P.s. discourse provides free hosting for open source projects https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/

**Comment by looeee** [comment]
@fraguada oops! Thanks :)

**Comment by fraguada** [comment]
P.s. i'd fill out the form, but it's probably best that @mrdoob does it, or someone who has more contributor clout than I.  I'd definitely volunteer to moderate/admin.

**Comment by sasha240100** [comment]
@fraguada @loeee @mrdoob we can just reformat my server to three.js/whitestormjs variant cause it already has 300 members that are interested in three.js as well as whitestormjs.

Just to keep existing auditory. Yes, I can add some moderators, feel free to ask me)

**Comment by looeee** [comment]
sasha240100 feel free to do that of course, but I think three.js warrants it's own separate discussion forum.

**Comment by sasha240100** [comment]
@looeee Discord allows to use separate channels. There will be separate discussion with people from both - three.js and whs. Everyone has access to each channel.

You will own your channels, sure. Discord has such opportunity. Just more people will be

**Comment by fraguada** [comment]
@looeee we would need someone with the capability to add a subdomain `discourse` to threejs.org.  Not sure who that is.

**Comment by sasha240100** [comment]
I would like to use an app over web client

**Comment by fraguada** [comment]
@looeee I've filled out the form @_@ to see what would happen fyi.  Lets see where that takes this discussion.

**Comment by lekxi** [comment]
@looeee i could launch it, but i still need more opinions about the software and future plans if any. I've setup a platform with Drupal too, it has active support and gives all control possibly needed without being tied to forum capabilities, by the cost of requiring more hosting power.

The myBB forum could be used anytime, just a few more details in the theme. But no popular forum-specific software provides modules for a "asset store" like section or something like those ideas, just to pick a future proved solution. (besides, most aren't maintained anymore)

The Drupal one would use Drupal 7 with 'advanced forums' and fills all requirements for a forum, plus being easy to extend for an asset depot, github integration etc. And the API is more worth for people to investigate than an decades old forum-tied one. The forum-module port for Drupal 8 is actually wip.

Please tell me your thoughts.

**Comment by fraguada** [comment]
@looeee @mrdoob someone from discourse has written me back and agrees that three.js fits their guidelines for open source projects.  We'd need to use discourse.threejs.org if that is something that the community wants.

**Comment by mrdoob** [comment]
@fraguada sounds good! does it support github login or does it require their own accounts?

**Comment by mrdoob** [comment]
Oh, I see... 

![screen shot 2017-03-13 at 12 36 47](https://cloud.githubusercontent.com/assets/97088/23871968/cc24658e-07e9-11e7-9340-afbd0cad3f20.png)

**Comment by mrdoob** [comment]
Looks good. Where does discourse.threejs.org need to point to?

**Comment by fraguada** [comment]
@mrdoob : 
![screen shot 2017-03-13 at 8 49 54 pm](https://cloud.githubusercontent.com/assets/1014562/23872509/dcee0632-082e-11e7-9e6a-ee874afd9aa3.png)

**Comment by mrdoob** [comment]
Done!

**Comment by fraguada** [comment]
Now to see about some categories and moderators!  Please sign in!

**Comment by mrdoob** [comment]
Wait, what happened to the github login...?

![screen shot 2017-03-13 at 14 25 10](https://cloud.githubusercontent.com/assets/97088/23876062/fa4724d8-07f8-11e7-8cce-8a6914c364e2.png)

**Comment by fraguada** [comment]
Oops, yeah, enabling...

**Comment by fraguada** [comment]
Ok @mrdoob , github logins should be enabled now 😅

**Comment by mrdoob** [comment]
👌👌👌

**Comment by mrdoob** [comment]
This issue can now be closed 😊
http://discourse.threejs.org/

**Comment by sasha240100** [comment]
@mrdoob I'd like to be a moderator :> :3

**Comment by fraguada** [comment]
@sasha240100 https://discourse.threejs.org/t/admins-and-moderators/

**Comment by munrocket** [comment]
We opened new discord server about webgl frameworks, maybe you will find it usefull https://discord.gg/hqvfu34
