### ISSUE TITLE
Discussion: adding curve support to blender exporter.

### ISSUE THREAD

**Issue by Epskampie** [mrdoob/three.js#10323]
I'm thinking about adding curve support to the blender exporter. I think it can be useful for creating camera paths etc. in blender, which can then be used from script. I think the best starting point would be the Blender `Bezier`, as it should map perfectly to threejs' [CubicBezierCurve3](https://threejs.org/docs/index.html?q=bezier#Reference/Extras.Curves/CubicBezierCurve3).

However, I have noticed that in the [JSON Object Scene format 4](https://github.com/mrdoob/three.js/wiki/JSON-Object-Scene-format-4) there is not yet any description for the format for curves.

What JSON format do you think the data should follow? 
Will this feature have any chance of getting merged?

**Comment by mrdoob** [comment]
It may be a little bit specific. In the past I did a sort of curve exporter fro C4D just to be used as camera paths.

**Comment by mrdoob** [comment]
Actually, it could also be exported as animation? https://threejs.org/examples/#webgl_animation_scene

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
