### ISSUE TITLE
EdgesGeometry doesn't work quite right on cylinder

### ISSUE THREAD

**Issue by flowerchaton** [mrdoob/three.js#10333]
##### Description of the problem 
EdgesGeometry works fine on box.
In cylinder case, EdgesGeometry only gets rid of diagonals, vertical lines still remain.
<img width="386" alt="screen shot 2016-12-11 at 17 43 33" src="https://cloud.githubusercontent.com/assets/10793922/21079355/dbe61c68-bfca-11e6-9d9d-5d4ab7901f21.png">
##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari
##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
- [x] maxOS

**Comment by WestLangley** [comment]
What you are seeing is z-fighting between your two materials.

**Comment by Mugen87** [comment]
@flowerchaton Try use a higher `thresholdAngle` value (second parameter) when creating `THREE.EdgesGeometry`. See https://jsfiddle.net/h20hnn3n/1/
