### ISSUE TITLE
Rotate camera with respect to user

### ISSUE THREAD

**Issue by digiperfect-sandeep-kumar** [mrdoob/three.js#10337]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
Hi,

Does threejs provide a control library which helps to rotate the camera with respect to user. 

Explanation : THREE.Matrix4().makeRotationZ(delta*2)  - This function rotates the camera around z axis. Now suppose the camera is already rotated by an angle theta. I would like to rotate around zcos(theta). Could you help me with this.

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Hectate** [comment]
There's several control scripts already part of three.js available in the repo:
https://github.com/mrdoob/three.js/tree/dev/examples/js/controls

I myself use OrbitControls for one of my projects which sounds like what you want to use. Besides including the file as a script, you just need to create a controls object and update it as you render...

```javascript
//orbit controls
controls = new THREE.OrbitControls( camera, renderer.domElement );
//controls.addEventListener( 'change', render ); // add this only if there is no animation loop (requestAnimationFrame)
controls.enableDamping = true;
controls.dampingFactor = 0.25;
controls.enableZoom = true;
//controls.autoRotate = true;

var render = function () {
    requestAnimationFrame( render );
    controls.update();
    renderer.render(scene, camera);
};
```
