### ISSUE TITLE
TypeError: Cannot read property 'array' of undefined

### ISSUE THREAD

**Issue by waitingcheung** [mrdoob/three.js#10339]
##### Description of the problem 

I am getting a TypeError when constructing an instance of Geometry from an instance of BufferGeometry.

```
TypeError: Cannot read property 'array' of undefined
    at Geometry.fromBufferGeometry (/path/three.js:12675:39)
```

Here is a simple test case to reproduce that

```js
var bufferGeometry = new THREE.BufferGeometry();
bufferGeometry.addAttribute('color', new THREE.BufferAttribute(new Float32Array( [0, 0, 0, 0.5, 0.5, 0.5, 1, 1, 1] ), 3 ) );
bufferGeometry.addAttribute('normal', new THREE.BufferAttribute(new Float32Array( [0, 1, 0, 1, 0, 1, 1, 1, 0] ), 3 ) );
bufferGeometry.addAttribute('uv', new THREE.BufferAttribute(new Float32Array( [0, 0, 0, 1, 1, 1] ), 2 ) );
bufferGeometry.addAttribute('uv2', new THREE.BufferAttribute(new Float32Array( [0, 0, 0, 1, 1, 1] ), 2 ) );
var geometry = new THREE.Geometry().fromBufferGeometry(bufferGeometry);
```

It seems that the problem occurs when the attribute 'position' is missing. If we change [line 231](https://github.com/mrdoob/three.js/blob/master/src/core/Geometry.js#L231) of Geometry.js to the following, we can create an instance of Geometry successfully.

```js
var positions = attributes.position !== undefined ? attributes.position.array : [];
```

##### Three.js version

- [x] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
The code expects at least a `position` attribute that contains the vertex data by now. This is in some way the minimum information for a valid geometry. Why don't you just add this line in your code.

```javascript
bufferGeometry.addAttribute( 'position', new THREE.Float32BufferAttribute( [], 3 ) );
```

**Comment by WestLangley** [comment]
@waitingcheung What is your use case for creating a `BufferGeometry` with no `position` attribute?

**Comment by waitingcheung** [comment]
The ``position`` attribute is computed later so it is not available at the time of creating a ``BufferGeometry``. The suggestion from @Mugen87 could be a workaround for this. It would be great if you can support default positions when the ``position`` attribute is not available.

**Comment by mrdoob** [comment]
Why are you converting `THREE.BufferGeometry` to `THREE.Geometry`?

**Comment by WestLangley** [comment]
> there is no compelling reason for converting THREE.BufferGeometry to THREE.Geometry.

If that is true, we should remove the method...

I am not sure it is true. There are issues such as this one:

https://stackoverflow.com/questions/43394385/three-smoothshading-has-no-effect-on-geometry/43395883#43395883

**Comment by Mugen87** [comment]
Wouldn't it be better to solve such issues when creating/exporting the model? I'm not sure if `three.js` should be the tool for "fixing" those geometries.

**Comment by WestLangley** [comment]
>there is no compelling reason for converting THREE.BufferGeometry to THREE.Geometry.

Do you propose removing the method, then?

**Comment by Mugen87** [comment]
Well, we need the method to create the counterparts of `BoxBufferGeometry` or `SphereBufferGeometry`. But generally i thought we head to deprecate `Geometry`, right? I think it's counterproductive if we now construct use cases for `Geometry`.

**Comment by WestLangley** [comment]
Users may need `Geometry` for adjacency information, for example. Who knows...

I also think it would be wise to identify where users use `Geometry` so we are prepared to offer work-arounds when we deprecate it.

We will stop _rendering_` Geometry` at some point, I expect. But I would retain the conversion utilities.

And I would not close this PR for the reason you stated -- maybe some other reason, but not that one. JMHO :).

**Comment by Mugen87** [comment]
Okay, you've convinced me 😊

**Comment by mrdoob** [comment]
Oh my... Sorry.

**Comment by Mugen87** [comment]
I have revisited this issue. For clarification: Even if the following code is applied to `Geometry.fromBufferGeometry()`...
```js
var positions = attributes.position !== undefined ? attributes.position.array : [];
```
...no attribute data are converted since a position attributes is required for `Face3` creation (an index without no position attribute makes no sense).

So we could apply this fix in order to avoid the runtime error however the output would not be usable at all. How about adding this instead:
```js
if ( attributes.position === undefined ) {

    console.error( 'THREE.Geometry.fromBufferGeometry(): Position attribute required for conversion.' );

}
```

**Comment by WestLangley** [comment]
I think that is reasonable.
