### ISSUE TITLE
The face of the shadow is reversed.

### ISSUE THREAD

**Issue by zhoushijie163** [mrdoob/three.js#10338]
![_2016-12-12_16-35-10](https://cloud.githubusercontent.com/assets/18611035/21092725/191d5d8a-c089-11e6-84cc-5cdb93401fba.png)
![_2016-12-12_16-35-48](https://cloud.githubusercontent.com/assets/18611035/21092727/19622abe-c089-11e6-95a0-5b86b2e31bb2.png)

##### Description of the problem 
WebGLRenderer algorithm for rendering shadows is wrong.
The face of the shadow is reversed.

##### Three.js version

- [X] Dev
- [X] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Shadows only work properly with _solid_ objects, which `PlaneGeometry` is not (only one side). Try with a flat `BoxGeometry`.
