### ISSUE TITLE
Fog seems to be dependent on near / far of camera 

### ISSUE THREAD

**Issue by kevineschmidt** [mrdoob/three.js#10341]
##### Description of the problem 
THREE.Fog seems to be dependent on camera near/far planes rather than a true distance to camera.
If I set a near and far value for fog and then alter the near & far values of the camera, the rendering of fog changes dramatically.

I would expect fog near/far to be relative to camera position, or at worst, near plane.  Having the far plan in the camera affect fog definitely seems odd.  

What seems to be the relevant line:
https://github.com/mrdoob/three.js/blob/dev/build/three.js#L7104

The depth is calculated using gl_FragCoord.z / gl_FragCoord.w, which is "it is a linear transform of the camera-space depth"  according to:
http://stackoverflow.com/questions/13711252/what-does-gl-fragcoord-z-gl-fragcoord-w-represent

##### Illustrative example
[fog_bug.tar.gz](https://github.com/mrdoob/three.js/files/649228/fog_bug.tar.gz)

##### Three.js version

- [X] Dev
- [x] r72
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by kevineschmidt** [comment]
[fog_bug.tar.gz](https://github.com/mrdoob/three.js/files/649233/fog_bug.tar.gz)

**Comment by kevineschmidt** [comment]
An alternative solution - requires adding a varying variable to the shader:
http://stackoverflow.com/questions/16131963/depth-as-distance-to-camera-plane-in-glsl

**Comment by kevineschmidt** [comment]
@WestLangley - I created a branch on a fork.  It currently only has one commit:
https://github.com/kevineschmidt/three.js/commit/367df52ba3e07941cf3ca8be883ec522e0e4ee05

I have 2 concerns:
1.  This might be a behavior change = possibly cause visual differences in existing code?
2.  I removed this segment from the shader, and I'm not wholly sure what the first portion of the #ifdef block does, to be honest.

 ```
   #ifdef USE_LOGDEPTHBUF_EXT

           float depth = gl_FragDepthEXT / gl_FragCoord.w;

   #else

           float depth = gl_FragCoord.z / gl_FragCoord.w;

   #endif
```

Is this commit suitable/ready/etc for a proper PR?

**Comment by WestLangley** [comment]
>I'm not wholly sure what the first portion of the #ifdef block does

It is possible to set the depth in the fragment shader with the extension.

>Is this commit suitable/ready/etc for a proper PR?

Try to include the shader chunks in the same order in each file.

You appear to have formatting problems, and missing newlines. Do not include build files in the PR. See https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js.

>This might be a behavior change = possibly cause visual differences in existing code

Definitely. What is the dynamic range of the old value of `depth`? What is the dynamic range of the value that replaces it? 

We should elicit opinions from others regarding this change. @bhouston ?

**Comment by kevineschmidt** [comment]
I will fix up based on your comments.  Regarding:
'Try to include the shader chunks in the same order in each file.'
Do you mean the header (_pars_) includes, or the code includes? Either way, this seems to be a bit dependent on a conditions, like what other shaders are included (sometimes the existing fog_pars_fragment follows, color_pars_fragment, other times envmap_pars_fragment) and obviously the code usage has to be in a single place

**Comment by kevineschmidt** [comment]
New commit: 
https://github.com/kevineschmidt/three.js/commit/ddd8c2b1eb8a92a344b261c2125d7a2997248309

And I have also created a new html file which illustrates the problem better if you swap this build vs. the current dev build.  This version does not include the built three.js libraries, however.  The animation loop simply adjusts the camera.far, leaving all other parameters alone.  In current dev, the cube changes color.  On my branch, it does not.  

[fog_bug.html.gz](https://github.com/mrdoob/three.js/files/652664/fog_bug.html.gz)

**Comment by WestLangley** [comment]
>I believe my solution is passing a more 'correct' value as it is a true distance-from-camera value

You are not using true distance from the camera; you are using `- mvPosition.z`, a measure of depth.

Let's wait for others to chime in.

**Comment by bhouston** [comment]
To get true depth use the functions here:

https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/packing.glsl

Basically this will get you true depth without having to pass it in.  Then you can define fog in terms of true depth from camera.

**Comment by kevineschmidt** [comment]
@bhouston

Thanks - I guess I have a few questions, and I apologize as I'm really new here.  
1.  Seems like you'd have to pass in the near/far plane values to use the code, which I did see.  I presume these could be extracted from the projection matrix?  I don't see any use of viewZToPerspectiveDepth in the code at this point.
2.  Seems like you'd also need to know whether you are dealing with a perspective or orthographic projection.  Perhaps this could be inferred from the projection matrix?
3.  Could you explain why mvPosition.z is not correct?  I thought this was the eye coordinate, and thus z would be the distance along the z axis from the camera? I realize the actual distance is longer (the length of mvPosition?), but that would model the fog spherically, correct?

**Comment by kevineschmidt** [comment]
@WestLangley @bhouston  - Any further thoughts?

**Comment by WestLangley** [comment]
@kevineschmidt I am also not sure @bhouston's suggestion is viable for the reasons you stated. Also, your approach is neither correct nor incorrect; it is just one way of doing it.

I think changing to a fog model that is a function of some measure of depth -- and independent of the camera parameters -- would be a good thing. Using `- mvPosition.z` for depth is reasonable. Users will have to tweak their fog params, however, as this will result in a visual change.

@mrdoob What is your opinion on changing to a different fog model? The counter argument is there have been no user complaints with the current model as far as I know.

**Comment by mrdoob** [comment]
> @mrdoob What is your opinion on changing to a different fog model? The counter argument is there have been no user complaints with the current model as far as I know.

I think it makes sense that fog is independent from near and far. I just didn't know it was possible at the time this was implemented 😇 

I support this! 👍

**Comment by WestLangley** [comment]
@kevineschmidt GIve the PR a go! You will have to modify the examples to get the look the same. [TIps](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js).
