### ISSUE TITLE
Clarity regarding basis vectors in ThreeJS matrix4

### ISSUE THREAD

**Issue by Formatter** [mrdoob/three.js#10348]
##### Description of the problem 
I am trying to render CAD drawings in browser using threejs and have overloaded the JSONLoader to load multiple JSONs in a single request. While the setup I have at the moment works well for drawings with few parts, when I try some heavy models, the tab tends to crash due to the chrome memory restrictions. So, I am trying to apply a visual surface determination algorithm to bring only the essential parts. So far z buffer and bounding box works well to render only the outer most parts and a few of the inner ones. But sadly, its still not enough. So now I am trying to apply Warnock's (area subdivision ) algorithm to dynamically modify the JSONs for a giving viewing angle, thus reducing non visible faces. Now coming to the relevant question, the first step for such an algorithm would be to transform the object's geometry for a given viewing angle. Like for example, consider you are looking a cube via a perspective camera, with the camera's lookAt being parallel to the object's local transform z axis. Now when you rotate 45 degrees around the object's local y axis, what I am thinking is that the camera should still be along the object's local z axis, ie this suggests a change in the basis vectors of the object(which in turn I hope would update the object's geometries for the new local basis vectors). I realize that there are methods to extractBasis and makeBasis in matrix4 but I am not quite getting the expected results. Am I going in the right direction or is there some other way to proceed here? 

##### Three.js version
- [x] r82

##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
This issues section is only to be used for reporting three.js bugs or for suggesting three.js enhancements.

See #10325 for a proposed forum that may be appropriate.

**Comment by Formatter** [comment]
My bad, will use the forum. Thanks
