### ISSUE TITLE
Three.js crashes browser tab (Aw snap) on iOS (iPad) when starting new game

### ISSUE THREAD

**Issue by andreasrosdal** [mrdoob/three.js#10340]
##### Description of the problem 
I'm using Three.js as a 3D engine in [Freeciv-web](https://play.freeciv.org/).  This is a bugreport and feature request for Three.js based on crashes reported by users on the game on iOS.

To reproduce:
1. Go to [play.freeciv.org](https://play.freeciv.org/) with an iOS device using Chrome or Safari.
2. Click the Single-player 3D beta button. 
3. Fill in your name and click start game. The browser tab will then crash with an "Aw, Snap" error message.

The game works nicely on all modern browsers on Windows 10 and Chrome on Android.
However, on chrome on iOS on a iPad, the browser tab crashes. The user is shown the "Aw, Snap!" error message from the browser. Safari shows the "something went wrong" error message.

A custom shader is used to render the terrain mesh. I use 3D models imported with the Three.js Collada importer. The source code and shaders can be [found here](https://github.com/freeciv/freeciv-web/tree/develop/freeciv-web/src/main/webapp/javascript/webgl).

This is the debug statistics from when the game has just started on Chrome on Windows 10:
geometries: 218
textures: 69
programs: 8
calls: 278
faces: 553471
points: 0
vertices: 1660413

The feature request that I would like to make is that Three.js would help me prevent the game from crashing the browser. If I have exceeded some resource on the GPU, then it would be nice if Three.js could help monitor the resource usage and give me an exception, rather than allowing the browser tab to crash. For example Three.js could report if I have created too many vertices or used too much memory for the device to handle. At the moment it is difficult for me to debug this problem since the browser tab crashed before any JavaScript exception is thrown.

The game works on Windows 10 and Android, so this is a problem specific to the iOS platform. It would be very nice if Three.js could help investigate platform-specific issues such as this.

##### Three.js version
- Dev (current dev from Github)

##### Browser
- [X] Chrome and Safari on iOS (iPad)

##### OS
- [X] IOS 10

##### Hardware Requirements (graphics card, VR Device, ...)
The game requires WebGL.

**Comment by aardgoose** [comment]
The issue is not something three.js can solve, the WebGL interface does not, as a deliberate policy give any information about the amount of GPU memory available (to prevent device fingerprinting, much like the battery status API). In the case of exhausting memory for the browser itself, browsers do not provide an API that gives memory information either with the exception of Chrome's non standard and vague performance.memory.

**Comment by mrdumb** [comment]
> The game works on Windows 10 and Android, so this is a problem specific to the iOS platform.

Your problem has nothing to do with a JavaScript library.
It's about WebGL on iOS (iPad).

**Comment by andreasrosdal** [comment]
Thanks for the replies. Do you have any suggestions about how to fix this on iOS?

**Comment by aardgoose** [comment]
Issues isn't the place for this, however I think there is maybe some value in a wiki section on memory saving techniques @mrdoob ?

**Comment by mrdoob** [comment]
@aardgoose maybe, but I suspect removing `THREE.Geometry` and adding `THREE.InstancedMesh` would be more effective 😁

**Comment by andreasrosdal** [comment]
Mrdoob, thanks for the feedback. Do you suggest that I remove THREE:Geometry and use THREE.InstancedMesh instead? Could you please give some more details?

**Comment by mrdoob** [comment]
Oh, I meant from the library itself. In your case... if you're using `THREE.Geometry`, consider switching to `THREE.BufferGeometry.
