### ISSUE TITLE
There is no morphColor information in json file exported from Blender.

### ISSUE THREAD

**Issue by iceleaf97** [mrdoob/three.js#10353]
##### Description of the problem 
I try to change the json file in this example.
[webgl_morphnormals](https://threejs.org/examples/?q=mo#webgl_morphnormals)
this is my json file that was exported from blender.
[rotate.json](https://github.com/iceleaf97/book/blob/gh-pages/rotate.json)  

There is no morphColor information in it.

Therefore I changed the json file(flamingo.js → rotate.json), the color of the json model was not loaded into the scene.

##### Three.js version
- [x] r82

**Comment by mrdoob** [comment]
`flamingo.js` was created using [convert_obj_three.py](https://github.com/mrdoob/three.js/blob/dev/utils/converters/obj/convert_obj_three.py). Unfortunately that feature is no longer supported (nor the converter).

**Comment by iceleaf97** [comment]
Is any method to import the color and animation into the scene?
