### ISSUE TITLE
Documentation for RectAreaLight and RectAreaLightShadow

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10365]
Should these have documentation? There are still a lot of TODOs in the code. 

Perhaps even just stub documentation warning people if they are not production ready yet.

**Comment by mrdoob** [comment]
> Perhaps even just stub documentation warning people if they are not production ready yet.

That sounds good to me. Yeah, we still need to play with that code a bit more.

**Comment by looeee** [comment]
OK, I'll get on it :)

**Comment by looeee** [comment]
#10378
