### ISSUE TITLE
AxisHelper not showing colored

### ISSUE THREAD

**Issue by Horray** [mrdoob/three.js#10360]
I'm trying to add an `AxisHelper` to my `three.js` project. I added it like this:

    axes = new THREE.AxisHelper(100);
    scene.add(axes);

It gets added, but it isn't colored It's solid white, and therefore hard to see. How can I make it the regular colors?

**[JSFiddle](https://jsfiddle.net/0p83hugs/)**

**Comment by WestLangley** [comment]
The OP is using `CanvasRenderer`.

**Comment by WestLangley** [comment]
The work-around and explanation are in [this SO answer](http://stackoverflow.com/questions/41154654/axishelper-not-showing-colored/41156635#41156635).

I assume `CanvasRender` is no longer under development.

**Comment by Mugen87** [comment]
I'm unable to reproduce the issue with latest dev branch:

http://jsfiddle.net/oL61khm7/3/
