### ISSUE TITLE
rendering failure of transparent png

### ISSUE THREAD

**Issue by shrekshrek** [mrdoob/three.js#10372]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

http://shrek.imdevsh.com/demo/book2/
transparent png texture is doesn't work in this demo.
maybe is rendering failure of transparent png texture?
it's my code:
        var _group = new THREE.Group();

        var _len = model.data.length;
        for (var i = 0; i < _len; i++) {
            var _geo = new THREE.PlaneGeometry(512, 512);
            _geo.translate(-256, 0, 0);

            var _mat = new THREE.MeshPhongMaterial({
                map: new THREE.TextureLoader().load(model.data[i]),
                side: THREE.DoubleSide,
                transparent: true
            });
            var _plane = new THREE.Mesh(_geo, _mat);
            _plane.rotation.set(0, 360 / _len * i / 180 * Math.PI, 0);

            _group.add(_plane);

        }

##### Three.js version

- [ ] Dev
- [x] r83
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Try setting `alphaTest: 0.5`.

**Comment by shrekshrek** [comment]
it's work. wonderful. thank a lot.
