### ISSUE TITLE
Extending Mesh class changes geometry to BufferGeometry

### ISSUE THREAD

**Issue by cheesyeyes** [mrdoob/three.js#10374]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

When I extend the Mesh class and create a new instance of the new class with a PlaneGeometry
it becomes a BufferGeometry. Why is that?

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
Can you provide a fiddle with your code?

**Comment by cheesyeyes** [comment]
`let mesh = new Mesh((new PlaneGeometry(1,1), new MeshBasicMaterial({color:0xff0000});
//mesh.geometry = PlaneGeometry

class Thing  extends Mesh{
  constructor(){
    super();
    this.something = {};
  }
}

let mesh = new Mesh((new PlaneGeometry(1,1), new MeshBasicMaterial({color:0xff0000});

//mesh.geometry = BufferGeometry`

**Comment by Mugen87** [comment]
Your constructor should have the parameters `geometry` and `material` and then pass these values to the `super` method. Something like this:
```javascript
class Thing extends Mesh {
  constructor( geometry, material ){
    super( geometry, material );
  }
}
```

More information [here](http://www.2ality.com/2015/02/es6-classes-final.html)

**Comment by cheesyeyes** [comment]
makes totally sense. thanks!
