### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodes' of null

### ISSUE THREAD

**Issue by omidakhavan** [mrdoob/three.js#10387]
Hi,
When i try to run your example about clladaloader which has model of monstor.dae i got this error.
Could you please test your example with latest version of colladaloader.js and threejs , 
It show correctly in this link https://threejs.org/examples/webgl_loader_collada.html
but when i downloaded all three js package i found out your example with colladaloader has error

**Comment by Mugen87** [comment]
I've tested this with the downloaded repo and Firefox 50.1.0. No errors. 

Can you also test with a Firefox? You maybe using a browser that blocks a XMLHttpRequest with protocol scheme `file`.
