### ISSUE TITLE
Clarification on Docs vs Wiki (vs forum?) 

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10388]
Continuation of the discussion here which is a bit stale at this point: #5410 

The docs currently have 4 sections
- Manual 
    - This has two pages at present, a very useful "Creating a scene" page and a kind of orphaned looking page on matrix transformations
- Reference
    - This still needs some expansion in places, but should now be a complete API reference (as of r83). (ping me if you find mistakes, of which I'm sure there are more a few!)
- Examples
    - This is very incomplete
- Developer Reference
    - Also very incomplete

The Wiki is a bit of a mess at the moment but has
- TODO (things to be developed in Three)
- JSON reference
- link to migration guide
- code style guide
- FAQ section which largely link to github issues
- various manual type articles
- "On the Net" section with links to all kind of Three related info across the net (some broken and some out of date)

@mrdoob you mentioned here #10342 that you'd like the JSON reference to stay in the Wiki (although you also said in #5410 that everything should go in the docs :p ) 

I have two suggestions:
1. Everything goes in the docs. Get rid of the Wiki

2. Split like so:
- Docs: Everything related to using Three
- Wiki: Everything related to developing Three

Obviously there would be some crossover in 2. but in ambiguous cases the docs should be preferred.

**Comment by mrdoob** [comment]
I think I prefer 2 ✌️

**Comment by looeee** [comment]
Great, me too :) 

So the first tasks would look like this:

1. Move Developer Reference pages to Wiki
2. Move manual type pages from Wiki to doc's Manual section
3. Create Useful Links page in doc's Manual section, check link in Wiki to see if they are still relevant and move them there
4. Move (or perhaps duplicate) Code Style guide to doc's Manual section
5. Move migration guide from Wiki to docs
6. Create FAQ page in doc's Manual section, move relevant questions there. Some FAQs in the wiki are related to development, they can be moved to a new page there

@mrdoob (or anyone else) thoughts?

**Comment by Fallenstedt** [comment]
@looeee I agree. The docs and wiki does seem all over the place. separating them would nice.

**Comment by looeee** [comment]
@mrdoob one thing that has occurred to me here is how useful the PR system is as review and record system for documentation (I mean, you are carefully reading over everything I submit before merging right? 😛 ). 

But seriously, everyone that is actively involved in three.js will presumably get notifications for any issues or PRs made here, and will know when something has been updated. The wiki on the other hand, as far as I'm aware has no such notification system - lots of changes can be made without anyone noticing unless they think to check, and the people with the expertise to notice and correct mistakes probably won't need to check the wiki very often. 

I'm still perfectly OK with the wiki / docs split, just wanted to raise this issue before implementing it.

**Comment by mrdoob** [comment]
> I mean, you are carefully reading over everything I submit before merging right? 😛

Of course! 😉

> I'm still perfectly OK with the wiki / docs split, just wanted to raise this issue before implementing it.

I guess we can start by moving things from wiki to docs and see what we end up with.

**Comment by looeee** [comment]
OK, sounds good! I'll leave the dev ref section as is for now.

**Comment by looeee** [comment]
I'll use this issue as a place to record changes I make to the wiki as well.

First changes:
Deleted "Getting Started"
Deleted "Using Matrices & Object3Ds in THREE"
These pages already have better counterparts in the docs

**Comment by looeee** [comment]
Shall I delete this page? https://github.com/mrdoob/three.js/wiki/Using-three.js-in-C%23-with-SharpKit

It's not really related to three

**Comment by mrdoob** [comment]
Sounds good!

**Comment by looeee** [comment]
Deleted Articles -> Drawing lines (moved to docs)
Deleted Articles -> Text in Three.js (moved to docs)
Deleted Articles -> Testing with npm (moved to docs)

Deleted Articles -> Using three.js in C# with SharpKit (not related to three.js)

**Comment by looeee** [comment]
Will I delete this page? It doesn't say much that a user couldn't work out on their own pretty quickly and may be out of date anyway
https://github.com/mrdoob/three.js/wiki/Using-SketchUp-Models

**Comment by mrdoob** [comment]
Kind of tempting to do a page on the docs with a collection of those...

**Comment by looeee** [comment]
Deleted Articles -> threejs-typescript-gulp-jspm-seed (Dead link)

Fixed link to three.js.org/docs and deleted second occurrence of link

Deleted Tools -> ThreeFab (hasn't been updated in 4 years)

**Comment by looeee** [comment]
>Kind of tempting to do a page on the docs with a collection of those...

Yup, I agree... I'm creating wishlist of manual pages that I'll link at some point that includes those.

I rather meant that that particular article doesn't have much useful info and can be deleted. A better version should be created in the future though.

**Comment by looeee** [comment]
Changed name of Migration to Migration Guide
Changed name of TODO to Developer's TODO list

Created *Introduction*, *Developer Guide* and *Three.js JSON format schema* sections

Created *Purpose of Wiki* page to explain seperation of Wiki and docs (currently empty)

**Comment by looeee** [comment]
Moved page _Detecting WebGL and browser compatibility_ from Wiki to manual #10427

**Comment by looeee** [comment]
Not sure what to do with this page:
https://github.com/mrdoob/three.js/wiki/Some-patterns-used-in-examples

@mrdoob will I delete it or move it to the Manual?

**Comment by looeee** [comment]
Should this page be moved to the manual or deleted?
https://github.com/mrdoob/three.js/wiki/Features

**Comment by looeee** [comment]
Created a useful links page in the docs and moved nearly all of the links from the wiki there: #10433

**Comment by looeee** [comment]
Deleted FAQs:
- Which import format / exporter should I use?
    - linked to very old issue, an updated version should probably be created
- How to use Blender export script?
    - linked to very old issue
 - How to use OBJ converter script?
    - linked to comments in source code
-How to update things with WebGLRenderer?
    - moved to manual #1042
- How to run things locally?

**Comment by looeee** [comment]
Should this page be moved to the manual or deleted?
https://github.com/mrdoob/three.js/wiki/Features

**Comment by mrdoob** [comment]
> Should this page be moved to the manual or deleted?
https://github.com/mrdoob/three.js/wiki/Features

I would delete it.

**Comment by looeee** [comment]
Done!

**Comment by looeee** [comment]
@WestLangley these are the pages moved from the Wiki to the docs. Which do you think should have stub redirects?

Getting Started (was already in manual)
Using Matrices & Object3Ds in THREE (was already in manual)
Drawing lines
Text in Three.js
Testing with npm

Detecting WebGL and browser compatibility 
How to run things locally
How to update things


My suggestion would be just these:
Testing with npm
Detecting WebGL and browser compatibility 
How to run things locally
How to update things

The rest were either of low quality or out of date anyway so it's unlikely they were linked

**Comment by WestLangley** [comment]
>Which do you think should have stub redirects?

Only these:
_How to run things locally_
_How to update things_

**Comment by looeee** [comment]
OK, done.

**Comment by looeee** [comment]
Unless anybody spots any other issues, aside from cleaning up the moved page, the last task here is deciding what to do with the Developer Reference section in the docs. 

@mrdoob thoughts?

**Comment by looeee** [comment]
I would like to finalise this issue for now - the last task is deciding whether to move the developer reference section to the wiki. @mrdoob did you have any thoughts on this?

**Comment by WestLangley** [comment]
Whatever you do would be fine with me, but please redirect long-established links.

**Comment by looeee** [comment]
@WestLangley I'm actually fine with leaving it as is, and I don't intend to add anything to the developer reference at the moment, so rather than breaking links I'll just close this issue for now.

**Comment by mrdoob** [comment]
Leaving it as it is sounds good to me 👍
