### ISSUE TITLE
Bug on tablet when i see this example

### ISSUE THREAD

**Issue by George35mk** [mrdoob/three.js#10396]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
https://threejs.org/examples/#webgl_interactive_raycasting_points

On this example when i use my tablet too see the interactive raycasting points my fps was 20 only with the tablet samsung galaxy tab s but when i press the (fps) button to (ms) inforformation after that the fps was 59 can you pls look at this i think is bug thnx

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [ ] IOS

**Comment by mrdoob** [comment]
fps = frames rendered in 1 second
ms = milliseconds that the current frame took to render

1 frame / 20 frames = 0.5 ms, which matches the 0.59ms you're seeing when switching the stats mode.
