### ISSUE TITLE
Deprecate THREE.Spline?

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#10400]
##### Description of the problem 

It looks like `Spline` in `src/math` is somewhat obsolete because `CatmullRomCurve3` provides nearly the same functionality. 

`Spline` is currently used in some examples (like [webgl_lines_dashed](https://threejs.org/examples/webgl_lines_dashed.html)). But it should be straightforward to change the code so `CatmullRomCurve3` is used instead.

Are there any objections to a removal of `Spline`?

##### Three.js version

- [X] Dev

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by looeee** [comment]
You beat me to this by a couple of hours 😁

**Comment by mrdoob** [comment]
Sounds good to me too 👌
