### ISSUE TITLE
GridHelper size - maybe poorly explained.

### ISSUE THREAD

**Issue by Alberto-Vivar** [mrdoob/three.js#10409]
First of all, I have to thank all the contributors of this project for its effort. ;)

Iin the [Grid Helper doc](https://threejs.org/docs/#Reference/Extras.Helpers/GridHelper), this is what says about size:

>>size -- The size of the grid. Default is 10.

So, I'd expected from one side to the opposite to size 10 units, and the grid would be 10x10.
 **BUT**, what really appears to be is to measure 20 x 20 units. Am i misunderstanding or what?
There it is a [jsfiddle](http://jsfiddle.net/6ydw03L8/1/) where I made a try.

[Note: forgive my poor english]

Thanks in advance.

**Comment by looeee** [comment]
Hmm... he's right you know! I'll update the docs. Actually the gridhelper page could do with  an overhaul.

@Alberto-Vivar thanks :) good catch

**Comment by WestLangley** [comment]
>So, I'd expected from one side to the opposite to size 10 units, and the grid would be 10x10.

Right. Just like `PlaneGeometry`.

IMHO, the API should be changed.

**Comment by Hectate** [comment]
Well it looks like when I touched this I didn't notice that the size was doubled. That's quite the oversight.

**Comment by Alberto-Vivar** [comment]
Nice.

**Comment by openhardwarecoza** [comment]
https://threejs.org/docs/#Reference/Extras.Helpers/GridHelper now 404s?
