### ISSUE TITLE
WebGLRenderer Clipping Plane with EffectComposer

### ISSUE THREAD

**Issue by Ludobaka** [mrdoob/three.js#10401]
##### Description of the problem 
When using global clipping planes of WebGLRenderer, the different passes of EffectComposer are not renderered correctly when they involve rendering a WebGLRenderTarget. Indeed, the renderer is also applying the clipping on textures, resulting in a brutal clipping.  You can see the effect in the following example :  http://jsfiddle.net/Ludobaka/tvvou3m2/

I'm available to fix the problem but I'm still thinking of how to design it. I prefered to create the issue first. I was thinking of :
- Modifying each ThreeJS Pass to deactivate clippingPlane when rendering a framebuffer
- Make some changes on WebGLRendererTarget to deactivate clippingPlanes when using a framebuffer

Update :
The problem seems to come at WebGLRenderer.render when calling projectObject. ThreeJS is checking CPU side if the object is viewable or not.

##### Three.js version

- [x] Dev
- [x] r83
- [x] r82
- [x] Previous rev with clipping planes

##### Browser

- [x] All of them

##### OS

- [x] All of them

##### Hardware Requirements (graphics card, VR Device, ...)
None

**Comment by Mugen87** [comment]
Fixed via #10403.
