### ISSUE TITLE
when in long distance(such as 1200000 away from (0,0)),racaster.setFromCamera() have low precision

### ISSUE THREAD

**Issue by GitHub-wk** [mrdoob/three.js#10408]
(***when in long distance(such as 1200000 away from (0,0)),racaster have low precision***)

##### Description of the problem 
```
unproject: function () {

		var matrix;

		return function unproject( camera ) {

			if ( matrix === undefined ) matrix = new Matrix4();

			matrix.multiplyMatrices( camera.matrixWorld, matrix.getInverse( camera.projectionMatrix ) );
			return this.applyProjection( matrix );

		};

	}(),
```
when we call ``racaster.setFromCamera`` ,threejs will call unproject function,but in long distance ``camera.matrixWorld`` is bad,so the result point has low precision. we can set camare position to (0,0,0),for`` ray.direction`` is not related to camera's position.

I solve this problem like this,then the pick point has high precition in long distance.
```
var tempCamera=camera.clone();
tempCamera.position.set(0,0,0);
tempCamera.updateMatrixWorld(true);
raycaster.setFromCamera(mouse, tempCamera);
raycaster.ray.origin.copy(camera.position);
```
##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Yeah, you should avoid such long values. Also, be aware that 1 unit = 1 meter. Your world is 1200 kilometers.
