### ISSUE TITLE
StandrardMaterial.aoMap not working in Chrome

### ISSUE THREAD

**Issue by larsberg** [mrdoob/three.js#10416]
It seems like the aoMap and aoMapIntensity have no effect on the THREE.MeshStandardMaterial in the most recent chrome (55.0.2883.95). It is working in firefox and safari though. I've been using this example to test: 

https://threejs.org/examples/#webgl_materials_displacementmap

##### Three.js version

- [ ] Dev
- [x] r83
- [x] r82
- ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
The effect is subtle in that example. Are you setting the `metalness` slider to zero first?

FWIW, on macOS Sierra / Chrome (55.0.2883.95) it works for me.

**Comment by larsberg** [comment]
ugh, It's working for me now, not sure what happened. I was testing this because it wasn't working in a project I'm working and now it seems too. 
sorry to waste your time!
