### ISSUE TITLE
doc: a tiny fault

### ISSUE THREAD

**Issue by PaulineStich** [mrdoob/three.js#10418]
Really nothing that is much important, but the mispelling makes it a fault. 

https://threejs.org/docs/?q=point#Reference/Materials/PointsMaterial

```
//This will add a starfield to the background of a scene
var starsGeometry = new THREE.Geometry();

for ( var i = 0; i < 10000; i ++ ) {
	var star = new THREE.Vector3();
	star.x = THREE.Math.randFloatSpread( 2000 );
	star.y = THREE.Math.randFloatSpread( 2000 );
	star.z = THREE.Math.randFloatSpread( 2000 );
	geometry.vertices.push( star );
}

var starsMaterial = new THREE.PointsMaterial( { color: 0x888888 } )
var starField = new THREE.Points( geometry, starsMaterial );
scene.add( starField );
```

##### Three.js version 

- [ ] r82

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
Would you like to do the correction? You can edit the mentioned file via the following link and then propose a file change:

https://github.com/mrdoob/three.js/edit/dev/docs/api/materials/PointsMaterial.html

**Comment by Fallenstedt** [comment]
https://github.com/mrdoob/three.js/pull/10466

#10466
