### ISSUE TITLE
Useful links page in docs

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10414]
I'm moving the links from the wiki to the docs as discussed here #10388

Thing is, a lot of the links are very out of date - it looks like nothing was added after 2012, and going through the links, while a couple of them are still useful most should probably be scrapped. 

So, the question is: what are the most up to date cutting edge resources for learning about and discussing three.js on the web in 2016?

Go!

**Comment by mrdoob** [comment]
For the last few years I've been collecting everything I find here:
https://plus.google.com/b/104300307601542851567/+ThreejsOrg

**Comment by looeee** [comment]
Thanks, there are some great links there.

**Comment by looeee** [comment]
Actually I would probably put a note at the top of the page saying something like:

In addition to this page, mrdoob maintains a collections of links on Google+, check them out here

What do you think?

**Comment by mrdoob** [comment]
Sounds good to me 👍

**Comment by looeee** [comment]
Cool. How do you like your name styled? mrdoob, mr.doob or something else?

**Comment by mrdoob** [comment]
mrdoob ✌️
