### ISSUE TITLE
Bug with group duplication within BufferGeometry.copy

### ISSUE THREAD

**Issue by adnanademovic** [mrdoob/three.js#10417]
##### Description of the problem 

There seems to be a bug when copying from a buffer geometry into another existing buffer geometry, which causes groups to be appended, instead of replaced.
I don't think this is working as intended.
[Problematic code](https://github.com/mrdoob/three.js/blob/master/src/core/BufferGeometry.js#L1017-L1024)

I think this needs a clearGroups() call before starting to add groups.

##### Three.js version

- [x] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
Um, same problem for `attributes`, right?

**Comment by adnanademovic** [comment]
Yeah. I think it's same with index as well.

**Comment by Mugen87** [comment]
`setIndex` works correctly. The given index is assigned to the corresponding property. No adding here.
```javascript
this.index = index;
```

**Comment by Mugen87** [comment]
I think we need an additional method `clearAttributes` and then call it with `clearGroups` at the beginning of `.copy()`.

```javascript
clearAttributes: function () {

	this.attributes = {};

},
```

**Comment by WestLangley** [comment]
`index` is not handled properly when copying from non-indexed to indexed.

It appears that the `copy()` method in both `Geometry` and `BufferGeometry` do not handle all properties.

**Comment by adnanademovic** [comment]
That is the scenario I was thinking of as well. The assignment should just happen unconditionally. Replacing
```
if ( index !== null ) {
    this.setIndex( index.clone() );
}
```
with
```
if ( index !== null ) {
    index = index.clone();
}
this.setIndex(index);
```

**Comment by Mugen87** [comment]
> index is not handled properly when copying from non-indexed to indexed.

Good point! 👍

**Comment by Mugen87** [comment]
Here's an alternative implementation. First, we do some kind of reset and then we execute the actual copy. The code regards all properties of `BufferGeometry`.

```javascript
copy: function ( source ) {

	var name, i, l;

	// reset

	this.index = null;
	this.attributes = {};
	this.morphAttributes = {};
	this.groups = [];
	this.boundingBox = null;
	this.boundingSphere = null;

	// name

	this.name = source.name;

	// index

	var index = source.index;

	if ( index !== null ) {

		this.setIndex( index.clone() );

	}

	// attributes

	var attributes = source.attributes;

	for ( name in attributes ) {

		var attribute = attributes[ name ];
		this.addAttribute( name, attribute.clone() );

	}

	// morph attributes

	var morphAttributes = source.morphAttributes;

	for ( name in morphAttributes ) {

		var array = [];
		var morphAttribute = morphAttributes[ name ]; // array of Float32BufferAttributes

		for ( i = 0, l = morphAttribute.length; i < l; i ++ ) {

			array.push( morphAttribute[ i ].clone() );

		}

		this.morphAttributes[ name ] = morphAttribute.clone();

	}

	// groups

	var groups = source.groups;

	for ( i = 0, l = groups.length; i < l; i ++ ) {

		var group = groups[ i ];
		this.addGroup( group.start, group.count, group.materialIndex );

	}

	// bounding box

	var boundingBox = source.boundingBox;

	if ( boundingBox !== null ) {

		this.boundingBox = boundingBox.clone();

	}

	// bounding sphere

	var boundingSphere = source.boundingSphere;

	if ( boundingSphere !== null ) {

		this.boundingSphere = boundingSphere.clone();

	}

	// draw range

	this.drawRange.start = source.drawRange.start;
	this.drawRange.count = source.drawRange.count;

	return this;

},
```

**Comment by Mugen87** [comment]
Drawback of this approach: Many object will be created if `.copy()` is executed in each frame...

**Comment by Mugen87** [comment]
This issue can be closed now.
