### ISSUE TITLE
Crossbrowser CanvasRenderer issues

### ISSUE THREAD

**Issue by obelmont** [mrdoob/three.js#10420]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

Hey there, had a look at one of my old projects and it looks the canvas and renderer and WebGL renderer is broken on chrome. 

The error I am getting is below.

`THREE.CanvasRenderer has been moved to /examples/js/renderers/CanvasRenderer.js` 

My Chrome version is 55.0.2883.95 (64-bit).

I have tried updating to r82 and that made no difference. 

Im using a function to check for webgl support (below) and then determine the renderer from that. Its coming back false and using the backup canvas element. 

```js
function webGLSupport() {
		try {
			var canvas = document.createElement('canvas');
			return !!(window.WebGLRenderingContext && (
				canvas.getContext('webgl') || canvas.getContext('experimental-webgl'))
			);
		} catch(e) {
			return false;
		}
	}

	if (webGLSupport()) {
		renderer = new THREE.WebGLRenderer({alpha: true});

	} else {
		renderer = new THREE.CanvasRenderer();
	}
```

I have also tried forcing WebGL and am getting this console response on chrome.
Having no issues with firefox or safari.

```
three.min.js:645 THREE.WebGLRenderer: Error creating WebGL context.
THREE.WebGLRenderer @ three.min.js:645
three.min.js:689 Uncaught TypeError: Cannot read property 'getExtension' of null
    at THREE.WebGLExtensions.get (three.min.js:689)
    at new THREE.WebGLRenderer (three.min.js:646)
    at init (index.js:51)
    at index.js:17
    at index.js:182
```

Also if I force the canvas renderer I get this error. This error is also consistent over safari 9.1.2 and Firefox 50.1.0

```
three.min.js:817 THREE.CanvasRenderer has been moved to /examples/js/renderers/CanvasRenderer.js
THREE.CanvasRenderer @ three.min.js:817
index.js:62 Uncaught TypeError: renderer.setPixelRatio is not a function
    at init (index.js:62)
    at index.js:17
    at index.js:182
```

Happy to keep looking at this if you think this is an error with my code however I thought it might be an issue with browser capability as the code hasn't changed in months!

Olly

##### Three.js version

- [ ] Dev
- [X] r82
- [x] r76

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by looeee** [comment]
> THREE.CanvasRenderer has been moved to /examples/js/renderers/CanvasRenderer.js

This is not an error, it means that the CanvasRenderer is no longer a part of the core and has been moved to that file. You will have to include it in order to use it.
