### ISSUE TITLE
Move migration guide to docs?

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#10421]
Maintaining this in two places is counterproductive, but I think it's important as part of both the normal docs and developer docs, so will I leave it in the Wiki and make a link in the docs, or move it to the docs and leave a link in the Wiki?

@Mugen87, @mrdoob you guys have been keeping this up to date, thoughts?

**Comment by looeee** [comment]
Same question goes for the Mr.doob's Code Style™ page.

**Comment by mrdoob** [comment]
I think I would keep those on the Wiki...

**Comment by looeee** [comment]
Sounds good! I'll add links to the docs.

**Comment by looeee** [comment]
#10425
