### ISSUE TITLE
DirectionalLightShadow constructor does not take camera

### ISSUE THREAD

**Issue by kylegmaxwell** [mrdoob/three.js#10437]
##### Description of the problem 
The orthographic shadow camera is hard coded, thus it only works in very limited circumstances. It seems like a simple typo, the input is called 'light' when it should probably be camera, and then a quick check to use the default or the camera that is passed in. Right now the 'light' parameter appears not to be used. I can probably make a pull request myself, but I wanted to check if anyone is already working on shadows, so as to not duplicate work.

LightShadow.call( this, new OrthographicCamera( - 5, 5, 5, - 5, 0.5, 500 ) );
https://github.com/mrdoob/three.js/blob/dev/src/lights/DirectionalLightShadow.js#L10

Also the link on this page to the source is broken (r83).
https://threejs.org/docs/index.html?q=shadow#Reference/Lights.Shadows/DirectionalLightShadow

##### Three.js version
- [x] Dev
- [x] r83

##### Browser
- [x] All of them

##### OS
- [x] All of them

##### Hardware Requirements (graphics card, VR Device, ...)
Any

**Comment by looeee** [comment]
>Also the link on this page to the source is broken (r83).

Ah, good catch - this is because the link is generated automatically and the doc page is not in an identical folder to the corresponding src file. There may be a couple of occurences of this that I didn't spot, I'll look into it

**Comment by looeee** [comment]
You can change the parameters of the camera, so there should never be a need to pass one in - the docs have been updated in the dev branch, so this will be explained there after the next release:

```
var light = new THREE.DirectionalLight( 0xffffff, 1, 100 );
light.shadow.camera.near = 0.5;       
light.shadow.camera.far = 500;
```

**Comment by kylegmaxwell** [comment]
ok, I just thought it was inconsistent since the LightShadow takes a camera. But now I see that SpotLightShadow also does not take an argument to it's constructor, so that's fair. Thanks.

ps. I worked around it by doing light.shadow.camera = new THREE.OrthographicCamera(...) since I might use the same camera for multiple lights.
