### ISSUE TITLE
Some material texture faces / triangles not rendering

### ISSUE THREAD

**Issue by Collaboratives** [mrdoob/three.js#10436]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem
Details here: http://stackoverflow.com/questions/41154498/threejs-some-material-texture-faces-triangles-not-rendering

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
As pointed out on SO, the issue appears to be faces with more than 4 sides. `OBJLoader`only supports triangular faces and quads.
