### ISSUE TITLE
Message data format for multi-threading support

### ISSUE THREAD

**Issue by matthias-w** [mrdoob/three.js#10447]
It would be great if there was the possibility to easily transfer computation heavy tasks with THREE.js to web workers. The message based communication from and to web workers only allow special [objects](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) to be sent. For example, functions are not allowed/supported.

An example case for this would be the loading and editing (e.g. doing some CSG stuff) of large geometry objects inside a web worker and transfer these geometries back to the main thread. Unfortunately, when doing so the received geometry object does have all the data properties (e.g. vertex array values) but no functions and therefore not usable. Maybe it could be helpful if there was some kind of method like `Geometry.fromMessageInterchangeFormat` to create a new Geometry instance on the basis of the already existing data properties.

Most users do have multi-core machines. It would be great if THREE.js would somehow (not necessarily in the way I proposed) take this into account. What do you think? Does that make sense?

**Comment by lekxi** [comment]
It is recommended to stick to buffer geometry. You can transfer buffer arrays between main and worker threads with nearly no cost (transferables). I generate large DC terrain chunks in multiple threads, but use 3js objects just temporary, spawning millions objects like THREE.Vector3 would both slow down and ramp up memory. You only need to import those parts of T3js you require to do math and stuff.
