### ISSUE TITLE
JSONLoader not reading stored Mesh files correctly.

### ISSUE THREAD

**Issue by jamesphilipreilly** [mrdoob/three.js#10468]
##### Description of the problem 
JSON loader cannot parse JSON file-based geometries correctly.  It parses the metadata correctly but passes the wrong parameter to _**scope.parse**_.  

 

Line **_32514_**  reads like this    _var object = scope.parse( **json** , texturePath );_

Line **_32514_**  should read      _var object = scope.parse( **json.data**, texturePath );_

I tested the correct answer with a save of a THREE.Mesh on release 83, 74 72 and several others.
				

##### Three.js version

- [ ] Dev
- [x ] r83
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Can you share a file that is not being read properly?

**Comment by jamesphilipreilly** [comment]
This file is exported from a geometry.toJson statement and then loadjson imported.
it is here

https://drive.google.com/open?id=0B0OVryHxkoY0Y3JCZnN1cEd2cWM

I have just returned to serious Three.js coding and it has improved so much over the last few years.
Congratulations. A very impressive body of work indeed!

**Comment by mrdoob** [comment]
This was the right fix 👌
https://github.com/mrdoob/three.js/blob/dev/src/loaders/JSONLoader.js#L529-L534

**Comment by jamesphilipreilly** [comment]
glad to hear it.


BTW  IMHO Three.js is the best library on git.  The code is beautifully
laid out, crystal clear and a joy to work with.  If only you could educate
some of the React-ish / ES 6 / functional programming/ Java  developers on
the value of clarity and simplicity!

Making things look simple and easy requires genuine brilliance!

**Comment by mrdoob** [comment]
😅
