### ISSUE TITLE
CCDIKSolver won't work correctly for a scaled model

### ISSUE THREAD

**Issue by Azuo** [mrdoob/three.js#10472]
##### Description of the problem 

Issue #10010 optimized CCDIKSolver, removed unnecessary updateMatrixWorld( true ) calls.
But the following replacement is <b>NOT</b> actually equivalent:

Replace:
`invLinkQ = link.getWorldQuaternion().inverse();`
with:
`invLinkQ = invLinkQ.setFromRotationMatrix( link.matrixWorld ).inverse();`

Since `setFromRotationMatrix` expects "a pure rotation matrix (i.e, unscaled)", but oberviously matrixWorld is not, so the CCDIKSolver won't work correctly for a scaled model.

##### Three.js version

- [X] Dev
- [X] r83
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by takahirox** [comment]
Good catch. I'll fix soon, thanks!
