### ISSUE TITLE
Importing Object with Multiple Materials From Blender; No Materials Appearing

### ISSUE THREAD

**Issue by Lyxpudox** [mrdoob/three.js#10473]
##### Description of the problem 
I'm trying to import a model from Blender (a Rubik's Cube) by using the Three.js Blender Exporter tool that has seven different materials on it. Upon loading the object however, I get an object that is completely grey. Although I've tried selecting 'Face Materials' when exporting and trying to break the object up by material, the object still shows up grey.

[Here](http://pastebin.com/DrafptVx) is the code, [here](http://pastebin.com/3GWW8Q7S) is JSON file, and [here](https://drive.google.com/file/d/0B1UmyRG0tncKRm05SkdVVnNsZ0U/view?usp=sharing) is the blend file I've been using.

I've also created this [thread](https://www.reddit.com/r/threejs/comments/5kejle/importing_a_model_from_blender_materials_not/), and no suggestions have worked yet. Is there any way to import an object from Blender that has multiple materials on it?

##### Three.js version

- [ ] Dev
- [x] r83

##### Browser

-  [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by inear** [comment]
The blender exporter is not supporting multimaterials. There is a fork and a PR that is waiting in the queue, but meanwhile you can use this: https://github.com/s9k/three.js/tree/exporter-multimat-fix2/utils/exporters/blender

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
