### ISSUE TITLE
Can't use a Texture created from a Canvas as a uniform

### ISSUE THREAD

**Issue by mchlr** [mrdoob/three.js#10486]
Hey there,

I've recently stumbled across this issue on my way to increase the EffectComposers performance. 

#### What I tried to do:
As I've already explained [here](https://github.com/mrdoob/three.js/issues/10350), I try to chain a lot of post-processing effects together to create an image alteration.

As performance is always a key factor for me, I started to notice that, naturally, the performance of an EffectComposer decreases with its load. (Number of ShaderPasses added into the specific composer)

Which brought an Idea into my mind: Since I'm still using the ColorLookUpShader (Have a look at my first issue, the link is above.), I could use one EffectComposer to render a set of transformations to a lookup table instead of an image. I could then re-use this lookup table created by the FirstComposer as a uniform in a SecondComposer. 
This way, I could encapsulate and use computing time efficiently as I could pre render a whole set of transformations and simply add the whole set as a lookup table into my SecondComposers' uniforms.

#### The Problem:

I tested different methods on how to achieve this behavior but unfortunately nothing really worked out.

Here is the Code I'm currently using to create both EffectComposers:

`                   var txt = testTexture;

                    var frstRenderer = new THREE.WebGLRenderer({
                        canvas: document.getElementById("CanvasOne"),
                        preserveDrawingBuffer: true
                    });
                    frstRenderer.setPixelRatio(window.devicePixelRatio);

                    var container = $("#ContainerOne")[0];

                    frstRenderer.setSize(container.offsetWidth, container.offsetHeight);

                    var aspect = txt.image.width / txt.image.height;
                    var fov = 60;
                    var dist = 450;

                    // Convert camera fov degrees to radians
                    fov = 2 * Math.atan(( txt.image.width / aspect ) / ( 2 * dist )) * ( 180 / Math.PI );

                    var frstCam = new THREE.PerspectiveCamera(fov, aspect, 1, 10000);
                    frstCam.position.z = dist;

                    var frstScene = new THREE.Scene();
                    var frstObj = new THREE.Object3D();

                    frstScene.add(frstObj);

                    var frstGeo = new THREE.PlaneGeometry(txt.image.width, txt.image.height);

                    var frstMat = new THREE.MeshBasicMaterial({
                        color: 0xFFFFFF,
                        map: txt //An image of the lookup table that would fit into my uniform.
                    });

                    var frstMesh = new THREE.Mesh(frstGeo, frstMat);
                    frstMesh.position.set(0, 0, 0);

                    frstObj.add(frstMesh);
                    frstScene.add(new THREE.AmbientLight(0xFFFFFF));

                    //PostProcessing

                    frstComposer = new THREE.EffectComposer(frstRenderer);
                    frstComposer.addPass(new THREE.RenderPass(frstScene, frstCam));

                    //This CopyShader is always used as the last pass to avoid setting and checking the renderToScreen state of the different ShaderPasses'
                    var effect = new THREE.ShaderPass(THREE.CopyShader);
                    effect.renderToScreen = true;

                    frstComposer.addPass(effect);

                    frstComposer.render();` 

Using this code I receive the correct image of the lookup table I'm using cropped into the canvas' container (a simple div-Element).

After adding some ShaderPasses into this first EffectComposer to alter the lookup table, I try to 'export' this texture by creating a new texture according to the canvas the EffectComposer rendered to.

`
function TestComposerTransition(composerOne, composerTwo) {

    var firstOutput = document.getElementById("CanvasOne");

    var tmpTxt = new THREE.Texture(firstOutput);
    tmpTxt.needsUpdate = true;

    //Clone the shaders' uniforms;
    shader = THREE.ColorLookupShader;
    shader.uniforms = THREE.UniformsUtils.clone(shader.uniforms);
    var effect = new THREE.ShaderPass(shader);

    //Add the shader-specific uniforms;
    effect.uniforms['tColorCube0'].value = TextureCache[0].texture; //Set to default LUT;
    effect.uniforms['tColorCube1'].value = tmpTxt;
    effect.uniforms['mixAmount'].value = 1;

    composerTwo.passes[composerTwo.passes.length - 1] = effect;

    var displayEffect = new THREE.ShaderPass(THREE.CopyShader);
    displayEffect.renderToScreen = true;
    composerTwo.insertPass(displayEffect, composerTwo.passes.length); //Add the copyShader as the last effect in Order to be able to display the image with all shaders active;

    composerTwo.render();
}
`

I then re-use this texture as a uniform in my `composerTwo` but unfortunately, instead of the correct altered image, I'm receiving [an altered, but heavily distorted version of this image.](http://imgur.com/a/dGZK8)

#### Conclusion:

As my first question regarding this issue got deleted pretty quickly, I also posted my question [here](http://www.html5gamedevs.com/topic/27318-threejs-webglrendertargettexture-as-uniform/) and [here](http://stackoverflow.com/questions/41271770/effectcomposer-access-the-image-created-by-the-composer) and haven't got any replies what so ever. After all the additional googleing, reading the three sourcecode and documentation I came to the conclusion that this could be a bug, because I don't know what to try out next. 

I already tried to change the renderers size to the correct size of the lookup table, without getting a different result.

If there are any more informations needed to resolve this issue, please let me know!

<br><br>
Best regards and a healthy start into the New Year,

Michael

##### Three.js version
- [X] r82

##### Browser
- [X] Chromium(NW.js)

##### OS
- [x] All of them

**Comment by WestLangley** [comment]
>Can't use a Texture created from a Canvas as a uniform

Yes you can.

>I came to the conclusion that this could be a bug, because I don't know what to try out next.

A three.js bug? I don't think so.

If I were to guess, I'd conjecture you are dealing with a mipmapping issue.

If you are not getting help on stackoverflow or elsewhere, try asking a simpler question and provide a link to a live example. Sometimes that helps.

**Comment by mchlr** [comment]
Thanks for the input, I'll check it out.

Regards,

Michael
