### ISSUE TITLE
Pinched TubeGeometry - getTangent() bug

### ISSUE THREAD

**Issue by wansco** [mrdoob/three.js#10483]
##### Description of the problem 
I am seeing an odd behavior in the tubegeometry with very specific lengths in one case a length of 3058 and 200 segments, but I'm sure I've seen this with other length combinations. Its pretty rare. The end result is the end of the tube looks flattened (pictures below).

I've tracked this down to a potential bug around line 256 of Curve.js, or at least that is where it is manifesting. Basically if pt1 & pt2 are equal in getTangent(), the tangent at that point will be 0,0,0, which causes problems with the trig functions.  This causes points to be drawn on one side or the other, instead of distributed around in a circle.

How pt1 & pt2 are the same is still a mystery. In getTangent(), t=0.985 is the magic number for this specific case. For anything greater than about 0.974, getPoint() returns the same point value. I am using a catmullrom spline with the tension set to zero (or very low). I also experienced this issue with my own curve implementation consisting of very simple line segments and a pretty straightforward lerp.

I identified this condition by adding a sanity check at line 256 of Curve.js:
if(pt1.equals(pt2)...
I'm not sure what a fix would be at this point. Increasing the delta to expand the search for different points works, but is very clunky. Ultimately there is some resolution issue with getTangent() that is jamming things up.

![flattendtube](https://cloud.githubusercontent.com/assets/2752282/21559202/ab982430-cdfc-11e6-8a9a-0e59c95a4ed6.png)

![flattendtube-wireframe](https://cloud.githubusercontent.com/assets/2752282/21559210/cfd6fa7e-cdfc-11e6-9682-e6a6cea99e12.png)

##### Three.js version

- [ ] Dev
- [x] r83
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
> For anything greater than about 0.974, getPoint() returns the same point value. I am using a catmullrom spline with the tension set to zero (or very low). I also experienced this issue with my own curve implementation consisting of very simple line segments and a pretty straightforward lerp.

Clearly, that would be a problem when estimating derivatives.

Can you provide the two test cases (jsfiddle) so we can reproduce your results? Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/.github/CONTRIBUTING.md). `dev` branch would be best.

**Comment by wansco** [comment]
jsfiddle:
http://jsfiddle.net/s6eorfnz/1/

There are 2 commented lines in there.

Line 204 - this adds one more vertex and the issue goes away

Line 215 - this is interesting. The pinched part moves away from the end. I haven't investigated this.

**Comment by wansco** [comment]
And another one using a much simpler "custom" curve (rather than the spline):
http://jsfiddle.net/s6eorfnz/2/

**Comment by wansco** [comment]
Well, it looks like this one is on me.... I didn't realize that my last 2 points were the same, which explains why the same behavior was present in 2 completely different getPoint() implementations.

This is still a case that might be dealt with on line 256 of Curve.js:
if(pt1.equals(pt2)
  console.error("Points overlap, tubegeometry may not display correctly");

Hopefully this thread will be useful to someone down the road.
