### ISSUE TITLE
threejs.live

### ISSUE THREAD

**Issue by ekatzenstein** [mrdoob/three.js#10481]
This probably isn't the best place to post, but I'm an idiot when it comes to social media. Building off of the set of example files and other projects like the html editor, I made a site so that users can interact with example files in-session: [threejs.live
](http://threejs.live)
Just wanted to share with the devs. Let me know if you have any feedback or questions. Thanks.

**Comment by Mugen87** [comment]
Cool! And i do like the usage of React. Great lib! :wink:

One little thing: If i change the examples over the side menu, i'm getting extremely high frame-rates with my Chromium. So the first example 60 fps, second examples 120 fps, third 180 fps and so on. The browser crashed when the example `webgl_camera` was rendered with over 600 fps. :stuck_out_tongue_winking_eye: :boom:

![image](https://cloud.githubusercontent.com/assets/12612165/21545853/00d8ce62-cddb-11e6-8c14-09cbb6110961.png)




Tested with Ubuntu 16.04 LTS.

**Comment by ekatzenstein** [comment]
Yikes! Thanks for the heads up. Was able to replicate, issue's been opened here: https://github.com/ekatzenstein/three.js-live/issues/1

**Comment by ekatzenstein** [comment]
resolved: https://github.com/ekatzenstein/three.js-live/issues/1

**Comment by ekatzenstein** [comment]
[[resolved now]](https://github.com/ekatzenstein/three.js-live/issues/1)

**Comment by Mugen87** [comment]
Much better :wink: !

**Comment by looeee** [comment]
This is a really great upgrade to the current example page - both the design and the functionality. Well done! 😁 

Perhaps with a little more work (in particular making it work on mobile), could this replace the current page at some point? The live coding feature would be a huge benefit.

**Comment by ekatzenstein** [comment]
Just updated to r84. @mrdoob the build is pretty straightforward, so I'd be happy to port into the site.  Let me know if you're interested.

**Comment by mrdoob** [comment]
I really like the idea of being able to see the code and also edit it.

However, I think requiring react-redux, react-router, create-react-app, create-react-app-sass, material-ui, ... just for that is a bit of over-engineering.

https://threejs.org/examples/ produces 5 requests and transfers 50KB (loads in ~600ms).
http://threejs.live/ produces 14 requests and transfers 260KB (loads in ~6s). 

We definitely need codemirror, but apart from that, I think we can achieve the same result with ~50 more lines of code inside index.html.

**Comment by mrdoob** [comment]
This is also an issue... https://github.com/ekatzenstein/three.js-live/issues/2

**Comment by ekatzenstein** [comment]
@mrdoob Makes sense. The hash issue is because I'm deploying with github pages and can't use browser history from what I understand. I agree on the over engineering - these are new technologies I've learned so I wanted to use them in a smaller project. I think react still has value here, but the additional libraries aren't essential.

**Comment by Mugen87** [comment]
For further discussions: https://discourse.threejs.org/t/threejs-live-official-examples-with-live-code-editing/129

**Comment by Mugen87** [comment]
@ekatzenstein Any chances you update `threejs.live` to `R90`? 

[Recently](https://github.com/mrdoob/three.js/issues/11579#issuecomment-366971254), a user thought that `threejs.live` is the latest list of examples. I know you've added a note on your page that refers to the official website. But unfortunately, one can easily overlook this link.
