### ISSUE TITLE
Box3.setFromObject showing incorrect coordinates

### ISSUE THREAD

**Issue by jextrevor** [mrdoob/three.js#10499]
##### Description of the problem 
When using Box3.setFromObject(object), the min and max values generated do not match the bounding box, and are instead very odd and specific values of around ±14.8, with a long string of decimals attached. Interestingly enough, these numbers are different every time, but they are the same for every bounding box computed.

##### Three.js version
I am using Three.JS revision 81.

##### Browser
Chromium

##### OS
Ubuntu MATE 16.10

##### Hardware Requirements (graphics card, VR Device, ...)
Intel Integrated Graphics, specifically Intel HD Graphics 3000.

**Comment by Mugen87** [comment]
Can you provide a [fiddle](https://jsfiddle.net/) that shows the bug? Also try using `three.js` R83...

**Comment by jextrevor** [comment]
Using R83 has no effect. I'm going to work on the fiddle, though it may take some time to reproduce the error I'm experiencing.

**Comment by looeee** [comment]
@jextrevor any update on the fiddle?

**Comment by jextrevor** [comment]
No update on the fiddle, I've been really busy the past few days. Will close until someone can reproduce.
