### ISSUE TITLE
doc: TextGeometry missing bevelSegments parameter

### ISSUE THREAD

**Issue by andreasplesch** [mrdoob/three.js#10493]
##### Description of the problem 

https://threejs.org/docs/index.html#Reference/Geometries/TextGeometry

does not list the bevelSegments parameter though in fact it is supported as TextGeometry uses ExtrudeGeometry.

This is probably due to the fact that 
https://github.com/mrdoob/three.js/blob/master/src/geometries/TextGeometry.js

does not explicitly include bevelSegments as part of the documentation comment.

##### Three.js version

- [ ] master

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by looeee** [comment]
@andreasplesch if you like you can edit the docs to add this.

**Comment by andreasplesch** [comment]
Yes, it would make for more complete documentation. The default is the default for ExtrudeGeometry which is 3. There is no strict upper limit though values above ca. 10 (100?) are rarely required and lead to extreme triangle densities and aspect ratios. This is perhaps why the parameter was not advertised ?

**Comment by looeee** [comment]
More likely it's an accidental omission.
