### ISSUE TITLE
doc: ShapePath only in dev

### ISSUE THREAD

**Issue by andreasplesch** [mrdoob/three.js#10492]
##### Description of the problem 

https://threejs.org/docs/index.html#Reference/Extras.Core/ShapePath links to 

https://github.com/mrdoob/three.js/blob/master/src/extras/core/ShapePath.js

but ShapePath.js is not in the master branch => 404

##### Three.js version

- [ ] master

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

doc

##### related issues

#10237

**Comment by Mugen87** [comment]
This can be closed now...
