### ISSUE TITLE
house.wrl VRML example file problems

### ISSUE THREAD

**Issue by andreasplesch** [mrdoob/three.js#10502]
##### Description of the problem 

https://github.com/mrdoob/three.js/blob/dev/examples/models/vrml/house.wrl

has 7 errors and

https://github.com/mrdoob/three.js/blob/a92f447d8a9190c8d118bae9baac63d122a96ea1/examples/models/vrml/house.wrl

has 45 errors when validated by Chisel ( http://www2.hrp.no/vr/tools/chisel/install.htm ).

The first error rof the dev version is at line 1902: "not a valid field for Transform"

https://github.com/mrdoob/three.js/blob/dev/examples/models/vrml/house.wrl#L1902

It looks like the children field is missing for the enclosing transform.

I noticed because cobweb ( http://titania.create3000.de/cobweb/ ) - a capable VRML browser - reported the same problem with the dev file.

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

none

##### related

#10290

**Comment by andreasplesch** [comment]
https://github.com/andreasplesch/three.js/blob/wrl/examples/models/vrml/house.wrl is fixed up file which validates, is nicely indented and has ROUTEs (animations) working. Since there are many duplicate DEFs (presumably from fused inlines) some behaviours are confused but overall this should be a better text case. Can PR it if desired.

**Comment by mrdoob** [comment]
> Can PR it if desired.

Yes please!
