### ISSUE TITLE
Normal shader incorrectly applies gamma/pre-multipledAlpha to encoded normals

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#10506]
##### Description of the problem 

The normal shader currently allows for encodings and pre-multipled alpha in the fragment shader here:

https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderLib/normal_frag.glsl#L34

I am not sure it is useful to allow for these encodings or pre-multiplied alpha as usually one wants to be able to decode exactly the normal when reading from this buffer -- any encoding or alpha-premultiplicate is likely not to be wanted because it needs to be compensated for when decoding.  In particular the encoding is very problematic as I've noticed that it gamma corrects the normal when writing it to the buffer if WebGLRenderer.gammaOutput is set.  This really messes things up - the normal is then decoded slightly incorrect.

I've just modified my branch of Three.JS to remove both pre-multiplied alpha and encoding from the normal shader.  I'd recommend we do the same to mainline Three.js if @WestLangley agrees.

/ping @WestLangley 

##### Three.js version

- [x] Dev
- [x] r82

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by WestLangley** [comment]
I think your proposed change makes sense.
