### ISSUE TITLE
ideas for bevel

### ISSUE THREAD

**Issue by andreasplesch** [mrdoob/three.js#10503]
This is an issue intended to accumulate and document ideas for the bevel feature of ExtrudeGeometry. 
As such it is closed until use cases or implementation arise. This may never happen because the feature is rarely used, and models typically are generated outside of Three.js . However, the option to enhance dynamic text may be considered as useful.

##### Description of the problem 

Bevel inflates the extrusion but a 'beveled' edge typically refers to an edge where the corner is cut off. This requires a scene designer to intentionally take into account the sizes which are added by BevelThickness and BevelSize. 

In addition, the roundness of the bevel is fixed as elliptical and cannot be modified. A BevelShape parameter is proposed which adjusts the shape from completely straight (or even concave) to elliptical to rectangular.

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by andreasplesch** [comment]
Bevel maintaining amount and size

Currently, the vertices for the extrusion are constructed from the back to the front. The bevel starts at -thickness for z, grows to full size at z=0, then the inflated curve is extruded by amount, and the front bevel goes back to regular size at z=amount+ thickness.

Instead, the bevel should start at z=0 with a curve contracted by size, grow to regular curve at z=thickness, then the curve is extruded by amount-2*thickness, and the front bevel goes to contracted size at z=amount.

Currently, calcBevVec () returns the outward translation vector. In order to use it for inward translation, it should be only necessary to flip the order of input points.

The other implementation changes should be trivial.

The main problem is the intended change in behavior itself because it is by definition backwards incompatible.

Another option bevelExpansion, true by default, could help by allowing a choice between the current and the new but often expected behavior.

**Comment by andreasplesch** [comment]
bevelShape option to control roundness of bevel 

It should be possible to replace the sin and cos functions with slightly more sophisticated math to control the shape of the bevel. Needs more research but could be really straightforward to implement.

**Comment by andreasplesch** [comment]
Just using pow(cos, n) should work well.

n=1 regular, elliptical shape
n=2 straight line
n=0.1 almost right angle
n>2 concave

![screenshot_2017-01-05-00-31-36](https://cloud.githubusercontent.com/assets/6171115/21670093/65f87c12-d2df-11e6-8ec3-af7618402cfe.png)

**Comment by andreasplesch** [comment]
https://rawgit.com/andreasplesch/three.js/ff7643b34313a8ccfe6b3bb4d1a25c034da7cf93/docs/index.html#Reference/Geometries/ExtrudeGeometry

uses a first implementation of bevelShape from the bevel branch of my fork.

It works as intended, and could be useful. I will adjust the text examples to see how it looks for text as well. The scalloping, concave bevel looks also useful.

I will also change the scaling of the parameter. I think it should be the negative exponent to a base of 2. Then negative values would be concave, 0 the current, circular default, 1 straight, and positive towards a corner. It also would be symmetric, eg. -3 would have the same curvature as +3.

**Comment by andreasplesch** [comment]
https://rawgit.com/andreasplesch/three.js/b19ae46a67e5eda9ac5787282b7ed78587d8381b/docs/index.html#Reference/Geometries/ExtrudeGeometry

uses better scaling for bevelShape.  n = 2^(1-shape). Definitely preferred. 0: straight, 1: default (circular), positive: convex, negative: concave . Definitely preferred.

**Comment by andreasplesch** [comment]
https://rawgit.com/andreasplesch/three.js/fb6b3fddfb76a55f309688ee75226599927a9432/docs/index.html#Reference/Geometries/TextGeometry

shows the effect on TextGeometry. It is subtle for the intended range between 1 (current) and 2, but dramatic for the scalloping with negative values.

**Comment by Mugen87** [comment]
It's great that you are working on some enhancements for the bevel logic! Interestingly there is some kind of open issue in this area:

Currently the bevel implementation is placed into `ExtrudeGeometry` which is not the best solution at all. I think it would be much nicer if we had something like a generic `BevelModifier` which can be applied on any kind of geometries. This solution would be more versatile and it would be easier to create `BufferGeometry` ports of  `ExtrudeGeometry` and `TextGeometry`.

I don't know a specific implementation of a `BevelModifier` like in Blender but i would support any kind of attempts for creating one. 

@andreasplesch What do you think about this idea?

**Comment by andreasplesch** [comment]
I think I found most of the github discussion on bevels after I opened and closed this issue and have some sense of the history and questions. 

Generally, I agree with the notion that Three is not a modelling tool, and complicated geometries should be generated (perhaps dynamically) in another tool/library. But ...

After I saw 'BevelModifier', my first reaction was a 'how ambitious' since generalizing might mean covering lots of corner cases and such. Though sometimes it just means coming up with a smarter solution. It certainly is another category of effort than trying to improve the existing logic.

If Blender has a BevelModifier, I would probably go and try to find out how it works first.

Then, another viable solution would be to try to adapt the ExtrudeGeometry bevel approach to other geometries. 

There the first question is how to identify which edges to bevel: all which are more acute than a threshold ? (This would allow surfaces composed of triangulated, flat polygons).

Then, the bevel behaviour probably needs to be to cut into a body rather than expand out. So, I would first try to modify the current extrudeGeometry bevel to that effect, see above.

Thinking about that and concretely which direction at the beveled edge between two neighbouring polygons of a general geometry would correspond to what is currently the z direction (extrusion direction), it seems unlikely that a lot of the current implementation could be reused. Back to blender or research.

For that it is useful to have thought about the problem in advance.

``` 
--------+-------
     A  |  B
```
A|B is an edge which needs to beveled.
Let's say we an find out which direction is 'to inside' from the winding orders (normals).
``` 
--------+-------
    A| s|s |B
```
s is the size of the bevel: how to measure ? Probably better to define a bevel depth d, eg. how deep the bevel would cut into the edge. d would be measure along the bisector of the two polygons (triangles).

Lets just consider a straight bevel first.

The complication is where multiple edges meet

``` 
--------+-------
    A| s|s |B
     |  |  | 
______  |  ______
   s    |   s   
--------+-------
    C| s|s |D
```
So, similar to the current getBevVec one can find the point where two retracted edges meet.

What if the A|C should not be beveled (but A|B should) ? Getting complicated but at least I have an appreciation of the problems. It looks like all edges need to be beveled once you start with one.

Is that what you in had in mind when suggestion bevel for general geometries ?

It looks like I will for now continue to look for (much) lower hanging fruits.

**Comment by andreasplesch** [comment]
https://github.com/BlenderVR/blender/blob/master/source/blender/bmesh/tools/bmesh_bevel.c

is the main code responsible for bevels in blender. Pretty daunting to me but could perhaps be ported (not by me as it would take forever). It uses super-ellipses for bevel profiles similar to what I have done, nice.

**Comment by Mugen87** [comment]
Indeed, complex code. I'm still looking for a more lean implementation with that covers only the most important basic features. Maybe the comparison with the bevel modifier of `Blender` was a little bit too ambitious 😉 .

**Comment by Mugen87** [comment]
> It looks like I will for now continue to look for (much) lower hanging fruits.

👍

**Comment by andreasplesch** [comment]
Starting as basic as possible is a good idea. The main and perhaps only feature to substantially reduce is the bevel profile. To a straight line.

Let's also consider only triangulated surfaces.

For each triangle we need to construct a new, smaller triangle with retracted edges.

Retract only edges which are between triangles at acute angles below threshold. Leave alone edges between coplanar triangles, obtuse angles and convex angles (?), and also border edges.

Find good offset for retraction based on bevel size: constant for each retracted edge in a given triangle.

Intersect/expand all retracted edges and unmodified edges to find vertices of  new triangle.

After all triangles are contracted, build bevel faces.

Connect the now split edges to a rectangle.

Leaves holes in corners. Since holes probably not planar, add retracted corner point. Retraction direction could be average normal of all participants. Retraction depth just bevel size ? Or 0, after all, just use original corner point.

Build triangular faces of corner pyramid.

Something like this may work for a start which then can be improved.

**Comment by napter** [comment]
Was this ever addressed? I am trying to use bevel but the fact that it is increasing the size of my geometry is causing a problem. Is there a way to bevel without inflating the extrusion but simply cuts\rounds the corner off? Thanks

**Comment by Mugen87** [comment]
> Was this ever addressed?

No. The bevel implementation has not changed so far.

**Comment by napter** [comment]
@andreasplesch I will take a look. To your point that ThreeJS isn't a modeling tool. I guess I am using it as one because I am using it to extrude paths into 3D objects. Is there a more appropriate javascript tool you are aware of that can extrude paths to 3D and bevel? Thank you!

**Comment by andreasplesch** [comment]
Clara.io comes to mind. But this is getting off topic and out of scope.

**Comment by andreasplesch** [comment]
#14233 has code for a cutting bevel.

**Comment by napter** [comment]
@andreasplesch #14233 looks like it is working perfectly, thank you!
