### ISSUE TITLE
code editor autoscrolling is annoying

### ISSUE THREAD

**Issue by v1nce** [mrdoob/three.js#10518]
When you edit a line, the editor scolls so that the edited line is the last displayed on screen. This is really annoying.
eg : the editor is showing lines : 50 to 100. You edit line 60 => the editor scrolls to show lines 20 to 60 

I don't know the version of three.js that is used.I used the online editor à https://threejs.org/editor/

tested on chrome/ubuntu

**Comment by Mugen87** [comment]
I can confirm this behavior. The mentioned PR should resolve this problem...

**Comment by Mugen87** [comment]
This can be closed now. It is fixed in `dev`...
