### ISSUE TITLE
image.crossOrigin Not being set

### ISSUE THREAD

**Issue by pacey** [mrdoob/three.js#10511]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
When I set the crossOrigin property on my texture loader it looks like it doesn't actually get set in the image object in the underlying ImageLoader e.g.
```
textureLoader = new THREE.TextureLoader()
textureLoader.setCrossOrigin('imgix.com')
const texture = textureLoader.load(imageUrl)
```

The cross origin property then gets set on the image, but upon inspection the property has the value `anonymous`:
![image](https://cloud.githubusercontent.com/assets/3204561/21684045/f81daa80-d353-11e6-9d93-94b859c39919.png)
![image](https://cloud.githubusercontent.com/assets/3204561/21683778/c9516be8-d352-11e6-8d2d-cb0aa8a85163.png)

And the Origin header does not have the correct value:
![image](https://cloud.githubusercontent.com/assets/3204561/21683929/74fcdc66-d353-11e6-9825-4f161bcce684.png)

##### Three.js version

- [ ] Dev
- [x] r83
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [] IOS
- [x] Mac

##### Hardware Requirements (graphics card, VR Device, ...)

edit: adding extra screenshot to show the crossOrigin property on the loader was set to what I wanted.

**Comment by Mugen87** [comment]
If you set `image.crossOrigin` to `true`, the value gets automatically converted to `true`.

See: https://jsfiddle.net/ud5eLhzh/1/

What `origin` header value do you expect? Isn't `localhost` correct?

**Comment by pacey** [comment]
I was looking for a way to set the `origin` header to a different value (one that our CDN expects to return the `access-control-allow-origin` header).

I thought by setting the `image.crossOrigin` property to a string it would set the `origin` header, but it looks like that is not the case!
