### ISSUE TITLE
ExtrudeGeometry: Customize bevel profile

### ISSUE THREAD

**Issue by andreasplesch** [mrdoob/three.js#10521]
##### Description of the problem 

This is more a possible enhancement than a problem. Currently, the profile of beveled edges in ExtrudeGeometries or TextGeometries is fixed as elliptical (after a fix #9372), or as straight by setting bevelSegments to 1. It would be nice (though rarely essential) to be able to customize the degree and sense of curvature of the bevel profile, by an additional parameter. The default setting of this parameter would ensure full backward compatibility.

##### Possible solution

It turns out it is possible to generalize the current method of calculating the profile of a bevel to accommodate such a bevelRoundness or bevelShape parameter. This only requires a few lines of code for some math.
Here is the result applied to the TextGeometry doc page:

custom:
![image](https://cloud.githubusercontent.com/assets/6171115/21727709/9c021174-d410-11e6-8aa2-6cc09bb2cd12.png)

default = current:
![image](https://cloud.githubusercontent.com/assets/6171115/21727676/65baafa4-d410-11e6-9d18-55d659a5adc1.png)

scalloped custom:
![image](https://cloud.githubusercontent.com/assets/6171115/21727770/de557124-d410-11e6-9f00-0ad0be2f27f7.png)

live: https://rawgit.com/andreasplesch/three.js/fb6b3fddfb76a55f309688ee75226599927a9432/docs/index.html#Reference/Geometries/TextGeometry

 (enable bevel and play with bevelShape)

for a fuller explanation see #10503 
##### Three.js version

- [x] Dev
- [x] r82
- [x] Bevel: https://github.com/andreasplesch/three.js/blob/bevel/src/geometries/ExtrudeGeometry.js#L474

##### Browser

- [x] All of them
- [x] Chrome
- [x] Firefox
- [x] Internet Explorer

##### OS

- [x] All of them
- [x] Windows
- [x] Linux
- [x] Android
- [x] IOS

##### related

#10503, #10160, #9372, #323

**Comment by Mugen87** [comment]
Since `ExtrudeGeometry` is already the most complex geometry generator, it's probably better to keep it as it is and avoid adding more use cases. Especially since this feature was not frequently requested over the last three years. Hence, I suggest to close this issue.

**Comment by andreasplesch** [comment]
This is a chicken and egg problem but I agree. In fact, bevel should perhaps be removed completely.
