### ISSUE TITLE
Hello mrdoob - What are some ThreeJS Editor Expansion areas ..

### ISSUE THREAD

**Issue by Seagat2011** [mrdoob/three.js#10520]
Hi mrdoob, on January 20th I will be recommending that my software team work on the ThreeJS editor as part of the 2017 Global Game Jam, for our Jam site at Fitchburg State University. There may be as many as 40 software engineers, 2d- and  3d Artists-- all working together under the Creative Commons v4 license.

Are there any areas, you wish us to focus on (I've already fixed a few ;)

Here are some features which I am focusing ..

1. Menubar.File.js  - Downloads more than 1 file at a time (FIXED): With the following code:

a = setInterval(function(){
  if(files.length){
    savestring( JSON_stringify( files[0]._blob ), files[0]._name);
    files.shift();
  }
  else{
    clearInterval(a);
  }
}, 150)

2. An inference engine for the js physics (engines) library, capable of matching user spline paths to available scripts with library.

3. An XML-inspired trace editor which infers code based on user-generated call-graphs (stack traces), eg: 

WebGL.Context.2D.Font.FontStyle.Text;("24 pt Calibri");
WebGL.Context.2D.Font.FillStyle.Text;("greeni");
WebGL.Context.2D.Font.Position.posX.float;( 70 );
WebGL.Context.2D.Font.Position.posY.float;( 70 );
WebGL.Context.2D.Font.FillText.Text;("Hello World! My first WebGL!");

..infers that the project requires an HTML canvas, using a 2d context. Only the necessary libraries (and Properties!) will be imported, iff desired, for lean gl. All of this will be performed visually, of course :)

4. Incorporate a scriptable physics, sound, lighting and mechanics engines, based on user-generated 3-d space hand traces, etc

5. Revert from app.json to project.json -- where Project.json includes only the "names" and file-extensions of the files necessary to import the project. In this way, afterwards, projects remain hand-editable and also extensible.

6. More codemirror themes ..

7. And much much more .. !

**Comment by tentone** [comment]
@Seagat2011 

Hi there, im actually working on something that might just be what you are asking for on my nunuStudio repository!

**Comment by looeee** [comment]
There is one thing that needs doing - I updated a large amount of the docs in the last release (and there are quite a few updates pending for the next release too), however given that it's the work of one person there are almost certainly quite a few errors and omissions. It would be amazing to have a second set of eyes go over it. 

Another thing that is so far largely missing from the docs and needs adding is expected ranges for parameters in constructors - three.js doesn't give warnings when unexpected values are given which can be an annoying and hard to pin down source of errors for people new to the library.

**Comment by webprofusion-chrisc** [comment]
Other fun/useful things to add: 
- FX Layers: it would be great to be able to add configurable layers of composite FX such as Depth of Field etc
- Ability to set a single Environment map and have all materials use it by default
- Edit for texture 'map' wrapping and offset (like https://github.com/jeromeetienne/threejs-inspector )
- Preset example lighting setups such as a studio 3-point lighting system

**Comment by Seagat2011** [comment]
Great! Thanx guys. I've seen the TODO page and I'll also look into the specs for the unfinished loaders.

@tentone : Ok, tentone, will look into
