### ISSUE TITLE
Rigged Simple glTF model does not animate (r83 or later)

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#10527]
##### Description of the problem 

I tried to display the Rigged Simple glTF model with the latest version of Three.js + glTF Loader, but I noticed that it was no longer animated.

https://cx20.github.io/gltf-test/examples/threejs/index.html?model=RiggedSimple&scale=0.2

The following error is displayed on the console.
```
three.js:36368
    can not bind to objectName of node, undefined 
        PropertyBinding
            getValue: ()
            node: Bone
            parsedPath: Object
            path: "Bone.001.scale"
            rootNode: Scene
            setValue: ()
            __proto__: Object
    bind @ three.js:36368
 :
```
This model has to animate as follows.
<img src="https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/1.0/RiggedSimple/screenshot/screenshot.gif"></img>

Three.js r82 + glTF Loader is OK
http://jsdo.it/cx20/gnom

Three.js r83 + glTF Loader is NG
http://jsdo.it/cx20/KyIp

##### Three.js version

- [x] Dev
- [x] r83
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by takahirox** [comment]
Probably it's not glTF specific issue, but Three.js animation system issue #10366

**Comment by donmccurdy** [comment]
This issue is now fixed.
