### ISSUE TITLE
Split repo into Core, Docs, Editor and Examples

### ISSUE THREAD

**Issue by webprofusion-chrisc** [mrdoob/three.js#10525]
##### Description of the problem 
The current three.js repo is large and can takes hours to clone on a standard broadband connection (depending on github etc).  I propose that the repo be split into discrete sections for the Core library, Docs, Editor and Examples. It may also be necessary for an 'organisation' to be created in github to contain the repos.

##### Three.js version

- [x ] Dev
- [ ] r82
- [ ] ...

**Comment by looeee** [comment]
I have far less than what I'd consider broadband at the moment and it recently took me about an hour to clone the repo. You should only need to do this rarely though and updates won't take long so I don't think this is a good enough reason to split the repo.

**Comment by webprofusion-chrisc** [comment]
@looee no, you're right bandwidth shouldn't be only motivation. However the discreet components to the project should be in their own repo regardless. The 1MB threejs core library does not need a 756MB repo - that's the space currently used on my disk for the clone I did yesterday. 

I wonder how many casual contributors could have updated docs or made minor changes but gave up when they lost interest during cloning?

**Comment by looeee** [comment]
You don't need to clone the repo to update the docs - there's an edit button in the top right of each page.

**Comment by Mugen87** [comment]
I also think that maintaining a single repo is hard enough. With this in mind, the big repo size is an acceptable drawback.
