### ISSUE TITLE
Transparent Geometry() objects not always transparent

### ISSUE THREAD

**Issue by paulmasson** [mrdoob/three.js#10523]
I have an unanswered [question](http://stackoverflow.com/questions/41475545/three-js-transparent-objects-from-geometry-occluding-others) on StackOverflow (in case there's a simple answer), but I think there might be a problem with the WebGL renderer.

When creating a scene with multiple transparent objects, I'm finding that objects created using Geometry() are sometimes not transparent but occlude other transparent objects. This doesn't happen when creating objects from geometries like BoxGeometry or SphereGeometry.

I can copy the code over here as well if you want. Here's a live [example](http://paulmasson.github.io/test.htm) of the code using r80. Updating to r83 doesn't change anything. The issue exists since at least r70.

##### Three.js version

- [ ] Dev
- [ ] r82
- [x] r80

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
What happens if you create the geometries with `BufferGeometry` instead?

**Comment by paulmasson** [comment]
@Mugen87 no difference in behavior: http://paulmasson.github.io/test_buffer.htm

**Comment by WestLangley** [comment]
Please use stackoverflow for help.

**Comment by paulmasson** [comment]
Already tried that to no avail.
