### ISSUE TITLE
Box Animated glTF model changes size as it rotates (r83 or Later)

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#10528]
##### Description of the problem 

I tried to display the Box Animated glTF model with the latest version of Three.js + glTF Loader, However, it seems that animation movement is not correct.
https://cx20.github.io/gltf-test/examples/threejs/index.html?model=BoxAnimated&scale=0.5

Three.js r82 + glTF Loader is OK
http://jsdo.it/cx20/gnrt
![image](https://cloud.githubusercontent.com/assets/1833979/21748755/7447cac2-d5d0-11e6-8505-f3c3e8ebc166.png)

Three.js r83 (or Later) + glTF Loader is NG
http://jsdo.it/cx20/iT08
![image](https://cloud.githubusercontent.com/assets/1833979/21748768/a7959256-d5d0-11e6-9079-9167417a7696.png)

This model has to animate as follows.
<img src="https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/1.0/BoxAnimated/screenshot/screenshot.gif"></img>

##### Three.js version

- [x] Dev
- [x] r83
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by takahirox** [comment]
I've confirmed this bug and figured out how to fix.
I'll make PR soon.

The root issue is here in `GLTFLoader`

https://github.com/mrdoob/three.js/blob/d8e8e579699492534b56aa2a763cd45beecb3a86/examples/js/loaders/GLTFLoader.js#L274

It always generates `KeyframeTrack` regardless to data type but
it should generate proper keyframe track instance corresponding to data type.
(eg. `QuaternionKeyframeTrack` for quaterinon)

**Comment by cx20** [comment]
I confirmed the fix and updated the following status :)
https://github.com/cx20/gltf-test
