### ISSUE TITLE
Request for more useful EdgesGeometry treatment of PlaneGeometry

### ISSUE THREAD

**Issue by unphased** [mrdoob/three.js#10531]
##### Description of the problem 
Feature request for EdgesGeometry used with PlaneGeometry to draw "segment boxes" based on the third and fourth args of PlaneGeometry ctor, instead of just one set of 4 outline lines. 

##### Three.js version

- [ ] Dev
- [x] r79
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

I understand that I can easily write a loop to assemble some LineSegment geometry to do what I want. I was just hoping I could get this for free. :P

**Comment by WestLangley** [comment]
`EdgesGeometry` must accept an arbitrary geometry. We can't make `PlaneGeometry` a special case.

You can create a grid like so:
``` javascript
var grid = new THREE.GridHelper( 1, 4, 0xffffff, 0xffffff ); // square
grid.scale.set( 10, 1, 20 ); // rectangular
scene.add( grid );
```

**Comment by unphased** [comment]
Makes sense. Does it merge coplanar triangles?
