### ISSUE TITLE
autoClear or preserveDrawingBuffer has no effect

### ISSUE THREAD

**Issue by cybafelo** [mrdoob/three.js#10538]
##### Description of the problem 

WebGLRenderer.autoClear = false / true; does nothing, renderer gets auto cleared always
WebGLRenderer.preserveDrawingBuffer = true / false; also does nothing, renderer gets autocleared always

##### Three.js version

- [Master, Dev]
- [r76, r77, etc. up until now] - did not try older revs

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [x] IOS

**Comment by looeee** [comment]
I've just tested both and they are working for me.

To see the effect of preserveDrawingBuffer change the value on line 67 here: http://threejs.live/#/webgl_trails

To see the effect of autoClear change the value on line 95 here:
http://threejs.live/#/webgl_lines_colors

If you are submitting an issue in future or want more help with this you should provide an example using something like JSFiddle or Codepen.

**Comment by WestLangley** [comment]
Please use stackoverflow for help.
