### ISSUE TITLE
MaterialShader with clip

### ISSUE THREAD

**Issue by rwirz** [mrdoob/three.js#10533]
Hi,

How works the clip feature with shader material?

I tried to do an example and I obtained this:
![untitled](https://cloud.githubusercontent.com/assets/8203181/21755550/58f9dd40-d5db-11e6-9065-08da77509cad.png)

The green sphere is clipped and it is using Phong material.
The blue sphere is using the shader material but it is not working.

The shader material is defined as:

var materialShader = new THREE.ShaderMaterial({
				    uniforms: {
				        color: { type: 'f', value: 1.0 }
				    },
                    side: THREE.DoubleSide,
                    clipping: true,
				    clippingPlanes: [localPlane],
				    vertexShader: document.
                                  getElementById('vertShader').text,
				    fragmentShader: document.
                                  getElementById('fragShader').text
				});

The shaders are the basic.

Where is the error?

Thanks

**Comment by WestLangley** [comment]
You must include the propper clipping logic in your vertex/fragment shaders.

Study the `THREE.ShaderChunk`s.
