### ISSUE TITLE
Zooming limit in trackball controls

### ISSUE THREAD

**Issue by Ashajoney** [mrdoob/three.js#10537]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Three.js version

- [ ] Dev
- [x] r70
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

Do trackball controls limits zooming in and out?

As I zoom in and out of the object,object breaks at some point.

I want to limit zooming in and out parameters as in orbit controls.

I dont want to use orbit controls in my case.

Thanks a bundle.

**Comment by WestLangley** [comment]
>Do trackball controls limits zooming in and out?

Yes.

**Comment by Ashajoney** [comment]
How can we do it?
I tried using .minDistance and .maxDistance properties but it fails to do
my wish.
