### ISSUE TITLE
canvas_materials_video not working on iOS 10.2

### ISSUE THREAD

**Issue by fthiery** [mrdoob/three.js#10542]
##### Description of the problem 

The demo here just displays a black frame instead of playing the video
https://threejs.org/examples/canvas_materials_video.html

Framerate drops to 4 frames per second, but nothing gets displayed.

##### Three.js version

- [ ] Dev
- [X] r83 (from threejs.org website)

##### Browser

- [X] Chrome 55.0.2883.79
- [X] Safari
- [X] Firefox 5.3
- [X] Probably all browsers

##### OS

- [X] IOS 10.2

##### Hardware Requirements (graphics card, VR Device, ...)

iPad Air A1474

**Comment by fthiery** [comment]
For what it's worth, this does work:
http://bfred-it.github.io/iphone-inline-video/demo/threejs.html

**Comment by Mugen87** [comment]
Does this problem still occur with the latest `three.js` version?

**Comment by Mugen87** [comment]
Closing. If the problem still exists, we can reopen the issue.
