### ISSUE TITLE
Device Orientation example and Moto X Play (no gyroscope)

### ISSUE THREAD

**Issue by iwersen** [mrdoob/three.js#10541]
Hi,

   I'm checking the device orientation example at https://threejs.org/examples/#css3d_panorama_deviceorientation using a Moto X Play cellphone. 

   I can see the bridge when moving the cellphone, but the image is constantly "shaking". Suppose you are checking the example page during an earthquake.

   This cellphone doesn't have a gyroscope but it has an accelerometer. Is that the reason?

Thanks

**Comment by Mugen87** [comment]
> This cellphone doesn't have a gyroscope but it has an accelerometer. Is that the reason?

I think so. Looks like Google Cardboard also not working on your phone...

https://www.reddit.com/r/Android/comments/3hzu9v/the_moto_x_play_is_missing_some_sensors_for/

**Comment by looeee** [comment]
I can confirm the issue with my Moto G which also lacks a gyroscope (no Google Cardboard for me 😢).
However the example does kind of work - when I move my phone the view does seem to rotate as desired, except for the extreme shakiness. 

Are the DeviceOrientationControls supposed to work with just an accelerometer? Or do they need both accelerometer and gyroscope to work? 
If it's the latter I agree that this issue should be closed.

**Comment by looeee** [comment]
https://threejs.org/examples/?#misc_controls_deviceorientation works with the same issue - it seems more like the sensitivity is set way too high rather than that it is not working. Or that there needs to be some kind of easing function applied to the movement. 

Can somebody with a device that does have a gyroscope check these examples?

**Comment by Mugen87** [comment]
With my Pixel (which has a gyroscope) the examples run very smooth.

**Comment by mrdoob** [comment]
Tested on a pixel too. Kind of laggy actually... I guess they aren't using the daydream stuff on that api yet.
