### ISSUE TITLE
documentation: Polyfills is 404 and Lut is not up to date

### ISSUE THREAD

**Issue by jonathanlurie** [mrdoob/three.js#10550]
In the doc, the Polyfills page [https://threejs.org/docs/index.html#Developer_Reference/Polyfills/Polyfills](https://threejs.org/docs/index.html#Developer_Reference/Polyfills/Polyfills) throws a 404.

Also, https://threejs.org/docs/index.html#Examples/Plugins/LookupTable mentions the methods setminV and setmaxV while the actual methods are named setMin and setMax.

Not really a big deal, just noticed.

**Comment by looeee** [comment]
Fixed the polyfill link here: #10554

If you come across minor errors in the docs like the LUT page feel free to click the "edit" button in the top right and fix them yourself :)

**Comment by jonathanlurie** [comment]
@looeee Oh right! I didn't know i could do it! Thanks!
