### ISSUE TITLE
iOS - THREE.DeviceOrientationControls initial heading/alpha fix for camera?

### ISSUE THREAD

**Issue by code-matt** [mrdoob/three.js#10552]
iOS for whatever reason sets the devices North or 0 to whatever direction the device is facing when the app/webpage loads. I am working on an app that requires the Three camera's heading to be real world accurate. 

I am using the THREE.DeviceOrientationControls which is flawless except for this issue :/ https://github.com/mrdoob/three.js/blob/master/examples/js/controls/DeviceOrientationControls.js

I tried: https://github.com/mrdoob/three.js/pull/4577

I have seen this iOS fix method elsewhere with other JS controls. It DOES correct the camera being real world correct heading no matter what direction the device is pointed when it loads up. However, it always breaks the cameras in the same way. Tilting the device in portrait mode as if you were going to look up at the sky or down at the ground will cause the scene to spin out of control and it causes crazy jitters at all times otherwise.

- [x ] r83
- [x ] IOS

Any help or ideas would be much appreciated. A thought I had: Could the entire Three worldspace be rotated the offset amount instead to counter this? I imagine people must have gotten around this iOS limitation in the past.

On a side note, I like how apple devs were told about this in 2011 and its still a thing.
http://lists.w3.org/Archives/Public/public-geolocation/2011Jul/0014.html

https://developer.apple.com/reference/webkitjs/deviceorientationevent

**Comment by code-matt** [comment]
I think I have it working. Perhaps there is a better way. 

Wait until a non 0 magneticHeading is returned from window.navigator.compass.watchHeading{ which gets passed to controls as new arg. Clear the watchId after.
```
THREE.DeviceOrientationControls = function (object, initialHeading) {
  this.alphaOffsetAngle = initialHeading * (Math.PI / 180)
....
....
    var alpha = this.deviceOrientation.alpha ? THREE.Math.degToRad(this.deviceOrientation.alpha) - this.alphaOffsetAngle : 0;
```

If you log alpha, its getting set to negative values which is weird, isn't it?

**Comment by mrdoob** [comment]
Hmm... Do other browsers support `window.navigator.compass.watchHeading`?

**Comment by code-matt** [comment]
I am using Cordova. Looking into it, I think ```navigator.compass```  might be something a plugin provided for me.

I am guessing deviceOrientation.webkitCompassHeading mentioned in the PR I had in my first message might provide the same thing for Safari though. Android its not a problem because 0 alpha is magnetic North.

**Comment by WestLangley** [comment]
Closing due to age. If there is an issue in a recent three.js revision, please file a new issue.

**Comment by dataexcess** [comment]
hey,

Yes when I'm using DeviceOrientationControls but cancel the permission my camera (controlled by DeviceOrientationControls) is facing downwards (negative y). Why can't the direction be initialised like a normal Object3D would? (positive z).

thnx
