### ISSUE TITLE
Bug: /examples/js/controls/OrbitControls.js:655 event.preventDefault();

### ISSUE THREAD

**Issue by Seagat2011** [mrdoob/three.js#10557]
##### Description of the problem 
This is a bug. preventDefault() cancels other mousedown/select operations (eg. inside dat.gui.min.js client frame )

..A better approach would be to utilize a filter

##### Browser

- [x] All of them

**Comment by WestLangley** [comment]
Did you use this pattern?
```javascript
controls = new THREE.OrbitControls( camera, renderer.domElement );
```

**Comment by Seagat2011** [comment]
Sorry, No

src: https://github.com/josdirksen/learning-threejs/chapter-08/17-load-babylon.html

var orbit = new THREE.OrbitControls(camera);
