### ISSUE TITLE
OrbitControl not working when camera position at 0,0,0

### ISSUE THREAD

**Issue by kgoedecke** [mrdoob/three.js#10561]
##### Description of the problem 
When I try to use OrbitControl just like in the examples provided, it only seems to work when i set ```camera.position``` to something other than 0,0,0. No events are being triggered but when I add ```camera.position.set(0, 0, 10);``` to my code then it suddenly starts to work.

##### Three.js version

- [x] r83

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [x] Linux
- [x] Mac
- [ ] IOS

**Comment by WestLangley** [comment]
You cannot set `controls.target` and `camera.position` to the same value.

**Comment by Mugen87** [comment]
Yep, check out this example as an orientation.

https://jsfiddle.net/c26wef25/4/
