### ISSUE TITLE
Answering questions posted on issue 10541 - Device Orientation example and Moto X Play (no gyroscope)

### ISSUE THREAD

**Issue by iwersen** [mrdoob/three.js#10560]
The issue #10541 was closed before answering some questions. You can close this issue after reading.

Google Maps has 360 degree photo viewer that follows the Moto X Play (no gyroscope) orientation perfectly. The movement is even better when using a device with gyroscope. There is a sample at https://www.google.com.br/maps/place/Eiffel+Tower/@48.8618283,2.2893783,3a,75y,2h,90t/data=!3m8!1e1!3m6!1s-MwhbA1qD1sI%2FV77dOMTA5pI%2FAAAAAAAAFio%2FVkYYHYNFKcAoJKut4DPfpVDR9NQUgDybgCLIB!2e4!3e11!6s%2F%2Flh5.googleusercontent.com%2F-MwhbA1qD1sI%2FV77dOMTA5pI%2FAAAAAAAAFio%2FVkYYHYNFKcAoJKut4DPfpVDR9NQUgDybgCLIB%2Fw234-h106-k-no-pi-6.8333335-ya2.40625-ro0-fo100%2F!7i8704!8i4352!4m5!3m4!1s0x47e66e2964e34e2d:0x8ddca9ee380ef7e0!8m2!3d48.8583701!4d2.2944813!6m1!1e1?hl=en

The bridge sample (https://threejs.org/examples/#css3d_panorama_deviceorientation) also follows the Moto X Play orientation, but the image "shakes" a lot. 

Since a Moto X Play works fine using the Google Maps viewer, I thought the "shaking" problem was a bug or sensitivity adjustment. That's why I've opened the issue #10541.

Additionally:
- Google Play says that Google Cardboard app is "not compatible" with Moto X Play.
- The Facebook app has a 360 degree photo viewer, but it doesn't follow the Moto X Play orientation. I think it disables the device orientation controls because there is no gyroscope.

Thanks

**Comment by looeee** [comment]
I agree that the last issue was closed prematurely - it does look like the device orientation controls could be adapted to work with the Moto G and Moto X as the Google maps link above does work smoothly pretty well on my Moto G (sometimes gets stuck and then swings wildly). 

However I also think it would be perfectly acceptable to decide not to support devices without gyroscopes.

**Comment by mrdoob** [comment]
> The issue #10541 was closed before answering some questions.

Even if the issue was closed you can still continue the conversation. We reopen issues sometimes.

**Comment by mrdoob** [comment]
Also, what @looeee said. I don't think we can easily support devices without gyroscopes. I would argue this should be implemented in the browser layer anyway.
