### ISSUE TITLE
Issue/Bug when using multiple transparent objects in front of each other

### ISSUE THREAD

**Issue by JHellwig** [mrdoob/three.js#10569]
Hello,
I am not sure if this is a bug or just a problem caused by my self, but I am running into a really weird issue using multiple transparent objects in front of each other. I have described my problem on http://stackoverflow.com/questions/40975579/transparent-object-hides-other-transparent-objects-alphatest-dont-works-and-de with some pictures. Till now there was no suggestion that was able to identify the problem here. I hope it is just a problem caused by my self and not a bug, because I would love to see it working.

Thank you for your time and help.

**Comment by bhouston** [comment]
The solution is to implement this: https://github.com/mrdoob/three.js/issues/9977

**Comment by JHellwig** [comment]
Did you already implement this kind of transparency-mode for the renderer in ThreeJS? Or do I have to wait till you finished your work and added it to ThreeJS/ create my own? I am very new to this. Currently adding renderer.transparency = THREE.OrderIndependentTransperancy; does no changes at all.

**Comment by looeee** [comment]
@JHellwig the linked pull request is till marked as "open" which means it has not been added yet.

**Comment by mrdoob** [comment]
> @JHellwig the linked pull request is till marked as "open" which means it has not been added yet. 

It's actually not a pull request, it's an issue with a proposal. Needs to be implemented still.
