### ISSUE TITLE
The diffuse color of glTF model BrainStem.glb is not displayed.

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#10572]
##### Description of the problem 

I tried the latest version of Three.js + glTF Loader, which supports the .glb format.

However, the diffuse color of glTF model BrainStem.glb was not displayed.
https://cx20.github.io/gltf-test/examples/threejs/index.html?category=sampleModels&model=BrainStem&scale=1&type=glTF-Binary

![image](https://cloud.githubusercontent.com/assets/1833979/21936197/a52a5c78-d9f3-11e6-88be-76ab73db8842.png)

The diffuse color of glTF model BrainStem.gltf is displayed.
https://cx20.github.io/gltf-test/examples/threejs/index.html?category=sampleModels&model=BrainStem&scale=1&type=glTF

![image](https://cloud.githubusercontent.com/assets/1833979/21936244/d9a45058-d9f3-11e6-9e6b-c0bd1fa10b39.png)

Since it can be displayed with Babylon.js and other libraries, I think that it is a problem of Three.js + glTF Loader.

##### Three.js version

- [x] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by donmccurdy** [comment]
Thanks! I'll take a look at this next week.
