### ISSUE TITLE
doesn't load texture locally

### ISSUE THREAD

**Issue by MarcoDruetta** [mrdoob/three.js#10571]
##### Description of the problem 
When I try to open a ThreeJS example with a texture i can see it, but if I try to open the same example of version r78 or before il work perfectly.
Thank you

##### Three.js version

- [ ] Dev
- [x] r82
- [x] r81
- [x] r80
- [x] r79
- [ ] r78

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by looeee** [comment]
Are you running a server locally and loading it through that? Or just opening the html file directly? 
You will run into problems if its the latter. See the manual page http://threejs.dev/docs/#Manual/Getting_Started/How_to_run_things_locally for more details. 

If your problem is something else can you provide more details?

**Comment by MarcoDruetta** [comment]
I tried to put the examples folder under IIS and it works but I still have the problem with my website.
It's an Asp.NET web site that writes dinamically the javascript for ThreeJS.
At this link you can find the web site using ThreeJS version r78:
http://213.26.81.69/Default.aspx?DO=NEW&CC=5&MOD=GUARVA01-ANT2
At this linkyou can find the same web site using ThreeJS version r83:
http://213.26.81.70/Default.aspx?DO=NEW&CC=5&MOD=GUARVA01-ANT2
And this is a screenshot of the difference:
![r78 vs r83](https://cloud.githubusercontent.com/assets/25101248/21932524/3e482c76-d9a1-11e6-954b-6be792aa96e5.png)

**Comment by MarcoDruetta** [comment]
Any news?

**Comment by looeee** [comment]
Can you provide a simple example that shows the problem? It will be very hard for anybody to tell whether its a problem in your code or a three.js bug from your examples.

**Comment by looeee** [comment]
Have a look at the https://github.com/mrdoob/three.js/wiki/Migration-Guide as well to see if you need to make any changes in your code.

**Comment by mrdoob** [comment]
This may be related to #10439.

**Comment by Mugen87** [comment]
@MarcoDruetta This problem should be solved. Please use the latest `three.js` version.
