### ISSUE TITLE
.onBeforeRender doesn't work for THREE.Sprite

### ISSUE THREAD

**Issue by TroKEMp** [mrdoob/three.js#10579]
##### Description of the problem 

.onBeforeRender doesn't work for THREE.Sprite. It works fine with THREE.Mesh, but nothing happens for sprites.

##### Three.js version

- [ ] Dev
- [x] r83
- [x] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
I think we need to enhance `THREE.SpritePlugin .render()` to enable this.

**Comment by WestLangley** [comment]
@TroKEMp What is your use case, by the way?
