### ISSUE TITLE
World orientation in examples/misc_controls_pointerlock.html

### ISSUE THREAD

**Issue by mimooh** [mrdoob/three.js#10578]
I would expect that walking takes place on X,Y plane and jumping on Z axis. Am I wrong that world in this example is not oriented as above? Is it on purpose?

**Comment by Mugen87** [comment]
_The following diagram depicts the WebGL coordinate system. The z-axis signifies depth. A positive value of z indicates that the object is near the screen/viewer, whereas a negative value of z indicates that the object is away from the screen. Likewise, a positive value of x indicates that the object is to the right side of the screen and a negative value indicates the object is to the left side. Similarly, positive and negative values of y indicate whether the object is at the top or at the bottom portion of the screen._

![image](https://cloud.githubusercontent.com/assets/12612165/21962804/c08dacae-db2e-11e6-811c-4dd4242b8b2a.png)

Source https://www.tutorialspoint.com/webgl/webgl_basics.htm

**Comment by looeee** [comment]
Also it's worth noting that not all 3D software follows this convention, although I think it is the most common. 3DS Max for example uses Z up, Y into the screen. 

Secondly this is what's known as a "right-handed" system which means that Z+ points towards you, Z- is into the screen. You might come across "left-handed" systems, in which case the Z- points towards you and Z+ is into the screen.

**Comment by mimooh** [comment]
Thanks guys. That makes sense. Pitty though, that there is not just one
convention :( Seems like it is better to reorient all my geometries
instead of modifying this and perhaps other three.js scripts.

-- 
Karol Kreński

**Comment by Mugen87** [comment]
@mimooh This issue can be close.

**Comment by mimooh** [comment]
Sure, I am closing the issue. Thanks for help.
