### ISSUE TITLE
Inconsistent behavior from `SphereGeometry.mergeVertices()` in Safari

### ISSUE THREAD

**Issue by dzhurley** [mrdoob/three.js#10575]
In Safari, use of `mergeVertices()` on `SphereGeometry` with the same parameters is inconsistent. I'm guessing this is somehow related to the rounding and precision of finding keys for the `verticesMap` in the `mergeVertices()`, but I'm unsure what Safari is doing.

Chrome and Firefox work as expected, tested with r81 on OS X.

<img width="886" alt="safari" src="https://cloud.githubusercontent.com/assets/344044/21948784/1b12c350-d9a2-11e6-88a4-6cc435570e6f.png">

**Comment by mrdoob** [comment]
Sounds like rounding errors indeed...
