### ISSUE TITLE
editor: language sensitive popup disappears quickly

### ISSUE THREAD

**Issue by SteveOW** [mrdoob/three.js#10574]
When editing a script on some occasions a popup appears listing valid options, e.g. I type "this.on" and the popup appears with completions such as onError, onLoad, ... etc.

However the popup disappaears in less than 1 second so there is no time to read or select options.

Three.js version: R83 

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [  ] All of them
- [ x ] Opera
- [ x ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ 7 ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

 Hardware Requirements (graphics card, VR Device, ...)
- using laptop keyboard to edit script.

**Comment by Mugen87** [comment]
Can reproduce. I think this happens because the editor reacts on the `change` event and immediately updates the view. The context menu seems to get lost in this process.

**Comment by Mugen87** [comment]
I had a look at this once again. It seems that removing the `refreshScriptEditor` signal and the corresponding [event handler](https://github.com/mrdoob/three.js/blob/dev/editor/js/Script.js#L425-L443) solves the problem.

@mrdoob Do you know why the source code of a script is explicitly set via `codemirror.setValue( script.source )`? The editor still works if you remove or comment out the mentioned event handler code.

**Comment by mrdoob** [comment]
> @mrdoob Do you know why the source code of a script is explicitly set via `codemirror.setValue( script.source )` on each code change? 

That's weird, where does that happen?

**Comment by Mugen87** [comment]
[Here](https://github.com/mrdoob/three.js/blob/dev/editor/js/commands/SetScriptValueCommand.js#L42) and [here](https://github.com/mrdoob/three.js/blob/dev/editor/js/commands/SetScriptValueCommand.js#L51). Looks like the call `this.editor.signals.scriptChanged.dispatch()` should be sufficient in this methods.

**Comment by mrdoob** [comment]
I think so yes. Probably the `scrollInfo` thing isn't needed then?

**Comment by Mugen87** [comment]
Yes. `cursorPosition` is obsolete, too. I've made a PR with the changes. Hope, that should do it
