### ISSUE TITLE
VR Controls for Google Daydream

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#10586]
Google introduced WebVR API in Chrome for Android last month (see [here](https://blog.chromium.org/2016/12/introducing-webvr-api-in-chrome-for.html)). In order to test this cool feature, i've developed a simple prototype with `three.js` 🙌 . As you can see in the source code of the HTML file (it is based on the example `webvr_cubes`), i was able to reuse `VREffect` and `VRControls`. I've just added a new entity called `DaydreamController` to enable interaction via the same-named input device.

The logic of the example is straightforward: You can use the controller to highlight some floating boxes. The visualization of the controller and its orientation is fairly simple, so there is some potential for improvement 😉 

If you want to check out this example, you need a Google Pixel (XL), the Daydream View and Chrome 56 (Beta). The website has an embedded origin trial token, so it's not necessary to enable WebVR in your browser manually.

@mrdoob If you like it i can create a PR with a new example and the `DaydreamController`. Of course the code of this file still needs some refinements.

**[DEMO](https://yume.human-interactive.org/examples/webvr/webvr_daydream.html)**
[DaydreamController.js](https://yume.human-interactive.org/examples/webvr/DaydreamController.js)

**Comment by Mugen87** [comment]
@toji I was not able to request data of the 'App' button in `DaydreamController.js`. Will this feature be available in later versions of Chrome?

BTW: Thanks for WebVR! 😉 👍

**Comment by toji** [comment]
The app button is reserved for use by the browser and will not be exposed to WebVR. Similar restrictions are in place for the Vive and Touch menu buttons.
