### ISSUE TITLE
SVGLoader not working with IE11

### ISSUE THREAD

**Issue by titani22** [mrdoob/three.js#10587]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
SVGLoader does not seem to work with IE11. Nothing gets displayed. I found two online examples. They both work with Chrome and FireFox, not with IE11. Here are the two examples
http://jsfiddle.net/3Lg911vs/4/
http://stackoverflow.com/questions/33140342/how-to-load-svg-file-into-svgrenderer-in-three-js  (click Run Code Snippet, then click Full Page).

After much debugging, I eliminated SVGLoader, loaded the SVG file myself, rendered the image myself, passed the image to three.js, yet the same exact behavior.

##### Three.js version

- [ ] Dev
- [x ] r82
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [ ] Firefox
- [x ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
Maybe you are not in a modern document mode. Please check out this thread for more information

http://stackoverflow.com/questions/27494296/svg-not-showing-in-ie11

**Comment by titani22** [comment]
Thank you. I checked. I am in modern document mode. IE displays 2D SVG files well. It also displays the rendered 2D bitmap image well. Yet when I make that image THREE.MeshBasicMaterial, and paint an object with it, it comes black.

**Comment by mrdoob** [comment]
This may be related to #10439.

**Comment by Mugen87** [comment]
@titani22 Do you still have this problem with R84?

**Comment by Mugen87** [comment]
Closing since the problem should be solved with the latest release. If it still exists, we can reopen the issue.
