### ISSUE TITLE
GLTFLoader sets matrixAutoUpdate to false and never computes the node matrix

### ISSUE THREAD

**Issue by Misterblue** [mrdoob/three.js#10585]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
In GLTFLoader, in `GLTFParser.prototype.loadNodes`, `_node.matrixAutoUpdate` is set to false. The code then sets the nodes position, translation, ... but does not compute the world matrix or set `matrixWorldNeedsUpdate`.

For most of the demos, this is not a problem because either animations are added (which sets `matrixAutoUpdate` to true) or the demo object is at position [0,0,0] so you don't notice the lack of matrix update. 

I don't know enough about Threejs to know what is exactly wrong here, but, if a node is specified and there are no shaders or animations (like using only the common material extensions), nodes get defined with position set but an uncomputed world matrix.

##### Three.js version

- [x] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by takahirox** [comment]
In the latest dev, `_node.matrixAutoUpdate` is set to true(default).

Refer to 

https://github.com/mrdoob/three.js/pull/10536#pullrequestreview-15655297
