### ISSUE TITLE
ThreeJS SubdivisionModifier not subdivide correctly a plane geometry

### ISSUE THREAD

**Issue by JordiGoPython** [mrdoob/three.js#10595]
##### Description of the problem 

i'm trying to subdivide a plane geometry on threeJS using SubdivisionModifie, i did this the last year and it worked fine, but now i updated my threeJS and SubdivisionModifie, and when i try to subdivide my plane geometry give me a different result.

code: 

`
var subdivisions = 4; var modifier = new THREE.SubdivisionModifier( subdivisions ); 
modifier.modify( geometry, subdivisions ); 
geometry.computeFaceNormals(); 
geometry.computeVertexNormals(); 
child.geometry.dispose(); child.geometry = geometry;
`

Before update: https://i.stack.imgur.com/LQ6VV.png
After update: https://i.stack.imgur.com/FFbSM.png

##### Three.js version

- [ ] Dev
- [x] r83
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by zz85** [comment]
@JordiGoPython do you remember what version you used last year? I'm guessing it could be using the Catmull-Clark that works with quads in `SubdivisionModifier`

**Comment by JordiGoPython** [comment]
@zz85 i used r57 version D:

**Comment by WestLangley** [comment]
Closing due to age.

`SubdivisionModifier` is intended to be used with closed models only.
