### ISSUE TITLE
everything looks oversaturated in Chrome 55 (latest)

### ISSUE THREAD

**Issue by netrocc** [mrdoob/three.js#10593]
##### Three.js version

- [x] r83
- [x] r82

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] OS X El Capitan

**Comment by Mugen87** [comment]
I don't have this problem with the same setup. Can you post a screenshot of the visual error? Besides, can you see any error messages or warnings in the browser console?

**Comment by netrocc** [comment]
Chrome Version 55.0.2883.95 (64-bit)

Here is a screenshot of the first online example, animation cloth.

![bildschirmfoto 2017-01-17 um 14 49 37](https://cloud.githubusercontent.com/assets/6792380/22022966/818e49e0-dcc4-11e6-9723-2291cc158585.png)

**Comment by netrocc** [comment]
nothing in the console.. only the usual

`THREE.WebGLRenderer 83`

**Comment by Mugen87** [comment]
Let's see if you have this problem with a non `three.js` application.

http://webglsamples.org/dynamic-cubemap/dynamic-cubemap.html

Same problem?

**Comment by netrocc** [comment]
No, that looks fine.

**Comment by zuspan** [comment]
I have this same issue with many threejs.org examples - running Version 55.0.2883.95 (64-bit) on Mac. And agree - the webglsamples.org site look normal.

**Comment by Mugen87** [comment]
What kind of GPUs are you using?

**Comment by netrocc** [comment]
Tested on 2 iMacs with this graphic cards:
* ATI Radeon HD 5750 1024 MB
* ATI Radeon HD 5670 512 MB

**Comment by netrocc** [comment]
I just figured out that when I set the alpha parameter as option for the renderer the issue goes away.

`var renderer = new THREE.WebGLRenderer({ alpha: true, antialias: true });`

**Comment by WestLangley** [comment]
@netrocc See https://github.com/mrdoob/three.js/issues/9685#issuecomment-271887698

**Comment by netrocc** [comment]
too late lol =)

**Comment by mrdoob** [comment]
#9685
