### ISSUE TITLE
An error in the document page about Three.Line and Three.LineSegment

### ISSUE THREAD

**Issue by shrekshao** [mrdoob/three.js#10596]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

`Three.LineSegments` is using `gl.LINES`
`Three.Line` is using `gl.LINE_STRIP`

The document gets it flipped. 
https://github.com/mrdoob/three.js/blob/master/docs/api/objects/LineSegments.html#L18
https://github.com/mrdoob/three.js/blob/master/docs/api/objects/Line.html#L18

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by looeee** [comment]
Oops! Fixed here #10599

By the way if you come across errors like this in the docs feels free to click the "Edit" button in the top right and make changes yourself.

**Comment by shrekshao** [comment]
Thanks! Got it.
