### ISSUE TITLE
[Feature request] CI Testing examples with screenshots

### ISSUE THREAD

**Issue by NicolasRannou** [mrdoob/three.js#10608]
Hi all,

Did you consider automatically testing examples somehow? In most cases, taking a "screenshot" of an example and comparing it to a reference image should be enough to know if an example is working.

There are many good libraries to compare images out there.
Selenium should help in this matter too.

Did you already attempted to do so or if there is any interest in it?

**Comment by mrdoob** [comment]
@zz85 gave it a go in the past, can't find the relevant PR at the moment.

**Comment by NicolasRannou** [comment]
Thanks @mrdoob it seems to be this one:
https://github.com/mrdoob/three.js/pull/3873

**Comment by NicolasRannou** [comment]
https://github.com/openlayers/openlayers/pull/3470 another ref. that could be useful

**Comment by takahirox** [comment]
I've been thinking similar things.

This tweet thread would help?

https://twitter.com/superhoge/status/809993255391739904

**Comment by cecilemuller** [comment]
+1 for visual tests, they could use Selenium, NW, Electron or SlimerJS, but isn't the limiting factor that it needs to run on a system with a GPU for WebGL ?

e.g. Travis CI can run with XVFB just fine, but doesn't have instances with GPUs as far as I recall, so the tests would have to run on something like the expensive EC2 instances, or merely locally on the dev's computer (but then it's not integrated to Github / doesn't run tests when receiving PRs).

**Comment by NicolasRannou** [comment]
Yes I couldn't say which one is the best approach as they all let you achieve the same things ultimately. (although @cecilemuller has a good point with the GPU requirement. )

Right now there is no continuous integration testings setup in THREEJS it seems so a first step could just be to create snapshots from all examples as part of the testing script and generate a simple webpage that displays the results in a mosaic  (maybe something like the ThreeJS [homepage](https://threejs.org/)) - very much like @zz85 did. (https://github.com/mrdoob/three.js/pull/3873)

Then we can make it smarter and add image comparaison things.

Of course such an approach anyway will not catch small issues but would give a good hint is an example is totally broken or not...

**Comment by cecilemuller** [comment]
I'll prepare a PR for it this week-end: at minimum we can have tests that devs can run locally on their computer, and later we can see what services could run them in the cloud (because Github integration would be handy).

**Comment by cecilemuller** [comment]
Not a PR, but as a starting point, here's a Selenium suite that uses ChromeDriver to make a screenshot of every example: https://github.com/wildpeaks/threejs-examples-screenshots

However a lot of examples have animations, so it wouldn't be enough to compare with a reference screenshot given the objects might be in a different positions than expected (without being an error).

It would be better to make test scenes specifically made for taking screenshots, and then it can also test additional things that unit tests wouldn't catch, e.g. interactions given webdriver can automate things like clicking buttons, keyboard input or mouse events.

**Comment by NicolasRannou** [comment]
Interesting approach to use Protractor - I thought is was tightly coupled with Angular.
I think even that might already be good enough - maybe take a couple of screenshots per example to catch animations.

Which would be your "testing workflow" @mrdoob? Just quick visual inspection of all examples or do you go into details of some examples, depending on new features being added?

**Comment by cecilemuller** [comment]
I used to think so about Protractor too, but fortunately it can also be used with non-Angular pages (especially being a React/Preact person myself 😃) and is convenient to delegate setting up the webdrivers, plus it seems well maintained.

**Comment by mrdoob** [comment]
> Which would be your "testing workflow" @mrdoob? Just quick visual inspection of all examples or do you go into details of some examples, depending on new features being added?

I try not to rely on testing. I push myself to not to merge things blindly and try to think of the consequences of every change as much as I can. It's obviously impossible some times, so I have a quick go at all the examples before releasing.

**Comment by Mugen87** [comment]
Let's tackle this feature request here: #16941
