### ISSUE TITLE
Exporting a normal map from blender to three.js scene format results in bumpMap, bumpScale instead of normalMap, normalScale

### ISSUE THREAD

**Issue by edsilv** [mrdoob/three.js#10602]
I _think_ this is a bug report so qualifies as a github issue. Apologies if not.

I posted it on SO a while back, but haven't had any replies.

http://stackoverflow.com/questions/41466698/how-to-export-normalmap-instead-of-bumpmap-with-three-js-blender-plugin

**Comment by gelibolue** [comment]
I thought it was a bug at first too. Then i found out it was a blender thing. 
Texture->Image Sampling->Normal Map checkbox toggles between bump and normal map if 
Influence->Normal is selected.

**Comment by edsilv** [comment]
Ah, brilliant - many thanks!
