### ISSUE TITLE
Editor as a stand-alone project?

### ISSUE THREAD

**Issue by onekiloparsec** [mrdoob/three.js#10610]
A 2-cents idea: it would be wonderful to contribute to the Editor as a dedicated project.

**Comment by cecilemuller** [comment]
It could be wrapped as standalone using [Electron](http://electron.atom.io) or [NW](https://nwjs.io) (Electron is much more popular, although Electron has issues with Web Workers, and NW uses a more recent version of Node and Chromium).

**Comment by cecilemuller** [comment]
Crazy idea, it could also be an extension for an existing editor, such as Visual Studio Code or Atom, then it could be convenient to use Code/Atom for the script parts and the Editor for model tweaking parts ? That would be harder than just wrapping as standalone though.

**Comment by onekiloparsec** [comment]
Thanks, but I am not talking about packaging (which is obviously possible). My title should have been clearer: I mean Editor as a stand-alone GitHub repo/project.

**Comment by mrdoob** [comment]
The reason I'm hesitant about moving it to its own repo would be that it would increase the maintaining requirements (which is something I'm already struggling about). I can also see it getting easily "out of sync". Right now it evolves in sync with the library.

**Comment by NetOperatorWibby** [comment]
Hmm, that makes sense. I'm currently using the editor in a project and have to manually copy files and update paths. Not that big a deal but I see the value in both arguments.

**Comment by jpryne** [comment]
As it stands, the editor is largely useless, as it is broken with any version of THREE from the last year or so. It's actually a source of confusion, teaching us how things used to work, but not how the library currently works.

**Comment by mrdoob** [comment]
> As it stands, the editor is largely useless, as it is broken with any version of THREE from the last year or so. 

Could you elaborate?

> It's actually a source of confusion, teaching us how things used to work, but not how the library currently works.

Please, elaborate on that too.

**Comment by jpryne** [comment]
My mistake. Seemed like just yesterday it was still defaulting to version 57 or so. I see now it's showing version 84. Lots of things are different between the two, hence the confusion I was referring to. While we're here, I'd say one majorly frustrating issue with the editor is when an infinite loop is created simply by editing the text in a loop condition. There's no way to cancel the loop! If you haven't saved, your code is lost.

**Comment by Mugen87** [comment]
As @mrdoob said: https://github.com/mrdoob/three.js/issues/10610#issuecomment-274066109

**Comment by cecilemuller** [comment]
Just in case someone stumbles on this issue from a search, there is someone working on a standalone editor for three.js: https://twitter.com/ArthurShefer/status/854847174953246720

**Comment by mrdoob** [comment]
And there is also http://nunustudio.org/
