### ISSUE TITLE
Loading a texture in THREE.js using Node

### ISSUE THREAD

**Issue by gnikoloff** [mrdoob/three.js#10616]
I am trying to build a messenger bot which does some image processing in 3d and returns a brand new image. I use THREE.CanvasRenderer and my app is hosted on Heroku.

When a user /POSTs an attachment to my webhook, I want to take the URL of the newly created image and insert it into my 3d Scene.

This is my code (using the node-canvas library):

    const addTexture = (imageUrl) => {
        
        request({
            uri: imageUrl,
            method: 'GET'
        }, (err, res, body) => {
            let image = new Canvas.Image();
            image.src = body;
            mesh.material.map = new THREE.Texture(image);
            mesh.material.needsUpdate = true;
        });
    }

The callback gets run and I can actually `console.log()` the image's contents, but nothing shows up in the scene - the plane I am supposed to render to just gets black without any errors... What am I missing here?

I also tried several other ways, without any success...

I tried using `THREE.TextureLoader` and patch it with jsdom (mock `document`, `window`) and `node-xmlhttprequest`, but then there is error with my `load` event (event.target is not defined...) Just like [in this example][1]

 How should one approach this problem? I have a `url` generated by Facebook, I want to download the image from it and place it in my scene?

  [1]: http://stackoverflow.com/questions/32919875/node-js-three-js-load-texture-on-cube

##### Three.js version

- [ ] Dev
- [ ] r82
- [x] THREE.CanvasRenderer 83

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by makc** [comment]
you may be running into [this issue](https://github.com/Automattic/node-canvas/issues/730#issuecomment-216044872)

**Comment by makc** [comment]
copy-pasting from my project,
```javascript
// http://stackoverflow.com/a/14855016/2207790
var loadTextureHTTP = function (url, callback) {
  require('request')({
    method: 'GET', url: url, encoding: null
  }, function(error, response, body) {
    if(error) throw error;

    var image = new Image;
    image.src = body;

    var texture = new THREE.Texture(image);
    texture.needsUpdate = true;

    if (callback) callback(texture);
  });
};
```
pretty much same code you have, except encoding = null
