### ISSUE TITLE
Broken Links on "Creating Text Page"

### ISSUE THREAD

**Issue by codypearce** [mrdoob/three.js#10611]
##### Description of the problem 
On https://threejs.org/docs/#Manual/Introduction/Creating_Text, the first example in section 2.  [Civilian Casualties in Afghanistan](http://plumegraph.org/) leads to a parked domain, and the http://typeface.neocracy.org/fonts.html link in section 4 leads to a 404

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by looeee** [comment]
This should be fixed now - the page still needs some work but broken links are gone at least.

**Comment by mrdoob** [comment]
Seems like the link has changed too... https://threejs.org/docs/#Manual/Getting_Started/Creating_Text
