### ISSUE TITLE
RectAreaLight Documentation

### ISSUE THREAD

**Issue by sam-g-steel** [mrdoob/three.js#10618]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
".isRectAreaLight" doc refers to spotlight instead of Rect Area

> [.isRectAreaLight](https://threejs.org/docs/index.html?q=rec#Reference/Lights/RectAreaLight)
> ------------------
> Used to check whether this or derived classes are **spot lights**. Default is true.
> You should not change this, as it used internally for optimisation.

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Hmm... If only we could hide those...

**Comment by looeee** [comment]
Yeah... I had some reservations as to whether to document these or not, but in the end I figured that everything visible to the user (except for _privateVariables) should be documented. 

If you think the wording should be changed though it wouldn't be too much effort. 

As a side note, ```Object.AssignProperties``` is used very minimally throughout the code (mainly just for IDs) - would it be a good idea use it for more properties that can't be changed without breaking things? Such as ```isXxx```, ```Material.lights``` and so on.

If things are defined that way (with ```writable``` and ```configurable``` set to false) then I think it would be OK to leave them out of the docs.

**Comment by looeee** [comment]
Fixed: #10622 

By the way @sam-g-steel  if you come across errors like this in the docs feel free to fix them yourself 😄

**Comment by sam-g-steel** [comment]
Absolutely, I saw it and just logged a ticket so I didn't forget... I was
going to submit a pull request but I got pulled a way from the computer.

Thanks

**Comment by jesseazueta** [comment]
Hey everyone, so just to be clear as of right now we can't hide the visibility of the area lights while allowing them to continue to emit light?
