### ISSUE TITLE
object self shadow 

### ISSUE THREAD

**Issue by alaprajz** [mrdoob/three.js#10612]
the ownshadow is unvisible. Could anybody help me?

...
renderer.shadowMapEnabled = true;
renderer.shadowMapSoft = true;

renderer.shadowCameraNear = 3;
renderer.shadowCameraFar = camera.far;
renderer.shadowCameraFov = 50;

renderer.shadowMapBias = 0.39;
renderer.shadowMapDarkness = 0.5;
renderer.shadowMapWidth = 1024;
renderer.shadowMapHeight = 1024;
...

var directionalLight = new THREE.DirectionalLight( 0xffffff, 0.5 );
directionalLight.isDirectionalLight= true;
directionalLight.position.set(1,1,0);
directionalLight.castShadow = true;
directionalLight.shadowDarkness = 0.5;
directionalLight.shadowMapSoft = true;
directionalLight.shadowMapWidth = 1024;
directionalLight.shadowMapHeight = 1024;
directionalLight.shadowCameraRight     =  5;
directionalLight.shadowCameraLeft     = -5;
directionalLight.shadowCameraTop      =  5;
directionalLight.shadowCameraBottom   = -5;

scene.add( directionalLight );

...
object.castShadow = true;
object.receiveShadow = true;
...

##### Three.js version

- [ ] Dev
- [ ] r82
- [x] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by takahirox** [comment]
Hi, I'll advice you to ask it at stackoverflow https://stackoverflow.com/
