### ISSUE TITLE
sketchup exports obj files with hierarchy

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#10628]
you won't believe your eyes but:

![screen shot 2017-01-23 at 2 47 41](https://cloud.githubusercontent.com/assets/242577/22188559/b95a0ee4-e116-11e6-83df-64db5ddf999e.png)

**Comment by mrdoob** [comment]
You mean that it uses `g` instead of `o`?

**Comment by makc** [comment]
at least one of 3js obj loaders at some point used g and o interchangeably so who cares. what matters is that it's possible to reconstruct hierarchy from what is following the g. the question is, what happens if the names have spaces in them?

**Comment by makc** [comment]
I will probably have to implement this. Also I will need the option to infer geometry pivot there... would you be interested in PR like that?

**Comment by mrdoob** [comment]
How do you infer the pivot?

**Comment by makc** [comment]
by the bbox. obviously it's just a guess, that's why I say "optional"

**Comment by mrdoob** [comment]
Why don't you export to collada instead?

**Comment by makc** [comment]
Idk, size, I guess. that's what they use in their site.

**Comment by makc** [comment]
ok, so on my sides of things, I did post-parsing loop that re-names and re-parents meshes; with that, I don't need to change the parser -> closing.
