### ISSUE TITLE
Wireframe indices update

### ISSUE THREAD

**Issue by martinRenou** [mrdoob/three.js#10638]
Hi everybody,

I have trouble with wireframe display, here is my use case:

- Creation of myBufferGeometry and myMaterial, then myMesh
- myMaterial.wireframe = true; (Here it works fine)
- Then I update the geometry with: myBufferGeometry.copy(newGeometry)

(The newGeometry have not the same number of triangles)

Then indices to display segments for wireframe seems to not been updated, because there's display issues.

Is there a way to update the wireframe indices? I can't find where it is computed in the source code.

Martin

**Comment by martinRenou** [comment]
I could create my own WireframeGeometry every time I update the geometry... But I don't like it because I assume wireframe indices are already computed (can't find where, but I is, because we can display with wireframe with material.wireframe = true, am I right?) and I don't want to do it twice as I have a big amount of data to display.

**Comment by takahirox** [comment]
Hi, I'll advice you to ask it at stackoverflow http://stackoverflow.com/ because here is not a help site.
Please post here after you make sure the issue you're facing is bug or 
you need feature request to solve it.

(About your issue, maybe `myBufferGeometry.index.needsUpdate = true`? anyways...)

**Comment by martinRenou** [comment]
Hi @takahirox thanks for your answer,
I'm sorry but it really sounds like a bug.. Updating the geometry shouldn't create a bug when we try to display with wireframe.
I have a webgl issue "glDrawElements: attempt to access out of range vertices in attribute 0", meaning that the segments indices for wireframe are not updated when I update the geometry (here, the new geometry have less vertices, that's why there is an out of range error).

```Javascript
let myGeometry = new THREE.BufferGeometry();
... (compute buffer attributes)
myGeometry.addAttribute(myCustomAttribute);
myGeometry.addAttribute(positionAttribute);
myGeometry.setIndex(indexAttribute);

myMaterial = new THREE.ShaderMaterial();
... (compute shaders)

myMesh = new THREE.Mesh(myGeometry, myMaterial);
```

After that, my mesh is displayed properly with triangle primitives.

```Javascript
myMesh.material.wireframe = true;
```

Here my mesh is properly displayed with line primitives. Then I update the geometry.

```Javascript
let newGeometry = new THREE.BufferGeometry();
... (compute buffer attributes)
newGeometry.addAttribute(newCustomAttribute);
newGeometry.addAttribute(newPositionAttribute);
newGeometry.setIndex(newIndexAttribute);

// Update the geometry
myMesh.geometry.copy(newGeometry);
```

Then my mesh is not displayed, and I have this webgl error (in the case which the new geometry have less triangles). For the case which the new geometry have more triangles, it is displayed with wireframe but the displayed mesh have holes (because there is a lack of line indices).
Btw, your fix does not work, because it is not indices that define triangles which must be updated, but indices that defines the wireframe mesh (lines).

Maybe I'm missing something? Maybe i'm not using material.wireframe properly, and I should create my own WireframeGeometry?

**Comment by takahirox** [comment]
Can you make an example on https://jsfiddle.net/ ?
(Refer to http://jsfiddle.net/hw9rcLL8/)

**Comment by Mugen87** [comment]
`material. wireframe` and `WireframeGeometry` are some two different things. You can always show a wireframe of your 3D objects via `material. wireframe` = `true`.

You use `WireframeGeometry` if you want to normally render your material but also want to visualize the wireframe. 

See this example: http://jsfiddle.net/hfj7gm6t/2952/

If you update the geometry of your 3D object, you have to re-create `WireframeGeometry`.

**Comment by martinRenou** [comment]
@Mugen87 Ok, I understand that.

But here is my issue:
https://jsfiddle.net/martinRenou/7c5joqpo/5/

It will update the geometry after 5 seconds, you can try the two use cases (update with more triangles, update with less triangles). The issue is that segment indices to display wireframe are not updated.

Is it now clear that it's an issue ? Or am I misunderstanding what material.wireframe = true should do?

**Comment by Mugen87** [comment]
This is a fixed version of your code (check out the last line of `updateGeom`): https://jsfiddle.net/7c5joqpo/7/

If you create a new geometry object, you need to **assign** the value to the mesh. If you want to change an existing geometry, you have to directly change the attributes in `BufferGeometry` like in this example http://stackoverflow.com/questions/16804705/modify-vertices-in-a-three-buffergeometry-object

**Comment by martinRenou** [comment]
Oh ok, thank you so much.

But I don't really understand why updating the old geometry doesn't work. If you think that's not an issue, then it's ok for me to close this.

**Comment by Mugen87** [comment]
If you use the `copy` method in this way, the renderer does not recognize that geometry data has changed. So i think it's better to use the `copy` method before you create your 3D objects because it's not intended to replace data at render time.

**Comment by Mugen87** [comment]
> If you think that's not an issue, then it's ok for me to close this.

Not sure about this. Let's see, what others say...

**Comment by martinRenou** [comment]
In fact, I now remember why I first decided to use the `copy` method instead of re-assign a new geometry. That's because I have multiple meshes that point to the same geometry. So if I want to re-assign the new geometry, I should do it to every meshes that point to this geometry, which is not a solution that I like because I have a lot of meshes with multiple geometries...

However, from what you said, I understand that it's the renderer that compute the indices that permits to display webgl lines when wireframe is set to true, is it?
Meaning that if the geometry change, the renderer should re-compute lines indices?

**Comment by martinRenou** [comment]
Ok so like you said, it's the renderer that compute new indices for wireframe in `getWireframeAttribute` function of WebGLObjects.js

I suppose that it's where the magic is: (line 193)

```Javascript
if ( property.wireframe !== undefined ) {
    return property.wireframe;
}
```

As I already compute wireframe indices on my geometry, I suppose that property.wireframe is not undefined. So I think we should check if the position attribute array still have the same length.

```Javascript
if ( property.wireframe !== undefined && 
    property.wireframe.length/2 == geometry.attributes.position.array/3 ) {
    return property.wireframe;
}
```

This fix the issue (I tried it quickly) but I don't know if there is a better way to do it as I don't really know ThreeJS code...

**Comment by mrdoob** [comment]
> Meaning that if the geometry change, the renderer should re-compute lines indices?

That's correct 👍

> This fix the issue (I tried it quickly) but I don't know if there is a better way to do it as I don't really know ThreeJS code...

That may work. Do you mind creating a Pull Request with the fix?

**Comment by martinRenou** [comment]
@mrdoob thanks,
#10696

**Comment by jee7** [comment]
I have the same problem. In my case I am updating only the indices of a `BufferGeometry` object. I want to debug if the code is working correctly and see the wireframe. As I'm updating every frame, creating new `WireframeGeometry` objects seems like a big overhead... maybe if there was some way to update it?

http://jsfiddle.net/01e3mb9h/

See the left cube is changing. The middle `wireframe: true` is stuck in some (first?) configuration. The right `WireframeGeometry` shows only the state, when it was initially created.

**Comment by Mugen87** [comment]
I think #15198 would solve this issue, right?

**Comment by jee7** [comment]
Was that merged (the PR is closed)? I have this problem with r106.
It looks like the same problem, yes, but I can't try the fix in your JSFiddle there.

**Comment by Mugen87** [comment]
I've closed the PR due to the lack of interest. However, I think it's worth to reopen it.

**Comment by Mugen87** [comment]
@jee7 Should be solved with the next release (`R107`) at the end of the month. 👍
