### ISSUE TITLE
Eslint errors

### ISSUE THREAD

**Issue by cecilemuller** [mrdoob/three.js#10646]
##### Description of the problem 

`eslint src` (or `npm run lint`) currently shows "1069 problems (1036 errors, 33 warnings)".

Beyond fixing those, it would also be good to automatically run the linter on push and pull requests to catch future linting errors early, e.g. using Travis CI (the config is straightforward, I could send a pull request for it) which integrates well with Github and is free for open source.

##### Three.js version

- [x] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

None

**Comment by mrdoob** [comment]
Unfortunately there are exceptions to the code style sometimes. I would prefer not to go down this path.

**Comment by cecilemuller** [comment]
Alright, I'll close it then. Perhaps you want to remove the eslint settings then ?

**Comment by mrdoob** [comment]
> Perhaps you want to remove the eslint settings then ?

Well, I'm finding it handy (and sometimes annoying) in Atom showing warnings.
