### ISSUE TITLE
Editor vertex/edge/face editing?

### ISSUE THREAD

**Issue by cellman1234** [mrdoob/three.js#10642]
Hey Mr. Doob, just want to say: This is an amazing lib!  Would it be possible to add vertex editing support for the three.js editor? (i.e. dragging individual vertices around to make custom meshes) Thanks!

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by mrdoob** [comment]
Hmm, I'm hesitant about implementing that. I think doing that would open a huge can of worms. I think I would prefer keeping it as scene editor only (just like Unity3d and Unreal...)

**Comment by makc** [comment]
maybe make a system where they can add plugins of some sort. as long as it is simpler than forking the editor.

**Comment by makc** [comment]
for example, jsfiddle like style, the code saved to local storage, they can edit/reload, grab some code from gist

**Comment by Mugen87** [comment]
As @mrdoob said, it's more sensible when the editor acts as a scene editor like in other engines.

**Comment by rafaelcastrocouto** [comment]
I'm not marketing but if someone else ends up in here searching for a model editor,
I suggest https://www.vectary.com ... it can export GBL and has great plugins.
