### ISSUE TITLE
If cache is enabled, FileLoader should not make duplicate requests.

### ISSUE THREAD

**Issue by ngokevin** [mrdoob/three.js#10644]
##### Description of the problem 

Given the code below, only one request should be fired.

```js
THREE.Cache.enabled = true
var fileLoader = new THREE.FileLoader();
fileLoader.load('foo.jpg');  // A
fileLoader.load('foo.jpg');  // B
```

1. `A` checks the cache and sees no pending requests.
2. `A` makes the request and stores the pending request in the cache as a Promise. The Promise will resolve the file.
3. `B` checks the cache and sees a pending request. `B` waits for the Promise to resolve the file.
4. The request finishes, and the Promise resolves.
5. `A` and `B`, both waiting on the Promise, triggers their callbacks at the same time with the same file response.

I'd like to volunteer to work on this. In A-Frame, we often have been having to maintain a cache of promises to prevent duplicate requests. If it sounds reasonable, below are several possible implementations:

1. Change THREE.Cache to store promises that resolve files, rather than directly storing files. I think this is the optimal solution because requests will always be asynchronous. This is sort of a breaking change, but three.js applications don't often enable the cache, or don't care about the internals of the cache.

2. Create a separate cache object (`RequestCache`) for pending requests. The current Cache stays intact, but there is more logic to maintain both the pending and complete caches.

3. Keep the pending request cache internal to the FileLoader. It'll just be a variable `var requestCache = {}`.

We'd also need a Promise polyfill. They're less than 1KB gzipped if that sounds fine.

##### Three.js version

- [x] Dev
- [x] r84

##### Browser

- [x] All of them

##### OS

- [x] All of them

##### Hardware Requirements (graphics card, VR Device, ...)

N/A

**Comment by takahirox** [comment]
Maybe related PR #10149

**Comment by takahirox** [comment]
@mrdoob
I wanna let it go ahead.

Currently we have two ideas to prevent duplicate requests.
- Using Promise (this thread)
- #10149 (conflicts now tho)

Which do you prefer?
Or is there any concerns?

**Comment by vladgaidukov** [comment]
@takahirox 
#10149 conflicts resolved

**Comment by takahirox** [comment]
@mrdoob 

Would you share your concerns about those approaches with us (again)?

**Comment by Mugen87** [comment]
I know it's a bit late but i vote for a `Promise` based solution and @ngokevin's first implementation approach 😊.
