### ISSUE TITLE
RawShaderMaterial: apparently appends a few uniforms

### ISSUE THREAD

**Issue by backspaces** [mrdoob/three.js#10653]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
The documentation for RawShaderMaterial states that no uniforms or attributes are automatically appended to the shaders. But webgl_buffergeometry_instancing.html appears to have 

> uniform mat4 modelViewMatrix;
> uniform mat4 projectionMatrix;

.. without including them in the uniforms object:
> uniforms: {
> time: { value: 1.0 },
> sineTime: { value: 1.0 }
> },

Is this just a documentation issue? I *like* the idea, just confused.

##### Three.js version

- [ ] Dev
- [ ] r82
- [x] r84

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Mac OS Sierra
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Year old iMac

**Comment by backspaces** [comment]
Let me be clear: I think the uniforms are great and quite sensible, just would like to see a dead-simple ShaderMaterial & RawShaderMaterial demo, especially highlighting their subtleties/advantages. The demo should be dynamic in that one or more buffers should change, animating a very simple geometry, maybe just a triangle.

**Comment by WestLangley** [comment]
@backspaces Why not code a one-triangle example yourself, and post on stackoverflow if you need help?

**Comment by backspaces** [comment]
You shamed me into it! http://backspaces.net/temp/shader0.html
I'll use this as a platform to try indexed & instanced & a large number.
