### ISSUE TITLE
EffectComposer/WebGLMultiRenderTarget flaw?

### ISSUE THREAD

**Issue by wothke** [mrdoob/three.js#10651]
##### Description of the problem 
Based on THREE.WebGLMultiRenderTarget (apparently not part of R84 but I found it in dev81) I implemented a render pass that creates a result texture as well as some kind of depth map. The idea is to then use those 2 results in some subsequent postprocessing pass. see my current test example here: https://www.wothke.ch/multitest/

I suspect that some patches are needed in THREE.EffectComposer to make sure those WebGLMultiRenderTarget attachments actually get propagated. Before I added a respective quickfix in my local version I got a nasty flicker due to the fact that the expected attachment was only available in the originally input WebGLMultiRenderTarget - but not in the clone created within EffectComposer. 

I don't know if the WebGLMultiRenderTarget feature is something you intend to release in the future. If that's the case, then you might want to have a look at EffectComposer..

##### Three.js version

- [x ] 81dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

requires 'WEBGL_draw_buffers' extension

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
`THREE.WebGLMultiRenderTarget`? Doesn't ring a bell...

**Comment by wothke** [comment]
found it here: http://edankwan.com/tests/threejs-multi-render-target/webgl_mrt.html (I had thought that the used "three.min.js" was some regular dev release version.. but maybe it isn't)

**Comment by Mugen87** [comment]
Refactoring `EffectComposer` or post processing passes can be reconsidered when #16390 lands.

**Comment by wothke** [comment]
the Kronos idiots destroyed the original semantics of the WEBGL_draw_buffers API anyway so I guess I don't care anymore..
