### ISSUE TITLE
logarithmicDepthBuffer causes shader compile errors on Firefox for Android

### ISSUE THREAD

**Issue by fraguada** [mrdoob/three.js#10664]
##### Description of the problem 
Hello!  Today I detected a problem on Firefox for Android 50.1.0 and Firefox for Android 51 Beta.  If I switch on `renderer.capabilities.logarithmicDepthBuffer= true;` the scene fails to load due to a shader compilation error.  [Here is a gist](https://gist.github.com/fraguada/fd8ddd03a5cf2a5bc05396ea24cb510e) with the console messages from a remote debugging session.  

[Here is a jsfiddle](https://jsfiddle.net/fraguada/6hLgnqke/1/) which fails on Firefox for Android, but Chrome for Android 55.0.2883.91 seems to work fine.

[Here is a jsfiddle](https://jsfiddle.net/fraguada/gtduv3ef/1/) which works on Firefox for Android.  All that is different is `renderer.capabilities.logarithmicDepthBuffer= false;`.

This was tested on a BQ androidone and Huawei P9.

##### Three.js version

- [ ] Dev
- [x] r79
- [x] r84

##### Browser

- [] All of them
- [ ] Chrome
- [x] Firefox for Android 50.1.0 and 51 beta
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Ohm... I don't think `renderer.capabilities.logarithmicDepthBuffer` shouldn't be changed at runtime.

Do these updates jsfiddles still have the issue?

https://jsfiddle.net/6hLgnqke/2/
https://jsfiddle.net/gtduv3ef/3/

**Comment by fraguada** [comment]
Hello,
The first link https://jsfiddle.net/6hLgnqke/2/ still had the issue, since logarithmicDepthBuffer = true.  I haven't had a chance to check the console output, but the result on android is the same, the scene does not show up.

**Comment by Mugen87** [comment]
I'm unable to reproduce with latest Firefox 61 on Android 8.1. In any event, bugs like this should be directly reported to https://bugzilla.mozilla.org/
