### ISSUE TITLE
Does the documentation state that FloatTypes shouldn't be used with RGBA texture formats?

### ISSUE THREAD

**Issue by marquizzo** [mrdoob/three.js#10665]
##### Description of the problem 

The [Texture Constants section](https://threejs.org/docs/index.html?q=webglrend#Reference/Constants/Textures) states that the 

> "RGBAFormat is the default and reads the red, green, blue and alpha components. The type must be `UnsignedByteType`, `UnsignedShort4444Type` or `THREE.UnsignedShort5551Type`."

However, the [WebGL GPGPU Water example](https://threejs.org/examples/webgl_gpgpu_water.html) uses a WebGLRenderTarget that uses the `RGBAFormat` and `THREE.HalfFloatType` or `THREE.FloatType`: 

	var renderTarget = new THREE.WebGLRenderTarget( sizeXTexture, sizeYTexture, {
		wrapS: wrapS,
		wrapT: wrapT,
		minFilter: minFilter,
		magFilter: magFilter,
		format: THREE.RGBAFormat,
		type: ( /(iPad|iPhone|iPod)/g.test( navigator.userAgent ) ) ? THREE.HalfFloatType : THREE.FloatType,
		stencilBuffer: false
	} );

Is this a documentation issue, or should the FloatTypes not be used to generate `RGBAFormat` textures?

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [x] IOS

**Comment by looeee** [comment]
It's at [examples/js/GPUComputationRenderer.js#L294](https://github.com/mrdoob/three.js/blob/master/examples/js/GPUComputationRenderer.js#L294) in case anyone else wants to look into this.

I suspect the reason is that the stipulation only applies when the texture is being used as a color map - the render target is likely being used in some other way, so the RBGA channels are being interpreted as something other than Red, Green, Blue, Alpha in the shader.

**Comment by marquizzo** [comment]
Yes, that example is using RBGA values to displace water ripples instead of drawing color. It works perfectly because `THREE.FloatType` has much higher precision than the 256 values under the default `UnsignedByteType`. I'm just wondering if the documentation needs to be updated.

**Comment by looeee** [comment]
> I'm just wondering if the documentation needs to be updated.

Yes, probably. It seems the situation is a bit more complicated than I thought when I wrote it. Do you want to take a stab at it?

There's some info in the WebGL Insights book [here](https://books.google.com.my/books?id=6crECQAAQBAJ&pg=PA129&lpg=PA129&dq=webgl+rgba+format&source=bl&ots=Jqci91PbMA&sig=SbbyLNeDOMDND69TK7zWmuG2pTY&hl=en&sa=X&redir_esc=y#v=onepage&q&f=false) that might be of help.

**Comment by Mugen87** [comment]
There are even more errors in this doc page.  For example the description for `LuminanceFormat` says:

> The type must be UnsignedByteType.

That's not true. `THREE.FloatType` or `THREE.HalfFloatType` also work. 

Example: https://jsfiddle.net/f2Lommf5/1856/

I suggest to remove all sections that starts with: `The type must be...` and just refer to [MDN](https://developer.mozilla.org/de/docs/Web/API/WebGLRenderingContext/texImage2D) instead.

**Comment by Mugen87** [comment]
BTW: The external links are not correct on this doc page. They are not created with `[link:]` but with plain anchor elements. Hence, the navigation is wrong.
