### ISSUE TITLE
Unable to get version newer than r77 from webjars

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#10669]
##### Description of the problem 

I am using Three.js in a Scala.js project. My preferred way to get Three.js is using webjars from SBT as follows:

    jsDependencies += "org.webjars.bower" % "three.js" % "0.77.0" / "three.js" minified "three.min.js"

The most recent version I have found on webjars is r77, anything more recent does not work.

##### Three.js version

- r82

##### Browser

- N/A

##### OS

- Windows

**Comment by mrdoob** [comment]
I'm not sure there is much we can do about that...?

**Comment by OndrejSpanel** [comment]
I have zero experience with artifact publishing, therefore I do not know. A few questions which perhaps might lead in the right direction:

How does webjar publishing work? Who can place archives there? Were r77 and before revisions placed there by you, or someone else, someone unrelated?

**Comment by mrdoob** [comment]
I never heard of webjar before...

**Comment by OndrejSpanel** [comment]
OK. I will try to learn to ropes and check I can do something about this.

Current webjars release is https://bintray.com/webjars/maven/org.webjars.bower%3Athree.js

I have found a github project called [WebJar for three.js](https://github.com/msiegenthaler/three.js-webjar), which was perhaps intended to handle webjar publishing (though it is currently release r68).

I have pushed "Add a new bower webjar", pointed to three.js root, chose version r82 ... and voila ... 

<pre>
Deployed!
It will take a few hours for the Maven Central index to update but you should be able to start using the Bower WebJar now.
GroupID = org.webjars.bower
ArtifactID = three.js
Version = 0.82.0
</pre>

I will check what automation options exist so that it is not necessary to do this manually for new releases.

**Comment by looeee** [comment]
Three.js has stopped using bower though, so that might not work for versions after r83.

**Comment by OndrejSpanel** [comment]
Thanks for bringing that up. For reference: bower removed in #10452

**Comment by OndrejSpanel** [comment]
I have deployed r83 and r80 manually. Both currently show in their log only:

<pre>
Generated POM
Converted dependencies to Maven
Resolved Licenses
Got NPM info
Determined Artifact Name: github-com-mrdoob-three-js
Starting Deploy
</pre>

**Comment by mrdoob** [comment]
Issue solved then? 😊

**Comment by OndrejSpanel** [comment]
Not yet, I am afraid. r82 is deployed (bower), but newer revisions (npm) are not.

**Comment by mrdoob** [comment]
Uh? https://www.npmjs.com/package/three

**Comment by OndrejSpanel** [comment]
This is a NPM package, but not deployed as webjar, therefore not accessible through Maven / Ivy / SBT.

**Comment by mrdoob** [comment]
So, is there anything that we can do?

**Comment by Mugen87** [comment]
@OndrejSpanel Any updates on this? Or can we close the issue?

**Comment by OndrejSpanel** [comment]
I am sorry, I was unable to proceed with this. For my purpose I have started including three.js by directly including the minified source.

**Comment by OndrejSpanel** [comment]
I do not know why, how or when it disappeared, but the issue no longer exists, I am able to download version 77-87 fine from Maven, the artifact page is https://mvnrepository.com/artifact/org.webjars.bower/three.js.
