### ISSUE TITLE
Box2  intersectsBox problem

### ISSUE THREAD

**Issue by jolofj** [mrdoob/three.js#10670]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

Box2   intersectsBox  doesn't match when the two bounding boxes are identical: 

This is the code now:
 return a.max.x < this.min.x || a.min.x > this.max.x || a.max.y < this.min.y || a.min.y > this.max.y ? !1 : !0

I guess it should be
 return a.max.x <= this.min.x || a.min.x >= this.max.x || a.max.y <= this.min.y || a.min.y >= this.max.y ? !1 : !0    instead

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...
The version that is used in the SVGRenderer demo: https://github.com/mrdoob/three.js/blob/master/examples/svg_sandbox.html

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Intel HD Graphics 520

**Comment by WestLangley** [comment]
>Box2 intersectsBox doesn't match when the two bounding boxes are identical:

@jolofj What do you mean by "doesn't match"?

Can you provide an example to demonstrate the issue?

Use `three.js`, not `three.min.js` for debugging.

**Comment by Mugen87** [comment]
I think we can close this issue. The following example shows that the current implementation of `.intersectsBox()` correctly detects so called "improper" intersections (e.g. two boxes _touches_ each other).

https://jsfiddle.net/k834tdhd/
