### ISSUE TITLE
The texture of crossOrigin is not displayed in glTF Loader from r84 or later

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#10678]
##### Description of the problem 

Three.js r83 was able to read the following glTF model, but it can not be read from r84 or later. .
https://cdn.rawgit.com/KhronosGroup/glTF-Sample-Models/4a08a32e/1.0/Duck/glTF/Duck.gltf
( https://cdn.rawgit.com/KhronosGroup/glTF-Sample-Models/4a08a32e/1.0/Duck/glTF/DuckCM.png )

http://jsdo.it/cx20/EK3t ... Three.js r83 + glTF Loader is OK
http://jsdo.it/cx20/GZt6 ... Three.js r84 + glTF Loader is NG
http://jsdo.it/cx20/8rIF ... Three.js r85dev + glTF Loader is NG

Three.js r85dev displays the following error on the console.
```
DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at https://cdn.rawgit.com/KhronosGroup/glTF-Sample-Models/4a08a32e/1.0/Duck/glTF/DuckCM.png may not be loaded.
    at Object.texImage2D (https://cdn.rawgit.com/mrdoob/three.js/10d0eb97a69d74ddf03f5d9fe34909ba75e026b0/build//three.js:19264:19)
    at uploadTexture (https://cdn.rawgit.com/mrdoob/three.js/10d0eb97a69d74ddf03f5d9fe34909ba75e026b0/build//three.js:18139:12)
    at WebGLTextures.setTexture2D (https://cdn.rawgit.com/mrdoob/three.js/10d0eb97a69d74ddf03f5d9fe34909ba75e026b0/build//three.js:17789:6)
    at WebGLRenderer.setTexture2D (https://cdn.rawgit.com/mrdoob/three.js/10d0eb97a69d74ddf03f5d9fe34909ba75e026b0/build//three.js:22230:14)
    at SingleUniform.setValueT1 [as setValue] (https://cdn.rawgit.com/mrdoob/three.js/10d0eb97a69d74ddf03f5d9fe34909ba75e026b0/build//three.js:4470:12)
    at Function.WebGLUniforms.upload (https://cdn.rawgit.com/mrdoob/three.js/10d0eb97a69d74ddf03f5d9fe34909ba75e026b0/build//three.js:4797:7)
    at setProgram (https://cdn.rawgit.com/mrdoob/three.js/10d0eb97a69d74ddf03f5d9fe34909ba75e026b0/build//three.js:21631:19)
    at WebGLRenderer.renderBufferDirect (https://cdn.rawgit.com/mrdoob/three.js/10d0eb97a69d74ddf03f5d9fe34909ba75e026b0/build//three.js:20361:18)
    at renderObjects (https://cdn.rawgit.com/mrdoob/three.js/10d0eb97a69d74ddf03f5d9fe34909ba75e026b0/build//three.js:21187:12)
    at WebGLRenderer.render (https://cdn.rawgit.com/mrdoob/three.js/10d0eb97a69d74ddf03f5d9fe34909ba75e026b0/build//three.js:20924:5)
```
I think that the cause is that the designation of crossOrigin differs between r83 and r84 and beyond.

##### Three.js version

- [x] Dev
- [x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

ThinkPad X260 + Intel(R) HD Graphics 520

**Comment by takahirox** [comment]
Try to add `loader.setCrossOrigin( 'anonymous' );`.
Refer to #10465

**Comment by cx20** [comment]
@takahirox I tried setCrossOrigin with some browsers.
Generally it seems that setCrossOrigin works. However,  If texture is in Data URI format (glTF-Embedded or glTF-Binary) in Safari, it is no longer displayed when setCrossOrigin is specified.

|glTF Format   |setCcrossOrigin|Chrome|Firefox|Safari|
|:-------------|:-------------:|------|-------|------|
|glTF-Embedded |    -          |  OK  |  OK   |  OK  |
|glTF-Embedded |Anonymous      |  OK  |  OK   |  NG  |
|glTF-Binary   |    -          |  OK  |  OK   |  OK  |
|glTF-Binary   |Anonymous      |  OK  |  OK   |  NG  |
|glTF(Regular) |    -          |  OK  |  OK   |  OK  |
|glTF(Regular) |Anonymous      |  OK  |  OK   |  OK  |

If possible, it is good to judge whether the texture is a Data URI or an external URI in glTF Loader and automatically specify setCrossOrigin.

**Comment by takahirox** [comment]
It seems like a known issue
http://stackoverflow.com/questions/31643096/why-does-safari-throw-cors-error-when-setting-base64-data-on-a-crossorigin-an

Would you replace this line in `ImageLoader`

https://github.com/mrdoob/three.js/blob/5463a48edb0bdaba66eeacff75efc1fcbb4a85e0/src/loaders/ImageLoader.js#L71

with

    if ( this.crossOrigin !== undefined && /^data:/.test( url ) ) image.crossOrigin = this.crossOrigin;

and check if your tell will be all ok?

**Comment by cx20** [comment]
> Would you replace this line in ImageLoader

I think that there is no problem with the presented code.

By the way, it seems that we checked data URI until r83.

https://github.com/mrdoob/three.js/blob/r83/src/loaders/ImageLoader.js#L34

Probably, I think that processing was removed when refactoring.

**Comment by takahirox** [comment]
> I think that there is no problem with the presented code.

You tested?

**Comment by cx20** [comment]
> You tested?

I'm sorry, but I have not done the test yet. Because I am out, I will test it when I return.

**Comment by cx20** [comment]
I tried the following code.
```js
if ( this.crossOrigin !== undefined && ! /^data:/.test( url ) ) image.crossOrigin = this.crossOrigin;
```
http://jsdo.it/cx20/kFNJ

|glTF Format   |setCcrossOrigin|Chrome            |Firefox            |Safari            |
|:-------------|:-------------:|------------------|-------------------|------------------|
|glTF-Embedded |    -          |:white_check_mark:|:white_check_mark: |:white_check_mark:|
|glTF-Embedded |Anonymous      |:white_check_mark:|:white_check_mark: |:white_check_mark:|
|glTF-Binary   |    -          |:white_check_mark:|:white_check_mark: |:white_check_mark:|
|glTF-Binary   |Anonymous      |:white_check_mark:|:white_check_mark: |:white_check_mark:|
|glTF(Regular) |    -          |       :x:        |        :x:        |        :x:       |
|glTF(Regular) |Anonymous      |:white_check_mark:|:white_check_mark: |:white_check_mark:|

I confirmed that texture is displayed in Safari.

**Comment by takahirox** [comment]
Thanks.

Just in case, the NGs of glTF(Regular) with `setCrossOrigin` - (undefined, right?)
are expected result, correct?

**Comment by cx20** [comment]
> Just in case, the NGs of glTF(Regular) with `setCrossOrigin` - (undefined, right?)

Yes. `-` is equivalent to `undefined` because it is a case without specifying anything.

> are expected result, correct?

Yes. The result is as expected.
However, since operation is different from r83, it is necessary to consider which operation is preferable.

In r83, it works without specifying `setCrossOrigin('anonymous')`. This was due to the following code.
https://github.com/mrdoob/three.js/pull/10465/files#diff-43f9265a3da0d9ebbf235517b2541578L796

```js
textureLoader.crossOrigin = options.crossOrigin || false;
// When crossOrigin is set to false the value of image.crossOrigin is 'anonymous'.
```
The current code is as follows.
```js
textureLoader.setCrossOrigin( options.crossOrigin );
```
If the behavior of r83 is better, you'd better set the default value to 'anonymous'.
```js
textureLoader.setCrossOrigin( options.crossOrigin || 'anonymous' );
```
I think that 'anonymous' is better by default, but what about other people?

**Comment by takahirox** [comment]
> textureLoader.setCrossOrigin( options.crossOrigin || 'anonymous' );
I think that 'anonymous' is better by default, but what about other people?

Disagreed because of security.
And setting `false` in r83 was just a bug.

**Comment by cx20** [comment]
> Disagreed because of security.

I think your opinion is correct.

> Setting `false` in r83 was just a bug.

I understood that the setting of r83 is a bug.

> And what I asked was the meaning of "NG" in the table.

"NG" in the table simply means "can not display". It does not mean unexpected results.
