### ISSUE TITLE
EdgesGeometry not showing all edges

### ISSUE THREAD

**Issue by x31xc0** [mrdoob/three.js#10677]
I'm trying to implement a wireframe view much like Maya has using the following code

` var geo = new THREE.EdgesGeometry( _this.geometry );`                                      
  `var mat = new THREE.LineBasicMaterial( { color: 0xffffff, linewidth: 2 } );`
  `var wireframe = new THREE.LineSegments( geo, mat );`
  `_this.scene.add( wireframe );`

But this is producing some unexpected results in that it does not seem to be rendering all of the edges and is still displaying some tri faces.

This is a comparison of the two: http://imgur.com/a/BpdDV

I understand that Face4 support has been removed and i was hoping that this could simulate what im looking to achieve. 

Apologies if i have the wrong idea about how this is meant to work.

Here is the source for the model i am using (http://pastebin.com/21XUKYbw)

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
What you see in maya is wireframe of a geometry done with quads. We do not support quads, we only support triangles.

**Comment by WestLangley** [comment]
http://stackoverflow.com/questions/41919939/threejs-maya-like-wireframe-implementation

**Comment by x31xc0** [comment]
@mrdoob Thanks for the response. Im pretty new to all of this. Is there no way i can achieve what im asking for? I would like to continue using threejs if i can.
