### ISSUE TITLE
vreffect + webvr polyfill = eyes swapped.

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#10684]
here is ios screenshot:

![img_8309 png](https://cloud.githubusercontent.com/assets/242577/22421881/c5a120f6-e6e9-11e6-932d-347005e24671.jpg)

so you guys either need to auto-unswap the eyes or give user the option to do so.

**Comment by makc** [comment]
filed the same bug with webvr polyfill https://github.com/googlevr/webvr-polyfill/issues/192 in case it's theirs.

**Comment by mrdoob** [comment]
Hmm, what's the scale of your scene?

**Comment by makc** [comment]
I think it's in meters, that thing at bottom-left is where the avatar stands normally, so about 4 meters to the ceiling.

**Comment by Kyle-Larson** [comment]
https://github.com/mrdoob/three.js/commit/d047a71132f4fc2aceec72f050a8173b60ab8e50

I think I found the culprit

Line 310:
```
cameraR.position.copy(cameraL.position);
cameraR.quaternion.copy(cameraL.quaternion);
cameraR.scale.copy(cameraL.scale);
```

**Comment by Kyle-Larson** [comment]
For what it's worth, the polyfill hasn't changed in at least 2 months, and we (My team for my project) haven't noticed the eyes swapping until recently.  It would make a lot more sense to me if it were a problem on Three's end than the polyfill's end.

**Comment by makc** [comment]
no, that was just saving one decompose call

[image: Inline image 1]

**Comment by mrdoob** [comment]
I wonder if #10446 had anything to do with this...?

**Comment by makc** [comment]
@mrdoob vreffect does not seem to use stereocamera

**Comment by mrdoob** [comment]
Oh! Uhm... Then I'm not sure how this can be an issue in `VREffect`. The issue would still be present without the polyfill...

**Comment by makc** [comment]
Random tweet from my feed:

![screen shot 2017-02-10 at 3 15 55](https://cloud.githubusercontent.com/assets/242577/22811495/741c0d46-ef3f-11e6-8e8c-9453ed0f03d0.png)

eyes swapped

**Comment by mrdoob** [comment]
I don't think these are eyes swapped. I just tried on my daydream and even if the screenshot gives the impression the eyes are swapped inside the device it feels correct.

![screenshot_20170209-183337](https://cloud.githubusercontent.com/assets/97088/22811950/d640fb42-eef6-11e6-8531-0c2c0e931588.png)

**Comment by makc** [comment]
the beauty of bare facts is that it does not matter what you think of it :P 1 in your screenshot, "left" eye sees the mountain on the right, and "right" eye does not, 2 both eyes are pinched more in the middle - both unlike e g this screenshot from oculus sdk:

![lol](https://developer3.oculus.com/images/documentation/pcsdk/0.5/defaultFOV.jpg)

(check the tree on the right, and correct distortion)

finally, [this game](http://www.knockknock.jp/sample/js-racing-vr/) uses three.js r64 and produces correct result:

![yeah](http://www.knockknock.jp/wp-content/uploads/2015/06/20150616_img.jpg)

**Comment by mrdoob** [comment]
It's hard to judge by screenshots. Please share a working link we can try.

**Comment by makc** [comment]
the only way I can think of why would you get this kind of image, if the eyes are not swapped, is if cameras are not parallel but looking at some near point in front of you.

**Comment by mrdoob** [comment]
Our eyes are not parallel...

![screen shot 2017-02-09 at 18 56 20](https://cloud.githubusercontent.com/assets/97088/22812441/91defb04-eef9-11e6-83ca-bed6eff929e5.png)

**Comment by makc** [comment]
however, if you look at the
![code above](https://cloud.githubusercontent.com/assets/242577/22491090/5790152a-e821-11e6-9dba-1ec45e1e70c6.png)

you see both cameras are using the same quaternion

**Comment by mrdoob** [comment]
But a different projection matrix:
https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/VREffect.js#L323-L324

**Comment by makc** [comment]
you mean the frustum is skewed?

**Comment by mrdoob** [comment]
Yep!

**Comment by mrdoob** [comment]
Some literature... (Which is also referenced in `StereoCamera`) 😁
http://paulbourke.net/stereographics/stereorender/

**Comment by makc** [comment]
Checked webvr polyfill code, it has these:

![screen shot 2017-02-10 at 4 03 44](https://cloud.githubusercontent.com/assets/242577/22812629/209988a4-ef46-11e6-8fdd-7785eed2bd7d.png)
![screen shot 2017-02-10 at 4 04 11](https://cloud.githubusercontent.com/assets/242577/22812628/209109e0-ef46-11e6-90f4-109923797d33.png)

does not look skewed to me 🤔

**Comment by mrdoob** [comment]
I don't know man... If you have a working link that we can test I'll be happy to take a look.

**Comment by makc** [comment]
Ok, so like I said, hard facts does not depend on my opinion 🙃 and facts are that [out[8] in the above thing does differ, so them projections are skewed indeed](http://jsfiddle.net/hfj7gm6t/3092/).
