### ISSUE TITLE
Browser crashes when exporting large files from editor

### ISSUE THREAD

**Issue by dleithinger** [mrdoob/three.js#10695]
##### Description of the problem 
When working with large files in the Three.js editor, the browser crashes when trying to export. After reloading the site, the editor usually automatically loads the model file from the cache just fine.

##### Browser
- [x] All of them

##### OS
- [x] All of them

**Comment by kapilgp** [comment]
Try to use BufferGeometries

**Comment by mhirsch** [comment]
I've had this happen too. It's not related to rendering the scene -- its something about turning the entire scene into a json object. I think the browser has a maximum string size of about 100MB. Is there some way to serialize the scene out to json without hitting this limit?

The scene object can be stored in localStorage without running into the problem, so the scene can be restored after the browser crash (as long as the autosave checkbox is checked).

**Comment by mrdoob** [comment]
Yes, the editor currently can't handle big geometries... How many triangles are we talking about anyway?

**Comment by mhirsch** [comment]
I ran into one today with 249k triangles, 198k vertices. It's a detailed architectural model. But it's not what I would consider absurdly large ;)

**Comment by Mugen87** [comment]
Merging this issue into #9187.

**Comment by makc** [comment]
perhaps something like [this](https://github.com/Faleij/json-stream-stringify#complete-example) could help here, but then you would need your own replacement of fflate.strToU8 to make a normal array (that you could grow) instead
