### ISSUE TITLE
FBX file not loading

### ISSUE THREAD

**Issue by filharvey** [mrdoob/three.js#10697]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
I have a FBX file which is falling on on load. Seems that the file has nodes which have no indices and weights. This was created via the FBX Converter app from Adobe from a FBX binary file.

I was using the webgl_loader_fbx.html as a base to load the model.

Model included.

##### Three.js version

- [ x] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Can you share the fbx file?

**Comment by filharvey** [comment]
Sorry thought I had. But needed to be zipped.
[toon.zip](https://github.com/mrdoob/three.js/files/745545/toon.zip)

**Comment by Kyle-Larson** [comment]
I'll take a look at it.  Seems to be that some of the deformers don't actually have indices / weights on them.  Shouldn't be too difficult of a fix.

**Comment by philhJC** [comment]
Yep, hopefully simple.

**Comment by Kyle-Larson** [comment]
Fix in ( #10699 ).

**Comment by Kyle-Larson** [comment]
@filharvey The one thing I couldn't verify is that the model had a texture that it was pointing to that wasn't included in the zip.  Furthermore, the texture references a photoshop file, which Three doesn't support importing (as far as I know), so in the program that created the FBX file, you should change your reference to point to an image file.  Then as long as the image file is in the same directory as the FBX file, you should be good to go.
