### ISSUE TITLE
*Material.lightMap should allow for HDR Encodings

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#10690]
##### Description of the problem 

*Material.lightMap is supposed to represent incoming light onto a material which then interacts with the surface to give a resulting intensity.  RIght now lightMap does not support encodings, such as RGBM*/RGBE/etc, thus it is limited to LDR, rather than HDR.  In reality, the incoming light is more accurately represented by HDR images.  To rectify this, we should allow for lightMap to have an encoding  (lightMapEncoding) similar to map (mapEncoding) and emissiveMap (emissiveMapEncoding).

##### Three.js version

- [x] Dev
- [x] r82

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by dherben** [comment]
I was surprised to find out that ThreeJS does not support HDR encodings in the lightmaps, seems to be one of the principal places where you would want this.

I'm considering picking this up myself, if someone could give me some information on what it would take to make it work.

**Comment by tomdelerue** [comment]
Yes, something I've been looking forward to for some time. Maybe I can help?

**Comment by Mugen87** [comment]
Should be fixed via #18052.
