### ISSUE TITLE
bump map repeat problem

### ISSUE THREAD

**Issue by rosone** [mrdoob/three.js#10704]
my texture map is not repeatable, fixed 1024*1024, but I want a repeatable bump map, but it doesn't repeat when I set repeat.set(2,2), however the bump map was zoomed in, is this a bug?

I've tried to make a 1024*1024 bump map, but it was still zoomed in.

here is the effect:
<img width="407" alt="1" src="https://cloud.githubusercontent.com/assets/1670400/22557184/aeb55f70-e9a4-11e6-8f31-7dd45f361214.png">
below is bump map
![Uploading 2.png…]()

**Comment by WestLangley** [comment]
See http://stackoverflow.com/questions/14371385/can-a-three-js-material-have-separate-repeat-values-for-a-bump-map-and-a-texture

**Comment by WestLangley** [comment]
Related: #8278 enhancement
