### ISSUE TITLE
material.clone() does not clone the uniforms

### ISSUE THREAD

**Issue by mqnc** [mrdoob/three.js#10705]
the title says it all

**Comment by takahirox** [comment]
Would you be a bit more specific?
You meant, the `unioforms` property of `ShaderMaterial`?

**Comment by mqnc** [comment]
Sorry, I just looked into the material.clone source and didn't find the uniforms, not into the ShaderMaterial.clone source. My bad. However, the issue remains:

If I create two objects and clone the ShaderMaterial of the first object for the second object, I cannot change the uniforms for one object without modifying the ones for the other object as well, so something seems to go wrong during cloning.

I also found that renderOrder does not get cloned.

I'm using r83 though.

I can look into these things and create a minimal example soon if this helps.

**Comment by takahirox** [comment]
Yeah, would you please make an example on https://jsfiddle.net/ or somewhere?
(Refer to http://jsfiddle.net/hw9rcLL8/)

Both `ShaderMaterial.uniforms` and `Object3D.renderOrder` seem to get cloned correctly in the code tho...
https://github.com/mrdoob/three.js/blob/8735cbab9576c0fc9f50bf43a7e94708aa6575c2/src/materials/ShaderMaterial.js#L93
https://github.com/mrdoob/three.js/blob/08c40e22c7cec08cb4df7b3552392eff50a125c1/src/core/Object3D.js#L92

**Comment by Mugen87** [comment]
As @takahirox said, the implementation is correct. We can reopen the issue if @mqnc illustrates the reported misbehavior with a fiddle.
