### ISSUE TITLE
Error in AnimationMixer.js

### ISSUE THREAD

**Issue by samskivert** [mrdoob/three.js#10700]
##### Description of the problem 
AnimationMixer.js line 287 has:

```
   rootUuid = ( actions._localRoot || this._root ).uuid;
```

That should be:

```
   rootUuid = ( action._localRoot || this._root ).uuid;
```

action not actions.

##### Three.js version

- [x] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

N/A

**Comment by takahirox** [comment]
Yep, I think it should be `action._localRoot`

**Comment by mrdoob** [comment]
@samskivert would you like to do a PR with the fix?

**Comment by samskivert** [comment]
Sure! One sec.
