### ISSUE TITLE
ColladaLoader should use DefaultLoadingManager

### ISSUE THREAD

**Issue by Seranth** [mrdoob/three.js#10718]
##### Description of the problem 
ColladaLoader.js is not using the DefaultLoadingManager. In fact, as far as I can tell it doesn't have any LoadingManager functionality at all, it uses its own loading manager it seems. It does however trigger the DefaultLoadingManagers onLoad function, but not synced with other loaders.

Please make ColladaLoader use the DefaultLoadingManager. ColladaLoader2 seems to be capable of doing that already, but, at least in my program, it displays the entire scene incorrectly, so I have to choose between a ColladaLoader that doesn't do the job and one that doesn't use the DefaultLoadingManager.

The problem with not being able to use the DefaultLoadingManager with ColladaLoader is that at the moment I have to use a fairly hacky workaround of creating bool variables for each loader I'm using, so that the DefaultLoadingManagers onLoad function does not trigger multiple times. Not sure why ColladaLoader triggers the DefaultLoadingManager's onLoad function at all, but it does, and in my program that leads to the entire scene being created twice, once with errors, which is why my workaround with bools was needed.

##### Three.js version

- [x] r84

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
`ColladaLoader2` was enhanced in June/July. If you still experience problems with the new loader, we can reopen this issue.
