### ISSUE TITLE
Another FBX Loading Issue

### ISSUE THREAD

**Issue by filharvey** [mrdoob/three.js#10714]
[dwarf.zip](https://github.com/mrdoob/three.js/files/750707/dwarf.zip)
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
Another FBX ascii model not being loading in properly.

Issues with 'IndexToDirect'???

##### Three.js version

- [x ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Kyle-Larson** [comment]
I'll take a look at it.  On a separate note, thanks for providing a lot of needed testing for the new FBX loader 😄

**Comment by Kyle-Larson** [comment]
Fixed in ( #10716 ).
FYI there's no material assigned to the mesh in the FBX file, which is why it shows up as the default blue color.  Other than that, the PR seems to fix all issues with the model.

**Comment by philhJC** [comment]
Thanks, 

Np, will be adding more and more FBX issues as I come across them. Moving game from unity to JS :-)
