### ISSUE TITLE
Rename text example with font.generateShapes or new example

### ISSUE THREAD

**Issue by koober** [mrdoob/three.js#10725]
##### Description of the problem 

After discovering font.generateShapes the hard way, I since noticed that it is somewhat mis-represented in Examples as "webgl_shaders_vector". 
[This fiddle](http://jsfiddle.net/koob3d/71xcpm0d/2/) combines it with another sample taken from Obsidian's textModule.
Might help other noobs?

##### Three.js version

- [x] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Yeah, I remember the holes hackiness when doing Obsidian... I think it would be nice to have an example for this, yep!
