### ISSUE TITLE
Best Video Size for VideoTexture

### ISSUE THREAD

**Issue by tatbocmui** [mrdoob/three.js#10726]
##### Description of the problem 
I want to design a player play VR video? But I think I have a problem with video which has a bitrate quite high. When I load a video with bitrate = 27.1Mb/s, the texture do not run smoothly. While with video's bitrate = 10Mb/s, the texture seems work very well? The size of video is 3840x1920. So can you give me which is the best video for videoTexture?

##### Three.js version

- [x] Dev
- [ ] r82
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by looeee** [comment]
Have you tried playing the video inside a normal video element? Does it play smoothly there?

**Comment by tatbocmui** [comment]
Dear looeee,
Yes. It still play very well with normal media VR player

**Comment by mrdoob** [comment]
I would suggest 2048×1024.
