### ISSUE TITLE
Texture issue (PNG loading and more)

### ISSUE THREAD

**Issue by wothke** [mrdoob/three.js#10724]
##### Description of the problem 

See testcase here: www.wothke.ch/three.js/png_test

The fragment shader heavily relies on a noise texture that it uses as an input
but multiple things go wrong when  that noise texture is created via THREE.js

 1) The random noise texture loaded from the noise256.png file should be equivalent 
 to the same kind of noise texture generated via JavaScript.
 (Also the same .png has the correct effect when used directly on ShaderToy:
 see https://www.shadertoy.com/view/4lKXWV# ) But when used via THREE.js
 TextureLoader something is no longer "right": see left-hand part of the 
 shader output VS right-hand (round VS angular).

 2) But even with the "better" noise texture (created in JavaScript) something else is still not 
 "right": The concentric circles *should not* be visible but should be blurred 
 instead and I have not managed to find any THREE.Texture setting that would 
 copy the original bahavior. However the flawed rendering can be simulated in 
 ShaderToy by activating the "VFlip" option on the respective iChannel0 noise 
 texture. I would have guessed that "flipY" might be the respective 
 THREE.js param .. but it does not seem to affect the issue at hand..

##### Three.js version

- [x] r84

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by looeee** [comment]
All I get for your first link is a black box.

**Comment by wothke** [comment]
I am testing with Win10 (64bit) and here the page works in Firefox (version 50.0.1) and Chrome (Version 55.0.2883.87 m).

**Comment by mrdoob** [comment]
I'm also only getting a black box... Chrome 56.0.2924.87, Firefox 51.0.1, OSX 10.10.5, Intel HD Graphics 6000

**Comment by wothke** [comment]
interesting, here it runs even with the Edge browser.. with no console errors..  

Still I fixed a stray " typo in the index.html and changed the init-sequence to make sure that the render pass is not used before it is completely configured. 

In case that does not fix the black-box effect, then I don't know what it might be (the shader code is almost identical to the one in ShaderToy - see my link above - and if that code works on your machine, then it should not be a driver issue..).

**Comment by mrdoob** [comment]
Still doesn't work...

![screen shot 2017-02-06 at 13 01 36](https://cloud.githubusercontent.com/assets/97088/22666189/8368ccce-ec6c-11e6-88a7-5d6674842235.png)

**Comment by mrdoob** [comment]
The ShaderToy one does though.

**Comment by makc** [comment]
![screen shot 2017-02-06 at 23 24 24](https://cloud.githubusercontent.com/assets/242577/22669092/74bab10e-ecc3-11e6-96f4-2f096b9953e6.png)

the effect animates so fast that I cant notice any difference

**Comment by makc** [comment]
more screenies:

![screen shot 2017-02-06 at 23 29 32](https://cloud.githubusercontent.com/assets/242577/22669316/47c5eb0e-ecc4-11e6-8852-4a061dce1470.png)
![screen shot 2017-02-06 at 23 29 54](https://cloud.githubusercontent.com/assets/242577/22669315/47c4a3f2-ecc4-11e6-9692-b0bc0c62ff83.png)

definitely different from shadertoy but not much from each other

**Comment by wothke** [comment]
great, at last somebody is able to reproduce it :-) here 2 screenshots using a bigger area:
![comparison](https://cloud.githubusercontent.com/assets/5231102/22673861/062f36dc-ecdd-11e6-82cf-4606cc6c50cc.gif)
on the right the "correct" version, i.e. where the input noise-texture (here generated via canvas) gives the shader whatever it needs to create these roundish/plasma-bubble structures. on the left the defect version: not a single plasma-like structure - everything is rather angular (it looks as if the random input is badly sampled). the ShaderToy version uses the *exact same* 256x256 noise-png-image that the left version here fails so miserably with.. I would suspect that there are wrong Texture settings being made while creating the texture from the png file..

**Comment by makc** [comment]
maybe it's smaller mip maps?

**Comment by makc** [comment]
p s I still dont think I see your problem the way you do, though
![screen shot 2017-02-07 at 8 10 09](https://cloud.githubusercontent.com/assets/242577/22681335/f5660de6-ed0c-11e6-9b78-ccfcfa3c030a.png)

**Comment by wothke** [comment]
@makc what do you mean? you don't see that patterns on the right (your screeny above) are all stretched in length? 
PS: even when I set  texture.generateMipmaps = false and  texture.minFilter= THREE.LinearFilter the effect is exactly the same.. and texture.repeat.set(10,10); makes no difference...

**Comment by makc** [comment]
> you don't see that patterns on the right (your screeny above) are all stretched in length?

ok but in your screen it was on the left
> on the right the "correct" version

**Comment by wothke** [comment]
ARRRGGH, I just found the answer for problem #1: my mistake! the 256x256 .png did not contain the data that I thought it did.. it was actually 64x64 data scaled up to 256x256 - when using correct 256x256 data it behaves as it should. Sorry to have bothered you with this mistake that was completely my own :-(

there now only remains the "VFlip problem", i.e. "the circles" that can be simulated on the ShaderToy side via the "VFlip" switch on the iChannel0 texture - but that I cannot get rid of on the THREE.js version side:

I updated the test-page to mimick the ShaderToy version as closely as possible. Only diffs: the minimal vertex shader "gl_Position = vec4( position, 1.0 )" that I am using might be different from whatever ShaderToy is using,  also don't know what ShaderToy might be doing between its mainImage() hook and the underlying main().

**Comment by wothke** [comment]
just for your information: ShaderToy's "random noise" input images are not at all random. in fact they are specifically designed to serve as inputs for iq's noise() implementation.. (R+B channels are random while G+A channel copy the R+B data with a specific offset..)

**Comment by krux02** [comment]
@wothke thaks a lot for this information. That explains a lot.
