### ISSUE TITLE
Adding jsfiddle link to ISSUES_TEMPLATE.md

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#10723]
##### Description of the problem 

I think it's worth to add jsfiddle link to ISSUES_TEMPLATE.md.
Small-test will help us figure out Three.js bug and understand feature request.

The link is written in CONTRIBUTING.md but sadly
it seems like many people don't see that for filing issue.

How about this

    ##### Description of the problem 

    Describe the problem/request in detail.
    Code snippet, screenshot, and small-test help us understand.
    You can edit
    http://jsfiddle.net/akmcv7Lh/ (current revision)
    http://jsfiddle.net/hw9rcLL8/ (dev)
    for small-test.

##### Three.js version

- [ ] Dev
- [ ] r82
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Sounds good to me!
/cc @WestLangley

**Comment by WestLangley** [comment]
It doesn't hurt to try. :)

**Comment by takahirox** [comment]
I'll make PR! :D
