### ISSUE TITLE
MeshLambertMaterial receive shadow is wrong

### ISSUE THREAD

**Issue by zhoushijie163** [mrdoob/three.js#10736]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
![2017-02-06_13-31-24](https://cloud.githubusercontent.com/assets/18611035/22635717/9c5f3336-ec70-11e6-8186-9a86d8283d11.png)

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
This is a limitation of `MeshLambertMaterial`.
