### ISSUE TITLE
Many examples are white or over-bright on Chrome on macOS

### ISSUE THREAD

**Issue by Nimja** [mrdoob/three.js#10747]
##### Description of the problem 

Several examples show up oddly on Chrome on macOS (OSX). This is true not just for Three.js, but appears to be a new-ish WebGL feature in Chrome.

For example, the experiment: http://madebyevan.com/webgl-water/ - Worked fine before, but is white now.

* https://threejs.org/examples/#webgl_shadowmap_pointlight - Screen is completely white.
* https://threejs.org/examples/#webgl_shadowmap - Works, but is very light.
* https://threejs.org/examples/#webgl_shadowmap_performance - Works fine.
* https://threejs.org/examples/#webgl_shadowmap_viewer - Works fine.

Console output (nothing special):

    THREE.WebGLRenderer 84

Chrome version: Version 56.0.2924.87 (64-bit)
macOS Sierra: 10.12.3

Also tested on Window 10, x64, examples show up correctly.

##### Three.js version

- [x] Current stable, see urls.

##### Browser

- [ ] All of them
- [x] Chrome (only on macOS, reported to them as well)
- [ ] Safari - Tested - Works like normal.
- [ ] Firefox - Tested - Works like normal.
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] maxOS Sierra 
- [ ] Windows (Confirmed that it works normally there).
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Nimja** [comment]
It appears to only happen in Chrome on macOS Sierra. So I reported it to the Chrome team as well.

**Comment by mrdoob** [comment]
What graphics card is that with?

**Comment by WestLangley** [comment]
Does it only happen with three.js when `antialias: true` ?

**Comment by Benjamin-Dobell** [comment]
@Nimja Could you please supply your machine's specs and chrome version?

I'm not seeing this with the following setup:

MacBook Pro (Retina, 15-inch, Late 2013)
NVIDIA GeForce GT 750M 2048 MB
macOS 10.12.3 (16D32)

Chrome Version 57.0.2987.21 beta (64-bit)

Granted mine's a slightly older Mac. Perhaps it's an AMD driver issue?

**Comment by mslonina** [comment]
I am seeing similar issue on old setup (Macbook Pro mid-2010 with NVidia GT330M). On Safari (macOS 10.12.3) WebGL is rendered properly (THREE.WebGLRenderer 78), on Chrome Three.js throws an error: THREE.WebGLRenderer: Error creating WebGL context

**Comment by SpencerIO** [comment]
I have the same problem.

Chrome 56.0.2924.87 (Official Build) (64-bit)
macOS Sierra
Version 10.12.3
MacBook Pro (17-inch, Late 2011)
AMD Radeon HD 6770M 1024MB
Intel HD Graphics 3000 512 MB

**Comment by Mugen87** [comment]
Closing. If this is still an issue in Chrome, please report a bug here: https://bugs.chromium.org/p/chromium/issues/list
