### ISSUE TITLE
New dedicated THREE JS forum

### ISSUE THREAD

**Issue by SimonCornwell** [mrdoob/three.js#10742]
I just opened a **dedicated forum** about Three JS because I hadn't find any dedicated community where developers can talking about it and share **opinions**, examples and codes.
This is the link so, feel you free to join it:
http://threejs.forumotion.com

**Comment by makc** [comment]
> Firefox can’t find the server at threejs.forumotion.com.

CC #10325

**Comment by mrdoob** [comment]
Wow. It already has ADs 😕

**Comment by makc** [comment]
@mrdoob try one of these blockers. I mainly use that because of youtube, but it helps in this case, too - no ads for me.

**Comment by mrdoob** [comment]
@makc trolling again? 😜

**Comment by makc** [comment]
@mrdoob sorry, did you expect links to blockers?

**Comment by makc** [comment]
Actually, I am not quite happy how adblock handled these ads. I have added two custom rules,
> threejs.forumotion.com##td[style="background:#f4f5e7;padding:inherit 0"]

to turn this:
![screen shot 2017-02-23 at 23 26 13](https://cloud.githubusercontent.com/assets/242577/23282024/cb0b6af8-fa1f-11e6-9a45-35692fc9badb.png)

into this:
![screen shot 2017-02-23 at 23 26 19](https://cloud.githubusercontent.com/assets/242577/23282015/c0eb6abe-fa1f-11e6-8353-06e978c57f22.png)

and
> threejs.forumotion.com###p0

to get rid of this:
![screen shot 2017-02-23 at 23 20 52](https://cloud.githubusercontent.com/assets/242577/23282008/b6dc885a-fa1f-11e6-8d73-df159e104c07.png)

**Comment by mrdoob** [comment]
If a website has annoying ads I stop visiting the website. I don't use adblocks.
