### ISSUE TITLE
PBR+PMREM on A7 iPad GPU : Overflow in implicit conversion issue 

### ISSUE THREAD

**Issue by Astrak** [mrdoob/three.js#10748]
There is an issue with `MeshStandardMaterial`+ HDR PMREM with the iPad A7 GPU, the reflexions appear too bright, there are no dark zones. 

The console warns for the fragment shader : `WARNING: 0:260: Overflow in implicit conversion, minimum range for lowp float is (-2,2)`. 

It happens with all browsers on this device. Here are screenshots from the UnrealBloom example : the first is the iPad / A7 (iOS 10) render, the second one the picture you get with any other device :

![img_0115](https://cloud.githubusercontent.com/assets/10037511/22685254/eb3b02b4-ed1f-11e6-811c-7aad0ccd820c.PNG)
![capture d ecran de 2017-02-06 17 52 22](https://cloud.githubusercontent.com/assets/10037511/22685575/23d4e742-ed21-11e6-8cf4-206e56616094.png)

##### Three.js version

- [ ] Dev > untested
- [x] r84
- [x] r83...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
- [x] iPad with A7 GPU

**Comment by bhouston** [comment]
@Astrak what line is 260 on your machine?  I am curious because lowp isn't that frequently used in the shaders.

**Comment by Astrak** [comment]
Hey @bhouston , I am quite surprised about it too. Line 260 refers to `uniform float flipEnvMap` from the `envmap_pars_fragment`, reproduced hereafter. Few days earlier it was indicating line 261, I did not identify why this change occured but 261 is a line with `#if defined....` conditions ! At least, the `flipEnvMap` uniform value being -1 or 1 it makes more sense with the warning message `min range ... is (-2,2)` though the reasons behind that behaviour would still be unclear. I am not such an expert but I have been thinking it could be related to what is described here, though it would not be linked to lines 260 or 261 : http://stackoverflow.com/questions/17861635/glsl-es-precision-errors-and-overflows.

The `envmap_pars_fragment` part in the console warning report :
`247: #if defined( USE_ENVMAP ) || defined( PHYSICAL )`
`248:     uniform float reflectivity;`
`249:     uniform float envMapIntensity;`
`250: #endif`
`251: #ifdef USE_ENVMAP`
`252:     #if ! defined( PHYSICAL ) && ( defined( USE_BUMPMAP ) || defined( USE_NORMALMAP ) || defined( PHONG ) )`
`253:         varying vec3 vWorldPosition;`
`254:     #endif`
`255:     #ifdef ENVMAP_TYPE_CUBE`
`256:         uniform samplerCube envMap;`
`257:     #else`
`258:         uniform sampler2D envMap;`
`259:     #endif`
`260:     uniform float flipEnvMap;`
`261:     #if defined( USE_BUMPMAP ) || defined( USE_NORMALMAP ) || defined( PHONG ) || defined( PHYSICAL )`
`262:         uniform float refractionRatio;`
`263:     #else`
`264:         varying vec3 vReflect;`
`265:     #endif`
`266: #endif`

**Comment by pailhead** [comment]
This looks like a gamma issue?

**Comment by bhouston** [comment]
I've seen this warning before but it doesn't make sense on that particular line in the GLSL code. So I hven't tracked it down.  That is a nice SO answer.  I guess if we do math immediately on texture2D it is dangerous because those are lowp values on some devices.
