### ISSUE TITLE
What is the order of vertices that are drawn in BoxGeometry

### ISSUE THREAD

**Issue by Carpetfizz** [mrdoob/three.js#10746]
We are trying to figure out the order in which vertices are inserted into the geometry in order to create a `BoxGeometry`. This is an image of what we think this order is, based on the order of `geometry.vertices`

![cube](http://i.imgur.com/GyAzq7m.png)
We would appreciate if you could confirm or deny this. Also, a justification of why this ordering is chosen would be appreciated - does it conform to some OpenGL specification?

Thank you!

**Comment by mrdoob** [comment]
I think it'll be simpler if you have a read at the source code itself:
https://github.com/mrdoob/three.js/blob/dev/src/geometries/BoxGeometry.js#L39-L197

**Comment by mrdoob** [comment]
Also, if you use `BoxBufferGeometry` you can use [drawRange](https://github.com/mrdoob/three.js/blob/dev/src/core/BufferGeometry.js#L38) to limit what gets drawn. If you add a slider to that value you should see the order.

**Comment by yiakwy** [comment]
@mrdoob  Real hard to figure it out from the codes. Why don't we mark the points using topLeft, bottomRight, upperPlane, lowerPlane with axis direction so on so forth.

**Comment by yiakwy** [comment]
@Carpetfizz Have you resolved this?
