### ISSUE TITLE
Geometry of purely custom attributes does not render at all (position must be set)

### ISSUE THREAD

**Issue by frederikaalund** [mrdoob/three.js#10751]
##### Description of the problem 

BufferGeometry with only custom attributes does not render in r84. Said geometry used to render in r79 (I think the issue was introduced in r81).

Example:

    let geometry = new THREE.BufferGeometry();
    geometry.addAttribute('gc_position_x', new THREE.BufferAttribute(positionsX.value, 1));
    geometry.addAttribute('gc_position_y', new THREE.InterleavedBufferAttribute(positionsY, 1, c , false));
    geometry.setDrawRange(0, N);  

This used to render just fine in r79. In r84, I have to add the following line to get it to work:

    geometry.addAttribute('position', new THREE.BufferAttribute(positionsX.value, 1));

I don't even declare `position` in the shader but three.js r84 still forces me to add the attribute. I think the behaviour from r79 was better. Can this be re-introduced?

Thanks in advance!

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by makc** [comment]
reminds me this https://github.com/mrdoob/three.js/issues/7304#issuecomment-147096788

**Comment by mrdoob** [comment]
Yep! Try with `mesh.frustumCulled = false;`.

**Comment by makc** [comment]
@mrdoob the fiddle there has frustumCulled = false and does not work

**Comment by mrdoob** [comment]
Which jsfiddle?

**Comment by makc** [comment]
http://jsfiddle.net/1v2Lyftu/ nope
http://jsfiddle.net/b1u8czcw/ no worky
http://jsfiddle.net/g0v9ofxd/ a-ah, black screen here too

**Comment by frederikaalund** [comment]
Thanks for the feedback!

@makc Yes, the problem is exactly the same in the those fiddles as in my application. Thanks for sharing. Indeed, all three fiddles can be fixed by adding a single line:

    geometry.addAttribute( 'position', new THREE.BufferAttribute( indices, 1 ) );

My argument is: Why do we have to declare the `position` when we are not even using it in the shader? All three fiddles would have worked fine in r79. I think the issue was introduced in r81.

**Comment by pailhead** [comment]
This really didn't work with frustum culling disabled?

**Comment by pailhead** [comment]
i tried the fiddles, and its indeed strange

**Comment by michalburger1** [comment]
The problem is this line:
```
var drawEnd = Math.min( dataCount, rangeStart + rangeCount, groupStart + groupCount ) - 1;
```
Even if you specify a custom drawRange the Math.min call will reset it to zero because it thinks that there are no vertices.

The only solution I can think of without breaking backward compatibility is blindly obeying the drawRange but only if neither index nor position attributes are defined. What I would actually prefer is always obeying drawRange even if it seems to exceed the dataCount and let the developer deal with it but that might break some existing code.

**Comment by michalburger1** [comment]
(The regression must have been caused by this https://github.com/mrdoob/three.js/commit/31d125e6d4e5d8e6650cbc06b29afd1d8bb44276)
