### ISSUE TITLE
Trying to achieve a silhouette shader on hidden parts of a mesh

### ISSUE THREAD

**Issue by sampicsampic** [mrdoob/three.js#10760]
Hi!
I'm currently building a three.js scene in which I have two objects. When the front object passes in front of the other I wish its hidden parts to be visible over the mesh that's hiding it. Something simmilar as the Unity silhouette shader: 
http://wiki.unity3d.com/index.php?title=Silhouette-Outlined_Diffuse
(2nd image where the character is hidden behind a wall)
The best real example of which I can think of this effect in action is in the 3d Mario games. I've attached a image since its exactly the effect i'm tring to achieve.

Does anybody know how I can achieve such an effect or an example scene that uses it?
![image](https://cloud.githubusercontent.com/assets/16738328/22749221/8c6879f2-edfa-11e6-8a0c-bd3dd749f425.jpeg)

**Comment by makc** [comment]
I would guess, you want to have a hero copy that is black-sh, and has depthWrite = false, and the hero drawn normally after the copy, e g with transparent = true.
