### ISSUE TITLE
how to run code

### ISSUE THREAD

**Issue by Augmentedgirls** [mrdoob/three.js#10778]
How to run following webgl code 
[webgl_morphtargets_human.txt](https://github.com/mrdoob/three.js/files/764516/webgl_morphtargets_human.txt)

**Comment by fraguada** [comment]
https://threejs.org/examples/#webgl_morphtargets_human

(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)
