### ISSUE TITLE
webgl_geometry_spline_editor example looks broken

### ISSUE THREAD

**Issue by edap** [mrdoob/three.js#10786]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

Describe the problem/request in detail.
Code snippet, screenshot, and small-test help us understand.

You can edit for small-test.
http://jsfiddle.net/akmcv7Lh/ (current revision)
http://jsfiddle.net/hw9rcLL8/ (dev)

##### Three.js version

- [ ] Dev
- [ x] r84
- [ ] ...

##### Browser

- [] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

Hi,
I had a look at this example https://threejs.org/examples/?q=splin#webgl_geometry_spline_editor and I've seen that only one point is draggable. I do not think that this was the original behaviour. I've found this example http://betteridea.co.th/iinsure/3d/examples/webgl_geometry_spline_editor.html that use version 0.73 where all the points are draggable

**Comment by Mugen87** [comment]
Seems like there is a problem with `DragControls`. This example also doesn't work:

https://threejs.org/examples/webgl_interactive_draggablecubes.html

**Comment by Mugen87** [comment]
The problem can be solved if these two [lines](https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/DragControls.js#L55-L56) in `DragControls. onDocumentMouseMove` are changed to:

```javascript
_mouse.x = ( event.clientX / _domElement.clientWidth ) * 2 - 1;
_mouse.y = - ( event.clientY / _domElement.clientHeight ) * 2 + 1;
```

The problem is that `_domElement.width` and `_domElement.height`provides too large values that don't match to the size of the renderer if `devicePixelRatio` is greater than 1.

**Comment by edap** [comment]
you guys are fast ;)
