### ISSUE TITLE
BufferGeometry & WebGLRenderer does not result `attribute vec3 color`

### ISSUE THREAD

**Issue by backspaces** [mrdoob/three.js#10785]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

Using a BufferGeometry with a color attribute does not result in a shader with `attribute vec3 color`.

Yet https://threejs.org/docs/api/core/BufferGeometry.html states that color is a standard attribute.

To test this, I build identical Buffer and Shader versions of the same program:
> http://backspaces.net/temp/buffquad.html
> http://backspaces.net/temp/shaderquad.html

The first fails, having white quads, while the second succeeds with the correct behavior.

The program simply creates many quads of 5 different colors.  The diff between the two is simply:
```
diff buffquad.html shaderquad.html
11a12,34
>     vertexShader = `
>       // Added by ShaderMaterial; uncomment for RawShaderMaterial
>       // uniform mat4 modelViewMatrix;
>       // uniform mat4 projectionMatrix;
>       // attribute vec3 position;
>       attribute vec3 color;
>
>       varying vec3 vColor;
>
>       void main() {
>         gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );
>         vColor = color;
>       }
>     `
>     fragmentShader = `
>       precision mediump float;
>       varying vec3 vColor;
>
>       void main() {
>         gl_FragColor = vec4(vColor, 1.0);
>       }
>     `
>
130c153,154
<       material = new THREE.MeshBasicMaterial({side:THREE.DoubleSide})
---
>       material = new THREE.ShaderMaterial(
>         { vertexShader, fragmentShader, side:THREE.DoubleSide } )
```
The only difference being the shaders and different materials.
Note the need for the shader to declare the color attribute.
 
This is either a bug in the documentation or an inability of the BufferGeometry and WebGLRenderer to coordinate correctly, producing the desired attributes.

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Mac OS X Sierra
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Latest OS X, 1 yr old iMac

**Comment by WestLangley** [comment]
```javascript
material = new THREE.MeshBasicMaterial( { vertexColors = THREE.VertexColors } );
```
