### ISSUE TITLE
Specularity Acting Weird in Phong Material

### ISSUE THREAD

**Issue by BionicRabbit3** [mrdoob/three.js#10808]
##### Description of the problem 

As far as I understand, setting the specular color of a Phong material to 0x000000 should mean the material is not shiny at all.
From my tests this is not the case, and setting the specualr color to black still leaves a weak but visible shiny highlight.

This can clearly be seen in the interactive example at:
https://threejs.org/docs/index.html#Reference/Materials/MeshPhongMaterial
Set the map to grass (for better contrast),
Set the shininess to 100 (again, for better contrast),
Then set the specular to black.
You'll notice you can still see the shine on the material.

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by bhouston** [comment]
Can you post a screenshot?  Where the highlight is located matters a lot.

Basically I am thinking it may be Fresnel (see https://en.wikipedia.org/wiki/Fresnel_equations ) The reason is that Fresnel at grazing angles losses its dependence on the material's reflectivity.

**Comment by WestLangley** [comment]
`specular` is the per-channel specular reflectance of the material at normal incidence.

Even if `specular` is black, e.g. zero, light is still reflected specularly at grazing angles.

Understand Schlick's fresnel model.

**Comment by bhouston** [comment]
@WestLangley jinks. :)

**Comment by BionicRabbit3** [comment]
Does that mean that setting specular to black and reflectivity to 0 will remove all shine?

**Comment by bhouston** [comment]
IF you want true black for a Matte cutout-like workflow use a BasicMaterial I believe.

**Comment by BionicRabbit3** [comment]
What if I want a material with a bump map but no shiny highlights?

**Comment by pailhead** [comment]
Use lambert?

**Comment by BionicRabbit3** [comment]
According to the documentation, the Lambert material does not have a
bumpMap property

**Comment by RemusMar** [comment]
> What if I want a material with a bump map but no shiny highlights?

Use a small complete black specular map.

**Comment by BionicRabbit3** [comment]
Wouldn't that have exactly the same problem as using complete black as the color for the specular attribute? As in, still being shiny because of the Fresnel effect?

**Comment by pailhead** [comment]
Yes it would, and would introduce a texture lookup where there should be none. You need the bump map available on a lambert shader. Not sure why it's missing, since it's a completely viable thing to do. Something that reacts to light, can have bumpiness. Having it on `MeshBasicMaterial` would make no sense.

**Comment by RemusMar** [comment]
> Wouldn't that have exactly the same problem as using complete black as the color for the specular attribute?

If you combine them ( black texture + black color) you'll get a better result.
Just try and you'll see.

**Comment by BionicRabbit3** [comment]
Sorry, my English is not the best, so I didn't understand:
Are you saying there IS a bumpMap option in the Lambert material but it's just not documented? Or are you saying there is no option, but it SHOULD exist?

**Comment by pailhead** [comment]
I've no idea, ill look. Bump map is just a chunk that transforms the normals, the stuff that happens on top of those normals can be just lambert, phong, fresnel, could have the whole PBR thing doesnt matter. It's just the normal thats transformed. I'm not sure why it wouldnt be there, so maybe it's just not documented.

**Comment by BionicRabbit3** [comment]
Huh, that kinda sucks. 🙁 
If so, two things are left:
1. @mrdoob Feature request: make bumpMap an option in the Lambert material.
2. Is there actually a way then to have a non shiny material with a bump map?

**Comment by bhouston** [comment]
This is a very special use case of a non-physically accurate material.  MeshLambertMaterial in Three.JS uses a per-vertex lighting model, thus a bumpmap doesn't make any sense unfortunately with this material.

I would just write a custom shader to achieve what you want.

**Comment by pailhead** [comment]
That makes sense, I didn't even see a normal normalization there.

**Comment by BionicRabbit3** [comment]
What about a standard material with 0 metalness and 100% roughness? Is that not actually not shiny, or is the shine so big it covers the whole material? (It doesn't seem shiny at all to me...)

**Comment by pailhead** [comment]
You should still get sime rim lighting

**Comment by WestLangley** [comment]
@BionicRabbit3 `MeshPhongMaterial` has a `shininess` parameter. Did you set it to 0 ?

**Comment by pailhead** [comment]
I think he's saying that we still see it, it's just really diffused?

**Comment by pailhead** [comment]
When you look at [wikipedia](https://en.wikipedia.org/wiki/Blinn%E2%80%93Phong_shading_model) for Blinn-Phong, there is no mention of fresnel or rim lighting? [Phong](https://en.wikipedia.org/wiki/Phong_reflection_model) article doesn't mention it either. The graphics in the phong article just show adding the N dot L and V dot RL. The blinn-phong article has a code example where it seems that spec color would completely eliminate the term. 

There is a lot more going on in three's phong shader?

**Comment by pailhead** [comment]
> Use a small complete black specular map.

Is actually what you're looking for, apologies @RemusMar. 

There is a specularStrength that seems to be locked to `1.0` but can be modulated by a texture if a spec texture is present. Hence, an all black texture would cause this to be `0.0` and it looks like it would completely eliminate the term. 

I'd kinda expect this value to be exposed to the user. I think old school 3ds max materials worked like that, you'd have the color, glossiness and specular strength. 

```glsl
float specularStrength;

#ifdef USE_SPECULARMAP

	vec4 texelSpecular = texture2D( specularMap, vUv );
	specularStrength = texelSpecular.r * uSpecularStrength;

#else

	specularStrength = uSpecularStrength;

#endif
```

**Comment by BionicRabbit3** [comment]
Thanks guys, it worked! 😄 

If that's the case, then feature request:
Expose the specular strength as a variable for the Phong material.

**Comment by pailhead** [comment]
I did it on all the materials that have specular map, but it might be needed only on phong? If it's needed at all that is :)

**Comment by bhouston** [comment]
Specular strength is either a measure of Fresnel Reflectance at F0 (we implemented this in the physical material as reflectance) or it is a measure of glossiness (e.g. roughness.)  Either way, specular strength should not have the capability of reducing Fresnel at the rim to nothing, thus if it is behaving this way or you want it to behave this way it is a bug.

Fresnel is always present in physically based models.  You do not get to remove it and still be a physically based model -- you are purposely trying to create a special effect that is non-physical.

See this page here for more: http://filmicworlds.com/blog/everything-has-fresnel/

**Comment by bhouston** [comment]
I think you should be creating your own shader rather than trying to make physically correct shaders incorrect for your specific needs.

**Comment by pailhead** [comment]
Wait i'm confused. Right now you can put in a black texture in the specularMap slot and get some output. You can also put in a white texture and get some different output. You're saying that as is, it's buggy? Per #9339 ?

**Comment by bhouston** [comment]
@pailhead Interesting find, I forgot about that conversation.  I agree with this old comment in that thread: https://github.com/mrdoob/three.js/issues/9339#issuecomment-233134206

**Comment by pailhead** [comment]
Still, would it be useful to modulate the modulating texture? I know it introduces another multiplication, but it may help the user dialing in the texture. Rather than going into photoshop, changing the values or something it could be just multiplied to get the sense of the values?
