### ISSUE TITLE
Proposal: VectorN.copy accepts vectors of different sizes

### ISSUE THREAD

**Issue by jayschwa** [mrdoob/three.js#10809]
I propose implementing a backwards-compatible change for vector `copy` methods where only the components that exist on input vector `v` are copied to `this`. Example:

```javascript
if ("x" in v) this.x = v.x;
if ("y" in v) this.y = v.y;
if ("z" in v) this.z = v.z;
```

Conceptually, this will allow `copy` to be used like a poor man's version of GLSL swizzling (e.g. `someVec3.xy = someVec2`). This would be useful on my current project where I'm positioning objects in 3D space from various vector sizes - sometimes 3D coordinates, and sometimes 2D coordinates from a tile-based map format.

Performance comparison of current and proposed implementations on my machine: https://www.measurethat.net/Benchmarks/ShowResult/4485

I am willing to implement the proposal, but I wanted to get approval / feedback first before starting.

**Updates:**

* Changed `if` condition from `v.c !== undefined` to `"c" in v` to address [feedback from WestLangley](https://github.com/mrdoob/three.js/issues/10809#issuecomment-280132996).

**Comment by WestLangley** [comment]
The problem with that implementation is if you pass in a `Vector3`, the copy will not necessarily be a copy.

**Comment by jayschwa** [comment]
Do you mean in cases where `v` deliberately has a component set to `undefined`?

**Comment by WestLangley** [comment]
Yes. I know it is an unusual case, but a copy should be an exact copy, IMHO.

**Comment by jayschwa** [comment]
Good point, thank you. I have updated the proposal to check for the existence of a component with `"c" in v` instead of `v.c !== undefined`.

**Comment by WestLangley** [comment]
Now my previous comments make no sense. Please restore your original post and suggest alternatives in the comments, instead.

**Comment by jayschwa** [comment]
The original post will reflect the latest updates so that new readers don't have to mentally "apply diffs" from comments. I added change log at the bottom of the original post so that context is retained.

Anyhow, I'd like to start on this if it's likely to be accepted. Is @mrdoob ultimately the one that needs to weigh in?

**Comment by WestLangley** [comment]
>The original post will reflect the latest updates so that new readers don't have to mentally "apply diffs" from comments. I added change log at the bottom of the original post so that context is retained.

@jayschwa As I said, please don't do that after users have commented. Readers have no way of knowing if a comment was made before or after the edit to your post.

**Comment by mrdoob** [comment]
I fear this may be pretty project specific...
Maybe you can just override the function for your project?

```js
THREE.Vector3.prototype.copy = function ( v ) {
    if ("x" in v) this.x = v.x;
    if ("y" in v) this.y = v.y;
    if ("z" in v) this.z = v.z;
    return this;
};
```

**Comment by WestLangley** [comment]
We use the pattern
```javascript
object.setFromClass( source );
```
when `source` is of a different type than `object`.

So in your case, it would be
```javascript
Vector3.setFromVector2( v );
```
I am not sure that make sense for most users.

**Comment by jayschwa** [comment]
Makes sense. Thanks for taking a look.
