### ISSUE TITLE
Daydream issue with objects attached to camera

### ISSUE THREAD

**Issue by HalfdanJ** [mrdoob/three.js#10805]
Attaching an object to the threejs camera in a webvr scene, for example a crosshair, should result in the object being completely static on the screen when rotating the head. But in daydream, it seems like the position is always rendered 1 frame behind. This is not the case in polyfill or vive on desktop, so not sure if its a daydream or threejs issue. 

Example: https://threejs.org/examples/#webvr_cubes 

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
- [x] Daydream

**Comment by mkeblx** [comment]
I didn't notice this issue testing on PixelXL+Daydream. But yes sometimes head-locked objects are the ones to most noticeably lag due to reprojection/latency issues. I don't believe is a threejs issue directly.

**Comment by HalfdanJ** [comment]
I've got it confirmed that it's due to reprojection on the daydream, and a threejs bug.

**Comment by mrdoob** [comment]
> I've got it confirmed that it's due to reprojection on the daydream, and a threejs bug.

What threejs bug?

**Comment by HalfdanJ** [comment]
Sorry, typo, meant "and **not** a threejs bug"

**Comment by mrdoob** [comment]
Yeah, I was thinking that maybe it was because the camera is not in the scene and is not updating its `matrixWorld` in time (probably should fix this), but the camera is in the scene in that example.
