### ISSUE TITLE
Editor: defines in ShaderMaterial INFO tab are not exported when exporting a scene

### ISSUE THREAD

**Issue by mhirsch** [mrdoob/three.js#10810]
##### Description of the problem 

In the threejs.org/editor, when defining a shader material, there is an INFO tab with a `defines` and `uniforms` object. Items filled in in the `defines` object do not show up in the `.json` file when `Export Scene` is selected from the `File` menu.

For example, in the r84 editor, create a new scene. Add a plane. Change the material to ShaderMaterial. In the INFO tab, modify the code to read:

```
{
	"defines": {
		"TEST": "1.0"
	},
	"uniforms": {}
}
```
In the VERTEX tab, modify the code to read:

```
void main() {
	gl_Position = projectionMatrix * modelViewMatrix * vec4( position, TEST );
}
```

Select File -> Export Scene. Open the `.json` file. Note that `TEST` only appears once. The subsequent scene does not render correctly when loaded, since the vertex shader fails to compile due to the missing definition of TEST.

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
This issue is solved with the next release (`R96`) via #14693. 🎉
