### ISSUE TITLE
VR examples not working in mobile Chrome Canary

### ISSUE THREAD

**Issue by spiderworm** [mrdoob/three.js#10812]
After enabling WebVR in Chrome Canary, I am able to enter VR mode (stereoscopic cameras and full screen) with several WebVR demos across the web (including http://codepen.io/davatron5000/full/WrwxJd). However, none of the Three.js WebVR examples (https://threejs.org/examples/) enter VR mode.

**Comment by mkeblx** [comment]
Are you using a Daydream compatible phone i.e. Pixel/PixelXL? Native WebVR API support is currently only enabled for Daydream phones. Your first link (as do many examples out there) uses the WebVR polyfill which provides partial support if it doesn't exist already; the Three.js WebVR examples do not use the polyfill.

**Comment by spiderworm** [comment]
I see. No, I do not use a Pixel, so that does clear things up a bit.

On that note, why not include the WebVR polyfill for those of us with phones that are a year or two old?

**Comment by mrdoob** [comment]
> On that note, why not include the WebVR polyfill for those of us with phones that are a year or two old?

Because when things don't work it will be even harder to figure out why it doesn't work 😖
