### ISSUE TITLE
getObjectByName doesn't work

### ISSUE THREAD

**Issue by alaprajz** [mrdoob/three.js#10813]
Dear MrDoob,
you never give me answer, but I respect and admire your job.
I read three.js / docs and stackoverflow and I have been trying to sold this questions for weeks.
I know that this answer is just a minute for you but this would means a month to sold or bypass the problem to me.
I would like ask:
getObjectByName of oLoader doesn't work, why?

var geometry = new THREE.SphereGeometry( 0.5, 32, 32 );
var material = new THREE.MeshBasicMaterial( {color: 0xffff00} );
var sphere = new THREE.Mesh( geometry, material );
sphere.name='gomb';
scene.add( sphere );

var objname = scene.getObjectByName('sphere', true );
function remove(id) {
  scene.remove(id);
}
remove(objname);

//-------------------------  is working-----------------------

var oLoader = new THREE.OBJLoader();
oLoader.load('model/0004_02_00_FF_00_xxxxxx_0_00.obj', function(object, materials) {
material_this = new THREE.MeshPhongMaterial( {
				color: 0x00FF00, 
				} );
	object.traverse( function(child) {
		if (child instanceof THREE.Mesh) {
		child.material = material_this;
		child.castShadow = true;
		child.receiveShadow = true;
		}
	});

object.position.x = 0;
object.position.y = 0;
object.position.z = 0;
object.name='0004_02_00_FF_00_xxxxxx_0_00';
scene.add(object);
});

var objname = scene.getObjectByName('0004_02_00_FF_00_xxxxxx_0_00', true );
function remove(id) {
  scene.remove(id);
}
remove(objname);

//-------------------------  doesn't work, why?---------------------

 Three.js version:latest

- [ x] Dev
- [ ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Because `oLoader.load()` is asynchronous. By the time you're doing `object.traverse()` the object hasn't loaded yet.

**Comment by alaprajz** [comment]
I understand the problem but I don't found solution.
(I tried children and parent functions)
What is your suggestion, please?
