### ISSUE TITLE
Shadow with PointLight not working

### ISSUE THREAD

**Issue by manumid** [mrdoob/three.js#10818]
##### Description of the problem 
PointLight shadows are not working.

JSFiddle with SpotLight: https://jsfiddle.net/manumid/krpgr0x0/2/ -> shadows working
JSFiddle with PointLight: https://jsfiddle.net/manumid/krpgr0x0/3/ -> shadows not working

The only difference in the code is the Light type used and their Light Helper respectively.

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
It is a symptom of https://github.com/mrdoob/three.js/issues/8559

Proposed patch is https://github.com/mrdoob/three.js/pull/10668

Updated fiddle to show the problem: https://jsfiddle.net/krpgr0x0/4/

/ping @tailsu
/ping @bhouston

**Comment by sasha240100** [comment]
@WestLangley Are you sure that fiddle is working?
![image](https://cloud.githubusercontent.com/assets/7657429/23079746/e5bef9dc-f556-11e6-905e-9e1b22b77f3f.png)

**Comment by WestLangley** [comment]
@sasha240100 The fiddle you linked to should demonstrate the bug: the lighting is clipped to a particular range for objects for which `receiveShadow` is `true`.

![screen shot 2017-02-17 at 2 30 20 pm](https://cloud.githubusercontent.com/assets/1000017/23080179/d38d5da0-f51d-11e6-8a5f-8856cd5090ed.png)

**Comment by sasha240100** [comment]
@WestLangley thanks! Now I understand.

**Comment by WestLangley** [comment]
Closing. See #11764
