### ISSUE TITLE
Is there a perfect way to import FBX or convert FBX to any format threejs supported?

### ISSUE THREAD

**Issue by etflly** [mrdoob/three.js#10815]
I have tried FBXLoader, convert_to_threejs,py, blender exporter, none of these could load or convert all FBX version:

- FBXLoader doesn't support binary FBX.
- convert_to_threejs is deprecated according to #5983
- blender could not import ascii FBX

So is there a perfect way to import FBX or convert FBX to any format threejs supported?

**Comment by donmccurdy** [comment]
You may want to try [FBXLoader2](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/FBXLoader2.js), or the most recent (unreleased) version of [FBXLoader](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/FBXLoader.js). There has been active work going on with those, and it looks promising. Binary FBX is still not supported, though.

***

BEGIN SELFISH PROMOTIONAL

You might also try converting to glTF: there are [several converters here](https://github.com/KhronosGroup/glTF#converters), and a Blender exporter. If you choose a converter, I suspect that you'll have better luck going FBX→DAE→GLTF than straight FBX→GLTF. Sketchfab also released a [Unity→GLTF exporter](https://github.com/sketchfab/Unity-glTF-Exporter), which I haven't tried yet.

^This won't be bug-free either, frankly, but we're very much "working on it" and would be glad for reports of any bugs you run into. Thanks!

END PROMOTIONAL

(I'm helping to maintain THREE.GLTFLoader and am slightly biased. 😬 )

**Comment by etflly** [comment]
Thanks for the help! I have tried [FBX-glTF](https://github.com/cyrillef/FBX-glTF) converter which works fine for me.

But when I tried to load a glTF file which was converted from a FBX file produced by FBX 2017 SDK, I got following error:

Unhandled shader semantic: COLOR_0
THREE.GLTFLoader.GLTFShader.update @ GLTFLoader.js:234
update @ GLTFLoader.js:115
animate @ webgl_loader_gltf.html:366

**Comment by donmccurdy** [comment]
For the COLOR_0 error, we fixed a bug that sounds a lot like that in r84. What version of Three.js are you on? If it's < r83 I'd try upgrading. If >= r83, it would be awesome if you can share an example model for me to test (might be our code, might be the converter).

I suggest FBX->DAE->GLTF because the DAE->GLTF converter is maintained by the Khronos team (who design glTF). The FBX->GLTF converter is maintained by Autodesk, which *would* be promising, except that it hasn't been updated in 11 months. Also it doesn't support animation yet.

**Comment by makc** [comment]
assimp2json could do the conversion, but their json is not 3js json, needs special loader (from examples folder)

**Comment by mrdoob** [comment]
How about the new AssimpLoader?

https://threejs.org/examples/?q=assimp#webgl_loader_assimp

**Comment by hmtri1011** [comment]
@mrdoob Hi, how can I implement web_gl_loader_assimp with .fbx (binary) model?
