### ISSUE TITLE
CocoonJS canvas+ and threejs with pixi. r83 and up not working at all.

### ISSUE THREAD

**Issue by khalimwu** [mrdoob/three.js#10825]
Been trying to deploy for cocoonJS using threejs and pixi. Made a simple example to show the problem.

[https://codepen.io/anon/pen/egawoq](https://codepen.io/anon/pen/egawoq)

Note: threejs stopped having cocoon support out of the box after r71. using a fresh pixi.js - v4.3.5 and threejs r71 will allow you to run it with the cocoonjs dev app.

The problem is that as soon as i have a mesh on scene, it seems like the renderer cleans up the rendered screen from pixi. Im still receiving the input events from my controls but no rendered image. pixi is using canvasRenderer so its not because they are using the same renderer type.

Version:
Example is on r71. Same behavior (after tweaking the library) on every other release up to r83.
r83 to above : It doesnt even launch, 'wrong shader program, cant compile'.

- [x] CocoonJS
- [x] Android

Edit: updated the codepen to show how the rendering on pixi gets inverted after the threejs render is done with its work (and removed from the domelement)

**Comment by mrdoob** [comment]
Hmm... We never "supported" CocoonJS. It's up to CocoonJS to support three.js...

**Comment by mrdoob** [comment]
You should report this to the CoocoonJS project.

**Comment by khalimwu** [comment]
Sorry for reopening this. I was half aware that this is more a cocoonJS issue, as three and pixi works fine on regular browsers ( i did think you were interested in supporting it ). Was just wondering if you could give me a hint of what could be going on, since it looks like the threeJS rendering is being prioritized. tried changing rendering order, manually clearing, not clearing at all.

**Comment by dmtaub** [comment]
If you don't use canvas+, and use the web GL webview with cocoon , it
probably works fine... Canvas plus has limited feature set, I had all sorts
of problems trying to use it with three.

**Comment by khalimwu** [comment]
Yes, with webview+ it works just fine.
