### ISSUE TITLE
Bug in DoubleSide?

### ISSUE THREAD

**Issue by cbeust** [mrdoob/three.js#10824]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

Example here:  http://jsfiddle.net/uawfq6t3/

This is a cube with all `ShadowMaterial` sides except the front and back. However, you'll notice that these two sides are dark on the inside of the cube instead of having a color, despite them being `DoubleSide`.

##### Three.js version

- [ ] Dev
- [ ] r84
- [x] Latest

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Shadows doesn't work with `DoubleSided`. You'll have to duplicate the polygons in your geometry.

**Comment by cbeust** [comment]
I'm curious: why?

Is this an implementation limitation? We're using an ambient light, shouldn't it light everything, including double sides?
