### ISSUE TITLE
[io_three] Use object origin for exporting

### ISSUE THREAD

**Issue by brainscript** [mrdoob/three.js#10855]
I'm currently working on a game with a lot of models which I create in [Blender](https://www.blender.org/) and export using the [`io_three` addon](https://github.com/mrdoob/three.js/tree/master/utils/exporters/blender/addons/io_three). I store all of them in the same file and the same scene.

When I export them using the addon the vertices in the exported file are **relative to the scene's center**. As far as I've seen there's no option to make them **relative to the object's origin** which is very important for my game, because players can place models with their mouse cursor, that's why I need the origin.

*Please add a checkbox on the export screen to enable that. :cat: :pray:*

**Comment by mrdoob** [comment]
Is this exporting a geometry or exporting the object?

**Comment by brainscript** [comment]
@mrdoob The `io_three` addon? It exports geometry, material settings and a lot more.

![screenshot](https://cloud.githubusercontent.com/assets/8706734/23315888/7197e236-fac8-11e6-94a5-faaf42ab5f84.png)

So yes, but the option I suggested would only affect the geometry anyway as far as I know.

**Comment by mrdoob** [comment]
Can you share an example of a file you're exporting that has the vertices relative to the scene origin?

**Comment by brainscript** [comment]
@mrdoob I just created a new scene, moved the default Blender cube while in **Object Mode** (I therefore didn't move the vertices), exported it and loaded it into my scene. And it was not at `0|0|0` where I wanted it to be. And yes, after resetting the model's position in Blender, reexporting and reloading it into the scene everything worked fine, it was at `0|0|0`.

If you want to recreate this just create a new Blender file, move the cube and export.

**Comment by mrdoob** [comment]
Can you share the file you created? I don't have access to Blender at the moment.

**Comment by brainscript** [comment]
@mrdoob 
The Blender file: https://file.io/hT68Jm
The JSON file: https://file.io/9eCCoE
The correct JSON file (where I didn't move the cube): https://file.io/QLcDDu

**Comment by makc** [comment]
I tried
> moved the default Blender cube while in Object Mode (I therefore didn't move the vertices), exported it

and I have no offset in geometry. my exporter must be older, because it does not have 'apply modifiers' option

**Comment by netgusto** [comment]
> and I have no offset in geometry. my exporter must be older, because it does not have 'apply modifiers' option

Neither do I, using latest blender (2.78c) and latest io_three (freshly downloaded from the github repo).

**Comment by jostschmithals** [comment]
I can reproduce @brainscript's issue with latest blender (2.78c) and latest io_three. If I export a cube which is translated in blender (using the exporter's default settings), the pivot point in three.js is not in the center of the cube, but in the center of one side.

**Comment by manthrax** [comment]
@makc By not having "scene" checked, you are using the geometry only exporter. I think it is making some assumptions that are not what you want.

Can you try the same experiment with "scene" checked on export, and pull your objects out of the imported scene instead?

**Comment by MarkStevens75** [comment]
Same issue for me using r87 and Blender 2.79, ( with scene on) was fixed issue by reverting blender addon back to the exporter used in r79 but still using threejs r87 for the rendering.

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
