### ISSUE TITLE
The bug of CanvasRenderer

### ISSUE THREAD

**Issue by zhoushijie163** [mrdoob/three.js#10853]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 

![2017-02-21_16-04-45](https://cloud.githubusercontent.com/assets/18611035/23157611/e0deca66-f856-11e6-80f8-d9bea9d02539.png)

##### Three.js version

- [x] Dev
- [x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [x] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

**Comment by zhoushijie163** [comment]
Previous versions of R71 are correct.

**Comment by mrdoob** [comment]
Fixed!
