### ISSUE TITLE
camera scripts in editor don't get saved

### ISSUE THREAD

**Issue by felipemanga** [mrdoob/three.js#10854]
##### Description of the problem 

Hello.
In the editor, scripts belonging to the camera are not saved.
The editor.toJSON method does not check if scripts belong to the camera, and editor.fromJSON does not restore the saved camera's uuid.

To replicate the issue:
In the Outliner, click on "camera".
Add a script.
click on "scene"
click on "camera"
script is gone. Is this the intended behavior?

AFAIK, the fix is simply:

Editor.js/fromJSON:
this.camera.uuid = camera.uuid;

Editor.js/toJSON:
if ( script.length === 0 || ( key !== this.camera.uuid && scene.getObjectByProperty( 'uuid', key ) === undefined ) ) {

but I don't know if changing the camera's uuid would have further consequences. I've applied these changes locally and haven't noticed any problems so far.

##### Three.js editor version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Decided to solve this by disallowing scripts being added to the camera. We may revisit this at some point.

**Comment by mrdoob** [comment]
Thanks for reporting though!
