### ISSUE TITLE
Threejs custom function “Object3D.prototype.toJSON ( meta )” and standard interface function “Date.prototype.toJSON ( key )” conflict

### ISSUE THREAD

**Issue by zhoushijie163** [mrdoob/three.js#10865]
##### Description of the problem 
Threejs custom function “Object3D.prototype.toJSON ( meta )” and standard interface function “Date.prototype.toJSON ( key )” conflict.
This causes an error when running the function "JSON.stringify()".

http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.5.44

##### Three.js version

- [x] Dev
- [x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by zhoushijie163** [comment]
http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.5.44

**Comment by mrdoob** [comment]
Could you create a jsfiddle showing the issue?

**Comment by zhoushijie163** [comment]
http://jsfiddle.net/bn0sLaa1/13/

**Comment by zhoushijie163** [comment]
http://jsfiddle.net/bn0sLaa1/14/

**Comment by zhoushijie163** [comment]
http://jsfiddle.net/bn0sLaa1/17/     (Dev)
http://jsfiddle.net/bn0sLaa1/16/     (R84)
Click the DIV  to can see this Error.

**Comment by zhoushijie163** [comment]
Can you fix it?

**Comment by Mugen87** [comment]
I've cleaned up the your fiddle a little bit: https://jsfiddle.net/bn0sLaa1/29/

With the new code, I'm unable to reproduce. Check out how serialization/deserialization of the scene graph is handled.
