### ISSUE TITLE
Number.isInteger not supported in IE

### ISSUE THREAD

**Issue by fraguada** [mrdoob/three.js#10872]
##### Description of the problem 

`Number.isInteger` is not supported in Internet Explorer and thus when using `ObjectLoader` there is an error when getting to [this line](https://github.com/mrdoob/three.js/blob/dev/src/loaders/ObjectLoader.js#L570).

Solution, in my case, was to use the [polyfill provided by Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger).

##### Three.js version

- [x] Dev
- [x] r84

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Added. Thanks!
