### ISSUE TITLE
Request for Callback on JSONLoader to change json 

### ISSUE THREAD

**Issue by greenred123** [mrdoob/three.js#10870]
##### Description of the problem

I am currently using three js with a backend service which I request the JSON and then the texture files from. When I request the texture files, the url does not end with the filename. 

For example I upload "texture1.jpeg" and "texture2.jpeg" to the backend.
I download them using urls that look a bit like this:
texture1.jpeg:  https://something.com/files/assets/5/something/49750349850349
texture2.jpeg: https://something.com/files/assets/5/something/59843095884304

At the moment I am solving this problem by writing the urls for the textures in the json file before uploading it to the backend, but this is not a great long term solution. Therefore I would like to be able to change the filenames in the json using a callback. This could also be used by other three js users to change other values in the json object before it is parsed.
 
For example:

```

Object.assign( JSONLoader.prototype, {

		load: function( url, onLoad, onProgress, onError, jsonEdit ) {

			var scope = this;

			var texturePath = this.texturePath && ( typeof this.texturePath === "string" ) ? this.texturePath : Loader.prototype.extractUrlBase( url );

			var loader = new FileLoader( this.manager );
			loader.setWithCredentials( this.withCredentials );
			loader.load( url, function ( text ) {

				var json = JSON.parse( text );
                                jsonEdit(json);
				var metadata = json.metadata;

```

##### Three.js version

- [x ] Dev
- [x ] r84

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
I think that's a bit too much for the library to handle...

**Comment by yomotsu** [comment]
@greenred123 
That is already possible!

You can make a [bypass with `THREE.JSONLoader.protptype.parse`](https://github.com/yomotsu/xmas2016/blob/master/src/js/utils/zipFileManager.js#L107) and [customized `THREE.Loader.Handlers`](https://github.com/yomotsu/xmas2016/blob/master/src/js/utils/zipFileManager.js#L123-L134)

**Comment by greenred123** [comment]
@yomotsu Thank you! I will take a look at this!
