### ISSUE TITLE
Draw multi materials on non indexed instanced geometry

### ISSUE THREAD

**Issue by Flur** [mrdoob/three.js#10875]
##### Description of the problem 

Multi materials don't work on non indexed instanced geometry.
Proposal #10842 

##### Three.js version

- [x ] Dev
- [x] r84

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by ffdead** [comment]
+1
