### ISSUE TITLE
STLLoader's binary check trips up

### ISSUE THREAD

**Issue by dnewman-polar3d** [mrdoob/three.js#10883]
##### Description of the problem 

The STLLoader's logic for determining if an STL data is ASCII or binary can get tripped up and declare some ASCII STL data to be binary.

##### Describe the problem/request in detail.

First note that an ASCII STL data must start with the string "solid " [trailing space intentional].

Now, the isBinary test in STLLoader begins by seeing if the data is a valid STL binary.  Let's accept that there is a reason to not first check for the string "solid " at the beginning.  When this binary check arrives at a computed data length which differs from the actual data length, it then attempts a second check.  (It used to not do this second check and just declare the data to be in ASCII format.)

This second check scans the data looking for any 8bit characters for which the 8th bit is set high.  That on the assumption that an ASCII formatted data uses US-ASCII and thus has no characters with the 8th bit set.  And that's where the problem lies.   We're seeing more and more "ASCII" STL files for which the optional name field following "solid " contains non-US-ASCII characters.  That trips up this binary test.

Now, you might say, "Well, that's an invalid ASCII STL file".  And you'd be right.  But we're already making this 8bit check because we think we may be accommodating a dubious binary STL file -- a binary STL file whose length is off.  So, pick your poison.

And note that this behavior is a behavior regression: older versions of three.js didn't make this additional check and thus "properly" detected these dubious ASCII STL files to be ASCII.

There's a couple of ways to address this, both involve checking the first few bytes of the data for the string "solid".  (You can be more strict and require "solid " with the mandatory trailing space, but I've seen plenty of ASCII STL files which didn't have that space...)  This check can be put before the binary length check, or right after it but before the check for bytes with the 8th bit high.  Here's sample working code,

        // Do we see 'solid' in the first few bytes of the file?
        // STL must begin with 'solid '
        var fileLength = reader.byteLength;
        if ( fileLength > 50 ) fileLength = 50;
        var solid = [ 115, 111, 108, 105, 100 ];
        var i = 0;
        for ( var index = 0; index < fileLength; index ++ ) {
          if ( reader.getUint8( index, false ) == solid[i] ) {

            i++;

            if ( i == 5 ) {

              // 'solid' seen near the start of the file
              return false;

            }

          } else {

            i = 0;

          }
        }

That code is overly liberal and just wants to see "solid" within the first 50 bytes....  It can be made more strict.  I've not seen an STL file with junk before the "solid" nor do ASCII STL files allow comments.  I coded it that way since I originally was looking within the first 100 bytes for "facet".  (Hey it was late, I was tired.)

##### Testing

It's fairly easy to make an ASCII STL file which will trip the current code up: edit the first line to contain a name field containing non-US-ASCII chars with the 8th bit set; e.g.,

    solid 穿山甲
    facet normal 0.7071067717164974 -0.00016366188967739515 0.707106771716591
      outer loop

##### Three.js version

- [*] Dev
- [*] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

None.

**Comment by mrdoob** [comment]
Nice! Would you like to do a Pull Request?

**Comment by dnewman-polar3d** [comment]
Pull Request generated.
