### ISSUE TITLE
SpotLightHelper incorrect positioning inside of Group

### ISSUE THREAD

**Issue by dennisss** [mrdoob/three.js#10887]
##### Description of the problem 

When creating a SpotLight added to a transformed group, adding a SpotLightHelper to the same group causes the SpotLightHelper to be incorrectly positioned. I'm assuming that this is due to the SpotLightHelper using the world matrix of the SpotLight. So the helper's matrix is being twice transformed: MatrixHelper = GroupMatrix * SpotLightWorldMatrix.

See below (line 52 is problematic): 
https://jsfiddle.net/qy7nwf35/

White helper lines should line up with boundaries of light:
<img width="403" alt="screen shot 2017-02-26 at 11 27 54 am" src="https://cloud.githubusercontent.com/assets/1341104/23341488/ad45b3ae-fc16-11e6-95f5-accbab85710c.png">

##### Three.js version

- [x] r84

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
Helpers are designed to be added directly as children of the scene -- not as children of the target object, or any other object.
