### ISSUE TITLE
example webgl_geometry_spline_editor DraggableControls not working in Chrome/Firefox

### ISSUE THREAD

**Issue by goretkin** [mrdoob/three.js#10891]
I am trying to use the example at https://threejs.org/examples/?q=spline#webgl_geometry_spline_editor .
It appears that I cannot reliably drag the control points. Sometimes while changing perspective, the dragging controls appear, but I can't get this to happen reliably. 

OS X 10.9
Firefox 51.0.1
Google Chrome 56.0.2924.87

**Comment by looeee** [comment]
I've tested this in Chrome Version 57.0.2987.74 beta (64-bit) and Firefox 51.0.1 on Windows 10 and can't see any problems - can you be more specific about the issue you are seeing? And also provide your browser versions and operating system?

**Comment by goretkin** [comment]
I've edited the original message to include browser/OS info.

I am expecting the dragging controls to appear when I hover or click on the cubes. Is that right? I'm struggling to describe the issue partly because I can't tell what the correct behavior is.

**Comment by looeee** [comment]
> I am expecting the dragging controls to appear when I hover or click on the cubes

That's the behaviour that I am getting at least. 

What do you mean by changing perspective? Moving the camera around?

**Comment by Mugen87** [comment]
I can reproduce. The problem is that the HTML section for spline configuration interferes with the controls event handling (the container element extends over the whole width of the screen). I've created a PR that introduces `dat.gui` for configuration. This solution is more consistent compared to other examples.

**Comment by Mugen87** [comment]
For Clarification: The red area is currently problematic...

![editor](https://cloud.githubusercontent.com/assets/12612165/23357813/b10b9322-fcdf-11e6-888d-e8befff63684.png)

**Comment by looeee** [comment]
Ah good catch. Won't there still be problems with the Dat.GUI overlay though? 

Currently if I add `display: none` to the offending html elements and then drag a control point over the stats weird things happen. 

Still, it will be an improvement over the current behaviour.

**Comment by goretkin** [comment]
I will give the PR a shot. However, I will say that I cannot drag the cube currently whether they are in that problematic red region, or not.

**Comment by goretkin** [comment]
I think I'm still seeing the same behavior. Here's a screen capture. You can see on the second take (after I hit refresh), one of the controls appears spontaneously as I'm moving the camera.

https://youtu.be/2N3vDqikXOA

**Comment by Mugen87** [comment]
Um, that's strange. I can't reproduce but i'll try it on an other PC. 

> Won't there still be problems with the Dat.GUI overlay though?

@looeee Yep, but the problematic region is much smaller. Besides, you can close the controls so they use only a minimum amount of screen space.

**Comment by Mugen87** [comment]
Maybe related to #10786

@goretkin  Can you please test with the `dev` branch of `three.js`? There is an fixed version of `DragControls`...

**Comment by goretkin** [comment]
That was it, my issue was a duplicate! However, I'm glad for the update in the controls too.
