### ISSUE TITLE
Blender's spotlight.distance value being ignored by blender2threejs exporter

### ISSUE THREAD

**Issue by Friksel** [mrdoob/three.js#10902]
ThreeJS exporter for blender is ignoring spotlight's distance values while exporting a scene, setting the distance to 0 hardcoded in object.py, causing spotlights to shine 'endless'.
The comment in the python file (object.py) says on line 49 (threejs r84): `# Commented out because Blender's distance is not a cutoff value.`
But setting the distance by code to the value I use in blender seems to work the same as in blender (has the same effect as far as I can tell). 
Does this value still needs to be commented out? Does this get a fix? Or could it be restored to the original blender distance value to be able to set the distance value inside blender?

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
