### ISSUE TITLE
TransformControls: Scale Controls too sensitive

### ISSUE THREAD

**Issue by msj121** [mrdoob/three.js#10916]
Even looking at the example given by threejs I think you will find that when one drags the scale controls the object goes to size extremes. I think for a small amount of movement the controls should be somewhat calibrated to produce smal but meaningful changes in scale

https://threejs.org/examples/misc_controls_transform.html

**Comment by jostschmithals** [comment]
You can change the scaling amount in lines  981, 991, 992, 993 of https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TransformControls.js

like this: #9312 (first comment) 

or like this: http://stackoverflow.com/questions/26463872/scaling-small-objects-using-three-transformcontrols 

(but this is not very convenient and it would indeed be nicer to have a possibility to adjust the scaling from outside - #5489).

**Comment by msj121** [comment]
@jostschmithals Sadly the new approach has been posted to remove "scalespeed" variable and I still have issues with large models that have been scaled down to still have even small changes make large impacts
