### ISSUE TITLE
AnimationAction: Shouldn’t action.isRunning() check the weight, too?

### ISSUE THREAD

**Issue by jostschmithals** [mrdoob/three.js#10913]
AnimationAction’s methods `isScheduled()` and `isRunning()` are clearly differenced: 

`action.isScheduled()` returns true, if the action is activated in the mixer (by calling play()).

`action.isRunning()` returns true, only if several conditions are fulfilled in addition to this:

`this.enabled && ! this.paused && this.timeScale !== 0  && this._startTime === null  && this._mixer._isActiveAction( this );`

My question:

Having these two distinct functions, I wonder, whether `isRunning()` shouldn’t contain the additional condition `this.weight !== 0` ? 

Only in this way `isRunning()` would reliably indicate, whether an animation is really performed at that moment. Or isn’t that the intended behavior of `isRunning()`?

**Comment by takahirox** [comment]
The current behavior of `_isRunning()` isn't strange to me because
even if `weight` is zero, the time in `AnimationAction` doesn't stop.

**Comment by jostschmithals** [comment]
Thank you for your clarification!

So it seems that `isRunning()` has an other purpose than I assumed: It has not the task to indicate whether the animated mesh is really moving/changing, but whether the action’s time is continuing in the background. *)

With this in mind I will add a short concretization to my recent updates of the animation docs (https://rawgit.com/mrdoob/three.js/dev/docs/#Reference/Animation/AnimationAction.isRunning) to avoid such misconceptions, but perhaps I should wait for your bugfix of #10912 before making a PR.

*) BTW: Wouldn’t it be perhaps useful to have an additional method for checking “my” use case?

**Comment by takahirox** [comment]
Yeah, adding the information to the docs is a nice idea.
(Sorry I'll start to work on #10912 soon)

About a new method, It'd be helpful maybe?
