### ISSUE TITLE
Performance gains if using typed arrays?

### ISSUE THREAD

**Issue by loldrup** [mrdoob/three.js#10915]
After reading this article on JIT performance:

https://hacks.mozilla.org/2017/02/a-crash-course-in-just-in-time-jit-compilers/

I realise that Vector3 operations could probably be made faster, if it was built upon JavaScripts typed array data structures. The following proposal might not be feasible for a lot of good practical reasons, so I just want to ask if it could at all be a benefit, theoretically:

The Vector3 constructor don't return the constructed 'this' object: instead it creates a new typed floating point array of length 3, to which it adds the appropriate prototype-link and constructor property. All the current Vector3 are altered to access the array indexes 0, 1, 2, instead of the previous object properties x, y, z. End users can still uses these properties, which will be implemented as getter and setter functions on the prototype.

This should allow faster looping over data structures containing Vector3's.

Drawbacks
The 'this' object is created, and discarded, whenever a Vector3 is constructed.

I don't think the getters and setters for the properties x, y, z will introduce a performance loss, as these functions will be inlined by the JIT.

Any comments on this suggestion?

**Comment by mrdoob** [comment]
We tried this. TypeArrays were slow to initialise. We also tried to create one big shared TypeArray.

In fact, we're currently moving back to arrays for Matrix4: https://github.com/mrdoob/three.js/pull/10702

**Comment by mrdoob** [comment]
Also...

> I don't think the getters and setters for the properties x, y, z will introduce a performance loss, as these functions will be inlined by the JIT.

Getters and setters are SUPER slow.
