### ISSUE TITLE
SceneLoader.js Availability under three.js source

### ISSUE THREAD

**Issue by prateepgedupudi** [mrdoob/three.js#10910]
(*** This section is for bug reports and feature requests only. This is NOT a help site. Do not ask help questions here. If you need help, please use stackoverflow. ***)

##### Description of the problem 
We are trying to use `SceneLoader.js` in our example to load different types of objects with the help of example provided in `https://threejs.org/examples/?q=sce#webgl_loader_scene`. But I am only seeing `SceneLoader.js` under  `examples\js\loaders\deprecated` not in actual threejs source(`three.js-master\src\loaders`). But it is very useful feature to load different type of objects and do transformations on those. Can we expect this features in future releases with any new classes. 

##### Three.js version

- [ ] Dev
- [x ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
SceneLoader is now removed from the library see #11123. Please consider to use [ObjectLoader](https://threejs.org/docs/#Reference/Loaders/ObjectLoader).
