### ISSUE TITLE
Math - THREE.Plane() Rotation Transformations

### ISSUE THREAD

**Issue by GitRyanPerrin** [mrdoob/three.js#10923]
##### Description of the problem 
I believe it would be useful to have a rotation method added to the THREE.Plane constructor. It is a simple procedure, and because there is already a translate method, I believe it should be an easy fix.

I will work on this myself if I can manage.

Below is a fiddle that shows an animation using the THREE.Plane() method in an animation loop causing rotations using basic transformations.

http://jsfiddle.net/akmcv7Lh/105/ 

##### Three.js version
- r84

**Comment by mrdoob** [comment]
@WestLangley what do you think?

**Comment by WestLangley** [comment]
>it would be useful to have a rotation method added to the THREE.Plane constructor

Added to the constructor? How so?

We already have `Plane.applyMatrix4( matrix )`, and several `Matrix4.makeRotation*()` methods for constructing a rotation matrix.

**Comment by GitRyanPerrin** [comment]
Object3D also has an applyMatrix() method, while also having rotation, rotateX, setRotationFromMatrix, and so on.  It seems these were added out of a concern for intuitive use, or case-specific use. It isn't an addition that is necessary, but it fits a similar use as rotateOnAxis vs. rotateX.

**Comment by WestLangley** [comment]
`Object3D` has a position and a local coordinate system. `Object3D.rotateX()` rotates the object around the x-axis in its local coordinate system.

How do you recommend applying this concept to `Plane`?

Which methods, specifically, do you recommend adding, and what would they do?

**Comment by GitRyanPerrin** [comment]
Here is an updated fiddle of me attempting to apply the concept. Unfortunately, it only worked the way it did in my previous fiddle.

http://jsfiddle.net/akmcv7Lh/108/

I hope this will give you a better idea of what I think could be implemented. My issue in doing it myself was a lack of knowledge in JavaScript inheritance. I am a hobbyist, so this is a bit deeper into JavaScript than I have journeyed.

It seems to me that instead of doing plane.applyMatrix4( new THREE.Matrix4().makeRotationX( angle ) ), while easy, is much less intuitive. But applying this concept serves a similar purpose as object.rotateX( angle ) does for Object3D, where you could have used object.rotateOnAxis( new THREE.Vector3( 1, 0, 0 ) , angle );

The rotation of the plane would be in the world's coordinate system though, rather than the local.

**Comment by WestLangley** [comment]
>The rotation of the plane would be in the world's coordinate system though, rather than the local.

Yes, and I do not find that very intuitive.

I am trying to keep an open mind, but I do not see a compelling reason for adding methods to the library that rotate a plane around a world axis. I would consider such methods to be application-specific.

Also, we represent `THREE.Plane` in Hessian (Hesse) Normal Form, so the plane can be rotated by rotating the normal.

---

Tip: It is wise not to instantiate a new `Matrix4` (or `Vector3`) every frame unnecessarily. If you do not understand closures yet, at a minimum you can instantiate one `Matrix4` and reuse it. :)

**Comment by GitRyanPerrin** [comment]
That's fair, and thanks for the tip!
