### ISSUE TITLE
mapBumpScale in json not setting bumpScale

### ISSUE THREAD

**Issue by greenred123** [mrdoob/three.js#10926]
##### Description of the problem 

I have exported a mesh with bump map from blender to json format. The material in the json looks like this:

```
"materials":[{
        "DbgIndex":0,
        "depthTest":true,
        "mapBumpScale":[3.5,3.5],
        "mapBump":"octonormal.png",
        "colorEmissive":[0,0,0],
        "mapBumpRepeat":[1,1],
        "opacity":1,
        "transparent":false,
        "mapBumpWrap":["RepeatWrapping","RepeatWrapping"],
        "visible":true,
        "shading":"phong",
        "vertexColors":false,
        "blending":"NormalBlending",
        "colorSpecular":[0.017937,0.535,0.006281],
        "depthWrite":true,
        "colorDiffuse":[0.7744,0.011461,0.621607],
        "DbgName":"Material.002",
        "specularCoef":49,
        "wireframe":false,
        "mapBumpAnisotropy":1,
        "DbgColor":15658734
    }]
```

I am loading the json file as follows:

```
jsonLoader.load( meshDetails.files[0], function ( geometry, materials ) {
					if( typeof geometry !== "undefined"){
						if( typeof materials !== "undefined" ){
							var material = new THREE.MeshFaceMaterial( materials );
```

Although mapBumpScale is 3.5 in the json file, when I look at the bumpScale of the material in three js inspector, it is set to 0. 

##### Three.js version

- [ ] Dev
- [x ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] Linux
- [x ] Android
- [ x] IOS

**Comment by WestLangley** [comment]
This issue was fixed in #10530. Make sure you are using the blender exporter from r.84.
