### ISSUE TITLE
Docs: Visitors trapped on the subpages. – Server-side redirect possible? 

### ISSUE THREAD

**Issue by jostschmithals** [mrdoob/three.js#10937]
If a user finds his way to the three.js docs **from outside**, by searching for a certain subject in a search engine, he will be directed immediately to a subpage of the docs where all the internal links (to items on this subpage and to other subpages) don’t work, and where he doesn’t find a navigation bar, a search field or at least a link to the index page.

Example: Make a google search for “three.js skinned mesh”. The first hit will be https://threejs.org/docs/api/objects/SkinnedMesh.html, with all links broken (the same happens with all other search items).

This appears to be very strange for someone who is new to three.js, and who doesn’t know that the links on the subpages do only work using https://threejs.org/docs/  as an entry point.

I guess it should not be associated with much work (but very useful), to make a server-side redirect, mapping (for example) https://threejs.org/docs/api/objects/SkinnedMesh.html to https://threejs.org/docs/#Reference/Objects/SkinnedMesh , thus giving a visitor from outside always the possibility to navigate inside the three.js docs in the normal way?

**Comment by mrdoob** [comment]
@looeee any ideas?

**Comment by looeee** [comment]
Yeah this is an annoyance - the examples have the same problem, and I think it's even worse there as there's no "view source" button when [trapped on a subpage](https://threejs.org/examples/webgl_camera.html). 

On the other hand, perhaps we would want to preserve the functionality of being able to view examples fullscreen? 

I guess server side redirects are out though since I think the host is gh-pages? And anyway a JavaScript redirect would probably be simpler. I'll have a look into this if you think it would be a good idea.

**Comment by mrdoob** [comment]
Yeah, I don't think it's a problem in the case of the examples.

I suspect there is a javascript way to handle this...

**Comment by looeee** [comment]
> Yeah, I don't think it's a problem in the case of the examples.

Personally it hadn't bothered me at all in the case of the docs, whereas the lack of "View Source" when googling examples frequently annoyed when I was starting to learn three.

**Comment by jostschmithals** [comment]
I hadn’t yet thought about a **JavaScript** solution because I didn’t know that the server configuration is not accessible. But now I will do this too. 

@looeee Personally I felt never “trapped” on the example pages as much as on the docs subpages, because the link on top of the page is always working, taking you directly to the three.js main page. And I didn’t really miss the example’s “source code” button either, because examining the source code directly with Ctrl+U has the additional advantage of clickable links to the resources.

On the other hand: Not even being able to go to a parent class directly from a docs page (in spite of many clickable-looking links on such a page), must be very confusing for a visitor from outside. Therefore my personal interest would be to focus on finding a solution for the problem with the docs.

But perhaps we can solve both issues at the same time?

**Comment by looeee** [comment]
> Personally I felt never “trapped” on the example pages as much as on the docs subpages, because the link on top of the page is always working, taking you directly to the three.js main page.

Not all the examples have that link (although most do).

> And I didn’t really miss the example’s “source code” button either, because examining the source code directly with Ctrl+U has the additional advantage of clickable links to the resources.

If you happen to know the shortcut, that's great - but not everyone will, and quite a few examples you  can't right click to view source, such as https://threejs.org/examples/webgl_animation_cloth.html

> But perhaps we can solve both issues at the same time?

That would be great - or at least perhaps we can take the opportunity to add a "View Source" button to full page examples.

**Comment by jostschmithals** [comment]
I agree that improving both (docs and examples) would be the best.

To solve the docs issue it should be easy to check in page.js, `if (!frameElement)`, and make a redirect in this case, using list.js (which is accessible on all subpages) for mapping the urls (like it is done in index.html, but vice versa). 

I will do this tomorrow.

**Comment by jostschmithals** [comment]
As far as I can see the redirection of the docs works well.

Concerning the **examples** the situation is a little different:
 
The redirection would be as easy as inserting `#` to the url and removing `.html`, and by redirecting we get the “View Source” button (which was requested by @looeee) for free.

But it seems that currently the examples share no common script that could be used for this.

Programmatically inserting an additional `<script>` tag into each example would be quickly done, but then we would have 340 changed files in one PR. I don’t know, whether that would be a problem in any respect?
