### ISSUE TITLE
Build a texture from an already existing WebGL Texture

### ISSUE THREAD

**Issue by valentin-pinkau** [mrdoob/three.js#10945]
I would like to add a feature to create a threejs texture from an already uploaded texture.

My specific case is, that I have a fluid simulation in webgl and I would like to share the output texture resource with three, so that I can draw the result inside the scene. I would like to avoid rewriting the simulation code and I thought this use case could be generalised, like sharing a resource with three.

What is your opinion on this? Is there another approach I missed?

Thanks!

**Comment by piranha771** [comment]
Hey, I did it a similar project with a RenderTarget:

	readTextureData(rt: THREE.WebGLRenderTarget): Uint8Array {
		const buf = new Uint8Array(rt.width * rt.height * 4); // 4 Btyes per pixel (RGBA)
		this._renderer.readRenderTargetPixels(rt, 0, 0, rt.width, rt.height, buf);
		return buf;
	}

This obviously requires that you render your fluid simulation data in a THREE.RenderTarget.
The retrieved buffer can be used to make a new THREE.DataTexture.

Hope that helps.
