### ISSUE TITLE
pmrem map lighting does not interpolate with .hdr maps

### ISSUE THREAD

**Issue by thmasn** [mrdoob/three.js#10940]
##### Description of the problem 

when using pmrem maps generated from hdr images, the cubetexture is always interpolated as closestfilter
this results in steps in the shading

this is noteable when changing the material in the pmrem example to a non-metal:
![problem](https://cloud.githubusercontent.com/assets/20150151/23625660/45a0a390-02aa-11e7-9c53-4cdcb61a418f.JPG)

it gets even worse when using high frequency environment maps and slightly bent materials:
![prob2](https://cloud.githubusercontent.com/assets/20150151/23625701/5f6d74f6-02aa-11e7-91fd-deb0371c20ee.JPG)
(the surface should be smooth instead of having these blocks)

changing the texture filter like this does not help:
```
hdrCubeRenderTarget.texture.magFilter = THREE.LinearFilter;
hdrCubeRenderTarget.texture.minFilter = THREE.LinearFilter;
```

this only occurs with the **.hdr** cube map source, so i think this goes as bug

i was unable to locate the reason for this in the sourcecode, but my guess is it has to do with the texture format

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Astrak** [comment]
As a quick workaround a small improvement can be achieved by increasing the size of the generated map from 1024 to 4096 (I proposed the idea [here](https://github.com/mrdoob/three.js/issues/9827), no time to PR yet. Note it will increase the generation time). 

To increase the map from 1024 to 4096, the `resolution` parameter  in `PMREMGenerator.js` has to be changed from 256 to 512. Then with a `Ctrl`+`F` the only `1024.0` value can be found in three.(min.)js file, and has turn to `4096.0`.

**Comment by thmasn** [comment]
That solution makes the problem only smaller at the cost of performance.

My current solution is to use a rgmb map, as it provides a similar result. I was unable to find any documentation on how they work exactly though.
Also they do not decode correctly on edge, i guess that is a separate issue

**Comment by bhouston** [comment]
RGBE, the format used by HDR images do not interpolate correctly between adjacent pixels in its encoded form.  Thus you can not rely on a hardware based interpolator (e.g. linear interpolation texture setting) to interpolate RGBE.  RGBM mostly interpolates correctly in its encoded form -- not perfectly but well enough that usually you do not notice the issue.

If you are looking for perfect results with full gumat, decode to FP16 or FP32 and use that as the texture.  The decoded true HDR values will of course interpolate properly but this does require a few extensions to be present.

If you check out how I implemented encoding you can actually decode a source RGBE Texture and re-encode as RGBM RenderTarget.  This may get you the best of both worlds.
