### ISSUE TITLE
Ability to change layers recursively

### ISSUE THREAD

**Issue by mysteryDate** [mrdoob/three.js#10959]
I often find that I want to change the layer of an entire group of object3Ds. For example: to render that group with another camera for a post-processing effect. Does it make sense to extend the behavior of `Layers.set` to use a `recursive` flag like `Object3D.copy()` does? I'd be willing to write the pull request.

**Comment by mrdoob** [comment]
How about...

```js
mesh.traverse( function( child ) { child.layers.set( 2 ) } )
```

**Comment by mysteryDate** [comment]
Oh wow. That works perfectly. Thank you so much for your time.
