### ISSUE TITLE
Printing debug view of scene graph?

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#10961]
Is there any existing feature for printing the scene tree to the console, e.g. for debugging? I'm finding it a bit time-consuming to expand `node.children` recursively in the JS Console. If not, I wanted to propose something along the lines of:

```js
SceneUtils.log( node );
```

```
. <Scene>
├── <Object3D>
│   └── joint_1 <Bone>
│       └── joint_2 <Bone>
│           └── joint_3 <Bone>
├── fancy_character <SkinnedMesh>
├── <PointLight>
├── <AmbientLight>
└── bookshelf <Mesh>
```

**Comment by takahirox** [comment]
How about this one?

    scene.traverse(function(obj) {
      var s = '';
      var obj2 = obj;
      while(obj2 !== scene) {
        s += '-';
        obj2 = obj2.parent;
      }
      if (s !== '') s += ' ';
      console.log(s + obj.type + ' ' + obj.name);
    });

If `Object3D` had `depth` property, the code would be much simpler...

**Comment by WestLangley** [comment]
A slight mod...
```javascript
scene.traverse( function ( obj ) {

	var s = '|___';

	var obj2 = obj;

	while ( obj2 !== scene ) {

		s = '\t' + s;

		obj2 = obj2.parent;

	}

	console.log( s + obj.name + ' <' + obj.type + '>' );

} );
```

**Comment by donmccurdy** [comment]
Thanks, either of these works great. 🙂

Does this seem appropriate for e.g. SceneUtils, or should I just bookmark the snippet?

**Comment by takahirox** [comment]
As for me, bookmaking is good enough (just my opinion).

**Comment by mrdoob** [comment]
I think it's pretty handy!
How about adding it to `Object3D` so we could do... `scene.log()` or `mesh.log()`...?

**Comment by takahirox** [comment]
Not bad.

What information should we display?
- type
- name

Anything else?

**Comment by jostschmithals** [comment]
I would like to suggest `console.group()` for outputting the scene graph. 
Here for the moment a very basic demo:

```
(function printGraph( obj ) {
    
    console.group( ' <' + obj.type + '> ' + obj.name );
 
    obj.children.forEach( child => printGraph( child ) );
    
    console.groupEnd();

} ( scene ) );  
```

If you open the dev tools in Chrome, you get the fully expanded tree, but you have also the possibility to collapse it partly to fit your needs.

Chrome, expanded:

![scenegraph_chrome](https://cloud.githubusercontent.com/assets/5700294/23752959/d81202b2-04d7-11e7-8908-5df5344514b8.PNG)



Chrome, partly collapsed:

![scenegraph_chrome_collapsed](https://cloud.githubusercontent.com/assets/5700294/23752964/ddad042e-04d7-11e7-9991-29a57dc3760e.PNG)


A little downside: Firefox currently supports no collapsing, but I’ve tested it with FF Nightly, and in Nightly it works the same as in Chrome.

Current FF (52):

![scenegraph_firefox_52](https://cloud.githubusercontent.com/assets/5700294/23752987/f3cedec6-04d7-11e7-96f0-6eb625712f81.PNG)


FF Nigthly:

![scenegraph_firefox_nightly](https://cloud.githubusercontent.com/assets/5700294/23752998/003b9262-04d8-11e7-92d0-dd187ef39f97.PNG)

**Comment by donmccurdy** [comment]
@jostschmithals that's a nice trick! along similar lines, if I add the `%o` placeholder, the console will print the entire tree expanded, while showing each individual node collapsed. You can expand e.g. `Mesh` to see its properties.

```js
(function printGraph( obj ) {
    
    console.group( ' <%o> ' + obj.name, obj );
 
    obj.children.forEach( child => printGraph( child ) );
    
    console.groupEnd();

} ( scene ) );
```

<img width="821" alt="screen shot 2017-03-09 at 10 45 35 am" src="https://cloud.githubusercontent.com/assets/1848368/23757774/bd36be8c-04b5-11e7-8ae1-7e144a977c08.png">

**Comment by jostschmithals** [comment]
I just wanted to suggest this further enhancement too, but I think then it would be more eye-friendly to choose the order from your first post (to avoid nesting):

```
(function printGraph( obj ) {
    
    console.group(obj.name + ' <%o> ', obj);
 
    obj.children.forEach( child => printGraph( child ) );
    
    console.groupEnd();

}(scene));
```

**Comment by jostschmithals** [comment]
... but unfortunately it seems, that FF doesn't understand the %o-thing in the same manner :-(

**Comment by WestLangley** [comment]
The script I posted above appears to handle scenes with many children a bit better as it counts -- rather than repeats -- duplicate lines. Try [this](http://threejs.org/examples/webgl_loader_json_blender.html) three.js example, which has 700+ child meshes.

    |___ <Scene>
        |___ <Group>
            |___Bip01_Pelvis <Object3D>
            ...
            ...
        |___ <AmbientLight>
        |___ <PointLight>
    725     |___ <Mesh>
... although it offsets the duplicates a bit.

**Comment by jostschmithals** [comment]
Indeed – this is not only „a bit”, but much more convenient in such a scenario (which I had not in mind)!

Would it perhaps make sense to have the possibility of switching between both types of implementation (combined in one method)? - I guess that the imaginable use cases can be very divergent, so that both implementations could be useful in different places.

**Comment by makc** [comment]
too bad I can't "favorite" issues on github

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/pull/10995#issuecomment-288256554

**Comment by donmccurdy** [comment]
For others interested, the [three.js inspector](https://chrome.google.com/webstore/detail/threejs-inspector/dnhjfclbfhcbcdfpjaeacomhbdfjbebi?hl=en) Chrome extension also shows a nice interactive scene graph.

**Comment by brainexcerpts** [comment]
Chrome extension seems to be dead but the [Three.js Developer Tools](https://addons.mozilla.org/en-US/firefox/addon/three-js-developer-tools/) for Firefox is awesome and does far more than just displaying an interactive view of the scene tree (this extension adds a tab in Firefox dev tools (F12))
