### ISSUE TITLE
Software Requirement Specifications document

### ISSUE THREAD

**Issue by NicolasRannou** [mrdoob/three.js#10966]
Hi there!

We are in the process of submitting a THREEJS-based application for FDA/CE certification. The certification allows doctor/surgeon to use the application in their daily clinical workflow.

A useful piece of documentation for the FDA approval is to provide Software Requirement Specifications (SRS) of the tools/libraries we use to to build the application.

Do you have such document for THREEJS, that details the expected behavior, API, release process, bug fixing process, etc.

If so, is it possible to access it?

Keep up the great job!
Thanks!

**Comment by mrdoob** [comment]
We don't. Feel free to write a draft of the specs here and we can ammend.

**Comment by NicolasRannou** [comment]
OK will let you know and make a draft and re-open if it is actually needed!
