### ISSUE TITLE
CSSRenderer is not correct in IE11

### ISSUE THREAD

**Issue by 34997593** [mrdoob/three.js#10965]
when the Z point of the CSS3DObject is not 0, the effect is not correct in IE11. the future version can be compatible with IE11?

https://threejs.org/examples/#css3d_sandbox
![ie11](https://cloud.githubusercontent.com/assets/7519262/23779557/204f02d8-057c-11e7-8db8-1f9ac5c20dee.jpg)
IE11
![chrome](https://cloud.githubusercontent.com/assets/7519262/23779564/2b401740-057c-11e7-91ff-a7af3eb555b6.jpg)
Chrome

##### Three.js version
- r84

##### Browser
- IE11

**Comment by mrdoob** [comment]
Do you mind sharing a screenshot?

**Comment by yomotsu** [comment]
@34997593
 I guess, the probrem is because of that IE does not support `transform-style: preserve-3d`. only `flat` is available.
https://msdn.microsoft.com/en-us/library/hh772282(v=vs.85).aspx

**Comment by 34997593** [comment]
@mrdoob I have added  screenshots with IE11 and Chrome .

**Comment by yomotsu** [comment]
Good news! I'm working on it, and it kinda works now.

![1](https://cloud.githubusercontent.com/assets/212837/23823579/b119b510-06a8-11e7-9fff-6ac0d0287e30.gif)
