### ISSUE TITLE
Samsung Android images are blurry with webgl THREE

### ISSUE THREAD

**Issue by invincible09** [mrdoob/three.js#10963]
Hey guys,

I am getting the following errors on Samsung S5 using chrome browser v55

![a6e08132-040a-11e7-8a44-c8f824e1d6fc](https://cloud.githubusercontent.com/assets/25088226/23731665/e7e8b9a6-043c-11e7-8f2c-47f7c5097042.png)

The output images is very blurry, any help is greatly appreciated.

Thanks!

**Comment by mrdoob** [comment]
Those are not errors, those are warnings.

**Comment by invincible09** [comment]
right.. but those warnings have anything to do with the blurry image on that specific device where those extensions aren't supported?

**Comment by mrdoob** [comment]
No idea, it could help if you shared a screenshot of the blurry image.

**Comment by mrdoob** [comment]
Also a link to the a test you're talking about.

**Comment by invincible09** [comment]
![3af7325e-0405-11e7-9336-1fb7982c41e9](https://cloud.githubusercontent.com/assets/25088226/23769486/895baeec-04dd-11e7-8be2-a27331518365.jpg)


link to the 360 image

**Comment by mrdoob** [comment]
Can you share a screenshot of this page too? http://webglreport.com/

**Comment by invincible09** [comment]
![2017-03-09-16-01-03_720](https://cloud.githubusercontent.com/assets/25088226/23770902/fd9008e4-04e2-11e7-8d95-96ef8dc0ed9d.png)
![2017-03-09-16-01-06_720](https://cloud.githubusercontent.com/assets/25088226/23770910/045b25a0-04e3-11e7-9505-e73ae0d7ea11.png)

**Comment by mrdoob** [comment]
Thanks for that! Unfortunately I don't have a Samsung S5 and I can't reproduce on a Pixel...

![screenshot_20170309-152703](https://cloud.githubusercontent.com/assets/97088/23775334/11dce296-04dd-11e7-9bd5-056e80f25e22.png)

**Comment by mrdoob** [comment]
Can't reproduce on a Nexus 5 either.

![screenshot_20170310-003817](https://cloud.githubusercontent.com/assets/97088/23775683/21aaecde-052a-11e7-9dd1-2afce9e73c42.png)
