### ISSUE TITLE
bad color decoding of rgbm maps on Edge 38.14393.0.0

### ISSUE THREAD

**Issue by thmasn** [mrdoob/three.js#10977]
##### Description of the problem 

on Microsoft edge, RGBM maps are not decoded correctly
![banding](https://cloud.githubusercontent.com/assets/20150151/23788966/29fea174-0579-11e7-9868-34b2c3eb4d96.JPG)

with 1 error:
![error](https://cloud.githubusercontent.com/assets/20150151/23789017/5b3b7316-0579-11e7-9ce6-84523796b9cb.JPG)

what it should look like:
![should](https://cloud.githubusercontent.com/assets/20150151/23789006/528b04e8-0579-11e7-9ff8-9f7cc312219b.JPG)

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [ ] All of them
- [x] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by bhouston** [comment]
It is a bug in Edge and IE11.  PNGs can not be used in this case unfortunately because the alpha value leads to quantization of the RGB values.
