### ISSUE TITLE
cannot export circle from blender using three.js json exporter

### ISSUE THREAD

**Issue by vt5491** [mrdoob/three.js#10975]
##### Description of the problem 

1) Create a circle in blender.
2) export using 'three.js'.  Doesn't matter if scene selected or not.
3) get error message:

```
[](Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\__init__.py", line 814, in execute
    exporter.export_geometry(filepath, settings)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\exporter\__init__.py", line 20, in inner
    func(filepath, options, *args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\exporter\__init__.py", line 85, in export_geometry
    geo.parse()
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\exporter\geometry.py", line 168, in parse
    self._parse_buffer_geometry()
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\exporter\geometry.py", line 390, in _parse_buffer_geometry
    array = func(self.node) or []
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\exporter\geometry.py", line 376, in <lambda>
    lambda m: api.mesh.buffer_position(m, self.options), 3)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\exporter\api\mesh.py", line 61, in inner
    mesh = data.meshes[name]
TypeError: bpy_prop_collection[key]: invalid key, must be a string or an int, not NoneT
```

##### Three.js version

- [x ] Dev
- [ ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ x] Windows (only tested on windows)
- [ ] Linux
- [ ] Android
- [ ] IOS

Blender 2.78b

**Comment by vt5491** [comment]
Note: this only seems to happen when the circle has no face.  I don't get it if I add a face to the circle.  I'm pretty new to blender, so I guess I probably want a face on my circles.  But still, if you ever create a circle, or a simple polygon and you don't create a face, you will get this error.

**Comment by vt5491** [comment]
There's a legitimate problem here.  Just because I found a circumvention, doesn't mean the original problem doesn't exist.  If you create a circle, and for whatever reason don't create a face the export will fail.  None of the other exporters have this problem.  That doesn't really seem like a stackoverflow question to me.

I didn't have to open this ticket.  I was trying to aid in making three.js even better.  I find that the three json exporter is pretty flaky, and I seem to have to go to the .obj format a lot and no wonder with the way you blow off people reporting problems.  

Don't get me wrong, I really appreciate what you're doing and I realize you're busy, but I would have more respect for you if you were just honest and closed the ticket "not important enough to fix or investigate".  I guess you're just not concerned about certain edge cases that cause the exporter to crash.

**Comment by mrdoob** [comment]
Maybe you can share the .blend?

**Comment by vt5491** [comment]
attached. Blender 2.78b.  Using the lastest io_three from three js under utils/examples/blender/addons/io_three

[circle_no_face.zip](https://github.com/mrdoob/three.js/files/835562/circle_no_face.zip)

**Comment by vt5491** [comment]
ColladaLoader to the rescue.  Works perfect.  It looks to me like the blender three js json exporter is basically dead? (hasn't been updated in three years).  It looks like it's not even part of the official THREE.js repo.  Sorry, I thought it was the main method for exporting to three.js and it was part of three.js.   It might work for a basic object like a cube, but is useless on anything semi-complex.  STL wasn't bad, but it only has geometry -- no materials.  Obj doesn't handle circles right, for some reason.

Thank you mrdoob.

**Comment by mrdoob** [comment]
Are you talking about this exporter?
https://github.com/mrdoob/three.js/tree/dev/utils/exporters/blender

**Comment by vt5491** [comment]
Yes.  However, I originally googled on "blender three js exporter github" and found https://github.com/satori99/threejs-blender-export, which I now realize is something else.   But it seems collada is the [preferred loader method](http://stackoverflow.com/questions/9783458/blender-export-to-three-js) at least as of four years ago.  However, it's hard to find any recent recommendations about what  loader is best for blender.  I had to empirically re-discover that collada seems to be the best.

But yes, the link you reference is the one I was using, and I can see that it is somewhat more maintained than I thought.
