### ISSUE TITLE
Wireframe and back faces

### ISSUE THREAD

**Issue by dalboris** [mrdoob/three.js#10983]
I desire to visualize a mesh + its wireframe. The mesh is open and therefore some back faces are visible.

Using a solid color for the wireframe gives uneven contrast between the shaded triangles and the unshaded edges:

http://jsfiddle.net/4nf8y3z1/1/

Using `lights: true` on the LineBasicMaterial seems not to work:

http://jsfiddle.net/4nf8y3z1/2/

    Uncaught TypeError: Cannot set property 'value' of undefined
    three.js:22031 Uncaught TypeError: Cannot set property 'needsUpdate' of undefined
    three.js:22031 Uncaught TypeError: Cannot set property 'needsUpdate' of undefined

As a workaround, I'm using a MeshPhongMaterial and a Mesh for the wireframe too, using the same geometry, and passing `wireframe: true`. This works great for the front-faces, but not for the back faces:

http://jsfiddle.net/4nf8y3z1/3/

Therefore, I played a bit with the GLSL shaders to change the illumination models such that instead of saturating dotNL, it takes the absolute value, so that back faces are shaded exactly as if they were front-facing:

http://jsfiddle.net/4nf8y3z1/4/

(this last jsfiddle is the same as the previous, except that it includes [three_fix.js](http://dalboris.com/threejs_wireframe_fix/three_fix.js) instead of three.min.js)

I just wanted to share this with you, and let you decide whether you want to integrate these changes, possibly with more thought (is changing saturate -> abs always ok, or could it break other thing? is the additional cost of the abs() ok? maybe this should be a parameter of the material? etc.).

For now, I just directly modified the build file three.js to get what I wanted, I don't have much more time for further investigation. :)

Great library by the way, I've started using it two days ago and I love it!

**Comment by mrdoob** [comment]
Wouldn't that be the same result as duplicating the light and placing it in the other side?  😶

**Comment by dalboris** [comment]
No, because the shading model still gives a non-zero illumination for back faces. Your suggestion gives the following result:

http://jsfiddle.net/4nf8y3z1/5/

**Comment by mrdoob** [comment]
I see... We used to have this wrap effect thing years ago. We ended up removing it because it was a bit of a hack.

**Comment by dalboris** [comment]
I see. Though, it's not necessarily a hack, it depends how do you interpret your geometry and how do you want to display it. For instance, if your mesh represents a "thin surface", like a piece of cloth or paper, then the orientation of the normal is actually irrelevant: there's no "inside" or "outside". Ideally, the way you render such geometry is by not culling any faces, and making sure that your illumination model is invariant by flipping the normal.

If your mesh represents a solid object, then back-facing triangles will always be obscured, thus you can cull them, and your illumination model doesn't have to be invariant by normal flip (i.e., it can safely ignore the possibility of having dotNL < 0)

By glancing over Three.js quickly, it seems that the current implementation for side = DoubleSide renders the mesh twice: once by culling the back faces, and the second time by culling the front-faces then flipping the normal. You can see how this is equivalent to not culling anything in the first place, and making sure that the shading model is invariant by normal flip. The issue is that Three.js seems to only do the "normal flip" when wireframe = false, reason for the discrepency between the triangle shading and the wireframe shading. Of course, correct me if I'm wrong. :)

**Comment by dalboris** [comment]
(actually, it seems that when "wireframe = true", then "side" is ignored, while it is common in CAD software to display a wireframe, but only the wireframe of front-facing triangles, which the following fails to do: http://jsfiddle.net/4nf8y3z1/6/)

**Comment by WestLangley** [comment]
>I see. Though, it's not necessarily a hack, it depends how do you interpret your geometry and how do you want to display it

It appears you are misunderstanding what @mrdoob is referring to. He is referring to _wrapped diffuse lighting_, which was removed as an option.

>By glancing over Three.js quickly, it seems that the current implementation for side = DoubleSide renders the mesh twice. ... Of course, correct me if I'm wrong.

three.js renders double-sided meshes by disabling culling and flipping normals on back faces. It renders the mesh once.

**Comment by dalboris** [comment]
Hum, with desktop OpenGL, you can use glPolygonMode(GL_FRONT, GL_LINE), then draw the mesh with glBegin(GL_TRIANGLES), which would draw the wireframe for the front-facing triangles.

But apparently, that's not available in OpenGL ES, thus not in WebGL (I'm less familiar with those). Now I actually understand why in three.js, you actually compute the edges of the mesh yourself and draw with gl.Lines. Then, I suppose you can do the culling yourself in the vertex shader.

Anyway, that was only related to the other problem, I actually don't require it (now). 

@WestLangley Thx for this info. That sounds reasonable :-) Then I think a simple fix to my initial problem would be do the same when wireframe=true: render once all edges, but flip all back-facing normals.
