### ISSUE TITLE
Transparent background is how to do？

### ISSUE THREAD

**Issue by zhubenjie** [mrdoob/three.js#10996]
render alpha or Transparent？
Seems to be no effect。。。

**Comment by WestLangley** [comment]
See [stackoverflow](http://stackoverflow.com/a/20496296/1461008).

**Comment by ddcouples** [comment]
`_renderer = new THREE.WebGLRenderer( { alpha: true } );
_renderer.setClearColor( 0x000000, 0 )`
it doesn't work,the background is alse balk!
