### ISSUE TITLE
running closure produced three.min.js through uglify saves additional 1744 bytes uncompressed, 2860 gzipped

### ISSUE THREAD

**Issue by kzc** [mrdoob/three.js#11003]
##### Description of the problem 

Size of `three.min.js` can be further reduced by running uglify on the closure emitted minified JS:

```
$ wc -c build/three.min.js
  503713 build/three.min.js

$ cat build/three.min.js | gzip | wc -c
  127852

$ node_modules/.bin/uglifyjs -V
uglify-js 2.8.12

$ node_modules/.bin/uglifyjs build/three.min.js -m -c warnings=false | wc -c
  501969

$ node_modules/.bin/uglifyjs build/three.min.js -m -c warnings=false | gzip | wc -c
  124992
```

**uncompressed savings:** 1744 bytes

**gzip savings:** 2860 bytes

Unit tests results are unchanged with additional uglify of `build/three.min.js`.

Perhaps I am missing something obvious.

##### Three.js version

- [x] Dev
- [ ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Have you also done performance tests?

**Comment by kzc** [comment]
Nope. I've never used this repo before.

**Comment by mrdoob** [comment]
Closure and Uglify not only minify but also improve the performance on some code. You may want to include performance changes in your analysis.

**Comment by kzc** [comment]
I'm not a user of this project and will not perform any further analysis. I was just looking for test data for uglify and thought you may find this information useful.
