### ISSUE TITLE
Quaternion onChange no longer works

### ISSUE THREAD

**Issue by jacklehamster** [mrdoob/three.js#11005]
##### Description of the problem 
Since the last version (85dev), quaternion.onChange no longer exists. It worked in 84.
Tested on Firefox, Chrome, MacOS

var q = new THREE.Quaternion()
alert(q.onChange); // undefined

##### Three.js version

- [x] Dev
- [ ] r84
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by jacklehamster** [comment]
Doc reference: https://threejs.org/docs/index.html#Reference/Math/Quaternion

**Comment by WestLangley** [comment]
It is an experiment: See comments in https://github.com/mrdoob/three.js/commit/eeae90e16fec92f78077fa424c73e86bfc135733.

**Comment by mrdoob** [comment]
What's your use case @jacklehamster?

**Comment by jacklehamster** [comment]
I have a few variables stored and deriving from the camera quaternion.
- quaternion array
- forward vector based on camera direction.

I don't calculate those all the time, so I just set a 'dirty' variable when the quaternion changes, then when I fetch any of those variables, I either use the cache or recalculate if it's dirty.

Now I still have a workaround, which is saving the last version of the quaternion, then instead of checking dirty, I check each x,y,z,w instead of the dirty flag. Don't think is much slower..

**Comment by mrdoob** [comment]
> Now I still have a workaround, which is saving the last version of the quaternion, then instead of checking dirty, I check each x,y,z,w instead of the dirty flag. Don't think is much slower..

👍

**Comment by sasha240100** [comment]
@jacklehamster @mrdoob I think `onChange` is quite useful. And I'd like to see it's implementation in vector3 too if possible.

Personally I need it to **handle position/rotation** updates in physics from client side.

@jacklehamster Can you share your workaround?

**Comment by mrdoob** [comment]
Oh man... if only `Object.observe()` or `Object.watch()` had gone somewhere...

**Comment by mrdoob** [comment]
I guess I'll revert for now.

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/1cdf246f9e4bcbce09d6bb05f803e31b59d015fa

**Comment by jacklehamster** [comment]
Well, in case you still need the workaround @sasha240100, or for anyone interested, here it is.
`   
     var lastQuat = new THREE.Quaternion() 
     function getCameraQuaternionData() {
        if(!camera.quaternion.equals(lastQuat)) {
            // QUATERNION HAS CHANGED, SO RECALCULATE ALL THE STUFF AND CACHE IT
            lastQuat.copy(camera.quaternion);
            return NEW STUFF;
        } else {
           return CACHED STUFF;
        }
    }
`
If you want this code to be reactive, I guess you can call it in a loop and put a callback function in the if statement.
