### ISSUE TITLE
addEventListener IE11 bug

### ISSUE THREAD

**Issue by RoeePeleg** [mrdoob/three.js#11012]
##### Description of the problem 

Im working with three.js on IE11 and have a problem with the addEventListener func:
the code inside the function is never being executed:

```
 	var fileInput = document.createElement( 'input' ); 
 	fileInput.type = 'file'; 
 	fileInput.addEventListener( 'change', function ( event ) { 
 		editor.loader.loadFile( fileInput.files[ 0 ] );
        } ); 
```

the browser familiar with the addEventListener func, bet somehow the inside function is not being called when i 'click' fileInput button: 

```
var importOption = new UI.Panel();
importOption.setClass('option');
importOption.setTextContent('Import');
importOption.onClick(function () {

    fileInput.click();

} );
options.add(importOption);
```
Any ideas of how can i trigger the 'change' function? I want it to be triggered by user button press, like it is written in the code.

This code was taken from the three.js source files, and works just fine on chrome.

##### Three.js version 
r73

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by yomotsu** [comment]
I thinks that is a browser problem. also you can use [stackoverflow](http://stackoverflow.com/questions/tagged/three.js) for this kind of question.

**Comment by jostschmithals** [comment]
This is not related to threejs and seems to be a completely correct behaviour:  

The change event - unlike the click event - doesn’t fire when the fileInput button is clicked, but when the file selection has actually been changed by the user. So I agree to @yomotsu‘s reference to stackoverflow for further help.

**Comment by RoeePeleg** [comment]
@jostschmithals  this code was taken from three.js source file and works just fine on chrome, so how could it be completely correct behaviour?

**Comment by jostschmithals** [comment]
Sorry, then I misinterpreted your very short code snippet (listening to **change** events, but trigger a **click** event shouldn't work in any browser).

BTW - did you try it with the current version of three.js (r84) too? - Since your version (r73) lots of things have changed.

**Comment by RoeePeleg** [comment]
Yes I have, no luck.
BTW i have edited the code snippet

**Comment by mrdoob** [comment]
> @jostschmithals this code was taken from three.js source file and works just fine on chrome, so how could it be completely correct behaviour?

No, this code was taken from https://github.com/mrdoob/ui.js which is a library used by the three.js editor.
