### ISSUE TITLE
lightHelper bug

### ISSUE THREAD

**Issue by f2egxz** [mrdoob/three.js#11017]
##### lightHelper bug

if set light.target ,but the lightHelper  didn't change.

```javascript
    var spotLight = new THREE.SpotLight( 0xffffff , 1 ,200,0.2 );
    spotLight.position.set( 30, 50, 10 );
    spotLight.castShadow = true;
    spotLight.target= cube;
    scene.add( spotLight );
    var spotLightHelper = new THREE.SpotLightHelper( spotLight );
    scene.add( spotLightHelper );
```

##### Three.js version

- [x] Dev
- [ ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by jostschmithals** [comment]
Did you call `spotLightHelper.update();` in the render loop?

**Comment by f2egxz** [comment]
No, that's why，thanks

**Comment by NicolasRannou** [comment]
Please close issue if solved :) @f2egxz
