### ISSUE TITLE
Many examples not loading

### ISSUE THREAD

**Issue by Bromides** [mrdoob/three.js#11011]
First of all, I am running the latest version of Chrome on macOS Sierra  on a mid 2011 21.5 inch iMac. WebGL works, the enabling flags problem is specifically not the issue, and yet the problem persists.

When loading examples such as [https://threejs.org/examples/#webgl_geometry_teapot](teapot)
or [https://threejs.org/examples/#webgl_geometry_convex](convex) or [https://threejs.org/examples/#webgl_materials_cubemap_dynamic2](cube), It just shows a white screen with nothing on it, even after waiting 5 minutes. Going into the web inspector reveals no errors, and as such, I cannot find what's wrong. The most interesting is the teapot, which looks like this 
![screenshot](https://cloud.githubusercontent.com/assets/17725324/23976553/d1fe7a54-09be-11e7-9bb8-9bfa17fa865e.png)

If anyone knows some other way to fix it beside what all I've found, please tell me, thanks

**Comment by WestLangley** [comment]
See the discussion in https://github.com/mrdoob/three.js/issues/9685.
