### ISSUE TITLE
panorama video doenst work on Mac Safari 10.0

### ISSUE THREAD

**Issue by slash851** [mrdoob/three.js#11014]
##### Description of the problem 

Demo of panorama video doesnt work on Mac Sarfari 10.0 and any other version
https://threejs.org/examples/?q=video#webgl_video_panorama_equirectangular

The weird version is that panorama-video from videojs that is using Three.js but older version is working on that browser
https://yanwsh.github.io/videojs-panorama/

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

**Comment by Mugen87** [comment]
I think the problem is that the video of the example uses the `WebM` format which is not supported by Safari, see http://caniuse.com/#feat=webm

The video format of the other website is MPEG-4 (http://caniuse.com/#feat=mpeg4).
