### ISSUE TITLE
CORS exceptions in several three.js examples/loader libraries

### ISSUE THREAD

**Issue by rkwright** [mrdoob/three.js#11020]
##### Description of the problem 

I have been slowly (spare time activity) implementing the old NeHe demos using three.js. You can see my progress [here](http://geofx.com/graphics/nehe-three-js/nehe-three-js.html).  I have now completed the first 31.  Number 31 is 3D models so I decided to use the 3D model-loading capabilities in three.js.  I leveraged the tutorial at [scripts tutorials](https://www.script-tutorials.com/webgl-with-three-js-lesson-7/).  However, most of their content was out-of-date and wouldn't work with r84.   Worse,  several of the models in r84 wouldn't work at all because the loaders had problems with CORS.

I also posted a question on StackOverflow [here](https://stackoverflow.com/questions/42840553/cors-fix-for-babylonloader-js-in-three-js)

#### Describe the bug or feature request in detail.  

I created a new set of demos. which you can see [here](http://geofx.com/graphics/nehe-three-js/lessons25-32/lesson31/lesson31webgl.html).  The 8 demos now work with r84-master , but I had to patch 4 of the loader libraries:

- BabylonLoader
- PDBLoader
- VRMLLoader
- VTKLoader

In each case, I had to make the same change, adding a handler for CrossOrigin:

    load: function ( url, onLoad, onProgress, onError ) {

        var scope = this;

        var loader = new THREE.FileLoader( scope.manager );

        // specify a CORS handler so the rest of the code doesn't have a cow
        loader.crossOrigin = '';

        loader.load( url, function ( text ) {

            onLoad( scope.parse( JSON.parse( text ) ) );

        }, onProgress, onError );

    },

if you would like me to push a pull-request with the changes (to r85dev, I  presume), let me know.

##### Three.js version

- [ ] Dev
- [ x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
N/A

**Comment by mrdoob** [comment]
Aww... NeHe... I started learning OpenGL with these...

**Comment by mrdoob** [comment]
Would you like to do a PR with the fixes?

**Comment by rkwright** [comment]
Will do.  Busy tonight (wife...) but will post the PR tomorrow.

**Comment by rkwright** [comment]
Well, I'm mildly embarrassed. We had a power outage for a few minutes last night so all my systems got rebooted.  And this morning I cannot reproduce the problem either on master or dev.  So it looks like it may have been some bug in WebStorm (which I use for development) and my "fix" was just working around some quirk in WS.  Just as well I retested as there is no point fixing non-bugs, eh? Sorry for any confusion.  Let me know if I am wrong.

I do have one question, though.  In updating, I got the latest PDBLoader, which now uses BufferGeometry instead of Geometry.  Not sure why this was done.  As you point out in the documentation of BufferGeometry, it makes it hard to access parts of the geometry, etc. which is EXACTLY what rendering a molecule is.  The code to read the (Buffer) Geometry and GeometryBonds is now 10 times as long. Its like the new PDBLoader reads the simple (PDB) text file, then builds these complex BufferGeometry Attributes (instead of constructing the Geometries), then the code which gets the (Buffer) Geometry and GeometryBonds has to go through this fairly complex dance to build the Geometries itself.  Doesn't make sense to me, but perhaps as a noob I am missing something.

**Comment by AUTOMAKHAN** [comment]
@rkwright you're not crazy. I had to patch Loader.prototype in the same way inside of createMaterial::loadTexture by setting the crossOrigin to empty string.

**Comment by rkwright** [comment]
@AUTOMAKHAN Hm. Thanks.  But I'm still confused.  Why did I see the failures one day, but not the other?  Why did some of the loaders throw exceptions but not others?  I get it that the loaders are not all the same, but still...

BTW, the actual demo is [here](http://geofx.com/graphics/nehe-three-js/lessons25-32/lesson31/lesson31webgl.html), which works fine without any CORS corrections...

**Comment by jostschmithals** [comment]
@rkwright Aren’t you loading all of your models from the same domain? I don’t yet understand, why there should be a cross origin problem in your linked demo. Or am I missing something?

**Comment by AUTOMAKHAN** [comment]
Are you using webstorm as a local dev server to host the assets? Or are you testing locally and pulling the assets from a remote URL? In the latter case, I believe your patch is necessary. 

This might also be related to browser caching.

**Comment by rkwright** [comment]
Ah, good point.  All the assets and the code are on Geo-F/X.  I tried to point to the caf2.pdb at mrdoob's github site, but then I get 

    XMLHttpRequest cannot load https://github.com/mrdoob/three.js/blob/master/examples/models/molecules/caf2.pdb. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:63342' is therefore not allowed access.

which seems reasonable, I guess, as github is not configured for CORS.  I don't have another server I can stage it on easily so I am kind of stumped as to how to test this.  Suggestions?

**Comment by rkwright** [comment]
I have not been able to reproduce this again.  I don't have an easy way to try to trigger a CORS exception.  Unless someone has a better suggestion, I would recommend closing this, at least for now.  If I or someone else can reproduce the problem it can be revisited then.
