### ISSUE TITLE
Morph targets not on GPU in ShaderMaterial

### ISSUE THREAD

**Issue by vrav** [mrdoob/three.js#11028]
##### Description of the problem 

Hey, sorry if seems like a help request. From my perspective it seems like a bug, or perhaps something lacking in the documentation?

What I'm trying to do is import a mesh and use a custom vertex shader to animate various morph targets. I'm not using a MorphBlendMesh because I'm not animating sequences, just morphing between static poses. 

I have a JSON mesh parsed with JSONLoader, with three morph targets. I load this into a Mesh, and everything appears fine in the data structure (named morphTargets entries, etc). When I create the material, I set morphTargets to true, and indeed I can use morphTarget0-7 in the vertex shader. Sadly, these attributes seem empty as the mesh disappears into nothing (so I assume the values are zero). I've looked at the JSON and the morph poses are there with altered vertices.

I know my laptop supports morph targets because this workflow works in an old demo I made with a very old version of three.js.

If my mesh object's geometry contains morph targets, and my material has morph targets enabled, shouldn't I be able to set gl_Position to morphTarget1 in my vertex shader and see that pose?

##### Three.js version

- [x] dev

##### Browser

- [x] Chrome

##### OS

- [x] ChromeOS

**Comment by Mugen87** [comment]
Can you please provide a [fiddle](http://jsfiddle.net/hfj7gm6t/) with your scene? Share at least your JSON file and the code where you create your material and mesh. This will help us to understand the  actual problem.

**Comment by makc** [comment]
maybe just look into shader editor to see how it works
![screen shot 2017-03-30 at 18 48 36](https://cloud.githubusercontent.com/assets/242577/24516027/9e85ce0e-1579-11e7-98e4-89a4e822a122.png)


and try again?

**Comment by vrav** [comment]
I updated three.js and the blender exporter and tried again. I'm not sure what was wrong -- the files look the same. Replicating the pattern you quoted in my custom shader, it now works -- and in fact simply setting position to morphTarget0 now works, whereas it didn't before. Sorry I don't know what caused this bug, but it appears to now be fixed. Perhaps simply an error on my part.
