### ISSUE TITLE
Blender Three.js json exporter; slight context.scene and edge modifier issue

### ISSUE THREAD

**Issue by soelen** [mrdoob/three.js#11029]
First off I would like to say the people which worked on this exporter did an amazing job; compact export, easy to use, configurable and whatnot. The "newly written"  animation exporter and animation libraries are gem as well.

So I was playing a bit with the exporter, to plan how to organize an upcoming project. I figured it would be a good idea to create new scenes in my blender file in order to export each scene later as a json object

![01](https://cloud.githubusercontent.com/assets/1114549/24078840/314674e6-0c79-11e7-828a-a5098738a692.jpg)

So uh, I will start going trough this issue by creating some example files based on the blender startup file. I loaded this startup file saved it and exported it immediately and selected scene, materials, lights, cameras and hierarchy in the exporter options. Everything worked out as supposed to.

![02](https://cloud.githubusercontent.com/assets/1114549/24078895/58206fb2-0c7a-11e7-98bc-d3e5efbec759.jpg)

[blenderandjsonfile.zip](https://github.com/mrdoob/three.js/files/853070/blenderandjsonfile.zip)

![03](https://cloud.githubusercontent.com/assets/1114549/24078892/4a14c008-0c7a-11e7-82d0-19ae1eec2bb6.jpg)

After this I created in the same blender file a new Scene and added a cube, light and camera into the newly created empty scene:

![04](https://cloud.githubusercontent.com/assets/1114549/24078918/3bd8d38e-0c7b-11e7-95e9-129045e5b7c9.jpg)

![05](https://cloud.githubusercontent.com/assets/1114549/24078919/3f7a95ea-0c7b-11e7-931e-f296aec02b48.jpg)

I tried to export this newly created scene with the same options in the exporter and produced following error log:

![06](https://cloud.githubusercontent.com/assets/1114549/24078930/8587c5b2-0c7b-11e7-952f-65233cc7ad7e.jpg)

Now I am not really a python developer but I tried to debug and track the issue a bit and was able to finally export my second scene. Unfortunately I wasn’t able to reproduce it but I saved the screen shot when I played with it a few hours ago and as you will see on this screen shot it  exported both objects from each blender scene into one Three.js scene:

![07](https://cloud.githubusercontent.com/assets/1114549/24079006/d323849e-0c7d-11e7-9fb4-9fb312f38a01.jpg)

So I might lean out too far out of the window but judging what I debugged so far I guess the exporter was never intended to export more than one defined blender scene. I tried to contribute somehow and checked the source code in order to improve the exporter but I couldn’t figure it out.

But hey the least I could do is to report what might be an issue : )

##### Enviroment
- [x] r84
- [x] Chrome
- [x] Firefox
- [x] Linux
- [x] Blender v2.76

**Comment by EvilProfesseur** [comment]
Were the elements in the first scene visible when you exported it? The exporter always fails for me in this manner if there are hidden elements. I just tried it and it produces the same error message

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
