### ISSUE TITLE
OBJExporter issue

### ISSUE THREAD

**Issue by davLap** [mrdoob/three.js#11032]
##### Description of the problem 
I exported CylinderGeometry(1, 1, 2, 6, 1) with OBJExporter. It should have 14 vertices and 24 faces.
Result is that exported object have 72 vertices and 24 faces. Each face creates 3 vertices even if vertex is shared with another face.

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by davLap** [comment]
I checked, It seems that OBJExporter calls a function which eventualy comes to a function DirectGeometry.fromGeomerty. This function then creates vertices based on faces. So if a face shares a vertex with another face, the same vertex is created twice. It face shares the same vertex, vertex is created each time. The same goes for normals, colors, uvs. 
I don't know, but is there some reason to do that? If there no reasons, I think that number of vertices, normals, uvs... of a mesh should be preserved (the same vertex shouldn't appear more than one).

**Comment by mrdoob** [comment]
Have you tried  using `CylinderBufferGeometry()` instead?

**Comment by NeklesaYuri** [comment]
The same issue worries me, how to make it work witch custom geometry.
Because after I've imported a model that was 4mb, after exporting it gets 40mb.
I inspected it in 3dmax, and noticed that all polygons are detached

**Comment by mrdoob** [comment]
Yeah... Unfortunately, three.js can't retain the obj data structure when loading. It needs to be transformed to a more webgl-ready data structure.

**Comment by mrdoob** [comment]
Closing this for now.
