### ISSUE TITLE
CylinderBufferGeometry: Wrong shading by duplication of one normal per ring possible

### ISSUE THREAD

**Issue by jostschmithals** [mrdoob/three.js#11046]
The CylinderBufferGeometry constructor produces doubled vertices and normals in the places where a ring is closed. This could result in wrong shading (one non-smoothed edge), in the screenshot only for demonstrating purposes forced by a call of computeVertexNormals().

![cylinder](https://cloud.githubusercontent.com/assets/5700294/24242974/d8ab194c-0fb9-11e7-8cb2-4c4a5fdcf45f.PNG)

Wouldn't it be cleaner to have no doubled vertices/normals at all on the sides? The duplication could easily be avoided in the constructor (by only doubling a row’s start index in the index array instead of doubling the vertex and normal). 

But since it’s the same with SphereBufferGeometry and SphereGeometry, I wonder whether the duplication is perhaps made intentionally for some reason I don’t know?

r85dev

**Comment by Mugen87** [comment]
You need an additional line of geometry data at the end because uv-coordinates differ. So it's necessary to ensure that textures are projected correctly.

**Comment by jostschmithals** [comment]
That makes sense. Should have had that in mind. Thanks!
