### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by wothke** [mrdoob/three.js#11042]
##### Description of the problem 

suggested enhancement:

When accessing the documentation via a Google search result (e.g. https://threejs.org/docs/api/core/Object3D.html) the detail pages come without the higher level navigation frame and consequently none of the embedded hyperlinks work. 

Ideally respective "Google links" should be automatically redirected (e.g. to https://threejs.org/docs/index.html#Reference/Core/Object3D) - but as a quick-win it would already improve usability if some kind of additional "home" link (mb next to the existing "edit" link) was provided on the detail pages..

##### Three.js version

- [ ] Dev
- [ ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by jostschmithals** [comment]
I made a pull request to solve this issue 2 weeks ago, but it has not yet been handled:
#10948
#10937
