### ISSUE TITLE
Docs: 1. Browser navigation not working; 2. Query strings needed?

### ISSUE THREAD

**Issue by jostschmithals** [mrdoob/three.js#11052]
Initiated by some discussed issues*) I am currently working on an improvement/refactoring of the doc’s main code (without changing the underlying iframes structure). Here are two additional issues:

**1. Browser navigation not working**

In the current version of the docs (https://threejs.org/docs) the browser navigation is working only in Edge. In FF and Chrome the back button works only one single time directly, but then you have to hit it always (at least) twice (Chrome showing the wrong URL every second time). The forward button is, depending on the situation, completely disabled or not working at all.
 
The reason: Unfortunately the default behavior associated to iframes is pushing two states to the browser history on each page change. This must be handled in a special way.
 
After having found a proper working cross-browser solution, a further question followed:

**2. Are query strings in the URL really needed?**

Currently the values of the search/filter input field don't only filter the entries of the navigation panel, but they are additionally reflected in the URL (in the form of dynamically increasing and decreasing query strings), and I don’t know what’s the purpose. For me the query strings make no sense in this place. I can’t imagine an advantage to have them here (having the deep links to the subpages is sufficient), and on the other hand I think the query snippets in the URL could cause confusion (and this feature could interfere with the browser navigation):

For instance: if someone types in “bo”, finds the BooleanKeyFrameTrack subpage, saves the link (https://threejs.org/docs/?q=bo#Reference/Animation.Tracks/BooleanKeyframeTrack) or sends it to someone. When the link is reopened, the navigation panel shows only the items that had (more or less accidentally) “survived” the filtering before. I think that’s no useful behaviour?

So I would like to remove the query strings from the URL (the search/filtering itself would work as before of course).

-----
*)
- broken links and missing navigation on the subpages #10937; 
- two different series of URLs for the same subpages #10948; 
- some redundancies and oddnesses in the code – for instance #11047  ;-)

**Comment by spite** [comment]
The idea of query strings was for /examples, so you could provide people looking for advice with links like https://threejs.org/examples/?q=webvr or https://threejs.org/examples/?q=loader. In /docs the idea made less sense, but the code was added similarly (things like https://threejs.org/docs/?q=audio). It was an improvement of the original experience of the docs and examples UI doing the minimal refactoring, when filtering results was added.

**Comment by jostschmithals** [comment]
No doubt – in the examples this is a valuable feature (and I had already assumed that it was implemented for those first)!

But I think in the docs it would be much harder to create a useful selection of pages by filtering, since there is no homogeneous naming convention. 

For example: If you type “Animation” to learn something about the new animation system, all KeyFrameTrack classes belonging to this system will be hidden, but KeyFrameAnimation of the collada loader will be shown. 

From my point of view the disadvantage outlined in my first post has more weight than possible advantages. That's the reason why in the docs (and only in the docs) I would limit the filtering to the direct live search, without query strings. 

But of course this is only my subjective evaluation.
