### ISSUE TITLE
rotation after pan is not correct

### ISSUE THREAD

**Issue by AngelTsTsvetkov** [mrdoob/three.js#11077]
When rotate some object after pan using OrbitControls.js or TrackballControls.js. The result is not expected except if object is in the middle of the screen.

**Comment by WestLangley** [comment]
`OrbitControls` and `TrackballControls` rotate and pan the _camera_ -- not the object.

**Comment by AngelTsTsvetkov** [comment]
so there is no easy way to rotate object (by standard way) after pan?

**Comment by WestLangley** [comment]
See https://threejs.org/examples/misc_controls_transform.html, for example.

**Comment by AngelTsTsvetkov** [comment]
in all examples, there are no simple way to rotate and move object ...
