### ISSUE TITLE
WebVRCamera layers and viewport

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#11071]
##### Description of the problem 

It looks like the WebVRCamera doesnt display layered objects because of the projection :)

https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1307

##### Three.js version

- [ ] Dev
- [ ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Samsy** [comment]
Sorry I've not read the previous thread,
Seems like you are taking care of it.

[](https://github.com/mrdoob/three.js/issues/10927)

Closing this one !

**Comment by mrdoob** [comment]
Uh oh. I hadn't thought of that. I guess that logic should be moved somewhere else...

**Comment by Samsy** [comment]
Hum pretty easy workaround at the end you could do : 

![capture d ecran 2017-03-28 a 14 34 39](https://cloud.githubusercontent.com/assets/3786958/24407743/b21c2a24-13c3-11e7-8e03-182f1f3c2d78.jpg)

**Comment by Samsy** [comment]
I also noticed you need to reset the viewport if you are using a target ( for postprocessing purpose ) using the webVR camera.
In that case you might not want to submit the frame directly.

https://github.com/mrdoob/three.js/blob/dev/examples/js/vr/WebVRCamera.js#L141

**Comment by Samsy** [comment]
I can pull request the project object thing if you wish me to !

**Comment by mrdoob** [comment]
Yeah! It would be great if you could do a PR with your use case as a example so I can keep it in mind when designing WebVRCamera.

**Comment by Samsy** [comment]
@mrdoob 
https://github.com/mrdoob/three.js/pull/11083
