### ISSUE TITLE
THREE.js Loaders and Ajax Requests

### ISSUE THREAD

**Issue by Coburn37** [mrdoob/three.js#11072]
##### Description of the problem 

The THREE.js loader system is great for small applications but trying to scale it into larger applications is proving to be a pain. I had recently had a need for URL rewriting (which, `setPath` type functions help with this somewhat but not for all use cases like querying API endpoints for resources) as well as custom headers (like authentication tokens). [A somewhat recent SO post shares this sentiment](http://stackoverflow.com/questions/41507098/how-can-i-set-headers-on-an-outgoing-three-textureloader-request)  but has been unanswered and the user notes in an edit that this behavior isn't configurable due to no sort of exposition of functionality in loaders like [ImageLoader](https://github.com/mrdoob/three.js/blob/dev/src/loaders/ImageLoader.js#L43).

THREE.js doesn't have a good API to manage all the ajax calls within the loader system such that the calls can be specified and modified externally. I looked into how [Ember.js does it](https://github.com/ebryn/ember-model#customize-ajax-settings) as a start and there's this `RESTAdapter` class you can create/extend to add the functionality you desire but this doesn't really seem to be a good fit for THREE.js due to the global nature of the `THREE` object in some environments.

For THREE.js specifically, one possibility might be to use the `LoadingManager` class and add functionality in there to handle ajax modification (something like a `setLoadingStrategy(url, method)`, that returns an object to merge with default ajax options. Sane defaults could be provided in `DefaultLoadingManager`.

I was just looking to see if there was any interest in this and possibly ongoing work regarding this. Currently, in this application, I'm thinking about just monkey patching everything I need but a more robust solution would be preferable given time trade off consideration

**Comment by hccampos** [comment]
This would indeed be highly appreciated. But also pretty tricky given the inconsistencies between all the loaders. At the moment we are simply monkey-patching the required classes to add the necessary configurations.

**Comment by fraguada** [comment]
@tentone has generalized loading for assets/resources in his [nunuStudio library](https://github.com/tentone/nunuStudio/tree/master/source/core/resources).  It might be worth looking at his implementation to see how the loading system could be generalized to handle different resources.  @tentone do you do the same abstraction for the various mesh formats?  Is it technically feasible to abstract all resources?  If so, would such a universal loader perform well?

**Comment by tentone** [comment]
@fraguada i believe @Coburn37 objective is different, what i have done was to create a single abstraction to load every resource format available directly from the resource object, (eg Image can load not only normal images but also TGA files automatically), the resource object is also responsible for serialization (i need it in nunuStudio, but honestly i think that object serialization should be moved to external modules in threejs).

But for every new loader i have to go there and add it manually. To solve the problem described above one solution could be to register every loader and its loading configuration in a generic loader. Something like.

```
//XPTO file loader
THREE.XPTOLoader =
(...)
//Still inside the XPTO file loader module registering the constructor and loading parameters
THREE.GeometryLoader.register(THREE.XPTOLoader, "arraybuffer", ...);
(...)
//Usiing the generic loader
var loader = new THREE.GeoemtryLoader();
loader.setPath(...);
loader.load("abc.obj", function(obj){...});
loader.load("abc.dae", function(dae){...});
loader.load("abc.3ds", function(ds){...});
```

but this limit loaders accessed using the generic loader (some loaders might require special configuration parameters (eg, list of materials, list of textures etc).

**Comment by Coburn37** [comment]
@tentone I think this is actually what I'm looking for. One of the huge things I need aside from being able to add headers is to be able to just parse/pass the raw data such as one might get from unpacking a loaded `.zip` file. Though it'd be even nicer if something like `Promises` could be used such that no matter if it's through an Ajax request, through zip unpacking, or just a simple auto resolving promise, the data could be parsed asynchronously and it's loading could be completely decoupled from the parsing of it (although I foresee there would be problems implementing `MTLLoader`)

[`Promises`](http://caniuse.com/#feat=promises) are unfortunately not supported in `IE11` which I believe is the only meaningful target that'd be left out of support that also supports WebGL and I don't think this would be a compromise I or most people that use this library would want to make.

A coworker pointed out that there was a [little work done in `FileLoader`](https://github.com/mrdoob/three.js/blob/dev/src/loaders/FileLoader.js#L192-L196) by @takahirox in #10708 but because `FileLoader` is used everywhere else via composition and not inheritance, it's not super useful from any other loader that doesn't also support the same function. Similarly, the method used in `ImageLoader` doesn't actually allow the addition of headers (at least to my knowledge, if you create an `img` element and add the `src` you have no way to modify its request)

**Comment by Coburn37** [comment]
Here's the problem in more formal terms as well as the solution that seemed like the best fit for the requirements and the amount of effort to put in.

#### Requirements:

* Must be able to modify underlying asset request method in loader (ajax, or just passing raw data)
    * Must be asynchronous so as to allow external request to be variable in length
    * Should be configurable at a loader instance level so that each loader may be configured differently but have a sane default
* Legacy support for scheme of passing a URL to instance as well as calling `setPath()`

#### Potential Solutions:

From the solutions I considered, there seemed to be a commonality to support the above requirements. There would need to be some sort of _asset resolution function_ which, given an identifier (a path, a url, whatever) would return a `then-able` (`Promise` in environments that support that). The solutions considered were:

1. Convert the current structure of composition to one of inheritance. Loaders all inherit from some `BaseLoader` class that implements the _asset resolution function_.
2. Add functionality to `FileLoader`, convert those loaders that use `ImageLoader` to use `FileLoader` OR change `ImageLoader` to support things similar to `FileLoader` too. `ImageLoader` creates an `img` element and loads the image with the `src` attribute which does not lend itself to modification easily. From here, expose all the functionality of _asset resolution function_ added to `FileLoader` and `ImageLoader` in the loaders that rely on these.
3. Modify `LoadingManager` to support the _asset resolution function_ as it's already passed around and even passed from parent to child loaders.

In order to see which solution would be a good fit, I dumped the dependencies of just the loaders to see how many currently use `LoadingManager` as well as to see how the current structure lends itself to using inheritance instead of composition.
![image](https://cloud.githubusercontent.com/assets/6759176/24780386/db327ff6-1b04-11e7-883d-374465065234.png)
It's best viewed [in the WebPack interactive viewer](http://webpack.github.io/analyse/) with the filtered webpack stats json file [that you can get from here](https://gist.github.com/Coburn37/7cd2686ac6d4e5a12f4489f847d061c4). From this, it can be seen that the top-most node (`LoadingManager`) is included in almost all other nodes (where the ones it's not included in don't matter all too much. Similarly, while both `FileLoader` and `ImageLoader` are used in pretty much all the classes, there's one or two where they're not used and the rest of the loaders have a pretty messy dependency graph. I don't think switching to inheritance (even partially) would really be a benefit and would turn out to be a headache.

Therefore, I think that modifying the `LoadingManager` to have the _asset resolution function_ defined above would be the best route to take. I believe it to be less work than trying to expose the functionality throughout all the loaders as it would just require making sure the current loaders pass `LoadingManager` around properly as well as using it as the sole source of asset resolution.

The proposed _asset resolution function_ would end up looking something like the following and would be added to the `LoadingManager`. It would not replace `FileLoader` or `ImageLoader` but would be the core functionality for these loaders.

    LoadingManager.getAssetFor(loader, ident, type) {
        //Using loader and ident (most likely a url), load the file data with type : type
        return { then : (func)=>{ func(""); } }; //Would return a then-able object (or a Promise in environments that support it) that would return the corresponding data for the given ident
    }

Considering THREE.js has no dependencies right now, the `then-able` object would have to be some internal, tiny, `Promise`-like polyfill.

That is my proposed solution and when it becomes necessary I will probably implement this where I can. Does anyone see any pitfalls or have suggestions on this?

**Comment by donmccurdy** [comment]
I patched THREE.GLTFLoader to support drag-and-drop with textures and extra binary resources. The relevant change was https://github.com/donmccurdy/three-gltf-viewer/commit/cf4f96ec1d1ee410409762a38deb72b1251d2637 

+1, it would be very nice to have drag-and-drop support for more formats in the editor. 🙂

***

@Coburn37 Of your three options listed, I agree that (3) is the most realistic. My concern with the first two is that loading a single asset might take multiple `FileLoader` instances, some created within the loader, so there's no obvious place to add the interceptors to a `FileLoader`.

But from your initial requirements, I don't think it's necessary to be asynchronous:

```js
const localAssets;

loadingManager.setURLTransform( function ( path, url ) {

  if ( localAssets.has( url ) ) {

    return URL.createObjectURL( localAssets.get( url ) );

  }

  return path + url;

} );

const loader = new THREE.MyFormatLoader( loadingManager );

loader.load( url );
```

The `FileLoader` could then use `LoadingManager` to resolve URLs this way, synchronously, and make an AJAX request to the URL it gets back. If it's a local asset, you just create a Blob URI to that local asset.

**Comment by donmccurdy** [comment]
LoadingManager now has a method to allow overrides of resource URLs. As long as model loaders use the manager for all requests (if any are not, that’s a bug) it should “just work” for any model format.

https://github.com/mrdoob/three.js/pull/11259
