### ISSUE TITLE
Ask for help: It is about “3D model’s problems in Chrome

### ISSUE THREAD

**Issue by sallypanda** [mrdoob/three.js#11084]
There are two situations in our website program.
It is about the **3D model in Chrome**,
One is no problem, an other has some problems.

The perfect one tested in my Chrome, everything runs well.

![](http://pccase.bluej.cn/media/1.jpeg)

But an other one was mapping dislocation. (**Chrome 57.0.2987.110 version**)

![](http://pccase.bluej.cn/media/2.jpeg)

When I used** “Canvas Texture”**, it was error occurred, but used **“.JPG” or “.Png”,** it worked.(It is the reason why we have to use CANVAS) 。This is [my site](http://buer.bluej.cn/src/html/exports/3d.html)

In this [website](https://threejs.org/examples/#webgl_loader_utf8) ,the samples also has problems, like this:

 ![](http://pccase.bluej.cn/media/3.png)

Do you know how to solve the problems with my website? 
Emergency! Thanks a lot.

**Comment by Mugen87** [comment]
Not sure i've understood the actual problem. 

Let's focus on the [three.js example](https://threejs.org/examples/#webgl_loader_utf8). Can you describe in detail what problem occurs? When i've open the example in my Chrome (57.0.2987.133) on Mac OSX, everything looks fine.
