### ISSUE TITLE
Disappearing objects while crossing opacity boundary

### ISSUE THREAD

**Issue by rkwright** [mrdoob/three.js#11085]
##### Description of the problem 

I have a collision detection demo which you can see [here](http://geofx.com/graphics/nehe-three-js/lessons25-32/lesson30/lesson30webgl.html).  It works fine.  However, if you rotate the cube about 45 degrees around the Y-Axis and then watch the bouncing objects closely, especially the Cubes, you will see that occasionally the objects will disappear for a fraction of a second. 

It appears that it occurs when the object crosses the boundary from the right-hand wall, which is partially transparent and across into (or out of) the front wall, which is wholly transparent.

This looks like a bug in the shader to me, but perhaps I am misunderstanding what is going on.

The sources for the demo are [here](https://github.com/rkwright/nehe-three-js/tree/develop/lesson30)

I have not had an opportunity to test on various systems, but it occurs on my new MacBookPro and my ancient Mac Pro. I also have seen it occur in both Safari and Chrome on my iPad 5.

##### Three.js version

- [ ] Dev
- [x ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [x ] iOS

**Comment by rkwright** [comment]
Also tested on Windows 10 (Lenovo laptop).  Saw same behaviour on Edge and Chrome.  Not so sure about the opacity angle, but it is interesting that it seems to only occur with the Cubes and not any of the other meshes?

**Comment by mrdoob** [comment]
I think the problem is here:
https://github.com/rkwright/nehe-three-js/blob/develop/lesson30/lesson30webgl.html#L102

Because you're setting the cube to be transparent, the renderer is sorting them (sometimes) in front of the walls and things break. z-buffer is annoying like that.

**Comment by rkwright** [comment]
Ah so.  Stupid of me.  I should have looked more carefully at the cube construction when I realized that only the cubes seemed to suffer this problem.  Many thanks for pointing this out to me!  The perils of cut and paste! Now fixed (thanks to your insight).  Closing.
