### ISSUE TITLE
Three.js Issues Running In CocoonJS Canvas+ On Nexus 7

### ISSUE THREAD

**Issue by jdd4494** [mrdoob/three.js#11090]
##### Description of Bugs

There were two bugs found when trying to run three.js inside of CocoonJS canvas+:

Issue #1:
Canvas+ does not support createElementNS, which causes a crash within the CocoonJS Canvas+ environment on both iOS and Android.  We were able to fix this by replacing createElementNS with createElement.  

Issue #2:
However, after fixing this we ran into a bug specifically on the Nexus 7 (might also effect other Android devices).  The error read:

        ERROR: 0:93: ‘const’: overloaded functions must have the same parameter qualifiers 
	ERROR: 1 compilation errors. No code generated.

It appears the WebGLShaders being created through Three.JS are unable to compile, and are causing a crash.  From what we can tell, it is an issue within three.js when trying to pass in the shader source.  Upon further investigation, it seems the main culprit was the function:

        `mat3 transpose( const in mat3 v ) {
		tmat3 tmp;
		ttmp[0] = vec3(v[0].x, v[1].x, v[2].x);
		ttmp[1] = vec3(v[0].y, v[1].y, v[2].y);
		ttmp[2] = vec3(v[0].z, v[1].z, v[2].z);
		treturn tmp;
	}`

We appeared to fix this by removing the 'const in’ from the parameters. This was being set in: var common (~line 4944) 

Attaching our modified Three.js library.  Any chance you can take a look?  Unfortunately, our project specifically needs to run within CocoonJS's Canvas+ environment.  It seems our patch accomplishes this, but would like a second set of eyes to confirm there are no repercussions to our changes.

[three.js.zip](https://github.com/mrdoob/three.js/files/882767/three.js.zip)

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [x] iOS

**Comment by mrdoob** [comment]
There are a bunch of consts in that file...
https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/common.glsl

**Comment by Mugen87** [comment]
I don't think we should change something. Instead i recommend to report these problems as bugs or feature request to `Canvas+`. [Document.createElementNS()](https://developer.mozilla.org/de/docs/Web/API/Document/createElementNS) is supported in all major browsers and the `const in` is also no exotic syntax.
