### ISSUE TITLE
How to generate structures based on arbitrary code

### ISSUE THREAD

**Issue by wolffe** [mrdoob/three.js#11096]
Given this code:

```
{
( 256 64 16 ) ( 256 64 0 ) ( 256 0 16 ) mmetal1_2 0 0 0 1 1
( 0 0 0 ) ( 0 64 0 ) ( 0 0 16 ) mmetal1_2 0 0 0 1 1
( 64 256 16 ) ( 0 256 16 ) ( 64 256 0 ) mmetal1_2 0 0 0 1 1
( 0 0 0 ) ( 0 0 16 ) ( 64 0 0 ) mmetal1_2 0 0 0 1 1
( 64 64 0 ) ( 64 0 0 ) ( 0 64 0 ) mmetal1_2 0 0 0 1 1
( 0 0 -64 ) ( 64 0 -64 ) ( 0 64 -64 ) mmetal1_2 0 0 0 1 1
}
```

How can I generate a cube using JavaScript (or any additional library) and the coordinates above. The code above should be interpreted as follows:

> In the example shown here, this brush is a 6 sided cuboid. The plane of its first face is defined by 3 points, ( 256 64 16 ) ( 256 64 0 ) ( 256 0 16 ). The other information supplied is the texture used by the face. "mmetal1_2" is the name of the texture, a single plane may only have a single texture. "0 0 0 1 1" are how the texture is display, and are respectively "X offset" "Y offset" "Rotation" "X scale" and "Y scale".
> 
> The plane points ( p1 ) ( p2 ) ( p3 ) are interpreted as follows. The plane points must be arranged such that the cross product of the vectors (p3 - p1) and (p2 - p1) is not null, that is, the three points must be linearly independent. Then, the normalized cross product represents the normal vector of the plane. Every point p for which (p - p1) * normal <= 0 (where * is the dot product) holds is considered to be in the half space defined by the plane. Every other point is considered not to be in the half space.

**Note 1:** CSS can be used, if necessary.

**Note 2:** What I actually need here is the concept and the mathematical functions. I can extract the coordinates using a JavaScript loop, but I don't know how to initially approach this. I just need a nudge in the right direction.

Here are the specifications for this coordinates system:
https://quakewiki.org/wiki/Quake_Map_Format

**Comment by looeee** [comment]
This is not a help site. But if you ask over on the forum or on stackoverflow, someone might help you.

**Comment by wolffe** [comment]
I have already asked on StackOverflow, but I thought three.js could do this. I have found several tutorials, but the coordinates looked different.

**Comment by jostschmithals** [comment]
> UPDATE: Where is the forum?

https://discourse.threejs.org/

**Comment by wolffe** [comment]
Thanks!
