### ISSUE TITLE
configurable Object3D properties

### ISSUE THREAD

**Issue by sublambda** [mrdoob/three.js#11092]
##### Description of the problem 

Properties in Object3D are defined to be non-configurable (i.e. Object.defineProperty default), which prevents proxies and subclasses from enhancing Object3D properties. Please consider making these properties configurable.

There are excellent reasons to _not_ make these fields writable, as discussed in [issue #8940](https://github.com/mrdoob/three.js/issues/8940). On the other hand, making the properties configurable provides the ability to extend the API without negative impact on the core interface.

##### Three.js version

- [x] Dev
- [ ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
The reason these are non-configurable is because people was doing stuff like this for copying positions:

```js
object.position = object2.position;
```

**Comment by sublambda** [comment]
Indeed, I understand that it's essential to prevent that. Making the properties configurable would not allow this (that is, they would still be unwritable), so it would not be possible to re-assign the property value naively.

Of course, adding configurable:true would still allow people to redefine these properties in subclasses to make them writable (if one were foolish enough to do that), but the change would not affect Object3D itself. 

thanks for the quick feedback!

**Comment by mrdoob** [comment]
Hmm, do you mind elaborating a bit more?

**Comment by sublambda** [comment]
sure, suppose I want to create a subclass of Object3D that redefines the position property to make it writable -- this affects _only_ instances of MutableObject3D. Instances of Object3D are not affected, so accidental (or naive) property value assignment is still prevented.
```
function MutableObject3D() {
  THREE.Object3D.call(this);
  Object.defineProperties( this, {
    position: {
      writable: true
    }
  });
}
```

ES6 proxies are another way of customizing property access which works only if the property is configurable.

**Comment by mrdoob** [comment]
I think I just need a use case.

**Comment by sublambda** [comment]
one use case: extended version of Object3D to allow transform state (position,scale,rot/quat) to be efficiently shared across multiple synchronized scene graphs.

**Comment by mrdoob** [comment]
I see... What do you think would be the side effects of making these properties configurable?

**Comment by sublambda** [comment]
I don't think there are any negative side effects, unless we're worried about people deleting properties (e.g. delete object.position), which seems like an improbable failure mode (doesn't seem likely that anyone would try to lose like this).

**Comment by mrdoob** [comment]
So people won't be able to do `object.position = object2.position`, but people will be able to do `delete object.position` and `Object.defineProperty( object, 'position', { value: object2.position } )`. Right?

**Comment by sublambda** [comment]
Correct. I assume that anyone using Object.defineProperty in this way knows what they're doing in some sense...it's a deliberate modification, as opposed to an innocent assignment error.

**Comment by mrdoob** [comment]
I see. Okay, sounds good to me. Would you like to do a PR for it?

**Comment by sublambda** [comment]
done, thanks @mrdoob
