### ISSUE TITLE
OBJLoader error on .dds load

### ISSUE THREAD

**Issue by niks123123** [mrdoob/three.js#11091]
##### Description of the problem 
Hello guys! When I'm trying to load textures for my object (DDSLoader+OBJLoader) I have this error:

> THREE.WebGLRenderer: WEBGL_compressed_texture_pvrtc extension not supported.

```JavaScript
var onProgress = function ( xhr ) {
	if ( xhr.lengthComputable ) {
		var percentComplete = xhr.loaded / xhr.total * 100;
		console.log( Math.round(percentComplete, 2) + '% downloaded' );
	}
};

var onError = function ( xhr ) { };

THREE.Loader.Handlers.add( /\.dds$/i, new THREE.DDSLoader() );

var mtlLoader = new THREE.MTLLoader();
mtlLoader.setPath( 'mtl/' );
mtlLoader.load( 'adder.mtl', function( materials ) {

	materials.preload();

	var objLoader = new THREE.OBJLoader();
	objLoader.setMaterials( materials );
	objLoader.setPath( 'obj/' );
	objLoader.load( 'adder.obj', function ( object ) {

	scene.add( object );

	}, onProgress, onError );

});
```
Can someone help me to fix it?
##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Looks like the extension [WEBGL_compressed_texture_pvrtc](https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_pvrtc) is not supported by your browser. You can also test this with one of `three.js`s examples: https://threejs.org/examples/#webgl_materials_texture_pvrtc

Do never rely 100% on extensions. Always provide a fallback path if the extension is not supported. For example you could load uncompressed textures instead.
