### ISSUE TITLE
webVR

### ISSUE THREAD

**Issue by simon3948** [mrdoob/three.js#11119]
the webVR examples dont seem to work at all using chrome on android, any suggestions?

**Comment by Mugen87** [comment]
What do you mean with _don't work_? Do you get a white screen, error messages or warnings? What kind of VR device are you using? 

BTW: It's not a bad idea to fill out the default template that you see when you create a new issue. These information a very useful to solve the problem.

**Comment by Mugen87** [comment]
I think we have to add an origin trials token to all WebVR examples.

@simon3948 Just to be sure: This example here works for you, right? https://webvr.info/samples/03-vr-presentation.html

**Comment by simon3948** [comment]
yes that one works fine, looks like thats the problem

**Comment by mkeblx** [comment]
Or can turn on WebVR flag in chrome://flags which probably want on if doing WebVR dev anyhow.
