### ISSUE TITLE
Add an options for ExtrudeGeometry to close or not the lids.

### ISSUE THREAD

**Issue by Horsetopus** [mrdoob/three.js#11118]
##### Description of the problem 

Request: Add an options for ExtrudeGeometry to close or not the lids.

##### Three.js version
- [x] r84

##### Browser
- [x] All of them

##### OS
- [x] All of them

**Comment by Mugen87** [comment]
https://github.com/mrdoob/three.js/pull/10268#issuecomment-264529568
