### ISSUE TITLE
ShadowMaterial and opacity: options not availlable in constructor parameters.

### ISSUE THREAD

**Issue by Horsetopus** [mrdoob/three.js#11116]
Hi,

Opacity parameter not considered when using it in the parameters object
For example, this doesn't set the opacity:
var shadowMaterial = new THREE.ShadowMaterial( { opacity: 0.5 } );

You have to do this:
shadowMaterial.opacity = 0.5;

Not a big issue, but it's inconsistant with the other material constructors.
Got me scratching my head for a while.

##### Three.js version
- [x] r84

##### Browser
- [x] All of them

##### OS
- [x] All of them

**Comment by Mugen87** [comment]
Fixed with #11160.
