### ISSUE TITLE
THREEjs fails to load with LESS.js running asynchronously

### ISSUE THREAD

**Issue by gospodnetic** [mrdoob/three.js#11117]
##### Description of the problem 

In case of longer model retrieval and rendering process, threejs fails to set up a canvas if there is a LESS.js running asynchronously. By fails to set up the canvas, I mean - the element into which the canvas should be placed is probably not yet loaded and canvas comes with both width & height = 0.

Half-solution is to set async="false" within the script tags linking to the less.js, but that is only half as it will make the rendering process to work most of the times. If you set async false on all of the scripts, it also won't work...
Other half-solution is to load the less.js only at the bottom of the body

The thing is, if less is rendered before rendering initialization is started, you don't get anything :/

##### Three.js version

- [x] r84

##### Browser

- [x] Chrome
- [x] Firefox

##### OS
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
@gospodnetic Maybe this works for you?

```javascript
window.onload = function ( event ) {

   init(); // start your three.js logic after all resources have loaded

}
```
The code of `init()` could look like [this](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_animation_cloth.html#L125).
