### ISSUE TITLE
BlendCharacter example: List of bugs and further issues

### ISSUE THREAD

**Issue by jostschmithals** [mrdoob/three.js#11126]
Currently making a thorough revision of the [BlendCharacter example](https://threejs.org/examples/#webgl_animation_skinning_blending) I’ve noticed several bugs (which will not be difficult to fix) and would like to ask if they can be reproduced by others. 

Here some situations in which they are occurring (there are many more similar ones):

0. Reload.
Drag the sliders.
_This causes rotations of the character around its y-axis (since the second parameter in the OrbitControls constructor is missing)_

1. Reload.
Try to set one of the “Blend Tuning” sliders to 1.0.
_This is only possible by dragging the mouse about 1 meter out of the screen, or indirectly by setting the other two sliders to 0 (Reason is the "normalization" of the sum of weights)._

2. Reload.
Set “idle” to 0 and “run” to 0, so that “walk” is implicitly set to 1. 
Try to decrease the “walk” value.
_This is not possible.
If you drag the mouse further to the left, all weight values are set to NaN, and clicking “start” doesn’t function any longer._

3. Reload.
Set “idle” to 0.
Click “walk to run”.
After finishing the crossfade (but the character continuing running) move “idle” to ca. 1 (so that the “run” slider moves to 0). 
_The character doesn’t change from “run” to “idle”, but to the  T pose. This is at least a confusing behavior (since the user doesn’t know, that in spite of dragging the slider the “idle” animation, which was deactivated under the hood by “walk to run”, remains deactivated, until all animations are restarted), and it feels like a bug since the different activation states belonging to the “Blend Tunes” sliders can’t be seen anywhere._

4. Continue from above without reloading (and without changing something different).
Set “run” to ca. 1.
Click “idle to walk”.
After finishing the crossfade (but the character continuing moving) decrease the value of “run”. 
_The character makes weird movements (while kind of hovering over the ground)._

5. Reload.
Set “run” to 0.9.
Click “idle to walk”.
After finishing the crossfade (but the character continuing moving) try to drag the “run” slider upwards. 
_Instead of this the “walk” slider and the “run” slider jump back suddenly (this happens because the third slider is not set to 0 when crossfading between the two other animations)._

6. Continue from above without reloading (and without changing something different).
Increase “run” to 1. 
_The character stops its motion and goes into T-pose.
Since the user doesn’t know that “run” had been deactivated by “idle to walk” (in 5.) and was not re-activated by moving the slider, I suppose he wouldn’t expect this, since the “run” slider is not disabled, and since the character was moving before (so why should the user click “start” again to reset the animation?). I would consider this to be a bug, too. It’s at least very counter-intuitive._

(Windows 10, all browsers)

**Comment by jostschmithals** [comment]
In addition to fixing these bugs I would like to change some further behavior in this example (if it is okay) to achieve a better user experience:

1. Pause button

If you have started the animation and then click “pause”, the motion is interrupted as it should, but then there is no possibility to continue from this state of movement (as one would expect it from a normal “pause” functionality). You have always to restart from the beginning by clicking “start” again (try “run” with a low timescale to see the difference). I would expect for instance a toggling functionality of this button (pause/continue).

Curiously enough: If you are in “step” mode, the “pause” button has the unpausing functionality which it is missing otherwise.

2. Initial weights

The initial weights (idle 1/3, walk 1/3, run 1/3) cause a non-natural movement of the character, until these values are changed. I think splitting the weights like this in such an initial static state makes not much sense. A mix of such animations makes only sense if it is done dynamically (like in the crossfades). So I would start for instance with (idle 0, walk 1, run 0).

3. Interruptions instead of smooth transitions

If the user clicks on “start“ with (idle 0, walk 1, run 0) to let the character walk, and if he makes a crossfade from “walk to run” afterwards, he should get a smooth transition. Instead of this the movement is interrupted first, since the action always starts from the beginning when clicking  “walk to run” (although the character is already walking). Same behavior with the other crossfades.

**Comment by jostschmithals** [comment]
There are some redundancies, unnecessary repeatings and further mistakes in the code (for instance: If no skinnedMesh can be found, an Uncaught TypeError will be thrown in line 29 in spite of the related test in the code. The reason: This test will never be reached since it comes too late (not until lines 31 to 37)).

All this is easy to fix, but I have one additional general question that I could not answer myself up to now: 

Is there a reason why there was implemented an extra event listener system for this example’s dat-gui, instead of using the built-in dat-gui functionality? This additional complexitiy is not the reason for the indecated bugs, so one could keep it untouched. But I can’t see an advantage of this extra implementation(?)

**Comment by mrdoob** [comment]
> What was the reason for implementing an extra event listener system for this example’s dat-gui, instead of using the built-in dat-gui functionality?

The answer may raise up if you try to remove it 😁

**Comment by mrdoob** [comment]
Everything sounds great by the way. The simpler the better!
