### ISSUE TITLE
ObjectLoader not firing done callback with json exported from blender

### ISSUE THREAD

**Issue by cesarpachon** [mrdoob/three.js#11125]
(note: I also published this in stackoverflow, I post here too because I suspect it is a bug
http://stackoverflow.com/questions/43207737/three-js-objectloader-not-firing-done-callback-with-json-exported-from-blender
)

I am using Three.js rev 84, blender 2.76 with three.js plugin 1.5.0. I am exporting a simple scene with a few meshes, no animations. the JSON looks good, but when I try to load it into javascript I only got progress callbacks being called, but neither the main callback nor the end callback:

```js
    var _self = this;
    var loader = new THREE.ObjectLoader();
    loader.load("../experiment01/cubic_character.json",function ( obj ) {
      //never called 
      _self.scene.add( obj );
},  function(a){
  //progress callback is called
}, function(b){
  //never called
})
```

I used the debugger to check the load process, it is parsing everything (I can see the hierarchy of children in the debugger) but in the parse method, that is supposed to call the load callback, it skip the call and just returns:

```
(33129) parse: function ( json, onLoad ) {
..
if ( json.images === undefined || json.images.length === 0 ) {
                if ( onLoad !== undefined ) onLoad( object );
            }
            return object; //it just returns here!
}
```

the code that calls the parse function does nothing with the return value:

```
(3311):             scope.parse( json, onLoad );
```

so, no callback being called, nothing being returned.. I wonder if it is a bug or I am missing something and using the loader in the wrong way. thanks.

**Comment by mrdoob** [comment]
Can you share the exported file?

**Comment by cesarpachon** [comment]
sure! 
[cubic_character.zip](https://github.com/mrdoob/three.js/files/894076/cubic_character.zip)

**Comment by mrdoob** [comment]
I see... I guess the loader breaks when images can't be found...

![screen shot 2017-04-04 at 14 13 55](https://cloud.githubusercontent.com/assets/97088/24678848/14075d9e-1941-11e7-91c8-802db656e680.png)

**Comment by mrdoob** [comment]
Fixed. Thanks!

**Comment by dpvignesh1997** [comment]
can you share the file @mrdoob .
Thank You

**Comment by tylerlindell** [comment]
I'm having issues with this also

```javascript
var scene=document.querySelector('a-scene').object3D
var loader = new THREE.ObjectLoader();

loader.load(
	// resource URL
	"/model.json",

	// onLoad callback
	// Here the loaded data is assumed to be an object
	function ( obj ) {
		console.debug("Debug", obj) //never called
		// Add the loaded object to the scene
		scene.add( obj );
	},

	// onProgress callback
	function ( xhr ) {
		console.log( (xhr.loaded / xhr.total * 100) + '% loaded' ); //this works
	},

	// onError callback
	function ( err ) {
		console.error( 'An error happened' );
	}
);
```
