### ISSUE TITLE
Object3D.worldToLocal

### ISSUE THREAD

**Issue by mikelhlin** [mrdoob/three.js#11128]
##### Description of the problem 

I needed to call updateMatrixWorld(true) before I get correct values from worldToLocal(v); yet functions such as getWorldPosition() or getWorldQuaternion() calls updateMatrixWorld(true) for you. Is the updateMatrixWorld(true) inadvertently left out of worldToLocal() or is it by design? 

##### Three.js version

- [ ] Dev
- [x ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
GitHub issues are for reporting bugs or reporting features. Please, consider using https://discourse.threejs.org/ instead.
