### ISSUE TITLE
Share buffer attributes between vertices in THREE.BufferAttribute

### ISSUE THREAD

**Issue by jodigiordano** [mrdoob/three.js#11131]
Maybe I missed it in the documentation.

Here is how I work with `THREE.BufferAttribute` right now:

    const data = [0, 0, 0, 1, 1, 1]
    const geometry = new THREE.BufferGeometry()
    geometry.addAttribute('data', new THREE.BufferAttribute(data, 1))

This code will send `0` to the first 3 vertices in the vertex shader, then `1` to the next 3 ones.

Here is what I would like to do:

    const data = [0, 1]
    const geometry = new THREE.BufferGeometry()
    geometry.addAttribute('data', new THREE.BufferAttribute(data, 1, 3))

So, _somehow_, I would like a more compact `data` array and a third `THREE.BufferAttribute` parameter to interpret this data like so:

    Each value in "data" is a 1-tuple for 3 vertices

My use case is working with 30k+ quads, where each quad is 6 vertices (non-indexed), and where some information is the same for the entire quad (ex: normals). With this feature, I would save 6 times the memory needed and some CPU cycles, unless I'm missing some insight on how things are handled internally in THREE.js.

**Comment by Mugen87** [comment]
This kind of special buffer layout is not supported by `three.js`. I assume you have to enhance `three.js` in various ways to get things working (e.g. custom `Geometry` and `Attribute` prototypes).

Besides, i've never seen a similar approach like that. It's maybe better to stick at a standard geometry representation in order to keep things more simple.

**Comment by Mugen87** [comment]
Closing, since this is neither a bug nor a feature request. Try to google after "geometry compression". Maybe you find an appropriate algorithm/technique for your use case.
