### ISSUE TITLE
Handle non-affine transforms correctly

### ISSUE THREAD

**Issue by yousefamar** [mrdoob/three.js#11148]
On @Mugen87's recommendation, I've opened a new issue. Please see #684 for details; nothing has changed. Live demo here: http://codepen.io/Paraknight/pen/ZedPNO?editors=0010

**Comment by Mugen87** [comment]
I think we should basically determine, if it we want to support non-affine transformation. AFAIK some 3D libraries explicitly support only affine transformations.

@WestLangley What do you think about this? Maybe it would be enough to just update the docs?

**Comment by WestLangley** [comment]
>Handle non-affine transforms correctly

@yousefamar Where is the non-affine transformation in your pen? Can you please explain what you think should be implemented differently?

>I think we should basically determine if it we want to support non-affine transformations.

@Mugen87 Can you please explain what you mean by that?

**Comment by Mugen87** [comment]
I've meant something like that https://www.google.com/patents/US5175808, so some kind of (image) warping mechanism.

**Comment by pailhead** [comment]
The pen doesn't seem to work.

**Comment by Mugen87** [comment]
If @yousefamar won't respond, i think it's better to close this issue. As soon as there are specific change requests, we can reopen it.

**Comment by yousefamar** [comment]
Apologies to keeping you waiting; I can investigate further during the weekend at best.

> The pen doesn't seem to work.

Does anybody else have issues with it? It works on all my devices. Any particular errors, @pailhead? The point of that pen is just a minimal working example to illustrate the issue. You can recreate it by just creating a textured quad that looks like the one depicted in #684.

It could also be that the texture isn't loading because of the weird cross-origin hacks I had to do. If you take that code out of CodePen into a little file and use a local texture, that should solve things in that case.

> @yousefamar Where is the non-affine transformation in your pen? Can you please explain what you think should be implemented differently?

Just to make sure we're seeing the same thing, is this what you see?

![dwtr7te](https://cloud.githubusercontent.com/assets/999235/25003504/01d8ab12-2050-11e7-9482-6a43a8a93dd5.png)

Is this not literally what is described in #684? I can't claim to know a lot about how things work in the background beyond what I've read, or if this is "expected" behaviour, but what I would expect to see would be the texture transformed correctly like in #684.

A superficial search yields [pointers](http://stackoverflow.com/questions/12414708/correct-glsl-affine-texture-mapping) to the "Q texture coordinate solution" which @mrdoob linked but is now dead. According to the the [cached page](https://web.archive.org/web/20160511083736/http://home.xyzw.us/~cass/qcoord/), there's an implementation of this somewhere, where "instead of specifying the texture coordinates for the upper vertices as (s,t) coordinates of (0, 1) and (1, 1), we can specify them as (s,t,r,q) coordinates of (0, width, 0, width) and (width, width, 0, width)", i.e. you can make OpenGL project the texture properly.

I don't know if this is something Three.js should do or it should be left to developers to sort out (as @Mugen87 said), and in the latter case, feel free to #wontfix and close this issue if you reach that consensus as maintainers.

I should also mention that I only raised this issue out of principle — I haven't used Three.js in years, so if you deem it unimportant, then I'm perfectly ok with a "this is not something we want to support" and that would give me the closure that letting an issue age out wouldn't.

In that case, a message to future googlers: you can work around this and approximate a non-affine transform by adding more faces; just map the texture over more detailed geometry until the trade-off between quality and performance is satisfactory.

**Comment by pailhead** [comment]
Definitely did not see this :). Only got a black screen. My understanding of this problem is that it just works like that, tesselating the faces helps like you said.

**Comment by Mugen87** [comment]
As @pailhead highlighted, there is a pragmatic and easy approach so solve this problem without changing the library. Besides, i think this use case feels rather specific and should preferably handled at user level.

**Comment by mrdoob** [comment]
A couple of articles on the subject:
http://reedbeta.com/blog/quadrilateral-interpolation-part-1/
http://reedbeta.com/blog/quadrilateral-interpolation-part-2/

**Comment by mrdoob** [comment]
However, these articles are only relevant when using quads, which we don't.
