### ISSUE TITLE
Samsung Tab S3 precisions issues with lights on Standard material

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#11142]
##### Description of the problem 

This is not a Three.JS bug but rather an issue on a mobile device dealing with I suspect precision issues.

This scene looks beautiful on most devices:

https://threejs.org/examples/#webgl_lights_physical

But on the new Samsung Tab S3 it has lots of artifacts that seem to be based on the light + surface position + surface normal.  Probably an issue in the specular BRDF:

![screenshot_20170407-115157](https://cloud.githubusercontent.com/assets/588541/24808841/7010b026-1b8b-11e7-83ab-e5e055f40327.png)

Specifically this grid pattern here that shifts with the light as it animates up and down:

![image](https://cloud.githubusercontent.com/assets/588541/24808861/83faf54c-1b8b-11e7-89e5-1b13dd0f3f48.png)

##### Three.js version

- [x] Dev

##### Browser

- [x] Chrome
- [x] Firefox

##### OS

- [x] Android

##### Hardware Requirements (graphics card, VR Device, ...)

- [x] Samsung Tab S3: http://www.gsmarena.com/samsung_galaxy_tab_s3_9_7-8554.php

**Comment by mrdoob** [comment]
@kenrussell have you guys received reports for this device?

**Comment by bhouston** [comment]
@kenrussell, there are a lot of issues on this device.  Chrome crashes a lot in ways that it doesn't on other devices.

Also Firefox renders stuff like this (but Chrome doesn't):

![screenshot_20170406-090832 1](https://cloud.githubusercontent.com/assets/588541/24812949/1c9be7f8-1b9a-11e7-94c3-e2c5a6fd46a5.png)

**Comment by bhouston** [comment]
The weirdest thing about this device is that it has the same GPU as the Google Pixel and OnePlus and S7 and they all work.  So it has to be driver issues or some slight GPU silicon customizations?

**Comment by kenrussell** [comment]
If you have reproducible failures and in particular crashes with Chrome then please file bugs on crbug.com/ . Include crash IDs from about:crashes, and about:gpu.

If you are seeing rendering issues on this device please try to help us by minimizing the shaders that are failing. It's only by that path, and adding the reduced shaders to the conformance suite, that we have leverage to get Samsung or Qualcomm to fix the (likely driver) bugs.
