### ISSUE TITLE
Non-indexed BufferGeometry with MultiMaterial

### ISSUE THREAD

**Issue by vladvlvl** [mrdoob/three.js#11140]
##### Description of the problem 

The problem is in geometry.fromBufferGeometry method. If BufferGeometry is non-indexed it is impossible to use MultiMaterial. Because material index of group is taken into account only if BufferGeometry has index. 
https://github.com/mrdoob/three.js/blob/master/src/core/Geometry.js#L326
But it is not always the case. For example, BufferGeometry loaded from .OBJ file is non-indexed but has groups.

##### Three.js version

- [ ] Dev
- [ ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I wonder if there was a special reason for not supporting groups in context of non-indexed `BufferGeometry` in `.fromBufferGeometry()`...

**Comment by Mugen87** [comment]
see #7917
