### ISSUE TITLE
onBeforeRender callbacks executed when not required

### ISSUE THREAD

**Issue by aardgoose** [mrdoob/three.js#11145]
##### Description of the problem 

The change 8c72ccc75a23752d9a89704038ed8fe1d91244c0 moving the layer visibility test into renderObject() has created an  issue where an Object3D.onBeforeRender() callback is called even when the object will not be rendered (the layers test, now in renderObject(), fails).

In my case this callback fails where I am carrying out a render pass to a texture with an override material and the callback is expecting a different material.

##### Three.js version

- [X] Dev
- [ ] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Any

**Comment by pailhead** [comment]
Any chance you could make a fiddle?

**Comment by mrdoob** [comment]
Hmm, that is tricky... The reason I moved it there was to avoid doing 2 projectObject() when in VR...

I think I understand your use case, but a jsfiddle would be super helpful.

**Comment by aardgoose** [comment]
I'll have a look time permitting...

**Comment by aardgoose** [comment]
OK, the movement of layer tests has also broken layers for use with Sprites() completely.

**Comment by mrdoob** [comment]
I guess I'll have to revert...

**Comment by pailhead** [comment]
How can we untangle the `onBeforeRender` feature and prevent stuff like this from happening? It seems like it's pretty brittle, but it also seems like patterns have been devised around it, so it's useful? There are a few issues like this that are kinda hard to consolidate given how big the renderer is.

**Comment by mrdoob** [comment]
Reverted: https://github.com/mrdoob/three.js/commit/fb14834c5bad806db056010d76106d3103394777
