### ISSUE TITLE
the uv offesets of the displacement map are not taken into account

### ISSUE THREAD

**Issue by Horsetopus** [mrdoob/three.js#11156]
##### Description of the problem 

Short version: the uv offesets of the displacement map are not taken into account when doing the dispalcement.
The issue is described in more details [here](https://discourse.threejs.org/t/update-displacement-map/146/5) but it was not very clear so here is [a dead simple sample](https://jsfiddle.net/Horsetopus/7jf70a7d/)
I use the same map as color and displacement, to affect the black flat mesh
The color moves properly ( the white spot moving clockwise ) but not the displacement ( witch remains in the middle ).

The [fix proposed by looeee in the post](https://discourse.threejs.org/t/update-displacement-map/146/5?u=horsetopus) works fine.

- [x] r84
- [x] All of them
- [x] All of them

**Comment by jostschmithals** [comment]
https://github.com/mrdoob/three.js/issues/7826
