### ISSUE TITLE
three.js 3MF sample is broken

### ISSUE THREAD

**Issue by rogersachan** [mrdoob/three.js#11155]
##### Description of the problem 

Viewing https://threejs.org/examples/webgl_loader_3mf.html shows nothing, but https://technohippy.github.io/3MFLoader/app/index.html works. What happened?

Support for 3mf is especially important since Microsoft's Paint3D primarily saves/exports/uploads (to Remix3D) in 3MF.

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

* Any

**Comment by jostschmithals** [comment]
In the dev branch it is working:

![3mf](https://cloud.githubusercontent.com/assets/5700294/24840677/8779e5ce-1d71-11e7-9e61-1553655454aa.JPG)

**Comment by rogersachan** [comment]
Does this mean it will be fully working in the next version?

**Comment by jostschmithals** [comment]
I don't know any details, but it seems that recently there was a bugfix:
https://twitter.com/mrdoob/status/822202673600544772
https://github.com/mrdoob/three.js/pull/10753

**Comment by Mugen87** [comment]
Fixed in `dev`. 

> Does this mean it will be fully working in the next version?

Yes.
