### ISSUE TITLE
scene.background may be clipped by the camera.

### ISSUE THREAD

**Issue by AsAddict** [mrdoob/three.js#11176]
the problem happens when the near of the camera exceeds 2.5 in the scene (because the rendering of the skybox is based on the camera's projection matrix). and the skybox is defined by the cubeBufferGeometry whose width equals 5.0 in WebGLRenderer.

**Comment by AsAddict** [comment]
Maybe:
gl_Position = modelView * position;
gl_Position.z = gl_Position.w -0.00001; // force to far plane.

**Comment by Mugen87** [comment]
Closing. We can reopen the issue if the bug is demonstrated with a [live example](https://jsfiddle.net/f2Lommf5/).

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/9ee6c4034b03f3f8f635344e33ab997c7ecd0648 fixed this issue.
