### ISSUE TITLE
Exporting with STLBinaryExport is not numerically robust 

### ISSUE THREAD

**Issue by neural99** [mrdoob/three.js#11173]
The STL file format requires that the face normals are given both as vertex ordering and explicit as three float values. One would expect that calculating the normals with _computeFaceNormals_ and then exporting would result in correct STL files.

However, the calculations in _computeFaceNormals_ are done based on the 64-bit float vertex data. These computed normals are then casted to 32-bit floats. Similarly the vertex data is casted to 32-bit floats. A recalculation of the normal from the 32-bit vertex data might not agree with previous calculations. This results in the exported STL data beeing unvalid. 

STLBinaryExport should enforce that the data outputted follows the specification of the STL format. Hence, it should compute face normals from the casted vertex data and not care about the normal properties of the geometry.

**Comment by kintel** [comment]
In my experience, STL normals are output in different way depending on the exporting apps. If an importing app want the vertex normals to always be per-face 32-bit normals based off the 32-bit vertex coordinates, it's a lot safer to simply calculate them on import.

Sounds like a pretty minor issue to me, but probably a good task to take on as a new developer.

**Comment by neural99** [comment]
It is true that there is no formal specification and that different implementations differs in this regard. However, I think this issue is particular to this implementation and a direct consequence of Javascripts 64-bit floating points numbers (and no 32-bit floats). 

I suggests that the normals should be calculated to from the 32-bit output values when exporting. Do you agree?

**Comment by pailhead** [comment]
The point of three is to be extendible. Seems very trivial to implement this functionality on top of three. IMHO, face derived normals are never needed in any file format for transfer. Explicit vertex normals are a different beast.
