### ISSUE TITLE
Should Point Shadows Use Cubemaps?

### ISSUE THREAD

**Issue by jaxry** [mrdoob/three.js#11189]
##### Description of the problem 
Point light shadows require an omnidirectional shadow map created by rendering a scene from all six positive and negative orthogonal directions from the light source. Typically a cubemap is used to store the resulting depth map. However, Three.js does not use a cubemap but instead uses a 2D texture which I find unusual.

https://github.com/mrdoob/three.js/blob/r84/src/renderers/webgl/WebGLShadowMap.js#L144-L179
Each direction is rendered onto a corresponding subregion of a 2D texture. 

https://github.com/mrdoob/three.js/blob/r84/src/renderers/shaders/ShaderChunk/shadowmap_pars_fragment.glsl#L148-L200
Then the texture is sampled in the fragment shader by remapping cubemap coordinates to this 2D layout.

Why are omnidirectional shadow maps rendered to a 2D texture rather than to a cubemap? Is there an advantage to using "virtual" 2D cubemaps like this versus using hardware cubemaps?

If this is still an open issue, here are some problems with using a 2D texture that a cubemap would solve:
* The subregions rendered don't completely map onto the 2D texture, leaving two square regions each the resolution of a cube face that waste memory.
* Combining six cube face textures into one 2D texture means that each face's max resolution can only be 1/4th the max texture resolution supported by WebGL.
* Unnecessary computations. The `cube2uv` function in the fragment shader would not be needed if cubemaps were used.

If we'd like to revisit the way shadow mapping is done, Gerasimov provides some implementation details of cubemap-based shadow mapping [here](http://http.developer.nvidia.com/GPUGems/gpugems_ch12.html).

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

**Comment by mrdoob** [comment]
I don't remember... @mkkellogg or @tschw probably do.

**Comment by mrdoob** [comment]
Relevant PR: #7153

**Comment by tschw** [comment]
The original implementation used cube samplers. Using 2D samplers instead solved portability issues, or maybe we did it, because it was less architecturally obstrusive to use a 2D sampler array (allowing simpler code on the JS end) - I don't quite recall. However, it's all been discussed in that PR and you can read it up if you have to know.

The "problems" you state are actually based on assumptions about how OpenGL is implemented and there is no such mandate in the specification: In fact, everything considered, you get no higher resolution limit in practice (see webglstats.com), which hints into the direction that cube maps are almost always driver code rather than hardware. When teaching the limited bare ES 2 cube map samplers to do seamless filtering, the "userland implementation" may actually even become cheaper.

**Comment by jaxry** [comment]
Thanks for the input. It's good to know this issue has already been considered. I know I'm nitpicking at small implementation details but I'm new to graphics programming so this is a learning experience for me. I'm happy to close this issue if you feel this isn't a problem.

I was under the impression that nearly every WebGL implementation properly filters along cubemap seams. But is this not true? If seams were visible due to improper filtering, then cubemaps would be entirely ineffective for environment mapping too. But three.js currently uses cubemaps for environment mapping without issues, at least for my device.

You mention texture2Ds are used for portability issues, but textureCubes are part of the base spec and should be supported by every device. Reading over the comments in the initial pull request, I couldn't find any more detail why texture2Ds are favored over textureCubes. I apologize if I missed the relevant comment. 

As for the max texture resolution, webglstats indicates that values supported for MAX_CUBE_MAP_TEXTURE_SIZE (which is per face) and MAX_TEXTURE_SIZE are nearly equal, meaning that using a cubemap versus a packed 2D texture does give you 4 times the max resolution.

You hinted that whether or not the empty regions in the 2D texture waste space is dependent on WebGL's implementation. We would have to measure memory usage to be certain, but I don't see how WebGL would be able to optimize such a thing. If you allocate a texture of a certain size, then I'd just expect WebGL to locate that amount of space, regardless if a subregion of that texture data is empty.

In any case, my concern largely comes from the fact that I have not found any articles or books which suggest using a 2D "virtual" cubemap over a proper cubemap. Do you know of another source that covers this topic?

**Comment by mrdoob** [comment]
@jaxry do you think you could give a go at implementing the cubemap approach and see if there are any benefits?

**Comment by mrdoob** [comment]
@jaxry any luck?

**Comment by jaxry** [comment]
@mrdoob I haven't implemented the cubemap approach and probably won't in the future.

**Comment by dbechrd** [comment]
Possibly relevant: https://www.gamedev.net/forums/topic/657968-filtering-cubemaps/?tab=comments#comment-5162187
