### ISSUE TITLE
Node could not compile three.js-editor javascript that I created

### ISSUE THREAD

**Issue by hasanbaghal** [mrdoob/three.js#11184]
Hi,
My question is at this link
 
https://stackoverflow.com/questions/43434694/node-could-not-compile-three-js-editor-javascript-that-i-created

so,I really want to have a index,js file instead of index.html file,because I want to develop that with my other js files.

thanks for your help
best reagrds

**Comment by Mugen87** [comment]
Solved with #11178

**Comment by hasanbaghal** [comment]
hi,Thanks,would you please send me an **example link** about :

Solved with #11178. Please fetch the latest  **dev  branch**. Besides, you need to remove all **dependencies** to  js/loaders/deprecated/SceneLoader.js  like  require('./js/loaders/deprecated/SceneLoader.js')  in your code.

I am new to node and javascript
best ragrds
