### ISSUE TITLE
Object3D eventDispatcher of type 'added' is not working

### ISSUE THREAD

**Issue by SepehrV** [mrdoob/three.js#11188]
##### Description of the problem 

Object3D event dispatcher of type "added" does not dispatch when objects are added to it. 
When I manually dispatch such an event the listener receives it but the default dispatcher is not working. The code is clearly there:
https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L322

jsfiddle example at:
http://jsfiddle.net/sepehr_2oo8/akmcv7Lh/119/

An 'added' event listener is attached to the scene. But it is only being called once when I am dispatching the event manually. I was expecting it to be called for each newly added object to the scene. Am I missing something here?

##### Three.js version
r84
##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
The event dispatch is related to the added object, not to the scene itself. I've change the fiddle to illustrate this.

http://jsfiddle.net/akmcv7Lh/121/

**Comment by SepehrV** [comment]
I see. Thanks for the clarification.
