### ISSUE TITLE
Example webgl_gpgpu_protoplanet not working on IE

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#11196]
##### Description of the problem 

As reported by @elmariachigrande on the forum ([here](https://discourse.threejs.org/t/example-webgl-gpgpu-protoplanet-not-working-on-ie/211)), the webgl_gpgpu_protoplanet example is not working on Edge or Internet Explorer. 

I tried opening several times on IE11, it made the browser completely hang each time (no error message, had to use task manager to close it), then it Edge it crashed the tab the first few times, but eventually loaded to show this:

![proto-error](https://cloud.githubusercontent.com/assets/5307958/25178460/199d4f8e-2530-11e7-91ac-a001b2232838.png)

I also tried setting the "preferred graphics processor" to both integrated and dedicated, but it doesn't seem to make a difference.

##### Three.js version

- [x] Dev
- [x] r84

##### Browser

- [ X ] Internet Explorer 11.0.15063.0IC
- [ X] Microsoft Edge 40.15063.0.0

##### OS

- [ X ] Windows 10

##### Hardware Requirements (graphics card, VR Device, ...)

NVIDIA GeForce GTX 970M
Intel HD Graphics 530

**Comment by Mugen87** [comment]
What happens if you set this [line](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_gpgpu_protoplanet.html#L442) to `false`. I don't think this extension is needed in this example.

Sry, i have no Windows OS around, so i need you to test this :blush:

**Comment by looeee** [comment]
No change, unfortunately.

**Comment by Mugen87** [comment]
Um, maybe this PR solves the issue: #10674

**Comment by yomboprime** [comment]
Later this day I'll be able to test in a Windows 8, i hope.

**Comment by yomboprime** [comment]
I don't have access to a Windows machine, sorry. I can't test the bug.

Can somebody else test in IE 11?

**Comment by vchizhov** [comment]
I get the following:
THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.
THREE.WebGLRenderer: OES_texture_half_float extension not supported.
THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.
Other browsers are fine, I don't think it matters but I'm using a r9 290.

**Comment by aardgoose** [comment]
I think this may be IE trying to unroll the nested x, y loops iterating through the textures and running into timeout or complexity issues.

If I run the example with a low number of particles say 4 16 or 64*, it works in IE11 and Edge, although it takes a long while to load with 64. 

When the example fails I get 'internal linking error' reported from gl.linkProgram(). (sometimes the browser just hangs).

It doesn't look like the example is intrinsically faulty, it just hits the limits of MS's shader compiler/linker. Possibly reduce the initial number of particles if IE/Edge is used and limit the maximum/warn for higher numbers.

* I expect of the failure is timeout related, the speed of the user's machine would influence the maximum number of particles supported.

**Comment by aardgoose** [comment]
Can this issue be closed? It's a limitation of Edge/IE WebGL implementation rather than a three.js bug.
 
/ping @mrdoob @looeee
