### ISSUE TITLE
OBJ boole

### ISSUE THREAD

**Issue by alaprajz** [mrdoob/three.js#11199]
How can I cut geometry from geometry in THREE.JS?
How can I cut geometry from groups of geometry?
![kep](https://cloud.githubusercontent.com/assets/9334903/25201113/1092d848-2551-11e7-89ec-3af3df2541ba.png)
regards:
alaprajz

**Comment by WestLangley** [comment]
http://stackoverflow.com/search?q=%5Bthree.js%5D+CSG
