### ISSUE TITLE
Gear VR input not working

### ISSUE THREAD

**Issue by pikilipita** [mrdoob/three.js#11197]
##### Description of the problem 

On the Gear VR oculus app, while in VR mode none of the following events are triggers while touching the headset side button:
mousedown, starttouch, keydown

Those events are triggered as expected while out of the VR mode.

it can be reproduced on this simple example:
http://lune.xyz/tests/vr2/

##### Three.js version

r84

##### Browser

Gear VR oculus new browser

##### OS

Android Gear VR

##### Hardware Requirements (graphics card, VR Device, ...)

Android Gear VR

**Comment by alaprajz** [comment]
internet browser in Oculus: IF samsung, then samsung internet browser -> more (right top corner) ->Labs -> Webvr (turn on switcher here)

**Comment by mkeblx** [comment]
/ping @DigiTec

Oculus in their browser currently do not expose HMD touchpad as touch/mouse events (but do as a gamepad) so this is expected behavior.

**Comment by pikilipita** [comment]
Thanks for the help. 
I found out how to get the buttons states:

var gamepads = navigator.getGamepads && navigator.getGamepads();

if (!gamepads)return;

var isPressed = gamepads[0].buttons[0].pressed;
