### ISSUE TITLE
Parallax Mapping and Lights

### ISSUE THREAD

**Issue by parallaxas** [mrdoob/three.js#11194]
Hello 
i'm experimenting around with three js (r84) and found an example about parallax mapping in the examples and also in #5388. The parallax example works very well. But when i try to add some lights it doesn't work. The scene seams to be black. I created the following code, maybe i miss something?:

```js
var shader = THREE.ParallaxShader;
var uniforms = THREE.UniformsUtils.clone(shader.uniforms);
var parameters = {
				    fragmentShader: shader.fragmentShader,
				    vertexShader: shader.vertexShader,
				    uniforms: THREE.UniformsUtils.merge([
                                                    THREE.UniformsLib["lights"],
                                                    { diffuse: { type: 'c', value: new THREE.Color(0xff00ff) } },
                                                    uniforms
				    ])
				};
				
var textureLoader = new THREE.TextureLoader();
material = new THREE.ShaderMaterial(parameters);
material.map = textureLoader.load('m.png');
material.bumpMap = textureLoader.load('b.png');
material.map.anisotropy = 4;
material.bumpMap.anisotropy = 4;
material.lights = true;
uniforms['map'].value = material.map;
uniforms['bumpMap'].value = material.bumpMap;

material.uniforms;
material.uniforms['parallaxScale'].value = -100.0 * 0.001;
material.uniforms['parallaxMinLayers'].value = 17.0;
material.uniforms['parallaxMaxLayers'].value = 20.0;
material.defines = {};
material.defines[THREE.ParallaxShader.modes.relief] = '';
material.needsUpdate = true;
```

After the definition the material is added to a plane. Is there any way to enable lighting with parallax mapping? The lights already working when i use it with basic material.

**Comment by Mugen87** [comment]
The `ParallaxShader` code does not consider any lights. That's one reason why this (experimental) functionality is only part of the examples and not of the core. If your material should react on lights, you have to enhance the code or use a material of the core (e.g. `MeshPongMaterial`) with just a bump or normal map instead.

**Comment by parallax4u** [comment]
Ok thank you for this information. What do you mean by enhance the code, what options do i have? Yes MeshPongMaterial with bump and normal map will work, but the 3D effect with parallax is much better :-) If i could do it by enhancing the code i will try.

**Comment by Mugen87** [comment]
> What do you mean by enhance the code, what options do i have?

I think you have to change the shader code in [examples/js/shaders/ParallaxShader.js](https://github.com/mrdoob/three.js/blob/dev/examples/js/shaders/ParallaxShader.js) so light information are processed correctly. Do support this task, you should reuse some shader chunks from `three.js` internal shader lib e.g. [lights_template.glsl](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/lights_template.glsl). Unfortunately i've never worked with this code so i'm not a big help here.

**Comment by parallaxas** [comment]
I tried to integrate the fragment of the lights_template.glsl into the fragmentShader of the ParallaxShader.js. But i have the problem that the definition of the function "RE_Direct" is missing, but i can't find the definition anywhere...

**Comment by Mugen87** [comment]
Have a look at this code. Maybe you can reuse this chunk in your application.

https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/lights_phong_pars_fragment.glsl#L75-L77

**Comment by parallaxas** [comment]
I will try this fragment.

While searching around the internet i found the following interessting article about parallax mapping and lighting and selfshadowing: 

http://sunandblackcat.com/tipFullView.php?topicid=28

But it is GLSL version 3.3... Currently three.js supports GLSL 1.0, right? But maybe it's easier to integrate in WebGL2 with GLSL 3.0, if three.js will support it in the future?

**Comment by jaxry** [comment]
Is parallax mapping useful or important enough to consider adding to the core materials in Three.js? If it is worth considering, I can start the process by submitting a preliminary pull request with the feature integrated.

**Comment by WestLangley** [comment]
IMHO, no. However, do you feel you can improve the example? That could be very illustrative.

**Comment by jaxry** [comment]
The ParallaxShader example does not work with lights so its use is limited. I meant to suggest the possibility of adding a parallax map fragment to `MeshPhongMaterial` and `MeshPhysicalmaterial` so that the mapping is integrated with lighting and the current current mapping techniques.
