### ISSUE TITLE
InstancedBufferGeometry draws all regardless maxInstancedCount

### ISSUE THREAD

**Issue by Mevedia** [mrdoob/three.js#11209]
I always wondered when there are left over instances when updating the maxInstancedCount, when i filled the buffer for position+scale so the scale isn't zero i noticed it draws all.

It's in WebGLBufferRenderer.js this line, no issues there.
`gl.drawArraysInstanced( mode, 0, count, geometry.maxInstancedCount );`

geometry.maxInstancedCount is passed with 1 in my test,, using a buffer for 10k, but all will be drawn. Is it required to limit the range of the InstancedBufferAttribute? What is the purpose of maxInstancedCount then?

**Yes i needed to set the element count of the InstancedBufferAttribute equal to maxInstancedCount, maybe it should get set by the renderer.**

**Comment by mrdoob** [comment]
How does it work in this example?
https://threejs.org/examples/webgl_buffergeometry_instancing.html

**Comment by lekxi** [comment]
I can't tell, but i should have mentioned that i'm using WebGL2. I'll look into it later again.

**Comment by Mugen87** [comment]
This seems to be a WebGL2 related issue. We are using [drawArraysInstancedANGLE](https://developer.mozilla.org/en-US/docs/Web/API/ANGLE_instanced_arrays/drawArraysInstancedANGLE) and [drawElementsInstancedANGLE](https://developer.mozilla.org/en-US/docs/Web/API/ANGLE_instanced_arrays/drawElementsInstancedANGLE). In both cases `maxInstancedCount` is used as the `primcount` parameter which works as expected.

Closing for now.
