### ISSUE TITLE
Docs pages is broken

### ISSUE THREAD

**Issue by modulesio** [mrdoob/three.js#11204]
Probably due to the new `r85`, but https://threejs.org/docs/ is a bit messed up.

Just wanted to make sure it's on someone's radar 🔍 👍.

<img width="764" alt="capture4" src="https://cloud.githubusercontent.com/assets/6926057/25260445/392a3fa2-261a-11e7-86f7-c4ce6067cd78.PNG">

**Comment by modulesio** [comment]
(Works now)

So closing!

**Comment by mrdoob** [comment]
Yep. I noticed that too... Reload reload! 😅

**Comment by jostschmithals** [comment]
Am I right that this problem did only occur, if someone had the docs opened in the moment of update (r84 -> r85)?

**Comment by mrdoob** [comment]
I think it's a problem if files.json being cached.

**Comment by jostschmithals** [comment]
I had no problems in spite of caching.

**Comment by Mugen87** [comment]
I've noticed right now that scrolling inside the menu is not possible from a smartphone. So you have no change to click on links further down the menu. You can emulate this behavior if you minify your browser window until the layout switches to mobile view.

![image](https://cloud.githubusercontent.com/assets/12612165/25269756/48dd8526-267e-11e7-87fb-e539ab7d6557.png)

**Comment by jostschmithals** [comment]
That's indeed bad. I will make a PR to fix this.
