### ISSUE TITLE
OutlinePass doesn't work with pixel ratio 2

### ISSUE THREAD

**Issue by jack-jun** [mrdoob/three.js#11205]
In the outline pass example, the pixel ratio is set to 1.
https://github.com/mrdoob/three.js/blob/master/examples/webgl_postprocessing_outline.html#L161

The scene is fuzzy and if we comment the line and use the device's pixel ratio, the scene is squeezed to the left bottom corner as the following screenshot:
![image](https://cloud.githubusercontent.com/assets/5774080/25269623/12b03e30-26b0-11e7-9774-dfb359e91961.png)

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by spidersharma03** [comment]
I will take a look

**Comment by proteamer** [comment]
It's look like EffectComposer doesn't handle `pixelRatio` which set in `WebGLRenderer` when creates [WebGLRenderTarget](https://github.com/mrdoob/three.js/blob/master/examples/js/postprocessing/EffectComposer.js#L17-L18).

I suggest to use next workaround: 

1. Create custom set size handler for `effectFXAA`: 
``` js
effectFXAA.setSize = function(width, height) {
    this.uniforms.resolution.value.set(1 / width, 1 / height);
};
```
2. Call `composer.setSize` with premultiplied `width` and `height` during initialization and window resizing:
``` js
var size = renderer.getSize();
var pixelRatio = renderer.getPixelRatio();
composer.setSize(width * pixelRatio, height * pixelRatio);
```

**Comment by jack-jun** [comment]
@proteamer It works!!  Thank you.
