### ISSUE TITLE
WebVR Rollercoaster going wrong direction in VR

### ISSUE THREAD

**Issue by mkeblx** [mrdoob/three.js#11214]
On rollercoaster facing backwards, but only when have WebVR flag enabled.
https://threejs.org/examples/webvr_rollercoaster.html

##### Three.js version

- [x] Dev

##### Browser

- [x] VR Browsers: Oculus Browser, Chrome-Android

##### OS

- [x ] Android

**Comment by Mugen87** [comment]
Okay, that was a bit chaotic. But this PR should fix it:#11218
