### ISSUE TITLE
HDR Bloom

### ISSUE THREAD

**Issue by korner-brazers** [mrdoob/three.js#11216]
Hi guys, I know this is not the place for questions, but you as developers know better where from what grows.

I recently posted a question: http://stackoverflow.com/questions/43544976/three-js-hdr-bloom

Is this possible in theory? Are there any ways?

It comes to mind about creating a new scene and re-rendering the necessary objects, but it seems to me stupid)) it might be better to somehow get the brightness value from all the shaders.

I want to create something like this: http://dt-byte.ru/fc87d432.png
Thank you.

**Comment by looeee** [comment]
@korner-brazers this is not a help site. But feel free to ask your question over on the [forum](https://discourse.threejs.org/).
