### ISSUE TITLE
FBXLoader2.js no animation

### ISSUE THREAD

**Issue by rohalchandrakar2007** [mrdoob/three.js#11227]
[wolf_fbx_mine.fbx.zip](https://github.com/mrdoob/three.js/files/951632/wolf_fbx_mine.fbx.zip)

**PLEASE FIND ATTACHED SCREENSHOT AND FBX FILE**

No visible animations:
showing warnings on browser console:
FBXLoader2.js:638 FBXLoader: Vertex has more than 4 skinning weights assigned to vertex.  Deleting additional weights.

##### Three.js version
- [x] r85

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS
![screen shot 2017-04-24 at 5 31 02 pm](https://cloud.githubusercontent.com/assets/5187994/25336231/2b611290-2914-11e7-9b22-b47ec5c4f120.png)

**Comment by yazancash** [comment]
as i know, in FBX format, there is no way to set maximum skinning weights to be assigned per vertex, so i think this limit is from FBXLoader.
anyway i have imported & re-exported your model here:
https://www.dropbox.com/s/jlw9hmml85z180w/wolf_fbx_mine2.zip?dl=0
you can test to see if problem is in model or FBXloader.

**Comment by rohalchandrakar2007** [comment]
Not able to download model from dropbox link.
Also i have tested multiple fbx models with animations none of them worked for me.
Only the model provided with threejs examples works.
Is there any way to test animations in threejs Editor?

**Comment by yazancash** [comment]
i wonder why model file takes longer time to upload. however
as i know, JSON editor does not support Animations, but i wonder what (Play) button do. (*for my models, also it does not show animations)
if you need more flexible format for animated models, i suggest to re-write your models to be in JSON format.
this what im doing after trying for a while with FBX and other loaders.

**Comment by rohalchandrakar2007** [comment]
I am trying to build fbx viewer demo.
Is there any alternate way to show fbx animations.

**Comment by yazancash** [comment]
maybe this helps:
https://www.dropbox.com/s/pwa31xkia8tg8v9/fbx%20threejs.zip?dl=0
you have to edit some codes, example Animation sets to play.

**Comment by rohalchandrakar2007** [comment]
Again your model is working fine.But same warning in case of my model.
can you try placing my model?   "wolf_fbx_mine.fbx.zip"

**Comment by yazancash** [comment]
on FBX Player example i gave above, i tried to run your original model, it does not work.
only after i import then re-export, it works correctly fine with animation. (i think your model has 5 animations, the first one running by default)
here screenshot. (there is no textures because i do not have the images)
https://postimg.org/image/5fp5gce8l/

**Comment by rohalchandrakar2007** [comment]
what tool you are using to re-export the models?

**Comment by yazancash** [comment]
Ultimate Unwrap 3D, contact me for license (yazancash@gmail.com)

**Comment by rohalchandrakar2007** [comment]
ok, 
Thanks

**Comment by Mugen87** [comment]
@rohalchandrakar2007 Is your problem solved? Or is this issue some kind of an enhancement request?

**Comment by rohalchandrakar2007** [comment]
not solved as FBXLoader has some issue with loading some fbx files.

**Comment by Mugen87** [comment]
Can you please briefly sum up what kind of problems `FBXLoader ` has (besides the skinning weights limitation) ? This will make it easier to start solving these issues.

**Comment by rohalchandrakar2007** [comment]
In my case that is the only problem.Dose it supports multiple animations?Can you solve that skinning weights issue?

**Comment by Mugen87** [comment]
That's not a limitation of `FBXLoader2` but of `three.js` in general, see

https://threejs.org/docs/index.html#api/core/Geometry.skinWeights

**Comment by rohalchandrakar2007** [comment]
On loading fbx file I get the message "deleting additional weights", but after that also animations are not proper.Should I pre process fbx files to remove additional weights? Or you can suggest any other way to play animations properly.

**Comment by Mugen87** [comment]
Good questions 😉 ! I think i would ensure that my content creation or modeling tool already exports the data in the right fashion. See https://blender.stackexchange.com/questions/14250/how-to-restrict-vertex-weights-to-no-more-than-n-number-of-bones

**Comment by rohalchandrakar2007** [comment]
I would go for pre-processing the file as I am trying to create fbx viewer.   :D

**Comment by Mugen87** [comment]
> I would go for pre-processing the file as I am trying to create fbx viewer. :D

I hope you don't mind when i close the issue. If you need help for your mentioned task or if you want to discuss your approach in general, please use [stackoverflow](http://stackoverflow.com/questions/tagged/three.js) or the [three.js forum](https://discourse.threejs.org/).

**Comment by rohalchandrakar2007** [comment]
Thank for all the help and quick reply...
