### ISSUE TITLE
FBXLoader2.js parse skeleton error

### ISSUE THREAD

**Issue by rohalchandrakar2007** [mrdoob/three.js#11224]
Not able to load fbx file.Getting console error 
"Uncaught TypeError: Cannot read property 'properties' of undefined"
in file FBXLoader2.js
line: 456 

##### Three.js version
r84

##### Browser
- [x] All of them

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Can you share the fbx file?

**Comment by rohalchandrakar2007** [comment]
[Spider_2.fbx.zip](https://github.com/mrdoob/three.js/files/950577/Spider_2.fbx.zip)




**# Missing Indexes and Weights data i think.**
Sample Deformer node in file:
Deformer: 4306413712, "SubDeformer::Body2", "Cluster" {
		Version: 100
		UserData: "", ""
		Transform: *16 {
			a: -0.999999999999806,6.19754814578925e-07,-5.06636987342628e-07,0,-6.19753631795702e-07,-0.999999582767283,-2.99078943118677e-06,0,-5.06639535456166e-07,-2.99079161290008e-06,0.999998509881869,0,4.16214017996244e-06,-0.912092149258087,-1.95026622031522,1
		} 
		TransformLink: *16 {
			a: -20,-1.01327914350323e-05,1.23950721899746e-05,0,1.23951084054879e-05,-5.98159007253794e-05,20.0000095367108,0,-1.01327688589458e-05,20.0000286102269,5.98159640501649e-05,0,7.48239399399608e-05,39.0053253173828,17.7575073242188,1
		} 
	}

**Comment by mrdoob** [comment]
Are you using the latest version? I've just dropped the `Spider_2.fbx` in https://threejs.org/editor/ and I got this:

![screen shot 2017-04-23 at 23 55 43](https://cloud.githubusercontent.com/assets/97088/25325464/80fd2886-2880-11e7-890a-acf33142d375.png)

**Comment by rohalchandrakar2007** [comment]
Yes, Its working with r85 virsion.But still there is no animation showing console exception:
"FBXLoader: Vertex has more than 4 skinning weights assigned to vertex.  Deleting additional weights".
![screen shot 2017-04-24 at 12 57 41 pm](https://cloud.githubusercontent.com/assets/5187994/25326394/a642a70c-28ed-11e7-97fd-55e71a71aa5e.png)
