### ISSUE TITLE
Graphical issue with transparency

### ISSUE THREAD

**Issue by mysterty** [mrdoob/three.js#11238]
##### Description of the problem 

Hello,

I have issue with ThreeJs when i try to superimpose a simple transparent scene with a cube onto another canvas. When the canvas and the cube intersect, that generate ugly reverted buggy colors.

Here my example with a 3D cube onto an audio spectrum
http://www.mysterty.com

![capture du 2017-04-25 13-17-51](https://cloud.githubusercontent.com/assets/1776125/25396378/aea9ddd2-29e4-11e7-9a54-8d55be0252a5.png)

##### Three.js version

- [] Master

##### Browser

- [x] Firefox
- [ ] Chrome : doesn't even play

##### OS

- [ ] Linux - Mint 18

**Comment by jostschmithals** [comment]
For me all looks fine in each situation of overlapping, in Chrome, FF and Edge:

![test](https://cloud.githubusercontent.com/assets/5700294/25398264/a2b474a4-29eb-11e7-8a70-f3b564c1a5fb.JPG)

**Comment by mysterty** [comment]
Thx @jostschmithals for your feed back. You are on windows ?
On linux chrome, i have that error :

> THREE.WebGLRenderer: Error creating WebGL context.
> Yd @ three.min.js:158

**Comment by jostschmithals** [comment]
Yes, I tried it on Windows.

**Comment by Mugen87** [comment]
I think this is not a `three.js` issue but a more general problem with your OS (Mint 18) and the corresponding GPU driver. You should check out first if you environment actually supports WebGL. It's strange that Chrome does not even run the example...

**Comment by cesarpachon** [comment]
Hi! I am having a issue that perhaps is related to this one, so I preferred comment here before opening a new one..
I am loading PNG files from external URL, but with one particular PNG, no-power-of-two, alpha-chanel, created with gimp, when I loaded and use as texture in a plane, It renders mixed with what it looks like screenshots portions of the current screen. in the attached screenshot you will see that it looks like if the cat had a layer on top with inverted parts of the chromium developer inspector window, that is opened at the right.
I notice that it says that as the image is not power of two, has to be resized, but I had not noticed that behavior with other textures. 
![chromium_threejs_issue](https://cloud.githubusercontent.com/assets/2874200/25408458/ab44a3cc-29d3-11e7-8844-412d8b09f471.png)
using three.js R77, Chromium Version 57.0.2987.98 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by mysterty** [comment]
thx @Mugen87 
Ok, i checked and effectively, chrome isn't well configured.

Buf firefox should be ok. I will investigate on OS issue and i keep you informed ;)
