### ISSUE TITLE
BoxHelper update() function 

### ISSUE THREAD

**Issue by Onnion19** [mrdoob/three.js#11230]
##### DESCRIPTION
Update() funciton from the boxhelper takes the object to be updated as argument. Otherwise it has no world matrix reference. 
(In docs, https://threejs.org/docs/#api/helpers/BoxHelper.update() , there isn't that argument which makes the function confusing). 

Describe the bug or feature request in detail.  

function should be: 
Initialize: 

`var box  = new THREE.BoxHelper( object ); 
scene.add ( box  );`

On render or loop: 
`box.update( object ); `

You can edit for small-test.  
http://jsfiddle.net/akmcv7Lh/ (current revision)  
http://jsfiddle.net/hw9rcLL8/ (dev)

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
See #11171. Use `box.setFromObject( object );`

**Comment by Mugen87** [comment]
BTW: I can't see in your fiddles the usage of `BoxHelper`,

**Comment by Mugen87** [comment]
> Otherwise it has no world matrix reference.

That's not true (see [here](https://github.com/mrdoob/three.js/blob/dev/src/helpers/BoxHelper.js#L14)). The given object is a property of the helper.
