### ISSUE TITLE
Objects do not render if the scene container is hidden from view when the object is being rendered

### ISSUE THREAD

**Issue by adam-clarey** [mrdoob/three.js#11237]
An odd bug.

I have a multi-step form where tabs are hidden from view (display:none).

In tab 2 the user adds their files, and in the background it renders the objects to be displayed on tab 5, but when you view tab 5, they are blank.

If instead you do not hide the tabs but show them all at the same time and upload the files, the objects render fine as expected.

**Comment by adam-clarey** [comment]
Why was this closed? It's a bug report, not a support request.

**Comment by Mugen87** [comment]
You should post this at stackoverflow first in order to determine if it is actually a three.js issue. This could also be a bug in your application, a genereal WebGL limitation or a problem with your browser.
