### ISSUE TITLE
index or position attributes are mandatory for BufferGeometry

### ISSUE THREAD

**Issue by vchizhov** [mrdoob/three.js#11242]
##### Description of the problem 

Is this intentional(the code's from WebGLRenderer.js the renderBufferDirect function)?:

```
var dataCount = 0;


if ( index !== null ) {

      dataCount = index.count;

} else if ( position !== undefined ) {

     dataCount = position.count;
}
```

When somebody creates a custom BufferGeometry without attributes named position and index, it never gets sent to the vertex shader thanks to this. Wouldn't it be better to have a dataCount field in the BufferGeometry and just add a `else if( geometry.dataCount!==undefined) { dataCount = geometry.dataCount }` in the WebGLRenderer.js? Or just choose whatever attribute's count.

##### Three.js version

r84

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by pailhead** [comment]
https://github.com/mrdoob/three.js/issues/10751
