### ISSUE TITLE
Vector2/3/4 normalize divide by zero

### ISSUE THREAD

**Issue by brianchirls** [mrdoob/three.js#11241]
##### Description of the problem 

As a result of #10849 and 381b95a291845f32f3ccddd0b780a37d43811f55, the `normalize` method on vector objects no longer checks against divide-by-zero. I understand there was some discussion about whether the check for zero/nan/etc. should happen in `divideScalar`, and I can understand why you guys decided to leave it out.

But I think it makes less sense to remove the check for `normalize`, since the divide operation is not directly exposed in that case. Although a normalized zero-length vector is, as far as I can tell, undefined, it is a case that can happen quite often. And this is a pretty significant API change that will require going through a lot of code to manually add back in that check, and it's so far undocumented. It's also something that may not show up immediately in quick tests, since it's a bit of a special case.

I suggest adding back in a divide-by-zero check to `normalize`, but leaving it out of `divideScalar`. If you like, you can add a console warning that the check may be removed in the future. And I think it's significant enough to warrant a hotfix to r85.

At the very least, please update the documentation and release notes for r85.

Thanks

##### Three.js version

- [x] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mattdesl** [comment]
Yup, agreed. Just got hit by this.

For what it's worth, the `isFinite` check (on x, y, z) that used to exist in multiplyScalar was actually crawling to the top of my profiler in some physics/performance-critical code. It makes a lot more sense to me, performance and API wise, just to check against zero in `normalize()` and maybe also similar functions like `setLength` and `clampLength`.

**Comment by WestLangley** [comment]
I am not a fan of returning incorrect answers without warning, but if you feel it is a reasonable trade-off in this case, one option to handling the zero-vector case is:
```
normalize: function () {

	return this.divideScalar( this.length() | 1 );

},
```

**Comment by brianchirls** [comment]
@mattdesl I did notice the discussion on `isFinite` being super slow, and I think checking against zero should be sufficient.

@WestLangley I think that should be a logical "or" (`||`), not a bitwise one, yes? typo?

**Comment by WestLangley** [comment]
@brianchirls Typo fixed. Thanks.

**Comment by mrdoob** [comment]
@WestLangley looks like a fair trade-off to me.

**Comment by WestLangley** [comment]
>but this still fails if the lookAt is along the z axis, with an up vector of 0,0,1.

Right. The logic fails if the user has set `.up` to be the z-axis.

@manthrax Are you setting z-up for a camera -- or for other objects -- in your app? If so, do you mind explaining your use case?

**Comment by manthrax** [comment]
I am setting z-up on my camera and animated characters.

Mostly because I prefer z-up, and also because it simplified some logic in our codebase that integrated with existing floorplan layout tools.. and ammo.js for physics. I think the former could be refactored to be more up-agnostic but I am more nervous about changing the up I'm using in ammo.js. mostly because of a distant hazy memory I have of bullet physics making slight adjustments on the z position of objects to resolve interpenetration, as an institutionalized hack.

z-up also seems like a more natural up than y to me, although I can see a philosophical argument for y-up as well, namely screenspace aligning with untransformed world space.

x-up, however, I feel is an abomination, and should never be discussed. :)

**Comment by manthrax** [comment]
This actually reminds me of something I wanted to ask about... I was thinking of just storing a single global Vector3 as my global up vector, and then just assigning that to each object.. such that setting that single vector would instantly change Up for all instantiated objects... but this also gave me a sort of spidey sense tingle, as perhaps being a bad practice.
What do you think? @WestLangley

**Comment by WestLangley** [comment]
>I am setting z-up on my camera and animated characters.

Do your animated characters use `.up` for anything? Are they calling `lookAt()`?

>I was thinking of just storing a single global Vector3 as my global up vector
That is how it is implemented. You can change it:
```
THREE.Object3D.DefaultUp.set( 0, 0, 1 );
```

**Comment by manthrax** [comment]
Excellent! Thanks :) Hadn't noticed that! Also, was wondering if you had any preference/justification for a specific up axis?

**Comment by WestLangley** [comment]
I have no preference.

Are you able to answer my last question?

**Comment by manthrax** [comment]
No I am not using lookAt directly on my animated characters at present.
However in a different project that does movement along splines for many small static meshes, I use it extensively.

**Comment by manthrax** [comment]
I made a JSFiddle showing some of this new counterintuitive behavior, and also what seems like it might be a bug in DirectionalLightHelper as well...

First I set Object3D.DefaultUp.set(0,0,1)

Then I make a DirectionalLight, and a DirectionalLightHelper moving along the X axis, to eventually line up looking down the Z (DefaultUp) axis.

At the point that it is looking exactly down that axis, the DirectionalLightHelper breaks, and its values are full of NaNs...

Additionally, the DirectionalLightHelper, doesn't seem to be aiming down the correct axis that the light is pointing along...  I animate a cube at the halfway point between light and 0,0,0, to illustrate that point...

and also when the NaN problem kicks in, I check for it, and flash the cube...

Let me know if any of this is unclear...

http://jsfiddle.net/5wgjvLnz/18/

**Comment by WestLangley** [comment]
@manthrax This is getting off-topic. Would you please move your comment to a new post and file a bug report. Thanks.

**Comment by dmmn** [comment]
Just been hit by this as well, are we actually applying @WestLangley fix in the next release?
(we should be using lengthSq instead of length for perfs btw)

Thanks 🙂

**Comment by mrdoob** [comment]
#11253
