### ISSUE TITLE
explicitly upload data to gpu

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#11245]
##### Description of the problem 

I'd like to have more control over when `gl.bufferData` get's called. Currently it's only partially exposed through `WebGLAttributes.update` which manages the internal cache? 

I think it's possible to have some control over this by calling `render()` with rgba mask set to false? 

Would it be helpful to have an explicit method that would call `gl.bufferData` and set up cache correctly, without having to go through `render()`?

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by pailhead** [comment]
Another thing that i was doing with this is discarding the buffer geometry, or using a single instance of it with 2^16 verts, to create gl buffers.

**Comment by Mugen87** [comment]
In the meanwhile, please use [GLBufferAttribute](https://threejs.org/docs/index.html#api/en/core/GLBufferAttribute) for this use case. It allows you to mange `WebGLBuffer`s on application level. 

https://threejs.org/examples/webgl_buffergeometry_glbufferattribute
