### ISSUE TITLE
aoMap appears inverted, for glTF- and Unity-style occlusion maps.

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#11268]
| gltf-viewer + original model | gltf-viewer + inverted occlusion | cx20 viewer + original model |
|---|---|---|
| ![a144f46e-2d28-11e7-958e-bf55fab4fe1a](https://cloud.githubusercontent.com/assets/1848368/25601714/f081e7a0-2ea2-11e7-85a1-4923cd298c17.png)    |  ![a46aa8be-2d28-11e7-9160-932ec31597ef](https://cloud.githubusercontent.com/assets/1848368/25601717/f56ef47e-2ea2-11e7-9b45-1644b83d6854.png)   | ![screen shot 2017-05-01 at 7 16 41 pm](https://cloud.githubusercontent.com/assets/1848368/25601777/43a75f8c-2ea3-11e7-9b3c-7ec9431f8d3c.png) |
| [scene](https://gltf-viewer.donmccurdy.com/) | [scene](https://gltf-viewer.donmccurdy.com/) | [scene](https://cdn.rawgit.com/cx20/gltf-test/5680855f392c403bb293ff3f905fedec8660c4b8/examples/threejs/index.html?category=tutorialModels&model=Corset&scale=1&type=glTF) |
| Occlusion appears inverted. | Occlusion appears correct. | No visible occlusion. |

The source model is [here](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Corset/glTF) (you can download it is as a zip using [gitzip](https://kinolien.github.io/gitzip/)).

With the same model, BabylonJS gives results more like the center image, with less gloss. Sandbox viewer [here](https://sandbox.babylonjs.com/). According to the [glTF spec](https://docs.unity3d.com/Manual/StandardShaderMaterialParameterOcclusionMap.html) and [unity's docs](https://docs.unity3d.com/Manual/StandardShaderMaterialParameterOcclusionMap.html), higher `r` values mean full indirect lighting, so BabylonJS is correct.

In case this is bad setup in my viewer somehow, my [lighting code is here](https://github.com/donmccurdy/three-gltf-viewer/blob/master/Viewer.js#L167-L178). Even with occlusion manually inverted (center image above) the whole model somehow looks too smooth, (more so than @cx20's demo) and I'm not sure why that would be.

As @takahirox pointed out, here is the relevant bit of [shader code](https://github.com/mrdoob/three.js/blob/f3650c387183eba3439dfa9280f6b5d246a589e8/src/renderers/shaders/ShaderChunk/aomap_fragment.glsl#L3-L4).

##### Three.js version

- [x] Dev
- [x] r85
- [x] r84

**Comment by WestLangley** [comment]
`aoMaps` use the 2nd set of UVs.
```glsl
float ambientOcclusion = ( texture2D( aoMap, vUv2 ).r - 1.0 ) * aoMapIntensity + 1.0;
```
Your geometry has only one set. Add another:
```
geometry.addAttribute( 'uv2', new THREE.BufferAttribute( geometry.attributes.uv.array, 2 ) );
```
Also, aoMaps occlude only ambient ( indirect ) light. Your scene has minimal ambient light to occlude. Increase the ambient light to see the occlusion effect.

Also, as I have mentioned before, if you are using `MeshStandardMaterial` or `MeshPhysicalMaterial`, it is wise to add an environment map if `metalness` is non-zero.

The @cx20 viewer should otherwise be fine.

**Comment by donmccurdy** [comment]
Thanks @WestLangley! 

Here's a version of the viewer that automatically copies `uv` to `uv2` and includes GUI controls for lighting and environment maps: https://gltf-viewer-experimental.donmccurdy.com/

Notwithstanding, the `aoMap` still appears inverted to me. Two screenshots in the same lighting:

| original | manually inverted `r` channel |
|-----|-----|
|  ![screen shot 2017-05-01 at 11 07 44 pm](https://cloud.githubusercontent.com/assets/1848368/25605997/afb3d0c8-2ec3-11e7-916d-d73012f2dbf2.png)  |  ![screen shot 2017-05-01 at 11 07 59 pm](https://cloud.githubusercontent.com/assets/1848368/25605995/addc3682-2ec3-11e7-8c2b-e882bf429b08.png)  |

The model is an official glTF 2.0 sample; I'm hoping to identify fixes needed to THREE.GLTF2Loader. Copying UV->UV2 may be one, but there appears to be at least one other problem here.

**Comment by donmccurdy** [comment]
I've updated my viewer to three.js r85 and the latest GLTF2Loader, and everything looks correct when the second set of UVs is present. This update also resolved some issues with roughness/metalness maps not being applied correctly (see: https://github.com/donmccurdy/three-gltf-viewer/issues/9). I will submit a patch to automatically create the second set of UVs for GLTF2Loader where possible, to support the expected occlusionRoughnessMetallic use cases like this.

Thanks for your help WestLangley!
