### ISSUE TITLE
glTF 2.0 SmilingFace model is not displayed

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#11264]
##### Description of the problem 

I am testing glTF 2.0 sample models and Three.js glTF 2.0 Loader.
https://github.com/cx20/gltf-test/tree/2.0#gltf-20-sample-models

However, it seems that SmilingFace is not displayed properly.
https://cdn.rawgit.com/cx20/gltf-test/5680855f392c403bb293ff3f905fedec8660c4b8/examples/threejs/index.html?model=SmilingFace&scale=1.0
![image](https://cloud.githubusercontent.com/assets/1833979/25565573/1277d54e-2e04-11e7-85ed-42fd7ff05ada.png)

SmilingFace.gltf uses the following model:
https://github.com/lasalvavida/glTF-Sample-Models/tree/2.0/2.0/SmilingFace/glTF

I tried r85 but it was the same result.
http://jsfiddle.net/akmcv7Lh/125/

##### Three.js version

- [x] Dev + #11262 
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

ThinkPad X260 + Windows 10 + Intel HD Graphics 520

**Comment by WestLangley** [comment]
The model is using vertex colors, but the vertex colors are black.

Also, `MeshStandardMaterial` is best with an environment map so there is something to reflect -- especially if `metalness` is 1, which it is in your case.

For a quick fix in your demo, set `metalness = 0` and `roughness = 0`.

For a better fix, add an environment map.

**Comment by donmccurdy** [comment]
@cx20 Looks like this model was created with COLLADA2GLTF. As of 1.0 there was an [open bug](https://github.com/KhronosGroup/COLLADA2GLTF/issues/12) where vertex colors were zeroed out, and that's what it looks like here, too. 

Here is a version of this model with vertex colors intact: https://github.com/sbtron/BabylonJS-glTFLoader/commit/630cb88f71bcb1f532731e481471b0392ee82f55

^this works in three.js, although it's not an exact match for the other versions of the same model (the colors are, intentionally I assume, a bit different).

**Comment by takahirox** [comment]
Maybe we should report this issue to the original?

**Comment by donmccurdy** [comment]
Thanks for reporting that, @cx20  — i think this issue can be closed but let's re-open if there are issues with the corrected model.
