### ISSUE TITLE
Latest spec glTF 2.0 Model are not displayed properly

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#11260]
##### Description of the problem 

I am testing glTF 2.0 sample models and Three.js glTF 2.0 Loader.
https://github.com/cx20/gltf-test/tree/2.0#gltf-20-pbr-models

However, it seems that some PBR models are not displayed properly.
https://cdn.rawgit.com/cx20/gltf-test/b6900f6f4d755a71691aaef5a19279da7472b69f/examples/threejs/index.html?category=tutorialModels&model=Corset&scale=1&type=glTF

![image](https://cloud.githubusercontent.com/assets/1833979/25558801/2d3980d0-2d69-11e7-8708-b4d8eef7381e.png)

I think that it was caused by updating to the latest specification about 10 days ago.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Corset

##### Three.js version

- [x] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

ThinkPad X260 + Windows 10 + Intel HD Graphics 520

**Comment by Mugen87** [comment]
Does it work with the `r84` version of `GLTF2Loader`?

**Comment by donmccurdy** [comment]
@Mugen87 GLTF2Loader was not released until r85. A previous version of this model does work with GLTF2Loader, but the models have changed, as the spec is evolving. I can look into that, and update GLTF2Loader accordingly.

**Comment by cx20** [comment]
I tried r85 but it was the same result.
http://jsfiddle.net/akmcv7Lh/124/

**Comment by takahirox** [comment]
Maybe I've figured out.
Texture magFilter, minFilter, wrapS, wrapT default values.

**Comment by takahirox** [comment]
BTW, we might need to support TANGENT attribute?

https://github.com/KhronosGroup/glTF-Sample-Models/blob/b8af7ed10a878fd8112979a54da562b5c0d12aa3/2.0/BoomBox/glTF/BoomBox.gltf#L143

https://github.com/KhronosGroup/glTF/issues/812

**Comment by donmccurdy** [comment]
Another issue I'm seeing on this model (after correcting for the issue @takahirox pointed out) is that occlusion is inverted.

Current:

![screen shot 2017-04-29 at 10 07 20 pm](https://cloud.githubusercontent.com/assets/1848368/25561829/a144f46e-2d28-11e7-958e-bf55fab4fe1a.png)

After inverting the `r` channel of occlusionRoughnessMetalness texture:

![screen shot 2017-04-29 at 10 07 34 pm](https://cloud.githubusercontent.com/assets/1848368/25561831/a46aa8be-2d28-11e7-9160-932ec31597ef.png)

**Comment by takahirox** [comment]
Inverting r channel...?
Model's issue?

**Comment by donmccurdy** [comment]
With the same model, BabylonJS gives the opposite result: https://sandbox.babylonjs.com/

According to the [glTF spec](https://docs.unity3d.com/Manual/StandardShaderMaterialParameterOcclusionMap.html) and [unity's docs](https://docs.unity3d.com/Manual/StandardShaderMaterialParameterOcclusionMap.html), higher `r` values mean full indirect lighting, so BabylonJS is correct.

We've theoretically implemented UE4's version of occlusionRoughnessMetallic, but I can't find docs on how they interpret occlusion. Perhaps UE4 is different than Unity, or perhaps our implementation doesn't quite match UE4 after all. @bhouston, do you know more on this?

**Comment by takahirox** [comment]
So, here may be the code we need to discuss

https://github.com/mrdoob/three.js/blob/f3650c387183eba3439dfa9280f6b5d246a589e8/src/renderers/shaders/ShaderChunk/aomap_fragment.glsl#L3-L4

**Comment by cx20** [comment]
I confirmed that this Issue has been fixed.
https://cdn.rawgit.com/cx20/gltf-test/5680855f392c403bb293ff3f905fedec8660c4b8/examples/threejs/index.html?category=tutorialModels&model=Corset&scale=1&type=glTF
![image](https://cloud.githubusercontent.com/assets/1833979/25565093/bf2e9204-2dfb-11e7-922e-81956b90e642.png)

**Comment by takahirox** [comment]
Maybe we should make another issue for aoMap?

**Comment by bhouston** [comment]
So you are saying the ThreeJS interpretation of AO maps is inverted?

**Comment by donmccurdy** [comment]
@takahirox @bhouston Yeah, I think that either our interpretation is inverted compared to Unity and glTF, or my scene lighting has somehow made it look that way. Filed a new issue: #11268.
