### ISSUE TITLE
Blank canvas in Chrome 58

### ISSUE THREAD

**Issue by kimasendorf** [mrdoob/three.js#11275]
##### Various examples on the website appear just as blank canvas

https://threejs.org/examples/#webgl_animation_cloth
https://threejs.org/examples/#webgl_animation_skinning_morph
https://threejs.org/examples/#webgl_camera
https://threejs.org/examples/#webgl_camera_logarithmicdepthbuffer
https://threejs.org/examples/#webgl_decals

just to name a few..

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS - El Capitan
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Gfx card: ATI Radeon HD 5750 1024 MB

**Comment by kimasendorf** [comment]
`renderer = new THREE.WebGLRenderer( { antialias: true } );` seems to cause the issue. Without `antialias: true` the whiteness disappears.

**Comment by Mugen87** [comment]
see #10747
