### ISSUE TITLE
Error creating WebGL context

### ISSUE THREAD

**Issue by vrbvillor** [mrdoob/three.js#11278]
##### Description of the problem 

F12 shows error THREE.WebGLRenderer: Error creating WebGL context.

##### Three.js version

The Newest version.

##### Browser

Chrome 58.0.3029.81

##### OS

 Windows 10

##### Hardware Requirements (graphics card, VR Device, ...)

The script is the same as the docs of threejs.org, page URL  https://threejs.org/docs/index.html#manual/introduction/Creating-a-scene

IT works in firefox, but not in chrome.  Is the chrome too low??

**Comment by sasha240100** [comment]
Works in `58.0.3029.96`. I confirm.
![image](https://cloud.githubusercontent.com/assets/7657429/25702356/4a159806-30d9-11e7-810a-d4ac6e1da810.png)

@vrbvillor Check if [simple WebGL test](https://get.webgl.org/) will work for you

**Comment by Mugen87** [comment]
@vrbvillor Please post your code in this [fiddle](https://jsfiddle.net/3no4e1wq/1/) for further testing.

**Comment by vrbvillor** [comment]
```
<script src="//github.com/mrdoob/three.js/blob/master/examples/js/Detector.js"></script>
<script>
if (Detector.webgl) {
    init();
    animate();
} else {
    var warning = Detector.getWebGLErrorMessage();
    document.getElementById('container').appendChild(warning);
}	
</script>
```

I use this to check the compatible. But it shows error.

Refused to execute script from 'http://github.com/mrdoob/three.js/blob/master/examples/js/Detector.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
2.html:17 
Uncaught ReferenceError: Detector is not defined  at 2.html:17

**Comment by vrbvillor** [comment]
I add a div with id container, it works.

```
Your graphics card does not seem to support WebGL.
Find out how to get it here.
```

**Comment by Mugen87** [comment]
This doesn't look like a `three.js` issue. Instead, the error seems to be related to your system (OS, GPU...).

**Comment by dummy000** [comment]
var ctx = canvas.getContext('2d');

make sure you are not declaring this..
