### ISSUE TITLE
BufferGeometry with morphAttributes does not create mesh with morphTargetInfluences

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#11277]
If I create a buffer geometry and add a position morph attribute, then create a mesh from it, the mesh doesn't have a morphTargetInfluences property so I can't animate the morph. 

Workaround is to add a fake morphTarget to the geometry:

```js
    bufferGeometry.morphTargets = [];
    bufferGeometry.morphTargets.push( 0 );
```

See this pen:
http://codepen.io/looeee/pen/YVxaKL?editors=0010

**Comment by Mugen87** [comment]
The following version of `Mesh .updateMorphTargets()` should solve the problem. Unfortunately, at least `MMDLoader` won't work with this change. `MMDLoader` assigns to `BufferGeometry` also `.morphTargets` which is actually a property of `Geometry`. I think `MMDLoader` does this because the name of a morph target animation sequence can't be saved in `morphAttributes`. But i'm not 100% sure about this. Didn't have time to debug `MMDLoader` so far. The only thing i can say is that the following examples has problems with this change: https://threejs.org/examples/webgl_loader_mmd_pose.html

```javascript
updateMorphTargets: function () {

		var geometry = this.geometry;

		if ( geometry.isBufferGeometry ) {

			var morphAttributes = geometry.morphAttributes;
			var keys = Object.keys( morphAttributes );

			if ( keys.length > 0 ) {

				var morphAttribute = morphAttributes[ keys[ 0 ] ];

				if ( morphAttribute !== undefined ) {

					this.morphTargetInfluences = [];

					for ( var i = 0, l = morphAttribute.length; i < l; i ++ ) {

						this.morphTargetInfluences.push( 0 );

					}

				}

			}

		} else {

			var morphTargets = geometry.morphTargets;

			if ( morphTargets !== undefined && morphTargets.length > 0 ) {

				this.morphTargetInfluences = [];
				this.morphTargetDictionary = {};

				for ( var m = 0, ml = morphTargets.length; m < ml; m ++ ) {

					this.morphTargetInfluences.push( 0 );
					this.morphTargetDictionary[ morphTargets[ m ].name ] = m;

				}

			}

		}

	},
```

**Comment by looeee** [comment]
It looks to me as if MMDLoader is using a similar hack - it's essentially doing

```js
 bufferGeometry.morphTargets = [];
 bufferGeometry.morphTargets.push( morph.name );
```
https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/MMDLoader.js#L861, where ```params``` is ```morph.name```

The problem (or at least one problem!)  is that these names are then used to create the ```mesh.morphTargetDictionary```, which ```webgl_loader_mmd_pose``` then loops over to create it's morph controls. So you example code above would need to be updated to create the ```mesh.morphTargetDictionary``` as well.

Which would be easily solved if ```BufferAttribute``` had a ```.name``` property, but at the moment it doesn't. Should we add the property?

**Comment by Mugen87** [comment]
> So you example code above would need to be updated to create the mesh.morphTargetDictionary as well.

Correct!

> Which would be easily solved if BufferAttribute had a .name property, but at the moment it doesn't. Should we add the property?

That's a good question. I like the idea because it is backwards compatible and easy to implement.

@mrdoob, @WestLangley What's your opinion about this?

**Comment by Mugen87** [comment]
I've created a PR so we can better see the changes...

**Comment by Mugen87** [comment]
@looeee With the new PR the creation of a morph attribute looks like this:
```javascript
const morphAttribute = new THREE.BufferAttribute( morphPositions, 3 );
morphAttribute.name = 'default';
geometry.morphAttributes.position.push( morphAttribute );
```

**Comment by looeee** [comment]
Sweet! 😁
