### ISSUE TITLE
ColladaLoader typescript definition file is broken

### ISSUE THREAD

**Issue by csuarezgfx** [mrdoob/three.js#11281]
I'm very new to TypeScript but I'm pretty sure the three-colladaloader definition is broken. The actual ColladaLoader has many functions and properties that are not listed in TypeScript definition file. It is not being recognized.

##### Three.js version

- [ ] Dev
- [x] r85.2
- [ ] ...

##### Three-ColladaLoader version
- [x] 0.0.1
##### Browser

- [x] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [X ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> ...are not listed in TypeScript definition file.

Of what file are you talking about? Is it part of the `three.js` repository?

**Comment by csuarezgfx** [comment]
Hi Thanks for the response. It is the TS Definitions file: **/node_modules/@types/three/three-colladaLoader.d.ts**

I got it by: npm install @types/three --save

**Comment by Mugen87** [comment]
Ah okay. Then you have to create an issue at https://github.com/DefinitelyTyped/DefinitelyTyped

`three.js` is not responsible for this code.

**Comment by csuarezgfx** [comment]
oic thanks
