### ISSUE TITLE
Inverting the Y axis?

### ISSUE THREAD

**Issue by Malharhak** [mrdoob/three.js#11286]
##### Description of the problem 

I need to use three.js with the Y axis pointing down instead of up. As far as I have seen, it doesn't seem to be an existing feature. Is it something that could be done? Changing the camera `up` vector would also mean that the `x` direction would change for example, so this is not a viable solution.

I am not sure how axis are handled so I don't know if what I am asking makes sense, but basically in my engine I use pixi.js or three.js depending on situations, and I would like both to have the same Y direction.

**Comment by mrdoob** [comment]
@nlra it's probably going to be easier to invert pixi.js' y axis.
