### ISSUE TITLE
problem with CustomBlending

### ISSUE THREAD

**Issue by Dark-Energy** [mrdoob/three.js#11280]
Function setBlending in `WebGLState` incrorrectly process `customBlending`: 
```
if ( blending !== currentBlending || premultipliedAlpha !== currentPremultipledAlpha ) {

	if ( blending === AdditiveBlending ) { 

	} else if ( blending === SubtractiveBlending ) {

	} else if ( blending === MultiplyBlending ) {

	//need check if CustomBlending given

	} else {

		//set normalBlending every time

	}

}

if ( blending === CustomBlending ) {
```

##### Three.js version

- [x] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
I formatted your post for clarity. Can you please make necessary corrections to your post and provide further detail?

**Comment by Dark-Energy** [comment]
sorry for my poor english, well, i ment this post have  enogh details. this code fragment, which need fix. when i give CustomBlending parameter, this code first set NormalBlending, then do some check: 
		if ( blending === CustomBlending ) {
			if ( blendSrc !== currentBlendSrc || blendDst !== currentBlendDst ...
			{
this may either enable CustomBlending or not enable because some arbitrary conditions. Then normalBlending will be enabled anyway. In my view, need replace last "else" statement with "else if (blending !== customBlending)" in order prevent this.

**Comment by sasha240100** [comment]
@Dark-Energy Why not using `switch/case` syntax?

**Comment by WestLangley** [comment]
> In my view, need replace last "else" statement with "else if (blending !== customBlending)" in order prevent this.

@Dark-Energy So we may better understand, can you please edit your original post and show how you think the code should be written? No code fragments, please.

**Comment by Dark-Energy** [comment]
how can i explain the code shoud be written with no code fragments?
i have written particle demo with customBlending and discover that my blending mode had been ignored. i began investgation and find that. I add pathed version library in my project. 

There are two blocks of if's, first of them check and apply  blending mode. It ended with 'else' block which enabled normalblending. State of WebGL is changed. Second if block check and apply custom modes. It  checks state of srcColor & srcAlpha function changed and assign new values to local variables. And... this block may run only once, then it reckons states still unchanged. But state of blending may be changed in other places. 
I patch the library, replace else in the end of first if block with 'else if'. Now my demo work fine.

**Comment by Dark-Energy** [comment]
@sasha240100 this way is acceptable.

**Comment by WestLangley** [comment]
@mrdoob I think the OP is suggesting a one-line change in the ` WebGLState` function `setBlending()`:
```
} else if ( blending === MultiplyBlending ) {

	if ( premultipliedAlpha ) {

		gl.blendEquationSeparate( gl.FUNC_ADD, gl.FUNC_ADD );
		gl.blendFuncSeparate( gl.ZERO, gl.SRC_COLOR, gl.ZERO, gl.SRC_ALPHA );

	} else {

		gl.blendEquation( gl.FUNC_ADD );
		gl.blendFunc( gl.ZERO, gl.SRC_COLOR );

	}

} else if ( blending !== CustomBlending ) { // <==== PROPOSED CHANGE

	if ( premultipliedAlpha ) {

		gl.blendEquationSeparate( gl.FUNC_ADD, gl.FUNC_ADD );
		gl.blendFuncSeparate( gl.ONE, gl.ONE_MINUS_SRC_ALPHA, gl.ONE, gl.ONE_MINUS_SRC_ALPHA );

	} else {

		gl.blendEquationSeparate( gl.FUNC_ADD, gl.FUNC_ADD );
		gl.blendFuncSeparate( gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA, gl.ONE, gl.ONE_MINUS_SRC_ALPHA );

	}

}
```
With all due respect, that change seems a bit hacky to me. I think the entire code block should not be executed if `blending === CustomBlending`.

**Comment by mrdoob** [comment]
@WestLangley sounds hacky indeed.

**Comment by WestLangley** [comment]
@mrdoob I think something needs to be done. Maybe this one-line change is adequate to prevent the code block from being called when `CustomBlending` is used.
```
if ( ( blending !== CustomBlending ) && ( blending !== currentBlending || premultipliedAlpha !== currentPremultipledAlpha ) ) {
```

**Comment by mrdoob** [comment]
That looks good.
