### ISSUE TITLE
New labels to tag issues that need help

### ISSUE THREAD

**Issue by fernandojsg** [mrdoob/three.js#11298]
I believe `threejs` should adopt a similar kind of tags as many projects are using right now to guide people that want to help to the project. 
For example in https://github.com/aframevr/aframe we've: `help wanted (easy)` used to tag simple bugs or feature requests focused on newcomers to start contributing without being overwhelmed or afraid to take a bigger task to start with. We also have `help wanted (hard)` for harder issues but that will be easy to spot for people that have the knowledge but don't know where they could do to help to the project.
Similar approach is used by the https://github.com/servo/servo project and many others.

I feel that when newcomers or more advanced users come to three.js, people don't know where they could help to improve the project so many interesting features needed by the engine are left undone because people don't know what is needed to be implemented as here we don't have a clear roadmap.
So you should read all the issues and try to guess and measure what you could do.

Starting with a tag as proposed, let's say as the one used in aframe or whatever you feel it could fit, people could just filter by these tags and start contributing.

**Comment by Mugen87** [comment]
I like the idea. This should make things more transparent.

BTW: There is actually a developer's todo list (see https://github.com/mrdoob/three.js/wiki/Developer%27s-TODO-list) but it is not actively maintained.

**Comment by fernandojsg** [comment]
Yep, probably having the tags could help to populate that TODO-list with link to the issues and people could find the relation between them all

**Comment by mrdoob** [comment]
Sounds good to me 👍

**Comment by Mugen87** [comment]
Okay, let's do it! I've created two new labels for the project: `Help Wanted (easy)` and `Help Wanted (hard)`. Here is the first issue with one of the new labels 🎉  #10932

**Comment by Mugen87** [comment]
I think we can gradually change the label `Enhancement` to `Help Wanted(*)` for some issues e.g. #10932.

**Comment by jostschmithals** [comment]
In fact a good idea, but IMO `Help Wanted(*)` could be easily misunderstood - in the sense of `Help (please use Stackoverflow)`; I needed a moment to realize that `Help` was was meant the other way round in this case.

I think `Contribution desired(*)` would be less ambiguous.

**Comment by fernandojsg** [comment]
No strong opinion about any of them, but what about renaming `Help (please use stackoverflow)` to `Question ()`?

**Comment by Mugen87** [comment]
There is already a `Question` label. It's intended for issues where users don't ask for help but have e.g. conceptual questions about the library.

**Comment by fernandojsg** [comment]
Ok, so I don't know, it's up to you I'm happy with whatever name you could propose ;)

**Comment by Mugen87** [comment]
Maybe we can change `Help (please use stackoverflow)` just into `Please Use Stackoverflow`?

**Comment by fernandojsg** [comment]
That's sound great to me

**Comment by WestLangley** [comment]
I think these labels may be too confusing. It must remain clear this is not a help site.

I would go with `Help Please Use Stackoverflow`, `Enhancement`, and `Enhancement (easy)`.

I think that is sufficient. `Enhancement (hard)` serves no purpose.

Contributors can be directed towards `Enhancement` tags.

**Comment by Mugen87** [comment]
I'm okay with this.

**Comment by fernandojsg** [comment]
Following the same approach as the commented projects, `help wanted (*)` (or whatever name) will be used not just for `enhancement` but also for `bugs` or whatever kind of tag we could add in the future.
It's to guide contributors on what they could do, solving an easy bug or implementing an easy feature for example.

Also I expect that tag to be added for "approved" suggestions, so they're suggestions that are considered useful enough for the core to be implemented or added to the roadmap/to-do list.

So I could create both tags and add them to the issues as they're "validated". We could have issues with `[Bug, needhelp]``[Enhancement]`, `[Enhancement, needhelp(easy)]`, ...

**Comment by WestLangley** [comment]
No additional help tags please. Adding `Bug (easy)` is OK.

**Comment by fernandojsg** [comment]
Yep, that could works, just adding `Enhancement/Bugs(easy)`

**Comment by Mugen87** [comment]
Ok, i've added now `Enhancement (easy)` and `Bug (easy)`.

Please check the complete list of labels here: https://github.com/mrdoob/three.js/labels

**Comment by fernandojsg** [comment]
Perfect, thanks! :+1:
