### ISSUE TITLE
Feature: adding bounding box to frustum culling?

### ISSUE THREAD

**Issue by neeh** [mrdoob/three.js#11291]
##### Description of the feature 

I'm currently programming a chunked heightmap terrain (a huge heightmap divided in several `THREE.Mesh` instances) and started to think about frustum culling.

Today, three.js only uses bounding sphere for frustum culling (see [`Frustum`](https://github.com/mrdoob/three.js/blob/13e1518b5fdcc5cfffb6675eed1d3f4a06154aa3/src/math/Frustum.js#L83)). But I found bounding spheres being quite impractical in my case, as you can see in the following picture : 

<p align="center">
<img src="https://cloud.githubusercontent.com/assets/2312419/25782617/af1d6784-334e-11e7-9cba-57658cab924c.png" />
</p>

I think it's more geometry-related stuff so, do you think that's OK to add something like `frustumCullingPrimitive` in `Geometry` and `BufferGeometry` with two new constants `FrustumCullingSphere` and `FrustumCullingBox`?

**Comment by WestLangley** [comment]
I think that is use-case-specific and more appropriate for the application level. You can always set the visibility of each object yourself.

**Comment by Mugen87** [comment]
I've seen once a feature in an other engine where users could configure the bounding volume of a mesh with a set of predefined entities. You have something like `mesh.bounds` and can assign all bounding volumes (AABBs, BoundingSpheres) that implement a specific interface. The assigned bounding volume is the used for frustum culling. Therefore i labeled this initially as an enhancement.

**Comment by aardgoose** [comment]
FWIW I have created a similar tiled terrain model so have a potential use for this, not sure how much culling  improvement would result.

**Comment by neeh** [comment]
I'm aware that this feature is quite specific, in the sense that it is rarely required, and it's not that important.

But, given that frustum culling is done **inside** of the three.js renderer, I wouldn't think of that feature as use-case-specific.

Handling bounding boxes frustum culling (or any other bounding volume) at the application level would imply disabling the frustum culling of three.js and reimplement another one.

Three.js deals with both boundingBoxes and boundingSpheres, so why would frustum culling be limited to bounding spheres?

Finally, the math code for this feature is [already written](https://github.com/mrdoob/three.js/blob/dev/src/math/Frustum.js#L141).

**Comment by pailhead** [comment]
It is done, but can also be disabled... you can totally manage this on an app level

**Comment by neeh** [comment]
Hey, just made an [experiment](https://jsfiddle.net/005bkwx6/) to test the improvement between box and sphere culling for my use-case.

There is no real improvement until you arrive in the range 30° - 50° for the azimuth of the camera. For those angles you can have from 2 to 8 times less objects with the AABB culling.

Not a major improvement in the end... Even though those angles are well suited for a third person camera.

What do you think about that?

**Comment by WestLangley** [comment]
@neeh Cool demo! :)

Is it worth it in your use case to set `tile.frustumCulled = false` and implement your own visibility culling -- or is the improvement not significant?

**Comment by neeh** [comment]
Thank you @WestLangley :)

Well, I don't really know... If it's not possible to change Three.js, I think I'll go this way. But everything seems like I'm gonna be fragment-limitant anyway...

**Comment by pailhead** [comment]
Was about to ask how is this even working when there is no mention of frustumCulled in the fiddle. The assumption is that the bb fits much better in this particular case and that there will always be more culling over a sphere?

**Comment by neeh** [comment]
The fiddle was only made to see the difference of performance between AABB frustum culling and Bounding sphere frustum culling in terms of visible chunks. (Here performance = the number of chunks sent to the GPU)
The frustum culling in the fiddle is the one of Three.js (bounding sphere).

**Comment by neeh** [comment]
Just realized how [**heavy**](https://github.com/mrdoob/three.js/blob/dev/src/math/Box3.js#L431) it is to compute the world space AABB of a geometry.
AABB won't have any benefit over Spheres because of this unless we start caching world space bounding volumes.
In the meantime, I created my own frustum culling algorithm (I opted for quadtree-like).

Let's close this, thanks for the help!

**Comment by sasmaster** [comment]
Sorry for breaking into a closed thread,but I very much disagree. Sphere - Frustum test becomes very imprecise for highly unsymmetrical meshes.Like long narrow quads.Here for example something I have been working on:

![scr1](https://user-images.githubusercontent.com/438400/43074646-accd8858-8e86-11e8-866e-6da0b2b30e53.PNG)

I need to build 2d mesh ,sort of border frame around groups of objects.In many cases the shape is narrow and long. And I may have many of those in close proximity of each other.generating binding sphere in such a case would be very sub-optimal for frustum test as it will report many false-positives for the empty areas inside the circumference of such a sphere. Now,I do realize that JavaScript is slow,and AABB - frustum impl would be considerably slower, yet ,allowing the API user to decide which frustum test mode to use (AABB or Sphere) would prevent a real mess on the application level,where currently I have to turn off frustum test per such object and compute that manually.

**Comment by that-ben** [comment]
> 
> 
> I'm aware that this feature is quite specific, in the sense that it is rarely required, and is not that important.
> 
> But, given that frustum culling is done **inside** of the three.js renderer, I wouldn't think of that feature as use-case-specific.
> 
> Handling bounding boxes frustum culling (or any other bounding volume) at the application level would imply disabling the frustum culling of three.js and reimplement another one.

3 years later, this is still very relevant IMO, much more so that now three.js has instanced mesh, for which implied/automatic three.js bounding box is completely useless, since it knows nothing about instances vertex offsets.  It would be really useful if we could set our own bounding box to any geometry.
