### ISSUE TITLE
Can we have a JPGLoader for obj + mtl loading?

### ISSUE THREAD

**Issue by timcombs** [mrdoob/three.js#11290]
##### Description of Problem

I've found the TGALoader and the DDSLoader when loading obj + mtl files. But why isn't there a JPGLoader for jpg files? So many free obj come with jpg files for texture.

Am I missing something obvious here?

##### Browser

- [x] All of them
- [x] Chrome at least
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them

**Comment by looeee** [comment]
https://threejs.org/docs/#api/loaders/TextureLoader

**Comment by timcombs** [comment]
well. then can we have an example that shows how to use TextureLoader when loading obj + mtl files? Because it does not seem straight-forward like DDSLoader or TGALoader.

**Comment by mrdoob** [comment]
There is no need for a `JPGLoader` because browsers already support `jpg` natively.
