### ISSUE TITLE
Animation System - keyframe with incorrect number of property values causes browser to crash

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#11302]
Using a keyframe with an incorrect number of property values causes the browser window to completely hang - e.g. if using a VectorKeyFrameTrack for position but accidentally adding 4 properties instead of 3. 

See this [codepen](http://codepen.io/looeee/pen/NjXMVR?editors=0010), switch lines 45 and 46 to see crash. Tested in Chrome, Firefox and Edge on Windows 10 so I presume it happens in all browsers 

I know the philosophy here is not to provide error checking when incorrect parameters are entered, and if that is what we decide to do here too I will close the issue. But actually causing the browser window to crash seems more serious than just a console error, so perhaps some check error checking is warranted here.

**Comment by Mugen87** [comment]
Can confirm this...

**Comment by Mugen87** [comment]
`three.js` actually logs an error message:

![image](https://cloud.githubusercontent.com/assets/12612165/25891606/edb82c70-3571-11e7-92d0-905649166967.png)

**Comment by Mugen87** [comment]
This for loop causes the problem. https://github.com/mrdoob/three.js/blob/master/src/animation/KeyframeTrackPrototype.js#L343-L345

**Comment by Mugen87** [comment]
I tend to leave it as it is. `three.js` provides an error message after all. And a fix that regards all special cases makes the code in `KeyframeTrackPrototype` only more complicated.

**Comment by looeee** [comment]
I'm on vacation for the next week (without a laptop :fearful: ) so can't confirm that I see the error message.
I'll check it when I get back, or if you want feel free to close the issue.

**Comment by Mugen87** [comment]
Have a great holiday! 😊

**Comment by looeee** [comment]
OK, I've verified that I can see the error message. Even though it's a pretty ugly crash and require that I have the console open before the crash happens in order to see the message I guess that is good enough.
