### ISSUE TITLE
FileLoader not working correctly in IE

### ISSUE THREAD

**Issue by SoenkeHu** [mrdoob/three.js#11305]
##### Description of the problem 

Using the FileLoader with the Internet Explorer causes an Error, because other browser parse json files in the xhr request and the Internet Explorer does not. 

My fix was replacing [this line](https://github.com/mrdoob/three.js/blob/r85/build/three.js#L29460) with:
	
	if(event.target.responseType !== "json") {

		var response = JSON.parse(event.target.response);

	} else {

		var response = event.target.response;
				
	}

##### Three.js version

- [x] Dev
- [x] r85
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
What version of Internet Explorer are you using? 

https://github.com/mrdoob/three.js/blob/master/src/loaders/FileLoader.js#L136

**Comment by SoenkeHu** [comment]
> What version of Internet Explorer are you using?

Internet Explorer 11.0.9600.18426 (IE11)

**Comment by Mugen87** [comment]
@SoenkeHu Unfortunately, i'm unable to verify this bug because i have no IE11 around. Would you still mind to do a PR with the change? Maybe with a comment in the code that links to this issue?

**Comment by jostschmithals** [comment]
I tried to load some three.js examples (which use FileLoader) with IE 11.1198.14393.0 and had no problems.

**Comment by Mugen87** [comment]
@jostschmithals Interesting. As far as i see you are using a higher IE11 version. Could this make the difference?

**Comment by jostschmithals** [comment]
Maybe. 

I don't know, since I didn't really "use" IE before (the performance is really bad - in some cases I get only 1-2 FPS whereas Chrome makes 30 FPS on the same system). 

I only tried to reproduce the described issue this evening (with the version shipped with the regular Windows update), since I couldn't imagine that such an issue which would affect many of the examples was not noticed before. 

Maybe it was only a temporary bug in one IE version?

**Comment by Mugen87** [comment]
> Maybe it was only a temporary bug in one IE version?

That may very well be.

@SoenkeHu Is it possible that you update your IE11 to a newer version?

**Comment by SoenkeHu** [comment]
It happens on two other machines too. (IE 11.1198.14393.0)

So the error that IE throws is 

> cannot read property "length" of undefined or null

 in [this line](https://github.com/mrdoob/three.js/blob/dev/src/loaders/JSONLoader.js#L140)
but the problem is in the FileLoader, because the JSON doesnt get parsed in the FileLoader nor in IE (unlike other browsers).

The problem occured in [the JSONLoader blender example](https://threejs.org/examples/#webgl_loader_json_blender)

The problem does not exist in r84.

**Comment by Mugen87** [comment]
I assume this commit is the problem: e4feff113c3d7c56b44fef2f8798265c76b727c3

This explains the different behavior to `r84`.

@jostschmithals Can you also test with the mentioned JSONLoader example?

**Comment by SoenkeHu** [comment]
@Mugen87 yes. That is it. All examples using the changed loaders dont work in IE11.
uncomplete List of examples with that problem:

BufferGeometryLoader
- https://threejs.org/examples/#webgldeferred_animation
- https://threejs.org/examples/#webgl_performance
- https://threejs.org/examples/#webgl_performance_static
- https://threejs.org/examples/#webgl_geometry_colors_lookuptable

JSONLoader
- https://threejs.org/examples/#canvas_materials_normal
- https://threejs.org/examples/#canvas_materials_reflection

I think it should be handled in the FileLoader.
Maybe extend [this if](https://github.com/mrdoob/three.js/blob/dev/src/loaders/FileLoader.js#L47). That should fix it.

**Comment by jostschmithals** [comment]
Indeed - I can confirm that these examples don't work in IE11 (yesterday I tested some different examples, since the original post was more unspecific).

**Comment by Mugen87** [comment]
Instead of adding new code, we maybe should revert e4feff113c3d7c56b44fef2f8798265c76b727c3. Let's wait what @mrdoob says.

**Comment by mrdoob** [comment]
@Mugen87 I guess I'll revert that commit 😇

**Comment by mrdoob** [comment]
Done! https://github.com/mrdoob/three.js/commit/49071e5a7770de3bf505705fc593abf2e13bc0af
