### ISSUE TITLE
Three.js Blender exporter: Name 'geometry data' not defined (geometry.py, L361)

### ISSUE THREAD

**Issue by cmeeren** [mrdoob/three.js#11307]
When using the three.js exporter for Blender, I occasionally get an error with a traceback ending with:

```
  File "c:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\exporter\geometry.py", line 361, in _scene_format
    geometry_data[constants.DRAW_CALLS] = draw_calls
NameError: name 'geometry_data' is not defined
```

The relevant line:

https://github.com/mrdoob/three.js/blob/a1fb0b5b3ffd766f7d58cc4ec065c6b9bd617e81/utils/exporters/blender/addons/io_three/exporter/geometry.py#L361

It seems a list called `geometry_data` is used, but it never seems to be assigned, nor used elsewhere in the three.js exporter (or anywhere in the entire Blender directory for that matter).

**Comment by centerionware** [comment]
I saw this too yesterday when trying to export a very large model with 400k verts. When I reduced the size of the model it worked.

**Comment by cmeeren** [comment]
Neither size nor number of vertices/objects seems to be the deciding factor for me.

**Comment by centerionware** [comment]
Interestingly, if I comment out the lines causing the problem the exporter still function normally on everything else, so I'm guessing the draw_calls code is something still in progress by someone, or a recent regression or deprecation. For now, adding a # to the start of lines 360 and 361 to comment them out is a workaround, unless/until someone patches or has patched it properly.

**Comment by cmeeren** [comment]
Yes, that seems to work for me too (in my very limited test).
