### ISSUE TITLE
No 'anchor' property in Object3D?

### ISSUE THREAD

**Issue by cenchy** [mrdoob/three.js#11317]
No anchor property in Object3D?

**Comment by Mugen87** [comment]
Can you please explain what would be the purpose of an `anchor` property? Or maybe you can describe a concrete use case?

**Comment by pailhead** [comment]
AFAIK no. You can add it

```
Object.defineProperty( THREE.Object3D, "anchor" , { ... } );
```

**Comment by mrdoob** [comment]
Maybe he means a `pivot`?

**Comment by pailhead** [comment]
Perhaps? But isn't that what you're supposed to achieve with Groups and Objects?

**Comment by Mugen87** [comment]
>  But isn't that what you're supposed to achieve with Groups and Objects?

Correct, see #1364.
