### ISSUE TITLE
THREE.ConvexGeometry is undefined (r85)

### ISSUE THREAD

**Issue by donpinkus** [mrdoob/three.js#11316]
##### Description of the problem 
After importing r85, `THREE.ConvexGeometry` is undefined.

According to its page in the [docs](https://threejs.org/docs/#examples/geometries/ConvexGeometry), it's a ThreeJS function.

Why is it undefined?

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donpinkus** [comment]
1. Didn't notice that there were two levels of hierarchy in the section docs, and this was under "Examples"

2. Took some googling before learning that things in "Examples" aren't in the official package. Obvious in hindsight, was really confusing since they're right alongside actual functionality.

**Comment by gazhay** [comment]
+1
