### ISSUE TITLE
Please, add these features to Three.js

### ISSUE THREAD

**Issue by berserk82** [mrdoob/three.js#11310]
Hello there.
My name is Ivano Arrighetta and I'm Italian.
I would like to see these features added to Three.js:
projected textures (textures which are emitted from a light source)
radiosity
caustics (see this demo: https://github.com/evanw/webgl-water)

Thanks in advance for any help.

Bye, Ivano.

**Comment by berserk82** [comment]
Drop the multiple camera thing, I discovered it's already possible.

**Comment by WestLangley** [comment]
>projected textures

I assume you referring to supporting a `mask` property of `SpotLight`. An alpha mask would block the light where alpha was 1; a color mask would tint the light. Material roughness would have to be accommodated for a consistent implementation.

>radiosity

Are you requesting global illumination support?

>caustics

That would be part of the application layer and is not relevant to three.js.

**Comment by berserk82** [comment]
Yes, exactly as you say for projected textures and radiosity.
Ok for caustics, it would have been cool.

**Comment by WestLangley** [comment]
Related GI question: #6575.

**Comment by berserk82** [comment]
Ok, but what about projected textures?

**Comment by pailhead** [comment]
Coming right up!

**Comment by berserk82** [comment]
Any news about projected textures?
