### ISSUE TITLE
What is three.js's normal map handedness convention?

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#11315]
It may be helpful to have this documented. @emackey pointed out an issue with GLTF2Loader (https://github.com/donmccurdy/three-gltf-viewer/issues/10) and normal map inversion seems to be responsible. For comparison:

> BabylonJS: x-axis = left, y-axis = down
> OpenGL: x-axis = right, y-axis = up
> DirectX: x-axis = right, y-axis = down

**Comment by emackey** [comment]
Has there been progress on this?

In my own projects I'm [fixing this manually](https://github.com/AnalyticalGraphicsInc/gltf-vscode/blob/c7be56a56b52a6b49bde1ca8696930bcc6568f4d/pages/three.js#L133) by setting:

```
    material.normalScale.x = -1;
```

**Comment by donmccurdy** [comment]
I haven't heard anything. It would be nice to know, but I'm inclined to just flip `normalScale.x` if that works correctly with the sample models.

**Comment by emackey** [comment]
The answers have been worked out by @WestLangley and @donmccurdy here:  https://github.com/mrdoob/three.js/pull/13784#issuecomment-379511456

Hopefully I'm summarizing correctly:

* ThreeJS's default normal map handedness is OpenGL, right-handed, same as glTF.
* ThreeJS's default UV origin is lower-left, opposite of glTF's upper-left UV origin.
* As a result, GLTFLoader must flip the UVs and then flip the normal handedness to compensate.
