### ISSUE TITLE
glTF 2.0 Morph targets model is not displayed

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#11326]
##### Description of the problem 

I am testing glTF 2.0 sample models and Three.js glTF 2.0 Loader.
https://github.com/cx20/gltf-test/tree/2.0#simple-models-for-testing-individual-features

However, it seems that morph targets model is not displayed.

Model : Animated Morph Cube
https://github.com/HowardWolosky/glTF-Sample-Models/tree/morphAnimation/2.0/AnimatedMorphCube
![image](https://raw.githubusercontent.com/HowardWolosky/glTF-Sample-Models/morphAnimation/2.0/AnimatedMorphCube/screenshot/screenshot.gif)

[Three.js + glTF Loader Result](https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/examples/threejs/index.html?category=tutorialModels&model=AnimatedMorphCube&scale=1&type=glTF) is NG
[Babylon.js + glTF Loader Result](https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/examples/babylonjs/index.html?category=tutorialModels&model=AnimatedMorphCube&scale=1&type=glTF) is OK

Model : Animated Morph Sphere 
https://github.com/HowardWolosky/glTF-Sample-Models/tree/morphAnimation/2.0/AnimatedMorphSphere
![image](https://raw.githubusercontent.com/HowardWolosky/glTF-Sample-Models/morphAnimation/2.0/AnimatedMorphSphere/screenshot/screenshot.gif)

[Three.js + glTF Loader Result](https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/examples/threejs/index.html?category=tutorialModels&model=AnimatedMorphSphere&scale=1&type=glTF) is NG
[Babylon.js + glTF Loader Result](https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/examples/babylonjs/index.html?category=tutorialModels&model=AnimatedMorphSphere&scale=1&type=glTF) is OK

##### Three.js version

- [x] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

ThinkPad X260 + Windows 10 + Intel HD Graphics 520

**Comment by takahirox** [comment]
`GLTF2Loader` doesn't support it but maybe we do soon #10806

**Comment by takahirox** [comment]
BTW is SimpleMaterial.gltf in your repository correct?
It doesn't seem to have a parameter corresponding to position attribute.

https://github.com/cx20/gltf-test/blob/7abbfeb846a887b7dd08adea3f631d112d0a764f/tutorialModels/SimpleMaterial/glTF/SimpleMaterial.gltf#L86-L110

**Comment by donmccurdy** [comment]
@takahirox are you started on this? I have also done a bit of work here: https://github.com/mrdoob/three.js/compare/dev...donmccurdy:feat-gltf-morphtargets

^it isn't doing anything yet, though.

**Comment by takahirox** [comment]
Yeah, I've started. Looks like our progresses are same haha.

**Comment by donmccurdy** [comment]
haha ok, we need a trello board or something 😆
I don't plan to do more for a couple days, so carry on!

**Comment by donmccurdy** [comment]
This is fixed now — if the model contains animation clips for the morph targets, they can be played as usual. If it contains morph targets alone, they are mutated with:

```js
mesh.morphTargetInfluences[0] = 0.0;
mesh.morphTargetInfluences[0] = 0.1;
// ...
mesh.morphTargetInfluences[0] = 1.0;
```

**Comment by cx20** [comment]
I confirmed that the model is displayed correctly.

[AnimatedMorphCube](https://cdn.rawgit.com/cx20/gltf-test/a9cd453d76bba2856941679de298f67c5499922f/examples/threejs/index.html?category=tutorialModels&model=AnimatedMorphCube&scale=1&type=glTF) is OK
[AnimatedMorphSphere](https://cdn.rawgit.com/cx20/gltf-test/a9cd453d76bba2856941679de298f67c5499922f/examples/threejs/index.html?category=tutorialModels&model=AnimatedMorphSphere&scale=1&type=glTF) is OK

**Comment by samwei12** [comment]
@donmccurdy 
hi, how can I get mesh attributes from a glTF loader object?

**Comment by donmccurdy** [comment]
@samwei12 If you mean attributes like vertex positions and normals, it doesn't actually matter what loader or model format you used to create the THREE.Mesh:

```js
result.traverse(function(node) {
  if (node.isMesh) {
    console.log(node.geometry.attributes);
  }
});
```

See [THREE.BufferGeometry](https://threejs.org/docs/#api/core/BufferGeometry) for more details.
