### ISSUE TITLE
webvr_cubes vs webvr_daydream freezes vr device

### ISSUE THREAD

**Issue by marclave** [mrdoob/three.js#11324]
Comparing the webvr_cubes and webvr_daydream examples, there is not a noticeable difference except for the DayDream Controller  and WebVREffect/control Even without the actually generating more cubes. One of them is adding the scene and was questioning if there is a best practice for adding a scene and what the idea for developing the DayDreamController and not using the WebVRControls.

There appears to be no high level documentation for the VREffect and VRControls nor the DayDreamController, and this question could answered in time after I get more experience with threejs but I wanted to pose it here.

Tested devices with VR enabled and not using polyfill:
samsung galaxy s4
Pixel
- [x ] Chrome
- [x ] Android

Just wanted insights on best practices due to the disparity of initialising the webvr application of the two where one has a poor performance.

**Comment by Mugen87** [comment]
> ...where one has a poor performance.

What example do you actually mean?

> There appears to be no high level documentation for the VREffect and VRControls nor the DayDreamController...

I think these entities are still a little bit experimental and therefore not yet documented. When things get more stable, there will also be an appropriate documentation.

**Comment by marclave** [comment]
[cubes](https://threejs.org/examples/webvr_cubes.html)

[daydream](https://threejs.org/examples/webvr_daydream.html)

**Comment by Mugen87** [comment]
I understood you in a way, that one example has a poorer performance than the other. Is that correct? 😇

**Comment by marclave** [comment]
Yeah exactly 😄

**Comment by marclave** [comment]
I understand the documentation part alongside the maturity of the modules.

**Comment by Mugen87** [comment]
And which example is it? cubes or daydream?

**Comment by marclave** [comment]
I really should have been more concise and clear.


The cubes example performs worse than daydream even generating cubes on the `mousedown` event in the cubes example.

**Comment by mrdoob** [comment]
That's good! `webvr_daydream` is a more optimised render path. It's still work in progress though. Eventually, all the examples will use the optimised render path.

**Comment by marclave** [comment]
Awesome thanks :smile:
