### ISSUE TITLE
Latest glTF 2.0 spec BoomBox is not displayed

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#11328]
##### Description of the problem 

Model : BoomBox
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoomBox

Result :
https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/examples/threejs/index.html?category=tutorialModels&model=BoomBox&scale=1&type=glTF

```
GLTF2Loader.js:1357 
Uncaught (in promise) RangeError: Invalid typed array length
    at new Float32Array (native)
    at https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/three.js/r86dev/GLTF2Loader.js:1357:14
    at _each (https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/three.js/r86dev/GLTF2Loader.js:860:26)
    at https://cdn.rawgit.com/cx20/gltf-test/bd72508c7291cc50eddeaeef1d0dfb35fe194ba0/libs/three.js/r86dev/GLTF2Loader.js:1332:11
    at <anonymous>
```

Relate : https://github.com/KhronosGroup/glTF-Sample-Models/pull/56

##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

ThinkPad X260 + Windows 10 + Intel HD Graphics 520

**Comment by takahirox** [comment]
I suppose this PR #11294 would fix this issue.

**Comment by takahirox** [comment]
The PR has been merged.
Would you try the test again?

**Comment by cx20** [comment]
I confirmed that it will be displayed with the latest version of glTF Loader.
https://cdn.rawgit.com/cx20/gltf-test/44fe5774bb3528d0e3388889ce4216579e52fc28/examples/threejs/index.html?category=tutorialModels&model=BoomBox&scale=1&type=glTF
