### ISSUE TITLE
Blender Exporter rotation around z issue

### ISSUE THREAD

**Issue by centerionware** [mrdoob/three.js#11329]
##### Description of the problem 

Everything exported from blender is rotated around it's local Z axis by 180 degrees.

To reproduce:
Open blender, with the default cube and default camera position edit the cube. Grab the left four vertices and drag out along the y axis to create a cuboid. Add a sphere near near the new extended end of the cuboid (As a seperate object, not as part of the same mesh)
Select no objects in the screen. Use the exporter, export the entire scene, hierarchy, and optionally materials with the rest of the settings left at the default.
Take the json, drop it into the threejs Editor. Notice the cuboid and the sphere don't line up like they do in blender, but if you rotate the cuboid and sphere around Z by 180deg (+ or - doesn't matter) they line up properly.

I noticed this with a larger scene I was working on, and absolutely everything is rotated around it's local center by 180 degrees on the Z axis. Using the io_three exporter from the dev branch a few days ago, and tried the import on the threejs editor at https://threejs.org/editor/

test files available on request, but since it's so simple to reproduce I'm not going to bother adding them to this post.

##### Three.js version

- [ x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by manthrax** [comment]
This is by design. The exporter makes some decisions about to adjust the mesh and transforms, before exporting it.

I think this may have been an early design choice that is no longer appropriate.

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
