### ISSUE TITLE
Change renderer.gammaInput/renderer.gammaOutput on the fly?

### ISSUE THREAD

**Issue by OrtOfOn** [mrdoob/three.js#11332]
Hi guys,

Is there a way to change these parameters in real-time? 

It seems the shader programs don't take it in consideration... even if I tell my materials to be updated (needsUpdate=true) after the change.

Or maybe there is a good reason that explains the WebGLRenderer needs to be disposed and instanciated again?

Many thanks.

Q.

**Comment by WestLangley** [comment]
Can you please explain your use case?

I understand that one use case would be to render to a texture with linear output (for further processing) and then render to the screen with gamma output.

You can avoid setting `renderer.gammaInput` and set `texture.encoding` instead. (See http://threejs.org/docs/#api/constants/Textures.) You will have to set `material.needsUpdate` if the encoding is changed after the first render.

Currently, I am not sure if output encoding on a per-material basis has been fully implemented.

This entire issue regarding encoding and extensions probably needs to be revisited.

/ping @bhouston 

three.js r.85

**Comment by bhouston** [comment]
gammaOutput, gammaInput are legacy.  You can set per-texture and per-render target encodings for read/write.  I'd do more research there and see if that can meet your needs.

**Comment by bhouston** [comment]
Just to be clear, use ```texture.encoding``` for reading and writing using various different encodings.

**Comment by WestLangley** [comment]
@bhouston I see that one can specify an encoding for a texture and an encoding for a render target.

However, in the case of rendering to the screen, I think the encoding is always `LinearEncoding`, unless `gammaOutput = true`, in which case it is `GammaEncoding`.

To the best of my knowledge, there are no other options. Am I missing something?

Do we need to deprecate `renderer.gammaOutput` and add `renderer.outputEncoding`, and declare `outputEncoding` applies only when rendering to the screen?

**Comment by OrtOfOn** [comment]
Hi guys, thanks for your replies.
@WestLangley: I'm building a previewer of MAX scenes for a client and I would like to let the user choose the type of Color Space (Gamme or Linear). 

It would be very nice to have something similar to Unity or Unreal.... for example: 

renderer.colorSpace = THREE.LinearEncoding;
or 
renderer.colorSpace = THREE.GammaEncoding;

I could work with deprecated gammeOutput/Input but on the fly changes are not take in consideration. A new WebGLRenderer must be instantiated.

I looked at the source and it seems the Shader Programs do not tell the texture the encoding has changed.

**Comment by bhouston** [comment]
> Do we need to deprecate renderer.gammaOutput and add renderer.outputEncoding, and declare outputEncoding applies only when rendering to the screen?

I agree with the above (BTW there is always an outputEncoding declared, it is just usually sourced from looking at the renderTarget.encoding or failing that renderer.outputGamma -- we just need it ot use the renderer.encoding instead of renderer.outputGamma.)  That end result you propose is what I intended but it does break every single example that currently uses gammaInput and gammaOutput, but it is the right thing to do for correctness and code simplification.

**Comment by bhouston** [comment]
We just need to modify this function call to get the renderer.outputEncoding: 

https://github.com/mrdoob/three.js/blob/7f55016b844512b4072b88f04c48996791ebce53/src/renderers/webgl/WebGLPrograms.js#L136

**Comment by WestLangley** [comment]
Great! We are all on the same page. :)

@OrtOfOn For now you can hack `WebGLPrograms.getProgramCode()` and make this change:
```
array.push( renderer.gammaOutput ); // add this line

return array.join();
```

Setting `material.needsUpdate` will then do what you expect.

We can figure out the best way to deprecate `renderer.gammaInput` and `renderer.gammaOutput`.

**Comment by OrtOfOn** [comment]
Thank you very much guys!
