### ISSUE TITLE
Buffer geometry addGroup not setting the material properly

### ISSUE THREAD

**Issue by edap** [mrdoob/three.js#11346]
##### Description of the problem 

I've created a buffered geometry (mergin together BoxGeometries and a custom geometry) and I want to apply 2 differents materials on it.
I've used the addGroup method, as explained here:
http://stackoverflow.com/questions/32921801/how-do-drawcalls-work-in-three-js

```javascript
    let geometry = palm.geometry;
    let bufGeometry = new THREE.BufferGeometry().fromGeometry(geometry);
    let palmBuffers = palm.buffers;

    let tot_vert = palmBuffers.totVertices;
    let tot_vert_foliage = palmBuffers.totFoliageVertices;
   //tot_vert = 149871
   // tot_foliage_vertices = 129387

    let materials =new THREE.MultiMaterial([material, trunkMaterial]);
    bufGeometry.clearGroups();
    bufGeometry.addGroup(0,tot_vert_foliage,1);
    bufGeometry.addGroup((tot_vert_foliage+1),tot_vert,0);
    //console.log(material);
    //console.log(trunkMaterial);
    // both materials are set
    let mesh = new THREE.Mesh(bufGeometry, materials);
    return mesh;
```
The result is this:
![screen shot 2017-05-16 at 12 38 47](https://cloud.githubusercontent.com/assets/161152/26102679/69712786-3a36-11e7-9f46-df725aaf9760.png)

The trunk of the palm in this picture is made by cubes, that are rendered correctly when using a single material. But When I use a multiple materials, as you see, the selected material it is applied only to certain faces.

##### Three.js version

- [ ] Dev
- [x ] r83
- [ ] ...

##### Browser

- [] All of them
- [x ] Chrome
- [ x] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Update to the current version, reproduce the problem by merging a few simpler geometries, and post on SO if you need help.

**Comment by edap** [comment]
Just in case someone else is in the same situation. My error was thinking that the count for the vertices goes like this:

from 0 to 129387 apply material 0
from (129387+1) to total number of vertices, apply material 1.

the second step is wrong, it should be:
"from 129387 to total number of vertices, apply material 1.", without the +1 for the count.
