### ISSUE TITLE
Docs: Explain the caching mechanism of three.js 

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#11345]
It would be very useful if somebody would create an additional documentation page that explains the different caching mechanism of `three.js`:

- It should be highlighted that a caching system is an important part of a 3D library in order to reduce the overhead implied by recreating or resetting something already done. The goal is to minimize the communication between `three.js` and the WebGL API, because those API calls can be expensive.
- Provide an overview what kind of entities are cached in `three.js` (e.g. Materials, Geometries, Textures...).
- Explain, what the `.dispose()` methods do and why they are important.

In the past, i've seen many questions about caching and code where `.dispose()` is not used correctly. An additional documentation page will provide a better understanding of this important topic.

The page could be integrated in the `Next Steps` section.

**Comment by pailhead** [comment]
+10

If i may add, would it make sense to comment some of the code? Going through the renderer can be quite intimidating.

**Comment by Mugen87** [comment]
The work result should be a new page like "[How to update things](https://threejs.org/docs/index.html#manual/introduction/How-to-update-things)". The assignee is of course free to add some comments in the code.

**Comment by pailhead** [comment]
Btw why did you tag this as easy :) this one doesnt seem so easy

**Comment by Mugen87** [comment]
Getting an overview about the caching mechanism is simple. You can search for `dispose`  in the `renderers` directory and study the related code or event listeners (like `onTextureDispose` or `onGeometryDispose`). Besides, it's not necessary to write any code. Indeed, depending on prior knowledge of the assignee it might be necessary to invest some time, but it should not be too complicated.

It's also not bad if some content would be missing with the initial commits. The community could add them in the context of the respective PR.

**Comment by Mugen87** [comment]
A note for the interested reader:  I can recommend two publications in this area: _Rendering Optimizations in the Turbulenz Engine by David Galeano_ and _WebGL Engine Design in Babylon.js by David Catuhe_. Both available in [WebGL Insights](http://www.webglinsights.com/).

**Comment by Mugen87** [comment]
@pailhead You're right. This is a task for a more advanced `three.js` user...

**Comment by pailhead** [comment]
😆 

I'm thinking more of a collaboration, almost pair coding or something.

**Comment by trusktr** [comment]
I opened an issue about it [in the forums](https://discourse.threejs.org/t/the-need-for-a-how-to-clean-things-up-section-of-the-docs/5831). In particular, here's a cleanup problem I encountered in [this comment](https://discourse.threejs.org/t/the-need-for-a-how-to-clean-things-up-section-of-the-docs/5831/2).

**Comment by Mugen87** [comment]
#15719 added a guide discussing the most important aspects relevant for users. Especially the usage of `dispose()` methods. 

Other caching mechanisms like uniform or WebGL state caching are transparent for the user and don't have to be a part of this guide.
