### ISSUE TITLE
Enhancements in SVGRenderer

### ISSUE THREAD

**Issue by linev** [mrdoob/three.js#11356]
Starting from ~20K faces, SVGRenderer slows down quickly.
Main problem - it creates as many SVG primitives (svg:line, svg:rect, svg:path) as faces in the model.
Most browsers have a problem to render SVG if number of primitives more than 20K.

One can optimize this. First of all, always use svg:path. And second, when consequent paths has same style (like similar fill color), just concatenate them. For many complex geometries this highly increase performance of SVGRenderer.

Another related issue - use of SVGRenderer with Node.js and [jsdom](https://github.com/tmpvar/jsdom). jsdom has similar limitation with number of created SVG primitives. But I want to use SVGRenderer to create plain SVG files (like [this one](https://github.com/linev/jsroot-test/blob/master/TGeo/alice.svg)). For such application I do not need DOM at all and can directly create SVG string. 

One can enhance SVGRenderer so, that it optionally creates plain string with SVG instead of SVG elements. This also can improve performance a lot (factor 20 for given geometry). 

I can provide pull requests implementing both features.

**Comment by mrdoob** [comment]
Interesting... Yeah! PRs for these would be great!

**Comment by linev** [comment]
#11359 - here is my first PR:

**Comment by linev** [comment]
#11379 - this is second PR with text-output support

**Comment by linev** [comment]
Just for history - here is workaround we used in our project:
https://github.com/root-project/jsroot/blob/master/libs/three.svg_renderer_header.js
https://github.com/root-project/jsroot/blob/master/libs/three.svg_renderer_footer.js
Original SVGRenderer "wrapped" into small extra code and instead of creation of many small elements single `svg:path` is produced. In many respects it is much more performant.

But SVG rendering we using only for debugging now - WebGLRenderer is working perfectly now in node.js and produced images can be embed into SVG using `svg:image` element.
