### ISSUE TITLE
Clean up XLoader

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#11353]
##### Description of the problem 

Someone would you please clean up `XLoader` code?
I think it's a bit too messed up to work among contributors.

/cc @adrs2002 

##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by adrs2002** [comment]
I think your point is rough.
Specifically, which area is it?

If you are thinking that "quality is low",  you do not mind writing so :smiley:

**Comment by takahirox** [comment]
For example,

wrong intent
https://github.com/mrdoob/three.js/blob/53e3b1b4061742889f64add932147ae85a3b503c/examples/js/loaders/XLoader.js#L1445-L1481

wrong space
https://github.com/mrdoob/three.js/blob/53e3b1b4061742889f64add932147ae85a3b503c/examples/js/loaders/XLoader.js#L425

wrong reference (maybe)
https://github.com/mrdoob/three.js/blob/53e3b1b4061742889f64add932147ae85a3b503c/examples/js/loaders/XLoader.js#L394

And I want it to be entirely readable more or we need comment.

**Comment by mrdoob** [comment]
@adrs2002 I wouldn't say is bad quality, but it sure has some issues... It creates a lot of functions in global scope which could collide with user's code.

I think https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/MD2Loader.js and https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/PlayCanvasLoader.js are good examples of my preferred structure for loaders.

Single object with `load` and `parse` as public methods.

**Comment by adrs2002** [comment]
OK. i fixing this.
Continue here　↓
https://github.com/mrdoob/three.js/pull/11361
