### ISSUE TITLE
Why BVH/PCDLoader load data as arraybuffer?

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#11354]
##### Description of the problem 

Why do `BVHLoader` and `PCDLoader` load data as `arraybuffer` and then convert it to `String`?
Is there any special reasons that they can't simply load as `text`?

/cc @herzig @filipecaixeta

##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by filipecaixeta** [comment]
If you go to the specification of PCD files you can see that there are 2 kinds of PCD. There is binary as ASCII, but for both versions the header is ASCII. By using an arraybuffer I was able to convert only the header to ASCII and have the data in binary. If you read as a text and later you find out that your data is binary you can't go back to binary.
Does that answer your question?

**Comment by takahirox** [comment]
Oops, I've missed that the logic for binary format starts from here

https://github.com/mrdoob/three.js/blob/1a336dc20a49fa5c5b80dd2b7dac2ca7cecce128/examples/js/loaders/PCDLoader.js#L191

Thanks!

**Comment by takahirox** [comment]
If I'm right, we can simply replace the conversion with loading as `text` in `BVHLoader`, correct?

https://github.com/mrdoob/three.js/blob/0e55a079cec600a17eb67c669c683d13daa9d79d/examples/js/loaders/BVHLoader.js#L27-L33
https://github.com/mrdoob/three.js/blob/0e55a079cec600a17eb67c669c683d13daa9d79d/examples/js/loaders/BVHLoader.js#L379-L386

**Comment by mrdoob** [comment]
I think so 👍
