### ISSUE TITLE
The WebGL2 sandbox example in offical site not working

### ISSUE THREAD

**Issue by liyuanqiu** [mrdoob/three.js#11363]
##### Description of the problem 
This example is not working
[https://threejs.org/examples/?q=webgl2#webgl2_sandbox](https://threejs.org/examples/?q=webgl2#webgl2_sandbox)

Browser's log shows:
<pre>
Uncaught TypeError: THREE.WebGL2Renderer is not a constructor
    at init (webgl2_sandbox.html:116)
    at webgl2_sandbox.html:56
</pre>

Release r83's release log shows that the WebGL2Renderer has already been added.
[https://github.com/mrdoob/three.js/releases/tag/r83](https://github.com/mrdoob/three.js/releases/tag/r83)
<pre>
WebGL2Renderer
    Added. (@mrdoob)
</pre>

Maybe something wrong in building?

##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by Mugen87** [comment]
This is actually a misunderstanding. `WebGL2Renderer` is not yet developed and therefore no part of the build. The release note just wanted to highlight that the corresponding file and some skeleton code was added.

**Comment by Mugen87** [comment]
I've prepared a little PR that removes the example from the list.

**Comment by liyuanqiu** [comment]
Sorry, I didn't explore the source code carefully. Thank you for your patient explanation.

**Comment by mrdoob** [comment]
After 5f889ce296aaf447ec5992a6df726691098a9110 it should work again. But only on browsers that support ES6 modules 😇
