### ISSUE TITLE
THREE.NURBSCurve getPoint is not work!

### ISSUE THREAD

**Issue by xjindf** [mrdoob/three.js#11362]
var nurbsDegree = 3;
                        for (var i = 0; i <= nurbsDegree; i++) {
                            nurbsKnots.push(0);
                        }
                        for (var i = 0, j = 7; i < j; i++) {
                            nurbsControlPoints.push(
                                    new THREE.Vector4(
                                        i,
                                        i+1,
                                        0,
                                        1
                                    )
                                );
                            var knot = (i + 1) / (j - nurbsDegree);
                            nurbsKnots.push(THREE.Math.clamp(knot, 0, 1));

                        }
                        nurbsCurve = new THREE.NURBSCurve(nurbsDegree, nurbsKnots, nurbsControlPoints);
                        var length = nurbsCurve.getLength();
                        var num = 5 / length;
                        var point = nurbsCurve.getPoint(num);

Thank you for your help through the incorrect point taken by getpoint. Thank you very much！！

**Comment by Mugen87** [comment]
Can you describe the expected and actual result of `.getPoint()`?

Besides, it would be great if you provide your code in a fiddle. It's easier to debug if we have a little test file. 

http://jsfiddle.net/akmcv7Lh/

**Comment by xjindf** [comment]
i provide code in a fiddle.I want to take a certain distance from the curve to locate the model, but the position that getpoint gets is not expected. I hope you can help me. Thank you very much! @Mugen87

**Comment by Mugen87** [comment]
Do this look better? http://jsfiddle.net/akmcv7Lh/130/

I've changed the way how you sample points in  the last `for` loop. Now you have an even distribution of points along your curve.

**Comment by Mugen87** [comment]
I think this is not a bug but more some kind of comprehension question. Have a look at https://threejs.org/docs/#api/extras/core/Curve.getPoint and the related examples in order to get a better understanding of the method. If you need further help, please ask a question at stackoverflow.
