### ISSUE TITLE
MeshStandardMaterial envMap incorrect sampling

### ISSUE THREAD

**Issue by NNskelly** [mrdoob/three.js#11367]
##### Description of the problem 

When a spherical/lat-long image is attached to a MeshStandardMaterial as an envMap, objects with that material set show the same portion of the env map reflected on faces 180 degrees opposed.  Additionally, at oblique angles, unnatural pinching to a single point is observed at the horizontal and vertical "edges" of the reflected environment.
Adding a sphere to my test scene in lieu of a flat plane, I note that the angle reflected in the environment map does not appear to change _at all_, irrespective of camera position, which is contrary to the typical notion of an environment/reflection map.

As a side note, adjusting the U offset property of a 305 SpericalReflectionMapping texture DOES cause it to resample to the appropriate rotation when used as a color or similar property map, but has no effect on the sampling when the texture is applied as an envMap.

##### Three.js version

- [ ] Dev
- [ ] r85
- [ ] ...

##### Browser

- [?] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [?] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Reproduced on current live https://threejs.org/editor/ in an unaugmented Chrome instance with the attached scene:
`{
	"metadata": {
		"version": 4.5,
		"type": "Object",
		"generator": "Object3D.toJSON"
	},
	"geometries": [
		{
			"uuid": "A189E19E-2A25-434D-8276-41FBCEF901D1",
			"type": "PlaneBufferGeometry",
			"width": 2,
			"height": 2
		},
		{
			"uuid": "96CE9946-FDA3-412A-8AFC-ED7CDC25B087",
			"type": "SphereBufferGeometry",
			"radius": 1,
			"widthSegments": 32,
			"heightSegments": 16,
			"phiStart": 0,
			"phiLength": 6.283185,
			"thetaStart": 0,
			"thetaLength": 3.141593
		}],
	"materials": [
		{
			"uuid": "07FF37D9-AC9C-44FA-BFC2-BDC69854DD4E",
			"type": "MeshStandardMaterial",
			"color": 16777215,
			"roughness": 0.0,
			"metalness": 1.0,
			"emissive": 0,
			"envMap": "AB3128FA-87B5-414D-8258-C96216BEAD57",
			"depthFunc": 3,
			"depthTest": true,
			"depthWrite": true,
			"skinning": false,
			"morphTargets": false,
			"dithering": false,
			"side": 2
		}],
	"textures": [
		{
			"uuid": "AB3128FA-87B5-414D-8258-C96216BEAD57",
			"name": "",
			"mapping": 305,
			"repeat": [1,1],
			"offset": [0,0],
			"wrap": [1001,1001],
			"minFilter": 1008,
			"magFilter": 1006,
			"anisotropy": 1,
			"flipY": true,
			"image": "810D111B-DB71-4542-B741-F0361C173F11"
		}],
	"images": [
		{
			"uuid": "810D111B-DB71-4542-B741-F0361C173F11",
			"url": "http://www.luxrender.net/wiki/images/6/66/Latlong_orientation.png"
		}],
	"object": {
		"uuid": "984719E6-2B4F-4689-941A-7DA94E00B648",
		"type": "Scene",
		"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
		"children": [
			{
				"uuid": "2D6D4BF3-7339-42EE-BABD-AE677AE50C3B",
				"type": "DirectionalLight",
				"name": "DirectionalLight 1",
				"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,5,5.672201,7.5,1],
				"color": 16777215,
				"intensity": 1,
				"shadow": {
					"camera": {
						"uuid": "9DEBCE98-3B51-4192-AC50-7A91714EEA97",
						"type": "OrthographicCamera",
						"zoom": 1,
						"left": -5,
						"right": 5,
						"top": 5,
						"bottom": -5,
						"near": 0.5,
						"far": 500
					}
				}
			},
			{
				"uuid": "B7F4B1D6-5964-4B3E-920A-27C9C5DD54EC",
				"type": "Mesh",
				"name": "Plane 2",
				"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
				"geometry": "A189E19E-2A25-434D-8276-41FBCEF901D1",
				"material": "07FF37D9-AC9C-44FA-BFC2-BDC69854DD4E"
			},
			{
				"uuid": "C1AEF017-AFD9-406B-9084-BD2414360AE2",
				"type": "Mesh",
				"name": "Sphere 1",
				"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
				"geometry": "96CE9946-FDA3-412A-8AFC-ED7CDC25B087",
				"material": "07FF37D9-AC9C-44FA-BFC2-BDC69854DD4E"
			}],
		"background": 11184810
	}
}`

**Comment by WestLangley** [comment]
Can you please link to a simple live example to demonstrate each of your four claims?

**Comment by NNskelly** [comment]
I would prefer to use your own live editor as the demo platform, both since it removes any variables outside the particular json files being loaded in, and because I don't want to load up my company's webserver with public-facing sandbox content.  GitHub doesn't take json, and isn't liking the zips I'm trying to attach, but you can save out the following json yourself and import them to see what I'm seeing (may need to reload a couple times after import before the inlined texture is available to render, or replace the mapped images with the ones I'll also attach):

Claims 1 and 3: reflection is the same on both sides of a plane, and in fact, stays fixed to the camera irrespective of angle.  Import the JSON in the original post, which contains a unit sphere and a unit plane, both set to full smooth/metallic and using only an env map consisting of the R/G/B/C/M/Y test cube lat-long image.  Results shown in the first 3 screencaps.

Claims 2 and 4: env textures pinch at oblique edges; offset affects angle of most maps but not env map.  Import the following JSON, which contains the same sphere/plane but with an additional inwards-facing "skysphere."  You may need to manually apply the provided jungle image to all specified maps, since the internet doesn't like loading from an http source into a https context.  Offset effect can be observed by manually tweaking the offset property of both texture entries in the json- [0,0] shows green foliage in the skysphere from the default camera position; [0.5,0] shows a tree trunk and root in the skysphere, but the env sphere remains the same.  To observe the pinching, just delete Sphere 1 and dolly/zoom in on the Plane 1, and spin around to put the camera just off the X+, X-, Y+ and Y- axes.  Results shown in the 4th screencap.

![latlong_orientation](https://cloud.githubusercontent.com/assets/28572171/26325889/6b45f6c8-3efe-11e7-8e04-c20c1fefdf40.png)
![latlong_spherical_jungle](https://cloud.githubusercontent.com/assets/28572171/26325891/6d35f334-3efe-11e7-9718-21c327aa00bf.jpg)

![reflectiona](https://cloud.githubusercontent.com/assets/28572171/26326025/13ab0f38-3eff-11e7-891d-68fa97ccad2f.png)
![reflectionb](https://cloud.githubusercontent.com/assets/28572171/26326027/15fc0030-3eff-11e7-934a-a563d9abfbad.png)
![reflectionc](https://cloud.githubusercontent.com/assets/28572171/26326031/17bfb628-3eff-11e7-9c51-7f14d99ac619.png)
![oblique](https://cloud.githubusercontent.com/assets/28572171/26326032/19b5e31c-3eff-11e7-901a-28d83bf0eda6.png)

**Comment by NNskelly** [comment]
I finally dove into the actual shader code to attempt to rewrite the spherical sampling to do what I was expecting, only to find a version of what I was expecting is already implemented for a different category of mapping: EquirectangularReflectionMap.

If you are using the THREE.js editor to create content for a scene, this mapping is not directly selectable, but it can be set as a texture's mapping mode per https://threejs.org/docs/index.html#api/constants/Textures (which, at time of writing, unhelpfully describes all mapping modes self-referentially).  Alternatively, breaking into the JSON after export, you can set the `mapping` property manually to **303** as opposed to the default 300 (UV) or 305 ("Spherical," which I can only presently conjecture is intended for mirror ball photos).

**Comment by NNskelly** [comment]
that said, I would be curious to know why line 33 of envmap_fragment.glsl is
```
sampleUV.y = saturate( flipNormal * reflectVec.y * 0.5 + 0.5 );
```
rather than
```
sampleUV.y = asin( flipNormal * reflectVec.y) * RECIPROCAL_PI + 0.5;
```

It seems a bit odd that in a lat-long sampling, longitude/x would be normalized-angular but latitude/y would be a linear read/clamp...

**Comment by mrdoob** [comment]
> It seems a bit odd that in a lat-long sampling, longitude/x would be normalized-angular but latitude/y would be a linear read/clamp...

Agreed. Do you mind doing a PR with the change?

**Comment by NNskelly** [comment]
Done.  Ignore comments on identical result; I was looking in entirely the wrong place.  Still wouldn't be bad to get a second set of eyeballs on it before any merge, tho.
