### ISSUE TITLE
Examples: More usage of stats.js

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#11365]
It would be great if more examples of `three.js` would use [stats.js](https://github.com/mrdoob/stats.js/), a JavaScript performance monitor. Right now, the usage is not continuous. But information about fps or frametime are always valuable feedback.

The linked examples shows how `stats.js` should be integrated. Although it's not much code to add per file, it might need some time to work through all relevant examples.

https://threejs.org/examples/webgl_geometry_colors.html

**Comment by mrdoob** [comment]
Actually, I think I would hold on on this one. Now that we're entering the VR world, we may want to stop relying in the dom for this. And, maybe, invest that time in doing adding a fps/ms meter to the renderer instead.

Also, when profiling, having the fps meter sometimes gets in the way...

<img width="417" alt="screen shot 2017-05-22 at 10 27 05 am" src="https://cloud.githubusercontent.com/assets/97088/26320967/c08cd2de-3ed9-11e7-947a-5165a8250ea8.png">

**Comment by Mugen87** [comment]
Sounds reasonable 👍 . Avoiding dependencies to the DOM is a good strategy.

**Comment by Mugen87** [comment]
Should we still merge the PR of @shitian-ni if the pending change request are cleaned up?

**Comment by mrdoob** [comment]
Probably not... 😟
