### ISSUE TITLE
Broken blender export with animation (workaround)

### ISSUE THREAD

**Issue by xbeat** [mrdoob/three.js#11371]
Hi,
by exporting the marine model from Blender: (examples/models/skinned/marine/marine_anims_core.blend folder) there are no errors but nothing appears (the original json works perfectly), so after a little compare of the two files I modified the json file in the material section like below. I exported the model with the parameters as in the image and the model in 'TPOSE' position and the export has been successful. Hope it may be useful.

**Parameter modified:
"materials":[{
...
"blending":"NormalBlending", (removed this line)
"color":16777215, (was 8947848)
"transparent":false, (was true)
...
}],**

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [x] Safari
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
macbook pro
![threejs_export_params](https://cloud.githubusercontent.com/assets/20385856/26285284/f0d677de-3e4c-11e7-9b2b-b7a030da78bd.png)

**Comment by mrdoob** [comment]
> "blending":"NormalBlending", (removed this line)

🤔

**Comment by xbeat** [comment]
Changing in Blender these material parameters:

1) Diffuse: color to 1 1 1 (white)
2) Diffuse: intensity to 1 
3) Unckeck transparency
4) THREE: Blending tyoe = NoBlending

The export work fine.
