### ISSUE TITLE
Issue when setting camera.position to Vector3

### ISSUE THREAD

**Issue by kgoedecke** [mrdoob/three.js#11372]
##### Description of the problem 

I noticed that when setting the position for PerspectiveCamera to a THREE.Vector3 nothing is displayed, but when I directly set the values, it works just fine.
```
camera.position.set( 0, 0, 0 );
```
 works, but
```
var newVector = new THREE.Vector3(0, 0, 0)
camera.position.set(newVector);
```

doesn't. I was wondering if this is a bug?

See the following two JSFiddle:
L8-10: https://jsfiddle.net/4zqkn7yw/5/
L9: https://jsfiddle.net/4zqkn7yw/4/

##### Three.js version

- [x] r82

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
That's not a bug. Try this:
```javascript
var newVector = new THREE.Vector3( 0, 0, 0 )
camera.position.copy( newVector );
```
Have a look at the docs of [Vector3](https://threejs.org/docs/index.html#api/math/Vector3) in order to understand the API.

**Comment by WestLangley** [comment]
`Object3D`'s `position`, `rotation`, `quaternion` and `scale` properties are immutable.

See the source code file `Object3D.js`.

The following pattern is invalid:

    object.position = vector;

Instead, you must use either

    object.position.set( x, y, z );

or

    object.position.copy( vector );
