### ISSUE TITLE
Dynamic removal of lights (texture in memory)

### ISSUE THREAD

**Issue by XubeiX** [mrdoob/three.js#11387]
I want to dynamically remove and add different types of lights from the scene and everything works fine but when I create a lights with castShadow = true ThreeJS create a additianal Texture probably shadow map texture (light.shadow.map.texture). After removing such lights, the texture is not removed. I try to dispose() texture before remove the light, but it is not working, the texture still exist in memory. How can I fix this problem? 

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Can you please provide a simple, live example to show exactly what you are doing?

Usually we recommend you set use one of these patterns:
```
 light.visible = false;
 light.intensity = 0;
 light.layers.toggle( 0 );
```
What is your use case? Are you permanently removing the light?

**Comment by XubeiX** [comment]
Yes, I permanently removing the lights from the scene. 

I do it in the fallowing way:
1. I use ObjectLoader to load JSON file with lights setup (json is exported from blender). For SpotLights and PointLights I enable castShadow and keeps all lights in Array (lightsArray).

```javascript
sceneLoader.load(sceneObjectToLoad, function(sceneObjects){
	while(sceneObjects.children.length !== 0){
		var object = sceneObjects.children[0];
		if(object.type.toLowerCase().indexOf('light') !== -1){
			if(object.isSpotLight || object.isPointLight){
				object.shadow = new THREE.LightShadow(new THREE.PerspectiveCamera( 60,  1, 10, 550 ));
				object.castShadow = true;
				object.shadow.mapSize.width = 2048;
				object.shadow.mapSize.height = 2048;
			}

			lightsArray.push(object);
			scene.add(object);
		} else {
		sceneObjects.children.shift();
		}
	}	
```

2. When user change the lights setups. I remove all the lights from scene and I'm back to the 1st step to load another JSON file.

```javascript
function removeLights(){
	while(lightsArray.length !== 0){
		if(lightsArray[0].castShadow){
			lightsArray[0].shadow.camera = null; //my try to dispose  the texture
			lightsArray[0].shadow.map.texture.dispose();
			lightsArray[0].shadow.map.texture = null;
			lightsArray[0].shadow.map = null;
		}
						
		lightsArray[0].castShadow = false;
		scene.remove(lightsArray[0])
		lightsArray.shift();
	}
}
```

And this part of code work becouse the lights are removed. I check scene children's object and the light gone, objects becomes black . 

And how it's look on render stats.
1. Loading 1 object with 1 material ( and texture), no lights.
![only object](https://cloud.githubusercontent.com/assets/9266046/26439004/603dea18-4126-11e7-8c35-f534438acf9b.PNG)
2. Loadng light setup (JSON file contains 4 lights - PointLight, PointLight, SpotLight and RectAreaLight). I enable cast shadow on 3 of them.
![object with lights](https://cloud.githubusercontent.com/assets/9266046/26439056/a4d56336-4126-11e7-96fc-d7cc8c41fd10.PNG)
3. Switch to no lights again. Texture counter doesn't change. Object become black.
![object with lights](https://cloud.githubusercontent.com/assets/9266046/26439056/a4d56336-4126-11e7-96fc-d7cc8c41fd10.PNG)
4. Again loading lights (the same JSON files). Another 3 texture are loaded.
![2nd switch](https://cloud.githubusercontent.com/assets/9266046/26439119/ee217b88-4126-11e7-9ad1-aac105c14d11.PNG)

**Comment by mrdoob** [comment]
Could you create a jsfiddle?

**Comment by XubeiX** [comment]
I prepared jsfiddle: http://jsfiddle.net/txa8Lfy9/
In my case the user change the lights setup by HTML selector and I use AJAX to listen on change. 

```javascripr
	$("#lights-selector").change(function(){
		removeLights();
		getNewLightSetup(this.value);
	});
```

In jsfiddle I used setTimeout to simulate changes.

**Comment by mrdoob** [comment]
I think the solution for this one is to add a `dispose()` to `THREE.LightShadow` and let the user call it when needed.

**Comment by WestLangley** [comment]
@mrdoob Yes, all the user has to do is call:
```
light.shadow.map.dispose();
```

Similar to:
```
mesh.material.map.dispose();
```
So, I don't think we need to add anything...

However, would you prefer adding convenience methods -- `light.dispose()` or `light.shadow.dispose()`?

**Comment by WestLangley** [comment]
@XubeiX This should work for you:
```
function timeOutRemove() {

	setTimeout( function () {

		while ( lightArray.length != 0 ) {

			var light = lightArray[ 0 ];

			if ( light.shadow && light.shadow.map ) {

				light.shadow.map.dispose();

			}

  			scene.remove( light );
			lightArray.shift();

		}

	}, 5000 );

}
```

**Comment by XubeiX** [comment]
@WestLangley Thanks for the help, works. 😄
