### ISSUE TITLE
StereoEffect intersect object not working ?

### ISSUE THREAD

**Issue by tmdeft** [mrdoob/three.js#11383]
##### Description of the problem 
```
var vector = new THREE.Vector3(mouse.x, mouse.y, 0.5);
    projector.unprojectVector(vector, camera);
var ray = new THREE.Raycaster(camera.position, vector.sub(camera.position).normalize());
var intersects = ray.intersectObjects(objectList, true);
```
Why Intersect object not working ?

##### Three.js version
- [ ] Dev
- [ ] r85
- [x] r69

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by WestLangley** [comment]
three.js r.69 is 3 years old. It would be wise to update to the current version.

See [this SO post](https://stackoverflow.com/a/41609683/1461008).
