### ISSUE TITLE
Bump version to 1.0.0

### ISSUE THREAD

**Issue by NameFILIP** [mrdoob/three.js#11396]
"If a project is going to be shared with others, it should start at 1.0.0, though some projects on npm don't follow this rule." - https://docs.npmjs.com/getting-started/semantic-versioning

npm dependency resolution behavior for `^1.2.0` and for `^0.2.0` is different. If the major version is 0, the caret will not pull the next minor version, which means previous versions will resolve to `1.3.0`, but not `0.3.0` (you can try it here https://semver.npmjs.com/). 

Otherwise, it's easy to end up with multiple versions of the same library in the bundle, and taking into account the size of three.js, it bloats the size of the bundle significantly.

**Comment by mrdoob** [comment]
Here's some discussion we had 4 years ago: #3102

**Comment by NameFILIP** [comment]
I guess that's not going to change 😢
