### ISSUE TITLE
Viewport clipped on Android

### ISSUE THREAD

**Issue by edsilv** [mrdoob/three.js#11390]
I'm seeing an issue in Chrome 58.0.3029.83 on Android 7.0.0 where the visible viewport is getting clipped.

Here's: https://threejs.org/examples/#webgl_animation_cloth

![screenshot_20170525-132558](https://cloud.githubusercontent.com/assets/1334393/26452523/29608c08-4158-11e7-9a33-ba604a2d5d45.png)

And https://threejs.org/examples/#webgl_camera:

![screenshot_20170525-132547](https://cloud.githubusercontent.com/assets/1334393/26452565/488e4002-4158-11e7-95cf-f9955534b166.png)

My own application is also exhibiting this problem:

![screenshot_20170525-132615](https://cloud.githubusercontent.com/assets/1334393/26452594/6abf63f4-4158-11e7-9c4a-a85986895388.png)

Some other examples are fine however:

https://threejs.org/examples/#webgl_clipping
https://threejs.org/examples/#webgl_loader_obj

Unable to discern the difference between these cases...

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Nexus 6 phone

**Comment by gauravrane** [comment]
They are working on it, it has nothing to do with a specific device or OS version.
[#11368](https://github.com/mrdoob/three.js/issues/11368)

**Comment by edsilv** [comment]
Closing as duplicate of #11368
