### ISSUE TITLE
Jumpy shadow

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#11394]
https://fiddle.jshell.net/hgcxt89k/3/

the cube goes up and down, the shadow does jumpy-jumpy.

**Comment by makc** [comment]
upping spotLight.shadow.mapSize.width/height makes it jump in smaller steps and also removes shadow softness

**Comment by mrdoob** [comment]
Not a bug. Try this:

```js
renderer.shadowMap.type = THREE.BasicShadowMap;
```

You'll see actual depth texture more clearly and I think you'll understand what's happening.

**Comment by makc** [comment]
@mrdoob default texture is supposed to be 512 pixels, and that camera helper makes it look like it's 64 pixels instead

**Comment by mrdoob** [comment]
The actual bug is that the `CameraHelper` doesn't really match the camera.

If we reduce the `angle` the depth map feels more 512ish.

```js
var spotLight = new THREE.SpotLight( 0xffffff, 1.2, 3000, Math.PI/8, 0, 2);
```

https://fiddle.jshell.net/hgcxt89k/5/

**Comment by mrdoob** [comment]
Actually, if you add `helper.update();` in the animate function, the helper looks better.

https://fiddle.jshell.net/hgcxt89k/6/

**Comment by mrdoob** [comment]
@Mugen87 @WestLangley this is a good example of why I'm suggesting using `onBeforeRender` in helpers.
