### ISSUE TITLE
Dynamic attributes can't be resized

### ISSUE THREAD

**Issue by michalburger1** [mrdoob/three.js#11397]
##### Description of the problem 

When using dynamic attributes, if you update the attribute with a new array that's larger than the previous one, three.js fails to resize the GPU buffer and draw calls will fail with out of range errors.

```javascript
var attribute = new THREE.BufferAttribute( shortArray, 3 );

// later on

attribute.setArray( longerArray );
attribute.needsUpdate = true;
```

Fiddle: http://jsfiddle.net/zvt9oumy/

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Should be hardware independent but this is where I tested it:
- Chrome 58 64-bit, Firefox 53 64-bit
- Windows 10
- NVIDIA Titan X

**Comment by michalburger1** [comment]
I'm no WebGL expert but I think the fix should be as easy as adding an appropriate bufferData call just before the bufferSubData call:

```
+ gl.bufferData( bufferType, array.byteLength, gl.DYNAMIC_DRAW );
  gl.bufferSubData( bufferType, 0, array );
```

https://github.com/mrdoob/three.js/blob/afb0dd4a4937d877c143fe7e9b7ea937c3f79eb5/src/renderers/webgl/WebGLAttributes.js#L81

**Comment by michalburger1** [comment]
In the meantime, can anyone think of any way to manually call `bufferData` on my attribute?

**Comment by michalburger1** [comment]
Replying to myself: I don't think there's any way to do this but calling `geometry.dispose()` and then recreating everything with new attributes a frame later[1] seems to work.

[1] My attributes are large and doing everything in the same frame tends to OOM webgl. I'm not really sure why waiting one frame fixes it though.

**Comment by makc** [comment]
why dont you have max size attribute and some sort of 1/0 values to turn extra values on/off

**Comment by michalburger1** [comment]
Because that would waste memory, I'd like to allocate more memory only when it's needed.

**Comment by Mugen87** [comment]
The buffer size of a `BufferAttribute` is fixed. Read the following manual page (section `BufferGeometry`) for more information:

https://threejs.org/docs/index.html#manual/introduction/How-to-update-things
