### ISSUE TITLE
soft shadows that blur/fade with the distance?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#11392]
Just saw [this tweet](https://twitter.com/Domenico_brz/status/867470065066799104) today and thought to myself, why doesnt 3js have something like this ootb? I must say, I have poor idea how do 3js shadows work, but I can imagine this is not too hard to do. For example: http://jsfiddle.net/hfj7gm6t/3878/ :D Can we have something like this, please?

**Comment by makc** [comment]
Waaaait, looking at http://developer.download.nvidia.com/shaderlibrary/docs/shadow_PCSS.pdf isn't that exactly what THREE.PCFSoftShadowMap should do...

**Comment by makc** [comment]
However, it does not do that at all. Here https://fiddle.jshell.net/hgcxt89k/2/ not only blur does not change with cube-plane distance, the shadow is also jumpy. Perhaps an old 3js version?

**Comment by makc** [comment]
Nnope, https://fiddle.jshell.net/hgcxt89k/3/ current build behaves exactly the same

**Comment by Mugen87** [comment]
@makc Can you please file a new issue for this problem? In this way we can separate your enhancement request and the bug.

**Comment by makc** [comment]
@Mugen87 I think it's actually the same issue. Because if PCFSoftShadowMap were behaving as in the pdf, I would have no reason to ask for anything

**Comment by Mugen87** [comment]
I was thinking more of the jumpy shadow 😉

**Comment by makc** [comment]
@Mugen87 #11394 here you go

**Comment by WestLangley** [comment]
Shadows in three.js are implemented as the absence of light. Shadows do not fade with distance.

Instead, the surrounding illuminated area darkens with distance -- as it should -- assuming the user has set the light parameters correctly. That darkening may give the illusion that the shadow is fading.

**Comment by mrdoob** [comment]
#8933

**Comment by makc** [comment]
@WestLangley 
> Shadows do not fade with distance.

but you have area lights, no? how do shadows work with those?

**Comment by mrdoob** [comment]
`AreaLight` does not support shadows yet.

**Comment by makc** [comment]
ok so closing until they do then
