### ISSUE TITLE
GLTF2 loader bug

### ISSUE THREAD

**Issue by tallpeca** [mrdoob/three.js#11405]
##### Description of the problem 

While trying to load this GLTF [ventil.zip](https://github.com/mrdoob/three.js/files/1033691/ventil.zip) I am getting following error in console: 
`Uncaught (in promise) TypeError: Cannot read property 'Attribute13' of undefined
    at GLTF2Loader.js:2040
    at _each (GLTF2Loader.js:892)
    at GLTF2Loader.js:2009
    at <anonymous>
(anonymous) @ GLTF2Loader.js:2040
_each @ GLTF2Loader.js:892
(anonymous) @ GLTF2Loader.js:2009
GLTF2Loader.js:2040 Uncaught (in promise) TypeError: Cannot read property 'Attribute13' of undefined
    at GLTF2Loader.js:2040
    at _each (GLTF2Loader.js:892)
    at GLTF2Loader.js:2009
    at <anonymous>
(anonymous) @ GLTF2Loader.js:2040
_each @ GLTF2Loader.js:892
(anonymous) @ GLTF2Loader.js:2009`

File was exported automatically using Ansys 18 software, therefore i would expect it is correct. If export is incorrect, identifying data fix workaround would be greatly appreciated. Thank you!

Full gltf package including .bin files and shareds can be found here [ventil-full.zip](https://github.com/mrdoob/three.js/files/1033698/ventil-full.zip)

##### Three.js version

- 0.85.2

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by cx20** [comment]
There is no version information (asset.version) in this glTF model.
As a result, this model may be in the form of a version earlier than glTF 1.0.
Relate: https://github.com/KhronosGroup/glTF/wiki/glTF-0.8-to-1.0-Guide
