### ISSUE TITLE
startIndex of setupVertexAttributes() is never passed with any useful value

### ISSUE THREAD

**Issue by stonexjr** [mrdoob/three.js#11406]
##### Description of the problem 

[Here](https://github.com/mrdoob/three.js/blob/afb0dd4a4937d877c143fe7e9b7ea937c3f79eb5/src/renderers/WebGLRenderer.js#L797) in the WebGLRenderer, the startIndex argument of setupVertexAttributes() is missing, hence, at [line 921](https://github.com/mrdoob/three.js/blob/afb0dd4a4937d877c143fe7e9b7ea937c3f79eb5/src/renderers/WebGLRenderer.js#L921), it will always be 0 by default.
The startIndex parameter is not need anymore?

##### Three.js version

- [ ] Dev
- [X] r85
- [ ] ...

**Comment by mrdoob** [comment]
Yeah, I don't think we support that yet?

**Comment by Mugen87** [comment]
see #13631
