### ISSUE TITLE
Three.js Objectloader (json) get only one material.

### ISSUE THREAD

**Issue by xbeat** [mrdoob/three.js#11426]
##### Description of the problem 

Exporting  [this file](https://sport.xbe.at/jsonPlayer/Player_animated_separated.blend) from Blender [this animation](https://sport.xbe.at/jsonPlayer/index.html) in three.js format i get only one material i checked the [[json file](https://sport.xbe.at/jsonPlayer/Player_animated_separated.json)] and all the images, textures and material are present.

Images:

    "images":[{
        "uuid":"B55D670C-B4A2-4236-A54D-AB4BBCA1F94A",
        "name":"Body_Diffuse.png",
        "url":"Body_Diffuse.png"
    },{
        "uuid":"9A03D391-22CD-4A14-B34A-1C081781368F",
        "name":"Uniform_Diffuse.jpeg",
        "url":"Uniform_Diffuse.jpeg"
    }], 

Textures and materials:

    "textures":[{
        "uuid":"B5BB2AC1-36E3-46AA-89BF-48441AB87093",
        "anisotropy":1,
        "magFilter":1006,
        "name":"Body",
        "repeat":[1,1],
        "wrap":[1000,1000],
        "mapping":300,
        "image":"B55D670C-B4A2-4236-A54D-AB4BBCA1F94A",
        "minFilter":1008
    },{
        "uuid":"C1E9BDEC-66D4-4B7B-8322-1F8F57DBBD82",
        "anisotropy":1,
        "magFilter":1006,
        "name":"Uniform",
        "repeat":[1,1],
        "wrap":[1000,1000],
        "mapping":300,
        "image":"9A03D391-22CD-4A14-B34A-1C081781368F",
        "minFilter":1008
    }],
    "materials":[{
        "uuid":"F67DB6D7-C163-4C21-8C71-707DAC1121CA",
        "shininess":50,
        "skinning":true,
        "name":"Body",
        "map":"B5BB2AC1-36E3-46AA-89BF-48441AB87093",
        "emissive":0,
        "vertexColors":0,
        "specular":8355711,
        "depthTest":true,
        "depthWrite":true,
        "type":"MeshPhongMaterial",
        "blending":"NoBlending",
        "color":13421772
    },{
        "uuid":"3FB56826-347F-4798-9FAC-D91F6C42983F",
        "shininess":50,
        "skinning":true,
        "name":"Uniform",
        "map":"C1E9BDEC-66D4-4B7B-8322-1F8F57DBBD82",
        "emissive":0,
        "vertexColors":0,
        "specular":8355711,
        "depthTest":true,
        "depthWrite":true,
        "type":"MeshPhongMaterial",
        "blending":"NoBlending",
        "color":13421772
    }],

But i get only (console.log) the last object "Uniform"
![But i get only (console.log) the last object "Uniform".](https://cloud.githubusercontent.com/assets/20385856/26641950/651669ce-462c-11e7-85ae-b0cdb08cc8a3.png)

Parameters used for exportation
![Parameters used for exportation](https://cloud.githubusercontent.com/assets/20385856/26641984/804e95ae-462c-11e7-9ea1-bb825224396a.png)

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [x] Safari
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by mrdoob** [comment]
Can you try exporting `BufferGeometry`?

**Comment by xbeat** [comment]
Using Type: BufferGeometry i get 'mesh === undefined'

**Comment by tomjohnson3** [comment]
Here's a data point (with same three.js version, etc.etc.):

I encountered the same issue, and, after inspecting my JSON file, I manually changed my Mesh object's "material" from a single UUID string (from the exporter) to an array of UUID strings - and that worked.

...for me, the Mesh was in object.children[0].children[0] ...so I changed this:

`"material":"AFD6AD39-ADAC-44BF-B625-96B080476A14",`

to this:

`
"material":[
   "AFD6AD39-ADAC-44BF-B625-96B080476A14",
   "D1ECC17E-6A1C-4EB0-BD49-A50167436902",
   "B0416C26-B6EB-41EB-BE7D-E4AEAC2549E2",
   "20143C80-7F9C-4616-9DA1-2AC18DEC3069",
   "8EAC11D7-3305-463D-A8B2-4F6D4F6711F9",
   "E5DD9C5E-97E1-45FC-AA86-C9E6AF712E19",
   "800CA968-D95A-4CAA-B8DF-1C3AA97A5B85"
],
`

NOTE: for me, it was important to match the order of the UUIDs in `geometries[0].materials`.

I'm hoping to have some time to dig into the Blender exporter and see if I can fix this. ...though I can't promise I'll be able to, as I'm not sure how complex the exporter is...and my Python is a bit rough. ;-)

**Comment by tomjohnson3** [comment]
Hmmm - after taking a look at the exporter, I'm not sure even where to start fixing this (without perhaps breaking something else).

**Comment by tomjohnson3** [comment]
Well, unfortunately, I'm having trouble repeating what I did to fix this issue...so there's something else going on. Now, regardless of how I update the "material" value, there's only a single material applied to the entire Mesh (the first material).

**Comment by manthrax** [comment]
#11793

**Comment by developer-lindner** [comment]
@xbeat How do you get the images set in the json-File? I don't get to work properly.. May someone have a look please? 

https://stackoverflow.com/questions/46585252/threejs-objectloader-materials-not-rendered-from-exported-json-file-blender

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
