### ISSUE TITLE
WebGL-compatibility-check.html & Creating-a-scene.html Nit Picking

### ISSUE THREAD

**Issue by topherbuckley** [mrdoob/three.js#11421]
##### Description of the problem 
In the WebGL-compatibility-check.html, shouldn't the init() and animate() functions be changed to match the methods used in Creating-a-scene.html? Using the instructions in WebGL-compatibility-check.html directly after going through the Creating-a-scene.html tutorial results in an undefined init() function. For those trying to learn three.js, I think this is confusing.  

So I recommend deleting the init() and replacing with comment "// Initialize anything here"

and renaming the animate() function to render() to match that used in the Creating-a-scene.html. Unless this animate() function is referring to something else, but even then, I think this causes unnecessary confusion to those going through the tutorials such as myself. Or maybe the render() function in Creating-a-scene.html should be renamed animate()? 

If the function names matched up and the init() function removed, one could move directly from the first tutorial to the next without any errors or troubleshooting. 

I could make a formal PR for both pages including these changes if you think this would be helpful. 

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Good point.
```
var animate = function () {

	requestAnimationFrame( animate );

	cube.rotation.x += 0.1;
	cube.rotation.y += 0.1;

	renderer.render( scene, camera );

};

animate();
```
