### ISSUE TITLE
CSS3DRenderer and Meshes

### ISSUE THREAD

**Issue by jaygarcia** [mrdoob/three.js#11429]
I know that this is not an issue specifically in ThreeJS proper, but given that @WestLangley is not active on twitter, I don't know how else to reach him.

Seems that there were some examples posted years ago that demonstrated how to render Meshes with an experimental CSS3DRenderer, but the dropbox files have since been deleted.

https://stackoverflow.com/questions/22388934/can-three-jss-css3drenderer-render-meshes

I was hoping someone had the source code so that I could look and see how faces were being placed on the vertices for the geometry. 

Sorry for the noise :(

**Comment by WestLangley** [comment]
OK. I reconstituted it. It is a version of `CSS3DRenderer` compatible with three.js r.65. I hacked it to support morphs, lights, and shading. [Renderer source](https://github.com/WestLangley/three.js/blob/dev-css/examples/js/renderers/CSS3DRenderer.js).

I expect performance can be improved, but I did not pursue it further.

[Demo](https://rawgit.com/westlangley/three.js/dev-css/examples/css3d_morphtargets_horse.html)

![screen shot 2017-05-31 at 6 17 47 pm](https://cloud.githubusercontent.com/assets/1000017/26656751/667eebea-462e-11e7-80ab-4a67751abd8a.png)

**Comment by Mugen87** [comment]
Cool! 👍
