### ISSUE TITLE
How do you allow dragging with fingers on mobile?

### ISSUE THREAD

**Issue by omarel1** [mrdoob/three.js#11428]
Is there a way to allow for touch drag. The drag doesn't work on mobile devices.

**Comment by jaygarcia** [comment]
It works for some examples. /shrug 
![threejs](https://cloud.githubusercontent.com/assets/180031/26651414/9c86e706-461a-11e7-91da-0346f0241ca4.gif)

**Comment by pailhead** [comment]
Allow touch drag on what? How is this a three.js thing?

**Comment by xbeat** [comment]
[Example](https://sport.xbe.at/jsonPitch/index.html) using orbitControls:
#### With Mouse
click Mouse Left & drag = rotate
mousewheel = zoom
click Mouse Right & drag = pan 
### Mobile
touch & drag = rotate
pinch = zoom (in out)
three finger = pan
