### ISSUE TITLE
GL Context Lost - preventDefault

### ISSUE THREAD

**Issue by leweaver** [mrdoob/three.js#11435]
##### Description of the problem 

The [updated WebVR 1.1 specification ](https://w3c.github.io/webvr/spec/1.1/#dom-vrdisplay-requestpresent) has provisions for multi-GPU systems, which rely on correct usage of the webglcontextlost and webglcontextrestored events, or, the page not handling the events at all.

* note, that due to a documentation build issue, you may need to look at the source [spec bikeshed file](https://github.com/w3c/webvr/blob/master/spec/1.1/index.bs) - search for '_context will be lost_'.

Currently three.js handles the event webglcontextlost, calling `event.preventDefault` to inform the browser that it intends to handle the webglcontextrestored event, yet makes no attempt to rebuild the resources (nor handle that event). Further, `resetGLState()`, `setDefaultGLState()` etc should actually occur in a webglcontextrestored.

Until such a time as three.js can confidently handle the webglcontextrestored event (such as building on the method proposed in issue #5507) handling of context lost should be removed entirely - or at the very least, not make a call to `event.preventDefault()` in the event handler.

From three.js WebGLRenderer.js:538
```
	function onContextLost( event ) {
		// LW: Remove this until glcontextrestored is handled correctly
		event.preventDefault();

		// LW: Below here should actually be in glcontextrestored
		resetGLState();
		setDefaultGLState();

		properties.clear();
		objects.clear();

	}
```

##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Multi GPU system (such as a laptop, or a machine with motherboard integrated graphics and a discrete adapter)
VR Headset plugged in to discrete GPU
Monitor plugged in to integrated motherboard graphics

**Comment by toji** [comment]
To expand on what @leweaver said: We've also determined that the next revision of WebVR (which should be the one that sticks around) will have forced context loss as a core concept of using WebGL with a VR device. [Pull request here.](https://github.com/w3c/webvr/pull/226)

The TL;DR version is that contexts used with WebVR devices will need to have a compatibility bit set on them. You can do this two ways. First, with a context creation arg, like so:

```js
let gl = glCanvas.getContext("webgl", { compatibleVrDevice: vrDevice });
```

This won't cause context loss, but may not be appropriate if you don't know ahead of time that the user will be using a specific `VRDevice`. The second method is a bit more disruptive:

```js
let gl = glCanvas.getContext("webgl");

// Some time later...
gl.setCompatibleVrDevice(vrDevice).then(() => {
    // If the VRDevice is connected to a different GPU than the one
    // the WebGL context was created with this would have forced
    // a context loss. The promise only resolves when the context
    // has been restored. If the page doesn't handle it the promise
    // is rejected.
});
```

Obviously the context loss case won't be triggered every single time, and many devices (such as mobile) may never see a context loss. But devices with multiple GPUs (even laptops with an integrated/discreet pair) could hit this path frequently.

Ideally Three.js can provide some mechanisms for dealing with context loss and promote it as something that developers need to pay attention to, otherwise you'll get a lot of devs who test their content on a single-GPU system and say "It Works!" and then wonder why things fail on some systems when their content is released in the wild.

**Comment by mrdoob** [comment]
Okay. Basic support added. Works in most of the cases but a few things break when restored (sprites, lensflares, etc). I'll be fixing them over the next days.

**Comment by kenrussell** [comment]
This is great news!

**Comment by Icerion777** [comment]
Hi mrdoob how can I restore everything in my project to before "WebGL has hit a snag" ? Thank you!

**Comment by mrdoob** [comment]
@Icerion777 I don't think so...

**Comment by mrdoob** [comment]
Ok, after b317394ef3ebee642cec0e5e38badcc9137ea266, 5e661c2b3022ba7d9313cd2ae2d0976ab3d6cf4d, 79c14c8fd0f01a123306fac15742871636305124 and f6392b404c19e560cff3f04a0f9c70d7df012fe3 this should now be working.

**Comment by makc** [comment]
@mrdoob let's say I have a cube map that is rendered once and then used somewhere; now if I subscribe to 'webglcontextrestored' on canvas - will I have all the resources ready in order to re-render the cube map? do I also need to render() the scene to handle needUpdate=true stuff 1st? give us tutorial :D

**Comment by mrdoob** [comment]
Good question. If you setup a jsfiddle I'll adapt it to make it work 😊

**Comment by makc** [comment]
@mrdoob https://jsfiddle.net/hfj7gm6t/4282/

**Comment by mrdoob** [comment]
@makc 

Basically, the user will have to take care of some things:

```js
renderer.domElement.addEventListener( 'webglcontextrestored', function () {

	cubeCamera.updateCubeMap( renderer, scene );

} );
```

https://jsfiddle.net/hfj7gm6t/4284/

**Comment by mrdoob** [comment]
@leweaver 🙌

**Comment by dirttech** [comment]
I am still getting this webgl_context_lost error after some time. It happens randomly and its frequency also depends on machine to machine. I am using below snippet  - 
`renderer.domElement.addEventListener('webglcontextlost', function(e) {
        setTimeout(renderer.forceContextRestore, 100);
});`

But it doesn't seem to solve the problem. @mrdoob

**Comment by makc** [comment]
@mrdoob I tried to upgrade the fiddle https://jsfiddle.net/023byLzq/ but it does not seem to work any more 😭

**Comment by Mugen87** [comment]
There was some legacy code. Try it with https://jsfiddle.net/a6n1bc2v/

**Comment by Mugen87** [comment]
Is this correct? https://jsfiddle.net/jfnvaxy7/

**Comment by makc** [comment]
@Mugen87 not for me, it just freezes on loss and never starts moving again

**Comment by makc** [comment]
I get this in the console, maybe it is relevant:
![Uploading Screen Shot 2021-08-29 at 16.36.22 .png…]()

**Comment by Mugen87** [comment]
What system are you using?

On my Windows 10 notebook with Chrome 92.0.4515.159 I see no console warnings at all.

**Comment by makc** [comment]
@Mugen87 it used to work 4 years ago on the same system 😭 it is macosx + firefox

**Comment by makc** [comment]
> it used to work 4 years ago

actually... I just [tried](https://jsfiddle.net/wxrdLa2v/) with [r94](https://github.com/mrdoob/three.js/releases?after=r96) that should have been used at July 19-th, 2017, and it also fails, so it must be a browser issue

**Comment by makc** [comment]
@Mugen87 I just tried this on win10 machine (specifically, your fiddle fork) and it does work without warnings for me as well (aside from restore handler taking too many ms) BUT, in most of the button clicks results the cube map comes out half-black. This is the same as what I see here in my "broken" firefox if I switch to another tab and then go back to jsfiddle :(

**Comment by Mugen87** [comment]
I have tested again and indeed after a few tries it seems only parts of the cubemap are getting rendered. Sometimes the cubemap completely black. Sometimes it works. 🤔 .

**Comment by makc** [comment]
@Mugen87 [this tweak](https://jsfiddle.net/ks9r3eht) will probably completely fix it on windows

**Comment by Mugen87** [comment]
That is of course the right fix! And it explains the different outcomes of the previous version. Depending on the torus knot's transformation, certain renderings of the cube camera were occluded by the mesh.
