### ISSUE TITLE
DirectionalLightHelper not pointing along directional light direction when DefaultUp is set to z-up

### ISSUE THREAD

**Issue by manthrax** [mrdoob/three.js#11437]
##### Description of the problem 

The DirectionalLightHelper, doesn't seem to be aiming down the correct direction vector of the light it is assigned to.

Additionally, DirectionalLightHelper breaks when pointing down the DefaultUp axis set to z-up.

This is related to:
https://github.com/mrdoob/three.js/issues/11241

Explanation:

First I set Object3D.DefaultUp.set(0,0,1)

Then I make a DirectionalLight, and a DirectionalLightHelper moving along the X axis, to eventually line up looking down the Z (DefaultUp) axis.

http://jsfiddle.net/5wgjvLnz/19/

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/11436#issuecomment-308279481
