### ISSUE TITLE
Support for textureOffset in three.js?

### ISSUE THREAD

**Issue by rkwright** [mrdoob/three.js#11439]
_My apologies for what IS a question, but I asked the question on stackoverflow and got one response and while nice enough, he didn't know the answer either._

The question (and all the details) on stackoverflow is [here](https://stackoverflow.com/questions/44314917/glsl-compiler-choosing-wrong-overloaded-function?noredirect=1#comment75670490_44314917).
 
It appears that the GLSL compiler used by three.js on OSX/Chrome/Firefox doesn't support textureOffset.  Is this correct?  If so, will the newer version of WebGLRenderer 2 support it?  Or is there some other way to solve my problem?

##### Three.js version

- [ ] Dev
- [x ] r85
- [ ] ...

##### Browser

- [] All of them
- [x ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x ] macOS 10.12.5, MacBookPro
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
N/A

**Comment by manthrax** [comment]
textureOffset is only specified in OpenGL 4. WebGL is OpenGL ES2.

That said, THREE.js does support offsetting a texture, out of the box, by setting texture.textureOffset.

**Comment by rkwright** [comment]
Thanks for the answer.  However, a JavaScript API for offsetting the texture doesn't help me.  I need the shader-level setting.  I'll figure out another way to do it.  Thanks

**Comment by manthrax** [comment]
Cool. Good luck!
