### ISSUE TITLE
IE:  An extra object in data.children in ObjectLoader.parseObject

### ISSUE THREAD

**Issue by LebedenkoN** [mrdoob/three.js#11432]
The problem occure while parsing json file for userDefined model. In ObjectLoader.parseObject in Internet Explorer while iterating over children there is an extra child "includes". 
`for ( var child in data.children ) {
object.add( this.parseObject( data.children[ child ], geometries, materials ) );
}`

##### Three.js version

- [ ] Dev
- [ ] r85
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Flur** [comment]
That would be great!

**Comment by mrdoob** [comment]
Where does "includes" come from?

**Comment by makc** [comment]
probably for...in uses larger set of keys than just numbers, includes is probably array's method name

**Comment by LebedenkoN** [comment]
@mrdoob "includes" come from Array.prototype, and for avoiding this kind of issue there can be two ways:

- add checking  for `hasOwnProperty`:
`for ( var child in data.children ) {`
 `if (data.children.hasOwnProperty(child)) object.add( this.parseObject( data.children[ child ], geometries, materials ) );`
` }` 
but this fix can slow down the iteration over array in cases when `data.children.length` is quite big

- resolving this issue as I have suggested in Pull Request
