### ISSUE TITLE
THREE.RayCaster not working for THREE.SkinnedMesh

### ISSUE THREAD

**Issue by henryJack** [mrdoob/three.js#11434]
##### Description of the problem 

I have added a new skinned mesh to a scene but Ray casting doesn't seem to work. 

Is this an issue or a known limitation of using `THREE.SkinnedMesh`? 

Does the issue lie within the `RayCaster` or the `SkinnedMesh`?

Thank you for writing such a fantastic framework!

##### Three.js version
- [ ] r85

##### Browser
- [ ] Chrome

##### OS
- [ ] Windows

**Comment by henryJack** [comment]
Sorry, after searching again I have found the open issue `https://github.com/mrdoob/three.js/issues/6440`. Could the branch made by @makc be merged into the mainline? Raycasting for SkinnedMeshes would be extremely useful.

**Comment by Mugen87** [comment]
Please resume the conversation in #6440
