### ISSUE TITLE
Documentation for the Editor

### ISSUE THREAD

**Issue by Snookid** [mrdoob/three.js#11443]
This may sound like a request for a help but it could also fall under Feature Request for a documentation for Editor. I've been looking for a documentation of the API/methods for the editor and I can't seem to find it.

What I'm trying to do is add a custom Object under default Add menu or change default Grid steps and sizes or something basic as change the camera to Ortho. These things can be done Three.js, however for editor, it usually requires some extra API/methods, like `editor.execute( New AddObjectCommand( obj ) );` or methods related to signals.

Spent entire 2 weekends reading and searching for methods. I find one but then again, after a while when I try to do something new like say loading json I need to scour through the files and search for Loader methods for editor.

Is there a doc for editor or request even for the basic tasks would be great?!

**Comment by cacho** [comment]
Theres some documentation here: https://github.com/mrdoob/three.js/blob/dev/editor/docs/Implementing%20additional%20commands%20for%20undo-redo.md
@Snookid this not what you where looking for?

**Comment by mrdoob** [comment]
Someone wrote this:
https://gist.github.com/rotoglup/e6b79a5c5a4b47d6684c473b42bde235

**Comment by Mugen87** [comment]
An official technical documentation about editor's code architecture seems out of scope to me. TBH, the used patterns are common and the code base itself isn't large. Interested developers should be able to get an overview in a manageable amount of time.

**Comment by mrdoob** [comment]
I think that gist solved the issue actually.
