### ISSUE TITLE
Clock.getElapsedTime() should be decoupled from Clock.getDelta()

### ISSUE THREAD

**Issue by spbond** [mrdoob/three.js#11444]
##### Description of the problem 

Currently, the getElapsedTime() method in the Clock class depends on the getDelta() method.  This leads to unintuitive behavior and performance costs.  

Calling Clock.getElapsedTime() calculates the delta even though it is not used, and causes the behavior of Clock.getDelta() to depend on whether it is called before or after Clock.getElapsedTime().
If the user wishes to reset the delta to 0, then they should either call Clock.getDelta() or a resetDelta() method should be added.

Calling Clock.getDelta() calculates a new elapsed time even though it may not be needed.  Also, elapsedTime += diff is less accurate than elapsedTime = newTime - startTime.

Finally, decoupling the functions will allow you to remove the elapsedTime property, which could lead to bugs if it is unintentionally altered.

The changes I propose ( with a couple minor performance improvements ) are as follows:

```
getElapsedTime: function () {
	if ( this.running ) {
		return ( ( performance || Date ).now() - this.startTime ) * .001;
	}

	if( this.autoStart ) {
		this.start();
	}

	return 0;
}
```
```
getDelta: function () {
	if ( this.running ) {
		var newTime = ( typeof performance === 'undefined' ? Date : performance ).now();
		var diff = ( newTime - this.oldTime ) * .001; // Trivial, but slightly faster than / 1000
		this.oldTime = newTime;

		return diff;
	}

	// Putting this here reduces the number of branch tests for the most common case
	if ( this.autoStart ) {
		this.start();
	}

	return 0;
}
```

As an aside, the performance or Date object could be saved as a property at creation, and you would not have to test for it every time.

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
see #5696

**Comment by spbond** [comment]
I would argue that this issue is still valid, since the commit proposed in #5696 does not decouple getElapsedTime() from getDelta().  In that commit, getElapsedTime() still calls getDelta() which makes the behavior order dependent.

However, reviewing it revealed to me that my suggestion doesn't report the expected value for elapsed time when the clock is stopped.  This can be addressed with a simple change while still keeping the 2 functions decoupled:

```
stop: function () {
	// Autostart should never be triggered by stop(), so we can't use getElapsedTime() here.
	if ( this.running ) {
		updateElapsedTime();
		this.running = false;
	}
}

getElapsedTime: function () {
	if ( this.running ) {
		updateElapsedTime();
	}
	else	if( this.autoStart ) {
		this.start();
	}

	return this.elapsedTime;
}

updateElapsedTime: function() {
	this.elapsedTime =  ( ( performance || Date ).now() - this.startTime ) * .001;
}
```

**Comment by Mugen87** [comment]
The issue #5696 is still open, so i think would make more sense to resume the discussion there.

**Comment by spbond** [comment]
Fair enough, do I need to repost my comments in the other thread?

**Comment by Mugen87** [comment]
I think it would make sense if you post a short summary of your content. The issue itself is already linked.
