### ISSUE TITLE
IE11: 'Uint8ClampedArray' is undefined

### ISSUE THREAD

**Issue by luruke** [mrdoob/three.js#11440]
Hello, starting from r85 threejs seems broken on IE11 (via browserstack at least).

The problems seems to be here:
https://github.com/mrdoob/three.js/blob/49071e5a7770de3bf505705fc593abf2e13bc0af/src/loaders/BufferGeometryLoader.js#L96

<img width="1432" alt="screen shot 2017-06-03 at 16 44 32" src="https://cloud.githubusercontent.com/assets/61326/26754536/dce2ba50-487c-11e7-9392-1420775651ee.png">

Anyone has the same problem?

##### Three.js version

- [x] Dev
- [x] r85
- [ ] r84

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by luruke** [comment]
Apparently the support for `Uint8ClampedArray` as been introduced in the build `KB2929437` from microsoft: https://support.microsoft.com/en-us/help/2929437/description-of-the-security-update-for-internet-explorer-11-on-windows-7-and-windows-server-2008-r2-april-8,-2014

That means that the bug should be reproduced just in older build of IE11.

**Comment by Mugen87** [comment]
I'm not sure it is appropriate to provide a fix here. The mentioned IE11 update is from 2014, right? That's pretty old. I think users need to upgrade their browser if they actually run into this problem.

@luruke Is this possible in your case?

BTW: We also use `Uint8ClampedArray` also in `src/core/BufferAttribute.js`.

**Comment by luruke** [comment]
Hello @Mugen87.

I'm ok to not support older build of IE11 , but at least we should add a check, in order to avoid to break all the javascript in the page.

Worth mentioning is that to reproduce the bug, is enough to load three js, even without using it.
So it's impossible "exit gracefully", if not loading the library dinamically.

Strangely enough, when I tried, the `r84` seemed to work. Any idea why?

**Comment by Mugen87** [comment]
I think because of this 43d6053fc7c07688d980be314385f6339c30248a

Before this change, the variable `TYPED_ARRAYS` was only created if the `.parse()` was called.

**Comment by Mugen87** [comment]
@luruke Any ideas how to fix this? Unfortunately, i'm unable to test and reproduce the problem on my machine.

**Comment by luruke** [comment]
@Mugen87 I'm using [BrowserStack](https://www.browserstack.com/) to replicate the issue.
More specifically the configuration is called (windows 8.1 - ie11 latest).
(Not sure if you can use a trial account).

I'm more than happy to create a pull request.

What about a simple:
```javascript
Uint8ClampedArray: typeof Uint8ClampedArray !== 'undefined' ? Uint8ClampedArray : Uint8Array,
```
Or it's better to move back the `TYPED_ARRAYS` inside `.parse()` ?
(of course it will mean fatal error when using it).

What I want for the moment is just make sure that the JavaScript code is correctly parsed, so I can gracefully degrade (aka not running the webgl part) on my website when running on IE11 (or when Uint8ClampedArray not available).

BTW this is not the only problem with this old IE11 build:

<img width="1436" alt="screen shot 2017-06-03 at 20 35 08" src="https://cloud.githubusercontent.com/assets/61326/26756149/9c319b78-489c-11e7-9c6e-f0fa936e4502.png">
<img width="1431" alt="screen shot 2017-06-03 at 20 38 02" src="https://cloud.githubusercontent.com/assets/61326/26756151/9eeeecb2-489c-11e7-83e4-103a0382f894.png">
<img width="1433" alt="screen shot 2017-06-03 at 20 38 08" src="https://cloud.githubusercontent.com/assets/61326/26756155/a2bb0a2e-489c-11e7-8a7c-01c441adda4c.png">

As you can see webgl is supported, the basic cube spinning is not working with r84, while an old demo r55 is working. In any case this is not my biggest concern, also considering that on browserstack windows is probably running on very limited video card / old drivers.

**Comment by Mugen87** [comment]
Before creating a PR, i'd like to wait what other developers say about this issue. 

Besides, i've made bad experiences with testing graphic intensive applications in VMs. They often report errors or warnings that don't occur on physical machines.

**Comment by mrdoob** [comment]
> What about a simple:
> ```javascript
> Uint8ClampedArray: typeof Uint8ClampedArray !== 'undefined' ? Uint8ClampedArray : Uint8Array,
> ```

That sounds like an okay workaround to me.
