### ISSUE TITLE
can not bind to bones as node does not have a skeleton 

### ISSUE THREAD

**Issue by RockyF** [mrdoob/three.js#11450]
##### Description of the problem 

I export my model to three.js type with armature from blender, but when play clipAction it got error: `can not bind to bones as node does not have a skeleton` several times
![image](https://cloud.githubusercontent.com/assets/1643017/26816293/7a328e32-4ac3-11e7-8799-fddc2436e120.png)

scene tree:
![image](https://cloud.githubusercontent.com/assets/1643017/26816340/b037a706-4ac3-11e7-931a-3f7d07884774.png)

I think three.js plugin did not export armature or skeleton.

##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by RockyF** [comment]
I resolved it by using SkinnedMesh!

**Comment by EdgeCastMedia** [comment]
@RockyF Hi can you help me with this issue? I can't seem to resolve it. Thank you for your time.
