### ISSUE TITLE
fbxloader can't use repeat wrapping.

### ISSUE THREAD

**Issue by llwslc** [mrdoob/three.js#11467]
##### Description of the problem 

correct loader:
![image](https://user-images.githubusercontent.com/5865414/26924363-167b0e08-4c78-11e7-8d2f-bebdf6eff421.png)

three.js is wrong
![image](https://user-images.githubusercontent.com/5865414/26924196-53ff173e-4c77-11e7-9735-774390fd31d3.png)

##### Three.js version

- [X] Dev
- [X] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by takahirox** [comment]
@llwslc
Would you share the fbx file?

**Comment by llwslc** [comment]
[here is the file](https://github.com/llwslc/theFbxFiles)
@takahirox
