### ISSUE TITLE
VertexColored geometry ignores lighting

### ISSUE THREAD

**Issue by lowlines** [mrdoob/three.js#11464]
##### Description of the problem 
When applying vertexColors to a mesh, the standard material types (Phong, Lambert) don't appear to take scene lighting into account, colors are just rendered out at that their raw color value. Attached jsfiddle demonstrates where every other face has a vertex color applied to it showing that while the material color reacts to light, the vertexColors don't.

Is this intended or a bug?
http://jsfiddle.net/qhyvks31/

##### Three.js version

- [ ] r83

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
```js
face.vertexColors[j] = new THREE.Color(255, 0, 255);
```

`THREE.Color` values go from `0` to `1`.
