### ISSUE TITLE
WebGLRenderLists retaining unused heap objects

### ISSUE THREAD

**Issue by aardgoose** [mrdoob/three.js#11478]
##### Description of the problem 

A problem with the new WebGLRenderLists which are hashed by Scene and Camera objects.

If a scene and or camera is used in a render pass, but is then not needed and discarded afterwards, the RenderLists retain references to the camera and scene objects and descendants, thus preventing garbage collection and the obvious problems with memory usage. The only mechanism available to delete the renderLists is to dispose of the renderer and start again which seems a bit extreme, and not always practical.

Should this be:

1. Ignored, as an obscure corner case. ( I hit it, but am probably not a typical user).

2. Add a mechanism to remove all or a specific WebGLRenderList. 

3. Use listeners on Scene and Camera dispose events or similar to remove RenderLists. ( probably the most complicated and error prone).

Any thoughts on this?

##### Three.js version

- [X ] Dev
- [ X] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
> If a scene and or camera is used in a render pass, but is then not needed and discarded afterwards, 

You mean is not needed for the rest of the application? Or do you create a new camera later?

**Comment by aardgoose** [comment]
In this case it is a camera used for a once only rtt pass and not used later, (Orthographic and Perspective cameras in use, so I can't use a single camera and recycle, so I end up with effectively orphaned render lists, if that makes sense.

**Comment by mrdoob** [comment]
Yeah. Makes sense. I think I would vote for exposing `renderer.renderLists`.

**Comment by aardgoose** [comment]
Closed by #11497
