### ISSUE TITLE
LineSegments bufferoverflow?

### ISSUE THREAD

**Issue by zwitter1** [mrdoob/three.js#11473]
##### Description of the problem 
In the middle of trying to update my three.js version (i don't remember or have trace of the original three version i was using) i ran into what appears to be a bug with the new (to me) LineSegments constructor. 

Im using LineSegments like in your "webgl_buffergeometry_lines_indexed" example to make a massive number of lines with a single javascript object. Everything performs as expected it seems until i get to a certain size of index array passed into my geometry. At which point a line connects from that most recent point back to the first indexed point. from there the lines are drawn unpredictably and the remainder of my object isn't drawn. 

Here is a simplified example of the problem: 
https://jsfiddle.net/zwitter1/g4eLshy0/4/

In this example i created a function that draws a spiral with straight lines. The first param specifies the number of lines drawn and the second param specifies the number of vertices used to create each line:

 `var lineProblem = createLineSample(100, 1000);`

****
based on what used to work with:
 
`new THREE.Line(lineGeo,lineMat, THREE.LinePieces)`

Id expect the rendered result to look identical between 

`createLineSample(100, 100);`
### and 
`createLineSample (100, 1000);`

seeing as ultimately 100 straight lines are being drawn regardless as to the number of vertices they consist of. However that is not the case after updating to the latest three and using:

 `new THREE.LineSegments(geometry, material);`

The result I see instead is as follows: 
`createLineSample(100, 100);`
![image](https://user-images.githubusercontent.com/1789250/26950809-04b30050-4c6d-11e7-81b6-48210387300e.png)

`createLineSample(100,1000);`
![image](https://user-images.githubusercontent.com/1789250/26950870-38500dae-4c6d-11e7-94c1-757dff5bab67.png)

The result in my actual application looks like this (been plaguing me for a while now):
![image](https://user-images.githubusercontent.com/1789250/26951077-ec7e8cf6-4c6d-11e7-9007-deb8cd715ba2.png)
 

note: I understand that it doesn't make sense to use more than 2 vertices for a straight line but im doing this to create curved lines in my final application in addition to straight lines more often than not.

### Things I have tried: 
If I shuffle the vertices array around such that the last vertices are pointed to by the indices first... they get displayed as expected (at least until i reach that offending index size). 

I have isolated the rogue line where the insanity starts to be between the(130941 -> 130942) indices array positions in my above example and between (128500 -> 128501) in my real application... doesnt make sense to me that they are different just yet.    

tracing the offending indices to find the correct vertices the lines should be drawn between shows that everything seems to be correct, but the rendered result doesn't reflect as such...
******
So might there be an overflow happening somewhere in the three.js library amidst the change to the LineSegments method?

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Could you simplify the jsfiddle so it focuses in the actual issue?

**Comment by Mugen87** [comment]
I think i've fixed your problem with this fiddle: https://jsfiddle.net/g4eLshy0/10/

The problem was that you created the index buffer with a `Uint16Array`, which only can handle values >= 65535. Instead, you have to use a `Uint32Array`.

With the new `.setIndex()` method, you only have to apply your index array. The creation of the correct typed array is automatically done by `three.js`. I've fixed this in your fiddle.

**Comment by zwitter1** [comment]
That does fix the problem. thank you Mugen87.
