### ISSUE TITLE
Possible memory leak when using canvas texture on shader material

### ISSUE THREAD

**Issue by rmarques-realstatus** [mrdoob/three.js#11471]
I am creating textual images from DOM canvas objects and using them to create textures. The latter are then fed into a ShaderMaterial.

I've created a jsfiddle example that is not unlike: https://threejs.org/examples/#webgl_test_memory

The amount of memory used keeps increasing with time. However, I believe I'm cleaning up the resources correctly. Given enough time the tab crashes, as it runs out of memory

Have opened an issue on StackOverflow: 
https://stackoverflow.com/questions/44432537/three-js-memory-management-shader-material

I'm using the latest version of three.js
The issue happens on all browsers. I've only tested on Windows.

Any help would be appreciated.

**Comment by pailhead** [comment]
Curious about this one. My theory is that a point is reached when there is a lot of garbage for the GC to dispose of, and the geometry/texture disposal has not happened yet. Everything is scheduled to be released correctly, it just doesn't happen fast enough. Of course, i know next to nothing about this, so probably completely wrong :)

**Comment by pailhead** [comment]
I also did not notice that you put all 10k planes, on top of each other. I've had some massive issues with this, usually when some kind of procedural geometry fails, and renders with an improper shader. For example: https://github.com/mrdoob/three.js/pull/11349, if the complicated "procedural" geometry is rendered with a regular shader, i had the graphics driver crash on my windows machine. With the proper shader it runs at 60. 

On that note, i would try to add:

```
randPos[ 10000 ] = randVec3 * 1000 - 500

createLabels(){
  for i in labels
    ...
    label.position.copy( randPos[ i ] )
    ...
}
```

Otherwise, i'm wondering if you even got to the cleanup stage that you expected. You do create a lot of stuff. I took the size of your label conservatively as a square, so it ends up being 78x78. 10k of these yields around 185mb of data. I wonder what kind of numbers do you get in `width`.

**Comment by rmarques-realstatus** [comment]
So in my real app I'm using sprites for text labels. I use DOM canvas objects to draw the text, and use that text as a texture, which is then applied to a plane. The Shader then controls various aspects such: size, visibility, etc.

The texts (labels) get updated based on what the user is seeing. There could be thousands of labels on screen at any given time. Thus, there's a lot of destruction and creation of dynamic labels.

I noticed that a lot of memory was being used and eventually the tab died. I narrowed down the problem to the labels. To better isolate the issue I made a JSfiddle that mimics what happens in the real world scenario, but speeds it up from hours into minutes.

I based my JSFiddle on the threejs' own memory example: https://threejs.org/examples/#webgl_test_memory

The fiddle dies just like my App, after a while. Something is for sure killing it.

I'm here to get some help from someone who knows about three.js (and WebGl) than me.

I've not been the first one to find peculiar memory behaviours when using sprites as textures: https://github.com/mrdoob/three.js/issues/7449

What do you think is wrong with my test?

I've also created a fiddle that uses a power of two texture. It takes longer for the tab to die, but still does so: https://jsfiddle.net/e3a8atsh/1/

**Comment by pailhead** [comment]
Im out of ideas, i didnt know that the webgl_test_memory also dies, i was looking at it with the profiler (which i dont really know how to use) and it didnt seem to be growing. Reducing the number of planes in your demo seemed to grow very slowly, but calling the GC from the profiler seemed to reset it.  #7449 is interesing, the conclusion seems to be that this acts differently on other machines?

The way i think i'd approach is is make groups of N labels. Give each group of labels the same texture, containing N labels. Render labels with 2d canvas, then call `renderer.render(scene[0],camera)`, then render another group into the canvas, and another scene, until you draw it all.

**Comment by tommytee** [comment]
May relate to https://github.com/mrdoob/three.js/issues/11378

**Comment by Mugen87** [comment]
@rmarques-realstatus You are creating each frame 10.000 identical geometry, material and texture objects. You could easily create only a single geometry, material and texture in `init()` and reuse them for all meshes. Also adding and removing 10.000 new planes per frame is much more extreme compared to `webgl_test_memory`. A poor performance under these circumstances is comprehensible.

BTW: `webgl_test_memory` runs stable on my computer. And #13201 made the handling of NPOT textures more memory efficient. 

There is at least one open issue in context of renderlists that still prevents GC from doing its work, see #12464

**Comment by Mugen87** [comment]
> There is at least one open issue in context of renderlists that still prevents GC from doing its work

Actually #12447 already tracks this issue. Closing.
