### ISSUE TITLE
FBX loader failing to load binary

### ISSUE THREAD

**Issue by CarlBateman** [mrdoob/three.js#11487]
##### Description of the problem 

FBX loader failing to load binary pearl.fbx from mixamo site.

##### small-test at
(jsfiddle won't allow CORS)

http://webglworkshop.com/fbx/index.html
fbx file at http://webglworkshop.com/fbx/pearl.fbx

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [x] Internet Explorer
- [x] Opera

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Summary of console output and errors listed:

THREE.WebGLRenderer 85
100% downloaded    Index.html:50 
FBX binary version: 7400    FBXLoader.js:3917 
Unknown texture application of type TransparentColor, skipping texture    FBXLoader.js:526
    parseParameters @ FBXLoader.js:526
    parseMaterial @ FBXLoader.js:420
    parseMaterials @ FBXLoader.js:387
    parse @ FBXLoader.js:124
    (anonymous) @ FBXLoader.js:61
    (anonymous) @ three.js:29466
Unknown texture application of type SpecularColor, skipping texture     FBXLoader.js:526 
Unknown texture application of type ShininessExponent, skipping texture     FBXLoader.js:526
Unknown texture application of type TransparentColor, skipping texture    FBXLoader.js:526
Unknown texture application of type SpecularColor, skipping texture    FBXLoader.js:526
Unknown texture application of type ShininessExponent, skipping texture    FBXLoader.js:526
Unknown texture application of type TransparentColor, skipping texture    FBXLoader.js:526
Unknown texture application of type SpecularColor, skipping texture    FBXLoader.js:526
Unknown texture application of type ShininessExponent, skipping texture    FBXLoader.js:526
Unknown texture application of type TransparentColor, skipping texture    FBXLoader.js:526
Unknown texture application of type SpecularColor, skipping texture    FBXLoader.js:526
Unknown texture application of type ShininessExponent, skipping texture    FBXLoader.js:526
Unknown texture application of type TransparentColor, skipping texture    FBXLoader.js:526
Unknown texture application of type SpecularColor, skipping texture    FBXLoader.js:526
Unknown texture application of type ShininessExponent, skipping texture    FBXLoader.js:526
FBXLoader: Vertex has more than 4 skinning weights assigned to vertex.  Deleting additional weights.    FBXLoader.js:780
    genGeometry @ FBXLoader.js:780
    parseMeshGeometry @ FBXLoader.js:686
    parseGeometry @ FBXLoader.js:659
    parseGeometries @ FBXLoader.js:636
    parse @ FBXLoader.js:126
    (anonymous) @ FBXLoader.js:61
    (anonymous) @ three.js:29466
pearl/pearl.fbx 1 26    index.html:44
TypeError: Cannot read property 'values' of null    Index.html:55
   at http://localhost:65003/root/three/FBXLoader.js:2145:35
   at Map.forEach (native)
   at parseAnimations (http://localhost:65003/root/three/FBXLoader.js:2133:12)
   at parseScene (http://localhost:65003/root/three/FBXLoader.js:1606:22)
   at THREE.FBXLoader.parse (http://localhost:65003/root/three/FBXLoader.js:127:24)
   at http://localhost:65003/root/three/FBXLoader.js:61:28
   at XMLHttpRequest.<anonymous> (http://localhost:65003/root/three/three.js:29466:21)
onError @ Index.html:55
(anonymous) @ FBXLoader.js:69
 
blob:http://localhost:65003/e4f94a03-16ab-49d6-b41b-fa7f0f286dec 2 26	Index.html:44 
blob:http://localhost:65003/227f8e8f-f9c5-4f6a-945a-eed1573a4759 3 26	Index.html:44 
blob:http://localhost:65003/eca94845-73fb-4d58-9d64-874806d92571 4 26	Index.html:44 
blob:http://localhost:65003/35c2f7b8-f078-4c31-9578-dd33b44f283f 5 26	Index.html:44 
blob:http://localhost:65003/4b16603d-1538-4add-80f0-8f44463f5a72 6 26	Index.html:44 
blob:http://localhost:65003/394172ac-4faa-4bd3-90aa-6b81e90fe027 7 26	Index.html:44 
blob:http://localhost:65003/661a04de-1afb-4ae9-aee6-08bfad529073 8 26	Index.html:44 
blob:http://localhost:65003/5704e2c5-6279-450d-aec7-3f7eb670762e 9 26	Index.html:44 
blob:http://localhost:65003/4cf6158f-a61c-49db-a761-f45cde1920c6 10 26	Index.html:44 
blob:http://localhost:65003/a0c1ac3b-f2bd-499c-b8a3-f3d1f3f68faa 11 26	Index.html:44 
blob:http://localhost:65003/aa4ea3d2-db4e-4dc7-a770-fa52b50e2136 12 26	Index.html:44 
blob:http://localhost:65003/aa5e2229-00cb-42ba-a16d-5fb7fd5970f8 13 26	Index.html:44 
blob:http://localhost:65003/c7cb7a04-2fed-4ad4-af1c-676b7c933367 14 26	Index.html:44 
blob:http://localhost:65003/2995a256-0d97-430c-8c61-4ab367b09567 15 26	Index.html:44 
blob:http://localhost:65003/5f139178-9caf-47a3-b86f-816f94385190 16 26	Index.html:44 
blob:http://localhost:65003/eb06be9f-e090-45e7-aad9-6f29d481bc27 17 26	Index.html:44 
blob:http://localhost:65003/5311fd2e-4ba0-46b9-8cfb-361d3f32809b 18 26	Index.html:44 
blob:http://localhost:65003/644e06bc-eba6-4b12-b54d-0a46bc1cbaaa 19 26	Index.html:44 
blob:http://localhost:65003/cbd93517-8f3e-4dea-bcb6-b85a0fe84680 20 26	Index.html:44 
blob:http://localhost:65003/fa01269f-afcf-40e0-b1e4-d3a7f9367a70 21 26	Index.html:44 
blob:http://localhost:65003/2c98f06c-1141-4963-a9d2-9aace865f47d 22 26	Index.html:44 
blob:http://localhost:65003/3b29317c-8ca1-4b53-b1ff-00ee232b0414 23 26	Index.html:44 
blob:http://localhost:65003/acbbcf85-f9ad-46fa-87d4-88300219d8b2 24 26	Index.html:44 
blob:http://localhost:65003/6875e4b9-75b1-457f-b333-717927894792 25 26	Index.html:44 
blob:http://localhost:65003/fea3e1d5-6851-4b2c-9257-d8bd6ba3d89e 26 26	Index.html:44

**Comment by Bonfims** [comment]
The same here with an 3D model with animation from Mixamo.
i can run the same fbx without animations from Mixamo, but, when i get him from mixamo, follow:
![image](https://user-images.githubusercontent.com/16294667/27041170-8ef13f94-4f69-11e7-845e-7dba14738269.png)
The character FBX with an animation from Mixamo:
[basicCharacter.fbx.txt](https://github.com/mrdoob/three.js/files/1068660/basicCharacter.fbx.txt)
The original model:
[basicCharacter.original.fbx.txt](https://github.com/mrdoob/three.js/files/1068661/basicCharacter.original.fbx.txt)
Is this a mixamo problem? Is my first time using three.js, so far I have not been able to load any kind of fbx with animations, neither mixamo or any other applications.

**Comment by Bonfims** [comment]
OOOOW GUYS,
I made a mistake. :(
in my case, was just the wrong way to get models from Mixamo...
![image](https://user-images.githubusercontent.com/16294667/27042773-5e16a92c-4f6e-11e7-8117-8027ef23132b.png)
I was making the download from "My Characters" tab, but, when i tried make the download from "Animations" tab, the model worked on FBXLoader, cool!
![mixamo_animation](https://user-images.githubusercontent.com/16294667/27042883-b484670e-4f6e-11e7-9d5a-d60ab60caf09.gif)

**Comment by takahirox** [comment]
Perhaps I've figured out what the root issue of this error is.

In general, `AnimationCurveNode` is an animation node and
`AnimationCurve` connected to a node represents animation
(times and values of key frame animation).

But sometimes, `AnimationCurveNode` doesn't have
any connected `AnimationCurve` (not sure why tho).

The error disappeared if I ignore such animation nodes.

![image](https://user-images.githubusercontent.com/7637832/27160000-e7f8f430-51ab-11e7-847d-a590ca4e0bea.png)

However,  the animation seems still weird.
Just her hands and legs tremble.

Where can I see the right animation?

(It's also weird around her eyes but it'd another issue, maybe textures?)

**Comment by CarlBateman** [comment]
Wow! That's certainly looking much better.

There is no animation in the pearl.fbx model. I can generate a separate animation file and upload if you need it (probably a good idea for testing anyway).

The eyes should look like this (this is the same file imported into SketchFab):
![pearl-correct](https://user-images.githubusercontent.com/2813834/27177498-801cab46-51be-11e7-8915-b579795b16d9.jpg)
and the original in Mixamo:
![pearl-original](https://user-images.githubusercontent.com/2813834/27177843-bca61e8e-51bf-11e7-823f-b5b10a5f87b3.jpg)

**Comment by CarlBateman** [comment]
I've uploaded pearl_walk.fbx to http://webglworkshop.com/fbx/pearl_walk.fbx

**Comment by CarlBateman** [comment]
@takahirox have you committed any changes?

**Comment by takahirox** [comment]
Sorry, still working on it now.

Animation looks fine?

![ezgif com-optimize](https://user-images.githubusercontent.com/7637832/27418299-29202fe2-5755-11e7-8b92-040878efec12.gif)

**Comment by CarlBateman** [comment]
@takahirox looking good. Mixamo has an "In Place" option which should make it easier to check imported animation.

Loading into PlayCanvas, SketchFab, Unity and Blender, the T-pose FBX I linked to has no tremble.

**Comment by takahirox** [comment]
Thanks. It seems the file actually has tremble animation, not sure how `FBXLoader` handle it yet.
I'll make PR to avoid the failure so far.

**Comment by CarlBateman** [comment]
Is it "tremble" or "idle"? If not in T-Pose probably "idle".

**Comment by takahirox** [comment]
Trembling. Probably you'll see what I mentioned if you replace the file with pearl.fbx in `webgl_loader_fbx` example.

**Comment by takahirox** [comment]
About her eyes, they seem fine.
That while color is just reflection of light.
This's the screenshot where I changed the light direction.

![image](https://user-images.githubusercontent.com/7637832/27463317-df4c6824-5801-11e7-90b4-7f3f028d5d73.png)

So I think we can close this thread.

**Comment by CarlBateman** [comment]
Sterling work, you should get a bl**dy knighthood. I have no idea what's causing the tremble.

One minor point, I found the error message confusing (twice). Partly because it's an external, third-party library and maybe partly because "import" has a different meaning to me.

Perhaps, rather than 
'FBXLoader: Import inflate.min.js from https://github.com/imaya/zlib.js'
have something like
'FBXLoader: External library Inflate.min.js missing, import from https://github.com/imaya/zlib.js'

**Comment by CarlBateman** [comment]
Before closing, the eyelashes should be transparent. Can this be fixed? Should it be a raised as a separate issue?
TIA

![image](https://user-images.githubusercontent.com/2813834/27479456-eba57ef8-580b-11e7-9a32-d44acd4416a1.png)

**Comment by takahirox** [comment]
Please file another issue.

**Comment by mrdoob** [comment]
> Perhaps, rather than
'FBXLoader: Import inflate.min.js from https://github.com/imaya/zlib.js'
have something like
'FBXLoader: External library Inflate.min.js required, import from https://github.com/imaya/zlib.js'

Sounds good to me. Would you like to edit the file directly
https://github.com/mrdoob/three.js/edit/dev/examples/js/loaders/FBXLoader.js

**Comment by CarlBateman** [comment]
Love to, but alas I'm not allowed to edit directly. 😞 
![fork](https://user-images.githubusercontent.com/2813834/27507348-1b4cedf8-58c5-11e7-8fc7-3b9b74bd9abc.gif)

**Comment by jostschmithals** [comment]
@CarlBateman You have to fork the repository first (green button). Then you can create a Pull Request in [this]( https://github.com/mrdoob/three.js/wiki/An-introduction-to-using-Git) way. [That](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js) might be relevant, too.

**Comment by CarlBateman** [comment]
In VS, got the repo, made changes but can't push it.

In terminal got as far as:
git pull upstream dev
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

So, yeah. I don't have a clue what's going on.

**Comment by jdanford** [comment]
You should fork this repository, clone your fork, and then run `git remote add upstream git@github.com:mrdoob/three.js.git` to add the upstream repository.

**Comment by CarlBateman** [comment]
Thanks for the feedback. In the end, I used "github desktop" and managed to raise the pull request.

**Comment by JamesHealdUK** [comment]
I've actually had a similar issue loading local files, only my FBXLoader seems to entirely miss the version of the file:
``Uncaught Error: THREE.FBXLoader: Cannot find the version number for the file given.
    at getFbxVersion (FBXLoader.js:4950)
    at THREE.FBXLoader.parse (FBXLoader.js:105)
    at init ((index):271)
    at start ((index):110)
    at HTMLButtonElement.onclick ((index):534)``

**Comment by mrdoob** [comment]
@JamesHealdUK It would be helpful if you could share the .fbx file...

**Comment by Travis1282** [comment]
I'm running into the same problem as James both locally and on a server. 

Error: THREE.FBXLoader: Cannot find the version number for the file given.
    at getFbxVersion (FBXLoader.js:3529)
    at THREE.FBXLoader.parse (FBXLoader.js:90)
    at Object.onLoad (FBXLoader.js:53)
    at XMLHttpRequest.<anonymous> (three.js:30794)


![vorona_256](https://user-images.githubusercontent.com/16586743/34429779-60003202-ec22-11e7-919f-5434cd4be1e2.JPG)

**Comment by mrdoob** [comment]
@Travis1282 It would be helpful if you could share the .fbx file...

**Comment by Travis1282** [comment]
Sorry about that:

http://realetravis.com/travis/FBXLoader/models/flying_sparrow.fbx

**Comment by looeee** [comment]
@Travis1282 would you mind opening a new issue about this? I'll take a look.

**Comment by looeee** [comment]
@Travis1282 your model gets past the version check in the latest FBXLoader:

```
THREE.WebGLRenderer 90dev
THREE.FBXLoader: FBX binary version: 6000
```

However something in the BinaryParser is failing silently and I haven't been able to figure out where, except that there seem to be some non-unicode characters parsed (displaying as `?` when I log them to the console).

It's likely that this is because your model is a very old version - the current FBX Binary version is 7400. 
The best thing for you to do is to re-export your model with a newer version.

**Comment by Gresliebear** [comment]
Still getting this issue today  'Could not load models/ybot.fbx: THREE.FBXLoader: Cannot find the version number for the file given.' for 7.1

**Comment by looeee** [comment]
@Gresliebear you can try converting to the file to a newer FBX version with this tool 

https://www.autodesk.com/developer-network/platform-technologies/fbx-converter-archives

**Comment by Gresliebear** [comment]
> 

@looeee thanks ill give this a shot I have tried other converters https://products.aspose.app/3d/conversion/fbx-to-gltf but this failed to convert animation from my fbx file into gltf file. I will give this a shot later 

The solution to this was not to move models to public folder yes that works but there this URL code

```
_LoadModels() {
        let url = new URL( '../resources/ybot.fbx', import.meta.url );
        const loader = new FBXLoader();
        // loader.setPath('./resources/');
        // console.log(loader)
        // https://r105.threejsfundamentals.org/threejs/lessons/threejs-fundamentals.html
        loader.load(`${url}`, (gltf) => {
            console.log(gltf)
            // scene.add( gltf.scene )
            gltf.scale.setScalar(0.01);
            gltf.traverse(c => {
            c.castShadow = true;
      });

```

Now I could pass my 3D objects from anywhere in my react app now they next challenge is loading 3D objects from postgres

**Comment by looeee** [comment]
I think this is the best FBX -> glTF converter currently:

https://github.com/facebookincubator/FBX2glTF

Alternatively, if you're using 3DS Max or Maya you can to exporting directly to glTF with the [Babylon.js exporter](https://doc.babylonjs.com/extensions/Exporters). I've heard it's pretty good but have not used it much myself.
