### ISSUE TITLE
Float to RGB packing

### ISSUE THREAD

**Issue by vchizhov** [mrdoob/three.js#11489]
24bit float packing could be added in the shader chunks, here's a link (I've tested the code to reconstruct normals from depth, seem to be working just fine): [float to 24bit](https://skytiger.wordpress.com/2010/12/01/packing-depth-into-color/)

#8295

Not sure why exactly @bhouston claims that the packing is imprecise as it is, a 0e0 error is claimed on the site I linked. And the theoretical foundations seem fine: [encoding](http://marcodiiga.github.io/encoding-normalized-floats-to-rgba8-vectors)

**Comment by Mugen87** [comment]
Closing since the engine does not support the RGB format anymore.
