### ISSUE TITLE
Proposal: add colour parameter to light helpers

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#11495]
Currently light helpers take the colour of the light, which is a good default and works well in most cases. 

However it's problematic when using, for example, a white light with a white scene background, which I would say is a very common use case and renders the helper invisible. 

Since light helpers are supposed to be disposable helper objects - i.e. put into a scene temporarily to help position a light, it doesn't make sense (to me at least) to have to adjust your scene to be able to use them. 
So I'd like to make a PR to add a colour parameter to these helpers, if others agree that it's a useful idea. They will still take the light colour by default, but this can be overridden to if necessary.

**Comment by mrdoob** [comment]
Sounds good 👍
