### ISSUE TITLE
use webpack / loadTexture fail

### ISSUE THREAD

**Issue by yangbin1994** [mrdoob/three.js#11500]
##### Description of the problem 

demo url: https://threejs.org/examples/#canvas_geometry_panorama_fisheye
```javascript
 var materials = [
        loadTexture(require('./img/px.jpg')), // right
        loadTexture(require('./img/nx.jpg')), // left
        loadTexture(require('./img/py.jpg')), // top
        loadTexture(require('./img/ny.jpg')), // bottom
        loadTexture(require('./img/pz.jpg')), // back
        loadTexture(require('./img/nz.jpg')) // front
 ];
````
webpack.config
```javascript
 {
                test: /\.(jpg|png|gif)$/,
                use: {
                    loader: 'file-loader',
                }
 },
```
there is no error, but ...
![image](https://user-images.githubusercontent.com/12080165/27072449-f907ebfa-5052-11e7-9f55-4e5adc8fecc5.png)

how can i fix it?

##### Three.js version

    "three": "^0.85.2"

##### Browser

- [x] All of them

##### OS

- [x] macOS

**Comment by Usnul** [comment]
I would consult the webpack documentation, but it seems like you're trying to push contents of a texture into "loadTexture" which expects a string URL to your texture instead. Try this instead:

```js
 var materials = [
        loadTexture('img/px.jpg'), // right
        loadTexture('img/nx.jpg'), // left
        loadTexture('img/py.jpg'), // top
        loadTexture('img/ny.jpg'), // bottom
        loadTexture('img/pz.jpg'), // back
        loadTexture('img/nz.jpg') // front
 ];
```

make sure that images are available at that location relative to html page. E.g.:
~/test.html
~/img/px.jpg

**Comment by llccing** [comment]
@yangbin1994  thanks 
the require("xxx.jpg") methods is very useful. 

my examples
```
var texture = new THREE.TextureLoader().load(require("../assets/floor.jpg"));
```

**Comment by Usnul** [comment]
what is the benefit of doing that?

if you use http2.0, which you should - you don't event gain the advantage of fewer separate TCP connections. Converting your entire asset into a data URL you do following:
- encode binary data as a string
- pay for decoding of said string at runtime
- end up with a bloated JS file, leading to longer parse time longer download times

Using data URL you end up with 2 copies of the asset in memory, one that's the data URL string itself, and the second is the decoded asset.

You could write some smarter converter to "load" texture as a static binary array instead, but a lot of above arguments still apply.

Convenient? - maybe... sometimes...

It's not fit for serious applications where performance is a consideration.

**Comment by Jalever** [comment]
> 
> 
> @yangbin1994 thanks
> the require("xxx.jpg") methods is very useful.
> 
> my examples in vue-cli project
> 
> ```
> var texture = new THREE.TextureLoader().load(require("../assets/floor.jpg"));
> ```

It helps for me! thanks bro
