### ISSUE TITLE
InstancedBufferGeometry intersection

### ISSUE THREAD

**Issue by ebeit303** [mrdoob/three.js#11501]
##### Description of the problem 

I tried the Instancedbuffergeometry, it works awesome, Intersection is not happening in InstancedBufferGeometry, i checked in the threejs(r85) library, checkBufferGeometryIntersection function have the position value only, I think the offset and orientation value need to use with the position.

I have another doubt in it, i have used one rawshadermaterial only, then how i can highlight the selected mesh.
[Link](https://stackoverflow.com/questions/44514873/instancedbuffergeometry-intersection-not-happening)

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Please do not repost SO questions here.

**Comment by ArtistZhou** [comment]
I find this issue too , it only try buffer geometry and not with the instance , it can't find the intersection object .what is your solution after all?

**Comment by WestLangley** [comment]
GPU picking. See https://threejs.org/examples/webgl_interactive_instances_gpu.html

Please use the three.js [forum](https://discourse.threejs.org) if you need help.
