### ISSUE TITLE
AO Map does not respect texture repeat on a Geometry V3 import

### ISSUE THREAD

**Issue by NNskelly** [mrdoob/three.js#11505]
##### Description of the problem 

When an Ambient Occlusion map is used on a model imported from the Version 3 Geometry format with 2 sets of UVs (sidenote: are 2 sets of UVs intended to be required for AO?), the AO texture ignores its Repeat property settings.

The following JSON is the most minimal case I could reproduce; save it out and load it into the https://threejs.org/editor/ .  All textures are attached to this thread; color and normal are standard, a third texture has roughness on the green channel and AO on the red channel and is used for both.

Simple plane geometry, 2 sets of UVs, texture repeat set to [1,1] on all:

```
{
	"metadata": {
		"version": 4.5,
		"type": "Object",
		"generator": "Object3D.toJSON"
	},
	"geometries": [
		{
			"uuid": "0A8F2988-626F-411C-BD6A-AC656C4E6878",
			"type": "Geometry",
			"data": {
				"vertices": [ 1, 1, 0, 1, -1, 0, -1, -1, 0, -1, 1, 0 ],
                "normals":  [ 0,0,1, 0,0,1, 0,0,1, 0,0,1 ],
                "uvs": [ [ 1, 1, 1, 0, 0, 0, 0, 1 ], [ 1, 1, 1, 0, 0, 0, 0, 1 ] ],
				"faces": [ 8, 2,1,0, 2,1,0, 2,1,0,   8, 3,2,0, 3,2,0, 3,2,0 ]
			}
		}],
	"materials": [
		{
			"uuid": "1004175C-0998-4243-900E-1183CE95A692",
			"type": "MeshStandardMaterial",
			"color": 16777215,
			"roughness": 0.5,
			"metalness": 0.01,
			"emissive": 0,
			"map": "2B905060-08BC-4F9A-B459-B19426D879A8",
			"normalMap": "DBCBCBC9-9C93-4CB0-96F0-BE95B3EAE706",
			"normalScale": [1,1],
            "roughnessMap": "2CC1EE93-3FA2-4458-A022-85210D6A415A",
            "aoMap": "2CC1EE93-3FA2-4458-A022-85210D6A415A",
            "aoMapIntensity": 0.5,
			"depthFunc": 3,
			"depthTest": true,
			"depthWrite": true,
			"skinning": false,
			"morphTargets": false,
			"dithering": false
		}],
	"textures": [
		{
			"uuid": "2B905060-08BC-4F9A-B459-B19426D879A8",
			"name": "",
			"mapping": 300,
			"repeat": [1,1],
			"offset": [0,0],
			"wrap": [1001,1001],
			"minFilter": 1008,
			"magFilter": 1006,
			"anisotropy": 1,
			"flipY": true,
			"image": "66BE77DC-B7CB-4C84-B685-DDCC506C4015"
		},
		{
			"uuid": "DBCBCBC9-9C93-4CB0-96F0-BE95B3EAE706",
			"name": "",
			"mapping": 300,
			"repeat": [1,1],
			"offset": [0,0],
			"wrap": [1001,1001],
			"minFilter": 1008,
			"magFilter": 1006,
			"anisotropy": 1,
			"flipY": true,
			"image": "CEB6F8FF-29C2-44D4-8C25-6998FF62CDE5"
		},
		{
			"uuid": "2CC1EE93-3FA2-4458-A022-85210D6A415A",
			"name": "",
			"mapping": 300,
			"repeat": [1,1],
			"offset": [0,0],
			"wrap": [1001,1001],
			"minFilter": 1008,
			"magFilter": 1006,
			"anisotropy": 1,
			"flipY": true,
			"image": "5D6FFCBC-2194-4A81-AC85-59D92F101A4C"
		}],
	"images": [
        {
            "uuid": "66BE77DC-B7CB-4C84-B685-DDCC506C4015",
            "url": "PodiumFloor_Floor_BaseColor.jpg"
        },
		{
			"uuid": "CEB6F8FF-29C2-44D4-8C25-6998FF62CDE5",
            "url": "PodiumFloor_Floor_Normal.jpg"
		},
		{
			"uuid": "5D6FFCBC-2194-4A81-AC85-59D92F101A4C",
            "url": "PodiumFloor_Floor_AO_R.jpg"
		}],
	"object": {
		"uuid": "378FAA8D-0888-4249-8701-92D1C1F37C51",
		"type": "Scene",
		"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
		"children": [
			{
				"uuid": "E7B44C44-DD75-4C29-B571-21AD6AEF0CA9",
				"type": "Mesh",
				"name": "SharedVertexTest",
				"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
				"geometry": "0A8F2988-626F-411C-BD6A-AC656C4E6878",
				"material": "1004175C-0998-4243-900E-1183CE95A692"
			},
			{
				"uuid": "95EE0E37-CAA0-455D-8F12-7C4FDF6DF794",
				"type": "PointLight",
				"name": "PointLight 1",
				"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,4.837141,1],
				"color": 16777215,
				"intensity": 0.25,
				"distance": 0,
				"decay": 1,
				"shadow": {
					"camera": {
						"uuid": "34ED7BBB-6BFE-47F4-B69B-554EC468FE20",
						"type": "PerspectiveCamera",
						"fov": 90,
						"zoom": 1,
						"near": 0.5,
						"far": 500,
						"focus": 10,
						"aspect": 1,
						"filmGauge": 35,
						"filmOffset": 0
					}
				}
			},
			{
				"uuid": "0F2D0E48-F685-487E-8E04-99E0B76F9A19",
				"type": "AmbientLight",
				"name": "AmbientLight 1",
				"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
				"color": 16777215,
				"intensity": 1
			}],
		"background": 11184810
	}
}
```

Result:
![2uv1x](https://user-images.githubusercontent.com/28572171/27105428-279fa65e-5055-11e7-8561-d4f63b22e695.png)
as expected.

Same geometry, now with the textures upped to [3,3] repeat, 1 set of UVs:

```
{
	"metadata": {
		"version": 4.5,
		"type": "Object",
		"generator": "Object3D.toJSON"
	},
	"geometries": [
		{
			"uuid": "0A8F2988-626F-411C-BD6A-AC656C4E6878",
			"type": "Geometry",
			"data": {
				"vertices": [ 1, 1, 0, 1, -1, 0, -1, -1, 0, -1, 1, 0 ],
                "normals":  [ 0,0,1, 0,0,1, 0,0,1, 0,0,1 ],
                "uvs": [ [ 1, 1, 1, 0, 0, 0, 0, 1 ] ],
				"faces": [ 8, 2,1,0, 2,1,0,   8, 3,2,0, 3,2,0 ]
			}
		}],
	"materials": [
		{
			"uuid": "1004175C-0998-4243-900E-1183CE95A692",
			"type": "MeshStandardMaterial",
			"color": 16777215,
			"roughness": 0.5,
			"metalness": 0.01,
			"emissive": 0,
			"map": "2B905060-08BC-4F9A-B459-B19426D879A8",
			"normalMap": "DBCBCBC9-9C93-4CB0-96F0-BE95B3EAE706",
			"normalScale": [1,1],
            "roughnessMap": "2CC1EE93-3FA2-4458-A022-85210D6A415A",
            "aoMap": "2CC1EE93-3FA2-4458-A022-85210D6A415A",
            "aoMapIntensity": 0.5,
			"depthFunc": 3,
			"depthTest": true,
			"depthWrite": true,
			"skinning": false,
			"morphTargets": false,
			"dithering": false
		}],
	"textures": [
		{
			"uuid": "2B905060-08BC-4F9A-B459-B19426D879A8",
			"name": "",
			"mapping": 300,
			"repeat": [3,3],
			"offset": [0,0],
			"wrap": [1000,1000],
			"minFilter": 1008,
			"magFilter": 1006,
			"anisotropy": 1,
			"flipY": true,
			"image": "66BE77DC-B7CB-4C84-B685-DDCC506C4015"
		},
		{
			"uuid": "DBCBCBC9-9C93-4CB0-96F0-BE95B3EAE706",
			"name": "",
			"mapping": 300,
			"repeat": [3,3],
			"offset": [0,0],
			"wrap": [1000,1000],
			"minFilter": 1008,
			"magFilter": 1006,
			"anisotropy": 1,
			"flipY": true,
			"image": "CEB6F8FF-29C2-44D4-8C25-6998FF62CDE5"
		},
		{
			"uuid": "2CC1EE93-3FA2-4458-A022-85210D6A415A",
			"name": "",
			"mapping": 300,
			"repeat": [3,3],
			"offset": [0,0],
			"wrap": [1000,1000],
			"minFilter": 1008,
			"magFilter": 1006,
			"anisotropy": 1,
			"flipY": true,
			"image": "5D6FFCBC-2194-4A81-AC85-59D92F101A4C"
		}],
	"images": [
        {
            "uuid": "66BE77DC-B7CB-4C84-B685-DDCC506C4015",
            "url": "PodiumFloor_Floor_BaseColor.jpg"
        },
		{
			"uuid": "CEB6F8FF-29C2-44D4-8C25-6998FF62CDE5",
            "url": "PodiumFloor_Floor_Normal.jpg"
		},
		{
			"uuid": "5D6FFCBC-2194-4A81-AC85-59D92F101A4C",
            "url": "PodiumFloor_Floor_AO_R.jpg"
		}],
	"object": {
		"uuid": "378FAA8D-0888-4249-8701-92D1C1F37C51",
		"type": "Scene",
		"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
		"children": [
			{
				"uuid": "E7B44C44-DD75-4C29-B571-21AD6AEF0CA9",
				"type": "Mesh",
				"name": "SharedVertexTest",
				"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
				"geometry": "0A8F2988-626F-411C-BD6A-AC656C4E6878",
				"material": "1004175C-0998-4243-900E-1183CE95A692"
			},
			{
				"uuid": "95EE0E37-CAA0-455D-8F12-7C4FDF6DF794",
				"type": "PointLight",
				"name": "PointLight 1",
				"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,4.837141,1],
				"color": 16777215,
				"intensity": 0.25,
				"distance": 0,
				"decay": 1,
				"shadow": {
					"camera": {
						"uuid": "34ED7BBB-6BFE-47F4-B69B-554EC468FE20",
						"type": "PerspectiveCamera",
						"fov": 90,
						"zoom": 1,
						"near": 0.5,
						"far": 500,
						"focus": 10,
						"aspect": 1,
						"filmGauge": 35,
						"filmOffset": 0
					}
				}
			},
			{
				"uuid": "0F2D0E48-F685-487E-8E04-99E0B76F9A19",
				"type": "AmbientLight",
				"name": "AmbientLight 1",
				"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
				"color": 16777215,
				"intensity": 1
			}],
		"background": 11184810
	}
}
```

Result:
![1uv3x](https://user-images.githubusercontent.com/28572171/27105475-4f46b436-5055-11e7-835c-44f4b57f6d76.png)
I would not have expected the complete darkness of the plane, but this may just be the way the shader works with only 1 set of UVs.

Same geometry, 2UV sets, with all textures tiled to [3,3]

```
{
	"metadata": {
		"version": 4.5,
		"type": "Object",
		"generator": "Object3D.toJSON"
	},
	"geometries": [
		{
			"uuid": "0A8F2988-626F-411C-BD6A-AC656C4E6878",
			"type": "Geometry",
			"data": {
				"vertices": [ 1, 1, 0, 1, -1, 0, -1, -1, 0, -1, 1, 0 ],
                "normals":  [ 0,0,1, 0,0,1, 0,0,1, 0,0,1 ],
                "uvs": [ [ 1, 1, 1, 0, 0, 0, 0, 1 ], [ 1, 1, 1, 0, 0, 0, 0, 1 ] ],
				"faces": [ 8, 2,1,0, 2,1,0, 2,1,0,   8, 3,2,0, 3,2,0, 3,2,0 ]
			}
		}],
	"materials": [
		{
			"uuid": "1004175C-0998-4243-900E-1183CE95A692",
			"type": "MeshStandardMaterial",
			"color": 16777215,
			"roughness": 0.5,
			"metalness": 0.01,
			"emissive": 0,
			"map": "2B905060-08BC-4F9A-B459-B19426D879A8",
			"normalMap": "DBCBCBC9-9C93-4CB0-96F0-BE95B3EAE706",
			"normalScale": [1,1],
            "roughnessMap": "2CC1EE93-3FA2-4458-A022-85210D6A415A",
            "aoMap": "2CC1EE93-3FA2-4458-A022-85210D6A415A",
            "aoMapIntensity": 0.5,
			"depthFunc": 3,
			"depthTest": true,
			"depthWrite": true,
			"skinning": false,
			"morphTargets": false,
			"dithering": false
		}],
	"textures": [
		{
			"uuid": "2B905060-08BC-4F9A-B459-B19426D879A8",
			"name": "",
			"mapping": 300,
			"repeat": [3,3],
			"offset": [0,0],
			"wrap": [1000,1000],
			"minFilter": 1008,
			"magFilter": 1006,
			"anisotropy": 1,
			"flipY": true,
			"image": "66BE77DC-B7CB-4C84-B685-DDCC506C4015"
		},
		{
			"uuid": "DBCBCBC9-9C93-4CB0-96F0-BE95B3EAE706",
			"name": "",
			"mapping": 300,
			"repeat": [3,3],
			"offset": [0,0],
			"wrap": [1000,1000],
			"minFilter": 1008,
			"magFilter": 1006,
			"anisotropy": 1,
			"flipY": true,
			"image": "CEB6F8FF-29C2-44D4-8C25-6998FF62CDE5"
		},
		{
			"uuid": "2CC1EE93-3FA2-4458-A022-85210D6A415A",
			"name": "",
			"mapping": 300,
			"repeat": [3,3],
			"offset": [0,0],
			"wrap": [1000,1000],
			"minFilter": 1008,
			"magFilter": 1006,
			"anisotropy": 1,
			"flipY": true,
			"image": "5D6FFCBC-2194-4A81-AC85-59D92F101A4C"
		}],
	"images": [
        {
            "uuid": "66BE77DC-B7CB-4C84-B685-DDCC506C4015",
            "url": "PodiumFloor_Floor_BaseColor.jpg"
        },
		{
			"uuid": "CEB6F8FF-29C2-44D4-8C25-6998FF62CDE5",
            "url": "PodiumFloor_Floor_Normal.jpg"
		},
		{
			"uuid": "5D6FFCBC-2194-4A81-AC85-59D92F101A4C",
            "url": "PodiumFloor_Floor_AO_R.jpg"
		}],
	"object": {
		"uuid": "378FAA8D-0888-4249-8701-92D1C1F37C51",
		"type": "Scene",
		"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
		"children": [
			{
				"uuid": "E7B44C44-DD75-4C29-B571-21AD6AEF0CA9",
				"type": "Mesh",
				"name": "SharedVertexTest",
				"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
				"geometry": "0A8F2988-626F-411C-BD6A-AC656C4E6878",
				"material": "1004175C-0998-4243-900E-1183CE95A692"
			},
			{
				"uuid": "95EE0E37-CAA0-455D-8F12-7C4FDF6DF794",
				"type": "PointLight",
				"name": "PointLight 1",
				"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,4.837141,1],
				"color": 16777215,
				"intensity": 0.25,
				"distance": 0,
				"decay": 1,
				"shadow": {
					"camera": {
						"uuid": "34ED7BBB-6BFE-47F4-B69B-554EC468FE20",
						"type": "PerspectiveCamera",
						"fov": 90,
						"zoom": 1,
						"near": 0.5,
						"far": 500,
						"focus": 10,
						"aspect": 1,
						"filmGauge": 35,
						"filmOffset": 0
					}
				}
			},
			{
				"uuid": "0F2D0E48-F685-487E-8E04-99E0B76F9A19",
				"type": "AmbientLight",
				"name": "AmbientLight 1",
				"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
				"color": 16777215,
				"intensity": 1
			}],
		"background": 11184810
	}
}
```

Result:
![2uv3x](https://user-images.githubusercontent.com/28572171/27106199-fc0ca7c8-5057-11e7-9bd1-549355d12ff9.png)
while the color and normal (although you may need to up the direct lighting or metalness to see it) and roughness tile correctly, AO is still at the same size as the [1,1] repeat case.

There's certainly a chance this issue is another offshoot of https://github.com/mrdoob/three.js/issues/9457 if e.g. something internal is going off-by-one in its material indexing for property lookup...

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [?] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [?] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Reproduced in live https://threejs.org/editor/ editor on Windows chrome Version 59.0.3071.86 (Official Build) (64-bit)

Textures:
![podiumfloor_floor_basecolor](https://user-images.githubusercontent.com/28572171/27106274-48b5ed96-5058-11e7-88d1-78df65b7600e.jpg)

![podiumfloor_floor_normal](https://user-images.githubusercontent.com/28572171/27106277-4b718522-5058-11e7-935b-366d894cb221.jpg)

![podiumfloor_floor_ao_r](https://user-images.githubusercontent.com/28572171/27106283-4d9a5e3c-5058-11e7-96a2-86cc933a6b32.jpg)

**Comment by WestLangley** [comment]
`lightmap` and `aomap` _require_ a 2nd set of UVs. `offset` and `repeat` apply only to the _first_ set of UVs. Do not expect different behavior.

Also see [this stackoverflow post](https://stackoverflow.com/questions/14371385/can-a-three-js-material-have-separate-repeat-values-for-a-bump-map-and-a-texture/14372235#14372235).

**Comment by NNskelly** [comment]
So... more edits to the manual, then.  And looks like this will be a bit more tedious.  I can step through the various material pages as I find time and put notes in the aoMap and lightmap fields of each to reference the need for multiple UV sets; is there anywhere that UVs, and specifically, multiple sets of UVs, are independently documented to cite what they're used for from that end?  I've been over the Geometry and BufferGeometry sections, and the reference examples of the Version 3 and Version 4 json formats, but they don't say anything explicit.  I only even worked out that multiple UV sets were a thing, let alone that each additional UV set meant an additional triad would be parsed in the Version 3 Geometry spec (for so-flagged faces), by trial-and-erroring against files from a 3rd-party exporter.

**Comment by WestLangley** [comment]
Since you are learning, I suggest you also learn your way around the source code. I am sure your improvements to the docs would be welcomed by all.

And, by the way, try not to complain. There is a lot to learn. Everyone has to go through what you are going through. :)

**Comment by NNskelly** [comment]
Working on the docs now, in fits and spurts.  

The frustration, sadly, is less about THREE- which is an amazing new initiative- and more at being up against deadlines and a CEO who naturally assumes that the latest thing he's seen on the internets is a mature and viable product ready to integrate into client-facing projects on a 1-2 month delivery timeline.  By the time I've dug down through the 3rd-party tech stack the boss is enamored with, found THREE at the bottom (as an already minified lib), and tried to build up again from it and a bunch of assets artists have handed over from their "normal" process, I don't tend to have a lot of time left to dig into THREE itself. The result being that when the docs and any StackOverflow posts I can find newer than ~2012 don't line up with the behavior I observe, it's often faster to isolate a concrete repro citing the discrepancy than to do further digging and questioning "intended" vs documented behavior and hoping that someone else with a recognizably similar use case will come along with answers before I have to show results on my end.

And hey, at least it's getting the clarifications made fairly quickly :)  As loud as I know I've been in the past few weeks, I'm definitely on board with leaving a better-paved road behind me for future explorers (it just, as alluded, might not be same-day when a dozen or more pages of docs want the same callouts)

**Comment by NNskelly** [comment]
Working on the docs now, in fits and spurts.  

The frustration, sadly, is less about THREE- which is an amazing new initiative- and more at being up against deadlines and a CEO who naturally assumes that the latest thing he's seen on the internets is a mature and viable product ready to integrate into client-facing projects on a 1-2 month delivery timeline.  By the time I've dug down through the 3rd-party tech stack the boss is enamored with, found THREE at the bottom (as an already minified lib), and tried to build up again from it and a bunch of assets artists have handed over from their "normal" process, I don't tend to have a lot of time left to dig into THREE itself. The result being that when the docs and any StackOverflow posts I can find newer than ~2012 don't line up with the behavior I observe, it's often faster to isolate a concrete repro citing the discrepancy than to do further digging and questioning "intended" vs documented behavior and hoping that someone else with a recognizably similar use case will come along with answers before I have to show results on my end.

And hey, at least it's getting the clarifications made fairly quickly :)  As loud as I know I've been in the past few weeks, I'm definitely on board with leaving a better-paved road behind me for future explorers (it just, as alluded, might not be same-day when a dozen or more pages of docs want the same callouts)

**Comment by NNskelly** [comment]
Looking to add UV notes to the various material docs, I see UVs mentioned in the committed source but not yet or only partially reflected on the site.  History shows edits made May 7.  Are these changes still in review, and/or does it make sense to do another pass calling out the repercussions of the 2nd set of UVs on the repeat & offset Texture params?
