### ISSUE TITLE
ObjectLoader try to access document(DOM) in RaytracingWorker

### ISSUE THREAD

**Issue by drreparo** [mrdoob/three.js#11518]
##### Description of the problem 

When i develop single page application, RaytracingWorker.js should be put on public.

In this case,
1. THREE (in RaytracingWorker.js) can't use three.js in node_modules.
  - Can't share THREE.Cache
2. In RaytracingWorker.js, ObjectLoader.parse - ImageLoader occur document.createElementNS. but, Worker can't get document and DOM Element.

##### Three.js version

- [x] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
> Can't share THREE.Cache

Why not?

> ObjectLoader.parse - ImageLoader occur document.createElementNS. but, Worker can't get document and DOM Element.

Hmm, maybe we should use `new Image()`...?

**Comment by primeiros** [comment]
> Can't share THREE.Cache

Umm.. RaytracingRenderer have to chase RaytracingWorker's path. But if they are placed in same path, it was lost RaytracingWorker path when it was built to Single Page Application. Therefore, RaytracingWorker placed in public path not affected build process to SPA, it can't get THREE.js in node_module.

> ObjectLoader.parse - ImageLoader occur document.createElementNS. but, Worker can't get document 
and DOM Element.

Hmm..  I will try to use it
