### ISSUE TITLE
[question]Points returned by GeometryUtils.randomPointsInGeometry can't be added to scene?

### ISSUE THREAD

**Issue by 349989153** [mrdoob/three.js#11516]
I'm trying to form an object's shape with even distribution of points. I've learned that there is `GeometryUtils.randomPointsInGeometry`  can be made use of ,so I decided to make a small scale experiment, with the code of  offcial example https://threejs.org/examples/?q=geome#webgl_geometries.

What I did is modify the parts of code of `three.js\examples\webgl_geometries.html` into 

```
//object = new THREE.Mesh(new THREE.TorusGeometry(50, 20, 20, 20), material);
//object.position.set(-200, 0, -200);
var points = THREE.GeometryUtils.randomPointsInGeometry(new THREE.TorusGeometry(50, 20, 20, 20), 200);//This statement worked as expected and returned an array filled with 200 points.
var pointSpace = new THREE.Points(points, new THREE.PointsMaterial({
  color: 0xfff000,
  size: 1
}));// This statement worked fine, too.
//scene.add(object)
scene.add(pointSpace);//This one throw an error
```

The last statement throw error 
﻿

> Uncaught TypeError: Cannot read property 'center' of undefined
>     at Sphere.copy (three.js:8183)
>     at Frustum.intersectsObject (three.js:8938)
>     at projectObject (three.js:21261)
>     at projectObject (three.js:21306)
>     at WebGLRenderer.render (three.js:20994)
>     at render (webgl_geometries.html?_ijt=e4c51gl3tn5bhfhiitvrc3d2nr:188)
>     at animate (webgl_geometries.html?_ijt=e4c51gl3tn5bhfhiitvrc3d2nr:165)

How can I solve this problem or is there anything I can refer to ? Please help me and thank in advance.

**Comment by Mugen87** [comment]
The good news is that your issue is not a bug. You just have to create a geometry object and pass this to the `THREE.Points` constructor and not the generated points itself.

```javascript
var geometry = new THREE.Geometry();
geometry.vertices = points;
var pointSpace = new THREE.Points( geometry, new THREE.PointsMaterial( {
  color: 0xfff000,
  size: 1
} ) );
```
