### ISSUE TITLE
JSON Loader does not support ShapeGeometry

### ISSUE THREAD

**Issue by ByDenis** [mrdoob/three.js#11526]
Hey. JSON Loader does not support ShapeGeometry(ShapeBufferGeometry) and ExtrudeGeometry (ExtrudeBufferGeometry). But the unloading works. Is it possible to add this feature to when?
- [ ] Dev
- [ x] r85
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [x ] Firefox
- [ x] Internet Explorer

##### OS

- [] All of them
- [x ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
Have you tried using the [ObjectLoader](https://threejs.org/docs/#api/loaders/ObjectLoader) or [BufferGeometryLoader]https://threejs.org/docs/#api/loaders/BufferGeometryLoader) instead?

**Comment by ByDenis** [comment]
Used ObjectLoader. Now I will try BufferGeometryLoader.

**Comment by ByDenis** [comment]
BufferGeometryLoader. Writes -"json.data is undefined".
I unload the .toJSON () method. Tried to unload mesh and geometry separately. The mistake is the same.

**Comment by ByDenis** [comment]
File:
{"metadata":{"version":4.5,"type":"BufferGeometry","generator":"BufferGeometry.toJSON"},"uuid":"F542C6D7-8AEC-417E-A70E-23C6CC22480C","type":"ShapeBufferGeometry","shapes":{"arcLengthDivisions":200,"curves":[{"arcLengthDivisions":200,"v1":{"x":0,"y":0},"v2":{"x":0,"y":2}},{"arcLengthDivisions":200,"v1":{"x":0,"y":2},"v2":{"x":2,"y":0}},{"arcLengthDivisions":200,"v1":{"x":2,"y":0},"v2":{"x":0,"y":0}}],"autoClose":false,"currentPoint":{"x":0,"y":0},"holes":[]}}

**Comment by looeee** [comment]
OK, as far as I can see ObjectLoader does not support ShapeBufferGeometry. It might work to use the FileLoader to load the JSON

```js
const loader = new THREE.FileLoader();

loader.setResponseType ( 'json' );

loader.load( 'yourFile', ( json ) => {
    const curvesArray = json.shape.curves;
} );

Then build a new shape from that curveArray.

**Comment by ByDenis** [comment]
Got it. Is there any plan ShapeBufferGeometry in ObjectLoader?

**Comment by Mugen87** [comment]
I think we need some changes in the code because all relevant entities for `ShapeGeometry` and `ShapeBufferGeometry` like `Shape`, `Path` or curves like `QuadraticBezierCurve`, `CubicBezierCurve` or `SplineCurve` are not fully ready for serialization and deserialization. 

For example, we need a `type` property (see geometries) in order to determine the type of curve in a json file. And `ObjectLoader` has to parse and rebuild all mentioned entities. 

I'm not sure how much refactoring is necessary to make things work.

**Comment by Mugen87** [comment]
I've seen that there is already an issue for this enhancement request. I will close this one and mark it as a duplicate. We should continue the conversation here #8007
