### ISSUE TITLE
Using UPERCASE_STYLE for constants?

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#1152]
So @chandlerprall was suggesting having a version variable somewhere in the API that a plugin or something that sits on top can use. He was suggesting `THREE.version`. The idea sounded good to me but the naming didn't feel right. If it's a constant it should be upercase `THREE.VERSION`. @chandlerprall then pointed out that maybe should be `THREE.Version` as that's [how we're handling the constants in other places](https://github.com/mrdoob/three.js/blob/master/src/textures/Texture.js).

That made me think that probably this needs reconsideration. Right now there is no difference between `CubeReflectionMapping` and `RepeatWrapping`. Even if the first one is a method and the second a constant. Also, they're poluting the root of the namespace and it makes it hard to know where these constants can be used and also which file to look for (when messing with the code).

So what about changing `THREE.CubeReflectionMapping` to `THREE.Texture.CubeReflectionMapping` `THREE.RepeatWrapping` to `THREE.Texture.REPEAT_WRAPPING`, ... ?

**Comment by dubejf** [comment]
:white_check_mark: THREE.REVISION is already implemented

As for the rest:
- Changing constants to UPPERCASE would break at lot of code for little benefit
- three.js kinda use semver, as all releases contain breaking changes (not sure if we are at 72.0.0 or 0.72.0 though)
- I think that the momentum for dart has dissipated.
