### ISSUE TITLE
BufferGeometry.setFromObject should handle BufferGeoemtry

### ISSUE THREAD

**Issue by vidartf** [mrdoob/three.js#11528]
If `BufferGeometry.setFromObject()` is called with a mesh, it [checks `object.geometry.isGeometry`](https://github.com/mrdoob/three.js/blob/44087407c20d29e0a18b383b82b03e6fa043febc/src/core/BufferGeometry.js#L326). This fails if the geometry is a `BufferGeometry`, which sets `isBufferGeometry = true`, but leaves `isGeometry` undefined.

Expected behavior / proposed fix:
If geometry has `isBufferGeometry === true`, simply copy.

This is reasonably easy to work around:
```js
if (object.geometry && object.geometry.isBufferGeometry) {
  target.copy(object.geometry);
} else {
  target.setFromObject(object);
}
```
However, I still think this behavior should be included, as the work-around kind of defeats the purpose of the function.

Note:
Should `BufferGeometry.updateFromObject` also receive a similar fix? It is not immediately clear from the documentation how it should differ from `setFromObject`, although the code is clearly different.

##### Three.js version

- [x] Dev
- [x] r85

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Why are you using `BufferGeometry.setFromObject()` with a mesh, that already has a buffer geometry? The method is obviously not designed to work in this way. Generally, `three.js` only performs consistency checks, when it's absolutely necessary. I don't think this is the case here...

**Comment by mrdoob** [comment]
Hmm... That method was done for transitioning from `Geometry` to `BufferGeometry`. So I guess it's somewhat internal. Maybe we should try to hide it, before more people gets confused?

**Comment by vidartf** [comment]
@Mugen87 : I was using it as part of a routine to create a (modified) copy of an existing object's geometry (which could be either `Geometry` or `BufferGeometry`). Basically, the line in question would be `var newGeom = new BufferGeometry().setFromObject( passedObject );`, then do some modifications to the buffer attributes of the new geometry.

> The method is obviously not designed to work in this way. 

The reason I filed the issue was because it didn't behave as I expected from its signature/documentation, so to say this is obvious seems rather dismissive. I'm perfectly OK with the resolution being a clarification of the docs or deprecation/internalization. A simple "not worth the hassle" answer is of course also OK. I simply wanted to point out a source of confusion in the API (user feedback).

**Comment by sasha240100** [comment]
@vidartf Why not just check whether it has `BufferGeometry` or not and make a copy from that geometry if it is: `var newGeom = passedObject.geometry === BufferGeometry ? passedObject.geometry.clone() : new BufferGeometry().setFromObject( passedObject );`

**Comment by Mugen87** [comment]
> so to say this is obvious seems rather dismissive.

Sry, i did not mean it like that. It is of course good to know when parts of the API are unclear.

The suggestion from @sasha240100 might help you further although i would check `object.geometry.isBufferGeometry === true`.
