### ISSUE TITLE
Transparency and DoubleSide: A bottle neck of shader code or WebGL limitation?

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#11539]
##### Description of the problem 

From history, I got many answers of limitation of WebGL on self-transparency with double side.
However, recently I use sketchfab viewer and see very good result.
I think we should be able to do it in threejs, too.

![screenshot 145](https://user-images.githubusercontent.com/6780177/27251830-f6ddcb68-5379-11e7-83ba-98228f85e79f.png)

![screenshot 146](https://user-images.githubusercontent.com/6780177/27251826-e8d87748-5379-11e7-8707-e5d8192fb5d6.png)

##### Three.js version
- [ ] Dev
- [x ] r85
##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
>I think we should be able to do it in threejs, too.

You can.
```
material.depthWrite = false;
```

Or, render front faces and back faces [separately](https://threejs.org/examples/webgl_geometry_convex.html).

**Comment by whatisor** [comment]
Disable depth write is not solution.
I will try to render front and back separately then.
Thanks

**Comment by whatisor** [comment]
Hi, Rendering 2 times for 2 sides is not solution, it is same with Depth Write Disable.
Do you think Geometry Face Ordering work?
I think we should support this feature. Without it, I alway heart it is rendering bug or limitation :)

**Comment by WestLangley** [comment]
Please show a live example demonstrating your use case, and explain why you feel neither approach is satisfactory.

**Comment by whatisor** [comment]
Hi, please just use Threejs sample, I configed like this:
![image](https://user-images.githubusercontent.com/6780177/27306980-e6e3dcda-5571-11e7-8af1-d52823aa611a.png)

**Comment by WestLangley** [comment]
Please provide a live example of self-transparency _that renders properly in sketchfab_, but not in three.js.

**Comment by whatisor** [comment]
Here you are
https://skfb.ly/68GTv

**Comment by whatisor** [comment]
this is almost perfect
https://skfb.ly/R6tZ

**Comment by mrdoob** [comment]
As you can see, even Sketchfab can't get transparencies right. Transparencies is one of those unsolved problems in realtime graphics. You can get things to look right, but you need to understand the problem well.

**Comment by whatisor** [comment]
Hi, although it is not perfect, I cannot see any problem with face color like our threejs.
Do you know what that it?(You can easily see dark and bright triangle in threejs screenshot)

**Comment by WestLangley** [comment]
>Do you know what that is? (You can easily see dark and bright triangle in three.js screenshot)

We can't answer that question because we do not know what you are doing.

**Comment by whatisor** [comment]
Hi, ok, I knew issue now:
When I apply sortFacesByMaterialIndex to save performance (for some big geometry like this discussion https://github.com/mrdoob/three.js/issues/11510).
Transparent issue come like this:

Before:
![screenshot 150](https://user-images.githubusercontent.com/6780177/27510576-36b48c62-593e-11e7-8d8c-dbe003decd25.png)
After:
![screenshot 149](https://user-images.githubusercontent.com/6780177/27510579-3dc27ef6-593e-11e7-80d3-640e773dddd7.png)
