### ISSUE TITLE
Blender export to JSON not exporting animations, bones, or skinning

### ISSUE THREAD

**Issue by chuckhacker** [mrdoob/three.js#11542]
##### Description of the problem 

Unable to export model with animation, no bones or skins are exported either.

JSON only contains:

```
"animations":[{
    "tracks":[],
    "fps":30,
    "name":"default"
}]
```

Export settings:

![screenshot from 2017-06-17 20-47-04](https://user-images.githubusercontent.com/143290/27257921-95ce9fa8-539e-11e7-83c8-cecda660ee97.png)

##### Three.js version

- [x] Dev

##### Blender version

2.78

##### Repro test case

Test case (contains Blend 3D model used, texture PNG file, Blender plugin repro, and bad JSON output missing the animations/bones/skins):
 
[broken.zip](https://github.com/mrdoob/three.js/files/1082889/broken.zip)

**Comment by chuckhacker** [comment]
The JSON from anim.blend (test case that should work) is also missing anything animation-related (bones, skinning attributes, keyframes):

[anim.json.txt](https://github.com/mrdoob/three.js/files/1082902/anim.json.txt)
^ had to rename to .txt extension in order for GitHub to permit me to upload it :|

**Comment by chuckhacker** [comment]
Solved. We finally found the sufficiently buried menu:

![screenshot from 2017-06-18 07-40-48](https://user-images.githubusercontent.com/143290/27258145-7e9981f0-53a7-11e7-991e-565755a023d8.png)

As feedback, when three very smart people can't figure this out after several hours of trial-and-error before discovering the hidden menu, the UI for this needs to be a bit more obvious -- or at least mentioned in the README.md documentation.

**Comment by WestLangley** [comment]
@chuckhacker Perhaps you will make a contribution and improve the UI and/or docs. :)

**Comment by chuckhacker** [comment]
I _might_ have some time tomorrow to throw something together (docs are definitely easier to update than UI for someone completely unfamiliar with your code base).

**Comment by carlosservipro** [comment]
But where is that menu?

**Comment by Mugen87** [comment]
> But where is that menu?

Do you mean "Vertex Groups"? It's in the "Object Data" Tab, see

![image](https://user-images.githubusercontent.com/12612165/37240524-ec942bf8-244c-11e8-8f47-5255ed4480df.png)
