### ISSUE TITLE
Support for AnimationAction sub-animations with startAt and endAt and units of _frames_ along with seconds

### ISSUE THREAD

**Issue by chuckhacker** [mrdoob/three.js#11541]
Actually, it looks like there isn't a way of specifying a sub-animation. Right now, Blender Godot Collada exporter only supports 1 animation.

So my artists' solution is to have each animation concatenated like so:
walk goes 0 to 0.933 seconds
idle goes 0.933 to 1.833 seconds

But frames is easier to work with than seconds.

How can I play these sub animations?

**Comment by booxie** [comment]
Best to be able to use seconds / and / or _frames_ . Yr

**Comment by chuckhacker** [comment]
Edited issue title and description to be much more clear.

**Comment by chuckhacker** [comment]
@booxie To be clear, this isn't a Blender Exporter issue. It is a feature request for AnimationAction.

**Comment by booxie** [comment]
Yeah , a frame can be is less than a second

**Comment by tbriley** [comment]
Have had similar issues - I was thinking it would actually just make sense to be able to define your actions or clips this way - ie, by feeding them start and end times (and/or frames) on clip or action creation.

**Comment by donmccurdy** [comment]
Related: https://github.com/mrdoob/three.js/pull/13430

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models

**Comment by Mugen87** [comment]
`AnimationUtils.subclip()` should be sufficient for this use case.
