### ISSUE TITLE
Renderer reset prevents setting background to black

### ISSUE THREAD

**Issue by vidartf** [mrdoob/three.js#11557]
##### Description of the problem 

A `WebGLRenderer` is used to render a scene with:
 - a sprite
 - background color set (or renderer gets clear color set) to another color than black (e.g. blue)

Next, the scene's background color (or render clear color) is set to black, and the scene rendered again. The background color will stay the same value as before.

For example see: https://jsfiddle.net/w9t5h1h2/3/
In the example, double-clicking the canvas will cycle the background color between black, red and blue. You can see that it never gets set back to black, but rather keeps the red color when it should have been black. Setting the color to blue/red again works.

The problem seems to be caused by the `SpritePlugin` calling `renderer.resetGLState()`, which resets the tracked `currentClearColor` to black, while leaving the context's clear color untouched.

A workaround is to use nearly-black (`0x000001`) for the background instead of black.

##### Three.js version

- [x] Dev
- [x] r85

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Related: #11001

**Comment by Mugen87** [comment]
I think we can mark this one as a duplicate. The problem is already tracked in #11001.
