### ISSUE TITLE
fbxloader skeleton animation not match

### ISSUE THREAD

**Issue by leoboboyan** [mrdoob/three.js#11553]
##### Description of the problem 
Hi, thanks for your working with 3js, i have been using it in my program.
lately, i found that the newest dev fbxloader support binary format now, that is cool !
but when i using it, it shows wrong animation, but i don't know why?
so, i come to asking for help.
thanks a lot!

![7104a049-9ab6-47bb-8ed7-6fe2f045a47a](https://user-images.githubusercontent.com/21359568/27269262-14e5067a-54e8-11e7-8a72-33a5b7ce1cdf.png)

it's definitely not right..

here is the file:

[bird.FBX.zip](https://github.com/mrdoob/three.js/files/1083787/bird.FBX.zip)
##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by leoboboyan** [comment]
@takahirox @Kyle-Larson

**Comment by leoboboyan** [comment]
Needs some help, any body ? @mrdoob 
i have tried convert it to other format, with no luck.
all i found is this : [https://github.com/mrdoob/three.js/issues/8511](url)
but still , i don't know how can i fix the fbxloader

**Comment by leoboboyan** [comment]
by the way , the fbx file looks fine in other tools like assimp viewer , or autodesk fbx viewer , so i guess , it might be some transform does't apply to the skin ?
it cost me 3 days, and make me crazy, i am learning the fbx format now.  :(

**Comment by takahirox** [comment]
Seems like the zip file doesn't include texture files.

**Comment by leoboboyan** [comment]
> Seems like the zip file doesn't include texture files.

that doesn't matter, it's animation works fine on sketchfab or other viewer, but import by our fbxloader, it's really weird, why does this happen? how can we fix it ?
thanks for your reply, and sorry for my poor english.. :)

**Comment by takahirox** [comment]
`FBXLoader` fails to load the FBX file if the texture files don't exist. I mean, developer can't test.

**Comment by leoboboyan** [comment]
> FBXLoader fails to load the FBX file if the texture files don't exist. I mean, developer can't test.

I see, i will ask our modeler for the texture files and provide another fbx file seems have another problem, wish it can helps you to improve.
wait a minute, i will do it now.

**Comment by leoboboyan** [comment]
Here is the bird with it's texture files:
[bird.zip](https://github.com/mrdoob/three.js/files/1096695/bird.zip)

And here is another fbx file:
[animation.fbx.zip](https://github.com/mrdoob/three.js/files/1096698/animation.fbx.zip)
it throw error when fbxloader parseAnimations func

@takahirox

**Comment by takahirox** [comment]
About animtion.fbx.zip, it doesn't throw any errors with the latest dev.
Probably it was fixed by the recent updates.

**Comment by takahirox** [comment]
Can you share the right animation video or something?

**Comment by leoboboyan** [comment]
sorry for so long, my disk has broken yesterday. :(
I have tried the newest dev version, and animation.fbx is working now, thanks !
And you can find the correct bird here: [https://skfb.ly/68RvV](https://skfb.ly/68RvV) @takahirox 

And by the way, thank you for the specular/grossiness workflow code, it's not so important for us, but it's very important for modelers. threejs should be able to solve this problem.

And it's so pity that we delete face4, because it's useful too. @mrdoob

**Comment by leoboboyan** [comment]
And i found that there is a little problem with animation.fbx too, in threejs, there is a flash at the end of the animation, and here is how it works on sketchfab: https://skfb.ly/68Syp @takahirox

**Comment by leoboboyan** [comment]
And a new test throw an new error, file : [m1911_finalFire.fbx.zip](https://github.com/mrdoob/three.js/files/1102027/m1911_finalFire.fbx.zip)

sketch link: https://skfb.ly/68SyG

sketch use osg as lib, i have tried three days, never install success, haha..
OSG can convert the fbx format to osgjs format, I think maybe you can find out how osg deal with the fbx format, so you can fix the fbxloader ?

**Comment by takahirox** [comment]
Looking into this issue but fixing isn't so easy?
Can anyone help?

**Comment by makc** [comment]
> Looking into this issue but fixing isn't so easy.

Looking into FBXLoader.js and not seeing `.transform` anywhere. so it's read but never used, basically.

> Can anyone help?

do you have a code that loads bird.fbx and shows the skeleton helper

**Comment by liuhongyi0101** [comment]
------------------ 原始邮件 ------------------
发件人: "makc";<notifications@github.com>;
发送时间: 2017年12月12日(星期二) 上午10:31
收件人: "mrdoob/three.js"<three.js@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [mrdoob/three.js] fbxloader skeleton animation not match (#11553)



 
Looking into this issue but fixing isn't so easy.
  
Looking into FBXLoader.js and not seeing .transform anywhere. so it's read but never used, basically.
  
Can anyone help?
  
do you have a code that loads bird.fbx and shows the skeleton helper

**Comment by makc** [comment]
@liuhongyi0101 I guess there was supposed to be an attachment, but it did not make it through the email gateway. try to drop it to the web comment form

**Comment by looeee** [comment]
> Looking into FBXLoader.js and not seeing .transform anywhere. so it's read but never used, basically.

@makc I have a PR open (#12829) that adds support for `.transformLink` on bones. I haven't added  `.transform` yet, but I think the process should be similar - that is, check if there is a `poseNode` associated with the bone's parent, and if not apply the `.transform` to the parent.

**Comment by looeee** [comment]
Tested this since #12829 and animation on bird.FBX is working correctly now. Closing.
