### ISSUE TITLE
Inline documentation

### ISSUE THREAD

**Issue by tentone** [mrdoob/three.js#11550]
##### Inline documentation

Hi, this has probably been discussed a couple of time already, i wasn't able to find recent issues regarding this).

Why not document three.js inline with code using jsdoc or similar?

That would probably help a lot to reduce documentation fragmentation and accelerate integration of new developers with already existing code? It would also help to integrate API docs in external editors (threejs editor, super powers, sublime, etc)?

I'm available to help document some of the existing code.

Thanks a lot!

Cumps

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/4725#issuecomment-41833647

**Comment by tentone** [comment]
I really dont like to have tons of documentation lines in the code, but since pretty much every IDE nowadays support comment folding for documentation i think its not that bad.

I believe inline documentation would be a big step forward to help removing the amount of PR being created to update documentation due to changes in the API.

**Comment by mrdoob** [comment]
> I believe inline documentation would be a big step forward to help removing the amount of PR being created to update documentation due to changes in the API.

Hmm... Why is that a problem? I actually prefer it that way. Avoids additional merge conflicts.

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/issues/12580#issuecomment-345797204

**Comment by zwcloud** [comment]
So if a __new__ user of three.js want to change the intensity of a [DirectionalLight][1], he or she will have to:
1. open https://threejs.org/docs/index.html
2. type `DirectionalLight`
3. click `DirectionalLight` link
4. search for `intensity`/`strength` in the doc but find nothing, then possibly luckily see *See the base Light class for common properties.*.
5. click `See the base Light class for common properties` link
6. search for `intensity`/`strength`, OK found it finally

Why not just support JSDoc? In a modern IDE,

```js
var light = new THREE.DirectionalLight(0xffffff, 1);
light.i //(***)
```

Auto-complete happens at (***), and it shows a tooltip saying

> The light's intensity, or strength.
> In physically correct mode, the product of color * intensity is interpreted as luminous intensity measured in candela.
> Default - 1.0.

It's apparent that which one is better. You developers are quite familiar with the API and usage, but for a new user, NO! Even for an old user of threejs, JSDoc can also bring many benefits.

Why JSDoc is important? Because it makes intellisense possible in all kinds of IDE.

> IntelliSense is the general term for a number of features: List Members, Parameter Info, Quick Info, and Complete Word. These features help you to learn more about the code you are using, keep track of the parameters you are typing, and add calls to properties and methods with only a few keystrokes.

I would like to contribute about this.

[1]: https://threejs.org/docs/index.html#api/lights/DirectionalLight

**Comment by mrdoob** [comment]
Is there an alternative to JSDoc that doesn't need to be part of the source? Can [tern](https://github.com/mrdoob/three.js/blob/dev/editor/js/libs/tern-threejs/threejs.js) be repurposed?

**Comment by looeee** [comment]
@mrdoob there's just a little bit more work involved to get that tutorial working. I posted some details on [the forum](https://discourse.threejs.org/t/three-js-autocomplete-with-vs-code/1636/2?u=looeee) a while back.

**Comment by donmccurdy** [comment]
FWIW it might be possible to write JSDoc _outside_ of the source files, and to generate API docs, examples, and autocomplete bindings from that. For example, glTF-Validator (which is compiled from Dart) does this — https://github.com/KhronosGroup/glTF-Validator/blob/master/tool/npm_template/index.js. Could imagine having a JS file that looks like this:

```js
/**
 * GLTFLoader is a loader for glTF 2.0 assets. Lorem ipsum...
 */
var GLTFLoader;

/**
 * Parses a string or buffer to glTF asset.
 * @param {string|ArrayBuffer} asset
 * @param {function} onLoad
 */
GLTFLoader.prototype.parse = function ( asset, onLoad ) {};

/* ... */
```

That doesn't reduce maintenance really (maybe slightly easier to write docs this way than HTML, subjective opinion) but does make the result machine-readable.

**Comment by mrdoob** [comment]
Is there a system that...?

* Doesn't have build process
* Lives outside the source
* Supports localisation
* Can be used for VSCode autocomplete
* Can be used for search in the docs

**Comment by tentone** [comment]
Its possible to write JSDoc in separated files.

But i think that threejs should really embrace inline documentation.

It might be ugly (that it is) but its easy to maintain. Since it it attached to the code a person that changes code can immediately change documentation to match.

```
 * Image class is used to store image data that is used to create Textures.
 * 
 * Images can be stored in mutiple formats.
 *
 * Some formats (tga, tiff, etc) are converted to png or jpeg in order to work with the rest of the code.
 * 
 * @class Image
 * @constructor
 * @extends {Resource}
 * @module Resources
 * @param {ArrayBuffer, Base64, String} data Can be URL to image, ArrayBuffer data or base64 encoded data.
 * @param {String} encoding Image encoding, required for ArrayBuffer data.
 */
```

**Comment by mrdoob** [comment]
Does JSDoc support localisation?

**Comment by looeee** [comment]
I would support this if the JSDocs can stay out of the source files. 

However, if we do go this path, then we really need to make the docs at `threejs.org/docs` be generated automatically from the JSDocs. Currently we only have one place that the docs can be out of date, with JSDoc AND online documentation then there are two places... and they _will_ get out of sync.

**Comment by tentone** [comment]
For nunuStudio in using YUIDoc http://yui.github.io/yuidoc/syntax/index.html that can be written in separated files but does not support localization :(

**Comment by mrdoob** [comment]
> Currently we only have one place that the docs can be out of date, with JSDoc AND online documentation then there are two places... and they will get out of sync.

I do not think out of sync documentation is a problem.

**Comment by looeee** [comment]
> I do not think out of sync documentation is a problem.

It will certainly be confusing for users if the online documentation and the editor inline documentation don't agree.

**Comment by mrdoob** [comment]
Those things are temporary.
