### ISSUE TITLE
 Renderer Size issue in Chrome vs 58 

### ISSUE THREAD

**Issue by ankitthapliyal93** [mrdoob/three.js#11567]
##### Description of the problem 

Issue: webgl renderer is pushed down to the bottom left corner and the scene is getting clipped to be only  visible in a small portion of the screen. Is working fine in all versions before chrome version 58.

//inside initial init function init function:

    this.canvas.width = window.innerWidth;
        this.canvas.height = window.innerHeight;
        this.m_nWidth = this.canvas.width;
        this.m_nHeight = this.canvas.height;
        // create renderer
        this.m_cRenderer = (OPENSPACE.ViewUtil.isWebGLAvailable(canvas)) ?
            (new THREE.WebGLRenderer({
                canvas: this.canvas,
                antialias: true,
                alpha: true
            })) :
            (new THREE.CanvasRenderer({
                canvas: canvas,
                antialias: true,
                alpha: true
            }));

        this.m_cRenderer.setClearColor(this.m_xSceneColor, 1);
        // set the viewport size
        this.m_cRenderer.setSize(this.m_nWidth, this.m_nHeight);
        // set rendering parameters
        this.m_cRenderer.setFaceCulling(THREE.CullFaceNone); // disable face culling
        // disable viewport auto clear to enable HUD overlay on 3D scene
        this.m_cRenderer.autoClear = false;
        this.m_cRenderer.sortObjects = false; 

Inside Update function on window resize for renderer :+1: : 

this.canvas.width= window.innerWidth;
            this.canvas.height=window.innerHeight;
            this.m_nWidth = this.canvas.width;
            this.m_nHeight = this.canvas.height;
            this.m_cPanowalk.updateCameras(this.m_nWidth, this.m_nHeight);

            // set the viewport size
            this.m_cRenderer.setSize(this.m_nWidth, this.m_nHeight, true);
            this.m_cRenderer.setViewport(0, 0, this.m_nWidth, this.m_nHeight); 

Note:
* Everything is getting updaed correctly. All the values of canvas get correct values.
* Renderer does not update the the screen accordingly.

##### Three.js version

- [ ] Dev
- [ ] r85
- [x] r79

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android on certain mobiles. like mi LEdTv
- [ ] iOS
![screenshot_2017-06-20-13-18-29-685_com android chrome](https://user-images.githubusercontent.com/25146456/27322326-54684dba-55bb-11e7-85ab-ce0ab0a45005.png)
![screenshot_2017-06-20-13-18-36-668_com android chrome](https://user-images.githubusercontent.com/25146456/27322327-546acbf8-55bb-11e7-91c9-c96701487e67.png)

**Comment by Mugen87** [comment]
Any chance you provide a [fiddle](https://jsfiddle.net/hfj7gm6t/) that shows the error?

What happens if you use a more recent version of `three.js`? Besides, does the error occur with Firefox on your smartphone?

**Comment by ankitthapliyal93** [comment]
Providing a fiddle for it will be difficult. This guy faces a same issue : https://stackoverflow.com/questions/44373088/web-gl-rendering-issue-in-chrome-58

And yes, It works fine with firefox. The issue started with chrome v58 and that too on certain android phones like mi, LETV. 

It works fine with other phones like nexus 4,5 one plus 3 and many more.

**Comment by gauravrane** [comment]
#11368

**Comment by Mugen87** [comment]
Closed in favor of #11368
