### ISSUE TITLE
mesh.localToWorld weird behaviour

### ISSUE THREAD

**Issue by KzMz** [mrdoob/three.js#11564]
##### Description of the problem 

Good evening!

In my project I'm creating a TextMesh from a font geometry and put into a pivot empty object. I need to get the world coordinates of every vertex of the TextMesh because I need to work with them to do some transformations of the text (custom bending etc...). 

Here's the code:

```
var pivot = new THREE.Object3D();
pivot.add(textMesh);

pivot.position.set(x, y, z);
pivot.rotation.set(roll, pitch, yaw);
scene.add(pivot);

pivot.updateMatrixWorld(true);
for(var i = 0; i < textMesh.geometry.vertices.length; i++)
{
    var worldCoords = textMesh.localToWorld(textMesh.geometry.vertices[i]);
}
```

What happens is that my textMesh has its position changed by the "localToWorld" function, which I didn't expect. 
Is there a way to get the world location of each vertex of the mesh without making the mesh move?
What am I doing wrong?
Is there an easier way to do a bending of a text mesh along a cylinder? I have already checked MOD3 and such and couldn't find anything which works with my setup so I was trying to do it myself.

Thank you for you help!

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Sorry, this is not a help site. Try [stackoverflow](http://stackoverflow.com/questions/tagged/three.js) or the [forum](https://discourse.threejs.org).
