### ISSUE TITLE
3MFLoader needs async handling of JSZip

### ISSUE THREAD

**Issue by ericberberich** [mrdoob/three.js#11583]
##### Description of the problem 

3MF Loader relies on `JSZip(data)` constructor, but newer versions of JSZip use loadAsync.

##### Three.js version

[x] r86

##### Browser

[x] All of them

##### OS

- [x] All of them

**Comment by mrdoob** [comment]
We rely on sync parsing though... We use this pattern:

```js
var loader = new THREE.3MFLoader();
var model = loader.parse( data );
```

**Comment by ericberberich** [comment]
It's in the parse function:

The `new JSZIP(data)` in line 48 returns `undefined` which makes zip `undefined`.

See https://github.com/Stuk/jszip/blob/master/lib/index.js

```
function JSZip() {
    // if this constructor is used without `new`, it adds `new` before itself:
    if(!(this instanceof JSZip)) {
        return new JSZip();
    }

    if(arguments.length) {
        throw new Error("The constructor with parameters has been removed in JSZip 3.0, please check the upgrade guide.");
    }

    // --> snip <--

}
```

**Comment by mrdoob** [comment]
😕

**Comment by ericberberich** [comment]
yeah sorry .... libs change more and more to async handling ..

**Comment by mrdoob** [comment]
Seems like we'll have to stay with an old version or switch to a library that allows synchronous.

**Comment by takahirox** [comment]
@mrdoob Do you still prefer sync JSZip? Yeah, sync method is easy to use and if we switch to async we break compatibility of .parse(). But I think less blocking the main thread by offloading this type of heavy processing like decoding/encoding getting popular so it may be a good time to rethink of the async option.

**Comment by Mugen87** [comment]
> But I think less blocking the main thread by offloading this type of heavy processing like decoding/encoding is getting popular

Just to clarify: Because it's async it does not mean the code is executed in a worker. The code is still executed in the main thread.

Apart from that, what would be the benefits of an upgrade? Does it fix a bug? Or performance issue? I does not seem so.

As long as there is no compelling reason, I would perform a change which does result in migration effort for the user.

**Comment by takahirox** [comment]
> Just to clarify: Because it's async it does not mean the code is executed in a worker. The code is still executed in the main thread.
>
> Apart from that, what would be the benefits of an upgrade? Does it fix a bug? Or performance issue? I does not seem so.

https://github.com/Stuk/jszip/pull/195

> rewrite the code into workers which are asynchronous

And this should be the benefit because of less main thread blocking.

> The code is still executed in the main thread.

I'm not sure if I understand correctly, but do you mean JSZip 3 still runs in main thread?

**Comment by takahirox** [comment]
Ah, wait. Does "Worker" in the thread not mean WebWorker...?
