### ISSUE TITLE
Collada animations, KeyFrameAnimation removed ? 

### ISSUE THREAD

**Issue by SebastienFPRousseau** [mrdoob/three.js#11585]
##### Description of the problem 
Hello, 

The class `KeyFrameAnimation` has been removed from  the docs and the examples. How am I supposed to animate my collada model when kinematics and skinning methods are not working at all ? How can i use the `collada.animations` with this latest release ( r86 ) ?

```
const loader = new ColladaLoader();

loader.load(source, function(collada) 
{
	const obj = collada.scene;
        const animations = collada.animations; // I have to use this.

	obj.traverse(function(child)
	{
		child.castShadow = true;
		child.receiveShadow = true;
	});
});
```

Thanks for reading. 

##### Three.js version

- [ ] Dev
- [x] r86
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
You can use `ColladaLoader2` for skeletal animations. Kinematics support is not yet implemented though.

Besides, the following [examples](https://threejs.org/examples/#webgl_loader_collada_skinning) shows how you can use the old `ColladaLoader` with skeletal animations and the core animation system. 

`KeyFrameAnimation`. `Animation` and `AnimationHandler` have been deprecated for almost two years and were removed from the project with `R86`. If you still depend on these entities, you can still checkout `R85`. These files won't be changed anymore.

**Comment by Mugen87** [comment]
BTW: The kinematics examples still works with `R86`: https://threejs.org/examples/#webgl_loader_collada_kinematics

**Comment by SebastienFPRousseau** [comment]
Thanks for reply. 

I didn't know that. Do you know some examples with the `ColladaLoader2`, please ?

**Comment by Mugen87** [comment]
These two are not yet official examples, but they work with the `ColladaLoader2` in the `master` branch.

https://yume.human-interactive.org/examples/collada/index.html
https://yume.human-interactive.org/examples/collada/multi.html (Heads up! Big collada file)

**Comment by SebastienFPRousseau** [comment]
Thanks for all !

I'll try this.
