### ISSUE TITLE
FBX loader problem with transparency

### ISSUE THREAD

**Issue by CarlBateman** [mrdoob/three.js#11598]
##### Description of the problem 

When importing FBX, some transparency information is lost.

Using the FBX loader example from Threejs.org site, just loading different model. Model at pearl_walk.fbx to http://webglworkshop.com/fbx/standing_idle.fbx

Looks like this
![image](https://user-images.githubusercontent.com/2813834/27481051-a9555454-5812-11e7-8dfd-615aa0d5da53.png)

Should look like this (from PlayCanvas) Note: PlayCanvas uses "Alpha to coverage"
![image](https://user-images.githubusercontent.com/2813834/27481301-da09ee7e-5813-11e7-9565-d5ea35c052aa.png)

or this (from SketchFab)
![image](https://user-images.githubusercontent.com/2813834/27481512-d4d4bbae-5814-11e7-97ba-888083923b82.png)

##### Three.js version

- [ ] Dev
- [x] r65

##### Browser

- [x] All of them

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by tauba** [comment]
I am having the very same problem here with another FBX file. I cannot use transparency on my model

And I am facing this output on the console

FBXLoader.js:542 
THREE.FBXLoader: Unknown texture application of type  "TransparentColor, skipping texture.

FBXLoader.js:542 
THREE.FBXLoader: Unknown texture application of type  "SpecularColor, skipping texture.

**Comment by SntsDev** [comment]
Yes, FBXLoader.js doesn't manage some options, like transparency. 

I ended up adding `alphaTest` to `parseParameters` function of FBXLoader:
```javascript
function parseParameters( properties, textureMap, childrenRelationships ) {
    
      var parameters = {};
            
      if (properties.TransparentColor && properties.TransparentColor.value === 1) {
                
         parameters.alphaTest = 0.3;
                
      }
      ...
```
It works ok with use of PNG for maps.

**Comment by TristanVALCKE** [comment]
I have a fix that work perfectly for make human export, maybe it will fix this too ! I will make a PR as soon as possible

**Comment by looeee** [comment]
I added support for several more material parameters and map types in #12317

@CarlBateman can you test with the latest dev version of FBXLoader and see if this problem is fixed?

**Comment by TristanVALCKE** [comment]
Ok i didn't see mine, @looeee would/could you add this one, or need i do a new PR ? It manage transparency **map** like models from make human:

```javascript
case 'TransparencyFactor':
case ' "TransparencyFactor':
	parameters.map = textureMap.get( relationship.ID );
	parameters.transparent = true;
	break;
```

**Comment by looeee** [comment]
I've tested this with the latest dev version and the transparency issue is fixed, so this can be closed. 

![pearl](https://user-images.githubusercontent.com/5307958/31324532-cbe44730-acdd-11e7-9527-903630c550b2.jpg)
