### ISSUE TITLE
Problems with ColladaLoader2

### ISSUE THREAD

**Issue by SebastienFPRousseau** [mrdoob/three.js#11597]
##### Description of the problem 

Hello @Mugen87 

Now I use the `ColladaLoader2` to load my model and play the animations but I get errors and display problems :
- the model does not display correctly, see by yourself. With the `ColladaLoader`my model displaying well.

![431847maria](https://user-images.githubusercontent.com/97088/27502968-f300ae68-582c-11e7-9dbf-999f0bd8a496.png)

- the updating of the mixer for animations generate this error on the console : 
`can not bind to bones as node does not have a skeleton PropertyBinding {path: ".skeleton.bones[Hips].position", ...`
For each error corresponding a warning during the loading like : 
`ColladaLoader2.js:2276 THREE.ColladaLoader: Missing data for bone: Hips.`
However you can see the skeleton on the picture I linked. 

The model come from mixamo : https://www.mixamo.com/ , which gives quality models.

Considering this code : 

```js
loader.load(source, function(collada) 
{
	const obj = collada.scene;
	const animations = collada.animations;

	obj.traverse(function(child)
	{
		child.castShadow = true;
		child.receiveShadow = true;

                if ( child instanceof THREE.SkinnedMesh ) 
                {
                       this.skeleton = new THREE.SkeletonHelper(child);
                       this.skeleton.material.linewidth = 3;
                       this.skeleton.visible = this.skeletonIsShowed;
                       this.environment.scene.add(this.skeleton);
                }
        }.bind(this));

        this.mixer = new THREE.AnimationMixer(obj);
        this.clip = animations[0];
        this.mixer.clipAction(this.clip).play();

}.bind(this));
```

Thanks for reading.

##### Three.js version

- [ ] Dev
- [x] r86
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Is it possible that you share the model? I need to debug this in order to see what's going wrong...

**Comment by SebastienFPRousseau** [comment]
https://www.fichier-zip.com/2017/06/23/maria/

**Comment by Mugen87** [comment]
Thanks for the file! I will look into it...

**Comment by Mugen87** [comment]
#11606 fixes the first part of problems. The texture of the lady should now be displayed correctly.

![image](https://user-images.githubusercontent.com/12612165/27511087-d3a49d76-591d-11e7-80a2-7ce742a43df6.png)

I'll investigate the animation problem within a separate PR.

**Comment by Mugen87** [comment]
I'm not sure if the animation data of this object are valid. As far as i can see, the file only contains two keyframes per bone. Besides, the time values are very strange (0.000000 and 0.033333). So the total length of the parsed animation clip is 0.033333 seconds. Well, it's no problem to change the duration for playback but still these data seems strange to me. I'll need more time to find the problem. Currently i was not able to playback the animation (`ColladaLoader` didn't work either).

BTW: I've imported the model in sketchfab and no animations were parsed at all, too.

https://sketchfab.com/models/1d1f8d2918d54c48a3c3e57f88fa8cd0

@SebastienFPRousseau Can you please verify if the animation data of your model are correct?

**Comment by SebastienFPRousseau** [comment]
It's weird... I suspected something like that. I think it's good for now, i will try another model. Thanks for the texture correction, waiting for the realease. Animations mustn't be valid.
