### ISSUE TITLE
Strange bug in ios, perfomance three.js gets slow 

### ISSUE THREAD

**Issue by adriancabouli** [mrdoob/three.js#11600]
I am trying to figure out what is happening...

I made a game with Tree.js. When i try it, as localhost with safari or chrome , or with Phonegap, this bug is always present...

The thing is this, when i minimize by pressing home button, then leaving the browser or Phonegap app in background, when i reopen the app it slows down going to 30 fps...but, if i press again home button and reenter the app, instantly the app it gets to 60 fps. Also the fps drops down when it pass a few minutes playing, but making this "trick" it gets 60fps at the instant. I would love to make this "magic trick"  by calling some function when i detect fps below than 50 fps.

Thnks!

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x ] iOS

**Comment by mrdoob** [comment]
Maybe you should report this to phonegap instead? Does it happen when running it as a website with Safari?

**Comment by adriancabouli** [comment]
Hi! This happen both, with phonegap and running as a website with Chrome and Safari!

**Comment by Mugen87** [comment]
Do you experience the issue with other WebGL (non `three.js`) applications?

**Comment by adriancabouli** [comment]
nope. Is the only webgl app that i tested. Is so weird!

**Comment by jdanford** [comment]
Do you get the same behavior with a minimal three.js scene like [this one](https://threejs.org/examples/#webgl_animation_scene)?

**Comment by adriancabouli** [comment]
I dont know if exists a function that detects when app(Safari, phonegap etc) lost focus, or get focus and activate render engine.

**Comment by izar89** [comment]
Just a guess. Are you using window.requestAnimationFrame()? Because the browser slows the framerate down when a page is idle (in the background). Take a look at the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) to check when a page is idle.

**Comment by Mugen87** [comment]
@adriancabouli Despite everything, this issue is not `three.js` related. Please post your problem at stackoverflow or the [forum](https://discourse.threejs.org/).
