### ISSUE TITLE
render order doesn't work correctly

### ISSUE THREAD

**Issue by immiao** [mrdoob/three.js#11602]
##### Description of the problem 

When the scene has both transparent and non-transparent objects, the render order seems not working correctly. The transparent objects are always rendered first even if I set the `renderOrder` of the non-transparent objects to a large value.

For example, I want to draw bounding box on top of some transparent objects. I have to set `boundingBoxMaterial.transparent = true` and `boundingBoxMaterial.opaque = 1.0` to make the `renderOrder` works correctly.

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by xueyinw** [comment]
wa
