### ISSUE TITLE
Request to create gitter channel and link on github and the "chat" link at threejs.org

### ISSUE THREAD

**Issue by tbriley** [mrdoob/three.js#11614]
It would be nice to have a gitter room as irc connections can be intermittent and also don't have chat history. With other open source projects that I contribute to this has always been a positive move -> an active chat is a great way to fire off quick "how-to" questions and also waffle on design, features, bugs, etc.

**Comment by mrdoob** [comment]
Seems like there are a couple already...

https://gitter.im/mrdoob/three.js
https://gitter.im/rmx/three.js

**Comment by tbriley** [comment]
created a pr for the main room - it would be great if this were also added as a chat link at threejs.org
