### ISSUE TITLE
Light casting shadows only

### ISSUE THREAD

**Issue by j3zusla** [mrdoob/three.js#11616]
Hello,

I have been working with shadows lately and noticed the shadowmap shadows intensity is proportional to the light intensity property. The process works very well if one uses the tandem (light-shadows), but there is no ways to render the shadowmap (to be used in further processing) and have the light casting the shadow not affecting (0 intensity) the scene objects.

In other words, can we have a light property, like .shadowsonly=true, which disables the light effect on the objects and still have a visible shadow on the shadowmap?

Thx for your consideration.

**Comment by mrdoob** [comment]
Do you mind sharing some images that illustrate what you're trying to achieve?

**Comment by j3zusla** [comment]
Re @mrdoob, here is a case scenario, where in the first picture the shadows are driven by directional lighting and the objects color is affected. In the second picture, I remove the directional light (0 intensity) I get the proper colors, but I loose the shadows. I wish to have the shadows from the first picture with the lightning (object colors) from the second picture.

![lightshadowissue](https://user-images.githubusercontent.com/11213220/27572488-9979c8ce-5b0c-11e7-85f1-1d76a125da6c.png)

**Comment by WestLangley** [comment]
>the shadowmap shadows intensity is proportional to the light intensity property.

In three.js, shadows are the absence of light. The light intensity does not change the color of the shadow itself -- only the color of the surrounding illuminated area. You can see that in the images you posted.

Try [ShadowMaterial](https://threejs.org/docs/#api/materials/ShadowMaterial). There are several examples of its use in the three.js examples.

**Comment by j3zusla** [comment]
> only the color of the surrounding illuminated area 

Yes, it is the effect that will be very useful to control (on/off), specially when rendering shadows that simulate the outdoors. Indoors, one can getby using multiple light sources and shadows that affect its surrounding. On the other hand, when simulating outdoors, if there are multiple light sources, one can easely see that something is not right...

The ShadowMaterial from what I understand is to render shadows only. I was hoping to not have to use it as I have just migrated all the object materials to MeshStandardMaterial and really like its rendering feel.

On a side note, I have found a tiny bug with the shadowmap: when the light source is in the negative z axis and the shadowmap feeds a custom shader, the shadows are inverted (as seen in this image). The bug maybe located into the packing/unpacking process, because the shadows look fine when rendered directly.

![bug_shadowmap](https://user-images.githubusercontent.com/11213220/27600880-9d1fc7d8-5b6d-11e7-8acd-4ba2c45c600d.png)

**Comment by WestLangley** [comment]
> if there are multiple light sources, one can easily see that something is not right...

Sorry, I still do not understand what you are referring to.

>when the light source is in the negative z axis and the shadowmap feeds a custom shader, the shadows are inverted

Sorry, I do not understand what you are referring to.

**Comment by j3zusla** [comment]
> if there are multiple light sources, one can easily see that something is not right...

Let's say you have a scene that contains a large world. The best option to get a constant light is to use  ambiant lighting, which is the first source of light. Ambiant lights don't cast shadows, therefore a need for  a second source of light to cast shadows (directional light in my case). This second source of light creates the color artifact; the color of the surrounding illuminated area that you mentioned, that does not look natural. Unfortunatly, there are no parameters to remove the artifact caused by this extra light. 

> when the light source is in the negative z axis and the shadowmap feeds a custom shader, the shadows are inverted

Maybe, this picture will help you understand better:

![zaxis_bug_shadowmap_three js](https://user-images.githubusercontent.com/11213220/27607523-6d048248-5b84-11e7-8faa-73fd8a1eb0d6.png)

hope this helps.

**Comment by WestLangley** [comment]
>This second source of light creates the color artifact; the color of the surrounding illuminated area that you mentioned, that does not look natural. Unfortunately, there are no parameters to remove the artifact caused by this extra light.

If you add a light source, the illuminated area gets brighter. That is to be expected. I do not see a problem here.

A shadow map is computed from the point of view of the light source. I do not see a problem here.

**Comment by mrdoob** [comment]
> On a side note, I have found a tiny bug with the shadowmap

If there is a bug you should create a new issue for this.
