### ISSUE TITLE
how to load the fbx file with textures in it ,not with texture files

### ISSUE THREAD

**Issue by wu21731** [mrdoob/three.js#11624]
##### Description of the problem 

my partner make a fbx file with textures in it.but when I load the file with three.js, the textures are missing,how to resolve it

##### Three.js version

- [ ] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by mrdoob** [comment]
Do you mind share the fbx files so we can use it as reference?

**Comment by wu21731** [comment]
@mrdoob 
please fix the file'type from .png to .fbx. because i can't send .zip  or .fbx.
![final3 -](https://user-images.githubusercontent.com/15685366/27722405-0c13c67a-5d9a-11e7-837e-397d7856315a.png)

**Comment by mrdoob** [comment]
You can't attach a zip file here?

**Comment by dill0wn** [comment]
I'm also having the same issue (which I also mentioned in #10897 ), here is a file

[mars_character_animation_textures.fbx.zip](https://github.com/mrdoob/three.js/files/1115931/mars_character_animation_textures.fbx.zip)

**Comment by takahirox** [comment]
@wu21731 I couldn't uncompress the file.

@dill0wn Can this model be displayed correctly with other viewers/libs?

**Comment by takahirox** [comment]
`Content` of `Video` has texture image data.
In mars_character_animation_textures.fbx, the base64 data follows comma and newline like this

```
Video: 1211670464, "Video::Map #1", "Clip" {
    ...
    Content: ,
 "iVBOR..."
}
```

Anyone knows if this style is standard and correct?

**Comment by dill0wn** [comment]
@takahirox I was able to look at it properly in the FBXViewer  application.

**Comment by dill0wn** [comment]
@takahirox, I hope it is standard, I know it was exported from 3ds Max 2016, I can try to get more info.

**Comment by takahirox** [comment]
I want some other models to ensure it's right specification.

**Comment by wu21731** [comment]
@mrdoob  Video: 1211670464, "Video::Map #1", "Clip" {
    ...
    Content: ,
 "iVBOR..."
} 
but the Content is not null, it has an image's base64
