### ISSUE TITLE
Fails to load Monster and Duck glTF models in example

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#11622]
##### Description of the problem 

Fails to load Monster and Duck glTF models in https://threejs.org/examples/webgl_loader_gltf2.html example because of 404 error.

The root issue seems first letters of their file/directory names in `gh-pages` branch are lower case, like
- gh-pages: `examples/models/gltf/monster/glTF/monster.gltf`
- master: `examples/models/gltf/Monster/glTF/Monster.gltf`

See
- https://github.com/mrdoob/three.js/tree/gh-pages/examples/models/gltf
- https://github.com/mrdoob/three.js/tree/master/examples/models/gltf
- https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf

@mrdoob

##### Three.js version

- [ ] Dev
- [x] r86
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by takahirox** [comment]
I'm not sure well how to maintain Three.js `gh-pages` branch but can Don or I directly send PR for `gh-pages`?
If I'm right, `master` branch is ok so what we should fix is `gh-pages` branch.

**Comment by donmccurdy** [comment]
Arg yeah it got renamed in a model update, and the [git case-sensitivity thing](https://stackoverflow.com/a/17688308/1314762) hit us.. I'm not sure how the push to `gh-pages` works, but glad to send a PR to the `gh-pages` branch if that helps? As @takahirox says, the `dev` and `master` are correct.

**Comment by mrdoob** [comment]
If you do a PR for `dev` I can take care of the rest.

**Comment by takahirox** [comment]
How can we make a PR in this case?
I mean, what we wanna do is, for example,  renaming `monster.gltf` with `Monster.gltf` for `gh-pages` but in `dev` branch the name is already `Monster.gltf`.

**Comment by takahirox** [comment]
We realized we need to update the glTF models (including Monster and Duck) to the latest version.
If we send the PR of that, can you fix the naming issue of `gh-pages`?

**Comment by mrdoob** [comment]
> I mean, what we wanna do is, for example,  renaming `monster.gltf` with `Monster.gltf` for `gh-pages` but in `dev` branch the name is already `Monster.gltf`.

Hmm? What PR fixed that?

**Comment by takahirox** [comment]
I misunderstood a bit.
They were `monster/duck` before but became `Monster/Duck` in r86 (by misoperation or something?).
- https://github.com/mrdoob/three.js/tree/r85/examples/models/gltf
- https://github.com/mrdoob/three.js/tree/r86/examples/models/gltf

(I thought `Monster/Duck` became `monster/duck` only in `gh-pages` branch)

So renaming `monster/duck` with `Monster/Duck` in `gltf2` example may be the easiest way to fix?

**Comment by takahirox** [comment]
Ah, wait. Seems like I've misunderstood again.
The root issue would be missing #11441 in `gh-pages` branch?

**Comment by donmccurdy** [comment]
Assuming `gh-pages` is published by copy/pasting from the master or dev branch on each release, the cause is probably [this Git issue](https://stackoverflow.com/q/17683458/1314762). Copy/pastes on case-insensitive filesystems (like macOS) are ignored by Git unless you force it to see them.

Since it's OK on the other branches, we can fix it manually on `gh-pages` and it will stay correct after that. Opened #11631.

**Comment by takahirox** [comment]
Ah, right.
The files in `gh-pages` are glTF 2.0, so #11441 isn't missing.
Sorry I've messed up.
