### ISSUE TITLE
FBXLoader can't load FBX from Blender

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#11628]
<img width="1548" alt="screen shot 2017-06-27 at 4 01 00 pm" src="https://user-images.githubusercontent.com/97088/27613693-d7342b4c-5b51-11e7-8883-6accb7ea2d6e.png">

[Rocker.fbx.zip](https://github.com/mrdoob/three.js/files/1107071/Rocker.fbx.zip)

/cc @takahirox

**Comment by takahirox** [comment]
Confirmed the bug.
Seems like I need to fix [`.endOfContent()`](https://github.com/mrdoob/three.js/blob/228e04bd4f6bfb7aeac3a42ae388ad4df04334f1/examples/js/loaders/FBXLoader.js#L4024). Let me look into closer...

**Comment by imZEH** [comment]
Does this issue fix ?

**Comment by looeee** [comment]
@imZEH please open a new issue and share the file you are having trouble with.
