### ISSUE TITLE
voxelpainter example improvement

### ISSUE THREAD

**Issue by ed2k** [mrdoob/three.js#11636]
##### Description of the problem 
this patch can hide rollOverMesh when shift key is pressed.
```
diff --git a/examples/webgl_interactive_voxelpainter.html b/examples/webgl_interactive_voxelpainter.html
index 0ede5f8..bb7f310 100644
--- a/examples/webgl_interactive_voxelpainter.html
+++ b/examples/webgl_interactive_voxelpainter.html
@@ -132,13 +132,15 @@
 
                                var intersects = raycaster.intersectObjects( objects );
 
-                               if ( intersects.length > 0 ) {
+                               if ( intersects.length > 0 && !isShiftDown ) {
 
                                        var intersect = intersects[ 0 ];
 
                                        rollOverMesh.position.copy( intersect.point ).add( intersect.face.normal );
                                        rollOverMesh.position.divideScalar( 50 ).floor().multiplyScalar( 50 ).addScalar( 25 );
-
-
+                                       rollOverMesh.visible = true;
+                               } else {
+                                       rollOverMesh.visible = false;
                                }

                                render();
@@ -194,7 +196,10 @@

                                switch( event.keyCode ) {

-                                       case 16: isShiftDown = true; break;
+                                       case 16: isShiftDown = true;
+                                       rollOverMesh.visible = false;
+                                       render();
+                                       break;

                                }

@@ -204,7 +209,10 @@

                                switch ( event.keyCode ) {

-                                       case 16: isShiftDown = false; break;
+                                       case 16: isShiftDown = false;
+                                               rollOverMesh.visible = true;
+                                               render();
+                                               break;

                                }
```
##### Three.js version

- [ ] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Posting a diff from `git` is maybe not the best approach for contributing. If you really want to change the example, file a PR and describe what kind improvements you introduce. This issue can then be closed.

**Comment by JinGuiMin** [comment]
Perhaps my question is quite naive, I don't understand why positions need to be added to normal vectors? I know he used it to make sure the mesh was above, but I really don't understand his reason;

I usually understand it through mathematical knowledge, but I really don't quite understand the principle of position. add (normal)

Can you help me if you have time？

**Comment by JinGuiMin** [comment]
Perhaps my question is quite naive, and I don't understand this sentence:

rollOverMesh.position.copy( intersect.point ).add( intersect.face.normal );

I know his role, but I don't know why he did it, and I don't know how to express my doubts. I don't know the principle behind position. add (normal), or what kind of mathematical knowledge is it based on?

If you have time, can you help me? Thank you!
