### ISSUE TITLE
Documentation of font.js is wrong, change default value of divisions from 4 to 5

### ISSUE THREAD

**Issue by cnspaha** [mrdoob/three.js#11630]
##### Three.js version

- [x ] Dev

Just took a look at https://threejs.org/docs/index.html#api/extras/core/Font at 
`.generateShapes ( text, size, divisions )`
There is said, that `divisions -- (optional) fineness of the Shapes. Default is 5.` But when looking at the code at https://github.com/mrdoob/three.js/blob/dev/src/extras/core/Font.js line 165 it says that 
`if ( divisions === undefined ) divisions = 4;`
So either the documentation should say that the default is 4 or the default should be changed to 5, like the documentation suggests

**Comment by mrdoob** [comment]
Would you like to fix the docs directly?
https://github.com/mrdoob/three.js/edit/dev/docs/api/extras/core/Font.html

**Comment by cnspaha** [comment]
yeah sure, just did it :)
