### ISSUE TITLE
Would like animations on models imported in the editor included on scene export

### ISSUE THREAD

**Issue by tbriley** [mrdoob/three.js#11642]
Currently when I import my models into the editor, on export I'm not getting any of the animations included (I've tested with fbx, gltf, and collada). It would be great if when a scene is exported, the animation clips that were on imported models are included. Cheers!

EDIT: splitting this into two separate issues (one for supporting animations on export, and another for previewing animations in the editor).

**Comment by harryhychu** [comment]
wanted these too !

**Comment by Mugen87** [comment]
Related #8422

**Comment by donmccurdy** [comment]
Is SkinnedMesh support in the editor a blocking issue for animation import/export? Or is it worth considering just keyframe animations + morph targets?

**Comment by takahirox** [comment]
I don't think it blocks.

**Comment by donmccurdy** [comment]
Now that animation playback (https://github.com/mrdoob/three.js/pull/15698) has been added, adding animation export would be a nice next step. 🙂

**Comment by Mugen87** [comment]
FYI: Animations are now honored when exporting an animated model to glTF, see #20454.

**Comment by tbriley** [comment]
Awesome!
