### ISSUE TITLE
sampler2dArray support?

### ISSUE THREAD

**Issue by abogartz** [mrdoob/three.js#11648]
##### Description of the problem 

One of the new features with WebGL 2.0 is the ability to send an array of textures to the GPU to get around the limitation on texture units. Apparently, this would allow dozens of textures in a shader while still only using a few texture units. I'm not finding anything related to this in the code or in the issues, and documentation is sparse. Is this something ThreeJS supports? If not, can it be added? Seems like a pretty big feature.

http://www.realtimerendering.com/blog/webgl-2-new-features/

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
WebGL2 features are not yet implemented but it's of course on the todo list see #9965

**Comment by Mugen87** [comment]
Closing. WebGL2 related stuff (e.g. feature requests) is discussed in #9965
