### ISSUE TITLE
Skinning animation model outputted from Blender glTF 2.0 Exporter is not displayed properly

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#11644]
##### Description of the problem 

This Issue has been separated from https://github.com/KhronosGroup/glTF-Sample-Models/issues/83#issuecomment-311939203

I also tried Blender 2.78c and [glTF 2.0 Explorter](https://github.com/KhronosGroup/glTF-Blender-Exporter/).
First I tried to display [EmaSimpleSkin.dae](https://github.com/cx20/jsdo-static-contents/blob/master/models/collada/EmaSimpleSkin/EmaSimpleSkin.dae) on Blender.
![emasimpleskin_blender_gltf2_20170629_002](https://user-images.githubusercontent.com/1833979/27683813-5785f166-5d02-11e7-966d-022e25e9bf5c.gif)
Next, I tried to display the glTF 2.0 file exported from Blender in Three.js.
[Three.js + glTF 2.0 model result:](http://jsdo.it/cx20/yfvq)
![emasimpleskin_threejs_gltf2_20170629](https://user-images.githubusercontent.com/1833979/27683862-82afeb9e-5d02-11e7-8406-f27db34ff958.gif)

I thought it was a problem with the exporter, but because it will be [displayed in the Vulkan Renderer](https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/22#issuecomment-311970226), there is a possibility of glTF 2.0 Loader problem in Three.js.

##### Three.js version

- [x] r86

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

ThinkPad X260 + Intel HD Graphics 520

**Comment by takahirox** [comment]
We can test on `dev`.
What I'm working on are skinning serialization and shared skeleton, they don't affect skinning animation itself.

**Comment by takahirox** [comment]
Can you share the model file here?

**Comment by donmccurdy** [comment]
Here is the `.gltf` from the Blender exporter:

[EmaSimpleSkin.zip](https://github.com/mrdoob/three.js/files/1113776/EmaSimpleSkin.zip)

More info in this thread: https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/22

**Comment by takahirox** [comment]
Even I set animation off, skinning seems weird.

![image](https://user-images.githubusercontent.com/7637832/27758690-cc0d9eea-5e55-11e7-81ff-a4ba84bdcfa4.png)

So, `bone` graph, `boneInverses`, or `bindMatrix` handling would be wrong?

**Comment by takahirox** [comment]
Looks working fine if I bind `skinnedMesh.matrixWorld` after scene graph building.

![ezgif com-optimize](https://user-images.githubusercontent.com/7637832/27759976-b080dcd8-5e77-11e7-8af2-de5898531cbc.gif)

But it breaks existing skin models(Monster/CesiumMan in examples) ... Hm...

**Comment by takahirox** [comment]
Is there any ways to confirm this model is correct in addition to using Vulcan renderer?

**Comment by donmccurdy** [comment]
@takahirox here is a version of CesiumMan generated by the Blender exporter (the default came from COLLADA2GLTF). It still works with current GLTF2Loader; does it break with the binding change above?

[CesiumMan.zip](https://github.com/mrdoob/three.js/files/1117463/CesiumMan.zip) (textures didn't export right but that's my fault)

AFAIK babylon.js is rendering the animation like we are, so it's possible the model is incorrect, but i'm not sure how to confirm that.

**Comment by takahirox** [comment]
It doesn't break CesiumMan exported by exporter but I speculate its `matrixWorld` is identity matrix.

What I've done for EmaSimpleSkin.gltf is

Adding the following line here https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTF2Loader.js#L2833

```javascript
_scene.updateMatrixWorld( true );
```

And adding either one of the followings here https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTF2Loader.js#L2852

```javascript
if ( child.isSkinnedMesh === true ) {
    child.bind( child.skeleton, child.matrixWorld );
}
```

```javascript
if ( child.isSkinnedMesh === true ) {
    var boneInverses = child.skeleton.boneInverses;
    for ( var i = 0, il = boneInverses.length; i < il; i ++ ) {
        boneInverses[ i ].multiply( child.matrixWorld );
    }
}
```

I'm feeling like EmaSimpleSkin.gltf is missing premultiplied bindShapeMatrix in Inverse Bind Matrices.
(Refer to https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#skins)

But I'm not sure why Vulkan renderer displays correctly...

**Comment by takahirox** [comment]
Seems like this's exporter's bug.
See the blender thread.

**Comment by cx20** [comment]
@takahirox Thank you for your research cooperation.
@donmccurdy Thank you for your support.
