### ISSUE TITLE
TriangleStrip + wireframe not rendering properly

### ISSUE THREAD

**Issue by RodrigoHamuy** [mrdoob/three.js#11646]
##### Description of the problem 

Steps to reproduce:
Render something using TriangleStrip with a wireframe material.

Expected behaviour:
Should see all the edges.

Current behaviour:
Not all edges are showing up using 4 to 6 vertices. 
If using 8 vertices or more, none edges are showing up and you get the following error:
```GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0```

jsfiddle: 
http://jsfiddle.net/hamuyrodrigo/akmcv7Lh/158/

##### Three.js version

- Dev
- r85

##### Browser

- Chrome
- Firefox

##### OS
- Linux

**Comment by WestLangley** [comment]
I think there is a fundamental assumption throughout the JS code that triangles are specified in groups of three.

Were you just experimenting, or do you have a specific use case for which a draw mode other than `THREE.TrianglesDrawMode` is important or required?

Related: https://github.com/mrdoob/three.js/pull/9980#issuecomment-257479746 and https://github.com/mrdoob/three.js/pull/9980#issuecomment-262606624.

**Comment by RodrigoHamuy** [comment]
Just experimenting.

**Comment by Mugen87** [comment]
`Mesh.drawMode` has been removed, see #18041.
