### ISSUE TITLE
Add ExtrudeFromFace

### ISSUE THREAD

**Issue by Secretmapper** [mrdoob/three.js#11647]
ExtrudeShape is useful, but it would open up a lot more opportunities if we can extrude `face3` and extrude faces from say CubeGeometry

**Comment by Mugen87** [comment]
Actually we want to keep the geometry entities as simple as possible. Adding such features makes everything unnecessary complicated. More advanced extrusions of geometries should be done in a 3D modeling tool.

**Comment by Secretmapper** [comment]
I see the view point, that's fair!

Is there a way to do this on user land right now though? Or is my option only creating a new shape that mirrors my geometry faces, and then extruding off that?

**Comment by Mugen87** [comment]
> Or is my option only creating a new shape that mirrors my geometry faces, and then extruding off that?

That should definitely work.

**Comment by Secretmapper** [comment]
Thanks!
