### ISSUE TITLE
Quad support in current Three.js version

### ISSUE THREAD

**Issue by Ashajoney** [mrdoob/three.js#11655]
##### Description of the problem 

Upon my thorough studies and research, I came to know that current Three.js version doesn't support quad and supports only tria and quad was deprecated since Three.js 60 version.
I do want to know whether we could incorporate quad support in current Three.js version and whether it associates with the performance or rendering issues.
What could be done to optimise the performance with quad support in current Three.js version.

Thanks & Regards,
Aasha Joney

##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
It is complicated... WebGL itself doesn't support quads.

![webgl primitives](http://math.hws.edu/eck/cs424/s12/notes/jan20-2.png)

We could create some geometry classes which could operate with quads, but we'll have to convert to triangles before sending them to WebGL anyway.

**Comment by pailhead** [comment]
This should probably be handled outside of the core. Why limit things to quads anyway? I've been using my own `Ngon` class for a while now.

**Comment by Ashajoney** [comment]
how could you able to achieve in versions below 60.?

**Comment by pailhead** [comment]
Three does not have any opinions on quads. You can support it yourself.

**Comment by WestLangley** [comment]
>How could the THREE.js versions below 60 supported quad and why that could not be incorporated into the current version.?

We decided to simplify the codebase. The renderer no longer handles quads.

Instead, loaders that support quads, convert the quads to triangles during the loading process.
