### ISSUE TITLE
SpotLight target does not work when decay parameter set to 2

### ISSUE THREAD

**Issue by schubboy** [mrdoob/three.js#11659]
If the spotlight is in "physical" mode, targeting will not work. For targeting to work, you MUST set the decay parameter to 1. Bug or no bug, thats how this is currently working.

So if I create a spotlight "var l = new THREE.Spotlight(0xffffff, 1);", the target will not work. But I do "var l = new THREE.Spotlight(0xffffff, 1, 0, Math.PI, 1);" targeting will work. If I do "var l = new THREE.Spotlight(0xffffff, 1, 0, Math.PI, 2);" or "var l = new THREE.Spotlight(0xffffff, 1, 100, Math.PI, 2);", targeting will not work.

Fiddle showing targeting working: http://jsfiddle.net/schubboy/rx09v1fy/
fiddle showing targeting NOT working due to decay parameter set to 2: https://jsfiddle.net/schubboy/rx09v1fy/

**Comment by WestLangley** [comment]
Your spotlight is shining up into the air, instead of down on the the plane.
Your spotlight angle is larger than the maximum allowed value. See the docs.
The `SpotLight` constructor has 6 args, not 5.
You are calling `updateMatrixWorld()` unnecessarily.
...
Please use stackoverflow for help.
