### ISSUE TITLE
Loading gltf v 2.0 or higher into the editor currently does not work

### ISSUE THREAD

**Issue by tbriley** [mrdoob/three.js#11650]
##### Description of the problem 

The default loader in the editor is for version 1 only. I've added basic support in a hacky [PR](https://github.com/mrdoob/three.js/pull/11649) but the model shows up as black:

![image](https://user-images.githubusercontent.com/6376639/27722934-03eb6d9c-5d9d-11e7-8901-4805c6ca1591.png)

For reference, this is the Cesium Man sample model from [Khronos](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan/glTF-Embedded).

**Comment by mrdoob** [comment]
You just need to add a light to the scene.

<img width="358" alt="screen shot 2017-06-30 at 9 31 17 am" src="https://user-images.githubusercontent.com/97088/27745092-eb76540a-5d76-11e7-89f3-e690e0825ae4.png">

**Comment by tbriley** [comment]
d'oh, i'd forgotten i removed my lights!
