### ISSUE TITLE
Would like the ability to preview animations on imported models in the editor

### ISSUE THREAD

**Issue by tbriley** [mrdoob/three.js#11669]
Ideally there would also be some kind of support for previewing animations on imported models in the editor. Even just a quick and simple way for our artists to test that an animation looks ok when loaded in would suffice. It could either default to play through all the animations, or give you a dropdown toggle in the inspector in the case where multiple clips may be embedded in a single file. Of course I can do a test project for this, or enforce gltf and point our artists [here](https://gltf-viewer.donmccurdy.com/), but it would be much nicer to be able to have built-in support for this in the scene.

**Comment by Temdog007** [comment]
#15698 fixes this. 

@Mugen87 , @mrdoob I think this issue can be closed.
