### ISSUE TITLE
Render Problem when I learning Three.js by the examples

### ISSUE THREAD

**Issue by sheweichun** [mrdoob/three.js#11673]
##### Description of the problem 

After I had cloned the three.js repository,I watch the canvas_camera_orthographic.html，I saw the scene like below:
![](https://img.alicdn.com/tfs/TB1oGxGSXXXXXbvapXXXXXXXXXX-2502-1064.png)
In the scene,Some cube hadn't rendered completely,is there any problem?How can I solve this?

##### Three.js version

- [x] 0.86.0
- [ ] r85
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
@sheweichun This appears to be due to near-plane clipping. Did you modify the example?

Also, see #11678.

**Comment by WestLangley** [comment]
@sheweichun After the next three.js release, let us know if the problem is still occurring.

**Comment by sheweichun** [comment]
ok

**Comment by sheweichun** [comment]
@WestLangley  no problem
