### ISSUE TITLE
Suggestion: auto uv2

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#11672]
##### Description of the problem 

If I'm right, `aoMap` and `lightMap` require `uv2` and users need to be aware of that and manually define it unless model has built-in `uv2`.

So, I'm wondering if it'd be useful that Three.js (`WebGLRenderer`?) automatically detects non-defined `uv2` and uses `uv` as `uv2` (or copies `uv` to `uv2`).

What do you folks think?

##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
I do no think we should be modifying the user's model, but a console warning may be nice.

Also, the 2nd set of UVs do not honor offset/repeat, so silently setting UVs behind the back of the user may lead to more confusion.

At some point, I hope we will be providing additional flexibility in this regard, so this problem will go away.

**Comment by takahirox** [comment]
How about console warning + using uv as uv2 (with offset/repeat adjusting)?

>  I hope we will be providing additional flexibility in this regard

For example?

**Comment by WestLangley** [comment]
>How about console warning + using uv as uv2 (with offset/repeat adjusting)?

Whether the console warning is just a warning, or also includes a temporary patch, is up to @mrdoob.

>I hope we will be providing additional flexibility in this regard, so this problem will go away.

Specifically, I was thinking of https://github.com/mrdoob/three.js/pull/8278.

**Comment by takahirox** [comment]
I haven't read through the entire thread #8278 yet but
Yeah, if we do #8278, seems like we don't need this auto uv2.
But it hasn't been merged yet.
Does it have any concerns?

**Comment by Mugen87** [comment]
We already highlight in the docs that `aoMap ` and `lightMap` require a second set of UVs. I think this is sufficient. Voting to close the issue.
