### ISSUE TITLE
Right to left support for texts

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [mrdoob/three.js#11680]
I need to show some text in **Persian/Arabic language**. I loaded a font including characters and I used `TextGeometry` to create a text on the scene:

```javascript
var loader = new THREE.FontLoader();
loader.load('B Zar_Regular.js', function (font) {
    var textGeo = new THREE.TextGeometry('سلام!', {
        font: font,
        size: 1,
        height: 0.05,
        curveSegments: 12,
    });
    var material = new THREE.MeshNormalMaterial();
    var textMesh = new THREE.Mesh(textGeo, material);
    textMesh.position.x = 15;
    scene.add(textMesh);
});
```
I was expecting to see `سلام!` but the output was:
![three rtl](https://user-images.githubusercontent.com/5295554/27819530-f8caf048-60af-11e7-849f-1856ad27be65.png)
letters are separated and order of characters is reversed mistakenly. After all it seems threejs do not support rtl languages. Am I right or I missed something? Is there any workaround as a quick solution? Thanks.

**Comment by mrdoob** [comment]
https://stackoverflow.com/questions/44920527/support-for-farsi-arabic-texts-in-three-js

**Comment by makc** [comment]
raster text with fancy shader maybe? just [drawing arabic into canvas](https://jsfiddle.net/7do1c5wk/) works ootb.

**Comment by ImanMahmoudinasab** [comment]
I answered the SO question it may help some people.
