### ISSUE TITLE
FBXLoader.parse relies on variables defined in FBXLoader.load

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#11695]
`FBXLoader.parse` error checking relies on two variables defined in `FBXLoader.load` - specifically `self` and `url`. This means that if you are calling the `parse` function directly then the error tests will themselves cause an error. 

The offending lines are: 

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/FBXLoader.js#L104

and 

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/FBXLoader.js#L110-L111

**Comment by jostschmithals** [comment]
see ...

https://github.com/mrdoob/three.js/pull/11483
https://github.com/mrdoob/three.js/issues/11398#issuecomment-308710144

**Comment by looeee** [comment]
@jostschmithals thanks 😁 I see you closed your PR with this comment:

> Indeed it seems that lines 103 and 110 are not needed at all because parse errors are already caught in the load function.

This doesn't cover the case where the parse function is called directly, and also the errors that are caught in these lines are not the same errors caught in the load function.  

The load function, appropriately, catches errors with loading the files, while the parse function catches errors in parsing the files, either because of wrong format or old versions.

**Comment by jostschmithals** [comment]
@looeee I think you're right, but at the moment I have no time to keep track of this, unfortunately.
