### ISSUE TITLE
Pieces of FBX files exported from 3DS Max have wrong transforms applied

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#11697]
I'm updating quite a few old FBX model to work with the FBXLoader, by importing them to 3DS Max and then re-exporting them with the 3DS Max exporter (I've tried both the standard and game exporter). 

I'm finding that pieces of the models have odd transforms applied when loaded in three.js, although they
display correctly in 3DS Max and with Clara.io. Here are two of the models:

Three.js:
![fan-three](https://user-images.githubusercontent.com/5307958/27860661-b7bcfcd8-61a7-11e7-8998-8b54c736754d.jpg)

Clara.io:
![fan-clara](https://user-images.githubusercontent.com/5307958/27860664-ba20123a-61a7-11e7-8e6e-698bac1a4611.jpg)

Three.js:
![phone-three](https://user-images.githubusercontent.com/5307958/27860693-d0eb589e-61a7-11e7-8470-f9e32b482f2c.jpg)
Clara.io:
![phone-clara](https://user-images.githubusercontent.com/5307958/27860694-d66311d6-61a7-11e7-8936-4a7ce53adeb8.jpg)

Both of the models are here:
[models with odd transform.zip](https://github.com/mrdoob/three.js/files/1124497/models.with.odd.transform.zip)

##### Three.js version

- [ x ] Dev
- [ ] r85
- [ ] ...

**Comment by tornadory** [comment]
I also met this issue, see https://discourse.threejs.org/t/issue-fbx-model-shows-abnormal/693/2

using newest version.

**Comment by looeee** [comment]
OK, I think I've found out the issue here - the loader always assumes that the pivot point is at the exact centre of the mesh, so the meshes with transformed pivot points are displayed in the wrong place. 

I'm going to close this issue and reopen as a new issue as I don't think this has anything to do with 3DS Max, rather it happens with all FBX files.
