### ISSUE TITLE
THREE.UnrealBloomPass, dispose method contains errors.

### ISSUE THREAD

**Issue by OrtOfOn** [mrdoob/three.js#11693]
##### Description of the problem 

It seems your THREE.UnrealBloomPass class has an error at line 137 and 138, in the dispose method:

this.renderTargetsVertical.**length()** must be this.renderTargetsVertical.**length**

Right?

**Comment by Mugen87** [comment]
That's correct 👍 ! Would you like to provide a PR with a fix?

**Comment by OrtOfOn** [comment]
I'm not strongly active on Github. Maybe it's better you do it :)

**Comment by Mugen87** [comment]
Thanks for reporting!

**Comment by mrdoob** [comment]
Thanks!
