### ISSUE TITLE
Advanced audio with wad

### ISSUE THREAD

**Issue by Berserk82** [mrdoob/three.js#11692]
Hello everyone. 
I'd like to use Wad for audio inside three.js (https://github.com/rserota/wad) instead of the default audio interface. 
Is this possible? How? 
I'm asking because I'd avoid to even just try without knowing and I'm a total noob with javascript in general. 
So thanks in advance for any help, greatly appreciated. 

Cheers.

**Comment by Mugen87** [comment]
> Is this possible? How?

If you are not using the build-in audio prototypes, you have to perform some additional tasks so spatial audio will work. With a custom library, your audio listener and positional audios are no part of the scene graph. That means you have to manually update position (and orientation) of the respective entities.

**Comment by Berserk82** [comment]
So, basically, you're saying I can use the 2 concurrently, but I can't integrate them (not out of the box).
Is this correct? 
I'm not really interested in audio positioning as far as wad is concerned, because I'd just want to use it for background music in my game (if there will be one), but I want to be sure I can. 

Thanks for now, and thanks again in advance for any further information.

**Comment by Mugen87** [comment]
I don't know `Wad` so i can't tell you how easy it is to couple both libraries. But i assume it won't work out of the box (so you as a developer must provide some magic).

Anyway, if you are going to use a library just for background music, there should be no problems. As i said before, spatial audio effects would require more work...

**Comment by Berserk82** [comment]
Thanks a lot.
I guess I can close the issue. 
I have another question, but it's related to textures, so I'm going to open another issue in order to allow users to easily track everything.
