### ISSUE TITLE
Procedural textures with fabric.js

### ISSUE THREAD

**Issue by Berserk82** [mrdoob/three.js#11694]
As you may have guessed, my target is to procedurally create content and make everything interact in real time. 
I found a solution for music, now it's time for textures.
The question is: is it possible to use fabric.js to generate a texture, and then use it for a material in three.js?
I guess the answer is yes, but I have a gap about how to do so.
Also, I'd like to do the opposite: render a scene in three.js and do post processing in fabric.js.
Please, give me advice. 

For the records, I won't post further questions for now.

Thanks in advance for either. 

Cheers.

**Comment by Wilt** [comment]
Questions should be posted on StackOverflow

**Comment by Berserk82** [comment]
Oh, sorry.
