### ISSUE TITLE
[Three.js Blender Export] warning

### ISSUE THREAD

**Issue by Lapsec** [mrdoob/three.js#11691]
I got warning when I import [Three.js Blender Export](https://github.com/mrdoob/three.js/tree/master/utils/exporters/blender) into Blender

![image](https://user-images.githubusercontent.com/6178850/27852066-3f7fe72e-6190-11e7-80b5-42ad8ecf168d.png)

 I try to run /io_three/__init__.py,  got error
![image](https://user-images.githubusercontent.com/6178850/27852237-fa6af90c-6190-11e7-8f2d-f1bcc5d897ca.png)

##### Three.js version

- [x] r86

##### Browser

- [x] Chrome

##### OS

- [x] macOS

**Comment by mrdoob** [comment]
Hmm.. This maybe more suitable to be reported (or ask for help) on Blender forums instead...
