### ISSUE TITLE
Adding features to TransformControls.js

### ISSUE THREAD

**Issue by ipepe** [mrdoob/three.js#11708]
Hey.

I will be doing some work on TransformControls and wondered how should I approach it? The project that will be using expanded version has that file checked into repository. I could from time to time sync You changes. But also wondered, that maybe it should be extracted to separate repository as plugin of Three.js?

I will be expanding snapping to specifying different values per axis (rotation and translation). Also a feature to "block" moving based on specified handler. Also I will need to specify what rotation axises are available (mainly because I don't want "E" rotations).

What is Your opinion?

**Comment by arodic** [comment]
Hi @ipepe,

For small iterative improvements it is probably best to simply submit PRs. For the sake of reverse compatibility, the default behavior should probably stay the same.

However, I think that complete refactor of all three.js controls is necessary. Especially, the more complex ones like TransformControls.js. That should probably go into its own repository until its stable enough to be merged into three.js. I't something I've been wanting to do for a very very long time :) This August it looks I'll finally get around to do it! I'll have more details to share soon.

**Comment by makc** [comment]
related #11340

**Comment by ipepe** [comment]
@makc Thanks for relating that issue. It was a valuable read.

**Comment by Mugen87** [comment]
Closing. If somebody likes to add features to `TransformControls`, just make a PR and the community can discuss the changes 😊
