### ISSUE TITLE
OBJLoader + MTLLoader texture won`t work it

### ISSUE THREAD

**Issue by deokhae** [mrdoob/three.js#11707]
##### Description of the problem 

Hi,

I`m used to use three.js r53, so I want to upgrade to latest version(r86).

obj loader goes well, but when I try OBJLoader + MTLLoader that texture file does not work.

first, when I try as the sample(https://threejs.org/examples/webgl_loader_obj_mtl.html)

there have an error occurred [Unexpected line: 's']

I found out that because OBJLoader could not work with s(lineFirstChar), so I gave a exception for that.

second, after that I can view object, but textures do not work with it.

this is my site(http://3dbank.xyz:9021/viewer/viewer_hologram_u.do?conts_uid=2388)
##### Three.js version

- [ ] Dev
- [x] r86
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
> there have an error occurred [Unexpected line: 's']

Where do you get that?

**Comment by deokhae** [comment]
I`ve modified objloader.js. I change back again. 

you can confirm the error from this url http://3dbank.xyz:9021/viewer/viewer_hologram_u.do?conts_uid=2388

**Comment by mrdoob** [comment]
How did you generated that obj?

**Comment by deokhae** [comment]
Here is my code:
	THREE.Loader.Handlers.add(/\.dds$/i, new THREE.DDSLoader());
	var mtlLoader = new THREE.MTLLoader(manager);
	var mtl_name = settings.mtlFile.substring(settings.mtlFile.lastIndexOf("/") + 1);
	var obj_name = settings.meshFile.substring(settings.meshFile.lastIndexOf("/") + 1);
	
	mtlLoader.setPath(settings.path);
	mtlLoader.load(mtl_name, function(materials){
		materials.preload();
		
		var objLoader = new THREE.OBJLoader(manager);
		objLoader.setMaterials(materials);
		objLoader.setPath(settings.path);
		objLoader.load(obj_name, function(object){
			object.position.set(-0, 0, 0 );
			object.rotation.set(0, +Math.PI*0.5, 0 );
			object.traverse( function( object ) 
			{
				object.castShadow = true;
				object.receiveShadow = true;
				//object.material = MeshPhongMaterials;
			});
			addObject(settings.container, object);
		}, onProgress, onError);
	})

I referenced this smaple(https://threejs.org/examples/webgl_loader_obj_mtl.html)

**Comment by deokhae** [comment]
I don`t know which obj was generated by which tool.

It`s basically provided by government and it`s made by many of tools(3dmax, maya, etc) after 3d scanning objects.

I`ll add comment later if I can find out 2388 object use which tool.

**Comment by deokhae** [comment]
I find out our obj made by ZBrush

**Comment by kaisalmen** [comment]
This is the file in question:
http://3dbank.xyz:9021/downStlImg.do?file=meshconv/conts_uid_2388/3dbts103601T.obj

Lines 59626-59628:
```
g 3dbts103601_1
usemtl 3dbts103601_11
s
```
Here the `s` doesn't fit the smoothing pattern (s without anything is not allowed according OBJ spec, btw):
```
var smoothing_pattern        = /^s\s+(\d+|on|off)/;
```
@jonnenauha @mrdoob shall we make `OBJLoader` resilient? `OBJLoader2` eats it already.

**Comment by mrdoob** [comment]
How should `s` supposed to be interpreted in this case?

**Comment by kaisalmen** [comment]
From the spec:
> **s group_number**
Polygonal and free-form geometry statement.
Sets the smoothing group for the elements that follow it. If you do
not want to use a smoothing group, specify off or a value of 0.
To display with smooth shading in Model and PreView, you must
create vertex normals after you have assigned the smoothing
groups. You can create vertex normals with the vn statement or
with the Model program.
To smooth polygonal geometry for rendering with Image, it is
sufficient to put elements in some smoothing group. However,
vertex normals override smoothing information for Image.
group_number is the smoothing group number. To turn off
smoothing groups, use a value of 0 or off. Polygonal elements use
group numbers to put elements in different smoothing groups.
For free-form surfaces, smoothing groups are either turned on or
off; there is no difference between values greater than 0.

My interpretation: s with nothing is not allowed. If a parser should behave tolerant in this case, then it must assign a default smoothing group for example 1 as off/0 (flat shading) needs to be explicitly set. Do you agree?

**Comment by mrdoob** [comment]
Agreed 👌

**Comment by deokhae** [comment]
thank you for answering my first question.

I`ve modified objloader.js to ignore that smoothing_pattern, I can render obj.

but I have another problem is files of texture won`t fit on obj

`THREE.WebGLRenderer: image is not power of two (5120x3584). Resized to 4096x4096 `

I thought is maybe because this warning message.

It shows very different from previous version(http://3dbank.xyz:9021/viewer/viewer_hologram.do?conts_uid=2388)

**Comment by kaisalmen** [comment]
The parse function of `THREE.MTLLoader` returns an object of this type `THREE.MTLLoader.MaterialCreator`. `OBJLoader.setMaterials` expects such an object. So, if you want to add materials manually, you have manipulate the MaterialCreator instance returned by `MTLLoader` or create one manually.

**Comment by deokhae** [comment]
Sorry, Maybe I was not clear.
I just want use multi texture, but it seems not working.
if I tried set material in traverse, it might be working in type of single texture obj. like below
`var objLoader = new THREE.OBJLoader(manager);
objLoader.setMaterials(materials);
objLoader.setPath(settings.path);
objLoader.load(obj_name, function(object){
					object.position.set(-0, 0, 0 );
					object.rotation.set(0, +Math.PI*0.5, 0 );
					object.traverse( function( object ) 
					{	
						object.castShadow = true;
						object.receiveShadow = true;		
						object.material = MeshPhongMaterials[0];
					} );

					addObject(settings.container, object);
				}, onProgress, onError);`
but does not working for multi texture type.
sample:
single type: http://3dbank.xyz:9021/viewer/viewer_hologram.do?conts_uid=2826
multi type: http://3dbank.xyz:9021/viewer/viewer_hologram_u.do?conts_uid=2388

and this obj and image files
[sample.zip](https://github.com/mrdoob/three.js/files/1161572/sample.zip)

**Comment by mrdoob** [comment]
That's unrelated from the `[Unexpected line: 's']` issue. Could you create a different issue?

**Comment by deokhae** [comment]
sure
