### ISSUE TITLE
ctrl+left click (or mouse wheel click) in documentation should open new tab

### ISSUE THREAD

**Issue by ConradBrean** [mrdoob/three.js#11712]
The titile says everything, this behaviour is expected, and works on almost any other website. The fact that it doesn't in three.js documentation hurts usabilty. Changing that would be appreciated :)

**Comment by mrdoob** [comment]
I've just cleaned up the documentation code a bit in 5225f34115127f759d9acd6e92e8ec1d137ea9e4 and I implemented your suggestion while at it.

However, we recently made it so if someone ends up in https://threejs.org/docs/api/loaders/FileLoader.html it gets redirected to https://threejs.org/docs/#api/loaders/FileLoader which may go againts what you're trying to do.
