### ISSUE TITLE
Object disappears when it is added in a different line of code

### ISSUE THREAD

**Issue by jiazheng** [mrdoob/three.js#11713]
##### Description of the problem 

I add two transparent object into the scene. An object loaded from .obj and a plane inside it.
The following page shows what I want:
[http://jiazhengblog.com/test/webgl/medal2.html](http://jiazhengblog.com/test/webgl/medal2.html)

But the other page have problem: the plane inside the object disappear:
[http://jiazhengblog.com/test/webgl/medal2-problem.html](http://jiazhengblog.com/test/webgl/medal2-problem.html)

The only difference between the two pages is the position of code for adding plane. You can see them in line from 174 to 191.
http://jiazhengblog.com/test/webgl/medal3d/Medal3D2.js
http://jiazhengblog.com/test/webgl/medal3d/Medal3D2-problem.js

For simplicity the following pattern works:
```
loadObject(function () {
    addObject();
});
addPlane();

```
but the following pattern not works:
```
loadObject(function () {
    addPlane();
    addObject();
});
```

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by jiazheng** [comment]
Don't you think it is a bug?

**Comment by mrdoob** [comment]
Probably not. Without looking in detail, I suspect is more likely to be a lack of understanding of asynchronous calls in JavaScript from your part.

**Comment by mrdoob** [comment]
Okay. I checked the links and I think the problem is sure to transparency and both injects being in the same position. Transparency is a difficult topic in WebGL and we can't do much about it. Try using `plane.renderOrder = 1`.
