### ISSUE TITLE
Blender JSON exporter is duplicating vertices.

### ISSUE THREAD

**Issue by marquizzo** [mrdoob/three.js#11720]
I noticed that there is an unnecessary repetition of vertices in the output when exporting from blender to JSON in BufferGeometry format.

Consider the following cube example:
![cubeflat](https://user-images.githubusercontent.com/7864858/27977649-8bd5baea-6320-11e7-8187-78f0e343b4bd.jpg)
When I export it using `type: Buffergeometry`, I get a 1.8 kb file with 34 vertices:

    "metadata":{
        "normal":34,
        "position":34,
        "version":3,
        "type":"BufferGeometry",
        "generator":"io_three"
    }

[see full output for flat cube](https://gist.github.com/marquizzo/3a1b76cf0cd39bb257480e864e82aeea)

However, when I smooth out the faces, like this...
![cubesmooth](https://user-images.githubusercontent.com/7864858/27977773-19f26620-6321-11e7-8dda-dc9b38f1d3a3.jpg)

... I get a much more reasonable output with only eight vertices, and a 0.9 kb file:

    "metadata":{
        "normal":8,
        "position":8,
        "version":3,
        "type":"BufferGeometry",
        "generator":"io_three"
    }

[see full output for smooth cube](https://gist.github.com/marquizzo/075778a210c53cfd3925eb6329fb0674)

Why does the flat cube get 34 vertices, instead of the expected 8? Shouldn't the flattening be handled in the normals instead of by making all faces separate? When I export a flat cube using the `type: Geometry` setting, I get 8 vertices and 6 normals, so it seems that it's possible.

##### System Specs:
- [ x ] Windows
- [ x ] Blender 2.78a
- [ x ] io_three version: (1, 5, 0)
- Exporter settings:
![settings](https://user-images.githubusercontent.com/7864858/27978270-4c64d15e-6323-11e7-989c-c164fc3433a4.jpg)
    - Enabled precision to 2

**Comment by WestLangley** [comment]
In `BufferGeometry`, a vertex can only be reused if the vertex and _all the attributes for that vertex_ are identical.

Since each corner of the box has 3 different normals, the fewest number of vertices you could possibly have for a box with orthogonal normals is 8 x 3 = 24.

With 12 triangles, the max is 12 x 3 = 36 vertices. So you are sharing 2. To determine why that is happening, you will have to step  through with a debugger.

**Comment by marquizzo** [comment]
Ah, thanks for the explanation. It seems this isn't an issue with the exporter, but an issue in my understanding of the way BufferGeometry handles normals, then. 

So just to clarify, BufferGeometry stores vertex normals, but Geometry can have either vertex or face normals? I was reading the [BuferGeometry documentation page](https://threejs.org/docs/index.html#api/core/BufferGeometry) and it states:

> normal (itemSize: 3)
> Stores the x, y, and z components of the face or vertex normal vector of each vertex in this geometry. Set by .fromGeometry(). 

... which was a bit confusing, because it says it stores "face or vertex normal vector".

**Comment by WestLangley** [comment]
`Geometry` can have vertex normals and/or face normals. Or neither.

The docs should be fixed.
