### ISSUE TITLE
an idea to optimize mesh raycast

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#11729]
so I was reading through that code for unrelated reasons, and found this: Mesh `raycast` 1st goes into `checkIntersection` that calls `ray.intersectTriangle`, and then optionally goes into `uvIntersection` that calls `Triangle.barycoordFromPoint`. so far so good, BUT `ray.intersectTriangle` seems to be already computing barycentric coords implicitly (see [line 449](https://github.com/mrdoob/three.js/blob/master/src/math/Ray.js#L449) and comments below it). so - if instead of
```
return this.at( QdN / DdN, optionalTarget );
```
it did something like
```
var result = this.at( QdN / DdN, optionalTarget );
result.b1 = ...;
result.b2 = ...;
return result;
```
no subsequent call to `Triangle.barycoordFromPoint` would be necessary.

**Comment by makc** [comment]
this actually saves calculations for single triangle, so not much gain.

**Comment by Mugen87** [comment]
I guess we leave to code as it is. The proposed changes to `Ray.intersectTriangle()` would make the method somewhat...inconsistent. Adding additional properties to the results vector seems hacky.
