### ISSUE TITLE
Raycaster works unreliably after changing vertices of BoxGeometry

### ISSUE THREAD

**Issue by JannisX11** [mrdoob/three.js#11723]
I have a box geometry with two functions to change it's corners.
This is one of them. The other is the same but for the opposite corner.
```javascript
this.to = function(arr) {
	//X
	bgs.vertices[0].setX(arr[0])
	bgs.vertices[1].setX(arr[0])
	bgs.vertices[2].setX(arr[0])
	bgs.vertices[3].setX(arr[0])
	//Y
	bgs.vertices[0].setY(arr[1])
	bgs.vertices[1].setY(arr[1])
	bgs.vertices[4].setY(arr[1])
	bgs.vertices[5].setY(arr[1])
	//Z
	bgs.vertices[0].setZ(arr[2])
	bgs.vertices[2].setZ(arr[2])
	bgs.vertices[5].setZ(arr[2])
	bgs.vertices[7].setZ(arr[2])

	bgs.verticesNeedUpdate = true
}
```
But after I change the position and scale of the geometry with this method, the THREE.Raycaster() works unreliably and sometimes doesn't find the geometry. In most cases it only works if the ray hits both the old and the new position of the geometry.

Example: http://server.zofenia.de/blockbench/web/beta/

##### Browser

- [x ] Electron (Chromium)
- [x ] Chrome
- [x ] Opera

##### OS

- [x ] Windows

**Comment by WestLangley** [comment]
If you modify your geometry, you need to call `computeBoundingSphere()`.

**Comment by JannisX11** [comment]
Thanks, you saved my day!
