### ISSUE TITLE
about JSON Model format 3

### ISSUE THREAD

**Issue by dushun** [mrdoob/three.js#11721]
How to define three.js JSON Model format 3 "faces"? One of the formats？
such as:

    "faces": [ 
		// triangle
		// 00 00 00 00 = 0
		// 0, [vertex_index, vertex_index, vertex_index]
		0, 0,1,2,

		// quad
		// 00 00 00 01 = 1
		// 1, [vertex_index, vertex_index, vertex_index, vertex_index]
		1, 0,1,2,3,

		// triangle with material
		// 00 00 00 10 = 2
		// 2, [vertex_index, vertex_index, vertex_index],
		// [material_index]
		2, 0,1,2, 0,

		// triangle with material, vertex uvs and face normal
		// 00 10 01 10 = 38
		// 38, [vertex_index, vertex_index, vertex_index],
		// [material_index],
		// [vertex_uv, vertex_uv, vertex_uv],
		// [face_normal]
		38, 0,1,2, 0, 0,1,2, 0,      ......

**Comment by WestLangley** [comment]
I am not sure I understand the question... It is also posted on [stackoverflow](https://stackoverflow.com/questions/44962231/about-json-model-format-3).

**Comment by dushun** [comment]
How to change Type bitmask？Thanks!

**Comment by dushun** [comment]
I use it THREE.ObjectLoader class display mesh rupture? 
<a href="http://imgur.com/17XUk8H"><img src="http://i.imgur.com/17XUk8H.jpg" title="source: imgur.com" /></a>
 I use Three.js Editor export .json file. 
`"geometries": [
{"uuid": "79CFFC92-B013-4DBD-A13E-2B82A69F0377","type": "Geometry",
"data": {"vertices": [2.432324,0.17101,-0.428884,2.5,0,0,2.469846,0.17101,0,2.462019,0,-0.43412,2.469846,......]

"normals": [1,0,0,0.925694,0.342089,-0.161451,0.939666,0.342089,0.001747,0.984808,0,......]

"uvs": [[0.700125,0.959411,0.74369,0.976782,0.700125,0.976782,0.744221,0.959411,......]

"faces": [40,1,0,2,0,1,2,0,1,2,40,1,3,0,0,3,1,0,3,1,40,4,3,1,4,3,0,4,3,0,40,3,5,0,3,5,1,3,5,1,......]`

How is it setting the proper bitmask for the face type?    

Thanks!

**Comment by WestLangley** [comment]
Do you mean [this formula](https://github.com/mrdoob/three.js/blob/master/src/core/Geometry.js#L1033-L1040) in `Geometry.toJSON()`?

    0 + 2^3 + 2^5 = 40

**Comment by dushun** [comment]
How to generate it something like that：
"faces": [1,0,2,0,1,3,2,4,1,4,2,5,5,6,4,6,5,7,7,8,6,8,7,9,11,10,12,10,11,13,14,11,12,13,15.....] 

I use Three.js Editor export json file
"faces": [40,1,0,2,0,1,2,0,1,2,40,1,3,0,0,3,1,0,3,1,40,4,3,1,4,3,0,4,3,0,40,3,5,......]use it THREE.ObjectLoader class，vertex index do not match the original faces， seems the faces are not composed of the correct vertices. http://i.imgur.com/17XUk8H.jpg  
Thanks！

**Comment by WestLangley** [comment]
Use `JSONLoader`, instead.

**Comment by dushun88** [comment]
Use JSONLoader error occurred

**Comment by dushun** [comment]
How to use three.js editor export quad？Not for triangle.   Thanks!

**Comment by marquizzo** [comment]
Three.js does not render quads, it only renders triangles. See this issue for more information on that topic:

https://github.com/mrdoob/three.js/issues/11655

**Comment by dushun88** [comment]
I use Three.js Editor as shown below: vertex index do not match the original faces， seems the faces are not composed of the correct vertices.
<a href="http://imgur.com/KJ4BzhB"><img src="http://i.imgur.com/KJ4BzhB.png" title="source: imgur.com" /></a>

But use it THREE.ObjectLoader class correctly displayedas below:
<a href="http://imgur.com/FV7mlm8"><img src="http://i.imgur.com/FV7mlm8.png" title="source: imgur.com" /></a>

This is the source file: http://114.215.129.33/ds/ds.js

I want to know why this is. Thanks!!

Three.js version

r68

**Comment by mrdoob** [comment]
> How to generate it something like that：
"faces": [1,0,2,0,1,3,2,4,1,4,2,5,5,6,4,6,5,7,7,8,6,8,7,9,11,10,12,10,11,13,14,11,12,13,15.....]

As @WestLangley said, three.js no longer supports quads internally. It can, however, "parse" quads still (though they get converted to triangles), I think the Blender Exporter still exports quads.
