### ISSUE TITLE
Exporting a cloud of points from blender results in error

### ISSUE THREAD

**Issue by justin522** [mrdoob/three.js#11739]
##### Description of the problem 

Exporting a cloud of points from Blender with only vertices checked in the option box resulted in the error below. Connecting three points into a face while leaving only vertices checked achieved the desired result. Now that I know the work-around it won't be a problem for me again, but changing this behavior might be nice for others.

Thank you, to everyone who works on this project and Ricardo Cabello in particular. Great work!

##### Error Message

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\__init__.py", line 814, in execute
    exporter.export_geometry(filepath, settings)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\exporter\__init__.py", line 20, in inner
    func(filepath, options, *args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\exporter\__init__.py", line 85, in export_geometry
    geo.parse()
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\exporter\geometry.py", line 165, in parse
    self._parse_geometry()
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\exporter\geometry.py", line 506, in _parse_geometry
    self[constants.VERTICES] = api.mesh.vertices(self.node, self.options) or []
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_three\exporter\api\mesh.py", line 61, in inner
    mesh = data.meshes[name]
TypeError: bpy_prop_collection[key]: invalid key, must be a string or an int, not NoneType

location: <unknown location>:-1
```

##### Three.js version

- [ ] Dev
- [x ] r85
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [?] macOS
- [?] Linux
- [ ] Android
- [ ] iOS

**Comment by marquizzo** [comment]
I also ran into that problem [last year] (https://blender.stackexchange.com/questions/63521/three-js-json-export-error-when-scene-has-no-faces). The exporter worked after adding a single face, and then I had to go into the JSON output and delete that face manually.

**Comment by mikerc19** [comment]
I tried this but I can't get it to work, I don't know if I'm doing it wrong, I keep getting the same error.
![error](https://user-images.githubusercontent.com/30182761/28295001-77e64762-6b12-11e7-8992-72df78f89947.JPG)

**Comment by justin522** [comment]
Well, without more details all I can do is guess what I might have done wrong in your shoes. In the previous posts it doesn't specify that the the face gets added to the same mesh that you're exporting, not a new mesh added to the scene.the previous posts it doesn't specify that the the face gets added to the same mesh that you're exporting, not a new mesh added to the scene.

Here's a blender file with a simple example of a mesh that exports, and a mesh that doesn't.
[example.zip](https://github.com/mrdoob/three.js/files/1154390/example.zip)

**Comment by mikerc19** [comment]
Here is a sample of what I'm trying to export to "tree js". a simple object (Plane, sphere, cylinder, etc.. ) is easy to export. But not this and can't figure out why. I tried converting to curves into a mesh but that didn't work either:

[mysample.zip](https://github.com/mrdoob/three.js/files/1156753/mysample.zip)

**Comment by mikerc19** [comment]
Hey @justin522 I figured out what you were saying, so I made faces all the way. Thanks for your help.

**Comment by justin522** [comment]
@mikerc19 : ) Glad I could help.

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
