### ISSUE TITLE
Resource leak in AsciiEffect.js

### ISSUE THREAD

**Issue by johnbuttcoingalt** [mrdoob/three.js#11741]
##### Description of the problem 

The AsciiEffect filter (examples/js/effects/AsciiEffect.js) creates orphaned DOM nodes each time render() is called.

Summary: the filter creates an HTML table once and updates it every render cycle by setting innerHTML on the table element.  Each time this happens you get another detached DOM tree containing all the tr and td elements from the previous render.

Proposed fix:  recursively remove child nodes from the table element before setting innerHTML.  A context diff of such a fix:

```patch
*** /usr/local/share/three.js/examples/js/effects/AsciiEffect.js        2016-12-15 00:04:02.000000000-0800
--- lib/AsciiEffect.js  2017-07-10 16:04:46.000000000 -0700
***************
*** 270,275 ****
--- 270,278 ----
 
               }
 
+               while(oAscii.hasChildNodes()) {
+                       asciifyImageCleanup(oAscii.firstChild);
+               }
               oAscii.innerHTML = "<tr><td>" + strChars + "</td></tr>";
 
               // console.timeEnd('rendering');
***************
*** 278,283 ****
--- 281,293 ----
 
       }
 
+       function asciifyImageCleanup(node) {
+               while(node.hasChildNodes()) {
+                       asciifyImageCleanup(node.firstChild);
+               }
+               node.parentNode.removeChild(node);
+       }
+ 
       // end modified asciifyImage block
 
 };
```

##### Three.js version

- [x] All of them

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by mrdoob** [comment]
Would you like to do a Pull Request?

**Comment by zz85** [comment]
hmms, i'm curious to know why this causes detached dom tree? is `oAscii` holding a reference that causes the DOM not to be garbage collected?

**Comment by zz85** [comment]
I did a heapdump but I do not see any visible leaks

![image](https://user-images.githubusercontent.com/314997/29697518-3bb53f44-8982-11e7-91ef-b74879260b7a.png)

**Comment by Mugen87** [comment]
I'm also unable to reproduce the memory leak. Closing.
