### ISSUE TITLE
GLTF2Loader removes extras from mesh

### ISSUE THREAD

**Issue by twittmann** [mrdoob/three.js#11745]
the extras of the mesh tag is not accesible.

I had a look at the source and found the error near
line: 2260 // clone Mesh to add to _node
the group ( which is equivalent to the read mesh ) is thrown away .. but the userData holds the extra info.

_node => holds the userData of the Node
child => hold the userData of the Primitve
 
so maybe there is a dummy node needed just to hold meshes userData. 

I'm not sure If this make sense couse removing this "group" seems to be done on purpose. 
( may be a performance tweak )

##### Three.js version

- [x ] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
Thanks for investigating @twittmann — you're right, this is a bug in the loader. The group is necessary because there could be (but very rarely are) multiple primitives in a mesh. Will get this patched as soon as I can get to it, or feel free to open a PR. 🙂

**Comment by donmccurdy** [comment]
This issue was fixed in #11757 by @twittmann and can be closed now.
