### ISSUE TITLE
how to submit a project

### ISSUE THREAD

**Issue by x1911** [mrdoob/three.js#11747]
hi Mr.doob, i appreciate your great work, thank you that you make so great libary .

with three.js after serveral months finally finsh a 3D game alpha version

which is www.dogfightx.com, 

is there any possibility submit it to the project list on three.org? 🙂

regards

**Comment by mrdoob** [comment]
I've just added a "submit project" link to http://threejs.org 😊

https://docs.google.com/forms/d/e/1FAIpQLSfrfc5cKz5HlWOYuYKP4igo0U0iUNtacfIwM54WEYXReJOO2Q/viewform
