### ISSUE TITLE
Lack of binary converter when three.js replaced python obj converter with node.js script

### ISSUE THREAD

**Issue by liuwei** [mrdoob/three.js#11744]
I am very glad to know that three.js replaced python obj converter with node.js script. The new converter only has few lines so it is very easy to understand and easy to extend to other 20+ converters such as fbx to json format for 3d models.  
But, python obj converter also has the other function: convert obj to binary json format. It is useful to condense and encrypt the json file. Can we get the obj converter to binary format with node.js script? 
Thanks!

**Comment by mrdoob** [comment]
The binary json format is deprecated. I would suggest using GLTF2 binary instead.

**Comment by liuwei** [comment]
Thank you, mrdoob. I am not expected that you can answer it in person.
Could you do me a favor to answer my question which also has another point：how to convert obj format file to GLTF2 binary format with node.js script like the following simple codes to convert obj to three json format?  

var content = JSON.stringify( objLoader.parse( text ).toJSON(), parseNumber );
fs.writeFileSync( path.basename( file, '.obj' ) + '.json', content, 'utf8' );

Thank you very much!

**Comment by mrdoob** [comment]
For this specific conversion, I would load the obj into [Blender](https://www.blender.org/) and [export to gltf](https://github.com/KhronosGroup/glTF-Blender-Exporter).
