### ISSUE TITLE
Infinite perspective projection camera

### ISSUE THREAD

**Issue by lexaknyazev** [mrdoob/three.js#11755]
Please, consider adding support for perspective cameras with infinite projection matrix (when `zfar` isn't defined).

Some background:
https://github.com/KhronosGroup/glTF/issues/722

glTF reference;
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#infinite-perspective-projection

CC @donmccurdy

**Comment by WestLangley** [comment]
What would you say is a compelling reason for supporting this option -- other than glTF supports it?

**Comment by lexaknyazev** [comment]
Here's a quote from
```
Tightening the Precision of Perspective Rendering
Paul Upchurch, Mathieu Desbrun
Journal of Graphics Tools, Volume 16, Issue 1, 2012
```
> **Infinite Projection versus Standard Projection**<br>
> The difference between the two methods above is 2ǫ relative error in depth, or 2ǫ absolute error in depth comparison. Since depth is in the range of [−1, 1] a relative (or absolute) error of 2ǫ is equivalent to a relative error of at least 2ǫ in depth. <br>
> While the infinite projection method has 2ǫ better precision and covers view space from the near plane to infinity, one might argue that, if there is no interest in rendering objects beyond a far clipping plane, the smaller depth buckets of a standard projection may be better. It is, however, easy to see that the precision of an infinite projection is better over a larger viewing range than the precision of a finite projection with reasonably large values of `f / n`.

**Comment by WestLangley** [comment]
Yes, I was aware of that paper. 

>Infinite projections are used cautiously since they are assumed to negatively impact precision. This is due to the same number of depth storage bits being distributed across a larger Z range.

>However, our analysis will show, counterintuitively, that the infinite projection is a more precise general purpose projection and the finite projection is only useful when the depth range ratio is very small or extremely high precision is needed at the near plane.

They provide a theoretical result that with an "infinite" projection matrix, precision can be improved by 2 machine units _as compared to a finite projection with reasonably large values of f / n._

But we do not advise users to do that. We advise users to set the near plane to be as large as is reasonable, and to set the far plane reasonably close.

>What would you say is a compelling reason for supporting this option -- other than glTF supports it?

I am still interested in hearing of a compelling three.js use case, however. Why is glTF supporting it?

**Comment by lexaknyazev** [comment]
> Why is glTF supporting it?

It was added by request from Oculus. The late Johannes van Waveren was advocating for making infinite projection matrix "everyone's first choice".

From recent experiences, models with unusually big dimensions don't show up in [three.js glTF viewer](https://gltf-viewer.donmccurdy.com/). Zooming camera out reveals that far plane isn't far enough. E.g.:
![image](https://user-images.githubusercontent.com/3479527/28177952-c245f6b6-680d-11e7-9d64-c354356fae07.png)

Of course, one could argue that camera planes should be adjusted individually for each model/scene.

**Comment by WestLangley** [comment]
>Of course, one could argue that camera planes should be adjusted individually for each model/scene.

Yeah, that seems like a user-error. Ensure the far plane value is big enough to contain the scene, and set `controls.maxDistance` to a reasonable value.

**Comment by donmccurdy** [comment]
Thanks all, I will improve the drag-and-drop viewer to infer appropriate near/far planes automatically (https://github.com/donmccurdy/three-gltf-viewer/issues/19).

Whether three.js should support infinite projection matrices, I will leave to you all.

**Comment by WestLangley** [comment]
Closing, but we can revisit if there is a compelling use case.

**Comment by trusktr** [comment]
> making infinite projection matrix "everyone's first choice".

Great 👍, because that's obviously the path to least friction for people wanting to just make a scene without fiddling with numbers and having to do math (as easy as CSS `perspective` property); it makes things easier for people.

**Comment by trusktr** [comment]
> Closing, but we can revisit if there is a compelling use case.

@WestLangley A bunch of people want to do this:

- people who know basic web technology (like using CSS 3D `perspective`) should be able to take existing knowledge and apply it in Three.js without friction.
- Some people like to mix CSS3D with WebGL, and not having infinite perspective is a barrier to doing this. Here's a bunch of examples and questions:
  - http://www.emagix.net/academic/mscs-project/item/camera-sync-with-css3-and-webgl-threejs
  - http://learningthreejs.com/blog/2013/04/30/closing-the-gap-between-html-and-webgl/
  - https://github.com/jeromeetienne/threex.htmlmixer (nice demo!)
  - http://michael-staub.rhcloud.com/2015/05/11/webvr-mixing-html-and-webgl/
  - https://stackoverflow.com/questions/33768227
  - https://stackoverflow.com/questions/24681170
  - http://adndevblog.typepad.com/cloud_and_mobile/2015/07/embedding-webpages-in-a-3d-threejs-scene.html
  - http://www.html5gamedevs.com/topic/11910-embedded-html/
  - https://docs.argonjs.io/tutorial/part2

Seems like having infinite perspective would be useful if it doesn't exist yet. If CSS 3D can do it, so can Three!
