### ISSUE TITLE
Dispose opportunity for WebVRManager

### ISSUE THREAD

**Issue by proteamer** [mrdoob/three.js#11758]
I faced with the memory leaks issue during disposing **WebGLRenderer** and figured out that reason of memory leaks is `vrdisplaypresentchange` event handler which is added in **WebVRManager**. I guess that we need `dispose` method to remove `vrdisplaypresentchange` event listener in **WebVRManager** and call `this.vr.dispose()` in `dispose` method of **WebGLRenderer**:

```javascript
// src/renderers/webvr/WebVRManager.js
this.dispose = function() {

	window.removeEventListener( 'vrdisplaypresentchange', onVRDisplayPresentChange );
};
```

```javascript
// src/renderers/WebGLRenderer.js
this.dispose = function () {

	_canvas.removeEventListener( 'webglcontextlost', onContextLost, false );

	renderLists.dispose();
	vr.dispose();
};
```

##### Three.js version

- [ ] Dev
- [x] r86

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Looks good! Would you like to do a Pull Request?
