### ISSUE TITLE
BufferGeometry vertex colors light  intensity

### ISSUE THREAD

**Issue by vinsticSmith** [mrdoob/three.js#11750]
##### Description of the problem 

When using vertex colors, light intensity must be set to a small value(0.003) to show objects correctly.but when using material's color, objects can be shown correctly under the default intensity(1) of light.

https://embed.plnkr.co/GWSuAbmSGHv4o75WK2Rj/

##### Three.js version

- [ ] Dev
- [x] r86
- [ ] ...

##### Browser

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by vinsticSmith** [comment]
Oh I see,,,,,color value must be from 0 to 1

**Comment by mrdoob** [comment]
😀
