### ISSUE TITLE
ThreeJSAnimationExporter Make 3d Max stuck

### ISSUE THREAD

**Issue by L-WindRider** [mrdoob/three.js#11751]
Software version : MAX2016_64bit
ThreeJSAnimationExporter：THREE.REVISION 86 in the library
At that time situation：Animation run again and again, Other card dead state.

**Comment by L-WindRider** [comment]
@mrdoob  I feel like I'm missing something.

**Comment by mrdoob** [comment]
Seems like ThreeJSAnimationExporter has become unmaintained.

**Comment by L-WindRider** [comment]
@mrdoob  So which version of it is maintained!

**Comment by L-WindRider** [comment]
@mrdoob  Or so, I have only ".max "with animated models, do you have any other good ways to make" threejs "available?
