### ISSUE TITLE
Labels: Enhancement ==> Feature Request

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#11759]
I suggest we replace the _Enhancement_ tag with _Feature Request_.

Although we use the words to mean the same thing, an Enhancement is a feature request that is deemed to be a good idea. That leaves no tags for feature requests that are not good ideas. (Well, I guess we could have a _Bad Idea_ tag, but that's a bad idea.)

Also, with a _Feature Request_ tag, the person adding the tag is not passing judgement on the reasonableness of the proposal.

The _Suggestion_ tag is reserved for proposals that are not feature requests -- such as this one.

**Comment by Mugen87** [comment]
And `Enhancement (Easy)` would turn into `Feature Request (Easy)`, right? 

TBH, i don't have a strong opinion on this one. Both options are okay for me...

**Comment by WestLangley** [comment]
Yes.

**Comment by mrdoob** [comment]
Sounds good to me 👍

**Comment by mrdoob** [comment]
Done!
