### ISSUE TITLE
ColladaLoader uses deprecated MultiMaterial

### ISSUE THREAD

**Issue by brmscheiner** [mrdoob/three.js#11760]
ColladaLoader.js [uses MultiMaterial](https://github.com/mrdoob/three.js/blob/5c2ebc708d61245c0fff40c19aee7d1dcd93e817/examples/js/loaders/ColladaLoader.js#L1180), which generates a deprecation warning every time I use it. Should be an easy fix, I would be willing to submit a PR after the issue is validated.

**Comment by Mugen87** [comment]
I think you can do this change but you should keep in mind that `ColladaLoader2` should be your first choice for loading collada models. `ColladaLoader2` was enhanced in the last weeks and all existing collada examples of `three.js` now use this version. There is only one feature `ColladaLoader2`  does not support so far in contrast to its predecessor: keyframe animations

**Comment by brmscheiner** [comment]
Ahh. Well if the loader is going to be removed soon it's probably not worth the trouble. I'll just switch to ColladaLoader2. Thanks for the heads up!

**Comment by Mugen87** [comment]
I forgot to mention that you have to pick `ColladaLoader2` from the `dev` branch. It's not used in production yet, but it will be available with `R87`.
