### ISSUE TITLE
GLTF2Loader -- support for CUBICSPLINE interpolation

### ISSUE THREAD

**Issue by zellski** [mrdoob/three.js#11761]
I've noticed that GLTF2Loader is undergoing fairly rapid iteration. Is there work in progress on supporting the new interpolation modes, most interestingly CUBICSPLINE? Of all the improvements from GLTF1 to GLTF2, getting away from densely sampled animation transforms (and the resulting enormous model files) is perhaps the most exciting.

If nobody else is working on this, we may end up taking a pass on it.

**Comment by donmccurdy** [comment]
> Is there work in progress on supporting the new interpolation modes, most interestingly CUBICSPLINE?

Not started yet, no. Please do feel free to work on this. 🙂  

/cc @takahirox

**Comment by donmccurdy** [comment]
Regarding the ongoing iteration, my own roadmap currently is:

1. Supporting experimental Draco mesh compression extension for glTF
2. KHR_cmnBlinnPhong extension
3. Refactoring to allow glTF extensions to be authored without modifying GLTF2Loader itself.

**Comment by donmccurdy** [comment]
`CUBICSPLINE` interpolation added with https://github.com/mrdoob/three.js/pull/11825. If you have a test model available, might be good to verify.

**Comment by zellski** [comment]
Great work! I believe the Blender folks are adding support for spline interpolation in their exporter shortly. Meanwhile I might hack up a tiny test-file by hand.

**Comment by donmccurdy** [comment]
Unfortunately it looks like CUBICSPLINE interpolation will need some more work. [I tried passing the glTF data directly into the three.js keyframe track](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js#L2206-L2211) and that wasn't it. Will need to read up on how both systems work and adapt the input data accordingly. See: #12233.

**Comment by zellski** [comment]
Aha, understood. You need a little McCurdy-minion to help you out.
