### ISSUE TITLE
skybox texture loading problem on chrome

### ISSUE THREAD

**Issue by eddicke** [mrdoob/three.js#11768]
##### Description of the problem 
[.Offscreen-For-WebGL-0EAEC5B0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
This is what came up in the console:
i tried duplicating the water shader material in codepen

[](https://codepen.io/marshall_hunts/pen/GEeXJa)
https://codepen.io/marshall_hunts/pen/GEeXJa
chrome couldn't load the skybox material but works fine locally

**Comment by mrdoob** [comment]
Hmm... I can't replicate...

**Comment by Mugen87** [comment]
I'm also unable to reproduce (with Chrome 60.0.3112.78)

@eddicke Do you still experience the problem?

**Comment by eddicke** [comment]
@Mugen87
@mrdoob

I think i fixed it by adding:
 THREE.TextureLoader.prototype.crossOrigin = '';

**Comment by Mugen87** [comment]
Sounds comprehensible 👍

**Comment by mrdoob** [comment]
On this topic... https://github.com/mrdoob/three.js/commit/8aacfda2d9a826749b0f1e93f757b25b7b26db86
No one has complained so far... 🤔
