### ISSUE TITLE
Three drops indices when converting from a Geometry > BufferGeometry

### ISSUE THREAD

**Issue by AndrewRayCode** [mrdoob/three.js#11776]
##### Description of the problem 

Every face in a `Geometry` has a `materialIndex`. When Three converts from a Geometry to a BufferGeometry...

    var bufferGeometry = THREE.BufferGeometry.new().fromGeometry(geometry);

...there's [an intermediary step where a DirectGeometry is used](https://github.com/mrdoob/three.js/blob/bde8a0540d1b6a7f0a9daf66f00e8f160994ff93/src/core/BufferGeometry.js#L467)...

    fromGeometry: function ( geometry ) {
        geometry.__directGeometry = new DirectGeometry().fromGeometry( geometry );

Note that a [`DirectGeometry` defines an `indices` array, then does nothing with it](https://github.com/mrdoob/three.js/blob/bde8a0540d1b6a7f0a9daf66f00e8f160994ff93/src/core/DirectGeometry.js#L9).

So it's not surprising when BufferGeometry [checks the intermediary `directGeometry.indices.length`, it won't ever be populated](https://github.com/mrdoob/three.js/blob/bde8a0540d1b6a7f0a9daf66f00e8f160994ff93/src/core/BufferGeometry.js#L506).

When the BufferGeometry comes out the other end, it has no indices. `bufferGeometry.getIndex()` is null.

[It looks like DirectGeometry's ability to handle indices was removed two years ago](https://github.com/mrdoob/three.js/commit/ed0b2eafe895de62bd5dbe63db14501f28647573#diff-3a1a405a5084cef2556ee83466287251L69).

Here's a CodePen demonstrating the problem. Check the logs. The merged geometry should have indices returned, but it doesn't. https://codepen.io/andrewray/pen/gRyrzR?editors=0010

##### Three.js version

- [x] Dev
- [x] r85

##### Browser

- [x] All of them
##### OS

- [x] All of them

**Comment by mrdoob** [comment]
> Every face in a `Geometry` has a `materialIndex`. When Three converts from a Geometry to a BufferGeometry...

`materialIndex` and `indices` are different things though. `materialIndex` refers to multi-materials. `indices` refer to attribute indices.

> Note that a [`DirectGeometry` defines an `indices` array, then does nothing with it](https://github.com/mrdoob/three.js/blob/bde8a0540d1b6a7f0a9daf66f00e8f160994ff93/src/core/DirectGeometry.js#L9).

Good catch!

> [It looks like DirectGeometry's ability to handle indices was removed two years ago](https://github.com/mrdoob/three.js/commit/ed0b2eafe895de62bd5dbe63db14501f28647573#diff-3a1a405a5084cef2556ee83466287251L69).

It was also added some weeks before that. Basically, I was trying to keep indices somehow but it was not really possible so I removed it.

**Comment by AndrewRayCode** [comment]
I'm a bit confused, is this a bug or not? I discovered this because [the ObjExporter first converts to a `BufferGeometry`](https://github.com/mrdoob/three.js/blob/master/examples/js/exporters/OBJExporter.js#L37):

    geometry = new THREE.BufferGeometry().setFromObject( mesh );

And then it [tries to read indices](https://github.com/mrdoob/three.js/blob/master/examples/js/exporters/OBJExporter.js#L47):

    var indices = geometry.getIndex();

which will always be null, because of the above conversion problem.

How are indices supposed to be populated from a Geometry > BufferGeometry? It was my misconception that they were read from `face.materialIndex`. I was using materialIndex and sending it through the objexporter and I was getting correct uv indices on export, but something about upgrading three made that stop working. I'm not sure which link in my mental chain is the incorrect one.

Related: Downstream this is affecting my ability to get indices from buffergeometry > objexport, since indices aren't populated. If you offhandedly know of any resources to untangle my SO question about how to manually set indices, that would be very helpful: https://stackoverflow.com/questions/45123977/three-js-correct-way-to-setindex-indices-for-buffergeometry

**Comment by Bryce-Summers** [comment]
I have also run into this issue, but from the input side and was about to write an issue statement.

I'm doing some topology / mesh connectivity work and need the indices to form connectivity data structures, such as one where every face stores its neighboring faces.

I'm loading an .obj file that has vertices and face indices, but OBJLoader2 loads and converts my file directly to a Buffer Geometry and thereby drops the index information. This is great for rendering, but it is not as great for geometers and topologists.

A work around is that I can convert the buffer geometry back to a regular geometry, then call the mergeVertices routine (I'm glad thats there.)
```
        geometry = new THREE.Geometry().fromBufferGeometry( geometry )
        geometry.mergeVertices() # Removes duplicate vertices to 4 decimal places and indexes their faces.
```

But this is redundant work and relies on floating point precision of around 4 decimal places, which means that I wouldn't be able to support files which perfectly defined indices, but vertices that are very close together.

What I would like is one of the following. a) .obj files have the option of being loaded into indexed meshes, b) bufferGeometries properly support the index attribute as stated at [here](https://threejs.org/docs/#api/core/BufferGeometry) in the Accessing Attributes section.

One work around is that I might go hunt down an antique version of the Object loader that loaded them into geometries or I might write my own.

**Comment by WestLangley** [comment]
@Bryce-Summers Does your obj file contain _only_ vertices and faces -- and no other attributes? If that is the case, I suggest you modify your copy of `ObjLoader2` and have it return `Geometry` -- or indexed `BufferGeometry` -- which ever you prefer.

Indexed `BufferGeometry` can only reuse a vertex if all the vertices's attributes are identical. So for general use, where there can be multiple attributes, returning non-indexed `BufferGeometry` makes the most sense.

**Comment by Bryce-Summers** [comment]
@WestLangley That makes sense to me. I'll modify my version. Do you think there should be a loading option for people who want the indices from the OBJ loader?

**Comment by WestLangley** [comment]
@Bryce-Summers If you mean the option to return indexed `BufferGeometry`, no, because in most cases it is not reasonable, and it adds a lot of additional logic to the loader.

BTW, would returning non-indexed `BufferGeoemtry` and simply adding an attribute `originalIndex` solve your problem?

**Comment by Bryce-Summers** [comment]
@WestLangley Thank you for your comments. I don't mean an option to return an indexed BufferGeometry. I mean a loader to load a normal [Geometry](https://threejs.org/docs/index.html#api/core/Geometry)

A returned BufferGeometry with tacked on original indices would not solve my problem without the original vertices as well, because the BufferGeometry vertices are getting baked into the attribute buffer, which destroys the original ordering of the triangles.

**Comment by WestLangley** [comment]
>I mean a loader to load a normal Geometry

@Bryce-Summers It is not up to me to decide, but `Geometry` may be deprecated at some point, so I don't think we want to go there.

**Comment by Bryce-Summers** [comment]
ok.

**Comment by Mugen87** [comment]
Closing. It's intended to produce a non-indexed `BufferGeometry` when converting from `Geometry`.  #13378 removed the `indices` property from `DirectGeometry` to avoid further confusion.
