### ISSUE TITLE
Combining two cameras

### ISSUE THREAD

**Issue by zizizi17** [mrdoob/three.js#11777]
Hello guys.
I fount some advices from Unity3D developers, that it's good idea to combine Perspective camera ( for 3d models ) and Ortographic camera ( for 2d models, that would be just as DOM nodes ).
Is is good practice to use 2 cameras at once with different layers. 
Or it's better to use 2 scenes for displaying 3d models at one scene, and DOM node on the other one?

**Comment by WestLangley** [comment]
If you are asking which is better:
```
renderer.render( scene, camera1 ); // layer 1 only
renderer.render( scene, camera2 ); // layer 2 only
```
or
```
renderer.render( scene1, camera1 );
renderer.render( scene2, camera2 );
```
I doubt it matters.

**Comment by zizizi17** [comment]
@WestLangley, thank you for reply. 
I indeed have one more question.
Can you suggest what is the proper way to create annotation on panorama360 for user interactions? 
User click - set up the annotation and provide it with a text.

**Comment by WestLangley** [comment]
Sorry, this is not a help site. Try [stackoverflow](http://stackoverflow.com/questions/tagged/three.js) or the [forum](https://discourse.threejs.org). Be sure to show your code, and identify the part of the problem you do not know how to do.
