### ISSUE TITLE
Wireframe index BufferAttribute not updated

### ISSUE THREAD

**Issue by Fyrestar** [mrdoob/three.js#11779]
It seems when wireframe is used the extra BufferAttribute for the wireframe, generated in WebGLObjects `getWireframeAttribute`, invoked by the renderer in `renderBufferDirect`, gets cached but not updated.

**Comment by Mugen87** [comment]
Reference: https://discourse.threejs.org/t/wireframe-material-issue/158

**Comment by WestLangley** [comment]
Can you please provide a live example to demonstrate exactly what you are doing?

**Comment by Mugen87** [comment]
Solved via #15198
