### ISSUE TITLE
GLTF2Loader morphtargets animation doesn't work after update to latest dev branch code

### ISSUE THREAD

**Issue by samwei12** [mrdoob/three.js#11784]
##### Description of the problem 

GLTF2Loader morphtargets animation doesn't work after update to latest dev branch code. They works fine somedays before

Models:

* [https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphCube](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphCube)
* [https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphSphere](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphSphere)

##### Three.js version

- [x] Dev   5225f34115127f759d9acd6e92e8ec1d137ea9e4
- [ ] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
Thanks! Fix coming soon. (#11785)

**Comment by samwei12** [comment]
@donmccurdy Nice! It works now

**Comment by samwei12** [comment]
@donmccurdy Another question, I found that if the vertes saved like positon0,normal0,targent0,positon1,normal1,targent1,...positonN,normalN,targentN,  morph targets have bugs, I will make a new pull request later :)
