### ISSUE TITLE
Depth Test Doesn't Work When Depth Buffer Set to False While Creating Render Target

### ISSUE THREAD

**Issue by immiao** [mrdoob/three.js#11783]
##### Description of the problem 

This is an image from `webgl_rtt.html` sample.

<img width="191" alt="screen shot 2017-07-17 at 10 47 55 am" src="https://user-images.githubusercontent.com/9515045/28282387-20ecbdf2-6adf-11e7-8389-c4447733f4f9.png">

When I set `depthBuffer` to `false`, the depth test doesn't work.

	rtTexture = new THREE.WebGLRenderTarget( window.innerWidth, window.innerHeight, { minFilter: THREE.LinearFilter, magFilter: THREE.NearestFilter, format: THREE.RGBFormat, depthBuffer: false } );

##### Three.js version
Current version

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Do you mind creating a jsfiddle that shows the issue?

**Comment by immiao** [comment]
Here's the jsfiddle:

https://jsfiddle.net/p4ob9d2e/

Change the line 76 `depthBuffer: true` then it works well.

**Comment by mrdoob** [comment]
> Change line 76 to `depthBuffer: true` then it works well.

Hmm, I don't see any difference... Both render like this:

<img width="522" alt="screen shot 2017-07-18 at 5 43 28 pm" src="https://user-images.githubusercontent.com/97088/28345665-a86be7e2-6be0-11e7-98f8-b41355e15bf7.png">

**Comment by immiao** [comment]
Hmm.. Are you sure? The jsfiddle doesn't work either in Chrome && Safari on my Macbook or Safari on my iPhone. The difference isn't very obvious. The red one is always in the front of the white one in the jsfiddle.

**Comment by mrdoob** [comment]
Do you mind sharing screenshots?

**Comment by immiao** [comment]
<img width="559" alt="screen shot 2017-07-18 at 8 02 35 pm" src="https://user-images.githubusercontent.com/9515045/28348839-1ad837e6-6bf4-11e7-8abc-d57a514ca418.png">

**Comment by immiao** [comment]
This problem exists in my own project. So I test it in the sample code. Then I find it also happens in the rtt sample code.

**Comment by WestLangley** [comment]
[Simplified fiddle](https://jsfiddle.net/p4ob9d2e/1/) by commenting out the last line.

>When I set depthBuffer to false, the depth test doesn't work.

(Line 46 in the new fiddle)

@immiao Can you please explain why you find that unusual?

**Comment by WestLangley** [comment]
Depth testing in the render target requires a depth buffer so there is something to depth test against.

The fiddle appears to be working as expected. https://jsfiddle.net/p4ob9d2e/2/
