### ISSUE TITLE
GLTF2Loader default material should now be MeshStandardMaterial

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#11797]
The glTF default material (if no material is specified) has changed with glTF 2.0, and is now a MeshStandardMaterial with metalness=1, roughness=1, and a few other properties. Currently we are creating a MeshPhongMaterial.

**Comment by WestLangley** [comment]
Having the default as a pure metal seems a bit odd to me. I would expect an insulator: metalness 0, roughness 0 - 0.5. That would be most similar to Phong. But it is up to you.

Pure metals require an environment map to render properly.

**Comment by donmccurdy** [comment]
Thanks — this would be good feedback for the glTF spec, which defines the default material when none is specified in the asset. Your suggestion is good by me if it can be updated in the spec, most likely in a future version, but I do think we want to use these values unless/until that happens, so that assets will look the same in three.js as in other engines.

**Comment by donmccurdy** [comment]
See: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#default-material

**Comment by WestLangley** [comment]
I'll leave it up to you to pursue if you want.

**Comment by UX3D-nopper** [comment]
Default material looks like this:
![grafik](https://user-images.githubusercontent.com/27856744/28382751-7e3b14cc-6cbf-11e7-9ad1-21645a6d98cf.png)

At first, we had metallicFactor = 0 and roughnessFacotr = 0, but that did collide with the empty material for PBR Metallic Roughness, as there the default is metallicFactor = 1 an roughnessFactor = 1.

So, that is the background for this.

**Comment by WestLangley** [comment]
@UX3D-nopper That does not look like a rough metal to me. Metals are difficult to get right, as they require proper environment lighting.

This is `MeshStandardMaterial` with the environment map as the only light source, `metalness` 1, and `roughness` 1.

![screen shot 2017-07-19 at 3 38 53 pm](https://user-images.githubusercontent.com/1000017/28386068-6d708374-6c98-11e7-9978-6c46ae868300.png)

**Comment by UX3D-nopper** [comment]
The goal for the default material is not to get the material look like "real-world" metal, iron or gold or whatever. Goal is, that factors for no glTF and empty material are exactly the same. The result is just "something grey".

In your case, you are simulating gold, so you modify the color and probably other input factors as well.

BTW, the above rendering is using IBL.

**Comment by WestLangley** [comment]
@UX3D-nopper OK. Thank you for the clarification.

**Comment by UX3D-nopper** [comment]
No problem, I just cross checked with UE4:

![grafik](https://user-images.githubusercontent.com/27856744/28388793-236358d8-6cd4-11e7-8bd6-2eae21c6629d.png)
![grafik](https://user-images.githubusercontent.com/27856744/28388886-71605248-6cd4-11e7-8994-91e01638a944.png)


IBL with the sphere using the HDRI image from the starter content.
