### ISSUE TITLE
Blender exporter - Exported object transforms and geometry don't match Blender.

### ISSUE THREAD

**Issue by manthrax** [mrdoob/three.js#11803]
##### Description of the problem 
The blender exporter is doing a bunch of coordinate space conversions to change the up axis...
So normals and vertices have their axis swapped around....
Additionally, there are attempts to adjust transforms to compensate for this shift, but they don't seem to be consistent.
When exporting the following scene, and importing the result into the three.viewer:

![image](https://user-images.githubusercontent.com/350247/28403989-35db7c40-6cdc-11e7-9ecb-83c1d3acf279.png)

I get this:

![image](https://user-images.githubusercontent.com/350247/28404009-4cd4c668-6cdc-11e7-8d20-f839442d9a52.png)

##### Three.js version

- [x] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by manthrax** [comment]
There are a number of transformations and coordinate swaps that occur in the exporter, i think in attempts to address peoples preference for default "up" vector. These transformations are spread throughout the exporter, and don't seem completely consistent to me.

I have disabled them in a local branch of the exporter, and I get a solid 1 to 1 correspondence between blender and the three viewer.

You can get my modified exporter here if you want to check it out:
https://github.com/manthrax/three.js/tree/blender-exporter-remove-coordinate-mangling

**Comment by manthrax** [comment]
Here is the screenshot from above, after exporting with the mangling disabled:

![image](https://user-images.githubusercontent.com/350247/28404410-0956d190-6cde-11e7-91ea-92c0c9d7742a.png)

(This also has my fixes for multiple materials per mesh.)

**Comment by manthrax** [comment]
Here's a list of issues that I think might stem back to this problem:

#11403 
#11329 
#10804 
#9454 
#8592
#7967
#6436
#4207

**Comment by Mugen87** [comment]
I'm not familiar with the blender exporter but we discussed a similar problem right here #11540.

So basically an exporter that produces output in the `three.js` format (see [JSON Object Scene format](https://github.com/mrdoob/three.js/wiki/JSON-Object-Scene-format-4)) needs to ensure that the geometry is expressed in the correct coordinate system. 

I'm a little bit confused now why your geometry is imported and rendered correctly even if you removed all coordinate system transformations in the exporter. The default up axis in Blender is `Z`. In `three.js` it's the `Y` axis. So how does this work?

BTW: I agree with you that the blender exporter should change the coordinate system consistently. If this is not the case, we need a fix.

**Comment by manthrax** [comment]
The exporter used to have controls that affected how the axes would be transformed/swapped, but that UI seems to have been changed/been removed in previous revs.

And good catch on my screenshot... I did rotate the scene root in the viewer, to look at it upright. I was focusing more on the relative positions of the objects, but I understand your point.

I'm suspecting that there is more nuance here than I thought... I saw you pinged @WestLangley in that other thread. Perhaps he can provide some insight. :)

I do think there is a case to be made for exposing the transform UI again, or maybe there is some hidden way to enable it?

**Comment by Mugen87** [comment]
I'm not sure we need an UI element for choosing e.g. the `UP` axis. From my point of view the exporter should always produce the `three.js` standard coordinate system.

**Comment by izar89** [comment]
Just tested some simple _static_ scenes and your exporter seems to work perfectly! 👍
Maybe the transform UI can be hidden with a tab? Then you can import any object in blender and fix it with the transform options if the axis are different?

**Comment by manthrax** [comment]
@izar89 I think that would be a good solution. Also, fixing the existing functionality seems important.

**Comment by manthrax** [comment]
Here's a copy of the .blend that shows the problem, and the resulting export...

[art.zip](https://github.com/mrdoob/three.js/files/1163190/art.zip)

**Comment by mrdoob** [comment]
> I'm not sure we need an UI element for choosing e.g. the `UP` axis. From my point of view the exporter should always produce the `three.js` standard coordinate system.

Agreed.

**Comment by manthrax** [comment]
Here is a simpler illustration of the buggy behavior:

![image](https://user-images.githubusercontent.com/350247/28438237-4d9520ae-6d52-11e7-8838-7e750a623851.png)

![image](https://user-images.githubusercontent.com/350247/28438268-6ec667ce-6d52-11e7-99c3-38d2b5c384f6.png)

And the blend file:

[xarrows.zip](https://github.com/mrdoob/three.js/files/1163655/xarrows.zip)

**Comment by manthrax** [comment]
Here's an example where the arrows are parented tip to tail, and each is rotated 25 degrees inward:

in blender:
![image](https://user-images.githubusercontent.com/350247/28438857-6e049d0e-6d54-11e7-92bc-2f5ff04a2ca5.png)

and in the three viewer:
![image](https://user-images.githubusercontent.com/350247/28438883-884d6074-6d54-11e7-8d3a-a80c50a2f571.png)

**Comment by mrdoob** [comment]
🤔

**Comment by rohan-deshpande** [comment]
Just chiming in; https://github.com/mrdoob/three.js/issues/11803#issuecomment-316826354 I mean... that looks totally broken to me.

**Comment by manthrax** [comment]
Yeah me too.. I definitely needs some love.

I also would not be sad if there was a checkbox to allow passthrough exporting without touching vertices/transforms, for when you really just want the actual data as it is in blender.. but that is another topic.

**Comment by mrdoob** [comment]
> Yeah me too.. It definitely needs some love.

Any takers? 😇

**Comment by manthrax** [comment]
I'm looking at it....

I think there is some confusion in the exporter, or maybe some legacy code that is transforming vertices and normals, in addition to the code transforming matrices for Y up...
There is special case logic for different export scenarios.

By disabling the vertex/normal remapping, but leaving the matrix remapping as is, it seems to produce the correct output:

![image](https://user-images.githubusercontent.com/350247/28446691-3ccd3f0c-6d81-11e7-967a-ef00a0c0de39.png)


![image](https://user-images.githubusercontent.com/350247/28446693-43b8d52e-6d81-11e7-8446-4a5e8753c9b2.png)


@Mugen87

**Comment by manthrax** [comment]
After reading the code further, simply disabling the coordinate axis flipping will touch many other parts of the exporter, so I'll need to do a bunch more reading/testing to figure out exactly what is going on.

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
