### ISSUE TITLE
Docs: show as a blank page

### ISSUE THREAD

**Issue by samwei12** [mrdoob/three.js#11805]
##### Description of the problem 

I can't open the docs page at all,  it just show a blank page, like this:

<img width="1436" alt="dingtalk20170720152109" src="https://user-images.githubusercontent.com/12758352/28405240-1dd299e2-6cf2-11e7-822d-1009df9fd529.png">

```
Uncaught DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at createNewIframe (https://threejs.org/docs/:402:19)
    at https://threejs.org/docs/:104:4
```

Additionally, It works on my iPhone

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
So this happens whenever you try to open a doc page? I'm unable to reproduce this on my iMac with various browsers. What kind of OS version are you using?

BTW: This [line](https://github.com/mrdoob/three.js/blob/gh-pages/docs/index.html#L402) causes the problem in your case.

**Comment by samwei12** [comment]
@Mugen87 Yes, every time, My OS version is 10.13 beta3

**Comment by Mugen87** [comment]
Does this error also happen with Chrome and FF? What browser have you tested?

**Comment by samwei12** [comment]
@Mugen87 I had tested it with Chrome and Safari

**Comment by samwei12** [comment]
@Mugen87  After I update to the latest dev branch code, it works on my local test page, (didn't work several days ago)

<img width="1439" alt="dingtalk20170723150620" src="https://user-images.githubusercontent.com/12758352/28497391-91740d3a-6f4b-11e7-8350-5613fa903e3c.png">

**Comment by Mugen87** [comment]
Okay. If you experience the problem with the new release in production, we can reopen this issue.
