### ISSUE TITLE
editor cannot import collada file

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#11807]
1.4.1:

![screen shot 2017-07-20 at 20 24 48](https://user-images.githubusercontent.com/242577/28432893-fe7db6c4-6d89-11e7-8a9e-15be99914fe6.png)

client code uses old Tim Knip and Tony Parisi parser that loads the file just fine.

same file in finder:

![screen shot 2017-07-20 at 20 29 07](https://user-images.githubusercontent.com/242577/28432924-24af4c22-6d8a-11e7-80de-539798143ebd.png)

**Comment by Mugen87** [comment]
Is it possible that you share the file?

**Comment by makc** [comment]
ok, here is the simplest of those models: 
[PW-PRVW-main_7.dae.zip](https://github.com/mrdoob/three.js/files/1163548/PW-PRVW-main_7.dae.zip)

**Comment by Mugen87** [comment]
Thanks for the file! 

Seems like there is a problem with the geometry parsing. I'll look into this more closing the next days.
