### ISSUE TITLE
Undefinend values in planeBufferGeometry causes raycaster to return empty

### ISSUE THREAD

**Issue by kpetrow** [mrdoob/three.js#11806]
##### Description of the problem
 I create a planeBufferGeometry and fill it like so:
```
var positions = new Float32Array(grid.elevations.length * 3).fill(undefined);
for(stuff){
 positions[i * 3 + 0] = xpos ;
 positions[i * 3 + 1] = ypos;
 positions[i * 3 + 2] = (isNaN(zpos)) ? undefined : zpos;
}

var geometry = new THREE.PlaneBufferGeometry();
geometry.addAttribute('position', new THREE.BufferAttribute(positions, 3));
var terrainMesh = new THREE.Mesh(geometry, material);
terrainMesh.name = myMesh;
scene.add(terrainMesh)

```
then raycast using:
```
raycaster.setFromCamera(mouse, camera);
var intersects = raycaster.intersectObject(scene.getObjectByName('myMesh'));
```

intersects is always empty.  If I do this:
`vertices[i * 3 + 2] = (isNaN(zpos)) ? -1: zpos;`

I get a result;  

Currently I'm thinking best work around is making a second planeBufferGeometry and assign the undefined values a -1.  Then handle if(z = -1) .  This position array can get rather large though and having another one is not ideal.

##### Three.js version

- [ ] Dev
- [ X] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by kpetrow** [comment]
It fails to compute a bounding sphere when NaN values are present and it looks like the raycast function in mesh.js has:

```
if ( geometry.boundingSphere === null ) geometry.computeBoundingSphere();
sphere.copy( geometry.boundingSphere );
sphere.applyMatrix4( matrixWorld );

if ( raycaster.ray.intersectsSphere( sphere ) === false ) return;
```
Seems like there are a couple of pre-checks  with bounding sphere and bounding rectangle before it gets into the math of raycasting.  Maybe by adding 

`if ( raycaster.ray.intersectsSphere( sphere ) === false && sphere != null ) return;`

**Comment by WestLangley** [comment]
three.js does not accommodate invalid data.

```
var geometry = new THREE.PlaneBufferGeometry();
geometry.addAttribute('position', new THREE.BufferAttribute(positions, 3));
```
You should be updating the values in the existing attribute, not adding a  new one.

**Comment by kpetrow** [comment]
undefined != invalid ??  There are unknown values in my positions array because they are unknown.  If i assign a value then it is incorrect.  The position array of the PlaneBufferGeometry is populated by real world data and sometimes the z elevation for that position is unknown and should reflect that.  Should computeBoundingSphere() handle undefined values?  Do you suggest a different geometry for surfaces?  move to SO? 

![image](https://user-images.githubusercontent.com/18248938/28430654-86c55eac-6d3e-11e7-8032-0b330b61f5c7.png)

the value of cloning and making a predefined z is that i could make z of -123 = undefined later on

**Comment by makc** [comment]
lol, it says Float32Array. is `undefined` Float32?

**Comment by makc** [comment]
> populated by real world data and sometimes the z elevation for that position is unknown and should reflect that.

I say, if you do not know coordinates - set all the vertices coords in the same triangle to 0. this will make the triangle invisible, leaving the hole in its place, just like you want to.

**Comment by kpetrow** [comment]
> lol, it says Float32Array. is undefined Float32?
not sure what you mean.  Code is snippet and simplified.

> I say, if you do not know coordinates - set all the vertices coords in the same triangle to 0. this will make the triangle invisible, leaving the hole in its place, just like you want to.
I think I have tried this before.  You then start to lose edges of defined areas. because the vertex of undefined is shared with a defined vertex.

I'm just thinking that having computeBoundingSphere() handle NaN or undefined would be proper behavior.  say my plane buffer geometry is 10x10 and i put 9x9 in it.  Just have it toss out the undefined values.  Or if not wanting to mess with the computeBoundingSphere() have the raycast check if sphere is null??  Regardless if it doesnt fail on creating the mesh, then the mesh methods should work??  If you want to be strict on sparse arrays then you can be strict only after the object is created?

**Comment by makc** [comment]
ok, let's focus on this:
> having computeBoundingSphere() handle NaN or undefined

how? if a single value is undefined, then both bounding sphere center and radius are uncertain, and also have to be undefined? if so, and you try to get an answer to 'will my ray intersect this sphere and where', what shall it be? 'I don't know', I guess?

> intersects is always empty

would returning point = new THREE.Vector3 (undefined, undefined, undefined) be better?

**Comment by kpetrow** [comment]
> if a single value is undefined, then both bounding sphere center and radius are uncertain.

It should just ignore the undefined points.  say my plane is defined as:
![image](https://user-images.githubusercontent.com/18248938/28435445-262ac9d0-6d50-11e7-9d3c-5131088cd613.png)

then just toss out the other undefined values.  if the definition is less then the values, then bounding sphere should shrink wrap into what is defined.  Diameter should be the furthest defined points.  I feel like this should just be in computeBoundingSphere():

`if( isNaN(position[i+2]) )continue;`

> would returning point = new THREE.Vector3 (undefined, undefined, undefined) be better?

No, there is an intersection with the planeBufferGeometry.  It just that the raycaster fails a optimization routine because computeBoundingSphere() can not properly handle undefined/null/NaN values.  I'll dig into the ComputeBoundingSphere code later tonight. It looks like after sphere is rectangle, which also might need to be modified.

**Comment by makc** [comment]
> It should just ignore the undefined points

in other words, it should behave as if undefined values were not there?

**Comment by kpetrow** [comment]
It should behave that undefined = undefined.  Bounding sphere should measure the largest defined values..  If we are going to get into a broader discussion then i'll resort back to:

> Regardless if it doesnt fail on creating the mesh, then the mesh methods should work?? If you want to be strict on sparse arrays then you can't be strict only after the object is created?

**Comment by makc** [comment]
well if undefined value is there you can't know the sphere radius.

**Comment by kpetrow** [comment]
> well if undefined value is there you can't know the sphere radius.

you can know the largest defined sphere.  function arrayMax([1,undefined]) should give you 1 vs is well we dont know what undefined could be so I'm just going to throw an error/warning.

**Comment by kpetrow** [comment]
My proposal in src/core/BufferGeometry.js ( start at line 629):
```
for ( var i = 0, il = position.count; i < il; i ++ ) {
   vector.x = position.getX( i );
    vector.y = position.getY( i );
    vector.z = position.getZ( i );
    maxRadiusSq = Math.max( maxRadiusSq, center.distanceToSquared( vector ) );
}
```
becomes
```
for ( var i = 0, il = position.count; i < il; i ++ ) {
   if(isNaN(position.getZ( i )) ||  isNaN(position.getX( i )) || isNaN(position.getY( i )) )
      continue;
   vector.x = position.getX( i );
    vector.y = position.getY( i );
    vector.z = position.getZ( i );
    maxRadiusSq = Math.max( maxRadiusSq, center.distanceToSquared( vector ) );
}
```

I am confused by how the center is found.  Looks like you might need to find the defined min,max of x,y,z;
I see that the sphere is created but where are the init values?
```
if ( this.boundingSphere === null ) {

				this.boundingSphere = new Sphere();

			}
```

**Comment by WestLangley** [comment]
As I said, three.js does not accommodate missing, `undefined`, `null`, or otherwise invalid data. If we were to do so for this case, we would have to do the same for every method in the library.

**Comment by makc** [comment]
@kpetrow what I am saying is that if you are (obviously) not happy with what 3js puts into boundingSphere, you could do this:
```javascript
geometry.boundingSphere = new THREE.Sphere (yourCenter, yourRadius);
geometry.boundingBox = new THREE.Box3 (yourMin, yourMax);
```
instead of relying on geometry.computeBoundingSphere/Box calls. this will allow you to bypass the checks that you are saying are in the way of finding intersections?

**Comment by makc** [comment]
> should give you 1 vs is well we dont know what undefined could be

this is just silly, imagine if we could solve any problem like that? we don't know what the value of X is, so we're just going to assume it's 1 and operate under that assumption. why not 2? I like 2 more.

**Comment by kpetrow** [comment]
As I said, three.js does not accommodate missing, undefined, null, or otherwise invalid attribute data. If we were to do so for this case, we would have to do the same for every method in the library.

So the bug is too big to fix?  What is the solution then for plane buffer geometry with holes?  If I modify src code, it will create upgrade nightmare.  Is there a better geometry type for surface data?  If it is not a bug what is the solution?

this is just silly, imagine if we could solve any problem like that? we don't know what the value of X is, so we're just going to assume it's 1 and operate under that assumption. why not 2? I like 2 more.

Seriously, do you not see my point at all?  The definition of the geometry should not override or supersede the data in the geometry. Methods should respect the data in the geometey not the definition of the geometry.

**Comment by kpetrow** [comment]
geometry.boundingSphere = new THREE.Sphere (yourCenter, yourRadius);
geometry.boundingBox = new THREE.Box3 (yourMin, yourMax);

This might work. Thanks.

**Comment by makc** [comment]
> Is there a better geometry type for surface data?

that might be BufferGeometry. if you are not happy with (0,0,0)-(0,0,0)-(0,0,0) triangles in PlaneBufferGeometry, you can create your own geometry avoiding the need to do something about triangles with missing data - by not creating these triangles in the 1st place.
