### ISSUE TITLE
Mesh's raycast not working for material array.

### ISSUE THREAD

**Issue by ckddbs** [mrdoob/three.js#11801]
##### Description of the problem 

when mesh has material array, raycast's output is empty.

    var mats = [new THREE.MeshBasicMaterial(), new THREE.MeshBasicMaterial()];
    var mesh = new THREE.Mesh(new THREE.BoxBufferGeometry(1,1,1), mats);
    var raycaster = new THREE.Raycaster(new THREE.Vector3(0,0,0), new THREE.Vector3(1,0,0));
    var output = raycaster.intersectObject(mesh);

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by manthrax** [comment]
@ckddbs Did you forget to add information describing the problem?

**Comment by ckddbs** [comment]
@manthrax I wrote description.

**Comment by manthrax** [comment]
@ckddbs 
I think that raycast is failing because the ray is starting Inside the object.

This works:
`
var mats = [new THREE.MeshBasicMaterial(), new THREE.MeshBasicMaterial()];
var mesh = new THREE.Mesh(new THREE.BoxBufferGeometry(1,1,1));
var raycaster = new THREE.Raycaster(new THREE.Vector3(-4,0,0), new THREE.Vector3(1,0,0));
var output = raycaster.intersectObject(mesh);console.log(output)
`

**Comment by ckddbs** [comment]
The problem is that material array doesn't have ".side" member used in below function.

_function checkIntersection( object, material, raycaster, ray, pA, pB, pC, point ) {_

**Comment by Mugen87** [comment]
see #11754

**Comment by manthrax** [comment]
@Mugen87 Interesting. Can you test this case with your fix for #11754 ?

**Comment by Mugen87** [comment]
Solved via #14227

**Comment by balusethuraman** [comment]
@Mugen87 I am facing the similar issue here. I have a single object loaded via objLoader which has multiple materials in it. I am trying to perform raycasting on to that object and it returns all the materials instead of returing the raycasted one.

Any help would be highly appreciated.

THanks

**Comment by Mugen87** [comment]
>  I am trying to perform raycasting on to that object and it returns all the materials instead of returing the raycasted one.

The result object of an intersection test does not return materials at all. This issue here was about multi-material support in general when perform raycasting against a mesh.

Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help.

**Comment by balusethuraman** [comment]
@Mugen87 Sorry. I should have been bit more clearer with my comment. Raycasting returns the array of objects (of different material). I am attaching the code for reference.

I am loading a object using objLoader (which is multimaterial object)

var mtlLoader = new THREE.MTLLoader();
            mtlLoader.setBaseUrl('/CustomSublimation/store/3D/assets/');
            mtlLoader.setPath('/CustomSublimation/store/3D/assets/');
            mtlLoader.load('Test.mtl', function (materials) {
                materials.preload();
                
                var objLoader = new THREE.OBJLoader();
                objLoader.setMaterials(materials);
                objLoader.setPath('/CustomSublimation/store/3D/assets/');
                objLoader.load('Test.obj', function (object) {
                	
                	var imgSrc = "http://localhost:8080/CustomSublimation/store/3D/assets/228180.png";
                	console.log(imgSrc);
                	var textureLoader = new THREE.TextureLoader();
                	textureLoader.crossOrigin = '';
                	var texture = textureLoader.load( imgSrc );
                	var i=0;
                	
                  object.traverse( function( node ) {
                	  	if(node.geometry){
						// Creating multi material object by passing material array from mtlLoader
                	  		multiMaterialObject = THREE.SceneUtils.createMultiMaterialObject( node.geometry, materials.materialsArray );  
                	  		multiMaterialObject.traverse(function(child){
                	  			if( child.material ) {
                	  				var material = new THREE.MeshLambertMaterial({
                                    	map: texture
            						    });
                                     if ( child instanceof THREE.Mesh ) {
                                    	material.name= child.material.name;
                                    	child.material = material;
                                        mesh[i] = child;
                                        i=i+1;
                                        child.castShadow = true;
                                        child.material.side = THREE.DoubleSide;
                                    } 
                                 }
                	  		});
                	  		objects[0] = multiMaterialObject;
                	  		
                	  	}
                       
                       
                	 });
                	
                    scene.add(multiMaterialObject);

                });

            });
           

            raycaster = new THREE.Raycaster();
            
            /* Renderer */

            //renderer = new THREE.WebGLRenderer();
            renderer = new THREE.WebGLRenderer({
            	preserveDrawingBuffer: true
       		 });
            renderer.shadowMap.enabled = true;
            renderer.shadowMap.type = THREE.PCFSoftShadowMap; // default THREE.PCFShadowMap
           /*  renderer.setPixelRatio(window.devicePixelRatio); */
            renderer.setPixelRatio(2);
            renderer.setSize(container.innerWidth(), container.innerHeight());
            renderer.setClearColor(new THREE.Color("#F0F0F0"));
            
            container.html(renderer.domElement);
            
            /* code for highlight*/
           /*  composer = new THREE.EffectComposer( renderer );
            var renderPass = new THREE.RenderPass( scene, camera );
			composer.addPass( renderPass );
			 outlinePass = new THREE.OutlinePass( new THREE.Vector2( container.innerWidth(), container.innerHeight() ), scene, camera );
			composer.addPass( outlinePass ); */
			
            /* Light */
            //Create a PointLight and turn on shadows for the light
            var light = new THREE.PointLight( 0xffffff, 1, 100 );
            light.position.set( 0, 10, 0 );
            light.castShadow = true;            // default false
            scene.add( light );

            //Set up shadow properties for the light
           /*  light.shadow.mapSize.width = 512;  // default
            light.shadow.mapSize.height = 512; // default
            light.shadow.camera.near = 0.5;       // default
            light.shadow.camera.far = 500      // default */

            /* Controls */

            controls = new THREE.OrbitControls(camera, renderer.domElement);
            controls.enableDamping = true;
            controls.dampingFactor = 0.25;
            controls.enableZoom = true;
            controls.rotateSpeed = 1;
            controls.maxPolarAngle = 1.3;
            controls.minPolarAngle = 1.3;
            controls.minDistance = 2.5;
            controls.maxDistance = 5;

            /* Events */
			
            
            window.addEventListener('resize', onWindowResize, false);
            window.addEventListener('keydown', onKeyboardEvent, false);
            document.addEventListener( 'click', onDocumentMouseClick, false );
			
			function onDocumentMouseClick( event ) {
			/* event.preventDefault();
			mouse.x = ( event.clientX / container.innerWidth() ) * 2 - 1;
			mouse.y = - ( event.clientY / container.innerHeight() ) * 2 + 1;

			// find intersections
			raycaster.setFromCamera( mouse, camera );
			var intersects = raycaster.intersectObjects( objects, true );  // response returns all the objects of different materials (What I need is only the object with the corresponding material what the user is clicked)
			if ( intersects.length > 0 ) {
					INTERSECTED = intersects[ 0 ].object;
					textureColor = INTERSECTED.material.color.getHex();
alert(INTERSECTED.material.name);
							
			} else {
				
			} */
			
			
		}

**Comment by homerjam** [comment]
I seem to have found a similar problem, I'm not sure if it's unique to InstancedMesh. I've created a reproduction here:

https://jsfiddle.net/homerjam/ojqrtezk/9/

Note this is the `webgl_instancing_raycast` example with the following changes:

```diff
// Line 51
- mesh = new THREE.InstancedMesh( geometry, [ material ], count );

+ geometry.clearGroups();
+ geometry.addGroup( 0, Infinity, 0 );

+ mesh = new THREE.InstancedMesh( geometry, [ material ], count );
```

As you'll (hopefully) see this causes a crash (I'm running latest Chrome on an M1 mac). This seems to be happening because of the call to `raycaster.intersectObject( mesh );` (line 132), without it the example/reproduction runs as normal (minus raycasting ofc).
