### ISSUE TITLE
Sphere Plane Intersection

### ISSUE THREAD

**Issue by casawa** [mrdoob/three.js#11818]
##### Description of the problem 

Suppose I create a Plane using setFromNormalAndCoplanarPoint with normal (0, 1, 0) and coplanar point (0, 5, 0) -- then plane.constant = -5. If I have a sphere of radius 2 centered at (0, 6, 0), and I use its intersectsPlane method on the plane I created, wouldn't

 Math.abs( this.center.dot( plane.normal ) - plane.constant ) = 11,

meaning the method would return false even though the sphere intersects the plane?

Should it be Math.abs( this.center.dot( plane.normal ) + plane.constant )?

##### Three.js version

- [ ] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
related #10957

**Comment by WestLangley** [comment]
Yes. And to avoid that error, I'd simplify the method like so:
```javascript
intersectsPlane: function ( plane ) {

	return Math.abs( plane.distanceToPoint( this.center ) ) <= this.radius;

},
```
