### ISSUE TITLE
Wrong color

### ISSUE THREAD

**Issue by bidolah** [mrdoob/three.js#11815]
##### Description of the problem 

The same color created using RGB string and hexadecimal color different on scene 

http://jsfiddle.net/bidolah/akmcv7Lh/171/

##### Three.js version

- [ ] Dev
- [x] r86
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by cecilemuller** [comment]
The float colors are in 0..1 range, not 0..255, so it should be `THREE.Color(1, 0.07, 0)` instead.

**Comment by jostschmithals** [comment]
or as CSS-string: 
` { color: new THREE.Color( 'rgb(255, 17 ,0)' ) }`
