### ISSUE TITLE
frustumCulled - flag doesn't have any effect

### ISSUE THREAD

**Issue by juusor** [mrdoob/three.js#11813]
I've been trying to disable frustum culling by setting the frustumCulled flag to false on objects that should be always visible even if they are beyond the camera far plane. 

But for me it seems that the frustumCulled flag doesn't have any effect. Or have I totally missed something elementary around the topic? (I didn't find much examples of how this flag should be used.)

Here is a simple example for demonstration:
http://jsfiddle.net/hw9rcLL8/115/
I think that the blue cube should be visible all the time...

##### Three.js version

- [x] Dev
- [x] r86

##### Browser

- [x] Chrome
- [x] Firefox

##### OS

- [x] Linux

**Comment by arodic** [comment]
Frustum culling does not affect near/far clipping. You need to increase your near/far range.

**Comment by juusor** [comment]
Aah.. ok. So the frustum culling only happens on left/right/bottom/top planes of the frustum and the camera's near/far ranges are "absolute" (so the there is no way to draw objects beyond them).

Perhaps a note about this could be added to Object3D's documentation (within the frustumCulled flag)? I guess this might be useful since many references illustrate that the far/near planes are equally part the frustum (also [Wikipedia](https://en.wikipedia.org/wiki/Viewing_frustum) which is referred from Three.js documentation).

Anyway, thanks for the answer. I'll open a discussing on Stackoverflow if still need some answers.
