### ISSUE TITLE
Blender Exporter - BufferGeometries not creating "groups

### ISSUE THREAD

**Issue by manthrax** [mrdoob/three.js#11816]
##### Description of the problem 

This form is for three.js bug reports and feature requests only.  
This is NOT a help site. Do not ask help questions here.  
If you need help, please use [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.  
A code snippet, screenshot, and small-test help us understand.

You can edit for small-test.  
http://jsfiddle.net/akmcv7Lh/ (current revision)  
http://jsfiddle.net/hw9rcLL8/ (dev)

##### Three.js version

- [ ] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
#11817
