### ISSUE TITLE
Blender Exporter - not exporting "groups" for BufferGeometries  with multiple materials.

### ISSUE THREAD

**Issue by manthrax** [mrdoob/three.js#11817]
##### Description of the problem 

The Blender exporter doesn't export groups for each sequence of faces with a given material on BufferGeometries.

This doesn't look suuper hard to implement, so I may take a shot at it, if nobody objects.

##### Three.js version

- [*] Dev
- [*] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by manthrax** [comment]
I've been looking at this...

There is code in the exporter to generate "drawcalls" for indexed buffergeometries element counts that exceed  the 0xffff or 0x7fffffff limits, imposed by webGL indexing.

The exporter exports these drawcalls, but they are not the same format as Groups used by the engine.

The exporter also exports these into the body of the export, rather than within the "data" object, so during parsing, the engine is ignoring them...

The implication here is that BufferGeometry of meshes > size of index buffer have been broken for some time.
I also ran across this the other day when exporting a scene with geometries > ~0xffff elements, and had to switch to 32 bit index buffers to get my export to work.

So now drawcalls has been superceded with Groups.

I think I can combine these two issues and fix both of them.

Looking into it....

**Comment by mrdoob** [comment]
Yes, that `drawcalls` object was removed quite a while ago.

**Comment by manthrax** [comment]
Yeah. The exporter is still emitting "drawcalls" for geoms > size of index, and it's ignored by the object parse because it's emitted in the wrong place, so it's a bug. Im hoping I can fix it in the same pass as adding material groups to buffer geometry export.

**Comment by manthrax** [comment]
Are there still concerns for platforms with the 65530 limit on primitive indices? If not, we may just want to make 32 bit index buffers the default..

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
