### ISSUE TITLE
Gltf2loader morph targets don't work together with skins

### ISSUE THREAD

**Issue by samwei12** [mrdoob/three.js#11812]
##### Description of the problem 

1. One simple glTF model has skins and morph targets
2. Skins work well
3. Change morph targets' weight don't work

like this :

![triangle_morph](https://user-images.githubusercontent.com/12758352/28446570-3f0c8ad8-6d91-11e7-85ca-f88c6fedd596.gif)

test model: 

[triangle.zip](https://github.com/mrdoob/three.js/files/1164235/triangle.zip)

##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
Testing this on https://gltf-viewer.donmccurdy.com/, it looks OK —

![27a85b96-d234-4a68-99ea-1f8d520e6534-57120-0000bc9ef0e0c02e](https://user-images.githubusercontent.com/1848368/28474858-04339a78-6dff-11e7-9106-4d669b27111c.gif)

Maybe you need to update to latest GLTF2Loader, or there is a bug with your viewer code?

**Comment by samwei12** [comment]
@donmccurdy 
Thanks, after I updated my code, It works on your test page , my viewer code may have same bugs, I will check it.
BTW: After I dragged models into your test page, it just show the content of the folder or glTF, so I copied your code and run it locally, like this:

<img width="1316" alt="dingtalk20170723153017" src="https://user-images.githubusercontent.com/12758352/28497518-f304cc80-6f4e-11e7-89dc-7658cb6365fb.png">

**Comment by donmccurdy** [comment]
@samwei12 good to hear!

Do you still see just the folder contents on https://gltf-viewer.donmccurdy.com/ now? if so could you open a bug on https://github.com/donmccurdy/three-gltf-viewer and let me know what browser you're using? Thanks!
