### ISSUE TITLE
CubeTexture with scene.background is getting rendered only in one eye in VR

### ISSUE THREAD

**Issue by mamun4122** [mrdoob/three.js#11828]
##### Description of the problem 

Skybox loaded with CubeTextureLoader() is not working properly in VR mode. When i enter VR mode it appears only for one eye. Here is the code:
```javascript
var environment_skybox = new THREE.CubeTextureLoader()
    .setPath( 'textures/cube/Bridge2/')
    .load( [ 'posx.jpg', 'negx.jpg', 'posy.jpg', 'negy.jpg', 'posz.jpg', 'negz.jpg' ] );

scene.background = environment_skybox;
```

**Non-VR mode**
![bug1](https://user-images.githubusercontent.com/9422829/28498992-f6ba6be0-6fcc-11e7-8f14-04f51df1369f.png)

**VR mode**
![bug2](https://user-images.githubusercontent.com/9422829/28498995-06b111c0-6fcd-11e7-976c-06eb6dceb266.png)

I have found that the problem is because in [here](https://github.com/mrdoob/three.js/blob/master/build/three.js#L16253) it is not considering for `ArrayCamera`.

##### Three.js version

- [ ] Dev
- [x] r86
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
 Vive or WebVR API Emulation extension

**Comment by mrdoob** [comment]
Woops! Fixing...
