### ISSUE TITLE
MeshDepthMaterial with BasicDepthPacking seems to be broken

### ISSUE THREAD

**Issue by modjke** [mrdoob/three.js#11837]
##### Description of the problem 

MeshDepthMateril with BasicDepthPacking is relying on gl_PointCoord.z to save depth data, but it seems like at that point it's always 1.0.
Example @ docs all white too
https://threejs.org/docs/#api/materials/MeshDepthMaterial

##### Three.js version

- [x] Dev
- [x] r86
- [x] r85
- [x] r84

##### Browser

Tested on these two, but i think it's consistent across all browsers.
- [x] Chrome
- [x] Edge

##### OS

- [x] Windows

**Comment by mrdoob** [comment]
It depends on `camera.near` and `camera.far`. Probably the `camera.far` is too far in the docs viewer.
