### ISSUE TITLE
Feature: shadow color "offset"

### ISSUE THREAD

**Issue by shellka** [mrdoob/three.js#11839]
##### Description of the problem 

Hello, is it possible to add color uniform for ShadowMaterial, so instead of:
`gl_FragColor = vec4( 0.0, 0.0, 0.0, opacity * ( 1.0 - getShadowMask() ) );`

have something like:
`gl_FragColor = vec4( shadowColor, opacity * ( 1.0 - getShadowMask() ) );`

And second point - is it possible to do the same for shadows, that cast on models?
https://yadi.sk/i/xyoumCN73LPjVS
`tgl_FragColor = vec4( 0.627451, 0.12549, 0.941176, opacity * ( 1.0 - getShadowMask() ) );`

##### Three.js version

- [ ] Dev
- [x] r85

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
1. Yes
2. Sadly no...

**Comment by WestLangley** [comment]
See #8238. I have not implemented this, despite its popularity, because I was not satisfied with how it handled hotspots. Hotspots can be over-bright, and when darkened, still over-bright. Given we have tone mapping implemented, I can revisit it.

**Comment by mrdoob** [comment]
> Hello, is it possible to add color uniform for ShadowMaterial, so instead of:
`gl_FragColor = vec4( 0.0, 0.0, 0.0, opacity * ( 1.0 - getShadowMask() ) );`
>
> have something like:
`gl_FragColor = vec4( shadowColor, opacity * ( 1.0 - getShadowMask() ) );`

Done!

**Comment by shellka** [comment]
Thanks you :)
