### ISSUE TITLE
 'mapTexelToLinear' : no matching overloaded function found

### ISSUE THREAD

**Issue by Kuree** [mrdoob/three.js#11838]
##### ERROR: 0:263: 'mapTexelToLinear' : no matching overloaded function found 

I was trying to load a DDS texture from a HTTP GET response (see the code below). Three.js failed to compile the default shader file. You can see the log file here:https://pastebin.com/eKVZcwvA. The DDS file can be found [here](https://drive.google.com/file/d/0B8GykstkLy9bc0dxZ2Z5azZVMDQ/view?usp=sharing)

```javascript
var xhr2 = new XMLHttpRequest();
xhr2.open('GET', 'test.dds', true);
xhr2.responseType = 'arraybuffer';
xhr2.onload = function(e) {
    if (this.status == 200) {
        var img_data = new Uint32Array(this.response);
        var map = THREE.DDSLoader.parse(img_data, true);
        var material = new THREE.MeshBasicMaterial({map: map});
        var mesh = new THREE.Mesh(geometry, material);

        scene.add(mesh);
        camera.position.z = 0.5;
         renderer.render(scene, camera);
     }
};

xhr2.send();
```

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Chrome OS Version 60.0.3112.72 (Official Build) beta (64-bit)

**Comment by mrdoob** [comment]
Any chance you can create a jsfiddle or upload a live example somewhere?

**Comment by WestLangley** [comment]
This looks like a user error to me.
```
        var map = THREE.DDSLoader.parse( img_data, true );
        var material = new THREE.MeshBasicMaterial( { map: map } );
```

**Comment by mrdoob** [comment]
@WestLangley Hmm, I don't see the difference between your code and the @Kuree...?

**Comment by WestLangley** [comment]
There is no difference. I was pointing out the error.

`DDSLoader.parse()` does not return a `Texture`.
