### ISSUE TITLE
Standard Shader not taking into account Albedo color for environment lighting

### ISSUE THREAD

**Issue by John-DeCorato-HZ** [mrdoob/three.js#11833]
I'm working with the PBR material in Three.js and noticed that you're not taking into account the albedo color of the object when getting the indirect diffuse lighting. Here are a few images showing the problem.

![image](https://user-images.githubusercontent.com/20100243/28546776-c36efed6-7080-11e7-8d7c-2f36761cd57e.png)

This is an object with only an environment map for the light source (the intensity is multiplied by 10 for visual affect)

![image](https://user-images.githubusercontent.com/20100243/28546832-ef2db5f8-7080-11e7-9094-41f7f123b9a7.png)

This is the same object with a spot light in the scene. The fix for this should be simple. I'd make a pull request myself but finding where everything gets put together in a shader chunk system is tedious.

**Comment by WestLangley** [comment]
>noticed that you're not taking into account the albedo color of the object when getting the indirect diffuse lighting

I think that is unlikely. It is more likely you are observing only specular reflection, and the irradiance from the light source is zero (not computed) for your environment map type. Some of the relevant code may have been commented out or not completed.

Can you provide a live link so your use case is clear?

**Comment by John-DeCorato-HZ** [comment]
I see what you're talking about now. It wasn't mentioned in the documentation but digging more thoroughly through the example code helped solve the problem. Sorry for the false flag.
