### ISSUE TITLE
Possible to animate nested mesh properties?

### ISSUE THREAD

**Issue by jamesgk** [mrdoob/three.js#11834]
I'm wondering if it's possible (or supposed to be possible) to animate nested properties of a mesh, e.g. material opacity. For example I'd like to do something like the following:

```javascript
    var trackName = mesh.uuid + ".material.opacity";
    var track = new THREE.NumberKeyframeTrack(
    	trackName, [0, 1], [1, 0], THREE.InterpolateLinear );
    var clip = new THREE.AnimationClip( undefined, 1, [track] );
    mixer = new THREE.AnimationMixer( mesh );
    mixer.clipAction( clip );
```

but as far as I can tell the created PropertyBinding ultimately just sets an opacity property on the mesh.
In my case this could be fixed with the following change to https://github.com/mrdoob/three.js/blob/dev/src/animation/PropertyBinding.js#L334:

```diff
                                function setValue_direct( buffer, offset ) {

-                                       this.node[ this.propertyName ] = buffer[ offset ];
+                                       this.targetObject[ this.propertyName ] = buffer[ offset ];

                                },

                                function setValue_direct_setNeedsUpdate( buffer, offset ) {

-                                       this.node[ this.propertyName ] = buffer[ offset ];
+                                       this.targetObject[ this.propertyName ] = buffer[ offset ];
                                        this.targetObject.needsUpdate = true;

                                },

                                function setValue_direct_setMatrixWorldNeedsUpdate( buffer, offset ) {

-                                       this.node[ this.propertyName ] = buffer[ offset ];
+                                       this.targetObject[ this.propertyName ] = buffer[ offset ];
                                        this.targetObject.matrixWorldNeedsUpdate = true;

                                }
```

but I'm not sure if it's deliberate to always set properties directly on the node object rather than the target.

**Comment by donmccurdy** [comment]
This is supposed to be possible; the track name parsing is careful to allow properties of the material.

I'm not sure if the proposed fix is correct, but it look OK to me.

**Comment by Mugen87** [comment]
This also works without a fix, see https://jsfiddle.net/b9t4v8wn/

**Comment by donmccurdy** [comment]
@Mugen87 nice! great that this works, although I think it may be a bug that this syntax is allowed instead of `.material.opacity`. See the unit tests for PropertyBinding here: https://github.com/mrdoob/three.js/blob/dev/test/unit/src/animation/PropertyBinding.js#L100-L129

**Comment by bhouston** [comment]
I did design it to be able to reach into sub-properties.  There are a limited number of subproperties that it supports including material, materials, and bones:

https://github.com/mrdoob/three.js/blob/dev/src/animation/PropertyBinding.js#L167

I think this pattern can be further extended to do more sub-properties if these are insufficient.

**Comment by donmccurdy** [comment]
Thanks @bhouston — as the subproperty whitelist already includes `.material`, it seems like `.material.opacity` should be OK.

@jamesgk do you have time to send a PR with your changes, and ideally update the unit tests to make sure that your syntax and @Mugen87's both work?

**Comment by jamesgk** [comment]
Yep, thanks.

**Comment by mrdoob** [comment]
@bhouston does the PR look good to you then?
