### ISSUE TITLE
renderer.clear() should probably clear all cube faces when the active render target is a WebGLRenderTargetCube

### ISSUE THREAD

**Issue by arilotter** [mrdoob/three.js#11847]
```js
const renderer = new THREE.WebGLRenderer();
const cubeCamera = new THREE.CubeCamera(0.1, 1000, 128);

// render something with the cube camera here

renderer.setRenderTarget(cubeCamera.renderTarget);
renderer.clear(); 
```

Expected behavior: `cubeCamera.renderTarget` (a `WebGLRenderTargetCube`) is fully cleared
Actual behaviour: only the currently active cube face of `cubeCamera.renderTarget` is cleared.

The following snippet shows how you can clear the entire `WebGLRenderTargetCube`
```js
const renderTarget = cubeCamera.renderTarget;
for (let i = 0; i < 6; i++) {
  renderTarget.activeCubeFace = i;
  renderer.setRenderTarget(renderTarget);
  renderer.clear();
}
```

**Comment by WestLangley** [comment]
#11850.

Let's see what the feedback is...

BTW, what is your use case?

**Comment by arilotter** [comment]
I'm rendering a bunch of static equirectangular images, and the depth buffer wasn't being cleared between renders, leading to incorrect images, so I had to clear each face of the render target before rendering each image.

**Comment by WestLangley** [comment]
>the depth buffer wasn't being cleared between renders

Why not?

**Comment by arilotter** [comment]
I wasn't using any sort of render loop, just calling `cubeCamera.updateCubeMap` and then `renderer.render`. I guess the auto clearing didn't have any opportunities to run.
