### ISSUE TITLE
clearTarget / render sets _currentRenderTarget permanently

### ISSUE THREAD

**Issue by modjke** [mrdoob/three.js#11845]
##### Description of the problem 

WebGLRenderer `clearTarget()` or `render()` with target specified permanently sets current rendering so calling `clear() `after (or clearColor/Depth/Stencil) clears previous renderTarget and not screen. Calling `setRenderTarget(null)` before `clear()` call fixes it.

##### Three.js version

- [x] Dev
- [x] r86

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by mrdoob** [comment]
Sounds like an easy to fix bug. Would you like to do a PR?

**Comment by WestLangley** [comment]
>clear() ... clears previous renderTarget and not screen.

It is more accurate to say `clear()` clears the current render target.

If you want to clear a target different from the current one, you have to set the desired target first.
