### ISSUE TITLE
Duplicated bones after SkinnedMesh::clone()

### ISSUE THREAD

**Issue by adalessandro** [mrdoob/three.js#11842]
If an instance of `SkinnedMesh` is cloned using the `SkinnedMesh::clone()` method, the resulting clone will have its bones duplicated. See the following explanation of the calling sequence:

The `SkinnedMesh::clone()` method will do two things:
* First it will call its contructor.
* Then calls the`Mesh::copy()` method, which calls `Object3D::copy()`.

https://github.com/mrdoob/three.js/blob/dev/src/objects/SkinnedMesh.js#L202

The constructor creates `Bone` objects from the geometry data and adds them to the current `SkinnedMesh` instance at `SkinnedMesh::initBones()`.

The later call to `Object3D::copy()` -which is called with (default) recursion enabled- will clone and add new children. These bones are already children of the new `SkinnedMesh` instance, so we're cloning and re-adding the same bones again.

Related to the issue itself, it'd be useful to allow changing the recursive parameter from the clone/copy methods. Here's a possible patch, adding the `recursive` parameter:

https://github.com/adalessandro/three.js/commit/272d308a5f069a9f8ba16853485b9b7401020502

Issue reported on `dev` branch.

**Comment by Mugen87** [comment]
We already have an ongoing discussion for this issue right here: #11574
