### ISSUE TITLE
iOS only, flickering edges with a RawShaderMaterial

### ISSUE THREAD

**Issue by charlesfleche** [mrdoob/three.js#11852]
##### Edges flicker in iOS, work on other browsers

JSFiddle : https://jsfiddle.net/charlesfleche/zmww5kos/

Expected result, here on Chromium Linux:
![Expected result, here on Chromium Linux](https://user-images.githubusercontent.com/2563098/28673341-8df22738-72e2-11e7-8f94-32f48473f01f.png)

Flickering edges on Safari iO (flickering is visible and edge artifacts change on a per frame render basis):
![Flickering edges on Safari iOS](https://user-images.githubusercontent.com/2563098/28673374-9c310ea4-72e2-11e7-8bc6-49ec76fd953d.png)

##### Context

Our custom shader composites arrays of textures with standard compositing operation (over, add, mult...), the same way Photoshop / After Effects / Nuke would composite layers. The fragment gets a procedural base color, assign it to `gl_FragColor`, then for each layer:
1. the matching texture gets composited with `gl_FragColor`: `gl_FragColor = merge(gl_FragColor, texelColor, MERGE_OPERATION)`. The type of merge (over, add, mult...) is defined with `MERGE_OPERATION`
2. based on a switch, alpha can be kept or reset to 1.0 for make the texture fully opaque: `gl_FragColor.a = transparent ? gl_FragColor.a : 1.0;`

The layers are defined by arrays of attributes, `TEXTURES_ARRAY_SIZE` being the number of layers:
``` glsl
uniform sampler2D layersTexture[TEXTURES_ARRAY_SIZE];
uniform int layersMergeOp[TEXTURES_ARRAY_SIZE];
uniform bool layersTransparent[TEXTURES_ARRAY_SIZE];
```

``` glsl
for (int layerIndex = 0 ; i < TEXTURES_ARRAY_SIZE ; ++i) {
    // gl_FragColor = compositeLayer(gl_FragColor, layerIndex);
}
```

In the jsfiddle sample the shaders have been simplified to composite only two procedurally defined colors (the base color and the first and only layer): we don't pass actual textures, so layersTexture does not exist. However:
- `layersMergeOp` is `[0]`, `0` being the `mergeOver` operation code
- `layersTransparent` is `[true]`, so we keep all transparency

##### Issue on iOS

This shader works fine on evey platform we've tried so far, Windows, macOS, Linux, Android on a range of browsers, but on iOS the edges are flickering. The problems seems to be related to alpha and antialiasing : after turning antialiasing off the edges are not flickering anymore.

Here are several options we are exploring that have an impact on the iOS edges flickering:
- FIX 1: hardcoding the merge operation code or the transparent layer property lookup
``` js
// int mergeOp = layersMergeOp[i];
int mergeOp = 0;
```
or
```
// bool transparent = layersTransparent[i];
int transparent = true;
```

- FIX 2: forcing the merge operation type prevents the operation type switch in `merge`, bypassing the `layersMergeOp[i]` lookup
```
// gl_FragColor = merge(gl_FragColor, color2, mergeOp);
gl_FragColor = mergeOver(gl_FragColor, color2);
```

- FIX 3: boundary checking the merge operation code to ensure that it matches an operation in the `merge` switch and forcing a static color for the fragment:
```
if (mergeOp < 0 || mergeOp > 2) {
    gl_FragColor = vec4(0.0, 0.0, 0.0, 0.0);
    return;
}
```

None of thoses fix make sense to me : it is as if looking values in the uniform arrays would return invalid values for the fragments computed for antialiasing purpose along the edges...

Is there something obvious I'm missing here ? An iOS limitation that I'm not yet aware off ?

Many thanks !

##### Three.js version

- [x] r86

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

- iPad Air 2 iOS 10.3.2
- Recent iPhone

**Comment by mrdoob** [comment]
May or may not be the case but... iOS drivers do not like dynamic accessing arrays.

Have you tried something like this?

```glsl
#define MERGE_OP 1

vec4 merge(vec4 bg, vec4 fg, int operation) {
#if MERGE_OP === 0
    return mergeOver(bg, fg);
#elif MERGE_OP === 1
    return mergeAdd(bg, fg);
#elif MERGE_OP === 2
    return mergeMult(bg, fg);
#else
  return bg;
#endif
}
```

**Comment by charlesfleche** [comment]
The merge operations are dynamically driven by the values in the layersMergeOp array. In the real shader (not the stripped down JS fiddle example), it works like this:
```
                Layer 1    Layer 2    Layer 3    Layer 4    ... Layer n
Texture         background lighten    foregound  decal      ...
Merge operation Over       Add        Over       Over       ...

```

Textures are in `uniform sampler2D layersTexture[TEXTURES_ARRAY_SIZE];`, merge operations in `uniform int layersMergeOp[TEXTURES_ARRAY_SIZE];`

So I need all operations to be defined in the shader as they are specified at run time for each layer.

What about this dynamic array lookup issue on iOS ? Do you know more about this ? Is there a bug entry at Apple about it ?

**Comment by mrdoob** [comment]
Even if my suggested approach is not feasible for this case, it would be good to know if it solves the issue you're seeing.

**Comment by Mugen87** [comment]
Closing. If this is still an issue, let's continue the discussion at the [forum](https://discourse.threejs.org/).
