### ISSUE TITLE
Serverside STLLoader - TypeError: Cannot read property 'target' of undefined

### ISSUE THREAD

**Issue by Manidavid** [mrdoob/three.js#11858]
### Description
Server side API for 3D STL file processing with node.js express framework + Three.js. 

I want to load STL file from amazon s3 url and parse its attributes like size and color from three.js server side api and return success json response.

installed the **three** node module using ` npm install three --save`.

converted `https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/STLLoader.js` this file into node module and its accessing from here **/lib/stl-loader.js** 

when i run my code it raised the below error,

my controller js file.
```
exports.stlmodel_create = function(req, res) {
    var THREE = require('three');
    var STLLoader = require('../lib/stl-loader')(THREE);

    var loader = new THREE.STLLoader();
    console.log(loader);

    var material = new THREE.MeshPhongMaterial( { color: 0xAAAAAA, specular: 0x111111, shininess: 200 } );
    console.log('callback');
    loader.load('./public/stlmodels/frame.stl', function ( geometry ) {
        console.log(geometry);
        var mesh = new THREE.Mesh( geometry, material );
        scene.add( mesh );
    } );
};
```

> `ReferenceError: XMLHttpRequest is not defined`
>     at FileLoader.load (\web-api\node_modules\three\build\**three.js:29860:23**)
>     at load (\web-api\node_modules\three-stl-loader\index.js:50:13)
>     at exports.stlmodel_create (\web-api\controllers\stlmodelController.js:10:10)

i found that **XMLHttpRequest node moude** also missed so i run ` npm install xmlhttprequest --save` to install and required this module with the below code.

my STL files are located in **/public/stlmodels/**  directory path

```
exports.stlmodel_create = function(req, res) {
    global.XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
    var THREE = require('three');
    var STLLoader = require('../lib/stl-loader')(THREE);

    var loader = new THREE.STLLoader();
    console.log(loader);

    var material = new THREE.MeshPhongMaterial( { color: 0xAAAAAA, specular: 0x111111, shininess: 200 } );
    console.log('callback');
    loader.load('./public/stlmodels/frame.stl', function ( geometry ) {
        console.log(geometry);
        var mesh = new THREE.Mesh( geometry, material );
        scene.add( mesh );
    } );

    res.send('NOT IMPLEMENTED: 3d model create POST');
};
```

It couldn't make the geometry object but got error saying  `TypeError: Cannot read property 'target' of undefined` , which i could not able to find any solution.

> C:\Users\Documents\GitHub\3d-web-api\node_modules\three\build\three.js:2986
> 5
>   `var response = event.target.response;`
>                                                             ^
> 
> TypeError: Cannot read property 'target' of undefined
>     at .<anonymous> (\web-api\node_modules\thre
> e\build\three.js:29865:26)
>     at dispatchEvent ((\web-api\node_modules\xml
> httprequest\lib\XMLHttpRequest.js:595:29)
>     at setState (\web-api\node_modules\xmlhttpr
> equest\lib\XMLHttpRequest.js:614:14)
>     at IncomingMessage.<anonymous> (\web-api\no
> de_modules\xmlhttprequest\lib\XMLHttpRequest.js:447:13)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

**`please note that i want to access the STL file from the Amazon s3 bucket URL('https://s3.amazonaws.com/minifactory-stl/WALLY_1plate.stl'). not from local directory` **

Please help me with this issue.

**Comment by mrballer** [comment]
Any progress here? I have a similar issue. I need to load stl files into three js.

**Comment by yomboprime** [comment]
Please use the forum for help: https://discourse.threejs.org
