### ISSUE TITLE
Request For Ability to Pan Sounds

### ISSUE THREAD

**Issue by smellyRose** [mrdoob/three.js#11854]
Would love the ability to pan sounds. Thanks in advance!

**Comment by Mugen87** [comment]
Does [PositionalAudio](https://threejs.org/docs/index.html#api/audio/PositionalAudio) work for you? There is also an example: https://threejs.org/examples/#misc_sound

**Comment by smellyRose** [comment]
It might work- I was looking for something a little simpler.. just want the ability to pan individual sounds in a 2D setting.

**Comment by Mugen87** [comment]
That's the minimal setup for 3D spatial audio. And also for 2D. You definitely have to use WebAudio in order to implement this feature.

See https://stackoverflow.com/questions/11177791/spatial-2d-sound-in-javascript

**Comment by smellyRose** [comment]
Got it- thanks!
