### ISSUE TITLE
Exported light angle doesn't match with Blender

### ISSUE THREAD

**Issue by warekurt** [mrdoob/three.js#11869]
I formed a scene with a plane and spot light with size=20. The value in radians match the one in exported json file so I guess the exporter works correctly here. (Except the distance value is hard coded to zero but I already found about it.)

Then there's the threejs render result at the bottom. (Added a weak Ambient Light as well) The size of the illuminated circle is larger than the one in Blender, about double in radius.

Any idea why this is happening? Is this some kind of bug, is it threejs interpreting larger or Blender interpreting narrower?

![light-angle-issue](https://user-images.githubusercontent.com/30603901/28793314-49d85d90-763b-11e7-8c39-669bd12156b2.png)

- [x ] r86
- [x ] Firefox
- [x ] Windows

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
