### ISSUE TITLE
Repeated texture with normal texture issue

### ISSUE THREAD

**Issue by jack-jun** [mrdoob/three.js#11872]
##### Description of the problem 
I use a texture and a normal texture to render a mesh, they work perfectly as the first screenshot. If the texture is set to repeat 2 on both direction, the normal texture is not repeated, and the mesh becomes strange...(the second screenshot).

Is there a way to use repeated texture with a non-repeated normal texture?
Thanks a lot. :) 

<img width="691" alt="wx20170802-150502 2x" src="https://user-images.githubusercontent.com/5774080/28862012-0bd37c94-7796-11e7-8750-a2e7bd0b8922.png">
<img width="729" alt="wx20170802-150446 2x" src="https://user-images.githubusercontent.com/5774080/28862027-1cf3f8d2-7796-11e7-9fd7-0980ef339e0d.png">

##### Three.js version

- [ ] Dev
- [x] r84
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
You have to configure the repeat on both textures, diffuse and normal. Are you actually doing this?

**Comment by jack-jun** [comment]
@Mugen87 Thanks for your reply, but I want the normal not repeated...

**Comment by WestLangley** [comment]
https://stackoverflow.com/questions/14371385/can-a-three-js-material-have-separate-repeat-values-for-a-bump-map-and-a-texture

**Comment by jack-jun** [comment]
@WestLangley thank you, i understand.
