### ISSUE TITLE
depth on traverse

### ISSUE THREAD

**Issue by sjpt** [mrdoob/three.js#11874]
##### minor suggestion, add depth to callbacks in traverse, traverseVisible, traverseAncestors

This would be an optional extra second parameter to the function (default 0),
passed to the callback, and incremented to the recursive calls.

It should be upward compatible with current version; easy to implement and helpful e.g. for quick debugging (which is why I wanted it)

##### Three.js version

- [ ] Dev
- [ ] r85
- [x ]all.

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Any use cases?

**Comment by WestLangley** [comment]
>It should be ... helpful e.g. for quick debugging (which is why I wanted it)

@sjpt You want this for debugging? You may find snippets in #10961 and #10995 of interest.

**Comment by sjpt** [comment]
@WestLangley Thanks, yes, useful snippets.
It is simple to generate these, but for debug you often want to write one-liners on the Developer Tools console (or at least I do).  Thus ...

@mrdoob Simple use case similar to #10961 but tailored to a specific debug situation:
scene.traverse( (x,n)=>{ console.log('    '.repeat(n), x.name, x.scale); if (n) x.matrix.scale( {x:1, y:1, z:1 } ) } );

(I always name my objects for debugging help, and in this case I wanted to check out what I had done to make some scales go silly.)

~~~
		traverse: function ( callback, n = 0 ) 
			callback( this, n );
			var children = this.children;
			for ( var i = 0, l = children.length; i < l; i ++ ) {
				children[ i ].traverse( callback, n+1 );
			}
		}

**Comment by Mugen87** [comment]
I'm not a fan of such changes. I would prefer to keep the methods as lean and simple as possible and rather use an external inspector tool for debugging purposes (see https://github.com/mrdoob/three.js/issues/10961#issuecomment-292193243)

**Comment by sjpt** [comment]
@Mugen87  The [three.js inspector](https://chrome.google.com/webstore/detail/threejs-inspector/dnhjfclbfhcbcdfpjaeacomhbdfjbebi?hl=en) Chrome extension look useful.  An interactive debugging tool like that is a slower way to check when you are looking for something specific, however,

Leanness is clearly desirable if not so lean as to be mean.  The traverse function is so trivial either way, and the alternatives are pretty straightforward too, so I am happy to close this.  Meanwhile, I've found out a lot more about console capabilities from following up on the thread that @WestLangley and you referenced; that's going to be really handy in future;  thank you
