### ISSUE TITLE
Unable to render dashed lines via SVG renderer

### ISSUE THREAD

**Issue by proteamer** [mrdoob/three.js#11879]
The issue appeared after  6a7d28773719e7ee9e59e4f68bf884856bab2e08. There are [lines of code](https://github.com/mrdoob/three.js/blob/dev/examples/js/renderers/SVGRenderer.js#L381-L393) which setup SVG lines depending on the `material.isLineBasicMaterial` and `material.isLineDashedMaterial` properties. But now if you create `LineDashedMaterial`, material properties `isLineBasicMaterial` and `isLineDashedMaterial` will be `true` so we never get SVG dashed lines.

##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Try switching the order of those 2 [`if-statements`](https://github.com/mrdoob/three.js/blob/dev/examples/js/renderers/SVGRenderer.js#L381-L393).
