### ISSUE TITLE
Animation exported from blender changes pivot point

### ISSUE THREAD

**Issue by roccapl** [mrdoob/three.js#11878]
##### Description of the problem 

A Skinned Animation exported from r86 blender exporter, in which a bone is rotated around its origin and moves a geometry is not exported properly.

![blender](https://user-images.githubusercontent.com/23173365/28917786-265f757a-7847-11e7-83c0-a43f35d70bdd.png)

The result in three is that the animation uses the world origin (or the object center, I cannot determine since they coincide once you apply rotation and location) as pivot point.

![three](https://user-images.githubusercontent.com/23173365/28917776-1f819d78-7847-11e7-9395-b0bd73e61138.png)

I prepared a simple project to demonstrate the issue
[test_three_anim_pivot.zip](https://github.com/mrdoob/three.js/files/1196839/test_three_anim_pivot.zip)

in the zip there is also the source blender file.

##### Three.js version

- [ ] Dev
- [X] r86

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
