### ISSUE TITLE
LineSegments issue in Orthographic projection

### ISSUE THREAD

**Issue by freesunwaywei** [mrdoob/three.js#11882]
When using three.js 0.86 EdgeGeometry and LineSegments to process Revit models and draw wall boundaries, if the two walls intersect, the lines are projected incorrectly under the orthographic projection, which can be done by perspective projection.

See: http://liuguixue.com/media/3d.png

**Comment by WestLangley** [comment]
Can you please provide a live example demonstrating that it renders correctly with a perspective camera, but not with an orthographic one?

**Comment by guixue** [comment]
@WestLangley I met  the same issue with author.
Please refer to :
 * [live example code](https://jsfiddle.net/guixue/egf7duw8/4/)
 * We expect the vertical lines(in the corner)  can be show.


![image](https://user-images.githubusercontent.com/691782/29031126-c3d750cc-7bbf-11e7-9da5-a7eedec8cc23.png)

**Comment by WestLangley** [comment]
You are seeing symptoms of z-fighting. See [this StackOverflow post](https://stackoverflow.com/questions/31539130/display-wireframe-and-solid-color/31541369#31541369).

**Comment by freesunwaywei** [comment]
Thanks a lot!
