### ISSUE TITLE
THREE.Mirror reflected lights are not correct. 

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#11885]
As you can see in this [example](https://codepen.io/looeee/pen/ZJBQPQ?editors=0010) the highlights of the object reflected in the mirror plane don't match up with the highlights on the object. 

![untitled-1](https://user-images.githubusercontent.com/5307958/28952298-6d0a692c-78fa-11e7-91f7-c3e13e322905.jpg)

##### Three.js version

- [ x ] Dev
- [ ] r85
- [ ] ...

**Comment by WestLangley** [comment]
I don't think there is any reason why they should.

![screen shot 2017-08-04 at 12 03 07 am](https://user-images.githubusercontent.com/1000017/28953779-7df6de52-78a8-11e7-9c72-af0853d515ef.png)

**Comment by RemusMar** [comment]
> As you can see in this example the highlights of the object reflected in the mirror plane don't match up with the highlights on the object.

Remove the "keyLight" and use the Phong material.

**Comment by looeee** [comment]
@WestLangley I'm going to sit down with a mirror and check this out to convince myself for sure - but I don't think highlight would cut off like the one in my image in the real world. When the object is actually touching the mirror, I would expect the highlight to be continuous from the mirror to the object.

**Comment by makc** [comment]
yep, in spheres example the surfaces of real and reflected spheres are at an 'angle' to each other, in case of the column there is no angle, and reflected surface is a continuation of real one.

**Comment by mrdoob** [comment]
Changed the lights colors for clarity.

https://codepen.io/anon/pen/XazVmd

<img width="863" alt="screen shot 2017-08-15 at 7 04 26 pm" src="https://user-images.githubusercontent.com/97088/29344423-a1a58162-81ec-11e7-85b8-2815e9a6eeee.png">

The blue light couldn't happen because the mirror would be occluding it (casting a shadow).

The green one... I don't know...

**Comment by WestLangley** [comment]
RIght. You can't draw inferences about the correctness of a model if your example is not physically possible.

**Comment by RemusMar** [comment]
> Changed the lights colors for clarity.
> https://codepen.io/anon/pen/XazVmd 

Again: use the Phong material
You'll get much better results.

**Comment by RemusMar** [comment]
To close this subject:
https://threejs.org/examples/webgl_mirror.html 
With Phong materials, Point lights and a decent setup, the Mirror reflected lights are correct.
cheers

**Comment by looeee** [comment]
@RemusMar using Phong material instead of PBR is a workaround, not a fix.

**Comment by RemusMar** [comment]
> using Phong material instead of PBR is a workaround, not a fix.

The Phong material is a solution.

**Comment by makc** [comment]
@RemusMar nope, same shit:
![screen shot 2017-08-16 at 13 08 44](https://user-images.githubusercontent.com/242577/29360631-1f55f924-8284-11e7-9a29-a88f2e835583.png)

maybe it is, indeed, correct? in the mirror, you see the object as if you would from below. if you rotate the scene to look up, there is same green spot you see in the mirror:

![screen shot 2017-08-16 at 13 10 50](https://user-images.githubusercontent.com/242577/29360685-65ba7674-8284-11e7-8082-4b09093ade83.png)

**Comment by looeee** [comment]
OK, I've spent quite a while looking at this and my conclusion is: 

I have no absolutely no freaking idea anymore 😆

I'm going to leave this open, but if other people think it should be closed that's fine (apologies to the client who brought this to my attention, I tried!).

**Comment by RemusMar** [comment]
>  same shit

For this scene setup ...
As I said before, with Phong materials, Point lights and a decent setup, the Mirror reflected lights are correct.
Example: https://threejs.org/examples/webgl_mirror.html

**Comment by RemusMar** [comment]
> As I said before, with Phong materials, Point lights and a decent setup, the Mirror reflected lights are correct.
> Example: https://threejs.org/examples/webgl_mirror.html 

Even more: if you replace in that example the Phong with Standard material you will get WRONG highliths and WRONG  mirror reflected lights.
So the Standard material is not properly implemented.

**Comment by RemusMar** [comment]
In this setup I get perfect results for both materials:
http://necromanthus.com/Test/html5/Lara_mirror.html 
Click on stage to switch between the Phong and Standard materials:

**Comment by makc** [comment]
@RemusMar we are all happy you have perfect results in that setup, but it's a bit like saying other people do not starve because I am not hungry - this issue was not about that setup )

**Comment by jchen10** [comment]
I feel this is indeed right. The highlight area on an object is specific to the direction of incoming lights and the position of observer's eyes. Given the lights and object are both fixed, the highlight area position changes on the surface of object as the observer moves. Regarding highlight area reflected in mirror, we can simply imagine the observer just walked inside opposite side of mirror to observe. So the highlight area in mirror is different from real world. This seems a bit anti-intuitive. But you can actually verify it by taking something before a mirror.

**Comment by WestLangley** [comment]
There is no bug demonstrated here. You need to create a physically-possible example to demonstrate a bug -- and that includes not having light sources emanating from behind the mirror. It also helps to avoid lights that are over-bright.
