### ISSUE TITLE
Maya export plugin does not work "Error line1"

### ISSUE THREAD

**Issue by SonnyAngell** [mrdoob/three.js#11888]
I have copied the plugin and script files into the appropriate folders, scoured the internet to make sure I am putting them in the right place.. and I still get this error when I try to activate the exporter
"// Error: line 1: invalid syntax // 
// Warning: line 1: Failed to run file: C:/Program Files/Autodesk/Maya2016/bin/plug-ins/threeJsFileTranslator.py // 
// Error: line 1:  (threeJsFileTranslator) // "

The python file is where it is supposed to be as well as the script file...

what do I do?

-Sonny

- [ ] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by jamesgk** [comment]
By "where it is supposed to be", do you mean that threeJsFileTranslator.py is in
`C:\Users\[username]\Documents\maya\[maya-version]\plug-ins\`?

**Comment by SonnyAngell** [comment]
Yes, they act like every other normal script / plugin combination. but the python script does not execute and I cannot export anything - I get the syntax error

**Comment by jamesgk** [comment]
Huh, it's strange that the error message lists "C:/Program
Files/Autodesk/Maya2016/bin/plug-ins/threeJsFileTranslator.py". If you
have that file on your computer, try deleting it and reloading the
plugin.

**Comment by SonnyAngell** [comment]
Ok, ill try that again but.. ive done that a few times..

maybe this system im working on is just a voodoo devil portal.... ive been having other really specific and weird issues with other software's

**Comment by jamesgk** [comment]
Alright. Be sure to also remove `C:/Program
Files/Autodesk/Maya2016/bin/scripts/ThreeJsExportScript.mel` if it exists.

**Comment by Mugen87** [comment]
Closing since this issue seems to be solved.
