### ISSUE TITLE
Changing material brokes SkinnedMesh connection to bones

### ISSUE THREAD

**Issue by postolka** [mrdoob/three.js#11887]
##### Description of the problem 
Changing material on SkinnedMesh causes loss of bone influence to its vertices.
When loaded (from Blender exporter) with material, bones works properly an changing bone positions changes mesh geometry:
![image](https://user-images.githubusercontent.com/1336305/28967733-d2a36eb0-791c-11e7-90a0-3015e1511d5c.png)
(shape width is changed via input button, which sets it's desired width)
Changing material causes geometry to reset to original value (as without bones) and changing bone position has no influence to skinned mesh anymore:
![image](https://user-images.githubusercontent.com/1336305/28967801-26e92050-791d-11e7-9a7e-d2833d2947c9.png)
Screenshot from Blender for better understanding how shape changing works:
![image](https://user-images.githubusercontent.com/1336305/28967880-9d0b1414-791d-11e7-9c0d-cd3286d9cef1.png)
I guess this issue is not related to Blender exported, as bones work correctly before material change. 
Additional info:
- changing material *property* (i.e. color) works
- changing material on single object also resets deformation on other objects (which kept their original/imported) - afterwards deformation works, but it is *shifted* - bones are kept at its original position, but reseting mesh shape seems to cause re-attaching vertexes at their "reset" state to shifted bone (instead of keeping same offset for bone and attached vertexes).

##### Three.js version
- [x] r86
- [x] r87
- [x] r88

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them (probably)
- [x] Windows (tested)
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by makc** [comment]
> changing material property (i.e. color) works

it does not if you add the map that was not there

**Comment by postolka** [comment]
Is there any plan to fix this issue?
Where to look to fix the problem?

**Comment by WestLangley** [comment]
Sorry, this post did not contain sufficient information for us to respond.
