### ISSUE TITLE
MTLLoader has error handling problem

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#11899]
not sure I can do a demo of this on jsfidde, but basic idea is this: I had MTL file with bad paths in it, and I used THREE.LoadingManager to wait for everything to load. so the loading setup looked like this:
```javascript
	var manager = new THREE.LoadingManager;
	manager.itemError = manager.itemEnd;
	manager.onProgress = function (url, itemsLoaded, itemsTotal) {
		// show progress bar or whatever
	};
	manager.onLoad = function () {
		// yay!
		render ();
	};

	var mtlLoader = new THREE.MTLLoader( manager );
	mtlLoader.setPath( 'models/' );
	mtlLoader.load( 'my.mtl', function( materials ) {
		materials.preload();
```
when I load textures manually and for some reason it's missing, the manager would still wait for the rest of stuff and then complete, but with MTLLoader it just completes right away, not waiting for anything.

I thought maybe the manager just runs out of stuff to wait for, and did this:
```javascript
	manager.itemStart ('dummy.jpg');

	var mtlLoader = new THREE.MTLLoader( manager );
	mtlLoader.setPath( 'models/' );
	mtlLoader.load( 'my.mtl', function( materials ) {
		materials.preload();

		// here I start loading things, and finally call
		// manager.itemEnd ('dummy.jpg'); when they
		// finish loading
```
but it did not help.

I fixed the file names in MTL, and then things worked, but I still think firing completion event upon error when manager has more stuff to load is an issue.

**Comment by Mugen87** [comment]
I've debugged the loading process and found something that's maybe related to this issue.

As you can see in the following example we load an image that does not exist on the server. 

https://jsfiddle.net/953fLxtg/3/

The corresponding `onLoad` callback of `ImageLoader` does not fire which is obviously correct. Instead `onError` is executed. 

The behavior of `LoadingManager` is different. Both callbacks are executed because of these [lines](https://github.com/mrdoob/three.js/blob/dev/src/loaders/ImageLoader.js#L69-L70). The image load fails so `onError` is executed. But the overall `onLoad` is also executed because all items were handled (successfully or not, that doesn't matter in this case).

**Comment by Mugen87** [comment]
Why are you doing this?
`manager.itemError = manager.itemEnd;`

Maybe this leads to the strange behavior?

**Comment by makc** [comment]
@Mugen87 Idk really, that's just copy-paste artifact from the project where we had to display user content. if the user uploads the model without textures it relies on, manager onLoad would never fire unless you do this.

**Comment by Mugen87** [comment]
The problem is that `itemEnd` is effectively called twice in the error case. And that raises the internal [itemsLoaded](https://github.com/mrdoob/three.js/blob/dev/src/loaders/LoadingManager.js#L36) variable in a faulty way. The loading process can't be correct under these circumstances.

**Comment by makc** [comment]
Well if it does not work either way, there is a problem. If I do that, and itemEnd is called twice, and if I dont, load never completes because bad urls in mtl. How am I supposed to handle this?

**Comment by Mugen87** [comment]
Um, i think we need a live demo to debug this. Any chances you can provide a fiddle that shows the problem?

**Comment by makc** [comment]
the fiddle needs cors-enabled file host. any suggestions?

**Comment by Mugen87** [comment]
AWS S3 should do it.

**Comment by Mugen87** [comment]
@makc Any news on this? If you like, i can temporarily deploy the assets for you on one of my S3 buckets.

**Comment by makc** [comment]
I forgot about this :( Now I need to remember what the project was this, to copy the code.

**Comment by makc** [comment]
Ok I have found that but cant seem to reproduce it. So unless it surfaces again, I shall close.
