### ISSUE TITLE
Light bleeding through when near the mesh

### ISSUE THREAD

**Issue by jonarya2** [mrdoob/three.js#11909]
I'm a newbie learning Three.js. I tried to create a physical light using given example.
[physical_lights_example](https://threejs.org/examples/webgl_lights_physical.html).

I modified the example so that box looks like a wall. As seen in below fiddle, when the light is near the box it is bleeding through it.
[light_bleeding](https://jsfiddle.net/jonarya/sap848ao/)

I have raised the issue in stackoverflow before.
[physical-light-go-beyond-wall](https://stackoverflow.com/questions/45499096/three-js-physical-light-go-beyond-wall)

**Comment by makc** [comment]
if you go to https://threejs.org/docs/#api/lights/PointLight it says:

> The lightShadow's camera is set to a PerspectiveCamera with fov of 90, aspect of 1, **near clipping plane at 0.5** and far clipping plane at 500.

so that must be why.

**Comment by WestLangley** [comment]
@makc is correct. See [this SO post](https://stackoverflow.com/a/45594695/1461008) for more info.
