### ISSUE TITLE
CombinedCamera does not have focus

### ISSUE THREAD

**Issue by maartenbreddels** [mrdoob/three.js#11904]
CombinedCamera in combination with StereoCamera will not work since CombinedCamera does not have the focus property, as expected [here](https://github.com/mrdoob/three.js/blob/f83fe541f6aac09e9a94943884f7d698dd55ba32/src/cameras/StereoCamera.js#L45)
It will lead to the projectionMatrix having a NaN, causing nothing to render.

**Comment by Mugen87** [comment]
As mentioned [here](https://github.com/mrdoob/three.js/blob/dev/examples/js/cameras/CombinedCamera.js#L4-L7), `CombinedCamera`  is...

_A general perpose camera for setting FOV, Lens Focal Length and switching between perspective and orthographic views easily. Use this only if you do not wish to manage both a Orthographic and Perspective Camera._

So just adding a new property is not sufficient. When i look at the code, it seems like `CombinedCamera`  is not designed to support `StereoCamera` at all. There are methods like `.toPerspective()` or `.toOrthographic()` but no `.toStereo()`. Other existing methods also need to be revisited in this context. Besides, an enhancement of this example is necessary (it uses `CombinedCamera`).

https://threejs.org/examples/#canvas_camera_orthographic2

@mrdoob I'm not sure in general if it makes sense to enhance `CombinedCamera` in this way. Maybe it's better if `CombinedCamera` just focuses on `OrthographicCamera` and `PerspectiveCamera`.

**Comment by mrdoob** [comment]
I actually am not a big fan of `CombinedCamera`. I'm always looking for excuse to remove it 😇

**Comment by mrdoob** [comment]
Like... how about doing something like `perspectiveCamera.toOrthographicCamera()` and orthographicCamera.toPerspetiveCamera()`?

Or... Make `copy()` handle both cameras?

**Comment by WestLangley** [comment]
I suppose you could remove `CombinedCamera` and add:
```javascript
OrthographicCamera.setFromPerspective( camera )
PerspectiveCamera.setFromOrthographic( camera )
```
Thing is, if you look at http://threejs.org/examples/canvas_camera_orthographic2.html, switching between the two camera types does not appear to do anything that makes sense -- at least to me.

**Comment by Mugen87** [comment]
I vote for `. setFromPerspective()` and `. setFromOrthographic()`.

**Comment by Mugen87** [comment]
From https://github.com/mrdoob/three.js/pull/12171#issuecomment-328646697

> However, I am not sure there is an intuitive way to compute the parameters of one camera type from the other. Consequently, I am not sure the methods even make sense. If fact, I am pretty sure they don't.

I've investigated this issue today and found no reference implementation for converting one camera type exclusively from the parameters of the other. So it seems like you can't do this in a generic way and therefore methods like `.setFromPerspective()` and `.setFromOrthographic()` make obviously no sense.

**Comment by WestLangley** [comment]
Well, it could be done given additional information: Identify the subset of scene vertices that are visible in the current frustum, then set the frustum of the other camera type to be sized to contain the same subset of vertices -- while maintaining the current aspect ratio, near and far planes, camera orientation and camera position.

I don't think it is worth it.

**Comment by Mugen87** [comment]
Interesting! Do you know any readings about this approach. Just so out of curiosity...

**Comment by WestLangley** [comment]
I do not.

**Comment by mrdoob** [comment]
`CombinedCamera` has been removed.

**Comment by openbuilds-engineer** [comment]
(: was investigating this today, need to implement a viewer where the user must be able to switch between perspective and parallel projection in realtime (CAD viewer).

Was CombinedCamera replaced with .setFromPerspective() and .setFromOrthographic(). ? Or just dropped entirely?

**Comment by Mugen87** [comment]
`CombinedCamera` was removed and not replaced with the mentioned methods.

**Comment by mrdoob** [comment]
I think it could be interesting to explore options to do the `setFromPerspective()` and `setFromOrthographic()`. 

I think we can use `THREE.CameraHelper` as reference: https://threejs.org/examples/webgl_camera.html

We know the 4 vertices of the near and far planes, I think it should be possible to create both matrices with that?

We should create a new issue for this, but for now I'm adding this to the rXX milestone so I don't forget.

**Comment by openbuilds-engineer** [comment]
Sweeeet (: will wait for this
