### ISSUE TITLE
AssimpLoader issues

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#11908]
Two things here:
1 it does not use loading manager
2 it says 'shortened binaries not supported', but I think assimp (now ?) does that by default when I do `assimp export my.file to.assbin` or `assimp export my.file to.assimp` - how should I create non-shortened file?

(#10255 @Virtulous )

**Comment by Mugen87** [comment]
We have a PR that solves your first point. I can't help you with the second question? What does `shortened binaries` actually mean in context of Assimp?

**Comment by makc** [comment]
Assimp has a bunch of code like
```
if (shortened) {
    // write one thing
} else {
    // write another thing
}
```
in their exporter, but I have no idea how to control that setting. [Asking them now](https://github.com/assimp/assimp/issues/1377).

**Comment by rchadwic** [comment]
I'll take a look for changes to the defaults. If we do really need to support the shortened format, that might take a few days. Not sure yet.

**Comment by rchadwic** [comment]
It seems like the "shortened" feature is some sort of a hash or integrity check or something. I can't understand how that feature could ever result in an actual model. I just writes the min and max values of the buffer. Are we 100% sure this is default export?

**Comment by makc** [comment]
I am getting this message from AssimpLoader, that's as far as I am sure. There could be all sorts of explanations here. Like if the loader reads values from wrong offset (say, because file structure changed).

**Comment by rchadwic** [comment]
Ah, found it. The inclusion of the metadata causes the read to offset incorrectly. 
https://github.com/assimp/assimp/commit/6c6a8fe671b927bf7ff37157436e803931b8ca68

I think I can handle this. Can you email your test file?

**Comment by makc** [comment]
Try this one:
[spider.fbx.assbin.zip](https://github.com/mrdoob/three.js/files/1212642/spider.fbx.assbin.zip)

**Comment by rchadwic** [comment]
Ok, good news and bad news. First, adding the parsing logic for the metadata fields did cause the file to parse correctly. However, the major and minor version values in the file header report 1.0. That really should be 4.0 or 4.1 or something. If the reporting of the file version is wrong, then the loader does not know which format to expect. How did you generate that file?

**Comment by makc** [comment]
I have built assimp from current master and used the command from the post above. Building assimp from e66dc5c (the one before metadata addition) does solve the problem, but I still cant display anything (well, that one problem might be on my side now).

**Comment by rchadwic** [comment]
![image](https://user-images.githubusercontent.com/1257870/29230974-501c1306-7eb3-11e7-9f51-f7fa58b30be6.png)

I didn't have any trouble viewing the model once I added the metadata code. There are missing maps, so maybe that's the issue. It's also huge, and comes in large enough that the default camera.far might be hiding it from you. 

But anyway, what's to be done about Assimp 4? If it were to report the major version properly, this would not be a problem.

**Comment by makc** [comment]
> what's to be done about Assimp 4?

idk, if you believe the data is incorrect, you need to open an issue with them?
