### ISSUE TITLE
Geometry without faces is still rendered in Mesh

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#11900]
The idea is that my Geometry always has same vertices, but faces are added optionally. However, it randomly decides to draw stuff regardless. Demo [here](https://jsfiddle.net/hfj7gm6t/4453/).

**Comment by makc** [comment]
An opposite issue [here](https://jsfiddle.net/hfj7gm6t/4454/) - we don't see faces where they are defined. So maybe this is because Geometry is shared between the Line and Mesh.

**Comment by Mugen87** [comment]
I've debugged this issue today. `Geometry` is internally converted to `BufferGeometry`. The outcome of this conversion depends on the type of object (Mesh, Line, etc.).

https://github.com/mrdoob/three.js/blob/ec67749b0767e2727deebd52da2dbd3a4e7ab6a2/src/renderers/webgl/WebGLGeometries.js#L77

So in @makc example, the geometry is converted as the geometry of a `Line` object. This will create a position and color attribute. When the instance of `Mesh` is rendered with the same `Geometry` object, the renderer returns the same cached instance of `BufferGeometry`.

https://github.com/mrdoob/three.js/blob/ec67749b0767e2727deebd52da2dbd3a4e7ab6a2/src/renderers/webgl/WebGLGeometries.js#L63-L65

This is the reason why you see these green triangles in the demo. `Mesh` and `Line` share the same `BufferGeometry` and interpret it differently. I think we can solve this problem if we try to respect the type of object when caching the `BufferGeometry`.

Or we just recommend to use `BufferGeometry` in the first place.

**Comment by Mugen87** [comment]
@mrdoob I suggest to introduce a new label `Wont't fix`, assign it to the issue and close it. I don't think it makes sense to add a fix to the renderer if the project is going to stop rendering `Geometry` anyway. The solution for this issue is the usage of `BufferGeometry`.
