### ISSUE TITLE
Multiple elements example on Microsoft browsers

### ISSUE THREAD

**Issue by surepe** [mrdoob/three.js#11916]
Following the title, [Multiple elements example](https://threejs.org/examples/webgl_multiple_elements.html ) (or everything else that is using an array of scenes with scissor)  isn't being rendered correctly while scrolling. Top ones is somehow dynamicly streching, bottoms is loosing their position. Only the top and the bottom sides of the page are affected, middle is always rendering normal.

Tested it on versions down to three r75 and all of them are affected. Not much care about older IE/Edge versions, those two (IE 11 and Edge 15) is enough.

Deffo it's neither hardware nor os specific, happens only in such environment.
Any polyfill or quick workaround will be appreciated, thanks!

**UPD:**
A quick [online test](https://www.browserling.com/browse/win/7/ie/11/https%3A%2F%2Fthreejs.org%2Fexamples%2Fwebgl_multiple_elements.html) for non-windows users or who doesn't have IE 11 / Edge 15. 

IE 11 / W10
![2017-08-10_051947](https://user-images.githubusercontent.com/30002276/29160506-2b605cd2-7dbb-11e7-859a-b3124f2a25bd.png)

Edge 15 / W10
![2017-08-10_052036](https://user-images.githubusercontent.com/30002276/29160507-2b658e64-7dbb-11e7-9bb6-7cdc7945d289.png)

IE 11 / W7
![2017-08-10_105732](https://user-images.githubusercontent.com/30002276/29160509-2b852814-7dbb-11e7-99c6-2829cb190b2e.png)

**Comment by looeee** [comment]
Can confirm. It's actually quite a cool effect though, and even though we should figure out why it's happening I vote that we leave it 😆

**Comment by surepe** [comment]
Not a three.js bug, this is just how Microsoft handles WebGL in 2017. 
It's [all the same behavoir](https://www.browserling.com/browse/win/7/ie/11/http%3A%2F%2Ftwgljs.org%2Fexamples%2Fitemlist.html) in the @greggman's twgl.
