### ISSUE TITLE
THREE.SpriteCanvasMaterial is not a constructor

### ISSUE THREAD

**Issue by fanxunran** [mrdoob/three.js#11910]
##### Description of the problem 

This form is for three.js bug reports and feature requests only.  
This is NOT a help site. Do not ask help questions here.  
If you need help, please use [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.  
A code snippet, screenshot, and small-test help us understand.

You can edit for small-test.  
http://jsfiddle.net/akmcv7Lh/ (current revision)  
http://jsfiddle.net/hw9rcLL8/ (dev)

##### Three.js version

- [ ] Dev
- [ ] r85
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Have you imported `CanvasRenderer` from `/examples/js/renderers/CanvasRenderer.js`?

**Comment by StevRoger** [comment]
I have imported it and it's still showing errors

**Comment by Mugen87** [comment]
`CanvasRenderer` and all related examples have been removed.
