### ISSUE TITLE
editor fails to load dae

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#11936]
Going collada route because of #11935 I see following error in the editor:
![screen shot 2017-08-12 at 22 57 23](https://user-images.githubusercontent.com/242577/29244166-d2256218-7fb1-11e7-9744-ab3d77e6c6e3.png)

File attached below:
[chibi.dae.zip](https://github.com/mrdoob/three.js/files/1220058/chibi.dae.zip)

**Comment by Mugen87** [comment]
I will have a look at this tomorrow. Thanks for the file so far!

**Comment by Mugen87** [comment]
After a quick look in the `dae` file, i suppose the error occurs because there are no material definitions in the file. If i remember correctly, this case is not considered by `ColladaLoader2` so far.

@makc Can you try to export your model with a material applied on it? (I've not looked in the source code yet but it's a good trial i think)

**Comment by makc** [comment]
@Mugen87 yep, this seems to work, thanks. the bounding box is off, but I can live with that.
![screen shot 2017-08-13 at 0 32 44](https://user-images.githubusercontent.com/242577/29244705-178c1344-7fbf-11e7-9311-9d1af6c46f5a.png)

**Comment by makc** [comment]
jesus christ, editor does not export the bones 😩 how deep is this rabbit hole (it actually exports them as Obj3D-s... useless)

**Comment by Mugen87** [comment]
@makc I've provided a little improvement to `ColladaLoader2`. Even if you apply no materials, `ColladaLoader2` should now load the file with a default material. So there should be no errors anymore and you see your object in the 3D scene.

**Comment by Mugen87** [comment]
> jesus christ, editor does not export the bones :weary: how deep is this rabbit hole (it actually exports them as Obj3D-s... useless)

I think the editor does not support skinned meshes so far...
