### ISSUE TITLE
OBJLoader not loading Structure.IO model files

### ISSUE THREAD

**Issue by fanguito-team** [mrdoob/three.js#11933]
##### Description of the problem 

I have the Structure.IO sensor which generates OBJ+MTL models that are correctly loaded into 3D editors (Blender, Cinema4D), but they are not showing in three.js. I've checked the loaded object and it has geometry and material that seems to be correct, but still it shows nothing when I add it to the scene.

Here you have the model I'm trying to use:
http://bit.ly/2fBy2MB

##### Three.js version

- [ ] Dev
- [x] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
https://stackoverflow.com/questions/45653096/objloader-not-loading-structure-io-model-files-in-three-js
