### ISSUE TITLE
FBXLoader loads lights as Object3Ds

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#11949]
Here is a simple light file - just a point light centred at (0,0,0) exported from 3DS Max.

When loading the file with the FBXLoader, it creates an Object3D instead of a light. I've tried exporting every light type from 3ds max, and various versions of both binary and ascii format, all with the same result. 

[just_a_light.zip](https://github.com/mrdoob/three.js/files/1224102/just_a_light.zip)

**Comment by norangit** [comment]
so does that mean three.js do not support any light from exported model from 3DS Max by using FBXLoader?

**Comment by looeee** [comment]
Closed via #12254
