### ISSUE TITLE
extra render call needed for skin to appear

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#11940]
basically everything else appears on 1st render(), and skin only appears on 2nd. if I do one extra render() in dae onLoad, the problem goes away.

**Comment by cl4ws0n** [comment]
I'm having the same issue, not using dae either

**Comment by mrdoob** [comment]
@makc could you share a link?

**Comment by mrdoob** [comment]
Are you talking about `THREE.SkinHelper`...?

**Comment by makc** [comment]
@mrdoob https://jsfiddle.net/hfj7gm6t/4579/

**Comment by makc** [comment]
with r87, the fiddle above now demonstrates correct model placement (forgot to report that bug) but this issue is still not resolved

**Comment by mrdoob** [comment]
Just to clarify. The issue is that `SkinnedMesh` needs 2 renders to appear?

**Comment by makc** [comment]
precisely

**Comment by makc** [comment]
[updated the fiddle to use threejs.org urls](https://jsfiddle.net/hfj7gm6t/4899/) - the problm is still there today

**Comment by Mugen87** [comment]
I've found the bug 🙌 

see https://jsfiddle.net/hfj7gm6t/4902/
