### ISSUE TITLE
lineSegment shader

### ISSUE THREAD

**Issue by MHA15** [mrdoob/three.js#11942]
hi everybody
I'm trying to write a graph visualization with Three.js so I have a bufferGeometry to save my vertexes and I'm using it with my own RawShaderMaterial to make thousands of Three.Points but now I want to know how shader of Three.lineSegments work to change it for my self.
I want to draw my edges with the same bufferGeometry and use two index for heads of the edge.
I had searching too much but I have not found anything?
is it possible? can be added into next release ?
thanks

**Comment by makc** [comment]
use firefox shader editor, just open the demo with line segments and it will show you shader source

**Comment by MHA15** [comment]
thanks. 
but as I sayed I used RawShayderMaterial and I wrote the shayders my own but my problem is according to my searches I should use 
vertexShader:
```
attribute float size;
            attribute vec3 color;
            varying vec3 vColor;

            void main() {
                vColor = color;

                gl_PointSize = size;
                gl_Position =  projectionMatrix * modelViewMatrix *  vec4( position , 1.0 );
            }
```
fragmentShader: 
```
varying vec3 vColor;
            void main() {
                gl_FragColor = vec4( vColor, 1.0 ) ;
            }
```
then in gl_Position  I just can use position not two point for start and end of line
