### ISSUE TITLE
Texture and material loading issue with THREE.OBJLoader2.WWOBJLoader2

### ISSUE THREAD

**Issue by Hari-KrishnanV** [mrdoob/three.js#11954]
I am using three.js to include matterport 3D models (OBJ + MTL format) in my web application. I have tried the web worker based method using THREE.OBJLoader2.WWOBJLoader2, but only one texture is getting applied to the 3D model (The first one). I have tried it using different 3D models, but the result is same. It works perfectly for 3D models with a single texture.

Here is my code

```
reader.addEventListener( 'load', function ( event ) {

    var uint8ArrayNew  = new Uint8Array(event.target.result);
    objBuffer = uint8ArrayNew;

    initPostGL();
    prepData = new THREE.OBJLoader2.WWOBJLoader2.PrepDataArrayBuffer(
        workerInput.obj,    // overall model name
        objBuffer,          // OBJ file as arrayBuffer
        workerInput.path,   // Texture path
        mtlString           // MTL as string
    );

    objectGroup = new THREE.Group();
    objectGroup.name = workerInput.obj;

    prepData.setSceneGraphBaseNode( objectGroup );
    prepData.setStreamMeshes( true );
    wwObjLoader2.setDebug(false);
    wwObjLoader2.prepareRun( prepData );
    wwObjLoader2.run();

}, false );
reader.readAsArrayBuffer( objectAsBuffer );
```
**Here is the link to the OBJ file [:]** https://www.dropbox.com/s/95l3cwv68a0r5hi/SampleObjMtlModel.zip?dl=0

**Screenshot of the output :** 
![frneb](https://user-images.githubusercontent.com/31029848/29311949-2525aa6a-81d1-11e7-9384-1ac0e82f0575.png)

##### Three.js version

- [ ] Dev
- [x ] r86
- [ ] ...

##### Browser

- [] All of them
- [x ] Chrome
- [x ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Fixed #11955

**Comment by Hari-KrishnanV** [comment]
Thanks a lot :)

**Comment by mudin** [comment]
@Hari-KrishnanV do you have any demo link and more source code?
