### ISSUE TITLE
WebGL Mirror Example Artifacts

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#11969]
Artifacts may be reproduced by zooming in and moving the camera a bit.

https://threejs.org/examples/webgl_mirror.html

![screen shot 2017-08-16 at 8 53 26 pm](https://user-images.githubusercontent.com/1000017/29391531-edeed5c6-82c5-11e7-90b9-ba789411986a.png)

##### Three.js version

- [ x ] Dev
- [ x ] r86

##### Browser

- [ x ] Chrome

##### OS

- [ x ] macOS

**Comment by RemusMar** [comment]
Indeed.
Also see this topic: https://github.com/mrdoob/three.js/issues/11885 
At the end I get the feeling the Mirror is not properly implemented.

**Comment by vanruesc** [comment]
The main camera's aspect ratio is never copied to the mirror camera.

```js
// "examples/Mirror.js" (lines 142-146)
mirrorCamera.near = camera.near;
mirrorCamera.far = camera.far;
mirrorCamera.updateMatrixWorld();
mirrorCamera.updateProjectionMatrix();
```

Should be changed to:

```js
mirrorCamera.updateMatrixWorld();
mirrorCamera.projectionMatrix.copy(camera.projectionMatrix);
```

I'll send a PR for this later!

Another problem with the mirror (and the planar ocean) is that it doesn't seem to work when the```logarithmicDepthBuffer``` is enabled. Oblique near plane clipping messes with depth and I never found a solution for this. I wish WebGL had ```glClipPlane``` 😞

**Comment by mrdoob** [comment]
@vanruesc I was messing with the code so I implemented it directly. Many thanks!

**Comment by WestLangley** [comment]
@mrdoob If you are still messing around, I think there is room for simplification...
```
//mirrorCamera.up.set( 0, - 1, 0 );
//mirrorCamera.up.applyMatrix4( rotationMatrix );
//mirrorCamera.up.reflect( normal ).negate();

mirrorCamera.up.set( 0, 1, 0 ).applyMatrix4( rotationMatrix ).reflect( normal );
```
