### ISSUE TITLE
'Export GLTF' menu of Three.js editor does not work

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#11962]
##### Description of the problem 

I tried the 'Export GLTF' menu of Three.js Editor.

https://cdn.rawgit.com/mrdoob/three.js/dev/editor/index.html

[File] - [Export GLTF]

![image](https://user-images.githubusercontent.com/1833979/29347098-efee53ec-8284-11e7-8914-7206442e34e2.png)

However, the following error occurs.

```js
GLTFExporter.js:29 
Uncaught TypeError: Cannot read property 'context' of undefined
    at THREE.GLTFExporter.parse (GLTFExporter.js:29)
    at UI.Row.<anonymous> (Menubar.File.js:188)
```

##### Three.js version

- [x] Dev
- [ ] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

ThinkPad X260 Intel(R) HD Graphics 520

**Comment by takahirox** [comment]
Seems like [`GLTFExporter` instantiation in Menubar.File.js is missing `renderer` argument](https://github.com/mrdoob/three.js/blob/13f2670d10734df3d2166e5ea99c4a702b75d8d1/editor/js/Menubar.File.js#L186)

**Comment by fernandojsg** [comment]
Yep, that parameter was added in the latest update and I forgot to include it on the editor. I'm working on it ;)

**Comment by fernandojsg** [comment]
There you have it https://github.com/mrdoob/three.js/pull/11964
