### ISSUE TITLE
FBXLoader failure

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#11973]
```
TypeError: Cannot read property 'children' of undefined
    at parseMaterial (http://super/3d/js/loaders/FBXLoader.js:434:43)
    at parseMaterials (http://secret/3d/js/loaders/FBXLoader.js:403:20)
    at THREE.FBXLoader.parse (http://web/3d/js/loaders/FBXLoader.js:120:20)
    at http://server/3d/js/loaders/FBXLoader.js:59:23
    at XMLHttpRequest.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/three.js/86/three.js:29871:21)
```

I am trying to find what file was that.

**Comment by makc** [comment]
They say it was [this one](https://www.cgtrader.com/free-3d-models/interior/other/dentist-office).

**Comment by takahirox** [comment]
I don't really wanna sign up that site.
Can you (personally) share the file with us?

**Comment by makc** [comment]
Let's see... looks like I can: [Dentist's office.FBX.zip](https://github.com/mrdoob/three.js/files/1236033/Dentist.s.office.FBX.zip)

**Comment by takahirox** [comment]
Thanks. I confirmed. I'll look into...

**Comment by takahirox** [comment]
I ran into the same error even I converted the file to ascii with Autodesk FBX Converter.
So probably it isn't a binary parser issue.

Seems like missing some `connection` data.
Can the file be loaded with other libs/viewers?

**Comment by makc** [comment]
I asked them if the file may be truncated (as in: broken download). They said:
> I tried the model on the desktop 3D viewer on windows and it opened fine

I tried the same to confirm, and my autodesk viewer does not claim any error:
![screen shot 2017-08-19 at 11 09 00](https://user-images.githubusercontent.com/242577/29485249-f3aec696-84ce-11e7-9865-c1ec1125ef97.png)

**Comment by takahirox** [comment]
OK, I see.

I speculate the file includes unused materials which don't have any connections.
Probably we can ignore them.

Would you please try `FBXLoader` in my branch that I updated?

https://github.com/takahirox/three.js/blob/FixFBXLoader/examples/js/loaders/FBXLoader.js

**Comment by makc** [comment]
Can't test the project atm, but FBXLoader does call onLoad with the file, at the very least.
```javascript
var loader = new THREE.FBXLoader;
loader.load ('Dentist\'s%20office.FBX', function (done) {
	console.log (done);
}, undefined, function (crap) {
	console.log (crap);
});
```

Btw, getting a bunch of warnings here
> THREE.MeshBasicMaterial: 'emissiveIntensity' is not a property of this material.
> THREE.FBXLoader: No implementation given for material type unknown in FBXLoader.js. Defaulting to basic material.

**Comment by looeee** [comment]
These two at least are very common and pretty self explanatory. 

```
No implementation given for material type unknown in FBXLoader.js. Defaulting to basic material

THREE.MeshBasicMaterial: 'emissiveIntensity' is not a property of this material.
```

However given how common this is I think it would be more useful if the default was something other than `MeshBasicMaterial`.

**Comment by looeee** [comment]
By the way I've tried importing this into 3ds max and then re-exporting and it loads 

![dentists-chair](https://user-images.githubusercontent.com/5307958/29488148-0629e02a-852f-11e7-9d61-36589d227c79.jpg)

Both files are the same FBX version (7400), however interestingly the re-export is much larger (44mb vs 22mb) 

I can't attach the re-exported file here as it's too big (it says there's a limit of 10mb, so how did @makc attach the original? 🤔 ).

**Comment by makc** [comment]
@looeee Idk, I just dropped the zip into the input field. maybe you  are emailing it, and it's your email limit?

**Comment by makc** [comment]
@looeee still, I cant get textures on 20 mb model:
![screen shot 2017-08-19 at 18 26 56](https://user-images.githubusercontent.com/242577/29488470-3d8324a0-850c-11e7-8b98-0ac40e60691c.png)

they are loaded but do not show up. was it the same for you before you re-exported?

**Comment by looeee** [comment]
@makc nope, was uploading on github on Chrome. It popped up an error saying I should try again with a file less than 10mb. 

If you want I can share the file with you via Dropbox.

As for loading the original file, I was testing it on my loader [here](www.black thread design.com/experiments/loader). It showed the same errors as you, then spewed a few more errors, something about textures but it crashed my console window before I could copy them.

From memory they were something like

Data64:blablabla..... Couldn't load texture someurl/door-fexture.jpg

**Comment by takahirox** [comment]
About default material, agreed.
I think `MeshStandardMaterial` would be better.

**Comment by makc** [comment]
@takahirox and what about textures? how come they are loaded (network tab says so) but do not make it into materials? is it because the property name is not 'map' (for MeshBasicMaterial) ?

**Comment by takahirox** [comment]
What are the texture names?

**Comment by makc** [comment]
There are too many of them:
![screen shot 2017-08-20 at 1 56 13](https://user-images.githubusercontent.com/242577/29490882-dfb7d386-854a-11e7-9a5d-e35ef7e92eba.png)

it also says this a lot:
![screen shot 2017-08-20 at 1 57 24](https://user-images.githubusercontent.com/242577/29490893-05aecbd0-854b-11e7-8847-b2ae19c54baa.png)

**Comment by takahirox** [comment]
What I wanna know are not image files but texture names like "3dsMax|maps|texmap_reflectionGlossiness"

**Comment by makc** [comment]
those I can only see in warnings, I did not make the file :) there are:
* 3dsMax|maps|texmap_reflection
* 3dsMax|maps|texmap_diffuse
* 3dsMax|maps|texmap_bump
* 3dsMax|maps|texmap_reflectionGlossiness
on repeat, not sure if I missed others

**Comment by makc** [comment]
missed 3dsMax|maps|texmap_refraction

**Comment by takahirox** [comment]
Oops, they aren't texture names but parameters in `connection` that we call relationship. Anyways, they're what I wanted to know, thanks.

[Currently we recognize the valid textures by using perfect match with only some types.](https://github.com/mrdoob/three.js/blob/7ebd51419100bc06ad1478fd67681b992627bfa4/examples/js/loaders/FBXLoader.js#L520-L545)

Probably we'd be better to do partial match with more types.

**Comment by takahirox** [comment]
I've update `FBXLoader` in my branch. Would you please try again?

Not sure how reflectionGlossiness should be handled tho. Is that for roughness?
And I ignore refraction so far.
If I'm right, it'd be for refraction of env map but Three.js doesn't support refractionMap yet.

**Comment by makc** [comment]
> env map but Three.js doesn't support refractionMap

then what do you think are these:

THREE.CubeRefractionMapping
THREE.EquirectangularRefractionMapping

**Comment by takahirox** [comment]
They aren't texture settings.

**Comment by makc** [comment]
[ORLY?](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_materials_cubemap_refraction.html#L87)

**Comment by takahirox** [comment]
Ah, I meant they aren't textures themselves but texture mapping parameters.
I'm not sure how to apply the textures which indicates 'refraction'.

For examples, the bump textures should be set to `material.bumpMap` but where `refraction` textures set to?

**Comment by makc** [comment]
[The answer was in the same demo](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_materials_cubemap_refraction.html#L110-L112) :)

The property names might differ for different materials, check the docs.

**Comment by takahirox** [comment]
Wait, doesn't material have both `reflection` and `refraction` textures?
I set `reflection` texture to envMap but it's for others? (roughness?)

**Comment by makc** [comment]
Now that, I think, 3js does not support ootb. @mrdoob or anyone feel free to correct me.

**Comment by takahirox** [comment]
What's ootb?

**Comment by makc** [comment]
out of the box. of course you can always just write your own shader.

**Comment by takahirox** [comment]
Updated my comments above to clarify.

**Comment by makc** [comment]
> Can you list up what textures each material uses in the FBX file? Like

no, I am not fbx wizard or anything ) I see the same file you do, and have no more information about this file than you have.

**Comment by takahirox** [comment]
Can you open another issue for FBX texture handling enhancement?
I wanna fix the original "loading failure" issue and close this thread for now.
