### ISSUE TITLE
THREE.Editor material tab is broken.. r87

### ISSUE THREAD

**Issue by manthrax** [mrdoob/three.js#11976]
##### Description of the problem 

THREE.Editor material tab is broken.. 
Looks like a problem with my recent multimaterial stuff.. maybe a bad merge...
I'm busy for the next couple weeks, so I might not be able to fix it right away...

But at first glance, it appears that 
SideBar.Material.js:29
Might need to set an initial default value like:
var materialSlotSelect =  new UI.Select().setWidth( '170px' ).setFontSize( '12px' ).onChange( update );
materialSlotSelect.setValue(0);

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by moraxy** [comment]
The HTML/CSS part of the material tab seems fine (i.e. no visual errors for me), but it no longer saves any changes to the entries.    
A quick `git bisect` between `r87` and `r86` points to [49a44b1cc1622dda6923a7380126122ca3be0dba](https://github.com/mrdoob/three.js/commit/49a44b1cc1622dda6923a7380126122ca3be0dba) as the first faulty commit - no idea yet what line in particular though.

**Comment by mrdoob** [comment]
Oks. Should be fixed now.
