### ISSUE TITLE
Editor: Importing the same filename twice fails in Chrome

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#11987]
##### Description of the problem 
Importing the same file (same _filename_ that is) twice doesn't work in Chrome, the console doesn't even show the usual `Loading <filename> (495 KB) 100%`.  
The reason seems to be that the fileInput element's ['change' EventListener](https://github.com/mrdoob/three.js/blob/b344450274513e92c55bdfa5f74c1ce836122a7d/editor/js/Menubar.File.js#L53-L57) doesn't trigger again, because the filename didn't change between events.  
According to [this StackOverflow answer](https://stackoverflow.com/a/12102992) this can be fixed by adding:
```diff
	fileInput.addEventListener( 'change', function ( event ) {
		editor.loader.loadFile( fileInput.files[ 0 ] );
+		fileInput.value = null;
	} );
```
It's kinda weird that Chrome wouldn't support this by default, but I've tested this change with Chrome 60.0.3112.101(Linux) and 60.0.3112.90(Windows 8.1), and it works in both of them. Firefox (55.0.2, Linux) works fine without it, but it doesn't seem to mind it either. Can't test IE or Safari. Also, I haven't checked the editor source too deeply if this breaks something, but so far everything works as normal.  
The closest bug report I could find is #11012, except it's Chrome this time and not IE.  

##### Three.js version

- [x] Dev
- [x] r86
- [x] r87

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Actually, the way we solved it before was using `form.reset()`. #9487

**Comment by mrdoob** [comment]
I never realised this was an issue because I always use drag&drop 😇

**Comment by mrdoob** [comment]
Fixed! Thanks!
