### ISSUE TITLE
Memory leaks when updating textures

### ISSUE THREAD

**Issue by I3ck** [mrdoob/three.js#11988]
##### Description of the problem 

I change the material of a plane via MeshBasicMaterial where map is DataTexture. 
The update has to happen very often, since the texture displays the world at current player location.

I attached a fiddle which reproduces the leak (approximately 2 MB / s), feel free to increase the texture size via width or height. I wanted to keep the leak rather small to not cause issues while reproducing.

http://jsfiddle.net/9r7pyks7/4/ 

It is a minimal copy of my issue which doesn't seem to render correctly. The leak is still there, tho.  
So fixing it here should resolve the issue in my full version.

##### Three.js version
- [x] The one at http://threejs.org/build/three.js  
- [ ] Dev
- [ ] r85
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by calrk** [comment]
In your example, you are recreating the material each frame. If you want to keep doing this, then you should call `map.material.dispose();` on it first, to make sure that it cleans up any resources.

````
dummyDataTex = new THREE.DataTexture( dummyRGBA, width, height, THREE.RGBAFormat );
dummyDataTex.needsUpdate = true;
map.material.dipose();
map.material = new THREE.MeshBasicMaterial( { map: dummyDataTex, side: THREE.FrontSide} )
````

Since the material doesn't change other than the map, a better way would be to just change the map.
```
dummyDataTex = new THREE.DataTexture( dummyRGBA, width, height, THREE.RGBAFormat );
dummyDataTex.needsUpdate = true;
if(map.material.map){
  map.material.map.dispose(); //clean up the previous texture
}
map.material.map = dummyDataTex;
````

Does that help your problem?

**Comment by I3ck** [comment]
I changed it to 
```
    dummyDataTex = new THREE.DataTexture( dummyRGBA, width, height, THREE.RGBAFormat )
    dummyDataTex.needsUpdate = true
    if (map.material.map) {
        map.material.map.dispose()
        map.material.map = dummyDataTex
    } else {
        map.material = new THREE.MeshBasicMaterial( { map: dummyDataTex, side: THREE.FrontSide} )
    }
```
There either is no leak at all now or a tiny one. It must at least be < 1-10% of what previously was leaked.  
So thank you!

**Comment by slahser1992** [comment]
thx!
