### ISSUE TITLE
ExtrudeGeometry's bevel algorithm

### ISSUE THREAD

**Issue by iamnotstone** [mrdoob/three.js#12002]
##### Description of the problem 

A bug for bevel contour algorithm.
The code below
```
function scalePt2( pt, vec, size ) {

     if ( ! vec ) console.error( "THREE.ExtrudeGeometry: vec does not exist" );

     return vec.clone().multiplyScalar( size ).add( pt );

}
```
in `src/geometry/ExtrudeGeometry.js` which is definitely wrong when the center of the contour is not `(0, 0)` .
It's also very easy to test this wrong algorithm. In the example `webgl_geometry_extrude_shapes.html`, you can just change the line 140 from
```
pts.push( new THREE.Vector2 ( Math.cos( a ) * l , Math.sin( a ) * l ) );
```
to
```
pts.push( new THREE.Vector2 ( Math.cos( a ) * l + 3, Math.sin( a ) * l ) );
```
Then, you'll find the red bevel of the 'star' become strange.

##### Three.js version

0.86.0

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
Can you please post a screenshot with the visual error? I'm unable to reproduce.

**Comment by iamnotstone** [comment]
![star](https://user-images.githubusercontent.com/15792984/29575005-cc91e23a-8728-11e7-8bfe-2dba2166ff0d.PNG)

Please take a look at this picture. The red 'star bevel' is not a equilateral star. The angle down side the center is more bigger then the one above the center. To reproduce this ,you can just do this:
in line 140: (the example above was set the offset to 3, may be that is not obvious)

`pts.push( new THREE.Vector2 ( Math.cos( a ) * l + 30, Math.sin( a ) * l) );`

in line 160 to 169:
`
                                var extrudeSettings = {

                                        amount                  : 20,

                                        steps                   : 1,

                                        material                : 1,

                                        extrudeMaterial : 0,

                                        bevelEnabled    : true,

                                        bevelThickness  : 10,

                                        bevelSize       : 40,

                                        bevelSegments   : 1

                                };
`
 This is mostly because the code is just do the multiplyScalar() function for every point of the contour. Below is a sketch for illustrate that.
![sketch](https://user-images.githubusercontent.com/15792984/29575063-fc4c0b2c-8728-11e7-97e5-ad8f946b8b79.png)

**Comment by Mugen87** [comment]
I don't have a ad-hoc solution for this problem because the code obviously assumes that the contour is not translated. Unfortunately, i'm not familiar with this part of `ExtrudeGeometry` so i need to study the implementation first. 

Any help with this issue is highly appreciated 😊

**Comment by iamnotstone** [comment]
I find myself miss understanding something. There should no wrong in this section....This issue should be closed.
