### ISSUE TITLE
Why the distance of the camera is 500, rather than <distance>

### ISSUE THREAD

**Issue by FishOrBear** [mrdoob/three.js#12011]
```
this.shadow = new LightShadow( new PerspectiveCamera( 90, 1, 0.5, 500 ) );
```

I think 
```
this.shadow = new LightShadow( new PerspectiveCamera( 90, 1, 0.5, distance) );
```
will be better?

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

**Comment by WestLangley** [comment]
`distance` can be zero.

**Comment by FishOrBear** [comment]
But the ```distance``` is 0, the light also no sense.
or
```
distance > 500 ? distance : 500
```

**Comment by mrdoob** [comment]
Currently, when `light.distance` is `0`, it actually means `Infinity`.

**Comment by FishOrBear** [comment]
When I use distance = 5000, I find that the results are not expected.
So I read the code.
I think this will bring chaos to the caller?

**Comment by mrdoob** [comment]
> When I use distance = 5000, I find that the results are not expected.

What are the expected results? And what results are you getting?

**Comment by FishOrBear** [comment]
In theory, when I set Distend = 5000
The distance of light should be 5000, but because of the camera parameters.
Point light source can only affect the distance of 500

**Comment by FishOrBear** [comment]
https://jsfiddle.net/cxcad/1z23vwv6/1/
in line 40

**Comment by WestLangley** [comment]
@mrdoob I cleaned up the fiddle: https://jsfiddle.net/1z23vwv6/2/

@FishOrBear It is your responsibility to set the shadow mapping parameters based on your scene. Generally, you should set the near and far planes of the shadow map to be as tight as possible for quality shadows.

**Comment by FishOrBear** [comment]
In the dynamically generated space inside.
There may be no way to perfect the near plane and far plane.
So I can only set its parameters as much as possible.
So that it has a normal effect.

According to my understanding, the smaller the near plane and the far plane, the shadow quality will be better?

**Comment by WestLangley** [comment]
Most the the depth precision is near the front of the frustum. So set your near plane as large as possible.

You can read about depth precision [here](http://www.songho.ca/opengl/gl_projectionmatrix.html).

**Comment by FishOrBear** [comment]
If I want to use millimeters to simulate the room, will it be too large to cause accuracy problems?
Or that I just control the camera's near plane and far plane can achieve the effect?

**Comment by WestLangley** [comment]
Try to answer your question yourself by doing an experiment.

If you need more help, see [stackoverflow](https://stackoverflow.com/questions/tagged/three.js) or the [forum](https://discourse.threejs.org). Be sure to show your code when you ask a question.
