### ISSUE TITLE
why circleGeometry has not an height parameter so it could be turn into a Cone easily

### ISSUE THREAD

**Issue by cyth319** [mrdoob/three.js#12014]
if circleGeometry has an height parameter it would be a coneGeometry automaticly. As far as i understand you already doing it with cylynderGeometry wihle making its top circle's radius 0. but if we build things up from the bottom  it would be most beautiful way indeed. 

-> give circle a height parameter (if height is 0 its a circle)
-> if height is not 0  its a cone
-> create cylinder two circle and planes between them

Is there a specific reason why you did not it this way?

**Comment by WestLangley** [comment]
`ConeGeometry` has the `height` parameter.

I would not merge cones and circle geometries because they have very different UV patterns.

**Comment by cyth319** [comment]
@WestLangley what UV pattern means?

**Comment by WestLangley** [comment]
Sorry. I meant to say [UV mappings](https://en.wikipedia.org/wiki/UV_mapping).
