### ISSUE TITLE
OrbitControls

### ISSUE THREAD

**Issue by wu21731** [mrdoob/three.js#12018]
##### Description of the problem 

This form is for three.js bug reports and feature requests only.  
This is NOT a help site. Do not ask help questions here.  
If you need help, please use [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.  
A code snippet, screenshot, and small-test help us understand.

You can edit for small-test.  
http://jsfiddle.net/akmcv7Lh/ (current revision)  
http://jsfiddle.net/hw9rcLL8/ (dev)

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

When I use the old version of OrbitControls.js, if I set enablePan=true and enableRotate=false ,I can drag the model with left key of mouse ,but can't drag it with the last version.

**Comment by WestLangley** [comment]
You can modify the `OrbitControls` button definitions.
```
// Mouse buttons
this.mouseButtons = { ORBIT: THREE.MOUSE.LEFT, ZOOM: THREE.MOUSE.MIDDLE, PAN: THREE.MOUSE.RIGHT };
```

**Comment by wu21731** [comment]
@WestLangley It doesn't work yet.

**Comment by wu21731** [comment]
replace
```
if (scope.enableRotate === false) return;

                handleMouseDownRotate(event);

                state = STATE.ROTATE;
```
with
```
                if (scope.enableRotate) {

                    handleMouseDownRotate(event);
                    state = STATE.ROTATE;
                } else if (scope.enablePan) {
                    handleMouseDownPan(event);
                    state = STATE.PAN;
                }
```
in function onMouseDown and onTouchStart.

**Comment by WestLangley** [comment]
`OrbitControls` is part of the examples, not part of the Library. You are free to change it as you like.
