### ISSUE TITLE
Can't import same file twice in a row in threejs editor.

### ISSUE THREAD

**Issue by ChrisDenham** [mrdoob/three.js#12025]
I've just been experimenting with the threejs editor at: https://threejs.org/editor/ and noticed what seems to be a general bug with the import function.

The thing I noticed is that if I import the same file twice in succession, the second import does nothing. If however, I import file A, then file B, then file A again, it works as expected.

I've tried it with my own JSON object files, and 3DS files, and even files exported by the editor itself... and I get the same problem regardless.

**Comment by Mugen87** [comment]
Maybe a duplicate, see #11987

**Comment by ChrisDenham** [comment]
Ah ha. 👍 
Sorry, I did search before I posted, but didn't manage to find the issue & fix. Thanks.
How often does the code at  https://threejs.org/editor/ get updated with bug fixes?

**Comment by Mugen87** [comment]
The editor is updated within a new `three.js` release. So the mentioned fix is available with `R88`.
