### ISSUE TITLE
webgl2

### ISSUE THREAD

**Issue by MHA15** [mrdoob/three.js#12035]
hi 
I had compile source of dev87 on my own to add webgl2renderer source and example 
I open sandbox example but it didn't show anything and it have no error which means webgl2renderer had added successfully 
Is webgl2renderer still have problem ? When we can use it(nearly)? 
I'm using RawShderMaterial and bufferGeometry only so I don't need to it be perfect match with other parts.
Can I still waiting or it's better for me to using pure webgl2 ?

**Comment by mrdoob** [comment]
What's your use case?

**Comment by BAntDit** [comment]
> Is webgl2renderer still have problem ?

It has no problems. It's just empty for now. Webgl2renderer is not ready and it does not make any DIPs, just clear render buffers each frame.

**Comment by MHA15** [comment]
I'm trying to write a 2d graph visualization with webgl but since it is hard for zoom and ... I'm using Threejs because of its camera.
and I wants webgl2 because of supporting newer version of glsl

**Comment by Mugen87** [comment]
see #11363 and #9965
