### ISSUE TITLE
OutlinePass doesnt work with white background on canvas?

### ISSUE THREAD

**Issue by JamesHealdUK** [mrdoob/three.js#12030]
##### Description of the problem 
Trying the example here: https://threejs.org/examples/webgl_postprocessing_outline.html

I've tried setting the renderer clear color to white, the outline of the selected object disappears until I change the background color to black again. Any way around this?
##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by drreparo** [comment]
you can change visibleEdgeColor, hiddenEdgeColor in THREE.OutlinePass.
but i guess the main problem is Overlay Materials blending Option.

In getOverlayMaterial function, default value is THREE.AdditiveBlending.
if light staged in scene, outline was blended with light, then it seems to be disappeard.
It was able to change situationally option,

such as,
blending : THREE.CustomBlending,
blendingEquation: THREE.AddEquation,
blendSrc: THREE.SrcAlphaFactor,
blendDst: THREE.OneMinusSrcColorFactor

...

**Comment by JamesHealdUK** [comment]
Tried those options, but still no change sadly. Tried all combination of colors for visibleEdgeColor and still nothing.

One user reported success by removing the blending attribute all together but that didnt work for me,sadly.

**Comment by silvainSayduck** [comment]
I got the OutlinePass to work with an opaque white background using [@DIeHarke's version](https://github.com/mrdoob/three.js/issues/12678#issuecomment-364641472) of the OutlinePass AND replacing `blending: THREE.AdditiveBlending` by `blending: THREE.NormalBlending` in the `getOverlayMaterial` function.

**Comment by mrsaleh** [comment]
I have the same issue, and I was wondering how this issue got closed without being resolved.

**Comment by makc** [comment]
@mrsaleh since technically there is nothing to fix - the example is not broken ) it just so happens that it uses dark backgound.

you can see the same thing happened in #17665 - it was closed as soon as a workaround was offered.
