### ISSUE TITLE
what is the blender-three.js file format?

### ISSUE THREAD

**Issue by norangit** [mrdoob/three.js#12052]
hi, I am new to three.js. I found demo:  https://threejs.org/examples/?q=blender#webgl_loader_json_blender,  the data source file is generated by blender, but the new file I got by blender 2.78 with three.js ad-on (from here https://github.com/mrdoob/three.js/tree/master/utils/exporters/blender) is below:
```
{
    "metadata":{
        "position":179,
        "generator":"io_three",
        "version":3,
        "type":"BufferGeometry",
        "normal":179
    },
    "data":{
        "index":{
            "array":[...],
            "type":"Uint16Array",
            "itemSize":1
        },
        "attributes":{
            "position":{
                "array":[...],
                "type":"Float32Array",
                "itemSize":3
            },
            "normal":{
                "array":[...],
                "type":"Float32Array",
                "itemSize":3
            }
        },
        "groups":[{
            "start":0,
            "materialIndex":0,
            "count":204
        }]
    }
}
```
And I can not render successfully by either ObjectLoader or JSONLoader, is there a latest demo with the above data format?

Or please tell me where I did go wrong?
Thanks so much!

**Comment by Mugen87** [comment]
Ensure, you use the type `Geometry` when you export your model.

![image](https://user-images.githubusercontent.com/12612165/29711171-ec56c942-8993-11e7-9912-e65ab11e681b.png)

**Comment by norangit** [comment]
Thanks very much!!!
