### ISSUE TITLE
Why extrudeGeometry are relate on binormal of spline?

### ISSUE THREAD

**Issue by budblack** [mrdoob/three.js#12056]
I found code in '/three.js/src/geometries/ExtrudeGeometry.js:464'

```js
normal.copy( splineTube.normals[ 0 ] ).multiplyScalar( vert.x );
binormal.copy( splineTube.binormals[ 0 ] ).multiplyScalar( vert.y );
```
It means that coordinate in extrud are almost only related the direction of normal and binormal. But not the world coordinate.

In some specical cases, such as pull along Axis X or Z. 
When
Value of x or z changed less than y, binormal towards to horizontal. 
Value of x or z changed more than y, binormal towards to  Vertical.

I think only draw an extrude with a horizontal shape, should we deal it's coordinate carefully.
In other time, coordinate of shape should not be relate on normal or binormal of spline.

**Comment by Mugen87** [comment]
The mentioned `normals` and `binormals` properties of a give extrude path are calculated with `Curve. computeFrenetFrames()`. These data can be used to define a orthonormal basis for a given point on the curve, which can be very useful generating correct extrusions. The theory behind this approach is based on the [Frenet–Serret formulas](https://en.wikipedia.org/wiki/Frenet%E2%80%93Serret_formulas).

**Comment by budblack** [comment]
Thx a lot. I'v read some papers about it. Now I know there's no contact between extrude's Y direction and world coordinate. Coordinate of a shape (or frames) to an extrude is only related on extrude path's derivative.
