### ISSUE TITLE
unexpected error when far/near is too big in PerspectiveCamera()

### ISSUE THREAD

**Issue by YIbanYiban** [mrdoob/three.js#12065]
I am working on a project that needs to move the camera in a large scale of range. so I use a large frustum. Then I found that when the difference of positions of far plane and near plane is bigger than a number(100000000 as an example), some planes near the borders of screen will disappear. This looks like a bug of culling and I haven't  find any similar problem throughout the Internet. 
My OS is MacOs 10.12.6 and I am using THREE.WebGLRenderer 87dev.

**Comment by mrdoob** [comment]
Can you share a screenshot?

Also, 1 unit = 1 meter. 100,000,000 meter sounds like a very big space. Are you doing a universe simulation or something?

**Comment by YIbanYiban** [comment]
Yes, I am trying to simulate the earth-sun system and show the details on the earth at the same time. So, I need a small value of near plane and a very big value of far plane. This is my screenshot and the near plane is at 0.001 and far plane is at 1000000. The earth radius is 6371 and the texture around the sphere is some kind of transparent. 
![screen shot 2017-08-29 at 09 06 07 2](https://user-images.githubusercontent.com/21998187/29800209-4ee8f0da-8c9b-11e7-8208-070be6818324.png)

**Comment by WestLangley** [comment]
You are limited by the precision of your hardware.

If you need to zoom in to a planet, then keep the camera at the origin, and move to planet near the camera.

Avoid small values of the near plane and follow the link in https://github.com/mrdoob/three.js/issues/12011#issuecomment-325533181.

**Comment by YIbanYiban** [comment]
However the problem is around the near plane, other than the far plane where the z-fighting used to happen.

**Comment by mrdoob** [comment]
> If you need to zoom in to a planet, then keep the camera at the origin, and move to planet near the camera.

That's how http://stars.chromeexperiments.com/ was done. Scaling the scene instead of having a impossibly big near/far.

**Comment by YIbanYiban** [comment]
I finally realize my poor understanding of the z-fighting phenomenon, Thank you and sorry for my disturbing...
