### ISSUE TITLE
why circlegeometry's central coordinates are always 0 0 0?

### ISSUE THREAD

**Issue by cyth319** [mrdoob/three.js#12069]
Is there a specific reason for we can not set central coordinates for ciclegeometry or its you just do not wnt make more coding job?

**Comment by WestLangley** [comment]
Use this pattern to translate any geometry.
```
var geometry = new THREE.CircleGeometry( radius, segments );
geometry.translate( x, y, z );
```

**Comment by cyth319** [comment]
okay but why we can not set it up from constructor? Thats what iam asking here

**Comment by mrdoob** [comment]
How would you propose the API should look like?

**Comment by cyth319** [comment]
ummmmmm yeah exactly

**Comment by WestLangley** [comment]
You would have to add a location parameter to the constructor of every built-in geometry for consistency.

**Comment by mrdoob** [comment]
> You would have to add a location parameter to the constructor of every built-in geometry for consistency.

Exactly.

@cyth319 please, use this approach: https://github.com/mrdoob/three.js/issues/12069#issuecomment-325378904

**Comment by cyth319** [comment]
yeah you are right.

**Comment by cyth319** [comment]
maybe i will do that and make a pull request in the future.
