### ISSUE TITLE
OrthographicCamera suddenly disappear objects

### ISSUE THREAD

**Issue by MHA15** [mrdoob/three.js#12060]
in OrthographicCamera I have some points with bufferGeometry and shderMaterial (in plane z=0) and I set the camera 
planes in -width/2 to width/2 and for height to when it's load I can see all of my points but when I drag my points into somewhere else (out of camera planes) and I pan to there, my points will be suddenly disappear.

isn't this a bug?

I'm using OrthographicCamera because my world is 2d and it has better performance in my case

latest version

**Comment by WestLangley** [comment]
Either set `frustumCulled = false`, or update the bounding sphere.

**Comment by MHA15** [comment]
shouldn't bounding sphere being update automatically? because I don't have this problem with perspective camera.
