### ISSUE TITLE
Threejs example "Vive/Paint" is freezing inside Oculus HMD in latest firefox and nightly. 

### ISSUE THREAD

**Issue by swomack** [mrdoob/three.js#12061]
##### Description of the problem 

https://threejs.org/examples/?q=vive#webvr_vive_paint

This example is freezing inside Oculus HMD (no new frame is submitted) when i press any button of a Oculus touch controller. Strange thing is that, the browser remains fine and there is no console error. Also, if i use the joysticks (axes) there seems to be no problem at all.

It works fine with chrome and vive with firefox is also working fine. The problem is only occurring with firefox (&nightly) + Oculus touch controller.

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Oculus Rift with touch controller.

**Comment by mrdoob** [comment]
I think you should report this to Mozilla instead.
