### ISSUE TITLE
Objectloader.js prompts the json format problem

### ISSUE THREAD

**Issue by shunzizhan** [mrdoob/three.js#12066]
##### Description of the problem 

When I use `threejs vue`, I introduce `ObjectLoader.js` files loaded obj files, but I have a question, it is wrong to suggest the json format, see the obj file header information found, but the introduction of the sample code and I are the same obj file, and then I found that the introduction of the sample presentation and `ObjectLoader.js` is a little difference, the official `OBJLoader.js` is processing and will file parsing into json, but `ObjectLoader.js` file seems without this step, I tried to modify `ObjectLoader.js` file, but the introduction of the file is not updated, don't know whether there is support for the development of modular

![image](https://user-images.githubusercontent.com/7811369/29768864-77806626-8c1a-11e7-84a0-728d827e544f.png)

my project use the same obj file
![image](https://user-images.githubusercontent.com/7811369/29768504-18b9c778-8c19-11e7-84c1-8f32788b5a8c.png)

demo
![image](https://user-images.githubusercontent.com/7811369/29768656-b25bd858-8c19-11e7-9819-b36eb282c121.png)

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
`ObjectLoader` and `OBJLoader` load two different formats. `ObjectLoader` loads three.js' `.json` format. `OBJLoader` loads `.obj` files.
