### ISSUE TITLE
Blender can not export JSON with skinning animation data

### ISSUE THREAD

**Issue by orklann** [mrdoob/three.js#12070]
With this example model file 

https://github.com/mrdoob/three.js/blob/dev/examples/models/skinned/simple/simple.blend

I can not export a JSON file which is the same as 

https://github.com/mrdoob/three.js/blob/dev/examples/models/skinned/simple/simple.js 

with correct skinning animation data.

What I want is the same as 

https://github.com/mrdoob/three.js/blob/dev/examples/models/skinned/simple/simple.js 

from 

https://github.com/mrdoob/three.js/blob/dev/examples/models/skinned/simple/simple.blend

I just want to learn how to generate skinning animation JSON file for three.js.

My JSON output has `bones: 0`

Blender version: `Version 2.78`
Export addon: current dev branch `r87` 

Need some help.

**Comment by orklann** [comment]
Solved.

The `simple.blend` in current repo does not associate the bones with the mesh, after selecting both mesh and armature and press CTL+P, and select `with automatic weights`, It's ready to export.

Export:
Only select the mesh, and export works

Please update the 

https://github.com/mrdoob/three.js/blob/dev/examples/models/skinned/simple/simple.blend

to correct it.

**Comment by Mugen87** [comment]
Do you mind creating a PR? :innocent:

**Comment by orklann** [comment]
I submit a PR a few hours ago.
