### ISSUE TITLE
Include file extension in module imports for using modules in browser

### ISSUE THREAD

**Issue by bentok** [mrdoob/three.js#12075]
##### Description of the problem 

When using modules natively in the browser (Chrome Canary with flag enabled), the import statement needs to include the file extension in the path. Otherwise the browser will return a 404 for the file.

Example:
```
Old: import { Light } from './Light';
New: import { Light } from './Light.js';
```

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by bentok** [comment]
Unless there is objection to this change, I plan on submitting a PR for this.

**Comment by looeee** [comment]
It is considered best practice to include the extension (at least according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)) since there is no guarantee that module bundlers or importers will work without it.

**Comment by Mugen87** [comment]
Besides, this change makes the code more consistent since there are various places where the file extension is already used.

Examples:
https://github.com/mrdoob/three.js/blob/master/src/Three.Legacy.js
https://github.com/mrdoob/three.js/blob/master/src/materials/Materials.js
