### ISSUE TITLE
VRControls and VREffect do not handle vrdisplayconnect or vrdisplaydisconnect

### ISSUE THREAD

**Issue by leweaver** [mrdoob/three.js#12109]
##### Description of the problem 
The `THREE.VRControls` and `THREE.VREffect` classes do not handle vrdisplayconnect or vrdisplaydisconnect events, so on desktop machines you must reload the page whenever an HMD is connected or disconnected. The vrDisplay object should be re-evaluated whenever either the vrdisplayconnect or vrdisplaydisconnect event is fired by the browser.

Further, a site that wishes to use these classes cannot implement the events themselves and re-instantiate the classes, as there is no callback or promise that can be used to determine when the internal gotVRDisplays callback has completed. The lack of a callback can also lead to a race condition, since the navigator.getVRDisplays method is not guaranteed to return immediately (there is nothing to tell consumer that the value of VRControls.getVRDisplay has been set).

Perhaps the addition of a third callback to the constructors could help: `THREE.VRControls = function ( object, onError, onDisplayChanged )` - this could be called from the internal `gotVRDisplays` method. 

##### Three.js version

- [ x ] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Any desktop VR hardware that can be connected or disconnected: Vive, Oculus, Windows Mixed Reality etc

**Comment by mrdoob** [comment]
The [WebVR.js](https://github.com/mrdoob/three.js/blob/dev/examples/js/vr/WebVR.js) that landed in r88 handles these events.
