### ISSUE TITLE
Example of ShaderMaterial with Shadowmap Support

### ISSUE THREAD

**Issue by andreasrosdal** [mrdoob/three.js#12114]
This is a feature-request for a ShaderMaterial with Shadow Support in Three.js, which would make it more user-friendly to add custom shaders with support for rendering shadows.

I have found the following code to create a ShaderMaterial that only renders shadow, however it only works with Three.js r71: https://gist.github.com/ayamflow/93aba91065c2b9750f4f

An example for Three.js with a custom ShaderMaterial with shadowmap support would also be useful.

**Comment by WestLangley** [comment]
Question [posted](https://stackoverflow.com/questions/46041064/enabling-shadow-map-on-custom-material-shader) on SO.

**Comment by andreasrosdal** [comment]
Thanks, @WestLangley. I have tried replicating the MeshLambertMaterial, still no success. I'll try some more, then share my code.  I therefore still think this feature request for a "high level" ShaderMaterial with shadows is valid.

**Comment by WestLangley** [comment]
Use SO for help please.

**Comment by mrdoob** [comment]
Maybe we should add a example for this.

**Comment by WestLangley** [comment]
>I therefore still think this feature request for a "high level" ShaderMaterial with shadows is valid.

There is no such thing as a `ShaderMaterial` that supports shadows out-of-the-box. It is the user's responsibility to specify the shader code.

Requesting an _example_ of a `ShaderMaterial` that supports shadows is reasonable.

**Comment by andreasrosdal** [comment]
An example of a ShaderMaterial with shadows would be perfect! Thanks for all the replies.

**Comment by moraxy** [comment]
Sorry if I'm misunderstanding something, shadows and shaders aren't exactly my forte, but would [example 3](http://blog.edankwan.com/post/three-js-advanced-tips-shadow)(above '_Tips for particle shadowing_') be helpful here?  
According to the comments it only works with `r74dev` and there's no proper source release, but it might be possible to port it to a more recent release, I hope.

**Comment by andreasrosdal** [comment]
@moraxy That code is for Three.js r74, which refers to a 'shadowmap_fragment'. However, I can't find this shader code in Three.js version r87. This is probably my most significant obstacle at the moment.  Where can I find shadowmap_fragment in r87?

**Comment by moraxy** [comment]
There was a `shadowmap_fragment.glsl` that was in `r74` and then got deleted in 8eaf494a462762562dcc4f862debb6df26a703dc, last version would be in [rev 3337a01](https://github.com/mrdoob/three.js/blob/3337a01f26dc3ff28c7718adb98a7f24a49baad3/src/renderers/shaders/ShaderChunk/shadowmap_fragment.glsl).  Does that one work?

**Comment by andreasrosdal** [comment]
@moraxy No, I'm not able to get shadowmap_fragment.glsl from r74 working on r87, probably because of more recent changes to the other shader code, for example shadowmap_vertex.glsl has been changed a lot after that. So a r87 example with a shadowmap would be very much appreciated.

**Comment by moraxy** [comment]
@andreasrosdal maybe PR #12167 might be of use, it adds receiving shadows to `ShaderMaterial`, although I can't tell if it adjusts the shadow for surface derformation. Maybe you can merge that with http://jsfiddle.net/gqeu932j/1/ (`ShaderMaterial` casting shadow) and all that's missing would be self-shadowing.

**Comment by andreasrosdal** [comment]
Thanks @moraxy - this brings me many steps closer. I'm studing the code now.

**Comment by andreasrosdal** [comment]
I have managed to implement a working shader with only shadows, by looking at PR #12167. However, combining the updated Watershader (which has shadows), with my Freeciv terrain shader is proving difficult. The resulting color in my terrain_fragment_shader_fragment.glsl will always be black. So basically the terrain shader always returns a black color, I'm not sure why, perhaps it is related to the fact that the Watershader is really a mirror, or perhaps something completely different)

This is my current development branch with the commit to adds shadows to the terrain shader:
https://github.com/andreasrosdal/freeciv-web/commit/bd8629c154f618db05f7428347c2295ab08561c5

The original terrain shaders can be found here before I added shadows:
https://github.com/freeciv/freeciv-web/tree/develop/freeciv-web/src/main/webapp/javascript/webgl/shaders

(I'm only reaching out for help here because I'm really stuck, I hope someone will help if they want to.)

**Comment by WestLangley** [comment]
Use SO for help please.

**Comment by andreasrosdal** [comment]
Thanks for the help. Closing this issue.

**Comment by zwcloud** [comment]
`ShaderMaterial` shadow with directional light: http://jsfiddle.net/gqeu932j

**Comment by wmcmurray** [comment]
I just made this basic example with **shadows**, **fog** and **dithering** support : 
https://gist.github.com/wmcmurray/6696fc95f25bbd2401d72a74e9493261 (currently working on r108)

It reuses shader chunks used by other threejs materials (I mostly looked at the meshphong shader code for inspiration). It's the first time I mess with ShaderMaterial, so it may not be perfect, but it works ! :man_shrugging:

**Comment by JosephCoppola-FW** [comment]
> `ShaderMaterial` shadow with directional light: http://jsfiddle.net/22jpzktk/

@wmcmurray Using the above fiddle, and replacing all the shader work with your example results in this -> http://jsfiddle.net/awp8vyxs/1/

Any idea what is wrong or what I may have missed?
