### ISSUE TITLE
Three.js does not work with FF shader editor now

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#12111]
it throws

> THREE.WebGLRenderer: Error: Permission denied to access property "apply"

followed by

> TypeError: gl is undefined

probably some "strict" somewhere messes this up. do you know any workaround?

**Comment by mrdoob** [comment]
When you say "now"... Do you mean after r87 or after a Firefox update?

**Comment by makc** [comment]
Good question, but I don't know the answer.

**Comment by makc** [comment]
However, [they were going to drop shader editor](https://github.com/spite/ShaderEditorExtension/issues/21), so they probably did not update it.

**Comment by mrdoob** [comment]
🤔

**Comment by makc** [comment]
Aaaaand it's FF. I checked 3js r73 just now, and it fails too.

**Comment by makc** [comment]
Just an update for people who end up here: it was not FF, it was Spector.js addon. everything went back to normal once I removed it.
