### ISSUE TITLE
WebGL to Vulkan

### ISSUE THREAD

**Issue by oracle63** [mrdoob/three.js#12116]
Do you wan't to adopt Vulkan ? Sorry for my bad English, i'm french... and i'm a newbie ^^

**Comment by tentone** [comment]
Hi

WebGL is the graphic API for the web, each web browser implements it differently, but usually WebGL is implemented on top of already existing API's (DirectX, OpenGL and eventually Vulkan).

I hope that i was able to explain this properly to you.

Cumps

**Comment by oracle63** [comment]
Thanks. And sorry for spamming.
