### ISSUE TITLE
ShadowMap logarithmic DepthBuffer issue

### ISSUE THREAD

**Issue by Fyrestar** [mrdoob/three.js#12126]
I'm having issues with shadows using logarithmic DepthBuffer and a DirectionalLight. The issue occurs by enabling both castShadow and receiveShadow for a mesh, it basically shadows itself with it's own casted shadow it seems. Where could i fix this?
![slog](https://user-images.githubusercontent.com/28584767/30039960-a779816e-91d8-11e7-8d85-9580257cae71.png)

I randomly found this fiddle you can test it. The sphere gets self-shadowed same as in the image above.
http://jsfiddle.net/zjb1bc2w

**Comment by mrdoob** [comment]
#7815
