### ISSUE TITLE
Android webView load fbx

### ISSUE THREAD

**Issue by wu21731** [mrdoob/three.js#12138]
##### Description of the problem 

```
Security context: 0xb9e0b9a9 <String[17]: http://www.ouu.cn>
2: flattenToBuffers [http://www.ouu.cn/mobile/js/FBXLoader.js:~3535] [pc=0x8ea9a854](this=0x8eed4799 <a Geometry with map 0xb9a45485>)
3: genGeometry [http://www.ouu.cn/mobile/js/FBXLoader.js:~702] [pc=0x8eaded54](this=0xb906b975 <JS Global Object>,geometryNode=0x9abbcc79 <an Object with map 0xb9a29e11>,deformer=0x5f5081f1 <undefined>)
4: parseMeshGeometry [http://ww...
```
##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by Mugen87** [comment]
Can you provide some more information what's actually happening in your application?

**Comment by Mugen87** [comment]
Closing. 

@wu21731 We can reopen it if you verify, that your problem is actually caused by a `three.js` bug.

**Comment by wu21731** [comment]
@Mugen87 so, how to resovle it?
