### ISSUE TITLE
Hi all ! How to make a pull request ?

### ISSUE THREAD

**Issue by oracle63** [mrdoob/three.js#12139]
You'll probably mocking me but i'm a newbie with github. I have corrected 74000 minor ESLint errors in whole repository with IntellidJ Code Quality Tool. Ive worked with a copy of the repo on local. I don't manage to make a pull request. I've only one branch: dev. Could you help me please ? Thanks.

**Comment by Mugen87** [comment]
These articles might help: 

https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js
https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by oracle63** [comment]
Thanks
