### ISSUE TITLE
Feature/Discussion: Allow different version of THREEJS/Object3D to coexist.

### ISSUE THREAD

**Issue by NicolasRannou** [mrdoob/three.js#12131]
##### Description of the problem 

I write a JS library that does create some "Helpers" for THREEJS. (Geometries, Cameras and Meshes).

I recently moved to a more standalone architecture, using es6 imports instead of relying on the global 'THREE' variable:
```
// before
class myHelper extends THREE.Object3D {...}

// now
import {Object3d} from 'three';
class myHelper extends Object3D {...}
```

As a result, I loose reference to the global `THREE` variable.

The problem is that if an application, an object is created from "THREE.Object3D" and another with my library from "{Object3D} from 'three'", the object ids might collide and THREEJS doesn't work as expected.

```
// my app
const scene = THREE.Scene();
const mesh = THREE.Mesh(...);
scene.add(mesh);

const myMesh = AMI.SliceHelper();
scene.add(myMesh);

// messed up..
```

Is there a good solution to manage those conflicts?

It seems that `THREE.Geometry` may also rely on unique IDs.

I do not have a good solution for that as it seems tricky.

1- Fix it in the core library?
2- Require usage of global "THREE" variable in my library?
3- Any best practice?

To me option 2 seems the only viable solution right now but I hope there may be a good way to tackle it...

**Comment by looeee** [comment]
You can just do 

    import * as THREE from 'three'; 

It seems like the simplest solution to me as it keeps everything in the global THREE namespace.

**Comment by NicolasRannou** [comment]
yes that seems the only way to go :(

What do you think about an "hybrid approach":
```
import {Vector3} from 'three';
import * as THREE from 'three';

class myHelper extends THREE.Object3D {
  ... do something with Vector3 that has no extra deps.
}
```

It is a bit more maintenance but some parts only rely on `Vector3` and `Matrix4`, which we should not have to keep attached to the global scope, correct? or should we keep it attached to the global scope too?

Thanks!

**Comment by looeee** [comment]
If you do `import * as THREE from 'three';` then you have already imported `Vector3`. There's no advantage to doing it twice.

**Comment by NicolasRannou** [comment]
Yes I did test my build process too fast, that didn't help -

I ended up keeping the global references when needed (i.e. THREE.Object3D, THREE.Mesh, etc.) but got rid of them when not needed (Vector3, Matrix4, etc.)
