### ISSUE TITLE
feature: optionally limit raycaster to single object

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#12130]
i e break out of all loops once one intersection was found. because when I think about it, there was hardly a single case ever when I had to look past [0]. I can imagine that in some cases it is needed, but most of the time it just burns the cycles for no reason, so there has to be an option to turn it off.

**Comment by makc** [comment]
even better would be to have gpu-based method to identify the foremost object so that user would not have to bother removing background from testing by hand, and then the current raycaster does not even need any code change.

**Comment by makc** [comment]
@Usnul that's close, but it relies on scene being static. ideally, we could have a way to pass object id as uniform to scene.overrideMaterial, and then gpu picking would be easier to implement

**Comment by makc** [comment]
(well, not that good idea too, because it explodes draw call count)

**Comment by mrdoob** [comment]
> i e break out of all loops once one intersection was found. because when I think about it, there was hardly a single case ever when I had to look past [0].

You're probably expecting that [0] is the closest one, right? In order to know that we have to test all the objects and sort the intersections. At that point, why not provide all the intersections too?

**Comment by makc** [comment]
because I can hand-pick only the objects that are in the front before feeding them to the raycaster. think alphabet cubes scattered across the floor, and I am not giving the raycaster the floor. true, you can put all the cubes together, and then [0] can be whatever, but then I would not be using this option.

however, like I said in my 2nd comment, if we could identify foremost object first, we dont need any change to raycaster at all - we can just run it on that object alone. so yeah. how to do that in arbitrary scene in the most efficient way? I can only think of replaceing  all the materials by hand, rendering to 1x1 and restoring original materials.

**Comment by makc** [comment]
I was thinking since I said
> we dont need any change to raycaster at all

this makes it more like support issue so no need to track it

**Comment by Usnul** [comment]
You could render to 1x1, you will have very few fragments, but you will still have the same geometry. Also, if you have to do a few lookups per frame - it will quickly become a burden. Spatial index (a special data structure to reason about space) is a better overall approach, albeit requiring more work to implement. If your geometry is animated via shaders - it becomes less easy.
