### ISSUE TITLE
FBX importer silently ignores translation animations if one axis doesn't change

### ISSUE THREAD

**Issue by DustinJSilk** [mrdoob/three.js#12149]
When importing an FBX animated object, all translation animations are ignored if any one axis doesn't change.

So if i animate a cube alone the Y-Axis but completely ignore the X and Z axis, then the animation won't play at all.

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by DustinJSilk** [comment]
My initial digging around brought me to [this line here] (https://github.com/mrdoob/three.js/blob/65dde6213e7027b5e3e9a7614868c34a19ec97f7/examples/js/loaders/FBXLoader.js#L3272) where hasCurve and hasKeyOnFrame fail completely if one axis is null.

**Comment by mrdoob** [comment]
Do you have a sample model we can use to fix this?

**Comment by looeee** [comment]
Here you go. A simple box at the origin that rotates around the y-axis by 355 degrees over 100 frames. 

boxRotateAllAxes.fbx - rotation is defined for all three axes, and the animation plays correctly.
boxRotateOnYOnly.fbx - rotation is defined only on the y-axis, and the animation does not play.

[rotationTests.zip](https://github.com/mrdoob/three.js/files/1286844/rotationTests.zip)

**Comment by mrdoob** [comment]
Sounds like an easy bug to fix.
