### ISSUE TITLE
Fragment shader played in reverse

### ISSUE THREAD

**Issue by scummtomte** [mrdoob/three.js#12147]
Hey!

I have this fragment shader that I found on shadertoy.com, and now I'm going to implement it via three.js. My issue is that I would really want to be able to go control the "time" of the shader. So that I can let it "play" and then "reverse" the effect to get it back to the starting point. It will also be interactive so it's not a question of an animation.

What would be the best way to do this?

Here's the shadertoy effect:
https://www.shadertoy.com/view/ldcGDX

Would really appreciate an answer, thank you!

**Comment by looeee** [comment]
@scummtomte this isn't a help site. Try asking over on the forum instead 

discourse.threejs.org

**Comment by scummtomte** [comment]
Ok, Sorry, thx!
