### ISSUE TITLE
Render object direct

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#12144]
What i originally wanted to do with `onBeforeRender()` was something like this:

```
foo.onBeforeRender = ( renderer , scene , camera )=>{

	
	 _gl.enable(_gl.STENCIL_TEST)

	_gl.clearStencil( 0 )
	_gl.clear( _gl.STENCIL_BUFFER_BIT )
	_gl.stencilFunc( _gl.ALWAYS , 1 , 1 )
	_gl.stencilOp( _gl.REPLACE , _gl.REPLACE , _gl.REPLACE )
        ....
       
        renderer.render( foo, overrideMaterial, camera ) 
}
```

I used to piggyback on a hack of `renderBufferDirect`, but i had to pass all the stuff that it wanted so i had to expose all of its arguments in `onBeforeRender`,

I've updated to r87 to actually use the official onBeforeRender but i'm baffled and not sure what to do. 

I wanted all of this logic to happen in the callback, either onBeforeRender or onAfterRender on last on the first (or last) thing i want to draw in sequence.

My scene graph looks something like this:

```
  ├ ObjBravo
     ├ meshA
     └ meshB
```

what i want to happen is:

0. render stuff
1. set stencil
2. draw A with shader FOO
3. stencil op
4. draw B
5. stencil op
6. draw A with shader BAR
7. clear stencil
8. render other stuff

I'm about to try making another mesh C, with the geometry from A but a different shader and change the render order. I'm concerned though that render order doesn't play well with transparency, and that i have to set a unique number for each one of these if i render multiple. 

Is there a better way of doing this? Could another method on the renderer help?

##### Three.js version

- [ ] Dev
- [x ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by pailhead** [comment]
This got addressed in the meantime. The issue was referring to the responsibilities of `renderBufferDirect`

https://github.com/mrdoob/three.js/blob/c318c586881d8ece16fe26de55bd0090e2df53ad/src/renderers/WebGLRenderer.js#L665-L693

**Comment by Mugen87** [comment]
Merging into #14476.
