### ISSUE TITLE
For...in loop in GLTFParser can cause gltf model load to fail

### ISSUE THREAD

**Issue by SamiraAtMicrosoft** [mrdoob/three.js#12162]
##### Description of the problem 

`GLTFParser.prototype.loadMeshes` and `GLTFParser.prototype.loadNodes` use `for...in` loops.

Since a `for...in` loop in JavaScript iterates over an objects properties, these can cause the parse to fail if there is a custom property added to the Array object elsewhere on the site. For example, in `GLTFParser.prototype.loadMeshes` there is:

```
for ( var name in primitives ) {
    var primitive = primitives[ name ];
    var geometry = geometries[ name ];
```

If another script does something like:

```
Array.prototype.newCustomProp = function (num) {
}
```

Then eventually `name` would equal `newCustomProp` and the attempt to find primitive/geometry will fail.

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
It is bad practice to extend the base prototypes of JavaScript.

Read this for more information: [Maintainable JavaScript: Don’t modify objects you don’t own](https://www.nczonline.net/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/)

Related #11972

**Comment by mrdoob** [comment]
> If another script does something like:
>
> ```
> Array.prototype.newCustomProp = function (num) {}
> ```

If you ever see someone doing that, invite him to quite the javascript world please 😉

**Comment by mrdoob** [comment]
However, if `primitives` is an array, we shouldn't use `for in`.
/cc @donmccurdy

**Comment by RemusMar** [comment]
> Array.prototype.newCustomProp = function (num) {}
> If you ever see someone doing that, invite him to quite the javascript world please

The market is full of software "developers" these days.
Next time they might start to prototype the Java Island and the Java Sea.

**Comment by donmccurdy** [comment]
Most of these `for...in` loops are left from glTF 1.0, which used object syntax for a lot of things. We can replace them with traditional `for` loops yes.
