### ISSUE TITLE
Gimbal lock problem with TrasformControls

### ISSUE THREAD

**Issue by madferro** [mrdoob/three.js#12176]
Hi everyone, 

I found a problem (probably a bug) with rotations and TransformControls.
Using the transform controls helper, if I rotate a mesh on the Y axis, when I reach 90 degrees everything is flipped by -180 degrees.

I think this is due to the software avoiding gimbal lock, how to avoid it?

I tried even on the threejs editor (https://threejs.org/editor/) and it occurs even there.

Thank you

**Comment by WestLangley** [comment]
This has nothing to do with Gimbal lock. It is also not a three.js bug.

See the [SO question](https://stackoverflow.com/questions/46172742/gimbal-lock-at-y-axis-90-degrees).

**Comment by madferro** [comment]
Ok, understood, thank you very much! I will switch everything considering angles from quaternions instead from meshes rotation euler. Thank you again :)!
