### ISSUE TITLE
object3d.frustumCulled property not working as expected

### ISSUE THREAD

**Issue by croraf** [mrdoob/three.js#12170]
I set `object3d.frustumCulled = false;`, and the object still does not show on screen when out of camera frustum (further than far property of camera)?

object3d is:
```
const getSphere = (position, radius, slices, color=0xFFFFFF) => {
    const geometry = new SphereGeometry( radius, slices, slices );
    const material = new MeshBasicMaterial( { color: color } );
    const sphere = new Mesh( geometry, material );

    sphere.translateOnAxis(position, 1); 
    
    return sphere;
}
```

**Comment by Mugen87** [comment]
I'm not sure you actually understand the concept of view frustum culling. Please read the following article for more information: http://www.lighthouse3d.com/tutorials/view-frustum-culling/

If i misunderstand your post, reopen the issue and please demonstrate the bug with a fiddle.

https://jsfiddle.net/hfj7gm6t/

**Comment by croraf** [comment]
Only objects in frustum get shown on screen. If object has object3d.frustumCulled = false; it gets rendered even if outside of frustum. 

https://jsfiddle.net/ay3dp71z/

frustum far is 1000, same as cube distance from camera. Therefore it is cut partially. I expect to show all cube if frustumCulled=false

**Comment by WestLangley** [comment]
Setting `frustumCulled` to `false` has no effect on culling by the GPU. It only mean the renderer does not perform a frustum culling test on the CPU side.

**Comment by croraf** [comment]
@WestLangley If this is true, I don't see the point of that property. And I don't see the point of the test on the CPU side, because this is the job of GPU.

**Comment by WestLangley** [comment]
Sometimes the bounding sphere is either not known, or is not being updated. In those cases, frustum culling can be turned off.

**Comment by Mugen87** [comment]
You also might turning frustum culling off for things like particle systems.

**Comment by mrdoob** [comment]
On the other hand, you also don't want to tell the GPU to draw your whole city scene when only one building is visible.

**Comment by croraf** [comment]
@mrdoob @WestLangley Do you want to say you have CPU _frustum_ culling before GPU _frustum_ culling. This seems wrong thing to do. It is smart not to forward irrelevant objects to GPU, but this should be done in some other way, not with _frustum culling_ (as this is done much faster with GPU).


Anyways, I have a couple of big objects that I want to render always (not to be affected by far frustum plane), and a number of small ones that I want to be affected by frustum. This is not possible to achieve?

**Comment by mrdoob** [comment]
> This is not possible to achieve?

Not for the `near` and `far` planes, no...
