### ISSUE TITLE
LensFlare gets removed before it exits the screen

### ISSUE THREAD

**Issue by croraf** [mrdoob/three.js#12186]
I set lens flare in the position of object (sun), or in the position in front of the sun.
When I rotate camera to the right lens flare enters properly but exits before it should, like in picture.
 
![image](https://user-images.githubusercontent.com/19698636/30397273-9b8ea21c-98cc-11e7-9fde-afcdafc0454d.png)

If I move the camera or flare to some other position, so that sun IS NOT behind the flare it works perfectly.
In some positions it works ok even if sun IS in the background.

Sun is of this material type:
```
material = new MeshBasicMaterial({
                map: texture
            });
```

lensflare texture is from here:
https://github.com/mrdoob/three.js/blob/dev/examples/textures/lensflare/lensflare0.png
```
var flareColor = new Color( 0xcccccc );
var lensFlare = new LensFlare( texture, 500, 0.0, AdditiveBlending, flareColor );
```
(it happens also with NormalBlending and I noticed the same in particles emitter- shader particle engine)
Firefox 55, Windows 32bit
Chrome 56 on Android.

**Comment by croraf** [comment]
No one :(. Here is live example. (rotate right. Recommended mozilla. You have sourcemap, so you can debug the source code in inspector.)

**Comment by WestLangley** [comment]
If you believe there is a three.js bug, can you please provide a live, 50-line example that demonstrates it?

**Comment by croraf** [comment]
If you can help me: https://jsfiddle.net/q7L87mdg/. I don't see the flare, flare image does not load due to some network issues (check third load). If I load commented jpg image it does load, but some error happens.

**Comment by croraf** [comment]
In the working fiddle (second one) I noticed that the flare disappears completely if distance to the camera is higher than 100 (`camera.position.z > 110`), and is shown correctly if lower than 70 (`camera.position.z < 80`). In the distances between `camera.position.z = 110` and `camera.position.z = 80` it disappears partially.

**Comment by croraf** [comment]
Also when texture is not set, or is set as plain THREE.TextureLoader() instead of THREE.CubeTextureLoader() the flare is shown correctly. https://jsfiddle.net/gcuouje1/

**Comment by WestLangley** [comment]
@croraf Is [this](https://jsfiddle.net/6jL0z9L1/2/) dev branch version working as you expect?

**Comment by croraf** [comment]
It does! I should also check my real-life example. Can you tell which commit fixed the issue?

**Comment by WestLangley** [comment]
Fixed by https://github.com/mrdoob/three.js/commit/9ee6c4034b03f3f8f635344e33ab997c7ecd0648.
