### ISSUE TITLE
Getting the warning  THREE.WebGLRenderer 64

### ISSUE THREAD

**Issue by MarkDijkstra** [mrdoob/three.js#12183]
I am build a 360 viewer plugin which three.js is a part of, the plugin works fine but when I look as the console I see the warning **THREE.WebGLRenderer 64**, what does this mean? And how can this be fixed beause when I use some 360 images the plugin crashes not sure if this is the issue?

**Comment by Mugen87** [comment]
This log just indicates what version of `three.js` is used. It has nothing to do with a runtime error.
