### ISSUE TITLE
post-processing render targets are 2x downsampled with hiDPI / retina displays

### ISSUE THREAD

**Issue by robertoranon** [mrdoob/three.js#12188]
When using the EffectComposer with a hiDPI / Retina display (e.g. MacBook Pro), and setting 

`renderer.setPixelRatio( window.devicePixelRatio );`

to use the full display resolution, then, if post-processing with EffectComposer is used, render targets used in the composer passes do not use the window.devicePixelRatio parameter in setting their resolution, with the effect that render targets are downsampled 2X wrt the native display resolution.

This happens because, in EffectsComposer.js, the default render target resolution is set using the renderer.getSize() method, which returns the size of the canvas, not taking into account the DPR.

Possible solutions could be:
- change EffectComposer.js to use getDrawingBufferSize() instead of getSize() : this will take into account DPR
- change getSize() in WebGLRenderer.js to take into account DPR when returning its result.

##### Three.js version

- [X] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

hiDPI / Retina display

**Comment by WestLangley** [comment]
Yes, that is exactly why `getDrawingBufferSize()` was added in #11374.

Would you care to update the composer and examples?

See if there is a significant performance hit.

**Comment by robertoranon** [comment]
I did the modification to the composer and examples (just webgl_postprocessing_nodes.html was calling `renderer.getSize()`).

The increase in visual quality is, as expected, quite noticeable.

Using an Intel HD Graphics 530, there is a significant performance hit in the following examples:
- crossfade
- dof
- dof2
- ssaa - unbiased
- sao
- ssao

With a more powerful Radeon Pro 460, there is a slight performance hit just with the sao example (55 fps instead of 60).

One solution to keep these examples running smoothly as before could be to use DPR=1 when creating the renderer, i.e. they behave as before.

There are a bunch of other calls, outside post processing, to `renderer.getSize()` in the examples ...

`examples/js/effects/OutlineEffect.js`
`examples/js/effects/StereoEffect.js`
`examples/js/effects/VREffect.js`
`examples/js/Mirror.js`
`examples/js/nodes/utils/ResolutionNode.js`
`examples/js/renderers/WebGLDeferredRenderer.js`

and also
`src/renderers/webvr/WebVRManager.js`

I don't have VR hardware, so I cannot test them all.

**Comment by WestLangley** [comment]
Please, and we can see what the ramifications are.

**Comment by robertoranon** [comment]
Here it is: [#12206](https://github.com/mrdoob/three.js/pull/12206)
