### ISSUE TITLE
decals has something wrong when rotate mesh

### ISSUE THREAD

**Issue by trymoremore** [mrdoob/three.js#12191]
i set the mesh like this：mesh.rotation.set(0,20,0); and use decals .the result is something wrong:
![image2](https://user-images.githubusercontent.com/27277007/30418699-7ce5a870-9966-11e7-905f-9eff3ca904f1.png)

**Comment by Mugen87** [comment]
Can you test if the following statement solves the problem? Please insert this line
```javascript
n.transformDirection( mesh.matrixWorld );
```
after this [statement](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_decals.html#L204).

**Comment by trymoremore** [comment]
thank you very much!!! it has work!
