### ISSUE TITLE
utils.js: arrayMin missing from current build

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#12197]
##### Description of the problem 
[`arrayMin`](https://github.com/mrdoob/three.js/blob/dev/src/utils.js#L5-L19) is missing from the current build, while [`arrayMax`](https://github.com/mrdoob/three.js/blob/dev/src/utils.js#L21-L35) is [in there](https://github.com/mrdoob/three.js/blob/dev/build/three.js#L13341-L13353), even though they're both exported in `src/utils.js`.
I'm guessing because `src/utils.js` is missing from `src/Three.js` but `arrayMax` is imported elsewhere while `arrayMin` isn't used anywhere yet? I don't know enough about modules 😇

##### Three.js version
- [x] Dev

**Comment by Mugen87** [comment]
I think `arrayMin` and `arrayMax` are intended for internal usage only. They are no part of the public API.

BTW: You are correct. `arrayMin` is currently not used and therefore it's missing in the build.

**Comment by mrdoob** [comment]
> BTW: You are correct. `arrayMin()` is currently not used and therefore it's missing in the build.

But I think it's okay to leave there even if it's not being used at the moment.
