### ISSUE TITLE
Suggestion: refactor rayCaster API

### ISSUE THREAD

**Issue by xcmaya** [mrdoob/three.js#12190]
##### Description of the problem 

Now the rayCaster has a member property called `.linePrecision` for intersection precision with line object. However, the intersection precision with Points object is passed in the '.params' property. This makes the API style is not very consistent.

Is better to unify the precision for Points and Line intersection?

##### Three.js version

- [ ] Dev
- [x ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Yes. Would you like to propose a change?

**Comment by xcmaya** [comment]
My proposal:
1: Just use one parameter, called 'pickPrecision', to control intersection precision for all objects. 
2: Make  'pickPrecision' work on the screen coordinate system instead of 3D coordinate system. In most of time, many users intuitively think the pick precision in the pixel unit, not in the 3D coordinate system.

**Comment by Mugen87** [comment]
Solved via #18590.
