### ISSUE TITLE
exceptions in text example

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#12198]
If you go to https://threejs.org/examples/webgl_geometry_text_earcut.html#FF003E110#Schei%C3%9Fe! you get no text and this in the console:
> TypeError: textGeo.faces is undefined
> webgl_geometry_text_earcut.html:451:23

If you go to https://threejs.org/examples/webgl_geometry_text_earcut.html and type somehing, the text appears... Only to disappear when you click bevel button. And then there is the same error as above.

**Comment by Mugen87** [comment]
Good find! The example needs `TextGeometry` instead of `TextBufferGeometry` otherwise this [code](https://github.com/mrdoob/three.js/blob/master/examples/webgl_geometry_text_earcut.html#L447-L484) won't work.

**Comment by Mugen87** [comment]
BTW: The german word you used in your link is not very decent, you know 😆.

**Comment by makc** [comment]
there are two more text examples, I think, I did not check these, but it might be good idea to.
