### ISSUE TITLE
texture max size

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#12201]
It could be good idea to limit texture size by some user setting, not just round up to next power of two or use max value reported by system. Otherwise we get this:
![screen shot 2017-09-15 at 0 36 28](https://user-images.githubusercontent.com/242577/30458958-36ae6016-99ae-11e7-8048-3588de213531.png)

ios also says the max size is 4096, for example, but using it triggers visible bugs, so you dont want 4K textures there.

**Comment by mrdoob** [comment]
I was actually considering changing it to the previous power of two. That way people would be "penalized"/ encouraged to resize it properly. I often see people ignoring this.

**Comment by fernandojsg** [comment]
:+1: to convert it to the smaller POT

**Comment by mrdoob** [comment]
I'm confused:

https://github.com/mrdoob/three.js/blob/r79/src/renderers/webgl/WebGLTextures.js#L49-L50
https://github.com/mrdoob/three.js/blob/r79/src/math/Math.js#L144-L148

**Comment by makc** [comment]
funny thing I thought in this case max texture width reported by api was 8192, but it looks like r79 does not query the api. api actually says max width is 8191. so rounding down would actually take care of this.

it would still not help with ios situation.

**Comment by mrdoob** [comment]
> it would still not help with ios situation.

Yeah. That's an additional issue.

**Comment by RemusMar** [comment]
> it would still not help with ios situation.

A 6000x3000 texture indicates newbie stuff.
Talking about iOS (and mobile devices), anything above 2048x2048 comes with a significant performances drop.
So 4096x4096 and 8192x8192 are bad ideas anyway.

**Comment by mrdoob** [comment]
Actually, now that `makePowerOfTwo` is going down we should be good:
https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLTextures.js#L419-L425
