### ISSUE TITLE
PCDLoader incorrect colors from ascii PCD files

### ISSUE THREAD

**Issue by focaldepth** [mrdoob/three.js#12207]
##### Description of the problem 

The decoding of RGB colors in incorrect in PCDLoader when decoding ascii files..

 three.js/examples/js/loaders/PCDLoader.js

I am basing this fact on PCD files that display correctly using Debian version of pcl_viewer.

We need to treat the data as a 32 bit integer and the color byte order is reversed.

Here is a code fix for the problem:

```js
  //var c = new Float32Array( [ parseFloat( line[ offset.rgb ] ) ] );
  //var dataview = new DataView( c.buffer, 0 );
  //color.push( dataview.getUint8( 0 ) / 255.0 );
  //color.push( dataview.getUint8( 1 ) / 255.0 );
  //color.push( dataview.getUint8( 2 ) / 255.0 );

   var c = new Int32Array( [ parseInt( line[ offset.rgb ] ) ] );
   var dataview = new DataView( c.buffer, 0 );
   color.push( dataview.getUint8( 2 ) / 255.0 );
   color.push( dataview.getUint8( 1 ) / 255.0 );
   color.push( dataview.getUint8( 0 ) / 255.0 );
```

##### Three.js version

Latest as of 2017 - 09 -15

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [x ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

N/A

**Comment by Mugen87** [comment]
The mentioned code section is currently not executed by the official [example](https://threejs.org/examples/webgl_loader_pcd.html) because the corresponding file is in binary format. So maybe this code was never tested before.

Would you like to do a PR with your changes? Besides, it would be cool if you could add a simple `PCD` ascii file for testing purposes to `/examples/models/pcd/`.

**Comment by Mugen87** [comment]
I've tested this issue with a simple ascii file. The current implementation seems to be correct, the file loads with correct vertex colors.

see #12213

**Comment by Mugen87** [comment]
@focaldepth BTW: If i implement your proposed fix, the model does not load correctly.

**Comment by Mugen87** [comment]
@focaldepth Can you please share one of your `PCD` files that does not load with `PCDLoader` on your system.

**Comment by Mugen87** [comment]
Closing. We can reopen the issue if @focaldepth provides a file for testing.

**Comment by baba1472** [comment]
@Mugen87 is it possible to re-open this issue? I am building on top of ThreeJS using the PCDLoader and I am noticing also that the colors are not coming out correctly. I have attached two screenshots:
- The first is a full window  in Ubuntu showing the PCD in the correct colors

- The second shows a half window in Chrome using ThreeJS showing the incorrect colors

- The third is the PCD file used in the screenshots. The file extension was changed to .txt to be able to upload to Github

![screen shot 2018-09-26 at 12 09 44 am](https://user-images.githubusercontent.com/1800746/46058703-c0f28180-c121-11e8-84ad-01272d36afbb.png)

<img width="952" alt="screen shot 2018-09-26 at 12 09 14 am" src="https://user-images.githubusercontent.com/1800746/46058718-cb148000-c121-11e8-862b-20e800b2e022.png">


[pcd_0000000 copy.txt](https://github.com/mrdoob/three.js/files/2418191/pcd_0000000.copy.txt)

**Comment by baba1472** [comment]
I also noticed that the colors are different for the mentioned pcd example file from PCL when displayed in the installed PCL Viewer vs the ThreeJS PCDLoader. See below:

![screen shot 2018-09-26 at 11 00 03 pm](https://user-images.githubusercontent.com/1800746/46122745-21e08f00-c1e0-11e8-9c13-f40fe93a7c59.png)
<img width="952" alt="screen shot 2018-09-26 at 11 00 21 pm" src="https://user-images.githubusercontent.com/1800746/46122746-21e08f00-c1e0-11e8-814b-2b44b075e715.png">

**Comment by WestLangley** [comment]
The loader is not decoding the colors correctly. This appears to work:
```javascript
var rgb = parseFloat( line[ offset.rgb ] );
var r = ( rgb >> 16 ) & 0x0000ff;
var g = ( rgb >> 8 ) & 0x0000ff;
var b = ( rgb >> 0 ) & 0x0000ff;
color.push( r / 255, g / 255, b / 255 );
```
There may be a more-elegant solution.

Plus, it should be:
```javascript
material.vertexColors = THREE.VertexColors;
```

**Comment by baba1472** [comment]
Yup, that seems to fix it for ascii files, thanks!

**Comment by Mugen87** [comment]
@baba1472 Does it also work with the proposed fix of @focaldepth?

```js
var c = new Int32Array( [ parseInt( line[ offset.rgb ] ) ] );
var dataview = new DataView( c.buffer, 0 );
color.push( dataview.getUint8( 2 ) / 255.0 );
color.push( dataview.getUint8( 1 ) / 255.0 );
 color.push( dataview.getUint8( 0 ) / 255.0 );
```

**Comment by Mugen87** [comment]
Does this fix also work with the PCD file shown on this website?

http://pointclouds.org/documentation/tutorials/pcd_file_format.php

@focaldepth's proposed solution was not able to load this file

**Comment by baba1472** [comment]
@Mugen87 Yes it works, they both now show the Pointcloud logo in purple and green.
<img width="952" alt="screen shot 2018-09-27 at 11 05 49 am" src="https://user-images.githubusercontent.com/1800746/46159200-4fabef00-c245-11e8-9a73-68d17f240610.png">

**Comment by baba1472** [comment]
**Note**
I copied @WestLangley code into the ascii conditional of the PCDLoader.js file only, so I am unsure about the fix for the binary data conditional, but I assume it is similar.

**Comment by Mugen87** [comment]
Um, I wonder if there is a solution which does not require bitwise operations...

**Comment by baba1472** [comment]
Sure no problem. To remove bitwise operations, this seems to work as well:

`var rgb = parseFloat( line[ offset.rgb ] );
var r = rgb / 256 / 256 % 256;
var g = rgb / 256 % 256;
var b = rgb % 256;
color.push( r / 255, g / 255, b / 255 );`

**Comment by WestLangley** [comment]
Compare with the source code of `Color.setHex()`.

**Comment by baba1472** [comment]
I actually just noticed that the OP's solution (instead of 0, 1, 2 using 2, 1, 0) does work with my files as well as the sample file, and it works for both ascii and binary.

**ASCII**
```
var c = new Float32Array( [ parseFloat( line[ offset.rgb ] ) ] );
var dataview = new DataView( c.buffer, 0 );
color.push( dataview.getUint8( 2 ) / 255.0 );
color.push( dataview.getUint8( 1 ) / 255.0 );
color.push( dataview.getUint8( 0 ) / 255.0 );
```

**BINARY**
```
color.push( dataview.getUint8( row + offset.rgb + 2 ) / 255.0 );
color.push( dataview.getUint8( row + offset.rgb + 1 ) / 255.0 );
color.push( dataview.getUint8( row + offset.rgb + 0 ) / 255.0 );
```

**Comment by baba1472** [comment]
Actually I take that back, it works for binary but not always for ascii (works for the PCL sample PCD file for both though).

The safest solution seems to be the one @Mugen87 or I posted

**Comment by Mugen87** [comment]
Would you like to do a PR with @WestLangley's suggestion? In this way, the code is at least similar to the implementation of `Color.setHex()`.

**Comment by baba1472** [comment]
Sure I can, or @WestLangley can since it was his suggestion.

**Comment by WestLangley** [comment]
@baba1472 Feel free. I just offered some help. This code needs to be tested by the maintainers.

**Comment by baba1472** [comment]
@Mugen87 I don't seem to have permission to publish my branch, to then submit a PR.

**Comment by Mugen87** [comment]
Strange. How does your workflow look like? Maybe the following two guides might help a bit:

https://help.github.com/articles/fork-a-repo/
https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js

**Comment by baba1472** [comment]
Thank you, pull request made @Mugen87
