### ISSUE TITLE
Animation property binding for shader uniforms

### ISSUE THREAD

**Issue by jeremyabel** [mrdoob/three.js#12202]
Would be very useful to have, I think. Currently I can only do 'object.material.color', or any of the other material properties, but I cannot do 'object.material.uniforms.foo.value' when creating a PropertyBinding. I can create a PR for this if y'all think it'd be valuable.

**Comment by donmccurdy** [comment]
You can do this with a bit of hackery:

```js
mesh = new THREE.Mesh( geometry, material );
mesh.materialDotUniformsDotFrame = material.uniforms.foo;
var track = new THREE.NumberKeyframeTrack( '.materialDotUniformsDotFoo[value]', [ 0, 1, 2 ], [ 1, 0, 1 ] );
```

Here's a [JSFiddle](https://jsfiddle.net/donmccurdy/v6khdvz2/).

If you see a way to support `object.material.uniforms.foo.value` directly that would be great, but I'm worried it may not be easy to do cleanly.

**Comment by jeremyabel** [comment]
Oh man that is fantastically hacky and I love it! I was working on having it do it directly but it's not very clean. It's not any more gross than all the checks for "material" and "materials" and "bones" are, and the morph target ones, though.

**Comment by jeremyabel** [comment]
I'll close this, I don't want to clutter the issues up. I'd love to add this trick to the documentation for the animation system though. It seems really handy. @donmccurdy does that sound reasonable?

**Comment by donmccurdy** [comment]
Not sure if it should be included haha.. it certainly isn't obvious, but also not exactly a normal part of the API. Actually, I can't find any examples in the docs for creating a `KeyframeTrack` at all. Ideally at least the normal case, e.g. animating position, should be covered in the [Animation System](https://threejs.org/docs/#manual/introduction/Animation-system) docs.
