### ISSUE TITLE
How FBXLoader add lights to scene?

### ISSUE THREAD

**Issue by norangit** [mrdoob/three.js#12205]
##### Description of the problem 

I want to export lights to three.js from blender, but it dose not work. Is there a online demo or youtube demo? 

Thanks very much!

my code:

```
            var loader = new THREE.FBXLoader( manager );
            loader.load( '1234567.FBX', function( object ) {

                /* object.mixer = new THREE.AnimationMixer( object );
                mixers.push( object.mixer );

                var action = object.mixer.clipAction( object.animations[ 0 ] );
                action.play(); */

                scene.add( object );
                  
            }, onProgress, onError );
```

fbx file is attached.
[1234567.fbx.zip](https://github.com/mrdoob/three.js/files/1306039/1234567.fbx.zip)

 (dev)

##### Three.js version

- [ ] Dev
- [ ] r86

##### Browser

- [ ] Chrome

##### OS

- [x] Windows

**Comment by mrdoob** [comment]
#11949
