### ISSUE TITLE
Fails to load large terrain mesh exported from Blender as .json

### ISSUE THREAD

**Issue by viperscape** [mrdoob/three.js#12215]
##### Description of the problem 

Exporting large mesh from Blender to threejs using threejs exporter.
```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at \node_modules\three\build\three.js:33434:21
    at XMLHttpRequest.<anonymous> (\node_modules\three\build\three.js:30090:21)
```

Steps to repeat:
Blender:
1. Add new Mesh -> Grid
2. Grid subdivisions 100x100, radius size 100
3. Position x:100, y:-100, z:0
4. Add Mesh Material (Flat)
4. Export as threejs
5. Select type: Geometry, uint16array with Vertices,Faces,Normals,Uvs,Face Materials

If I do all these steps but keep subdivisions to 50x50, sized 100 it will load. 
Any idea what is going on? I cannot paste the raw json because it's too long for sites like pastebin

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Electron Application

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by viperscape** [comment]
Here it is
[terrain.json.txt](https://github.com/mrdoob/three.js/files/1308751/terrain.json.txt)

**Comment by viperscape** [comment]
Just realized uint16 array might be the issue here, I'll switch it up when I get a chance and see if it then loads

**Comment by donmccurdy** [comment]
Could you paste the `.blend` file too?

BTW if you zip up the file, you can drag it directly into the GitHub comment box.

**Comment by looeee** [comment]
I can't reproduce the error - your JSON file loads fine for me, using r87. Are you sure you are using the latest version from NPM?

![download](https://user-images.githubusercontent.com/5307958/30541521-f9561a4c-9ca5-11e7-9362-4403decc42ed.png)

**Comment by viperscape** [comment]
Ok I think I narrowed down the issue, I believe it's related to gulp copying the assets around and somehow truncating it occasionally, sigh. Thank you all for helping, you rock :)
