### ISSUE TITLE
WebGLRenderer .setViewport() and .setScissor() inverted coordinates

### ISSUE THREAD

**Issue by davdtm** [mrdoob/three.js#12210]
##### Description of the problem 

I've a rather complex application which looks not properly working after the commit 43ae8e4ef86bb11ce3c46dbe1e3e17f2a26f82bd. I see different issues because of such commit but the simplest to describe is that the geometry looks shifted few pixels up in the y direction. I've recently updated my three release from 83 to 87 and after a quite painful bisection I've found that my application gets broken after the reported commit (message: "WebGLRenderer: Added y swap to setViewport() and setScissor()." made on 8 Jun 2017) . It's possible (I'd say it's almost sure) that the commit is correct and I simply need to update something on my side, but I don't fully understand what such commit does and why such change has been pushed. Could someone explain me the reasons behind it?

thanks in advance

Dav

##### Three.js version

- [ x] r86

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
> It's possible (I'd say it's almost sure) that the commit is correct and I simply need to update something on my side

Yes. After that commit, `setViewport( x, y, width, height )` coordinate system now has the `0,0` on the top left.

**Comment by WestLangley** [comment]
@mrdoob Can you please explain why you make that change?

Not only is the measurement of `y` from the top instead of from the bottom, the point`( x, y )` is now the _upper left_ corrner of the rectangle rather than the bottom left.

**Comment by mrdoob** [comment]
> @mrdoob Can you please explain why you make that change?

I thought it was confusing. When using `setViewport()` I think using the classical 2D space (Y down) is more intuitive. Also, before that change, the user had to know the framebuffer height.

**Comment by WestLangley** [comment]
Hmm... IMHO, changing the convention seems confusing to me. I think sticking to the gl convention is most natural. That would be
```javascript
setViewport( left, bottom, width, height ); // measured from the lower left
```
As it is currently, the args are
```javascript
setViewport( left, top, width, height ); // measured from the upper left
```

**Comment by mrdoob** [comment]
This commit shows what this meant to the examples: https://github.com/mrdoob/three.js/commit/447f8e418903e2d5e79b195a5a4f4b680c3afb55

**Comment by WestLangley** [comment]
I tried to find a `getViewport()` method thinking that that would really be confusing, but I guess we don't have such a method...

**Comment by davdtm** [comment]
@mrdoob  and @WestLangley , thanks for your quick reply! Now it makes sense, I'll fix my application. However, may this change deserve to be explicitly highlighted within the migration guide? I think that others may get confused as well

**Comment by mrdoob** [comment]
@davdtm yeah, would you like to add it?

**Comment by WestLangley** [comment]
I'm hopeful @mrdoob will change his mind. Setting the viewport for the renderer now uses a different convention than setting the viewport for a render target.
```javascript
renderTarget.viewport.set( x, y, width, height ); 
```

**Comment by mrdoob** [comment]
Uh oh...

**Comment by WestLangley** [comment]
@mrdoob Please revert this change. This is not a canvas API. Let's adhere to the webGL convention.

https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/viewport
