### ISSUE TITLE
extend files such as 'THREE.OrbitControls', 'OBJLoader' not yet support es6 module

### ISSUE THREAD

**Issue by dyh333** [mrdoob/three.js#12226]
hi, @mrdoob . i found three now has build an es6 module file named 'three.module.js', it was great! 
while there are some other extend files such as 'THREE.OrbitControls', 'OBJLoader' and so on, has not yet support es6 module. 
has any plan for dealing it? 
thanks.

**Comment by Mugen87** [comment]
see #9562
