### ISSUE TITLE
3D object rendered result different from other 3D visualizing software

### ISSUE THREAD

**Issue by vinjohn** [mrdoob/three.js#12220]
##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Hi, guys, I recently encounter a really weird bug.

let me show you some pictures first.

pictures below are rendered result w.r.t same .obj mesh from different software.
1. from 3D builder in win10
![1](https://user-images.githubusercontent.com/9766597/30523271-39bd92bc-9c11-11e7-8f84-7c8c73894036.PNG)

2. from three.js
![2](https://user-images.githubusercontent.com/9766597/30523086-7292c66a-9c0d-11e7-9fe9-d90bb6435cac.png)

please ignore the color difference, you may notice the position of the box object is different and the file object falling to pieces.

I use OBJLoader to load this .obj file.

it's not the weird part yet, what confuse me is that this obj is a subset of another obj, and in this obj, it actually has 14 objects, and the box and the file is the only two have problems

I've also confirm with MeshLab and blender, results from  3D builder is right.

I've read a former issue post which mentioned winding order error. I am new to this, not sure if it is a winding order issue.

the obj file in the picture is zipped and attached.

Any help will be greatly appreciated!!
[test.zip](https://github.com/mrdoob/three.js/files/1309239/test.zip)

**Comment by WestLangley** [comment]
Please try [stackoverflow](https://stackoverflow.com/questions/tagged/three.js) or the [forum](https://discourse.threejs.org) first.
