### ISSUE TITLE
Blender json mesh, unexpected raycaster results

### ISSUE THREAD

**Issue by viperscape** [mrdoob/three.js#12229]
I was unable to figure this out in IRC, it seems like a bug. I have two meshes that are like planes, they are placed at 0,0,0 and 20,0,20 and they're both 20 units square. One is an import from blender as json (it's a basic grid or plane mesh) the other is a cubegeometry built in threejs. Running Intersection tests from a raycaster, the cubegeom reports identical Y values of 0, where the blender mesh reports seemingly random values, such as 6.549024078594812e-8, 1.2337679322627082e-8, or -3.065805458390969e-7

I'm curious if [this issue](https://github.com/mrdoob/three.js/issues/10111) is some how related.

Blender mesh and export attached
[plane mesh.zip](https://github.com/mrdoob/three.js/files/1315104/plane.mesh.zip)

Any ideas why the blender mesh reports various Y values? The X and Z values look fine

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Electron App

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Sorry, this is not a help site. Try [stackoverflow](https://stackoverflow.com/questions/tagged/three.js) or the [forum](https://discourse.threejs.org). Be sure to show your code when you ask a question.

**Comment by viperscape** [comment]
I understand, but I specifically stated that this seems like a bug. The reported Y axis is inaccurate. Thank you

**Comment by viperscape** [comment]
I just want to report that the ColladaLoader works fine, and reports proper Y axis information on the mesh coming out of Blender. So now it is no doubt in my mind a Blender->JSON error in the io_three exporter itself. I am sorry you closed this issue, as it is clearly a bug. Please reopen if you will
