### ISSUE TITLE
Problem with CanvasRenderer when using STL models

### ISSUE THREAD

**Issue by ipepe** [mrdoob/three.js#12228]
##### Description of the problem 

Hello everyone, we are having problem when generating previews using CanvasRenderer in phantomjs. Because phantomjs does not support WebGL. I would describe problem as artifacts in rendering mesh, I am suspecting `function painterSort` of `Projector.js` to be faulty. I reproduced problem here:

https://ipepe.github.io/threejs-software-vs-webgl/
**Warning! Two three.js instances created on this page are really heavy load on machine**

Source code: https://github.com/ipepe/threejs-software-vs-webgl/blob/master/index.html

Or please see screenshot below:

![screen shot 2017-09-19 at 11 37 28](https://user-images.githubusercontent.com/10695953/30586038-f8c09c90-9d2e-11e7-8584-bf0faf669dc5.png)

##### Three.js version
- [x] r87

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
WebGL capable machine for comparision to CanvasRenderer.

**Comment by WestLangley** [comment]
When using `CanvasRenderer`, you need to set

    material.overdraw = 0.5; // or some number between 0 and 1

This will help to alleviate the problem with the seams.

**Comment by WestLangley** [comment]
And don't try to render models with 225000 faces with CanvasRenderer.
