### ISSUE TITLE
Flickering geometry in webgl_geometry_extrude_shapes2

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#12234]
##### Description of the problem 
If you turn the camera in `webgl_geometry_extrude_shapes2`([r87](https://threejs.org/examples/webgl_geometry_extrude_shapes2.html), [dev](https://rawgit.com/mrdoob/three.js/dev/examples/webgl_geometry_extrude_shapes2.html)) till you face the back of the mesh, the smaller meshes can be seen flickering through the larger yellow mesh for a few seconds. If you keep the camera in motion, the flickering never stops.
Also, I'm getting a deprecation warning:  
`three.js:42911 THREE.Shape: .extrude() has been removed. Use ExtrudeGeometry() instead.`

##### Three.js version
- [x] Dev
- [x] r87

##### Browser
- [ ] All of them
- [x] Chrome (61.0.3163.91)
- [x] Firefox (55.0.2)
- [ ] Internet Explorer

##### OS
- [ ] All of them
- [x] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I removed the warning with a new PR. The mentioned z-fighting is caused by some overlapping geometry that is derived from the initial geo data. I'm not sure we need to fix this...
