### ISSUE TITLE
GLTFLoader: Animation with cubic spline interpolation not working

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#12233]
##### Description of the problem 

Pulling this over from https://github.com/aframevr/aframe/issues/3036. Each keyframe for the `scale` channel (for example) contains 9 floats. GLTFLoader creates KeyframeTracks incorrectly for cubic spline interpolation, the scale comes to `0 0 0`, and errors are thrown.

Linear interpolation works correctly.

[glTF cubic spline interpolation notes](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#appendix-c-spline-interpolation).

Assets:
- .gltf: https://s3.amazonaws.com/bug-figures/v2-locrotscale-cube-embedded-buffers.gltf
- .blend: https://s3.amazonaws.com/bug-figures/cube.blend

##### Three.js version

- [x] Dev
- [x] r87
- [] ...

**Comment by alexkowel** [comment]
Seems like the issue is in KeyframeTrack which incorrectly sets value size for CubicInterpolant

**Comment by donmccurdy** [comment]
Yes, although GLTFLoader is just blindly passing its input data into the KeyframeTrack constructor, which is probably wrong... we will need to look at how to convert from glTF's cubic spline representation to three.js's.

**Comment by donmccurdy** [comment]
Closing as duplicate of https://github.com/mrdoob/three.js/issues/11761
