### ISSUE TITLE
Vertical Line with Outline Postprocessing

### ISSUE THREAD

**Issue by nicorocky1986** [mrdoob/three.js#12238]
Hi,

Running chrome by selecting the graphics processor (for my notebook Nvidia GeForce 840m ) or running from a desktop PC with a similar graphics card, I see vertical lines when the object's outline is triggered.

I also see the problem in https://threejs.org/examples/?q=outline#webgl_postprocessing_outline

is there any option to remove these lines?

Here some code i use:
```js
  // postprocessing
            composer = new THREE.EffectComposer(renderer);

            var renderPass = new THREE.RenderPass(scene, camera);
            composer.addPass(renderPass);

            outlinePass = new THREE.OutlinePass(new THREE.Vector2(window.innerWidth, window.innerHeight), scene, camera);
            outlinePass.pulsePeriod = 2;
            composer.addPass(outlinePass);

            effectFXAA = new THREE.ShaderPass(THREE.FXAAShader);
            effectFXAA.uniforms['resolution'].value.set(1 / window.innerWidth, 1 / window.innerHeight);
            effectFXAA.renderToScreen = true;
            composer.addPass(effectFXAA);
            composer.addPass(outlinePass);


        function onMouseMove(event) {
            event.preventDefault();
            var rect = renderer.domElement.getBoundingClientRect();
            mouse.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
            mouse.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;
            raycaster.setFromCamera(mouse, camera);
            var intersects = raycaster.intersectObjects(cilindro.children);

            if (intersects.length > 0) {
                oggoutline = [];
                if (modificaattiva == true) {
                    oggoutline.push(intersects[0].object);
                }
                outlinePass.selectedObjects = oggoutline;
            }
            else {
                oggoutline = [];
                outlinePass.selectedObjects = oggoutline;
            }
        }
```

Here some scren-shot

![menu](https://user-images.githubusercontent.com/10629733/30658938-9cc1ae84-9e3c-11e7-83d5-7aaa5c0de116.jpg)
![screen_3](https://user-images.githubusercontent.com/10629733/30658939-9cc6d058-9e3c-11e7-97cd-1812708c9c8d.jpg)
![screen_1](https://user-images.githubusercontent.com/10629733/30658940-9cc994e6-9e3c-11e7-8025-263dfb27db6a.jpg)

Thank you

##### Three.js version

- [ x ] Dev
- [ ] r87
- [ ] ...

##### Browser

- [ ] All of them
- [ x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ x ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

- Notebook HP Pavilon
- HP Nvidia GeForce 840m

**Comment by nicorocky1986** [comment]
Wrong screen-shot this is what i see on the official example:

![screen-shot-official](https://user-images.githubusercontent.com/10629733/30659689-e33c78f6-9e3e-11e7-816e-5c039cd6a481.jpg)

**Comment by mrdoob** [comment]
Weird... Latest drivers?

**Comment by Mugen87** [comment]
@nicorocky1986 Closing. Just reopen the issue if the problem still occurs with latest drivers and browsers.
