### ISSUE TITLE
Accept 'normalized' values in typed BufferAttributes

### ISSUE THREAD

**Issue by Bsheridan12** [mrdoob/three.js#12241]
It would be ideal if we could call 
```javascript
geometry.addAttribute( 'color', new THREE.Uint8BufferAttribute( colors, 4, true ) );
```
rather than

```javascript
let colorAttr = new THREE.Uint8BufferAttribute( colors, 4 );
colorAttr.normalized = true;

geometry.addAttribute( 'color', colorAttr );
```

After reading the documentation on BufferAttributes I was a little confused for a minute as to why the former was not working and had to check the code. 

Obviously not a big issue but would be nice to have.

Thanks

**Comment by WestLangley** [comment]
That seems like a good idea. Would you like to file a PR?

**Comment by Bsheridan12** [comment]
Sure, added [here](https://github.com/mrdoob/three.js/pull/12242)
