### ISSUE TITLE
When then rotation mesh raycaster   intersections[0].face.normel error

### ISSUE THREAD

**Issue by shinseed** [mrdoob/three.js#12255]
##### Description of the problem 
![image](https://user-images.githubusercontent.com/13995240/30736954-5a27b66e-9fb7-11e7-911a-df2dcd325a04.png)
code
![image](https://user-images.githubusercontent.com/13995240/30736971-6e4664f6-9fb7-11e7-9030-9bd7802d5d1d.png)
In the right direction
![image](https://user-images.githubusercontent.com/13995240/30737026-a9d8b1f4-9fb7-11e7-8c98-ec3c28031197.png)

##### Three.js version

- [ ] Dev
- [1] r87
- [ ] ...

##### Browser

- [x] All of them
- [1 ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [1 ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This problem is related to the corresponding example and should already solved in `dev`.

see #12194

**Comment by shinseed** [comment]
thanks！ @Mugen87
