### ISSUE TITLE
improve blender exporter UI

### ISSUE THREAD

**Issue by cg-cnu** [mrdoob/three.js#12259]
Hey guys, 

Hope this is the place to talk about the blender exporter. If not feel free to point me to the right place.
I have been using blender exporter for a while and thought we can clean up the ui a bit.

Here is the current ui vs the modified 

![image](https://user-images.githubusercontent.com/2767425/30745634-8ff79cf2-9fc4-11e7-8939-4faad3f45564.png)

Did I got the grouping right? Feel free to comment and give ideas. 
Here is the [code](https://github.com/cg-cnu/three.js/tree/blender-exporter-ui), if you wanna have a look. If it works, I will do a pr.

Thanks :smile:

**Comment by Mugen87** [comment]
Beautiful! Much better than before :+1:

**Comment by mrdoob** [comment]
Super beautiful!
