### ISSUE TITLE
Strange shading behaviour

### ISSUE THREAD

**Issue by croraf** [mrdoob/three.js#12253]
Where does the vertical shadow come from (I'm using BasicShadowMap)? https://jsfiddle.net/23br8m3u/

![image](https://user-images.githubusercontent.com/19698636/30715852-159a837c-9f18-11e7-8c69-144bbd6621d9.png)

**Comment by WestLangley** [comment]
Please use stackoverflow or the forum for help.

**Comment by croraf** [comment]
This just looks wrong: https://jsfiddle.net/bxnb2sxq/
Is this the way Basic shadows work, or is it a bug?
