### ISSUE TITLE
Ray.intersectPlane can return a point not on the plane

### ISSUE THREAD

**Issue by williame** [mrdoob/three.js#12277]
##### Description of the problem 

A ray that intersects a plane should return an intersection point on the plane.

This test:

	var y = 3;
	var plane = new THREE.Plane(new THREE.Vector3(0, 1, 0), y);
	var ray = new THREE.Ray(new THREE.Vector3(499.99999999999994, 800.0000000000001, 1299.9999999999998),
		new THREE.Vector3(-0.7109099746692112, -0.5659885650405765, -0.41744934082967555));
	var hit = ray.intersectPlane(plane);
	console.log("ray.intersectsPlane", ray.intersectsPlane(plane));
	console.log("hit", hit);
	console.log("hit y", hit.y, " != ", y);

Prints:

    ray.intersectsPlane true
    floor.js:92 hit Vector3 {x: -508.60820327430287, y: -3.0000000000001137, z: 707.7410015126403}
    floor.js:93 hit y -3.0000000000001137  !=  3

The plane is at 3y, and the hit is -3 and a bit!

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
see  #10957, especially this [comment](https://github.com/mrdoob/three.js/issues/10957#issuecomment-285072930)

The issue with the decimal places is due to floating point inaccuracy.

**Comment by WestLangley** [comment]
>The plane is at 3y,

You are beginning with a false premise. The plane passes through ( 0, - 3, 0 );
```javascript
distanceToPoint: function ( point ) {

	return this.normal.dot( point ) + this.constant;

},
```
