### ISSUE TITLE
the error of using lightmap

### ISSUE THREAD

**Issue by trymoremore** [mrdoob/three.js#12270]
i use the lightmap to add shadow to the model,but the result is error,
the setting of js :
"mapLight" : "Q4.jpg",
and the setting of html:
 for ( var i = 0; i < materials.length; i ++ ) {
            	materials[ i ].lightMapIntensity =0.75;
            	}
geometry.faceVertexUvs[ 1 ] = geometry.faceVertexUvs[ 0 ];
the result:
![image1](https://user-images.githubusercontent.com/27277007/30782176-88d99c94-a15f-11e7-95d5-4d3bef715889.png)

i set down the lightMapIntensity,the result is normal ,but the shadow is disapperar:
![image2](https://user-images.githubusercontent.com/27277007/30782195-ac07a2ce-a15f-11e7-9e06-0d3d3e716e26.png)

**Comment by WestLangley** [comment]
Lightmaps in three.js are treated as a source of light. They are purely additive to the total indirect diffuse light; they do not darken or attenuate light.

Only ambient occlusion maps (aoMap) darken; they attenuate total indirect diffuse light.
