### ISSUE TITLE
Under the orthogonal camera, there is a problem with the halo

### ISSUE THREAD

**Issue by FishOrBear** [mrdoob/three.js#12272]
I tried using a OrthographicCamera
in https://threejs.org/examples/webgl_lights_physical
I do not know if this is a bug

```javascript
let height = 2;
let aspec = window.innerWidth / window.innerHeight;
camera = new THREE.OrthographicCamera(-2, 2, 2, -2,
    -1000, 1000);
camera.left = aspec * height / -2;
camera.right = aspec * height / 2;
camera.bottom = height / -2;
camera.top = height / 2;

camera.position.x = -4;
camera.position.z = 4;
camera.position.y = 2;
camera.updateProjectionMatrix();
```

![image](https://user-images.githubusercontent.com/19372111/30790405-570724e6-a1de-11e7-8ea9-be52e68153f4.png)

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser
- [x] Chrome

##### OS
- [x] Windows

**Comment by WestLangley** [comment]
I assume you are referring to the long, narrow, white highlight. Correct?

I am unable to reproduce this on a mac.

**Comment by FishOrBear** [comment]
@WestLangley  
Yes i modified it into a quadrature camera and tried to move + rotate it, there would be such a problem.
`long, narrow, white highlight.`

**Comment by WestLangley** [comment]
Are you able to reproduce the problem with a different computer?

**Comment by FishOrBear** [comment]
I reproduce the problem on other windows computers.

**Comment by Egyptionl** [comment]
OrthographicCamera don't render Jsonloader object from blender. only PerspectiveCamera work 
is there some solution ?

**Comment by WestLangley** [comment]
@FishOrBear Can you reproduce the problem with a perspective camera?

**Comment by FishOrBear** [comment]
@WestLangley  Perspective camera can not reproduce the problem.

**Comment by FishOrBear** [comment]
OrthographicCamera
![image](https://user-images.githubusercontent.com/19372111/30845417-de42d602-a2c5-11e7-8752-535c0bddf2df.png)


PerspectiveCamera
![image](https://user-images.githubusercontent.com/19372111/30845426-e6406ab8-a2c5-11e7-8d51-58f750a20f7a.png)

**Comment by FishOrBear** [comment]
@Egyptionl   
 I suggest you provide an example to illustrate the problem.
http://jsfiddle.net/

**Comment by WestLangley** [comment]
Sorry, I have no idea what you are doing. Perhaps someone else can address this.

**Comment by Mugen87** [comment]
@FishOrBear I'm also unable to reproduce. Can you provide a live version (maybe a [fiddle](https://jsfiddle.net/f2Lommf5/)) that shows the visual error?

**Comment by FishOrBear** [comment]
@Mugen87 
hi This is a simple example   https://jsfiddle.net/q65t62k9/

I changed it `OrbitControls.js`   So I control the camera

For the sake of simplicity I have embedded the code directly.

**Comment by WestLangley** [comment]
What you are seeing is a distortion of the specular highlight due to the orthographic projection.

This is not a three.js bug.

Also, I suggest you avoid a negative near plane. See [this SO post](https://stackoverflow.com/questions/17558085/three-js-orthographic-camera/17567292#17567292).

**Comment by clainkey** [comment]
Are you sure it's not a bug?
lights_template.glsl does `geometry.viewDir = normalize( vViewPosition );`
but under orthographic projection shouldn't it be `geometry.viewDir = vec3(0, 0, 1);`
I used firefox's shader editor to replace that one line in the floor's shader and this is the result: 
![screenshot from 2017-10-02 16-53-41](https://user-images.githubusercontent.com/32471105/31104768-c2ef8bac-a793-11e7-8a3d-1b03d6654f00.png)
