### ISSUE TITLE
Weird behavior when rendering to render target in onBeforeRender

### ISSUE THREAD

**Issue by nopjia** [mrdoob/three.js#12284]
See JSFiddle: http://jsfiddle.net/9nLf96ys/

### Context
I'm building a "screen" object, which renders whichever way it's facing onto itself. I've got everything working alright, but I want to take advantage of the `.onBeforeRender` callback and get rid of an extra update call when using the object.

### To reproduce the bug:
1. Go to JSFiddle: http://jsfiddle.net/9nLf96ys/
1. Uncomment `renderToScreen()` under `onBeforeRender()`
1. Comment out `myScreen.renderToScreen()` under `animate()`
1. Run the code
1. You should get `[.Offscreen-For-WebGL-0x7fee2b002a00]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.`

### Investigation
I've tried commenting out both `renderer.clearTarget()` and `renderer.render()` to find out that the error is coming from both cases. I think the problem is coming from the fact that I'm calling these two functions inside another already-ongoing `render()`. When `renderer.setRenderTarget()` is called, the same render target must have already been bound to a material that is about to be rendered by the outer `render()` function, and thus the error is thrown. 

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Why do you claim this is a three.js bug?

**Comment by nopjia** [comment]
Unless you spot a mistake in my code, then yes. 
I should be able to arbitrarily call `renderer.render()` inside `onBeforeRender()` without any unexpected side effects. Just the fact that I move the same function from `animate()` to `onBeforeRender()` should not cause the renderer to behave differently.

**Comment by WestLangley** [comment]
Your error message is telling you the problem with your code.

Also, it is too late to do a visibility test in `onBeforeRender()`.

**Comment by nopjia** [comment]
> it is too late to do a visibility test in onBeforeRender().

Visibility test is for the "inner" `renderer.render()` pass. MyScreen removes itself from the scene before it renders the scene again. Before I did the visibility test, I was getting the same error even in the case without the `onBeforeRender()` method, but I was still getting the correct result. After I disabled visibility, the error went away in the case where I run the function in animate(). So I know my visibility test is working.

> Your error message is telling you the problem with your code.

The error tells me I'm using same texture I'm rendering to. According to my answer above, I should be correctly removing the object that is using that texture from the scene, for the *inner* render call. 

Still, let's assume that doesn't work and my code is wrong, we can try something else. In JSFiddle, we can comment out line 12 `this.material.map = this._target.texture;` to make sure we're *not* using that texture at all. Once we run this code, the error *does* go away but I get the same buggy behavior, that objects in the scene is disappearing. From this experiment, I am convinced that the error is in fact *not harmful* as I have found out in the first paragraph. 

My hypothesis is that drawing to a render target inside `onBeforeRender` causes really weird internal states for the WebGLRenderer.

**Comment by WestLangley** [comment]
>My hypothesis is that drawing to a render target inside onBeforeRender causes really weird internal states for the WebGLRenderer.

You could be right. @ProPuke had to modify the renderer to support recursion in #12033.

**Comment by mrdoob** [comment]
You forgot to reset the `RenderTarget`.

```js
    renderToScreen(renderer, scene) {
        this.visible = false;
        renderer.clearTarget(this._target, true, true, false);
        renderer.render(scene, this._camera, this._target, false);
        renderer.setRenderTarget( null );
        this.visible = true;
    }
```

**Comment by nopjia** [comment]
Nailed it. Thanks @mrdoob !
So I guess inside render() the renderTarget is stateful. I think to be completely safe, I should set it back to whatever it was before.
```
renderToScreen(renderer, scene) {
    this.visible = false;
    var oldRenderTarget = renderer.getRenderTarget();
    renderer.clearTarget(this._target, true, true, false);
    renderer.render(scene, this._camera, this._target, false);
    renderer.setRenderTarget(oldRenderTarget);
    this.visible = true;
}
```

**Comment by WestLangley** [comment]
Nice job, @mrdoob!

**Comment by mrdoob** [comment]
😅
