### ISSUE TITLE
THREE.Volume is not a constructor

### ISSUE THREAD

**Issue by tymiao1220** [mrdoob/three.js#12282]
I got error `THREE.Volume is not a constructor` when I am using NRRDLoader.js to parse nrrd file.

here is the code in NRRDLoader.js 312 line
`var volume = new THREE.Volume();`

And I am using the source code on github, and up-to-date

Chrome is used

**Comment by Mugen87** [comment]
Have you included the following files?

https://github.com/mrdoob/three.js/blob/dev/examples/webgl_loader_nrrd.html#L54-L55
