### ISSUE TITLE
Function.prototype.name bug in Internet Explorer

### ISSUE THREAD

**Issue by ben-girardet** [mrdoob/three.js#12294]
##### Description of the problem 

I'm using THREE in an Aurelia-CLI project. It means it is loaded using modules and RequireJS. It works all fine except in Internet Explorer (tested in IE 11).

The code that breaks is the following (in the polyfill section at the top, lines 42-57) in the [/build/three.js](https://raw.githubusercontent.com/mrdoob/three.js/dev/build/three.js) file

```js
if ( Function.prototype.name === undefined ) {

  // Missing in IE
  // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

  Object.defineProperty( Function.prototype, 'name', {

    get: function () {

      return this.toString().match( /^\s*function\s*([^\(\s]*)/ )[ 1 ];

    }

  } );

}
```

It returns the `can't redefine non-configurable property "name"` error.

Following [this post](https://stackoverflow.com/questions/6903762/function-name-not-supported-in-ie) I've tried to replace the code above with:

```js
if (!(function f() {}).name) {
  Object.defineProperty(Function.prototype, 'name', {
    get: function() {
      var name = (this.toString().match(/^function\s*([^\s(]+)/) || [])[1];
      // For better performance only parse once, and then cache the
      // result through a new accessor for repeated access.
      Object.defineProperty(this, 'name', { value: name });
      return name;
    }
  });
}
```

**And it fixes the problem !**

=> It seems that the polyfill code currently used in /build/three.js doesn't work well. Is it possible to replace this code for future builds ?

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Would change the check to this make any difference?

```js
if ( 'name' in Function.prototype === false ) {
```

Or

```js
if ( Function.prototype.hasOwnProperty( 'name' ) === false ) {
```

**Comment by ben-girardet** [comment]
I confirm that only changing the `if` is enough. 

```js
if ( 'name' in Function.prototype === false ) {
```

it the way to go!

**Comment by mrdoob** [comment]
Fixed. Thanks!
