### ISSUE TITLE
FBXLoader obj names miss the following characters: : - _

### ISSUE THREAD

**Issue by VI-GE** [mrdoob/three.js#12295]
##### Description of the problem 

When I check over the object names  after obtaining a scene using FBXLoader and compare to the ones I get from the FBX Autodesk SDK ones I notice missing the following characters: - _ :
The peculiar thing is that they don't seem to be missing in a consistent manner, sometimes I find underscores in the name.

I glanced over the code and the only thing I can think of is the 
line s = decodeURIComponent( escape( s ) );
inside getString

I haven't tested yet to sew how the data is before being handed to decodeURIComponent but I suspect that might be it.

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
See [FBXLoader:1734](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/FBXLoader.js#L1734):

```js
model.name = node.attrName.replace( /:/, '' ).replace( /_/, '' ).replace( /-/, '' );
```

That could be replaced with:

```js
model.name = PropertyBinding.sanitizeNodeName( node.attrName );
```

Colons must be replaced (they'll cause issues with animation) but underscores and dashes can be safely left alone.

**Comment by VI-GE** [comment]
@donmccurdy very interesting, I have ctrl+f the code but didn't find that.

What is the reason that colons will cause issues with animation? the string is used for anything in particular? or it causes issues when referencing an url?

**Comment by donmccurdy** [comment]
> What is the reason that colons will cause issues with animation? the string is used for anything in particular?

The [animation system](https://threejs.org/docs/#manual/introduction/Animation-system) associates animation clips with particular objects using their names, in a CSS selector-like syntax:

```
hand_left.material.color
```

Names may contain only letters, numbers, dashes, and underscores.

> Sorry @donmccurdy that code is related to model.name but I was talking about the name inside each Object3D

The code applies to all scene graph nodes, which could include Mesh, Object3D, Camera, Light, etc.

**Comment by VI-GE** [comment]
@donmccurdy  I see, could you perhaps show me the code/line number of this limitation in the animation code?

Thank you.

**Comment by looeee** [comment]
@VI-GE it's not a limitation, it's the way the animation system finds which property to animate. 

[PropertyBinding.parseTrackName](http://threejs.dev/docs/#api/animation/PropertyBinding.parseTrackName) is the place to start if you want to see how it works.
