### ISSUE TITLE
objectloader not working after switching from Canvasrenderer to WebGLRenderer

### ISSUE THREAD

**Issue by BenPav** [mrdoob/three.js#12299]
##### Description of the problem 

I had a working model that had a transparency issue when the model overlapped.  I was told this was a limitation of the CanvasRenderer and switching to the WebGL renderer would fix this issue.  After switching, my model doesn't show up at all.  The relevant code is below: 

      renderer = new THREE.CanvasRenderer();
				renderer.setPixelRatio( window.devicePixelRatio );
				renderer.setSize( SCREEN_WIDTH, SCREEN_HEIGHT );
				container.appendChild( renderer.domElement );
                var loader = new THREE.ObjectLoader();
                loader.load("../js/lights.json", function(object) {
                    
                       var material = new THREE.MeshBasicMaterial( { color: 0x333333 } );
                       object.traverse( function ( child ) {
                        if ( child instanceof THREE.Mesh ) {
                            child.material = material;
                            child.geometry.computeFaceNormals();
                            child.material.overdraw = 0.5
                        };  
                       });
                       object.scale.set(3, 3, 3);
                       object.position.x = 1;
                       object.position.y = 1;
                       object.position.z = 1;
                       object.rotation.set( 25, 25, 25 );
                       scene.add( object );
                       var helper = new THREE.BoxHelper( object );
                            scene.add( helper );
                    },

                    function (xhr) {

                        console.log((xhr.loaded / xhr.total * 100) + '% loaded');
                    },
                      //if download fails
                    function (xhr) {

                        console.error('An error happened : ' + xhr);
                    }
                );`

The model can be downloaded here.

https://www.dropbox.com/s/r78rcfwbbjcp4l3/lights.json?dl=0

##### Three.js version

- [ ] Dev
- [X] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
I've just tested your model and it's working fine for me, so this is not a bug. If you need help try asking over on the forum: discourse.threejs.org
