### ISSUE TITLE
objectloader not working after switching from Canvasrenderer to WebGLRenderer

### ISSUE THREAD

**Issue by BenPav** [mrdoob/three.js#12296]
##### Description of the problem 

I had a working(abliet buggy) object from Blender exported and loaded with the Object Loader.  I was told the WebGL renderer can solve the issues with some overlap transparency.  However, once I switched the renderer, the object is no longer showing up. No error messages in the Console either.

##### Three.js version

- [ ] Dev
- [X] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by makc** [comment]
do you really think you have included enough information )
