### ISSUE TITLE
The threejs application ran for a period of time the phone was very hot

### ISSUE THREAD

**Issue by shunzizhan** [mrdoob/three.js#12293]
I was learning about threejs recently, but I found that on mobile devices, about 5 minutes of browsing the web, the phone started to heat up, especially on the iPhone, because the requestAnimationFrame didn't stop asking for it? Can it be optimized? I would appreciate your help

**Comment by Mugen87** [comment]
It is quite normal that interactive 3D web applications utilize `requestAnimationFrame` to create infinite render loops. But sometimes it can make sense to only render the scene if something has changed (e.g. the view position). The following example renders the scene if the corresponding controls detect a `change` event. That means the user actually performs an input operation.

https://threejs.org/examples/?q=sky#webgl_shaders_sky

**Comment by shunzizhan** [comment]
Meaning it's normal for the phone to be hot?

**Comment by Mugen87** [comment]
It's pretty usual that devices warm up when they execute graphic intensive applications. But terms like "warm" or "hot" are subjective in general. Does it hurt when you hold the iPhone in your hand?

**Comment by makc** [comment]
[iphone is able to detect overheating and shut down since 2009](https://www.pcmag.com/article2/0,2817,2349598,00.asp). if it does not do it, it follows its temperature is normal by apple standards.

**Comment by VI-GE** [comment]
I don't think this issue should remain opened, it's a noob question that pollutes the conversation.

Please close it.

**Comment by Mugen87** [comment]
This can also be said more politely.
