### ISSUE TITLE
Convert "View Source" button to a link on examples section

### ISSUE THREAD

**Issue by martinjoiner** [mrdoob/three.js#12305]
When browsing the examples section I often want to open the source code in a new tab but I can't because the "View Source" button is a JavaScript controlled HTML button. 

I am offering to fork, fix and create a pull request to just change this to a anchor tag (still visually styled like a button) so that users can right-click/rollerball-click to open in a new tab/window. 

Just gimme the thumbs up and I will do the work.

**Comment by mrdoob** [comment]
Go for it 👍
