### ISSUE TITLE
raycaster.intersectObjects not working for gltf model

### ISSUE THREAD

**Issue by harry-liu** [mrdoob/three.js#12303]
##### Description of the problem 

I add a gltf format model to scene, and it shows. when i try to get intersects by 
raycaster.intersectObjects( scene.children )
its not working

it worked on obj format model

##### Three.js version

- [x] Dev
- [*] r87
- [x] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This is not a help site. Please use stackoverflow or the [forum](https://discourse.threejs.org/).
