### ISSUE TITLE
OBJLoader2 not loading Material properly

### ISSUE THREAD

**Issue by jtoribiop** [mrdoob/three.js#12324]
##### Description of the problem 

I have a OBJ/MTL created with ifcconverter from a IFC file.

When I use OBJLoader it works fine.
![image](https://user-images.githubusercontent.com/29660134/31132714-23228d32-a823-11e7-88f9-4310e9662807.png)

But if I use OBJLoader2...
![image](https://user-images.githubusercontent.com/29660134/31132652-fb3e248e-a822-11e7-9eea-b6697aa7a02e.png)

I use the lastest realease (https://github.com/kaisalmen/WWOBJLoader) but it didn´t work too.

I need OBJLoader2 beacuse I work with big files.

Files: [obj_mtl_files.zip](https://github.com/mrdoob/three.js/files/1352775/obj_mtl_files.zip)

##### Three.js version

- [ ] Dev
- [ ] r87
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by kaisalmen** [comment]
Hi @jtoribiop the material names contain `/`. Material name parsing (`usemtl`) does not expect that and therefore only uses part of the material name. I will fix that.

**Comment by kaisalmen** [comment]
Fix is available, but have to check there are no regressions:

**Comment by kaisalmen** [comment]
No regressions found, but fixed an additional bug in line processing (`l`) I found by accident.
