### ISSUE TITLE
FBXLoader does not pay attention to TimeMode

### ISSUE THREAD

**Issue by ignazioa** [mrdoob/three.js#12332]
##### (fixed) framerate is hardcoded to 30

Both TimeMode and TimeProtocol (FBXTree.GlobalSettings) are parsed correctly but fps are hardcoded to 30 in several places in the code.
As a result animations with different (fixed) frame-rates do not play correctly (nor they have the correct number of frames).

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
Yeah, I've been working on this but haven't finished it yet. It's on the to do list though!

**Comment by ignazioa** [comment]
Great to hear you are working on this 👍 I'll keep my workaround in for now
Here you go a test file which only contain an animation at 60 fps
[test_60fps.zip](https://github.com/mrdoob/three.js/files/1356310/test_60fps.zip)
I'll search for a better example with a mesh.

**Comment by looeee** [comment]
Thanks! What's your workaround btw?

**Comment by ignazioa** [comment]
Just a quick hack that serve my puropuse, see below:
```
//inside parseAnimations()
var TimeModeEnum = [30, 120, 100, 60, 50, 48, 30 ];			
if ( 'GlobalSettings' in FBXTree && 'TimeMode' in FBXTree.GlobalSettings.properties ) 
        fps = TimeModeEnum[FBXTree.GlobalSettings.properties.TimeMode.value];

var returnObject = {
        curves: new Map(),
        layers: {},
        stacks: {},
        length: 0,
        fps: fps,
        frames: 0
};
//and then reference animations.fps instead of hardcoding 30fps
```

**Comment by looeee** [comment]
Looks good - I've been doing something similar, but I haven't tested it enough to see if there are problems. 

The other issue is that there are a few more enums to support. The full list of is [here](http://docs.autodesk.com/FBX/2014/ENU/FBX-SDK-Documentation/index.html?url=cpp_ref/class_fbx_time.html,topicNumber=cpp_ref_class_fbx_time_html29087af6-8c2c-4e9d-aede-7dc5a1c2436c).

I really don't understand why they can't just use a float for framerate and support all of them at once 😆 

But anyway... the ones I'm having difficulty with are 

* **eFrames1000:** 1000 milli/s (use for date time) - perhaps this means 1fps? 
* **eCustom:**  Custom frame rate value (not sure how to test this as I have no models using it) 

Then there is 
* **eNTSCDropFrame:**  is used for broadcasting operations where clock time must be (almost) in sync with time code. To bring back color NTSC time code with clock time, this mode drops 2 frames per minute except for every 10 minutes (00, 10, 20, 30, 40, 50). 108 frames are dropped per hour. Over 24 hours the error is 2 frames and 1/4 of a frame. A time-code of 01:00:03:18 equals a clock time of 01:00:00:00

And a couple of others like this, which I guess explain the use of enums... but I think we can ignore these and just set this equal to eNTSC

**Comment by ignazioa** [comment]
My comments here below:

eFrames1000: same understanding you have, should be 1fps.
eCustom: this could be interesting, probably would require support for FrameRate property.
eNTSCDropFrame: given my understanding, this would probably require a more complex implementation on how frame time is reconstructed. I agree that having it equal to eNTSC could be a best effort implementation as today (probably good for all practical threejs cases :D )

**Comment by ignazioa** [comment]
@looeee Just realized that TimeMode = eDEFAULT_MODE = 0 may hide fps different than 30. In my understanding in such cases a fixed frame rate can be derived as max_frame_number/timestamp_interval

**Comment by looeee** [comment]
@ignazioa good to know. Do you have any models that use this method for determining frame rate so I can test? If not I'll try and create some myself.

**Comment by liubgithub** [comment]
good idea,I have solved may problem!

**Comment by ignazioa** [comment]
@looeee Here you are! Hope it helps :)
[test_defaulttimemode.zip](https://github.com/mrdoob/three.js/files/1386907/test_defaulttimemode.zip)

**Comment by looeee** [comment]
@ignazioa I don't see any model when I load that file ( with any loader ) - it looks like there should be a character called RokokoGuy?

**Comment by ignazioa** [comment]
@looeee I am afraid that's correct, the file only contains animation. (sorry, was the only example I found lying around)

**Comment by looeee** [comment]
Closing this for now. It's hard to tell for sure without a visible model, but far as I can see the animation is now parsed correctly.
