### ISSUE TITLE
Enhancement: Generalize cube shader by simplifying it

### ISSUE THREAD

**Issue by EliasHasle** [mrdoob/three.js#12330]
Just mentioning my recent question on SO: https://stackoverflow.com/questions/46509919/perspective-projection-of-glsl-texturecube-on-arbitrary-geometry-from-same-origi

I found the solution too. _transformDirection_ was a PITA. With just using the world position as a direction (avoiding _#include common_ too, as a bonus), the cube texture could be applied to any mesh without getting distorted (I will be using this in the process of generating correct image warping for multiprojector setups). Of course, this doesn't account for cases when the user wants to rotate the cubemap, but neither does the current shader, ref. #11103 (unless I have missed something).

And the normalization can be removed too. It is both unnecessary and useless, AFAICS. Useless because the interpolated vectors are not in general normalized, and unnecessary because textureCube accounts for unnormalized vectors. :-)

Will my proposed change have any (bad) unintended consequences? Such as breaking other legitimate uses of the current shader?

**Comment by WestLangley** [comment]
>Will my proposed change have any (bad) unintended consequences?

Skyboxes can be offset from the origin. The current code allows for that; yours does not.

**Comment by EliasHasle** [comment]
Hm. But if one wants do do transforms on the cube, why not just sample the texture using interpolated vertex position instead (and project vertices to screen the standard way)? (I guess that is how it works when one makes a cube with a cubetexture (basic material).) I thought the point of the cube shader would be to just sample using the world position, but then I may be wrong. My use case is kind of narrow, anyway.
