### ISSUE TITLE
OrbitControls - are camera instanceof checks still necessary?

### ISSUE THREAD

**Issue by shelbyspeegle** [mrdoob/three.js#12339]
##### Description of the problem 

`OrbitControls` has some `instanceof` checks in the dolly and pan functions.

these check `scope.object` against the classes `THREE.PerspectiveCamera` and `THREE.OrthographicCamera`.

could these checks be replaced with `scope.object.isPerspectiveCamera` and `scope.object.isOrthographicCamera`?

snippet from `threejs/examples/js/controls/OrbitControls.js`:
```
function dollyOut( dollyScale ) {

	if ( scope.object instanceof THREE.PerspectiveCamera ) {

		...

	} else if ( scope.object instanceof THREE.OrthographicCamera ) {

		...
```

this check was failing for me because i had two `PerspectiveCamera` classes running around during a conversion to direct ES6 imports (threejs internal classes using `PerspectiveCamera` from `three.module.js`, and my project using from `three/src/cameras/PerspectiveCamera`), which is my own issue, but i am wondering if switching to using class flag is more appropriate.

##### Three.js version

- [x] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> could these checks be replaced with scope.object.isPerspectiveCamera and scope.object.isOrthographicCamera?

I like this suggestion.
