### ISSUE TITLE
Feature: properly reset context for use by other renderer

### ISSUE THREAD

**Issue by ivanpopelyshev** [mrdoob/three.js#12338]
Sometimes people use 2d and 3d renderers on the same context. 

This is the demo of usage pixi + threejs: 
Using renderTarget: https://jsfiddle.net/c34p532r/24/
Without renderTarget: https://jsfiddle.net/xyL1sv02/

The problem is that simple `renderer.state.reset()` doesnt do the job, as seen here: https://jsfiddle.net/gle6/c34p532r/23/

Need an extra operation with FrameBuffer:

```js
renderer.setRenderTarget(null);

//or from the renderer

_currentRenderTarget = null;
```

The question is: shall we add "reset" method to renderer itself that does both things? I can make a PR for it.

**Comment by ivanpopelyshev** [comment]
This PR in pixi.js was merged yesterday, 05 oct 2017: https://github.com/pixijs/pixi.js/pull/4344/files

**Comment by makc** [comment]
> The problem is that simple renderer.state.reset() doesnt do the job, ...
> Need an extra operation with FrameBuffer:
> renderer.setRenderTarget(null);

how is it a problem, if you can actually do it =D it's not like WebGLProperties not being exposed (at some point, I think you can read them now).

**Comment by ivanpopelyshev** [comment]
The problem is that `reset` doesnt reset whole state, only a part of it, so I want special function in renderer itself that for sure resets everything and has "Use it for integration with other libs" in jsdoc.

Or we have to do something about `_currentRenderTarget` being hidden in a context.

**Comment by makc** [comment]
> Or we have to do something about _currentRenderTarget being hidden in a context.

I don't get it?

![screen shot 2017-10-09 at 19 13 49](https://user-images.githubusercontent.com/242577/31350084-0f4ca11e-ad26-11e7-880c-672af89101d4.png)

**Comment by ivanpopelyshev** [comment]
ThreeJS does an assignment `_currentRenderTarget = target1`
PIXI changes it to target2
ThreeJS wants to change it to target1 but does not because `_currentRenderTarget === target1`

The idea of reset is that you invalidate current saved state, and may be set some params that are needed for your engine. Currently, `_currentRenderTarget` does not follow this idea.

**Comment by mrdoob** [comment]
Would you like to propose a PR?
