### ISSUE TITLE
Allow ColladaLoader to parse images that are read through FileReader.

### ISSUE THREAD

**Issue by MohmadAyman** [mrdoob/three.js#12349]
##### Description of the problem 

Hello!, We are trying to allow users to loader their models through the browser, we are using the FileReader API, we are ok loading the meshes and using the `loader.parse`, the problem we face is when a mesh has a texture uri in it, e.g. 
`<init_from>../../materials/textures/base_color.png</init_from>` .
I would propose adding an argument to the loader where the user can pass a dictionary of the images in DataUri form, and the loader would search for the image there if that argument was provided. 

I can help implementing this if this does make sense to you.

Thanks!

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
Related: https://github.com/mrdoob/three.js/pull/11259

**Comment by mrdoob** [comment]
I solved this issue differently in `KMZLoader`:
https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/KMZLoader.js#L29-L89

**Comment by donmccurdy** [comment]
That requires the data is already a single file, zipped, yes? Expensive to zip everything up if it wasn't already, and then unzip. (the difference in folders and zips is _very_ noticeable testing larger files on https://gltf-viewer.donmccurdy.com/, which supports both for Chrome+FF).

**Comment by mrdoob** [comment]
Yeah... I'll have a read at #11259 later today.
