### ISSUE TITLE
Blender exporter can't handle Cycles Node Setup

### ISSUE THREAD

**Issue by developer-lindner** [mrdoob/three.js#12344]
##### Description of the problem 

When exporting a model which was build with the Cycles Engine the "images" property
is empty in the json file.

When using a simple cube and add a material / texture image with the Blender Engine,
the "images" property is set and ThreeJS can handle it correctly.

So the exporter would need some love to handle Cycles Node System as well  i guess?!

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> So the exporter would need some love to handle Cycles Node System as well i guess?!

That's correct. The exporter is not ready to work with Cycles engine. Also see #8887

**Comment by donmccurdy** [comment]
If it helps any, the [Blender glTF exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter) does work with Cycles, although you need to use the PBR cycles nodes that ship with the exporter.

**Comment by developer-lindner** [comment]
![bildschirmfoto 2017-10-09 um 00 37 06](https://user-images.githubusercontent.com/5435866/31321912-99335dd0-ac8d-11e7-9e5f-f664e6916809.png)

Switched to Blender Renderer now... but still no luck. Using cast shadow is not allowed or is it a bug too?

**Comment by donmccurdy** [comment]
@developer-lindner sorry for the very late reply, but yes an error thrown when cast shadows are enabled is certainly a bug.

**Comment by mrdoob** [comment]
@donmccurdy yeah... I think we should proceed with the deprecation of the blender exporter... 😅

**Comment by donmccurdy** [comment]
@mrdoob Do you mean continue with #12903 and remove the Blender JSON exporter soon, or something more gradual like warnings in the documentation? From https://github.com/mrdoob/three.js/issues/12903#issuecomment-352923439 I guess we were thinking of discussing options again in Summer 2018, and that is almost here.

**Comment by mrdoob** [comment]
Yeah, I vote for removing it too 💪

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
