### ISSUE TITLE
recent version broke in non-browser implementation

### ISSUE THREAD

**Issue by gre** [mrdoob/three.js#12356]
##### Description of the problem 

So far Three.js was working in a non-browser implementation (e.g. in React Native Expo EXGLView implementation e.g. https://docs.expo.io/versions/latest/tutorials/create-floatyplane-game.html ) but with recent WebVRManager it is no longer the case, it breaks in WebVRManager when it do `window.addEventListener`.

Is it possible to be more safe in checking window exists when trying to access it? I understand it is a bit specific case to do Three.js not in a browser, but I don't think mocking `window` is such a good idea neither (because it's gonna break all libs that branch on existence of `window`).

##### Three.js version

0.87.1

**Comment by Mugen87** [comment]
Related #12288

**Comment by gre** [comment]
ok great, sorry not having searched that !
