### ISSUE TITLE
ColladaLoader2 exception

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#12358]
Unfortunately can't share the file because it's the client property, and also quite huge (140+ MB). I was attempting to load it and export specific objects as JSONs, but this happened:
![screen shot 2017-10-08 at 21 06 00](https://user-images.githubusercontent.com/242577/31319972-e4c3fe4c-ac6c-11e7-97c4-f767abd0438e.png)
Idk if the warnings above are relevant, just dropping it here for the record.

**Comment by makc** [comment]
In case my file version is different, the line 2095 is this:
![screen shot 2017-10-08 at 21 10 02](https://user-images.githubusercontent.com/242577/31319986-30dd9220-ac6d-11e7-8d3d-be39d726f8cf.png)

**Comment by Mugen87** [comment]
This is a current limitation of the loader. It's not possible to parse geometry if it has more than four vertices. Can you check in the file of your customer how many vertices a single face has?

**Comment by Mugen87** [comment]
You can set a breakpoint [here](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/ColladaLoader2.js#L2140) and check the value of `maxcount`.

**Comment by makc** [comment]
Ok, I'm fine with the warning, but there is hard error, too. Can't it at least use 1st 3 vertices?

**Comment by makc** [comment]
Tried old parser by Tim Knip and Tony Parisi. Got a bunch of complaints about MultiMaterial removed, then it thought for a while, and finally stopped the page and blanked the console. Maybe the tab run out of memory.

**Comment by makc** [comment]
Ok, I had better luck with FBX version of the model. I will close this since I can't provide the test case.

**Comment by Mugen87** [comment]
If you can share a test file, i'll try to implement the support for such geometry. The loader "only" needs to subdivide the face into single triangles. This could be easier than i initially thought.
