### ISSUE TITLE
First-time rendering fails on the Chrome browser

### ISSUE THREAD

**Issue by Mann90** [mrdoob/three.js#12359]
##### Description of the problem 

The first time calling of 'renderer.render' will draw nothing in the Chrome browser (v61 or after).

The test code:

```javascript
var scene = new THREE.Scene();
var camera = new THREE.PerspectiveCamera( 75, window.innerWidth/window.innerHeight, 0.1, 1000 );

var renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );
document.body.appendChild( renderer.domElement );

var geometry = new THREE.BoxGeometry( 1, 1, 1 );
var material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
var cube = new THREE.Mesh( geometry, material );
scene.add( cube );

camera.position.z = 5;

var draw = function () {
    cube.rotation.x += 0.1;
    cube.rotation.y += 0.1;
    renderer.render(scene, camera);
};

draw();
```

##### Three.js version

- [ ] Dev
- [X] r87
- [ ] ...

##### Browser

- [] All of them
- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [X] macOS (10.13 High Sierra)
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by Mugen87** [comment]
It works in my case, see.

https://jsfiddle.net/f2Lommf5/109/

Tested with Chrome Version 61.0.3163.100.

**Comment by TristanVALCKE** [comment]
Work for me too, but just a question. Are you expecting that the cube rotate after call draw() ???

**Comment by makc** [comment]
I had similar problem in #11940 but it only applied to skins.

Jsfiddle does work for me, and thecube does rotate.

**Comment by Mann90** [comment]
On my machine, it just shows a black screen as shown in the following screenshot.

Note: My macOS is 10.13 (High Sierra) and the browser is Chrome 61 and Chrome Canary 63.
(The issue cannot be reproduced on earlier version of macOS or other browsers.)
![image](https://user-images.githubusercontent.com/8889106/31323825-be38114c-ac7a-11e7-9758-9833da3a144e.png)

**Comment by Mugen87** [comment]
🤔

**Comment by looeee** [comment]
Working fine for me here on Chrome 62 beta, Windows 10. 

@Mann90 do you get an console error messages?

**Comment by TristanVALCKE** [comment]
@Mann90 have you some extra addon or chrome/flags active like webgl2 ?

**Comment by Mann90** [comment]
1. There is no any error messages in the console.
2. No extra WebGL extension installed.

(Again: This issue happens on macOS High Sierra + Chrome 61/Chrome Canary 63. Other OS or browsers like Firefox have no such issue.)

**Comment by Mugen87** [comment]
@Mann90 Can you please paste `about:gpu` in your address bar and copy the entire page to a new [pastebin](https://pastebin.com/).

/cc @kenrussell

**Comment by Mann90** [comment]
Attached please find the zipped gpu information. 
 (By the way, I can also reproduce the issue on the Safari on the same computer. Only Firefox has no issue on my machine.)

[gpu.html.zip](https://github.com/mrdoob/three.js/files/1369279/gpu.html.zip)

**Comment by jaredpike** [comment]
I am experiencing the same issues as @Mann90.

[gpu.htm.zip](https://github.com/mrdoob/three.js/files/1389460/gpu.htm.zip)

**Comment by DOLI91** [comment]
I'm experiencing glitching and textures not properly loading since upgrading to High Sierra. The same project however works fine on FireFox and Safari

**Comment by Mugen87** [comment]
I've upgraded to macOS 10.13.1 (High Sierra) and tested again with Chrome 62.0.3202.75. Still unable to reproduce.

@Mann90 @jaredpike  Do you experience the issue with the latest version of macOS and Chrome?

**Comment by Mann90** [comment]
Yes. The issue is there on macOS 10.13.1 and Chrome (61,62, beta, and Chrome canary as well.)

**Comment by kenrussell** [comment]
Sorry for the delay triaging this.

I can reproduce the problem on an NVIDIA MacBook Pro with 10.13.1 and both Chrome Canary (64) and Stable (62). about:gpu is attached.

Safari and Safari Technology Preview (STP) behave differently, but reproduce the same underlying problem. With STP, the canvas is almost completely transparent. Adding another call to "draw()" at the end of the fiddle https://jsfiddle.net/f2Lommf5/109/ makes the cube show up. In STP the cube is ghostly green over the page's gray background.

I'll see whether this is happening on more types of GPUs. I've contacted Apple asking whether they can reproduce, and whether I should file a Radar. @Mugen87 could you provide your about:gpu ? The reports above indicate this is happening on dual-GPU MacBook Pros with NVIDIA and AMD discrete GPUs.

Please feel free to file this at crbug.com and include the repro case. Send me the bug ID if you file it. Thanks.

[gpu.htm.zip](https://github.com/mrdoob/three.js/files/1462494/gpu.htm.zip)

**Comment by Mugen87** [comment]
> @Mugen87 could you provide your about:gpu ? 

Here you go! [about_gpu.htm.zip](https://github.com/mrdoob/three.js/files/1462557/about_gpu.htm.zip)

**Comment by kenrussell** [comment]
Thanks. I can't reproduce the rendering failure on a 15-inch, Mid 2015 MacBook Pro with AMD Radeon R9 M370X discrete GPU running 10.13.2 beta, and Chrome 64.0.3264.0 (Official Build) canary (64-bit):

GPU0	VENDOR = 0x1002, DEVICE= 0x6821 *ACTIVE*
GPU1	VENDOR = 0x8086, DEVICE= 0x0d26

So far I can only reproduce the rendering failure on an NVIDIA GPU. Bugs have been seen and filed with Apple about rendering problems with NVIDIA GPUs on macOS 10.13 so I'm doubtful we will be able to work around this in the browser.

If you can reduce this test case further and eliminate the Three.js dependency we would really like to incorporate it into the WebGL conformance suite.

https://www.khronos.org/registry/webgl/sdk/tests/conformance/canvas/drawingbuffer-static-canvas-test.html is one that's known to fail on NVIDIA GPUs on 10.13. It's probably related to allocation of large textures, but the Three.js example doesn't seem to be doing that.

**Comment by kainino0x** [comment]
It sounds like this reduced test case
https://github.com/KhronosGroup/WebGL/pull/2543
is sufficient, and we no longer need the reduced test case as @kenrussell had requested.

**Comment by kenrussell** [comment]
That's right. Thanks @kainino0x .

**Comment by kenrussell** [comment]
FYI, this was a bug in the graphics driver for NVIDIA GPUs in macOS 10.13. A workaround is in the current Chrome Canary: 64.0.3275.0 (Official Build) canary (64-bit).

This issue was tracked on the Chromium side in http://crbug.com/775202 and I'm aiming to merge the workaround to Chrome 63.
