### ISSUE TITLE
Outline post processing bug

### ISSUE THREAD

**Issue by jack-jun** [mrdoob/three.js#12350]
##### Description of the problem 
Hello,

I followed the outline post processing example, using the effect on a transparent canvas(the alpha buffer is enabled in WebGLRenderer). While an object is selected and added the edges, the canvas background becomes black just like in the example(see the screenshots below).

<img width="664" alt="2017-10-20 3 42 18" src="https://user-images.githubusercontent.com/5774080/31810241-9bcd6278-b540-11e7-9d28-502e90ba9a99.png">
<img width="632" alt="2017-10-20 3 42 59" src="https://user-images.githubusercontent.com/5774080/31810242-9c164312-b540-11e7-848d-01549c9d2eb1.png">

Thanks.

##### Three.js version

- [ ] Dev
- [x] r87

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Custom solution here: https://discourse.threejs.org/t/post-processing-outline-error/1081/7
