### ISSUE TITLE
Animations don't end on last keyframe of clip.

### ISSUE THREAD

**Issue by CorinWilkins** [mrdoob/three.js#12369]
Using the current FBX loader from -dev

My skeletal animations, loaded from a binary FBX, exported from Maya using the game exporter, are ending on the t-pose with a brief pause before looping. 

I have investigated the issue and it appears that all the last position, rotation, scale, values in the animation clip's tracks are all the same (I believe the t-pose, but can't visualise it) regardless of the bone positions/rotations in the last frame of the animation when viewed in Maya.

reducing the duration of the clips by about 40% seems to cut out the move to the t-pose, but I have had to get the animator to add a 40% sacrificial buffer to the end of each clip. If I don't add this buffer the animation is cropped, it is as if the last frame of the clip is being replaced with the t-pose.

I can't share that model, but I have an example of a cube orbiting a point, which pauses at the t-pose (not really a t-pose) frame each loop.

I've seen the example (with the character running with its arms in the air) which works as expected, so assume there is a combination of export settings that is unsupported/should be avoided.

thanks

[animtest.zip](https://github.com/mrdoob/three.js/files/1368951/animtest.zip)

**Comment by looeee** [comment]
In 3DS Max there is a setting in the Animations section of the FBX exporter called "Remove Single Key" which I think solves this. Does Maya have something similar?

![fxb](https://user-images.githubusercontent.com/5307958/31367118-53edc45a-ad9f-11e7-9dba-58d265e542ad.jpg)

**Comment by CorinWilkins** [comment]
Thanks Looeee, 

That's given us enough of a steer to get the animations exporting properly.

When exporting anims from Maya to fbx for three.js:

Frame 0 has to be the bind pose.  This must be keyed and maya must be on that frame when you export.  It does not need to be included in a clip.
Do not let the exporter bake animation.  
All anim must be created at 30fps
Clips do not need padding or extra frames, if they do not look correct an export setting is wrong.
Below are the settings from Maya 2017 U4

![maya-fbx-settings-2](https://user-images.githubusercontent.com/1826895/31382917-213832cc-adb1-11e7-915f-34676300bc50.png)
![maya-fbx-settings-1](https://user-images.githubusercontent.com/1826895/31382918-21546bfe-adb1-11e7-954e-d721d84c1d3b.png)

Hopefully this helps anyone else that stumbles across this.

**Comment by looeee** [comment]
Great, glad that worked for you. And thank you for sharing the screenshots. 

> All anim must be created at 30fps

Support for different frame rates should be added soon, see #12332
