### ISSUE TITLE
Anaglyph example is broken

### ISSUE THREAD

**Issue by TristanVALCKE** [mrdoob/three.js#12365]
##### Description of the problem 

Where is the skybox ? [https://threejs.org/examples/#webgl_effects_anaglyph](https://threejs.org/examples/#webgl_effects_anaglyph)

##### Three.js version

- [ ] Dev
- [ ] r87
- [x] Threejs.org

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This seems to be fixed in `dev`.

**Comment by TristanVALCKE** [comment]
Ok i confirme it is fixed in dev at PR#12345. I close

**Comment by mrdoob** [comment]
9ee6c4034b03f3f8f635344e33ab997c7ecd0648 fixed it.
