### ISSUE TITLE
The glTF model of "Polly" does not animate correctly

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#12364]
##### Description of the problem 

The project "Polly" seems to have been created to introduce all new features of glTF 2.0.
https://www.youtube.com/watch?v=l7TB1O51X_M

However, I tried [project_polly.gltf](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/polly/project_polly.gltf) displayed in three.js + glTF Loader, skinning animation seems not to be displayed correctly. 
I do not know if this is a model problem or a viewer problem.
 (Because it is [not displayed correctly even with Babylon.js](http://jsdo.it/cx20/aGqk), it may be a problem on the model side.)

[Three.js + glTF Loader + project_polly.gltf result:](http://jsdo.it/cx20/qugw)
![image](https://user-images.githubusercontent.com/1833979/31326452-660180ac-ad02-11e7-96fc-4b4fc9e525f7.png)

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

ThinkPad X260 (HD Graphics 520) + Windows 10 + Chrome 61

/ping @donmccurdy 
/cc @UX3D-nopper

**Comment by UX3D-nopper** [comment]
U need to investigate, when your morphing is happening. Before or after the skinning calculations.
Unfortunatelly, this is not well defined with glTF as far as I know.

**Comment by donmccurdy** [comment]
There is another issue with morph targets (#12368) also. Will try to resolve that first and then see where we're at with Polly, as that issue is probably simpler.

**Comment by donmccurdy** [comment]
With those issues fixed, the head still shrinks at strange interval in the animation: https://gltf-viewer-experimental.donmccurdy.com/#model=https://raw.githubusercontent.com/KhronosGroup/glTF-Blender-Exporter/master/polly/project_polly.gltf

So, the morph target issue I mentioned is not the problem. [We apply morphing before skinning calculations](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderLib/meshphysical_vert.glsl#L30-L43). Is that expected?

**Comment by pikilipita** [comment]
Actually, I made a  mistake in the description of the issue: th efile is actually a .glb file, exported from blender.

You can get it here:
[https://xr.plus/tmp/cosmonaut-glb.zip](https://xr.plus/tmp/cosmonaut-glb.zip)

**Comment by donmccurdy** [comment]
The [model has been updated](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly) for better support across all engines, and this problem is no longer visible.

Closing.
