### ISSUE TITLE
GLTFLoader: Morph targets not animating correctly in ROME models

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#12368]
The [ROME glTF models](https://github.com/mrdoob/rome-gltf) are not playing correctly in the latest version of GLTFLoader. Some pieces of the models are displaced (see screenshot) and some property binding errors appear in the log:

```
THREE.PropertyBinding: Trying to update property for track: horse_colorMap.morphTargetInfluences but it wasn't found. Group
```

<img width="490" alt="screen shot 2017-10-09 at 7 07 10 am" src="https://user-images.githubusercontent.com/1848368/31342111-9c82e2c0-acc0-11e7-9d4a-309815adf2c2.png">

This may have been introduced by #12244.

**Comment by mrdoob** [comment]
> This may have been introduced by #12244.

Uh oh! Should we revert?

**Comment by donmccurdy** [comment]
Let me check tonight, I’m hoping it can be fixed while still trimming those extra Object3Ds.
