### ISSUE TITLE
Rounded rectangle helper

### ISSUE THREAD

**Issue by martinjoiner** [mrdoob/three.js#12366]
I have a little helper function that makes rounded rectangle shapes (like border-radius in CSS) and extrudes them to meshes. The function takes a parameters config object to vary whether it is solid, or just a hollow border (centre punched out), the depth and border thickness and obviously material. 

It's very useful for whipping up floating clickable labels. 

I am happy to create a pull request to make this a built-in feature of Three.js but only if you think it deserves to be in there. What direction is the library going in? Would something like that be a good feature or so specific it would be considered bloat?

**Comment by pailhead** [comment]
I tried to do something similar:

https://github.com/mrdoob/three.js/pull/9858

While it may be useful, it should probably be in examples (i never got around to pushing it there). 

I don't completely agree with the current selection of geometries, but the place where we are at now seems to be that those are locked in, anything else can be an example. 

Another way of approaching this could be to publish an npm module:

https://www.npmjs.com/package/three-rounded-box

But the problem with that is it has to be advertised. Someone who can improve this (horrible) code of mine, may not even be aware of it's existence.

**Comment by WestLangley** [comment]
There is a rounded rectangle in [this three.js example](http://threejs.org/examples/webgl_geometry_shapes.html).

**Comment by pailhead** [comment]
That might be a solution, overload two examples with shapes and geometries.

**Comment by mrdoob** [comment]
> What direction is the library going in? Would something like that be a good feature or so specific it would be considered bloat?

I think that would be a bit bloat-y... Once you go down that path, why leave it at all corners having the same radius? Etc...

I think the example should be enough.
