### ISSUE TITLE
ShaderMaterial rendered with two cameras shows improper light/normal relationship in second camera

### ISSUE THREAD

**Issue by cl4ws0n** [mrdoob/three.js#12370]
I am trying to figure out how to properly use Three.js' built in ShaderChunks for lighting and fog and such, and I figured a good first step was to just copy one of the ShaderLib shaders' setup. So to start with I used:

```js
customMaterial = new ShaderMaterial({
  lights: true,
  uniforms: UniformsUtils.merge( [
    UniformsLib.common,
    UniformsLib.specularmap,
    UniformsLib.envmap,
    UniformsLib.aomap,
    UniformsLib.lightmap,
    UniformsLib.emissivemap,
    UniformsLib.fog,
    UniformsLib.lights,
    {
      emissive: { value: new Color( 0x000000 ) },
      diffuse: { value: new Color( 1,1,1 ) }
    }
  ]),
  vertexShader: document.getElementById("vertexShader").textContent,
  fragmentShader: document.getElementById("fragmentShader").textContent
})
```
Where the shader code is just directly copied from [meshlambert_vert.glsl](https://github.com/mrdoob/three.js/blob/r87/src/renderers/shaders/ShaderLib/meshlambert_vert.glsl) and [meshlambert_frag.glsl](https://github.com/mrdoob/three.js/blob/r87/src/renderers/shaders/ShaderLib/meshlambert_frag.glsl), and that section there is based on [this entry in the `ShaderLib`](https://github.com/mrdoob/three.js/blob/r87/src/renderers/shaders/ShaderLib.js#L31)

However, I am rendering my test scene from two different cameras/renderers at once, and I immediately noticed an issue. Changing one camera's perspective changes the second camera's lighting angle, for objects with this customMaterial applied.

Here you can see the standard `MeshLambertMaterial` on the left, and my copies on the right.

![image](https://user-images.githubusercontent.com/17188122/31354222-2f53a69a-acfb-11e7-95a0-04d0a522451b.png)
![image](https://user-images.githubusercontent.com/17188122/31354240-405e297e-acfb-11e7-9f91-8c33f73c5a2d.png)

As of now I'm not really certain why this is happening. Is it a bug in the shader update routine? Is it my uniform copying method? Something else?

**Comment by WestLangley** [comment]
Please use [stackoverflow](https://stackoverflow.com/questions/tagged/three.js) or the [forum](https://discourse.threejs.org) for help.

https://stackoverflow.com/questions/46612145/how-do-i-assemble-proper-uniforms-for-threejs-shaders

**Comment by cl4ws0n** [comment]
I wasn't looking for help when I posted this here. I was trying to report an issue. This should not be closed. I'm just not sure whether that issue is with the renderer, shadermaterial, or just the total lack of documentation on this system.

**Comment by mrdoob** [comment]
Sorry @cl4ws0n, but we prefer to keep github for confirmed bugs. We don't have the resources to help every user to determine where the issue is.
