### ISSUE TITLE
changing renderer resolution doesn't update scissor 

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#12384]
There's a line in WebGLRenderer:

```js
		state.scissor( _currentScissor.copy( _scissor ).multiplyScalar( _pixelRatio ) );
```

inside of `initGLContext`. When the `setPixelRatio` method is used, this scissor is not updated. Does it need to be updated? Maybe `setScissor` needs to be called in `setPixelRatio`?

**Comment by mrdoob** [comment]
> Does it need to be updated?

I don't know. Do you have a use case?

**Comment by trusktr** [comment]
Not yet actually, I was only playing around to learn what it does, and I saw that.

**Comment by mrdoob** [comment]
Closing until you have a use case.
