### ISSUE TITLE
Example webgl_geometries2 broken?

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#12388]
##### Description of the problem
I can't quite make it out from the source, are they intentionally bunched up and overlapping? ([link](https://threejs.org/examples/webgl_geometries2.html))
![webgl_geometries2](https://user-images.githubusercontent.com/4936897/31425810-1b43680e-ae61-11e7-8ae4-10f7ea83d390.png)

##### Three.js version
- [x] Dev
- [x] r87

##### Browser
- [x] Chrome
- [x] Firefox

##### OS
- [x] Windows

**Comment by Mugen87** [comment]
Yes, the example was always like that. But i don't know the reason for this clutter.

**Comment by WestLangley** [comment]
I suggest it be renamed to `webgl_geometries_parametric.html`,  and cleaned up like `webgl_geometries`.

**Comment by Mugen87** [comment]
Sounds good!
