### ISSUE TITLE
Corrupt WebGLIndexedBuffer causing rendering error

### ISSUE THREAD

**Issue by acampbellb** [mrdoob/three.js#12380]
I have encountered a bizarre issue that I've spent days trying to uncover to no avail. The setup is quite simple and I've attached a working example of the HTML and script that renders a PNG as a background image (Mesh), and a loaded GLTF model. The index.html file within the attached ZIP file contains the JS script that generates the THREE scene.
[test.zip](https://github.com/mrdoob/three.js/files/1372366/test.zip)

The problem occurs when I attempt to replicate this working example within the context of a React application. I am able to generate a THREE scene with just the GLTF model (by itself), but as soon as I add the background Mesh to the scene I get the following warnings and error.

```
main.bundle.js:19070 THREE.WebGLProgram: gl.getProgramInfoLog() 
C:\fakepath(468,3-100): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll
C:\fakepath(477,3-100): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll

THREE.WebGLRenderer: image is not power of two (100x100). Resized to 128x128 <img crossorigin=​"Anonymous" src=​"assets/​models/​gltf/​defiant/​textures/​None_diffuse.jpeg">​
THREE.WebGLRenderer: image is not power of two (100x100). Resized to 128x128 <img crossorigin=​
"Anonymous" src="assets/models/gltf/defiant/textures/akmainmat_diffuse.jpeg">
THREE.WebGLRenderer: image is not power of two (100x100). Resized to 128x128 <img crossorigin=​"Anonymous" src=​"assets/​models/​gltf/​defiant/​textures/​akmainmat_deblack.jpg_diffuse.jpeg">​

main.bundle.js:17803 Uncaught TypeError: Cannot read property 'type' of undefined
    at WebGLIndexedBufferRenderer.setIndex (main.bundle.js:17803)
    at WebGLRenderer.renderBufferDirect (main.bundle.js:22646)
    at renderObject (main.bundle.js:23335)
    at renderObjects (main.bundle.js:23308)
    at WebGLRenderer.render (main.bundle.js:23072)
    at Renderer3D.renderScene (main.bundle.js:163778)
    at rapidRender (main.bundle.js:163744)
```

As you can see it begins processing the texture images, and then hits an error after processing 3 images. In the working example it generates a resize warning for all of the texture images, and no error. Again, if I remove the image Mesh, the GLTF object renders fine without the error. But, as soon as I add the Mesh, it fails to load all of the textures and renders the model with holes in it.

##### Three.js version

Version: 0.87.1 (NPM)

##### Browser

- [] All of them
- [X] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

No special hardware

**Comment by mrdoob** [comment]
Any chance you can create a jsfiddle?

**Comment by acampbellb** [comment]
As the issue is within a React application it would be difficult to do a fiddle.  I'll look into making it available from my web-server, I'll post the URL once its up & running.

**Comment by acampbellb** [comment]
I've docker containerized an example of this problem, and loaded it up on a blade. The website URL is www.nexusmicros.com.  After the front page loads, click the '3D Demo' link in the upper left-hand corner of the page. This will load the background image Mesh (starfield), and a GLTF model (starship), it uses Orbit Controls so you can inspect the model by zooming in on it. You will notice the ship has holes in the surface, which is a result of the errors that occur when the scene is rendered. Even though the model is completely loaded (GLTF loader uses the LoadingManager) it appears to fetch the texture images after the object is added to the scene and rendered. You can view the reoccurring error in the browser (Chrome) developer tools console.

**Comment by acampbellb** [comment]
Update on this issue. I noticed that the GLTF model was version 2, interestingly enough the model loads fine with the version 1 loader, but I thought it might have some bearing on this particular problem, so I tried using the GLTF2Loader, same problem occurs.

**Comment by mrdoob** [comment]
Closing until a simple jsfiddle is provided.

**Comment by kurozael** [comment]
@mrdoob 

I am also experiencing this exact issue. I don't have a jsfiddle because I'm never used that, but a similar setup to @acampbellb leads me to the same error. This is kind of a blocker for us.

Thanks.

**Comment by mrdoob** [comment]
@kurozael could you create a jsfiddle? thanks!

**Comment by kurozael** [comment]
Hi @mrdoob I'm not sure how to do this, but the OP's .zip file demonstrates the bug perfectly, are you able to use his example to debug it?

**Comment by kurozael** [comment]
Hi @mrdoob 

I've identified a fix for this bug, please see the pull request at #14367
