### ISSUE TITLE
WebGLRenderer does not properly detect a need for updates in ShaderMaterials

### ISSUE THREAD

**Issue by ghost** [mrdoob/three.js#12383]
##### Description of the problem 

`needsUpdate` flags for `ShaderMaterials` are not assigned correctly/have leaks?

If you have a multiple renderer & camera setup this bug becomes obvious. I was able to find a "quick fix" to my issue which I think proves this is a bug. [Here is a codepen](
https://codepen.io/cl4ws0n/pen/qPYwzp?editors=0010) where the default `MeshLambertMaterial` is shown on the left cube, and a  `ShaderMaterial` copy of it is shown on the right cube. The left image is one `WebGLRenderer` and `PerspectiveCamera`, and the right image is another set of them. Both sets are rendering the same scene and cubes.

Here you can see a simple demo, of before and after I added `shaderMat.needsUpdate = true` before each render pass.
![image](https://imgur.com/lAqDKCP.gif)
![image](https://imgur.com/AjSspbR.gif)

##### Three.js version

- [X] Dev
- [X] r87
- [X] ...

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by takahirox** [comment]
Does this issue happen only when multiple renderers are used?

**Comment by takahirox** [comment]
Seems like this's a bug indeed.
Renderer2's Directional light's data is leaked to Renderer1's in the example case.

`material.uniforms` of `ShaderMaterial`'s is used as `materialProperties.shader.uniforms`  in `WebGLRenderer`.

https://github.com/mrdoob/three.js/blob/f60be20072a5400f1be23b9c0c279304686507d1/src/renderers/WebGLRenderer.js#L1468-L1473

And uniforms variables for Directional lights is set to `materialProperties.shader.uniforms` here.

https://github.com/mrdoob/three.js/blob/f60be20072a5400f1be23b9c0c279304686507d1/src/renderers/WebGLRenderer.js#L1538-L1557

(FYI, `lights.state.directional` is generated and calculated here)

https://github.com/mrdoob/three.js/blob/f60be20072a5400f1be23b9c0c279304686507d1/src/renderers/webgl/WebGLLights.js#L160-L185

So, one `material.uniforms` is shared among multiple renderers. `uniforms.directionalLights.value = lights.state.directional;` affects all renderer's `materialProperties.shader.uniforms`.

Renderer2 overrides `material.uniforms.directionalLights.value` with its `lights.state.directional`. Then Renderer2's `lights.state.directional` is transferred to WebGL uniforms for both Renderer1 and Renderer2. Renderer1's `lights.state.directional` is just ignored.

/ping @mrdoob

**Comment by takahirox** [comment]
An easy solution would be setting the clone of `material.uniforms` to `materialProperties.shader.uniforms` and adding the function copying values from `material.uniforms` to `materialProperties.shader.uniforms` in `WebGLRenderer`?

**Comment by Mugen87** [comment]
Yes, you basically need the same approach for custom shaders that is already used for built-in materials: Copying the current values from the material to the internal uniforms object. However, this will cause additional overhead for all other use cases expect for this one (sharing a custom shader  across multiple renderers). Although this overhead would be probably just minor...

**Comment by mrdoob** [comment]
Closing this for now.
