### ISSUE TITLE
Blender exporter doesn't support linked textures

### ISSUE THREAD

**Issue by goose121** [mrdoob/three.js#12409]
When the materials of objects are linked to that of another object in blender (select objects, make the one with a texture the working object, Ctrl-L, select "Material"), they show up as all having that texture in blender. After exporting to JSON using the plugin and rendering WebGL, though, the texture only shows up on the original object (the one that was the working object when linked)

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
