### ISSUE TITLE
[bug with forums] The Discourse rules seem very strict. Posting a GitHub link flags and removes a thread.

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#12400]
I tried to post a GitHub link in a reply to [this now-hidden thread](https://discourse.threejs.org/t/nesting-scenes-is-possible-what-is-it-good-for/965), but doing that seems to have flagged the thread and made it invisible so it no longer appears in the thread list. I don't think that that post has anything in it that deserves flagging (automatic or not).

Then I tried to post a [new thread about the problem](https://discourse.threejs.org/t/posting-a-link-to-another-thread-blocks-the-original-thread-from-the-forums/979) in the forums, and that thread got similarly flagged when I posted a screenshot showing the problem.

Since I can't report the issue there, I'm reporting it here.

When I tried to reply to the first issue, it gave me this message:

![screenshot 2017-10-12 at 2 45 18 pm](https://user-images.githubusercontent.com/297678/31520791-fd342d0c-af5b-11e7-9662-e5aa4fd6d136.png)

The host is `github.com`.

It gave me these notifications at the same time:

![screenshot 2017-10-12 at 2 46 42 pm](https://user-images.githubusercontent.com/297678/31520855-320d95e0-af5c-11e7-96a3-bddab7e8a40e.png)

And the messages look like this:

![screenshot 2017-10-12 at 2 47 36 pm](https://user-images.githubusercontent.com/297678/31520877-51de66b0-af5c-11e7-9d9e-62daf71c6a37.png)

The current rules seems to be dictatoriously harsh. Instead of removing a whole thread, the system should just prevent the post from being posted.

It currently makes it impossible to shared GitHub links (and obviously the likelihood of people wanting to share GItHub links relating to Three.js is probably somewhat high).

I've never had this issue with any other Discourse instance before, so something leads me to believe that settings on Three's instance are a bit too strict.

**Comment by trusktr** [comment]
Was it automatic? Or does someone just not like me posting? It seems automatic to me, but I could be wrong.

**Comment by looeee** [comment]
It's not a bug, it's a feature :wink:

New users who post loads are treated with suspicion in case they are spammers. 

Your posts were automatically flagged as spam. I've removed the flags now.

**Comment by trusktr** [comment]
@looeee `system` is not letting me reply to threads. 😢
