### ISSUE TITLE
Suggestion: default crossOrigin of *Loader should be undefined

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#12413]
##### Description of the problem 

The default `crossOrigin` of some `*Loader`s under `examples/js/loaders` are `Anonymous` while base `Loader`'s is `undefined`.

IMO, `crossOrigin` of all `*Loader`s should be `undefined` for security and consistency.

If you folks agree with this, I'll make PR.

These loaders seems to have default `Anonymous` `crossOrigin` as far as I know from the grep command.

- `AssimpJSONLoader`
- `AssimpLoader`
- `BinaryLoader`
- `ColladaLoader`
- `GLTFLoader`
- `MTLLoader`
- `VRMLLoader`

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
see b37706008b705805b1b197dafbac027e54a0342d

@mrdoob What was your motivation for setting `Anonymous` as the default value?

**Comment by msbit** [comment]
Just working through this now, and in the specific case of `ImageLoader`:

* setting a `crossOrigin` value of `undefined`
* drawing a loaded image onto a canvas
* creating a new `THREE.CanvasTexture` based on that canvas

results in a security error, because the canvas is ["tainted"](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image#What_is_a_tainted_canvas), so in that particular case `undefined` probably isn't a sensible default.

**Comment by mrdoob** [comment]
> @mrdoob What was your motivation for setting Anonymous as the default value?

I don't remember... Here are some old discussions: #779 #4653

**Comment by mrdoob** [comment]
`anonymous` lower-case? we may want to change that indeed...

**Comment by takahirox** [comment]
IIRC, CORS setting will be propagated. @msbit 's case is expected result.

Security is often tradeoff between secured and capability. I prefer secured side as default, `undefined` crossOrigin, and apps (devs) set appropriate value when necessary. But not a strong preference.

**Comment by mrdoob** [comment]
As far as I remember, if `crossOrigin` is set to `undefined` textures do not load in the [rawgit link](https://rawgit.com/mrdoob/three.js/dev/examples/). So if we set it to `undefined` by default we'll have to add `loader.setCrossOrigin( 'anonymous' )` in all the examples.

**Comment by mrdoob** [comment]
It would also "break" A LOT of projects... But if someone has really good arguments for doing it we can reconsider it.

**Comment by MarcelKlammer** [comment]
Setting crossOrigin to undefined rather than anonymous would not result in more security.

This security feature is located server side with a proper CORS configuration.

I don't think that sending Origin in the request header would do any harm in an everyday developer scenario.

**Comment by mrdoob** [comment]
Sounds good. Should we change `Anonymous` to `anonymous` though?

**Comment by msbit** [comment]
> Should we change `Anonymous` to `anonymous` though?

Might be prudent, according to [this](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes):

> An invalid keyword and an empty string will be handled as the `anonymous` keyword.

so we may simply be getting the `anonymous` behaviour through a bit of a quirk (though I'm not able to quickly find anything that indicates whether case is important).

**Comment by makc** [comment]
some old safari failed to load images with anonymous set if there were no cors headers. otherwise it is good default

**Comment by takahirox** [comment]
> Setting crossOrigin to undefined rather than anonymous would not result in more security.

Thanks. This is what I wanted to know to discuss, how risky setting `anonymous` to default value. So there's no reason to push `undefined` for me as default now.
