### ISSUE TITLE
VideoTexture cloning bug

### ISSUE THREAD

**Issue by dokydok** [mrdoob/three.js#12422]
When cloning a VideoTexture the video element inside is undefined and an error is thrown

**Comment by Mugen87** [comment]
Can confirm this bug, see https://jsfiddle.net/dcb8ug7k/2/

**Comment by Mugen87** [comment]
https://github.com/mrdoob/three.js/blob/master/src/textures/VideoTexture.js#L19

If we use `scope.image` instead of `video` the problem should be solved. Maybe a better solution is to override `clone()` like `Mesh` does.

**Comment by gabrielgrant** [comment]
Confirming this an an issue when `THREE.ShaderPass` tries to copy a VideoTexture, and it is fixed by @Mugen87 's patch in #12460 (thanks @Mugen87 !)
