### ISSUE TITLE
GLTF loader error: Joints is undefined

### ISSUE THREAD

**Issue by pikilipita** [mrdoob/three.js#12425]
Using the latest verison of the GLTF Loader ( as of 17/10/2017 ), I have a new error showing:
"joints is undefined".

This was not happening with an older ( from late september ) 

I can provide a model if needed

**Comment by takahirox** [comment]
Please share the model file with us.

**Comment by donmccurdy** [comment]
@pikilipita It sounds like you have an older glTF 1.0 file. Note that three.js currently supports glTF 2.0+.Probably want to stick with GLTFLoader from <=r86, or convert the file to glTF2 (tooling for this is coming soon).

Although there is (supposed to be) a better error message to explain this case.

**Comment by pikilipita** [comment]
Actually, I made a mistake in the description of the issue: the file is actually a .glb file, exported from blender.

You can get it here:
[https://xr.plus/tmp/cosmonaut-glb.zip](https://xr.plus/tmp/cosmonaut-glb.zip)

**Comment by takahirox** [comment]
No error appeared on both r87 and the latest `dev` with the model file in my environment.

Would you please check if the Three.js and `GLTFLoader` are actually the latest version?
If you still face this error with the latest Three.js, please make the example online. We'd help.

**Comment by pikilipita** [comment]
I am not able to reproduce the error on a simple page. 
It only happen in a complex page with lots of javascripts libs loaded. 
So I guess there is some conflict between librairies.

I'll keep you updated if find what's exactly wrong

**Comment by takahirox** [comment]
Then, would you please close this issue so far and open again when you achieve to reproduce the error?
