### ISSUE TITLE
WebGLRenderer.info improvements

### ISSUE THREAD

**Issue by Astrak** [mrdoob/three.js#12420]
Currently `renderer.info` provides a lot of valuable information, but the data is reinitialized at each `render` method call, which breaks its use when having multiple render calls per frame (mirrors, composing...). 

To address this, a pattern like the following could provide a way to decide when to reset this data :

```
renderer.info.autoUpdate = false;
renderer.info.needsUpdate = true;
```
'reset' may be a better fit but 'update' is used everywhere, no idea what you prefer.

This way `composer.renderer.info` could get going by using this internally, for mirrors however one would have to manually set this behaviour, depending on when to reset the counters.

What do you think about that ?

**Comment by WestLangley** [comment]
I like it, but I would suggest

    renderer.info.autoReset = false;
    renderer.info.reset();

**Comment by Astrak** [comment]
What do you think about the effectcomposer, could it benefit handling that internally ? Or would it be better to let the user decide in that case too ?

**Comment by WestLangley** [comment]
>What do you think about the EffectComposer, could it benefit handling that internally

I expect it would be better to keep it simple and let the user handle it. That may mean exposing an option for resetting the info counter from within the Composer's passes.

 ... Or adding Composer pre-pass callbacks. :-)
