### ISSUE TITLE
FBXLoader fills in random crap in geometry groups

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#12427]
While trying to convert the result of FBXLoader in something useable, I have discovered various anomalies such as these:
![screen shot 2017-10-18 at 6 15 12](https://user-images.githubusercontent.com/242577/31700863-6a28a338-b3cc-11e7-81e1-3a23f66e8227.png)
![screen shot 2017-10-18 at 6 17 46](https://user-images.githubusercontent.com/242577/31700864-6a4cb480-b3cc-11e7-8028-c5f68ea52d12.png)
(here: missing groups, negative material indices)

**Comment by looeee** [comment]
Can you share a simple model that does this? I'll take a look.

**Comment by makc** [comment]
Unfortunately this file is 100+ MB and has 20K+ objects. So not simple at all.

**Comment by makc** [comment]
But I can run any diagnostic script on it, if you want.

**Comment by looeee** [comment]
Is it happening with other files, or just with that one? 

And do you know which exporter was used to generate the file?

**Comment by makc** [comment]
> Is it happening with other files

I dont deal much with FBX because I know there are format zoo, actually, with every SDK version introducing breaking changes, so no much other files I tried with. This one - I only need to extract subset of it, but my old Mac is not powerful enough to open full file in 3D editor in any form, so I thought I would write a script that will load FBX and then export JSON. Which I did, but at the time of splitting geometries of multimaterial meshes I ran into issues presented above.

> do you know which exporter was used to generate the file?

From what hex editor says, it is 3dmax plugin:
![screen shot 2017-10-18 at 12 21 29](https://user-images.githubusercontent.com/242577/31713759-9e0d215a-b3ff-11e7-9f46-cf2fd3c56043.png)

**Comment by looeee** [comment]
Hmm, don't think there is much I can do with that, sorry! 

If you can create some simpler multimaterial objects that have the same problem I'll take a look.

**Comment by looeee** [comment]
@makc would you be able to test this with the latest dev version? Missing groups should be fixed now at least. 

I haven't come across any other files with negative indices issues so that may be a problem in your model.

**Comment by makc** [comment]
> Missing groups should be fixed now at least.

I am getting some geometries with single group now, I guess that was the fix.

Negative indices are still there:

![screen shot 2017-10-28 at 15 32 18](https://user-images.githubusercontent.com/242577/32134925-05248d7a-bbf7-11e7-9dc3-bc6d45aef473.png)
![screen shot 2017-10-28 at 15 36 14](https://user-images.githubusercontent.com/242577/32134926-05467d7c-bbf7-11e7-8a92-b3f6a88fc61f.png)

**Comment by makc** [comment]
I tried to see where do they come from, but I have no idea where to dig from there:

![screen shot 2017-10-28 at 16 14 33](https://user-images.githubusercontent.com/242577/32135205-6cbdec84-bbfb-11e7-9207-2da99606d8e8.png)
![screen shot 2017-10-28 at 16 15 37](https://user-images.githubusercontent.com/242577/32135206-6ce158cc-bbfb-11e7-87c4-7dee23072059.png)

**Comment by looeee** [comment]
If you uncomment this line in the loader

https://github.com/mrdoob/three.js/blob/21ab28ec24611f303d0f5975f8d3236a8f863dde/examples/js/loaders/FBXLoader.js#L100

it will log the FBXTree - this is the data structure created by the TextParser or BinaryParser which is then used to build the three.js model. 

Material index information is found in the Geometries - so expand to `FBXTree.Objects.subNodes.Geometry` - all the geometries in the file are here, identified by ID. 

Next, expand the geometry `FBXTree.Objects.subNodes.Geometry[ID].subNodes.LayerElementMaterial[0].subNodes.Materials.properties.a` - this is an array containing the raw material mapping information for the model. 

It shouldn't have any negative indices. If it does, then either:

* there's a problem with your model
* there's a problem in the parser

**Comment by makc** [comment]
> so expand to FBXTree.Objects.subNodes.Geometry

this freezes my browser every time I try to expand anything there and below. I guess I will have to script it.

**Comment by makc** [comment]
so I placed this instead of log:
```javascript
for (var ID in FBXTree.Objects.subNodes.Geometry) {
	var a = FBXTree.Objects.subNodes.Geometry[ID].subNodes.LayerElementMaterial[0].subNodes.Materials.properties.a;
	if (a.length > 1) if (a.indexOf (-1) > -1) {
		console.log (FBXTree.Objects.subNodes.Geometry[ID]); debugger
	}
}
```
and got the same thing as before:
![screen shot 2017-10-30 at 15 13 33](https://user-images.githubusercontent.com/242577/32175342-f6493686-bd84-11e7-9eb6-5581a0c3cb6b.png)

**Comment by makc** [comment]
Ok, I have the same model in collada, so I checked the mapping there - it appears that the materials for those three `-1`s are not set in DAE either 😡 So, I am closing this in favor of
> there's a problem with your model

![screen shot 2017-10-30 at 16 25 25](https://user-images.githubusercontent.com/242577/32179262-440fedb0-bd8f-11e7-9276-24907c16e19e.png)
