### ISSUE TITLE
Alpha to Coverage Support

### ISSUE THREAD

**Issue by mattdesl** [mrdoob/three.js#12438]
##### Feature: Support Alpha To Coverage

It would be nice to support a flag for [Alpha to Coverage](https://medium.com/@bgolus/anti-aliased-alpha-test-the-esoteric-alpha-to-coverage-8b177335ae4f). This feature has existed in WebGL contexts for a while, however, it seems hardly used in practice.

It can be used to create really crisp alpha cutouts with MSAA-enabled contexts. 

When enabled, you no longer need to specify alphaTest or perform a `discard` in the fragment shader, you simply output the frag alpha and the GL context will handle cutouts. You can read more about it [here](https://medium.com/@bgolus/anti-aliased-alpha-test-the-esoteric-alpha-to-coverage-8b177335ae4f), including some tricks to make things even smoother.

```js
// enable alpha to coverage with current ThreeJS renderer
const gl = renderer.getContext();
gl.enable(gl.SAMPLE_ALPHA_TO_COVERAGE);
```

This feature assumes MSAA is enabled and supported (i.e. may not work in external monitors).

Here is an example wireframe shader using alpha to coverage:
https://mattdesl.github.io/webgl-wireframes/app/
![screenshot 64](https://user-images.githubusercontent.com/1383811/31785155-4396df8a-b4d2-11e7-895e-3056fcd2e8a1.png)

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by haroldiedema** [comment]
I've tried implementing this in my game engine but had to revert it back once I found out that it completely breaks with any material that has an opacity < 1.0.

Take this for example:
```javascript
let renderer = new THREE.WebGLRenderer();
let mesh     = new THREE.Mesh(
    new THREE.BoxBufferGeometry(1, 1, 1),
    new THREE.MeshPhongMaterial({ color: 0xff0000, opacity: 0.75, transparent: true })
);

// Enable AtoC
const gl = renderer.getContext();
gl.enable(gl.SAMPLE_ALPHA_TO_COVERAGE);
```

You would expect a red box with 75% opacity, but with AtoC enabled, the box disappears entirely.

Though I am unsure if this is just a matter of configuring some extra parameters on the WebGL context or not. It looks like it needs some more work in order for this to function properly within Three.

**Comment by Mugen87** [comment]
> You would expect a red box with 75% opacity, but with AtoC enabled, the box disappears entirely.

AFAIK, using `SAMPLE_ALPHA_TO_COVERAGE` can be considered as a replacement for using `alphaTest`. If you set `alphaTest` to `0.76` for your phong material, the cube is going to vanish, too.

https://jsfiddle.net/vakxejuf/1/

However, this does not happen with by enabling `SAMPLE_ALPHA_TO_COVERAGE`.

https://jsfiddle.net/vakxejuf/2/

> let renderer = new THREE.WebGLRenderer();

You have to pass in `{ antialias: true }` in order to enable MSAA, otherwise `SAMPLE_ALPHA_TO_COVERAGE` won't work.
