### ISSUE TITLE
whats in store for r88 and future releases?

### ISSUE THREAD

**Issue by cyth319** [mrdoob/three.js#12440]
three.js is standing in r87 for a long time? i am curious about whats in your mind for future? what are you trying to do right now?

i read something like removing .geometry all together. is that correct?

**Comment by mrdoob** [comment]
My current tasks:

* Make WebVR experience smooth
* Make more special objects (self rendering objects). Like Mirror, Water, etc...

On top of that, whatever people's itches are being scratched 🙂

**Comment by mrdoob** [comment]
My current tasks:

* Make WebVR experience smooth
* Make more special objects (self rendering objects). Like Mirror, Water, etc...

On top of that, whatever people's itches are being scratched 🙂
