### ISSUE TITLE
Memory not released after dispose

### ISSUE THREAD

**Issue by feabauer** [mrdoob/three.js#12447]
##### Description of the problem 

The created objects (mesh/material/geometry) are not released, after disposed in Three.js R87, while all released in Three.js R86, with the same code.

	var container;

	var camera, scene, renderer;

	init();
	animate();

	function init() {
		container = document.createElement( 'div' );
		document.body.appendChild( container );

		camera = new THREE.PerspectiveCamera( 60, window.innerWidth / window.innerHeight, 1, 10000 );
		camera.position.z = 100;

		scene = new THREE.Scene();

		renderer = new THREE.WebGLRenderer();
		renderer.setPixelRatio( window.devicePixelRatio );
		renderer.setSize( window.innerWidth, window.innerHeight );
		container.appendChild( renderer.domElement );
	}

	function animate() {
		requestAnimationFrame( animate );
		renderer.render( scene, camera );
	}
	
	var planes = [];
	function testplanes(){
		for(var i=0; i<100; i++){
			var m = new THREE.Mesh( 	new THREE.PlaneBufferGeometry( 1, 1 ), 
										new THREE.MeshBasicMaterial( {color: 0x010101*i } ));
			m.position.x = -50+i;
			scene.add( m );
			planes.push(m);
		}
	}			

	function delplanes(){
		for(var i=0; i<100; i++){
			scene.remove(planes[i]);	
			planes[i].geometry.dispose();
			planes[i].material.dispose();
			planes[i] = null;
		}	
	}
	

Typing testplanes() in console, then typing delplanes();
100 Meshes, 100 MeshBasicMaterial, and 100 PlaneBufferGeometry, remain in memory,  with memory profiling of heap snapshot,  in Three.js R87.  While all released in Three.js R86. 

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Itee** [comment]
Same under 88dev

**Comment by takahirox** [comment]
Seems like `renderItems` in `WebGLRenderer` keeps the rendered objects even after you call `geometry/material.dispose()`. In the example case, it holds `Mesh` objects and they have references to `geometry` and `material` then `geometry/material` memory aren't released.

Perhaps this's a bug?
I'm making PR to fix.
