### ISSUE TITLE
Types problem for Light

### ISSUE THREAD

**Issue by WahlbergRu** [mrdoob/three.js#12452]
Hello, can u looked my issues. 
I right or not? If yeah I can make PR
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20772

**Comment by Mugen87** [comment]
Sry, we have nothing to do with these type definitions for `three.js`. Try to ping the actual authors of the following file in your issue. [three-core.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/three/three-core.d.ts)

**Comment by Mugen87** [comment]
Yes, you can also use `THREE.Color` for this.

**Comment by WahlbergRu** [comment]
thx
