### ISSUE TITLE
Mirror + PerspectiveCamera

### ISSUE THREAD

**Issue by Freeman555** [mrdoob/three.js#12468]
version: r87

Hello,

After  combine:
https://threejs.org/examples/?q=poin#misc_controls_pointerlock
+
https://threejs.org/examples/?q=mirror#webgl_mirror

There are some glitches around edges, take a look;

![three_js_mirror](https://user-images.githubusercontent.com/15048451/31863916-e07027ce-b754-11e7-9027-c5006b60016c.png)

Code:
https://codepen.io/Freeman555/pen/qPwKpQ

To make fix it u can change value in PerspectiveCamera from 75 to 50;
`camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 1, 1000 );`

But there some other way to still have 75 value of perspective?

**Comment by Mugen87** [comment]
Looks like this problem is already fixed in `dev`. https://jsbin.com/madacecicu/edit?js,output

BTW: `THREE.Mirror` was reworked and is now `THREE.Reflector`. The counterpart `THREE.Refractor` is available with the next release.

**Comment by Freeman555** [comment]
@Mugen87 
Thank u 4 info, I close it.
