### ISSUE TITLE
how to minify our own three.js fork?

### ISSUE THREAD

**Issue by cyth319** [mrdoob/three.js#12467]
i made a few changes in a few .js files now i want to  minify it in order to download to my computer. How to do it?

**Comment by looeee** [comment]
What you want to do is compile. It's pretty straightforward, but for help questions you need to ask over on the [forum](https://discourse.threejs.org/).

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/blob/dev/utils/build/README.md
