### ISSUE TITLE
Add textures to model

### ISSUE THREAD

**Issue by Satif** [mrdoob/three.js#12476]
I have upload dae model. How to attach all needed textures to it?

**Comment by tentone** [comment]
Hi

Cant understand what you mean, you need to explain you problem properly and if possible show what you have...

After loading the .dae file using the ColladaLoader you can manually create Texture objects and attach them to your materials.

Cumps

**Comment by Mugen87** [comment]
Please use stackoverflow or the [forum](https://discourse.threejs.org/) for help.

**Comment by Satif** [comment]
Here is [stackoverflow](https://stackoverflow.com/questions/46889967/three-js-collada-loader-textures)
