### ISSUE TITLE
GLTFLoader. Data is already JSON in parse function

### ISSUE THREAD

**Issue by antonio-gomez** [mrdoob/three.js#12470]
Using the loader with GLTF2 models (downloaded from sources like sketchfab) give the following error:

"Uncaught SyntaxError: Unexpected end of JSON input."

Solved with changing:

```
if ( magic === BINARY_EXTENSION_HEADER_MAGIC ) {
  extensions[ EXTENSIONS.KHR_BINARY_GLTF ] = new GLTFBinaryExtension( data );
  content = extensions[ EXTENSIONS.KHR_BINARY_GLTF ].content;
} else {
  content = convertUint8ArrayToString( new Uint8Array( data ) );
}
var json = JSON.parse( content );
```

into this:

```
if ( magic === BINARY_EXTENSION_HEADER_MAGIC ) {
    extensions[ EXTENSIONS.KHR_BINARY_GLTF ] = new GLTFBinaryExtension( data );
    content = extensions[ EXTENSIONS.KHR_BINARY_GLTF ].content;
    var json = JSON.parse( content );
} else {
  try {
    var json = JSON.parse( data );
  }
  catch ( e ) {
    content = convertUint8ArrayToString( new Uint8Array( data ) );
    var json = JSON.parse( content );
  }
}
```
A simple check if it is already valid JSON.

I'll submit a pull request with the patch. Thanks!

**Comment by takahirox** [comment]
Yeah, enabling `GLTFLoader.parse()` to handle string would be worth.

How about simply checking if data is `string`?

	if ( typeof data === 'string' ) {

		content = data;

	} else {

		var magic = convertUint8ArrayToString( new Uint8Array( data, 0, 4 ) );

		if ( magic === BINARY_EXTENSION_HEADER_MAGIC ) {

			extensions[ EXTENSIONS.KHR_BINARY_GLTF ] = new GLTFBinaryExtension( data );
			content = extensions[ EXTENSIONS.KHR_BINARY_GLTF ].content;

		} else {

			content = convertUint8ArrayToString( new Uint8Array( data ) );

		}

	}

	var json = JSON.parse( content );

/cc @donmccurdy

**Comment by donmccurdy** [comment]
+1 this is worth fixing yeah. The solution @takahirox proposes would be my preference. Thanks!

**Comment by miandry** [comment]
After change with @takahirox    convertUint8ArrayToString is not defined

**Comment by donmccurdy** [comment]
@miandry Are you using it somewhere else? In recent versions of three.js that function has been renamed to `THREE.LoaderUtils.decodeText( array )`.

**Comment by miandry** [comment]
@donmccurdy thks i will check it
