### ISSUE TITLE
88DEV Massive Resource Memory Leak

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#12478]
A recent push to the dev branch has created some type of infinite loop / massive memory leak situation when loading the same material multiple times. I do not use the THREE.Cache system (which should be disabled by default). I've used my own caching system for quite some time now and until updating to this weeks dev build, have never had a problem.

I'm not sure which PR caused this but as soon as I went back to the 88dev build from a couple weeks ago, everything is fine.

I am at work right now, and probably will not have time to build a fiddle for a couple days as I am incredibly busy right now. I will work on it ASAP.

r88dev (this weeks, a couple weeks ago was fine)
Chrome
Win7 64bit
Nvidia Geforce 1060

**Comment by takahirox** [comment]
Probably #12458 will fix?

**Comment by titansoftime** [comment]
Probably so, will test it when your PR is merged.

**Comment by mrdoob** [comment]
Merged. Crossing fingers!

**Comment by titansoftime** [comment]
Success! All is well. Thank you!

**Comment by mrdoob** [comment]
Pheeew!
