### ISSUE TITLE
Feature request: .set() using THREE.Vector3 objects

### ISSUE THREAD

**Issue by polyclick** [mrdoob/three.js#12477]
Hi

I've always wondered if there is a particular reason for not being able to set vectors by providing the actual vector object. Is this due to performance reasons? It sure would clean up our code a lot more.

Currently we have to do this:

```
let newPosition = new THREE.Vector3(4.0, 2.0, 1.0);
object.position.set(newPosition.x, newPosition.y, newPosition.z);
```

Of course, this is just a short example, but image doing a lot a these calculations. This approach results in a lot of typing, redundancy and is very prone for typing errors. Wouldn't it be great if we could do something like this:

```
let newPosition = new THREE.Vector3(4.0, 2.0, 1.0);
object.position.set(newPosition);
```

I'm interested in your views on this.

**Comment by takahirox** [comment]
I think you can use `.copy()`.

**Comment by polyclick** [comment]
You mean `.clone()` right?

I both tried: `object.position.set(newPosition.clone())` and `object.position = newPosition.clone()`

**Comment by takahirox** [comment]
No. 

`.copy()` https://threejs.org/docs/#api/math/Vector3.copy

**Comment by polyclick** [comment]
Wow! This is great. That indeed works!
