### ISSUE TITLE
Example 'webgl_morphnormals' consumes all memory

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#12474]
##### Description of the problem 
The `webgl_morphnormals` example starts out normal i.e. GUI is loading fine etc., but it then never shows the two flamingos and instead very quickly eats up all the available memory.  
Current [r87/homepage](https://threejs.org/examples/webgl_morphnormals.html) is fine, current [dev](https://rawgit.com/mrdoob/three.js/dev/examples/webgl_morphnormals.html) is not.

##### Three.js version
- [x] Dev
- [ ] r87

##### Browser
- [ ] All of them
- [x] Chrome (v62.0.3202.62 Linux, v61.0.3163.100 Windows)
- [x] Firefox (v56 both)
- [ ] Internet Explorer (possibly, can't test)

##### OS
- [ ] All of them
- [x] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by takahirox** [comment]
#12458 fixes this issue.

**Comment by moraxy** [comment]
I'm still seeing the same effect after applying #12458 locally, as well as via the [rawgit preview](https://rawgit.com/mrdoob/three.js/0fddd78643437ddf936c0c8258b37ac8b40bdebc/examples/?q=morphn#webgl_morphnormals) - is there any other PR I'm missing?

**Comment by takahirox** [comment]
You need to update `build` by running `npm run build`

**Comment by moraxy** [comment]
christ, what a rookie mistake 😞 
yeah #12458 fixes it, thank you

**Comment by takahirox** [comment]
Just in case, would you please keep this issue open until #12458 is merged?

**Comment by mrdoob** [comment]
Seems to fix it on my end 🎉
