### ISSUE TITLE
glTF loader not implementing "normalized" data on accessors?

### ISSUE THREAD

**Issue by my2iu** [mrdoob/three.js#12481]
##### Description of the problem 

I'm creating some glTF files, and there aren't many glTF importers yet, so it's possible I may simply be creating my files incorrectly. But I think the Three.js glTF loader isn't handling normalized data for vertex colors correctly.

Here is a file that I'm trying to load in three.js:
   http://www.user00.com/threejsnotnormalized.js

In it, I'm creating a GLB with a triangle where the vertex colors at the corners are:
   0xFF0000FF, 0xFF0100FF, 0xFF000032

The colors are stored as 8-bit unsigned bytes.

The result I'm seeing is below:

![threejsnotnormalized](https://user-images.githubusercontent.com/1350963/31923600-7b43ae0c-b849-11e7-9f63-91b857187a1f.jpg)

It looks like the 0x01 in the green channel of the 2nd point is being converted to a 1.0 instead of 1.0/255. I see other consistencies when using the vertex colors 0xFF0000FF, 0xFFFF00FF, 0xFF0000FF that are consistent with 0xFF being interpreted as 255 instead of as 1.0.

I think that when I set {"normalized":true} for the accessors, then the data should be normalized, but it seems that three.js isn't doing that.

You can edit for small-test.  
http://jsfiddle.net/akmcv7Lh/ (current revision)  
http://jsfiddle.net/hw9rcLL8/ (dev)

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Haswell integrated graphics

**Comment by takahirox** [comment]
Thanks for reporting.

`GLTFLoader` doesn't support `accessor.normalized` yet.
We should let it support.

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#accessornormalized

**Comment by donmccurdy** [comment]
Thanks @takahirox! Let me know if I should take a look at anything also. :)

**Comment by takahirox** [comment]
Almost done in the local branch.
But I don't have any `accessor.normalized` file and can't test well enough other than threejsnotnormalized.js.
Any other `accessor.normalized` files?

**Comment by donmccurdy** [comment]
Not that I'm aware of. That might be a good request for the https://github.com/bghgary/glTF-Asset-Generator project.

**Comment by takahirox** [comment]
Here is the working repository

https://github.com/takahirox/three.js/blob/GLTFLoaderAccessorNormalized/examples/js/loaders/GLTFLoader.js#L1475-L1567

Seems like it's working for  threejsnotnormalized.js but is not tested well enough yet.

**Comment by donmccurdy** [comment]
I only just saw this but there is an optional `normalized` argument to THREE.BufferAttribute: https://threejs.org/docs/#api/core/BufferAttribute, which passes into WebGL `vertexAttribPointer()` call.

**Comment by takahirox** [comment]
Oh, I wasn't aware of that. I'll look into it tomorrow...

**Comment by takahirox** [comment]
Updated.

https://github.com/takahirox/three.js/blob/GLTFLoaderAccessorNormalized/examples/js/loaders/GLTFLoader.js#L1475-L1506

Seems like we should use `normalized` argument.

**Comment by donmccurdy** [comment]
Nice! That seems more convenient yes 😄

**Comment by takahirox** [comment]
> That might be a good request for the https://github.com/bghgary/glTF-Asset-Generator project.

Yup. And requesting to https://github.com/KhronosGroup/glTF-Sample-Models seems also nice.
