### ISSUE TITLE
Feature: Support for multiple renderers in WebVR

### ISSUE THREAD

**Issue by sjlynch** [mrdoob/three.js#12489]
##### Description of the problem 

Note: I am not asking for help. I am asking for a feature where WebVR accepts multiple renderers and draws them the same way Threejs currently handles multiple renderers. 

This SO post describes what the feature would do: 
https://stackoverflow.com/questions/46573338/threejs-webvr-with-two-separate-renderers

This would be a great feature for enhancing VR performance. There are times you have expensive screen shaders (such as a dynamic sky) that you need to upscale in order to get decent fps.

##### Three.js version

- [ ] Dev
- [x ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
I do not understand... Why do you need two renderers?

**Comment by sjlynch** [comment]
By using .setPixelRatio set to 0.3 on the renderer which handles the expensive gpu work, I can use a shader to render expensive volumetric clouds on a sky dome without much performance loss or loss of quality. It works well outside of VR. I tried to instead render the shader to a plane fixed to the camera using a render target to upscale (or would it be downscale?) the shader and this also works outside of VR but I ran into another issue: https://github.com/mrdoob/three.js/issues/12706

It seems threejs behaves a little differently when using WebVR.

**Comment by mrdoob** [comment]
Sorry, in the future we won't even be able to control the size of the gl context while in VR (with the WebVR 2.0) API. So your approach is, unfortunately, not future-proof.

**Comment by mrdoob** [comment]
How about rendering the clouds into a `RenderTarget` instead?

**Comment by pailhead** [comment]
Why use two renderers?
