### ISSUE TITLE
ColladaLoader "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by jayPare** [mrdoob/three.js#12490]
I'm trying to repeat the kinematics example found here:

https://threejs.org/examples/#webgl_loader_collada_kinematics

However, I'm using my own collada, and I'm getting the "length" error at line 138 (I'm using the exact same code for now):

https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_collada_kinematics.html

Here is my dae file:

https://www.dropbox.com/s/41ci5mb8n6s0i0g/nao.dae?dl=0

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Your `dae` file does not contain any kinematic information, so tags like `library_kinematics_models` or `library_kinematics_scenes` but just a simple armature (skeletal animation). Besides, the file does not contain any animation data. You are only able to statically display it.

**Comment by jayPare** [comment]
What if I want to animate my a armature? Is there anything else in Three.js to do that with my collada file?

**Comment by Mugen87** [comment]
You can apply animation data in a content creation tool like Blender. It is uncommon to use skeletal animation entities like a skin or a bone hierarchy without any keyframes of the respective bones.

**Comment by jayPare** [comment]
Closing as apparently I cannot animate without having animation in my model.

**Comment by looeee** [comment]
> It is uncommon to use skeletal animation entities like a skin or a bone hierarchy without any keyframes of the respective bones.

It's not that uncommon - there are two use cases I've dealt with recently, albeit with FBX rather than Collada: 

1. animations are defined in a separate file
2. the skeleton is used to set up user control of a character

**Comment by jayPare** [comment]
> It's not that uncommon - there are two use cases I've dealt with recently, albeit with FBX rather than Collada:
> 
> animations are defined in a separate file
> the skeleton is used to set up user control of a character

And is there a way to do it with Collada using Three.js? :O

**Comment by looeee** [comment]
> And is there a way to do it with Collada using Three.js?

@jayPare no idea, I've never tried.

**Comment by jayPare** [comment]
@looeee but if I export my model to FBX I should be able to do so?

**Comment by looeee** [comment]
Yes probably. If you ask over on the [forum](discourse.threejs.org) and
explain exactly what you want to do I'll give you some pointers.

**Comment by looeee** [comment]
Yes probably. If you ask over on the [forum](discourse.threejs.org) and
explain exactly what you want to do I'll give you some pointers.

**Comment by jayPare** [comment]
> Yes probably. If you ask over on the forum and
> explain exactly what you want to do I'll give you some pointers.

The link seems to be broken @looeee 

I will definately post as soon as I have the link! :)

**Comment by looeee** [comment]
Fixed

**Comment by jayPare** [comment]
There we go:

https://discourse.threejs.org/t/looking-for-a-way-to-animate-model-with-bones-and-joints-rotation-infos/1085

**Comment by jayPare** [comment]
Just updated my question @looeee and @Mugen87, in cas you have ideas. Same URL!
