### ISSUE TITLE
Blender Expoprter not export animation clip info

### ISSUE THREAD

**Issue by cbsim77** [mrdoob/three.js#12492]
##### Description of the problem 

I test sample:
https://github.com/mrdoob/three.js/tree/master/utils/exporters/blender/tests/blend/anim.blend
can't export animationClip

i think bug.

##### Three.js version

- [ ] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by Mugen87** [comment]
I was able to export the model with this setup:

![image](https://user-images.githubusercontent.com/12612165/32018983-008028d8-b9cc-11e7-8820-3cf30d7efe8c.png)

**Comment by cbsim77** [comment]
thank your answer.
but, It's not OK.

exported json.
"animations":[{
        "fps":24,
        "name":"default",
        "tracks":[]
    }],

not found animations.
