### ISSUE TITLE
GLTFLoader doesn't feed the property 'bones' of geometry in SkinnedMesh

### ISSUE THREAD

**Issue by marlinilram** [mrdoob/three.js#12494]
##### Description of the problem 
Hi, guys,

I'm not sure if this is as design but geometry.bones is used for initialization for a copy case of SkinnedMesh.

Thanks!

##### Three.js version

- [ ] Dev
- [x] r86
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by takahirox** [comment]
Thanks for reporting.

This isn't a glTF specific but a generic `SkinnedMesh` issue. `SkinnedMesh.clone()` doesn't clone `Skeleton`, and expects ‘Skeleton.bones` are initialized in its constructor with `geometry.bones`.

So it doesn't correctly clone if `Skeleton` and `Skeleton.bones` are initialized out of `SkinnedMesh` constructor without `geometry.bones`. It should be fixed.

**Comment by marlinilram** [comment]
Hi, guys,
the `Skeleton.bones` sometimes isn't a normal tree structure. Some array elements of `Skeleton.bones` might be children of other array element so `Object3D.clone()` can not deep copy the structure correctly. I wrote a method to deep copy `Skeleton`. Hope it would help for others with same problem. Thanks.

```javascript
const cloneSkeleton = (skeleton) => {
  // clone all bones
  let boneMap = {}
  skeleton.bones.forEach(bone => {
    bone.traverse(subBone => {
      if (Object.keys(boneMap).findIndex(key => { return key === subBone.uuid }) === -1) {
        boneMap[subBone.uuid] = {
          cloned: subBone.clone(false),
          parent: subBone.parent
        }
      }
    })
  })
  // restructure cloned bones
  Object.keys(boneMap).forEach(key => {
    let info = boneMap[key]
    // get the real parent of cloned bone
    let parentInfo = info.parent ? boneMap[info.parent.uuid] : null
    // if real cloned parent found, add this bone to it
    if (parentInfo) { parentInfo.cloned.add(info.cloned) }
    else {
      // it's a root bone, clone/create it and add this bone to it
      let root = info.parent ? info.parent.clone(false) : new Object3D()
      root.name = 'RootBone'
      root.add(info.cloned)
    }
  })
  // create bones for cloned skeleton
  let bones = skeleton.bones.map(bone => { return boneMap[bone.uuid].cloned })
  return new Skeleton(bones, skeleton.boneInverses)
}
```

**Comment by donmccurdy** [comment]
Closing this, we can track the issue in #11573 and #11574.
