### ISSUE TITLE
Suggestion re: multi-line shader chunks

### ISSUE THREAD

**Issue by CarlBateman** [mrdoob/three.js#12516]
##### Description of the problem 

Deep diving into ShaderChunks I noticed that the chunks are now single line and use #include.
e.g.
`var linedashed_vert = "uniform float scale;\nattribute float lineDistance;\nvarying float vLineDistance;\n#include <common>\n#include <color_pars_vertex>\n#include <fog_pars_vertex>\n#include <logdepthbuf_pars_vertex>\n#include <clipping_planes_pars_vertex>\nvoid main() {\n\t#include <color_vertex>\n\tvLineDistance = scale * lineDistance;\n\tvec4 mvPosition = modelViewMatrix * vec4( position, 1.0 );\n\tgl_Position = projectionMatrix * mvPosition;\n\t#include <logdepthbuf_vertex>\n\t#include <clipping_planes_vertex>\n\t#include <fog_vertex>\n}\n";`

vs

```
vertexShader: [

"uniform float scale;",
"attribute float lineDistance;",

"varying float vLineDistance;",

THREE.ShaderChunk[ "common" ],
THREE.ShaderChunk[ "color_pars_vertex" ],
THREE.ShaderChunk[ "logdepthbuf_pars_vertex" ],

"void main() {",

	THREE.ShaderChunk[ "color_vertex" ],

	"	vLineDistance = scale * lineDistance;",

	"	vec4 mvPosition = modelViewMatrix * vec4( position, 1.0 );",
	"	gl_Position = projectionMatrix * mvPosition;",

	THREE.ShaderChunk[ "logdepthbuf_vertex" ],

"}"

].join( "\n" ),
```
Both new and seasoned users may refer to code as a learning resource when the documentation is insufficient.
Aren't multi-line shader chunks clearer and easier to read?
Shouldn't the non-standard `#include <>` be avoided to avoid confusion (it could be mistaken for some kind of weird C++like template -- I speak from experience)?
At least in three.js (clearly this isn't an issue for three.min.js)?

##### Three.js version

- [ ] Dev
- [x] r83?+

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
Instead of using the build file, try to work with the `GLSL` files in the `ShaderLib` directory. In this way, editors or IDEs can provide syntax highlighting and auto-completion for `GLSL` code.

Example:
https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderLib/linedashed_vert.glsl

**Comment by Mugen87** [comment]
The library uses `#include` as a preprocessor keyword in order to include shader chunks.

**Comment by CarlBateman** [comment]
OK, on reflection, I think this (and a couple of related issues) just boil down to a lack of a documentation.

If the Renderers / Shaders implementation is stable and no-one else is working on their docs, I'd be happy to write up something.

**Comment by Mugen87** [comment]
Sounds good! 👍

**Comment by pailhead** [comment]
Where will this documentation live? This is not something that an user changes ever, but is something one should be familiar if using `onBeforeCompile`

**Comment by Mugen87** [comment]
Closing. The place of any shader-related documentation can be discussed if someone actual provides a PR.y
