### ISSUE TITLE
AudioListener: deprecation warning in Chrome 63 beta

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#12510]
Just started to get this warning from Chrome Version 63.0.3239.18 (Official Build) beta (64-bit)

> [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152

Related to this line:

https://github.com/mrdoob/three.js/blob/bf2f88a553b15aeffef01db2bb2d62a5d018fd1a/src/audio/AudioListener.js#L81

**Comment by Mugen87** [comment]
From the website:

> Historically, Chrome implemented dezippering such that when the value setter of an AudioParam was used, the value was not changed instantaneously. Instead, an exponential approach equivalent to setTargetValueAtTime was done. The actual time constant used was never specified and depended on the AudioParam. With the spec change in https://github.com/WebAudio/web-audio-api/pull/393, (Sep 2015), all dezippering was removed from the spec. Dezippering will be removed from Chrome. 
The appropriate replacement is to use setTargetAtTime(value, context.currentTime, timeConstant), where timeConstant is probably around 10-20 ms, which was the typical value used in Chrome for dezippering.

Explanation for dezippering: https://github.com/WebAudio/web-audio-api/issues/76#issuecomment-27954865

I think this setup should work then:

```javascript
this.gain.gain.setTargetAtTime( value, this.context.currentTime, 0.01 );
```

**Comment by Mugen87** [comment]
I've realized that it might be no good idea to hard-code the value `timeConstant`. It's better to use the time delta value from the previous frame.

@mrdoob Any ideas how we can provide such a time delta value to `AudioListener` and `Audio`?

**Comment by mrdoob** [comment]
@Mugen87 Seems like some objects may benefit from a `.update()` method which the renderer could call per frame... Another example is `VideoTexture`. https://github.com/mrdoob/three.js/issues/12605#issuecomment-343005903

**Comment by Mugen87** [comment]
Okay, i'll try to find a solution by using a `.update()`  method.

**Comment by Mugen87** [comment]
I think it should be sufficient if the renderer just updates `AudioListener` with the last frame (or delta) time. Objects of type `Audio` and `PositionalAudio` can access this value via their `listener` reference (a ctor parameter). The actual problem is: How can the renderer reliably find an instance of `AudioListener`? If we determine that `AudioListener` has to be a child of camera, it might be an easy task. But this approach might introduce limitations since `AudioListener` won't work correctly if users add a listener to the scene graph.

**Comment by mrdoob** [comment]
> But this approach introduces limitations since `AudioListener` won't work correctly if users add it to the scene graph.

You mean conceptually or technically?

**Comment by Mugen87** [comment]
I mean conceptually. If the renderer only checks the camera for an `AudioListener`, it won't find the instance in the scene graph. 

My problem is: I'd like to have a clear way to say: "Hey renderer, here you have the listener of the scene. Be so kind and update it every frame." 😊

**Comment by Mugen87** [comment]
Maybe some explicit code?

```javascript
renderer.setAudioListener( listener );
```

**Comment by jshamble** [comment]
Not sure if this is the most elegant solution/complies with the three.js coding conventions, but in the meantime anyone looking for a quick fix, I just required setVolume to take in the delta as a parameter each time the renderer is updated and it works for me.

`setVolume:function(value,delta){this.gain.gain.setTargetAtTime(value, this.context.currentTime, delta);return this}});`

**Comment by Mugen87** [comment]
@jshamble Yes, this solution works but it also a bit strange that `.setVolume()` has a time delta parameter. Such a technical detail needs to be hidden by the library.

Anyway, we are happy for any suggestions that helps us to implement this feature 👍

**Comment by moraxy** [comment]
more deprecation warnings from the [sandbox example](https://rawgit.com/mrdoob/three.js/dev/examples/?q=webaud#webaudio_sandbox), M65 is the current stable version (`65.0.3325.181` here)

> [Deprecation] OscillatorNode.frequency.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

> [Deprecation] AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018  See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.

> [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
