### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offset' of undefined

### ISSUE THREAD

**Issue by sandipJava** [mrdoob/three.js#12524]
![offset error](https://user-images.githubusercontent.com/32532237/32157634-ab1c2804-bd6a-11e7-8060-0a59d6299abe.png)
![offset error2](https://user-images.githubusercontent.com/32532237/32157635-ab43e72c-bd6a-11e7-9b71-3543a14183dc.jpg)

I added on obj cube1(using obj Loader), then create cube2 , I want move cube2 ob cube1.

Code
=======
[cube.txt](https://github.com/mrdoob/three.js/files/1426173/cube.txt)

**Comment by makc** [comment]
you are using SpriteCanvasMaterial with WebGLRenderer, that's why

**Comment by Mugen87** [comment]
Besides, use this example as an orientation for sprites with `WebGLRenderer`.

https://threejs.org/examples/#webgl_sprites

**Comment by sandipJava** [comment]
I need ur help can u mail me ur mail... sandip.d@nipun.net... pls @makc  @Mugen87 @gilesbowkett @zimbatm @darwin

**Comment by sandipJava** [comment]
I created one 3d Map .obj (Using 3d max).  Then I loaded this map using three.js. Then I created one cube. This cube must be move on the road. how I can read the obj property and how I can set road on the map., Now this cube going in white space. Currently I gave manual road path for  moving cube.
Please share ur mail then I can send you obj files. Please Help me.

![new map 2](https://user-images.githubusercontent.com/32532237/32207989-9d0137ee-be25-11e7-8180-22d7a19250da.jpg)
![new map](https://user-images.githubusercontent.com/32532237/32207992-a10c4856-be25-11e7-8271-a4b8232bf1c8.jpg)

code: 
[ObjLoader.txt](https://github.com/mrdoob/three.js/files/1429632/ObjLoader.txt)

**Comment by sandipJava** [comment]
see example... https://threejs.org/examples/webvr_rollercoaster.html

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help questions.

**Comment by sandipJava** [comment]
@Mugen87  I used
