### ISSUE TITLE
computeVertexNormals breaking collada animation 

### ISSUE THREAD

**Issue by FuzzyWobble** [mrdoob/three.js#12521]
![screen shot 2017-10-29 at 4 33 26 pm](https://user-images.githubusercontent.com/1490568/32148027-ea2177f6-bcc6-11e7-8b60-e92ebc52ffac.png)

Hello. I am trying to smooth a faceted dae/collada model. As soon as I run the code below, the model returns to t-pose and I loose all animation characteristics (when I don't run the code below the animation works perfectly but texture extremely faceted). Is computeVertexNormals breaking animations or am I just doing something terribly wrong? All I am trying to do is smooth the texture. Thanks! 

```javascript		
avatar.traverse(function (child) {
   if (child instanceof THREE.Mesh) {
	var Geometry = new THREE.Geometry();
	const tempGeo = Geometry.fromBufferGeometry(child.geometry);
	tempGeo.mergeVertices();
	// after only mergeVertices my textrues were turning black so this fixed normals issues
	
        tempGeo.computeVertexNormals();
	tempGeo.computeFaceNormals();
	var BufferGeometry = new THREE.BufferGeometry();
	child.geometry = BufferGeometry.fromGeometry(tempGeo); 
         //no more animation if you cal this
   }
});
```

**Comment by WestLangley** [comment]
>Is computeVertexNormals breaking animations or am I just doing something terribly wrong?

I expect you can answer your own question by stepping through with a debugger. If you need help, please use a help site.
