### ISSUE TITLE
Clicking on Collada mesh that has triangles geometry error.

### ISSUE THREAD

**Issue by MohmadAyman** [mrdoob/three.js#12523]
##### Description of the problem 
Hi,

Using the new ColladaLoader with meshes with triangles geometry makes a problem with `Raycaster.intersectObjects()`

here is how where the problem arises

```
  var ray = new THREE.Raycaster( this.camera.position,
      vector.sub(this.camera.position).normalize() );

  var allObjects = [];
  this.scene.getDescendants(allObjects);
  var objects = ray.intersectObjects(allObjects);

  var model;
  var point;
  if (objects.length > 0)
  {
    modelsloop:
    for (var i = 0; i < objects.length; ++i)
    {
      model = objects[i].object;
      if (model.name.indexOf .....
.......
.......
```
If the mesh has triangles geometry it is returned as a THREE.Group() with the mesh(s) as children, the children have `name` = `null` which breaks this part of the code - `ray.intersectObjects(allObjects)` doesn't return groups, just meshes -
 
I've made a work around this problem by adding at [this commit on my repo.](https://github.com/MohmadAyman/three.js/commit/3b2d1d9418a807b0726398e8a6c2e871aa43dd8d) 

If this workaround doesn't arise any problems, I can open a PR.
I guess the other option, if that was not okay, would be modifying the `THREE.Raycaster.intersectObjects` function.

[Example mesh](https://bitbucket.org/osrf/gazebo_models/raw/2736659d92e2c1afe4098fb1c68cb2feb3a55484/house_2/meshes/house_2.dae).
##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by MohmadAyman** [comment]
I realized this problem after the models that has triangle geometries started to appear after @Mugen87  recent fix for [this issue](https://github.com/mrdoob/three.js/issues/12443).

**Comment by Mugen87** [comment]
The `name` of the object is set [here](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/ColladaLoader.js#L3120-L3122). Your commit adds a new line that does exactly the same thing. Any reasons for this? Maybe a better fix is to change this [line](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/ColladaLoader.js#L2754) to the following:

```javascript
name: xml.getAttribute( 'name' ) || ''
```
Can you please check if this also solves your problem?

**Comment by MohmadAyman** [comment]
Yes that does solve the problem!

**Comment by MohmadAyman** [comment]
No there was no particular reason -for now- to name the `mesh` the same name as the `THREE.Group()`, so this works.

[here is the PR](https://github.com/mrdoob/three.js/pull/12529)

**Comment by Mugen87** [comment]
Thanks for the PR! 👍
