### ISSUE TITLE
Exporter for Blender / Emissive properties

### ISSUE THREAD

**Issue by JustJarethB** [mrdoob/three.js#12522]
##### Description of the problem 

Hi, I have a project in Blender which I downloaded from a tutorial (.blend [Here](https://www.blenderguru.com/tutorials/create-a-spaceship-part-2-of-2?rq=spaceship) ). It contains a few Emissive materials, one of which is meant for lights, the other for highlights (think led strip). Using the exporter and loader, these materials are not showing as emissive of any sort. I have gone through the json manually and set some of the "colorEmissive" values which has given a more pleasing result, but is still not what I would like.
Hopefully I'm not missing something here..

1) I believe there is a slight issue with the exporter script that's has been written
2) Would it be possible to have some way of automatically creating a light source for emissive materials so they behave more similarly to those on Blender? Perhaps even another Material type?

Extract from JSON 
Adapted:
`{
        "depthTest":true,
        "blending":1,
        "vertexColors":false,
        "transparent":false,
        "colorSpecular":[0.5,0.5,0.5],
        "colorEmissive":[0,18,124],
        "DbgIndex":1,
        "wireframe":false,
        "opacity":1,
        "shading":"phong",
        "specularCoef":50,
        "visible":true,
        "colorDiffuse":[0.0264838,0,0.38812],
        "doubleSided":true,
        "DbgColor":15597568,
        "DbgName":"RedLines",
        "depthWrite":true
    }`
##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Take care :)

**Comment by donmccurdy** [comment]
> I believe there is a slight issue with the exporter script that's has been written

This is probably a missing feature in the blender exporter, yes. The [glTF Blender Exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter/) does support emissives, but would require some tweaks to the materials in Blender to convert them to PBR and freeze mirror transformations.

> Would it be possible to have some way of automatically creating a light source for emissive materials so they behave more similarly to those on Blender? Perhaps even another Material type?

Unfortunately this isn't feasible — what you want is probably gaussian blur in post-processing (e.g. [UnrealBloomPass](https://github.com/mrdoob/three.js/blob/dev/examples/js/postprocessing/UnrealBloomPass.js)), not a light source, and a model loader can't automatically add that for you.

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
