### ISSUE TITLE
Problematic json export of SphereGeometry

### ISSUE THREAD

**Issue by LagodViads** [mrdoob/three.js#12527]
##### Description of the problem 

Consider this code :

```
let g = new THREE.SphereGeometry(1,2,2)
let t = new THREE.Matrix4().makeTranslation(100,0,0)
g.applyMatrix( t )
let jsg = g.toJSON();
```
We can see the transformation correctly affects the geometry vertices : 
```
console.log( g.vertices.map( v => v.x ) ) 
//  [ 100, 99, 100.5, 100.5, 100 ]
```
But if we export as json :
```
console.log( JSON.stringify( jsg ) )

// {
//   "metadata": {
//     "version": 4.5,
//     "type": "Geometry",
//     "generator": "Geometry.toJSON"
//   },
//   "uuid": "5D17605B-7519-4DED-91AC-255C33AE1A9C",
//   "type": "SphereGeometry",
//   "radius": 1,
//   "widthSegments": 2,
//   "heightSegments": 2
// }
```
I would expect the transformation to be applied to the geometry when exporting to json ; the geometry would be described  as vertices/faces. 

I am doing something wrong ?

Thanks.

##### Three.js version
 
- [x] r87

##### Browser

- [x] All of them
- [] Chrome
- [] Firefox
- [] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
No, you are not doing something wrong. This is just the way `.toJSON()` serializes the default geometry entities of `three.js`. As soon as the method encounters the `parameters` property, it just serializes the parameters of the geometry and nothing else. This behavior is of course a limitation in your case.

You can bypass this logic if you delete the property like in this example: https://jsfiddle.net/f2Lommf5/217/

It's a little bit hacky, but at least it works.

**Comment by Mugen87** [comment]
You should also remove the `type` property or the deserialization will fail. `three.js` will recognize your geometry as a `SphereGeometry` but won't find the `parameters` property.

**Comment by Mugen87** [comment]
Wait, this approach is better. Just create an empty geometry object, copy the sphereGeometry and then apply the transform. Then you don't have to delete properties...

https://jsfiddle.net/f2Lommf5/219/

**Comment by WestLangley** [comment]
>Problematic json export of SphereGeometry

Once you modify the geometry, it is no longer a `SphereGeometry`. You will need to modify other properties for consistency. How you choose to do that is up to you.

Also,

>let t = new THREE.Matrix4().makeTranslation(100,0,0)
g.applyMatrix( t )

That is an old code pattern. Instead, use
```javascript
geometry.translate( 100, 0, 0 );
```

**Comment by LagodViads** [comment]
@Mugen87 
Thanks for the insight. Copying the geometry to a new Geometry is what I ended up doing. 

@WestLangley 

> Once you modify the geometry, it is no longer a SphereGeometry.

If I understand correctly, direct transformation of the vertices of a typed geometry is not the correct usage ; transformations of typed geometries should be set in the containing mesh. 

> Instead, use geometry.translate( 100, 0, 0 ); 

Ok, thanks.

**Comment by Mugen87** [comment]
> transformations of typed geometries should be set in the containing mesh.

That will definitely work.

**Comment by WestLangley** [comment]
>If I understand correctly, direct transformation of the vertices of a typed geometry is not the correct usage

There is nothing wrong with doing that. It is often done when geometries are merged, for example.
