### ISSUE TITLE
Fallback GLTF decoding does not handle UTF8

### ISSUE THREAD

**Issue by stevesan** [mrdoob/three.js#12535]
https://github.com/mrdoob/three.js/blob/b5cc08daa9d24e1396b245b2a18704e825b19efe/examples/js/loaders/GLTFLoader.js#L1139

**Comment by donmccurdy** [comment]
Hm, this is [certainly fixable](https://stackoverflow.com/questions/17191945/conversion-between-utf-8-arraybuffer-and-string), but seems like an uncommon case. Can you say more about what browsers you are trying to support and where you are getting UTF-8 glTF assets?

I'm wondering if we should just recommend using a TextDecoder polyfill: https://github.com/inexorabletash/text-encoding

**Comment by stevesan** [comment]
Yeh it’s not a huge deal.  I think a sufficient fix for this is to just
fail with an error, perhaps pointing to the polyfill :)

**Comment by takahirox** [comment]
`s = decodeURIComponent( escape( s ) );` would be another option like `FBXLoader` does?

**Comment by donmccurdy** [comment]
> I think a sufficient fix for this is to just
fail with an error, perhaps pointing to the polyfill

Is there an error thrown here, or do things just mysteriously fail later on down the line when that byte is read? If you have an example model you can share we can test this out.

> s = decodeURIComponent( escape( s ) ); would be another option like FBXLoader does?

i don't think I understand ... does that work? and would it slow down parsing for normal models? 🤔

**Comment by stevesan** [comment]
What happens in our non-browser environment is that it silently interprets
UTF8 as ascii, leading to file not found errors later on.

**Comment by takahirox** [comment]
Oops, seems like `s = decodeURIComponent( escape( s ) );` is for another purpose. That's for handling encoded UTF-8, like "%E3%81%82". I've removed the comment.

**Comment by donmccurdy** [comment]
Hm ok. I think I'd prefer not to check each character just so we can throw errors, that sounds like a performance hit. Would probably recommend the TextDecoder polyfill then... by the way is there a converter/exporter adding these UTF-8 characters? Or is it part of the name of an object in the model, do you know? Would be nice to know where that is coming from.

**Comment by stevesan** [comment]
Well filenames can contain utf8, and those show up for things like texture
images.

Ok I was thinking you could just error if TextDecoder is not defined.

**Comment by sandipJava** [comment]
I created one 3d Map .obj (Using 3d max).  Then I loaded this map using three.js. Then I created one cube. This cube must be move on the road. how I can read the obj property and how I can set road on the map., Now this cube going in white space. Currently I gave manual road path for  moving cube.
Please share ur mail then I can send you obj files. Please Help me.
@stevesan @donmccurdy 
![new map 2](https://user-images.githubusercontent.com/32532237/32207989-9d0137ee-be25-11e7-8180-22d7a19250da.jpg)
![new map](https://user-images.githubusercontent.com/32532237/32207992-a10c4856-be25-11e7-8271-a4b8232bf1c8.jpg)

code: 
[ObjLoader.txt](https://github.com/mrdoob/three.js/files/1429632/ObjLoader.txt)

see example... https://threejs.org/examples/webvr_rollercoaster.html

**Comment by donmccurdy** [comment]
> Ok I was thinking you could just error if TextDecoder is not defined.

Unless UTF-8 becomes a fairly common problem, I don't think we want to strictly require the polyfill by throwing an error when it's missing... I'd be OK with logging a warning saying something like: `THREE.GLTFLoader: TextDecoder API missing, falling back to manual decoding. May fail for assets containing UTF-8 characters.`.

**Comment by donmccurdy** [comment]
hm there are a non-trivial number of different loaders doing ad-hoc TextDecoder fallbacks: https://github.com/mrdoob/three.js/search?utf8=%E2%9C%93&q=textdecoder&type=

maybe we should just implement this with utf-8 support in a utility (`LoaderSupport.bin2str`?) and reuse it everywhere

**Comment by donmccurdy** [comment]
Here is a proposal for consolidating all of the decoding: https://github.com/mrdoob/three.js/pull/12654

If we're happy with that, I think that would be a reasonable place to implement UTF-8 in the non-TextDecoder code path.
