### ISSUE TITLE
Add `powerPreference` preference

### ISSUE THREAD

**Issue by luruke** [mrdoob/three.js#12533]
According the WebGL spec, there is a `powerPreference` option when requesting a webgl context:
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2.1

I'm not sure how and if the current browsers supports this, but it seems "mentioned" in either chromium ([code](https://cs.chromium.org/search/?q=powerPreference&sq=package:chromium&type=cs)) and webkit ([code](https://github.com/WebKit/webkit/search?utf8=%E2%9C%93&q=powerPreference&type=)) codebase.

Currently, is not possible to pass any additional parameter, unless you create and pass a context outside three js:
https://github.com/mrdoob/three.js/blob/b83561c04ef7f73e47534b14b6267a6b2c748161/src/renderers/WebGLRenderer.js#L205

I propose either to add a `powerPreference` param for WebGLRenderer or allow "custom" params.

What do you think?

**Comment by Mugen87** [comment]
I vote for a new `powerPreference` parameter.

**Comment by mrdoob** [comment]
Sounds good yeah. @luruke would you like to do a PR?

**Comment by luruke** [comment]
@mrdoob I will

**Comment by luruke** [comment]
Pull request #12753

**Comment by felixturner** [comment]
does it do anything?

**Comment by mrdoob** [comment]
@felixturner I think it does in Safari, but I have not tested it.
