### ISSUE TITLE
Obj Loader read its property and set the path

### ISSUE THREAD

**Issue by sandipJava** [mrdoob/three.js#12542]
I created one 3d Map .obj (Using 3d max).  Then I loaded this map using three.js. Then I created one cube. This cube must be move on the road. how I can read the obj property and how I can set road on the map., Now this cube going in white space. Currently I gave manual road path for  moving cube.
Please share ur mail then I can send you obj files. Please Help me.

![new map 2](https://user-images.githubusercontent.com/32532237/32207989-9d0137ee-be25-11e7-8180-22d7a19250da.jpg)
![new map](https://user-images.githubusercontent.com/32532237/32207992-a10c4856-be25-11e7-8271-a4b8232bf1c8.jpg)

code: 
[ObjLoader.txt](https://github.com/mrdoob/three.js/files/1429632/ObjLoader.txt)

**Comment by sandipJava** [comment]
see example... https://threejs.org/examples/webvr_rollercoaster.html

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help questions.
