### ISSUE TITLE
[gltf] 	 'THREE.GLTFLoader: Duplicating UVs to support aoMap.' ?

### ISSUE THREAD

**Issue by sonygod** [mrdoob/three.js#12544]
hi,my mode have two uv  channels, the uv2 for AO,but the three.js render error!
![image](https://user-images.githubusercontent.com/748320/32213313-aaab80ae-be55-11e7-97cb-b7555b7b88fb.png)

this is right show.
![image](https://user-images.githubusercontent.com/748320/32213324-b62e501e-be55-11e7-9b23-b90c7b953498.png)

![image](https://user-images.githubusercontent.com/748320/32213346-d32b8ef2-be55-11e7-9d4e-829634177065.png)

**Comment by takahirox** [comment]
Can you share your glTF file with us for the test?

**Comment by donmccurdy** [comment]
Closing — please reopen with your example file(s) if this still a problem.

**Comment by ranbuch** [comment]
@donmccurdy I have found the same issue [here](https://gltf-viewer.donmccurdy.com/#kiosk=1&model=https://www.khronos.org/assets/gltf/BusterDrone.glb), looks more like a feature though.

Can you please explain what `Duplicating UVs to support aoMap` means?

**Comment by looeee** [comment]
@ranbuch please ask on the [forum](https://discourse.threejs.org/) if you need help.
