### ISSUE TITLE
https://discourse.threejs.org/t/obj-loading-and-make-road-path-on-it-see-description-and-image/1105?u=sandipnd31

### ISSUE THREAD

**Issue by sandipJava** [mrdoob/three.js#12545]
https://discourse.threejs.org/t/obj-loading-and-make-road-path-on-it-see-description-and-image/1105?u=sandipnd31

**Comment by Mugen87** [comment]
It is no good style to clutter the issue section with your help request. Please focus on the forum and stackoverflow.

**Comment by sandipJava** [comment]
@Mugen87  Sir , Help me to solve my issue

**Comment by sandipJava** [comment]
@Mugen87  See forum link https://discourse.threejs.org/t/obj-loading-and-make-road-path-on-it-see-description-and-image/1105?u=sandipnd31
