### ISSUE TITLE
how to rotate a object around a special point

### ISSUE THREAD

**Issue by trymoremore** [mrdoob/three.js#12547]
i want to rotate a object around the read point like this :
![i](https://user-images.githubusercontent.com/27277007/32219440-2e32c604-be69-11e7-8d72-bd957886f0e8.jpg)

but the fact is this:
![image](https://user-images.githubusercontent.com/27277007/32219518-6566bad6-be69-11e7-9b63-9487d67004aa.png)

this is my code :
gz.position.set(0,-50,0);
gz.rotation.x+=-0.1*Math.PI;

**Comment by sandipJava** [comment]
@trymoremore  I have also same problem I want to move cube on the obj

**Comment by Dev-Jareth** [comment]
Have a look at https://stackoverflow.com/questions/15214582/how-do-i-rotate-some-moons-around-a-planet-with-three-js
Is this what you mean
