### ISSUE TITLE
Which is the best loader in Three.js?

### ISSUE THREAD

**Issue by sandipJava** [mrdoob/three.js#12553]
I want to do some operation on 3d external file. for example I want to read file x y z axis, I want to restrict or set boundary on that 3d file. Which is the best loader to do operations.

**Comment by Mugen87** [comment]
I think it's sufficient to ask the question at one place.

https://discourse.threejs.org/t/which-is-the-best-loader-in-three-js/1120

I'll send you there a post with some information about loaders in `three.js`.
