### ISSUE TITLE
Docs: Buffergeometry .normals attribute clarification

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#12559]
The description of the .normals attribute in the [buffergeometry docs](https://threejs.org/docs/#api/core/BufferGeometry) says:

> Stores the x, y, and z components of the face or vertex normal vector of each vertex in this geometry.

But as far as I am aware only vertex normals are supported in WebGL.

**Comment by WestLangley** [comment]
Thanks. An improvement would be:

>Stores the x, y, and z components of the vertex normal vector of each vertex in this geometry.

**Comment by looeee** [comment]
Yeah I figured - I was just wondering if we should clarify that face normals are interpolated if converting from a geometry that has them.

**Comment by looeee** [comment]
Sorry, I'm wrong - the face normals from a geometry are duplicated, not interpolated.

https://github.com/mrdoob/three.js/blob/c1afee8fea2157a3846b7b9bdf00d4f69d7076eb/src/core/DirectGeometry.js#L160

I'll update the docs now, your suggestion is fine.
