### ISSUE TITLE
Mysterious Points (BUG?)

### ISSUE THREAD

**Issue by wolfgangvonludwigsburg** [mrdoob/three.js#12550]
##### Description of the problem 
In search for some serious larger threejs visualization projects, I found the "mother" of all animation efforts,
I think it's ROME - "3 Dreams of Black".

Wanting to start to analyse the basic mesh, I took these files

https://github.com/dataarts/3-dreams-of-black/blob/master/tests/cityShader/assets/city/City.Ground1_.008.js
https://github.com/dataarts/3-dreams-of-black/blob/master/tests/cityShader/assets/city/Ground1.jpg

and combined it with my own test file, which I put into the examples folder of my current threejs-folder.
( in City.Ground1_.008.js I uncommented these 2 lines near EOF: //postMessage( model ); //close(); )
=> see attachment

I have "uppend" the points a little bit, so they should appear BEFORE the textured ground plane ...

Please try my test file;
initially, and at certain camera z-distances (pls scroll your mouse!) the points are somehow "disappearing" ... ?!

I hope, I have done nothing wrong by posting this.

BTW,
- Did someone refactor '3-dreams-of-black' already to some actual threejs-version ?
- Does someone have a conversion tool, to convert JSON Version 2 models right into JSON Version 4 ?
- Concerning https://github.com/mrdoob/rome-gltf ... - is JSON Version 4 "up to date",
  or is GLTF the future format ?

Best Wishes, Wolfgang

##### Attachment
[City.Ground1_.008_points.zip](https://github.com/mrdoob/three.js/files/1432472/City.Ground1_.008_points.zip)

##### Three.js version

- [x] Dev
- [x] r87
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Core i7-3770 Integrated Graphics

**Comment by looeee** [comment]
@wolfgangvonludwigsburg the [forum](https://discourse.threejs.org/) is probably a better place to discuss this.

**Comment by wolfgangvonludwigsburg** [comment]
@looeee may I ask, could you verify the issue on your system?

![mysterious points](https://user-images.githubusercontent.com/9339385/32262241-d0fbd622-bed3-11e7-9b71-5df79ca6c413.jpg)
camera.position.z:

Points NOT visible at 200000
Points NOT visible at 190000
Points     visible at 180500
Points NOT visible at 171475
...
(alternating visible/not visible)

I presume, it is a concern of the underlying shaders.

**Comment by wolfgangvonludwigsburg** [comment]
The better ISSUE title should be:
**PointsMaterial over textured MeshBasicMaterial does'nt render consistently on long-dimensioned camera positions(e.g. 10*1e3)**

I simplified the test code (put this into your three-examples folder):

```
<body>
<script src='../build/three.js'></script>
<script src='js/controls/OrbitControls.js'></script>
<script src='js/libs/dat.gui.min.js'></script>
<script>

    const renderer=new THREE.WebGLRenderer
    renderer.setSize(window.innerWidth,window.innerHeight)
    document.body.appendChild(renderer.domElement)

    const scene=new THREE.Scene
    scene.background=new THREE.Color( 0x666666 )

    const camera=new THREE.PerspectiveCamera(75,window.innerWidth/window.innerHeight,0.1,1 *1e6)
    camera.position.set(0,0,200 *1e3)
    new THREE.OrbitControls(camera, renderer.domElement)

    scene.add( new THREE.AxisHelper(200 *1e3/2) )
    scene.add( new THREE.GridHelper(200 *1e3  ) )

    //points
    const geometry = new THREE.Geometry
    geometry.vertices.push( new THREE.Vector3(0,0,0) )
    var points = new THREE.Points(
        geometry,
        new THREE.PointsMaterial({
            color   : 0x000000,
            size    : 1 *1e5
        })
    );
    points.position.set(0,0,10 *1e3)
    scene.add( points );

    //plane
    const map=new THREE.TextureLoader().load('textures/perlin-512.png')
    const plane=new THREE.Mesh(
        new THREE.PlaneGeometry(200 *1e3,200 *1e3),
        new THREE.MeshBasicMaterial({
            map     : map
        })
    )
    scene.add(plane)

    //GUI
    const gui=new dat.GUI({width:300})
    gui.add(camera.position ,'z'         ,100 *1e3,300 *1e3 ).listen() .name('camera.position.z'    )
    gui.add(points.material ,'size'      ,  1 *1e3,  3 *1e5 ).listen() .name('points.material.size' )
    gui.add(plane           ,'visible'                      ).listen() .name('plane.visible'        ).onChange(value=>plane .visible=value)
    gui.add(points          ,'visible'                      ).listen() .name('points.visible'       ).onChange(value=>points.visible=value)

    //render
    setInterval(()=>{
        renderer.render(scene,camera)
    },100)

</script>

```

**Comment by donmccurdy** [comment]
I can't comment on the different JSON versions, but any of the ROME glTF assets should work with the latest THREE.GLTFLoader:

https://gltf-viewer.donmccurdy.com/#model=https://raw.githubusercontent.com/mrdoob/rome-gltf/master/files/models/life_soup/quadruped_fox.gltf

They may require double-side materials, which the viewer above and files themselves do not set.

**Comment by WestLangley** [comment]
Increase your near plane to 100.

See [this SO answer](https://stackoverflow.com/questions/26717513/stl-rendering-with-threejs/26725521#26725521).

Also, [this article](http://www.songho.ca/opengl/gl_projectionmatrix.html).
