### ISSUE TITLE
Raycaster not working with initially zero-length lines

### ISSUE THREAD

**Issue by matpen** [mrdoob/three.js#12567]
I am new to three.js, so firstly I would like to thank for a great library.

Next, here is the problem I am facing. The raycaster seems not to work when used with a line that was created with two overlapping points (that is, if the line had **originally** zero length). The raycaster continues **not** to detect the line, even if the vertices have changed and the line has a non-zero length **afterwards**.

On the other hand, if the line had originally non-zero length, its vertices can be modified at will (even by bringing the line length to zero) and the raycaster still works correctly.

Here is a test in form of a [jsFiddle](http://jsfiddle.net/kskf727e/) and as a [gist](https://gist.github.com/matpen/a18572b4d52a59631105c483a69c1b89).

And here are my specs:
- three.js r87
- Firefox 56.0 and Chrome 62.0 0.3202.75
- Ubuntu 16.04 64-bit

I would like to point out that this issue might affect other kinds of entities, e.g. cubes, if their spatial extension was initially zero. I just did not test that, yet.

**Comment by makc** [comment]
maybe you need to update bounding sphere / box on the geometry

**Comment by matpen** [comment]
Yes, that solves the issue. Thank you for the quick reply and sorry for the noise: my google-fu failed me this time!
