### ISSUE TITLE
[bug?] Value of 'premultipliedAlpha' has no effect?

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#12563]
##### Description of the problem 

When I change the value of `premultipliedAlpha` to `false` the result is the same.

For example:

- http://jsfiddle.net/gxnr75wn/3
- http://jsfiddle.net/gxnr75wn/4

I thought the difference would be something like this, when doing it with vanilla WebGL:

- http://jsfiddle.net/Px65h/376
- http://jsfiddle.net/Px65h/377

In those last two examples, it is easy to see the difference. I was expecting the same difference with the Three.js examples.

##### Three.js version

- [x] r88

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [x] Chrome OS

##### Hardware Requirements (graphics card, VR Device, ...)

N/A

**Comment by WestLangley** [comment]
There shouldn't be any difference if you specify your colors correctly.

What you have implemented in your example is not valid code when `premultipliedAlpha` is `true`.
```glsl
gl.clearColor( 1.0, 0, 0, 0.5 ); // .a can't be greater than .alpha
```
It should be
```glsl
gl.clearColor( 0.5, 0, 0, 0.5 );
```
Read the three.js source code so you understand the decisions we made when we implemented this feature.

I would not change the renderer's `premultipliedAlpha` setting unless you really know what you are doing. `NormalBlending` in three.js requires that `premultipliedAlpha` be set to `true`, the default.
