### ISSUE TITLE
Should FBXLoader return indexed geometry?

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#12560]
I've been testing returning indexed buffer geometry with the FBXLoader, and it looks like it should be possible (at least, I have it working for some simple models consisting of just vertices and normals).

It certainly reduces duplication of vertex info a lot, especially when dividing up quads. 

Getting the indexing to work with  complex models with skinning data will be quite a bit of work though, so before I go ahead, is this something that is worth the effort? Or are there potential negative effects from doing this?

**Comment by makc** [comment]
they gave up on this in other loaders. I liked how it used to parse into Geometry and you could then (in theory) convert to indexed BufferGeometry or not, depending on how you wanted it. but now when the Geometry is hated, they just do 3 unique vertices per triangle.

**Comment by WestLangley** [comment]
>is this something that is worth the effort?

If you were determined to do it, I would create `BufferGeometry.toIndexed()`, instead.

**Comment by makc** [comment]
> BufferGeometry.toIndexed()

this would have no means to preserve hard edges

**Comment by WestLangley** [comment]
Right. three.js is not modeling software.

**Comment by looeee** [comment]
> If you were determined to do it, I would create BufferGeometry.toIndexed(), instead.

The reason I'm suggesting it here is that FBX is already storing data in an indexed format, at least for vertex positions. Every mesh geometry has at least these two properties:

https://github.com/mrdoob/three.js/blob/05d67e9fb68e19adb17400d32e4964f1debd52cd/examples/js/loaders/FBXLoader.js#L669-L670

Things get a bit more complex for other properties (material indexes, normals, uvs etc) which can be stored in a few different ways (combinations of indexed or direct and per vertex, per polygon or per polygon vertex).

**Comment by makc** [comment]
@looeee I believe now that it is pointless to ask people to do the opposite of what they want to with their project, just look:
> three.js is not modeling software.
:D
especially when you can't really offer the solution that will make everyone happy. so when I need controversial feature like original inidces I just use old loaders from git history, or hack the code. so, for your question, why dont you just make sure that indices will be easy for interested people to hack in, and leave it at that?

**Comment by looeee** [comment]
@makc I was just asking this question to try and understand whether it's worth the effort to try and make the FBXLoader return indexed buffer geometry. From my understanding, indexed geometry has two advantages: 

* lower memory requirements 
* faster vertex shader since there are potentially a lot less vertices to do the operations on 

However I don't know if there are corresponding disadvantages (aside from the obvious one that the code is more complex to write), hence asking this question. 

@WestLangley  I think you are suggesting something different here - I want to create an indexed buffer geometry directly, not via an unindexed geometry which I then convert, since it appears that the information to do so is already contained in the FBX format.

I would need to investigate further to see whether this is actually possible, and I'm just wondering if this is something that is desirable before I go ahead and do that. If it's a bad idea for some reason then I would be better to spend my time improving some other part of the loader instead.

**Comment by looeee** [comment]
Closing for now - seems like the fact that WebGL has only only index per geometry is a bit of a sticking point, since FBX format has lots of indices. It might be possible to remap these onto the single index but that's a problem to consider another day 😁

**Comment by mrdoob** [comment]
> From my understanding, indexed geometry has two advantages:
> * lower memory requirements 
> * faster vertex shader since there are potentially a lot less vertices to do the operations on 

I was once told that, often, drivers convert indexed geometries to flat geometries before uploading to the gpu for compatibility reasons.

**Comment by looeee** [comment]
Interesting. That would make it doubly not worth the effort then.
