### ISSUE TITLE
Feature request: Types of arguments in documentation 

### ISSUE THREAD

**Issue by Itee** [mrdoob/three.js#12580]
Next to #12574 part 1

Currently we was have access to the variable type using hovering in the documentation. But it is maybe unusable on mobile. And is not guess to know !

The proposal is to add the type and when possible the range of the parameters.

Example: 

`fooParam - The fooParam of the bar class. A Floating point number, in the range 0.0 - 1.0 with default to null`

instead of

`fooParam - The fooParam of the bar class. Default to null`

**Comment by Itee** [comment]
/ping @mrdoob So what is your opinion ?

**Comment by haroldiedema** [comment]
> "Currently we was have access to the variable type using hovering in the documentation."

I've been using THREE for a few years now and find myself going to the docs for reference on a regular basis. Just to prove the usefulness of this, I've never known this "feature" was there.

**Comment by Mugen87** [comment]
> Why don't we use a JSDoc standard in the code and generate documentation based on that?

This was already discussed a number of times, see #2869, #4725, #11550

I think the approach of the project is clear: https://github.com/mrdoob/three.js/issues/3445#issuecomment-17605827

**Comment by haroldiedema** [comment]
Ah my apologies, I wasn't aware.

**Comment by Mugen87** [comment]
No problem

**Comment by WestLangley** [comment]
@haroldiedema Thanks for your suggestion, anyway.

**Comment by mrdoob** [comment]
Another issue of JSDocs I've recently realised is that it doesn't scale to docs localisation (not that our docs have been localised yet anyway... 😛)

**Comment by mrdoob** [comment]
@Itee can you point me to a docs page were that change is applicable?

**Comment by Itee** [comment]
@mrdoob Almost everywhere in the doc ?!

But if you want some listing:

- [timeScale](https://threejs.org/docs/#api/animation/AnimationAction): A value of 0 causes the animation to pause. Negative values cause the animation to play backwards. Default is 1. _We got a 0, a 1, and negative values... So are we in a range like: -1 -> 1, -1.0 -> +1.0,  or -Inf -> +Inf ?_
- [weight](https://threejs.org/docs/#api/animation/AnimationAction): The degree of influence of this action (in the interval [0, 1]). Values between 0 (no impact) and 1 (full impact) can be used to blend between several actions. Default is 1. _This one is perfectly clear !_
- [PropertyMixer](https://threejs.org/docs/#api/animation/PropertyMixer): ...
- [far](https://threejs.org/docs/#api/cameras/OrthographicCamera): Camera frustum far plane. Default is 2000. The valid range is between the current value of the near plane and infinity. _Could i use negative values ?_
- [zoom](https://threejs.org/docs/#api/cameras/OrthographicCamera) Gets or sets the zoom factor of the camera. Default is 1. _Zoom range is ?_
- etc... etc...

Maybe this could be normalized during doc generation ?

**Comment by looeee** [comment]
far: Camera frustum far plane. Default is 2000. The valid range is between the current value of the near plane and infinity.

near: Camera frustum near plane. Default is 0.1. The valid range is greater than 0 and less than the current value of the far plane.

I don't see how this one could be much clearer. 

> Maybe this could be normalized during doc generation ?

Docs are written by hand, not generated. 

Automatically generated docs tend to be pretty horrible to read.

**Comment by Itee** [comment]
@looeee 

> Docs are written by hand, not generated.

Ok I thought there was some helpers or templates somewhere.
