### ISSUE TITLE
Black screen in chrome at first load

### ISSUE THREAD

**Issue by churmstech** [mrdoob/three.js#12589]
when i open three js site in chrome v61 browser show black screen but after 2-3 time reload it looks fine and objects show grate result i know it is due to rotation of object that is created in render function the code is  given below
```javascript
var mesh, mesh2, mesh3;

var renderer = new THREE.WebGLRenderer({canvas: document.getElementById('myCanvas'), antialias: true});
renderer.setClearColor(0xffffff);
renderer.setPixelRatio(window.devicePixelRatio);
renderer.setSize(window.innerWidth, window.innerHeight);
//document.body.appendChild(renderer.domElement);
var camera = new THREE.PerspectiveCamera(35, window.innerWidth / window.innerHeight, 0.1, 3000);
camera.position.set(0,0,0);
var scene = new THREE.Scene();
var light = new THREE.AmbientLight(0xffffff, 0.75);
light.position.set(150, 1500, 1500);
scene.add(light);

var light1 = new THREE.PointLight(0xffffff, 0.5);
scene.add(light1);

var loader = new THREE.JSONLoader();
loader.load('crystal.json', handle_load);

function handle_load(geometry, materials){
	var materials = new THREE.MeshLambertMaterial({
		color: 0x79CDDC,
	});
	 mesh = new THREE.Mesh(geometry, materials);
	scene.add(mesh);
	mesh.position.z = -5.5;
	mesh.position.y = 0;	

}

var loader2 = new THREE.JSONLoader();
loader2.load('crystal2.json', handle_load2);

function handle_load2(geometry2, materials2){
	var materials2 = new THREE.MeshLambertMaterial({
		color: 0xff4d97,
	});
	mesh2 = new THREE.Mesh(geometry2, materials2);
	scene.add(mesh2);
	mesh2.position.z = -18;	
	mesh2.position.x = 6;	
}

var loader3 = new THREE.JSONLoader();
loader3.load('crystal2.json', handle_load3);

function handle_load3(geometry2, materials2){
	var materials2 = new THREE.MeshLambertMaterial({
		color: 0x4c00a9,
	});
	mesh3 = new THREE.Mesh(geometry2, materials2);
	 
	scene.add(mesh3);
	mesh3.position.z = -14;	
	mesh3.position.x = 3.2;	
	mesh3.position.y = -2.8;
}

requestAnimationFrame(render);

function render(){

	mesh.rotation.y =  (window.scrollY * 5) * 0.001;

	renderer.render(scene, camera);
	requestAnimationFrame(render);
	mesh2.rotation.y = 2.7 + (window.scrollY * 5) * 0.001;
	mesh3.rotation.x =  (window.scrollY * 5) * 0.001;

}
```

**Comment by churmstech** [comment]
when i open three js site in chrome v61 browser show black screen but after 2-3 time reload it looks fine and objects show grate result i know it is due to rotation of object that is created in render function the code is  given below

<script>
			var mesh, mesh2, mesh3;
			
        	var renderer = new THREE.WebGLRenderer({canvas: document.getElementById('myCanvas'), antialias: true});
			renderer.setClearColor(0xffffff);
			renderer.setPixelRatio(window.devicePixelRatio);
			renderer.setSize(window.innerWidth, window.innerHeight);
			//document.body.appendChild(renderer.domElement);
			var camera = new THREE.PerspectiveCamera(35, window.innerWidth / window.innerHeight, 0.1, 3000);
			camera.position.set(0,0,0);
			var scene = new THREE.Scene();
			var light = new THREE.AmbientLight(0xffffff, 0.75);
			light.position.set(150, 1500, 1500);
			scene.add(light);
			
			var light1 = new THREE.PointLight(0xffffff, 0.5);
			scene.add(light1);
			
			var loader = new THREE.JSONLoader();
			loader.load('crystal.json', handle_load);
			
			function handle_load(geometry, materials){
				var materials = new THREE.MeshLambertMaterial({
					color: 0x79CDDC,
				});
				 mesh = new THREE.Mesh(geometry, materials);
				scene.add(mesh);
				mesh.position.z = -5.5;
				mesh.position.y = 0;	
				
			}
			
			var loader2 = new THREE.JSONLoader();
			loader2.load('crystal2.json', handle_load2);
			
			function handle_load2(geometry2, materials2){
				var materials2 = new THREE.MeshLambertMaterial({
					color: 0xff4d97,
				});
				 mesh2 = new THREE.Mesh(geometry2, materials2);
				scene.add(mesh2);
				mesh2.position.z = -18;	
				mesh2.position.x = 6;	
				
			}
			
			var loader3 = new THREE.JSONLoader();
			loader3.load('crystal2.json', handle_load3);
			
			function handle_load3(geometry2, materials2){
				var materials2 = new THREE.MeshLambertMaterial({
					color: 0x4c00a9,
				});
				 mesh3 = new THREE.Mesh(geometry2, materials2);
				 
				scene.add(mesh3);
				mesh3.position.z = -14;	
				mesh3.position.x = 3.2;	
				mesh3.position.y = -2.8;
				
			}
			
			
			requestAnimationFrame(render);
			function render(){
				
				mesh.rotation.y =  (window.scrollY * 5) * 0.001;
				
				renderer.render(scene, camera);
				requestAnimationFrame(render);
				mesh2.rotation.y = 2.7 + (window.scrollY * 5) * 0.001;
				mesh3.rotation.x =  (window.scrollY * 5) * 0.001;
			}
			
        </script>

**Comment by Freeman555** [comment]
@churmstech 
U use json file from local PC, pls put code on website like http://jsfiddle.net/ or https://codepen.io/ to reproduce problem.

**Comment by sujatakhatal53** [comment]
Hi @Mugen87  , I know you have closed this issue. but can you tell how you have resolved this issue? I am struggling for same. My three.js code shows black screen before scene loads.
can you help me to resolve this?

**Comment by mrdoob** [comment]
We use GitHub issues to track confirmed bug reports and feature development.
If you need help, please use the [forum](https://discourse.threejs.org/), the [chat](https://discord.gg/HF4UdyF) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
