### ISSUE TITLE
directX.x loader bug

### ISSUE THREAD

**Issue by marshall-hunts** [mrdoob/three.js#12599]
i tried loading my model in the new x-loader but it's returning cannot read property name of null

[https://jsfiddle.net/48xkyp1m/](url)

here's the log file:-

three.min.js:173 THREE.WebGLRenderer 88
three.min.js:145 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
get @ three.min.js:145
XLoader.js:1457 Uncaught TypeError: Cannot read property 'name' of null
    at THREE.XLoader.XAnimationObj.make (XLoader.js:1457)
    at THREE.XLoader.animationFinalize_step (XLoader.js:1362)
    at THREE.XLoader.animationFinalize_step (XLoader.js:1373)
    at THREE.XLoader.animationFinalize (XLoader.js:1331)
    at XLoader.js:206

Here's the diectx.x model:
[https://cdn.rawgit.com/marshall-hunts/game-assets/master/monster.x](url)

**Comment by Itee** [comment]
Your link is dead, use this one:

[https://jsfiddle.net/48xkyp1m/](https://jsfiddle.net/48xkyp1m/)

**Comment by Itee** [comment]
The bone 103 named 'Tree' haven't parent. The method make should be protected about case like this, but maybe could you find a work around with this info ?

**Comment by Itee** [comment]
Here the fiddle with an overload of make methods, i got the skeleton and break geometry but this is a start.

[https://jsfiddle.net/n4unsfao/](https://jsfiddle.net/n4unsfao/)

**Comment by adrs2002** [comment]
sorry, i'll check after 12 hours.

but, i made xloader v2.0 is here
https://github.com/adrs2002/threeXfileLoader/blob/v2.0/threeXLoader.js

can you try and report this ?

**Comment by marshall-hunts** [comment]
update: 
https://jsfiddle.net/n4unsfao/4/

seems like it can't read the frame.

i also tried it with this model:

https://cdn.rawgit.com/mrdoob/three.js/r88/examples/models/xfile/SSR06_Born2.x

but's it showing the exact same thing in the log file

**Comment by marshall-hunts** [comment]
@Itee 
https://jsfiddle.net/n4unsfao/3/

the model loads, but couldn't play the animation
 i also tried playing the animation in open3mod and it plays perfectly well

**Comment by adrs2002** [comment]
@marshall-hunts 

this file ( monster.x ) is likely [ scene ] file.  2 skinnedMesh into 1 file.
threeXLoader.js is Support [ one (skinned) Mesh ] file  now.

I can try read scene file, but I think it will take some time.

**Comment by marshall-hunts** [comment]
@adrs2002 
Can you check out this file if it works; it has one skinned mesh

https://cdn.rawgit.com/marshall-hunts/game-assets/master/2monwolv.x

**Comment by adrs2002** [comment]
@marshall-hunts 
thanks file.

[ 2monwolv.x ] is too many allocation bone weights of 1 vertex. 
in three.js, max 4 allocate weights of vertex.
Can you fix vertices?

**Comment by marshall-hunts** [comment]
@adrs2002 
https://raw.githubusercontent.com/marshall-hunts/game-assets/master/2refor.x

it's fixed

**Comment by adrs2002** [comment]
hmmm.. sorry waiting.
http://adrs2002.com/sandbox/xloader/xfileTest_dummy.html
i think, just a little more.... but I do not know the last one..

**Comment by adrs2002** [comment]
@marshall-hunts 

OK, LGTmyself. please check !
http://adrs2002.com/sandbox/xloader/xfileTest_dummy.html

https://raw.githubusercontent.com/adrs2002/threeXfileLoader/master/threeXLoader.js
