### ISSUE TITLE
Exporting Morph Targets is still broken

### ISSUE THREAD

**Issue by lovemoebius** [mrdoob/three.js#12595]
After being very confused on how to actually export Morph Targets I found this thread

https://github.com/mrdoob/three.js/issues/8710

It doesn't seem like following what @filmshaw posted works at all. Not commenting out the the part of the code seems to add an Edgesplit to my mesh every time I try to export it. Which, in return, gives me the error that I can't export a mesh with modifiers and shape keys.

![yv75icpy35za_blender_2017-11-06_23-25-56 1](https://user-images.githubusercontent.com/23533178/32469299-eba3f8e0-c349-11e7-9637-d0547088e2f6.png)

Which I suppose is what should be happening.

However, if I do comment out the code I just receive this error

![zffqbvfowsqj_blender_2017-11-06_23-28-22 1](https://user-images.githubusercontent.com/23533178/32469384-4e698440-c34a-11e7-9f55-ce1a834f53d7.png)

I don't know if I'm just very confused as to how to go about this, but I can't seem to get it working. Is there a specific fix I'm missing for this specific issue or is this still open?

**Comment by lovemoebius** [comment]
I tried fiddling with the object.py mentioned in the other thread.

It seems like uncommenting [line 496 of object.py](https://github.com/mrdoob/three.js/blob/dev/utils/exporters/blender/addons/io_three/exporter/api/object.py#L496) leads to a successful export that seems to have all the morph targets.
The file loads and displays correctly, however I have yet to try the morph targets.

**Comment by derivou** [comment]
Hello, I exported my model following the recommandation about the object.py file and got a loadable three.js file. BUT the animation is wrong ; it is a smoothed cube like shape and in Blender I deform just a few vertex ; in Three.js it results in a kind of rotation/elongation of the whole object. My material is a shader material using a copy of the phong vertex shader and the frag is phong. Any help ?

**Comment by lovemoebius** [comment]
I ended up asking another question over here https://github.com/mrdoob/three.js/issues/12623#issuecomment-345324743 about the same exact problem. 

As far as I understand it the exporter is either broken or not compatible with threejs. I was having your exact same problem and I couldn't find any solutions no matter how much I fiddled with the code or the exported itself. 

Using a glTF exporter seems to fix the issue, however I have not been able to export to gltf while having a lot of morph targets. Blender just hangs forever on the exporting screen. 

I used this https://github.com/KhronosGroup/glTF-Blender-Exporter to export it. 
This https://github.com/Kupoman/blendergltf seems to also do the same, however last time I checked it did not export morph targets.

**Comment by derivou** [comment]
ok I updated to r88 and blender 2.79 ; as I have the same result, I tried this : in my three.js code I inverted Y=Z and  Z=-Y for Mesh.Geometry.morphAttributes.position[0].array ; Then it works. So, there is somewhere inversion of Y and Z ...

**Comment by derivou** [comment]
Hi ,may I ask what is the current status of the io_three blender exporter ? is there any change in the different issues ?

**Comment by Mugen87** [comment]
It's better if focus on another format and exporter. Read #12903 for more information.

**Comment by derivou** [comment]
Oh thanks I was not aware of this. So for objects combining skeleton animation and shape keys there is currently no workflow with no issues.

**Comment by looeee** [comment]
@derivou FBXLoader supports skeletal animation and morph targets. 

However, I have no idea whether the blender exporter will successfully export them.

**Comment by derivou** [comment]
OK thanks for recommandations. I will follow the KhronosGroup  ...

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
