### ISSUE TITLE
Inconsistent matrix ordering in API

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#12602]
##### Description of the problem 

Some parts of the API are inconsistent with internals when it comes to matrices.

`Matrix4#elements` is in row-major order, while `Matrix4#set` expects arguments in column-major order (or maybe I've got the term backwards. The `Matrix4#copy` method accepts a matrix in the opposite ordering as the argument for `Matrix4#set`.

This is not intuitive, and when someone messes up due to providing a matrix in the wrong order, the problem is strange and hard to find.

For example, take this fiddle where the box moves up and to the right:

http://jsfiddle.net/ft08jqyv/6

If one uses `Matrix4#elements` instead of `Matrix4#set`, then the result is very strange and unexpected:

http://jsfiddle.net/ft08jqyv/7

Problems caused by this can be hard to find and debug, unless the author remembers what he modified recently to go take a look at what changed.

I think it's a good idea to have consistency in the API.

##### Three.js version

- [x] r88

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by trusktr** [comment]
For reference, one might want to intuitively do this:

```js
object.matrix.set( ...otherObject.matrix.elements )
```

but that won't work. They'll have to take the more complicated approach:

```js
const m = otherObject.matrix.elements
object.matrix.set(
  m[0], m[4], m[8], m[12],
  m[1], m[5], m[9], m[13],
  m[2], m[6], m[10], m[14],
  m[3], m[7], m[11], m[15],
)
```

otherwise their resulting matrix will be unintentionally flipped.

**Comment by trusktr** [comment]
Furthermore, the `set` method has the opposite ordering of the `copy` method; room for further confusion.

**Comment by trusktr** [comment]
I may have swapped the row-major and column-major terms, but if the API were consistent, I wouldn't be confused at all; I wouldn't have to think about swapping anything and/or whether they are "row" or "column" major.

**Comment by trusktr** [comment]
PR: https://github.com/mrdoob/three.js/pull/12603

**Comment by WestLangley** [comment]
This issue was addressed in https://github.com/mrdoob/three.js/issues/3814.

**Comment by trusktr** [comment]
So, leave as is?

**Comment by WestLangley** [comment]
Yes.
