### ISSUE TITLE
ColladaLoader: Automatically setting of path breaks loading via files

### ISSUE THREAD

**Issue by cnspaha** [mrdoob/three.js#12609]
With the ColladaLoader I have the following problem.
When trying to load a model via files (instead of url) it won't find textures.
I used the approach to load the files described in https://github.com/mrdoob/three.js/pull/12591#issuecomment-342179286

But unfortunately the the ColladaLoader always extracts an url base path from the passed .dae file and if it is empty it sets it to './' . IMO it is just wrong. If I want to have an path set I should set it on my own.

So for example in 'extraFiles' (see linked comment above) I have the key 'filename.png' but it tries to access './filename.png' (because of the default behaivour to set './' ) which of course doesn't exists.

So my suggestion is to rewrite it like it is in the ObjLoader:

Before:
```javascript
	load: function ( url, onLoad, onProgress, onError ) {

		var scope = this;

		var path = THREE.Loader.prototype.extractUrlBase( url ); // REMOVE THIS LINE!

		var loader = new THREE.FileLoader( scope.manager );
		loader.load( url, function ( text ) {

			onLoad( scope.parse( text, path ) );

		}, onProgress, onError );

	},
```

After:
```javascript
	load: function ( url, onLoad, onProgress, onError ) {

		var scope = this;

		var loader = new THREE.FileLoader( scope.manager );
		loader.setPath( scope.path );
		loader.load( url, function ( text ) {

			onLoad( scope.parse( text, scope.path ) );

		}, onProgress, onError );

	},
	
	setPath: function ( value ) {

		this.path = value;

	},
```

The only problem I see with this new approach is that it could break current implementations.
So probably we should make an fallback like:
```javascript
	load: function ( url, onLoad, onProgress, onError ) {

		var scope = this;

                scope.path = scope.path === undefined ? THREE.Loader.prototype.extractUrlBase( url ) : scope.path; 
		var loader = new THREE.FileLoader( scope.manager );
		loader.setPath( scope.path );
		loader.load( url, function ( text ) {

			onLoad( scope.parse( text, scope.path) );

		}, onProgress, onError );

	},
```
In this fallback case the user would at least get the possibility to set the path himself to an empty string ( '' ), if required.

@Mugen87 ;)

##### Three.js version
- [ x ] r88

##### Browser
- [x] All of them

##### OS
- [x] All of them

**Comment by Mugen87** [comment]
I like the suggestion. `THREE.GLTFLoader` handles this situation similarly. Do you want to make a PR for this :blush:?

**Comment by Mugen87** [comment]
see
https://github.com/mrdoob/three.js/blob/de50f388a85aaa27c3aec823405d77fe5ca1cb07/examples/js/loaders/GLTFLoader.js#L27

**Comment by cnspaha** [comment]
> I like the suggestion. THREE.GLTFLoader handles this situation similarly. Do you want to make a PR for this 😊?

Sure, I don't mind ;)

**Comment by cnspaha** [comment]
made PR from issue =>  https://github.com/mrdoob/three.js/pull/12614
