### ISSUE TITLE
how to limit the move of camera when check out the camera hit other object

### ISSUE THREAD

**Issue by trymoremore** [mrdoob/three.js#12600]
i use raycaster to check whether  the camera hit other object ,like this:
var distance = intersects[ 0 ].distance;
        if ( distance > 0 && distance < 10 ) {
            controls.isOnObject( true ); 
}
and when the camera hit other object i use "controls.isOnObject( true );" to stop the camera hit other object ,but it doesn't work ,and warm that controls.isOnObject is not a function.
i set controls as this : controls = new THREE.OrbitControls( camera,renderer.domElement);

**Comment by Mugen87** [comment]
`THREE.OrbitControls` does not have a method `. isOnObject()`.
