### ISSUE TITLE
Error while loading the screen after WebVR Trail update

### ISSUE THREAD

**Issue by kvskranthikumar** [mrdoob/three.js#12611]
##### Description of the problem 

After WebVR Trail update now we are getting below error -
"Cannot assign to read only property 'pose' of object '#'"

With WebVR chrome extension used.

https://threejs.org/examples/#webvr_cubes

##### Three.js version

- [ ] Dev
- [ ] r87
- [x] r88

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Chrome for Windows?

**Comment by kvskranthikumar** [comment]
Yes, it is chrome browser in Windows OS

**Comment by mrdoob** [comment]
What version of Chrome?

**Comment by kvskranthikumar** [comment]
Chrome - Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by mrdoob** [comment]
Oculus? Vive? ...

**Comment by kvskranthikumar** [comment]
WebVR API Emulation 1.1.4 - Chrome Browser on desktop in Windows 7

**Comment by mrdoob** [comment]
> WebVR API Emulation 1.1.4

What is that?

**Comment by takahirox** [comment]
Probably this Chrome extension

https://chrome.google.com/webstore/detail/webvr-api-emulation/gbdnpaebafagioggnhkacnaaahpiefil

**Comment by mrdoob** [comment]
Oh, I missed that from the first post...

> With WebVR chrome extension used.

Please, report this issue at the extensions' repo instead.

https://github.com/spite/WebVR-Extension
