### ISSUE TITLE
MaterialLoader doesn't handle textures correctly

### ISSUE THREAD

**Issue by Rolliboy** [mrdoob/three.js#12613]
##### Description of the problem 

Exporting material to JSON using Material.toJSON() method return an object that is not correctly parsed by MaterialLoader.
Here a fiddle to quickly see what I've done to get the error.

http://jsfiddle.net/akmcv7Lh/211/

##### Three.js version

- [ ] Dev
- [x] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Rolliboy** [comment]
I can't understand if I asked something strange or not understandable, just in case let me know! :)
I start to believe that I'm on a completely wrong way to handle materials and textures.

**Comment by Itee** [comment]
No no you're right !
`MaterialLoader` doesn't handle textures in JSON. Currently, you need to set them using `loader.setTextures()` intead.

I will take a look for 'fix it'

**Comment by Itee** [comment]
Wow... headache coming !

So i update you fiddle with a 'work arround'. 

The first time you will load the fiddle the second cube could be black ( why ? I really don't know ) but if you run again it will be correctly display as expected.

Here the updated fiddle: [http://jsfiddle.net/akmcv7Lh/243/](http://jsfiddle.net/akmcv7Lh/243/)

**Comment by Rolliboy** [comment]
Thank you @Itee 
Actually I'm currently parsing Textures of "Json Material" using a custom parser that I built.


Looping this array:
```
var maps: ["map", "roughnessMap", "metalnessMap", "alphaMap"]

maps.forEach(function(key) {
    JSONmaterial[key] = loader.load(JSONmaterial[key]);
}
```
Then I'm able to create material using:
`var newMaterial = new THREE.MeshStandardMaterial(JSONmaterial);`

Hoping there was a better and clean method but it's ok :)

**Comment by Tazshelby2016** [comment]
What is the state of this issue? It seems to be stale, and possibly able to be closed.

**Comment by mrdoob** [comment]
🤷‍♂️

**Comment by Mugen87** [comment]
I've review the issue closely today and updated the fiddle to the latest `three.js` version:

https://jsfiddle.net/eb7faq8j/1/

From my point of view, `MaterialLoader` works as expected. Before you parse a material from a JSON definition, it's necessary to set all used textures via `MaterialLoader.setTextures()`. This is normally done by `ObjectLoader`. If you use `MaterialLoader` by your own, you have to serialize and save textures separately.

Of course it's now valid to ask why `MaterialLoader` does not handle textures, too. The thing is that material are serialized own their own. Meaning you just call `material.toJSON()` like in the fiddle. Textures however might be shared across many materials. So it makes sense to just to save the `UUID` of a texture and use it later to restore shared textures.

The process requires some management which is normally performed by `ObjectLoader`. Like I said before, if you don't use this loader, you have to implement some of this logic on app level.

**Comment by Mugen87** [comment]
@mrdoob I think this issue can be closed (unless we want to refactor how serialization/deserialization of materials work).

**Comment by Tazshelby2016** [comment]
These old issues may have been fixed accidentally, I think they need to be went through. Especially the ones from 2013.

**Comment by Mugen87** [comment]
I've done this last year multiple times and most of them are conceptual issues (and thus have a long-term character).

**Comment by Tazshelby2016** [comment]
I see. But doesn't that mean that they should hold focus?

**Comment by donmccurdy** [comment]
Sort of a drive-by comment here, but I'd love to see more objects implement a `fromJSON` method, which classes like ObjectLoader could invoke, rather than putting that logic into ObjectLoader directly. A separate `MaterialLoader` class would then be unnecessary. Maybe not an urgent short-term priority, but that feels like a better long-term direction to me.

**Comment by Mugen87** [comment]
We actually have any issue for this^^: #11266
