### ISSUE TITLE
FBXLoader: Partial transparent maps doesn't work

### ISSUE THREAD

**Issue by cnspaha** [mrdoob/three.js#12625]
##### Description of the problem 

When loading a FBX file ( [succubus.zip](https://github.com/mrdoob/three.js/files/1461582/succubus.zip), it is the original file, no export ) via FBXLoader transparent parts of a map isn't taken into account.

The map, opened in Gimp so you can see the transparent parts, hair + feathers:
![unbenannt3](https://user-images.githubusercontent.com/22448974/32662101-a4f09218-c629-11e7-8630-c2dececf4c15.PNG)

What it should look like [Sketchfab](https://sketchfab.com/models/8c0746e3d1304ed283a3bb4772a8d2cc)
![unbenannt](https://user-images.githubusercontent.com/22448974/32662105-ab47fdc2-c629-11e7-8d8b-e7948e2f8457.PNG)

What it really looks like (my viewer):
![unbenannt2](https://user-images.githubusercontent.com/22448974/32662109-aebf165c-c629-11e7-9dac-749c9c5fc8c5.PNG)

The problem can be worked around with when applying following code on every mesh the FBXLoader creates:
```typescript
            ((obj as THREE.Mesh).material as THREE.Material).transparent = true;
            ((obj as THREE.Mesh).material as THREE.Material).side = THREE.DoubleSide;
            ((obj as THREE.Mesh).material as THREE.Material).alphaTest = 0.5;
```

But of course I don't want this code to be applied on every mesh because AFAIK transparency and alpha testing costs quite a bit of performance, especially if it isn't needed...

I am willingly to make a PR if I would know how to fix this.

One possible solution is that we would have to check ONLY the PART of the image being used per mesh if there is any transparency and if there is some then setting the transparent parameter on the material.

@Kyle-Larson @takahirox  since you both wrote this Loader, do you have any idea?
@Mugen87 @donmccurdy you both are pretty active on loader issues/PRs probably you could help here too? ;)

##### Three.js version

- [ x ] r88

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by donmccurdy** [comment]
Since the model is on Sketchfab already, you can download the glTF version there. It looks correct with r88 GLTFLoader, other than some transparency artifacts that aren't loader-related.

Preview on https://gltf-viewer.donmccurdy.com/:

<img width="410" alt="screen shot 2017-11-10 at 7 09 06 am" src="https://user-images.githubusercontent.com/1848368/32664480-2ef0c0f8-c5e6-11e7-8617-6de519f72cde.png">

Issue in the FBX file looks similar to https://github.com/mrdoob/three.js/issues/11598

**Comment by WestLangley** [comment]
If you are setting `alphaTest`, and your textures are cut-outs (no semi-transparency), there is no need to set `material.transparent = true`. And therefore, you should see no "transparency artifacts".

**Comment by donmccurdy** [comment]
That's good to know, thanks 🙂

the glTF asset from sketchfab doesn't set `alphaTest` but perhaps it should... trying a quick test after dragging the glTF into https://gltf-viewer.donmccurdy.com/ ...

```js
content.traverse((node) => {
  if (node.isMesh) {
    node.material.transparent = false;
    node.material.alphaTest = 0.5;
  }
});
```

i'm not getting the right result:

![screen shot 2017-11-10 at 8 39 58 am](https://user-images.githubusercontent.com/1848368/32668895-ab80d6f0-c5f3-11e7-8257-df411dd614c5.png)

**Comment by Mugen87** [comment]
If a load the `FBX` file with `FBXLoader` and set `alphaTest` to `0.5`, the result looks okay.

![image](https://user-images.githubusercontent.com/12612165/32702727-5ef556b8-c7eb-11e7-8987-af10baabf138.png)

Uploading the `FBX` file back to Sketchfab, i have the following result. It looks like that manually adjustments are also necessary when using Sketchfab.

![image](https://user-images.githubusercontent.com/12612165/32702783-128e8168-c7ec-11e7-8c90-0c6203729c41.png)

**Comment by Mugen87** [comment]
I guess we can close this issue.

**Comment by cnspaha** [comment]
> If a load the FBX file with FBXLoader and set alphaTest to 0.5, the result looks okay.

can you provide me with your example code?
Because in my case it looks quite different... got some nasty white silhuettes around the feathers but don't know why. 
I set the side to DoubleSide and the alphaTest to 0.5, don't do anything more with the material.
![image](https://user-images.githubusercontent.com/22448974/32712254-e6ef34e6-c843-11e7-96ad-ec132014d231.png)


> If you are setting alphaTest, and your textures are cut-outs (no semi-transparency), there is no need to set material.transparent = true. And therefore, you should see no "transparency artifacts".

Thanks :)

So the only option is to set alphaTest to 0.5 for every model and part I load? Because there is no possibility to check if I need to?

**Comment by donmccurdy** [comment]
> So the only option is to set alphaTest to 0.5 for every model and part I load? Because there is no possibility to check if I need to?

GLTFLoader could be altered to do this automatically, see above, assuming it shows the right result (currently it isn't for me). Not sure whether the FBX format provides clear indicators of when alphaTest should be changed or not though, to enable FBXLoader to do it automatically.

**Comment by cnspaha** [comment]
> GLTFLoader could be altered to do this automatically, see above, assuming it shows the right result (currently it isn't for me). Not sure whether the FBX format provides clear indicators of when alphaTest should be changed or not though, to enable FBXLoader to do it automatically.

haven't used the GLTFLoader yet.
Regarding the indicator for alpha in the FBX format I will do some researching, but don't know if it will provide good results :/ But when I do, I will post in this issue and let you know

**Comment by Mugen87** [comment]
@cnspaha I've just done this:

```javascript
loader.load( 'models/fbx/succubus.fbx', function( object ) {

	object.traverse( function( o ) {

		if ( o.isMesh === true ) {

			o.material.alphaTest = 0.5;
		
		}

	} );
           
	scene.add( object );

} );
```

**Comment by cnspaha** [comment]
@Mugen87 
I do the same as you. But just found the culprit... it is the "alpha" property on the WebGLRenderer.
If it is set to "true" the white silhuette appears...

**Comment by cnspaha** [comment]
close this, since it doesn't seem possible to check if there such parts contains alpha.

**Comment by donmccurdy** [comment]
I followed up about why the glTF version doesn't render correctly; there is an unexpected case in the format spec. Will post more updates here: https://github.com/KhronosGroup/glTF/issues/1158

**Comment by looeee** [comment]
> GLTFLoader could be altered to do this automatically, assuming it shows the right result (currently it isn't for me; see above). Not sure whether the FBX format provides clear indicators of when alphaTest should be changed or not though, to enable FBXLoader to do it automatically.

@donmccurdy how is this indicated in GLTF? I'll take a look and see if there is anything similar in FBX.

**Comment by donmccurdy** [comment]
@looeee glTF sets `alphaMode` as one of BLEND, MASK, or OPAQUE. Another property, `alphaCutoff`, corresponds to three.js's `alphaTest`. But (per KhronosGroup/glTF#1158) `alphaCutoff` is only used in MASK mode, not BLEND, and so the format technically does not allow why Sketchfab is trying to do here. That may be an oversight that needs to be corrected in a future glTF version...

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#alpha-coverage

**Comment by looeee** [comment]
There's an enum AlphaSource in FBX, unfortunately the [documentation](http://help.autodesk.com/view/FBX/2017/ENU/?guid=__cpp_ref_class_fbx_texture_html) is as usual pretty sparse (documentation as comments here):

```js
{ 
    eNone, // no alpha         
    eRGBIntensity,  //RGB Intensity (computed).
    eBlack // Alpha channel. Black is 100% transparency, white is opaque          
};
```

I wonder if `eBlack` could be used to indicate alpha test is needed?

**Comment by yazancash** [comment]
i have same problem.
in FBX file, textures are defined as below:
```
Texture: 123, "Texture::texmap123", "" {
	Type: "TextureVideoClip"
	Version: 202
	TextureName: "Texture::texmap123"
	Properties70:  {
		P: "UseMaterial", "bool", "", "",1
	}
	FileName: "123.png"
	ModelUVTranslation: 0,0
	ModelUVScaling: 1,1
	Texture_Alpha_Source: "RGBIntensity"
	Cropping: 0,0,0,0
}
```

i can see `Texture_Alpha_Source: "RGBIntensity"`
but model is appearing with no transparency. even when i set AlphaTest = 0.5

is there any solution for this?
