### ISSUE TITLE
JSONLoader doesn't load JSON files, making it impossible to use Morph Targets

### ISSUE THREAD

**Issue by lovemoebius** [mrdoob/three.js#12623]
I'm working with the webgl_morphtargets_human example to try and understand how to modify the morph targets of my model since I can't seem to find any information on how to do this outside of this one undocumented example.

I supposed this would be as simple as switching the model that is already being loaded with mine, however it doesn't seem to be that way.

If I switch the model that is being loaded in [UCS_config.json](https://github.com/mrdoob/three.js/examples/models/skinned/UCS_config.json) with mine and try to load it, the console gives me back the error 

"should be loaded with THREE.ObjectLoader instead."

Now this would be fine if it weren't for the fact that Objectloader, for some reason, makes it impossible to run [Line 47 of UCSCharacter.js](https://github.com/mrdoob/three.js/blob/dev/examples/js/UCSCharacter.js#L47), since, for some reason Objectloader doesn't load geometry but a mesh (from what I understand by googling the issue).

So, here my issues are two.

The first one is that the Blender Exporter doesn't seem to be exporting in the same format the JSON loader is trying to read. Here's [my test file](https://pastebin.com/dmCTZEzZ) compared to [the one being loaded by the example ](https://github.com/mrdoob/three.js/blob/dev/examples/models/skinned/UCS/umich_ucs.js). 
Even a quick glance at the two makes it clear that they're not even close to similar.

The second issues is that morph targets seem to be inaccessible from a file loaded with ObjectLoader. However this might just be my fault as I can't seem to find any information on how this can be done.

Are there any temporary fixes for any of these?

**Comment by donmccurdy** [comment]
> Now this would be fine if it weren't for the fact that Objectloader, for some reason, makes it impossible to run Line 47 of UCSCharacter.js, since, for some reason Objectloader doesn't load geometry but a mesh (from what I understand by googling the issue).

There is a short example (not including morph targets) in the [ObjectLoader docs](https://threejs.org/docs/#api/loaders/ObjectLoader). The important thing is that the result is an Object3D or subclass. Adjusting the code from UCSLoader, you might do something like this:

```js
var loader = new THREE.ObjectLoader();
loader.load( config.baseUrl + config.character, function( object ) {
  var geometry;
  object.traverse((node) => {
    if (node.isMesh) geometry = node.geometry;
  });
  // ...
});
```

However, I don't see morph targets in that test file... Can you post the `.blend` file, in case there is a bug in the exporter?

**Comment by lovemoebius** [comment]
I don't have the .blend file anymore unfortunately, long story, but I thought I'd figure out if I could get the Morph Targets to work before actually starting to work on the morph targets themselves which would take me a long time. And of course my current json is way too big to be pasted anywhere.

I made this cube to test from now on since it's probably going to be quicker either way https://pastebin.com/Rnh88B2n. 
Here's a link to the blend https://a.pomf.cat/swoqik.blend

I tried out that code you posted. My current Objectloader code looks like this 

`var loader = new THREE.ObjectLoader();
		loader.load( config.baseUrl + config.character, function( object ) {
		  var geometry;
		  object.traverse((node) => {
			if (node.isMesh) geometry = node.geometry;
		  });

			geometry.computeBoundingBox();
			geometry.computeVertexNormals();

			mesh = new THREE.SkinnedMesh( geometry, [] );
			mesh.name = config.character;
			scope.root.add( mesh );

			var bb = geometry.boundingBox;
			scope.root.scale.set( config.s, config.s, config.s );
			scope.root.position.set( config.x, config.y - bb.min.y * config.s, config.z );

			mesh.castShadow = true;
			mesh.receiveShadow = true;

			scope.mixer.clipAction( geometry.animations[0], mesh ).play();

			scope.setSkin( 0 );

			scope.checkLoadComplete();
			
		});`

While it doesn't give me the same errors as before, it seems to have problems with 

`scope.mixer.clipAction( geometry.animations[0], mesh ).play();`

As it gives me the error 
`UCSCharacter.js:61 Uncaught TypeError: Cannot read property '0' of undefined
    at UCSCharacter.js:61
    at ObjectLoader.parse (three.js:34476)
    at Object.onLoad (three.js:34435)
    at XMLHttpRequest.<anonymous> (three.js:30483)`

If commented out the page seems to load fine, however the cube isn't displayed in any case.

(apologies for the broken code tag, can't seem to get it working)

**Comment by donmccurdy** [comment]
This example code you're working from assumes you have a model that uses both morph targets AND skinning, which is greatly overcomplicating this. 🙃

Here is a much simpler example, I would work from that: 

https://morph-test-wnvgoknsdu.now.sh/

The important parts are: 

```js
var loader = new THREE.ObjectLoader();
loader.load( 'test.json', function ( object ) {

  object.traverse((node) => {
    if (node.isMesh) mesh = node;
  });

  mesh.material.morphTargets = true;

  scene.add( mesh );

});
```

```js
function render() {

  if ( mesh ) {
    mesh.rotation.y += 0.01;
    mesh.morphTargetInfluences[0] = (mesh.morphTargetInfluences[0] + 0.01) % 1;
  }

  renderer.render( scene, camera );

}
```

**Comment by lovemoebius** [comment]
That was incredibly helpful and works perfectly, didn't think it would be that simple.

However after doing some more testing with more complex models I think I might've actually found a bug. From my tests it looks like if a JSON model has more than one material, no changes will be applied to the morph targets.

Live test (same code as before): http://creativiii.com/threejs/examples/webgl_morphtargets_human2.html

Blend file: https://a.pomf.cat/oyfcdc.blend

**Comment by donmccurdy** [comment]
In that case the line `mesh.material.morphTargets = true` needs to be changed:

```js
mesh.traverse((node) => {

  if (!node.isMesh) return;

  var materials = Array.isArray(node.material) ? node.material : [node.material];

  for (var i = 0; i < materials.length; i ++) {
    materials[i].morphTargets = true;
  }

});
```

**Comment by lovemoebius** [comment]
That fixed it.

Just to ask, how do you know this stuff? It's not on the Docs. Did you just learn it from the base Three.js code?

**Comment by donmccurdy** [comment]
Yeah, I'm actually not sure where/if multiple material stuff is documented... 😕 I've just run into it before. The part about enabling morph targets is in docs for material subclasses (e.g. [MeshStandardMaterial](https://threejs.org/docs/#api/materials/MeshStandardMaterial)). Perhaps it should also be on the base [Material class](https://threejs.org/docs/#api/materials/Material) docs.

**Comment by lovemoebius** [comment]
Last question before I completely give up on this, is there a reason why every single morph target I try only works correctly at values 0 and 1?

I tried this with a bunch of different meshes, compex and simple, and it looks like every single mesh becomes very deformed with any value that aren't 0 or 1. The deformation seems to usually be scaling related in one of the three axes.

http://creativiii.com/threejs/examples/webgl_morphtargets_human3.html

This can be checked at this live link and then inputting in the console the values to change like:
`mesh.morphTargetInfluences[0] = -.5`

I have no clue why this is happening. I've also experienced random rotations with more complex meshes.

**Comment by donmccurdy** [comment]
If you're setting the influences to negative values, then they're probably going the opposite way you intend, yes. Normal values would be floats [0...1], although there are certainly cases to go below 0 or above 1.

It's also possible the morph targets are configured wrong in your model... if it's glTF you can debug it [here](https://gltf-viewer.donmccurdy.com/) but otherwise that requires some setup.

Here is a simpler example:

https://cdn.rawgit.com/donmccurdy/three.js/7aa389883e26af8558ede56eed3551156d869d2e/examples/webgl_morphtargets_sphere.html

**Comment by lovemoebius** [comment]
I'm not setting the values to negative numbers. With only positive numbers, while setting a morphtarget to 0.5 for example, the mesh will just entirely flatten itself. If I set the morph target to 1, the mesh will reach the shape that I gave it in blender, however that shape will be mirrored to the opposite side it started as.

http://creativiii.com/threejs/examples/webgl_morphtargets_human3.html

This is using your code, as you can see it just it just refuses to work right.

I'm fairly sure my morph targets are set up right. I'm following what this tutorial does up until part 14, after which I export using the settings found [here](https://github.com/mrdoob/three.js/issues/8710#issuecomment-288163037)

Maybe it's a blender problem? Are you using blender for your models? This happened to me even while using models that I didn't make myself and I downloaded from the internet so it's even more confusing.

I also tried to convert my model to gltf, however nothing seems to load even while using the exact code you posted.

http://creativiii.com/threejs/examples/webgl_morphtargets_human4.html

**Comment by donmccurdy** [comment]
Ok, yeah the effect of the influence value is just to interpolate between two shapes, so it entirely depends on what you're exporting from Blender... if `-0.5` works for you that's fine, too.

> I also tried to convert my model to gltf, however nothing seems to load even while using the exact code you posted.

That's a glTF 1.0 model, which would require LegacyGLTFLoader and doesn't support morph targets anyway:

![screen shot 2017-11-17 at 11 29 16 am](https://user-images.githubusercontent.com/1848368/32965185-aaad5c48-cb8a-11e7-8c2e-b626736ce08d.png)

OBJ doesn't support morph targets also, so even a new version of OBJ2GLTF would not work. My model was created with https://github.com/KhronosGroup/glTF-Blender-Exporter/.

**Comment by donmccurdy** [comment]
^I saw that error by setting a breakpoint, otherwise you'd need to set pass `onError` handler when calling `loader.load(onSuccess, undefined, onError)`

**Comment by lovemoebius** [comment]
> Ok, yeah the effect of the influence value is just to interpolate between two shapes, so it entirely depends on what you're exporting from Blender... if -0.5 works for you that's fine, too.

-0.5 doesn't work, that's the problem. I can't have intermediate shapes at all.

However it seems like glTF does work as intended, however I am having some trouble exporting big meshes with blender, the program doesn't crash but it's either taking a very long time or not working at all.
I'll keep waiting and see what happens.

Are there any specific settings I should use or do are the default ones okay?

Thank you for all the help so far by the way, you're a saint.

**Comment by donmccurdy** [comment]
> Are there any specific settings I should use or do are the default ones okay?

I assume normal use of Blender shape keys should work with glTF morph targets, but i'm not too familiar with Blender honestly.

**Comment by donmccurdy** [comment]
I think any remaining issues are not related to JSONLoader, so will close this in favor of #12595 if that's ok.
