### ISSUE TITLE
Cannot use THREE.WebGLUtils from Typescript

### ISSUE THREAD

**Issue by DomDumont** [mrdoob/three.js#12622]
##### Description of the problem 

Hi all, it seems THREE.WebGLUTils is not exposed through @types.
I'm trying to use this code ( https://github.com/spite/THREE.UpdatableTexture ) in typescript.

By the way, if someone has a better option to load small texture blocks into a bigger one, i'm interested ;-)

##### Three.js version

the one from npm install ("three": "^0.87.1")

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/10681#issuecomment-287921860
