### ISSUE TITLE
(lack of) Documentation regarding triangulation?

### ISSUE THREAD

**Issue by loldrup** [mrdoob/three.js#12626]
What's the one-stop-shop for documentation on performing triangulation with three.js?
Searching for 'triangulation' on the three.js documentation site gives no hits.

Is [this project](https://github.com/Wilt/three.js_triangulation) officially sanctioned as The Right Way to approach triangulation with three.js?

Is there a way to get three.js sanctioned triangulation code purely through NPM? Searching for 'three triangulation' on npmjs.com gives no hits, and the above mentioned project only talks about installation via bower.json. Yuck!

**Comment by donmccurdy** [comment]
For docs on three.js's triangulation see [THREE.ShapeUtils](https://threejs.org/docs/#api/extras/ShapeUtils).

But, I would suggest just using [earcut](https://github.com/mapbox/earcut). We may go that direction in the future: https://github.com/mrdoob/three.js/pull/12286. Example usage of earcut with three.js: https://github.com/mrdoob/three.js/issues/5959#issuecomment-148339422

**Comment by Mugen87** [comment]
I use this as an opportunity to vote for an application of `earcut` again 😊 . The current implementation of `ShapeUtils` (a port from [here](http://www.flipcode.com/archives/Efficient_Polygon_Triangulation.shtml)) was repeatedly insufficient if users required a robust triangulation process. Instead, users switched to external libs (in most cases `earcut`). IMO, this is a clear signal to improve the built-in solution.

Besides, an improved triangulation algorithm would be a nice feature for `R89`:blush:

**Comment by loldrup** [comment]
Luckily I only need to triangulate simple polygons, so I'll stick with ShapeUtils.
Thank you McCurdy!


Den 10. nov. 2017, fra 18.58, Michael Herzog <notifications@github.com> skrev:

I use this as an opportunity to vote for an application of earcut again 😊 . The current implementation of ShapeUtils (a port from here) was repeatedly insufficient if users required a robust triangulation process. Instead, users switched to external libs (in most cases earcut). IMO, this is a clear signal to improve the built-in solution.

Besides, an improved triangulation algorithm would be a nice feature for R89😊

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

Den 10. nov. 2017 18.58, fra 18.58, Michael Herzog <notifications@github.com> skrev:

**Comment by Mugen87** [comment]
This should be solved with #12661 and #12725. `three.js` uses now a port of an earcut implementation, see https://github.com/mapbox/earcut

**Comment by Wilt** [comment]
> "the above mentioned project only talks about installation via bower.json. Yuck!"

@loldrup You can easily install a git repository using npm, that is no rocket science:

    "three.js_triangulation": "git+https://github.com/Wilt/three.js_triangulation.git",

I will add this to the readme when I find some free time.
