### ISSUE TITLE
Feature request in ThreeJSExporter

### ISSUE THREAD

**Issue by Sachin1706** [mrdoob/three.js#12639]
##### Description of the problem 

In three.js/utils/exporters/max/ThreeJSExporter.ms, there is only one function that export selected objects into one .js file. It could have more function like export each object in selection into .js( separate file) and also each layer in file (containing mesh objects) export into .js ( separate file).

##### Three.js version

- [x] Dev
- [ ] r87
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Sachin1706** [comment]
In three.js/utils/exporters/max/ThreeJSExporter.ms, there is only one function that export selected objects into one .js file. It could have more function like export each object in selection into .js( separate file) and also each layer in file (containing mesh objects) export into .js ( separate file).

**Comment by Sachin1706** [comment]
In three.js/utils/exporters/max/ThreeJSExporter.ms, there is only one function that export selected objects into one .js file. It could have more function like export each object in selection into .js( separate file) and also each layer in file (containing mesh objects) export into .js ( separate file).

**Comment by Mugen87** [comment]
The exporter has been removed, see #12930
