### ISSUE TITLE
Feature Request Bulk export .js to .obj

### ISSUE THREAD

**Issue by sora1984** [mrdoob/three.js#12633]
Would be nice to be able to bulk export .js files to .obj files

**Comment by Mugen87** [comment]
Do you mean something like this?

https://github.com/mrdoob/three.js/blob/dev/examples/js/exporters/OBJExporter.js

**Comment by sora1984** [comment]
cheers for that. how would one go about using that file to export multiple .js files to .obj ? 
regards

**Comment by donmccurdy** [comment]
The gist would be:

```js
const THREE = require('three');
const OBJExporter = require('three/examples/js/exporters/OBJExporter');
const fs = require('fs');

const files = [ 'file1.js', 'file2.json' ];

const loader = new THREE.ObjectLoader(); // or JSONLoader, depending on the format.
const exporter = new THREE.OBJExporter();

files.forEach( ( file ) => {

  loader.load( file, ( result ) => {

    var objContent = exporter.parse( result );
    fs.writeFile( file.replace(/\.js(on)?/, '.obj'), objContent );

  } );

});
```

^whether it's really quite that easy to use three.js in node.js, i'm not sure... might need to hotpatch `global.XMLHttpRequest` or something.
