### ISSUE TITLE
Three audio breaking up Mac Chrome

### ISSUE THREAD

**Issue by lagauche** [mrdoob/three.js#12632]
##### Description of the problem 

I'm playing an mp3 44.1khz sample rate with PositionalAudio and using an Orbit camera to listen. On Chrome, on a Mac, it's clicking and breaking up for a split second once and a while. This didn't seem to be the case on Windows/Chrome, but I haven't had a chance to test.

Not sure if this is a Three.js bug, a Web Audio API bug or a Chrome/Mac bug : /

Update edit:
This might have to do with the 320kbps VBR format I used. I would delete this issue if I knew how, though if it is really an issue it would be good to know : )

##### Three.js version

r88

##### Browser

- [x] Chrome

##### OS

- [x] macOS

**Comment by Mugen87** [comment]
If you can apply a live demo, i can test it on my iMac with Chrome. Although i don't think this is a `three.js`  issue.

**Comment by lagauche** [comment]
Hey @Mugen87 thanks thanks! the website is www.xlagauchex.com
I removed the LoadManager settings since that's when the issue was the worst. Click the shirt button to start the music.

Small warning: it's not NSFW, but there is a texture of internal flesh - probably a throat that might be a bit weird to some.

**Comment by Mugen87** [comment]
I was not able to hear any form of glitch on my iMac and i don't think this issue section is the right place for your problem.

Try to isolate the glitch with a small test case (maybe just an empty page with a single `audio`  element) and request for help at stackoverflow. Also consider to test with different audio [formats](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats).
