### ISSUE TITLE
Rapid change in perspective when using OrbitControls and TransformControls together

### ISSUE THREAD

**Issue by brmscheiner** [mrdoob/three.js#12630]
You can reproduce this bug easily in the [WebGL Geometry Spline Editor example](https://threejs.org/examples/#webgl_geometry_spline_editor). Select one of the objects and move it toward the top of the scene. When the cursor gets to the top edge of the screen the perspective instantaneously shifts (by 90 degrees I think).

I am on OSX 10.12.6 and Chrome 62 but I have reproduced the same bug on Windows and in an Electron app as well.

**Comment by FishOrBear** [comment]
Because the sample did not add the <Pointer Lock API> feature.
Lost mouse over capture when mouse hovers over canvas.
When you go back to the canvas, the canvas thinks you are rotating the view.

look this 
https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API

and this
https://threejs.org/examples/?q=point#misc_controls_pointerlock

**Comment by brmscheiner** [comment]
@FishOrBear very cool, I was not aware of the Pointer Lock API. This certainly provides a way of getting around the issue, but for many use cases it may be appropriate to keep the cursor and allow the mouse to easily enter/leave the scene.

**Comment by brmscheiner** [comment]
If anyone comes across this thread in need of a hacky fix, I was able to stop this behavior by modifying the handleMouseMoveRotate function in OrbitControls.js:

`function handleMouseMoveRotate( event ) {

      var currentTime = new Date().getTime();

      var timeSinceLastRotation = currentTime - this.lastRotationTime;
      var largeRotation =
        Math.abs(event.clientX - rotateStart.x) > 30 || Math.abs(event.clientY - rotateStart.y) > 30;

      if (largeRotation && timeSinceLastRotation > 750) return;

			rotateEnd.set( event.clientX, event.clientY );
			rotateDelta.subVectors( rotateEnd, rotateStart );

			var element = scope.domElement === document ? scope.domElement.body : scope.domElement;

			// rotating across whole screen goes 360 degrees around
			rotateLeft( 2 * Math.PI * rotateDelta.x / element.clientWidth * scope.rotateSpeed );

			// rotating up and down along whole screen attempts to go 360, but limited to 180
			rotateUp( 2 * Math.PI * rotateDelta.y / element.clientHeight * scope.rotateSpeed );

			rotateStart.copy( rotateEnd );

			scope.update();

      this.lastRotationTime = currentTime;
		}`

**Comment by FishOrBear** [comment]
`Pointer Lock API` This api has a headache, when I` exitPointerLock`, the mouse is still in its original position.

I do not know what's the solution to this problem.

**Comment by makc** [comment]
looks to me as if transform controls blocks mouse move but not mouse down, so orbit controls receives mouse down, then nothing, and then near the top of the screen transform controls lose... control... and orbit controls now receive huge leap with mouse move event. something like that

**Comment by makc** [comment]
> Seems like there is a moment where the transform controls stop handling the onMouseMove event and then the orbit controls start handling it and do the huge rotation.

ah right, that's what you said

**Comment by arodic** [comment]
This should be fixed in #14619

**Comment by arodic** [comment]
The fix has been merged.
