### ISSUE TITLE
FBXLoader makehuman fbx deformations

### ISSUE THREAD

**Issue by jabojabo** [mrdoob/three.js#12652]
[character.zip](https://github.com/mrdoob/three.js/files/1473017/character.zip)
Hello,
I have a fbx character designed and exported to FBX with makehuman 1.1.1.
When the character hasn't got a skeleton integrated the character is perfectly rendered. But when a skeleton is added the character is rendered deformed. It's loaded with FBXLoader and the example provided in the three.js distribution.

I don't think the problem is with makehuman or the export. Blender renders it perfectly.

I attach a couple of pics. Also the fbx files (EDIT: textures are at the end of this message). Just in case they are useful.

##### Three.js version
- [X] r88

##### Browser
-  Chrome
- Opera
##### OS
- [X ] Linux: Ubuntu 16.04
![without_skeleton](https://user-images.githubusercontent.com/33674526/32812519-c0d80112-c9a5-11e7-89fd-c607b038cc2a.png)
![with_skeleton](https://user-images.githubusercontent.com/33674526/32812520-c10914c8-c9a5-11e7-83a9-9e4bd002120b.png)

[textures.zip](https://github.com/mrdoob/three.js/files/1473432/textures.zip)

**Comment by looeee** [comment]
Possibly related #11553

**Comment by jabojabo** [comment]
I'll take a look. Thank you.

**Comment by looeee** [comment]
Fixed in #13045
