### ISSUE TITLE
Can't exporter json 

### ISSUE THREAD

**Issue by Lololu1988** [mrdoob/three.js#12659]
// Error: line 0: RuntimeError: file S:\Maya_2016_DI\build\Release\runTime\Python\Lib\site-packages\maya\OpenMayaAnim.py line 1415: (kInvalidParameter): Object is incompatible with this method // 

##### Three.js version

- [ ] Dev
- [ ] r88
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by mrdoob** [comment]
How about expiring to FBX instead?

**Comment by Lololu1988** [comment]
Thx for your reply.@mrdoob
but I need json.So I want to konw why.
Now I export FBX and use Blender to export json.
