### ISSUE TITLE
CubeTextureLoader exchanges +X and -X textures in Scene.background

### ISSUE THREAD

**Issue by MagnuzBinder** [mrdoob/three.js#12657]
##### Description of the problem 

When loading textures for a Scene.background CubeTexture using
`Scene.background = new THREE.CubeTextureLoader().load( pX, nX, pY, nY, pZ, nZ );`
with p = positive (+) and n = negative (-), pX is displayed towards the negative X direction ("left") and nX towards the positive X direction ("right"), while as expected, pY is displayed towards the positive Y direction ("up"), nY towards the negative Y direction ("down"), pZ towards the positive Z direction ("rear") and nZ towards the negative Z direction ("front").

At present, the workaround is flipping the order of the X textures in the call. If this is intended behavior, the documentation needs to be updated to reflect this:
`Scene.background = new THREE.CubeTextureLoader().load( nX, pX, pY, nY, pZ, nZ );`

##### Three.js version

- [ ] Dev
- [x] r88
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
See [this SO answer](https://stackoverflow.com/a/45999554/1461008).

**Comment by MagnuzBinder** [comment]
Thank you, that explains it. I submitted a patch to add the explanation of projection order to the documentation, since more than me have and probably will wonder about it.
