### ISSUE TITLE
NPM 'three' package has invalid characters.

### ISSUE THREAD

**Issue by d3x0r** [mrdoob/three.js#12650]
npm install three

"three": "^0.88.0",

in node_modules/three/build/three.js 

three.js:35947 Uncaught SyntaxError: Unexpected number

		this.aStartAngle = aStartAngle ||Â 0;

**Comment by Mugen87** [comment]
There is already a PR for this problem. #12634

**Comment by d3x0r** [comment]
closing, because duplicate... so it is an error that originates from the sources.....
