### ISSUE TITLE
GLTFLoader r88: camera's are loaded as Object3D instead of OrthographicCamera / PerspectiveCamera

### ISSUE THREAD

**Issue by Friksel** [mrdoob/three.js#12656]
While loading a scene with GLTFLoader (in r88) cameras (from the 'cameras' section inside the gltf) are loaded as Object3D, instead of OrthographicCamera or PerspectiveCamera. And thus important methods like updateProjectionMatrix() are missing in the resulting objects. (ObjectLoader does return camera-objects as OrthographicCamera / PerspectiveCamera while loading a scene from json).

**Comment by Friksel** [comment]
I just found out what the problem is: GLTFLoader doesn't return camera-objects directly, but within a 'wrapper' Object3D as a child. The camera itself is the first item in its children array. That's unexpected and unwanted. It's different then ObjectLoader behaviour and the gltf file doesn't have and cannot have multiple camera's inside a single camera object (see the cameras section below). 

**Loading a scene with Objectloader (works as expected):**
`this.data.mainCam = this.data.scene.getObjectByName('mainCam'); // returns OrthographicCam object`

**Loading a scene with GLTFLoader (strange behaviour):**
`this.data.mainCam = this.data.scene.getObjectByName('mainCam'); // returns Object3D object`
`this.data.mainCam = this.data.scene.getObjectByName('mainCam').children[0]; // returns OrthographicCam object`

**cameras-object inside the gltf(2) file:**
```
"cameras" : [
        {
            "name" : "mainCam", 
            "orthographic" : {
                "xmag" : 46.0, 
                "ymag" : 46.0, 
                "zfar" : 200.0, 
                "znear" : 9.999999747378752e-05
            }, 
            "type" : "orthographic"
        }
    ], 
```

**Comment by donmccurdy** [comment]
Could you share an example file (`.gltf`, `.blend`, or both)? You can drag-and-drop .zip files into GitHub comments. The "Duck" example [here](https://threejs.org/examples/?q=gltf#webgl_loader_gltf) uses a camera that parses correctly, without a wrapping Object3D, so I'm not sure what's happening here.

**Comment by Friksel** [comment]
Thanks for your reply @donmccurdy . Strange. On first sight the duck.gltf looks the same.

I just did a test with a very simplified gltf with the same result as described above. Here's the gltf together with its .blend. For this I just used the default startup scene in blender and only changed the objectnames and the color of the cube. 
[gltftest.zip](https://github.com/mrdoob/three.js/files/1475327/gltftest.zip)

**Comment by donmccurdy** [comment]
Hm that extra Object3D is baked into the model. Looks like the Blender exporter is doing this.

Viewing the console on https://gltf-viewer.donmccurdy.com/ you see:

<img width="329" alt="screen shot 2017-11-15 at 7 54 43 am" src="https://user-images.githubusercontent.com/1848368/32845745-606d1a44-c9da-11e7-9c99-272f592e69b6.png">

There are two nodes, `mainCam` and `Correction_mainCam`, in the source glTF.

The quickest workaround, rather than relying on the node name, would be:

```js
var camera;
model.traverse((node) => {
  if ( node.isCamera ) camera = node;
});
console.log(camera);
```

but i would also suggest filing a bug on the exporter about this.

**Comment by Friksel** [comment]
Thanks for your quick help. On my side I just found out the Duck.gltf is working with my code, so that's useful info too. Strange this bug is in the exporter. I'm using the latest version of the gltf2 exporter for blender created by the KhronousGroup itself. Don't understand the 'Correction'-part in the camename either, 'cause this is the most simple scene possible in blender. I'll file a bug on the exporter then.

Wich exporter are you using / was used to create the Duck gltf example?

Nice viewer btw!

**Comment by donmccurdy** [comment]
The Duck example was made with [COLLADA2GLTF](https://github.com/KhronosGroup/COLLADA2GLTF) (there is a branch in progress that supports glTF 2.0). I suspect the blender exporter is creating that extra "Correction_" part to work around some issue or other, but the authors will know. Same thing happens with lights, I believe. Seems like it should be possible to flatten during export automatically.

**Comment by Friksel** [comment]
@donmccurdy I think it's better to continue the talk here instead of on the exporter side for now:

`Good points. @Friksel I think the summary here is that Blender's default camera orientation is somewhat different than glTF's, and correcting that requires this extra node. It will be necessary to check node.isCamera in three.js as described in the other thread, or make manual changes to the model.`

I don't think this is be the way to go. In my opinion loading a scene by json with the Objectloader should have the exact same scene as loading it through gltf with the gltfLoader. On the other side Objectloader and blender to threejs exporter have problems transforming axis from Blender to threejs too. So if that is solved using the gltfexporter that would be a great improvement.

I'll have to take a closer look on how to work with this. For now it seems like getting the first child of the camera works, but at the moment I don't have the time to test if that's also working on transformations and rotations. I'll take a closer look if I find some time.

**Comment by donmccurdy** [comment]
> I don't think this is be the way to go. In my opinion loading a scene by json with the Objectloader should have the exact same scene as loading it through gltf with the gltfLoader.

That would be great, it's just hard. The Blender three.js exporter and the Blender glTF exporter are maintained by different people, and different formats have requirements that things work a certain way, so it's hard to guarantee it will be exactly the same result.

I think you can always be sure that first child of the camera will have the same rotation (it's just rotating the camera to face `-Z` relative to the parent, which is the defined default direction of glTF. Changing glTF-Blender-Exporter to not have two nodes would be a lot of work.

Getting the first child of the camera is fine, or you could do this if you want to be very sure it will also work for glTF models not exported from Blender:

```js
var cameraWrap = model.getObjectByName('mainCam');
var camera;
cameraWrap.traverse((node) => { if ( node.isCamera ) camera = node; });
console.log(camera);
```

**Comment by Friksel** [comment]
Yes, seems like loading cameras this way is working fine in the project I'm working on. Not sure about rotations, but that's for later. With the nice trick you gave it's easier to convert my project from Objectloader to gltfLoader. I put it in a function:

```
getCameraByName(scene, name) {
        const cameraWrap = scene.getObjectByName(name);
        let camera = null;
        if (cameraWrap) {
            if (cameraWrap.isCamera) {
                camera = cameraWrap;
            } else {
                cameraWrap.traverse((node) => {
                    if (node.isCamera) {
                        camera = node;
                    }
                });
            }
        }
        return camera;
    }
```

Now I'm moving on to the next step: making the lights and materials work / solving shader problems. And wrong axis problems. But if these are done it's a big step forward looking at the great improvement in filesize of gltf!
