### ISSUE TITLE
A few documentation flaws

### ISSUE THREAD

**Issue by MagnuzBinder** [mrdoob/three.js#12658]
##### Description of the problem 

Since I'm new to three.js, I browsed through the documentation on the website and found a few flaws in it. Since it seems to be at least partly generated from the code, I wasn't sure where to report it, so if there is a better place and way than this, please let me know. Corrections are suggested using => . Here goes:

https://threejs.org/docs/index.html#api/core/DirectGeometry
Double instance of .verticesNeedUpdate

https://threejs.org/docs/index.html#api/core/EventDispatcher
Mixin => Mixing

https://threejs.org/docs/index.html#api/core/Geometry
skeleton.bones[10] => skeleton.bones[0]

https://threejs.org/docs/index.html#api/deprecated/DeprecatedList
ParticleSystem has been renamed to Sprite. => Particle has been renamed to Sprite.

https://threejs.org/docs/index.html#api/extras/core/Path
Adds to the from the points. ???

https://threejs.org/docs/index.html#api/lights/DirectionalLight
hex => color

https://threejs.org/docs/index.html#api/loaders/ImageLoader
many models => many images

https://threejs.org/docs/index.html#api/loaders/JSONLoader
texturePath => ?path

https://threejs.org/docs/index.html#api/math/Box3
in 2D space => in 3D space

https://threejs.org/docs/index.html#api/math/Sphere
Vector3, otherwise a new Box3 => Box3, otherwise a new Box3

https://threejs.org/docs/index.html#api/math/Vector4
index - 0, 1 or 2. => index - 0, 1, 2 or 3.

https://threejs.org/docs/index.html#api/renderers/WebGLRenderer
domElementdomElement => domElement

https://threejs.org/docs/index.html#api/renderers/WebGLRenderTarget
.LinearFilter => LinearFilter

https://threejs.org/docs/index.html#api/scenes/Fog
hex => color

https://threejs.org/docs/index.html#api/scenes/FogExp2
hex => color

##### Three.js version

- [x] Dev
- [ ] r88
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Thanks for reporting 👍 . So....would you also like to do a PR with your suggestions? 😊

**Comment by mrdoob** [comment]
There is a `EDIT` button on the top-right of each page. If you click on it you should be able to do the fix and save it/submit PR.

**Comment by MagnuzBinder** [comment]
Thank you for the hint. It didn't work before, because I wasn't logged in. Sorry about that, but now it's submitted. I left out the texturePath in JSONLoader, because according to code it's correct, although slightly confusing (at least to me who are noob to this).

**Comment by mrdoob** [comment]
#12660 #12662 #12663 #12664 #12665 #12666 #12667 #12668 #12669 #12670 #12671 #12672 #12673 #12674
