### ISSUE TITLE
i replace the fbx in examples\models\fbx and rename it in file webgl_loader_fbx.html but this does not render the file.

### ISSUE THREAD

**Issue by Pratap-Bhuvnesh** [mrdoob/three.js#12676]
##### Description of the problem 

I replace the fbx in examples\models\fbx and rename it in file webgl_loader_fbx.html but this does not render the file.
##### Three.js version

- [ ] Dev
- [ ] r88
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
Can you share the model? I'll take a look. You can add zip files here.

**Comment by Pratap-Bhuvnesh** [comment]
Hi Blue, i did'nt change anything exclude replacing fbx file and mention it into webgl_loader_fbx.html
[test.zip](https://github.com/mrdoob/three.js/files/1477752/test.zip)

**Comment by looeee** [comment]
I've tested the FBX-DEMO.FBX (table) model contained in your zip file - it's loading fine, it's just very large in scale and positioned quite far back and to the right behind the camera. If you zoom out enough or scale the model down you will see it. Adding this line: 

```js
object.scale.multiplyScalar(0.01);
```

just before `scene.add(object);` will help.

**Comment by Pratap-Bhuvnesh** [comment]
Hi Blue, Thanks for the help. But still this is not working.
Please let me know ,more methods like above to change.
object.scale.multiplyScalar(0.01);   this does not affect.

**Comment by mrdoob** [comment]
@Pratap-Bhuvnesh Does the model load in https://threejs.org/editor/?

**Comment by Pratap-Bhuvnesh** [comment]
@medoob Thanks for the reply. I am not sure.... How may i come to know that?
