### ISSUE TITLE
Possible memory leak when using WebGLRenderer with React

### ISSUE THREAD

**Issue by lysigk** [mrdoob/three.js#12684]
##### Description of the problem 

I'm working on a Three.js application using React and Redux. So far I have created [this test application](https://github.com/lysigk/react-redux-three) to figure out how to implement rendering, state manangement, input handling etc.

Things are running fine and smoothly as long as no events are triggered. However, for some reason, as soon as events like `mousemove` are fired, memory usage constantly goes up and performance decreases.

The yellow line in the performance profile shows this constant piling up of events:

![memory_leak](https://user-images.githubusercontent.com/13220138/32961359-86da662e-cbc8-11e7-8ee3-dd2e8698b93a.png)

Unfortunately, at this point my application is a bit too complex for a JSFiddle or something like that. If it would be helpful, I could upload the application on Firebase or try to isolate the problem.

I'm not sure if this is a Three.js related issue. But when I remove the WebGLRenderer and only do the input handling and scene updating part, everything works fine. Also, the problem ocurrs as soon as the WebGLRenderer is created, so the WebGLRenderer.render() call or the animation loop doesn't seem to be the cause for the problem.

##### Three.js version

- [X ] r88

##### Browser

- [] All of them
- [X ] Chrome
- [ X] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [X ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
GeForce GT 720M

**Comment by mrdoob** [comment]
> I'm not sure if this is a Three.js related issue.

Please, report when you're sure...
