### ISSUE TITLE
GLTFLoader - Internet Explorer Error

### ISSUE THREAD

**Issue by rck1** [mrdoob/three.js#12683]
##### Description of the problem 

GLTFLoader does not work in Internet Explorer 11.  Even when gltf only uses standard diffuse texture (.jpg) and no depth texture.  The model does not load.  You can try the link from three.js examples: 
https://threejs.org/examples/webgl_loader_gltf.html.

Internet Explorer spits out the following warnings.

> THREE.WebGLRenderer 88
> THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.
> THREE.WebGLRenderer: OES_texture_half_float extension not supported.
> THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.
> Timer "GLTFLoader" already exists.
> Error: THREE.GLTFLoader: Unable to parse model.
```
   {
      [functions]: ,
      __proto__: { },
      description: "THREE.GLTFLoader: Unable to parse model.",
      message: "THREE.GLTFLoader: Unable to parse model.",
      name: "Error"
   }
```

##### Three.js version

- [ ] Dev
- [x] r88
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
Perhaps we should surface the full error rather than "unable to parse model", but i'm guessing you will need a [Promise](https://caniuse.com/#search=Promise) [polyfill](https://www.npmjs.com/package/promise-polyfill) for IE11.

**Comment by rck1** [comment]
Thank you @donmccurdy.  Sorry, I don't quite grasp what you are saying.  I'm not strong with JavaScript.

I wish we could live in a world without IE11 but the vast majority of my clients are stuck on IE11.  And it looks like it'll be that way for quite some time.  Is this something you can resolve in GLTFLoader?  What can I do in the meantime to get this working in IE11?

**Comment by donmccurdy** [comment]
IE11 is missing a feature, called Promises, that GLTFLoader needs. You can try "patching" IE11 with a fake implementation by adding this script before any of your other scripts:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/native-promise-only/0.8.1/npo.js"></script>
```

If that doesn't work, I think I will need you to share a demo showing how your scene is set up.

**Comment by takahirox** [comment]
> IE11 is missing a feature, called Promises, that GLTFLoader needs. You can try "patching" IE11 with a fake implementation by adding this script before any of your other scripts:
>
>    <script src="https://cdnjs.cloudflare.com/ajax/libs/native-promise-only/0.8.1/npo.js"></script>

Maybe it'd be worth to add this note to `GLTFLoader` document or somewhere?

**Comment by rck1** [comment]
@donmccurdy Adding _npo.js_ worked!  This made my day!  Thank you.

Out of curiosity, was _GLTFLoader.js_ written in ES6 and compiled to ES5?  Is that why Promise is used?  For future versions, is there a good workaround to using Promise to avoid incompatibility with IE11?

@takahirox I agree, this should be documented.

**Comment by donmccurdy** [comment]
The core three.js library is written in ES6 and compiled back to ES5. But, things in `examples/js/*` are not compiled at all, and so they're mostly written in ES5. Using Promises here was an exception, because I think the loader would become very messy without them.

We can't include the Promise patch directly in GLTFLoader, so unless #9562 resolves or GLTFLoader someday becomes part of the core library, it will be necessary to include that Promise script for IE11 support.

A note in the docs or at the top of the file would be fine I think.

**Comment by rck1** [comment]
Thank you @donmccurdy.  This is a fascinating discussion and I'm learning a lot.   I think it makes a lot of sense to make GLTFLoader part of the core three.js library.  I hope we can see that within the next few releases.  In the meantime, the Promise [polyfill](https://github.com/stefanpenner/es6-promise) solution works great.
