### ISSUE TITLE
MorphTargets incorrectly affect other objects in scene

### ISSUE THREAD

**Issue by daniel-keller** [mrdoob/three.js#12691]
##### Description of the problem 
I have a simple box mesh with a morphTarget and a slider which adjusts the morphTargetInfluence. The morph affects the mesh as it should but it also shrinks any other mesh in the scene. 

I've put together a jsfiddle (modified from the threejs morph target) example below to demo the issue. In this demo moving the slider correctly morphs the corner of the red cube but incorrectly shrinks the size of the blue cube. The cube meshes are entirely unrelated so I don't see how the morph could affect the blue cube.

https://jsfiddle.net/djmm7vv2/ (88)

##### Three.js version

- [ ] Dev
- [x] r88

##### Browser

- [x] All of them
- [x] Chrome
- [x] Firefox
- [x] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
```javascript
var blue = new THREE.MeshLambertMaterial( { color: 'blue', morphTargets: false } );
```
