### ISSUE TITLE
Unable to use WebGLRenderTarget with webVR

### ISSUE THREAD

**Issue by sjlynch** [mrdoob/three.js#12706]
##### Description of the problem 
I am rendering a scene to a plane using WebGLRenderTarget and it is working great outside of WebVR. As soon as I enter VR (click on the enter VR button) with Oculus rift, the scene turns white and the Oculus doesn't render anything when putting it on. Without the render target, VR works perfectly.

		renderer.render(scene, camera);
		renderer.render(skyScene, camera, skyTexture, true);

If I comment out the second line, VR mode works again (but obviously the texture doesn't get rendered).

I also rendered the texture to a cube positioned in the middle of the scene and had the same problem (blank screens). Any idea what might cause this? Has anyone had success rendering to a texture when in VR mode?

##### Three.js version

- [x] Dev
- [x] r88
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
1080GTX, Oculus Rift

**Comment by WestLangley** [comment]
Question [cross-posted](https://stackoverflow.com/questions/47381167/threejs-cannot-use-webglrendertarget-with-webvr) on SO.

**Comment by takahirox** [comment]
`submitFrame()` twice could cause the issue?

https://github.com/mrdoob/three.js/blob/8213851a45c405cad68d86e90dfa44387fa2f95e/src/renderers/WebGLRenderer.js#L1200-L1204

What'll happen if you comment out the above code and replace your code with the following code?

    renderer.render( scene, camera );
    renderer.render( skyScene, camera, skyTexture, true );

    if ( renderer.vr.enabled ) { 
  
        renderer.vr.submitFrame(); 
  
    } 
`

**Comment by mrdoob** [comment]
Related: #11582

**Comment by Mugen87** [comment]
Closing in favor of #15614
