### ISSUE TITLE
premultiplied alpha material update problem

### ISSUE THREAD

**Issue by Astrak** [mrdoob/three.js#12705]
Using premultiplied alpha gives awesome renderings, thanks a lot for this feature, especially to @bhouston . However I'm reporting some issues with it. I've tried all my best just to understand them but in vain, so pardon my poor descriptions. For each of them the provided code is to be tested in [the premultiplied alpha example](https://threejs.org/examples/webgl_materials_transparency.html)

## 1. 
Switching the `premultipliedAlpha` property on both materials at runtime creates a very different rendering : 
```js
scene.children[1].material.premultipliedAlpha=false;
scene.children[0].material.premultipliedAlpha=true;
```
However it seems that actually the mesh with the original premultiplied alpha is the one with the incorrect rendering : if an opacity of 0 is set for both meshes along with a black color, the mesh with the original premultiplied alpha is unvisible, while the mesh that we just turned to premultiplied alpha has visible reflects, this is what I'm personally expecting. 
```js
scene.children[1].material.opacity=scene.children[0].material.opacity=0;
scene.children[1].material.color.setRGB(0,0,0);
scene.children[0].material.color.setRGB(0,0,0);
scene.children[1].material.premultipliedAlpha=scene.children[0].material.premultipliedAlpha=true;
```

## 2. 
At runtime, the following code does not generate the premultiplied alpha for a new mesh (same code as in the example) :
```js
const a=new THREE.Mesh(
  new THREE.SphereBufferGeometry(18,30,30), 
  new THREE.MeshStandardMaterial({
    transparent: true, 
    opacity: 0, 
    color: 0x000000,
    premultipliedAlpha: true 
  })
);
scene.add(a);//the new sphere is fully transparent, no blending
```
However this one does :
```js
const a=new THREE.Mesh(
  new THREE.SphereBufferGeometry(18,30,30), 
  new THREE.MeshStandardMaterial({
    transparent: true, 
    color: 0x000000,
    opacity: 0//no premultiplied alpha defined initially
  })
);
scene.add(a);//exec here
//once the previous lines executed (material compiled in between ?), add this :
a.material.premultipliedAlpha=true//works.
```
## 3. 
If a light is added, then this last mesh, with working premultiplied alpha, disappears, and i can't find a way to get it back. After this, switching the `premultipliedAlpha` property does switch the rendering of the material but only for opacity values superior to 0, nothing is visible at a 0 opacity anymore. This only affects the newly created mesh. However the same problem can be triggered on the original mesh with premultiplied Alpha :
```js
renderer.toneMapping=THREE.ReinhardToneMapping;
scene.children[1].material.needsUpdate=true
//now the original sphere with premultipled alpha 
//does not have it anymore
```

I had a hard time understanding how it exactly works, I tried to recompile everything with `renderer.compile(scene,camera)`, not sure it could really help but it has no effect. 

How to avoid these problems ? I've debugged the shaders with WebGL Inspector, in all cases they seem to keep the related `define`. The code for blending depends on the `premultipliedAlpha` boolean that we can check from the console and has no reason not to be correct. I'm stuck there in my understanding of these rendering differences.

**Comment by WestLangley** [comment]
This looks like a help question to me. Try this.

```javascript
scene.children[ 1 ].material.needsUpdate = true;
scene.children[ 0 ].material.needsUpdate = true;
```

**Comment by bhouston** [comment]
@WestLangley is correct in my opinion.

**Comment by Astrak** [comment]
Ow did I not even try that ? Sorry for the disturbance :innocent:
