### ISSUE TITLE
FBXLoader: show wrong transform

### ISSUE THREAD

**Issue by nNightKil** [mrdoob/three.js#12716]
##### Description of the problem 

Today, I found that FBXLoader doesn't load the correct transform for model. Then, I try the three.js editor on the website, also shows wrong result.

**Original FBX File:**
[test1.zip](https://github.com/mrdoob/three.js/files/1490966/test1.zip)

**Original model in 3dsmax:**
![trrzsv82 381 tkn9 a2f](https://user-images.githubusercontent.com/13641738/33068011-e40b357e-ceea-11e7-9f25-1acb4e4c0a92.png)

**Wrong result in my code:**
![d pawxir1ge69r 1 7nn](https://user-images.githubusercontent.com/13641738/33068007-e3693512-ceea-11e7-801d-0f79b2e0f227.png)

**Three.js Website Editor result:**
![nbvib1 s0v4yhr4 hjcilfn](https://user-images.githubusercontent.com/13641738/33068010-e3dd3a70-ceea-11e7-93d2-5686a1e6b85b.png)
![7s cdu nw a338qm n](https://user-images.githubusercontent.com/13641738/33068008-e3af13d4-ceea-11e7-9375-2cde734a00d2.png)

##### Three.js version

- [ ] Dev
- [x] r88
- [x] r87

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
Confirmed, this seems to be loading correctly in other viewers but not with three.js. I'll take a look.

**Comment by looeee** [comment]
Turned out to be a pretty easy fix: #12717

**Comment by nNightKil** [comment]
Awesome! It's Correct now. ：）
Thank you ~ 👍
