### ISSUE TITLE
The "Hello world" example fails

### ISSUE THREAD

**Issue by Mann90** [mrdoob/three.js#12719]
##### Description of the problem 

The "Hello world" example (https://threejs.org/docs/index.html#manual/introduction/Creating-a-scene) is broken in r88.

I got the error message in the Chrome DevTool console: 'three.js:35947 Uncaught SyntaxError: Unexpected number'.

##### Three.js version

- [ ] Dev
- [X ] r88
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

[helloworld.zip](https://github.com/mrdoob/three.js/files/1492992/helloworld.zip)

**Comment by looeee** [comment]
Checking line 35947 of your three.js file I see this:

`this.aStartAngle = aStartAngle ||Â 0;`

Not sure where the `Â` came from, but removing it fixes the issue.

Perhaps we should change the tutorial to reference three.js this way, what do you think? 
`<script src="https://threejs.org/build/three.min.js"></script>`

**Comment by mrdoob** [comment]
#12634
