### ISSUE TITLE
Broken example in materials/nodes

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#12722]
##### Description of the problem 
The `adv / caustic` example in [materials / nodes](https://threejs.org/examples/webgl_materials_nodes.html) fails due to a broken shader:
````
THREE.WebGLShader: Shader couldn't compile.
THREE.WebGLShader: gl.getShaderInfoLog() vertex
ERROR: 0:339: 'worldPosition' : undeclared identifier 
ERROR: 0:339: 'xyz' :  field selection requires structure or vector on left hand side 
ERROR: 0:339: 'assign' :  cannot convert from 'float' to 'varying highp 3-component vector of float'
 <...shader source...>
THREE.WebGLProgram: shader error:  0 gl.VALIDATE_STATUS false gl.getProgramInfoLog Must have a compiled vertex shader attached.
ERROR: 0:339: 'worldPosition' : undeclared identifier 
ERROR: 0:339: 'xyz' :  field selection requires structure or vector on left hand side 
ERROR: 0:339: 'assign' :  cannot convert from 'float' to 'varying highp 3-component vector of float'
Error: WebGL warning: linkProgram: Must have a compiled vertex shader attached.
Error: WebGL warning: useProgram: Program has not been successfully linked.
````
Above log is from FF 57.0 with the version on threejs.org. The relevant lines for `worldPosition` in the shader source:
````glsl
317: #if defined( USE_ENVMAP ) || defined( DISTANCE ) || defined ( USE_SHADOWMAP )
318: 	vec4 worldPosition = modelMatrix * vec4( transformed, 1.0 );
319: #endif
...
339: vWPosition = worldPosition.xyz;
````
No `#define`s for those constants in the dumped source.

##### Three.js version
- [x] Dev
- [x] r88

##### Browser
- [x] Chrome 62.0.3202.94 (current)
- [x] Firefox 57.0 (current)

##### OS
- [x] Windows

**Comment by moraxy** [comment]
got it, rev db347605ed00cdf045f88120289056f3f299f088 is to blame, it removed the `defined( PHYSICAL )` from the line `317: #if defined( USE_ENVMAP ) || defined( DISTANCE ) || defined ( USE_SHADOWMAP )` above. Just adding it back in fixes it and so far no new bugs in the other node examples.  
Was there a reason for removing it beyond simple cleanup?

**Comment by mrdoob** [comment]
> Was there a reason for removing it beyond simple cleanup?

Can't recall. Do you want to do a PR?

**Comment by WestLangley** [comment]
>Just adding it back in fixes it 

Let's see if @sunag will have a look...

**Comment by sunag** [comment]
I will see. I just forgot about it.
