### ISSUE TITLE
GLTF Loader not loading the keyframe translate animation?

### ISSUE THREAD

**Issue by im84** [mrdoob/three.js#12728]
Hi there,
I'm quite new to Three JS and I'm having a problem to get working a simple KeyFrame translate animation, yet the rotation seems to work well.
I use the GLTF Loader to get the model with the animations into Three JS. Is there any known issue related to this type of animation? Is it not supported in Three JS or am I doing something wrong?

Note:
I've tried several sample models with this type of animation to open up in https://fltf-viewer.donmccurdy.com, yet with no success, as well. 

Here's the sample gltf model from https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxAnimated

[glTF-sample.zip](https://github.com/mrdoob/three.js/files/1498036/glTF-sample.zip)

Thanks a lot
Cheers

Igor

**Comment by donmccurdy** [comment]
It's working for me: https://gltf-viewer.donmccurdy.com/#model=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoxAnimated/glTF/BoxAnimated.gltf

^Note that you need to open the Animations menu and press *playAll*.

**Comment by im84** [comment]
Thanks a lot!
You are right about that one :) 
Yet the same thing doesn't seem to be working (at least for me) in these 2 models:

[translate_animations.zip](https://github.com/mrdoob/three.js/files/1498266/translate_animations.zip)

I can see, that in the previous model, the rotation and the translation have been done (exported) as 2 separate animations.
In the latter 2 models, there's only 1 animation in the list, though. May this be the issue? Should I always separate multiple animations somehow to get them played properly?

Thanks a lot for your help

Igor

**Comment by im84** [comment]
I think I've found it!
When exporting model from Blender to GLTF, I must have the "Force sample animations" checkbox checked :)

Everything works just fine afterwards :)

Thanks

![image](https://user-images.githubusercontent.com/33920018/33162355-c156cbe8-d05b-11e7-9cea-28628eb2beb9.png)

**Comment by donmccurdy** [comment]
I’m surprised that checkbox was needed, but glad it’s working! Freezing transforms (or whatever Blender’s equivalent is...) might help avoid surprises. The Khronos Group Blender exporter does not support multiple Actions yet, so everything will be part of the same animation when you export to glTF.
