### ISSUE TITLE
Loading issue in TDSLoader

### ISSUE THREAD

**Issue by stef-levesque** [mrdoob/three.js#12730]
https://github.com/mrdoob/three.js/blob/97cab20e90ab6188b9bc10af13d5be406f0b8854/examples/js/loaders/TDSLoader.js#L53-L60

@cnspaha I don't think you should `loader.setPath( path );` at L57, it result in the loader duplicating the base path when trying to load the mesh file.

(i.e. loading 'file:///some/path/mesh.3ds' result in the loader trying to load 'file:///some/path/file:///some/path/mesh.3ds' )

**Comment by cnspaha** [comment]
Yeah I get your problem.
Till now I always set the path via the ```setPath()``` method and afterwards just passed in the filename instead of the whole path so it worked for me. But you are right, will take a look into it and provide a fix / PR

**Comment by cnspaha** [comment]
should be fine now with PR #12731 , please close ;)
