### ISSUE TITLE
opaque objects sorting problem with depthTest=false

### ISSUE THREAD

**Issue by sgaoae** [mrdoob/three.js#12737]
##### Description of the problem 
Example:
https://jsfiddle.net/v2udjzbe/
Two boxes are drawn with ShaderMaterial. 

Front box: yellow, depthTest: false, transparent: false
Back box: red, depthTest: true, transparent: false
The back box appears in front of front box while it is expected to be in the back. 

I think how it is caused:
The sorting of opaque objects in WebGLRenderLists should be the reason. 
program.id and material.id are used before z index, so the earlier the WebGLProrgram is compiled or the Material is created, more front the object appears. 

I think the if else sequence in the function should be changed. 
1st: renderOrder
2nd: z index
3rd: other things

Suggested change:
```javascript
function painterSortStable( a, b ) {

	if ( a.renderOrder !== b.renderOrder ) {

		return a.renderOrder - b.renderOrder;

	}  else if ( a.z !== b.z ) {

		return a.z - b.z;

	} else if ( a.program && b.program && a.program !== b.program ) {

		return a.program.id - b.program.id;

	} else if ( a.material.id !== b.material.id ) {

		return a.material.id - b.material.id;

	} else {

		return a.id - b.id;

	}

}
```

Currently, the problem has not been tested on other platforms but I think it is a common one. 
Thank you very much. @mrdoob 

##### Three.js version

- [ ] Dev
- [x] r83
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by sgaoae** [comment]
@mrdoob

**Comment by sgaoae** [comment]
This can be related to #9208
@mrdoob

**Comment by sgaoae** [comment]
VERY SORRY. It does not work and I sincerely apologize if the suggestion wastes your time. 
@mrdoob

**Comment by sgaoae** [comment]
I write a new example using three box geometry and MeshBasicMaterial https://jsfiddle.net/errd49Lk/1/

I have found such pattern:
1. the order depends on the creation order
a: transparent: false, depthTest: false
b: transparent: false, depthTest: false

2. the order depends on the creation order
a: transparent: false, depthTest: false
b: transparent: false, depthTest: true

3. the order depends on the position
a: transparent: false, depthTest: true
b: transparent: false, depthTest: true

I am very curious about pattern 2. I think the order should also depend on position for pattern 2, so the problem could be related to depthTest.

**Comment by sgaoae** [comment]
I think I have found the reason for the jsfiddle example. 
The reason should be that disabling depthTest also disables depthWrite in webgl. 

For https://jsfiddle.net/v2udjzbe/: 
Front box: yellow, depthTest: false, transparent: false
Back box: red, depthTest: true, transparent: false

Front box is drawn first. its color is drawn on the screen and the depth buffer is not updated. 
Back box is drawn after that, as the depth of front box is not written in depth buffer, its color will be drawn and override the front box color. 

For https://jsfiddle.net/errd49Lk/1/: 
cube0: blue, depthTest: false, 1st closest to camera
cube1: green, depthTest: true, 2nd closest to camera
cube2: red, depthTest: true, 3rd closest to camera

cube0 is drawn first. its color is drawn on the screen and the depth buffer is not updated. 
cube1 is drawn after that, as the depth of cube0 is not written in depth buffer, its color will be drawn and override the cube0 color. 
cube2 is drawn after that, as the depth of cube0 is not written in depth buffer, its color will be drawn and override the cube0 color, but as the depth of cube1 is written, its color will not override cube1 color. 

So by setting depthTest=false, we automatically set depthWrite=false in rendering although the depthWrite value in Material is not updated. Am I right?
But I want the cube0 and front box to appear before certain other objects, is there a way to achieve such effects without setting renderOrder? I have lots of objects in my scene and I just don't want to specify for each of them. 
Or is there a way to turn on depthWrite whiling setting depthTest to false?

Thank you very much. @mrdoob

**Comment by mrdoob** [comment]
Sorry, I'm getting lost. Do you mind simplifying your question?

**Comment by sgaoae** [comment]
Yeah... My mistake. But a small suggestion if my analysis is right:
If disabling depthTest automatically disables depthWrite, please update the depthWrite value of the material when setting depthTest=false just to be more clear. 
Thank you very much and sorry for making you lost. 
@mrdoob

**Comment by WestLangley** [comment]
>disabling depthTest automatically disables depthWrite

That is not true.

I think you need to visit a help site. [Maybe this](https://stackoverflow.com/questions/12666570/how-to-change-the-zorder-of-object-with-threejs/12666937#12666937).

**Comment by sgaoae** [comment]
@WestLangley 
But gl.disable(gl.depth_test) will disable depthtest and also prevent write to depth buffer so depthwrite is also disabled and both of depthtest and depthwrite will not take effect, right?
If not so, can you explain the effects in my example https://jsfiddle.net/v2udjzbe/ and https://jsfiddle.net/errd49Lk/1/ ? I think the effects are just pretty wierd.

**Comment by sgaoae** [comment]
Dear all, @mrdoob , @WestLangley 
I have found a way to achieve the effects that I want by modifying 
WebGLState.js function DepthBuffer function setTest:

now in https://jsfiddle.net/v2udjzbe/, the red box appear after the green one and I can see all of the three box in correct order in https://jsfiddle.net/errd49Lk/1/ using the same code
here is my modification:

```javascript
setTest: function ( depthTest ) {

	if ( depthTest ) {

		enable( gl.DEPTH_TEST );
		let depthFunc = currentDepthFunc
		if ( depthFunc ) {
			switch ( depthFunc ) {
				case NeverDepth:
					gl.depthFunc( gl.NEVER );
					break;
				case AlwaysDepth:
					gl.depthFunc( gl.ALWAYS );
					break;
				case LessDepth:
					gl.depthFunc( gl.LESS );
					break;
				case LessEqualDepth:
					gl.depthFunc( gl.LEQUAL );
					break;
				case EqualDepth:
					gl.depthFunc( gl.EQUAL );
					break;
				case GreaterEqualDepth:
					gl.depthFunc( gl.GEQUAL );
					break;
				case GreaterDepth:
					gl.depthFunc( gl.GREATER );
					break;
				case NotEqualDepth:
					gl.depthFunc( gl.NOTEQUAL );
					break;
				default:
					gl.depthFunc( gl.LEQUAL );
			}
		} else {
			gl.depthFunc( gl.LEQUAL );
		}

	} else {
		// disable( gl.DEPTH_TEST );
		gl.depthFunc( gl.ALWAYS )
	}
}
```
I think gl.disable(gl.depth_test) will disable depthtest and also prevent write to depth buffer, while I want to do no depth comparison and write to depthbuffer to achieve my expected effects in my example.

**Comment by WestLangley** [comment]
@sgaoae Apologies, you are correct.

> Disabling depth testing Deactivates depth comparisons and updates to the depth buffer.

> The glDepthFunc function specifies the function used to compare each incoming pixel z value with the z value present in the depth buffer. The comparison is performed only if depth testing is enabled.

So if `material.depthTest = false`, there will be no writes to the depth buffer, even if `material.depthWrite = true`.

I believe the library is operating correctly. Do you disagree?

**Comment by sgaoae** [comment]
Well, that operation causes the effect shown in my two examples, and also some problems in my project. The behavior I expect is that directly writing to depth buffer without comparison is allowed while in the current implementation, it is not. 

Initially, I thought it was a bug, now I have removed the word "BUG" in the title. 

Thank you for the help link, but it is not very useful as I will have to move many objects between two scenes if using that implementation. 

I hope that I can get the expected behavior by set depthTest=false and depthWrite=true, or through using other APIs. Thank you very much.

**Comment by mrdoob** [comment]
> The behavior I expect is that directly writing to depth buffer without comparison is allowed while in the current implementation, it is not.

Unfortunately, that's how how WebGL itself behaves...

> I hope that I can get the expected behavior by set depthTest=false and depthWrite=true, or through using other APIs. 

Good luck!

**Comment by sgaoae** [comment]
@mrdoob 
But instead of using gl.disable(gl.depth_test), using gl.depthFunc(gl.always) can allow writing to depth buffer with no comparison. Will you consider use gl.depthFunc(gl.always) when setting depthTest=false?
You can refer to my modification below. 
This is my final question now and really thank you very much for your help. 
```javascript
setTest: function ( depthTest ) {

	if ( depthTest ) {

		enable( gl.DEPTH_TEST );
		let depthFunc = currentDepthFunc
		if ( depthFunc ) {
			switch ( depthFunc ) {
				case NeverDepth:
					gl.depthFunc( gl.NEVER );
					break;
				case AlwaysDepth:
					gl.depthFunc( gl.ALWAYS );
					break;
				case LessDepth:
					gl.depthFunc( gl.LESS );
					break;
				case LessEqualDepth:
					gl.depthFunc( gl.LEQUAL );
					break;
				case EqualDepth:
					gl.depthFunc( gl.EQUAL );
					break;
				case GreaterEqualDepth:
					gl.depthFunc( gl.GEQUAL );
					break;
				case GreaterDepth:
					gl.depthFunc( gl.GREATER );
					break;
				case NotEqualDepth:
					gl.depthFunc( gl.NOTEQUAL );
					break;
				default:
					gl.depthFunc( gl.LEQUAL );
			}
		} else {
			gl.depthFunc( gl.LEQUAL );
		}

	} else {
		// disable( gl.DEPTH_TEST );
		gl.depthFunc( gl.ALWAYS )
	}
}
```

**Comment by sgaoae** [comment]
No need for this. 
set depthTest = true, depthWrite=true, depthFunc = AlwaysDepth should achieve the effects. 
Sorry for the interruption. 
Revised example:
https://jsfiddle.net/sgaoae/v2udjzbe/1/
https://jsfiddle.net/sgaoae/errd49Lk/2/
