### ISSUE TITLE
Anti-aliasing works in older versions but not in recent versions

### ISSUE THREAD

**Issue by ykessler** [mrdoob/three.js#12740]
##### Description of the problem 

Setting WebGLRenderer `antialias: true` works as expected in version 68, but seems to have no affect in versions 78 or 88. 
`renderer = new THREE.WebGLRenderer( { antialias: true } );`

- r68: https://jsfiddle.net/8p7jja9L/5/ (Works)
- r78: https://jsfiddle.net/8p7jja9L/6/ (Doesn't work)
- r88: https://jsfiddle.net/8p7jja9L/7/ (Doesn't work)

68 result:
<img width="133" alt="screen shot 2017-11-24 at 1 04 30 pm" src="https://user-images.githubusercontent.com/321127/33220693-3f689cca-d118-11e7-89fc-08236b55d435.png">

78,88 result:
<img width="111" alt="screen shot 2017-11-24 at 1 04 46 pm" src="https://user-images.githubusercontent.com/321127/33220698-44fea724-d118-11e7-9384-1eec616345ee.png">

##### Three.js version

- [x] r88
- [x] r78
- [ ] r68

##### Browser

- [x] Chrome
- [x] Firefox
- [x] Safari

##### OS

- [x ] macOS

**Comment by moraxy** [comment]
Weird, they all render the same to me. Can you see the difference in the [multiple renderers example](https://rawgit.com/mrdoob/three.js/dev/examples/webgl_multiple_renderers.html)?

Also, do you have HiDPI screen? If so, adding `renderer.setPixelRatio( window.devicePixelRatio );` might be worth a try.

**Comment by Mugen87** [comment]
The solution is to add `renderer.setPixelRatio( window.devicePixelRatio );`.
