### ISSUE TITLE
multiplyVectors() on Vector3 does compute properly

### ISSUE THREAD

**Issue by ddimitrovd** [mrdoob/three.js#12741]
I am doing the flowing operation:

`console.log('dirVec:', directionVector);
 console.log('nodeAim:', nodeAimVector);
 rotationVector.multiplyVectors(directionVector, nodeAimVector);
 console.log('rot:', rotationVector);`

As It says in the documentation multiplyVectors(a,b) should get the cross product a x b.
here is the output i get:

dirVec: Vector3 {x: -0.37183999999999173, y: 0, z: 0}
nodeAim: Vector3 {x: -396.62816, y: 4.5, z: 0}
rot: Vector3 {x: 147.4822150143967, y: 0, z: 0}

This is obviously not correct. the rotationVector shout be a vector entirely parallel to the Z axis. Am I wrong? I have used several cross product calculator and they all confirm it.

**Comment by Mugen87** [comment]
The docs might be a little bit unclear in this case. `a x b` does not mean cross product but just a component-wise multiplication.

Use `Vector3.crossVectors()` to calculate the cross product.

**Comment by Mugen87** [comment]
Maybe we should change this to `a * b`...

**Comment by ddimitrovd** [comment]
Thanks! Yeah it is definitely unclear. I think it should indeed be `a * b`

**Comment by YawarRaza7349** [comment]
I think saying "component-wise multiplication" would be clearer than saying `a * b` (and similarly for the division methods).

**Comment by Mugen87** [comment]
Fixed in `dev` see 8ae267866c11afd994be17c51c295cdc707ae375

@YawarRaza7349 Any chances you make a PR with your proposal? For consistency reasons, it would be also necessary to adjust the documentation for `Vector2` and `Vector4`.
