### ISSUE TITLE
GLTF 2 Glossiness is too strong

### ISSUE THREAD

**Issue by vorg** [mrdoob/three.js#12749]
I've been implementing Specular Glossiness GLTF extension in my own engine and came to ThreeJS as a source of through to discover that something is off in your implementation as the glossiness is too strong. 

Screenshot of your gltf loader from r88 https://threejs.org/examples/?q=gltf#webgl_loader_gltf

Metallic Roughness:
![screen shot 2017-11-25 at 21 34 16 copy](https://user-images.githubusercontent.com/171001/33235366-5443e8c6-d22f-11e7-8043-30c16ffa50e2.jpg)

Specular Glossiness:
![screen shot 2017-11-25 at 21 34 05 copy](https://user-images.githubusercontent.com/171001/33235368-59fd8772-d22f-11e7-97c2-a46d1e157195.jpg)

I assume the first one (Metallic-Roughness) is correct as it looks consistent with BabylonJS although the black part is too dark on both but looks better on the second screenshot (might be another issue).

![screen shot 2017-11-25 at 21 51 59 copy](https://user-images.githubusercontent.com/171001/33235390-a5b91c6c-d22f-11e7-8baf-2c6fc7f69061.jpg)

any my engine (PEX).

![screen shot 2017-11-25 at 22 26 46 copy](https://user-images.githubusercontent.com/171001/33235401-c7fc56c2-d22f-11e7-8dda-1c908f200075.jpg)

##### Three.js version

- [x] r88

##### Browser

- [x] All of them

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
For the "too dark" part of the issue, I've reopened #12554.

/cc @takahirox for the question of glossiness

**Comment by takahirox** [comment]
Probably I've figured out.

Specular-Glossiness texture RGB should be applied in sRGB space but I was missing sRGB encoding.

https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_pbrSpecularGlossiness#specularglossinesstexture

I'll make PR soon.
