### ISSUE TITLE
Unit tests status - what to do with unit test bugs / mistakes?

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#12759]
##### Description of the problem 

While browsing three.js code, sometimes I find an error in the unit test code.

I am not sure what is the current status of unit tests for the project. While browsing the code, some tests seem to be quite complete (math), some partial (core), some more or less stubs (todos) only (see also #12714).

When I run tests using `npm test`, the result is:

```
1..1788
# pass 3
# skip 0
# todo 1284
# fail 501

```

 Are you interested in such problems? Should I create issues or PRs for them? Would you prefer an individual PR for each test, or multiple tests at once?

##### Three.js version

- [X] Dev

**Comment by Mugen87** [comment]
\ping @Itee

**Comment by donmccurdy** [comment]
Hi @OndrejSpanel! Most of those "failed" tests are actually passing; it is a temporary problem in the test framework fixed by #12768. There are about ~30 remaining tests that really are failing right now, and then the ~1200 TODOs. I think we'd be glad to have PRs for any of those issues, however you prefer to send them. Batching them up is completely fine. 🙂  Thanks!

**Comment by OndrejSpanel** [comment]
OK. Once that PR is merged, I will check this again and hopefully submit a PR soon.

**Comment by OndrejSpanel** [comment]
I am checking the test now after the merge. I can confirm it is improved, When running from a browser, the result is: 

> with 31 failed, 0 skipped, and 1126 todo.

When running using `npm test`, it is a bit worse, many test are reporting error:

> stack: TypeError: assert.numEqual is not a function

Totals running with `npm test` are:

```
1..1750
# pass 504
# skip 0
# todo 1126
# fail 120

```

**Comment by moraxy** [comment]
The error with `assert.numEqual` can at least temporarily be fixed by including `test/unit/qunit-utils.js` in the generated `test/unit/three.source.unit.js`. Then you get a slight improvement:
```
1..1750
# pass 553
# skip 0
# todo 1126
# fail 71
```

**Comment by Itee** [comment]
You should not be hurt by the fails in fact. The are lot of things that are currently incorrect. Be patient ! Unit tests are a really big part. I will submit PR soon, file by file.
