### ISSUE TITLE
Bounding Sphere in Triangle

### ISSUE THREAD

**Issue by erickavalossantiago** [mrdoob/three.js#12767]
Para un proyecto estoy realizando una semisuma de los puntos del triangulo y luego calculando una esfera que lo envuelva para utilizarlo en colisiones para un mejor rendimiento, actualmente no lo tiene, se podría incorporar ?

m = (a+b+c)/3

//bounding sphere.
radius = max (distance(a,m),distance(b,m),distance(c,m)), es posible ?

**Comment by erickavalossantiago** [comment]
Vengo trabajando en un proyecto FPS básico donde tengo que saltar sobre bases triangulares y al comparar punto por punto para todos los triángulos, suele disminuir el rendimiento así que opté por envolver cada triángulo en una esfera y así ayuda a saber qué triángulos están cerca y sólo calcular la posible colisión con los triángulos más cercanos o que colisionen con ese límite de esfera.

**Comment by erickavalossantiago** [comment]
I want implement custom physics collisions, so using meshes decrease performance, hence i am using THREE.Triangle instead that.

**Comment by makc** [comment]
> using meshes(THREE.Mesh) decrease performance

how exactly? it just runs [this](https://github.com/mrdoob/three.js/blob/master/src/math/Ray.js#L433) in the loop. Triangle class does not store anything pre-calculated for this method, it just holds vertex references - if you want faster math, you need to bypass 3js completely
