### ISSUE TITLE
Encapsulate "warn" as Three.warn

### ISSUE THREAD

**Issue by mandysimon88** [mrdoob/three.js#12774]
This is a request to encapsulate all instances of "console.warn" as Three.warn so that lines like 16797 do not spit out hundreds of lines of code.

If it were just encapsulated, then someone sophisticated could choose to override it. But, the default behavior and @mrdoob's desire to not allow developers to just flip a switch and disable logging would still be preserved.

As is, the only way to run a test with Three and an external library (like, say, a mock canvas with a mock webgl context) is to try to turn off warns all the places Three is called...

It wouldn't be so bad if the warns spit out a line or two, but hundreds of lines of code like 16797 is just crazy. When you have multiple tests, it's thousands of lines of code, only a handful of which are actually meaningful deprecations.

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/pull/5835#issuecomment-347614373
