### ISSUE TITLE
PositionalAudio doesnt correctly disconnect its panner

### ISSUE THREAD

**Issue by zynga-jpetersen** [mrdoob/three.js#12775]
##### Description of the problem 

When PositionalAudio disconnects it doesn't disconnect its panner.

I built a small test where I loopily create and recreate the same audio file.

http://jsfiddle.net/hubrf011/3/

I used an audio inspector in chrome to observer the web audio nodes behavior:
https://chrome.google.com/webstore/detail/web-audio-inspector/cmhomipkklckpomafalojobppmmidlgl

Each loop I destroy the last PositionalAudio and create a new one. But in the inspector you can see the original PannerNode persists and its gainer is still connected.

During the cleanup, I remove the PositionalAudio from the parent, call stop and then disconnect. Reading the documentation I don't see what else I should be doing.

I created a small test:
http://jsfiddle.net/hubrf011/3/

I also tried to do a bit of manipulating the internals of the class Audio to see if just needed an  additional panner disconnect but its still leaking the panner node. (http://jsfiddle.net/hubrf011/4/)

Sorry about the audio file in the example, it was just the first one that came up when searching for free test sound that was relatively tolerable to hear on loop.

Thanks for looking at my issue and thanks for the great library.

##### Three.js version

- [x] r88

##### Browser

- [  ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I'm not sure if the visualization of the Chrome extension is correct. The Web Audio developer tool in Firefox  shows a completely different behavior that actually meets my expectations: The nodes are garbage collected and disappear from the visualization. Therefore, it shouldn't matter if there is a connection between the panner and the respective gain node.

@zynga-jpetersen What result do you get with the latest FF?

**Comment by Mugen87** [comment]
Just for the sake of completeness: It is actually not necessary to recreate `Audio` or `PositionalAudio` objects for playback. The usual workflow is to load your audio files once and reuse them in your scene.

But still we should clarify if `three.js` actually disposes audio elements in a correct way.

**Comment by zynga-jpetersen** [comment]
Yeah I'd originally seen the case when spawning a lot of different sound effects in three and built an smaller example that replicated the behavior (and recreating the same sound seemed like the easiest example). 

In my real use case I was seeing hundreds of panner/gain nodes all trying to affect one gain node at the end. It seemed to be causing the audio to get really "crunchy" which I thought might be related to the great number of connections (my attempts since reporting this bug, as I mentioned above, seemed to fixed the connections but not crunchiness from playing a lot of audio all at once (this was in chrome)). I'm still investigating the cause of that, which I think is really just related to playing too many PositionalAudios at once.

Anyway I'm trying to repro the behavior my test case showed in firefox, but for some reason in the Web Audio panel I'm only seeing "Waiting for an audio context to be created...". I'll see if it working on my machine or someone else's to re-confirm what I was previously seeing.

Thanks for the prompt responses.

**Comment by Mugen87** [comment]
> Anyway I'm trying to repro the behavior my test case showed in firefox, but for some reason in the Web Audio panel I'm only seeing "Waiting for an audio context to be created..." even though the sound is playing.

I guess FF can't identify the audio context when the application runs in an iframe of another site. It only works for me when i call the page directly.

**Comment by Mugen87** [comment]
@zynga-jpetersen Any news on this?

**Comment by Mugen87** [comment]
Closing for now.

**Comment by dataexcess** [comment]
I'm having the same problem. can confirm with Audio chrome extension

**Comment by mrdoob** [comment]
@Mugen87 I guess `PositionalAudio` needs this?

```js


	disconnect() {

		super.disconnect();

		this.panner.disconnect( this.gain );

	}
```

**Comment by Mugen87** [comment]
Looking good!

**Comment by mrdoob** [comment]
I'll do a PR.
