### ISSUE TITLE
Textured, unanimated mesh disappears when another animated mesh starts animating

### ISSUE THREAD

**Issue by madmaw** [mrdoob/three.js#12776]
##### Description of the problem 

We have a problem where if you load a textured, unanimated mesh using the `JSONLoader` the mesh created from that will disappear from the scene when a completely separate textured, animated mesh, also loaded using the `JSONLoader`, starts animating.  

I have a simplified example of the behavior here

https://codepen.io/madmaw/project/editor/Depkde#0

You can see the two boxes get loaded (you'll have to excuse the 404 on the texture file, codepen doesn't allow media uploads on the free version - doesn't effect the behavior though) and are visible, then the monster mesh gets loaded, then the animation starts and one of the boxes disappears. The box that disappears has `morphTarget` manually set to `true` on its material, while the one that stays does not.  I would expect both boxes to remain visible after the animation starts playing. 

I've worked around it for the time-being by turning off `morphTarget` on meshes that don't have animations. This seems to work in all cases, even when you have a mesh that contains animations, has `morphTarget` set to `true`, but isn't animating. 

##### Three.js version

- [ ] Dev
- [x] r88
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Why are you setting `material.morphTargets = true` when the geometry does not have morph targets defined?

**Comment by madmaw** [comment]
Ah, because I don't know any better. Makes sense now you point it out, but it's not obvious from a user's perspective, and it's not mentioned in the documentation for material, and a lot of examples contain that line (which I assumed was harmless). Perhaps it could handle this case a bit more gracefully, either a warning or not randomly getting removed?

**Comment by WestLangley** [comment]
Your meshes are sharing shaders -- in particular, the monster and the first cube share a Lambert shader that supports textures and morphs, but the first cube does not have morphs defined. That error is causing an issue when the monster animation begins.

Your work-around is obvious. Someone else will have to decide if we want to do anything about this.

**Comment by WestLangley** [comment]
@Mugen87 I'm thinking we can close this. What say you?
