### ISSUE TITLE
renderer.getDrawingBufferSize() not reporting correct width and height

### ISSUE THREAD

**Issue by DJviolin** [mrdoob/three.js#12770]
I have the following setup where I calculating the screen's width and height value multiplied with the pixel ratio: [[LINK]](http://mrdoob.com/projects/htmleditor/#B/rVbtb6M2GP+c/hVetql0o0BuO+2Whk5rLmtP6m1VW6maNGln4AHcA5vZJkmv1/99jw0k0KTTfZiiAH7e/Xte7NlXb/+Y3/55tSC5LovTg5l5kYLyLBwDH58ejGY50ATfo5lmuoBTnUsA716RFURZQY5JBqIELR/wM64jmPmNnNFAOiVxTqUCHY5rnR6/GW8ZnJYQjpcMVpWQekxiwTVwFFyxROdhAksWw7FduKRWII9VTAsaFRBy4ZKScVbWpSVCOPECJNH1kNR4U/qhCWgUieSBPJqvUUllxviUBCd2KZYg00KspiRnSQLcUp/MI6Z8SVWrVQnFNBOoRyMlilpDo65FtTFVQKo3Cxv+lEyC4NuGkAPLct2jGCczv4tx5rd4z0yspwc2/liyShMl43Cca12pqe+XMhEi8jKm8zryYlH6XWL8qGZF0i4RJCSNT9GBNdI3aBExf98nKyE/UilqnpBUSMyZxKSSqM6mrYDxi25jkYCXCZEVYJ1WvhVldekzpWpQfoKpZcUvLAl/eP3zm+DrePLKmGApcVaMJ2LlMc5B3hlcSBiGJDhqsd3DJhWVWBI92smO6IUF9JlsQ2zxNc8lxV1hwUnqEhUDB5egdAIS5EnHL0E19m3aBVeaVGwNxTXFlKOD1mtTmFdbzufPZHKy1bmZXy8Wv/999+7t7cVWq7et73pmd/UuFu/OL26fKbabHGpaXDnTzpG1QrEfqAazMsu05rEpVdKIIMgWOsyhhQEdcFiR2wt06l2BVBWg+BLmluuQn7CfdkP390TlkolryjkgTRyjL3cwgMofIvCCWa9rQe8TevgxCJrdjmxSBz5vDKXFpmF7EY0/Zk2Z9yXnohDSIcE6DcyPtAjaotCw1rUcWr5taJeCYgE5R16BHw457HrTtt698oTMfFjTsiqwL1o7yo8lJgkbNz0c+NmM0b6jM7E+q9MU5HnLdcirAHHrHh00tnrRrGS0GBh4jyV9RhWL37dchzyiJA6rbl9PmyhM+e8oO5vA3K2HAaY0wb1b3c5Q11gDY3cQnV9et5wuK21FdgoenhPbvnJebLhWe6h4wz6Bs1uy7r4+ag284HfbY3vkrJt+3brDsu2KFVta4JAsROZ86ItPyTeP/fXTX3yg3+M3BBR4AQcjuo316UMf1ETEdWnGoTlGPFpVuIV5jgeDs5l7XiLKRQFGapM63z/oD1jM7WKJ/Eum8GjGvJFDLGFE4NAlgt9ZoWtLcElKCwWdoafhCBrK7g4jj9rpsHda7hs5g4Gw0f2vaTLQqKsES/lKinuw8WFzSLZ2tiD8j3X1BfWyB7DNLO+QkvAPnq76V0tHid8kbsXp5AY97EmhrYy3Jt/j+eoFweuTPdyHljt51rZe8+F052Q7zvuB9q8TM7+5qeDNxV4h/wU=)

I tried to implement `renderer.getDrawingBufferSize()`, because if I believe it does the same thing: [[LINK]](http://mrdoob.com/projects/htmleditor/#B/rVZtb9s2EP7s/ArO2xBlcyS5W7HOLykWx0sKpFuQBAgGDFgp6SQxlUSNpGynaf77jqRkSbFT9MNgWBLv/Y73HDn75uzPxe1fV0uSqjw7OZjpF8lokcyHUAxPDgazFGiE78FMMZXBiUoFgHsvyRqCJCPHJAGegxIP+BlWAcw8K6c1kE5JmFIhQc2HlYqP3wxbRkFzmA9XDNYlF2pIQl4oKFBwzSKVziNYsRCOzWJEKgniWIY0o0EG84KPSM4Klle5IcJ87PpIops+yXqT6sEGNAh49EAe9dcgpyJhxYT4U7PkKxBxxtcTkrIogsJQn/QjpMWKylqr5JIpxlGPBpJnlQKrrni5NZVBrLYLE/6EjH3/e0tIgSWp6lC0k5nXxDjz6nrPdKwnByb+ULBSESnC+TBVqpQTz8tFxHngJkylVeCGPPeajfGCimVRvcQiIWl4gg6Mka5BUxH99zyy5uIjFbwqIhJzgXsmcFNJUCWTWkD7Rbchj8BNOE8yME5Lz4iyKveYlBVIL8KtZdlbFs1/ev3rG//bcPxKm2AxcdasiPjaZUUB4k7Xhcznc+If1bXdwyYlFdgSHdp0R/TCFPSZrCXW9dXPFcWssOEEHREZQgEjgtIRCBDThp+DtPbNtvNCKlKyDWTXFLccHdRebWNetZzPn8l4autktW4W18vlH//cvTu7vWj1Oon90DG8T/Ni+e784vaZap3oju6B6TnsD/YJs+r6HvXtTU0lEDbKOTKaFBFEFeiVXsZVEermJlYEt8UUG2MzhcNwCliT2ws06V6BkCWg+AoWhuuQXxCBu6l6e3IYkfFIA8AnNo7B1zvoldbr5/eCWbcBrfsJPfzs+zbbgWmDns8bTalrY9luQMOPiQVGV3LBMy4c4m9iX/9IXUHTRgo2qhJ9y7eWdskptpxz5Gb44ZDDBs0GrPfS5SLxYEPzMkMk1XakFwrcJIR6fNjzsx28XUenfHNaxTGI85rrkFc+1q15NKUx/Y5mBaNZz8B7BMEplSx8X3Md8oiSON6avJ62UWjA7Cg728BGrYdeTWmEuRvdxlADxZ6xOwjOL69rTrMr1gx2Ooo2Wm4C6kxQ7LPE5n6D/EbhGRa1qrtuJ8lzwBl+2k6PQQ2BrS88ylroOy/OhNp7X9HEtYuR0T6Y1wZe8NuOgD1yxs0X5kCDDpw4HOd4xhPnQ1d8Qr577K6f/i56+h2+JaDAC3XQom2sTx+6uxjxsMr1xNYnnUvLElNYpHh2Oe3ORjxfZqCltr3ieQfdMwCbablC/iWTeHvARiGHiBmswOGI8OLOCF2DnY0xzSQ0hp76M68vuzv9XGrG0d5xvm/G9SbQVvdL46unUZURYudK8Hsw8SEaBds4bRH+x776in7ZU7Dt4dFUSsC/eAFQvxk6SvwuMBWnkesNDVdwZWTcDfkRrwCu77+e7uE+1Nzxsznh2g+nOcrr86MbaPfGM/PsZQovV+aW+x8=)

However this approach not returning the screen's width and height, instead really little values.

##### Three.js version

- [ ] Dev
- [x] r88
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I think the values are correct. The problem in your example is this code:
```javascript
const pixelRatio = window.devicePixelRatio || 1;
const SCREEN_WIDTH = window.innerWidth * pixelRatio;
const SCREEN_HEIGHT = window.innerHeight * pixelRatio;
```
This is actually not necessary since `three.js` automatically calculates the correct dimensions of the canvas. You just have to do this:
```javascript
renderer.setPixelRatio( window.devicePixelRatio );
renderer.setSize( window.innerWidth, window.innerHeight );
```

The drawing buffer represents the actual resolution of your canvas. Check out this [example](https://jsfiddle.net/f2Lommf5/398/) which produced the following output on my machine. 

![console](https://user-images.githubusercontent.com/12612165/33329433-d5298c8c-d45c-11e7-8263-520b92d76ae1.jpg)

**Comment by Mugen87** [comment]
Read #11374 for more information

**Comment by DJviolin** [comment]
Thank You, I misunderstood what that setting is for.

**Comment by DJviolin** [comment]
I tested on mobile and with the documented settings at devicePixelRatio: 2, I'm getting the half of the resolution of the screen. I'm using composer and it's handling the rendering loop.

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/9271#issuecomment-230107655

If you instantiate an instance of `EffectComposer`, the size of the internal render target should be the size of the renderer's drawing buffer. If you are using `EffectComposer.setSize( width, height )` for resizing, you need to multiply the pixel ratio with the parameters. So something like this.

```javascript
var pixelRatio = window.devicePixelRatio;
composer.setSize( window.innerWidth * pixelRatio, window.innerHeight * pixelRatio );
```

**Comment by WestLangley** [comment]
Perhaps, when resizing, a coding pattern similar to that used in the `EffectComposer` constructor would be reasonable.
