### ISSUE TITLE
CurrentRenderList is not disposed of?

### ISSUE THREAD

**Issue by Busata** [mrdoob/three.js#12777]
##### Description of the problem 

We have some memory leaks in our application & I noticed that the currentRenderList & properties object on the WebGLRenderer are not collected. When adding
```javascript
 // to the dispose function they do seem to get collected
currentRenderList = {};
properties.clear();
properties = {};
```
##### Three.js version

- [ ] Dev
- [x] r88
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I think it's no problem that `currentRenderList` is not initialized. `renderLists.dispose();` is the important call that cleans up all references inside `WebGLRenderLists`.

@mrdoob About the properties object: Why not rename the `.clear()` of `WebGLProperties` to `.dispose()` and call it inside `renderer.dispose()`? Same for `WebGLObjects`.

**Comment by mrdoob** [comment]
@Mugen87 sounds good 👍
