### ISSUE TITLE
VR always starts in Firefox Quantum

### ISSUE THREAD

**Issue by Gronsak** [mrdoob/three.js#12785]
##### Description of the problem 

Running any basic code sample in Firefox Quantum (57.0+) seems to initialize VR

For easy testing, going to [this](https://threejs.org/docs/index.html#api/geometries/SphereGeometry) sample site starts SteamVR hooked up to Firefox.

Issue only appears in Firefox, tested in Chrome, Edge and IE.
Not sure if it's a problem in earlier versions of Firefox. I also did some quick testing with some other WebGL frameworks and I didn't experience the same issue.

##### Three.js version

- [ ] Dev
- [x] r88
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
GTX1080, HTC Vive

**Comment by mkeblx** [comment]
Another data point, I couldn't reproduce with: FF 57.0.1, Win10, indicated sample, Rift.

This has been an issue before though.

**Comment by mrdoob** [comment]
> Running any basic code sample in Firefox Quantum (57.0+) seems to initialize VR

What do you mean with initialize VR?

**Comment by mrdoob** [comment]
> For easy testing, going to [this](https://threejs.org/docs/index.html#api/geometries/SphereGeometry) sample site starts SteamVR hooked up to Firefox.

Hmm... Sounds like a Firefox bug?
