### ISSUE TITLE
help me. i`m calculate screen coord in vertex shader is wrong

### ISSUE THREAD

**Issue by dytmh** [mrdoob/three.js#12786]
gl_Position = uPMatrix * uMVMatrix * vec4(positions, 1.0);
vec4 pos = normalize(gl_Position);
vec2 screenpos = vec2(pos.x * 0.5 + 0.5, pos.y * 0.5 + 0.5) * viewportSize;
vec2 uv = screenpos / viewportSize;
vec4 color = texture2D(textureAlpha, uv);

textureAlpha size === viewportSize

i`m use gl_FragCoord.x/viewportSize.x in fragment shader is ok.

perspective or ortho projection is same wrong.  this image use ortho projection.

this is textureAlpha  framebuffer
![_20171201112959](https://user-images.githubusercontent.com/4333197/33466810-47301456-d68b-11e7-8ada-704febc3f5b1.png)

this is other shader use textureAlpha 
![_20171201112948](https://user-images.githubusercontent.com/4333197/33466824-633e4136-d68b-11e7-8327-1fa5cc7391d2.png)

**Comment by WestLangley** [comment]
Sorry, this is not a help site. Try the [forum](https://discourse.threejs.org).
