### ISSUE TITLE
Many Empty Warnings

### ISSUE THREAD

**Issue by dylnmc** [mrdoob/three.js#12782]
##### Description of the problem 

I am not sure if this is reproducible, but I am on Windows 7, and I am using Firefox Quantum. I see a lot of these warnings: `THREE.WebGLProgram: gl.getProgramInfoLog()`; however, there is no message associated with them.

Here is the cause (if I do not add what this function returns to the scene, then I do not get the warning in firefox):

```javascript
/**
 * createWave(): creates a sine wave
 * @param {number} len length
 * @param {number} amp amplitude
 * @param {number} freq frequency of wave -- dont' forget freq = (velocity)/(wavelen)
 * @param {number} phase phase (how much it is shifted)
 * @param {number} res resolution (higher means more points)
 * @param {number} fillspace vertical bar at ever `fillspace` point
 * @param {object} atts attributes for the material
 * @return {THREE.Line} sine wave (threejs Line)
 */
function createWave(len, amp, freq, phase, res, fillspace, atts) {
    var waveGeom = new THREE.Geometry();

    for (var i = 0, fillmark = 0, posPts = len * res; i < posPts; i++) {
        var pos = new THREE.Vector3(
            i / (posPts - 1) * len,
            amp * Math.sin(i / (posPts - 1) * _TWO_PI * freq + phase),
            0
        );
        waveGeom.vertices.push(pos);

        fillmark--;

        if (fillmark <= 0) {
            var mid = new THREE.Vector3(pos.x, 0, 0);
            waveGeom.vertices.push(mid);
            waveGeom.vertices.push(pos);
            fillmark = fillspace;
        }
    }

    var waveMat = new THREE.LineBasicMaterial(atts);
    var line = new THREE.Line(waveGeom, waveMat);

    return line;
}
```

I am constantly calling `mesh.material.dispose();` and `mesh.geometry.dispose();` (every few render frames or so) for each of the waves, and then I remove each from the scene, recreate it with the above function and add it (back) to the scene. Am I doing something wrong? Is this a firefox issue?

I tried to shut up the warnings with the following (to no avail):

```javascript
var ctx = _renderer.context;
ctx.getShaderInfoLog = function () { return ""; };
```

I just ended up with the same empty warnings. Google Chrome spits out the info log once, but it does not continue to do it after that.

##### Three.js version
- r88

##### Browser
- [x] Firefox Quantum

##### OS
- [x] Windows (7)

**Comment by moraxy** [comment]
see #11138, also happens with Chrome
