### ISSUE TITLE
Blender export to Threejs.json  bug, objects has been rotated

### ISSUE THREAD

**Issue by gaoqi8985** [mrdoob/three.js#12806]
##### Description of the problem 

when i use blender to export my scene to threejs, all 
objects  looks like rotated in my website.
but when i change the code of
'utils/exporters/blender/addons/io_three/exporter/api/mesh.py'
from line 23 to 37 like this :
![oi8bR.png](https://s1.ax1x.com/2017/12/05/oi8bR.png)
everything is ok!

but why? and how to fixed ?

before I change the code:
![oiZEq.png](https://s1.ax1x.com/2017/12/05/oiZEq.png)
after I change the code:
![oit56.png](https://s1.ax1x.com/2017/12/05/oit56.png)
##### Three.js version

- [ ] Dev
- [x] r88
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by douglasppaz** [comment]
@gaoqi8985 You export cameras too? Or just the objects?
If you rotate the camera, you can take the same result.

flip_axes's code commented isn't good solution. I created this pull request #12784 with a possible solution to our problems.

**Comment by gaoqi8985** [comment]
@douglasppaz 
if you look the picture more careful, you will find  that we  can not take the same result by rotate camera,
in the picture 1, It is one face to three model, in the picture 2, it is three model face to one, and I can tell you ,the model in picture 1 , the  model is look at a little upper, and in picture 2  ,they look at a little down,
It looks like every model rotated by it's  self center,  or mirrored 2 axis  by it self center. 
Could you catch up with me ? my English is poor.

**Comment by muhammedmaruf** [comment]
if dir == XZ_Y:
        a = (a[0], a[2], -a[1])
    elif dir == X_ZY:
        a = (a[0], -a[2], a[1])
    elif dir == _XY_Z:
        **a = (a[0], a[1], a[2])**

When I removed the X and Y negative values, I saw that the problem was solved.
But I do not know if it will cause another problem.

**Comment by Mugen87** [comment]
Hey guys. Please note https://github.com/mrdoob/three.js/pull/14117

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
