### ISSUE TITLE
WebGL 2 support

### ISSUE THREAD

**Issue by wdanilo** [mrdoob/three.js#12802]
Hi! 
I would like to ask what is the status of WebGL2 in Three.js and if there is any concrete roadmap / timeline for implementing its support? 

I've read all the related threads, including https://github.com/mrdoob/three.js/issues/9965, however, it seems that this is a very long journey and it's not clear when and if we will arrive there. Are there any concrete plans to support WebGL2Renderer and WebGLMultiRenderTarget in near future? Can I right now somehow use multiple render targets or other 2.0 features in current Three.js (event developer version)? Thank you so much for improving this great framework! :)

**Comment by mrdoob** [comment]
#9965
