### ISSUE TITLE
FBX Loader : Biped animation

### ISSUE THREAD

**Issue by vinco90** [mrdoob/three.js#12814]
##### Description of the problem 

This form is for three.js bug reports and feature requests only.  
This is NOT a help site. Do not ask help questions here.  
If you need help, please use [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.  
A code snippet, screenshot, and small-test help us understand.

You can edit for small-test.  
http://jsfiddle.net/akmcv7Lh/ (current revision)  
http://jsfiddle.net/hw9rcLL8/ (dev)

##### Three.js version

- [x] Dev
- [ ] r88
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [x] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

I have some questions about biped animations.
My biped animations are different from Autodesk FBX Review.
Biped animations parsed properly?
If your answer is yes, any options I should consider when exporting biped animations?

This is my fbx file. [space - (5).FBX.zip](https://github.com/mrdoob/three.js/files/1534325/space.-.5.FBX.zip)
I don't have max file now.

**Comment by looeee** [comment]
Confirmed it's not working correctly - the bones in the arms seem to be rotated 180 degrees. I'll take a look.

**Comment by vinco90** [comment]
I find max file [Astronaut2.max.zip](https://github.com/mrdoob/three.js/files/1534549/Astronaut2.max.zip)

**Comment by looeee** [comment]
This is now fixed: #12829

**Comment by vinco90** [comment]
Oh, Thank you.
