### ISSUE TITLE
Raytracing example doesn't complete properly when using more than 3 Web Workers

### ISSUE THREAD

**Issue by wyckster** [mrdoob/three.js#12813]
##### Description of the problem 

The [raytracing sandbox example](https://threejs.org/examples/raytracing_sandbox.html) doesn't complete correctly if you add webworkers beyond the default of 3.

##### Steps to reproduce:

1. Browse to https://threejs.org/examples/raytracing_sandbox.html
2. Click Render, wait for it to complete.
3. Click + to add a webworker  (changes from 3 to 4)
4. Click Render, wait for it to complete.

It leaves one square incomplete.

If you perform the above steps but add more of web workers. (like change from 3 to 25)  then it will leave 22 squares incomplete (25 - 3 = 22).

Example with 5 workers leaving 2 squares unfinished.  (5 - 3 = 2)
![incomplete-5](https://user-images.githubusercontent.com/6098274/33625835-e50b2e66-d9c6-11e7-87ba-e5d381d01f54.png)

Example with 25 workers leaving 22 squares unfinished.  (25 - 3 = 22)
![incomplete-25](https://user-images.githubusercontent.com/6098274/33625836-e7bc5b80-d9c6-11e7-9a22-adba67f5418a.png)

##### Three.js version

- [x] r88

##### Browser

- [x] Chrome

Google Chrome | 62.0.3202.94 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | `4fd852a98d66564c88736c017b0a0b0478e885ad-refs/branch-heads/3202@{#789}`
OS | Windows
JavaScript | V8 6.2.414.42

##### OS

- [x] Windows

**Comment by mrdoob** [comment]
Interesting. Seems you're very close to find where the bug is. Any guesses?

**Comment by wyckster** [comment]
I would guess that in RaytracingRenderer.js, `init` is only called when you call `updateSettings`, and `updateSettings` is only called when the constructor calls `setSize`.  When you add a new worker (clicking the '+') and it so happens that `renderering` is false, then it does not call `updateSettings` on the newly added worker.

Then in the RaytracingWorker.js, because `init` was never called for this worker, the worker does not have a `loader` and it gets an exception trying to execute `loader.parse( data.scene )` because `loader` is undefined, which ultimately causes it not to execute `sceneId = data.sceneId`, which prevents it from being included in the completion count.

But that's just a guess.  ;)

**Comment by mrdoob** [comment]
> But that's just a guess. ;)

Do you want to test it? ;)

**Comment by wolfgangvonludwigsburg** [comment]
Solution: unchain dependency "renderering"
=========

in three.js-r89dev\examples\js\renderers\RaytracingRenderer.js,
lines around 80-85

change

			updateSettings( worker );

			if ( renderering ) {

				worker.postMessage( {
                                ...

to

			if ( renderering ) {

				updateSettings( worker );

				worker.postMessage( {
                                ...


I've put together a test case, and wondered,
why newly (from gui) demanded workers got no "init" (="initialize") directives,
thus working with the default set blocksize "var BLOCK = 128;" ...

Reason: The emission of the "init"-directive for a new worker in THREE.RaytracingRenderer.setWorkers()
depends on boolean var "renderering", which defaults to false, thus prevents the "init" directive.

MfG, WvL

**Comment by mrdoob** [comment]
I see. Anyone up for doing a PR with the fix?

**Comment by wolfgangvonludwigsburg** [comment]
@mrdoob
At the moment, I'm not experienced enough with "githubbing" PRs (I just started).

I would like to support three.js with some little cash amount,
how could I transfer ... ?

**Comment by mrdoob** [comment]
Better to spend that money on a githubbing course 😉

**Comment by wolfgangvonludwigsburg** [comment]
Dear Mr.Doob,

please be careful by accepting my unskilled stumbled-together PR ...
- it's been my first serious PR action on github ... ;-)

I saved the course expenditure in favour we need some money for any future occasions ... ?
