### ISSUE TITLE
Documentation error in Mesh material property

### ISSUE THREAD

**Issue by ir-fuel** [mrdoob/three.js#12810]
##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

The documentation of the `Mesh` class states:

.material

An instance of material derived from the Material base class, defining the object's appearance. Default is a MeshBasicMaterial with a random colour.

But I just saw in my Collada loader that the `material` property contains an array.

**Comment by Mugen87** [comment]
Yes, `.material` might represent an array of material objects. Looks like the documentation is not 100% precise in this context.

**Comment by Mugen87** [comment]
see d381e6cca05878a784fa509c5846f3aebc003e95
