### ISSUE TITLE
Size of SphereGeometry changes depending on number of Segments

### ISSUE THREAD

**Issue by vin-ni** [mrdoob/three.js#12812]
##### Description of the problem 

I was calculating the relative size of a SphereGeometry, when I noticed a slight growth in size when augmenting the number of Segments. Is this a bug or a feature?

![size](https://user-images.githubusercontent.com/9806572/33621675-d985018c-d9eb-11e7-99b1-ad93f2c35eb7.jpg)

##### Three.js version
- [x] r88

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
None

**Comment by WestLangley** [comment]
SO post: https://stackoverflow.com/questions/47656641/three-js-calculate-relative-size-on-screen-through-camera
