### ISSUE TITLE
FBX exporter

### ISSUE THREAD

**Issue by CorentinLemaitre** [mrdoob/three.js#12815]
Hello,
I have seen that there is a fbx - three.js link but only in one way. Use a fbx to produce a three.js .
Is it possible to build a fbx exporter ? (it is a proposal)

**Comment by looeee** [comment]
Currently you could use the GLTFExporter and then convert to FBX (perhaps via SketchFab).

**Comment by donmccurdy** [comment]
GLTFExporter is probably a good place to start, or OBJExporter is easier to import and convert in other tools but doesn't support lights, animation, PBR, etc.

Some options for converting glTF to other formats are the [unofficial Blender importer](https://github.com/ksons/gltf-blender-importer) or [aspose](https://www.aspose.com/). We're working on more tools for that.
