### ISSUE TITLE
three.js partly broken with Safari 11.0.2 on macOS 10.13.2

### ISSUE THREAD

**Issue by MagnuzBinder** [mrdoob/three.js#12825]
##### Description of the problem 

three.min.js r88 stopped rendering the canvas for some of my work with the update from macOS 10.13.1 and Safari 11.0.1 to macOS 10.13.2 and Safari 11.0.2 on iMac 14.2. RayCaster, or at least its methods setFromCamera and intersectsObjects, still works. Everything worked with macOS 10.13.1 and Safari 11.0.1. It still works with macOS 10.13.2 and Mozilla Firefox 57.0.1. My partly corresponding raw WebGL work still works with macOS 10.13.2 and Safari 11.0.2. I also re-tested my work with macOS 10.13.1 and Safari 11.0.1 on MacBook Pro 15"/2012 with NVIDIA GeForce GT 650M, and all works there.

three.js has always thrown the warning below but still worked OK, so I don't know if it can be related. No other errors or warnings reported.
[Warning] THREE.WebGLShader: gl.getShaderInfoLog() (3) (three.min.js, line 77)
"fragment"
"WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
"
+ a 1001 line dump

I checked some of the examples on the three.js website, and some render the canvas, others not:
OK: https://threejs.org/examples/#webgl_animation_cloth
No: https://threejs.org/examples/#webgl_animation_keyframes_json
No: https://threejs.org/examples/#webgl_animation_scene
No: https://threejs.org/examples/#webgl_animation_skinning_blending
No: https://threejs.org/examples/#webgl_animation_skinning_morph
OK: https://threejs.org/examples/#webgl_camera
OK: https://threejs.org/examples/#webgl_camera_array

##### Three.js version

- [ ] Dev
- [x] r88
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
iMac 14.2 (Intel Core i7, 3,5 GHz, 16 GB, Boot ROM IM142.0123.B00)
GPU: NVIDIA GeForce GTX 780M, ROM 3782

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/12598#issuecomment-345866082

The mentioned warning (`WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported`) is not related to the problem.

**Comment by MagnuzBinder** [comment]
Rendering with three.min.js r88 works on macOS 10.13.2 / Safari 11.0.2 if renderer.alpha = true, but opacity is ignored, i.e. materials with transparent = true and opacity < 1 are rendered as opacity = 1. This works as expected on macOS 10.13.1 / Safari 11.0.1, macOS 10.13.2 / Mozilla Firefox 57.0.1, and iOS / Safari 10.3.3, regardless of renderer.alpha. So, setting renderer.alpha = true at least partly mitigates the problem.

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/12598#issuecomment-349998680

This issue is actually a duplicate.
