### ISSUE TITLE
fossa.io thinks material.js is GPL-3.0 and fails

### ISSUE THREAD

**Issue by edsilv** [mrdoob/three.js#12826]
We have fossa.io set up for our project and it's failing because it thinks Material.js is GPL-3.0. Not sure why..?

https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js

v0.87.1

**Comment by edsilv** [comment]
Possibly a fossa issue, not a three.js one :-)

**Comment by looeee** [comment]
Have you raised it with them?

**Comment by edsilv** [comment]
Not sure where the best place to do that would be - they have many repos. Maybe twitter?

**Comment by edsilv** [comment]
https://twitter.com/edsilv/status/938775921200386048

**Comment by Mugen87** [comment]
I don't think this issue is related to `three.js`. You should contact the [support](support@fossa.io).

**Comment by cjcross** [comment]
You're correct. Just looked into this and it seems that FOSSA was flagging some code in src/materials/Material.js as a potential GPL-3.0 reference. After reviewing the match data it's clear that there's no actual GPL there. In such cases, you can just ignore the match in FOSSA.
