### ISSUE TITLE
Set skeleton bone's rotation in world coordinates

### ISSUE THREAD

**Issue by Rishanthakumar** [mrdoob/three.js#12827]
##### Description of the problem 

Hi, I am trying to set the rotation of the skeleton bone using quaternion in world coordinates. Is there any way where i can directly apply to the skeleton bone and make the rotation in world coordinates (not local coordinates of the bone).

##### Three.js version

- [ ] Dev
- [x] r88

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
https://discourse.threejs.org/t/how-to-set-child-object-rotation-using-quaternion-in-world-coordinates-using-threejs/1357
