### ISSUE TITLE
Gear VR Oculus browser stuck at loading screen after Enter VR

### ISSUE THREAD

**Issue by Ben-Mack** [mrdoob/three.js#12822]
`webvr_cubes` example works fine, but I can't get my own implement working, please see this fiddle: https://jsfiddle.net/cq2xt3ww/1/

After hit `Enter VR`, the browser just display the loading screen of Oculus browser ( black background with an white spinning icon ), cannot get into the 3D scene (This loading screen alway appear after hit `Enter VR`, but normally just under 1 second then it'll disappear and display 3D scene)

Samsung Internet Browser working fine, this problem only occurs on Oculus browser.

I'm using Samsung S7 Edge, Gear VR 2015, Default Oculus Internet browser.

**Comment by Ben-Mack** [comment]
I figured it out, so I have to replace 
`requestAnimationFrame( animate );` 
to 
`renderer.animate( render );` 
then it working good now.

**Comment by mrdoob** [comment]
🎉

**Comment by otaviojacobi** [comment]
What needs to be done to run three.js with VR ?
- Include the [WebVRPolyfill](https://github.com/googlevr/webvr-polyfill) package into your project.
- Include the [WEBVR class](https://github.com/mrdoob/three.js/blob/dev/examples/js/vr/WebVR.js) class into your project.
- In three.js set your ```render.vr.enabled = true;```
- Disable all your other controls (such as OrbitControl.js, TrackbarControl.js ...)
- Create/set the ```vr-button``` from the WEBVR class as the exemple below:
```javascript
import 'three/examples/js/vr/WebVR';

let vrButton = document.getElementById('vr-button');
if (!vrButton) {
    vrButton = WEBVR.createButton(glRenderer);
    vrButton.id = 'vr-button';
    vrButton.style.color = '#000';
    vrButton.style.borderColor = '#000';
    vrButton.style.backgroundColor = 'white';
    vrButton.style.opacity = 1;
    document.body.appendChild(vrButton);
}
```

- If you're using ```requestAnimationFrame( animate );``` change it to ```render.animate( render );```
