### ISSUE TITLE
Impossible to set render gamma value.

### ISSUE THREAD

**Issue by wdanilo** [mrdoob/three.js#12831]
##### Description of the problem 

Hi!
I'm trying to blend colors in Three.js, however it seems that Three.js does some gamma processing that I cannot disable or change. According to documentation, I should be able to tell:

```
renderer = new THREE.WebGLRenderer({
    antialias: true
    gammaInput  = false
    gammaOutput = false
    gammaFactor = 1.0
});
```
However, changing these settings does not affect the final image at all. I've created a sample scene in shadertoy here: https://www.shadertoy.com/view/4tsfzf . Note that the shader converts the colorspace from linear to sRGB explicitely. The results I've got are as follow:

![1](https://user-images.githubusercontent.com/1623053/33766641-c0b47e1e-dc1e-11e7-93be-f6a64082a128.png)

Starting from the left to right side:
* Running the shader in Three.js with explicit conversion from linear to sRGB space
* Running the shader in Three.js without the conversion
* Running the shader in shadertoy with explicit conversion from linear to sRGB space (and this is the correct way it should look like).

Changing the parameters described above does not affect how it looks like. It seems to me that it is a bug, because I cannot disable some gamma setting that Three.js is applying. It could be something else, but this is my strongest bet here.

I would be thankful for any help / workaround. I've been reading other threads, like https://github.com/mrdoob/three.js/issues/11110 and tested other options (mentioned to be introduced in the future, but without any success).

Thanks! :)

##### Three.js version

- [ ] Dev
- [x] r88
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
You posted code seems to be wrong. It should be:
```javascript
var renderer = new THREE.WebGLRenderer( { antialias: true } );
renderer. gammaFactor = true;
renderer. gammaFactor = true;

```

**Comment by Mugen87** [comment]
see https://threejs.org/docs/index.html#api/renderers/WebGLRenderer

**Comment by wdanilo** [comment]
@Mugen87 Actually I was trying both versions, but neither changes anything - setting it here or there makes completely no effect and I get exactly the same results :(

**Comment by WestLangley** [comment]
`renderer.gammaFactor` is not intended to be changed.

Changing `renderer.gammaInput` or `renderer.gammaOutput`  requires setting
```
material.needsUpdate = true;
```

Please use the forum if you need further help.

**Comment by wdanilo** [comment]
@WestLangley Thank you, however I actually think this might still be a bug:
1. If I'm not able to remove the gamma automatically added by Three.js, I cannot add custom gamma in shaders / post processing. So far, it seems there is no such option, because as you told, we cannot change `renderer.gammaOutput`. 
2. I'm setting `gammaInput` and `gammaOutput` before rendering a single frame, so `material.needsUpdate` sohuldn't be needed. Even if I set it, still there is no effect.

Doesn't sound it like a bug to you?

**Comment by WestLangley** [comment]
You have not demonstrated a three.js bug. You need to provide code or a live link to do that.

FYI, the docs are incorrect. `gammaInput` only applies to certain textures -- not input colors. Colors are assumed to be in linear space and are not changed on input.

**Comment by Bug-Reaper** [comment]
> `renderer.gammaFactor` is not intended to be changed.
> 
> Changing `renderer.gammaInput` or `renderer.gammaOutput` requires setting
> 
> ```
> material.needsUpdate = true;
> ```
> 
> Please use the forum if you need further help.

God thanks so much! I’ll add this to docs @WestLangley
