### ISSUE TITLE
R88 Visible Property Not Working for Child Nodes

### ISSUE THREAD

**Issue by rankinstudio** [mrdoob/three.js#12842]
##### Description of the problem 

This code: 

`someObject.children[0].children[0].visible = 0;`

Will turn the visibility of the objects child node off just fine in R85

In R88, it switches the value to 0, but the child node is still visible in the scene.

Not sure if this is a bug or if I'm just missing something here.

Cheers

- [ ] Dev
- [ x] r88
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Set `visible` to `false`, not zero.

**Comment by rankinstudio** [comment]
Setting it to false just changes the visible value to 0, so changing it to 0 works fine.

No difference, still doesn't make the object go invisible.

**Comment by rankinstudio** [comment]
Strange, in R85 you could set it to 0. False worked. Thanks

**Comment by rankinstudio** [comment]
Strange, in R85 you could set it to 0. False worked. Thanks
