### ISSUE TITLE
Get 3D spatial coordinates

### ISSUE THREAD

**Issue by shsm385** [mrdoob/three.js#12841]
In development I would like to take 3D spatial coordinates.
By using intersects.length with THREE.Raycaster () you can get the mouse coordinates of the 3D object.

However, from the coordinates of the mouse, I want to obtain the spatial coordinates without objects in 3D space.

Therefore, we need a function to convert the position of the mouse pointer on the screen to the coordinates in 3D space.

**Comment by WestLangley** [comment]
See, for example, [this SO answer](https://stackoverflow.com/questions/13055214/mouse-canvas-x-y-to-three-js-world-x-y-z/13091694#13091694).
