### ISSUE TITLE
DirectGeometry.fromGeometry with no faces gives empty position array while converting to BufferGeometry

### ISSUE THREAD

**Issue by mamun4122** [mrdoob/three.js#12853]
I was trying to create `BufferGeometry()` from `Geometry()` which was created using VRML loader. But the problem is that when the geometry has only vertices without faces it returns empty position array. After analysis i found that the bug occurs because of in `DirectGeometry.fromGeometry` function vertices is not updated if there is no faces: [Link](https://github.com/mrdoob/three.js/blob/dev/src/core/DirectGeometry.js#L144)

##### Three.js version

- [ ] Dev
- [ ] r88
- [x] r86

**Comment by Mugen87** [comment]
The latest `VRMLLoader` automatically creates `BufferGeometry`. So there is no need for a conversion.

`DirectGeometry.fromGeometry()` assumes faces in the geometry.  I'm not sure it's necessary to change this assumption. Line geometries are not supported but this was no feature request so far...

**Comment by mamun4122** [comment]
I have tried with the latest `VRMLLoader` & in the `BufferGeometry` it is still giving empty position array for that `mesh`.  But the model loads properly in the `scene`.
