### ISSUE TITLE
[suggestion] replace the EventDispatcher with EventEmitter

### ISSUE THREAD

**Issue by jcyuan** [mrdoob/three.js#12854]
the current one is really hard to use, and `dispatchEvent(evt)` must be an object which takes a bit mem I prefer to use string instead.
and other handy methods like `on/off/once` and context binder for `on` method [`on(type, fn, context)`] etc (I'm using Typescript so this one is really useful to me).
please, just use EventEmitter as the default dispatcher, it's really convenient, or add a new argument `context` for `addEventListener` method.
EventEmitter3: 
https://github.com/primus/eventemitter3

**Comment by mrdoob** [comment]
The idea of EventDispatcher is to provide the same javascript API available for dom elements. Because of this, we'll "soon" be able to remove all this code: https://twitter.com/mrdoob/status/931176663139811330

**Comment by Mugen87** [comment]
> EventTarget is constructable & extendable in Chrome Canary!
Wow! :flushed:

**Comment by jcyuan** [comment]
But the current one is not convenient to use.
I don't care whether EventTarget can be extended or not. I just want to manage my event handler easier, say add them with context binding / remove it easily without extra class member assigned.

For example in TS (I'm using TS):
`
class A extends THREE.Object3D {
     public constructor(){  super(); this.init(); }
     public init() {
             this.addEventListener("event", this.handler);   //how to bind this context?
             //this.addEventListener("event" () => {});    //in this one the handler is bound with context but how to remove this event?? to remove it I have to do this:
     //private _handler:Function;
             //this._handler = () => {  this.handlerMethod();  };
             //this.removeEventListener("event", this._handler);
             //this._handler = null;
     }
}
`

Actually It's easy to improve:
1, use EventEmitter
2, modify addEventListener as addEventListener(event, handler, contextScope);

@mrdoob @Mugen87 

what do you guys think?

**Comment by mrdoob** [comment]
Sounds like you have a workaround that works for you?

**Comment by Mugen87** [comment]
I vote for keeping the implementation of `EventDispatcher` simple and similar to the DOM API. In this way, it will be easier to move to a standard solution in the future.

I also think that it's not hard for users to extend the default behavior, if necessary.

**Comment by jcyuan** [comment]
@mrdoob yes, this subject is just a suggestion that to improve the API usage more convenient for endusers.
