### ISSUE TITLE
Add an object to the scene and immediately call raycaster.intersectObject(object, true) return incorrect result

### ISSUE THREAD

**Issue by wangfan008** [mrdoob/three.js#12864]
##### Description of the problem 

Hi,
I'm doing some development with raycaster.I find that It  goes wrong when the mesh is created and immediately detect, 

    var scene = new THREE.Scene();

    // camera
    var camera = new THREE.PerspectiveCamera( 45, window.innerWidth / window.innerHeight, 1, 1000 );
    camera.position.set( 0, - 450, 400 );
    camera.rotation.x = 45 * ( Math.PI / 180 );
    scene.add( camera );

    // plane
    var geometry = new THREE.PlaneGeometry( 300, 300 );
    var material = new THREE.MeshBasicMaterial( { color: 0x0000ff } );
    var mesh = new THREE.Mesh( geometry, material );
    scene.add( mesh );

    // renderer
    var renderer = new THREE.WebGLRenderer();
    renderer.setSize( window.innerWidth, window.innerHeight );
    document.body.appendChild( renderer.domElement );
    this.pointer = new THREE.Vector2(2, 2);
    this.raycaster = new THREE.Raycaster();
    this.pointer.x =-1;
    this.pointer.y =-1;
    this.raycaster.setFromCamera(this.pointer, camera);
    var intersects = this.raycaster.intersectObject(mesh, true);
    if(intersects.length > 0){
          console.log('has` intersects');
    }
In my understanding,the intersects should be an empty array,but the result is not.Is that a bug? Or something I have not realized?
You can edit for small-test.  
http://jsfiddle.net/wangfan008/m42s2cuz

##### Three.js version

- [✔️] r83

##### Browser
- [ ✔️] Chrome

##### OS
- [✔️] macOS

**Comment by mrdoob** [comment]
Could you change the title of the issue to something more descriptive?

**Comment by wangfan008** [comment]
@mrdoob I am very sorry that my English is not good enough. Now can you see what I mean?

**Comment by WestLangley** [comment]
The renderer updates `object.Matrix` and `object.MatrixWorld` for you by default. But since you are raycasting prior to rendering, you need update the matrix transforms manually. For example:
```javascript
camera.position.set( 0, - 450, 400 );
camera.rotation.x = 45 * ( Math.PI / 180 );
scene.add( camera );
camera.updateMatrixWorld();
```
