### ISSUE TITLE
Varying performance from raycast onto planeBuffer

### ISSUE THREAD

**Issue by kpetrow** [mrdoob/three.js#12869]
I am trying to find the closest distance from a point to planeBuffer Geometry along a plane in a direction range:

```
 for (var zDown in verticalDistances) {
    var myIntersect = {};  
   for (var theta = Math.PI / 2 - 0.5; theta < Math.PI / 2 + 0.5; theta += 0.3) {
                var rayDirection = new THREE.Vector3(
                    Math.cos(theta),
                    Math.sin(theta),
                    0
                ).transformDirection(object.matrixWorld);
                 //  console.log(rayDirection);

                _raycaster.set(verticalDistances[zDown].minFacePoint, rayDirection, 0, 50);
                //  console.time('raycast: ');
                var intersect = _raycaster.intersectObject(planeBufferMesh);
                //   console.timeEnd('raycast: '); // this is huge!!! ~ 2,300 ms
               
                //   console.log(_raycaster);
                //    console.log(intersect);
                if (intersect.length == 0) continue;
                if ((!('distance' in myIntersect)) || myIntersect.distance > intersect[0].distance) {
                    myIntersect.distance = intersect[0].distance;
                    myIntersect.point = intersect[0].point.clone();
                }
            }
// do stuff
}
```

I get great results with mouse hover on the same surface but when performing this loop the raycasting is taking over 2 seconds per cast.  The only thing i can think of is that the BackSide of the DoubleSide Material is a ton slower?  Also i notice as I space out my verticalDistances[zDown].minFacePoint to be farther apart raycast starts to speed up up (500ms /cast).  So as the distance between  verticalDistances[i].minFacePoint and  verticalDistances[i+1].minFacePoint  increases, the raycaster performs faster.

I would go the route of using octree but the mouse hover event works extremely well on the exact same planeBuffer.  Is this a side of Material issue,. that could be solved by loading 2 FrontSide meshes pointing in opposite directions?

Thank You!!!!

##### Three.js version

- [ ] Dev
- [ x] r84
- [ ] ...

##### Browser

- [??] All of them
- [X ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [??] All of them
- [ X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by kpetrow** [comment]
I have tried reversing the surface and it is still giving bad results.  This will rule out the /Front/Back/Double side theory.

**Comment by pailhead** [comment]
Any chance you can post some live code? It's always a good idea to profile it, see what's going on.
