### ISSUE TITLE
Fail to visualize a mesh

### ISSUE THREAD

**Issue by jihoonl** [mrdoob/three.js#12873]
Hello, 

I am failing to visualize [this dae](https://github.com/PR2/pr2_common/blob/kinetic-devel/pr2_description/meshes/base_v0/base.dae). Could you help me on this?

I have checked that it visualizes the model when I override the material. So, I think it mishandles its material loaded from dae file. It should look like the image below.

![base](https://user-images.githubusercontent.com/1556736/33933393-d81e0bee-dff5-11e7-9605-e4a072e781dc.png)

Thanks!

##### Three.js version

- [x] Dev
- [x] r88
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by kpetrow** [comment]
Can you provide any details?  It looks like it is using multiple materials have you tried to isolate the offending material?

**Comment by Mugen87** [comment]
I'm not yet sure what goes wrong but i looks like the loader has a problem with transparency information. You should also able to see your model if you set `material.transparent` to `false` instead of overwriting it.

**Comment by Mugen87** [comment]
Your model tries to load `tif` textures. I don't think this is supported, see https://github.com/mrdoob/three.js/issues/436#issuecomment-1825872

**Comment by jihoonl** [comment]
Ok. I confirmed it works after converting `tif` to `png`. Thanks!.
