### ISSUE TITLE
Enhancement: allow Sprite to pivot at anywhere of the texture

### ISSUE THREAD

**Issue by sgaoae** [mrdoob/three.js#12878]
##### Description of the problem 

Currently, Sprite's pivot at the center of the texture. It could allow itself to pivot at anywhere of the texture. 
I suggest that it can be used in this way:
```javascript
sprite.pivot = new Vector2(0.5, 0.5) // 50%, 50% pivot at center
sprite.pivot = new Vector2(0.5, 1) // 50%, 100% pivot at center bottom
sprite.pivot = new Vector2(1, 1) // 100%, 100% pivot at right down corner
```
I have found the corresonding StackOverflow question but the first answer seems to be a little difficult. Maybe the last answer will be helpful for implementing this enhancement. 
That answer changes the vertices array. 
the StackOverflow question link: https://stackoverflow.com/questions/24757325/three-js-change-the-pivot-point-of-a-sprite

##### Three.js version

- [x] r86
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Even if one is not rotating the sprite, being able to offset the sprite's `origin/anchor/pivot/offset` would be a nice feature when implementing text labels.

This can be hacked by modifying `WebGLSpriteRenderer.js` like so:
```glsl
// vec2 alignedPosition = position * scale;
vec2 alignedPosition = ( position + vec2( 0.5, - 0.5 ) ) * scale; // pivot lower left
```

I will implement something like this if there is interest.

**Comment by sgaoae** [comment]
Well, I think there should be interests for a big WebGL project utilizing THREE.JS as text labels are always used to make the 3D scene more understandable. So please implement this at your convenience. 
And thank you very much for your suggestions, it works for me. @WestLangley

**Comment by kpetrow** [comment]
Its sort of hacky but cant you increase the size of the canvas to change the pivot point?  If you want it to be around the right side of your label just make your canvas twice as large and utilize the left side of the canvas or vice versa?

**Comment by sgaoae** [comment]
@kpetrow Yes, I have tried that way and temporarily solve the problem I faced before I post this issue. But it will be much convenient for me to implement my desired effects if changing the pivot is supported as there will be no need to deal with the unused part of the canvas.

**Comment by WestLangley** [comment]
>Currently, Sprite's pivot at the center of the texture.

@sgaoae I think what you mean to say is: "Currently, a sprite's pivot is at the center of the _sprite_.", and you would like to be able to rotate the sprite around a point different from the sprite's  _center_.

This has nothing to do with the sprite's texture.

**Comment by sgaoae** [comment]
@WestLangley Yes, sorry for my inappropriate description and you understand what I mean. 
Thank you very much for your work.

**Comment by vidartf** [comment]
Was this closed by #12931?

**Comment by WestLangley** [comment]
Yes. Closing...

**Comment by ajaykjangid** [comment]
Hi @WestLangley 

How can I change pivot of CSS3DSprite.

Thanks

**Comment by Mugen87** [comment]
`CSS3DSprite` has nothing to do with `Sprite`.

You should be able to change the pivot of an image used in a `CSS3DSprite` element via the CSS property [transform-origin](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin).

**Comment by ajaykjangid** [comment]
Thanks @Mugen87
