### ISSUE TITLE
Feature Request: edit renderOrder in the editor

### ISSUE THREAD

**Issue by mhirsch** [mrdoob/three.js#12884]
##### Description of the problem 

It would be awesome if you could add a `renderOrder` property to a `Mesh` in a `scene.json`, and when loaded in the editor (r88) it would set the render order for the Mesh object. It would be even more awesome to have a way to set the `renderOrder` in the OBJECT tab in the SCENE tab in the editor! 

##### Three.js version

- [ ] Dev
- [x] r88
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by rajvicky** [comment]
how to enter editor
