### ISSUE TITLE
Reintroduce ColladaLoader convertUpAxis option

### ISSUE THREAD

**Issue by T045T** [mrdoob/three.js#12888]
##### Description of the problem 

Would you consider adding the convertUpAxis option back in? If it defaults to ```true```, that wouldn't change any behavior, but we do have a use case at https://github.com/RobotWebTools/ros3djs where we need to be compatible with a system that ignores the up axis (and is unlikely to change soon, because that would break quite a few things).

Now, we could fork ColladaLoader (for now, that's what we're planning to do), but of course it would be nicer to just use the current version

##### Three.js version

- [x] Dev
- [x] r88

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by mrdoob** [comment]
See #11540

**Comment by Mugen87** [comment]
The loader relies on the value in the `<up_axis>` tag of a Collada file. If it detects `Z_UP` in rotates the scene (in some sense it performs a "conversion"). 

@T045T So your `dae` files don't set the `<up_axis>` in the correct way? If so, i tend to leave the loader as it is since it works strictly according to the standard.

**Comment by T045T** [comment]
@Mugen87 Yeah, some of them don't. They're not exactly *my* or *our* ```dae``` files, they're provided by ROS packages (like [baxter_description](https://github.com/RethinkRobotics/baxter_common/tree/master/baxter_description)). 

Now of course it would be preferable to fix the ```dae``` files (I've already created a number of PRs to do just that), but not all of these types of packages are public, and people expect meshes that load "correctly" in [RViz](https://github.com/ros-visualization/rviz) to work with [ros3djs](https://github.com/RobotWebTools/ros3djs) without modification. Or they don't use ```ros3djs```at all, and have no incentive to change their models, since RViz [does not read the up_axis value](https://github.com/ros-visualization/rviz/issues/1045).

Older versions of ```ColladaLoader(2)``` had an option called ```convertUpAxis``` - I'm not sure it ever actually did anything, but I imagine it would have disabled [this if statement](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/ColladaLoader.js#L3465).

I understand wanting to follow the standard correctly, but I'd also appreciate not having to fork ```ColladaLoader```. It's not a big deal either way, to be honest, but I thought it was worth asking.

**Comment by Mugen87** [comment]
Let's see what @mrdoob thinks about that...

**Comment by Mugen87** [comment]
This won't be fixed, sry. You need to enhance `ColladaLoader` by yourself.

**Comment by mrdoob** [comment]
Workaround:

```js
new THREE.FileLoader().load( 'file.dae', function ( text ) {

    text = text.replace( '<up_axis>Z_UP</up_axis>', '<up_axis>Y_UP</up_axis>' );

    var collada = new THREE.ColladaLoader().parse( text );
    scene.add( collada.scene );

} );
```
