### ISSUE TITLE
Typescripts for materials are wrong

### ISSUE THREAD

**Issue by pbrink231** [mrdoob/three.js#12892]
##### Description of the problem 

Hello,
I dont know if this is the right area because I am new to a lot of this.  I would gladly help if you can direct me in the right direction.

I am using Angular 5, I downloaded the latest npm releases today.
npm install @types/three --save
npm install three --save
npm install --save three-obj-loader

My code is just the object loader section that is giving the problem.  The code runs fine but typescript is giving an error.  I pulled this from the example for loading .obj file
```
      // load .obj model
      // my object - 'assets/objects/objtest.obj'
      // three js man - 'https://threejs.org/examples/obj/male02/male02.obj'
      var Objloader = new THREE.OBJLoader( manager );
      Objloader.load( 'assets/objects/objtest.obj', function ( object ) {
        // traverse through complete object structure
        object.traverse( function ( child ) {
          // can apply texture? Mesh -> yes
          if ( child instanceof THREE.Mesh ) {
            // use child.name to identify Mesh by name given
            // when .obj was exported so you can
            // colorize / change texture only on 
            // specific parts of the object
            console.log('child', child);
            child.material.map = texture;  <--- HERE
            
            if (child.name === 'dach') {
             // color mesh in red
              var color = new THREE.Color("rgb(255, 0, 0)");
              child.material.color.set(color);  <--- HERE
            }
          }
        });
```

The error has to do with the `child.material.color` & `child.material.map`
```
ERROR in src/app/layout/threed/threed.component.ts(176,28): error TS2339: Property 'map' does not exist on type 'Material | Material[]'.
  Property 'map' does not exist on type 'Material'.
src/app/layout/threed/threed.component.ts(181,30): error TS2339: Property 'color' does not exist on type 'Material | Material[]'.
  Property 'color' does not exist on type 'Material'.
```
##### Three.js version

- [ ] Dev
- [x] r88
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please have a look at https://github.com/mrdoob/three.js/issues/10681#issuecomment-287921860. Hope this will help you further.

**Comment by pbrink231** [comment]
Understand.  thank you

**Comment by lukerohanbailey** [comment]
Coming to this very late, by ran into the `Property 'color' does not exist on type 'Material | Material[]'.` issue today. In my case I had this

```
const sphereRef = useRef<Mesh>(null);
sphereRef.current?.material.color.set(color.current); // Error here
```

However if I pass in the generics TS is happy:

```
const sphereRef = useRef<Mesh<SphereGeometry, MeshBasicMaterial>>(null);
sphereRef.current?.material.color.set(color.current); // No error here
```

Hopefully this can help anyone else who runs into this little quirk!

**Comment by aidanmarler** [comment]
Okay I just ran into this issue and want to say I solved it also with declaring the material type - the error is just from strict typing held up by typescript. 

This here gave me an error on build and in vs code, despite running without an error in the dev server:
```
const meshMat = (this.mesh.children[0] as THREE.Mesh).material;
meshMat.color.copy(new THREE.Color(1, 1, 1));
```

It took me a while to figure out, but I just had to use the type and it worked great.
`const meshMat = (this.mesh.children[0] as THREE.Mesh).material as THREE.MeshBasicMaterial;`
