### ISSUE TITLE
OBJLoader2 loading a 404'd resource results in a bad stack trace unable to log the error indicating failure

### ISSUE THREAD

**Issue by unphased** [mrdoob/three.js#12900]
##### Description of the problem 

There are no implementations of the `logger.logInfo` routine, indeed nothing other than references (calls) for this token in the entire codebase.

##### Three.js version

- [x] r88
- [ ] Dev
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

Relevant stack

```
LoaderSupport.js:445 Uncaught TypeError: this.logger.logInfo is not a function
    at new Builder (LoaderSupport.js:445)
    at OBJLoader2.LoaderBase (LoaderSupport.js:748)
    at new OBJLoader2 (OBJLoader2.js:27)
```

Maybe some missing newer dependency code failed to make it into r88's js files? @kaisalmen

**Comment by unphased** [comment]
Actually i'm not sure why I didn't see it but ConsoleLogger does have `logInfo`. I'm not sure what is causing the `this` scope problem...

**Comment by unphased** [comment]
OK I had to `new` the `ConsoleLogger`.

Really it would be nicer if the OBJLoader2 example does this by default (use a new ConsoleLogger). Because it took me a long time to get it to stop giving a really bad stack trace when the resource path was bad...

**Comment by kaisalmen** [comment]
With the proper scope the issue is gone. Tested it with a not-existing resource and with the fix the "Uncaught TypeError" is gone and the error message is printed in the log.

**Comment by unphased** [comment]
Just to further nitpick....

The error looks like this: 

`Error occurred while downloading ".mtl": [object ProgressEvent]`

Could we maybe make `logError` take multiple args, or do something to make it print a useful field of the ProgressEvent in question? `[object x]` getting printed for me is pretty smelly.

**Comment by kaisalmen** [comment]
@unphased I opened https://github.com/kaisalmen/WWOBJLoader/issues/32
