### ISSUE TITLE
THREE.Loader: .extractUrlBase() has been deprecated. Use THREE.LoaderUtils.extractUrlBase() instead.

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#12909]
For most of the samples I get this console "warning".
In r89 only.
I'm not sure if this change is an improvement.

**Comment by Mugen87** [comment]
This PR #12654 introduces the change. I thought i've cleaned up all references to `Loader.prototype.extractUrlBase` with #12871.

**Comment by RemusMar** [comment]
Hi Michael,

> This PR #12654 introduces the change.
As I said before, I'm not sure if this change is an improvement.

> I thought i've cleaned up all references to Loader.prototype.extractUrlBase with #12871.
That SEA3D loader is outdated.

**Comment by Mugen87** [comment]
The [official examples](https://threejs.org/examples/?q=sea) don't show any warnings. As far as i can see, `SEA3DLoader` does not use `. extractUrlBase()` at all.

I was not sure about this change in the first place. But this https://github.com/mrdoob/three.js/pull/12654#issuecomment-349557593 convinced me 😊

**Comment by RemusMar** [comment]
> The official examples don't show any warnings. 

They are outdated

> As far as i can see, SEA3DLoader does not use .extractUrlBase() at all.

It's the SEA3D.js file.
Mine it's completely different.
For example, the "SEA3D.File.prototype.load" (line 3115 for you) for me looks like:

SEA3D.File.prototype.load = function ( url ) {
	var self = this,
		xhr = new XMLHttpRequest();
	xhr.open( "GET", url, true );
	if (!this.config.path) {
		this.config.path = THREE.Loader.prototype.extractUrlBase( url );
	}
	if ( self.config.progressive ) {
		var position = 0;
		xhr.overrideMimeType( 'text/plain; charset=x-user-defined' );
	} else {
		xhr.responseType = 'arraybuffer';
	}
	xhr.onprogress = function ( e ) {
		if ( self.config.progressive ) {


> I was not sure about this change in the first place. But this #12654 (comment) convinced me 😊

Ricardo has a good point, but still ...

**Comment by RemusMar** [comment]
I've updated all the SEA3D files for r89.
Here is the minified version in action:
http://necromanthus.com/Test/html5/testA_disco.html

**Comment by Mugen87** [comment]
Claire Redfield again 😍 😊

**Comment by RemusMar** [comment]
Fixed in the latest SEA3D update.
