### ISSUE TITLE
feature request: Disable self-shadowing for specific objects.

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#12919]
It would help hugely in shadow-acne cases where bias would otherwise introduce other unwanted effects, etc.

I'm not an expert in this area, but maybe this would involve generating an ID map from the main camera's perspective so each pixel contains an object ID, and also storing IDs in the shadow map (is vec4 enough for that for shadow map which I presume doesn't use alpha values?). Then we can compare ID map to IDs in the shadow map, and from this we can determine to not draw self-shadows on certain objects if they are hit by light. We'd skip this check on object that are fully shadowed by other objects.

This would also incur the extra overhead from rendering to yet another map. However, in small cases that aren't super graphically intense (f.e. rendering simple UIs with a few PlaneGeometries), it might not be noticeable, and therefore such a feature would be useful in, for example, preventing the peter panning like in the following pen, where the Sphere intersects with the Planes:

https://codepen.io/trusktr/pen/OzMGJK

**Comment by WestLangley** [comment]
This is way too general to be useful. If you have a concrete suggestion, you can open another issue.

**Comment by krikienoid** [comment]
I can definitely see this being useful as well, specifically for dealing with shadow acne.

What kind of info would you need to make a more concrete suggestion?
