### ISSUE TITLE
Object3d VS Geometry (drawing secenes without Object3d)

### ISSUE THREAD

**Issue by cyth319** [mrdoob/three.js#12918]
does three.js really need objext3d? when i began to read docu. object3d confused me. ithink its a waste and should not be necessary to draw a scene.

first, there are vertices (Vector3) and then faces(Face3) comes in. Face3 alrady consist normal, color, materialndex but not material. We use Object3d to combine material and material index as far as i understood. So why not face3 consist material itself instead of index? Thus we can draw a scene with a geometry only.

**Comment by mrdoob** [comment]
Keep reading 😉

**Comment by cyth319** [comment]
@mrdoob why you closed this?

**Comment by mrdoob** [comment]
Because this section is for bug reports and feature requests.

Also, unfortunately, we don't have enough resources to respond all the questions that new users may have.

**Comment by cyth319** [comment]
@mrdoob  i know that discourse will be a better place for tihs but hack i can not sign up for it. so this is the only place for me to ask this type of quesiton.Maybe i will find a few poele to discuss about the issue. On the other hand you can see it as a feature request. 
REquest: remove the object3d

**Comment by mrdoob** [comment]
> @mrdoob i know that discourse will be a better place for tihs but hack i can not sign up for it.

Why not? You should be able to sign in with your github account.

**Comment by cyth319** [comment]
yeah, i only tried with facebook and twitter so far. thanks

**Comment by cyth319** [comment]
anyway. why you said "keep reading" at first answer? is it sometihng you already thought and realized it is necessary

**Comment by mrdoob** [comment]
If you experiment a little bit more with the library you'll understand why things are the way they are.

**Comment by cyth319** [comment]
iam usign 3.js only to draw tihngs. i couldn't experiment with material section yet.  i know u put alota effort to this project but trying to make a program lighter is always good, i guess

**Comment by looeee** [comment]
I just tested and it looks like sign up with Google and Facebook were never set up properly on Discourse. 
I should probably fix that... 🤔 

I'm going to remove the Yahoo sign in link as well well I'm at it - FB, Google, Twitter and Github should be enough options.
