### ISSUE TITLE
Z axis not vertical by default

### ISSUE THREAD

**Issue by zoic21** [mrdoob/three.js#12914]
##### Description of the problem 

I just start with three.js but I see by default Z axis (this is the blue) is not set verticaly, I wonder why ? And how to fix that ?

Thank in advance

http://jsfiddle.net/sxoxnphb/

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the [forum](discourse.threejs.org) or stackoverflow for help questions.
