### ISSUE TITLE
Editor feature request: don't confirm the deletion of every object

### ISSUE THREAD

**Issue by ryankaplan** [mrdoob/three.js#12917]
##### Description of the feature change 

I find it frustrating that the editor asks to confirm every time I delete an object. It's easy enough to undo a mistaken deletion, so a hard confirmation seems unnecessary. If project maintainers agree, I'd be happy to send out a PR for the changed behavior.

**Comment by mrdoob** [comment]
> If project maintainers agree, I'd be happy to send out a PR for the changed behavior.

Yeah, give it a go!

**Comment by wuweiweiwu** [comment]
@mrdoob if no is currently working on this I'd like to take it!
