### ISSUE TITLE
Problem with envMap

### ISSUE THREAD

**Issue by aJean** [mrdoob/three.js#12910]
##### Description of the problem 

i use cubeTexture to load six skybox imgs
and set it to MeshBasicMaterial's envMap

``` javascript
var material = new THREE.MeshBasicMaterial({
       envMap: texture,
       side: THREE.DoubleSide
});

var skyBox = new THREE.Mesh(new THREE.SphereGeometry(2000, 32, 32), material);
```

it works fine with r86，but makes wrong mapping direction in r89

is there anything changes between the two version ?

and how can i fix the problem?

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Are you inverting the scale of the object?

**Comment by WestLangley** [comment]
Your skybox has an environment map???

Where did you copy that code pattern from?

**Comment by mrdoob** [comment]
Kind of makes sense (naming-wise) he wants that texture to be the environment, thus he set the envMap 🤓

**Comment by WestLangley** [comment]
I expect there will be users who will need to replace
```javascript
mesh.scale.x = - 1;
```
with
```javascript
mesh.geometry.scale( - 1, 1, 1 );
```

three.js r.89

**Comment by aJean** [comment]
hi， thanks for help
i tried to set the scale but got a black screen ...

``` javascript
skyBox.geometry.scale( 1, 1, - 1 );
```

**Comment by WestLangley** [comment]
Copy the coding patterns in the three.js examples.

**Comment by aJean** [comment]
sad t . t
