### ISSUE TITLE
wrong faceCulling when animation scales object

### ISSUE THREAD

**Issue by leoboboyan** [mrdoob/three.js#12925]
##### Description of the problem 

Recently, I found that some parts of models are not rendering on my site when animation playing.
It seems that these models are scaled by skeleton animation, when camera rotates, those parts who behind the camera will disappear, even if they are scaled so they should be seeing.

Sorry for my english, any advice?

Here is an file, you can open it with ColladaLoader2.js, then rotate the camera, the glasses will disappear at some angle.
[gc.dae.zip](https://github.com/mrdoob/three.js/files/1574867/gc.dae.zip)
##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Amritesh** [comment]
Try disabling frustrumCulling while importing the object.
for(let i=0;i<object.children.length;i++){
			let child = object.children[i];
			if(child.isMesh)
				child.frustumCulled = false;
}
*This will have some performance hit.

**Comment by leoboboyan** [comment]
> Try disabling frustrumCulling while importing the object.
for(let i=0;i<object.children.length;i++){
let child = object.children[i];
if(child.isMesh)
child.frustumCulled = false;
}
*This will have some performance hit.

thanks for your reply, i have tried, but it doesn't work.
