### ISSUE TITLE
the error of outlinepass

### ISSUE THREAD

**Issue by trymoremore** [mrdoob/three.js#12926]
i set outline as the example,but i don't need the FXAA, so i remove the FXAA,the result is that Nothing appears，it's all dark; when i add the FXAA,it back to normal.

**Comment by Mugen87** [comment]
`FXAA` is usually applied at the end of the pass chain. If you remove it, you have to set `renderToScreen` to `true` on the previous pass in the chain. In the example `webgl_postprocessing_outline.html`, this would be the `outlinePass` object.

**Comment by trymoremore** [comment]
i set the outlinePass as this: 

> outlinePass.renderToScreen=true;
but it doesn't work

**Comment by WestLangley** [comment]
Replace the FXAA pass with:
``` javascript
var copyPass = new THREE.ShaderPass( THREE.CopyShader );
copyPass.renderToScreen = true;
composer.addPass( copyPass );
```
Please use the forum or stackoverflow if you need more help.

**Comment by trymoremore** [comment]
@Mugen87 @WestLangley thanks for your help
