### ISSUE TITLE
FBXLoader: Binary files not loading correctly since new LoaderUtils code was introduced

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#12924]
I haven't had a chance to investigate this fully yet, but compressed binary files seem not to be loading since the introduction of the new LoaderUtils code - the error message takes several minutes to come up:

```
TypeError: Failed to execute 'decode' on 'TextDecoder': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'
    at Object.decodeText (three.min.js:734)
    at BinaryReader.getString (FBXLoader.js:3653)
    at BinaryParser.parseNode (FBXLoader.js:3014)
    at BinaryParser.parse (FBXLoader.js:2972)
    at THREE.FBXLoader.parse (FBXLoader.js:78)
    at FBXLoader.js:53
    at three.min.js:649
```

The same files in ASCII format load fine, as do uncompressed binary files (so the xsi_man.fbx file loads OK).

**Comment by looeee** [comment]
Here's a file that loaded before and doesn't now: [fuzzywobble.zip](https://github.com/mrdoob/three.js/files/1574244/fuzzywobble.zip)

(hopefully @FuzzyWobble doesn't mind me sharing this file)

**Comment by looeee** [comment]
OK, it wasn't anything too serious! The `BinaryParser.getUint8` method, contrary to what you would expect, does not return a `Uint8` Arraybuffer - rather it parses an section of Uint8 data types and returns an ordinary array. 

`TextDecoder.decodeText`, on the other hand, does expect a Uint8 Arraybuffer.

**Comment by agackakan** [comment]
Hello,
Thnx for the fix. There is also an error related with animation. Duration is zero.

**Comment by agackakan** [comment]
I think it is because of lack of null terminated string control in getString method

**Comment by looeee** [comment]
Can you share your model? Was it working with previous version of the loader?

**Comment by agackakan** [comment]
I have a world of warcraft model so i do not know if it is okay to share.
It was ok with previous version except fps. I corrected fps issue and was planning to share. Current version has no fps settings.
I saw your new getString implementation, mine was similar too.
Currently i have texture problems which was ok with previous version. (actually i needed to put textures in the same folder with fbx file)

**Comment by looeee** [comment]
Can you test it with the latest dev version since #12936 was merged? If you still have problems open a new issue, and a separate one for the textures problem. Although there is generally very little that can be done if you can't share the model. 

If you are worried about making the model public, you can send it to me privately and I pinky swear to delete it once I'm done 😛

**Comment by evanmrose** [comment]
@looeee @mrdoob is this scheduled for release in .90?

**Comment by mrdoob** [comment]
Yes. Should be released this week.
