### ISSUE TITLE
Blender2js --JSONLoader

### ISSUE THREAD

**Issue by Thinkia** [mrdoob/three.js#12927]
![monster](https://user-images.githubusercontent.com/33954058/34204434-8ac675c4-e5b9-11e7-8ac2-9d8f064e275a.png)

My code : https://github.com/Thinkia/ThreeJs/blob/master/demos/monster_lv1.html;

Now : use  monster_walk.json+monster_run.json+monster_attack.json+monster_death.json;

I  want: use   only  monster_all.json  ;

I   try    Refer to the document , ask teacher   but  fail;

How to optimize the code?    

Thanks

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
