### ISSUE TITLE
Was THREE.ShapeUtils.triangulate removed without warning?

### ISSUE THREAD

**Issue by loldrup** [mrdoob/three.js#12938]
from v88 to v89

A warning could have been raised, and the warning could even have pointed to an appropriate alternative.

By the way, https://threejs.org/docs still shows nothing when one searches for 'triangulation'.

**Comment by Mugen87** [comment]
I actually thought this method was only used interally by the library, sry. In any event, the new polygon triangulation algorithm ist noted in the migration guide.

TBH, i don't think we need an extra page for the triangulation algorithm in the docs. The documentation to ShapeUtils should be sufficient.

**Comment by loldrup** [comment]
The ShapeUtils documentation looks just fine, but how does one know to look for a 'ShapeUtils' class when one wants to do triangulation? Could an invisible tag 'triangulation' be added to that page?
https://threejs.org/docs/#api/extras/ShapeUtils

Thanks for the tip regarding there being a migration guide :). Though it doesn't say that ShapeUtils has been moved to the 'extras' folder.
https://github.com/mrdoob/three.js/wiki/Migration-Guide

⁣

Den 21. dec. 2017 13.54, fra 13.54, Michael Herzog <notifications@github.com> skrev:

**Comment by looeee** [comment]
The ShapeUtils page is at least the first result when you google for "three.js triangulation".

**Comment by loldrup** [comment]
Ah, I use duck Duck Duck Go, and ShapeUtils is not even on the first page of search results (though the page has infinite scroll, so I could look on forever..).


⁣

Den 21. dec. 2017 14.10, fra 14.10, Lewy Blue <notifications@github.com> skrev:

**Comment by loldrup** [comment]
Ahh, so what happened was that 'triangulate' was removed and triangulateShape has been added (or was always there). So all that's missing is:
* The migration guide could mention that 'triangulate' has been removed, deferring to triangulateShape.
* Duck Duck Go should start pointing to ShapeUtils when searching for three.js triangulation (could three.js help the poor search engine with a #triangulation tag in the ShapeUtils doc?)

⁣

Den 21. dec. 2017 14.19, fra 14.19, Michael Herzog <notifications@github.com> skrev:

**Comment by mrdoob** [comment]
> * The migration guide could mention that 'triangulate' has been removed, deferring to triangulateShape.

The migration page is a wiki. Feel free to complete the gaps 😊

**Comment by Mugen87** [comment]
@loldrup I've added a note that `ShapeUtils.triangulate()` has been removed. Thanks for that hint!

**Comment by Mugen87** [comment]
> (could three.js help the poor search engine with a #triangulation tag in the ShapeUtils doc?)

I think it is the task of `Duck Duck Go` to process the content of the website correctly. Even if i like the idea of the project, i don't think we should optimize for a specific search engine.

**Comment by loldrup** [comment]
Oh, putting super relevant tags on a web page is hardly to optimize for anything specifically.
I just tried out bing.com, and it too fails to find the ShapeUtils documentation page when searching for 'three.js triangulation'

⁣

Den 22. dec. 2017 00.04, fra 00.04, Michael Herzog <notifications@github.com> skrev:

**Comment by Mugen87** [comment]
What do you mean with tag? Something like:
```HTML
<meta name="keywords" content="triangulation">
```

**Comment by loldrup** [comment]
I just read that meta tags are sometimes used for search result text snippets, so a full 'description' text could serve both purposes, embedded in a meta tag:

<meta name="description" content="ShapeUtils provides functions for triangulation of Shapes in Three.js">

But your suggestion would also suffice, yes. Though I think one should use name="description"..? dunno...

https://www.sitepoint.com/meta-tags-html-basics-best-practices/

⁣

Den 22. dec. 2017 00.14, fra 00.14, Michael Herzog <notifications@github.com> skrev:

**Comment by challakoushik** [comment]
I used to use 
`THREE.ShapeUtils.triangulate(vertices)`
where vertices was an array of 2d points in the correct order, recently I upgraded to three js version 92 and now it says triangulate is no longer a function, so I tried the new function THREE.ShapeUtils.triangulateShape as mentioned in https://threejs.org/docs/#api/extras/ShapeUtils

but that doesnt seem to work either. What would be the way to triangulate a set of vertices?

**Comment by mrdoob** [comment]
@challakoushik https://github.com/mrdoob/three.js/blob/dev/src/extras/ShapeUtils.js#L32-L71

**Comment by challakoushik** [comment]
yep, I did the same thing but it doesnt work, I replaced triangulate with traingulateShape but I get the error 
```
Error: points[(l - 1)].equals is not a function
at removeDupEndPts (three.js?version=@@timestamp:27531)
at Object.triangulateShape (three.js?version=@@timestamp:27492)
```

**Comment by challakoushik** [comment]
@mrdoob  Okay, my bad the vertices I had were like `{x: x,y: y}` and not an instance of `THREE.Vector2` . I fixed it, Thanks!
