### ISSUE TITLE
TextureLoader onProgress

### ISSUE THREAD

**Issue by Claod44** [mrdoob/three.js#12937]
##### Description of the problem 
Hi,

I need to update a progressBar %,
TextureLoader onProgress is not working as I can see on the docs.
I found : 
using xhr / fileloader to load the image => able update the %,
Store the downloaded result and create a texture with it

How can I do that, is there news about it or any changes about textureloader onProgress ?

Thank you

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please read #10439

This suggestion might work for you: https://github.com/mrdoob/three.js/issues/10439#issuecomment-275785639

**Comment by Claod44** [comment]
Hello, Yeah I was sleeping, then back to the code I found that : 

The TextureLoader contains a load methode, the load methode needs the onProgress of the TextureLOader parameter besause the TextureLoader.load() constains an ImageLoader that is supposed to launch it back when the Image is loading. Buuuuut, the ImageLoader is restricted :
