### ISSUE TITLE
Blender importer

### ISSUE THREAD

**Issue by NeklesaYuri** [mrdoob/three.js#12941]
##### Description of the problem 

I've noticed that Blender exporter tool has an import option but it is not implemented yet.
Is it in the development now? If yes, where can I check the progress?

It would be a nice feature to be able to import .json models into a blender, because .obj generated by objexporter has a huge overhead in memory and model's geometry is unsolid.

##### Three.js version

- [x] Dev
- [ ] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
I don't know whether there's work in progress for JSON import to Blender, but one option might be to use GLTFExporter, test the output [here](https://gltf-viewer.donmccurdy.com/), then try importing to Blender with (unofficial) https://github.com/ksons/gltf-blender-importer. I'm hopeful there will be more+improved glTF import options in the near future.

**Comment by Mugen87** [comment]
> Is it in the development now?

As far as i know, no. Also see #12903
