### ISSUE TITLE
Loaders: Inconsistent implementations of .setPath()

### ISSUE THREAD

**Issue by wolfgangvonludwigsburg** [mrdoob/three.js#12942]
Hey dear guys,

since you urged + forced me (me, just a innocent threejs user), see https://github.com/mrdoob/three.js/issues/12903
I bravely followed you to use **GLTF**, and tried ...

It looks, as if **GLTFLoader.setPath()** doesn'nt work ...

The default "Blender Cube" should appear like this:
https://rawgit.com/wolfgangvonludwigsburg/three.js/dev/examples/_webgl_loader_gltf_cube_PR.html

Compare to current "90dev" state:
https://rawgit.com/wolfgangvonludwigsburg/three.js/dev/examples/_webgl_loader_gltf_cube_fail.html
Console.log: Failed to load resource: the server responded with a status of 404 (Not Found)

To verify the loading path, I've put in an additionally FileLoader request (which succeeds).

The fix could be, in GLTFLoader.js,
line 27, after
```
    var path = this.path !== undefined ? this.path : THREE.LoaderUtils.extractUrlBase( url );
```
insert
```
    if ( this.path !== undefined )
        url = this.path + url;
```
If you verify the fault, should I do a PR, or the author of GLTFLoader.js ?

BTW: Additionally I tried JSONLoader.setPath() which fails (member method not available) ...
- maybe all loaders should behave accordingly in the same manner ... ?

90dev, Chrome, Windows

**Comment by donmccurdy** [comment]
@wolfgangvonludwigsburg I think you're right that it's a bug, but FYI you should rarely need to use `.setPath()` to load a model. Here are [docs for GLTFLoader](https://threejs.org/docs/#examples/loaders/GLTFLoader), and a basic example looks like this:

```js
var loader = new THREE.GLTFLoader();
loader.load('models/gltf/Cube/cube.gltf', function ( gltf ) {
  scene.add( gltf.scene );
});
```

**Comment by donmccurdy** [comment]
BTW if you just have a glTF model and want to very quickly make sure it's exported correctly from your editor, you can drag-and-drop it here: https://gltf-viewer.donmccurdy.com/

**Comment by donmccurdy** [comment]
@looeee it looks like FBXLoader is doing the same thing as GLTFLoader here, and using `setPath()` only for extra resources. Any idea if that has been discussed before somewhere?

**Comment by wolfgangvonludwigsburg** [comment]
@donmccurdy
THX for your comments!

I would argue, that if setPath() is available on a loader, it should function ...

**Comment by donmccurdy** [comment]
> Well, I would argue, that if setPath() is available on a loader, it should function in the same way, as the other loaders do ...

It looks like other loaders are not consistent either... I think the purpose of `setPath()` is just for when you have extra resources in a different folder than your original model, and otherwise you don't need to use it. In which case GLTFLoader is doing the right thing. But I'm not sure that's how it's intended to work.

**Comment by wolfgangvonludwigsburg** [comment]
It's a matter of software design ...
FileLoader as a Base class, from which all other Loaders are deriving

**Comment by donmccurdy** [comment]
Well, except that Loader is already the base class, not FileLoader, and FileLoader never has to deal with extra resources... Perhaps we should rename the method `setResourcePath` or even remove it since `setUrlModifier()` can do the same thing now, but that would be a breaking change..

**Comment by wolfgangvonludwigsburg** [comment]
Some model file formats have e.g. texture links included, which additionally complicates this issue.
That's why some format have "all resources included", e.g. blender, threejs format version 4, as far as I know.

**Comment by donmccurdy** [comment]
> Some model file formats have e.g. texture links included, which additionally complicates this issue.

True, FBX and glTF have that as well. Fortunately I think that's the easiest case here. 😁

**Comment by mrdoob** [comment]
> @looeee it looks like FBXLoader is doing the same thing as GLTFLoader here, and using `setPath()` only for extra resources. Any idea if that has been discussed before somewhere?

Interestingly, `MTLLoader` also has a `setTexturePath()`. https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/MTLLoader.js#L74-L78

**Comment by donmccurdy** [comment]
I've renamed the issue *Loaders: Inconsistent implementations of .setPath()*, as I think the changes to consider would be:

1. [ ] Ensuring that all loaders use `setPath()` for extra resources but not the original request.
2. [ ] Deprecate `setPath()` on FileLoader and ImageLoader, as they have no extra resources.
3. [ ] Consider renaming `setPath()` in cases where it must behave differently than this, renaming the normal case to `setResourcePath()`, or similar clarification.

**Comment by wolfgangvonludwigsburg** [comment]
I think in the "loaders class tree", there are even more inconsistencies as well;
if I only focus on .obj and .gltf, there are differences in the granularity of the returned interface objects,
eg.:
- OBJLoader  returns a _group_ object
- OBJLoader2 returns _object.detail.loaderRootNode_ (= group)
- GLTFLoader returns another _"compound object"_ ...

BTW, another issue I found out, it seems as if there is no ability of loading just & only points ...
You can export **Points** (= a PointCloud (without faces/uvs)) with Blender,
but no way to import these Points in threejs, as far as i have seen for now.

**Comment by donmccurdy** [comment]
The differences in returned values have various reasons, some intentional some probably not... glTF may contain more than just a model, so a `THREE.Group` is not sufficient. Feel free to open a new issue to suggest changes, but I think it's too complex a thing to discuss in this thread.

About points, could you open a new issue describing what you've tried that isn't working? Some formats support points, other formats do not. Formats that support points may not necessarily return _only_ a `THREE.Points` object, e.g. glTF would return that something like this:

```
{
  scene: <THREE.Scene>,
  ...
{
```

.... where the `scene` entry contains one or more `THREE.Points` objects as children or grand-children.

**Comment by takahirox** [comment]
I'm not sure if it's the same issue you're facing, but I'm already aware of that `GLTFLoader` can't handle(display) `Points` correctly.

The reason is `GLTFLoader` doesn't create `PointsMaterial` for `Points`. `Points` needs `PointsMaterial` to be rendered. It can't be rendered with `Mesh*Material` (If I'm right).

I already started to work on the fix in my local branch.

Another issue I'm aware of is glTF doesn't hold point size information. I'm gonna ask or open an issue to glTF team (if necessary).

As @donmccurdy mentioned, please open an issue if what I mentioned aren't what you ran into.

**Comment by wolfgangvonludwigsburg** [comment]
@donmccurdy, @takahirox: Many THX for your responses so far!

Don has recently "widened" the issue concern,
if you go one step further, it could even become: _loaders - code quality / orthogonal code testing_

I mean something like (pseudo code):

```
for each available model-loader:
   load (her specific format) export file/model, containing 1 point / 1 edge / ... / 1 (default) cube / ... / complex model into her scene
   for all renderers:
      render(),
      then look, if the scene has rendered the model as expected

```
I can write a 
- test case to accomplish that (in the coding style of e.g. examples/webgl_multiple_elements.html), or 
- write unit tests (like test/unit/editor/Loader.tests.js)

I found (in docs, wiki) no development directive, which of these three.js/mrdoob does prefer ? ...

Concerning **Points**, I'll open a new issue or PR, as you suggested ...
Beforehand: The most minimal model is IMO 1 Point/1 Vertex/no materials,
e.g. 1_point.obj
```
# zero point
v 0 0 0
# maybe plus
p 1

```
which could be rendered by THREE.Points / gl.drawArrays(gl.POINTS, ...), taken any default material/fragm. shader.
In my tests with any loaders, I could'nt find that zero point, oh no ;-)

**Comment by wolfgangvonludwigsburg** [comment]
To be more concrete (I'll work it out next days; **Happy 2018 !!**):
```
<script src='../build/three.js'             ></script>
<script src='js/controls/OrbitControls.js'  ></script>
<script src='js/libs/dat.gui.min.js'        ></script>
<script src='js/loaders/LoaderSupport.js'   ></script>
<script>

    const strLoaders = [
        {name: 'OBJLoader'      , ext: 'obj'    },
        {name: 'OBJLoader2'     , ext: 'obj'    },
        {name: 'GLTFLoader'     , ext: 'gltf'   },
        {name: 'ColladaLoader'  , ext: 'dae'    },
        {name: 'FBXLoader'      , ext: 'fbx'    },
        //TODO: all model-loaders...
    ]

    const models = [
        'Point',
        //TODO: use all these models ...
        'Edge',
        'Cube',
        'Monkey',
    ]

    for (strLoader of strLoaders){

        const script = document.createElement('script')
        document.head.appendChild( script )
        script.onload = function(e) {
            const loader = new THREE[ this.strLoader.name ]
            loader.load(
                `models/_/Points/${models[0]}.${this.strLoader.ext}`,
                model =>{
                    console.log( model )
                    //TODO: add to scene, render, verify ...
                }
            )
        }
        script.strLoader = strLoader
        script.src= `js/loaders/${ script.strLoader.name }.js`

    }//for

</script>

```

**Comment by mrdoob** [comment]
@takahirox how about this..

* `.setPath` applies to the original file.
* `.setResourcesPath` if set, we apply it to resources, otherwise we use the path from `.setPath`.

PS: Yes, I prefer `.setResourcesPath` (plural) instead of `.setResourcePath`. 
PS2: `.setTexturesPath` also sounds better than `.setResourcesPath`.

**Comment by WestLangley** [comment]
Actually, the singular form, `.setTexturePath`, sounds best to me for some reason...

**Comment by donmccurdy** [comment]
Note that it is not just for textures — resources could include `.bin` files for glTF, audio and script files for SEA3D, animation files for MMD, ... but MTLLoader does already use a `.setTexturePath` method for one example.

Another way to simplify might be deprecating `.setPath` on loaders that have no external resource files.

**Comment by Mugen87** [comment]
I vote for @mrdoob suggestion. Having two methods, one for the main file and a second one for additional resources. But I would choose `setResourcePath()` as the method name.

**Comment by takahirox** [comment]
Sorry I wrote poorly but what I proposed is same as what @mrdoob suggested. I implied 

> .setResourcesPath if set, we apply it to resources, otherwise we use the path from .setPath.

I think what we should decide here are

1. Whether we need `.setPath` or not for original data
2. Singular or plural for additional resources
3. Whether we need the same method name for additional resources or each loader can have different method name like `.setTexturePath` for `MTLLoader` while `.setResourcePath` for `GLTFLoader`.

Voting

1. We keep `.setPath` so far
2. Singlar
3. Different method names

**Comment by WestLangley** [comment]
>.setResourcePath sounds good to you @WestLangley?

Sure.

**Comment by WestLangley** [comment]
What is the status on this, please?

**Comment by donmccurdy** [comment]
I also prefer `setResourcePath` over `setTexturePath` and the plural alternatives. Since resource is a generic term, I do not think we need an additional `setTexturePath` method for loaders where all of the resources happen to be textures, like MTLLoader. If we're agreed on that, the tasks are updating (all?) loaders such that:

* [ ] `.setPath()` affects original file (or multiple original files forCubeTextureLoader)
* [ ] `.setResourcePath()` affects dependencies of original files, if applicable

**Comment by WestLangley** [comment]
> the tasks are updating all loaders such that:
>>.setPath() affects original file (or multiple original files forCubeTextureLoader)
> > .setResourcePath() affects dependencies of original file, where applicable

>List of loaders:
>...

It seems there is agreement. Who is willing to take responsibility for this task?

**Comment by Mugen87** [comment]
I suggest the owners mentioned in this [wiki page](https://github.com/mrdoob/three.js/wiki/Owners) should migrate their respective loaders.

**Comment by donmccurdy** [comment]
Checklist loaders requiring a `setResourcePath()` method:

- [ ] AssimpJSONLoader
- [ ] AssimpLoader
- [ ] (#14932) ColladaLoader
- [ ] FBXLoader
- [ ] GLTFLoader
- [ ] LoaderSupport (?)
- [ ] MTLLoader
- [ ] OBJLoader2 (?)
- [ ] VRMLoader
- [ ] deprecated/LegacyGLTFLoader
- [ ] ObjectLoader

*Based on all files in examples/js/loaders/ containing the text "setPath", plus ObjectLoader. There may be others I've missed, like XLoader or SEA3DLoader, if this change makes sense for those loaders.

**Comment by Mugen87** [comment]
@kaisalmen Can you please check how `LoaderSupport` and `OBJLoader2` are affected by this issue? It would be great if you can provide a PR in order to align the interface if necessary.

**Comment by kaisalmen** [comment]
Yes, I will take care. Thanks for pinging me.

**Comment by Mugen87** [comment]
@takahirox I've had a look at `MMDLoader` and I think it's a bit complicated to implement a `.setPath()` method. The loader has a method `MMDLoader.loadWithAnimation()` that accepts two URLs to assets, possibly both in different directories. A single base path defined via `setPath()` could not handle a use case like this. What do you think?

https://github.com/mrdoob/three.js/blob/2f46e2a6ed597423c1aee7789cc1ad0e988a8772/examples/webgl_loader_mmd.html#L124-L133

**Comment by kaisalmen** [comment]
@Mugen87 PR for OBJLoader2 V2.5.0 implementing this agreement, plus nodejs support and hopefully a working fix for minification problems with webpack/angular should be ready this weekend (before R98 is due).

**Comment by takahirox** [comment]
＠Mugen87 MMD assets MMDLoader handles can be grouped into three.

1. Model files (pmd/pmx)
2. Texture image files. File path is pointed from model files.
3. Keyframe Animation, Position data files (vmd/vpd). Independent of model and texture files.

Like other loaders, 1. can be with `.path` and 2. can be with `.resourcePath`. Wondering how 3. should be with. Maybe `.path`? Any other loaders which is in a similar situation?

**Comment by Mugen87** [comment]
> Any other loaders which is in a similar situation?

Unfortunately not. But I think it should be okay to establish something like `.setAnimationPath()` and `.animationPath`. Any opinions on this?

**Comment by WestLangley** [comment]
I'm assuming `.setAnimationPath()` would be for `MMDLoader` only. I think that is OK.

**Comment by abishek28007** [comment]
@donmccurdy 

```javascript
var loader = new THREE.GLTFLoader();
loader.load('models/gltf/Cube/cube.gltf', function ( gltf ) {
  scene.add( gltf.scene );
});
```

gives following error

```
index.js:1375 SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (<anonymous>)
    at GLTFLoader.parse (GLTFLoader.js:110)
    at Object.onLoad (GLTFLoader.js:58)
    at XMLHttpRequest.<anonymous> (three.module.js:23913)
```
since the gltfLoader is trying to fetch data using a fetch/get call.
