### ISSUE TITLE
Superfluous memory allocations in the 'triangulateShape' function

### ISSUE THREAD

**Issue by loldrup** [mrdoob/three.js#12940]
https://github.com/mrdoob/three.js/blob/dev/src/extras/ShapeUtils.js

Functions 'removeDupEndPts' and 'addContour', as well as arrays 'vertices' and 'holeIndices' are allocated on *each* call to the triangulateShape function.

These could all be moved to a closure, and thus reused across calls.

**Comment by Mugen87** [comment]
> These could all be moved to a closure, and thus reused across calls.

Yes, that would of course be possible. I just wonder if it this change is really necessary since `ShapeUtils.triangulateShape()` is normally not called within the render loop. Right now, the code is easy to read and avoids additional scopes which always introduce some overhead.

**Comment by loldrup** [comment]
Well, the three.js code base is littered with scopes introduced for performance reasons. So any source code reader will have to grok the scoping idea anyhow. You're not spoiling a pristine piece of real estate ;)

If you decide not to scope, I'll just copy the code and make my own scoped version. No problem.






Den 21. dec. 2017 23.55, fra 23.55, Michael Herzog <notifications@github.com> skrev:

**Comment by Mugen87** [comment]
Hey, i don't feel strong about this 😉 . If @mrdoob thinks it's worth, we can of course make a PR.

**Comment by Mugen87** [comment]
But there is one point i want to highlight: Many loaders and all geometry generators also have nested functions since the related code is not called in each frame. Therefore i'm not sure further action is needed.

**Comment by mrdoob** [comment]
> If you decide not to scope, I'll just copy the code and make my own scoped version. No problem.

While you're at it, maybe you want to do a PR with the change too? 😊

**Comment by loldrup** [comment]
Good idea :)
Though I'm going in vacation mode until 3rd of January.

⁣

Den 22. dec. 2017 01.07, fra 01.07, "Mr.doob" <notifications@github.com> skrev:

**Comment by loldrup** [comment]
The question arises: what is three.js meant for? If it is strictly meant for the things that the authors of three.js can imagine (it deep to be typical, blessed usage), then I follow your point.
If the usage of three.js is meant to be more open ended, then we can't rule out that users won't use basically any available function in some high performance situation.

⁣

Den 22. dec. 2017 00.26, fra 00.26, Michael Herzog <notifications@github.com> skrev:

**Comment by mrdoob** [comment]
> The question arises: what is three.js meant for? If it is strictly meant for the things that the authors of three.js can imagine (it deep to be typical, blessed usage), then I follow your point.

Too hard of a question for these festive days... 😉

I'll do the change.

**Comment by mrdoob** [comment]
Fixed. Thanks!
