### ISSUE TITLE
Shadow based on FPS 

### ISSUE THREAD

**Issue by AmjadKh94** [mrdoob/three.js#12958]
how to enabled/ disable shadow in respect to FPS ?
for example : When FPS is less than 30 i want to disable shadow and when its more then 30 i want to enable it 
- [x] Dev
- [ ] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
Please direct help questions to the forum: https://discourse.threejs.org/
