### ISSUE TITLE
GLTFLoader loses non-ascii char name of node

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#12956]
##### Description of the problem 

`GLTFLoader` loses non-ascii char name of node because of `PropertyBinding.sanitizeNodeName()`, for example Japanese char bone name 右手 (right hand).

I faced this issue when I tried converting `MMD` model to glTF.  Not only Japanese char but also Chinese char demand will probably increase so I wanna fix.

Regular expressions used in `sanitizeNodeName()` are

    name.replace( /\s/g, '_' ).replace( /[^\w-]/g, '' )

`\w` represents `[a-zA-Z_0-9]` then it doesn't match non-ascii chars.

An easy solution in my mind is explicitly specifying chars we wanna remove instead of using `[^\w-]`. Perhaps `-`, `'`, `"`, `:`, `/` and so on.

Any better solutions?

/cc @donmccurdy 

##### Three.js version

- [x] Dev
- [ ] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
The goal is that `sanitizeNodeName()` will output names that are safe for use with `parseTrackName()`, which also relies on `/w` in regular expressions... if we can fix it in both places, no objection to changing the expressions though. Maybe relevant: https://stackoverflow.com/questions/2392194/how-to-match-the-international-alphabet-english-a-z-non-english-with-a-regu

**Comment by takahirox** [comment]
`parseTrackName()` allows any chars for accessor name, like `.bones[右手]`.

	// Object on target node, and accessor. Name may contain only word
	// characters. Accessor may contain any character except closing bracket.
	var objectRe = /(?:\.([\w-]+)(?:\[(.+)\])?)?/;

	// Property and accessor. May contain only word characters. Accessor may
	// contain any non-bracket characters.
	var propertyRe = /\.([\w-]+)(?:\[(.+)\])?/;

**Comment by donmccurdy** [comment]
In accessors yeah, but the sanitization would need to make names safe for `nodeRe` as well: https://github.com/mrdoob/three.js/blob/dev/src/animation/PropertyBinding.js#L125

Maybe worth trying to replace `\w` with `\p{L}`, unit tests should catch things well enough here.

**Comment by takahirox** [comment]
Does JavaScript regular expression support `\p{L}`? `'右手'.match( /\p{L}+/ )` will be `null` here.

**Comment by takahirox** [comment]
Regarding `objectIndex` (accessor name of object), it's compared with `.name` only for `Bone`.

https://github.com/mrdoob/three.js/blob/dev/src/animation/PropertyBinding.js#L544

So, relaxing sanitize for `Bone` instance would be another solution?

**Comment by donmccurdy** [comment]
That's pretty disappointing that JS can't detect non-ASCII word characters in regular expressions. 😫

It would be nice to solve this without checking node type, since devs using their native languages for other nodes is totally reasonable.... proposed a fix here: https://github.com/mrdoob/three.js/pull/12968
