### ISSUE TITLE
load mutiple objs in quadtree with lod

### ISSUE THREAD

**Issue by weimochanyue** [mrdoob/three.js#12962]
im using three.js lod to load mutiple models,here is my code, i found if a want to add lod when load obj success, i need to redo the loop.
is there any packaged function that i can use if i want load mutiple objs in quadtree with lod??

`var addLod = function(object){
					mesh = object.children[0];
					group.add( mesh );
					var count = Math.pow(4,(j-1));
					if(i == count){
						var distance = dist[j];
						group.updateMatrix();
						group.matrixAutoUpdate = false;
						lod.addLevel( group, distance );
						group = new THREE.Group();
						i = 1;
						j++;
					}
					else{
						i++;
					}
				}

				for(l = startLevel; l<(endLevel+1); l++){
					sideW = Math.pow(2,l); 
					
					group = new THREE.Object3D();//create an empty container
					for(m=1;m<(sideW+1);m++){
						for(n=1; n<(sideW+1);n++){
							var step = Math.pow(2,(totalLevel-l));
							var x = sideTotal - m*step;
							var y = sideTotal - n*step;
							
							// load obj
							var filename = 'tile_'+l+'_'+x+'_'+y+'_tex';
							var mtlLoader = new THREE.MTLLoader();
							mtlLoader.setPath( objLocate);
							mtlLoader.load( filename+'.mtl', function( materials ) {

								materials.preload();

								var objLoader = new THREE.OBJLoader();
								objLoader.setMaterials( materials );
								objLoader.setPath(objLocate);
								objLoader.load( filename+'.obj', addLod);
							}, onProgress, onError);
						}
					}
				}`

**Comment by looeee** [comment]
Please direct help questions to the forum: https://discourse.threejs.org/
