### ISSUE TITLE
Direct support for Decal textures like bump and color texture

### ISSUE THREAD

**Issue by nayanpts** [mrdoob/three.js#12977]
Hello team,

This is a feature request:
I was wondering if there is a possible way in three.js to implement decal textures directly like bump and color texture.

Let's say I have a JSON file containing a cube with 6 faces, one of its face has a decal texture (a .png image with part of image transparent) and a color (red),
Once load it into three.js scene, we can see both decal texture and color behind it.

Thanks.

**Comment by WestLangley** [comment]
You can monkey-patch decal support using a pattern like the following:
```javascript
THREE.ShaderChunk.map_fragment = THREE.ShaderChunk.map_fragment.replace(

	`diffuseColor *= texelColor;`,

	`
	#ifndef DECAL
		diffuseColor *= texelColor;
	#else
		diffuseColor = vec4( mix( diffuse, texelColor.rgb, texelColor.a ), opacity );
	#endif
	`

);
```
Usage:
```javascript
var material = new THREE.MeshPhongMaterial( { // or Basic, Lambert, Standard, Physical
	color: 0xff0000,
	map: texture
} );

material.defines = material.defines || {};
material.defines.DECAL = ""; // set as needed
```
If there is interest, we can support this feature via either a `material.decal = true` flag, or if the map and decal map need to be supported concurrently,  a separate `material.decalMap` property.

**Comment by nayanpts** [comment]
Hello Team,

Thank you very much..

This solution worked for us.

Also, it would be really great if something like material.decalMap existed, so that we could apply both color texture and decal texture on the same face.

Thanks.

**Comment by WestLangley** [comment]
>so that we could apply both color texture and decal texture on the same face.

You can also use the approach explained [in this post](https://github.com/mrdoob/three.js/issues/12135) to do that.

**Comment by pailhead** [comment]
@WestLangley 

Any chance you could give some thoughts on why you're suggesting this:

>You can monkey-patch decal support using a pattern like the following:

Rather than using `material.onBeforeCompile`?

Why would you monkey patch this and override it globally?

**Comment by WestLangley** [comment]
>Any chance you could give some thoughts on why you're suggesting this:

Because it was easy.

>Why would you monkey patch this and override it globally?

The built-in materials still work as they did prior to the monkey patch, and the new decal feature works with multiple built-in materials.

**Comment by pailhead** [comment]
>Because it was easy.

Easy for this specific example, or easy overall? Would you do this instead of the `onBeforeCompile` or you wouldn't have `#ifdef` branching if you changed the shader for a specific material? Not trying to be a smart-ass, just trying to understand the way of thinking.

**Comment by WestLangley** [comment]
I did not give it that much thought. `onBeforeCompile()` is a perfectly fine solution, too.

**Comment by Mugen87** [comment]
Closing. Using [Material.onBeforeCompile](https://threejs.org/docs/index.html#api/en/materials/Material.onBeforeCompile) seems the best way to extend built-in materials with such small enhancements. The introduction of a separate `decalMap` seems too use case specific.
