### ISSUE TITLE
Documentation correction required

### ISSUE THREAD

**Issue by atul-mourya** [mrdoob/three.js#12974]
##### Description of the problem 

Hi, there's a small correction needed in the documentation that I recently noticed.
xhr and err argument are not in their corresponding positions

![image](https://user-images.githubusercontent.com/16312255/34372835-657e3a74-eafd-11e7-9f86-b9f771ed703e.png)

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
Good catch!  

There's an "edit" button in the top right of each docs page, would you like to submit a correction?

**Comment by atul-mourya** [comment]
@looeee Thanks for the direction. I made the changes now.

**Comment by wolfgangvonludwigsburg** [comment]
Here is another one, in:

https://threejs.org/docs/#examples/loaders/MTLLoader

there is a reference to **OBJMTLLoader**, which seems no longer do exist ?
(... in the docs, and in the examples/js/loaders-tree)

Before I edit, can someone please confirm ...

r90dev

**Comment by Mugen87** [comment]
Both issues should be fixed now :+1: 

eff32a82114d3fe4aed0eb11f5c9b2918696ccb5
92dacdcce9f78eb7aba2df6e915fb073bdd22049
