### ISSUE TITLE
IO_THREE for THREE.ObjectLoader has a bug: allows only one material per geometry, and only if material has no texture

### ISSUE THREAD

**Issue by DenisTis** [mrdoob/three.js#12971]
By loading each scene object separately with JsonLoader, everything works fine.

However, once all objects are combined in one scene and scene file is exported from Blender,
THREEJS refuses to use JSONLoader, and you are obliged to use ObjectLoader.
However loaded object has only one material, if material has no texture, or no material at all, if material has texture.

THREE.JS is 0.88.0, Blender v2.79, IO_THREE: 4.3.
By googling I found the issue exists from 2015 already...

By parsing exported JSON I found the reason:
"geometries" section is correct and contains all geometries used in scene.
"object-children" section contains hierarchy of all geometries used in the scene.
For example, I have 3 road blocks, this is one geometry, but 3 entries under object section.

Then each of these entries contains both propetries "geometry" and "material".

It seems to me to be a bug, as all materials should be taken from relevant "geometry" section.

Here is the same issue described 3 years ago:
https://stackoverflow.com/questions/29927755/exporting-a-scene-from-blender-to-threejs-every-object-has-just-one-single-mate

**Comment by Mugen87** [comment]
What happens when you export your scene in a format like `FBX`, `Collada` or `glTF` and use one of the respective [loaders](https://github.com/mrdoob/three.js/tree/dev/examples/js/loaders)?

There are also some examples that illustrates the usage of these entities:

https://github.com/mrdoob/three.js/blob/dev/examples/webgl_loader_fbx.html
https://github.com/mrdoob/three.js/blob/dev/examples/webgl_loader_collada.html
https://github.com/mrdoob/three.js/blob/dev/examples/webgl_loader_gltf.html

**Comment by donmccurdy** [comment]
If you’re able to share the `.blend` file so something similar, that may be helpful.

The official glTF blender exporter is here: https://github.com/KhronosGroup/glTF-Blender-Exporter and you can test the result in threejs with https://gltf-viewer.donmccurdy.com/

**Comment by DenisTis** [comment]
Hi guys, thanks a lot for positive answer. 
I tested the scene with glTF-Blender-Exporter and uploaded it to gltf-viewer - it works fine!
However, I cannot upload scene.gltb file in my javascript.
I try to do as in this link: https://threejs.org/docs/#examples/loaders/GLTFLoader
There, I get complaint for the line 
`let loader = new THREE.GLTFLoader();`
- saying "THREE.GLTFLoader is not a constructor"

I checked and I cannot find this object in three.js library. I thought probably it is available in last THREE version only, updated from 88 to 89, but still have same problem. Should I use some plugin for that?

**Comment by donmccurdy** [comment]
Many loaders aren’t included by default in three.js, but you can download the ones you want here: https://github.com/mrdoob/three.js/tree/dev/examples/js/loaders

and then include them in the page as:

```html
<script src="FooLoader.js"></script>
```

**Comment by donmccurdy** [comment]
Or in browserify / commonjs:

```js
FooLoader = require('three/examples/js/loaders/FooLoader');
```

**Comment by DenisTis** [comment]
Thank you for clarifying! A small thing - I could see that GLTFLoader is not exporting shadow flags "Cast" and "Receive" from blender. As it is a minor thing, I could activate it manually. Is it planned to deliver new version of GLTFLoader? Should I open a new issue for that?

**Comment by donmccurdy** [comment]
The glTF file format doesn’t have a way to include shadows other than ambient occlusion, so you’d need to enable them after loading the model.
