### ISSUE TITLE
Support for multiple canvases

### ISSUE THREAD

**Issue by wdanilo** [mrdoob/three.js#12978]
Hi!
Does Three.js support drawing to multiple html canvases? It is possible in pure WebGL and it would be straightforward to add it to Three.js if i'm not missing something obvious. I haven't found any simple API allowing for it though. Here is an example: https://jsfiddle.net/greggman/vDKd5/

**Comment by WestLangley** [comment]
https://threejs.org/examples/?q=multiple

**Comment by wdanilo** [comment]
@WestLangley oh, I have to be blind! Thank you for your answer and yeah, its simple to achieve using current apis! I understand it is better to use just canvases and "draw" there results from render than using multiple renderers? Or using multiple renderers should have similar performance and the scene and all the buffers would be "shared" under the hood?

**Comment by WestLangley** [comment]
Sorry, I have no idea. Perhaps you can try the forum...

**Comment by mrdoob** [comment]
> Or using multiple renderers should have similar performance and the scene and all the buffers would be "shared" under the hood?

It's better to reuse the same renderer.
