### ISSUE TITLE
ImageLoader does not URL-escape "+"

### ISSUE THREAD

**Issue by unphased** [mrdoob/three.js#12983]
##### Description of the problem 

AWS S3 rejects `+` in URLs (on GETs), nonconformant to spec. See https://forums.aws.amazon.com/thread.jspa?messageID=722673

It would be nice if there was maybe a way to configure ImageLoader to escape its url's. It's unclear if it would be safe to just change ImageLoader to escape its url's. It would probably break people's stuff. 

Since my app directly loads from S3 for the time being, I see no quick way to fix this without continually patching my three.js from now on. Kind of lame, so I'm sort of just asking folks for how they would address this type of issue. Thanks. 

I'm even considering hacking my MTL file data (which contain the relative paths to the particular jpgs in question here) to escape those pluses, just so I can avoid maintaining an additional patch on a core dependency. Only because it turns out that this is still practical for me to do at this time.

##### Three.js version

- [ ] Dev
- [ ] r89
- [x] r88
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
You can override request URLs for any of the loaders using a [LoadingManager](https://threejs.org/docs/#api/loaders/managers/LoadingManager), as long as the loader uses its manager correctly;

```js
var manager = new THREE.LoadingManager();
manager.setURLModifier( ( url ) => {
  return url.replace( /\+/g, '%2B' );
} );
var mtlLoader = new THREE.MTLLoader( manager );
mtlLoader.load( 'my+materials.mtl', function () { ... } );  // '+' in URL will be escaped.
```

**Comment by unphased** [comment]
Thank you so much

**Comment by unphased** [comment]
This may not be properly wired through with OBJLoader2, but I should have enough information to get somewhere useful with it at least.

**Comment by unphased** [comment]
I will have a PR for OBJLoader2 shortly. It's just not passing the LoadingManager through. 

I do have a question though. It's clear to see that there exists a difference in behavior with e.g. the `+` URL-escapement between ImgLoader and FileLoader... how much of that matters since loading an MTL causes it to load both types of resources under the hood?

Actually I'm looking at the dev branch now and stuff has changed quite a bit comparing to r88, so my questions seem moot. This issue might even be moot. Let's see...
