### ISSUE TITLE
GLTFLoader: No received shadows for spec/gloss materials.

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#12980]
From https://github.com/aframevr/aframe/issues/3325, glTF models using the spec/gloss ShaderMaterial do not receive shadows, while those using the metal/rough MeshStandardMaterial do.

Demo: https://bug-gltf-specgloss-shadows-lbxbxojcha.now.sh/

**Comment by takahirox** [comment]
I'll check into later.

**Comment by takahirox** [comment]
In demo, looks like the bottom object receives shadow of the top object.

![image](https://user-images.githubusercontent.com/7637832/34400588-554ede5e-ebd6-11e7-8a3f-3bda2db81946.png)

 Am I missing something?

**Comment by donmccurdy** [comment]
Hmm ok I don't see shadows in Chrome, but it's fine in Firefox. That's ... odd. 🤨

**Comment by takahirox** [comment]
The screenshot is taken on my Chrome (+Windows10)

**Comment by donmccurdy** [comment]
No such luck here, Chrome + macOS. The lighting does animate correctly, just no shadows. Very strange..


<img width="356" alt="screen shot 2017-12-28 at 12 34 28 am" src="https://user-images.githubusercontent.com/1848368/34401192-fb3f7596-eb66-11e7-9034-d968030cd802.png">

**Comment by takahirox** [comment]
I made jsfiddle example. I wanted to remove A-Frame from the example.

http://jsfiddle.net/kjpddn34/1/

![image](https://user-images.githubusercontent.com/7637832/34412265-85418f6e-ec1f-11e7-9feb-97d8f044217a.png)

On my Chrome + Windows10, the bottom specular-glossiness model receives the shadow cast by the top specular-glossiness model as the screenshot shows.

How will it be on Mac? (I don't have Mac)

**Comment by donmccurdy** [comment]
Ok, that example does look correct on Chrome + macOS, shadows are fine:

<img width="255" alt="screen shot 2017-12-28 at 9 19 02 am" src="https://user-images.githubusercontent.com/1848368/34413255-30557d86-ebb0-11e7-9ff9-07e2d5daff6b.png">

so the issue must be (a) in A-Frame or (b) something specific to the Skull model...

**Comment by PlumCantaloupe** [comment]
I did notice that the lighting works on Windows 10 (FF57) also; but yes nothing on Mac OSX High Sierra (FF57) or iPhone iOS11 (Safari). I also re-exported the model using blender and Khronos GLTF exporter plugin ( https://github.com/KhronosGroup/glTF-Blender-Exporter ) and shadows are received for MetalRough worked but not SpecGloss.

I am just getting into Aframe and Three.js but you can see an example test here: https://plumcantaloupe.github.io/  (along with another randomly textured object). Going from left to right: skull.obj (manual import) skull.gltf (metalRough) skull.gltf (specGloss) sphere.gltf(specGloss).

Hope that helps. I'll dive in a bit more once more comfortable (I am not strong in .js just yet :).

**Comment by takahirox** [comment]
I updated jsfiddle example with Skull specular-glossiness model.

http://jsfiddle.net/kjpddn34/2/

Looks fine on my Windows10 + Chrome.

![image](https://user-images.githubusercontent.com/7637832/34450730-147cf142-ed55-11e7-89a6-16d489958211.png)

How about Mac?

**Comment by donmccurdy** [comment]
Thanks, in Chrome on macOS I do see the shadow on the skull as well.

So, I guess that narrows the issue down to something A-Frame specific?

**Comment by takahirox** [comment]
Maybe yes?

I haven't read the related A-Frame code yet but I guess there's `if ( material.isStandardMaterial )` that's missing specular-glossiness material or something? (But it can't explain why this's platform specific issue...)

**Comment by donmccurdy** [comment]
Here's the relevant code: https://github.com/aframevr/aframe/blob/master/src/components/shadow.js#L35-L51

It might be just some edge case where `material.needsUpdate = true` isn't called.

**Comment by takahirox** [comment]
That could be?

Running the following code on the console would be able to check if that's the issue.

    document.getElementsByTagName('a-scene')[0].object3D.traverse( function ( obj ) {

        if ( obj.material ) {

            if ( Array.isArray( obj.material ) ) {

                for ( var i = 0, il = obj.material.length; i < il; i ++ ) {

                    obj.material[ i ].needsUpdate = true;

                }

            } else {

                obj.material.needsUpdate = true;

            }

        }

    } );


BTW I've found another issue in that A-Frame code.
`node.material` can be `Material` array but the code is missing that case.

https://github.com/aframevr/aframe/blob/master/src/components/shadow.js#L45

should be like this

    var materials = Array.isArray( node.material )
                      ? node.material
                      : node.material.materials || [node.material];

I'll test and send PR later (or next year?), I gotta go out now.

Skull doesn't have material array, so this isn't the reason of the original issue.

**Comment by donmccurdy** [comment]
Heh, now the demo A-Frame demo is showing shadows for me correctly too: https://bug-gltf-specgloss-shadows-lbxbxojcha.now.sh/ ... maybe a race condition with that `scene.hasLoaded` check, then? I was on a slower internet connection earlier.

**Comment by takahirox** [comment]
You meant, the shadow is fine without the code I posted above now?

If so, I want someone to try the code who can reproduce the issue to know if it seems race condition. I can't reproduce  the issue here....

**Comment by donmccurdy** [comment]
With no changes, right... i'm assuming it's a race condition in A-Frame, not related to three.js or GLTFLoader.

**Comment by takahirox** [comment]
@PlumCantaloupe Can you reproduce this issue and check if the code I posted above makes the shadow be fine? I wanna move this issue back to A-Frame issue thread once we confirm this's A-Frame issue, not Three.js's.

**Comment by PlumCantaloupe** [comment]
Unfortunately neither yours or the link Don posted above seems to work for me on Apple devices, and I haven't been able to find any loading discrepancies though any kind of refreshing or the like. I will have to try at university to see if a much faster wired connection makes a difference ... 

I also made a gltf loading component mimicking the THREEjs way with no luck (though I could set envMaps at least :) [https://glitch.com/edit/#!/sapphire-patient](https://glitch.com/edit/#!/sapphire-patient)

**Comment by donmccurdy** [comment]
Let's re-open this issue on A-Frame's repository if we have a clear example. 👍
