### ISSUE TITLE
Map textures leak to another object material's maps and break RectAreaLight reflection

### ISSUE THREAD

**Issue by tiborsaas** [mrdoob/three.js#12985]
##### Description of the problem 

I've run into a very strange bug. I'm not sure if the title describes it correctly, because I'm not even sure how to find a grip on the subject.

A picture will describe it better:

![image](https://user-images.githubusercontent.com/342688/34410781-dd1cdd4e-ebd2-11e7-976e-0809bf72ab1a.png)

What you see here is that the `rectAreaLight`'s reflection on the floor is glitchy. The weird thing is that if I turn off the texture loading on the logo, then the glitch effect is gone and the reflection becomes smooth again. 

![image](https://user-images.githubusercontent.com/342688/34410821-2b8644c0-ebd3-11e7-8b96-24f7a0b68fff.png)

To get rid of the glitchy effect, uncomment this line: 

https://github.com/tiborsaas/portfolio-3d/blob/master/src/logo.js#L23

### Run project

`npm run dev` should launch the app once dependencies are installed

### See it in action

https://tiborsaas.github.io/portfolio-3d/glitchy.html

##### Three.js version

- [x] r89

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [x ] Windows (only tested on this)
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Nothing special

**Comment by WestLangley** [comment]
Can you please create a minimal example that demonstrates the problem?

**Comment by tiborsaas** [comment]
Here you go:
https://jsfiddle.net/b65n7xp7/1/

If you uncomment the normalMap, the floor texture changes.

**Comment by WestLangley** [comment]
For one thing, you need to include this:
```html
<script src="js/lights/RectAreaLightUniformsLib.js"></script>
```

**Comment by tiborsaas** [comment]
It fixes the floor, but then the cube's shininess goes away and the normalmap starts to look like a black and white texture.

![image](https://user-images.githubusercontent.com/342688/34419140-7ea57778-ec02-11e7-84eb-7bfdc3e2d4cb.png)

**Comment by tiborsaas** [comment]
Hmmm. It was probably because the light was inside the cube, however there still might a bug somewhere. 

What do you think that that normal map should look like this?

![image](https://user-images.githubusercontent.com/342688/34419342-9f2a27e0-ec03-11e7-8c8c-d043bc023e8d.png)

**Comment by tiborsaas** [comment]
It seems fine, I converted the `RectAreaLightUniformsLib.es6.js` to ES6 and the glitchy effect is now gone.
