### ISSUE TITLE
BufferGeometry: ComputeVertexNormals

### ISSUE THREAD

**Issue by kaktus40** [mrdoob/three.js#12991]
##### Description of the problem

Hello,
I worked with BufferGeometry and I update positions . Also when I use [computeVertexNormals](https://github.com/mrdoob/three.js/blob/dev/src/core/BufferGeometry.js#L675-L794) and the number of position points is different from the previous state, the normal [array](https://github.com/mrdoob/three.js/blob/dev/src/core/BufferGeometry.js#L703) doesn't fit the size of the position array. 
Is it a bad use case (number of position points must be the same) or should there be a correction in the code?

##### Three.js version

- [ ] Dev
- [X] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by Mugen87** [comment]
> Is it a bad use case (number of position points must be the same) or should there be a correction in the code?

The number of position vectors must be the same. `BufferGeometry`  assumes that the item count of its attributes is static and does not change after creation.

**Comment by Mugen87** [comment]
BTW: This manual page (section `BufferGeometry`) might be helpful to you:

https://threejs.org/docs/#manual/introduction/How-to-update-things

**Comment by kaktus40** [comment]
Thanks for the guide. It's clear for me.

**Comment by kaktus40** [comment]
By the way, ``bufferGeometry.drawRange`` commands index array or it only works on position array?

**Comment by Mugen87** [comment]
It depends on whether the geometry is indexed or non-indexed. So if you have no index buffer, `drawRange` refers to the amount of entries in the position buffer.

**Comment by WestLangley** [comment]
@kaktus40 Please TRY before you ask.
