### ISSUE TITLE
VRMLLoader: Support Text Nodes

### ISSUE THREAD

**Issue by DoomTay** [mrdoob/three.js#13002]
##### Description of the problem
[Here](http://hedges.org/thehedges/Ver21.wrl) is one such example of a text node with a "size" field containing only one number.
##### Three.js version

- [x] r89

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Yes, this feature is not supported. Maybe we should rename the issue to "VRMLLoader: Support Text Nodes" or something like that. Besides, the semantic of `size` is different when it's used inside `fontStyle`.

**Comment by DoomTay** [comment]
It seems that VRMLLoader fails to support a few things besides V1. I couldn't get it working with [this](http://hedges.org/thehedges/Ver21.wrl) or [this](http://www.rccad.com/Gallery/Vrml/stratoracer.wrl) or [this](https://web.archive.org/web/20080922201846oe_/http://www.itl.nist.gov/iaui/ovrt/projects/vrml/VRML2/PCAR.wrl) NIST-developed one

It's a shame, because I was hoping to use this as the backbone for a Firefox addon that allows for VRML navigation, saving me the work of having to research and write my own thing

**Comment by bartmcleod** [comment]
VrmParser does not yet support Text, but I'm happy to address the issue following #13402.

**Comment by bartmcleod** [comment]
@DoomTay would you mind to file an issue at the VrmlParser project? https://github.com/bartmcleod/VrmlParser
I am looking into it. The first hurdle with Ver21.wrl seems to be that Switch is not yet supported or even parsed correctly.

**Comment by bartmcleod** [comment]
@DoomTay your example files seem to be full blown games with a lot of interaction, some of which might be supported by the current implementation of VrmlParser. Some of it is not, such as the Script node and route arrays. To be able to fully render these examples using VrmlParser is an interesting and ambituous goal. The challenge we could be facing here extends well beyond supporting the Text node.

**Comment by Mugen87** [comment]
I had a go on  implementing `TextNode` in `VRMLLoader` today. Unfortunately, without success^^. This part of the VRML spec is really hard to map on today's Web APIs. You have to draw the text on a canvas element and then use it as a texture for a plane geometry. However, the sizing of the canvas as well as the correct application of VRML font style definitions when drawing the text is very complex. 

TBH, the amount of code which is necessary to implement full support (or at least a decent one) seems to outweigh the benefits of text nodes.

**Comment by bartmcleod** [comment]
@Mugen87 The text node has alreadt  (limited) support in the vrmlparser project. The VRMLLoader in Three is just an example of how VRML could be used in Three, but actual development effort in this field should go to the vrmlparser project, as this offers better separation of nodes. This makes it easier to add support one node at a time and to improve upon nodes when new ideas come up. It is also fully aware of the VRML node tree, which should make it possible to treat text in more advanced ways. We would however need someone with deep knowledge of fonts to be able to make a viable modern implementation.

**Comment by Mugen87** [comment]
> It is also fully aware of the VRML node tree, which should make it possible to treat text in more advanced ways. 

`VRMLLoader` was rewritten last year. This works now in the loader, too. 

Anyway, I'm fine with advising users to use your vrmlparser project if they need to work with `TextNode` for some reasons.

**Comment by bartmcleod** [comment]
> VRMLLoader was rewritten last year. This works now in the loader, too.
I wasn't aware of this. I have been very busy doing other stuff. It is kinda sad that apparently the two projects diverged in such way that rewrites in one do not benefit the other.

**Comment by Mugen87** [comment]
I think we have discussed this before but `VRMLLoader` should behave like other `three.js` loaders and just parse geometries and materials. It's not its task to parse the whole application that a VRML asset might represent (including script logic, sensors etc.). 

Against this backdrop, it's totally okay when different projects have different focus areas.

**Comment by bartmcleod** [comment]
We did discuss it before and the projects do have different focus areas. However, I think they _could_ share more than they do now. I have separated out the treatment of animation logic and sensors following that discussion, but I do not know in how far this contributed to the development of the loader `VRMLLoader` a year ago, if at all. That would mean duplicated effort I'm affraid.

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/issues/13002#issuecomment-624063402.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Bart McLeod <notifications@github.com>
发送时间：2020-05-05 22:17
主题：Re: [mrdoob/three.js] VRMLLoader: Support Text Nodes (#13002)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

We did discuss it before and the projects do have different focus areas. However, I think they could share more than they do now. I have separated out the treatment of animation logic and sensors following that discussion, but I do not know in how far this contributed to the development of the loader VRMLLoader a year ago, if at all. That would mean duplicated effort I'm affraid.
