### ISSUE TITLE
ShaderMaterial.onBeforeUpdate method

### ISSUE THREAD

**Issue by wdanilo** [mrdoob/three.js#13019]
##### Description of the problem

Feature request.

Can we have ShaderMaterial.onBeforeUpdate function?

Use case:
I'm generating vertex and fragment shaders based on some user-defined properties. Generation is generally cheap, but it would be great if it would happen only when necessary. So when user defines a property, I've got two ways to follow:
  1. I can generate new shaders and set `material.needsUpdate = true` flag (thats what I do now)
  2. I could postpone the generation to the moment the shader is about to update. This way if user sets multiple properties I will generate the shaders once, not many times.

##### Three.js version
- [x] r89

##### Browser
- [x] All of them

##### OS
- [x] All of them

##### Hardware Requirements (graphics card, VR Device, ...)
none

**Comment by WestLangley** [comment]
Can you please provide a live example to demonstrate your use case?

Why do you need to set the `needsUpdate` flag, and why are you not able to control when shaders are created?

**Comment by pailhead** [comment]
>I could postpone the generation to the moment the shader is about to update.

Why not set the flag then?

**Comment by wdanilo** [comment]
@WestLangley if that would be necessary I will create an example, but I will try to explain myself better first.

@pailhead: It's not this optimization I'm looking for.

I've got some objects, that are user defined. These objects are rectangles with shapes defined as SDF functions. User is provided with an API to define how the shape looks like, in particular, it is possible to re-define the shape. Each shape re-definition is just a generation of a shader code. 

What I want to do is to allow user use some public APIs like `object.addCircle(...)` or `object.defineAttribute(...)` and generate the code only when necessary. So the action flow would look like:

  1. User has some object A
  2. User modifies it by using API, like `A.addCircle` or `A.defineVariable`
  3. After each action the flag on material `needsUpdate` is set to true BUT the code is not yet re-generated
  4. Only when Three.js re-generates the material, the code is also generated - this is what I want to achive - instead of generating the code after each user action, to generate it only when it really would be needed.

**Comment by fordhurley** [comment]
I think there are better ways to go about this without changing THREE. One option is to manage your own version of "needsUpdate" and check this from your render loop before rendering. This would be happening next to all the other updates you do each frame (e.g., animation). Of course, I don't fully understand your use case, so I could be missing something.

**Comment by wdanilo** [comment]
@fordhurley youre totally right - I could do it, but then I need to keep some store of all materials used in the scene and iterate over them on each update, which would be double-work if THREE already does it. Including it in THREE would have no performance overhead in comparison to this solution, am I wrong here?

**Comment by Mugen87** [comment]
This feature request was unfortunately never really clear, sorry. The requested live example would have been a big help to evaluate this issue. Based on the current facts, it's seems impossible to suggest a concrete change to the library.

Feel free to reopen the issue if you can better demonstrate your use case. Or even better, make a PR that implements your approach.
