### ISSUE TITLE
LoopRepeat executes an action once too many

### ISSUE THREAD

**Issue by gero3** [mrdoob/three.js#13011]
##### Description of the problem

When I was writing the unit test of AnimationAction, I noticed something I didn't expect. When asking to LoopRepeat a action 3 times, it executes the action 4 times, I think. 
Example: https://jsfiddle.net/wqoLka39/3/

##### Three.js version

- [x] Dev
- [ ] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
This is documented under AnimationAction.repetitions:

> The number of repetitions of the performed AnimationClip over the course of this action. Can be set via setLoop. Default is Infinity.

> Setting this number has no effect, if the loop mode is set to THREE.LoopOnce.

> **Note: The first run is not taken into account. For example: if repetition is set to 2, the total number of executed rounds will be 3.**

**Comment by donmccurdy** [comment]
^I've been surprised by that as well. Not sure if there's another way to phrase the API that would feel more intuitive.

**Comment by bhouston** [comment]
This is confusing.  We should just change the behavior to be what everyone
expects.

Best regards,
Ben Houston
http://Clara.io Online 3d modeling and rendering

**Comment by gero3** [comment]
I agree.
