### ISSUE TITLE
Feature request: Example of complete clean up.

### ISSUE THREAD

**Issue by wrcstewart** [mrdoob/three.js#13012]
It would be useful to have a definitive example of cleaning up objects/scenes/mesh/geometry and any etc's. This would be useful for those that want to carry out changes  dynamically by recreating a mesh.

Please also show when and how any reuse of a structure might be more appropiate. As newbie I'm not sure what is meant by phrases like "reusing" a geometry.

**Comment by wrcstewart** [comment]
Can anyone tell me where I find the feature request Label! ? Can't see it anywhere ....

**Comment by Mugen87** [comment]
There are already two examples which illustrate how to clean up things.

https://threejs.org/examples/?q=memory

BTW: You don't have the permission to set labels in the project.

**Comment by Mugen87** [comment]
Also see #11345

**Comment by Mugen87** [comment]
I'm marking this as a duplicate. Please continue the discussion in #11345 :+1:
