### ISSUE TITLE
Documentation: Filter by Method Names

### ISSUE THREAD

**Issue by loldrup** [mrdoob/three.js#13025]
It seems nothing shows up when I filter on 'triangulateShape' on https://threejs.org/docs/
Is that intended behavior? Can you reproduce?

**Comment by looeee** [comment]
TriangulateShape is in the [ShapeUtils page](https://threejs.org/docs/#api/extras/ShapeUtils). 

Currently the search only works for pages, not internal hrefs within pages. 
It would be great if it also searched within pages, so we could return results for things like:

`threejs.org/docs/#api/extras/ShapeUtils.triangulateShape`

**Comment by Mugen87** [comment]
I'm not sure if it's worth to implement something like a full-text search. I prefer to keep things simple even if we have to live with some limitations. The code base of the docs is already quite big (and maybe too complex).

BTW: I can find the documentation page when i just type into google : _triangulateShape_. Even three.js is not required^^.

**Comment by looeee** [comment]
@Mugen87 I agree that a full text search is not necessary - however, each class's parameters and methods are included as internal hyperlinks and it would be useful to be able to search these.

For example, it would be great to easily see which classes override an inherited method such as [Object3D.clone](https://threejs.org/docs/#api/core/Object3D.clone). There is currently no easy way to check this. 
But if you could just search the docs for "clone" and have every class with a clone method show up then checking this would be simple.

**Comment by Mugen87** [comment]
I've renamed the issue so it describes the actual feature request 😇

**Comment by haroldiedema** [comment]
Reference PR #13027

**Comment by Mugen87** [comment]
Merging into #19342.
