### ISSUE TITLE
Getting map files from the editor?

### ISSUE THREAD

**Issue by nuliknol** [mrdoob/three.js#13028]
Could you add a feature to the editor, to download map files ?
For example, this mesh, has 3 maps (Map,Rough Map, and Env Map):
https://threejs.org/editor/#file=https://mrdoob.neocities.org/021/app.json
however , if I click on the texture icon it asks me to upload a file, but what I want is to download it.
Is this possible to implement?
In the mean time, where exactly the URL is stored in the app.json,  so I could download it and use in my own mesh?

**Comment by Mugen87** [comment]
> In the mean time, where exactly the URL is stored in the app.json, so I could download it and use in my own mesh?

The images are stored as a Base64 encoded string. You can manually extract the string and decode it (e.g with an [online converter](https://codebeautify.org/base64-to-image-converter)).

**Comment by mrdoob** [comment]
You can use the browser developer tools for that. In the case of Chrome:

<img width="1254" alt="screen shot 2018-01-04 at 4 09 05 pm" src="https://user-images.githubusercontent.com/97088/34590138-b2ee6816-f169-11e7-82f4-43de84575c47.png">

**Comment by nuliknol** [comment]
thanks mrdoob!
