### ISSUE TITLE
Camera 这个怎么设置？

### ISSUE THREAD

**Issue by lettywiterock** [mrdoob/three.js#13036]
在nodeThreeObject 添加了 Camera？ 使用 array[]：还是function
例：
[
new THREE.MeshLambertMaterial({
            color: Math.round(Math.random() * Math.pow(2, 24)),
            transparent: true,
            opacity: 0.75
          }),
new THREE.PerspectiveCamera(75, window.innerWidth/window.innerHeight, 0.1, 1000)
]

if 需要点击事件 -->  onNodeClick（）
直接修改：new THREE.PerspectiveCamera(75, window.innerWidth/window.innerHeight, 0.1, 1000)
这个？
help me ... (っ °Д °;)っ

**Comment by looeee** [comment]
Please ask help questions on the forum: https://discourse.threejs.org/

请在论坛上提问帮助: https://discourse.threejs.org/

You'll probably get a better response if you ask in English too, even using [automatic translation](https://translate.google.com).
