### ISSUE TITLE
feature request: support points in obj

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#13031]
While working with the client files exported from JNetCAD, I had this error:
![screen shot 2018-01-03 at 20 00 27](https://user-images.githubusercontent.com/242577/34535042-fabbd0e2-f0c0-11e7-9119-bea8660eceb0.png)

which was caused by following group:
![screen shot 2018-01-03 at 19 59 38](https://user-images.githubusercontent.com/242577/34535067-0e7bb6b0-f0c1-11e7-9e86-6aa7e154ad72.png)

I think 3js could easily create THREE.Points for these, but if not, at least create dummy Object3D and do not throw errors?

**Comment by richardmonette** [comment]
@mrdoob I've been working on a PR to implement this feature. Does this warrant its own new example? 

https://github.com/mrdoob/three.js/pull/13060

**Comment by makc** [comment]
since I didn't know when someone will have time to implement it, I used quick hack:
```
				} else if ( lineFirstChar === 'p' ) {

					// these should have been THREE.Points
					// for quick solution, we hack these in as THREE.LineSegments

					var pointParts = line.substring( 1 ).trim().split( " " );
					var lineVertices = [], lineUVs = [];

					for (var pi = 0; pi < pointParts.length; pi++) {
						lineVertices.push (pointParts[pi]);
						lineVertices.push (pointParts[pi]);
					}

					state.addLineGeometry( lineVertices, lineUVs );
```

not sure if it's useful to anyone.

**Comment by makc** [comment]
ok, it seems #13060 was merged
