### ISSUE TITLE
About the problem of superposition of transparent materials

### ISSUE THREAD

**Issue by openforus** [mrdoob/three.js#13044]
##### Description of the problem
When two transparent materials plane are superimposed, they are viewed from different directions then Can't see through each other. depthWrite  depthTest is set to true.
[ cube  Look from  the front](https://pan.baidu.com/s/1jIy65BS)
can see the back plane  

[ cube look  from the Front side ](https://pan.baidu.com/s/1i4SK2pf)
can see the back plane pass through the front plane

[ cube  Look   from the  top back](https://pan.baidu.com/s/1gfzs9V1)
can't see the back plane and side plane pass through the back plane

[ cube  Look  from  the back side ](https://pan.baidu.com/s/1jIajYJW)
can't see the back plane and side  plane pass through the back plane

##### Three.js version

r88

##### Browser
 Chrome
##### OS
Windows
#####graphics card
gtx645

**Comment by looeee** [comment]
@openforus please direct help questions to the forum: https://discourse.threejs.org/

**Comment by openforus** [comment]
@looeee  @openforus   Thanks 
 I found the reason for the problem,Should be set
material.alphaTest = 0.5;
