### ISSUE TITLE
Incorrect program output when Material.transparent=true is set.

### ISSUE THREAD

**Issue by wdanilo** [mrdoob/three.js#13042]
##### Description of the problem

Here is a sample scene:
https://jsfiddle.net/s3rjfcc3/1/

If you move mouse over the ball, you can see values printed to console: `[5, 37.5, 30, 5]`, however, the shader outputs following values instead: `[1.0,7.5,6.0,5.0]`. This problem occurs when we are using `transparent:true` in the Material settings. Without it, it runs correctly.

##### Three.js version

- [x] Dev
- [x] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by pailhead** [comment]
Might be related - https://stackoverflow.com/questions/17981163/webgl-read-pixels-from-floating-point-render-target

**Comment by wdanilo** [comment]
Ok, guys on the three.js slack just discovered what it is. It is alpha premultiplication!

**Comment by pailhead** [comment]
there's a three.js slack?

**Comment by manthrax** [comment]
@WestLangley The three.js slack started by @repsac has been getting a fair amount of use over the last year.. If you want to direct help questions here: https://threejs-slack.herokuapp.com/

**Comment by WestLangley** [comment]
@manthrax Thanks for the tip. SO seems to have fallen out of favor somewhat.

/ping @Mugen87 Maybe we should link to slack, too.

**Comment by mrdoob** [comment]
There is a link to slack right in https://threejs.org/ 🤓

**Comment by WestLangley** [comment]
:-)

A link [here](https://github.com/mrdoob/three.js), too, may be helpful -- and perhaps a help section linking to all the help sites on the [Wiki](https://github.com/mrdoob/three.js/wiki).
