### ISSUE TITLE
GLTFLoader: Simplified examples

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#13041]
The current glTF examples are functioning as unit tests more than anything else – the code is complex to support all of the options and extensions, has a custom GUI, and isn’t a very easy reference for developers.

I’d like to clean that up: show just a few nice-looking example models and either put each example in a new page (as COLLADA does) or use dat.gui and reduce the complexity of the code.

But from a development perpective it’s helpful having all of the models and extensions to test... What’s a good way to organize this? Proposed:

- `loaders` / `gltf`/ (simple example with one model)
- `loaders` / `gltf` / `animation` (simple example with one animated model)
- `loaders` / `gltf` / `advanced` (complex example with many models and extension variations)

/cc @takahirox

**Comment by Mugen87** [comment]
I like this proposal. Three examples with different emphases (basic, animation, advanced) sounds reasonable.

**Comment by takahirox** [comment]
I was gonna propose the same thing.
The current glTF example is too complicated and we should simplify.

I'll think again how to organize tomorrow (I'm about to sleep now!) but personally prefer less examples for good maintenance. Maybe "simple example with one animated model" and, if necessary, another one for develop purpose. (I think animated one can cover non-animated one)

**Comment by mrdoob** [comment]
👍

**Comment by harry-liu** [comment]
pls show how to manage the memory when switch models in new gltf examples

**Comment by looeee** [comment]
@harry-liu that's not the purpose of the GLTF example. 

See these examples for details of memory management: https://threejs.org/examples/?q=memory

**Comment by harry-liu** [comment]
@looeee thanks, but still dont know how to use gltf loader to manage memory

**Comment by looeee** [comment]
@harry-liu GLTFLoader doesn't manage memory, it just loads models. If you need any more help with this please ask over on the forum: https://discourse.threejs.org/

**Comment by takahirox** [comment]
How about making only one simple example using Project 'polly'.

Here is the master? https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly

Users can see (almost?) all glTF 2.0 features.

Adding another model (or example) for extensions would be also ok.

**Comment by donmccurdy** [comment]
The issue with Polly is that it's 50MB and (at least on my laptop) can only run at ~45fps. There's also a transparency issue that isn't webgl-friendly.

Here are more examples featured on Sketchfab: https://sketchfab.com/features/gltf

And a bunch more animated ones: https://sketchfab.com/models?features=downloadable+animated+staffpicked&sort_by=-likeCount

We can just pick something with a CC license and include attribution, I assume?

Some ideas in no order:

| name | size | animated | screenshot |
|---|---|---|---|
| DamagedHelmet | 4mb | —  | ![damagedhelmet](https://user-images.githubusercontent.com/1848368/34620874-d705c8e2-f1fb-11e7-87bf-9ac6c695c665.png) |
| guardians_of_the_galaxy | 14mb | ✅  |  ![guardians](https://user-images.githubusercontent.com/1848368/34620943-132d2ba8-f1fc-11e7-897c-f7043c99f469.png) |
| WaterBottle | 9mb | — | ![waterbottle](https://user-images.githubusercontent.com/1848368/34620966-2e68d296-f1fc-11e7-8db1-c13e0987c87f.png) |
| ftm | 55mb | — | ![ftm](https://user-images.githubusercontent.com/1848368/34621006-564c2a38-f1fc-11e7-9f37-590902130480.png) |
| busterDrone | 20mb | ✅  | ![busterdrone](https://user-images.githubusercontent.com/1848368/34621092-a687593c-f1fc-11e7-8cab-804a96698c8a.png) |
| hiih | 12mb | — | ![hiih](https://user-images.githubusercontent.com/1848368/34621105-b1c2a0ae-f1fc-11e7-8706-fc93a2ee5a8c.png) |
| shift_happens | 19mb | ✅  |  ![shift_happens](https://user-images.githubusercontent.com/1848368/34621141-d882cdae-f1fc-11e7-825d-9c540783e7a0.png) |

**Comment by Mugen87** [comment]
I suggest to use models < 10 MB. `DamagedHelmet` would be ideal for a basic example.

**Comment by mrdoob** [comment]
Agreed. I vote for Damaged Helmet too 👍

**Comment by donmccurdy** [comment]
Ok, let's start with that. Maybe later on we add a second example with animation that's under 10mb, for variety. 🙂

**Comment by takahirox** [comment]
Yeah, that's a good start.
