### ISSUE TITLE
Json export corrupted vertices

### ISSUE THREAD

**Issue by MrEveryhand** [mrdoob/three.js#13040]
Good day everyone!

I have next problem:
I exported blender model into json format, which previously I exported from maya fbx format to blender. Also I want to export one morph target with it, but when I do this, three js show me corrupted mesh (see picture below). Without morph target it looks normal, but with it many vertices on my model are pushed to the geometrical center. 

Please answer if someone have any clue and sorry for my low-level english.

![index](https://user-images.githubusercontent.com/34971271/34573114-4e497264-f184-11e7-82b1-703fdee8b674.jpg)

**Comment by Mugen87** [comment]
I guess you already posted this question here. 

https://discourse.threejs.org/t/export-json-from-blender/1567

Github is not intended for help request. I've answered on your question at the forum.
