### ISSUE TITLE
How to generate a compressed .... not working

### ISSUE THREAD

**Issue by rhgrafix** [mrdoob/three.js#13059]
The link on https://github.com/aleeper/three.js 
In this section:
Usage
Download the minified library and include it in your html. Alternatively see “how to build the library yourself.”
takes me to this page:
“https://github.com/mrdoob/three.js/wiki/build.py,-or-how-to-generate-a-compressed-Three.js-file
with a blank comment window.
Link should be: https://github.com/mrdoob/three.js/wiki/Build-instructions
Thanks

**Comment by WestLangley** [comment]
Avoid outdated forks. That one is 5 years old.

Refer to the three.js site, instead: https://github.com/mrdoob/three.js
