### ISSUE TITLE
feature request: convert SVG to Geometry object.

### ISSUE THREAD

**Issue by nuliknol** [mrdoob/three.js#13052]
I think it would be a nice feature if an SVG file could be imported into Geometry object, with extrude option. Right not the only way I can think of loading and extruding an SVG is by importing it from Blender as already extruded geometry in JSON format.

**Comment by WestLangley** [comment]
Did you see [this example](https://threejs.org/examples/webgl_geometry_extrude_shapes2.html)?

**Comment by Mugen87** [comment]
IMO, the example is sufficient for this use case.

**Comment by WestLangley** [comment]
The example could use some refactoring and cleanup, IMHO, if someone is interested.

**Comment by Mugen87** [comment]
385559bf2a42d956f3a0bf0ac5015abb70f10ae6  Just some minor code style improvements but better than before 😊
