### ISSUE TITLE
FBX loader: blender animated models are broken

### ISSUE THREAD

**Issue by pikilipita** [mrdoob/three.js#13051]
While the new example with a mixamo model works great, unfortunately the latest version of the FBX loader is messing up animated models exported from blender.

a fbx loader with the fbx loader as from 28/12/2017:
![screen shot 2018-01-06 at 13 01 38](https://user-images.githubusercontent.com/1799792/34639594-a226e7f4-f2e2-11e7-9418-12838b51551b.png)

the same model loaded with the new fbx loader as from 06/01/2018:
![screen shot 2018-01-06 at 13 01 22](https://user-images.githubusercontent.com/1799792/34639595-b2358b00-f2e2-11e7-9850-3d7f7f2b90d9.png)

I'm attached the cat model here:
[cat exported from blender.fbx.zip](https://github.com/mrdoob/three.js/files/1608747/cat.exported.from.blender.fbx.zip)

I've checked several other fbx exported from blender, they all suffer the same issue.

( tested using threejs 89 )

**Comment by looeee** [comment]
I'm investigating this now. 

Actually your model was not displaying well even with older versions of the loader:

![screenshot-threejs test-2018-01-08-11-57-15-231](https://user-images.githubusercontent.com/5307958/34659426-23de544c-f46b-11e7-88c0-cec058e9a809.png)

**Comment by looeee** [comment]
@pikilipita fixed here: #13061

**Comment by pikilipita** [comment]
Thanks!
I've checked a dozen of animated models with this fix, works like a charm now. Awesome :)

Just a thing: when minyfing the file, I get this error:
SyntaxError: Unexpected token: punc (()
( line 2940 )
maybe you should change the line 2937 to:

parseSubNode: function ( name, node, subNode ) {

**Comment by looeee** [comment]
> I've checked a dozen of animated models with this fix, works like a charm now

Sweet! Great to have a second set of eyes on this, there are only so many models I can test by myself. 

> maybe you should change the line 2937... 

Oops, that's what it should have been already. I'll make a PR.
