### ISSUE TITLE
scene.background affected by tonemapping

### ISSUE THREAD

**Issue by pikilipita** [mrdoob/three.js#13066]
images displayed on the background of the canvas using scene.background are affected by environment maps, in my case, they get darken.

I thought the purpose of the scene background was to display an image on the back of the canvas, but without the need of using an <img> html tag.

In cases like the one below, I would expect the scene background not to be affected in any way by the scene lightning.

![screen shot 2018-01-08 at 14 59 59](https://user-images.githubusercontent.com/1799792/34674096-e719eb06-f484-11e7-8768-ad1dc9161d73.png)

**Comment by WestLangley** [comment]
Can you please provide a live example to demonstrate your issue?

**Comment by pikilipita** [comment]
While doing the example, I found out that is it not directly the envmap that is affecting the scene background, but the:
renderer.toneMapping
and
renderer.toneMappingExposure
values

here's the example:
[http://lune.live/scene_background/](http://lune.live/scene_background/)

**Comment by WestLangley** [comment]
OK, that makes more sense.

Is it acceptable to set a CSS background and set `WebGLRenderer( { alpha: true } ), instead?

**Comment by pikilipita** [comment]
I'm using scene.background to I can make screengrabs of the canvas that include the background.
That's how are generated all the thumbnails on this page:
[https://xr.plus](https://xr.plus)

if the image is outside of the canvas is will be excluded from the screengrab.

**Comment by WestLangley** [comment]
Got it.

Do you require tonemapping in your app?
```javascript
renderer.toneMapping = THREE.NoToneMapping;
```

**Comment by pikilipita** [comment]
Ideally,
I would like to let users adjust the exposure of their environment map, like here:
[https://threejs.org/examples/webgl_materials_envmaps_hdr.html](https://threejs.org/examples/webgl_materials_envmaps_hdr.html)

**Comment by mrdoob** [comment]
As discussed in #14827, backgrounds should be affected by tonemapping. #14856 aligned the behaviour to not be affected but we'll eventually implement the shaders bits so they're affected.
