### ISSUE TITLE
memory consumption of UUID strings.

### ISSUE THREAD

**Issue by aardgoose** [mrdoob/three.js#13069]
##### Description of the problem

UUID generation in Math.js produces strings stored as concatenated strings in Firefox and Chrome.

On Chrome 40bytes are used for each component of the final string,  creating heap overhead.  In my application with thousands of objects this adds up.

For example, Heap size using Chrome

r89 as is: 95MB
r89 with uuid flattened with String().toUpper(): 66MB.

I see similar results using Firefox.

##### Three.js version

- [ ] Dev
- [x ] r89
- [ ] ...

##### Browser

- [x] All of them
- [x ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Pull Request? 😊

**Comment by aardgoose** [comment]
If there isn't a nasty performance hit, considering that uuid generation has been tuned for speed... I'll take a look.

**Comment by takahirox** [comment]
Can lazy UUID generation solve your app case?

**Comment by aardgoose** [comment]
@takahirox  lazy generation would help to some extent, but as more of a scene is explored the memory consumption would still increase. I presume using a getter function to generate uuid's on request.

To test I have replaced the Objects in WebGLAttributes and WebGLProperties with WeakMaps* keyed on the scene objects/attributes directly rather than the uuids., and for testing stubbed out uuid generation.
This works well with no obvious performance hits and the expected reduction in heap use with  large object counts.
 
It may be worthwhile to combine this approach with lazy generation where exporters/editors require uuids?

@mrdoob your thoughts, worthwhile pursuing?

   \* to preserve the current behaviour.

**Comment by mrdoob** [comment]
How many objects are you dealing with? I mean, at what scene graph size this becomes an issue?

**Comment by mrdoob** [comment]
> r89 as is: 95MB
r89 with uuid flattened with String().toUpper(): 66MB.

I missed that, what is `String().toUpper()`?

**Comment by takahirox** [comment]
I'd like to know the total memory consumption on your app and the percentage of memory consumption for `uuid`. Feeling like 40bytes/object isn't too huge...

**Comment by takahirox** [comment]
904 bytes per uuid(36chars)? That's kinda surprising...

**Comment by takahirox** [comment]
`.toUpperCase()` technique seems very interesting.

I evaluated memory consumption with the following code.

    <html>
    <head>
    </head>
    <body>
    <script src="https://rawgit.com/mrdoob/three.js/r89/build/three.js"></script>
    <script>
    var num = 0x10000;

    var array = [];

    for ( var i = 0; i < num; i ++ ) {

        //array.push( THREE.Math.generateUUID().toUpperCase() );
        array.push( THREE.Math.generateUUID() );

    }
    </script>
    </body>
    </html>

`610 Bytes` per uuid with `THREE.Math.generateUUID()` while `74 Bytes` per uuid `THREE.Math.generateUUID().toUpperCase()` on my Windows10 + Chrome.

`74 Bytes` per 36 chars sounds very reasonable.

--------

detail:

4.3MB for Three.js itself on heap. (heap where I comment out the loop)
42.4MB with `THREE.Math.generateUUID()` on heap, 610B (= (42.4MB - 4.3MB) / 0x10000) / uuid
8.9MB with `THREE.Math.generateUUID().toUpperCase()` on heap, 74B (= (8.9MB - 4.3MB) / 0x10000) / uuid

**Comment by aardgoose** [comment]
Hi, nice.

I got 904 from looking at heap info and counting counting the shallow size allocations in the chain.  May have mis-counted (also Chrome  on Win10 ) Chrome 63 rather than bleeding edge, 

You see similar effects though. 74 sounds OK, looking at heap dumps looks like there is a fixed overhead and then the final allocation is in multiples of fixed sized buckets ( multiples of 8) which 74 isn't but there is probably other overheads/noise in the stats.

**Comment by mrdoob** [comment]
Hmm... I don't understand how `toUpperCase()` would make trigger less memory consumption. Do you see the same effect with Firefox?

**Comment by aardgoose** [comment]
I did see similar issues in firefox of similar size though I didn't dig as deep.

the original uuid strings are stored as a linked list arrangements of pointers to the original strings in the LUT rather than a new memory allocation for the complete string.  However the list arrangement structures take up a lot more space, as the string is build up in small segments there are about 12 of these linking objects.  The toUpperCase() code ensures that String() assumes the original string is being modifed so a new copy is created rather than another ref to the original string (that's my assumption anyway and the heap captures so this change in storage (concat strings show up as a separate class of objects).

**Comment by takahirox** [comment]
As @aardgoose this's JavaScript strings memory layout topic.

I'm not so familiar with that, but the following is my rough understanding.

For example, uuid "D30D4BC2-4BAE-49FF-8A3F-3F9A4467A0FA" layout in low-layer is represented as linked list, like

    // more precisely, not the raw string but pointer to LUT of generateUUID()?
    'D3' -> '0D' -> '4B' -> ...

because of `generateUUID()` logic, concatenating strings in LUT.

https://github.com/mrdoob/three.js/blob/dev/src/math/Math.js#L11

And seems like `.toUpper/LowerCase()` allocates new consecutive memory space "D30D4BC2-4BAE-49FF-8A3F-3F9A4467A0FA". Therefore, memory consumption will be reduced by removing overheads.

In JS code layer, even if the two strings looks the same the memory layout can be different in low-layer. `.toUpper/LowerCase()` tech optimizes it.

I hope JS engine optimizes well and we won't need this hacky tech in the future.

**Comment by mrdoob** [comment]
So a solution would be to remove the `toUpperCase()`?

**Comment by makc** [comment]
@mrdoob I think they want one more toUpperCase on generateUUID return expression

**Comment by mrdoob** [comment]
Moving it then?

**Comment by aardgoose** [comment]
Yes, sorry if that wasn't clear,

return String(   <uuid expression>  ).toUpperCase();

You can remove the toUpperCase() when setting up the lut, it doesn't change the end result, The conversion on the returned expression happens with it there or not.

The rather hacky nature is why I proposed the WeakMap solution as well, avoids the costs of uuid generation unless they are required, and removes the need for uuid's in a lot of situations all together.

**Comment by Usnul** [comment]
It might be worth mentioning that 16 bytes are required to represent UUID. It might also be of interest to note that new Uint8Array(16) would provide just that, without any necessity for resizing, reallocating or indeed, even string manipulation.

**Comment by makc** [comment]
@Usnul I tried that [here](https://github.com/mrdoob/three.js/pull/13094#issuecomment-357077546), it was 15 times slower.

**Comment by takahirox** [comment]
@mrdoob I think we should add this to the r91 milestone, we should quickly solve this issue.

**Comment by mrdoob** [comment]
@takahirox I didn't think there was a solution...? Seemed like a V8 thing...?

**Comment by Usnul** [comment]
@makc I have a bit of a counter to what you have written:
https://jsfiddle.net/Travnik/3guqr5va/11/

numbers:
generateUUID: 347.219970703125ms <- base
generateUUID2: 1697.90185546875ms <- your version
generateUUID3: 191.04296875ms <- my version, using 16 byte array instead of your 36

The main problem is in materializing the string. Actual generation is pretty quick and compact.

**Comment by takahirox** [comment]
@mrdoob Probably no *perfect* solution but there may be better situation. I'm gonna follow up the discussion and try some ideas soon. In my mind, there're two options now. Using "Number tech" mentioned in #13094 or reverting generateUUID.

IMO huge memory consumption can lead slow performance, we should fix.

**Comment by makc** [comment]
@Usnul nice try, however your UUID3's toString() is again a bunch of strings +ed together. This whole issue exists because doing so wastes lots of memory.

**Comment by Usnul** [comment]
@makc 
I didn't make myself clear.

There are 2 things I propose which are separate which I believe this solution achieves:
 - use minimal amount of memory to *represent* UUID
 - avoid materializing strings, as that is not relevant for the purposes of UUID, except maybe debug and serialization.

**Comment by makc** [comment]
ah well, of course, if you modify 3js to never call toString unless actually needed (as in during the serialization), this issue will go away

**Comment by aardgoose** [comment]
There is a pending PR #13102 that removes the need for UUID in the core rendering process and is faster on Chrome and FF. 

I observed the heap bloat in FF as well as Chrome/V8, I didn't check for Edge.

I think UUIDs could then be removed from BufferAttributes after this change which would give a significant saving in UUID memory when a lot of geometries are in use. (Unless UUIDs for BufferAttributes are used in any of the export formats, but I don't believe they are).  Also UUID's could be removed from WebGLRenderTarget, but obviously not a big win.

I posted a previous PR that used lazy UUID generation which could apply on top of this (the current implementation would require a simple polyfill for IE).  The lazy approach moves the cost of UUID creation to when UUID's are used so export operations will be slightly slower.

**Comment by takahirox** [comment]
I evaluated some flattening techniques mentioned in https://github.com/davidmarkclements/flatstr but they're as slow as `String.toUpperCase()`. `String.toUpperCase()` seems a bit faster than them. I speculate `String::Flatten` in JS engine isn't fast regardless how we trigger. Seems like we can't avoid tradeoff between performance and memory consumption.

In short term, we need to determine which one should take priority. Personally I prefer lower memory consumption because uuid generation performance affects only initialization while memory consumption has an impact all running time.

In long term, I agree with @aardgoose. I wanna encourage lazy UUID generation and uuid reference removal except for serialization.

(In further longer term, we could expect JS engines optimization will improve.)

**Comment by takahirox** [comment]
Performance

| generateUUID | Chrome | FireFox Nightly |
| ---- | ---- | ---- |
| r87 | 1300ms | 800ms |
| r90 | 300ms | 400ms |
| r90 + .toUpperCase() | 600ms | 800ms |

**Comment by takahirox** [comment]
Total heap size comparison with 5000 objects on Windows.

| revision | Chrome | FireFox Nightly |
| ---- | ---- | ---- |
| r87 | 72.2MB | 73.20MB |
| r90 | 78.8MB | 78.75MB |
| dev | 77.4MB | 72.60MB |
| dev + .toUpperCase() | 69.8MB | 71.01MB |

In dev, @aardgoose has removed `.uuid` from some modules so total heap size in dev is a bit smaller than r90's. And by using `.toUpperCase()` we can reduce further 10%.

(The number of dev + FireFox Nightly seems weird... Why it's so small?)

	var container, stats, controls;
	var camera, scene, renderer, light;

	init();
	animate();

	function init() {

		container = document.createElement( 'div' );
		document.body.appendChild( container );

		camera = new THREE.PerspectiveCamera( 45, window.innerWidth / window.innerHeight, 0.25, 20 );
		camera.position.set( -1.8, 0.9, 2.7 );

		controls = new THREE.OrbitControls( camera );
		controls.target.set( 0, -0.2, -0.2 );
		controls.update();

		scene = new THREE.Scene();

		// objects
		var num = 5000;

		for ( var i = 0; i < num; i ++ ) {

			var mesh = new THREE.Mesh(
				new THREE.BoxBufferGeometry( 0.01, 0.01, 0.01 ),
				new THREE.MeshStandardMaterial()
			);

			scene.add( mesh );

		}

		renderer = new THREE.WebGLRenderer( { antialias: true } );
		renderer.setPixelRatio( window.devicePixelRatio );
		renderer.setSize( window.innerWidth, window.innerHeight );
		container.appendChild( renderer.domElement );

		window.addEventListener( 'resize', onWindowResize, false );

		// stats
		stats = new Stats();
		container.appendChild( stats.dom );

	}

	function onWindowResize() {

		camera.aspect = window.innerWidth / window.innerHeight;
		camera.updateProjectionMatrix();
		renderer.setSize( window.innerWidth, window.innerHeight );

	}

	//

	function animate() {

		requestAnimationFrame( animate );
		renderer.render( scene, camera );
		stats.update();

	}

**Comment by Usnul** [comment]
There are at least 2 sides. And i don't quite understand the purpose here:

- speed
- memory footprint

I suggested solution that is both fast (i believe it's the fastest so far, about 50% of the next best thing) and takes minimal amount of space: 16 bytes per UUID. What are the other considerations?

**Comment by takahirox** [comment]
I think your solution is fitting to lazy uuid generation. I'm thinking very similar one (almost same) for lazy uuid generation we do after we remove all `.uuid` references from Three.js core and `examples/` except for serialization.

    Object.defineProperties( Object3D.prototype, {

        _uuid: {
            value: null,
            writable: true
        },

        'uuid': {

            get: function () {

                if ( this._uuid === null ) {

                    this._uuid = generateByteArray();

                }

                return bytesToString( this._uuid );

            },

            set: function ( value ) {

                this._uuid = stringToBytes( value );

            }

        }

    } );

With this idea, probably we need to announce that `.uuid` shouldn't be referenced so often (each animation frame).

Doing this a bit too early now, because some examples and user apps refer `.uuid` each animation frame.

**Comment by mrdoob** [comment]
It may be better to invest all these energies in implementing Instancing instead. In a way, it solves this problem too.

**Comment by takahirox** [comment]
Yeah, that could be one of the good solutions in long term.

Regarding in short term, I prefer `.toUpperCase()` solution because

> In short term (r91, r92), we need to determine which one should take priority. Personally I prefer lower memory consumption because uuid generation performance affects only initialization while memory consumption has an impact all running time.

change is very easy and 10% memory consumption reduction sounds good to me.

What do you think?

**Comment by mrdoob** [comment]
Yeah, sounds good to me. We can merge and test during the `r92` cycle.

**Comment by takahirox** [comment]
So let's reopen #13094

> It may be better to invest all these energies in implementing Instancing instead

I'm also very interested in more use of instancing in Three.js. Is #10750 the hottest thread about instancing?

**Comment by aardgoose** [comment]
closed now since uuids either removed or flattened.

**Comment by mrdoob** [comment]
Seems like we're not alone... https://github.com/kelektiv/node-uuid/pull/267

**Comment by aardgoose** [comment]
Interesting .. I'm not sure i'd class it as a bug, just a corner case concatenating lots of small strings that uuid generation hits where v8 is optimised for more general case of generally larger strings.

Out of curiosity I had a look at the v8 source code, what i _think_* it does is first allocate a small head object for the initial string, and copy the concatenate strings into this initial object until it is full, after that the additional parts are left in place and the string changed to be more or less a linked list of this first object and the original string sources, which is pretty much what you see in the heap dumps.

* from reading C++ heavily obscured with macros writing intermediate code stub assembly, so may be entirely wrong.

**Comment by makc** [comment]
> what's the option to disable UUID generation?

something like
```js
var base = "@!#$<", count = 0;
THREE.Math.generateUUID = function () {
   count++; rerurn base + count;
}
```

> why generating UUIDs in the first place instead of a simple auto-incremented number?

I think I have asked before, and they gave me some bullshit reason, like some other code breaks if you dont (so instad of fixing the problem on that end they carry on with UUIDs)

**Comment by mrdoob** [comment]
TIL that some browsers now have `crypto.randomUUID()`:

https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

**Comment by mrdoob** [comment]
Btw, I learnt that from Safari Technology Preview 132 release notes:

https://webkit.org/blog/11971/release-notes-for-safari-technology-preview-132/

**Comment by aardgoose** [comment]
Interesting

Also in development for FF https://bugzilla.mozilla.org/show_bug.cgi?id=1723674
