### ISSUE TITLE
THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values. 

### ISSUE THREAD

**Issue by karuppasamy20** [mrdoob/three.js#13062]
camera = new THREE.PerspectiveCamera( 27, window.innerWidth / window.innerHeight, 5, 3500 );
				camera.position.z = 2750;
				scene = new THREE.Scene();
				scene.background = new THREE.Color( 0x050505 );
				scene.fog = new THREE.Fog( 0x050505, 2000, 3500 );
				//
				var particles = 500000;
				var geometry = new THREE.BufferGeometry();
				var positions = [];
				var colors = [];
				var color = new THREE.Color();
				var n = 1000, n2 = n / 2; // particles spread in the cube
				// for ( var i = 0; i < particles; i ++ ) {
				// 	// positions
				// 	var x = Math.random() * n - n2;
				// 	var y = Math.random() * n - n2;
				// 	var z = Math.random() * n - n2;
				// 	// positions.push( x, y, z );
				// 	// colors
				// 	var vx = ( x / n ) + 0.5;
				// 	var vy = ( y / n ) + 0.5;
				// 	var vz = ( z / n ) + 0.5;
				// 	color.setRGB( vx, vy, vz );
				// 	colors.push( color.r, color.g, color.b );
        //   // console.log('message',colors);
        //   // if(i==3)
        //   //   break;
				// }
				geometry.addAttribute( 'position', new THREE.Float32BufferAttribute( cart[1], 3 ) );
				geometry.addAttribute( 'color', new THREE.Float32BufferAttribute(  cart[2], 3 ) );
				geometry.computeBoundingSphere();
				//
				var material = new THREE.PointsMaterial( { size: 15, vertexColors: THREE.VertexColors } );
				points = new THREE.Points( geometry, material );
				scene.add( points );
				//
				renderer = new THREE.WebGLRenderer( { antialias: false } );
				renderer.setPixelRatio( window.devicePixelRatio );
				renderer.setSize( window.innerWidth, window.innerHeight );
				container.appendChild( renderer.domElement );
				//
				stats = new Stats();
				container.appendChild( stats.dom );
				//
				window.addEventListener( 'resize', onWindowResize, false );

**Comment by looeee** [comment]
Please direct help questions to the forum: https://discourse.threejs.org/
