### ISSUE TITLE
Adding a computeCurvature function to BufferGeometryUtils

### ISSUE THREAD

**Issue by sneha-belkhale** [mrdoob/three.js#13074]
Hey all,
I've been creating some animations in three.js, and had the idea that having a curvature attribute in my bufferGeometry could lead to some interesting shader effects. 
I made a function that essentially takes in a bufferGeometry and computes a curvature attribute based on a vertex point and it's neighboring point positions and normals (using this formula, but for 3D https://computergraphics.stackexchange.com/questions/1718/what-is-the-simplest-way-to-compute-principal-curvature-for-a-mesh-triangle )

I think this could be a useful function to add to BufferGeometryUtils (along with computeTangents).

Let me know if y'all think this could be interesting, and I'll commit my function to BufferGeometryUtils for you all to check out :)

(fragment shader from curvature element value test)
<img width="411" alt="screen shot 2018-01-09 at 10 04 17 am" src="https://user-images.githubusercontent.com/17795014/34730281-89eb6982-f524-11e7-9d2a-c85e05f06f4f.png">

Best,
Sneha

**Comment by mrdoob** [comment]
That's interesting. I think we could start with a example for it?

**Comment by WestLangley** [comment]
The local curvature of a mesh must be approximated -- or inferred -- and there are a variety of proposed methods for doing so. I don't think we need to include a particular curvature method in the utils. But as @mrdoob said, it could possibly be the basis for an interesting shader in one of the examples.

**Comment by sneha-belkhale** [comment]
@mrdoob  @WestLangley, makes sense, I'll clean up my example and post it here
