### ISSUE TITLE
BufferLoader for loading .buf files

### ISSUE THREAD

**Issue by darshithedpara** [mrdoob/three.js#13078]
> hello guys i came up with new idea…

i facing major problem when i want to load **300Mb > object** file so i thought

first of all we divide our object into several parts like :

1. mashes.buf
2. transforms.buf
3. bounds.buf
4. faces.buf
5. faces16.buf
6. vertices.buf
7. normals.buf
8. uvs0.buf
9. uva1.buf

then we create **queueAjaxGet** for calling this small chunks one by one and load into scene…

it would be very useful and mobile device also may not crashes anymore…

**any suggestion where to start ?**

thanx in advance :slight_smile: @mrdoob

**Comment by Mugen87** [comment]
Crossposting: https://discourse.threejs.org/t/new-feature-request-bufferloader-in-three-js/1591

Closing this issue in favor of the forum thread.

**Comment by pailhead** [comment]
Ow :( why only a slight smile for mrdoob?
