### ISSUE TITLE
I have some questions about r81 to r88

### ISSUE THREAD

**Issue by BadmasterY** [mrdoob/three.js#13095]
My previous project used r81, but recently my team wanted to change the version to r88. However, we have encountered some problems in this process. We hope that we will not change the original project and use r88 directly. So we want to use jQuery. GetScript () to dynamically replace r81, but jQuery is wrong. The error code is as follows:

parsererror

TypeError: Cannot set property AudioContext of #`Object` which has only a getter.

However, we soon found that r81 can replace r88 dynamically, which is really amazing! So I want to know if there's any good way to get the high version to cover the low version.

**Comment by Mugen87** [comment]
Can you please provide a simple [live example](https://jsfiddle.net/f2Lommf5/) in order to show the problem?
