### ISSUE TITLE
Loading FBX, loadTextures expecting an object where it's an array

### ISSUE THREAD

**Issue by Benjy1979** [mrdoob/three.js#13098]
##### Description of the problem
Loading in an FBX file, but the "textureNode" variable is an array of textures rather than just one.
The FBX is here:
http://www.articad.biz/fbx/Kitchen2.zip
http://www.articad.biz/fbx/images.zip
```
fbx_loader.html:71 1% downloaded
fbx_loader.html:71 65% downloaded
fbx_loader.html:71 100% downloaded
FBXLoader.js:2965 THREE.FBXLoader: FBX binary version: 7400
FBXLoader.js:386 Loading G & R Kitchen.fbxDiffuse_8.png
fbx_loader.html:66 G & R Kitchen2.fbx 2 3
fbx_loader.html:75 TypeError: Cannot read property 'FileName' of undefined
    at loadTexture (FBXLoader.js:346)
    at parseTexture (FBXLoader.js:311)
    at parseTextures (FBXLoader.js:297)
    at THREE.FBXLoader.parse (FBXLoader.js:104)
    at Object.onLoad (FBXLoader.js:53)
    at XMLHttpRequest.<anonymous> (three.js:30794)
```
##### Three.js version

- [ ] Dev
- [ ] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
@Benjy1979 did you find out what the problem was?

**Comment by Benjy1979** [comment]
Yeah, old version! I had taken the version from the samples instead of downloading the whole threejs folder.
