### ISSUE TITLE
Make unrollLoops optionally available for THREE.ShaderMaterial 

### ISSUE THREAD

**Issue by Aadjou** [mrdoob/three.js#13090]
**Problem**
- We use shader code from the `THREE.MeshPhongMaterial` in a `THREE.ShaderMaterial`
- The results are the same, except on Macbooks with radeon cards, where shadows are missing
- This is caused by loops in the shadow shader chunks
- If we force the [unrollLoops in WebGlProgram][WebGlProgram] to execute for our ShaderMaterial, we get correct results
- See [Original Issue][Original Issue 3d.io] on 3d.io for further information

**Design Questions**

- Why does the condition in [line 509][WebGlProgram] exclude shader materials?
- Why does it not exclude raw shader materials?

Right now, the .isShaderMaterial, .isRawShaderMaterial etc. are arbitrary flags that do many different things in the WebGlProgram and in other places, and the original intent is not comprehensible.

**What's next?**
We would like to solve this edge caseand make a PR so that we can avoid the dirty workaround we are currently using, but we also think being able to unrollLoops for ShaderMaterial can be essential for the usability thereof.

How should we go about this? We would first like to understand what is the reason for the status quo.

One idea was to implement an optional flag in the material prototype definition to replace the condition 
(eg. Material.prototype.unrollLoops)

Usually I would not suggest to add a flag for something like this, but we need a way to toggle the unroll in the _WebGlProgram_ from the material definition or enable it for all ShaderMaterials.

Curious to hear other great ideas!

[Original Issue 3d.io]: https://github.com/archilogic-com/3dio-js/issues/38#issuecomment-356644954
[WebGlProgram]: https://github.com/mrdoob/three.js/blob/949690710f25127869a60a3762b638feb0c60c0c/src/renderers/webgl/WebGLProgram.js#L509

**Comment by AVGP** [comment]
I think this is an interesting discussion to have - how can we enable reusing shader chunks without copy&paste (which will eventuall fall behind upstream)? Loop unrolling definitely is something that is probably needed (and done in a RawShaderMaterial, but not ShaderMaterial) - so what's the official way forward here?

**Comment by Mugen87** [comment]
Related issue #12312

**Comment by Aadjou** [comment]
@Mugen87 thank you for the reference!
@AVGP this PR was not merged.
https://github.com/mrdoob/three.js/pull/12323

**Comment by Mugen87** [comment]
Right now there are two possible solutions:

- Add something like `unrollLoops` as a property to `ShaderMaterial`
- Custom shaders have to set a `define`(e.g. `UNROLL_LOOPS`) to force the loop unrolling

TBH, i'm fine with both solutions. It's just important to expose the control of loop unrolling to the user for custom shaders in some way...

**Comment by WestLangley** [comment]
>Right now there are two possible solutions.
>>Custom shaders have to set a define(e.g. UNROLL_LOOPS) to force the loop unrolling

DEFINES are not appropriate as a solution. This flag is not set in the shader.

**Comment by Mugen87** [comment]
I've meant it like that 56da7308335495b082576ea5fe8796ae9ac8c592

**Comment by WestLangley** [comment]
Yes, I understand. Sorry, @Mugen87, I should have made it clear I was stating an opinion, not a fact. I need to be more careful. :)

This is all handled on the CPU. Defines are injected into the shader code, so I think your flag suggestion is a better API.

**Comment by mrdoob** [comment]
I think I prefer the API in #12323.
Unfortunately I can't merge that PR because the branch the PR points to has been deleted.

**Comment by Aadjou** [comment]
So how should we proceed? @Mugen87 should we reopen #12323? (or recreate it?)

**Comment by Mugen87** [comment]
We should focus on your PR #13124

**Comment by Mugen87** [comment]
There is now a third option :blush: #13140

**Comment by Aadjou** [comment]
sounds great to me!
that's exactly why I made this issue, because it's a design decision. 
What do you think of option 3 @WestLangley @AVGP

**Comment by Mugen87** [comment]
> The "i" variable is still required, right?

Yes. It's still part of the regular expression.

> i assume unroll loops for nested loops is not supported?

Correct.

> where should this be documented?

Maybe we can enhance the doc pages for [ShaderMaterial](https://threejs.org/docs/index.html#api/materials/ShaderMaterial) and [RawShaderMaterial](https://threejs.org/docs/index.html#api/materials/RawShaderMaterial).
