### ISSUE TITLE
Lookat flipping direction (bug?) 

### ISSUE THREAD

**Issue by FutureCake** [mrdoob/three.js#13093]
##### Description of the problem

I have the following scene visable here: http://gravient.thomashoek.com/drag_example/

In the initial mode the text looks at the mouse. but when you make sertain mouse movements the text seems to flip the direct of looking at the mouse. As far as i figured out this happens when the mouse crosses the middle of the canvas.

A quick in depth explanation of the problem: So when the mouse is at the top of the screen the mesh looks at the bottom of the screen. And this is the same for all directions.

But when you move the mouse again in a certain undefined manner the problem fixes it self.

I am not sure if this is a bug or just me not understanding something. But i have used three js a bunch of times and never experienced this before. So that is why i thought i would be useful ask / notify here. 

i will add a file containing all my javascript. So you can try to recreate the problem yourself. Or maybe see what is happening in the code. 

[Archive.zip](https://github.com/mrdoob/three.js/files/1623862/Archive.zip)

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Sorry, this is not a help site. If you can demonstrate a bug, that is a different matter. Perhaps you can try the forum.
