### ISSUE TITLE
Reset mesh after animation, to the loading position

### ISSUE THREAD

**Issue by MarcRibguth** [mrdoob/three.js#13097]
I'm trying to set back the mesh to the T-pose, after the animation stoped. There are four skinned meshes on this object. And if i call on all skinned meshes .pose() it will destroy the pose compled. The rigth mesh has the name "Boy01_Brows_Geo". And some animated objects don't have skinned meshes to begin with. Is there a easy way to get the Object back to its loading state? Or else I need to find the right mesh for calling .pose() and find a solushen to set the other meshes back. The methode I use at the moment, only works with some animations from mixamo.com and skinned meshes. And it's ugly:

    object.traverse(function (child) {

      if (child instanceof THREE.Mesh && child.isSkinnedMesh 
        && child.geometry.FBX_Deformer.bones[0].position.x != 0
        && child.geometry.FBX_Deformer.bones[0].position.y != 0
        && child.geometry.FBX_Deformer.bones[0].position.z != 0) {
  
        child.pose();
      }

    })

Reloading the object is not an option. There must be an easier way to set the object back to the start. (The loading pose is not part of the animation)

- [ ] Dev
- [x] r89 and the FBXLoader from the Dev Branch (#13063)

**Comment by MarcRibguth** [comment]
Here the model 
[Capoeira.zip](https://github.com/mrdoob/three.js/files/1626030/Capoeira.zip)

**Comment by donmccurdy** [comment]
Does calling `mixer.stopAllAction()` do the trick? Or `.stop()` / `.reset()` on individual AnimationActions?

**Comment by MarcRibguth** [comment]
Thanks for your fast reply and sorry for my late reply.
I tested it today and only stop/reset the action does the trick. thanks!
