### ISSUE TITLE
Shadow normalBias and slopeBias

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#13108]
I didn't see these two options in Three, unless I missed it.

Based on https://github.com/mrdoob/three.js/issues/5554, it'd be cool to start getting more ways to tweak shadow.

We need a **bias that adapts to slope**, and a **normal bias** to be up to standard it seems. 

Those would help me get rid of ACNE in this demo: https://codepen.io/anon/pen/dJKxxp

No matter what I set for the `bias` on line `8`, I can't seem to find a way to remove the ACNE. It is more noticeable if you go full screen on desktop, and move the light to one side then look at the opposite side.

As #5554 says,

> currently if you have a large plane you want to receive shadows - you are out of luck pretty much.

Seems like that's the case here because of the light making steep angles with the backgound surface.

**Comment by trusktr** [comment]
Here's about normal bias: https://docs.unity3d.com/ScriptReference/Light-shadowNormalBias.html

Seems easy to implements. Maybe I'll give it a go at some point...

**Comment by trusktr** [comment]
Search for "modify the bias according to the slope" [here](http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-16-shadow-mapping/) for a definition. Basically the bias can get bigger based on a growth factor and depending on the slope of the light ray compared to the surface.

**Comment by mrdoob** [comment]
Looks much better indeed!
Would you like doing a PR with your implementation?

**Comment by ButzYung** [comment]
I wish I could do a PR, but unfortunately, I am still stuck with a (very *coughs*) old version of three.js that is hard for me to give up for various reasons. I have checked some shadow demos on newer builds of three.js, and obviously their lighting and shadowing algorithms are quite different from the one I am using. I have just done some simple tests on directionl lights on some specific scenes, and I am not even sure if the same fix would work equally well on the current build of three.js. I suppose someone else more talented could give it a try on the current version of three.js. The slope-based bias algorithm isn't something complicated anyways.

**Comment by OndrejSpanel** [comment]
For the record: I have submitted a sloped bias in #18413, it was closed (rejected) eventually, mostly because of my inability to show it is worth merging.

**Comment by mrdoob** [comment]
@OndrejSpanel Depending of user demand sometimes PRs get reopened and merged.

**Comment by mrdoob** [comment]
@OndrejSpanel Could `depthOffsetUnits` and `depthOffsetFactor` be simplified into jus one parameter `slopeBias`?

**Comment by OndrejSpanel** [comment]
I think `depthOffsetFactor` could be called `slopeBias`. The `depthOffsetUnits` value closely corresponds to ordinary `bias`. I am not sure if they are 100 % equivalent, to verify that it would be necessary to check the exact computations used.

**Comment by mrdoob** [comment]
Hmm, just read [your other comment](https://github.com/mrdoob/three.js/pull/18413#issuecomment-922977759). I guess we can close this issue then?

**Comment by OndrejSpanel** [comment]
I suggest closing this until someone comes with a compelling case for sloped bias.

If necessary, I think the PR #18413 can be revived anytime later, it does nothing extra difficult or tied to some particular revision of three.js.
