### ISSUE TITLE
Mirror for site

### ISSUE THREAD

**Issue by WahlbergRu** [mrdoob/three.js#13113]
##### Description of the problem

Can you make mirror with another IP, because in some parts of russia you ip adress has blocked.

**Comment by Mugen87** [comment]
Why not just using a proxy server or VPN service?

**Comment by mrdoob** [comment]
Which parts of Russia have blocked it? Does it show the reason why it is blocked?

**Comment by makc** [comment]
@mrdoob there is ongoing troll battle where anons commit alt.suicide.methods pasta to github repo, and authorities then block github for hosting suicide propaganda, which is illegal in Russia. github gets blocked, trolls get lols, russian autorities are shamed, and github gets unblocked. this happens like once per month or two. of course, there may be another reason why it's blocked in Russia, but this would be my best guess.

**Comment by bhouston** [comment]
Can not you just use rawgit on http://github.com/mrdoob/three.js/branch/gh-pages or somethign similar?

Also isn't there a ton of open proxy servers around the world?

**Comment by makc** [comment]
tor should work too

**Comment by mrdoob** [comment]
> Can not you just use rawgit on http://github.com/mrdoob/three.js/branch/gh-pages or somethign similar?

Indeed! This should work: http://rawgit.com/mrdoob/three.js/gh-pages/
