### ISSUE TITLE
[Types bug] Camera for rendering

### ISSUE THREAD

**Issue by WahlbergRu** [mrdoob/three.js#13125]
##### Description of the problem

new WebGLRenderer().render support only one type for camera, but If I use CubeCamera I have types error. 

    /**
     * Render a scene using a camera.
     * The render is done to the renderTarget (if specified) or to the canvas as usual.
     * If forceClear is true, the canvas will be cleared before rendering, even if the renderer's autoClear property is false.
     */
    render(scene: Scene, camera: Camera, renderTarget?: RenderTarget, forceClear?: boolean): void;

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/10681#issuecomment-287921860
