### ISSUE TITLE
Enhance texture/material transform documentation

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#13135]
After seeing this:

https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1991-L2061

I propose adding some kind of documentation to let the world know that there is magic happening under the hood.

>Texture classes have a transform property. Materials can use multiple textures, but also have a single transform property. 
Because a single material, with a single transform property can have many textures with many unique transform properties - Three.js does voodoo magic under the hood to chose which texture's transform to honor. 
This is the list ~[insert list]~.

## edit

1. map
2. specularMap
3. displacementMap
4. normalMap
5. bumpMap
6. roughnessMap
7. metalnessMap
8. alphaMap
9. emissiveMap 

Maybe warn the user that if they have some kind of transform on the emissive map, it will be completely ignored, and the user can expect to see the transform belonging to **any** other 8 map slots that come before?

##### Three.js version

- [x] Dev
- [x] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
Documenting this sounds like a good idea, but describing it as 'voodoo magic' is not really acceptable... In my opinion 😛

**Comment by WestLangley** [comment]
See https://stackoverflow.com/questions/14371385/can-a-three-js-material-have-separate-repeat-values-for-a-bump-map-and-a-texture/14372235#14372235

**Comment by pailhead** [comment]
>but describing it as 'voodoo magic'

J/k was just stubbing it :) but the list does seem somewhat arbitrary hence the term

**Comment by pailhead** [comment]
@westlangley 

That is an interesting point, all shader related problems can be solved by simply writing shaders. I’d suggest looking into onBeforeCompile instead of writing a shader from scratch though.

Still, as is this seems like tribal knowledge. I know your SO answers are broadly referenced but maybe the information in that answer should be in the actual documentation.

**Comment by WestLangley** [comment]
@pailhead Would you be willing to improve the docs? The SO link is just suggested text you can copy if you want.

**Comment by pailhead** [comment]
It might be worth revisiting what this transformation is and how it behaves. 

https://github.com/mrdoob/three.js/blob/1c7a88bd8e30f2784457534e46f20833fdd62bd4/src/renderers/shaders/ShaderChunk/uv_vertex.glsl#L3

> I would like to use a texture!

**_Thats super awesome! Do you want to scale it, offset it and/or rotate it, perhaps?_**

> (opt1) I have absolutely no idea what you're talking about....

**_Thats's fine! I'm just going to set up an identity matrix in the shader and add a few more instructions to your texture, you don't have to worry about a thing._**

>(opt2) Yes please! I have a bunch of textures that need to go into channel `uv0` which need to tile and repeat and stuff, you see they're representing brick, and all these elements that make it look all nice and slightly shiny, bumpy and such. But then i have a light map that needs to not tile, but be in this whole other chan....

**_Say no more! I've got just the thing you need! `Texture` has a number of properties that you can mutate, one of them is a `Vector2` another one is a float etc._**

> Cool. I have 4 textures total, so just configure them all the same?

**_Well... technically you don't have to, I'm ever going to use just one of them to apply the transformation._**

> Hmm... which one?

**_Hold on, consult `[this]` SO answer, I don't really know. :(. If you want to be safe, just make sure they all have the exact same values, then you won't care which one I use, or if you don't like it you can always go write some GLSL, GLSL is fun!_**


Meh, probably didnt explain it well, but maybe having something like:

```javascript
const myMaterial = new THREE.Material({
   map: someTexture,
   anotherMap: anotherTexture,
   textureTransform: wantTransformOrNoIdeaWhatItIs ? 
      new THREE.TextureTransform({position,rotation,offset}) :
      null,
})
```
or

```javascript
const myMaterial = new THREE.Material({
   map: someMap,
   mapChannel: 0,
   anotherMap: anotherMap,
   anotherMapChannel: 1,
   thirdMap: thirdMap,
   thirdMapChannel: 2,
   textureTransform: [ new Transform(), null, new Transform()],
})
```
Or even

```javascript
const anotherTexture = new THREE.Texture({ transform: new THREE.TextureTransform() })
```

**Comment by pailhead** [comment]
@WestLangley 

uhh i may have some bias towards how it works today. Documenting at least, may give me some piece, so in lieu of rethinking this, yes i can document this.

**Comment by pailhead** [comment]
There's also an example submitted to show the users how they can override this behavior. 
https://github.com/mrdoob/three.js/pull/14174
