### ISSUE TITLE
Fix Blender Exporter rotation issues

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#13130]
As noted in https://github.com/mrdoob/three.js/pull/12987#issuecomment-355168140, by using the [glTF exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter/) as reference we should be able to finally solve the rotation issues.

Relevant code:

https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/v1.0.0/scripts/addons/io_scene_gltf2/gltf2_extract.py#L34-L60

https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/v1.0.0/scripts/addons/io_scene_gltf2/gltf2_generate.py#L1356

https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/v1.0.0/scripts/addons/io_scene_gltf2/gltf2_generate.py#L1487

Test scene:

https://github.com/mrdoob/three.js/pull/12987#issuecomment-355166713

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
