### ISSUE TITLE
New example for logarithmicDepthBuffer + depthtexture

### ISSUE THREAD

**Issue by elunty** [mrdoob/three.js#13138]
##### Description of the problem

I wondering if its possible for someone to create a new example similar to depth texture example (https://threejs.org/examples/?q=depth#webgl_depth_texture) but using logarithmicDepthBuffer =true in the webglrenderer. Maybe I am just misunderstanding something and the depth buffer option does not actually change the results of the depth texture..

##### Three.js version

- [ ] Dev
- [ ] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
This question is reposted from [SO](https://stackoverflow.com/questions/48314587/storing-the-logarithmic-depth-in-a-three-depthtexture).

Study the source code of `depth_frag.glsl`. There has been a lot of discussion on this. It will take some time to reconstruct the history. Start with https://github.com/mrdoob/three.js/pull/8602.

Beware your platform may or may not support 'EXT_frag_depth'.

Feel free to post your suggestion for improvement.

**Comment by elunty** [comment]
Isnt depth_frag.glsl actually for MeshDepthMaterial and not a DepthTexture?

**Comment by WestLangley** [comment]
@elunty So sorry, misread your post.

**Comment by elunty** [comment]
Okay so.. turns out I am an idiot. I'm using some custom shaders for my object (`three.points`), and for some reason i expected `logarithmicDepthBuffer: true` to magically make my custom shader assign the logarithmic depth to the `depthTexture` object. It turns out (obviously) that isn't true at all.

I'll close the issue..
