### ISSUE TITLE
Add MeshStandardMaterial to SVG Renderer

### ISSUE THREAD

**Issue by mattrei** [mrdoob/three.js#13131]
##### Description of the problem

Meshes with `MeshStandardMaterial` are currently not considered (and therefore rendered) within the `SVGRenderer` in the _examples_ folder. 

##### Three.js version

- [x] Dev
- [x] r89

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
[SVG](https://developer.mozilla.org/en-US/docs/Web/SVG) doesn't support shaders.
