### ISSUE TITLE
SpriteNodeMaterial transparency lost?

### ISSUE THREAD

**Issue by gigablox** [mrdoob/three.js#13148]
@sunag For PR:
https://github.com/mrdoob/three.js/pull/11531

One issue I ran into:
https://jsfiddle.net/f0j2v3s8/

It seems like SpriteNodeMaterial transparency is lost, there is no combination of blending I can use on to get this example to work.

Any ideas?

**Comment by sunag** [comment]
it was to removed the black box inside of the character?

**Comment by gigablox** [comment]
@sunag The sprite has an alpha channel - I'm trying to make the transparency show so there is no black. I'm able to get this working for other types of sprites but not `SpriteNodeMaterial` for some reason.

**Comment by sunag** [comment]
is need add a node in `alpha` channel:

`material.transparent` is setted in `build` if alpha slot is used

https://jsfiddle.net/213rn0rs/

```javascript
  sprite1.material.alpha = new THREE.SwitchNode( new THREE.TextureNode( walkingManTexture, sprite1.material.color.coord ), "r" );
```

**Comment by sunag** [comment]
or to prefer

https://jsfiddle.net/3x79hpw3/

```javascript
sprite1.material.alpha = new THREE.Math1Node( new THREE.SwitchNode( new THREE.TextureNode( walkingManTexture, sprite1.material.color.coord ), "r" ), THREE.Math1Node.INVERT );
```

**Comment by gigablox** [comment]
@sunag  Oh wow, yes this is what I was trying to do! Thank you so much!

**Comment by gigablox** [comment]
Targeting the alpha channel is what worked for me :)
`new THREE.Math1Node( new THREE.SwitchNode( sprite1.material.color, "a" ), THREE.Math1Node.SUB );`

Thanks again!

**Comment by sunag** [comment]
@gigablox You're welcome!
