### ISSUE TITLE
Possible fix/update for custom scaling and moving using TransformControls.js

### ISSUE THREAD

**Issue by lrusso** [mrdoob/three.js#13142]
I modified the TransformControls script in order to use a variable for how much the object will resize or move in each event. I also deleted a few functions as well. Anyway, I hope it may help some of the code.

Demo: https://lrusso.github.io/Three_with_TransformControls_patched/Viewer.html
Source: https://github.com/lrusso/Three_with_TransformControls_patched

**Comment by Mugen87** [comment]
IMO, this modification is too application-specific and should be no part of the default `TransformControl`. I suggest to create a new topic at the [forum](https://discourse.threejs.org/) (category `Resources`) and present your work there.

https://discourse.threejs.org/c/resources
