### ISSUE TITLE
[Feature request] Clipping against path of planes

### ISSUE THREAD

**Issue by NicolasRannou** [mrdoob/three.js#13153]
Is there any plan to support clipping against a path composed of "N" planes.

You can think of it as the yellow mesh there:
![screen shot 2018-01-22 at 5 48 10 pm](https://user-images.githubusercontent.com/214063/35232825-c9bc6200-ff9c-11e7-9320-d0ecf65bc01d.png)

Using the current clipping method doesn't quite work in this context.

I'd be happy to work on that if you have any suggestion on the best way to tackle it.

**Comment by WestLangley** [comment]
>Is there any plan to support clipping against a path

No. I expect that is too application-specific. You can write your own shader to do that, however -- or inject code into an existing shader.

We do support clipping against "N" planes.

**Comment by WestLangley** [comment]
Sorry, this is not going to become a three.js feature. Try one of my above suggestions.
