### ISSUE TITLE
Inescapable and non-disposable animation loop

### ISSUE THREAD

**Issue by brunnerh** [mrdoob/three.js#13151]
##### Description of the problem

The `WebGLRenderer` has an internal `loop` function as part of the `animate` function, looking at the code it will loop indefinitely and there is no hook for disposal either:

	function loop( time ) {
		if ( onAnimationFrame !== null ) onAnimationFrame( time );

		var device = vr.getDevice();

		if ( device && device.isPresenting ) {
			device.requestAnimationFrame( loop );
		} else {
			window.requestAnimationFrame( loop );
		}
	}

(Looked into this after my `animate` callback was still being executed after calling `renderer.dispose()`, which seems like it should not be the case.)

##### Three.js version

- [x] Dev
- [x] r88

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
If we keep track of the return value of a `requestAnimationFrame()` call, we can stop the animation loop in `dispose()` via `cancelAnimationFrame()`.
