### ISSUE TITLE
Documentation says the tube argument to torus is a diameter, when it seems to be a radius

### ISSUE THREAD

**Issue by mysteryDate** [mrdoob/three.js#13155]
https://github.com/mrdoob/three.js/blob/a885290f59ff6b1692b5cccd8e7ab5b2bba33946/docs/api/geometries/TorusBufferGeometry.html#L48

<img width="899" alt="screen shot 2018-01-22 at 16 52 38" src="https://user-images.githubusercontent.com/2529989/35246491-e3cc1472-ff94-11e7-9990-0636515b3b27.png">

If `radius = tube` and it appears from the generated torus that `tube` is the *radius* of the tube, not it's diameter.

**Comment by WestLangley** [comment]
radius — radius of the torus. Default is 1. 
    tube — radius of the tube. Default is 0.4. 

Would you like to fix it?

**Comment by Mugen87** [comment]
`TorusKnotGeometry` and `TorusKnotBufferGeometry` also needs this fix.

**Comment by mysteryDate** [comment]
Sure! I should have suggested when I opened ticket, I'll fix it.
