### ISSUE TITLE
Only one scene is rendered in VR

### ISSUE THREAD

**Issue by brunnerh** [mrdoob/three.js#13161]
##### Description of the problem

If i have a perspective camera and an orthographic camera, each rendering separate scenes to the same renderer, only the contents of the first scene appear in VR. It does not appear to matter that one of the cameras is orthographic. Even when using the same camera to render the two scenes, the second scene only shows up in the browser, not the VR display.

What the update loop looks like:

```javascript
// renderer.autoClear is set to false
renderer.animate(() =>
{
	renderer.clear();

	renderer.render(scene, camera);
	renderer.clearDepth();
	renderer.render(hud, hudCamera);
});
```

As the names imply the goal was to render a HUD on top of the perspective scene; unfortunately the HUD disappears.

##### Three.js version

- [ ] Dev
- [x] r89

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Tested this on an Android device running Chrome Beta 64.

**Comment by Mugen87** [comment]
So this problem only happens in VR, right? Can you reproduce the problem with this [Chrome Extension](https://chrome.google.com/webstore/detail/webvr-api-emulation/gbdnpaebafagioggnhkacnaaahpiefil)?

It will be easier to investigate the issue if you provide a simple live demo/reduced test case.

**Comment by brunnerh** [comment]
Here is a test file where only the red sphere appears in VR:

```html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Multiple Scenes Demo</title>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/89/three.min.js"></script>
	<style>
		html {
			background: #333;
		}
	</style>
</head>

<body>
	<script>
		const side = 400;

		const renderer = new THREE.WebGLRenderer();
		renderer.setSize(side, side);
		renderer.autoClear = false;
		renderer.vr.enabled = true;
		document.body.appendChild(renderer.domElement);

		// Perspective Scene
		const scene = new THREE.Scene();
		const camera = new THREE.PerspectiveCamera(75, 1, 1, 500);

		const sphere = new THREE.Mesh(new THREE.SphereGeometry(5, 100, 100), new THREE.MeshBasicMaterial({ color: "#ff0000" }));
		sphere.position.z = -20

		scene.add(sphere);

		// Orthographic Scene
		const hud = new THREE.Scene();
		const half = side / 2;
		const hudCamera = new THREE.OrthographicCamera(-half, half, -half, half, 0, 500);

		const canvas = document.createElement("canvas");
		canvas.width = side;
		canvas.height = side;
		const ctx = canvas.getContext("2d");
		ctx.beginPath();
		ctx.arc(half, half, side / 10, 0, Math.PI * 2);
		ctx.lineWidth = side / 20;
		ctx.strokeStyle = "#ffffff";
		ctx.stroke();

		const texture = new THREE.Texture(canvas)
		texture.minFilter = THREE.LinearFilter;
		const material = new THREE.MeshBasicMaterial({ map: texture, transparent: true });
		const planeGeometry = new THREE.PlaneGeometry(1, 1);
		const plane = new THREE.Mesh(planeGeometry, material);
		plane.position.z = -20
		plane.rotation.x = Math.PI;
		plane.scale.set(side, side, 1);
		plane.updateMatrix();
		texture.needsUpdate = true;
		hud.add(plane);

		const sphere2 = new THREE.Mesh(new THREE.SphereGeometry(side / 10, 100, 100), new THREE.MeshBasicMaterial({ color: "#00ff00" }));
		sphere2.position.z = -20
		hud.add(sphere2);

		renderer.animate(() =>
		{
			renderer.clear();

			renderer.render(scene, camera);
			renderer.clearDepth();
			renderer.render(hud, hudCamera);
		});

		(async () =>
		{
			const devices = await navigator.getVRDisplays();
			if (devices.length == 0)
				return;

			const display = devices[0];
			const enter = document.createElement("button");
			enter.textContent = "VR";
			enter.addEventListener("click", async () =>
			{
				await display.requestPresent([{ source: renderer.domElement }]);
				renderer.vr.setDevice(display);
			});
			document.body.appendChild(enter);
		})();
	</script>
</body>

</html>
```

**Comment by brunnerh** [comment]
Using the extension the problem also manifests.

Non-VR:

![image](https://user-images.githubusercontent.com/834235/35283931-cbc8500a-0059-11e8-9fa0-d2d8c4d7264f.png)

VR:

![image](https://user-images.githubusercontent.com/834235/35283958-da3b08f8-0059-11e8-8b02-32557eafa24c.png)

**Comment by mrdoob** [comment]
Yes, currently you can only do one render per frame in VR.

For your use case, I recommend you add the HUD as a child of the main camera and disable `depthTest` on its materials.

Also, VR does not support Orthographic cameras.

**Comment by brunnerh** [comment]
Thank you for the information and suggestions!
