### ISSUE TITLE
Overlapping holes cause triangulation failure

### ISSUE THREAD

**Issue by svcew-dinesh** [mrdoob/three.js#13160]
This is extension of issue #3386

I am trying to add two rectangles to one parent rectangle so that parent rectangle will have the cut same as its children. If two rectangles are apart from each other its working fine but if we combine both then the issue occurs.
Please check the issue in [jsfiddle](https://jsfiddle.net/6dtzfLfn/1/)

**Comment by Mugen87** [comment]
Our code currently expects that holes are not overlapping. If you ensure this, you will get proper results:

https://jsfiddle.net/6dtzfLfn/7/

`three.js` uses internally a port of [earcut](https://github.com/mapbox/earcut) for polygon triangulation. If you can reproduce the issue just with earcut, you might want to open an issue at the respective repository.
