### ISSUE TITLE
Example broken on mobile

### ISSUE THREAD

**Issue by leighhalliday** [mrdoob/three.js#13164]
##### Description of the problem

This example is broken on Android/Chrome:
https://threejs.org/examples/#webgl_gpgpu_water

```
THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
get @ three.js:20901
initGLContext @ three.js:21436
WebGLRenderer @ three.js:21480
init @ webgl_gpgpu_water.html:272
(anonymous) @ webgl_gpgpu_water.html:251
three.js:20901 THREE.WebGLRenderer: OES_texture_half_float extension not supported.
get @ three.js:20901
initGLContext @ three.js:21437
WebGLRenderer @ three.js:21480
init @ webgl_gpgpu_water.html:272
(anonymous) @ webgl_gpgpu_water.html:251
three.js:20901 THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.
get @ three.js:20901
initGLContext @ three.js:21438
WebGLRenderer @ three.js:21480
init @ webgl_gpgpu_water.html:272
(anonymous) @ webgl_gpgpu_water.html:251
webgl_gpgpu_water.html:406 No OES_texture_float support for float textures.
```

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Comment by Mugen87** [comment]
The example works on my Pixel with Android 8.1.

> OES_texture_float_linear extension not supported.
 OES_texture_half_float extension not supported.
OES_texture_half_float_linear extension not supported.

It's important to know that the mentioned extensions are not supported on all devices (see e.g. https://webglstats.com/webgl/extension/OES_texture_float_linear). If they are missing, the example won't work.
