### ISSUE TITLE
FBXLoader Not Loading Binary octat-streat (parse) file

### ISSUE THREAD

**Issue by dharveshmydeen** [mrdoob/three.js#13166]
##### Description of the problem
Hi,

I have Used Latest three.js package and working in angular 5.

By using FBXLoader it is loading normal plain/text file and it is working fine.

But,It is showing error while uploading binary parse fbx file

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/s3rjfcc3/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/ptgwhemb/) (dev branch)
* [codepen](https://codepen.io/anon/pen/aEBKxR) (latest release branch)
* [codepen](https://codepen.io/anon/pen/BJWzaN) (dev branch)

##### Three.js version

- [ ] Dev
- [x ] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
Can you share the model you are having problems with?

And have you tested with the latest dev version of the loader?

**Comment by dharveshmydeen** [comment]
I have uploaded my Binary Parse Model File.It is not Loading and Showing the below error

![screenshot from 2018-01-24 15-31-47](https://user-images.githubusercontent.com/20161904/35332715-f17c410c-0131-11e8-8a13-5a2f09a73e6c.png)




[BinaryModel.zip](https://github.com/mrdoob/three.js/files/1659821/BinaryModel.zip)

**Comment by looeee** [comment]
It loads fine with the latest version of the loader from the dev branch. Please update your loader.

**Comment by dharveshmydeen** [comment]
Thanks you,

I am using "version": "0.89.0" .I think it is a latest Version.
I am using this in angular 5.0
I have loaded the model using the code which you have given in your example. https://threejs.org/examples/?q=fbx#webgl_loader_fbx

I dont know how where to locate the model in this scene.

Can your share loading function which you have used..?

**Comment by looeee** [comment]
Yes, R89 is the latest release. You need to take the files from the development branch (R90dev) here:
https://github.com/mrdoob/three.js/tree/dev

You'll need to update the three.js file and the FBXLoader.js file

I tested it in my loader [here](https://www.blackthreaddesign.com/loader/).

**Comment by looeee** [comment]
If you need any more help please ask over on the [forum](http://discourse.threejs.org/).
