### ISSUE TITLE
ObjectLoader.js uses "anonymous" LoadingManager in parseImages()

### ISSUE THREAD

**Issue by emeyex** [mrdoob/three.js#13177]
See https://github.com/mrdoob/three.js/blob/master/src/loaders/ObjectLoader.js, currently line number 494 in master branch: `var manager = new LoadingManager( onLoad );`

The problem is that there is no way to pass custom parameters to that `LoadingManager` instance. In my specific use-case, I need to remap all asset urls in my game, i.e. using `setURLModifier`. Using `DefaultLoadingManager` or passing a custom instance into the `ObjectLoader` constructor doesn't work for the images referenced in the JSON object because that "anonymously" created `LoadingManager` of course is totally unrelated and just uses the defaults. So all the images referenced in the JSON object fail to load.

I'm unsure what the correct solution is, but the outcome that I'm after is to be able to apply my custom `setURLModifier` function to any dependencies loaded as part of `ObjectLoader.load`. Seems like options include using the manager parameter that was supplied to the `ObjectLoader`, or else maybe forwarding options from that one to the one created inside `parseImages()`?

**Comment by emeyex** [comment]
For anyone looking for a work around, the following is working for me, but obviously it would be great if this were fixed inside the actual `ObjectLoader.load` code instead.

```
function customLoadObject( rootUrl, urlModifier, onLoaded, onProgress, onError ) {
	const fileLoader = new THREE.FileLoader( );
	fileLoader.load( rootUrl, ( rawText ) => {
		const json = JSON.parse( rawText );
		for ( const img of json.images ) {
			img.url = urlModifier( rootUrl.substring(0, rootUrl.lastIndexOf("/") + 1) + img.url );
		}
		const objLoader = new THREE.ObjectLoader( );
		objLoader.parse( json, onLoaded );
	}, onProgress, onError );
}
```
☝️  is more or less a straight copy/paste of `ObjectLoader.load` (I removed the error handling to simplify), but before calling `parse()`, I iterate over the images in the JSON and modify the URLs inline. In my case I believe this would break if `setTexturePath()` were used, instead I manually compute and prepend it.

**Comment by Mugen87** [comment]
`ObjectLoader` uses an additional instance of `LoadingManager` to fire the global `onLoad()` callback iff all images are loaded. Um, this is something that other loaders actually handle differently. If you want to wait until all resources (e.g. textures) are fully loaded, you have to use the `onLoad()` callback of the respective loading manager.

Maybe we can change the following [line](https://github.com/mrdoob/three.js/blob/master/src/loaders/ObjectLoader.js#L494) to:
```javascript
var loader = new ImageLoader( scope.manager );
```
So we use a single loading manager for all internal loaders. I guess this would be more consistent with respect to other loaders. But it also changes the current behavior of `ObjectLoader` which might be problematic for certain users (they would have to use loading manager to restore the old behavior).

**Comment by emeyex** [comment]
That would definitely make more sense to me (to wait for all resources to load by using the shared loading manager). Enabling that behavior could maybe just be provided via an extra option so as not to change old/existing code bases?

**Comment by emeyex** [comment]
Added a PR ☝️ that addresses the issue for me, and should otherwise preserve behavior for anyone who doesn't care about the new addition.

**Comment by emeyex** [comment]
Since @Mugen87 closed the PR (https://github.com/mrdoob/three.js/pull/13187), I will continue conversation here.

I find it a little bewildering that after offering a fix for a bug and incorporating all feedback into the PR promptly, that it is then closed without any substantive explanation. It seems like it would be more constructive to actually point out real problems with the PR if there are any - that is, assuming you are interested in encouraging contributions from the community at large. If you _aren't_ interested in such contributions, it might be best to advertise that plainly.

**Comment by Mugen87** [comment]
I think you exaggerate the whole thing a little bit. You contribution is valuable since you've pointed out an issue in `ObjectLoader`. If one of the collaborators closes a PR, then that does not mean the work of the developer is unwanted.

The thing is you've created a lot of code that is actually not necessary. If the internal image loader uses the global loading manager, it's not necessary to track if all images are loader. Besides, it'm still interested in the feedback of other core developers if a change is actually required. Maybe we just leave it as it is.

**Comment by emeyex** [comment]
I don't take it personally if you close my PR, it's the closing of it without further explanation that was off-putting. Thank you for providing some more details, I will take a look and see if I can improve the PR based off your comment: 

> The thing is you've created a lot of code that is actually not necessary. If the internal image loader uses the global loading manager, it's not necessary to track if all images are loader.

I will be the first to admit I am new to the three.js codebase and still getting my bearings, so I appreciate the specific feedback.

**Comment by Mugen87** [comment]
> it's the closing of it without further explanation that was off-putting.

Sorry for this. You're right, an explanation would have been appropriate. I guess it was just the lack of time to write some good feedback.

**Comment by donmccurdy** [comment]
> Besides, it'm still interested in the feedback of other core developers if a change is required at all. Maybe we just leave it as it is.

For my $0.02, in this situation it seems like the LoadingManager is being used to work around the lack of other async syntax, like `Promise.all()`. In GLTFLoader we are just using Promises, and it's easier to make sure the images all use the same LoadingManager. But I'm not sure whether any Promises are used in the core codebase; without transpiling that could be a breaking change. :/

**Comment by emeyex** [comment]
@Mugen87 👍 No worries, I understand having limited time.

I've just taken a closer look at the code - unless I'm misunderstanding your comment, the code I've added is necessary whether you use `DefaultLoadingManager` (I assume that's what you mean by `global loading manager`) or a new instance of `LoadingManager`. The anonymous callbacks passed to `loader.load` (`ObjectLoader.js` line 493 in my PR) will be invoked for every image that loads, and are not gated by any loading managers (see `ImageLoader.load` implementation). The reason that code was not _previously_ necessary is because the `onLoad` callback was passed into a new anonymous LoadingManager. As far as creating `a lot of code`, I'm not sure that I entirely agree, but I can try to remove any redundancies.

As far as leaving the code "as is," I would just like to re-iterate that for anyone who uses any kind of asset remapping (i.e. source file: `assets/some/file.png` -> dist file: `assets/5cd532983fa7665e.png`) the current `ObjectLoader.js` requires that you jump through some ugly, hacky hoops (see the work-around I posted at the top of thread). If you are comfortable with that, then I suppose it's ok to leave it. My PR also addresses the fact that the `onError` callback is not called for images that fail to load. I suppose that's an open question as to the desired behavior, but personally it seems best to bubble up such events "properly."

@donmccurdy I'm all for using promises, but like you said not sure what the general policy is on them in the core codebase.

**Comment by emeyex** [comment]
Pushed up a bit more concise version [here](https://github.com/emeyex/three.js/blob/objectloader-unify-loadingmanager/src/loaders/ObjectLoader.js#L469) (will hold off on creating a PR for now). Moved almost all the logic into `imageFinishedLoading()`.

For reference, here are the lines I mentioned above in `ImageLoader.js` demonstrating that some mechanism for waiting on all images is necessary regardless of what kind of loading manager is passed in:
* [onLoad if image is already cached](https://github.com/mrdoob/three.js/blob/dev/src/loaders/ImageLoader.js#L37)
* [onLoad if image is not already cached](https://github.com/mrdoob/three.js/blob/dev/src/loaders/ImageLoader.js#L53)
* [onError](https://github.com/mrdoob/three.js/blob/dev/src/loaders/ImageLoader.js#L69)

**Comment by emeyex** [comment]
Probably kicking a dead horse, but I spent some more time testing, looking through the loading code, and made one more change. Made a new [PR](https://github.com/mrdoob/three.js/pull/13244) as it seems like the right thing to do. Enjoy!

**Comment by Mugen87** [comment]
related #9288
