### ISSUE TITLE
FBX importer (binary) parse PointLight color is incorrect.

### ISSUE THREAD

**Issue by HoldenCa** [mrdoob/three.js#13179]
##### Description of the problem
FBX importer (binary) parse PoitLight color incorrect.
You expect "ColorRGB" as vector3 but you have to expect "Color" as vector3 also.

```javascript
if ( innerPropType1 === 'ColorRGB' || innerPropType1 === 'Vector' || innerPropType1 === 'Vector3D' || innerPropType1.indexOf( 'Lcl_' ) === 0 ) {

 innerPropValue = [
  subNode.propertyList[ 4 ],
  subNode.propertyList[ 5 ],
  subNode.propertyList[ 6 ]
 ];

} else {

 innerPropValue = subNode.propertyList[ 4 ];

}
```

I Can fix it by myself, but I want you to suggest me. If it's bad idea instaed of checking innerPropType1, check subNode.propertyList.length to define if the value of property is an vector or it's just single value?
Also seems that PointLight distance calculated wrond.
`distance = lightAttribute.FarAttenuationEnd.value / 1000; `
You don't have to divide on 1000 here.

And need to add position for point light.
```javascript
 case 0: // Point
          model = new THREE.PointLight(color, intensity, distance, decay);
          //position that is looks like in 3ds max
          model.position.fromArray(nodeProperties.Lcl_Translation.value);
          break;
```
##### Three.js version

- [x] Dev
- [ ] r89
- [ ] ...

##### Browser

- [] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by looeee** [comment]
@HoldenCa incorrect color parsing is fixed in #13265 

`FarAttenuationEnd` and position for point light still need fixing, would you like to create PRs for those?

**Comment by looeee** [comment]
> And need to add position for point light.

```js
 case 0: // Point
          model = new THREE.PointLight(color, intensity, distance, decay);
          //position that is looks like in 3ds max
          model.position.fromArray(nodeProperties.Lcl_Translation.value);
          break;
```

There is not `nodeProperties` available in this method, and the light's position and rotation should be getting set the same way as any other object so I don't think that this is necessary.

**Comment by looeee** [comment]
Fixed the `FarAttenuationEnd` division issue in #13516

@HoldenCa if you have an example where a light is being incorrectly position, please open a new issue and share your model. Closing this for now.
