### ISSUE TITLE
SoftwareRenderer border flickering on Chrome

### ISSUE THREAD

**Issue by Ben-Mack** [mrdoob/three.js#13174]
On Chrome (v64 latest), examples using SoftwareRenderer produces below flickering: 
![ezgif-2-0716262583](https://user-images.githubusercontent.com/6309393/35398204-f1026394-0223-11e8-9e92-1af4d5f247be.gif)

These 2 examples:   
  https://threejs.org/examples/software_geometry_earth.html
 https://threejs.org/examples/software_sandbox.html
have flickering.

But https://threejs.org/examples/software_lines_splines.html  is not!

Firefox 57 working good on all examples. I've updated gpu driver but still see these artifacts.

##### Three.js version
- [ ] Dev
- [x] r89

##### Browser
- [ ] All of them
- [x] Chrome 64
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- Windows 10 64bit

**Comment by Mugen87** [comment]
I'm unable to reproduce with Chrome 64.0.3282.119 and macOS 10.13.2. Um, maybe the flickering happens only with Windows?

**Comment by haroldiedema** [comment]
I can confirm this is broken. Looks like a browser issue though.

For me, it was working on Chrome 63.0.3239.132 (Official build) (64-bits).
When I updated to version 64.0.3282.119 (Official build) (64-bits), it shows exactly like the image OP posted.

**Comment by looeee** [comment]
Looks fine to me on Windows 10, Chrome Version 64.0.3282.119 (Official Build) beta (64-bit).

**Comment by Mugen87** [comment]
@Ben-Mack Do you mind to file a bug here: https://bugs.chromium.org/p/chromium/issues/list

It also worth to highlight that updating to Chrome 64 seems to introduce this issue.

**Comment by Mugen87** [comment]
I've tested with a windows machine today and the demo looks fine. It would be nice if someone who can reproduce the problem also reports this to the Chromium issue tracker.
