### ISSUE TITLE
Delete the render pipe with THREE. EffectComposer

### ISSUE THREAD

**Issue by BadmasterY** [mrdoob/three.js#13171]
I only see function like addPass, insertPass, render, reset, setSize, and swapBuffers.But I didn't see deletet in the THREE Effection, except what did I miss?

I now through the array to the operation of the rendering pipeline to delete, but I do think it does have a serious impact on the performance, after doing this in bloody android machine can not run!

So I'm wondering if there's a better way to do it, or if you can just add a delete function directly inside this method.

In fact, I would like to add or delete the rendering pipeline dynamically, so that I can change the rendering effect dynamically like the game.

Now I don't have any good ideas to implement, who can tell me how to solve this problem.

**Comment by WestLangley** [comment]
Sorry, this is not a help site. Try [the forum](https://discourse.threejs.org).
