### ISSUE TITLE
FBXLoader changes object names.

### ISSUE THREAD

**Issue by HoldenCa** [mrdoob/three.js#13182]
##### Description of the problem
After recent changes FBX loader started to modify objects names.
For example I'm exporting a plane from 3ds max with name "Plane001", after import by FBXLoader name is converted to "Plane001Model".
Is it correct behaviour?
I want to relly on object names in my code.

##### Three.js version

- [x ] Dev
- [ ] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [x ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
I can't reproduce this. Can you share the model you are having problems with?

**Comment by HoldenCa** [comment]
@looeee  Sorry, for bothering. I can't reproduce on latest dev also.
