### ISSUE TITLE
FBXLoader animation doesn't work.

### ISSUE THREAD

**Issue by HoldenCa** [mrdoob/three.js#13185]
##### Description of the problem

After recent changes FBXLoader doesn't handle animations properly and falls with error.

![image](https://user-images.githubusercontent.com/13250475/35445565-b0de2f9a-02ba-11e8-895d-e5ab6235ef4e.png)
fbx model with test animation is attached.
[test_animation.zip](https://github.com/mrdoob/three.js/files/1668147/test_animation.zip)

**Comment by looeee** [comment]
Fixed in #13221
