### ISSUE TITLE
Misleading Documentation  - Matrix4

### ISSUE THREAD

**Issue by miguelriemoliveira** [mrdoob/three.js#13183]
The description for the [Matrix4](https://threejs.org/docs/#api/math/Matrix4) in the online documentation says:

"
> Every Object3D has three associated Matrix4s:
> Object3D.matrix: This stores the local transform of the object.
> Object3D.matrixWorld: The global or world transform of the object. This is the object's transformation relative to its parent. If the object has no parent, then this is identical to the local transform.
"

Perhaps I am misunderstanding something, but the matrixWorld should store the **object's transformation relative to the world**. Thus the sentence "This is the **object's transformation relative to its parent**" seems incorrect. 

I would guess this sentence was written to the _matrix_ . I think that's the proper description for the matrix, not for the matrixWorld.

Am I getting it all wrong or is this just a typo in the documentation?

Regards,

Miguel

PS: Thanks for making  THREEJS such a great tool

**Comment by Mugen87** [comment]
Good find! Indeed, the sentence `This is the object's transformation relative to its parent.` is wrong there. It belongs to `matrix`. Would you like to correct the description? 😊

**Comment by miguelriemoliveira** [comment]
You mean with a pull request? I can try to do that.

**Comment by Mugen87** [comment]
Yes please 👍

**Comment by Mugen87** [comment]
You can also use the "Edit" feature of github.

![image](https://user-images.githubusercontent.com/12612165/35441404-af8042e4-02a3-11e8-8187-e8fb6519ee60.png)

**Comment by miguelriemoliveira** [comment]
Made a mistake and did a pull request to my own fork first. Now its correct - a pull request is open to fix this one.
