### ISSUE TITLE
Critical Bug of getInverse when I use arrowHelper!

### ISSUE THREAD

**Issue by yiakwy** [mrdoob/three.js#13188]
##### Description of the problem

Hello I am developing a 3d system and it generates a lot arrowHelper programmatically. The issue is that  every few seconds,  a warning "THREE.Matrix3: .getInverse() can't invert matrix, determinant is 0" be fired.

``` javascript
from = new THREE.Vector3(-edge.start.x, 0.1, -edge.start.y)
to = new THREE.Vector3(-edge.end.x, 0.1, -edge.end.y)
dir = to.clone().sub(from)
len = dir.length()
arrowHelper = new THREE.ArrowHelper(dir.normalize(), from.clone().sub(shift), len, color)
arrowHelper.children[1].scale.set(1,1,1)

```

those huge I/O operations (console.log) might run out the memory of my browser.

When I dived into the codes, I believe that there is a bug or misunderstanding in the codes 

``` javascript
getNormalMatrix: function ( matrix4 ) {

   return this.setFromMatrix4( matrix4 ).getInverse( this ).transpose();

},
```

The warning comes from *getinverse* showing me that it is trying to call a matrix3, however in fact, it is calling matrix4 and of course compared to matrix3, matrix4 contains a lot of zeros.

I don't think this is an intended behavior. Wish you can help me out of warnings.
##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by vincentfretin** [comment]
I have a similar issue with lots of 
"THREE.Matrix4: .getInverse() can't invert matrix, determinant is 0" or
"THREE.Matrix3: .getInverse() can't invert matrix, determinant is 0"
and with a texture inside a sphere that is now black.
using r89 and removing the changes from 
https://github.com/mrdoob/three.js/pull/12787
fixed the issue for me.

**Comment by vincentfretin** [comment]
For the black texture I had, I now need to set material side:back and keep a negative scale, see 
https://github.com/aframevr/aframe/issues/3288#issuecomment-361054219
but I still have lots of `.getInverse() can't invert matrix, determinant is 0` warnings of my scene.

**Comment by yiakwy** [comment]
@vincentfretin Thank you! Now I know why this happened. But it seems that PR is likely for addressing another problem. Simply revert the commit might not be an ideal solution.

**Comment by mudin** [comment]
I had the same issue with ArrowHelper.
The arrow helper’s length should be bigger than headLength.
Otherwise it is child Line’s scale.y will be 0. and causes this issue.
https://threejs.org/docs/#api/en/helpers/ArrowHelper
