### ISSUE TITLE
bug? animation behavior inconsistent, only moves half length

### ISSUE THREAD

**Issue by wjessup** [mrdoob/three.js#13189]
I'm creating an animation for that's dynamic based on a bunch of stuff, so the movements are not fixed, even the number of movements depends on state. I'm also creating objects and animating those in the middle of all of it.

It was working perfectly until I started to refactor it a bit and use only a single mixer. Now I get this behavior where the animationClip says the right thing but the animation itself doesn't work correctly.

In the animated GIF below you can see that both animation tracks should go from 0 -> 150 moving the blocks up, but visually one block moves about 75 and the other 150. 

![image](https://dha4w82d62smt.cloudfront.net/items/3f3t2j0T3N1m1n1E440A/Screen%20Recording%202018-01-27%20at%2003.09%20PM.gif)

It goes fast so here's the logged values:
![image](https://user-images.githubusercontent.com/13675/35477364-b10bb3fa-0375-11e8-9075-7d82ebce40a8.png)

and the code:
![image](https://user-images.githubusercontent.com/13675/35477323-3b331a88-0375-11e8-9903-9de624c3a5ce.png)

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [] All of them
- [X] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by gavinkou** [comment]
From: bounces+848413-91e8-gavin.kou=163.com@sgmail.github.com [mailto:bounces+848413-91e8-gavin.kou=163.com@sgmail.github.com] On Behalf Of Will Jessup
Sent: Sunday, January 28, 2018 7:22 AM
To: mrdoob/three.js <three.js@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: [mrdoob/three.js] bug? animation behavior inconsistent, only moves half length (#13189)

 

I'm creating an animation for that's dynamic based on a bunch of stuff, so the movements are not fixed, even the number of movements depends on state. I'm also creating objects and animating those in the middle of all of it.

It was working perfectly until I started to refactor it a bit and use only a single mixer. Now I get this behavior where the animationClip says the right thing but the animation itself doesn't work correctly.

In the animated GIF below you can see that both animation tracks should go from 0 -> 150 moving the blocks up, but visually one block moves about 75 and the other 150.

 <https://camo.githubusercontent.com/ebca92f576c7a4f4d9b385c5b6799b4d9e8652e9/68747470733a2f2f64686134773832643632736d742e636c6f756466726f6e742e6e65742f6974656d732f33663374326a3054334e316d316e3145343430412f53637265656e2532305265636f7264696e67253230323031382d30312d3237253230617425323030332e3039253230504d2e676966> 

It goes fast so here's the logged values:
 <https://user-images.githubusercontent.com/13675/35477364-b10bb3fa-0375-11e8-9075-7d82ebce40a8.png> 

and the code:
 <https://user-images.githubusercontent.com/13675/35477323-3b331a88-0375-11e8-9903-9de624c3a5ce.png> 


Three.js version


*	[ ] Dev
*	[X] r89
*	[ ] ...


Browser


*	[] All of them
*	[X] Chrome
*	[ ] Firefox
*	[ ] Internet Explorer


OS


*	[] All of them
*	[ ] Windows
*	[X] macOS
*	[ ] Linux
*	[ ] Android
*	[ ] iOS


Hardware Requirements (graphics card, VR Device, ...)

**Comment by Mugen87** [comment]
Sorry, this is not a help site. Please try [the forum](https://discourse.threejs.org). Also provide a live demo or reduced test case. In this way, it's easier for other community members to help you.
