### ISSUE TITLE
FBX loader PerspectiveCamera enhancement

### ISSUE THREAD

**Issue by HoldenCa** [mrdoob/three.js#13180]
##### Description of the problem

Consider to apply FocalLength from fbx file for Pespective camera. It's makes scene looks pixel perfect as in 3ds max.

```javascript
var FocalLength = cameraAttribute.FocalLength ? cameraAttribute.FocalLength.value : null;

switch ( type ) {

   case 0: // Perspective
      model = new THREE.PerspectiveCamera( fov, aspect, nearClippingPlane, farClippingPlane );
      if ( FocalLength !== null )  model.setLens( FocalLength );
      break;
```

##### Three.js version

- [ ] Dev
- [ ] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
This looks good - would you like to make a pull request? 

A couple of comments: 

`var FocalLength` should be `var focalLength`

`model.setLens` - I presume this should be [model.setFocalLength](https://threejs.org/docs/#api/cameras/PerspectiveCamera.setFocalLength) ?
