### ISSUE TITLE
text direction  for text geometry  

### ISSUE THREAD

**Issue by eliasasaid1** [mrdoob/three.js#13181]
It seems there is an issue with the text geometry when using arabic unicoded letters I attached the files needed to reproduce the issue.

also you must the below hash to reproduce it : three.js-dev/examples/webgl_geometry_text.html#FF00A1001#%D8%B3%D8%A7%D9%82

problem occurs when text is set as below : 

`	var text = "\u0633\u0627\u0642", //there is problem with text displayed (direction and letters linking it may be due that there is no support for any other language than English) it should be ساق  also last letter should display ق (two small points above the letter should be displayed)`

[arabic typesetting_regular.typeface.zip](https://github.com/mrdoob/three.js/files/1667523/arabic.typesetting_regular.typeface.zip)

**Comment by Mugen87** [comment]
see #11680
