### ISSUE TITLE
[BUG]: onBeforeCompile hashing

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#13192]
##### Description of the problem

Go to https://codepen.io/anon/pen/KQPBjd. Comment line `#41` and the other cube that stays in the scene will change the shader.

This is due to:
https://github.com/mrdoob/three.js/blob/35a26f178c523514673d992da1aece23c1cfca6e/src/renderers/webgl/WebGLPrograms.js#L244

The same `onBeforeCompile` is provided to both materials, even though there is a condition that will process the shaders differently. 

https://github.com/mrdoob/three.js/pull/13198 has a different approach but doesn't have this issue:
https://codepen.io/anon/pen/rJNgYZ

##### Three.js version

- [x] Dev
- [x] r89
- [ ]...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by pailhead** [comment]
I looked into fixing this, but i'm not sure what to do. There is no way of knowing what's in the `onBeforeCompile`, other than it does it's own "compile". Since this only makes sense on materials, and not `ShaderMaterials` one could compile the `onBeforeCompile` and use that to hash, but seems a bit too hacky.

**Comment by Mugen87** [comment]
I've looked into this today and i wouldn't say it's a bug. More a feature request. The implementation of `material.onBeforeCompile()` is currently not designed to support dynamic scenarios like your `if` statement. As you mentioned correctly, the renderer can't distinct between both materials since the program code is identical.

Workaround: It's easy to avoid the problem if you apply for each material a unique callback. 

Fix: https://codepen.io/anon/pen/xYyKjX?editors=0010

**Comment by pailhead** [comment]
True, but it’s suuuuuuupeer hacky. I use this feature a lot and it’s very cumbersome to work with. Is there any chance you could take a look at my PR and give some feedback? 

With a couple more lines of code I think that this can become much more powerful and user friendly.

As is:

- can’t have logic in the callback 
- have to know the each specific shader in order to know where to inject uniforms varyings and functions ( why can’t it be just uniform: { type, name } and then three knows what to do with it)
- very verbose

**Comment by pailhead** [comment]
>  is currently not designed to support dynamic scenarios like your if statement in the callback function. 

I’d argue the semantics here :)

It was not designed to begin with, I think it was literally “hey this works with 3 lines of code” 🤣 
It does actually kinda work with my dynamic scenario - I’m getting multiple materials to use the same chunks  and their subsets, it just requires a pretty inconvenient work around. 

If I do however make a feature request do you think that this can be redesigned to be more friendly?

**Comment by Mugen87** [comment]
> If I do however make a feature request do you think that this can be redesigned to be more friendly?

Making a feature request is a good idea. You should note your requirements/suggestions in short/summarised form. Besides, link to your PR that illustrates your idea of a concrete implementation.

I guess i would close this issue and create a new one with the mentioned content.

**Comment by mrdoob** [comment]
I'm having a hard time to figure out an approach that is not a hack to implement this over the current material system. The #11475 hack was included instead.

As I proposed in a previous meetup, I think we should study how to implement this on top of MeshNodeMaterial instead.

https://threejs.org/examples/?q=nodes#webgl_materials_nodes

**Comment by pailhead** [comment]
This might be a solution for this feature:

```
const _obc = shader => {...}
const obc = `
function (shader){
  const _${ hash() }
  ${ _obc.toString() }
  _obc(shader)
}
`
material.onBeforeCompile = eval(obc)
```

**Comment by pailhead** [comment]
It works

https://codepen.io/pailhead/pen/EGLNzJ
