### ISSUE TITLE
ColladaLoader: wrong opacity in parsing

### ISSUE THREAD

**Issue by chalienge** [mrdoob/three.js#13207]
##### Description of the problem

The collada loader can not recognize transparency correctly. The glass and leaf parts inside the attached model has got two transparent materials, but the opacity properties are wrong when loaded into the scene.

[boi_chamber.zip](https://github.com/mrdoob/three.js/files/1680174/boi_chamber.zip)

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
This is related to https://github.com/mrdoob/three.js/issues/2210#issuecomment-7286036.
```
<transparent opaque="RGB_ZERO">
<color sid="transparent">1.000000  1.000000 1.000000 1.000000</color>
</transparent>
<transparency>
<float sid="transparency">0.000000</float>
</transparency>
```
As a test, the model renders correctly if transparency `0.000000` is replaced with `1.000000` in the model file.

**Comment by Mugen87** [comment]
@WestLangley Does that mean we have to evaluate the `opaque` attribute in order to calculate the correct value for `material.opacity`? Right now the loader performs just this opertation:
```javascript
material.opacity = parameter.float; // parameter.float is the value of the transparency tag
```

**Comment by WestLangley** [comment]
>Does that mean we have to evaluate the opaque attribute in order to calculate the correct value for material.opacity?

Apparently so.
