### ISSUE TITLE
How can I save shadow map as an image?

### ISSUE THREAD

**Issue by vaing4723** [mrdoob/three.js#13200]
I want to save the shadow map render target as an image, and I use the follow method,
At the end of WebglShadowMap render function, I add these codes:

var image = document.createElement('img');
var dataURL = _renderer.domElement.toDataURL();
image.src = dataURL;
document.body.appendChild(image);

![image](https://user-images.githubusercontent.com/12947170/35558266-8d259860-05e2-11e8-9331-29cf2d5ae7e1.png)
Later, I get the image, but there is nothing on it, I only can see a black picture, what's wrong with me ?How can I get it truely? 

And I even attempting to draw the shadow map texture in a plane geometry, I have pass the textureId to the shader, and the fragment shader like this,
![image](https://user-images.githubusercontent.com/12947170/35558228-7036862e-05e2-11e8-91e2-23de65e0cb63.png)
But the result is also show a black color. I can confirm that 'u_texture' and 'v_uv' parameters are correct, but I dont konw why the result.

I need your help,please.

**Comment by Mugen87** [comment]
This is not a help site. Please use the [forum](https://discourse.threejs.org/).

**Comment by vaing4723** [comment]
Can I transfer the topic to the forum directly?

**Comment by vaing4723** [comment]
Can I transfer the topic to the forum directly?

**Comment by Mugen87** [comment]
Unfortunately not.
