### ISSUE TITLE
Object3D.onBeforeRender, Object3D.onAfterRender keep running continuously

### ISSUE THREAD

**Issue by gadlol** [mrdoob/three.js#13202]
##### These callback functions run always...

In the docs : [https://threejs.org/docs/#api/core/Object3D.onBeforeRender](url) it is written:

> An optional callback that is executed immediately before the Object3D is rendered. This function is called with the following parameters: renderer, scene, camera, geometry, material, group.

"is executed" not "is keep executed continuously"...

From my tests these callback functions keep running.

I dont know if it should run continuously or not but the docs and the functionality differs.

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [x] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I would say the documentation correct. It says: _An optional callback that is executed immediately before the Object3D is rendered._ The object is rendered each frame, thus the callback is fired each frame, too.

**Comment by gadlol** [comment]
Hmm, if that's the case you are right...

**Comment by Mugen87** [comment]
You can check the source code if you wish to be on the safe side 😉 

https://github.com/mrdoob/three.js/blob/f09e1a6a9b8ba6018efdf7d707e8a4f59c0f9d84/src/renderers/WebGLRenderer.js#L1434-L1461
