### ISSUE TITLE
FBXLoader: Find a bug in the code that leads to load fail.

### ISSUE THREAD

**Issue by nNightKil** [mrdoob/three.js#13212]
##### Description of the problem

Find a little bug in FBXLoader.  See the code in the following picture:
![image](https://user-images.githubusercontent.com/13641738/35617000-e38efe6a-06b1-11e8-82e3-2b107cf41eab.png)

when the "children" is undefined, the "fileName" is undefined, too.
and the below code doesn't consider this condition and call `fileName.indexOf`.
It will result a error and load fail.
need add:
`if (fileName !== undefined && (...))`

##### Three.js version

- [x] Dev
- [ ] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by acc-firala** [comment]
I had this exact problem - my FBX fails to load because of line 341. 

However - I tried out your change and this causes a GET 404 in line 347 (because filename still is undefined, right?)

**Comment by looeee** [comment]
I'll take a look at this and other FBXLoader issues tomorrow

**Comment by looeee** [comment]
@nNightKil @acc-firala could you share the files that are causing issues? 

A fix should be pretty easy but it would be best if I can test it against you files.

**Comment by nNightKil** [comment]
I add the code by myself and then my model had shown right. But I load another model just now and  failed.
[testError.zip](https://github.com/mrdoob/three.js/files/1685396/testError.zip)

**Comment by acc-firala** [comment]
Unfortunately my files are under NDA of client. Wish I could share. When I convert the Binary FBX to ASCII with Maya, the same happens.

**Comment by looeee** [comment]
@nNightKil your testError.fbx doesn't have any textures so the `loadTexture` function never gets called. 

Anyway, the issue should be fixed in #13228
