### ISSUE TITLE
FBXLoader: Wrong Normal Data for lighting

### ISSUE THREAD

**Issue by nNightKil** [mrdoob/three.js#13214]
##### Description of the problem
I update the FBXLoader today and find that it show wrong normal (I guess is the normal) when lighting for some fbx model. I will show different view for the same scene in the following, note that I have set the intensity of the directional light to 1000 ( I think big enough ). However, it shows wrong effect.

![image](https://user-images.githubusercontent.com/13641738/35626037-61e09ee6-06cf-11e8-84b9-d56b3104baed.png)
![image](https://user-images.githubusercontent.com/13641738/35626057-6d6b2d4e-06cf-11e8-95d9-42127858a7a4.png)
![image](https://user-images.githubusercontent.com/13641738/35626068-7a17b008-06cf-11e8-8e9c-44f59c64a546.png)
![image](https://user-images.githubusercontent.com/13641738/35626073-81eff358-06cf-11e8-80be-662aea13a661.png)

## It show in **r87** like (the sun icon is a directional light):
![image](https://user-images.githubusercontent.com/13641738/35626243-0bbeaa70-06d0-11e8-8442-c2bf349416e7.png)

## and in **r89**:
![image](https://user-images.githubusercontent.com/13641738/35626183-de417d66-06cf-11e8-8bed-3c4cdb105642.png)

## **In addition**, reversely in **r87**, the FBXLoader also has some bugs (the icon in the scene is a rectarea light)：
![image](https://user-images.githubusercontent.com/13641738/35626420-a9056972-06d0-11e8-8c63-b5a9f9a95c02.png)

## which show in **r89**:
![image](https://user-images.githubusercontent.com/13641738/35626556-11288be2-06d1-11e8-8674-6a8ecfc06d23.png)

So I think when fix some bug in r89, it maybe leads to the oppositive bug.

##### Three.js version

- [x] Dev
- [x] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
Can you share the models? I'll take a look

**Comment by nNightKil** [comment]
[testModel.zip](https://github.com/mrdoob/three.js/files/1684280/testModel.zip)

These are the model that result the problem. I just simplify the two model.  Which show wrong in the website editor is the "testSofa1.fbx", and the "testIron.fbx" is which show wrong in r87.

**Comment by looeee** [comment]
testIron.fbx looks fine. 

testSofa.fbx is missing textures so it appears black. Can you provide the textures as well?

**Comment by nNightKil** [comment]
What I get is just this model without textures. So it's neccessary for the model have the textures? But in r87, it show right.

r87:
![image](https://user-images.githubusercontent.com/13641738/35676618-602d629c-0787-11e8-9eea-81ba399c6a46.png)

r89:
![image](https://user-images.githubusercontent.com/13641738/35676648-7bdfd9ca-0787-11e8-8721-ac4499eb13c7.png)

I try it and guess the angle between what in r89 and the realistic light has a bias of 90 degree.

**Comment by WestLangley** [comment]
>note that I have set the intensity of the directional light to 1000 ( I think big enough )

1 is big enough. That is a clear sign the normals are not correct.

In r.88 the normals appear correct, and the model is loaded on its side.

![screen shot 2018-02-01 at 10 45 20 am](https://user-images.githubusercontent.com/1000017/35687724-74f64134-073d-11e8-8d0d-b904ad3bc539.png)

In r.89, the normals are not correct, and the model is loaded right-side-up.

![screen shot 2018-02-01 at 10 47 05 am](https://user-images.githubusercontent.com/1000017/35687792-a1ef0d60-073d-11e8-9433-b2c53a2c5da8.png)

**Comment by looeee** [comment]
This issue is that I applied the pre transform to the vertices, but not to the vertex normals. Kind of obvious that I would need to do that in hindsight...

Fixed in #13290
