### ISSUE TITLE
WebVR Origin Trial Tokens

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#13218]
I'm being told the tokens expired on the 21st. How do you usually request them?

**Comment by Mugen87** [comment]
I'm using this form:

 https://docs.google.com/forms/d/e/1FAIpQLSeTp7amHWjumMZpJBklt0gCuD8QbSHIPlrp5_EVzCYWhf_uEg/viewform

**Comment by mrdoob** [comment]
I see. Do you mind requesting new ones?

**Comment by Mugen87** [comment]
When the tokens expire, i automatically get an email with a new form for the upcoming tokens. The current tokens are still valid up to February 26. 

I request new tokens as soon i get the respective notification.

**Comment by mrdoob** [comment]
I see what happened. We updated it on `dev` but I forgot to cherry-pick to `gh-pages`.
Fixed! https://github.com/mrdoob/three.js/commit/16ea8233436c87156c851211242de437e944f316
