### ISSUE TITLE
[BUG] Can't get gl.VERSION correctly.

### ISSUE THREAD

**Issue by finscn** [mrdoob/three.js#13210]
https://github.com/mrdoob/three.js/blob/e2973b76f11de536975ee1a8d0776e15aaca9e69/src/renderers/webgl/WebGLState.js#L345

on some android platforms ,  the code 
```
/^WebGL\ ([0-9])/.exec( gl.getParameter( gl.VERSION ) )
```
will return `null`  (because there is no `WebGL`, only `OpenGL ES`),
so , this line will take an error `Cannot read '1' of null`.

### Suggestion : 
change to 
```
var version = /^WebGL\ ([0-9])/.exec( gl.getParameter( gl.VERSION ) );
version = version ? parseFloat(  version[ 1 ] ) : 1.0; 
```

**Comment by eastecho** [comment]
Same here.

I'm running three.js with WeChat platform, the same problem occured.

**Comment by Mugen87** [comment]
> (because there is no WebGL, only OpenGL ES)

Does that mean you are not using `three.js` in a browser but in a WebView or something?

**Comment by finscn** [comment]
@Mugen87  , in browser , but it's the built-in browser of  custom ROM .
In China , there are many custom ROMs in different android phones.

**Comment by Mugen87** [comment]
I'm curious how these browser internally work 🤔. They have a WebGL API but no WebGL implementation?

**Comment by finscn** [comment]
@Mugen87  , they could run many webgl app , just information of gl.VERSION is incorrect.
So magic ...

**Comment by Mugen87** [comment]
I've realized that there is already a PR for introducing OpenGL ES support: #13046

@finscn Can you please check what's different compared to your PR? I think one PR that tackles the issue is sufficient.

**Comment by finscn** [comment]
@Mugen87  , I read the  #13046 , and it inspires me.
I've updated my PR.
Now , I think . my PR is better than #13046. 
Whatever , thanks , @raindust .
