### ISSUE TITLE
SAOPass: Change blending mode when rendering to screen

### ISSUE THREAD

**Issue by cnspaha** [mrdoob/three.js#13222]
##### Description of the problem

Following case:
1. Render some stuff on the canvas
2. Use SAOPass with ```renderToScreen=true``` for postprocessing
3. Expected behaviour => SAO is being put/rendered over the current canvas
    Actual behaviour     => Canvas is being 'cleaned' with the (probably empty) readBuffer 

The actual behaviour happens because the SAOPass renders the readBuffer (which can be empty) with no blending (```THREE.NoBlending```) on the canvas. Because there is no blending, the canvas gets 'cleaned/overwritten' with this readBuffer.

```javascript
THREE.SAOPass.prototype = Object.assign( Object.create( THREE.Pass.prototype ), {
	constructor: THREE.SAOPass,

	render: function ( renderer, writeBuffer, readBuffer, delta, maskActive ) {

		// Rendering readBuffer first when rendering to screen
		if ( this.renderToScreen ) {

			this.materialCopy.blending = THREE.NoBlending; // <-- HERE!!!!!!!
			this.materialCopy.uniforms[ 'tDiffuse' ].value = readBuffer.texture;
			this.materialCopy.needsUpdate = true;
			this.renderPass( renderer, this.materialCopy, null );

		}
```

Possible Fix:
Instead of ```THREE.NoBlending``` we could use ```THREE.NormalBlending``` so the readBuffer doesn't 'clean/overwrite' the canvas with its content.

```javascript
THREE.SAOPass.prototype = Object.assign( Object.create( THREE.Pass.prototype ), {
	constructor: THREE.SAOPass,

	render: function ( renderer, writeBuffer, readBuffer, delta, maskActive ) {

		// Rendering readBuffer first when rendering to screen
		if ( this.renderToScreen ) {

			this.materialCopy.blending = THREE.NormalBlending; // <-- HERE!!!!!!!
			this.materialCopy.uniforms[ 'tDiffuse' ].value = readBuffer.texture;
			this.materialCopy.needsUpdate = true;
			this.renderPass( renderer, this.materialCopy, null );

		}
```

/ping @Mugen87  @mrdoob 

I don't mind providing a PR if my suggestion is fine with you.

##### Three.js version

- [x ] Dev

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
It seems to work [here](https://threejs.org/examples/webgl_postprocessing_sao.html) with the following setup:
```javascript
composer = new THREE.EffectComposer( renderer );
renderPass = new THREE.RenderPass( scene, camera );
composer.addPass( renderPass );
saoPass = new THREE.SAOPass( scene, camera, false, true );
saoPass.renderToScreen = true;
composer.addPass( saoPass );
```
What is different in your application from the example's code?

**Comment by cnspaha** [comment]
yeah sure the "normal" way works like intendend. 

But I have one problem. When drawing Lines/LineSegments and draw them via RenderPass (or a custom one) into a framebuffer I have problem with AA. I can use SMAA, FXAA or similar but the results will be way worse than when drawing lines directly on the canvas and not into an FBO.

So my intention was that I draw ALL STUFF (background, lines, model) directly on canvas, so the lines are like I want them to be. And with my change, I suggested, everything works fine because the SAO is simply put over my rendered stuff. But with the current implementation 'NoBlending' material clean away my previous rendered stuff on the canvas.
Below some images for better understanding of my problem ;) 

Like I want it to be (with my changes and everything rendered directly canvas):
![1](https://user-images.githubusercontent.com/22448974/35719813-74eebfb4-07eb-11e8-9626-10bde47060f8.png)
The "normal" way (rendering to FBO), see the ugly lines:
![2](https://user-images.githubusercontent.com/22448974/35719811-74c4bb24-07eb-11e8-9f4e-65a5d0ec6cc3.png)
The "normal" way with applied SMAA, still ugly lines:
![3](https://user-images.githubusercontent.com/22448974/35719812-74daef52-07eb-11e8-8325-7e7a59064813.PNG)

**Comment by Mugen87** [comment]
I understand your use case. But with this change `SAOPass` would behave differently compared to other passes in the repo. I'm a little bit concerned about the PR's consistence...

**Comment by WestLangley** [comment]
> the SAOPass renders the readBuffer (which can be empty) 

Can you please elaborate?

Also can you provide live links of your examples?

**Comment by cnspaha** [comment]
@WestLangley 
yeah, just prepared a little example
https://jsfiddle.net/s3rjfcc3/12/
as you can see, you only see the green cube+SAO but the red cube is also rendered but overwritten/cleared by the SAOPass, see images below.

In this example the readbuffer isn't empty, it's the green cube. But if it would be empty (no ```THREE.RenderPass```) you would only see black.

```javascript
    function animate() {
      requestAnimationFrame(animate);
      renderer.render(scene2, camera); // rendering of red cube to screen/canvas

      composer.render(scene, camera); // rendering of green cube + SAO to screen/canvas
    }
```

What I expect:
![1](https://user-images.githubusercontent.com/22448974/35790714-142ae670-0a44-11e8-9541-e81832c6dc72.PNG)
What I get:
![2](https://user-images.githubusercontent.com/22448974/35790715-144b309c-0a44-11e8-92a3-813ff79c0ca2.PNG)

Spector.js:
left side is with my changes, right side without my changes:
![3](https://user-images.githubusercontent.com/22448974/35790713-141067e6-0a44-11e8-9ffe-3cce0cf2b675.PNG)
you can see, on the left side the SAOPass is being blended with the previous rendered red cube => ```THREE.NormalBlending```, on the right side its ```THREE.NoBlending```

**Comment by WestLangley** [comment]
```javascript
renderer.render(scene2, camera); // rendering of red cube to screen/canvas
composer.render(scene, camera); // rendering of green cube + SAO to screen/canvas
```

That is not how `EffectComposer` was designed to be used.

```javascript
composer = new THREE.EffectComposer( renderer );

renderPass = new THREE.RenderPass( scene2, camera );
composer.addPass( renderPass );

renderPass = new THREE.RenderPass( scene, camera );
renderPass.clear = false;
composer.addPass( renderPass );
```

**Comment by cnspaha** [comment]
@WestLangley 
yeah I know how it SHOULD be used, but as stated in my second post, if I use it like this the lines just look very bad... so I tried to render everything on screen instead. but when I set ```renderToScreen=true``` on every pass, the lines will look fine, but then the SAOPass cleans the canvas (with its content) with ```THREE.NoBlending```  before rendering the SAO on Top of it.

**Comment by WestLangley** [comment]
You are free to modify `EffectComposer` to your liking. It is part of the examples, not the core library.

Or try an antialiasing post-processing pass.

**Comment by Mugen87** [comment]
I agree to @WestLangley. I don't see a need to make a PR for this, sry.

**Comment by mrdoob** [comment]
Agreed.
