### ISSUE TITLE
ObjLoader object.children not of type Mesh 

### ISSUE THREAD

**Issue by agilecollab** [mrdoob/three.js#13226]
##### Description of the problem

When using es6 syntax ObjLoader does not return instances of Mesh as suggested within the example code.  

```
import { Mesh, ... } from 'three';
import { ObjLoader } from 'three-addons';

...

const objLoader = new OBJLoader(manager);
objLoader.load('models/model.obj', object => { 

  object.traverse(child => {
  console.log(child) // Obj {..., type: "Mesh", ...} 

    if(child instanceof Mesh) { //This condition fails,
      ... apply texture ... 
    }

  }
});

```

##### Three.js version

- [ ] Dev
- [ x] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by agilecollab** [comment]
Tested with my model as well as the example code Male02.obj and my desired object with the same result. changing the condition to `child.type === 'Mesh'` appears to work.

**Comment by agilecollab** [comment]
Changing the condition to `child.isMesh` also appears to work.

**Comment by Mugen87** [comment]
Maybe there is a problem within the `three-addons` npm module. What happens when you directly use the code of the latest `OBJLoader` from here:

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/OBJLoader.js

**Comment by mrdoob** [comment]
Yeah the `OBJLoader` in `three-addons` may be old. But our current `OBJLaoder` still has some `instanceof`.

**Comment by agilecollab** [comment]
Thanks for the info guys, mucho appreciated. 

The version of OBJLoader within the examples expects `THREE` to be defined within the global scope, which I would prefer not to do... as I would have to specifically modify my webpack config to expose THREE globally. 

I'm in the process of creating a PR for `three-addons` to update their version of OBJLoader to the current implementation... hopefully that will resolve this :)

Thanks!

**Comment by mrdoob** [comment]
Thank you!
