### ISSUE TITLE
OrbitControls scope.update() calls slow rendering if update() is called in render loop

### ISSUE THREAD

**Issue by dustinkerstein** [mrdoob/three.js#13234]
If you're calling controls.update() in the render loop (ie. to enable damping / momentum) you may end up with a performance issue due to the extra update() calls. I've only tested this with handleTouchMoveRotate but I imagine the same can be reproduced on all of the places where scope.update() is called in OrbitControls (rotate, handleMouseMoveRotate, handleMouseMoveDolly, etc.) I also only have really noticed this on iOS devices, though I'm sure has an effect elsewhere. 

For now, I've just commented out all of the scope.update() calls and things seem much happier on the devices that I've tested.

I'm not sure if this is something that needs to actually be fixed in OrbitControls or maybe just documented but I figured I'd open an issue either way.

##### Three.js version
- [X] r89

##### Browser
- [x] All of them

##### OS
- [x] All of them

**Comment by WestLangley** [comment]
Can you please provide a live example to demonstrate the issue?

**Comment by dustinkerstein** [comment]
> Can you please provide a live example to demonstrate the issue?

I just tried to reproduce on the example OrbitControls but I wasn't able to rep. I think it may just be due to the different type of CPU/GPU load compared to my original app. I'll keep trying to put together a simple test.

**Comment by dustinkerstein** [comment]
I guess we can just leave this issue closed but for reference. It definitely has an appreciable effect on my app, but I don't really have time to build another example and can't post the source of my app at this time.
