### ISSUE TITLE
Force material update from CanvasTexture to allow change of canvas content?

### ISSUE THREAD

**Issue by dekdevy** [mrdoob/three.js#13233]
Hello,

I have a problem with CanvasTexture / material.
When you create a Material in Threejs and give it a CanvasTexture as a map, you actually need to call renderer.render() before the content of the canvas is copied into WebGL memory.
Because of this, it is necessary to keep the canvas image contents in memory and you cannot modify them until you actually force the material to update.

What I would like to do is:
Create one canvas element and draw something into it (Text).
Then, I want to create a material and copy the canvas contents. 
Next, Id like to clear the canvas and write another text into it, create a material, and so on..
This can happen as often as 50-100 times per frame (damage numbers and nameplates in an RPG) when bigger parts of the scene are updated at once. Even pre-caching a bunch of canvases in order to reuse them in a round-robin way has already improved performance but also falls victim to other problems (materials that are invisible / culled, for example - as they also do not update).

This is problematic, because as of right now, I have to create hundreds of canvas elements and keep them around for a long time. This is a lot of overhead that could simply be solved if there was some way to force a material update or somehow hardcopy the data out of a canvas and use it as a map.

**Comment by Mugen87** [comment]
Maybe you can utilize [WebGLRenderer.compile()](https://threejs.org/docs/index.html#api/renderers/WebGLRenderer.compile) for this use case?

**Comment by dekdevy** [comment]
@Mugen87  I have looked into this but its unfortunately too massive to call live on a running 60 fps application. I edited my post above, in some occasions it can happen that i need to create 50 or more sprites in a single frame (an RPG, where a lot of damage numbers could pop up at any time, or a zone with NPCs is loaded into the world and their name plates are created at the same time). 
So working with a round-robin system of cached HTML elements that get freed up every frame works, but it still causes problems when materials are loaded that are not rendered instantly, for example a spriteText that is invisible until later.
Is there a way to at least force materials to update on the next render call, even if they are set to .visible = false?

**Comment by aardgoose** [comment]
@dekdevy Have you considered using a glyph atlas - one canvas, texture and material.  Text selected by geometry, and you can cache the geometries for commonly used strings and use across multiple objects.

No canvas creation or texture uploading apart from initial creation of atlas and material use.

Needs a custom shader but works well for my use case.

https://github.com/aardgoose/CaveView.js/blob/dev/src/js/materials/GlyphMaterial.js
https://github.com/aardgoose/CaveView.js/blob/dev/src/js/core/GlyphString.js

**Comment by dekdevy** [comment]
@aardgoose looks interesting, but if I understand this correctly, its not designed to dynamically create new texts on the fly, correct? 
The rendering itself looks great though (kerning etc). Does it use one drawcall per glyph or one per word?

**Comment by aardgoose** [comment]
I use it to create strings as needed (ie on the fly), but many strings are repeatedly used so I cache the geometries to avoid overhead (memory and creation time).

1 draw call per string. Instanced attributes to reduce vertex data to min,  so just four values per character in attributes.

This is really StackExchange material rather than a three.js issue though.
