### ISSUE TITLE
Baking ambient occlusion to texture dynamically

### ISSUE THREAD

**Issue by DVLP** [mrdoob/three.js#13230]
##### 

It would be good from performance perspective to be able to dynamically bake ambient occlusion once on scene load instead of using post processing. This would be good for i.e. procedurally generated levels. Currently achieving GI is either by using prebaked scenes from 3d software or using Effect Composer that costs performance

I'd like to be able to export scenes from my modified three.js editor and bake GI when the level loads in the game https://stackoverflow.com/questions/48572818/dynamic-ambient-occlusion-baking-in-three-js

##### Three.js version

- [ ] Dev
- [ x] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Please do not cross-post help questions here.

**Comment by DVLP** [comment]
What about now? This is a genuine feature request not just cross posting
