### ISSUE TITLE
PolyhedronGeometry is not working with Materials Array.

### ISSUE THREAD

**Issue by smatthews1999** [mrdoob/three.js#13240]
##### Three.js version
- [ ] Dev
- [x] r89
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [X ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

I cannot set PolyhedronGeometry with an array of materials, as I can with BoxGeometry.  The shape is only taking the first material.
Here is a CodePen to illustrate the problem.
https://codepen.io/smatthews1999/pen/paygLQ?editors=1010

- note - when looking at a wireframe version of the wedge shape, it has 8 facets, so I am using 8 materials.  (This worked back when the implementation was MeshFaceMaterial)

**Comment by WestLangley** [comment]
You need to set the material index for each face.
```javascript
for ( var i = 0; i < wedgegeo.faces.length; i ++ ) {

    wedgegeo.faces[ i ].materialIndex = i % 8;
 
}
```

Try the forum if you need more help.

**Comment by smatthews1999** [comment]
Thank you.
