### ISSUE TITLE
THREE.WebGLShader: Shader couldn't compile. Native browser on Samsung S4 Android 4.2 

### ISSUE THREAD

**Issue by yairans** [mrdoob/three.js#13245]
Hi 
I'm using three.js for 360 degree video.
on Native browser + Samsung S4 + Android 4.2 I get this [error](https://github.com/mrdoob/three.js/files/1692944/error.txt)
in Chrome browser on this device it works well.

**Comment by Mugen87** [comment]
This error should be fixed since `R88` via #12248. What version of `three.js` are you using?

**Comment by Mugen87** [comment]
Closing. We can reopen if the problem still exists with `three.js` > `R88`.
