### ISSUE TITLE
Docs imply that `BufferGeometry.attributes.index` exists

### ISSUE THREAD

**Issue by mysteryDate** [mrdoob/three.js#13257]
https://threejs.org/docs/#api/core/BufferGeometry

Under the section `Accessing Attributes`, `index` is listed as a buffer attribute. It should probably noted that this is actually on `geometry.index` not `geometry.attributes.index`.

I can fix the document if you all want.

**Comment by mrdoob** [comment]
> I can fix the document if you all want.

Yes please! 😊
