### ISSUE TITLE
THREE.LoadingManager onError too vague

### ISSUE THREAD

**Issue by tlorton1** [mrdoob/three.js#13258]
##### Description of the problem

I am using `THREE.LoadingManager()` to have a manager for `THREE.FBXLoader()`.

When I use `manager.onError()` to check my console errors, it only says there is an error and doesn't say anything else. Will this be improved in the future? It would be nice to know more about the error. Here is the console:

![loadingmanageronerror](https://user-images.githubusercontent.com/26261876/35833920-1a090f6a-0a88-11e8-94ad-78d1e8343949.png)

And here is the onload function:

 ```javascript
            var camera = new THREE.PerspectiveCamera(25, 1, 1, 2000);
            var scene = new THREE.Scene();

            var manager = new THREE.LoadingManager();
            manager.onStart = function(url, itemsLoaded, itemsTotal) {
              console.log( 'Started loading file: ' + url + '.\nLoaded ' + itemsLoaded + ' of ' + itemsTotal + ' files.' );
            };
            manager.onProgress = function(item, loaded, total) {
              console.log(item, loaded, total);
            };
            manager.onLoad = function() {
              console.log('Loading Complete!')
            }
            manager.onError = function(url) {
              console.log('There was an error loading: ' + url);
            }


            var onProgress = function(xhr) {
              if (xhr.lengthComputable) {
                var percentComplete = xhr.loaded / xhr.total * 100;
                console.log(Math.round(percentComplete, 2) + '% downloaded');
              }
            };
            var onError = function(xhr) {};


            var loader = new THREE.FBXLoader(manager);
            loader.load(xhr.responseURL, function(object) {
              scene.add(object);
              console.log(object);
            }, onProgress, onError);

            var renderer = new THREE.WebGLRenderer();
            renderer.setPixelRatio(window.devicePixelRatio);
            renderer.setSize(500, 500);
            renderer.render(scene, camera);
            var container = document.getElementById("ava");
            container.appendChild(renderer.domElement);

```
##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by pailhead** [comment]
The loader however does return an error? You want all of them to bubble up through the manager?

**Comment by Mugen87** [comment]
Yeah, it should be sufficient when the loader reports the error.

**Comment by tlorton1** [comment]
My point is that it reports an error, yes, but it doesn't elaborate on the error. So how am I supposed to know what the error is?

**Comment by Mugen87** [comment]
Try the following:
```javascript
function onError( error ) {

   console.error( error );

}

var loader = new THREE.FBXLoader( manager );
loader.load( url, onLoad, onProgress, onError );
```
Do you see more information now?

**Comment by tlorton1** [comment]
Thank you so much! I now have another issue, [here](https://github.com/mrdoob/three.js/issues/11579), with inflate.min.js not being able to import.
