### ISSUE TITLE
Bundler & Minifier

### ISSUE THREAD

**Issue by eugenco** [mrdoob/three.js#13269]
##### Description of the problem

Bundler & Minifier failed when analize and working with three.js file:

4 errors:
Can't have 'break' outside of loop: break linear_scan
Can't have 'break' outside of loop: break linear_scan
Can't have 'break' outside of loop: break validate_interval
Can't have 'break' outside of loop: break handle_stop

##### Three.js version

- [ ] r89

**Comment by Mugen87** [comment]
Do you mean this tool? https://github.com/madskristensen/BundlerMinifier

I guess it makes more sense to file a bug at the project's repo. This is not a `three.js` related issue.

**Comment by eugenco** [comment]
Problem in three.js file:
wrong using 'break' js keyword

P.S. yes this tool: https://github.com/madskristensen/BundlerMinifier

**Comment by Mugen87** [comment]
Just out of curiosity: Does the tool indicate the problematic lines? `break` is used 175 times in the `three.js` build file...

**Comment by eugenco** [comment]
4 errors:
Can't have 'break' outside of loop: break linear_scan
Can't have 'break' outside of loop: break linear_scan
Can't have 'break' outside of loop: break validate_interval
Can't have 'break' outside of loop: break handle_stop

no more info

**Comment by Mugen87** [comment]
Too bad 😞

**Comment by donmccurdy** [comment]
Likely this issue with BundledMinifier, not threejs: https://github.com/madskristensen/BundlerMinifier/issues/252

**Comment by Mugen87** [comment]
There you go! 😊
