### ISSUE TITLE
Binary FBX file fails to animate, whereas ASCII version works perfectly.

### ISSUE THREAD

**Issue by RubiconDev** [mrdoob/three.js#13270]
Hi,

I'm using the FBX loader to load a simple animation of a dice cup. It is very animation with no bones/skeletons. I exported ASCII and binary versions from 3DS Max.

Both the ASCII and the binary version of the file load fine, but only the ASCII version animates.

I've attached the fbx file here.
[cup.zip](https://github.com/mrdoob/three.js/files/1)

The loader reports:
THREE.FBXLoader: FBX binary version: 7300

Thanks for your help,

Steve.

##### Three.js version

- [ ] Dev
- [ ] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
ALL

**Comment by Mugen87** [comment]
Looks like your `FBX` file is not attached correctly. Can you please have a look?

**Comment by RubiconDev** [comment]
Sorry about that. This any better?

[cup.zip](https://github.com/mrdoob/three.js/files/1703955/cup.zip)

**Comment by looeee** [comment]
The animation is playing fine for me. Please make sure you are using the lastest version of the FBXLoader from the dev branch.

**Comment by RubiconDev** [comment]
Thanks for the fast response. All sorted now. 

Steve.
