### ISSUE TITLE
STLLoader not working and no error to trace back

### ISSUE THREAD

**Issue by tymiao1220** [mrdoob/three.js#13278]
I am new with STL format image, and currently using STLLoader to load geometry and display on the screen. For some .stl file I am able to do so (generated from 3d Slicer) whereas for some of them ( created from itk) STLLoader are not able to load file, and no error pop up.

When I break into the `STLLoader.js` code in vary first `load: function()`, I find `loader.load()` is not able to load stl file successfully, and then just skip it for some reason.

Could someone give me some hint, I attached stl file that is not working.

Thanks in advance!

[Not working stl file](https://github.com/tymiao1220/not-working-stl.git)

**Comment by donmccurdy** [comment]
The file renders on GitHub (https://github.com/tymiao1220/not-working-stl/blob/master/out.stl), which uses three.js, so this is probably an error with how you're loading the file. 

We can't provide help through this issue tracker, but if you can post your code on the [forum](https://github.com/tymiao1220/not-working-stl/blob/master/out.stl) someone should be able to take a look.
