### ISSUE TITLE
Raycast tool does not work properly and something wrong with vertices updating

### ISSUE THREAD

**Issue by yiakwy** [mrdoob/three.js#13273]
##### Description of the problem
I am developing a sidebar toolkit which switch modes between selecting objects and non-selecting objects.

To summarize,

P1 raycaster does not work as expected
P2 vector.unproject might not be accurate
p3 when object position updated, its vertices keep values in the last frame

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

## Details

I build a series of LineSegments from a topological parameters computation server I build. I want let users to select line segments they desire to test global navigation functionality. 

(1) P1, raycaster does not work
Initially, I wanted use raycaster to project mouse onto plane position

```js
		// collect intersects
		var intersects = []
		
		// https://stackoverflow.com/questions/17216039/how-to-pick-lines-in-three-js
		// see the discussion, this might not work as expected
		// intersects = raycaster.intersectObjects(this.context.scene, true)
		intersects = this.intersectObjects(roads, floorGroup, raycaster)

```
The raycaster is built using the following codes

```js
		let raycaster 
		if (this._camera instanceof THREE.PerspectiveCamera) {
			
			raycaster = new THREE.Raycaster()
			let vec = new THREE.Vector3(this._mouse.x, this._mouse.y, 1)
			vec.unproject(this.context.camera)
			raycaster.set(this.context.camera.position, vec.sub(this.context.camera.position).normalize())

```

This would not work because it returns empty array everytime when I try to "pick". The scene (I have "quadTree" & "Division" and inverse-query table for indexing but I muted them to test the functionalities for the moment) contains base floor built from plane geometry, and some other floor segments where roads placed on.

I am frustrated because the codes seem to be correct.

(2) P2, Ok I built my own raycaster and everyting works good until I found some unpleasant problems:
(2-1) After unprojected mouse vector , I solved equation P0 + t*Dir = P where P.y = 0, then I triggered quadtree to collect objects nearby. If they are selected, I will flip the hex color value.
But, I found that the solution point does not perfectly coinside with mouse position on my screen. There is always a shift between the mouse on screen and point drawed on 3d world. Because the equation is simple, I suspect that the error has some relationship with "unproject" method.

(2-2) Since quadtree just uses my AABB to collect candidates, they are not true targets I wanted. I need to perform more rigorous tests. However I found after setting the position of the intersected point or sphere, the vertices are not updated accordingly.

```js
			this.trackball.position.set(clickpos.x, 0, clickpos.z)
			this.verticesNeedUpdate = true
```

This will prevent me to produce a good functionality for developers and customers.

**Comment by Mugen87** [comment]
This is not a help site. It's for bugs and feature request only.

Please use the [forum](https://discourse.threejs.org/) and provide [live demos](https://jsfiddle.net/f2Lommf5/) or reduced test cases that illustrates your problems. 

You should also have a closer look to the official examples. The following one shows how to create interactive lines via `Raycaster`.

https://threejs.org/examples/#webgl_interactive_lines

**Comment by yiakwy** [comment]
@Mugen87 Hello Thank you for the reference. I have read the codes. I think the most different part is
```js
raycaster.linePrecision = 3;
```
and I tested on 

```js
		intersects = raycaster.intersectObjects(roads, true) [ok]
		intersects = this.intersectObjects(roads, floorGroup, raycaster) [ok]

```

It works. thanks.

**Comment by yiakwy** [comment]
@Mugen87 Sadly, it sometimes works, but sometimes not.  I use the following structure now

```js
intersects = raycaster.intersectObjects(roads, true)
if (intersects.length > 0) {
// update sphere position and get intersection of sphere between the floor
} else {
intersects = raycaster.intersectObjects(roads, true)
}
```

Could you explain me how does raycaster compute "intersection point"? 

I am also still confused for the problem 2.

**Comment by donmccurdy** [comment]
@yiakwy please ask on the forum.
