### ISSUE TITLE
Examples: panorama_equirectangular does not support touch controls

### ISSUE THREAD

**Issue by ramkalyan** [mrdoob/three.js#13275]
##### Description of the problem

Mobile touch is not working for the following example:

https://threejs.org/examples/webgl_panorama_equirectangular.html

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by Mugen87** [comment]
The example as many others only support mouse controls right now.
