### ISSUE TITLE
Outline pass not working properly with an orthographic camera

### ISSUE THREAD

**Issue by DIeHarke** [mrdoob/three.js#13274]
##### Description of the problem

As the title imposes the outline pass have an issue, when you use an orthographic camera (instead of a perspective one). The behavior of the decision, whether the edge is visible or hidden is different (and actually not correct). An outline segment is "marked" as hidden if something is drawn in front or behind the segment. Only if there is nothing else than the background the outline segment is "marked" as visible.

Here is an image showing the issue:

![Outline Pass Orthographic Camera Issue](https://i.imgur.com/T7mdhjm.png)

And I also included a jsfiddle:

* [jsfiddle](https://jsfiddle.net/jjtvd4c1/)

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Demo for testing: https://jsfiddle.net/9a3c8o5a/6/

`OutlinePass` does not support `OrthographicCamera` right now. But changing  `perspectiveDepthToViewZ()` to `orthographicDepthToViewZ()` at the following code section seems to solve the issue.

https://github.com/mrdoob/three.js/blob/4ef0d67dd794220db3ef692f85a77d5b41be7b99/examples/js/postprocessing/OutlinePass.js#L372-L375

**Comment by DIeHarke** [comment]
@Mugen87 Nice that is definitely solving the issue. I haven't put any additional investigations in looking for other problems related to the usage of an orthogonal camera.

**Comment by Mugen87** [comment]
@mrdoob @WestLangley Should we make a PR for this? We could test the camera type and adjust the respective `*DepthToViewZ()` function in the fragment shader.

**Comment by WestLangley** [comment]
Fine with me.

**Comment by Mugen87** [comment]
Solved via #13283
