### ISSUE TITLE
import fbx run Failed to execute 'uniform3fv' on 'WebGLRenderingContext'

### ISSUE THREAD

**Issue by FuS1** [mrdoob/three.js#13281]
Hello All:

I try import [my fbx file ](http://mpinnacle.oss-cn-beijing.aliyuncs.com/island.rar) , but show this error

![image](https://user-images.githubusercontent.com/5563956/36012488-6873f0e8-0d99-11e8-9f44-a21d0260f157.png)

then I try trun 'v' to new Float32Array(v), 

![image](https://user-images.githubusercontent.com/5563956/36012622-4262ffba-0d9a-11e8-8c43-a3b6e64ca8bc.png)

it ok in desktop chrome and andriod chrome

![image](https://user-images.githubusercontent.com/5563956/36012553-d12d76f4-0d99-11e8-9b19-6f827e449d18.png)

however, it show black in IOS chrome.....   Why?

![image](https://user-images.githubusercontent.com/5563956/36012590-0fbb5c2e-0d9a-11e8-94dd-dfc729066d45.png)

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [x] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
chrome in windows 7 
chrome in iphone 7
chrome in ipad 2 pro

**Comment by looeee** [comment]
I don't get any errors when loading this with the latest dev version. However it is black - maybe related to #13214?

**Comment by FuS1** [comment]
Can I see your code, and FBXLoader.js ?
Thank you
