### ISSUE TITLE
THREE.Water reflections break when a object with depthWrite false is in view

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#13287]
With the new water that was introduced a couple versions ago, I am seeing (what appears to be) the same issue that occurred a long time ago with the original water system that THREE.Water was based on.

https://github.com/jbouny/ocean/issues/12

I am seeing this exact same behavior in my game (r89).

I do not have a fiddle up and ready yet, but I will tomorrow.

Chrome 64.

**Comment by mrdoob** [comment]
> I do not have a fiddle up and ready yet, but I will tomorrow.

Thanks!

**Comment by titansoftime** [comment]
Closing as I cannot reproduce the issue in a fiddle.

Will keep trying, will update if I find anything.

**Comment by titansoftime** [comment]
I have FINALLY been able to reproduce this issue in a fiddle (after practically porting my whole game over to a fiddle lol).

The issue occurs whenever a material with depthWrite (at least spriteMaterial, haven't tested others) set to false is in frustum.

If you move the camera a bit up/down left/right you will see the reflections go crazy.

Here is the fiddle. I removed most non-relevant pieces.

https://jsfiddle.net/titansoftime/cafv1k78/

**Comment by mrdoob** [comment]
Do you mind describing a little bit more what the issue is?

**Comment by titansoftime** [comment]
When a material with depthWrite set to false is in view, reflections are broken. I do not know why, but my fiddle demonstrates this issue.

This was not an issue before this example was refactored a couple years ago.

**Comment by Mugen87** [comment]
It seems the issue can be solved by making the water's material opaque:

https://jsfiddle.net/nz7tmpka/1/

I do see a reason why the material is transparent right now. If nobody has objections, I'll make a PR with the fix.

**Comment by titansoftime** [comment]
I use transparency to simulate clearer waters in some situations, it's a nice effect. But honestly at this point, I'd just be happy to use the current version as opposed to having to maintain a 2 year old version separately (which does work with transparency).
