### ISSUE TITLE
SAO pass not working properly with an orthographic camera

### ISSUE THREAD

**Issue by DIeHarke** [mrdoob/three.js#13286]
##### Description of the problem

As the title imposes the sao pass have an issue, when you use an orthographic camera (instead of a perspective one). Similar to [#13274](https://github.com/mrdoob/three.js/issues/13274) the depth computation is not working properly. Also the proposed solution from @Mugen87 to fix the issue for  [#13274](https://github.com/mrdoob/three.js/issues/13274) is not sufficient enough to solve the problem here.

Image showing the scene rendered with output option: Beauty+SAO:
![Beauty+SAO](https://i.imgur.com/0nbn0AP.png)

Image showing the scene rendered with output option: Depth:
![Depth](https://i.imgur.com/SNrBEyJ.png)

I also created a fiddle demonstrating the problem:
- https://jsfiddle.net/vgs6r3pj/

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
How does this version look to you? https://jsfiddle.net/vgs6r3pj/3/

I've just performed a minor change in `SAOPass` to set the correct value for the define `PERSPECTIVE_CAMERA`. Besides, i've used a different setup for the orthographic camera.

**Comment by DIeHarke** [comment]
Yeah true that was the mistake. Due to my camera near / far plane settings the depth map was clipped. In the DepthLimitedBlurShader you are also able to switch between the camera settings. Is this necessary?

And yes your version looks good to me ;). So need to be more carefull with my camera confiurations then...

**Comment by Mugen87** [comment]
> In the DepthLimitedBlurShader you are also able to switch between the camera settings. Is this necessary?

Good find! I'll make a PR with the fix.
