### ISSUE TITLE
BoxBufferGeometry - computeVertexNormals() on indexed buffer geometry has no effect - needsUpdate undefined

### ISSUE THREAD

**Issue by cybafelo** [mrdoob/three.js#13292]
##### needsUpdate undefined

I think this is a bug - when I create a boxbuffergeometry - it has indexes created automatically - i have six materials - all is fine - 

Now I use the 'computeVertexNormals()' function to make my geometry appear smooth - however - it has no effect.

I step into the code and always the same thing

`this.normalizeNormals();`
`attributes.normal.needsUpdate = true;`

But needsUpdate is undefined - setting it to true has no effect.

I also set the bufferAttribute 'normal' to dynamic - it has also no effect.

What I'm hoping to see is this: (this is a normal box geometry after computeVertexNormals())

![image](https://user-images.githubusercontent.com/5380664/36066998-f9e21c78-0eb4-11e8-885f-c28a2dffe4ec.png)

but instead I see this for my bufferboxgeometry - no matter what i do:

![image](https://user-images.githubusercontent.com/5380664/36067007-21921692-0eb5-11e8-9213-2a41b5bb91d2.png)

##### Three.js version

- [ ] Dev
- [ x] r89
- [ ] ...

##### Browser

- [] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [x ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
VGA compatible controller: Intel Corporation Device 5912 (rev 04)

**Comment by WestLangley** [comment]
You need to use `THREE.BoxGeometry()`to obtain the result you are looking for.

`THREE.BoxBufferGeometry` only shares vertices whose vertex normals are parallel.

The code is working as designed. If you need more help, please use the forum.

**Comment by cybafelo** [comment]
@WestLangley 
Where is the forum - maybe put a link in github so people can know where to go?

I can achieve the effect using boxGeometry - this is not the problem - the problem is that 'needsUpdate' doesn't exist.

this is a similar issue to #9790

Simply closing issues don't make them go away - if this isn't a problem, maybe the real issue is some documentation on the subject -

Using stack-overflow just sent me on endless circular references telling me to set 'needsUpdate' to true -

Would be fine if this setting actually existed.

Ok - well - thanks for telling me what I already knew - and forum link would be helpful.

**Comment by Mugen87** [comment]
There you go: https://discourse.threejs.org/

**Comment by looeee** [comment]
@cybafelo  There is a link to the forum in the text that comes up when you make a new issue. Which you did read, right?

**Comment by mrdoob** [comment]
@cybafelo I've added a link to the forum in the README https://github.com/mrdoob/three.js/commit/d718fb01089fdbc4126eb96eb1473b0493cfcfbb 👍

**Comment by cybafelo** [comment]
super thanks - i don't ready everything always - i tend to skip over things which don't look important - i could have used stack-overflow but i'm under pressure to get a project done and i know using github is the fastest way to get an answer.. thanks i'll checkout the forum..

**Comment by cybafelo** [comment]
anyways I have a new problem now - its on the forum:

https://discourse.threejs.org/t/instanced-geometry-with-multi-material-buffergeometry/1860
