### ISSUE TITLE
Can not change the number of particles of protoplanet example

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#13293]
##### Description of the problem

I tried [protoplanet](https://threejs.org/examples/webgl_gpgpu_protoplanet.html) example, However I noticed that it is not working correctly r86 or later.

[protoplanet example for r85](https://cdn.rawgit.com/mrdoob/three.js/r85/examples/webgl_gpgpu_protoplanet.html) is OK (can change the number of particles).
[protoplanet example for r86 or later](https://cdn.rawgit.com/mrdoob/three.js/r86/examples/webgl_gpgpu_protoplanet.html) is NG (can *not* change the number of particles).

I think probably need to add parentheses.
> https://github.com/mrdoob/three.js/blob/r86/examples/webgl_gpgpu_protoplanet.html#L280
```js
//var WIDTH = hash || ( isIE || isEdge ) ? 4 : 64;
var WIDTH = hash || ( ( isIE || isEdge ) ? 4 : 64 );
```

##### Three.js version

- [x] Dev
- [x] r86 or later

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [x] Internet Explorer
- [x] Edge

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

ThinkPad X260 Intel HD Graphics 520

**Comment by Mugen87** [comment]
Yep, that solves the issue for me. Would you like to do a PR with the change?
