### ISSUE TITLE
Crash on Firefox, slow on Internet Explorer and devices (demo provided)

### ISSUE THREAD

**Issue by Richacinas** [mrdoob/three.js#13302]
##### Description of the problem

Hello there,

I researched a lot about this problem and I'm going crazy trying to understand why my example is causing a crash on Firefox, and runs VERY SLOWLY con Internet Explorer and mobile devices.

I'm rendering a big (4K) image on a sphere geometry, trying to create a kind of a pano viewer. In the real application, we can go from one place to the next one, clicking on the invisible shapes that are created inside the sphere.

In the real app, we have a big (4K) video rendering so we have some stuff in a certain area that moves in a loop. However, for this demo I commented those lines (addVideoTexture and renderVideo), so I understand this is not the issue here.

Pay attention to our raycaster, I suspect it is causing big performance problems, but I don't know any other way of detecting when our mouse is going over an "action hotspot" (look above) or a "indicator hotspot" (invisible areas that would allow to go to other places when clicking).

The problem is that this demo is causing a crash on Firefox, and going very very slow on plenty of devices and Internet Explorer.

Thanks a lot...

Ricardo

##### Example:

[https://jsfiddle.net/ggL3uemh/13/](https://jsfiddle.net/ggL3uemh/13/)

##### Three.js version

r89

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [x] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This is not a help site. Please use the [forum](https://discourse.threejs.org/) instead.

**Comment by Richacinas** [comment]
Of course!

I posted it on the forum and StackOverflow already.

Sorry about that
