### ISSUE TITLE
Uncaught TypeError: callback.onProgress is not a function

### ISSUE THREAD

**Issue by tymiao1220** [mrdoob/three.js#13306]
I am new in three js and currently using STLLoader to load some binary STL file for meshing. The problem is after calling 
```
const stlLoader = new THREE.STLLoader();
stlLoader.load(annotationUrl,function(geometry){
//meshing
});

```
I get error said `Uncaught TypeError: callback.onProgress is not a function
    at XMLHttpRequest.<anonymous> (three.js:30839)`

Can someone give me some hint to work around.
Thanks in advance!

**Comment by Mugen87** [comment]
This is not a help site. Please use the [forum](https://discourse.threejs.org/) instead.
