### ISSUE TITLE
How generate Sphere from Vector3 points?

### ISSUE THREAD

**Issue by Odin04ka** [mrdoob/three.js#13307]
var geometry = new THREE.Geometry();
        for (var i = 0; i < 5000000; i ++ ) {
            var vertex = new THREE.Vector3();
            vertex.x = getRandomArbitrary(-100, 100);
            vertex.y = getRandomArbitrary(-80, 80);
            vertex.z = getRandomArbitrary(-100, 100);
            vertex.multiplyScalar(Math.PI);
            geometry.vertices.push( vertex );
        }

        var sprite = new THREE.TextureLoader().load("./textures/sprites/ball.png");
        material = new THREE.PointsMaterial({ size: 2, map: sprite, alphaTest: 0.5, transparent: true });
        particles = new THREE.Points(geometry, material);
        scene.add( particles );

How i can generate sphere from my array points?

**Comment by looeee** [comment]
Please direct help questions to the [forum](https://discourse.threejs.org/).
