### ISSUE TITLE
PlaneHelper.position not translating helper plane

### ISSUE THREAD

**Issue by kpetrow** [mrdoob/three.js#13319]
When trying to position the PlaneHelper It is rotating the helper plane instead of translating.

https://jsfiddle.net/qwzw7spx/

##### Three.js version

- [ ] Dev
- [ X] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [??] All of them
- [X ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
>When trying to position the PlaneHelper

Don't do that. They position themselves.

Please use the forum if you need more help.
