### ISSUE TITLE
Blender Exporter: Error occuring when exporting loose edges as BufferGeometry

### ISSUE THREAD

**Issue by BrunoB69** [mrdoob/three.js#13312]
I get an error if i try to export a particular object from Blender (V2.79) using three.js exporter. 
After some research i have found that it occurs if the object that i try to export has loose edges which are not part of a face. Unfortunately inserting faces for those edges is not an option, because the model that i need to export came from a customer and contains many hundreds of those loose edges. 
I chose to export BufferGeometry which is from my understanding necessary to get the object shown with BasicLineMaterial in threeJS (I am new to three.js).  The object in blender has a wire-frame material assigned. 
There is no error if i choose to export Geometry but then i am not getting anything displayed in three.js (with Firefox). Due to the fact that the original file is far to large, i have created a very small blender model to reproduce the issue which i have added as an attachment. I saved the settings of three.js exporter in that file. You can download it here: 

[LINK DELETED]

Here is the complete error message from blender.

```
Error recorded to None
Traceback (most recent call last):
  File "/home/brunob/.config/blender/2.79/scripts/addons/io_three/__init__.py", line 814, in execute
    exporter.export_scene(filepath, settings)
  File "/home/brunob/.config/blender/2.79/scripts/addons/io_three/exporter/__init__.py", line 20, in inner
    func(filepath, options, *args, **kwargs)
  File "/home/brunob/.config/blender/2.79/scripts/addons/io_three/exporter/__init__.py", line 51, in export_scene
    scene_.parse()
  File "/home/brunob/.config/blender/2.79/scripts/addons/io_three/exporter/scene.py", line 107, in parse
    self._parse_geometries()
  File "/home/brunob/.config/blender/2.79/scripts/addons/io_three/exporter/scene.py", line 185, in _parse_geometries
    geo.parse()
  File "/home/brunob/.config/blender/2.79/scripts/addons/io_three/exporter/geometry.py", line 168, in parse
    self._parse_buffer_geometry()
  File "/home/brunob/.config/blender/2.79/scripts/addons/io_three/exporter/geometry.py", line 446, in _parse_buffer_geometry
    assert(len(attrib_data_in) > 0)
AssertionError

location: <unknown location>:-1
```

This could be related to #11739 but the error message is different.

##### Three.js version

- [ ] Dev
- [x] r89
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
n.a.

**Comment by mrdoob** [comment]
<img width="321" alt="screen shot 2018-02-26 at 7 28 07 pm" src="https://user-images.githubusercontent.com/97088/36709144-40b920b0-1b2b-11e8-827c-c4714ef4e404.png">

I have deleted the link in your post. Either you have a virus on your system or file-upload.net adds viruses to files. Please, embed the file to here instead.

**Comment by BrunoB69** [comment]
Well that was the site. I use Debian and checked. There is no dmg file on my side. What was the file hoster that i used again? To avoid it in the future.


[ThreeJSExportBug.blend.gz](https://github.com/mrdoob/three.js/files/1761672/ThreeJSExportBug.blend.gz)

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
