### ISSUE TITLE
Removing Injected Shader Items

### ISSUE THREAD

**Issue by Diniden** [mrdoob/three.js#13318]
I was just wondering:

Is there any way to NOT include the injected shader items at the top of my vertex shaders?

I literally only use ShaderMaterial, BufferGeometry, Scene, and the Webgl Renderer. 

I have no need for the fanciness, but I like the basics provided. If I could remove the header which adds a bunch of useless functionality to my shader (and masks/utilizes names I'd rather use in other ways) it'd make my life a lot simpler.

I have googled and searched for awhile for an answer to this but could not find anything.

**Comment by mrdoob** [comment]
I think `RawShaderMaterial` is what you're after.

**Comment by Diniden** [comment]
Iz what I needed! No idea why I couldn't find that before! Thanks :) 🎉
