### ISSUE TITLE
Depth material example inverted

### ISSUE THREAD

**Issue by mkeblx** [mrdoob/three.js#13329]
##### White to black or black to white

Depth material example states 'White is nearest, black is farthest'. But example rendering shows the opposite. Need to make consistent. Decision of whether to change text, or material.
https://threejs.org/docs/#api/materials/MeshDepthMaterial

##### Three.js version

- [ x] Dev
- [ x] r90

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I would say the docs are wrong.

It should be: `Black is nearest, White is farthest.`

**Comment by WestLangley** [comment]
`MeshDepthMaterial` was previously "white nearest", but was inverted in #8573. See [this comment](https://github.com/mrdoob/three.js/pull/8573#issuecomment-207771253).

In fact, in `UnpackDepthRGBAShader`, white is nearest:

    "float depth = 1.0 - unpackRGBAToDepth( texture2D( tDiffuse, vUv ) );",

Also, if the background is black when rendering a depth map, then, to be consistent, far depths should also be black.

IMO, that is a compelling reason to revert.

So I would say the docs are fine, and `MeshDepthMaterial` should be reverted to "white nearest" for `BasicDepthPacking`.

/ping @bhouston

**Comment by bhouston** [comment]
What is the convention used by the native depth texture extension?  I believe that it uses near as 0.0, and far as 1.0 right -- because it is using Normalized Device Coordinates right?

The RGBA packed depth should probably use the same convention for consistency.  Thus far is White, and near is Black.

**Comment by bhouston** [comment]
If you are drawing to a native depth texture or a simulated RGBA packed depth texture, you have to clear to 1.0 or White: https://github.com/mrdoob/three.js/blob/dev/examples/js/postprocessing/SAOPass.js#L237

Just like if you are drawing to a normal buffer, you need to clear with (0.5, 0.5, 1.0), a normal vector pointing down z axis: https://github.com/mrdoob/three.js/blob/dev/examples/js/postprocessing/SAOPass.js#L244

**Comment by WestLangley** [comment]
It is true, in NDC, far is 1. But the colors for grayscale (visual) rendering can be anything we want.

In https://threejs.org/examples/webgl_materials_channels.html, there is no clearing to white, and the background and depth colors are inconsistent.

Also, `SAOPass` uses `UnpackDepthRGBAShader` which has white nearest.

**Comment by bhouston** [comment]
In this end, this is just a choice we have to make.  I prefer to be as least interesting as possible thus if there is already a coordinate system assumed for this parameter elsewhere, such as in NDC, I advocate we standardize on it, rather than having difference choices in different places.

But I do not care that much about this.

**Comment by WestLangley** [comment]
>if there is already a coordinate system assumed for this parameter elsewhere, such as in NDC, I advocate we standardize on it

We are not changing the coordinate system. We are just using different colors -- swapping black and white.

I agree that there is no "right answer" here, but I vote to revert to "white nearest" for the reasons I stated in my previous comments.

**Comment by mrdoob** [comment]
I think "white nearest" makes the most sense to me (visually).
