### ISSUE TITLE
ColladaLoader: Error while parsing/building skeleton

### ISSUE THREAD

**Issue by jadutter** [mrdoob/three.js#13335]
I asked stackoverflow, and the first comment suggested it may be a bug that I should report. 

I give a detailed report in my post here:

https://stackoverflow.com/questions/48796931/why-cant-colladaloader-js-from-three-js-load-my-file/48797863#48797863

And here's extra relevant info not mentioned on stackoverflow. 

Chrome requesting http://127.0.0.1:5000/raptor

Flask web server returns raptor.html that imports three.js and ColladaLoader.js and contains the script to import the raptor.dae. 
Substituting raptor.dae with the elf.dae from the demo works. 

Windows 10 
 
NVIDIA GeForce GTX 950

Files saved and server run on Samsung 128GB USB 3.0 Flash Drive Fit (MUF-128BB/AM) https://www.amazon.com/dp/B017DH3O5A/ref=cm_sw_r_cp_apa_m3pHAbXRXVACJ

Everything I've done is self taught, and this issue is just the one obstacle where I don't have the knowledge to solve it, let alone the minimum amount of knowledge to search for the answer. 
Any guidance I can get would be greatly appreciated.

**Comment by Mugen87** [comment]
File: https://drive.google.com/open?id=1h8po_76L3AgRMpIAF8sQtdTKLntHSAQG

I see multiple problems with this `dae` model. Investigating...

**Comment by Mugen87** [comment]
Your model should now load with the latest `dev` version of `ColladaLoader`. But there is still one problem in context of skeleton parsing. I'll provide more details as soon as i know what's going wrong.

**Comment by jadutter** [comment]
I've loaded the dev version of three.js and ColladaLoader.js
Elf.dae still loads, and Raptor still does not load. 

The raptor file is ripped from Ark Survival Evolved and I found it online. 
![image](https://user-images.githubusercontent.com/4691511/36285842-35eb25d8-127b-11e8-83ac-abe88ee2dc1c.png)

Let me know if there's anything I can do to help.

**Comment by Mugen87** [comment]
> Elf.dae still loads, and Raptor still does not load.

Um, i'm afraid you are doing something wrong. With latest `ColladaLoader` it looks fine on my Computer:

![image](https://user-images.githubusercontent.com/12612165/36309689-f1c298e0-1325-11e8-8ec2-84084589ecb4.png)

**Comment by Mugen87** [comment]
> Elf.dae still loads, and Raptor still does not load.

Yeah, you're right. I've added a change to my local `dae` file and that solved the problem :sweat_smile: 

The problem is that the file refers to the skeleton in an unusual way. It does not refer to the top most bone, but to the node of the visual scene. `ColladaLoader` can't process this setup at the moment. If you change to following markup from
```xml
<skeleton>#ID8</skeleton>
```
to
```xml
<skeleton>#ID9</skeleton>
```
it should actually work.
