### ISSUE TITLE
No support on Mozilla Firefox Quantum

### ISSUE THREAD

**Issue by yashLadha** [mrdoob/three.js#13349]
##### Description of the problem

The examples that are mentioned in the readme, are unable to run in quantum.

![image](https://user-images.githubusercontent.com/18033231/36337155-0840de20-13b6-11e8-925a-c5ba875d23f2.png)

##### Three.js version

- [ ] Dev
- [ ] r90
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Please, report this to mozilla instead. https://bugzilla.mozilla.org/
