### ISSUE TITLE
DS_Store pollution

### ISSUE THREAD

**Issue by Itee** [mrdoob/three.js#13345]
##### Description of the problem

All sources folder are polluting by .DS_Store from Mac. 
Are they really useful for other people ?

##### Three.js version

- [ ] Dev
- [x] r90
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Itee** [comment]
Apparently the .DS_Store entry is in the gulp file under dev branch ! But file are still present using `npm install three`

**Comment by Mugen87** [comment]
> in the gulp file

What file? Do you mean `.gitignore`?

> But file are still present using npm install three

Can you explain the problem in more detail, please?

**Comment by donmccurdy** [comment]
And, are you on a Mac, or have the files leaked into your machine? Macs create these files any time you rearrange files in Finder, but they are excluded by .gitignore anyway.

**Comment by mrdoob** [comment]
I do not see any .DS_Store file here...
https://github.com/mrdoob/three.js/tree/dev/src

**Comment by Itee** [comment]
Sorry yes i mean in `.gitignore`... Need to sleep 😪 

And the problems is not critical, but there is some DS_Store file in the r90 that shouldn't be here. 

I'm under Windows

When i clone the repo, everythings is ok, no DS_Store files.

But when i setup a new project and do `npm run install --save three` i got some .DS_Store file in the folder tree

Some of the path containing .DS_Store files:

- node_modules\three\src\cameras
- node_modules\three\src\core
- node_modules\three\src\extras

To see what i'm talking:

<p align="center"><a href="https://www.youtube.com/watch?v=e9WYqX6PbCw"><img src ="https://img.youtube.com/vi/e9WYqX6PbCw/0.jpg" /></a></p>

**Comment by mrdoob** [comment]
Weird, I don't see any `.DS_Store` on those paths...

https://github.com/mrdoob/three.js/tree/dev/src/cameras
https://github.com/mrdoob/three.js/tree/dev/src/core
https://github.com/mrdoob/three.js/tree/dev/src/extras

**Comment by donmccurdy** [comment]
Oh, heh I see it now... the files are in npm but not Git.

Example: https://unpkg.com/three@0.90.0/src/.DS_Store

From npm docs:

> Use a .npmignore file to keep stuff out of your package. If there's no .npmignore file, but there is a .gitignore file, then npm will ignore the stuff matched by the .gitignore file. 

We have both, and `.gitignore` excludes `.DS_Store` but `.npmignore` does not. Easy fix, just need to add it to `.npmignore.

**Comment by Itee** [comment]
I now they are not under src when cloning. But when using npm...

This is the... strange things that happen here. And this is only under r90. A never see that before

**Comment by Itee** [comment]
Aaaahhh !!! 

Thank for the solution @donmccurdy

**Comment by Itee** [comment]
Who make the change ?

**Comment by mrdoob** [comment]
@Itee feel free to do a PR 👍
