### ISSUE TITLE
ColladaLoader instance nodes imported with names like 'instance_0'

### ISSUE THREAD

**Issue by shelbyspeegle** [mrdoob/three.js#13365]
##### Description of the problem

After the replacement of `ColladaLoader` with `ColladaLoader2` (now named just `ColladaLoader`), it looks like the imported information has changed a little bit.

heres a (condensed) snippet of my dae.
```
<library_nodes>
  <node id="ID3" name="Element_entry-door-handle">
    <node id="ID47" name="instance_3">
      </matrix>
      <instance_node url="#ID48" />
    </node>
  </node>
  <node id="ID48" name="Anchor">
    </instance_geometry>
  </node>
</library_nodes>
```

the behavior that i used to see was that the imported dae object would look like this:
```
scene.children[0] = [
  {
    name: 'Element_entry-door-handle',
    children: [
      {
        name: 'Anchor'
      }
    ]
  }
]
```

now it is looking like this:
```
scene.children[0] = [
  {
    name: 'instance_0',
    children: [
      {
        name: 'instance_3'
      }
    ]
  }
]
```

is this the expected output? on one hand i see at as incorrect because of how `ColladaLoader` used to work, but on the other hand i see it as correct because it matches how the dae is represented.

i am able to achieve what i need by doing a search through `library.nodes` and marrying the 'instance' up with its original definition and getting _that_ name.

would you accept a PR if i ensure that instance nodes are coming through with their definitions name rather than `'instance_0'`, `'instance_1'` etc?

i'll work on putting together a jsfiddle and updating this issue once complete.

##### Three.js version

- [ ] Dev
- [ ] r90
- [x] r88

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> i'll work on putting together a jsfiddle and updating this issue once complete.

👍

**Comment by shelbyspeegle** [comment]
alright i am super close, i just need a way of referencing the previous version of `ColladaLoader.js` in the demo to show the old functionality.

i have logging in the console to show the part of the scene that has the `instance_0` name. here is the demo: http://jsfiddle.net/zhpv6pn6/7/.

you can find my dae at https://raw.githubusercontent.com/shelbyspeegle/threejs-13365/master/source-model.dae.

**Comment by Mugen87** [comment]
Can you please check what happens if you change the following [line of code](https://github.com/mrdoob/three.js/blob/707b44a18c30161efdd2023247af88a4bde8d302/examples/js/loaders/ColladaLoader.js#L3309) to:
```js
if ( object.name === '' ) object.name = ( type === 'JOINT' ) ? data.sid : data.name;
```
Does this change improve the names of your scene graph?

**Comment by shelbyspeegle** [comment]
yes! thanks for the line number too! passing all my tests now without special lookup against library nodes 👍

**Comment by Mugen87** [comment]
Do you wanna make a PR with the change? I think we can put this in `ColladaLoader`.

**Comment by shelbyspeegle** [comment]
sure!
