### ISSUE TITLE
SAO omit items

### ISSUE THREAD

**Issue by pawelstan** [mrdoob/three.js#13363]
Hey! 

Is there a way not to apply SAO on objects in scene? 

Saw this example:
http://alteredqualia.com/three/examples/webgl_postprocessing_ssao.html

I think the SAO skip is in this DepthPassPlugin. SAO skips the flares and the car.

https://github.com/virtual-world-framework/three.js/blob/1974df1db138a927352cff44a338366dbc18d31a/src/extras/renderers/plugins/DepthPassPlugin.js

This example is really old. But is there a way to have this effect using the latest SAO example?
Is the multiple Scenes the only way currently?

Cheers,
P.

**Comment by Mugen87** [comment]
This is not a help site. Please ask a question at the [forum](https://discourse.threejs.org/).
