### ISSUE TITLE
how to replace parent object's children object with some object.

### ISSUE THREAD

**Issue by CharellKing** [mrdoob/three.js#13361]
var parent = replacee_object.parent;
var position = new THREE.Vector3();
parent.updateMatrixWorld();
position = replacee_object.matrixWorld;

// remove replacee_object;
parent.remove(replacee_object);

// add replacer_object
parent.add(replacer_object);
replacer_object.setPosition(position);

**Comment by Mugen87** [comment]
This is not a help site. Please use the [forum](https://discourse.threejs.org/)  instead.

**Comment by CharellKing** [comment]
thank you
