### ISSUE TITLE
`fromDirectGeometry` method may have something wrong

### ISSUE THREAD

**Issue by WJsjtu** [mrdoob/three.js#13369]
##### `fromDirectGeometry` method in class `BufferGeometry` may have something wrong.

I've been reading the source code of three.js for learning. And to make it clear I transform some code into typescript [(here)](https://github.com/WJsjtu/three.ts) for a strong type outline of three.js .
When I was reading the source code of `fromDirectGeometry` method in class `BufferGeometry`, I thought there was something wrong with the code 
[here](https://github.com/mrdoob/three.js/blob/master/src/core/BufferGeometry.js#L524) . The `arrayMax` function from `utils.js` requires argument to be an array of number, so the  statement `var TypeArray = arrayMax( geometry.indices ) > 65535 ? Uint32Array : Uint16Array;` implies `indices` property of `DirectGeometry` is an array of number, however in statement `this.setIndex( new BufferAttribute( indices, 1 ).copyIndicesArray( geometry.indices ) )`, `copyIndicesArray` method in class `BufferAttribute` [(source)](https://github.com/mrdoob/three.js/blob/master/src/core/BufferAttribute.js#L132)  requires argument to be an Array of `Face3` instances. So I think there might be something wrong with the source code, since the `>` operator in JavaScript always returns false when arguments are two objects. 

##### Three.js version
- [x] Dev
- [x] r90

**Comment by Mugen87** [comment]
Cross posting: https://discourse.threejs.org/t/question-about-fromdirectgeometry-function-of-buffergeometry/1890

Closing this in favor of the post in the forum.

**Comment by WestLangley** [comment]
I think this issue should be reopened and the code should be fixed.

**Comment by Mugen87** [comment]
What do you suggest? Removing `BufferAttribute.copyIndicesArray()` and the respective section in `BufferGeometry.fromDirectGeometry()`?

**Comment by WestLangley** [comment]
I am not sure `DirectGeometry.indices` is ever used.

**Comment by Mugen87** [comment]
This is the only access I've found in the whole repos:
https://github.com/mrdoob/three.js/blob/4966686e9bce8b762f08deb317fc8ab6894aa48e/src/core/BufferGeometry.js#L524

**Comment by mrdoob** [comment]
Thanks guys!

**Comment by WJsjtu** [comment]
https://github.com/mrdoob/three.js/blob/4966686e9bce8b762f08deb317fc8ab6894aa48e/src/core/DirectGeometry.js#L25-L26
 Are these two properties ever used?
https://github.com/mrdoob/three.js/blob/4966686e9bce8b762f08deb317fc8ab6894aa48e/docs/api/core/DirectGeometry.html#L68-L77
The doc says they can be calculated, but no such functions are found for `DirectGeometry`.
https://github.com/mrdoob/three.js/blob/4966686e9bce8b762f08deb317fc8ab6894aa48e/docs/api/core/DirectGeometry.html#L99-L107
Here too.
https://github.com/mrdoob/three.js/blob/4966686e9bce8b762f08deb317fc8ab6894aa48e/docs/api/core/DirectGeometry.html#L97
And this is not true.
