### ISSUE TITLE
STLLoader out of memory exception( not enough memory to perform this operation)

### ISSUE THREAD

**Issue by AMOLCAD** [mrdoob/three.js#13371]
##### Description of the problem
I'm Facing issue in loading stl file using STLLoader in the three js. My stl geometry data is huge more than 2 gb. it throws exception as memory excpetion 

##### Three.js version
 
- [ ] r90 

##### Browser
 - [ ] Internet Explorer

##### OS
- [ ] Windows 

##### Hardware Requirements (graphics card, VR Device, ...)
NVIDIA graphics card, 
128 Gb RAM Machine

**Comment by Mugen87** [comment]
This is not a help site. Loading big files was already discussed multiple times at stackoverflow or the forum. Just one example:

https://discourse.threejs.org/t/loading-big-obj-file-about-300-mb-will-crash-te-browser-and-take-much-time-to-load/1401

**Comment by mrdoob** [comment]
@AMOLCAD Any way you can provide a example that crashes IE?
