### ISSUE TITLE
iOS: RGBADepthPacking doesn't work correctly

### ISSUE THREAD

**Issue by cnspaha** [mrdoob/three.js#13372]
##### Description of the problem

MeshDepthMaterial with THREE.RGBADepthPacking doesn't work correctly on iOS.

How to reproduce:

Simply open https://threejs.org/examples/?q=chann#webgl_materials_channels on a iOS device and set the material to "depthRGBA".
The issue with the depth packing can be also seen when opening the SAO example.

Works fine on Chrome (Mobile), Firefox, Internet Explorer, Microsoft Edge, Safari.
Doesn't work on Safari Mobile

What to expect (screenshot from android device): 
![screenshot_20180220-140601](https://user-images.githubusercontent.com/22448974/36426463-572aae3a-164a-11e8-889f-6925d99b59ed.png)

What I get:
![img_0003](https://user-images.githubusercontent.com/22448974/36426496-68f02ff0-164a-11e8-9382-b4ddfe08b809.PNG)

Seems to be a problem with the RGBADepthPacking packing. will investigate it a bit further.

##### Three.js version

- [x] Dev

##### Browser

- [x] iOS Safari Mobile

##### OS

- [x] iOS (11?)

##### Hardware Requirements (graphics card, VR Device, ...)
Device with iOS (iPhone), only tested iPhone X so far.

**Comment by Mugen87** [comment]
Seems like a duplicate: #9092

**Comment by cnspaha** [comment]
oh yeah you are right, haven't found this one
