### ISSUE TITLE
texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#13389]
ok, this is not really an issue (yet ?) more like a question, but I just started to have this message, and am not sure what to do about it:
![screen shot 2018-02-21 at 19 35 29](https://user-images.githubusercontent.com/242577/36498478-ade22c9a-173e-11e8-916d-99c4f284a527.png)

**Comment by Mugen87** [comment]
I guess your are on FF? Have a look at https://bugzilla.mozilla.org/show_bug.cgi?id=1400077

**Comment by Mugen87** [comment]
BTW: I would say the forum or stackoverflow is the more appropriate place for discussing stuff like that...

**Comment by makc** [comment]
> It's still functional, because that's what the spec requires, but we advise against using it.

so basically FF devs litter the console for no good reason. thanks!
