### ISSUE TITLE
FBXLoader.js is not loading the attached fbx & not showing any error!

### ISSUE THREAD

**Issue by nnavaneetha** [mrdoob/three.js#13382]
In Chrome below console log

THREE.WebGLRenderer 90
FBXLoader.js:2861 THREE.FBXLoader: FBX binary version: 7400
three.js:30626 XHR finished loading: GET "http://localhost/FBXViewer/examples/models/fbx/Test1.fbx".

##### Three.js version

- [ ] Dev
- [x] r90
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

[Test1.zip](https://github.com/mrdoob/three.js/files/1743210/Test1.zip)

**Comment by looeee** [comment]
Tested the file and it appears to be loading correctly. 

Make sure that you are using the latest FBXLoader and try adapting the code from  
https://threejs.org/examples/#webgl_loader_fbx as a starting point. 

If you need any more help, please ask over on the forum.

**Comment by nnavaneetha** [comment]
Used the same code & its not working...

Please find the attached screenshot & the sample files are working

**Comment by mrdoob** [comment]
#13385
