### ISSUE TITLE
Throw error when vectors aren't normailzed in Quaternion#setFromUnitVectors

### ISSUE THREAD

**Issue by birneamstiel** [mrdoob/three.js#13383]
##### Description of the problem
I was wondering if it would make sense to check that passed unit vectors really are normalized in `Quaternion`'s function `setFromUnitVectors`. 
https://github.com/mrdoob/three.js/blob/707b44a18c30161efdd2023247af88a4bde8d302/src/math/Quaternion.js#L350-L360
I accidentally called the function with not normalized vectors couple of times and found it quite annoying to search for the mistake (since the Quaternion will silently result in being set to the identity Quaternion).

I'm aware that it's my responsibility to make sure I meet the assumptions being made when calling the function, then again somewhere else in this class there's an explicit check: https://github.com/mrdoob/three.js/blob/707b44a18c30161efdd2023247af88a4bde8d302/src/math/Quaternion.js#L197-L203

**Comment by Mugen87** [comment]
Basically, we don't verify parameters for performance reasons. The mentioned section in `.setFromEuler()` was added because the semantics of the parameter `euler ` has changed.

**Comment by swt2public** [comment]
Alright, thanks for the clarification!

**Comment by birneamstiel** [comment]
Alright, thanks for the clarification!
