### ISSUE TITLE
FBXLoader.js is not loading the attached fbx & no error in console!

### ISSUE THREAD

**Issue by nnavaneetha** [mrdoob/three.js#13385]
[Busway 3DView-Preview.zip](https://github.com/mrdoob/three.js/files/1743816/Busway.3DView-Preview.zip)
Used the same code https://threejs.org/examples/#webgl_loader_fbx
& its not working!

Please find the attached screenshot & the sample files are working

Attached one more file too 
![issue](https://user-images.githubusercontent.com/19159334/36477424-21bcc93a-1727-11e8-87b0-3e010f87f64e.png)

##### Three.js version

- [ ] Dev
- [x] r90
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Your model loads correctly but it's hard to see with the white ground. Just remove the ground (`mesh`+`grid`) in the example and everything should be fine 😊 

![image](https://user-images.githubusercontent.com/12612165/36484454-a66c8b6a-1719-11e8-9a38-45de3d5b5dda.png)

Please use the [forum](https://discourse.threejs.org/) if you need more help.

**Comment by nnavaneetha** [comment]
Hi, 

Thanks...but I changed the bg color to black & still its not showing the content!
PFA
![issue](https://user-images.githubusercontent.com/19159334/36524588-7eb4dcc2-17cc-11e8-8253-e832203813bd.png)

Thanks,
Navan.

**Comment by mrdoob** [comment]
@nnavaneetha what's happening with the grid? what graphics card are you using?

**Comment by nnavaneetha** [comment]
graphics card  : Intel(R) HD Graphics 520 & same effect after turning of the grid

The default sample of fbx is working fine.

**Comment by mrdoob** [comment]
> The default sample of fbx is working fine.

I see, so it's a error in your code then. Lets move this to the [forum](https://discourse.threejs.org/).

**Comment by nnavaneetha** [comment]
@mrdoob ,
Im using the sample code from the below URL.
https://threejs.org/examples/#webgl_loader_fbx

**Comment by nnavaneetha** [comment]
[webgl_loader_fbx.zip](https://github.com/mrdoob/three.js/files/1755830/webgl_loader_fbx.zip)

**Comment by EmreKarslan** [comment]
https://github.com/mrdoob/three.js/blob/72ac6e0ca533571f233b612727e5c20a865fb735/examples/webgl_loader_fbx.html#L79 can u try change this lines 79 and 80 if ur fbx model not have animation your fbx loader looks broken but it's wrong in here check line 79,80
`var action = mixer.clipAction( object.animations[ 0 ] );
action.play();` to change with this lines `if(object.animations.lenght>0){
var action = mixer.clipAction( object.animations[ 0 ] );
action.play()
}`
