### ISSUE TITLE
JSONLoader still report console error '...use SceneLoader...'

### ISSUE THREAD

**Issue by jimtang** [mrdoob/three.js#13405]
##### Description of the problem

See JSONLoader line 61. 
but SceneLoader is deprecated.

##### Three.js version

- [ ] Dev
- [ ] r90
- [ ] ...

**Comment by Mugen87** [comment]
Good catch! I suggest to remove the following section:

https://github.com/mrdoob/three.js/blob/3ebd7499638c81dcb5d053105c9faacb0458bd4b/src/loaders/JSONLoader.js#L61-L66

**Comment by Mugen87** [comment]
@jimtang Do you wanna make a PR with the change? 😇
