### ISSUE TITLE
[Question] How could we integrate a NRRD file loader from ThreeJS library with React library?

### ISSUE THREAD

**Issue by YoneMoreno** [mrdoob/three.js#13403]
I am trying to integrate ThreeJS and React.

I have tried to load a NRRD file using ThreeJS loader and it works as expected, however it is on a single file. Here is the code if you would like to explore further: https://github.com/YoneMoreno/LoadNRRDInThreeJSExample

The use case is to integrate that example with React.

I have studied those links: https://stackoverflow.com/questions/38836553/how-to-use-jquery-ui-with-react-js/40350880#40350880

https://stackoverflow.com/questions/41248287/how-to-connect-threejs-to-react

And I have tried the following code:

` import React from 'react';
import * as THREE from 'three';

class LoadNRRD extends React.Component {
    componentDidMount() {
        let camera = new THREE.PerspectiveCamera(60, window.innerWidth / window.innerHeight, 0.01, 1e10);
        camera.position.z = 300;

        let scene = new THREE.Scene();

        scene.add(camera);

        var loader = new THREE.NRRDLoader();
        loader.load("models/columnasegmentado01.nrrd", function (volume) {
            var sliceZ;

            //z plane

            var indexZ = 0;
            sliceZ = volume.extractSlice('z', Math.floor(volume.RASDimensions[2] / 4));
            scene.add(sliceZ.mesh);

        });

        // renderer

        renderer = new THREE.WebGLRenderer({antialias: false, alpha: true});
        renderer.setPixelRatio(window.devicePixelRatio);
        renderer.setSize(window.innerWidth, window.innerHeight);

        let container = document.createElement('div');
        document.body.appendChild(container);
        container.appendChild(renderer.domElement);

        let controls = new THREE.TrackballControls(camera, renderer.domElement);
        controls.rotateSpeed = 0;
        controls.zoomSpeed = 5;
        controls.panSpeed = 2;
        controls.noZoom = false;
        controls.noPan = false;
        controls.staticMoving = true;
        controls.dynamicDampingFactor = 0.3;

        let stats = new Stats();
        container.appendChild(stats.dom);

        window.addEventListener('resize', onWindowResize, false);

        function onWindowResize() {

            camera.aspect = window.innerWidth / window.innerHeight;
            camera.updateProjectionMatrix();

            renderer.setSize(window.innerWidth, window.innerHeight);

            controls.handleResize();

        }

        function animate() {

            requestAnimationFrame(animate);

            controls.update();

            renderer.render(scene, camera);

            stats.update();

        }

    }

    render() {
        return (
            <div
                style={{width: '400px', height: '400px'}}
            />
        )
    };

}

export default LoadNRRD;`

And I tried to download all Threejs modules involved by hand and link them on index.html:

`<!doctype html>

<html lang="es">
<head>
    <script src="https://cdn.rawgit.com/seikichi/tiff.js/master/tiff.min.js"></script>
    <meta charset="utf-8">
    <title>Atlas</title>
    <meta name="description" content="Atlas">
    <meta name="author" content="">
</head>

<body>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<script src="js/controls/TrackballControls.js"></script>

<script src="js/Volume.js"></script>
<script src="js/VolumeSlice.js"></script>
<script src="js/loaders/NRRDLoader.js"></script>

<script src="js/Detector.js"></script>
<script src="js/libs/stats.min.js"></script>
<script src="js/libs/gunzip.min.js"></script>

<div id="mainApp"></div>
</body>
</html>`

Well, as result we get the following:

`Failed to compile
./src/components/animals/LoadNRRD.js
  Line 29:  'renderer' is not defined  no-undef
  Line 30:  'renderer' is not defined  no-undef
  Line 31:  'renderer' is not defined  no-undef
  Line 35:  'renderer' is not defined  no-undef
  Line 37:  'renderer' is not defined  no-undef
  Line 46:  'Stats' is not defined     no-undef
  Line 57:  'renderer' is not defined  no-undef
  Line 70:  'renderer' is not defined  no-undef

Search for the keywords to learn more about each error.`

As a result I decided then to download and install Threejs from npm module, following its repository instructions:

https://threejs.org/docs/#manual/introduction/Import-via-modules

I verified the installation:

![imagen](https://user-images.githubusercontent.com/22214901/36541724-b3e8eb72-17d6-11e8-8b12-0f649dbe9785.png)

I wonder if renderer is undefined means that we are not linking the renderer created with a div which contains it as in the example 

https://stackoverflow.com/questions/41248287/how-to-connect-threejs-to-react

Uses:

`render() {
    return (
      <div
        style={{ width: '400px', height: '400px' }}
        ref={(mount) => { this.mount = mount }}
      />
    )
  }`

And mine is just:

`render() {
    return (
        <div
            style={{width: '400px', height: '400px'}}
        />
    )
};`

I also wonder about the following sentences in the code I am trying to integrate:

`renderer = new THREE.WebGLRenderer({antialias: false, alpha: true});
        renderer.setPixelRatio(window.devicePixelRatio);
        renderer.setSize(window.innerWidth, window.innerHeight);`

How could we insert the ThreeJS canvas being generated when calling WebGLRenderer into an existing div? to display it on the web

In addition I really wonder why the IDE keeps showing Unresolved type... for ThreeJS functions. It knows about Three itself but not about its functions. As example in WebStorm:

![imagen](https://user-images.githubusercontent.com/22214901/36541780-ede6c68c-17d6-11e8-839e-c524af1d7f30.png)

Thank you for your help! 😯

Resposted from SO https://stackoverflow.com/questions/48928751/react-how-could-we-integrate-a-nrrd-file-loader-from-threejs-library-with-react

**Comment by WestLangley** [comment]
This is not a help site. Please do not cross-post help question here.
