### ISSUE TITLE
FBXLoader.js  not working for attached files but working for sample fbx file!

### ISSUE THREAD

**Issue by nnavaneetha** [mrdoob/three.js#13411]
[Busway 3DView-Preview.zip](https://github.com/mrdoob/three.js/files/1743816/Busway.3DView-Preview.zip)
Used the same code https://threejs.org/examples/#webgl_loader_fbx
& its not working!

Please find the attached screenshot & the sample files are working

Attached fbx file and the source file too.

Code:

Im using the sample code from the below URL.
https://threejs.org/examples/#webgl_loader_fbx

But the provided sample fbx files are working fine!

PFA
![issue](https://user-images.githubusercontent.com/19159334/36524588-7eb4dcc2-17cc-11e8-8253-e832203813bd.png)

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/s3rjfcc3/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/ptgwhemb/) (dev branch)
* [codepen](https://codepen.io/anon/pen/aEBKxR) (latest release branch)
* [codepen](https://codepen.io/anon/pen/BJWzaN) (dev branch)

##### Three.js version

- [ ] Dev
- [x] r90
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Looks fine to me.

![screen shot 2018-02-23 at 12 24 18 am](https://user-images.githubusercontent.com/1000017/36579247-134a313a-1830-11e8-81e0-81027f376817.png)

**Comment by looeee** [comment]
@nnavaneetha your files are ok, the problem is with your code. If you need more help, ask on the [forum](http://discourse.threejs.org).

**Comment by mrdoob** [comment]
#13385

**Comment by nnavaneetha** [comment]
@looeee, Im using the sample code from the below URL.
https://threejs.org/examples/#webgl_loader_fbx
