### ISSUE TITLE
TypeScript: module augmentation, add methods and properties to Object3D

### ISSUE THREAD

**Issue by endel** [mrdoob/three.js#13425]
Hello there,

I'm having troubles augmenting definitions for the `"three"` module.

I'd like to add methods and attributes on `THREE.Object3D`. I've tried many variations of the following example, but none of them seem to work:

**augment.d.ts:**

```typescript
/// <reference types="three" />

declare namespace THREE {
    export interface Object3D {
        addBehaviour (klass: any): any;
        getEntity (): any;
    }
}
```

**Usage:**

![screen shot 2018-02-24 at 19 20 53](https://user-images.githubusercontent.com/130494/36635655-e34e50f6-1997-11e8-9492-9471e0301734.png)

Anyone has experience augmenting THREE definitions on TypeScript?
Cheers!

**Comment by sidroopdaska** [comment]
Did you figure this out?

**Comment by endel** [comment]
@sidroopdaska I've found some TypeScript open issues about this. Unfortunately, it's not possible to do this currently because of the way the type definitions are written for three.js.

More info:
- https://github.com/Microsoft/TypeScript/issues/18877
- https://github.com/Microsoft/TypeScript/issues/9532
