### ISSUE TITLE
Cannot pass THREE.Color or THREE.Vector3  to uniform struct variable

### ISSUE THREAD

**Issue by douduck08** [mrdoob/three.js#13434]
##### Description of the problem
I tried to pass THREE.Color or THREE.Vector3 to custom shader with uniform struct variable, but I got  error at `setValue3fv` in three.js.

I had followed the description in [issues 10759](https://github.com/mrdoob/three.js/issues/10759). Did I make mistake?

Part of shader code, about struct defination:
```c
struct Material {
    vec3 color;
    vec3 diffuse;
    vec3 specular;
};
uniform Material material;
```
My part of script about uniform:
```javascript
var uniforms = {
    material: {
        value: {
            color: new THREE.Color(1, 1, 1),
            diffuse: new THREE.Color(0.8, 0.8, 0.8),
            specular: new THREE.Color(1, 1, 1),
        }
    }
}
```

Btw, the uniform array of struct is working fine. only has trouble on single struct.

##### Three.js version

- [ ] Dev
- [x] r90
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
see https://jsfiddle.net/f2Lommf5/1916/

Please use the [forum](https://discourse.threejs.org/) if you need more help.
