### ISSUE TITLE
OBJLoader: Smoothing groups and BufferGeometry groups

### ISSUE THREAD

**Issue by jeum** [mrdoob/three.js#13443]
This is about the way you manage smoothing groups in OBJLoader [(your remark about it)](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/OBJLoader.js#L583-L602) and more generally about BufferGeometry Groups rendering.

> @todo Handle files that have varying smooth values for a set of faces inside one geometry but does not define a usemtl for each face set

IMO :
1- This case is a 'standart' case and g/s/usemtl should generate bufferGeometry groups (BTW can we add a name to a group ?)
2- Actually this parameter set the material.flatShading (true/false), but it does not do the job

In 3DSMax the smoothing group integer is a kind of faces group index which indicates that the faces are not 'merged' with neighbour faces with a different index.
An example here (look at the bottom teapot) :
![Image](http://wiki.polycount.com/w/images/f/fc/Smoothing_groups.jpg)

I don't know how that could be reproduced ... but, if I come back to bufferGeometry Groups, I think that the result could be approached if the limit between group stays visible even if material.flatShading = false, ie **by displaying the edges between non-coplanar faces of a different group**.

For example this cube contains groups referencing the same material :
```
groups: […]
0: Object { start: 0, count: 6, materialIndex: 0 }
1: Object { start: 6, count: 6, materialIndex: 0 }
2: Object { start: 12, count: 6, materialIndex: 0 }
3: Object { start: 18, count: 6, materialIndex: 0 }
4: Object { start: 24, count: 6, materialIndex: 0 }
5: Object { start: 30, count: 6, materialIndex: 0 }
```
![image](https://user-images.githubusercontent.com/4399390/36672709-982e4738-1b00-11e8-8a05-668a45b58163.png)
For me it reproduces the `Cube with group names` example of [obj specs](http://paulbourke.net/dataformats/obj/) (middle of page) :
```
    v 0.000000 2.000000 2.000000
    ...
    # 8 vertices

    g front cube
    f 1 2 3 4
    g back cube
    f 8 7 6 5
    g right cube
    f 4 3 7 8
    g top cube
    f 5 1 4 8
    g left cube
    f 5 6 2 1
    g bottom cube
    f 2 6 7 3
    # 6 elements
```
But I expected the render below (which is `flatShading = true`) ..
OR
The following obj should be rendered as `flatShading = true` material even if it's `false` ?
```
    v 0.000000 2.000000 2.000000
    ...
    # 8 vertices

    s 1
    f 1 2 3 4
    s 2
    f 8 7 6 5
    s 3
    f 4 3 7 8
    s 4
    f 5 1 4 8
    s 5
    f 5 6 2 1
    s 6
    f 2 6 7 3
    # 6 elements
```
![image](https://user-images.githubusercontent.com/4399390/36673287-8efc110c-1b02-11e8-941e-804ff7dbb801.png)

This way we could manage smoothed portions of the mesh and 'flat' limit between faces groups ?

**Comment by jeum** [comment]
My previous .obj sample register faces as quads, but if I look at a simple cube exported by 3DS as tris, 's' groups serve to delimit faces :

```
# 3ds Max Wavefront OBJ Exporter v0.97b - (c)2007 guruware
# File Created: 03.11.2014 18:30:47

mtllib cube.mtl

#
# object Box001
#

v  10.6458 -30.9381 -11.4229
v  30.5467 8.9477 -34.0742
v  37.0458 30.9381 10.3576
v  17.1449 -8.9477 33.0089
v  -34.7603 -10.3092 -14.9910
v  -28.2612 11.6812 29.4408
v  -8.3604 51.5669 6.7895
v  -14.8595 29.5765 -37.6423
# 8 vertices

vn 0.9081 -0.4126 0.0714
vn -0.9081 0.4126 -0.0714
vn -0.3980 -0.7977 0.4530
vn 0.1300 0.4398 0.8886
vn 0.3980 0.7977 -0.4530
vn -0.1300 -0.4398 -0.8886
# 6 vertex normals

vt 50.0000 0.0000 0.0000
vt 50.0000 50.0000 0.0000
vt 0.0000 50.0000 0.0000
vt 0.0000 0.0000 0.0000
# 4 texture coords

g Box001
usemtl wire_198225087
s 2
f 1/1/1 2/2/1 3/3/1 
f 3/3/1 4/4/1 1/1/1 
s 4
f 5/4/2 6/1/2 7/2/2 
f 7/2/2 8/3/2 5/4/2 
s 8
f 1/4/3 4/1/3 6/2/3 
f 6/2/3 5/3/3 1/4/3 
s 16
f 4/4/4 3/1/4 7/2/4 
f 7/2/4 6/3/4 4/4/4 
s 32
f 3/4/5 2/1/5 8/2/5 
f 8/2/5 7/3/5 3/4/5 
s 64
f 2/4/6 1/1/6 5/2/6 
f 5/2/6 8/3/6 2/4/6 
# 12 faces
```

**Comment by mrdoob** [comment]
Have you considered using glTF insread?

There is an exporter for 3DS Max: http://doc.babylonjs.com/resources/3dsmax_to_gltf
Then you can load with GLTFLoader: https://threejs.org/examples/#webgl_loader_gltf

**Comment by WestLangley** [comment]
> File Created: 03.11.2014 18:30:47

Normals look fine to me...

![screen shot 2018-02-27 at 12 09 59 am](https://user-images.githubusercontent.com/1000017/36711701-c6937baa-1b52-11e8-8594-90ec8ce6c203.png)

`BufferGeomety` groups are not smoothing groups -- they are material groups.

To support smoothing groups with `BufferGeometry`, we would have to identify and duplicate all vertices on the boundaries of smoothing groups ( i.e., where a shared vertex has more than one normal ).

**Comment by jeum** [comment]
`i.e., where a shared vertex has more than one normal`
Ok, my reasoning is chained to the fact that vertices have only 1 normal .. so indeed we would have to duplicate vertices (or create 1 mesh per sg..)

`Have you considered using glTF instead?`
No I will try this one, thanks.


Sorry for this mistake, however I just point the fact that the 's' index driving material shading (wich is an important parameter) once converted to true/false is surprising. I also wonder how it is managed by objmtl (since it's not by the 'illum' .mtl statement) and I suppose it should just depend on vn (wich are faces normals and not vertices .... ).

So, since it is an important parameter, I prefer to provide a reference material (wich is flat or not) to the parser and replace the properties given by the .mtl file... (simple remark)
