### ISSUE TITLE
FBX Loader DataView is not a constructor

### ISSUE THREAD

**Issue by Ashutosh421** [mrdoob/three.js#13450]
##### FBXLoader unable to load FBX model in my client's machine

The FBXLoader works perfectly on my machine. What's strange is when my client is trying to integerate my JS bundle in his Java Maven code, everything stucks after the FBXLoader is unable to load files.
After the loader load function is called the FBXLoader throws an error.
DataView is not a constructor.
I have no clue what is the reason. I tried to search the reason online couldn't find anything. The code runs perfectly fine when we are running it through my applications.

Here's the Code Snippet
```js
loadingModel = "../fbx/Window.fbx";
  loader.load(loadingModel, function (object) {
        lastLoadedObject = object;
        object.traverse(function (child) {
            if (child.isMesh) {
                child.receiveShadow = true;
                if(child.name.includes("Glass")){
                    child.material = glassMaterial;
                }
                if(child.name.includes("BottomRail") || child.name.includes("TopRail")){
                    child.material = rails_material;
                }
                if(child.name == "Wall"){
                    child.material = wallMaterial;
                }
                if(child.name.includes("Handle")){
                    child.material = rails_material;
                }
            }
        });
    
        //if(!loadingModel.includes())
        object.name = doorName;
        loadingScene.addNewModel(object);
        $("#loading").hide();
    },
    function (xhr) {
        console.log((xhr.loaded / xhr.total * 100) + '% loaded');
        $("#loading").show();
        if(xhr.loaded == xhr.total){
            doorOptions.reset();
        }
    },
    // onError callback
    function (err) {
        console.log('An error happened ' + err);
    });
```
##### Three.js version

- [ ] Dev
- [x] r90
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
On which browser is the application executed? I guess the problem is not related to `FBXLoader` but to the missing support of `DataView` in the runtime environment.

**Comment by Ashutosh421** [comment]
Basically they are using Java as backend and SmartGWT to create html at runtime.
What is exactly DataView? If there is no support for DataView what is the possible alternative ? Do I have to use some other loader?

**Comment by looeee** [comment]
[Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView) is some info on dataviews. 

The FBXLoader uses a DataView for reading Binary FBX files. You could get around this by exporting your FBX in ASCII format. You'll have much larger file sizes, however you could always try compressing these yourself for some savings.

Alternatively you could try a DataView polyfill such as [this one](https://gist.github.com/mika76/20b86c76afb77c35e0b4) (no idea if it works, that was just the first result I found on Google).

**Comment by Ashutosh421** [comment]
Thanks..
     This is the first alternative I have already sent to the client.
Waiting for his reply..  Alternatively I'll try it in ASCII format..  once
I get a confirmation from the client.  Thanks for the quick help. Will
update you guys once I get this fixed.



Thanks and Regards,
Ashutosh

**Comment by looeee** [comment]
No problem. If you need more help, please ask on the [forum](https://discourse.threejs.org/).
