### ISSUE TITLE
Blender export wrong rotation

### ISSUE THREAD

**Issue by giangm9** [mrdoob/three.js#13458]
##### Description of the problem
I export a scene by this python function from io_three
```
exporter.export_scene(file_name, settings.no_animation)
```
Link to the blender scene [Link](https://github.com/giangm9/blender3js/blob/dev/exporter/tests/blend/rotation.blend)
In blender scene looks like this
![screenshot from 2018-02-28 18-06-38](https://user-images.githubusercontent.com/10234339/36784518-403dece6-1cb2-11e8-8bd4-b605598e25f5.png)
when I load the scene and render, my output is 
![screenshot from 2018-02-28 18-08-26](https://user-images.githubusercontent.com/10234339/36784551-660937e6-1cb2-11e8-9a11-822eda6d10ce.png)
as you can see that, the position is right, but the Yrotation ( maybe) is wrong
Link to my project https://github.com/giangm9/blender3js
##### Three.js version

- [ ] Dev
- [ ] r90
- [x] r89

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS
Blender version
- [x] 2.76

**Comment by Mugen87** [comment]
Duplicate: #12806

**Comment by WestLangley** [comment]
@Mugen87 Are you certain this is a duplicate -- with identical causes?

**Comment by donmccurdy** [comment]
@giangm9 it looks like the link to your `.blend` file has broken?

**Comment by Mugen87** [comment]
We have multiple issues like this and i think the solution is described here. 

#13130

**Comment by giangm9** [comment]
@donmccurdy  I removed it when the issue is closed
