### ISSUE TITLE
an option not to update VideoTexture ?

### ISSUE THREAD

**Issue by p5aholic** [mrdoob/three.js#13457]
VideoTexture automatically update itself while it's video element is playing. It's so useful and mostly We don't need to change the feature. But, in my current work, I need to stop updating texture while video element is playing. Adding an option not to update VideoTexture is very useful in some occasion like below.

```
VideoTexture.prototype = Object.assign( Object.create( Texture.prototype ), {

	constructor: VideoTexture,

	isVideoTexture: true,

	update: function () {

		var video = this.image;

		if ( video.readyState >= video.HAVE_CURRENT_DATA && this.autoUpdate) { // adding an option not to update texture

			this.needsUpdate = true;

		}

	}

} );
```

In this example code, setting autoUpdate to false will stop automatic texture updating.

thanks.

**Comment by Mugen87** [comment]
If we would introduce an `autoUpdate` property, we should not evaluate it at this point but here:
https://github.com/mrdoob/three.js/blob/23be4d6b8484e2912c3ac760720d1ccc6af2f693/src/renderers/webgl/WebGLTextures.js#L205
The new code could look like this:
```js
if ( texture.isVideoTexture && texture.autoUpdate ) updateVideoTexture( texture ); 
```
If `autoUpdate` is set to `false`, the user has to call `videoTexture.update()` instead.

**Comment by dustinkerstein** [comment]
For this use-case, maybe try not using a VideoTexture `texture = new THREE.Texture(video);` and then manually calling `texture.needsUpdate = true` in your render loop. That's how I do it. Though this causes some major issues with desktop Safari (flashing black) and I end up using VideoTexture on Safari as a workaround.

**Comment by p5aholic** [comment]
@Mugen87 Thanks!

**Comment by mrdoob** [comment]
> For this use-case, maybe try not using a VideoTexture `texture = new THREE.Texture(video);` and then manually calling `texture.needsUpdate = true` in your render loop. 

👍

> Though this causes some major issues with desktop Safari (flashing black) and I end up using VideoTexture on Safari as a workaround.

Hmm... Any ideas why?

**Comment by dustinkerstein** [comment]
No, not really. I noticed it a few weeks ago and quickly put in a workaround for my app. I don't believe it was always like this. It's possible a recent Safari update changed the behavior, but I figured using the manual texture approach wasn't 100% supported so it might not work everywhere. I'd be happy to add a bug for investigation though. Should I do that?

**Comment by mrdoob** [comment]
@dustinkerstein for the time being I've done #13470 so we can test this a bit more.
