### ISSUE TITLE
Updating color of vertex influenced others vertices

### ISSUE THREAD

**Issue by jason1105** [mrdoob/three.js#13455]
Defined a color varible, and assigned it to face.vertexColors, when update color in animation, others vertices of face was changed. 

Cause:
If use baseColor.clone() to assigned color to vertexColors, that work well.  So I think a reference varible caused this problem.

----------
Code snipped:
```
// Initialize all vertices with green
let baseColor = new THREE.Color(0x00ff00);
for (let i = 0; i < this.geometry.faces.length; i++) {
  let face = this.geometry.faces[i];
  this.geometry.faces[i].vertexColors = [baseColor, baseColor, baseColor];
}

...

// Dynamic update in rendering, for example just update one vertex with red
this.geometry.faces[1].vertexColors[0].setRGB(255, 0, 0);
this.geometry.colorsNeedUpdate = true;
this.scene.render();
```

Screen hardcopy:
Expect：[Image](https://ibb.co/iurs0x)
Actual：[Image](https://ibb.co/kCakLx)

##### Three.js version

- [ ] Dev
- [ ] r90
- [x] r89

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
It's hard to say what your issue is since you haven't provided a complete code example, but try setting `material.vertexColors = THREE.VertexColors`. 

If you need more help please ask over on the [forum](https://discourse.threejs.org/).
