### ISSUE TITLE
Octree return face or vertex index

### ISSUE THREAD

**Issue by kpetrow** [mrdoob/three.js#13460]
It would be helpful to have Octree.search return the index of the face or vertex in the result set.

The current results do not have a reference to their original position in the faces or vertices array.

Maybe this is already implemented and I cant figure out where.  work i have done #13459

**Comment by EdoardoSchnell** [comment]
+1, this would be awesome

**Comment by Mugen87** [comment]
`THREE.Octree` has been removed from the repo: #15451

Please report feature request and bugs at the original repo: https://github.com/collinhover/threeoctree
