### ISSUE TITLE
Cannot set property 'lightsHash' of undefined within GearVR and webvr example

### ISSUE THREAD

**Issue by danrossi** [mrdoob/three.js#13461]
This might affect others but with the latest branch. But when launching presentation with GearVR and the gear controller example I receive this error

```
VM270 three.js:18494 Uncaught TypeError: Cannot set property 'lightsHash' of undefined
```

And therefore rendering breaks. I have experienced this same problem launching in Gear in other examples. and require to put a catch around the render

```
try {
	renderer.render( scene, camera )
} catch(e) {}
}
```

**Comment by mrdoob** [comment]
I've just tried https://rawgit.com/mrdoob/three.js/dev/examples/webvr_gearvr.html on Galaxy S8/GearVr and the Oculus browser and it displays correctly.

(Minus the standingMatrix issue introduced in #13158 that is.)

**Comment by danrossi** [comment]
It was happening but after an update it isn't. A temporary issue possibly.
