### ISSUE TITLE
SVGLoader

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#13478]
Currently, [SVGLoader](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/SVGLoader.js) only returns the nodes.

I hink it'll be a great improvement if the loader could convert svg nodes to `THREE.Shape` which could then be used by `THREE.ShapeGeometry` or `THREE.ExtrudeGeometry`. With that in place, adding `svg` support to the [editor](https://threejs.org/editor/) would make a few designers happy.

We happen to have some basic code already in [webgl_geometry_extrude_shapes2](https://rawgit.com/mrdoob/three.js/dev/examples/webgl_geometry_extrude_shapes2.html):

https://github.com/mrdoob/three.js/blob/dev/examples/webgl_geometry_extrude_shapes2.html#L49-L389

Also, for reference, @jonobr1 has been tackling this same issue for `two.js` for a while now:

https://github.com/jonobr1/two.js/blob/dev/src/two.js#L798-L1475

**Comment by jonobr1** [comment]
I'd be happy to translate the Two.js logic over.

**Comment by mrdoob** [comment]
@jonobr1 😍

**Comment by jonobr1** [comment]
Ricardo kicking it off! https://github.com/mrdoob/three.js/pull/13616

**Comment by paulbrzeski** [comment]
I'm getting some very strange results when trying to use this.. Even a really simple SVG example from W3C,
`<svg height="210" width="400">
  <path d="M150 0 L75 200 L225 200 Z" />
</svg>`
results in the following:
![capture](https://user-images.githubusercontent.com/951100/37564410-7e9d06d0-2ad0-11e8-8f2f-0b935f8c897a.PNG)

**Comment by paulbrzeski** [comment]
@mrdoob I know this is still a WIP but I got some strange results trying to use the SVGLoader even though it works fine with the example tiger.svg.

Using the d3-threeD implementation from webgl_geometry_extrude_shapes2's example worked fine though.

**Comment by mrdoob** [comment]
Please, share the files that are giving you strange results.

**Comment by paulbrzeski** [comment]
Github wouldn't let me post the file so here it is in a public repo - https://github.com/paulbrzeski/manifold/blob/master/potrace.svg

**Comment by mrdoob** [comment]
@paulbrzeski After d82442aedc15d726b2bbf280ce93a98c093a8ebe, your files are starting to appear 😁

**Comment by paulbrzeski** [comment]
Not sure where SVGLoader is at with the styles but I noticed the current copy of SVG on the **dev** branch [wasn't parsing the style information](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/SVGLoader.js#L513) so I made some changes.

https://github.com/paulbrzeski/manifold/pull/3/files#diff-951105ef94046da2301be208fa86ff54R513

**Comment by mrdoob** [comment]
@paulbrzeski Would you like to do a PR with that improvement?

**Comment by paulbrzeski** [comment]
Sure :)

**Comment by iambumblehead** [comment]
Following the example [here,][0] some shapes come out okay and some do not. [This svg from google material design][1] isn't formed correctly at the end.

[0]: https://threejs.org/examples/#webgl_loader_svg
[1]: https://github.com/google/material-design-icons/blob/master/image/svg/design/ic_adjust_24px.svg

**Comment by jonobr1** [comment]
I can take a look at this. I recently fixed an issue with Two.js SVG parsing that might be realted to this.

**Comment by jonobr1** [comment]
PR for partial fix for @iambumblehead's referenced SVGs here: https://github.com/mrdoob/three.js/pull/14276

I need some help from someone that knows the `THREE.ShapePath` and `THREE.Path` to vet how I'm accessing the initial x, y coordinate vector of a path.

**Comment by yomboprime** [comment]
Hello, I've implemented the `transform` node attribute (only `translate` and `matrix`, which are the ones Inkscape produces)

Would you like a PR with this?

**Comment by mrdoob** [comment]
@yomboprime yes please! 😊

**Comment by yomboprime** [comment]
I've implemented now the `rotate` and the `scale` also. There's only left the `skew`.

My implementation only supports orthonormal matrices for circles, ellipses and arcs. That's why I've not implemented `skew`. The rest of curves work OK with any matrix.

Let me 1 more day to prepare the PR... 😉

**Comment by napter** [comment]
@yomboprime it looks like this only uses the first transform:
`var transformType = transformAttr.substr( 0, openParPos );`
However, my SVG has two transforms, a translate and scale but only the transform is being applied:
`<g transform="translate(0.000000,558.466321) scale(0.022383,-0.022383)"
fill="#000000" stroke="none">`

I hope I understood that right. Is that something that can be fixed?
Thanks

**Comment by napter** [comment]
@mrdoob here it is. I tested removing the translate and then the scale works but with both there it is only executing the translate so it is just doing the first transform. 

[c2fab75fbb234c1abf41c7f2669e1fa0_outer.bmp.zip](https://github.com/mrdoob/three.js/files/2494486/c2fab75fbb234c1abf41c7f2669e1fa0_outer.bmp.zip)

**Comment by napter** [comment]
@mrdoob @yomboprime I think perhaps I should have commented that on issue [14418](https://github.com/mrdoob/three.js/pull/14418) instead. It is an issue with the implementation of transforms in SVG.

**Comment by napter** [comment]
I implemented [these changes](https://www.diffchecker.com/AGG0KLc4) that _seem_ to fix it. However, I am not familiar with the code and it is very naively  implemented. I pretty much just changed all the places that return "transform" to return "transforms", a list of transforms, and then loop over it. I am not sure what the currentTransform and whether my changes handled that ok.

**Comment by yomboprime** [comment]
I think it should be better to compose the two transforms (or N of them) into one, inside the GetNodeTransform function.

**Comment by HakuG** [comment]
SVGLoader doesn't seem to color Path nodes correctly. 

Here's a link to the whatsapp SVG file: https://www.flaticon.com/free-icon/whatsapp-logo_33447

And here's what trying to use it in the loader gets me:
![image](https://user-images.githubusercontent.com/5514073/49361147-4443cc80-f6a9-11e8-88dc-b70b2b989551.png)

It renders fine in Inkscape. This also only seems to be an issue with paths.

**Comment by yomboprime** [comment]
> SVGLoader doesn't seem to color Path nodes correctly.

I've checked that this happens with versions previous to my modifications of transforms (8fcef653cff8394278437eda1494948c2947629b)

**Comment by Mugen87** [comment]
Closing. It's best to create a new issue if the latest `SVGLoader` is not able to correctly load a `SVG` file.

**Comment by yomboprime** [comment]
> @yomboprime I'm still having these issues, even using the most recent version of three.js and your version of transforms

Ops, I missed this comment, sorry.
