### ISSUE TITLE
Water2 Reflection is Reversed

### ISSUE THREAD

**Issue by msimpson** [mrdoob/three.js#13473]
@Mugen87 
https://github.com/mrdoob/three.js/blob/d55897b8e9b2632896d8ac146a05b3b4be3668f8/examples/js/objects/Water2.js#L324

Should be more like:
```
vec4 reflectColor = texture2D( tReflectionMap, vec2( 1.0 - uv.x, uv.y ) );
```

**Comment by Mugen87** [comment]
Good find! Would you like to do a PR with the fix`

**Comment by msimpson** [comment]
Sure. I'll throw one together.

**Comment by mrdoob** [comment]
Haha! This is like when the reflection in MeshStandardMaterial was flipped, like, for months 😁

**Comment by mrdoob** [comment]
Many thanks!

**Comment by WestLangley** [comment]
The colors of the reflection also do not appear to be correct.

There is really no reason to rotate the knot in the demo. Removing the rotation makes it easier to identify bugs.

**Comment by mrdoob** [comment]
> The colors of the reflection also do not appear to be correct.

I think they're correct but `MeshNormalMaterial` is making things confusing.

**Comment by Mugen87** [comment]
What material would be more appropriate for the torus? 

And yes, i'm fine with removing the rotation 😇
