### ISSUE TITLE
VideoTextures on Safari and seeking issue

### ISSUE THREAD

**Issue by dustinkerstein** [mrdoob/three.js#13482]
@mrdoob Since we're talking about all this video stuff, I have a somewhat related question / possible bug, though it likely only affects my particularly use case. In this [example](https://files.panomoments.com/js/videoiOS_seek.html) I try to set the currentTime to some frame before showing the texture. I don't ever want to show frame 0.  In the above example, it should immediately load to the frame that appears half cut-off. This works fine in Chrome and Firefox, but on iOS Safari it somehow forces me to render frame 0. Try tapping the screen and it will force a needsUpdate and then show the new frame, but no matter how long those setTimeouts are, it always will show frame 0 initially. On Desktop Safari, I see the same behavior, but it's compounded by the flashing black issue. Any ideas on why this happens, or how to avoid it?

Thanks,
Dustin

##### Three.js version
- [X] r90

##### Browser
- [x] Safari

##### OS
- [x] macOS
- [x] iOS

**Comment by mrdoob** [comment]
Sorry, but better to use the forum for questions like this.

**Comment by dustinkerstein** [comment]
Fair enough :) Just thought it could somehow be related to some of the existing Safari issues we were discussing (ie. the black frame flashing).

**Comment by mrdoob** [comment]
Right. We should report these to Apple though. It's dangerous!

**Comment by dustinkerstein** [comment]
FYI - I posted over on the Three.js Discourse - https://discourse.threejs.org/t/video-texture-updates-sometimes-showing-previous-frame/2247 - and also put together a simple color coded JSFiddle example that highlights this Safari issue - https://jsfiddle.net/rj7L0rsa/
