### ISSUE TITLE
Bender export / json loader mapNormalFactor bug

### ISSUE THREAD

**Issue by Troyhy** [mrdoob/three.js#13483]
When exporting from blender a mesh witch has an normal map applied to material resulting render is evenly black mesh.
Issue is fixed by patching material before mesh is made in loader callback:
``` javascript
function (geometry, materials) {
   ...
   materials[0].normalScale = new THREE.Vector2( 1, 1 );
   ...
```
But this has to be done individually to each material and scaling is not coming from material.
After digging I found that if you change 
``` javascript
case 'mapNormalFactor':
	json.normalScale = [ value, value ];
	break;
``` 
in here https://github.com/mrdoob/three.js/blob/dev/src/loaders/Loader.js#L256
to:
``` javascript
case 'mapNormalFactor':
	json.normalScale = value;
	break;
``` 
Problem is solved.

Sorry not providing batch, might also be that I have some setting wrong in my Blender model/material/export

##### Three.js version

- [x] Dev
- [ ] r90
- [ ] ...

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
Looks like a bug in `Loader.initMaterials()`.  `mapBumpScale` and `mapNormalFactor`  actually differ. They should be the same.

https://github.com/mrdoob/three.js/blob/4eb5068baf000e930d9c348a7d87c9a2e25d377d/src/loaders/Loader.js#L244-L246

**Comment by Mugen87** [comment]
Can you share your Blender and JSON file, please?

**Comment by Troyhy** [comment]
Here you go.

Json file: 
https://pastebin.com/d8F0HvjC

zip with blender file and normal map
http://www.filedropper.com/barrel

**Comment by Mugen87** [comment]
Yeah, you are right. `json.normalScale = [ value, value ]; ` is wrong since `value` is already an array with two entries. I've also checked the exporter code. Compared to `bumpScale` (which is a single float), `normalScale` is exported as an array of two values.

Would you like to to a PR with the fix?

**Comment by Troyhy** [comment]
> Would  you like to to a PR with your suggested fix?
Not sure what you mean, but I created a pull request for this fix.

**Comment by Mugen87** [comment]
Sry, typo. PR looks fine :+1:
