### ISSUE TITLE
mapAORepeat don't work 

### ISSUE THREAD

**Issue by trymoremore** [mrdoob/three.js#13498]
i use the BinaryLoader to add mesh in scene, i set the mapAORepeat in the js file,but it seems don't work

**Comment by Mugen87** [comment]
Can you please provide a little bit more context? Maybe your model and the respective code?

**Comment by trymoremore** [comment]
@Mugen87 
i set the gemoetry before use aomap like this:
geometry.faceVertexUvs[ 1 ] = geometry.faceVertexUvs[ 0 ];
it's some information about mapAO in my js file:
	"mapAO" : "NOCC205438_Ao.jpg",
	"mapAORepeat" : [1, 1],
and the result is that:
![result](https://user-images.githubusercontent.com/27277007/36969056-63708ffc-209f-11e8-9ecf-1933b5476fff.png)
and i change the js file like this :
	"mapAO" : "NOCC205438_Ao.jpg",
	"mapAORepeat" : [0.5, 0.5],
but the result is not change

**Comment by Mugen87** [comment]
Ah, i see now. That's a known limitation, see https://github.com/mrdoob/three.js/issues/9457#issuecomment-237308814

**Comment by Mugen87** [comment]
Closing since #9457 is still open as a valid feature request.

**Comment by trymoremore** [comment]
@Mugen87 thank you very much!
