### ISSUE TITLE
OrbitControls odd behavior

### ISSUE THREAD

**Issue by JERRYZFC** [mrdoob/three.js#13528]
https://threejs.org/examples/#misc_controls_orbit
THREE.WebGLRenderer 90

##### Browser
Chrome  version: 65.0.3325.146
can not behave normally

Firefox/Internet Explorer
console message：too much recursion

**Comment by Mugen87** [comment]
> can not behave normally

Can you please elaborate a bit? What kind of behavior do you experience?

> Firefox/Internet Explorer
console message：too much recursion

I'm unable to reproduce with FF 58.0.2.

**Comment by XanderLuciano** [comment]
>Firefox/Internet Explorer
>console message：too much recursion

Unable to reproduce as well. Tested in:

Microsoft Edge 41.16299.248.0 (poor performance)
IE 11.248.16299 (poor performance)
FF 58.0.2 (no issue)
Chrome 41, 64, and 67 (no issue)

**Comment by Mugen87** [comment]
@JERRYZFC We can reopen the issue if show the problem with a [live example](https://jsfiddle.net/Lbfno0gw/2/).
