### ISSUE TITLE
Suggestion: integrate with CI and require PRs to pass

### ISSUE THREAD

**Issue by dbkaplun** [mrdoob/three.js#13533]
Currently, it's difficult to contribute, when tests are already broken and lint does not pass. It would also make maintenance easier as everyone would have immediate feedback if the PR can be merged.

There have been discussions in the past, but they invariably end with "some code is not supposed to pass lint/tests". It would be nice to revisit this decision as three.js has no measures in place to tell a potential contributor if his code is remotely valid.

Thanks for considering!

**Comment by mrdoob** [comment]
@fernandojsg is looking into this over the next few months.
