### ISSUE TITLE
Sprite(Material) not clipped by clippingPlanes

### ISSUE THREAD

**Issue by wcoebergh** [mrdoob/three.js#13539]
##### Description of the problem

SpriteMaterials are not clipped (see screenshot below). Although [SpriteMaterial constructor docs](https://threejs.org/docs/#api/materials/SpriteMaterial) specifically state that all inherited [Material properties](https://threejs.org/docs/#api/materials/Material.clippingPlanes) can be set.

```
var textureLoader = new THREE.TextureLoader();
textureLoader.crossOrigin = "Anonymous";
textureLoader.load("https://cdn0.iconfinder.com/data/icons/small-n-flat/24/678111-map-marker-512.png", function(texture) {

	var mat = new THREE.SpriteMaterial({
		map: texture,
		clippingPlanes: [{clipPlane}]
	});

	var sprite = new THREE.Sprite(mat);

	sprite.position.set(-1, -1, 2);
	scene.add(sprite);
});
```

<img width="719" alt="screen shot 2018-03-08 at 22 55 12" src="https://user-images.githubusercontent.com/5583186/37178949-4f1eb2fe-2324-11e8-92e4-2eb710959b4a.png">

##### Three.js version

- [ ] Dev
- [ ] r90
- [x] r89

##### Browser

- [ ] All of them
- [x] Chrome (only one tested so far)
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS (only one tested so far)
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements

MB Pro 13 2017

**_PS: Thanks for the awesome work_**

**Comment by WestLangley** [comment]
Sprites currently do not support clipping.

**Comment by looeee** [comment]
@wcoebergh it seems like, until this is implemented, the docs are incorrect. Would you like to fix them?

**Comment by wcoebergh** [comment]
#13546
