### ISSUE TITLE
deprecation/ API change warning lifetimes

### ISSUE THREAD

**Issue by aardgoose** [mrdoob/three.js#13537]
Deprecated / changed APIs

Observing the ongoing API changes eg deprecating the optional nature of many method paramaters, is there a plan/policy on how long warnings are in place, before i. the API is changed ii. the warnings are removed given they are bloating the code. I'm discounting Three.Legacy.js because that is easily removed.

Looking through the source history, there are warnings and parameter count checks in Vector2,3,4 dating from early 2013 for changes to the .add() .sub() etc methods.

Can these be removed now?

**Comment by mrdoob** [comment]
I'm not sure...

Maybe the plan could be that when we start working on `WebGL2Renderer` we don't include `Three.Legacy.js`?

**Comment by aardgoose** [comment]
In the case for Vector[2|3|4].add() etc the warnings and checks are in the main code.  

I imagine Three.Legacy will still be required as other items become deprecated.

**Comment by Mugen87** [comment]
> Looking through the source history, there are warnings and parameter count checks in Vector2,3,4 dating from early 2013 for changes to the .add() .sub() etc methods.

I vote to remove this code.

**Comment by mrdoob** [comment]
>> Looking through the source history, there are warnings and parameter count checks in Vector2,3,4 dating from early 2013 for changes to the .add() .sub() etc methods.

> I vote to remove this code.

I don't know about that... Some people dive into three.js using (old) books that has outdated code. If we remove these they'll get a bit lost.

**Comment by Mugen87** [comment]
Um, good point. Didn't thought about that...

**Comment by pailhead** [comment]
Maybe the books could be updated.

**Comment by mrdoob** [comment]
Not the ones that have been printed already... 😛 But yes, they're updating them.

**Comment by pailhead** [comment]
Given how quickly threejs changes we could make proclamation that no threejs book should ever be printed on paper ever again :)

**Comment by mrdoob** [comment]
Blogposts are also an issue actually...

**Comment by Mugen87** [comment]
Turned out that instead of using a policy it's better to decide on a case by case basis whether a warning should be removed or not. A decision usually depends on many (sometimes opposing) factors like usability, performance, code complexity or the affect on tree shaking/bundle size. We have all of these in mind and always try to find the most appropriate solution when a warning is potentially removed.
