### ISSUE TITLE
frustum.intersectsObject not check geometry's groups

### ISSUE THREAD

**Issue by vinstics** [mrdoob/three.js#13545]
##### Description of the problem

When rendering scene, objects outside camera's frustum will not be rendered. But if object is geometry with groups, frustum.intersectsObject only checks the whole object's bounding sphere. Currently I workaround this by toggling material's visibility in scene.onBeforeRender/onAfterRender, but if some groups of geometry share the same material, this will not work.
  
	intersectsObject: function () {

		var sphere = new Sphere();

		return function intersectsObject( object ) {

			var geometry = object.geometry;

			if ( geometry.boundingSphere === null )
				geometry.computeBoundingSphere();

			sphere.copy( geometry.boundingSphere )
				.applyMatrix4( object.matrixWorld );

			return this.intersectsSphere( sphere );

		};

	}()

##### Three.js version

- [x] Dev
- [x] r90

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
Related: #7071

**Comment by vinstics** [comment]
Here's my workaround. I had tested it with huge scene in Chrome 65. It‘s’ performance still good even though toggling material's visibility per rendering brings extra consumption. Native support will have even better performance.

    /* tslint:disable no-invalid-this */
    import * as THREE from './buffergeometry.type';
    
    THREE.BufferGeometry.prototype.computeBoundingSphereByGroup = function() {
    
      if (!Array.isArray(this.boundingSphereGroup)) {
        this.boundingSphereGroup = [];
      } else {
        return; // 已经计算过了
      }
    
      const position: THREE.BufferAttribute = this.attributes.position;
      const indices: THREE.BufferAttribute = this.index;
      const groups: { start: number; count: number; materialIndex?: number }[] = this.groups;
      const box = new THREE.Box3();
      const vector = new THREE.Vector3();
    
      if (position && groups) {    

        for (let j = 0, len = groups.length; j < len; ++j) {

          const group = groups[j];    
          const idx: number[] = [];

          if (indices) {
            const array = indices.array;
            for (let i = 0; i < group.count; ++i) {
              idx.push(array[group.start + i]);
            }
          } else {
            for (let i = 0; i < group.count; ++i) {
              idx.push(i);
            }
          }
    
          const pos: number[] = [];
          let index;
          for (let i = 0, count = idx.length; i < count; ++i) {
            index = idx[i];
            pos.push(position.getX(index));
            pos.push(position.getY(index));
            pos.push(position.getZ(index));
          }
    
          box.setFromArray(pos);
    
          const sphere = new THREE.Sphere(box.getCenter());
          const center = sphere.center;
          let maxRadiusSq = 0;
    
          for (let i = 0, il = pos.length; i < il;) {
            vector.x = pos[i++];
            vector.y = pos[i++];
            vector.z = pos[i++];
            maxRadiusSq = Math.max(maxRadiusSq, center.distanceToSquared(vector));
          }
    
          sphere.radius = Math.sqrt(maxRadiusSq);
          if (isNaN(sphere.radius)) {
            console.error('THREE.BufferGeometry.computeBoundingSphere(): ' + // tslint:disable-line
              'Computed radius is NaN. The "position" attribute is likely to have NaN values.', this);
          }
    
          this.boundingSphereGroup.push(sphere);
        }
      }
    
    };



      private onBeforeRender(renderer: THREE.WebGLRenderer,
                             scene: THREE.Scene,
                             camera: THREE.OrthographicCamera | THREE.PerspectiveCamera,
                             target) {
        const objects: THREE.Mesh[] = [];
        scene.traverse((object) => {
          if (ESFilter.isESObject(object)) {
            objects.push(object as THREE.Mesh);
          }
        });
    
        const frustum = new THREE.Frustum();
        const projectMatrix = new THREE.Matrix4();
        const sphere = new THREE.Sphere();
        projectMatrix.multiplyMatrices(camera.projectionMatrix, camera.matrixWorldInverse);
        frustum.setFromMatrix(projectMatrix);
    
        for (let i = objects.length; i--;) {
          const mesh = objects[i];
          const matrix = mesh.matrixWorld;
          const materials = mesh.material as THREE.Material[];
          const geometry = mesh.geometry as THREE.BufferGeometry;
          geometry.computeBoundingSphereByGroup();
    
          for (let j = materials.length; j--;) {
            const mat = materials[j] as THREE.MeshStandardMaterial;
            mat.originVisible = mat.visible;
            sphere.copy(geometry.boundingSphereGroup[j]).applyMatrix4(matrix);
            mat.visible = frustum.intersectsSphere(sphere);
          }
        }
      }
    
      private onAfterRender(renderer: THREE.WebGLRenderer,
                            scene: THREE.Scene,
                            camera: THREE.OrthographicCamera | THREE.PerspectiveCamera,
                            target) {
        const objects: THREE.Mesh[] = [];
        scene.traverse((object) => {
          if (ESFilter.isESObject(object)) {
            objects.push(object as THREE.Mesh);
          }
        });
    
        for (let i = objects.length; i--;) {
          const materials = objects[i].material as THREE.Material[];
          for (let j = materials.length; j--;) {
            const mat = materials[j] as THREE.MeshStandardMaterial;
            mat.visible = mat.originVisible;
          }
        }
      }

**Comment by Mugen87** [comment]
Are you okay with marking the issue as a duplicate and focus on #7071, instead?

**Comment by vinstics** [comment]
@Mugen87 yeah, that's all right. It's just one use case you may consider to make this library better.
