### ISSUE TITLE
Unit Tests: What is the intended Runtime Environment?

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#13556]
##### Description of the problem

While fixing some unit tests, I've noticed that some parts of the code are unable to run in a node.js environment since there are dependencies to `XMLHttpRequest` and `window.performance`. Because of this the command `npm run test` does not produce a flawless result.

I wonder what is the intended way to execute the unit tests. Calling `test/unit/UnitTests.html` in the browser? If so, we should maybe remove `npm run test` and only have `npm run build-test`. Or we remove `test/unit/UnitTests.html` and just focus on node.js.

##### Three.js version

- [X] Dev
- [X] r90
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
Personally I use the browser so I can filter into specific test suites (probably qunit CLI can do that too?) and step through a debugger. But if we want to do so, we could use something like [karma-qunit](karma-qunit) to have `npm test` run tests in a browser and display results in CLI.

Having a way to run tests in CLI would be nice-to-have I think though, e.g. we could use a recommended set of "polyfills" like XmlHttpRequest and TextDecoder, and have some warning when new changes require different workarounds...

**Comment by Mugen87** [comment]
Okay, i make a small PR so `npm run test` is free of fails. I just skip the problematic tests. Not the best solution but we can improve this later.

**Comment by fernandojsg** [comment]
+1 for running it on the cli as we could use them for CI

**Comment by Mugen87** [comment]
Thanks for your feedback! So there are valid use cases for both browser and CLI support 👍
