### ISSUE TITLE
OrbitControls.js triggers scroll-prohibiting bug in Firefox 58+

### ISSUE THREAD

**Issue by loldrup** [mrdoob/three.js#13559]
https://github.com/loldrup/firefox_scroll_bug

The repository linked to above contains a "minimal" (ahem...) code example for inducing a scroll-prohibiting bug in Firefox 58+.

The file orbit_controls.html in the repository is a near-standard example of using the OrbitControls.js.  The only thing I have added is 50 lines of html saying "Hello1", "Hello2" etc. to the top of the page. With that many lines on the page, a need for scrolling arises. But this scrolling is not possible in Firefox 58, while it was perfectly possible in Firefox 57. Thus there is a regression bug in Firefox.
Do note thar the actual orbit controls example visualisation can't be seen, as it is placed at the bottom of the page, below the 50 lines... 

The challenge is to reduce the code of this bug-inducing example. The Firefox bug manager has asked for that. I know very little about the internals of three.js and OrbitControls.js. Thus I'm asking for help from the three.js developers on how to reduce the code size for this bug-example, while keeping the bug-inducing behavior.

This is the Firrefox bug on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1418442

**Comment by XanderLuciano** [comment]
This actually sounds like a bug in FireFox 57 and not FireFox 58. The page has `overflow: hidden` on the body tag which **should** prevent scrolling. 

I forked your repo and created 2 examples showing the difference in behavior with and without `overflow: hidden`

No Scrolling: https://xanderluciano.github.io/firefox_scroll_bug/no-scroll.html
Scrolling: https://xanderluciano.github.io/firefox_scroll_bug/scroll.html

If they are both scrolling in FireFox 57 then it's a bug in FireFox 57 as the behavior is as expected in Chrome 65 and FireFox 58 (can't find a standalone download for 57 right now).

**Comment by loldrup** [comment]
Woops.. I got the Firefox version number wrong. The bug occurs in FF 57+,
but is absent in FF 56.
I'm delighted to learn that the issue comes down to simply setting a flag.
That should make it quite easy to fix this "bug" in my program code :)))

Thank you!
