### ISSUE TITLE
My material texture is being distorted and glitched as I go farther away

### ISSUE THREAD

**Issue by challakoushik** [mrdoob/three.js#13557]
The wallpaper texture I applied on my wall flickers very heavily for some reason and I don't know why. When I'm close to the mesh, it looks somewhat fine but once I take the camera far away the texture gets heavily distorted. I did try turning antialias of the render on and off but that doesn't seem to be the issue. Secondly, this issue doesn't happen when there is only color and no texture on the material, so I'm assuming its something to do with the texture.

![screenshot 3](https://user-images.githubusercontent.com/20658812/37242119-06bfa45c-248a-11e8-8a85-13e041491c55.jpg)
![screenshot](https://user-images.githubusercontent.com/20658812/37242124-1471e4b6-248a-11e8-98a6-fa9915125000.jpg)
![screenshot 1](https://user-images.githubusercontent.com/20658812/37242129-1f1117ca-248a-11e8-892a-ac5b0851e408.jpg)
![screenshot 2](https://user-images.githubusercontent.com/20658812/37242132-270febea-248a-11e8-921a-fd1f3fd88fd4.jpg)

**Comment by looeee** [comment]
This is not a help site, ask on the forum: 
https://discourse.threejs.org
