### ISSUE TITLE
LOD: Use .onBeforeRender() instead of .update()

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#13572]
`THREE.LOD` currently requires manual updates via `lod.update( camera )` in the render loop. Perhaps this can be done automatically using `onBeforeRender` now?

**Comment by Mugen87** [comment]
I like the idea. I just wonder if there are use cases where you don't want to update the LOD object each frame but at a lower tick rate. A separate `.update()` method could be useful in this context.

**Comment by mrdoob** [comment]
If we do this using `onBeforeRender` in VR it would happen per eye, and it could happen that the result is different for each eye...

Ideally this would happen at projecting time?

**Comment by donmccurdy** [comment]
Hm good points..  Sounds like `.update( camera )` is reasonable to keep then. :)
