### ISSUE TITLE
TypeScript port of three.js

### ISSUE THREAD

**Issue by semleti** [mrdoob/three.js#13576]
##### Description of the problem

Hello fellow threejsers!
Today I would like to present a project I've been working on and off for a month: a [TypeScript](https://www.typescriptlang.org) port of three.js creatively called [three.ts](https://github.com/semleti/three.ts)
It's mostly for fun and to get more familiar with TypeScript and three.js, but I hope it could end up being usefull to someone.
The project is ~90% done.
It currently passes all unit tests ( except 8).
~90% of the [examples](https://htmlpreview.github.io/?https://github.com/semleti/three.ts/blob/master/examples/index.html) are working.

Sadly, I have introduced a few bugs which don't throw an error, so I have no idea where to start looking for them :/
I would really appreciate it if some of you could give a few of the [issues](https://github.com/semleti/three.ts/issues) a quick look to give me a clue as to where to start looking.

Feel free to [drop by](https://github.com/semleti/three.ts) to check the project out, tell me what you think of it or what might be the root of one of the issues ;)
Please let me know if you find any bugs :p

project: https://github.com/semleti/three.ts
issues: https://github.com/semleti/three.ts/issues
examples: https://htmlpreview.github.io/?https://github.com/semleti/three.ts/blob/master/examples/index.html
(there are a few issues with the examples when viewed through htmlpreview.github.io, so you might want to download them)

The one issue which saddens me the most is that triangles are rendererd in the wrong order:
https://github.com/semleti/three.ts/issues/2

![rendering_order_glitch](https://user-images.githubusercontent.com/16369524/37299503-cc19d0c0-2623-11e8-815c-4074230bd408.png)

  
  
Tested only on my machine for now:

##### Three.js version

- [x] Dev
- [ ] r90
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
NVidia GeForce GTX 760

**Comment by Mugen87** [comment]
I guess the [forum](https://discourse.threejs.org/) is a better place for this post.

**Comment by semleti** [comment]
Thank you.
I had asked @mrdoob if the threejs github was a good place since it's in part about coding, which he said was ok.
But I'll gladly go to the forum if you think it's a better place for this :)
Sorry for the trouble ;)

**Comment by Mugen87** [comment]
No problem. It's just my personal opinion.

**Comment by semleti** [comment]
Moved to the forum:
https://discourse.threejs.org/t/typescript-port-of-threejs/2104
