### ISSUE TITLE
Blender exporter works with Skeleton animation but wrong rotation with regular objects

### ISSUE THREAD

**Issue by giangm9** [mrdoob/three.js#13577]
##### Description of the problem
Blender 2.78, 2.79
I have a blender file with 2 skeleton animation and 2 monkeys
![peek 2018-03-13 11-13](https://user-images.githubusercontent.com/10234339/37322348-8cd95336-26af-11e8-9eb8-47f6b83ba8ab.gif)
when i export from blender to threejs, here is the result
https://giangm9.github.io/blender3js/public/examples/anim.html
as you can see, only 1 object was exported correctly, that is the object in with original at (0, 0, 0)
The rotation of the 2 monkey also wrong
The blend file is downloadable at the top-left corner of the page
Here is the export options, i export from command line
```
{'addon_version': (1, 5, 0),
 'animations': 'pose',
 'applyModifiers': True,
 'blendShapes': True,
 'bones': True,
 'cameras': True,
 'colors': True,
 'compression': None,
 'customProperties': True,
 'embedAnimation': True,
 'embedGeometry': True,
 'embedTextures': False,
 'enablePrecision': True,
 'exportTextures': True,
 'extraVertexGroups': '',
 'faceMaterials': True,
 'faces': True,
 'frameIndexAsTime': False,
 'frameStep': 1,
 'geometryType': 'geometry',
 'hierarchy': True,
 'indent': True,
 'indexType': 'Uint16Array',
 'influencesPerVertex': 2,
 'lights': True,
 'logging': 'disabled',
 'maps': True,
 'materials': True,
 'mixColors': True,
 'morphTargets': False,
 'normals': True,
 'precision': 6,
 'scale': 1.0,
 'scene': True,
 'skinning': True,
 'textureFolder': 'tests/blend/textures',
 'tracks': True,
 'uvs': True,
 'vertices': True}
```

##### Three.js version

- [ ] Dev
- [x] r90
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
None

**Comment by donmccurdy** [comment]
This is likely a bug in the exporter, but FWIW I'm working on u[pdates to the glTF Blender Exporter to support multiple animations](https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/166). If you want to try the experimental version there with `THREE.GLTFLoader`, it should just work:

![715a598f-de31-4983-be16-058bfcbb55d1-44168-0001de4a58408e11](https://user-images.githubusercontent.com/1848368/37323917-c315d1de-2643-11e8-9bad-95d1e7be9c84.gif)

[anim.zip](https://github.com/mrdoob/three.js/files/1805561/anim.zip)

**Comment by donmccurdy** [comment]
If I give each bone a unique name, I get better results, but still broken...

**Comment by giangm9** [comment]
I think the problem with the skeleton animation is: In blender, the Mesh is the  child of the skeleton, but in threejs, the skeleton is the child, but the location of the Mesh is relative to its parent, so that the location of the mesh is at (0, 0, 0)

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117).

https://threejs.org/docs/#manual/introduction/Loading-3D-models
