### ISSUE TITLE
Dose three.js support cross-domain access?

### ISSUE THREAD

**Issue by trymoremore** [mrdoob/three.js#13579]
Dose three.js support cross-domain access?
I want to use image with URL like  as material's mapDiffuse but chrome get the error "DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': Tainted canvases may not be loaded.".
![309894ee-e795-492b-affd-a6d251256084](https://user-images.githubusercontent.com/27277007/37325753-2af84562-26ca-11e8-9937-c93eb6694904.png)

**Comment by Usnul** [comment]
To me this is not sufficient to debug your issue. In short: "yes is dose". 
I suggest you provide more information on what you are loading and how. What is the version of three.js that you are using?

**Comment by Mugen87** [comment]
@trymoremore Please use the [forum](https://discourse.threejs.org/) if you need more help. Like @Usnul said, loading assets from different origins is supported. But it's more a feature of the Web Platform and than of `three.js`.

**Comment by liericiyan** [comment]
the same question
