### ISSUE TITLE
DOF2 example broken

### ISSUE THREAD

**Issue by mirohristov-com** [mrdoob/three.js#13599]
The [dof2 example](https://threejs.org/examples/#webgl_postprocessing_dof2)  seems to have stopped working since r91 and r90 or even before that. 

My guess is it's the `depthMaterial = new THREE.MeshDepthMaterial();` returning blank/black result but I'm pretty new to threejs so I wouldn't know.

It appears to be working better in r88 - https://jsfiddle.net/3bvpr75n/4/

Any idea for a quick fix besides downgrading?

##### Three.js version

- [x] r91

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
Can you please check if it looks better with this adjusted fiddle? https://jsfiddle.net/3bvpr75n/14/

**Comment by mirohristov-com** [comment]
Yes. I'm not sure if that's what the original example looked like but at least the depth is taken into account when blurring. Should we just fix the bokehShader?

**Comment by Mugen87** [comment]
Now that i think about it...i don't think the fix is correct. I'll try to revisit this over the next days.

**Comment by Mugen87** [comment]
I guess we need a similar fix like in #11881

**Comment by otse** [comment]
This is broken again, no clue.

Here is an older version that works. Does @Mugen87 have a simple hotfix for this? 

http://broiler.astrometry.net/~kilian/bloopyfloop/examples/webgl_postprocessing_dof2.html

**Comment by Mugen87** [comment]
Thanks for sharing this. I'll try to have a look in the next days.

**Comment by Mugen87** [comment]
There seems to a problem with calculating the focal depth.

**Comment by Mugen87** [comment]
I think the example needs a complete overhaul. I've only fixed the depth sampling which was definitely broken. There are more things that needs a correction: The example does not focus objects in the center and back.

**Comment by Mugen87** [comment]
@mrdoob Maybe it's better to remove this example and the broken `webgl_postprocessing_ssao` from `files.js` for the moment. We can add the back when they are working again.

**Comment by Mugen87** [comment]
Any help in this would be great! 😊

**Comment by Mugen87** [comment]
@otse Can you please check if the new PR solves the problem? It should be hopefully better than before.

https://rawgit.com/Mugen87/three.js/dev7/examples/webgl_postprocessing_dof2.html

**Comment by otse** [comment]
I think you almost got it, but the closest monkeys don't focus.

**Comment by Mugen87** [comment]
They actually do, you just have to increase the f-stop value to increase the DOF.

The PR ensures that the focus is now expressed in world z. I'm not sure what units were used before but the parametrization slightly changed.

**Comment by Mugen87** [comment]
It's about the following lines. The value for the uniform `focalDepth` should be a viewZ value.

https://github.com/mrdoob/three.js/blob/efeb95f10790ab4755171584139d5344177f2713/examples/webgl_postprocessing_dof2.html#L420-L426

**Comment by zz85** [comment]
@Mugen87 - looks like you're going down the right path. The change in depth packing requires a javascript equivalent of `perspectiveDepthToViewZ()` calculated in the shaders to match up the correct values.

**Comment by Mugen87** [comment]
Thank for the feedback! I've tried the following:
```js
function perspectiveDepthToViewZ( invClipZ, near, far ) {

    return ( near * far ) / ( ( far - near ) * invClipZ - far )

}
```
And then in the render function
```js
point.copy( intersects[ 0 ].point );

point.applyMatrix4( camera.matrixWorldInverse ).applyMatrix4( camera.projectionMatrix );

var viewZ = perspectiveDepthToViewZ( point.z, camera.near, camera.far );
```
But it seems the calculated `viewZ` value is too small. When i select monkeys in the back, the spheres in the front getting sharp.

**Comment by mrdoob** [comment]
@Mugen87 I think this broke when we changed the depth texture? Have you tried `1.0 - viewZ`?

**Comment by Mugen87** [comment]
Yes, but this does not work :disappointed: . According to https://stackoverflow.com/a/12904072/5250847, it should be:
```js
point.project( camera );
var depth = ( point.z + 1 ) * 0.5; // ensure normalized range [0,1]
var viewZ = perspectiveDepthToViewZ( depth, camera.near, camera.far );
```
The result is now better but it's still not possible to focus the monkeys in the front.

**Demo**: https://jsfiddle.net/3bvpr75n/34/
