### ISSUE TITLE
raycaster's doc needs update

### ISSUE THREAD

**Issue by vinstics** [mrdoob/three.js#13598]
##### Description of the problem
[Raycaster](https://threejs.org/docs/index.html#api/core/Raycaster)

indices seems no longer exists. face and faceIndex will always be set.

<blockquote>
When intersecting a Mesh with a BufferGeometry, the faceIndex will be undefined, and indices will be set; when intersecting a Mesh with a Geometry, indices will be undefined.
</blockquote>

##### Three.js version

- [x] Dev
- [x] r91

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
That's correct. Would you like to do a PR with the change? 😊

**Comment by Mugen87** [comment]
Also noticed that for non-indexed `BufferGeoemtry` an additional property `index` is set. This should also be added in the docs.

https://github.com/mrdoob/three.js/blob/566f53d5db20a7088b5462c5f3755930914b7abf/src/objects/Mesh.js#L298-L303

**Comment by WestLangley** [comment]
You can remove it and see if users complain.

**Comment by vinstics** [comment]
@Mugen87 Sorry I'm not familiar with git and don't know how to do a PR, I'll learn it soon and try next time.

**Comment by Mugen87** [comment]
@vinstics Thanks for reporting the issue!
