### ISSUE TITLE
deviceorientation laggy behavior 

### ISSUE THREAD

**Issue by iBasel** [mrdoob/three.js#13604]
##### Description of the problem

Since updating to chrome 65 on android, deviceorientation has become laggy.
https://threejs.org/examples/#misc_controls_deviceorientation

Not sure if this is related:
https://developers.google.com/web/updates/2017/09/webvr-origin-trial-chrome-62

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I can reproduce the issue on my Pixel with Chrome. No problems with FF.

Seems to be a browser issue though.

**Comment by mrdoob** [comment]
Yeah, this is a regression in Chrome 65. Its been fixed already though. Next browser update should get this fixed.
