### ISSUE TITLE
 I set the transparent color.But chorme doesn't show up properly.

### ISSUE THREAD

**Issue by CGerAJ** [mrdoob/three.js#13600]
##### Description of the problem

Firefox & safari can be implemented, but the background can't be displayed in the background with the chrome threejs under the multi-layer dom structure.

I set the transparent color.Firefox & safari can be implemented,But chorme doesn't show up properly.I have submitted the question to google.

```
renderer.setClearColor(0xffffff, 0);
```

templates ADDress:

http://www.luckhome.cn/threejs/index.html

##### Three.js version

- [x] r91

##### Browser

- [ ] All of them
- [x] Chrome  65 & Chrome  64
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS 10.13.3
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by CGerAJ** [comment]
<img width="705" alt="2222222" src="https://user-images.githubusercontent.com/20548301/37459109-0d35a2ea-2882-11e8-99c3-3a67bb2e6b35.png">

**Comment by CGerAJ** [comment]
![11111111](https://user-images.githubusercontent.com/20548301/37459123-1a569efc-2882-11e8-80b9-052a57b019dd.png)

**Comment by CGerAJ** [comment]
Normal display status

<img width="1665" alt="33333333" src="https://user-images.githubusercontent.com/20548301/37459173-4096a224-2882-11e8-98cb-ebe73529bcab.png">

**Comment by Mugen87** [comment]
Have you considered using your background image as a background texture? Something like:
```js
var loader = new THREE.TextureLoader();
var texture = loader.load( 'path/to/your/background_image.jpg' );
scene.background = texture; 
```
This should also work in Chrome.

**Comment by WestLangley** [comment]
@Mugen87 I do not think `CanvasRenderer` supports scene background images.

**Comment by Mugen87** [comment]
Oh, i did not realize he is using `CanvasRenderer`...

**Comment by Mugen87** [comment]
@CGerAJ In any event, you should report this at the Chromium issue tracker instead. I've tested this on my machine and the bug only happens with Chrome and not with Safari and FF.

https://bugs.chromium.org/p/chromium/issues/list

**Comment by CGerAJ** [comment]
Yesterday, I sent a screenshot to Google.Recently, there have been more and more bugs in chorme version 65.

https://bugs.chromium.org/p/chromium/issues/list

I can't open this page.Thank you for submitting issues to chorme.

**Comment by mrdoob** [comment]
@CGerAJ Are you using `CanvasRenderer` for compatibility or because you liked that effect?

**Comment by Mugen87** [comment]
Um, it does not work with Chrome Canaray (67.0.3372.0), too :pensive:

**Comment by CGerAJ** [comment]
@mrdoob  That's what the design needs are. I've avoided this bug by modifying the DOM structure. I hope Google can fix these bugs

**Comment by Mugen87** [comment]
I've debugged this one more time. Instead of setting `renderer.setClearColor(0xffffff, 0);`, create your renderer like this:
```js
renderer = new THREE.CanvasRenderer( { alpha: true } );
```
In this way, you background image should work in Chrome, too.

**Comment by CGerAJ** [comment]
Today I tested the method you gave me, and solved my problem.TKS

https://threejs.org/docs/index.html#examples/renderers/CanvasRenderer

```
alpha - whether the canvas contains an alpha (transparency) buffer or not. Default is false.
```
