### ISSUE TITLE
Clone defines on Material.clone()?

### ISSUE THREAD

**Issue by f1cognite** [mrdoob/three.js#13602]
##### Description of the problem
Should the `Material.clone()` function also clone / copy the defines on the original material?

##### Three.js version

- [ ] Dev
- [x] r90
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I guess this is only relevant for `ShaderMaterial`. The respective `.copy()` method already regards `.defines`.

https://github.com/mrdoob/three.js/blob/566f53d5db20a7088b5462c5f3755930914b7abf/src/materials/ShaderMaterial.js#L96

**Comment by WestLangley** [comment]
@f1cognite Can you please explain your use case or show a code snippet?

**Comment by Mugen87** [comment]
Now that i look at the code. Why don't we do this?
```js
this.defines = Object.assign( {}, source.defines );
```
Otherwise both materials refer to the same `defines`, right?
