### ISSUE TITLE
Can not set DirectionalLightShadow's direction

### ISSUE THREAD

**Issue by iamnotstone** [mrdoob/three.js#13608]
##### Description of the problem

The DirectionalLightShadow always lookAt Vector3(0,0,0).

I set its direction below, but it not works. The light.shadow.camera always lookAt (0,0,0)
```
      var light = new THREE.DirectionalLight(0xffffff, 1)
      light.position.set(20,0,20)
      light.lookAt(new THREE.Vector3(400,400,400))
      light.castShadow = true
```
here is my code on codepen:

[codepen] (https://codepen.io/iamnotstone/pen/jzrzge)

##### Three.js version

 - [x] r91

##### Browser

- [x] Chrome

##### OS

- [x] Linux

**Comment by WestLangley** [comment]
This is not a help site. Please use the [forum](https://discourse.threejs.org).
