### ISSUE TITLE
Uncaught TypeError when render an empty BufferGeometry with wireframe

### ISSUE THREAD

**Issue by NataliaDSmirnova** [mrdoob/three.js#13601]
##### Description of the problem

I render a mesh that consists of empty geometry (without positions an indices) and material with wireframe:

` var geometry = new THREE.BufferGeometry(); `
` var material = new THREE.MeshPhongMaterial( {wireframe: true} );`
`mesh = new THREE.Mesh( geometry, material );`
` scene.add( mesh );`

**Expected result:**
Nothing is rendered

**Actual result:**
An exception occured:
>Uncaught TypeError: Cannot read property 'array' of undefined
    at Object.getWireframeAttribute (three.min.js:37)
    at Xd.renderBufferDirect (three.min.js:179)
    at n (three.min.js:152)
    at u (three.min.js:151)
    at Xd.render (three.min.js:186)
    at animate ((index):113) 

There is a live example:
* [jsfiddle]http://jsfiddle.net/akmcv7Lh/310/) (latest release branch)

##### Three.js version

- [ ] Dev
- [x] r91
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows10
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
graphics card GeForceGTX 650

**Comment by Mugen87** [comment]
You need to add at least a `position` attribute: http://jsfiddle.net/akmcv7Lh/313/

Related: #10339

**Comment by Mugen87** [comment]
@mrdoob @WestLangley We could add a safety check at the following place. Or do we still consider that a `BufferGeometry` without `position` attribute is no valid geometry?

https://github.com/mrdoob/three.js/blob/566f53d5db20a7088b5462c5f3755930914b7abf/src/renderers/webgl/WebGLGeometries.js#L157

**Comment by NataliaDSmirnova** [comment]
@Mugen87 There is no information in documentation about legal minimum composition of BufferGeometry. Theoretically empty geometry should be valid, but not rendered. The safety check would be great.

**Comment by WestLangley** [comment]
There are many was to create an invalid geometry. We do not validate inputs in three.js. There are too many possible user errors to test for. We also give the users a lot of flexibility, and validation is hard.

>Or do we still consider that a BufferGeometry without a position attribute is no valid geometry?

I think the current status on that is it depends on what part of the code you are reading.

**Comment by bunnybones1** [comment]
The fix for this has caused a different issue. 
https://github.com/mrdoob/three.js/pull/18044
I'm not sure silencing this error was worth silently skipping rendering valid geometry that is missing an attribute called `position`. Maybe there's a better way to address both issues.

**Comment by Mugen87** [comment]
@bunnybones1 Let's discuss your issue in #18044 and not post in closed PRs/issues.
