### ISSUE TITLE
360 video plays only audio and black video on FireFox Android

### ISSUE THREAD

**Issue by ErezBouskila** [mrdoob/three.js#13624]
##### Description of the problem
When playing a 360 video on FF v59 on Android there is only audio and the video is black, checking the console the following error is displayed:
Error: WebGL warning: texImage2D: GetAsSourceSurface or GetDataSurface failed after blit failed for TexUnpackImage.

Steps to reproduce:
1. Open link in FF on Android - http://www.kaltura.com/index.php/extwidget/preview/partner_id/1900001/uiconf_id/38956021/entry_id/0_o4gnhsf7/embed/dynamic
2. Play the video and you will only hear the audio and the video will be black.

Related bugs:
https://github.com/mrdoob/three.js/issues/13206
https://github.com/mrdoob/three.js/pull/13215

##### Three.js version

- [ ] Dev
- [x] r91
- [x] 73

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I can reproduce the problem with FF 59.0.1 on Android 8.1.

You should report this problem to Mozilla instead since it's clearly a browser issue.

https://bugzilla.mozilla.org/
