### ISSUE TITLE
Wrong Variable in FBXLoader for specular color

### ISSUE THREAD

**Issue by BasicMan01** [mrdoob/three.js#13630]
**Description:**
In the following fixed issue a wrong variable for specular color ist used.

**Issue reference:**
#13515

**Code reference:**
https://github.com/mrdoob/three.js/blob/c3216344736b165c15af8fa8065748e180b189b4/examples/js/loaders/FBXLoader.js#L461

I think the correct left part must be "parameters.specular".

**Three.js version**
- [x] r91

**Comment by looeee** [comment]
Oops! I'll fix it 😅
