### ISSUE TITLE
Cant set spotlight target correctly.

### ISSUE THREAD

**Issue by isassaba** [mrdoob/three.js#13639]
Hi im trying to set up the car lights, but when i try to set the spotlight to the floor in front of the car it always target the point (0,0,0) nothing seems to modify that.
I've tried:
- spotlight.target.position.set(x,y,z);
-spotlight.target.updateMatrix();

I would aprecciate if you have any solution to do this quickly.
Thanks in advice.

**Comment by WestLangley** [comment]
https://threejs.org/docs/index.html#api/lights/SpotLight
```javascript
scene.add( light.target );
```

**Comment by ninofiliu** [comment]
Use `scene.add(light.target)` *then* `scene.add(light)`. (`scene.add(light.target, light)` is also fine).

If you do this the other way around, the spotlight will target the default of (0,0,0).
