### ISSUE TITLE
GLTFLoader: camera xfov calculation is wrong

### ISSUE THREAD

**Issue by pjoe** [mrdoob/three.js#13642]
##### Description of the problem

xfov is not calculated correctly. As fov is an angle you can not just multiply aspect ratio, but should do something like `xfov = atan(tan(yfov) / aspectratio)` (see https://www.gamedev.net/forums/topic/203238-perspective---x---fov/?tab=comments#comment-2294951)

This conversion is done here: https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js#L2356

##### Three.js version

- [x] Dev
- [x] r91

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by pjoe** [comment]
After more testing the right formula is:

`xfov=2*Math.atan(Math.tan(yfov/2) * aspect)`

**Comment by donmccurdy** [comment]
Thanks for the report! Looking at this now, I'm not sure why we convert to `xfov` at all... glTF provides `yfov`, or "The floating-point vertical field of view in radians", and the `THREE.PerspectiveCamera` constructor expects "Camera frustum vertical field of view" in degrees. So we should just convert directly from radians to degrees.

**Comment by pjoe** [comment]
Hah, that explains what I'm seeing ... double (or triple) checked that the xfov got calculated correctly, but scene still didn't look quite right :)

Should be very easy fix then.

**Comment by donmccurdy** [comment]
Opened #13646
