### ISSUE TITLE
webgl_loader_obj_mtl not working on Chrome 65/MacOS

### ISSUE THREAD

**Issue by Fasani** [mrdoob/three.js#13641]
##### Description of the problem
Console Errors
THREE.WebGLRenderer: Error creating WebGL context.
Uncaught TypeError: Cannot read property 'getExtension' of null

Please also include a live example if possible. You can start from these templates:
https://threejs.org/examples/webgl_loader_obj_mtl.html

Also on:
http://demos.littleworkshop.fr/infinitown

##### Browser
- [x] Chrome 65

##### OS
- [x] macOS

**Comment by Mugen87** [comment]
Both websites work for me on macOS (10.13.3) and Chrome (65.0.3325.162). Have you tested with other browser, too?

**Comment by looeee** [comment]
I get a lot of errors on the infinitown link... but not this error.

**Comment by mrdoob** [comment]
@Fasani Do you get that error only with that example or with all the examples? What graphics card do you have?

**Comment by mrdoob** [comment]
Thanks. Please, include graphics card info in the future and perform more testing before reporting.
These false positive issues can be time consuming for maintainers.
