### ISSUE TITLE
THREE.Plane projectPoint() gives wrong result

### ISSUE THREAD

**Issue by Elania** [mrdoob/three.js#13640]
I assume this function should project the given point onto the plane, so that as a result I get the point on the given plane that has the smallest distance to the given point.

Let's say I do have a simple Hesse plane that lies in the XZ plane with normal (0,1,0) and constant 10.
I want to project point (0,20,0) on that plane. Obviously, the projected point on the plane should be at (0,10,0).
So what I did was to create a THREE.Plane with these values I called the function projectPoint() with my point (0,20,0).

These are the functions from THREE.Plane that will be used:
```
distanceToPoint: function ( point ) {
  return this.normal.dot( point ) + this.constant;
},

projectPoint: function ( point, target ) {
  if ( target === undefined ) {
    console.warn( 'THREE.Plane: .projectPoint() target is now required' );
    target = new Vector3();
  }
  return target.copy( this.normal ).multiplyScalar( - this.distanceToPoint( point ) ).add( point );
},
```
If you would calculate it by hand:

distanceToPoint
(0, 1, 0) * (0, 20, 0) + 10 = 30

projectPoint
(0,1,0) * (-30) + (0, 20, 0)
= (0, -30, 0) + (0, 20, 0)
= (0, -10, 0)

The result is (0, -10, 0) but it should be (0, 10, 0). Am I getting something wrong here?

**Comment by looeee** [comment]
The equation of the plane is y + 10 = 0 
This is y = -10 
So the plane is below the x-axis, which means that (0, 10, 0) cannot be a point on the plane.

**Comment by Elania** [comment]
Ah sorry, my fault, I did not understand correctly how the plane should be defined here. 
It is
x * n + d = 0
instead of
x * n - d = 0
So I just need to multiply the constants of my planes with -1 and it should work.
Thank you very much for your help! 
Can be closed.
