### ISSUE TITLE
Degraded reflector/mirror performance since r90

### ISSUE THREAD

**Issue by Busata** [mrdoob/three.js#13656]
Today I've upgraded our codebase from r88 -> r91, everything seems to work fine aside from the reflectors (code which has not significantly changed since r88 from what I see). I've noticed that when checking individual upgrades, the problem starts at r90.

It seems to go exponentially bad when our entire model + mirror are in the frustrum, when I'm right in front of it & little else of the model, the performance is OK. Now since I can't provide live examples, I was wondering if someone could point me on where to look/investigate, or what could have changed in that release that affects them?

##### Three.js version

- [ ] Dev
- [x] r91
- [x] r90
- [ ] r89
- [ ] r88

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
>I can't provide live examples

Can you create a simple example or jsfiddle that duplicates the problem?

**Comment by Busata** [comment]
In our codebase, the effect below is even more exaggerated, from running rather smoothly at capped 60fps, to 10fps when a lot of furniture with different materials/geometry are in view. This was not an issue with 88 so something seems different.

Bit of a contrived example, but we render 3D models of houses with furniture in it, so I can't quite easily create an example of that.
(note that if the cube amount is too high for your PC to render, please adjust the Cubes amount)
(the far & near planes are deliberately high to remain consistent)

r88 : https://codepen.io/anon/pen/qomNpV/
r89 : https://codepen.io/anon/pen/WzjodK/ 
r90 : https://codepen.io/anon/pen/MVmbrx/

r88 & 89 both run for me at 17-18fps,
r90 drops it down to 9fps.

**Comment by mrdoob** [comment]
I don't see any mirror in these examples... 🤔

**Comment by Mugen87** [comment]
The mirror is at the ground. It's not easy to spot 😅 

Um, the only thing i remember is #13110

This change was very necessary since the rendering with mirrors was highly unpredictable and buggy.

**Comment by Mugen87** [comment]
BTW: I'm not sure the tests are 100% valid. The version of `Reflector` should always match the version of `three.js`. Currently you are using the latest version of `Reflector` in all demos.

**Comment by Busata** [comment]
@Mugen87 I've checked out the repo, according to annotate on the dev branch, nothing notable has changed since r88

**Comment by Mugen87** [comment]
Okay. I'll try to make a performance analysis tomorrow. I hope can see something obvious in my dev tools...

**Comment by Mugen87** [comment]
Um, i think the overhead is produced through additional calls of `initMaterial()` in `setProgram()`. When the reflectors renders the scene, the `lightsHash` of the respective material has changed because it renders the scene in a different `WebGLRenderState`. This will trigger an update of the material (but no program change). 
https://github.com/mrdoob/three.js/blob/683289bd00dc2eb8230744c03d7e7c67c68a2f2b/src/renderers/WebGLRenderer.js#L1640-L1644
This additional overhead was necessary in order to avoid the mentioned problems in #12883. The performance drop in @Busata's is so visisble since each of these 6000 boxes is rendered with an own material.

**Comment by Busata** [comment]
Heh, was about the post the same culprit, profiled our app:

https://imgur.com/a/EVxri

**Comment by Busata** [comment]
@Mugen87 from what I gather from that pull request, you've implemented the concept of render states that track the lights/shadows/... used for a rendertarget & restores them upon switching?

If so, the render state for reflector & the scene are in essence the same, is the juggling of materials updates really needed in those scenarios?

**Comment by Mugen87** [comment]
Since the reflector renders with a different view matrix, light uniforms are going to change. So updating these uniforms is necessary, hence the material update.

**Comment by Busata** [comment]
Ok, thanks. Will check why the updates in our case affect performance so badly.

**Comment by Busata** [comment]
Since we were using custom materials I was fearing it was that, but replacing them with basic materials causes serious fps drops too. We seem to have 900 different materials in the scene, which probably all get rendered too due to everything being in the frustum at the location where the fps drops. We'll have to hold off upgrading for now I suppose, can't think of alternatives for now to solve this differently.

**Comment by Busata** [comment]
Realised that we don't use any dynamic lights in the first place. So I can easily circumvent these state switches by setting lights property to false.

**Comment by Usnul** [comment]
related: https://github.com/mrdoob/three.js/issues/14121
