### ISSUE TITLE
Incorrect shape with holes, when one area eclosed by another

### ISSUE THREAD

**Issue by strangerintheq** [mrdoob/three.js#13653]
##### Description of the problem

Hi!
Problem description:
I have a svg path with holes and i want to extrude geometry from it, everything is fine except usecase where i have a isolated inner figure in source svg path

here is a [fiddle](https://jsfiddle.net/4h19hov1/22/) with example of problem
 
[dev-branch fiddle](https://jsfiddle.net/4h19hov1/24/)

at top of the scene: is the final result of extruding

at bottom: separated subshapes, one hole related to another polygon

edit: i dig into three.js code and figured out that is a bug of ShapePath.toShapes method.
the part of code with detection of correct hole target is bugged.  case when one area enclosed my another (countour hierarchy) is not handled properly

##### Three.js version

- [x] Dev
- [x] r91
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
- any

**Comment by Mugen87** [comment]
> the part of code with detection of correct hole target is bugged. case when one area enclosed my another (countour hierarchy) is not handled properly

Can you please link to the mentioned code section?

**Comment by Mugen87** [comment]
I could image that nested shapes are not supported so far...

**Comment by strangerintheq** [comment]
https://github.com/mrdoob/three.js/blob/dev/src/extras/core/ShapePath.js

Scroll down source to last return statement.
Look at the value of return variable, in my case it contains two shapes, one with hole from another. Code above is trying to resolve the relations between shapes and holes, but..

**Comment by WestLangley** [comment]
Pasting the path from the fiddle into `webgl_geometry_extrude_shapes2.html` produces this:

![screen shot 2018-03-21 at 1 01 53 pm](https://user-images.githubusercontent.com/1000017/37724936-381dc5b6-2d08-11e8-9998-a1c4bb2caf00.png)

**Comment by Mugen87** [comment]
@strangerintheq What is your intended visual output?

**Comment by strangerintheq** [comment]
Svg path is clockwise...

**Comment by Mugen87** [comment]
I mean can you please specify the expected visual output with a screenshot? TBH, i don't understand what you are trying to achieve...

**Comment by strangerintheq** [comment]
here is expected result [fiddle](https://jsfiddle.net/4h19hov1/30/) 
it achieved by manual managing of svg path subpaths sequence

**Comment by WestLangley** [comment]
What does "manual managing" mean?

**Comment by WestLangley** [comment]
>moved it to place after second subpath (1 2 3 4 5 -> 1 2 5 3 4)

Why do you think that worked?

Are your subpaths clockwise or counterclockwise or both?

**Comment by strangerintheq** [comment]
It seems that all my paths and sub paths is always clockwise

**Comment by strangerintheq** [comment]
I was fixed bug in my case with this code:

https://github.com/mrdoob/three.js/blob/dev/src/extras/core/ShapePath.js 
` 
return fixShapesHoles(shapes);



function findEnclosingShapes(hole, shapes) {
    return shapes.filter(function (shape) {
        return isPointInsidePolygon(hole.currentPoint, shape.getPoints());
    });
}

function findAllInnerShapes(shape, possibleInnerShapes) {
    return possibleInnerShapes.filter(function (s) {
        return isPointInsidePolygon(s.getPoints()[0], shape.getPoints());
    });
}

function findLastInnerShapeIndex(shapes) {
    return shapes.map (function (shape, i) {
        var copy = shapes.slice(0);
        copy.splice(copy.indexOf(shape), 1);
        return {
            index: i,
            shapes: findAllInnerShapes(shape, copy)
        };
    }).find(function (item) {
        return item.shapes.length === 0;
    }).index;
}

function fixShapesHoles(shapes) {
    if (shapes.length > 1) {
        var holesToShapeMap = [];
        var allHoles = shapes.reduce(function (acc, shape) {
            return acc.holes.concat(shape.holes);
        });
        shapes.forEach(function (shape) {
            shape.holes = [];
        });
        allHoles.forEach(function (hole, i) {
            holesToShapeMap[i] = findEnclosingShapes(hole, shapes)
        });
        holesToShapeMap.forEach(function (shapes, i) {
            var targetShapeIndex = shapes.length === 1 ? 0 :
                findLastInnerShapeIndex(shapes);
            shapes[targetShapeIndex].holes.push(allHoles[i]);
        });
    }
    return shapes;
}
`

**Comment by strangerintheq** [comment]
PS: let me know if you interesting in pull request

**Comment by WestLangley** [comment]
>It seems that all my paths and sub paths is always clockwise

By default, paths should be clockwise; holes counterclockwise. Please try it.

**Comment by strangerintheq** [comment]
@WestLangley but how? it is a input data for me, i cant determine where is shape or hole to reverse hole path

**Comment by WestLangley** [comment]
See this [SVG fill-rule property demo](https://codepen.io/AmeliaBR/pen/fmiEv).

**Comment by Mugen87** [comment]
I think we can close this issue. Like @WestLangley mentioned, input paths should be clockwise, holes counterclockwise. Users have to ensure that their data corresponds to this standard.

**Comment by WestLangley** [comment]
> input paths should be clockwise, holes counterclockwise. Users have to ensure that their data corresponds to this standard.

I would call it an SVG option, set by the SVG `fill-rule` property.

It is a three.js standard, however -- subject to the value of the `toShapes()` argument `isCCW`.

Note that three.js fills by triangulation, while SVG fills per pixel.

**Comment by mrdoob** [comment]
Maybe this is something that `SVGLoader` will be able to handle. Still early days though... #13478

**Comment by whatisor** [comment]
I get same issue when fill-rule is evenodd.
All paths and holes are clockwise.

**Comment by mrdoob** [comment]
@whatisor can you share the file?

**Comment by whatisor** [comment]
Here you are
https://1drv.ms/u/s!AlqoDpkC4l4wgeUls4-4WDA6PU5xzg?e=etwAHR

It is generated by potrace library

**Comment by whatisor** [comment]
So, I believe it is same issue to support evenodd rule:
https://github.com/iPlug2/iPlug2/issues/135
