### ISSUE TITLE
Is there an example of medical imaging (DICOM) ?

### ISSUE THREAD

**Issue by tanxu1120** [mrdoob/three.js#13668]
Is there an example of medical imaging (DICOM) ?
I did not find it.

**Comment by Mugen87** [comment]
There is only a NRRDLoader with a corresponding [example](https://threejs.org/examples/webgl_loader_nrrd.html) but no `DICOMLoader`. 

Reading this [article](https://www.embodi3d.com/blogs/entry/341-how-to-create-an-nrrd-file-from-a-dicom-medical-imaging-data-set/), it seems you want to create a NRRD file from a DICOM Medical Imaging Data Set for visualization purposes in any case.

**Comment by NicolasRannou** [comment]
@tanxu1120 please have a look at [ami.js](https://github.com/FNNDSC/ami).

You can think of it as an extension of Three for medical imaging. There are a bunch of loaders, helpers, custom shaders that should allow you to look at your data more easily.

https://fnndsc.github.io/ami/#geometries_slice

The difference with other existing web packages is that it is the only one based on WebGL for DICOM visualization.

**Comment by yasertalha** [comment]
i) I uploaded a Dicom image (.dcm) using html input Tag
ii) Then files from uploaded dicom image is added to cornerstoneWADOImageLoader library using  below func `cornerstoneWADOImageLoader.wadouri.fileManager.add(file);`   
iii) Then using function `cornerstone.loadImage` func, extracted the canvas and assigned that canvas as input to  `new THREE.Texture`

check this [codesandbox](https://codesandbox.io/s/xenodochial-firefly-ye087?file=/src/App.js:2284-2302) , 
if condition in line : 36 , is the code need to be corrected
