### ISSUE TITLE
Broken example "webgl_materials_envmaps_hdr"

### ISSUE THREAD

**Issue by bgirschig** [mrdoob/three.js#13669]
##### Description of the problem

It looks like the [webgl_materials_envmaps_hdr](https://threejs.org/examples/webgl_materials_envmaps_hdr) example is broken. The mipmap levels are all displayed simultaneously on the ground plane.
There are no errors in the console.

Maybe it's just a bug with the example but I thought it might be revealing a bug with three itself.

![screen shot 2018-03-23 at 9 29 31 am](https://user-images.githubusercontent.com/6248734/37819157-ce6d9d78-2e7c-11e8-856c-fc6fff82d940.png)

##### Three.js version

- [ ] Dev
- [x] r91
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
macbook air
Intel HD Graphics 5000

**Comment by Mugen87** [comment]
No, it's not a bug. It's intended to visualize the environment map.

**Comment by bgirschig** [comment]
oh ok, sorry for that
