### ISSUE TITLE
THREE.FontLoader() parse() does not return a THREE Font object instance

### ISSUE THREAD

**Issue by scottialex** [mrdoob/three.js#13665]
I use my own system getFile() function to retrieve files from our secure app. I fetched the file helvetiker_regular.typeface.json and then parsed it like so:

let loader = new THREE.FontLoader();
let font = loader.parse( jsonFile);

As you can see in my 3 attachments, the parse method returns a generic object, not an instance of a THREE Font object.

When I use loader.load() method it returns an instance of THREE Font object.

Is this a bug?

Alejandro

![screen shot 2018-03-22 at 2 28 11 pm](https://user-images.githubusercontent.com/6372395/37791706-4aef8f2a-2de0-11e8-8206-9de7c388f092.png)
![screen shot 2018-03-22 at 2 28 43 pm](https://user-images.githubusercontent.com/6372395/37791707-4afef92e-2de0-11e8-9970-06f644f4da39.png)
![screen shot 2018-03-22 at 2 29 30 pm](https://user-images.githubusercontent.com/6372395/37791708-4b0c90c0-2de0-11e8-8dbc-f7f4d9d9d1c7.png)

**Comment by Mugen87** [comment]
I guess you have to do this:
```js
let loader = new THREE.FontLoader();
let json = JSON.parse( jsonFile ); // You have to parse the data so it becomes a JS object 
let font = loader.parse( json );
```

**Comment by scottialex** [comment]
Aha! I did try JSON.parse() but inadvertently parsed it backwards!

I did this and of course it wouldn't work...
let font = loader.parse( jsonFile );
font = JSON.parse( font ); 

This is my final working code, thank you!

    getFile( "/fonts/helvetiker_regular.typeface.json", ( jsonString ) =>
    {
      let jsonParsed = JSON.parse(jsonString);
      let loader = new THREE.FontLoader();
      let font = loader.parse( jsonParsed );
      let shapes = font.generateShapes( "SAMPLE TEXT", 100, 2 );
    } );
