### ISSUE TITLE
Ring geometry being lit from direction opposite to normals with MeshStandardMaterial

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#13682]
See this [pen](https://codepen.io/looeee/pen/NYaKGN?editors=0010).

The light is affecting the ring geometry from the opposite direction to its normals when it has a `MeshStandardMaterial` applied. This occurs for both `RingBufferGeometry` and `RingGeometry`. Lighting works as expected with `MeshPhongMaterial`.

![front](https://user-images.githubusercontent.com/5307958/37873813-0a8f57e2-304e-11e8-883e-b8bbab1459cd.png)

![back](https://user-images.githubusercontent.com/5307958/37873815-0c663bb2-304e-11e8-82ff-b2eec47e6627.png)

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

**Comment by Mugen87** [comment]
Wait...everything is correct.

@looeee You just applied wrong values to the constructor of `RingBufferGeometry`.

see https://jsfiddle.net/f2Lommf5/3785/

Instead of 
````
new THREE.RingBufferGeometry( 20, 15, 32 );
````
it should be
```
new THREE.RingBufferGeometry( 15, 20, 32 );
```

**Comment by looeee** [comment]
Oh wow! Haha, didn't see that at all.

The order of parameters is completely opposite to what my intuition says is right, feels like it should be outer, then inner. 

Thanks 😁
