### ISSUE TITLE
Add object to panorama

### ISSUE THREAD

**Issue by phidang0810** [mrdoob/three.js#13697]
Hi guys.
I try to build mini app same with https://gigapixel.panoramas.com/superbowl/2018
I'm using example https://threejs.org/examples/#webgl_panorama_equirectangular  but I don't know how to do:
- I want to add object(box,...) into the position of mouse when mouse down. 
- Change object color when hover.
Could you help me! Thank you :)

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
