### ISSUE TITLE
Intent to implement WebGL2 support

### ISSUE THREAD

**Issue by fernandojsg** [mrdoob/three.js#13702]
We’ve been [discussing for a while](https://github.com/mrdoob/three.js/issues/9965) how to address the WebGL2Renderer implementation. But it seems we just keep delaying it because of other priorities and also due to the complexity, that surely will require a decent amount of time and effort to get it done completely.

To help unblocking this issue I have included this feature on my team’s roadmap ([mixed reality team at mozilla](https://twitter.com/mozillareality)) to help improving the WebGL & WebXR ecosystem. So you should expect some mozillians working on it not just as their hobby :)

I’ve been discussing with @mrdoob to create a [Github Project just for WebGL2Renderer](https://github.com/mrdoob/three.js/projects/3) so we could keep track of the things being developed for the WebGL2Renderer and make it easy to spot where your help could speed up the release of new features.

In the short term @takahirox has been working on [VAO](https://github.com/mrdoob/three.js/issues/8705) and [UBO](https://github.com/mrdoob/three.js/issues/13700) implementation, identifying the changes that must be done on the current renderer to accommodate them. So we would like to kick off the discussion with these two features.

**Comment by takahirox** [comment]
I made WebGL2 base branch following #9965 and #12250

Repo: https://github.com/takahirox/three.js/tree/WebGL2Base
Examples: https://rawgit.com/takahirox/three.js/WebGL2Base/examples/index.html

You can start WebGL2.0 + Three.js with it.

**Comment by lo-th** [comment]
yo i have a methode to convert any shader of three to webgl2
it's not so complex for glsl side 
a example ( if you see green V2 is webgl2 )
https://lo-th.github.io/Shader.lab/#metahexa

**Comment by fernandojsg** [comment]
Initial support for WebGL2 added on the `WebGLRenderer` 🎉 thanks to @takahirox https://github.com/mrdoob/three.js/pull/13717

**Comment by mrdoob** [comment]
I think this can be closed now. Since `r118`, `WebGLRenderer` creates a WebGL 2 context by default.
