### ISSUE TITLE
Object3D: localToWorld/worldToLocal for quaternion and scale?

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#13704]
I've been seeing a lot of questions boiling down to not knowing how to convert rotation to/from world coordinate space. There's a nice API to do this for position (`localToWorld`/`worldToLocal`) but no equivalent for quaternion and scale. We could consider adding those helpers, and perhaps deprecating the more limited `getWorld*()` getters. 

Proposed:

```js
// Converts argument from local to world space
object.localToWorldPosition( position )
object.localToWorldQuaternion( quaternion )
object.localToWorldScale( scale )

// Converts argument from world to local space
object.worldToLocalPosition( position )
object.worldToLocalQuaternion( quaternion )
object.worldToLocalScale( scale )
```

Based on https://github.com/mrdoob/three.js/pull/5420 we might not want to add such helpers. I'll admit I dislike the verbose names. But `getWorld*(target)` is strictly less useful than the proposal, and has the notable side effect of calling `updateMatrixWorld()` where `fooToBar` does not.

Alternatively, additions to the [matrix transformation docs](https://threejs.org/docs/#manual/introduction/Matrix-transformations) might do the job.

/cc @WestLangley @jbaicoianu

**Comment by donmccurdy** [comment]
Very probably there is a better API for this that would not involve Object3D... 🤔

**Comment by WestLangley** [comment]
As I [said](https://github.com/mrdoob/three.js/pull/5420#issuecomment-58297430):

>Object3D.localToWorld( vector ) and Object3D.worldToLocal( vector ) are two methods I would remove.
>How does an object transform a vector? Of course, the answer is it doesn't.

I know they are widely-used, so they would have to be deprecated in favor of an alternative.

**Comment by WestLangley** [comment]
@donmccurdy Actually, I am not sure I understand what your concern is...

**Comment by donmccurdy** [comment]
@WestLangley if I understand correctly, your concern is with the current `localToWorld` API surface, not the functionality it provides? I agree with that, if so.

If I have a position in the local coordinate space of object1 and want to convert it the local coordinate space of object2, `localToWorld` / `worldToLocal` does the job nicely. To do the same thing with rotation, you need to be comfortable working with matrices, and I think we could make that a bit easier unless there are shortcuts I've missed.

How about:

```js
// worldToLocal
object.matrixWorld.transformPosition( position );
object.matrixWorld.transformQuaternion( quaternion );
object.matrixWorld.transformScale( scale );

// localToWorld
matrixWorldInverse = new Matrix4().getInverse( object.matrixWorld );
matrixWorldInverse.transformPosition( position );
matrixWorldInverse.transformQuaternion( quaternion );
matrixWorldInverse.transformScale( scale );
```

**Comment by trusktr** [comment]
I think this is nice:

```js
object.matrixWorld.clone()  // returns a new matrix, if you want a new one.
  .inverse() // modifies the new one in place
  .transformPosition(object.position)
```

and if you're using a cache:

```js
const m = new Matrix4
// ...
m.copy(object.matrixWorld) // don't make a new one, use a cache
  .inverse() // modifies m in place
  .transformPosition(object.position)
```

The difference making the existing `clone` and `copy` first class citizens because they already exist. `.inverse()` would always modify in place.  

Internally, this `inverse()` method could use a cache (instead of accepting `m` as a parameter), which helps with the implementation itself.

I feel this makes the mental model of `inverse()` nicer without an extra parameter, while `clone` and `copy` provide the mechanisms by which to make those other choices.

The same could apply to all the other math methods (in-place method, with clone/copy/new for making the other choices of "make a new one" or "use a cache"). It's just simpler.

**Comment by WolfgangFahl** [comment]
I think even this proposal does not help yet. The current way rotation is implemented is not intuitive and very very very confusing for beginners. If you rotate something you might end up having the positions of elements changed that you did not intend to reposition. See https://stackoverflow.com/questions/57311356/rotating-an-object-properly-around-a-pivot-point-given-axis-and-angle for how many approaches and questions are already out there. Many of the approaches and examples are outdated and add to the confusion. It would be good to have more "proper/official" example that show how a tree of objects with rotated childs can be handled. Currently I am using the 

```
static adjustRelativeTo(mesh, toMesh) {
    //logSelected("adjusting toMesh",toMesh);
    //logSelected("beforeAdjust",this.mesh);
    toMesh.updateMatrixWorld(); // important !
    mesh.applyMatrix(new THREE.Matrix4().getInverse(toMesh.matrixWorld));
    //logSelected("afterAdjust",this.mesh);
  }
```

pattern and I am not even sure whether this is the correct approach.

**Comment by makc** [comment]
this ticket was mentioned in `a way to get worldToLocal for quaternions` question, so here is [one](https://jsfiddle.net/h9cgs0t2/) way to convert rotation to local frame, assuming uniform scale

**Comment by WestLangley** [comment]
@donmccurdy I can add something like this, if you want:
```js
setWorldPosition: function ( vector ) {

	this.position.copy( vector );

	if ( this.parent ) {

		this.parent.updateWorldMatrix( true, false );

		this.position.applyMatrix4( _m1.getInverse( this.parent.matrixWorld ) ); // hopefully no _m1 nane-conflict...

	}

	return this;

},

setWorldQuaternion: function ( q ) {

	this.quaternion.copy( q );

	if ( this.parent ) {

		this.quaternion.premultiply( this.parent.getWorldQuaternion( _q1 ).inverse() );

	}

	return this;

},
```
I'm not sure, however, a `.setWorldScale( scale )` method makes sense.

**Comment by donmccurdy** [comment]
I don't know if I can speak for the people who have upvoted this issue, but in my case I am interested in converting a quaternion in local space to a quaternion in world space (or vice versa). I don't necessarily want to modify the object whose local space I'm using, so setters aren't what I'd had in mind.

Maybe I should have suggested methods on `SceneUtils`, rather than adding to the Object3D instance methods...

**Comment by WestLangley** [comment]
Oh, that should be easy. In fact I prefer it.
```
quaternion.localToWorld( object1 ).worldToLocal( object2 );

vector.localToWorld( object1 ).worldToLocal( object2 );
```
Is that the API you are looking for?

**Comment by donmccurdy** [comment]
I like that! We probably can't import Object3D in the Vector.js or Quaternion.js files, without creating a circular dependency, but it doesn't look like that would be necessary...

**Comment by WestLangley** [comment]
Good. I'll take care of it. :-)

I think `vector.localToWorld( object )` is how `object.localToWorld( vector )` should have been implemented in the first place.

**Comment by nyditot** [comment]
For me, `object.localToWorld( vector )` seems more appropriate with regards to encapsulation because it's the object that is maintaining its internal coordinate system and hence it should be the object's responsibility to transform coordinates. Putting the capability in the vector's domain means that it will require access to the object's internal coordinate mechanisms. Having said that, the required mechanisms are already public so I can see where having both `vector.localToWorld( object )` and `object.localToWorld( vector )` might be useful.

I would also like to see overloaded methods for Object3D's `localToWorld `and worldToLocal that accept position, quaternion or scale and returns the appropriate transformation.

**Comment by enderh3art** [comment]
Did we end up implementing a solution for this? Would love to understand how to do worldToLocal for rotations and scale

**Comment by WestLangley** [comment]
@enderh3art See the proposed `Quaternion` methods in #20243.
```js

localToWorld( object ) {

	return this.premultiply( object.getWorldQuaternion( _q ) );

}

worldToLocal( object ) {

	return this.premultiply( object.getWorldQuaternion( _q ).inverse() );

}
```
