### ISSUE TITLE
The addition of panning modes to OrbitControls has made it harder to convert to a module

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#13709]
Since [panning modes](https://github.com/mrdoob/three.js/blob/764875d4c97c230c990f07a63c58a222cdb3d566/examples/js/controls/OrbitControls.js#L1066-L1067) were added to OrbitControls it's become more complex to use it as a module. The problem is that the properties are added to the THREE global within the OrbitControls script:

```js
THREE.ScreenSpacePanning = 0;
THREE.HorizontalPanning = 1;
```

When using it as module, it's necessary to import `THREE`: 

```import * as THREE from 'three'```

to the `OrbitControl` module, and make a few minor changes to export `OrbitControls` as a function. 

However, assigning properties to the `THREE` object is not possible, it now throws the error:

```
error: Error: Illegal reassignment to import 'THREE' with OrbitControls.module.js
```

So I now have to make extra changes to the file, assigning the panning modes to `OrbitControls` instead of `THREE`. 

So we'll need to do either:

* move the panning modes to `src/contants.js`
* make the panning modes properties of `OrbitControls` instead of `THREE`

**Comment by WestLangley** [comment]
Well, this gives us the opportunity to do what I think is better, anyway:

1. remove `.panningMode`
2. make the new "horizontal panning" the default behavior, and
3. add a new property `.useLegacyPanningMode`, which is `false` by default.

This gets rid of the (horrible) `HorizontalPanning` nomenclature.

I can make that change if there is agreement.

**Comment by Mugen87** [comment]
@WestLangley Sounds good!

**Comment by looeee** [comment]
Likewise, sounds good to me 🙂

**Comment by WestLangley** [comment]
Will do. Waiting on #13706...
