### ISSUE TITLE
Rendering a geometry without a position attribute broken when migrating from r89 to r91

### ISSUE THREAD

**Issue by sam6321** [mrdoob/three.js#13719]
After migrating from r89 to r91, I've started getting an error while rendering instanced buffer geometry that does not have a position attribute.
My specific use case involves setting up an instanced buffer geometry with a few instanced buffer attributes in a way similar to the following:

```javascript
let geometry = new THREE.InstancedBufferGeometry();
geometry.addAttribute('instanced1', new THREE.InstancedBufferAttribute(new Float32Array(data1), 3));
geometry.addAttribute('instanced2', new THREE.InstancedBufferAttribute(new Float32Array(data2), 3));

let mesh = new THREE.Mesh(geometry, material);
scene.add(mesh);

// My own asyncronous loader is called to load in the position attribute from a model file
// A few rendering cycles occur in the meantime...

geometry.addAttribute('position', new THREE.BufferAttribute(new Float32Array(modelData), 3));
```

Essentially, I set up my instanced attributes first, then call an asynchronous loader to load in the model data that I want to render.

In r89 I had no issues doing this, but in r91 (and r90) I now get an error in [WebGLBufferRenderer](https://github.com/mrdoob/three.js/blob/r91/src/renderers/webgl/WebGLBufferRenderer.js) on line 36 in the time after creating the mesh, but before loading in the position attribute. 
```javascript
var position = geometry.attributes.position;

if ( position.isInterleavedBufferAttribute ) { // This line

	count = position.data.count;

	extension.drawArraysInstancedANGLE( mode, 0, count, geometry.maxInstancedCount );

} else {

	extension.drawArraysInstancedANGLE( mode, start, count, geometry.maxInstancedCount );

}
```
Obviously this line is going to fail, because my instanced buffer geometry doesn't have a position attribute yet.

After digging through the [WebGLRenderer](https://github.com/mrdoob/three.js/blob/r91/src/renderers/WebGLRenderer.js) code a little, I've found that it was actually this change in `renderBufferDirect` that's causing this issue:
```javascript

var dataCount = Infinity; // This was 0 in r89, but was changed to Infinity in r90 and r91

if ( index !== null ) {

	dataCount = index.count;

} else if ( position !== undefined ) {

	dataCount = position.count;

}

var rangeStart = geometry.drawRange.start * rangeFactor;
var rangeCount = geometry.drawRange.count * rangeFactor;

var groupStart = group !== null ? group.start * rangeFactor : 0;
var groupCount = group !== null ? group.count * rangeFactor : Infinity;

var drawStart = Math.max( rangeStart, groupStart );
var drawEnd = Math.min( dataCount, rangeStart + rangeCount, groupStart + groupCount ) - 1;

var drawCount = Math.max( 0, drawEnd - drawStart + 1 );

if ( drawCount === 0 ) return;
```
This was causing an early out in r89, because dataCount was set to 0 and there was no position attribute. After being changed to Infinity, `renderBufferDirect` no longer early outs here and attempts to render the instanced buffer geometry despite it not having a position attribute.

Would it be desirable to explicitly early out inside `renderBufferDirect` when attempting to render a geometry that does not contain a position attribute?
As a temporary fix, I've been setting the draw range on my geometry to (0, 0) then to (0, Infinity) once the model data has loaded, but this doesn't quite seem correct.
##### Three.js version
- [x] dev
- [x] r91
- [x] r90

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
> This was causing an early out in r89, because dataCount was set to 0 and there was no position attribute. 

#13128 changed this behavior in order to fix another problem.

Why don't use setup your instanced attributes when your loader has loaded the position attribute?

**Comment by Makio64** [comment]
I hit this problem as well, its counter intuitive. 

If my geometry position is setup in the vertexshader with radius and thetaAngle I dont want to push another vec3 informations to the gpu..

**Comment by Mugen87** [comment]
I hope the PR solves the problem.
