### ISSUE TITLE
ColladaLoader: add support for polylist with more than 4 vertices

### ISSUE THREAD

**Issue by l-xiong** [mrdoob/three.js#13727]
Please expand the ColladaLoader to support polylist of more than 4 vertices.

Here is a section of the DAE that the loader can't parse correctly.

`<polylist count="18" material="Material2">
                    <input offset="0" semantic="VERTEX" source="#ID23"/>
                    <input offset="1" semantic="TEXCOORD" source="#ID24"/>
                    <vcount>5 5 8 8 4 4 4 4 5 5 5 5 5 5 4 4 4 4</vcount>
                    <p>0 0 1 1 2 2 3 3 4 4 5 4 6 3 7 2 8 1 9 0 10 5 11 6 12 7 13 8 14 9 15 10 16 11 17 12 18 12 19 11 20 10 21 9 22 8 23 7 24 6 25 5 26 13 27 14 28 15 29 16 30 16 31 15 32 14 33 13 34 17 35 18 36 19 37 20 38 20 39 19 40 18 41 17 42 21 43 22 44 23 45 24 46 25 47 25 48 24 49 23 50 22 51 21 52 26 53 27 54 28 55 29 56 30 57 30 58 29 59 28 60 27 61 26 62 31 63 32 64 33 65 34 66 35 67 35 68 34 69 33 70 32 71 31 72 36 73 37 74 38 75 39 76 39 77 38 78 37 79 36 80 40 81 41 82 42 83 43 84 43 85 42 86 41 87 40</p>
                </polylist>`
##### Three.js version

- [ ] Dev
- [x] r91
- [ ] ...

**Comment by Mugen87** [comment]
Please share your complete `DAE` file in this thread. 

As a workaround, try to convert your model to `glTF` via: https://github.com/KhronosGroup/COLLADA2GLTF

You can load the file with [GLTFLoader](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js).

**Comment by l-xiong** [comment]
[DC2430.txt](https://github.com/mrdoob/three.js/files/1861082/DC2430.txt)

Unfortunately, I have to stick with DAE files for now.  I reverted to the old loader for the time being.

**Comment by donmccurdy** [comment]
@l-xiong Understood. If you've tried COLLADA2GLTF and had any particular issues please do report them as bugs. 🙂
