### ISSUE TITLE
Add faces to several separate lines

### ISSUE THREAD

**Issue by soloprimos** [mrdoob/three.js#13721]
I have created a scene with several lines of geometries, but all the lines are separated as daughters of the scene, I would like to know how I could add faces to this scene, I hope it is possible, I am developing my degree project: D
![issue](https://user-images.githubusercontent.com/13036774/38069559-fcf51f1a-32e4-11e8-990e-420d46cfd49d.png)

**Comment by looeee** [comment]
Please use the [forum](https://discourse.threejs.org/) for help questions.

**Comment by soloprimos** [comment]
Ok, Thanks and sorry.
