### ISSUE TITLE
Textures on each box/cube face

### ISSUE THREAD

**Issue by AdsonCicilioti** [mrdoob/three.js#13740]
##### Simple question: 

With the end of MeshFaceMaterials and MultiMaterials, I would like someone to show me a simlpes example of how to put images as textures on each face of a Cube or Box?

I'm starting with Three.js and trying to follow the documentation, but this question really did come up.

What I have [is here](https://jsfiddle.net/adsoncicilioti/yx4t311L/)

##### Three.js version

- [x] r91
- [ ] Dev
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
- [x] All OK!

**Comment by WestLangley** [comment]
Sorry, this is not a help site. Please use the [forum](https://discourse.threejs.org).
