### ISSUE TITLE
Points don't castShadow

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#13749]
##### Points don't castShadow

Points don't castShadow in the latests version of three.js, I try with customDepthMaterial and classic PointsMaterial, but it didnt work, not sure since which version its broken.

[JSFiddle] http://jsfiddle.net/ptgwhemb/67/

##### Three.js version
- [x] Dev
- [x] r91

##### Browser

- [x] All of them
- [x] Chrome
- [x] Firefox
- [x] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
None

**Comment by WestLangley** [comment]
Works fine: http://jsfiddle.net/ptgwhemb/70/

Shadows for points are sensitive to the shadow map size, since they are sized in pixels.

```javascript
spotLight.shadow.mapSize.width = 512; // changed
spotLight.shadow.mapSize.height = 512; // changed
```
Also with the material you selected, it was harder to see.

```javascript
THREE.MeshStandardMaterial( { metalness: 0, roughness: 0 } ); // changed
```

**Comment by Makio64** [comment]
Thanks @WestLangley for the quick answer but I still have no shadows : 

![image](https://user-images.githubusercontent.com/213351/38220610-61681304-36db-11e8-8c01-b36b6b38d811.png)

I tried with 2048x2048 / 256x256 as well, still 0 shadow & no shader error popping.

My config : 
- Windows 10
- Chrome / Firefox latest
- Nvidia gtx1070

**Comment by WestLangley** [comment]
So this fiddle ( http://jsfiddle.net/ptgwhemb/70/ ) does not render `Point` shadows on your platform?

![screen shot 2018-04-02 at 7 24 32 pm](https://user-images.githubusercontent.com/1000017/38221043-8da2757a-36ab-11e8-9dbc-12db2b2ff296.png)

**Comment by Makio64** [comment]
Yes, I double checked and the screenshot is from your fiddle (70)

**Comment by antoineabbou** [comment]
Don't have shadow either : 

<img width="623" alt="capture d ecran 2018-04-03 a 01 57 52" src="https://user-images.githubusercontent.com/22654097/38222112-4ff2b6b2-36e3-11e8-81e7-973ef9a3f1df.png">


**My config :**

- Macbook pro 13' (High Sierra) 
- Chrome / Firefox latest
- Intel Iris Plus Graphics 650

**Comment by floz** [comment]
For information both versions work for me!

@Makio64 version:
![screen shot 2018-04-03 at 9 27 53 am](https://user-images.githubusercontent.com/1920071/38222705-58258394-3721-11e8-9cbe-4fde5fcc333e.png)

@WestLangley version:
![screen shot 2018-04-03 at 9 27 58 am](https://user-images.githubusercontent.com/1920071/38222707-5ce96a3a-3721-11e8-85e5-eef254d55039.png)

My config:
![screen shot 2018-04-03 at 9 18 40 am](https://user-images.githubusercontent.com/1920071/38222678-2f51f722-3721-11e8-86c3-08ad7f7272aa.png)

I was talking with @Makio64 who was suggesting that maybe an extension changed?

**Comment by floz** [comment]
Another weird behavior: 
Changing the sizse of the particles have no effect on the size of the particles in the shadow http://jsfiddle.net/ptgwhemb/112/

**Comment by Makio64** [comment]
I try with all the version on jsfiddle until threejs r85 and I can't see the shadow on any of them. Then the shadow disapear on both object from r84.

On my codevember 2016, I was using the r82 + customDepthMaterial and I can still see the shadow : 
http://makiopolis.com/codevember/05

**particleDepth.fs **
 ```
#define DEPTH_PACKING 0
#define USE_SHADOWMAP 1

#include <common>
#include <packing>
#include <logdepthbuf_pars_fragment>

void main() {
	gl_FragColor = vec4( 1. );
	#include <logdepthbuf_fragment>
	#include <encodings_fragment>
	gl_FragColor = packDepthToRGBA( gl_FragCoord.z );
}

```

**particleDepth.vs **
 ```
#define USE_SHADOWMAP 1

#include <common>
#include <logdepthbuf_pars_vertex>

uniform sampler2D t_pos;
uniform lowp float size;

void main() {
	gl_PointSize = 1.;
	vec4 worldPosition =  modelViewMatrix * vec4( position, 1.0 );
	#include <logdepthbuf_vertex>
	gl_Position = projectionMatrix *  worldPosition;
}
```

+ this setup
```
		renderer.shadowMap.type = THREE.PCFSoftShadowMap
		renderer.gammaInput = false
		renderer.gammaOutput = false
		renderer.shadowMap.renderReverseSided = false
		renderer.shadowMap.renderSingleSided = false
```

**Comment by RemusMar** [comment]
> Works fine: http://jsfiddle.net/ptgwhemb/70/

It doesn't work on Firefox 52.7.3 on Windows

> Shadows for points are sensitive to the shadow map size, since points are sized in pixels.

Logically speaking, a point does not cast any shadow

**Comment by WestLangley** [comment]
>Logically speaking, a point does not cast any shadow

No trolling, please.

**Comment by RemusMar** [comment]
> No trolling, please.

I'm not trolling at all.
A point is not a 3D model and it's not a 1x1 sprite.
A point does not exist in a 3D world, so it doesn't cast any shadow.

cheers

**Comment by Mugen87** [comment]
Works fine on Ubuntu 16.04 and Chromium 65.0.3325.181/Firefox 59.0.2.

**Comment by Makio64** [comment]
Following a Twitter poll, the current version doesn't work on around 30% of machines.

The fix suggest by Edan Kwan works : 
http://jsfiddle.net/ptgwhemb/151/

Link to the twitter conversation : https://twitter.com/makio64/status/981138144438423552

**Comment by RemusMar** [comment]
> The fix suggest by Edan Kwan works :
> http://jsfiddle.net/ptgwhemb/151/

Indeed.
![points_and_shadows](https://user-images.githubusercontent.com/11772787/38253101-75ea59f8-375e-11e8-8591-f36ac663831a.jpg)
Presuming a point can cast shadows ... LOL
p.s.
Firefox ESR is very important becaus it proves the backwards compatibility.

**Comment by WestLangley** [comment]
Thing is, the rendered point shadows are still sensitive to the dimensions of the shadow map.

One option is to try to make this work automatically.

The other option is to require `customDepthMaterial`, and provide an example. That way, the user has more control.

**Comment by mrdoob** [comment]
I can reproduce (MacBook Pro, Intel Iris Graphics 550)
Investigating...

**Comment by Makio64** [comment]
Probably the default value of gl_Point on some graphic card have probably 0 by default and on other have 1, some mac and gtx1060/70/80

@WestLangley : Example with customDepthMaterial will be great, as its currently hard to create ShaderMaterial for particles and get the shadow work well, but necessary on many projects to improve the visual quality.

**Comment by mrdoob** [comment]
I guess #14086 fixes this... 😇

**Comment by WestLangley** [comment]
@mrdoob Not really.  #14086 removed non-functional code chunks related to points _receiving_ shadows.

For points to properly cast shadows, either a different -- or custom -- depth material is required. That is tricky because points are sized in pixels, making the automatic sizing of point shadows difficult.

I expect if points were sized in world units, instead, fixing this would be straightforward.
