### ISSUE TITLE
FBXLoader: Wrong rotation interpolation

### ISSUE THREAD

**Issue by nick-nikoliuk** [mrdoob/three.js#13756]
##### FBXLoader: Wrong rotation interpolation
Actual result:
Rotation interpolation doesn't work properly.
See [video](https://youtu.be/SZDGMohj7wE):.

Expected result:
Rotation animation work properly.

FBX example attached.
[video](https://youtu.be/SZDGMohj7wE):
[example.zip](https://github.com/mrdoob/three.js/files/1871163/example.zip)

##### Three.js version

- [ ] Dev
- [x] r91
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by nick-nikoliuk** [comment]
Any ideas, @looeee?

**Comment by nick-nikoliuk** [comment]
It seems THREE.Quaternion() can't contain information about angles more than 360 degree. But quaternions used in animation keys. So I suggest to use Euler as interpolation keys and than update quaternion.
@looeee @mrdoob

**Comment by Krulvis** [comment]
@nick-nikoliuk I've had the same problem trying to rotate a text around an axis, but it doesn't get automatically converted to quaternions and the exporter just generates quaternions that don't make sense to me, they produce something completely different.

**Comment by looeee** [comment]
Good to know, I must check that converter out. It will also work correctly in the FBXLoader once #13838 is merged.

**Comment by looeee** [comment]
Closing since #13838 was merged.
