### ISSUE TITLE
Raycasting of Sprites Does Not Account for Center and Scale

### ISSUE THREAD

**Issue by mrz5018** [mrdoob/three.js#13751]
Raycasting for sprites does not work in a lot of different circumstances.  When the center of the sprite is altered, the area that the raycaster checks moves with it.  So, the circle that is being checked (raycasting of a sprite just checks a disc around the center) is located around the new center.  This means that instead of the circle covering a large portion of the sprite it really only covers the one corner (while also covering a large area that is actually not inside of the sprite).  Please see my beautiful art below for reference:

-- Center at (0.5, 0.5)
<img width="343" alt="drawing" src="https://user-images.githubusercontent.com/3534492/38229182-8677652e-36d5-11e8-9d5f-bd70a37b3090.png">

-- Center at (0, 0)
<img width="535" alt="drawing 1" src="https://user-images.githubusercontent.com/3534492/38229183-8b8f996e-36d5-11e8-929d-ea31a20c627f.png">

I originally tried to fix it by doing some math in the raycast function (code below), but this math only works if the camera is not rotated.  Once the camera rotates obviously the sprite is no longer oriented solely in the XY plane.

```
// Raycast override function

function() {
      var intersectPoint = new THREE.Vector3();
      var worldPosition = new THREE.Vector3();
      var worldScale = new THREE.Vector3();

      return function raycast(raycaster, intersects) {
        worldPosition.setFromMatrixPosition(this.matrixWorld);
        worldScale.setFromMatrixScale(this.matrixWorld);

       worldPosition.x =
          (0.5 - this.center.x) * worldScale.x + worldPosition.x;
        worldPosition.y =
          (0.5 - this.center.y) * worldScale.y + worldPosition.y;
        raycaster.ray.closestPointToPoint(worldPosition, intersectPoint);

        if (Math.abs(worldPosition.x - intersectPoint.x) > worldScale.x / 2) {
          return;
        }
        if (Math.abs(worldPosition.y - intersectPoint.y) > worldScale.y / 2) {
          return;
        }

        var distance = raycaster.ray.origin.distanceTo(intersectPoint);

        if (distance < raycaster.near || distance > raycaster.far) return;

        intersects.push({
          distance: distance,
          point: intersectPoint.clone(),
          face: null,
          object: this,
        });
      };
    })();

```

I'm going to also throw something up on StackExchange to see if someone has a quick fix for me, but for the long term fix I figured that this deserved a bug report.  In general the center and scale values of a sprite need to be used to properly detect a raycast.

##### Three.js version

- [ ] Dev
- [x] r91
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Also, a non-rotated sprite always renders right-side-up even if the camera is tilted. That is, if the camera is upside-down, the rendered sprite will still appear right-side-up.

This behavior would need to be accommodated if raycasting against sprites is to be handled accurately.

If you are satisfied with an approximation, as we have been so far, then all that is required is to get the center of the sprite correct, and the scale close-to-correct. This is reasonable, because users will typically click near the center of the sprite.

**Comment by mrz5018** [comment]
Yeah, I think that an approximation is fine in general.  But I think that to solve the other issues, like raycasting not handling changes to the center, the solution will most likely just have to be exact.

At first I was hoping that I could just make some sort of bounding box that contains every possible orientation of the sprite.  Unfortunately that doesn't work, because the bounding box would have to be about 2x the size of the actual sprite.  So, that ends up being even worse than the disc approximation.

In my head, I feel like somehow the camera needs to passed into the raycaster.  That way the rotation of the camera could be used to determine the tilt of the sprite's plane.  Does that make sense?  I'm rusty on my linear algebra, and I can't really think through in my head how it would work, but I'm confident that knowing the rotation of the camera would give enough information to translate the original center to where it currently is.

If anyone has any input I'm happy to translate the math into the code.  I just can't put it all together...

**Comment by makc** [comment]
when ever I need something sprite-like and clickable, I just end up using a plane with .quaternion = camera.quaternion in .updateMatrixWorld or somewhere. this way you use same raycast code that you use for meshes.

**Comment by pailhead** [comment]
Agreed. It would probably require more optimization if it was on mouse move, but on mouse click you should be able to rotate the planes and cast against them. Drawing can be a completely different thing,  preferably instancing the same quads.

**Comment by mrz5018** [comment]
@makc You're 100% right, this is a much easier way to handle the situation.  I just do a `plane.quaternion.copy(camera.quaternion)` and that seems to do the trick.

I'll need to figure out a way to mimic the `sprite.center` functionality on a plane geometry, but this completely alleviates the raycasting issue.
