### ISSUE TITLE
PolyhedronGeometry: cols is not necessarily be power of two

### ISSUE THREAD

**Issue by migiyubi** [mrdoob/three.js#13758]
When `detail` is set, PolyhedronGeometry subdivides its faces by `Math.pow(2, detail).`
However, the current tessellation algorithm works with arbitrary natural numbers.

It must be better to subdivide by `detail` as is.

**Comment by Mugen87** [comment]
What are the benefits this change?

Besides, it would not be backwards compatible, right?

**Comment by WestLangley** [comment]
>What are the benefits this change? Finer control over the tessellation?

Yes. I think `detail` would behave more like `subdivisions` in `SubdivisionModifier`.

>Besides, it would not be backwards compatible, right?

It would not. `detail` of 0 would be invalid.

**Comment by migiyubi** [comment]
Exactly as @WestLangley mentioned.

Actually, I got a situation where generated mesh is too coarse with 8, but too fine with 16...

If the compatibility is the most important, we can do something like
`PolyhedronGeometry(vertices, indices, radius, detail); // -> exponent`
`PolyhedronGeometry(vertices, indices, radius, detail, true); // -> as is`

**Comment by WestLangley** [comment]
Maybe allow fractional values of `detail` like so:
```javascript
var cols = Math.round( Math.pow( 2, detail ) );
```

**Comment by migiyubi** [comment]
That sounds good.
It has less impact and also satisfies my desire by passing `Math.log(N)/Math.log(2)` or something.

**Comment by WestLangley** [comment]
I'm not really liking the idea of allowing fractional values of `detail`, though. Perhaps you can just hack your own fork of three.js...

The other solution is to set:
```javascript
var cols = detail;
```
and in the constructor,
```javascript
detail = detail || 1;
```
This would not be backward-compatible, however.

**Comment by Mugen87** [comment]
TBH, I don't vote for a change that breaks backward-compatibility.

**Comment by migiyubi** [comment]
Okay, maybe I should solve this in my own customization, leaving the origin as it is.
Thank you for your opinions.

**Comment by WestLangley** [comment]
OK. Closing.
