### ISSUE TITLE
Provide URDF loader

### ISSUE THREAD

**Issue by buddha314** [mrdoob/three.js#13768]
For doing simple simulations in Bullet with viz in ThreeJS, Collada is too complicated.  It would be very useful to load URDF files for objects if possible.

**Comment by mrdoob** [comment]
Do you have a link to the URDF spec?

**Comment by buddha314** [comment]
Ah, I should have included that, sorry: http://wiki.ros.org/urdf/XML  And the package level description as well: http://wiki.ros.org/urdf

**Comment by mrdoob** [comment]
Thanks! We'll also need sample models.

**Comment by buddha314** [comment]
I have been using [this robot](https://github.com/bulletphysics/bullet3/blob/master/data/r2d2.urdf) and [this duck](https://github.com/bulletphysics/bullet3/blob/master/data/duck_vhacd.urdf) to create a rather strange animation of R2D2 chasing a rubber duck into infinity.  Pretty fun!  Would like to do it in ThreeJS.

**Comment by mrdoob** [comment]
I wonder if @yomboprime would like to give it a try.
It would follow the `threejs_physics` he contributed.

**Comment by buddha314** [comment]
And there is a port of Bullet called [`ammo.js`](https://github.com/kripken/ammo.js/) I have been playing with. Happy to try the other physics lib.

**Comment by yomboprime** [comment]
I'd like, but I don't have time ATM for this project, sorry.

I would do a ```URDFParser``` and then implement a class for each physics engine. For example a ```AmmoURDFBuilder``` to start, and so on.

**Comment by gkjohnson** [comment]
Hey @buddha314!

I've been using URDF for visualization in THREE, as well, and have a repo with a URDF loader here:

https://github.com/gkjohnson/urdf-loaders/tree/master/javascript

It has primarily been tested with the features the robots I've worked with use (continuous, prismatic, revolute joints, mesh geometry) but I've been slowly adding more features into it. [Here's](https://gkjohnson.github.io/urdf-loaders/javascript/example/index.bundle.html) a demo page! Some of the less advertised features there are that you can drag and drop folders with URDF models to visualize them and drag the joints around.

![manipulation-animation](https://user-images.githubusercontent.com/734200/43433896-2bf9cd92-942e-11e8-9bcd-b144223ff4bf.gif)

My use case has primarily been visualization but I'd be happy to work with you to add other features you might need for physics simulation to round it out! A couple things I noticed when testing your models:
- The duck model uses OBJ models while the loader only supports STL and Collada files (as the spec states) out of the box. This can easily be overridden and I've been considering supporting more formats by default.
- A number of the URDFs in the repo you posted specify the XML version as `0.0`, which the browser's xml parser does not like. They seem to work just fine if you change it to `1.0`.

Hope it's helpful! Let me know if I can help!

**Comment by buddha314** [comment]
Oh, this is cool!  Just saw it and thanks!

**Comment by kavikode** [comment]
Excellent Work! I just wish IK was included in your example @gkjohnson I hope somebody can help me get IK integrated to the library of that URDF loader. Can anyone please help me ?

**Comment by Mugen87** [comment]
@kavikode Please post `URDFLoader` related question at https://github.com/gkjohnson/urdf-loaders.

**Comment by danilobassi8** [comment]
https://github.com/gkjohnson/urdf-loaders is great but wont work if we moved all the render process to a web worker because it uses DOMParser(). Is there any solution for that?
