### ISSUE TITLE
WebGL Shader error when loading PBR models in mobile firefox

### ISSUE THREAD

**Issue by soadzoor** [mrdoob/three.js#13765]
##### Description of the problem

Hi,

It seems, three.js uses a WebGL extension (GL_EXT_shader_texture_lod) without checking whether it's supported first. To reproduce the problem, do the following:

Open up this [link](https://threejs.org/examples/webgl_loader_gltf_extensions.html) in a mobile firefox browser:  (I have android, but I believe it might be the same for iOS as well).

If you switch to a PBR model, it won't appear in the scene. If you switch to another kind of model, it will appear just fine. Based on this, I believe, it has something to do with PBR.

I connected my phone to the firefox webIDE, and the console outputs the following message when the problem occurs:
![capture](https://user-images.githubusercontent.com/10392261/38298135-c9d3c282-37f6-11e8-83d3-c7c4d4d4653e.PNG)

##### Three.js version

- [ ] Dev
- [x] r91
- [x] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [x] iOS

**Comment by takahirox** [comment]
I think Three.js checks if browser supports EXT_shader_texture_lod extension. Could you go http://renderingpipeline.com/webgl-extension-viewer/ (or somewhere) to see if your browser actually supports the extension?

**Comment by RemusMar** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1447916

**Comment by soadzoor** [comment]
@takahirox Here's a screenshot of that viewer from my android-firefox browser. 

![screenshot_20180404-125040](https://user-images.githubusercontent.com/10392261/38303646-e975cb2a-3806-11e8-8553-b224041a3867.jpg)


@RemusMar How is this related? I don't think that for example BoomBox has video textures, or skinned meshes. Does it?

**Comment by takahirox** [comment]
I see "EXT_shader_texture_lod" in the list. So this would be FireFox issue by any chance?

**Comment by soadzoor** [comment]
Possibly. I'll try to make some research. Thanks!

**Comment by RemusMar** [comment]
> How is this related? I don't think that for example BoomBox has video textures, or skinned meshes. Does it?

It's a Firefox bug (shaders related).
On your Android phone use the Chrome browser and you won't notice any bug.
In other words, the issue is not reaqlted to Three.js

**Comment by RemusMar** [comment]
http://necromanthus.com/Test/html5/Lara_mirror.html 
Click on stage to switch between the Phong and the Standard shaders.
Chrome on Android: everything is ok
Firefox on Android: you cannot see the mesh

**Comment by soadzoor** [comment]
Right. I just thought that three.js doesn't check the extensions it uses. My bad.
