### ISSUE TITLE
Lightmap is rendered upside-down when using GLTFs

### ISSUE THREAD

**Issue by soadzoor** [mrdoob/three.js#13777]
##### Description of the problem

I work on a complex scene, and for some reason, the lightmaps were always glitchy, when I loaded it in three.js, in GLTF format. For debugging purposes, I prepared a very simple scene in blender, and I realized that the lightmaps are upside-down, when I load it in three.js, even when I use the texture coordinates as UV maps, like this:
```
node.material.lightMap = lightMap;

var uvs = node.geometry.attributes.uv.array;
node.geometry.addAttribute( 'uv2', new THREE.BufferAttribute( uvs, 2 ) );

node.material.needsUpdate = true;
```

When I export it as OBJ, it has no problems (the materials are black in obj, but that's not the problem, I know the reason for that one):
![lightmap_bug](https://user-images.githubusercontent.com/10392261/38359992-b0fbe0c2-38c9-11e8-90b7-966e8c955893.PNG)

Anyone can try using this [link](http://people.inf.elte.hu/soadzoor/lightmap_bug)

You'll need to drop this zip in the gltf version: 
[gltf.zip](https://github.com/mrdoob/three.js/files/1879497/gltf.zip)

First I thought the lightmap is rotated by 90 deg CW, but later I realized it is flipped (mirrored) vertically. To make it even stranger, the textures (maps) are rendered fine with the same UV sets.

Anyone has an idea why?

Also, here's the blender project, maybe it can help someone to discover the problem: 
[lightmaps.zip](https://github.com/mrdoob/three.js/files/1879502/lightmaps.zip)

##### Three.js version

- [ ] Dev
- [x] r91
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by soadzoor** [comment]
Oh, wow. Thanks. But it feels like a workaround this way. Will it be improved some day to do this automatically if it's a gltf object? Or it's not possible (not nice..?) to detect these kind of things?

**Comment by donmccurdy** [comment]
The loader cannot tell what you do with the model after loading, so hard to do this automatically or detect it. But I would not be surprised if the glTF format eventually supported lightmaps, in which case `flipY=false` would be automatic.

**Comment by soadzoor** [comment]
Yea, right. Thanks!
