### ISSUE TITLE
New CSS3D renderer

### ISSUE THREAD

**Issue by deadmanswitch** [mrdoob/three.js#13788]
Hi!

I am working on a new CSS3D renderer, which supports BufferGeometry. It can display any type of polygon, not just rectangular shapes. Multimaterials and texture mapping is also supported.

I added the CSS3DObject and CSS3DSprite classes to the project, so the original CSS3D examples will also work.

The examples can be found here: http://css3d.tk/

I would like to contribute it to the project. Should I replace the existing CSS3DRenderer then, or create a CSS3DRenderer2 class?

**Comment by Mugen87** [comment]
Instead of adding a new renderer or replacing the old one, i vote to add selected features to the existing `CSS3DRenderer`. For example it would be nice to add support for orthographic cameras if possible, see #11534.

**Comment by WestLangley** [comment]
>@WestLangley did this years ago already

https://rawgit.com/westlangley/three.js/dev-css/examples/css3d_morphtargets_horse.html

**Comment by Mugen87** [comment]
> Although it's obviously possible to hack around CSS3D to render 3D models, it remains a hack and it's not the right technology for it.

I agree with this. Users should focus on WebGL for real 3D rendering.
