### ISSUE TITLE
Make an official icon for three.js

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#13793]
Sourcetree on MacOS supports project icons (a file named icon.png in the root folder). 

<img width="576" alt="icons" src="https://user-images.githubusercontent.com/234804/38454031-91ff3ade-3a9a-11e8-8e35-42d90d1d8cfc.png">

Hoping github's app and website will do the same in the future. In any case it would be nice if three.js had an official icon saved in the root as icon.png. If MrDoob has a preference or maybe hold a contest or even just as a placeholder?

<img width="113" alt="three" src="https://user-images.githubusercontent.com/234804/38454097-6d04038a-3a9b-11e8-981a-9ae97ea9246a.png">

**Comment by looeee** [comment]
This seems like quite a specific use case for adding an extra file, unless lots of people are using Sourcetree or it has uses beyond just that app. 

In any case, there is an icon. @mrdoob created it when we set up the forum last year:

<img width="362" alt="020b4bf5260882fa7b29b4aba7c3ff2c8e46aad0" src="https://user-images.githubusercontent.com/5307958/38454395-eba34a8a-3a90-11e8-9c95-680a7aea037f.png">

**Comment by Usnul** [comment]
@looeee 
I like the fact that it's a *tri*angle, but it has 16 sub-triangles. We can make it 3 also, that would align better with the name.

**Comment by looeee** [comment]
> We can make it 3 also

What do you mean?

**Comment by yomotsu** [comment]
@Usnul Just FYI:
https://github.com/mrdoob/three.js/issues/2789#issuecomment-284244912

**Comment by Usnul** [comment]
@looeee @yomotsu 
I mean this:
![Triangle of three](https://i.stack.imgur.com/slHHe.jpg)

**Comment by looeee** [comment]
Actually I like that a lot. However, the very first result on Google for "triangle logo" is this:

![citgo](https://user-images.githubusercontent.com/5307958/38496394-92a6a542-3c27-11e8-9a71-fc82c2a358b8.jpg)

**Comment by Usnul** [comment]
@looeee 
sure, just change the colours a bit, add some rotation, maybe some skew :)

I don't think we should allow google to have exclusive rights on triangles, I want to keep using triangular polygons in my meshes!

**Comment by StanBoyet** [comment]
It's going to look a lot like ours if you tilt it a bit 😬
![logo-drawbotics-icon 3](https://user-images.githubusercontent.com/1906401/38992880-5e64cf26-43e2-11e8-9bef-348a35dafd06.png)

**Comment by looeee** [comment]
This one might be a little less copyright infringing
 
![logo_1](https://user-images.githubusercontent.com/5307958/38997690-43fbcb86-4418-11e8-8d14-9c0ae30a7378.png)

**Comment by saivan** [comment]
You could also make a three out three, three sided shapes 😆 

![image](https://user-images.githubusercontent.com/8543370/39170008-3f0916ba-47dd-11e8-8463-fafa7c3713f1.png)

**Comment by atul-mourya** [comment]
How about creating a poll? seems like we have a lot of choice.

**Comment by Fyrestar** [comment]
I don't know if there should be a color, i use this in white for a platform i'm setting up, in plain white for dark background.
![three](https://user-images.githubusercontent.com/28584767/50236288-4badea00-03ba-11e9-8c9b-9794c8e2d634.png)

**Comment by saurabhdaware** [comment]
How about simply turning javascript logo to 3d ? 
something like this
![threejs](https://user-images.githubusercontent.com/30949385/58746251-e0446a00-8479-11e9-9396-4829edcf6afa.png)

Ignore the shadows and box corners I know they are not perfect. I just wanted to show what I have in my mind.. if you guys like it I will fix those things create the logo properly

**Comment by greggman** [comment]
It already has a logo 😝

![ScreenFlow](https://user-images.githubusercontent.com/234804/58754752-61e7d680-8512-11e9-86c3-1036ad35cb58.gif)

**Comment by mrdoob** [comment]
Done! https://github.com/mrdoob/three.js/commit/c69db34ef86ac3d708ea939f1f41591373f61b37
