### ISSUE TITLE
matrix.decompose fills quaternion with NaN-s

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#13809]
So, there is this matrix with all but three elements = 0:
![crap1](https://user-images.githubusercontent.com/242577/38501181-aa433b0e-3c0c-11e8-91b5-fdbe19004c7d.png)
On any other day I'd say garbage in - garbage out, but today this happens to animation keyframe data while parsing dae file:
![crap](https://user-images.githubusercontent.com/242577/38501268-d782fd02-3c0c-11e8-835d-a3599fc4a2fc.png)
which ultimately crashes the whole loader business:
![crap2](https://user-images.githubusercontent.com/242577/38501405-38953434-3c0d-11e8-902d-d66d28373349.png)
Can we maybe have some good values hardcoded for things like this?

**Comment by makc** [comment]
having if (isNaN (quaternion.x)) { quaternion = new THREE.Quaternion(); } after decompose() gets me past keyframe errors, but undefined data is something else....

**Comment by Mugen87** [comment]
> which ultimately crashes the whole loader business:

As far as i can see, the loader does not crash. It parses the entire file and the animation plays even with these wrong keyframes.

**Comment by Mugen87** [comment]
Sry, i forgot to mention, that i've tested this bug after #13817. Try the changes from the PR and you will  see what I mean.

**Comment by Mugen87** [comment]
Closing. We don't apply a fix here since the loader does not sanitize input data.
