### ISSUE TITLE
GLTFExporter: Create round-trip import/export example

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#13805]
The current GLTFExporter example is essentially a set of unit tests, which I think we could move to GLTFExporter.tests.js. Instead, and inspired by @looeee's [converter here](https://blackthread.io/gltf-converter/), I think it would be great to have a simple example showing a default model "before" and "after", and let the user upload a new file to replace it. Probably only support uploading one or two formats (just GLB?) to keep the example simple. This would also help to test round-trip exporting tricky examples like NormalTangentMirrorTest.

Planning to give this a try if it sounds OK..

/cc @fernandojsg @takahirox

**Comment by takahirox** [comment]
What's the purpose of showing "before" and "after" to users? To show the limitation of glTF spec and exporter?

**Comment by donmccurdy** [comment]
> We might as well make it be actually useful though, what about FBX or Collada to glb?

Yeah, TBD.. I think it's a tricky line between a good example and something that will have too many moving parts.

> What's the purpose of showing "before" and "after" to users? To show the limitation of glTF spec and exporter?

Selfishly I'd like to be able to test quickly that any glTF sample can be both imported and exported correctly. Testing the exporter and importer more than the spec. If we also allow import of other formats then yes it would start to show differences in the spec. Not sure if that's something we want or no.

Maybe it's still a "test" more than an example, but I think it's one that others may find interesting.
