### ISSUE TITLE
Inconsistencies in curve arguments for the Font loader

### ISSUE THREAD

**Issue by mysteryDate** [mrdoob/three.js#13812]
According to the SVG specification, the order of arguments to a "quadratic bezier curve to command" is [`(x1, y1, x, y)`](https://www.w3.org/TR/SVG/paths.html#PathDataQuadraticBezierCommands)

But [Font.js](https://github.com/mrdoob/three.js/blob/dev/src/extras/core/Font.js#L114) uses the implied order `(x, y, x1, y1)`

What's extra crazy is that [Path](https://github.com/mrdoob/three.js/blob/dev/src/extras/core/Path.js#L61) uses the SVG standard order. 

"Cubic bezier curve to" suffers from this exact problem. `(x, y, x1, y1, x2, y2)` instead of `(x1, y1, x2, y2, x, y)`

Is there a reason for this besides backwards compatibility? Is there _any_ chance we could make this the standard for future versions?

Also, [implicit move to](https://www.w3.org/TR/SVG/paths.html#PathDataMovetoCommands) is not supported, but we could add that without breaking anything (I think).

**Comment by Mugen87** [comment]
> But Font.js uses the implied order (x, y, x1, y1)

I don't think that's correct. It applies the values in the right order to `path.quadraticCurveTo()`. First the control point, then the end point. `Font.createPath()` just reads the value form the `outline` array in a different order since it's defined like that in the respective font JSON file.

**Comment by mysteryDate** [comment]
Yes, but why is it defined like that in the respective font JSON file?

**Comment by Mugen87** [comment]
I don't know that, sry. Maybe @gero3 knows the answer 😉
