### ISSUE TITLE
ColladaLoader: getBuild does not check for data == null

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#13810]
I have this situation here:
![crap](https://user-images.githubusercontent.com/242577/38502235-2bc020a0-3c0f-11e8-9ae0-f5e14503d5ee.png)
this gets no image passed to getBuild which then crashes.

**Comment by Mugen87** [comment]
Please provide the `dae` file and textures for debugging.

**Comment by makc** [comment]
adding if(!data)return; gets me loading result at least, not sure how valid

**Comment by makc** [comment]
@Mugen87 I dont have textures, just dae
[test_v56.zip](https://github.com/mrdoob/three.js/files/1890203/test_v56.zip)

**Comment by makc** [comment]
@Mugen87 you will also need #13809 fixed to load this dae

**Comment by Mugen87** [comment]
The problem is that the `dae` file refers to an undefined texture. I guess we can change `getImage()` so it's similar to `getCamera()` and `getLight()` and thus more robust.
