### ISSUE TITLE
Transform Three to monorepo with multiple npm packages

### ISSUE THREAD

**Issue by Itee** [mrdoob/three.js#13829]
From #9562 

The purpose: 

transform Three to monorepository with multiple npm packages.

Why:

@sompylasar
> The monorepo concept is where multiple independent packages that are published to npm separately but maintained together in a single repository. Almost like three.js repo is organized now, and almost like you described in the organization structure you posted, but all in one repo.

> This structure helps maintainers to make well-integrated changes across multiple packages and release versions of them that are compatible with each other: the goals the maintainers are strive for throughout this issue thread.

> Having multiple repositories puts more maintenance and process work on all the developers, having to have duplicate configurations, workflow scripts, documentation, etc.

How:

With help of some script like @donmccurdy did [here](https://github.com/donmccurdy/aframe-extras/blob/master/scripts/publish.js).

**Comment by cecilemuller** [comment]
The scope `three` used to be available back in 2016 but not anymore.
However, both user and organizations `threejs` appear still available:
https://www.npmjs.com/org/threejs
https://www.npmjs.com/~threejs

It would be useful if @mrdoob registered the organization account, then the packages could be grouped together under the threejs namespace.

**Comment by donmccurdy** [comment]
If we're confident we will use the npm namespace, we should attempt [name dispute resolution](https://www.npmjs.com/policies/disputes) on the `@three/*` namespace first I think. Per NPM policy, "Don't squat on package names, user names or organization names". Names like `@three/gltfloader` and `@three/postprocessing` would be ideal. But we shouldn't reach out to NPM without being sure we'll use the name officially.

**Comment by Itee** [comment]
> The scope three used to be available back in 2016 but not anymore.
However, both user and organizations threejs appear still available

Personally, i prefer to use `@three` than `@threejs` for the namespace. But maybe i miss something about (available back in 2016) ?

> But we shouldn't reach out to NPM without being sure we'll use the name officially.

Totally agreed !

**Comment by Mugen87** [comment]
After the modularization this year I think the issue is obsolete.
