### ISSUE TITLE
envMap doesnt work correctly in r91

### ISSUE THREAD

**Issue by PerspectivesLab** [mrdoob/three.js#13823]
Hi there, envMap for MeshStandardMaterial renders differently in r91, it was rendering nice in r90, 
it seems caused by mipmap generation in [ this commit ](https://github.com/mrdoob/three.js/commit/51fe8f7acc4269fc9e98b012720644c5a28cf862)
the cube map is 1024x1024 and generate texture maxMipLevel: 10 in r91, as in r90 is 8 static.
here are the screenshots @takahirox :

r90 :
![envmap90](https://user-images.githubusercontent.com/25195799/38567727-c3f65a7e-3c9b-11e8-839b-beccbacd20c9.jpg)
 
r91:
![envmap91](https://user-images.githubusercontent.com/25195799/38567749-d0dc0bee-3c9b-11e8-96b8-420e8fa74ab7.jpg)

the envmap renders correctly by far in r90, is this a wanted behaviour? thx

- [ ] Dev
- [ X] r91
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by richardmonette** [comment]
@PerspectivesLab 's which loader are you using to load the envmap (cubemap)?

**Comment by PerspectivesLab** [comment]
i use the cubemap loader, and assign material.envMap  @richardmonette

**Comment by takahirox** [comment]
Could you make a live example for the test?

**Comment by mrdoob** [comment]
This may be unrelated, but I found this code today:

```js
float tex_mip_level(highp vec2 coord, highp vec2 tex_size) {
   highp vec2 coord_scaled = coord * tex_size;

   highp vec2 dx_scaled = dFdx(coord_scaled);
   highp vec2 dy_scaled = dFdy(coord_scaled);

   highp vec2 dtex = dx_scaled*dx_scaled + dy_scaled*dy_scaled;
   highp float min_delta = max(dtex.x,dtex.y);
   float miplevel = max(0.5 * log2(min_delta), 0.0);

   return miplevel;
}
```

**Comment by Mugen87** [comment]
Is this issue still relevant? AFAICS, #13501 replaced a fixed value of 8 with the real real maximum mip level which was a correct change. Even if the visuals have changed with `r91`, isn't the render process more correct now?

Since a live example was never provided and no other users complained about that change it's probably better to close the issue.

**Comment by mrdoob** [comment]
I don't think it is still relevant.
