### ISSUE TITLE
FBX animations with bones and positions messed up with FBXLoader R89 and later

### ISSUE THREAD

**Issue by jsalli** [mrdoob/three.js#13821]
##### Description of the problem
Hi,
We use a FBX-file with animations and we added now couple of animations for cables which use bones. The animations with bones are messed up and the positions of the cables are also wrong when loading the FBX-file with [FBXLoader.js](https://github.com/mrdoob/three.js/blob/r91/examples/js/loaders/FBXLoader.js) loader from Three.js release 89 and later. The FBXLoader from Three.js release 88 works perfectly. The Three.js release itself doesn't seem to have any change to the problem, only the FBXLoader makes this.

When using FBXLoader version R91 and the items are placed to wrong positions frustum culling seems to hide the cables based on their correct positions. The cables disappear even though they are in the view when you have the camera in certain angle/position.

Here is the 3D model with animation and two scenes, one with the r88 FBXLoader and one with r91 FBXLoader. You can see the behaviour [in this repo](https://github.com/jsalli/threejs-animation-bug).

The 3D model is modeled with Blender then exported as an FBX to 3DS Max 2017. In 3DS Max we added bones, made the skinning and animations.

Can you help us to solve this? The r91 version of FBXLoader helps us with other things and fixes some bugs in the r88 that we had.

##### Three.js version

- [ ] Dev
- [x] r89 and later
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
I'll take a look - the model does seem to be loading correctly in some other places such as Sketchfab, and displays correctly but without animation in Autodesk FBX Review. 

However loading it into 3DS Max there are warnings about an incomplete pose node, and exporting it back to FBX there are lots of warnings about gimbal lock on the bones. You could look into fixing those warnings and see if it resolves the issue.

**Comment by jsalli** [comment]
My colleague worked a bit more on the model and got it working with the r91 version of the FBXLoader. My [repo](https://github.com/jsalli/threejs-animation-bug) has a new version of the model named "working_model_of_cabel_pipes.FBX" and a new html file "workingFBXloader.html" to show it. 

In Blender he applied the location, rotation and scale of the model before exporting it to an FBX. Then in 3DS Max he didn't assign a parent helper (an empty object as parent) to meshes that had bones. Now the model's position and animations show correctly.

Any idea what causes this?

**Comment by looeee** [comment]
Not really 😅  

The conversion of bone transforms from FBX to three.js is very complex. Unless there are lots of people having problems I'd rather not try and support all the edge cases like this. 

For now, just make sure that all transforms are applied to bones and objects before exporting. In 3DS max this means resetting transforms and centering pivot points to objects. Also make sure that there are no warnings when importing and exporting your FBX to 3DS Max.

**Comment by donmccurdy** [comment]
For what it's worth, using [FBX2GLTF](https://github.com/facebookincubator/FBX2glTF) on either FBX model in the repo gives a working glTF animation for me.

**Comment by jsalli** [comment]
We'll apply all the transforms in the future to the models. And thanks @donmccurdy for the info. It might be a good idea for us to move to using glTF at some point. I've heard that it should be a better format for the web use for 3D models.

Should I close this issue?

**Comment by mrdoob** [comment]
I guess we can close it for the time being...

**Comment by looeee** [comment]
Yeah, let's close it for now. If other people report problems we can reconsider it.
