### ISSUE TITLE
Raycaster could not select FBX model

### ISSUE THREAD

**Issue by zhengoogle** [mrdoob/three.js#13833]
THREE.Raycaster could not select FBX model.
Is there any way to implement click events for FBX models.

**Comment by WestLangley** [comment]
Please use `http://discourse.threejs.org` for help.

**Comment by zhengoogle** [comment]
i find the solution
https://discourse.threejs.org/t/raycaster-only-working-correctly-when-adding-boxhelper-to-the-scene/2250
