### ISSUE TITLE
Error material with fog

### ISSUE THREAD

**Issue by osov** [mrdoob/three.js#13849]
Good afternoon. I write using an interpreter, I want to share the error found (and not one).
When using fog, you can observe an intimate bug.
If you create a minimal scene where there will be a cube, then reproduce the problem like this:
1) look at the cube, turn on the fog.
2) we set aside the camera so that the cube is not drawn.
3) turn off the fog
4) turn on the fog
5) view camera to the cube
6) and starts a constant update of the material (infinitely long until the object is visible or until we turn off the fog)

the kernel error is:
method: **setProgram**
line:
**else if (material.fog && materialProperties.fog! == fog) {
material.needsUpdate = true;
}**
The meaning of the error is that these 2 objects (materialProperties.fog and fog) are incorrectly compared.
Here is an example:
var a = new THREE.FogExp2 ();
var b = new THREE.FogExp2 ();
console.log (a !== b);
Will give out the false, although in fact the objects are identical.

**Comment by Mugen87** [comment]
> Will give out the false, although in fact the objects are identical.

What? Your create two different objects. Why should they be identical?

**Comment by WestLangley** [comment]
Can you please provide a live example?

https://jsfiddle.net/f2Lommf5/

**Comment by osov** [comment]
> What? Your create two different objects. Why should they be identical?
That's what I'm talking about. but in the engine check is done exactly as I described above.
there, if you look at it, the fog property of the scene is compared with the property of the fog material of the object.
It's not easy to create a demo, but I'll try.

**Comment by Mugen87** [comment]
I've create a simpler demo based on your code: https://jsfiddle.net/f2Lommf5/5383/

I'm not able to reproduce the problem.

**Comment by osov** [comment]
The problem is that you **will not see** in this case what happens inside the **ThreeJS engine**, namely - constant updating of the material, although in this case it is not as critical as in the case of an error in the operation of lighting (in another branch).

**Comment by Mugen87** [comment]
I'm not sure I can follow you. Do you say `three.js` does not update the materials correctly? 

> although in this case it is not as critical as in the case of an error in the operation of lighting (in another branch)

What do you mean with "other branch"?

**Comment by osov** [comment]
> Я не уверен, что смогу следовать за тобой. Вы говорите, three.jsчто не обновляете материалы правильно?

No, it updates everything correctly, it's just that no changes are made during the rendering, but the code inside the kernel causes an update request:
```
else if ( material.fog && materialProperties.fog !== fog ) {
	material.needsUpdate = true;
} 
```
but in fact there is no reason for constant updating. (absolutely every frame)
> Что вы имеете в виду с «другой веткой»?

https://github.com/mrdoob/three.js/issues/13851

**Comment by Mugen87** [comment]
I've debugged this and I can find an error. If a new fog setting is applied, `material.needsUpdate` is set to `true` in `setProgram()`. This will trigger the call of `initMaterial()`.

https://github.com/mrdoob/three.js/blob/fb46a77f8ef9f82992b5119c834ae72ad1f46578/src/renderers/WebGLRenderer.js#L1654-L1659

Inside this function, the new fog is applied to the `materialProperties`.

https://github.com/mrdoob/three.js/blob/fb46a77f8ef9f82992b5119c834ae72ad1f46578/src/renderers/WebGLRenderer.js#L1569

This ensure that no more material updates are triggered by the new fog. So, I still don't understand the reported problem.

@osov How should we change the code so it would be correct from your point of view?

**Comment by osov** [comment]
I also studied the function call list and where the processing takes place. By demo example, you do not understand what's going on?
Logically, there should be 1 call to the material after changing the fog settings, but in the example I showed that after the indicated manipulations, at each iteration of the loop, the material is updated infinitely.
If I have not explained clearly enough, I can try to record a video and show what happens.

**Comment by osov** [comment]
[Video_2018-04-13_205048.zip](https://github.com/mrdoob/three.js/files/1908059/Video_2018-04-13_205048.zip)
Recorded a video. maybe I just do not explain it clearly enough.

**Comment by Mugen87** [comment]
Indeed, the video was helpful. After some debugging, I can reproduce the problem in my test case.

https://jsfiddle.net/f2Lommf5/5410/

The good thing is the error seems not serious since the resulted overhead is minimal. The respective shader program is not recompiled. Maybe we could fix the problem by comparing the fogs via a hash?

**Comment by osov** [comment]
> Maybe we could fix the problem by comparing the fogs via a hash?

Yes. Perhaps you can solve the problem. The costs here are really small, but still unpleasant that there is such a bug.

Look at the very critical problem, here the expenses are simply catastrophic, FPS can fall almost to zero. https://github.com/mrdoob/three.js/issues/13851

**Comment by mrdoob** [comment]
My question is... Why are you creating a new `FogExp2` object instead of just changing its values?

**Comment by osov** [comment]
> Why are you creating a new FogExp2 object instead of just changing its values?

Because in my example it is shown that first I create a fog by specifying scene.fog = new THREE.FogExp2 (color, 0.02); then delete by making scene.fog = null ;, so the fog is gone and you have to create it again.

**Comment by looeee** [comment]
Why don't you do:

```
const fog = new THREE.FogExp2 (color, 0.02); 
scene.fog = fog;

...
scene.fog = null;
```

**Comment by WestLangley** [comment]
See the Materials section [here](https://threejs.org/docs/#manual/introduction/How-to-update-things).

Adding or removing fog requires the shader to be recompiled.

**Comment by osov** [comment]
> Adding or removing fog requires the shader to be recompiled.

I know it. the problem is there in another, on the video I showed.

**Comment by Mugen87** [comment]
The problem is that the code compare fog instances via `materialProperties.fog !== fog` to see if a material update is necessary. When @osov overwrites an existing fog with a new instance of the same type, the if statement evaluates to true in all upcoming frames. This happens because `materialProperties.fog` is never updated with the new fog instance since `initMaterial()` returns at this place:

https://github.com/mrdoob/three.js/blob/fb46a77f8ef9f82992b5119c834ae72ad1f46578/src/renderers/WebGLRenderer.js#L1480-L1481

**Comment by WestLangley** [comment]
>Why are you creating a new FogExp2 object instead of just changing its values?
>>Because in my example it is shown that first I create a fog by specifying scene.fog = new THREE.FogExp2 (color, 0.02); then delete by making scene.fog = null ;, so the fog is gone and you have to create it again.

As @mrdoob said, try this, instead:
```javascript
scene.fog.density = 0;
```

**Comment by Mugen87** [comment]
I'm not sure it's worth to add more complexity to the code in order to avoid a minimum amount of overhead. Besides, I've never seen that users change the fog like you did. So I don't think many users are involved in this issue.

**Comment by osov** [comment]
Ok.
