### ISSUE TITLE
glTF Loader doesn't support `texCoord` other than 0

### ISSUE THREAD

**Issue by MiiBond** [mrdoob/three.js#13844]
##### Description of the problem

@donmccurdy 
glTF 2.0 allows each texture referenced from a material (the textureInfo structure) to include a `texCoord` value. By default, this is 0 to use the first UV channel. It looks like three.js doesn't support anything other than 0 here. The value is just ignored so any models using the second UV channel don't render correctly.

Is this intensional?

##### Three.js version

- [x] Dev
- [ ] r91
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
See https://github.com/mrdoob/three.js/issues/12608 — `occlusionTexture` may use a second set of UVs (and a light map if you're adding one outside the glTF file) but otherwise all maps must use the first UV set in three.js.

**Comment by MiiBond** [comment]
Duplicate of #12608
