### ISSUE TITLE
Transparent image used as material rendering incorrectly. 

### ISSUE THREAD

**Issue by xbeat** [mrdoob/three.js#13863]
The mesh of the soccer golie net (see image below) uses a transparent material, the back part (the grey one) becomes incorrectly transparent only from the point of view of the camera (the background of the skybox is displayed) while the green part, which uses an image as background is rendered correctly.

![Screenshot](https://user-images.githubusercontent.com/20385856/38771252-1657f16a-4020-11e8-9d5a-1c5227580f8b.png)

Live Example
* https://xbe.at/AI-3DSoccer/start.html

Code
* https://github.com/xbeat/AI-3DSoccer

##### Three.js version

- [ ] Dev
- [x ] r91
- [ ] ...

##### Browser

- [x] Safari
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Please start with a help site: http://discourse.threejs.org.

**Comment by xbeat** [comment]
[SOLVED]
https://discourse.threejs.org/t/transparent-image-used-as-material-rendering-incorrectly-solved/2445
