### ISSUE TITLE
Black screen on canary in VR mode

### ISSUE THREAD

**Issue by mamun4122** [mrdoob/three.js#13865]
##### Description of the problem
I am getting black screen with canary & htc vive when i enter vr mode. The scene is working perfectly inside the htc vive but not mirroring anything in canary.   I am trying this example: https://threejs.org/examples/?q=vive#webvr_vive. I have also tried other webvr examples in https://threejs.org.

But if i try the https://webvr.info/samples/04b-simple-mirroring-2.html they are working fine.

I am not quite sure is it three.js bug or canary bug as the second example is working in canary. Both examples are working fine on Firefox.

##### Three.js version

- [ ] Dev
- [x] r91
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Canary
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
* HTC VIVE
* SteamVR Version 2018-04-10 (1523310137)
* NVIDIA GeForce GTX 970

**Comment by Mugen87** [comment]
Seems to be a browser related problem to me. Have you considered to report a bug here:

https://bugs.chromium.org/p/chromium/issues/list

**Comment by mamun4122** [comment]
I was not sure as the samples from  https://webvr.info/ was working perfectly. 

I have also reported the bug at chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=833256
