### ISSUE TITLE
Geometry > BufferGeometry does not group by materialIndex efficiently (reduce your draw calls by 1/4 with this one weird trick)

### ISSUE THREAD

**Issue by AndrewRayCode** [mrdoob/three.js#13869]
When a Geometry is converted to a BufferGeometry, the Faces of the Geometry are turned into BufferGeometry groups. Each group becomes a draw call in the end.

Faces **are not grouped** by `.materialIndex`, instead the faces are looped over and **a new group is created every time a different `materialIndex` is found:

https://github.com/mrdoob/three.js/blob/f10400e7124a081a24f244a9b4d6fddedf948a5e/src/core/DirectGeometry.js#L53-L71

By sorting my Geometry's faces (`geometry.faces = geometry.faces.sort((a,b) => a.materialIndex - b.materialIndex)`) I was able to reduce my BufferGeometry groups (and therefore draw calls) from 400 to 50.

You have to sort other things too to make sure all the data lines up.

There's at least two ways to address this, sort the faces and all other geometry arrays first before converting, or make the groups loop actually group by `materialIndex` instead of building a new one every time it finds a new one.

**Comment by WestLangley** [comment]
You can do this:
```javascript
geometry.sortFacesByMaterialIndex();
bufferGeometry = new THREE.BufferGeometry.from( geometry );
```

**Comment by AndrewRayCode** [comment]
why close? would you accept a PR with adding this as part of the conversion?

**Comment by mrdoob** [comment]
@AndrewRayCode Any chance you can use `BufferGeometry` directly?
