### ISSUE TITLE
MTLLoader:  MTLLoader problem

### ISSUE THREAD

**Issue by alwxkxk** [mrdoob/three.js#13881]
##### Description of the problem
I think this may be a bug:
When I used MTLLoader load 3ds Max .mtl file,it can't show anything.
At last ,I replaced MTLLoader.js which our company using (may be one or two years ago),it can show. 
I compare them and only a few code is different.
Thanks for any help. 

Note:MTLLoader2.js is our company using ,which is old.

![success](http://oswmftzo3.bkt.clouddn.com/2.png) 
https://jsfiddle.net/bdtm494j/2/

![fail](http://oswmftzo3.bkt.clouddn.com/1.png) 
https://jsfiddle.net/bdtm494j/1/

##### Three.js version

- [ ] Dev
- [x] r91
- [ ] ...

##### Browser

- [x] Chrome

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by kaisalmen** [comment]
I think this is fixed already for R92 by #13685

**Comment by alwxkxk** [comment]
Thanks
