### ISSUE TITLE
ColladaLoader: image urls aren't cleared of file:///... garbage

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#13890]
I am getting urls like http://127.0.0.1:8000/collada_model/file:///I:/DROP_BOX/Dropbox/PROJECTS/PROMOTION_PLY_projects/TABLE/Table_low_res_maya/sourceimages/_00_A1Shape.jpg by default.

Doing loader.setPath ('collada_model/') results into urls transformed to http://127.0.0.1:8000/collada_model/file:///I:/DROP_BOX/Dropbox/PROJECTS/PROMOTION_PLY_projects/TABLE/Table_low_res_maya/sourceimages/_00_A1Shape.jpg (no-op)

Doing
```javascript
				// create texture if image is avaiable

				if ( image !== undefined ) {
image = image.substr(image.lastIndexOf ('/') + 1); // <--- this
					var texture = textureLoader.load( image );
```
somewhere in ColladaLoader.js gets me urls without file:/// stuff, but I should not be doing this by hand, right?

**Comment by Mugen87** [comment]
I'm not sure what kind of final URL you expect. Can you please post your desired result?

Source URL: http://127.0.0.1:8000/collada_model/file:///I:/DROP_BOX/Dropbox/PROJECTS/PROMOTION_PLY_projects/TABLE/Table_low_res_maya/sourceimages/_00_A1Shape.jpg

Transformed URL (used for loading):

?

**Comment by makc** [comment]
well if I do loader.setPath, I expect everything on the left of _00_A1Shape.jpeg to be replaced by that path, at least. so http://127.0.0.1:8000/my_path/_00_A1Shape.jpeg

**Comment by makc** [comment]
if you argue that it should support subfolders inside that path, it's ok too. as long as I can get rid of protocol/host part of the urls that are in dae

**Comment by Mugen87** [comment]
I don't think this is how `.path` works, see
https://github.com/mrdoob/three.js/blob/e624c9b98829a86e9e17d0267e64d3e132677ada/src/loaders/ImageLoader.js#L23 

If a path is set, the given URL is expanded by this path. 

@donmccurdy Could @makc use [LoadingManager.setURLModifier](https://threejs.org/docs/index.html#api/loaders/managers/LoadingManager.setURLModifier) for its use case?

**Comment by makc** [comment]
hey  LoadingManager.setURLModifier  looks like it might work. I never knew it was there.  I guess someone added it before to fix exactly the situation like this, so closing )
