### ISSUE TITLE
Raycasting reports a  wrong faceIndex when picking a face of an unindexed BufferedGeometry

### ISSUE THREAD

**Issue by wlinna** [mrdoob/three.js#13894]
##### Description of the problem
Raycasting reports a wrong faceIndex when picking a face of an unindexed BufferedGeometry. Instead, it seems to be (the expected faceIndex) * 3.

I'm read through raycasting code, and I't seems to me that the problem is either in `checkBufferGeometryIntersection`  or here:

https://github.com/mrdoob/three.js/blob/master/src/objects/Mesh.js#L300

It says that `intersection.index` is a "triangle number in positions buffer semantics", but I fail how `a` is related to a "triangle number" here. Instead, it is merely an index in position buffer, which should be divided by 3 to get a triangle number.

This same `a` is also assigned to `faceIndex` in `checkBufferGeometryIntersection`

https://github.com/mrdoob/three.js/blob/master/src/objects/Mesh.js#L217

I searched Stackoverflow, and found this:

https://stackoverflow.com/questions/49045520/threejs-raycasting-reports-wrong-faceindex-when-picking-a-face

There's also a link to an example. 

##### Three.js version

- [x] Dev
- [ ] r91
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I think you're right. To ensure a consistent face index for both indexed and non-indexed geometry, we should change

https://github.com/mrdoob/three.js/blob/ba4489ded66212ac9e6d3017a6bb856023bd026f/src/objects/Mesh.js#L217

to 

```js
intersection.faceIndex = Math.floor( a / 3 );
```

and remove this [line](https://github.com/mrdoob/three.js/blob/dev/src/objects/Mesh.js#L279) because it's redundant.

@wlinna Can you please verify if this fix solves the issue?

**Comment by wlinna** [comment]
Yes. Those changes solve the issue.

Thanks for a quick answer

**Comment by Mugen87** [comment]
@wlinna Thanks for testing. I've realized that the change hast to be different. But the results should be the same.
