### ISSUE TITLE
Apparently wrong formula in Quaternion.setFromEuler method

### ISSUE THREAD

**Issue by czajkow** [mrdoob/three.js#13898]
## Description of the problem

I am checking out Quaternion.setFromEuler method in JSBin (jsbin.com), and in some cases it seems to ignore the order of applying rotations stored in the Euler object. Namely, for
`r = new THREE.Euler(Math.PI/2,0,0, "ZXY");`
`var a = new THREE.Quaternion;`
`a.setFromEuler(r);`,
we get the same quaternion as for the default order ("XYZ"), which should not be the case.
I compared the source code of Quaternion.setFromEuler (Dev, r92) with the code on [https://www.mathworks.com/matlabcentral/fileexchange/20696-function-to-convert-between-dcm--euler-angles--quaternions--and-euler-vectors?focused=3775364&tab=function](url) and it is different. (although the code on mathwork is referenced by Quaternion.js).
Below I give details of how I used three.js on JSBin:

#### The whole code (HTML) with the example:
`<!DOCTYPE html>`
`<html>`
`<head>`
`  <meta charset="utf-8">`
`  <meta name="viewport" content="width=device-width">`
`  <title>JS Bin</title>`
`  <pre id="log" style="font-size:2em;"></pre>`
`</head>`
`<body>`
`<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r82/three.min.js"></script>`
`<script>`
`  var log = document.getElementById("log");`
`  `
`  var r = new THREE.Euler(Math.PI/2,0,0), r1 = new THREE.Euler(Math.PI/2,0,0, "ZXY");`
`  var a = new THREE.Quaternion, a1 = new THREE.Quaternion;`
`  a.setFromEuler(r);`
`  a1.setFromEuler(r1);`
`  log.innerText = [a.x.toFixed(6), a.y.toFixed(6), a.z.toFixed(6), a.w.toFixed(6)] + "\n" +`
`    [a1.x.toFixed(6), a1.y.toFixed(6), a1.z.toFixed(6), a1.w.toFixed(6)];`
`</script>`
`</body>`
`</html>`

##### Three.js version

- [x] Dev
- [x] r82

##### Browser

- [x] Opera 51.0.2830.26

##### OS

- [x] Linux Ubuntu 16.04.3 LTS (x86_64; Unity)

##### Hardware Requirements (graphics card, VR Device, ...)
Graphics card: Intel® HD Graphics 530 (Skylake GT2)

**Comment by WestLangley** [comment]
You appear to have a misconception.
```javascript
new THREE.Euler( Math.PI / 2, 0, 0, 'ZXY' );
```
represents a rotation about the local z-axis by 0, followed by a rotation about the local x-axis by PI/2, followed by a rotation about the local y-axis by 0.

**Comment by czajkow** [comment]
That is true... I was assigning the x value to the first rotation instead of x-axis.
I apologize and I close the issue.
