### ISSUE TITLE
Links on three.js documentation website prevent ctrl/cmd+click or right click opening

### ISSUE THREAD

**Issue by mkarnicki** [mrdoob/three.js#13900]
Hi mrdoob/team,

Many times while going through the documentation I would like to ctrl/cmd+click on links pointing to particular class documentation to open in new tab. Because the <a> elements don't even contain href attribute, it simply doesn't work. Similarly, I can't right click and "Open in new tab".

I'm not providing an example because you can pick any documentation page and look for any documentation-linked class name to see the problem.

The documentation of three.js is pretty good and I'm thankful! Just wondering if it'd not be too much work to perhaps update the onclick listener / setFragmentUrl function to consider if a modifier is pressed. (I understand the lack of href is because you want the doc page to be like an SPA).

Thank you for your consideration and have a great day,
Michal

**Comment by Mugen87** [comment]
We should consider this issue as a bug, see https://github.com/mrdoob/three.js/issues/13951#issuecomment-385202371

**Comment by d07RiV** [comment]
Created pull request if you don't mind.

#14198

**Comment by will-ca** [comment]
Aside from CTRL+Click being broken, this also messes with and history/tab navigation by making Chrome treat all documentation pages as the exact same page, and it makes the documentation completely unsearchable on DuckDuckGo and presumably other search engines (but not Google).

**Comment by mz8i** [comment]
I'd like to second this request, and especially from the perspective of #13951 - when browsing documentation pages of any project, the middle mouse button is essentially my most used button as I always open links in new tabs. 

Just started using Three and this is massively impacting my productivity when browsing documentation.

I'd be willing to help amend this as I can foresee this impacting me a lot over time - I can see there was a PR a couple of years ago, any hints on whether/how one could help push this forward soon?
