### ISSUE TITLE
Deferred Rendering pipeline introduction

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#13907]
# Deferred rendering
Forward rendering doesn't fit well with most advanced use cases, and when it does - it lacks performance. I want to see a Deferred, Tiled renderer as the main renderer in three.js, not something relegated to /examples folder. 
### Motivation
Any kind of post processing you want to have today requires you to build part of the pipeline, depth buffer, normals and colour also. This results in duplicated effort for the hardware in most cases resulting in sub-optimal performance. 
If you wish to have any kind of sub-system which relies on a G-buffer, such as G-buffer based decal system which writes into colour+normal buffers - you require what three.js doesn't have.  

### Some useful links:
* **XG** by Alteredqualia: http://alteredqualia.com/xg/examples/earth_bathymetry.html (more http://alteredqualia.com/)
* **Deferred Irradiance Volumes** by pyalot: http://codeflow.org/webgl/deferred-irradiance-volumes/www/ (github https://github.com/pyalot/webgl-deferred-irradiance-volumes)
* **Tiled Deferred Renderer** by tiansijie: http://tiansijie.github.io/Tile_Based_WebGL_DeferredShader/ (source https://github.com/tiansijie/Tile_Based_WebGL_DeferredShader)

born as a result of this issue: #13807

**Comment by Mugen87** [comment]
Closing in favor of #2624.

**Comment by Usnul** [comment]
I don't think that this is really a duplicate. That issue talks about a specific implementation. This one talks about having deferred rendering as a valid choice for users of three.js

My wish was to point out the difference, I'm fine with the decision to close the issue.
