### ISSUE TITLE
Jerky Pointer lock controls

### ISSUE THREAD

**Issue by MrAnima** [mrdoob/three.js#13902]
##### Description of the problem

Whenever I try to play any ThreeJS-based project on internet, including VoxelJS, that uses pointer lock, I'm completely unable to control the camera with my mouse. Basically, after moving the mouse a little bit, the camera turns completely downwards or upwards and stays locked. If I move the mouse, it spins anti-clockwise "in-sync" with my mouse, whatever direction I move it in. Sometimes, by moving the mouse downwards when I'm locked with the camera facing up, or vice versa, I manage to gain control back, but it does the same thing a few centimeters after.
I'd like to show exactly what's wrong but in order for you to understand what's going on, I'd have to film both my screen and my mouse, which is a bit complicated.

Things that fail:
* [Official pointer lock demo](https://threejs.org/examples/misc_controls_pointerlock.html)
* All VoxelJS projects I've tried so far (including a personal one), here are two examples
  * [Voxel Drone](http://shama.github.io/voxel-drone/)
  * [Voxel Sky](http://shama.github.io/voxel-sky/)

I think about less than one year ago, I successfully played a VoxelJS demo game without any problem, so it's probably linked to my browser. Also, I seem to be the only person to be affected by it...

##### Three.js version

Pointerlock demo: "`THREE.WebGLRenderer 92`"
Voxel drone: "`THREE.WebGLRenderer 54`"

##### Browser

- [ ] All of them
- [x] Chrome _65.0.3325.181_
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Probably doesn't matter; MSI laptop with _Nvidia GeForce GTX765M_ graphics card

**Comment by Mugen87** [comment]
I'm unable to reproduce in Chrome 66.0.3359.117.

Have you tested with other browser, too?

**Comment by MrAnima** [comment]
I just did a bit of research, and while playing with [a little demo on MDN](https://mdn.github.io/dom-examples/pointer-lock/), I quickly realized that the red ball often teleport in weird locations, which is definetly linked to the problem I'm having, so **it's not three.js' fault**, but rather Chrome (I'm experiencing a lot of other really frustrating problems) or my computer (not my mouse, I also checked). Sorry for not searching enough.

Thanks anyways for your really quick answer ! 😄

**Comment by GalloglyP** [comment]
This appears to still be an issue with some chrome 79.0.3945.88 on windows . I am just using the pointerlock example to test. It is working properly on chrome linux, and Firefox 71.0 on windows and linux. A colleague was not able to reproduce on their chrome 79.0.3945.88 windows or chrome 79.0.3945.88 macOS.

The chrome bug tracker listed above has been closed. 

What are your thoughts on adding a high low filter parameter to the pointer lock controls. This fix works for me with range set to ~200.  


    function onMouseMove( event ) {

        if ( scope.isLocked === false ) return;
        var movementX = event.movementX || event.mozMovementX || event.webkitMovementX || 0;
        var movementY = event.movementY || event.mozMovementY || event.webkitMovementY || 0;

        if (movementX > scope.range || movementX < -scope.range) return;

**Comment by welschmoor** [comment]
We are almost in 2026 and I am confirming that in Chrome on Windows this still happens. Firefox fine. Chrome on Mac is fine too. Only windows, only Chrome. All your examples are buggy as hell, unplayable.

Update: setting the polling rate of the mouse to 125 solved the issue, any other value leads to bugs.
