### ISSUE TITLE
Improving Shadows

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#13908]
# Better Shadows.
More specifically, i want to see a better shadow-mapping implementation than PCF. Such as Variance shadowmaps. Second, i wish to see a cascading shadowmaps. They were once at the core of thee.js, but fell victim to bitrot and lack of support.
### Motivation
Currently shadows require a fair amount of artistry just to make them look okay. If we had a better shadowmap algorithm - a lot of existing problems with acne and filtering would go away. If we had a cascading shadowmap implementation - it would remove the need for artistry currently required to set up shadow camera for each shadow-casting light in the scene.

born from this issue: #13807
More details is available here: #5554

### Related
#14048 Soft Shadows via Light Source Sampling

**Comment by Mugen87** [comment]
> Such as Variance shadowmaps.

This is supported since `R108`, see #17171 🎉

**Comment by looeee** [comment]
Cascaded Shadow Maps: #18481

**Comment by Mugen87** [comment]
> More specifically, i want to see a better shadow-mapping implementation than PCF. Such as Variance shadowmaps. Second, i wish to see a cascading shadowmaps. 

Both techniques are now in the library. I think this issue can be closed now.

**Comment by Usnul** [comment]
>Both techniques are now in the library

Not to be a spoilsport, but I don't think CSM (Cascaded Shadowmaps) is part of three.js in any way, or did I miss something?

**Comment by arpu** [comment]
@Usnul  https://github.com/mrdoob/three.js/commit/e11983171f2eaa26bbf2cca8482765db92691988
