### ISSUE TITLE
A way to extend fog type?

### ISSUE THREAD

**Issue by jcyuan** [mrdoob/three.js#13914]
for example I'd like to add HeightFog for the scene, but it seems that there is no way to do that as Fog will be applied for all the objects in the scene.
so this can be only implemented by THREE official?

**Comment by WestLangley** [comment]
Correct. If you want custom fog, you will have to inject code into the shader. Perhaps something like the following:
```glsl
#ifdef USE_FOG

	#ifdef FOG_EXP2

		float fogFactor = 0.5 * exp2( - fogDensity * fogDensity * vElevation * vElevation * LOG2 );

	#else

		float fogFactor = 0.5 * ( 1.0 - smoothstep( fogLow, fogHigh, vElevation ) );

	#endif

	gl_FragColor.rgb = mix( gl_FragColor.rgb, fogColor, fogFactor );

#endif
```

**Comment by jcyuan** [comment]
@WestLangley kk, I will try to to this, but if there is a common way to custom some 'global shaders' which can be applied for all the objects in the sene that would be great. you think?
