### ISSUE TITLE
Introduction of a Particle Engine

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#13912]
# Competent Particle Engine (nice to have)
Particles are the magic stuff of the real-time visualization. As such, i believe it is necessary for a comprehensive real-time visualization to have a good particle engine. Simulation aspect can be kept rudimentary, have a way to plug in simulation logic, but handle things like sorting particles in view-space according to depth, and offer solution for tracking lifecycle of a particle, such as spawning/dying. Things like self-shadowing could be amazing to have also.

Examples:
* https://github.com/squarefeet/ShaderParticleEngine

born as a result of this discussion: #13807

**Comment by looeee** [comment]
There's also three.proton: https://github.com/a-jie/three.proton

And a more limited system already in the repo: [file](https://threejs.org/examples/js/GPUParticleSystem.js), [example](https://threejs.org/examples/webgl_gpu_particle_system.html)

**Comment by Usnul** [comment]
There are a few things that SPE doesn't do, in fact @squarefeet and I have attempted to do a re-write of the engine about a year ago, but we both go busy with other things and it's been frozen since. Mainly, i think three.js could handle things like particle pools, emitters, visibility tracking. If you have a dedicated datastructure to record various parameters of particles, as well as group them by emitters and handle sizing. Offering some kind of node-based simulation model for particles would be even more attractive, but I see how some people would see that as a bit too much.

**Comment by sunag** [comment]
I think that the Nodes System can already provide a robust Particle System, especially when integrated with GPU Compute for example https://github.com/mrdoob/three.js/pull/26655, both particle systems presented are parameterized and do not allow flow control as Nodes can offer and other advantages such as being compatible with any Material.

Since this issue was created several years ago, should we close it in favor of Node System?

**Comment by Mugen87** [comment]
> Since this issue was created several years ago, should we close it in favor of Node System?

Yes, I vote for doing that!

**Comment by LeviPesin** [comment]
Agreed, I think Nodes system allows the most for particle engine as a 3D library should provide -- and any more "high-level" interfaces should be developed by application themselves.
