### ISSUE TITLE
Question about EffectComposer documentation

### ISSUE THREAD

**Issue by j0hh** [mrdoob/three.js#13918]
Hey,
I'm currently in the process of porting EffectComposer to an ES6 module and have noticed that there isn't really any documentation on EffectComposer and it's related passes. 
Is there a specific reason for this, or is it just a simple lack of time? 😀
I'd be happy to contribute, if that's the case.

**Comment by Mugen87** [comment]
>  or is it just a simple lack of time

That one.

> I'd be happy to contribute, if that's the case.

:+1:

**Comment by j0hh** [comment]
Cool. I'll get on it.

**Comment by Mugen87** [comment]
Closing. Just make a PR if you have something to share :wink:
