### ISSUE TITLE
Why are Sprites which are transparent when rendered by WebGLRenderer opaque with SVGRenderer?

### ISSUE THREAD

**Issue by zfrenchee** [mrdoob/three.js#13934]
##### Description

I wanted to export SVGs from three.js, so I switched everything over to be rendered by an `SVGRenderer`: 
```
// var renderer = new THREE.WebGLRenderer( { 'alpha':true, 'transparent':true } );
var renderer = new THREE.SVGRenderer( { 'alpha':true, 'transparent':true } );
```
 However, all sprites are now opaque white, obscuring many other objects in the scene. Is this intentional? Shouldn't sprites which were transparent when rendered by `WebGLRenderer` still be transparent when rendered by `SVGRenderer` ?

**Comment by Mugen87** [comment]
`transparent` is not a valid parameter of `WebGLRenderer`. `SVGRenderer` has not parameters at all.

You should first ensure that your code is actually correct. Use stackoverflow or [forum](https://discourse.threejs.org/) for this and also provide you code or (even better) live examples.

**Comment by Mugen87** [comment]
Updated fiddle: https://jsfiddle.net/xh2e5y4d/3/

Your sprites do nowork since textures are not supported by `SVGRenderer`.

**Comment by zfrenchee** [comment]
Thanks @Mugen87 ! Just one final (usage) question: is there a way to do effectively the same thing in SVGRenderer? If you could point me towards some keywords I should look into I would much appreciate it!

**Comment by Mugen87** [comment]
I'm not sure about this but if you can manage to render your text as <text> elements, you should be back in the game.

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text

**Comment by zfrenchee** [comment]
@Mugen87 I'm also noticing some other issues with the SVGRenderer in that fiddle -- there are sometimes missing patches from the meshes:

<img width="569" alt="screen shot 2018-05-09 at 5 40 17 pm" src="https://user-images.githubusercontent.com/2761597/39841322-5d7938f8-53b0-11e8-90dc-8e2795cb0fd5.png">

Is this just the reality of the SVGRenderer, or am I configuring it wrong? (Let me know if I should ask this question somewhere else)

**Comment by mrdoob** [comment]
> Is this just the reality of the SVGRenderer

Yeah, it's a limitation of SVGRenderer.
