### ISSUE TITLE
Envmap example : Different rendering depending on the browser

### ISSUE THREAD

**Issue by aurelienwipon** [mrdoob/three.js#13935]
##### Description of the problem

Hello,

We have noticed on some computers, the example https://threejs.org/examples/#webgl_materials_standard is rendered in different ways depending on the browser running the scene. 

On theses computers, the Chrome and Firefox browser don't manage to display correctly the envmap (the background scene texture color seems to be slightly different too). No error in browser console.
On Edge and IE 11, the scene is well rendered. The only (little) problem is that it is very slow (10 FPS).

We tried different graphics card drivers but nothing changes (OS : Windows 10 pro 64 bits, Graphics card model : Geforce GTX 260, current driver version 342.01)

I join printscreen of the render.

I don't find similar issue posted on the GIT discuss. Did you know the problem or do you have ideas to avoid the matter ? 

##### Three.js version

- [ ] Dev
- [X] r92
- [ ] ...

##### Browser
![chrome](https://user-images.githubusercontent.com/38105815/39234281-14fff348-4873-11e8-803c-e641c500d95f.png)
![edge](https://user-images.githubusercontent.com/38105815/39234282-1517061e-4873-11e8-9337-640490706b41.png)
![firefox](https://user-images.githubusercontent.com/38105815/39234283-152eb9ee-4873-11e8-8db2-adf968beb42a.png)
![internet_explorer_11](https://user-images.githubusercontent.com/38105815/39234284-1549a45c-4873-11e8-9a3b-5425914d9ad5.png)

- [] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Windows 10 pro 64 bits 
Graphics card model : Geforce GTX 260 
Current driver version 342.01

**Comment by aurelienwipon** [comment]
Chrome version : Version 66.0.3359.117 (Build officiel) (64 bits)
Firefox version : 59.0.2 (64 bits)
Edge version : Microsoft Edge 41.16299.248.0
Internet Explorer 11 version : 11.248.16299.0

**Comment by WestLangley** [comment]
Can you help by answering the following questions?

1. Does this example render the same on all four browsers using a previous three.js revision?
2. Are there other examples that exhibit the same issue using r.92?

**Comment by aurelienwipon** [comment]
@WestLangley Thanks for your answer. Yes, I can :

1-I've test 2 previous releases :
-With r91 the rendering is exactly the same than with r92 on all browsers.
-With r84  the rendering is exactly the same than with r92 on edge, IE 11 and firefox, but on chrome it's different, the model is totaly white without error in console.

Result on Chrome with r84 :
![chrome_r84](https://user-images.githubusercontent.com/38105815/39247134-da6c0ac0-4898-11e8-84f6-e633aad19b6c.png)

Do you want I test other specific version ?

2- I didn't see other problems but I didn't test all examples. I will test all examples on Edge and Chrome and I will come back here after these tests.

**Comment by aurelienwipon** [comment]
@WestLangley 2- Yes on r92 there are some other examples with the same problem :

Here are some printscreen with rendering differences between Chrome (on the left) and Edge (on the right)

![camera_example](https://user-images.githubusercontent.com/38105815/39250387-f4e02c30-48a0-11e8-91bc-9e0b7e76e20a.png)
![convex_geometry_no_blue_sphere](https://user-images.githubusercontent.com/38105815/39250388-f4fe28c0-48a0-11e8-9a30-c2ab7ccb2f47.png)
![cubemap_dynamic_2_black](https://user-images.githubusercontent.com/38105815/39250389-f51b5b0c-48a0-11e8-83f5-7ef7fd34a53f.png)
![cubemap_refraction_not_rendered_on_chrome](https://user-images.githubusercontent.com/38105815/39250390-f536863e-48a0-11e8-9342-140deb2c63a4.png)
![decals_color_difference](https://user-images.githubusercontent.com/38105815/39250391-f55218f4-48a0-11e8-97e8-eb0f35aa8487.png)
![envmap_exr_not_render_on_chrome](https://user-images.githubusercontent.com/38105815/39250392-f56fc78c-48a0-11e8-959d-213c5620127d.png)
![envmap_hdr_not_render_on_chrome](https://user-images.githubusercontent.com/38105815/39250393-f58aa200-48a0-11e8-84ad-014acfa719a0.png)
![geometry_colors](https://user-images.githubusercontent.com/38105815/39250394-f5a63132-48a0-11e8-98a1-abf92b31e673.png)
![geometry_shapes_no_little_box](https://user-images.githubusercontent.com/38105815/39250395-f5c21b90-48a0-11e8-8ea2-90ccf224bf58.png)
![gltf_extensions_no_reflection](https://user-images.githubusercontent.com/38105815/39250396-f5dda446-48a0-11e8-9303-2c27a933f6bc.png)
![gpgpu_birds_not_render_on edge](https://user-images.githubusercontent.com/38105815/39250397-f5f9c8ce-48a0-11e8-9d9a-6714c81042df.png)
![gpgpu_protoplanet edge](https://user-images.githubusercontent.com/38105815/39250398-f627e222-48a0-11e8-9704-d1c4e2c889cb.png)
![gpu_particle_system_not_render_on_chrome](https://user-images.githubusercontent.com/38105815/39250400-f64c62dc-48a0-11e8-8600-492f278081fe.png)
![interactive_points_not_rendered_on_chrome](https://user-images.githubusercontent.com/38105815/39250401-f674b782-48a0-11e8-8bef-9285dc12e7ea.png)
![interactive_raycasting_points_not_render_correctly_on_chrome](https://user-images.githubusercontent.com/38105815/39250402-f6a6ae54-48a0-11e8-9864-b84ba6d6f162.png)
![kinect_not_render_on_chrome](https://user-images.githubusercontent.com/38105815/39250403-f6cdb4ea-48a0-11e8-9a1a-fe6da542130f.png)
![loader_amf_not_render_on_edge](https://user-images.githubusercontent.com/38105815/39250405-f6f3469c-48a0-11e8-9497-081edf229b6e.png)
![reflectivity_bad_render_chrome](https://user-images.githubusercontent.com/38105815/39250406-f7104ac6-48a0-11e8-933f-fd039c36f1e6.png)

On edge all examples are slower than on Chrome. With some examples the rendering differences are very important, for example :
-camera / cinematic Chrome : 50 FPS  -  Edge : 3 FPS
-camera / logarithmicdepthbuffer 50 FPS  -  Edge : 8 FPS

**Comment by mrdoob** [comment]
@kenrussell are Geforce GTX 260 supported by Chrome?

**Comment by kenrussell** [comment]
@mrdoob The GeForce GTX 260 was released 9 years ago. The Chrome team doesn't test on such old hardware and can't guarantee that everything is working correctly on it.

**Comment by mrdoob** [comment]
@kenrussell sounds good. thanks!

**Comment by mrdoob** [comment]
Closing this. Unsupported hardware.
