### ISSUE TITLE
Webworker for rasterize/decode Texture from image

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#13960]
##### Webworker for rasterize/decode img

Switch the decoding of images ( rasterize ) in a webworker instead of the mainthread help to avoid the "freeze" effect happening when decoding medium/large image.

Basic idea : https://aerotwist.com/blog/the-hack-is-back/

I use these in my current production involving texture from image and the smoothness gain is real, I think it would be nice to add this feature directly in the TextureLoader + keeping the current simple image load when webworker are not not available. 

##### Three.js version

- [x] Dev
- [x] r92

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
There is already [ImageBitmapLoader](https://github.com/mrdoob/three.js/blob/dev/src/loaders/ImageBitmapLoader.js) and a respective example. Have you missed these resources? 😉 

https://threejs.org/examples/webgl_loader_imagebitmap.html

**Comment by Makio64** [comment]
@Mugen87 I did miss it, hard to catch up with all the new stuffs here :)

After read the code of  ImageBitmapLoader from what I understand the blob & createBitmap are happening in the mainthread instead of a webworker, and we can probably switch to a webworker for perf gain and avoid the freeze.

**Comment by Mugen87** [comment]
I don't think so. The usage of `ImageBitmap` already avoids the decode overhead in the main thread. Moving the other stuff in a worker seems inappropriate to me.

**Comment by mrdoob** [comment]
> After read the code of ImageBitmapLoader from what I understand the blob & createBitmap are happening in the mainthread instead of a webworker, and we can probably switch to a webworker for perf gain and avoid the freeze.

Profile it 😉

The decoding happens in a different thread. The remaining browser freeze happens in gl when uploading the texture to the GPU. The only way to workaround it AFAIK is by using compressed textures.

**Comment by mrdoob** [comment]
@spite went into more detail here: https://github.com/mrdoob/three.js/pull/12456#issuecomment-340501247

@paullewis any chance you can add a warning on that article to avoid this kind of confusions?
