### ISSUE TITLE
Cannot read property 'clone' of undefined

### ISSUE THREAD

**Issue by dbkaplun** [mrdoob/three.js#13964]
Using `BufferGeometry#setFromObject` and `Geometry#fromBufferGeometry`in sequence causes an error.

Here's the [repro](https://codepen.io/anon/pen/odZxda). (Scroll down in the JS)

Error:
```js
Uncaught TypeError: Cannot read property 'clone' of undefined
    at addFace (VM444 three.js:9158)
    at Geometry.fromBufferGeometry (VM444 three.js:9219)
    at VM445 pen.js:15
```

Code:
```js
let points = new THREE.Points(geom);
const bufGeom = new THREE.BufferGeometry().setFromObject(points);
points = new THREE.Points(new THREE.Geometry().fromBufferGeometry(bufGeom));
```

Related: #10339

**Comment by WestLangley** [comment]
It works fine if the number of points is a multiple of 3.

`Geometry.fromBufferGeometry( bufferGeometry )` assumes `bufferGeometry` represents a mesh.

**Comment by dbkaplun** [comment]
This is a bug though, right?

I don't think requiring geometries to have a multiple of three number of points is a reasonable solution to this problem.

**Comment by WestLangley** [comment]
`Geometry.fromBufferGeometry()` assumes the geometry represents a mesh. Does your geometry represent a mesh?

**Comment by Mugen87** [comment]
From my point of view, the code works as designed. I tend to close the issue.

**Comment by dbkaplun** [comment]
I will try to spend some for this ticket later this week/weekend!

**Comment by dbkaplun** [comment]
I've created #14022, which fixes this error, since a face is always made from a group of 3 points. It would also be good to update documentation for `fromBufferGeometry` to mention support for `Points` geometries.

**Comment by WestLangley** [comment]
Closing. See https://github.com/mrdoob/three.js/pull/14022#issuecomment-412400720.
