### ISSUE TITLE
UCBrowser support ? 

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#13961]
Hello there,
I'm just wondering how bad is the webgl UCBrowser on Android implementation currently, is it supported at the moment or completely out of support ( as a confirmation ) ? 

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I guess it's better to ask this question at stackoverflow.

**Comment by mrdoob** [comment]
UC Browser for Android is Chromium based.
