### ISSUE TITLE
Fat lines, world position and clipping

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#13979]
##### Description of the problem

I'm unable to apply clipping to the new fat lines in the examples. `clippingPlanes` and `clipping` don't seem to be doing anything. While looking into the shader's i realized i don't know how to obtain the world or view position of the fragment.

##### Three.js version

- [ ] Dev
- [x] r92
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by pailhead** [comment]
The world space position i was able to generate by lerping between start end end with `position.y`. I'm not sure about the default clip planes, but they may not be working.

**Comment by WestLangley** [comment]
Derived classes of`ShaderMaterial` require setting `material.clipping = true`.

**Comment by pailhead** [comment]
I could swear that i tried both `.clipping = true` and `.clippingPlanes = [plane]` but i didn't do anything else regarding updates, which, looking at the shader code seems like it would be necessary, will try again tomorrow.

**Comment by mrdoob** [comment]
@pailhead: #13999
