### ISSUE TITLE
Support WebXR API (to eventually deprecate WebVR v1.1)

### ISSUE THREAD

**Issue by cvan** [mrdoob/three.js#13973]
The [WebXR API](https://immersive-web.github.io/webxr/) is the successor to [WebVR API (v1.1)](https://immersive-web.github.io/webvr/). There is a new Chrome Origin Trial, [WebXR](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/available-trials.md#current-experimental-features).

You can test WebXR on Chrome M67+ (with the WebXR and Gamepad Extensions flags enabled from `chrome://flags`). Tentative timeline for Chrome: September 2018. Other browser vendors: TBD.

Relevant links:

- [Chrome Beta M67: Announcing WebXR Origin Trial]( https://blog.chromium.org/2018/04/chrome-67-beta-webxr-origin-trial.html)
- [Intent to Experiment (Chromium mailing list)](https://groups.google.com/a/chromium.org/forum/m/#!topic/blink-dev/7TWtMJffZno/discussion)
- https://github.com/immersive-web/webxr-samples#readme
- https://github.com/immersive-web/webxr-polyfill#readme
- https://github.com/immersive-web/webxr-reference#readme (WIP documentation which will eventually live on [MDN](https://developers.mozilla.org/)) 
- immersive-web/webvr-polyfill#318

**Comment by modulesio** [comment]
Is there supposed to be an option on the trial signup form? I don't see it...

![capture 4](https://user-images.githubusercontent.com/6926057/39489841-d3cc702c-4d54-11e8-9259-daf1ba3acde3.PNG)

**Comment by cvan** [comment]
@modulesio thanks, I filed GoogleChrome/OriginTrials#46, and it was swiftly fixed. check the [Sign-Up page](https://docs.google.com/forms/d/e/1FAIpQLSfO0_ptFl8r8G0UFhT0xhV17eabG-erUWBDiKSRDTqEZ_9ULQ/viewform) now:

<img width="714" alt="screen shot of Features on Origin Trials Sign-Up page" src="https://user-images.githubusercontent.com/203725/39551954-f529860c-4e1b-11e8-8bac-5de864729885.png">

**Comment by mrdoob** [comment]
#13978 😊

**Comment by mrdoob** [comment]
There are still a few bugs, but all the examples should be able to Enter/Exit XR now.

https://rawgit.com/mrdoob/three.js/dev/examples/?q=webvr

**Comment by mrdoob** [comment]
XRInput now implemented via `rendere.vr.getController()`.
I've also added the same API to `WebVRManager` for cross-browser/device support.

This example should behave the same in WebVR and WebXR:
https://rawgit.com/mrdoob/three.js/dev/examples/webvr_daydream.html

**Comment by mrdoob** [comment]
This is how the abstraction looks like:
![download_20180623_075256](https://user-images.githubusercontent.com/97088/41810884-7bf295d6-76ba-11e8-841e-7c3bd63467cb.jpg)

**Comment by Mugen87** [comment]
WebVR support has been removed #18129. WebXR is now available with latest Chrome (without flags or origin trials token) and supported via `WebXRManager`.
