### ISSUE TITLE
Parsing the animations in ColladaLoader

### ISSUE THREAD

**Issue by ValentinChareyre** [mrdoob/three.js#13981]
##### Description of the problem

Hello,

The following is a **solution** to a problem I have just faced with the **animations** parsed by the new ColladaLoader.

I use Autodesk Maya 2017, and when exporting the 3D model containing animations, an extra `<animation>` tag has been added under the "real" `<animation>` tag.

```xml
<animation id=​"xxx-anim" name=​"xxx">
    ​<animation>
        ​<source id=​"xxx-Matrix-animation-input">​</source>​
        <source id=​"xxx-Matrix-animation-output-transform"></source>
        ​<source id=​"xxx-Interpolations">​​</source>​
        <sampler id=​"xxx-Matrix-animation-transform">​</sampler>
        ​<channel source=​"#xxx-Matrix-animation-transform" target=​"xxx/​matrix">​</channel>​
    </animation>
​</animation>
```

I digged into the source code of the `ColladaLoader` and I added the following lines into the `parseAnimation( xml )` function in order to handle this extra tag:

```javascript
switch ( child.nodeName )
{
    /* Handling 'source', 'sampler' and 'channel' */

    case 'animation':
        child.setAttribute( 'id', xml.getAttribute( 'id' ) );
        child.setAttribute( 'name', xml.getAttribute( 'name' ) );
        parseAnimation( child );
        return;
}
```
##### Three.js version

- [ ] Dev
- [x] r92
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by ValentinChareyre** [comment]
Since I am far from being a ThreeJS expert, I wanted to "suggest" a "quick fix", without knowing if the problem came from the Maya exporter, or if the library should handle this case.

PS: I deliberately chose `return` instead of break, because the `animation` child node is the real one we want to parse and the following line should not be called

```
library.animations[xml.getAttribute( 'id' )] = data;
```

**Comment by Mugen87** [comment]
According to page 46 of https://www.khronos.org/files/collada_spec_1_4.pdf, it's valid to nest animation tags. So I don't think it's bug in the exporter. Besides, overwriting attribute properties seems to not valid, even it works for your case.

**Comment by Mugen87** [comment]
Can you please share a Collada file for testing purposes?

**Comment by ValentinChareyre** [comment]
Here is a splending teapot ! 😄 

[teapot.zip](https://github.com/mrdoob/three.js/files/1970832/teapot.zip)

I understand, the id and name should be correctly referenced in the `animation` returned property, and I don't see other way but setting it like this....

**Comment by Mugen87** [comment]
The problem is that animations can also be defined like this:
```xml
<animation name="jump" id="jump">
 <animation id="skeleton_root_translate">
 <source/><source/><sampler/><channel/>
 </animation>
 <animation id="left_hip_rotation">
 <source/><source/><sampler/><channel/>
 </animation>
 <animation id="left_knee_rotation">
 <source/><source/><sampler/><channel/>
 </animation>
 <animation id="right_hip_rotation">
 <source/><source/><sampler/><channel/>
 </animation>
 <animation id="right_knee_rotation">
 <source/><source/><sampler/><channel/>
 </animation>
</animation> 
```
Overwriting attributes is problematic in this case, right?

**Comment by ValentinChareyre** [comment]
Yes, clearly, you are right. Maybe, a simple check before calling `setAttribute` will prevent the overwrite?
