### ISSUE TITLE
unicode character split issue in function createPaths(src/extras/core/Font.js)

### ISSUE THREAD

**Issue by mooncaker816** [mrdoob/three.js#13988]
##### Description of the problem

While creating paths for common string text, the current function `createPaths( text, size, divisions, data )` works fine, but not for those characters whose unicode is > U+FFFF due to below split function:
`var chars = String( text ).split( '' );`
For example, character "𝄞" (U+1D11E) is split into 2 parts, so it won't be able to referred correctly while looking up from the font glyphs.

![](http://oumnldfwl.bkt.clouddn.com/three.png)
 
I guess there're pretty less requirements as mine, maybe the impact is almost zero. But still better to handle properly for those kind of scenarios. 😃

Thanks.

##### Three.js version

- [ ] Dev
- [x] r92
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Couldn't we just use `Array.from` for this use case? https://jsfiddle.net/5LLchg9q/

 `Array.from` is not supported in IE 11, but we could still use `split()` as a fallback. We could also add a polyfill.

**Comment by Mugen87** [comment]
I wonder if we could drop IE11 support at some point? 🤔

**Comment by mooncaker816** [comment]
Yes, both `Array.from(text)` & `[...text]` works. 
I think use `split()` as fallback is reasonable.

**Comment by Mugen87** [comment]
So instead of 
```js
var chars = String( text ).split( '' );
```
let's do this:
```js
var chars = Array.from ? Array.from( text ) : String( text ).split( '' ); // see #13988
```
Would you like to do a PR with the changes

**Comment by mooncaker816** [comment]
Hi @Mugen87 , PR #13998 is created, pls kindly review. Thanks.

**Comment by gero3** [comment]
https://jsfiddle.net/5LLchg9q/1/

Why not use 
String.prototype.match.call(string, /[\uD800-\uDBFF][\uDC00-\uDFFF]?|[^\uD800-\uDFFF]|./g)
instead of 
String( text ).split( '' )

**Comment by Mugen87** [comment]
@gero3 Can you please explain the regex a bit? 😇

**Comment by mooncaker816** [comment]
@Mugen87, 
For the unicode point within `\u10000-\u10FFFF`, I believe they are encoded with Extended UCS-2 in JS as a pair of surrogate points: \<high surrogate\>\<low surrogate\>, where high surrogate range is `\uD800 - \uDBFF` and low surrogate range is `\uDC00 - \uDFFF`. 
Such as `\u10001` => `\uD800\uDC01`. 
`high surrogate = Math.floor((unicode point - 0x10000) / 0x400) + 0xD800`
`low surrogate = (unicode point - 0x10000) % 0x400 + 0xDC00`

So I guess @gero3 intends to pick all those pairs by `[\uD800-\uDBFF][\uDC00-\uDFFF]` and ignore the invalid character with only one single surrogate by `[^\uD800-\uDFFF]`? (Although the single surrogate scenario should not happen.)

If this is true, then I guess we should use below regex:
`/[\uD800-\uDBFF][\uDC00-\uDFFF]|[^\uD800-\uDFFF]/g` 
or 
`/[\0-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]/g`

@gero3 , Pls correct me if I'm wrong, thanks.

https://jsfiddle.net/vj49vuxb/2/

**Comment by Mugen87** [comment]
@mooncaker816 If you are happy with the current implementation of your PR, i would prefer this way. It's just easier to read than introducing a new regex.

**Comment by zz85** [comment]
The regex looks like a condensed version of https://github.com/dotcypress/runes

**Comment by Mugen87** [comment]
The examples in the README file seem to work with `Array.from()`.
