### ISSUE TITLE
Instanced Geometry Suggestion

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#13995]
I successfully created a ground foliage system using instanced buffer geometry. Setting up the instancing wasn’t nearly as bad as I though it would be, however one aspect was just downright tedious.

What I’m referring to is recreating the Lambert shader manually and then adding in the custom orientation / position adjustments. This was necessary for the foliage material to respect scene lighting / shadows etc. Rebuilding the Lambert Material into a ShaderMaterial was not fun.

Would it not be easier to have a few for example: ShaderChunks[‘Instancing’]? If I’m not overlooking anything, it would just require a few chunks, an instancing_pars chunk which could contain the instancing attributes and applyQuaternionToVector function (from three.js dev instancing examples), and one right after the ‘begin_vertex’ chunk to alter the vec3 transformed variable using the function.

Would this not be much more user friendly? If a user wants to take advantage of instancing (who wouldn't), they simply have to set instancing: true on the material and of course set up the needed buffer attributes. They would no longer have to manually reconstruct an entire materials shader.

I've seen more complex examples of trying to ease usage of instancing, perhaps we should start with something a little more simple like this?

I’d be more than happy to make a PR, if this is desirable.

**Comment by titansoftime** [comment]
I did a console log of `THREE.ShaderLib['lambert']`, then replaced all the `#include`  with the corresponding `THREE.ShaderChunk` in both the vertex and fragment shader.

I'm familiar with the shader chunks but not  `Material.onBeforeCompile()`.

**Comment by Mugen87** [comment]
Replacing the includes is actually not necessary, see this [example](https://github.com/mrdoob/three.js/blob/e6aeced47b6961590658f701715d6689d3936155/examples/js/objects/Water2.js#L330-L332).

Apart from that, I'm in general not sure if we need a new to add new library functionality if `Material.onBeforeCompile()` is properly used.

**Comment by donmccurdy** [comment]
I haven't tried using builtin materials with instancing, so neither the "not fun" @titansoftime mentions nor the `onBeforeCompile` trick you mention are familiar to me... Perhaps we could write an example of this, and consider the `material.instancing=true` change if that isn't straightforward enough?

**Comment by titansoftime** [comment]
Oh, well I feel like an idiot about swapping out those includes lol, oh well.

I'll check out the onBeforeCompile and see if that works as well as patching in my new shader chunks.

I must add though, as an end user, I think it would be far more simple to utilize my suggested method, and it's pretty small change.

When I first looked into instancing a few years ago, I saw that I would have to mess with shaders and was like "umm, nope".

Adding a instancing flag/define to materials and adding like 2 additional junks would open up instancing to novice users in my humble opinion.

I've got my solution working fine for me, just want to extend the benefits of the knowledge your assistance has brought me to others (especially newbies) =]

**Comment by Mugen87** [comment]
> Perhaps we could write an example of this.

I've written this codepen to show how to enhanced standard material for basic instanced rendering. If you guys like it, I make a PR with a new example.

https://codepen.io/anon/pen/bMoOKB?editors=1010

**Comment by WestLangley** [comment]
There a many more details that need to be dealt with, in general. I'm filing another example today.

**Comment by Mugen87** [comment]
The codepen was just meant to get a first impression of the approach. It's good to see a more detailed example 👍

**Comment by pailhead** [comment]
@Mugen87  are you familiar with this?
https://www.npmjs.com/package/three-instanced-mesh

**Comment by pailhead** [comment]
>I've written this codepen to show how to enhanced MeshStandardMaterial with Material.onBeforeCompile() for basic instanced rendering. If you guys like it, I make a PR with a new example.

But in the end, I think that this may actually argue for my case. Providing more trivial `onBeforeCompile` examples would serve as good bait. Maybe more people would run into problems that i'm having as soon as they move past the trivial one liner examples. 

I'm curious how this will look (missed the comment). I hope I'm wrong about all of this and that some amazing concise, intuitive and performant code is presented:

>There a many more details that need to be dealt with, in general. I'm filing another example today.

**Comment by pailhead** [comment]
Just to reiterate:

From the OP:
>Would it not be easier to have a few for example: ShaderChunks[‘Instancing’]?

From @mrdoob 
https://github.com/mrdoob/three.js/pull/10791#pullrequestreview-43514115

Paraphrasing:

**Suggestion**:
>With feature FOO we can easily add dummy named chunks

```
//inside some material template
#include <logdepthbuf_pars_fragment>
#include <clipping_planes_pars_fragment>
...
#include #include <MY_DUMMY_CHUNK_PROPOSAL>
#include #include <AFTER_NORMAL>
#include #include <THREES_GLOBAL_UNIFORM_INJECTION_PLACE>
#include #include <EXTERNAL_GLSL_FUNCTIONS>
...
```

**Response:**
>No, it should be different syntax. 

```
% HOOK_NAME %
```

**Comment by pailhead** [comment]
@Mugen87 

>Replacing the includes is actually not necessary, see this example.

>Apart from that, I'm in general not sure if we need to add new library functionality if Material.onBeforeCompile() is properly used.

What is the proposal here, or what do you have in mind when you say "properly used"? 

I see the example as the inverse of the problem. It's how to include some shader chunk that's exclusively used by the templates, in a custom `ShaderMaterial`. 
The problem here is how to use something that would be exclusive to a `ShaderMaterial` or `RawShaderMaterial` (custom GLSL) and use it in a template. 

Please correct me if i'm wrong.

If this contract is up on that template level, meaning:
>Let's all agree that every `Material` is an instance of `ShaderMaterial` 
then overriding a built-in material such as `MeshLambertMaterial` would require providing a new template. Meaning, you would copy the code for Lambert, put your additional `#includes`, and call it done. 

I've seen this approach i think, but i thought that `onBeforeCompile` is supposed to bring convenience, or flexibility here?

**Comment by pailhead** [comment]
```javascript
class Material_onBeforeAfter_begin_vertex extends THREE.SomeMaterial{
	constructor(params){
		super(params)
		
		this.chunks.begin_vertex = `
			${params.beforeChunk}
			${THREE.ShaderChunk.begin_vertex}
			${params.afterChunk}
		`

	}

}

class InstanceMaterial extends Material_onBeforeAfter_begin_vertex{

	static chunk_before_begin_vertex = '...'
	static chunk_after_begin_vertex = '...'

	constructor(params){
		params.beforeChunk = InstanceMaterial.chunk_after_begin_vertex
		params.afterChunk = InstanceMaterial.chunk_after_begin_vertex

		super(params)

	}

}

class NormalMappingMaterialWrapper extends THREE.SomeMaterial {
	
	static chunk_replace_normal_begin = '...'

	static chunk_append_to_normal_begin = '...'

	constructor(someMaterial){
		super()
		this.copy(someMaterial)

		if( this.chunks.normal_begin ) {
			this.chunks.normal_begin = NormalMappingMaterialWrapper.chunk_replace_normal_begin
		} else {
			console.warn('Source material already has a chunk override for this chunk, would you like to foo, bar or baz')
		}

		if( this.chunks.normal_begin ) {
			this.chunks.normal_begin += NormalMappingMaterialWrapper.chunk_append_to_normal_begin
		} else {
			this.chunks.normal_begin = THREE.ShaderChunk.normal_begin + NormalMappingMaterialWrapper.chunk_append_to_normal_begin
		}

	}
}

//now this should hopefully work
const myInstance_NormalMapped_Material = new NormalMappingMaterialWrapper( new InstanceMaterial() ) 
```

**Comment by pailhead** [comment]
Even with `onBeforeCompile` in place, i've seen experienced users reach out for `THREE.ShaderChunk`
https://github.com/mrdoob/three.js/issues/12977#issuecomment-354140905

Unfortunately, I think that this is currently the superior way to `onBeforeCompile`.

```javascript

overrideChunks( myChunkManager.getChunks() )

function someMaterialWrapper( material ){
  const mat = material.clone()
  if( mat.defines.foo ){
    mat.defines.bar = ''
  } else {
    mat.defines.foo = ''
  }
  return mat
}
```
`Material.defines === {}` is a decent structure to work with, so something like this could work, provided any material, check whether it's some extended material by checking the defines, and then apply some logic that makes your effect work with the input effect.

**Comment by pailhead** [comment]
Here's how to keep the familiar `Material` interface with `materialIncludes` applied to this example:

https://github.com/pailhead/three.js/blob/material-includes-demo/examples/webgl_buffergeometry_instancing_lambert.html

_(the example itself is valuable to show how to apply instancing, this just demonstrates how to remove the boilerplate by leveraging more of what exists in three.js already)_

**Comment by Usnul** [comment]
I also took a stab at this. I wanted to have instancing for Foliage, and I wanted to be able to edit the instances in:
- count
- instanced attribute values

I also wanted to be able to reference each instance individually, so I can remove it later or edit its attributes (position,rotation,scale).

I ended up writing a lot of code, mostly due to abstractions which are required to achieve this, the end result was being able to render millions of instances while being able to manipulate them at runtime.
Some problems I ended up solving:

- material rewriting (based on @pailhead's approach, that was very helpful)
  - have to also create a .customDepthMaterial to get shadows to work
- instance index <-> reference mapping
- dynamic resizing of number of instances, including standard things like over-allocation to reduce chance of rebuilding the attributes entirely.
- make random removes cheap on average ( O(1) ) (e.g. index 1234 out of 5000 instances)
- spatial index abstraction on top of that, to only include instances that are visible, this removes a limit of number of instances to some degree
- binary serialization/deserialization. Reducing time and size footprint of the instance set.

**Comment by titansoftime** [comment]
@pailhead 

I've read through your posts and it seems that the main issue with my proposal is that it does not conform with the direction of the API.

That is understandable, but I figured adding a couple new chunks to the existing couple dozen would be fine.

> a gotcha is that this function must not include any branching logic, meaning there is no if else in there, otherwise it behaves rather erratically. Not a bug though:

I'm curious as to what additional logic you are referring to. At least for my use case it was simply enough to alter the transformed position/rotation in that one spot (after begin_vertex). What additional logic would be needed for instance placement?

**Comment by Usnul** [comment]
@titansoftime 

> Question regarding removing instances? Does this not require you to basically recreate the bufferGeometry? This would have noticeable runtime performance issues yea?

There are some tricks you can do. Simplest one is to not rebuild BufferGeometry and let it have more attributes than what you're actually using, at some later point you may decide that it's too big and it's not worth it to keep using all that memory and rebuild it, but that's an arbitrary point in time of your choosing.

> For my spatial indexing, I created a simple cell/chunk system based on scene x/z dimensions and number of chunks per axis. The one issue I had to resolve was frustum culling. For each cells geometry I had to basically create a box of vertices for each cell and set the geo boundingSphere based off those points, otherwise things would prematurely get culled. Curious as to your approach.

I use an already existing BVH implementation and populate it with references to individual instance (references are just int32 values). BVH leaves have an actual bounding box (AABB) for the instance. Here's what a leaf looks like:
```c
{
id: int32,
x0: double,
y0: double,
z0: double,
x1: double,
y1: double,
z1: double
}
```

My culling code looks like this:

```javascript
    camera.updateProjectionMatrix();

    const frustums = [];
    const frustum = new THREE.Frustum();
    frustum.setFromMatrix(new THREE.Matrix4().multiplyMatrices(camera.projectionMatrix, camera.matrixWorldInverse));
    frustums.push(frustum);

    group.update(frustums); // <- Magic happens here
```

Code for the `Group.update`:
```javascript
InstancedFoliage.prototype.update = function (frustums) {
    const instances = this.instances;

    const elementsToAdd = new Set();
    const elementsToRemove = [];

    function visitLeaf(node) {
        const index = node.object;
        //TODO check screen space size to decide if element should be seen or not
        elementsToAdd.add(index);
    }

    //build visible set
    this.bvh.threeTraverseFrustumsIntersections(frustums, visitLeaf);

    // console.log(`Visible: `, elementsToAdd.size);


    //remove those that are no longer visible
    instances.traverseReferences(function (ref) {
        if (!elementsToAdd.has(ref)) {
            //no longer visible
            elementsToRemove.push(ref);
        } else {
            //visible, and is already in the group, update the set
            elementsToAdd.delete(ref);
        }
    });

    //cull instances that are no longer visible
    elementsToRemove.forEach(function (ref) {
        instances.remove(ref);
    });

    const elementData = [];

    //process entities that have become newly visible
    for (let index of elementsToAdd) {
        //read transform data for instance
        this.data.getRow(index, elementData);

        const positionX = elementData[0];
        const positionY = elementData[1];
        const positionZ = elementData[2];

        const rotationX = elementData[3];
        const rotationY = elementData[4];
        const rotationZ = elementData[5];
        const rotationW = elementData[6];

        const scaleX = elementData[7];
        const scaleY = elementData[8];
        const scaleZ = elementData[9];

        const i = instances.add(index);

        //apply instance transforms
        instances.setPositionAt(i, positionX, positionY, positionZ);
        instances.setRotationAt(i, rotationX, rotationY, rotationZ, rotationW);
        instances.setScaleAt(i, scaleX, scaleY, scaleZ);
    }

};
```

I have a compact binary table for keeping instance transforms beside BVH, that way BVH remains fairly small and is traversed quite quickly.

You probably noticed, but this means that I have to essentially compute a bounding box for every instance. This is actually not that big a deal, I compute one for each instance specifically, but you could use an overestimated one by taking the bounding sphere and scaling that, for my usecase I'm okay paying extra for creation of an instance for the benefit of having a really tight box at runtime. That's also a reason why I don't rebuild the entire thing every time but use efficient serialization format to just load thousands of already processed instances.

Also, regarding culling - i just turn it off on the `THREE.Mesh` -> mesh.frustumCulled = false. Since i do my own culling anyway, no point in having three trying to do anything here.

**Comment by pailhead** [comment]
@titansoftime 
>Also, very cool regarding the ability to reposition/rotate instances. Mine does not allow that.

>I'm curious as to what additional logic you are referring to. At least for my use case it was simply enough to alter the transformed position/rotation in that one spot (after begin_vertex). What additional logic would be needed for instance placement?

We're talking about (several) different things. 

1. I don't understand your implementation or proposal. **reposition** and **rotate** are the two most basic operations i want to do with instances. You mentioned that you achieved this with a few lines, but i'm confused what you're referring to. Can you rotate the instances in your example or not?

2. I'm talking about the logic in `onBeforeCompile`. 
   >Would this not be much more user friendly? If a user wants to take advantage of instancing (who wouldn't), 
 
    No, no and no. This time i'm going to be more firm :). Three.js has an api that allows you to do this extension, **without asking the whole world to conform to your use case**. I was just mentioning that it doesn't make things much easier, even though it exists.  And was mostly responding to @Mugen87:
    > if Material.onBeforeCompile() is properly used.
    
    Simple example, i wrote `InstancedMesh`, it does a similar thing, differently. **I like that one**, you like this one. It's going to be hard for either one of us to just agree, but the difference is, i've actually had a PR here for a year :)

3. >Is this what you did to enable casting of shadows? I have been struggling for days trying to figure this out. Receiving shadows was no issue.

   Not at all, this is **what I did**, the man said so himself:
   >material rewriting (based on @pailhead's approach, that was very helpful)
   have to also create a .customDepthMaterial to get shadows to work

   https://github.com/mrdoob/three.js/pull/10750
   https://www.npmjs.com/package/three-instanced-mesh

 
To be brutally honest - WTF is going on here :D

@titansoftime this is the second time you're participating in an instancing issue here. The first time you were in support of a really bad solution, and an inspiration to writing `InstancedMesh`. You posted on SO and the only reply was mine, and i tried to give you more insight into how things work. I thought you tried it, but here you are again asking for the same thing.

I tell you that you are asking for the same thing, but you don't believe it! And then you ask for more of the `InstancedMesh`. Yes the solve for the shadows is to use the `customDepthMaterial`, **does this mean you have to reconsider your approach**:?

>If I’m not overlooking anything, it would just require a few chunks, an instancing_pars chunk 

So yeah, in short you're overlooking a lot of things.

@WestLangley and @Mugen87 

I think you guys are wasting time on `onBeforeCompile` (mugen and "proper" usage that never happened) and rewriting proposed PRs (west). **This is fine**, piece, love ❤️  and happy feelings!

What i don't understand is why couldn't you go to the PR for example and say:

> Hey we're ditching this. 

Why couldn't you go to one of the `onBeforeCompile` issues and go:

> Hey, this actually works, **i know how to properly use it** just need the time to write examples, please be patient.

It  would be respectful towards my time.

**Comment by titansoftime** [comment]
@unsul Super cool stuff man.

@pailhead 

Man, I don't even know where to begin. In respects to me saying "Also, very cool regarding the ability to reposition/rotate instances. Mine does not allow that." I said repositioning, not positioning. As in altering position at runtime. Obviously you want to position your instances...

I don't understand your issue with me asking Unsul a question about shadows...

In fact, I am not really enjoying reading walls of exasperation.

Closing this.

**Comment by pailhead** [comment]
Youre using different terminology. I never really thought of a concept of "repositioning" something in 3d graphics. It's redundant, it feels like i would always be "repositioning" instead of "positioning".

The term for updating attributes and such in three.js is `dynamic`.

**Comment by pailhead** [comment]
@Usnul 

No, sorry if it came the wrong way. I've put it up on npm and licensed it and write walls of texts so it can be built upon and improved. I would definitely like to discuss the philosophies. 

I'm curious what you mean by coupling since both seem to be coupled. My impression is that you've done a lot on the culling front and structures to efficiently do all of that on the CPU?

**Comment by titansoftime** [comment]
I will create a PR this weekend. Not for the intent of merging, but just so that we can actually be on the same page. Perhaps my code will require less context clues than my terminology.

I am also super interested in Unsul's BVH approach to instance culling. I have to artificially inflate my bounding spheres for each "cell" in order to get good looking results, which of course results in less than ideal culling and the drawing of excessive polygons.

**Comment by Usnul** [comment]
@pailhead 
* your approach is for fixed number of instances, mine is dynamic
* your approach is for visualization only, mine includes spatial reasoning
* your approach is for all instances to be in GPU memory, mine is intended for visualization of a fraction of a very large set
* yours tracks instances by index, mine by a reference, which only makes a difference when you have the ability to remove instances though

**Comment by pailhead** [comment]
I'm curious to see what all that means, do you have some code to share?

**Comment by Usnul** [comment]
@pailhead 
I cull in the context of instanced geometry, essentially only one geometry is ever submitted in a draw call, the attributes of that geometry and number of requested instanced to draw changes, sometimes attributes are rebuilt when arrays' capacity becomes much larger than actual number of drawn instances. I think we're on the same page - I implemented this system in order to reduce number of draw calls to 1.

PS: I included an example
http://server1.lazy-kitty.com/tests/instanced-foliage-1mil/

**Comment by pailhead** [comment]
It could work with non instanced meshes though too?

**Comment by Usnul** [comment]
@pailhead 
I appreciate your desire. We could talk about that module if you want. My implementation is dynamic in size, meaning you can add/remove instances, which your implementation doesn't permit - i guess that's the largest different really.

**Comment by pailhead** [comment]
Ty, just point me to the code, I’m curious to see how it’s being managed.

**Comment by Usnul** [comment]
@pailhead 
I work on non-public repository. I would be happy to share the code, if you ping me privately.

**Comment by mrdoob** [comment]
Closing in favor of #17505.
