### ISSUE TITLE
Ray.intersectTriangle throws THREE.Ray: .at() error though target doesn't work

### ISSUE THREAD

**Issue by kpetrow** [mrdoob/three.js#13997]
Requiring these targets is a pretty big change.  Going through trying to update busted code and found this:

Documentation for [ray](https://threejs.org/docs/#api/math/Ray.intersectTriangle) says this should still be returning a Vector3
```
intersect = ray.intersectTriangle(P1, P2, P3, true);
console.log(intersect); // error Ray: At() requires target
```

But sure maybe the docs weren't updated, make it jive with everything else
```
var intersect = new THREE.Vector3();
ray.intersectTriangle(P1, P2, P3, true, intersect);
console.log(intersect); // p {x: 0, y: 0, z: 0}
```
It requires the target to be passed in and then it returns the correct Vector3.
```
var intersect = new THREE.Vector3();
intersect = ray.intersectTriangle(P1, P2, P3, true, intersect);
console.log(intersect); // correct p {x: 18.90542234, y: -176.43918164, z: 6632.0632793}
```

It looks like every ray function is still returning Vector3, or atleast the docs say it is.  I can wip up a fiddle if needed, but would rather not given its quitting time on friday.  Thanks..

**Comment by kpetrow** [comment]
Well crap,

**Comment by mrdoob** [comment]
🤔?
