### ISSUE TITLE
webgl_postprocessing_godrays example not working

### ISSUE THREAD

**Issue by NicolasRannou** [mrdoob/three.js#13991]
There is a gray for but no God Rays are visible.

No errors in the consoles.

https://threejs.org/examples/?q=godray#webgl_postprocessing_godrays

**Tested on:**
MacOS: 10.13.5
Chrome: 66.0.3359.139
Firefox: 59.0.2

<img width="584" alt="screen shot 2018-05-04 at 11 36 02 am" src="https://user-images.githubusercontent.com/214063/39621524-5a779eee-4f8f-11e8-90e5-cfd096f8067b.png">

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/13884
