### ISSUE TITLE
WebGLBackground: Rendering issue with Reflector

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#14006]
##### Description of the problem

While investigating an [issue](https://discourse.threejs.org/t/how-to-close-water-shadow-in-tilt-photography-model/2570) in the forum, I've encountered a rendering problem with `scene.background`.

This fiddle shows how it should look like. Proper reflections of the torus knot and the skybox:
https://codepen.io/anon/pen/XqeyBM

But if you set `transparent` to true on the reflectors material, it looks like this:
https://codepen.io/anon/pen/XqeyxR

![image](https://user-images.githubusercontent.com/12612165/39674398-9e2fbb2c-514b-11e8-9cc1-02affdf8461a.png)

For some reasons, the (white) clear color of the renderer is visible in the reflector's render target at certain parts. I have found two ways to solve this problem:

- Don't use `scene.background` but manually create the skybox like in this example:
https://codepen.io/anon/pen/jxGQQb
- It does also work if you set `depthWrite` to true of the shader material in `WebGLBackground`.

I don't know so far why these approaches fix the issue but I suppose it has to do something with the way `WebGLBackground` renders the background.

Note: The reflector is rendered **after** the background in all these examples.

##### Three.js version

- [x] Dev
- [ ] r92
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Does #15329 solve this one?

**Comment by Mugen87** [comment]
Yes, it does!!! :tada: :raised_hands:

**Comment by Mugen87** [comment]
Um, I'm afraid this problem is still not solved.  #15329 solved the issue when the reflectors material is transparent: https://codepen.io/anon/pen/XqeyxR

But now the problem occurs if the reflectors material is opaque, see https://codepen.io/anon/pen/XqeyBM

The problem is also visible in the [WebVR sandbox demo](https://threejs.org/examples/webvr_sandbox.html). As soon as you remove the background, the glitch is gone.

**Comment by mrdoob** [comment]
> The problem is also visible in the [WebVR sandbox demo](https://threejs.org/examples/webvr_sandbox.html). As soon as you remove the background, the glitch is gone.

I think #15662 fixed that issue.
