### ISSUE TITLE
Collada Loader TGA support

### ISSUE THREAD

**Issue by vlakken** [mrdoob/three.js#14003]
The example collada loader doesn't appear to support TGA files, I made a fork and with the following changes the loader now supports TGA. Is this something that could be merged?

https://github.com/mrdoob/three.js/compare/dev...vlakken:dev

##### Three.js version

- [ ] Dev
- [x] r92
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by makc** [comment]
but this would make TGALoader a dependency, no?shouldn't you do something like `if (THREE.TGALoader) ...` to make sure the TGALoader is not suddenly required when people do not use tga?

**Comment by vlakken** [comment]
Hey

I made the TGALoader no longer required, if a collada file has tga textures but ithe loader is not found  a console.warn will be triggered. 

https://github.com/mrdoob/three.js/compare/dev...vlakken:dev

**Comment by mrdoob** [comment]
@vlakken would you like to create a PR with your change?
