### ISSUE TITLE
[Enhancement] onBeforeCompile may break material's .clone() method

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#14009]
##### Description of the problem

`onBeforeCompile` seems to be ignored when cloning materials:

https://codepen.io/anon/pen/yjPLrJ?editors=1010

Expected result is equal amount of yellow and red cubes. 

Proposing to either:
1. consider `Material.onBeforeCompile` when cloning
2. document that there should be no cloning happening after setting this callback 
3. document that `.clone()` is non deterministic, it's going to be a different clone depending on the presence of `onBeforeCompile`

##### Three.js version

- [ ] Dev
- [x] r92
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
^Same applies to materials relying on `mesh.onBeforeRender` for updates, per https://github.com/mrdoob/three.js/issues/11573. When users have added the `.onBeforeFoo` hook themselves it's not so bad — they can probably realize pretty intuitively that the callback has to be copied over manually. But it's less obvious when the hook is added by a loader, e.g. GLTFLoader needs this to properly render spec/gloss PBR materials, and the resulting models don't "just work" when you clone them.

I'm not sure what solution makes sense here... Copying callbacks when cloning an object feels unintuitive, e.g. the DOM doesn't do this. More flexible ways to customize materials would certainly reduce the need for these hooks — maybe node-based materials, allowing custom nodes, are the (long-term) solution?

**Comment by pailhead** [comment]
I think `mesh.onBeforeRender` is slightly different, you could call it off the parent in some order. `onBeforeCompile` also hashes the materials, making this a lot more tricky. ( i might be wrong )
https://github.com/mrdoob/three.js/issues/13192

**Comment by pailhead** [comment]
I was going to say, it sounded like an issue of something that probably shouldnt be in `onBeforeRender` in the first place. 

https://github.com/mrdoob/three.js/blob/04e86d0e9f7f4dafffc134064c36049a7368deca/examples/js/loaders/GLTFLoader.js#L775

I will continue this conversation in the other issue.

**Comment by pailhead** [comment]
Given the example of gltf loader limitations, i would advise against trying to implement complex effects with `onBeforeCompile`.

**Comment by WestLangley** [comment]
> I guess I'm wondering whether we should try to keep improving hooks for replacement into shaders and onBeforeCompile, or whether we should be spending time on that instead. For example, implement glTF's spec/gloss materials as THREE.NodeStandardSGMaterial.

I agree, focusing on `NodeMaterial` would be a much better use of our time -- and we could follow that up with a graphical API to go with it.

**Comment by pailhead** [comment]
So, what is the appropriate timeline? Three years have passed since 2015. For the material includes no additional time would be spent.

@westlangley you were spending time yesterday doing an instancing example for onBeforeCompile, why spend time on that of the node material is appearing?

**Comment by pailhead** [comment]
>I guess I'm wondering whether we should try to keep improving hooks for replacement into shaders and onBeforeCompile, 

If it’s three lines of code then I guess hooks should be improved. At least that’s how I see the availability of onBeforeCompile. 

If it is ten lines of code, it seems like too much, that’s why material level includes have been rejected.

This is fine. But what’s the argument for waiting for 3+ years for node material, and the argument for its size if there is a penalty?

**Comment by pailhead** [comment]
Also, can you please stay on the topic of the issue? What is to be done in this particular case when I want to clone something that has onBeforeCompile and should the docs give me any additional information.

**Comment by pailhead** [comment]
> I guess I'm wondering whether we should try to keep improving hooks for replacement into shaders and onBeforeCompile, or whether we should be spending time on that instead. 

What are you wondering, can you share some thoughts?

**Comment by donmccurdy** [comment]
For this particular case, I don't think `.onBeforeCompile` should be copied when cloning an object. I won't object to documentation explaining that `.onBeforeCompile` won't be copied, but I also don't think it will help many people — if you know that `.onBeforeCompile` has been added to your material, you can probably figure out pretty quickly that it doesn't persist after cloning. It's the users who don't know what `.onBeforeCompile` is who are going to struggle, and I don't see how we solve that. Hooks make a good escape hatch, but a poor API.

More generally (and, yes, arguably off-topic 😅) if we knew that having a node-based material system in `src/*` really was an eventual goal, then I think we would approach this issue (and several others, like https://github.com/mrdoob/three.js/issues/12608) differently. Not just waiting for a thing from 2015 — there are plenty of active contributors to three.js, and if we know how NodeMaterial fits into the roadmap we can spend our time helping sunag to build it.

**Comment by pailhead** [comment]
Could you elaborate a bit on what hooks mean to you and why are they poor api?

Scenekit has something like his.

**Comment by pailhead** [comment]
An interesting find is that copying a `StandardMaterial` just straight up nukes the defines, that could be otherwise used with monkey-patched `THREE.ShaderChunk`. 

https://github.com/mrdoob/three.js/blob/dev/src/materials/MeshStandardMaterial.js#L123

**Comment by pailhead** [comment]
I found this:

https://en.wikipedia.org/wiki/Cloning_(programming)

>In computer science, cloning refers to the making of an *exact copy* of an object

**Comment by donmccurdy** [comment]
When extending a builtin material as you are doing, and adding an `onBeforeFoo` callback in the constructor, you should also be extending the `clone` or `copy` function to copy that callback if you intend for it to be preserved.

> "Exact copy" does this mean the object should behave like the original?

No — note that _all_ `Object3D` instances extend `EventDispatcher`, and can have arbitrary event callbacks attached to them — these are not cloned. I'm suggesting that hooks like `onBeforeFoo` are effectively an event callback and not a "property", and that it doesn't make sense for it to be cloned. I would expect for cloning to give identical results to serializing and de-serializing an object. For another example, cloning DOM nodes does not copy event listeners.

Using these hooks means that an object has state that cannot be cleanly observed, serialized, or modified. That is what I mean when I say it is a "bad API". Not that hooks shouldn't be used, they're useful escape hatches for custom needs, but common situations (like modifying builtin materials) should _eventually_ be supported through a non-imperative API. NodeMaterial is more promising for this purpose.

**Comment by donmccurdy** [comment]
> Digesting what you said makes it sound like no documentation here is even necessary.

I'm fine with documenting this. I just don't think documentation solves #11573, because users trying to clone an object probably have no idea (1) what a glTF extension is, (2) that one particular extension creates meshes with a custom material and others do not, and (3) that these custom materials involve `.onBeforeRender` and that the callback must be copied manually. There's nowhere we can put that documentation to really help, because users expect (very reasonably) that once they've loaded an object, they can forget about the file format used to load it.

In any case, although we seem to disagree on it, please feel free to open a PR to copy `.onBeforeFoo` or document the omission. It's a subjective question and ultimately others will need to weigh in. :)

**Comment by pailhead** [comment]
Please, is it possible to get your thoughts on some of the rest of this stuff?

I think i can maybe try to digest it to.

1. measure the similarity of `ShaderMaterial` API with `Material.onBeforeCompile`
2. if it's high, could `onBeforeCompile` be called `deferredShaderMaterialInterface`?

**Comment by pailhead** [comment]
>and (3) that these custom materials involve .onBeforeRender and that the callback must be copied manually. 


I don't think that this should be the holy word. I've suggested an implementation that does it without the `onBeforeRender`.
