### ISSUE TITLE
OBJLoader2 loadMtl Does Not Accept Array Buffer

### ISSUE THREAD

**Issue by pizza-r0b** [mrdoob/three.js#14010]
##### Description of the problem

[OBJLoader2 .loadMtl docs](https://threejs.org/docs/#examples/loaders/OBJLoader2.loadMtl) state content is text or array buffer, however array buffer is not supported. `_loadMtl` function in `OBJLoader2` calls the following:

`processMaterials(Validator.isValid(resource.content) ? mtlLoader.parse(resource.content) : null);`

`mtlLoader.parse` doesn't take an array buffer, just text.

##### Three.js version
r92

**Comment by kaisalmen** [comment]
@pizza-r0b thanks for spotting this.
It seems to a good idea to use `THREE.LoaderUtils.decodeText` inside `OBJLoader2.loadMtl` to transform an ArrayBuffer to a String and make this work instead of adjusting the docs.

**Comment by kaisalmen** [comment]
@Mugen87 I will take care. I have some other smaller bug fixes available for `OBJLoader2` and will open a combined PR later.

**Comment by pizza-r0b** [comment]
@kaisalmen Thanks I wasn't aware of `THREE.LoaderUtils.decodeText` I was using [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/TextEncoder)

**Comment by kaisalmen** [comment]
PR is now available!
