### ISSUE TITLE
apply animation to imported model

### ISSUE THREAD

**Issue by snowendless** [mrdoob/three.js#14029]
Hi guys,

I have a project using Three.js to display simulation,  here's the step:

1, export model in obj file, export the animation data in customized json file.

2, load the obj file in three.js and apply animation to the imported model.

It works great till I try to upgrade three.js to r86, which have a brand new animation system.

I've tried to apply animation to imported model with r86, but I can't use any animation function outside loaders....

I know I can export the model and animation in other file format and convert old file to new ones, 

but don't you think it would be more comfortable to have tools to apply customized animation outside loaders?

or any idea for work-around?
##### Three.js version

- [ ] Dev
- [x] r86
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow.
