### ISSUE TITLE
Vertex Color in OBJLoader2 works wrong

### ISSUE THREAD

**Issue by kirillovdm** [mrdoob/three.js#14032]
I'm trying to load my .obj and .mtl using OBJLoader2. Everything works good except FACE material. Actually FACE part of model created from Vertex Color Obj file. Desktop editor display my model pretty good. 
If I load FACE with [Sean-Bradley's Vertex Color Loader](https://github.com/Sean-Bradley/objVertexColors) it looks good. Seems Like the problem with OBJLoader2 Vertex Color algorithm: it can read the color, but do it with a strange green color.

In browser:
https://imgur.com/a/bV0WEhY
In desktop editor:
https://imgur.com/a/BIHsx52

What's the problem?

**Comment by donmccurdy** [comment]
Could you share a model so we can reproduce this? You can drag ZIP files into GitHub comments. Thanks!

**Comment by kirillovdm** [comment]
@donmccurdy sure! 
Also a should to say that I used [threejs-full-es6](https://www.npmjs.com/package/threejs-full-es6).
Now I use [three-full](https://www.npmjs.com/package/three-full) (updated package) and can't see the model on the scene at all (but in console I see that the model and materials are loaded).

[Here is](https://bobbled.zazmic.com/api/v1.1/download/14c57f7940584e2dbe742e75ddfbb6cc/62.zip) the zip this all files

**Comment by donmccurdy** [comment]
Getting inconsistent results from this model in different viewers... 

| macOS quicklook | obj2gltf -> GLTFLoader |
| <img width="509" alt="screen shot 2018-05-09 at 10 43 44 am" src="https://user-images.githubusercontent.com/1848368/39830488-738ee87a-5376-11e8-87f4-4e2502253b0c.png"> | <img width="549" alt="screen shot 2018-05-09 at 10 48 40 am" src="https://user-images.githubusercontent.com/1848368/39830530-9211b9d0-5376-11e8-9c89-fc241d6564f8.png"> |

**Comment by kirillovdm** [comment]
@donmccurdy yes, i see. But desktop editor (mashlab) can open this model correctly. Its mean that the model contain all info about vertex and color. Model in GLTFLoader looks almost good, but the FACE part contain VertexColor data and GLTFLoader can't read it. As I can see, VertexColor Loader was implemented in OBJLoader2, but it works wrong (with strange green color. see my first attached pic)..

I just want to understand how I can expand VertexColor reader in OBJLoader2 (because [this solution](https://github.com/Sean-Bradley/objVertexColors) works pretty good but only for models with VertexColor and can't read textures and mapping data ) or how I need to change my model.

**Comment by kaisalmen** [comment]
@kirillovdm It is a simple bug in `OBJLoader2`:
https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/OBJLoader2.js#L929:
```javascript
var indexPointerC = scope.colors.length > 0 ? indexPointerV : null;
```
must be this:
```javascript
var indexPointerC = scope.colors.length > 0 ? indexPointerV + 1 : null;
```
Looks better, doesn't it?
![image](https://user-images.githubusercontent.com/21079138/39837204-113898d2-53d6-11e8-82a1-12a53ece54c8.png)

Thanks, for spotting this. PR will come ...

**Comment by kirillovdm** [comment]
@kaisalmen, oooohhhh, really!? Thanks a lot buddy! That's what I was looking for!
Now you can call it OBJLoader++ 
=)

**Comment by kaisalmen** [comment]
PR is now available!
