### ISSUE TITLE
Ray Intersect**** functions do not change target to null

### ISSUE THREAD

**Issue by kpetrow** [mrdoob/three.js#14033]
These targets are giving me the run around.    But basically the issue i see is that ray intersect should make the target null if no intersect is found.  Instead it returns unchanged target if no intersect is found.  This makes it impossible to tell if target was the same or just not found or defeats the purpose of re-using target, since it has to be cleared all the time.

```
 var sphere = new THREE.Sphere( new THREE.Vector3(0,0,0), 5 )
 var ray = new THREE.Ray(new THREE.Vector3(0,10,0), new THREE.Vector3(0,1,0));
 var target = new THREE.Vector3();
 ray.intersectSphere(sphere,target);
console.log(target); // p {x: 0, y: 0, z: 0} !!!!!

```

[fiddle](https://jsfiddle.net/eo2bymw1/)

##### Three.js version

- [ ] Dev
- [x ] r92
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by hccampos** [comment]
You can't actually modify the value of an argument in Javascript. You can modify the values in the object which is passed, but not the actual original reference.

To check if there is an intersection you need to check the return value of the method. If there is no intersection the method should return `null`.

**Comment by kpetrow** [comment]
Wait. I thought you got rid of returning objects and only using targets?  What functions use target exclusivly, and which take both?  This is really confusing me. some functions are now target only and some need both not to throw a "THREE.Ray: .at() target is now required" and some require no target?

**Comment by hccampos** [comment]
The targets are just to avoid unnecessary memory allocation and motivate people to reuse objects. If you are not in the hot path and don't care about too much garbage being generated you can just do `ray.intersectSphere(sphere, new THREE.Vector3());` and call it a day. It is equivalent to what it used to do when no target was provided.

Anyway, maybe this is moving towards territory that would better be served by a post in https://discourse.threejs.org/

**Comment by kpetrow** [comment]
Last comment and I'll move it.  So a target is required, but if there are no intersects then you have to check what is returned anyway to know if an intersect occurred? If the function is returning a new object regardless of target(its just required now) how is that re-using anything?

**Comment by hccampos** [comment]
If there is an intersection, it fills the target with the intersection and returns it (no new object allocated). Otherwise, it just returns null. So you make your target once when the app starts and then you just reuse it afterwards.
