### ISSUE TITLE
FBXLoader "TypeError: a.indexOf is not a function.(In'a.indexOf(0)'), 'a.indexOf is undefined"

### ISSUE THREAD

**Issue by tedyage** [mrdoob/three.js#14034]
I've wrote a program that using FBXLoader to load a mars object. It ran smoothly in the PC browsers and Mobile browsers such as chrome and safari...
  Howerver, when it ran in the ipad safari, it popped up an error that content is "TypeError: a.indexOf is not a function.(In'a.indexOf(0)'), 'a.indexOf is undefined". I wonder why it happened like that and how to solve this problem.
  Here is my piece of code about FBXLoader:

    //FBX Loader
      var fgxloader = new THREE.FBXLoader().
      load("asset/source/threejs_mars.fbx",function(object){
        console.log(object.toJSON());
        object.position.set(0,0,0);
        scene.add(object);
      },function(xhr){
        console.log("object "+(xhr.loaded/xhr.total*100)+"% loaded");
      },function(error){
        alert(error);
      });

  Could anyone help me please?

##### Three.js version

- [ ] Dev
- [x] r92
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
Can you share the file? I'll take a look.

**Comment by tedyage** [comment]
@looeee , you can check it out on: https://github.com/tedyage/ThreeJSCrashCourse/blob/master/planet.html

**Comment by looeee** [comment]
@tedyage which one of the files here is causing the problem? 

https://github.com/tedyage/ThreeJSCrashCourse/tree/master/asset/source

**Comment by makc** [comment]
it says mars

**Comment by tedyage** [comment]
@looeee ,the fbx file called threejs_mars.fbx caused this problem.
And I'm sorry for replying that late. And guess what, my work mate updated the system version of that ipad. And bang! it loaded that model smoothly as well. 
Any way, thanks for helping me with this problem.

**Comment by pailhead** [comment]
>it says mars

Wow, this really clarifies what it means "too much to read" :)

**Comment by looeee** [comment]
Haha! @pailhead goals 😛 

@tedyage can this be closed now?

**Comment by makc** [comment]
@pailhead  in original post there was this line
> load("asset/source/threejs_mars.fbx",function(object){

but like you say, too much to read
