### ISSUE TITLE
Upscale instead of downscale for power-of-two scaling

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#14041]
##### Description of the problem

Upscale instead of downscale by default. It'd be nice not to lose detail by default. Upscaling to the nearest power of two would preserve detail.

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by trusktr** [comment]
It would mean more memory, but I think a good default is preserving the user's intended look and feel when they first try it out, then they can optimize later.

**Comment by WestLangley** [comment]
See #13126.

**Comment by trusktr** [comment]
maybe an option to configure default to scale up or down could be useful.

But why does scaled down version look so bad sometimes, while browser's native CSS downscaling looks great? Is it just the algorithm in Three.js isn't as good?

**Comment by pailhead** [comment]
what if you have a texture that's 1025x1025 pixels in size?

**Comment by pailhead** [comment]
>But why does scaled down version look so bad sometimes, while browser's native CSS downscaling looks great? Is it just the algorithm in Three.js isn't as good?

Do you have a screenshot example?

**Comment by mrdoob** [comment]
That's how the behaviour used to be before r88. (31e8e610b6ad86aca97c24c71fd4ebc6b5bfa259). The reasoning of changing it was because users were ignoring the warnings and I thought downscaling would inspire users to provide power of two textures.

**Comment by trusktr** [comment]
Here's a screenshot, with an `<img>` tag in the background. The image is 3840 pixels wide, my display 2400 native pixels, and my desktop is set to 1350 pixels to make things a little bigger than native sizing, on Chrome OS:

![screenshot 2018-05-11 at 4 04 21 pm](https://user-images.githubusercontent.com/297678/39950508-66e1bb86-5536-11e8-9df5-56627375a12d.png)

And here's the same thing, but with a canvas in the background (Three.js):

![screenshot 2018-05-11 at 4 05 23 pm](https://user-images.githubusercontent.com/297678/39950517-7ab2d24e-5536-11e8-95b4-783a6b7f80bb.png)

I'm getting bad results with Three.js. At first I thought it might've been due to the downscaling that it mentions in the console. Is there anything else that can cause it?

**Comment by trusktr** [comment]
In either case, the black background is what we see behind the transparent images, only the gray streets are rendered by the `<img>` or `<canvas>`

**Comment by trusktr** [comment]
It seems like there's something actionable here: it'd be great if it just looked great in Three.js by default (not sure if it has to do with the downsizing though).

I'm doing something very simple: just a Scene, with a white ambient light, a Plane with white colored phong with a texture map, aligned to the screen. And that's it. It should look good, but it doesn't.

So my feature request is for it to look good with such a simple setup. :)
