### ISSUE TITLE
Potential misuse of `onBeforeRender`

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#14042]
`onBeforeRender` might be seeing some misuse. There are examples of using it to manage materials, and i've just run across an `onAfterClone` proposal for `Mesh` which i think is not a good idea.

I found this information scattered around examples, (ranging from old, to some submitted a few days ago), and old posts. I haven't been around to give my 2 cents when those posts were originally made, but would like to. So i'm not sure where best to address it?

##### Three.js version

- [x ] Dev
- [x ] r92
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
> There are examples of using it to manage materials, and i've just run across an onAfterClone proposal for Mesh which i think is not a good idea.

Can you add links to the pieces of codes you're referring to?
