### ISSUE TITLE
QuickHull warning in node.js

### ISSUE THREAD

**Issue by maurocolella** [mrdoob/three.js#14043]
##### Description of the problem

In `node.js`, the default QuickHull example throws warnings, such as:
`THREE.Triangle: .normal() has been renamed to .getNormal().`

Also for `area()` and `midpoint()`.

Due to issues with ES6 modules / three inclusion, it was necessary in this case for me to copy the examples, and work on them locally. Ie. 
`import * as THREE from 'three';`

But with the above warning, the problem seems to be:
    `triangle.normal(this.normal);`
    `triangle.midpoint(this.midpoint);`

In QuickHull. Eq. when the example was designed these were used as setters. 

Are there equivalent setters in the latest build? I can't find them from the doc.

##### Three.js version

- [ ] Dev
- [x] r92
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
These methods were renamed with, see #13549

**Comment by maurocolella** [comment]
Ok, thank you. In other words, in order to set, say, the midpoint on a
triangle, I should use `getMidpoint`?

**Comment by Mugen87** [comment]
No. `getMidpoint()` calculates the midpoint of the triangle and stores the results in the given target vector.

**Comment by maurocolella** [comment]
Ok. Thank you for the clarification. Should the examples get an update or
otherwise be added to the core api (as `ext` or anything to that effect)?

As it stands it's a bit confusing.

**Comment by Mugen87** [comment]
I don get a warning with this example: https://threejs.org/examples/#webgl_geometry_convex

**Comment by maurocolella** [comment]
Ok. Well I can't import the examples from the npm package (in `import`
syntax) because THREE is locally scoped, and it's not imported in the
examples.

**Comment by Mugen87** [comment]
The examples and the build version of `three.js` should match in order to avoid such warnings.

**Comment by Mugen87** [comment]
see #9562
