### ISSUE TITLE
Material.toJSON missing serialization of polygonOffset, polygonOffsetFactor, polygonOffsetUnits

### ISSUE THREAD

**Issue by bGute** [mrdoob/three.js#14070]
##### Description of the problem
The .toJSON function of the [Material](https://github.com/mrdoob/three.js/blob/2f2e5f73181e7e3e1a845ab5d9c67192cb1e16e4/src/materials/Material.js#L136) class dose not consider polygonOffset, polygonOffsetFactor and polygonOffsetUnit, but the [MaterialLoader](https://github.com/mrdoob/three.js/blob/2f2e5f73181e7e3e1a845ab5d9c67192cb1e16e4/src/loaders/MaterialLoader.js#L92) class is considering them.
##### Three.js version
- [x] r92
##### Browser
- [x] All of them
##### OS
- [x] All of them

Related: #6254

**Comment by Mugen87** [comment]
Would you like to do a PR? It should be an easy change.

**Comment by bGute** [comment]
PR is now available!

**Comment by gero3** [comment]
done I guess
