### ISSUE TITLE
Uncaught SyntaxError: Unexpected token { in ObjectLoader.js:1

### ISSUE THREAD

**Issue by SreyPichh** [mrdoob/three.js#14074]
I am new to three.js and I am trying to load an object which rendered from blender in json format but it says Uncaught SyntaxError: Unexpected token {  in ObjectLoader.js:1 

and also another error 
Uncaught TypeError: Cannot read property 'type' of undefined
    at ff.parseObject (three.min.js:755)
    at ff.parse (three.min.js:745)
    at Object.onLoad (three.min.js:744)
    at XMLHttpRequest.<anonymous> (three.min.js:650)

this is from console, 
please help, thank you!

**Comment by Mugen87** [comment]
Please use stackoverflow or the [forum](https://discourse.threejs.org/) for help requests. 

Also provide the Blend and JSON file in your post.
