### ISSUE TITLE
Skinned mesh with normal map lighting distortions

### ISSUE THREAD

**Issue by madisjanno** [mrdoob/three.js#14080]
##### Description of the problem

I have a flat mesh with skeletal animations and a normal map. When bones are rotated from the default position and alter the faces, the normals from the map seem to get distorted creating visible edges between triangles. 

This occurs with both MeshStandardMaterial and MeshPhongMaterial.

Live preview: https://madisjanno.github.io/ProceduralCreatures/
![distorted](https://user-images.githubusercontent.com/17701214/40180934-9f7bc752-59f0-11e8-8aa0-8d05d0d6a7f5.png)

##### Three.js version

- [x] r87
- [x] dev

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Can you provide a version without a normal map applied?

**Comment by madisjanno** [comment]
![distorted2](https://user-images.githubusercontent.com/17701214/40230443-2ab8e0c0-5aa0-11e8-8008-975a3a39e9f4.png)
Without the normal map, all normals point towards (0,0,1). It's flat shaded.

I tried setting the normals to (0,1,0)
![image](https://user-images.githubusercontent.com/17701214/40231295-4d8a0892-5aa3-11e8-950a-81d428abcc8c.png)
There are no lighting discontinuities.

A similar setup with a normal map pointing towards (0,1,0)
![image](https://user-images.githubusercontent.com/17701214/40231240-fe915fce-5aa2-11e8-8e75-0b998a3323c9.png)

**Comment by WestLangley** [comment]
Sorry, we are not going to debug your app. You will need to provide a simple example.

Try applying your normal map to a tessellated `PlaneGeometry`.

**Comment by madisjanno** [comment]
I put together a much shorter example here: https://jsfiddle.net/1d1hafg2/

**Comment by makc** [comment]
it's almost as if material.shading is set to THREE.FlatShading by default. do we even still have this shading property?

**Comment by Mugen87** [comment]
@makc It's [Material.flatShading](https://threejs.org/docs/#api/materials/Material.flatShading) now.

**Comment by Mugen87** [comment]
@makc It's [Material.flatShading](https://threejs.org/docs/#api/materials/Material.flatShading) now.

**Comment by makc** [comment]
@Mugen87 setting that to `true` nukes the material entirely https://jsfiddle.net/rv54moep/2/

**Comment by pailhead** [comment]
You may not be able to render normal maps with three.js the way you want to. Three does no averaging of the tangents so i think for the purposes of normal mapping it is as if you had `FlatShading` always set.

**Comment by madisjanno** [comment]
>This is not a bug, this is a feature.

What is the upside of this design?

**Comment by pailhead** [comment]
I'm not sure i'm not aware of any, i hope others pitch in.  

It's probably not a lot of code, and it all happens in the shader so it's somewhat self contained. This was probably the least amount of effort to make the statement `three.js can render normal maps` valid. It's hard to challenge that, but it's definitely limited in its usefulness.

**Comment by pailhead** [comment]
Some upsides I thought of:

1. You don’t need to provide any extra tangent information. (Saves some memory and such), makes it simple.

2. It works really well on THREE.PlaneGeometry

**Comment by pailhead** [comment]
I think I need to correct myself, I don’t actually quite fully understand how this breaks down but the lee head looks decent. But it’s worth investigating and writing up some conclusions. It depends a lot on the normal map.

**Comment by WestLangley** [comment]
@madisjanno Your normal map is specifying normals which are tangent to the surface.

Closing. You can reopen if you can clearly demonstrate a three.js bug.
