### ISSUE TITLE
How to use CanvasRenderer in Angular4 Typescript

### ISSUE THREAD

**Issue by ngunhaSO** [mrdoob/three.js#14088]
##### Description of the problem
I follow the tutorial here https://threejs.org/examples/?q=particle#canvas_particles_waves to create waving particles. However, this tutorial requires the library CanvasRenderer under threejs/examples/js/canvas. The tutorial works with angular1 though.

How do I use CanvasRenderer() with angular 4 typescript? 

Here is my package.json

angular/animations: "5.2.10",
angular/common: "5.2.10",
angular/compiler: "5.2.10",
angular/compiler-cli: "5.2.10",
angular/core: "5.2.10",
angular/forms: "5.2.10",
angular/http: "5.2.10",
angular/platform-browser: "5.2.10",
angular/platform-browser-dynamic: "5.2.10",
ionic-native/core: "4.7.0",
ionic-native/splash-screen: "4.7.0",
ionic-native/status-bar: "4.7.0",
ionic/storage: "2.1.3",
ionic-angular: "3.9.2",
ionicons: "3.0.0",
rxjs: "5.5.10",
sw-toolbox: "3.6.0",
three: "^0.92.0",
three-canvas-renderer: "^2.0.0",
zone.js: "0.8.26"

**Comment by Mugen87** [comment]
Please use stackoverflow or the [forum](https://discourse.threejs.org/) for help requests.
