### ISSUE TITLE
Eye separation setting needs to be added.

### ISSUE THREAD

**Issue by Triuman** [mrdoob/three.js#14090]
I am using the webvr_video.html example in my project. The videos I am using are stereoscopic. So I do not need eye separation which actually cause me to see sphere geometry in 3D. I want both eye cameras at the same position. Is there a way to do that?

The example I am using:
[https://github.com/mrdoob/three.js/blob/master/examples/webvr_video.html](url)

This example creates a huge sphere to minimize eye separation effect but it is still seen.

**Comment by mkeblx** [comment]
Eye separation would still be not needed whether stereo or mono. One method can try is to parent camera, and set scale of parent to a suitably small value, same effect of making sphere larger.
