### ISSUE TITLE
Failed To Building Web Page ThreeJs and React

### ISSUE THREAD

**Issue by GitHub1396** [mrdoob/three.js#14106]
Dear All,
I am building a react app with threejs. All js files needed to demonstrate 3D file is excluded from react and located inside index.html file as follows:

<script type="text/javascript" src="%PUBLIC_URL%/treejs/js/three.js"></script>
    
    <script type="text/javascript" src="%PUBLIC_URL%/treejs/js/CanvasRenderer.js"></script>
    <script type="text/javascript" src="%PUBLIC_URL%/treejs/js/OrbitControls.js"></script>
    <script type="text/javascript" src="%PUBLIC_URL%/treejs/js/postprocessing/EffectComposer.js"></script>
    <script type="text/javascript" src="%PUBLIC_URL%/treejs/js/postprocessing/RenderPass.js"></script>
    <script type="text/javascript" src="%PUBLIC_URL%/treejs/js/postprocessing/ShaderPass.js"></script>
    <script type="text/javascript" src="%PUBLIC_URL%/treejs/js/postprocessing/MaskPass.js"></script>
    <script type="text/javascript" src="%PUBLIC_URL%/treejs/js/postprocessing/SSAOPass.js"></script>
    <script type="text/javascript" src="%PUBLIC_URL%/treejs/js/loaders/FBXLoader.js"></script>
    <script type="text/javascript" src="%PUBLIC_URL%/treejs/js/loaders/inflate.min.js"></script>
    <script type="text/javascript" src="%PUBLIC_URL%/treejs/js/shaders/SSAOShader.js"></script>
    <script type="text/javascript" src="%PUBLIC_URL%/treejs/js/shaders/CopyShader.js"></script>
    <script type="text/javascript" src="%PUBLIC_URL%/treejs/js/shaders/CopyShader.js"></script>
    
    <script type="text/javascript" src="%PUBLIC_URL%/treejs/js/app.js"></script>

All things work perfectly while using local node server (npm start ... ).
However, when I build them for publishing in a web and uploading built files, only blank page is shown on the website!

Would you please give me some advice?

Best Regards

**Comment by makc** [comment]
yeah, open the console (F12), check the error messages

**Comment by GitHub1396** [comment]
I opened.
relevant canvas is created successfully. However, nothing 3D is shown in it.

**Comment by makc** [comment]
oh maybe the model file did not make it into your build so it fails to load. check network tab

**Comment by GitHub1396** [comment]
I have checked. The is status for fbx file is "404 Not Found"

**Comment by GitHub1396** [comment]
How I can fix this?
The fbx file exist in the relevant path!

**Comment by makc** [comment]
well 404 says it does not.

**Comment by makc** [comment]
I guess I will spend all of my remaining mana on telepathy spell :) You probably do not 'require' the model path, do you.

**Comment by GitHub1396** [comment]
I put this file in the same location of index.html and address it in js file. however, the problem still exists.

**Comment by makc** [comment]
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-images-fonts-and-files
