### ISSUE TITLE
Texture.dispose not work

### ISSUE THREAD

**Issue by Jad2wizard** [mrdoob/three.js#14109]
##### Description of the problem
Hi, I'm a beginner of WebGL and Three.js. I am trying to create an Earth on WebApp similar to the Google Earth. 
I found the function **Texture.dispose not work** when I update the Texture of Earth Mesh. Because the Texture is also visible, and **the memory is increasing** due to the new Texture's images loaded.
```
const canvas = document.createElement('canvas');  //canvas of the new Texture
drawCanvas(northLatitude, eastLongitude, southLatitude, westLongitude, zoom, canvas).then(() => {
    const nextTexture = new THREE.CanvasTexture(canvas); 
    nextTexture.gnerateMipmaps = false;
    earth.material.uniforms.texture.value.dispose();
    earth.material.uniforms.texture.value = nextTexture;
})
```
This code doesn't work, and the memory increase each time I update the texture.

I have to replace the texture.image with an empty canvas before invoking texture.dispose. The last canvas can be destroyed and the memory discreased.
```
const canvas = document.createElement('canvas');  //canvas of the new Texture
drawCanvas(northLatitude, eastLongitude, southLatitude, westLongitude, zoom, canvas).then(() => {
    const nextTexture = new THREE.CanvasTexture(canvas); 
    nextTexture.gnerateMipmaps = false;
    earth.material.uniforms.texture.image = document.createElement('canvas'); //
    earth.material.uniforms.texture.value.dispose();
    earth.material.uniforms.texture.value = nextTexture;
})
```

Why texture.dispose don't destroy the image of it?
##### Three.js version

- [ ] Dev
- [x] r92
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by IceFrozen** [comment]
same to me 

window
chrome latest version（32bit）
Integrated graphics  

the memory of gpu in task manager (chrome) keep growing until the words "Rats! WebGL hit a snag." occured

**Comment by Jad2wizard** [comment]
I change my code to
```
const canvas = document.createElement('canvas');  //canvas of the new Texture
drawCanvas(northLatitude, eastLongitude, southLatitude, westLongitude, zoom, canvas).then(() => {
    const nextTexture = new THREE.CanvasTexture(canvas); 
    const lastTexture  = earth.material.uniforms.texture.value;
    nextTexture.gnerateMipmaps = false;
    setTimeout(() => {
        lastTexture.dispose();
    }, 3000);
    earth.material.uniforms.texture.value = nextTexture;
})
```
And I found the memory increase about 90MB immediately and dicrease 50MB 3 seconds later. So memory increase about (90MB - 50MB) = 40MB each time updating the texture.

**Comment by IceFrozen** [comment]
@Jad2wizard  do u have a solution?

**Comment by Jad2wizard** [comment]
@IceFrozen I am reading threejs code.......

**Comment by IceFrozen** [comment]
@Jad2wizard  me too , tell me if you got sth userful

**Comment by Jad2wizard** [comment]
@IceFrozen OK

**Comment by makc** [comment]
why THREE.CanvasTexture and not just THREE.Texture

**Comment by makc** [comment]
oh look #11378
