### ISSUE TITLE
Need a way to scale eye parameter width/height

### ISSUE THREAD

**Issue by joshpatt2** [mrdoob/three.js#14113]
Right now the VrManager is doing:

			var eyeParameters = device.getEyeParameters( 'left' );
			var renderWidth = eyeParameters.renderWidth;
			var renderHeight = eyeParameters.renderHeight;

			currentPixelRatio = renderer.getPixelRatio();
			currentSize = renderer.getSize();

			renderer.setDrawingBufferSize( renderWidth * 2, renderHeight, 1 );

The problem is some browser send smaller width/heights then resolution (Such as Oculus Browser), causing image to not be as crisp as possible.

- [ ] Dev
- [ ] r92
- [ ] ...

##### Browser

Oculus browser

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
Fixed via #14115
