### ISSUE TITLE
List all built-in GLSL functions in ShaderMaterial Doc

### ISSUE THREAD

**Issue by atul-mourya** [mrdoob/three.js#14118]
Hi,
I think it would be great to add list of all the available built-in GLSL functions in the `ShaderMaterial ` docs. 
This can be very useful when creating a custom shader.

This will certainly add more value to the documentation and will avoid confusion while searching functions elsewhere and interpreting it for threejs.

Thanks Team.

**Comment by makc** [comment]
here's easy way to do it: https://github.com/cbaggers/glsl-spec/blob/master/functions.json

**Comment by chem-g-gman** [comment]
How about just link to the WebGL Reference Card?

Last 2 pages cover all of GLSL

https://www.khronos.org/files/webgl/webgl-reference-card-1_0.pdf

**Comment by greggman** [comment]
How about just link to the WebGL Reference Card?

Last 2 pages cover all of GLSL

https://www.khronos.org/files/webgl/webgl-reference-card-1_0.pdf

Unlike the list above they also tersely document what most of them do

**Comment by makc** [comment]
then you want to link to page 4 directly: https://www.khronos.org/files/webgl/webgl-reference-card-1_0.pdf#page4

**Comment by atul-mourya** [comment]
Sounds very practical. Reference card are though very minimalist,  but would serve the purpose very well.

**Comment by Mugen87** [comment]
Yeah, I think referring to the existing WebGL Reference Card makes more sense than creating a new doc page.

Maybe a good place for this resource would be: https://threejs.org/docs/#manual/introduction/Useful-links

**Comment by atul-mourya** [comment]
Certainly, adding it into Useful link will keep the resources at one place. 
But, I would prefer it to see within the same **ShaderMaterial Doc**.

Something like this:

![capture](https://user-images.githubusercontent.com/16312255/40493378-3d487eb8-5f90-11e8-96fd-442035cc56d6.JPG)

**Comment by Mugen87** [comment]
I think that is somewhat misleading. The section "Built-in attributes and uniforms" refers to program entities provided by `three.js`. The new section "Built-in functions"  would refer to entities provided by GLSL instead. I (and maybe other users) would expect GLSL functions defined by `three.js`.

Against this backdrop, `Useful Links` seems more appropriate to me.
