### ISSUE TITLE
BGR DataTexture support

### ISSUE THREAD

**Issue by stormtroopa** [mrdoob/three.js#14120]
I like to put BGR image data into a DataTexture. The PixelFormat enum doesn't know this format yet, but webGL does.
Would it be possible to extend the WebGLUtils accordingly?

So I can call: new THREE.DataTexture( data, w, h, THREE.BGRFormat);

**Comment by Mugen87** [comment]
What is `BGR`? And on what `internalformat` are you referring to?

https://developer.mozilla.org/de/docs/Web/API/WebGLRenderingContext/texImage2D

**Comment by makc** [comment]
[Bulgaria ISO 3166-1 code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#Officially_assigned_code_elements)

**Comment by CaptainCoding** [comment]
I think swizzling is not supported in WebGL.
https://www.g-truc.net/post-0734.html
what means "TEXTURE_SWIZZLE_* enum values are removed from the WebGL 2.0 API" ?
see https://www.khronos.org/registry/webgl/specs/latest/2.0/#5.20

**Comment by Mugen87** [comment]
The document says:

> Unfortunately, neither WebGL 1.0 or WebGL 2.0 support texture swizzle due to performance issue of implementation such feature on top of Direct3D which doesn't have any equivalent functionality.
