### ISSUE TITLE
`Raycaster.setFromCamera` Error in OrthographicCamera.

### ISSUE THREAD

**Issue by FishOrBear** [mrdoob/three.js#14128]
https://github.com/mrdoob/three.js/blob/dev/src/core/Raycaster.js#L85:78

```
if ( ( camera && camera.isOrthographicCamera ) ) {
	this.ray.origin.set( coords.x, coords.y, ( camera.near + camera.far ) / ( camera.near - camera.far ) ).unproject( camera ); // set origin in plane of camera
	this.ray.direction.set( 0, 0, - 1 ).transformDirection( camera.matrixWorld );
}
```

when
`
camera.near + camera.far  === 0
`

Ray initialization error.

I think the code should be
```
if ( ( camera && camera.isOrthographicCamera ) ) {
	this.ray.origin.set( coords.x, coords.y, -1 ).unproject( camera ); // set origin in plane of camera
	this.ray.direction.set( 0, 0, - 1 ).transformDirection( camera.matrixWorld );
}
```

Do not know if my understanding is wrong.

(sorry,My English is not good, these are from Google Translate.)

**Comment by WestLangley** [comment]
See https://stackoverflow.com/questions/17558085/three-js-orthographic-camera/17567292#17567292

Also https://threejs.org/docs/#api/cameras/OrthographicCamera

`near` should be greater than or equal to zero, otherwise, objects behind the camera will be rendered.

**Comment by FishOrBear** [comment]
@WestLangley 

Emmmm, I want to render the object behind the camera, so my near negative.

It seems that doing `unproject` after z is set to -1 will not cause other errors, and the code is simpler?

**Comment by WestLangley** [comment]
Also see #9098.

**Comment by FishOrBear** [comment]
@WestLangley 
I think the distance returned should be the distance from the object to the observer's screen, not the camera's distance, because the camera's range has actually shown the object behind the camera.

**Comment by WestLangley** [comment]
Why are you setting the near plane to be negative and rendering objects behind the camera?

**Comment by FishOrBear** [comment]
In CAD software, a general orthogonal camera will display all the ranges.

If I set a negative plane, then I can ignore the position of the camera.

**Comment by makc** [comment]
What if you exclude the object from culling by the camera, then camera's near will not not matter? https://threejs.org/docs/#api/core/Object3D.frustumCulled

**Comment by WestLangley** [comment]
Currently, in three.js, `near` is a _distance_, and should be positive (non negative for an `OrthographicCamera`). That keeps the frustum in front of the camera.

So, the real question is, should we change that policy and officially support negative distances for `near` for `OrthographicCamera`. This would render objects behind the camera, too.

Imagine if the user places a `PointLight` at the camera location. Objects behind the camera would be rendered, and they would be backlit.

**Comment by Mugen87** [comment]
AFAIK, Unity does not allow negative values for `near`. I would prefer a policy similar to other popular engines.

**Comment by WestLangley** [comment]
Closing. three.js only supports non-negative values for the near plane.
