### ISSUE TITLE
[Feature request] Normal map in object space

### ISSUE THREAD

**Issue by Julien-Arlandis** [mrdoob/three.js#14139]
##### Description of the feature

Object space is the local 3D space of the object. Up is always up and left is always left. It is a uniform space that you understand really well because that is what the world is really like. Tangent space, on the other hand, is best thought of as surface space. In tangent space, up is always away from the surface (in other words, along the normal).

Apparently, Three.js only supports tangent space for normal space textures, so it will be very fun to supports object space too.

**Comment by WestLangley** [comment]
Can you please explain your use case -- and need for this feature -- in more detail?

**Comment by Ben-Mack** [comment]
Yes, Object-space normal map is especially helpful on resolving normal map seams problems on mesh with non-tilling normal map like game character or 3D scan model.

Please take a look at this issue where the use case and pros is explained very detailed: https://github.com/KhronosGroup/glTF/issues/1284

**Comment by Julien-Arlandis** [comment]
Thanks for your answer, I will illustrate my need by an example.
Compare the rendering of the same generated map with normal map in world space coordinates : 
-with Sketchfab : https://sketchfab.com/models/387eb203b5fb4349b83fb83beb038e41
-with Three.js : http://pf-01.lab.parisdescartes.fr:1357/mapRender/?ref=savoie
We can see a discontinuity of faces when we use the wrong coordinate system. In my case it's very difficult to generate normal map in space tangent because of a specific geographic modelisation (2.5D).

**Comment by bhouston** [comment]
Object space normal maps are moderately common in 3D.  It would be a useful feature for sure.

**Comment by WestLangley** [comment]
Proposed API for object-space normal map support:
```javascript
material.normalMap = myNormalMap;
material.objectSpaceNormalMap = true; // default false, implies a tangent-space normal map
```
Or
```javascript
material.normalMap = myNormalMap;
material.normalMapType = THREE.ObjectSpaceNormalMapType; // default THREE.TangentSpaceNormalMapType
```
I prefer the second one, even though there are only two options in this case.

Other options,
```javascript
material.normalMapType = THREE.ObjectSpaceType; // default THREE.TangentSpaceType
```

```javascript
material.normalMapType = THREE.ObjectSpaceNormalMap; // default THREE.TangentSpaceNormalMap
```

/ping @mrdoob

**Comment by Julien-Arlandis** [comment]
Thanks for your propose.
I prefer the second option because it allows multiple type supports.

**Comment by bhouston** [comment]
@WestLangley I think the names should be:

```
THREE.ObjectSpace
THREE.TangentSpace
```

The reason is that there are other spaces that could be useful for specification elsewhere and then we do not have to have duplicate constants.  Other spaces I can think of are:

```
THREE.WorldSpace
THREE.ViewSpace / Camera but without perspective transform
THREE.LightSpace
THREE.ScreenSpace
THREE.CustomSpace / you specify a matrix that defines the space.
THREE.TextureSpace / a UV space.
```

Most of these spaces are basically just matrix selection, except for screen space which includes a perspective transform.  I do not think these should be implemented now, but if we follow this naming convention, we could.

I think that having space specifiers is sort of cool.  I am sure there are at least a couple more than I am missing.

**Comment by WestLangley** [comment]
@bhouston 

To clarify, I assume you are suggesting a different property name, too:
```javascript
material.normalMap = myNormalMap;
material.normalMapSpace = THREE.ObjectSpace; // default THREE.TangentSpace
```

>I think that having space specifiers is sort of cool.

I am not sure I see a use case for the others space types...

**Comment by bhouston** [comment]
> I am not sure I see a use case for the others space types...

Often you want to apply a offset to an object and you want to specify in which space that offset is done: ViewSpace, ObjectSpace (local space) or WorldSpace.  Or if you want to rotate an object, you may want to specify the coordinate system.

Basically these spaces can be used to show a transform widget in a specific coordinate system on an object and then you move it there.  There is already some of this in the ThreeJS editor as well as the Clara.io editor.  (In the ThreeJS editor remember there is a [ ] local check box that is switching between THREE.WorldSpace and THREE.ObjectSpace for the manipulators.)

Also I like being able to ask a node in the scene graph to give its its matrix in any of these spaces.  If you have this type of accessor on the scene graph, implementing manipulators that are flexible in which coordiante system they use becomes easy.

```
node.getTransform( THREE.ViewSpace, camera );
node.getTransform( THREE.ObjectSpace );
node.getTransform( THREE.WorldSpace );
```

This is a very useful generalization that other engines do.

**Comment by bhouston** [comment]
@Ben-Mack can you create a simple example for @WestLangley ?  It would be helpful as you know how to use xNormal.

**Comment by Ben-Mack** [comment]
@WestLangley I've created object space normal map based on [Ten24 Sample Scan](http://ten24.info/sample-scan/)
[Object Space Normal map sample model.zip](https://github.com/mrdoob/three.js/files/2076314/Object.Space.Normal.map.sample.model.zip)

**Comment by Julien-Arlandis** [comment]
Thanks for the model.
It's missing mtl file? 
So, do you know how to tell the mtl file which geometry was used for the normal map?

**Comment by WestLangley** [comment]
@Ben-Mack Is your gltf Nefertiti model with the two normal maps available in the public domain for use as a three.js example? It is reasonably-sized, which is a plus.

**Comment by mlimper** [comment]
You can use the model under creative commons for non-commercial purposes (CC BY-NC), please acknowledge the lab that digitized it like this:

> 3D scan of a copy of the Nefertiti Bust, digitized by Fraunhofer IGD, Competence Center Cultural Heritage Digitization, http://www.cultlab3d.de/

Would be cool to see this as a three.js example!
Many thanks, and keep up the great work!

**Comment by WestLangley** [comment]
@mlimper Thank you!

@mrdoob We can create a separate object-space normal example using the [Nefertiti model](https://github.com/BabylonJS/Babylon.js/pull/3706), or alternatively, we can use the model and its OS-normal map as part of the glTF example. Which would you prefer?

**Comment by donmccurdy** [comment]
OS normal maps are [technically not "valid" glTF yet](https://github.com/KhronosGroup/glTF/issues/1284), even though it's certainly possible to make examples like this. So ideally this should be separate from the glTF examples for now.
