### ISSUE TITLE
Object3D.getWorld* Performance

### ISSUE THREAD

**Issue by 7frank** [mrdoob/three.js#14135]
Hi there,

I'm currently relying on _getWorldPosition()_, _getWorldQuaternion()_, etc. to determine the absolute position of elements within a scene.  Mostly to calculate distances and orientations. I've encountered mayor performance issues this way. This could be tracked back primarily to _updateWorldMatrix_(true). It seems that the current implementation does force (unnecessary?) recursive recalculation of all _matrixWorld_ objects this way for all _children_ everytime one of the _getWorld_* methods gets called. 
This seems redundant from my perspective. 

For now I've removed the _updateWorldMatrix_()  and rely on the _worldMatrix_ being generated automatically beforehand.

##### Three.js version
- [x] r90

##### Browser
- [x] All of them

##### OS
- [x] Windows

**Comment by donmccurdy** [comment]
An alternative that will not call `updateWorldMatrix()` for position is 

```js
var position = new THREE.Vector3().copy(object.position);
object.localToWorld(position);

console.log(position);
```

I'm not aware of a concise alternative for rotation and scale. Related: https://github.com/mrdoob/three.js/issues/13704

**Comment by WestLangley** [comment]
This is part of the long-standing problem: `updateMatrixWorld()` does not do what the name says it does.

See https://github.com/mrdoob/three.js/pull/6448#issuecomment-95624064, for example.

**Comment by Mugen87** [comment]
The situation of this issue has changed a bit. `Object3D.getWorld*()` methods now use `Object3D.updateWorldMatrix()` which means the world matrix is now computed in the _correct_ way. That is updating the matrices starting from the root node down the hierarchy up to the current node. Children are not updated anymore. This change in behavior might solve performance issues in certain use cases but could also introduce performance issues in other use cases. However, the methods always compute the correct result now.

If you still experience performance problems with those methods please share your feedback in #20220. In this issue, the general design and potential performance limitations in context of world matrix computation are discussed.

Merging this issue into #20220.
