### ISSUE TITLE
refraction is broken in MeshStandardMaterial?

### ISSUE THREAD

**Issue by robertoranon** [mrdoob/three.js#14142]
##### Description of the problem

In the webgl_materials_cubemap_refraction example, I tried to change the materials from MeshPhong to MeshStandard, and the refraction effect was gone (the statue on the left still uses the MeshPhongMaterial, the other two use a MeshStandardMaterial): 

<img width="1177" alt="screen shot 2018-05-25 at 16 16 35" src="https://user-images.githubusercontent.com/6480367/40549196-1e45ba9c-6037-11e8-95b5-6194876c35f7.png">

Is there something I am missing to enable refraction? from the documentation, it doesn't look so.

##### Three.js version

- [X] r92

##### Browser

- [X] Chrome
- [X] Safari

##### OS

- [X] macOS

**Comment by WestLangley** [comment]
`MeshStandardMaterial` is a physically-based (PBR) material. Refraction, as implemented in `MeshPhongMaterial` is not a PBR technique. Granted, it is reasonably convincing.

In `MeshStandardMaterial`, if you set `material.metalness = 1;` and  `material.roughness = 0;`  you can achieve an effect you are looking for, but I am not aware of any metals that are transparent. I do not think support for refraction was intended.

You can also study the work-around used in http://threejs.org/examples/webgl_materials_reflectivity.html.

**Comment by robertoranon** [comment]
Thanks a lot! I'll try to come up with an update to the documentation to explain this and submit a PR, if you are interested

**Comment by WestLangley** [comment]
It might be more appropriate to revisit the code, instead, and see if changes are warranted.

**Comment by ManishJu** [comment]
I think refractionRatio should be removed from the documentation of MeshStandardMaterial here:
https://threejs.org/docs/#api/en/materials/MeshStandardMaterial

**Comment by mrdoob** [comment]
@ManishJu Would you like to do a PR with the fix?

**Comment by ManishJu** [comment]
The solution is to set the correct texture mapping constant. For me it was cubeUVRefractionMapping.

**Comment by Mugen87** [comment]
Related #19623
