### ISSUE TITLE
improve example page

### ISSUE THREAD

**Issue by HypnosNova** [mrdoob/three.js#14140]
I think the example page is too old and not convenient enough for learners to use.

What if we try to make pages like this: [https://www.threejs.org.cn/gallery/](https://www.threejs.org.cn/gallery/)
We can just make a simple online code editor, when people click a demo, we don't need to load the page in the iframe, we can ajax the code to the online editor and editor run the code. It‘’s a more convenient way to use. (And in this link, I use [ACE](https://ace.c9.io/) as a code editor and also provide common used three.js' key words hints)

**Comment by HypnosNova** [comment]
It looks like this:
![tim 20180525210347](https://user-images.githubusercontent.com/7953802/40545699-4e141854-605f-11e8-9caa-9a572c73e6cd.png)

**Comment by Mugen87** [comment]
A similar suggestion was discussed before. See https://github.com/mrdoob/three.js/issues/10481#issuecomment-274225768

**Comment by makc** [comment]
What about doing this as a part of threejs.org/editor

**Comment by WestLangley** [comment]
So, what is the management plan? Do we want to reimplement the examples page or not?

/ping @mrdoob Are you happy with what we have now or would you like to see the examples implemented differently?

**Comment by mrdoob** [comment]
I think I'm happy with what we currently have.
It definitely can be improved, but I wouldn't completely change it like what this PR proposes.

**Comment by WestLangley** [comment]
Thanks, @mrdoob. Closing, then.

**Comment by stla** [comment]
Hello,

 If you want to add an example, I made a nice app these days : [HopfApplication](https://github.com/stla/HopfApplication). It could be in the "ParametricGeometry" category.

**Comment by mrdoob** [comment]
@stla That looks pretty cool actually! Would you like to make a PR with the new example?

**Comment by stla** [comment]
Hello,

  Ok. In which "folder" should I put my code?

**Comment by mrdoob** [comment]
Just try to follow the current structure as much as you can.
In the PR itself we can make changes if needed.
