### ISSUE TITLE
[Feature Request] 3ds exporter 

### ISSUE THREAD

**Issue by mananaBoyJorge** [mrdoob/three.js#14159]
Is the 3ds exporter deprecated because I am unable to find it in the repository.
Is it possible to build to a 3ds exporter?

**Comment by looeee** [comment]
Yes, it was removed in #12930. If you still need it you can find the code from older releases [here](https://github.com/mrdoob/three.js/releases), however it's strongly recommended to use FBX format instead. 

If you need more help with this please use the [forum](https://discourse.threejs.org/).

**Comment by mananaBoyJorge** [comment]
Thank you for the response looee.

I would be more than happy to use FBX exporter but I don't think even FBX exporter is there. 
Here's the problem, I get FBX / 3DS file from a tool, load it using one of the loaders, modify a few things and then I want to export it back as FBX / 3DS so that the tool can consume it. 

Any link to any of the exporters will be helpful. Thank you.

**Comment by donmccurdy** [comment]
@mananaBoyJorge there are two types of exporters in this repo — exporters to the JSON format from modeling tools (we previously had 3DS Max exporter that exported JSON) and exporters to different formats from the browser. I assume you're asking about the latter, right? Equivalent to OBJExporter, GLTFExporter, and PLYExporter? No FBX or 3DS equivalent exists that I know of sorry.

**Comment by Mugen87** [comment]
https://discourse.threejs.org/t/how-do-i-export-a-modified-scene-to-3ds-format/2942

**Comment by sunag** [comment]
https://github.com/sunag/sea3d/tree/master/Exporter/3ds%20Max
