### ISSUE TITLE
Bump mapping artifacts when flatShading is true

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#14152]
The artifacts appear to have been introduced with https://github.com/mrdoob/three.js/commit/73e3b92f42b36477c8cce9d30b12156ee15bf21b, which was a workaround for an Adreno bug posted in #9988.

Reproducible be setting:
```javascript
material.flatShading = true;
```
in http://threejs.org/examples/webgl_materials_bumpmap.html.

Reverting the commit fixes it.

![screen shot 2018-05-26 at 6 21 40 pm](https://user-images.githubusercontent.com/1000017/40580730-111c939a-6113-11e8-98b0-1455117b49ff.png)

##### Three.js version

- [x] Dev
- [x] r.86-r92

##### Browser

- [x] Chrome/Safari

##### OS

- [x] macOS
- [ works ok ] iOS

**Comment by makc** [comment]
mac os screenshot from here:

![screen shot 2018-06-03 at 2 59 55](https://user-images.githubusercontent.com/242577/40881850-49de2fb4-66da-11e8-89c4-e58fdba8e35c.png)

**Comment by mrdoob** [comment]
I can't reproduce here. What system are you on @WestLangley?

**Comment by WestLangley** [comment]
macOS, Chrome/Safari. 
It may be the old GPU: AMD Radeon HD 6750M 512 MB

This old code works:
```glsl
vec3 vSigmaX = dFdx( surf_pos );
vec3 vSigmaY = dFdy( surf_pos );
```

The new code causes artifacts as pictured above:
```glsl
vec3 vSigmaX = vec3( dFdx( surf_pos.x ), dFdx( surf_pos.y ), dFdx( surf_pos.z ) );
vec3 vSigmaY = vec3( dFdy( surf_pos.x ), dFdy( surf_pos.y ), dFdy( surf_pos.z ) );
```

.. and it is because of the z-component only:

```glsl
vec3 vSigmaX = dFdx( surf_pos ); // works
vec3 vSigmaY = dFdy( surf_pos );

vSigmaX.z = dFdx( surf_pos.z ); // artifacts
vSigmaY.z = dFdy( surf_pos.z );
```

**Comment by mrdoob** [comment]
Hmm, what version of MacOS? 🤔

**Comment by WestLangley** [comment]
macOS 10.13.5

**Comment by mrdoob** [comment]
Oh noes... Sounds like another driver bug.
Same issue in Firefox?

**Comment by WestLangley** [comment]
Yes. Same issue in Firefox.

**Comment by mrdoob** [comment]
I don't know what to do here... 😐

The right thing to do would be to create a reduced case and report it to Chrome, Apple and/or AMD. But I'm not sure they'd be fixing it...

**Comment by WestLangley** [comment]
Agreed. Closing.
