### ISSUE TITLE
Missing callbacks for parse function in JSONLoader

### ISSUE THREAD

**Issue by UstymUkhman** [mrdoob/three.js#14156]
Hi there! I just found out that `parse` function of `JSONLoader` doesn't have `onLoad` and `onError` callbacks like `GLTFLoader` (for example). Mine is just a suggestion for a feature that might be useful, especially if `parse` function is used in a Promise or to check if JSON file could be corrupted in any way.

I hope this will be helpfull.
(Love this project, by the way 😄)

##### Three.js version

- [ ] Dev
- [x] r92
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> JSON file could be corrupted in any way

The JSON is already parsed in the `load()` method. In general, `three.js` does not sanitize the input. So I'm not sure about the benefit of this suggestion.

**Comment by donmccurdy** [comment]
I don't think sanitizing the input is main question here, it's similar to https://github.com/mrdoob/three.js/issues/12942 in that the signatures of different loaders are inconsistent. `GLTFLoader.prototype.parse(file, path, onLoad, onError)` is different than `JSONLoader.prototype.parse(file, path)`. I guess JSONLoader returns before textures have loaded? I don't have a strong opinion, but would be OK with the change.

**Comment by UstymUkhman** [comment]
@donmccurdy Yes, the main point is about the inconsistency of different loaders in their parse functions (the number of parameters are different because of the `onLoad` and `onError` callbacks), so when using different loaders, one has to be careful not to call them in the same way.

'Cause let's say, I've settuped my code to parse different assets in the same way; so, when `onLoad` callback is called I resolve the `Promise` and can manage my mesh. Of course, in case of `JSONLoader` my `Promise` will never be solved so I have to parse my `.json` objects in a different way.

I actually had this issue and I agree: it's a bit stupid as real problem (that's why mine is just a suggestion), but the point is that different loaders are inconsistent. I suppose this is because `JSONLoader` is one of the oldest and its `parse` method has linear flow (no async functions); JSON file is parsed right after that method is called.

About 

> JSONLoader returns before textures have loaded

I'm not sure, but it's possible. The evidence of this could be this warning I had:

`WebGLRenderer: Texture marked for update but image is undefined`

immediately after calling `parse` method. `image` propriety of `Texture` is solved shortly after and it's initialized with a proper DOM element instead of `undefined`, so despite that warning, I don't think this could be a real issue here, unless you have a particular scenario...

Although, if JSONLoader actually returns before textures have loaded, this could be another reason to provide this loader with `onLoad` and `onError` callbacks.

**Comment by Mugen87** [comment]
> I guess JSONLoader returns before textures have loaded?

Yes, it works like that. I'm just a little bit surprised about the mentioned warning. This should not happen since `TextureLoader.load()` ensures that `texture.needsUpdate` is only set to `true` if the corresponding image has actually loaded. Only then the texture upload is executed by `WebGLRenderer`.

**Comment by Mugen87** [comment]
Unifying the interface and behavior of the loaders would be a great thing. One long-standing from my point of view is that some loaders `parse()` method only returns if all resources are loaded (`ObjectLoader`). Other loaders like `JSONLoader` or `ColladaLoader` return as soon as the geometry data are parsed. If you want to wait for all resources, you have to use `LoadingManager`.

**Comment by pailhead** [comment]
Could https://github.com/mrdoob/three.js/blob/dev/src/loaders/Loader.js be a part of this issue? `JSONLoader` for example doesn't extend from it, but uses it as some kind of material manager.

**Comment by WestLangley** [comment]
What is the status on this, please?

**Comment by mrdoob** [comment]
We're in the process of moving away from `JSONLoader` so better to leave it as it is.
