### ISSUE TITLE
Mesh.raycast does not sort intersections as the documentation states

### ISSUE THREAD

**Issue by cjamin** [mrdoob/three.js#14160]
The results are not sorted in close-to-far order. I can't seem to find anything in [the code ](https://github.com/mrdoob/three.js/blob/master/src/objects/Mesh.js) trying to sort the result.
Am I missing something?

**Comment by WestLangley** [comment]
Sorting is performed in `Raycaster.intersectObjects()` and `Raycaster.intersectObject()`.

**Comment by cjamin** [comment]
Oh, ok, I was looking at [the wrong place](https://github.com/mrdoob/three.js/blob/master/src/core/Raycaster.js#L44)!
It would nice if the documentation of `Mesh.raycast` could state explicitly that the result is not ordered. Thanks!

**Comment by amitlzkpa** [comment]
#16034 
Made a pull request. 
First PR here!

**Comment by looeee** [comment]
@amitlzkpa welcome aboard!
