### ISSUE TITLE
`verticesNeedUpdate = true` not works.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [mrdoob/three.js#14162]
See here: [codepen](https://codepen.io/zhengxiaoyao0716/pen/yEBPWg?editors=0010)
Notice the line #L45 and #L48.

![image](https://user-images.githubusercontent.com/12682063/40619631-651ab8e4-62c8-11e8-85b8-2498bdad81ca.png)

![image](https://user-images.githubusercontent.com/12682063/40619678-8f209a78-62c8-11e8-98aa-7f678609a1c5.png)

Core of the problem code:
``` javascript
    points.geometry.vertices = [
      new THREE.Vector3(-0.1, 0.1, 0),
      new THREE.Vector3(-0.1, -0.1, 0),
      new THREE.Vector3(0.1, -0.1, 0)
    ];
    // points.geometry.vertices.push(new THREE.Vector3(0.1, 0.1, 0)); // this works.
    setTimeout(() => {
        points.geometry.vertices.push(new THREE.Vector3(0.1, 0.1, 0));
        points.geometry.verticesNeedUpdate = true; // why not works?
    }, 0);
```

**Comment by WestLangley** [comment]
https://stackoverflow.com/questions/36699389/verticesneedupdate-in-three-js/36699654#36699654

**Comment by zhengxiaoyao0716** [comment]
![image](https://user-images.githubusercontent.com/12682063/40621022-b468d804-62cd-11e8-8416-e370d636f887.png)

**Comment by WestLangley** [comment]
You can't resize buffers. You can only change the contents of buffers.

https://stackoverflow.com/questions/31399856/drawing-a-line-with-three-js-dynamically/31411794#31411794

**Comment by zhengxiaoyao0716** [comment]
Thank you, that works well.
But maybe we can add those as notice item into the document?
I can't got this just from the document, it said that `To signal an update in this array, .verticesNeedUpdate needs to be set to true.` [Geometry.vertices](https://threejs.org/docs/index.html#api/core/Geometry.vertices)

**Comment by Mugen87** [comment]
Adding a note is a good idea. But i think I would prefer the following page, section `Geometry`:

https://threejs.org/docs/index.html#manual/introduction/How-to-update-things

**Comment by zhengxiaoyao0716** [comment]
@Mugen87 I found nothing different on that page:
![image](https://user-images.githubusercontent.com/12682063/40648573-5a937a8e-6361-11e8-9c9a-afb7e724e64a.png)
It said that, we set the flags to true, and the `Geometry` will be updated. But that didn't work unless I use `BufferGeometry` instead.

**Comment by Mugen87** [comment]
The documentation is unclear. It means when you update existing values. Doing stuff like adding new vertices does not work since the underlying buffers are fixed size.

**Comment by zhengxiaoyao0716** [comment]
Yeah, that's what I want to see on the document, `set flags to true` only works when you update existing values.

**Comment by Mugen87** [comment]
Feel free to make a PR :blush:
