### ISSUE TITLE
bad performance with batched rendering and AA on

### ISSUE THREAD

**Issue by sasmaster** [mrdoob/three.js#14167]
I am rendering a single mesh,which uses a a batched geometry from 5000-10000 primitives (sphere at the moment).

And already at 5000 + , my FPS drops from 60 to 30-40. Now,that;s a single draw call.I also have a grid and axis helpers,but that's it. What I do see is that if I disable anti-aliasing,the FPS jumps back to a steady 60 fps. I am not really aware how much GL  is different in terms of performance in Js,but as C++ GL developer it looks weird that MSAA has such an impact on the performance. Or THREE.js uses something else for AA?

My Code:
 ` 
window.onload = function (e) {

  var stats = new Stats();
  stats.showPanel(0);  
  document.body.appendChild(stats.dom);
  var mesh;
  var scene;
  var pickingScene;
  var cam;
  var renderer;
  var pickingRT;
  var controls;
  var pickingData = [];
  init();
  animate();
  function init() {

    scene = new THREE.Scene();
    cam = new THREE.PerspectiveCamera(50, window.innerWidth / window.innerHeight, 1, 15000);
    cam.position.z = 4000;
    renderer = new THREE.WebGLRenderer({ antialias: true });
    document.body.appendChild(renderer.domElement);

    renderer.setClearColor(0xcccccc, 1);
    renderer.setPixelRatio(window.devicePixelRatio);
    renderer.setSize(window.innerWidth, window.innerHeight);
    renderer.autoClear = false;

    //------------------   debug controls(dev only) -----------------//
    controls = new THREE.OrbitControls(cam);

    var grid = new THREE.GridHelper(2000, 20);
    grid.position.y = -150;
    scene.add(grid);

    var axesHelper = new THREE.AxesHelper(100);
    scene.add(axesHelper);

    //-----------------------------------------------------------------//

    var geometry = new THREE.Geometry();   

    var defaultMaterial = new THREE.MeshBasicMaterial({
      color: 0xffffff,
      vertexColors: THREE.VertexColors,
      flatShading: true
   });

    //generate 3d objects:

    var position = new THREE.Vector3();
    var rotation = new THREE.Euler();
    var scale = new THREE.Vector3();
    for (var i = 1; i < 8500; i++) { // start at 1 to avoid id of 0

      position.x = Math.random() * 12000 - 6000;
      position.y = Math.random() * 12000 - 6000;
      position.z = Math.random() * 12000 - 6000;
      //rotation.x = Math.random() * 2 * Math.PI;
      rotation.y = Math.random() * 2 * Math.PI;
      //rotation.z = Math.random() * 2 * Math.PI;
      scale.x = Math.random() * 200 + 100;
      scale.y = Math.random() * 200 + 100;
      scale.z = Math.random() * 200 + 100;

      //generate visible (aka real geoemtry)
      // give the geom's vertices a random color, to be displayed

      var geom = new THREE.SphereGeometry(1, 4, 3);
      var color = new THREE.Color(Math.random() * 0xffffff);
      applyVertexColors(geom, color);

      var cube = new THREE.Mesh(geom);
      cube.position.copy(position);
      cube.rotation.copy(rotation);
      cube.scale.copy(scale);
      cube.updateMatrix();
 
     geometry.merge(cube.geometry,cube.matrix);
 
    }//for

    var bufferGeometry = new THREE.BufferGeometry().fromGeometry( geometry );
     //create final batched meshes
    var drawnObject = new THREE.Mesh(bufferGeometry, defaultMaterial);
    scene.add(drawnObject);

  }

  function onWindowResize() {
    cam.aspect = window.innerWidth / window.innerHeight;
    cam.updateProjectionMatrix();
    renderer.setSize(window.innerWidth, window.innerHeight);
  }

  function animate() {
    stats.begin();
    controls.update();
    renderer.render(scene, cam);
    stats.end();
    requestAnimationFrame(animate);
  }
}

function applyVertexColors(g, c) {
   g.faces.forEach(function (f) {
    for (var j = 0; j < 3; j++) {
      f.vertexColors[j] = c;
    }
  });
}

 `

##### Three.js version

- [x ] 93dev
 
##### Browser
 
- [x ] Chrome
 

##### OS

 
- [ x] Windows
 

##### Hardware Requirements (graphics card, VR Device, ...)

 GTX 960M , Intel i7,16Gb RAM

**Comment by Mugen87** [comment]
>  Or THREE.js uses something else for AA?

No, if you pass `antialias: true` to the renderer, it uses the default MSAA of WebGL.

Please use the [forum](https://discourse.threejs.org/) or stackoverflow for performance related help questions.
