### ISSUE TITLE
FBX Loading Problem

### ISSUE THREAD

**Issue by Ouyang-Zhaoxing** [mrdoob/three.js#14173]
##### FBX Loading Problem on IphoneSE
In our project,IphoneSE has problems.It cannot load the FBX model.No other mobile device has such a problem.
We tried to open the official FBX loading example with IphoneSE and the loading failed.
##### Three.js version
- [x] r92
##### Browser
- [x] Safari
##### OS
- [x] iOS

**Comment by Mugen87** [comment]
Does it work with other browser than Safari? Besides, are there any error messages?

**Comment by donmccurdy** [comment]
And could you share the model or a demo? You can put ZIP files into GitHub comments.

**Comment by Ouyang-Zhaoxing** [comment]
@Mugen87 Other browsers do not work. It has no error message.

**Comment by Ouyang-Zhaoxing** [comment]
@donmccurdy I think you don't need our models and demos because it doesn't work in the examples provided on the official website.
https://threejs.org/examples/?q=fbx#webgl_loader_fbx

**Comment by donmccurdy** [comment]
Hm. That examples works for me (I also have an iPhone SE).

![0ff8b727-ca1c-456f-829b-b58c4339147e-7641-00000b34928f92a7](https://user-images.githubusercontent.com/1848368/40757970-dcfe961e-643f-11e8-8bd2-ff2eb75e88bd.gif)


Do you know the version of iOS?

**Comment by Ouyang-Zhaoxing** [comment]
Thank you for a serious answer. We have two IphoneSE. The IOS version is 9.3.3 and they all fail. I upgraded one of the devices, it is successfully loaded. I think this is Apple's problem : )
