### ISSUE TITLE
Box3.setFromObject() Does Not Work with New LineSegmentsGeometry

### ISSUE THREAD

**Issue by Bsheridan12** [mrdoob/three.js#14184]
When computing the bounding box on a Group using: 

`let bbox = new THREE.Box3().setFromObject(object3D);
let center = new THREE.Vector3();
bbox.getCenter(center);`

The positions of all verts within any fat line buffer are not taken into account.

This throws off the scale/translation of all shapes within that group causing them to shoot off into space rather than expand from a fixed point.

**Comment by WestLangley** [comment]
Right. "Fat lines" uses instancing, in which vertices are translated on the GPU -- not the CPU. So what you are observing is not unexpected.

Try using `lineSegmentsGeometry.computeBoundingBox()` in your application.

**Comment by Bsheridan12** [comment]
That does work for me but if possible I need to be able to translate thicklines as part of the Group to ensure all the different buffers remain stacked properly after scaling.

**Comment by Bsheridan12** [comment]
@WestLangley it looks like excluding lineSegmentsGeometry from Box3's function resolves my issue.

Within the traverse function 

`else if ( geometry.isBufferGeometry && !geometry.isLineSegmentsGeometry ) {...}`

Creating a separate else if for geometry.isLineSegmentsGeometry that uses the same code as bufferGeometry but instead sets attribute to `var attribute = geometry.attributes.instanceStart` also seems to have the same affect.

**Comment by Bsheridan12** [comment]
Yep, was able to just patch that function and get the desired results.

Ah I see. I thought that had been been fully integrated at this point.
It's been super helpful for our project though. Also love the new changes to it, we'd been putting off finding a solution to thick dashed lines and just today we saw you'd added support for that.

Thanks for taking the time to look at this and as always for all the work you put into three.js!

**Comment by WestLangley** [comment]
Thanks for pointing out the limitations. If `fat lines` are integrated into three.js, we will need to address these issues.
