### ISSUE TITLE
Document function translateX/Y/Z more accurately

### ISSUE THREAD

**Issue by haolly** [mrdoob/three.js#14185]
.translateX ( distance : Float ) : this
Translates object along x axis by distance units.

# .translateY ( distance : Float ) : this
Translates object along y axis by distance units.

# .translateZ ( distance : Float ) : this
Translates object along z axis by distance units.

Those three function all translate object in **local space**  , but it can be very easy to assum those function will translate in **world space**

**Comment by WestLangley** [comment]
Correct.  It should be:

    Translates object along x-axis in object space by distance units.

Would you like to file a PR and fix it?
