### ISSUE TITLE
converting buffergeometry to geometry need a lot of memory

### ISSUE THREAD

**Issue by tonifds** [mrdoob/three.js#14187]
converting loaded stl mesh from buffergeometry to geometry need a lot of memory.
how i can reduce memory  usage or get the mesh of intersection between a stl buffergeometry and a plane?

**Comment by Usnul** [comment]
Support question. Use support channels instead.

I do not recommend use of `Geometry` classes for the very reason that they require more memory, as well as the fact that they have worse runtime performance.
