### ISSUE TITLE
Is internally .matrixWorld is used?

### ISSUE THREAD

**Issue by nfyfamr** [mrdoob/three.js#14188]
I have two functions which difference is using clone of originObj.matrixWorld to multiply with 'transform' argument.
the first one does not work but second one does.
as far as I know the 'matrix' and 'matrixWorld' properties of object3d are newly calculated in every frame, more specifically in renderer.render().
So I thought that assigning arbitrary matrix to .matrix or .matrixWorld is worthless, cause it will be overwrited in rederer.render().
If my thought is right, following two functions are working well either.
But only second one does work.
What is misunderstanding I am?

```
	applyTransform(originObj, target, transform) {
		const newTransform = originObj.matrixWorld.multiply(transform);
			// decompose newTransformMatrix as position, rotation and scale
		const position = new THREE.Vector3();
		const quaternion = new THREE.Quaternion();
		const scale = new THREE.Vector3();
		newTransform.decompose(position, quaternion, scale);

		target.position.copy(position);
		target.quaternion.copy(quaternion);
		target.scale.copy(scale);
	}
```

```
	applyTransform(originObj, target, transform) {
		const newTransform = originObj.matrixWorld.clone().multiply(transform);
			// decompose newTransformMatrix as position, rotation and scale
		const position = new THREE.Vector3();
		const quaternion = new THREE.Quaternion();
		const scale = new THREE.Vector3();
		newTransform.decompose(position, quaternion, scale);

		target.position.copy(position);
		target.quaternion.copy(quaternion);
		target.scale.copy(scale);
	}
```

r90

**Comment by nfyfamr** [comment]
'doesn't work' means when I calling that function each frame, the value of newTransform is changed.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
