### ISSUE TITLE
Pixelated Fat Dashed Lines

### ISSUE THREAD

**Issue by Bsheridan12** [mrdoob/three.js#14197]
Fat dashed lines don't appear to be fully solid on my desktop.

![image](https://user-images.githubusercontent.com/8675651/40866437-3f62578a-65c3-11e8-9608-5c37ef889210.png)

I've tested this on two different laptops and fat dashed lines look great so it seems to be machine/browser specific.

I thought this might have been Z fighting but disabling depthTest and removing all other shapes from the scene made no improvement.

**Comment by WestLangley** [comment]
Very fat dashed lines can have artifacts if the points are too close together, but likely what you are seeing is a different issue.

There is not much that can be done, however, given the information you have provided.

**Comment by Bsheridan12** [comment]
Is there anything I can do to further investigate the issue?

**Comment by WestLangley** [comment]
You could specify the problematic browsers, OS, GPU, and devices.

You could provide a simple live link or jsfiddle if you feel it is informative.

**Comment by Bsheridan12** [comment]
Edge, FireFox 60.0.1 64bit, Chrome 67.0.3396.62 64bit, Windows 10 Pro, NVIDIA GTX 1080 Ti, Acer Predator XB321HK - Not sure what other devices you were looking for.

I'd provide a link to our app using fat lines from v0.93 but I have same issue with the example provided in the current documentation so that should suffice: https://threejs.org/examples/webgl_lines_fat.html

I've tested two laptops running the same browsers and the same OS and have not experienced this issue at all on those.

**Comment by looeee** [comment]
I see the same artefacts as in the image above. To reproduce: open example, set width to 10 and check "dashed" on Chrome 67, Win 10. 

My GPU is GTX 970M.

Looks OK on Edge  and Firefox though, there are some smaller artefacts on sharp curves but that's probably related to "Very fat dashed lines can have artifacts if the points are too close together".

@Bsheridan12 can you double check and confirm that you are seeing this on Edge and Firefox? Otherwise it's probably a browser issue.

**Comment by Bsheridan12** [comment]
@looeee Yep, just confirmed on both FireFox and Edge I can reproduce this issue by changing nothing in the example other than selecting 'dashed.'

**Comment by Mugen87** [comment]
@looeee I also have these artifacts on Firefox (60.0.1) and Ubuntu 16.04, Intel Ivybridge Mobile.

**Comment by WestLangley** [comment]
The points in the "fat lines" example are numerous, and very close together. Can the problem be reproduced with a more reasonable example -- a dashed line of, say, 10 points?

**Comment by d07RiV** [comment]
The example uses its own material/shaders for some reason, and the problem is caused by shader checking UV coordinates, which are never specified, so they're probably random noise. I can't even find the attribute definition for `uv` anywhere (it's copied into `vUv` in vertex shader).

			#ifdef USE_DASH

				if ( vUv.y < 0.5 || vUv.y > 0.5 ) discard; // discard endcaps <--- this line

				if ( mod( vLineDistance, dashSize + gapSize ) > dashSize ) discard; // todo - FIX

			#endif
