### ISSUE TITLE
Dead Links In New Loading 3D Models Doc

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#14190]
https://rawgit.com/mrdoob/three.js/dev/docs/#manual/introduction/Loading-3D-models

At least for me, I am getting either:

![image](https://user-images.githubusercontent.com/6549763/40849550-d6d03e70-6587-11e8-8765-220dd32a2420.png)

or a completely blank page when clicking on any of the exporter links within the doc.

This is the case in both chrome and firefox.

Putting `target="_blank"` in the link html fixes the issue.

**Comment by Mugen87** [comment]
> Putting target="_blank" in the link html fixes the issue.

Yes, external pages should open in a new tab. :+1:

**Comment by looeee** [comment]
They should also have `rel="noopener"` [for security]( https://mathiasbynens.github.io/rel-noopener/), although I'm not sure if this is still an issue for newer browsers.

**Comment by Mugen87** [comment]
@titansoftime Do you want to make the PR?

**Comment by titansoftime** [comment]
At work, gotta pick up kids. Possibly Saturday or Sunday sure.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Michael Herzog <notifications@github.com> Date: 6/1/18  1:31 PM  (GMT-06:00) To: "mrdoob/three.js" <three.js@noreply.github.com> Cc: Kevin <titansoftime@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [mrdoob/three.js] Dead Links In New Loading 3D Models Doc (#14190) 
@titansoftime Do you want to make the PR?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/mrdoob/three.js/issues/14190#issuecomment-393970751","url":"https://github.com/mrdoob/three.js/issues/14190#issuecomment-393970751","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mrdoob/three.js","title":"mrdoob/three.js","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mrdoob/three.js"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Mugen87 in #14190: @titansoftime Do you want to make the PR?"}],"action":{"name":"View Issue","url":"https://github.com/mrdoob/three.js/issues/14190#issuecomment-393970751"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [mrdoob/three.js] Dead Links In New Loading 3D Models Doc (#14190)",
"sections": [
{
"text": "",
"activityTitle": "**Michael Herzog**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Mugen87",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mrdoob/three.js\",\n\"issueId\": 14190,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"mrdoob/three.js\",\n\"issueId\": 14190\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mrdoob/three.js/issues/14190#issuecomment-393970751"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341550683\n}"
}
],
"themeColor": "26292E"
}

**Comment by titansoftime** [comment]
Meh, did it during lunch.

#14195

**Comment by titansoftime** [comment]
Updated PR.

#14196

**Comment by d07RiV** [comment]
Shouldn't they use `target="_top"`? Forcing links to open in a new tab is often considered bad style. I'm not fully convinced about it, but it's probably worth discussing, since some docs pages do use target=top, like TextGeometry page referencing facetype library.

**Comment by Mugen87** [comment]
@d07RiV The usage of `[link:...]` is not free of bugs. If there are special characters in the link name like ` or &, the link is not resolved.

**Comment by Mugen87** [comment]
> But the code that processes links can be fixed, which seems to be a better solution than trying to update a bunch of html files.

That's right. I'd would be great if you can have a look.
