### ISSUE TITLE
BoxHelper - performance issue when updating on Safari.

### ISSUE THREAD

**Issue by damoch** [mrdoob/three.js#14201]
##### Description of the problem

As the title says, Safari literally chokes itself, whenever I try to update BoundingBox of model like 3DBenchy (the framerate is at 4FPS at best). I tried on different Macs (El Capitan, Sierra, High Sierra, with and without external Video Card), and there was the same problem. Funnily enough, whenever i switch to a different browser (like Firefox or Google Chrome) it works with rock solid 60FPS on the same machine.
Is there anything, that could be done, or I should just go to WebKit's bugtracker? I've heard, that Safari does not have hardware support for WebGL - could that be the reason for this issue?
And finally - thanks for awesome work on threejs :)

* [Example](https://damoch.github.io/three-test/) 
If you open the console, there is "API", that you can mess around with:
* `rotate = false` disables rotation of object
* `updateBox = false` disables update of bounding box on every frame
* `helper.update()` updates bounding box
* `loadStl(path)` loads STL file from `path` (I'm not sure if it works). if called without parameter, it loads default file, which is 3DBenchy.stl.

##### Three.js version

- [x] r93

##### Browser

- [x] Safari

##### OS

- [x] macOS (El Capitan, Sierra, High Sierra)

##### Hardware Requirements (graphics card, VR Device, ...)
- I was able to reproduce this on every graphics card, that was built in every iMac/MacBook that i had access to.

**Comment by Mugen87** [comment]
> I've heard, that Safari does not have hardware support for WebGL

Where have you heard this?

**Comment by Mugen87** [comment]
I don't think this statement is valid. Safari does use the GPU for WebGL otherwise they would have to emulate everything in software. WebGL might be disabled but then you can't view any WebGL content.

> Is there anything, that could be done, or I should just go to WebKit's bugtracker.

Correct, please report this issue right there.

**Comment by WestLangley** [comment]
Fiddle that reproduces the problem: https://jsfiddle.net/41275nvb/

The math code is considerably slower on Safari than on Chrome.

**Comment by damoch** [comment]
I've reported this to WebKit's bugtracker -> https://bugs.webkit.org/show_bug.cgi?id=186236

**Comment by WestLangley** [comment]
@Mugen87 Can you replicate this issue on macOS using the fiddle I posted, which is considerably simpler than the OP's.
