### ISSUE TITLE
Need to Flip the object functionality 

### ISSUE THREAD

**Issue by sandeepsedar** [mrdoob/three.js#14207]
Hi,
 I am using in three js library for 3D view.
I want to need flip object functionality.
Please help me. 

Current object :- 
![current obj](https://user-images.githubusercontent.com/39150036/40885959-cee71c14-6740-11e8-8842-8789c003830c.png)

After flip(Need)

![flipobj](https://user-images.githubusercontent.com/39150036/40885983-2a3ff4e6-6741-11e8-80db-2a93cba8a542.png)

Thanks.

**Comment by donmccurdy** [comment]
Hi, please use the threejs forums for help questions: https://discourse.threejs.org/
