### ISSUE TITLE
GLTF exporter : missing weights for joined cloth mesh

### ISSUE THREAD

**Issue by derivou** [mrdoob/three.js#14212]
I work with three.js r93, blender 2.79b. I export a gltf2 object : a human body with a cloth (an apron). The object has an armature and animations (walking). I transfer weights data in Blender from the human body to the cloth so as to make the cloth follow the body. I join then cloth and human body to make one object. This is well animated in Blender but not for the export loaded in three.js. It seems the export has lost the weights for the apron.

**Comment by donmccurdy** [comment]
Are you able to provide the model (`.blend` or `.gltf`)? You can drag ZIP files into Github comments.

**Comment by derivou** [comment]
[proust.zip](https://github.com/mrdoob/three.js/files/2066209/proust.zip)

**Comment by derivou** [comment]
the gltf is 5M big ... so I provide the .blend with

**Comment by donmccurdy** [comment]
Cross-filing this to https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/236. The exported `.gltf` file has far too many joint influences per vertex to be rendered in any realtime engine, but I can't figure out if that's related to the model itself or if the exporter is doing something wrong.
