### ISSUE TITLE
LGTM: Remove analysis for Python

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#14213]
Since the removal of the Blender JSON exporter removed most of the project's Python code as well, I think we can safely disable the respective code analysis.

**Comment by mrdoob** [comment]
I don't think that is something that can be configured...?

**Comment by Mugen87** [comment]
Oh, I was not aware of that. I thought there is some kind of language setting.

**Comment by mrdoob** [comment]
After #14308... ✌️

<img width="998" alt="screen shot 2018-06-16 at 6 34 28 pm" src="https://user-images.githubusercontent.com/97088/41503905-0d0a55da-7194-11e8-8d56-c0c9227a97d7.png">

**Comment by Mugen87** [comment]
I like that yellow color 😊

**Comment by mrdoob** [comment]
https://twitter.com/lgtmhq/status/1008819464907812864
