### ISSUE TITLE
The 3d chart use Three.js how to do?

### ISSUE THREAD

**Issue by TongDaDa** [mrdoob/three.js#14222]
![screen shot 2018-06-01 at 6 20 32 pm](https://user-images.githubusercontent.com/23241188/40970604-ad9b8942-68ed-11e8-962e-7fcc4570646a.png)
![screen shot 2018-06-01 at 6 21 44 pm](https://user-images.githubusercontent.com/23241188/40970605-aef1b8de-68ed-11e8-8728-1cd2626a82cd.png)

How to use three.js implement the 3d effect, i need it,  hope that hree.js can accomplish, but i don't know how do .

Or you have any good ideas? to tell me please, very thanks....

**Comment by Mugen87** [comment]
The [forum](https://discourse.threejs.org/) is an ideal place for such help requests.
