### ISSUE TITLE
Clone mesh doesn't clone its material and geometry objects

### ISSUE THREAD

**Issue by marcobraghim** [mrdoob/three.js#14223]
##### Description of the problem
When I try to clone a mesh object I expect it will be full cloned, with "new" material and geometry objects. Is this behavior on purpose?

##### Three.js version

- [ ] Dev
- [x] r93
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] chromium (nw js actually)

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS
![captura de tela de 2018-06-04 21-59-15](https://user-images.githubusercontent.com/2068045/40987938-3e197930-68c0-11e8-9852-9c14948a77b6.png)

**Comment by donmccurdy** [comment]
Hi @marcobraghim, this is as intended. There is a high performance cost to deeply cloning materials, textures, and geometry — not just while duplicating them, but higher cost to render after that. Because you generally want to have as few materials and geometries as possible, it's better to clone only what you need:

```
mesh2 = mesh1.clone();
mesh2.traverse((node) => {
  if (node.isMesh) {
    node.material = node.material.clone();
  }
});
```

**Comment by marcobraghim** [comment]
It's really interesting and make me think if I need to change my strategy related to the materials and whole performance stuff at all... Thank you.

**Comment by NalinKamboj** [comment]
@marcobraghim how did you finally manage to solve this? I have a model which I need to clone (4 clones) and I want to be able to manipulate them individually. Currently, when I clone a model and add it to my scene, I only see one object.

**Comment by NalinKamboj** [comment]
@donmccurdy How would you recommend proceeding with what I described above? I couldn't find relevant info in docs.
