### ISSUE TITLE
 THREE.AudioLoader fails to load the same resource again

### ISSUE THREAD

**Issue by yuseitahara** [mrdoob/three.js#14225]
##### Description of the problem

 THREE.AudioLoader can't load the same resource more than once because AudioContext.decodeAudioData is a destructive function, a given arraybuffer becomes empty after the call. The first call of decodeAudioData succeeds and the next one fails, in console you can find an error message

> // In Chrome,
> Cannot decode detached ArrayBuffer

> // In Firefox
> Argument of AudioContext.decodeAudioData can't be a detached buffer

To solve the problem, a copy of the original arraybuffer that XMLHttpRequest returns should be given to decodeAudioData, then the original arraybuffer is still alive, it can be used again for the next decodeAudioData calls.

> // Copy the original arrayBuffer before calling decodeAudioData
> decodeAudioData(arrayBuffer.slice(0))

Reproducible Code Snippet : [https://jsfiddle.net/yuseit/nrud7tqs/](https://jsfiddle.net/yuseit/nrud7tqs/)

aframevr/aframe#3623

##### Three.js version

- [x] Dev
- [x] r93

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
see #13710

**Comment by Usnul** [comment]
> see #13710

looks gnarly :)

**Comment by yuseitahara** [comment]
> see #13710

Exactly the same issue.

**Comment by Mugen87** [comment]
Sry, for the delay. I hope we get the PR merged soon.

**Comment by Mugen87** [comment]
#13710 is now merged
