### ISSUE TITLE
Scene .toJSON error when THREE.CubeTextureLoader

### ISSUE THREAD

**Issue by dezomer** [mrdoob/three.js#14228]
If THREE.CubeTextureLoader is used **scene.toJSON()** crashes 

function getDataURL(image)

line 3737 context.drawImage(.. // param is an array of the 6 images of the CubeTexture

##### Three.js version

- [ ] Dev
- [x] r93
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Duplicate: #9458
