### ISSUE TITLE
StandardNodeMaterial: Rough metals are too reflective.

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#14238]
Rough metals are more reflective than their MeshStandardMaterial counterparts. Very likely missing a fix similar to https://github.com/mrdoob/three.js/pull/13501. This is the glTF metal/rough spheres example:

| StandardNodeMaterial | MeshStandardMaterial |
|---|---|
| <img width="505" alt="screen shot 2018-06-07 at 9 41 43 pm" src="https://user-images.githubusercontent.com/1848368/41136458-fad21762-6a9b-11e8-8012-cfee64c01aef.png"> | <img width="520" alt="screen shot 2018-06-07 at 9 41 51 pm" src="https://user-images.githubusercontent.com/1848368/41136464-06ea0ba4-6a9c-11e8-8434-48f0bc26e16a.png"> |

/cc @sunag

**Comment by sunag** [comment]
@donmccurdy Thanks you! I already fixed this. It was really the maxMIPLevels. I will just wait merger this PR:  https://github.com/mrdoob/three.js/pull/14214 to publish the next. Your WIP PR of GLSL with nodes also helped :+1:

**Comment by donmccurdy** [comment]
Excellent, thank you!

**Comment by mrdoob** [comment]
> @donmccurdy Thanks you! I already fixed this. It was really the maxMIPLevels. I will just wait merger this PR:  https://github.com/mrdoob/three.js/pull/14214 to publish the next. 

Merged! ✌️

**Comment by sunag** [comment]
Fix here: https://github.com/mrdoob/three.js/pull/14333
