### ISSUE TITLE
TextGeometry and Faceless

### ISSUE THREAD

**Issue by alessiocarrafa** [mrdoob/three.js#14234]
##### Description of the problem

Adding TextGeometry to the scene will throw "THREE.DirectGeometry: Faceless geometries are not supported." error.
You can check it also at this demo page https://threejs.org/docs/scenes/geometry-browser.html#TextGeometry

##### Three.js version

- [x] r93

##### Browser

- [x] Chrome
- [x] Firefox

##### OS

- [x] Linux

**Comment by Mugen87** [comment]
The message was introduced via https://github.com/mrdoob/three.js/pull/14105

/ping @paulmasson

**Comment by paulmasson** [comment]
The message is doing the job it is supposed to do. Somewhere along the way something that used to just silently fail is now being flagged. The regular TextGeometry example does not have this issue.

**Comment by Mugen87** [comment]
If created a PR to fix the issue. It's somewhat unfortunate that the warning message is triggered even with an initial instance of `Geometry`. Empty geometry containers should not be considered as invalid. Ideally, the engine just ignore them.
