### ISSUE TITLE
wrong link in removed blender exporter page

### ISSUE THREAD

**Issue by SET001** [mrdoob/three.js#14247]
@donmccurdy in the removed [blender exporter page](https://github.com/mrdoob/three.js/tree/dev/utils/exporters/blender) there is a link saying [Loading 3D Models](https://threejs.org/docs/#manual/introduction/loading-3d-models). If you open that page it say `404 File not found`

Also it is not understandable what to use now. Having model in Blender what is the preffered way to move it to threejs scene? Should I export it in OBJ format and then use OBJLoader.js or there are better ways?

**Comment by donmccurdy** [comment]
Good catch- The correct link should be https://threejs.org/docs/index.html#manual/introduction/Loading-3D-models, and suggests what to use now.

**Comment by Mugen87** [comment]
@SET001 Would you like to make a PR and correct the link?

**Comment by SET001** [comment]
ok, I'll do it
