### ISSUE TITLE
SubdivisionModifier not working on array of material

### ISSUE THREAD

**Issue by iShankarG** [mrdoob/three.js#14241]
I have try to add Subdivisions Modifier to my cube, but not working when using array of material. I need to use different image for different side.
Here is the CodePen link https://codepen.io/shankarG/pen/BVyByL

##### Three.js version

- [ ] Dev
- [ ] r93
- [x] r92

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Neither `BufferSubdivisionModifier` nor `SubdivisionModifier` support multiple materials right now. `BufferSubdivisionModifier` returns a new geometry without groups, `SubdivisionModifier` does not respect material indices.

**Comment by iShankarG** [comment]
@Mugen87 Is there any workaround and how long will it take this be fixed.

**Comment by Mugen87** [comment]
I've added a fix for `SubdivisionModifier`. Let's tackle `BufferSubdivisionModifier` in a separate PR.

**Comment by Mugen87** [comment]
Closing since `BufferSubdivisionModifier` was removed via #14397. Please use `SubdivisionModifier` instead.
