### ISSUE TITLE
Shader error with varyings

### ISSUE THREAD

**Issue by Fyrestar** [mrdoob/three.js#14248]
After running a project after a chrome update, i suddenly get a shader error:

> Varyings with the same name but different type, or statically used varyings in fragment shader are not declared in vertex shader: LB

Now, the varyings are exactly the same for both fragment and vertex, i checked this even though it wouldn't have worked before if this was the case. Even more weird: it names a variable which isn't even a varying but a uniform. No other variable is called like this uniform, and the uniform is declared for both fragment and vertex.

Has anything changed? It's been longer and happened around chrome 64.

**Edit: i'm not quite sure since it been longer, but removing a function which uses this unfiform (but the function not being used) fixes this issue. I'll investigate it more.**

**Comment by Mugen87** [comment]
Is this issue related to `three.js` or WebGL/Browser issue in general? In the latter case, I don't think we need issue in this repo. You might want to file a bug at: https://bugs.chromium.org/p/chromium/issues/list

**Comment by Fyrestar** [comment]
I can't tell yet, i need to investigate more and replicate it, it's ok if this gets deleted though.

**Comment by Mugen87** [comment]
We can reopen the issue if you can actually demonstrate a `three.js` bug.
