### ISSUE TITLE
Problem with slerp, and possible solution

### ISSUE THREAD

**Issue by hamishtodd1** [mrdoob/three.js#14258]
Here's some code. Sorry it's very contextless, but it is 3:25AM where I am.
```js
var verticesWide = 31

var tl = new THREE.Quaternion(-1,0,0,0)
var tr = new THREE.Quaternion(0,0,1,0)
var bl = new THREE.Quaternion(0,-1,0,0)
var br = new THREE.Quaternion(0,0,0,1)

var endsOfRule = Array(3);
endsOfRule[0] = [
	jonSlerp(tl,tr,0/(verticesWide-1)),
	jonSlerp(bl,br,0/(verticesWide-1))
];
var firstStepSize = 0.0000001;
endsOfRule[1] = [
	jonSlerp(tl,tr,firstStepSize/(verticesWide-1)),
	jonSlerp(bl,br,firstStepSize/(verticesWide-1))
];
endsOfRule[2] = [
	jonSlerp(tl,tr,firstStepSize*2/(verticesWide-1)),
	jonSlerp(bl,br,firstStepSize*2/(verticesWide-1))
];

var pointsInS3 = 
[
	endsOfRule[0][0].clone().slerp(endsOfRule[0][1],1/(verticesWide-1)),
	endsOfRule[1][0].clone().slerp(endsOfRule[1][1],1/(verticesWide-1)),
	endsOfRule[2][0].clone().slerp(endsOfRule[2][1],1/(verticesWide-1))
];

console.log(pointsInS3[0].distanceTo(pointsInS3[1]),pointsInS3[1].distanceTo(pointsInS3[2]))
```
The log gives you two different numbers which, if you think about it, should be the same. It works for maaaaaany other quaternions, but not these ones.

I implemented the pseudocode slerp from here and it worked http://number-none.com/product/Understanding%20Slerp,%20Then%20Not%20Using%20It/ my implementation is below. It required adding sub, add, and multiplyScalar to the quaternion class
```js
function jonBlowSlerp(q0,q1,t)
	{
		var theta0 = Math.acos(q0.dot(q1))
		var theta = t * theta0;
		var toSubtract = q0.clone().multiplyScalar( q0.dot(q1) );
		var q2 = q1.clone().sub( toSubtract ).normalize();

		return q0.clone().multiplyScalar(Math.cos(theta)).add( q2.clone().multiplyScalar(Math.sin(theta)) );
	}
```

**Comment by Mugen87** [comment]
Any chances to provide a [live demo](https://jsfiddle.net/f2Lommf5/) that demonstrates the bug and maybe your solution. That makes it easier to validate your proposal.

**Comment by mbredif** [comment]
Is that related to the discrepancy in Quaternion slerp interpolation ? 

- [Quaternion.slerpFlat](https://github.com/mrdoob/three.js/blob/013b604d20ffc6f0bcd1b0ac36f2c755d9b851ba/src/math/Quaternion.js#L43-L77) defaults to lerp (linear interpolation) for tiny angles (`sqrSin > Number.EPSILON`)
- [Quaternion.slerp](https://github.com/mrdoob/three.js/blob/013b604d20ffc6f0bcd1b0ac36f2c755d9b851ba/src/math/Quaternion.js#L536-L545) defaults to the average quaternion (linear interpolation at 0.5) for tiny angles (`Math.abs( sinHalfTheta ) < 0.001`)

@hamishtodd1, are you experiencing the same issue using `Quaternion.slerpFlat` ?

@Mugen87 what do you think of aligning the behavior (threshold and interpolation of small angles) of Quaternion.slerp to match the one of Quaternion.slerpFlat ? Average quaternion is not precise enough for our the iTowns use case (see iTowns/itowns/pull/774)

**Comment by WestLangley** [comment]
Closing this due to lack OP response.

@mbredif Please open a separate issue if you feel it is warranted.
