### ISSUE TITLE
NodeMaterial, how to interface with properties

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#14254]
Another topic extracted from https://github.com/mrdoob/three.js/issues/7522 and https://github.com/mrdoob/three.js/issues/14252
@donmccurdy 

```javascript
var material = new THREE.MeshStandardMaterial();
material.map = textureLoader.load('foo.png'); // returns Texture

var node = material.node; //a new layer, between Material
node.color.coord.index = 1; // why does color have a coord index?

console.log( material.node.color ); // THREE.TextureNode
console.log( material.color ); // what does this log?
```

I'm experiencing cognitive overload when i read this code. For every material prop `.foo` there seems to be a corresponding `.node.foo` node. Is this the intended interface? Could it be:

```javascript
var material = new THREE.MeshStandardMaterial();
material.map = textureLoader.load('foo.png'); // returns Texture
material.map.coord = 1
```

^ nodes do their noding behind the scene, while i have a more meaningful context for something like `coord` (it belongs to a texture, or texture mapping).

**Comment by donmccurdy** [comment]
Let's not start an issue on this please. My example code was purely a speculative attempt at a backward-compatible MeshStandardMaterial implementation on top of nodes, and it is not worth discussing specific syntax here until some code exists to discuss. The goal here is to have a backward-compatible state for existing code, and not that we encourage people to mix and match in that way.

**Comment by pailhead** [comment]
@donmccurdy i've removed your code that i used in the post and made it generic. Please reopen this issue as i feel that this is a valid issue, for one of the current examples.

**Comment by donmccurdy** [comment]
The crux of the problem is that no documentation has yet been written. Certainly we should fix that. There is no need for an open-ended issue discussing how to use NodeMaterial or a theoretical backward-compatible wrapper, unless it is feedback on code that is already checked in. Sorry to be terse, these are too many tangents and resurrections of previous threads, and it is becoming disruptive to the aspects of NodeMaterial that still require more discussion.

**Comment by pailhead** [comment]
The checked in code can be seen here:
https://github.com/mrdoob/three.js/blob/dev/examples/webgl_materials_nodes.html#L361-L367
