### ISSUE TITLE
NodeMaterial structure changes compared to existing shaders

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#14250]
Trying to extract various topics from  https://github.com/mrdoob/three.js/issues/7522

See this comment for a direction for texturing/mapping imposed by `NodeMaterial`. https://github.com/mrdoob/three.js/pull/14214#issuecomment-395811448 

I propose this requirement be extracted from `NodeMaterial` and considered for application to the other systems:

For example, right now the templates are limited by this pattern:
https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/alphamap_fragment.glsl

```glsl
//alphamap_fragment.glsl

#ifdef USE_ALPHAMAP

	diffuseColor.a *= texture2D( alphaMap, vUv ).g; // why hardcode "vUv" into the coord slot?

#endif
```

It can be refactored to be more in line with the need imposed by `NodeMaterial`.

```glsl
//alphamap_fragment.glsl

#ifdef USE_ALPHAMAP

	diffuseColor.a *= texture2D( alphaMap, alphaUV ).g;

#endif
```

To be preceded by:
```glsl
//alphamap_mapping_fragment.glsl

#ifdef USE_ALPHAMAP
    vec2 alphaUV = vUv;
#endif
```

This would break up and decouple a chunk that is overloaded to begin with IMO, which would then validate the comparison with `NodeMaterial`.

Would it make sense to document these differences before the new API becomes default?
Would it also make sense to refactor the existing structure, given that  https://github.com/mrdoob/three.js/issues/7522 is still not in `/src` while the templates are? Ie. is there a reason to keep the templates as is, other than this PR from 2015?

Why keep the current template convoluted?

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/14245#issuecomment-397957636
