### ISSUE TITLE
EventDispatcher issues with prototype based callbacks

### ISSUE THREAD

**Issue by sasmaster** [mrdoob/three.js#14251]
Hi. I am binding prototype (member) function as callbacks for events. But I noticed that when I want to
check if an object already has event listener, the test doesn't pass.I found that this check inside EventListener code:

  `    return listeners[ type ] !== undefined && listeners[ type ].indexOf( listener ) !== - 1;`

Can't find indexOf of a function made like this:

  `  obj.addEventListener('fooevent', this.onFooEvent.bind(this));`

Because the registered callback method signature looks like ''anonymous' function.That's,it doesn't have function signature as a standalone Js method has if used instead.

Currently, to overcome this one,I am doing something like this:

 ```
 if(obj._listeners !== undefined && obj._listeners['fooevent']!== undefined)
      {
        obj._listeners['fooevent'].length = 0;
      }
```

Is this fixable? Or the way, JavaScript creates this sort of methods,renders this whole THREE.EventDispatcher useless for binding prototype functions as callbacks ? 
 
  r93dev

**Comment by Mugen87** [comment]
`EventDispatcher` actually has its own repository: https://github.com/mrdoob/eventdispatcher.js

Do you mind creating an issue at this place? 😇

**Comment by sasmaster** [comment]
Oops,didn't know that. Will move it there...
