### ISSUE TITLE
The problem of converting from geometry to buffergeometry

### ISSUE THREAD

**Issue by lovepsone** [mrdoob/three.js#14261]
Good day! I tried to convert the old format (JSON Model format 3) to a new one (JSON Object / Scene format 4). I used the following code:

               let loader = new THREE.JSONLoader();
		loader.load(file, function(geometry, materials)
		{
			for (var i = 0; i < materials.length; i++)
			{
				materials[i].map.wrapS = materials[i].map.wrapT = THREE.RepeatWrapping;
				materials[i].map.repeat.set(1, 1);
				materials[i].side = THREE.DoubleSide;
			}

			let bufferGeometry = new THREE.BufferGeometry().fromGeometry(geometry);
			let displacement = new Float32Array(bufferGeometry.attributes.position.count);
			bufferGeometry.addAttribute('displacement', new THREE.BufferAttribute(displacement, 1)); 
			let mesh = new THREE.Mesh(bufferGeometry, materials);
                       let tmpData =  mesh .toJSON();
		});

passed tmpData to ajax and save file.

but when you load the converted model, it does not look like it should
##### Three.js version
 r93
##### Browser
 All of them
##### OS
- [ ] Windows

**Comment by Mugen87** [comment]
`Geometry` is internally converted to `BufferGeometry`. If you do it manually and it does not work, there has to be a problem in your application. Please try it at stackoverflow or the [forum](https://discourse.threejs.org/).
