### ISSUE TITLE
Documentation: mocha testing howto error

### ISSUE THREAD

**Issue by mimooh** [mrdoob/three.js#14271]
The docs on https://threejs.org/docs/#manual/buildTools/Testing-with-NPM (mocha part) didn't work for me: 

"By default this will run anything in test/ (not having directory test/ can run into npm ERR!, create it by mkdir test)"

What fixed things for me was creating test/test.js (not just mkdir test/), as found at https://mochajs.org/#getting-started

```
$ npm install mocha
$ mkdir test
$ $EDITOR test/test.js # or open with your favorite editor
```

In your editor:

```js
var assert = require('assert');
describe('Array', function() {
  describe('#indexOf()', function() {
    it('should return -1 when the value is not present', function() {
      assert.equal([1,2,3].indexOf(4), -1);
    });
  });
});
```

**Comment by Mugen87** [comment]
What about step 3 in section `Add three.js`. 

> Let's add a simple test that will verify that the three.js object is available and working. Create test/verify-three.js containing

Have you maybe overlooked that?

**Comment by mimooh** [comment]
Well, see what comes first, and what comes later in your docs. I was stuck at ealier:
"This should now *succeed*, reporting 0 passing (1ms) or similar."
and I spent my time on mocha website, before I learnt from the docs what you are now bringing.

**Comment by Mugen87** [comment]
I suppose the content of this site is more than two years old. This could be the reason why does not work with the latest version of mocha. Would you like to make a PR to correct the steps?

**Comment by mimooh** [comment]
I was just trying, but I know too little of nodejs/npm. For instance mocha docs say that tests should be run by: "./node_modules/mocha/bin/mocha", while threejs-mocha docs prefer "npm test". The second one doesn't work for me, but I just don't feel competent in mocha or nodejs generally to write docs. Sorry, cannot help.

**Comment by mrdoob** [comment]
> Sorry, cannot help.

Should this be closed then?
