### ISSUE TITLE
isLineCurve3 must to be added

### ISSUE THREAD

**Issue by git-mormot** [mrdoob/three.js#14285]
https://github.com/mrdoob/three.js/blob/8a9a106f79e13e7f5b0e7fa1a57ed4a31f8ba74b/src/extras/core/CurvePath.js#L173

I think it would be nice to add isLineCurve3 check in CurvePath::getPoints() function.

**Comment by Mugen87** [comment]
Yes, that makes sense. Would you like to make a PR with the change?

**Comment by git-mormot** [comment]
I made a PR. Please check it.
