### ISSUE TITLE
Unexposed renderer objects and functions

### ISSUE THREAD

**Issue by Fyrestar** [mrdoob/three.js#14284]
I'm implementing a `ChunkMesh `based on `THREE.Mesh` basically rendering multiple fixed memory buffer geometries representing one for the same mesh by using the onAfterRender callback and renderBufferDirect.

Besides the additional geometries being not touched anyway, the webgl object for the geometry will be updated / initialized within `projectObject`, and requires the webgl objects object, which sadly isn't exposed by default.

It would be nice if this as well as the `projectObject ` function could be exposed, since both can be used to implement custom strategies such as for buffer geometry rendering in the onBeforeRender and onAfterRender callbacks, as well as overwriting the render item list generation, here for example i replaced the linear approach with an spatial managed one and auto-instancing.

**Comment by pailhead** [comment]
At one point, much more of these internals were exposed to the outside world. +1

**Comment by Mugen87** [comment]
Merging into #20457.
