### ISSUE TITLE
Memory Error by loading larger DRACO compressed GLTF files

### ISSUE THREAD

**Issue by chlueth** [mrdoob/three.js#14295]
I'm loading a 79MB GLTF file, compressed with DRACO with the following error.

> Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 2004156416, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0       draco_wasm_wrapper.js:20:197
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 2004156416, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0        draco_wasm_wrapper.js:20:208
uncaught exception: abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 2004156416, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.

Files with round about 60MB are working fine. Can anybody help?

**Comment by Mugen87** [comment]
I guess it makes more sense to post the issue at the Draco repo: https://github.com/google/draco

We are just using the Draco as an external lib.
