### ISSUE TITLE
GLTFLoader doesn't save 'extras' of a root glTF-object

### ISSUE THREAD

**Issue by wlinna** [mrdoob/three.js#14294]
##### Description of the problem

GLTFLoader doesn't save `extras` that are attached to the root glTF-object to `userData`

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#reference-gltf

It merely adds unknown extensions to `userData`, even though `userData ` could be immediately initialized with `json.extras`, which is what GLTFLoader should, IMO, do.

https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/GLTFLoader.js#L187

##### Three.js version

- [X] Dev

**Comment by takahirox** [comment]
Good catch! Would you like to make PR?

**Comment by wlinna** [comment]
Sure. I'll do it on Monday.

**Comment by mrdoob** [comment]
#16735
