### ISSUE TITLE
Material super class may know too much about it's sub classes

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#14290]
Three.js currently has 16 built-in materials that can be found here:

https://github.com/mrdoob/three.js/tree/dev/src/materials

All 16 of these materials extend `Material`:

https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js

The `Material` supper class may possibly know too much about the sub classes.

These kind of properties belong on the super class because all of the materials share them, and they are needed to work with `THREE.WebGLRenderer`.

https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L16-L68

This method is generic:

https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L80

This method is less:

https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L136

For example:

Only 1/16 materials has these properties, yet the super class knows about it.
https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L165-L166

Only some material have these, it's actually not obvious from just reading this code:
https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L171-L174

This i believe is only used for `gl_PointSize` which is present only in one or two materials? 
https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L228

These make sense only with `Line` types:
https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L246-L249

I'm not sure but it feels like almost the majority of `this[ propName ]` present in `toJSON` doesn't have a declaration in the constructor, leaving one to wonder where `propName` may possibly come from.

Would it make sense to consider a more generic approach here? Removing all these properties that are not initialized by `Material` might make adding properties to existing materials and new materials easier, as they wouldn't have to touch this file.

A good example of this process can be seen in https://github.com/mrdoob/three.js/pull/14239. Only two materials are modified, but the super class has to be made aware of that.

**Comment by pailhead** [comment]
As `Material` get's more complex it will become harder and harder to refactor it. In the least, each prop would require a `console.warn` when deprecated etc. I think it's better to plan ahead where some property should live.

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/14245#issuecomment-397957636
