### ISSUE TITLE
Orbit controls zooming limits

### ISSUE THREAD

**Issue by LuisEgan** [mrdoob/three.js#14300]
##### Description of the problem

Zooming with Orbit controls depend on the radius of the spherical coordinates of the camera relative to the orbiting axis, and, of course, you have a limit when zooming in because the radius can only get so little, but the problem is if you zoom close to the orbiting axis, then rotate the camera and look down (or up) you can't zoom into that direction because of the radius...

I am opening this issue because I'm not sure if this would be a feature request (being able to zoom up and down regardless of the radius) or if I'm not getting something.

##### Three.js version

- [ ] Dev
- [x] r92

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Crossposting: 

https://discourse.threejs.org/t/orbit-controls-zooming-limits/3148/4
https://stackoverflow.com/questions/50885465/three-js-orbit-controls-zooming-limits

From my point of view, it's clearly no feature request but more an uncertainty about how `OrbitControls` work. Please use stackoverflow or the forum for clarification.
