### ISSUE TITLE
EdgesGeometry: Add serialization/ deserialization

### ISSUE THREAD

**Issue by marcobraghim** [mrdoob/three.js#14302]
All my scene objects is created with a **wireframe**. When I export objects from the scene it works ok with the code bellow:

``` javascript
var objList = $this.getSceneObjects()
for (var i in objList) {
  $this.savefile.scene.objects.push(objList[i].toJSON())
}
```

Then I put all objects together, store some more needed information and save in a whatever file. So my program will **open** this file, it's not an importation at all, it's an opening to keep editing objects... But when I try to do it, I get a lot of errors. That's my opening code:

``` javascript
var fileJson = JSON.parse(fs.readFileSync(file))
var document = new App.Document(file)
        
// Load Scene saved objects
var loader = new THREE.ObjectLoader();
for (var obj in fileJson.scene.objects) {
  var item = fileJson.scene.objects[obj]
  document.getScene().add(loader.parse(item))
}
```

Note in the image attached that none of the objects could be rendered with that **wireframe** I said before... =/

##### Three.js version

- [ ] Dev
- [x] r93
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Chromium

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

![captura de tela de 2018-06-14 20-54-25](https://user-images.githubusercontent.com/2068045/41498127-0391f4c0-713c-11e8-8c5e-6438859a8476.png)

**Comment by Mugen87** [comment]
Seems like `ObjectLoader` can process `EdgesGeometry` yet.

**Comment by Mugen87** [comment]
Does it work if you are not using `EdgesGeometry` in your app?

**Comment by Mugen87** [comment]
Serialization/ deserialization is somewhat tricky since it has a geometry object as parameter. Let's label this issue as a feature request. For now, a workaround is to manually create `EdgesGeometry` in your app when you load a scene. I know it's not a nice solution but it should work.

**Comment by marcobraghim** [comment]
Thanks a lot! I'll be waiting for it with no problems. =)

**Comment by marcobraghim** [comment]
Let me check it out =D

**Comment by marcobraghim** [comment]
Yeah!! It works just fine for me. Thank you very much =D

#letItBePulledPlease

![captura de tela de 2018-06-23 14-37-17](https://user-images.githubusercontent.com/2068045/41812113-14980cd4-76f3-11e8-91e5-0040fb5f8ffa.png)
 =D

**Comment by spade69** [comment]
why it's not being merged? i think it works.  Or u guys give me some advice to make use of worker.

**Comment by Mugen87** [comment]
Closing in favor of #16340.
