### ISSUE TITLE
Incorrect example in SkinnedMesh documentation

### ISSUE THREAD

**Issue by CakeWithSteak** [mrdoob/three.js#14314]
The example in the [SkinnedMesh documentation page](https://threejs.org/docs/#api/objects/SkinnedMesh) creates a `CylinderBufferGeometry`, and later tries to set skin indices and weights like this:
```javascript
geometry.skinIndices.push( new THREE.Vector4( skinIndex, skinIndex + 1, 0, 0 ) );
geometry.skinWeights.push( new THREE.Vector4( 1 - skinWeight, skinWeight, 0, 0 ) );
```
However, this code doesn't work since `BufferGeometry` doesn't have the `skinIndices` and `skinWeights` properties - those are only present in `Geometry`.

The issue could be fixed by either changing `CylinderBufferGeometry` to `CylinderGeometry` or setting the skin weights and indices as attributes in the `BufferGeometry`
(NOTE: The embedded example on the page correctly uses a `CylinderGeometry`, only the code provided below it is incorrect)

**Comment by mrdoob** [comment]
Sound like you already figured out the fix. Would you like to do a PR with it?
