### ISSUE TITLE
ObjectLoader: missing class member crossOrigin

### ISSUE THREAD

**Issue by MarcelKlammer** [mrdoob/three.js#14318]
##### Description of the problem

ObjectLoader has no class member crossOrigin, only the method setCrossOrigin is present.

Comparing it to other classes like TextureLoader, which has

crossOrigin: 'Anonymous'

ObjectLoader should also have this member specified.

I tried to have a real S3 URL in images in a json file instead of data:

The following error occured:
THREE.WebGLState: DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.

This error is gone when adding 

crossOrigin: 'Anonymous'

as a class member to ObjectLoader.

##### Three.js version

- [x] Dev
- [x] r93

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
It's maybe a good idea to add the property to `ObjectLoader` and `JSONLoader`. The latter one does not even have the method `setCrossOrigin()`.

Also related: #12413

**Comment by mrdoob** [comment]
Yeah, I think we should harmonize this.
