### ISSUE TITLE
Time of AnimationActions set to NaN, animation not playing.

### ISSUE THREAD

**Issue by JaccoGoris** [mrdoob/three.js#14310]
##### Description of the problem
I followed the examples of the animations very closely but my animations wont play. when looking into the data, the time of my animationAction is NaN. Since I'm doing the same thing as on the example, and I'm using the same version of threejs; I'm unsure where the issue might be.

I've pushed my project to this repo:
https://github.com/JaccoGoris/three-react-fbx-animation-test
So you can clone it and test it if you want.

![image](https://user-images.githubusercontent.com/7052832/41508672-ab2df6c2-7248-11e8-80a7-28c5669ed6a5.png)

##### Three.js version

- [ ] Dev
- [x] r93
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

Chrome
Version 67.0.3396.87 (Official Build) (64-bit)

Mac Os High Sierra
Version 10.13.4 (17E202)

**Comment by makc** [comment]
I bet this line causes it
> mixer.update(this.props.deltaSeconds);

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.

**Comment by JaccoGoris** [comment]
I'll post there as per your direction, but I do want to clarify that I did everything according to the examples and documentation that I found and it's not working, which is why I considered this a bug in the animationMixer Module or FBXLoader module. But I'll try the forum next thanks.

**Comment by mrdoob** [comment]
@JaccoGoris If you report a bug only when you *think* you found one you're basically asking us to debug your code for you. It's better to report bugs when you know for sure it's a bug and you can point us to the line causing it.
