### ISSUE TITLE
CSS3D renderer chrome issue with embed Vimeo/youtube

### ISSUE THREAD

**Issue by geekance** [mrdoob/three.js#14320]
##### Description of the problem
Quite recently, it is impossible to access Vimeo/youtube controls when displayed using the CSS3D renderer. 
You can test this issue on the following page: https://threejs.org/examples/#css3d_youtube

This is only a Chrome issue, Firefox an Safari works as expected.

**Comment by Mugen87** [comment]
I can confirm the issue. Indeed, seems to be a Chrome related problem.

**Comment by geekance** [comment]
Thanks for the feedback, are you capable to investigate the issue?

**Comment by mrdoob** [comment]
It works fine here.. 🤔

**Comment by geekance** [comment]
It work on your Chrome? 
Normally you should be able to play the videos using the central button but the controls à the bottom are unreachable. 
Do you confirm that observation?

**Comment by mrdoob** [comment]
I can play and use the controls in that example.

**Comment by geekance** [comment]
Version 67.0.3396.87 (Official Build) (64-bit) is the version I use

**Comment by geekance** [comment]
Did you manage to verify the issue on this version of Chrome?

**Comment by Mugen87** [comment]
I have also used  67.0.3396.87

**Comment by yomotsu** [comment]
I can't reproduce too. I have tested in
- macOS Chrome Version 67.0.3396.87
- Windows10 Chrome Version 67.0.3396.87

Maybe addons?

**Comment by haroldiedema** [comment]
Works fine here on Chrome  65.0.3325.181 (Official Build) (64-bit).

**Comment by yomotsu** [comment]
Whether works correctly or not is depends on rotate angle. I don't think that is CSS3D renderer's fault tho
![2](https://user-images.githubusercontent.com/212837/41606652-23ee2032-741f-11e8-8633-66137b9c8e8b.gif)
![3](https://user-images.githubusercontent.com/212837/41606912-be2f43b0-741f-11e8-9a58-486b8630419f.gif)

**Comment by Mugen87** [comment]
I guess Chrome 67.0.3396.87 introduces a change we are not aware of...

**Comment by geekance** [comment]
I confirm also that it seems we are in a situation where the mouse coordinates the iframe is receiving are shifted comparing to actual cursor position.

Not sure either if the issue comes from the Youtube/Vimeo API (I have a similar issue with Vimeo) or from Chrome or from the CSS3D renderer...

Thanks to all for your help so far :).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16167110/41608525-fa36658c-73e8-11e8-9311-8e8086ae29d9.gif)

**Comment by geekance** [comment]
Thanks for that. Do you know how long it could take them to solve this kind of issue?

**Comment by mrdoob** [comment]
Confirmed here. It broke in Chrome 67.

**Comment by mrdoob** [comment]
Thanks for reporting @Mugen87!

**Comment by Mugen87** [comment]
> Do you know how long it could take them to solve this kind of issue?

Not sure about that. But if you star the issue, you might give it more priority.

![image](https://user-images.githubusercontent.com/12612165/41616238-c8f96f4a-73fd-11e8-9737-ae98bb67b238.png)

**Comment by Mugen87** [comment]
Closing. The reported [Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=854247) is now a prio 1 bug.

**Comment by geekance** [comment]
Thanks all for the great help.
