### ISSUE TITLE
Helper to deal with multi-materials

### ISSUE THREAD

**Issue by moroine** [mrdoob/three.js#14334]
##### Description of the problem

I am currently merging meshes with different materials which result in a single mesh with material property being an array.

Then I had to update all my code base in order to support this, and I feel like repeating myself a LOT !

That's why I think it might be cool to have something to help us dealing with that.

I don't think forcing material to be an array is a good move because of the memory overhead it will add.

I am thinking on a stuff more like this:

```javascript
forEachMaterial(callback) {
  if (Array.isArray(this.material)) {
     for( var i =0; l = this.material.length; i < l; i++ ){
        callback(this.material[i]);
    }
  } else {
     callback(this.material);
  }
}
```

Like this on my side I could replace 

```javascript
if (Array.isArray(mesh.material)) {
     for( var i =0; l = this.material.length; i < l; i++ ){
        material[i].opacity = 0.5;
    }
} else {
  material.opacity = 0.5;
}
```
By

```javascript
mesh.forEachMaterial(function(material) {
  material.opacity = 0.5;
});
```

**Comment by WestLangley** [comment]
>I am currently merging meshes with different materials which result in a single mesh with material property being an array.

Why not merge only meshes that share a single material? Only one material can be rendered in a draw call, so if you have N materials, you will have N draw calls anyway -- and maybe many more than that if your merged faces are not properly sorted.

**Comment by moroine** [comment]
I didn't know about that, but it make sense.

But as far I import the model, and threejs allow material to be an array I want to deal with that case in order to make sure it won't crash.

**Comment by WestLangley** [comment]
You can merge to a single geometry if you want, but if you have N materials, make sure your buffer-geometry has only N groups.

**Comment by moroine** [comment]
Thanks for the tip!

Do I close this PR as it won't be that much used?

**Comment by WestLangley** [comment]
@moroine I think that makes sense.
