### ISSUE TITLE
MeshPhysicalMaterial reflectivity may not work

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#14359]
Changing the value of `reflectivity` in [this docs page](https://threejs.org/docs/#api/materials/MeshPhysicalMaterial) seems to do nothing.

When making a `ShaderMaterial` using the same templates, this seems to modulate the specular highlight.

##### Three.js version

- [ ] Dev
- [x] r93
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Fixed. Thanks, for the heads up @pailhead!

**Comment by WestLangley** [comment]
For reference, the `reflectivity` property of `MeshPhysicalMaterial` controls the specular reflectance of the material for non-metals; that is, it models the extent to which the material reflects its environment when `metalness` is zero.

**Comment by pailhead** [comment]
Here's a crude demo of where i tested it:

http://dusanbosnjak.com/test/webGL/three-chunk-material/

when changing reflectivity one will be locked at 1 the other will modulate.

**Comment by mrdoob** [comment]
Thanks @pailhead 🙌
