### ISSUE TITLE
Add a way to get the max number of uniforms supported

### ISSUE THREAD

**Issue by theochampion** [mrdoob/three.js#14368]
##### Description of the problem

Hi guys, I'm doing a scene where I have a lot of `pointLight`. It render fine on desktop but fail on mobile due to the number of `uniforms` supported by the GPU being too low.  

The question is, how can I get the number of supported `uniforms` form three.js in order to render less that that amount of lights (`MAX_VERTEX_UNIFORM_VECTORS`) ?

##### Three.js version

- [ ] Dev
- [x] r93
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
[WebGLRenderer.capabilities.maxVertexUniforms](https://threejs.org/docs/#api/renderers/WebGLRenderer.capabilities) will tell you this. 

In future, please direct help questions to the [forum](https://discourse.threejs.org/) or Stackoverflow.
