### ISSUE TITLE
Negative scale in camera matrix turns models inside out

### ISSUE THREAD

**Issue by Korijn** [mrdoob/three.js#14372]
Objects are not turned inside out when giving them a negative scale thanks to the fixes in #12787 However when setting a negative scale on the camera, the scene is turned inside out regardless.

Looking at the changes made in #12787 I believe that instead of taking the determinant of `object.matrixWorld` it should be the determinant of `object.modelViewMatrix` which includes the camera view transform.

Local testing confirms that this resolves the issue.

**Comment by WestLangley** [comment]
Scaling the camera is not supported. Can you please explain your use case?

Granted, even if the camera is unscaled, the camera could be added as a child of another object, so your proposed code change has merit.

Please experiment with this pattern and see what consequences you find:
```javascript
var group = new THREE.Group();
scene.add( group );
group.add( camera );

group.scale.set( a, b, c );
camera.scale.set( d, e, f );
```

**Comment by Korijn** [comment]
The use case is to flip the view space around an axis, effectively mirroring the rendered image. It is perfectly supported and works well, except that normals are inverted. In the PR that I referenced this bug was fixed for object transforms, but not for view transforms. I think this should be corrected.

**Comment by WestLangley** [comment]
I can understand the use case for mirroring a scene object. What is your use case for mirroring the rendered image? Can you use post-processing for that?

**Comment by Usnul** [comment]
if you negatively scale your camera, what happens is you turn camera frustum inside-out, in which case, rightly, nothing bound by the frustum should be rendered, and everything outside of it should be, i think? 

It's an interesting proposition which I personally haven't thought much about.

**Comment by Korijn** [comment]
@Usnul That is not what is happening. First the camera applies its view matrix (camera.matrixWorld) to the world, to align it with view-space where the negative z-axis is the view direction. Then it applies the projection matrix (camera.projectionMatrix), which takes a frustum in view space and projects it onto the screen. The scale, position and rotation properties of camera go into camera.matrixWorld (the view matrix), not in the projection matrix. So, the frustum is not turned inside out, just the world.

**Comment by mrdoob** [comment]
Have you considered transforming the canvas instead?

```js
renderer.domElement.style.transform = 'scaleX(-1)';
```

**Comment by Usnul** [comment]
@Korijn 
Explain this to me please, if I have a frustum, which is defined by a set of 6 planes, and each plane has a normal and an offset, applying a negative scale to such a thing will invert normals, by design - right? Now, I don't know about you, but in my book a frustum with normals pointing OUT instead of IN is not an INCLUSION frustum, but and EXCLUSION one, it's like saying "i want to see everything except for what's in this frustum". 

I understand that the transfrom matrix and frustum paradigms exist in parallel and aren't actually strictly tied, so you _could_ compute a valid inclusion frustum after negatively scaling your transform matrix. Scaling a position is different from scaling a direction.

**Comment by Korijn** [comment]
The reason we don't want to use post-processing effects (like CSS or image-space shaders) is that we still want to be able to project world space coordinates to 2D screen coordinates with `coord.project(camera)`.

I'm not sure why you consider it hacky? It's just a transform of the view space?

Put it another way: if you put the negative scale in the object transform instead of the camera transform (as is supported already before this PR), it will still end up in the modelViewMatrix and have the same effect on the frustum.
