### ISSUE TITLE
connecting positional audio to web audio api effects

### ISSUE THREAD

**Issue by noahneumark** [mrdoob/three.js#14373]
Is there a way to use the .connect() from web audio api to route positional audio elements to effects?  I'd like to use the convolution effect in particular.  This would open up some realistic audio rendering possibilities since convolution can emulate real spaces.  Panning and fading (current positional audio) isn't enough to create a real experience.  Convolution would help create the illusion of echos and sound refraction.

**Comment by Mugen87** [comment]
What do you mean with `effects`? Are you referring to another library?

**Comment by mrdoob** [comment]
I think https://developers.google.com/resonance-audio/develop/web/getting-started may be a @noahneumark is trying to build.

**Comment by Mugen87** [comment]
Closing. We can reopen this issue if @noahneumark responds.
