### ISSUE TITLE
SVGLoader and SVGObject: uncaught TypeError: node.setAttribute is not a function

### ISSUE THREAD

**Issue by arrchhy** [mrdoob/three.js#14387]
##### Description of the problem

I'm trying to load a .svg file into three.js using SVGLoader and SVGObject. What I have is fairly straightforward:

```js
var loader = new THREE.SVGLoader();
loader.load( 'https://upload.wikimedia.org/wikipedia/commons/b/b0/NewTux.svg', function ( paths ) {
	var obj = new THREE.SVGObject(paths)
	scene.add( obj );
});
```

and then have it rendered with `new THREE.SVGRenderer()`.

```js
function animate() {
	requestAnimationFrame( animate );
	render();
}

function render() {
	renderer.render( scene, camera );
}
```

But I get `uncaught TypeError: node.setAttribute is not a function` error repeatedly when I try to have it `animate()`. 

<img width="1251" alt="screen shot 2018-06-28 at 2 00 40 am" src="https://user-images.githubusercontent.com/10269911/41991186-2b6fdfa4-7a77-11e8-91f4-c953c5bdb3ac.png">

Looks like something is broken internally. 

This is what I have:

```js
var container = document.getElementById( 'container' );
//
scene = new THREE.Scene();
scene.background = new THREE.Color( 0xffffff );
//
camera = new THREE.PerspectiveCamera( 1, window.innerWidth / window.innerHeight, 0.1, 100 );
camera.position.set( 0, 0, 0 );

var loader = new THREE.SVGLoader();
loader.load( 'https://upload.wikimedia.org/wikipedia/commons/b/b0/NewTux.svg', function ( paths ) {
	var obj = new THREE.SVGObject(paths)
	scene.add( obj );
	animate();
},
// called when loading is in progresses
function ( xhr ) {
	console.log( ( xhr.loaded / xhr.total * 100 ) + '% loaded' );
},
// called when loading has errors
function ( error ) {
	console.log( 'An error happened' );
});

renderer = new THREE.SVGRenderer();
renderer.setPixelRatio( window.devicePixelRatio );
renderer.setSize( window.innerWidth, window.innerHeight );
container.appendChild( renderer.domElement );

function animate() {
	requestAnimationFrame( animate );
	render();
}

function render() {
	renderer.render( scene, camera );
}
```

Another code snippet (doing basically the same thing as I did) from [a StackOverflow accepted answer back in 2015](https://stackoverflow.com/questions/33140342/how-to-load-svg-file-into-svgrenderer-in-three-js/33194449) gives the same error too. That means it worked 3 years ago.

A live demo can be found on the StackOverflow post.

##### Three.js version

- [x ] Dev
- [ ] r94
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

(Haven't tested it in other OS)

**Comment by mrdoob** [comment]
Apologies...

A few months ago we changed `SVGLoader` so it generates a geometry instead of just loading the nodes.

Please, use this loader instead:

```js
/**
 * @author mrdoob / http://mrdoob.com/
 * @author zz85 / http://joshuakoo.com/
 */

THREE.LegacySVGLoader = function ( manager ) {

	this.manager = ( manager !== undefined ) ? manager : THREE.DefaultLoadingManager;

};

THREE.LegacySVGLoader.prototype = {

	constructor: THREE.LegacySVGLoader,

	load: function ( url, onLoad, onProgress, onError ) {

		var scope = this;

		var parser = new DOMParser();

		var loader = new THREE.FileLoader( scope.manager );
		loader.load( url, function ( svgString ) {

			var doc = parser.parseFromString( svgString, 'image/svg+xml' ); // application/xml

			onLoad( doc.documentElement );

		}, onProgress, onError );

	}

};
```

**Comment by arrchhy** [comment]
Aw got it. Thanks mate!

**Comment by Igna07** [comment]
can you share your solution with your problem? i'm also dealing with the same issue. i wish you can teach me what did you do to load a svg file in three js and add it to your scene.

**Comment by bpetar** [comment]
This fix has some issues, I cant change the position of the SVGObject.

**Comment by rayhomme** [comment]
Is there a perspective on how this can be done? I need to implement an SVG editor inside a WebGL scene. Does it have to be a custom Loader?

**Comment by Mugen87** [comment]
> I need to implement an SVG editor inside a WebGL scene.

It's better to discuss such application related issues at the [forum](https://discourse.threejs.org/). 👍
