### ISSUE TITLE
WebVR video example not working on Oculus Go / Oculus Browser in VR mode

### ISSUE THREAD

**Issue by kmlx** [mrdoob/three.js#14380]
WebVR video example not working on Oculus Go / Oculus Browser in VR mode

com.oculus.browser (OculusBrowser/4.5.1.108860099 SamsungBrowser/4.0 Chrome/61.0.3163.141)

##### Description of the problem

Steps to reproduce:
0. grab an Oculus Go and open the Oculus Browser
1. go to https://threejs.org/examples/#webvr_video
2. press "Enter VR"
3. notice a black screen

Expected:
Video plays and is displayed in VR mode.

In the console we got the following warnings:
```
THREE.WebGLRenderer: Can't change size while VR device is presenting.
WebGLRenderer.setSize @ three.js:21995
13:53:05.330 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]RENDER WARNING: there is no texture bound to the unit 0
13:53:05.330 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]RENDER WARNING: there is no texture bound to the unit 0
13:53:05.347 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]RENDER WARNING: there is no texture bound to the unit 0
13:53:05.348 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]RENDER WARNING: there is no texture bound to the unit 0
13:53:05.366 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]GL ERROR :GL_INVALID_VALUE : glTexParameteri: unknown texture
13:53:05.367 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]GL ERROR :GL_INVALID_VALUE : glTexParameteri: unknown texture
13:53:05.367 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]GL ERROR :GL_INVALID_VALUE : glTexParameteri: unknown texture
13:53:05.367 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]GL ERROR :GL_INVALID_VALUE : glTexParameteri: unknown texture
13:53:05.367 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]GL ERROR :GL_INVALID_OPERATION : glTexImage2D: unknown texture for target
13:53:05.367 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]RENDER WARNING: there is no texture bound to the unit 0
13:53:05.367 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]RENDER WARNING: there is no texture bound to the unit 0
13:53:05.391 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]RENDER WARNING: there is no texture bound to the unit 0
13:53:05.391 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]RENDER WARNING: there is no texture bound to the unit 0
13:53:05.396 webvr_video.html:1 [.Offscreen-For-WebGL-0xc89fac00]GL ERROR :GL_INVALID_VALUE : glTexParameteri: unknown texture
```

##### Three.js version

- [ ] Dev
- [x] r93
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Oculus Browser

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Oculus Go

**Comment by mrdoob** [comment]
Confirmed. It's a browser bug though...

**Comment by DigiTec** [comment]
We have identified a state restore issue related to a performance feature. This will be fixed in Oculus Browser 4.7 unless we are able to pull it back into a maintenance release.

**Comment by frankolivier** [comment]
We fixed it in 4.6.2, which will be releasesed very soon.

**Comment by jonobr1** [comment]
@frankolivier any possibility of revealing a timetable to the release? Over at www.with.in we have a big update, but wanna hold off until we know it'll work in the Oculus Go.

**Comment by iansan5653** [comment]
@frankolivier Any idea when 4.6.2 is coming out? We have some projects at USF that rely on Go to function.

**Comment by frankolivier** [comment]
We are rolling out 4.6.2 right now; all users should have it in the next few weeks.

**Comment by oscarmarinmiro** [comment]
I don't know it this is related, but with Oculus Browser 4.1 on Oculus Go, if in chrome://flags I disable the WebVR optimizations (first option), I stop having issues (mostly noise in the texture) with WebVR videos (in AFrame 0.8.2)

**Comment by iansan5653** [comment]
@oscarmarinmiro It's definitely related -- I haven't received the 4.6.2 update yet but disabling that flag fixes the issue for me. Thank you!

**Comment by paulmasson** [comment]
Just got the update. The example works now.

**Comment by kmlx** [comment]
Thank you for all the help everyone.

I can confirm the WebVR video example is now working on Oculus Go / Oculus Browser in VR mode.
