### ISSUE TITLE
Standing matrix is always applied in r93

### ISSUE THREAD

**Issue by joshpatt2** [mrdoob/three.js#14398]
I upgraded my threeJS webvr project to r93 and found the y position of the head mountained display.  The differeince was the "this.standing" value is gone from VRManager.

Looks like this was removed from:
https://github.com/mrdoob/three.js/commit/a3f33be18c48124c3d5a0faf366685bde72587e6#diff-fdee169d721b24ed863f98ee8b9f67f4

But we added the matrix back without the boolean:
https://github.com/mrdoob/three.js/commit/cfd22c2c4f4621d770f3a5af68b0533e69af5959#diff-fdee169d721b24ed863f98ee8b9f67f4

Was this by design or was this something that got over looked? I

**Comment by joshpatt2** [comment]
This is breaking on Oculus Go/GearVR/Rift...Is there any work around or should the isStanding be added back in?

**Comment by mrdoob** [comment]
I can reproduce with https://threejs.org/examples/?q=webvr#webvr_rollercoaster

**Comment by joshpatt2** [comment]
Thanks for confirming, I added the code back on a local change but haven't done a pull request, i can do one now :)

Also could I get this pull request looked at:
https://github.com/mrdoob/three.js/pull/14114

Thanks!

**Comment by joshpatt2** [comment]
Current pull request for this issue:
https://github.com/mrdoob/three.js/pull/14802
