### ISSUE TITLE
How to achieve this effect？

### ISSUE THREAD

**Issue by treasureMoment** [mrdoob/three.js#14390]
How to achieve this effect？

![c45c85dacfbfdf438d49e0328c27ad26](https://user-images.githubusercontent.com/35365475/42023993-c5d8235e-7af3-11e8-9cfe-1b86ff5c7389.png)

when zoom ,the Arrows will follow changed 
help,give me an idea!

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
