### ISSUE TITLE
Refraction with custom geometry

### ISSUE THREAD

**Issue by CesarVonc** [mrdoob/three.js#14405]
##### Description of the problem

Hello,

I noticed an issue with the Refraction example :

https://threejs.org/examples/?q=refr#webgl_refraction

If I change the plane by a box and rotate it, some times the shader show weird things :

![image](https://i.imgur.com/rPdvldj.gif)

Modifications of the example :

Line 81 :
`var refractorGeometry = new THREE.BoxBufferGeometry( 4, 4, 4 );`

	function render() { 

		refractor.material.uniforms.time.value += clock.getDelta();
	
		refractor.rotation.y += 0.02;
	
		renderer.render( scene, camera );

	}

##### Three.js version

- [x] r94

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
`Reflector` and `Refractor` are intended to be used with a planar geometry.

**Comment by WestLangley** [comment]
>Reflector and Refractor are intended to be used with PlaneGeometry.

Actually, in `webgl_mirror.html`, a `CircleBufferGeometry` is used.

**Comment by Mugen87** [comment]
@mrdoob Should I correct your edit? 😉

**Comment by WestLangley** [comment]
You can also use an arbitrary shape:
```javascript
var shape = new THREE.Shape( points );
var geometry = new THREE.ShapeBufferGeometry( shape );
```

**Comment by CesarVonc** [comment]
I noticed that all kind of geometry seems to work if we keep the camera looking at the Z object axis.

Might be a nice feature to have it working for all point of view ?

**Comment by mrdoob** [comment]
> @mrdoob Should I correct your edit? 😉

Hehe, ops! I tried to make it more clear. I should have said `PlaneGeometry`, `CircleGeometry`, `ShapeGeometry`, ...

**Comment by mrdoob** [comment]
> I noticed that all kind of geometry seems to work if we keep the camera looking at the Z object axis.
>
> Might be a nice feature to have it working for all point of view ?

@Mugen87 Have you investivated this?

**Comment by Mugen87** [comment]
The algorithm of `Reflector` and `Refractor` assumes there is a single reflection/refraction plane. I think you need a different approach if you want to support an arbitrary amount of planes defined by a group of planar polygon faces.
