### ISSUE TITLE
using LineDashedMaterial and LineSegments the last line is solid?

### ISSUE THREAD

**Issue by bung87** [mrdoob/three.js#14407]
##### Description of the problem

http://jsfiddle.net/7y65xgab/26/
##### Three.js version

- [ ] Dev
- [x] r94
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
The `position` attribute must have 3 components.

http://jsfiddle.net/7y65xgab/30/

**Comment by bung87** [comment]
ok, thanks ! solve my problem, I use LineBasicMaterial and BufferAttribute with specified the itemSize 2 without this problem, so I thought I could do the same thing with LineDashedMaterial:), feel free to close this issue.
