### ISSUE TITLE
Flow and Typescript annotations

### ISSUE THREAD

**Issue by nelsonvassalo** [mrdoob/three.js#14421]
In the prospect of fully modularizing the library in the future (as close as it now), shouldn't we have TypeScript and Flow annotations for Three.js? I think there's a .ts library already, would it be hard to transpile it to FLow types?

##### Three.js version

- [x] Dev
- [ ] r94
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
We are not doing any support for type script related issues. The type definitions itself are not maintained in a different [repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/three).

**Comment by bhouston** [comment]
I'd like to revisit typescript support in Three.JS at some point, it is pretty amazing frankly.
