### ISSUE TITLE
Render video on sphere texture on react-native-webgl

### ISSUE THREAD

**Issue by devdivr** [mrdoob/three.js#14434]
I implemented a video player on sphere texture on WebGlView but occurs an error(_which is 'undefined is no an object (evaluation video.readyState)_) while renderer's rendering. I didn't catch what was wrong. Any idea to solve this issue or examples to catch it?
<img width="299" alt="screen shot 2018-07-08 at 5 15 14 pm" src="https://user-images.githubusercontent.com/5515672/42421239-92b117ec-82d2-11e8-99b2-45dea4328244.png">

`import React, {Component} from "react";
import {StyleSheet, View} from "react-native";
import {WebGLView} from "react-native-webgl";
import THREE from "./three";
import Video from "react-native-video";

type Props = {};

const MAX_FOV = 20;

let currentRenderId = 0;

export default class App extends Component<Props> {

  videoSource = "url.mp4";

  handleVideo = () => {
    return <Video
      ref={this._assignRoot}
      source={{uri: this.videoSource}}
      sytles={styles.video}/>
  }

  render() {
    return (
      <View style={styles.container}>
        <WebGLView style={{width: 2048, height: 512}} onContextCreate={this.onContextCreate}/>
      </View>
    );
  }

  onContextCreate = (gl: WebGLRenderingContext) => {
    let renderId;
    let camera, scene, mesh, texture;

    const rngl = gl.getExtension("RN");

    const {drawingBufferWidth: width, drawingBufferHeight: height} = gl;

    const renderer = new THREE.WebGLRenderer({
      canvas: {
        width,
        height,
        style: {},
        addEventListener: () => {
        },
        removeEventListener: () => {
        },
        clientHeight: height
      },
      context: gl
    });
    renderer.setSize(width, height);

    function init() {

      this.state = {
        phiStart: (Math.PI / 2 * 3) - (-Math.PI / 2.6),
        phiLength: -Math.PI / 1.3,
        thetaStart: (Math.PI / 2) - Math.PI / 12,
        thetaLength: Math.PI / 6,
        fov: MAX_FOV,
        radius: 10,
        widthSegments: 16,
        heightSegments: 4,
      };

      const {phiStart, phiLength, thetaStart, thetaLength, fov, radius, widthSegments, heightSegments} = this.state;
      camera = new THREE.PerspectiveCamera(fov, width / height, 0.1, 1000);
      currentRenderId++;
      renderId = currentRenderId;

      scene = new THREE.Scene();

      let geometry = new THREE.SphereGeometry(radius, widthSegments, heightSegments,
        phiStart, phiLength,
        thetaStart, thetaLength
      );

      let video = this.handleVideo;

      texture = new THREE.VideoTexture(video);
      texture.minFilter = THREE.NearestFilter;
      texture.magFilter = THREE.NearestFilter;
      texture.format = THREE.RGBFormat;

      let material = new THREE.MeshBasicMaterial({map: texture});
      mesh = new THREE.Mesh(geometry, material);
      scene.add(mesh);

      camera.position.z = 0;
    }

    const animate = () => {
      texture.needsUpdate = true;
      renderer.render(scene, camera);
      // }
      mesh.rotation.x = this.rotateX;
      mesh.rotation.y = this.rotateY;

      requestAnimationFrame(animate);

      gl.flush();
      rngl.endFrame();
    };

    init();
    animate();
  };
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  video: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
});`

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
