### ISSUE TITLE
Is there any limit on android or any mobile phone?

### ISSUE THREAD

**Issue by Devilsparta** [mrdoob/three.js#14440]
##### Description of the problem
I've tried a test on an android huawei mobile phone.

In this test, I just create a scene , a renderer and a camera, use `requestAnimationFrame` to call renderer.update() every time.

the Fps is not stable on chrome.It's only 30 - 40 fps.

is there performance issue or limit on mobile phone?

if anyone can tell me how to optimize performance, that would be better.

thanks for answering this.

##### Three.js version

- [ ] Dev
- [x] r94
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please ask such help requests at the [forum](https://discourse.threejs.org/) or stackoverflow.
