### ISSUE TITLE
Increase upper limit on number of morph targets / blend shapes

### ISSUE THREAD

**Issue by s5g** [mrdoob/three.js#14441]
##### Description of the problem

As discussed in #6465 the maximum number of rendered morph targets is either 8 (targets have vertices only) or 4 (targets have vertices and normals). This limit is related to the WebGL MAX_VERTEX_ATTRIBS value which in turn is based on GPU support.

http://webglstats.com/webgl/parameter/MAX_VERTEX_ATTRIBS
http://webglstats.com/webgl2/parameter/MAX_VERTEX_ATTRIBS

However many models, in particular those used for facial animation, may have more than 4 or 8 active blendshapes. So currently these models will not render correctly.

The suggestion is to look for ways to increase the limit.

##### Three.js version

- [x] Dev
- [x] r94

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by makc** [comment]
I have patched 3js for someone, doubling the limit. Worked for them with no problems. It is not too hard to have this as a setting

**Comment by mrdoob** [comment]
Yeah, a way of changing this setting would be nice.
Anyone up for giving it a go?

**Comment by JosephCoppola-FW** [comment]
@makc, did you achieve doubling the limit by simply changing the maxAttributes and maxVertexAttributes in WebGLCapabilities.js and WebGLState.js to a number that works for you?

**Comment by makc** [comment]
@JosephCoppola-FW probably different GPU. [This](http://webglstats.com/webgl/parameter/MAX_VERTEX_ATTRIBS) says only 1 in 5 GPUs can do more than 16 attributes.

My reading of @jspdown [comment](https://github.com/mrdoob/three.js/issues/6465#issuecomment-240031471) is that they still use 8 targets on GPU:
> Those that are mostly used for the initial configuration of the model and that aren't supposed to be updated [run] on the CPU.
> ...to configure a human body that had ~32 morphtargets. Only 6 of them needed real-time updates, others were only used to pre-configure the model.

**Comment by makc** [comment]
btw, 16 attributes is actually 16 * 4 numbers. so if we consider 3 numbers for the single set of normals and 2 for UVs, potentially there can be (16*4-3-2)/3 = 19 morph targets.

**Comment by marcoantonioroldan** [comment]
> He parcheado 3js para alguien, duplicando el límite. Trabajó para ellos sin problemas. No es muy difícil tener esto como escenario

Could you share the way you did it?

**Comment by marcoantonioroldan** [comment]
I am currently working with a model in .glb format, it is a humanoid and semi-realistic facial expressions require at least 14 shape keys / morphing targets. Given this scenario of a limit of 8, is there a way to increase them? Can anyone share it?

**Comment by JosephCoppola-FW** [comment]
@marcoantonioroldan I posted a detailed shader material example in #15556 

Specifically here -> https://github.com/mrdoob/three.js/issues/15556#issuecomment-478161986

**Comment by Mugen87** [comment]
Merging into #21636.
