### ISSUE TITLE
ColladaLoader: data is undefined

### ISSUE THREAD

**Issue by Splizard** [mrdoob/three.js#14452]
The ColladaLoader fails to load this model.
https://raw.githubusercontent.com/0ad/0ad/master/binaries/data/mods/public/art/meshes/skeletal/bear.dae

Results in this error (in Firefox):
TypeError: data is undefined ColladaLoader.js:215:1

Here is the fiddle.
https://jsfiddle.net/tfgv4sd5/

I can provide more Collada files that reproduce this issue if requested :+1:

**Comment by Mugen87** [comment]
The problem in this case is that the Collada file does not contain any material definition although the geometry refers to a material instance with key `material0`. So the model partly causes the loading problem. 

There is already a PR to solve this issue by applying a default material to the object: #13172

**Comment by Splizard** [comment]
Ah, I can confirm that with #13172 changes applied, the model loads.

**Comment by mrdoob** [comment]
#13172 has been merged 🙌
