### ISSUE TITLE
ColladaLoader: Add support for node processing with non-unique IDs

### ISSUE THREAD

**Issue by Splizard** [mrdoob/three.js#14453]
The ColladaLoader fails to load this model.
https://raw.githubusercontent.com/0ad/0ad/master/binaries/data/mods/public/art/meshes/skeletal/elephant_african_bush.dae

Results in this error (in Firefox):
too much recursion ColladaLoader.js:3377:8

Here is the fiddle.
https://jsfiddle.net/L923p7ke/

I can provide more Collada files that reproduce this issue if requested :+1:

**Comment by Mugen87** [comment]
Two nodes of your `DAE` file have the same id `Elephant`.
```
<node id="Elephant" name="Elephant" type="NODE">
        <matrix sid="transform">1.3 0 0 0 0 1.3 0 0 0 0 1.3 0 0 0 0 1</matrix>
        <node id="Elephant" name="Elephant" sid="Elephant" type="JOINT">
```
This is something `ColladaLoader` can't handle since it expects that the `id` is unique.

**Comment by Splizard** [comment]
This resolves the issue for the models I am loading.
```
function parseNode( xml ) {

    ...

    if (hasNode(data.id)) { 
        console.warn("Duplicate id", data.id, "(ignoring)")
    } else {
        library.nodes[ data.id ] = data;
    }
    return data;

}
```

**Comment by mrdoob** [comment]
@Splizard Would you like to do a PR with the fix?

**Comment by Mugen87** [comment]
I don't think this change is correct. You are parsing the node but don't add it to the node library? What if other parts of the Collada file want to refer to the node?

**Comment by Splizard** [comment]
It doesn't add support for non-unique IDs, however, it does provide a more helpful warning and fixes the "too much recursion" error.
