### ISSUE TITLE
Local space clippingPlanes of material

### ISSUE THREAD

**Issue by yaoyao-cn** [mrdoob/three.js#14463]
##### Description of the problem

Feature Request:

the default clipping plane of material is in world space. this makes it not very convenient if we want the clip plane to follow the Mesh object just like a child of it.

if we treat a clip plane as a Object3D, and the material hold a reference to it. thus we can make the clip plane either in world or in local space by changing the parent of clip plane.

##### Three.js version

- [ ] Dev
- [x] r94
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
You can clip in local space instead of world space if you transform your desired clipping plane prior to rendering.
```javascript
mesh.onBeforeRender = function() {

	this.material.clippingPlanes[ 0 ].copy( clippingPlane ).applyMatrix4( this.matrixWorld );

};
```

**Comment by yaoyao-cn** [comment]
@WestLangley clever idea! that's exactly what i need. thank you !
i think i should not only overwrite the onBeforeRender  function but also the onAfterRender, **because the materials i use are shared between meshes. and i need reset the clip plane in onAfterRender.**

the only thing i worry about is the performance. i wander if it will impact the performace, because i change the clip plane of material every fame. it seems that a uniform cache is maintained internally, right ?
@Mugen87 @WestLangley is it will impact the performace if i change the clip plane every frame?
thank you very much!

**Comment by yaoyao-cn** [comment]
i think it will not impact the performance.
the manual says:
All uniforms values can be changed freely (e.g. colors, textures, opacity, etc), values are sent to the shader every frame
https://threejs.org/docs/#manual/introduction/How-to-update-things
