### ISSUE TITLE
Why delete convert_obj_three.py, in the new version of the project?

### ISSUE THREAD

**Issue by xujinjiao** [mrdoob/three.js#14461]
Why delete convert_obj_three.py, in the new version of the project?

The latest version of threejs has no convert_obj_three.py, but sees convert_to_threejs.py in the FBX directory.

**Comment by Mugen87** [comment]
see 89cb329fec39cd7c570752b09352b70188cac89b

Use [obj2three](https://github.com/mrdoob/three.js/blob/dev/utils/converters/obj2three.js) instead.
