### ISSUE TITLE
Incorrectly weighted samples in PMREMGenerator

### ISSUE THREAD

**Issue by akhosravian** [mrdoob/three.js#14469]
##### Description of the problem

I noticed some glb files using PBR materials looked much more metallic in three.js under a particular environment map compared to other viewers (Substance Painter and Unity). After some investigation I believe this is due to PMREMGenerator not weighting lighting samples correctly -- each sample is weighted the same which causes HDR environment maps with large variations in intensity to become unsightly when convolved.

Here's a tonemapped image that shows the problem (notice what happens to the sun in the bottom right of the bottom left face): https://raw.githubusercontent.com/akhosravian/threejs_pmrem_bug/master/pmrem.JPG

Here's a screenshot of a line of sphere of increasing roughness using the map from that image:
https://raw.githubusercontent.com/akhosravian/threejs_pmrem_bug/master/issue.jpg

Live examples (the assets here are rather large so it takes a bit to load): 
https://jsfiddle.net/r07gpq2a/
https://jsfiddle.net/tkqcfraz/

Standalone project: https://github.com/akhosravian/threejs_pmrem_bug

Is there a way to work around this?
 
##### Three.js version

- [ ] Dev
- [x] r94
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by bhouston** [comment]
The theoretical foundations for the weighting of the PMREM generator as noted in the comment at the start of the file are approximate.  It needs to be fixed so that it has a sound theoretically foundation.

@richardmonette seemed to indicate he maybe willing to improve the theoretical foundations but I think he then never got around to it: https://github.com/mrdoob/three.js/pull/13693#issuecomment-376736623

**Comment by richardmonette** [comment]
@akhosravian Have you tried removing the arbitrary adjustments https://github.com/mrdoob/three.js/blob/dev/examples/js/pmrem/PMREMGenerator.js#L103 and https://github.com/mrdoob/three.js/blob/dev/examples/js/pmrem/PMREMGenerator.js#L109 ?

Those two lines in particular had jumped out to me as particular tweaks / optimizations that may not have as strong a theoretical basis.

**Comment by richardmonette** [comment]
Another question I had hoped to find time to resolve was whether radiance and irradiance as correctly being treated as separate maps. As I understand it, the PMREM is handling the 'pre-filtered environment map' (https://learnopengl.com/PBR/IBL/Specular-IBL) but there should actually be a separate irradiance map, and that would require slightly different pre-filtering. The linked article above has a pretty good explanation of this split-sum approximation approach, my hope had been to compare the existing three.js implementation to their recommendations, and propose any adjustments/improvements accordingly.

**Comment by akhosravian** [comment]
Thanks for the replies y'all. @richardmonette I did try removing those values, but it didn't make it obviously better. Bumping the number of samples up (as in https://jsfiddle.net/fc47m8pg/) helps with the visual artifacts, but I think causes over brightening. 

I may take a look at applying a better fix using the links in the thread and will send along a PR if I do.
