### ISSUE TITLE
InstancedBufferGeometry with dynamic size, best practice?

### ISSUE THREAD

**Issue by navigator117** [mrdoob/three.js#14472]
I'm current using InstancedBufferGeometry & InstancedBufferAttribute to do geometry updating for a large amount of instances (> 5000).  The InstanceBufferAttribute like offset\rotation\color was create with Float32Array underlying. when remove instance I "splice" these arrays, when adding I push back data to these arrays, and set maxInstancedCount & needsUpdate accordingly. Everything works fine when the dynamic 
add/remove count was small, but when the  count increase, these operations seems waste too much cpu cycles, as there are FPS drops frequently.
Is there a best practice to handle this situation?
 If I know the max amount of instances, is it possible to add a "flag" InstanceBufferAttribute, and when removing I just set flag at the index, when adding I just clear flag at the index. the shader can see this flag and just "ignore" those instances with flags set?

**Comment by WestLangley** [comment]
This is NOT a help site. Please do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
