### ISSUE TITLE
Add `DrawGeometry` function to WebGLRenderer

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#14476]
Hello! 
THREE provides a really nice, quick approach for setting up a scene but there are times when the default render path isn't ideal. I want to propose adding a function like `DrawGeometry` to the WebGLRenderer API.

### WebGLRenderer.DrawGeometry(<Geometry|BufferGeometry\>, <Material\>, <Matrix4\>, <Camera\>, <Scene\>, <RenderTarget\>, <Options\>)
Draws the geometry to the render target immediately.

#### Geometry|BufferGeometry
The geometry to render.

#### Material
The material to render with.

#### Matrix4
The world matrix to transform the geometry.

#### Camera
The camera to render with.

#### Scene
The scene to render in the context of (for lighting, fog, etc).

#### RenderTarget
The target to render to.

#### Options
A set of draw options including things like `frustumCulled`.

### Use Cases
At a high level this would afford more flexibility to create custom render paths to suit different types of optimizations and scene complexity.

- In cases where you're dealing with tens or hundreds of thousands of meshes in a scene it can be beneficial to save transform information in a minimal representation to save memory (an array of matrices, for example). This can't be done all the easily at the moment because THREE requires Object3Ds and Meshes to render.
- If a set of visible geometry is already known (through a custom octree frustum culling implementation or precomputed visible sets) there's no reason to have THREE iterate over all geometry in the scene and it can be much slower to do so. This lets you control what gets drawn and iterated over.
- Some effects are just convenient to implement with a custom draw and don't need an object in the scene hierarchy.
- You may want to draw for only X milliseconds during a frame -- this would let you measure how long you've spent drawing so far. 

In a couple of these cases the solution at the moment is to remove everything (or almost everything) from the scene and rebuild it specifically so THREE doesn't doesn't spend time iterating over everything, which can take time in itself.

Thoughts?

**Comment by Mugen87** [comment]
Why not using [WebGLRenderer.renderBufferDirect](https://threejs.org/docs/#api/renderers/WebGLRenderer.renderBufferDirect) for this?

**Comment by Mugen87** [comment]
> How are light uniforms set on the material in this case? Do they need to be updated manually?

No, that happens within `renderBufferDirect()`. But you need to call at least `.compile()` so lights and shadows are correctly prepared. Normally you use `renderBufferDirect()` for special objects rendered along the normal workflow. Lensflares are a good example for this.

**Comment by Mugen87** [comment]
> It looks like the documentation is a out of date and could be updated a bit, as well.

Should be fixed with 1658d119a10e331203795bd531e89e56480a57e2

**Comment by pailhead** [comment]
>Why not using WebGLRenderer.renderBufferDirect for this?

I think this had some issues before, `renderBufferDirect` may not be enough.

**Comment by gkjohnson** [comment]
Thanks @Mugen87. It does seem like there are quite a few problems with it, at the moment. Ideally I'd like to be able to do this to draw a bunch of sphere that each have a random color.

```js
// ... set up scene, camera, object states

// update cached scene info like lights uniforms etc so
// it can be added onto the materials on draw (I think that's
// what this is for?)
renderer.compile( scene, camera );

renderer.setRenderTarget( null );
renderer.clear();

// reusable object, geometry, material
var object = new THREE.Object3D();
var material = new THREE.MeshBasicMaterial();
var geometry = new THREE.SphereBufferGeometry( 1, 40, 40 );
for ( var i = 0; i < objectStates.length; i ++ ) {

    // randomize the color
    material.color.r = Math.random();
    material.color.g = Math.random();
    material.color.b = Math.random();

    var s = objectStates[ i ];
    object.matrixWorld = s.matrixWorld;
    renderer.renderBufferDirect( camera, null, geometry, material, object, null );

}

```

However I'm finding a few issues with it:
- In the above code all the geometry will draw with the same color every frame instead of each with a different random color, which makes it seem like the draw calls are getting queued?
- It seems that you _have_ to call `renderer.render` and draw a scene with the geometry you want to render first in order to called `renderBufferDirect`. Otherwise there are errors (it seems like the geometry isn't initialized?)
- The camera matrix used in the call to `renderer.render` is the one used when drawing with `renderBufferDirect` rather than the one provided in the function call.
- Setting the objects' `o.material.visible` property to `false` causes the material's matrices to not be updated when calling `renderBufferDirect`, even though it shouldn't be used. It seems like the same thing happens if an object is considered frustum culled, making objects that move off the edge of the screen "stick" to the edges.

I haven't had a chance to look at the source to see what exactly is going on but I'll try to put together an example that repros all these problems so it's more clear. It seems like with some changes this could be used for what I want. Maybe the name of the function could be updated, though? I'm also not super clear on how `compile` plays into all this -- is it bad to call it every frame?

Finally, what's the difference between `renderBufferDirect` and `renderBufferImmediate`, if anything (other than the function signatures)?

Thanks!

**Comment by pailhead** [comment]
@gkjohnson

Does this sound like a vaguely similar problem? The issue with `renderBufferDirect` was that it used some stuff from the closure that you didn't have available outside of `WebGLRenderer`.

https://github.com/mrdoob/three.js/issues/12144

**Comment by gkjohnson** [comment]
@pailhead it definitely sounds like a similar need.

> The issue with renderBufferDirect was that it used some stuff from the closure that you didn't have available outside of WebGLRenderer.

Can you explain this a little bit more? I feel like I'm providing everything it needs in order to do what I expect if it's using the cached lighting information that `compile` initializes.

> Correct, don't call it every frame. WebGLRenderer will actually do that under special conditions (material.needsUpdate for example).

Even if I never call `renderer.render`? I want to use `renderBufferDirect` exclusively in some cases. If I have a bunch of moving lights how are they updated? Is there any way to know if `compile` has already been called on that scene / camera? 

Thanks!

**Comment by pailhead** [comment]
>I'm also not super clear on how compile plays into all this -- is it bad to call it every frame?

Correct, you shouldn't recompile shaders every frame. Under special conditions (`material.needsUpdate === true`) `WebGLRenderer` will do this for you. 

I think that this is related to:

https://github.com/mrdoob/three.js/issues/12144

I think my scenario was that i had uninstantiated geometry as far as `WebGLRenderer` is concerned. An equivalent of `.compile()` may have been missing at that time for geometries. 

The issue i think is this:
https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1248

**Comment by pailhead** [comment]
Your code:
```
// ... SET UP SCENE, camera, object states

//...

// reusable object, geometry, material
var object = new THREE.Object3D(); 

//...
```

So you've set up a scene graph, and then made an object outside the scene graph. `renderer.compile()` never encountered your 
```
var material = new THREE.MeshBasicMaterial();
```

**Comment by gkjohnson** [comment]
Yeah I think that's some of the same problem I'm having, as well. But I don't think you should have to manually call `objects.update( object )` to perform a draw. This is what I noticed when looking over the renderer code, some of which you mentioned:

- There's a lot happening in `render` that could be happening in `renderBufferDirect`, such as [initializing the geometry](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1283) (and calling skeleton.update) and [updating the modelView matrices](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1388).

- Shaders look like they're fine and compiled as-needed without calling the compiled function because `initMaterial` is [called if needed in `setProgram`](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1620).

- One of the only benefits to calling compile ahead of time (other than to precompile shaders) is to set the [currentRenderState variable](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L948) to something, which [`render` sets to null once its finished](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1160) so it can't be relied on.

- The reason the materials aren't updating is because the renderer assumes that if the program is currently used [then nothing needs to be updated](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1633) and the `render` function resets the cache by [setting the _currentCamera to null (which is checked in setProgram)](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1035)

I'd be interested in updating the renderer to allow for the types of operations I'm talking about. I understand that some or a lot of what I mentioned is there for the sake of optimization. Does this belong in a new function? Would any of this be affected by the new WebGL2Renderer?

Thoughts @mugen87? @mrdoob?

Thanks!

**Comment by Mugen87** [comment]
@gkjohnson Adding a function with all your requirements would provide more flexibility, yes. But I'm not sure what this means for performance and code complexity. I think we need to solve problems like #14121 first before we add a new API for rendering. `onBeforeRender` is a good example that shows how simple features can add a lot of complexity to the renderer if we want consistent behavior/correct output for different use cases.

> I'd be interested in updating the renderer to allow for the types of operations I'm talking about.

If you want to do this, I suggest you intensively test your code before submitting a PR. I mean don't test your new function for your specific use case but also test it within different scenarios (e.g. nested render calls, post-processing, multiple scenes). Also do performance test in order to ensure your solution if fast.

**Comment by gkjohnson** [comment]
@Mugen87 Makes sense. It would also be possible to add a few new functions that achieve this functionality without touching the current render path at all. I'll think through it a bit more when I have more time.

Also, here's a repro of some of the issues with RenderBufferDirect with some callouts in the comments. You can see if you move the camera around that the balls "stick" to the side of the screen because their matrices aren't getting updated.

[renderBufferDirect-repro.zip](https://github.com/mrdoob/three.js/files/2208074/renderBufferDirect-repro.zip)

Thanks!

**Comment by gkjohnson** [comment]
It might also be worth noting that this per-object motion blur example (and similar effects) are a use case for this type of functionality:
https://github.com/mrdoob/three.js/issues/14476

**Comment by pailhead** [comment]
Not really. It's just one of the many many examples of graphics algorithms you can use a pattern like this for.

**Comment by gkjohnson** [comment]
Ha, fair enough!

**Comment by pailhead** [comment]
What would probably be helpful is to give some thought to whats going on and see if some concerns overlap and if some refactoring or renaming could be done.

**Comment by gkjohnson** [comment]
> I don't like the signature that much in your proposal

Understood -- I've been meaning to write up a new set of functions to propose when I got a chance after our discussions. This focuses more on adding functions to enable the functionality we're talking about instead of renaming. Heres are some thoughts on what an API might look like, the types of use cases they accommodate and the (hopefully) minimal impact on the current state of THREE:

## New Functions
### WebGLRenderer.compileShader( \<Material | Array\> )
### OR WebGLRenderer.compileMaterial ( \<Material | Array\> )

Takes a Material or array of materials to compile and upload to the GPU. Currently this is automatically done [here](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1620) if the material isn't already compiled. This lets you compile materials that aren't currently in scenes.

##### Note
- This might require changes to `WebGLProgram.getParameters`

##### Rough Implementation
```js
compileShader( material ) {

    if ( Array.isArray( material ) ) {

        material.forEach( m => this.uploadGeometry( m ) );
        return;

    }

    // "initMaterial" takes a material, fog, and an object. The function is resilient
    // to `fog` being undefined and the fog and the object are otherwise only passed to
    // WebGLProgram.getParameters(), which just needs to be changed to handle the case
    // where object === undefined.
    initMaterial( material, undefined, undefined );

}
```

### WebGLRenderer.uploadGeometry( \<Geometry | Array\> )

Takes a Geometry to upload to the GPU in preparation for rendering. Currently this _cannot_ be done without adding an object with the material into a scene.

##### Note
- This currently requires a handle to a `Mesh` object to upload the geometry, but it looks like that could probably be removed eventually.

##### Rough Implementation
```js
var tempMesh = new THREE.Mesh();
uploadGeometry( geometry ) {

    if ( Array.isArray( geometry ) ) {
        
        geometry.forEach( g => this.uploadGeometry( g ) );
        return;

    }

    // Currently the renderer requires that a Mesh be passed to
    // objects.update() for some reason. Looking at the code it seems
    // like there's not a whole lot that requires the object. It would
    // seem that it's only there to handle the case when THREE.Geometry
    // is used. It looks like that could be changed but it doesn't have
    // to happen here.
    tempMesh.geometry = geometry;
    objects.update( tempMesh );

}
```

### WebGLRenderer.setRenderState( \<Scene\>, \<Camera\> )

Sets up lights to be used on subsequent calls geometry and set the current render state.

##### Rough Implementation
```js
setRenderState( scene, camera ) {
    
    currentRenderState = renderStates.get( scene, camera );
    currentRenderState.init();
    
    scene.traverse( o => {

        if ( o.isVisible && o.isLight ) {
            
            currentRenderState.pushLight( object );
            
            if ( o.cashShadow ) {

                currentRenderState.pushShadow( object );

            }

        }

    } );
    currentRenderState.setupLights( camera );

}
```

### WebGLRenderer.renderBufferDirect( ..., \<forceUpdateMaterial:Boolean\> )

An update to `renderBufferDirect` so that the material can be modified between draw calls by setting `forceUpdateMaterial` to `true`. The flag would need to be added to `setProgram`, as well.

##### Note
- `uniformsNeedUpdate` on the ShaderMaterial does _most_ of the work needed here, but sknning doesn't seem to update appropriately.
- Documentation should be updated to say that the worldMatrix needs to manually be made up to date before calling this function.
- It would also be nice if this function would upload the geometry if it hasn't been already but I'd like to minimize changes to the existing render path.

## Functions to Remove
### WebGLRenderer.compile(...)
It doesn't seem like there's a reason that the scene context or camera are needed in order to compile a material and the `compileShader` function accomodates the existing functionality.

---

I think this should let you render a bit more like I laid out before _without_ ever calling `render()` and I think should handle the cases you mentioned @pailhead. It should also minimize changes to the current render path:
```js
// ... set up scene, camera, object states
// ... initialize the materials and geometry
var material = new THREE.MeshBasicMaterial();
var geometry = new THREE.SphereBufferGeometry( 1, 40, 40 );
renderer.compileShader( [ material, ...] );
renderer.uploadGeometry( [ geometry, ...] );
var object = new THREE.Object3D();

// ...

function renderLoop() {
    
    // Prep the target
    renderer.setRenderTarget( null );
    renderer.clear();

    // Prep the lights and scene
    renderer.setRenderState( scene, camera );

    // reusable object, geometry, material
    for ( var i = 0; i \< objectStates.length; i ++ ) {

        // randomize the color
        material.color.r = Math.random();
        material.color.g = Math.random();
        material.color.b = Math.random();

        var s = objectStates[ i ];
        object.matrixWorld = s.matrixWorld;
        renderer.renderBufferDirect( camera, null, geometry, material, object, null );

    }
}
```

One thing I'm still confused about, though is why the camera matrices don't seem to be updated when calling `renderBufferDirect` but I'll have to take a look at that at another time. I'm sure there's more going on that I'm not fully grasping but I might try adding a few of these functions and seeing what does and doesn't work and tracing the flow the renderer a bit more.

**Comment by Mugen87** [comment]
Sorry, I'm in no way open for the API proposed in your last comment. Something like `compileShader()` or `setRenderState()` is too low level. 

Logic like render lists and states, shader programs or performing draw calls is engine-internal and not intended for exposing. This will only lead to additional code paths, complexity and it will make it harder for us to optimize the renderer. 

I think it's best if this issue and #14578 are closed. If devs need more controls about the render process, it's to write a custom rendering engine.

**Comment by gkjohnson** [comment]
Some other PRs I've submitted that I think are more in line with three.js patterns will address the issues I originally created this for which I'm hoping can be revisited once JSM and ES6 conversion have been addressed. I will open a new issue if this becomes a need again.

Thanks!
