### ISSUE TITLE
Bizarre bug causes random colours

### ISSUE THREAD

**Issue by liquidmetalrob** [mrdoob/three.js#14491]
I've found a bizarre bug that causes objects to appear in random colours even when the colour is specified in the material.
It seems to happen when a material is accessed through a dictionary with a variable as a key.
So, for example:

`j = 0`
`k = 1`
`o = 1`
`m = {j:material, k:material}[o]`

You can see it happening in this [Fiddle](https://jsfiddle.net/liquidmetalrob/ft1ryd0n/4/).
Every time you refresh it you get different random colours.

I'm using the latest version of three.js, 94 in Chrome on Windows.

**Comment by donmccurdy** [comment]
JavaScript does not allow variables on the left side of the color in an object literal that way — those are interpreted just as "j" and "k" strings. As a result, `m` is undefined and the mesh gets a randomly colored material (https://github.com/mrdoob/three.js/blob/master/src/objects/Mesh.js#L27) on each pageload.

See https://stackoverflow.com/questions/6500573/dynamic-keys-for-object-literals-in-javascript. In newer versions of JS you could do this:

```
j = 0
k = 1
o = 8
m = {[j]:material, [k]:material}[o]
```

but even so note that there is no value for "8" and the result will be undefined.

**Comment by liquidmetalrob** [comment]
That would explain it.
That thing with the 8 was just a mistake typing it in.
