### ISSUE TITLE
Make lookAt work with the scenegraph?

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#14496]
As it is `lookAt` says it doesn't work if the object you're calling it for has parents etc... I was wondering what you all think about removing that restriction. My guess is most projects only call `lookAt` at most once a frame to aim the camera so making it a little heavier is not likely to affect performance since it's not the kind of function to be called 1000s of times a frame.

On the other hand, making it more flexible makes it more useful for things like pointing a character's head at an object of interest. Pointing a security camera what what it's tracking. Pointing a gun turret at it's target. 

Thoughts?

Here's a sample

https://jsfiddle.net/greggman/7gdux2ch/

and a preliminary pull request below

**Comment by Mugen87** [comment]
I vote for this change. Unity also respects the parent transformation when using `lookAt()`. It also useful for #14444

**Comment by Mugen87** [comment]
BTW: Cool fiddle 😊

**Comment by pailhead** [comment]
>Thoughts?


```javascript
const myVec = new THREE.Vector3()
const myNode = new THREE.Object3D()

myNode.updateMatrixWorld()
myNode.localToWorld(myVec)

thing.lookAt(myVec)
```

With the `localToWorld` this limitation is not so far detached from the scene graph. Personally, i would maybe avoid overloading `lookAt` and do `lookAtNode`, i believe this conversation was had in the past.

**Comment by greggman** [comment]
I'm just going by pretty much every other 3D engine except three.js.  There's matrix lookAt which is of course the standard function. Then there's scene graph lookAt which in 3DSMax, Maya, Unity, Unreal, and most other engines do take the position in the scene graph into account.  It really makes zero sense for scene graph functions not to work with the scene graph. In other words. `THREE.Matrix4.lookAt` deals with matrices. `THREE.Object3D.lookAt` deals with the scene graph. So you already have 2 functions, one for each case.


All of them require the camera to be part of the scene so that you can put cameras anywhere (like [the fiddle](https://jsfiddle.net/greggman/7gdux2ch/)).

**Comment by WestLangley** [comment]
@greggman Don't worry, this will be fixed. It is going to have to be implemented in conjunction with some additional changes to ensure matrix updates during graph traversal are efficient.

**Comment by greggman** [comment]
Does it need to wait for faster graph traversal? If I understand correctly the PR above won't really add any perf regressions for use cases that are already in use. So, for people that start using it for new uses cases their code might be a little slow (though again this is not generally something called 1000s a times a second) and then, as the graph traversal stuff is updated it will just get faster for them. My point being I'm not sure why this feature needs to be gated on other things getter faster.

**Comment by looeee** [comment]
> with some additional changes to ensure matrix updates during graph traversal are efficient.

@WestLangley are you talking about #14138?

**Comment by Mugen87** [comment]
> Does it need to wait for faster graph traversal? 

From my point of view, no. The PR can be merged ahead of this.

**Comment by pailhead** [comment]
>There's matrix lookAt which is of course the standard function. Then there's scene graph lookAt...

This is actually a great point. `SceneNode.lookAt()` should probably look at another scene node. The `Matrix4` one makes sense to look at a vector.

**Comment by greggman** [comment]
any progress on this? I really like to use it 😜  Of course I can do it in my own code but would love to be able use a built in solution.

Does the solution need to be perfect today? `lookAt` is unlikely to be called 100s of times per frame so even an inefficient solution is better than non since `lookAt` can't be used much today because of its limitations. 

>> If I understand correctly the PR above won't really add any perf regressions for use cases that are already in use.
>
> I claim it will, if it is implemented as in your example. Every scene node, except the scene itself, has a parent.

My point wasn't there are zero perf regressions, my point is they are unimportant. Because `lookAt` is not that useful today no one is calling it 100s of times a frame. They are likely calling it just once for their one camera so in the scheme of all of their code their code will get 0.0001% slower. In other words this doesn't have to wait for a perfect solution (whatever that happens to be).

**Comment by WestLangley** [comment]
>any progress on this? 

#14517 has been available for a month. See if it works for you.
