### ISSUE TITLE
GLTFLoader fails with custom inherited array.prototype properties

### ISSUE THREAD

**Issue by Remi-Tribia** [mrdoob/three.js#14501]
##### Description of the problem

Hi! I use forEach2 to iterate over arrays and I noticed it throws an error with GLTFLoader, because the "for...in" loop iterate over the inherited prototype properties too and it can't find the key named "forEach2" obviously...

I think testing with hasOwnProperty can't hurt : 

https://github.com/mrdoob/three.js/blob/5ac20d718943e23d40e5215f15452ec2240a2c58/examples/js/loaders/GLTFLoader.js#L280-L282
```
for ( var lightId in lights ) { // line 280
	if ( ! lights.hasOwnProperty( lightId ) ) continue;

// Same trick with following "for...in" loops...
```

Well adding forEach2 is the cause of this issue but maybe it can help others...

##### Three.js version
- [x] r94

##### Browser
- [x] Chrome

##### OS
- [x] Windows

**Comment by donmccurdy** [comment]
I think this was a mistake, probably copied from an older version of the extension:

```js
var lights = extension.lights || {};

for ( var lightId in lights ) { ... }
```

`extension.lights` is an array, not an object, and we should be using an indexed `for` loop instead.
