### ISSUE TITLE
Camera CenterOn to fit objects Perfectly according to camera orientation

### ISSUE THREAD

**Issue by moroine** [mrdoob/three.js#14511]
Hello,

I manage to make it works, you can find an example here: 
https://codepen.io/bilouwan/project/full/XpgGOp/ 

As it is quite complex to implements, no really the code but more the maths and it is quite a common stuff when playing with the camera I am wondering about making a PR.

What do you think about it? Could it be useful? Better to add it under examples or inside the core like Math or Camera method may be...

**Comment by selimbek** [comment]
Hi, 

I'm sure that will be usefull for lot of people. 
I recommand to make PR with commented code, under example section. ( center.js as an external library, and the others files merged into an html file example)

You should pack your center.js into an nes THREE object. A user case could be: THREE.CameraCentering()

**Comment by selimbek** [comment]
Hi,

I'm sure that will be usefull for lot of people.
I recommand to make PR with commented code, under example section. ( center.js as an external library, and the others files merged into an html file example)

You should pack your center.js into a new THREE object (THREE.CameraCentering ?). A user case could be: 
var cameraCentring = new THREE.CameraCentering();
cameraCentring.addCamera( myCamera1);
cameraCentring.addCamera( myCamera2);
...
cameraCentring.centeringTo( threeObect3DArray );

**Comment by haroldiedema** [comment]
That is a very nifty feature.

If you make a PR, please make sure to not have any references to things in the global scope though.

**Comment by moroine** [comment]
Actually, in my case, I am doing some animations with the Camera so I don't want to modify the camera directly.

I think I can do an API similar to Box3 with kind of:

```
const viewBox = new CameraViewBox();
viewBox.setViewFromCamera(camera);
viewBox.setFromObject(object);

viewBox.getCenter(controls.target);
viewBox.getObserverPosition(camera.position);
```

@haroldiedema  sure, global variable are here just to validate the logic, I still need to figure out what would be the API.

**Comment by haroldiedema** [comment]
So if I understand correctly, all you need for this feature to work is a `Camera` and a set of one or more `Object3D` instances right?

If that's the case, I think you're on the right track in my opinion.

```javascript
const camera  = new THREE.PerspectiveCamera();
const viewBox = new THREE.CameraViewBox(camera);

viewBox.centerObjects(object1, object2, object3, ...);
```
I don't think it gets any easier than this.

Perhaps for ease-of-use, you could also add some `add` and `remove` functions for the object instances. This would make dynamically adding / removing objects very easy like how you demonstrate in the codepen.

```javascript
viewBox.add(object1);
viewbox.remove(object2);
```

**Comment by Mugen87** [comment]
Merging into #6784.
