### ISSUE TITLE
Check for removal of children in the traverse method

### ISSUE THREAD

**Issue by jkulanko** [mrdoob/three.js#14514]
##### Description of the problem
Removing children while using the traverse function will result in an error.  I propose a second check to make sure that l = children inside the loop, in case a node is removed.
Original: 
```javascript
traverse: function ( callback ) {

			callback( this );

			var children = this.children;

			for ( var i = 0, l = children.length; i < l; i ++ ) {

				children[ i ].traverse( callback );

			}

		}
```
My proposal:
```javascript
traverse: function ( callback ) {

			callback( this );

			var children = this.children;

			for ( var i = 0, l = children.length; i < l; i ++ ) {
                                if(l != children.length){
                                l=children.length;
                                i--;
                                }
				children[ i ].traverse( callback );

			}

		}
```

There might be a better way to do it, but that change got my code working.
* [jsfiddle](https://jsfiddle.net/3foLr7sn/20/) 

##### Three.js version

- [ ] Dev
- [x] r94
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by jkulanko** [comment]
It does traverse the children but if it’s removed from the scene than it won’t matter what happens to it’s children. However, I agree there is probably a much better way that doesn’t waste time traversing the children of a removed object. 

In general, I think it should account for the removal of objects. The case in which I was using it for is a scene with many objects, each object has a mesh and line segments. I want an option in my program to toggle the lines on the meshes so I use the traverse function to remove all instances of line segments, while keeping a copy of the original scene for when the user wants to turn lines back on.

**Comment by aardgoose** [comment]
You might find Layers more efficient. You can switch the visibility of multiple objects at once simply by changing the Layers of your Camera object.

https://threejs.org/docs/#api/core/Layers

**Comment by looeee** [comment]
> In general, Object3D.traverse() assumes that the structure of the scene graph does not change.

This should be documented. 

> traverse function to remove all instances of line segments

There are lots of ways you could do this without scene traversal. How about keeping an array of line segments, and when you want to or remove them to the scene:

```js
const lineSegments = [ line1, line2, line2, ... ];

scene.add( ...lineSegments );
scene.remove( ...lineSegments ); 

// or if you can't use destructuring
lineSegments.forEach( ( line ) => { scene.add( line ) } ); 
lineSegments.forEach( ( line ) => { scene.remove( line ) } ); 
```

**Comment by WestLangley** [comment]
> In general, Object3D.traverse() assumes that the structure of the scene graph does not change.
>> This should be documented.

@looeee IMHO, that is not necessary. It is reasonable to expect users to understand the ramifications of modifying a graph while traversing it. Same with an array. Save yourself some work. :-)

@jkulanko If you need further help, please use the [forum](https://discourse.threejs.org).

Closing, as this is a user error.
