### ISSUE TITLE
Multiple transparent materials rendering issue

### ISSUE THREAD

**Issue by nurbs999** [mrdoob/three.js#14529]
##### Description of the problem

If two objects have a transparent material the one behind seems to disappear. In my tests one the material didn't get rendered on some camera angles.

Here is a fiddle demo: https://jsfiddle.net/3foLr7sn/36/

##### Three.js version

- [ ] Dev
- [x ] r94

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by looeee** [comment]
Please put any help questions on the [forum](https://discourse.threejs.org/).

**Comment by nurbs999** [comment]
Well, actually I think this is a bug in the rendering pipeline or in handling transparent materials in threejs.
