### ISSUE TITLE
Add a getter for "session" in WebXR

### ISSUE THREAD

**Issue by soadzoor** [mrdoob/three.js#14532]
##### Description of the problem

It would be very helpful if I could get the `session`, and the `XRInputDevice`, specially the "handedness", and "pointerOrigin" properties. The only way I find to do this now, is by changing my three.js file, which obviously not a nice solution.

I think the best way would be something like this:
`var session = renderer.vr.getSession();`, then
`var inputDevice = session.getInputSources();`

Or is there already a way to get this, and I couldn't find it..?

##### Three.js version

- [ ] Dev
- [x] r94
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Could you add links to the specific parts of the WebXR API you're referring to?

**Comment by soadzoor** [comment]
@mrdoob Maybe this is the one: https://immersive-web.github.io/webxr/#xrinputsource-interface

The XRinputsource is logged on the console in three.js when you use a compatible VR device (and browser), but as far as I know, there's no way to get the same "information" without modifying three.js, (or maybe WebVR.js (from the examples))

**Comment by mrdoob** [comment]
Is this to know if the VR controller is for the left hand or the right hand?

**Comment by soadzoor** [comment]
Partially, yes! For me, personally, it would be very useful to check if the user even HAS a hand-controller (so they use a VR headset like daydream), or not (so they use a VR headset like google cardboard).

"What would be the point of all this?" You might ask. The answer is that if (s)he uses a handcontroller, then I add a helper (like in the webvr ballshooter example), because it's very useful. If it doesn't have a handcontroller, then I don't add it, because it's very disturbing in this case (as the helperline is coming right from the user's "nose").

**Comment by mrdoob** [comment]
> If it doesn't have a handcontroller, then I don't add it, because it's very disturbing in this case (as the helperline is coming right from the user's "nose").

Haha, yeah. I noticed that 😅

One option would be to user the `userData`:

```js
var controller = renderer.vr.getController( 0 );
console.log( controller.userData.vr.hand ); // 'left'
```

Would that work? What other data is available/needed?

**Comment by mrdoob** [comment]
Maybe for the time being we can add that object direction into the controller's `userData`?

**Comment by soadzoor** [comment]
Yea, I believe that should be okay :)

**Comment by soadzoor** [comment]
Yea, I'll try , thanks :)

**Comment by soadzoor** [comment]
It seems I don't have a permission to push into this repo :(

**Comment by Mugen87** [comment]
Try to fork the repository and then create a pull request. More information about contributing right here:

https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js

**Comment by soadzoor** [comment]
Any reason why the PR is not merged yet? :/

**Comment by Mugen87** [comment]
@soadzoor It still needs to be review by @mrdoob
