### ISSUE TITLE
glTF animation doesn't stop at last frame

### ISSUE THREAD

**Issue by Lee-Heisenbug** [mrdoob/three.js#14541]
##### Description of the problem
I've created a scene with an animated cube and exported it(glTF). After I loaded the scene, I played the animation once. But the animation didn't stop at last frame. 
![reality](https://user-images.githubusercontent.com/26576701/43177651-db85eae8-8ffb-11e8-8075-6d160605c02b.gif)

Then I tried to export the scene again with "force sample animation" checked, the aniamtion worked as expected.
![expected](https://user-images.githubusercontent.com/26576701/43177626-b6161954-8ffb-11e8-9dd5-ac39277dc536.gif)

It seems not a bug of  glTF exporter (KhronosGroup/glTF-Blender-Exporter#270). But I think it might have something to do with the GLTFCubicSplineInterpolant? Because I found something in the console (the parameter of evaluate function is the end time of the animation) :
![gltfcubicsplineinterpolant](https://user-images.githubusercontent.com/26576701/43177826-c0a9c5ea-8ffc-11e8-8936-bfdb283ef69e.jpg)

Here is the .blend file:
[test-cube.zip](https://github.com/mrdoob/three.js/files/2226317/test-cube.zip)
The web:
[animation-test.zip](https://github.com/mrdoob/three.js/files/2226366/animation-test.zip)

##### Three.js version

- [ ] Dev
- [x] r94
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> I've created a scene with an animated cube and exported it(glTF). After I loaded the scene, I played the animation once. But the animation didn't stop at last frame.

Please use [AnimationAction.clampWhenFinished](https://threejs.org/docs/#api/animation/AnimationAction.clampWhenFinished) in order to achieve this effect.

**Comment by Lee-Heisenbug** [comment]
Yeah, I believe I've set .clampWhenFinished = true. But still no luck.

**Comment by Mugen87** [comment]
It does not work since the last position in the keyframe track is `(0,0,0)`. So right now, the animation does what it's supposed to do.

**Comment by donmccurdy** [comment]
Note that when an animation has cubic spline interpolation in glTF, it uses a different `track.values` layout (and a different interpolation function) than the three.js default...

[ inTangent_1, splineVertex_1, outTangent_1, inTangent_2, splineVertex_2, ... ]

... where each tangent or control point is a vec3 in this case. For this values list:

[0, 0, -0, 0, 0, -0, 0, 0, -0, 0, 0, -0, 0, 6.861611366271973, -0, 0, 0, -0]

The final position is `0, 6.86..., 0`. We override `track.createInterpolant`, which i would have expected to work properly with `clampWhenFinished`, but perhaps that isn't the case. I haven't had the chance to debug further on this yet.

**Comment by donmccurdy** [comment]
Should be fixed by #14550.
