### ISSUE TITLE
THREE.DRACOLoader: Decoding failed: Unknown minor version

### ISSUE THREAD

**Issue by duyhau206** [mrdoob/three.js#14552]
Hi everybody! I'm new to threejs. I'm trying to load gltf-Draco 3d model by GLTFLoader and DRACOLoader. I have an error with decoder allow image:
![capture](https://user-images.githubusercontent.com/41716616/43241887-d63b2a36-90c7-11e8-896f-ae298589fbba.PNG)

And this is my code:

`var camera, scene, renderer;
        var container = document.getElementById('container');
        // Configure and create Draco decoder.
        var loader = new THREE.GLTFLoader();
        THREE.DRACOLoader.setDecoderPath('../three.js-master/libs/draco/');
        THREE.DRACOLoader.setDecoderConfig({ type: 'js' });
        var dracoLoader = new THREE.DRACOLoader();

        init();
        animate();
        function init() {
            camera = new THREE.PerspectiveCamera(35, window.innerWidth / window.innerHeight, 0.1, 15);
            camera.position.set(3, 0.25, 3);
            scene = new THREE.Scene();
            scene.background = new THREE.Color(0x443333);
            scene.fog = new THREE.Fog(0x443333, 1, 4);
            // Ground
            var plane = new THREE.Mesh(
                new THREE.PlaneBufferGeometry(8, 8),
                new THREE.MeshPhongMaterial({ color: 0x999999, specular: 0x101010 })
            );
            plane.rotation.x = - Math.PI / 2;
            plane.position.y = 0.03;
            plane.receiveShadow = true;
            scene.add(plane);
            // Lights
            var light = new THREE.HemisphereLight(0x443333, 0x111122);
            scene.add(light);
            var light = new THREE.SpotLight();
            light.angle = Math.PI / 16;
            light.penumbra = 0.5;
            light.castShadow = true;
            light.position.set(- 1, 1, 1);
            scene.add(light);

            loader.setDRACOLoader(dracoLoader);
            loader.load(
                // resource URL
                '../three.js-master/models/gltfModel/Duck/Duck.gltf',
                // called when the resource is loaded
                function (gltf) {

                    scene.add(gltf.scene);

                    gltf.animations; // Array<THREE.AnimationClip>
                    gltf.scene; // THREE.Scene
                    gltf.scenes; // Array<THREE.Scene>
                    gltf.cameras; // Array<THREE.Camera>
                    gltf.asset; // Object

                },
                // called while loading is progressing
                function (xhr) {

                    console.log((xhr.loaded / xhr.total * 100) + '% loaded');

                },
                // called when loading has errors
                function (error) {

                    console.log('An error happened');

                }
            );

            // renderer
            renderer = new THREE.WebGLRenderer({ antialias: true });
            renderer.setPixelRatio(window.devicePixelRatio);
            renderer.setSize(window.innerWidth, window.innerHeight);
            renderer.gammaInput = true;
            renderer.gammaOutput = true;
            renderer.shadowMap.enabled = true;
            container.appendChild(renderer.domElement);
            window.addEventListener('resize', onWindowResize, false);
        }
        function onWindowResize() {
            camera.aspect = window.innerWidth / window.innerHeight;
            camera.updateProjectionMatrix();
            renderer.setSize(window.innerWidth, window.innerHeight);
        }
        function animate() {
            render();
            requestAnimationFrame(animate);
        }
        function render() {
            var timer = Date.now() * 0.0003;
            camera.position.x = Math.sin(timer) * 0.5;
            camera.position.z = Math.cos(timer) * 0.5;
            camera.lookAt(new THREE.Vector3(0, 0.1, 0));
            renderer.render(scene, camera);
        }`

Please help me!.

##### Three.js version

- [ ] Dev
- [x] r94
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
The Draco decoder version needs to match the encoder that created the file. For any glTF file with Draco compression, the correct decoders are in a subfolder:

```js
THREE.DRACOLoader.setDecoderPath('../three.js-master/libs/draco/gltf');
```

if that doesn't work, do you know what tool was used to Draco-compress your model?

**Comment by donmccurdy** [comment]
More details here: https://github.com/mrdoob/three.js/blob/dev/examples/js/libs/draco/README.md

**Comment by duyhau206** [comment]
Thanks for the quick help @donmccurdy .
I trying with first suggestion and success. The Draco decoder version needs to match the encoder that created the file.
I'm modeling with blender and compress with glTF-pipeline, after that i load it on website with three js.
Thank you very much @donmccurdy and have a nice day
