### ISSUE TITLE
Unecessary string concatanation in WebGLRenderer

### ISSUE THREAD

**Issue by oguzeroglu** [mrdoob/three.js#14554]
https://github.com/mrdoob/three.js/blob/ecec267ddb42860a000f636160514145b08eaddc/src/renderers/WebGLRenderer.js#L652

Instead of string concatanation in this line, _currentGeometryID, _currentProgramID and _currentWireframe variables should be defined and compared to the geometryId, programID and wireframeID seperately: 

```
if (_currentGeometryID != geometryID || _currentWireframe != wireframe || _currentProgramID != programID){
  updateBuffer = true;
   // update _currentGeometryID, _currentWireframe and _currentProgramID variables
}
```

String concatanation causes GC activity since it creates a new string each time and this function is called on each frame. The GC activity caused by this line may be observed using Chrome's Allocation Profiler.

**Comment by Mugen87** [comment]
Um, maybe a structure like this is better:
```js
_currentGeometryProgram = {
    geometryID: '',
    programID: '',
    wireframe: false
};
```
In this way, we still have one variable and avoid `_currentGeometryID`, `_currentWireframe` and `_currentProgramID`.
