### ISSUE TITLE
LOD: Consider adding hysteresis option.

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#14565]
With the LOD systems in Unreal, Unity, and Blender, LODs have a threshold that offsets the distance where the LOD appears from the distance where it disappears, to reduce flickering from small movements (e.g. head movement with roomscale VR). From [Unreal docs](https://docs.unrealengine.com/en-us/Engine/Animation/Persona/MeshDetails):

> **LOD Hysteresis** | Used to avoid "flickering" when on LOD boundry. Only take into account when moving from complex to simple.

**Comment by mrdoob** [comment]
Hmm... Is there a video or more documentation that shows the flickering?

**Comment by makc** [comment]
sounds like you would have to move sideways exactly at the right distance. how likely is that?

**Comment by donmccurdy** [comment]
I can make a screencapture but it would be a bit subjective — whether it's actually noticeable depends mostly on the similarity of the two LOD levels and the transition distance. 

Not sideways, but the point of this feature is that there should be no place on a game map where the user can step forward-back-forward and see an LOD change _twice_. So "hysteresis" reduces the total number of changes likely to be observed in practice.

But this isn't terribly important to me currently, and it's easy to implement in userland. I'll close this for now and let others comment here if they have a use for it. :)

**Comment by mrdoob** [comment]
Oh, so it's like a range where the state is kept with the previous change?

**Comment by donmccurdy** [comment]
Right, so if you're moving toward a tree and increase quality from LOD3 to LOD2 at 50m distance, you'd have to move back to 55m distance in order to drop back to LOD3.

**Comment by makc** [comment]
could be done (along with multitude of other things) easily if LOD accepted user function returning level index instead of distances

**Comment by donmccurdy** [comment]
True, although if you strip out the selection of level index from [LOD.js](https://github.com/mrdoob/three.js/blob/dev/src/objects/LOD.js), there isn't much code left for a user to implement anyway. ;) 

Similar properties exist in Unreal, Unity, and Blender, although semantics differ — distance vs screen space, hysteresis as percentage of distance vs absolute value. I think a property is preferable to a callback function here, because it can be (de)serialized.
