### ISSUE TITLE
Apply SubdivisionModifier without shape destruction

### ISSUE THREAD

**Issue by iShankarG** [mrdoob/three.js#14584]
##### Description of the problem

I'm applying SubdivisionModifier for cubes to get curved edges, but shape of cube destroyed. I need to maintain the shape of cube with only curved corners.

* [codepen](https://codepen.io/shankarG/full/jpaxBg/) (latest release branch)

##### Three.js version

- [ ] Dev
- [x] r94

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by WestLangley** [comment]
Please use the forum for help. For example: https://discourse.threejs.org/search?q=round-edged
