### ISSUE TITLE
webgl_objects_update.html example

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#14583]
What three.js feature(s) do we want this demo to demonstrate?

What should be added to, or removed from, this demo?

https://threejs.org/examples/webgl_objects_update.html

(Note that It is not disposing of geometries properly.)

**Comment by Mugen87** [comment]
It seems the demo is a showcase for `Geometry.groupsNeedUpdate`.

https://github.com/mrdoob/three.js/pull/5006

**Comment by WestLangley** [comment]
Thanks, @Mugen87 .  Since, `groupsNeedUpdate` is not required for `BufferGeometry`, that is not an issue.

Anything else that you can see?

**Comment by Mugen87** [comment]
Nope.

**Comment by WestLangley** [comment]
@mrdoob Maybe this example no longer needed.

**Comment by mrdoob** [comment]
Yeah, it was never a example of usage. More like a example to make sure things didn't break.

**Comment by mrdoob** [comment]
I think I vote for removing it too.
