### ISSUE TITLE
DirectionalLight is not actually a directional light

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#14585]
Does is matter that the `DirectionalLight` is not actually a directional light?

Here's a screenshot of a directional light lighting one face of a cube

<img width="717" alt="screen shot 2018-07-30 at 22 15 54" src="https://user-images.githubusercontent.com/234804/43399523-437b8e98-9446-11e8-8b45-496301d824f1.png">

Here's the fiddle that's from: https://jsfiddle.net/greggman/ae2yc7uj/

It's clearly not a directional light. If it was a directional light it would be a solid color but you can clearly see it's not a solid color. In order to produce the affect seen in the screenshot a position is needed. A direction light (in computer graphic terms) has no position so it's impossible to render different lighting across a flat surface.

Is this a bug? Should the docs change to say a direction light is not actually a directional light?

##### Three.js version

- [X] Dev
- [X] r94

**Comment by greggman** [comment]
I see the issue is that it's a specular highlight but it's not a directional specular highlight it's a point specular highlight. Is that the intent?

**Comment by WestLangley** [comment]
The `DirectionalLight`is modeled as a point source that is very far away, so the rays are essentially parallel -- like the sun.

The sun registers a hot spot on smooth surfaces, right?

**Comment by paulmasson** [comment]
@greggman I'm with you on this one: parallel rays do not produce a hot spot on a flat surface. The current behavior is physically inaccurate. I've noticed the same thing myself when placing a directional light over a plane.

**Comment by WestLangley** [comment]
![](http://math.hws.edu/graphicsbook/c4/diffuse-vs-specular.png)

**Comment by paulmasson** [comment]
Physics means: go out in the real world and look at flat surfaces in direct sunlight. How many hot spots are as distinctly visible as the image above? The current behavior is exaggerated compared to reality.

**Comment by looeee** [comment]
@paulmasson Some materials will show a very strong hotspot under direct sunlight in the real world - for example, a shiny skyscraper like this one:

![20130612-113655](https://user-images.githubusercontent.com/5307958/43550879-ede99bf8-95dc-11e8-810f-02fb6ef50406.jpg)
 


You can model both extremes easily if you switch to `MeshStandardMaterial` and play around with roughness:

roughness: 1
https://jsfiddle.net/ae2yc7uj/33/
![r1](https://user-images.githubusercontent.com/5307958/43550770-8d94e546-95dc-11e8-882e-5d5ee4982270.png)


roughness: 0
https://jsfiddle.net/ae2yc7uj/34/
![r0](https://user-images.githubusercontent.com/5307958/43550773-915fdea6-95dc-11e8-9302-45b8d59a961d.png)

**Comment by paulmasson** [comment]
@looeee now I see what you mean. I hadn't thought about interpolating between mirrors and dull surfaces. Very interesting!

I still think there is a question of whether the default behavior is exaggerated. Either that or the directional light documentation might include some of this discussion.

**Comment by greggman** [comment]
@WestLangley's explanation works for me.
