### ISSUE TITLE
Audio isPlaying appears to be incorrect (audio playing multiple times)

### ISSUE THREAD

**Issue by chrisyarbrough** [mrdoob/three.js#14587]
Code:
`if (sound.isPlaying) {
     sound.stop();
   }
   sound.play();`

Expected:
Three.js PositionalAudio can be restarted by calling stop and play again. Before calling stop, it should be possible to query "isPlaying" and only stop audio when required.

Actual:
When the function is called multiple times with a 1 second delay in between, the audio is played multiple times simultaneously, as if there were multiple tracks overlapping each other.

Reproduction fiddle:
https://jsfiddle.net/Xarbrough/odc0tp4x/1/

Click the screen multiple times with short and longer delays. Expected behaviour would be that the sound is correctly restarted every time, but actually behaviour is, that the sound sometimes plays multiple times on top of each other.

##### Three.js version
- [x] r94

##### Browser
- [x] Chrome

##### OS
- [x] Windows

**Comment by Mugen87** [comment]
The problem in this particular fiddle is that the `onEnded()` event listener fires after the call of `play()`. So you start the audio again, `isPlaying` is set to `true` but the event listener of `onended` overwrites `isPlaying` with `false`. The following fiddle illustrates this by overwriting `Audio.onEnded()`.

https://jsfiddle.net/f2Lommf5/10501/

**Comment by Mugen87** [comment]
BTW: `onended` is always fired after a call of `.stop()`.

**Comment by Mugen87** [comment]
@chrisyarbrough Can you please check if the PR solves the issue for you 😇 ?
