### ISSUE TITLE
No error handler for OBJLoader2.loadMtl

### ISSUE THREAD

**Issue by iamnotstone** [mrdoob/three.js#14606]
##### Description of the problem

Here is my code:

```
  var objLoader = new THREE.OBJLoader2()             
   try{
    objLoader.loadMtl(mtlurl, null, onLoadMtl)
  }
  catch(e){
    console.log('mtl load error:', e)
  }
```
as there is some network error . so I got this below in my console:
three.min.js:619 GET https://xxxx.xxx.xxx/mtl/xxxx net::ERR_CERT_COMMON_NAME_INVALID

But I didn’t catch any error in my own code neither did the onMtlLoader function called.

Instead , I try @Mugen87's suggestion [here](https://discourse.threejs.org/t/can-not-catch-objloader2-error/3496) . OBJLoader works perfect for catching network error.
So I think is it necessary to add an onError callback for OBJLoader2.loadMtl ?

##### Three.js version

- [ ] Dev
- [x] r95
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by kaisalmen** [comment]
@iamnotstone  @Mugen87 I backported a fix from `OBJLoader2` 3.0.0-dev that addresses this issue. Next version of `OBJLoader2` will offer a single functions for loading obj and mtl offering all callbacks with full functionality.
The backport requires to register a generic error callback. This is not a nice as, but will solve your problem.

I will release version 2.4.2 of npm package of `wwobjloader2`, soon. A PR here will come afterwards.
If you don't want to wait, check out master branch of https://github.com/kaisalmen/WWOBJLoader and see how the error handler is utilized in `WWParallels` example.
