### ISSUE TITLE
Distance based fog?

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#14601]
Should fog be distance from camera instead of distance from camera's zplane?

Currently fog is just the z distance from the zplane of the camera. That means if you just turn the camera in place objects that are not really getting closer to the camera come out of the fog. That doesn't seem correct (although maybe it's intentional?)

Here's 6 cubes in a circle around the camera. The camera is spinning in place. you can see the cubes come out of the fog even though they are not actually closer to the camera

http://jsfiddle.net/greggman/Lx3mhvbe/

Changing the fog from this

    fogDepth = -mvPosition.z;

to this

    fogDepth = length(mvPosition);

Seem like it might work?

Example: https://fog-fix.glitch.me/

Not sure it's correct but the objects are no long coming out of the fog

##### Three.js version

- [X] Dev
- [X] r94

**Comment by Mugen87** [comment]
I think this is a good suggestion.

**Comment by mrdoob** [comment]
Agreed. I never liked this fog technique.

**Comment by WestLangley** [comment]
Actually, this approach only works correctly if the distance is calculated in the fragment shader, not in the vertex shader. So #14602 will have to be reverted for now.

**Comment by BarthaBRW** [comment]
Is there any progress about this issue?

**Comment by amitukind** [comment]
Is there any progress on this? I have implemented it and I am going to create a PR.

**Comment by Mugen87** [comment]
There is already a PR for this, see #17592.

**Comment by amitukind** [comment]
@Mugen87 I need to change in realtime all object's opacity based on their distance from the camera. The fog technique doesn't work there. Changing manually in animate is consuming a lot of CPU.
