### ISSUE TITLE
Orbit Control Arrow Key Behavior

### ISSUE THREAD

**Issue by msmcgillis** [mrdoob/three.js#14603]
##### Description of the problem

Load this html in a browser and make the window so you only see half the green square.

```
<html>
<head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/94/three.min.js"></script>
<script src="https://threejs.org/examples/js/controls/OrbitControls.js"></script>
<style>
.size {
  width: 400px;
  height: 240px;
}
</style>
<script>
  class BasicCanvas {
    constructor(target,color) {
      this.target = target;
      this.scene = new THREE.Scene();
      this.camera = new THREE.PerspectiveCamera(75,
           this.target.offsetWidth/this.target.offsetHeight,0.1,1000);
      this.camera.position.z=5;

      this.renderer = new THREE.WebGLRenderer();
      this.renderer.setSize(this.target.offsetWidth,this.target.offsetHeight);
      this.target.appendChild(this.renderer.domElement);

      this.controls=new THREE.OrbitControls(this.camera,this.target);
      
      var geometry = new THREE.BoxGeometry(1,1,1);
      var material = new THREE.MeshBasicMaterial({color: color });
      var cube = new THREE.Mesh(geometry,material);
      this.scene.add(cube);
      this.animate();
    }

    animate() {
      requestAnimationFrame(this.animate.bind(this));
      this.renderer.render(this.scene,this.camera);
    }
  }
  document.addEventListener("DOMContentLoaded",function() {
    var a=new BasicCanvas(document.getElementById("a"),"#0000FF");
    var b=new BasicCanvas(document.getElementById("b"),"#00FF00");
  });
</script>
</head><body>
<div id="test" contenteditable="true">
  <div id="a" class="size"></div>
</div>
<div id="b" class="size" contenteditable="true"></div>
</body></html>

```

Then use the up arrow key and notice both boxes get bigger. Ideally to me only one of them would get the key input just like using the mouse on these only impacts the one the mouse is in.

Now use the down arrow and notice the boxes shrink but the page also moves. This I addressed by updating the OrbitControl handleKeyDown function and adding event.preventDefault() to all the keys that are processed.

Current browsers support contenteditable so I tried adding that two the div's that are used to hold the canvas to see if that would adjust the key behavior. I also modified the OrbitControl 

```
window.addEventListener( 'keydown', onKeyDown, false );
```

To

```
scope.domElement.addEventListener( 'keydown', onKeyDown, false );
```

 The above change causes the arrow keys to no longer function.

As another experiment I used the test div around the blue box and replaced:

```
window.addEventListener( 'keydown', onKeyDown, false );
```

With

```
var x = document.getElementById("test");
x.addEventListener( 'keydown', onKeyDown, false );
```

With the above if I click on the blue box then press arrow keys they now work but both the blue and green box change size. Both boxes changing looks like a bigger issue of how this code is structured in relation to multiple three canvases on the same page. So far I have not dug into that to see what options are possible but thought I would share the above for now.

##### Three.js version

- [ ] Dev
- [ ] r95
- [ X ] 94

##### Browser

Probably all but I use Chrome.

- [ ] All of them
- [X] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

Probably all that have keyboards but I used macOS.

- [ ] All of them
- [ ] Windows
- [ X ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by WestLangley** [comment]
Closing. This is something you will have to handle in your app, and is not a three.js issue. If you are able to provide a compelling argument otherwise, you can reopen this.
