### ISSUE TITLE
Malware link in LatheGeometry.js

### ISSUE THREAD

**Issue by zadvorsky** [mrdoob/three.js#14613]
Not super major (and I'm not sure where else to file this), but the link http://astrodud.isgreat.org/ in the accreditation documentation for https://github.com/mrdoob/three.js/blob/master/src/geometries/LatheGeometry.js leads to a site that's fishy.

**Comment by mrdoob** [comment]
Good catch!
I think we can safely remove that whole line. Would you like to do a PR?

**Comment by zadvorsky** [comment]
Thanks! I'll try to find some time in the next few days.

**Comment by zadvorsky** [comment]
Beat me to it! Thanks.
