### ISSUE TITLE
webgl_loader_nrrd.html is not disposing of geometries properly

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#14610]
Type `renderer.info` into the console.

**Comment by stity** [comment]
@WestLangley  Can you be a bit more specific about the issue ? Is the issue about renderer.info.memory.geometries increasing when you use the demo ?
I don't see why it is a problem

**Comment by WestLangley** [comment]
Yes. You need to call `geometry.dispose()`. There is probably no reason to repeatedly instantiate new geometries, anyway.

 Quite frankly, `Volume.js`, `VolumeSlice.js`, and `webgl_loader_nrrd.html`all need to be reviewed.
