### ISSUE TITLE
GLTFLoader: The direction of the directional light should ignore scale

### ISSUE THREAD

**Issue by 06wj** [mrdoob/three.js#14618]
As KhronosGroup/glTF#1223 says:
> Directional light inherits the orientation of the node that it belongs to but ignores position and scale.

Three's implementation dosen't ignore the scale.
```
// Three's implementation
lightNode.target.position.set( 0, 0, 1 );
lightNode.add( lightNode.target );

uniforms.direction.setFromMatrixPosition( light.matrixWorld );
vector3.setFromMatrixPosition( light.target.matrixWorld );
uniforms.direction.sub( vector3 );
uniforms.direction.transformDirection( viewMatrix );
```

**Comment by donmccurdy** [comment]
See https://github.com/mrdoob/three.js/issues/13373 and https://github.com/mrdoob/three.js/pull/14557. I suppose GLTFLoader scale-correct the initial target position? But that's still not the same as ignoring scale, e.g. animation on a parent node's scale will affect the light, and we don't know whether the user will scale the model when adding it to the scene.

**Comment by donmccurdy** [comment]
The glTF lighting spec has been amended in the latest draft, such that scale does affect light direction. I believe this can be closed.
