### ISSUE TITLE
sizeAttenuation for sprites?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#14626]
following things seem to be removed from sprites:
* affectedByDistance #278
* scaleByViewport #279

meanwhile, sizeAttenuation exists for points. can we have it for sprites, too? seems like rather typical use case

**Comment by Mugen87** [comment]
I only know size attenuation in combination with points. `THREE.Sprite` based on a plane geometry and this effectively a billboard. I've never seen size attenuation in this context.

> seems like rather typical use case

Do you have a reference for this statement?

**Comment by makc** [comment]
Well, it is always the case for me. Pins on globes/maps, text labels, etc.

**Comment by makc** [comment]
It just seems to be solveable so much easier in the shader. Right now I am doing this hack:
```
tmp.copy (sprite.position);
camera.worldToLocal (tmp); if (tmp.z < 0) {
	sprite.scale.setScalar (-scale * tmp.z);
	sprite.updateMatrixWorld (true);
```
and it gets tiresome

**Comment by mrdoob** [comment]
I think this is a valid request.
