### ISSUE TITLE
webgl_geometry_colors_lookuptable.html needs to be revisited

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#14634]
The example is not disposing of geometries properly. Geometry should likely be reused anyway.

Look-up-table should probably be rendered with an orthographic camera.

`examples/math/Lut.js` also needs to be revisited.

**Comment by Mugen87** [comment]
> The example is not disposing of geometries properly.

The linked PR solves at least this problem.

**Comment by Mugen87** [comment]
> examples/math/Lut.js also needs to be revisited.

What do you have in mind for this file?

**Comment by WestLangley** [comment]
>What do you have in mind for this file?

It's just.. different...
```javascript
this.legend.position = parameters.hasOwnProperty( 'position' ) ? parameters[ 'position' ] : { 'x': 21.5, 'y': 8, 'z': 5 };

this.legend.position = new THREE.Vector3( position.x, position.y, position.z );
```
In the main demo,
- the model probably should be loaded only once, updating the vertex colors as needed
- `axis` is not needed
- `normalizeNormals()` is not needed
- `parameters` args use a different convention than we have adopted

Regarding the legend, I suggested using an orthographic camera for that, but maybe for VR support, a floating sprite is the right way to go. I am not sure what the feeling is on that...

I know this is not high-priority, but this code, after all, is presented as an example to be copied.
