### ISSUE TITLE
Spotlight can't set target correctly

### ISSUE THREAD

**Issue by Rybots** [mrdoob/three.js#14638]
Hi, I'm trying to set up the spotlights, but target always directs to (0,0,0).
I've tried
- spotlight.target.position.set(x,y,z);
- spotLight.target = object; 
- spotLight.lookAt( object.position ); ← this direct to weired point(not expected direction)

and also I've tried

scene.add( spotLight );
scene.add( spotLight.target );

but it didn't work...
I would appreciate if anyone had any solution.
Thanks!

**Comment by looeee** [comment]
Please use the forum for help requests:
https://discourse.threejs.org

**Comment by jespertheend** [comment]
```let spotLight = new THREE.SpotLight(0xFFFFFF, 1, 0, 1, 1, 1);
spotLight.position.set(-140, 80, 160);
spotLight.target.position.set(-120, 80, 160);
spotLight.target.updateMatrixWorld();
this.scene.add(spotLight);
```
