### ISSUE TITLE
FileLoader cannot handle request.abort()

### ISSUE THREAD

**Issue by okitu** [mrdoob/three.js#14652]
The change, that let's FileLoader cache duplicate requests by default, introduced a problem, when aborting a request before it's loaded.

XMLHttpRequest.abort() does not tirgger 'load' or 'error' events but instead an 'abort' event.

Because that event is not handled, the request will be stuck in the FileLoaders 'loading' object, that is used to determine, if a file is already loading.

[Demo jsfiddle](https://jsfiddle.net/42brk186/) 

By adding a listener for 'abort' this could be prevented:

    request.addEventListener( 'abort', function ( event ) {
        ... handle the same way an error would be handled
    }, false );

I'm not sure, if handling it as an error is the way to go, because aborting has to be called on purpose, but this is how i do it for now.

##### Three.js version

- [x] r88+

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
> I'm not sure, if handling it as an error is the way to go, because aborting has to be called on purpose, but this is how i do it for now.

I think it's okay if the engine internally handles this cases as an error ( in the sense of the request was not completed as expected). It should actually be an easy fix when using the the same code for the `error` event:

https://github.com/mrdoob/three.js/blob/6201c9ac8c8a384ebc475e5bdb7c6ee0d75885f7/src/loaders/FileLoader.js#L224-L240

**Comment by okitu** [comment]
@Mugen87 Most certainly sir.

#14674
