### ISSUE TITLE
Adding onStart argument to LoadingManager constructor?

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#14659]
##### Description of the problem

`LoadingManager` has four `.on` callback function properties, `.onLoad`, `.onProgress`, `onError`, and `.onStart`. It takes three of them as arguments of the constructor, `onLoad`, `onProgress`, and `onError`.

https://threejs.org/docs/#api/loaders/managers/LoadingManager

Why not adding the firth argument `.onStart` to the constructor? Any historical reasons?

If you folks agree with adding it, I'll make PR.

##### Three.js version

- [x] Dev
- [ ] r95
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by takahirox** [comment]
Oops, I've missed that thread. Hm, I can understand that..

**Comment by takahirox** [comment]
Hm, adding a note in the code so far? Other devs will think the same thing later.

**Comment by Mugen87** [comment]
Yeah, referring to #5689 in `LoadingManager` can't hurt. I would do it here:

https://github.com/mrdoob/three.js/blob/32914a505d8353b10d76802cdd87eba427ae6e34/src/loaders/LoadingManager.js#L14
