### ISSUE TITLE
Box3#applyMatrix4() no longer supports projection transformation matrices

### ISSUE THREAD

**Issue by razh** [mrdoob/three.js#14655]
##### Description of the problem

#13993 introduced an optimization to `Box3#applyMatrix4()` that only supports affine transforms.

[![screen shot 2018-08-06 at 9 24 21 pm](https://user-images.githubusercontent.com/240770/43748893-d8cfb496-99bf-11e8-9261-3fdc810aa07e.png)](https://codepen.io/razh/full/mjGBVV/)

[**CodePen**](https://codepen.io/razh/full/mjGBVV/)

- **`geometry.applyMatrix()`** - The geometry is transformed with `applyMatrix()`.
- **`r93 Box3#applyMatrix4()`** & **`r92 Box3#applyMatrix4()`** - A `Box3` instance is constructed from the geometry. A non-affine matrix is then applied.

For `BoxGeometry`, it is expected is that both operations result in equivalent `Box3` instances.

The `r92` version transformed each `Box3` vertex, then used `setFromPoints()` to resize to fit.

- **r92**: https://github.com/mrdoob/three.js/blob/r92/src/math/Box3.js#L562-L596
- **r95**: https://github.com/mrdoob/three.js/blob/r95/src/math/Box3.js#L562-L585

See https://github.com/mrdoob/three.js/issues/6039 for a similar issue with a `Vector3#applyMatrix4()` optimization.

##### Three.js version

- [x] Dev
- [x] r95
- [x] r94
- [x] r93

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by WestLangley** [comment]
@razh Thank you for providing a well-written and clear demo.

I support reverting #13993.

**Comment by mikialex** [comment]
I haven't consider the case that matrix is not affined, for consistency it should be revert
