### ISSUE TITLE
Replacing material with onBeforeRender does not effect

### ISSUE THREAD

**Issue by zhgu1992** [mrdoob/three.js#14664]
##### Description of the problem

Now I want to replace the old material with a new one when rendering every object, like this:
THREE.Object3D.prototype.onBeforeRender = function (renderer, scene, camera, geometry, material, group) {
    if(this._material){
      return this._material;
    }
};
it does not work.  I do not want to traverse the scene to do this, because it is not very efficient.
Is there any solutions?

##### Three.js version

- [x] Dev
- [x] r95
- [x] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by zhgu1992** [comment]
Now I want to use a new material replace the old when rendering every object, like this. 
THREE.Object3D.prototype.onBeforeRender = function (renderer, scene, camera, geometry, material, group) {
    if(this._material){
      return this._material;
    }
};
it does not work.  I do not want to traverse the scene to do this, becase it is not very efficient.
Is there any solutions?

**Comment by Mugen87** [comment]
No, what you are trying to do is not supported by `onBeforeRender()`. 

> I do not want to traverse the scene to do this, because it is not very efficient.

This highly depends on the complexity of your scene. Normally, an additional traversal should be no problem.

**Comment by zhgu1992** [comment]
when we render some objects with effectComposer like THREE.OultlinePass. [https://github.com/mrdoob/three.js/blob/dev/examples/js/postprocessing/OutlinePass.js#L4](url)  Let us see the code:
`// Make selected objects invisible
			this.changeVisibilityOfSelectedObjects( false );

			var currentBackground = this.renderScene.background;
			this.renderScene.background = null;

			// 1. Draw Non Selected objects in the depth buffer
			this.renderScene.overrideMaterial = this.depthMaterial;
			renderer.render( this.renderScene, this.renderCamera, this.renderTargetDepthBuffer, true );

			// Make selected objects visible
			this.changeVisibilityOfSelectedObjects( true );

			// Update Texture Matrix for Depth compare
			this.updateTextureMatrix();

			// Make non selected objects invisible, and draw only the selected objects, by comparing the depth buffer of non selected objects
			this.changeVisibilityOfNonSelectedObjects( false );
			this.renderScene.overrideMaterial = this.prepareMaskMaterial;
			this.prepareMaskMaterial.uniforms[ "cameraNearFar" ].value = new THREE.Vector2( this.renderCamera.near, this.renderCamera.far );
			this.prepareMaskMaterial.uniforms[ "depthTexture" ].value = this.renderTargetDepthBuffer.texture;
			this.prepareMaskMaterial.uniforms[ "textureMatrix" ].value = this.textureMatrix;
			renderer.render( this.renderScene, this.renderCamera, this.renderTargetMaskBuffer, true );
			this.renderScene.overrideMaterial = null;
this.changeVisibilityOfNonSelectedObjects( true );`
Now we traverse four times and also use the depthMaterial .It cost much time and not very good.
In the OpenGL engine, we also use a scheme strategy. we can render the objects with effectComposer when rendering them with a simple white material or any material you want, and also render the others with a simple black material, then we can get the similar renderTargetBuffer.
But traversing four times every frame cost too much, is there any solutions?

**Comment by shawn0326** [comment]
This problem also exists in the deferred renderer. Perhaps, instead of modifying the onBeforeRender method, it is better to provide a separate getMaterial function to avoid multiple calls to the traverse method？

**Comment by EliasHasle** [comment]
How about moving `Scene.overrideMaterial` to `Object3D`, so that it applies to an object and all of its descendants? (Will of course require checking this property on every object encountered by the renderer during scene traversal.)

**Comment by Mugen87** [comment]
Closing. `onBeforeRender()` can't be used for the OP's request. The mentioned performance aspect can be considered in #14577.
