### ISSUE TITLE
Change of the FBX animated object's position..

### ISSUE THREAD

**Issue by eriadel** [mrdoob/three.js#14662]
##### Description of the problem

Hi again guys,

You've did great job regarding the support for Euler's orders. However there's just another and last issue (at least from our perspective we can't overcome)

After load of the FBX object we see model loaded with animation running.

We can't change object's position. I mean after 👍 

        scene.add(object);
        **object.position.x = -5000;**

Object is still in the center.
Is there anything we can do to move loaded animated FBX object in the space ?

Second thing:

Please consider to add followin patch for Your FBX loader example (this covers some transparency issues regarding models imported from Mixamo:

            if (child.isMesh) {

                if (child.material != null) {

                    var mat = child.material;

                    if (mat.transparent) {
                        mat.transparent = false;
                    }

                    mat.side = THREE.DoubleSide;
                }

                child.castShadow = true;
                child.receiveShadow = true;
            }

Cheers,
Carl

##### Three.js version

- [ ] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by looeee** [comment]
> object.position.x = -5000;

Moving animated objects around works fine for me. Please use the  [forum](https://discourse.threejs.org/) if you need more help with this. 

> Please consider to add following patch for Your FBX loader example

This is something I'm trying to find a proper solution for, in the meantime you will have to apply this patch in your own app. See #11598 and #12625 for more details.
