### ISSUE TITLE
webgl_geometry_spline_editor.html: Camera controls are not responsive

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#14669]
Live: https://threejs.org/examples/webgl_geometry_spline_editor.html

- [x] Dev
- [x] r95

**Comment by Mugen87** [comment]
I think there is a problem related to `TransformControls`. I can not use the mouse right now.

See #14619

**Comment by arodic** [comment]
Although, I am not sure I feel good about the hack. The reason this worked in the first place is not very intuitive (see my comments in #14619) I think we need a better way to handle multiple controls.

**Comment by arodic** [comment]
This one if fixed since #14619 has been merged.

**Comment by WestLangley** [comment]
Thanks @arodic !
