### ISSUE TITLE
Positioning of the object doesn't work for this FBX object.

### ISSUE THREAD

**Issue by eriadel** [mrdoob/three.js#14672]
##### Description of the problem

Positioning of the object doesn't work for this FBX object with recently implemented Euler's orders. 
Why ?

https://drive.google.com/open?id=1l5imG1xL-wDkoT0uUIEkH36fD1fJ0gs3

Considered as a bug in Three JS, cause object, materials are loaded properly and animation is running.

##### Three.js version

- [x ] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by donmccurdy** [comment]
See https://discourse.threejs.org/t/moving-loaded-fbx-models-in-space-how-to-do-this/3709/4, I'm able to reposition the model normally when animations are paused.
