### ISSUE TITLE
JSPM package contains unnecessary files

### ISSUE THREAD

**Issue by LordBenjamin** [mrdoob/three.js#14676]
Including three.js using JSPM (`"three": "github:mrdoob/three.js@r89",`) results in a 400MB dependency - the package includes all source, documentation and examples.

For an application to depend on three.js, only the contents of `build/` are required. Would it be possible to ship a package that only contains these files?

I would expect that if I wanted to work with the docs / examples / etc, I could simply clone or export the Github repo.

![image](https://user-images.githubusercontent.com/13396705/43892214-45b4fcec-9bc3-11e8-907c-02f689e4aa8b.png)

**Comment by Mugen87** [comment]
I don't think there is much what we can do on our side. The `npm` package of `three.js` is small:

https://bundlephobia.com/result?p=three@0.95.0

**Comment by LordBenjamin** [comment]
PR incoming - let me know if there's any issue with adding the JSPM config to `package.json`.

**Comment by kevinlandsberg** [comment]
> PR incoming - let me know if there's any issue with adding the JSPM config to `package.json`.

Hello,

why is the folder examples not included into the jspm files?
I am installing the library via jspm and i am missing the examples folder with all the javascripts inside...
(/examples/js/*). Can you please add it???
