### ISSUE TITLE
Regex issue in TextureLoader

### ISSUE THREAD

**Issue by 4zuko** [mrdoob/three.js#14675]
https://github.com/mrdoob/three.js/blob/a1daef37e5a6b80d0173af54edd000202b95fca5/src/loaders/TextureLoader.js#L34

Description:
It seems that `i` modifier is missing in regex ` /\.(jpg|jpeg)$/`. Or we could be more specific using following regex: `/\.(?:jpe?g|JPE?G)$/`.

Three.js version
- [x] r95

Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

OS
- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I vote for using `/\.(?:jpe?g|JPE?G)$/`;

**Comment by takahirox** [comment]
@4zuko Nice catch. Would you like to make PR?

**Comment by 4zuko** [comment]
@takahirox: Ok. Done.

**Comment by mrdoob** [comment]
I think I would use the `i` modifier instead. What if the user has `name.JPg`... 😁
