### ISSUE TITLE
DirectionalLightHelper and HemisphereLightHelper's orientations are incorrect

### ISSUE THREAD

**Issue by robertlong** [mrdoob/three.js#14683]
The DirectionalLightHelper and HemisphereLightHelper do not take the light's orientation into account.

DirectionalLight:
In this example I have set the DirectionalLight's target to a child of the light and set the light's position and rotation. I have added an AxesHelper to visualize the orientation of the light. The DirectionalLightHelper should be facing the same direction as the light's target.

https://jsfiddle.net/3foLr7sn/80/

HemisphereLight:
In this example I have set the HemisphereLight's position and rotation. I expect the HemisphereLightHelper to reflect the effect of the hemisphere light. So I think I'd expect the yellow side to be facing the sphere. The hemisphere light faces the origin, regardless of rotation, and the HemisphereLightHelper should do the same.

https://jsfiddle.net/3foLr7sn/90/

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
`DirectionalLight` and `HemisphereLight` do not use their rotation property.

**Comment by robertlong** [comment]
Right, but the helpers shouldn't either. Take a look at my examples, the helpers do not reflect the direction of the lights.

**Comment by WestLangley** [comment]
Please do not set the `rotation` property of your lights.

Add `light.target` as a child of the scene -- not the light itself.
