### ISSUE TITLE
MeshBasicMaterial should have displacement map support

### ISSUE THREAD

**Issue by oguzeroglu** [mrdoob/three.js#14697]
I think that the MeshBasicMaterial's should support displacement maps. Since the displacement maps are not directly light related, there's no reason for basic materials to not to support displacement maps.

Any opinions?

**Comment by WestLangley** [comment]
Can you please explain your use case?

**Comment by oguzeroglu** [comment]
Height maps are usually much cheaper than dealing with complex models so are used a lot. There may be cases where the user don't want the material of the object to be affected by lights but still look "displaced". Also the displacement map calculation in the vertex shader has nothing conflicting with the mesh basic material I guess. So why not? The displacement is rather geometry related than the material itself anyway.

**Comment by oguzeroglu** [comment]
Ok, so maybe #14698 helps the user in this use case in the future since it makes the displacement mapping non material related. I'm closing this issue.
