### ISSUE TITLE
Raycaster intersects with invisible objects

### ISSUE THREAD

**Issue by Disorrder** [mrdoob/three.js#14700]
There is one old problem for me, but still I can't find same issue in task tracker.

Have a look at this line:
https://github.com/mrdoob/three.js/blob/a1daef37e5a6b80d0173af54edd000202b95fca5/src/core/Raycaster.js#L46
Why Raycaster checks `visible` property only on intersectable's object? I mean, if I set `visible = false` in parent, children become invisible for renderer, but still intersectable. Should Raycaster check nearest parents until find invisible? I have to check result of intersection for invisible parents in every single project. Is it any reason for not checking parents here?

My code:
```javascript
var bool;
THREE.Object3D.prototype.isVisible = function() {
    bool = true;
    this.traverseAncestors((parent) => {
        if (!parent.visible) bool = false;
    });
    return bool;
};
```

**Comment by WestLangley** [comment]
Is this what you are doing?

```javascript
parent.add( object );
parent.visible = false;

raycaster.intersectsObjects( [ object ], recursive );
```

**Comment by Mugen87** [comment]
Um, this behavior is somewhat inconsistent. From my point of view, it would be actually better if `intersectObject()` does not check the visibility at all and delegates this to the app level code. 

If we keep `if ( object.visible === false ) return; `, we might consider to check the hierarchy, too. However, this will impact performance.

**Comment by Disorrder** [comment]
@WestLangley nope. Recursive means raycaster will trigger all children of intersectable object. But I need to check visibility recursive

**Comment by WestLangley** [comment]
@Disorrder How is that different from the code snippet I posted?

**Comment by mrdoob** [comment]
> Um, this behavior is somewhat inconsistent. From my point of view, it would be actually better if `intersectObject()` does not check the visibility at all and delegates this to the app level code. 

Yeah, I don't know what the solution is. We try to help the user but we can't handle situations like @Disorrder's.

For his use-case... he should either start the raycast test from the parent or use [gpu picking](https://threejs.org/examples/?q=inter#webgl_interactive_cubes_gpu).

**Comment by WestLangley** [comment]
Right. We can't handle situations like @Disorrder's. But we could change raycasting behavior to disregard the object's `visible` property. I think it is worth giving that serious consideration.

**Comment by Mugen87** [comment]
I suggest to remove the test on `Object3D.visible` and add a test based on `Layers` instead. This idea was already suggested here https://github.com/mrdoob/three.js/issues/7551#issuecomment-154400499 and it would be similar to how raycasting works in [Unity](https://docs.unity3d.com/ScriptReference/Physics.Raycast.html). In this way, we decouple the raycast from the visibility of the object but still allow to filter out unwanted objects. Something like this in `intersectObject()` might work:
```js
function intersectObject( object, raycaster, intersects, recursive ) {

        if ( object.layers.test( raycaster.layers ) ) { 

            object.raycast( raycaster, intersects );

        }

	if ( recursive === true ) {

		var children = object.children;

		for ( var i = 0, l = children.length; i < l; i ++ ) {

			intersectObject( children[ i ], raycaster, intersects, true );

		}

	}

}
```
Notice that children would still be tested even if the layer test evaluates to `false` for the current object. In this way, layers in `Raycaster` are treated similar like in `WebGLRenderer`.

**Comment by BarthaBRW** [comment]
Is there any workaround or solution to use raycasting with invisible meshes?

**Comment by WestLangley** [comment]
>Is there any workaround or solution to use raycasting with invisible meshes?
```js
mesh.visible = true;
mesh.material.visible = false;
```

**Comment by BarthaBRW** [comment]
It will make the renderer draw it even its material is invisible, won't it?

**Comment by Mugen87** [comment]
> In this case, it will make the renderer draw it even if its material is invisible, won't it?

No, the renderer does only push renderable objects in the render list if the respective material is visible:

https://github.com/mrdoob/three.js/blob/7ed66c17b2e1a028e006916baf4f0bffe5a9622a/src/renderers/WebGLRenderer.js#L1346-L1350

**Comment by BarthaBRW** [comment]
Then it's cool, thank you.

**Comment by Mugen87** [comment]
Related: #11312

**Comment by fernandojsg** [comment]
I'd love to get this in, it could be super useful when interacting with different elements that you want to toggle on/off using the same raycaster, eg: opening the UI and hiding the elements on your scene or so.

**Comment by Mugen87** [comment]
There is one side effect when introducing `THREE.Layer` to `THREE.Raycaster` which is important to highlight. Let's say you want to exclude certain objects from raycasting via layers. This could be achieved by shifting objects from the default layer `0` to layer `1` via:
```js
object.layers.disable( 0 );
object.layers.enable( 1 );
```
You have to be aware that with this configuration, objects in layer `1` won't get rendered since the renderer only processes objects which have a common layer with the camera. To render all objects AND to exclude certain objects from raycasting, you also need to configure the camera. In the above case you need to enable layer `1`.
```js
camera.layers.enable( 1 );
```
So although the introduction of `THREE.Layer` will provide great flexibility, the dependency to `Camera.layers` might be a confusing bit for users. However, this could be clarified with the documentation.

**Comment by mrdoob** [comment]
I think using `layers` would be better:

https://github.com/mrdoob/three.js/blob/d2a4ed6c98a1621df65b7b5081715170add884fe/src/core/Object3D.js#L105

**Comment by mrdoob** [comment]
Ops! Dupe-posted 😁

**Comment by mrdoob** [comment]
But, we could add `layers` to `Raycaster` too.

**Comment by mrdoob** [comment]
#11312 was pretty much there.

**Comment by Mugen87** [comment]
> But, we could add layers to Raycaster too.

Yes, that's just the other way around. I guess we only need to highlight in the docs how this approach is intended to be used.

> #11312 was pretty much there.

Yes, the question is should we remove the test on `Object3D.visible` and only rely on layers instead?

**Comment by mrdoob** [comment]
> Yes, the question is should we remove the test on `Object3D.visible` and only rely on layers instead. The current way how `Object3D.visible` is handled is a bit inconsistent as the OP pointed out.

Yes, I vote for removing the `Object3D.visible` check (even if we may break user-land code). And implement `Layers`.

**Comment by fernandojsg** [comment]
+1 for removing `.visible` in favor of `layers`

**Comment by steve3d** [comment]
well, I really don't need this _feature_ , I need to ignore the invisible objects for raycast.

so someone need to raycast invisible, and someone still need to ignore invisible when raycast, why not create a switch so users can decide when to ignore invisible objects?

**Comment by Mugen87** [comment]
I think using `THREE.Layers` should provide you this flexibility now.

**Comment by andrew-morse** [comment]
Just updated to the latest version of THREE which includes this `Raycaster.layers` feature (which is a great idea by the way), and at first it seemed to break our previous implementation of Raycaster.  We use Layers in our application to show/hide different entities, and both Layers and Raycaster had previously worked great prior to updating THREE.

Once I updated, `Raycaster.intersectObjects()` started returning an empty array.  It seems that I now need to use `raycaster.layers.set()` to enable all of our entities on layers to be visible to the Raycaster.  Once I made this change `Raycaster.intersectObjects()` began working properly again.

So, now I'm curious about the default state of Raycaster.  I figured that Raycaster would by default check all layers if no layers were 'set', but the opposite seems to be true.  You now need to tell Raycaster explicitly what layers to include, even if that means running all layers through `raycaster.layers.set()`.  Just hoping to get some clarification on why it was built this way.  Thanks!

**Comment by Mugen87** [comment]
The default state is the same like for cameras. Raycaster only checks objects in channel zero. If you assign objects to different layers, you also have to configure the camera and raycaster accordingly.

**Comment by themightyatom** [comment]
Alternative strategy! (for anyone having similar issues)

It's worth remembering that you send an array of objects to Raycaster in the first place, and in this array you can easily weed out the objects you don't want in the Raycast operation.  That's always been my strategy, and never had any problems.

**Comment by williammeers** [comment]
I have added to the three js method (function intersectObject(object, raycaster, intersects, recursive) {):

if (object.visible === false) return; // Checking if visible
