### ISSUE TITLE
Roughness problem when using equirectangular hdr image for MeshStandardMaterial's envMap

### ISSUE THREAD

**Issue by zhutq** [mrdoob/three.js#14709]
##### Description of the problem
I'm trying to use equirectangular .hdr image as MeshStandardMaterial's envMap.
It seems roughness does not work with equirectangular .hdr envMaps, although it does work with cube hdr maps.

The original examples/webgl_materials_variations_standard.html, using cube hdr maps, looks like:
![screenshot from 2018-08-14 21-36-11](https://user-images.githubusercontent.com/1166360/44096095-05add5c6-a00d-11e8-96de-3cc6668a8e7c.jpg)

When using an equirectangular hdr image instead, the result is as follows. The reflections of higher roughness are as sharp as that of lower roughness.
![screenshot from 2018-08-14 21-41-38](https://user-images.githubusercontent.com/1166360/44096101-0979bd96-a00d-11e8-9711-91791be8d7ff.jpg)

My loading code:
```javascript
new THREE.RGBELoader().load( 'textures/miranda_uncropped.hdr', function( texture ) {
	texture.encoding = THREE.RGBEEncoding;
	texture.flipY = true;
	texture.mapping = THREE.EquirectangularReflectionMapping;

       	// .....
       	var material = new THREE.MeshStandardMaterial( {
		map: imgTexture,
		bumpMap: imgTexture,
		bumpScale: bumpScale,
		color: diffuseColor,
		metalness: beta,
		roughness: 1.0 - alpha,
		envMap: index % 2 === 0 ? null : texture
	} );
        // ......
```

##### Three.js version

- [x] Dev
- [ ] r95
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Only cube environment maps are supported for `MeshStandardMaterial`.

See if you can get `EquirectangularToCubeGenerator` to work in your use case.

Example: https://threejs.org/examples/webgl_materials_envmaps_exr.html

**Comment by zhutq** [comment]
> See if you can get EquirectangularToCubeGenerator to work in your use case.
> Example: https://threejs.org/examples/webgl_materials_envmaps_exr.html
EquirectangularToCubeGenerator results in black when `texture.encoding = THREE.RGBEEncoding`.
My loading code:
```
new THREE.RGBELoader().load( 'textures/miranda_uncropped.hdr', function( texture ) {
	texture.encoding = THREE.RGBEEncoding;
	texture.minFilter = THREE.NearestFilter;
	texture.magFilter = THREE.NearestFilter;
	texture.flipY = true;

        var cubemapGenerator = new THREE.EquirectangularToCubeGenerator( texture, 512 );
        // ......
```

**Comment by richardmonette** [comment]
The THREE.EquirectangularToCubeGenerator has the assumption that your data is already in THREE.RGBAFormat, if I recall correctly. Can you pre-convert your RGBE image to Linear RGBA? Alternatively, if you use equirectangular EXR, then https://threejs.org/examples/webgl_materials_envmaps_exr.html would be exactly the example you need.
