### ISSUE TITLE
OffscreenCanvas does not have toDataURL ability

### ISSUE THREAD

**Issue by troy351** [mrdoob/three.js#14713]
##### Description of the problem

https://github.com/mrdoob/three.js/blob/b4908d2aa519097fea5d1f98c276e129ea9779cf/src/extras/ImageUtils.js#L13-L53

if `canvas` is an instance of `OffscreenCanvas `, the call `canvas.toDataURL`  will throw an error, should avoid it,

##### Three.js version

- [ ] Dev
- [x] r95
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Oh, I guess we should remove that if statement then.
Would you like to do a Pull Request?

**Comment by troy351** [comment]
you mean remove `OffscreenCanvas` part, just use `canvas` ?
