### ISSUE TITLE
Drawcalls optimization: ordering faces by materialIndex

### ISSUE THREAD

**Issue by jfcampos** [mrdoob/three.js#14724]
##### Description of the problem

Recently I managed to greatly improve the performance in one of my scenes and wanted to share my solution, maybe this could end up as a feature in three.js... or maybe it already exists and I just didn't see it :)

My 3D model is one big mesh (exported from blender) with over 40 materials, lightmapping, etc, and loading it into my scene adds ~900 drawcalls, resulting in very poor performance (specially in VR).

So I had the idea of grouping the faces with the same materialIndex together, hoping they will be drawn in the same drawcall. I created this script and the drawcalls reduced from over 1000 to 95.

If this is a valid solution I can do a PR.

        var geometry = mesh.geometry;

        var perMaterial = {};

        //Categorize faces and uvs by materialIndex
        for (var i = 0; i < geometry.faces.length; i++) {
            var f = geometry.faces[i];
            if (!perMaterial[f.materialIndex]) {
                perMaterial[f.materialIndex] = [];
            }
            var temp = {};
            temp.face = f;
            temp.uvs = [];
            for (var j = 0; j < geometry.faceVertexUvs.length; j++) {
                temp.uvs.push(geometry.faceVertexUvs[j][i]);
            }

            perMaterial[f.materialIndex].push(temp);
        }

        //Create new ordered arrays
        var faces = [];
        var uvs = [];

        for (var key in perMaterial) {
            for (var i = 0; i < perMaterial[key].length; i++) {
                var temp = perMaterial[key][i];
                faces.push(temp.face);
                for (var j = 0; j < temp.uvs.length; j++) {
                    if (!uvs[j]) uvs[j] = [];
                    uvs[j].push(temp.uvs[j]);
                }
            }
        }

        //Asign new arrays to geometry
        geometry.faces = faces;

        for (var i = 0; i < uvs.length; i++) {
            geometry.faceVertexUvs[i] = uvs[i];
        }

        geometry.elementsNeedUpdate = true;

##### Three.js version

- [x] Dev
- [ ] r95
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Correct, face sorting is a valid approach in order to reduce draw calls. Have you realized that there is already [Geometry.sortFacesByMaterialIndex()](https://threejs.org/docs/#api/core/Geometry.sortFacesByMaterialIndex)?

**Comment by WestLangley** [comment]
This is already supported for `Geometry`. For `BufferGeometry`, see #13748, which is currently waiting improvement.

**Comment by jfcampos** [comment]
... I can't believe it was already available in geometry right in front of me. Damn!

Well I'm happy I got to the right solution on my own. Thanks guys.

Is there a reason for not applying this automatically?

**Comment by Mugen87** [comment]
> Is there a reason for not applying this automatically?

Yeah, it would be nice if face sorting is performed automatically by the engine. But from my point of view, it's important that the original geometry object (which is in control of the user) is not altered in an unexpected way. This might be one reason why it's not supported by `three.js`.

In any event, it might be a good idea to implement face sorting in `DirectGeometry.fromGeometry()`. This method is internally used by `three.js` when converting a `Geometry` to a `BufferGeometry` object.

**Comment by jfcampos** [comment]
Got it. I'll close the issue. Many thanks.

**Comment by fractalfantasy** [comment]
any idea of how to do this with a buffer geometry?
