### ISSUE TITLE
CanvasRenderer: renderOrder breaks z-ordering

### ISSUE THREAD

**Issue by rattai** [mrdoob/three.js#14725]
##### Description of the problem

When using the CanvasRenderer, objects with a higher renderOrder are always visible even if they are behind lower renderOrder objects.

This [jsfiddle](https://jsfiddle.net/my5xoLzf/27/) shows the same scene rendered with WebGL on top and Canvas on the bottom.  The red box has renderORder=10.  The sphere has default renderOrder=0.

![screenshot from 2018-08-16 14-43-41](https://user-images.githubusercontent.com/1168030/44228595-aeb91700-a163-11e8-8ccf-878f48652f84.png)

##### Three.js version

- [x] Dev
- [x] r95
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
This is a limitation (some may say a feature) of the `CanvasRenderer`.
