### ISSUE TITLE
GLTFLoader: availability of original node info of parsed Object3D (feature request)

### ISSUE THREAD

**Issue by rdrgn** [mrdoob/three.js#14739]
glTF handles nodes with their indices (`nodeIndex` or `nodeId` in `GLTFParser`). So some extension data in glTF-based file formats (e.g. [bone mapping in VRM](https://dwango.github.io/en/vrm/vrm_spec/#model-bone-mapping-json-extensions-vrm-humanoid)) depend on node indices.

However, it seems that objects loaded by current `GLTFLoader` don't have any indices info. We can get complete node data from `data.parser.json.nodes`, but cannot link them with parsed objects in `data.scene` one to one.

I suggest adding original node info to `Object3D.userData` or adding an array of nodes with `Object3D` references to somewhere.

**Comment by donmccurdy** [comment]
I should point out that glTF nodes do not necessarily map 1:1 with three.js nodes — in this example...

- node 
  - mesh
    - primitive
- node
  - mesh2
    - primitive1
    - primitive2
    - primitive3
    - ...

... we attempt to flatten things as much as possible. The first node will result in a single THREE.Mesh, where the second may become a Group containing one or more meshes, or a single mesh, depending on whether the primitives can be merged safely. So unfortunately, even with userData, the mapping you suggest is not trivial.

Do you mind saying a bit more about how you would want to use these indices? If you ensure your objects have unique names, using node names and `scene.getObjectByName(...)` may be more robust. Or accessing `parser.getDependency( 'node', index )` directly, combined with https://github.com/mrdoob/three.js/pull/14492, may be an option.

**Comment by rdrgn** [comment]
Thank you for the comment. And please excuse my lack of explanation. I understood that it is impossible to map 1:1.

VRM, for example, uses nodes' indices to specify which bone is humanoid's head, arm, etc. or which node has a collider. I had tried to use node names and `scene.getObjectByName(...)` for mapping. But node names  sometimes conflict because they are not guaranteed to be unique in glTF.

However, I think `scene.getObjectByName(...)` is a flexible method. This is enough in most cases. So I will try to solve the issue at my own application for the time being.

**Comment by donmccurdy** [comment]
Closing for now, but feel free to comment on https://github.com/mrdoob/three.js/issues/15087 if you have preferences on how we handle duplicate node names. Thanks!

**Comment by rdrgn** [comment]
Now, #15418 seems to be helpfull for me!
I love three.js and its contributors.

**Comment by FMS-Cat** [comment]
`:eyes:`
