### ISSUE TITLE
PLY Loader & Textures

### ISSUE THREAD

**Issue by AndreySukhov** [mrdoob/three.js#14735]
As it said in this issue https://github.com/mrdoob/three.js/issues/3382

```
the PLYLoader does not support texture coordinates.
```

Is it still the same ? 

code:
```
var loader = new PLYLoader()
    loader.load(path,(geometry) => {
      geometry.computeVertexNormals();

      new THREE.TextureLoader().load( `${url}` (texture) => {
        let material = new THREE.MeshStandardMaterial({
          map: texture,
        })

        let mesh = new THREE.Mesh(geometry, material)
        mesh.position.x = 0
        mesh.position.y = 0
        mesh.position.z = 0
        mesh.rotation.x = -Math.PI / 2
        mesh.scale.multiplyScalar(1.2)
        mesh.castShadow = false
        mesh.receiveShadow = false
        this.scene.add(mesh)
        this.camera.position.set(15, 15, 121)

        this.preloaderRoot.querySelector('progress').setAttribute('value', '100')
        this.preloaderRoot.style.display = 'none'
      })
    }, onProgress, onError)

```

three.js - 0.93.0
Chrome latest
macOs Sierra 10.12.6

screenshot of the result in attachment
![screen shot 2018-08-17 at 16 09 47](https://user-images.githubusercontent.com/11033139/44267737-0923a780-a238-11e8-9363-19339507eb87.png)
##### Three.js version

- [x] Dev
- [x] r95
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
`PLYLoader` should be able to parse texture coordinates. 

https://github.com/mrdoob/three.js/blob/af878f446dc4d5ee6153000cee88dd32e902eb91/examples/js/loaders/PLYLoader.js#L337-L341

Can you share your `PLY` file in this thread?

**Comment by AndreySukhov** [comment]
yes, it can be downloaded with this link https://yadi.sk/d/FYvKvmo53aKoKQ 
Textures are in .jpg , if this matters

**Comment by WestLangley** [comment]
If uv's are defined in the file, they are not handled. The model loads as position-only data.

Here is the model rendered using `MeshNormalMaterial` with `flatShading`.

![screen shot 2018-08-17 at 7 24 07 pm copy](https://user-images.githubusercontent.com/1000017/44293144-5bc08c00-a257-11e8-9c8b-fca0d10934d2.jpg)

**Comment by Mugen87** [comment]
An other workaround is to convert the `PLY` file to `glTF`. Blender is able to import `PLY` files. You can then perform an export to `glTF` with the following tool: https://github.com/KhronosGroup/glTF-Blender-Exporter

More information in: https://threejs.org/docs/#manual/introduction/Loading-3D-models

**Comment by AndreySukhov** [comment]
thanks,  I'll try that solution

**Comment by Mugen87** [comment]
> uv's are defined in the file, but they are not handled. 

@makc I've seen you've added the support for texture coordinates (#9121). How common is this type of uv definition in PLY (I mean what @WestLangley mentioned, one uv pair per index)? Do you think it's worth to implement this feature request?

**Comment by WestLangley** [comment]
@Mugen87 Yeah, it appears you reverted @makc's `texcoord` support when you filed #9796.

**Comment by Mugen87** [comment]
Yeah, we aware of this see https://github.com/mrdoob/three.js/pull/9796#issuecomment-250842474

**Comment by WestLangley** [comment]
You could have retained @makc's PR if you created non-indexed `BufferGeometry`. You can determine if non-indexed is required from the header.

**Comment by makc** [comment]
@Mugen87 
> Do you maybe know how common this type of uv definition is in PLY

no idea, it was one time thing I did from sample file

**Comment by WestLangley** [comment]
The right way to handle `texcoord` is to check if shared vertices share the same uv, and if not, duplicate only the vertices necessary. That way, the indexed-geometry can be retained.

But unless there is user demand for `texcoord`, I would suggest holding off on this for now -- especially since there are noted workarounds.

**Comment by tbalouet** [comment]
If user demand is needed, I'm actually working on a model loader using mainly PLY files, and the client I'm working for would like to use the exported textures from the scanner he has, so this feature would be highly appreciated (but I think it's already in the pipes as MrDoob marked it for r97)

**Comment by Mugen87** [comment]
@AndreySukhov Can you please verify if your model loads correctly with the new PR?
