### ISSUE TITLE
provide timeliner_gui  source code ?

### ISSUE THREAD

**Issue by tong3d** [mrdoob/three.js#14758]
##### Description of the problem

in examples-->js-->libs-->timeliner_gui.min.js 
it can provide source code?

##### Three.js version

- [ ] Dev
- [ ] r95
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I guess you are looking for:

https://github.com/tschw/timeliner_gui

**Comment by JumpNote** [comment]
thank you！！！
