### ISSUE TITLE
ES6 import of three.js broken

### ISSUE THREAD

**Issue by griffin2000** [mrdoob/three.js#14760]
At ToT(1fe4e34b7a6ff26824c8fd276d0c3c285aed656f import ) three.js ES6 import seems to be broken:

Importing as an ES6 module as described here (https://threejs.org/docs/#manual/introduction/Import-via-modules):
`import * as THREE from '/static/js/third-party/three.js';`

Results in this error
```
three.js:4 Uncaught TypeError: Cannot set property 'THREE' of undefined
    at three.js:4
    at three.js:5
```
Are  there more up-to-date instructions for including as a module? Or is this a bug?

**Comment by BlueMagnificent** [comment]
It looks like you are importing from three.js version that was meant to be included via tag script. Did you try
`npm install three`
How exactly is your setup?

**Comment by griffin2000** [comment]
I am using a built version. I actually see the issue. I'm importing three.js, it show be three.module.js (that is built in \three.js\build).

This works fine:
`import * as THREE from '/static/js/third-party/three.module.js'; 
`

**Comment by Mugen87** [comment]
The documentation assumes you are importing the `npm` module. But yeah, using `three.module.js` is the solution if you want to work with `import` statements.
