### ISSUE TITLE
PCDLoader does not handle errors correctly

### ISSUE THREAD

**Issue by elcommie** [mrdoob/three.js#14776]
##### Description of the problem

The PCDLoader doesn't handle errors well.  If there's an error when parsing, the error handler passed in is not called and the resulting exception is only caught by a global process handler.  This may apply to all loaders as if there's an error in the `setTimeout` method used for loading there's no way to catch that exception.  

```js
        var url = 'https://threejs.org/examples/textures/sprites/disc.png';
        var loader = new THREE.PCDLoader().load(
          url, 
          () => alert('something loaded'),
          () => {},
          () => alert('error handler - never gets called')
        );
```

##### Three.js version

-  r91

##### Browser

- [x] All of them
- [x]  Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [x] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

any

**Comment by mrdoob** [comment]
Could you attach files here that the loader has trouble parsing?

**Comment by elcommie** [comment]
Sure.  Here's an image file:

![disc](https://user-images.githubusercontent.com/28607371/44612129-b52a3d00-a7ba-11e8-8ffd-51432b9a76af.png)

**Comment by Mugen87** [comment]
Maybe something like this would help to improve error handling:
```js
try {

    onLoad( scope.parse( data, url ) );

} catch ( e ) {

    if ( onError ) onError( e );

}
```
The `onError()` callback of `PCDLoader.load()` would be able to handle exception causes by an invalid format.

**Comment by elcommie** [comment]
Don’t think that will work.  The `onLoad` method calls `setTimeout` internally.  I would think you’d need to put the try catch there

**Comment by Mugen87** [comment]
I was able to catch the error with this code when trying to load the following URL with `PCDLoader`:

https://threejs.org/examples/textures/sprites/disc.png

**Comment by elcommie** [comment]
You're right.  That worked.  I'm surprised given that it does seem to be calling onLoad in a setTimeout, but perhaps because the timeout is 0?  

It would be good to add a re-throw if no `onError` method is specified, but otherwise that seems to solve the issue.

**Comment by Mugen87** [comment]
Would you like to do a PR and add the code snippet to `PCDLoader`:innocent:?

**Comment by elcommie** [comment]
Sure.  Why not?  I'll get something up later today
