### ISSUE TITLE
SpotLightHelper: Incorrect orientation with rotated spotlight.

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#14773]
When a SpotLight is rotated, its SpotLightHelper will face the wrong direction.

Demo: https://spotlighthelper-rqvdesskxl.now.sh/examples/webgl_lights_spotlight

```js
spotLight = new THREE.SpotLight( 0xffffff, 1 );
scene.add( spotLight.target );
spotLight.quaternion.set( -0.707106769, 0, 0, 0.707106769 ); 
```

While a spotlight doesn't need to be rotated explicitly (it has a target), appending the target as a child of the light, then rotating the light, is a helpful trick to get a direction-based API (e.g. when the light is loaded from a model) or to animate the light. In this situation the helper doesn't work properly.

![screen shot 2018-08-23 at 8 13 40 pm](https://user-images.githubusercontent.com/1848368/44562994-0c73d300-a711-11e8-872c-745ae8b9e15c.png)

**Comment by WestLangley** [comment]
`Spotlight`  does not honor its `rotation` and `quaternion` properties, and the quaternion should not be changed.

**Comment by WestLangley** [comment]
#14738 is closely-related to this issue.

**Comment by donmccurdy** [comment]
Rotation and quaternion can still affect the direction of the light, though —

```js
light.add( light.target );
scene.add( light );
light.rotation.x = Math.PI / 3;
```

Demo: https://spotlighthelper-fmurzsqzcq.now.sh/examples/webgl_lights_spotlight

GLTFLoader relies on this to create an expected behavior that (1) spot lights can be animated, and (2) the light's direction is always +Z relative to its local transform.

**Comment by WestLangley** [comment]
`SpotLight` and `DirectionalLight` behavior will likely have to be changed. See #14658.

Furthermore, to be compatible with your specs, `light.target` may have to be removed completely.

I think we should deal with this as soon as possible.

**Comment by donmccurdy** [comment]
Unfortunately, yes. The `light.add( light.target )` hack does _almost_ what glTF needs it to do, but certain things (like scaling on one axis) will cause the spot light to behave non-directionally. Also related: https://github.com/mrdoob/three.js/issues/14618

**Comment by rowild** [comment]
This behaviour seems to be happening since v96. In v95 the helper works correctly - see pen:
`https://codepen.io/rowild/pen/pQZJqz?editors=0010`
The pen is currently set to v95. If the version is changed to v96 or anything else above, the direction of the the cone is calculated wrongly. 
Let me know if the pen is related to this behaviour or if I should open a new issue. Thanks!
Thanks a ton to @manthrax for helping me out with this!
