### ISSUE TITLE
Support material similar to Blender's "Principled BSDF"

### ISSUE THREAD

**Issue by moorage** [mrdoob/three.js#14778]
Blender's [Principled BSDF shader](https://docs.blender.org/manual/en/dev/render/cycles/nodes/types/shaders/principled.html) is an extremely powerful PBR shader with a lot of convenient settings as seen below.

I'd love either a wiki on how to convert values from a principled BSDF shader node in blender and turn those into a three.js material, or even better, a helper function to do so!

![render_cycles_nodes_types_shaders_principled_node](https://user-images.githubusercontent.com/8590/44611232-dab44800-a7b4-11e8-886a-b6e8093408d5.png)

**Comment by mrdoob** [comment]
@donmccurdy do you know if the GLTF exporter handle these?

**Comment by donmccurdy** [comment]
glTF-Blender-Exporter does not support Principled BSDF nodes, but the next version ([glTF-Blender-IO](https://github.com/KhronosGroup/glTF-Blender-IO/)) already does. Properties that exist in glTF's PBR model (metalness, roughness, AO, emissive, baseColor, alpha, normal, tangent) are exported, the rest are ignored. I expect that more of these PBR properties will make their way into glTF over time.

**Comment by moorage** [comment]
By 'alpha' do you mean tranmission, by any chance?

**Comment by donmccurdy** [comment]
No, they're fairly different ([see this thread](https://developer.blender.org/T51408)), but I do see a "TODO" in the glTF-Blender-IO code suggesting that we try to use the transmission data for alpha automatically. That would be a very rough approximation, though. Neither glTF nor three.js have IOR transparency yet, but again that will evolve over time.
