### ISSUE TITLE
Mobile Fog Bug Part 2

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#14786]
Continuation of #14736 as a result of fix #14752 

While fog now works on mobile with mediump, it is still bugged.

Sorry for the less than perfect example, adding the heightmap to highlight the issue would be a pain. Will do so if necessary.

https://jsfiddle.net/titansoftime/o81nje2a/

See the break of fog on the green plane at the furthest distance:

![bug](https://user-images.githubusercontent.com/6549763/44623879-27754d00-a8a1-11e8-9477-7dfa0f9f0637.PNG)

This is also what I am seeing in app (although much more noticeable than in the example):

![bug](https://user-images.githubusercontent.com/6549763/44623883-4a076600-a8a1-11e8-9d4f-685932f97624.jpg)

**Comment by greggman** [comment]
I already gave you a solution. 

https://github.com/mrdoob/three.js/pull/14740

**Comment by titansoftime** [comment]
So this new fog puts a limit on camera.far? In the example this is no problem, in app however, it means I will have to make things a bit smaller as I have lensflares, and domes from the hemisphere light example etc. that need to be further than the terrain plane.

In master version I have no issues whatsoever and the fog doesn't really look noticeably different.

It's not like three.js to knowingly include bugs.

**Comment by WestLangley** [comment]
>It's not like three.js to knowingly include bugs.

That is a false premise.

>Please help by experimenting with your code to identify changes that will make the problem go away.

...and then report back.

**Comment by titansoftime** [comment]
The change that make the bug go away in all situations is using the master version instead of the dev build.

I recommend reverting the change to fog as bhouston has pointed out the previous method not only worked but is considered a viable option by respected voices in the 3d community.

I feel like I have put more than enough time into this issue. I will be overwriting the fog shader code moving forward as that seems to be recommended solution for resolving three.js issues.

Leaving this open in case anyone decides to actually fix it.

**Comment by mrdoob** [comment]
@titansoftime what @WestLangley is asking for is to see if you can help us by tweaking the `camera.far` and `fog.distance` values and see if the artifact goes away at some point. We can't reproduce outselves so that kind of information will help us when trying to resolve this.

**Comment by mrdoob** [comment]
Also, is this with `Fog` or `FogExp2`?

**Comment by titansoftime** [comment]
I will unfortunately not have the free time myself to play around with this until at least this weekend (if not the weekend after that). Debugging mobile at my pharmacy is too obvious lol. Kids just started school etc. etc. Super busy.

FogExp2.

**Comment by mrdoob** [comment]
Okay. Reverted for now.
