### ISSUE TITLE
Materials length of childrens "undefined" instead of 1.

### ISSUE THREAD

**Issue by turkoz14** [mrdoob/three.js#14799]
I was iterating on the materials of childrens objects from a .obj model when i realized that when the length of materials is 1 instead of return 1 it returns undefined. Dont know if this is intentionally, but it seems incorrect to me.
Thanks!
![screen shot 2018-08-28 at 15 10 42](https://user-images.githubusercontent.com/7903152/44742048-42300780-aad5-11e8-9832-0c81426d0028.png)

**Comment by donmccurdy** [comment]
Could you share the code involved in that printout? Note that `mesh.material` is not necessarily an array. It can be a reference to a `Material` instance, which would not have a length property. i.e.:

```js
/* {THREE.Material|Array<THREE.Material>} */
mesh.material;
```

**Comment by turkoz14** [comment]
this is how i iterate on the childrens materials 

for(var i = 0; i < object.children.length;i++)
{
  console.log("Nombre Material: "+object.children[i].name);
  console.log("Cant Material: "+object.children[i].material.length);
  for(var j = 0; j < object.children[i].material.length;j++ ){
    if(object.children[i].material[j].name == "mat1")
    {
      console.log("mat1");
      object.children[i].material[j] = mat1;
    }
    else if(object.children[i].material[j].name == "mat2")
    {
      console.log("mat2");
      object.children[i].material[j] = mat2;
    }
    else if(object.children[i].material[j].name == "mat3")
    {
      console.log("mat3");
      object.children[i].material[j] = mat3;
    }
    else if(object.children[i].material[j].name == "mat4")
    {
      console.log("mat4");
      object.children[i].material[j] = mat4;
    }
  }
}

**Comment by donmccurdy** [comment]
I see, thanks. Your code assumes that `.material` will always be an array, which isn't the case. A more robust approach would be:

```js
var materials = Array.isArray( object.children[i].material )
  ? object.children[i].material
  : [ object.children[i].material ];
console.log('Cant Material: ' + materials.length);
for ( var j = 0; j < materials.length; j++) { ... }
```
