### ISSUE TITLE
Requesting media stored on S3 via Cloudfront does not work when cloudfront distribution is restricted

### ISSUE THREAD

**Issue by pineapplejoe** [mrdoob/three.js#14797]
We are trying to access textures on Amazons AWS S3.  The media is fronted by their CDN cloudfront.  

We have aliased the CDN distribution to look like a subdomain of ours.  So for example.

our website : foo.com.
Cloudfront CDN will be: cdn.foo.com

Cloudfront can restrict access via signed cookies.  We have the signed cookies (NOTE: these are set with the domain parameter explicitly set so that subdomains will also receive the cookies) - and using regular html elements like the IMG element - we can see that the HTTP request header contains the signed cookies.  As a result the IMG element is able to show our images just fine.  

However - when we try and load same images via textureloader - we get CORS errors and in inspecting the headers - we dont see any cookies.  We instead see chrome referring to "provisional headers are shown".  

A bit new to troubleshooting in this space but based on our searching we dont see a solution.   Heres what we are doing.  We have tried setting crossorigin to "" or "anonymous".  Neither works.  

		var imageTextureLoader = new THREE.TextureLoader();
		imageTextureLoader.setCrossOrigin("use-credentials");
		imageTextureLoader.load(imageName, function(imageTexture){ ...});

What are we missing?  What do you suggest we try?  Since the regular browser elements just work - trying to figure out why this is different.  

NOTE: When we make the Cloudfront distrubution not restrict access - this feature works as expected.  However we need to restrict access so our content is just not available anywhere and everywhere. 

##### Three.js version

Version 92

##### Browser

- [] All of them
- [ X] Chrome - only Chrome is supported.  Unknown if others work or dont work. 
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
