### ISSUE TITLE
VRML importer does not respect object positions.

### ISSUE THREAD

**Issue by Glinkis** [mrdoob/three.js#14798]
When using the VRML importer, any objects that does not have their pivot in the center of the scene are moved to the center of the scene.

##### Three.js version
r94

##### Browser
- [x] All of them

##### OS
- [x] All of them

**Comment by Glinkis** [comment]
When importing this file: 
[test.wrl.zip](https://github.com/mrdoob/three.js/files/2339052/test.wrl.zip)

This is how I expect it to be:
<img width="296" alt="screen shot 2018-08-31 at 08 48 23" src="https://user-images.githubusercontent.com/8037927/44897059-b4356600-acfa-11e8-88e6-62f117785b0e.png">

This is what I get:
<img width="469" alt="screen shot 2018-08-31 at 08 48 30" src="https://user-images.githubusercontent.com/8037927/44897072-be576480-acfa-11e8-8392-1d716c3e6d2c.png">

**Comment by Glinkis** [comment]
This may be a problem with my own code after all.
I will dive a bit deeper, and if this is indeed the case I will close this issue with an apology.

**Comment by Mugen87** [comment]
> I will dive a bit deeper, and if this is indeed the case I will close this issue with an apology.

No problem. I've loaded the file in `webgl_loader_vrml` and see this:

![image](https://user-images.githubusercontent.com/12612165/44903539-1b5c1600-ad0d-11e8-82a0-786afb9ef7cc.png)

**Comment by Glinkis** [comment]
Yes, it seems that this was an issue in my code, that had to do with detaching the object from its parent before the scene graph world matrices had been calculated.
