### ISSUE TITLE
CubeCamera does not support layers

### ISSUE THREAD

**Issue by brianchirls** [mrdoob/three.js#14804]
##### Description of the problem

It seems to me that `CubeCamera` should support `layers` just like all the other camera types and the abstract base class. [As it is now](https://github.com/mrdoob/three.js/blob/34dc2478c684066257e4e39351731a93c6107ef5/src/cameras/CubeCamera.js#L22-L50), six child cameras are created, and the layers are not copied over.

There is currently a workaround, which is to traverse through the children and set layers, but it's a bit cumbersome and inconsistent.

Thanks.

##### Three.js version

- [x] Dev
- [x] r95
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by aardgoose** [comment]
Two ways of approaching this I can think of.

Simple way. For each sub camera use the parent camera's layers object.

`cameraXX.layers = this.layers;`

down side, removes the ability to set sub cameras separately  easily,  Does anyone do that/want to do that?

Overly complicated way.

replace the CubeCamera.layers object with an object with functions that updates the sub cameras layers object, which preserves exiting behaviour allowing sub camera layers to be set individually. 

Any thoughts @mrdoob, simple way seems best to me.
