### ISSUE TITLE
VRMLLoader: Support normals, creaseAngle, and index

### ISSUE THREAD

**Issue by Glinkis** [mrdoob/three.js#14814]
When importing this vrml file: [test.wrl.zip](https://github.com/mrdoob/three.js/files/2339702/test.wrl.zip), I expect to get this:

<img width="221" alt="screen shot 2018-08-31 at 12 24 28" src="https://user-images.githubusercontent.com/8037927/44907618-de961c00-ad18-11e8-8133-e6ecb80902a2.png">

But instead I get this:

<img width="251" alt="screen shot 2018-08-31 at 12 24 42" src="https://user-images.githubusercontent.com/8037927/44907622-e229a300-ad18-11e8-85bd-39620bb73da0.png">

When inspecting the VRML file, I can see that there is an attribute called `creaseAngle`, which I suspect is the normal definition angle.

However, in the source code for the `VRMLLoader`, I can find no such attribute check.

**Comment by WestLangley** [comment]
Your file specifies no normals, correct? Therefore the loader can't import them.

However, the loader does compute them. The loader generates non-indexed `BufferGeometry`, a collection of independent triangles, and the computed normals are 'flat' ones orthogonal to each face.

You are correct that the loader does not honor `creaseAngle` when computing normals.

**Comment by Glinkis** [comment]
I just want to say I am currently working on both `creaseAngle` and `normals` support.
`Normals` support is done, but I want to implement creaseAngle and indexing before I issue a pull request.

**Comment by WestLangley** [comment]
Questions:

1. It is correct to say that this loader should be expected to _create_ normals if normals are not specified in the file?

2. I never liked calling `computeVertexNormals()` in loaders. IMO, the loaders should just load the data in the file, not create data. It is OK if this loader is an exception, if that is what users expect when `creaseAngle` is specified.

/ping @donmccurdy 
/ping @Glinkis

**Comment by donmccurdy** [comment]
I don't know much about the VRML spec, but for what it's worth the glTF specification says `When normals are not specified, client implementations should calculate flat normals.`. That's as simple as setting `material.flatShading=true` for us, but conceptually it doesn't feel so different from calling `.computeVertexNormals()`. Mainly it is a question of (a) whether VRML specifies any such behavior when normals are omitted, and if not, (b) whether other VRML renderers have consistent behavior we should imitate.

**Comment by Glinkis** [comment]
If normals exist, they should be imported.
If they don't, it should fall back to creaseAngle.
And lastly, if neither exist it can simply call `computeVertexNormals()`.

**Comment by Mugen87** [comment]
If you think it's worth, why not?

**Comment by WestLangley** [comment]
You can support instancing if you want, but instanced buffer geometry is not the way to do it.

Personally, I would wait until there is demand for it, but it is up to you.

**Comment by mrdoob** [comment]
Our current support for instanced geometry is very basic. You still need to build you own materials...

**Comment by Glinkis** [comment]
Me my colleague have been trying to implement crease angle support for a while now, but putting this logic in VRMLLoader seems kind of pointless, as it would be way better to just have a `computeVertexNormals( creaseAngle );`method in `BufferGeometry`.

The loader could then just call this method and be done with it.
It would also allow similar things in other loaders without a bunch of duplicate logic.
