### ISSUE TITLE
Documentation: Broken link in InstancedBufferGeometry doc page

### ISSUE THREAD

**Issue by lhogho** [mrdoob/three.js#14819]
##### Description of the problem

The bottom of the doc page of [InstancedBufferGeometry](https://threejs.org/docs/index.html#api/en/core/InstancedBufferGeometry) has a link to the source [src/en/core/InstancedBufferGeometry.js](https://github.com/mrdoob/three.js/blob/master/src/en/core/InstancedBufferGeometry.js) which is broken.

##### Three.js version

- [x] r96

##### Browser

- [x] Opera
- [x] Chrome
- [x] and maybe all others

##### OS

- [x] All of them

![untitled](https://user-images.githubusercontent.com/20371270/44948837-b9df9880-ae2d-11e8-9368-50cb98e9345d.png)

»(◕‸◕)«

**Comment by fordhurley** [comment]
I believe this is the case for all links to source from the docs. Not seeing another issue for it, but it was mentioned here: https://github.com/mrdoob/three.js/pull/14750#issuecomment-417635324
