### ISSUE TITLE
distance = 0 mean infinity is wrong for physically correct lights

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#14811]
##### Description of the problem

With `physicallyCorrectLighting = true` setting `distance` to 0 on a pointlight is supposed to mean `infinity` but that's not what actually happens

http://jsfiddle.net/greggman/c0xht34n/

move the distance slider to 0 and suddenly the scene is blown out but a physically based light would not do that.

##### Three.js version

- [X] Dev
- [X] r96

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by mrdoob** [comment]
What do you think @bhouston?
