### ISSUE TITLE
Editor: Deleting node while dragging breaks viewport

### ISSUE THREAD

**Issue by mqp** [mrdoob/three.js#14810]
1. Load any scene in the editor, e.g. the examples will do fine.
2. Use the left mouse button to select an object.
3. Left-click and hold one of the square transform gizmos that let you move the object on two axes.
4. While holding LMB, press Backspace to delete the selected node.
5. Observe that you can no longer move the viewport camera with the left and right mouse buttons.

You can restore the camera functionality by selecting another object and then unselecting it. Clearly something about the "is an object currently selected" state got broken in step 4.

Tested in Chrome stable 68.0.3440.106 and Firefox nightly 63.0a1 on Ubuntu.

##### Three.js version

- [ ] Dev
- [x] r96
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I can confirm this behavior on Chrome 68.0.3440.106 and macOS (10.13.6).
