### ISSUE TITLE
WebXR: XRSession.depthNear/depthFar are not set

### ISSUE THREAD

**Issue by enh6** [mrdoob/three.js#14829]
XRSession.depthNear/depthFar are not set according to camera.near/far. The default value may cause some clipping issues. 

##### Three.js version

- [x] Dev
- [ ] r96
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Oh, true. Would you like to do a Pull Request with the fix?

**Comment by chadkittilstved** [comment]
His
