### ISSUE TITLE
"'GL_OES_standard_derivatives' : extension is not supported" after context lost/restored in Safari

### ISSUE THREAD

**Issue by nraynaud** [mrdoob/three.js#14830]
When forcing a context lost then restore in Safari 11.1.2, I get an error "'GL_OES_standard_derivatives' : extension is not supported" when the renderer tries to compile the shader, I see with the debugger that the JS code actually passes on the function that loads the extension.

http://jsfiddle.net/0syfbot1/2/

##### Three.js version

- [ ] Dev
- [x] r96
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware
MacBook Pro

Intel Iris Pro 1536 Mo

**Comment by mrdoob** [comment]
If you can only reproduce this on Safari 11.1.2 is likely a browser issue.
Would you like to report it directly to Apple?

**Comment by nraynaud** [comment]
I was hoping to have someone else have an expert look at it first, it's been a couple of years I have not done any webgl.

**Comment by mrdoob** [comment]
We have our plates a bit full already... Would be great if you could help us by reporting the issue to Apple.

**Comment by nraynaud** [comment]
I did report it there: https://bugreport.apple.com/web/?problemID=44072111

**Comment by mrdoob** [comment]
Thank you!
