### ISSUE TITLE
box3.intersectsPlane bug

### ISSUE THREAD

**Issue by shyf1301** [mrdoob/three.js#14834]
In the following example, the plane obviously intersects with the box, but the function intersectsPlane returns false.
[example](https://jsfiddle.net/rn6jzdub/4/)
I find that adding two negative sign before both of the plane.constant can fix the bug.
https://github.com/mrdoob/three.js/blob/c570b9bd95cf94829715b2cd3a8b128e37768a9c/src/math/Box3.js#L387
Also, I think the definition of the constant of the plane is not distinct, which cause the bug.

##### Three.js version

- [x] Dev
- [x] r96
- [x] ...

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by WestLangley** [comment]
@Mugen87 Something is wrong, then. Can you please figure out why your unit test did not catch this. #7445

**Comment by Mugen87** [comment]
The test was wrong, too.
