### ISSUE TITLE
VRMLLoader fails if there are comments in the file.

### ISSUE THREAD

**Issue by Glinkis** [mrdoob/three.js#14837]
I have a VRML file that I have exported from Rhino, a CAD software. And it seems that rhino adds comments in the generated file, which results in an error when I try to import the file with `VRMLLoader`.

`THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values. `

This is VRML file. (the code is folded for readability)
<img width="347" alt="screen shot 2018-09-03 at 16 42 41" src="https://user-images.githubusercontent.com/8037927/44992721-65a4f780-af98-11e8-993e-6375b771a8cc.png">

**Comment by Mugen87** [comment]
Can you please share the entire file for testing?

**Comment by Glinkis** [comment]
Ah, yes. Here it is.
[test3.wrl.zip](https://github.com/mrdoob/three.js/files/2345937/test3.wrl.zip)

**Comment by donmccurdy** [comment]
Since it seems like you've found multiple issues with the Rhino -> VRML workflow, you may want to try https://github.com/mcneel/glTF-Rhino.
