### ISSUE TITLE
Geometry's fromBufferGeometry() should clean vertices and colors

### ISSUE THREAD

**Issue by pixue** [mrdoob/three.js#14857]
Geometry's fromBufferGeometry() exports duplicated vertices and colors.

Code to reproduce:

```
var box = new THREE.BoxGeometry(1,1,1);
var bufferBox = new THREE.BufferGeometry();
bufferBox.fromGeometry(box);

var newBox = new THREE.Geometry();
newBox.fromBufferGeometry(bufferBox);
```
Result:
box : {vertices: Array(8), colors: Array(0)}
newBox : {vertices: Array(36), colors: Array(36)}

If you see useful, we have written a basic method to remove the vertices and fix the vertex index in the faces:
```
function clearDuplicateVertices(geometry) {
        //store the vertex index changes
        var data = [];
        var vertices = [];
        var faces = [];

        //vertices
        for (var v = 0; v < geometry.vertices.length; v++) {
            var vertex = geometry.vertices[v];

            //see if we have that vertex already
            var newIndex = -1;
            for (var i = 0; i < vertices.length; i++) {
                if (vertices[i].equals(vertex))
                {
                    newIndex = i;
                    break;
                }
            }

            if (newIndex > -1)
            {
                data.push({oldIndex: v, newIndex: newIndex});
            } else
            {
                vertices.push(vertex);
                data.push({oldIndex: v, newIndex: vertices.length - 1});
            }
        }

        //faces
        for (var f = 0; f < geometry.faces.length; f++) {
            var currentFace = geometry.faces[f];

            var a = currentFace.a;
            var b = currentFace.b;
            var c = currentFace.c;
            for (var i = 0; i < data.length; i++) {
                var currentData = data[i];

                if (a === currentData.oldIndex) {
                    a = currentData.newIndex;
                }

                if (b === currentData.oldIndex) {
                    b = currentData.newIndex;
                }

                if (c === currentData.oldIndex) {
                    c = currentData.newIndex;
                }
            }
            faces.push(new THREE.Face3(a, b, c));
        }

        //copy
        var geo = new THREE.Geometry();
        geo.vertices = vertices;
        geo.faces = faces;
        geo.computeFaceNormals();
        return geo;
    }
```
##### Three.js version
- [x] r96

**Comment by ieskudero** [comment]
I think that what @pixue wants to say is that you can avoid duplicated vertices when converting from BufferGeometry to Geometry. Maybe the function `geometry.fromBufferGeometry()` should do `mergeVertices()` before returning the result. Otherwise you will end having duplicated vertices most of the time.

**Comment by Mugen87** [comment]
> Maybe the function geometry.fromBufferGeometry() should do mergeVertices() before returning the result. 

`BufferGeometry` does not have a method `.mergeVertices()`. And I think the usage of `mergeVertices()` makes only sense for an indexed geometry.

**Comment by Mugen87** [comment]
Ah, I see. Yes, a call of `Geometry.mergeVertices()` after the following line can't hurt.

https://github.com/mrdoob/three.js/blob/cc06e7cbc2237b07f8a0cb59511037841c3877a2/src/core/Geometry.js#L337-L338

@ieskudero Would you like to do a PR with the change?

**Comment by ieskudero** [comment]
Ok, done, I think, this is the first time contributing to a project like this. Can you check if it is right, please?

**Comment by WestLangley** [comment]
I am not sure calling  `mergeVertices()` is a good idea. Think about the impact that will have on existing users. 

Users can always call `mergeVertices()` themselves if that is what they want. Also, `mergeVertices()` has a hard-wired precision parameter.

>Yes, a call of Geometry.mergeVertices() after the following line can't hurt.

If you insist on doing it anyway, I would call it _prior_ to computing face normals, not after.

**Comment by Mugen87** [comment]
>  I would call it prior to computing face normals, not after.

That's a good idea.

**Comment by WestLangley** [comment]
>I would call it prior to computing face normals, not after.
>>I'm not sure I understand the difference in this.

Face normals are computed _from_ the vertices.

However, I would not call `mergeVertices()` in this method. We should not be modifying the user's vertex data behind the back of the user. Furthermore, vertex perturbations can have a significant impact on models defined on a small scale.

**Comment by mrdoob** [comment]
I don't think we should change `Geometry` at this point.
We should, instead, focus on how to move away from it.

**Comment by ieskudero** [comment]
@WestLangley, @mrdoob I understand what you are saying, but maybe you can put a comment in the documentation of the function `fromBufferGeometry()`, so people who doesn´t know about it can do `mergeVertices()` by themselves, because I don´t think people is aware of this duplication.

**Comment by mrdoob** [comment]
Sounds good. Would you like to do a PR with the documentation improvement?

**Comment by ieskudero** [comment]
OK, I will give it a try.

**Comment by Mugen87** [comment]
Okay, I'm fine with this decision.

> Face normals are computed from the vertices.

That's correct. But even if you compute face normals before merging, there should be no visible difference in the result. And the computation is not more expensive.
