### ISSUE TITLE
Smart camera parameters

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#14858]
##### Description of the problem
Smart camera parameters to optimize depth accuracy.
We often see z-fighting issue(rendering is flicking) for many models if camera NEAR-FAR range is not minimum (minimum to cover all geometry)
When using OrbitControl or other controls or camera animation, this NEAR-FAR range should be dynamically updated to avoid rendering issue.
##### Three.js version

- [ x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by WestLangley** [comment]
It is the user's responsibility to avoid small values of the near plane.

Are you not able to to do that for some reason?

**Comment by Mugen87** [comment]
> NEAR-FAR range should be dynamically updated to avoid rendering issue.

I've never seen that a 3D or game engine does this. Can you name an example if possible?

**Comment by whatisor** [comment]
I just think it is an enhancement for the dynamic(moving) camera.
Camera need to understand situation of scene to udpate NEAR plane with optimal value, not by human manually.
As a result, render always render with the best accuracy.

**Comment by Usnul** [comment]
> I've never seen that a 3D or game engine does this. Can you name an example if possible?

@Mugen87 
My engine does that :)

I'm not very sure if that's a good idea overall or not, as you end up with a bit of flickering when clipping planes are adjusted. For me the results have been great so far, but your mileage may vary.

I do a search query on scene BVH to determine depth clipping planes before rendering takes place.

**Comment by Mugen87** [comment]
@Usnul It would be interesting for @whatisor if you can share a link to your code :+1:  

@whatisor You can also have a look at certain model viewers. They also perform such an adjustment based on the size of the models bounding box:

https://github.com/donmccurdy/three-gltf-viewer/blob/f9a7accd380ed2eaa64b6debaa56510246bf06dc/src/viewer.js#L228-L229

**Comment by whatisor** [comment]
Thank @Usnul, in fact, I am considering if we ought to make it as renderer feature to make it work in the best accuracy with any camera parameters and scene.
Just a suggestion! :)

**Comment by Mugen87** [comment]
https://github.com/mrdoob/three.js/issues/14858#issuecomment-419310318

Closing, as @WestLangley said this needs to be implemented in the app layer.
