### ISSUE TITLE
Docs links invalid

### ISSUE THREAD

**Issue by modulesio** [mrdoob/three.js#14850]
The docs pages for classes e.g. https://threejs.org/docs/#api/en/math/Matrix4 point to pages like https://github.com/mrdoob/three.js/blob/master/src/en/math/Matrix4.js.

That is not a valid path afaict (note the `/en`).

<img width="516" alt="capture3" src="https://user-images.githubusercontent.com/6926057/45065356-b7c44680-b086-11e8-9a33-b641be9d345a.PNG">

**Comment by mrdoob** [comment]
#14819
