### ISSUE TITLE
Add WebVR section to the documentation

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#14860]
##### Description of the problem

Right now we don't have "WebVR contents creation" section in the document. (Let me know if I'm missing.) Then users who wanna create WebVR contents need to pick up necessary info from `WebGLRenderer` doc and `WebVR` examples.

I think having WebVR section in the document is very useful to such users. (Actually I had missed I must use `renderer.setAnimationLoop` so I spent so long time to fix.)

##### Three.js version

- [x] Dev
- [ ] r96
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Sounds good to me 👌

**Comment by soadzoor** [comment]
+1, A while ago, it also gave me a headache, to figure out why my renderer doesn't work in VR mode. Then I saw the `renderer.setAnimationLoop` in one of the examples.

**Comment by takahirox** [comment]
Closing in favor of #14904
