### ISSUE TITLE
Raycaster no longer works with Sprites using CanvasRenderer

### ISSUE THREAD

**Issue by wwbbluesky** [mrdoob/three.js#14868]
three.js  version more than 0.93, Raycaster Method no use to Sprite.

**Comment by Mugen87** [comment]
Please add some more details to you report. It would be great if you can demonstrate the issue in a [live](https://jsfiddle.net/f2Lommf5/), too.

**Comment by wwbbluesky** [comment]
Thank for your feedback very much. I had test the three api versions (0.94, 0.95,0.96), Raycaster is not work on Sprite.
In this example , the web address  is   'https://threejs.org/examples/?q=int#canvas_interactive_particles', the bug can show. Thank for you help very much. Wait for your feed back!

**Comment by wwbbluesky** [comment]
Raycaster no longer works with Sprites using CanvasRenderer and WebGLRenderer.

**Comment by mrdoob** [comment]
I don't think that's true. This example uses WebGLRenderer and works:
https://threejs.org/examples/webgl_raycast_sprite.html

**Comment by wwbbluesky** [comment]
I test this example "https://threejs.org/examples/webgl_raycast_sprite.html".  If I change the code:

function getIntersects( x, y ) {

			x = ( x / window.innerWidth ) * 2 - 1;
			y = - ( y / window.innerHeight ) * 2 + 1;

			mouseVector.set( x, y, 0.5 );
			raycaster.setFromCamera( mouseVector, camera );
                     

      1.       return raycaster.intersectObject(scene.children, true);   //  It is  not work,  the bug detail is '
Uncaught TypeError: object.raycast is not a function
    at intersectObject (three.js:43271)
    at Raycaster.intersectObject (three.js:43323)
    at getIntersects ((index):162)
    at onDocumentMouseMove ((index):131)   '

			return raycaster.intersectObject( group, true );  // It is ok!

		}

But in the api introduction "https://threejs.org/docs/index.html#api/en/core/Raycaster"  , it says :
var intersects = raycaster.intersectObjects( scene.children ). 
 is it  the method 'raycaster.intersectObjects'  have change?

**Comment by Mugen87** [comment]
Um, I guess this bug was introduced via #14292

At least on problem is that `SpriteCanvasMaterial` does not have a `rotation` property. So `cos` and `sin` become `NaN` values in the following code section:

https://github.com/mrdoob/three.js/blob/d1ba0bcc88a3f81e191eb3b6d5ed9f1c1ea7fb57/src/objects/Sprite.js#L107-L114

/cc @06wj

**Comment by 06wj** [comment]
My fault, I will make a PR to fix it.
