### ISSUE TITLE
How to Write More text in defferent location

### ISSUE THREAD

**Issue by yankai12** [mrdoob/three.js#14867]
##### Description of the problem

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/3foLr7sn/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/qgu17w5o/) (dev branch)
* [codepen](https://codepen.io/anon/pen/aEBKxR) (latest release branch)
* [codepen](https://codepen.io/anon/pen/BJWzaN) (dev branch)

##### Three.js version

- [ ] June
- [ ] r96
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by yankai12** [comment]
var pos=GetMouseLonLat(event);
                fontloader.load('../Lib/fonts/FZShuTi_Regular.json',function (font) {
                    var text='111111';
                    var g=new THREE.TextGeometry(text,{
                        font:font,
                        height : 20,
                        size :70,
                        hover: 30,
                        curveSegments :4,
                        bevelThickness : 2,
                        bevelSize : 1.5,
                        bevelSegments : 3,
                        bevelEnabled :true,
                        // font = undefined,
                    });
                    g.computeBoundingBox();
                    var m = new THREE.PointsMaterial({color:0xff0000, flatShading: THREE.FlatShading});
                    var mesh = new THREE.Mesh(g,m);
                    let position1 =  Coordinate.sphericalToCartesian(pos.lon,pos.lat);
                    let p3 = new Vector3( position1.x,position1.y,position1.z);
                    mesh.position.set(p3.x,p3.y,p3.z);
                    scene_dy.add(mesh);
this is my code ,it can draw more text,but it also draws a sphere

**Comment by yankai12** [comment]
![_20180906140430](https://user-images.githubusercontent.com/31153968/45138080-cb35f580-b1dd-11e8-97a2-0f57324f8aa5.png)

**Comment by WestLangley** [comment]
Sorry, this is not a help site. Please use the [forum](https://discourse.threejs.org/) for help questions.
