### ISSUE TITLE
Bone property for rigging

### ISSUE THREAD

**Issue by tiancaipipi110** [mrdoob/three.js#14887]
Say I have two bones: Bone_0, Bone_1. I would like to create 6 GUI controls to control position on x, y, z and rotation on x,y,z for Bone_0, same for Bone_1.         
I've assigned    `child.skeleton.bones[0].position.y = guiControls.Bone_0;`   Then what should I assign `child.skeleton.bones[0].position.z`    to ? I wasn't able to find the 'Bone_0' properties.
```
 ////GUI
        guiControls = new function () {
            this.Bone_0 = 0.0;
            this.Bone_1 = 0.0;
        }

        datGUI = new dat.GUI();
        //datGUI.add(guiControls, "scene");
        var folder = datGUI.addFolder('Controls');

        folder.add(guiControls, 'Bone_0', -3.14, 3.14);
        folder.add(guiControls, 'Bone_0', -3.14, 3.14);

        folder.add(guiControls, 'Bone_1', -3.14, 3.14);
        folder.add(guiControls, 'Bone_1', -3.14, 3.14);



 scene.traverse(function (child) {
            if (child instanceof THREE.SkinnedMesh) {

                child.position.y += .01;

                child.skeleton.bones[0].position.y = guiControls.Bone_0;
                child.skeleton.bones[0].rotation.y = guiControls.Bone_0;

                child.skeleton.bones[1].position.y = guiControls.Bone_1;
                child.skeleton.bones[1].rotation.y = guiControls.Bone_1;

            }
        });
```

**Comment by tiancaipipi110** [comment]
[simple.txt](https://github.com/mrdoob/three.js/files/2364452/simple.txt)

**Comment by WestLangley** [comment]
Please, use the [forum](https://discourse.threejs.org/) for help. We use GitHub issues for bug reports and feature requests only.

**Comment by tiancaipipi110** [comment]
This is a feature request, the property is not included and documented in the library.
