### ISSUE TITLE
Strange color in piz-compressed exr envMap

### ISSUE THREAD

**Issue by zhutq** [mrdoob/three.js#14893]
##### Description of the problem

I’m using equirectangular exr envMaps. But when the exr is piz-compressed, there’s a strange green-blue area on the map, which does not exist if the exr is not compressed. (The two exr's look the same with exrdisplay and there’s nothing strange on the piz-comporessed one.) It especially affects smooth metal materials.

Piz compressed: https://jsfiddle.net/qgu17w5o/172/
![screenshot from 2018-09-10 17-40-53](https://user-images.githubusercontent.com/1166360/45301728-19335c00-b544-11e8-8213-bb4dd35a4b64.png)
Not compressed:  https://jsfiddle.net/qgu17w5o/171/ 
![screenshot from 2018-09-10 17-42-19](https://user-images.githubusercontent.com/1166360/45301730-1cc6e300-b544-11e8-9218-4cb4ae26b459.png)

##### Three.js version

- [x] Dev
- [ ] r96
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by richardmonette** [comment]
If you try the same thing with a different set of un/compressed EXRs, is the pattern of the decompression artifacts exactly the same?

**Comment by zhutq** [comment]
I experimented with several other EXRs.
Only some of them have the same issue.
Another set:
Piz compressed:
![screenshot from 2018-09-11 10-01-40](https://user-images.githubusercontent.com/1166360/45333745-49ade100-b5aa-11e8-9554-ca9a42afc422.png)
![screenshot from 2018-09-11 10-02-43](https://user-images.githubusercontent.com/1166360/45333751-4ca8d180-b5aa-11e8-967f-071fb80935d3.png)

Not compressed:
![screenshot from 2018-09-11 10-02-03](https://user-images.githubusercontent.com/1166360/45333757-54687600-b5aa-11e8-9b93-d0dda23cb6ce.png)
![screenshot from 2018-09-11 10-04-03](https://user-images.githubusercontent.com/1166360/45333762-58949380-b5aa-11e8-9cf5-db660b4dd244.png)

**Comment by Mugen87** [comment]
It seems this is still an issue with the latest `EXRLoader`:

https://jsfiddle.net/q6b85wg9/

**Comment by WestLangley** [comment]
/ping @sciecode Wild guess...  does the loader assume the image height is a power-of-two?

**Comment by sciecode** [comment]
Loader makes no assumption of the image data at all. 
I believe this is likely a bug on the PIZ decompression algorithm itself.
