### ISSUE TITLE
FeatureRequest: Is it possible to add isClassName everywhere ?

### ISSUE THREAD

**Issue by Itee** [mrdoob/three.js#14898]
This is a feature request.

Currently many class in threejs have included an isClassName property to performance reason, mainly in Renderer.

Is it possible to consider this as a global pattern for all threejs class and allow fast type checking ?

**Comment by Mugen87** [comment]
I would say, yes.

**Comment by mrdoob** [comment]
I think I would prefer adding these when someone needs them...

**Comment by Itee** [comment]
You cannot project where or when developer will need this feature. This allow to replace the ``foo instanceof Bar`` statement in favor of fast boolean check.

But maybe this pattern is only useful where inheritance take place ? Where an instanceof check could be perform ?

Would you that i find just class like this. That will reduce the amount of change in this PR, and allow this pattern only in usable places.
