### ISSUE TITLE
Scaling snap for the Transform Controls

### ISSUE THREAD

**Issue by rromanchenko** [mrdoob/three.js#14902]
Hello guys,

I wonder, if it's possible to consider some 'scaling snap' value while using "scale" mode for the "Transform Controls"? The expectation here is to snap "endpoint" while scaling.

Thanks.

**Comment by arodic** [comment]
It should be possible. I'll be adding this feature in TransformControls v3. It is another major overhaul so I can't give an ETA yet.

In the meantime, if you are willing to give it a go, scale transformations are applied [here](https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/TransformControls.js#L420).

You should simply define new property `scaleSnap` and apply it in similar fashion like its implemented per-axis in positionSnap [here](https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/TransformControls.js#L372)

**Comment by rromanchenko** [comment]
Thank you, arodic.
I close this ticket.

**Comment by gizm0bill** [comment]
should be pretty easy, something like: 
```js
  if ( this.scaleSnap ) // for all axes
    _tempVector2.divideScalar( this.scaleSnap ).round().multiplyScalar( this.scaleSnap ) 
```

**Comment by arodic** [comment]
@rromanchenko @gizm0bill I added scaleSnap in #18146.

**Comment by akoniuk-amc** [comment]
Thanks, guys!

**Comment by rromanchenko** [comment]
Thanks, guys!

**Comment by gizm0bill** [comment]
Thanks but I think yours and my solution would be relative to current scale?
Also maybe I could rewrite these controls to make them more extendable (right now there are a lot of conditionals in the logic) and also expose the gizmos, what do you think?

**Comment by arodic** [comment]
> Thanks but I think yours and my solution would be relative to current scale?

My implementation is applied to absolute scale in local space.

> Also maybe I could rewrite these controls to make them more extendable

Sure why not. I started working on a completely [new version](https://github.com/arodic/three.js-controls) about a year ago but got distracted by other work.

I will continue to support this control with minor feature requests and bug fixes. But for anything beyond that I think it makes a lot more sense to start from scratch.
