### ISSUE TITLE
FeatureRequest: Is it possible to add type everywhere ?

### ISSUE THREAD

**Issue by Itee** [mrdoob/three.js#14900]
This is a feature request.

Currently many class in threejs have their own implementation of type = "ClassName"

Is it possible to consider this as a global pattern for all threejs class ?

**Comment by Mugen87** [comment]
AFAIK, `type` is only considered for serialization/deserialization. If a class is no part of the serialization/deserialization process, the `type` property is superfluous.

**Comment by Itee** [comment]
About this [comment](https://github.com/mrdoob/three.js/pull/14901#issuecomment-420632851) the implementation of type property is (i think) missing in lot of serialisable class.

Should it be interesting to inherit an "serializable interface" with type, toJson and fromJson ?

**Comment by Mugen87** [comment]
Related #11266

**Comment by Itee** [comment]
I'm aware of it, thanks.

**Comment by Mugen87** [comment]
How about closing this issue and proceed the discussion in #11266?
