### ISSUE TITLE
NodeMaterial: Instancing API

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#14919]
I believe NodeMaterial could support an expressive instancing API, without requiring users to modify builtin shaders. The [instancing • lambert](https://github.com/mrdoob/three.js/blob/master/examples/webgl_buffergeometry_instancing_lambert.html) example shows the simplest pre-existing approach, and is still complex enough that users will find it challenging to instance a 3D model created in a DCC tool.

Proposal:

```js
import * as THREE from 'three';
import {
  StandardNodeMaterial,
  InstanceTransformNode,
  AttributeNode,
  FloatNode,
  OperatorNode,
  TextureNode
} from 'three/js/nodes/THREE.Nodes';

var material = new StandardNodeMaterial();

// Configure shared material properties as usual.
material.metalness = new FloatNode( 0 );

// Configure material.instanceTransform to reference 1-3 InstancedBufferAttribute nodes.
material.instanceTransform = THREE.InstanceTransformNode(
  new AttributeNode( 'instancePosition', 'vec3' ),
  new AttributeNode( 'instanceQuaternion', 'vec4' ),
  new AttributeNode( 'instanceScale', 'vec3' )
);

// Configure per-instance material properties using node expressions and InstancedBufferAttribute.
material.roughness = new AttributeNode( 'instanceRoughness' );
material.color = new OperatorNode(
  new TextureNode( baseColorTexture ),
  new AttributeNode( 'instanceColor' ),
  OperatorNode.MUL
);
```

With this API, and as loaders enable the NodeMaterial system, instancing models created in DCC tools becomes much easier:

```js
var treePositions = new Float32Array(  [
  0, 0, 0,
  10, 0, 0,
  20, 0, 0
] );

var loader = new THREE.GLTFLoader();
loader
  .setUseNodes( true )
  .load( 'tree.glb', ( gltf ) => {
    var model = gltf.scene.children[ 0 ];

    model.geometry = new THREE.InstancedBufferGeometry().fromBufferGeometry( model.geometry );
    model.geometry.addAttribute( 'instancePosition', new THREE.InstancedBufferAttribute( treePositions, 3 );
    model.material.instanceTransfom = new THREE.InstanceTransformNode( THREE.AttributeNode( 'instancePosition' ) );

    scene.add( model );
  } );
```

This idea is based loosely on noticing recently that Unity [plans to add instancing support to its Shader Graph master nodes](https://forum.unity.com/threads/feedback-wanted-shader-graph.511960/page-3#post-3354433).

/cc @sunag

**Comment by sunag** [comment]
A few months ago I have been thinking of adding particles support in `NodeMaterial` basead in `instancing • lambert`. I have some requests on the `SEA3D` forum about support for `Sparticle` in `Three.JS` on `SEA3D` had it in `Away3D`. http://community.poonya.com/110 http://community.poonya.com/183

I was thinking of something like:
```javascript
material.position = new AttributeNode( 'instanceMatrix', 'm4' );
```
or maybe more closer to your idea:
```javascript
material.position = new ComposeNode(
    new AttributeNode( 'instancePosition', 'vec3' ),
    new AttributeNode( 'instanceQuaternion', 'vec4' ),
    new AttributeNode( 'instanceScale', 'vec3' )
);
```
I think we can use `position` `slot` for this.
I am not sure but I think that the term `Instance..Node` is not necessary.

> material.roughness = new AttributeNode( 'instanceRoughness' );

I had not thought of that. It looks great.

Thanks for sharing... inevitably this is a way forward.

**Comment by sunag** [comment]
I can make an example as soon as possible.

**Comment by donmccurdy** [comment]
I like your suggestion of using `material.position` rather than a new socket. 👍

Possibly related: while trying to test this I've run into a bug where a varying and a temp variable are colliding on names:

![screen shot 2019-01-28 at 11 36 54 pm](https://user-images.githubusercontent.com/1848368/51892127-ca9d2780-2355-11e9-9aa1-7c04ed606a28.png)

Steps to reproduce this are a bit complicated at the moment, I'll share something when I can. Meanwhile I hacked around it with a prefix in `NodeBuilder.getTempVar()`.

**Comment by donmccurdy** [comment]
^Moved this question to a new issue: https://github.com/mrdoob/three.js/issues/15666

**Comment by donmccurdy** [comment]
This is working quite nicely now that #15666 is fixed. Doesn't seem like a new `InstanceTransformNode` API is necessary. 😎
