### ISSUE TITLE
Raycaster.setFromCamera is incorrect for back half of OrthographicCamera frustum.

### ISSUE THREAD

**Issue by arodic** [mrdoob/three.js#14916]
It appears to be failing [here](https://github.com/mrdoob/three.js/blame/dev/src/core/Raycaster.js#L85)

Correct calculation, to start the ray from back of the frustum I think should be:

```javascript
this.ray.origin.set( coords.x, coords.y, camera.near / ( camera.near - camera.far ) ).unproject( camera ); 
```

Notice the sphere position is not updated in back half of the frustum in live example:

* [jsfiddle](https://jsfiddle.net/wmbyhgxr/) (dev branch)

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by WestLangley** [comment]
Your near plane value is negative. See the [docs](https://threejs.org/docs/#api/en/cameras/OrthographicCamera.near).

Also have a look at [this SO answer](https://stackoverflow.com/a/17567292/1461008). I assume your world-space units are not pixels.

**Comment by arodic** [comment]
@WestLangley is negative near plane restricted by design for some reason or is this a bug? Afaik, negative near plane should be just fine and projected output looks alright in the canvas.

**Comment by arodic** [comment]
I understand that negative near plane makes no sense with perspective projection, but orthographic is entirely different geometry and as far as I can tell OpenGL, and most tools I've used have no problem with negative near plane.

**Comment by Mugen87** [comment]
@arodic What is your use case for a negative near plane?

**Comment by arodic** [comment]
Mugen87 right now I used negative plane for convenience. For example if I wanted to rotate OrthographicCamera around a point and see entire scene, I could simply put the camera there, set near/far to encompass the scene and rotate (no target/lookAt required).

However, I think this boils down do how we think about cameras. Perspective camera is kind of like a real world camera. Its projection geometry is a frustum and it shoots things in front of its center.

Orthographic camera, on the other hand, has a cuboid projection geometry and restricting it to front of the camera center seems arbitrary. Moreover, threejs examples use negative near plane and rendering a scene with negative near plane results with a perfectly fine and expected result..

**Comment by WestLangley** [comment]
The three.js examples should not be using a negative near plane. Rendering objects that are behind the camera can be confusing to users and can cause objects to be back-lit. Raycasting from the near clipping plane when the near clipping plane is behind the camera will result in the returned distance to the the intersected object being incorrect.
