### ISSUE TITLE
How to solve one complex mesh transparent is not rendered correctly problem?

### ISSUE THREAD

**Issue by HypnosNova** [mrdoob/three.js#14925]
![image](https://user-images.githubusercontent.com/7953802/45604161-490ec200-ba64-11e8-823d-fc20816319b0.png)
looks like the screenshot on official document demo.
Just one mesh but the geometry is very complex. If I set the transparent and opacity, some part of the mesh is no rendered correct. And depthSet and depthWrite cannot solve it.
Is there any way to solve the problem?

**Comment by WestLangley** [comment]
We prefer you use the [forum](https://discourse.threejs.org) or stackoverflow for help.

See [this SO answer](https://stackoverflow.com/a/13236863/1461008) for one workaround.
