### ISSUE TITLE
Effect of image sharpness

### ISSUE THREAD

**Issue by 836257514** [mrdoob/three.js#14928]
Is there any way, I can adjust the image's sharpness?
After I do some research on bing, I find the below link by webgl, but don't know how to implement it in three.js.
https://webglfundamentals.org/webgl/lessons/webgl-image-processing-continued.html

Anyone can help me?

**Comment by Mugen87** [comment]
Please use stackoverflow or the [forum](https://discourse.threejs.org) for help requests.
