### ISSUE TITLE
Object3D.lookAt question

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#14930]
Not sure if (or why) is this supposed to be like that, but Object3D.lookAt is currently long-ass code that does not work within hierarchy, and it even says so in the [docs](https://threejs.org/docs/#api/en/core/Object3D.lookAt):
> This method does not support objects with rotated and/or translated parent(s).

What am I currently using instead of `mesh.lookAt (target)` is these 2 lines:
```javascript
				matrix4.lookAt (mesh.position, target, up);
  				mesh.quaternion.setFromRotationMatrix (matrix4);
```
I have `target` in local space, and could not care less where does `up` point to, so it works for me. However, even if I had to use world space and specific `up`, it would add at most couple of lines to convert them into local space and we're back to this simple code.

With that in mind, I'd like to know what is the reason behind current Object3D.lookAt version?

**Comment by WestLangley** [comment]
`lookAt()`orients the object so its local, positive z-axis points in the direction of the target, and its local x-axis is orthogonal to the world-space `up` direction. (For example, if the object were an airplane, its wings would remain level.)

Rotated parents are now supported; non-uniformly-scaled parents are not.

The docs, by the way, are outdated.

**Comment by makc** [comment]
> Rotated parents are now supported

I wonder why I couldn't get it to work then. Very well, I am closing this since I don't have a fiddle to back it up.

**Comment by backspaces** [comment]
Is this still the case?
> lookAt() orients the object so its local, positive z-axis points in the direction of the target, and its local x-axis is orthogonal to the world-space up direction. (For example, if the object were an airplane, its wings would remain level.)

.. I need to point the positive x-axis at the target.

**Comment by mrdoob** [comment]
Please, use the [forum](https://discourse.threejs.org/) or the [chat](https://discord.gg/HF4UdyF) for help.
