### ISSUE TITLE
Is it possible to let Fog interact with the material's opacity?

### ISSUE THREAD

**Issue by YingcaiDong** [mrdoob/three.js#14944]
##### Three.js version
- [x] r95

##### Browser
- [x] All of them

##### OS
- [x] Windows

##### Feature description:
I am working on a project that displays buildings. The requirement is to let the building gradually fade out (transparent) based on the distance between the camera and the buildings. Also, this effect has to follow the camera's movement.

I consider using THREE.Fog(), but the Fog seems can only change the material's colour. 
![fog](https://user-images.githubusercontent.com/22902303/45820250-62a64880-bcb4-11e8-8f4c-11e1583e66fa.png)
The image above shows the building interact with the white fog. But is it possible to add fog interact with the material's opacity? For example, the solid white part can be totally transparent, while the nearer area can be semi-transparent.

**Comment by Mugen87** [comment]
Please use stackoverflow or the [forum](https://discourse.threejs.org/) for help requests.

https://stackoverflow.com/questions/52425575/is-it-possible-to-let-fog-interact-with-the-materials-opacity
