### ISSUE TITLE
Failed to load MTL

### ISSUE THREAD

**Issue by mjwise-hyx** [mrdoob/three.js#14947]
when i test the loader of obj-mtl ,it tell me that 
![image](https://user-images.githubusercontent.com/42193551/45856415-ef213b80-bd86-11e8-8eec-ea6f2176847c.png)

**Comment by Mugen87** [comment]
Please read the following guide in order to understand and solve your problem: https://threejs.org/docs/index.html#manual/en/introduction/How-to-run-things-locally
