### ISSUE TITLE
Rendering of semitransparent textures on renderTarget.

### ISSUE THREAD

**Issue by HoldenCa** [mrdoob/three.js#14959]
Semi transparent textures blends with black color when I render it to renderTarget.
And I don't see possibility of how to avoid this except to set no blending to semi transparent material, but it leads to another issue when I render two semi transparent objects that overplaps one another.

Expected behaviour: should exist possibility of rendering semi transparent textures into renderTarget without blending with black color.

**Comment by WestLangley** [comment]
If you are unable to resolve your issue, please post you question and your code on [the forum](https://discourse.threejs.org) or stackoverflow. If you are later able to confirm a three.js bug, you may reopen this.
