### ISSUE TITLE
Instanced Rendering with Collada model

### ISSUE THREAD

**Issue by xjindf** [mrdoob/three.js#14961]
var loader = new THREE.ColladaLoader();
loader.load('xx.dae', function(collada){
     var dae = collada.scene;
     var geometry = new THREE.InstancedBufferGeometry();
     geometry.attributes.position = bufferGeometry.attributes.position;
     geometry.attributes.color = bufferGeometry.attributes.color;
     geometry.attributes.normal = bufferGeometry.attributes.normal;
     geometry.attributes.uv= bufferGeometry.attributes.uv;

     var offsets=[];
     for(var i=0;i<10;i++){
          offsets.push(0,0,i*5);
    }
     geometry.addAttribute('instancePosition', new THREE.InstancedBufferAttribute(new Float32Array(offsets), 3));
                    
     var shaderMaterial = new THREE.ShaderMaterial({
              uniforms: {},
              vertexShader: document.getElementById('vertexShader').textContent,
              fragmentShader: document.getElementById('fragmentShader').textContent
     });
    var mesh = new THREE.Mesh(geometry, shaderMaterial);
   scene.add(mesh);
});

But the model I imported is multi-material, how can I combine it, I hope I can get help, thank you very much.

**Comment by Mugen87** [comment]
Please use stackoverflow of the [forum](https://discourse.threejs.org/) for help requests.
