### ISSUE TITLE
Object3D.onBeforeRender not triggered for Object3D and Group objects.

### ISSUE THREAD

**Issue by arodic** [mrdoob/three.js#14970]
##### Description of the problem

Right now, objects without geometry such as `Object3D`, `Group` and similar extended objects have `onBeforeRender()` method inherited from `Object3D`, but the method never gets triggered - probably by design since said objects are not renderable.

This issue is a feature request to make it possible to force execution of `onBeforeRender()` even if the object is not renderable. This could possibly be a solution for #14921 as well.

One possible but naive solution is to implement `.needsRender` property to tell renderer to trigger the method.

My current use case for this feature is to provide non-renderable objects a reference to the current camera (via `onBeforeRender()` argument) in order to transform it's renderable children based on camera direction and distance in an multi-viewport and multi-camera application environment where setting camera references externally would add unreasonable complexity to application code.

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by WestLangley** [comment]
If the feature you want is not implemented, perhaps you can hack it by using a renderable object with `colorWrite = false` and `depthWrite = false` in place of your `Group`. I realize that is not particularly appealing...

**Comment by Mugen87** [comment]
Closing in favor of #11306.

> Would colorWrite = false and depthWrite = false still produce a draw call?

Yes.
