### ISSUE TITLE
CompressedTexture S3TC - DXT5 bug when set as NormalMap

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#14984]
##### CompressedTexture S3TC - DXT5 bug when set as NormalMap

When the normalmap is set using a s3tc - dxt5 compressed texture it create artefact , see screenshot below :  

![bug_ktx](https://user-images.githubusercontent.com/213351/46163564-ce2b7f80-c28b-11e8-8973-af2454becc0d.jpg)

JSFiddle example (need a CORS allow origin * extension ) - comment/uncomment the different GLTF to see the render difference with all .ktx/ all .png / all .ktx except normal
https://jsfiddle.net/f15mL2su/39/ 

I read in different place DXT5 as normalmap need some special code in the shader : 
https://blogs.msdn.microsoft.com/shawnhar/2008/10/30/dxt-compression-for-normalmaps/
https://www.nvidia.com/object/real-time-normal-map-dxt-compression.html
https://www.garagegames.com/community/blogs/view/22776

I try to change the normal fragment and argb function but coudnt fixed it, help will be appreciate, thanks :)

##### Three.js version

- [x] Dev
- [x] r97

##### Browser

- [x] All of them on Desktop

##### OS

- [x] All of them on Desktop (S3tc / dxt5 is support on desktop only)
- [x] Windows
- [x] macOS
- [?] Linux

##### Hardware Requirements (graphics card, VR Device, ...)
support of S3TC extension is needed.

**Comment by Mugen87** [comment]
What happens when you use the code mentioned in https://discourse.threejs.org/t/orange-encoded-normal-map-support/3984/6?u=mugen87?
