### ISSUE TITLE
GLTFLoader : RangeError: Invalid typed array length: 24

### ISSUE THREAD

**Issue by Aarbel** [mrdoob/three.js#14993]
I've got this error deploying three.js viewer wrapper by React on Heroku.

The link : https://clovis-bim-viewer.herokuapp.com/

All works perfectly locally, or thru a local network on localhost or http://192.168.x.x

![image](https://user-images.githubusercontent.com/25119847/46247624-65b8db80-c40e-11e8-910c-64473bd5f34f.png)

![image](https://user-images.githubusercontent.com/25119847/46247612-2a1e1180-c40e-11e8-9251-6475d7d4926b.png)

Do you know a way to fix it ?

**Comment by Aarbel** [comment]
Ok issue solved.

Gltf loader expect a binary file next to the loadef gltf file.
So i added back the binary file and all is working great !

**Comment by 2016CS112** [comment]
@Aarbel How you load gltf  in GLTFLoader in react ?
