### ISSUE TITLE
Error loading models exported from Daz3D

### ISSUE THREAD

**Issue by ran-j** [mrdoob/three.js#14996]
I create a model in daz 3d, but when I export as a collada and try to load in three  js I got this error 

```
Uncaught RangeError: Maximum call stack size exceeded
    at SkinnedMesh.Mesh [as constructor] (three.min.js:14322)
    at new SkinnedMesh (three.min.js:25480)
    at buildObjects (ColladaLoader.js:3653)
    at buildNode (ColladaLoader.js:3467)
    at getBuild (ColladaLoader.js:219)
    at getNode (ColladaLoader.js:3680)
    at buildNode (ColladaLoader.js:3442)
    at getBuild (ColladaLoader.js:219)
    at getNode (ColladaLoader.js:3680)
    at buildSkeleton (ColladaLoader.js:3296)
```

My configs to export https://imgur.com/a/vCQmMCm

How Im loading 

```
var loadingManager = new THREE.LoadingManager(function () {
    scene.add(modelRender);
  });

  var loader = new THREE.ColladaLoader(loadingManager);
  loader.load('./src/models/e/Teste.dae', function (collada) {
    var animations = collada.animations;

    if (animations.length > 0) {
      var avatar = collada.scene;
      mixer = new THREE.AnimationMixer(avatar);
      var action = mixer.clipAction(animations[0]).play();
      modelRender = avatar
    } else {
      modelRender = collada.scene;
    }

  });
```

##### Three.js version

- [ ] Dev
- [ ] r97
- THREE.ColladaLoader: File version 1.4.1 || THREE.WebGLRenderer 96

##### Browser

- [] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

GTX 1060 
Core I5 4460
20 Ram

**Comment by mrdoob** [comment]
Could you share the model?

**Comment by Mugen87** [comment]
Your code looks correct. I guess there has to be a problem in the loader/file.

**Comment by ran-j** [comment]
Here https://drive.google.com/file/d/1H46sUPdqBTWwpyRx-2vnZ322PbjCWxDz/view?usp=sharing

**Comment by ran-j** [comment]
https://drive.google.com/file/d/1ra8oBzZzzJ7pUU3gjd1l6M6V6XBqM9WK/view?usp=sharing FBX

**Comment by ran-j** [comment]
When I use https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_fbx_nurbs.html 

I got 

```
(index):89 Uncaught ReferenceError: Stats is not defined
    at init ((index):89)
    at (index):59
init @ (index):89
(anonymous) @ (index):59
```

**Comment by donmccurdy** [comment]
Converting to glTF with [FBX2glTF](https://github.com/facebookincubator/FBX2glTF) gives a mostly-working result, although (1) there's a minor issue with the character's eyes, and (2) the textures are too large as @Mugen87 mentions — I get about 3-5 FPS.

**Comment by mrdoob** [comment]
> When I use https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_fbx_nurbs.html

Try loading the fbx in https://threejs.org/editor/ instead.

**Comment by ran-j** [comment]
```
Uncaught TypeError: Cannot read property 'toString' of undefined
    at FBXLoader.js:2499
    at Array.forEach (<anonymous>)
    at AnimationParser.parseAnimationLayers (FBXLoader.js:2480)
    at AnimationParser.parseClips (FBXLoader.js:2365)
    at AnimationParser.parse (FBXLoader.js:2337)
    at FBXTreeParser.parseScene (FBXLoader.js:849)
    at FBXTreeParser.parse (FBXLoader.js:149)
    at FBXLoader.parse (FBXLoader.js:122)
    at FileReader.<anonymous> (Loader.js:197)
```

**Comment by mrdoob** [comment]
Can you share the fbx too?

**Comment by looeee** [comment]
The FBX should load after #15017, unfortunately it seems that transforms are not correct.

**Comment by ran-j** [comment]
On windows 10 ~Mixed Reality View open normaly

https://imgur.com/a/Hqm46y1

**Comment by Mugen87** [comment]
Closing since the test files do no exists anymore. 

However, #20932 should fix the issue for the FBX assets.
