### ISSUE TITLE
renderer.vr.enabled is altering my camera position even though there is no device

### ISSUE THREAD

**Issue by toloudis** [mrdoob/three.js#14994]
I want to allow users to switch in and out of VR headset from web browser. When not in VR, trackball controls will be used.  However,  in the case where no VR devices are attached, the WebGLRenderer is altering my camera position, which messes up the setup that was initially passed to TrackballControls.
The code that does this is in WebVRManager.getCamera: 
```
	this.getCamera = function ( camera ) {

		var userHeight = frameOfReferenceType === 'stage' ? 1.6 : 0;

		if ( device === null ) {

			camera.position.set( 0, userHeight, 0 );
			return camera;

		}
```
Is this the intended behavior?

Three.js r97,  all browsers, testing on Windows 10.

**Comment by mrdoob** [comment]
It is the intended behaviour.
Maybe you can add the camera as a child of a group and assign that group to the TrackballControls?

**Comment by toloudis** [comment]
I felt that if I make the camera a child of a group, the renderer will still modify its position.
I am trying to just delay setting vr.enabled until I detect a vrdisplaypresentchange event, something like this:
```
    window.addEventListener( 'vrdisplaypresentchange', () =>  {
      const device = that.renderer.vr.getDevice();
      if ( (device && !device.isPresenting) || !device ) {
        console.log("LEFT VR");
        that.renderer.vr.enabled = false;
        that.resetPerspectiveCamera();
      }
      else {
        console.log("ENTERED VR");
        that.renderer.vr.enabled = true;
        that.controls.enabled = false;
      }
    
    } );

```
I'm not able to test it with a device yet, until Monday.
