### ISSUE TITLE
PMREM generator convolution gives wrong results over Iphone6

### ISSUE THREAD

**Issue by Domenicobrz** [mrdoob/three.js#15005]
##### Description of the problem
The PMREM generator is computing lower radiance values over chrome on Iphone6 for .jpg envmaps
I'll attach a .zip with a debug page with the assets and test scripts that I'm running

The expected result on desktop/android is:
![s2](https://user-images.githubusercontent.com/25647854/46424982-e4798580-c73a-11e8-8189-36641354f273.PNG)

While on an Iphone6 the cube_uv texture is computed as:
![s1](https://user-images.githubusercontent.com/25647854/46425008-f529fb80-c73a-11e8-8551-a433b8260db6.PNG)

To exclude any problem related to gamma correction / exposure I've included the following lines of code in the fragment shader of PMREMGenerator.js, which essentially outputs a red pixel if the computed radiance surpass a set threshold
```
rgbColor /= float(NumSamples);\n\
if(length(rgbColor) > 1.4) {\n\
   gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);\n\
   return;\n\
}\n\
//rgbColor = testColorMap( roughness ).rgb;\n\
gl_FragColor = linearToOutputTexel( vec4( rgbColor, 1.0 ) );\n\
```

On desktop/android these modifications will generate this result:
![s3](https://user-images.githubusercontent.com/25647854/46425282-84cfaa00-c73b-11e8-8a2f-69c2a4715fa3.PNG)

While on the Iphone6 no red pixel is computed, meaning the accumulated irradiance is lower than the expected

##### Three.js version
- [x] r97

##### Browser
- [x] Chrome
- [x] Safari

##### OS
- [x] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Iphone6

Here's the test page:

[three-issue.zip](https://github.com/mrdoob/three.js/files/2448530/three-issue.zip)

**Comment by WestLangley** [comment]
Please update to the current revision of three.js. Make sure you set the options correctly, and ensure the device supports those options. This can be tedious.

**Comment by mrdoob** [comment]
We have a new `PMREMGenerator`. #18004
Feel free to re-open this if the issue is still there after updating.
