### ISSUE TITLE
Mesh.applyMatrix inconsistant behaviour before / after first render

### ISSUE THREAD

**Issue by gonnavis** [mrdoob/three.js#15001]
##### Description of the problem

The difference between these two codes is only the order of animate(); and setMatrix();
Why one cause cube rotate by local coordinate, one cause rotate by world coordinate?
* [codepen](https://codepen.io/gonnavis/pen/yReOeg) (latest release branch)
* [codepen](https://codepen.io/gonnavis/pen/wYMGgK) (latest release branch)

##### Three.js version

- [ ] Dev
- [x] r97
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
The renderer updates the object's matrix for you, but you need to update the matrix yourself if you call a method that relies on it.
```javascript
mesh.position.x = 5;
mesh.updateMatrix();
```
If you need additional help, please direct your questions to the [forum](https://discourse.threejs.org).
