### ISSUE TITLE
ComputingBoundingSphere NaN values on 2-components position

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#15009]
##### Description of the problem

Hey, this is definitely non-blocking, but, would be helpful to check if the position array is a 3-component based buffer before computing the boundings ( sphere / box ) of a geometry

##### Three.js version

- [ ] Dev
- [ ] r97
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Duplicate #6288
