### ISSUE TITLE
Is there a reliable way to ensure shaders defines are correct on ShaderMaterials that use shader chunks from standard shaders

### ISSUE THREAD

**Issue by griffin2000** [mrdoob/three.js#15008]
Its fairly common to have a ShaderMaterial that is largely based on the standard three.js shaders, with a few custom additions.  E.g.:
```

	myShaderMaterial = new THREE.ShaderMaterial( {

		uniforms: THREE.UniformsUtils.merge( [
			THREE.UniformsLib.common,
			THREE.UniformsLib.envmap,
			THREE.UniformsLib.aomap,
			THREE.UniformsLib.lightmap,
			THREE.UniformsLib.emissivemap,
			THREE.UniformsLib.bumpmap,
			THREE.UniformsLib.normalmap,
			THREE.UniformsLib.displacementmap,
			THREE.UniformsLib.roughnessmap,
			THREE.UniformsLib.metalnessmap,
			THREE.UniformsLib.fog,
			THREE.UniformsLib.lights,
			{
				emissive: { value: new THREE.Color( 0x000000 ) },
				roughness: { value: 1.0 },
				metalness: { value: 0.0 },
				envMapIntensity: { value: 1 } ,// temporary
				myUniform: foo,
			}
		] ),
		lights:true,
		vertexShader: THREE.ShaderChunk.meshphysical_vert,
		fragmentShader: my_meshphysical_frag //Basically just THREE.ShaderChunk.meshphysical_frag with couple of custom features

	});
```

This works fine except the defines in the shader that are setup based on the material parameters, e.g. USE_MAP, are incorrect as these rely on the standard Three.js parameters.

I can hack it work by setting the material parameter, as if it was a regular material AND the relevant uniforms

```
	myShaderMaterial.map = this.grassTexture; //This has no effect (except to ensure USE_MAP is set
	myShaderMaterial uniforms.map.value = this.grassTexture;
	myShaderMaterial.uniforms.map.type = "t";
```
Is there a more reliable way to ensure these are set?

**Comment by WestLangley** [comment]
That is a reasonable question, but this board is not a help site. In the future, please use [stackoverflow](https://stackoverflow.com/questions/tagged/three.js) or the [forum](https://discourse.threejs.org).

https://stackoverflow.com/questions/21928178/replicating-meshlambertmaterial-using-shadermaterial-ignores-textures/21939336#21939336

Also, you do not need to set `.type` when defining uniforms.

**Comment by griffin2000** [comment]
I realize you can manually set the defines. But was actually suggesting there should be a way to set those defines based on the uniforms, rather than have to set the parameters and the uniforms. It at least an easy way to enumerate them.
