### ISSUE TITLE
Raycasting support for Line2Segments

### ISSUE THREAD

**Issue by ojones5** [mrdoob/three.js#15006]
##### Description of the problem

I'm not sure if this is a bug or a new feature to be added. When I try to click on a line2segment, I never get an intersection. I have been successful with getting intersections with line segments.

 I have attached a fiddle that demonstrates the problem:

https://jsfiddle.net/aitheorem/gr7e6why/66/

##### Three.js version
 r97

##### Browser

- [x] All of them

##### OS
 I don't know if this a problem only windows. I have not tested the other operating systems.
- [x] Windows

**Comment by WestLangley** [comment]
`THREE.LineSegments2` uses instancing to generate its geometry. That means the geometry is computed on the GPU. Raycasting, on the other hand, occurs on the CPU.

`THREE.LineSegments2` is part of the examples, and currently does not support raycasting.

**Comment by Mugen87** [comment]
Respective discourse topic: https://discourse.threejs.org/t/raycasting-with-linesegment2-objects/4256
