### ISSUE TITLE
Documentation for which materials can be applied to which objects

### ISSUE THREAD

**Issue by Methuselah96** [mrdoob/three.js#15015]
The documentation for `Line`, `LineSegments`, `Mesh`, and `Points` don't specify which materials those objects are allowed to be created with. It seems from the names of materials that materials beginning with `Mesh` (e.g. `MeshBasicMaterial`, `MeshDepthMaterial`, `MeshLambertMaterial`, `MeshNormalMaterial`, `MeshPhongMaterial`, `MeshPhysicalMaterial`, `MeshStandardMaterial`, and `MeshToonMaterial`) should only be applied to `Mesh`s, materials beginning with `Line` (e.g. `LineBasicMaterial` and `LineDashedMaterial`) should only be applied to `Line` and `LineSegments`, and `PointsMaterial` should only be applied to `Points`. Is it correct that only a certain subset of materials should be applied to certain objects? If this is the case, can that be documented in the documentation or code? I'm fine with making the PR to update the documentation if that's the case, but I thought I should ask if this is the case first. (The reason for this issue is because of the discussion started here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27413).

**Comment by looeee** [comment]
Is there ever a case where any of the materials could be used with objects of a type that's not in their name? I.e. is there ever a time when you might want to use a `PointsMaterial` with a line or something similar? 

If not then I think that the material's names are sufficient documentation.

**Comment by Methuselah96** [comment]
I think it would be good to clarify this since there has been some confusion (see discussion here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27413). The `SpriteMaterial` seems to be nicely documented that is "for use with a `Sprite`." It would be similarly helpful to clarify in the description of each material to say what objects it can be useful (e.g. for line materials to add to the description "for use with a `Line`, for the mesh materials "for use with a `Mesh`" and for `PointsMaterial` "for use with `Points`".

**Comment by Methuselah96** [comment]
For example, it seems as if a `MeshDepthMaterial` can be applied to a `Line` "as an overrideMaterial in some postprocessing" (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27413#pullrequestreview-162180117). There have been some disagreements in the TypeScript definitions whether these objects should accept any type of material, or if they should only allow a certain subset of materials. It has been brought up that the three.js documentation does not specify which materials can be applied to which objects. Can a `MeshDepthMaterial` be applied to a `Line`? Should there be a `LineDepthMaterial` instead? It doesn't seem as if "the material's names are sufficient documentation."

**Comment by Methuselah96** [comment]
It might be stating the obvious, but we have to decide in the TypeScript definitions whether or not the object constructors should accept any type of `Material` or whether it should restrict them to accepting only the materials it is "obvious" for them to accept. Obviously for someone using this library in JavaScript it doesn't matter one way or the other. However, the point of the TypeScript definitions is to define which types should be allowed and which types should not as to avoid any misuse of the library. That way if someone passes a `MeshBasicMaterial` into a `Sprite`, the compiler can warn the user that they're probably doing something they weren't intending to do. So three.js might not throw an error when a mesh material is passed into `Points`, but if it doesn't render the `Points` (doesn't work as intended), then TypeScript should restrict the user from making that mistake if possible.

All that to say, we have to make a decision in the TypeScript definitions whether or not to restrict the types of materials in object constructors. And the lack of documentation and self-evident code makes it hard to prove that the types of these materials should be restricted. Some people do not find the current naming convention to be sufficient documentation and sometimes stating what may seem obvious is necessary especially when writing code. Unless you're opposed to the idea, I plan on making a PR to add it to the documentation to clarify the situation.

**Comment by looeee** [comment]
I would suggest that for typescript you do the same as three.js and allow any material to be applied to any object, then let the user decide whether the result is what they want. As noted previously, at least in the case of `MeshDepthMaterial` it may be desirable to apply it to a `Line`. Perhaps that means this material is not correctly named, unless there is some good reason that I'm not aware of why you shouldn't do this. However, that's a separate discussion.

I'm not opposed to you making a PR, go ahead and we can discuss this further there.

**Comment by pailhead** [comment]
>It might be stating the obvious, but we have to decide in the TypeScript definitions whether or not the object constructors should accept any type of Material or whether it should restrict them to accepting only the materials it is "obvious" for them to accept.

In order for whatever TypeScript pattern to be consistent with three you should allow for `material : Material` in any node, rather than limiting it to a subset of the sub classes. I'd make a `MySafeMesh` that only accepts materials of certain type, i wouldn't change the behavior of the library by changing the interface.  As @looeee has pointed out, you can pass any material and you most likely wont get errors, at least not in JS (maybe something fails with GLSL). 

With this being said, maybe it would be good to clarify this in the documentation. Materials in general are intended to be used with the corresponding node based on the prefix in the name, but any material type can be passed to any node type.

**Comment by Mugen87** [comment]
> I would suggest that for typescript you do the same as three.js and allow any material to be applied to any object, then let the user decide whether the result is what they want.

👍 

AFAICS, the TS declaration files are authored in this way now. Meaning the material type for meshes, lines or points is `Material | Material[]`.

Besides, the existing naming convention makes it quite obvious what material is intended for what type of 3D object. Hence, additional documentations seems redundant.
