### ISSUE TITLE
Rawgit.com is shutting down

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#15027]
For the last few years we have been using https://rawgit.com/ for "previewing" PRs.

In the case of https://github.com/mrdoob/three.js/pull/14942 we would use this link to preview the changes before merging:

https://rawgit.com/yomboprime/three.js/moses/examples/webgl_gpgpu_water.html

Unfortunately, as you can see, rawgit is going away, and the proposed alternative (https://www.jsdelivr.com) serves html as `Content-Type: text/plain`. 

https://cdn.jsdelivr.net/gh/yomboprime/three.js@71e474c75fae8f341468c3b98fcf98ddacc27701/examples/webgl_gpgpu_water.html

Is anyone aware of any other option to continue that workflow? Maybe a browser extension?

**Comment by donmccurdy** [comment]
Zeit Now has a solid GitHub integration that can create static deployments for each PR: https://zeit.co/docs/integrations/now-for-github. But note the max file size and storage limits — we'd need more than the free OSS tier, and/or to move large files elsewhere.

**Comment by looeee** [comment]
[Githack](www.githack.com) is a clone of rawgit:

https://raw.githack.com/yomboprime/three.js/moses/examples/webgl_gpgpu_water.html

[Staticaly](www.staticaly.com) is similar but only has production, not CDN links:

https://cdn.staticaly.com/gh/yomboprime/three.js/moses/examples/webgl_gpgpu_water.html

Same with [htmlpreview.github.io](https://htmlpreview.github.io/) except that it's hosted with GH pages:

https://htmlpreview.github.io/?https://github.com/yomboprime/three.js/blob/moses/examples/webgl_gpgpu_water.html

**Comment by mrdoob** [comment]
Feels like https://raw.githack.com/ is the way to go 🤞

**Comment by mrdoob** [comment]
Worth a quick read though: https://github.com/rgrove/rawgit/pull/191#issuecomment-428310526

**Comment by fraguada** [comment]
I have started using [unpkg](https://unpkg.com/#/) which returns a content type: `content-type: application/javascript; charset=utf-8`
usage:
`<script type="text/javascript" src="https://unpkg.com/three@0.97.0/examples/js/controls/OrbitControls.js"></script>`

**Comment by looeee** [comment]
@fraguada could you show how to use unpkg to load a live example? 

Something like:

https://unpkg.com/three@0.97.0/examples/webgl_animation_skinning_blending.html

**Comment by pailhead** [comment]
People wanted to donate to three.js development in the past. Could this count? If a higher tier on one of these services were listed as a "nice to have" maybe someone would want to pick up this tab?

**Comment by fraguada** [comment]
@looeee 

> However, in that case I think you can just use GitHub pages:
> https://threejs.org/examples/js/controls/OrbitControls.js

Strange, that is the first thing I tried on a codepen when I wrote that on the forum and it didn't work. Seems to work fine now...

**Comment by pailhead** [comment]
There seems to be this:

https://raw.githack.com/
