### ISSUE TITLE
ArrayCamera only renders nearby objects

### ISSUE THREAD

**Issue by rjdlee** [mrdoob/three.js#15022]
##### Description of the problem

Hey, I'm trying to use ArrayCamera with several PerspectiveCameras. However, objects further than ~15m from the camera are not rendered at all. I was able to recreate this behavior with the ArrayCamera Example (see the attached Codepens). I tried copying the fov/aspect/near/far properties of the child PerspectiveCameras to the parent ArrayCamera with no luck. When I directly render one of the PerspectiveCameras, the distant meshes render properly.

* [codepen](https://codepen.io/anon/pen/JmEdRY) (Object at z: -2 doesn't render)
* [codepen](https://codepen.io/anon/pen/bmgdgM) (Object at z: -1 renders correctly)

##### Three.js version

- [x] r97

##### Browser
Only tested in Chrome

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
Only tested on MacOS

- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
N/A

**Comment by WestLangley** [comment]
Sorry, this is not a help site. Please direct your question to the [forum](https://discourse.threejs.org).
