### ISSUE TITLE
AR？

### ISSUE THREAD

**Issue by SeanSure** [mrdoob/three.js#15024]
When will ar be supported on webapp? I saw some WebAR demos from git,but there is not an instance here,Are you expanding it and when will implement?

**Comment by Mugen87** [comment]
`three.js` supports WebXR which is intended to be a unified JavaScript API for both VR and AR. There are not official examples but you might want to have a look at the following article:

https://blog.google/products/google-ar-vr/augmented-reality-web-everyone/

Here is the link to the related github repo: https://github.com/google-ar/webar-article

**Comment by mrdoob** [comment]
We now have a AR example:
https://threejs.org/examples/?q=webxr#webxr_ar_paint

We'll be adding more as the WebXR AR Module stabilizes next year.
