### ISSUE TITLE
Less verbose imports in tests

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#15023]
Tests currently requires verbose imports that are somewhat hard to manage, and have to take into account the relative directories of the test and the code:

```js
import { AnimationClip } from '../../../../src/animation/AnimationClip';
import { AnimationUtils } from '../../../../src/animation/AnimationUtils';
import { BufferAttribute } from '../../../../src/core/BufferAttribute';
import { BufferGeometry } from '../../../../src/core/BufferGeometry';
import { Mesh } from '../../../../src/core/Mesh';
import { Object3D } from '../../../../src/core/Object3D';
import { NumberKeyframeTrack } from '../../../../src/animation/tracks/NumberKeyframeTrack';
import { VectorKeyframeTrack } from '../../../../src/animation/tracks/VectorKeyframeTrack';
import {
	InterpolateLinear,
	InterpolateSmooth,
	InterpolateDiscrete
} from '../../../../src/constants.js';
```

It would be convenient if this could be simplified to import from a common root, like:

```js
import { AnimationClip, AnimationUtils, BufferAttribute, ... } from '../../../../src/';
```

**Comment by donmccurdy** [comment]
Ah, yeah `src/Three.js` looks right. As far as I can tell it works just the same, and sourcemaps don't break... if there isn't some problem I've missed this would be much easier to work with. 👍

**Comment by mrdoob** [comment]
Yeah. That sounds good to me.

**Comment by Usnul** [comment]
Personally I prefer verbosity. For someone who wants to learn - tests are a good place to start. And being able to navigate to small modules of interest is helpful. If you just say "aaaaal of these come from one file" it diminishes that understandability. And if you say "hey, but Three.js just re-exports stuff", then the same argument still applies - you have to de-reference your references now.

I'm not sure what others use for their development environment - I use WebStorm, and it handles imports largely automatically for me, so one or many lines doesn't matter to me in terms of development speed.

Lets say you want to do some refactoring, and you ask a question "where is this class used?" - well, only in one place, apparently - in "Three.js".

**Comment by donmccurdy** [comment]
I'm not totally convinced those imports in tests are doing much good to new learners; with very few exceptions (`constants.js`) an import of `Foo` comes from a file named `Foo.js`, finding the file should not be a problem. And practically if beginners come across ES6 modules at all, they are going to see example code using the npm package in the same way, so the proposed syntax would be more consistent with:

```js
import { AnimationClip, AnimationUtils, ... } from 'three';
```

But in any case, that's a great idea on setting up the dev environment to do this. I checked and sure enough there's a VSCode extension that autocompletes imports and it works here. So I'm OK if we'd rather keep things as-is, since this isn't so inconvenient as it seemed.

**Comment by mrdoob** [comment]
I don't really have an opinion on this.

**Comment by donmccurdy** [comment]
Ok, it's fine for now.
