### ISSUE TITLE
glTF - Skinned Mesh not displayed.

### ISSUE THREAD

**Issue by TimJeskeSensape** [mrdoob/three.js#15020]
I am working on a project were I have examples of real time deformations with ThreeJS. I am creating objects in Blender and export them with the glTF-Exporter to glTF and then import them into ThreeJS and display them. This works perfectly fine with normal models and models with morph targets, but if I add an armature in Blender and export it with the Blender glTF-Exporter, no object is rendered in ThreeJS. The object is there and is logged like this:
![importedobjectinthreejs](https://user-images.githubusercontent.com/37153205/46582275-74257980-ca44-11e8-9427-01852d138795.jpg)

The positioning seems to be right. I let the camera rotate and it wasn't rendered anywhere.
The 3D-Object is correctly rendered in online glTF-Viewers and the VSCode glTF-Add-on. Also the bones are shown there correctly.

I am loading the models like that:

```
import GLTFLoader from 'three/examples/js/loaders/GLTFLoader';
loadModel(modelName, gltfPath) {
    return new Promise((resolve, reject) => {
      this.loader.load(gltfPath, gltf => {
        let objectWrapper = new THREE.Object3D();
        objectWrapper.add(gltf.scene);
        this.models.set(modelName, objectWrapper);
        return resolve();
      });
    });
  }
```

Any ideas why 3D-Objects with bones are not rendered in my scene?

**Comment by donmccurdy** [comment]
Your code looks OK, are you able to share the model (you can drag a ZIP into GitHub comments)? If not, perhaps check object scale and camera parameters.

**Comment by 06wj** [comment]
Try setting frusumCulled to false, it is possible that it was culled.

**Comment by TimJeskeSensape** [comment]
@donmccurdy I can upload this object, which is one of those objects that don't work.
[simple.zip](https://github.com/mrdoob/three.js/files/2455100/simple.zip)

@06wj Thank you. I will try it. On which object do I have to set frusumCulled to false? The imported object has frusumCulled true and all its children too. Do I have to set for all of them or only mesh objects or only bones?

**Comment by TimJeskeSensape** [comment]
I set _frustumCulled_ to false for the imported object and every child it has and it didn't work.

**Comment by Mugen87** [comment]
Crosspost: https://discourse.threejs.org/t/gltf-skinned-mesh-not-displayed/4406

As long as you can't prove a bug, it's actually more a help request than anything else. Because of this, the discussion should be done in the forum.

**Comment by TimJeskeSensape** [comment]
@Mugen87 Ok sorry, I will close this issue and continue asking in the forum.
