### ISSUE TITLE
Bug with Texture

### ISSUE THREAD

**Issue by ostapch** [mrdoob/three.js#15034]
#####  Texture not loaded

You can see this [sample](https://codesandbox.io/s/r024j72r24).
This bug reproduced only in Chrome browser and tested on Windows and macOS.
For current fix I can use `setTimout()` that you can uncomment on line 82 in sample.

##### Other notes

When you click `click` button then this broken texture can be reproduced for random cube. But when you start clicking event programmaticaly then it won't be reproduced.

##### Three.js version

- [x] r97
- [x] r87

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

![screenshot_3](https://user-images.githubusercontent.com/12660249/46804658-df848980-cd6b-11e8-96a4-2ab327658ebc.png)

**Comment by Mugen87** [comment]
Do you also have the problem when using an ordinary texture and not `CanvasTexture`? Maybe there is a problem in context of the HTML5 canvas element.

BTW: I can confirm that only Chrome shows this glitch. In FF or Safari the texture looks good.

**Comment by Mugen87** [comment]
Do you mind reporting the issue at https://bugs.chromium.org/p/chromium/issues/list

**Comment by ostapch** [comment]
No I don't. By the way I updated chrome to 70 version and this bug doesn't appear.

**Comment by Mugen87** [comment]
I can confirm that the update to Chrome 70.0.3538.77 solved the issue. In this case, it's not necessary to report the bug anymore.
