### ISSUE TITLE
SVGLoader ignores styles without a fill

### ISSUE THREAD

**Issue by pgodwin** [mrdoob/three.js#15032]
##### Description of the problem

If an svg has `fill="none"` SVGLoader skips the group/paths. 

For example, loading following SVG file results in no paths being returned by the loader, where a simple line should appear.

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"  width="27987" height="16561" xMin="0" yMin="0">
<g fill="none"  stroke="red" stroke-width="10" transform="matrix(0.9180685877799988,0,0,0.9180685877799988,1146.04833984375,16504.53515625)" xMin="0" yMin="0" >
        <path d="M 10159,-11001 L 10103,-15001 L 5103,-13986 L 14144,-13986"/>
    </g>
</svg>
```

This is due to `isVisible(style)`

```js
 function isVisible( style ) {

        return style.fill !== 'none' && style.fill !== 'transparent';
}
```

Ideally, should isVisible be checking for an actual visibility related property? eg `display="none"`?

##### Three.js version

- [x] Dev
##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by pgodwin** [comment]
I've created a PR with a possible patch. Open to suggestions.
https://github.com/mrdoob/three.js/pull/15033

**Comment by mrdoob** [comment]
Yeah, the loader currently doesn't support strokes.

**Comment by pgodwin** [comment]
Thanks @mrdoob. Is it something you'd like implemented? It looks like two.js has implemented it for their webgl context.

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/pull/16077
