### ISSUE TITLE
GLTFLoader: Issue with sibling animation nodes

### ISSUE THREAD

**Issue by honux** [mrdoob/three.js#15050]
For some reason, the sibling nodes on the following model are receiving modifications which were not intended for them, also ignoring specific modifications for them.

Eg: In the animation, the weapon does not rotate to the correct position. Also, the cheese (The "rock" near the foot) seems to be moving, even though there is no animation programmed for it.

[twitch.zip](https://github.com/mrdoob/three.js/files/2476105/twitch.zip)

Expected:
![image](https://user-images.githubusercontent.com/2934877/46912777-782a2d80-cf55-11e8-8c7d-579694753f00.png)

Result:
![image](https://user-images.githubusercontent.com/2934877/46912782-8e37ee00-cf55-11e8-8447-6adcfb39b94c.png)

All the other loaders (http://sandbox.babylonjs.com/, https://pissang.github.io/clay-viewer/editor/, Blender, etc) seems to be working just fine.

##### Three.js version
- [X] Dev

##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

**Comment by honux** [comment]
It is, it is just a dump from the original League of Legends character. I have not changed anything on it.

I am assuming is an error with Three loader since the official blender extension does not display it that way.

**Comment by donmccurdy** [comment]
I'm assuming the original LoL character was not in glTF format? Was this converted somehow, or can you point me to the source? It could certainly be a bug, but looking at the file contents it does look like the cheese _should_ be moving.

**Comment by Usnul** [comment]
@honux 
can you try this viewer and post the result?
https://gltf-viewer.donmccurdy.com/

it is written on top of three.js, so if it's wrong here - likely it's a three.js loader issue, otherwise - something to do with your pipeline.

**Comment by honux** [comment]
It also displays this gltf on this viewer.
![image](https://user-images.githubusercontent.com/2934877/47257559-d4b1af00-d465-11e8-815e-28f31f27461a.png)

**Comment by donmccurdy** [comment]
Yeah sorry, I’m not sure what’s going on here. Whether it’s our bug or the other engines I’ll keep looking at this...

**Comment by Usnul** [comment]
I have 1 suspicion: three.js has a "unique" way of binding animation. It could have something to do with things like dots in the bone names.

**Comment by Mugen87** [comment]
`R113` (to be more precise #18543) has fixed this issue.

![image](https://user-images.githubusercontent.com/12612165/75988118-630ac180-5ef1-11ea-9fef-0f5adf8ed951.png)
