### ISSUE TITLE
THREE.Matrix4 compose/decompose incorrectly with non-uniform scale

### ISSUE THREAD

**Issue by suiy** [mrdoob/three.js#15079]
##### Description of the problem

It appears that the [compose/decompose function in THREE.Matrix4](https://github.com/mrdoob/three.js/blob/34dc2478c684066257e4e39351731a93c6107ef5/src/math/Matrix4.js#L741-L827) are producing errors when the matrix contains non-uniform scale and rotation components. For example, if we have a matrix4 multiplied with a matrix4 composed from non-uniform scale and rotation, the decomposed T/R/S from the multiplied matrix4 are incorrect.

```
var m1 = new THREE.Matrix4()
var nonUniformMatrix = new Three.Matrix4();
nonUniformMatrix.scale(1, 2, 3);
nonUniformMatrix.makeRotation(Math.PI/4, Math.PI/4, 0);
m1.multiply(nonUniformMatrix, m1);

//TRS are incorrect
m1.decompose(t, r, s)
```

The impact of the problem include:
 - the child object has incorrect scale, rotation, translation if its parent has non-uniform scale and rotation
 - The child object may skewed when rotate or scale locally if its parent has non-uniform scale and rotation
 - When remove the child object from the parent object and add it back to the scene, the transform of child object cannot be recovered. 

##### Reproduce code example:

```javascript
var camera, scene, renderer, control, parentMesh, childMesh;
init();
render();
function init() {
       ...
        var geometry = new THREE.BoxBufferGeometry( 200, 200, 200 );
        var geometry2 = new THREE.BoxBufferGeometry( 100, 100, 100 );
        var material = new THREE.MeshLambertMaterial( { map: texture } );
        
        parentMesh = new THREE.Mesh( geometry, material );
        parentMesh.rotation.set(Math.PI/4, Math.PI/4, 0);
        parentMesh.scale.set(1, 3, 5);
        parentMesh.position.set(-100, 0, 0);

        childMesh = new THREE.Mesh( geometry2, material );
        childMesh.position.set(200, 200, 0);
        
        parentMesh.add(childMesh);
        scene.add( parentMesh );
        
        ...
}
function render() {
        renderer.render( scene, camera );
}
```

##### Reproduce demo
1: a scene contains parent-child objects and rotation/scale update functionalities
 - Open the [ThreeJS demo scene 1](https://s3-us-west-2.amazonaws.com/yuansui-share/Threejs/threejs-example.html)
 - Change x, y, or z of child rotation/scale
 - The child object is skewed when rotation.x, rotation.y, or rotation.z is changed.

2: a scene contains parent-child objects and [TransformControl template](https://threejs.org/examples/js/controls/TransformControls.js)
 - Open the [ThreeJS demo scene 2](https://s3-us-west-2.amazonaws.com/yuansui-share/Threejs/misc_controls_transform.html)
 - TRS gizmo does not update the child object as expected
 - child object is skewed in rotation

##### Three.js version

- [x] Dev
- [x] r97
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
N/A

**Comment by WestLangley** [comment]
See https://github.com/mrdoob/three.js/issues/3845.
