### ISSUE TITLE
OutlinePass does not support outlining child meshes

### ISSUE THREAD

**Issue by ipepe** [mrdoob/three.js#15075]
Hello!

### problem
I noticed that outline only works if Your objects are directly children of scene. Because of that, when I try to outline object that is child of an object in scene. The `visible = false` flag on parent makes child object invisible for outline pass.

### live code snippet
**soon**

### possible solutions
 * cloning scene?
 * using transparency instead of visibility?

I noticed that @Mugen87 is familiar with `three.js/examples/js/postprocessing/OutlinePass.js`

I could try to fix this issue, but I think that idea how to do it should be discussed here first.

**Comment by Mugen87** [comment]
> The visible = false flag on parent makes child object invisible for outline pass.

I think this is the intended behavior. As you can see at the following fiddle, making the mesh invisible also affects the child meshes.

https://jsfiddle.net/f2Lommf5/15288/

**Comment by ipepe** [comment]
So how can we make outline on child mesh?

**Comment by Mugen87** [comment]
I would say you have to perform a custom change to `OutlinePass`. I do not vote for a PR since `OutlinePass` behaves as expected.

**Comment by Mugen87** [comment]
@ipepe Since another use had the same question at the forum, I've shared a modified version of `OutlinePass` here:

https://discourse.threejs.org/t/outlinepass-for-child-meshes/15063/3?u=mugen87

This version controls the visibility via `Object3D.layers` which makes it easy to differentiate between parents/child meshes.

**Comment by mrdoob** [comment]
@Mugen87 Should we make that the default?

**Comment by Mugen87** [comment]
I'm not sure yet :innocent: . I wonder if this approach might interfere with use cases where an app already controls visibility with layers.

**Comment by Mugen87** [comment]
I mean you never know what layer is used by a camera to render something on screen...
