### ISSUE TITLE
GLTFLoader: Unable to load draco compressed model

### ISSUE THREAD

**Issue by n2k3s2it** [mrdoob/three.js#15091]
##### Description of the problem

The (draco compressed) model [`00_07_e-processed_compressed.glb`](https://n2k3s2it.github.io/gltf/00_07_e-processed_compressed.glb) can't be loaded by ThreeJS, it produces the following error in the [glTF Viewer](https://gltf-viewer.donmccurdy.com):
![array_is_null](https://user-images.githubusercontent.com/44294202/47225133-9bbdff80-d3bd-11e8-9eb5-7b82b951513a.png)

It is a valid glb file according to the [glTF Validator](http://github.khronos.org/glTF-Validator/).
The file can be loaded fine in BabylonJS and Cesium previews using [glTF Tools](https://marketplace.visualstudio.com/items?itemName=cesium.gltf-vscode) plugin for VSCode.

The model can be loaded fine using normal files just fine:
- [00_07_e-processed.gltf](https://n2k3s2it.github.io/gltf/00_07_e-processed.gltf)
- [00_07_e-processed.glb](https://n2k3s2it.github.io/gltf/00_07_e-processed.glb)

The 3D file is originally exported from Unity using [UnityGLTF runtime exporter](https://github.com/KhronosGroup/UnityGLTF) and draco compressed using [glTF Pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline).

Tested in our own application using r91.
Tested with [glTF Viewer](https://gltf-viewer.donmccurdy.com) using r97.
Tested with [git clone](https://github.com/donmccurdy/three-gltf-viewer) of glTF Viewer locally, where three.js is replaced with the dev (r98) version.

##### Three.js version

- [x] Dev (r98)
- [x] r97
- [x] r91 (our current version)

##### Browser

- [x] All of them (probably, but tested Chrome, Firefox & Safari)
- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge

##### OS

- [x] All of them (probably, but only tested Windows & MacOS)
- [x] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
I've added the fix for this issue to https://github.com/mrdoob/three.js/pull/15084. With that, the result is:

<img width="539" alt="screen shot 2018-10-19 at 10 35 29 am" src="https://user-images.githubusercontent.com/1848368/47234446-c773c200-d38a-11e8-9022-0bc5ff41f664.png">

But I don't see the same yellow coloring in BabylonJS. There are vertex colors in this model... can you confirm this looks correct?

**Comment by donmccurdy** [comment]
Looking at the uncompressed models, I'm going to assume the yellow vertices shouldn't be there. 🤔
