### ISSUE TITLE
FBXLoader rotated Objects

### ISSUE THREAD

**Issue by p1337** [mrdoob/three.js#15097]
##### Description of the problem

We export FBX Files from Revit (CAD Building Software). These files show rooms, that we want to load in three.js + ar.js .

after using the latest FBXLoader, some of the elements are rotated and some come through in the right orientation.

Images

- [Revit image](http://p1337.synology.me/vrview/images/errors/Revit.png)
- [FBXLoader image](http://p1337.synology.me/vrview/images/errors/FBXLoader.png)
- [Autodesk FBX Viewer image](http://p1337.synology.me/vrview/images/errors/adsk_FBX.png)

Testing this FBX File with other online Viewers - show that the generated FBX File ist quite ok.

FBX File:
- [FBX](http://p1337.synology.me/vrview/images/errors/3D-EXPORT.fbx)

##### Three.js version

- [ ] Dev
- [x] r97
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by p1337** [comment]
Maybe solved:

replaced in FBXLoader.js  ~ row 3976:

`var array = transformData.rotation.map(THREE.Math.degToRad);`

with 

`    if (transformData.rotation.map(THREE.Math.degToRad)[2] < 0) {

                var bereinigt = transformData.rotation.map(THREE.Math.degToRad)[2] * -1.5;
                var array = new Array;
                array.push(transformData.rotation.map(THREE.Math.degToRad)[0]);
                array.push(transformData.rotation.map(THREE.Math.degToRad)[1]);
                array.push(bereinigt);
            }
            else if (transformData.rotation.map(THREE.Math.degToRad)[2] > 0) {

                var bereinigt = transformData.rotation.map(THREE.Math.degToRad)[2] * -3.5;
                var array = new Array;
                array.push(transformData.rotation.map(THREE.Math.degToRad)[0]);
                array.push(transformData.rotation.map(THREE.Math.degToRad)[1]);
                array.push(bereinigt);

            } else if (transformData.rotation.map(THREE.Math.degToRad)[2] == 0 ){

                var bereinigt = transformData.rotation.map(THREE.Math.degToRad)[2] * 1.5;
                var array = new Array;
                array.push(transformData.rotation.map(THREE.Math.degToRad)[0]);
                array.push(transformData.rotation.map(THREE.Math.degToRad)[1]);
                array.push(bereinigt);
            }

            else {
                var array = transformData.rotation.map(THREE.Math.degToRad);

            }`


Please verify.

**Comment by looeee** [comment]
Thanks for looking into this. I'll take a look later in the week and see if your code is a general solution.

**Comment by mrdoob** [comment]
Files are no longer available.
