### ISSUE TITLE
TrackballControls: Fixed bad zoom performance

### ISSUE THREAD

**Issue by boulabiar** [mrdoob/three.js#15096]
The issue described in #14182 and #14013 is still present.

**Comment by Mugen87** [comment]
Since #14013 is still open, do you mind to close the issue? I don't think there is a benefit to have two issues for the same problem.

**Comment by boulabiar** [comment]
ok, I'll close it.
But I'm really confused what does #14622 actually fix to get merged and closed?
it pretends to fix #14182 and #14013 ?

**Comment by Mugen87** [comment]
The PR fixed an issue with "spongy" edges. @XanderLuciano explains the fix in the following video very well:

https://www.youtube.com/watch?v=QqQ-qKrXLoI

**Comment by boulabiar** [comment]
Ok, I hope one day I will be able to explain like him!
BTW, in that same video, and exactly at 1:47 to 1:50 it is still possible to view the problem happening after the "fix".
