### ISSUE TITLE
GLTFLoader: WebWorker support?

### ISSUE THREAD

**Issue by sarathsi** [mrdoob/three.js#15090]
Is there any support currently or future plans for loading glTF model using Web Workers, just like OBJLoader2 (https://threejs.org/docs/#examples/loaders/OBJLoader2)

**Comment by Mugen87** [comment]
This topic was already discussed in a previous PR. Please have a look at: https://github.com/mrdoob/three.js/pull/13263#issuecomment-368287030

**Comment by donmccurdy** [comment]
In summary — it would probably be a mistake for us to move the entire GLTFLoader parsing process into a Web Worker, as OBJLoader2 does. But for certain parts of the parsing process (Draco decompression) Web Workers would be a great addition.

If you have a specific example where parsing is not as fast as you'd like, please feel free to share it and we can consider the options. :)

**Comment by Mugen87** [comment]
> But for certain parts of the parsing process, like Draco decompression, Web Workers would be a great addition.

Since we already have #13648 for this, I think it's better to close the issue. We can reopen the issue if @sarathsi provides a concrete use case where the parsing process or a pure `glTF` file (without Draco compression) is faster in a worker than in the main thread.
