### ISSUE TITLE
Change "gammaFactor" on runtime make no effect

### ISSUE THREAD

**Issue by Ben-Mack** [mrdoob/three.js#15100]
Change WebGLRenderer gammaFactor on runtime take no effect, the renderer does not update accordingly to the new gammaFactor value.

I also tried to set materials and textures needsUpdate to true but still the same.

Maybe the only way left is recreate the renderer, but I think it's more like a bug.

**Comment by WestLangley** [comment]
It was designed that way on purpose, and not considered something a user would change.

What is your use case for changing it?

**Comment by Ben-Mack** [comment]
It's like a kind of post-processing filter, with ability to change the look of whole scene.

Changing gamma is not a rare use case in 3D renderer (e.g. V-Ray 3dsMax), where quite a few users change gamma to 1.6 or 1.8 to have better contrast than the default 2.2 (or 1.0)

**Comment by WestLangley** [comment]
Hmmm. We were planning on removing `gammaInput` and `gammaOutput` in favor of:
```javascript
material.encoding = THREE.sRGBEncoding; // or THREE.LinearEncoding
renderer.outputEncoding = THREE.sRGBEncoding; // or THREE.LinearEncoding
```
That means `gammaFactor` would be removed, too.

Is that a problem for your use case, or would [GammaCorrectionShader](https://github.com/mrdoob/three.js/blob/dev/examples/js/shaders/GammaCorrectionShader.js) be adequate if `GAMMA_FACTOR` were a uniform?

//

There probably would be complaints. I suppose we could support:
```javascript
renderer.gammaFactor = 1.8;
renderer.outputEncoding = THREE.GammaEncoding;
```
In any event, `material.needsUpdate = true` would be required when `gammaFactor` is changed.

**Comment by Ben-Mack** [comment]
Yes, removing gammaFactor will be a problem for us, so I suggest Three.js should keep a way for user to fine tune gammaFactor as it is now.

About updating gammaFactor on runtime, I've written steps to reproduce here: https://discourse.threejs.org/t/change-gammafactor-on-runtime-take-no-effect/4591/3

_(Sorry for double post, Github has some problem make this issue 404 for a while, I thought it got deleted)_

**Comment by bhouston** [comment]
> Yes, removing gammaFactor will be a problem for us, so I suggest Three.js should keep a way for user to fine tune gammaFactor as it is now.

Write your own post processing filter called GammaPass and implement anything you want there.  Basically that is what you want anyhow and it gives you the flexibility to add/remove and adjust it real time in an efficient manner.

Basically because you are doing it in a bad way you are running into issues with it.  Just do it properly as a post effect pass.

**Comment by bhouston** [comment]
When @Ben-Mack wrote this it was indicative of the correct solution:

> It's like a kind of post-processing filter, with ability to change the look of whole scene.

Basically it is a post effect pass and should be implemented as such.
