### ISSUE TITLE
can we have something like delay property on AnimationClip

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#15103]
as far as I can see, AnimationClip tracks always run from T = 0 to duration. it would be great if we could set the delay to run them from T = delay to delay + duration.

are we supposed to edit the times in tracks just to set the delay.

**Comment by donmccurdy** [comment]
Would `track.shift(...)` or `action.startAt(...)` work? E.g.:

```js
clip.tracks.forEach( ( track ) => track.shift( -2.0 ) );

var action = mixer.clipAction( clip );
action.startAt( 2.0 );
action.play();
```

The latter looks like what you want. See https://threejs.org/docs/#api/en/animation/AnimationAction.startAt.

**Comment by makc** [comment]
oh yes, [it](https://github.com/mrdoob/three.js/blob/78ecf5f17e83cd3d1d94e02844a0864789a03be6/src/animation/AnimationAction.js#L342-L360) does look like it could work, thanks.
