### ISSUE TITLE
GLTFExporter does not honor draw range with indexed geometry.

### ISSUE THREAD

**Issue by Moumou38** [mrdoob/three.js#15104]
At the moment not aivailable, it would be nice to have indexed geometry with draw range support in GLTF exporter. 
https://github.com/mrdoob/three.js/blob/master/examples/js/exporters/GLTFExporter.js line 564 : 
`// @TODO Indexed buffer geometry with drawRange not supported yet`

**Comment by Mugen87** [comment]
Merging into #21538.

**Comment by WestLangley** [comment]
>Merging into #21538.

?

This PR is about _indexed_ geometry; #21538 is about _non-indexed_.

**Comment by Mugen87** [comment]
Ups, I've misread that. Reopening.
