### ISSUE TITLE
Initially muted video breaks videoTexture

### ISSUE THREAD

**Issue by EliasHasle** [mrdoob/three.js#15111]
I am doing some experiments using webcam input and saving processed video with audio to a local file. I have encountered a strange problem, that _may be a browser bug_. I am using one of the most recent versions of Chromium for Windows. Below is a simple script (with no image processing) to reproduce the problem. The record button starts and stops a recording. Without muting the audio, there will be feedback. Therefore I want to mute the audio for the video element that is being used as a texture, but keep the audio for the recording.

Setting [muted](https://www.w3schools.com/tags/av_prop_muted.asp):true during the Object.assign (remove _//_ from _//muted: true,_ in the script below) causes this error message:
**WebGL: INVALID_VALUE: tex(Sub)Image2D: video visible size is empty**
and afterwards setting mute to false does not help.

Strangely, letting muted be false initially, it can be toggled using dat.GUI and achieve the desired effect.

I can work around the problem by creating a new pure video stream for the video element, but it would be better to understand why muted:true does not work.

````
<!doctype html>

<html>
<head>

<script src="http://threejs.org/build/three.js"></script>
<script src="http://threejs.org/examples/js/libs/dat.gui.min.js"></script>

</head>
<body>
<script>
var videoTexture, videoSettings, videoStream, audioTrack;

let gui = new dat.GUI();

navigator.mediaDevices.getUserMedia({video: true, audio: true}).then(function(stream) {
	videoSettings = stream.getVideoTracks()[0].getSettings();
	audioTrack = stream.getAudioTracks()[0];
	//Making a separate pure video stream is a workaround
	//let videoStream = new MediaStream(stream.getVideoTracks());
	let video = document.createElement("video");
	Object.assign(video, {
		srcObject: stream,//videoStream,
		autoplay: true,
		//Setting muted here breaks everything
		//muted: true,
	});
	//Toggling muted later works as expected, if muted was initially false:
	gui.add(video, "muted");
	//document.body.appendChild(video);
	videoTexture = new THREE.VideoTexture(video);
	videoTexture.minFilter = THREE.LinearFilter;
	init();
	}
	).catch(function(error){console.error(error);});

var renderer, scene, camera;

function init() {
	let w = videoSettings.width;
	let h = videoSettings.height;

	//Renderer setup
	document.body.style = "overflow: hidden;";
	var container = document.createElement("div");
	document.body.appendChild(container);
	renderer = new THREE.WebGLRenderer({antialias: true});
	renderer.setSize(w, h);
	container.appendChild(renderer.domElement);
	
	//Scene setup:
	scene = new THREE.Scene();
	
	let display = new THREE.Mesh(
		new THREE.PlaneBufferGeometry(2, 2),
		new THREE.MeshBasicMaterial({map: videoTexture})
	);
	scene.add(display);
	
	//Camera setup:
	camera = new THREE.OrthographicCamera(-1,1,1,-1);
	camera.position.z = 1;
	//scene.add(camera);

	videoStream = renderer.domElement.captureStream(videoSettings.frameRate);
	videoStream.addTrack(audioTrack);
	
	let data, mediaRecorder;
	let recording = false;
	gui.add({record: function() {
		if (!recording) {
			data = [];
			mediaRecorder = new MediaRecorder(videoStream);
			mediaRecorder.ondataavailable = function(e) {data.push(e.data);};
			mediaRecorder.onstop = function(e) {
				let blob = new Blob(data, {type: "video/webm"});
				let a = document.createElement("a");
				a.download = "Video_recording.webm";
				a.href = window.URL.createObjectURL(blob);
				a.click();
			}
			mediaRecorder.start();
			recording = true;
		} else {
			mediaRecorder.stop();
			recording = false;
		}	
	}},"record");
	
	
	setInterval(function() {
			renderer.render(scene, camera);
		}, 1000./videoSettings.frameRate);
}
</script>
</body>
</html>
````

**Comment by Mugen87** [comment]
> I am using one of the most recent versions of Chromium for Windows.

Do you have the same problem in other browser, too. e.g. Firefox? If not, I suggest you close this issue and file a bug right here: https://bugs.chromium.org/p/chromium/issues/list

**Comment by EliasHasle** [comment]
I will test that later today. Thank you. :-)

**Comment by EliasHasle** [comment]
@Mugen87 It works in Firefox. In standard updated Chrome it fails under the same conditions as in the standalone Chromium installation I used, but without the WebGL warning.

I suppose we cannot rule out 100% that Three.js is involved (due to browser compatibility fallbacks etc.), unless I make a pure WebGL demo that replicates the behavior.

**Comment by Mugen87** [comment]
Please don't get me wrong but you should not have created the issue in the first place. Only then if you can clearly demonstrate a `three.js` bug. So I think it's better to close the issue and only reopen if it is not a browser issue.

**Comment by WestLangley** [comment]
Please use the three.js [forum](https://discourse.threejs.org) for help requests. If you can demonstrate a three.js bug, you may reopen this.

**Comment by mrdoob** [comment]
> I confirmed the bug in pure WebGL, and filed a report here: https://bugs.chromium.org/p/chromium/issues/detail?id=898550

@EliasHasle thanks for doing that!

**Comment by WestLangley** [comment]
@EliasHasle Thanks.

>I have encountered a strange problem, that may be a browser bug.
>...for all I knew at the time it could have been a three.js bug

Please understand that we do not have the resources here to debug user's code (or the interest, for that matter), so we ask users to limit postings here to feature requests and demonstrated three.js bugs.

**Comment by jufa** [comment]
Followup in case anyone finds their way here: setting the video playhead to > 0 seemed to have resolved this in my application using an mp4 in a `VideoTexture` instance, i.e. `video.currentTime = 1;`

**Comment by EliasHasle** [comment]
@jufa Hm, I wonder whether that somehow applies to a live camera stream too...

**Comment by iefreer** [comment]
in this case, a workaround is to call video.play() before using it as a video texture
