### ISSUE TITLE
No info in docs how to load 3D models

### ISSUE THREAD

**Issue by Alwox** [mrdoob/three.js#15116]
https://threejs.org/docs/#manual/en/introduction/Loading-3D-models this page in manual actually is not containing any info how to load 3D model. There is only info that Three.js have many loaders and no info how to use them. When i go to loader page (no link to this in manual, i found this accidentally) there is also not too much useful info. At least for beginners but loading 3D models is quite basic feature. I think it would be great to have short step by step instructions how to reach it.

**Comment by donmccurdy** [comment]
I’ve thought about this but wasn’t sure how to resolve it — if we show code on the page, would it just be GLTFLoader? Usage for other loaders will vary, and many don’t have their own pages in the docs.

Or we could link directly to https://threejs.org/docs/index.html#examples/loaders/GLTFLoader

**Comment by Alwox** [comment]
I think having one example there would be good idea but also would be nice to have it "ready to copy paste" ;) because this example https://threejs.org/docs/index.html#examples/loaders/GLTFLoader is not working for me when i add it to code from first manual page. I found info that probably i need copy paste GLTFLoader file but still it's not obvious. Also usage of loaders in different loaders examples looks quite different (i assume it's not because on loader speciefic) what makes harder to find out how to actually use them. I think we need one simple, complete example how to just move our 3D model on browser screen :)
