### ISSUE TITLE
BoxGeomtery documentation improvements

### ISSUE THREAD

**Issue by rexdk** [mrdoob/three.js#15115]
I hope someone may find this suggestion useful:

I think the current BoxGeometry dosumentation has the following issues:

===1===
“BoxGeometry is the quadrilateral primitive geometry class”
i) I think that this is technically a cuboid, not a quadrilateral which is a plane figure with 4 vertices.
ii) The position and orientation of the cuboid is not clear from the current documentation.

===2===
“width — Width of the sides on the X axis.”
i) The sides are not “on” the X axis. 

===3===
“geometry.parameters; // outputs an object {width: 1, height: 1, depth: 1, widthSegments: undefined, heightSegments: undefined}”
i) The <code></code> is wrongly formatted, so that prettify.js mucks the indentation up.
ii) The object should include { ... depthSegments: undefined }
iii) It would help to give an example showing the inheritance from Geometry, as this is a basic class that a newbie might consult.

======
May I suggest the attached replacement documentation? It should have an html extension, but I can't seem to upload that. If this is helpful, then it's better than me moaning about documentation issues. If it's not helpful, I'll go away quietly ;)

[BoxGeometry.txt](https://github.com/mrdoob/three.js/files/2507757/BoxGeometry.txt)

**Comment by WestLangley** [comment]
You can make a contribution by editing the [file](https://github.com/mrdoob/three.js/blob/dev/docs/api/en/geometries/BoxGeometry.html) yourself. Would you like to do that?

**Comment by rexdk** [comment]
Sure. But I don't know how to do that - sorry, this is new to me. Feel free to give me some simple guidance - thank you.

**Comment by WestLangley** [comment]
Click on the "Edit this file" icon. It looks like a pencil. Do what you can. If you mess up, don't worry. :-)

**Comment by Mugen87** [comment]
Yes :innocent:

**Comment by rexdk** [comment]
OK. Took a while to discover how, but I think it's done. Pardon my inexperience.
