### ISSUE TITLE
Edit button in docs broken after r96

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#15136]
##### Description of the problem
#14846 stripped the localization from the `[path]` placeholder to get the links to the source files working again but the edit button in the top right needed that to point to the localized docs file.

https://github.com/mrdoob/three.js/blob/12450bedbef53649992cf55f10d7c1b9a253570f/docs/page.js#L102-L106

First noticed in https://github.com/mrdoob/three.js/pull/14750#issuecomment-414792240 as far as I can tell. A previous hotfix(hiding the button) was applied in 0c58464ab1b37451d6440025bc5d8c0095fec8da, but got removed with the release of r96.

**Comment by Mugen87** [comment]
A simple fix is to add the following line in `page.js` right before `window.open()`.
```js
if ( section === 'api' ) path = /\/api\/[A-z0-9\/]+/.exec( pathname ).toString().substr( 5 );
```
https://github.com/mrdoob/three.js/blob/c0dbf052eb276e407a0d2ea881b010303859d9cd/docs/page.js#L104
This will ensure the path has the localized part which is necessary to build the correct URL.

Any better ideas? 😇
