### ISSUE TITLE
GLTFLoader - TypeError: Cannot read property 'response' of undefined

### ISSUE THREAD

**Issue by Jonybang** [mrdoob/three.js#15154]
##### Description of the problem
```
const loader = new GLTFLoader();
loader.setCrossOrigin('anonymous');
loader.load('model-assets/untitled.gltf', function (gltf) {
   // ...
});
```
The code above throws the error:
```
three.module.js:32183 Uncaught TypeError: Cannot read property 'response' of undefined
    at three.module.js:32183
    at XMLHttpRequest.wrapped (index.js:3134)
```
Maybe because i used webpack for build js files into one.

##### Three.js version

- [ ] Dev
- [x] r97

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/pull/15155#issuecomment-464200925
