### ISSUE TITLE
SMAAPass: Texture marked for update but image is incomplete

### ISSUE THREAD

**Issue by cnsdato** [mrdoob/three.js#15162]
##### Description of the problem
When using the SMAAPass, a warning is logged:
`THREE.WebGLRenderer: Texture marked for update but image is incomplete`
This warning occurs because the `Image.complete` is false, after setting `Image.complete` it looks like it is asynchronous.

Please also include a live example if possible. You can start from these templates:

* https://threejs.org/examples/?q=smaa#webgl_postprocessing_smaa
* https://codepen.io/DaTo/pen/rqZQEB

##### Three.js version

- [ ] Dev
- [x ] r97
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
You're right! A simple fix could look like the following code section. Ideally it would be place after this [line](https://github.com/mrdoob/three.js/blob/c0dbf052eb276e407a0d2ea881b010303859d9cd/examples/js/postprocessing/SMAAPass.js#L53) in `SMAAPass`:
```js
var self = this;

setTimeout( function () {

        // assigning data to HTMLImageElement.src asynchronous (see #15162)
        // using setTimeout() avoid the warning "Texture marked for update but image is incomplete"

	self.searchTexture.needsUpdate = true;
	self.areaTexture.needsUpdate = true;

}, 0 );
```
Would you like to do a PR with the changes?

**Comment by WestLangley** [comment]
That looks like a hack to me. Please consider a more conventional pattern:
```javascript
var image = new Image();
image.src = dataURL;

var texture = new THREE.Texture( image );

image.onload = function () {
    texture.needsUpdate = true;
};
```

**Comment by Mugen87** [comment]
Indeed, that's nicer 👍

**Comment by cnsdato** [comment]
I will change it to onload callbacks.
