### ISSUE TITLE
WebGL: ERROR: too many uniforms loading glTF on iOS

### ISSUE THREAD

**Issue by revyTH** [mrdoob/three.js#15167]
##### Description of the problem

I've exported a scene from Blender in glTF format (using https://github.com/KhronosGroup/glTF-Blender-Exporter) and import back in threejs using GLTFLoader.
The scene loads fine in chrome and safari desktop, but fails to load on iOS 12. These are the errors inspected from safari:

WebGL: ERROR: too many uniforms
THREE.WebGLShader: Shader couldn't compile.
THREE.WebGLShader: gl.getShaderInfoLog() – "fragment" – "ERROR: too many uniforms↵" – "1: #extension GL_OES_standard_derivatives : enable↵2: precision highp float;↵3: precision highp int;↵4: #define SHADER_NAM…"
THREE.WebGLProgram: shader error:  – 0 – "gl.VALIDATE_STATUS" – false – "gl.getProgramInfoLog" – "" – "" – "ERROR: too many uniforms"
WebGL: INVALID_OPERATION: useProgram: program not valid
WebGL: INVALID_OPERATION: drawElements: unable to simulate vertexAttrib0 array
[...]

##### Three.js version

- [ ] r95

##### Browser

- [ ] Safari

##### OS

- [ ] iOS

**Comment by mrdoob** [comment]
Can you share the file?

**Comment by revyTH** [comment]
Done!

[hallway_gltf.zip](https://github.com/mrdoob/three.js/files/2529998/hallway_gltf.zip)

**Comment by soadzoor** [comment]
@revyTH Looks like the `.bin` file is missing from your zip. Without that, it's impossible to debug this problem.
