### ISSUE TITLE
Favicon for website.

### ISSUE THREAD

**Issue by rockmandash** [mrdoob/three.js#15169]
Hello, can you have a favicon for the official website?
It will be great for chrome bookmark.
![image](https://user-images.githubusercontent.com/7580792/47693293-18f63980-dc34-11e8-9040-5b72b77dd365.png)

**Comment by Mugen87** [comment]
Related #13793

**Comment by Mugen87** [comment]
I'm marking this as a duplicate. Discussion about an icon goes here: #13793
