### ISSUE TITLE
Prefetching DRACO decoder in GLTF Loader

### ISSUE THREAD

**Issue by TyLindberg** [mrdoob/three.js#15168]
Currently when a DRACO encoded glTF file is loaded with the GLTFLoader, the DRACO decoder will only be fetched after all of the mesh and texture data has been loaded.

For non-embedded glTF files would it be better to prefetch the DRACO decoder using `THREE.DRACOLoader.getDecoderModule()` after loading the .gltf file, causing the DRACO decoder to load in parallel with the mesh and texture data? My thought is that this would decrease the perceived load time for the user, while also allowing the DRACO decoder WebAssembly file to compile while the rest of the model assets are loading.

**Comment by donmccurdy** [comment]
Great idea; this should speed things up:

<img width="640" alt="screen shot 2018-10-30 at 8 04 15 am" src="https://user-images.githubusercontent.com/1848368/47727978-af1d6600-dc1a-11e8-94a7-55922e4dd696.png">

I think it would be reasonable to prefetch at the end of the GLTFDracoMeshCompressionExtension constructor:

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js#L500-L512

Would you be willing to open a PR? :)

**Comment by TyLindberg** [comment]
Definitely! I'll get an implementation up and running and compare the network load times.
