### ISSUE TITLE
"materialLine" in OBJLoader.js is undefined

### ISSUE THREAD

**Issue by FAdrien** [mrdoob/three.js#15175]
Looking at the file [OBJLoader.js](https://github.com/mrdoob/three.js/blob/34dc2478c684066257e4e39351731a93c6107ef5/examples/js/loaders/OBJLoader.js) at line _698_ :

> materialLine.copy( material );

However, _materialLine_ is only defined in the above **if** block so... **"materialLine" in OBJLoader.js at line _698_ is undefined**.

---

Now, replace : 
> materialLine.copy( material );

by
> materialPoints.copy( material );

also leads to an error in [three.js](https://raw.githubusercontent.com/mrdoob/three.js/dev/build/three.js) near line _23480_ :

> uniforms.ambientLightColor.value = lights.state.ambient;

where _uniforms.ambientLightColor_ is **undefined**.

**Comment by Mugen87** [comment]
Can you share your `OBJ` file for testing. I suspect the mentioned code path was not review so far.
