### ISSUE TITLE
I add a fix for  loading JSON with more then one set of UV 

### ISSUE THREAD

**Issue by rtsamir** [mrdoob/three.js#15173]
Hi,

at _JSONLoader.js_ I add a fix for  loading JSON with more then one set of UV 
See The Fixed JSONLoader.js attached. 

Thanks,
Ronen Tsamir.
[JSONLoader.zip](https://github.com/mrdoob/three.js/files/2529733/JSONLoader.zip)

**Comment by Mugen87** [comment]
Maybe it's better to create a PR instead? This makes it easier to see your actual changes.

**Comment by rtsamir** [comment]
So JSON Format will no longer be supported ?

**Comment by rtsamir** [comment]
Thanks, I'll Check the ObjectLoader

**Comment by Mugen87** [comment]
Closing this for now.
