### ISSUE TITLE
computeFaceNormals() giving different results on some browsers

### ISSUE THREAD

**Issue by Fejm** [mrdoob/three.js#15181]
##### Description of the problem
_(I'm new on Three.js so please be patient)_

Running computeFaceNormals() on custom geometry is giving different result based on browser. 
For example, it's work as intented on Chome and Firefox but not work on IE11 or android version of chrome.

Discovered this issue while learning UV mapping.

Please check live example for more info:
* https://jsfiddle.net/ya23nv5u/

Chrome:
![chrome](https://user-images.githubusercontent.com/5827560/47782016-7c00d280-dcff-11e8-91c9-d2c9733ab075.png)
IE11:
![ie](https://user-images.githubusercontent.com/5827560/47782017-7c00d280-dcff-11e8-8d81-b61f54b8518c.png)

##### Three.js version

- [x] Dev
- [x] r97

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer
- [x] Chrome (Android)

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [x] Linux
- [x] Android
- [ ] iOS

**Comment by Mugen87** [comment]
When I'm using your fiddle in Chrome (70.0.3538.77), I see the same output like your IE11 screenshot.

**Comment by Fejm** [comment]
Hmmm.. It's not working now.. Maybe Chrome update was pushed today. :|

**Comment by Mugen87** [comment]
Why do you think this has something to do with `computeFaceNormals()`? If I comment out the method call, I have the same output:

https://jsfiddle.net/ya23nv5u/4/

**Comment by pailhead** [comment]
The screenshot indicates a difference with uvs if anything, not normals?

**Comment by Fejm** [comment]
After using computeFaceNormals() i was able to get correct locations for UV, as shown on screenshots. When outputing data to console there was difference between Chrome and IE.

It's looks like chrome update removed this "difference" and i'm done here. It looks like my code is broken now.

**Comment by Mugen87** [comment]
I don't think that this issue is related to normals but texture mapping.

The issue section at github is for bugs and feature request only. If you discover a browser bug, please directly report the issue to the vendor. If you need help, use the [forum](https://discourse.threejs.org/) or stackoverflow. You can reopen the issue if you clearly demonstrate a `three.js` bug.
