### ISSUE TITLE
copyFramebufferToTexture and WebGLRenderTarget.texture.image undefined

### ISSUE THREAD

**Issue by axa2** [mrdoob/three.js#15196]
Hello, when calling WebGLRenderer.copyFramebufferToTexture it expects the given Texture.image to have a defined width and height.
But if the given Texture comes from a WebGLRenderTarget the image field is undefined.
Shouldn't copyFramebufferToTexture receive an optional specified width and height?

r98

```javascript
this.copyFramebufferToTexture = function ( position, texture, level ) {
	var width = texture.image.width; // image undefined when texture comes from a render target
	var height = texture.image.height;
	var glFormat = utils.convert( texture.format );
	this.setTexture2D( texture, 0 );
	_gl.copyTexImage2D( _gl.TEXTURE_2D, level || 0, glFormat, position.x, position.y, width, height, 0 );
};
```

**Comment by Mugen87** [comment]
The method is not designed to support a `WebGLRenderTarget`. What is your use case for not using an instance of `Texture`?

**Comment by axa2** [comment]
Thanks for the answer.
For the record, I am copying a render target to another using a quad and a copy program, I was testing the gl copyTexImage2D call expecting some performance gains, but there is none.
I have no reasons to suggest an api change. Thanks for your time
