### ISSUE TITLE
GLTFLoader: metal/rough and spec/gloss materials inconsistent.

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#15195]
Per https://github.com/KhronosGroup/glTF-Sample-Models/pull/192, our implementation of the metal/rough and spec/gloss PBR materials is somewhat inconsistent —

![47862952-976ff880-de39-11e8-98ed-d327c9eda53e](https://user-images.githubusercontent.com/1848368/47866553-54237480-ddbc-11e8-8935-dd0456546cdb.png)

In theory these two models should match. Currently most WebGL implementations do not have the spec/gloss material correct, but the BabylonJS rendering (https://github.com/KhronosGroup/glTF-Sample-Models/pull/192#issuecomment-419227265) looks like a good reference.

/cc @takahirox this looks similar to the roughness bug you fixed previously?

**Comment by cx20** [comment]
I confirmed that this issue has been fixed in the latest GLTFLoader.
However, the color of the background environment map seems to have changed slightly.
It used to be a color close to orange like sunset before, but seems to be whitish as a whole when using the latest version of three.js.

![image](https://user-images.githubusercontent.com/1833979/48678413-7db70b00-ebc6-11e8-9703-65afcf36cfbe.png)

Is the usage wrong?

**Comment by cx20** [comment]
@donmccurdy Thank you for your advice.  By setting `encoding`, color problem of environment map has been solved.
However, it seems that the color of the water bottle is also darkly displayed, is it correct?
![image](https://user-images.githubusercontent.com/1833979/48725137-9418a180-ec6e-11e8-9bdd-ccf19fa07e9e.png)

**Comment by donmccurdy** [comment]
I'm not sure if that's correct or not... if other engines in the preview list are also using that environment map it would be helpful to compare.

**Comment by cx20** [comment]
I compared several engines using the same environment map. However, I did not know which was the correct display result.
![image](https://user-images.githubusercontent.com/1833979/48732527-4bb7ae80-ec83-11e8-99ff-d2c7ec9f63f5.png)

**Comment by cx20** [comment]
I have created Issue on the above. https://github.com/mrdoob/three.js/issues/15285
