### ISSUE TITLE
FBXLoader - Issue Adding Axes Helper to child meshes of group.

### ISSUE THREAD

**Issue by uscivics** [mrdoob/three.js#15208]
##### Description of the problem

Three.js AxesHelper to all children of group. Axes Helper position defaults to 0,0,0 for each axeshelper that is added.

The following code is used to load the fbx model:

```
var loader = new THREE.FBXLoader();
                loader.load( '../assets/models/Windia_C4D_Export.fbx', function ( object ) {
                //loader.load( '../assets/models/quiggles_AR.fbx', function ( object ) {
                    console.log(object);
                    object.traverse( function ( child ) {
                        console.log(child);
                        if ( child.isMesh ) {

                            const oldMat = child.material;
                            //CONVERT MATERIAL TO STANDARD MATERIAL.
                            child.material = new THREE.MeshStandardMaterial({
                                color: oldMat.color,
                                map: oldMat.map,
                            });

                            child.castShadow = true;
                            child.receiveShadow = true;
                            child.material.combine = THREE.MixOperation;
                            child.material.envMap = envMap;
                            child.material.shininess=10;
                            child.material.refractionRatio=.5;
                            child.material.reflectivity=0.1;
                            //child.material.normalMap = texture;
                            //child.material.normalMapType = 0;
                            child.material.metalness=1;
                            //child.material.color.setHex( 0xffffff );
                            var sphereAxis = new THREE.AxesHelper(200);
                            child.add(sphereAxis);

                        }

                    } );
                    console.log(object);
                    object.scale.set(1,1,1);
                    scene.add( object );

                } ); 
```

The object loads, and the axeshelper's are applied to each child mesh in the group.  What I'm noticing is that each child mesh occupies the same position and I'm assuming that the axishelper relies upon that position to place itself.  Is there a way I can redefine each child mesh's position after the fbx model is loaded and then apply the axeshelper to the child object?  So the child meshes have a position relative to the position of the group, and they don't all contain the same position of 0,0,0.

Is this a limitation of the fbx loader?  How should one achieve this?

Here's my summary of the issue on SO, as I wasn't sure if this was a three.js issue or user error:

* [StackOverflow](https://stackoverflow.com/questions/53158594/adding-three-js-axeshelper-to-all-children-of-group-axes-helper-position-defaul) 

##### Three.js version
- [ ] r97

##### Browser

- [x] All of them

##### OS

- [X ] macOS

**Comment by WestLangley** [comment]
>I wasn't sure if this was a three.js issue or user error:

This is not a three.js issue. Please get help at one of the help sites, instead.
