### ISSUE TITLE
BufferGeometryLoader can not  load userData from json file

### ISSUE THREAD

**Issue by huangdade** [mrdoob/three.js#15209]
BufferGeometry.toJSON export userData of BufferGeometry object. However, the BufferGeometryLoader can't load userData.

**Comment by Mugen87** [comment]
Would you like to do a PR with the fix? It should be an easy change.

**Comment by Mugen87** [comment]
I think you just have to add the following two lines before the return statement in `BufferGeometryLoader.parse()`.
```js
if ( json.name ) geometry.name = json.name;
if ( json.userData ) geometry.userData = json.userData;
```
In this way, we also fix the missing parsing of the `name` property.

**Comment by Mugen87** [comment]
Since @huangdade is not responding, I've create a small PR to fix the issue.
