### ISSUE TITLE
Some times aoMap or normalMap or bumpMap doesn't work. 

### ISSUE THREAD

**Issue by guozi110001** [mrdoob/three.js#15204]
I export scene from unity and everything seems well but some of the furnitures always  missing normalMap or aoMap effects. 
It looks like the pictures below:(left is unity effect and the right one is in threejs)
![normalmapbug](https://user-images.githubusercontent.com/21121957/47962226-9b2b9700-e054-11e8-807f-b34862ab58cd.jpg)
![aomapnormalmapbug](https://user-images.githubusercontent.com/21121957/47962228-a088e180-e054-11e8-9735-d25a9e6af065.jpg)

And the aoMap or normalMap is righthere as others do.Only three or two furnitures display unnormal.
![mapbugsconsole](https://user-images.githubusercontent.com/21121957/47962254-112ffe00-e055-11e8-9798-686759d7cac5.jpg)

Has anyone ever had this problem? Or anyone who can help me sove it .I need your help

**Comment by looeee** [comment]
Can you share a model that has this problem? Then we can investigate whether it's a bug or not.

**Comment by donmccurdy** [comment]
It may also help to know what exporter/formats you're using, and how many UV sets are in this model.

**Comment by guozi110001** [comment]
> Can you share a model that has this problem? Then we can investigate whether it's a bug or not.

Faile to upload. I put it on my server where you can download.Here is the address:[Sofa_LazySofa_003.zip](http://fancys.cn/upload_test/webgl/Sofa_LazySofa_003.zip)
Looking forward to your reply.

**Comment by guozi110001** [comment]
> It may also help to know what exporter/formats you're using, and how many UV sets are in this model.

I simulited ObjectLoader to write my own exporter and loader.They have good running . Other models have the normalMap effect normally either. I havn't find the differents between them.The Uvs looks like below:
![uvsinformation](https://user-images.githubusercontent.com/21121957/47973082-251f4280-e0dd-11e8-8204-1a283d8f5b3a.jpg)

**Comment by looeee** [comment]
> I simulited ObjectLoader to write my own exporter and loader.

We're not going to be able to help you to debug your own code here. 
If you export with a standard format such as glTF, FBX, OBJ, DAE etc and verify that the issue is still there then we can look into this further. 

Otherwise you can try asking for help over on the [forum](https://discourse.threejs.org/)/

**Comment by guozi110001** [comment]
Thank you for your suggestion.
