### ISSUE TITLE
Extrude geometry creates two disconnected surfaces

### ISSUE THREAD

**Issue by napter** [mrdoob/three.js#15218]
##### Description of the problem

When extruding [this SVG](https://dl.dropboxusercontent.com/s/gtv9pameg71pd01/test%20inkscape%20--%20direct%20reversed-in-code.svg?dl=0) of a shape with a hole, three of the extruded faces are connected but the fourth (the one extruded from the hole) is separate. Here are some screenshots to illustrate the issue:

The SVG is made up of two paths, the inner path is the hole:
![svg capture](https://user-images.githubusercontent.com/6260841/48111192-60755a80-e21e-11e8-9d83-49bfde3ce3b0.PNG)

The extrude creates two surfaces instead of one. The blue surface, made up of the outer wall, top and bottom, and the green surface, made up of the inner wall.
![stlcapture](https://user-images.githubusercontent.com/6260841/48111263-c235c480-e21e-11e8-9b89-b653439d3a2c.PNG)

Here I believe you can see part of the problem with the triangulation. The red vertex should connect to the blue vertex. The blue vertex is "non-manifold" it doesn't connect to another triangle on the top layer. 
![trianglecapture](https://user-images.githubusercontent.com/6260841/48111375-396b5880-e21f-11e8-8289-2412586cc3cf.PNG)

Here is the same surface after running a repair so that it is now a single surface. Note the two vertices from above are now connected.
![repairedcapture](https://user-images.githubusercontent.com/6260841/48111523-e80f9900-e21f-11e8-87e1-d5e5fb6a73d6.PNG)

Here is a [JS Fiddle](https://jsfiddle.net/nathanaa/efbjrx1t/9/) that reproduces the problem, you can see the triangulation problem here too if you zoom in on the same spot
![wirecapture](https://user-images.githubusercontent.com/6260841/48111589-37ee6000-e220-11e8-9bb4-196d46215722.PNG)

This is occurring with the latest dev branch (r98) as you can see in the fiddle.

**Comment by napter** [comment]
A note on this: The triangles above violate the following rule in the [STL specification](http://www.fabbers.com/tech/STL_Format): "Vertex-to-vertex rule. Each triangle must share two vertices with each of its adjacent triangles. In other words, a vertex of one triangle cannot lie on the side of another." A triangle vertex is lying on a side on the screenshots above, this occurs both it the mesh generated by ThreeJS from the extrude function and is also the case in an STL file exported by the STLExporter. 

Should the ThreeJS mesh follow the vertex-to-rule of the STL spec? If not, I assume the STL exporter should at least export a valid STL.

**Comment by WestLangley** [comment]
To clarify, on the path defining the hole, an additional vertex is inserted on each segment during the extrusion process.

Vertices of the Shape (the curved segments are on the outer edge)
![screen shot 2018-11-10 at 1 43 03 am](https://user-images.githubusercontent.com/1000017/48298380-82731500-e48a-11e8-9b50-2115fedd1cd9.png)


Vertices of the Extrusion
![screen shot 2018-11-10 at 1 42 17 am](https://user-images.githubusercontent.com/1000017/48298383-8e5ed700-e48a-11e8-9f1a-0e07dc637ed5.png)

**Comment by novogrammer** [comment]
I found same problem.
These surfaces create small noise.


```
var shape = new THREE.Shape();
shape.moveTo(-2,-2);
shape.lineTo(-2,2);
shape.lineTo(2,2);
shape.lineTo(2,-2);
shape.lineTo(-2,-2);

shape.moveTo(-1,-1);
shape.lineTo(1,-1);
shape.lineTo(1,1);
shape.lineTo(-1,1);
shape.lineTo(-1,-1);
```

![extrude disconnected surface](https://user-images.githubusercontent.com/912810/51545504-77365f80-1ea5-11e9-897b-5d38d0ba4749.png)

**Comment by WestLangley** [comment]
/ping @Mugen87 
/ping @yomboprime 
Any interest in pursuing this? Is this an `SVGLoader` issue or an extrusion issue?

**Comment by yomboprime** [comment]
Sincerely, I don't grasp the problem.

**Comment by WestLangley** [comment]
@yomotsu This is my understanding of the issue: Either in the loaded STL, or in the extruded geometry, or in both, the triangulation is invalid:

>"Vertex-to-vertex rule. Each triangle must share two vertices with each of its adjacent triangles. In other words, a vertex of one triangle cannot lie on the side of another."

So this is invalid.

![screen shot 2019-02-12 at 10 28 19 pm](https://user-images.githubusercontent.com/1000017/52684818-8e50f600-2f15-11e9-8393-09b5ea4266b2.png)

**Comment by yomboprime** [comment]
Thanks.

After debuggong a bit, I've seen that the second subpath (corresponding to the hole) has line segments with the start and end point equal (i.e., the line segment has degenerated into a point). This happens in 1 of every 2 line segments in the hole subpath.

Then, I've read the svg file and so it happens in it. For example, "L131.4, 132.3L131.4, 132.3". 

So I wonder if this is not a problem with the source SVG. I would ask @napter to check the svg, and if possible find a valid smaller svg that reproduces the error.
