### ISSUE TITLE
Use Object.assign in OBJLoader2

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#15227]
https://github.com/mrdoob/three.js/blob/36f9f34752a985359e2556c68a52234436cefdfa/examples/js/loaders/OBJLoader2.js#L513-L521

Should this be replaced with just?

     Object.assign(materials, materialCreator.materials);

According to MDN Object.assign doesn't exist in IE. Is it still a goal of THREE.js to support IE? If so maybe a similar function should be added to three (I'd vote for not supporting IE personally)

**Comment by greggman** [comment]
Actually `Object.assign` is polyfilled in `src/polyfills.js`

**Comment by kaisalmen** [comment]
Hi, yes this is likely not the only place. I will check `OBJLoader2` and `LoaderSupport` and make the code simpler where possible.

**Comment by Mugen87** [comment]
@kaisalmen It seems this issue is still relevant:

https://github.com/mrdoob/three.js/blob/8830252ad0ee3df8bc542b7a697f3310b6564b10/examples/jsm/loaders/obj2/worker/parallel/OBJLoader2Parser.js#L156-L164

**Comment by kaisalmen** [comment]
Thanks, I completely forgot about this one. It should be resolved in the mentioned commit.
