### ISSUE TITLE
Suggestion: modify use of transparent and opacity properties

### ISSUE THREAD

**Issue by ieskudero** [mrdoob/three.js#15230]
This is a suggestion about the use of the `transparent `and `opacity `properties of material. As it says in the documentation, `transparent ` must be set to true in order to make `opacity `work, but I think most of the people that sets `opacity < 0` assumes that the material is going to be translucent without doing anything else.

I didn´t searched a lot, but the documentation shows (or so I understand) that it can be because of the color transparency over material. If this is the only reason, shouln't `transparent `property be in color? or maybe material should have another property like `colorBlend`, instead of `transparent`.

I understand that `transparent `property is useful in material, but maybe it should be a read only property that returns `opacity < 1` ?

**Comment by WestLangley** [comment]
If `mesh.material.map` has a alpha channel that is less than 1, the mesh will be translucent -- even if `opacity` is 1. Translucent objects must be rendered after opaque ones.

A similar case occurs if the user is using a custom `ShaderMaterial` that sets alpha less than 1.

In those cases, a flag is required to signify "not opaque", ensuring proper rendering order.

For consistency, the flag is always required, even though transparency is implied when `opacity` is less than 1.

**Comment by ieskudero** [comment]
OK, I get it. I didn't though about the many cases where transparency can`t be detected easily, and I'm not sure if there is one way to set that flag automatically without hitting performance or complicating the code too much.

I will think about it.

Thanks for the explanation @WestLangley.
