### ISSUE TITLE
Update examples to use renderer.setAnimationLoop

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#15233]
Since `renderer.setAnimationLoop` was added a few months back, we should update most of the examples to use this.

It's cleaner, since it abstracts away the call to `requestAnimationFrame` and means that a minimal loop now can be done like this:

```js
function init() {

    var scene = ...
    var camera = ...
    var renderer = ...

    renderer.setAnimationLoop( function () {

        renderer.render( scene, camera );

    } );
}

init();
```

Instead of the current way:

```js

var scene, camera, renderer;

function init() {

    scene = ...
    camera = ...
    renderer = ...

}

function animate() {

    requestAnimationFrame( animate );

    renderer.render( scene, camera );

}

init();
animate();
```

If people agree, I'll start to work on converting the examples over the next couple of weeks.

**Comment by Mugen87** [comment]
TBH, I have never felt that the call of `requestAnimationFrame()` needs to be encapsulated. So I'm not sure it's worth the effort to adjust the entire code base...

**Comment by Mugen87** [comment]
We already have the VR guide that explains how to use `WebGLRenderer. setAnimationLoop()`. I think this is currently sufficient for the VR space.

https://threejs.org/docs/index.html#manual/en/introduction/How-to-create-VR-content

**Comment by mrdoob** [comment]
I think I like this. But I prefer this pattern:

```js
function init() {

    var scene = ...
    var camera = ...
    var renderer = ...

    renderer.setAnimationLoop( animation );

}

function animation() {

    renderer.render( scene, camera );

}

init();
```

**Comment by looeee** [comment]
> But I prefer this pattern:

That won't work, it would need to be:

``` js
var scene, camera, renderer;

function init() {

    scene = ...
    camera = ...
    renderer = ...

    renderer.setAnimationLoop( animation );

}

function animation() {

    renderer.render( scene, camera );

}

init();
```

Or, to avoid declaring the variables at the top:

```js
function init() {

    var scene = ...
    var camera = ...
    var renderer = ...

    renderer.setAnimationLoop( function () {

        animation( renderer, scene, camera );

    } );

}

function animation( renderer, scene, camera ) {

    renderer.render( scene, camera );

}

init();
```

**Comment by mrdoob** [comment]
> That won't work, it would need to be:

Oh yes, sorry. I meant to move the declarations outside but I forgot.

**Comment by Mugen87** [comment]
So this one, right?
```js
var scene, camera, renderer;

function init() {

    scene = ...
    camera = ...
    renderer = ...

    renderer.setAnimationLoop( animation );

}

function animation() {

    renderer.render( scene, camera );

}

init();
```
Okay, I'm fine with this. I hesitated at the beginning because we should not give the impression that every example is VR-ready (see https://github.com/mrdoob/three.js/issues/15233#issuecomment-437769812). Even if this change makes it easier to use the examples in VR, most demos are conceptually not designed to work well in this space.
