### ISSUE TITLE
Line.Clone Will cause an error

### ISSUE THREAD

**Issue by FishOrBear** [mrdoob/three.js#15239]
ref: https://github.com/mrdoob/three.js/pull/15062

If you are constructing a line, use Geometry
Then line.clone() will cause an error.

```
let l = new Line(new Geometry());
l.clone();
```

**Comment by Mugen87** [comment]
Related: https://discourse.threejs.org/t/error-when-changing-from-r97-to-r98/4905

**Comment by WestLangley** [comment]
```javascript
let l = new Line( new Geometry() );
```

A `BufferGeometry` is trying to copy a `Geometry`.


@Mugen87 Please link to #15064, instead.

**Comment by kheyse-oqton** [comment]
I also ran into this issue. Seems like a clear regression?

**Comment by Mugen87** [comment]
https://github.com/mrdoob/three.js/pull/15981 solved this issue.

Demo: https://jsfiddle.net/roxLkv3u/
