### ISSUE TITLE
How to calculate the depth of a world point in javascript?

### ISSUE THREAD

**Issue by dytmh** [mrdoob/three.js#15245]
How to calculate the depth value of a world point in javascript? 

Vector3 p;
p.project(camera);

p.z === gl_FragCoord.z ?

**Comment by Mugen87** [comment]
This is no help site. Please use the [forum](https://discourse.threejs.org/) or stackoverflow.

**Comment by Mugen87** [comment]
https://discourse.threejs.org/t/after-using-the-project-method-for-world-point-the-z-is-depth-value/4931
