### ISSUE TITLE
Threejs not working when imported via module

### ISSUE THREAD

**Issue by AncientChild** [mrdoob/three.js#15241]
##### Description of the problem
When trying to import threejs via another js-file my browser spits out an error-log telling me that it cant set THREE of undefined at line 4 of three.js. This undefined refers to global. When i load threejs via html-tag and set the type to module, i get the same behaviour. Therefore i assume that the problem appears because modules are set to strict behaviour by default, and your variable global might be referenced before it is declared as var/let/const. When including threejs via a "normal" html-tag without the type-attribute set to module, everything is working as expected.

##### Three.js version

- [ ] Dev
- [ ] r98
- [x] Master

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
Can you provide a demo? Note that there are [multiple builds](https://github.com/mrdoob/three.js/tree/dev/build) and only one is a valid ES module.

**Comment by AncientChild** [comment]
Wow. Missing that three.module.js was not my greatest achievement today. It would help though, if inside the documentation ( https://threejs.org/docs/#manual/en/introduction/Import-via-modules ) the import-statement would be changed accordingly, or there was some sentence pointing to the existence of a special build for the use as a module. I think otherwise other people could fall into the same trap as i did. (They might however notice the module-file before opening a git issue ;)

**Comment by mrdoob** [comment]
@AncientChild Would you like to submit a PR to the docs with the clarification?
