### ISSUE TITLE
WebGLTextures: Resize images just once 

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#15248]
look at this sequence of warnings:

![screen shot 2018-11-14 at 19 03 53](https://user-images.githubusercontent.com/242577/48502615-39cbab00-e840-11e8-8ded-4ba71470d521.png)

it does not look like it's intended

**Comment by Mugen87** [comment]
> it does not look like it's intended

What would be the intended behavior from your point of view?

**Comment by mrdoob** [comment]
Sure doesn't look right. Please, tell us more 🙂

**Comment by makc** [comment]
> What would be the correct behavior from your point of view?

I'm not sure, but it probably should not be doing the resize twice at least

**Comment by makc** [comment]
I guess a part of it is that code calling clampToMaxSize is ignoring mipmapping settings

**Comment by Mugen87** [comment]
Yeah. `clampToMaxSize()` does currently not check if a POT texture is needed. But if the function is enhanced in order to do so, there might be some redundant code. That's why I suggest to try to merge `clampToMaxSize()` and `makePowerOfTwo()`.

**Comment by mrdoob** [comment]
@Mugen87 sounds good 👌

**Comment by Mugen87** [comment]
We have a PR :tada:
