### ISSUE TITLE
out of memory in texture.tojson

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#15247]
this is probably edge case, but if you have many textures and try to export the scene on ios you get this:
![screen shot 2018-11-14 at 17 07 18](https://user-images.githubusercontent.com/242577/48499303-6e3b6900-e838-11e8-904e-592f27e240c1.png)
can we please re-use the canvas here? no need to create tons of canvases, right?

**Comment by Mugen87** [comment]
This is in `ImageUtils`, right?

https://github.com/mrdoob/three.js/blob/859993dab1aac5b03f694af9e0a1330e524f89d2/src/extras/ImageUtils.js#L23
