### ISSUE TITLE
MeshStandardMaterial & MeshPhysicalMaterial Lighting problem on Adreno GPU

### ISSUE THREAD

**Issue by MagicLM** [mrdoob/three.js#15244]
##### Description of the problem
MeshStandardMaterial & MeshPhysicalMaterial Lighting problem on Adreno GPU.

Not Adreno GPU
![image](https://user-images.githubusercontent.com/15254228/48467216-38d85080-e823-11e8-920e-b9a037189e00.png)

Adreno GPU
![image](https://user-images.githubusercontent.com/15254228/48467178-1f370900-e823-11e8-931c-29bd91b28a09.png)

live example:
* [codepen](https://codepen.io/magiclm/pen/WYpGyg?editors=1111) 

##### Three.js version

- [x] r98

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [x] Android

##### Hardware Requirements (graphics card, VR Device, ...)
- [x] Adreno GPU

**Comment by MagicLM** [comment]
@looeee 
Yes, I've been testing it for a long time and I don't know which part of the calculation is not compatible.But it's all good if you use a  **MeshPhongMaterial**.And I don't see the similar problem on **skechfab**,so it should be just MeshStandardMaterial & MeshPhysicalMaterial problem.

**Comment by Mugen87** [comment]
What happens if you set the precision property of the material to a lower value like so:
```js
material.precision = 'mediump';
```

**Comment by MagicLM** [comment]
@Mugen87 
if set
`material.precision = 'mediump';`
macOS
![image](https://user-images.githubusercontent.com/15254228/48478239-b067a900-e83e-11e8-92fb-aa5aa55de5d7.png)

iOS
![image](https://user-images.githubusercontent.com/15254228/48478201-8f06bd00-e83e-11e8-9647-8db676642a8c.png)

Android with Adreno 512 GPU
![image](https://user-images.githubusercontent.com/15254228/48478017-11db4800-e83e-11e8-8e21-be6be88b5dd4.png)

Android not Adreno GPU
![image](https://user-images.githubusercontent.com/15254228/48478632-d0e43300-e83f-11e8-92e3-9c5929fe63a3.png)

**Comment by Mugen87** [comment]
This might be a precision problem of the PBR materials in `three.js`.

Related: #14570

**Comment by MagicLM** [comment]
@Mugen87 
I think it should not be a problem of precision.
#### For high precision：
**iOS** is correct
**Android not Adreno GPU** is correct
**Android with Adreno GPU** is **incorrect**

----
#### For medium precision：
**iOS** is **incorrect**.
**Android not Adreno GPU**  is correct but looks just fuzzy.
**Android with Adreno GPU** is **incorrect** too.

----

**Comment by Mugen87** [comment]
We had multiple issues with Adreno GPUs in the past where the floating point precision was always the source of the problem e.g. #14137

**Comment by MagicLM** [comment]
But, **MeshPhongMaterial** is correct on all device.Does it use different precision?
I am just a beginner for shader : )

**Comment by Mugen87** [comment]
> Does it use different precision?

No. But `MeshStandardMaterial` and `MeshPyhsicalMaterial` do not work with `mediump` right now. #14570 tracks this issue.

**Comment by MagicLM** [comment]
@Mugen87 
`MeshStandardMaterial` and `MeshPyhsicalMaterial` also have rendering issues with `highp` on Adreno GPUs.
Do you mean Adreno GPUs use `mediump` default?
Now what can I do to deal with this problem? Any Suggestions? Thank you.

**Comment by Mugen87** [comment]
> Do you mean Adreno GPUs use mediump default?

Certain devices do not support `highp`. `mediump` is the maximum precision.

**Comment by MagicLM** [comment]
I found this code when I was looking at [adreno_opengl_es_developer_guide.pdf](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=2ahUKEwjRtbz5pdTeAhUL5bwKHdrGCUQQFjABegQIAhAC&url=https%3A%2F%2Fdeveloper.qualcomm.com%2Fqfile%2F28557%2F80-nu141-1_b_adreno_opengl_es_developer_guide.pdf&usg=AOvVaw1uhupVJVaKfaSyqW2f8bjh).
```
precision mediump float;
#ifdef GL_FRAGMENT_PRECISION_HIGH
     #define NEED_HIGHP highp
#else
     #define NEED_HIGHP mediump
#endif
varying  vec2 vSmallTexCoord;
varying NEED_HIGHP vec2 vLargeTexCoord;
```
Can modifications like this work?

**Comment by Mugen87** [comment]
This might be a part of the solution. But the actual challenge is to adjust stuff like lighting calculations so they still work with lower precision.

**Comment by MagicLM** [comment]
I hope it will be solved soon. [Sketchfab](https://sketchfab.com) has no problem there. Maybe we can learn from it.
I will try this plan tomorrow. Thank you for your answer. @Mugen87

**Comment by Mugen87** [comment]
Is it okay for you when I mark this issue as a duplicate and close it? The actual precision problem is already tracked here: #14570

**Comment by Mugen87** [comment]
Thanks for sharing your solution. It might be valuable when #14570 moves on.

**Comment by mrdoob** [comment]
FYI @bhouston @WestLangley https://github.com/mrdoob/three.js/issues/15244#issuecomment-440949378
