### ISSUE TITLE
GLTFLoader: minor optimization

### ISSUE THREAD

**Issue by andreasplesch** [mrdoob/three.js#15258]
##### Description of the problem

https://github.com/mrdoob/three.js/blob/d3bff25fc38c6143665b7ef482f2ebef3073b3af/examples/js/loaders/GLTFLoader.js#L1049-L1052

can be slightly optimized. Also see https://github.com/KhronosGroup/glTF/issues/1411#issuecomment-410356033

Rearranging to
```js
                var s2 = - 2 * ppp + 3 * pp;
		var s3 = ppp - pp;
                var s0 = 1 - s2;
		var s1 = s3 - pp + p;
```
saves three multiplications during each cubicspline animation frame. Still, not sure if worth it as this may not make a measurable difference.

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by andreasplesch** [comment]
http://jsben.ch/AY8VU

is a simplistic test which indicates a few percent performance gain.

**Comment by donmccurdy** [comment]
This looks good to me, could you open a PR?

**Comment by andreasplesch** [comment]
ok, I tested on 
https://bghgary.github.io/glTF-Assets-Viewer/?manifest=https://raw.githubusercontent.com/KhronosGroup/glTF-Asset-Generator/master/Output/Manifest.json&folder=0&model=5
with dev tools overrides since they are not many examples around.
PR #15275

**Comment by andreasplesch** [comment]
I tested http://jsben.ch/AY8VU on Linux Chrome and Firefox (60.3.0esr), and Windows Chrome, and Android Chrome. I can check Windows Firefox (release) later.

Hard to see how it could be slower ?

**Comment by donmccurdy** [comment]
Tested in Chrome, Firefox, and Safari. It wasn't consistent across multiple runs. Running the same test in Firefox repeatedly sometimes showed one or the other as faster. Safari was more consistent, with code block 2 being slightly faster. Overall the trend appears to be slightly faster, and intuitively that makes sense, so I'm happy with the PR.

**Comment by takahirox** [comment]
I think this type optimization should be done by JavaScript Engine. So weird Chrome becomes faster with this change. I know micro benchmark test sometimes doesn't fairly compare the performance. I'll write the test by myself and share the result.
