### ISSUE TITLE
Use standingMatrix in WebVR as an option

### ISSUE THREAD

**Issue by unilimes** [mrdoob/three.js#15250]
Now, if we use WebVR, we can't use matrix of camera, to control position of left/right cameras. Our idea is to add some flag in WebVRManager such as `.useStandingMatrix` to define which matrix will be used.

**Comment by MrMaksymov** [comment]
It would be cool, because sometimes you need to animate the camera, and doing it through the camera wrapper is not always convenient.

**Comment by tnormandao** [comment]
The reason why I did not use the solution out of the box, but began to reinvent my wheel.

**Comment by Mugen87** [comment]
WebVR support has been removed, see #18129.
