### ISSUE TITLE
webgl_shaders_ocean triggers warnings

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#15254]
##### Description of the problem
In the current `dev` commit of [webgl_shaders_ocean @ 1715e623ecf7b451bfef7f460cd7b2cb0828d9e6](https://rawgit.com/mrdoob/three.js/1715e623ecf7b451bfef7f460cd7b2cb0828d9e6/examples/webgl_shaders_ocean.html) I'm getting
```
[.WebGL-0x3830e6afbc00]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.
```
while in the current `master` [webgl_shaders_ocean @ 
 5360a81b8c557ed255e97b87c49e7d00b546b795](https://rawgit.com/mrdoob/three.js/5360a81b8c557ed255e97b87c49e7d00b546b795/examples/webgl_shaders_ocean.html) changing the `azimuth` or the `inclination` slider causes
```
[.WebGL-0x3830e6ba8100]GL ERROR :GL_INVALID_OPERATION : glDrawArrays:
Source and destination textures of the draw are the same.
```
Both of them > 255 times, i.e. `WebGL: too many errors, no more errors will be reported to the console for this context.` follows.

##### Three.js version

- [x] Dev (1715e623ecf7b451bfef7f460cd7b2cb0828d9e6)
- [x] r98 (5360a81b8c557ed255e97b87c49e7d00b546b795)

##### Browser

- [x] Chrome

##### OS

- [x] Linux

##### Hardware Requirements (graphics card, VR Device, ...)
Intel Core i7 integrated graphics, Intel something 4000? maybe 4500?

**Comment by moraxy** [comment]
Firefox `dev`
```
Error: WebGL warning: drawArrays:
Active texture 0 for target 0x8513 is 'incomplete', and will be rendered as RGBA(0,0,0,1),
as per the GLES 2.0.24 $3.8.2: Because the minification filter requires mipmapping,
the texture must be "mipmap complete".
```
Firefox `master`
```
Error: WebGL warning: drawArrays: Feedback loop detected between tex target 0x8513,
tex unit 0, levels 0-8; and framebuffer attachment 0x8ce0, level 0.
```

**Comment by Mugen87** [comment]
I can confirm these warnings. Although the title of your issue is misleading. The example is not "broken" since it produces the intended visual output with good performance.

**Comment by moraxy** [comment]
Oh sorry, I forgot the screen shots, the lighting is different, too:
![master](https://user-images.githubusercontent.com/4936897/48557912-3be94480-e8e8-11e8-8d09-4ec6e6decf1c.png)
![dev](https://user-images.githubusercontent.com/4936897/48557918-3ee43500-e8e8-11e8-98f9-d215ac7b1a73.png)
`dev` is the dark one. The sun-facing side is bright as usual in both versions.

**Comment by Mugen87** [comment]
Oh, I see. Yeah, the ico-sphere looks slightly different. Here are the links:

https://threejs.org/examples/webgl_shaders_ocean.html
https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_shaders_ocean.html

**Comment by Mugen87** [comment]
@moraxy Can you please verify the linked PR. It solves the visual difference between both versions...

**Comment by moraxy** [comment]
Lighting is fixed, thou the `glDrawArrays: Source and destination textures of the draw are the same.` is still there when playing with the sliders.

**Comment by Mugen87** [comment]
Thanks for testing! Yes, the warnings are caused by another issue. The lighting problem was introduced with #15236, hence the simple fix.
