### ISSUE TITLE
DirectionalLightHelper is broken

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#15260]
##### Description of the problem

The `DirectionalLightHelper` no longer points in the correct direction

// target is directly below light

```
    light.position.set(5, 10, 5);
    light.target.position.set(5, 5, 5);
    scene.add(light);
    scene.add(light.target);
```

r94 good : http://jsfiddle.net/greggman/kjfdpb94/

<img width="592" alt="screen shot 2018-11-16 at 17 05 41" src="https://user-images.githubusercontent.com/234804/48606061-e7b29300-e9c1-11e8-9163-b715402ff12d.png">

r98 bad: http://jsfiddle.net/greggman/trLb679p/

<img width="594" alt="screen shot 2018-11-16 at 17 06 30" src="https://user-images.githubusercontent.com/234804/48606099-00bb4400-e9c2-11e8-8d13-d47cfff31188.png">

##### Three.js version

- [x] Dev
- [x] r98

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
See #15200 and try the dev branch.
