### ISSUE TITLE
add dispose() to BufferAttribute

### ISSUE THREAD

**Issue by yaoyao-cn** [mrdoob/three.js#15261]
is it possible to add a dispose() method to BufferAttribute?

i need to dispose buffer attribute directly, not through the buffer geometry.
so i will change BufferAttribute and WebGLAttributes a bit, but i am not sure whether i am right.

i will change like this:
1.Make BufferAttribute as a sub classs of EventDispatcher to dispatch the dispose event
2.Handle dispose event in WebGLAttributes

am i right?  thank you !

##### Three.js version

- [x] Dev
- [ ] r98
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> i need to dispose buffer attribute directly, not through the buffer geometry.

Can you please explain your use case a bit? How does your workflow look like?

**Comment by yaoyao-cn** [comment]
@Mugen87 
ok, let me try to explain my workflow.

i am developing a GIS system like goole earth web and i need to render the whole earth with DOM and DEM. the earth is renderd through dynamic tiles which are subdivided autometically base on the camera distance.
every tile is a buffer geometry initialized with no buffer attributes and index buffer. the buffer attributes and index buffer are set by the tile manager every frame. so the shape of the tile can change every frame depending on the incoming DOM and DEM data from internet.

tiles are cached, every frame the tile manager pick some free tiles, set the buffer attribute, construct meshes(meshes are also cached) and then add the meshes to the threejs scene. after the render process, the tile manager remove the meshes from threejs scene and mark the tiles used as free tiles again.

in a word. meshes , buffer geometries and buffer attributes are separated objects for the system. the system know how to dispose all of them. buffer attributes and index buffers are shared between buffer geometries.

so, i need a dispose method of buffer attribute. just like the Texture.dispose() of material.

**Comment by Mugen87** [comment]
I think that sounds reasonable.

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/pull/17063#issuecomment-737993363.
