### ISSUE TITLE
How to render geometry which is out of projection window of camera 

### ISSUE THREAD

**Issue by panny3690** [mrdoob/three.js#15284]
Hi Team,

I am displaying Axes triad which is not zoom in/out on mouse operation, I am managing this code through shaders, which are projecting axes triads on correct location on 2D canvas but the located on (0,0,0) 3D location.

After zooming in or panning if 3D Point(0,0,0), goes out of camera projection window these axes are clipping abruptly.

Note: 3D Point position is 0,0,0 and two point position is different which is managed by shaders.

Probable solution 
1. Is there any setting with which geometry will always render on canvas?

Camera is Orthographic.

##### Three.js version

THREE.WebGLRenderer 90 (I dont think this version specific issue)

##### Browser

- [x] All of them
- [x] Chrome
- [x] Firefox
- [x] Internet Explorer

##### OS

- [x] Windows

**Comment by Mugen87** [comment]
This is not a help site. Please use stackoverflow or the [forum](https://discourse.threejs.org/).
