### ISSUE TITLE
VRMLLoader: fails to load wrl files of crystal models

### ISSUE THREAD

**Issue by colorzircon** [mrdoob/three.js#15281]
I'm a university teacher teaching Crystallography. I have built a lot of crystal models in .wrl format exported from WinXmorph and Krystalshaper, two software of crystal morphology drawing. These files can be opened correctly by many PC software.

Recently, I tried to share these models on web, so that my students could view them through the browser whatever using PC, Phone or Pad.
These .wrl files are much simpler than house.wrl, however, cannot be loaded by VRMLLoader.

I will be very appreciated if you can help me to solve the problem. It's very significant for me and my students.

Attachment is several entire files for testing.

Look forward to your reply.

[models for testing.zip](https://github.com/mrdoob/three.js/files/2597956/models.for.testing.zip)

**Comment by donmccurdy** [comment]
As a possible workaround, these files seem to open correctly in Blender and export with the same appearance using https://github.com/KhronosGroup/glTF-Blender-IO. I realize if you have a lot of files that may be too much work. Example:

[models for testing.zip](https://github.com/mrdoob/three.js/files/2598010/models.for.testing.zip)
![screen shot 2018-11-19 at 7 59 27 pm](https://user-images.githubusercontent.com/1848368/48750767-a7f3e180-ec35-11e8-884f-d5e353e5b300.png)

**Comment by colorzircon** [comment]
> As a possible workaround, these files seem to open correctly in Blender and export with the same appearance using https://github.com/KhronosGroup/glTF-Blender-IO. I realize if you have a lot of files that may be too much work. Example:
> 
> [models for testing.zip](https://github.com/mrdoob/three.js/files/2598010/models.for.testing.zip)
> ![screen shot 2018-11-19 at 7 59 27 pm](https://user-images.githubusercontent.com/1848368/48750767-a7f3e180-ec35-11e8-884f-d5e353e5b300.png)

Thank you very much for your prompt response. It's really an efficient method. 
But I don't know if there a way to display .glb files on web, because I try to enable them to be viewed through the browser using PC, Phone or Pad.

**Comment by donmccurdy** [comment]
You can definitely display the `.glb` files on web, yes — http://gltf-viewer.donmccurdy.com/ is an example, using [THREE.GLTFLoader](https://threejs.org/docs/#examples/loaders/GLTFLoader).

**Comment by colorzircon** [comment]
> You can definitely display the `.glb` files on web, yes — http://gltf-viewer.donmccurdy.com/ is an example, using [THREE.GLTFLoader](https://threejs.org/docs/#examples/loaders/GLTFLoader).

Thank you very much. The problem that has been bothering me for a long time has been solved.
![image](https://user-images.githubusercontent.com/35207803/48752682-73c80180-ecc5-11e8-82d6-dfeab92c6ba9.png)

Is there a way to batch convert .wrl to .glb in Blender？

**Comment by donmccurdy** [comment]
Yes, but it would require a bit of scripting ... see https://blender.stackexchange.com/questions/34537/how-to-batch-convert-between-file-formats. I haven't done this for VRML before but in theory you can just change a couple lines depending on the format.

**Comment by Mugen87** [comment]
I've tested one of your VRML files and found a couple of issue in `VRMLLoader`:

- the loader can't handle definitions of `ROUTE` so far (this produces a runtime error)
- the loader is not able to process `IndexedLineSet`
- the loader is not able to parse malformed VRML files. E.g. the current regular expressions are not able to parses lines like: `Transform{rotation 1 0 0 0.0 children[`

Solving all these issues is actually quite a lot of work^^

**Comment by Mugen87** [comment]
The commas are not the problem but the `children[` after the four quaternion values. But as you said, this is probably still valid VRML. The loader is just not able to parse it...

**Comment by Mugen87** [comment]
That said, even if the loader would be fixed, it still a much better solution to load the assets as `glTF` like @donmccurdy suggested.

**Comment by andreasplesch** [comment]
@colorzircon : You could also try https://github.com/create3000/x_ite (understands VRML fully) or https://github.com/x3dom/x3dom (understands X3D) . But this should be discussed elsewhere.

**Comment by colorzircon** [comment]
Thank you all very much, my warm friends.

Up to now, there are three ways to display `.wrl` files.

1.  using [THREE.GLTFLoader](https://threejs.org/docs/#examples/loaders/GLTFLoader) as @donmccurdy suggested.

2.  using [X3DOM.js](https://doc.x3dom.org/tutorials/index.html). `.wrl` file need to be convert to `html` [Instantreality](http://doc.instantreality.org/tools/x3d_encoding_converter/) supplies an online encoding converter and also local [PC software](http://www.instantreality.org/downloads/) converter.

3.  [X_ITE](http://create3000.de/x_ite/getting-started/) can directly load `.wrl` files without prior plugin installation.

**Comment by andreasplesch** [comment]
Oh, it looks like you have been already aware of alternatives. Apologies for the noise.

**Comment by colorzircon** [comment]
> Oh, it looks like you have been already aware of alternatives. Apologies for the noise.

Never mind！
Thank you very much for your suggestion.
