### ISSUE TITLE
Editor: list of objects in the right panel not dragging properly

### ISSUE THREAD

**Issue by RamCrodd** [mrdoob/three.js#15307]
The objects listed, in the right panel of the Editor, under the tab "Scene", are not dragging properly.

This behavior occurs when you have the Editor **locally** and running **on Chrome**, instead it is fine on Firefox.

(It is also fine in the Editor online with both Chrome and Firefox)

##### Three.js version

- [ ] Dev
- [x] r98
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> are not dragging properly.

What do you mean by that? Can you please explain a bit what's going wrong?

**Comment by RamCrodd** [comment]
For instance, if you try to make "Add -> Group" and then a couple of objects, and you want to group them, you should drag the two objects into the group object.

And it works only in the cases mentioned before:

![image](https://user-images.githubusercontent.com/11232347/48915990-e3ceb700-ee80-11e8-9718-10c047b08af4.png)

In the other cases mentioned before this is not working (they don't drag at all).

I hope this is less ambiguous.

**Comment by RamCrodd** [comment]
Noticed right now that on version **r99dev** it is **working**.

**Comment by Mugen87** [comment]
Then let's close the issue for now and consider it as fixed. We can reopen it you still experience the wrong behavior with the next release.
