### ISSUE TITLE
 THREE.TypedArrayUtils.Kdtree Insert Point

### ISSUE THREAD

**Issue by xjindf** [mrdoob/three.js#15300]
I would like to ask whether kdtree can add insert and remove methods. Thank you very much

**Comment by donmccurdy** [comment]
From the code, it "has no insert and remove" — https://github.com/mrdoob/three.js/blob/34dc2478c684066257e4e39351731a93c6107ef5/examples/js/TypedArrayUtils.js#L159-L183.

Do you need that functionality for something particular?

**Comment by xjindf** [comment]
Yes, I need to request the corresponding data list and add it to the BufferAttribute according to the current field of view. I hope kdtree is not unchanged. I believe that adding and deleting methods will be more applicable. Thank you very much.

**Comment by Mugen87** [comment]
`TypedArrayUtils` has been removed, see #20871.
