### ISSUE TITLE
PMREMGenerator flips the X axis when receiving a non CubeTexture

### ISSUE THREAD

**Issue by jsantell** [mrdoob/three.js#15301]
##### Description of the problem

When using a texture from WebGLRenderTargetCube (e.g. EquirectangularToCubeGenerator) with PMREMGenerator, the generated environment map does not match the environment, and is flipped on the X axis, unlike when using a CubeTexture.

This can be recreated [in the EXR example](https://threejs.org/examples/?q=exr#webgl_materials_envmaps_exr) and:

```
scene.background = cubemapGenerator.renderTarget;
//cubemapGenerator.dispose();
```

![screenshot from 2018-11-21 15-45-11](https://user-images.githubusercontent.com/641267/48876890-80c41e00-edb5-11e8-8be9-fde636b80712.png)
![screenshot from 2018-11-21 15-42-23](https://user-images.githubusercontent.com/641267/48876902-90436700-edb5-11e8-87d9-5ca9150a0b83.png)

##### Three.js version

- [x] Dev
- [ ] r98
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Yes. I believe the following statements are true:

In `webgl_materials_envmaps_hdr`, reflections are correct, but the PMREM Cube_UV map tiles are mirrored.

in `webgl_materials_envmaps_exr`, reflections are mirrored, but the PMREM Cube_UV map tiles are correct.
