### ISSUE TITLE
if scene use skybox , then mesh material disable depthTest and  depthWrite no show

### ISSUE THREAD

**Issue by dytmh** [mrdoob/three.js#15304]
If the scene uses skybox via `scene.background`, it's not possible to see the mesh when `depthTest` and `depthWrite` of its materials is set to `false`.

```js
envMap = new THREE.CubeTextureLoader()
.setPath( 'textures/cube/skyboxsun25deg/')
.load( [ 'px.jpg', 'nx.jpg', 'py.jpg', 'ny.jpg', 'pz.jpg', 'nz.jpg' ] );
scene.background = envMap;

var lineMaterial = new THREE.MeshBasicMaterial();
lineMaterial.color.setHex( 0xDAA520 );
material.depthTest = false;
material.depthWrite = false;

var lineGeometry = new THREE.BoxBufferGeometry( 10, 10, 10 );
var lineEntity = new THREE.Mesh( lineGeometry, lineMaterial );
scene.add( lineEntity );
```
![image](https://user-images.githubusercontent.com/4333197/48887077-0bb22080-ee69-11e8-84e8-c62fc0798f74.png)
##### Three.js version

- [x] Dev
- [x] r98
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Fiddle for reproduction: https://jsfiddle.net/f2Lommf5/16063/

I guess you expect to see the cube although `depthTest` and `depthWrite` is set to `false`, right?

**Comment by Mugen87** [comment]
As a workaround, create you skybox like in this fiddle: https://jsfiddle.net/f2Lommf5/16064/

```js
var cubeShader = THREE.ShaderLib[ 'cube' ];
cubeShader.uniforms[ 'tCube' ].value = envMap;
			
var skyBoxMaterial = new THREE.ShaderMaterial( {
    fragmentShader: cubeShader.fragmentShader,
    vertexShader: cubeShader.vertexShader,
    uniforms: cubeShader.uniforms,
    side: THREE.BackSide
} );
	
var skyBox = new THREE.Mesh( new THREE.BoxBufferGeometry( 1000, 1000, 1000 ), skyBoxMaterial );
scene.add( skyBox );
```

**Comment by WestLangley** [comment]
>it's not possible to see the mesh when depthTest and depthWrite of its materials is set to false.

If the background is rendered last of the opaque objects, it will overwrite other scene elements rendered with `depthWrite = false`.

I don't think `depthTest` is relevant to this issue.

Perhaps the background should be rendered first.

**Comment by Mugen87** [comment]
I think the following issue is related to this one: #14006

**Comment by mrdoob** [comment]
> Perhaps the background should be rendered first.

Yeah... The fact that it renders last is supposed to be to avoid drawing pixels twice. It's a optimisation that keeps bumping into cases where it creates issues.

I agree, we should change it so it renders first. It'll be better to favour something robust better than something optimal but delicate.

**Comment by aardgoose** [comment]
Can't think of  anything that isn't hacky.

We could put the background objects in the renderList before the sort process and then use renderOrder to position it relative to other objects in the list with a known high value, to allow objects to override to control ordering.  Feels very fragile, but maintains the optimisation for most cases.

**Comment by WestLangley** [comment]
@aardgoose Would you be willing to try, anyway. :-)

**Comment by mrdoob** [comment]
@WestLangley should I change it so `WebGLBackground` renders first in the meantime?

**Comment by WestLangley** [comment]
Sure. What is your technique to achieve that?

**Comment by mrdoob** [comment]
Hmm... changing the `.pop()` for a `.unshift()` [here](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLBackground.js#L89)?
And passing the transparent objects render list instead?
