### ISSUE TITLE
GLTFLoader: Skinned meshes distorted

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#15319]
##### Description of the problem

I've realized that certain glTF models like the small robot or the cesium man look distorted in `dev`. Could this be related to the latest changes to `SkinnedMesh`?

Check out the hands of the robot:
https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_animation_skinning_morph.html

and the torso of the cesium man:
https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_loader_gltf_extensions.html

The skinning example of `FBXLoader` and `ColladaLoader` looks fine. Same for the [webgl_animation_skinning_blending](https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_animation_skinning_blending.html) which uses `GLTFLoader`.

##### Three.js version

- [x] Dev
- [ ] r98
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
oh no 😅

<img width="200" alt="screen shot 2018-11-26 at 10 36 13 am" src="https://user-images.githubusercontent.com/1848368/49026897-fee54380-f16c-11e8-8edc-46c91cc3af48.png">

**Comment by donmccurdy** [comment]
PR https://github.com/mrdoob/three.js/pull/15314/ removed the call to `normalizeSkinWeights()` in the constructor. If I add that back, it fixes the issue for the robot model. Weights in these models are supposed to be normalized already, and at some point the glTF validator will warn about it if not. So, if there's a performance benefit to skipping the normalization by default we can try to correct the models.

**Comment by Mugen87** [comment]
> PR #15314 removed the call to normalizeSkinWeights() in the constructor.

Um, I think I would add it back for now. We can still remove the call of this method at a later point.

**Comment by mrdoob** [comment]
What's wrong with these models? They look correct to me 😜

Instead of adding the `normalizeSkinWeights()` back in `SkinnedMesh`, I would add the call in `GLTFLoader` instead.

**Comment by Mugen87** [comment]
> Instead of adding the normalizeSkinWeights() back in SkinnedMesh, I would add the call in GLTFLoader instead.

:+1:

**Comment by zeux** [comment]
GLTF spec says:

> The joint weights for each vertex must be non-negative, and normalized to have a linear sum of 1.0. No joint may have more than one non-zero weight for a given vertex.

The side-effect of normalizeSkinWeights is that models with UNSIGNED_BYTE normalized=true vertices are broken because the normalization divides all weights by ~255.

**Comment by donmccurdy** [comment]
Thank you @zeux! 

I'd be happy to see that `normalizeSkinWeights()` call removed – as you say, spec-conformant models do not need it. Unfortunately we'll get bug reports from confused users if we do, and it will be difficult to help them – incorrect weights are arguably more common than UNSIGNED_BYTE weights today. 

It will help for glTF validator to begin warning about incorrect skin weights (https://github.com/KhronosGroup/glTF-Validator/issues/58), both so that users can diagnose this and so existing exporters will fix bugs. Once that happens, I'm OK with removing this use of `normalizeSkinWeights` entirely. Until then, it seems OK to only apply it when weights are floating-point.

/cc @bghgary should glTF-Asset-Generator cover skin weights with different component types?

/cc @lexaknyazev

**Comment by zeux** [comment]
I have a patch that only normalizes floating-point weights, will submit a PR momentarily. Seems like a reasonable compromise.

**Comment by bghgary** [comment]
> should glTF-Asset-Generator cover skin weights with different component types?

You mean like this? 🤔

https://github.com/KhronosGroup/glTF-Asset-Generator/blob/master/Output/Positive/Animation_SkinType/README.md

**Comment by zeux** [comment]
@bghgary This is actually a perfect example :) It shows THREE.js not handling BYTE weights at the moment. #16611 should fix this.

**Comment by donmccurdy** [comment]
> You mean like this? 🤔

Exactly like that. Guess I need to go through those tests more closely. 😅
