### ISSUE TITLE
WebGLBackground only uses first encountered texture encoding

### ISSUE THREAD

**Issue by jsantell** [mrdoob/three.js#15325]
##### Description of the problem

I've been attempting to use `scene.background` with cubemaps since they've just landed recently and uncovered an issue with encodings (filing an issue for corresponding PR #15299).

Currently, when texture is set on `scene.background`, the background material is compiled with the current texture defining the encoding via `mapTexelToLinear`. Changing `scene.background` with a different texture that uses a different encoding results in the new background using the encoding from the first texture. Infact, all scenes using the renderer will be encoded with whatever the initial background texture was.

This is reproducible in the HDR/EXR examples with some small changes (found in #15299). For instance, in the HDR example, if setting the LDR texture to be displayed first, the subsequently loaded HDR texture is rendered like this (pixellation is a different known issue in these examples?):

![img](https://user-images.githubusercontent.com/641267/48872093-83664980-ed9c-11e8-9380-a18eb6bd42c4.png)

##### Three.js version

- [x] Dev
- [ ] r98
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Would setting `material.needsUpdate = true` when the background texture is different solve this?

**Comment by jsantell** [comment]
@mrdoob The material itself is only accessible to WebGLBackground, and background texture equality check is insufficient, in the case where encoding is set after the loading of a texture
