### ISSUE TITLE
EXRLoader is not working on Samsung Galaxy S8

### ISSUE THREAD

**Issue by silvainSayduck** [mrdoob/three.js#15343]
##### Description of the problem

I noticed that the `EXRLoader` is not working on (at least) Samsung Galaxy S8. This example https://threejs.org/examples/webgl_materials_envmaps_exr.html renders as completely black, as can be seen on this screenshot: ![EXR_not_supported](https://i.imgur.com/WKTY0J7.png)

The console shows the following errors
```
THREE.WebGLRenderer 98
three.js:15111 THREE.WebGLRenderer: OES_texture_float extension not supported.
three.js:15111 THREE.WebGLRenderer: OES_texture_half_float extension not supported.
three.js:15111 THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.
three.js:15111 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
three.js:15111 THREE.WebGLRenderer: EXT_texture_filter_anisotropic extension not supported.
three.js:15111 THREE.WebGLRenderer: EXT_shader_texture_lod extension not supported.
44WebGL: INVALID_ENUM: texImage2D: invalid type
43[.WebGL-0xcc23c400]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
169[.WebGL-0xcc23c400]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
webgl_materials_envmaps_exr.html:1 WebGL: too many errors, no more errors will be reported to the console for this context.
````

I have read on some other issue that this might be limited to Samsung phones due to the lack of some of those extensions. Is there any way around this? 

This other HDR example is working fine: https://threejs.org/examples/?q=hdr#webgl_materials_envmaps_hdr

Although it shows the same warnings:
```
THREE.WebGLRenderer 98
three.js:15111 THREE.WebGLRenderer: OES_texture_float extension not supported.
three.js:15111 THREE.WebGLRenderer: OES_texture_half_float extension not supported.
three.js:15111 THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.
three.js:15111 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
three.js:15111 THREE.WebGLRenderer: EXT_texture_filter_anisotropic extension not supported.
three.js:15111 THREE.WebGLRenderer: EXT_shader_texture_lod extension not supported.
```

##### Three.js version

- [ ] Dev
- [x] r98
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Comment by silvainSayduck** [comment]
I have figured out a workaround (albeit probably not a very good one) for now, for Android phones:

```js
new EXRLoader().load(envMap, (dataTexture) => {
  let texture;
  if (isAndroid) {
    const imageData = new ImageData(new Uint8ClampedArray(dataTexture.image.data.map((value) => value * 255)), dataTexture.image.width, dataTexture.image.height);
    texture = new THREE.Texture(imageData);
    texture.needsUpdate = true;
  }
  ...
}
```

**Comment by Mugen87** [comment]
Should be solved via #17887. `EXRLoader` always returns an instance of `DataTexture` with `RGBAFormat`.

**Comment by robertoranon** [comment]
Hi, 

  the EXR loader example currently online (https://threejs.org/examples/#webgl_loader_texture_exr) does not work with Samsung S10, S9, S8 .... black texture, as reported at the beginning of this thread

**Comment by mrdoob** [comment]
I've tested the `EXRLoader` examples on a Galaxy S8 (SM-G950U1)

https://threejs.org/examples/#webgl_loader_texture_exr

![Screenshot_20200703-141417_Chrome](https://user-images.githubusercontent.com/97088/86497778-f7146900-bdbd-11ea-81a4-03ccf6f7b024.jpg)

https://threejs.org/examples/#webgl_materials_envmaps_exr

![Screenshot_20200703-141100_Chrome](https://user-images.githubusercontent.com/97088/86497814-101d1a00-bdbe-11ea-9ffb-75caa6f2d036.jpg)

**Comment by robertoranon** [comment]
my tests were done using the S8, S9, S10 on browserStack

**Comment by mrdoob** [comment]
I see. Can you report the issue to browserStack then?

**Comment by robertoranon** [comment]
Wait, I'll see your flawless Galaxy S8 and raise you another problematic Galaxy S8+ :)

Black screen on Galaxy S8+ (SM-G955F), Android 9, Chrome 83, Mali G71. Probably the loader works for some combination of android/chrome/gpu and not others ...

Regarding browserStack, I might be wrong, but was under the impression that when you use their service your are working with real devices and not some emulation ... am I wrong?

**Comment by robertoranon** [comment]
This is the console on the browserStack S8:

three.module.js:16709 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
three.module.js:16709 THREE.WebGLRenderer: EXT_texture_filter_anisotropic extension not supported.
webgl_loader_texture_exr.html:1 [.WebGL-0xc6f64900]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?

**Comment by mrdoob** [comment]
Unfortunately, I can't afford to buy every single device 😕

**Comment by robertoranon** [comment]
I know, it's pretty much impossible to test everything ... well I think just letting people know that there can be problems with this loader and some android devices is better than nothing
