### ISSUE TITLE
GLTFExporter doesn't support InterleavedBuffer

### ISSUE THREAD

**Issue by andrewvarga** [mrdoob/three.js#15349]
##### Description of the problem

InterleavedBufferAttribute is not supported by GLTFExporter currently.
There is a comment which verifies this:
```
// @TODO Fails on InterleavedBufferAttribute, and could probably be
// optimized for normal BufferAttribute.
```

I'm happy to implement this, but I wanted to create an issue first to make sure the issue is visible, it's not currently being worked on and everyone is notified about the progress about it.

##### Three.js version

r98

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by donmccurdy** [comment]
Agreed it would be nice to support this. I haven't worked on it yet, but note https://github.com/mrdoob/three.js/pull/15348 does affect that code a little bit. If you're able to open a PR that would be great thanks!

/cc @takahirox @fernandojsg

**Comment by andrewvarga** [comment]
Thanks for the heads up. Can I regard the the code within #15348 as the most up to date version of the exporter, ie. can I base my updates on top of that?

**Comment by donmccurdy** [comment]
Depends on how comfortable you are with Git rebasing later 😅 I think we can get the other PR merged soon though.

**Comment by fernandojsg** [comment]
+1 to a PR adding support for it! ^_^

**Comment by makc** [comment]
I am currently using following code to fix this:

![Screen Shot 2019-03-27 at 3 32 05 ](https://user-images.githubusercontent.com/242577/55046269-38598d00-5041-11e9-89aa-f974f68c5ddd.png)

Let me know if I am missing anything else.

**Comment by Mugen87** [comment]
Fixed via 39fbd2c3d0dbf0f42a3c3fe486b39b6447ab270b and 1969817095dd2a3df8fe6b30fccb5918f9c20c96.

**Comment by Mugen87** [comment]
If interleaved data should be retained in the produced `glTF` asset, it's best to make a new issue.

**Comment by makc** [comment]
@Mugen87 why itemSize check is > 3 and not > 4

**Comment by Mugen87** [comment]
Using 4 is of course better. Fixing...
