### ISSUE TITLE
add camera to object3d, position double

### ISSUE THREAD

**Issue by yinhunfeixue** [mrdoob/three.js#15342]
The following code
![image](https://user-images.githubusercontent.com/29660825/49196097-811b7500-f3c4-11e8-8e34-e669fba50af2.png)

unset cube's position
![image](https://user-images.githubusercontent.com/29660825/49196065-647f3d00-f3c4-11e8-976b-9eb6d127d87f.png)

after set position
![image](https://user-images.githubusercontent.com/29660825/49196118-a3ad8e00-f3c4-11e8-9bd9-a032db48d5f1.png)

display
![image](https://user-images.githubusercontent.com/29660825/49196135-b32cd700-f3c4-11e8-956b-e0895cf68fa0.png)

Why did the camera move twice as far？

**Comment by WestLangley** [comment]
Correct. `CameraHelper` must be a child of the scene.

I am not sure if `CameraHelper` works correctly if the camera is a child of a translated object.

**Comment by looeee** [comment]
Probably OK if we just add a note to the docs about this. Does this apply to all helpers, or just this one?

**Comment by WestLangley** [comment]
`Object3D.lookAt()` now supports hierarchies; it used to ignore the parents' transform. Consequently, some helpers needed to be modified -- others may need to be, too.

I think it is safe to say that a helper should be added as a child of the scene.

**Comment by Mugen87** [comment]
Since the original question of the OP was answered, it's better to close the issue. Feel free to create a new issue if something in context of helpers needs to be refactored or changed.
