### ISSUE TITLE
GLTFExporter: Support spec/gloss PBR materials

### ISSUE THREAD

**Issue by tiancaipipi110** [mrdoob/three.js#15351]
Hello, I'm using GLTFLoader to import the .gltf models, then use gltf exporter to export them. 

However some materials are only able to be displayed, but unable to be exported.  It seems like three.js has a couple of built-in materials+ shader materials. gltf loader seems to create shader materials as far as three.js built-in materials do not cover what' s in gltf file. now gltf exporter does not support exportinng shader materials. and from here we have a problem.

Can anyone help with this? Thanks.

**Comment by makc** [comment]
I imagine that for th proper fix gltfloader would need to create its own material type, instead of ShaderMaterial. Then exporter could easily export it.

**Comment by looeee** [comment]
> glTF has three material modes:

> * unlit
> * metal/rough PBR
> * spec/gloss PBR

Perhaps we should support spec/gloss PBR directly in three.js?

**Comment by makc** [comment]
@looeee which is what I said, basically, but `material.isGLTFSpecularGlossinessMaterial` could work, too

**Comment by donmccurdy** [comment]
I'm certainly not opposed to adding a spec/gloss PBR material to the core materials. We've discussed that a bit in https://github.com/mrdoob/three.js/issues/10985 and https://github.com/mrdoob/three.js/pull/11038, and that would solve the fact that GLTFSpecularGlossinessMaterial can't be cloned (although https://github.com/mrdoob/three.js/pull/14099 might also achieve that?). But the difference between these two PBR materials, and MeshPhysicalMaterial for that matter, is not likely to be obvious to most users. So there is an argument for keeping it 'tucked away' in GLTFLoader, too.

I believe GLTFExporter can be fixed to support spec/gloss either way.

**Comment by looeee** [comment]
> But the difference between these two PBR materials, and MeshPhysicalMaterial for that matter, is not likely to be obvious to most users. 

As a counterargument, many users will come to three.js already familiar with PBR, or want to bring in assets authored in Substance Painter or other programs using spec/gloss, and find it frustrating that only one of the standard PBR pathways is supported. 

It's not trivial to [convert spec/gloss maps to metal/roughness](https://marmoset.co/posts/pbr-texture-conversion/), meaning that many PBR assets cannot be (easily) three.js at the moment.

**Comment by RemusMar** [comment]
There is no perfect workflow, but this one is the probably the best:
https://github.com/BabylonJS/Exporters/issues/269

**Comment by donmccurdy** [comment]
@takahirox or @fernandojsg would you have time to look at exporting spec/gloss materials from GLTFExporter by any chance?
