### ISSUE TITLE
Issues with Cinema4D FBX models

### ISSUE THREAD

**Issue by pikilipita** [mrdoob/three.js#15358]
animated fbx models exported from Cinema4D used to load perfectly with the fbx loader version back from 04/2018, with with latest version of the loader, meshes are all over the place.

Fbx models exported from Blender are not affected bu this issue.

Here's an example model having this issue ( look at the character hands )
[https://lune.live/forums/cinema4d-bug.fbx.zip](url)

The patch proposed in this issue [https://github.com/mrdoob/three.js/issues/15354](url) makes things a bit better for cinema4D fbx files, but not as perfect as it is used to be.

Tested on Threejs r99 and fbx loader as of 02/12/2018

**Comment by looeee** [comment]
I am aware of this and other related issues but I have a considerable backlog of work at the moment so I'm not sure when I'll have time to investigate.

**Comment by looeee** [comment]
This was fixed in #19093
