### ISSUE TITLE
Chrome version 70 WebM, always does not clean up historical images

### ISSUE THREAD

**Issue by liaohengfan** [mrdoob/three.js#15359]
##### Description of the problem
In the Chrome browser version 70.0.3538.110, using VideoTexture, video format WebM, always do not clean up the historical image, the display content has been superimposed, and there is no problem in the chrome 69 version, this situation makes me very trouble, thank you.
E-mail: liaohengfan@yeah.net

##### Three.js version
- [ ] ...

##### Browser
- [ ] Chrome

##### OS
- [ ] Windows
# #

**Comment by Mugen87** [comment]
Please report this issue right here: https://bugs.chromium.org/p/chromium/issues/list

**Comment by liaohengfan** [comment]
I may not express this problem clearly. The actual situation is to use WebM as the source of Videotexture in three.js. The texture rendered has all the historical content of the video, not just the current frame of the video. I will also Feedback on chormium, thank you
