### ISSUE TITLE
Documentation: Clearer description of displacementScale in 

### ISSUE THREAD

**Issue by kristoffer-dyrkorn** [mrdoob/three.js#15363]
I have a suggestion for a clearer description of the displacementScale property in the MeshPhongMaterial object.

Applies to the documentation for r99.

The text is now:

> How much the displacement map affects the mesh (where black is no displacement, and white is maximum displacement). Without a displacement map set, this value is not applied. Default is 1.

My suggestion is:

> Mesh vertices will be displaced depending on the intensity of the pixels (black is no displacement,  white is maximum displacement). This property defines how far, measured in local coordinate units, a vertex will move when maximally displaced. The default value is 1.

Am open for other ideas as well.

**Comment by Mugen87** [comment]
@kristoffer-dyrkorn TBH, I don't think your suggestion is an improvement. It's not clear from your text that `displacementScale` modulates the value sample from the displacement map. This is more clear in the current description.

**Comment by kristoffer-dyrkorn** [comment]
Ah. In that case my suggestion was not that clearer :)
