### ISSUE TITLE
Can I draw 200,000 2d rectangles

### ISSUE THREAD

**Issue by FeiVincent** [mrdoob/three.js#15377]
##### Description of the problem

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/3foLr7sn/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/qgu17w5o/) (dev branch)
* [codepen](https://codepen.io/anon/pen/aEBKxR) (latest release branch)
* [codepen](https://codepen.io/anon/pen/BJWzaN) (dev branch)

##### Three.js version

- [ ] Dev
- [ ] r99
- [x] r96
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

I want to draw a lot of rectangle boxes, and now I use the BufferGeometry, but I have to set eight position points, can I use four vertex coordinates to draw the rectangle box

```
const lineBuffer = new THREE.BufferAttribute(new Float32Array(rectCount * 8 * 3), 3);
    let x, y, w, h;
    let ax, ay, bx, by, dx, dy, cx, cy, index;
    const z = 0;
    for (let i = 0; i < rectCount; i++) {
      x = data[i][0];
      y = data[i][1];
      w = data[i][2];
      h = data[i][3];

      ax = x;
      ay = y;
      bx = x + w;
      by = y;
      dx = x + w;
      dy = y + h;
      cx = x;
      cy = y + h;
      index = i * 8;
      // 几何体八个顶点的x,y,z坐标
      lineBuffer.setXYZ(index + 0, ax, ay, z); // a
      lineBuffer.setXYZ(index + 1, bx, by, z); // b
      lineBuffer.setXYZ(index + 2, bx, by, z); // b
      lineBuffer.setXYZ(index + 3, dx, dy, z); // d
      lineBuffer.setXYZ(index + 4, dx, dy, z); // d
      lineBuffer.setXYZ(index + 5, cx, cy, z); // c
      lineBuffer.setXYZ(index + 6, cx, cy, z); // c
      lineBuffer.setXYZ(index + 7, ax, ay, z); // a
    }
    const rectLineGeometry = new THREE.BufferGeometry();
    rectLineGeometry.addAttribute('position', lineBuffer);
    const lineMaterial = new THREE.LineBasicMaterial({
        color: 0x000000,
        linewidth: 2
      });
    lineMaterial.depthTest = false;
   const lines = new THREE.LineSegments(rectLineGeometry, lineMaterial);
   scene.add(lines);
```
I can draw a lot of rectangles this way, but I want to drag and drop one of them, which I can't do right now

**Comment by looeee** [comment]
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
