### ISSUE TITLE
about postprocessing ,canvas context imagedata always black

### ISSUE THREAD

**Issue by deyihu** [mrdoob/three.js#15371]
##### about postprocessing ,canvas context imagedata  always black
when set  WebGLRenderer **alpha=true**

https://jsfiddle.net/f2Lommf5/16257/

```javascript
    renderer = new THREE.WebGLRenderer( { antialias: true ,alpha: true} )
```
canvas context  imagedata is transparent

![3](https://user-images.githubusercontent.com/25998927/49426442-8cfba280-f7db-11e8-94c6-af919ec17c11.png)

but use postprocessing  canvas context image always black
https://jsfiddle.net/f2Lommf5/16258/

![5](https://user-images.githubusercontent.com/25998927/49426583-f7acde00-f7db-11e8-87ae-13b0ba66ab5a.png)

Then I try.
https://jsfiddle.net/f2Lommf5/16259/
```javascript
 var renderScene = new THREE.RenderPass( scene, camera ,null,new THREE.Color('red'),0);

```
 canvas context  imagedata still black

I hope when postprocessing   canvas context   imagedata is transparent,I can save canva as transparent image.
What should I do?

##### Three.js version

- [ ] Dev
- [x] r99
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome 68
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows 10
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This is not a help site. Please use the [forum](https://discourse.threejs.org/) or stackoverflow.
