### ISSUE TITLE
ShapeGeometry does not handle CW boundary with CW holes

### ISSUE THREAD

**Issue by jgg3** [mrdoob/three.js#15388]
##### Description of the problem

ShapeGeometry includes a section of code to correct the traversal direction of the boundary and holes.  But it is written such that the holes are only corrected if the boundary is _not_ clockwise.  This results in failure in the case where the boundary is clockwise and the holes are clockwise.

The hole corrections should be independent of the outside boundary correction.

![capture](https://user-images.githubusercontent.com/20710907/49603028-159f4d80-f958-11e8-96d0-3d1eb8de68c3.JPG)

##### Three.js version

- [ ] Dev
- [x] r99
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
>The hole corrections should be independent of the outside boundary correction.

I am inclined to agree. Would you like to file a PR to fix it?
