### ISSUE TITLE
Improve visual of PlaneHelper

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#15396]
This is just simple suggestion to improve visual of PlaneHelper:
Should we remove some redundant INNER egdes like this?
```

	function PlaneHelper( plane, size, hex ) {

		this.type = 'PlaneHelper';

		this.plane = plane;

		this.size = ( size === undefined ) ? 1 : size;

		var color = ( hex !== undefined ) ? hex : 0xffff00;

		var positions = /*[ 1, - 1, 1, - 1, 1, 1, - 1, - 1, 1,*/[ 1, 1, 1
		, - 1, 1, 1
		, - 1, - 1, 1
		, 1, - 1, 1
		, 1, 1, 1
		//, 0, 0, 1
		];

		var geometry = new BufferGeometry();
		geometry.addAttribute( 'position', new Float32BufferAttribute( positions, 3 ) );
		geometry.computeBoundingSphere();

		Line.call( this, geometry, new LineBasicMaterial( { color: color } ) );

		//

		var positions2 = [ 1, 1, 1, - 1, 1, 1, - 1, - 1, 1, 1, 1, 1, - 1, - 1, 1, 1, - 1, 1 ];

		var geometry2 = new BufferGeometry();
		geometry2.addAttribute( 'position', new Float32BufferAttribute( positions2, 3 ) );
		geometry2.computeBoundingSphere();

		this.add( new Mesh( geometry2, new MeshBasicMaterial( { color: color, opacity: 0.2, transparent: true, depthWrite: true } ) ) );

		this.lookAt( this.plane.normal );
	}
```

**Comment by Mugen87** [comment]
So instead of:

![image](https://user-images.githubusercontent.com/12612165/49685677-e3245a80-fae7-11e8-8177-e5d5db0c953f.png)

the new code produces this:

![image](https://user-images.githubusercontent.com/12612165/49685674-d6a00200-fae7-11e8-8ff3-87be9b6bbdb9.png)

Not sure about this change. TBH, I think the current visual about is already appropriate.

**Comment by WestLangley** [comment]
@whatisor I understand your concern, but with this PR, when you zoom in close to the plane, nothing is visible. That is why I included the diagonals in the first place.

**Comment by whatisor** [comment]
@WestLangley ,yeah, that is good for debugging, but not good for final development. I think no one wants to display surface with diagonals :D

**Comment by mrdoob** [comment]
> I think no one wants to display surface with diagonals :D

Actually, I think it would look better with more diagonals 😊

**Comment by mrdoob** [comment]
Or maybe a cross?
