### ISSUE TITLE
InterleavedBufferAttribute has no clone method

### ISSUE THREAD

**Issue by sasha240100** [mrdoob/three.js#15395]
##### Description of the problem

Hi! I get this error because `InterleavedBufferAttribute` has no `.clone()` method. This happens when I'm trying to clone geometry that uses `InterleavedBufferAttribute`.
![image](https://user-images.githubusercontent.com/7657429/49679976-1a6b1b00-fa98-11e8-9ac4-fc304af5c4aa.png)

##### Three.js version

- [x] Dev
- [ ] r99
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by robertlong** [comment]
The `GLTFLoader` gets around this by converting the `InterleavedBufferAttribute` to a `BufferAttribute`. https://github.com/mrdoob/three.js/pull/12800

I need to clone geometries loaded by the `GLTFLoader` in Mozilla Spoke. I've got around this by forking the `GLTFLoader` and using my own `ClonableInterleavedBufferAttribute` that does the same conversion and spits out a warning.

```js
import { BufferAttribute, InterleavedBufferAttribute } from "three";

export default class ClonableInterleavedBufferAttribute extends InterleavedBufferAttribute {
  clone() {
    console.warn("Cloning an InterleavedBufferAttribute is unsupported. Converting to a BufferAttribute instead.");

    const count = this.count;
    const itemSize = this.itemSize;
    const array = this.array.slice(0, count * itemSize);

    for (let i = 0, j = 0; i < count; ++i) {
      array[j++] = this.getX(i);
      if (itemSize >= 2) array[j++] = this.getY(i);
      if (itemSize >= 3) array[j++] = this.getZ(i);
      if (itemSize >= 4) array[j++] = this.getW(i);
    }

    return new BufferAttribute(array, itemSize, this.normalized);
  }
}
```

I think this is a decent solution. Cloning no longer fails unexpectedly and you get a warning telling you that the geometry is going to be changed.

@donmccurdy proposed adding this clone method to the InterleavedBufferAttribute. Is there any objection to that?

**Comment by Mugen87** [comment]
Related #18537.

**Comment by donmccurdy** [comment]
What do you think of having the `BufferGeometry` `clone()` method take care of this instead, by reusing `InterleavedBufferAttribute` instances rather than cloning them?

**Comment by robertlong** [comment]
Yeah, that probably makes more sense. Then you could preserve the InterleavedBufferAttributes and just make a copy if they share the same underlying buffer. In my case I'm combining geometries, so I should make them regular BufferAttributes anyway, but I think having the BufferGeometry handle this is the right solution.
