### ISSUE TITLE
Example Licence

### ISSUE THREAD

**Issue by shengchiliu** [mrdoob/three.js#15408]
It's not about a bug.
I'm writing a paper and wondering can I use your sample in my publication. (I'll write the 3D model comes from three.js)?

**Comment by Mugen87** [comment]
What do you mean with "sample"? Are you referring to a particular model?

**Comment by shengchiliu** [comment]
I mean this 3D model
https://threejs.org/examples/#webgl_materials_matcap
Can I use the 3D model or other 3D models from your official examples in my journal paper?

**Comment by shengchiliu** [comment]
Basically, I am planning to capture images from different orientations of the 3D model and use the images in my paper. My question is that am I allowed to that? or what should I do to get the license for using your 3D model?

**Comment by Mugen87** [comment]
> My question is that am I allowed to that?

I'm on a lawyer but I would say yes^^. This particular model is licensed under `Creative Commons Attribution 3.0 Unported License`. I think you should be safe if you mentioned the origin of the model (this repository) and the respective license.

**Comment by shengchiliu** [comment]
Cool, this helps me a lot, thanks!

**Comment by Mugen87** [comment]
FYI, this is the actual license text: https://github.com/mrdoob/three.js/blob/dev/examples/models/gltf/LeePerrySmith/LeePerrySmith_License.txt

**Comment by shengchiliu** [comment]
I'll mention that the origin of the model is from www.triplegangers.com and the javascript code is from this repository.
Sounds good?

**Comment by Mugen87** [comment]
Yeah. Maybe it's a good idea to mention that the model is licensed under `Creative Commons Attribution 3.0 Unported License`.

**Comment by shengchiliu** [comment]
Got it.
Many thanks.
