### ISSUE TITLE
I cannot load texture image when I try to load mtl + obj loader.

### ISSUE THREAD

**Issue by uoon-dev** [mrdoob/three.js#15400]
##### Description of the problem
My code is here
```js
  var mtlLoader = new THREE.MTLLoader();
  mtlLoader.load("obj/Calisma2.mtl", function (materials) {
    materials.preload();
    var objLoader = new THREE.OBJLoader();
    objLoader.setMaterials(materials);
    objLoader.load("obj/Calisma2.obj", function (object) {
      house = object;
      scene.add(object);
    }, null, null);
  });
````
Even if I use mtl loader, I cannot load texture image. 
My repo is here. Can you give me an advice?

https://github.com/uoon-dev/threejs/tree/master/course02
 
<img width="859" alt="example" src="https://user-images.githubusercontent.com/38661266/49694661-8309e300-fbd1-11e8-80d3-d4beed62317d.png">

##### Three.js version

- [ ] Dev
- [x] r99
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This is not a help site. Please use the [forum](https://discourse.threejs.org/) or stackoverflow.

**Comment by uoon-dev** [comment]
Oh I'm sorry. I posted because there were similar issue. Thank you for guide.
