### ISSUE TITLE
not able to load geometry from objectLoader at server side (using npm module)

### ISSUE THREAD

**Issue by kannanlink3d** [mrdoob/three.js#15405]
##### Description of the problem

when using the npm module the 'window' is not defined.
Then this line crashes.

    if( 'THREE' in window && 'LegacyJSONLoader' in THREE ) {  
    ...
    }

Another problem is I can not convert a geometry created using following code for line to bufferGeometry as face data is not available.

    <let geometry = new THREE.Geometry();

    let material = new THREE.MeshBasicMaterial({
        color: color,
        opacity: 1.0
    });

    geometry.vertices.push(startPoint, endPoint);

    let lineMesh = new THREE.Line(geometry, material);

so how do i load it using objectLoader now as the support for geometry is removed from objectloader .

##### Three.js version

- [ ] Dev
- [x] r99
- [ ] ...

##### Browser

- [x] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by kannanlink3d** [comment]
found a solution.

**Comment by BrightShadow** [comment]
@kannanlink3d what was the solution?

**Comment by szwbuaa** [comment]
@kannanlink3d what was the solution?
