### ISSUE TITLE
Make pragma unroll_loop more dev-friendly

### ISSUE THREAD

**Issue by Granipouss** [mrdoob/three.js#15414]
Hi everyone,

Three.js is a really nice library, I have been experimenting with the `ShaderMaterial` lately and I think the `#pragma unroll_loop` helper is useful but could be even better.

Here are the two points that I want to improve:
- For the loop to be unrolled, it has to follow a very strict pattern, it would be nice to be able to put spaces wherever one wants, and to choose any name for the loop index. This issue can be solved easily with a small change on the regexp I think.
- The unrolling will create a broken shader if there any block inside unrolled one, it happened to me with if statement in the for loop. This would take a bit more of logic to be solved but would make the pragma a way more reliable tool.

So what do you think ?

**Comment by Mugen87** [comment]
I'm open to enhance the functionality of the pragma as long as it is correctly documented (right here: https://threejs.org/docs/index.html#api/en/materials/ShaderMaterial) and well tested.

Not sure about your second suggestion but the first one sounds good to me. Any chances to share the code for the enhanced regex?

**Comment by Granipouss** [comment]
I will implement the regex very soon in a PR.
But here is for some explanations, starting with the current regexp:
```js
var pattern = /#pragma unroll_loop[\s]+?for \( int i \= (\d+)\; i < (\d+)\; i \+\+ \) \{([\s\S]+?)(?=\})\}/g;
```

- To allow other spacing, we can just replace all ` ` with `\s*?`. So that `for ( int i = 0; i < 10; i ++ )` is still a match, but that `for (int i = 0; i < 10; i++)` also is.
- To allow other variable name than `i`, we can replace the first `i` with the group `(\w+?)` and all the follow by a back reference to the first group `\1` that will ensure than the same literal is repeated.

Optionally, we could also allow `i--` and `i <= 10` with some other change of the same kind.

I just have one thing preventing from doing the pull request right now. I have not found the tests on the `unrollLoops` function, and as it is not exposed I don't even know if it can be tested as is. What is you recommandation on testing that piece ? Shall I export it along `WebGLProgram`, make it a static method of `WebGLProgram` or put is in a separated module dedicated to parsing and unit tested ?

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/15429#issuecomment-532601711
