### ISSUE TITLE
Sprite with texture clips transparent mesh behind it

### ISSUE THREAD

**Issue by LuHaoPeng** [mrdoob/three.js#15411]
##### Description of the problem

I'm not sure if it's my fault or three.js error. I used sprite **with texture** to show a sign in front of a **transparent** mesh. When rotating to some angle, the sprite clipped part of the mesh.

good angle
![good](https://user-images.githubusercontent.com/13071103/49796927-f1d57080-fd78-11e8-99f4-8e15e52c2728.png)

bad angle 1
![bad1](https://user-images.githubusercontent.com/13071103/49796938-f7cb5180-fd78-11e8-85da-15249c7654ec.png)

bad angle 2
![bad2](https://user-images.githubusercontent.com/13071103/49796954-0285e680-fd79-11e8-9594-43041f016071.png)

I tried **opaque** mesh and sprite with **default** material. Either worked well, but not with both.

See [this fiddle](https://jsfiddle.net/LuHaoPeng/ke0p2wnj/)

Or maybe it's not a recommended way to display a sign?

##### Three.js version

- [x] Dev
- [x] r99
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

none.

**Comment by Mugen87** [comment]
Looks like a depth sorting issue. Setting `depthWrite` to `false` for the sprite material seems to mitigate the issue a bit:

https://jsfiddle.net/0dso41pg/

**Comment by LuHaoPeng** [comment]
Looks much better! Thanks!

Vaguely though, at some angle, it looks like the sign is under that mesh, which I believe is not.
![bad3](https://user-images.githubusercontent.com/13071103/49796783-97d4ab00-fd78-11e8-9968-16b17a0d186c.png)

**Comment by WestLangley** [comment]
>I'm not sure if it's my fault or three.js error.

If you are not sure, we prefer you ask your question on the three.js [forum](https://discourse.threejs.org), instead.

This is not a three.js bug. Depending on your objective, you can do this,
```javascript
textSprite.material.depthTest = false;
textSprite.renderOrder = 1;
```
or you can use multiple render passes.
