### ISSUE TITLE
GLTFExporter: Support lights

### ISSUE THREAD

**Issue by callmegaga** [mrdoob/three.js#15415]
Why GLTFExporter can't support light? Will it be  supported at later version?

**Comment by donmccurdy** [comment]
Lights are a relatively new feature in glTF 2.0, and haven't been implemented in GLTFExporter yet. We'd welcome a pull request, otherwise I expect this will be implemented eventually. :)

**Comment by lokiiarora** [comment]
Hey @donmccurdy, I was checking on the [GLTFExporter](https://github.com/mrdoob/three.js/blob/62b8e18b0ebfe945c0f1a2b087f1da3098b1ad2f/examples/js/exporters/GLTFExporter.js#L1827), turns out it exports lights.

I wonder @callmegaga is concerned about an older version, can we close this?

**Comment by Mugen87** [comment]
Related #15519.
