### ISSUE TITLE
HDR and EXR Environment Map Issue

### ISSUE THREAD

**Issue by njarraud** [mrdoob/three.js#15410]
##### Description of the problem

Fragment Shader from PMREMGenerator.js doesn't seem to run properly on Windows 10 platforms.
In some cases, colors are washed out with a red, green or blue tint even becoming fully white.

- This issue doesn't impact macOS.
- The issue is observed with equirectangular HDR images in .exr or .hdr format.

To illustrate the issue, I loaded an HDR image an assigned the texture as envMap of a THREE.MeshPhysicalMaterial material. The env map is rotated thanks to a small tweak in equirectangularToCubeGenerator.js

Rotation angles being problematic are linked to the HDRI loaded. Some HDRIs fail at 0° (and therefore issue can be reproduced with the original file equirectangularToCubeGenerator.js without my tweak)

Tweak in equirectangularToCubeGenerator.js:
`boxMesh.rotation.y = options.rotation;`

PMREMGenerator.js shipped with threejs r98 which has a different fragment shader is having a similar issue as r99 but not as bad.

1. macOS: https://youtu.be/WVZhLqYOGGE
2. Windows 10 PMREMGenerator.js r98: https://youtu.be/zdr-6hdQh20
3. Windows 10 PMREMGenerator.js r99: https://youtu.be/e8i0nATe1PQ

I also added a [jsfiddle](https://jsfiddle.net/h0y5scpx/7/).

##### Three.js version

- [x] Dev
- [x] r99
- [x] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Any chance you can create a jsfiddle for us?

**Comment by njarraud** [comment]
Yes, here it is:
* [jsfiddle](https://jsfiddle.net/h0y5scpx/6/)

**Comment by looeee** [comment]
I can confirm this, it seems to be a Chrome issue though. Rotation at 61 degrees shows the strongest effect. 

## Windows 10,  Chrome 71.0.3578.80 

#### Rotation 59 degrees
![cr59](https://user-images.githubusercontent.com/5307958/49776692-08a7a300-fd38-11e8-9d54-2392d5d0b323.png)


#### Rotation 61 degrees
![cr61](https://user-images.githubusercontent.com/5307958/49776695-0a716680-fd38-11e8-9751-a4eaae5487de.png)


## Windows 10,  Firefox 63.0.3

#### Rotation 59 degrees
![ff59](https://user-images.githubusercontent.com/5307958/49776698-0c3b2a00-fd38-11e8-9ff6-9a1b933f4266.png)


#### Rotation 61 degrees
![ff61](https://user-images.githubusercontent.com/5307958/49776701-0e9d8400-fd38-11e8-8069-dfdbb679e516.png)

**Comment by njarraud** [comment]
I have exactly the same results with Chrome or Firefox on Windows, meaning same issues for same angles.

**Comment by peteroupc** [comment]
Could it be an issue with ANGLE, which I believe Firefox and Chrome use on Windows?

**Comment by mrdoob** [comment]
Could be... Doesn't happen in Edge?

**Comment by njarraud** [comment]
I just tried with Edge right now and I have the same issue.

**Comment by looeee** [comment]
I can't reproduce this in either Edge 44.17763.1.0 or Firefox 63.0.3

@njarraud what versions are you running?

**Comment by njarraud** [comment]
I ran it on Firefox 63.0.3 and the latest version of Chrome as of today.
For Edge, I cannot say right now. I never use it and that was on my CAD workstation. I will try to find more windows machines to test.

**Comment by njarraud** [comment]
I run some more testing over the weekend with multiple machines.

The issue is very visible on all 3 browsers (Chrome, Firefox and Edge) when using an integrated Intel GPU. When I switched on the NVidia GPU, Firefox do not have the issue anymore, Chrome has a very light one - as seen on @looeee post - and it still very well visible on Edge (but I could only try with r42 instead of the latest r44).

To recap:

1. Intel HD Graphics 630:
- Firefox 64.0: Strong issue as seen in the videos from my first post
- Chrome 71.0.3578.98: Strong issue as seen in the videos from my first post
- Edge 42.17134.1.0: Strong issue as seen in the videos from my first post

2. NVIDIA Quadro M1200 4GB:
- Firefox 64.0: No issue
- Chrome 71.0.3578.98: Light issue
- Edge 42.17134.1.0: Strong issue as seen in the videos from my first post

3. Intel HD Graphics 620:
- Chrome 71.0.3578.98: Strong issue as seen in the videos from my first post
- Edge 42.17134.1.0: Strong issue as seen in the videos from my first post

**Comment by mrdoob** [comment]
#15390 mentions that it removes the yellow tint. Do you mind trying it?
