### ISSUE TITLE
Unreal bloom colour issue

### ISSUE THREAD

**Issue by thapliyalshivam** [mrdoob/three.js#15436]
The example under three.js 
https://threejs.org/examples/?q=bloom#webgl_postprocessing_unreal_bloom
tells about about loading themodel and having bloom effect applied.
However there's no article to tell how to add coloured bloom.

Only on adding #fff material while bloom is achieved. However, if someone wants a coloured bloom for e.g. a neon string, it doesn't render. as soon as one changes material from #fff to any other, bloom is not rendered.

**Comment by WestLangley** [comment]
This is just an example. If you need help modifying it, please redirect your question to the [three.js forum](https://discourse.threejs.org).
