### ISSUE TITLE
ParametricGeometry - calling paramfunc

### ISSUE THREAD

**Issue by willgoldring** [mrdoob/three.js#15437]
The new format for calling the paramfunc for parametric geometry (with target) seems to be erroneously processing normals, as seen in the surface rendering below.

I'm using it as follows, and it seems to be calling my function much more than requested by the two params (u,v) in the geom call.
var cnt = 0;

        var surfgeom = new THREE.ParametricGeometry(paramfunc, 10, 10, false);
        console.log("cnt=" + cnt);

        var surfmat = new THREE.MeshPhongMaterial({
            side: THREE.DoubleSide,
            color: 0xffffff,
            vertexColors: THREE.VertexColors,
            specular: 0x050505,
            shininess: 100.,
            emissive: 0x111111,
        });
      
        var surfmesh = new THREE.Mesh(surfgeom, surfmat);
        scene.add(surfmesh);

        function paramfunc(u, v, target) {
            cnt++;
            uint = parseInt(u * 200.0);
            pt = curves[uint].getPoint(v);
            console.log("u=" + u + " uint=" + uint + " v=" + v + " x=" + pt.x + " y=" + pt.y + " z=" + pt.z);
            target.set(pt.x, pt.y, pt.z);
        }
image

![image](https://user-images.githubusercontent.com/7935416/50047892-8db1f580-0073-11e9-969a-cfd4ea39d4e2.png)

![image](https://user-images.githubusercontent.com/7935416/50047870-23995080-0073-11e9-8654-c00530de160d.png)

**Comment by WestLangley** [comment]
Please redirect your question to the [three.js forum](https://discourse.threejs.org).
