### ISSUE TITLE
[feature request] switch canvas of renderer

### ISSUE THREAD

**Issue by Fenzland** [mrdoob/three.js#15445]
##### Description of the problem

Currently, each renderer bind with a special canvas. Even if I do settings like `renderer.domElement = another canvas`, there is nothing works.
I have a page with hundreds of canvases, they are render with three.js and almostly never change. I want to use a single renderer to render all canvases.
So I wish feature that allow user to switch canvas of renderer.

##### Three.js version

- [ ] Dev
- [x] r99
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> Even if I do settings like renderer.domElement = another canvas, there is nothing works.

The renderer's internal WebGL context is directly connected with a specific canvas element. That's the reason why assigning an other canvas element to `WebGLRenderer.domElement` does not work.

If you have to render to multiple canvas elements, you might want to use an approach presented in the following example:

https://threejs.org/examples/webgl_multiple_canvases_grid.html

**Comment by Fenzland** [comment]
> > Even if I do settings like renderer.domElement = another canvas, there is nothing works.
> 
> The renderer's internal WebGL context is directly connected to a specific canvas element. That's the reason why assigning an other canvas element to `WebGLRenderer.domElement` does not work.
> 
> If you have to render to multiple canvas elements, you might want to use an approach presented in the following example:
> 
> https://threejs.org/examples/webgl_multiple_canvases_grid.html

Thank you. Copy render result to other canvases, that's helpful.
The feature request is not required.
