### ISSUE TITLE
[feature request] configurable handedness (direction of rotation)

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#15442]
##### Description of the problem

It'd be nice to configure the default direction of rotation (handedness) in Three.js.

Maybe it can be a static property on Object3D or Matrix4?

For example: 

```js
Object3D.HANDEDNESS_X = 'left'
Object3D.HANDEDNESS_Y = 'right'
Object3D.HANDEDNESS_Z = 'left'
```

or maybe on an instance-per-instance basis? F.e.:

```js
Object3D.handednessX = 'left'
Object3D.handednessY = 'right'
Object3D.handednessZ = 'left'
```

I think perhaps on an object-per-object would be nicer and more flexible.

Ah, but if it is on an object-per-object basis, then we have access to the matrix, so it would be cleaner for it to be an instance variable on `Matrix4`:

```js
Object3D.matrix.handednessX = 'left'
Object3D.matrix.handednessY = 'right'
Object3D.matrix.handednessZ = 'left'
```

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by trusktr** [comment]
Here's a codepen example, where I've hacked CSS3DRenderer, where I'm keeping the DOM structure nested, and simply copying over local matrices instead of world matrices to the DOM elements, and as you see the X rotation in the DOM is inverse from Three.js rotation (left handed instead of right):

https://codepen.io/anon/pen/BvzpVa

You can see the slightly-visible mesh rotating the opposite direction on X.

If we could simply invert the handedness for that axis, then it'd make the end-user code cleaner, instead of user having to negate rotation values, or having to abstract it higher and making code harder to understand (that example is already a little bit hacky, I wouldn't want to make it more hacky).

**Comment by Mugen87** [comment]
I've tried to introduce a configurable `forward` vector but without luck, see #14703. I think this exactly the functionality that you are looking for.

`Object3D.forward` would be a great addition for the library. I support any forms of attempts which try to implement this feature.

**Comment by mrdoob** [comment]
I think such a feature will make the math classes ~9 times more complicated...

In 7 years we were not able to export from Blender with the right handedness. And that was a case of single handedness to single handedness. In short, handedness is complicated.

Feel free to give it a go, but I suspect the complexity this brings would scare contributors.

**Comment by mrdoob** [comment]
> https://codepen.io/anon/pen/ZVOKwG

For some reason this page enters a infinite reloading loop in Chrome.

**Comment by looeee** [comment]
> For some reason this page enters a infinite reloading loop in Chrome

Does it work in incognito? I've very intermittently been having that problem with codepen for about a year now but incognito mode usually fixes it. I think it's a problem with some extension but I haven't tracked down which one yet.

**Comment by mrdoob** [comment]
@looeee it does yeah! 🤔

**Comment by trusktr** [comment]
The way I was thinking of the implementation it wouldn't touch the Math classes, just Object3D `rotation.xyz` API: basically simply negate the values if needed.  But then if someone goes and does their own matrix math, they're on their own (and it may not match the handedness in Object3D).

I'll make a PR for discussion if I can get a chance.

**Comment by WestLangley** [comment]
See https://www.evl.uic.edu/ralph/508S98/coordinates.html.

There is no way I would support making per-axis handedness configurable.

I recommend closing this issue.

**Comment by trusktr** [comment]
Who are we to tell users they can't pick the "direction of rotation" of their axes?

Being able to at least configure handedness (or "direction of rotation") for all axes together instead of individually seems at least reasonable.

I'd enjoy to simply toggle a flag and have Three.js align with regular CSS3D transforms. Maybe you aren't using CSS 3D, but I am, and such a feature would be sweet because then I don't have to think about all the maths.

**Comment by trusktr** [comment]
> There is no way I would support making per-axis handedness configurable.

I've explained why I want the feature. It'd be nice if you can explain why you don't want it.

**Comment by Mugen87** [comment]
Engines like Unity also don't offer such an option. For good reasons.

> This google search shows I'm not the only one that would like more configurability over the axes.

People who are searching for this are obviously not familiar with the complexity behind such a feature.

**Comment by trusktr** [comment]
How much complexity would it add? (Just curious, not implying anything about the complexity.)

**Comment by mrdoob** [comment]
> How much complexity would it add? (Just curious, not implying anything about the complexity.)

You may want to do some studying on the subject over the holidays 😉
