### ISSUE TITLE
customDepthMaterial and customDistanceMaterial are documented in the wrong place

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#15449]
https://threejs.org/docs/#api/en/materials/Material.customDepthMaterial

https://threejs.org/docs/#api/en/materials/Material.customDistanceMaterial

These are not properties of materials. As far as I can see from the [couple](https://threejs.org/examples/#webgl_buffergeometry_instancing_lambert) of [examples](http://threejs.org/examples/#webgl_shadowmap_pointlight) where they are used, they should be properties of `Mesh`, or perhaps `Object3D`. 

By default, these properties are not initialised at all, even to undefined, and the only reference to them in the source is a couple of lines in `WebGLShadowMap` here:

https://github.com/mrdoob/three.js/blob/074290d3823ada31cade0c70c976be09213c99f9/src/renderers/webgl/WebGLShadowMap.js#L263-L278

Perhaps we could initialise them in `Object3D` as 

```
function Object3D() {

    ... 
    
    this.customDepthMaterial = undefined;
    this.customDistanceMaterial= undefined;
    ...
}
```

and then document them correctly?

**Comment by pailhead** [comment]
That one was my bad. I wouldn't put them on `Object3D` though as many things extend from it that have no relationship to materials whatsoever (light, camera).

**Comment by looeee** [comment]
There's other cases in the library where things defined on the base class only work for some of the extended classes, so I'm not sure that's a problem. 

For example on material we have `material.dithering` that only works for Lambert, Phong and Standard materials.

**Comment by Mugen87** [comment]
`customDistanceMaterial` should be a property of `PointLight` since it is only used in this context right now.

I would put `customDepthMaterial` to `Mesh` for now since casting shadows with points and lines is problematic, see https://github.com/mrdoob/three.js/issues/7738.

**Comment by pailhead** [comment]
Actually, would you consider the thought of keeping the doc on the material, and moving the prop to the material? I think my primary objective was to document the three missing props starting from the `defines`  which are also for the most part private-ish. 

The base concept is that some of the stuff is shared, while the mesh has no idea about it.
```
class SomeMaterial {
   fragmentMain: 'glslThatDrawsColorLight',
   fragmentDepth: 'somePackingGLSL'
   vertexShaderBase: 'someVertTransformation',
   vertexShaderLights: 'glslForNormalsAndSuch'
}
```

Ie. 

```
myMesh.material = myColorMaterial
myMesh.customDepthMaterial = myCustomDepthMaterial
```
vs
```
myColorMaterial.depth = myCustomDepth
myMesh.material = myColorMaterial
```
If you're applying the same material to N meshes, you don't have to set this twice.

**Comment by looeee** [comment]
> Actually, would you consider the thought of keeping the doc on the material

The current API seems simpler, but I don't have any kind of strong opinion on this. 

However, the documentation is currently incorrect and confusing so if this is going to take some time to work out, we should remove the current documentation in the meantime.

**Comment by Mugen87** [comment]
I vote to change the documentation like suggested here: https://github.com/mrdoob/three.js/issues/15449#issuecomment-448552384

This will reflect the current usage of both properties. I don't think the documentation should account for scenarios which are currently not supported by the renderer. Like I said before `customDistanceMaterial` is only evaluated to `PointLights` and `customDepthMaterial` by `WebGLShadowMap`.

**Comment by mrdoob** [comment]
I think it's okay to put it on `Object3D` and mention that only affects `Mesh`.
