### ISSUE TITLE
Sharing depth buffer between targets

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#15440]
I'm experimenting with an effect that uses the stencil buffer. I'd like to be able to share the depth/stencil render buffer between different targets.

It seems like i've been able to do what i want by changing this:

https://github.com/mrdoob/three.js/blob/b2ca5694e09700682f4f0e499e77d048b6f94f3b/src/renderers/webgl/WebGLTextures.js#L814

to:

```
setupRenderBufferStorage( renderTarget.ownDepthBuffer || renderTargetProperties.__webglDepthbuffer, renderTarget )
```

and creating the buffer myself on the render target.

I am unable to find a way to do this without modifying the library. The super private caching internals seem to be in the way, since `createRenderbuffer()` is both called and stored inside the renderer.

I don't understand what exactly `depthTexture` is, but it seems like it is something similar to this, and can be provided from outside. Is there a way to achieve what i'm doing here without the hack?

**Comment by mrdoob** [comment]
> I don't understand what exactly `depthTexture` is, but it seems like it is something similar to this, and can be provided from outside. Is there a way to achieve what i'm doing here without the hack?

I don't think so...

How do you think the API for this should be?

**Comment by pailhead** [comment]
Here's an example of how I'm using this:

https://raw.githack.com/pailhead/three.js/depth-peel-stencil/examples/webgl_materials_depthpeel.html

The little quads kinda show what's going on, but I want to try to visualize it better. There are two targets being flip flopped, so the same scene is being drawn to both of them. But with each pass, I do some stencil logic, and I keep it around for the next one. Because each pass needs to write something to it, I need to keep the same buffer between both targets.

**Comment by pailhead** [comment]
Wow, sharing between the final composition target as well made it run at 60fps at half rez on an iphone. I think this would be a useful feature.

**Comment by gkjohnson** [comment]
@pailhead Can you explain a bit more about why using [DepthTexture](https://threejs.org/docs/#api/en/textures/DepthTexture) wouldn't work? At least on the surface it seems to be what you're interested in, granted it requires an extension to work.

**Comment by Mugen87** [comment]
Closing in favor of #15490.

**Comment by gkjohnson** [comment]
@Mugen87 #15490 is a PR, though -- does it make sense to close the issue in favor a PR?

**Comment by Mugen87** [comment]
Well, if both more or less contain the same discussion I think it's okay. Especially since the initial post (https://github.com/mrdoob/three.js/pull/15490#issue-241462789) is very detailed.
