### ISSUE TITLE
orbitcontrols pan with orthographic camera does not works properly

### ISSUE THREAD

**Issue by kannanlink3d** [mrdoob/three.js#15446]
##### Description of the problem

pan from OrbitCOntrols of r99 does not work properly 
it  pans in x direction 
but nothing happens when i move mouse in y direction 

this was working fine with version 72 and lower (since controls.constraint has been removed )
Please provide a working solution if it works with some conditions/settings/function calls.

##### Three.js version

- [ ] Dev
- [x] r99
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
`OrbitControls` is now panning parallel to the XZ plane. Set
```javascript
controls.screenSpacePanning = true;
```
for legacy behavior.

**Comment by kannanlink3d** [comment]
controls.screenSpacePanning = true;
