### ISSUE TITLE
GLTFLoader: exposing GLTFParser class and Constants

### ISSUE THREAD

**Issue by yomotsu** [mrdoob/three.js#15477]
Currently, [GLTFParser](https://github.com/mrdoob/three.js/blob/bda55a3bf0bc3f181b295a1c34997935f8ed7f1e/examples/js/loaders/GLTFLoader.js#L213) and constants in [GLTFLoader](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js) are scoped and cannot be used in user-land.
However, sometimes it is needed.

Usecases:

- glTF-ish file may need special parsing using modified(extended) GLTFParser.
- glTF models may be supplied in JSON or JSONP format from a WebApp API rather than files and need GLTFParser directly.

Also, [`WEBGL_CONSTANTS` and other constants](https://github.com/mrdoob/three.js/blob/bda55a3bf0bc3f181b295a1c34997935f8ed7f1e/examples/js/loaders/GLTFLoader.js#L1088-L1195
) would be useful if available under `THREE` or somewhere

What I would like to have is:

- `THREE.GLTFParser`

and maybe:

- `gltfLoaderInstance.gltfParser`
- `THREE.WEBGL_CONSTANTS.FLOAT = 5126` and so on

**Comment by mrdoob** [comment]
Wouldn't be opposed to move `GLTFParser` outside of the closure and add it to the `THREE` namespace.

The module version of the file could export `GLTFLoader` and `GLTFParser`.

**Comment by donmccurdy** [comment]
Rather than another top-level object, maybe just `GLTFLoader.Parser`? Even when using the parser directly users should generally not construct it themselves, but use `loader.getParser()` when that is implemented. Constants could be something like `GLTFLoader.WebGLConstants.FLOAT`.

> ... ideally it should be in one place, rather than in both GLTFLoader.js and NPM...

The idea here would be that there should be _official_ glTF constants on NPM (e.g. maintained by Khronos, not just for three.js), so users can install them in the rare case that they need custom parsing. But threejs examples cannot have dependencies, so the constants will have to be duplicated for GLTFLoader.

**Comment by donmccurdy** [comment]
^Feel free to open a PR for moving the parser and constants out of the closure if this is still helpful. I would wait on other PRs for the rest.

**Comment by takahirox** [comment]
> glTF-ish file may need special parsing using modified(extended) GLTFParser.

Just curious to know what "glTF-ish file" means by.

**Comment by takahirox** [comment]
> Rather than another top-level object, maybe just GLTFLoader.Parser?

Voting for non top-level object.

I think putting under `THREE` may require better maintenance, for example writing document and keeping compatibility as much as possible. It may be too early for the parser now. I guess we still optimize/refactor/update the parser.

**Comment by yomotsu** [comment]
@takahirox `GLTFLoader.Parser` could be okay for that?

> Just curious to know what "glTF-ish file" means by.

I meant VRM and maybe eVRM (can be seen in [ニコニ立体](https://3d.nicovideo.jp/works/td50051)), or othrer Web App oriented models.

<img width="1090" alt="screen shot 2018-12-29 at 12 28 49 pm" src="https://user-images.githubusercontent.com/212837/50533021-5d835000-0b65-11e9-92a2-0fa6e2f3b535.png">

**Comment by takahirox** [comment]
Making `.getParser()` PR. I think I can share soon.

**Comment by takahirox** [comment]
@yomotsu My understanding is VRM consists of glTF 2.0 core spec with some limitation + VRM custom extension. And `parser` in user side is necessary for handling the custom extension, correct? "glTF-ish" sounded a bit vague to me so I just want it to be more specific.

**Comment by yomotsu** [comment]
That's right. VRM is a glTF based extended format, and the Parser may need to handle HumanBones, Facial expression blendings, MToon Materials, and others.

In addition, some Web App like ニコニ立体 may use encrypted VRM like "eVRM" in order to protect user upload models, and injecting user-land function to the parser may be needed as well.

**Comment by donmccurdy** [comment]
To be clear, we can't guarantee that the parser's API will remain the same over time. Internal methods might be renamed or removed, and extending them may be fragile. If you're really customizing the loader for new formats and extensions, it's very possible you'll want to just fork the loader. 

But if you're OK with all that, a PR is still fine with me.

**Comment by yomotsu** [comment]
Thanks for your suggestions. I understand and `getParser` could guarantee that.
Even though, having the official Parser class as `GLTFLoader.Parser` would be great for me.

@takahirox Would it be okay?

**Comment by takahirox** [comment]
I wanna suggest that we first go with `.getParser()`. And thinking of the option exposing `GLTFLoader.Parser` when we realize we really need.

**Comment by MarioDelgadoSr** [comment]
Re: https://github.com/mrdoob/three.js/issues/15477#issuecomment-449906411

The glTF 2.0 specs allow for [embedded data URIs](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#uris) 

For that scenario, what would be the value for the path parameter in with the [loader.parse() method](https://threejs.org/docs/#examples/loaders/GLTFLoader.parse) ?  Would it be an empty string ("")?

**Comment by donmccurdy** [comment]
@MarioDelgadoSr yes, an empty string is fine in that case. You can also use LoadingManager's setURLModifier() method to affect this.

**Comment by MarioDelgadoSr** [comment]
@donmccurdy (re: https://github.com/mrdoob/three.js/issues/15477#issuecomment-503241742) 

Including link to documentation on LoadingManager's setURLModifier() method for anyone else researching use case: https://threejs.org/docs/index.html#api/en/loaders/managers/LoadingManager.setURLModifier

**Comment by donmccurdy** [comment]
Do we still need this, with access to the `gltf.parser` object and the newer extension API?

**Comment by yomotsu** [comment]
It would be better for me.
@FMS-Cat What do you think?

**Comment by FMS-Cat** [comment]
Yes, exposed parser and the plugin system is working well.

**Comment by takahirox** [comment]
Plugin system provides the extensibility of the loader. How do you want to use the exposed parser?

**Comment by mrdoob** [comment]
If I understand @FMS-Cat correctly, he's saying that this issue can be closed.

**Comment by FMS-Cat** [comment]
I mean, the constructor of GLTFParser is okay to not be exposed I think. my bad.

**Comment by takahirox** [comment]
OK, thanks for clarifying.

Then, let's close this issue for now. And let's reopen or create a new one if you folks encounter a use case the plugin system doesn't cover.
