### ISSUE TITLE
FPS drop when model appears

### ISSUE THREAD

**Issue by hungtd58** [mrdoob/three.js#15479]
When I use ThreeJs to load my .dae file, FPS is only 5-7.
I try to optimize it with blender and meshlab, I can load it smooth but model becomes worse. Can anyone explain to me why my model is lag when load.
You can download my model at [here](https://drive.google.com/file/d/1jGipM2GL_ol-4HRFrQefcq0TC7hE5c5i/view?usp=sharing).
Thanks you!!

**Comment by Mugen87** [comment]
This is not a help site. Please use the [forum](https://discourse.threejs.org/) or stackoverflow for such requests.
