### ISSUE TITLE
scene.background CubeTextureLoader with OrthographicCamera doesn't render

### ISSUE THREAD

**Issue by wellcaffeinated** [mrdoob/three.js#15472]
##### Description of the problem

When using an orthographic camera, the scene background (if it's a cube texture) won't render.
Here's a test: http://jsfiddle.net/e50fz47r/
If you uncomment the perspective camera you'll see that it renders just fine.

##### Three.js version

- [ ] Dev
- [x] r99
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
MacBook Air (13-inch, Mid 2012)
Intel HD Graphics 4000 1536 MB

**Comment by WestLangley** [comment]
I do not think it makes sense to use an orthographic camera with a skybox, since the projection varies as a function of the skybox's size.

A perspective camera does not have that problem (as long as the camera is centered in the skybox, something we ensure).

**Comment by Mugen87** [comment]
@wellcaffeinated What is your motivation to use an orthographic camera with a skybox?

**Comment by wellcaffeinated** [comment]
Motivation: demonstrating demonstrating vector math in a "space" scene. So the orthographic camera is necessary to see the projections clearly, but I want the demonstration to look like it's in space

**Comment by wellcaffeinated** [comment]
At the moment I'm trying to work with something like this:
```
    let skyGeometry = new THREE.SphereGeometry(50, 50, 50)
    let skyMaterial = new THREE.MeshBasicMaterial({ envMap: this.spaceBackgroundTexture, side: THREE.BackSide })
    let skyBox = new THREE.Mesh( skyGeometry, skyMaterial )
    scene.add(skyBox)
```

This means if i zoom out i can see the edges of the sphere... but perhaps it works well enough for my purposes since I don't need to let the user have perpetual zoom.

**Comment by wellcaffeinated** [comment]
on second thought... it scales the stars. So not a great solution...

**Comment by wellcaffeinated** [comment]
This workaround seems to be alright for my purposes:
```javascript
init(){
  camera = new THREE.OrthographicCamera( -w/2, w/2, -h/2, h/2, 1, 1000 )
  // near cuts off the rest of the scene
  spaceCam = new THREE.PerspectiveCamera( 30, w / h, 1000, 10000 )
}
render(){
  spaceCam.position.copy(camera.position)
  spaceCam.lookAt(vOrigin)
  renderer.autoClear = true
  renderer.render( scene, spaceCam )
  renderer.autoClear = false
  renderer.render( scene, camera )
}
```

**Comment by pailhead** [comment]
You can just set `autoClear = false` and call `renderer.clear()` before your first `render()`

**Comment by wellcaffeinated** [comment]
@pailhead thanks

I've noticed now that the orthographic camera sees the cube that the scene creates but it's not a child of the scene so i can't scope its visibility with layers. Is there any way to have control over this to prevent the orthographic camera from seeing the cube? Or get any kind of access to the cube mesh it creates?

**Comment by pailhead** [comment]
Oh, have you tried using different scenes?

**Comment by wellcaffeinated** [comment]
I haven't, i thought it would be overkill.
I ended up copying the threejs code in webglrenderer to create my own box, then added it to the scene with a layer. Seems like a lot of trouble to get this effect but I guess it's an edgecase...?

But i mean... I could imagine someone making a starcraft-like game with a space background, so I think it might be worth thinking about facilitating this for others.

**Comment by pailhead** [comment]
Much less of an overkill than disassembling the renderer :)

**Comment by Mugen87** [comment]
Closing. It's better to continue the discussion at the [forum](https://discourse.threejs.org/). We can reopen the issue if there is a more concrete feature request.
