### ISSUE TITLE
SVGRenderer is failing to clip SVGObjects behind the camera.

### ISSUE THREAD

**Issue by bpetar** [mrdoob/three.js#15476]
When adding svg object to 360 scene, i see it two times.

Issue is also explained on this stackoverflow link:
https://stackoverflow.com/questions/53762371/svgrenderer-with-orbitcontrols-shows-two-svg-elements-on-opposite-sides?noredirect=1

Problem example is here:
http://mystic-peanut.com/mystic_sites/svgdouble/svg_sandbox.html

##### Three.js version

- [ ] Dev
- [x] r99
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Um, I'm not able to reproduce the problem with this fiddle:

https://jsfiddle.net/f2Lommf5/16830/

What are you doing different?

**Comment by bpetar** [comment]
I am using 'THREE.SVGObject'

https://jsfiddle.net/f2Lommf5/16841/

**Comment by Mugen87** [comment]
Ah, now I see! Yes, that's indeed a buggy behavior.

**Comment by Mugen87** [comment]
How about testing if the z-coordinate in NDC space of an `SVGObject` lies in the range of `[0,1]`? I would a single line to add right [here](https://github.com/mrdoob/three.js/blob/23b73236e51d428d63d1beed3279da7f769935de/examples/js/renderers/SVGRenderer.js#L253):
```js
if ( _vector3.z < 0 || _vector3.z > 1 ) return; // FIX
```
For testing: https://jsfiddle.net/f2Lommf5/16845/

**Comment by Mugen87** [comment]
In any event, performing this type of object clipping in clip space (well, in NDC in our case) seems more natural to me. 

>That mapping is very sensitive near the boundary for a perspective camera.

Can you demonstrate this with a live example? It would be interesting to see an actual use case where the range test fails in NDC space but works in view space.

**Comment by WestLangley** [comment]
Well, perhaps it is not a problem;  the mapping to NDC space is just not continuous.

Personally, I prefer the test in camera space for clarity, but do as you wish.

**Comment by Mugen87** [comment]
Let's see what @mrdoob prefers. Both solutions solve the problem.

**Comment by Mugen87** [comment]
I'm a bit impatient so I've created a PR with the first approach mentioned in this thread.

**Comment by bpetar** [comment]
This helped me greatly with my project. Thank you for your fix.

**Comment by sebastien-schneider** [comment]
There's some drawbacks with this fix when you use an OrthographicCamera. By default, without any position change on the SVGObject, the z value is slightly under 0 and the SVG object just not appears at all :-(
