### ISSUE TITLE
Half-float attribute support

### ISSUE THREAD

**Issue by simon-paris** [mrdoob/three.js#15480]
##### Description of the problem

It's currently impossible to make a half float attributes work, since the GL buffer type is derived from the JS buffer type, and JS doesn't have a half float buffer type.

I'd like to add a special case to Uint16 and Int16 attributes that causes them to be interpreted as half floats.

```javascript
var myAttr = new THREE.BufferAttribute(new Uint16Array(whatever), 3);
myAttr.useHalfFloat = true;
```

Would this be acceptable?

##### Three.js version

- [x] All

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
I personally would love to see `Float16Array` 😇 

https://esdiscuss.org/topic/float16array

Without such a data type, you have to manually perform the conversion to half-float which is cumbersome. I'm not sure we want code like the following in the library core:

http://codeflow.org/experiment/half-float/main.js

**Comment by mrdoob** [comment]
Could be a good idea to start with a example though. 

If I understand correctly, what we need in core is a way to hint the renderer that we attribute is half-float and then a helper (in examples) to convert the array. Correct?

**Comment by Mugen87** [comment]
I think so. @simon-paris Do you want to give it a try?  

BTW: I have create a test fiddle for the forum some time ago that shows how to use a data texture with half float data (`THREE.HalfFloatType`):

https://jsfiddle.net/f2Lommf5/1856/

It would be great if the helper could also be used to convert the data for this use case. Right now, I manually set the half float value for `10000`.

**Comment by WestLangley** [comment]
https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/HDRCubeTextureLoader.js#L27

**Comment by Mugen87** [comment]
How convenient^^

**Comment by Mugen87** [comment]
Okay. But one thing bothers me. `BufferAttribute.useHalfFloat` would only work in specific cases (when using `Uint16Array` and `Int16Array`). I think it's better to put the property to `Int16BufferAttribute` and `Uint16BufferAttribute`.

**Comment by mrdoob** [comment]
So rather than adding `useHalfFloat` you are suggesting we check for `attribute.isInt16BufferAttribute` instead?

**Comment by Mugen87** [comment]
I've meant we should not introduce a new property to `BufferAttribute`. I would add a property to the more specific classes `Int16BufferAttribute` and `Uint16BufferAttribute`.

**Comment by Mugen87** [comment]
Um, it seems that `vertexAttribPointer` accepts half float attributes only with WebGL 2, see

https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/vertexAttribPointer
