### ISSUE TITLE
Render to float texture throws error when context is webgl2

### ISSUE THREAD

**Issue by RaymanNg** [mrdoob/three.js#15493]
##### Description of the problem

I can't render to float texture in 'webgl2' context,  and there are lots of `GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete` in my browser console

if I change the line
`context = canvas.getContext('webgl2');`
to `context = canvas.getContext('webgl');` in below code example,
those errors will disappear.

I want to know why this issue happen, and how to deal with it.
Thanks

A code example
```js
let canvas, context;
let camera, scene, renderer;

function init() {
    canvas = document.getElementById('canvas');
    context = canvas.getContext('webgl2');

    scene = new THREE.Scene();
    camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
    camera.position.z = 1.0;

    renderer = new THREE.WebGLRenderer({ canvas: canvas, context: context });
    renderer.setPixelRatio(window.devicePixelRatio);
    renderer.setSize(window.innerWidth, window.innerHeight);
}

var target = new THREE.WebGLRenderTarget(256, 256, {
    format: THREE.RGBAFormat,
    type: THREE.FloatType
})

function render() {
    renderer.render(scene, camera, target);
}

function animate() {
    requestAnimationFrame(animate);
    render();
}

init();
animate();
```

##### Three.js version

- [x] Dev
- [ ] r99
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Fiddle for testing: https://jsfiddle.net/f2Lommf5/16874/

Firefox shows a similar warning:

> Error: WebGL warning: clear: Framebuffer not complete. (status: 0x8cd6) COLOR_ATTACHMENT0Attachment has an effective format of RGBA32F, which is not renderable. three.min.js:184:123
Error: WebGL warning: clear: Framebuffer must be complete.

Removing `THREE.FloatType` as a parameter also remove the warning.

**Comment by RaymanNg** [comment]
Hi @Mugen87 , thanks for your reply.

According to the [read float buffer example](https://github.com/mrdoob/three.js/blob/1cbcaab0b8c80cd66b5812881597529f9ebd19c0/examples/webgl_read_float_buffer.html#L131), render to float texture is possible, why I can't do the same thing with webgl2 context?

**Comment by Mugen87** [comment]
I don't know why this happens. I've personally never used floating point textures with WebGL 2 so far.

**Comment by lmj01** [comment]
I got some similar problem, move some webgl1 shader to webgl2, it cause some strange result, so it is the webgl2 problem or the  threejs library problem ? or #version es 300 problem?
which one known why ?

**Comment by Mugen87** [comment]
It seems you can fix it in your app by calling:
```js
renderer.extensions.get( 'EXT_color_buffer_float' );
```
According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/EXT_color_buffer_float) `RGBA32F` now becomes `color-renderable`. The internal FBO of the render target is now complete.

Demo: https://jsfiddle.net/f2Lommf5/16883/

I think we have to enhance the renderer a bit so the extension is enabled automatically when using WebGL2 and a float texture.
