### ISSUE TITLE
"getParameter is not a function"

### ISSUE THREAD

**Issue by benguild** [mrdoob/three.js#15491]
##### Description of the problem

Saw this on Sentry.

> TypeError: getParameter is not a function
>   at WebGLRenderingContext.getParameter(<anonymous>:13:20)
>   at new Uf(/ajax/libs/three.js/99/three.min.js:32:198)
>   at c(/ajax/libs/three.js/99/three.min.js:152:261)
>   at new be(/ajax/libs/three.js/99/three.min.js:180:467)
>   at apply(sourceMap:7:1)
>   at HTMLDocument.a(../src/integrations/helpers.ts:77:19)

##### Three.js version

- [ ] Dev
- [x] r99
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome _(60.0.3112)_
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Not sure.

**Comment by Mugen87** [comment]
Um, any chances to reproduce the problem? `WebGLRenderingContext` does have a method [.getParameter()](https://developer.mozilla.org/de/docs/Web/API/WebGLRenderingContext/getParameter). I wonder why it's not a function in your case...

**Comment by Mugen87** [comment]
Closing. We can reopen if the OP provide more information about the issue.
