### ISSUE TITLE
"InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer')."

### ISSUE THREAD

**Issue by benguild** [mrdoob/three.js#15492]
##### Description of the problem

We're not using the 'arraybuffer' response type, so I'm assuming that this is from three. Unfortunately, I don't have a stacktrace, though.

##### Three.js version

- [ ] Dev
- [x] r99
- [ ] ...

##### Browser

- [ ] All of them
- [X] Chrome _(71.0.3578)_
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Not sure.

**Comment by donmccurdy** [comment]
Hard to say without a way to reproduce this. If you can share a demo or some code that lets us reproduce the error we can probably help better.

**Comment by Mugen87** [comment]
Closing. We can reopen if the OP provide more information about the issue.

**Comment by basslagter** [comment]
I'm getting the same issue when upgrading to 3.1.4, although on my machine (a Windows 10 laptop) it is complaining about the responseType being 'blob':

"Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'blob')"

If I revert back to 3.1.3, things work as expected. Cannot really figure out why this occurs.

**Comment by donmccurdy** [comment]
Version `3.1.x` of what? The threejs library is at `0.100.0` curently.

**Comment by mrdoob** [comment]
Please, let us know what package is it when you figure it out.

**Comment by pvkamath** [comment]
Saw the exact same problem with Cypress Js v 3.1.4. Upgraded to version 3.1.5 and the problem went away.
