### ISSUE TITLE
Convert concatenated string arrays to template strings

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#15506]
I started to write a script to try to convert all concatenated string arrays into template strings.

In other words

```
var foo = [
  "several",
  "lines",
  "of",
  "text",
].join( "\n" );
```

into

```
var foo = `
  several
  lines
  of
  text
`;
```

but then I realized I should ask before wasting several hours.

Should I do this or no?

**Comment by donmccurdy** [comment]
I think this would be the first ES6 in the library? We don't yet use const/let, classes, etc. The import/export statements don't count, as they're converted automatically by Rollup.

Presumably we'll eventually pull off the bandaid, but not sure what the first step would be, or when.

See https://github.com/mrdoob/three.js/issues/6419

**Comment by greggman** [comment]
There's already lots of this in the library.

See every file in here

https://github.com/mrdoob/three.js/tree/dev/src/renderers/shaders/ShaderChunk

**Comment by donmccurdy** [comment]
Oh, that's a recent change I think? No complaint from me then. :)

**Comment by takahirox** [comment]
I just wanna make clear the purpose of the change because I'm not familiar with template strings. Because the initialization should be faster due to no `.join()`? Or because it's simpler and more readable?

**Comment by looeee** [comment]
It's simpler and more readable for sure. I'm not aware of any initialisation benefit either way, but I expect it's negligible. 

However, the main benefit I can see is that since #15473 was merged, shader code written like this:

``` js
export default /* glsl */`
#ifdef USE_ALPHAMAP
	diffuseColor.a *= texture2D( alphaMap, vUv ).g;
#endif
`;
```

can have have proper syntax highlighting in at least VSCode and Atom editors with just a little bit of setup.

**Comment by greggman** [comment]
Okay well here's a PR

**Comment by donmccurdy** [comment]
> Because the initialization should be faster due to no .join()? Or because it's simpler and more readable? And/or any other benefits?

In any case, they're compiled out for compatibility with older browsers. https://github.com/mrdoob/three.js/blob/dev/rollup.config.js#L161-L191

**Comment by Mugen87** [comment]
Merging into #6419.
