### ISSUE TITLE
TransformControls: Transformation problem with child objects

### ISSUE THREAD

**Issue by Moon-ChangHyun** [mrdoob/three.js#15521]
##### Description of the problem

When an object that have some child objects on scene tree is rotated, the child objects get some malfunction with the TransformControls. In worldSpace cordinate system, there is a difference between the direction of operation and the direction of movement.
And the speed of movement of an object is proportional to the scale of its parents, not to its own scale.
[
![image](https://user-images.githubusercontent.com/44778823/50679594-6d100680-1047-11e9-869d-0f565fb7c147.png)
](url)
This picture is a screenshot of a situation which is problematic through [https://threejs.org/editor].
In this picture I drag up the green axis. But the actual direction of travel was different, as shown by the white solid line.

##### Three.js version

- r100

##### Browser

- All of them

##### OS

- All of them

**Comment by Moon-ChangHyun** [comment]
> Is it possible to demonstrate the problem with a live example? You can use the following fiddle as a starter template (`TransformControls.js` is already included).
> 
> https://jsfiddle.net/f2Lommf5/16918/

Hello, thanks advice. I updated code in the link you append. 
Plz check it out.

**Comment by Mugen87** [comment]
When you edit and save a fiddle, you have to share the new link.

**Comment by Moon-ChangHyun** [comment]
Sorry, I updated it again.
https://jsfiddle.net/f2Lommf5/16926/

**Comment by arodic** [comment]
I'll look into it! It should be easy to fix.

**Comment by arodic** [comment]
Hey @Moon-ChangHyun I believe I have a fix on [this branch](https://github.com/arodic/three.js/tree/fix/15521_transform_controls). I fixed it by transplanting parts of [new implementation that I'm working on](https://github.com/arodic/three.js-controls). I'm afraid that there is a small chance that this fix might introduce regressions since it is transplanted from a completely refactored code.

That being said, I could use some help thoroughly testing this fix before I submit a pull request.

**Comment by Moon-ChangHyun** [comment]
Thanks to your feedback. The bugs I've found seem to have been fixed appropriately.
Will this bug fix be included in the r101 release?

**Comment by arodic** [comment]
Maybe, I'm not sure. Did you had a chance to test controls thoroughly? I'm
concerned that something else might have broke and could use someone else's
eyes just to double check everything manually (since we don't have
automated testing for this).

**Comment by Moon-ChangHyun** [comment]
OK. I will let you know if any problems are found in the revised version.
