### ISSUE TITLE
support getUniformBlockIndex

### ISSUE THREAD

**Issue by lmj01** [mrdoob/three.js#15539]
now three.js support webgl2, so hava any plane to implementation the interface of the webgl2 in task?

**Comment by Mugen87** [comment]
[WebGL2RenderingContext.getUniformBlockIndex()](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/getUniformBlockIndex) is used in context of Uniform Buffer Objects (UBO). There is already an issue that tracks UBOs in context of `three.js`, see #13700. Hence, I suggest to mark this issue as a duplicate and close it.

**Comment by Mugen87** [comment]
Notice #15562
