### ISSUE TITLE
MeshLambertMaterial and HemisphereLight

### ISSUE THREAD

**Issue by bunnybones1** [mrdoob/three.js#15530]
Hemisphere light and shadows appear applied in the wrong order on MeshLambertMaterial, in comparison to MeshPhongMaterial.

Here is a scene with a hemisphere light and a spotlight, using MeshPhongMaterial:
<img width="573" alt="screen shot 2019-01-05 at 1 07 12 pm" src="https://user-images.githubusercontent.com/453513/50727609-2ecc2300-10eb-11e9-9832-0f57cf7a98d6.png">

Here is the same setup, but the materials are MeshLambertMaterial:
<img width="502" alt="screen shot 2019-01-05 at 1 07 22 pm" src="https://user-images.githubusercontent.com/453513/50727613-3986b800-10eb-11e9-9074-e82b9778bb35.png">

Apparently, in phong's case, the shadows are applied before being re-illuminated with the hemisphere light, but in lambert's case, it looks like the hemisphere applies its illumination to the vertex color in the vertex shader, making it impossible to "re-illuminate" the shadow samples in the fragment shader. Passing an extra light color varying to the fragment for shadow re-illumination could be a solution. I'll try this and report back within a few days.

I should note that using Lambert with shadows and a hemisphere light has a relatively inexpensive but beautiful aesthetic.

I'm using THREE r100.

**Comment by Mugen87** [comment]
Can you please demonstrate the issue with a simple [live example](https://jsfiddle.net/f2Lommf5/)?

**Comment by WestLangley** [comment]
>Hemisphere light and shadows appear applied in the wrong order on MeshLambertMaterial, in comparison to MeshPhongMaterial.

That is not exactly the issue. Hemisphere lights are treated as direct lights in the Lambert shader. However, they are not direct lights; they are indirect lights -- a poor man's model for global illumination.

In fact, the following two lights should provide the same illumination -- and they don't with `MeshLambertMaterial` when shadows are present:
```javacript
new THREE.AmbientLight( 0xffffff, 1 );
new THREE.HemisphereLight( 0xffffff, 0xffffff, 1 );
```

Another problem is shadows in `MeshLambertMaterial` are a hack -- they mask all direct light. This is an consequence of performing lighting calculations in the vertex shader. We can't fix that.

However, we can fix the artifact you are seeing by correctly treating hemisphere lights as an indirect light source in the shader.
