### ISSUE TITLE
Camera orientation affects PointLight on MeshPhongMaterial

### ISSUE THREAD

**Issue by lastant** [mrdoob/three.js#15534]
When the camera's position is close to an axis, changing its orientation (without changing the position of the camera, of the PointLight source and of the MeshPhongMaterial mesh) affects the illumination by the light source. See screenshots (StereoEffect renderer) made from one camera position and different camera orientations. There are four different illuminations, only two are shown here. The light source is behind the Earth, far away. 
I read somewhere that PointLight is actually a combination of 6 segments, so maybe if the camera is close to their border, its orientation can affect which segment is activated?
Three.js used is r100.

![screenshot_2019-01-06-20-21-44-394_ch astrate spacevr](https://user-images.githubusercontent.com/1300156/50739210-ca9a8380-11fe-11e9-865c-dbf5db8e2eee.png)
![screenshot_2019-01-06-20-21-55-461_ch astrate spacevr](https://user-images.githubusercontent.com/1300156/50739211-cb331a00-11fe-11e9-92e6-1ef18b595fd4.png)

**Comment by Mugen87** [comment]
Can you please demonstrate the issue with a [live example](https://discourse.threejs.org/)?
