### ISSUE TITLE
HTTPS Mixed Content Error trying to load hosted stl file

### ISSUE THREAD

**Issue by taibhse-designs** [mrdoob/three.js#15535]
##### Description of the problem

When trying to load an stl file hosted and stored beside the core html file of my project, I receive the following error, 

`Mixed Content: The page at 'https://website.ie/3dprintcalc/3d.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.website.com/404.html'. This request has been blocked; the content must be served over HTTPS.`

This is the code used to load my stl which is causing the issue, 
```

 var loader = new THREE.STLLoader();
            loader.load('adam.stl', function(geometry) {


                default_mesh = new THREE.Mesh(geometry, material);
                default_mesh.receiveShadow = true;
                default_mesh.castShadow = true;


                scene.add(default_mesh);

            });

```

I cannot see a way to force or ensure content is loaded over https, unsure if this is a bug or a required feature as this prevents being able to use content on a secure page.

##### Three.js version

latest

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
