### ISSUE TITLE
Consider providing a converter for old JSON models

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#15547]
With JSONLoader moving out of the core library and requiring BufferGeometry conversion to render, we should consider providing a converter (based on https://github.com/mrdoob/three.js/tree/dev/utils/converters) to upgrade old JSON models to the new JSON format or glTF. 

For example:

```
node legacythree2gltf.js model.json
```

**Comment by donmccurdy** [comment]
I'll have a go at this, if there are no suggestions otherwise. Example models would be helpful, otherwise I'll just start with the list in https://github.com/mrdoob/three.js/issues/14737. There are a few edge cases (e.g. lightmaps) we can't currently export to glTF.

**Comment by donmccurdy** [comment]
Made some progress: https://github.com/mrdoob/three.js/pull/15552

**Comment by Mugen87** [comment]
Closing due to #17976.
