### ISSUE TITLE
BufferGeometry.computeVertexNormals ingores drawRange

### ISSUE THREAD

**Issue by linev** [mrdoob/three.js#15560]
BufferGeometry.computeVertexNormals() function produces wrong results when setDrawRange is specified. Especially when start index is not multiple of 3 - for instance after calling bufGeom.setDrawRange(2, 300).

This loop should include check of drawRange values:

https://github.com/mrdoob/three.js/blob/dev/src/core/BufferGeometry.js#L713

Same problem is with BufferGeometry.normalizeNormals() function.

**Comment by linev** [comment]
If necessary, I could easily provide PR solving the problem

**Comment by WestLangley** [comment]
That was done on purpose. `drawRage` is for drawing.

**Comment by linev** [comment]
> That was done on purpose. drawRage is for drawing.

Normals are also for drawing. And they calculated wrong. 
Additional problem - if same BufferAttribute shared between geometries, computeVertexNormals() changes data which does not belong to geometry itself.

**Comment by WestLangley** [comment]
`.computeVertexNormals()` computes all the normals for the entire geometry -- not just some of them. This was a design decision.

`.drawRange` only controls which vertices are rendered.

**Comment by linev** [comment]
> .computeVertexNormals() computes all the normals for the entire geometry -- not just some of them. This was a design decision.

Fine. 
It means, index should only contain vertex indexes and nothing else.
I was trying to misuse large int32array for different purposes.
