### ISSUE TITLE
RectAreaLightHelper not working on npm distribution

### ISSUE THREAD

**Issue by david-campos** [mrdoob/three.js#15579]
##### Description of the problem
RectAreaLightHelper from 'three' package installed via npm is not working, it seems to try to use at some point THREE.BackSide, but THREE is not existent in the file (it has not been imported) so the construction of a RectAreaLightHelper fails.

To recreate the bug simply install the npm version of three as indicated in the documentation
`npm install three`
and run some code like:
```
import {RectAreaLight, RectAreaLightHelper} from "three";

var light = new RectAreaLight();
var helper = new RectAreaLightHelper(light);
```

When reaching the construction of the new helper, the script fails.

##### Screenshot
Here we can see the error in build/three.module.js inside the node_modules folder, seen from Chrome developer tools:
![Imgur](https://i.imgur.com/G9EQPCp.png)

##### Three.js version
npm distribution, three 0.100.0

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Will happen on any

**Comment by Mugen87** [comment]
Yeah, the usage of the `THREE` namespace at this place is invalid. The PR should fix the issue.

**Comment by david-campos** [comment]
Checking now the file I noticed this bug appears in ArrowHelper too, it uses THREE.Vector3 :)
