### ISSUE TITLE
CanvasTexture: Strange shadow

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#15575]
##### Description of the problem
`THREE.CanvasTexture` has strange shadow with `ctx.fillStyle = "#ffffff";`

A live example:
* [codepen](https://codepen.io/anon/pen/YddrGG) (latest release branch)

Screenshot:
![image](https://user-images.githubusercontent.com/23699926/51093292-1e980000-17dd-11e9-83e4-cae8c70834fe.png)

##### Three.js version
- [x] r100

##### Browser
- [x] Chrome
- [x] Firefox

##### OS
- [x] Windows

**Comment by looeee** [comment]
It's to do with the fact that outside the circle is transparent - if you set the scene background to black you'll see this:

`scene.background = new THREE.Color( 0x000000 )` 

![download](https://user-images.githubusercontent.com/5307958/51094165-a97cf880-17e5-11e9-9473-a786ab31458f.png)

**Comment by linbingquan** [comment]
> It's to do with the fact that outside the circle is transparent - if you set the scene background to black you'll see this:
> 
> `scene.background = new THREE.Color( 0x000000 )`

I mean `Canvas` has not strange shadow with `getCanvasDom()`, such as this example in [codepen](https://codepen.io/anon/pen/pqqdRv) 

```js
function getCanvasDom() {
  var WIDTH = 512
  var canvasDom = document.createElement("canvas");
  canvasDom.width = WIDTH;
  canvasDom.height = WIDTH;
  var ctx = canvasDom.getContext("2d");
  ctx.fillStyle = "#ffffff";
  ctx.strokeStyle = "#ffffff";
  ctx.arc( WIDTH / 2, WIDTH / 2, 250, 0, 2*Math.PI, true );
  ctx.fill();

  return canvasDom;
}
var canvasDom = getCanvasDom();
document.body.appendChild( canvasDom );
```
canvas screenshot:
![image](https://user-images.githubusercontent.com/23699926/51094345-062ce300-17e7-11e9-937b-86af32b8b486.png)

**Comment by looeee** [comment]
Even though that canvas looks fully white, the part outside the circle is actually transparent and showing the color behind it.

I'm not sure commenting on whether this is expected behavior or not BTW, I just wanted to share my observations on why it's happening.

**Comment by WestLangley** [comment]
Please use the [forum](https:discourse.threejs.org) for help.
