### ISSUE TITLE
clipAction doesn't work after material changed to MeshDepthMaterial 

### ISSUE THREAD

**Issue by shengchiliu** [mrdoob/three.js#15570]
I tried to show depth map using MeshDepthMaterial in this example
https://threejs.org/examples/#webgl_morphtargets_horse

However, the animation didn't work, after the material changed to MeshDepthMaterial.
My question is that how can show the animation in the depth material?

**Comment by WestLangley** [comment]
It works just fine.
```javascript
camera = new THREE.PerspectiveCamera( 50, window.innerWidth / window.innerHeight, 400, 800 );

...

mesh.material = new THREE.MeshDepthMaterial( { morphTargets: true, depthPacking: THREE.BasicDepthPacking } );
```

Please use the three.js [forum](https://discourse.threejs.org) if you need more help.

**Comment by shengchiliu** [comment]
It works! Thanks a lot!
