### ISSUE TITLE
How to render multi scenes in  VR

### ISSUE THREAD

**Issue by zhudongwork** [mrdoob/three.js#15586]
##### Description of the problem

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/3foLr7sn/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/qgu17w5o/) (dev branch)
* [codepen](https://codepen.io/anon/pen/aEBKxR) (latest release branch)
* [codepen](https://codepen.io/anon/pen/BJWzaN) (dev branch)

##### Three.js version

- [ ] Dev
- [ ] r100
- [x] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
I wanted to render multi scenes with a renderer in vr.
My code was like that:
`function animate() {

				renderer.setAnimationLoop( render );

			}
function render() {
				renderer.render( scene, camera );
				renderer.render( scene1, camera );
			}`

**Comment by Mugen87** [comment]
Please sue the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
