### ISSUE TITLE
OrbitControls: ReferenceError THREE is not defined

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#15583]
I'm not sure it's the best way to fix this error, but I delete `THREE.` can fixed `ReferenceError`, like:
```js
OrbitControls.prototype.constructor = OrbitControls;
```

Error screeshot:
![image](https://user-images.githubusercontent.com/23699926/51169085-f6e08f00-18e5-11e9-9bfb-513d9a53b90d.png)

**Comment by Mugen87** [comment]
Should be solved via #15582
