### ISSUE TITLE
Add Stencil Function Material Properties

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#15603]
At the moment writing to the stencil buffer is a bit inconvenient (and undocumented). Would it make sense to add material property that defines the stencil operations? Here's an idea of what the API might look like:

```js
// Render where a mesh intersects the rest of the world
const frontFaceMat = new MeshBasicMaterial();
frontFaceMat.side = FrontSide;
frontFaceMat.depthWrite = false;
frontFaceMat.colorWrite = false;
frontFaceMat.stencil = {
    func: ALWAYS,
    ref: 0,
    mask: 0xff,

    fail: KEEP,
    zfail: KEEP,
    zpass: INCR_WRAP
};

const backFaceMat = new MeshBasicMaterial();
backFaceMat.side = BackSide;
backFaceMat.depthWrite = false;
backFaceMat.colorWrite = false;
backFaceMat.stencil = {
    func: ALWAYS,
    ref: 0,
    mask: 0xff,

    fail: KEEP,
    zfail: KEEP,
    zpass: DECR_WRAP
};

const intersectionMat = new MeshBasicMaterial();
intersectionMat.depthWrite = false;
intersectionMat.depthTest = false;
intersectionMat.opacity = 0.25;
intersectionMat.color.set(0xff0000);
intersectionMat.stencil = {
    func: NOTEQUAL,
    ref: 0,
    mask: 0xff,

    fail: REPLACE,
    zfail: REPLACE,
    zpass: REPLACE
};

const materials = [ frontFaceMat, backFaceMat, intersectionMat ];
const intersectionGroup = SceneUtils.createMultiMaterialObject( geometry, materials );
```

Of course this depends on the meshes in the `intersectionGroup` being run _in order_ and _after everything we want to intersect_, which the default webgl renderer object sort would probably mess up but maybe there are ways around that I'm unaware of?

**Comment by WestLangley** [comment]
>Would it make sense to add material property that defines the stencil operations?

Yes. I am at a loss to recall why we did not do that in the first place.

In fact, adding an example along the lines of your suggestion would be very beneficial.

---

Adding a link to [this SO answer](https://stackoverflow.com/a/54238011/1461008) and, in particular, my subsequent comments. I think making gl calls behind the back of the renderer is unadvisable.

**Comment by gkjohnson** [comment]
> I think making gl calls behind the back of the renderer is unadvisable.

I agree -- is setting the `renderOrder` on a material currently the only way to guarantee geometry get's drawn in a specific order?

**Comment by gkjohnson** [comment]
Made quick PR here: https://github.com/mrdoob/three.js/pull/15611

**Comment by WestLangley** [comment]
>I think making gl calls behind the back of the renderer is unadvisable.
>>I agree -- is setting the renderOrder on a material mesh currently the only way to guarantee geometry get's drawn in a specific order?

I think you may have misunderstood what I was trying to say.... The user should be calling `renderer.state` methods, instead of webgl methods, to prevent the renderer state and webgl state from getting out of sync.
