### ISSUE TITLE
TDSLoader can't get full child name

### ISSUE THREAD

**Issue by pegasus1982** [mrdoob/three.js#15607]
When I try to load `3DS` file, I can't get full child name
For example
I named an object "CG1-boxArmSeat" in 3DS Max 2016
But I can only get name : "CG1-boxA" in three.js
How to fix this issue?

**Comment by Mugen87** [comment]
Can you please share the 3DS file in this thread?

**Comment by RemusMar** [comment]
3DS is a DOS format, file names are limited to 12 characters: 8 for the name proper, '.' (dot), and a 3-character file-name extension. 

https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2017/ENU/3DSMax/files/GUID-E4C19A8E-F941-44F8-A2AB-0A2DF80656E3-htm.html
