### ISSUE TITLE
[Feature] Support plugin install pattern

### ISSUE THREAD

**Issue by AmyFoxFN** [mrdoob/three.js#15612]
Hi, the contributors of three

Thanks for writing the amazing 3D lib, it's really good to use and give us a lot of help to develop beautiful 3D objects.

However, there is something bother me, when I am trying to `import 'three/examples/js/controls/OrbitControls'` as an extend method to THREE in the develop mode of ES6 modules. Such as the identifier of `THREE` would be undefined without handle it in Webpack, like what happened in https://github.com/mrdoob/three.js/issues/15583. And the OrbitControls can't be control as a module. It makes little inconvenient and out of style in the age of **Modularization Development**.

I have seen the PR https://github.com/mrdoob/three.js/pull/14803, https://github.com/mrdoob/three.js/pull/15582. But I think, it's not only about **Modularization**, but also something  about **the develop pattern of how to extend plugin to three**.

Maybe The plugin pattern could be like:
```js
import * as THREE from 'three'
import OrbitControlsPlugin from '@threejs/plugin-orbit-controls'

// Register and install a plugin.
THREE.use(OrbitControlsPlugin)

// After register, we could use the extend method.
THREE.OrbitControls()
```

It will be really nice if you @mrdoob  @Mugen87 could help. Thanks a lot!

**Comment by donmccurdy** [comment]
Converting the examples to ES modules (as begun in 
https://github.com/mrdoob/three.js/pull/15518) effectively solves this. There is no registration or installation required:

```js
import { Scene } from ‘three’;
Import { OrbitControls } from ‘three/examples/jsm/controls/OrbitControls.js’;

const controls = new OrbitControls();
```

The user can still attach things to the THREE namespace if they wish, but it isn’t required or global.

**Comment by AmyFoxFN** [comment]
Thank your very much.
But I'm still refuse about if the THREE will be reported to be undefined, when I import  ‘three/examples/jsm/controls/OrbitControls.js’.

as there is a line in [the OrbitControls.js](https://github.com/mrdoob/three.js/pull/15518/files#diff-3285de3826a51619836a5c9adc6bee74) of #15518 :
```
OrbitControls.prototype.constructor = THREE.OrbitControls;
```

**Comment by donmccurdy** [comment]
This is still a work in progress; that issue will be fixed by https://github.com/mrdoob/three.js/pull/15582. In the end the example modules shouldn't reference the `THREE` namespace directly at all.

**Comment by AmyFoxFN** [comment]
That's pretty good. Thanks a lot!
