### ISSUE TITLE
The new SSAO not working on iOS

### ISSUE THREAD

**Issue by easyfrog** [mrdoob/three.js#15617]
##### Description of the problem

https://threejs.org/examples/?q=ssao#webgl_postprocessing_ssao

use iPhone safari open this link.  will get a black screen result.
So is it ssao not support iOS? 

##### Three.js version

- [ ] Dev
- [x] r100
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

**Comment by easyfrog** [comment]
> Do you see any warnings or error messages in the browser console? Besides, does this also happen with Chrome or Firefox on iOS? How old is your iPhone (which version)?
> 
> The implementation relies on the `WEBGL_depth_texture` extension. It might be not available on your hardware.

Thank you for your replay.

I test with iPhone7 and iPhoneX max.  but only on safari.
And all of them got black screen like this: 
![wechatimg3629](https://user-images.githubusercontent.com/10724325/51439647-3b11cc00-1cf8-11e9-8665-ab1fc0286c12.png)

**Comment by easyfrog** [comment]
@Mugen87 It looks like SSAO shader's uniforms count is beyound iOS limit.

**Comment by Mugen87** [comment]
Do you have similar problems with other post processing effects?

https://threejs.org/examples/?q=postporcessing

**Comment by easyfrog** [comment]
@Mugen87 
Yes  I test other postprocessting.  All works fine except "SSAO" example.  So I think this is not a Divice problem , is a Compatible problem.

this is some screenshot:

SAO: 
![1181548061653_ pic](https://user-images.githubusercontent.com/10724325/51465344-b465f900-1da2-11e9-9889-2632e96c868e.jpg)

Bloom:
![1191548061692_ pic](https://user-images.githubusercontent.com/10724325/51465358-bc259d80-1da2-11e9-8105-203f74424fed.jpg)

SSAO:
![1201548061769_ pic](https://user-images.githubusercontent.com/10724325/51465371-c5166f00-1da2-11e9-8200-3aa0da3f9639.jpg)

**Comment by Mugen87** [comment]
Does the following depth of field demo work?

https://threejs.org/examples/webgl_postprocessing_dof2

The respective shader uses a comparable amount uniforms.

**Comment by easyfrog** [comment]
@Mugen87 
I don't know how to show the uniforms count number.
But this demo works fine.

![wechatimg121](https://user-images.githubusercontent.com/10724325/51468120-1f1a3300-1da9-11e9-81a3-b1951f650953.jpeg)

**Comment by Mugen87** [comment]
Sry, I don't have an iPhone so I'm unable to reproduce. The implementation works fine on my Pixel (1) and also with Safari macOS.

Can you please post the warning message (the yellow part of the log) of your browser console? It's not necessary to share the entire code, just the message at the top of the section.

**Comment by easyfrog** [comment]
@Mugen87 
The SSAO works perfect on My android phone too and looks very nice.

I saw the log message. and it seems useless. same as the error message.
So I think it's better to test on a iPhone device.

![wechatimg122](https://user-images.githubusercontent.com/10724325/51471863-d5364a80-1db2-11e9-8112-d323e087d657.jpeg)

**Comment by TimvanScherpenzeel** [comment]
My iPhone 8 (Safari, iOS 12.1.2) reports support for 64 fragment uniform vectors and 128 vertex uniform vectors using [detect-features](https://timvanscherpenzeel.github.io/detect-features/). I can also confirm that the SSAO demo does not work on my iPhone either.

**Comment by easyfrog** [comment]
> My iPhone 8 (Safari, iOS 12.1.2) reports support for 64 fragment uniform vectors and 128 vertex uniform vectors using [detect-features](https://timvanscherpenzeel.github.io/detect-features/). I can also confirm that the SSAO demo does not work on my iPhone either.

My Android phone :  vertex and fragment are both 256.
iPhone 7 and iPhone x :  fragment is 64, vertex is 128.

**Comment by Mugen87** [comment]
I remember a similar issue with other examples: #7807

I would be good to know if you experience the problem with any other examples of `three.js`. In any event, I'm a bit surprised that this warning is not triggered with other shaders...

**Comment by easyfrog** [comment]
I try to change these three unifroms `kernelRadius`,  `minDistance`, `maxDistance` of `SSAOShader`  to normal variable. But still alert `too many uniforms` error.
So,  have other solutions?

**Comment by Mugen87** [comment]
Does the following example work for you?

https://threejs.org/examples/webgl_depth_texture

I'd like to know if it's not a problem related to `WEBGL_depth_texture` extension. Besides, please test the SSAO example with Chrome, too.

**Comment by TimvanScherpenzeel** [comment]
> Does the following example work for you?
> 
> https://threejs.org/examples/webgl_depth_texture
> 
> I'd like to know if it's not a problem related to the `WEBGL_depth_texture` extension. Besides, please test the SSAO example with Chrome, too.

Runs fine on my iPhone 8 (Safari & Chrome, iOS 12.1.2) though noticeably a bit less precise when compared to desktop. The SSAO example fails on both browsers (likely because both are WebKit based).

**Comment by Mugen87** [comment]
I have tested the demo today with an old laptop from 2012 that has a [Intel Ivy Bridge Mobile GPU](https://www.notebookcheck.net/Intel-HD-Graphics-Ivy-Bridge.85998.0.html). The Hardware is definitely weaker than modern iPhone GPUs. The SSAO example runs with just 16 FPS but without a runtime error. Interestingly, the Intel GPU supports 4096 vertex and fragment uniforms.

TBH, I can't believe that the amount of uniforms of the SSAO shader is responsible for the error. What happens when the example is changed so that only a single box is rendered?

**Comment by easyfrog** [comment]
@Mugen87   
hi, How many uniforms does the old laptop support?  You can get the info use [detect-features](
https://timvanscherpenzeel.github.io/detect-features/)

The newest iPhone xs Max only support maxFragmentUniform is **64** and maxVertexUniform is **128**.
But even the old Mac or PC both of the uniforms support **1024**. I think this is the key point.

**Comment by Mugen87** [comment]
> How many uniforms does the old laptop support?

Already note this in my previous post. 4096 for both fragment and vertex shader.

**Comment by Mugen87** [comment]
There was lately a change in `dev` that removed a special format of a data texture. Does it make any difference on your iPhones?

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_postprocessing_ssao.html

**Comment by Mugen87** [comment]
I have manually counted the uniforms of the SSAOShader in the vertex and fragment shader. It uses 6 uniforms in the vertex shader and 17 in the fragment. If the mentioned limit of 128 and 64 uniforms refers to a single shader program, the SSAO shader should have enough room.

**Comment by WestLangley** [comment]
From https://webglstats.com/webgl/parameter/MAX_FRAGMENT_UNIFORM_VECTORS

>MAX_FRAGMENT_UNIFORM_VECTORS
>The maximum number of 4-element vectors that can be passed as uniform to the vertex shader.
>All uniforms are 4-element aligned, a single uniform counts at least as one 4-element vector.

```glsl
uniform vec2 resolution;                      1
uniform vec3 cameraPosition;                  1
uniform vec3 kernel[ KERNEL_SIZE ];           KERNEL_SIZE (default 64)
uniform mat4 viewMatrix;                      4
uniform mat4 cameraProjectionMatrix;          4
uniform mat4 cameraInverseProjectionMatrix;   4
```

So, `KERNEL_SIZE` needs to be no larger than __50__ to limit the total to __64__.

**Comment by Mugen87** [comment]
@easyfrog Can you try to lower the kernel size on 32 and see whats happening?

**Comment by easyfrog** [comment]
@Mugen87 @WestLangley
Yes, I change kernel size from 64 to 32 both SSAOPass and SSAOShader.  Finally It works! 
But there is some artifacts When the camera is approximately perpendicular to the surface of the object.

![kkk](https://user-images.githubusercontent.com/10724325/51790372-4c167d80-21cf-11e9-9b86-1b6a1e468861.png)

**Comment by Mugen87** [comment]
@easyfrog Can you please post how the depth map looks like on your iPhone? Just choose the "Depth" output setting from the UI controls.

**Comment by WestLangley** [comment]
@easyfrog See https://stackoverflow.com/questions/45446609/incorrect-depthtexture-with-ssao/45497578#45497578.

**Comment by mrdoob** [comment]
Should we set `KERNEL_SIZE` to `32` by default?

**Comment by Mugen87** [comment]
I've originally used `64` since it was the recommended kernel size in this [implementation](https://learnopengl.com/Advanced-Lighting/SSAO). But I have seen no that an [other one](https://github.com/McNopper/OpenGL/blob/aa0d6a00b2706ea87f40afd5965f74704c6df4e3/Example28/shader/ssao.frag.glsl#L3) uses `32`. Let's try out this value and see how it goes.

**Comment by Mugen87** [comment]
@easyfrog Have you tried the approach mentioned at stackoverflow? Do the artifacts go away by changing the `near` and `far` values of the camera?

**Comment by Mugen87** [comment]
> I can not set it up manually.

`SSAOPass` uses the values from the given camera. It should be no problem for you to change these values in your code.

https://github.com/mrdoob/three.js/blob/18e4439b555a7e175f44b9051c1755b7d90448f9/examples/js/postprocessing/SSAOPass.js#L85-L86

**Comment by WestLangley** [comment]
>What is the best value of near and far

@easyfrog Set `camera.near` as large as possible and set `camera.far` so the scene bounding sphere is contained in the front half of the frustum.

Read about _depth precision_ in http://www.songho.ca/opengl/gl_projectionmatrix.html.

**Comment by Mugen87** [comment]
I guess the issue can be considered as fixed. If you still need help configuring your camera, please use the [forum](https://discourse.threejs.org/) or stackoverflow.
