### ISSUE TITLE
OrbitControls Keyboard controls don't work when in an Iframe

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#15619]
##### Description of the problem

The keyboard for OrbitControls don't work in an iframe. The reason is the `mousedown` handler calles `preventDefault`. Part of that default is the iframe getting the focus

See this example: https://jsfiddle.net/3foLr7sn/ or this one  https://jsfiddle.net/qgu17w5o/   both are the default bug report examples

Drag on the sphere then press the arrow keys. Note they don't work

##### Three.js version

- [X] Dev
- [X] r100

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

N/A

**Comment by Mugen87** [comment]
Related #9437
