### ISSUE TITLE
FirstPersonControls should repect intial object rotation

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#15629]
Consider this to be a feature request, I guess? Both #3010 and #6551 were closed as help, and [all](https://stackoverflow.com/questions/14638135/firstpersoncontrols-start-by-looking-at-an-object) [of](https://stackoverflow.com/questions/13474434/three-js-first-person-controle-makes-objects-disappears-from-scene) [relevant](https://stackoverflow.com/questions/24819945/three-js-loaded-model-is-disappearing-while-switch-to-firstperson-control-from-o/25045425#25045425) [SO](https://stackoverflow.com/questions/20905101/three-js-firstperson-control-start-orientation/20906487#20906487) [questions](https://stackoverflow.com/questions/14638135/firstpersoncontrols-start-by-looking-at-an-object/14638753#14638753) are either unanswered, or the answer is "set lat and lon".

So why dont you set lat and lon to the values corresponding to object.rotation rather than to 0 in FirstPersonControls constructor?

**Comment by makc** [comment]
This is the patch I applied on the project:
```javascript
//	this.lat = 0;
//	this.lon = 0;
//	this.phi = 0;
//	this.theta = 0;
	var target = new THREE.Vector3(0, 0, -1);
	var matrix = new THREE.Matrix4();
	object.updateMatrix();
	matrix.extractRotation(object.matrix);
	target.applyMatrix4(matrix);
	this.phi = Math.acos(target.z / target.length());
	this.theta = Math.atan2(target.y, target.x);
	this.lat = 90 - THREE.Math.radToDeg(this.phi);
	this.lon = THREE.Math.radToDeg(this.theta);
```
Idk if it is entirely correct, because I had to add PI/2 to object.rotation.y in another place (suspected loader problem) but maybe this patch has a bug.

**Comment by Mugen87** [comment]
I think the feature request is valid. I just wonder if the implementation could raise wrong expectations. What if a user wants to use `camera.lookAt()` during rendering? In this case, the computed rotation would be overwritten by `FirstPersonControls`.

**Comment by mrdoob** [comment]
Would a `controls.setOrientation()` do the trick?

**Comment by Mugen87** [comment]
Yeah, i think so 👍

**Comment by makc** [comment]
as long as it works :)

**Comment by Mugen87** [comment]
It worked on my computer^^. Let me do a PR 👍
