### ISSUE TITLE
SSAO bug on webgl2

### ISSUE THREAD

**Issue by lp249839965** [mrdoob/three.js#15623]
when change the context to webgl2, the example of ssao will console 
### invalid internalformat/format/type combination GL_LUMINANCE/GL_LUMINANCE/GL_FLOAT
the SSAOPass.js code use THREE.LuminanceFormat for noiseTexture lead to that console

**Comment by Mugen87** [comment]
What happens if you change the format parameter in the following line to `THREE.RGBAFormat`?

https://github.com/mrdoob/three.js/blob/4ca3860851d0cd33535afe801a1aa856da277f3a/examples/js/postprocessing/SSAOPass.js#L384

**Comment by Mugen87** [comment]
You can fix this problem by switching to `THREE.RGBAFormat` and adjusting the generation of the data texture accordingly. Would you like to do a PR with the change.
