### ISSUE TITLE
Vector3.multiplyScalar(-1) invalid result when have 0 as component

### ISSUE THREAD

**Issue by mrbianchi** [mrdoob/three.js#15625]
Vector3.multiplyScalar(-1) on a vector with 0 as components makes the result with "-0"
when you compare the result with equals , the "-0" isnt taked as "0" , then the result is invalid

**Comment by linbingquan** [comment]
I debuged example `webgl_interactive_voxelpainter.html` also has this issue, `normal.y` is `-0`.

![image](https://user-images.githubusercontent.com/23699926/51521002-3cf69f00-1e60-11e9-8f36-a36c726f5e95.png)

**Comment by Mugen87** [comment]
> when you compare the result with equals , the "-0" isnt taked as "0" 

I don't think this is true. Have a look at the following live demo: https://jsfiddle.net/n2mz6puj/

`+0 === -0` evaluates to `true`. This is also true for all `Vector3`.

**Comment by mrbianchi** [comment]
Lost the point, I cant reproduce it, I close it
