### ISSUE TITLE
encodings_pars_fragment: Bug in vector/matrix multiplication 

### ISSUE THREAD

**Issue by AngusLang** [mrdoob/three.js#15621]
https://github.com/mrdoob/three.js/blob/2ad018c7c7ad103c9da9d7f22b3154537384ab26/src/renderers/shaders/ShaderChunk/encodings_pars_fragment.glsl.js#L82

when i use these lines of code to convert logluv color space data to linear space. render result shows that there is only blue channel preserved. so I read the original page above. The problem is 
```javascript
float3 vRGB = mul(Xp_Y_XYZp, InverseM);
```
is not the same as
```javascript
vec3 vRGB = Xp_Y_XYZp.rgb * cLogLuvInverseM;
```
.
so i move `cLogLuvInverseM` matrix to the left, problem solved.

**Comment by WestLangley** [comment]
@Mugen87 

1. Can you make the same argument for `LinearToLogLuv()`?

3. Are `cLogLuvM`and `cLogLuvInverseM` transposed?

3. How did you test this?

**Comment by WestLangley** [comment]
Please read this thread: https://stackoverflow.com/questions/16578765/hlsl-mul-variables-clarification.
