### ISSUE TITLE
ObjectLoader still creates multiple materials with same uuid

### ISSUE THREAD

**Issue by mixtur** [mrdoob/three.js#15635]
looks like [this](https://github.com/mrdoob/three.js/issues/15152) is still a problem in one case.

So to remind. In old format with MultiMaterials, ObjectLoader may create multiple materials with the same uuid. After [this PR](https://github.com/mrdoob/three.js/pull/15128) Something like

```
MultiMaterialA = [X, Y]
MultiMaterialB = [X, Z]
```

no longer triggers that problem

but this does

```
Material = X
MultiMaterial = [X, Y]
```

**Comment by Mugen87** [comment]
Are you interested in making PR like last time in order to solve the issue?

**Comment by mixtur** [comment]
Sure. But it may take a while, I am a little busy now.
