### ISSUE TITLE
Postprocessing examples stopped working on Fairphone 2.0 (Adreno 330)

### ISSUE THREAD

**Issue by jagracar** [mrdoob/three.js#15633]
Some of the postprocessing examples stopped working on my mobile.

For example, this example only shows a black screen:

https://threejs.org/examples/?q=pos#webgl_postprocessing

I had a look at the console output and I get some warnings, but I don't know if that's the problem, because the same example was working some months ago:

  THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.
  THREE.WebGLRenderer: ANGLE_instanced_arrays extension not supported.
  THREE.WebGLRenderer: OES_texture_float_linear extension not supported.

##### Three.js version

- [ ] Dev
- [x] r100
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Comment by Mugen87** [comment]
What mobile device and what version of mobile Chrome are you using? Does it also happen with Firefox?

**Comment by jagracar** [comment]
Hi @Mugen87 

Chrome 71.0.3578.99 running on a Fairphone 2.0 with Android 7.1.2

I also tried Firefox and I've got the same black screen result

**Comment by jagracar** [comment]
Sorry, I just closed the issue by mistake...

**Comment by jagracar** [comment]
I have to check it again, but some weeks ago I had the same problem with an iphone. Will check later.

**Comment by jagracar** [comment]
In case it helps to understand the problem, in this example I can see the backgrounds, but the heads are black:
https://threejs.org/examples/?q=pos#webgl_postprocessing_advanced

**Comment by Mugen87** [comment]
Um, it's not the first time that users report problems in context of Adreno 300 GPUs, see #9988. If this is actually a similar device/driver issue, there will be most likely no fix.

**Comment by jagracar** [comment]
Thanks @Mugen87  

Indeed that could be the problem. I will investigate a bit. I'm quite sure the examples were running fine in previous three js versions. I will test it and if the problem persists with older versions then the graphics driver update is probably the reason.

**Comment by jagracar** [comment]
Hi again,

I tested the example with older versions of three.js and the problem persists. 

It's most probably related with the update to Android 7 that took place last November:
https://support.fairphone.com/hc/en-us/articles/208342503-Fairphone-OS-for-Fairphone-2-Release-Notes

I found this issue which indicates that OpenGL 3.0 is not enabled in that particular Android version:
  https://bugtracker.fairphone.com/project/fairphone-android-7/issue/56

Thank you for help with this. If you come to Munich one day I buy you a beer!

**Comment by jagracar** [comment]
Finally! After reading your comments in #14137 i tried the proposed solution:

https://github.com/mrdoob/three.js/issues/14137#issuecomment-397843382

and it worked nicely for me :)

It seems that the software update from Android 6 to 7 created the problem, but switching my THREE.MeshPhongMaterial to mediump resolved it.

My postprocessing examples now work fine:
https://webgl-shaders.com/badtv-example.html

Thank you  everybody for your help!

**Comment by mrdoob** [comment]
@Mugen87 I guess it's worth testing what post processing shaders could work as mediump.

**Comment by Mugen87** [comment]
Yes. But desktops automatically use `highp` no matter what precision you set in the shader. The following fiddles represent some of our post-processing examples in `mediump`. Test with a Pixel 1.

Does not work:
- [webgl_postprocessing](https://jsfiddle.net/nryjqf93/show) (moire pattern)
- [webgl_postprocessing_dof](https://jsfiddle.net/dg9kvrp6/show) (no blur)
- [webgl_postprocessing_dof2](https://jsfiddle.net/1Lkheyaj/show)(moire pattern, wrong focus area)
- [webgl_postprocessing_advanced](https://jsfiddle.net/dg9kvrp6/2/show) (heads are black, background flickers)
- [webgl_postprocessing_sao](https://jsfiddle.net/hucbr586/1/show) (occluded areas look scattered)
- [webgl_postprocessing_glitch](https://jsfiddle.net/usn3xj2c/) (moire pattern)
___
Does work:
- [webgl_postprocessing_afterimage](https://jsfiddle.net/6uc89qjs/4/show)
- [webgl_postprocessing_godrays](https://jsfiddle.net/trgwhc6s/show)
- [webgl_postprocessing_masking](https://jsfiddle.net/usn3xj2c/1/show)
- [webgl_postprocessing_outline](https://jsfiddle.net/qd201rhs/show)
- [webgl_postprocessing_pixel](https://jsfiddle.net/xwnbqrc3/show)
- [webgl_postprocessing_sobel](https://jsfiddle.net/7gfxLrnh/)
- [webgl_postprocessing_ssao](https://jsfiddle.net/9bzh15qv/show)
- [webgl_postprocessing_unreal_bloom](https://jsfiddle.net/6uc89qjs/5/show)

It seems quite a bit of work to ensure that certain shaders also work in `mediump`. I think a first step could be to find out why the mentioned moire pattern is produced...

**Comment by Mugen87** [comment]
Interesting. I have analyzed the dot-screen shader of `webgl_postprocessing` and realized that the moire pattern is not produced by the related shader code. The actual problem is setting `MeshPhongMaterial.flatShading` to `true`. So the moire pattern might be related to the derivate functions `dFdx` and `dFdy` functions that are used to compute the normals in the fragment shader.

I have create a new test case based on `webgl_postprocessing` that demonstrates the issue but without the post processing related code. Just some meshes with a flat shaded material (renderer created with `mediump` parameter): https://jsfiddle.net/xuztjcdv/2/show

I wonder if we should create a new issue. Something like: `flatShading` does not work with `mediump`.

**Comment by Mugen87** [comment]
BTW: The test case looks like this on my Pixel:

![image](https://user-images.githubusercontent.com/12612165/51976553-3b8f2d00-2485-11e9-8ea2-48d5042b0339.png)

**Comment by jagracar** [comment]
https://www.enkisoftware.com/devlogpost-20150131-1-Normal-generation-in-the-pixel-shader

**Comment by Mugen87** [comment]
`three.js` already uses a value in view space for normal derivation:

https://github.com/mrdoob/three.js/blob/18e4439b555a7e175f44b9051c1755b7d90448f9/src/renderers/shaders/ShaderLib/meshphong_vert.glsl.js#L51
https://github.com/mrdoob/three.js/blob/18e4439b555a7e175f44b9051c1755b7d90448f9/src/renderers/shaders/ShaderChunk/normal_fragment_begin.glsl.js#L6-L8

So it seems the article does not help in context of `mediump` precision issues. As far as I can see, it only discusses precision issues related to 32 bit floating points (`highp`).

**Comment by Mugen87** [comment]
Um, I've research this afternoon for a solution. Unfortunately, I found only these two approaches that would work for mobile devices:

- Generate flat normals in a DCC tool or in JavaScript
- Generate flat normals with a geometry shader (does not work with WebGL)

I found no resource that demonstrates how to use `dFdx`/`dFdy` in order to safely compute flat normals in context of `mediump`.
