### ISSUE TITLE
THREE.PointerLockControls rotating bug

### ISSUE THREAD

**Issue by ABTOMAT** [mrdoob/three.js#15639]
##### Description of the problem

While testing official example of THREE.PointerLockControls I have experienced the bug.
When you're moving mosue around at some point the camera "teleports" to another rotation.
This bug is persistent.
I was only one person among my friends that encounters this bug, everyone else has it OK.

https://threejs.org/examples/misc_controls_pointerlock.html

* [youtube](https://www.youtube.com/watch?v=3dJk9ap0YT8) (Youtube video that shows the bug)

##### Three.js version

Latest, used in official examples.

##### Browser

- [x] Chrome
- [ ] Firefox
- [x] Yandex Browser
- [x] Opera

##### OS

- [x] Microsoft Windows [Version 10.0.17763.253]

**Comment by ABTOMAT** [comment]
I've tried this in Firefox and there's no bug.
But this bug also appears on Opera (just tried) and YandexBrowser (yet another blink-based browser) and Microsoft Edge.

So FF is currently the only browser that does not produce this bug.

**Comment by Mugen87** [comment]
I'm sorry, but I don't think there is something we can do here. `PointerLockControls` uses the API in the intended way. I recommend you report the issue to one of the browser vendors instead.

https://bugs.chromium.org/p/chromium/issues/list

**Comment by ABTOMAT** [comment]
Thank you for your answer!
Maybe this is because mouse coordinates "jumps" because of browser bug.
BUT I have implemented mouselook in my game in another way and it works for me while this sample still produces bug.
I think the problem is that you use Three.js euler angles in calculations that are not stored directly in engine, but calculated from matrices, which is not safe.
Will return to this question later, let's see if someone else gets this bug.

**Comment by mrdoob** [comment]
> I think the problem is that you use Three.js euler angles in calculations that are not stored directly in engine, but calculated from matrices, which is not safe.

Do you mind console-logging the mouse values and the euler values in your environment to check if that's the case?

**Comment by ABTOMAT** [comment]
Yes, I think it'd be a good idea.
I hope I will find some time to download the example and test it on my server to be able console.logging it.
This would determine what causes the bug: mouse values OR eulers?

**Comment by WestLangley** [comment]
The first thing I would suggest is to borrow your friend's mouse and see if the problem goes away.

**Comment by Mugen87** [comment]
Let's reopen if the OP can demonstrate that it's actually a `three.js` issue. I rather think it's a device/browser issue.

**Comment by WestLangley** [comment]
>Let's reopen if the OP can demonstrate that it's actually a three.js bug.

Good idea.

If the issue occurs on multiple browsers, it is likely not a browser issue. If it occurs only on the OP's hardware, and it can't be replicated by others with the same device, it is likely not a device issue.

**Comment by Mugen87** [comment]
Fair enough^^

**Comment by franverona** [comment]
You can reproduce the teleport bug [with the demo](https://threejs.org/examples/?q=pointer#misc_controls_pointerlock) by doing this:

1. Click the instructions to lock.
2. Automatically try to move.

If you do it quickly enough, you will be teleported outside the boxes area.
