### ISSUE TITLE
Editor User problem

### ISSUE THREAD

**Issue by city8208** [mrdoob/three.js#15630]
Hi,I use three.js editor on my site.
But I have some problem need to solve.

1.At Sidebar.Object 129.I got the model scale,How do I get the real size(like box3)
2.If import model is hanging,how do I set auto set bottom.
3.I change the chassis size and its success ,then How do I set default camera zoom. 

Looking forward to your favorable reply.

**Comment by Mugen87** [comment]
Sry, but please use the [forum](https://discourse.threejs.org/) or stackoverflow for such help requests. Also try to ask only a single question per thread/topic.
