### ISSUE TITLE
How can i add 3dxml file to scene?

### ISSUE THREAD

**Issue by bahadir1981** [mrdoob/three.js#15637]

**Comment by Mugen87** [comment]
So you are looking for a loader for the [3DXML](https://en.wikipedia.org/wiki/3DXML) 3d format?

AFAIK there is no possibility so far to load such files into a `three.js` app. You might want to convert the format to something else if possible. May I ask what's your use case for working with `3DXML`?

**Comment by mrdoob** [comment]
I would consider this a help request.

**Comment by mrdoob** [comment]
Please, use the [forum](https://discourse.threejs.org/) instead.
