### ISSUE TITLE
Example on Half-Edge data structure in THREE?

### ISSUE THREAD

**Issue by leemun1** [mrdoob/three.js#15643]
#### Feature request
I would like an example of the HalfEdge data structure in THREE. I noticed that an implementation of it is already included and documented at https://threejs.org/docs/#examples/quickhull/HalfEdge, but I could not find an example usage of it. 

Would it be possible to add an example of using HalfEdge?

**Comment by WestLangley** [comment]
`QuickHull.js` itself uses that data structure. It is also used by `ConvexGeometry.js`.

If you need help, then you can file a post on the three.js forum.

**Comment by leemun1** [comment]
@WestLangley Ok. Thank you! I will poke around in the forum for sure!
