### ISSUE TITLE
BufferAttribute's updateRange should be reset in a single manner

### ISSUE THREAD

**Issue by tonso** [mrdoob/three.js#15652]
##### Description of the problem

The problem is that the updateRange isn't reset properly (updateRange.offset = 0, updateRange.count = -1) in all cases, particularly:
1) Immediately after the buffer is created
2) After the buffer is partially updated

Something like this:
```
	function WebGLAttributes( gl ) {
		...
		function updateBuffer( buffer, attribute, bufferType ) {
			...
			} else {

				gl.bufferSubData( bufferType, updateRange.offset * array.BYTES_PER_ELEMENT,
					array.subarray( updateRange.offset, updateRange.offset + updateRange.count ) );

+				updateRange.offset = 0;
				updateRange.count = - 1; // reset range

			}

		}
		...
		function update( attribute, bufferType ) {

			if ( attribute.isInterleavedBufferAttribute ) attribute = attribute.data;

			var data = buffers.get( attribute );

			if ( data === undefined ) {

				buffers.set( attribute, createBuffer( attribute, bufferType ) );
																
+				if ( attribute.dynamic ) {
+
+					attribute.updateRange.offset = 0;
+					attribute.updateRange.count = -1;
+
+				}
			...

		}
```
##### Three.js version

- [ ] Dev
- [x] r100
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I think it makes sense to set the `offset` value to zero in `updateBuffer()`. But the change in `update()` seems unnecessary to me. `createBuffer()` does not use `updateRange` range at all so why resetting it then?

**Comment by tonsomar** [comment]
@Mugen87 So that the following invariant was always true: "After some changes were committed to the buffer, the updateRange gets reset". Buffer creation doesn't use updateRange, but still changes the buffer. If the buffer isn't updated later, the updateRange will keep whatever value there was before the buffer creation, and that may get misleading later.

**Comment by Mugen87** [comment]
Um, I still think it makes no sense since buffer creation is something different than a (partial) update. When defining the buffer `updateRange` is irrelevant. I think it would be confusing if `updateRange` range changes in this situation.

**Comment by tonsomar** [comment]
@Mugen87 So you think, that leaving irrelevant values within `updateRange` after buffer creation and initial update with the very same `glBufferData` isn't confusing?

**Comment by Mugen87** [comment]
> that leaving irrelevant values

It would be the user who sets these values in the first place, right? Doing this has obviously no effect.

**Comment by tonsomar** [comment]
> Doing this has obviously no effect.

I'm not sure if that's the right way, I'd probably call `updateBuffer` from `createBuffer` instead of directly calling `glBufferData`. The user doesn't care when exactly the buffer is created, and can modify updateRange whenever he wants, even beforehand.

**Comment by tonsomar** [comment]
So you think the user should care when exactly the buffer is created and decide if he modifies `updateRange` or not based on that?

**Comment by Mugen87** [comment]
The idea is simple: Just resetting the values if they are actually used.

**Comment by tonso** [comment]
Ok, then why the `updateRange` is not used during the buffer creation?

**Comment by Mugen87** [comment]
Because the entire buffer should be allocated not only a part of it.

**Comment by tonso** [comment]
Ok, obviously. But my point is still there: the user can modify JS buffer contents and `updateRange` before or after the actual GL buffer creation, and count on the invariant that `updateRange` will be reset when the changes are committed next time (with `glBuffer(Sub)Data`, no matter if it's called from `updateBuffer` or `createBuffer`, which btw are both called from `update`). I guess you'll stick to your point anyway, so I'm done with arguing.

**Comment by Mugen87** [comment]
Let's see how the owner devs evaluate your this 😉
