### ISSUE TITLE
Poor memory performance in Safari

### ISSUE THREAD

**Issue by Avocher** [mrdoob/three.js#15653]
##### Description of the problem

We are experiencing memory issues in our three.js app at a much higher rate in Safari compared to other browsers. The following memory test: https://threejs.org/examples/webgl_test_memory.html shows what we are experiencing. For me the test stabilises at around 2GB memory usage in Safari 12.0.1 on my MacBook. Safari will also show the following message: "This webpage is using significant memory closing it may improve responsiveness of your mac". 

##### Three.js version

- [ ] Dev
- [x] r100
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

**Comment by Mugen87** [comment]
Have you considered to report this issue at the browser vendor's bug tracker? For example:

https://bugs.webkit.org/
