### ISSUE TITLE
throughthedark link on homepage redirecting

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#15677]
Link to https://throughthedark.withgoogle.com/ on the threejs homepage is now redirecting to https://play.google.com/. 😕

![screen shot 2019-01-30 at 7 27 40 pm](https://user-images.githubusercontent.com/1848368/52028783-2f2ac480-24c5-11e9-84da-bfce1e0737ed.png)

**Comment by mrdoob** [comment]
Oh noes...

**Comment by mrdoob** [comment]
Commented out. Thanks!
