### ISSUE TITLE
Feature Request: LensFlareElement as core export

### ISSUE THREAD

**Issue by CreativeHouseDotOrg** [mrdoob/three.js#15679]
Hi

I didn't see this explicit I will have to ask for a LensFlare Feature Request. Would it be possible to get The LensFlare Parts from the examples as a part of the core to the next R101? As it's really important I need to get it up asap. Any chance to have it done in a fair amount of time?

Kind Regards

/cc

[https://github.com/mrdoob/three.js/issues/15648](https://github.com/mrdoob/three.js/issues/15648)

[https://github.com/mrdoob/three.js/commit/eebed390cb5f30bdbc0fe71a55a9770b888995cd#commitcomment-32130305](https://github.com/mrdoob/three.js/commit/eebed390cb5f30bdbc0fe71a55a9770b888995cd#commitcomment-32130305)

[https://discourse.threejs.org/t/how-do-i-include-three-lensflareelement-in-angular-project/5885/11](https://discourse.threejs.org/t/how-do-i-include-three-lensflareelement-in-angular-project/5885/11)

[https://stackoverflow.com/questions/54385521/how-do-i-include-three-lensflareelement-in-angular-project](https://stackoverflow.com/questions/54385521/how-do-i-include-three-lensflareelement-in-angular-project)

**Comment by Mugen87** [comment]
> Would it be possible to get The LensFlare Parts from the examples as a part of the core to the next R101?

No, since we invested quite a lot of effort to move the lensflare plugin out of the core.

I think you have placed your help request at enough places. It's not necessary to open new issues.

**Comment by RemusMar** [comment]
> Would it be possible to get The LensFlare Parts from the examples as a part of the core to the next R101? 

LensFlare was part of the core until r90.
You won't see it back starting with r101.
