### ISSUE TITLE
TRHEE.ShaderMaterial attribute

### ISSUE THREAD

**Issue by vkuchinov** [mrdoob/three.js#15689]
I need to update shader attribute immediately in the mouseover event. For example:

```
function onMouseMove(event) {
...
if(id < N){

                highlight[id] = 1.0;
                points.geometry.attributes.highlight.needsUpdate = true;
           
            }
...

)};
```
And in a vertex shader, I have a conditional:

`if(highlight > .5){ vColor = vec3(1., 0., 1.); }`

where the highlight is an attribute float. It passes vColor to fragment, to gl_FragColor.

But, I am almost 99% sure that points.geometry.attributes.highlight.needsUpdate = true; doesn't update attribute, or at least, not immediately in the mouseover event cycle.

Setting needsUpdate is an immediate method?

I could provide the full code upon request.

##### Three.js version
- [x] r98

##### Browser
- [x] Chrome

##### OS
- [x] macOS

**Comment by vkuchinov** [comment]
And hard-reset works well.

`points.geometry.addAttribute("highlight", new THREE.BufferAttribute(new Float32Array(highlight), 1));`

instead of

`points.geometry.attributes.highlight.needsUpdate = true;`

**Comment by Mugen87** [comment]
Have you tried my suggestion mentioned at the forum?

https://discourse.threejs.org/t/glsl-immediate-attribute-update/5964/2?u=mugen87

**Comment by WestLangley** [comment]
Please handle this on the forum. You can reopen this if you can demonstrate a three.js bug.

**Comment by vkuchinov** [comment]
> Have you tried my suggestion mentioned at the forum?
> 
> https://discourse.threejs.org/t/glsl-immediate-attribute-update/5964/2?u=mugen87
> 
> Besides, have you realized that your [demo](http://vkuchinov.github.io/highlightShader/) does not work correctly when the window is resized (for example when you open the dev tools)? It's not possible in this case to select a particular shape anymore.
> 
> Before you post a bug report at GitHub, you should ensure that your app-level code is free of bugs.

A bug is when you did something wrong. When you didn't do resize function, because it's not the part of the problem, it's not a bug.

**Comment by vkuchinov** [comment]
Wanted proofs?

This is a working example with addAttribute
http://vkuchinov.github.io/dualShadersAdd/
the other is based on needsUpdate
http://vkuchinov.github.io/dualShadersUpdate/ and it's not working

Both codes are equals except these lines:
points.geometry.addAttribute("highlight", new THREE.BufferAttribute(new Float32Array(highlight), 1)); 
vs.
points.geometry.attributes.highlight.needsUpdate = true;

**Comment by WestLangley** [comment]
```javascript
geometry.addAttribute("highlight", new THREE.BufferAttribute(new Float32Array(highlight), 1));

...

highlight[current_id] = 1.0;
```

You are updating a JavaScript array, not the attribute array.

**Comment by Mugen87** [comment]
Oh man, I've totally overlooked this...

**Comment by WestLangley** [comment]
@Mugen87 That's OK! :-)
