### ISSUE TITLE
Error on load FBX From Mixamo

### ISSUE THREAD

**Issue by ran-j** [mrdoob/three.js#15680]
##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox

##### OS

- [] All of them
- [X ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
I5 : 4460
GTX 1060
20 GB RAM

#######
Whem the FBX loads the maps files he load with a desktop path:

 "http://localhost:3000/model/C:/Users/Ran-pc/Documents/SPn/Test/v2/gina.images/ozi_classiquedress_dress01.jpg"

and my model are not displaying.
On mixamo my model load normaly.

I took the code from here https://threejs.org/examples/webgl_loader_fbx.html

Model: https://drive.google.com/open?id=1-NCVQsiUG4hRNjJrqunX1d1lXL7DFwpH

![screen shot 01-31-19 at 07 20 pm 001](https://user-images.githubusercontent.com/17410205/52086224-7d0aff80-258d-11e9-8546-87599920d154.PNG)
![screen shot 01-31-19 at 07 20 pm](https://user-images.githubusercontent.com/17410205/52086225-7d0aff80-258d-11e9-83dd-0531a614f2b1.PNG)
![screen shot 01-31-19 at 07 22 pm](https://user-images.githubusercontent.com/17410205/52086238-885e2b00-258d-11e9-8b24-a09fd18df87e.PNG)

**Comment by looeee** [comment]
Does the model load OK in other apps? 

Mixamo tends to leave the original model mainly unchanged so this is probably an issue coming from the app is was made in. If it was 3D studio max, open up the asset explorer and strip paths from all the assets then load them from the same folder as the file. 

As an aside, this model with textures is over 230mb. You'll need to reduce that a lot for it to be workable on the web.

**Comment by ran-j** [comment]
FBX Review open normaly.

This model was made in Daz Studio.

![image](https://user-images.githubusercontent.com/17410205/52133075-c90a8280-2627-11e9-9787-d9e464f6a83f.png)

**Comment by ran-j** [comment]
I fix the model and reduce https://drive.google.com/open?id=1-cpSbjpuJh-N9QpcR-4eZeXlGrPHEYpI

But still not loading.

**Comment by ran-j** [comment]
Wem I tried to load on https://threejs.org/editor/

![image](https://user-images.githubusercontent.com/17410205/52138375-23a9db80-2634-11e9-8451-4fa667428f02.png)

**Comment by looeee** [comment]
Actually the textures from original model don't load in FBX review unless I move the `gina.images` directory into the same directory as the FBX model:

![gina](https://user-images.githubusercontent.com/5307958/52154322-509fd200-26b8-11e9-989c-5c00d7e0b919.jpg)

**Comment by looeee** [comment]
Your new one has some other errors, I think perhaps related to some of the textures being .tif
Can you try converting them to JPG or PNG and see if it works then?

**Comment by ran-j** [comment]
It's default from Daz I guess but if the texture is with error the model should load but without texture right?

**Comment by looeee** [comment]
>if the texture is with error the model should load but without texture right?

Yes, this may be a bug in the loader. 

But you will need to convert textures from TIF anyway since browsers can't load TIF - always use JPG or PNG for best results.

**Comment by ran-j** [comment]
Ok, can you help load the model after I will try to convert the TIF

**Comment by looeee** [comment]
Let's see if it works after you've converted the textures. 

If not you can try using [FBX2glTF](https://github.com/facebookincubator/FBX2glTF) to convert to a glTF binary (.glb) file and see if that works.

**Comment by ran-j** [comment]
Ok I will try this tomo

**Comment by ran-j** [comment]
Works in a very strange way

![image](https://user-images.githubusercontent.com/17410205/52169885-824f8200-2726-11e9-8851-ca2c08b5436f.png)

**Comment by looeee** [comment]
> Works in a very strange way

What did you do to make this happen? Can you share that model?

**Comment by ran-j** [comment]
FBX : https://drive.google.com/open?id=1-cpSbjpuJh-N9QpcR-4eZeXlGrPHEYpI

GLB: https://drive.google.com/open?id=1LAXtDpNGxrf3iTckfc5p_64LMU8_06Ty

To create the glb :
![image](https://user-images.githubusercontent.com/17410205/52489001-501ba580-2ba8-11e9-92ba-4314bc81a7c4.png)

**Comment by mrdoob** [comment]
The issue here seems like it's related to the animation parsing code.

The current code crashes and it abort the loading.

<img width="799" alt="screen shot 2019-02-19 at 7 17 01 pm" src="https://user-images.githubusercontent.com/97088/53064001-0c178300-347b-11e9-9788-981e2945b5f1.png">

**Comment by ran-j** [comment]
I took this animation on mixamo

**Comment by yazancash** [comment]
can we get Mixamo FBX animations to work without using GLB convertor ?

**Comment by ran-j** [comment]
I figured it out the error, Daz Studio 3d models come with a lot of bones and thats bug threejs and babylon JS.

I imported the model on blender and remove their bones and add mixamo bones and add mixamo animation, works perfectly

If you whant to debug why Daz models do not work jus create a simple "Genesis 8" and export a fbx and convert to glb or something

**Comment by ran-j** [comment]
> Works in a very strange way
> 
> ![image](https://user-images.githubusercontent.com/17410205/52169885-824f8200-2726-11e9-8851-ca2c08b5436f.png)

I figure out that this skin is a bug from FBXtoGTLF converter and I think they alread fix that

**Comment by looeee** [comment]
Unfortunately, the files are no longer available so I can't test to see if this model is fixed or not.

**Comment by mrdoob** [comment]
Closing then.
