### ISSUE TITLE
Zero-length bezier curves not strictly handled (getLength(), getSpacedPoints(), etc)

### ISSUE THREAD

**Issue by BenTalagan** [mrdoob/three.js#15691]
##### Description of the problem

It seems that the corner case of a zero-length BezierCurve is not strictly well handled by THREE (maybe other types of curves are affected too). It could be nice to have a clean behavior. For example (tested under chrome, firefox and node but it probably happens everywhere by design) : 

```javascript
var v = new THREE.Vector2(0.1,0.1);
var curve = new THREE.CubicBezierCurve(v,v,v,v);
curve.getLength();
> 2.943923360032081e-15
```
It seems that Three tries to perform calculations just like it would do for other curves and accumulates float imprecision. One way to achieve a clean result would be to simply test if all four points are equal. It seems to me that it's the only case where float imprecision can be annoying (because we expect a pure zero length). Some other functions are also affected (getSpacedPoints(), etc).

##### Three.js version
- [x] r101

##### Browser
- [x] All of them

##### OS
- [x] All of them

**Comment by Mugen87** [comment]
`three.js` tends to not check such edge cases for performance reasons. I can't think of a reason where the mentioned floating point precision issue should cause problems in context of path and shape generation. Since curves are normally used in order to generate a visual result (like a shape geometry), minor deviations in the decimal area are not visible for the user.

**Comment by BenTalagan** [comment]
Thanks for your answer!

Ok, this is my use case :-) I'm currently using three.js to build a framework for doing procedural calligraphy. I use Three for both calculation and visualization. In this scope, a "user" is in fact a developer coding strokes as as serie of bezier curves, just like a digital artist would do with his/her mouse in a digitial painting software. Since it this coding be dependent of dynamic parameters, one cannot avoid cases were a parameter will affect the stroke in such a way that, in an extreme case, one of the bezier segment of the stroke would be reduced to a zero-length curve. The curve is reduced to a point and this may trigger side effects ; in my case this was about tangents, because I needed to travel across the stroke to accumulate a serie of rotation values during the travel (imagine that the stroke performs multiple loops, you want to know at which angle you started, and at which angle you ended, this difference may be far more superior than 2.PI if you encountered multiple loops). A zero-length curve has no tangents (it's a point). I was aware of this and was testing the length of the curve to treat this special case. But since the result of getLength was not zero, it would fall in the normal case loop and random tangents and rotation angles would be generated, and broke the algorithm. That's for the whole story :-)

It's not a big deal since I'm doing the test by myself at higher level to avoid this behavior now, instead of calling getLength. Also I understand perfectly the performance argument. I guess the choice is dependent to three's design philosophy. Not a big deal, but maybe good to notice, at least (imho).

**Comment by Mugen87** [comment]
Many thanks for your detailed explanation! It's good to hear that it's manageable to handle this issue on app-level. For now, I personally would leave the implementation as it is in order to avoid overhead that is not necessary in most cases. Let's see how the other devs think about this.

**Comment by WestLangley** [comment]
I agree with @Mugen87. Your issue is best handled at the application layer.

**Comment by BenTalagan** [comment]
Ok! No problem and perfectly understandable. For anyone stumbling on this thread with similar issues, this is my solution, I use a simple wrapper around the curve implementation.

```javascript
THREE.PatchedBezierCurve = class extends THREE.CubicBezierCurve {
  
  constructor(v1,v2,v3,v4) {
    super(v1,v2,v3,v4);
    this._zeroLength = (v1.equals(v2) && v2.equals(v3) && v3.equals(v4));
  }

  isZeroLength() {
    return this._zeroLength;
  }

  getLength() {
    return (this._zeroLength)?(0):(super.getLength());
  }
  
  getPoint(t) {
    return (this._zeroLength)?(this.v1.clone()):(super.getPoint(t));    
  }
  
  getPointAt(u) {
    return (this._zeroLength)?(this.v1.clone()):(super.getPointAt(u));    
  }
  
  getPoints(divisions) {
    if(!this._zeroLength)
      return super.getPoints(divisions);
    
    var ret = new Array(divisions+1);
    for(var i=0;i<ret.length;i++)
      ret[i] = this.v1.clone();
    
    return ret;
  } 
  
  getSpacedPoints(divisions) {
    if(!this._zeroLength)
      return super.getSpacedPoints(divisions);
    
    var ret = new Array(divisions+1);
    for(var i=0;i<ret.length;i++)
      ret[i] = this.v1.clone();
    
    return ret;
  }
  
  getTangent(t) {
    return (this._zeroLength)?(new THREE.Vector2(0,0)):(super.getTangent(t));      
  }
  
  getTangentAt(u) {
    return (this._zeroLength)?(new THREE.Vector2(0,0)):(super.getTangentAt(u));      
  }
  
}
```
