### ISSUE TITLE
Parallax-Corrected CubeMap

### ISSUE THREAD

**Issue by sneha-belkhale** [mrdoob/three.js#15704]
So I was creating a room scene and wanted to attach a cube texture environment map to the ground ( taken with the three.js CubeCamera ). The environment map showed up but since environment maps are used under the assumption that all objects are at an infinite distance, there was a major parallax issue that made the env map unusable for my scene.

This article covers the topic pretty clearly: 
https://www.clicktorelease.com/blog/making-of-cruciform/

I think it would be nice to include this little patch for those who desire it. I've already wrote a patch for the current physical shader, which simply applies the correction if the #define PARALLAX_CORRECT exists. The user would have to specify two uniforms, maybe like so : 

```
var parallaxCorrectMat = new THREE.MeshPhysicalMaterial({
envMap: someEnvMap,
cubeMapSize: new Vector3(100,200,100),
cubeMapPos: new Vector3(0,0,0)
})
```

Let me know your thoughts ---

Sneha

**Comment by sneha-belkhale** [comment]
for clarity - I made a demo where you can see the difference between the parallax corrected / default cube maps. 

https://codercat.tk/tmp/parallaxCubeMap/

**Comment by Kif11** [comment]
I would like to have similar functionality for creating realistic ground reflections.

**Comment by sneha-belkhale** [comment]
cool, can one of the threejs guys let me know if this sounds good to add? I already have the basic code ready for a PR.

**Comment by Mugen87** [comment]
I've a question about the article. It says:

> We want to correct the normal that we use to lookup the cubemap. A cubemap assumes that the images rendered in the different faces are far far away. What we do with the parallaxCorectNormal function is take that vector, and look where it intersects a volume that defines the scene. **I'm using a cuboid because it accurately models the hall model.**

What if a cuboid is not suitable for other scenarios?

**Comment by sneha-belkhale** [comment]
@Mugen87 - 

Yeah so this specific implementation only works for cuboids. 

It's not optimal but with cuboids alone you could cover a range of scenarios by segmenting your envmap into a set of cuboids.

**Comment by looeee** [comment]
> What if a cuboid is not suitable for other scenarios?

Cuboids would work for the majority of indoor scenes, since most rooms are cuboids or combinations of cuboids (e.g. hallways with a 90 degree bend).

**Comment by Mugen87** [comment]
@looeee Yeah, that's true.

@sneha-belkhale Your approach is also know as _Box Projected Cubemap Environment Mapping (BPCEM)_ or _Box Projected Cubemaps_, right? If it's similar to what [Unity](https://docs.unity3d.com/Manual/AdvancedRefProbe.html) offers, I think it's beneficial to have this as an option in the library. I vote for a PR 😊

**Comment by Mugen87** [comment]
Instead of using `PARALLAX_CORRECT`, I think I would refer to the term `BOX_PROJECTION`.

**Comment by WestLangley** [comment]
It appears this technique generates incorrect specular reflections...

![prallax-corrected screen shot](https://user-images.githubusercontent.com/1000017/52649277-08519280-2eb6-11e9-8b53-64f5a0452739.png)

**Comment by sneha-belkhale** [comment]
@Mugen87 ahh yeah it's the same as Box Projection Mapping -- and yeah we should use this term instead of parallax correction.

@WestLangley hmm so I think the issue you pointed out has to do with the fact that i'm using a `THREE.CubeCamera` to generate the environment map. Since the CubeCamera is static, the specular that's visible in the env map is also static. Generally env maps are static images, so I guess this is a problem with every env map?

**Comment by WestLangley** [comment]
>I think the issue you pointed out has to do with the fact that i'm using a `THREE.CubeCamera` to generate the environment map

Yes.

Could not your case could be implemented via `THREE.Reflector`, in which case I assume these artifacts would go away?

**Comment by sneha-belkhale** [comment]
@WestLangley It could for this specific demo, but for other use cases the `THREE.Reflector` is limiting. I would like to use the `MeshPhysicalMaterial` so I can manipulate other material properties besides the env map. Also the user might want to have a static texture as the env map ( instead of generating 1 to 1 from the scene )

**Comment by Mugen87** [comment]
There are some interesting [comparisons](https://www.gamedev.net/forums/topic/568829-box-projected-cubemap-environment-mapping/) between these different approaches like:

![image](https://user-images.githubusercontent.com/12612165/52782850-55696c00-3050-11e9-9577-fe21ee5e0ad3.png)

Using a mirror is more expensive than using just a static environment map. So depending on the use case, Box Projected Cubemaps seem to provide a good visual approximation with better performance.

**Comment by Mugen87** [comment]
As long as we document the restrictions of this approach, I think it's good to add BPCEM to the material system. The changes should be manageable and you can nicely demonstrate the feature with an example.

**Comment by WestLangley** [comment]
I think the proper way to implement this is via a `LightProbe` class. It has been discussed in #6251. Such a class can model position-based ambient diffuse, or position-based specular reflections.

**Comment by Mugen87** [comment]
Um, I'm not sure it's valid to compare BPCEM with light probes. Unity offers both. They would not do this if there would be no use cases for BPCEM.

**Comment by WestLangley** [comment]
See https://docs.unity3d.com/Manual/UsingReflectionProbes.html and https://docs.unity3d.com/Manual/AdvancedRefProbe.html.

**Comment by Mugen87** [comment]
Yes, but Unity distsinc between `ReflectionProbes` and `LightProbes`, see

https://docs.unity3d.com/Manual/LightProbes.html
https://docs.unity3d.com/Manual/ReflectionProbes.html

TBH, I never used light probes in Unity but I would say a `ReflectionProbe` is nothing else than a wrapper around a dynamic cube map. As stated in the docs `BPCEM` is an improvement of this approach.

**Comment by WestLangley** [comment]
Regardless of the nomenclature, my point is it is implemented like a light source -- it is added to the scene, rather than as a property of a material.

**Comment by Mugen87** [comment]
Oh, now I see what you mean. That's indeed different and without new classes it's not possible to implement it in that way.

My point is...the effort to implement `BPCEM` seems to be manageable and who nows when a probe implementation hits the core. `BPCEM` is something we can offer now without affecting existing code (in context of backwards compatibility). If probes are introduced at a later point, the library can deprecate the material properties and refer to the new classes.

**Comment by WestLangley** [comment]
My preference is to implement it as a probe.

If you are insistent, rather than modifying the built-in materials, you can create a live example using shader code injection. I would avoid using a `CubeCamera` in the example; that will have specular artifacts. Just use a static cube map.

**Comment by Mugen87** [comment]
@mrdoob How do you feel about that?

**Comment by sneha-belkhale** [comment]
Hey - thanks for the feedback @Mugen87  and @WestLangley . Yeah so the scene light probe approach is probably the more correct way, but I do think there are immediate use cases for BPCEM and would be good to have in the mean while.

Personally I think having it as part of the material would be simple to implement, better documented, and more user-friendly than searching for shader code injection in an example -- but I guess @mrdoob can decide:)

**Comment by sneha-belkhale** [comment]
heya, any updates on this? @Mugen87 @WestLangley @mrdoob

**Comment by mrdoob** [comment]
We should definitely implement light probes eventually.

In the meantime, we can add an example of `BPCE` in the `examples` folder (just like `THREE.Reflector` and `THREE.Refractor`). I would not modify the current built-in materials just for this.

**Comment by sneha-belkhale** [comment]
alright, I'll fix the example I have to use shader injection instead, adjust the scene a bit, and make a PR in the next few days.
