### ISSUE TITLE
Feature Request: Editor frameless in electron

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#15708]
I try to use  `new BrowserWindow( { frame: false } )`  for `Editor`, how do you feel.

Screenshot:
![image](https://user-images.githubusercontent.com/23699926/52224278-904a0200-28e2-11e9-9a55-56f07c0a1e4d.png)

**Comment by Mugen87** [comment]
Doing this on macOS means you have no close, minimize and maximize buttons anymore. These buttons are usually on the top-left corner of an app. TBH, it's a bit confusing when they are missing...

**Comment by linbingquan** [comment]
@Mugen87  I saw `VS Code` and `GitHub Desktop` are frameless in win10, I don't know how to do it between different OS(operating system).

![image](https://user-images.githubusercontent.com/23699926/52480752-92b0a280-2be7-11e9-9890-b12a7256cc80.png)

![image](https://user-images.githubusercontent.com/23699926/52485575-238d7b00-2bf4-11e9-9a0c-f5375c592e11.png)

**Comment by linbingquan** [comment]
Editor uses PWA, in https://github.com/mrdoob/three.js/commit/a5bf724f2041983e85e1207c6a050ba0ccc5e1d4 and https://github.com/mrdoob/three.js/commit/66863f3262a1b51141727358f8776b7226f8c071
