### ISSUE TITLE
Inconsistent errors on GLTF export from Blender after modifying action

### ISSUE THREAD

**Issue by aoedipus** [mrdoob/three.js#15701]
I have a model with 7 animations that exports ok, with or without actions being pushed down into NLA tracks, or saved as data blocks. I introduce a new animation following a workflow identical to the other seven (all from Mixamo, imported as FBX). The exporter then craps out, using settings that have not changed. A voodoo process ensues, trying things like purging data, removing then relinking actions, appending from a .blend file instead of importing the FBX directly, reinstalling the exporter, clearing keyframes, quitting and restarting, saving as a new file name, etc. 

Sometimes one of these things works - or something else happens that makes it appear as though one of these things works. There's no rhyme or reason that I can discern. Establishing a reliable workflow for modifying an animation or introducing a new action has become fraught with fear.

Likely related to [36](https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/39) and [166](https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/166), but so far nothing is working for me in a predictable way.

Occasionally bones with a -1 orientation on a given quaternion rotation get messed up on an fbx import, which I'll correct in Blender. Again, there's not a pattern for why this happens that I can figure out. Unsure if it's somehow related.

The steps that seem to semi-reliably get things exporting properly again include: purging data > clearing all animation data in the scene view, relinking actions by running through each of them in the action editor, saving as a new .blend file, quitting blender, reopening the file, and exporting. When that fails, as a last resort I will clear keyframes, but this often requires a fair amount of cleanup. Even this last step only works sporadically.

If I had hair left to pull out I would.

Any feedback much appreciated, and thanks for all the hard/great work. Sorry if this is an inappropriate post for this forum due to it being a gltf/blender issue more than a three.js one.

[This file is an example](http://nideffer.net/book/media/mod/game/pnpc/alvin/Alvin.blend) of one that was broken a bit ago, but started working again after the clearing keyframes step.

Will follow up post to the Khronos group.

I'm currently using the most recent build of the [gltf 2.0 Import-Export package](https://github.com/KhronosGroup/glTF-Blender-IO) from Julien Duroure, Norbert Nopper (et al.). 

##### Three.js version

- [ ] Dev
- [ ] r101
- [r98] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
If you can reproduce the issue with a couple glTF viewers (https://gltf-viewer.donmccurdy.com/, https://sandbox.babylonjs.com/), this sounds likely to be a problem with the Blender exporter rather than three.js. You may want to file an issue on https://github.com/KhronosGroup/glTF-Blender-IO instead.
