### ISSUE TITLE
FBX loader .setPath() is having no effect

### ISSUE THREAD

**Issue by Chaky74** [mrdoob/three.js#15717]
As title says, FBX loader is not using path defined with .setPath function. Instead it looks for resources in root folder.
IMO, the loader is missing line

`loader.setPath( self.path );`

as line 48, which fixes the issue.

##### Three.js version

- [ ] Dev
- [x] r101
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
> As title says, FBX loader is not using path defined with .setPath function. Instead it looks for resources in root folder.

`.setPath()` affects the initial `.fbx` file. To change the directory for resources, use `.setResourcePath()`.

**Comment by donmccurdy** [comment]
See https://github.com/mrdoob/three.js/pull/14955 – we're working to make this consistent across loaders.

**Comment by Chaky74** [comment]
I'm bit talking about .setResourcePath. That part Works fine. Once the model is loaded, textures load without a problem (which are not on the same folder as the model, nor in any subfolder, but on in different folder alltogether). Path to the model, on the other hand, is the issue described above.

**Comment by donmccurdy** [comment]
Hm I see, thanks. @looeee it looks like `setPath` is just used as a fallback to `setResourcePath` right now, and doesn't affect the initial `.fbx` request.
