### ISSUE TITLE
TransformControls prevent mouse's "back" button browser navigation

### ISSUE THREAD

**Issue by wyckster** [mrdoob/three.js#15713]
##### Description of the problem

@mrdoob , @arodic 

#14170 added an event handler at the document level that calls `preventDefault` for the `mouseup` event.  This killed back-button mouse (button == 3) and forward-button (button == 4) functionality that is used for browser navigation.

If you have such a mouse, and you go to https://threejs.org/editor/ you'll see that you can't use the back-button on your mouse to return back to this page.  (...provided that your mouse pointer is currently in the body of the page.  If your button is in the chrome / header-bar of the browser, then it *will* work.)  

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows 10
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

I tested with Microsoft IntelliMouse Optical USB and PS/2 Compatible (IntelliPoint)

- Driver Provider: Microsoft
- Driver Date: 2011-05-18
- Driver Version 8.20.409.0

I have tested a dozen or so different PC's and there are some PC's that do not exhibit this behaviour - I'm not sure what the difference is.   It may be (and this is purely speculation) that a fancier mouse driver intercepts the back button and performs navigation a different way other than relying on the document to receive a back button (button==3) event.

**Comment by arodic** [comment]
Bug confirmed with Wacom stylus. Will look into it!
