### ISSUE TITLE
failed to load embed TGA in FBX

### ISSUE THREAD

**Issue by hifar** [mrdoob/three.js#15718]
##### Description of the problem
Failed to load embed TGA in FBX, reason is set the path in TGA loader

suggest adding below check in LoadTexture function of FBXLoader.js

> 			if ( extension === 'tga' ) {
> 			    console.log(THREE.Loader.Handlers.handlers);
> 				var loader = THREE.Loader.Handlers.get( '.tga' );
> 				console.log(loader);
> 				if ( loader === null ) {
> 
> 					console.warn( 'FBXLoader: TGALoader not found, creating empty placeholder texture for', fileName );
> 
> 					texture = new THREE.Texture();
> 
> 				} else {
>                     //Check embed Media, if true , set path to undefined
> 				    if (fileName.indexOf('blob:') === 0 || fileName.indexOf('data:') === 0) {
> 				        loader.setPath(undefined);
> 				    }
> 					texture = loader.load( fileName );
> 
> 				}

**Comment by looeee** [comment]
Can you share the model here?

**Comment by hifar** [comment]
you can try this fbx.

[test1.zip](https://github.com/mrdoob/three.js/files/2837387/test1.zip)

To reproduce this, you can  export  TGA Texture model to  fbx in 3ds max with embed media option. 

After I added this check code , this issue can be resolved.

>   		    if (fileName.indexOf('blob:') === 0 || fileName.indexOf('data:') === 0) {
>   		        loader.setPath(undefined);
>   		    }

**Comment by Roar1827** [comment]
@hifar I'm experiencing this same warning. Were you able to work around it? Thanks.

**Comment by looeee** [comment]
Fixed in #16993

You'll need t add the `TGALoader` like this in your app before using the `FBXLoader`: 

``` js
THREE.Loader.Handlers.add( /\.tga$/i, new TGALoader() );
```
