### ISSUE TITLE
Video samples fail on iOS

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#15732]
##### Description of the problem

The video samples:

https://threejs.org/examples/webgl_materials_video.html

https://threejs.org/examples/webgl_video_panorama_equirectangular.html

no longer work on iOS (no idea if they ever did but I suspect they did)

##### Three.js version

- [x] Dev
- [x] r101
- [ ] ...

##### Browser

- [ ] All of them
- [x] Safari
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

**Comment by TimvanScherpenzeel** [comment]
I can report the following, Macbook Pro (macOS High Sierra 10.13.6):

Desktop Safari (12.0.3):
- https://threejs.org/examples/webgl_materials_video.html (no thrown errors, won't play)
- https://threejs.org/examples/webgl_video_panorama_equirectangular.html (throws `Unhandled Promise Rejection: NotSupportedError: The operation is not supported.`, won't play)

Chrome (71):
- https://threejs.org/examples/webgl_materials_video.html (no thrown errors, won't play)
- https://threejs.org/examples/webgl_video_panorama_equirectangular.html (plays fine)

Firefox (65):
- https://threejs.org/examples/webgl_materials_video.html (plays fine)
- https://threejs.org/examples/webgl_video_panorama_equirectangular.html (plays fine)

**Comment by Mugen87** [comment]
`webgl_video_panorama_equirectangular.html` does not work in Safari because it does not support `WebM`: https://caniuse.com/#feat=webm

The video in `webgl_materials_video` does work if you just play it without WebGL. But for some reasons, things break as soon as you try to use it as a video texture.

I suspect the issue in Chrome is related to the autoplay policy. If I set the `muted` property in `webgl_video_panorama_equirectangular` to `false`, the demo stops working. But when I open both example via the side bar in https://threejs.org/examples/, they work perfectly.

**Comment by Mugen87** [comment]
@mrdoob Should we introduce a start screen for `webgl_materials_video` and `webgl_video_panorama_equirectangular` similar to the audio example? I mean with a start button and the description text: _Automatic audio playback requires a user interaction._

**Comment by Mugen87** [comment]
I've created a PR with the first approach so it's to see how it looks like.

**Comment by Mugen87** [comment]
Okay, `webgl_video_panorama_equirectangular` should be the only example now that does not work in Safari because of the missing `WebM` support. Not sure what to do in this case. Maybe politely ask Webkit to implement `WebM` support 😇 ?

**Comment by greggman** [comment]
Or switch to mp4 since it's supported everywhere at this point

[webms-as-mp4s.zip](https://github.com/mrdoob/three.js/files/2860125/webms-as-mp4s.zip)

**Comment by Mugen87** [comment]
I personally think since `WebM` is the more modern and royalty free format, I would leave the code as it is in `webgl_video_panorama_equirectangular`. All major browsers should support `WebM`.

**Comment by greggman** [comment]
Apple has no plans to ever support Webm. That means there are 1.3 billion iOS devices that require mp4 as the only video format their browser supports as well as > 50% of mac users who only use Safari.

**Comment by Mugen87** [comment]
I'm sorry, I am too rebellious and therefore unable to judge this issue objectively 😇

**Comment by greggman** [comment]
Well, if you want to try to be objective 

I see PRs rejected because they don't work in IE

IE's market share is less than 1 in 50 people
Safari's is greater than 1 in 7

**Comment by Mugen87** [comment]
Your numbers are fine. I just can't understand why Apple refuses to support `WebM` although it's the better format. This is the reason for my let's say "resistance". Anyway, @mrdoob should decide^^

**Comment by greggman** [comment]
The most obvious reason Apple doesn't support WebM because there's no hardware support for it so it uses much more battery than mp4.  They support hvec, I suspect other browsers will eventually too

https://caniuse.com/#feat=hevc

**Comment by Mugen87** [comment]
Okay, I have tested your MP4 files with the examples. Everything works fine but when using MP4 in `webvr_video` and Chrome, the video stutters. Especially when I move the mouse over links, bookmarks or menu points. That does not happen with WebM. 

This might be related to the way how the video texture is refreshed in the example.
