### ISSUE TITLE
Suggestion: WebGLRenderer and WebGL2Renderer init _pixelRatio = window.devicePixelRatio.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#15733]
I'm not sure this suggestion is good, `WebGLRenderer` and `WebGL2Renderer` init with
```js
let _pixelRatio = window.devicePixelRatio;
```

I see many `Examples` have this code.
```js
renderer.setPixelRatio( window.devicePixelRatio );
```

**Comment by Mugen87** [comment]
`window` is not available in a worker so doing this will break the code when `three.js` is executed in a separate thread.

Apart from that, I think it's better when it is set explicitly like the size of the renderer (width/height).
