### ISSUE TITLE
suspicious if-structure in reversePainterSortStable

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#15736]
In `reversePainterSortStable` in `src/renderers/webgl/WebGLRenderLists.js` there is either a sneaky copy & paste bug or at least (what should be) a code style violation:  
https://github.com/mrdoob/three.js/blob/0f671389163c4b0d9d02dae7badadb1517029380/src/renderers/webgl/WebGLRenderLists.js#L35-L55
Note the `} if ( a.z !== b.z ) {` missing an `else` or a line-break in line 45, presumably the `else` like in  `painterSortStable`.  
Tracing it back leads to a commit from Feb 20, 2015: 052f81ab6ed877935ad4657453752e9efa8018a4

**Comment by Mugen87** [comment]
Oh! That's indeed a bug. Can you make a PR with the fix?

**Comment by mrdoob** [comment]
A PR with the fix would be great indeed!
