### ISSUE TITLE
Uncaught TypeError: (intermediate value).setTranslation is not a function

### ISSUE THREAD

**Issue by imguccho** [mrdoob/three.js#15734]
Something like this should work as well with three.js v78, if you wanted to eg. rotate around your objects edge instead if its center:

``` .js
mesh.geometry.translate( -myObjectWidth/2, 0, 0 );
```

_Originally posted by @nylki in https://github.com/mrdoob/three.js/issues/1364#issuecomment-227131082_

**Comment by Mugen87** [comment]
Why have you created two issue, see #15735?
