### ISSUE TITLE
webaudio_orientation example is off by 90 degrees

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#15738]
The [webaudio_orientation](https://threejs.org/examples/#webaudio_orientation) example seems to be off by 90 degrees, assuming that it's not supposed to be possible to hear the music from behind the red wireframe box. 

As a side note, I think the example would have more impact if the "wall" was not wireframe - perhaps it could be made slightly transparent instead?

**Comment by Mugen87** [comment]
Thanks for finding this bug. It was introduced with #15424. We missed that audios might have no playback controls so `isPlaying` is always `false`.

I've tried to improved your demo according to your suggestions. The wall is now transparent which looks indeed a bit better.
