### ISSUE TITLE
Memory leak with TransformControls

### ISSUE THREAD

**Issue by mmaenz** [mrdoob/three.js#15743]
##### Description of the problem

When using TransformControls with angular references are left after dispose of component.
TransformControls.dispose() only releases listener but not any geometry or material associated with it so gc can't release memory (https://stackoverflow.com/questions/33152132/three-js-collada-whats-the-proper-way-to-dispose-and-release-memory-garbag/33199591#33199591)

It was even hard to find all references as it misused Object3D and not Group for ...XY/XYZ/XYZE...

What I did so far:
```
public static disposeTransformControl(node: THREE.Object3D) {
		if (node === undefined || node.children === undefined) return;
		for (let i = node.children.length - 1; i >= 0; i--) {
			let child = node.children[i];
			//child.userData = null;
			this.disposeTransformControl(child);
			const c = child as any;
			if (c.E) {
				this.disposeTransformControl(c.E);
				this.disposeNode(c.E);
				c.E = null;
			}
			if (c.XYZ) {
				this.disposeTransformControl(c.XYZ);
				this.disposeNode(c.XYZ);
				c.XYZ = null;
			}
			if (c.XY) {
				this.disposeTransformControl(c.XY);
				this.disposeNode(c.XY);
				c.XY = null;
			}
			if (c.XYZE) {
				this.disposeTransformControl(c.XYZE);
				this.disposeNode(c.XYZE);
				c.XYZE = null;
			}
			if (c.XZ) {
				this.disposeTransformControl(c.XZ);
				this.disposeNode(c.XZ);
				c.XZ = null;
			}
			if (c.YZ) {
				this.disposeTransformControl(c.YZ);
				this.disposeNode(c.YZ);
				c.YZ = null;
			}
			if (c.planes) {
				this.disposeTransformControl(c.planes);
				this.disposeNode(c.planes);
				c.planes = null;
			}
			if (c.activePlane) {
				this.disposeTransformControl(c.activePlane);
				this.disposeNode(c.activePlane);
				c.activePlane = null;
			}
			if (c.pickers) {
				this.disposeTransformControl(c.pickers);
				this.disposeNode(c.pickers);
				c.pickers = null;
			}
			if (c.handles) {
				this.disposeTransformControl(c.handles);
				this.disposeNode(c.handles);
				c.handles = null;
			}

			if (c.handleGizmos) {
				if (c.handleGizmos.E) {
					for (const ar of c.handleGizmos.E) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.handleGizmos.X) {
					for (const ar of c.handleGizmos.X) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.handleGizmos.Y) {
					for (const ar of c.handleGizmos.Y) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.handleGizmos.Z) {
					for (const ar of c.handleGizmos.Z) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.handleGizmos.XY) {
					for (const ar of c.handleGizmos.XY) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.handleGizmos.YZ) {
					for (const ar of c.handleGizmos.YZ) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.handleGizmos.XZ) {
					for (const ar of c.handleGizmos.XYZ) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.handleGizmos.XYZ) {
					for (const ar of c.handleGizmos.XYZ) {
						this.destructHandlerPicker(ar);
					}
				}

				if (c.handleGizmos.XYZE) {
					for (const ar of c.handleGizmos.XYZE) {
						this.destructHandlerPicker(ar);
					}
				}

				this.disposeTransformControl(c.handleGizmos);
				this.disposeNode(c.handleGizmos);
				c.handleGizmos = null;
			}

			if (c.pickerGizmos) {
				if (c.pickerGizmos.E) {
					for (const ar of c.pickerGizmos.E) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.pickerGizmos.X) {
					for (const ar of c.pickerGizmos.X) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.pickerGizmos.Y) {
					for (const ar of c.pickerGizmos.Y) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.pickerGizmos.Z) {
					for (const ar of c.pickerGizmos.Z) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.pickerGizmos.XY) {
					for (const ar of c.pickerGizmos.XY) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.pickerGizmos.YZ) {
					for (const ar of c.pickerGizmos.YZ) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.pickerGizmos.XZ) {
					for (const ar of c.pickerGizmos.XZ) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.pickerGizmos.XYZ) {
					for (const ar of c.pickerGizmos.XYZ) {
						this.destructHandlerPicker(ar);
					}
				}
				if (c.pickerGizmos.XYZE) {
					for (const ar of c.pickerGizmos.XYZE) {
						this.destructHandlerPicker(ar);
					}
				}
				this.disposeTransformControl(c.pickerGizmos);
				this.disposeNode(c.pickerGizmos);
				c.pickerGizmos = null;
			}

			this.disposeNode(child);
			node.remove(child);
			child = null;
		}
	}
```
Code is quick and dirty solution not meant as perfect solution!

What would be the right way to solve this?

Thanks
-Michael
##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by arodic** [comment]
Would changing `Object3D` to `Group` fix this issue?

Since all objects are part of the TransformControls hierarchy, you should be able to traverse and discard all of their geometries and materials in a simple `traverse()` loop. Maybe I'm missing something.

**Comment by mmaenz** [comment]
No it would'nt. dispose() only should be responsible for releasing resources that a allocated during creation. There should be no need to check twice for unreleased resources.

The real benefit of using Group over Object3D is when using typescript. Object3D is not designed to have more Object3D inside and needs to be casted to any. 

From the description of Group:
`This is almost identical to an Object3D. Its purpose is to make working with groups of objects syntactically clearer.` That is exactly what TransformControl needs, Group extends from Object3D and can hold multiple Object3D's like X/Y/Z/XY/XYZE...

I would prefer Group over Object3D.

**Comment by arodic** [comment]
Ah OK. The use of Group vs. Object3D is not relevant for memory disposal. Its a syntax clarity issue.

> When using TransformControls with angular references...

Is this issue particular to Angular in some way?

Also, can you turn your code example into a PR? It will make it easier to understand the intention. Moreover maybe we can come up with a more generalized solution that can be applied to other articulated rigs in threejs such as characters, camera controls, game objects etc....

You are also welcome to change Object3D to Group if you prefer it like that. If you do, please send it as a separate PR.

**Comment by trusktr** [comment]
@mmaenz Hmm, you're totally right, calling `dispose` on the controls does not actually dispose everything as one might be led to believe.

I started a forums thread about [cleaning things up](https://discourse.threejs.org/t/the-need-for-a-how-to-clean-things-up-section-of-the-docs/5831).

**Comment by arodic** [comment]
@trusktr @mmaenz @mrdoob would it make sense to first implement `dispose()` on `Mesh`, `Material`, `Line`, etc? I think it would help eliminate redundant implementations.

Thinking about it some more, perhaps it would be prudent **not** to dispose everything and reuse it across all instances of `TransformControls` instead.

Current `dispose()` function could be renamed to `disconnect( domElement )` and we should also have `connect( domElement )` function to help facilitate multi-viewport scenarios where different types of tools and controls can be connected/disconnected at any time.

**Comment by Mugen87** [comment]
`Material.dispose()` does already exit. However, what is the purpose of `Mesh.dispose()` and `Line.dispose()`?

**Comment by arodic** [comment]
> However, what is the purpose of Mesh.dispose() and Line.dispose()?

To dispatch dispose event on associated geometry and material.

**Comment by arodic** [comment]
@Mugen87 [Babylon.js](https://github.com/BabylonJS/Babylon.js/blob/master/src/Meshes/mesh.ts#L2012), it appears has a dispose function on mesh object with optional parameter to dispose recursively a well as materials and textures (optional). If this was implemented in Three.js, users of TransformControls, and any other rig for that matter can simply call `dispose()` and be done with it.

**Comment by Mugen87** [comment]
Okay, I see what you mean. Yes, it would make the disposal of objects easier. However, it would change how the current semantics of `dispose()`. Normally, objects just dispatch the dispose event and don't care about their properties. For instance a material does not call `dispose()` on its textures. For good reasons since the texture could be used in context of another material. If this is true and you dispose it, internal resources like the `WebGLTexture` object have to define from scratch.

So without refactoring, it would be no good idea to just add `Mesh.dispose()` or `Line.dispose()`.

**Comment by mmaenz** [comment]
Breaking the convention of Three extending dispose to a second parameter only for TransformControl to clean up makes no sense. Maybe it would be helpful to have a `TransformControl.destroy()` to release all of it's resources? This way developers can decide wether to reuse or to completely remove the control.

**Comment by mrdoob** [comment]
Would it make sense to introduce `dispose( recursive = false )` to `Object3D`?

**Comment by Mugen87** [comment]
If this means `Object3D.dispose()` is overwritten by `Mesh`, `Line` and `Points` and so they release their geometry and materials, we also have to enhance `Material.dispose()` in order to free the related textures.

However, I'm not sure about such a change. Consider a scenario where a user creates multiple meshes with the same material and geometry. If some of these meshes are removed over time, calling `Mesh.dispose()` would make things worse than before. As long as meshes with the same geometry and material are in the scene, all related WebGL resources have to be recreated from scratch by the renderer (also the shader program which is potentially very expensive). I just have the  fear `Object3D.dispose()` can easily be misused and things get dispose unintentionally.

**Comment by arodic** [comment]
Since there are no textures in TransformControls [this](https://github.com/mrdoob/three.js/pull/16065/files#diff-2f3358633f28f586c2b975857500460aR131) should do the trick, right?

What is the proper way to test this fix? I tried creating 10,000 instances of TransformControls with and without the fix without noticeable difference in GPU memory utilization :(

**Comment by mrdoob** [comment]
> However, I'm not sure about such a change. Consider a scenario where a user creates multiple meshes with the same material and geometry.

That's why I suggested `recursive` as `false` by default. Setting `recursive` would only be used when really wanting to clean everything.

> Since there are no textures in TransformControls [this](https://github.com/mrdoob/three.js/pull/16065/files#diff-2f3358633f28f586c2b975857500460aR131) should do the trick, right?

I think that looks good. I'll merge 👌

**Comment by Mugen87** [comment]
> That's why I suggested recursive as false by default. Setting recursive would only be used when really wanting to clean everything.

Oh, then I've interpreted the parameter incorrectly. I thought it would control the traversal through the object (so `dispose()` is also called for child objects).

**Comment by trusktr** [comment]
Maybe I should add a version of [these cleanup functions](https://github.com/infamous/infamous/blob/39ab9e3854f32911c1bc53ac0dca0d1696f4242d/src/utils/three.ts#L10-L61) onto `Object3D.prototype`?

It'll prevent errors like that fact that the new `TransformControls.dispose` method will crash on array materials.
