### ISSUE TITLE
Different angles haven't same result in webaudio_orientation.html

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#15746]
I'm not sure which screenshot has problem, the `Red Wall Mesh` isn't transparent in special angle.

![1](https://user-images.githubusercontent.com/23699926/52516090-f4acee80-2c5f-11e9-9f37-b78c62036b93.jpg)
![2](https://user-images.githubusercontent.com/23699926/52516091-fb3b6600-2c5f-11e9-8814-b26d32db61a9.jpg)

**Comment by looeee** [comment]
It remains transparent, as you can see from the background and floor. It's just the `gridHelper` that is having trouble, due to the transparency sorting algorithm. 

I guess we could fix this by making the helper non-transparent and setting it to a light grey color instead.

**Comment by Mugen87** [comment]
> I guess we could fix this by making the helper non-transparent and setting it to a light grey color instead.

Done!
