### ISSUE TITLE
SVGLoader places holes in wrong place if they use relative coordinates

### ISSUE THREAD

**Issue by openbrian** [mrdoob/three.js#15751]
##### Description of the problem

When an SVG has a path and this path has a hole, the hole doesn't start in the right place.

<path d="m 80,10 0,50 -70,0 0,-50 z m -51,31 5,0 0,-5 -5,0 z" />

In this case z should return the pointer to 80,10, but it doesn't.  When it runs the z command, the firstPoint has the wrong value.  It appears that the firstPoint is saved when at the END of the m command.  So it has the position of the last point.

It looks like the last change to this file is the cause of the issue.

I forked the project and created a branch called svgloader-bug-demo

https://github.com/openbrian/three.js/tree/svgloader-bug-demo

In this branch, I add test case 8 under examples/modesl/svg/tests/.  And I altered the SVGLoader example to use this file.  I also included a PNG for what the SVG looks like.  This matches what a browser would render.

##### Three.js version

- [x] Dev
- [ ] r101
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by makc** [comment]
Might be relevant: https://github.com/mrdoob/three.js/issues/14569#issuecomment-408537132

**Comment by openbrian** [comment]
@makc I think not.  This issue is all about identifying the firstPoint in a subpath.  WIth some console logging I could see the loader is misidentifying the first point.

**Comment by openbrian** [comment]
I can see from this commit https://github.com/mrdoob/three.js/commit/c04d08adf41ea7e8f791bf17411fb01bc8fd153a  that the old version would call setFirstPoint() when j == 0.  In the new version first point is only set after j reaches the number of points in the subpath, i.e. the last point.

**Comment by WestLangley** [comment]
ephemeral test link

https://raw.githack.com/openbrian/three.js/svgloader-bug-demo/examples/webgl_loader_svg.html

**Comment by openbrian** [comment]
Ah yes thanks.  There's the bug.  No hole.  I could work on this, but I don't know the purpose of the previous commit on the svgloader and I don't know if I'll break it.  Something about curves.  Is there a test case for it?  @yomboprime ?

**Comment by yomboprime** [comment]
It seems to me that the proper solution is to:

1 - Insert this line inside any `for` loop in the `switch`, once `point` is calculated there:
`if ( j === 0 && doSetFirstPoint === true) firstPoint.copy( point );`

2 - Change the final `if ( doSetFirstPoint === true )` block to just:
`doSetFirstPoint = false;` i.e. remove the `if` and the call to `copy`

I've done a quick test but don't have time to make today:


![screenshot_20190210_174022](https://user-images.githubusercontent.com/2453652/52536447-ff987980-2d5a-11e9-8439-9f852df7c15b.png)

**Comment by yomboprime** [comment]
Here is the modified SVGLoader.js
[SVGLoader.txt](https://github.com/mrdoob/three.js/files/2849132/SVGLoader.txt)

**Comment by openbrian** [comment]
Looks good.  I didn't review the modified SVGLoader.  Just make sure to do this for 'M' and 'm'.

Not really needed at this point, but fwiw here's a reference to the SVG spec which applies.  https://www.w3.org/TR/SVG/paths.html#TermInitialPoint
