### ISSUE TITLE
displacement map is ignored -  FBXLoader

### ISSUE THREAD

**Issue by ranbuch** [mrdoob/three.js#15760]
##### Description of the problem
As described [here](https://discourse.threejs.org/t/gltfexporter-exporting-invalid-gltf-from-fbx/6063) in some cases the `FBXLoader` ignores the `displacement map`

[Link to FBX file](https://cdn.hexa3d.io/hotlink-ok/test/33949.zip)

Thank you

##### Three.js version

- [ ] Dev
- [X] r101
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
There are two materials defined in this FBX file, and neither has a displacement map. The only texture node is the color map which is correctly loaded.
