### ISSUE TITLE
renderer.shadowMap.enabled prevents the model displaying on mobiles

### ISSUE THREAD

**Issue by gitMacchina** [mrdoob/three.js#15767]
Setting `renderer.shadowMap.enabled = true` prevents the model displaying on mobiles
https://github.com/mrdoob/three.js/issues/2023, it's just a black screen, but works fine on desktop browsers. By removing that line the model will then display on mobiles.

##### Three.js version

- [ X] r101

- [X ] iOS

![img_7636](https://user-images.githubusercontent.com/25795402/52695090-7f913000-2f63-11e9-85de-95f5862ea45f.PNG)
![img_7638](https://user-images.githubusercontent.com/25795402/52695100-84ee7a80-2f63-11e9-8a88-4a71be9cbe98.PNG)

**Comment by Mugen87** [comment]
Can you please share some information about your smartphone's hardware, the iOS and browser version? Besides, sharing a live example would be useful in order to test with different devices.

**Comment by gitMacchina** [comment]
I'm using an iPhone 8 running iOS 12.0 and tested it in Chrome (71.0.3578.89) and Safari.

The site is live at www.missed.flights but I've disabled shadowMap on iOS devices at the moment. I can create a test site later with shadowMap enabled.

**Comment by Mugen87** [comment]
Does this example work on your device? https://threejs.org/examples/webgl_shadowmap

**Comment by gitMacchina** [comment]
Yeah shadows are working in that example in both Chrome and Safari which makes me think it must be specific to me implantation.

This is a snippet of my code as it is with the shadows disabled on iOS:

> const renderer = new THREE.WebGLRenderer({
>     antialias: true
> });
> 
> const w   = window.innerWidth;
> const h   = window.innerHeight;
> const dpi = window.devicePixelRatio;
> 
> renderer.setSize(w, h);
> renderer.setPixelRatio(dpi);
> renderer.setClearColor(0x000000, 1);
> 
> const iDevices = [
>     'iPad Simulator',
>     'iPhone Simulator',
>     'iPod Simulator',
>     'iPad',
>     'iPhone',
>     'iPod'
> ];
> 
> let ios = false;
> 
> if (!!navigator.platform) {
>     while (iDevices.length) {
>         if (navigator.platform === iDevices.pop()){
>             ios = true;
>         }
>     }
> 
>     if (!ios) {
>         renderer.shadowMap.enabled = true;
>     }
> }
> 
> const section = document.querySelector("section");
> section.appendChild(renderer.domElement);
> 
> const scene = new THREE.Scene();
> 
> const camera = new THREE.PerspectiveCamera(50, w/h, 0.1, 10000);
> camera.position.z = 20;
> camera.position.x = -3;
> camera.position.y = 2;
> 
> //Bloom
> const params = {
>     exposure: 0.9,
>     bloomStrength: 0.32,
>     bloomThreshold: 0,
>     bloomRadius: 0.44
> };
> 
> const renderScene = new THREE.RenderPass( scene, camera );
> renderScene.setSize(w, h);
> 
> const bloomPass = new THREE.UnrealBloomPass( new THREE.Vector2( (dpi * w), (dpi * h) ), 0, 0, 0 );
> 
> bloomPass.renderToScreen = true;
> bloomPass.threshold = params.bloomThreshold;
> bloomPass.strength = params.bloomStrength;
> bloomPass.radius = params.bloomRadius;
> 
> composer = new THREE.EffectComposer( renderer );
> composer.setSize( dpi*w, dpi*h );
> composer.addPass( renderScene );
> 
> var FXAAShader = new THREE.ShaderPass(THREE.FXAAShader);
> 
> FXAAShader.renderToScreen = true;
> 
> FXAAShader.material.uniforms[ 'resolution' ].value.x = 1 / ( w * dpi );
> FXAAShader.material.uniforms[ 'resolution' ].value.y = 1 / ( h * dpi );
> 
> composer.addPass( FXAAShader );
> 
> composer.addPass( bloomPass );


Is it possible that this is to do with my poly count (~250k) or EffectComposer?

**Comment by Mugen87** [comment]
You might want to switch the order of adding your passes to the composer. So render pass first, then the bloom pass  and lastly the FXAA pass. It also makes not sense to set `bloomPass.renderToScreen` to `true` if you want to apply `FXAA` after it.

Anyway, it might be interesting to know if there are any warnings in your browser console. These messages might be helpful to analyze the issue

**Comment by gitMacchina** [comment]
Thanks for the advice, I'll give that a try.

There are no messages/warnings in the console.

**Comment by Mugen87** [comment]
> There are no messages/warnings in the console.

Too bad. Well, as long as you can't  proof it's a bug in the library, this issue should be closed. Instead, try to demonstrate the problem with a live example and use the [forum](https://discourse.threejs.org/) or stackoverflow for more help.

When your black screen is actually a bug of the renderer, we can reopen this issue,
