### ISSUE TITLE
GLTFLoader: Forcing the format of a texture after execution of the texture loader.

### ISSUE THREAD

**Issue by CharlesJPL** [mrdoob/three.js#15763]
##### Description of the problem
In our project, we have an Uber texture loader that is replacing JPG/PNG textures from a GLTF model by the corresponding compressed texture (DXT, ETC, PVRTC, ASTC) dynamically. It then calls either the KTX Loader for compressed textures or the Texture Loader if no compressed texture was found.

But if the original GLTF file contains a mimeType for the texture, the GLTF loader is replacing our compressed texture format to either RGB or RGBA just after even if the texture returned by the loader is a compressed one and it will result in an invalid texture.

**GLTF file contains:**
``` 
"images" : [
  {
    "mimeType" : "image/jpeg",
    "name" : "test",
    "uri" : "test.jpg"
  }
],
```

**GLTF Loader source:** https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/GLTFLoader.js#L2201-L2206

Is this behavior really needed ? because the Texture loader should take care of updating the texture format beforehand.

**Texture Loader source:**
see: https://github.com/mrdoob/three.js/blob/dev/src/loaders/TextureLoader.js#L36

Our workaround is to save the texture format in the Uber texture loader and re-apply it after execution of the GLTF loader.

We're still not happy on how we manage the compressed textures for each platform so if you have suggestions I'll be happy to read them.

Thanks,

Original commit: https://github.com/mrdoob/three.js/commit/c8407b4c53db78f99e6732e105a4ae530956d3c3

##### Three.js version
- [x] Dev
##### Browser
- [x] All of them
##### OS
- [x] All of them
##### Hardware Requirements (graphics card, VR Device, ...)
N/A

**Comment by donmccurdy** [comment]
> Is this behavior really needed ? because the Texture loader should take care of updating the texture format beforehand.

TextureLoader `.format` detection relies on the file extension, so given a model with embedded textures it has no idea and will default to `RGBAFormat`. When everything is set to `RGBAFormat` we run into issues like https://github.com/mrdoob/three.js/issues/14757. 

Longer term glTF will have a compressed texture extension to handle this, but meanwhile... I guess GLTFLoader could check if `texture.format` is already something other than `RGBAFormat`, and if so, leave it alone?

/cc https://github.com/mrdoob/three.js/pull/15758 + @mrdoob

**Comment by mrdoob** [comment]
> Longer term glTF will have a compressed texture extension to handle this, but meanwhile... I guess GLTFLoader could check if `texture.format` is already something other than `RGBAFormat`, and if so, leave it alone?

I guess that sounds good to me.. Does this conflict with #15758 though?

**Comment by donmccurdy** [comment]
> Does this conflict with #15758 though?

Maybe not, but we'll have to check for `texture.format` there too... if the `normalMap` is a PNG, the effect of setting RGBFormat instead of RGBAFormat is just less GPU memory, correct?

**Comment by mrdoob** [comment]
> the effect of setting RGBFormat instead of RGBAFormat is just less GPU memory, correct?

That's my guess. Unfortunately I do not know tools to double check this.

**Comment by c-andrews** [comment]
Has there been any developments with multiple Compressed Textures within a GLTF file? If i've missed it could you point me in the right direction.

**Comment by donmccurdy** [comment]
@c-andrews on the file format side, yes. An open source technology called Basis [has been announced](https://www.khronos.org/blog/google-and-binomial-contribute-basis-universal-texture-format-to-khronos-gltf-3d-transmission-open-standard), and will be used by glTF to support cross-platform compressed textures. However, the specification work is not finished – see https://github.com/KhronosGroup/glTF/pull/1612. Three.js supports Basis (via THREE.BasisTextureLoader) for loading textures separately, but it is not yet possible to embed them in glTF files.

**Comment by donmccurdy** [comment]
This was fixed a while back, the changes to `.format` are only applied if the texture is not compressed.
