### ISSUE TITLE
Unexpected result with CreateFromMorphTargetSequence function when repeating morphtargets

### ISSUE THREAD

**Issue by nicolasbotanic** [mrdoob/three.js#15774]
##### Three.js version

- [ ] Dev
- [x] r101
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

Each time you repeat the same morphtarget in a sequence generated by CreateFromMorphTargetSequence it will have less maximum influence. Resulting max influence is 1/morphtarget_appareances.
I expected all morphtargets to reach a maximum influence of 1 always 

ex: 
A sequence with two  morphtarget 0 and one morphtarget 1 will show morphtarget 0 with a maximum influence of 0.5 each time and morphtarget 1 with max influence of 1

A sequence with three  morphtarget 0, two morphtarget 1 and one morphtarget 2 will show morphtarget 0 with a maximum influence of 0.33 each time,  morphtarget 1 with max influence of 0.5 and morphtarget 2 with max influence of 1

Code: https://jsfiddle.net/qdmuw3Lz/2/

**Comment by Mugen87** [comment]
You are not creating your morph target sequence correctly. It's not right to pass the same morph target several times in a row into a sequence. You have to do it like so:

https://jsfiddle.net/gxsfobyp/1/

If you want a different duration per morph target, you have to create the keyframe tracks by yourself.

**Comment by nicolasbotanic** [comment]
@Mugen87 it still happens when there are repetition but not in a row.
check mt2 never reach influence 1 in this sequence: https://jsfiddle.net/kw6ru59n/

I see this example as proper use of CreateFromMorphTargetSequence

Also if this is a bug, it would be good if the fix allows to repeat morphtargets in a row too (it would be an intuitive result to get a freezed animation and I guess it wont hurt to make it so)

**Comment by Mugen87** [comment]
@donmccurdy Isn't it a bit unusual to built a morph target sequence like this? I've never seen this before. Normally, a morph target appears in a morph target sequence just once.

**Comment by donmccurdy** [comment]
Given the API provided by `CreateFromMorphTargetSequence`, this usage seems OK to me. It's a pretty blunt way of controlling the sequence timing, but it's the only way exposed by that API, so I'm willing to consider it a bug.

***

Aside, I think `CreateFromMorphTargetSequence` should go the way of `THREE.Geometry` and be deprecated at some point. Passing an array of `Vector3` vertices is far from optimal, and doesn't work with `BufferGeometry`. Better alternatives exist, and could easily be wrapped up into a nice API that gives fine-grained control over the timing of each target. For example:

```js
var geometry = new THREE.BufferGeometry();
var position = new THREE.BufferAttribute( new Float32Array( [ 0, 0, 0, 0, 0, 1, 1, 0, 1 ] ), 3 );
geometry.addAttribute( 'position',  position );
geometry.morphAttributes.position = [ position, position, position, position ];

var mesh = new THREE.Mesh( geometry );
mesh.morphTargetDictionary.a = 0;
mesh.morphTargetDictionary.b = 1;
mesh.morphTargetDictionary.c = 2;
mesh.morphTargetDictionary.d = 3;

var timesA =  [ 0, 1, 2 ];
var timesB =  [       2, 3, 4 ];
var timesC =  [             4, 5, 6 ];
var valuesA = [ 0, 1, 0 ];
var valuesB = [       0, 1, 0 ];
var valuesC = [             0, 1, 0 ];
var trackA = new THREE.VectorKeyframeTrack( '.morphTargetInfluences[a]', timesA, valuesA, THREE.InterpolateLinear );
var trackB = new THREE.VectorKeyframeTrack( '.morphTargetInfluences[b]', timesB, valuesB, THREE.InterpolateLinear );
var trackC = new THREE.VectorKeyframeTrack( '.morphTargetInfluences[c]', timesC, valuesC, THREE.InterpolateLinear );

var clip = new THREE.AnimationClip( 'clip1', undefined, [ trackA, trackB, trackC ] );
```

**Comment by donmccurdy** [comment]
I'm not fully sure that a higher-level API like `CreateFromMorphTargetSequence` is even needed, because setting up the input sequences at least as complex as what the method actually does. But if we wanted a replacement, I'd suggest something like:

```js
var clip = THREE.AnimationUtils.createClipFromMorphTargetSequence(
  'clipName',
  [ t0, t1, t2, t3, ... ],
  [ 'targetA', 'targetB', 'targetA', 'targetC', ... ]
);
```

**Comment by Mugen87** [comment]
Apart from your API suggestion, I was curious what's actually happen under the hood. If you add the same morph target multiple time into a morph target a sequence of morph targets, the equal amount of animation tracks with the same name is created. That means the animation system internally creates the same property mixer and property binding for a single entity (e.g. `.morphTargetInfluences[target0]`). Tracks with the same name have unique interpolators but identical result buffers. This leads to an accumulation of animated values and not the the effect @nicolasbotanic is hoping. From my point of view, it's just a wrong interpretation of how the animation system should be used. And we should not consider this as a bug. It's the intended behavior of the system.

**Comment by Mugen87** [comment]
BTW: Certain loaders (`LegacyJSONLoader`,`MD2Loader` and `SEA3DLoader`) use `AnimationClip.CreateClipsFromMorphTargetSequence` and `AnimationClip.CreateFromMorphTargetSequence`. So removing them means providing alternative solutions for these classes.

**Comment by donmccurdy** [comment]
Better output for `CreateFromMorphTargetSequence`, given multiple occurrences of the same target, would be a single track like:

```js
var track = new THREE.VectorKeyframeTrack(
  '.morphTargetInfluences[a]',
  [ 0, 20, 40, 60, 80 ], 
  [ 0, 1,  0,  1,  0 ],
  THREE.InterpolateLinear
);
```

But since I'm suggesting that we deprecate `CreateFromMorphTargetSequence`, I won't argue that its behavior should be changed. An alternative solution for the loaders above should be feasible, and probably an improvement for the latter two that are (hopefully?) using BufferGeometry now.

**Comment by nicolasbotanic** [comment]
@Mugen87 I understand you know the internals of this so for sure your POV is different than mine (and frankly and a newbie on this). Looking at the documentation for CreateFromMorphTargetSequence it says "Returns a new AnimationClip from the passed morph targets array of a geometry" so from this sentence without knowing the internals my interpretation is I put an array of targets and I get a resulting animation from one to the next target in the array with all the assumptions I expressed in my previous comments.

If your POV of the proper way the API should be used, what would be the correct documentation for it which would prevent any bad interpretation?

**Comment by Mugen87** [comment]
> If your POV of the proper way the API should be used, what would be the correct documentation for it which would prevent any bad interpretation?

Well, the documentation should highlight that adding the same morph target multiple times in a row is not valid^^. However, from my point of view this method should not be part of the "real" public API which is intended for users. I think `CreateFromMorphTargetSequence` is more a helper for loaders in order to create animation clips from their morph targets. TBH, I think the library should not provide an interface for user in order to define morph targets. As demonstrated earlier in the issue, when users define their keyframe tracks directly the existing API is sufficient.

> and probably an improvement for the latter two that are (hopefully?) using BufferGeometry now.

Yes, all loaders except `LegacyJSONLoader` are based on `BufferGeometry` now.
