### ISSUE TITLE
Demo Material Skin problem uv inversion

### ISSUE THREAD

**Issue by greatAznur** [mrdoob/three.js#15771]
##### Description of the problem

I use the export gltf blender (the last on the site khronos) it works very well on the example webgl_loader_gltf the texture is displayed everything is ok I have a problem when I use it with webgl_materials_skin the uv is reverse
by editing the file  we can see that the UV is reversed
when I saye a blender since a new model must reverse the uv and everything except practice besides that it is and only compatible with the demo webgl_materials_skin

Describe the bug or feature request in detail.

https://imageshack.com/a/img924/7003/99rBCI.png
##### Three.js version

- [ ] Dev
- [X] r101
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by titansoftime** [comment]
Same, I have been manually inverting the uv's in blender to compensate. However I believe this issue belongs on the https://github.com/KhronosGroup/glTF-Blender-IO page.

**Comment by donmccurdy** [comment]
We need more details to reproduce this than “when I use it with webgl_materials_skin the uv is reverse“. Please share the complete code or a demo. If you’re loading a glTF model and then changing the material or textures, note the documentation under *Textures* here: 
https://threejs.org/docs/index.html#examples/loaders/GLTFLoader

**Comment by titansoftime** [comment]
Don't have any files at this particular workstation however I can say that I personally don't use the materials/textures from the gltf file, just the geometry and the uv's are definitely reversed compared to at least how the three-io exporter handled it.

**Comment by manthrax** [comment]
I have had this problem before and want to re-emphasize donmccurdys mention about **flipY**

**Comment by donmccurdy** [comment]
Closing this for now – it sounds like `flipY=false` needs to be set on the textures, but glad to take a closer look with further detail.
