### ISSUE TITLE
OrbitControls keydown event

### ISSUE THREAD

**Issue by Bertagit** [mrdoob/three.js#15776]
##### Description of the problem

The controls add an event keydown on window, though a specific dom element is passed at the constructor, this prevent the use of keyboard, also in text input, throughout the DOM. In my project i use vue.js with vuetify

In OrbitControls.js at the row 929:
`window.addEventListener( 'keydown', onKeyDown, false );`
for fix the problem my solution is replace this line with:
`scope.domElement.addEventListener( 'keydown', onKeyDown, false );`

##### Three.js version

- [ ] Dev
- [x] r101
- [ ] ...

##### Browser

- [x] All of them
- [] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Isn't your issue already solved by https://github.com/mrdoob/three.js/pull/15693? Please verify this with the latest `dev` version of `OrbitControls`.

https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/OrbitControls.js

**Comment by Bertagit** [comment]
#15693  fix the bug. Thanks for the support
