### ISSUE TITLE
setScene in Editor.js

### ISSUE THREAD

**Issue by deping** [mrdoob/three.js#15773]
##### Description of the problem
Always add children[0] and while loop seems endless, I didn't seem remove children[0] from scene.

https://github.com/mrdoob/three.js/blob/a39c8a82541fcd3f89d750ad0804359827e091bc/editor/js/Editor.js#L127-L131

##### Three.js version

- [ ] Dev
- [x] r101
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> Always add children[0] and while loop seems endless, I didn't seem remove children[0] from scene.

Sorry, but it's not clear what your issue is about. Can you please elaborate a bit?

**Comment by deping** [comment]
I find that function setScene in Editor.js is confusing(endless loop to add child 0 of scene), may be wrong.
```
while ( scene.children.length > 0 ) { 
  
 	this.addObject( scene.children[ 0 ] ); 
  
 }
```

**Comment by Mugen87** [comment]
When the above code adds the children of the given scene to the scene of the editor, `Object3D.add()` ensures that objects are removed from the former parent. Check out the following code snippet:

https://github.com/mrdoob/three.js/blob/27811881f61e647ae2b8b009e3032f62739c2c25/src/core/Object3D.js#L383-L387

So the code in `Editor.js` is actually correct.
