### ISSUE TITLE
FbxLoader.js: parseAnimationLayers get wrong eulerOrder

### ISSUE THREAD

**Issue by huoguangjin** [mrdoob/three.js#15788]
```js
sceneGraph.traverse( function ( child ) {

    if ( child.ID = rawModel.id ) {

        node.transform = child.matrix;

        if ( child.userData.transformData ) node.eulerOrder = child.userData.transformData.eulerOrder;

    }

} );
```
Condition `child.ID = rawModel.id` is always true, so the `THREE.QuaternionKeyframeTrack` parsed from FBX file will get a wrong `eulerOrder`.

https://github.com/mrdoob/three.js/blob/e284e9bf28c422131a02f9af44b9813aed9828b9/examples/js/loaders/FBXLoader.js#L2513

**Comment by mrdoob** [comment]
@looeee seems like an easy fix?

**Comment by mrdoob** [comment]
Fixed. Thanks!
