### ISSUE TITLE
OrbitControls with and without damping are vastly different

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#15801]
##### Description of the problem

Maybe this isn't a bug but ... if I put OrbitControls in and the only thing I change is if `enableDamping` = true or false the sensitivity is vastly differnt

Example, just use the default example

* [jsfiddle](https://jsfiddle.net/3foLr7sn/) (latest release branch)

That's `enableDamping` = false. You can see dragging the mouse across the sphere rotates about 1/3 a revolution

![orbitcontrols-enabledamping-false](https://user-images.githubusercontent.com/234804/52995518-3eff4e00-345e-11e9-9452-0a825927e2c2.gif)

Add `controls.enableDamping = true` and uncomment the `controls.update();` line and suddenly it rotates 1.66 revolutions.

![orbitcontrols-enabledamping-true](https://user-images.githubusercontent.com/234804/52995579-648c5780-345e-11e9-83e5-84789c84ea90.gif)

I would think as a user of the library the amount of revolution in those 2 cases should be about the same and the only difference is whether or not the sphere keeps spinning after I release the mouse if the last mouse event was different than the next to last mouse event?

Should this be adjusted to match or is that the way it's meant to be?

note this seems to be related to https://github.com/mrdoob/three.js/issues/9577 

##### Three.js version

- [x] Dev
- [x] r101

##### Browser

- [x] All of them

##### OS

- [x] All of them

##### Hardware Requirements (graphics card, VR Device, ...)

N/A

**Comment by Mugen87** [comment]
> Should this be adjusted to match or is that the way it's meant to be?

I would say a consistent behavior like you have mentioned would be desirable.

I just wonder if we should merge your post with #9577 in order to make it easier to track this issue. Essentially, it also about speed and sensitivity of `OrbitControls`.

**Comment by WestLangley** [comment]
If you set `controls.enableDamping = true;`, you must also set `controls.update()` in the render loop.

**Comment by greggman** [comment]
> If you set `controls.enableDamping = true;`, you must also set `controls.update()` in the render loop.

Yes, that doesn't change the issue. The result is the same

**Comment by WestLangley** [comment]
Your demo does not show the intended behavior, because your code is not correct.

**Comment by greggman** [comment]
Sorry I tried to be helpful. I keep forgetting I shouldn't do that in this repo

**Comment by arodic** [comment]
Hey Greg, thanks for reporting this, I also noticed it while refactoring controls in another repo. If I remember it correctly, it was physics bug. The difference in behavior is also evident in misc_orbit_controls.html example. Hopefully, #9577 will account for this.
