### ISSUE TITLE
OrbitControls: handleKeyDown is eating all the keys events

### ISSUE THREAD

**Issue by mghini** [mrdoob/three.js#15810]
##### Description of the problem

The changed implementation for handleKeyDown of OrbitControls is preventing every keys event to be received by the browser.
If the 3D view has the focus, users are unable to send any keydown input event to the browser, even the more obvious, such as F5.
Testable from [orbit example](https://threejs.org/examples/?q=orbit#misc_controls_orbit)

the right implementation for the function handleKeyDown should call preventDefault only if needed, like in the following code:

	function handleKeyDown( event ) {

		//console.log( 'handleKeyDown' );

		switch ( event.keyCode ) {

			case scope.keys.UP:
				event.preventDefault();
				pan( 0, scope.keyPanSpeed );
				scope.update();
				break;

			case scope.keys.BOTTOM:
				event.preventDefault();
				pan( 0, - scope.keyPanSpeed );
				scope.update();
				break;

			case scope.keys.LEFT:
				event.preventDefault();
				pan( scope.keyPanSpeed, 0 );
				scope.update();
				break;

			case scope.keys.RIGHT:
				event.preventDefault();
				pan( - scope.keyPanSpeed, 0 );
				scope.update();
				break;

		}

##### Three.js version

- [x] Dev
- [x] r101
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This should be already fixed by https://github.com/mrdoob/three.js/pull/15693
