### ISSUE TITLE
A shadow acne with a freshly inserted mirrored mesh

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#15821]
##### Description of the problem

When a mesh is inserted into the scene with a mirroring scale (-1,1,1), the shadow in the first frame after insertion is rendered wrongly, resulting in shadow acne. My guess is the first time the shadow map is rendered wrong side is used for shadow casting for mirrored objects.

I understand it is not an important issue for most users as the glitch lasts only one frame and mirroring is needed to show it. I am willing to provide the fix if possible, but I would like to get some advice what to look for.

Acne screenshot:

![image](https://user-images.githubusercontent.com/6927223/53200127-18d5db80-3621-11e9-9619-32e0643eb198.png)

Code needed to reproduce can be seen at: https://github.com/mrdoob/three.js/commit/b37102e3be3f312fa872ce82834620d23f85c5cc

Or in the live example: https://jsfiddle.net/bnkmufao/

##### Three.js version

- [x] Dev
- [ ] r101
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Tested on one nVidia and one ATI card, reproduced on both of them, I guess it is not HW related.

**Comment by WestLangley** [comment]
>My guess is the first time the shadow map is rendered wrong side is used for shadow casting for mirrored objects. ... I would like to get some advice what to look for.

That's a reasonable hypothesis. Look for `frontFaceCW` in the source.
