### ISSUE TITLE
GLTFLoader: Incorrect texture transform.

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#15831]
Reported by @scurest in https://github.com/KhronosGroup/glTF-Blender-IO/pull/299#event-2158076463, GLTFLoader is not getting texture transforms correct in some cases.

[disagree.zip](https://github.com/mrdoob/three.js/files/2897504/disagree.zip)

Left: ThreeJS
Right: Expected

![53119706-a88e6380-3515-11e9-85a9-cb40489d2e0f](https://user-images.githubusercontent.com/1848368/53294263-4abd7e00-3798-11e9-881c-f44a5b30d508.jpg)

Here is the [`KHR_texture_transform` specification](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_transform), but note there is a [mistake that needs correction](https://github.com/KhronosGroup/glTF/issues/1563).

##### Three.js version

- [ ] Dev
- [x] r101
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by scurest** [comment]
So...

I looked at what happens to the TRS transform `Trans[t] * Rot[r] * Scale[s]` when you switch from a UV space where the origin is at the top-left to one where it is at the bottom-left but the image is upside down. I was wrong earlier about the center of rotation, having it be the bottom-left is correct. It looks like all that needs to happen is the rotation needs to be negated: `Trans[t] * Rot[-r] * Scale[s]`.

Assuming that this is the function that sets the matrix...

https://github.com/mrdoob/three.js/blob/34dc2478c684066257e4e39351731a93c6107ef5/src/math/Matrix3.js#L276-L287

Then, if I factored right, this is doing

```
Trans[tx, ty] *
Trans[cx, cy] *
Scale[sx, sy] *
Rot[-rotation] *
Trans[-cx, -cy]
```

[(evidence)](https://www.wolframalpha.com/input/?i=%7B%7B1,0,t_1%7D,%7B0,1,t_2%7D,%7B0,0,1%7D%7D+.+%7B%7B1,0,c_1%7D,%7B0,1,c_2%7D,%7B0,0,1%7D%7D+.+%7B%7Bs_1,0,0%7D,%7B0,s_2,0%7D,%7B0,0,1%7D%7D+.+%7B%7Bcos+theta,+sin+theta,+0%7D,%7B-sin+theta,+cos+theta,+0%7D,+%7B0,0,1%7D%7D+.+%7B%7B1,0,-c_1%7D,%7B0,1,-c_2%7D,%7B0,0,1%7D%7D)

Taking (cx, cy) = (0, 0) you get `Trans[t] * Scale[s] * Rot[-r]`. Note the order of the scale and rotation.

So this would explain it. And indeed, if I hack in a `setUvTransform` that does `Trans[t] * Rot[-r] * Scale[s]`

```js
var c = Math.cos( rotation );
var s = Math.sin( rotation );

this.set(
    sx * c, sy * s, tx,
    - sx * s, sy * c, ty,
    0, 0, 1
);
```

the expected result is obtained.

----

There is not, in general, a way to compute an `r'` and `s'` st. `Scale[s'] * Rot[-r'] = Rot[-r] * Scale[s]`, so there's no way you can set the `rotation` and `scale` in the loader to fix this.

So my recommended fix is for the loader to set `texture.matrixAutoUpdate = false` and set `texture.matrix` to the correct TRS matrix manually :+1:

**Comment by donmccurdy** [comment]
Thanks @scurest!

> There is not, in general, a way to compute an `r'` and `s'` st. `Scale[s'] * Rot[-r'] = Rot[-r] * Scale[s]`, so there's no way you can set the `rotation` and `scale` in the loader to fix this.

Do you know whether one way or the other is more common practice (other than in glTF and threejs – in both of which this is a fairly new feature)? As you suggest I get the correct result with:

```js
texture.matrixAutoUpdate = false;

texture.matrix
	.identity()
	.scale( scale[ 0 ], scale[ 1 ] )
	.rotate( rotation )
	.translate( offset[ 0 ], offset[ 1 ] );
```

However, requiring on `matrixAutoUpdate=false` means we're going to have a bad time animating texture transforms when that glTF extension is eventually complete, and it's one I'd like to support. 😞 Our animation system uses [VectorKeyframeTrack](https://threejs.org/docs/#api/en/animation/tracks/VectorKeyframeTrack) and [NumberKeyframeTrack](https://threejs.org/docs/#api/en/animation/tracks/NumberKeyframeTrack) to target specific properties.

@WestLangley when the `texture.rotation` feature was originally added, you included [this comment](https://github.com/mrdoob/three.js/blob/4a477b7b0d874d2d7036ebf4aedd62760ccf7c90/examples/webgl_materials_texture_rotation.html#L151):

> I don't understand how rotation can preceed scale, but it seems to be required...

I feel bad suggesting we change this just because GLTFLoader would benefit, but what would you think of altering `setUvTransform` here?

**Comment by WestLangley** [comment]
I chose to implement texture rotation in three.js so that rotating the texture would not induce shearing when the scale was non-uniform. That meant that scaling needed to be applied before rotation.

I also chose to consider `center` as a pivot point around which _both_ scaling and rotation occurred.

These were arbitrary decisions made by me.

Presumably the existing code implements that, but based on this thread and my inline comment, something may be amiss...

I would be interested in seeing how a proposed change impacts https://threejs.org/examples/webgl_materials_texture_rotation.html.

**Comment by AndrewRayCode** [comment]
I'm import a GLTF model into three with a fairly simple unwrap, and I'm seeing the texture applied unexpectedly. Blender:

<img width="971" alt="Screen Shot 2020-03-16 at 8 02 20 PM" src="https://user-images.githubusercontent.com/79215/76817807-1bbde400-67c1-11ea-8bf3-11ce7950e269.png">

Threejs:

<img width="372" alt="Screen Shot 2020-03-16 at 8 02 31 PM" src="https://user-images.githubusercontent.com/79215/76817814-211b2e80-67c1-11ea-94c4-a2bf72b56734.png">

Are there any hotpatches that can be done after the import is complete to get correct texture alignment?

**Comment by donmccurdy** [comment]
@AndrewRayCode could you share the `.blend` and glTF files? ZIP archives can be dragged into github comments.

**Comment by AndrewRayCode** [comment]
Blender:

<img width="1147" alt="Screen Shot 2020-03-16 at 8 48 33 PM" src="https://user-images.githubusercontent.com/79215/76820160-8bcf6880-67c7-11ea-953e-1839f054e49d.png">

Three:

<img width="486" alt="Screen Shot 2020-03-16 at 8 47 42 PM" src="https://user-images.githubusercontent.com/79215/76820246-d650e500-67c7-11ea-8b3c-3b67c8206c87.png">

I'm exporting as gltf without materials, and manually assigning the material in three:
```js
 gltf.scene.children[0].material = cat;
```

Zip file attached:

[BlenderCatGltfExportWrongUvsTestThreejsGithub.zip](https://github.com/mrdoob/three.js/files/4341387/BlenderCatGltfExportWrongUvsTestThreejsGithub.zip)

**Comment by AndrewRayCode** [comment]
@donmccurdy hmm if I use the embedded image format with materials checked, it looks right in threejs. but if I make a `new MeshStandardMaterial({ map: sameCatTexture })` and then apply it to the mesh with `gltf.scene.children[0].material = myMaterial`, it doesn't have the right UVs

**Comment by donmccurdy** [comment]
> but if I make a new MeshStandardMaterial({ map: sameCatTexture }) and then apply it to the mesh with gltf.scene.children[0].material = myMaterial, it doesn't have the right UVs

This could break for a couple reasons:

1. glTF UV coordinate system does not flip the Y axis, so you need to set `texture.flipY = false` when loading a texture separately (see [GLTFLoader docs](https://threejs.org/docs/#examples/en/loaders/GLTFLoader))
2. If you've set custom UV transforms in Blender, those would be attached to the _texture_, not the UV map, so you'd need to manually re-transform your texture in three.js to maintain that.

**Comment by AndrewRayCode** [comment]
@donmccurdy ok, that makes sense. This is difficult for my case because I would like to integrate GLTF models into a pipeline where I replace the materials on them in a game engine.

However, setting `.flipY = false` on the texture before applying it to the model **worked for me.** I don't even know what UV transforms are in blender, so hopefully I can ignore that issue for now

**Comment by donmccurdy** [comment]
UV transforms (also called texture transforms) would be something like this, if the values on the Mapping node are customized:

![Screen Shot 2020-03-16 at 9 46 38 PM](https://user-images.githubusercontent.com/1848368/76822884-9f7ecd00-67cf-11ea-9cac-2272bb906685.png)

Even when you are exporting the textures from Blender, those are only supported in three.js with some major caveats, so ignoring it might be best. :)

**Comment by mrdoob** [comment]
Is this still an issue?

**Comment by donmccurdy** [comment]
The example attached by @AndrewRayCode appears correctly in three.js now:

![Screenshot 2023-06-23 at 12 41 23 PM](https://github.com/mrdoob/three.js/assets/1848368/70f40cbd-c464-4727-8527-21fbc199e21d)

The example in the OP (disagree.zip) remains inconsistent between three.js and babylon.js, but I have not seen any user-reported occurrences of this problem. 

I would vote to close this issue, track https://github.com/KhronosGroup/glTF/issues/1563, and reopen if that issue is resolved and requires updates from us.

**Comment by donmccurdy** [comment]
A bit more context, from https://github.com/KhronosGroup/glTF-Blender-IO/issues/2366#issuecomment-2400464322. Currently the three.js UV transform implementation does not match the glTF specification when the UV transform contains both:

1. non-uniform scaling
2. non-zero rotation

If scaling is uniform, or there's no rotation, then Scale[s] x Rot[-r] = Rot[-r] x Scale[s] should be equivalent. As @WestLangley mentions above, we have our reasons for the choice, and it's not obvious whether changing the UV transform implementation now would benefit our users. I'm hesitant for GLTFLoader to disable `texture.matrixAutoUpdate = false` automatically — think that would require downstream workarounds for the R3F/Threlte/Tresjs libraries.

We could perhaps log a warning in GLTFLoader if non-uniform scaling and non-zero rotation are observed, since we can be sure the result will be incorrect, though it's unclear what the user can do with that information.
