### ISSUE TITLE
Fix type of elements property in Matrices 

### ISSUE THREAD

**Issue by thinkimlazy** [mrdoob/three.js#15839]
##### Description of the problem
In math module i.e. Matrix3 or Matrix4 has property  _elements_ of type [number].
But in documentation and in TS typings it's stated as typed array(Float32Array).
So `new Matrix3().elements instanceof Float32Array` is gonna be false.
```
 function Matrix3() {

	this.elements = [

		1, 0, 0,
		0, 1, 0,
		0, 0, 1

	];
```

maybe it would be better change it to something like
``` 
function Matrix3() {
	this.elements = new Float32Array([

		1, 0, 0,
		0, 1, 0,
		0, 0, 1

	]);
```

##### Three.js version
- [x] Dev

##### Browser
- [x] All of them

##### OS
- [x] All of them

**Comment by Mugen87** [comment]
Please read https://github.com/mrdoob/three.js/pull/10702 to understand why code should not be changed. It's better to correct the docs. Would you like to do this change?

**Comment by thinkimlazy** [comment]
Ok, I would like to do it.

**Comment by Mugen87** [comment]
If you are still interested in doing this change, then please have a look at the contribution guide:

https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js

It hopefully helps to setup a valid PR.
