### ISSUE TITLE
renderTarget argument has been removed in r102

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#15849]
Not a single issue with the current r101.
The problem started with the current 102dev.
I get hundreds of console warnings like this one:

THREE.WebGLRenderer.render(): the renderTarget argument has been removed. Use .setRenderTarget() instead. three.min.js:197:289
THREE.WebGLRenderer.render(): the forceClear argument has been removed. Use .clear() instead. three.min.js:197:434

I get those warnings with many samples.
Here is one of them:
http://necromanthus.com/Test/html5/Lara_mirror.html

**Comment by Mugen87** [comment]
Yes, the `renderTarget` and the `clear` parameter were removed, see  #15571

It's necessary to adjust your code base in order to avoid the warnings. The [migration guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide#r101--r102) might be useful in this context.

**Comment by RemusMar** [comment]
> Yes, the `renderTarget` and the `clear` parameter were removed from `WebGLRenderer.render()`, see #15571

Hi Michael,

I don't use the renderTarget and forceClear parameters in my scripts.

**Comment by Mugen87** [comment]
Can you demonstrate the warnings with live example? It seems your linked demo still uses `R101`.

**Comment by RemusMar** [comment]
> Can you demonstrate the warnings with a live example? It seems your linked demo still uses `R101`.

http://necromanthus.com/Test/html5/Lara_mirror_102dev.html

**Comment by Mugen87** [comment]
You should upgrade `THREE.Mirror` to `THREE.Reflector`. The latest version from `dev` should produce no warnings, see:

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_mirror.html

**Comment by RemusMar** [comment]
> You should upgrade `THREE.Mirror` to `THREE.Reflector`. The latest version from `dev` should produce no warnings, see
> https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_mirror.html 

I tried Reflector a few days ago and I got the same warnings.
But I will investigate more this evening.
cheers

**Comment by RemusMar** [comment]
As I expected, the same console warnings with Reflector and 102dev:
http://necromanthus.com/Test/html5/Lara_reflector_102dev.html

**Comment by Mugen87** [comment]
You are not using the correct version of the file. Try it with this one:

https://github.com/mrdoob/three.js/blob/dev/examples/js/objects/Reflector.js

Your version of `Reflector` has the following code:
```js
renderer.render( scene, virtualCamera, renderTarget, true );
```
which is in `dev`:
```js
renderer.setRenderTarget( renderTarget );
renderer.clear();
renderer.render( scene, virtualCamera );
```

**Comment by RemusMar** [comment]
Good catch!
Now I have to find out why do I get console warnings in 102dev for this one:
http://necromanthus.com/Test/html5/testA_disco.html

**Comment by RemusMar** [comment]
For the 2nd sample I get another console warning (thousand times, every frame) in 102 dev:

WebGLRenderer: .getCurrentViewport() now requires a Vector4 as an argument

OMG ...
Folks, did you really improve anything with all these changes?

**Comment by RemusMar** [comment]
That .getCurrentViewport() change was present in **LensFlare.js** file only.
Anyway, the main question remain:  any improvements after these changes?

**Comment by mrdoob** [comment]
> Folks, did you really improve anything with all these changes?

Yes.

1. The `getCurrentViewport()` saves on garbage collection (no new `Vector4` created in every call).
2. The `renderTarget` parameter removal is simplifies how to know where is `WebGLRenderer` rendering to.

**Comment by mrdoob** [comment]
Thanks for testing new versions and letting us know what issues you find by the way. Super helpful!

**Comment by mrdoob** [comment]
Are all the issues with your tests solved?

**Comment by RemusMar** [comment]
> Are all the issues with your tests solved?

Yes Ricardo.
Except LensFlare and Mirror (Reflector), I didn't find other issues so far.
:thumbsup:
