### ISSUE TITLE
Warning after leaving VR mode

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#15852]
##### Description of the problem

On `webvr` examples, the console keeps outputting the following warning after leaving VR mode.

```
getFrameData must be called within a VRDisplay.requestAnimationFrame callback.
```

##### Browser + Headset

OculusGo + OculusBrowser(Chromium based).

##### Three.js version

- [x] Dev
- [ ] r101
- [ ] ...

**Comment by mrdoob** [comment]
Thanks!
