### ISSUE TITLE
GLTFExporter: support Geometry with Points

### ISSUE THREAD

**Issue by gouldingken** [mrdoob/three.js#15864]
"Geometry should have been covered by this block:

https://github.com/makc/three.js.fork/blob/fc31f5e634714c9811a8a13046419b369b8ee522/examples/js/exporters/GLTFExporter.js#L1030-L1033"

The previous issue was closed with this comment, but the issue persists and is easily replicated - at least for Point objects. The problem is that this code skips the case where "mesh.isPoints"

_Originally posted by @donmccurdy in https://github.com/mrdoob/three.js/pull/15203#issuecomment-435642084_

The issue can be replicated in the examples/misc_exporter_gltf.html file by replacing the BufferGeometry points with regular points.

```js
// ---------------------------------------------------------------------
// Points
// ---------------------------------------------------------------------
var pointGeometry = new THREE.Geometry();
for ( var i = 0; i < numPoints; i++ ) {
	pointGeometry.vertices.push(new THREE.Vector3(
		-50 + Math.random() * 100,
		Math.random() * 100,
		-50 + Math.random() * 100,
	));
}

...

var points = new THREE.Points( pointGeometry, pointsMaterial );
```

Saving the scene will result in the Uncaught TypeError: geometry.getAttribute is not a function

**Comment by donmccurdy** [comment]
Would you want to make a PR? 

Note, though, that use of Geometry is discouraged and in the future you will not be able to render it without first converting to `BufferGeometry`. If you cannot use `BufferGeometry` for some reason that we could fix, please let us know.

**Comment by jonra1993** [comment]
Hi @gouldingken did you were able to solve the issue. I have similar problem when I try to export a pointcloud.
![image](https://user-images.githubusercontent.com/23468720/71751319-32eb6780-2e49-11ea-9df4-138ef35d117b.png)
