### ISSUE TITLE
GLTFLoader: Custom geometry attributes

### ISSUE THREAD

**Issue by sneha-belkhale** [mrdoob/three.js#15868]
Is there a reason the GLTFLoader skips custom geometry attributes?

https://github.com/mrdoob/three.js/blob/327c9dde64fcaae88dc4a5d48c4397886ca7ada9/examples/js/loaders/GLTFLoader.js#L2444

**Comment by donmccurdy** [comment]
Just that we haven't had an example using them yet. Feel free to make a PR!

glTF uses the convention of uppercase attribute names, with custom attributes prefixed by an underscore, like `_TEMPERATURE`. I'd suggest that we keep the underscore but lowercase it to match threejs convention, e.g. `_temperature`.

**Comment by sneha-belkhale** [comment]
@donmccurdy 

Sounds good, I made a PR here #15878 

Thanks:)

**Comment by donmccurdy** [comment]
Fixed in #15878, thanks!
