### ISSUE TITLE
Broken code indentation in the documentation

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#15871]
##### Description of the problem

Some code indentations in the documentation look broken

For example

https://threejs.org/docs/#manual/en/introduction/Matrix-transformations

![image](https://user-images.githubusercontent.com/7637832/53645780-f5dca480-3c7c-11e9-92d4-b5dd40eaa210.png)

I'm not a CSS expert, but I guess it's caused by `white-space: pre-wrap;` in `docs/page.css`?

##### Three.js version

- [*] Dev
- [ ] r102
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This issue can easily solved by removing a parts of the indentation similar to other pages of the docs. AFAIK, the usage of `white-space` is necessary in order to prevent the code sections to appear in a single line.
