### ISSUE TITLE
Performance drop if camera is inside clipping area

### ISSUE THREAD

**Issue by LinoPhil** [mrdoob/three.js#15872]
##### Description of the problem

Moving the camera inside the scene area which is clipped using clippingPlanes leads to a big Performance drop.

Just zoom in ->  [JSFiddle Example: https://jsfiddle.net/p4hm9fg2/](https://jsfiddle.net/p4hm9fg2/)

With the cam outside the sphere I get around 60fps dropping to 20fps when moving the camera inside.
May be vary depending on your system.

##### Three.js version

- [ ] Dev
- [x] r102
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

got: Cpu i7-7820 with Intel HD 630

**Comment by WestLangley** [comment]
FWIW, I do not observe a performance drop on MacOS or iOS.

**Comment by WestLangley** [comment]
@LinoPhil What is the performance if you remove the clipping planes?

**Comment by LinoPhil** [comment]
@WestLangley with renderer.localClippingEnabled = false; i can fly through the whole sphere without any performance drop.

**Comment by mrdoob** [comment]
I do not observe a performance drop either. `Mesa DRI Intel(R) HD Graphics 615 (Kaby Lake GT2)` on a Pixelbook.

**Comment by looeee** [comment]
I'm getting the performance drop on my laptop. Steady 60fps outside the sphere dropping down to ~16fps when I zoom inside it. 

Not sure if I'm running on the integrated GPU (Intel HD530) or main (GTX 970m).

**Comment by RemusMar** [comment]
> Moving the camera inside the scene area which is clipped using clippingPlanes leads to a big Performance drop. 

I get 60 FPS in any camera position.
Tested with both integrated (HD 630) and discrete (GTX 1060) graphics.

**Comment by Mugen87** [comment]
No performance drop in my iMac (AMD Radeon R9 M295X).

**Comment by LinoPhil** [comment]
I tested with an gtx 960, the example szene is too easy for that. So I incresed to 400spheres and decreased their sizes -> [http://jsfiddle.net/vq2109ho/](http://jsfiddle.net/vq2109ho/)

In this szenario (gtx 960+complexer scene) I got some more strange things: 
- looking from down the sphere upward also drops the fps
- the fps drops from 55 to 20 if i set renderer.localClippingEnabled = false; even if the camera is outside of the sphere

**Comment by RemusMar** [comment]
> So I incresed to 400spheres and decreased their sizes -> http://jsfiddle.net/vq2109ho/ 

I get very low FPS values with or without clipping.
But what are you doing here is bad practice in any 3D engine.
Just try with Unreal or Unity and you'll get the same crappy results.

**Comment by LinoPhil** [comment]
@RemusMar you mean the example with the many spheres? Of course it is, its just an extreme test case showing some strange behavior. The main problem is the original test. @looeee could also reproduce it. You said you didnt get a drop with HD 630, did you test with chrome under windows?

**Comment by RemusMar** [comment]
> You said you didnt get a drop with HD 630, did you test with chrome under windows?

Steady 60 FPS in any camera position with or without clipping in the 1st sample.
Tested with HD 630 (and GTX 1060) in Windows with both Chrome and Firefox.

**Comment by LinoPhil** [comment]
Hmm, thats strange 

![out60](https://user-images.githubusercontent.com/25367101/53700458-e1bab380-3df2-11e9-9b6e-852a33b5d4c6.jpg)

![in27](https://user-images.githubusercontent.com/25367101/53700459-e5e6d100-3df2-11e9-9f50-bc4f18389a3a.jpg)

**Comment by RemusMar** [comment]
> Hmm, thats strange

Your variable FPS value indicates an issue with OS/drivers/browser.
On the other hand, WebGL is buggy on certain configs.

**Comment by looeee** [comment]
> Your variable FPS value indicates an issue with OS/drivers/browser.

This seems likely. I updated my nvidia drivers last week since I've been experiencing annoying screen flicker. 

I just did a complete clean reinstall (open windows in safe mode, uninstall drivers, reboot and then reinstall) and now I'm getting smooth 60 fps for all camera positions. 

Unfortunately it hasn't done anything about my screen flickering. About once every 20 seconds, ugh...

**Comment by Mugen87** [comment]
In any event, this issue is not related to `three.js`. 

@LinoPhil Please try the do the same as @looeee. If the problem does not go away, consider to report the problem at a different place (e.g. bug tracker of the browser vendor or the GPU vendor).
