### ISSUE TITLE
DataTexture not working as uniform for custom fragment shader

### ISSUE THREAD

**Issue by stur86** [mrdoob/three.js#15882]
I previously created a thread on Discourse for this thinking it may be my fault, but I'm convinced it's a bug now, because I can't find any reasonable explanation. Basically I'm creating a DataTexture procedurally, then passing it as a uniform to a ShaderMaterial with a very simple custom shader, yet what arrives seems to be only a black empty texture. I took care to use `needsUpdate` and all. The shader compiles properly and the texture contains the data it's supposed to. The same texture even works of passed as `alphaMap` to a different material.

Here is a live example of the problem:

https://codepen.io/stur86/pen/KEzvGX

For more info see the Discourse thread. This might be hardware-dependent:

https://discourse.threejs.org/t/cant-get-a-sampler2d-uniform-to-work-from-datatexture/6366/6

##### Three.js version

- [ ] Dev
- [x] r102
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
You can't use `Uint8ClampedArray` in this case, see https://github.com/KhronosGroup/WebGL/issues/1533

I have simplified your fiddle a bit since a custom shader material is not necessary in order to demonstrate the solution: Use `Uint8Array`. https://codepen.io/anon/pen/XGdEWb

**Comment by stur86** [comment]
> You can't use `Uint8ClampedArray` in this case, see [KhronosGroup/WebGL#1533](https://github.com/KhronosGroup/WebGL/issues/1533)
> 
> I have simplified your fiddle a bit since a custom shader material is not necessary in order to demonstrate the solution: Use `Uint8Array`. https://codepen.io/anon/pen/XGdEWb

Oh, that's interesting. I'm pretty sure in a different test I did it worked even with `Uint8ClampedArray` when used in a pre-existing material. But it was using it as an alphaMap, so I wonder what happened.
