### ISSUE TITLE
Cannot find variable: ImageBitmap 

### ISSUE THREAD

**Issue by ninth-mind** [mrdoob/three.js#15885]
##### Description of the problem
When loading a texture (or image) using `THREE.TextureLoader` on iOS Safari or iOS Chrome, I get the error "Cannot find variable ImageBitmap"

##### Hack Solution
Before loading the texture: 
`window.ImageBitmap = window.ImageBitmap || function () { return null }`

##### Three.js version

- [X] Dev
- [X] r102

##### Browser
- [ ] All of them
- [x] Chrome
- [ ] Firefox (did not test)
- [x] Safari
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

**Comment by mrdoob** [comment]
Is that a runtime error and the whole thing stops or a warning in the console?

**Comment by ninth-mind** [comment]
@mrdoob - Runtime ( i suppose)
I am using the Device Orientation Controls, and it only becomes a problem when I look at the object that is loading the texture...

**Comment by tonygentilcore** [comment]
Just bumped into this on v102 as well. v101 works fine.

**Comment by Mugen87** [comment]
Can you please share the line of code where the runtime error occurs? `THREE.TextureLoader` and `THREE.ImageLoader` do not use `ImageBitmap` at all. 

> Just bumped into this on v102 as well (it affects Safari on OSX too). v101 works fine.

Can you please share a live demo that demonstrates this issue? I've tested with Safari on macOS (10.14.3) with some examples but I was not able to reproduce.

**Comment by tonygentilcore** [comment]
Sure, here's a repro: https://codepen.io/tonygentilcore/pen/EMyKZM?editors=0010

The line `const texture = new THREE.TextureLoader().load(eyeData)` (where `eyeData` is `data:image/jpg;base64,<<ELIDED>>`) crashes safari with:
```
ReferenceError: Can't find variable: ImageBitmap
```

Again, chrome works fine and it works fine in Safari if the external script in settings is changed from `//cdnjs.cloudflare.com/ajax/libs/three.js/102/three.min.js` to `//cdnjs.cloudflare.com/ajax/libs/three.js/101/three.min.js`.

**Comment by WestLangley** [comment]
`ImageBitmap` has limited support according to https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap.

This regression appears to have been introduced in #15805.

**Comment by ninth-mind** [comment]
Yes!! Line 33 of https://github.com/mrdoob/three.js/pull/15805. That's the line I was trying to find to reference but couldn't.

**Comment by Mugen87** [comment]
It seems the PR change the order of tests in the related if statement for no reasons. This should be easy to fix.

**Comment by merwaaan** [comment]
@Mugen87 the order is actually important. It was changed so that types not available in web workers are evaluated last (HTMLImageElement, HTMLCanvasElement).

Reverting the order would break this in web worker. 

Would using typeof(Type) === "undefined" instead of instanceof fix both issues?

**Comment by Mugen87** [comment]
I see, but the current order breaks the code in Safari. I've added now the `typeof` statement to all test so the if `statement` works in all environments.
