### ISSUE TITLE
Equirectangular panorama demo poles pinching fix

### ISSUE THREAD

**Issue by jtomori** [mrdoob/three.js#15892]
##### Description of the problem
Example for [Equirectangular panorama demo](https://threejs.org/examples/webgl_panorama_equirectangular.html) has visible pinching on the bottom pole.

It can be fixed by setting `minFilter = THREE.LinearFilter;` on panorama texture.

[Example fix](https://jsfiddle.net/sLb1pmo9/)

I would suggest updating this example so it produces correct results.

##### Three.js version

- [ ] Dev
- [x] r102
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Fixed. Thanks!

**Comment by WestLangley** [comment]
So, mipmaps are now being generated and not used?

Is the mipmap/pinching-tradeoff worth it?

**Comment by mrdoob** [comment]
Maybe for this specific case it is?

**Comment by WestLangley** [comment]
I don't think removing the mips is a good idea -- users copy these examples.

I would revert https://github.com/mrdoob/three.js/commit/9957632e709855c09fe8662ff3c1d1467dd6b523, and instead, reduce the tessellation of the sphere. As is, it is overkill anyway.

```js
var geometry = new THREE.SphereBufferGeometry( 500, 32, 16 );
```

**Comment by mrdoob** [comment]
We could also add a comment in that line documenting the reason?

**Comment by WestLangley** [comment]
I do not care about the pinching. I never noticed it.

I do not think we should remove the mipmapping, however.

**Comment by WestLangley** [comment]
The purpose of linear filtering is not to reduce pinching. I would not use it for that purpose.

I would use the mipmaps that are being generated.

**Comment by Deboracgs** [comment]
texture.anisotropy = 16; works fine!
