### ISSUE TITLE
Missing surfaces - gltf loader.

### ISSUE THREAD

**Issue by tiancaipipi110** [mrdoob/three.js#15912]
This model is missing surfaces immediately after drop it to the viewer https://gltf-viewer.donmccurdy.com/   The model is good in Blender.
Model link:  https://drive.google.com/file/d/1YdJUy7R6V2c9_6YeHukKlz3zIZRyfikE/view?usp=sharing

**Comment by Mugen87** [comment]
Please file an issue at the respective project site of the exporter, instead. The following [gltf-viewer](https://gltf-viewer.donmccurdy.com/) and the [Babylon.js Sandbox](https://sandbox.babylonjs.com/) reports 121 errors with your asset.

**Comment by tiancaipipi110** [comment]
What about this asset, same issue with missing surface. I've tried solidify in Blender, still no help.
[GLTF.zip](https://github.com/mrdoob/three.js/files/2936453/GLTF.zip)

**Comment by Mugen87** [comment]
Please redirect you help requests to the [fourm](https://discourse.threejs.org/) or stackoverflow.

**Comment by donmccurdy** [comment]
^You'll need to share the original `.blend` file in whatever place you post, as well.
