### ISSUE TITLE
Problems with using Mesh.material as array

### ISSUE THREAD

**Issue by zhuravlev12** [mrdoob/three.js#15913]
##### Description of the problem

`var geometry = new THREE.BoxBufferGeometry( 1, 1, 1 );`
`var material = new THREE.MeshBasicMaterial( { color: 0xffff00 } );`
`var mesh = new THREE.Mesh( geometry, [material] );`
`var materialProperties = properties.get( material );`

materialProperties is empty object. Is it right behavior?

Callstack of bug:
`Uncaught TypeError: Cannot read property 'getUniforms' of undefined`
`    at setProgram (three.js:24111)`
`    at WebGLRenderer.renderBufferDirect (three.js:23123)`
`    at renderObject (three.js:23845)`
`    at renderObjects (three.js:23815)`
`    at WebGLRenderer.render (three.js:23608)`

How can I render multimaterial meshes by WebGLRenderer?

##### Three.js version

- [ ] Dev
- [x] r102
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Please redirect your question to the three.js [forum](https://discourse.threejs.org).
