### ISSUE TITLE
Memory increase when using wasm decoder in DRACO Loader

### ISSUE THREAD

**Issue by scarletsky** [mrdoob/three.js#15928]
##### Description of the problem

When using wasm decoder in DRACO Loader, the memory will increase even if you refresh page. And the memory will be freed when you close the tab.

The `webgl_loader_draco` example can reproduce this issue, just comment the following line, and it will use wasm decoder.

```diff
diff --git a/examples/webgl_loader_draco.html b/examples/webgl_loader_draco.html
index 1eaf08f2e..46c321f50 100644
--- a/examples/webgl_loader_draco.html
+++ b/examples/webgl_loader_draco.html
@@ -47,7 +47,7 @@

                // Configure and create Draco decoder.
                THREE.DRACOLoader.setDecoderPath( 'js/libs/draco/' );
-               THREE.DRACOLoader.setDecoderConfig( { type: 'js' } );
+               // THREE.DRACOLoader.setDecoderConfig( { type: 'js' } );
                var dracoLoader = new THREE.DRACOLoader();
                init();
                animate();
```

And then take heap snapshot:

![image](https://user-images.githubusercontent.com/2386165/54015675-5c9d1900-41bb-11e9-9117-53b7be82e38a.png)

##### Three.js version

- [ ] Dev
- [x] r102
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I'm able to reproduce with Chrome 72.0.3626.121 on macOS. And yes, the memory does not increase when using the JavaScript version of the decoder. 

However, I'm not able to reproduce the issue with Firefox 65.0.1.

![image](https://user-images.githubusercontent.com/12612165/54031445-09bd6480-41af-11e9-81dc-da5193722ce1.png)

This could indicate a browser issue. Can you also make a test with Firefox?

**Comment by scarletsky** [comment]
Yes, Firefox does not have this issue.

**Comment by Mugen87** [comment]
Do you mind filing a bug at the Chromium issue tracker?

https://bugs.chromium.org/p/chromium/issues/list

If this is a browser bug, there is nothing we can do here.

**Comment by donmccurdy** [comment]
Does memory usage return to normal if you call `THREE.DRACOLoader.releaseDecoderModule()`? Note that after doing so, you won't be able to use the module without reloading the page (https://github.com/google/draco/issues/349).

**Comment by Mugen87** [comment]
The example already does this after the bunny has loaded.

https://github.com/mrdoob/three.js/blob/579e8d256f5cbd5eae737c42289bd21264d63269/examples/webgl_loader_draco.html#L96

**Comment by scarletsky** [comment]
I have opened an issue in https://bugs.chromium.org/p/chromium/issues/detail?id=940067

**Comment by Mugen87** [comment]
As mentioned at the issue at bugs.chromium, the browser's task manager does not show the mentioned increase in memory. In any event, this is not a `three.js` issue so please continue the discussion at the Chromium bug tracker.

**Comment by VeinSyct** [comment]
This is a Chrome bug, Opera and Firefox doesn't seem to have this issue.
