### ISSUE TITLE
three.js.org

### ISSUE THREAD

**Issue by shinenelson** [mrdoob/three.js#15925]
[js.org](js.org) has a [DNS service](dns.js.org) that provides [js.org](js.org) sub-domains  that can point to websites hosted on github. I think we could move to three.js.org.

The only change that needs to be done from our part is to change the [CNAME file](https://github.com/mrdoob/three.js/blob/gh-pages/CNAME) with the new sub-domain.

**Why would you want to change the existing domain?**
I think having a [js.org](js.org) sub-domain could show a better affiliation with the javascript community.
Also, the current existing domain is very similar to the proposed domain as well.

I can create a pull request for changing the [CNAME file](https://github.com/mrdoob/three.js/blob/gh-pages/CNAME) with the custom sub-domain as well the pull request to [js-org/dns.js.org](https://github.com/js-org/dns.js.org) to assign the sub-domain to [three.js](https://github.com/mrdoob/three.js).

I'm asking approval / permission to do these :point_up_2: for [three.js](https://github.com/mrdoob/three.js).

**Comment by Mugen87** [comment]
TBH, I find `https://three.js.org` confusing. Other projects also don't do this e.g.:

https://reactjs.org/
https://angularjs.org/
https://www.babylonjs.com/

 Do you see the similarity to https://threejs.org?

**Comment by shinenelson** [comment]
This idea was [proposed to React](https://github.com/facebook/react/issues/11874) and they didn't want it. AngularJS' hosting provider is probably not compatible to work with the [js.org](https://js.org) service.

However, since BabylonJS is hosted on [netlify](https://netlify.com) which again could in-turn be used with [js.org](https://js.org) as well. I'm going to try and suggest the [js.org](https://js.org) sub-domain to them as well. Let's see how that goes.

Of course, the domain name similarity exists with the mentioned services, but then there are other services that prefer the [js.org](https://js.org) sub-domain as well. Some examples : 
* [browserless.js.org](https://browserless.js.org)
* [canvas.js.org](https://canvas.js.org)
* [cargo.js.org](https://cargo.js.org)
* [cnc.js.org](https://cnc.js.org)
* [csv.js.org](https://csv.js.org)
* [cycle.js.org](https://cycle.js.org)
* [impress.js.org](https://impress.js.org)
* [mobx.js.org](https://mobx.js.org)
* [redux.js.org](https://redux.js.org)
* [telegraf.js.org](https://telegraf.js.org)

**Comment by looeee** [comment]
I think this is a bad idea for a couple of reasons:

1. It's completely unnecessary. We already have a perfectly fine, well known domain. If it's not broken, don't fix it
2. It's confusing, too similar to the current domain

Aside from that, do you know what kind of effect changes like this to an established domain will have on SEO?

**Comment by arodic** [comment]
> I think having a js.org sub-domain could show a better affiliation with the javascript community.

How so?

**Comment by Mugen87** [comment]
From my point fo view, this is complete nonsense nobody needs.

**Comment by RemusMar** [comment]
> I think we could move to three.js.org.

To switch from a (owned) domain to a SUB-domain (owned by someone else) is a bad idea from any point of view.
Not to mention that **threejs.org** is a nice domain name ...

**Comment by shinenelson** [comment]
Alright. I wouldn't argue further. Your arguments are all valid. I just thought that I should propose the idea and see how you'd like it. I'll close this issue now.

**Comment by mrdoob** [comment]
Thanks for the suggestion. Unfortunately this is likely to break many things and will cause confusion with existing subdomains such as http://discourse.threejs.org. This goes into the category of "if it's not broken don't fix it" 🙂
