### ISSUE TITLE
Suggestion: Consider removing src/loaders/Loader.js

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#15935]
##### Description of the problem

`Loader` document mentions 

> Base class for implementing loaders.

https://threejs.org/docs/#api/en/loaders/Loader

But with #15933, no loader will inherit `Loader`. 

And Some loaders use `Loader.Handlers`. We may be able to move `Handlers` into `LoaderUtils` or somewhere. `CTMLoader` and `LegacyJSONLoader` call `Loader.createMaterial()/.initMaterials()`, we also may be able to move these methods somewhere.

We may be able to remove `Loader`.

##### Three.js version

- [x] Dev
- [ ] r102
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
All loaders should have the same API as much as possible, and if a common base class helps with that then I'd want to keep it. However, nothing in `THREE.Loader` is currently being used that way, so I'm fine with removing it.

> And Some loaders use Loader.Handlers. We may be able to move Handlers into LoaderUtils or somewhere...

I would suggest that the `LoadingManager` class be used here.

**Comment by Mugen87** [comment]
> I would suggest that the LoadingManager class be used here.

I agree. I think adding `LoadingManager.addHandler()`/`LoadingManager.removeHandler()` and deprecate `Loader.Handlers` would be a much nicer API. 

In this context, we should also refactor the following code section:

https://github.com/mrdoob/three.js/blob/09e1fde724b89e2de4d5e774de27f137ab13d97c/examples/js/loaders/FBXLoader.js#L298-L305

Handlers should added by the app layer, not by the loader itself.

**Comment by Mugen87** [comment]
> CTMLoader and LegacyJSONLoader call Loader.createMaterial()/.initMaterials(), we also may be able to move these methods somewhere.

Since `CTMLoader` is now gone, only `LegacyJSONLoader` depends on `Loader.createMaterial()/.initMaterials()`. We could now copy over both methods from `Loader` like done in #16030 without creating duplicated code anymore.

**Comment by Mugen87** [comment]
Closing. As mentioned here, we remove all legacy code from `Loader` and use it instead as a base class for all other loaders.

https://github.com/mrdoob/three.js/pull/17293#issuecomment-523218182
