### ISSUE TITLE
WebGPU

### ISSUE THREAD

**Issue by NiNJAD3vel0per** [mrdoob/three.js#15936]
I am curious that Three.js has a plan to support WebGPU. Is it possible?

**Comment by TimvanScherpenzeel** [comment]
Theoretically in the far future but as you may know the WebGPU group is still actively talking / aligning on forming firsts proposal / spec / drafts. It will be years before we will have a complete spec and working standardised implementations.

That said I would recommend getting involved / following in the WebGPU development here:  https://github.com/gpuweb/gpuweb/wiki and https://www.w3.org/community/gpu/

If WebGPU turns out to be as powerful as we all hope it to be libraries like Three.js will likely have to be rewritten from scratch in order to take full advantage of it.

**Comment by NiNJAD3vel0per** [comment]
@TimvanScherpenzeel  
Yes, I agree. I will be the far future. 
 Is it impossible to add WebGPU renderer in three.js without rewriting the core from scratch? should we have to rewritten the whole engine(API) in threejs from scratch? I think even if WebGPU comes out, it would be very likely to coexist together (WebGL/WebGPU) for a while. I don't think WebGPU would kill all WebGL ecosystem. maybe or not..

**Comment by donmccurdy** [comment]
ThreeJS has many different renderers already – WebGLRenderer, WebGL2Renderer, CSS3DRenderer, SVGRenderer... WebGPU can be handled similarly, when the API is ready. Deeper changes to the library are possible over time, too.

Closing this issue for now, although I'm excited for these next-gen APIs as well. :)

**Comment by NiNJAD3vel0per** [comment]
@donmccurdy  
Indeed.. 
According to the WebGPU proposal, They mentioned about Three.js deverlopers as one of their main target audiences. 
[https://gpuweb.github.io/admin/cg-charter.html](url)
> JavaScript framework developers who are building GPU libraries, intended to be used in Web content, but providing a higher-level API and hiding much of the low-level graphics and compute details from their users. For example, three.js.

**Comment by mrdoob** [comment]
> My Question is that They use another shader language called WHLSL.

"We'll cross that bridge when we come to it"

**Comment by mcrawshaw** [comment]
Was announced @ Google I/O with experimental support in Chrome Canary for OSX available now:
https://www.youtube.com/watch?v=K2JzIUIHIhc

**Comment by perspectly** [comment]
Babylon has announced full support for it when it comes out. Check it out here: https://youtu.be/K2JzIUIHIhc?t=1077

**Comment by MichelDiz** [comment]
Not sure why close this as it was mentioned the potential support. By logic, we left issues open to "track" it. If you close it, you just forget about... unless there is other issue to track it.

**Comment by mrdoob** [comment]
I can assure you we won't forget about it... 😁

**Comment by MichelDiz** [comment]
But I'm not a maintainer. Personally, I will follow the first framework that adopts webgpu. And the point isn't me. Is the message you guys give closing this. It is like "Cool thing, sure thing, but I don't care. It can hold there in the limbo".

**Comment by donmccurdy** [comment]
@MichelDiz this issue was opened to ask if we plan to support WebGPU. The question has been answered: we absolutely do plan to support WebGPU. It is probably too early now to work on that, but new issues will be opened when we are ready to discuss this.

**Comment by DVLP** [comment]
@TimvanScherpenzeel certain parts that are abstracted away from the users will have to be rewritten but suggesting the whole thing will have to be "rewritten from scratch" is a massive overstatement. Buffer geometries will have the same format. Just like WebGL, WebGPU is also based on shaders GLSL -> WHLSL. It seems like glTF format that has become WebGL standard will also be WebGPU standard. All most-used Three.js APIs will stay 99% unchanged while the new WebGPU renderer will be under the hood and hopefully will bring large performance boost and unlock a potential of rendering big scenes at high fps.

**Comment by sinokgr** [comment]
Hi all,
many thanks for the updates on this one!
I just wanted to share my perspective on features like this. In our case, we don't always use WebGL for consumer applications. We do have WebGL experiences that we visualise very big datasets where the assets are ~1GB and served locally on fixed hardware where we can control the browsers and its flags to enable WebGPU. So even if in experimental mode, we could definitely love to have support for that. I understand that we are the minority, but I just wanted to add this view in the conversation.

**Comment by mrdoob** [comment]
@sinokgr How does WebGPU help on displaying 1GB assets? As far as I understand the data structures for geometry data are the same as WebGL.

**Comment by sinokgr** [comment]
thanks for the reply @mrdoob . To be 100% honest, I won't claim I understand enough the differences and the information I find online is very vague (according to my research anyway). The main feeling I'm getting is from stuff I read like the last message from @DVLP  that you liked, 
> will bring large performance boost and unlock a potential of rendering big scenes at high fps.
that make me think that we're going to see at least some improvements. This might be, how fast for example these assets will load, better fps maybe? I'm not sure.

**Comment by DVLP** [comment]
Initial loading to the regular memory will stay the same but the entire GPU API will be quicker so from the moment where GPU is involved it should be faster. Here's how I see where the performance boost will be coming from:
1. Load model file to the browser - same speed
2. Parse model and load geometry to an array buffer - same speed
3. Load GPU programs - faster
4. Load textures - initially the same speed but faster when handing over to the GPU
5. Transfer geometry to the GPU - faster
6. Make a series of draw calls to render a frame - faster

**Comment by sinokgr** [comment]
Many thanks for the explanation @DVLP . Points 5 and 6 sound very interesting to me since we have thousands of objects with a lot of materials.

**Comment by DVLP** [comment]
It may be a long time until WebGPU is widely adapted. Until then you can speed up the whole thing using mesh instancing
https://threejs.org/docs/#api/en/objects/InstancedMesh

**Comment by sinokgr** [comment]
I'm afraid we can't use instancing, all objects are unique @DVLP

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Nick Moutafis <notifications@github.com>
发送时间：2020-05-15 01:48
主题：Re: [mrdoob/three.js] Will there be WebGPU based renderer? (#15936)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

I'm afraid we can't use instancing, all objects are unique @DVLP

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/pull/20254
