### ISSUE TITLE
i can not find PCDLoader in THREE

### ISSUE THREAD

**Issue by yokyj** [mrdoob/three.js#15944]
export * from './loaders/AnimationLoader';
export * from './loaders/CompressedTextureLoader';
export * from './loaders/DataTextureLoader';
export * from './loaders/CubeTextureLoader';
export * from './loaders/TextureLoader';
export * from './loaders/ObjectLoader';
export * from './loaders/MaterialLoader';
export * from './loaders/BufferGeometryLoader';
export * from './loaders/LoadingManager';
export * from './loaders/ImageLoader';
export * from './loaders/ImageBitmapLoader';
export * from './loaders/FontLoader';
export * from './loaders/FileLoader';
export * from './loaders/Loader';
export * from './loaders/LoaderUtils';
export * from './loaders/Cache';
export * from './loaders/AudioLoader';

these are all the loaders exported in the Three.d.ts

##### Three.js version

- [ ] Dev
- [ ] r102
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
It's not part of the core, so you'll need to include it separately.

You can find it here: 
https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/PCDLoader.js

There's an example of how to use it here:
https://threejs.org/examples/#webgl_loader_pcd

If you need more help, please ask over on the [forum](https://discourse.threejs.org).

**Comment by yokyj** [comment]
but i am using it in a react project,what should i install by npm or yarn

**Comment by Mugen87** [comment]
If there is no existing package at npm, you have to convert `PCDLoader` to a module by yourself. That's the better approach anyway since you ensure to use the latest version of `PCDLoader`.
