### ISSUE TITLE
GLTFLoader: Incorrect quaternion cubicspline interpolation

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#15950]
From https://github.com/donmccurdy/three-gltf-viewer/issues/138 –

> When playing the animation of this model, the mesh gets squished.
> Expected behavior: Skinned rotation animation around the up-axis.
> Actual behavior: The model gets horizontally scaled in addition to rotation.

[rigged-box.zip](https://github.com/mrdoob/three.js/files/2953418/rigged-box.zip)

The model animates incorrectly in https://gltf-viewer.donmccurdy.com/, but correctly in http://sandbox.babylonjs.com/. Looking at the interpolation function...

https://github.com/mrdoob/three.js/blob/27811881f61e647ae2b8b009e3032f62739c2c25/examples/js/loaders/GLTFLoader.js#L1058-L1067

... it seems suspicious that we're always writing into indices 0-3 on the result buffer, rather than using `i1` as done in QuaternionLinearInterpolant:

https://github.com/mrdoob/three.js/blob/eaa4f9dc511d3091443069db0f9c74093e29f943/src/math/interpolants/QuaternionLinearInterpolant.js#L30-L34

three.js r101

**Comment by takahirox** [comment]
That `QuaternionLinearInterpolant` also writes into 0-3. The second argument of `Quaternion.slerpFlat` is the offset to write into result buffer.

https://github.com/mrdoob/three.js/blob/eaa4f9dc511d3091443069db0f9c74093e29f943/src/math/Quaternion.js#L28-L88

**Comment by donmccurdy** [comment]
Hm I see. In that case I don't know what's causing this. 🤔

**Comment by donmccurdy** [comment]
@UX3D-eckerlein are we sure these cubicspline tangents are correct? I'd expect at least the first and last to be `0 0 0 0` but instead see:

<img width="326" alt="Screen Shot 2019-03-15 at 5 27 40 PM" src="https://user-images.githubusercontent.com/1848368/54468238-d0a16900-4747-11e9-8282-419e79075fb4.png">

Maybe related to https://github.com/KhronosGroup/glTF-Blender-IO/issues/361?

**Comment by UX3D-eckerlein** [comment]
This has been fixed in the Blender-IO Repository:
https://github.com/KhronosGroup/glTF-Blender-IO/commit/770ed2f35f4f9a033815e66e4ea585ce7a9606ef

The issue was that the exporter wrote incorrect tangent and quaternion data when animating quaternions using cubic splines. The problem was solved by simply baking any such animation.

**Comment by donmccurdy** [comment]
Thanks! 

Aside from situations where the rotation is >180º from one keyframe to the next, do you know if there's a reason quaternion cubicspline animation would technically need to be baked? Either way, glad there's a workaround. :)
