### ISSUE TITLE
Incorrect Typescript definitions for InstancedBufferAttribute

### ISSUE THREAD

**Issue by nsunderland-cognite** [mrdoob/three.js#15956]
##### Description of the problem

https://github.com/mrdoob/three.js/blob/bee2b8ace8be7074cf0a34e3c9653eedcb9c512f/src/core/InstancedBufferAttribute.d.ts#L38-L43

This is inconsistent with the actual signature:

https://github.com/mrdoob/three.js/blob/bee2b8ace8be7074cf0a34e3c9653eedcb9c512f/src/core/InstancedBufferAttribute.js#L7

##### Three.js version

- [x] Dev
- [x] r102

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
Would you like to do a PR with the fix?

**Comment by nsunderland-cognite** [comment]
Can do, coming up soon
