### ISSUE TITLE
Ability to edit 3D mesh

### ISSUE THREAD

**Issue by brylie** [mrdoob/three.js#15959]
It would be useful to perform basic mesh editing tasks from the ThreeJS Editor.

When working with basic primitives, it would be useful to modify the geometry, such as:
- edit vertex
- edit edge
- sub-divide face
- loop cut

These basic operations could serve as the foundation for further mesh-editing features.

**Comment by Mugen87** [comment]
This was discussed before here: https://github.com/mrdoob/three.js/issues/10642

It was decided to consider the editor as a pure scene editor similar to other engines.
