### ISSUE TITLE
[Feature Request] Adjust Horizontal FOV

### ISSUE THREAD

**Issue by ClickSimply** [mrdoob/three.js#15968]
Describe the bug or feature request in detail.

ThreeJS field of view option on the camera only adjusts vertical field of view, allow the horizontal field of view to be adjusted as well or create a new camera that has an adjustable horizontal field of view.

##### Three.js version
- [x] r102

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by WestLangley** [comment]
[This SO answer](https://stackoverflow.com/a/26665260/1461008) provides the formula that relates the horizontal and vertical FOVs.

```js
hFOV = 2 * Math.atan( Math.tan( camera.fov * Math.PI / 180 / 2 ) * camera.aspect ) * 180 / Math.PI; // degrees
```
You can use that to solve for the vertical FOV as a function of the horizontal FOV.

**Comment by ClickSimply** [comment]
Yes, that’s how you calculate the horizontal FOV, however Id like to **adjust** it indipendent of the vertical fov.

**Comment by peteroupc** [comment]
> 
> 
> Yes, that’s how you calculate the horizontal FOV, however Id like to **adjust** it independent of the vertical FOV.

That involves solving for the aspect ratio (width to height ratio), given the vertical and horizontal fields of view.

**Comment by WestLangley** [comment]
Of the three quantities, vertical FOV, horizontal FOV, and aspect ratio, you can control two of them.

In three.js, a perspective camera is parameterized by its vertical FOV and aspect ratio. If you want to compute either of those two values from the other (plus horizontal FOV), you will have to do that at the application layer.

For example:
```js
const hFOV = 50; // desired horizontal fov, in degrees

camera.fov = Math.atan( Math.tan( hFOV * Math.PI / 360 ) / camera.aspect ) * 360 / Math.PI; // degrees

camera.updateProjectionMatrix();
```
