### ISSUE TITLE
Viewing mesh at a very hard angle causes texture to stretch

### ISSUE THREAD

**Issue by Owlzy** [mrdoob/three.js#15962]
##### Description of the problem

When viewing a mesh at a very hard angle the texture stretches.  In the screenshot I made a cube to test, but the real project uses many hexagons, which is how we spotted the issue due to the sloping edges of the hexagons being at a smaller angle relative to the camera.  In the actual scene its very noticeable.

I made the simple test cube and mapped it myself, so I'm confident it wasn't artist error.  For now we will make them a separate mesh in order to maintain a hard edge as the lines go into the distance, but my assumption is that this is an issue as its not something I've encountered outside of threejs.  Please correct me if I am wrong on this and its perhaps configuration or otherwise.  

https://pasteboard.co/I5eDZbT.png

##### Three.js version

- [ ] Dev
- [x ] r102
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
You can solve this using `anisotropy`:
https://threejs.org/examples/#webgl_materials_texture_anisotropy
