### ISSUE TITLE
[Feature request] Accessible library of reusable shader functions

### ISSUE THREAD

**Issue by EliasHasle** [mrdoob/three.js#15970]
OK, so now there is a ShaderLib with complete shaders, and there is ShaderChunk, which is some of a mess of segments that are reused. What I would be interested in seeing, would be something like ShaderFunctions, a library of reusable functions, such as noise, discretization, sigmoid, convolutions etc. It could have a nice docs page too. I would gladly contribute a few functions with doc, if you are interested.

Usage would be with `#include`, so this could all be part of ShaderChunk, but the ShaderChunk library is so messy. Maybe functions could reside in a subfolder of ShaderChunk, after #14348.

**Comment by Mugen87** [comment]
It seems a node based approach is similar to what you are looking for. Have you already checked out how `NodeMaterial` works? There are already classes like [NoiseNode](https://github.com/mrdoob/three.js/blob/dev/examples/js/nodes/procedural/NoiseNode.js) which represents are reusable function node that can be part of a node material definitions. `NodeMaterial` is still part of the examples and undocumented/unstable but it might have a more important role in the future. Have a look a the examples and the respective source code.

https://threejs.org/examples/?q=node

**Comment by EliasHasle** [comment]
Thanks. Hmm, I guess I should look closer into NodeMaterial. At first sight, it seems like a sort of high-level way to define composite materials. Useful, I guess, but what I suggested would be a low-level alternative that keeps the material definition within the shader. Is there a reason these approaches could not coexist?
