### ISSUE TITLE
FBXLoader inside three.module.js

### ISSUE THREAD

**Issue by sonyoungrack** [mrdoob/three.js#15971]
Hi, I'm Korean Developer!

I am using "three.module.js" to use the grammar 'es6'.

Problem is, I want to use the FBXLoader, but I don't know how to use it.

In an HTML file
```
<script src = "Three.js">
<script src = "FBXLoader.js">
```
I don't want to add this.

Is there any way you can use it only by import?

I am Korean, and I am using a translator, so the translation may be unstable. Please understand.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help request.
