### ISSUE TITLE
Data structures are not garbage collected on dispose

### ISSUE THREAD

**Issue by revyTH** [mrdoob/three.js#15972]
##### Description of the problem

see https://discourse.threejs.org/t/dispose-things-correctly-in-three-js/6534

I am experiencing problems on correctly disposing a scene and all the associated data structures.

In my test I followed these steps (using Chrome devtools):

1. Start from an empty scene, force garbage collection and taking memory snapshot.
2. Adding meshes to the scene with the "ADD MESHES" button (100 meshes added per click), force garbage colelction and take memory snapshot.
3. Dispose scene using the "DISPOSE" button, wait some seconds, force garbage collection and taking memory snapshot.

##### RESULT (comparison between snapshot 3 and snapshot 1):

![snapshots_3_1](https://user-images.githubusercontent.com/26633801/54348321-14fa0f80-4649-11e9-954a-b494ff069ebd.png)

As you can see most of the three.js data structures are kept in memory and not garbage collected.

##### EXPECTED BEHAVIOUR

All the three.js data structures should be garbage collected, giving a memory state comparable to the initial state.

This is the live plunker:

[https://plnkr.co/edit/pmeB0t3tEbOAaKdebhbr](https://plnkr.co/edit/pmeB0t3tEbOAaKdebhbr)

##### Three.js version

- [x] r102

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
`dispose()` methods deallocates memory from the GPU (and not from the CPU).

**Comment by Mugen87** [comment]
Closing. The main issue was that the test program of the OP had multiple `console.log` statements. When objects are logged to the console, they are not GC collected even if a program has no references to it anymore. We had once a similar issue right here: #11378

Removing the `console.log` statements resolved the issue, see https://discourse.threejs.org/t/dispose-things-correctly-in-three-js/6534/14?u=mugen87
