### ISSUE TITLE
Add Degrees mode

### ISSUE THREAD

**Issue by 1337Franq** [mrdoob/three.js#15978]
Hi,
If you are an avverage person like me you propably use degrees instead of radians.
For a person like me who has never used radians before its pretty confusing to use them.
So it would be great to have a function like in p5 angleMode(DEGREES) so it would be nice to see 
THREE.angle(DEGREES)

**Comment by looeee** [comment]
There's a helper utility for converting called [degToRad](https://threejs.org/docs/#api/en/math/Math.degToRad)
