### ISSUE TITLE
Cloning Line with LineDashedMaterial returns a Line with LineBasicMaterial

### ISSUE THREAD

**Issue by soadzoor** [mrdoob/three.js#15974]
##### Description of the problem

Given this code:
```
const material = new THREE.LineDashedMaterial({
	color: 0xff0000,
	linewidth: 1,
	scale: 1,
	dashSize: 8,
	gapSize: 4,
});	
const geometry = new THREE.BufferGeometry();
const vertices = new Float32Array([
	-100.0, 0.0,  0.0,
	 100.0, 0.0,  0.0
]);

geometry.addAttribute( 'position', new THREE.BufferAttribute(vertices, 3));
				
const line = new THREE.Line(geometry, material);
line.computeLineDistances();
				
const line2 = line.clone();
line2.position.setY(-20);
```

I'd assume that `line` and `line2` should look the same. However, they don't. See the screenshot below:
![Capture2](https://user-images.githubusercontent.com/10392261/54354091-0e25c980-4656-11e9-810c-268409fe5c71.PNG)

I investigated a little bit, and it turned out that during the cloning process, Lines get `LineBasicMaterial` by default, even when the original material was `LineDashedMaterial`:
![Capture](https://user-images.githubusercontent.com/10392261/54354178-488f6680-4656-11e9-823d-a61905e5cdd4.PNG)

I tried to create a demo, as clean and short as possible:

 * [demo.zip](https://github.com/mrdoob/three.js/files/2966166/demo.zip)

Live example:
* [jsfiddle](https://jsfiddle.net/soadzoor/4xcq7auf/1/)

I'll try to look for a nice solution myself, but any advice / feedback is welcome, as always. As a workaround I can do something like:
```line2.material = line.material;```
But I'd rather have it fixed as it should be.

##### Three.js version

- [x] r102

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Related: #15064.

For convenience, updated [fiddle](https://jsfiddle.net/k6oyz9bd/) with change proposed in #15064.

**Comment by mrdoob** [comment]
Also related #15974.

**Comment by WestLangley** [comment]
@mrdoob what?   :)

**Comment by mrdoob** [comment]
@WestLangley Sorry, I meant... Also related #15062
