### ISSUE TITLE
Editor: add FPS counter

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#16007]
It would be useful for the editor to have an FPS counter - probably the best place for this would be in the lower left of the viewport along above the object, vertices, triangles count. 

Alternatively, stats.js could be added, perhaps in the viewport top left. That would have the advantage of showing memory data as well. In that case it should probably be disabled by default since it's a bit more visually distracting. 

@Temdog007 what do you think?

**Comment by Temdog007** [comment]
I think using stats.js would be the easiest and most logical way to do this.

**Comment by mrdoob** [comment]
I would just add `ms` to `ViewportInfo` and add simple code to calculate how long rendering the frame took.
