### ISSUE TITLE
Option blending does not exist for Lensflare

### ISSUE THREAD

**Issue by Cosmoledo** [mrdoob/three.js#16001]
##### Three.js version

- [x] r102

##### Browser

- [x] All of them

##### OS

- [x] All of them

##### Problem

As written in the docs of Lensflare (https://threejs.org/docs/#examples/objects/Lensflare) there should be an option at the LensflareElement to change the blending-mode.
But this option is never read in the sourcecode (https://github.com/mrdoob/three.js/blob/dev/examples/js/objects/Lensflare.js) in Line 275

**Comment by WestLangley** [comment]
Thanks. That was changed in #13280.

Presumably, the docs need to be updated to match the code.
