### ISSUE TITLE
Near-Plane Clipping Problem when using external import model as a mirror(oblique faces)

### ISSUE THREAD

**Issue by majinge78467** [mrdoob/three.js#16013]
https://github.com/mrdoob/three.js/blob/a46700a4261fe20f03418bea9417e59898a23f50/examples/js/objects/Reflector.js#L83
https://github.com/mrdoob/three.js/blob/a46700a4261fe20f03418bea9417e59898a23f50/examples/js/objects/Reflector.js#L131
We can know from the source code,mirrors rotation info which from mirror's worldmatrix  will be used to construct the Near cut face in cameras projectMatrix.
I met difficulty when I use an external model in FBX format，whose mirror mesh is a oblique plane with oblique normal,but it's worldMatrix rotation is (0,0,0)，and the woodybracket behind the mirror can not be correctly culled.
What can I do to correct?

**Comment by WestLangley** [comment]
Please redirect your question to the three.js [forum](https://discourse.threejs.org).
