### ISSUE TITLE
Safari Canvas inspector shows drawElements being called twice

### ISSUE THREAD

**Issue by dbismut** [mrdoob/three.js#16028]
##### Description of the problem

As I was trying to work on performance for another project, Safari Canvas Inspector seemed to show the canvas being rendered _twice_ per frame. I put together a very simple example showing just an image and run it through Safari Canvas Inspector once again and stumbled upon the same issue, with `drawElements` and `clear` methods being called twice per frame.

![ezgif com-optimize](https://user-images.githubusercontent.com/5003380/54744518-7bda7400-4bc7-11e9-9e39-6e283c92e6df.gif)

Codesandbox link of the simplified example is here: https://j3o32qpxpy.codesandbox.io

I've tried to implement a clumsy count log of `drawElements` (commented out in the Codesandbox link) and it only logged one call per frame, so I'm thinking that this might be a Safari Canvas Inspector issue.

##### Three.js version

- [ ] Dev
- [x] r102
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari

##### OS

- [] All of them
- [ ] Windows
- [x ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
`three.js` definitely draws the plane just once per frame. I've tested the Canvas Inspector of Safari 12.0.3 on my system and it shows even three calls of `drawElements`.

![image](https://user-images.githubusercontent.com/12612165/54745908-1be5cc80-4bcb-11e9-81e2-317f9241864c.png)

**Comment by mrdoob** [comment]
Good to know that Safari is adding these tools though!

**Comment by dbismut** [comment]
I agree, is it the only canvas inspector remaining?

**Comment by Mugen87** [comment]
Firefox has a similar tool.

**Comment by dbismut** [comment]
I thought it was deprecated though 😞
https://developer.mozilla.org/en-US/docs/Tools/Deprecated_tools

**Comment by Mugen87** [comment]
> It was deprecated due to lack of use.

Too bad...

**Comment by dbismut** [comment]
Just for information, Safari Technology Preview seems to have fixed the problem in its latest release!
