### ISSUE TITLE
ObjectLoader doesn't parse all geometries

### ISSUE THREAD

**Issue by Temdog007** [mrdoob/three.js#16026]
##### Description of the problem

`ObjectLoader` doesn't support parsing the following geometries:

- `TextGeometry`
- `ParametricGeometry`
- `InstancedGeometry`
- ~~`WireframeGeometry`~~

This causes an issue where the Editor cannot load any scenes or objects that use these geometries.

##### Three.js version

- [x] Dev
- [x] r102

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
There was already a PR (see #14357) in order to introduce support for `EdgesGeometry` and `WireframeGeometry` but it was not accepted. The problem is that adding support for all those geometries blows up `ObjectLoader` and I'm not sure this is desired.

**Comment by Temdog007** [comment]
I understanding not wanting to serialize `EdgesGeometry` and `WireframeGeometry` since those take geometry as a parameter. I would still suggest that `TextGeometry` and `InstancedGeometry` be serialized. This is so that the Editor can import and export these geometries.

**Comment by Temdog007** [comment]
Duplicate of #16340
