### ISSUE TITLE
Raycaster.intersectObjects returns wrong order

### ISSUE THREAD

**Issue by drcmda** [mrdoob/three.js#16031]
##### Description of the problem

![ezgif com-optimize (6)](https://user-images.githubusercontent.com/2223602/54755761-f8c91600-4be6-11e9-9217-d6fb24d8e767.gif)

intersectObjects does not seem to take actual render order into account, the docs say:

> Checks all intersection between the ray and the object with or without the descendants. Intersections are returned sorted by distance, closest first. An array of intersections is returned...

but that will lead to a false order when multiple objects are positioned in the same place. They're rendered correctly, since Three knows internally which object is on top of the other due to opaque ordering, renderOrder and perhaps other indications. But the Raytracer seems to be disconnected from that knowledge as it merely sorts distance, which is random.

I am specifically bumping into this now because i am trying to implement event.stopPropagation for events: [codesandbox](https://codesandbox.io/s/qx20oomj69) The first object that should receive the event is the green one, when it calls stopPropagation, the blue image shouldn't fire. But since order isn't deterministic the object that's visually behind gets to stop propagation first.

##### Three.js version

- [x] r102

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by drcmda** [comment]
PS. if for some reason this gets thrown out, then i'd like to ask if there is any way for me to figure out which object is actually on top and if i can get this data anywhere.

**Comment by gkjohnson** [comment]
Can you provide a minimal example that reproduces the issue?

**Comment by drcmda** [comment]
@gkjohnson i tried to reduce the example above, here's what i've got: https://codesandbox.io/s/042njk2zqp

for some reason it gets two hits for each mesh, no idea why, but you see that it gets the blue one first and the green second. I think the original example above will give you a better picture how that affects a real world case, but the problem is there in this one, too.

**Comment by gkjohnson** [comment]
Your objects are at the same z position in space (`0`) and are both a distance of 5 units from the camera so the logged order should be expected. Try moving one of the planes to a different z position in space.

```js
console.log(hits.map(h => h.distance));
// [5, 5, 5, 5]
```

**Comment by WestLangley** [comment]
The raycaster does raycasting. That is all it does. It does not know anything about rendering or depth testing.

Also, be careful not to be confused into thinking that `renderOrder` determines what is "on top".

**Comment by drcmda** [comment]
@gkjohnson that’s the point, the renderer determines another order, while the Raycaster merely sorts distance.

@WestLangley is there any way I can get the visual order?

**Comment by WestLangley** [comment]
@drcmda Maybe someone on the three.js [forum](https://discourse.threejs.org) can help you with your app.

Closing, as this is an application issue -- not a three.js issue.

**Comment by mrdoob** [comment]
> @WestLangley is there any way I can get the visual order?

If both objects are in the same position... I guess you could traverse the scene? 

Try this:

```js
var array = [];
scene.traverse( function ( child ) { array.push( child } );
array.inderOf( intersectedObject1 );
array.inderOf( intersectedObject2 );
```
