### ISSUE TITLE
Unity compatible per-material render order support

### ISSUE THREAD

**Issue by FMS-Cat** [mrdoob/three.js#16060]
Already discussed a bit on #14415 

We already have `renderOrder` for meshes and groups,
but not for materials, which is supported by Unity (as `renderQueue`).
It would help sorting rendering order of multi-material meshes in certain condition.

I have no idea how much the idea makes good impact for us but I need this at least (🙄),
Since I have to display Unity-compatible stuff (I mean, VRM) on https://hub.vroid.com ...

demo below
https://codepen.io/FMS-Cat/pen/pYBwzw

**Comment by Mugen87** [comment]
Can you please demonstrate a use case (best with a live example) where the existing features of the library are not sufficient so `Material.renderOrder` becomes necessary?

**Comment by Mugen87** [comment]
If I understand you pen correctly, you can only achieve your intended visual result right now if you split up your the geometry into two, create two meshes and apply different materials, right?

**Comment by FMS-Cat** [comment]
Yes, and that's why I said I don't know how the idea help us.
We currently don't have scene description format that describes rendering order of submeshes
(other than VRM, which is unpolished and still wip),
I think the change doesn't cause large impact on both codebase and performance though.

**Comment by FMS-Cat** [comment]
Actual our case in VRoid Hub can be seen on the slide below (Japanese 🙇):

https://speakerdeck.com/fms_cat/webshi-jie-tejun-false3dmoterunisheng-wochui-kiip-mufang-fa?slide=42

We currently are addressing the issue by replacing the `WebGLRenderLists` for our own one.

**Comment by donmccurdy** [comment]
> It would help sorting rendering order of multi-material meshes in certain condition.

Note that in upcoming r103, GLTFLoader will no longer create multi-material meshes. If it's still a dependency of VRMLoader that may affect this issue.

**Comment by FMS-Cat** [comment]
> in upcoming r103, GLTFLoader will no longer create multi-material meshes

https://github.com/mrdoob/three.js/pull/15889

What, I didn't know that!

The PR sounds like we should avoid to use the multi-material meshes...?

**Comment by donmccurdy** [comment]
All glTF files that worked before should still work— each primitive (or material) in a glTF mesh will now become a separate threejs Mesh when loaded.

**Comment by FMS-Cat** [comment]
Yes I acknowledged that, and then I no longer need the feature request anymore 😅

Separating into meshes affects to performance though (at bone update section),
so I might rather use previous merging method anyway.

**Comment by Mugen87** [comment]
Just to clarify: `Material.renderOrder` is useful for sorting the render order of render items derived from a multi material mesh. If you just have meshes with one material, you could put the information from your render queue directly to `Mesh.renderOrder`, right?

**Comment by WestLangley** [comment]
>Just to clarify: Material.renderOrder is useful for sorting the render order of render items derived from a multi material mesh.

Maybe instead of hardwiring in the renderer:
```js
groupOrder = object.renderOrder;
```
we should do this:
```js
addGroup: function ( start, count, materialIndex, groupOrder ) {

	this.groups.push( {

		start: start,
		count: count,
		materialIndex: materialIndex !== undefined ? materialIndex : 0,
		groupOrder: groupOrder !== undefined ? groupOrder : 0

	} );

},
```
It's the object that needs to be sorted, not the material.

**Comment by Mugen87** [comment]
I think it's important not to mix `THREE.Group` and `BufferGeometry.groups`. The first code snippet from `projectObject()` is for the case you assign a render order to an instance of `THREE.Group`. This is for the case you want nested sorting in the scene graph. `BufferGeometry.groups` is only relevant for multi material objects. The derived render items can't be sorted right now and I guess that is @FMS-Cat problem.

**Comment by WestLangley** [comment]
OK.

But still, objects can share materials. `Material.renderOrder` does not make sense to me. We render and sort renderable objects, not materials.

**Comment by Mugen87** [comment]
I agree.Unity's allows to influence the render order on material/shader level (see https://docs.unity3d.com/Manual/SL-SubShaderTags.html) whereas `three.js` does this on object level. Hence, it feels inconsistent to introduce `Material.renderOrder`.

Even if `Material.renderOrder` would be introduced, the feature would not be compatible to Unity's approach like suggested in the issue's title. For example the value of `renderOrder` is "relative" to each render list (opaque and transparent objects). Unity's render queue value is global instead.

**Comment by WestLangley** [comment]
So the question is now, how about my suggestion above, adding
```js
BufferGeometry.groups[ i ].renderOrder
```

But even so, this is such an edge case...

**Comment by FMS-Cat** [comment]
> If you just have meshes with one material, you could put the information from your render queue directly to Mesh.renderOrder, right?

True.

> the value of renderOrder is "relative" to each render list (opaque and transparent objects). Unity's render queue value is global instead.

Yes that is also true, Unity still may use separated render lists internally though,
to achieve opaque should render forward to behind, transparent should render behind to forward.
(and yeah I don't like the way the renderLists gets separated at certain constants (2501 I guess?)).

**Comment by FMS-Cat** [comment]
> how about my suggestion above, adding
>
> ```
> BufferGeometry.groups[ i ].renderOrder
> ```
>
> But even so, this is such an edge case...

Yeah I think so too 😩

**Comment by Mugen87** [comment]
Closing for now. I think we agree to not introduce `Material.renderOrder`. As mentioned by @WestLangley, the engine sorts and renders objects, so it's better if `renderOrder` is only related to `Object3D`. 

If a user really needs to sort the derived render items of a multi material object, the idea is the transform the object into multiple ones and use `Object3D.renderOrder` again. In other words, this (special) use case needs to be solved on application level.
