### ISSUE TITLE
Proposal: Rename AxesHelper, GridHelper, PolarGridHelper

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#16078]
`AxesHelper`, `GridHelper`, and `PolarGridHelper` are not actually helpers, since they are not dependent on another object.

Is there support for renaming these objects to `THREE.Axes`, `THREE.Grid`,  and `THREE.PolarGrid`?

Once concern is the axes helper is very limited, so removing the 'helper' nomenclature may be misleading to some users. (Users may expect more features, such as tick-marks and labels.)

`ArrowHelper` is also not dependent on another object. Maybe it could become `THREE.Arrow`.

**Comment by WestLangley** [comment]
IMO, helpers, which depend on other objects, and expect another object as a constructor arg, should not support `clone()`. Instead, they can optionally have an `update()` method.

**Comment by Mugen87** [comment]
This comment was my motivation to work at the helpers: https://github.com/mrdoob/three.js/issues/13565#issuecomment-372160160

If you call `scene.clone()`, then things will break if helpers are part of the scene graph. I think all objects derive from `Object3D` should support `copy()` and `clone()`. I would not differentiate between helpers that depend on another object and "independent" helpers. I fear things get only more complicated this way.

**Comment by WestLangley** [comment]
>If you call scene.clone(),...

As I have stated previously, IMO only the math objects (_maybe_) should support clone. Clone should be removed from `Object3D()`. That is the source of all the problems with clone.

Add clone support only to the objects for which it makes sense. It does not make sense to clone a camera helper, for example. It does make sense to update a camera helper with a different camera.

>I would not differentiate between helpers that depend on another object and "independent" helpers.

The classes listed above are not helpers in the first place. What does a grid helper help?

**Comment by Mugen87** [comment]
> The classes listed above are not helpers in the first place. What does a grid helper help?

Um, yeah I have to admit that a different nomenclature would be valid. But if you think of these classes as "scene helpers", the names do make sense^^

**Comment by pailhead** [comment]
>Clone should be removed from Object3D().

Is this being proposed elsewhere? I'd like to find out how would `Object3D` be cloned without a clone method.

**Comment by WestLangley** [comment]
Closing due to lack of support.

**Comment by mrdoob** [comment]
Late feedback... 😅

I see these as helpers really, as they're helping to visualise the 3d world. I think the naming sets the right expectations compared to `THREE.Water`, `THREE.Sky`, etc
