### ISSUE TITLE
KTX Cube Textures Fail

### ISSUE THREAD

**Issue by John-DeCorato-HZ** [mrdoob/three.js#16089]
Loading a compressed cube KTX texture causes THREE.js to crash. The bug appears to be that CompressedImageTextures with an array as their image are still treated as individual images. This bug is related to a PR that I submitted earlier this morning.

There is an additional bug with the KTX Texture loader, in that the supplied mipmaps are loaded in the level order [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, etc] when CompressedTexture expected them to be in order [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, etc], but I believe this is a greater issue that needs to be addressed first.

The place that THREE.js crashes is https://github.com/mrdoob/three.js/blob/640f046fc6f3918778e9dfb59fcc9ab3fac9cb05/src/renderers/webgl/WebGLTextures.js#L676, because it's attempting to read the mipmaps from the base image container when the mipmaps are all stored in an array inside of the image parameter.

**Comment by oguzeroglu** [comment]
@John-DeCorato-HZ May I ask how could you get CompressedTextures working with any of the CubeTexture or CubeTextureLoaded classes? I cannot seem to create a CubeTexture from CompressedTextures and having a quick look at the code three.js does not seem to support CubeTextures with CompressedTextures. I'm not exactly sure though.

**Comment by John-DeCorato-HZ** [comment]
@oguzeroglu I just set the flag isCubeTexture to true.

```javascript
const ktxCubeTex = new KTXLoader().load(textureUrl)
ktxCubeTex.isCubeTexture = true
ktxCubeTex.generateMipmaps = false //I have my mips in my ktx
```

**Comment by oguzeroglu** [comment]
I see, I think I got this issue wrong. I was talking about creting a THREE.CubeTexture object using 6 different THREE.CompressedTexture object.
