### ISSUE TITLE
WebGLRenderer: When its renderTarget is undefined, it simply doesn't work

### ISSUE THREAD

**Issue by FMS-Cat** [mrdoob/three.js#16084]
### Description

When you do `renderer.setRenderTarget()` then attempt to `renderer.render()` ,
it doesn't work properly.
However, when you pass `null` instead of `undefined` , it works properly

[Documentation](https://threejs.org/docs/#api/en/renderers/WebGLRenderer.setRenderTarget) and [type definition](https://github.com/mrdoob/three.js/blob/7a7d6e222bcf7b7b6eff48cf0e9132b6a236ce3b/src/renderers/WebGLRenderer.d.ts#L343) says giving `undefined` to the `setRenderTarget` is not wrong usage.
(and type definition says we should not use `null` here)

Demo:

https://codepen.io/FMS-Cat/pen/LaKJvG?editors=0010

### Code / Stack Trace

This is a stack trace:

![image](https://user-images.githubusercontent.com/7824814/55127058-33383300-5152-11e9-9aaa-1907acb0db68.png)

This part makes a mess I guess:

https://github.com/mrdoob/three.js/blob/7a7d6e222bcf7b7b6eff48cf0e9132b6a236ce3b/src/renderers/WebGLRenderer.js#L1208-L1218

### How should we fix this?

I completely recognize what went wrong, so I can propose these solutions:

- Accept both `undefined` and `null` as a render target
  - Automatically replace `undefined` render target with `null` , at beginning of `setRenderTarget`
  - Most preferable imo?
- Ban `undefined` render target
  - Also good to prevent confusion

Which one do you prefer? I'm not good at this context

**Comment by WestLangley** [comment]
The documentation incorrect; the code is correct.

`setRenderTarget()` accepts either a valid render target or `null`. This was established by convention.

Would you like to file a PR to correct the docs?

**Comment by FMS-Cat** [comment]
Good to know! I'll send a PR
