### ISSUE TITLE
Git folder too big

### ISSUE THREAD

**Issue by johnbalvin** [mrdoob/three.js#16091]
#####Git folder is too big, cloning repository last like 1 hour
![image](https://user-images.githubusercontent.com/25888114/55201005-f0488080-518e-11e9-89d8-126324fc772f.png)

Is there a way this library "restart" git not to have that big git file 
##### Three.js version

- [ ] Dev
- [x] r103
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
See #6922 and #8977.

You can do this for smaller size:

```
git clone --depth 1
```
