### ISSUE TITLE
Lens flare shows through object

### ISSUE THREAD

**Issue by jnarm** [mrdoob/three.js#16096]
I am trying to implement lens flare on a model , I am not sure if this is a bug , but I have not seen any other mention of it within issues only over at the forums which has been left unanswered.

It seems that the lens flare is coming through the model when it is viewed from a different angle using orbitcontrols.

![ce1054f6138c630553d964a460ecbe1cc9d6b1b1](https://user-images.githubusercontent.com/16320513/55230149-d783ad80-5216-11e9-8616-211811f2fa0a.png)
![736cb7c3fd7b6b357970cd5827d09d101b912656](https://user-images.githubusercontent.com/16320513/55230153-da7e9e00-5216-11e9-9a2d-7df8d9ccc283.png)

I wont be able to put up a live isolated test case until the project has been finished unfortunately.

##### Three.js version

- [ ] Dev
- [x] r103
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by titansoftime** [comment]
I might have time this weekend to setup an example. We'll see how it goes.

**Comment by RemusMar** [comment]
Most likely there is something wrong with your scene setup or that truck material (alpha related).
Just check out this sample: 
http://necromanthus.com/Test/html5/testA_flare.html 
Walk around Claire R or put the gun in front of the flare.

**Comment by WestLangley** [comment]
>I wont be able to put up a live isolated test case until the project has been finished unfortunately.

Closing for now, then. 

You can reopen this issue when you provide the test case.
