### ISSUE TITLE
Clean up webgl_animation_multiple example

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#16105]
##### Description of the problem

`webgl_animation_multiple` example doesn't follow Three.js code style.

https://github.com/mrdoob/three.js/wiki/Mr.doob's-Code-Style%E2%84%A2

I'm glad if someone cleans up.

##### Three.js version

- [x] Dev
- [ ] r103
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
@strazdinsg Any interests in doing this? 😇

**Comment by takahirox** [comment]
Ah, sorry I had a change of heart and did by myself. Making PR now.

**Comment by takahirox** [comment]
#16106

**Comment by strazdinsg** [comment]
Thanks for reporting, I did not know about the code style guide. Will know next time :)
@takahirox How did you update the style? Configured IDE with the rules from the document and did auto-format?

BTW, I see there is a rule about naming: ConstantsLikeThis. In the file I created CONSTANTS_ARE_LIKE_THIS, probably should be renamed?
I will take a look at the rules and check if the example follows them. Will create a PR in case I find necessary changes.

**Comment by takahirox** [comment]
I manually edited because I don't use IDE to write JavaScript.

I know some modules use CONSTANT_NAME style, for example `GLTFLoader`. I think renaming them may be good for code consistency.

**Comment by strazdinsg** [comment]
We could ask @mrdoob why the constant naming rule is so weird, I have not seen ConstantsLikeThis anywhere else. But I know that one should not question coding convention, just use the one that has been decided "by the board" :). @mrdoob, in case there is an error in the style document and you actually meant CONSTANTS_LIKE_THIS, let us know :)

**Comment by mrdoob** [comment]
I don't have a preference. `CONSTANTS_LIKE_THIS` look good to me.

**Comment by takahirox** [comment]
I prefer `CONSTANTS_LIKE_THIS`. Do you mind if I update the code style wiki page?

**Comment by mrdoob** [comment]
> Do you mind if I update the code style wiki page?

Go for it.

**Comment by takahirox** [comment]
Done
