### ISSUE TITLE
TransformControls: Z-sorting issues with transparent materials

### ISSUE THREAD

**Issue by pikilipita** [mrdoob/three.js#16101]
Transparent materials with png textures are drawned on top of the transform controls. When disabling transparency, the z sorting is correct, see images below
Checked on r96 and r103 

![Screen Shot 2019-03-29 at 23 25 29](https://user-images.githubusercontent.com/1799792/55265776-1008a300-527a-11e9-91ac-266245e2d443.png)
![Screen Shot 2019-03-29 at 23 25 18](https://user-images.githubusercontent.com/1799792/55265777-1008a300-527a-11e9-8f92-1ff6e6c433e0.png)
![Screen Shot 2019-03-29 at 23 14 25](https://user-images.githubusercontent.com/1799792/55265778-1008a300-527a-11e9-8ae2-e983623024e5.png)
![Screen Shot 2019-03-29 at 23 14 16](https://user-images.githubusercontent.com/1799792/55265781-1008a300-527a-11e9-95e0-c12a383c0cc6.png)

**Comment by WestLangley** [comment]
As a work-around, for each of your scene meshes, try setting
```js
mesh.renderOrder = - 1;
```
See if that solves the problem.

It appears `TransformControls` is either going to have to avoid transparent materials or set `renderOrder = Infinity`.

/ping @arodic

**Comment by pikilipita** [comment]
Thank you, I will try your suggestion
Working with transparency has never easy on Threejs ;)
