### ISSUE TITLE
LGTM PRs analysis timeout increase.

### ISSUE THREAD

**Issue by sciecode** [mrdoob/three.js#16116]
##### Recent LGTM analysis timeouts

All recent PR analysis check on LGTM are getting timeout, I would like to raise the discussion if a timeout increase is necessary for the correct evaluation of test cases. 

LGTM [docs](https://help.semmle.com/lgtm-enterprise/admin/help/changing-analysis-timeout.html) explains how this can be done under global settings.

I've went through all merged PRs that happened between the last PR that correctly analyzed all tests and the first PR that started timing out. I couldn't locate any relevant changes that would introduce this problem. 

Which leads me to believe that timeout are occurring because of the sheer amount of code. Therefore, increasing timeout seems the most logic course of action. 

LGTM default timeout is 4 hours, I'm proposing a increase to, at least, 5 hours to verify if the same still occurs.

**Comment by mrdoob** [comment]
Sounds good to me 👌

**Comment by donmccurdy** [comment]
Are there logs available from a run that has timed out? It shouldn't take 4 hours to run our tests – locally they run in 3.5 seconds. Increasing the timeout by another hour doesn't seem like the right fix here.

**Comment by Mugen87** [comment]
> Are there logs available from a run that has timed out?

The log says  `Timed out during 'Analysis'`. However, I can't see something suspicious in the logs...

https://lgtm.com/projects/g/mrdoob/three.js/logs/rev/pr-1011be9fae5ad70c7d7141bba0c13342e7f7a1eb/lang:javascript/stage:Build%20merge_2d5c39879af019e9e9bd2381116faeb357cc1c0b

**Comment by sciecode** [comment]
Recent pull requests are no longer timing out, it could've been something wrong on LGTM's end.
Successful check shows analysis in just under 45minutes:

https://lgtm.com/projects/g/mrdoob/three.js/logs/rev/pr-20dc4d89fadfb08971370f931e2d8827cf4e16cd/lang:javascript/stage:Build%20merge_392a73981990f7d0d16b9fc4486568b91dba17d4

**Comment by WestLangley** [comment]
>l It shouldn't take 4 hours to run our tests – locally they run in 3.5 seconds. Increasing the timeout by another hour doesn't seem like the right fix here.

Exactly.

**Comment by Mugen87** [comment]
Then closing the issue. If the analysis will time out again, it's better to directly contact the support of `lgtm.com`.
