### ISSUE TITLE
released WebGLRenderer referenced by material program

### ISSUE THREAD

**Issue by mikialex** [mrdoob/three.js#16123]
##### Description of the problem

WebGLRenderer referenced by material.dispose after all reference deleted( memory leak ).
Here are some sample code: if you run this sample, and use chrome memory snapshot, you will find WebGLRenderer cant be GCed, which is seem be referenced by material or something. But if you uncomment the material.dispose, the renderer can be GCed properly.

If user not call dispose on all the material which was rendered by some renderer(I think its quite unreasonable),  these renderers may not be released.

![屏幕快照 2019-04-01 下午6 07 16](https://user-images.githubusercontent.com/13088597/55322411-dd93bb80-54ae-11e9-8f5d-4394dd965cd8.png)

```js
var scene = new THREE.Scene();
var camera = new THREE.PerspectiveCamera( 75, window.innerWidth/window.innerHeight, 0.1, 1000 );

var renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );
document.body.appendChild( renderer.domElement );

var geometry = new THREE.BoxGeometry( 1, 1, 1 );
var material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
var cube = new THREE.Mesh( geometry, material );
scene.add( cube );

camera.position.z = 5;

renderer.render( scene, camera );

// material.dispose();

renderer.dispose();
renderer = null;

scene.dispose();
```

Material.dispose remove the program on the material. I've reviewed some code, and feel curious about why material object hold the program.

WebGLRenderer use WebGLGeometries/ WebGLAttributes WebGLProperties to map the user scene data(like, Bufferattributes, Texture) to gl resource(like buffer, gltexture) by maps/weakmaps. Why we direct put program on material instead of use similar mapping ways to avoid such issue?  The other reason material should not hold the program is program is gl context bound. I know threejs could use same scene object and support multi renderer, but it seems strange.

 The reason maybe is too many old code directly use program on material, change this to a renderer related getter is quite a breaking change.

I'am using three in custom ways and feel free to make some changes by our own usage.  Maybe I need more info and the design decision about this issue.

##### Three.js version

- [x] Dev
- [x] r103
- [x] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I'm not sure I understand the actual issue. Do you mean calling `material.dispose()` does not free all related resources? 

Might be related to #12464.

**Comment by mikialex** [comment]
The issues is: When I released all reference to WebGLrenderer, the renderer cant be GCed. Except you have disposed all the material you have used in this renderer.

**Comment by Mugen87** [comment]
Well, why don't you dispose the materials?

**Comment by Mugen87** [comment]
Okay, now I understand. Yes, this is the intended behavior. The library assumes the app disposes materials, geometries and textures separately.

**Comment by mikialex** [comment]
In fact, Its not easy for user to call all materials dispose to actually release renderer.  Users should collect their materials in one place...,thats sound weird .  Maybe we need a weakmap to collect all materials used before, and dispose them all when renderer dispose. I think the library should do this because its a quite common case.

In my point of view,  user can create scene object(geometry, mateial ,,,) and use them freely without too much constraint. Not need worrying render in which canvas/ctx I render and when to dispose.  Dispose is just for release the bound underlayered gl resource, not lead to other object like renderer cant be garbage collect issues.  The lifetime of scene object should not have relation with the renderer.

For now,  like I said above, I found that the webglrenderer leak is due to the unreleased program on material. I think maybe the best way to solve this is not directly put the program object on material. but aquired by renderer.getMaterialProgram(material), this maybe better?>

**Comment by Mugen87** [comment]
I think it's valid to discuss the scope of `WebGLRenderer.dispose()`. Right now, the method does not call `dispose()` on user created objects. It's the responsibility of the app to do this if necessary. Not sure if we want to change this policy.

@mrdoob What do you think?

**Comment by Mugen87** [comment]
Merging into #20346.
