### ISSUE TITLE
Exporting single object to image

### ISSUE THREAD

**Issue by arsonhub** [mrdoob/three.js#16129]
Hello, is it possible to export a selected object to image, like a screenshoot ? I don't want to export all objects on the scene. From this post https://github.com/mrdoob/three.js/issues/989 I saw a solution but it seems to export all scene.

var renderer = new THREE.WebGLRenderer( { preserveDrawingBuffer: true } );
window.open( renderer.domElement.toDataURL( 'image/png' ), 'screenshot' );

Thanks for your answer.

**Comment by looeee** [comment]
Please use the [forum](https://discourse.threejs.org) when asking for help.
