### ISSUE TITLE
Suggestion: Making BufferGeometry.attributes/index properties private or immutable

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#16132]
##### Description of the problem

Currently there are two ways to access `attributes` and `index` properties of `BufferGeometry`. 

1. Directly accessing like `geometry.attributes/index`
2. Using accessing methods `geometry.get/add/removeAttribute()` and `geometry.get/setIndex()`.

I'd like to suggest letting 1 be deprecated by making `.attributes/index` properties private.

**Purposes**

1. For clearer API.

The existence of two ways to access geometry's `attributes/index` may be a bit confusing to users. When should they use accessing methods and when should they directly access? I think the only one way using accessing method is clearer API.

Actually, in `BufferGeometry` document we already encourage using accessing methods rather than directly accessing. So I don't think making them private will be so big trouble.

https://threejs.org/docs/#api/en/core/BufferGeometry

> you must call .getAttribute to access the 'position' attribute

> .attributes : Object
> This hashmap has as id the name of the attribute to be set and as value the buffer to set it to. Rather than accessing this property directly, use .addAttribute and .getAttribute to access attributes of this geometry.

> .addAttribute ( name : String, attribute : BufferAttribute ) : BufferGeometry
> Adds an attribute to this geometry. Use this rather than the attributes property, because an internal hashmap of .attributes is maintained to speed up iterating over attributes.

2. For VAO implementation.

We've been working on VAO implementation in #14600. We proposed assigning one VAO to one geometry which manages the set of attributes and index. VAO is for performance, so we need to quickly detect whether we need to update VAO or not. Taking time each frame to judge if we need the update doesn't make sense.

So I proposed attributes/index addition and removal to/from geometry observation. But currently Three.js API is too flexible that users can directly access `attributes/index` properties and add/remove to/from them. This makes the observation hard. Making the properties private can have it easy because we only need to observe accessing methods.

**Disadvantage**

1. Breaking core/examples/user code.

I see a lot of codes directly accessing `geometry.attributes/index`. If we make the properties private, such codes need to be updated.

2. We need to add `.getAttributeNames()` method (or something)

I sometimes see this type of code.

```javascript
for ( var attributeName in geometry.attributes ) {
    var attribute = geometry.attributes[ attributeName ];
    ....
}
```

It can't be handled with the current attribute accessing methods. Probably we will need to add a new method `.getAttributeNames()` which returns attribute names as an array.

Feedback is welcome.

##### Three.js version

- [x] Dev
- [ ] r103
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
from https://threejs.org/docs/#api/en/core/BufferGeometry
>you must call .getAttribute to access the 'position' attribute

To clarify, that statement is patently false.

**Comment by Mugen87** [comment]
I think a sensible implementation of VAOs is only possible if this suggestions is accepted. It's more or less a general decision whether performance is more important for the engine than flexibility. 

My former view on the `three.js` was that project was always focused on flexibility. However, certain performance features like VAOs or caching of matrices require a more strict API. The latter one for example will require to make `Object3D.matrix` private which is a similar breaking change.

I personally tend to performance (since better performance was requested multiple times) but it is also true that `three.js` was criticized in the past for its less stable API (for example [here](http://www.html5gamedevs.com/topic/37703-babylonjs-vs-threejs-choosing-a-webgl-framework-for-sony/)). Because of this, I'm very unsure about how to decide in this issue...

**Comment by donmccurdy** [comment]
> I think a sensible implementation of VAOs is only possible if this suggestions is accepted.

I don't understand this part... what benefit does making `geometry.attributes` private give that just making it readonly would not? Are we worried about users doing:

```js
// this?
geometry.attributes.position = new THREE.BufferAttribute(...);

// or this?
geometry.attributes.position.updateRange(...);
```

If the latter is one of our concerns, then just changing it to `getAttribute('position').updateRange(...)` doesn't really solve anything. Making `geometry.attributes` an immutable object, rather than a private variable, would avoid a breaking change without – as far as I can tell – any downside for VAO support.

Aside: My impression has always been that `addAttribute` and `removeAttribute` were the right way to go, and that direct assignments/deletions were never guaranteed to work. But I didn't know `getAttribute` existed, and have never used it. 😅

**Comment by Mugen87** [comment]
> geometry.attributes.position = new THREE.BufferAttribute(...);

This would be bad. All direct assignments or deletions to `BufferGeometry.attributes` don't raise the new `BufferGeometry.version` property which is introduced in #14600.

**Comment by donmccurdy** [comment]
Right, but if `geometry.attributes.position.updateRange(...);` is not bad, then I don't see why we need `geometry.attributes` to be private rather than just immutable. Not necessarily opposed to that either, but it doesn't seem necessary for the goals here.

**Comment by aardgoose** [comment]
You could make geometry.attributes a Proxy() object to handle direct access correctly and allow existing applications to continue functioning, but Proxy() is not supported on IE11.

**Comment by Mugen87** [comment]
> Right, but if geometry.attributes.position.updateRange(...); is not bad, then I don't see why we need geometry.attributes to be private rather than just immutable. 

How would this look like? Maybe some code would clarify things^^

**Comment by donmccurdy** [comment]
At the simplest...

```js
class BufferGeometry {
  setAttribute( name, attribute ) {
    this.attributes = Object.assign( {}, this.attributes, { [ name ]: attribute } );
    Object.freeze( this.attributes );
    return this;
  }
}
```

... but there are any number of ways to implement this, which would all make it obvious to users that `geometry.attributes` is readonly. Making the right method obvious is probably more important than making it impervious to monkeypatching here.

I'm offering this as a way to avoid breaking code that reads from `geometry.attributes`, not necessarily as advice.  If we think that `getAttribute(name)` is a better API for whatever reason, we can also figure out a way to make that migration with limited inconvenience to users.

**Comment by takahirox** [comment]
Oh, I didn't know that I can make an immutable object.

So, yeah for VAO purpose I think immutable `.attributes/index` properties is good enough, we don't need to make them private.

I still feel the only one way to access using `getAttribute/Index()` is clearer API. But also I don't think we need to break a lot of codes right now. We can make them private when we think we really should do.

What I'd like to improve in short term is performance by using VAO rather than cleaning up API. So I'd like to suggest making `.attributes/index` properties immutable and force to use `.add/removeAttribute()` and `setIndex()` for adding/removing attribute and index for now.

What do you think? It can still break this type of code.

```javascript
geometry.attributes.position = new THREE.BufferAttribute(...);
delete geometry.attributes.position;
geometry.index = new THREE.BufferAttribute(...);
geometry.index = null;
```

But I agree with Don 

> Aside: My impression has always been that addAttribute and removeAttribute were the right way to go, and that direct assignments/deletions were never guaranteed to work.

**Comment by yomboprime** [comment]
I just wanted to comment that I could help converting the examples that use direct attribute access to the method api.

**Comment by aardgoose** [comment]
The only examples using direct access for assignment appear to be

examples/js/loaders/LWOLoader.js
examples/webgl_buffergeometry_instancing2.html
examples/webgl_buffergeometry_instancing_dynamic.html

**Comment by Mugen87** [comment]
> I'm offering this as a way to avoid breaking code that reads from geometry.attributes, 

I'm not sure reading from `BufferGeometry.attributes` is the actual issue. The problematic part is the configuration of the `BufferGeometry`. And introducing VAO would mean a migration effort in any case, even if `.attributes/index` would be readonly.

Against this backdrop, it could be worth to make `BufferGeometry.attributes` directly private in order to enable VAO and a cleaner API all at once.

**Comment by donmccurdy** [comment]
I agree that reading from `geometry.attributes` is not an issue, but this means making `.attributes` private (as opposed to readonly) is not actually necessary to enable VAO.

In my opinion, `getAttribute('foo')` is cleaner than `.attributes.foo`, since setters are required to modify it anyway. Whether it is actually worth deprecating _reads_ from `.attributes.foo` and breaking a lot of existing code depends (to me) on how many other breaking changes VAO requires, and the performance benefits we see from that.

**Comment by Mugen87** [comment]
> we can probably take a warn-but-not-break approach indefinitely here.

It would be best to verify if this is actually possible and all relevant use cases are supported. In this way, the discussion avoids to promote a solution that might be inappropriate.

**Comment by donmccurdy** [comment]
I don't think there's any technical blocker here. We can use getters/setters:

```js
Object.defineProperty(this, 'attributes', {
  get: function() {
    console.warn( 'THREE.BufferGeometry: Please use getAttribute().' );
    return _attributes;
  },
  set: function() {
    throw new Error( 'THREE.BufferGeometry: Please use addAttribute() / removeAttribute().' );
  }
});
```

**Comment by aardgoose** [comment]
@donmccurdy surely that only handles assignment or getting the entire attribute object itself. not properties of the attribute object?

**Comment by donmccurdy** [comment]
Yes, but calling `geometry.attributes.position.count()` still accesses the attributes property, and will still log the same warning. :)

**Comment by aardgoose** [comment]
ah, of course. Although set: will only catch this.attribute = foo  rather than this.attribute.foo = foo  so not handling that case with the right message.

**Comment by takahirox** [comment]
It seems that we can't hook `geometry.attributes.position = bufferAttribute;` and call `geometry.addAttribute( 'position', bufferAttribute )` insted (other than using `Proxy`). So the getter should be like this?

```javascript
Object.defineProperty(this, 'attributes', {
  get: function() {
    console.warn( 'THREE.BufferGeometry: Please use getAttribute(), addAttribute(), or removeAttribute().' );
    this.version ++;
    return _attributes;
  }
});
```

It counts up `geometry.version` leading to VAO update even if just getting an attribute, but keeps working.

**Comment by takahirox** [comment]
> depends (to me) on how many other breaking changes VAO requires, and the performance benefits we see from that.

The current VAO implementation in #14600 requires
- Deprecating direct `geometry.attributes/index` access
- The following properties immutable

```
BufferAttribute: .normalized, .itemSize, .type,
InterleavedBufferAttribute: .normalized, .itemSize, .type. .offset, .data.stride
InstancedBufferAttribute/InstancedInterleavedBuffer: .meshPerAttribute.
```

https://github.com/mrdoob/three.js/pull/14600#issuecomment-478768913

The performance benefit is 10-15% performance gain overall application in significant VBO switching case.

Maybe I need to test more general case but this performance benefit looks good even though we sacrifice something. IMO the second requirement seems ok because usually they aren't updated runtime.  The first requirement might have a bit impact breaking a lot of code. But deprecating direct access looks cleaner API, so I'd like to go with it.

**Comment by takahirox** [comment]
> Reading the .attributes property should not increment any counters or have other side effects. The Object.freeze() suggestion above prevents the attributes object from being modified, so attributes.position = foo will fail.

OK, I thought we didn't want to break any user code/application even if having side effect which can be solved by updating their code. But seems like I misunderstood the discussion.

**Comment by takahirox** [comment]
Made draft PR to show how the change looks like. #16232

**Comment by takahirox** [comment]
Closing for now because I made VAO without any breaking existing APIs PR #16287 We can revisit later if needed.
