### ISSUE TITLE
PCDLoader: Memory error with arraybuffer

### ISSUE THREAD

**Issue by DepickereSven** [mrdoob/three.js#16136]
##### Description of the problem

I'm getting the following error: 
`
"[Exception... "Out of Memory" nsresult: "0x8007000e (NS_ERROR_OUT_OF_MEMORY)" location: "JS frame :: webpack-internal:///./src/assets/js/Vue/Live/ThreeJs/Init.js :: updateFigure :: line 98" data: no]"
`

So how do I get that memory error?
Well, I'm trying to recreate a live image feed.
What I do is I send a request to a server to get a raw PCD file in text format.
When I receive an answer I replace it with the current mesh that is loaded.
But after 1056 requests I got that memory error.
The ArrayBuffer is getting bigger and bigger??
The size of the data string is around 16MB each.

The code where he gets the error:

```
async function updateFigure(liveFeed) {
        PCDData = liveFeed;
        let PCD = scene.getObjectByName('liveFeed');
        let loader = new Three.PCDLoader();
        let enc = new TextEncoder();
        let data = enc.encode(PCDData);
        let mesh = loader.parse(data, 'liveFeed');
        PCD.geometry = mesh.geometry;
        PCD.geometry.center();
    }
```

Arraybuffer is becoming 12GB.

![image](https://user-images.githubusercontent.com/26543813/55449784-8a7d4e00-55ff-11e9-9ce3-4a62eca71508.png)

##### Three.js version

- [x] Dev
- [ ] r103
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Can you provide a test case we can use to reproduce the issue?

**Comment by DepickereSven** [comment]
I have made [a test](https://github.com/DepickereSven/ThreeJs-PCDLoader-memory) case so you can try to simulate it.

You need to run a server that is located in the folder `node`
You can run it by `npm start`

The web app is located in the folder `WebApp`
You can run it by `npm run serve`

The standard ThreeJs library files are located in the following folder:
`WebApp/src/assets/js/Vue/Live/ThreeJs/Libs`

The code above I was referring to [is located here](https://github.com/DepickereSven/ThreeJs-PCDLoader-memory/blob/master/WebApp/src/assets/js/Vue/Live/ThreeJs/Init.js#L85-L95):

```
    async function updateFigure(liveFeed) {
        PCDData = liveFeed;
        let PerrinePCD = scene.getObjectByName('liveFeed');
        let loader = new Three.PCDLoader();
        let enc = new TextEncoder();
        // TODO Change to the right data input to load directly
        let data = enc.encode(PCDData);
        let mesh = loader.parse(data, 'liveFeed');
        PerrinePCD.geometry = mesh.geometry;
        PerrinePCD.geometry.center();
    }
```
I tested my test case now It gives the memory error at 3.8GB see screenshot. I placed a counter in the number of requests he sends and now crashes he at the 297 request.

![crash](https://user-images.githubusercontent.com/26543813/55460306-418bc080-5624-11e9-8a23-554d3a4a1e09.JPG)

If you have other questions feel free to ask.

**Comment by DepickereSven** [comment]
[a test](url)

**Comment by DepickereSven** [comment]
[a test](url)

**Comment by Mugen87** [comment]
There is indeed a memory leak in your application. Before assigning a new geometry to `PerrinePCD`, you have to call `dispose()` on the old geometry. Otherwise all previous geometries are kept inside the renderer:
```js
PerrinePCD.geometry.dispose();
PerrinePCD.geometry = mesh.geometry;
```

**Comment by DepickereSven** [comment]
Thank you very much, like you can see the overall RAM usage is now around 140MB instead of increasing everytime

![Solve](https://user-images.githubusercontent.com/26543813/55468517-24f88400-5636-11e9-8764-c7768bead089.JPG)
