### ISSUE TITLE
OBJLoader: this.materials is expected to have create method but defined as Array

### ISSUE THREAD

**Issue by pvogel2** [mrdoob/three.js#16135]
Hi, first of all: I think three.js is a great library and I like it a lot!

The following thing I found in three.js revision 103.

The OBJLoader.setMaterials sets the internal used property materials and expects an Array (see documentation). Internally a create  method is called on materials which is not defined on Array:
https://github.com/mrdoob/three.js/blob/19cea63fa4b6a06991fc9f47a252637e58df8763/examples/js/loaders/OBJLoader.js#L685

Some example code to trigger the problem:

    const objLoader = new THREE.OBJLoader();
    objLoader.setMaterials([new THREE.MeshStandardMaterial( { color: 0x444444 } )]);
    objLoader.load('path/to/some/obj/file');
 
at this point it seems there is some legacy(?) code remaining or do I get something wrong? When I give a MTLLoader result (which is a MTLLoader.MaterialCreator) to the OBJLoader.setMaterials method everything works fine.

But I think this can not be the correct sollution because on the other hand materials ist treated as Array inside the OBJLoader and Array methods are also called on it not defined on MTLLoader.MaterialCreator.

**Comment by eos3tion** [comment]
the right type is `MaterialCreator`
