### ISSUE TITLE
请问three里如何使用 3dmax导出的摄像机动画？

### ISSUE THREAD

**Issue by seanin** [mrdoob/three.js#16139]
问题：3dmax导出的 摄像机动画（fbx格式，动画已经在3dmax里做好了），three加载这个fbx后，使用
`mixer = new THREE.AnimationMixer( model );
 mixer.clipAction( model.animations[ 0 ] ).play();`
方法后 ，普通的物体运动动画可以播放，但是摄像机动画不播放；

请问该如何实现这个需求，有案例可以参考么？

**Comment by Mugen87** [comment]
Can you please write your issue in English? I've tried to translate your content with a translator but I'm not sure I understand the result^^

As far as I understand, you have animated a model and a camera in 3DSMax and exported the project to FBX. After importing to `three.js`, the animation of the model works but the camera is still static.

Is this your issue?

**Comment by seanin** [comment]
OK. thanks.
Your translation is very accurate. 
The camera has path animation in 3dsmax, But after importing to three.js, the camera is still static.

**Comment by looeee** [comment]
@seanin can you share the model here?

**Comment by seanin** [comment]
That model has 50M, I put it on the baidu network disk,

链接：https://pan.baidu.com/s/1PdKiktSDQSZB29Mc3CcN-A 
提取码：4ebx

**Comment by pailhead** [comment]
Can someone share the translation? Let's go to O(1) instead of O(n).

**Comment by looeee** [comment]
> That model has 50M, I put it on the baidu network disk, @looeee

@seanin that's telling me I need to install an app to download. Can you share somewhere that I can directly download, such as dropbox or google drive?

**Comment by mrdoob** [comment]
Lets move this to https://discourse.threejs.org/ please.

**Comment by seanin** [comment]
I've moved the translation and model download links on to
https://discourse.threejs.org/t/how-to-use-the-camera-animation-in-three-by-3dsmax-exported/6959

@looeee @pailhead

**Comment by asfdafasf** [comment]
您好，请问最终是怎么解决的呀？方便告知吗？

**Comment by pxim** [comment]
> 您好，请问最终是怎么解决的呀？方便告知吗？

没解决，没用摄像机动画；动画是 物体变化；

**Comment by asfdafasf** [comment]
@pxim 好的，谢谢了！因为我导出摄像机动画也出现了这个问题！
