### ISSUE TITLE
Directional Lights are inverted?

### ISSUE THREAD

**Issue by John-DeCorato-HZ** [mrdoob/three.js#16143]
When creating buffer geometry and forcing all of the normals to be (0, 1, 0), I need to set the position of a directional light to (0, -1, 0) to get the light to shine top down. Is this expected behavior?

I double checked by creating a default plane geometry with a standard material and adding a directional light. When rotating the plane along the x axis 1.5708 radians (making the normals [0, 1, 0]), the plane is dark. When rotating -1.5708 radians, the plane is lit.

**Comment by WestLangley** [comment]
Please redirect your question to the three.js [forum](https://discourse.threejs.org).

**Comment by looeee** [comment]
Also, please create a working demo showing your issue when you post there, as a JSFiddle or Codepen.
