### ISSUE TITLE
GLTFLoader: can load model without texture correctly on IE11 but can not load model with texture?

### ISSUE THREAD

**Issue by JackQu2018** [mrdoob/three.js#16142]
##### Description of the problem
why GLTFLoader can load model without texture correctly on IE11 but can not load model with texture.
Here are two links to illustrate this problem. 
1. http://support.huawei.com/onlinetoolsweb/SmartApi/get3dDtail?threedurl=EG8120L@c79df9d1675a4d9e9988f61fc7bacbb3
2.  http://support.huawei.com/onlinetoolsweb/SmartApi/get3dDtail?threedurl=MA5833@776fcd9c95de42b6867011dfd1c4b3ab

In the first link, there is no texture for the model, and it can be loaded  and displayed successfully on IE11. But in the second link, there are textures for the model, and it can not be loaded and displayed. I don't know why, could anyone help? thanks very much
My IE11 version is 11.2189.14393.0.

**Comment by donmccurdy** [comment]
Sorry I'm not sure how to help you with this. Do you see any errors in the JavaScript console in IE11? Does the model work in http://gltf-viewer.donmccurdy.com/ or http://sandbox.babylonjs.com/? If you can isolate the problem to a simpler demo that would help..

**Comment by mrdoob** [comment]
This is what I'm getting:

![CaptureIE1](https://user-images.githubusercontent.com/97088/56475063-ff41ec00-6437-11e9-93b1-9b3f0a535e95.PNG)
![CaptureIE2](https://user-images.githubusercontent.com/97088/56475065-0406a000-6438-11e9-9ddc-651f03099c2e.PNG)

**Comment by mrdoob** [comment]
Closing until @JackQu2018 provides more info.

**Comment by JackQu2018** [comment]
Thanks @mrdoob @donmccurdy
