### ISSUE TITLE
Draco exporter not exporting mesh morph targest

### ISSUE THREAD

**Issue by visus100** [mrdoob/three.js#16146]
After exporting mesh (morph targets included) with [Draco Exporter example](https://threejs.org/examples/?q=draco#misc_exporter_draco) **morph targets are not exporting**.

3D Object was created in [KhronosGroup-Blender-Exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter) with .glb extension. Morph targets fully worked before exporting (tested). 

[link to repository with described models ](https://github.com/visus100/Draco-gltf) 

![console output comparing](https://user-images.githubusercontent.com/22850382/55523503-e8567800-5689-11e9-8d74-81cc56b158f4.png)

* [codepen with exported model](https://codepen.io/donkeyLuck0/pen/mgVWew)

##### Three.js version

- [ ] Dev
- [x] r103
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
The Draco (`.drc`) format supports only geometry – no animation, materials, textures, or morph targets. For those features, you can export to glTF and then add Draco compression to the geometry in the glTF file. See the [DRACOLoader documentation](https://threejs.org/docs/#examples/loaders/DRACOLoader).

**Comment by visus100** [comment]
Correct me if I'm wrong but in official [Draco Version 1.3.4 release ](https://github.com/google/draco)
There is note:
-Released Draco Animation code

So i think that it could be work for animations included in DRACOLoader (maybe as a feature).

**Comment by TimvanScherpenzeel** [comment]
As a side note: there is an ongoing effort to https://github.com/KhronosGroup/glTF/pull/1407 to add support for DRACO animation compression to the glTF spec as an extension.

**Comment by donmccurdy** [comment]
The Draco library supports more than the `.drc` file format. That's the library used to create compressed glTF files, too. As far as I know that animation code is only currently used in the (incomplete) glTF compressed animation extension, and `.drc` is not meant to be used for anything more than geometry.

If you want features beyond just geometry, using Draco in glTF is the way to go here. THREE.GLTFExporter already supports morph targets.
