### ISSUE TITLE
Editor: Scene.background and .environment are not set when importing a JSON scene.

### ISSUE THREAD

**Issue by Temdog007** [mrdoob/three.js#16154]
##### Description of the problem

When loading a scene, the background of the editor is not set to the background of the scene. This causes an issue when exporting because the scene's background will be overwritten to the Editor's default gray.

##### Three.js version

- [x] Dev
- [x] r103

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
As mentioned in #18479 and #18715, it's necessary to change `ObjectLoader`, `Scene.toJSON()` and `Object3D.toJSON()` to make this work in the core library.

The editor itself needs some minor changes in `SetSceneCommand` and `Editor` .

**Comment by Mugen87** [comment]
With #22023 and #22187 in place, this issue can be closed 🎉 .
