### ISSUE TITLE
Docs: MeshDistanceMaterial is missing

### ISSUE THREAD

**Issue by Temdog007** [mrdoob/three.js#16159]
##### Description of the problem

There is no entry for `MeshDistanceMaterial`. There is an [example](https://threejs.org/examples/?q=point#webgl_shadowmap_pointlight) that uses `MeshDistanceMaterial`, ~~but  it also uses a [`customDistanceMaterial`](https://github.com/mrdoob/three.js/blob/5fa442d2d4478f6ef1a8697a969abeef92b51507/examples/webgl_shadowmap_pointlight.html#L103) property that isn't explained either in the docs.~~

##### Three.js version

- [x] Dev
- [x] r103

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> but it also uses a customDistanceMaterial property that isn't explained either in the docs.

https://threejs.org/docs/index.html#api/en/core/Object3D.customDistanceMaterial

**Comment by Mugen87** [comment]
BTW: The doc page for `MeshMatcapMaterial` does not exist, too.
