### ISSUE TITLE
PointerLockControls needs better implementation

### ISSUE THREAD

**Issue by arodic** [mrdoob/three.js#16160]
##### PointerLockControls needs better implementation consistent and compatible with other controls.

While trying to validate PR #16093 I noticed that `PointerLockControls` does not play nice with OrbitControls and implements several anti-patterns that result with strange and unexpected behaviors.

Some of the problems:

1. It sets camera rotation to 0,0,0 in the constructor (because otherwise it does not work correctly).

2. It moves camera from its original hierarchy to its own Object3D hierarchy.

3. It requires its `yawObject` and its children to be added to rendered scene (otherwise transforms are not applied to camera)

4. Unlike other controls, It does not emit `change` event.

5. In the example (misc_controls_pointerlock.html), there is an application-side implementation of first person controls in conjunction with `PointerLockControls` that exhibits convoluted patterns that require understanding on internal hierarchy of `PointerLockControls` and its (internally set) relationship with the camera.

Suggested solution:

Re-implement `PointerLockControls` in such way that it does not reset camara's rotation, it does not make any modifications to any scenegraph, and can be intuitively used like other controls.

**Comment by WestLangley** [comment]
Do you intend to file a PR and reimplement `PointerLockControls`?

**Comment by arodic** [comment]
@westlangley I started doing it, then realized I might be wasting time if there is strong opposition to the idea, since it will be a breaking change after all. I hope this issue will gauge the interest and support to improve this piece of code.
