### ISSUE TITLE
Regression: WebGLRenderer 'vr' variable refactor breaks in NodeJS

### ISSUE THREAD

**Issue by Sunstradamus** [mrdoob/three.js#16165]
##### Description of the problem

`navigator` is undefined in NodeJS. The refactoring done in commit https://github.com/mrdoob/three.js/commit/67eb3c4f6bba237fe517cccf8a48af22774a708d changed the underlying logic of the code from:

```
if navigator.exists && navigator.has('xr')
  vr = WebXRManager
else
  vr = WebVRManager
```

to

```
if navigator.exists
  if navigator.has('xr')
    vr = WebXRManager
  else
    vr = WebVRManager
else
  vr = null
```

This allows the previously non-nullable `vr` to be null. This causes the renderer to break when rendering in NodeJS on https://github.com/mrdoob/three.js/blob/00bd806e0d0754e6ab09ca0a272e5566bc94f59d/src/renderers/WebGLRenderer.js#L1122

While I understand that NodeJS is not supported, the fix to this issue is relatively trivial. Reverting https://github.com/mrdoob/three.js/commit/67eb3c4f6bba237fe517cccf8a48af22774a708d will fix the regression.

##### Three.js version

- [x] Dev
- [x] r97 - r103

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] NodeJS

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

N/A

**Comment by Mugen87** [comment]
Yes, I think this change makes sense. I think we were not aware of the mentioned side effect when https://github.com/mrdoob/three.js/pull/14914#issuecomment-422858333 was implemented.

**Comment by mrdoob** [comment]
Indeed...
