### ISSUE TITLE
101 -> 103: renderer alpha ignored

### ISSUE THREAD

**Issue by revyTH** [mrdoob/three.js#16176]
##### Description of the problem

Switching from 101 to 103 I noticed that enabling alpha on renderer does not have effect anymore:

`
renderer = new THREE.WebGLRenderer({antialias: true, alpha: true})
renderer.setClearColor(0x000000, 0)
`

Need to change something in the code?

##### Three.js version

- [x] r103

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
I'm not able to reproduce, see: https://jsfiddle.net/tnqpgdf9/

Please demonstrate the issue with a live example.

**Comment by revyTH** [comment]
Yeah the problem was with a modified version of the UnrealBloomPass to enable transparent background, taken from this discussion: [https://github.com/mrdoob/three.js/issues/14104](https://github.com/mrdoob/three.js/issues/14104). It worked in 101 but it seems broken in 103.
Maybe should close this and ask in that thread directly?

**Comment by Mugen87** [comment]
> Maybe should close this and ask in that thread directly?

Yes. There might be a relation to the removal of `renderTarget` and `forceClear` parameters of `WebGLRenderer.render()` in `R102` (see #15571). This change requires a migration in user code so render targets are set correctly and clears are properly performed.
