### ISSUE TITLE
ImageBitmapLoader options can be overriden before the former request is done

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#16197]
##### Description of the problem

**Background**

`ImageBitmapLoader` aynchronously calls `createImageBitmap()` inside. So `ImageBitmapOptions` passed from user to `ImageBitmapLoader` via `.setOptions()` is used aynchronously.

https://github.com/mrdoob/three.js/blob/dev/src/loaders/ImageBitmapLoader.js#L68-L85

```javascript
fetch( url ).then( function ( res ) {

	return res.blob();

} ).then( function ( blob ) {

	return createImageBitmap( blob, scope.options ); // using options here

} } ).then( function ( imageBitmap ) {
```

**Problem**

If user consecutively loads two or more files with different `ImageBitmapOptions` parameter, only the last option is used for all the requests and other options are ignored.

```javascript
var loader = new THREE.ImageBitmapLoader();

loader.setOptions( { imageOrientation: 'none' } );
loader.load( url1, function ( bitmap1 ) {
    // bitmap1 is created with { imageOrientation: 'flipY' } option
    // because option is overriden before creating bitmap1
} );

loader.setOptions( { imageOrientation: 'flipY' } ); // options is overriden 
loader.load( url2, function ( bitmap2 ) {
} );
```

**Potential solutions**

1. Keep options when `.load()` is called and use that options for `createImageBitmap()`.
2. Ask users to create another `ImageBitmapLoader` instance if they want to pass another option parameter, and document it.

##### Three.js version

- [x] Dev
- [ ] r103
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> Ask users to create another ImageBitmapLoader instance if they want to pass another option parameter, and document it.

I would go that route. Otherwise it would be better to remove `setOptions()` and apply the configuration object as a parameter of `load()` instead.
