### ISSUE TITLE
Mesh jumping around

### ISSUE THREAD

**Issue by DepickereSven** [mrdoob/three.js#16193]
I have a camera that generates PCD files that I load in the browser. 
So to create a sort kind of live stream I replace the current mesh.
But I noticed that he jumps around.
See the image and test case.

This is the boundingsbox max and min values of 2 PCD I load.
![jump](https://user-images.githubusercontent.com/26543813/55711140-aed19400-5a1e-11e9-90c0-74bdc24d5c04.JPG)

I don't know if the problem is the bounding box?
Is there a way I can lock my mesh to a certain position in x y z-direction so it won't jump around.

I have made a[ test case](https://github.com/DepickereSven/ThreeJs-PCDLoader-memory/tree/JumpingMesh) so you can try to simulate it.

(Make sure you're in the JumpingMesh branch)

You need to run a server that is located in the folder node
You can run it by npm start

The web app is located in the folder WebApp
You can run it by npm run serve

The standard ThreeJs library files are located in the following folder:
WebApp/src/assets/js/Vue/Live/ThreeJs/Libs

##### Three.js version

- [x] Dev
- [ ] r103
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
