### ISSUE TITLE
Box's setFromObject doesn't work on CSS3DObject

### ISSUE THREAD

**Issue by joenil** [mrdoob/three.js#16203]
##### Description of the problem
An CSS3DObject got all dimensions Infinity:
![image](https://user-images.githubusercontent.com/11400674/55771041-07556f80-5ab9-11e9-9ec1-38264e64afbd.png)

##### Three.js version

- [ ] Dev
- [x] r103
- [ ] ...

##### Browser

- [x] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Usnul** [comment]
It makes sense. There is no geometry behind CSS3DObject. Extracting the dimensions would be error-prone, since HTML content can change, it's not static, and even if it is - say you're loading an image, before it loads - the dimensions of the element are likely to be different.
