### ISSUE TITLE
[OrbitControls] Use touchmove instead of pinch for zooming

### ISSUE THREAD

**Issue by MorenoDD** [mrdoob/three.js#16215]
Hi folks,
I would like to change the default behaviour of the OrbitControls. 
My needs is to use touchmove instead of pinch for zooming on mobile devices.

I see that the function onTouchMove() (which call handleTouchMoveDolly()) is triggered when you use two fingers. 

Take a look at this reference:
https://2018.craftedbygc.com/

Did you have any suggestion?

Thanks.

**Comment by WestLangley** [comment]
Please use the three.js [forum](https://discourse.threejs.org) for help requests.
