### ISSUE TITLE
OBJLoader: Loader does not return valid geometry with inconsistent face definitions

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#16211]
If the OBJ file specifies face indices inconsistently then the loader will return geometry with mismatched attribute lengths. I ran into this issue while loading an OBJ file I'm working with and it causes the geometry to not render. Unfortunately I can't share the model but I'll try to give a  rough example of what's happening.

The OBJ face list might be formed like so. Notice that one face does _not_ specify normals while the other faces do:
```obj
f 1050//4 1051//5 1049//6
f 185//7 183//8 179//9
f 500 505 1053
f 732//10 500//11 1053//12
f 153//13 144//14 137//15
```

This will result in a position attribute with a count of `15` and a normal array with a count of `12`, meaning the geometry will fail to render (and the normals and positions are now misaligned in their respective arrays). The problematic logic seems to be in [the `addFace` function](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/OBJLoader.js#L279), which just ignores an empty normal values even if they're defined in sibling faces. You can see that this will also be a problem for UVs, as well.

The problem is not present in `OBJLoader2` and a mesh formed like this loads just fine in MeshLab, as well.

**Comment by Mugen87** [comment]
So you suggest to add some default values for missing entries in the OBJ? If so, how would these default values look like?

Instead of adding new values, the loader could also discard buffer attributes with a wrong `count` property.

**Comment by gkjohnson** [comment]
By default it looks like the loader will [generate face normals](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/OBJLoader.js#L657) if a set of normals isn't provided, so it would make sense to me to generate a face normal if a normal isn't provided. For UVs I would just set them to `0,0`.

If no normals or uvs are specified in any of the faces in a group, though, I would expect that no normal or uv attributes get created.

> Instead of adding new values, the loader could also discard buffer attributes with a wrong `count` property.

It doesn't really feel right to discard that data just because it's only specified for some faces but this would prevent the loader from output un-renderable geometry.
