### ISSUE TITLE
VRML loader in three.js rev 94 and above

### ISSUE THREAD

**Issue by farshid2** [mrdoob/three.js#16219]
I have a VRML model at: https://fe4d.com/tmap/assets/tube.wrl .
I can load it with VRMLLooader in three.js rev 82. But when tried three.js rev 94 and rev 102, it failed.

Thanks

##### Three.js version

- [ ] Dev
- [x] r102
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
see https://stackoverflow.com/questions/55609571/vrml-loader-in-three-js-rev-94-and-above

I can confirm there is a regression. I was able to load the file with `three.js` `R82` and the respective version of `VRMLLoader`.

**Comment by Mugen87** [comment]
see https://stackoverflow.com/questions/55609571/vrml-loader-in-three-js-rev-94-and-above

I can confirm there is a regression. I was able to load the file with `three.js` `R82` and the respective version of `VRMLLoader`.

**Comment by Mugen87** [comment]
With the linked PR, `tube.wrl` should work again. At least I have the same visual result as with `R82`.

![image](https://user-images.githubusercontent.com/12612165/56039091-cc12a500-5d33-11e9-923b-fd081e7ff00d.png)
