### ISSUE TITLE
FirstPersonControls is not a constructor

### ISSUE THREAD

**Issue by steeves66** [mrdoob/three.js#16229]
##### FirstPersonControls is not a constructor

please I do not understand, here is my code:

<src script = "libs / js / threejs / FirstPersonControls">
camera = new THREE.PerspectiveCamera (75, window.innerWidth / window.innerHeight);
...........
...........
controls = new THREE.FirstPersonControls (camera);

but the console sends me back:
Uncaught TypeError: THREE.FirstPersonControls is not a constructor.

Where is the problem ? help me

**Comment by WestLangley** [comment]
This is not a help site. Please use the three.js [forum](https://discourse.threejs.org) instead.
