### ISSUE TITLE
Threejs circular grid geometry, The one you created uses linesegments, 

### ISSUE THREAD

**Issue by ogeniuspriority** [mrdoob/three.js#16236]
Idea like making a plane mesh with subdivisions but that has various shapes like circular, trapesoid,

**Comment by Mugen87** [comment]
Can you please describe in more detail your feature request? It's not clear to me how the visual result should look like.

**Comment by ogeniuspriority** [comment]
Greetings,

I was making a water circular plane surface in a circular flask, After
adding water  waves using shaders, they were misbehaving, they only work on
a plane (rectangular) geometry cuz it's the one that has multiple lateral
and verticles subdivisions, So my idea would be to take a normal
(rectangular) plane and cut out a circular plane with lateral and verticles
subdivisions. It will be useful creating surfaces with lateral subdivisions
that are not only rectangular, for example the ring makes V only  shaped
surfaces which are no good when u try to simulate water surface, Even a
circular plane in the form of a concentrical rings and angled lines from
the center, would boost the potential of creating more awesome fluid
surface simulations. Like giving surface to the circular grid.

Thanks,
O'Genius Priority Ltd.
Empowering Genuine Welfare

**Comment by Mugen87** [comment]
Thanks for your explanation! However, this feature sounds a bit too application specific for a build-in geometry generator. At least from my point of view.

**Comment by mrdoob** [comment]
I agree.
