### ISSUE TITLE
GLTFExporter: Unable to export multi material object.

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#16263]
##### Description of the problem

If you import the following `OBJ` file into the editor, it looks like so:

[house.obj.zip](https://github.com/mrdoob/three.js/files/3084700/house.obj.zip)

![image](https://user-images.githubusercontent.com/12612165/56206035-a0e9c780-604b-11e9-9bd4-b19a5b16df8a.png)

If you now export to `glTF` and load it into a [glTF viewer](https://gltf-viewer.donmccurdy.com/), it seems certain parts of the model are missing:

![image](https://user-images.githubusercontent.com/12612165/56206468-c88d5f80-604c-11e9-96cc-496ef9003772.png)

The house model is a multi-material asset. It seems the exporter only respect the parts with the first material applied.

Original issue: https://discourse.threejs.org/t/scene-quality-doesnt-match-when-exported-compared-to-first-time-load-scene/7099

##### Three.js version

- [x] Dev
- [x] r103
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by takahirox** [comment]
I'm aware of the root issue but didn't have time to fix.

https://github.com/mrdoob/three.js/blob/dev/examples/js/exporters/GLTFExporter.js#L1361-L1370

`cachedData` key should take account of `group.start` and `group.count`, not only `geometry.index`.
