### ISSUE TITLE
WebVR stopped working on IOS version 12.2

### ISSUE THREAD

**Issue by giterium** [mrdoob/three.js#16266]
Stopped responding to position changes

**Comment by revyTH** [comment]
> Stopped responding to position changes

Yes, these are bad news from Apple. You have to enable orientation data manually in settings. And even doing that, you could have problems to access orientation data.

See [stackoverflow](https://stackoverflow.com/questions/55697528/ios-12-2-device-orientation-data-still-blocked-even-after-manual-enabling-in-se)

**Comment by Mugen87** [comment]
> And even doing that, you could have problems to access orientation data.

Meaning, you have to serve your app over https in order to have a secure context. In any event, there is nothing the `three.js` library can do here.
