### ISSUE TITLE
ReferenceError: 'ImageBitmap' is not defined

### ISSUE THREAD

**Issue by luk9like** [mrdoob/three.js#16274]
##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer (Edge)

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

In my Web Application users can upload a png-file. Then i want to set this image as Texture in my scene. It works fine on Chrome, FF and on Android. But Edge says  ERROR ReferenceError: 'ImageBitmap' is not defined. And on ios Nothing happens.

`const loader = new THREE.TextureLoader();
      if ( image === undefined ) { console.log( 'Texture is not valid!' ); }
      loader.load(image, (texture) => {
        const material = new THREE.MeshPhongMaterial({
          map: texture,
        });`
By removing the material the Object will be shown without the texture and without errors.

**Comment by mrdoob** [comment]
Can you create jsfiddle that shows the issue?

**Comment by Mugen87** [comment]
I assume the OP does not use the latest version of `three.js`. Please try it with `R103`.

**Comment by mrdoob** [comment]
Closing for now.

**Comment by ttracey93** [comment]
This is definitely still a thing. I'll work on a jsfiddle later.
