### ISSUE TITLE
Suggestion: Add .onPresentChange() to WebVR/XRManager

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#16277]
##### Description of the problem

**Background**

Users may want to do something when entering or existing VR mode. With WebVR API, they can use window's `vrdisplaypresentchange` event handler.

```javascript
window.addEventListener( 'vrdisplaypresentchange', function() {

    if( renderer.vr.isPresenting() ) {

        // entering VR mode

    } else {

        // existing from VR mode

    }

} );
```

With current WebXR API, it doesn't have `vrdisplaypresentchange` event. They need to watch `XRSession` method/event instead.

```javascript
session.requestFrameOfReference( ... ).then( function () {

    // entering VR mode

} );

session.addEventListener( 'end', function () {

    // existing from VR mode

} );
```

**Problem**

`WebXRManager` doesn't expose `session` so users can't touch `session`. Even if we expose, they need to watch two types of events one for `WebXR` and another for `WebVR`.

**Potential Solutions**

I'd like to suggest adding `onPresentChange` to `WebXR/VRManager`. It can hide the difference from users.

```javascript
// user code
renderer.vr.onPresentChange = function ( isPresenting ) {

    if ( isPresenting ) {

        ...

    } else {

        ...

    }

};

// WebXRManager
session.requestFrameOfReference( ... ).then( function () {

    ....

    this.onPresentChange( true );

} );

function onSessionEnd() {

    ....

    this.onPresentChange( false );

}

// WebVRManager
function onVRDisplayPresentChange() {

    .....

    this.onPresentChange( this.isPresenting() );

}
```

Looking good? Or any better solution ideas?

##### Three.js version

- [x] Dev
- [ ] r103
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Instead of making the user check a boolean, I think it'd be better to have explicit functions like `onStartSession` or `onEndSession`. Or dispatch events from `renderer.vr`.

**Comment by takahirox** [comment]
I like that idea. I'll make PR. No preference whether `onStart/EndSession` or dispatch events. Dispatch event so far because even if we want to add new event dispatching we don't need to add new methods.

**Comment by takahirox** [comment]
Made PR #16365
