### ISSUE TITLE
Can't pass null to WebGLRenderer.setRenderTarget() to set back to canvas in Typescript

### ISSUE THREAD

**Issue by garyo** [mrdoob/three.js#16281]
##### Description of the problem

I'm using typescript and three.js 0.103.0. I'm trying to reset the render target back to the canvas. 
The code looks like it wants a `null`, but the type decl doesn't accept `null`: it's declared as:
```typescript
  setRenderTarget(renderTarget?: RenderTarget, activeCubeFace?: number, 
    activeMipMapLevel?: number): void;
```
which means it has to be a valid RenderTarget or omitted (undefined). Omitting it (or passing undefined) causes an error later, here (in WebGLRenderer.js line 1200), where it specifically checks that it's not null (so undefined sneaks through):
```
		if ( _currentRenderTarget !== null ) {

			// Generate mipmap if we're using any kind of mipmap filtering

			textures.updateRenderTargetMipmap( _currentRenderTarget );

			// resolve multisample renderbuffers to a single-sample texture if necessary

			textures.updateMultisampleRenderTarget( _currentRenderTarget );

		}
```

Seems like the code there (and perhaps elsewhere?) should either be changed to `(if !_currentRenderTarget)`, or else `setRenderTarget` should always set `_currentRenderTarget` to null if it's undefined. (That seems better to me -- omitting the arg is clean.)

##### Three.js version

- [ ] Dev
- [ x] r103
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This is already fixe in `dev`, see #16086
