### ISSUE TITLE
Feature: (I could contribute) A "Protractor Helper"

### ISSUE THREAD

**Issue by RobertLRead** [mrdoob/three.js#16288]
Dear Awesome THREE.js contributors,

I needed an in-scene "protractor" that draws an arbitrary angle in three space; I've implemented a preliminary, poorly written version which can be seen here: [https://pubinv.github.io/segmented-helixes/index.html](https://pubinv.github.io/segmented-helixes/index.html).
Change "tau" to see the protractor move; there are other protractors in the scene as well.

![Screen Shot 2019-04-19 at 9 38 33 AM](https://user-images.githubusercontent.com/5296671/56428978-ee9e4400-6286-11e9-8997-798d0b467324.png)

Is this worth cleaning up and submitting a pull request for? It is not obvious it is of wide applicability, but if you need it you need it.

The interface would like something like:

```js
let A = new THREE.Vector3(20,-15,0);
let B = new THREE.Vector3(0,0,0);
let C = new THREE.Vector3(10,13,0);
let color = "green";
let label = "theta = ";

var protractorHelper = new THREE.ProtactorHelper( A,B,C, color, label

 );
scene.add( protractorHelper );
```

(I hope I am not violating some etiquette here---I don't want to invest the time in cleaning it up if nobody will ever use it.)

**Comment by WestLangley** [comment]
My personal view is this is a bit application-specific, but you could make it available on your github site for others to use. 

You could also showcase it on the three.js [forum](https://discourse.threejs.org).

**Comment by Mugen87** [comment]
Yes, other devs post similar projects in the forum now. The `Showcase` category seems to be well received by the community.

**Comment by mrdoob** [comment]
Agreed.
