### ISSUE TITLE
webgl2 example not using webgl2

### ISSUE THREAD

**Issue by aardgoose** [mrdoob/three.js#16299]
The example https://threejs.org/examples/#webgl2_loader_gltf
is not using webgl2 as its name etc indicates.

Is it planned to have a simpler method of requesting WebGL2 than passing in a canvas and context parameters?  eg version: "webgl2"|"webgl2"|"auto"?

##### Three.js version

- [X ] Dev
- [X] r103
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by fernandojsg** [comment]
I like the idea of using a parameter when creating the WebGLRenderer to define the context you would like to use, otherwise use `auto` as default (= using webgl2 if available, otherwise webgl1)

**Comment by Mugen87** [comment]
Yes, it's more consistent to request a WebGL2 for this example.

> Is it planned to have a simpler method of requesting WebGL2 than passing in a canvas and context parameters? eg version: "webgl2"|"webgl2"|"auto"?

The current workflow was discussed here: https://github.com/mrdoob/three.js/pull/13717#discussion_r186597492

In the meanwhile, I favor  @fernandojsg suggestion.

**Comment by Mugen87** [comment]
@aardgoose It's better to create a separate issue for the WebGL 2 context creation issue. This issue just tracked the missing WebGL 2 context in the example.
