### ISSUE TITLE
GLTFLoader texCoord

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#16297]
so it says in the code:
> console.warn( 'THREE.GLTFLoader: Custom UV sets in "' + this.name + '" extension not yet supported.' );

apart from it being not supported, it is supposed to be on mapDef:
![Screen Shot 2019-04-21 at 14 35 16 ](https://user-images.githubusercontent.com/242577/56468842-decb5f00-6442-11e9-96b6-98653cec1b97.png)

then, how would one even support it? hacking the shaders?

**Comment by donmccurdy** [comment]
See https://github.com/mrdoob/three.js/issues/12608.

> apart from it being not supported, it is supposed to be on mapDef:

The texture transform extension can override the texcoord of the mapdef, for reasons related to fallback behavior in older versions.

> then, how would one even support it? hacking the shaders?

Or something like https://github.com/mrdoob/three.js/pull/14572.
