### ISSUE TITLE
some problem with Raycaster. 

### ISSUE THREAD

**Issue by zl-cn** [mrdoob/three.js#16303]
I'm using threebox(https://github.com/peterqliu/threebox).
raycaster is not working as expected with version 0.103.0 or later. (https://github.com/peterqliu/threebox/blob/master/examples/raycaster.html)
but version 0.102.0 is ok.
modify Vector3.js to the version 0.102.0 solved this problem.
but it's not a good solution, hope some one can fix it.
---------------------------------------
diff --git a/src/math/Vector3.js b/src/math/Vector3.js
index aba02fea0..cffbdf94a 100644
--- a/src/math/Vector3.js
+++ b/src/math/Vector3.js
@@ -1,6 +1,6 @@
 import { _Math } from './Math.js';
 import { Quaternion } from './Quaternion.js';
+import { Matrix4 } from './Matrix4.js';

unproject: function ( camera ) {
 
-		return this.applyMatrix4( camera.projectionMatrixInverse ).applyMatrix4( camera.matrixWorld );
+		var matrix = new Matrix4();
+		//return this.applyMatrix4( camera.projectionMatrixInverse ).applyMatrix4( camera.matrixWorld );
+		return this.applyMatrix4( matrix.getInverse( camera.projectionMatrix ) ).applyMatrix4( camera.matrixWorld );
 
},

**Comment by Mugen87** [comment]
Please post this issue at `threebox`. In general, you can not use third party plugins with an arbitrary `three.js` version. The current supported version of `threebox` is `R94`.
