### ISSUE TITLE
Feature suggestion: Automatically fixes ESLint rules

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#16312]

**Comment by looeee** [comment]
Do you have some ideas on how to do this? Maybe we could add a script to package.json?

**Comment by gkjohnson** [comment]
You should be able to fix lint errors with the command line using `npm run lint -- --fix`, which runs eslint with the `--fix` argument.

**Comment by Mugen87** [comment]
@gkjohnson That works just fine. Another option is to properly configure your IDE/editor (e.g. VSCode) so it automatically fixes lint errors when saving a file.

**Comment by linbingquan** [comment]
- Install ESLint 
![image](https://user-images.githubusercontent.com/23699926/56867788-41f95a80-6a1c-11e9-83c8-b8f0f2b089e8.png)

- Auto Fix On Save
![image](https://user-images.githubusercontent.com/23699926/56867793-4887d200-6a1c-11e9-99c8-3a8002ca26b3.png)

**Comment by linbingquan** [comment]
VSCode setting
- Install ESLint 
![image](https://user-images.githubusercontent.com/23699926/56867788-41f95a80-6a1c-11e9-83c8-b8f0f2b089e8.png)

- Auto Fix On Save
![image](https://user-images.githubusercontent.com/23699926/56867793-4887d200-6a1c-11e9-99c8-3a8002ca26b3.png)
