### ISSUE TITLE
Suggestion: Mesh clone method support a "recursive" argument

### ISSUE THREAD

**Issue by yennyF** [mrdoob/three.js#16315]
Grettings!
if mesh inherits the method add children (from Object3D), its clone method should support taking a "recursive" argument or at least make the Mesh class consistent.

**Comment by Mugen87** [comment]
Some context: https://discourse.threejs.org/t/how-clone-a-mesh-without-its-descendants/7201

**Comment by gkjohnson** [comment]
This should be a pretty easy fix (though breaking if the current behavior is relied on anywhere). The real question is whether or not there's a reason Meshes are assumed to not have children. I don't think I have strong opinions either way.

**Comment by Mugen87** [comment]
I think this issue can be closed. Starting with #19471 classes like `Mesh` do not have overwritten `clone()` methods anymore. They all use the implementation of `Object3D`.
