### ISSUE TITLE
LoadingManger (in multi instance case) fails to fire onLoad.

### ISSUE THREAD

**Issue by msmcgillis** [mrdoob/three.js#16311]
##### Description of the problem

If you have multiple threejs objects on a page that each use LoadingManager only one of the objects will fire the LoadManager onLoad call back.

The problem is in the FileLoader in its load call. In the broken case all we do in the FileLoader load is:

```
if ( loading[ url ] !== undefined ) {

			loading[ url ].push( {

				onLoad: onLoad,
				onProgress: onProgress,
				onError: onError

			} );

			return;

		}
```

The above code causes a return without ever telling the different manager itemStart. Not exactly sure how you want to fix but the above needs to identify if different load requests come from different managers and if it is the first time for a particular manager trigger its itemStart then when the file is done we also need to trigger all the different managers itemEnd.

##### Three.js version

- [ ] Dev
- [X] r103
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

## example html to reproduce problem

```
<html>
<head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/103/three.js"></script>
<style>
#test1 {
  width: 200px;
  height: 200px;
}
#test2 {
  width: 200px;
  height: 200px;
}
</style>
</head>
<body>
  <div id="test1"></div>
  <div id="test2"></div>
</body>
<script>
class word {
  constructor(target) {
    this.scene  = new THREE.Scene();
    this.camera = new THREE.PerspectiveCamera( 75,
                  target.offsetWidth/target.offsetHeight, 0.1, 1000 );
    this.camera.position.z = 100;
    this.renderer = new THREE.WebGLRenderer({antialias:true});
    this.renderer.setSize( target.offsetWidth, target.offsetHeight );
    target.appendChild( this.renderer.domElement );

    this.scene.background = new THREE.Color(0xFFFFFF);
    var light = new THREE.AmbientLight(0xFFFFFF);
    this.scene.add(light);

    var manager = new THREE.LoadingManager();
    manager.onLoad = this.draw.bind(this);
    new THREE.FontLoader(manager).load("https://threejs.org/examples/fonts/optimer_bold.typeface.json",this.savefont.bind(this));
  }

  savefont(font) {
    this.font = font;
  }

  draw() {
    var geometry = new THREE.TextGeometry("Test",{
      font: this.font,
      size: 50,
      height: 1,
      curveSegments: 4
    });
    geometry.center();
    var material = new THREE.MeshLambertMaterial( { color: 0x0000EE } );
    var word = new THREE.Mesh( geometry, material );
    this.scene.add( word );
    this.render();
  }

  render() {
    requestAnimationFrame( this.render.bind(this) );
    this.renderer.render(this.scene,this.camera);
  }
}
new word(document.getElementById("test1"));
new word(document.getElementById("test2"));
</script>
</html>
```

**Comment by mrdoob** [comment]
Can you create a jsfiddle showing the issue?

**Comment by msmcgillis** [comment]
https://jsfiddle.net/r2ju6n0c/1/

That is a copy of the above html. Let me know if it isn't what you are after.

**Comment by Mugen87** [comment]
It seems this is a design limitation of `three.js`. `FileLoader` avoids duplicate requests by using a unique cache which is equal for all instances of `FileLoader`. This approach does not work if you using `LoadingManager` like in your application. Normally, you create a single `LoadingManager` in order to manage multiple requests using multiple loaders. The class is not intended to provide an additional `onLoad()` callback for normal requests. I suggest you refactor your code like so to avoid this issue:

https://jsfiddle.net/w5uyoqh6/

**Comment by msmcgillis** [comment]
That was a simple example to demonstrate the basic issue. In real code during init many different things are needed before rendering can begin: font, js, images, ...  So it would be nice if this just worked. The idea of refactoring wouldn't accomplish what is needed in the actual code.

So I either have to write my own LoadingManager that supports this or fix this Loading frame work to support.

Is this an enhancement that would be desired in three.js?

**Comment by Mugen87** [comment]
> Is this an enhancement that would be desired in three.js?

 You are right, the behavior is unexpected and confusing. I think it would be good to fix this limitation. Are you interested in doing a PR so the project can see how the changes would look like?

**Comment by msmcgillis** [comment]
I will take a closer look and see what I come up with.

**Comment by msmcgillis** [comment]
Just want to bounce thoughts to make sure I go down a path that is likely to be accepted.

Three modules use the cache:

FileLoader, ImageBitmapLoader, and ImageLoader.

All other loaders it looks like depend on those three.

Those three have very different load logic and a bunch of things I would say are inconsistent and possibly broken in them.

1. Only FileLoader has duplicate request code fix
2. Only FileLoader has onProgress support
3. FileLoader uses XMLHttpRequest
4. ImageLoader uses img object with event listeners (img object does not support onProgress from what I can tell)
5. ImageBitmapLoader uses fetch (fetch does not support onProgress from what I can tell)

My thinking is to push all the actual request/duplicate and general external call processing into the cache code so it is in one place to maintain and consistent and uses XMLHttpRequest for all requests so we can provide consistent support of all the manager and loader callbacks.

So those three loaders will have two functions (the current load will get split into two calls): load and cacheload (name matter? this is new) the load function will be very simple and basically just call the cache.get. The cache will do all the work based on cache.get parameters (will have more parameters not positive on all of them yet). Additional parameters will be required to track duplicate requests, and multiple managers.  The cache.get will either instantly call the loaders cacheload with the cached value or send off the request using XMLHttpRequest and once that request completes call all the appropriate loaders cacheload. cacheload will then perform all the things unique to the particular type of loader after we have the XMLHttpRequest results. The load call may also have a few unique things before calling the cache.get call won't be sure until I actually get this working.

The cache will also do all the manager book keeping callbacks and duplicate request callbacks when a XMLHttpRequest completes or when we already have the item cached and just return it.

Let me know if you have any concerns about the above. But that is what I'm currently working towards.

**Comment by msmcgillis** [comment]
I have some of this working or I at least fixed the problem that was causing my issue for the FileLoader (now working on the ImageLoader and  ImageBitmapLoader code). But take a look at this fiddle. This is a demonstration of the current threejs code for the above three identified loaders that use the Cache.

https://jsfiddle.net/kbzatx14/1/

1. Font is broken because of duplicate request code that is only in FileLoader.
2. ImageLoader only makes a single request I'm guessing this may be a Chrome optimization of some sort for the img tag.
3. ImageLoader does the img tag twice because it does not have duplicate request code.
4. ImageBitmapLoader is upside down.
5. ImageBitmapLoader makes two requests because it does not have duplicate request code.
6. Enabling the cache does not change any of the above behavior.
7. Only FileLoader supports dataURI (my thinking is support for this should be consistent for all three loaders)

Another thing confuses me about ImageBitmapLoader we have this in the documentation:

"Unlike FileLoader, ImageBitmapLoader does not avoid multiple concurrent requests to the same URL."

However it does have the same cache calls so in theory my thinking is it should avoid multiple concurrent requests. The reason it doesn't in my test case is it doesn't have the same duplicate request detection.

Again just want to confirm that my direction is the goal which is to make all three of these work consistently with regards to the cache. Side note with my current implementation even if the cache is off if a "duplicate requests occurs" where the code detects it those duplicates will all get handled with a single XMLHttpRequest call.

**Comment by Mugen87** [comment]
> Again just want to confirm that my direction is the goal which is to make all three of these work consistently with regards to the cache.

I'm not sure this is a good idea if you need to add a lot of code for this. Since `FileLoader`, `ImageLoader` and `ImageBitmapLoader` use different web APIs in loading resources, it's complicated to implement a consistent loading and caching process. I think it's better to just focus on the issue with `FileLoader` and `LoadingManager`.

BTW: `ImageBitmapLoader` works as expected. You have to define the image orientation with `setOption()`, see https://jsfiddle.net/oq0xus7v/

**Comment by msmcgillis** [comment]
Well I got the ImageLoader and FileLoader consistent but the ImageBitmapLoader created issues but I think I have those worked out as well had to spend some time figuring out how to best deal with the createBitmapImage promise consistently from a possible generic API for all loaders that use the cache.

But, my latest concern is along the following:

Suppose I have url/cache key https://fc.jenika.com/image/family/person.png now suppose I load that with ImageLoader and ImageBitmapLoader for different reasons. If we used the current cache as it is this will not work the ImageLoader caches an Image object the ImageBitmapLoader caches BitmapImage. Two very different things that are not interchangeable. Which ever is called first and stores its results in an enabled cache brakes the other. Similar issue if you tried to use the same key for some reason with FileLoader which would need to be yet another very different result in the cache.

I'm thinking ideally we still would like to only get that url once so we would cache the basic request in the cache. But then we need to cache separate values for each loader that directly uses the cache and manipulates the base results. Like imageLoader and imageBitmapLoader do. Make since?

I debated about making everything go through FileLoader as a first pass but then we would only ever cache the raw results and my impression is things like createBitmapImage can be fairly slow so it is a good idea to cache its results for future requests.

So far most of what I have done is just shuffling code around and working out how to swap fetch with XMLHttpRequest and replace the Image src loading with setting it from XMLHttpRequest result. We could decide to replace XMLHttpRequest with fetch but supporting onProgress with fetch is a little interesting and I'm really not sure about its browser compatibility. If I'm lucky I may have something to commit to my fork by end of tomorrow for you to look over.

Side note all I have been doing is modifying the src/loader/*.js files and ignoring all the *.ts files once I get the *.js working I will take a closer look at the *.ts stuff and see what needs to be done for it. But, I'm not real clear on how the *.ts files are getting used to validate them. Also not real clear on your approach to documentation or unit testing yet.

**Comment by msmcgillis** [comment]
See above commit for initial code changes. You can try this fiddle.

https://jsfiddle.net/k3xczf5h/

If you use chrome and open network panel you should see the two files only get loaded once over the network using xhr with the cache enabled. Then if you disable the cache you only request the files twice. Once for each of the group of loads.

Note: that is independent of actually requesting the image file 8 times with 8 different managers and loaders, and requesting the font file 4 times with 4 different managers and and loaders.

**Comment by msmcgillis** [comment]
I believe a number of bugs still exist in a few different situations so it isn't ready yet but this should allow you to see if this looks like a direction that you are OK with.

**Comment by Mugen87** [comment]
Many thanks for your work so far!

> replace the Image src loading with setting it from XMLHttpRequest result

`ImageLoader` used `FileLoader` once but that changes was reverted for various reasons, see https://github.com/mrdoob/three.js/issues/10439. I guess we will run in the same problems again if we go this route. What do you think?

**Comment by msmcgillis** [comment]
Hard for me to be sure with out a set of test cases to validate this new code against for those requirements. Do we have any?

For the list of 5 side effects what I have I think will be OK for 1, 2, and 4. But 3 and 5 are not something I have looked at and out of those I think svg will be OK but I don't follow the issue around 3 exactly to know what options to try and offer. To my thinking they should know the URL already they provided it to the load request.

From my read of most of the responses people ended up implementing work arounds that are effectively what I wrote but their solutions never dealt with the cache properly which my code tries to do consistently for all loaders. I think what I have is a much better start at resolving 10439 consistently but again test cases are key to knowing.

**Comment by msmcgillis** [comment]
See above commit for my latest code I think the three modules that use the Cache directly are now working well with the Cache doing all the work related to the Cache management.

Issues I ran into:

1. data uri - from my testing with Chrome, Firefox and Safari I couldn't see any value in special data uri processing. For all three browsers with current versions XMLHttpeRequest seems to do reasonable things with the data uri's i tested with.

2. ImageBitmapLoader - different behavior with browsers
    1. chrome loads images upside down on default
    2. firefox loads as expected on default
    3. safari does not support we only generate warnings my feeling is the init should error or something more significant but left as is

3. file uri - different behavior with browsers (local html file loading local loader files all on your system but getting the javascript from servers)
    1. chrome fails to load loader files with CORS errors (my 2c is this is a bug with chrome)
    2. firefox works as expected
    3. safari fails to load loader files with CORS errors (my 2c is this is a bug with safari)

    my thinking is if the html file is loaded with a file://... path and the loader requests use relative paths then the browser should treat those paths as relative to the html files location and if found correctly load it. In this case CORS should treat the html's file location as the "same server".

**Comment by msmcgillis** [comment]
The above commit includes changes that allow me to generate the three min version of javascript without having java. I use the standard node container to do my three.js work and it doesn't include java. The google-closure-compiler seems to support a javascript version when java isn't available, but has to be called using npx (I also had to change the language_in parameter).

I'm going to start using the above code with my applications to see if any other issues appear.

**Comment by msmcgillis** [comment]
For my fork I created a 16311 branch and moved all my changes to it so it will be easier for me to keep my dev fork in sync with the three.js dev branch.

https://github.com/msmcgillis/three.js/tree/16311
