### ISSUE TITLE
GLTFExporter: combine AO, metal & roughness into one texture

### ISSUE THREAD

**Issue by fernandojsg** [mrdoob/three.js#16325]
Some reference code: https://glitch.com/edit/#!/occlusion-roughness-metalness

Retrieving old discussion from : https://github.com/mrdoob/three.js/issues/14940

> Merging metal/rough/AO textures on the same texture on different channels is something we had in our plan for features to support in the GLTFExporter since the beginning. Actually I had it on my backlog but I have not had time yet to take a look at it :)
So I agree with @donmccurdy on the proposal as something we should support soon:

>> - If metal/rough textures are different and have different sizes, use one, skip the other, and log a warning.
>-  If metal/rough textures are different and have the same size: combine them
>> - If only one of metal/rough is present, export that.
>> - If AO has the same size as the (combined) metal/rough, merge its red channel into that image.

>And I'll add to the wishlist two things:
>- An option as `convertSizeWhenCombineTextures` so it will try to combine them by reescaling the ones with different size.
>- Comparing images to detect duplicates. This could be added on the exporting process itself or as a postprocess action including it on GLTFEXporter.Utils

**Comment by kowsheek** [comment]
We've been working on a shader-based solution which has been tricky so far, any luck with your implementation @fernandojsg?

**Comment by kolodi** [comment]
Any updates on this so far? 

> 
> 
> Some reference code: https://glitch.com/edit/#!/occlusion-roughness-metalness
> 

I just tested this solution based on canvases and it seems to be working.





> 
> 
> We've been working on a shader-based solution which has been tricky so far, any luck with your implementation @fernandojsg?

So maybe we should implement it as proposed by @fernandojsg just to close the feature gap in editor? Maybe someone has started to work on it?
