### ISSUE TITLE
Moving the camera model will shake if the coordinates are large

### ISSUE THREAD

**Issue by dytmh** [mrdoob/three.js#16324]
##### Description of the problem

Moving the camera model will shake if the coordinates are large

var position = new THREE.Vector3( 1000000, 0, - 100000 );

1. Geometry coordinates are large, model will shake
var box = new THREE.BoxBufferGeometry( 5, 5, 5 );
box.translate( position.x, 0, position.z );
var mesh = new THREE.Mesh( box );
scene.add( mesh );

2. But it's fine if you move the coordinates of the Mesh
var box = new THREE.BoxBufferGeometry( 5, 5, 5 );
var mesh = new THREE.Mesh( box );
mesh.position.x = position.x;
mesh.position.z = position.z;
scene.add( mesh );

I feel like only the modelViewMatrix is different.

My application needs to generate geometry on a large number of coordinates, and the origin of the model is keep at 0,0,0

##### Three.js version

- [ ] Dev
- [x] r103
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

This is the example
[webgl.zip](https://github.com/mrdoob/three.js/files/3111309/webgl.zip)

**Comment by Mugen87** [comment]
This happens because of floating point inaccuracies. Offsetting your geometry and camera far away from the origin is no good approach. Doing this is not only a problem in `three.js` but in other engines, too. Check out this video done with Unity: https://www.youtube.com/watch?v=G5UTyC6IpSI

**Comment by dytmh** [comment]
> 这是因为浮点不准确。将几何体和相机偏离原点是不好的方法。这样做不仅是一个问题，`three.js`而且在其他引擎中也是如此。观看使用Unity完成的视频：[https](https://www.youtube.com/watch?v=G5UTyC6IpSI)：[//www.youtube.com/watch？v = G5UTyC6IpSI](https://www.youtube.com/watch?v=G5UTyC6IpSI)。毛刺看起来与你的例子相似。

Hello, I do a gis big data visualization, I use InstancedBufferAttribute to generate a lot of coordinate points, InstancedBuffer is a very important optimization

**Comment by Mugen87** [comment]
I just wanted to say with my previous post that this issue needs to be handled on application level. `three.js` can't provide a fix for this.
