### ISSUE TITLE
readRenderTargetPixels not working with WebGLRenderTargetCube

### ISSUE THREAD

**Issue by throni3git** [mrdoob/three.js#16331]
##### Description of the problem

I've experienced that `readRenderTargetPixels` is not working with `WebGLRenderTargetCube`, e.g.

```js
renderer.setRenderTarget(RT, i);
renderer.readRenderTargetPixels(RT, 0, 0, RT.width, RT.height, pixelBuffer);
```

I guess the `setRenderTarget` call isn't having an effect. There is a getter in `readRenderTargetPixels` that returns an array of six `WebGLFramebuffer`.

```js
	this.readRenderTargetPixels = function ( renderTarget, x, y, width, height, buffer ) {

		if ( ! ( renderTarget && renderTarget.isWebGLRenderTarget ) ) {

			console.error( 'THREE.WebGLRenderer.readRenderTargetPixels: renderTarget is not THREE.WebGLRenderTarget.' );
			return;

		}

		var framebuffer = properties.get( renderTarget ).__webglFramebuffer;

		if ( framebuffer ) {

			var restore = false;

			if ( framebuffer !== _currentFramebuffer ) {

				_gl.bindFramebuffer( 36160, framebuffer );

				restore = true;

			}
```

What i'm trying to achieve is for a given cube envmap to extract the cube levels of detail coming from `PMREMGenerator` given in the HDR envmap examples. Are there any workarounds for this?

##### Three.js version

- [ ] r102

**Comment by mrdoob** [comment]
Can you create a jsfiddle?

**Comment by throni3git** [comment]
yeah, here is a fiddle: https://jsfiddle.net/throni3/zpuv1od0/
It gets you straight to the point, see comments.

**Comment by throni3git** [comment]
I have found a solution, that seems to work. I added a new parameter to `readRenderTargetPixels` which describes an index. Looks like this:

             this.readRenderTargetPixels = function ( renderTarget, x, y, width, height, buffer, activeCubeFaceIndex ) {

			if ( ! ( renderTarget && renderTarget.isWebGLRenderTarget ) ) {

				console.error( 'THREE.WebGLRenderer.readRenderTargetPixels: renderTarget is not THREE.WebGLRenderTarget.' );
				return;

			}

			var framebuffer = properties.get( renderTarget ).__webglFramebuffer;

			if ( activeCubeFaceIndex != undefined ) {

				framebuffer = framebuffer[ activeCubeFaceIndex ];

			}

			if ( framebuffer ) {

				var restore = false;

				if ( framebuffer !== _currentFramebuffer ) {

					_gl.bindFramebuffer( 36160, framebuffer );

					restore = true;

				}`

Is that something that can be integrated into the codebase or are there more adequate ways?

**Comment by WestLangley** [comment]
@throni3git I have tested your proposed change and it works for me.

I suggest you file a PR so @mrdoob can more easily see the diffs. I would support whatever he and @Mugen87  decide.
