### ISSUE TITLE
InstancedBufferGeometry: second material cannot read attributes on Intel GPU

### ISSUE THREAD

**Issue by govizlora** [mrdoob/three.js#16332]
##### Description of the problem

I created an InstancedBufferGeometry based on an ExtrudeBufferGeometry, and I wanted to assign different ShaderMaterial for the face and the side.

It worked on the discrete GPU on MacBook, but on MacBooks with only the integrated Intel GPU (or force use the intel GPU using [gfxcardstatus](https://gfx.io/)), the side material failed to read values from the InstancedBufferAttribute.

Live example: [jsfiddle](https://jsfiddle.net/govizlora/67c1ezk3/1/)
In this example, both the face and the side shares the same ShaderMaterial and they should all be red.

- On discrete GPU it looks correct:
<img width="576" alt="Screen Shot 2019-04-25 at 11 06 26 AM" src="https://user-images.githubusercontent.com/12785565/56758928-9797e380-674c-11e9-9549-936ecfa15046.png">

- But on intel GPU, the side cannot read the `offset` and `color` InstancedBufferAttribute:
<img width="592" alt="Screen Shot 2019-04-25 at 11 05 58 AM" src="https://user-images.githubusercontent.com/12785565/56758974-b1392b00-674c-11e9-85e6-d6c0cbd22ab2.png">

##### Three.js version

- [ ] Dev
- [x] r104
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Intel HD Graphics 630, Intel Iris Pro, Intel Iris Plus Graphics 650

**Comment by Mugen87** [comment]
Please execute the WebGL conformance test suite and share the failed tests in this thread:

https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html

**Comment by Mugen87** [comment]
Closing. Please report the issue a browser vendor or directly to Intel.
