### ISSUE TITLE
Consistently document class inheritance

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#16345]
It looks like some of the object inheritance is inconsistently display in the docs. [Box3Helper](https://threejs.org/docs/#api/en/helpers/Box3Helper) is listed as inheriting from just `LineSegments →` while the [SkinnedMesh](https://threejs.org/docs/#api/en/objects/SkinnedMesh) page displays the fully inheritance chain as `Object3D → Mesh →`. Is there a preferred format? I think I prefer showing the full inheritance chain so it's more immediately clear how an object can be used. In that case the Box3Helper page should display `Object3D → Line → LineSegments →`.

Would it be worth making a helper function to generate that list like the other links in the docs?

**Comment by mrdoob** [comment]
> Would it be worth making a helper function to generate that list like the other links in the docs?

Not sure... maybe easier to just easier to identify which are incomplete and fix them?
