### ISSUE TITLE
Performance issue when caching uniform arrays

### ISSUE THREAD

**Issue by fernandojsg** [mrdoob/three.js#16355]
When working on the Multiview PR https://github.com/mrdoob/three.js/pull/16316 I've noticed that updating array of matrices uniforms impact the performance quite a lot.
This is mainly because of the cache, checking both elements are the same and then copying the array if not, seems to be a hot spot.

I'll try to get some numbers to compare using cache vs not using for arrays. I believe it could be interesting to consider avoid caching arrays or maybe provide a way to define that you don't want to cache some uniforms if you already know they'll be changing per frame.

Looking at the Babylon's sourcecode it seems they just cache simple data https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/effect.ts#L1113-L1122 but not arrays https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/effect.ts#L1131-L1174.

So some ideas:
* Avoid using cache for Array uniforms
* Allow the user to define which uniforms must not use cache
* Add a new boolean param to `setValue` to force non-cache update, eg: `uniform.setValue(gl, 'name', [a,b], true)`

**Comment by Mugen87** [comment]
If the caching is really the source of the performance issue, I vote for option one and just avoid it in order to keep things simple.

**Comment by fernandojsg** [comment]
Duplicating the answer from the multiview PR:

> I have created a different branch to try to fix the performance issue introduced because of the cache of uniforms (Described in #16355)

> https://github.com/fernandojsg/three.js/commit/d35d296ee2cf2b49f3f36515d1c6be5c0c9d020f

> The performance difference between setting the uniforms "manually" and doing the flatten versus the standard version of calling uniforms.setValue results in the webgl_multiple_views_multiview example goes from 55ms measuring renderer.render() to 22ms...

> Removing the cache on `WebGLUniforms` for array of Matrix4 and Matrix3 will improve, around `~30ms`

**Comment by mrdoob** [comment]
I also vote for removing caching of Arrays and simplify things.
