### ISSUE TITLE
Usage for script tag in React environment (ShaderMaterial)

### ISSUE THREAD

**Issue by rjsgml5698** [mrdoob/three.js#16369]
##### Description of the problem

Hello!

I have something to ask. I need your help. I want to use ShaderMaterial in react.

I do not understand how to use react in the code below. I have tried many times but have not implemented it.

```
<script type="x-shader/x-vertex" id="vertexshader">

			attribute float scale;

			void main() {

				vec4 mvPosition = modelViewMatrix * vec4( position, 1.0 );

				gl_PointSize = scale * ( 300.0 / - mvPosition.z );

				gl_Position = projectionMatrix * mvPosition;

			}

</script>

```
```
<script type="x-shader/x-fragment" id="fragmentshader">

			uniform vec3 color;

			void main() {

				if ( length( gl_PointCoord - vec2( 0.5, 0.5 ) ) > 0.475 ) discard;

				gl_FragColor = vec4( color, 1.0 );

			}

</script>
```
I do not understand how to use the script tag in React environment. I've looked it up in stackoverflow, but I can not find anything useful.

I would really appreciate it if you let me know about it.

##### Three.js version

- [ ] Dev
- [x] r86
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

Thank you again.

**Comment by looeee** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests, and also include a complete code example demonstrating your problem. Snippets like you've included here are not enough to go on.

**Comment by rjsgml5698** [comment]
Ah, Okay

Thank you!
