### ISSUE TITLE
ArrayCamera: bounds vs viewport

### ISSUE THREAD

**Issue by fernandojsg** [mrdoob/three.js#16361]
On the `ArrayCamera` documentation currently we can read the following requirement:
https://github.com/mrdoob/three.js/blob/dev/docs/api/en/cameras/ArrayCamera.html#L17
```
It's mandatory to define for each sub camera the *bounds* property which determines the part of the viewport that is rendered with this camera.
```

But I just noticed that the `webgl_array_camera` example has changed from using `bounds` to `viewport`:
https://github.com/mrdoob/three.js/commit/7a4c9629d071c440dd990ad7b5036a0887a669e2#diff-4922b91cfbe857ae22c8196e08f64f00L40

While on `WebVRManager` we still use `bounds` to define each camera's viewport:
https://github.com/mrdoob/three.js/blob/dev/src/renderers/webvr/WebVRManager.js#L45-L49

I believe `bounds` is usually a better option as it could let us easily adapt the real viewport size when resizing the window or when changing between different RenderTargets (as we do on WebVR or when using [Multiview FBOs](https://github.com/mrdoob/three.js/pull/16316)).

@mrdoob do you mind clarifying this, if both options should be supported, or are you switching to use just one of them? Thanks!

**Comment by mrdoob** [comment]
As far as I remember... I added implemented `bounds` mainly influenced by the WebVR API. Then the WebXR API decided to provide absolute coordinates and that made me add `viewport`.

I agree that `bounds` is nicer conceptually. However, the benefit of `viewport` is that we can control at a pixel level every view. With bounds there were always gaps in-between views:

<img width="407" alt="Screen Shot 2019-04-30 at 11 01 42 AM" src="https://user-images.githubusercontent.com/97088/56982986-64cc6180-6b37-11e9-8d5a-fcee72bb03d1.png">

https://raw.githack.com/mrdoob/three.js/r90/examples/#webgl_camera_array
