### ISSUE TITLE
NodeMaterial: Incorrect RectAreaLight specular highlight

### ISSUE THREAD

**Issue by MEBoo** [mrdoob/three.js#16375]
I know that RectAreaLight can't cast shadows, and that's ok... but I have this problem

A scene with a single spotlight and a single area light (you can see its highlight on the floor)
![image](https://user-images.githubusercontent.com/39593253/57103577-7889ea80-6d26-11e9-9384-7915e029ad52.png)

The same scene with shadow casting enabled for the spotlight
![image](https://user-images.githubusercontent.com/39593253/57103723-d6b6cd80-6d26-11e9-879d-ac7588a77f8a.png)

what's wrong?

##### Three.js version

- [x]  Dev

**Comment by WestLangley** [comment]
It is best to redirect your question to the three.js [forum](https://discourse.threejs.org).

If you can provide a _live example_ demonstrating a bug in the _current three.js revision_, you may reopen this issue.

**Comment by MEBoo** [comment]
I've planned to update Three in a month, it's a bit complex since there are many changes I've to take care.

But if you are redirecting me to the forum, you say it isn't a bug.. maybe with the update the problem is already resolved.

**Comment by WestLangley** [comment]
>But if you are redirecting me to the forum, you say it isn't a bug.

I did not say that. I don't know if it is a bug.

I do know it is something I was not able to reproduce.

>Sorry, could you confirm me that the RectAreaLight can't and should not conflict with another light even if that one is casting shadows?

I would not expect such a conflict to occur.

**Comment by MEBoo** [comment]
Hi @WestLangley 
Here your Fiddle!

https://jsfiddle.net/9zkrbj2m/6/

The problem is when the specular highlight is on a NodeMaterial! 
Check the floor plane on my demo.
It works when If you use a normal material

**Comment by WestLangley** [comment]
@MEBoo Thanks for the fiddle.

It seems to me the `RectAreaLight` specular highlight is incorrect with `NodeMaterial` regardless of whether another light casts a shadow; toggling the shadow can amplify the error.

Data is being corrupted somewhere, apparently. I am not sure what is going on...

**Comment by sunag** [comment]
sorry delay... `RectAreaLightUniformsLib.js` modify native uniforms but nodematerial not use native uniforms... this bug is because of this `ltc_1` and `ltc_2` is not sended to uniforms. 
This example above fix this:

https://jsfiddle.net/8nhk975v/

```javascript
 material.onBeforeCompile2 = material.onBeforeCompile;
 material.onBeforeCompile = function ( shader, renderer ) {

	this.onBeforeCompile2( shader, renderer );

	this.uniforms.ltc_1 = { value: undefined };
	this.uniforms.ltc_2 = { value: undefined };

};
```

**Comment by WestLangley** [comment]
Also, due to #16777 in r.106, you also need to call
```js
THREE.RectAreaLightUniformsLib.init();
```

**Comment by sunag** [comment]
this PR fix this issue 
https://github.com/mrdoob/three.js/pull/16796
