### ISSUE TITLE
SimplifyModifier with OBJLoader - Loosing Texture UVs

### ISSUE THREAD

**Issue by yazancash** [mrdoob/three.js#16384]
Original Model :
[http://rigmodels.com/del/PFT7TOLW1O68QOYQM5AT957UC_1.jpg](http://rigmodels.com/del/PFT7TOLW1O68QOYQM5AT957UC_1.jpg)

After using SimplifyModifier :
[http://rigmodels.com/del/PFT7TOLW1O68QOYQM5AT957UC_2.jpg](http://rigmodels.com/del/PFT7TOLW1O68QOYQM5AT957UC_2.jpg)

Simplification function is working good, but sounds im loosing Texture UVs.

Code:
```
objLoader = new THREE.OBJLoader();
	objLoader.load('3dmodels/bear.obj', function (object) {
	object.traverse(function (child) {
		if (child instanceof THREE.Mesh) {
		child.material.side = THREE.DoubleSide;
		MeshGeometry = new THREE.Geometry().fromBufferGeometry( child.geometry );
		MeshGeometry.computeFaceNormals();
		MeshGeometry.mergeVertices();
		MeshGeometry.computeVertexNormals();

	var modifier = new THREE.SimplifyModifier();
        var simplified = modifier.modify(MeshGeometry, MeshGeometry.vertices.length * 0.85 | 0);
        simplified.computeFaceNormals();
        simplified.computeVertexNormals();

		material1 = child.material.clone();
		mesh = new THREE.Mesh(simplified, material1);
		scene.add(mesh);
		}
    });
```

##### Three.js version

- [ ] Dev
- [ ] r104
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
`THREE.SimplifyModifier` does not support geometries with texture coordinates so far. However, there is a related issue experimenting with this topic, see #14058

**Comment by yazancash** [comment]
Now SimplifyModifier function works with Textured models. Here is example:

[](https://rigmodels.com/3d_LOD.php?view=5OOOEWDBCBR630L4R438TGJCD)

you can extract [JS codes](https://rigmodels.com/css/SimplifyModifier.js) and use in your project.

**Comment by Mugen87** [comment]
Merging into #14058.

**Comment by Quost** [comment]
> Now SimplifyModifier function works with Textured models. Here is example:
> 
> https://rigmodels.com/3d_LOD.php?view=5OOOEWDBCBR630L4R438TGJCD
> 
> you can use this [JS code](https://rigmodels.com/css/SimplifyModifier.js) in your project.

Broken link. Do you still have it?
