### ISSUE TITLE
When presenting in VR/XR `camera.getWorldPosition()` is wrong

### ISSUE THREAD

**Issue by speigg** [mrdoob/three.js#16382]
When presenting in VR/XR, `camera.getWorldPosition()` (which internally calls `this.updateMatrixWorld( true )`) returns the incorrect value, because the underlying 
position/quaternion values are never updated to match the correct VR/XR pose stored in the local and world matrices.

For example, if the VR/XR camera is retrieved early (before calling `render`) in order to use the updated pose (e.g., for content layout purposes), that pose is lost as soon as `updateMatrixWorld` is called on the camera:

```js
// in render loop, while running in VR/XR:
const currentCamera = renderer.vr.getCamera(mainCamera)
// at this point, the matrix/matrixWorld of currentCamera and mainCamera 
// are the same, both of them based on the VR/XR pose
mainCamera.getWorldPosition() // resets based on position value
currentCamera.getWorldPosition()  // resets based on position value
// at this point, we have lost the VR/XR pose on both cameras, 
// and their respective poses may no longer match at all
// (their matrices will be fixed again when calling `render()`, but in 
// the meantime any calculations based on either camera pose,
// or their children, will be incorrect)
```

I believe `renderer.vr.getCamera` should actually decompose the VR/XR pose, updating the underlying position/quaternion values on both `mainCamera` and the resulting VR/XR camera. 

I see the value in `mainCamera` maintaining it's original pose when exiting VR/XR, however the above behavior seems confusing (and incorrect). If `renderer.vr.getCamera` is fixed as I describe, perhaps it should also remember & reset the `mainCamera` position/quaternion values back to their original values when exiting VR/XR presentation. Or perhaps it should just be the app's responsibility to restore a proper `mainCamera` pose when exiting VR/XR presentation. Either way, `getWorldPosition` and other calculations that depend on `updateMatrixWorld` should work correctly on these cameras when presenting in VR/XR.

**Comment by mrdoob** [comment]
You should be able to get the data you need from `camera.matrixWorld`.
