### ISSUE TITLE
controls always set _change flag to true.

### ISSUE THREAD

**Issue by iamnotstone** [mrdoob/three.js#16389]
##### Description of the problem
the code below in TrackBallControls or OrthgraphicTrackBallControls may lead to endless rendering in some project.

```
this.panCamera = ( function () {

		var mouseChange = new THREE.Vector2(),
			objectUp = new THREE.Vector3(),
			pan = new THREE.Vector3();

		return function panCamera() {

			mouseChange.copy( _panEnd ).sub( _panStart );


                      // here, this value may never be zero.  why not use a numerical small value? like:
                      // if( mouseChange.lengthSq() < 1e-9)
			if ( mouseChange.lengthSq() ) { 


				// Scale movement to keep clicked/dragged position under cursor
				var scale_x = ( _this.object.right - _this.object.left ) / _this.object.zoom;
				var scale_y = ( _this.object.top - _this.object.bottom ) / _this.object.zoom;
				mouseChange.x *= scale_x;
				mouseChange.y *= scale_y;

```

##### Three.js version

- [x] Dev
- [x] r104
- [] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Let's discuss this issue first in the forum. If it is a bug, you can reopen it.

https://discourse.threejs.org/t/controls-always-set-change-flag-to-true/7398
