### ISSUE TITLE
Examples: Vertex Animations from HoudiniFx Simulations to ThreeJS

### ISSUE THREAD

**Issue by sneha-belkhale** [mrdoob/three.js#16398]
Hey,

I recently worked on a tool to bring HoudiniFx simulations on soft and fluid bodies to render real-time on the browser with ThreeJS, building off of the work of [this project](https://vimeo.com/207832662). 

The basic technique is to store the position, normal, and color data of the animation in EXR textures, and update the vertices over time in the shader. Using EXR textures is necessary for precision. 

Here is a [live demo](https://codercat.tk/vertex-cache-aframe/) and [code](https://github.com/Kif11/three-body/blob/vertex-cache-demo/src/components/VertexCacheTextures.js)

I think this tool may be useful to other ThreeJS devs, so it would be cool to share with the community as an example, let me know your thoughts!

![vertex](https://user-images.githubusercontent.com/17795014/57319824-749c0500-7138-11e9-9a4a-4fe4182d5f25.gif)

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/16288#issuecomment-485298858

We recently tend to recommend the `Showcase` category on the forum for such demos. It seems you've already used this opportunity^^:

https://discourse.threejs.org/t/bringing-soft-and-fluid-body-vertex-animations-from-houdinifx-to-threejs/7411
