### ISSUE TITLE
TrackBallControl zooming on Ipad is not working properly

### ISSUE THREAD

**Issue by Mehraal** [mrdoob/three.js#16396]
I am working on the 3d image which has been implemented and working properly on all browsers on desktop but when I try it on iPad and other touch devices and try to zoom the object jumps out of the screen and I have to reload the image to get the object back. are there any solutions for it since it is working on the desktop?

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
