### ISSUE TITLE
MTL and OBJ and JPG problems with OBJLoader2 

### ISSUE THREAD

**Issue by alexs7** [mrdoob/three.js#16395]
There seems to be a problem when loading .obj files that have a .jpg, and a .mtl texture. I am using the example "webgl_loader_obj2" and I just changed these lines of code:

```
..
...
var onLoadMtl = function ( materials ) {
  objLoader.setModelName( modelName );
  objLoader.setMaterials( materials );
  objLoader.setLogging( true, true );
  objLoader.load( 'models/obj/my_scans/Model.obj', callbackOnLoad, null, null, null, false );
 };
 objLoader.loadMtl( 'models/obj/my_scans/Model.mtl', null, onLoadMtl );
...
..
```

as you can see to load "Model".

Now this renders fine in Meshlab, but on a browser it shows nothing.

The console shows no errors:

![Screenshot 2019-05-06 at 17 58 59](https://user-images.githubusercontent.com/1533281/57241384-c05f8900-7028-11e9-8bf5-39b8763380bf.png)

**Comment by yomboprime** [comment]
Please use [the forum](https://discourse.threejs.org/) for help requests.
Does the network tab show the loading of your model files? Perhaps it is not finding them.
Also, a complete fiddle helps people helping you.

**Comment by alexs7** [comment]
Network seems to be showing that everything is fetched. I will post the question over to the forums that you mentioned.
