### ISSUE TITLE
FBX 2018 format are shown all black without any error

### ISSUE THREAD

**Issue by saucebing** [mrdoob/three.js#16410]
I loaded a free model which is FBX 2018 format to threejs but it is shown all black without any error. I used the same code to load other two FBX 2018 format files and everything was fine, **even with animation**, which was played well with my code. I exported them using 3DS MAX so I am sure the version of the format. By the way, I also used https://discoverthreejs.com/apps/loader/ to test my model, which is also shown black, but the model is normal in autodesk 3DS MAX. The code, the screenshot and the model are attached below. And if I exported it to .obj it was still black.

` 

       // model
        var loader = new THREE.FBXLoader();
        var gra = this;
        loader.load( 'fbx_files/005/005_2.FBX', function ( object ) {

              if(object.animations && object.animations[0]) {
                gra.mixer = new THREE.AnimationMixer( object );
                var action = gra.mixer.clipAction( object.animations[ 0 ] );
                action.play();
              }

              object.traverse( function ( child ) {

                if ( child.isMesh ) {

                child.castShadow = true;
                child.receiveShadow = true;

                }

                } );
              object.scale.set(10000,10000,10000);
              object.position.y = 100;
              console.log(object);
              scene.add( object );
        } , onProgress = function(xhr) {
          console.log( ( xhr.loaded / xhr.total * 100 ) + '% loaded' );
        }, onError = function(e) {
          console.log(e);
        }
        );
`

<img width="1279" alt="Screenshot 2019-05-10 at 11 53 52" src="https://user-images.githubusercontent.com/4333044/57522357-63125300-731a-11e9-99ca-4b0a737dbccd.png">

<img width="1278" alt="Screenshot 2019-05-10 at 12 02 21" src="https://user-images.githubusercontent.com/4333044/57522986-9b666100-731b-11e9-897b-8cca5586e915.png">

The model (with two fbx files) are attached below:
[005.zip](https://github.com/mrdoob/three.js/files/3166138/005.zip)

##### Three.js version

- [x] Dev
- [ ] r104
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by saucebing** [comment]
Sorry for modifying so many times, I found it was visible but just all black so I couldn't recognize it easily. But what's the reason of the black? Does anyone can fix it?

**Comment by mrdoob** [comment]
Does that version of Maya support exporting to GLTF yet?

**Comment by saucebing** [comment]
> Does that version of Maya support exporting to GLTF yet?

Unfortunately, I have just 3DS MAX but no Maya so I can not export it to GLTF format. And the format that 3DS MAX supports are shown below:
![Screenshot 2019-05-10 at 19 49 01](https://user-images.githubusercontent.com/4333044/57550087-36cbf600-735d-11e9-8d56-a956099e7976.png)

If you have any suggestion, I can export it to any format it supports for you to test.

By the way, are developers in this project full-time or part-time? I am just curious and may consider to do some contributions if I have spare time.

**Comment by saucebing** [comment]
Oh, I found that 3DS MAX can install some plug-ins such as Babylon and then it might be able to export scene to glFT format. I will go to have a try and then give a feedback.

**Comment by saucebing** [comment]
Wonderful!!! I use 3DS MAX + Babylon Plugin to export my model to glTF 1.0 format. And the texture was shown quickly!! But colors are a much darker. I can use another plugin to export it to a file as glTF 2.0 format. Just wait to see what would happened.

**Comment by saucebing** [comment]
It has been glTF 2.0 yet. And I found that I can solve the darker color problem by increasing the light intensity. The problem has been solved perfectly! I would try to convert all of my models to glTF!! Thank you very much!! I will close this issue.
