### ISSUE TITLE
Intertia for OrbitControls

### ISSUE THREAD

**Issue by skizzo** [mrdoob/three.js#16414]
I just can't get my OrbitControls to behave like on SketchFab, which makes zooming/rotating/panning "slow down" and not just immediately stop when releasing mouse/touch. 

When the value for `dampingFactor` is e.g. 0.2, there is some slowing down happening, but the controls are **way** to sensitive. I don't need to rotate my model 10 times by swiping once from the left to the right.

When the value is higher than 1.4, the objects in the scene just "wiggle" every frame, which makes it completely unusable.

I found a StackOverflow question - [Inertia in OrbitControls from ThreeJS
](https://stackoverflow.com/questions/20285892/inertia-in-orbitcontrols-from-threejs) - but it's from 2013/2014, so since the code base changed a lot this doesn't do the trick any more.

Any ideas? Thanks.

**Comment by WestLangley** [comment]
Please redirect your question to the [three.js forum](https://discourse.threejs.org).
