### ISSUE TITLE
[TypeScript Support] Camera missing some properties.

### ISSUE THREAD

**Issue by Rubinhuang9239** [mrdoob/three.js#16428]
##### Description of the problem
```
       camera.aspect = window.innerWidth / window.innerHeight;
       camera.updateProjectionMatrix();
```

tsc will indicate
`Property 'aspect' does not exist on type 'Camera'`
and
`Property 'updateProjectionMatrix' does not exist on type 'Camera'`

which is not aligned with THREE documentation here:
https://threejs.org/docs/#api/en/cameras/PerspectiveCamera

I believe more properties is missing in the `Camera.d.ts`, or the typing is still in progress?

##### Three.js version

- [ ] Dev
- [x] r104
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> I believe more properties is missing in the Camera.d.ts, or the typing is still in progress?

It seems your are mixing `Camera` with `PerspectiveCamera`. The base class `Camera` does not have the property `aspect` and the method `updateProjectionMatrix()`. But `PerspectiveCamera` does.

https://github.com/mrdoob/three.js/blob/3ee4074c68a91c99c156de55ab71b000c9284ce7/src/cameras/PerspectiveCamera.d.ts#L35
https://github.com/mrdoob/three.js/blob/3ee4074c68a91c99c156de55ab71b000c9284ce7/src/cameras/PerspectiveCamera.d.ts#L116

**Comment by Rubinhuang9239** [comment]
Totally, thanks for that.

**Comment by ofersarid** [comment]
how do access the `PerspectiveCamera` class instead of just the `Camera` class ?

**Comment by lighthaus205** [comment]
Using typescript, the following worked for me, adding a type definition when retrieving the camera from useThree:

```javascript
const { camera }: { camera: THREE.PerspectiveCamera } = useThree();
``` 

Or you write it like this:

```javascript
const { camera } = useThree();
const perspectiveCamera = camera as THREE.PerspectiveCamera;
```
