### ISSUE TITLE
Inconsistent Default CORS Behavior for MTLLoader?

### ISSUE THREAD

**Issue by spenceryue** [mrdoob/three.js#16438]
**Problem:**
In [Line 168](https://github.com/mrdoob/three.js/blob/1bb18eb508323b80fe1c5b64265e7d6594167fff/examples/js/loaders/MTLLoader.js#L168) of `MTLLoader.js`:

	materialCreator.setCrossOrigin( this.crossOrigin );

`this.crossOrigin` is `undefined` by default for `THREE.MTLLoader`, so the default value given by `THREE.MTLLoader.MaterialCreator` at [line 210](https://github.com/mrdoob/three.js/blob/93e72ba7b24958ddb0652bd33171edd14ed2d693/examples/js/loaders/MTLLoader.js#L210):

	crossOrigin: 'anonymous',

is overwritten and ignored.

**Suggestion to Fix:**
Either `THREE.MTLLoader` should set a default value for `crossOrigin` as well or the `setCrossOrigin` method ([line 212](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/MTLLoader.js#L212)) of `THREE.MTLLoader.MaterialCreator` should return early for a null input.

**Comment by Mugen87** [comment]
I think it should be sufficient if `MTLLoader` defines `crossOrigin: 'anonymous',` for its prototype similar to `GLTFLoader` or `ColladaLoader`. Would you like to do a PR with the change.

**Comment by spenceryue** [comment]
Sure, I'll do a PR.
