### ISSUE TITLE
ColladaLoader: Throw error if xml fails to parse correctly

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#16443]
If a Collada file fails to parse as XML correctly the Collada loader tries to parse it anyway and gives less than helpful errors. Here is one of the models I was having trouble loading:

https://bitbucket.org/DataspeedInc/velodyne_simulator/src/master/velodyne_description/meshes/HDL32E_base.dae.

With the problematic lines being the following because arrow characters are used in an attribute:

```xml
<library_visual_scenes>
    <visual_scene id="Scene" name="Scene">
      <node id="<STL_BINARY>" name="<STL_BINARY>">
        <matrix>1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1</matrix>
```

The result is a partially-parsed xml document with a `<parsererror>` tag as the first child node in the `COLLADA` tag. In this case the partially-formed xml was invalid and caused the loader to fail but it could have failed silently and only loaded part of the model. This file does not load in Meshlab, either, and it looks like Assimp is the source of the invalid Collada file conversion: https://github.com/assimp/assimp/issues/823.

My suggestion would be to throw / log an error if a `<parsererror>` tag is present and return a `null` model. Thoughts?

**Comment by Mugen87** [comment]
> My suggestion would be to throw / log an error if a <parsererror> tag is present and return a null model.

That sounds good 👍 ! Would you like to make a PR with this change?

**Comment by gkjohnson** [comment]
Unfortunately for my use case I'm unable to manually update the Collada files or dictate that they not have these types of bad attributes from various exporters so if anyone comes across this wondering the same my solution has been to extend the ColladaLoader and sanitize the xml text before parsing:

```js
class CustomColladaLoader extends ColladaLoader {

    parse(text, path) {

        text = text.replace(/".+?"/g, match => {

            return match
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;');
        
        });
        return super.parse(text, path);

    }

}
```
