### ISSUE TITLE
Clipping a volume in Three.Js giving Black area instead of Inner Material

### ISSUE THREAD

**Issue by ayushGHub** [mrdoob/three.js#16455]
##### Description of the problem

I am trying to clip a volume from all three planes in ThreeJS to look into the inner structure. 

Clipping is done inspired and implemented in fragment shader by discarding the drawing of the pixel if it is beyond your clipping limit:

   	gl_FragColor  = accumulatedColor;
					
	if(worldSpaceCoords.x < xClippingPlaneMin) discard;
	if(worldSpaceCoords.x < xClippingPlaneMin) discard;
	if(worldSpaceCoords.z < zClippingPlaneMin) discard;
	if(worldSpaceCoords.z > zClippingPlaneMax) discard;
	if(worldSpaceCoords.y < yClippingPlaneMin) discard;
	if(worldSpaceCoords.y > yClippingPlaneMax) discard;
   
And have circulated the above information by passing through the shader material (Two pass Volume Rendering) as shown in below code.

    var materialFirstPass = new THREE.ShaderMaterial( {
					vertexShader: document.getElementById( 'vertexShaderFirstPass' ).textContent,
					fragmentShader: document.getElementById( 'fragmentShaderFirstPass' ).textContent,
					side: THREE.BackSide,
				
				} );
    materialSecondPass = new THREE.ShaderMaterial( {
					vertexShader: document.getElementById( 'vertexShaderSecondPass' ).textContent,
					fragmentShader: document.getElementById( 'fragmentShaderSecondPass' ).textContent,
					side: THREE.FrontSide,
					depthWrite: false,

	uniforms: {	tex:  { type: "t", value: rtTexture },
								cubeTex:  { type: "t", value: cubeTextures['bonsai'] },
								transferTex:  { type: "t", value: transferTexture },
								steps : {type: "1f" , value: guiControls.steps },
								alphaCorrection : {type: "1f" , value: guiControls.alphaCorrection },
								xClippingPlaneMin : {type: "1f" , value: guiControls.xClippingPlaneMin },
								xClippingPlaneMax : {type: "1f" , value: guiControls.xClippingPlaneMax },
								yClippingPlaneMin : {type: "1f" , value: guiControls.yClippingPlaneMin },
								yClippingPlaneMax : {type: "1f" , value: guiControls.yClippingPlaneMax },
								zClippingPlaneMin : {type: "1f" , value: guiControls.zClippingPlaneMin },
								zClippingPlaneMax : {type: "1f" , value: guiControls.zClippingPlaneMax }
							},
				 });

	sceneFirstPass = new THREE.Scene();
	sceneSecondPass = new THREE.Scene();

	var boxGeometry = new THREE.BoxGeometry(1.0, 1.0, 1.0);
	boxGeometry.doubleSided = true;

	var meshFirstPass = new THREE.Mesh( boxGeometry, materialFirstPass );
	var meshSecondPass = new THREE.Mesh( boxGeometry, materialSecondPass );

	sceneFirstPass.add( meshFirstPass );
	sceneSecondPass.add( meshSecondPass );

It looks something of this sort black boundary which I want to be the rendered surface.[![enter image description here][1]][1]
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/qiiX9.png
  [2]: https://i.stack.imgur.com/77lKq.png

This code is an extension of [lebarba's code ](http://www.lebarba.com/)
##### Three.js version

- [ ] Dev
- [ ] r104
- [x] r68

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Please redirect your question to the three.js [forum](https://discourse.threejs.org).
