### ISSUE TITLE
TypeScript: add customDepthMaterial and customDistanceMaterial to Object3D type definition

### ISSUE THREAD

**Issue by He3lixxx** [mrdoob/three.js#16474]
##### Description of the problem

In the documentation, [`customDepthMaterial`](https://threejs.org/docs/index.html#api/en/core/Object3D.customDepthMaterial) and [`customDistanceMaterial`](https://threejs.org/docs/index.html#api/en/core/Object3D.customDistanceMaterial) are listed as properties of `Object3D`. But they are not listed in the [corresponding type definition file](https://github.com/mrdoob/three.js/blob/dev/src/core/Object3D.d.ts) leading to type checking errors when using with typescript.

##### Three.js version

- [x] Dev
- [x] r104

**Comment by Mugen87** [comment]
Would you like to do a PR with the fix? 😇
