### ISSUE TITLE
Is this available: ARRenderer.js with three.js

### ISSUE THREAD

**Issue by Rcreators** [mrdoob/three.js#16470]
Hello,

I am using three.js from 1.5 years now and created a 3D ecommerce addon for wordpress with it. I am yet not sure is this question to post here or not but here it is. I was trying to find AR features work with Three.js from long time and as last week Google released AR for Web with model viewer, i am quite excited to implement it. So i dig into model viewer src from github and found this one in three-components.

ARRenderer.js

https://github.com/GoogleWebComponents/model-viewer/blob/master/src/three-components/ARRenderer.js

As it says created by MRDoob and other developers and using three.js to form AR scene. So i think Mrdoob already created AR part for thee.js but i am not able to find it on three.js doc or src directory to use it directly with three.js

Can anyone help me with is it right now available with three.js or it yet remains to implement ? Also if already available, can guide me to page where to look for doc and convert existing scene into AR. 

Thanks in advance.

**Comment by mrdoob** [comment]
We're still waiting for the [WebXR API](https://www.w3.org/TR/webxr/) to define the AR features and land in browsers. Until then, the only option to have some AR support is by interfacing with Android/iOS AR viewers like [model-viewer](https://github.com/GoogleWebComponents/model-viewer/) does.

**Comment by Rcreators** [comment]
Hello Mrdoob,

Does we have answer on this one now. Any helper class or anything added for threejs for AR ?

Also i found this one but its 2 year old. did it useful, if you aware of.  https://github.com/google-ar/three.ar.js

**Comment by Mugen87** [comment]
Related #15024 

@Rcreators Nothing has changed since May so experimenting with `three.ar.js` should be still the way to go.

**Comment by Rcreators** [comment]
Hello @mugen87,

Thanks for replying and adding to related topic. I saw your comment there as well. I already read this articles and post from Google and also read 2-3 article on directly using immersive-ar as well with native browser API. But none the article describes how to use already built threejs scene or canvas and add support for ar. That is why I am looking for ar extension for three.js specifically. If you have any link to share for same, please let me know. 

Thanks in advance.

**Comment by mrdoob** [comment]
We now have one official AR example:
https://threejs.org/examples/?q=webxr#webxr_ar_paint

**Comment by OliverXH** [comment]
@mrdoob 
Is there any use of WebXR introduction in three.js now?

**Comment by Mugen87** [comment]
Well, there is a simple guide that explains the setup of VR content:

https://threejs.org/docs/index.html#manual/en/introduction/How-to-create-VR-content

It could be a bit extended to cover AR specifics (like `ARButton`).
