### ISSUE TITLE
Typings for "examples" missing since migration from DefinitelyTyped

### ISSUE THREAD

**Issue by efokschaner** [mrdoob/three.js#16489]
##### Description of the problem
It seems that when Typings were moved from DefinitelyTyped in (https://github.com/mrdoob/three.js/pull/15597), the typings for some of the "examples" THREE components were missed.

Example of OrbitControls typings that used to exist: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34281/files#diff-5538b1e47ec97fd5b888c9f74edd522b

- Is there an existing plan or strategy for the typings of the "examples" section of three.js?
- Would I be welcome to make a pull request to add them?
- Is it fine if they are unconditionally part of the THREE module? Anything else might be tricky without changes to the examples themselves.

##### Three.js version
- [x] r104

##### Browser
N/A

##### OS
N/A

##### Hardware Requirements (graphics card, VR Device, ...)
N/A

**Comment by Mugen87** [comment]
Currently, more and more example files are converted to modules. You can find them in the `JSM` folder.

https://github.com/mrdoob/three.js/tree/dev/examples/jsm

When a file is converted, we normally add TS declaration files.

**Comment by efokschaner** [comment]
This is great! Somehow I missed this when trying to see what was going on. I'll try using the new modules and see if that works as expected.
