### ISSUE TITLE
Scenery with Points was not fully rendered

### ISSUE THREAD

**Issue by saucebing** [mrdoob/three.js#16484]
I followed example webgl_points_sprites to import snow in my scenery. But the scenery is not fully rendered at some angles. My code is nearly the same as the example except of updating scheme, which is 
`            

for ( var i = 0; i < scene.children.length; i ++ ) {
	var object = scene.children[ i ];
	if ( object instanceof THREE.Points ) {
		object.rotation.y = time * ( i < 4 ? i + 1 : - ( i + 1 ) );
		object.position.y -= 10 * (i + 1);
		if(object.position.y < this.ymin - this.ymax)
		object.position.y = this.ymax;
	}
}

`
The normal one should be:
<img width="1236" alt="Screenshot 2019-05-18 at 23 08 14" src="https://user-images.githubusercontent.com/4333044/57975581-a8421f00-79c3-11e9-8705-73f0d732fc62.png">

But when I changed the angle of my camera, snow didn't appear in front of the wall:
<img width="1239" alt="Screenshot 2019-05-18 at 23 08 32" src="https://user-images.githubusercontent.com/4333044/57975587-c3ad2a00-79c3-11e9-9fb4-98b594d86989.png">
<img width="1239" alt="Screenshot 2019-05-18 at 23 08 52" src="https://user-images.githubusercontent.com/4333044/57975592-d45da000-79c3-11e9-84e6-e1e5d0a68321.png">

In this screenshot, snow covered the two houses but still didn't cover the wall:
<img width="1238" alt="Screenshot 2019-05-18 at 23 32 16" src="https://user-images.githubusercontent.com/4333044/57975673-42569700-79c5-11e9-9409-0d2860b1932a.png">

In this one, it just covered the sky but if I change a little bit angle of my camera it became normal:
<img width="1239" alt="Screenshot 2019-05-18 at 23 36 45" src="https://user-images.githubusercontent.com/4333044/57975692-0d970f80-79c6-11e9-903e-0e9a3efe1457.png">

I tested in different directions and it all had such issue.

##### Three.js version

- [x] Dev
- [ ] r104
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Please redirect your question to the three.js [forum](https://discourse.threejs.org).
