### ISSUE TITLE
Translate documentation to another language

### ISSUE THREAD

**Issue by Mamboleoo** [mrdoob/three.js#16504]
Hi!
I'm interested in translating the documentations into French after noticing some of my students are sometimes struggling with English terms.

I wanted to know if there was a specific process for that and also a way to link a version of the translate page to the English one.
I mean, does every English page have a version number that could be linked to any translation so users know if the page he is currently reading in another language is up to date or not.

Thanks!

**Comment by mrdoob** [comment]
The setup is pretty simple.

https://github.com/mrdoob/three.js/tree/dev/docs/api

You can duplicate the `en` folder to `fr` and start translating.
Then you'd need to ad a `fr` option here:

https://github.com/mrdoob/three.js/blob/dev/docs/index.html#L32-L35

**Comment by Mamboleoo** [comment]
That's awesome!
I'll try to force myself to work a few hours a week on that 🙏
