### ISSUE TITLE
Docs: Broken formatting

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#16513]
![Screen Shot 2019-05-22 at 2 23 28 ](https://user-images.githubusercontent.com/242577/58138916-b482e200-7c38-11e9-94d7-3f81e0f14957.png)

https://threejs.org/docs/#api/en/extras/curves/EllipseCurve

**Comment by gkjohnson** [comment]
I'm not seeing that formatting in either dev or deployed. Everything looks good to me. What browser are you using?

**Comment by Mugen87** [comment]
> I'm not seeing that formatting in either dev or deployed

Same here. I've seen this once and the styles from the backend were not properly loaded. Probably a temporary server issue...

**Comment by makc** [comment]
> What browser are you using?

firefox

**Comment by makc** [comment]
it is actually better today. perhaps some script or css did not load yesterday.

![Screen Shot 2019-05-22 at 11 10 17 ](https://user-images.githubusercontent.com/242577/58162334-4c58ee00-7c82-11e9-8aa3-ed7e99866348.png)
