### ISSUE TITLE
SVG Renderer shows cracks in mesh spheres

### ISSUE THREAD

**Issue by nathancarter** [mrdoob/three.js#16540]
##### Description of problem

When I use the `SVGRenderer`, spheres look fine, unless I also include mesh lines in the scene, in which case spheres begin to show cracks.  Here is how to reproduce:

 1. Put the HTML code given below into `three/examples/svg-renderer-bug.html` (since it was copied from `examples/svg_lines.html`, so it references relative paths the same way that file does).
 2. Load it and notice the cracks between polygons in the sphere meshes, as in the following screenshot.  The topmost sphere is particularly bad.

![bad-spheres](https://user-images.githubusercontent.com/1316622/58269137-cff80500-7d7e-11e9-852d-b4f84bcac050.png)

 3. Comment out the section of code entitled "add lines," which adds the mesh lines.
 4. Reload the webpage and you will see no cracks any longer, as in the following screenshot.

![good-spheres](https://user-images.githubusercontent.com/1316622/58269144-d25a5f00-7d7e-11e9-9d2d-33bb2a46ae15.png)

```html
<!DOCTYPE html>
<html lang="en">
	<body>
		<!-- started with examples/svg_lines.html, so this assumes it's in the examples/ folder -->
		<script src="../build/three.js"></script>
		<script src="js/renderers/Projector.js"></script>
		<script src="js/renderers/SVGRenderer.js"></script>
		<script>
			// set up scene, and renderer
			const scene = new THREE.Scene();
			const renderer = new THREE.SVGRenderer();
			document.body.appendChild( renderer.domElement );
			renderer.setSize( window.innerWidth, window.innerHeight );
			// set up camera
			const camera = new THREE.PerspectiveCamera( 33, window.innerWidth / window.innerHeight, 0.1, 100 );
			camera.position.set( 4.4, 3.9, 2.3 );
			camera.lookAt( new THREE.Vector3( 0, 0, 0 ) );
			camera.updateProjectionMatrix();
			// add spheres
			addSphere = ( x, y, z ) => {
				const sphere = new THREE.Mesh(
					new THREE.SphereGeometry( 0.2, 16, 16 ),
					new THREE.MeshBasicMaterial( {
						color : new THREE.Color( 0.5, 0.5, 0.5 )
					} ) );
				sphere.translateX( x )
					  .translateY( y )
					  .translateZ( z );
				scene.add( sphere );
			}
			for ( var i = -1 ; i <= 1 ; i += 1 )
				for ( var j = -1 ; j <= 1 ; j += 1 )
					for ( var k = -1 ; k <= 1 ; k += 1 )
						addSphere( i, j, k );
			// add lines (the section you comment out to make the bug go away)
			addLine = ( x1, y1, z1, x2, y2, z2 ) => {
		        var geometry = new THREE.BufferGeometry();
		        geometry.addAttribute( 'position',
		            new THREE.Float32BufferAttribute( [ x1, y1, z1, x2, y2, z2 ], 3 ) );
		        scene.add( new THREE.Line( geometry,
		            new THREE.LineBasicMaterial( { color : '#0000ff', linewidth : 5 } ) ) );
			}
			for ( var i = -1 ; i <= 1 ; i += 1 ) {
				for ( var j = -1 ; j <= 1 ; j += 1 ) {
					addLine( i, j, -1, i, j, 1 );
					addLine( i, -1, j, i, 1, j );
					addLine( -1, i, j, 1, i, j );
				}
			}
			// render
			renderer.render( scene, camera );
		</script>
	</body>
</html>
```

##### Three.js version

- [ ] Dev
- [x] r104
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

I tested on just one machine, a MacBook Pro 15" from 3 years ago.  I do not know about other setups.

**Comment by Mugen87** [comment]
Live example with your code: https://jsfiddle.net/d1v46rhb/3/

I can actually reproduce on macOS with latest Chrome and Firefox.

BTW: Calling `camera.updateProjectionMatrix();` is not necessary when you only change the 3D transformation (e.g. via `lookAt())`.

**Comment by WestLangley** [comment]
The artifacts appear to occur only at distances further from the camera.

It also occurs if lines are present and line width is zero.

Fiddle with OrbitControls: https://jsfiddle.net/t189yjpx/

Tested in macOS - Chrome and Safari.

**Comment by WestLangley** [comment]
Adding overdraw support in #16541 seems to fix this, but I am not sure why the presence of lines in the scene would have any impact.

![Screen Shot 2019-05-23 at 7 22 49 PM](https://user-images.githubusercontent.com/1000017/58292759-97612700-7d90-11e9-809e-b7380e41d7f4.png)
