### ISSUE TITLE
WebVR and WebXR 

### ISSUE THREAD

**Issue by mvilledieu** [mrdoob/three.js#16551]
Hi, 

Devices like the Magic Leap One will be adding support for both WebVR and WebXR in the near future. Right now as you all know, if the implemented version of WebXR API doesn't match the right version of the Browser, it results in broken WebXR API calls. Even if technically `('xr' in navigator)` does exist. The issue with that specific test happening in the `WebGLRenderer` 

https://github.com/mrdoob/three.js/blob/880abcfb33801112211f8560d1910bbdc0246757/src/renderers/WebGLRenderer.js#L313

is that there is no way for a device that supports both WebXR and WebVR to specifically request the `renderer.vr` to be initialized using the `WebVRManager` and not `WebXRManager`. This becomes an issue when WebXR is constantly evolving and breaking changes are being introduced at every update like it currently is. 

**Example:**

Currently, if WebXR is broken, and I decide to start the immersive session using WebVR rather than WebXR by for example commenting out the `if('xr' in navigator){}` code in here:

https://github.com/mrdoob/three.js/blob/93e72ba7b24958ddb0652bd33171edd14ed2d693/examples/js/vr/WebVR.js#L134-L197

The `renderer.vr` has at this point already been initialized with the`WebXRManager` in place of the needed `WebVRManager` because of that test:

https://github.com/mrdoob/three.js/blob/880abcfb33801112211f8560d1910bbdc0246757/src/renderers/WebGLRenderer.js#L313

 and cause the WebVR session to not work on not start.

**Propositions:** 

Devs should be able to specify if they want their renderer to be initialized with `XR` or `VR`. This way they could be requesting the stable WebVR API rather than getting stuck with WebXR just because their device supports WebXR in appearance. 

Here are the solutions I propose, let me know what you guys think:

- Rather trying to initialize WebXR first if `('xr' in navigator)` and WebVR if it is not the case. We could do the opposite, by first trying to initialized WebVR if `'getVRDisplays' in navigator`. 

**Pros:** WebVR is currently stable, not WebXR. 
**Cons:** At this point, people with devices that support both WebXR, and WebVR, would be stuck with WebVR, the same way they are currently stuck with WebXR. 

- Make an exception for the MagicLeap device based on the user agent. We could test against the user agent and make sure while the WebXR API is not entirely stable to force running WebVR. 

**Pros:** Would always work running the stable WebVR API. 
**Cons:** Dirty exception for one specific device, not sustainable if every company does that.

-  Refractoring the `WebGLRenderer` to be able to force initializing it using the WebXRManager, or the WebVRManager, it could be a parameter we pass to the Class.

**Comment by mrdoob** [comment]
#16552
