### ISSUE TITLE
LineDashedMaterial ignores gapsize and dashsize for the last drawn line in a LineLoop

### ISSUE THREAD

**Issue by soadzoor** [mrdoob/three.js#16589]
##### Description of the problem

I wanted to create a dashed square with LineLoop, but the last drawn line (from 4 to 1) is not affected by the gapsize and dashsize I provide at the LineDashedMaterial.

![Capture](https://user-images.githubusercontent.com/10392261/58509731-8a30a780-8197-11e9-8251-d2243db7beb5.PNG)

See this example: https://jsfiddle.net/soadzoor/6c1L52qo/2/

I know a workaround that would probably work: using a `Line` instead of `LineLoop` and provide a 5th vertex with the same values as the 1st vertex, but it's not very nice.

I might take a look at this, and try to find a solution myself in the following days, but feel free to share your thoughts.

##### Three.js version

- [x] Dev
- [x] r104

##### Browser

- [x] All of them

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
This is a webGL limitation. `geometry.attributes.lineDistance.array[ 0 ]` would need two values for that to work: zero at the start, and the line length at the end.

>using a Line instead of LineLoop and provide a 5th vertex with the same values as the 1st vertex

That is the solution.

**Comment by soadzoor** [comment]
> This is a webGL limitation. `geometry.attributes.lineDistance.array[ 0 ]` would need two values for that to work: zero at the start, and the line length at the end.

Couldn't we push another value to that array and tell the renderer to use that for the last line?

Or if it's really impossible, then I think we should mimic `LineLoop` with `Line` under the hood in case the material is `LineDashedMaterial`, or something.

**Comment by Mugen87** [comment]
> we should mimic LineLoop with Line under the hood in case the material is LineDashedMaterial, or something.

Since there is a valid workaround for this problem (using `THREE.Line`), I suggest to close the issue and mark it as `Won't fix`.
