### ISSUE TITLE
FBXLoader: Inflate.min.js required

### ISSUE THREAD

**Issue by jiawenquan** [mrdoob/three.js#16602]
```
import {FBXLoader} from "three/examples/jsm/loaders/FBXLoader";
      
      const objLoader = new FBXLoader();
      // TODO: Add error handling.
      objLoader.load(file, async (object: any) => {
      scene.add(object);
      });
```

error： `THREE.FBXLoader: External library Inflate.min.js required, obtain or import from https://github.com/imaya/zlib.js`

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
`inflate.min.js` is currently not available as a module so you have to import it via the script tag like so:
```js
<script src="libs/inflate.min.js"></script>
```

**Comment by jiawenquan** [comment]
thank you
