### ISSUE TITLE
Consolidate text formatting in Documentation 

### ISSUE THREAD

**Issue by yuinchien** [mrdoob/three.js#16619]
##### Description of the problem
Currently the text formatting is inconsistent and introduces irregular spacings in the article. This creates problem for having clear & consistent type hierarchy, which is important for users to parse information quickly.

- Example 1: the `<br>` tag after `<h1> ` at the top of the article is unnecessary, the extra spacing doesn't look good. 
![Screen Shot 2019-05-30 at 11 06 30 AM](https://user-images.githubusercontent.com/406636/58654100-03311b80-82cc-11e9-8337-2608556830d0.png)
 
- Example 2: This page has double `<br>` tags in single paragraph, the formatting creates unnecessary gaps.
![Screen Shot 2019-05-30 at 11 09 33 AM](https://user-images.githubusercontent.com/406636/58654118-104e0a80-82cc-11e9-8a1b-11dbdbe91ca0.png)

- Example 3: The paragraph bellow `<h2>Constructor<h2>` is missing `<p>` tag, and results in very tight spacing.
![Screen Shot 2019-05-30 at 11 23 04 AM](https://user-images.githubusercontent.com/406636/58654860-b3ebea80-82cd-11e9-9d3d-dbf57e658b35.png)

Recommendation: avoid `<br>` globally when formatting content, use `<h1> <h2> <h3> <p>` properly to create clear type hierarchy.

**Comment by AlokTakshak** [comment]
@mrdoob  i would like to contribute , can you explain what all needs to be done.

**Comment by Mugen87** [comment]
After a series of PRs, the formatting of the doc pages should be more consistent now. There are still a few differences across the pages (e.g. the way how parameters are documented) but the general formatting should be definitely improved compared to May 2019.
