### ISSUE TITLE
Missing Vector2 import in Triangle.d.ts

### ISSUE THREAD

**Issue by spassvogel** [mrdoob/three.js#16617]
I'm having some troubles running the latest (r105) threejs from npm. Basically the typescript compiler complains that `src\math\Triangle.d.ts` is missing an import for Vector2. If I add this import myself the error goes away.

##### Three.js version

- [ ] Dev
- [x] r105

**Comment by Mugen87** [comment]
There is already a fix for this bug, see #16616
