### ISSUE TITLE
Page loading blank

### ISSUE THREAD

**Issue by 1097364388** [mrdoob/three.js#16629]
##### Description of the problem
https://threejs.org/examples/#canvas_geometry_cube
this page loading blank, console.error:
(index):165 Uncaught TypeError: Cannot read property 'classList' of undefined
    at selectFile ((index):165)
    at loadFile ((index):156)
    at (index):183

##### Three.js version

- [ ] Dev
- [x] r105
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
![Snipaste_2019-05-31_17-16-17](https://user-images.githubusercontent.com/23415941/58697033-65bd1100-83cb-11e9-8e66-0e8e13fd96ab.png)

- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
`CanvasRenderer` and the respective examples were removed with `R98` last year, see #15029
