### ISSUE TITLE
Documentation: Broken WebGL2 Site Link

### ISSUE THREAD

**Issue by cfrenchi** [mrdoob/three.js#16631]
I have been trying to get familiar with three.js and while reading the documentation on threejs.org under [WebGL2](https://threejs.org/docs/index.html#manual/en/introduction/How-to-use-WebGL2) , the link at the bottom for the example of [WebGL2 / materials / texture3d / volume](https://threejs.org/examples/#webgl2_materials_texture3d_volume) doesn’t display and makes the div panel - div contentWrapper - div content upset when the link is followed.

Looking into this more, it looks like there is no html file linked in the debugger. Attached are two images, one that is working and the one mentioned above that is not. I’m not getting a 404, just a white screen. Perhaps this was removed and the link just needs to be deleted from WebGL2 ? Checking the github, I see no reference to this file in the examples. Perhaps it was renamed?

![error](https://user-images.githubusercontent.com/10055468/58705614-b9a10900-837d-11e9-85c9-b35c5de42e20.PNG)

![working](https://user-images.githubusercontent.com/10055468/58705624-c32a7100-837d-11e9-800a-65d23fb14fde.PNG)

@looeee provided the correct example link on discourse as https://threejs.org/examples/#webgl2_materials_texture3d with a mention of the site design changes and the handling of incorrect URLs possibly at play.

##### Three.js version

- [ ] Dev
- [ ] r105
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Fixed via 153574b57f3a3e4c16315b45f5b7733cf46cb169:

see https://raw.githack.com/mrdoob/three.js/dev/docs/index.html#manual/en/introduction/How-to-use-WebGL2

**Comment by Mugen87** [comment]
@arpu Thanks for reporting! Fixing...
