### ISSUE TITLE
 three.js  Material  `Albedo`  Texture  is not found

### ISSUE THREAD

**Issue by jiawenquan** [mrdoob/three.js#16632]
##### Description of the problem

I want to create use a PBR material,
but three.js  Material  `Albedo`  Texture  is not found
 

##### Three.js version

- [x] Dev
- [x] r105

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by donmccurdy** [comment]
Please share a demo or code to reproduce the problem. What is the exact result you are seeing?

**Comment by Mugen87** [comment]
Maybe he ist just looking for [MeshStandardMaterial.map](https://threejs.org/docs/index.html#api/en/materials/MeshStandardMaterial.map)?

**Comment by WestLangley** [comment]
In three.js, `material.map` is the albedo map.

**Comment by jiawenquan** [comment]
[bingxiang.zip](https://github.com/mrdoob/three.js/files/3245641/bingxiang.zip)
this Texture is `Fridge_AlbedoTransparency.png`,

**Comment by mrdoob** [comment]
@jiawenquan use that texture as `material.map` and set `material.transparent = true`.
