### ISSUE TITLE
Keyboard keys break in examples after clicking "View Source Code" button

### ISSUE THREAD

**Issue by PaulKElliott** [mrdoob/three.js#16636]
#### Description of the problem

Keyboard keys break in examples after clicking "View Source Code" button in lower right.  No big deal.

Reproduce:

Go here
https://threejs.org/examples/?q=con#misc_controls_orbit
or here
https://threejs.org/examples/?q=con#webgl_shadowmap

Click View Source button in lower right.  Switch tab back to the example.  Try pressing a keyboard key that should do something.

Also, seems Example keyboard key controls don't ever work in Edge browser.

##### Three.js version

- [ ] Dev
- [x] r105
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by cfrenchi** [comment]
I can recreate this problem on Firefox and Chrome. 

However, after clicking source, if I go back to the example page and press tab until I return back to the canvas, the controls come back. 

It seems that the keys are trying to be applied to the button after clicking source.
When you go to a fresh page like the one that @PaulKElliott linked, pressing enter does nothing. 
Clicking source and then returning to the examples tab, pressing enter opens a new github source window. It seems that that element is still selected after clicking it.

**Comment by cfrenchi** [comment]
Taking a look at the a href that is acting like a button, adding in an onlick to focus on the iframe seems to solve the problem.

<a id="button" target="_blank" style="" href="https://github.com/mrdoob/three.js/blob/master/examples/webgl_animation_cloth.html" title="View source code for animation<span class=&quot;spacer&quot;>/</span>cloth on GitHub" **onclick="document.getElementById('viewer').focus();"**>tewst
</a>

Looking at the creation script where the button is being generated is probably the best place to create this and actually call a function as opposed to putting js right into the html. Above is a work around to see if this would solve the problem when testing in firefox inspector.

**Comment by Mugen87** [comment]
> This seems to also trigger when a user clicks the search bar after an example is loaded.

It also happens when you click at any polace on the side navigation. As soon as the iframe looses the focus, keyboard input does not work anymore. 

In some sense, this is a restriction of executing the examples in iframes. I personally would not start to adding selective fixes for this but just accept it as a limitation.

**Comment by mrdoob** [comment]
> I personally would not start to adding selective fixes/hacks for this but just accept it as a limitation.

Agreed 👍
