### ISSUE TITLE
GLTFLoader: Animation samplers don't handle normalized accessors correctly

### ISSUE THREAD

**Issue by zeux** [mrdoob/three.js#16658]
GLTF spec says that for rotation and weights animations, values may contain BYTE/SHORT normalized values. However, they aren't supported correctly by three.js.

What happens right now is that we create (for example) QuaternionKeyframeTrack, which ends up calling AnimationUtils.convertArray which simply creates a new Float32Array without normalizing the values.

I would like to fix it but I'm not sure where the best place to fix this is. Should GLTFLoader convert the output accessor to Float32Array manually, or is it better to add normalized input array support to various keyframe tracks?

**Comment by donmccurdy** [comment]
Thanks for raising these issues. My feeling is that GLTFLoader should probably convert the output accessors to Float32Array manually, as trying to add an abstraction around the places these arrays are accessed in a KeyframeTrack would likely have negative performance implications that outweigh the memory use. Open to other suggestions, though!
