### ISSUE TITLE
ShaderMaterial with { lights: true } requires user to define all uniforms manually

### ISSUE THREAD

**Issue by Gollum999** [mrdoob/three.js#16656]
##### Description of the problem

If you set `lights: true` when creating a `ShaderMaterial`, the material will break with the following error:

    Uncaught TypeError: Cannot set property 'value' of undefined

This can be fixed by manually defining all of the uniforms that `ShaderMaterial` expects, e.g.

    uniforms: {
        ambientLightColor: { value: null },
        lightProbe: { value: null },
        directionalLights: { value: null },
        spotLights: { value: null },
        rectAreaLights: { value: null },
        pointLights: { value: null },
        hemisphereLights: { value: null },
        directionalShadowMap: { value: null },
        directionalShadowMatrix: { value: null },
        spotShadowMap: { value: null },
        spotShadowMatrix: { value: null },
        pointShadowMap: { value: null },
        pointShadowMatrix: { value: null },
    }

Assuming I'm not missing some step that merges those uniforms in automatically.  I couldn't find mention of this behavior in the docs anywhere, and other uniform-passing properties like `clipping` and `fog` don't seem to have this problem.  The uniforms above also aren't listed under [WebGLProgram](https://threejs.org/docs/#api/en/renderers/webgl/WebGLProgram) (which maybe makes sense since they aren't automatically injected).

[CodePen example](https://codepen.io/gollum999/pen/vwbOQP)

##### Three.js version

- [x] Dev
- [x] r105
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

None

**Comment by WestLangley** [comment]
Please redirect your question to the three.js [forum](https://discourse.threejs.org).

**Comment by WestLangley** [comment]
```js
var uniforms = THREE.UniformsUtils.merge( [

	THREE.UniformsLib[ "lights" ],
	// ...

] );
```

**Comment by Gollum999** [comment]
Thanks for the snippet, that seems to work.

So I take it that this behavior is by design?  In that case, is it mentioned in the docs anywhere?

**Comment by Mugen87** [comment]
> In that case, is it mentioned in the docs anywhere?

Nope. However, a note code be added here: https://threejs.org/docs/index.html#api/en/materials/ShaderMaterial.lights
