### ISSUE TITLE
How can i render a diamond with refraction?

### ISSUE THREAD

**Issue by twlick** [mrdoob/three.js#16665]
I am trying a render a diamond with three js. I tried using refraction envMap but the result is not so good. I tried using the texture of the diamond itself. But it looks more like a glass in diamond shape. i also tried the fresnel shader but the result is not even near what i expect

Can anyone suggest me way do it correctly?

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
