### ISSUE TITLE
Can the console message "THREE.WebGLRenderer 105" be optional?

### ISSUE THREAD

**Issue by orassayag** [mrdoob/three.js#16682]
##### Description of the problem

I don't need to see the version on console, it's annoying.
Thanks.

**Comment by WestLangley** [comment]
#5835

**Comment by orassayag** [comment]
I tried to do:
```
	const renderer = new THREE.WebGLRenderer({
		logging: false
	});
```
But it's not working... any other ideas?

**Comment by Mugen87** [comment]
As mentioned in the PR, it's not possible to suppress logging.

**Comment by raiskila** [comment]
That PR seems to be a 404. Where is this currently discussed?
