### ISSUE TITLE
About the memory usage of the DRACOLoader

### ISSUE THREAD

**Issue by Ouyang-Zhaoxing** [mrdoob/three.js#16681]
##### Description of the problem

Describe the bug or feature request in detail.

[DRACOLoader](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/DRACOLoader.js)

DRACOLoader seems to have a problem, using it to load the model will make the memory footprint very high, I used the same model to test separately. I don't understand the principle of DRACO. If such memory usage is normal, I hope someone can tell me why.

##### Three.js version

- [x] Dev
- [x] r105
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
@Ouyang-Zhaoxing you can call `DRACOLoader.releaseDecoderModule()` to deallocate the WASM decoder library and free its memory. Alternatively you could try [running Draco on a worker](https://github.com/mrdoob/three.js/pull/15249) to move those costs off the main thread. In any case, the Draco decoder itself is not maintained here – for help with that I'd suggest the Draco repository or mailing list, there may be options like [preallocating memory](https://github.com/google/draco#javascript-decoder-performance). For help with the threejs wrapper, I'd recommend the forums.
