### ISSUE TITLE
fbx2threejs export error when fbx file with images

### ISSUE THREAD

**Issue by taoroot** [mrdoob/three.js#16709]
##### Description of the problem

![image](https://user-images.githubusercontent.com/14340565/59024265-20de2200-8884-11e9-98e2-bbc541de13c0.png)

##### Three.js version

- [ ] Dev
- [x] r105
- [ ] ...

- [x] Node.js

**Comment by Mugen87** [comment]
Can you please share your FBX file in this thread?

**Comment by taoroot** [comment]
[004.zip](https://github.com/mrdoob/three.js/files/3266127/004.zip)

**Comment by Mugen87** [comment]
Your FBX file contains embedded images in binary format. As mentioned in the source code of the converter, this type of images are not yet supported. The converted should actually throw an error but instead a runtime error is produced since `Blob` can only be used in browsers.
