### ISSUE TITLE
Multiple directional lights interfering with each other

### ISSUE THREAD

**Issue by GCDeveloper** [mrdoob/three.js#16746]
##### Issue

Having multiple directional lights in the scene causes their intensities to combine, causing a much brighter scene. Dividing each intensity by the number of directional lights, or setting all but 1 light intensity to 0 solves this issue. However, in this case, these lights do not correctly cast shadows. They cast shadows on geometry such as a plane, but they do not cast shadows on models, such as you can see in the below image (close trees have shadows due to the close directional light having normal intensity, far trees do not have shadows due to their directional light having 0 intensity).

<img width="516" alt="Screenshot 2019-06-09 at 22 53 45" src="https://user-images.githubusercontent.com/17480805/59165049-7416d580-8b0d-11e9-9b2b-03cef9e686f3.png">

The code for this can be seen and ran locally at https://github.com/GCDeveloper/r3act/blob/learning/src/Scene.js

##### Three.js version

THREE.WebGLRenderer 104

##### Browser

Tested only on
- [x] Chrome 74

##### OS

Test only on:
- [x] macOS

**Comment by GCDeveloper** [comment]
Shadows are not made properly on models when setting intensity of every directional light to the same value. Only 1 directional light at 1 time can have these shadows, by setting all other lights intensity to 0.

**Comment by gkjohnson** [comment]
Can you describe what you mean by properly rendering shadows? If there are multiple directional lights in a scene I would expect the light to become more intense and if a light intensity is set to 0 then it shouldn't do anything.

**Comment by GCDeveloper** [comment]
In the top right the shadow on the plane/ground is ok, but it is not being casted onto the tree models. That is using a different directional light than the one close to the camera.

**Comment by WestLangley** [comment]
This is not a help site. Do not cross-post SO and three.js forum posts here.

Closing.
