### ISSUE TITLE
Suggestion: Add `setFromProjectionMatrix` to PerspectiveCamera

### ISSUE THREAD

**Issue by speigg** [mrdoob/three.js#16741]
It would be nice if there was a convenient way to decompose a perspective projection matrix into the properties of THREE.PerspectiveCamera. As a starting point, I have implemented a method that decomposes (on or off-axis) perspective projection matrix into a set of top/left/bottom/right FOVS:

```js
class CameraFOVs {
  top = 0
  left = 0
  bottom = 0
  right = 0
  horizontal = 0
  vertical = 0
}
const _fovs = new CameraFOVs()
const _getFovsMatrix = new THREE.Matrix4()
const _getFovsVector = new THREE.Vector3()
const FORWARD = new THREE.Vector3(0, 0, -1)
function getFovs(projectionMatrix: THREE.Matrix4) {
  const out = _fovs
  const invProjection = _getFovsMatrix.getInverse(projectionMatrix, true)
  const vec = _getFovsVector
  out.left = vec
    .set(-1, 0, -1)
    .applyMatrix4(invProjection)
    .angleTo(FORWARD)
  out.right = vec
    .set(1, 0, -1)
    .applyMatrix4(invProjection)
    .angleTo(FORWARD)
  out.top = vec
    .set(0, 1, -1)
    .applyMatrix4(invProjection)
    .angleTo(FORWARD)
  out.bottom = vec
    .set(0, -1, -1)
    .applyMatrix4(invProjection)
    .angleTo(FORWARD)
  out.horizontal = out.right + out.left
  out.vertical = out.top + out.bottom
  return out
}
```

Something similar to this would be nice to add to `THREE.PerspectiveCamera`, perhaps named `setFromProjectionMatrix`, and able to correctly decompose to the `fov` / `aspectRatio` / `view` / `near` / `far` properties. 

Use Case: decomposing projection matrix from WebXR/WebVR

**Comment by mrdoob** [comment]
I'm not sure this is possible. As far as I understand, WebXR/WebVR projections are not necessarily normal perspective projections...

**Comment by speigg** [comment]
@mrdoob, yes they can be off-axis, but the code I gave above can decompose off-axis projection matrices correctly. The only thing I haven’t accounted for is skew, I think. I don’t think an XR system would ever present a skewed projection matrix, but even I’m wrong about that it should still be possible to decompose it if we include a skew component.

**Comment by mrdoob** [comment]
I see I see.

Do you mind elaborating about more on the use case? Why do you want to decompose these WebVR/WebXR projection matrices?

**Comment by Mugen87** [comment]
Closing for now until the use case is more clear. AFAIK, apart from this issue there was no request for `setFromProjectionMatrix()` in the past.

**Comment by makc** [comment]
> Why do you want to decompose these WebVR/WebXR projection matrices?

btw, how does culling work with these

**Comment by Mugen87** [comment]
Please do not ask questions in closed issues.
