### ISSUE TITLE
(editor) Unclear: how to select render/play camera

### ISSUE THREAD

**Issue by danksky** [mrdoob/three.js#16742]
##### In the three.js editor, there seems to be no way to choose which camera is rendering to the screen in "PLAY" mode. 

This is especially inconvenient because the scene I'm using has an orthographic camera.
Am I missing something?

**Comment by Mugen87** [comment]
`Play` mode uses always the default perspective camera of the scene. You can preview with different camera (see screenshot) but this setting is not used when activating `Play`.

![image](https://user-images.githubusercontent.com/12612165/59158782-0f815980-8ac0-11e9-9ac3-1ce5ceaff293.png)

**Comment by Temdog007** [comment]
You can change the `Player's` camera by calling `setCamera(camera)`.

#### Example
```javascript
player.setCamera(scene.getObjectByName("OrthographicCamera"));
```

Add a script to your scene that will call this function.
