### ISSUE TITLE
Feature request:  A way to control the initial twist of the shape while extruding it along a curve3

### ISSUE THREAD

**Issue by challakoushik** [mrdoob/three.js#16753]
https://discourse.threejs.org/t/how-to-control-the-initial-twist-of-the-shape-while-extruding-it-along-a-curve3/8018

The issue I'm facing is explained in the above link. I'm fine with the shape being twisted based on the path but the initial orientation of the 2D shape should be controllable.

**Comment by Mugen87** [comment]
All geometries are created with a certain assumptions. For example the vertices of `PlaneGeometry` lie in the XY plane. If you want to change the orientation of the geometry, do what I suggest in the [forum](https://discourse.threejs.org/t/how-to-control-the-initial-twist-of-the-shape-while-extruding-it-along-a-curve3/8018/2?u=mugen87).

**Comment by WestLangley** [comment]
I would consider this a feature request, not a help request.

It is the same issue as in https://github.com/mrdoob/three.js/issues/5258. This issue has been raised many times, if I recall correctly.

three.js is not a modeling tool, so I am not sure we will ever support the feature requested here.

@challakoushik If you are extruding in a straight line, then do not set an extrusion `path`-- set extrusion `depth` instead. That should avoid unexpected behavior.

**Comment by Mugen87** [comment]
I only recall this one: #13705

**Comment by WestLangley** [comment]
#905

#1569

https://stackoverflow.com/questions/25626171/threejs-extrudegeometry-depth-gives-different-result-than-extrudepath

**Comment by Mugen87** [comment]
In general, I'm against making the geometry generators more complex. The APIs are often used in unpredictable ways so I prefer simple parameters that do no fancy stuff.
