### ISSUE TITLE
gl.DEPTH_STENCIL not accepted by renderbufferStorageMultisample()

### ISSUE THREAD

**Issue by aardgoose** [mrdoob/three.js#16756]
The value DEPTH_STENCIL here is rejected as invalid in Chrome 75 (but accepted by Firefox).

https://github.com/mrdoob/three.js/blob/6737d0dfe3a92a83f0a7e385e223bae437bce091/src/renderers/webgl/WebGLTextures.js#L795

..looking into the specs for the underlying openGL call at https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glRenderbufferStorageMultisample.xhtml

a sized internalFormat such as DEPTH24_STENCIL8 is required, Firefox translates DEPTH_STENCIL to DEPTH24_STENCIL8 internally.

Is changing this to DEPTH24_STENCIL8 acceptable?

**Comment by Mugen87** [comment]
`DEPTH_STENCIL` is used multiple times in `WebGLTextures`. Does this issue also occur with a non-multisampled render target?

**Comment by aardgoose** [comment]
I've not checked those code paths.

**Comment by aardgoose** [comment]
Tested the line you highlighted.  works fine in Chrome.

**Comment by Mugen87** [comment]
Um, strange.

@kenrussell Do you have any recommendations what to do in this case? It seems applying `DEPTH_STENCIL` to `WebGL2RenderingContext.renderbufferStorageMultisample()` is not a valid operation.

**Comment by kenrussell** [comment]
The unsized DEPTH_STENCIL format was accepted as a renderbuffer internal format in WebGL 1.0 as a workaround.

In WebGL 2.0 the sized internal format is (or should be) required. Can you conditionalize these code paths to pass in the sized internal format when running on WebGL 2.0?

Separately, I've filed a bug against KhronosGroup/WebGL to add a test to clear up this discrepancy.

**Comment by Mugen87** [comment]
@kenrussell Many thanks for your feedback.

> Tested the line you highlighted. works fine in Chrome.

Have you tested the line with a WebGL2 rendering context?

**Comment by aardgoose** [comment]
I tested both paths with a WebGL2 context

**Comment by Mugen87** [comment]
So using `DEPTH_STENCIL ` with `renderbufferStorage` is no problem but it is an issue with `renderbufferStorageMultisample`? Shouldn't both variants treated the same?

**Comment by aardgoose** [comment]
Ideally, but WebGL 1 doesn't support the DEPTH28_STENCIL8 constant.  (just tested with Chrome, it gives 'invalid internal format' and agrees with MDN documentation, where it is only given for WebGL2.

**Comment by kenrussell** [comment]
@Mugen87 it's supported in renderbufferStorage for backward compatibility. renderbufferStorageMultisample is a new WebGL 2.0 entry point so the WebGL WG avoided carrying forward the handling of the unsized version for that API. Sized internal formats weren't supported in WebGL 1.0 at all.

**Comment by Mugen87** [comment]
Okay, understood! In this case the PR of @aardgoose provides the correct fix.
