### ISSUE TITLE
Uncaught ReferenceError: THREE.Clock is not a constructor

### ISSUE THREAD

**Issue by danksky** [mrdoob/three.js#16774]
##### Uncaught ReferenceError: THREE.Clock is not a constructor

Backstory: I've been following [this guide](https://medium.com/@soffritti.pierfrancesco/how-to-organize-the-structure-of-a-three-js-project-77649f58fa3f) to modularize my three.js project and coding environment. I want to eventually include one `<script>` tag in one `index.html` file with `index.js`. So here're the starts of my `header-main.js` and `scene-manager.js` files:

--> Did I follow [this guide](https://threejs.org/docs/#manual/en/introduction/Import-via-modules) on importing three.js incorrectly?

**header-main.js**
```
import SceneManager from './scene-manager.js';

const canvas = document.getElementById("header-banner-canvas");

const sceneManager = new SceneManager(canvas);
...
```
**scene-manager.js**
```
'use strict';

import * as THREE from './header-lib/three.js';

export default function SceneManager(canvas) {

    const clock = new THREE.Clock();
    
    const screenDimensions = {
        width: canvas.width,
        height: canvas.height
    }
    ...
}
```

##### Three.js version

- [ ] Dev
- [x] r105
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

--> Did I follow [this guide](https://threejs.org/docs/#manual/en/introduction/Import-via-modules) on importing three.js incorrectly?

**Comment by WestLangley** [comment]
This is not a help site. Please redirect your question to the three.js [forum](https://discourse.threejs.org/).

**Comment by danksky** [comment]
> This is not a help site.

@WestLangley Thanks for the link. Are you implying that this isn't an issue?

**Comment by mrdoob** [comment]
If you are able to describe the bug confidently we can look into it.

Otherwise you are asking us to debug your code and or time is limited. 

We tend to send these issues to the forum first.
