### ISSUE TITLE
Shadow material item masking other items in background.

### ISSUE THREAD

**Issue by tavvayaswanth567** [mrdoob/three.js#16776]
Hi, 

The issue is I have created a geometry of cube first, then geometry which has shodowmaterial to enable shadows. Both geometries are almost at the same location. I have made the opacity to 0, still the cube in background is not visible clearly. Is this expected or if yes, how do I make shadow geometry transparent but still receive shadows.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests. Github is only for bug reports and feature requests.
