### ISSUE TITLE
iOS UIWebView doesn't provide OffscreenCanvas.getContext("2d")

### ISSUE THREAD

**Issue by vobu** [mrdoob/three.js#16782]
##### Description of the problem
as the title says, iOS (12.2) UIWebView doesn't provide OffscreenCanvas.getContext("2d"), breaking texture resizing in src/renderers/webgl/WebGLTextures.js:65 and thus failing three.js to run.

(debugging console Safari -> iOS sim)
> (new OffscreenCanvas(1,1).getContext("2d")) === null 
< true
> (new OffscreenCanvas(1,1).getContext("webgl")) === null 
< false

fix is on its' way at https://github.com/mrdoob/three.js/pull/16781 !

##### Three.js version

- 0.105.1

##### Browser

- iOS 12.2 UIWebView

##### OS

- iOS

**Comment by Mugen87** [comment]
> fix is on its' way at #16781 !

Um, I wonder if it's not better to report this issue to Apple instead. A fix on their side would be the better solution than patching `WebGLTextures`. TBH, it makes no sense to me to provide the `OffscreenCanvas` interface but not the ability to get a drawing context from it.

**Comment by vobu** [comment]
> > fix is on its' way at #16781 !
> 
> Um, I wonder if it's not better to report this issue to Apple instead. A fix on their side would be the better solution than patching `WebGLTextures`. TBH, it makes no sense to me to provide the `OffscreenCanvas` interface but not the ability to get a drawing context from it.

I agree, but given that Apple is dropping UIWebView (in favor of WKWebView), they will certainly not invest in such a fix. And also given that cordova iOS will keep UIWebView for the time being (b/c WebView will break lots of commodity functionality), I assumed patching `WebGLTextures` would be the more pragmatic approach.

**Comment by Mugen87** [comment]
I see. Okay, against this backdrop it seems reasonable to test if a context can actually acquired and is not null.
