### ISSUE TITLE
InterleavedBufferAttribute misses toJSON method

### ISSUE THREAD

**Issue by Alchemist0823** [mrdoob/three.js#16835]
##### Description of the problem

https://github.com/mrdoob/three.js/blob/dev/src/core/InterleavedBufferAttribute.js
InterleavedBufferAttribute misses toJSON

##### Three.js version

- [ ] Dev
- [ x] r105
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Read the following two issue why a copy/clone operations on attribute levels is difficult. #15395/#12800

**Comment by Mugen87** [comment]
Fixed via #18537. Cloning/serializing interleaved attributes deinterleaves the data now. Ideally, the engine can retain interleaved data in the future when an entire `BufferGeometry` is cloned /serialized.
