### ISSUE TITLE
BoxHelper is deprecated: Use {@link BoxHelper THREE.BoxHelper} instead.

### ISSUE THREAD

**Issue by zacaj** [mrdoob/three.js#16831]
##### Description of the problem

On latest (105.1), I'm getting a linter (latest tslint 5.17) error when I try to use BoxHelper, saying that it's deprecated, and that I should switch to BoxHelper.  I'm guessing that since the actually deprecated BoundingBoxHelper is commented out, it's interpreting its deprecation notice as applying to BoxHelper (immediately below it in BoxHelper.d.ts) instead.  Is there any reason to still have that commented out class?

##### Three.js version

- [ ] Dev
- [x] r105
- [ ] ...

**Comment by Mugen87** [comment]
> Is there any reason to still have that commented out class?

No, it can be removed now.

**Comment by zacaj** [comment]
Hopefully I did that right...
