### ISSUE TITLE
Cubic panorama for a sphere's texture

### ISSUE THREAD

**Issue by pewixg3** [mrdoob/three.js#16842]
Hi
I'm trying to create a panorama with a sphere and these image for texture : 
![cubemap_1560274075222100992](https://user-images.githubusercontent.com/45328945/59770543-85e43f80-92a8-11e9-8050-c075df3e8c64.jpg)

I have already succeed to do this with an equirectangular panorama.

I hope someone have an idea.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by WestLangley** [comment]
>This form is for three.js bug reports and feature requests only.
>This is NOT a help site. Do not ask help questions here.

I wonder what it is about those instructions that is so difficult to understand...

**Comment by yomboprime** [comment]
> > This form is for three.js bug reports and feature requests only.
> > This is NOT a help site. Do not ask help questions here.
> 
> I wonder what it is about those instructions that is so difficult to understand...

Perhaps we should add a link to the forums there? 🤔

**Comment by mrdoob** [comment]
@yomboprime worth a ty 🤔
