### ISSUE TITLE
example shaders not compatible with WebGL2

### ISSUE THREAD

**Issue by aardgoose** [mrdoob/three.js#16870]
Out of curiosity I have tried running the examples using a WebGL2 context, several fail. The most common problem is the use of ShaderMaterials with a uniform 'texture' which conflicts with the GLSL ES 3.0 texture() function (easily fixed by renaming the uniform of course).

I think it would be good if examples avoided this issue, given the confusion that may occur if/when examples are used as the basis for other's code.

Thoughts?

**Comment by yomboprime** [comment]
`GPUComputationRenderer.js` is guilty here.

**Comment by mrdoob** [comment]
Yeah, we should definitely clean that up.

**Comment by aardgoose** [comment]
I'll sort them out shortly
