### ISSUE TITLE
怎么引用GPUParticleSystem ？

### ISSUE THREAD

**Issue by Yanzengyong** [mrdoob/three.js#16906]
直接THREE.GPUParticleSystem是没有的， import { GPUParticleSystem } from 'three/examples/js/GPUParticleSystem' ，我通过这个方式引用会报ReferenceError: THREE is not defined
./node_modules/_three@0.105.2@three/examples/js/GPUParticleSystem.js

**Comment by Mugen87** [comment]
It should be:
```js
import { GPUParticleSystem } from 'three/examples/jsm/GPUParticleSystem.js' 
```

**Comment by Mugen87** [comment]
Notice that the `GPUParticleSystem` is not available as a module (for a complete list, check out the section `Importable Examples` in [Import via modules](https://threejs.org/docs/index.html#manual/en/introduction/Import-via-modules). 

Moreover, `GPUParticleSystem` will be removed with the next release.

**Comment by Mugen87** [comment]
Besides, you always import example modules from the `jsm` directory like so:
```js
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
```
You path points to the `js` directory.

**Comment by Yanzengyong** [comment]
thx
