### ISSUE TITLE
VRML Example Doesn't Work on Safari after r106

### ISSUE THREAD

**Issue by bleighb** [mrdoob/three.js#16919]
##### Description of the problem

Example just results in a black screen with the following error: 

<img width="808" alt="image" src="https://user-images.githubusercontent.com/3516166/60211096-58f5d680-982c-11e9-8b2c-f5acaf3b68ea.png">

Also, the VRML files I've been working with stopped parsing correctly on all browsers with the new dependency added, but that's probably for a separate issue.

##### Three.js version

- [x] r106

##### Browser

- [x] Safari

##### OS

- [x] macOS

**Comment by Mugen87** [comment]
Can you please share one of the problematic VRML files. The screenshot you posted shows a parsing error.

**Comment by bleighb** [comment]
Here's a [gist](https://gist.github.com/bleighb/1a88ca16106a0db8568900be51de8f04) with the .wrl file contents. 

It seems all other .wrl files exported from this application (Helitronic Tool Studio) also fail in the same way.

**Comment by Mugen87** [comment]
The PR closed the issue but I still looking for your WRL file 👍

**Comment by Mugen87** [comment]
The general Safari issue is fixed in `dev`: 

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_loader_vrml.html

It was necessary to change one of the regular expression since it was not evaluated correctly in Safari!

**Comment by bleighb** [comment]
Awesome, thank you! 🙏

**Comment by Mugen87** [comment]
I've investigated the other VRML file and found a strange issue. Some shape definitions contain no definition of a `coordIndex`:
```
Shape {
      appearance Appearance {
        material Material {
          diffuseColor 0.700 0.700 0.700 
          ambientIntensity 0.500 
          specularColor 0.500 0.500 0.500 
          shininess 0.500 
          transparency 0.000 
        }
      }
      geometry IndexedFaceSet {
        color Color {
          color [
            0.435 0.000 1.000
          ]
        }
      }
    }
```
Shapes like this are actually not valid since the actual vertex data are missing. In other words, you can't render a geometry with just its color data. So this looks like a bug in the exporter of your content creation tool.

May I ask, how should the model `ex-2.wrl` look like? Can you share a screenshot of the intended result?

**Comment by bleighb** [comment]
This is what it looks like loaded in r105. Also works by dragging the file (or any file exported by the program) into the r105 editor.

![image](https://user-images.githubusercontent.com/3516166/60291887-f7943d00-98e9-11e9-9ed9-6f6b0c2fb66a.png)

**Comment by mrdoob** [comment]
I'll update `gh-pages`.

**Comment by mrdoob** [comment]
Done!

**Comment by mrdoob** [comment]
Still getting this error with `ex-2.wrl` in https://threejs.org/editor/ though...

<img width="638" alt="Screen Shot 2019-06-27 at 4 21 52 PM" src="https://user-images.githubusercontent.com/97088/60307079-e3efd300-98f7-11e9-87db-23c34eab9ad8.png">

**Comment by Mugen87** [comment]
I was able to load `ex-2.wrl` with the last PR. The loader is now a bit more fault-tolerant. However, it logs a warning to notify the missing geometry data.

**Comment by bleighb** [comment]
Awesome, it works now. Just one minor problem, is that the material reproduction might be off. It's an easy fix though, I just need to change each materials `shininess`, `specular`, and `emissive` props to match the original. This is probably a result of the new loader more closely adhering to the VRML spec, right?

<img width="508" alt="Screen Shot 2019-06-28 at 10 28 48 AM" src="https://user-images.githubusercontent.com/3516166/60349772-3c72af00-9990-11e9-9798-589f69299a80.png">

`r105` on the left, `dev`/`r106.x` on the right

**Comment by Mugen87** [comment]
> This is probably a result of the new loader more closely adhering to the VRML spec, right?

The loader implements the VRML spec more strictly than before. That was also the reason why you geometries could not processed in the first place.
