### ISSUE TITLE
HLS video not playing in mobile browser.

### ISSUE THREAD

**Issue by melzoSMIS** [mrdoob/three.js#16913]
##### Description of the problem

I am working on aframe and video.js in react to show a 360 video (hls video) in browser.
It is working fine in desktop browser but in mobile browser it shows black screen and plays only audio.
Search almost everything.
Project url : https://melzo.com/dekho/5d0b7e1ab263bf000fa383a7
open this in mobile browser and and click on tutorial2

Browser error : (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}

##### Browser

Google chrome 75

##### OS

- [x] Android
- [x] iOS

**Comment by Mugen87** [comment]
Um, why are you posting such an issue here? It does not look like a `three.js` bug.

I suggest you file a bug at the respective browser vendor.

**Comment by melzoSMIS** [comment]
I also posted in browser.
It shows: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The video element contains cross-origin data, and may not be loaded. 

Please suggest any solution.

**Comment by mrdoob** [comment]
No idea...

**Comment by NongDeng** [comment]
Play video with hls.js in android can resolve it
