### ISSUE TITLE
Typo in CompressedTexture.d.ts 

### ISSUE THREAD

**Issue by hjlld** [mrdoob/three.js#16915]
https://github.com/mrdoob/three.js/blob/8aa8b6bf438362ef444810673e1865ce8e67e463/src/textures/CompressedTexture.d.ts#L17

`format?: PixelFormat,` should be `format?:  CompressedPixelFormat`

**Comment by Mugen87** [comment]
Would you like to do a PR with the change?

**Comment by hjlld** [comment]
@Mugen87  Sorry, I wish, but I'm a noob to github, not familiar with how to send PR and contribute to big project. :(

**Comment by Mugen87** [comment]
No problem. Should be fixed now 👍
