### ISSUE TITLE
Revisiting the style guide etc in response to r106

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#16927]
As of r106 all the examples now use es6 modules. I've been told more than once in the last year that some kind of code was unacceptable because it was not IE11 compatible.

For example [here's one](https://github.com/mrdoob/three.js/issues/15506). 

I know there are others.

But now that all the examples are using `import` the repo is decidedly not compatible with IE11. In fact it's not compatible with any browser before May 2017.

So, now that someone has finally decided to break compatibility with old browsers how about all rest?

* template literals? yes/no
* `const` and `let`? yes/no
* destructuring? yes/no
* `class` keyword? yes/no
* `Set`? `Map`?
* arrow functions
* async/await

etc...

**Comment by Mugen87** [comment]
The builds of `three.js` still work in older browser. Just migrating the examples to modules has not changed anything about this fact. Hence, I'm not sure it's the right opportunity to revisit this topic.

Instead of creating a new issue, it would be better to continue the discussion here: #6419
