### ISSUE TITLE
"export 'ParticleCanvasMaterial' (imported as 'THREE') was not found in 'three'

### ISSUE THREAD

**Issue by pass13046132** [mrdoob/three.js#16925]
#my code block
import * as THREE from 'three';

new THREE.MeshBasicMaterial({
            color: this.getRandomColor(),
            program: this.particalRender
 });

and then, see this problem

**Comment by Mugen87** [comment]
`ParticleCanvasMaterial` does not exist in the entire repository. It's a deprecated class that was removed in the past. Are you still using it in your app?

**Comment by pass13046132** [comment]
> `ParticleCanvasMaterial` does not exist in the entire repository. It's a deprecated class that was removed in the past. Are you still using it in your app?

ok, not in my app, It's the first time i use three.js, so i have some problem. thanks for your help.    : )
