### ISSUE TITLE
Geometry and BufferGeometry types missing in r106

### ISSUE THREAD

**Issue by samalexander** [mrdoob/three.js#16926]
##### Description of the problem

Geometry and BufferGeometry types are missing from WebGLRenderer.d.ts file. Compiling an app that uses three.js with tsc produces the following errors with r106:

```javascript
node_modules/three/src/renderers/WebGLRenderer.d.ts:317:13 - error TS2304: Cannot find name 'Geometry'.

317     geometry: Geometry | BufferGeometry,
                  ~~~~~~~~

node_modules/three/src/renderers/WebGLRenderer.d.ts:317:24 - error TS2304: Cannot find name 'BufferGeometry'.

317     geometry: Geometry | BufferGeometry,
                             ~~~~~~~~~~~~~~


Found 2 errors.
```

##### Three.js version

- [ ] Dev
- [x] r106
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This is already fixed here: #16918

@mrdoob I'm afraid we need to bump the `npm` package. Otherwise we get more issue like this one...

**Comment by Mugen87** [comment]
I wonder if there is a way to detect such errors with Travis. We had a similar issue last release...

**Comment by mrdoob** [comment]
@Mugen87 done!

**Comment by mrdoob** [comment]
> I wonder if there is a way to detect such errors with Travis. We had a similar issue last release.
>
> Would it be possible to perform some sort of test-build with TS?

/ping @gkjohnson

**Comment by gkjohnson** [comment]
Surprisingly it doesn't look like the typescript linter has or is using the `no-undef` rule. I'll do a little more research and submit an issue in that repo if I can't figure it out.

**Comment by gkjohnson** [comment]
I've added an issue in the typescript-eslint repo:

https://github.com/typescript-eslint/typescript-eslint/issues/662
