### ISSUE TITLE
Points.updateMorphTargets causes Uncaught TypeError with Geometry

### ISSUE THREAD

**Issue by nyacg** [mrdoob/three.js#16928]
##### Description of the problem
When creating a new Points object using a Geometry we get an 'Uncaught TypeError:  Cannot convert undefined or null to object at  Points.updateMorphTargets'. This is because the updateMorphTargets function iterates over the keys of the `geometry.morphAttributes` which is undefined for a Geometry (but `{}` by default for a BufferGeometry).

* [jsfiddle](https://jsfiddle.net/45z2u6Lf/) (Demo of error, look in console and then uncomment line 30 to 'fix')

To recreate:
```js
const geometry = new THREE.Geometry();
geometry.vertices.push(new THREE.Vector3());
const points = new THREE.Points(geometry);  // Error thrown
```

To 'fix':
```js
const geometry = new THREE.Geometry();
geometry.vertices.push(new THREE.Vector3());
geometry.morphAttributes = {};
const points = new THREE.Points(geometry); 
// etc...
```

##### Three.js version

- [ ] Dev
- [x] r106
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
`Geometry` is not supported by `Mesh.updateMorphTargets()` and `Points.updateMorphTargets()`. The solution is to use `BufferGeomtry` instead.

Notice that sooner or later `Geometry` is not renderable anymore, see #15514

**Comment by nyacg** [comment]
Ahh, ok, this still feels like an issue given there are no warnings about the deprecation of Geometry and/or that the Points class now requires a BufferGeometry.

**Comment by Mugen87** [comment]
> Ahh, ok, this still feels like an issue given there are no warnings about the deprecation of Geometry and/or that the Points class now requires a BufferGeometry.

True, I guess we have overlooked that the method is called in the ctor per default. It might be better to implement the same check like in `Mesh`.

**Comment by Plankton555** [comment]
I just encountered this as well. Code that worked last week generated an error now. The "fix" that @nyacg proposed worked in my case as well.

Just to make sure I understand correctly: The "permanent" fix should be to switch Geometry to BufferGeometry? (I'm not that experienced with three.js, that's why I'm asking)

**Comment by Mugen87** [comment]
Yep, `BufferGeometry` should be your first choice.
