### ISSUE TITLE
Calling attach method of transform controls generates type errors

### ISSUE THREAD

**Issue by Dhawaldeep** [mrdoob/three.js#16923]
##### Description of the problem
I am using three version 105 in my angular app
On compiling the project. I get the following type error in TransformControls.d.ts

```
ERROR in node_modules/three/examples/jsm/controls/TransformControls.d.ts(31,3): error TS2416: Property 'attach' in type 'TransformControls' is not assignable to the same property in base type 'Object3D'.
  Type '(object: Object3D) => void' is not assignable to type '(object: Object3D) => this'.
    Type 'void' is not assignable to type 'this'.
```
And following is the method where I call attach method

Note: tControls is an instance of TranformControls
```
importSolarPanel(){
    const loader = new GLTFLoader()
    loader.load('assets/scene.gltf', (gltf)=>{
      console.log(gltf)
      gltf.scene.traverse(mesh=>{
        if(mesh instanceof Mesh){
          this.tControls.attach(mesh)
        }
      })
      this.tControls.setMode('rotate')
      this.scene.add(gltf.scene)
    }, (ev)=>{
      console.log(ev)
    }, (err)=>{
      console.log(err)
    })
  }
```

##### Three.js version

- [ ] Dev
- [x] r105
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Can you please check if #16929 solves the issue?
