### ISSUE TITLE
OBJLoader didnt work with import/require

### ISSUE THREAD

**Issue by erickAvSanti** [mrdoob/three.js#16937]
Im working with vue cli3, 
I was thinking that the next snippet will work perfect like with texture. but it didnt work.
import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader';
let obj_loader = new OBJLoader();
      obj_loader.load(
        // resource URL
        require('@/assets/blender/mesh.obj'),
        // called when resource is loaded
        function ( object ) {

          scene.add( object );

        },
        // called when loading is in progresses
        function ( xhr ) {

          console.log( ( xhr.loaded / xhr.total * 100 ) + '% loaded' );

        },
        // called when loading has errors
        function ( error ) {

          console.log( 'An error happened' );

        }
      );

Textureloader works perfectly.

let loader = new THREE.TextureLoader();
      loader.load( 
        require('@/assets/images/texture.png'), 
        function ( texture ) { 
          cubeGeo = new THREE.BoxGeometry( step, step, step );
          cubeMaterial = new THREE.MeshLambertMaterial( { color: 0xfeb74c, flatShading: true, map: texture,transparent:true,opacity:1 } ); 
          if(dev_mode){
            console.log("texture",texture);
            console.log("cubeMaterial",cubeMaterial);
          }
          if( pendingJson ){
            //instance.addVoxelFromJson( pendingJson );
          }
        }, 
        function ( xhr ) {
          if(dev_mode)console.log( (xhr.loaded / xhr.total * 100) + '% loaded' );
        }, 
        function ( xhr ) {
          if(dev_mode)console.log( 'An error happened' );
        }
      );

**Comment by mrdoob** [comment]
This example uses `OBJLoader` by importing the es module:
https://threejs.org/examples/webgl_loader_obj.html

**Comment by erickAvSanti** [comment]
Entiendo perfectamente la referencia que me muestras, pero al trabajarlo con vue/webpack para modo desarrollo y modo producción lo recomendable es utilizar import/require y es lo que no funciona.

En un proyecto con 'vue-cli npm'  y threejs me topé con la necesidad de importar un archivo wavefront y hasta ahora no puedo lidiarlo, encontré una forma alternativa que no me ayuda a optimizar.

**Comment by mrdoob** [comment]
Sounds like your are asking for help on how to use vue/webpack with three.js.

This section is for bug reports or feature request. Please, use the [forum](https://discourse.threejs.org/) for for help and guidance requests.
