### ISSUE TITLE
computeBoundingBox error when filling BufferGeometry

### ISSUE THREAD

**Issue by daylanKifky** [mrdoob/three.js#16935]
##### Description of the problem

I created a fixed length buffer, and then gradually filled it with vertices that come from a data stream to display a pointCloud.

If I try to `computeBoundingBox()` on the `BufferGeometry` it includes all the empty points on the buffer making the boundingBox extend until (0,0,0). 

I would expect this to be restricted by the `BufferGeometry.drawRange`

[fiddle](https://jsfiddle.net/4Lw93ac6/)

##### screenshot
![image](https://user-images.githubusercontent.com/11839769/60286150-751e7400-990f-11e9-965d-234d54e8d564.png)

##### Three.js version

- [x] Dev
- [x] r106

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
The `drawRange` has no effect when computing the bounding volumes. In this case, you have to performa  manual computation.
