### ISSUE TITLE
linewidth invalid,It is a poor experience. We hope three can achieve compatibility internally

### ISSUE THREAD

**Issue by 624220042** [mrdoob/three.js#16938]
Although the official webgl_lines_fat solution is provided, the line width is increased by more than 1000 times in use, and even if you divide by 1000, lines with different slopes will vary in thickness.

**Comment by Mugen87** [comment]
Can you please elaborate in more detail what you mean? I'm afraid the issue is somewhat unclear right now...

**Comment by 624220042** [comment]
thanks，your THREE.MeshLine can solve my problem!
