### ISSUE TITLE
LineMaterial with lowered opacity shows brighter circles

### ISSUE THREAD

**Issue by AlexVestin** [mrdoob/three.js#16964]
##### Description of the problem

Using the Line2 from the [example](https://threejs.org/examples/?q=line#webgl_lines_fat),
when I try to adjust the opacity using `matLine.uniforms.opacity.value = 0.x`, I get the line
to be transparent, however there are less transparent circles  which are only visible from some angles. I have tried to change around in the `LineMaterial` material file to solve this, but couldn't find a solution. 

Here is an image of the circles:
![linedemo](https://user-images.githubusercontent.com/31164322/60536254-235a5d00-9d06-11e9-82b7-363e8bef1e70.PNG)

To reproduce this I added `transparent: true` to the LineMaterial parameters and 
`matLine.uniforms.opacity.value = 0.3;`.

##### Three.js version

- [ ] Dev
- [x] r106
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
See discussion in #16570.

**Comment by AlexVestin** [comment]
@WestLangley Thank you, should have searched better.

**Comment by WestLangley** [comment]
Try [THREE.MeshLine](https://github.com/spite/THREE.MeshLine). You may like it better.

**Comment by AlexVestin** [comment]
I did try MeshLine, however the lines appeared flat when facing the camera, however this might have been a mistake somewhere on my end. I'll try to render a line with LineMaterial to a rendertarget and then apply the opacity on that, and see how that works out.

**Comment by WestLangley** [comment]
Please report back.

Fat lines tries to improve on the MeshLine mitered joints, and also maintain uniform line thickness regardless of the view angle, but fat lines do lack satisfactory opacity support.

**Comment by AlexVestin** [comment]
It did work for my purpose, since I already wanted the lines to be the same opacity and don't mind them being a separate layer. I'd imagine this approach wouldn't work if the lines are supposed to be in scenes with more meshes (or at all with line by line opacity)
