### ISSUE TITLE
ShaderLib.

### ISSUE THREAD

**Issue by cihadturhan** [mrdoob/three.js#16965]
##### Description of the problem

I was trying to use `depthRGBA` from `ShaderLib`

It has typescript definition so autocomplete works but there is no implementation on javascript side.
See this line: https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderLib.d.ts#L21

This is not available on javascript file:
https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderLib.js

Is `depthRGBA` removed from implementation?

##### Three.js version

- [ ] Dev
- [x] r106

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
The `depthRGBA` shader was removed in #8573. The new pattern to use is:

```js
material = new THREE.MeshDepthMaterial( {

	depthPacking: THREE.RGBADepthPacking

} );
```

See http://threejs.org/examples/webgl_materials_channels.html.

**Comment by WestLangley** [comment]
@cihadturhan Thanks for pointing out the error.
