### ISSUE TITLE
Parameter Inversion

### ISSUE THREAD

**Issue by 8BitRift** [mrdoob/three.js#16966]
##### 
The first two arguments passed to the Raycaster and Ray classes are first origin, and second direction, but for the ArrowHelper class it is direction first and then origin. Also direction in ArrowHelper is abbreviated to dir for some reason but it is not that way in Raycaster or Ray. Although not technically a bug, the switching of the parameters for the different classes makes remembering what goes where convoluted and I believe it should be addressed.
##### Three.js version

- [ ] Dev
- [x] r106
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by WestLangley** [comment]
Both `origin` and `direction` are `Vector3`s.

Changing the API for `ArrowHelper` will be difficult because there is no _reliable_ way to auto-correct, or alert the user he is passing args in the incorrect order.

I am inclined to think you are going to have to live with it.

**Comment by 8BitRift** [comment]
@WestLangley
Yea, I guess one sloppy solution could be to check which Vector3 is normalized as the direction should always be normalized and if they are both normalized output a warning.  Memorizing the correct order may be easiest for people who have worked with three.js for a while, but for new people their code could fail in unexpected ways simply because they made a wrong assumption that something as paired as origin and direction would always appear in the same order. (like me and the half hour i wasted today trying to figure out why my code wasn't working because of this)

**Comment by WestLangley** [comment]
Sorry.
