### ISSUE TITLE
Unexpected mouse behavior

### ISSUE THREAD

**Issue by billthefish** [mrdoob/three.js#16973]
Steps to reproduce:

- Hold down the left mouse button inside the model container
- While continuing to hold the mouse button, have the mouse pointer leave the model container
- Release the mouse button outside of the model container
- Return the mouse pointer inside the model container
- The model continues to rotate as if you still had the button depressed.

Expected behavior:

The model does not respond without the mouse button depressed.

Confirmed on Windows 10 with Chrome 75 and Firefox 67 using this example hosted by three.js:
https://threejs.org/examples/#webgl_interactive_cubes_gpu

**Comment by samipe** [comment]
You can only detect events that happen inside the browser window, therefore your mouseup-event won't be detected. Nothing to do with three.js.

**Comment by billthefish** [comment]
Not moving the mouse out of the browser completely, only the model container element (e.g. to the side bar). Is this still then a browser limitation?

**Comment by billthefish** [comment]
I found the answer. Thanks for pointing me in the right direction.
