### ISSUE TITLE
NormalNode.scope='local' outputting incorrect values

### ISSUE THREAD

**Issue by fi4sk0** [mrdoob/three.js#16975]
##### Description of the problem

I think the NormalNode does not output the correct vector if the scope is NormalNode.LOCAL
This is visible in the nodes example [webgl_materials_nodes](https://threejs.org/examples/?q=nodes#webgl_materials_nodes), choosing "node / normal". If scope is "world" or "view" it looks correct to me. Selecting scope = "local" should look like "world", since the teapot is not moving, but the camera is orbiting, instead it is similar to "view".

Unfortunately I didn't understand all the code, but changing the following lines in https://github.com/mrdoob/three.js/blob/7f52269ff54590592bbf8a461a908b25e260a240/examples/jsm/nodes/accessors/NormalNode.js#L44 
```javascript
		case NormalNode.LOCAL:

			// to use vObjectNormal as vertex normal
			// builder.requires.normal = true;

			result = 'normal';

			break;
```
to 
```javascript
		case NormalNode.LOCAL:

			// to use vObjectNormal as vertex normal
			builder.requires.normal = true;

			result = 'vObjectNormal';

			break;
```
solves to problem, but I don't understand enough to foresee the side effects.

I hope this is helpful @sunag and thank you for your great work!!

##### Three.js version

- [ ] Dev
- [x] r106
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by njarraud** [comment]
I just ran into the same issue with the broken LOCAL scope for NormalNode.
I didn't really studied the whole node code but your fix is working for me as well.

Here are screenshots with and without the fix - Triplanar texture projection with local normal and position nodes so that the projection remains identical when objects are moved around. Without the fix, the texture is being updated when the camera is moving.

![broken](https://user-images.githubusercontent.com/45501180/61344189-76a2e280-a8a4-11e9-9162-d2c5e220a8ed.jpg)

![fixed](https://user-images.githubusercontent.com/45501180/61344194-79053c80-a8a4-11e9-948b-8d99b1fcfcb9.jpg)

**Comment by fi4sk0** [comment]
I'm also having trouble to get normal maps working with triplanar mapping because the NormalMapNode uses partial derivatives of the UVs, which are obviously not available or constant zero in the fragment (and so are the derivatives).
https://github.com/mrdoob/three.js/blob/5403a8a793e2a64bff1e1f2009f0a120d1db9b48/examples/jsm/nodes/misc/NormalMapNode.js#L34

I read through this very elaborate triplanar normal mapping [article](https://medium.com/@bgolus/normal-mapping-for-a-triplanar-shader-10bf39dca05a) and I understand the issues of finding the proper surface tangents, but I don't know how to inject that into either this node or creating a function node for my purposes. 

And help on this would be greatly appreciated!

Also: in which space the should the normal vector returned by the function plugged into `StandardNodeMaterial.normal` be?

**Comment by sunag** [comment]
@njarraud and @fi4sk0 thank you for analysis! I will try to see this week, probably this issue fix this other https://github.com/mrdoob/three.js/issues/17042

**Comment by njarraud** [comment]
@sunag Thank you for working on the node system for Threejs. The results are just amazing and it much more versatile than the standard material system.

@fi4sk0 I am trying to do the same thing as you. I started a thread on threejs [discourse](https://discourse.threejs.org/t/triplanar-normal-mapping/8550/4) channel.

**Comment by sunag** [comment]
About triplanar normal mapping might you could consider using `blend normal map` ( https://blog.selfshadow.com/publications/blending-in-detail/ ) and modify only the `triplanar_mapping` example.

**Comment by njarraud** [comment]
@sunag I created a custom node that I called TriplanarNormalMapNode that seems to do the job.

I also used the paper you linked to create another useful one to mix 2 sets of normals with a specified blending method:
`var normal = new MixNormalNode(bevelNormal, noiseNormal, MixNormalNode.UDN);`

I shared them with @fi4sk0 and I can send them to you if you are interested.
