### ISSUE TITLE
“0” width for box renders as “1” width

### ISSUE THREAD

**Issue by sebasecheverry** [mrdoob/three.js#16972]
##### Description of the problem

“0” width for box renders as “1” width

Describe the bug or feature request in detail.

When creating a box 

`new THREE.BoxGeometry(opening.geometry.xLength, opening.geometry.yLength, opening.geometry.zLength)`

when you make a 0 width box.

`new THREE.BoxGeometry(0, 1, 1)`

It renders on the screen with 1 as width. I think it should not render anything. Is this a bug of three.js?.

##### Three.js version

r106

##### Browser

- [X ] Chrome

##### OS

- [X ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
The dimensions passed to the constructor of `BoxGeometry` or `BoxBufferGeometry` must be non-negative.

three.js does not validate function, or constructor, arguments.

**Comment by samipe** [comment]
```
function BoxBufferGeometry( width, height, depth, widthSegments, heightSegments, depthSegments ) {

  ...

  width = width || 1;
  height = height || 1;
  depth = depth || 1;
}
```

Seems intentional to me

**Comment by sebasecheverry** [comment]
@WestLangley 0 is a non-negative value.  However, my question is as @samipe says. Is it really intentional?. Who can confirm that?.

**Comment by WestLangley** [comment]
@sebasecheverry Oops. I meant _positive_.   :-)

Normals are not correct when a zero is passed as a dimension.

**Comment by WestLangley** [comment]
@sebasecheverry Oops. Sorry, I meant _positive_.

If zeros are allowed as a dimension, the normals will be incorrect. So, additional changes would be required.

Degenerate triangles would also occur, unless there were further modifications to the code.

**Comment by samipe** [comment]
Cube with 0 width makes no sense. Use a rectangle instead.

**Comment by Mugen87** [comment]
> Use a rectangle instead.

In our case [THREE.PlaneBufferGeometry](https://threejs.org/docs/index.html#api/en/geometries/PlaneBufferGeometry).
