### ISSUE TITLE
Can I use a Material Array for ShaderMaterial and SphereGeometry?

### ISSUE THREAD

**Issue by duoduodady** [mrdoob/three.js#16974]
Can I use a Material Array for ShaderMaterial?

The BoxBufferGeometry used a material array for Skybox.
just like :

  let envMap = new THREE.CubeTextureLoader()
                            .setPath('images/skybox/')
                            .load(['px.jpg', 'nx.jpg', 'py.jpg', 'ny.jpg', 'pz.jpg', 'nz.jpg']);
            let cubeShader = THREE.ShaderLib['cube'];
            cubeShader.uniforms['tCube'].value = envMap;

            let skyBoxMaterial = new THREE.ShaderMaterial({
                fragmentShader: cubeShader.fragmentShader,
                vertexShader: cubeShader.vertexShader,
                uniforms: cubeShader.uniforms,
                side: THREE.BackSide
            });

            var skyBox = new THREE.Mesh(new THREE.BoxBufferGeometry(1000, 1000, 1000), skyBoxMaterial);
            scene.add(skyBox);

If I use the THREE.SphereBufferGeometry or THREE.SphereGeometry with a material array.
How can I do?
1、load the material array to a Canvas?
2、use UVs mapping?

**Comment by WestLangley** [comment]
This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

**Comment by duoduodady** [comment]
Thanks for your focus!

I will go to forum !



yunpenger@163.com
 
From: WestLangley
Date: 2019-07-05 00:03
To: mrdoob/three.js
CC: duoduodady; Author
Subject: Re: [mrdoob/three.js] Can I use a Material Array for ShaderMaterial and SphereGeometry? (#16974)
This form is for three.js bug reports and feature requests only.
This is NOT a help site. Do not ask help questions here.
If you need help, please use the forum or stackoverflow.
