### ISSUE TITLE
Enable "linkback" plugin on the forum

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#16980]
Going over the plugins we have available on the forum, I noticed that there's a GitHub linkback plugin, which is currently disabled. 

If a PR or issue on the repo is discussed here, then the plugin will make a discrete post on this repo to alert people, with "Discourse Meta" replaced by "Discourse three.js"

![14fa55442fcee62f772b5b6e09437c9d2fe83f3d](https://user-images.githubusercontent.com/5307958/60716930-c00d3c80-9f4a-11e9-8bdb-5266c04e5f9b.png)

Enabling this would help to bridge the gap between the forum and here a bit and prevent useful info from getting lost.

**Comment by WestLangley** [comment]
In trying to understand the motivation for this plugin, I found this explanation:

>We do most of our discussion on meta.discourse.org, so there is often a post or topic about the change with more context.

But we don't do that. We do _all_ our PR discussions here, on this site.

The point of the discourse help site is to keep help questions over there, and off of this site. I am not sure a bot posting links on this site is a good idea. We can add links ourselves when it is appropriate -- and we do.

**Comment by Mugen87** [comment]
> But we don't do that. We do all our PR discussions here, on this site.

I would not say that. A lot of discussion related to PRs or github issues happens in the forum with the user base. We might want to give this plugin a try to find out how useful it actually is.

**Comment by looeee** [comment]
> But we don't do that. We do all our PR discussions here, on this site.

You are not active on the forum, so how can you know what's discussed there?

**Comment by mrdoob** [comment]
I think this will create even more notifications/noise for me to go through every day...

**Comment by Mugen87** [comment]
Okay, it seems this suggestions receives not enough support. Closing for now.
