### ISSUE TITLE
How can I import `OBJLoader` or `OBJLoader2` in es6?

### ISSUE THREAD

**Issue by Mds92** [mrdoob/three.js#16984]
How can I import `OBJLoader` or `OBJLoader2` in es6?
```
import { OBJLoader } from 'three';
```
Not work.

**Comment by Mugen87** [comment]
Please read the following guide for more information: [Import via modules](https://threejs.org/docs/index.html#manual/en/introduction/Import-via-modules)

Consider you use the latest `three.js` version, it would be:
```js
import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader.js';
```

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.
