### ISSUE TITLE
Set CSS2DObject dom style 'display:none' is not work

### ISSUE THREAD

**Issue by chenxiaoleizi** [mrdoob/three.js#17009]
##### Description of the problem

I use `CSS2DRenderer` to create a `label`, and when i set `label.style.display = 'none'` the label is not hide, and the label style display come to '', have a look at live code.
And a back 'r101' `CSS2DRenderer` it is work.

Here is th live code:

* [Code pen](https://codepen.io/chenminglei/pen/PrLzOO) (latest release branch)

##### Three.js version

- [ ] Dev
- [x] r106
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Setting `display` like in your codepen is not valid since the value is overwritten by `CSS2DRenderer`. Hide the label like so: `label.visible = false;`.

https://codepen.io/anon/pen/MMxjEy

**Comment by Mugen87** [comment]
Please use the forum if you need more help.
