### ISSUE TITLE
Texture stretching in Chorme but fine in FF !!!

### ISSUE THREAD

**Issue by baoquylan** [mrdoob/three.js#17001]
Hi everyone.I just a newbie and researching about threejs. I create a roof by ExtrudeGeometry and apply texture on it, 
Problem : texture was stretching in Chrome and still fine in FF
I was use method mapping uv, I just find it on internet

      ` var geometry = extrudedRoofGeometry;
        geometry.uvsNeedUpdate = true;
        geometry.faceVertexUvs[0] = [];

        geometry.faces.forEach(function (face) {

            var components = ['x', 'y', 'z'].sort(function (a, b) {
                return Math.abs(face.normal[a]) > Math.abs(face.normal[b]);
            });

            var v1 = geometry.vertices[face.a];
            var v2 = geometry.vertices[face.b];
            var v3 = geometry.vertices[face.c];

            geometry.faceVertexUvs[0].push([
                new THREE.Vector2(v1[components[0]], v1[components[1]]),
                new THREE.Vector2(v2[components[0]], v2[components[1]]),
                new THREE.Vector2(v3[components[0]], v3[components[1]])
            ]);

        });`

In Firefox
![pic1](https://user-images.githubusercontent.com/31461989/60940597-4092bb00-a306-11e9-9e9e-d46ebe8bbf9f.png)

In Chorme
![pic2](https://user-images.githubusercontent.com/31461989/60940609-45f00580-a306-11e9-90c6-2a765c48225e.png)

Please, give me some advice. Thanks, 

##### Three.js version

- [ ] Dev
- [x] r106
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
This is NOT a help site. Do not ask help questions here.

If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

**Comment by mrdoob** [comment]
https://discourse.threejs.org/t/texture-stretching-in-chorme-but-fine-in-ff/8452
