### ISSUE TITLE
ExtrudeGeometry's extrudePath should be Curve not CurvePath

### ISSUE THREAD

**Issue by gonnavis** [mrdoob/three.js#17029]
In the Docs -> ExtrudeGeometry & ExtrudeBufferGeometry, it's extrudePath option should be Curve not CurvePath.

**Comment by Mugen87** [comment]
Would you like to make a PR with the change? It's also necessary to change the respective TS declaration file:

https://github.com/mrdoob/three.js/blob/b1a13ffbbcd40520da6f683f8c06f11a63031997/src/geometries/ExtrudeGeometry.d.ts#L18

**Comment by gonnavis** [comment]
OK, I'll try!

**Comment by gonnavis** [comment]
Hello, I made a pr https://github.com/mrdoob/three.js/pull/17036, is it OK?

**Comment by Mugen87** [comment]
Looks good 👍
