### ISSUE TITLE
NDI Support for three.js

### ISSUE THREAD

**Issue by magdesign** [mrdoob/three.js#17026]
Is there any possibility to add Newtek NDI streams to display as Texture (Similar to Video as Texture) ?

Or how would I achieve this ?
Thanks for any inputs.

More info about NDI: https://www.newtek.com/ndi/sdk/
NDI is the next big thing in multimedia.
We are developing a videomapper based on three.js and want to implement NDI as an input (https://openmapper.ch)

**Comment by Mugen87** [comment]
Sorry, I've never head something of Newtek NDI. How would you include such a stream into an ordinary web page?

**Comment by magdesign** [comment]
Posted the question on Stackoverflow: https://stackoverflow.com/questions/57020591/newtek-ndi-stream-within-a-webpage-webgl-three-js

This was the only thing I found to realise a solution with node.js but its only windows compatible: https://github.com/Streampunk/grandiose

**Comment by Mugen87** [comment]
I'm closing this issue for now since it's make more sense to investigate how to playback such a stream in general and with pure WebGL. A feature request in context of `three.js`  can be done later.
