### ISSUE TITLE
Memory leaks when using potree

### ISSUE THREAD

**Issue by spirityy** [mrdoob/three.js#17028]
I have the problem loading large pointcould data. 

At the beginning, 
![mem1](https://user-images.githubusercontent.com/424997/61043700-7bc9e280-a409-11e9-83bf-7119504a897c.png)

After a while,
![mem3](https://user-images.githubusercontent.com/424997/61043717-84bab400-a409-11e9-8e59-b7d159c15dda.png)

The problem is PotreeRenderer class this.buffers? Or web workers load laz/las file cause memory leak?

I've exclude other possible causes.Without the point cloud being loaded, there is no memory leak for any operation.

chrome tool:
![WechatIMG232](https://user-images.githubusercontent.com/424997/61178819-bfe6fe00-a628-11e9-9950-88a7273510de.jpeg)

**Comment by Mugen87** [comment]
Since it's a potree issue, please post here instead: https://github.com/potree/potree
