### ISSUE TITLE
this.position.add() is not a function

### ISSUE THREAD

**Issue by ouyangxiaobai** [mrdoob/three.js#17030]
![NWO`RP0U6TK KN71U@)MU1E](https://user-images.githubusercontent.com/25460485/61202209-7aeec480-a719-11e9-9056-3583d3ef714f.png)

why

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for such help requests. It might be also helpful to demonstrate the issue with a [live example](https://jsfiddle.net/tfg2un9L/). 

P.S. As you can see in the linked demo, `Object3D.translateY()` seems to work fine. So there is probably an issue with your app.
