### ISSUE TITLE
WebXRManager: renderer.getContext() throws

### ISSUE THREAD

**Issue by modulesio** [mrdoob/three.js#17034]
It looks like [`WebXRManager` is constructed in `WebGLRenderer`](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L314), and tries to [`getContext()` of the renderer](https://github.com/mrdoob/three.js/blob/ce97f8b14b19c5130f0c48f27ffe0dec5dce042f/src/renderers/webvr/WebXRManager.js#L18).

However, this happens before the [`getContext` accessor is set up in the first place](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L326).

Should `WebXRManager` initialization be moved down?

**Comment by Mugen87** [comment]
> Should WebXRManager initialization be moved down?

That's probably the best solution. Do you want to make a PR for this? 😇

**Comment by mrdoob** [comment]
I think I would solve it differently.

**Comment by mrdoob** [comment]
Thanks for the bug report!

**Comment by fernandojsg** [comment]
Yeah nice catch!

**Comment by takahirox** [comment]
Just my two cents. I know it may be just my preference but I prefer moving down the manager initialization (or something) because (new) users might think having both renderer and gl arguments in the constructor looks redundant.
