### ISSUE TITLE
Normal issue with Bump Maps in StandardNodeMaterial

### ISSUE THREAD

**Issue by njarraud** [mrdoob/three.js#17042]
##### Description of the problem
Normals generated by BumpMapNode (and NormalMapNode) in StandardNodeMaterial seem to be incorrect.

I made 2 simple examples using only a HDR environment map to light the scene - One with StandardNodeMaterial and a second one with MeshStandardMaterial to show the difference. I also added a screenshot from Blender Eevee with the exact same set up which tends to prove that the result generated by MeshStandardMaterial is correct.

The scale factor also seem to be behaving differently.

![test](https://user-images.githubusercontent.com/45501180/61342495-799ad480-a89e-11e9-8a70-186c1f75e229.jpg)

* [jsfiddle](https://jsfiddle.net/dwkt8c5s/15/) StandardNodeMaterial
* [jsfiddle](https://jsfiddle.net/grfmnh6x/) MeshStandardMaterial

##### Three.js version

- [x] Dev
- [x] r106

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by njarraud** [comment]
I keep experimenting with the node materials and I may have a suggestion regarding NormalMapNode.

If the geometry includes multiple uv sets, I would have thought that NormalMapNode would use the same uv set as the one specified in TextureNode, or at least that it would have been an argument of the constructor.

Currently, this is not very obvious that the uv index has to be set manually after:

`let normalTex = new THREE.TextureLoader().load('normal.png');`
`let normalNodeText = new Nodes.TextureNode(bevelTex, new Nodes.UVNode(1));`
`let normalMap = new Nodes.NormalMapNode(normalNodeText);`
`normalMap.uv = new Nodes.UVNode(1);`

**Comment by sunag** [comment]
I am try revise the `BumpMapNode` in `jsfiddle` still without success . 
I am need to recreate the example locally and continue the tests...

**Comment by sunag** [comment]
@njarraud try replaces the function `generate` of `NormalNode` for this:
It will fix `NormalNode.WORLD` problem.
Exist other bugs to fix I will launch a PR with theses fixes soon.
```javascript
NormalNode.prototype.generate = function ( builder, output ) {

	var result;

	switch ( this.scope ) {

		case NormalNode.LOCAL:

			// to use vObjectNormal as vertex normal
			//builder.requires.normal = true;

			result = 'normal';

			break;

		case NormalNode.WORLD:

			if ( builder.isShader( 'vertex' ) ) {

				return '( modelMatrix * vec4( objectNormal, 0.0 ) ).xyz';

			} else {
				
				//builder.requires.worldNormal = true;

				//result = 'vWNormal';
				
				builder.addNodeCode( 'vec3 worldNormal = inverseTransformDirection( normal, viewMatrix );' );
				
				result = 'worldNormal';

			}

			break;

		case NormalNode.VIEW:

			result = 'vNormal';

			break;

	}

	return builder.format( result, this.getType( builder ), output );

};
```

**Comment by sunag** [comment]
`NormalNode.VIEW` need fix.

**Comment by njarraud** [comment]
@sunag I tried your code. It seems to fix BumpMapNode but on the other hand it breaks NormalMapNode.
