### ISSUE TITLE
brep format support

### ISSUE THREAD

**Issue by Spaceman007** [mrdoob/three.js#17053]
## brep format support

Hi, is there someone dealing with [brep](https://en.wikipedia.org/wiki/Boundary_representation) using three.js?

I have some brep files and I wanna if I can use three.js to render them in my browser.

Thank you for your reply.

**Comment by Mugen87** [comment]
Can you please share some BREP files in this issue? Any maybe a link to the specification? I have no idea how complex this standard is but maybe someone wants to start with an implementation.

**Comment by Spaceman007** [comment]
Here is the [occt_brep_format](https://www.opencascade.com/doc/occt-6.7.0/overview/html/occt_brep_format.html). 
I export two brep files with [freecad](https://www.freecadweb.org/).
[brep_files.zip](https://github.com/mrdoob/three.js/files/3426011/brep_files.zip)

![Screenshot from 2019-07-24 17-33-47](https://user-images.githubusercontent.com/12627808/61782929-83da4700-ae39-11e9-9612-5cabb7959f0c.png)
![Screenshot from 2019-07-24 17-34-05](https://user-images.githubusercontent.com/12627808/61782946-89d02800-ae39-11e9-8d61-296932d7c7bf.png)

**Comment by Spaceman007** [comment]
I found a brilliant project [jsketcher](https://github.com/xibyte/jsketcher) may be helpful. Their website is http://web-cad.org/.

**Comment by Mugen87** [comment]
Merging into #5524.
