### ISSUE TITLE
Documentation for ShaderMaterial .morphTarget property needs review

### ISSUE THREAD

**Issue by mghini** [mrdoob/three.js#17051]
##### Description of the problem

In the documentation page for ShaderMaterial, the current property description for morphTarget:
"Defines whether the material uses morphTargets; true morphTarget attributes to this shader"
is not clear and needs review.

see [https://threejs.org/docs/#api/en/materials/ShaderMaterial](https://threejs.org/docs/#api/en/materials/ShaderMaterial)

##### Three.js version
- [x] r106

**Comment by Mugen87** [comment]
> true morphTarget attributes to this shader

Maybe something like this instead: `When set to true, morph target attributes are available in the vertex shader`.

It would make sense to align the description of `morphNormals`.

**Comment by mghini** [comment]
I will
I personally would leave morphNormals as it is and review morphTarger like this:

Defines whether the material uses morphTargets. Set as true to pass morphTarget attributes from the Geometry to the shader. Default is false.

is it ok for you?

**Comment by Mugen87** [comment]
Um, I don't like the reference to `THREE.Geometry`. It also think `set to true` sounds more correct.

**Comment by mghini** [comment]
ok, perfect. Something like this:
"When set to true, morph target attributes are available in the vertex shader. Default is false."
for morphTargets
and
"When set to true, morph normal attributes are available in the vertex shader. Default is false."
for morphNormals?

**Comment by Mugen87** [comment]
Sounds good! 👍
