### ISSUE TITLE
TextureNode colorspace/encoding issue

### ISSUE THREAD

**Issue by njarraud** [mrdoob/three.js#17066]
##### Description of the problem

I have a discrepancy between MeshStandardMaterial and StandardNodeMaterial used with color textures. Unless I missed something, the texture generated by TextureNode seems to have an issue with color space or encoding.

Renderer:
`renderer.gammaOutput = true;`

Texture encoding:
`texture.encoding = THREE.sRGBEncoding;`

Node texture:
`nodeTexture = new TextureNode(texture);`

Example with three.js standard material system:
MeshStandardMaterial 1 (solid color):
`mtl.color = new THREE.Color(_VALUE_).convertSRGBToLinear();`

MeshStandardMaterial 2 (color texture):
`mtl.map = texture;`

![MeshStandardMaterial](https://user-images.githubusercontent.com/45501180/61612327-5b741080-acb2-11e9-881b-f3cb040fbea5.jpg)

Example with three.js node system:
StandardNodeMaterial 1 (solid color):
```
mtl.color = new ColorNode(_VALUE_);
mtl.color.value.convertSRGBToLinear();
```

StandardNodeMaterial 2 (color texture):
`mtl.color = nodeTexture;`

![StandardNodeMaterial](https://user-images.githubusercontent.com/45501180/61612420-a5f58d00-acb2-11e9-83b0-9252c04e5560.jpg)

Both images shall be similar however we can notice that on the second one, the object with the texture is all washed out.

* [jsfiddle](https://jsfiddle.net/3onvw7kj/2/)

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by n2k3s2it** [comment]
You might be using the wrong NodeMaterial. `StandardNodeMaterial` (as you write) is not the same as `MeshStandardNodeMaterial` unless that's a typo 😄

**Comment by njarraud** [comment]
No it is not a typo. I want to show that texture encoding is properly handled using the standard material system of Three.js (MeshStandardMaterial) but that when switching to the node system with a similar PBR workflow (e.g StandardNodeMaterial), using TextureNode the result is completely different when it shall be similar.

**Comment by njarraud** [comment]
I added a [jsfiddle](https://jsfiddle.net/3onvw7kj/2/) to explain a bit better the issue.
Both parts shall look identical however the part using the texture with StandardNodeMaterial (object1) is not as expected.

**Comment by njarraud** [comment]
@sunag I find a fix for this issue

In TextureNode.js, I replaced
`this.colorSpace.fromEncoding( builder.getTextureEncodingFromMap( this.value ) );`
by 
`this.colorSpace.fromDecoding( builder.getTextureEncodingFromMap( this.value ) );`
on line 68

Tell me if I am wrong, but the result makes sense to me now:

Now when the encoding property of a texture is set to sRGBEncoding, TextureNode.generate triggers the function sRGBToLinear() instead of LinearTosRGB(). The result is that a sRGB PNG texture with a colour value X is displayed the exact same way as a solid color X converted using convertSRGBToLinear().

If the texture encoding value is left to default (LinearEncoding), the result is that a sRGB PNG texture with a colour value X is displayed the exact same way as a solid color X.

**Comment by sunag** [comment]
Yes! You are correct, it is a bug.
I still have to create examples to test all of these nodes properly...

Do you want to do a PR to fix this bug? or wait I fix this in a next revision?

> NOTE: I just see your issue right now, for topics related to NodeMaterial you can ping my nick @sunag to that I can see faster.

Thanks!

**Comment by njarraud** [comment]
Thanks. I created a [PR](https://github.com/mrdoob/three.js/pull/17094) for this bug.
