### ISSUE TITLE
How to load gltf model directly in editor ppage

### ISSUE THREAD

**Issue by sagirr** [mrdoob/three.js#17065]
How ,the gltf model to be loaded when editor page load (
Example like this:  https://codepen.io/shshaw/pen/yPPOEg
) , 

I tried but failed
, there is a solution

**Comment by WestLangley** [comment]
Convert your model to `.glb` format and drag-and-drop it onto the editor.

This is not a help site. If you need more assistance, please redirect your questions to https://discourse.threejs.org.
