### ISSUE TITLE
comet-shaped light spot with orthographicCamera

### ISSUE THREAD

**Issue by JohnHwangx** [mrdoob/three.js#17083]
When I add orthgraphicCamera in scene, there will be a comet-shaped light spot at certain viewing angles. The light is directionalLight. How to avoid that.
![image](https://user-images.githubusercontent.com/16515614/61758397-33da9080-adf7-11e9-8d3f-2eabed6ff354.png)

**Comment by WestLangley** [comment]
This is not a help site. Please redirect your question to the three.js help site: https://discourse.threejs.org.
