### ISSUE TITLE
Documenting breaking changes in release notes

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#17098]
Hello all maintainers! Thanks for the continued work on this awesome lib!

It'd be great if breaking changes were marked in the release notes. Perhaps they can begin with a bold **breaking** keyword, or putting them in their own "breaking changes" section, or something.

**Comment by Mugen87** [comment]
The migration guide is intended for this use case. All breaking changes are listed there along with the recommended migration tasks.

https://github.com/mrdoob/three.js/wiki/Migration-Guide
