### ISSUE TITLE
Add isAnimated property to object3Ds

### ISSUE THREAD

**Issue by viperphase1** [mrdoob/three.js#17097]
I ran into a situation recently where I needed an easy way to tell programatically if an object3D is animated. My current solution is to iterate through every animation and track looking for keyframe tracks with the node's name. Is there a better way to do this? If not it would be great to add a property like isAnimated to object3Ds that gets set to true when the model is loaded.

**Comment by donmccurdy** [comment]
Animation clips can be created in many ways – from the original model, from another file, or generated dynamically at runtime. Arguably an Object3D could be considered "animated" if the application is animating it, even if no KeyframeTracks target that object, or if one of its parents is animated.

In short... I don't think there is a broadly useful definition of "isAnimated" that a loader could provide users, and so it is probably better not to add this property to the library.

> My current solution is to iterate through every animation and track looking for keyframe tracks with the node's name. Is there a better way to do this?

You do need to iterate over each track, but could probably make some of this easier using `THREE.PropertyBinding.parseTrackName()` or `findNode()` ([source](https://github.com/mrdoob/three.js/blob/master/src/animation/PropertyBinding.js#L124)). If there's another method that should be available there, perhaps we could add one.
