### ISSUE TITLE
How to Convert .OBJ file to .JS file

### ISSUE THREAD

**Issue by Proxz1994** [mrdoob/three.js#17095]
I am getting problem with the convertion of the 3D object to the Javascript file, I have tried convert 3D object to the json, but there is getting problem with my three.js project. I have also surf the web about convert json to js file but same it is not working.

I want to have the data of Geomatrics, Faces, Vertices, UV shell count/UVs, Material, Edges. I got improper data in the json file, like i got Geomatrices, Vertices, UVs, Materials, but i can't find get the arrays of the edges, Faces.

So if anyone have any idea or any converter for the same which is usefull for me.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
