### ISSUE TITLE
How to get the coordinates

### ISSUE THREAD

**Issue by 624220042** [mrdoob/three.js#17106]
How to get the coordinates (? ,?, Z),when the mouse click the screen, the click point may be a blank area without any object

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by WestLangley** [comment]
https://stackoverflow.com/questions/13055214/mouse-canvas-x-y-to-three-js-world-x-y-z/13091694#13091694
