### ISSUE TITLE
Has this been resolved or is there a work around for increasing the line width?

### ISSUE THREAD

**Issue by nrgapple** [mrdoob/three.js#17107]
https://github.com/mrdoob/three.js/blob/978a56055c8d712a1c146396ffa313034b0f7e81/docs/api/en/materials/LineBasicMaterial.html#L77

**Comment by WestLangley** [comment]
See these examples for workarounds:

https://threejs.org/examples/webgl_lines_fat.html
https://threejs.org/examples/webgl_lines_fat_wireframe.html

And in the current dev branch:

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_materials_wireframe.html
