### ISSUE TITLE
Rawshader example - wrong variable naming and value.

### ISSUE THREAD

**Issue by lab101** [mrdoob/three.js#17112]
Hey,

Was looking into the rawshader example it's a bit confusing because there is a variable called **triangles** which make you think that this will be the number of triangles on screen while it's actually just the number of vertices. Also the number 500 is strange because the vertices need to be a multiplier of 3.

https://github.com/mrdoob/three.js/blob/fa1768032860a003835a821155c0ab14c83f173b/examples/webgl_buffergeometry_rawshader.html#L85

Greets
Kris

**Comment by moraxy** [comment]
Introduced in 749353837a7eccea18a35f34ff78ff8a0abce32f which went from
```js
for ( var i = 0, l = triangles * 3 * 3; i < l; i += 3 ) {
```
to
```js
for ( var i = 0; i < triangles; i ++ ) {
```
For comparison: [old](https://raw.githack.com/mrdoob/three.js/05d67cc5b9b98e66c10ba8461a805b46af49f854/examples/webgl_buffergeometry_rawshader.html) [new](https://raw.githack.com/mrdoob/three.js/749353837a7eccea18a35f34ff78ff8a0abce32f/examples/webgl_buffergeometry_rawshader.html)

**Comment by Mugen87** [comment]
You are right, that's confusing. I would rename `triangles` to just `vertexCount` and set it to 600.

Do you want to make the PR with the change?

**Comment by lab101** [comment]
okay will make a PR later this weekend.
