### ISSUE TITLE
MeshStandardMaterial renders black on iOS

### ISSUE THREAD

**Issue by MrJoshBowman** [mrdoob/three.js#17113]
Using Three.js v105-106

I've just switched all my Geometry object code over to creating pure BufferGeometry and when I was testing it on my laptop across browsers the mesh and textures appeared without issue.

However, when i tested them on iOS browsers, any BufferGeometry with a MeshStandardMaterial rendered as black, still with its texture alphas.

I tried switching back to standard Geometry with MeshStandardMaterial and everything worked fine on iOS again. I also swapped back to BufferGeometry and tried a MeshBasicMaterial and MeshLambertMaterial, both of which worked totally fine. 

- [x] r106

##### Browser
- [x] all of them

##### OS
- [x] iOS v13 Public BETA

##### Hardware Requirements (graphics card, VR Device, ...)
- iPhone X
- iPad Pro 10.5"

**Comment by mrdoob** [comment]
There isn't much we can do without a working link or a jsfiddle...

**Comment by MrJoshBowman** [comment]
apologies, I couldn't replicate it using boilderplate code and the PlaneBufferGeometry.
I'm building my own PlaneBufferGeometry without indices which (because I can't get indices working) but after jumping on the three.js Slack channel, it appears that the issue is solved by adding 'precision: 'mediump' ' to the MeshStandardMaterial, based on this already open bug report: https://github.com/mrdoob/three.js/issues/14137 so I'll close this.

**Comment by WestLangley** [comment]
@MrJoshBowman Do not get into the habit of blaming the library when your code does not work.

**Comment by MrJoshBowman** [comment]
I submitted it because it was inconsistent behaviour. In the year I've been learning three.js I haven't ever posted a bug report or blamed the library.

'mediump' ignores normals for the MeshStandardShader at creation of geo and buffergeo producing non-black squares, and MeshLambertShader ignores normals at creation of geo and buffergeo producing non-black squares, That's inconsistent behaviour in the MeshStandardShader library, which i had to find a work around for.

I'm fine with being accused of my code not working because of a library inconsistency 'gotcha', and that's why I updated my report.

**Comment by mrdoob** [comment]
> It works fine on PCs and laptops, just not iOS hardware.

Would be great if you can figure out why that's the case.

**Comment by schlaegerz** [comment]
I am getting a similar problem, my stuff renders with MeshStandardMaterial just fine on most devices, but then on Galaxy S9 it goes completely crazy. I haven't been able to isolate the problem with a jsfiddle as its part of a complicated system, but I do find it weird that it only reproes on some devices. I ended up just doing a work around and checking for the user agent string and then switching to MeshPhongMaterial if it is on android

**Comment by Mugen87** [comment]
> but I do find it weird that it only reproes on some devices. 

I'm afraid that's not unusual. Different devices have different GPUs and drivers. Without a live example for reproduction it is almost impossible to find the root cause for this issue.
