### ISSUE TITLE
Post processing in release 106

### ISSUE THREAD

**Issue by bugsbun1** [mrdoob/three.js#17115]
##### Description of the problem
Hello guys I recently tried to add postprocessing with the latest threejs release 106.
As soon as i add the sepia effect pass to my composer , my screen goes black with no errors .
On commenting  line "composer.addPass(sepiaPass)" I am able to render on the screen.

```
var composer = new THREE.EffectComposer(renderer);

var renderPass = new THREE.RenderPass(scene, camera);
composer.addPass(renderPass);
renderPass.renderToScreen = true;

var sepiaPass = new THREE.ShaderPass(THREE.SepiaShader);
composer.addPass(sepiaPass);
//sepiaPass.renderToScreen = true;


var render = function () {
 //renderer.render(scene, camera);
 composer.render();

  requestAnimationFrame( render );

};


render();
```

##### Three.js version

- [ ] Dev
- [x] r106
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the forum for help requests:

https://discourse.threejs.org/t/post-processing-in-release-106/8742
