### ISSUE TITLE
Examples: NRRD example broken

### ISSUE THREAD

**Issue by antonymarion** [mrdoob/three.js#17123]
Hello

Just to know if you are planning to fix this example in the next release?

https://threejs.org/examples/webgl_loader_nrrd.html

The slices move seems to be broken on v0.106.2
v0.101.1 still works.

Cheers,

**Comment by moraxy** [comment]
`git bisect` blames 6745ce099d5fbc94f964184d6fd020085b6d9042

**Comment by Mugen87** [comment]
> Just to know if you are planning to fix this example in the next release?

Sorry, we were not aware of that. The linked PR should fix the issue.

**Comment by mrdoob** [comment]
FYI @WestLangley
