### ISSUE TITLE
NormalNode not fully fixed

### ISSUE THREAD

**Issue by njarraud** [mrdoob/three.js#17126]
##### Description of the problem

NormalNode has been updated a few days ago however I do not believe that it has fixed the issue with the LOCAL scope.

See [jsfiddle](https://jsfiddle.net/r54qgebd/4/) with the dev version of three.js

- Objects displaying world normal seem to be represented properly: normal doesn't depend on the camera but only on the orientation of the object.

- Objects displaying local normal seem to be represented incorrectly: normal shall not depend on the camera and shall be identical independently of the object orientation. This is not the case and it currently behaves the same way as the view normal.

- Objects displaying view (camera) normal seem to be represented properly: normal are based on the camera view.

The solution with _vObjectNormal_  presented in this [post](https://github.com/mrdoob/three.js/issues/16975) seems to help but I don't know if it is a proper fix or only works in some cases.

NormalMapNode output doesn't seem to be correct either and it may be related to this issue. I will do some more testing on this one. Once we manage to get NormalNode outputting the expected values, we shall then recheck normalMapNode and BumpMapNode.

![normal](https://user-images.githubusercontent.com/45501180/62098193-83302d80-b2dd-11e9-9dfe-ed137bb7bf1a.jpg)

I created the exact same configuration in Blender where normals are properly represented for all 3 scopes. You can download the blend file [here](https://www.mecabricks.com/crossorigin/normal/normal.blend).

![normalBlender](https://user-images.githubusercontent.com/45501180/62098343-ff2a7580-b2dd-11e9-9816-8bbb0334f656.jpg)

/ping @sunag 

##### Three.js version

- [x] Dev
- [x] r106

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by sunag** [comment]
@njarraud Thank your nice explanation... I will see this in this weekend.

> The solution with vObjectNormal presented in this post seems to help but I don't know if it is a proper fix or only works in some cases.

Yes, I want to remove `requires` property as soon as possible. I need before fix NormalNode.LOCAL fix other nodes that use LOCAL instead of VIEW.

**Comment by sunag** [comment]
@njarraud This is already fixed but should I publishing the PR withing a few days.

**Comment by njarraud** [comment]
Thanks. Really looking forward to testing it!

**Comment by sunag** [comment]
@njarraud Sorry the delay, I fix the NormalNode.NORMAL. (I put VIEW by mistake https://github.com/mrdoob/three.js/pull/17265/commits/4d5fdc74bdab4bd01d19613f412a09dcb0cd52fb) You can see in this PR https://github.com/mrdoob/three.js/pull/17265.  Revision 8, contains big changes, for this reason, it can take a while

**Comment by njarraud** [comment]
Awesome. I currently use my own branch with quick fixes for the problems I encountered. Modifications look good. I'll try them when PR will be merged with the dev branch. Thanks again.
