### ISSUE TITLE
where is the LoaderSupport.js  &  OBJLoader2.js  in r106 ?

### ISSUE THREAD

**Issue by caelanChan** [mrdoob/three.js#17125]

**Comment by Mugen87** [comment]
The code was refactored and is now module based only. You can find the loader and related files here:

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/OBJLoader2.js
https://github.com/mrdoob/three.js/tree/master/examples/jsm/loaders/obj2

Notice that `LoaderSupport` has been removed. It's to study the related `OBJ2Loader` examples to understand the changes.

https://threejs.org/examples/?q=obj2
