### ISSUE TITLE
Index of BufferGeometry only works clockwise?

### ISSUE THREAD

**Issue by Janekdererste** [mrdoob/three.js#17129]
##### Description of the problem
I'm not quite sure whether this is a question or a suggestion for documentation improvement. If I create a simple indexed geometry like the following:
```
const vertices = new Float32Array([
      center[0] + 0,
      center[1] + 0,
      0,
      center[0] + 0,
      center[1] + 1000,
      0,
      center[0] + 1000,
      center[1] - 0,
      0,
      center[0] + 1000,
      center[1] + 1000,
      0,
    ])

    const geometry = new BufferGeometry()
    const positionsAttribute = new BufferAttribute(vertices, 3)
    geometry.addAttribute('position', positionsAttribute)

    geometry.setIndex([0, 2, 1, 1, 2, 3])

    const normals = new Float32Array([0, 0, 1, 0, 0, 1])
    geometry.addAttribute('normal', new BufferAttribute(normals, 3))

    const mesh = new Mesh(geometry, new MeshBasicMaterial({ color: 0xff3300 }))
    this.scene.add(mesh)
```
My scene will display a square. If I change the index to the following:
```
geometry.setIndex([0, 2, 1, 1, 3, 2])
```
The second triangle is not displayed. It seems like I have to specify the index for a fragment in a clockwise direction. Is this a bug or a feature? If it is a feature it would be nice to have a hint in the BufferGeometry documentation.

##### Three.js version

- [ ] Dev
- [ ] r106
- [ x] 105.2

##### Browser

- [] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer - not tested

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
>  Is this a bug or a feature?

It's neither a bug nor a feature. It's problem in your application. The order of vertices or indices should be consistent. If you switch from CCW to CW or vice verca, you get incorrect results.

I've created a live example with your code (https://jsfiddle.net/yrxh23aj/). As you can see, the second triangle is only visible from the back (I've added `OrbitControls` so it's easy to change the camera).

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more clarification for this topic.

**Comment by Janekdererste** [comment]
Oh, thanks for your answer. This certainly doesn't have to be in the documentation.
