### ISSUE TITLE
Deprecated CircleBufferGeometry

### ISSUE THREAD

**Issue by zosma180** [mrdoob/three.js#17130]
##### Description of the problem

The **CircleBufferGeometry** is marked as **deprecated** in the "CircleGeometry.d.ts" file.
The deprecation note suggest to use the BoxGeometry instead.
It is right?

##### Three.js version

- [ ] Dev
- [x] r106

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> It is right?

No. Looks like a copy/paste error. The note can be removed.

Would you like to do this change 😇

**Comment by zosma180** [comment]
> No. Looks like a copy/paste error. The note can be removed.

Ok. Thanks

> Would you like to do this change


Sure

**Comment by Mugen87** [comment]
That's the spirit 😊

**Comment by EliasHasle** [comment]
@zosma180 Welcome as contributor to three.js! 🎉 👏 🎶 💐 🚀 😅

**Comment by zosma180** [comment]
Thanks!
Nice to be part of it
