### ISSUE TITLE
Make use of WEBGL_multi_draw Extension

### ISSUE THREAD

**Issue by soadzoor** [mrdoob/three.js#17139]
Hey,

Today I saw some very exciting stuff at SIGGRAPH 2019 conference.
One I'm particularly interested in is WEBGL_multi_draw Extension, which - as far as I understand - could significantly reduce the number of draw calls by allowing better batching. Based on the speaker's sheet, this could lead to up to **70x** performance improvement in some cases, especially when there are a lot of objects to render.

Here are some information about this:

1. [https://www.khronos.org/registry/webgl/extensions/WEBGL_multi_draw](https://www.khronos.org/registry/webgl/extensions/WEBGL_multi_draw/)
2. [https://twitter.com/tojiro/status/1099056933783457797](https://twitter.com/tojiro/status/1099056933783457797)
3. [https://docs.google.com/presentation/d/1iznxalgXLLSWVNHQ6le9Gzv_TYzsD5R_gg8yT5ckf2A/edit#slide=id.g4c932beacf_5_0](https://docs.google.com/presentation/d/1iznxalgXLLSWVNHQ6le9Gzv_TYzsD5R_gg8yT5ckf2A/edit#slide=id.g4c932beacf_5_0)

Do we plan to support this extension? It would be awesome!

**Comment by mrdoob** [comment]
I think I would first try to create a good abstraction on top of instancing.

**Comment by Mugen87** [comment]
TBH, I have never understood this extension. What the actual difference from using just instance rendering?

**Comment by Usnul** [comment]
I believe it is intended for submitting render requests for varying geometry as opposed to instanced rendering where geometry is the same and instead we have additional "instanced" attributes. I guess it's like a limited draw command queue?

**Comment by mrdoob** [comment]
This is one of those where you wonder if it wouldn't be better to invest that time in WebGPU instead...

**Comment by soadzoor** [comment]
> This is one of those where you wonder if it wouldn't be better to invest that time in WebGPU instead...

As the creator of this issue, I say let's invest the time in WebGPU instead! 😄

**Comment by avesus** [comment]
This is to render multiple disconnected triangle strips without stop triangles really fast.
