### ISSUE TITLE
How to make the axis at the center of these objects instead of the origin of the group, and not move the position of the object

### ISSUE THREAD

**Issue by wenrenqiang** [mrdoob/three.js#17142]
![image](https://user-images.githubusercontent.com/35467304/62271158-81e03b80-b46a-11e9-9673-366a8e5fa968.png)

How to make the axis at the center of these objects instead of the origin of the group, and not move the position of the object

**Comment by wenrenqiang** [comment]
Prerequisites do not move the location of the original object
前提不移动原始物体坐标

**Comment by Mugen87** [comment]
Um, I'm not sure I understand. If you select the group object in the editor, the helper objects of `TransformControls` are placed at the position of the group. There is no way to change this.

**Comment by wenrenqiang** [comment]
@Mugen87 It’s actually a project of my own, edited with the editor, and now it’s solved.

**Comment by wenrenqiang** [comment]
![image](https://user-images.githubusercontent.com/35467304/62290228-6a697880-b493-11e9-9cab-7626e3c3451e.png)
I am not sure I updated the version of three.js using version 107 but it seems to have a bug.

**Comment by wenrenqiang** [comment]
@Mugen87 
When there is a sprite object in my scene, the radiation detection of three.js is reported incorrectly. The previous version did not have this error.

**Comment by yaoforworker** [comment]
你怎么解决的？大神
How did you solve it?

**Comment by wenrenqiang** [comment]
@yaoforworker 那个问题?

**Comment by Mugen87** [comment]
You have to setup your raycaster like so.

```js
raycaster.setFromCamera( coords, camera );
```

More information in: #17078

**Comment by wenrenqiang** [comment]
![image](https://user-images.githubusercontent.com/35467304/62928576-5efb4300-bdeb-11e9-98b3-47a41cacbe08.png)
@Mugen87How to set the editing controller so that it looks at the position specified to me when it is rotated, instead of always looking at the origin

**Comment by wenrenqiang** [comment]
I seem to have some problems with this setting.

**Comment by wenrenqiang** [comment]
I set it to THREE.Vector3(0,1,0) but it looks like some problems

**Comment by Mugen87** [comment]
@wenrenqiang Please use the [forum](https://discourse.threejs.org/) for help request. Github is actually not intended for this kind of questions.
