### ISSUE TITLE
why my graphics show like this？

### ISSUE THREAD

**Issue by amandaQYQ** [mrdoob/three.js#17141]
<img src="https://github.com/amandaQYQ/three.js/blob/master/img/14.png?raw=true" width="300px" height="300px"/>
I'am learning three.js, and i try some demos, this is one of my demo ,i don't know why it display like this? when i change the position of camera, it change, but why?

below is my code。Thanks!

<img src="https://github.com/amandaQYQ/three.js/blob/master/img/15.png?raw=true" />

请问，有人知道我这是什么原因造成的吗，改变相机的position的时候 会出现，尝试了很多次，找不到他的规律。

**Comment by troy351** [comment]
![image](https://user-images.githubusercontent.com/8372385/62273611-83146700-b470-11e9-9cc4-eddd22161e79.png)
Make it larger

Also, please ask questions [here](https://discourse.threejs.org)
