### ISSUE TITLE
Unable to use a WebGLRenderTargetCube as input for LightProbeGenerator

### ISSUE THREAD

**Issue by n2k3s2it** [mrdoob/three.js#17143]
Hey I'm trying to use a `WebGLRenderTargetCube` as input for the `LightProbeGenerator.fromCubeTexture()`.
But it only accepts `CubeTexture` not `WebGLRenderTargetCube`.

The reason I have a `WebGLRenderTargetCube` is because I'm using `CubeCamera` to create a snapshot of my scene and want to use that as my environment light info for the LightProbe.

I'm not sure what the visual representation of the `WebGLRenderTargetCube` is, as a `CubeTexture` has an array of 6 images pointing to each axis negatively and positively. So I don't know how to convert it myself.

Would it be possible to generate a `CubeTexture` from `WebGLRenderTargetCube` or let the  `CubeCamera` output a `CubeTexture` directly?

[(Asked here as well, as suggested.)](https://discourse.threejs.org/t/lightprobegenerator-from-webglrendertargetcube/8786/2)

**Comment by nipmarsh** [comment]
Hello,

I had the same issue and i implemented it.
https://github.com/mrdoob/three.js/pull/17282

Sincerely

**Comment by Mugen87** [comment]
Solved via #17790
