### ISSUE TITLE
window.onresize horizontal issue

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#17157]
This in not an r107 bug, it's older, but hard to tell how old.
A sample with many THREE features in action:
https://necromanthus.com/Test/html5/testA.html 
Everything looks and runs just fine.

If you reduce the window height, you'll get the right result:
![rescale-height_ok](https://user-images.githubusercontent.com/11772787/62359898-a6422380-b50f-11e9-874e-983592df3b60.jpg)

But if you reduce the window width, you'll get wrong result:
![rescale_width_bad](https://user-images.githubusercontent.com/11772787/62359950-c1ad2e80-b50f-11e9-9893-4460cd8a3db3.jpg)

Tested with the latest version of Chrome, Firefox and Edge.
It worked just fine serveral versions ago.

**Comment by Mugen87** [comment]
I does seem to work if I remove the `width` style of the `div` element with id `room`.

![image](https://user-images.githubusercontent.com/12612165/62366520-671fcc80-b527-11e9-8323-d04853750707.png)

Why are you defining dimensions for this `div` in the first place?

**Comment by RemusMar** [comment]
> Why are you defining dimensions for this div in the first place?

Hi Michael,
I don't define anything.
Just click on Tools / Web Developer / Page Source.

**Comment by RemusMar** [comment]
Damn ... you're right:

		room.style.width = winW+'px';
		room.style.height = winH+'px';

I don't even remember about those lines .

**Comment by Mugen87** [comment]
I think it should work if you remove these two lines. The enclosing `div` will be automatically as big as its content.

**Comment by RemusMar** [comment]
Yes, it's working without them.
But it's also working if you add those two lines in the "window.onresize" function as well.

As far as I remember, those lines were added a couple of years ago as a workaround for buggy browsers (mobile).

Anyway, I will test later today a few older THREE releases to see the results.
It still doesn't explain why the vertical rescale works fine in any situation.

You can close this ticket if you like.

**Comment by RemusMar** [comment]
I decided to keep those lines (the mobile browsers are still buggy).
Anyway, because more and more people are interested in THREE and post-processing effects, here is the BLOOM version:
http://necromanthus.com/Test/html5/testA_bloom.html
