### ISSUE TITLE
Does anyone know what caused this?

### ISSUE THREAD

**Issue by wenrenqiang** [mrdoob/three.js#17154]
![image](https://user-images.githubusercontent.com/35467304/62350240-bf110000-b534-11e9-8c57-8b4150c705b2.png)
![image](https://user-images.githubusercontent.com/35467304/62350258-cfc17600-b534-11e9-86b1-7cb8c9b8efd9.png)
Does anyone know what caused this?How to solve?

**Comment by wenrenqiang** [comment]
This is the code in the editor

**Comment by Mugen87** [comment]
Can you please describe how to reproduce this runtime error?

**Comment by wenrenqiang** [comment]
I modified most of the code in the editor.Checking the automatic save will report this error, why can't it be cloned?

**Comment by Mugen87** [comment]
Sorry, use the [forum](https://discourse.threejs.org/) or stackoverflow for such help requests.
