### ISSUE TITLE
NodePostProcessing setSize PixelRatio issue

### ISSUE THREAD

**Issue by njarraud** [mrdoob/three.js#17168]
##### Description of the problem

pixelRatio value from the renderer is lost when setSize function is called by NodePostProcessing. e.g. when the window is resized.

To test the issue on a high pixel density screen, resize the window while running [postprocessing / nodes](https://threejs.org/examples/?q=nodes#webgl_postprocessing_nodes) example.

/ping @sunag 

##### Three.js version

- [x] Dev
- [x] r107

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by sunag** [comment]
Hi @njarraud I am fixing this in r8 PR https://github.com/mrdoob/three.js/pull/17265
