### ISSUE TITLE
Ocean example breaks in WebVR mode

### ISSUE THREAD

**Issue by spacorum** [mrdoob/three.js#17170]
##### Description of the problem

Using Water.js (from the ocean shader example), there is a problem when entering WebVR mode (tested with Firefox + Oculus Rift and also with the Chrome + WebVR emulation). The mirror shader doesn´t rotate in sync with the rest of the scene, and it´s strechted. Also, if you rotate the camera enough, the sphere on one side will be completely covered by the ocean shader, while the other sphere will be completely visible (like there was a unique ocean shared between boths cameras, I can´t explain better).

 It looks like the whole reflection shader only reflects the original camera, but not the VR ones (notice the reflection in the middle, is the sphere you would see with VR disabled).

![Captura](https://user-images.githubusercontent.com/6510193/62423275-4f7b4c00-b6bf-11e9-9aee-25cbb4ba54d4.gif)

The problem seems to be in the **_scope.onBeforeRender()_** function in Water.js (commenting this code fixes the ocean size/position/rotation, but obviously there is no mirror shader on it (only a dark plane without any reflections).

* [jsfiddle] (https://jsfiddle.net/spacorum/61oqycz7/)
* [jsfiddle] (https://fiddle.jshell.net/spacorum/61oqycz7/show/)  
fullscreen direct link to allow WebVR emulation controls on Chrome

##### Three.js version

- [ ] Dev
- [X] r107

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Graphics card: NVIDIA GeForce GTX 1070
VR Device: Oculus Rift on Firefox (it can be replicated using Chrome + WebVR emulation)

**Comment by Mugen87** [comment]
Can you please also verify the sandbox example with your system? Does the mirror also break there?

https://threejs.org/examples/webvr_sandbox

**Comment by spacorum** [comment]
Yes, the mirror in the sandbox example also breaks in both cases (Firefox +
Oculus, Chrome + WebVR emulator). The mirror displays stretched and badly
located/rotated.

As the ocean, it works well in standard mode, but not with WebVR enabled.

**Comment by spacorum** [comment]
Yes, the mirror in the sandbox example also breaks in both cases (Firefox +
Oculus, Chrome + WebVR emulator). The mirror displays stretched and badly
located/rotated. As the ocean, it works well in standard mode, but not with WebVR enabled.

![Captura2](https://user-images.githubusercontent.com/6510193/62427316-ba457b00-b6f1-11e9-84f6-d1b2374b3f9a.gif)

**Comment by Mugen87** [comment]
I can reproduce with Chrome 76 Beta/WebXR and a Pixel 1. The rendering of the mirror is broken. Especially the location of the mirror in 3D space is totally wrong.

Everything is fine in non-XR mode.

**Comment by Mugen87** [comment]
Maybe related to #16367?

**Comment by spacorum** [comment]
Thanks, @Mugen87 this fixes the problem in the webvr_sandbox mirror.
But how could this be applied to the Water.js example? It doesn´t use the Reflector/Refractor files, so the problem is still there. Should this new code be used in scope.onBeforeRender() somehow?

**Comment by Mugen87** [comment]
Ops, I forgot that the ocean example uses `THREE.Water` and not `THREE.Water2` (which internally uses `THREE.Reflector`).

> Should this new code be used in scope.onBeforeRender() somehow?

I could image that the same code from the PR fixes the issue in `THREE.Water`. Can you place it at the very end of `onBeforeRender()` and see if that solves the problem? Otherwise I can verify this tomorrow myself.

**Comment by Mugen87** [comment]
In general we have not verified that all examples code can be used in XR. So depending on what example you convert to XR demos, you might encounter more files that need XR-related patches.

Hence, I'm going to change this issue to a feature request since `THREE.Water` never supported XR so far.

**Comment by Mugen87** [comment]
Um, I've tested your fiddles on a Pixel 1 but it's not possible to successfully enter VR. The site hangs up. It seems the mentioned enhancement to `onBeforeRender()` is not sufficient to run the example in VR.

**Comment by spacorum** [comment]
Can you take a look on a computer instead of the mobile? 
The fix magically worked for me on Water.js (tested on desktop and laptop), so maybe it´s a problem with Pixel? The reflection shows properly located/rotated after adding your code at the very end of **scope.onBeforeRender()**:

`// Restore viewport`
`var viewport = camera.viewport;`
`if ( viewport !== undefined ) {`
`        renderer.state.viewport( viewport );`
`}`

Now I can see the ocean perfectly on both cameras (left and right).
It goes smooth on Oculus Rift and also with Chrome XR emulator.

**Comment by Mugen87** [comment]
Interesting...yeah, the problem could be related to Daydream. 

Do you want to make a PR with the enhancement of `Water.js`?

**Comment by spacorum** [comment]
Sure. Never made one tbh, but I´m on it.

**Comment by Mugen87** [comment]
Great. I'll try to make another test with Oculus Quests the next days...

**Comment by spacorum** [comment]
Just updating this thread in case anyone lands here in the future. Although the original issue was related to the WebVR era, there's still a small but persistent bug affecting WebXR — again, related to viewport restoration.

If you're working on a project that combines `Water.js`, `Lensflare.js`, and WebXR, you might notice that when entering an XR session, the ocean somehow triggers the occlusion logic in the Lensflare. This results in the flares appearing as semi-transparent, barely visible, or even fully blocked by a mysterious dark rectangle. It looks like an occlusion artifact, but nothing is physically in front of the sun.

![Image](https://github.com/user-attachments/assets/0f125206-2ba9-432a-b418-1bdb1f208091)

The weird part is that the viewport values themselves are correct — both in normal rendering (standard camera) and in XR mode (per-eye cameras). The issue seems to be **how** the viewport is being restored. 

This line works perfectly in normal mode, but breaks Lensflare in XR:
`renderer.state.viewport(viewport);`

On the other hand, this line works fine in XR, but causes glitches or stretching in non-XR:
`renderer.setViewport(camera.viewport);`

So the workaround that’s been working for me (tested on r165) is:
```
if (renderer.xr.enabled && renderer.xr.isPresenting) {
    renderer.setViewport(viewport); // XR-safe
} else {
    renderer.state.viewport(viewport); // fallback for non-XR
}
```


I'm not exactly sure why this solves the problem — maybe someone can shed light on what happens internally during XR framebuffer rendering. Thanks for your amazing work!
