### ISSUE TITLE
Material Stencil Parameters broke MaskPass

### ISSUE THREAD

**Issue by vanruesc** [mrdoob/three.js#17175]
##### Description of the problem

Material stencil parameters have been added in #15611 thanks to the efforts of @gkjohnson. Unfortunately, these changes broke the `MaskPass` from the [post processing examples](https://threejs.org/examples/webgl_postprocessing_masking). This has been pointed out earlier by @WestLangley and @Mugen87 in [#15611](https://github.com/mrdoob/three.js/pull/15611#discussion_r309060124) and a fix was merged via #17136.

In #17136 @mrdoob commented that [the fix won't be published until r108](https://github.com/mrdoob/three.js/pull/17136#issuecomment-517493656) which is a bummer.
It would be nice if you could reconsider and publish a patch release for r107.

##### Three.js version

- [ ] Dev
- [x] r107
- [ ] r106

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
What's your use case? Does your project depend on Material Stencil and `MaskPass`?

**Comment by vanruesc** [comment]
My project currently doesn't use the new Material Stencil Parameters. I use the `MaskPass` to apply post processing effects to portions of the screen. Here's an example that uses `three` r106: https://vanruesc.github.io/postprocessing/public/demo/#pixelation

**Comment by mrdoob** [comment]
I see. And waiting for this month release (August 28th) is not an option?

**Comment by vanruesc** [comment]
I thought about waiting for r108 and using the current dev version, but both options felt wrong so I opened an issue instead. However, since you're recommending it, I might as well just wait.

Thanks for your time!
