### ISSUE TITLE
raycaster with set position to (x, 0, z) and set direction to (0, -1, 0) will return emtpy at some time

### ISSUE THREAD

**Issue by recoye** [mrdoob/three.js#17178]
##### Description of the problem
step 1:
create a raycaster
let ray = new THREE.Raycater();

setp2:
create box
let box = new THREE.BoxGeometry(1, 1, 1);

create panel
let panelGeometry = new THREE.PlaneBufferGeometry(100, 100);
panelGeometry.rotateX(Math.PI / -2);
let material = new THREE.MeshPhongMaterial( {
        color: 0x333333, 
        shading: THREE.FlatShading,
        transparent: true,
        opacity: 1,
    } );
let panel = new THREE.Mesh(panelGeometry, material);

step3:
move box with mouse moving
// rotation box
box.rotation.y = mouse1.x - mouse0.x
// move box
box.position.set(x, 0, z)

step4:
update ray origin to box position
ray.set(box.position, new THREE.Vector3(0, -1, 0));
let result = ray.intersectObject(panel);

// BUG here
the length of result as we known must be more than 1,but it return 0 at some time.

this is the demo to show this issue,the box's color will change when the result return 0
 
* [jsfiddle](http://jsfiddle.net/ewb89g2m/5/) (latest release branch)
* [jsfiddle](http://jsfiddle.net/ewb89g2m/6/) (dev branch)

##### Three.js version

- [ ] Dev
- [ ] r107
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
The problem is that the origin of your ray lies directly on the surface of your plane. Due to floating point inaccuracies there might be cases where no intersection is detected. You can easily avoid this issue by adding a little tolerance value to the origin of your ray:

http://jsfiddle.net/eu58vpnj/1/

**Comment by recoye** [comment]
thanks
