### ISSUE TITLE
Why GLTF 1.0 file not load in gltfLoader ?

### ISSUE THREAD

**Issue by raviarsuda05** [mrdoob/three.js#17172]
When i try to load gltf 1.0 file in gltfLoader its give some exception and errors.

**Comment by Mugen87** [comment]
`GLTFLoader` only supports `glTF 2.0` assets. Use [LegacyGLTFLoader](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/deprecated/LegacyGLTFLoader.js) instead.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help with `GLTFLoader`.

**Comment by raviarsuda05** [comment]
Ok Thanks for your information
