### ISSUE TITLE
After code update in Trackballcontrols.js giving error

### ISSUE THREAD

**Issue by vatansbeytr** [mrdoob/three.js#17187]
This update cause error: https://github.com/mrdoob/three.js/commit/4e9527159a63302ac7494413281039f517f2cd95#diff-825d6d415c7142a9d0520f6ae0c45928

Error:
```
TrackballControls.js:38 Uncaught TypeError: Cannot read property 'ROTATE' of undefined
    at new THREE.TrackballControls (TrackballControls.js:38)
    at loader.js:37

```
```
loader.js:
`window.addEventListener("load", function () {
    "use strict";
    
    var w = 560, h = 560;
```
    
    var renderer = new THREE.WebGLRenderer();
    renderer.setSize(w, h);
    var view = document.getElementById("view");
    view.appendChild(renderer.domElement);
    
    var camera = new THREE.PerspectiveCamera(45, w / h, 1, 1000);
    camera.position.set(0, 0, 50);
    
    
    var scene = new THREE.Scene();
    scene.add(new THREE.AmbientLight(0x666666));
    
    var scene = new THREE.Scene(); // initialising the scene
    scene.background = new THREE.Color( 0xff0000 );

    renderer.setClearColor( 0xffffff, 0);

    var light1 = new THREE.DirectionalLight(0xffffff);
    light1.position.set(0, 100, 100);
    scene.add(light1);
    
    var light2 = new THREE.DirectionalLight(0xffffff);
    light2.position.set(0, -100, -100);
    scene.add(light2);
    
    var mat = new THREE.MeshPhongMaterial({
        color: 0x339900, ambient: 0x339900, specular: 0x339900,
    });
    var obj = new THREE.Mesh(new THREE.Geometry(), mat);
    scene.add(obj);
    
 _**Cause Error -->**_  **var controls = new THREE.TrackballControls(camera, view);**

    var loop = function loop() {
        requestAnimationFrame(loop);
        //obj.rotation.z += 0.05;
        controls.update();
        renderer.clear();
        renderer.render(scene, camera);
    };
    loop();
    
    // file load
    var openFile = function (file) {
        var reader = new FileReader();
        reader.addEventListener("load", function (ev) {
            var buffer = ev.target.result;
            var geom = loadStl(buffer);
            scene.remove(obj);
            obj = new THREE.Mesh(geom, mat);
            scene.add(obj);
        }, false);
        reader.readAsArrayBuffer(file);
    };
    
    // file input button
    var input = document.getElementById("file");
    input.addEventListener("change", function (ev) {
        var file = ev.target.files[0];
        openFile(file);
    }, false);
    
    // dnd
    view.addEventListener("dragover", function (ev) {
        ev.stopPropagation();
        ev.preventDefault();
        ev.dataTransfer.dropEffect = "copy";
    }, false);
    view.addEventListener("drop", function (ev) {
        ev.stopPropagation();
        ev.preventDefault();
        var file = ev.dataTransfer.files[0];
        openFile(file);
    }, false);
}, false);`

**Comment by Mugen87** [comment]
This change was done in order to make the API of `TrackballControls` more similar to `OrbitControls`. 

There is no problem with the official example: https://threejs.org/examples/misc_controls_trackball

I'm unable to see in your code what your are doing different. Consider to make simple live example that demonstrates the issue: https://jsfiddle.net/f2Lommf5/

**Comment by Mugen87** [comment]
Closing for now.
