### ISSUE TITLE
GLTFLoader: bone animation is broken after calling optimize

### ISSUE THREAD

**Issue by JordyvanDortmont** [mrdoob/three.js#17180]
##### Description of the problem

The bone animation with linear interpolation loaded with the `GLTFLoader` does not work when `KeyFrameTrack.optimize` is called. I've included [a sample asset](https://send.firefox.com/download/54e78eaa251196eb/#ntoIZYK2h39BFoZVBeiDbw) for which this is the case.

I also bisected the problem and this has been an issue since #15893. If the changes to the following lines are reverted, the bone animation does work after calling `KeyFrameTrack.optimize`. https://github.com/mrdoob/three.js/commit/ec1d5a7a72f9afbf40c00c5db6b30d298820b860#diff-43f9265a3da0d9ebbf235517b2541578L2910-R2903

##### Three.js version

- [x] Dev
- [x] r103 - r107

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
@JordyvanDortmont the sample asset link has expired, would you mind resharing it? You can drag .ZIP files directly into GitHub comments.

**Comment by JordyvanDortmont** [comment]
@donmccurdy instead, for ease of access, I've made a branch on our `three.js` fork with an example that displays the behavior.

I've added one line to the example that calls ` optimize` on all animations.

https://github.com/dialoguetrainer/three.js/tree/optimize_bone_animation
https://raw.githack.com/dialoguetrainer/three.js/optimize_bone_animation/examples/webgl_animation_skinning_blending.html
