### ISSUE TITLE
Shadow matrix calculations tidy up

### ISSUE THREAD

**Issue by supereggbert** [mrdoob/three.js#17198]
I'm just looking over the shadow mapping code and it looks like the shadow camera update and shadow matrix calculations are currently happening in WebGLShadowMap.js. Would these not be better off in there respective LightShadow classes? It would get rid of a whole bunch of type dependant conditions and make the whole thing cleaner. It looks like that's the ultimate indent and the current situation is just a legacy remnant; but I thought I'd check before doing any work to tidy it up, just in case I'm missing something.

**Comment by mrdoob** [comment]
Yeah, it is legacy remnant indeed. Definitely needs some clean up 🙏
