### ISSUE TITLE
Broken fragment shader in webgl_loader_nodes example

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#17197]
##### Description of the problem
Load up example `webgl_loader_nodes`([dev link](https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_loader_nodes.html)) and select `xray` in the box to the right.

```
THREE.WebGLShader: gl.getShaderInfoLog() fragment
ERROR: 0:774: ',' : syntax error

774: gl_FragColor = vec4( outgoingLight, pow( ( dot( , nodeU3 ) + nodeU4 ), nodeU5 ) );
```
Note the missing variable after `dot(`. The line in question seems to be
https://github.com/mrdoob/three.js/blob/f190ca64c182826b4402c07dc406523558840cfa/examples/jsm/nodes/materials/nodes/PhongNode.js#L319-L323
where `alpha.result` is `pow( ( dot( , nodeU3 ) + nodeU4 ), nodeU5 )`

I'm getting no errors from all the default examples from `webgl_materials_nodes` however.

##### Three.js version

- [x] Dev

##### Browser

- [x] Chrome
- [x] Firefox

##### OS

- [x] Linux

**Comment by moraxy** [comment]
Works fine in `r106`

**Comment by sunag** [comment]
Sorry, for some reason I have not seen this post. VIEW scope will be added again in the next PR.

**Comment by sunag** [comment]
Fix here https://github.com/mrdoob/three.js/pull/17265/commits/4d5fdc74bdab4bd01d19613f412a09dcb0cd52fb in this PR https://github.com/mrdoob/three.js/pull/17265
