### ISSUE TITLE
MeshNormalMaterial: Can't use clippingPlanes with flatShading

### ISSUE THREAD

**Issue by troy351** [mrdoob/three.js#17192]
##### Description of the problem

```
THREE.WebGLProgram: shader error:  0 35715 false gl.getProgramInfoLog No compiled fragment shader when at least one graphics shader is attached.
THREE.WebGLShader: gl.getShaderInfoLog() vertex
ERROR: 0:109: 'vViewPosition' : redefinition
```

Please also include a live example if possible. You can start from these templates:
https://jsfiddle.net/89q1zs23/

##### Three.js version

- [ ] Dev
- [x] r107
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I can confirm this bug. It happens when `flatShading` is set to `true` and clipping planes are used with `MeshNormalMaterial` because the shader chunk `clipping_planes_pars_vertex` and `normal_vert.glsl.js` from the shader lib define `vViewPosition`.

**Comment by troy351** [comment]
Is this just a variable renaming thing? If so, I'll just fixed myself as a quick solution
