### ISSUE TITLE
 texture.minFilter is null when adding gltf object

### ISSUE THREAD

**Issue by DerouineauNicolas** [mrdoob/three.js#17203]
Hi, thanks for this awesome tool which is threejs.

Using threejs version from the cdn dev/build/three.js and the sample code for gltf loading, 

        loader.load(
          // resource URL
          'models/obj2gltf.gltf',
          // called when the resource is loaded
          function ( gltf ) {

            scene.add( gltf.scene );

            gltf.animations; // Array<THREE.AnimationClip>
            gltf.scene; // THREE.Scene
            gltf.scenes; // Array<THREE.Scene>
            gltf.cameras; // Array<THREE.Camera>
            gltf.asset; // Object

          },
          // called while loading is progressing
          function ( xhr ) {

            console.log( ( xhr.loaded / xhr.total * 100 ) + '% loaded' );

          },
          // called when loading has errors
          function ( error ) {

            console.log( 'An error happened' );

          }
        );

I'm getting the following error message when adding the gltf.scene to the scene: 
    Error: WebGL warning: texParameter: pname 0x2801: Invalid param 0x0000. 10 three.js:20712:9

The gltf object was generated from obj2gltf (from an obj and mtl file) and is correctly displayed in in gltf viewer. Any clue about what could be causing this issue ?

**Comment by Mugen87** [comment]
Can you please share `obj2gltf.gltf` in this issue?

**Comment by DerouineauNicolas** [comment]
Hi, A sample file can be found here:

http://the.ndero.ovh/file/obj2gltf.gltf

**Comment by Mugen87** [comment]
Um, I have no console warning when I import the asset in this `three.js` based `glTF-viewer`:

https://gltf-viewer.donmccurdy.com/

**Comment by DerouineauNicolas** [comment]
Yes, me neither, but I wanted to have a standalone example, so I took the example from https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_gltf.html and just removed the RGBELoader and used only the gltf loader. This is where I got the warning/error. The code I'm using is this one:

        var container, stats, controls;
        var camera, scene, renderer;
        // Instantiate a loader
        var loader = new THREE.GLTFLoader();

        // Optional: Provide a DRACOLoader instance to decode compressed mesh data
        THREE.DRACOLoader.setDecoderPath('../');
        loader.setDRACOLoader(new THREE.DRACOLoader())

        init();
        animate();

        function init() {

            container = document.createElement('div');
            document.body.appendChild(container);

            camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.25, 20);
            camera.position.set(- 1.8, 0.9, 2.7);

            scene = new THREE.Scene();

            // Load a glTF resource
            loader.load(
                // resource URL
                'models/obj2gltf.gltf',
                // called when the resource is loaded
                function (gltf) {

                    scene.add(gltf.scene);

                    gltf.animations; // Array<THREE.AnimationClip>
                    gltf.scene; // THREE.Scene
                    gltf.scenes; // Array<THREE.Scene>
                    gltf.cameras; // Array<THREE.Camera>
                    gltf.asset; // Object
                },
                // called while loading is progressing
                function (xhr) {

                    console.log((xhr.loaded / xhr.total * 100) + '% loaded');
                },
                // called when loading has errors
                function (error) {

                    console.log('An error happened');

                });

            renderer = new THREE.WebGLRenderer({ antialias: true });
            renderer.setPixelRatio(window.devicePixelRatio);
            renderer.setSize(window.innerWidth, window.innerHeight);
            renderer.gammaOutput = true;
            container.appendChild(renderer.domElement);

            controls = new THREE.OrbitControls(camera, renderer.domElement);
            controls.target.set(0, - 0.2, - 0.2);
            controls.update();

            window.addEventListener('resize', onWindowResize, false);

            // stats
            //stats = new Stats();
            //container.appendChild( stats.dom );

        }

        function onWindowResize() {

            camera.aspect = window.innerWidth / window.innerHeight;
            camera.updateProjectionMatrix();

            renderer.setSize(window.innerWidth, window.innerHeight);

        }

        //

        function animate() {

            requestAnimationFrame(animate);

            renderer.render(scene, camera);

        }

**Comment by Mugen87** [comment]
I'm unable to reproduce on my system (iMac, Chrome 76.0.3809.100).

**Comment by DerouineauNicolas** [comment]
I wasn't using the latest version of GLTFLoader, that was the reason. Thanks for your help !
