### ISSUE TITLE
ColorKeywords in Euler.d.ts

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#17210]
Are the `ColorKeywords` supposed to be in `Euler.d.ts`? 
https://github.com/mrdoob/three.js/blob/d41db0e13e26a610a04e5ff20a66c0a18faf216d/src/math/Euler.d.ts#L5-L14
Apparently they've been there since `Euler.d.ts` got imported. Shockingly, nothing in `Euler` references them.

**Comment by Mugen87** [comment]
I think you can just remove this namespace.

**Comment by 97amarnathk** [comment]
@Mugen87  I would love to start in threeJS contributions with this. Can I have this issue assigned to me?

**Comment by Mugen87** [comment]
It seems @moraxy gave you a like so why not 😉

**Comment by 97amarnathk** [comment]
Sure. I will try to do this by tomorrow. :)

**Comment by 97amarnathk** [comment]
@Mugen87  

I have submitted a PR addressing this issue.
https://github.com/mrdoob/three.js/pull/17261
