### ISSUE TITLE
Docs: use jsfiddle or codepen?

### ISSUE THREAD

**Issue by guettli** [mrdoob/three.js#17213]
On https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene I read:

>Before you can use three.js, you need somewhere to display it. Save the following HTML to a file on your computer, along with a copy of three.js in the js/ directory, and open it in your browser.

It would be very nice if you could jsfiddle or codepen for the examples.

Same here: https://threejs.org/docs/index.html#manual/en/introduction/How-to-run-things-locally

**Comment by Mugen87** [comment]
Regarding `Creating-a-scene`, similar code is already available in the readme file. It also contains a link to a fiddle: https://jsfiddle.net/f2Lommf5/

I think it's okay to put this link or another fiddle with the exact code from the documentation at the end of `Creating-a-scene` (section `The result`).

I'm not sure how a live example would be helpful in `How to run things locally`. The guide is mainly focused on local web server configuration but not client-side related stuff.
