### ISSUE TITLE
webgl_loader_ctm broken

### ISSUE THREAD

**Issue by moraxy** [mrdoob/three.js#17231]
##### Description of the problem
Can't find `examples/jsm/loaders/ctm/CTMLoader.js` ([current dev](https://raw.githack.com/mrdoob/three.js/61ad2baf329e8e23ad7cd0846d3ffe9bf2c00992/examples/webgl_loader_ctm.html))  
Used to work in [`r107`](https://raw.githack.com/mrdoob/three.js/r107/examples/webgl_loader_ctm.html)

Hinted at in #17061, maybe related to c4f53e0b4afe365d94da9230d2c9273a57c0561f? The commit message for that is
```
# Conflicts:
#	examples/webgl_loader_ctm.html
```

##### Three.js version

- [x] Dev
- [ ] r107

**Comment by WestLangley** [comment]
`CTMLoader` was removed in #16949.

**Comment by Mugen87** [comment]
The change is also noted in the migration guide:

https://github.com/mrdoob/three.js/wiki/Migration-Guide#r107--r108

**Comment by moraxy** [comment]
Oh I see, I was testing by looping over `examples/*.html`. Didn't realize `webgl_loader_ctm` is no longer listed in `files.js` - sorry.

**Comment by vf2e** [comment]
What if I want to load a ctm file now?

**Comment by Mugen87** [comment]
It's best to checkout `R107` and copy the CTM files to your application code.

**Comment by vf2e** [comment]
> It's best to checkout `R107` and copy the CTM files to your application code.

thx，that's works.But I still don't understand why you remove the CTM loader .

**Comment by mrdoob** [comment]
> thx，that's works.But I still don't understand why you remove the CTM loader .

Because GLTF+Draco is a better fit for what CTM tried to solve.
