### ISSUE TITLE
'OBJLoader' is not exported from 'three' (imported as 'THREE').

### ISSUE THREAD

**Issue by engmagdy87** [mrdoob/three.js#17246]
I use three js with react 16
when I use 
`
var loader = new THREE.OBJLoader();
`

I got this error
`
'OBJLoader' is not exported from 'three' (imported as 'THREE').
`

I use 
react 16.8.6
three 0.107.0
Chrome 76.0.3809.100
windows 10

**Comment by Mugen87** [comment]
You have to import `OBJLoader` separately. It should look like so when using the `three` npm package:
```js
import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader.js';
```
