### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by MercureTony** [mrdoob/three.js#17248]
Hi! How can I start contributing to this open-source project?

**Comment by mrdoob** [comment]
How do you want to contribute?

Fix a bug? Add a feature? Improve the docs? ...

**Comment by MercureTony** [comment]
Hey! I would like if it's possible, try fixing a bug ( especially in javascript) or even improve the documentation:).

**Comment by Mugen87** [comment]
Maybe the following is a good "first issue" 😇 

I've noticed that the header comment in the source files are not always at the same position. Sometimes they are at the top of the file like here (so above the imports):

https://github.com/mrdoob/three.js/blob/a63f7f8cb09c8643703a0850fbabc6af3b2d0d06/src/audio/Audio.js#L1-L8

Sometimes they are above the class definition (so beneath the imports):

https://github.com/mrdoob/three.js/blob/a63f7f8cb09c8643703a0850fbabc6af3b2d0d06/src/animation/AnimationAction.js#L1-L14

@mrdoob Do you have a preference where the header should be placed? If so, @MercureTony could align this in all `src` files.

**Comment by looeee** [comment]
The docs always need work. 

There's a doc page for [OrbitControls](https://threejs.org/docs/#examples/en/controls/OrbitControls), but none of the other controls, for example.

**Comment by mrdoob** [comment]
> @mrdoob Do you have a preference where the header should be placed? 

Yes, I think the header comment should be on top.

**Comment by mrdoob** [comment]
@MercureTony Depending of your level of experience with the library, you can have a look at [these bugs](https://github.com/mrdoob/three.js/issues?q=is%3Aissue+is%3Aopen+label%3ABug). If you're just starting, I would recommend just using the library in your projects and eventually you'll find something that can be improved.

**Comment by MercureTony** [comment]
Thank you for your replies! I haven't use the library that much, but I am willing to learn how to use it.
@Mugen87, Okay I will take a look at them.
