### ISSUE TITLE
OrthographicTrackballControls goes into a infinite loop on pan

### ISSUE THREAD

**Issue by drcmda** [mrdoob/three.js#17250]
##### Description of the problem

see: https://codesandbox.io/s/musing-rgb-ouriz

this code: https://github.com/mrdoob/three.js/blob/master/examples/jsm/controls/OrthographicTrackballControls.js#L273-L275

seems to always yield true, so it goes into the scope block and flags _changed = true, which later on creates a dispatchEvent. if three is rendering in a loop the event will fire on every frame.

in our project we render on demand. for this to work we listen to the cameras events in order to switch off the renderloop once the camera is done moving. this works great, but on pan it just keeps on rendering.

##### Three.js version

- [x] r107

##### Browser

- [x] Chrome

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
I can confirm this issue. Interestingly, it does not occur in `TrackballControls`.
