### ISSUE TITLE
do gpu picking with 1x1 pixel render target BUG

### ISSUE THREAD

**Issue by xjindf** [mrdoob/three.js#17257]
//set the view offset to represent just a single pixel under the mouse,When THREE.Points is used in scenarios, it cannot be picked up correctly.
        self.camera.setViewOffset(self.renderer.domElement.width, self.renderer.domElement.height, mouse.x * window.devicePixelRatio | 0, mouse.y * window.devicePixelRatio | 0, 1, 1);
        self.renderer.setRenderTarget(self.pickingTexture);
        self.renderer.render(self.pickingScene, self.camera);
        self.camera.clearViewOffset();
        self.renderer.readRenderTargetPixels(self.pickingTexture, 0, 0, 1, 1, pixelBuffer);

        //Use the following code GPU to picking the normal work
        self.renderer.setRenderTarget(self.pickingTexture);
        self.renderer.render(self.pickingScene, self.camera);
        self.renderer.readRenderTargetPixels(self.pickingTexture, mouse.x, self.pickingTexture.height - mouse.y, 1, 1, pixelBuffer);

I'm not sure whether it was caused by camera. setViewOffset or what I did wrong?

**Comment by Mugen87** [comment]
Sorry, github is not a help site. Please use the forum to verify if the problem is caused by your code:

https://discourse.threejs.org/t/three-points-use-gpu-picking-is-not-work/9045
