### ISSUE TITLE
Water2: Can it be used for an ocean scenario?

### ISSUE THREAD

**Issue by EliasHasle** [mrdoob/three.js#17251]
##### Three.js version

- [ ] Dev
- [ X ] r107
- [ ] ...

With some settings, the water will at a certain angle change rapidly. I do not know/understand the source well enough to pinpoint what causes this, though. I have so far seen this problem only with a wide/high plane and high scale parameter.

Running demonstration of the glitch (just uploaded, so maybe not online yet):
http://eliashasle.github.io/three.js/examples/webgl_water_bug.html

**Comment by Mugen87** [comment]
I'm sure the implementation does not produce good results with an arbitrary parameterization. How about making the plane smaller `var waterGeometry = new THREE.PlaneBufferGeometry( 2000, 2000 );` and also the scale factor?

**Comment by EliasHasle** [comment]
I increased the geometry and the scale proportionally. The point with having a big plane is to use it as an "infinite" ocean. A respectable use case, in my opinion. I find it strange that a mere 100x scale-up can produce such a large artifact. Note that it behaves well from all other angles.

**Comment by Mugen87** [comment]
> The point with having a big plane is to use it as an "infinite" ocean

This water effect comes from Portal 2 and is not intended to use it for an ocean scenario.

BTW: The people you have pinged have nothing to do with `Water2`. I was the developer.

**Comment by EliasHasle** [comment]
> This particular water effect comes from Portal 2/LFD 2 and is not intended for an ocean scenario. 

Good to know, but _that does not explain the glitch_. It does, however, explain why there is no cool sun reflection effect. I was under the impression that `Water2` would somehow replace `Water`, but if that is not the case, it may turn out wiser to use `Water`.

> BTW: The people you have pinged have nothing to do with `Water2`. I was the developer.

OK! I pinged Slayvin because he is the author of Reflector, and jbouny because he is the original author of `Water` (as far as I know), which I think relies on the same principle for the distorted reflection (however implemented a bit differently).

**Comment by Mugen87** [comment]
> Good to know, but that does not explain the glitch.

I would be great if you can have a look at the code. Some time has passed when I've developed this so I need to study the  implementation like everyone else.

**Comment by EliasHasle** [comment]
Thank you. I understand. I will look at the code, one day, but I am afraid it is of relatively low priority for me too. (Switching to `Water` is a quick fix.)

**Comment by Slayvin** [comment]
@EliasHasle 
This looks like a simple rasterization/clipping issue.
Simply increase the geometry of your water plane, like so:
```js
var waterGeometry = new THREE.PlaneBufferGeometry( 2000, 2000, 2, 2 );
```
This seems nothing, but this will 'divide' your plane, making it 4 polygons ( instead of 1), but will help the rasterizer a lot in its calculation!
If the glitch is still visible, try to increase the division more.

**Comment by EliasHasle** [comment]
@Slayvin Thank you for your reply. This is a kind of error that I haven't heard about before. The simple modification you propose indeed removes the glitch in the test case. I will close the issue now, and reopen if the problem resurfaces.

@Mugen87 Thanks to you too. Great work on the shader. It is beautiful even without the flow texture, and even better with it. 👍

**Comment by wmcmurray** [comment]
> @EliasHasle
> This looks like a simple rasterization/clipping issue.

Huge thanks @EliasHasle !! 👍🏻 

I've been scratching my head over glitches related to this for such a long time... it's all solved now ! ✨
