### ISSUE TITLE
the phongmaterial's problem in r107

### ISSUE THREAD

**Issue by Lin150202102281** [mrdoob/three.js#17278]
if i not have the colour blindness, the phong material doesn't work by the r107

my code:
  ...
  this.materialClient = new THREE.MeshLambertMaterial({color:0x5CACEE, transparent:true, 
  opacity:0.8, side:THREE.DoubleSide});
  ...
  ...
  scope.cache.children[i].material = scope.materialClient;
  
![GIF](https://user-images.githubusercontent.com/26421690/63237848-2ab5d580-c276-11e9-956f-5f57dae8e0c1.gif)

**Comment by Mugen87** [comment]
> , the phong material doesn't work by the r107

Why do you use `MeshLambertMaterial` then? `MeshPhongMaterial` would be the correct one.
