### ISSUE TITLE
how to play max format 3D file in three.js?

### ISSUE THREAD

**Issue by datavisorfrankhe** [mrdoob/three.js#17270]
Hello, I have a question on how to quick jump into three.js.

I got a requirment to play .max fomat, this is the folder structure i received from my prodiers.

```
[fileName].max
MAXFILES.TXT
- Users
 .....(a lot data here...)
```

I am interested in using three.js to play these 3D images. But I can not find a proper way, what loader to use etc.

Can I get some suggestions from three.js expert on if this is doable using three.js, if doable, what shall I do next?

Thanks

**Comment by donmccurdy** [comment]
Here is the [list of available three.js loaders](https://github.com/mrdoob/three.js/tree/dev/examples/js/loaders), but `.max` is not supported.

A `.max` file can pretty much only be opened by Autodesk 3DS Max. You, or the artist, will need to open the file in 3DS Max and export the file in a format that other programs can read.  I would suggest exporting to glTF (with [this exporter](https://doc.babylonjs.com/resources/3dsmax_to_gltf)) or FBX.

If you need more help with this, I'd recommend the [threejs forums](https://discourse.threejs.org/).
