### ISSUE TITLE
Fog based on depth not view distance?

### ISSUE THREAD

**Issue by supereggbert** [mrdoob/three.js#17274]
Just playing with some fog and noticed something that seems a bit off, I'm not sure if it's intentional but it looks like fog is currently using the camera depth, should it not be using view distance? Using depth as apposed to distance means what you see is dependant on camera direction and you get a horizontal line across the scene instead of a nice circular fall off and that doesn't seem right.

##### Three.js version

- [x] Dev
- [x] r107
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by supereggbert** [comment]
Here is a quick example of what I was expecting compared to what I'm getting:
![example](https://user-images.githubusercontent.com/166785/63211355-da137080-c0ed-11e9-8831-385dfda34afd.jpg)

**Comment by mrdoob** [comment]
We tried to fix this last year: https://github.com/mrdoob/three.js/issues/14601 https://github.com/mrdoob/three.js/pull/14602 https://github.com/mrdoob/three.js/issues/14601#issuecomment-409791978 https://github.com/mrdoob/three.js/pull/14617

**Comment by supereggbert** [comment]
Sorry, I completely forgot to check the closed issues. I've hacked round the problem, and it looks like an easy fix given current code base vViewPosition is already setup so it's only a minor change. I'll sort out a PR.

**Comment by EliasHasle** [comment]
That sounds like good idea. I guess I will wait until your PR is merged before I introduce FogExp (#17264, step 2. Step 1 is merged to dev.)

**Comment by EliasHasle** [comment]
Anyway, it is debatable whether depth-based fog is really wrong in all cases. If you consider the screen as a window to the game world, why should there be fog on your side? And in fact there is always some "fog" in the real air, and this will in some cases (very thin game fog or heavy smoking in front of the screen) more than compensate...
