### ISSUE TITLE
how to cut a whole panorama image into side images

### ISSUE THREAD

**Issue by datavisorfrankhe** [mrdoob/three.js#17275]
I wondered if there is any standard on how to cut a panorama.

I have a whole panorama image, but in order to play panorama using JS library, I have to provide left/front/right/back/top/bottom images separately, each one is a square. So I am thinking to cut the whole panorama file into these six equal sized smaller images.

I tried to search online how to prepare these qual sized images, but can not find any standard.

Does anyone have idea on how to prepare the images?

Thanks

**Comment by mrdoob** [comment]
You can use this tool:
https://discourse.threejs.org/t/hdri-spherical-map-to-cubemap-converter/3555
