### ISSUE TITLE
Evaluate code auto-formatting

### ISSUE THREAD

**Issue by enomado** [mrdoob/three.js#17288]
- Fast typing
- Much simpler diffs
- It gives some freedom on line breaks so matrix, for example, shouldn't be formatted inline. But there is ingoring also exists

**Comment by Mugen87** [comment]
I'm not sure I understand your issue. What do you expect here from the `three.js` project?

**Comment by donmccurdy** [comment]
The project already has an [eslint config](https://github.com/mrdoob/three.js/blob/dev/package.json#L27-L44), so `eslint --fix` should already work. But I don't know that we would want to require it for every PR, or apply it to the existing codebase wholesale. It's just there for those who find automation makes it easier to follow the styleguide.

**Comment by enomado** [comment]
I notice  https://github.com/mrdoob/three.js/issues/11552 and https://github.com/mrdoob/three.js/issues/15545 and search issue where I can read discussion about using some auto-formatting tools like prettier to do format-on-save in editor.

Looks like I find [Mr.doob's Code Style™](https://github.com/mrdoob/three.js/wiki/Mr.doob%27s-Code-Style%E2%84%A2). Is there any config for this style?

@donmccurdy, does this tool actually fix/add/remove trailing commas, spaces? Like here https://prettier.io/playground/

**Comment by gkjohnson** [comment]
> Is there any config for this style?

The ESLint config for this project is defined in the `package.json`: 

https://github.com/mrdoob/three.js/blob/dev/package.json#L27-L44

> does this tool actually fix/add/remove trailing commas, spaces?

Running eslint --fix can auto-fix all those issues. There are also code editor plugins that afford inline linter error highlighting and probably allow for auto-format on save, too (though I don't use that myself).

**Comment by donmccurdy** [comment]
For example:

```js
// Before
function doTheThing(arg){
	var foo = '2389' + arg;
	console.log(foo);
}
doTheThing('_yeah');

// After `eslint --fix sample.js`
function doTheThing( arg ) {

	var foo = '2389' + arg;
	console.log( foo );

}
doTheThing( '_yeah' );
```

As @gkjohnson mentions, you can set up your editor to do this automatically, but threejs doesn't require any particular editor.

**Comment by enomado** [comment]
Even didn't know about this **eslint** feature.
Current **VS Code** config looks like:
```
"editor.formatOnSave": false
"eslint.autoFixOnSave": true
```
Thanks.
