### ISSUE TITLE
How to choose the machine configuration for best WebGL performance？

### ISSUE THREAD

**Issue by hookex** [mrdoob/three.js#17285]
##### How to choose the machine configuration？
Since the application needed to render a large number of 3D scenes using WebGL, our company decided to purchase a high-performance desktop machine. I wondered how to choose the machine? Multi-core CPU or high-frequency CPU? Game graphics or professional graphics? Gaming computer or professional graphics workstation。
I can't find this solution online, I hope to get your's advice.

Budget: 4300$

##### Three.js version
latest

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Please redirect your question to the three.js help site: https://discourse.threejs.org.
