### ISSUE TITLE
clone issue: SpotLight.target which is placed in scene graph is cloned in two roles

### ISSUE THREAD

**Issue by EliasHasle** [mrdoob/three.js#17299]
##### Description of the problem

Case: Make many similar lamps with geometry and attached SpotLight.

````
let scene = new THREE.Scene();
let lampMesh = new THREE.Mesh(fooPars);
let spotLight = new THREE.SpotLight(barPars);
spotLight.target.position.set(1,2,3);
lampMesh.add(spotLight, spotLight.target);

for (let i = 0; i < numLights; i++) {
    let lightClone = lampMesh.clone();
    lightClone.position.set(0,0,i);
    scene.add(lightClone);
}
````

The cloning will copy the target independently in the roles of `lampMesh.children[1]` and of `lampMesh.target`. This will cause the lamps to interpret the target position as a global position, rather than a local one, and moving the targets in the scene will have no effect on the lights, because their actual `target` properties are independent clones with no `parent`. And the error is/was really hard to locate.

Proposed solution: I am not sure. The only one I can think of is adding an optional parameter to _all_ clone methods, that contains a map (literal object) from original ID/UUID to already cloned objects, such that whenever an already cloned object is encountered, the existing clone will be reused in the new role. The map is passed down the recursion, and must also be passed to the `copy` methods. This seems like a drastic solution which will require a substantial amount of work, but it is also a general solution which will solve similar problems that _may_ exist elsewhere. I am not sure it is without unintended consequences, though.

User solution with current implementation: Don't use `clone` without knowing how it will behave. For the case above, consider either adding targets to scene after cloning, or building the copies without using `clone`, e.g. by using instances of a class which has static geometry and material.

Please also include a live example if possible (**maybe later**). You can start from these templates:

* [jsfiddle](https://jsfiddle.net/3foLr7sn/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/qgu17w5o/) (dev branch)
* [codepen](https://codepen.io/anon/pen/aEBKxR) (latest release branch)
* [codepen](https://codepen.io/anon/pen/BJWzaN) (dev branch)

**Comment by Mugen87** [comment]
Many issues with `clone()`/`copy()` methods were exposed in the past like #16076 or #16224. This is obviously another one.

TBH, I'm not a fan of trying to make the clone more fancy like described in your proposed solution. What you demonstrated seems to me a conceptual issue of the engine which is now hard to change. Removing all `clone()` and `copy()` methods from complex classes like `Object3D` might be the easiest and clean approach.

**Comment by WestLangley** [comment]
>What you have demonstrated seems to me a conceptual issue of the engine

@Mugen87 Can you please explain what you see as the problem with the library in this use case? If you are not sure, it is OK to say so. I am interested in specifics. (The OP's description is not clear to me...)

**Comment by EliasHasle** [comment]
@WestLangley I tried to be clear. I will gladly clarify if you can be specific on what you find unclear. :)

**Comment by WestLangley** [comment]
Let's see what @Mugen87 has to say in response to my two questions...

**Comment by EliasHasle** [comment]
A sketch of the proposal:

````
clone(recursive=true, cloneCache={}) {
    return new this.contructor().copy(this, recursive, cloneCache);
}
copy(source, recursive=true, cloneCache) {
    //Repeat this for several properties:
    if (recursive && cloneCache && source.someProperty.UUID in cloneCache) {
        this.someProperty = cloneCache[source.someProperty.UUID];
    } else {
        this.someProperty = source.someProperty.clone(recursive, cloneCache);
        //or this.someProperty = source.someProperty.clone(); (depending on the need for further recursion)
       cloneCache[source.someProperty.UUID] = this.someProperty;
    }
}
````

**Comment by Mugen87** [comment]
> Can you please explain what you see as the problem with the library in this use case?

It's probably best to explain this issue with `CameraHelper`. As we know, `CameraHelper.clone()` is currently broken. When fixing the helper via #16076,  another problem in context of clone operations was revealed. Similar to what @EliasHasle describes here.

When a 3D object has a property that refers to another 3D object in the scene e.g. `helper.camera`, there are two issues that might occur. 

- The camera will be cloned but `helper.camera` still refers to the old reference.
- The camera in the scene will be cloned and `helper.camera` which results in two independent camera objects.

When I understand @EliasHasle issue correctly, the latter one happens here.

**Comment by WestLangley** [comment]
Thanks.

I have in the past advocated removing `clone()` from all methods except the math classes. But we could just try removing `clone()` from certain classes and see what happens.

**Comment by Mugen87** [comment]
I have to admit that I favor your approach more than in the past. I'm just afraid this approach might break a lot of code since I've seen the usage of `clone()` so many times in the past. It's a bit an unfortunate situation...

**Comment by WestLangley** [comment]
Also, `clone()` calls `copy()`, and `SpotLight.copy()` does this:
```js
this.target = source.target.clone();
```

Whether the target should be cloned or not depends on the use case.

This is a complicated issue. three.js is very flexible, and with flexibility comes a responsibility on the part of the user to understand how it works. Sometimes, that means reading the code or stepping through with a debugger. I think most users eventually come to understand this responsibility.

**Comment by gkjohnson** [comment]
> I have in the past advocated removing clone() from all methods except the math classes. But we could just try removing clone() from certain classes and see what happens.

I use `clone` for caching and cloning loaded 3d assets to improve load times when loading the same geometry multiple times and to save on memory so I would be sad to see it removed:

```js
const cache = {};
function load(path, cb) {
    if (cache[path]) {
        cb(cache[path].clone());
    } else {
        (new GLTFLoader()).load(path, model => {
            cache[path] = model.clone();
            cb(model);
        });
    }
}
```

Because of this I think I'm unlikely to see the clone issues like those mentioned here but I think it would be difficult and tedious to replace the functionality if it were removed. It would also be frustrating to try to clone something but have it throw because an object with no clone function was deep in the hierarchy. It seems that the function works in 90%+ of use cases but if there are known gotchas with some objects then maybe they can be added to the documentation?

**Comment by looeee** [comment]
> model.clone()

I expect that will fail when the model is a `SkinnedMesh`, and possibly in other unexpected places too.

**Comment by donmccurdy** [comment]
The challenge — both with SkinnedMesh and `light.target` — is that they can't always be handled recursively, as `object.clone()` assumes. The SkinnedMesh's bones or the light's target might be children of that node, they might be children of an ancestor, or they might not be in the subtree being cloned at all. That last case is more or less guaranteed to fail, and we might as well throw an error.

The workaround for cloning a SkinnedMesh is [`SkeletonUtils.clone( ... )`](https://threejs.org/docs/#examples/en/utils/SkeletonUtils.clone), which does some extra processing before and after the cloning recursion.

```js
var object2 = THREE.SkeletonUtils.clone( object1 );
```

A similar method could be moved to SceneUtils, to handle both cases. As an API I very much prefer `var b = a.clone()`, but it would be pretty complex to make that work perfectly. The parent class, Object3D, would probably need to know a lot about its subclasses, Light and SkinnedMesh.

**Comment by EliasHasle** [comment]
@donmccurdy This (or approximately this) would conserve `b = a.clone()`, right?

````
Object3D.prototype.clone = function(recursive=true, cloneCache, subtreeUUIDs) {
    let theClone = new this.constructor();
    if (!recursive) {
        theClone.copy(this, false);
        return theClone;
    }

    if (cloneCache===undefined) {
        treeUUIDs = {};
        this.traverse(obj=>subtreeUUIDs[obj.UUID]=true);
        //subtreeUUIDs now holds all Object3D descendants
        cloneCache = {};
    }

    theClone.copy(this, true, cloneCache, subtreeUUIDs);
    return theClone;
}

SpotLight.prototype.copy = function(source, recursive=true, cloneCache, subtreeUUIDs) {
    .... /*other code*/
    if (recursive) {
        if (subtreeUUIDs[source.target] === undefined && target.parent!==null) {
            throw new Error("SpotLight.prototype.copy: Recursive cloning failed, because SpotLight target is attached outside cloned tree.");
        }
        if (cloneCache && source.target.UUID in cloneCache) {
            this.target = cloneCache[source.target.UUID];
        } else {
            this.target= new source.target.constructor();
            if (cloneCache) {
                cloneCache[source.target.UUID] = this.target;
            }
            this.target.copy(source.target, recursive, cloneCache, subtreeUUIDs);
        }
    } else {
        this.target = source.target.clone(false);
    }
    .... /*other code*/
}
````

**Comment by EliasHasle** [comment]
> There are a couple parts of that I'm not sure about – mainly, after creating `this.target = new source.target.constructor();`, how does the target get attached to the right parent in the hierarchy? Its parent may not have been cloned yet.

Objects encountered during the recursive cloning traversal use the cache too. So if the target is encountered first as `spotlight.target` and then as e.g. `object.children[0]`, the target which is in cached will be added to the cloned object, so that it gets the right parent. That is unless I have overlooked something, which I frequently do.

**Comment by EliasHasle** [comment]
Ah, that is a problem.

**Comment by EliasHasle** [comment]
> ```js
> Object3D.copy = function ( source, recursive, cache = {} ) {
> 
>   // Save the newly cloned object to the cache so it can be reused
>   // later if other objects reference it.
>   cache[ this.UUID ] = this;
> ```

You don't really know here that `this` is supposed to be a clone, but maybe that does not matter? Hm, if you are right in that assumption, you have overcome the obstacle that I bumped into. By putting everything in `copy` and caching `this`.

**Comment by EliasHasle** [comment]
> Oops this should actually be `cache[ source.UUID ] = this;` -- updated in the example above.

OK, I updated the quote too.

> I'm not sure I follow why this should be considered an exception. If the DirectionalLight target is outside the subtree being copied then a new target will be created but it won't be in any parent.

Do you think it should then be detached, so that it keeps its world transform?

**Comment by EliasHasle** [comment]
> I've submitted PR #17370 that implements the behavior I described for DirectionalLight.

I think at least SpotLight must also be handled by the same PR.

> > ```
> > light.target = scene;
> > scene.add(light);
> > ```
> 
> Ha, oh man. I guess here calling `light.clone()` would result in a cloned light that is parented to its target (which is the cloned scene). Seems weird but reasonable?

How about `scene.clone()`?

**Comment by EliasHasle** [comment]
A more productive discussion follows from the concrete solutions in #17370. Closing here.
