### ISSUE TITLE
Invalid processing in exponential representation of SVGLoader#parseFloats

### ISSUE THREAD

**Issue by ayatty** [mrdoob/three.js#17306]
In parseFloats() of SVGLoader, an unexpected result was returned.

This is because the following regular expression used in parseFloats () does not handle exponential notation correctly:
`
var array = string.split( /[\s,]+|(?=\s?[+\-])/ );
`

When string is "123.456e-20,789.012-20+1000",
> (Expected value)
> ["123.456e-20", "789.012", "-20", "+1000"]
>   
> (Result value)
> ["123.456e", "-20", "789.012", "-20", "+1000"]

How about changing as follows?
`
string.match(/[^\d]*\d+(\.\d+)?([eE][+\-]?\d+)?,?/g);
`
Result: ["123.456e-20,", "789.012", "-20", "+1000"]

There is an extra "," at the end of array [0], but parseFloat() stops the conversion if an invalid character is found, so there is no harm.

one more.
In the process following the regular expression,
> // Handle values ​​like 48.6037.7.8
> // TODO Find a regex for this

There is a comment, but how should "48.6037.7.8" be handled?
Current results [48.6037, 0.7, 0.8]
Is there such a case? [48.6037, 7.8]

I don't know which is right,
The latter can be supported by changing the regular expression as follows.
string.match(/[^\d]*\d+(\.\d+)?([eE][+\-]?\d+)?[,\.]?/g);

Thank you.

**Comment by yomboprime** [comment]
Sorry, I've got little expierence with regular expressions and it would take me much effort to validate that expression.

About the interpretation, I think it should be "[48.6037, 0.7, 0.8]"

**Comment by ayatty** [comment]
As you say, “48.6037.7.8” is
It seems correct to split into ["48.6037", ".7", ".8"].
There was also an explanation in the SVG specification (“0.6.5” as an example). I'm sorry.
(https://www.w3.org/TR/SVG11/paths.html#PathDataBNF)

Is it difficult to change regular expressions?

**Comment by yomboprime** [comment]
> Is it difficult to change regular expressions?

Not to change them, but they are harder to validate than regular code.
