### ISSUE TITLE
geometry does not update if a new vector is assigned to a vertex

### ISSUE THREAD

**Issue by mqnc** [mrdoob/three.js#17313]
[jsfiddle](https://jsfiddle.net/wjvonfzg/)
```
//object.geometry.vertices[0].set(1, Math.cos(t), 0) // <- this works
object.geometry.vertices[0] = new THREE.Vector3(1, Math.cos(t), 0) // <- this works only once
object.geometry.verticesNeedUpdate = true
```
I don't even know if this is an issue because I think you can always reuse the old vector but it took me a while to find that this is the problem in my code and I don't know why it doesn't work.

**Comment by WestLangley** [comment]
That is known, and it is by design. Use
```js
geometry.vertices[ 0 ].set( x, y, z );
geometry.verticesNeedUpdate = true;
```
`Geometry` is converted to `BufferGeometry` by the library prior to rendering. Consider using `BufferGeometry` in your app.
