### ISSUE TITLE
Editor: Export objects created by scripts

### ISSUE THREAD

**Issue by mracette** [mrdoob/three.js#17322]
##### Description of the problem

_Edited 8/22/19 to clarify use case_

Use case:
- create blank slate editor scene
- populate with single mesh
- write script to clone the mesh, transform the clone(s), then add the clone(s) to scene.
- press 'Play'
- file > export GLTF

Expected behavior:
- if the GLTF is exported _after_ the users hits 'Play', it should include the clones. If exported while in edit mode, it should not include the clones.

Current behavior:
- exported GLTF file never includes the clones, but published export does include the scripts that created the clones (file > publish)

Specifically, here's the script I'm using. I could imagine adding the clones to a group instead of the scene and expecting that the exported group would also include the clones. Thoughts?

```javascript
for(var i = 0; i < 8; i++) {
	var clone = scene.getObjectByName('Circle').clone();
	clone.rotateY(i * Math.PI * 2 / 8);
	clone.translateX(1);
	scene.add(clone);
}
````

##### Three.js version
- [X] r107

**Comment by Mugen87** [comment]
> if the GLTF is exported after the users hits 'Play', it should include the clones.

It is not supposed that this happens. The exporters only export what's in the scene graph while in edit mode. The app player is decoupled from this logic. It's also no possible to edit objects which are created from your scripts at execution time.

If you click on "Publish" , the scripts are of course included and executed when the resulting app is opened in a browser. But keep in mind that exporting and publishing are two different things. 

The idea is that you can implement basic apps with the editor and publish them as standalone apps. The exporter are only focused on exporting the scene graph or a specific objects into a 3D formats like `OBJ` , `glTF` or `Collada`.

**Comment by mracette** [comment]
All that makes sense. I'm just trying to stress that if this functionality were added, it would unlock the ability to use the editor to quickly mock up and export scripted assets for use in other projects. 

Maybe I'm the only one who would like to use the editor to do this and everyone else is using Blender/Unity. However, it feels a little silly publishing a scene from the editor and then hooking up an exporter in the resulting code to accomplish what I described above.

**Comment by Mugen87** [comment]
> However, it feels a little silly publishing a scene from the editor and then hooking up an exporter in the resulting code to accomplish what I described above.

True, this is not an ideal workflow for you. But because of the current architecture of the editor it's a bit inconvenient to implement what you are looking for. I'm referring to the fact that the editor and the app player are two decoupled things. Not sure if we want to change this...

**Comment by mrdoob** [comment]
You can actually achieve this from the browser's console.

Select the object you want to clone, open the devtools and paste this in the console:

```js
var object = editor.selected;
for(var i = 0; i < 8; i++) {
	var clone = object.clone();
	clone.rotateY(i * Math.PI * 2 / 8);
	clone.translateX(1);
	editor.addObject(clone);
}
```

I guess the editor is scriptable 🤓

**Comment by mracette** [comment]
Ok.. that's cool. Thanks for the workaround :)
