### ISSUE TITLE
saopass.d.ts missing 'params' property

### ISSUE THREAD

**Issue by jhlee4** [mrdoob/three.js#17334]
##### Description of the problem
sao pass example: https://github.com/mrdoob/three.js/blob/master/examples/webgl_postprocessing_sao.html

I was trying out sao example from the official website, and I noticed that saopass in saopass.d.ts file was missing` params` property. 

example uses `params` property for gui.

I am not 100% sure if this is a mistake.

##### Three.js version
- Dev
- r107

##### Browser
- [ ] All of them
- [X] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [ ] All of them
- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Are you referring to the `params` object for `dat.gui`? No, this objects are never defined in a type declaration file.

**Comment by gkjohnson** [comment]
@Mugen87 There is a "params" field on the SAOPass object itself:

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/postprocessing/SAOPass.js#L51-L62

I've added it in #17340

**Comment by jhlee4** [comment]
@gkjohnson fantastic :)

**Comment by Mugen87** [comment]
@gkjohnson Thanks for clarifying 👍
