### ISSUE TITLE
EditorControls  Set Maximum and Minimum Zoom Level

### ISSUE THREAD

**Issue by Huai-Dc** [mrdoob/three.js#17347]
Can't set zoom range

**Comment by Mugen87** [comment]
I'm not sure we want to start to introduce such fine-granular configurations to the editor. Could get out of control...

**Comment by arodic** [comment]
Agree, OrbitControls are configurable version of EditorControls. Why not use them instead?

One limit that might make sense in EditorControls is to make min target<>camera distance near clipping plane and maximum distance far clipping plane.

**Comment by Mugen87** [comment]
It's not only about the controls. As far as I understand the OP, the zoom range should be configurable via the editor's UI. I think it's better to focus on the most important settings and avoid  more exotic stuff for now.

**Comment by Huai-Dc** [comment]
thanks！i'm use OrbitControls instead
