### ISSUE TITLE
Docs: Broken link on FAQ

### ISSUE THREAD

**Issue by fllprbt** [mrdoob/three.js#17348]
At https://threejs.org/docs/index.html#manual/en/introduction/FAQ, the link for the example of _How can scene scale be preserved on resize?_ is not working. Currently, it points to http://jsfiddle.net/Q4Jpu/.

**Comment by Mugen87** [comment]
The link does work for me.

**Comment by fllprbt** [comment]
Yes, but I am having a 404 Not Found (nginx).

Chrome Version 76.0.3809.100 (Macbook). Tested also with incognito but nothing changed.

Can you see the fiddle normally?

**Comment by Mugen87** [comment]
Yes. It also works from my smartphone.

**Comment by fllprbt** [comment]
Oh, my vpn security blocks everything from jsfiddle...

sorry to bother you and thanks for the quick reply :). Closing the issue...
