### ISSUE TITLE
OrbitControls Steering property

### ISSUE THREAD

**Issue by lidonghai1** [mrdoob/three.js#17346]
When some scenarios are panoramic, the camera's turn is reversed. Can OrbitControls set a turn to an attribute?

**Comment by WestLangley** [comment]
See https://threejs.org/examples/webgl_panorama_cube.html and try:
```js
controls.rotateSpeed = - 0.25;
```
If that does not work for you, please provide a live example to demonstrate your use case.

**Comment by lidonghai1** [comment]
> See [threejs.org/examples/webgl_panorama_cube.html](https://threejs.org/examples/webgl_panorama_cube.html) and try:
> 
> ```js
> controls.rotateSpeed = - 0.25;
> ```
> 
> If that does not work for you, please provide a live example to demonstrate your use case.

Thank you. Your method solved my problem.

**Comment by WestLangley** [comment]
Closing. This is a request for a feature that is already supported.
