### ISSUE TITLE
OBJLoader2.d.ts: Argument of type 'void' is not assignable to parameter of type 'Object3D'

### ISSUE THREAD

**Issue by thkaza** [mrdoob/three.js#17364]
##### Description of the problem

The return type of objloader2.parse in the OBJLoader2.js code is **Group** and in OBJLoader2.d.ts is **void**

##### Three.js version

- [ ] Dev
- [x] r107
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Good catch! Do you wanna make a PR with the fix?

**Comment by thkaza** [comment]
Yes sure, I am trying to find some time and then I will do it

**Comment by thkaza** [comment]
Hi @Mugen87 ,
To be honest I am not sure what type it should be now. In the latest version I see the `return this.baseObject3d `is of type `any`.
I do not know what is more proper to change it to? To `any`, to `Group` or to `Object3D`?
I do not want to break anything

**Comment by Mugen87** [comment]
@kaisalmen Any thoughts about this issue?

**Comment by kaisalmen** [comment]
@thkaza Thanks you for spotting the wrong return type. Very obvious mistake, but I didn't notice it when cleaning up before r108.

`Group` is derived from `Object3D` and the default `baseObject3d` should be just `Object3d` as it is the base type, can have children and when it is set via the set function it can be any derivation it, so it will always be instanceof `Object3d` => return type of `parse` should be `Object3D`. Does that sound logic to you?

`OBJLoader2Parallel.parse` is void, but this is not reflected in `ts`file I just noticed. I will review and fix this, too. Sorry, for the inconvenience.

**Comment by thkaza** [comment]
Hi @kaisalmen, to me yes it sounds logic, but since I just started to use threejs I cannot have an opinion :), you are the expert here.
No need to apologize, no inconvenience caused :)
I will wait for the release from your side.

Thanks again
