### ISSUE TITLE
BoxHelper's TypeScript definition file is missing setFromObject 

### ISSUE THREAD

**Issue by mmakrzem** [mrdoob/three.js#17374]
##### Description of the problem

I'm trying to use the BoxHelper in my TypeScript project and I noticed that the typescript definition file found here: 

`https://github.com/mrdoob/three.js/blob/dev/src/helpers/BoxHelper.d.ts`

is missing the definition for the setFromObject function defined in:

`https://github.com/mrdoob/three.js/blob/master/src/helpers/BoxHelper.js`

##### Three.js version

- [ ] Dev
- [X] r107
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
That's right. `copy()` and `clone()` is also missing. Would you like to do a PR and add the missing declarations?

**Comment by mmakrzem** [comment]
Sure, but I don't know what a PR is, nor do I know how to submit changes.  Could you point me to some instructions on how to submit changes?

**Comment by Mugen87** [comment]
Some general information: https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js

If you just want to edit a single file, you can use the "edit" function of github:

https://help.github.com/en/articles/editing-files-in-your-repository

This makes it a bit easier to contribute a change. You can automatically create a PR at the end of the editing.
