### ISSUE TITLE
mergeBufferGeometries

### ISSUE THREAD

**Issue by JudeNino** [mrdoob/three.js#17371]
Im trying to merge this code below and the error is "Unable to get property 'mergeBufferGeometries' of undefined or null reference". Can someone help me? Thanks!

        function addCube(){
          var geo = new THREE.BufferGeometry().fromGeometry(new THREE.BoxGeometry(25, 25, 25))

          for ( var i = 0; i < 10000; i ++ ) {
            var geometry = geo.clone()
            geometry.applyMatrix( new THREE.Matrix4().makeTranslation(Math.random() * 1000 - 500, Math.random() * 1000 - 500, 0) );
            geometry.rotateX(Math.random() * 1)
            geometry.rotateY(Math.random() * 1)
            cubes.push(geometry)
          }
          var geometriesCubes = THREE.BufferGeometryUtils.mergeBufferGeometries(cubes);
          var mesh = new THREE.Mesh(geometriesCubes, new THREE.MeshNormalMaterial());
          scene.add(mesh);
        }

**Comment by James-Smyth** [comment]
You are getting that error because BufferGeometryUtils is a separate component located under `three.js/examples/jsm/utils/`

`import { BufferGeometryUtils} from 'three/examples/jsm/utils/BufferGeometryUtils.js';`

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
