### ISSUE TITLE
Suggestion: Remove use of gl_FragDepthEXT for Logarithmic Depth Buffer

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#17384]
Logarithmic depth buffer uses the `gl_FragDepthEXT` in the [fragment shader when possible](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/logdepthbuf_fragment.glsl.js#L4). However setting the depth in the fragment shader means that optimizations like the [early depth test](https://www.khronos.org/opengl/wiki/Early_Fragment_Test) can't be performed meaning that this code path could cause a performance hit. I see that the use of the extension was originally introduced but commented out in #4566 and then enabled in #6458 but the rationale behind setting the the depth in the fragment shader isn't clear.

Is there a reason to not always adjust z in the vertex shader? If not I can make a PR to remove the use of `gl_FragDepth`.

**Comment by WestLangley** [comment]
>Is there a reason to not always adjust z in the vertex shader?Implementing logarithmic depth buffer in software has limitations.

For example, a large floor geometry must be tessellated, otherwise it can become clipped. I was able to confirm this several years ago.

See https://github.com/mrdoob/three.js/pull/4566/files#diff-c78fde2d3da4f38bf2a6d6365b5422e4R1669-R1675.

**Comment by gkjohnson** [comment]
> For example, a large floor geometry must be tessellated, otherwise it can become clipped. I was able to confirm this several years ago.

Got it, this makes sense -- maybe I'll look into updating the docs and adding a comment to describe why it's being used. From the article it sounds like the lack of `ARB_conservative_depth` extension in webgl could make logarithmic depth buffer less favorable unless it's really needed.
