### ISSUE TITLE
Node Material normals flipped

### ISSUE THREAD

**Issue by arobertson0** [mrdoob/three.js#17383]
##### Description of the problem

On the newest version of three.js, the normals as seen on the  [node material example](https://threejs.org/examples/?q=node#webgl_materials_nodes) are flipped.

This is what it looked like [before the latest release](https://rawgit.com/mrdoob/three.js/r107/examples/?q=nodes#webgl_materials_nodes):

![node-normal-before](https://user-images.githubusercontent.com/52537956/63973839-9ddef900-ca79-11e9-8d7c-695bb2610590.png)

[After the release](https://threejs.org/examples/?q=node#webgl_materials_nodes):
![node-normal-after](https://user-images.githubusercontent.com/52537956/63973838-9ddef900-ca79-11e9-8ae6-53dae14d062a.png)

##### Three.js version

- [x] Dev
- [x] r108

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Android
- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] iOS

**Comment by arobertson0** [comment]
@sunag could this be related to recent changes for clearcoat normals?

**Comment by sunag** [comment]
I think that It is because the pertubNormal2Arb in NodeMaterial was update, now pertub2.. result is diferentes with double-sided material. I am working for NodeMaterial get the core functions in runtime.

**Comment by Mugen87** [comment]
For testing (latest `dev` version) 

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_materials_nodes.html

**Comment by sunag** [comment]
I still am not sure about change this, apparently with `use node material` and without NodeMaterial the result (MeshStandardNodeMaterial x MeshStandardMaterial) is the same? I have tested this with other sides to assure if this is really a bug or a not.

**Comment by sunag** [comment]
Maybe this is a bug of the function `pertubNormal2Arb` from the core?

**Comment by sunag** [comment]
https://raw.githack.com/sunag/three.js/dev-node-sides/examples/webgl_materials_nodes.html

https://github.com/mrdoob/three.js/pull/17584
