### ISSUE TITLE
The FBXLoader doesn't load FBX files with built-in DDS textures.

### ISSUE THREAD

**Issue by 4NK4** [mrdoob/three.js#17388]
##### Description of the problem
      Issues of loading TGA were solved, but it was a BUG to load DDS!
 
- [x ] Dev
- [ ] r108
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I wouldn't say it's bug. More a feature request. I remember that @looeee already worked on this some time ago but encountered some issues with DDS, see https://github.com/mrdoob/three.js/pull/13227
