### ISSUE TITLE
Docs: Missing controls pages

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#17382]
##### Description of the problem

Regarding Controls documents, currently Three.js has only `OrbitControls` document. I think it's helpful to users if we have all the Controls documents.

##### Three.js version

- [x] Dev
- [ ] r108
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This would be a good "First issue" for devs who would like to start contributing. Especially since `OrbitControls` can be used as some kind of template.

**Comment by Mugen87** [comment]
All controls in the examples directory are now documented 👍
