### ISSUE TITLE
Issue with Display of obj file 

### ISSUE THREAD

**Issue by jogibear9988** [mrdoob/three.js#17394]
##### Description of the problem

OBJ File displayed correctly in Blender:

![image](https://user-images.githubusercontent.com/364896/64062366-b9671280-cbe5-11e9-8582-aacf0ed6fd79.png)

and wrong with ThreeJS ( https://discoverthreejs.com/apps/loader/ )

![image](https://user-images.githubusercontent.com/364896/64062369-c5eb6b00-cbe5-11e9-9086-1f7032154a3e.png)

[demo ob.zip](https://github.com/mrdoob/three.js/files/3562305/demo.ob.zip)

##### Three.js version

Version of  https://discoverthreejs.com/apps/loader/

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Yes, your OBJ asset is not rendered correctly by the `three.js editor`. However, even Sketchfab and Quicklook 3d (Mac). 

Please export your asset to `glTF` instead and use `THREE.GLTFLoader`.

**Comment by jogibear9988** [comment]
My Software has no export for gltf.
You know why it does not work?

**Comment by Mugen87** [comment]
You can convert your OBJs with this converter:

https://github.com/AnalyticalGraphicsInc/obj2gltf

> You know why it does not work?

No yet. But it's suspicious that so many viewers are not able to load the OBJ file correctly.

**Comment by gkjohnson** [comment]
The file you provided uses commas in place of decimal places, which I've never seen in an OBJ file before.

```obj
v 0,5835005 0,8100001 -1,52
v -0,5834996 0,7817158 -1,531716
v -0,5834996 0,8100001 -1,52
vn 3,139165E-07 -1,748456E-07 1
```

Changing the commas to periods makes it look more like your image in Meshlab but there are still a few warnings. Maybe the remaining warnings have to do with the exponential number format? I'm not sure if that's valid in OBJ, either.

**Comment by jogibear9988** [comment]
@gkjohnson 
that means commas are incorrect or seldom? if they are incorrect I need to raise an issue at the product exporting them.

**Comment by gkjohnson** [comment]
@jogibear9988 
I would submit an issue to the product you're using -- it doesn't seem like commas are considered valid for numbers in OBJ unless I'm missing something. Here are some related issues that seem to point to applications incorrectly using the current locale settings for numbers serialization resulting in commas in some regions rather than periods for decimals:

https://github.com/keenanwoodall/Deform/issues/17
https://github.com/microsoft/RoomAliveToolkit/issues/23

**Comment by jogibear9988** [comment]
I've send a issue to them. I'll leave this open until I get an answer. But maybe commas could also be supported even if they are wrong (blender does so.) I've also looked in a specification wich I found, but I didn't find if it's allowed or not...

**Comment by gkjohnson** [comment]
> But maybe commas could also be supported even if they are wrong (blender does so.)

My preference would be to not encourage the proliferation of nonstandard file definitions if it seems to be wrong. It looks like most applications can't open the file as expected with commas so I don't think three.js should, either.

What version of blender are you using?

**Comment by jogibear9988** [comment]
2.80

**Comment by DanielJoyce** [comment]
It looks like its exporting the obj numbers in localized format. Commas are used in many eu countries for decimals, and decimal points for commas.

OBJ format says nothing about expected localization of number. So technically respecting the locale of the machine when trying to load them might make sense.

This would be harder for a browser though, as the browser locale could be different than the locale of the server hosting the loaded asset.

**Comment by DanielJoyce** [comment]
Given it was invented in the US, US number format is likely the unoffficial standard.

**Comment by Mugen87** [comment]
Closing. This needs to be fixed on exporter side. 

Blender users should use `glTF` instead of `OBJ` anyway.

**Comment by jogibear9988** [comment]
I've created an issue on the software author, and they said they will fix, so closing is okay

**Comment by jogibear9988** [comment]
What I still do not understand, why is it black&white in threeJs?

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for such help requests 👍
