### ISSUE TITLE
tga loader demo not working

### ISSUE THREAD

**Issue by LevanaTheButcher** [mrdoob/three.js#17399]
##### Description of the problem

https://threejs.org/examples/?q=tga#webgl_materials_texture_tga
not working at all. aslo had a lot of issues in tga loader and couldnt use it but im most concerned about this demo, its just a blank page.

##### Three.js version

- [ ] Dev
- [ ] r108
- [x ] latest

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
i3 7400 | r9 280x

**Comment by mrdoob** [comment]
I think the example got renamed:
https://threejs.org/examples/?q=tga#webgl_loader_texture_tga

**Comment by LevanaTheButcher** [comment]
ah sorry man the docs pointed to blank page

**Comment by Mugen87** [comment]
> ah sorry man the docs pointed to blank page

Fixed with the next release 😇
