### ISSUE TITLE
Unable to set th needsUpdate to true

### ISSUE THREAD

**Issue by WREQI** [mrdoob/three.js#17392]
Curve3's needsUpdate becomes false when I use TubeBufferGeometry

**Comment by Mugen87** [comment]
It's not intended that user set this property. It's for internal use only.

**Comment by EliasHasle** [comment]
> Curve3's needsUpdate becomes false when I use TubeBufferGeometry

Presumably because the `Curve3` is updated during the construction of `TubeBufferGeometry`.

**Comment by mrdoob** [comment]
> Curve3's needsUpdate becomes false when I use TubeBufferGeometry

What do you think should happen instead? What are you trying to do?

**Comment by Mugen87** [comment]
Closing due to lack of feedback from the OP.
