### ISSUE TITLE
Torus rotation on Z axis doesn't work properly

### ISSUE THREAD

**Issue by FilipLitwora** [mrdoob/three.js#17408]
Hi, i found a bug in threejs. Rotating torus on Z axis is impossible unless you set `torus.rotation.order = "ZXY"` what I think is inconvenient.
[codesandbox](https://codesandbox.io/s/threejs-87kvbl)

##### Three.js version
- [x] r108

##### Browser
- [x] Chrome

##### OS
- [x] Windows

**Comment by Mugen87** [comment]
It seems your link leads to a 404 page.
