### ISSUE TITLE
CSS3D object is visible throughout 3d objects and not remains aligned while rotate the scene

### ISSUE THREAD

**Issue by Krrish92** [mrdoob/three.js#17417]
##### Description of the problem

I am using CSS3DRenderer for rendering HTML on FBX 3d objects. It's working fine but when I rotate my scene, HTML is visible through 3D objects like transparent and alignment of HTML also is being disturbed. I am new in Threejs. any advice or guidance would be greatly appreciated.

Please see the video on the  https://drive.google.com/file/d/1xAhznWdrEDQr7TGb4zMGWEwV9FC6j3zn/view 

Also i have raised concern on StackOverflow with code snap. Please have a look on https://stackoverflow.com/q/57756551/10753132 link

##### Three.js version

- [ ] Dev
- [x] r108
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please don not crosspost from stackoverflow or the [forum](https://discourse.threejs.org/). Github is not intended for help requests.
