### ISSUE TITLE
Material has no control over stencilBuffer.setMask()

### ISSUE THREAD

**Issue by amsXYZ** [mrdoob/three.js#17419]
##### Description of the problem

After the recent changes that offer control over the stencil buffer state through the material interface in #15611 , one major aspect of the stencil state setup was overlooked: the stencil write mask.

This can be set directly through the stencil buffer like: 
``` javascript
renderer.state.buffers.stencil.setMask(MASK);
```

But, as we can see [here](https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/WebGLState.js#L684), it's not exposed nor used through the material's stencil parameters:
``` javascript
var stencilWrite = material.stencilWrite;
stencilBuffer.setTest( stencilWrite );
if ( stencilWrite ) {
	stencilBuffer.setFunc( material.stencilFunc, material.stencilRef, material.stencilMask );
	stencilBuffer.setOp( material.stencilFail, material.stencilZFail, material.stencilZPass );
}
```

Material's ``material.stencilMask`` should be split in ``material.stencilWriteMask`` (which would be use in conjunction with ``renderer.state.buffers.stencil.setMask()``) and ``material.stencilFuncMask`` to properly expose all the stencil state functionality through the material layer.

Some nice links on the topic:
* [stencilMask](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/stencilMask)
* [stencilFunc](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/stencilFunc)

##### Three.js version

- [X] Dev
- [X] r108
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by gkjohnson** [comment]
You're right! Thanks for the catch. I can add and update the stencil parameters on the material and docs later this week.

It looks like WebGL also affords the ability to set mask for the front and back faces separately with [stencilMaskSeparate](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/stencilMaskSeparate). Maybe it's worth supporting that, too? Maybe `material.stencilFrontWriteMask` and `material.stencilBackWriteMask`?

**Comment by amsXYZ** [comment]
Not just the mask, but the ops and funcs too!
* [stencilFuncSeparate](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/stencilFuncSeparate)
* [stencilOpSeparate](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/stencilOpSeparate)

Regarding support for that... I'm not sure. I mean, it's always nicer to have more control, but we shouldn't make the stencil state API too confusing... 

Maybe it should look something like this?
``` typescript
interface StencilFuncParameters {
  func: stencilFunc;
  ref: number;
  mask: number;
}

interface StencilOpParameters {
  fail: stencilOp;
  zFail: stencilOp;
  zPass: stencilOp;
}

interface StencilState {
  side: Side; // Controls if regular or "Separate" version of stencil state calls are used.
  frontWriteMask: number;
  backWriteMask: number;
  frontStencilFunc: StencilFuncParameters;
  backStencilFunc: StencilFuncParameters;
  frontStencilOp: StencilOpParameters;
  backStencilOp: StencilOpParameters;
}
```

**Comment by gkjohnson** [comment]
Hm that's true... I'll stick with just adding the other mask field for now and maybe this can be thought about in the future.

For reference Unity lets you set the stencil states for front and back faces separately or you can set them together: https://docs.unity3d.com/Manual/SL-Stencil.html
