### ISSUE TITLE
OBJLoader is missing Specular + Normal maps

### ISSUE THREAD

**Issue by yazancash** [mrdoob/three.js#17414]
Hi

when i load OBJ file using MTLLoader + OBJLoader, with material file as below:

```
newmtl Material001
Ka 0.000000 0.000000 0.000000
Kd 0.698039 0.698039 0.698039
Ks 0.000000 0.000000 0.000000
d 1.000000
illum 2
Ns 9.84916
map_Kd base.png
map_Ks spec.png
nor normal.png
```

on render, model is appearing without Spec/Normal maps.

this is not supported yet?

any plan to support in future ?

**Comment by Mugen87** [comment]
Specular maps are already support, see

https://github.com/mrdoob/three.js/blob/3099698f90c58a613c855579be638f437805ae2a/examples/jsm/loaders/MTLLoader.js#L392-L398

And normal maps, too. However, according to this [source](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Physically-based_Rendering), the normal map is defined via `norm` and not `nor` like in your post.

https://github.com/mrdoob/three.js/blob/3099698f90c58a613c855579be638f437805ae2a/examples/jsm/loaders/MTLLoader.js#L408-L412

Can you please share an OBJ file with the respective MTL?

**Comment by Mugen87** [comment]
Specular maps are already support, see

https://github.com/mrdoob/three.js/blob/3099698f90c58a613c855579be638f437805ae2a/examples/jsm/loaders/MTLLoader.js#L392-L398

And normal maps, too. However, according to this [source](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Physically-based_Rendering), the normal map is defined via `norm` and not `nor` like in your post.

https://github.com/mrdoob/three.js/blob/3099698f90c58a613c855579be638f437805ae2a/examples/jsm/loaders/MTLLoader.js#L408-L412

Can you please share an OBJ file with the respective MTL?

**Comment by yazancash** [comment]
i see. well thank you.

i have a question:
**map_bump** = **norm** ?

i will prepare example OBJ to view online.

**Comment by Mugen87** [comment]
> i have a question:
map_bump = norm ?

The spec says these are two different things.

**Comment by yazancash** [comment]
i think Normal map is a modern type of bump map.

here is example in OBJ format. (Texture + Normal map)
https://rigmodels.com/3d.php?view=3A33JN88AR54IVDX7RNOVCGMK

it does not look like ThreeJS Example:
https://threejs.org/examples/?q=normal#webgl_materials_normalmap_object_space

* i made another test & applied Lighting same to ThreeJS example (Point light instead of Directional) but no close result. like Normal map is ignored.

**Comment by Mugen87** [comment]
I get the same results if I configure the normal map as an object space normal map. So after loading I do this:

```js
object.traverse( child => {

    if ( child.isMesh ) {

        child.material.normalMapType = THREE.ObjectSpaceNormalMap;
        child.geometry.removeAttribute( 'normal' );

    }

}  );
```

![image](https://user-images.githubusercontent.com/12612165/64189345-54751c00-ce74-11e9-8fe5-9ac4dd255361.png)
