### ISSUE TITLE
Don't you think,the memory of three.js is a little bit large?

### ISSUE THREAD

**Issue by shyakocat** [mrdoob/three.js#17424]
##### Don't you think,the memory of three.js is a little bit large?

I'm not sure if it's my problem.

(And if needing screenshot I will upload later.)

The operation is very easy.

First open the Chrome and visit https://threejs.org/examples/. Then check the monitor,the GPU thread cost some memory(maybe 200M-400M).And run an example,the memory add up to 800M-1G.

I write some demo,and they cost lots of memory(about 1G).

By the way,I don't know how to dispose a renderer properly,if I new a renderer and call renderer.render(),the memory will leak.(every time add about 800M)

I'm sorry I can't express clearly in English.I just want to know: Is it normal?(about the large memory cost)

- [ ] Dev
- [ ] r108
- [√] r107

##### Browser

- [ ] All of them
- [√] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [√] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Um, I can monitor with Chrome's task manager a similar memory consumption with other engines, too. What do you see when testing the examples of Babylon.js (https://doc.babylonjs.com/examples/)?

**Comment by shyakocat** [comment]
> Um, I can monitor a similar memory consumption with other engines, too (using Chrome's task manager). What do you see when testing the examples of Babylon.js (https://doc.babylonjs.com/examples/)?

Thanks for replying.I'm sorry that I couldn't view it in time.

(Yeah,I expressed badly.I mean Chrome's task manager.)

For some reasons(web),I need a long wait to open the example of Babylon.js(That's why I didn't choose Babylon.js at first).I couldn't tell how it performance exactly,but maybe similiar to three.js.

I've ever tried claygl,it cost 800M+ as well.

(I didn't try every lib listed in awesome-webgl.)

Emmmmmm...I'm ashamed that I'm not good at WEBGL.So I don't know the reason.

I wonder,if I display the same scene in a C++(GL/DX) program,the memory cost may be less than 100M(or even <20M).

But what the large memory used for?I think it shouldn't cost so much.Maybe it's a feature of Chrome??

**Comment by mrdoob** [comment]
> (And if needing screenshot I will upload later.)

Yes please, can you share screenshots?

**Comment by shyakocat** [comment]
> > (And if needing screenshot I will upload later.)
> 
> Yes please, can you share screenshots?

![Before](https://user-images.githubusercontent.com/20227559/64263277-f58dd080-cf61-11e9-8b69-08e06877b839.png)

![After](https://user-images.githubusercontent.com/20227559/64263304-01799280-cf62-11e9-8018-65cb24784fbe.png)

This is a simple test.

The memory of GPU thread at first(no example displaying)is about 200M.

And then open one example.The memory is about 800M.

Though it's not accurate(and the number is floating).But we can simply infer the memory cost by the example is about 800M-200M=600M(maybe we cannot do it directly).

I only mean this.And different examples show variously(400M~1G+).

I ask for optimizing(to decrease memory size).Or maybe it's a normal thing.

**Comment by shyakocat** [comment]
Maybe it's a strange question.But I concerned that maybe some PC(s) don't have enough RAM.

Apart from this,I ask in a weak voice:

```
let main = () => {
    let renderer = new THREE.WebGLRenderer({antialias: true, alpha: true});
    //INIT: camera,light,scene
    //INIT: texture,material,mesh
    let animate=()=>{
        //ANIMATION
        renderer.render(camera,scene);
        requestAnimationFrame(animate);
    };
    animate();
    //DISPOSE: texture,material,mesh
    //NOPE: camera,light
    scene.dispose();
    renderer.dispose();
};
```

If I write code below.

Then I call main() serveral times.The memory will leak.

And if I don't write
```
renderer.render(camera,scene);
```
(Or composer)

Memory showes fine.

Am I dispose in a wrong way?

**Comment by shyakocat** [comment]
Ops,actually in my code the animate is be awaited until end.So the dispose will be executed after the animate.The code below is not that strict...

**Comment by Mugen87** [comment]
> Then I call main() serveral times.The memory will leak.

I don't think calling `main()` multiple times is a good idea since you start multiple times a render loop. You should call `animate()` only once. At least you should cancel an animation frame request previously scheduled through a call to `requestAnimationFrame()` before calling `main()` again.

**Comment by Mugen87** [comment]
After searching the internet for this topic it seems that the high memory footprint of the GPU process was already discussed at many places e.g.: https://www.quora.com/Why-is-Google-Chromes-GPU-taking-up-over-450-000-K-of-memory-Is-there-anything-I-can-do-to-fix-it

**Comment by mrdoob** [comment]
Use the DevTools Memory panel for a more accurate memory measurement:

<img width="1209" alt="Screen Shot 2019-09-04 at 11 30 07 AM" src="https://user-images.githubusercontent.com/97088/64281187-7075cd80-cf07-11e9-94b5-92d4817ba52b.png">

**Comment by shyakocat** [comment]
Thanks for replying.(Mugen87&mrdoob)

It's very kind of you to solve my confusion.

(I used to save the GPU thread memory and found that half of it is 0.)

(It seems that "quora" is banned in my country..Actually "Google""Twitter""Facebook""Youtube"as well unless use VPN)

However,the last question is,

For example,I write the main() function (async;You could consider all operation run step-by-step;init->animate->dispose is a complete procedure.). and in a promise:
```
  await main();
  await main();
  await main();
  ...
```
We suppose that the GPU thread memory is 200M as first.When I call main() at first,it become 1G(for example).Then the second main() makes it become 2G.Then 3G,4G...I temporarily call it memory leak.

Also,if we call main() only once.The GPU thread memory turns 200M to 1G.Then I have no way to make it come back from 1G to 200M.If I don't need render after that,the memory is still 1G.That makes me uncomfortable(in fact it's not a matter at all).

**Comment by shyakocat** [comment]
I mean one renderer cost 1G memory(for example).

So I modified my code,now the renderer is only one,so memory remain at 1G though I render serveral times and serveral scenes.

But I can't release that 1G memory(in GPU thread).

In fact,I use it just for a small effect.But the effect may be called serveral times when needing.I want to keep the memory at a low level.

**Comment by shyakocat** [comment]
I apologize that I didn’t know forum before.

And it’s not strict that the screenshot provided didn’t wait the texture loaded.

And I’m not good at DevTool but I think it can only inspect JavaScript heap (like variables) rather than GPU memory(maybe I mistake).

**Comment by mrdoob** [comment]
> And I’m not good at DevTool but I think it can only inspect JavaScript heap (like variables) rather than GPU memory(maybe I mistake).

I assure you that the grass texture is not 1G.

**Comment by shyakocat** [comment]
> I assure you that the grass texture is not 1G.

Yes,I just make an example let it easy to calculate.

But it seems that the basic memory cost is still large,although the memory of model is far smaller.

And most important,how to release it.Not use F5(fresh),or iframe.

**Comment by mrdoob** [comment]
I think you should report this issue to Chrome instead.

**Comment by shyakocat** [comment]
> I think you should report this issue to Chrome instead.

Thank you for replying when busy.

(Forgive my poor English)

Probably it really relates with Chrome.If have any idea or new process,I’d appreciate it if you could concat me then.
