### ISSUE TITLE
Add module based codepen/jsfiddles?

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#17437]
These templates use `<script>` tags

* [jsfiddle](https://jsfiddle.net/3foLr7sn/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/qgu17w5o/) (dev branch)
* [codepen](https://codepen.io/anon/pen/aEBKxR) (latest release branch)
* [codepen](https://codepen.io/anon/pen/BJWzaN) (dev branch)

Both codepen and jsfiddle now support module scripts.

For jsfiddle you need to set it to use no wrap

<img width="326" alt="Screen Shot 2019-09-06 at 10 02 47" src="https://user-images.githubusercontent.com/234804/64393882-734efa80-d08e-11e9-9eb4-b5b0e151bef5.png">

Whether you want to add them, replace the old module ones, or do nothing is of course up to you guys. Just passing on that both systems can handle `import` now

Examples:

* [jsfiddle](https://jsfiddle.net/greggman/pfdt8h6e/)
* [codepen](https://codepen.io/greggman/pen/aboEyNZ)

**Comment by looeee** [comment]
My preference would be to stop recommending jsfiddle at all since it's completely unusable on mobile (well, I think you can add '/show' or something to the URL to display just the preview, but most people don't know that). It's also blocked in China, according to a recent user on the forum. 

Perhaps we could take this opportunity to include an example that loads models using glitch too.

**Comment by Mugen87** [comment]
What are the alternative to jsfiddle? I don't like codepen since you need an account in order to create pens.

**Comment by looeee** [comment]
There's codesandbox.io and glitch.com, no need for accounts on either and they both allow uploading assets.

**Comment by Mugen87** [comment]
It's very easy with codesandbox.io to add `npm` packages (which is actually nice way to define external dependencies). Is this also possible with glitch.com?

**Comment by looeee** [comment]
> Is this also possible with glitch.com?

Yes, you just add them to package.json as usual.

**Comment by Mugen87** [comment]
Good to know, thx 😊

**Comment by mrdoob** [comment]
Thanks! Updated https://github.com/mrdoob/three.js/commit/b874402805d37b27d22d6e3a6212d4a843266568

I removed the codepen links because, indeed, it seems like they force you to create an account if you want to fork them.
