### ISSUE TITLE
Pointlight does not work in PyQt5 QwebEngineView 

### ISSUE THREAD

**Issue by xflyyxfl** [mrdoob/three.js#17448]
while I loaded a scene(Any scene with light) in PyQt5 QwebEngineview,(chrome)  It's all black but edge line.
I am not sure the the problem from threejs or QwebEngineview. and when I load https://webglreport.com/ in QwebEnV,it tells that the it support webgl1 and webgl2

**Comment by Mugen87** [comment]
Can you please verify if other WebGL demos work? For instance the example from Babylon.js:

https://doc.babylonjs.com/examples/

**Comment by xflyyxfl** [comment]
> Can you please verify if other WebGL demos work? For instance the light examples from Babylon.js:
> 
> https://doc.babylonjs.com/examples/
No,it dooe not work.
I just load https://doc.babylonjs.com/examples/ in QwebEngineView,when I choose a example at left, the right area is just white blank. But it does work normally in Chrome

**Comment by xflyyxfl** [comment]
So the QwebEngineView is not a real Chromeium.
I quit it. 
Electron will be my choice.

**Comment by Mugen87** [comment]
Good luck! 😊
