### ISSUE TITLE
How to see the webgl_custom_attributes_points2 example in CodePen?

### ISSUE THREAD

**Issue by castana1962** [mrdoob/three.js#17450]
Hi
Sorry for my ignorance but I am trying with one example from here.
It is the webgl_custom_attributes_points2
Since I am starting with this topic, I copied the htlm code of this example in CodePen( only in the Html tab, but I do not know what code should I add in the CSS and JS tabs)
and I only can see the following
three.js - custom attributes example - particles - billboards
For it, Could anybody advice how I could see this example of in the CodePen?
Thanks for your time
Best Regards
Alejandro

##### Three.js version

- [ ] Dev
- [ ] r108
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Here is a glitch with the example: https://glitch.com/~sepia-pelican

It's always recommended to check the browser console for errors. E.g. if you load the sprite textures from the wrong URL, the example will just render a black screen.

Please use the [forum](https://discourse.threejs.org/) for more help.

**Comment by castana1962** [comment]
Hi Murgen87
Thanks for your help !!!
Best Regards
Alejandro
