### ISSUE TITLE
Generic SkinnedMesh example for CCDIkSolver?

### ISSUE THREAD

**Issue by crazyquark** [mrdoob/three.js#17452]
Hello,

I apologize if I am being dense but I've been trying to figure out how to build an IK chain for an existing mesh and skeleton(exported from Blender as GLTF).
All I have in terms of docs is this page: https://threejs.org/docs/#examples/en/animations/CCDIKSolver

**Comment by crazyquark** [comment]
:( There are no answers there, that's why I hoped the devs might help.

**Comment by Mugen87** [comment]
The idea is to ask a new question at stackoverflow or the forum.

**Comment by abernier** [comment]
for ref, original @crazyquark question on the forum: https://discourse.threejs.org/t/example-of-how-to-use-ccdiksolver-with-a-generic-skinnedmesh/9571
