### ISSUE TITLE
DRACOloader getDecoderModule / releaseDecoderModule have been removed but no instance replacement

### ISSUE THREAD

**Issue by flipswitchingmonkey** [mrdoob/three.js#17464]
##### Description of the problem
Latest changes to DRACOloader deprecated the getDecoderModule and releaseDecoderModule methods and show this message instead:
THREE.DRACOLoader: The .getDecoderModule() method has been removed. Use instance methods.

However no instance methods are provided.

##### Three.js version

- [ ] Dev
- [x] r108

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
see https://discourse.threejs.org/t/issue-with-setdecoderpath/9556
