### ISSUE TITLE
Feature Request. AnimationMixer.timeJump(timeInSeconds)

### ISSUE THREAD

**Issue by Bug-Reaper** [mrdoob/three.js#17485]
So I'm working on an animation editor. For this reason, I needed to be able to jump to specific times in an animation. Unfortunately `AnimationMixer.update()` only let's you jump to a new time relative to your old time. Great for normal playback. Not great if you're trying to implement a slider that allows the user to scrub through the animation and jump to specific points. No docs on this but I did find a way:

```
  function jumpTime(animMixer, timeInSeconds){
    animMixer.time=0;
    for(var i=0;i<animMixer._actions.length;i++){
      animMixer._actions[i].time=0;
    }
    animMixer.update(timeInSeconds)
  }
```
This works great, but it feels like a total hack since you have to use the undocumented `_actions` attribute of the AnimationMixer object.

Can I make a PR to add a `.timeJump(seconds)` method to the AnimationMixer object? I think my use case above highlights sufficient need.

**Comment by mrdoob** [comment]
> Can I make a PR to add a `.timeJump(seconds)` method to the AnimationMixer object? I think my use case above highlights sufficient need.

Sounds good to me! `.setTime(seconds)` may be a better name though?

**Comment by Bug-Reaper** [comment]
Agreed! `setTime` is definitely less confusing than `timeJump`. PR submitted :)
