### ISSUE TITLE
The shadow effect is not realistic

### ISSUE THREAD

**Issue by migsantos121** [mrdoob/three.js#17492]
##### How to improve shadow effect
![image](https://user-images.githubusercontent.com/36492625/64864390-445cf980-d637-11e9-80b6-e009cf66983b.png)
I have added shadow effect to the mesh and used radius to make it look better.
It's better now but still not so vivid and realistic.
How can I improve it?
I want to make it like the below image.
![image](https://user-images.githubusercontent.com/36492625/64864451-69ea0300-d637-11e9-8732-813507266f09.png)

- [ ] Dev
- [ ] r108
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the forum for help requests.

https://discourse.threejs.org/
