### ISSUE TITLE
微信小程序

### ISSUE THREAD

**Issue by haihuo0910** [mrdoob/three.js#17506]
什么时候可以支持一下微信小程序？

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests. Besides, please write your posts in English.

**Comment by haihuo0910** [comment]
Ok, thank you

**Comment by mrdoob** [comment]
Translation:

**WeChat applet**
When can I support the WeChat applet?

**Comment by yannliao** [comment]
@haihuo0910  i have transplant three.js to wechat mini program. See [https://github.com/yannliao/three.js](https://github.com/yannliao/three.js) . Welcome for PR and issue.

**Comment by yannliao** [comment]
@haihuo0910 for now primitives , gTLFLoader , orbitcontrol , ObjLoader are supported

**Comment by zzy-life** [comment]
> @haihuo0910 i have transplant three.js to wechat mini program. See https://github.com/yannliao/three.js . Welcome for PR and issue.

Your project has not been updated in two or three years
