### ISSUE TITLE
MeshStandardNodeMaterial doesn't seem to support opacity

### ISSUE THREAD

**Issue by ghost** [mrdoob/three.js#17518]
The `transparent` property of a `MeshStandardNodeMaterial` gets set back to false after one frame when the property `needsUpdate` is set to true. The opacity property when set to 0.7, and stays like that even after the update.

This makes it so that transparency is not supported when using the `MeshStandardNodeMaterial`. Unless I'm missing something? See this [JSFiddle](https://jsfiddle.net/b2chkteL/).

I would like to see this working 😋

**Comment by donmccurdy** [comment]
I think that setting `material.alpha = <some node>` automatically enables transparency.  For example:

```javascript
material.alpha = new SwitchNode( new TextureNode( baseColorTexture ), 'a' );
```

If you're using alpha for alpha clip/test, instead, use `material.mask`.

**Comment by sunag** [comment]
@n2k3s2it, for now, you can use something like @donmccurdy suggested:
This feature should be implemented at some point.

```javascript
var material = new MeshStandardNodeMaterial();
material.color.setHex( 0x00ffff );
material.fragment.alpha = new FloatNode( 0.5 );
```

**Comment by n2k3s2it** [comment]
Thanks for the fast response. The workaround is enough for me at this moment. I'll see this fixed in a future version. Thanks!

**Comment by n2k3s2it** [comment]
Offtopic note: I'll be continuing on my personal account @n2k3 (I can't seem to transfer issues to my personal account)

**Comment by Mugen87** [comment]
https://github.com/mrdoob/three.js/issues/14722#issuecomment-1236774514
