### ISSUE TITLE
NodeMaterial: Roughness appears to be broken

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#17523]
`git bisect` suggests #17368, but there are so many commits for which the shader does not even compile, it is hard to pinpoint exactly when the error was introduced.

https://threejs.org/examples/webgl_materials_envmaps_hdr_nodes.html (set metalness to 1)

### Three.js version

- [ x ] Dev
- [ x ] r108

**Comment by sunag** [comment]
I fixed this in NodeMaterial r8, if I am not mistake is related with maxMipLevel, but r8 still need more work to finish... 
I will create a PR to fix some issues recently.
