### ISSUE TITLE
add examples/jsm, examples/js folders to CDN and change three.js CDN path

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#17522]
Would it be a good idea to add the examples/jsm and examples/js folders to the CDN?

There's a few reasons this seems like it would be a good idea

1. The offical instructions say you should always use the correct version of an example (like OrbitControls) but 1000s and 1000s of snippets/codepens/jsfiddles etc link directly to https://threejs.org/examples/js/controls/OrbitControls.js. Of course putting the example js files on the CDN won't make devs do it correctly but it will at least give them a simple option

2. If three.js's CDN path changed from 

    ```
    https://cdnjs.cloudflare.com/ajax/libs/three.js/109/three.module.js
    ```

    to

    ```
    https://cdnjs.cloudflare.com/ajax/libs/three.js/109/build/three.module.js
    ```

    and the examples jsm files were at

    ```
    https://cdnjs.cloudflare.com/ajax/libs/three.js/109/examples/jsm/...
    ```

    Then users could use three **and** all the supporting example helpers like GLTFLoader, EffectComposer, etc via ES6 modules.

    As it is `three.module.js` is on a CDN but AFAICT there isn't much point to that since you can't use any of the modules as internally they all have paths of the form `import {x} from '../../../build/three.module.js'`

**Comment by donmccurdy** [comment]
Is Cloudflare the official three.js CDN in some way? There are others that already support examples:

```
https://cdn.jsdelivr.net/npm/three@v0.108.0/examples/jsm/utils/SkeletonUtils.js
```

```
https://unpkg.com/three@0.108.0/examples/jsm/loaders/GLTFLoader.js
```

**Comment by greggman** [comment]
I have no idea what the offical CDN is. cloudflare comes up first when I search

https://www.google.com/search?q=three.js+cdn

**Comment by mrdoob** [comment]
I think option 2 sounds good to me.
Is that something we need to ask to the cdnjs project?

**Comment by donmccurdy** [comment]
Looks like they're managed here, with some automation: 

https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/three.js

Don't know whether replicating `examples/js/*` and `examples/jsm/*` would be something the cdnjs maintainers want or not. 🤔

**Comment by donmccurdy** [comment]
^But yeah to be clear, Cloudflare's CDNJS project is not maintained by us; we can only make suggestions or pull requests for what they include.
