### ISSUE TITLE
FBXLoader: misplaced animation timings

### ISSUE THREAD

**Issue by alexkuz** [mrdoob/three.js#17540]
##### Description of the problem

I have a FBX model with several animations and for some reason each animation got a delay, like they are placed one after another (notice a duration here):

![Screen Shot 2019-09-19 at 20 18 38](https://user-images.githubusercontent.com/790659/65268023-ed679080-db1e-11e9-9c78-4696a32e44af.png)

I tried converting it with `fbx2gltf`, didn't succeeded to actually render it yet but at least timings look fine:
![Screen Shot 2019-09-19 at 20 17 39](https://user-images.githubusercontent.com/790659/65268211-59e28f80-db1f-11e9-987a-7a88e67a48f2.png)

Here's the model (pass: fbxbug):

[female.zip](https://github.com/mrdoob/three.js/files/3632583/female.zip)

And here's how one of animations looks like compared with Autodesk FBX Review:

[Screen Recording 2019-09-19 at 19.44.06.zip](https://github.com/mrdoob/three.js/files/3632603/Screen.Recording.2019-09-19.at.19.44.06.zip)

##### Three.js version

- [ ] Dev
- [x] r108
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by looeee** [comment]
Thanks for sharing your model @alexkuz.

Can you confirm whether this is the same issue as #14894 ?

**Comment by alexkuz** [comment]
Ah, yes, it does look very similar.
You can close this one as a duplicate, I guess :)
