### ISSUE TITLE
Adding THREE.Fire to a scene breaks THREE.OutlinePass

### ISSUE THREAD

**Issue by DavidDufour** [mrdoob/three.js#17551]
##### Description of the problem

I'm trying to combine a toon shader, outline pass, pixel pass, and a fire effect in a demo I'm doing and I noticed that when you add a FIRE it breaks OutlinePass for other objects.

Example:
https://jsfiddle.net/xq5m96c8/6/

I think the release and dev branches are labeled wrong here:
* [jsfiddle](https://jsfiddle.net/yn8azeg1/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/kLwhx875/) (dev branch)

##### Three.js version

- [x] Dev
- [ ] r108
- [ ] ...

##### Browser

- [] All of them
- [X] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

P.S. Really loving three.js

**Comment by DavidDufour** [comment]
Upon further inspection if the FIRE is added to OutlinePass than the other objects can be outlined:

https://jsfiddle.net/f0329jyo/4/

**Comment by Mugen87** [comment]
`THREE.Fire` was not tested with all possible combinations with other `three.js` classes. So it's not surprising that certain scenarios do not work.

**Comment by mikepiecuch** [comment]
I can take a look and see if I can figure it out.

**Comment by Mugen87** [comment]
Closing, see #20495.
