### ISSUE TITLE
MeshPhongMaterial.specular is not a THREE.Color

### ISSUE THREAD

**Issue by jeum** [mrdoob/three.js#17555]
Hi
For some reason the `THREE.MeshPhongMaterial.specular` is not a `THREE.color` :

`console.log(material instanceof THREE.Color) => false`
and
`console.log(material.specular) => ... <prototype>: Object { … }`

**Comment by Mugen87** [comment]
> For some reason the THREE.MeshPhongMaterial.specular is not a THREE.color

As you can see here, the property is of type `THREE.Color`.

https://github.com/mrdoob/three.js/blob/5eedaf42d7578702f0a58f97c0d0148abfc87bae/src/materials/MeshPhongMaterial.js#L64

> console.log(material instanceof THREE.Color) => false

Your code is actually wrong. It should be:

```js
console.log(material.specular instanceof THREE.Color);
```

Live demo: https://jsfiddle.net/c5wh0sr6/
