### ISSUE TITLE
TypeError when copying MeshStandardMaterial to MeshPhysicalMaterial

### ISSUE THREAD

**Issue by akutruff** [mrdoob/three.js#17565]
##### Description of the problem

When passing a MeshStandardMaterial to MeshPhysicalMaterial.copy(), the following error occurs
```
  TypeError
      at Vector2.copy 
      at MeshPhysicalMaterial.copy
```
https://github.com/mrdoob/three.js/blob/d39dabbdc5ff35326a0ae0512773ebca95fe3555/src/materials/MeshPhysicalMaterial.js#L74

```source.clearcoatNormalScale``` is undefined on MeshStandardMaterial, which leads to the error.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/b9dy05uk/) (latest release branch)

##### Three.js version

- [ ] Dev
- [x ] r108
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
> When passing a MeshStandardMaterial to MeshPhysicalMaterial.copy()

Out of curiosity, what's your use case for doing that?

**Comment by akutruff** [comment]
The code I'm maintaining has a techniques system that converts materials generally to physical materials.  Was working fine, but broke now that I'm trying to upgrade to r108

**Comment by Mugen87** [comment]
Performing a copy operations between different material types is actually not supported. However, there is #13111.

**Comment by mrdoob** [comment]
Hmm, I wonder what happens if you do this instead:

```js
var material1 = new THREE.MeshStandardMaterial();
var material2 = new THREE.MeshPhysicalMaterial( material1 );
```

**Comment by akutruff** [comment]
Nice! Using the constructor seems to do the trick at first blush.  Will keep monitoring.

**Comment by akutruff** [comment]
Actually, there is a problem still.  After using the constructor version, the MeshPhysicalMaterial has .defines as STANDARD and not PHYSICAL.  The .type property is also clobbered and is now MeshStanadardMaterial.

**Comment by takahirox** [comment]
> /cc @takahirox

@mrdoob You meant, do you want me to fix the conflicts in #13111? (Sorry, I didn't notice for a while)

**Comment by Mugen87** [comment]
I personally would not support copy operations between different materials. `copy()` should be restricted to the same type. Everything else is a hack from my point of view.

Copying incompatible materials should be performed property by property on app level.

**Comment by gborisg** [comment]
I just bumped into another use case for this request. I am using the GLTFLoader and the output does not support clear coat. I need to install that clear coat, so I need to upgrade the material to MeshPhysicalMaterial. Hopefully this will get solved somehow for the people who will need it in the future.

**Comment by takahirox** [comment]
> Copying incompatible materials should be performed property by property on app level. Hence, I vote to close the issue and #13111.

Coming to think agree with it. For example, if two or more materials have the same name property but their type are different (e.g., float vs array) the code would be complex. Or it would require us to carefully name properties. I don't think it's good.

If we still think we want to support copying between different materials, making helper functions (in examples?) with explicit type name `copy_from_standard_to_physical()` might be good rather than doing in `copy()`?

**Comment by mrdoob** [comment]
I think I vote for not supporting this.
