### ISSUE TITLE
Vector2.rotate(angle, optionalCenter) to replace Vector2.rotateAround(center, angle) ?

### ISSUE THREAD

**Issue by EliasHasle** [mrdoob/three.js#17568]
Context: #7307 

Would it be even better with:
```
rotate: function ( angle, center ) {

    if ( center === undefined) {

        center = _v.set( 0, 0 ); //where _v is preallocated in module scope
        ////Could even be
        //center = { x: 0, y: 0 };
        //for the purpose here

    }

    var c = Math.cos( angle ), s = Math.sin( angle );

    var x = this.x - center.x;
    var y = this.y - center.y;

    this.x = x * c - y * s + center.x;
    this.y = x * s + y * c + center.y;

    return this;

}
```

rotate with mandatory angle and optional center defaulting to the origin (i.e. treating the vector as a direction). This is what I repeatedly see myself expecting to find in Vector2.

This mirrors `Vector2.angle()` better (since that one always is with respect to the origin). In fact, that one could be `Vector2.angle(optionalCenter)` for even better symmetry...

**Comment by EliasHasle** [comment]
Or just:

```
rotate: function ( angle, center ) {

    var cx = 0, cy = 0;

    if ( center !== undefined ) {

        cx = center.x;
        cy = center.y;

    }

    var c = Math.cos( angle ), s = Math.sin( angle );

    var x = this.x - cx;
    var y = this.y - cy;

    this.x = x * c - y * s + cx;
    this.y = x * s + y * c + cy;

    return this;

}
```

**Comment by Mugen87** [comment]
Since there are methods like `Quaternion.rotateTowards()` or `Vector3.angleTo()` the nomenclature `Vector2.rotateAround()` seems consistent to me. TBH, I would keep the method as it is.
