### ISSUE TITLE
Some vertex of gltf are wrong. Howcan I solve that?

### ISSUE THREAD

**Issue by scf89** [mrdoob/three.js#17577]
Hello
I have an issue when I get the vertexfrom a face of a gltf model with three. I noticed that most of the faces have stored wrong normal and vertex values and I need the correct normal to write a function
![image](https://user-images.githubusercontent.com/48352507/65605274-1bc6ef00-dfa9-11e9-95cf-7f8327bf1941.png)

In the image you can see that the model is correct but for the point that it's in the origin of the axis says that the vertex ofthe face are those three espheres
I don't know exactly what's happening because the model is loaded well but vertex are different
Any help will be welcome
Thanks

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
