### ISSUE TITLE
BufferGeometry.fromGeometry() does not set isBufferGeometry

### ISSUE THREAD

**Issue by geoynomous** [mrdoob/three.js#17574]
```
var geometry = new THREE.Geometry();
geometry.vertices.push(
    new THREE.Vector3( -10,  10, 0 ),
    new THREE.Vector3( -10, -10, 0 ),
    new THREE.Vector3(  10, -10, 0 )
);
console.log('geometry', geometry.isGeometry, geometry.isBufferGeometry);

var bufferGeometry = new THREE.BufferGeometry().fromGeometry(geometry);
console.log('bufferGeometry', geometry.isGeometry, geometry.isBufferGeometry);

```
the later is `(true, undefined)`, but should be `(true, true)`

see https://jsfiddle.net/6gch1xum/

There is also an warning "THREE.DirectGeometry: Faceless geometries are not supported." which I understand ... but it should not come in this context - when moving from a Geometry to a BufferGeometry

##### Three.js version

- [ ] Dev
- [x] r108
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> but it should not come in this context

Actually it should come in this since you have not defined any faces for your geometry.

> the later is (true, undefined), but should be (true, true)

That's wrong, `(true, undefined)` is correct. `geometry` still refers to `Geometry` so `isBufferGeometry` is of course `undefined`.

Fixed code: https://jsfiddle.net/Lxoj21wr/
