### ISSUE TITLE
Update Material type definitions to allow nullable textures

### ISSUE THREAD

**Issue by OlovNord** [mrdoob/three.js#17587]
Update the type definitions for `MaterialParameters` (and subclasses) to allow null for any texture values, this would be more consistent with the type definitions of `Material` (and subclasses) and also allow removing multiple textures at once using `setValues`.

Example of the inconsistent definitions from [MeshStandardMaterial](https://github.com/mrdoob/three.js/blob/master/src/materials/MeshStandardMaterial.d.ts):
`MeshStandardMaterial` defines map as `map: Texture | null;`
`MeshStandardMaterialParameter` defines map as `map?: Texture;` but should probably be defined as  `map?: Texture | null;`

**Comment by Mugen87** [comment]
I don't see a problem of making this change. Do you want to give it a try?

**Comment by OlovNord** [comment]
Sure, I'll see what I can do.
