### ISSUE TITLE
Suggestion: Matrix addition and subtraction

### ISSUE THREAD

**Issue by EliasHasle** [mrdoob/three.js#17582]
I suggest introducing per-element addition of matrices in Matrix3 and Matrix4. This will, among other possibilities, allow simplification of some calculations that would otherwise involve first multiplying the same vector by different matrices and then adding/subtracting the results. (Matrix product is distributive over addition.)

Simplify:
```
target.set(0,0,0);
v.copy(input).applyMatrix3(A);
target.sub(v);
v.copy(input).applyMatrix3(B);
target.sub(v);
return target;
```

to
```
target.set(0,0,0);
M.addMatrices(A,B);
v.copy(input).applyMatrix3(M);
target.sub(v);
return target;
```

The single line spared must be paid for with declaration/preallocation of `M`, but it spares a bunch of multiplication operations caused by the extra `applyMatrix3`. Not least, matrix addition is a basic operation for manipulating matrices, that people familiar with linear algebra will expect to find (even though the linalg features of three.js are very targeted towards GL).

I will gladly contribute this feature myself, if there is interest.

**Comment by EliasHasle** [comment]
> Matrix product is distributive over addition.

Note that this property does _not_ carry over to the shorthand homogeneous coordinates transforms in `Vector2.applyMatrix3` and `Vector3.applyMatrix4`. If my suggestion goes through, this should probably be clearly stated in the docs.

I feel a bit in doubt about my plans for (ab)using three.js matrices and vectors for other linear algebra operations than those directly involved in computer graphics. There exist more general-purpose libraries.

**Comment by WestLangley** [comment]
`Matrix4` affine and projection matrices are not closed under addition and subtraction, so your suggestion is not appropriate in that case.

`Matrix3` is a limited class to support methods needed for the library.

>I feel a bit in doubt about my plans for (ab)using three.js matrices and vectors for other linear algebra operations than those directly involved in computer graphics. There exist more general-purpose libraries.

Agreed.

**Comment by EliasHasle** [comment]
The fact that not all matrix additions/subtractions make sense is not alone an argument against supporting addition/subtraction. However, in computer graphics the usage of Matrix4 is almost solely for affine transforms, so in that context you have a point.

In https://news.ycombinator.com/item?id=16789716, @bhouston considers the possibility of using a faster back-end for three.js linear algebra operations. If that were to be applied, the additional cost of also allowing n*m matrices and more general linalg operations would probably be low. But I guess I should just close this issue soon if there isn't a "landslide" of support for including more general linalg.

**Comment by Mugen87** [comment]
> But I guess I should just close this issue soon if there isn't a "landslide" of support for including more general linalg.

More methods means we also have to maintain this stuff. I think it's sufficient if we focus on math logic which is related to interactive 3D graphics.
