### ISSUE TITLE
Sample code doesn't work.

### ISSUE THREAD

**Issue by JPNYKW** [mrdoob/three.js#17585]
##### Description of the problem

I tried run two source codes. there's on README in this repository, and [three.js website](https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene).
but, they doesn't work.

```js
// on README
var camera, scene, renderer;
var geometry, material, mesh;

init();
animate();

function init() {

	camera = new THREE.PerspectiveCamera( 70, window.innerWidth / window.innerHeight, 0.01, 10 );
	camera.position.z = 1;

	scene = new THREE.Scene();

	geometry = new THREE.BoxGeometry( 0.2, 0.2, 0.2 );
	material = new THREE.MeshNormalMaterial();

	mesh = new THREE.Mesh( geometry, material );
	scene.add( mesh );

	renderer = new THREE.WebGLRenderer( { antialias: true } );
	renderer.setSize( window.innerWidth, window.innerHeight );
	document.body.appendChild( renderer.domElement );

}

function animate() {

	requestAnimationFrame( animate );

	mesh.rotation.x += 0.01;
	mesh.rotation.y += 0.02;

	renderer.render( scene, camera );

}
```

And

```html
<!-- on Three.js website -->
<html>
	<head>
		<title>My first three.js app</title>
		<style>
			body { margin: 0; }
			canvas { width: 100%; height: 100% }
		</style>
	</head>
	<body>
		<script src="js/three.js"></script>
		<script>
			var scene = new THREE.Scene();
			var camera = new THREE.PerspectiveCamera( 75, window.innerWidth/window.innerHeight, 0.1, 1000 );

			var renderer = new THREE.WebGLRenderer();
			renderer.setSize( window.innerWidth, window.innerHeight );
			document.body.appendChild( renderer.domElement );

			var geometry = new THREE.BoxGeometry( 1, 1, 1 );
			var material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
			var cube = new THREE.Mesh( geometry, material );
			scene.add( cube );

			camera.position.z = 5;

			var animate = function () {
				requestAnimationFrame( animate );

				cube.rotation.x += 0.01;
				cube.rotation.y += 0.01;

				renderer.render( scene, camera );
			};

			animate();
		</script>
	</body>
</html>
```

I got errors there are same in two codes.

##### on Google Chrome
![image](https://user-images.githubusercontent.com/31243896/65740056-65871500-e122-11e9-9b85-2f85e84f1cde.png)

##### on Firefox Developer Edition
![image](https://user-images.githubusercontent.com/31243896/65740570-2d80d180-e124-11e9-9d9e-d0a1aa2ed067.png)

##### Three.js version

- [x] Dev
- [x] r108
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by EliasHasle** [comment]
I just tested the second one with r108, and it works as expected. If you do another run with `three.js` instead of `three.min.js`, it will be easier to debug.

Note that there is also a complaint about character encoding. Could you share the exact content of your source file?

I guess this will soon be judged as a user-side problem, and then you will surely feel more welcome asking on the forum: https://discourse.three.js.org :)

Hm, the example code misses `<!doctype html>` at the top. Shouldn't be a big issue, but I think it should in principle have been there.

**Comment by Mugen87** [comment]
Please use the forum for help requests. 

Besides, the code from the readme file is actually used in the following fiddle:

https://jsfiddle.net/f2Lommf5/

**Comment by JPNYKW** [comment]
I'm sorry, I was mistaken. 
It does worked.
