### ISSUE TITLE
ReferenceError: Vector3 is not defined in PointerLockControls

### ISSUE THREAD

**Issue by kdaimiel** [mrdoob/three.js#17594]
I am getting this error after updating **three.js** to the las version (**0.108.0**) when I try to use PointerLockControls.

```	
   ReferenceError: Vector3 is not defined
	    at <Jasmine>
	    at new THREE.PointerLockControls (node_modules/three/examples/js/controls/PointerLockControls.js:25:12)
	    at Object.createControls (src/js/scene-factory.js:7:2946)
	    at UserContext.<anonymous> (test/js/scene-factorySpec.js:86:35)
	    at <Jasmine>
```
I guess this came from change https://github.com/mrdoob/three.js/commit/c15c2d6aac6e9705b0d5543c654e40c6e01a8b2f#diff-91b9b80f02ab244e0330fd5aac0bd483 where two new functions are created **moveForward** and **moveRight** with a new vector instanced as `var vec = new Vector3();` and I suppose it should be instanced as `var vec = new THREE.Vector3()`

**Comment by WestLangley** [comment]
Thanks, but that was fixed in #17444
