### ISSUE TITLE
DRACOLoader: Add parse() method

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#17593]
The deprecated `decodeDracoFile` method should be removed and replaced with a `parse` method similar to other loaders. Currently `decodeDracoFile` does not propagate errors, and should do so. So probably a signature like:

```js
dracoLoader.parse( arrayBuffer, /* options, maybe? */, onLoad, onError );
```

**Comment by mrdoob** [comment]
> /* options, maybe? */

What options does it need?

**Comment by donmccurdy** [comment]
Currently it takes `attributeIDs` and `attributeTypes`, which are only needed if you create a `.drc` file in a very particular way (which most Draco users don't). There were some other options (quantization, triangle fans) that I've removed in the latest refactoring. I omitted them to simplify things, and because I don't have any examples of someone using them, but I wouldn't be opposed to re-implementing them if the need arises, and if so those would require two additional options.

For users with Draco-compressed `.gltf` files (which I think is the large majority), none of this is necessary.

**Comment by mrdoob** [comment]
I think I would follow [ImageBitmapLoader](https://github.com/mrdoob/three.js/blob/dev/src/loaders/ImageBitmapLoader.js#L33-L39) pattern.

```js
var loader = new THREE.DracoLoader();
loader.setOptions( {} );
loader.parse( 'file.drc', onParse, onError );
```

**Comment by donmccurdy** [comment]
Disadvantage here is that `attributeIDs` and `attributeTypes` are likely to be different for each geometry decompressed. If each `parse()` call requires a new loader, then we'd need those loaders to share a pool of workers and balance tasks across them.

We could make sure the options are copied and stored for the task duration when parse is called, to support this pattern...

```js
loader
  .setOptions( { ... } )
  .parse( buffer1, onLoad, onError )
  .setOptions( { ... } )
  .parse( buffer2, onLoad, onError );
```

... but I don't know if that's better or not. 🤔

**Comment by Gamesbxonline** [comment]
Thank you guys, I will learn from you
---------------------
**GamesBX2**
