### ISSUE TITLE
OBJLoader2 (jsm) not working correctly on IE11

### ISSUE THREAD

**Issue by Jens84** [mrdoob/three.js#17590]
##### Description of the problem

In OBJLoader2Parser.js, the **skinIndex** and **skinWeight** buffers are not defined (skinning is not supported by OBJ format) but not explicitely set to null.

https://github.com/mrdoob/three.js/blob/ab18028c402f7d7f5a64772ee297be9acb746df0/examples/jsm/loaders/obj2/worker/parallel/OBJLoader2Parser.js#L1050-L1056

In MeshReceiver.js, if the buffers are **not strictly equal to null**, then it creates typed arrays from them.

https://github.com/mrdoob/three.js/blob/ab18028c402f7d7f5a64772ee297be9acb746df0/examples/jsm/loaders/obj2/shared/MeshReceiver.js#L110-L119

The issue seems to be that IE11 does not accept to instantiate a typed array with an **undefined** size (while other browsers seem to, by considering it as 0) and throws an exception (**Typed array constructor argument is invalid**):

![IEDoesNotAcceptUndefinedSize](https://i.imgur.com/tMuq2rt.png)

![ChromeAcceptsUndefinedSize](https://i.imgur.com/bTY61Vo.png)

I would suggest either to check (in MeshReceiver) if the buffers are **not equal to null** (but not strictly, so that it also works with **undefined** values) or to explicitely set the missing buffers to **null** (in OBJLoader2Parser).

##### Three.js version

- [x] Dev
- [x] r108
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Um, IE11 does not support ES6 syntax so I really wonder how you execute the code in this browser...

**Comment by Jens84** [comment]
We're building ou app using Stencil, so I guess it compiles it with polyfills.

**Comment by Mugen87** [comment]
Okay I see. I guess @kaisalmen can have a look at this issue.

**Comment by kaisalmen** [comment]
Will see if I can fix this tonight. Release is tomorrow, correct? Are there more then two IE11 users left on the planet? 😉

**Comment by Jens84** [comment]
Haha trust me, if I could, I would not bother supporting it ^^

**Comment by Mugen87** [comment]
> Release is tomorrow, correct?

The milestone says it's next monday^^.

**Comment by kaisalmen** [comment]
> The milestone says it's next monday^^.

Ah, last release was on the 28th. 😊 

I pushed a branch and will now open a WIP PR and remove the WIP status if @Jens84 agrees with the change as I cannot test it with IE11 myself.
