### ISSUE TITLE
Can instancing work with `MeshStandardMaterial`?

### ISSUE THREAD

**Issue by marcofugaro** [mrdoob/three.js#17606]
##### Description of the problem

Hi! Love the new `InstancedMesh`, so much easier to use!
Was wondering if it will work with more complex materials such as `MeshStandardMaterial`? I tried using it in the example, but it didn't work and I am guessing it's because `InstancedMesh` is still WIP.

My objective is to use `MeshStandardMaterial` with an envMap/texture, will that be possible in the future?

##### Three.js version

- [x] Dev
- [ ] r108
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Yes :)

**Comment by mrdoob** [comment]
https://jsfiddle.net/7ta3nrm5/
