### ISSUE TITLE
OBJLoader2 docs out of date

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#17609]
##### Description of the problem

The [OBJLoader2 docs](https://threejs.org/docs/#examples/en/loaders/OBJLoader2) seem out of date. They mention methods like loadMtl and setMaterials which no longer exist AFAICT

##### Three.js version

- [X] Dev
- [X] r108
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by kaisalmen** [comment]
I already fixed the docs with https://github.com/mrdoob/three.js/pull/17441
