### ISSUE TITLE
Raycasting issue with TriangleStripDrawMode

### ISSUE THREAD

**Issue by jeffpyke** [mrdoob/three.js#17613]
##### Description of the problem
Raycasting doesn't work as expected with TriangleStripDrawMode. Raycasting works as if TrianglesDrawMode was being used. Below is a screenshot with TrianglesDrawMode and TriangleStripDrawMode. Raycasting only intersects over the triangles rather than the entire area as expected.

![Screenshot from 2019-09-30 10:01:09](https://user-images.githubusercontent.com/7103357/65899819-69f13f00-e369-11e9-8879-10f7c00f9a36.png)
![Screenshot from 2019-09-30 10:00:44](https://user-images.githubusercontent.com/7103357/65899822-6bbb0280-e369-11e9-894f-3f3384097572.png)

##### Three.js version

0.100.0

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by gkjohnson** [comment]
Related to #17369 which adds support for raycasting meshes with `TriangleStripDrawMode`.

**Comment by WestLangley** [comment]
Related: `TriangleFanDrawMode` #9869

**Comment by Mugen87** [comment]
`Mesh.drawMode` has been removed. Please check the migration guide for `R112` to see the recommended migration task.

https://github.com/mrdoob/three.js/wiki/Migration-Guide#r111--r112
