### ISSUE TITLE
Materials not correctly applied by ObjLoader2Parallel (jsm)

### ISSUE THREAD

**Issue by Jens84** [mrdoob/three.js#17615]
##### Description of the problem

The OBJLoader2Parallel does not correctly apply given materials, added by calling addMaterials(materials) before loading, when using web workers (executeParallel = true) and falls back to default materials instead.

In WorkerRunner.js, **payload.materials** are applied to the corresponding instance of OBJLoader2Parser using ObjectManipulator.

https://github.com/mrdoob/three.js/blob/a84f4c469dd1b9414b45ff47da8433febc60bfdb/examples/jsm/loaders/obj2/worker/parallel/WorkerRunner.js#L52-L54

However, in order for the ObjectManipulator to call the appropriate method, which is setMaterials(payload.materials), the second argument (L53) should be an object with **materials** as key and **payload.materials** as value.

https://github.com/mrdoob/three.js/blob/a84f4c469dd1b9414b45ff47da8433febc60bfdb/examples/jsm/loaders/obj2/utils/ObjectManipulator.js#L14-L37

I would suggest to move **materials** (L193) to the **params** object above in OBJLoader2Parallel.js and remove L53 from WorkerRunner.js:

https://github.com/mrdoob/three.js/blob/a84f4c469dd1b9414b45ff47da8433febc60bfdb/examples/jsm/loaders/OBJLoader2Parallel.js#L185-L193

##### Three.js version

- [x] Dev
- [x] r108
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
/ping @kaisalmen (sorry for the many pings^^)

**Comment by kaisalmen** [comment]
> /ping @kaisalmen (sorry for the many pings lately^^)

No worries. Good to see people still use the loader...

@Jens84 Thank you for the suggestion. I will check and fix this. It probably broke when I removed the default material init from the constructor of `MaterialHandler`. It will be fixed in r110 as r109 was just released.

**Comment by kaisalmen** [comment]
@Jens84 your analysis perfectly outlined the solution. Thank you 👍 This was broken for a longer time and not recently, I think. I exposed material override in `OBJLoader2#addMaterials` with the above PR as well.
