### ISSUE TITLE
SVGLoader: Unable to load SVG file. Many details lost.

### ISSUE THREAD

**Issue by SeanSure** [mrdoob/three.js#17611]
I had loaded a svg file in my computer,but the svg path didn't render a correct order,many details were been keeped out.and the shape looks like strange.
[map1.svg.zip](https://github.com/mrdoob/three.js/files/3670071/map1.svg.zip)

**Comment by Mugen87** [comment]
I can confirm that the imported SVG does not correct:

Result of `SVGLoader:

![image](https://user-images.githubusercontent.com/12612165/65869416-b42eec00-e37a-11e9-9e5d-fd5e799bb58a.png)

SVG preview on Mac:

![image](https://user-images.githubusercontent.com/12612165/65869457-cdd03380-e37a-11e9-8537-c9bd7f47d1ab.png)

**Comment by WestLangley** [comment]
>SVG rendering is a _can of worms_

For others, that is slang for "SVG rendering is complicated" -- I assume due to the [rendering order](https://www.w3.org/TR/SVG2/render.html#RenderingOrder).

**Comment by yomboprime** [comment]
About the strokes not rendering, I've found it happens only in Firefox. In chrome it renders OK. I will file an issue.

**Comment by SeanSure** [comment]
I counted the area of each mesh first, and then let the larger one load first
