### ISSUE TITLE
Incorrect imports in Typescript types

### ISSUE THREAD

**Issue by sandersn** [mrdoob/three.js#17616]
Imports are incorrect in two d.ts files that provide Typescript types. The upcoming 3.7 version of Typescript found these errors:

1. materials/ShaderMaterial.d.ts

```ts
import { ShaderMaterialParameters } from './ShaderMaterial';
```

The import is circular, referring to ShaderMaterial.d.ts itself!

2. geometries/ExtrudeGeometry.d.ts

```ts
import { CurvePath } from './../extras/core/CurvePath';
import { UVGenerator } from './ExtrudeGeometry';
```

Same for the second import of ExtrudeGeometry.d.ts.
The fix is to delete these exports. I'll create a PR for this shortly.

##### Three.js version

- [x] Dev

**Comment by sandersn** [comment]
Typescript 3.7 will be out next week. Would it be possible to publish a version with this fix before then?

**Comment by mrdoob** [comment]
`r110` is [due in two days](https://github.com/mrdoob/three.js/milestone/23).
