### ISSUE TITLE
Chrome 77 texImage2D upload performance on OSX

### ISSUE THREAD

**Issue by dustinkerstein** [mrdoob/three.js#17619]
_FYI, this appears to be solely a Chromium WebGL issue (ie. not related to Three.js) but I just wanted to post here for informational purposes. Feel free to delete/close if this is unwanted._

I just noticed that my Three.js application was dropping an immense amount of frames on the latest Chrome (tested only on OSX so far). This appears to be coming from `texture.needsUpdate = true` (ie. texImage2D upload). Try comparing this JSFiddle on Chrome 76 vs. 77 - https://jsfiddle.net/qz9ka6xm 

I'll post a bug on Chromium if there's not already one and link it here for reference.

**Comment by dustinkerstein** [comment]
Looks like this is the issue - https://bugs.chromium.org/p/chromium/issues/detail?id=1007889

**Comment by Mugen87** [comment]
There is definitely a huge performance gap between latest Chrome and FF. Tested on macOS.

**Comment by Mugen87** [comment]
Looks like the issue is already fixed in Chrome Canary and Dev (see https://bugs.chromium.org/p/chromium/issues/detail?id=1007889#c33).
