### ISSUE TITLE
PointsMaterial + light support

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#17618]
##### Description of the problem

From #10491 

Currently PointsMaterial doesn't support lighting. It may be interesting if we do.

Suggested how to implement here https://github.com/mrdoob/three.js/issues/10491#issuecomment-329491923

> particle lighting may be computed just by distance from light source (according to intensity, decay, distance parameters of the light sources), it makes sense.

[How it'll look like](https://twitter.com/superhoge/status/946723196148916225)

##### Three.js version

- [x] Dev
- [ ] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by EliasHasle** [comment]
`PointsBasicMaterial` and `PointsLitMaterial`? Hm. <details><summary>A dream I had</summary>I had a dream once of making a `PointsPhongMaterial` that would render perfect spheres with Phong shading, but I think that is better to do otherwise, e.g. using quads (or high-res. spheres, duh), given the huge distortions that will occur near a perspective camera, that will require a lot of discards on large points.</details>

**Comment by Mugen87** [comment]
I think it's important to discuss the general reasonableness of light support for points and lines. Both have no normal data and thus you can't implement proper lighting equations. Not sure we want to go this route and arouse false expectations...

**Comment by mrdoob** [comment]
@EliasHasle You should probably used `InstancedMesh` for your dream 🙂

**Comment by mrdoob** [comment]
@Mugen87 Considering [GLTF may have normals in lines](https://github.com/mrdoob/three.js/issues/17511#issuecomment-531996575) I'd be open minded about this.

**Comment by mrdoob** [comment]
For points, I think it would make sense to have a material that is affected by light based on whether the particle is "in range" to the light.

A good use case would be a rainy night scene where spotlights affect a cloud a points/raindrops.

![Ford-Taurus-2019-red-color-car-in-night-Ford-Taurus-2019-car-in-rain-in-night-wallpaper](https://user-images.githubusercontent.com/97088/65920970-9e7af000-e395-11e9-997f-f2e3ec2ceca7.jpeg)

**Comment by EliasHasle** [comment]
> @EliasHasle You should probably used `InstancedMesh` for your dream 🙂

Yes, but that would be too easy. 😉 I like the beauty of the idea of solving perfect spheres in GLSL without a sphere geometry.

**Comment by LeviPesin** [comment]
Thinking about this issue and https://github.com/mrdoob/three.js/issues/17511... This is a large breaking idea, but -- maybe we can make BasicMaterial, StandardMaterial, PhongMaterial, etc which wouldn't be mesh- or line-dependent but work for any type of object. I think it is rather complicated to try to make this with shader chunks, but I think it's possible using the nodes system...

**Comment by Mugen87** [comment]
This feature is implemented in `WebGPURenderer` via implementing custom lighting models for node materials.

https://threejs.org/examples/webgpu_lights_custom

It's out of scope to implement something comparable for `WebGLRenderer`. Considering this issue as fixed.
