### ISSUE TITLE
FileLoader incorrectly caches responses irrespective of HTTP response code

### ISSUE THREAD

**Issue by nh2** [mrdoob/three.js#17635]
##### Description of the problem

I have a logic around texture loading that retries loading the URL on failure, for the case that a texture is not yet generated server-side or that the server errors out serving it.

I found that three.js's caching logic in `FileLoader` caches responses when it shouldn't, making its `load` function return incorrect results when it is called a second time after an HTTP error.

Concrete exmaple with which I observed it, via a texture loader:

* First call to `load( "non_existent_url.texture", onLoad, onProgress, onError )`
  * HTTP 404 is obtained with response body `Could not find file non_existent_url.texture` from the server, `onError` is called, no texture buffer is passed  to `onLoad`
* Second call to `load( "non_existent_url.texture", onLoad, onProgress, onError )`
  * The cache is inspected, and the string `Could not find file non_existent_url.texture` is passed as an `ArrayBuffer(44)` texture buffer to `onLoad`!
  * Naturally these bytes are not a proper texture, and the texture decoder crashes hard.

So in the first call, `onError` is called correctly, and in the second call `onError` is not called; instead `onLoad` is called with garbage data.

##### Detail investigation

three.js has a `Cache` for HTTP requests in its `FileLoader` class, to load loaded files only once.

It puts things into the cache like here:
https://github.com/mrdoob/three.js/blob/e0a31ea77c0242ae29ef6e951fa588216e1d247f/src/loaders/FileLoader.js#L175

Key parts:

```javascript
var request = new XMLHttpRequest();
request.open( 'GET', url, true );
request.addEventListener( 'load', function ( event ) {
  // ...
  Cache.add( url, response );        // add to cache here
  // ...
  if ( this.status === 200 || this.status === 0 ) {
  // ... further status code handling
```

**As you can see, it puts the `response` into the `Cache.add` _before_ checking the `status` code.**

In particular, it caches it even if the status is 404, a 500-series or anything like that. The response body is put into the cache.
Then where the cache is checked
https://github.com/mrdoob/three.js/blob/e0a31ea77c0242ae29ef6e951fa588216e1d247f/src/loaders/FileLoader.js#L30
when the request comes around next time, it just returns the cached result (response body of the 404 in my example) as the "proper" result of the HTTP request, as if it was a 200.

##### What three.js should do

It should cache responses only on HTTP success, moving the `Cache.add( url, response );` into the `if ( this.status === 200 || this.status === 0 ) {` block.

I'll send a PR for this.

##### Three.js version

- [x] Dev
- [x] r109
- [x] pretty much any previous version

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by nh2** [comment]
PR at #17636..

According to a quick `grep Cache.js`, with results

```
src/Three.js:export { Cache } from './loaders/Cache.js';
src/loaders/FileLoader.js:import { Cache } from './Cache.js';
src/loaders/ImageBitmapLoader.js:import { Cache } from './Cache.js';
src/loaders/ImageLoader.js:import { Cache } from './Cache.js';
```

`ImageBitmapLoader` and `ImageLoader` do not suffer from this problem as `FileLoader` does.

**Comment by Mugen87** [comment]
So the fundamental assumption of your issue is that the status code of HTTP response might change. 

Have you considered to solve this issue on app level? I mean you could test with a simple fetch if the resource is ready and only then load with a `three.js` loader. In this way, the library has not need to be changed (and this no side effects occur).

**Comment by nh2** [comment]
> So the fundamental assumption of your issue is that the status code of HTTP response might change.

@Mugen87 No:

I argue that even if you know and desire that the HTTP status code does _not_ change (e.g. that it always stays 403 Forbidden), three's logic is incorrect:

The first time you query it you get an error (`onError` called), the second time you do not.

If you assume that the status code doesn't change, you should get the same result (`onError`) every time.

Do you see what I mean?

**Comment by Mugen87** [comment]
Okay, an example tells more than thousand words:

https://jsfiddle.net/8r2Lygd7/

So you say the second call of `FileLoader.load()`  should also produce a 404 error, right?

Indeed, the current behavior is strange since the second response is a HTML document. Adding a resource to the cache only on success would solve this issue, right.

Unfortunately, we do not have much test cases to verify the `Cache` logic. AFAICS, only one example does enable the Cache (`webgl_geometry_text`). We might have to merge your proposed PR and hope for the best^^.

**Comment by nh2** [comment]
> So you say the second call of `FileLoader.load()` should also produce a 404 error, right?

Yes, that would be good. Precisely speaking I'm saying the second call should at least call `onError` instead of `onLoad`. But having it re-query the server an re-observe a 404 is the simplest and most sensible behaviour that fulfills that, so that's why I proposed that in my PR.

> Okay, an example tells more than thousand words:

Yeah you're right, I should have made one, but wrote up my findings at 3 am so I ran out of time :sleeping_bed: :)

I've forked and slightly modified your fiddle to log to console which callbacks are called: https://jsfiddle.net/p94sxmbq/

It prints

```
onProgress called
onError called
onLoad called
```

In our desired solution (and my PR), the `onLoad` should not be there.

> Indeed, the current behavior is strange since the second response is a HTML document. Adding a resource to the cache only on success would solve this issue, right.

:+1: 

> Unfortunately, we do not have much test cases to verify the `Cache` logic. AFAICS, only one example does enable the Cache (`webgl_geometry_text`). We might have to merge your proposed PR and hope for the best^^.

That is fine by me :)
