### ISSUE TITLE
SpriteMaterial+Water: unreliable transparency

### ISSUE THREAD

**Issue by anemol** [mrdoob/three.js#17632]
When i wanted to migrate from R91 to the latest version (R109), i encountered a problem of transparency with the use of SpriteMaterial (from a canvas texture) and Water.js (sea), depending on the position of the camera.

With the R91, it works very fine.

Also, for Water.js, the **options.mirror** (true | false) option is no longer available. 

![image](https://user-images.githubusercontent.com/10926763/65982890-9d70be00-e47c-11e9-8a13-e6efe3906294.png)

Live example:  [jsfiddle](https://jsfiddle.net/be9dy7ok/) 

##### Three.js version

- [ ] Dev
- [x] r109

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Linux Mint 19.20 (4.15) -  Nvidia Geforce GTX 1060

**Comment by WestLangley** [comment]
You deleted your SO question. Use `sprite.renderOrder = 1`.
