### ISSUE TITLE
Examples / docs broken in Firefox with experimental OffscreenCanvas enabled

### ISSUE THREAD

**Issue by Prinzhorn** [mrdoob/three.js#17642]
# Description of the problem

Some change in the last few days broke all the examples when experimental OffscreenCanvas is enabled in Firefox. I've had it enabled for a while and I think yesterday I noticed the examples were broken. The reason it crashes is that Firefox does not implement the `2d` context yet, only `webgl`. The offending line of code is https://github.com/mrdoob/three.js/blob/9f4fb2bed002db1d9a5294b4050a585cd90b4552/src/renderers/webgl/WebGLTextures.js#L23 The error is `NS_ERROR_NOT_IMPLEMENTED`

![Selection_533](https://user-images.githubusercontent.com/679144/66055850-7bd40d00-e536-11e9-88ff-0371b4ff3259.png)

We could argue it's expected behavior when enabling an experimental feature and I would accept that. I just thought I'd let you know since it worked until very recently. For now I've disabled it again to keep using the docs.

To reproduce go to `about:config`, enable `gfx.offscreencanvas.enabled` and open https://threejs.org/examples/#webgl_animation_cloth
## Three.js version

- [x] Whatever is used on https://threejs.org/examples/ and https://threejs.org/docs/

## Browser

- [x] Firefox 69.0.1 on Ubuntu with `gfx.offscreencanvas.enabled = true`

## OS
- [x] Linux (I don't have anything else to test)

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/16781#issuecomment-536810694

**Comment by Prinzhorn** [comment]
Glad I could help, here's the relevant bug https://bugzilla.mozilla.org/show_bug.cgi?id=801176

**Comment by mrdoob** [comment]
Glad to know that I'm not crazy (or my computer rather).
I've disabled the flag and it works fine again 🙏

**Comment by Mugen87** [comment]
Now that it's clear where the runtime error comes from: I think I would leave the check in `WebGLTextures` as it is.
