### ISSUE TITLE
InstancedMesh shadows are wrong

### ISSUE THREAD

**Issue by yomboprime** [mrdoob/three.js#17656]
##### Description of the problem

```InstancedMesh``` shadows don't show up correctly. It seems only one instance shadow is rendered always at the origin.

This online experiment shows the bug. Please look at the center of the tower to see the instance shadow:
https://yomboprime.github.io/instancedBricks/examples/instancedBricks.html

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by WestLangley** [comment]
Instancing currently requires a `customDepthMaterial` for proper shadow support.

See https://threejs.org/examples/webgl_buffergeometry_instancing_lambert.html.

**Comment by WestLangley** [comment]
I would consider this a feature request, not a bug.

**Comment by mrdoob** [comment]
I made sure shadows worked when implementing `InstancedMesh`, I'll have a look.

**Comment by mrdoob** [comment]
@yomboprime could you turn the example into a jsfiddle?

**Comment by yomboprime** [comment]
> @yomboprime could you turn the example into a jsfiddle?

I will.

BTW, it is the casting that doesn't work. The receiving of shadows by the instances is working right.

**Comment by mrdoob** [comment]
Oh, I think I know what's happening. Do they work if you hide the floor?

**Comment by mrdoob** [comment]
No need for the jsfiddle. I'm pretty sure I know what it is.

**Comment by yomboprime** [comment]
Oh, I already did it:
https://jsfiddle.net/c61L3y84/

**Comment by yomboprime** [comment]
Note that I edited the fiddle link, it was wrong.

**Comment by yomboprime** [comment]
> Oh, I think I know what's happening. Do they work if you hide the floor?

Yes, they do!

**Comment by mrdoob** [comment]
Should work now!
