### ISSUE TITLE
Script: npm start doesn't work correct in dev branch.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#17668]
##### Description of the problem

I run `npm start`, the `localhost:8080` doesn't work,
but I run `http-server -c-1 -p 8080`, the website is OK.

I think npm script `concurrently` has some thing wrong,
but I don't know how to fix it.

##### Three.js version

- [x] Dev
- [ ] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by arpu** [comment]
does it work with 

```npm run-script start``` ?

**Comment by linbingquan** [comment]
> 
> 
> does it work with
> 
> `npm run-script start` ?

It doesn't work.
![图片](https://user-images.githubusercontent.com/23699926/66260303-748b5880-e7ef-11e9-9460-ebd6c18b1238.png)

**Comment by Mugen87** [comment]
@linbingquan You are on Windows, right? I had the exact same issue with `http-server` and Windows with another project. There is currently an issue with this `npm` module, see

https://github.com/http-party/http-server/issues/525

Although many devs affected the bug has not been fixed so far. The workaround is to use explicit URL like `http://localhost:8080/examples/index.html`. 

@mrdoob An other option is to downgrade the `npm` package in `package.json` to `0.9.0`.

**Comment by makc** [comment]
[seems to be fixed now](https://github.com/http-party/http-server/pull/569)?

**Comment by Mugen87** [comment]
It seems they haven't updated the npm package yet.

**Comment by thornjad** [comment]
The fix is now published as 0.12.0

**Comment by Mugen87** [comment]
See 0998172670b1a385bacba16cbd7145aa1aa662bd
