### ISSUE TITLE
The outline pass doesn't allow for dark outline

### ISSUE THREAD

**Issue by NicolasRannou** [mrdoob/three.js#17665]
##### Description of the problem

The outline pass doesn't allow for dark outlines. Somehow the darker the color the more transparent it is. I'd expect the opacity of the edge not to change with the color.

That may be related to the latest changes made to make it work with transparent background?

Set the visible edge color to '#000'. The edge disappears.
https://threejs.org/examples/?q=out#webgl_postprocessing_outline

##### Three.js version

- [x] Dev
- [x] r109
- [ ] ...

##### Browser

- [x] Chrome

##### OS

- [x] macOS

**Comment by Mugen87** [comment]
> That may be related to the latest changes made to make it work with transparent background?

Are you referring to #17462? The link below leads to the `R108` version without this fix. I can't see a different behavior.

https://rawcdn.githack.com/mrdoob/three.js/r108/examples/webgl_postprocessing_outline.html

**Comment by NicolasRannou** [comment]
Indeed it seems it always behaved like that then, but is it the expected behavior though?

**Comment by Mugen87** [comment]
Probably not. You have similar color issue with a complete withe scene background:

![image](https://user-images.githubusercontent.com/12612165/66253467-0308c700-e769-11e9-8e2c-2335211f31c6.png)

Notice how the outline disappears at certain branches. This issue might be causes by the way the outline is blended over the rendered scene.

**Comment by makc** [comment]
Add this line of code to https://rawcdn.githack.com/mrdoob/three.js/r108/examples/webgl_postprocessing_outline.html
```
outlinePass.overlayMaterial.blending = THREE.SubtractiveBlending
```
and you will get this:
![Screen Shot 2019-11-11 at 23 41 49 ](https://user-images.githubusercontent.com/242577/68626981-e9337000-04dc-11ea-990a-68f9de3886ac.png)

**Comment by VeAmas** [comment]
@makc 
`outlinePass.overlayMaterial.blending = THREE.CustomBlending`
may works better! :)

**Comment by raccoonhands1** [comment]
> [@makc](https://github.com/makc) `outlinePass.overlayMaterial.blending = THREE.CustomBlending` may works better! :)

works! strangely the implementation does not have a normal blending mode by default

**Comment by raccoonhands1** [comment]
> > [@makc](https://github.com/makc) `outlinePass.overlayMaterial.blending = THREE.CustomBlending` may works better! :)
> 
> works! strangely the implementation does not have a normal blending mode by default

in case anyone is wondering.. THREE.NormalBlending is a more intuitive approach.

outlinePass.MATERIAL_NAME.blending = THREE.NormalBlending;
