### ISSUE TITLE
SPE broken in 110dev

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#17677]
https://github.com/squarefeet/ShaderParticleEngine 
It worked just fine in r109.
Now it doesn't work anymore and the console is bloated with messages like:

THREE.BufferAttribute: .dynamic has been deprecated. Use .usage instead.
Error: WebGL warning: bufferData: usage: invalid enum value NONE
Error: WebGL warning: drawArrays: Vertex fetch requires 750, but attribs only supply 0.
Error: WebGL warning: bufferSubData: Offset+size passes the end of the buffer.

@Mugen87 
Michael, the backwards compatibility ?

**Comment by Mugen87** [comment]
Good catch! It seems I've only tested `.setDynamic()` but missed to verify `.dynamic`. Since SPE uses the latter one, the wrong value was set in `three.legacy.js`. 

Can you please try it again with the latest `dev` build?

**Comment by RemusMar** [comment]
> Can you please try it again with the latest dev build (see 28b5d10)?

Well done!

**Comment by Mugen87** [comment]
Thanks for reporting!

**Comment by mrdoob** [comment]
Indeed! Thanks for testing`dev` 🙏
