### ISSUE TITLE
Editor not working properly

### ISSUE THREAD

**Issue by joesnows** [mrdoob/three.js#17696]
Hello, new to the comunity, my first report, please bare with me.

I am an artist who uses threeJS editor as a means to configure my 3D assets, to export to some clients i work with.
Recently, with the release of r109, the shader configurations in the  "Material" tab lost a lot of properties like copy/paste , and is unnable to select or configure everything bellow the new field "sheen". 
This happens in all my devices, and also in several web-browsers.

Hope this report helps, it caused me and the corporations i work a lot of trouble. Thank you, have a nice day.

**Comment by Mugen87** [comment]
> and is unnable to select or configure everything bellow the new field "sheen".

I can actually reproduce.

@sdinesh86 Can you please have a look at this?

**Comment by mrdoob** [comment]
Yeah, I bumped into this too but I didn't get time to debug it. I just figured it out.

Seems like #17443 is the PR that broke it. I'll comment the code for now.

**Comment by mrdoob** [comment]
I updated `gh-pages` so https://threejs.org/editor/ should be fixed in some minutes. Make sure you do a hard refresh.

Sorry for the inconvenience and thanks for letting us know!

**Comment by mrdoob** [comment]
> Recently, with the release of r109, the shader configurations in the "Material" tab lost a lot of properties like copy/paste

That change was intentional though. The UX is not the best right now but if you go to the `PROJECT` panel you'll see all the materials in your scene and you should be able to apply each to different objects. It should provide the same functionality that copy/paste did.

**Comment by sdinesh86** [comment]
@Mugen87 @mrdoob Sorry for the delayed reponse, was away for some day's
I will take look at it and will change it ASAP

**Comment by mrdoob** [comment]
@sdinesh86 don't worry, I'm taking care of it already.
