### ISSUE TITLE
InstancedMesh's setMatrixAt fails when another mesh in the scene has the same material

### ISSUE THREAD

**Issue by GuilhermeRossato** [mrdoob/three.js#17701]
##### Description of the problem

I'm having a problem where the InstancedMesh method `setMatrixAt` seems to fail (the matrix positions doesn't change visually) whenever I add another object with the same material object (not a clone) in the scene. No log/warning/errors are emitted.

The following briefly illustrates:

```js
    var geometry = new THREE.BoxBufferGeometry();
    var material = new THREE.MeshStandardMaterial( { roughness: 0, envMap: texture });
    var mesh1 = new THREE.Mesh( geometry, material );
    mesh1.position.set(0, 1, 0);
    scene.add( mesh1 ); // removing this line makes the instanced mesh work as intended
    mesh = new THREE.InstancedMesh( geometry, material, 9 ); // same material usage
    scene.add( mesh ); // This works and I can see both meshes in the scene.
    
    var dummy = new THREE.Object3D();
    dummy.position.set( 1, 5, 1 );
    dummy.updateMatrix();
    mesh.setMatrixAt( 0, dummy.matrix ); // Nope, doesn't work, it just stays where it's at.
    mesh.setMatrixAt( 1, dummy.matrix ); // Rotation seems to be applied, but position doesn't.
    // It looks like every instance is at the same place, but I don't know.
```

Note that if I use material.clone() at the instanced mesh declaration, the problem also goes away / is fixed, but now I have two materials, and I intend to have one for performance reasons.

A live example is available here:

* [jsfiddle](https://jsfiddle.net/ghmrdk4z/4/) (The problem is that you should see multiple boxes, but only 1 or 2 are visible, remove line 41 to fix)

##### Three.js version

- [x] Dev
- [x] r109
- [ ] r108

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [X] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

(Not applicable, as far as I know)

**Comment by GuilhermeRossato** [comment]
I have not checked whether other OS'es or Browsers have this issue, I just confirmed it on Windows, both Chrome and Edge.

**Comment by mrdoob** [comment]
Yeah, known issue. Haven't made that work yet.

**Comment by s-ol** [comment]
Not sure if that is a related issue or intended behaviour, but I also have problems re-usinng the `BufferGeometry` passed into `InstancedMesh`. For example when using one geometry for two `InstancedMesh`es, neither renders, and there is also no warnings or errors.

**Comment by mrdoob** [comment]
@s-ol Interesting. Do you mind putting together a jsfiddle?

**Comment by s-ol** [comment]
@mrdoob sure, here you go: http://jsfiddle.net/x7Lzvqte/

you can toggle the red & green batches on and off individually with the bools at the top.
When either one is on it works as expected (red on the left or green on the right), but when both are on only the green one renders, and it renders on the left side.

**Comment by Mugen87** [comment]
I've debugged the issue a bit and found out that the bug refers to the same root cause mentioned here: https://github.com/mrdoob/three.js/issues/17959#issuecomment-562846047. 

The renderer needs the ability to manage multiple shader programs per material. Currently there is only a 1:1 relationship. Multiple materials can share a single shader program. But not the other way around. 

This feature is actually necessary since in the example the renderer assumes it can reuse the same shader for the instanced mesh.

**Comment by donmccurdy** [comment]
> The renderer needs the ability to manage multiple shader programs per material. Currently there is always a 1:1 relationship...

Or alternatively, a property on the material that enables instancing, similar to the relationship between .skinning=true and THREE.SkinnedMesh. I’m not sure which solution is better but would prefer consistency. 🤔

**Comment by donmccurdy** [comment]
> but now I have two materials, and I intend to have one for performance reasons.

Note that in any outcome here, you really do need two shader programs for this situation. You might find that using an InstancedMesh with count=1 for the second object avoids this, not sure if there should be any side effects of that...

**Comment by mracette** [comment]
I just got bit by this as well. A note in the docs while the fix is underway would be great.
https://threejs.org/docs/#api/en/objects/InstancedMesh

**Comment by Mugen87** [comment]
@mracette Good point. Let me update the docs.
