### ISSUE TITLE
GLTFLoader: Could we re-think about how we deal depth buffer for `BLEND` materials?

### ISSUE THREAD

**Issue by FMS-Cat** [mrdoob/three.js#17706]
##### Description of the problem

Already discussed a bit about it on #13889

Currently, we are letting `depthWrite: true` for every material that is being loaded from GLTFLoader, even when the material is `alphaTest: BLEND` .
And glTF spec does not specify how we must set our depth write, even in non-normative sections, since the use of glTF is not restricted to the traditional realtime rasterizer.
It just says that we should try to make it look proper in as many situations as possible.

See: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0/#alpha-coverage

I think we should follow other "majority" implementations for this situation. (uhhh is this good idea?)
Note that it's pretty easy to change the behavior, just adding a line to GLTFLoader would work I think.

- BabylonJS uses depth write only if alpha blending is disabled.
  https://github.com/BabylonJS/Babylon.js/blob/26d9fe4991d9e4d749618463548f853e837ff2ba/src/Engines/engine.ts#L837
- I depleted my energy to research other engines......

##### Three.js version

- [x] Dev
- [x] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by FMS-Cat** [comment]
Yes that is pretty expected and reasonable answer, thank you @donmccurdy -san!
I think I need more examples of actual model and implementations

**Comment by Kagetsuki** [comment]
We've essentially run into this issue and I think we may have a very specific example. We have a semi transparent material under a mostly transparent material and it displays fairly well in babylon, but in three.js we have two scenarios:
1. Default of depthWrite: true does not calculate the transparency of the material behind the other transparent material and is either culling it or giving it a very high alpha or something (left is three, right is babylon):
![defaults comparison](https://user-images.githubusercontent.com/864634/70498673-7d373c80-1b5a-11ea-98bc-a6a6235d6e69.png)
2. Setting depthWrite to false seems to completely ruin materials:
![depthWrite disabled](https://user-images.githubusercontent.com/864634/70498827-02225600-1b5b-11ea-8242-dedfe5b52e11.png)

Here's the glb of the model we're testing (we can provide the original Blend file if anyone wants it).
[HumanEye-V2(concept).zip](https://github.com/mrdoob/three.js/files/3943221/HumanEye-V2.concept.zip)

For us it would be preferable if the display was like babylon by default - as the babylon version is very close to what we're looking for and it seems to have a high[er] compatibility with the Blender (2.81) glTF exporter. For others this may of course not be the case, but I feel like with so much effort being put into the Blender exporter by members of the Khronos Group(♥) it may be a better reference.?

If there's anything we can do to help with this issue please let me know.

**Comment by donmccurdy** [comment]
@Kagetsuki the problem visible in your third image comes from setting `depthWrite=false` on _all_ materials. If you set the option only on the transparent materials, you'll get a reasonable result.

![Screen Shot 2019-12-22 at 8 53 05 PM](https://user-images.githubusercontent.com/1848368/71336705-25ef7f80-24fd-11ea-81df-d598a4f3381c.png)

@FMS-Cat Okay, I think I agree at this point. Let's set `depthWrite=false` for transparent materials in GLTFLoader. Opened https://github.com/mrdoob/three.js/pull/18235.

**Comment by Kagetsuki** [comment]
@donmccurdy That is correct. Thanks for the clarification and thanks for your continued work!

**Comment by donmccurdy** [comment]
Fixed: https://github.com/mrdoob/three.js/pull/18235.

**Comment by donmccurdy** [comment]
Thanks for the examples and discussion, @FMS-Cat and @Kagetsuki!

**Comment by Kagetsuki** [comment]
Thank *you* @donmccurdy .

**Comment by FMS-Cat** [comment]
Ohhhh I didn't notice to this! Thank you ❤️

**Comment by greggman** [comment]
FTW, this change broke stuff. So while it may have worked for the example above it is not clear it's the correct thing to do?

I didn't search that hard but some scenes that broke (testing [here](https://gltf-viewer.donmccurdy.com/))

https://sketchfab.com/models/a1d315908e9f45e5a3bc618bdfd2e7ee

https://sketchfab.com/3d-models/izzy-animated-female-character-free-download-8476e3679aa442c3ad811727705524ac

https://sketchfab.com/3d-models/fantasy-sea-keep-daa54937ce844ed390101fa9318843ba ?

I don't know how many others might break. It's really hard to find scenes that I have permission to download that have any kind of transparency at all to test with.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Greggman <notifications@github.com>
发送时间：2020-05-18 17:35
主题：Re: [mrdoob/three.js] GLTFLoader: Could we re-think about how we deal depth buffer for `BLEND` materials? (#17706)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

FTW, this change broke stuff. So while it may have worked for the example above it is not clear it's the correct thing to do?
I didn't search that hard but some scenes that broke (testing here)
https://sketchfab.com/models/a1d315908e9f45e5a3bc618bdfd2e7ee
https://sketchfab.com/3d-models/izzy-animated-female-character-free-download-8476e3679aa442c3ad811727705524ac
https://sketchfab.com/3d-models/fantasy-sea-keep-daa54937ce844ed390101fa9318843ba ?
I don't know how many others might break. It's really hard to find scenes that I have permission to download that have any kind of transparency at all to test with.

**Comment by mrdoob** [comment]
@greggman Any chance you can share screenshots?

**Comment by donmccurdy** [comment]
Checking the first three examples, they are all cases where the material has enabled transparency for objects with 100% opacity. Unfortunately that seems to be pretty common on Sketchfab; I'd be curious if we can ask them to fix that in their generated glTF models.

**Comment by greggman** [comment]
Maybe you have different experience. In games I've rarely worked on a project that used depthWrite = false except for particles effects

![wjwiGLP8Uo](https://user-images.githubusercontent.com/234804/82263627-4af9f880-999e-11ea-8b8c-fdf474709257.gif)
![KttvBSkioM](https://user-images.githubusercontent.com/234804/82263637-4e8d7f80-999e-11ea-886d-f9aad8471db0.gif)
![8BtBhCpOLr](https://user-images.githubusercontent.com/234804/82263651-53523380-999e-11ea-8059-2668d1e97b47.gif)
![yTiAxZYKVd](https://user-images.githubusercontent.com/234804/82263659-55b48d80-999e-11ea-8595-a7893c3bdefc.gif)
![qU9P1XwPXH](https://user-images.githubusercontent.com/234804/82263662-577e5100-999e-11ea-919f-789a3af6ce5e.gif)
![WaJe6EwygL](https://user-images.githubusercontent.com/234804/82263665-59e0ab00-999e-11ea-98b6-16afe3dc7eb2.gif)

**Comment by donmccurdy** [comment]
I think all of these models would be better served by `transparent = false` than `transparent = true`. Artists can't just enable `.transparent=true` on an entire opaque model, that will cause other kinds of problems, including overdraw at least.

The glTF format gives three alpha options:

a) alphaMode=BLEND: disable alpha test, enable alpha blend
b) alphaMode=MASK: enable alpha test, disable alpha blend
c) alphaMode=OPAQUE: disable alpha test, disable alpha blend

glTF does not specify when depthWrite should be enabled/disabled, but (with this change) we apply it only to the BLEND case by default. If these models were using the mask mode, which I think they should be, then depthWrite would not be disabled.

***

All that said, yes, I realize that transparency sometimes requires depthWrite=true, and in other cases requires depthWrite=false. Whichever default we choose, some things will be broken. https://github.com/mrdoob/three.js/pull/18235 lists other cases that were _fixed_ by the change. I think those cases are more compelling: some of those models were designed as well as they could be, and were still broken, whereas these ones generated by Sketchfab are unfortunately not using particularly good material settings.

**Comment by greggman** [comment]
I realize things will break either way. In my experience I expect the new way to break things far more often than visa-versa just given that I've all the games I've worked and having never turned off depth testing except for particles. But, I guess we'd have to find more scenes find out if the there is an advantage to defaulting to one way or the other.  It's possible it's 50/50. It's also possible it's 90/10 one way or the other.

**Comment by donmccurdy** [comment]
For comparison (details in https://github.com/mrdoob/three.js/pull/18235) this behavior appears to be recommended by Unity's docs, and enabled by default in Unreal Engine and BabylonJS. Probably there's more of a grey area for models that need both alpha test and alpha blend, but these models don't enable alpha test. 😕
