### ISSUE TITLE
GLTFExport, broken binary export

### ISSUE THREAD

**Issue by Bug-Reaper** [mrdoob/three.js#17704]
No errors but using GLTFExport with binary set to true only produces a 2 byte file.
Setting binary to false, and trying the same export gives a valid 3.4mb .gltf file.

Possibly related to the fact I'm exporting un-merged morphTarget animations.

[Live Demo Here](https://threejs-demos.s3.us-east-2.amazonaws.com/GLTF2/bug.html)

[Code Here](https://github.com/mrdoob/three.js/files/3710683/gltfBinBug.zip)

**Comment by Mugen87** [comment]
There is an error in your code. When you perform a `glb` export, the `glTF` variable in the parse callback is of type `ArrayBuffer`. So you can parse it to JSON. If I use the exact same code from the official [example](https://threejs.org/examples/misc_exporter_gltf), I can properly export your `glb` and load it with  `GLTFLoader`:

```js
function exportBinary() {
    if (animation) {
        var exporter = new THREE.GLTFExporter();
        exporter.parse(group.children[0], function(gltf) {
            saveArrayBuffer( gltf, 'scene.glb' );
        }, {
            onlyVisible: false,
            animations: [animation],
            binary: true
        });
    }

}

function saveArrayBuffer( buffer, filename ) {

	save( new Blob( [ buffer ], { type: 'application/octet-stream' } ), filename );

}

var link = document.createElement( 'a' );
link.style.display = 'none';
document.body.appendChild( link ); // Firefox workaround, see #6594

function save( blob, filename ) {

	link.href = URL.createObjectURL( blob );
	link.download = filename;
	link.click();

	// URL.revokeObjectURL( url ); breaks Firefox...

}
```

**Comment by Bug-Reaper** [comment]
Ohhh fucking duh. Thanks @Mugen87, my bad.
