### ISSUE TITLE
Device orientation controls example no longer works on iOS13 Safari

### ISSUE THREAD

**Issue by sirxemic** [mrdoob/three.js#17713]
##### Description of the problem

Open https://threejs.org/examples/?q=orientation#misc_controls_deviceorientation in Safari on an iPhone with iOS 13 installed.

In the latest versions of iOS (probably also iPadOS) the only way to make orientation controls work is to explicitly call `DeviceOrientationEvent.requestPermission()` *and* do this on a user action like tapping a button.

This is similar to #16266, but it looks like in the latest version you can't fix it anymore by simply using HTTPS and toggling a Safari setting. Using `requestPermission` seems to be the only way to fix it now.

To solve this for the examples, I'm thinking of something like the following (with improved phrasing):
- Show a full-screen button (with a dark, transparent background) that says something like "In order to make this example to work, we need your permission to access your device's orientation. Tap the screen to try out this example".  This should only be shown based on whether `DeviceOrientationEvent.requestPermission` exists.
- When the user has denied orientation controls, change the message to something like "You've denied access to your device's orientation. If you'd like to permit this access after all, please restart your browser."
- Hide the button when an orientation event has fired. This is necessary because once you've permitted (or denied) controls, it won't ask again (even in new tabs) until you restart safari.

##### Three.js version

- [ ] Dev
- [x] r109

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

**Comment by Mugen87** [comment]
There is already a similar screen for audio examples (see https://threejs.org/examples/?q=audio#webaudio_visualizer) since a user interaction is required for proper Web Audio usage.

We could use the same HTML/CSS for `misc_controls_deviceorientation`. Just adapt the JS according to this [guide](https://medium.com/flawless-app-stories/how-to-request-device-motion-and-orientation-permission-in-ios-13-74fc9d6cd140).

**Comment by HypnosNova** [comment]
I solve this problem in this PR: https://github.com/mrdoob/three.js/pull/17823
