### ISSUE TITLE
InstancedBufferGeometry disables fragDepth

### ISSUE THREAD

**Issue by EliasHasle** [mrdoob/three.js#17715]
Context: https://github.com/mrdoob/three.js/issues/17618#issuecomment-536753086 and https://discourse.threejs.org/t/coding-jam-pixel-perfect-spheres-without-high-res-geometry/10154

Compare the version made with repeating quads: https://eliashasle.github.io/perfect_spheres.html
to the version made with instancing of a single quad: https://eliashasle.github.io/perfect_spheres_instanced.html

What I observe is much more flickering on the instanced version while moving the camera. The mode of the flickering is consistent with loss of fragment depth, in that spheres are now either entirely behind or entirely in front of one another.

I googled around, and searched here too, but found no indications that instanced arrays are incompatible with fragment depth. I would be happy if you could shed light on the issue.

##### Three.js version

- [?] Dev
- [X] r109
- [?] ...

##### Browser

- [?] All of them
- [X] Chrome
- [X] Firefox
- [X] Edge
- [ ] Internet Explorer

##### OS

- [?] All of them
- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Unknown.

**Comment by EliasHasle** [comment]
Now I am not sure. I just checked again (after a good night's sleep), and observed some examples of the same form of flickering on the non-instanced version, and not horribly much on the instanced version. Closing for now.

**Comment by mrdoob** [comment]
Nice experiment btw!
