### ISSUE TITLE
Change InstancedMesh api signature to count, geom, mat

### ISSUE THREAD

**Issue by drcmda** [mrdoob/three.js#17714]
##### Description of the problem

The current signature is unfortunate, since geom and mat have defaults (which means they should be last), but count has to be supplied (it should therefore be first). This causes us some headaches when we need to create an instancedmesh declaratively, like so:

```jsx
<instancedMesh args={[null, null, count]}>
  <sphereBufferGeometry attach="geometry />
  <meshBasicMaterial attach="material" />
```

declarative use or not, this is also weird in the imperative way:

```jsx
const m = new THREE.InstancedMesh(null, null, count)
m.geometry = ...
m.material = ...
```

the proposal would be:

```jsx
new THREE.InstancedMesh(count)
new THREE.InstancedMesh(count, geom)
new THREE.InstancedMesh(count, geom, mat)
```

which i think is natural, in js and ts alike

    (count: number, geom?: THREE.Geometry, mat?: THREE.Material)

examples:

https://codesandbox.io/s/three-fiber-useloader-pjcc1

https://codesandbox.io/s/react-three-fiber-gestures-xj31x?from-embed

The prototype is still very new and hasn't even been documented. Can we fix this before it's too late? @mrdoob

**Comment by mrdoob** [comment]
Another solution would be to set `1` as default for `count` I guess? 😁

**Comment by drcmda** [comment]
would be a great solution, if count can later be set by a getter this would even be optimal.

**Comment by mrdoob** [comment]
Hmm, that's react-three-fiber style influencing three.js api... 😁

I'm not sure what's the right solution here. We can't easily resize `count` without creating a new `TypeArray` when increasing the size.

**Comment by drcmda** [comment]
i think defaults coming last and required vars first is a code standard in all languages. in typescript for instance it wouldn't be permissable:

<img width="1066" alt="Screenshot 2019-10-11 at 23 29 11" src="https://user-images.githubusercontent.com/2223602/66686213-f9a6bf80-ec7e-11e9-8f18-214958554739.png">

**Comment by mrdoob** [comment]
I was joking. Lets focus on the `count` issue.

**Comment by donmccurdy** [comment]
Alternatively, make Geometry and Material required? 😇

**Comment by mrdoob** [comment]
Haha!

Here's my understanding of the issue:

@drcmda is mixing two issues in one (the typescript one is related but unrelated).

The core issue is that he wants to use the API like this:

```js
const mesh = new THREE.InstancedMesh();
mesh.geometry = geometry1;
mesh.material = material1;
mesh.count = 50;
// user changes parameters in react-three-fiber layer
mesh.geometry = geometry2;
mesh.material = material2;
mesh.count = 500;
```

Handling these property changes requires logic that should sit somewhere, either in react-three-fiber or in three.

In a way, the issue was that I made `count` public.

I don't know...

**Comment by drcmda** [comment]
@donmccurdy that would be worse for us, b/c then we can't declare instance meshes any longer, they'll have to be imperative. i know our case isn't that pressing for this lib, but even just fixing it for api clarity is a plus - the other objects all work required first, optional last, and every other mesh can receive geom/mat later, which is a very useful feature. 😊

**Comment by donmccurdy** [comment]
I see. 👍

I'd disagree that required, immutable constructor arguments make a declarative API impossible — this is supported in A-Frame VR by re-creating an underlying object when needed, for example — but I understand this might have unwanted side effects on your API.

Making `count` the first argument, or making it optional, seems OK to me. But I do think an operation like `mesh.count++` should not hide its (negative) performance implications.

**Comment by mrdoob** [comment]
I agree.

@drcmda 

Again, the issue here is `count` and not `geometry` or `material`.

I'm happy to default `count` to `1` in the constructor if it helps but, unfortunately, I think you will have to add extra code in your layer. You'll have to create a new `InstancedMesh` every time the user changes the `count` property (at least when they increase it). Don't forget to dispose the previous `InstancedMesh` (not that I have coded that yet 😇).

**Comment by drcmda** [comment]
well i didnt say it makes declarative use impossible, it just looks weird and causes people headaches b/c they need to browse documents. also for api consistency this is not optimal b/c the other three prototypes do not behave like this. from an api standpoint alone and typescript of course this should be re-considered. you're about to make a prototype official that has two optionals followed by a required arg - this will never go away after you set it in stone by documenting it in 110.

**Comment by RemusMar** [comment]
> But I do think an operation like `mesh.count++` should not hide its (negative) performance implications.

+1

**Comment by mrdoob** [comment]
> count = 1 wouldn't change much, it's the `args={[null, null, count])` that's a little unfortunate.

I guess I'm going to have to learn React...

Is not possible to do something like this?

```jsx
<instancedMesh args={[
    <sphereBufferGeometry>,
    <meshBasicMaterial>,
    count
]}>
```

**Comment by WestLangley** [comment]
Would
```js
mesh = new InstancedMesh( geometry, material, options );
```
be acceptable as an API? `options` is an object.

Or
```js
mesh = new InstancedMesh( geometry, material ).setCount( n );
```
I much prefer the first patern, but I believe @mrdoob prefers the second...

If not, then my preference is to retain the current API for three.js-consistency.
```js
mesh = new InstancedMesh( geometry, material, count );
```

**Comment by donmccurdy** [comment]
@drcmda for context, many threejs objects (Mesh, Line, LineLoop, LineSegments, Points, SkinnedMesh) share `geometry, material` as the first two arguments. I think we're hoping for a solution that maintains consistency with that.

**Comment by drcmda** [comment]
understood, it's no big deal. i think the count prop was kinda special, b/c these other objects can mostly be constructed without passing any args, but instanced mesh can't.

> Is not possible to do something like this?

yes, but that would need some layering. but it's not that bad: null, null, count is a small price to pay. :-)

@WestLangley i would generally prefer constructor args over imperative apis, they're shutting out the declarative stuff for real, it can't be properly mapped.

**Comment by mrdoob** [comment]
>> Is not possible to do something like this?
>
> yes, but you could just as well pass the classes. but it's not that bad: null, null, count is a small price to pay. :-)

Well, then that's `react-three-fiber` "opinionated" design. Probably influenced by the React/JSX ecosystem? But the Three.js API is meant to use by passing stuff in the constructors. The fact that you can change `geometry` and `material` after the fact is just a nice-to-have feature.

Regarding `null, null, count`... `Mesh` currently allows `undefined`, `Geometry` or `BufferGeometry`. 

https://github.com/mrdoob/three.js/blob/dev/src/objects/Mesh.js#L49-L50

I don't know what happens when `WebGLRenderer` tries to render a `null`. In `react-three-fiber` API that could happen if the user forgot the geometry node:

```jsx
<instancedMesh count={[null, null, 10]}>
  <meshBasicMaterial attach="material" />
```

**Comment by Mugen87** [comment]
Closing. It seems the consensus is to not change the API in the suggested way.
