### ISSUE TITLE
THREE.MeshBasicMaterial: 'stencilWrite' is not a property of this material.

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#17723]
And yet: https://github.com/mrdoob/three.js/blob/master/examples/webgl_clipping_stencil.html#L57-L61
```
				var baseMat = new THREE.MeshBasicMaterial();
				...
				baseMat.stencilWrite = true;
```
what gives?

**Comment by Mugen87** [comment]
All materials have this property. Can you please demonstrate how you get this warning message ?

**Comment by mrdoob** [comment]
@makc you should know at this point that we appreciate when bug reports provide enough information for validation 😔

**Comment by makc** [comment]
@Mugen87 are there really many ways to end up with this warning? You guys know exactly where it comes from, but just for the sake of it, here is the screenshot
![Screen Shot 2019-10-14 at 17 03 51 ](https://user-images.githubusercontent.com/242577/66761703-ce051e80-eea4-11e9-92e7-24b3ad12abfb.png)

**Comment by Mugen87** [comment]
I can't reproduce this: https://jsfiddle.net/cLnj4e3x/

**Comment by Mugen87** [comment]
Are you aware that #15611 landed in `R107`? You are using `R105`.

**Comment by mrdoob** [comment]
@makc please, always provide the version of three.js you're using when reporting bugs... 😔
