### ISSUE TITLE
How to use three.js-example in Vue? 

### ISSUE THREAD

**Issue by CharlesJhonson** [mrdoob/three.js#17726]
The examples of Gyroscop and Stereo works when I use ' three/examples/js/controls/DeviceOrientationControls.js' and 'three/examples/js/effects/StereoEffect.js' in the single html file. But it doesn't work when I use them(StereoEffect.js, DeviceOrientationControls.js) in vue with wepack tool. Would you please guide, thanks very much.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org) for help requests.
