### ISSUE TITLE
Issue with clampWhenFinished

### ISSUE THREAD

**Issue by sinokgr** [mrdoob/three.js#17730]
Hi All,

I think I found a small bug with the `clampWhenFinished` property in the `AnimationAction`s. I started with [this](https://threejs.org/examples/#webgl_loader_fbx) example and I loaded a [new FBX](https://github.com/mrdoob/three.js/files/3724220/teapot.zip) with two clips.

I then updated the properties for both clips

    openAction = mixer.clipAction( object.animations[ 0 ] );
    openAction.clampWhenFinished = true;
    openAction.setLoop(THREE.LoopOnce, 1);

    closeAction = mixer.clipAction( object.animations[ 1 ] );
    closeAction.clampWhenFinished = true;
    closeAction.setLoop(THREE.LoopOnce, 1);

and finally I added two buttons to control the animations (here's the final code).
[webgl_loader_fbx.zip](https://github.com/mrdoob/three.js/files/3724463/webgl_loader_fbx.zip)

The issue:
`clampWhenFinished` disabled (working as expected)
![working](https://user-images.githubusercontent.com/22396951/66752741-db1d1000-ee9a-11e9-8499-5b0c01f0d696.gif)

`clampWhenFinished` enabled (not working as expected)
![notWorking](https://user-images.githubusercontent.com/22396951/66752749-dfe1c400-ee9a-11e9-8437-c3420a5b2096.gif)

So, for some reason, after I click the second animation, it only goes halfway.

- [ ] Dev
- [x] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
When you set `clampWhenFinished` to `true`, the animation is just paused and has still an (weighted) influence on the transformation. To fix your code, just ensure to call `.stop()` for the other action in both click handlers. Example:
```js
div.addEventListener("click", function(e){
    openAction.reset();
    openAction.play();
    closeAction.stop();
});
```
Please use the [forum](https://discourse.threejs.org/) if you need more help.

**Comment by sinokgr** [comment]
sorry for that. I thought that this was a bug.
