### ISSUE TITLE
Arguments are passed to Ray by reference in constructor but by value in .set

### ISSUE THREAD

**Issue by Neptilo** [mrdoob/three.js#17738]
##### Description of the problem

The `origin` and `direction` vector arguments are inconsistently passed by reference in `THREE.Ray`'s constructor and passed by value in its `.set` method.
This has the effect that the vectors initially passed in the constructor are unexpectedly modified when calling `.set`.

**Example:**
```
let o0 = new THREE.Vector3(1, 2, 3);
let d0 = new THREE.Vector3(4, 5, 6);
let ray = new THREE.Ray(o0, d0);
let o1 = new THREE.Vector3(3, 2, 1);
let d1 = new THREE.Vector3(6, 5, 4);
ray.set(o1, d1);
```
`o0` and `d0` now contain the values of `o1` and `d1`.

##### Three.js version

- [x] Dev
- [x] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Well, this is the intended design of all `three.js` classes. Objects you pass into the constructor are assigned to the respective properties. `.set()` methods retain the references and just copy over the values. I can't imagine this convention is something the project is going to change now.

**Comment by Neptilo** [comment]
Thanks for the info. I guess I never came across such objects. Can you give some examples?
This behavior seemed very unintuitive to me and I was certain it was a bug. If it is a convention, then I think it should at least be mentioned somewhere in the doc.
For now, I can't find another class behaving this way, but I did find an example behaving as I would expect: `Box3`. Shouldn't that class also follow this convention then?

**Comment by Mugen87** [comment]
> Can you give some examples?

You can check any other math class which has object properties. For example `Box3`:

https://github.com/mrdoob/three.js/blob/697f63c572a081e1d7dc119a6d6e8d9da8b57c4c/src/math/Box3.js#L37-L55

**Comment by Mugen87** [comment]
> If it is a convention, then I think it should at least be mentioned somewhere in the doc.

I wondering where a good place could be. One way is to update the descriptions of all relevant `set()` methods...

**Comment by Neptilo** [comment]
Thanks for the example.
I agree that this would be the right place, because if it is in a general file, one will very likely miss it.

**Comment by Mugen87** [comment]
It seems there are only ten places where it's necessary to add a note. Would it be sufficient to add the following sentence to the description of all respective methods?

`Please note that this method only copies the values from the given objects.`

**Comment by WestLangley** [comment]
This is not necessary.

**Comment by Neptilo** [comment]
@Mugen87 Yes I believe this would be sufficient.
@WestLangley Why not?

**Comment by Mugen87** [comment]
IMO, such a clarification in the documentation does not hurt. 

@Neptilo Feel free to enhance the documentation with my suggested text or something similar.

**Comment by Neptilo** [comment]
Thanks. I will do when I find some time

**Comment by Neptilo** [comment]
I created [this pull-request](https://github.com/mrdoob/three.js/pull/17954).
