### ISSUE TITLE
Modifier: SimplifyModifier.js with larger meshes

### ISSUE THREAD

**Issue by kpetrow** [mrdoob/three.js#17734]
I have a ~10 Million faces surface i need to simplify.  I have triangle souped it and pass it to the 
SimplifyModifier routine and always get a crash.  There are a couple points in the code that say can be optimized, but i am not exactly sure how to do that. Could anyone provide any advice on how to get this too work without crashing?  Is there a geometry simplifier that doesn't convert to geometry?   

##### Three.js version

- [ ] Dev
- [x ] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Geometry modifiers perform in general topological operations on data. Using a format geometry representation like `BufferGeometry` which is optimized for rendering is usually no good approach. Using `Geometry` makes the code more manageable but also more ressource-intensive. 

You might get better results with a different type of implementation (e.g. base on half-edge data structure) but I assume it won't be easy to implement if you want to support processing 10 Mio. faces.

**Comment by kpetrow** [comment]
@Mugen87 So im on my own?  Was really hoping for a library.  Thanks for the advice.  

We have a half edge lib we use for draping lines onto surfaces.  Any advice on how to implement a simplification algo?

**Comment by Mugen87** [comment]
Sorry, I don't know something like that out of the box. `SimplifyModifier` has a basic implementation but more advanced algorithms are also more complex.

Because of #14058, it might be worth to revisit `SimplifyModifier`. But to be honest, this task has not a very high priority since many devs perform such operation during the design phase e.g in Blender.
