### ISSUE TITLE
Revisit sessionstart/end events

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#17737]
##### Description of the problem

We added `sessionstart/end` events in #16365. I read WebXR API again and I'm feeling like revisiting them. Because

1. `session.renderState` (active render state) is updated in the first animation frame since `session.updateRenderState()` is called in the newest WebXR API spec (thanks to https://github.com/mrdoob/three.js/pull/15840#discussion_r333203039). One of the purposes of `sessionstart/end` events is an alternative of WebVR API `vrdisplaypresentchange` then the start event should be fired when it's ready to render in immersive mode (=active render state is ready) but currently `sessionstart` is fired before calling the first `session.requestAnimationFrame()` meaning active render state is not ready yet.

2. The name `sessionstart` might be bit confusing. From the name user may think it's fired when `navigator.xr.requestSession()` promise is resolved but currently it's fired when `session.requestReferenceSpace()` promise is resolved.

So I'd like to suggest the both

1. Firing the start event in the first animation frame. VR PostProcessing PR (#15840) needs it because `EffectComposer` wants to get the drawing buffer size of immersive mode when it's updated
2. Rename the events to `immersivestart/end` (or something better names)

What do you think @mrdoob?

##### Three.js version

- [x] Dev
- [ ] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
I think this sounds good to me. Feel free to submit a PR.

**Comment by takahirox** [comment]
OK, I will maybe next week.
