### ISSUE TITLE
CubeTexture.needsUpdate

### ISSUE THREAD

**Issue by EliasHasle** [mrdoob/three.js#17731]
Any chance of a change to `needsUpdate=true` when data are available at construction? (Consider the case with `DataTexture` in #17491?) I just spent a lot of time trying to make a custom `CubeTexture` work. Part of the problem is that all examples only use `CubeTextureLoader` (which internally sets `needsUpdate` after loading).

**Comment by EliasHasle** [comment]
Hm, I understand that `Texture` behaves the same way, and that `CanvasTexture` was created as a sort of user-friendly workaround. Is there really no better solution, such as intercepting the setting of texture.image with a setter function that considers the type and loading status of the texture before deciding whether to set `needsUpdate`?

**Comment by Mugen87** [comment]
>  Is there really no better solution, such as intercepting the setting of texture.image with a setter function that considers the type and loading status of the texture before deciding whether to set needsUpdate?

TBH, I find such an approach hard to understand. The current policy of when `Texture.needsUpdate` is set to `true` is some sort of default. And it works well for the standard usage of `Texture` and `CubeTexture` (by loading them via the respective loaders). There might be edge cases where you need a different behavior but that needs to be handled on application level.

Yes, it does make sense to set `Texture.needsUpdate` to `true` for `DataTexture` and `CanvasTexture`. But let's highlight one more time that both type of textures are normally constructed in a different way (by applying the texture data when constructing the object itself). So I think the current status of when `needsUpdate` is set is consistent and no cause for change.
