### ISSUE TITLE
Not sound in a mp4 into webGL three.js

### ISSUE THREAD

**Issue by castana1962** [mrdoob/three.js#17732]
Hi 
Sorry for my ignorance but I am starting with the tree,js projects.
First I added a Video loop in mp4 ( without sound) in my three.js project and it worked fine but after that I added one sound to this mp4 file and now I can see the Video Loop but not can hear its sound, for it, Coul anybody help me to fix it? Thanks for your time
Best Regards

##### Description of the problem

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/yn8azeg1/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/kLwhx875/) (dev branch)

##### Three.js version

- [ ] Dev
- [ ] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org) for help requests.

Notice that automatic video playback with sounds requires a user interaction. More information right here: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by castana1962** [comment]
Hi Mugen87
I did not know about this forum.
Sorry for my mistake
Thanks for your time
