### ISSUE TITLE
Since Chrome v77 video rendering is very slow

### ISSUE THREAD

**Issue by agentsmis** [mrdoob/three.js#17744]
##### Description of the problem
Since the update of Chrome v77 the video rendering is very slow and stutters.
It rise the warning: requestAnimationFrame' handler took <N>ms
I use ThreeJS v101. But in version 109 is the same error.

Can I controll the fps?

What can I do? Thank you!

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/17619
