### ISSUE TITLE
TS: Missing ACESFilmicToneMapping declaration.

### ISSUE THREAD

**Issue by aline-coasta** [mrdoob/three.js#17756]
https://github.com/mrdoob/three.js/blob/35eaaa18bd5fae9033bdac30a857a281122c9536/src/constants.d.ts#L117

I think ACESFilmicToneMapping is omitted in constants.d.ts file.

**Comment by Mugen87** [comment]
Good catch! Do you want to add it?

**Comment by Mugen87** [comment]
Never mind. Solved via #17781
