### ISSUE TITLE
Multiple Views Raycasting TransformControls

### ISSUE THREAD

**Issue by kavikode** [mrdoob/three.js#17750]
I am trying to show multiple views on the same renderer
like https://github.com/mrdoob/three.js/blob/master/examples/webgl_multiple_views.html
in each view I am trying to perform object picking/raycasting
once an object is picked in the specific view, I'd like to attach the THREE.TransformControls. It only works in the 2nd in the middle but not the others. Can you please help?

I have a teapot object and then…
                raycaster = new THREE.Raycaster();

                renderer = new THREE.WebGLRenderer();
                renderer.setPixelRatio( window.devicePixelRatio );
                renderer.setSize( window.innerWidth, window.innerHeight );
                document.body.appendChild( renderer.domElement );

                 control = new THREE.TransformControls( camera, renderer.domElement );

                control.addEventListener( 'change', render );

                scene.add( control );
                renderer.domElement.addEventListener( 'mousedown', clickEvent );

            function clickEvent( event ) {
                var elem = renderer.domElement,
                    boundingRect = elem.getBoundingClientRect(),
                    x = (event.clientX - boundingRect.left) * (elem.width / boundingRect.width),
                    y = (event.clientY - boundingRect.top) * (elem.height / boundingRect.height);
				//1st view
                var view = tripleViews[1];
               camera = view.camera;
                var WIDTH = Math.floor(windowWidth * view.width);
                var HEIGHT = Math.floor(windowHeight * view.height);

                mouse.x = ( x / WIDTH ) * 2 - 1;
                mouse.y = - ( y / HEIGHT ) * 2 + 1;

                raycaster.setFromCamera( mouse, camera );
                var intersects = raycaster.intersectObjects( scene.children );
                if ( intersects.length > 0 ) {
                    if ( INTERSECTED != intersects[ 0 ].object ) {
                        INTERSECTED = intersects[ 0 ].object;

                        if ( control.object === undefined || control.object !== INTERSECTED ) {
                            control.attach( INTERSECTED );
                        }
                    }
                }

                render();
            }
##### Description of the problem

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/yn8azeg1/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/kLwhx875/) (dev branch)

##### Three.js version

- [ ] Dev
- [ ] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
