### ISSUE TITLE
Implement VRML v4.0 in THREE.VRMLLoader for X3Dv4 standards implementation

### ISSUE THREAD

**Issue by coderextreme** [mrdoob/three.js#17755]
##### Description of the problem

Upgrade THREE.VRMLLoader to X3D (VRML) v4 in the next few months, as a reference implementation of the X3Dv4 standard.

##### Three.js version

- [x ] Dev
- [x ] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Same as glTF requirements, I think. VR is in X3Dv4.1 (after X3Dv4).

**Comment by cecilemuller** [comment]
X3D is its own thing though (and has a much wider scope), I think the VRML loader only aims to target VRML97.

**Comment by Mugen87** [comment]
Related discussion at the forum: https://discourse.threejs.org/t/vrml-viewer-still-maintained/555

**Comment by coderextreme** [comment]
THREE VRML Loader was rewritten and supports v2. I’m getting some feedback that V2 does not support PROFILEs.

John

Sent from Mail for Windows 10

**Comment by coderextreme** [comment]
VRML97 (v2) only supports the Base profile.   Does VRMLLoader completely meet the conformance for the  Base profile?  Would it be easier to meet an X3D Interchange profile than the VRML97 Base profile?

**Comment by cecilemuller** [comment]
> I’m getting some feedback that V2 does not support PROFILEs.

Yes VRML doesn't support PROFILE, profiles were introduced with X3D which is a different standard and file format(s).

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/16726#issuecomment-543828389
