### ISSUE TITLE
Video texture example does not work on iOS

### ISSUE THREAD

**Issue by gfodor** [mrdoob/three.js#17757]
##### Description of the problem

It seems that the video texture examples do not work on iOS -- I suspect it has to do with the iOS 13 upgrade, but can't confirm at the moment. This example:

https://threejs.org/examples/#webgl_materials_video

now plays the video full screen. Behind the video, it does seem like texture uploads are happening because once you exit full screen, the underlying example has the last played video frame on the texture.

We noticed that videos no longer play in hubs (hubs.mozilla.com) on iOS and so I went to try this example to see if the basic example worked properly.

##### Three.js version

Version used on examples

##### Browser

- iOS 13 Safari

##### OS

- iOS 13

##### Hardware Requirements (graphics card, VR Device, ...)

iPhone 7

**Comment by gfodor** [comment]
A user tested on iOS 12 and confirmed the same behavior.

**Comment by Mugen87** [comment]
Sorry, I don't have an iOS device at hand and thus can't currently debug the issue.

**Comment by mrdoob** [comment]
> This example:
> 
> https://threejs.org/examples/#webgl_materials_video
>
> now plays the video full screen. Behind the video, it does seem like texture uploads are happening because once you exit full screen, the underlying example has the last played video frame on the texture.

Any chance you can share a screenshot to illustrate?

**Comment by gfodor** [comment]
Sure, not much to see tho, it’s just the movie playing full screen

**Comment by gfodor** [comment]
![IMG_0095](https://user-images.githubusercontent.com/220020/67117161-d0ae8f00-f196-11e9-8c1e-7723195e9426.jpg)

**Comment by gfodor** [comment]
and if i close the full screen, i see the example with the cube, and the last frame of the video on it. (the video no longer playing nor audio)

**Comment by gfodor** [comment]
![IMG_0096](https://user-images.githubusercontent.com/220020/67118242-559aa800-f199-11e9-8c4c-8cb659d9ba15.jpg)

**Comment by Mugen87** [comment]
I had the opportunity today to test with an iPad (5th generation) and iOS 13.2.

> now plays the video full screen. 

I was unable to reproduce. Safari renders `webgl_materials_video` as expected without entering full screen. Other video examples like [webgl_video_panorama_equirectangular](https://threejs.org/examples/webgl_video_panorama_equirectangular.html) also work fine. 

This issue is probably only related to iPhones...

**Comment by timothyallan** [comment]
Just confirming I get the same broken behavior on 13.1.3 on an iPhone 6s Plus. Wonder if it's an iPadOS vs iOS feature set issue, now that they're two separate packages.

**Comment by sciecode** [comment]
I can confirm this behavior iPhone 6 - iOS 13.1.2

**Comment by mrdoob** [comment]
Has this been reported to Apple? We sure didn't change anything.

**Comment by sciecode** [comment]
From  Webkit Blog post [\<video\> Policies](https://webkit.org/blog/6784/new-video-policies-for-ios/)
> A note about the `playsinline` attribute: this attribute has recently been added to the HTML specification, and WebKit has adopted this new attribute by unprefixing its legacy `webkit-playsinline` attribute. This legacy attribute has been supported since iPhoneOS 4.0, and accordance with our updated unprefixing policy, we’re pleased to have been able to unprefix `webkit-playsinline`. Unfortunately, this change did not make the cut-off for iOS 10 Developer Seed 2. If you would like to experiment with this new policy with iOS Developer Seed 2, the prefixed attribute will work, but we would encourage you to transition to the unprefixed attribute when support for it is available in a future seed.

I've tested dropping the prefix on the `playsinline` attribute and it seems to have fixed the issue.

[playsinline example](https://rawcdn.githack.com/sciecode/three.js/4609001bebe140d21a96f55d1baf8949754dbaa8/examples/webgl_materials_video.html) 

@timothyallan @gfodor can you guys confirm this patch works?

**Comment by gfodor** [comment]
confirmed on my end, thanks for fixing! we already add playsinline to our
video elements in hubs, so I guess our regression is unrelated to this one.
:(

**Comment by gfodor** [comment]
fyi, it looks like our issue stems from audio, this radar is in line with what we are seeing: https://bugs.webkit.org/show_bug.cgi?id=203435

**Comment by timothyallan** [comment]
@sciecode Yep, works with iOS 13.1.2
