### ISSUE TITLE
Creating a compressed texture prints unrelated unsupported texture compression warning

### ISSUE THREAD

**Issue by Xalcon** [mrdoob/three.js#17759]
##### Description of the problem

I'm currently writing a texture loader for a proprietary texture container format that uses DXT1/DXT3/DXT5 for some of the supported encodings.

When I create the compressed texture and assign it to a material, everything works as expected - but I get the following warning in the console: (this is on chrome, but firefox shows the same behavior)
```
THREE.WebGLRenderer: WEBGL_compressed_texture_pvrtc extension not supported.
  | get | @ | three.module.js:15777
  | getCompressedTextureFormats | @ | three.module.js:20338
  | uploadTexture | @ | three.module.js:21548
  | setTexture2D | @ | three.module.js:21163
  | safeSetTexture2D | @ | three.module.js:22032
  | setValueT1 | @ | three.module.js:16776
  | WebGLUniforms.upload | @ | three.module.js:17235
  | setProgram | @ | three.module.js:25294
  | WebGLRenderer.renderBufferDirect | @ | three.module.js:24028
  | renderObject | @ | three.module.js:24789
  | renderObjects | @ | three.module.js:24759
  | WebGLRenderer.render | @ | three.module.js:24536
  | loop | @ | main.ts:46
  | (anonymous) | @ | main.ts:51
  | async function (async) |   |  
  | (anonymous) | @ | main.ts:25
  | load (async) |   |  
  | (anonymous) | @ | main.ts:6
```

And indeed, my browser does not support the pvrtc extension:
```
EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
```
**But** the format I'm using is completly unrelated to pvrtc as I'm using the `RGB_S3TC_DXT1_Format`.

I'm able to reproduce the same issue in all of the public compressed texture examples, i.e.
https://threejs.org/examples/webgl_loader_texture_dds.html

I've looked into the code a bit. The uploadTexture function calls getCompressedTextureFormats() to check if the given compression format is supported. The getCompressedTextureFormats function builds an array of supported compression formats by testing each known compression extension until one is found - which in turn prints a warning about not supporting the given extension.
https://github.com/mrdoob/three.js/blob/9f4fb2bed002db1d9a5294b4050a585cd90b4552/src/renderers/webgl/WebGLTextures.js#L437
https://github.com/mrdoob/three.js/blob/9f4fb2bed002db1d9a5294b4050a585cd90b4552/src/renderers/webgl/WebGLState.js#L495-L508
https://github.com/mrdoob/three.js/blob/34dc2478c684066257e4e39351731a93c6107ef5/src/renderers/webgl/WebGLExtensions.js#L44-L48

I'm not sure what the most elegant solution to this is, but the [WebGLExtensions](https://github.com/mrdoob/three.js/blob/34dc2478c684066257e4e39351731a93c6107ef5/src/renderers/webgl/WebGLExtensions.js) getter in its current form should not be used to determine IF an extension is supported since it will always print a warning if the given extension is not supported - even if you have a fallback. 

##### Three.js version

- [x] Dev
- [x] r109
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome 77.0.3865.120 64 Bit
- [x] Firefox 69.0.3 (64-bit)
- [ ] Internet Explorer _(unable to test)_

##### OS

- [ ] All of them
- [x] Windows 10 Version 1903 Build 18362.418
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Well, I guess we need a way to revert the format id into the extension name.

Just put this together:
```js
if ( format >= 0x83F0 && format <= 0x83F3 ) {

    return 'WEBGL_compressed_texture_s3tc';

} else if ( format >= 0x8C01 && format <= 0x8C03 ) {

    return 'WEBGL_compressed_texture_pvrtc';

} else if ( format === 0x8D64 ) {

    return 'WEBGL_compressed_texture_etc1';

} else if ( ( format >= 0x93B0 && format <= 0x93BD ) || ( format >= 0x93D0 && format <= 0x93DD ) ) {

    return 'WEBGL_compressed_texture_astc';

}
```

**Comment by mrdoob** [comment]
I had a closer look and refactored the code that deals with compressed textures.
Let us know if it didn't solve your issue.

**Comment by Xalcon** [comment]
I can confirm, the warning is now gone and my texture loading code is still working fine :) Thanks!
