### ISSUE TITLE
CodeSerializer Can't serialize code for OBJLoader2Parallel worker correctly when threejs is bundled with webpack 

### ISSUE THREAD

**Issue by manyoo** [mrdoob/three.js#17769]
##### Description of the problem

I'm using Threejs in a project with webpack to bundle the code. When I'm trying to use the OBJLoader2Parallel class to load obj files in a web worker,  But it failed due to undefined webpack code _utils_ObjectManipulator_js__WEBPACK_IMPORTED_MODULE_0__ in the worker code.  

After some investigation, I find out that the worker code are generated on the fly using CodeSerializer based on code like WorkerRunner.js, ObjectManipulator.js and OBJLoader2Parser.js, which are all bundled into the same bundle file by webpack.

But due to ObjectManipulator.js is imported to WorkerRunner.js file, the code below:
`ObjectManipulator.applyProperties( parser, payload.params );`
in WorkerRunner.js will be converted to:
`_utils_ObjectManipulator_js__WEBPACK_IMPORTED_MODULE_0__["ObjectManipulator"].applyProperties( parser, payload.params );
`
by webpack.

Then, when the OBJLoader2Parallel is building the worker code with CodeSerializer, the code above will be copied directly and it can't resolve _utils_ObjectManipulator_js__WEBPACK_IMPORTED_MODULE_0__["ObjectManipulator"] to the ObjectManipulator object. This makes the worker fail.

##### Three.js version

- [ ] Dev
- [x] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by manyoo** [comment]
I've moved the ObjectManipulator code into WorkerRunner.js directly, which works in my case. But I'm not sure if it breaks other things or conforms to the design.  Here's my change: [https://github.com/mrdoob/three.js/compare/dev...manyoo:dev](https://github.com/mrdoob/three.js/compare/dev...manyoo:dev)

**Comment by kaisalmen** [comment]
This looks alright when I just looked at it briefly. I will provide further feedback early next week.

**Comment by kaisalmen** [comment]
Thank you, for coming up with a solution. There were problems with webpack and especially with minification/uglification in the past.

**Comment by kaisalmen** [comment]
@manyoo I performed some clean-up in `WorkerRunner` squashed them together with your changes and rebased them. Sorry, it took a little longer.

**Comment by manyoo** [comment]
Thanks! @kaisalmen

**Comment by geoff-harper** [comment]
I believe I'm getting this or something similar still. I'm using create-react-app (v3.3.0) and the loader works well in cra's dev env but when compiled for prod it breaks with a ReferenceError.

ObjectManipulator is undefined in one of these line 84 or 85 of `three.js/examples/jsm/loaders/obj2/worker/parallel/WorkerRunner.js`
```
ObjectManipulator.applyProperties( parser, payload.params, false );
ObjectManipulator.applyProperties( parser, callbacks, false );
```

If there's anything else I can provide let me know, this is very high priority for myself

**Comment by qskycolor** [comment]
> I believe I'm getting this or something similar still. I'm using create-react-app (v3.3.0) and the loader works well in cra's dev env but when compiled for prod it breaks with a ReferenceError.
> 
> ObjectManipulator is undefined in either line 84 or 85 of `three.js/examples/jsm/loaders/obj2/worker/parallel/WorkerRunner.js`
> 
> ```
> ObjectManipulator.applyProperties( parser, payload.params, false );
> ObjectManipulator.applyProperties( parser, callbacks, false );
> ```
> 
> If there's anything else I can provide let me know, this is very high priority for myself

when I use webpack to build, I also get this error, I'm waiting a solution.Thank you.

**Comment by kaisalmen** [comment]
Is there something available in a repo I can access and execute to reproduce the problem. Is there some minification/uglification done in the build process. What is the configuration? What is the build environment, etc...?
I am willing to help, but without context this is guess-work.

**Comment by geoff-harper** [comment]
I've set up a test repo at [https://github.com/geoff-harper/obj-parallel-cra-test](https://github.com/geoff-harper/obj-parallel-cra-test)

**Comment by kaisalmen** [comment]
@geoff-harper thank you very much. I can now reproduce the issue. The uglyfied code is broken.  I already used `yarn eject` to retrieve the webpack config, but I have not yet understood why. I will come back to you...
