### ISSUE TITLE
Why the Editor ground grid lines show and hide?

### ISSUE THREAD

**Issue by fselcukcan** [mrdoob/three.js#17763]
##### Description of the problem

Is it me or the grid lines in default ground you see in [the Editor](https://threejs.org/editor) always shows and hide after certain camera angles and distances? (actually no ground is shown in SCENE tab only a Camera and a Scene)
Problem does exist in Chrome but not in Firefox.
Actually it can be improved to be better looking if not the most necessary feature to have.

In addition, can it be inspectable like the Camera and Scene or is there a reason for that this ground does not show up in the Editor?

##### Three.js version

- [ ] Dev
- [x] r109
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Any chance can illustrate your question with a screenshot or two?

**Comment by looeee** [comment]
Original discussion here:

https://discourse.threejs.org/t/why-editor-ground-grid-lines-show-and-hide/10307/9

**Comment by mrdoob** [comment]
Okay, lets continue in the forum.
