### ISSUE TITLE
A little bit more contrast for some parts of UI in Editor

### ISSUE THREAD

**Issue by fselcukcan** [mrdoob/three.js#17762]
##### Description of the problem

A little bit more contrast for some parts of UI in Editor on [https://threejs.org/editor](https://threejs.org/editor) in light theme would be great.
For example it is hard to distinguish which of the gizmoes selected in the gizmo selector section on bottom.

##### Three.js version

- [ ] Dev
- [x] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Any chance can illustrate your question with a screenshot or two?

**Comment by looeee** [comment]
@mrdoob original discussion here

https://discourse.threejs.org/t/little-bit-more-contrast-for-some-parts-of-ui-in-editor-light-theme/10323/5

**Comment by Mugen87** [comment]
FWIW: I've showed the editor's light theme to a former colleague who works as a designer. He thinks the contrast is okay as it is. The white/gray mix is similar to what we see here at github or at the forum.

**Comment by mrdoob** [comment]
Yeah... Also, the suggestion seems too vague.
