### ISSUE TITLE
TS: Missing type declaration for BufferGeometry.setAttribute

### ISSUE THREAD

**Issue by OlovNord** [mrdoob/three.js#17760]
##### Description of the problem

The setAttribute method was added to BufferGeometry in commit https://github.com/mrdoob/three.js/commit/eab99103aff8b3bb121cb1dd54ba4bcc3e7fd7ed , but no type declaration has been added to BufferGeometry.d.ts

##### Three.js version

- [x] Dev
- [x] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
see #17666
