### ISSUE TITLE
webgl_materials_channels example is broken

### ISSUE THREAD

**Issue by marcofugaro** [mrdoob/three.js#17775]
##### Description of the problem

1. go to https://threejs.org/examples/webgl_materials_channels
2. select `Material > depthBasic` or  `Material > depthRGBA`
3. this error appears in the console:

![image](https://user-images.githubusercontent.com/7217420/67158504-2458de00-f339-11e9-91d4-a03e40f5d5cf.png)

##### Three.js version

- [ ] Dev
- [x] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Related #17626

**Comment by Mugen87** [comment]
The breakage is fixed but a warning is still logged.

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_materials_channels.html
