### ISSUE TITLE
Feature Request: An automated ThreeJS code patch engine

### ISSUE THREAD

**Issue by Seagat2011** [mrdoob/three.js#17773]
##### Feature Request: Converting the Three.js library update/patch engine to XSLT could facilitate auto-updating

I would like to build it and implement a pull request

Alan Turing proved all relativistic Turing Machines are also Turing Complete, thus:

1. function loadModule(){
2. .
3. .
4. }
5.  
6. function unloadModule(){
7. .
8. .
9. }
 
is equivalent to

1.0 function loadModule(){
1.1 .
1.2 .
1.3 }

2.0 function unloadModule(){
2.1 .
2.2 .
2.3 }

The latter could be represented (or converted) to XSLT

XSLT is a versatile templating language developed to implement well-structured libraries at scale...

Thus a submitted patch example w/ test case

2.0.0 function unloadModule(a){

//2.0 assert(unloadModule()) FAIL
//2.0.0 assert(unloadModule(...)) PASS

could run at the command line, to assert its correctness, and later automatically versioned and incorporated into the live code base

**Comment by Seagat2011** [comment]
Or perhaps another tool such as an angelic debugger to detect and repair bugs or suspicious constructs.

Let me know

**Comment by mrdoob** [comment]
> Feature Request: Converting the Three.js library update/patch engine to XSLT could facilitate auto-updating

Auto updating user code?

**Comment by Seagat2011** [comment]
Yes, if thats what you require. Any submission that can be templatized.

**Comment by Seagat2011** [comment]
With the use of an angelic debugger the user would only need to provide. PASS & FAIL test cases, to facilitate an automatic patch.

**Comment by Seagat2011** [comment]
A built-in theorem prover that catalogs github repositories could, with the aid of combinatorics, auto implement many new features

**Comment by Seagat2011** [comment]
I am a real person, I am not an AI built by Microsoft.

**Comment by Seagat2011** [comment]
We must move quickly to widen our skills

The existence of Google finally proves that search is faster than computation, which is the preliminary proof that P=NP -- a mathematical model that states all Non-deterministic Polynomial runtime algorithms (C^k), which can be easily checked by humans, is baseline equivalent to the set of all deterministic Polynomial runtime algorithm (K^c) that are computable by machines.

The reason this is important is in 1950 Alan Turing proved all algorithms in P are computable by machines.

A machine can or will be able to do Anything a human can do

P=NP 

Essentially it means that all higher-order models can be collapsed down to two dimensions  (in other words, onto a simple sheet of paper), Anything that can be written down can be fed to an algorithm, which is basically a set of rules. And all algorithms are computable (by machines)

**Comment by donmccurdy** [comment]
This looks like spam. On the chance that I'm misunderstanding, please link to sources describing XSLT and its application to any software library.

**Comment by Seagat2011** [comment]
I'm referring to the way we could use it.

REFERENCE
XSLT - https://en.m.wikipedia.org/wiki/XSLT

**Comment by Seagat2011** [comment]
Try to imagine git svn, not only at the source code level -- but also at the semantic level

**Comment by Seagat2011** [comment]
From a programmer point of view, imagine a javascript array, Q, representing the XSLT library with each array entry, Q[i], representing a valid javascript statement. 

And Q.insertAt, Q.shift, Q.pop, Q.innerJOIN("\n"), Q.eval() are all valid operations

**Comment by Seagat2011** [comment]
Now for step two: the XSLT library, Q, now represents the Semantic equivalence of the entire ThreeJS library, with each entry Q[i], now a (relativistic) tensor, whose contents, R, are our valid javascript statements...

Do you see where we can go with this?

**Comment by mrdoob** [comment]
Sorry @Seagat2011, we're not interested in this.
