### ISSUE TITLE
3MFLoader: Add support for (embedded) textures.

### ISSUE THREAD

**Issue by omjavaheri** [mrdoob/three.js#17780]
i load 3mf file 
```js
var loader2 = new ThreeMFLoader();
                console.log(loader2);
                loader2.load('./Pile.3mf', function (object) {
                    console.log(object.traverse);
                    object.quaternion.setFromEuler(new THREE.Euler(-Math.PI / 2, 0, 0));
                    //object.position.x = 0;
                    //object.position.y = -250;
                    //object.position.z = 0;
                    scene.add(object);
                    render();

                });
```
don't show 3md color and image

**Comment by Mugen87** [comment]
Please use the the [forum](https://discourse.threejs.org/) or stackoverflow for help request. If you can demonstrate a bug in the loader, we can reopen the issue.

**Comment by Mugen87** [comment]
Some discussion in the forum revealed this is actually a valid feature request. `3MFLoader` does currently not support textures which can also be embedded in the `3MF` file. Here is an example:

[Pile.3mf.zip](https://github.com/mrdoob/three.js/files/3754705/Pile.3mf.zip)

**Comment by Mugen87** [comment]
Diffuse textures are now supported by `3MFLoader`. The support for specular textures is currently not doable since `three.js` interprets them differently than 3MF. More information here: https://github.com/mrdoob/three.js/pull/17806#issue-331934255
