### ISSUE TITLE
Is there any way to commit Object3D transformations?

### ISSUE THREAD

**Issue by olegpatron1992** [mrdoob/three.js#17788]
##### Commit Object3D  transformations

Using blender Im used to apply any transformations to object with CTRL+A; so object becomes zero transformations (rotation/scale/position). Then I can transform object from scratch not worring about previous transformations. Is there any way to do the same in THREE.JS? Something like THREE.Object3D.commitTransforms()?

[Blender example](https://i.stack.imgur.com/zclHK.gif)

[stackoverflow](https://stackoverflow.com/questions/58502308/is-it-possible-to-apply-rotation-scale-position-on-three-object3d)

**Comment by Mugen87** [comment]
Please don't use github for help request. Use stackoverflow or the [forum](https://discourse.threejs.org/) instead.
