### ISSUE TITLE
Animation not found in GLTF Loader

### ISSUE THREAD

**Issue by JudeNino** [mrdoob/three.js#17799]
So im trying to import object as GLTF and sad to say It only shows the object and texture, the animation is not found.

Here's my code:
	// Instantiate a loader
		var loader = new THREE.GLTFLoader();

		// Load a glTF resource
		loader.load(
			// resource URL
		'models/neonglobe/Parrot.glb',
		// called when the resource is loaded
		function ( gltf ) {

			scene.add( gltf.scene );

		},
	
		// called while loading is progressing
		function ( xhr ) {
			console.log( ( xhr.loaded / xhr.total * 100 ) + '% loaded' );

		},
		
		// called when loading has errors
		function ( error ) {	
			console.log( 'An error happened' );

		}
	);
Here's the output: I got the object from three.js sample.
![parrot](https://user-images.githubusercontent.com/38944064/67362749-917a9800-f520-11e9-88c2-786480872400.png)

I hope someone can help me! Thank you so much :)

**Comment by Mugen87** [comment]
Animations are not played automatically. You can access the parsed animation clips via `gltf.animations` and an instance of `AnimationMixer` for the actual playback. Also don't forget to update the mixer in your animation loop.

```js
var animations = gltf.animations;

var mixer = new THREE.AnimationMixer( gltf.scene );
var action = mixer.clipAction( animations[ 0 ] ); 
action.play();
```

Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need more help.
