### ISSUE TITLE
"buffer format and fragment output variable type incompatible" on Chrome 76+

### ISSUE THREAD

**Issue by dukedhx** [mrdoob/three.js#17805]
Getting errors below and couldn't draw markups to the canvas as we could on Firefox/Safari:
```
[.WebGL-0x7f9bc1853c00]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: buffer format and fragment output variable type incompatible
```

Code to draw the markups: https://github.com/Autodesk-Forge/forge-rcdb.nodejs/blob/master/src/client/components/Viewer/Extensions/Dynamic/Viewing.Extension.PointCloudMarkup/PointCloudMarkup/PointCloudMarkup.js

Expected output:
![image](https://user-images.githubusercontent.com/10786558/67457135-68175480-f665-11e9-8e87-514847337433.png)

Any ideas? Appreciate the help!

Please also include a live example if possible. You can start from these templates:

* https://forge-rcdb.autodesk.io/configurator?id=5a361b2b58144b5ed2936ddf

##### Three.js version
- [X] r71

##### Browser
- [X] Chrome v76 and onwards

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This looks like an application specific issue to me since the browser console is full of warnings. You can reopen the issue if you can actually demonstrate a bug in the library. Sorry, but the issue is closed for now.

**Comment by duhaime** [comment]
I reached this error with a frame buffer object when my FBO frag shader didn't include any gl_FragColor definition
