### ISSUE TITLE
Disabling casting shadows on one from multiple lights crashes the renderer

### ISSUE THREAD

**Issue by moskopio** [mrdoob/three.js#17802]
##### Description of the problem

Given a scene that contains multiple light sources, disabling casting shadows on only one of the lights will result with renderer crashing. 

StackTrace:
```
three.js:16521 Uncaught TypeError: Cannot read property 'toArray' of undefined
    at flatten (three.js:16521)
    at PureArrayUniform.setValueM4Array [as setValue] (three.js:16999)
    at Function.WebGLUniforms.upload (three.js:17248)
    at setProgram (three.js:25307)
    at WebGLRenderer.renderBufferDirect (three.js:24041)
    at renderObject (three.js:24802)
    at renderObjects (three.js:24772)
    at WebGLRenderer.render (three.js:24549)
    at render ((index):111)
```

This problem started occurring from version r108. In r107 the problem does not occur.

Examples:
* [jsfiddle](https://jsfiddle.net/pbkx9mwg/) (r109, clicking on 'shadows' will crash the renderer)
* [jsfiddle](https://jsfiddle.net/uxovnwmg/) (r107, clicking on 'shadows' will work properly)

##### Three.js version

- [x] r108
- [x] r108
- [ ] r107

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Some shadow map related refactoring was done in `R108` like #17074. This use case was probably overlooked.

**Comment by Mugen87** [comment]
Actually, I can not reproduce with latest `dev` version:

https://jsfiddle.net/ewhgdyk4/1/

**Comment by moskopio** [comment]
https://jsfiddle.net/pbkx9mwg/ is running using [r109](https://cdnjs.cloudflare.com/ajax/libs/three.js/109/three.js) and crash does happen on this version. 

However, it does work fine on https://jsfiddle.net/ewhgdyk4/1/ which is using latest [dev](https://raw.githack.com/mrdoob/three.js/dev/build/three.js) :+1:

Thank you @Mugen87 !

**Comment by Mugen87** [comment]
I'm glad this issue is already resolved :sweat_smile:
