### ISSUE TITLE
Feature request: ability to compile materials one-by-one (on demand), before rendering

### ISSUE THREAD

**Issue by soadzoor** [mrdoob/three.js#17822]
Hey,

I'm working on a project where I'm using a canvas to create CanvasTextures (then materials from them, then meshes from those..). For performance/optimization purposes, I only use one canvas (and it's very important to keep it that way), and reuse it for every new textures I create (so it's a lot more efficient on the memory than creating a separate canvas for all the different textures).

But this way when there are more than 1 textures are created between 2 frames, then all of those are becoming the same, because the canvas gets overriden before the material compiles. If I could force a material to compile, that would be a solution to this problem. Right now, I'm using a pretty ugly workaround: I'm using canvas.toDataURL to get the information of the current canvas' data before it gets overwritten.

It works, but it's definitely slower and uglier than having an option to force-compile a material.

I'm aware of the WebGLRenderer's `compileMaterials` function, but that traverses through all the elements of the scene, so that's not really what I'd need. What I'd need is the `initMaterial` function to be exposed somehow, if possible.

I'd gladly create a PR with this, but I'd like to know the  opinions of the collaborators about this topic first.

Cheers

**Comment by soadzoor** [comment]
After reading more about this topic, it might be better to create only the texture immediately (upload data to GPU), probably not necessary to compile the material.

**Comment by Mugen87** [comment]
`WebGLRendererinitTexture()` was added lately (#17697) and will be available with the next release `R110`. Maybe you can already check the `dev` version and see if it mitigates your issue.

**Comment by soadzoor** [comment]
@Mugen87

Based on it's description, it's exactly what I need, thanks! Will try soon!

I might reopen the issue in case it's not helping, but I'm 99% sure it will!
