### ISSUE TITLE
support RAW format file or convert to gltf 、obj format 

### ISSUE THREAD

**Issue by kt7456** [mrdoob/three.js#17827]
Is there any way to read the .raw format file or convert it to gltf, obj format?

**Comment by donmccurdy** [comment]
Sorry for commenting on a very old issue, but in case this is helpful to someone: the `.raw` file extension usually implies a [raw image format](https://en.wikipedia.org/wiki/Raw_image_format) containing camera-native data that can (with some effort) be transformed to open domain RGB data like .hdr or .exr files. Ideally that conversion would happen offline, in tools like libraw, dcraw, Adobe Lightroom, etc.

If one does need to load a camera-native image in three.js directly, I've had some success using [`libraw.wasm`](https://github.com/ssssota/libraw.wasm) for that purpose. This requires a ~800kb WASM binary.

Aside: Converting a 2D image to a 3D model (.gltf, .obj) is probably a misunderstanding – there's no direct 'conversion' between the two concepts, although you could of course create a 3D scene and make that 2D image appear somewhere in it.
