### ISSUE TITLE
calling renderer.render() inside scene.onBeforeRender() corrupts the renderer state

### ISSUE THREAD

**Issue by wizgrav** [mrdoob/three.js#17839]
##### Description of the problem

calling renderer.render() from inside scene.onBeforeRender() eventually crashes the renderer. The issue is that currentRenderState is set to null at the end of the inner renderer.render() and then when execution continues from scene.onBeforeRender() it tries to access methods on the null object.

This is unfortunate because scene.onBeforeRender() is the only opportunity we get to render anything/ prepare textures using the VR arrayCamera before the actual scene rendering. In my case this was triggered while setting up a tiled forward setup using a shader to generate the tile texture in order to up the light count. Depth prepass and such are also affected

##### Three.js version

- [x] Dev
- [x] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Fixed via #18626.
