### ISSUE TITLE
Update npm installation CL instruction

### ISSUE THREAD

**Issue by flomerboy** [mrdoob/three.js#17835]
##### Description of the problem

When I tried to run `npm install three` with npm v 6.11.3, I got a bunch of errors. The correct command that got it to work for me was `npm i three`.

I suggest to update the documentation to say `npm i three` so that others won't run into this mistake. 

I'm not certain that this issue exists for other folks with different versions of npm, but the instructions on https://www.npmjs.com/package/three list `npm i three` which leads me to believe that this is what should be listed on the official three.js website.

**Comment by mrdoob** [comment]
> When I tried to run `npm install three` with npm v 6.11.3, I got a bunch of errors. 

What errors did you get?

**Comment by flomerboy** [comment]
okay actually I just tried to reproduce today but I am actually getting the same warnings from both commands - and reading them with more scrutiny - they are actually just saying that they created new files and folders because the folder was empty. 

Apologies, I'll close this 😅
