### ISSUE TITLE
Three.js not coloring in LineSegments properly.

### ISSUE THREAD

**Issue by Woolworths** [mrdoob/three.js#17836]
##### Description of the problem

Three.js with LineSegments and BufferGeometry is not correctly coloring lines while using geometry attributes and THREE.VertexColors. I'm not sure if I'm misunderstanding what's going on here or whether this is a bug.

See here:
https://codepen.io/woolworths/pen/JjjrJVw
My output:
<img width="716" alt="Screen Shot 2019-10-30 at 6 14 44 pm" src="https://user-images.githubusercontent.com/6524227/67836632-3e689c80-fb41-11e9-8965-635c9bb64ca2.png">

Furthermore, if I display 2 lines:  
`bufferIndices.push(0, 1, 1, 2, 0, 2);`  
I still have to add 3 colors:
`bufferColors.push(1,0,0,0,0,1,1,1,0);`  

I thought the vertexColors property of LineBasicMaterial was supposed to color the line? It appears as if it is colouring the line by "mixing" the colours from the edge of the line. 

Anyone know any fixes? :)

##### Three.js version

- [ ] Dev
- [x] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Not sure.

**Comment by Mugen87** [comment]
Your codepen shows the expected behavior since vertex colors are interpolated between two vertices. If you want to color the entire line, it's better to use an non-indexed geometry like so:

https://jsfiddle.net/dtLfgab3/

Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need more help.

**Comment by Woolworths** [comment]
My apologies, thank you for the prompt response.
