### ISSUE TITLE
Documentation for getObject

### ISSUE THREAD

**Issue by Semphora** [mrdoob/three.js#17854]
https://threejs.org/docs/#api/en/core/Object3D.getObjectByProperty

The documentation states that the getObjectBy... functions search through the children of an object. The implementation however seems to be such, that if the parent itself satisfies the condition, it gets returned instead.

either the implementation or the documentation should probably adjusted

**Comment by Mugen87** [comment]
Feel free to clarify the documentation 👍

**Comment by Semphora** [comment]
done. pull request #17862
