### ISSUE TITLE
PMREM causes seams on Nvidia GPUs with anisotropic filtering enabled

### ISSUE THREAD

**Issue by JordyvanDortmont** [mrdoob/three.js#17855]
##### Description of the problem

When adding an equirectangular environment map to a scene using `THREE.WebGLRenderTargetCube.fromEquirectangularTexture` and using the `PMREMGenerator` on Nvidia GPUs in both Firefox and Chrome on Windows, anisotropic filtering causes seams in the lighting of the 3D model. You can see this happening in the screenshot of the EXR environment map example below.

![seams_screenshot](https://user-images.githubusercontent.com/13318975/68072879-ddcca000-fd8a-11e9-90b9-3630078d62e0.jpg)
https://threejs.org/examples/?q=env#webgl_materials_envmaps_exr

The seams are present independent of the settings, so for EXR, PNG and JPG, any metalness / roughness and exposure. They're not present in IE or Edge, not on an Adreno GPU on Android and not on a Chromebook.

Nvidia's default settings enable anisotropic filtering in the control panel for the GTX 1070 and GTX 2060 (Mobile). When you disable anisotropic filtering for Chrome and Firefox, the seams are gone. This is unfortunate, because most users won't disable anisotropic filtering manually, so they'll see the seams.

Am I missing some setting that fixes this? I tried changing some texture filtering, wrapping and anisotropy settings, but to no avail. I believe this was not caused by any recent change, because I encountered the issue earlier this year as well.

##### Three.js version

- [x] Dev
- [x] r110

##### Browser

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Edge

##### OS

- [x] Windows
- [ ] Android
- [ ] Chrome OS

##### Hardware Requirements

- [x] Nvidia GTX 1070
- [x] Nvidia GTX 2060 (Mobile)
- [ ] Adreno 630 (OS: Android)
- [ ] Some integrated Intel GPU for Chromebook

**Comment by sciecode** [comment]
I was able to reproduce this problem, however these seams are unrelated `fromEquirectangularTexture`.
Seams are being introduced by `PMREMGenerator`.

PMREM: 
![image](https://user-images.githubusercontent.com/3927951/68136795-9e29c380-ff04-11e9-8d31-261814405c2f.png)

without:
![image](https://user-images.githubusercontent.com/3927951/68136972-e812a980-ff04-11e9-8018-bf0944cd5a42.png)

**Comment by sciecode** [comment]
After digging a little bit more through `PMREMGenerator` code, I noticed the following comment at the very top of the file:

> To avoid cube map seams, I create an extra pixel around each face. This way when the cube map is sampled by an application later(with a little care by sampling the centre of the texel), the extra 1 border of pixels makes sure that there is no seams artifacts present.

Clearly the creators knew about the possibility of cube map seams and devised a solution to it, but perhaps they failed to considered that anisotropic wouldn't guarantee sampling from the center of the texel.

I believe it would be wise to ping creators in here.

**Comment by JordyvanDortmont** [comment]
Thanks for looking into this @sciecode! I changed the title and the issue to match your findings. I also noticed the comment in the file and apparently PMREM is going to be replaced by @elalish? https://github.com/mrdoob/three.js/issues/16409#issuecomment-548830788

**Comment by elalish** [comment]
@JordyvanDortmont I believe I fixed this with #18004, but I'd very much appreciate it if you could verify.

**Comment by elalish** [comment]
Correction, please test #18045 instead, since #18004 broke some of the examples (including the one referenced).

**Comment by JordyvanDortmont** [comment]
The seams are gone now, so it's fixed. Thank you!
