### ISSUE TITLE
Draco + morph targets results in Cannot read property 'isInterleavedBufferAttribute' of null

### ISSUE THREAD

**Issue by jespertheend** [mrdoob/three.js#17878]
##### Description of the problem

Hi, I have the following glb object. [morph.glb.txt](https://github.com/mrdoob/three.js/files/3813911/morph.glb.txt) (please remove .txt extension, github doesn't allow .glb uploads)
When I drag this file to [gltf-viewer.donmccurdy.com](https://gltf-viewer.donmccurdy.com/) it loads fine.

However, when I add draco compression to it using [gltf.insimo.com](https://gltf.insimo.com/) I end up with this file: 
[morph with draco.glb.txt](https://github.com/mrdoob/three.js/files/3813926/morph.with.draco.glb.txt)
Which loads fine on [gltf.insimo.com](https://gltf.insimo.com/) but gives an error on [gltf-viewer.donmccurdy.com](https://gltf-viewer.donmccurdy.com/.) The latter seems to be on three.js r108 whereas [gltf.insimo.com](https://gltf.insimo.com/) is still on r88.

It seems like somewhere along the way support for draco and Morph  targets broke. I'm getting the following error `Cannot read property 'isInterleavedBufferAttribute' of null`.
This is not just an issue with the gltf viewer, as it is also happening on my local build with three r110.

It appears like the issue lies within `GLTFLoader.js @ addMorphTargets()`. I tried to fix it myself but haven't had much luck so far.
`parser.getDependency( 'accessor', target.POSITION )` appears to return a resolved Promise with `null` which is intended, but I think when draco is involved, `parser.getDependency('accessor')` shouldn't be called in the first place.

If anyone could help me out with this that'd be much appreciated :)

##### Three.js version
r110

**Comment by donmccurdy** [comment]
@jespertheend sorry, the glTF+Draco extension does not actually support morph targets. gltf.insimo.com did an experimental implementation proposing it, but that never got standardized and isn't supported in any other glTF tools. 

I'd suggest suggest using glTF-Pipeline for Draco compression instead (which will leave the morph targets uncompressed). Alternatively, [gltfpack](https://github.com/zeux/meshoptimizer#gltfpack) might be able to reduce the size of your morph targets without Draco. You'll need to avoid gltfpack's `-c` option, as that's also an experimental thing that requires a custom loader.

**Comment by donmccurdy** [comment]
Closing this issue, but happy to discuss alternatives more in the forums.

**Comment by jespertheend** [comment]
Ah I see, that explains why the draco compressor from glTF-Pipeline was still significantly bigger than the one from gltf.insimo.com.
I took the GLTFLoader and draco library from gltf-pipeline and added it to our project with some changes. It might not be the best futureproof way to do it, but we really needed to reduce the bandwidth. We went from 42Mb to 12Mb for our total page. Which offsets a significant amount of server costs.

Thanks for the help though! I wasn't aware gltf.insimo.com was using a non-standard way.

**Comment by svensht2** [comment]
@donmccurdy I'm also working on a glTF usage that is geometry heavy and relies on efficiently compressed morph targets for significant file size reductions.
My understanding is that morph targets compression is on the roadmap for the draco extension, but I'm unable to find any updates or timelines on that.
I experimented with the Draco animation compression capabilities, on which the draco animation extension is built on and I found that its still 3-4x less efficient than encoding the morph target deltas as an attribute.
I'd be happy to contribute to this effort, and would appreciate pointers on first steps to go about this.

**Comment by donmccurdy** [comment]
> I experimented with the Draco animation compression capabilities, ... and I found that its still 3-4x less efficient than encoding the morph target deltas as an attribute.

I'm not sure if that is feedback on the Draco library itself, or the proposed extension (https://github.com/KhronosGroup/glTF/pull/1407) but you may want to comment there either way, mentioning (a) your interest in the proposal and (b) any feedback on the current state of things.

That is just a proposal; it is neither formally on a roadmap nor actively being worked on, that I'm aware of.

**Comment by jespertheend** [comment]
@svensht2 I ended up using the latest version of threejs with an older version of the draco library with some slight modifications. We're essentially using the same setup as what is currently live on [gltf.insimo.com](https://gltf.insimo.com/) but with a newer threejs version. We're also using [gltf.insimo.com](https://gltf.insimo.com/) to compress our assets and it's currently working very nicely. We're saving many MBs on the network and server costs as a result.

The way we're doing it might not be the official way, since draco morph targets is not available yet. So it might not be what you're looking for, but it works for us for now. [ducklings.io](https://ducklings.io/) is the page I'm talking about in case you need an example.

**Comment by svensht2** [comment]
@jespertheend  thanks for the pointers, what you're doing is exactly what I'm looking for, good to hear there is a way to still achieve this compression.
Why did you need to make modification in Draco?
Beyond getting this to work I would also like to see how I can help to making this part of the spec. I believe that integrating this support into the glTF draco extension would be beneficial to anybody that is using morph targets and cares about file size.

**Comment by jespertheend** [comment]
I don't exactly remember the details, but from what I can recall and from what I can see in my git repository. You'll have to use the GLTFLoader.js and DRACOLoader.js from what is currently live on insimo. Along with the external library directory which you should host separately.

You can then add draco support to your gltf loader using
```
gltfLoader.setDRACOLoader(new THREE.DRACOLoader("libs/draco/",{
    type: "js",
}));
```
The only modifications I had to make were adding back support for proper names in the morphTargetDictionary. The lines of code that you see [here](https://github.com/mrdoob/three.js/blob/aeb347fdfabcaef4b5be5164214e8df7b7d9a762/examples/js/loaders/GLTFLoader.js#L1359) were not in the insimo version yet. So you'll have to add those if you want to have a useful `morphTargetDictionary` names.

Also I removed two `console.time( 'GLTFLoader' );` lines because they were cluttering my console.
