### ISSUE TITLE
Feature Request: Clear Coat tint and thickness

### ISSUE THREAD

**Issue by raMaa026** [mrdoob/three.js#17874]
Hello,

The Clear coat shader is a great addition to three.js and big thanks whoever worked on it.
While exploring SketchFab settings, I have noticed that they have thickness and tint added as well, which ads more to the visual impact overall.

It would be a great help if these features could be implemented in three.js.

Thank you very much

**Comment by donmccurdy** [comment]
Related: The proposed glTF clearcoat extension (draft) is here: [KHR_materials_clearcoat](https://github.com/KhronosGroup/glTF/pull/1677). This is based on [Autodesk Standard Surface](https://github.com/Autodesk/standard-surface) and [Dassault Systemes Enterprise PBR](https://github.com/DassaultSystemes-Technology/EnterprisePBRShadingModel).

That proposal does not include the features suggested here (coat thickness and tint). But it does include a few things not yet in three.js: `clearcoatMap` and `clearcoatRoughnessMap`.

**Comment by raMaa026** [comment]
Would you be able to tell me if these two features are available for 1.0 version.

Thank you

**Comment by donmccurdy** [comment]
I'm not sure what you mean by "1.0 version"... glTF, or three.js?

In either case – there are no plans to add clearcoat thickness or tint in either one. If you are using glTF and would like to see these supported, I would recommend commenting on https://github.com/KhronosGroup/glTF/pull/1677 and sharing examples and use cases if you can do so.

**Comment by raMaa026** [comment]
Thank you. I will try to do what you have suggested.

**Comment by Mugen87** [comment]
Closing for now. I'm adding #16977 here since it is the leading issue for enterprise PBR improvements. I recommend to proceed the discussion there.
