### ISSUE TITLE
 Failed to execute 'texImage2D' on 'WebGLRenderingContext'

### ISSUE THREAD

**Issue by xiewenling** [mrdoob/three.js#17879]
##### Description of the problem
I got the following error when when set texture for my 3D objects:
VM1084:1 THREE.WebGLState: TypeError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': No function was found that matched the signature provided.
![image](https://user-images.githubusercontent.com/57386346/68294058-3329e980-00ca-11ea-97c2-5cf10a31d28f.png)

After debug I found the problem is caused by the function resizeImage in WebGLTextures. This function sometimes return me an OffscreenCanvas, which is not supported by WebGLRenderingContext.texImage2D.
![image](https://user-images.githubusercontent.com/57386346/68293933-ecd48a80-00c9-11ea-9129-43f86363659a.png)

I am trying to fix this problem in function resizeImage by returning the                    
                    'return context.getImageData(0, 0, width, height);'
instead of 
' return canvas;'
But I am really not sure this is the right way. Would you give me some suggestions?

##### Three.js version
r105

##### Browser
I am using a browser based on Chromium 69.0.3497.100

##### OS
- [ ] Windows
- [ ] macOS

**Comment by xiewenling** [comment]
Here is my code change:
![image](https://user-images.githubusercontent.com/57386346/68294378-fad6db00-00ca-11ea-9438-ee1a58223c80.png)

**Comment by Mugen87** [comment]
> I am using a browser based on Chromium 69.0.3497.100

What does this exactly mean? Browser like Chrome and Firefox have no problems when `OffscreenCanvas` is used for resizing. Besides, there is a check that ensure `OffscreenCanvas` is only used if it's available and a context creation possible. 

> OffscreenCanvas, which is not supported by WebGLRenderingContext.texImage2D.

This is not true for latest browser version. I guess your browser version is just too old.

https://bugs.chromium.org/p/chromium/issues/detail?id=753483

**Comment by xiewenling** [comment]
This browser is an open source browser which used widely in Chins. It is based on Chromium 69.0.3497.100. And I have no way to upgrade the core of this browser. Is there any way I can workaround this problem?

**Comment by xiewenling** [comment]
I am using the 360 browser, this browser is widely used in China. It is based on Chromium 69.0.3497.100. I have no way to push the 360 company to upgrade the Chromium version. Is there any way I can workaround this problem?

**Comment by xiewenling** [comment]
And BTW, the same company has another browser based on 63.0.3239.132, which works pretty well for me. So this might not simply because the the Chromium too old.

**Comment by WestLangley** [comment]
Update to the latest revision of three.js. Either use power-of-two textures, or disable mipmaps.

**Comment by Mugen87** [comment]
> And BTW, the same company has another browser based on 63.0.3239.132, which works pretty well for me

`OffscreenCanvas` is available without a flag in Chromium 69. So older versions don't have it and hence the existing checks in `WebGLTextures` work. 

I don't think we are going to the code in `WebGLTextures` just because 360 browser uses a Chrome version with buggy `OffscreenCanvas` support. The workarounds to avoid resizing are easy to use. 

BTW: Another way to avoid the internal resize is to use a WebGL 2 rendering context.

**Comment by trusktr** [comment]
> Update to the latest revision of three.js. Either use power-of-two textures, or disable mipmaps.

Sure enough, I had a canvas being used as a texture with canvas dimensions not power-of-two.

The error makes no sense for an end user. Can we instead output `Either use power-of-two textures, or disable mipmaps.`?

**Comment by kmturley** [comment]
Has the same issue.... I think the WebGL error is showing as a console warning, which isn't the most helpful. The top results on google say it's a CORS issue, when it's a texture issue:

> [.WebGL-0x86d0ad00]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
> 251[.WebGL-0x86d0ad00]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
> three.min.js?cache=dbbe9ec:133 THREE.WebGLRenderer: Texture has been resized from (1258x430) to (1024x256).
> l @ three.min.js?cache=dbbe9ec:133
> three.min.js?cache=dbbe9ec:131 THREE.WebGLState: TypeError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': No function was found that matched the signature provided.

My canvas size was:
width = 104.83333333333333
height = 35.833333333333336

I fixed by rounding the canvas width and height up to the next power of two:
```
nextPowerOf2(n) {
  return Math.pow(2, Math.ceil(Math.log(n) / Math.log(2)));
}

canvas.width = nextPowerOf2(width);
canvas.height = nextPowerOf2(height);
```

**Comment by NongDeng** [comment]
Play video with hls.js in android can resolve it.

**Comment by Hammad-hab** [comment]
I have the same issue. `three.module.js:21931 THREE.WebGLState: TypeError: Failed to execute 'texSubImage2D' on 'WebGL2RenderingContext': Overload resolution failed.
    at Object.texSubImage2D (three.module.js:21927)
    at uploadTexture (three.module.js:23159)
    at WebGLTextures.setTexture2D (three.module.js:22624)
    at SingleUniform.setValueT1 [as setValue] (three.module.js:17427)
    at Function.WebGLUniforms.upload (three.module.js:17953)
    at setProgram (three.module.js:27748)
    at WebGLRenderer.renderBufferDirect (three.module.js:26700)
    at renderObject (three.module.js:27308)
    at renderObjects (three.module.js:27277)
    at renderScene (three.module.js:27199)
texSubImage2D @ three.module.js:21931
uploadTexture @ three.module.js:23159
setTexture2D @ three.module.js:22624
setValueT1 @ three.module.js:17427
WebGLUniforms.upload @ three.module.js:17953
setProgram @ three.module.js:27748
WebGLRenderer.renderBufferDirect @ three.module.js:26700
renderObject @ three.module.js:27308
renderObjects @ three.module.js:27277
renderScene @ three.module.js:27199
WebGLRenderer.render @ three.module.js:27019
Animation @ App.js:76
requestAnimationFrame (async)
Animation @ App.js:72
requestAnimationFrame (async)
Animation @ App.js:72
requestAnimationFrame (async)
Animation @ App.js:72
requestAnimationFrame (async)
Animation @ App.js:72
requestAnimationFrame (async)
Animation @ App.js:72
requestAnimationFrame (async)
Animation @ App.js:72
requestAnimationFrame (async)
Animation @ App.js:72
requestAnimationFrame (async)
Animation @ App.js:72
Main @ App.js:78
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
./src/index.js @ index.js:7
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
three.module.js:21931 THREE.WebGLState: TypeError: Failed to execute 'texSubImage2D' on 'WebGL2RenderingContext': Overload resolution failed.
    at Object.texSubImage2D (three.module.js:21927)
    at uploadTexture (three.module.js:23159)
    at WebGLTextures.setTexture2D (three.module.js:22624)
    at SingleUniform.setValueT1 [as setValue] (three.module.js:17427)
    at Function.WebGLUniforms.upload (three.module.js:17953)
    at setProgram (three.module.js:27748)
    at WebGLRenderer.renderBufferDirect (three.module.js:26700)
    at renderObject (three.module.js:27308)
    at renderObjects (three.module.js:27277)`
I use ReactJS with ThreeJS

**Comment by mrdoob** [comment]
There's nothing we can do to fix this.
Please report the issue to 360 browser instead.
