### ISSUE TITLE
BUG: MeshPhongMaterial flicker with flatShading: false

### ISSUE THREAD

**Issue by kpetrow** [mrdoob/three.js#17882]
Updated from v92 to v110 and have flicker on the edges.  I use PlaneBufferGeometry with null z values to represent unknown elevations(holes).  The sparse grid shows a flicker where the nulls' edges are.  Was not seen with flatShading: true or v92:

![image](https://user-images.githubusercontent.com/18248938/68339808-812af700-00a2-11ea-8f01-ec761d009580.png)

I know you are going to say NaN are not supported in geometries, but any chance you could fix this or point me in proper direction?

##### Three.js version

- [ ] Dev
- [x ] r110
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by kpetrow** [comment]
Its something that occurred between 103 and 104.  103 works, 104 flickers.... Looking at change log

**Comment by Mugen87** [comment]
I'm afraid a screenshot is not sufficient to debug this issue. Please always provide live examples when reporting such problems.

**Comment by kpetrow** [comment]
thank you for your help;  Flicker is seen when not moving.

https://jsfiddle.net/b4xzmqcr/

**Comment by kpetrow** [comment]
The issue gets worse when multiple windows are open and active.  Also noticeably when "lightShot" screen capture was opened.  Also noticed when whats app message received.  I have a dev team of 4 guys finding inconsistencies of producing on different graphics cards with different results, but all see a flicker at different times

**Comment by Mugen87** [comment]
Sorry, but I can't see any flickering on my system. Tested with Chrome 78.0.3904.97, FF 70.0.1 and macOS 0.14.6.

**Comment by kpetrow** [comment]
video:

[here](https://drive.google.com/open?id=1zgscsAoXE1DNdWyIW1qORhXgatCRhKL1)

windows version 1809 OS Build 17763.805
NVIDIA GeForce RTX 2080 SUPER

All tester have windows

**Comment by arpu** [comment]
looks like a Problem with the nvideo driver?  i tested this on two Systems, with amd driver without any problem

**Comment by kpetrow** [comment]
I haven't gone through the diff of 103-104, but ideas on where to look that would make this happen?

**Comment by sciecode** [comment]
Was able to replicate on Windows with NVidia GPU, but not on Mac with intel integrated GPU. 

Couldn't find anything on the change logs from `r103 -> r104` that would explain that. 

But, then again, you are making use of unsupported behavior, as you said it yourself.

**Comment by kpetrow** [comment]
Seems very odd that separate instances of three are causing it.  Even though unsupported seems like it could be a canary for a scoping issue?

**Comment by makc** [comment]
why not just map NaNs to some big but finite values to move the triangles out of the view

**Comment by Mugen87** [comment]
In any event, I don't see a `three.js` bug here. I suppose this happens also with pure WebGL and with any other 3D engine so I think it's more correct to close the issue and move the dicussion to stackoverflow or the forum.

**Comment by kpetrow** [comment]
@makc We are constantly updating the surface with new known position.  Might be worth testing but would take a considerable amount of work.  If anything this would double the overhead(two geometries needed) of multi-million point grid geometries.

@Mugen87 I do not think that is true because the issue is not seen in r104.  There was a change in the code base that introduced this bug.  If ti never worked then webGL/GPU issue, but it was working until something changed

**Comment by kpetrow** [comment]
So there were two shader changes in the revision. 

line: 6083
`	var lights_pars_begin = "uniform vec3 ambientLightColor;\nuniform vec3 lightProbe[ 9 ];\nvec3 shGetIrradianceAt( in vec3 normal, in vec3 shCoefficients[ 9 ] ) {\n\tfloat x = normal.x, y = normal.y, z = normal.z;\n\tvec3 result = shCoefficients[ 0 ] * 0.886227;\n\tresult += shCoefficients[ 1 ] * 2.0 * 0.511664 * y;\n\tresult += shCoefficients[ 2 ] * 2.0 * 0.511664 * z;\n\tresult += shCoefficients[ 3 ] * 2.0 * 0.511664 * x;\n\tresult += shCoefficients[ 4 ] * 2.0 * 0.429043 * x * y;\n\tresult += shCoefficients[ 5 ] * 2.0 * 0.429043 * y * z;\n\tresult += shCoefficients[ 6 ] * ( 0.743125 * z * z - 0.247708 );\n\tresult += shCoefficients[ 7 ] * 2.0 * 0.429043 * x * z;\n\tresult += shCoefficients[ 8 ] * 0.429043 * ( x * x - y * y );\n\treturn result;\n}\nvec3 getLightProbeIrradiance( const in vec3 lightProbe[ 9 ], const in GeometricContext geometry ) {\n\tvec3 worldNormal = inverseTransformDirection( geometry.normal, viewMatrix );\n\tvec3 irradiance = shGetIrradianceAt( worldNormal, lightProbe );\n\treturn irradiance;\n}\nvec3 getAmbientLightIrradiance( const in vec3 ambientLightColor ) {\n\tvec3 irradiance = ambientLightColor;\n\t#ifndef PHYSICALLY_CORRECT_LIGHTS\n\t\tirradiance *= PI;\n\t#endif\n\treturn irradiance;\n}\n#if NUM_DIR_LIGHTS > 0\n\tstruct DirectionalLight {\n\t\tvec3 direction;\n\t\tvec3 color;\n\t\tint shadow;\n\t\tfloat shadowBias;\n\t\tfloat shadowRadius;\n\t\tvec2 shadowMapSize;\n\t};\n\tuniform DirectionalLight directionalLights[ NUM_DIR_LIGHTS ];\n\tvoid getDirectionalDirectLightIrradiance( const in DirectionalLight directionalLight, const in GeometricContext geometry, out IncidentLight directLight ) {\n\t\tdirectLight.color = directionalLight.color;\n\t\tdirectLight.direction = directionalLight.direction;\n\t\tdirectLight.visible = true;\n\t}\n#endif\n#if NUM_POINT_LIGHTS > 0\n\tstruct PointLight {\n\t\tvec3 position;\n\t\tvec3 color;\n\t\tfloat distance;\n\t\tfloat decay;\n\t\tint shadow;\n\t\tfloat shadowBias;\n\t\tfloat shadowRadius;\n\t\tvec2 shadowMapSize;\n\t\tfloat shadowCameraNear;\n\t\tfloat shadowCameraFar;\n\t};\n\tuniform PointLight pointLights[ NUM_POINT_LIGHTS ];\n\tvoid getPointDirectLightIrradiance( const in PointLight pointLight, const in GeometricContext geometry, out IncidentLight directLight ) {\n\t\tvec3 lVector = pointLight.position - geometry.position;\n\t\tdirectLight.direction = normalize( lVector );\n\t\tfloat lightDistance = length( lVector );\n\t\tdirectLight.color = pointLight.color;\n\t\tdirectLight.color *= punctualLightIntensityToIrradianceFactor( lightDistance, pointLight.distance, pointLight.decay );\n\t\tdirectLight.visible = ( directLight.color != vec3( 0.0 ) );\n\t}\n#endif\n#if NUM_SPOT_LIGHTS > 0\n\tstruct SpotLight {\n\t\tvec3 position;\n\t\tvec3 direction;\n\t\tvec3 color;\n\t\tfloat distance;\n\t\tfloat decay;\n\t\tfloat coneCos;\n\t\tfloat penumbraCos;\n\t\tint shadow;\n\t\tfloat shadowBias;\n\t\tfloat shadowRadius;\n\t\tvec2 shadowMapSize;\n\t};\n\tuniform SpotLight spotLights[ NUM_SPOT_LIGHTS ];\n\tvoid getSpotDirectLightIrradiance( const in SpotLight spotLight, const in GeometricContext geometry, out IncidentLight directLight  ) {\n\t\tvec3 lVector = spotLight.position - geometry.position;\n\t\tdirectLight.direction = normalize( lVector );\n\t\tfloat lightDistance = length( lVector );\n\t\tfloat angleCos = dot( directLight.direction, spotLight.direction );\n\t\tif ( angleCos > spotLight.coneCos ) {\n\t\t\tfloat spotEffect = smoothstep( spotLight.coneCos, spotLight.penumbraCos, angleCos );\n\t\t\tdirectLight.color = spotLight.color;\n\t\t\tdirectLight.color *= spotEffect * punctualLightIntensityToIrradianceFactor( lightDistance, spotLight.distance, spotLight.decay );\n\t\t\tdirectLight.visible = true;\n\t\t} else {\n\t\t\tdirectLight.color = vec3( 0.0 );\n\t\t\tdirectLight.visible = false;\n\t\t}\n\t}\n#endif\n#if NUM_RECT_AREA_LIGHTS > 0\n\tstruct RectAreaLight {\n\t\tvec3 color;\n\t\tvec3 position;\n\t\tvec3 halfWidth;\n\t\tvec3 halfHeight;\n\t};\n\tuniform sampler2D ltc_1;\tuniform sampler2D ltc_2;\n\tuniform RectAreaLight rectAreaLights[ NUM_RECT_AREA_LIGHTS ];\n#endif\n#if NUM_HEMI_LIGHTS > 0\n\tstruct HemisphereLight {\n\t\tvec3 direction;\n\t\tvec3 skyColor;\n\t\tvec3 groundColor;\n\t};\n\tuniform HemisphereLight hemisphereLights[ NUM_HEMI_LIGHTS ];\n\tvec3 getHemisphereLightIrradiance( const in HemisphereLight hemiLight, const in GeometricContext geometry ) {\n\t\tfloat dotNL = dot( geometry.normal, hemiLight.direction );\n\t\tfloat hemiDiffuseWeight = 0.5 * dotNL + 0.5;\n\t\tvec3 irradiance = mix( hemiLight.groundColor, hemiLight.skyColor, hemiDiffuseWeight );\n\t\t#ifndef PHYSICALLY_CORRECT_LIGHTS\n\t\t\tirradiance *= PI;\n\t\t#endif\n\t\treturn irradiance;\n\t}\n#endif";`

and line 6095:
`	var lights_fragment_begin = "\nGeometricContext geometry;\ngeometry.position = - vViewPosition;\ngeometry.normal = normal;\ngeometry.viewDir = normalize( vViewPosition );\nIncidentLight directLight;\n#if ( NUM_POINT_LIGHTS > 0 ) && defined( RE_Direct )\n\tPointLight pointLight;\n\t#pragma unroll_loop\n\tfor ( int i = 0; i < NUM_POINT_LIGHTS; i ++ ) {\n\t\tpointLight = pointLights[ i ];\n\t\tgetPointDirectLightIrradiance( pointLight, geometry, directLight );\n\t\t#ifdef USE_SHADOWMAP\n\t\tdirectLight.color *= all( bvec2( pointLight.shadow, directLight.visible ) ) ? getPointShadow( pointShadowMap[ i ], pointLight.shadowMapSize, pointLight.shadowBias, pointLight.shadowRadius, vPointShadowCoord[ i ], pointLight.shadowCameraNear, pointLight.shadowCameraFar ) : 1.0;\n\t\t#endif\n\t\tRE_Direct( directLight, geometry, material, reflectedLight );\n\t}\n#endif\n#if ( NUM_SPOT_LIGHTS > 0 ) && defined( RE_Direct )\n\tSpotLight spotLight;\n\t#pragma unroll_loop\n\tfor ( int i = 0; i < NUM_SPOT_LIGHTS; i ++ ) {\n\t\tspotLight = spotLights[ i ];\n\t\tgetSpotDirectLightIrradiance( spotLight, geometry, directLight );\n\t\t#ifdef USE_SHADOWMAP\n\t\tdirectLight.color *= all( bvec2( spotLight.shadow, directLight.visible ) ) ? getShadow( spotShadowMap[ i ], spotLight.shadowMapSize, spotLight.shadowBias, spotLight.shadowRadius, vSpotShadowCoord[ i ] ) : 1.0;\n\t\t#endif\n\t\tRE_Direct( directLight, geometry, material, reflectedLight );\n\t}\n#endif\n#if ( NUM_DIR_LIGHTS > 0 ) && defined( RE_Direct )\n\tDirectionalLight directionalLight;\n\t#pragma unroll_loop\n\tfor ( int i = 0; i < NUM_DIR_LIGHTS; i ++ ) {\n\t\tdirectionalLight = directionalLights[ i ];\n\t\tgetDirectionalDirectLightIrradiance( directionalLight, geometry, directLight );\n\t\t#ifdef USE_SHADOWMAP\n\t\tdirectLight.color *= all( bvec2( directionalLight.shadow, directLight.visible ) ) ? getShadow( directionalShadowMap[ i ], directionalLight.shadowMapSize, directionalLight.shadowBias, directionalLight.shadowRadius, vDirectionalShadowCoord[ i ] ) : 1.0;\n\t\t#endif\n\t\tRE_Direct( directLight, geometry, material, reflectedLight );\n\t}\n#endif\n#if ( NUM_RECT_AREA_LIGHTS > 0 ) && defined( RE_Direct_RectArea )\n\tRectAreaLight rectAreaLight;\n\t#pragma unroll_loop\n\tfor ( int i = 0; i < NUM_RECT_AREA_LIGHTS; i ++ ) {\n\t\trectAreaLight = rectAreaLights[ i ];\n\t\tRE_Direct_RectArea( rectAreaLight, geometry, material, reflectedLight );\n\t}\n#endif\n#if defined( RE_IndirectDiffuse )\n\tvec3 irradiance = getAmbientLightIrradiance( ambientLightColor );\n\tirradiance += getLightProbeIrradiance( lightProbe, geometry );\n\t#if ( NUM_HEMI_LIGHTS > 0 )\n\t\t#pragma unroll_loop\n\t\tfor ( int i = 0; i < NUM_HEMI_LIGHTS; i ++ ) {\n\t\t\tirradiance += getHemisphereLightIrradiance( hemisphereLights[ i ], geometry );\n\t\t}\n\t#endif\n#endif\n#if defined( RE_IndirectSpecular )\n\tvec3 radiance = vec3( 0.0 );\n\tvec3 clearCoatRadiance = vec3( 0.0 );\n#endif";`

reverting both lines solves the flicker. reverting 6083 breaks it and reverting 6095 resolves flicker.

**Comment by kpetrow** [comment]
looks like probe light is causing this issue @WestLangley :

Added support for light probes. [#16223](https://github.com/mrdoob/three.js/pull/16223)

**Comment by kpetrow** [comment]
updated fiddle with super flicker:
https://jsfiddle.net/sxjemofg/1/

**Comment by kpetrow** [comment]
RESOLVED

fixed it.  Is this worth committing?  Someone who knows get and three should commit this 👍 @WestLangley 
@Mugen87 


```
vec3 shGetIrradianceAt( in vec3 normal, in vec3 shCoefficients[ 9 ] ) {
	// normal is assumed to have unit length
	float x = normal.x, y = normal.y, z = normal.z;
	// band 0
	vec3 result = shCoefficients[ 0 ] * 0.886227;

      //FIX
      // in webgl 2.0 this could be replaced with  isnan(val)
      if( ! (
              x < 0.0 || x > 0.0 || x == 0.0 ||
              y < 0.0 || y > 0.0 || y == 0.0 ||
              z < 0.0 || z > 0.0 || z == 0.0
          )
        ){ return result; };
      // response from dev who helped fix this:
      // "it is a bug because they should always account for NaN 
      // whether it is intended or not ;)"
      //END FIX

	// band 1
	result += shCoefficients[ 1 ] * 2.0 * 0.511664 * y;
	result += shCoefficients[ 2 ] * 2.0 * 0.511664 * z;
	result += shCoefficients[ 3 ] * 2.0 * 0.511664 * x;
	// band 2
	result += shCoefficients[ 4 ] * 2.0 * 0.429043 * x * y;
	result += shCoefficients[ 5 ] * 2.0 * 0.429043 * y * z;
	result += shCoefficients[ 6 ] * ( 0.743125 * z * z - 0.247708 );
	result += shCoefficients[ 7 ] * 2.0 * 0.429043 * x * z;
	result += shCoefficients[ 8 ] * 0.429043 * ( x * x - y * y );
	return result;
}
```

**Comment by WestLangley** [comment]
> I use PlaneBufferGeometry with null z values to represent unknown elevations(holes). 

You have NaN's in your position data.

You also have NaN's in your vertex normals. Hence their length is undefined.

three.js does not support NaNs in data pushed to the GPU.

**Comment by kpetrow** [comment]
one should always account for NaN whether it is intended or not.  And its a simple fix.  We need this to work for our production and it doesnt harm anything having a check in.   Could we please add, is there any harm?  @WestLangley

**Comment by WestLangley** [comment]
>one should always account for NaN whether it is intended or not.

No, YOU need to account for it in your app and pass valid data.

**Comment by Mugen87** [comment]
Yes, this is something that needs to be fixed on app level.

> three.js does not support NaNs in data pushed to the GPU.

NaN geometry data also corrupt operations on the CPU like intersection tests or the computation of bounding volumes. So again, this is no library bug.

**Comment by kpetrow** [comment]
We have a valid use case for putting NaN's in our data set that as far as I can tell can not be done in any other way, efficiently.  In any real world application dealing with NaN's is just a fact of life and you cant just pass the technical debt onto someone else.

@Mugen87 Bounding Volumes was actually my last post.  It all stems from not handling NaN's properly.  Just a simple test for isNaN would resolve most these.  Why is there such push back and not a desire to resolve this issue?

Are there any suggestions for dealing with real world data that has NaN's?  We have bandied around alpha mapping, but then we increase overhead with the map and need to access the alpha map and the vertex positions.  

Also what if the numbers are very large and overflows?  Will that cause a NaN that might need to be dealt with.

**Comment by Mugen87** [comment]
> Why is there such push back and not a desire to resolve this issue?

`NaN` values is an app level problem from our point of view since the user is in some sense the data producer. Geometric data like position, normal or color data are meant to be numerical. `NaN` data are no numerical data.

Handling `NaN` values is use case specific since proper default values depend on what the application actually does.

This is not only an issue in graphics. When you process huge data in context of KDD and machine learning, data cleanup is one important preparation step before you execute the actual algorithm (which is not responsible for handling missing, undefined or corrupt values),

**Comment by kpetrow** [comment]
so this is a "no" on resolving?  Is there a reason not to other than "we don't support this"?  Its a one line PR.

I guess we will be patching every update from here out.

**Comment by WestLangley** [comment]
three.js does not validate data -- much less accommodate invalid data. That is the app's responsibility.

Also, your patch accommodates your use case, but it does not accommodate an arbitrary use case with invalid data. So, your patch is not a "fix".

**Comment by WestLangley** [comment]
>I guess we will be patching every update from here out.

One way to handle your examples is to add an "invalid" attribute: 0 if valid; 1 if invalid. Then discard fragments for which the interpolated attribute value is non-zero.

**Comment by kpetrow** [comment]
> Also, your patch accommodates your use case, but it does not accommodate an arbitrary use case with invalid data. So, your patch is not a "fix".

 what case would it not fix?  It fixes unknowns in position array from flickering. Could I add a switch to turn off probe lighting?

> One way to handle your examples is to add an "invalid" attribute: 0 if valid; 1 if invalid. Then discard fragments for which the interpolated attribute value is non-zero.

Where woudl you implement this.  Seems alot like an alpha map but culling vertices else where?

**Comment by WestLangley** [comment]
My [suggestion](https://github.com/mrdoob/three.js/issues/17882#issuecomment-551936446) is similar to alpha-testing and would require injecting code into the fragment shader. Without knowing the details of your use case, I can only offer it as a suggestion.

Please use the three.js forum if you need additional help.

**Comment by mrdoob** [comment]
> Just a simple test for isNaN would resolve most these. Why is there such push back and not a desire to resolve this issue?

You may have more luck by doing a PR with that simple test rather than asking us to do it for you.

**Comment by makc** [comment]
@kpetrow,
> two geometries needed... ExplodeModifier

of course you could just create un-indexed buffer geometry to begin with, and not use ExplodeModifier or convert geometries otherwise.

> RESOLVED... Is this worth committing?

well, you know, a bunch of IF-s in the shader that almost noone would need any way... so, probably not.

**Comment by kpetrow** [comment]
> You may have more luck by doing a PR with that "simple test" rather than asking us to do it for you.
yes the debt is too big to resolve, so lets never fix it @mrdoob .  Why not start here?  If I do a PR to fix this issue will get any traction? 

> well, you know, a bunch of IF-s in the shader that almost noone would need any way... so, probably not.
@makc 
Single if.  You also turn off other features like shading, and transparency.  Why not make this new undocumented featured(only example) that effect primary lighting switchable?

> no flicker here at all
@makc 
Well great let me just ship your computer around so everyone can use it. Or even better we will buy everyone a plane ticket and then can come stand in line to use your computer where the software does work.
