### ISSUE TITLE
Opacity does not work with Line2

### ISSUE THREAD

**Issue by rishihahs** [mrdoob/three.js#17899]
##### Description of the problem

The [fat lines implementation](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/lines/Line2.js) doesn't support the `opacity` property. Instead it has to manually be set via `material.uniforms.opacity.value`.

* [(not working) jsfiddle with opacity field](https://jsfiddle.net/2ge5doy1/)
* [(working) jsfiddle with opacity using uniforms](https://jsfiddle.net/Lhf18jr6/)

Using `uniforms.opacity.value` isn't ideal however because it can't be animated. Creating a `NumberKeyframeTrack` with `.material.uniforms.opacity.value` doesn't work as that's not a valid property. Animating opacity requires `.material.opacity`.

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by WestLangley** [comment]
That is by design. See the discussion in #16570.

**Comment by rishihahs** [comment]
Okay, I don't mind the corner artifacts, but I can see why it can be confusing.

I guess a workaround to animating opacity is having an `onBeforeRender` function that takes the opacity value and passes it on to uniforms.

**Comment by WestLangley** [comment]
BTW, what is your use case for fat lines? Are your lines a few pixels wide or very wide?

Would [THREE.MeshLlne](https://www.npmjs.com/package/three.meshline) be a better choice for your use case?

**Comment by rishihahs** [comment]
They're not too wide, and THREE.MeshLine would normally be a good choice. However, unlike fat lines, they don't [yet support vertex colors](https://github.com/spite/THREE.MeshLine/issues/34).
