### ISSUE TITLE
The ShapeGeometry rendered unexpected

### ISSUE THREAD

**Issue by OPY-bbt** [mrdoob/three.js#17891]
##### Description
Add two rectangle paths in scene, the one is clockwise, the other is counterclockwise. when the origin of two paths is set to 0. Threejs will render triangle in the screen. when o variable is set to 0.1(not zero), Threejs will render rectangle, this case is normal.
```
// use counterclockwise wrap rule
path.toShapes(true, false);
```

##### Demo
[Sandbox](https://codesandbox.io/s/xenodochial-bohr-sxfkw)
 
##### Browser
- Chrome

##### OS
- macOS

**Comment by Mugen87** [comment]
> Add two rectangle paths in scene, the one is clockwise, the other is counterclockwise.

Why are you adding path data with different winding order? When using a consistent winding order, the result seems correct:

https://codesandbox.io/s/white-butterfly-c0ecb

**Comment by OPY-bbt** [comment]
This is a simple example of the problem I encountered，the result of changing o variable from 0 to 0.1 is unexpected.
