### ISSUE TITLE
Incomplete type definitions in Nodes

### ISSUE THREAD

**Issue by martinRenou** [mrdoob/three.js#17893]
The type definitions for Node materials seem incomplete. All the shortcuts like `color`, `alpha` etc are missing.

**Comment by makc** [comment]
+1

ShadowMaterial params are declared as ShaderMaterialParams, so passing the color there triggers the typescript

**Comment by Mugen87** [comment]
Oh dear, the type declaration file for `ShadowMaterial` was totally messed up. Let's fix this...

**Comment by Mugen87** [comment]
@martinRenou What do you mean with shortcuts? Can you show the respective JS code, please?

**Comment by martinRenou** [comment]
Sorry, I was not super clear, and thanks for taking the time for opening a PR for this!

So there seem to be a "shortcut" logic in the code here: https://github.com/mrdoob/three.js/blob/master/examples/jsm/nodes/materials/StandardNodeMaterial.js#L22-L41

And my understanding is that it dynamically adds getter and setters to the Material prototype: https://github.com/mrdoob/three.js/blob/22ed6755399fa180ede84bf18ff6cea0ad66f6c0/examples/jsm/nodes/core/NodeUtils.js#L11-L27

This might be the case for other classes in the `nodes` examples. I could come up with a PR myself fixing those.

**Comment by Mugen87** [comment]
> I could come up with a PR myself fixing those.

That would be great! /cc @sunag

**Comment by sunag** [comment]
> That would be great!

+1
