### ISSUE TITLE
HDR environment & incorrect roughness 

### ISSUE THREAD

**Issue by ViliusLuneckas** [mrdoob/three.js#17911]
##### Description of the problem

HDR environment loaded using `PMREMGenerator` makes semi-rough (0.2-0.3) materials apear too shiny, compared to http://github.khronos.org/glTF-Sample-Viewer/, https://www.babylonjs.com or Unity. 

On the left, model rendered in Unity viewer. On the right using latest threejs, PMREMGenerator, GLTFLoader and HDR map: 
![image (34)](https://user-images.githubusercontent.com/217922/68626194-75e12c80-04e3-11ea-8e9a-cf86b85d3bbe.png)

Also, that visible on the simple metal roughness spheres test: 
<img width="548" alt="test" src="https://user-images.githubusercontent.com/217922/68626329-d4a6a600-04e3-11ea-87d4-8f9cdf3e336b.png">

I found couples of PRs (https://github.com/GoogleWebComponents/model-viewer/pull/684, https://github.com/GoogleWebComponents/model-viewer/pull/710) on model-viewer addressing similar problems and drastically improving `PMREMGenerator`. Meanwhile original code in this repo is 9 months old.

Previous, probably related issue – https://github.com/mrdoob/three.js/issues/13107

Has anyone run into the same problem?

##### Three.js version

- [x] r110

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

- Intel Iris Plus Graphics 655

**Comment by mrdoob** [comment]
It is definitely a known issue. And the hope was that @elalish was going to upstream the changes he did in model-viewer at some point.

@elalish do you have any rough idea of a when you'll be able to do it?

**Comment by elalish** [comment]
Yes, I just finished another significant refactor of that work: https://github.com/GoogleWebComponents/model-viewer/pull/880
Once that lands, I plan to start upstreaming it here.
