### ISSUE TITLE
MeshStandardMaterial iOS rendering issues

### ISSUE THREAD

**Issue by jocabola** [mrdoob/three.js#17918]
Hi there,

I think I might have found a bug on iOS. I have a `MeshStandardMaterial` working with a texture for its roughness(green), metallic(blue) and AO(red) channels...

In my case AO is not used, so red channel is empty. This causes iOS to render incorrectly or at least completely different than any other platform including Safari on OS X, Android, Chrome, etc. The resulting rendering on iOS is completely dark. If I remove the aoMap linkage to texture the render is then fixed, but shouldn't it be ignored like in other platforms?

Unfortunately I can't share this particular example right now cause it is for a commercial project under development but can try to put another example online if you can confirm this is a **bug**.

Many thanks!

**Comment by jocabola** [comment]
Also let me add that my PNG was 8-bit indexed (not showing RGB channels in PhotoShop), just in case I re-exported as 24 bit (with Red channel being properly displayed in black) and the issue remains.

Tested on iPhone 6 iOS 10.3.3 and iPhone XR iOS 13.1.2

**Comment by sciecode** [comment]
Hello @jocabola, it would be useful if you could provide an [jsfiddle example](https://jsfiddle.net/hyok6tvj). Doesn't need to be anything complex, just enough for us to replicate this behavior.

**Comment by Mugen87** [comment]
Can you please run all texture related test from the WebGL conformance test suite on one of your problematic devices?

https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html

Just enable the checkbox `all/conformance/textures` end then hit the respective run button. It would be interesting to know if one or more tests fail.

**Comment by jocabola** [comment]
Hello,

Thanks a lot for your feedback. I have been isolating a simpler example and I wasn't able to longer reproduce this behaviour...

After digging a bit further in, turns out that it might be related to the texture I was using since this had an alpha channel which is probably messing with the RGB channels in iOS somehow. **If I don't have a transparent background the behaviour in all platforms is identical** but if there is an alpha channel (even not affecting the rendered surface) things go funky on iOS. Getting very different results. Perhaps this is a known behaviour already. Nevertheless it will be a different bug then and I should do a bit more testing before posting a new issue. Also, it makes no sense to have transparent pixels on a PBR texture for roughness/metalness/AO.

Thanks and sorry for the misleading initial post!

**Comment by mrdoob** [comment]
Is it a PNG and maybe iOS applies premultiplied alpha in a different way than the rest?

**Comment by jocabola** [comment]
Yes, it is a PNG and it does look like it could be a premultiplied alpha issue.

**Comment by mrdoob** [comment]
If you can create a jsfiddle that shows the issue we can ping Apple.

**Comment by WestLangley** [comment]
>In my case AO is not used, so red channel is empty.

What does "empty" mean to you?

>If I remove the aoMap linkage to texture the render is then fixed

So your mesh has an `AOMap` but the AO data is "empty"? What you mean by that?

**Comment by mrdoob** [comment]
I guess the red channel was... "white"? And then the alpha messed with the values?

**Comment by jocabola** [comment]
Hi,

I didn't have access to my testing iPhone till today and I had another look. First of all, @WestLangley had a point here cause I had black on the red channel which is supposed to darken (occlude) the surface obviously. The fact that iOS was behaving differently than all the rest, I assumed it was broken there and didn't think straight! So, I would say iOS is consistent in its behaviour but not on all the other platforms I could test (all major browsers in OS X with an intel GPU & latest Android on a Pixel 3).

**Situation is the following:**
1. I have a texture with transparent background with roughness(green) and metallic(blue) information but no red at all (black AO).
2. Then all the pixels where there is green and blue information, is rendered as if the red channel would be white. The remaining pixels are rendered correctly (occluded).

Behaviour on Desktop (seems faulty):
![Desktop Behaviour](https://tmp.jocabola.com/threejs-pbr-texturing-transparency/captures/desktop.gif)

Behaviour on iPhone (consistent, seems correct):
![iPhone](https://tmp.jocabola.com/threejs-pbr-texturing-transparency/captures/iphone.gif)

**Textures Used**
[Color map](https://tmp.jocabola.com/threejs-pbr-texturing-transparency/textures/color.png)
[roughness/metallness/ao map with transparency](https://tmp.jocabola.com/threejs-pbr-texturing-transparency/textures/pbr.png)
[roughness/metallness/ao map without transparency](https://tmp.jocabola.com/threejs-pbr-texturing-transparency/textures/pbr2.png)
[env map](https://tmp.jocabola.com/threejs-pbr-texturing-transparency/textures/env.png)

**LINK**
[https://tmp.jocabola.com/threejs-pbr-texturing-transparency/](https://tmp.jocabola.com/threejs-pbr-texturing-transparency/)

Anyway, as mentioned earlier, it makes no sense to have transparency in this kind of textures...

Thanks!

**Comment by mrdoob** [comment]
Just to confirm...

When the texture is not transparent it behaves the same in all platforms/devices you have tested, right?

**Comment by jocabola** [comment]
Correct! It is only with transparency when it keeps consistent on iOS but looks incorrect anywhere else. The link I shared allows to switch textures and activate/deactivate aoMap linkage...
