### ISSUE TITLE
three.js/src/objects/InstancedMesh.d.ts has an incorrect import?

### ISSUE THREAD

**Issue by Antonio-Sorrentini** [mrdoob/three.js#17924]
The 4th line in the file
three.js/src/objects/InstancedMesh.d.ts

reads:

import { BufferAttribute } from './../core/BufferAttribute.js';

is this correct?
shouldn't it be 

import { BufferAttribute } from './../core/BufferAttribute';

Thanks

**Comment by Mugen87** [comment]
Your totally right! Should be okay now.

**Comment by Antonio-Sorrentini** [comment]
Thanks @Mugen87 for the very quick fix.
I think the same problem (import of .js files) is in these other files (and only these, now I checked them all):

Three.js\src\loaders\ImageBitmapLoader.d.ts
Three.js\src\math\SphericalHarmonics3.d.ts
Three.js\src\renderers\webgl\WebGLTextures.d.ts

**Comment by Mugen87** [comment]
Thanks for reporting this! 🙌

**Comment by Antonio-Sorrentini** [comment]
You are welcome, and compliments for this incredibly excellent software. 😋
