### ISSUE TITLE
LoadingManager.getHandler does not work half the time if a regex with g flag is passed

### ISSUE THREAD

**Issue by SBRK** [mrdoob/three.js#17920]
If adding a handler with a regex that has the `g` flag, the `regex.test` in `getHandler` will return null every other time.
I think `string.match` should be used rather than `regex.test` to avoid any side effect like this

**Comment by donmccurdy** [comment]
Could you share an example to reproduce this issue?

**Comment by SBRK** [comment]
Here you go @donmccurdy 
https://jsfiddle.net/qkwx4Lg1/

**Comment by makc** [comment]
so basically this:
![Screen Shot 2019-11-14 at 13 12 35 ](https://user-images.githubusercontent.com/242577/68856309-7e528680-06e0-11ea-8cb1-2dfeab60b7e7.png)

**Comment by makc** [comment]
apparently you can do this to keep using `test()`:
![Screen Shot 2019-11-14 at 13 20 01 ](https://user-images.githubusercontent.com/242577/68856744-8eb73100-06e1-11ea-83f5-46db149a69a1.png)

**Comment by Mugen87** [comment]
> If adding a handler with a regex that has the g flag

May I ask, why are you adding the `g` flag in the first place? Normally the regex applied to `addHandler()` should always have this structure: `/\.tga$/i`.

**Comment by SBRK** [comment]
> > If adding a handler with a regex that has the g flag
> 
> May I ask, why are you adding the `g` flag in the first place? Normally the regex applied to `addHandler()` should always have this structure: `/\.tga$/i`.

I just took the habit to add g, and didn't think too much about it. Nethertheless, calls to `getHandler` should be consistant

**Comment by Mugen87** [comment]
@makc Using 'lastIndex` seems like an appropriate solution 👍
