### ISSUE TITLE
TypeScript return type for Plane.intersectLine should be Vector3 | undefined

### ISSUE THREAD

**Issue by bergwerf** [mrdoob/three.js#17931]
Currently `Plane.intersectLine` has return type `Vector3`: https://github.com/mrdoob/three.js/blob/22ed6755399fa180ede84bf18ff6cea0ad66f6c0/src/math/Plane.d.ts#L27. But the function returns undefined if there is no intersection. So the return type should be `Vector3 | undefined` (sorry I was too lazy to create a PR).

**Comment by Mugen87** [comment]
@linbingquan Do you want to fix this? 😇

**Comment by bergwerf** [comment]
Same issue but in this case with null: https://github.com/mrdoob/three.js/blob/22ed6755399fa180ede84bf18ff6cea0ad66f6c0/src/core/BufferGeometry.d.ts#L36

(I bet there are more).

**Comment by linbingquan** [comment]
I created a PR https://github.com/mrdoob/three.js/pull/17934
