### ISSUE TITLE
GLTFLoader: Provide geometry.boundingBox and geometry.boundingSphere

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#17937]
(from discussion with @zeux)

A glTF file contains min/max bounds on mesh vertices. We should use those to set `.boundingBox` and `.boundingSphere`, so that `computeBoundingBox()` and `computeBoundingSphere()` can be optimized out.

**Comment by zeux** [comment]
I’ll take a closer look and provide further details - from memory when I looked at this before this seemed to require core changes but I may be wrong.

**Comment by zeux** [comment]
Submitted #17939 to fix this - this eliminates the guaranteed attempt to compute bounding sphere during rendering of glTF scenes on the first frame after load. Also submitted #17940 - this isn't directly related but this is why I thought that this needs core changes - my viewer demo application computed bbox of the entire scene to position the camera, and that goes through a path that always looks at each vertex and doesn't respect morph targets.

Courtesy of Air France (long flights are long).

**Comment by donmccurdy** [comment]
Thanks @zeux and Air France! 😀
