### ISSUE TITLE
can we get opacity on default uniforms in ShaderMaterial?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#17947]
I mean, since it is defined in the Material any way? Right now I have to add `uniform float opacity;` in the shader and then `opacity: { get value() { return mesh.material.opacity } }` in the material.uniforms myself

**Comment by Mugen87** [comment]
So you mean an enhancement of the built-in uniforms of [WebGLProgram](https://threejs.org/docs/index.html#api/en/renderers/webgl/WebGLProgram)?

**Comment by makc** [comment]
@Mugen87 I guess? I think right now this uniform is only added with some shader chunk, but it could be conditional uniform there

**Comment by Mugen87** [comment]
I'm not sure about this feature request (sry). There are no conditional uniforms so far (only attributes). Besides, users could request to do the same for other (common) material properties as well.

It's somewhat a design decision so I'm curious how @mrdoob feels about this request.

**Comment by makc** [comment]
> There are no conditional uniforms so far (only attributes)

yes, same thing as with morphing. you would thing setting material.morphTargets = true makes all the stuff you want available in your shader, but no, that is only half of the story. I guess this will remain like this for another 5 years

**Comment by maccesch** [comment]
Yeah I need this too. And like @makc said it's an attribute on `Material` anyway.
