### ISSUE TITLE
Audio not playing on ios13

### ISSUE THREAD

**Issue by pikilipita** [mrdoob/three.js#17948]
it looks like on all our projects ( we're using threejs rev 105), audio files are not played anymore on ios13 ( tested on phone 11 ).
They are all played after a user input, and they work fine on android browsers.

Even this threejs example is silent on ios13:
https://threejs.org/examples/#webaudio_sandbox

I checked loading & playing an audio file in simple javascrtip, outside of threejs, it works

Anyone has the same issue?

**Comment by Mugen87** [comment]
> Even this threejs example is silent on ios13:

It does not work because the example uses `ogg` which is unfortunately not supported by Safari:

https://caniuse.com/#search=ogg

As long as you request for a user interaction audio on iOS should work.

**Comment by mrdoob** [comment]
We could probably just use mp3 now (all the mp3 patents expired in 2017).
I assume Firefox can now play it without "hacks"?

**Comment by Mugen87** [comment]
> I assume Firefox can now play it without "hacks"?

Not sure about that. I remember some issue with Linux-based operating systems 🤔

**Comment by pikilipita** [comment]
after more testing, I'm now almost sure playing media on Safari mobile has again changed.

This used to work:
- user touch a button on the page
- from this moment it is possible to start playback of media ( audio or video ) at any time

What only works now:
- user touch a button on the page
- starting a media playback is only possible at the exact same time the touch has been made, not later on on the webpage life.

Or in other words, you can't get the user to press a button, and 5 seconds later, start an audio or a video, that won't work :/

--
@MrDoob, I can confirm playing mp3 files works fine on Firefox Android
