### ISSUE TITLE
MeshPhysicalMaterial reflectivity should not affect material brightness

### ISSUE THREAD

**Issue by Ben-Mack** [mrdoob/three.js#17944]
This can be observed most clearly when the MeshPhysicalMaterial is fully rough (roughness 1, metalness 0, with envMap), increasing `reflectivity` will brighten up the material. 
This behaviour should not happened.

Using 3ds Max as reference, changing IOR of Max's Physical Material or VRayMtl does not affecting the overall brightness:

VRayMtl at different IOR: (upper row's glossiness=0, lower row's glossiness=1)
![vraymtl-combined](https://user-images.githubusercontent.com/6309393/69003384-a7b72080-0933-11ea-8f6d-c9083cee1915.png)
Max's Physical material at different IOR : (upper row's roughness=1, lower row's roughness=0)
![physical material combined](https://user-images.githubusercontent.com/6309393/69003314-0d0a1200-0932-11ea-987a-38ba8ddc59f2.png)
(metalness is 0 in all above images)

Three.js fiddle to demonstrate this problem (click +1 button to see the material brighten up as reflectivity increased): https://jsfiddle.net/u1k7324c/

**Comment by WestLangley** [comment]
`.reflectivity` takes values between 0 and 1. The default is 0.5.

In your fiddle, you are setting the values to 1, 2, 3, ...
