### ISSUE TITLE
WebVR: navigator.xr.isSessionSupported is not a function in Chrome.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#17945]
##### Description of the problem

I open the example `webvr_6dof_panorama.html` in Chrome, it has an error like:

```js
Uncaught TypeError: navigator.xr.isSessionSupported is not a function
```
![图片](https://user-images.githubusercontent.com/23699926/69008882-7ae22800-098a-11ea-8d20-3e03f5e3be9f.png)

I found mrdoob removed the condition in https://github.com/mrdoob/three.js/commit/78a51f5eb960d0e7f903a96a219724a3df6106f0, I want to fix it by myself, but I don't know how to fix it, because the Firefox and Edge is OK, maybe I miss something.

https://github.com/mrdoob/three.js/blob/fb405ea69e96a8bbbfb18641f606f4e67be935f5/examples/jsm/vr/WebVR.js#L174-L181

##### Three.js version

- [x] Dev
- [ ] r110
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome 77 or 78
- [ ] Firefox 71
- [ ] Edge

##### OS

- [ ] All of them
- [x] Windows 10
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
We only support the last version of the WebXR API and Chrome 79+ uses `isSessionSupported`. Chrome 79 is now in Beta and should land as stable Dec 10.

**Comment by linbingquan** [comment]
> We only support the last version of the WebXR API and Chrome 79+ uses `isSessionSupported`. Chrome 79 is now in Beta and should land as stable Dec 10.

Thanks.
