### ISSUE TITLE
Wildly incorrect values returned by Ray.at() and Ray.intersectSphere()

### ISSUE THREAD

**Issue by JoshuaCWebDeveloper** [mrdoob/three.js#17941]
##### Description of the problem

The point calculated by `Ray.at()` seems very off. I'm assuming that distance `t`  refers to a length in pixels, and therefore, a `t` value of 100 on the ray (255, 255, 255) --> (0, 0, 255) would result in a point somewhere between the origin and the direction, but instead it results in the point (255, 255, 25755).

Maybe I don't understand what `Ray.at()` is supposed to do? If that is the case then `Ray.intersectSphere()` is making the same mistake as I am. For a sphere with a radius of ~220 and a center at (255, 255, 255), the calculated intersection of the above ray (with an origin inside the sphere) and the sphere is (255, 255, 25755), which is quite a ways away from the sphere. :)

The below example can also be found at https://codepen.io/JoshuaCWebDeveloper/pen/MWWzxGj.
```javascript
console.log(THREE.REVISION);

var ray = new THREE.Ray(
    new THREE.Vector3(255, 255, 255),
    new THREE.Vector3(0, 0, 255)
);

var atPoint = new THREE.Vector3();
ray.at(100, atPoint);

console.log("atPoint:", atPoint);     //{x: 255, y: 255, z: 25755}

var sphere = new THREE.Sphere(
    new THREE.Vector3(255, 255, 255),
    220.83
);

var intersect = new THREE.Vector3();
ray.intersectSphere(sphere, intersect);

console.log("intersect:", intersect); //{x: 255, y: 255, z: 56566.65}
```
##### Three.js version

- [ ] Dev
- [ ] r110 (Not on CDNJS)
- [x] r109
- [x] r99

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox (Not tested)
- [ ] Internet Explorer (Not tested)
- [x] Opera

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS (Not tested)
- [ ] Linux (Not tested)
- [ ] Android (Not tested)
- [ ] iOS (Not tested)

##### Hardware Requirements (graphics card, VR Device, ...)
None

**Comment by lojjic** [comment]
I suspect this is due to your ray's direction vector not being normalized. From the [Ray docs](https://threejs.org/docs/#api/en/math/Ray):

> direction - Vector3 The direction of the Ray. **This must be normalized (with Vector3.normalize) for the methods to operate properly.**

Be sure you're not interpreting the ray's two input values as "pointA --> pointB", that's not correct, it's more like "pointA and direction from pointA".

**Comment by JoshuaCWebDeveloper** [comment]
Thank you @lojjic. Yes, my mistake was misreading the docs as saying that the direction was a point that the ray passes through, rather than the direction in fact being the unit vector of the ray. After changing my definition of the ray to the following, I get the expected results:
```javascript
var origin = new THREE.Vector3(255, 255, 255);
var direction = new THREE.Vector3(0, 0, 0);
direction.subVectors(new THREE.Vector3(0, 0, 255), origin).normalize();

console.log("origin:", origin, "direction:", direction);

var ray = new THREE.Ray(
    origin,
    direction
);
```

**Comment by WestLangley** [comment]
@JoshuaCWebDeveloper Please use the three.js forum if you need additional help.
