### ISSUE TITLE
Update HelioWebXRPolyfill

### ISSUE THREAD

**Issue by yhuangbrowser** [mrdoob/three.js#17964]
##### Description of the problem

HelioWebXRPolyfill.js needs to be updated to support Helio 0.98.00, and remove polyfill for Helio 0.97.00.

##### Three.js version

- [x] Dev
- [ ] r110

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Helio

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [x] Lumin OS
##### Hardware Requirements (graphics card, VR Device, ...)
Magic Leap One

**Comment by Mugen87** [comment]
In the meanwhile, is `HelioWebXRPolyfill` still required?

**Comment by mrdoob** [comment]
I think I would remove it 👍

**Comment by mrdoob** [comment]
Done. https://github.com/mrdoob/three.js/commit/f60a0eb7c8192106930631d07727c178c95aac66
