### ISSUE TITLE
How do I play the specified frame animation in fbx ？

### ISSUE THREAD

**Issue by i-fuyun** [mrdoob/three.js#17966]
##### Description of the problem
How do I play the specified frame animation ？
The fbx have 100 frames.
Like this from 10 to 25 frame.
![image](https://user-images.githubusercontent.com/5111701/69224557-bd3c7c80-0bb7-11ea-9841-56ec75a45a0e.png)

this is my now code
![image](https://user-images.githubusercontent.com/5111701/69224675-f117a200-0bb7-11ea-98df-4b94ddccdb0e.png)

##### Three.js version

- [x] Dev
- [x] r110
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
