### ISSUE TITLE
Animation.optimize creates problems when coupled with GLTFLoader

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#17963]
GLTF loader produced a skinned mesh. 
Some tracks in an animation share buffers (Float32Array).
Animation optimization method performs surgery on said buffers in-place. This would be "OK" if it was the entire track being shared, but when a `KeyframeTrack.times` is being shared, and optimizer decides to optimize one of the sharing tracks based on the key values - you end up with problems. 

Here's the offending part:
https://github.com/mrdoob/three.js/blob/dc0d21fcb7b9d8aa14493ba427727adbafee51a7/src/animation/KeyframeTrack.js#L350-L439

Took me a while to catch. A fix is rather easy - copy the buffer data before doing surgery.
```js

function copyArray(array) {
    return new array.constructor(array);
}

....
//Start of "optimize" method:
 var times = copyArray(track.times),
        values = copyArray(track.values),
```

**Comment by donmccurdy** [comment]
Probably the cause of https://github.com/mrdoob/three.js/issues/17180. I'm inclined to say that the arrays should be copied when `optimize()` is called, and should not be done in advance by GLTFLoader, but I'm not totally sure. :/

**Comment by donmccurdy** [comment]
Thanks for investigating this, @Usnul!
