### ISSUE TITLE
VSMShadowMap ignores "castShadow" flag

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#17972]
After some debugging in my application, I came across a peculiar bug. If you set `castShadow = false` on a `Mesh` and use `VSMShadowMap` - the shadow is still being drawn. If you use  `PCFSoftShadowMap` - the shadow is not rendered, as expected.

**Comment by arpu** [comment]
from the docs
```
VSMShadowMap filters shadow maps using the Variance Shadow Map (VSM) algorithm. When using VSMShadowMap all shadow receivers will also cast shadows.

```
https://threejs.org/docs/#api/en/constants/Renderer

**Comment by Usnul** [comment]
Thanks @arpu , Interesting, maybe there should be a warning of some kind. Seems really like a bug otherwise.

**Comment by WestLangley** [comment]
Duplicate of #17473.
