### ISSUE TITLE
DRACOLoader: exposing _initDecoder as public method

### ISSUE THREAD

**Issue by TyLindberg** [mrdoob/three.js#17970]
Previously one could call `THREE.DRACOLoader.getDecoderModule()` to preload the DRACO libraries, but there is no respective public instance method on the current DRACOLoader module. However, the private method `_initDecoder` seems to accomplish preloading. Would it be possible to make this method public or make a public wrapper for it?

https://github.com/mrdoob/three.js/blob/219e3c1bc24163e2c31ab6f5cf4bb66f81b689bc/examples/jsm/loaders/DRACOLoader.js#L230

**Comment by donmccurdy** [comment]
I think that would be a good addition, yes. The method can just be renamed. 

I'm having a hard time deciding what to name it. Using "init" or "initialize" sounds like it should only be called once, when it's actually called each time `load` is called. Maybe just `.preload()`?

**Comment by TyLindberg** [comment]
Yeah, `.preload()` seems like a good name to me. Want me to tackle changing that and opening up a PR or are you planning to make that change?

**Comment by donmccurdy** [comment]
Please do! :)

**Comment by TyLindberg** [comment]
Implemented in #17983.

**Comment by donmccurdy** [comment]
Thanks @TyLindberg!
