### ISSUE TITLE
Support loading GLTF 2.0 files with custom shaders using 'KHR_techniques_webgl' specification.

### ISSUE THREAD

**Issue by J-Rojas** [mrdoob/three.js#17977]
It would be helpful to import custom shader code through GLTF files.

The draft specification for KHR_techniques_webgl is available here:

https://github.com/KhronosGroup/glTF/blob/c1c12bd100e88ff468ccef1cb88cfbec56a69af2/extensions/2.0/Khronos/KHR_techniques_webgl/README.md

It is currently used by [Cesium](https://github.com/AnalyticalGraphicsInc/cesium/blob/d26ccfea38dcf4623cf5da3faca141913c64cfe1/Source/Scene/processModelMaterialsCommon.js) and [Hilo3d (Alibaba's webgl engine)](https://github.com/hiloteam/Hilo3d/blob/master/src/loader/GLTFExtensions.js)

**Comment by takahirox** [comment]
I'm interested in supporting it. Actually I tried before but I gave up due to no glTF example model including KHR_techniques_extension. Is there any good model including it for the test now?

**Comment by donmccurdy** [comment]
> The draft specification for KHR_techniques_webgl is available...

This draft hasn't been updated in a while. I think that Cesium implementation might only be glTF 1.0, but I'm not sure. @ggetz do you know?

> is there any good model including it for the test now?

Afraid not.

Unfortunately I would vote against merging support for `KHR_techniques_webgl` into three.js unless it's really going to be approved and supported by more tools. I'm not sure whether that will be the case. If we were able to make GLTFLoader extensible enough that this could be done without modifying the loader (https://github.com/mrdoob/three.js/issues/11682) that could help users to work around it and use the draft extension for their own projects if they wanted to.

**Comment by takahirox** [comment]
>  If we were able to make GLTFLoader extensible enough that this could be done without modifying the loader (#11682) that could help users to work around it and use the draft extension for their own projects if they wanted to.

Agreed with this.

**Comment by J-Rojas** [comment]
> 
> This draft hasn't been updated in a while. I think that Cesium implementation might only be glTF 1.0, but I'm not sure. @ggetz do you know?

If you visit the spec README, it states that it's written against glTF 2.0.

> 
> > is there any good model including it for the test now?
> 

Hilo3d has a working example here from on the Khronos Group spec.

[SampleTechniques model](https://github.com/hiloteam/Hilo3d/tree/master/examples/models/SampleTechniques)
[Viewer Demo with custom shader](https://hiloteam.github.io/Hilo3d/examples/loader/glTF_loader.html?model=SampleTechniques)

**Comment by donmccurdy** [comment]
I thought the Cesium implementation had just implemented the glTF 1.0 version, but you're right it's 2.0 as well. The sample is good to know about too, thanks!

It would be awesome if someone wanted to implement support in THREE.GLTFLoader, but all the same, I would prefer not to merge support for draft extensions unless they are nearer to approval than this one appears to be.

**Comment by donmccurdy** [comment]
I'm closing this issue just to avoid any confusion with the "Feature Request" label, since we're not ready to accept this as a pull request unless the draft extension is approved or near approval. I think there are some other approaches to this worth exploring, too.
