### ISSUE TITLE
module not found Uncaught TypeError: Failed to resolve module specifier "three.module.js". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by lmchun** [mrdoob/three.js#17979]
I forked the three.js from the github three js master and I am trying to make a local copy of it.

I tried opening an example in the master and I am getting this error:

Uncaught TypeError: Failed to resolve module specifier "three.module.js". Relative references must start with either "/", "./", or "../".

I have tried to host it on a local server, changed the directory, installed an npm, and hosted it on my github to see if it would work but all getting the same error. 

I am working off of the example/web_vr_ballshooter.html 
from the master.

help please;-;

<img width="954" alt="Screen Shot 2019-11-21 at 1 49 27 PM" src="https://user-images.githubusercontent.com/29472755/69379690-c6842280-0c65-11ea-9e30-b315d4e9d863.png">

**Comment by donmccurdy** [comment]
Please use the forums (https://discourse.threejs.org/) for help topics. Thanks!
