### ISSUE TITLE
NURBS

### ISSUE THREAD

**Issue by MasseGuillaume** [mrdoob/three.js#1799]
I have some spare time.

@mrdoob is it something you want in three.js ?

On CPU:
http://cgit.freedesktop.org/mesa/mesa/tree/src/glu/sgi/libnurbs/interface/glinterface.cc?h=8.0 ( restrictive license )
https://svn.blender.org/svnroot/bf-blender/trunk/blender/source/blender/blenkernel/intern/curve.c ( GPL )
http://www.nar-associates.com/nurbs/c_code.html ( copyright, non commercial reuse ok )

On GPU:
http://kingkong.me.berkeley.edu/~adarsh/Papers/CAD09.pdf
10 X faster
but high setup cost

**Comment by Tectract** [comment]
Hi guys, I'm also interested in NURBS modeling, and I have a little pet C++11 project I've been working on called OpenNURBS, I have it stamped with the Mozilla License. Specifically the features I'm working on require curve and surface offsetting and extrusion, and filleting, and finally sub-surface collision detection and minimum distance computation. It's part of a Bio-Fractal Tree project, with the goal of creating intertwining, non-overlapping, space-filling "bio-fractal" tree geometries and meshes.

I'm interested in possible incorporating code or helping translate algorithms back and forth between javascript and C++11/14 for curve / surface offsetting, extrusion, filleting, collision detection, and minimal distance computation. If there are other FOSS NURBS project people that want to just collaborate on the C++ side also, I'd like to look at that, @sntx. OpenNURBS will have it's own GUI, but I'd also like to support outputting geometries / meshes into a format that could be loaded easily into Three.js / webGL easily also. I also have some crystal geometry generators that I'd like to see repurposed for OpenGl / webGL, if I can figure out an easy way to translate these old MATLAB programs into c++ / javascript and have an easy way to output to Three.js / webGL.

**Comment by dmtaub** [comment]
Just as a point of reference
https://github.com/pboyer/verb
