### ISSUE TITLE
Line2.material.clippingPlanes = [plane] 

### ISSUE THREAD

**Issue by 389652405** [mrdoob/three.js#17998]
Line2.material.clippingPlanes = [plane] ;
LineSegments2.material.clippingPlanes = [plane] ;
this setting is invalid;
other material is ok

**Comment by Mugen87** [comment]
> this setting is invalid;

What do you mean by that? Please invest more time when reporting issues at github. You should always describe the actual and expected result in detail. Besides, it's best to provide a [live demo](https://jsfiddle.net/f2Lommf5/) or git repository which demonstrates the problem.

**Comment by Mugen87** [comment]
Closing. The issue can be reopened when more information are provided.

**Comment by 389652405** [comment]
THREE.Line2 and THREE.LineSegments2 Cannot be cropped by clippingPlanes;
http://drm.gitee.io/clippaln/webgl_clipping.html
