### ISSUE TITLE
How do I convert the model’s 3d local coordinates to global and then to screen coordinates for the 2d div.

### ISSUE THREAD

**Issue by i-fuyun** [mrdoob/three.js#17996]
##### Description of the problem

How do I convert the model's 3d local coordinates to global
and then to screen coordinates  for the 2d div.
![image|690x213](https://aws1.discourse-cdn.com/standard17/uploads/threejs/original/2X/1/12e2d0d5de3459b6aab269a73e97f1e43f34198f.png) 
![image|690x225](https://aws1.discourse-cdn.com/standard17/uploads/threejs/original/2X/2/20dbc1a5fe8a6ca634ce09b00f85818441bf8e0f.png) 

target is a mesh.

This is the now result, have a large discrepancy.
![image|690x462](https://aws1.discourse-cdn.com/standard17/uploads/threejs/original/2X/5/53c0175b392225c239858ef21b06596862f6c343.jpeg)

https://discourse.threejs.org/t/how-do-i-convert-the-models-local-coordinates-to-global-and-then-to-screen-coordinates/11021

##### Three.js version

- [x] Dev
- [x] r110
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
This is not a help site. Please do not ask help questions here.

**Comment by mrdoob** [comment]
Use the `CSS2DRenderer`:
https://threejs.org/examples/?q=css2d#css2d_label

**Comment by i-fuyun** [comment]
> You can use the `CSS2DRenderer`:
> https://threejs.org/examples/?q=css2d#css2d_label

I solves this problem with use https://threejs.org/examples/?q=css2d#css2d_label
Thank you very much.
