### ISSUE TITLE
Application of NormalMatrix to BufferAttribute is not correct.

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#18001]
The `normalMatrix` is not necessarily length-preserving.

`BufferGeometry.applyMatrix()` uses this patten:

```js
normalMatrix.applyToBufferAttribute( attribute );
```

This pattern leaves the normals unnormalized.

`FBXLoader` also uses the pattern.

**Comment by makc** [comment]
> The normalMatrix is not necessarily length-preserving.

why is that, @WestLangley ?

**Comment by WestLangley** [comment]
@makc A normal matrix will not preserve length if the transform from which it is computed has a scale component.

**Comment by makc** [comment]
@WestLangley so it is computed just by 0-ing translation?

**Comment by WestLangley** [comment]
@makc It is not. Googling "transforming normal vectors" may be helpful.
