### ISSUE TITLE
Effect Composer fails when used in conjunction with AR.js

### ISSUE THREAD

**Issue by ElevenAM** [mrdoob/three.js#18002]
##### Description of the problem

I believe that there is a bug where EffectComposer doesn't properly apply when integrating with an AR implementation. Without AR, the EffectComposer runs as expected and we get a nice bloom/ glow effect but once we apply EffectComposer to AR, we lose the filter effect entirely. 

I don't think that this is an implementation issue as in the first example image, I see two layers, one the camera and one the THREE canvas scene and by applying some opacity, I can see the EffectComposer working as expected. 

It is only when I run finalComposer.render(); where finalComposer is simply a new EffectComposer that I do get the scenes to overlay BUT, I lose the effects competely.

Images of bug
https://imgur.com/a/q51702p

Example: 
https://jsfiddle.net/0k7hm2cb/

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> Without AR, the EffectComposer runs as expected and we get a nice bloom/ glow effect but once we apply EffectComposer to AR, we lose the filter effect entirely.

Sounds like an issue in AR.js, no? In general, we can't ensure that third-party code plays nicely with all `three.js` components. As long as you can't demonstrate a bug in `EffectComposer`, it's better to close the issue and report an issue to `AR.js` instead.
