### ISSUE TITLE
THREE.Line2 and THREE.LineSegments2 Cannot be cropped by clippingPlanes;

### ISSUE THREAD

**Issue by 389652405** [mrdoob/three.js#18009]
THREE.Line2 and THREE.LineSegments2 Cannot be cropped by clippingPlanes;
http://drm.gitee.io/clippaln/webgl_clipping.html

**Comment by Mugen87** [comment]
Try setting `material.clipping` of the line material to `true`.

**Comment by WestLangley** [comment]
Fat lines support clipping -- both local and global. Set `material.clipping = true;`

>It should be okay if LineMaterial sets this property always to true.

`ShaderMaterial` requires that `.clipping` be set to `true` to use user-defined clipping planes. `LineMaterial` extends `ShaderMaterial`.

If Fat lines are promoted into the library as a built-in material, then we can change the behavior.

**Comment by Mugen87** [comment]
I just wanna say that there is no problem if the default value would be `true`, even if no clipping planes are used. In this case, @389652405 would never run into this issue.

**Comment by WestLangley** [comment]
I prefer to adhere to the convention for `ShaderMaterial`, but we can make this change if you want. 

It just means users need to set `.clipping`  to `false` if they don't want the lines clipped by the clipping planes.

**Comment by 389652405** [comment]
Thank you very much.
