### ISSUE TITLE
It must be targetLine

### ISSUE THREAD

**Issue by aline-coasta** [mrdoob/three.js#18014]
https://github.com/mrdoob/three.js/blob/0998172670b1a385bacba16cbd7145aa1aa662bd/src/helpers/DirectionalLightHelper.d.ts#L17

**Comment by Mugen87** [comment]
You're right! Do you want to make a PR with the fix?

**Comment by aline-coasta** [comment]
Sorry but I cannot do it by myself.
Please do it for me.
Regards.

**Comment by Mugen87** [comment]
Done: 0dd603877a96aae836d50700714eeae6d4bfba29

Maybe next time 😉
