### ISSUE TITLE
problem in new PMREMGenerator.js

### ISSUE THREAD

**Issue by lo-th** [mrdoob/three.js#18029]
##### Description of the problem

in new PMREMGenerator.js 
_sceneToCubeUV overdraw each face so final map have only one face 

solution is simple add 
_renderer.autoClear = false;
before 
_renderer.setRenderTarget( cubeUVRenderTarget );

and reactivate old autoClear after 

##### Three.js version

- [x] Dev
- [x] r111
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by elalish** [comment]
Good call, thanks! I put it in one function and forgot the other two. I'll put in a fix now.
