### ISSUE TITLE
THREE.LegacyJSONLoader removed

### ISSUE THREAD

**Issue by baronwatts** [mrdoob/three.js#18024]
Since the THREE.LegacyJSONLoader has been removed pretty much all of my clients sites where I used the loader has broken. Is there an alternative to the THREE.LegacyJSONLoader or is there a source code available? very disappointing to say the least.

**Comment by Mugen87** [comment]
Sometimes code is removed. I know it sucks but we can't keep stuff forever. 

As the name of this loader implied, it was legacy code. I think users had enough time in the last years to get rid of `JSONLoader` and the respective deprecated JSON format. Hence, you have to restore the code on your own and use it as a custom (application-level) loader.

**Comment by baronwatts** [comment]
Is it possible to provide the source code so I can load it locally instead? I've been using the loader since it was first introduced and there is no way I can reconvert all of the old .js models back to their original .obj format.

**Comment by Mugen87** [comment]
> Is it possible to provide the source code so I can load it locally instead?

Of course. You can use the following URL or just checkout the `r110` tag of the repository.

https://rawcdn.githack.com/mrdoob/three.js/r110/examples/js/loaders/deprecated/LegacyJSONLoader.js

Notice that there is also a script that can convert your legacy JSON files directly to `glTF`. Better than using `OBJ`.

https://gist.github.com/donmccurdy/c090dc53c7bfb704ef9de654ecc07632

**Comment by baronwatts** [comment]
Thanks! This is very useful.
