### ISSUE TITLE
PLYExporter generates incorrect mesh

### ISSUE THREAD

**Issue by ua4192** [mrdoob/three.js#18049]
##### Description of the problem

Hi

When I use PLYExporter library and I generate a ply file from a scene, the ply file seems no to be properly generated.

When you open the ply with meshlab, it prompts this message:

![image](https://user-images.githubusercontent.com/29919345/70030413-7bdda100-15a9-11ea-98a0-7166a2ac5db5.png)

After accepting this message this is what I get:

![image](https://user-images.githubusercontent.com/29919345/70030682-00c8ba80-15aa-11ea-9bbf-a6eab4e880aa.png)

If I click on OK, it only shows the points not the faces.

It happens with all the versions I have tested and with all models I have converted.

The most strange thing is that if I use PLYLoader it seems to be correct.

![image](https://user-images.githubusercontent.com/29919345/70030546-b8a99800-15a9-11ea-8e38-90cc8e770574.png)

Best regards

##### Three.js version 

- All of them

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
None

**Comment by Mugen87** [comment]
Can you please share the PLY file in this thread? I've found out that the way `property list` is defined breaks MeshLab right now.

**Comment by Mugen87** [comment]
Closing for now. Please reopen the issue if the issue still happens with the latest `PLYExporter` from `dev`. Don't forget to share the problematic `PLY` file then.

**Comment by ua4192** [comment]
Hi Michael.

Sorry for the delay.

I was unable to add the file before due to familiar problems.

The problem happens with any geometry converted with plyExporter. I was using r108.

My real problem is not directly linked with meshlab, my real problem is that I want to convert my ply files to nxz (nexus format) and I realized that many files converted with PLYExported were not properly converted.

Anyway, I will try other different conversion pipelines in order to be sure.

Many thanks as always for your support.

Best regards


Best regards
