### ISSUE TITLE
Incorrect render for MeshStandardMaterial with PointLight

### ISSUE THREAD

**Issue by elalish** [mrdoob/three.js#18046]
##### Description of the problem

With a very simple illuminated room example, I'm getting discontinuities in the lighting of the walls. Though my point light source is closer to the ceiling than the floor, the floor is shown as brighter than the ceiling. Here is my jsfiddle: https://jsfiddle.net/elalish/36cp8gwd/10/

##### Three.js version

- [x] Dev
- [x] r111
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
> I'm getting discontinuities in the lighting of the walls.

What do you mean by that?

> Though my point light source is closer to the ceiling than the floor, the floor is shown as brighter than the ceiling.

Considering that you're using a `PointLight`...  sounds physically logical to me?

**Comment by elalish** [comment]
Here are the discontinuities I'm seeing:
![image](https://user-images.githubusercontent.com/1649964/70084369-02eb4300-15c3-11ea-9944-eab0fbbb665e.png)

**Comment by elalish** [comment]
Or looking toward the ceiling: 
![image](https://user-images.githubusercontent.com/1649964/70084543-53fb3700-15c3-11ea-8dcb-3d8904bf9985.png)

**Comment by elalish** [comment]
Not really any better with physicallyCorrectLights enabled: https://jsfiddle.net/elalish/36cp8gwd/11/

**Comment by elalish** [comment]
Hmm, on second though, maybe this is correct after all (at least once physicallyCorrectLights is enabled). I think the lack of multiscattering here is just shocking to my brain.

**Comment by mrdoob** [comment]
If you've lived long enough in a world with no multi-scattering, it makes sense to your brain 😁
