### ISSUE TITLE
Why is there no support for non linear texture encoding on lightMap?

### ISSUE THREAD

**Issue by SBRK** [mrdoob/three.js#18050]
It appears only maps, envMaps and emissiveMaps use the the decoding functions when passed a texture that doesn't use linear encoding: 
https://github.com/mrdoob/three.js/blob/c7d88958041ff4af90bfd72fa3867716215fa1f6/src/renderers/webgl/WebGLProgram.js#L633-L638

We would like to use RGBD textures for lightmaps. Is there a reason for not applying the decoding to lightMaps (or all types of maps, for that matter) ?

**Comment by SBRK** [comment]
I found the PR that added this and it was briefly asked by @bhouston but not really addressed. 
https://github.com/mrdoob/three.js/pull/8117#issuecomment-187765059

So, would it be a good idea to add this for all types of maps ?

**Comment by Mugen87** [comment]
As mentioned in the following comment, the engine currently assumes that light maps are always defined in linear color space.

https://github.com/mrdoob/three.js/issues/11110#issuecomment-291000734

> Is there a reason for not applying the decoding to lightMaps (or all types of maps, for that matter) ?

Well, if there is a compelling reason it's of course possible to change the current behavior.

**Comment by donmccurdy** [comment]
> So, would it be a good idea to add this for all types of maps ?

I think this only makes sense for maps containing color data right now. Normal maps should never be encoded sRGB, for example, so there's not much point in supporting that. Light maps are usually sRGB, I believe, so the suggestion sounds good.
