### ISSUE TITLE
Ionic/ng not compiling

### ISSUE THREAD

**Issue by Daandeve** [mrdoob/three.js#18055]
##### Description of the problem

Hi, i tried to use three.js in ionic with angular.
But when i compile i get the following error.

[ng] ERROR in node_modules/three/src/core/BufferAttribute.d.ts:21:6 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 21  set needsUpdate( value: boolean );
[ng]         ~~~~~~~~~~~
[ng] node_modules/three/src/core/InterleavedBufferAttribute.d.ts:19:6 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 19  get count(): number;
[ng]         ~~~~~
[ng] node_modules/three/src/core/InterleavedBufferAttribute.d.ts:20:6 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 20  get array(): ArrayLike<number>;
[ng]         ~~~~~
[ng] node_modules/three/src/renderers/WebGLRenderer.d.ts:35:31 - error TS2304: Cannot find name 'OffscreenCanvas'.
[ng] 35  canvas?: HTMLCanvasElement | OffscreenCanvas;
[ng]                                  ~~~~~~~~~~~~~~~
[ng] node_modules/three/src/renderers/webgl/WebGLAttributes.d.ts:6:43 - error TS2304: Cannot find name 'WebGL2RenderingContext'.
[ng] 6  constructor( gl: WebGLRenderingContext | WebGL2RenderingContext );
[ng]                                             ~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/three/src/renderers/webgl/WebGLUtils.d.ts:3:43 - error TS2304: Cannot find name 'WebGL2RenderingContext'.
[ng] 3  constructor( gl: WebGLRenderingContext | WebGL2RenderingContext, extensions: any, capabilities: any );
[ng]                                             ~~~~~~~~~~~~~~~~~~~~~~
[ng]

##### Three.js version

- [ ] Dev
- [ ] r111
- [x] 0.111.0

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

-

**Comment by kunalkakkad** [comment]
Hello,
I am facing the same with version 0.112.1 also.
So @Daandeve did you find any solution?

**Comment by Mugen87** [comment]
Related: #18377
