### ISSUE TITLE
TypeError: Cannot read property 'precision' of null

### ISSUE THREAD

**Issue by lonelam** [mrdoob/three.js#18059]
##### Description of the problem
Hello, I got an error when I call `new THREE.WebGLRenderer({alpha: true, canvas: canvas})`
```TypeError: Cannot read property 'precision' of null```
when too many different webgl contexts exist in chrome, many methods in `three.js/src/renderers/webgl/WebGLCapabilities.js` will return null and throw an error before a new webgl context created and the oldest context dropped.

##### Three.js version

- [ ] Dev
- [ ] r111
- [x] r102

##### Browser
- [x] Chrome
##### OS
- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
What are the reasons for the existence of so many WebGL rendering contexts in your app? Besides, can you demonstrate the issue with a live example?

**Comment by Mugen87** [comment]
Closing due to lack of feedback.
