### ISSUE TITLE
can we make alphamap_fragment.glsl sample red channel?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#18053]
A mix of feature request and question. I have pbr model here that is set up like this:
![eb_basic_material_setup](https://user-images.githubusercontent.com/242577/70058350-0ab8e080-15df-11ea-90dc-3ce974e03668.png)

See, to match 3js `combined OcclusionRoughnessMetallic (RGB) texture` (#16325 ?) I only have to swap G → B and R → G, however I cannot just move opacity mask B → R, because [it appears to be sampled from G](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/alphamap_fragment.glsl.js), conflicting with roughness.

Now I know that R channel is supposed to be used by AO in 3js, but this model does not use AO. I also do not know how common this type of material is (i e if they mass-follow some tutorial, or the tool creates it, or they just connected the nodes at random) - just know that it is out there, and consider if the alpha sampling can/should be moved

**Comment by Mugen87** [comment]
The green channel is used on purpose. It's actually explained in the [docs](https://threejs.org/docs/#api/en/materials/MeshBasicMaterial.alphaMap).

> the WebGL renderer will use the green channel when sampling this texture due to the extra bit of precision provided for green in DXT-compressed and uncompressed RGB 565 formats.

**Comment by makc** [comment]
@Mugen87 well I guess it is time to write some onBeforeCompiler hack ¯\_(ヅ)_/¯
