### ISSUE TITLE
Override Material: Morph Targets

### ISSUE THREAD

**Issue by vanruesc** [mrdoob/three.js#18062]
##### Description of the problem

I'm using `MeshNormalMaterial` and `MeshDepthMaterial` as override materials and I sometimes set `morphTargets` to `true`. Now in `three@0.111.0`, this setting prevents objects without morph targets from being rendered altogether.

I'm not sure if this behaviour is intentional but since this change hasn't been documented I thought I should let you know.

##### Sandbox

Uncomment line 23 in `index.js`:
https://codesandbox.io/s/override-material-morph-targets-06hjw

##### Three.js version

- [x] Dev
- [x] r111
- [ ] r110
- [ ] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I can confirm this worked with `R110`. The regression was probably introduced via #17649.

**Comment by Mugen87** [comment]
Simplified example:

`R110`: https://jsfiddle.net/aoLbzj1s/
`R111`: https://jsfiddle.net/aoLbzj1s/1/

The problem is that setting `morphTargets` to `true` does render the mesh when the geometry contains no morph targets. With `R110` the mesh is still rendered.

**Comment by zeux** [comment]
Yeah we definitely need to always set the base influence if the material being used has the morph target shader variant. I will take a look...

**Comment by vanruesc** [comment]
FYI: the same problem occurs when `morphNormals` is set to `true` in `MeshNormalMaterial`.
