### ISSUE TITLE
Object3D type definition: missing readonly keyword for some attributes

### ISSUE THREAD

**Issue by martinRenou** [mrdoob/three.js#18076]
##### Description of the problem
The `position`, `rotation`, `quaternion`, `scale`, `modelViewMatrix` and `normalMatrix` attributes of `Object3D` are defined using the [`Object.defineProperties`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties) static method (See [here](https://github.com/mrdoob/three.js/blob/dev/src/core/Object3D.js#L70)). This method will set properties as read-only (writable = false) by default.

The problem is that those properties are not defined as read-only in the type definition (See [here](https://github.com/mrdoob/three.js/blob/dev/src/core/Object3D.d.ts#L62)), which results in this code to compile (which I guess should not): 
```typescript
const camera = new THREE.PerspectiveCamera(...);

// This compiles, but throws an error at runtime
camera.position = new THREE.Vector3(1, 1, 1);
```

I can come up with a PR fixing this if that is considered a bug.

**Comment by Mugen87** [comment]
>  I can come up with a PR fixing this

Sounds good!

**Comment by martinRenou** [comment]
I am wondering if some other attributes are supposed to be readonly?
