### ISSUE TITLE
 SkeletonHelper( skeleton ) Does not work.

### ISSUE THREAD

**Issue by sketchpunk** [mrdoob/three.js#18081]
https://threejs.org/docs/#api/en/helpers/SkeletonHelper

> Constructor
> SkeletonHelper( object )
> object -- can be any object that has an array of Bones as a sub object.
> For example, a Skeleton or a SkinnedMesh.

SkinnedMesh works, not Skeleton. Documentation does not seem to reflex how it works in the code. SkeletonHelper calls a function called "getBoneList" which only collects bones from object.children, does not look at object.bones, which explains why it doesn't work.

The simple solution is to just change the documentation to say any object with an array of children and not mention skeleton as an example or replace it with Bone. 

Or fix getBoneList to check for the existence of object.bones and load the data from there.

**Comment by Mugen87** [comment]
> The simple solution is to just change the documentation to say any object with an array of children and not mention skeleton as an example or replace it with Bone.

That sounds good.
