### ISSUE TITLE
Quaterion to Euler conversion done on each Object3D.quaternion write

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#18090]
This is just a post to solicit some preliminary feedback before I dedicate more time to the issue (proper repro with timing, PR ...):

On each `Object3D.quaternion` write the value is converted to the Euler `rotation` (using the `_onChangeCallback`). When manipulating very large and very dynamic scenes (>1000 nodes, all of them moving) this can be causing very significant performance hit, as the computation is quite slow -  `atan2` and `asin` is used. I never read the Euler representation.

For my use it would be much better if the Euler representation was not stored at all and would be computed only when necessary, when someone would be reading it. The `rotation` variable would be replaced by a property, writing to it would set the `quaternion`, reading from it would compute it.

Would such implementation be suitable for general use? Are other projects / other people reading Euler rotation extensively from the scene? Any other things I am missing in the bigger picture?

**Comment by Mugen87** [comment]
Related: #14910. Notice that the PR was closed because bi-directional sync did not cause a performance bottleneck. 

> this can be causing very significant performance hit

Please demonstrate this with a live example similar to the PR (see https://github.com/mrdoob/three.js/pull/14910#issuecomment-476804028). Without concrete numbers, it's not possible to evaluate this issue.

**Comment by OndrejSpanel** [comment]
A quick Chrome performance profiling session shows 3 of 20 ms in a typical frame on my computer spent in the Euler - Quat conversion for https://threejs.org/examples/index.html#webgl_performance. It is quite possible there is some hidden detail which will prevent me reducing this, but I stay encouraged and I will try this and report any findings.

**Comment by mrdoob** [comment]
> It is quite possible there is some hidden detail which will prevent me reducing this, but I stay encouraged and I will try this and report any findings.

Ok, closing this until then.
