### ISSUE TITLE
Normal in editor, trackballcontrols cannot be used after publishing

### ISSUE THREAD

**Issue by yanwencheng** [mrdoob/three.js#18092]
**In the editor, write the following code in scene script, which can be controlled normally. But it can't be controlled after publishing. See the attachment for the released code**
[ykkj.zip](https://github.com/mrdoob/three.js/files/3933142/ykkj.zip)
```


var controls= new THREE.TrackballControls( camera, renderer.domElement );
var stats=new Stats
console.log(stats)
console.log(1111)
function update(){

	 stats.update();
     controls.update();
}

function createText(msg){
var loader = new THREE.FontLoader();
		loader.load( 'fonts/Microsoft_YaHei_Regular.json', function ( font ) {
			var color = new THREE.Color( 0xffffff );
			var matLite = new THREE.MeshBasicMaterial( {
				color: color,
				transparent: false,
				opacity: 1,
				side: THREE.DoubleSide
			} );
			var message =msg;
			var shapes = font.generateShapes( message, 0.5 );
			var geometry = new THREE.ShapeBufferGeometry( shapes );
			geometry.computeBoundingBox();
			var board = scene.getObjectByName( 'board' );
			board.geometry=geometry
})
}
```

**Comment by Mugen87** [comment]
The editor does not import `TrackballControls` so you can't use it in a script. Have you modified the editor source code?

**Comment by yanwencheng** [comment]
> The editor does not import `TrackballControls` so you can't use it in a script. Have you modified the editor source cod

> The editor does not import `TrackballControls` so you can't use it in a script. Have you modified the editor source code?

Yes, I have modified the editor. Script can run in the editor, no problem. But when I access the post release project, there is no control effect. There are no console errors

**Comment by Mugen87** [comment]
You have to understand that we do not provide support if users implement custom enhancements in source files. Github is for bugs and feature requests only.

Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need help.
