### ISSUE TITLE
New PMREM effect loss severely

### ISSUE THREAD

**Issue by gonnavis** [mrdoob/three.js#18105]
Old PMREM, SHA-1: 0ddb31a0f722d76df776f01f57ee41f0865c0c75
http://gonnavis.com/threejs_test/pmrem/old/

New PMREM, SHA-1: aeb347fdfabcaef4b5be5164214e8df7b7d9a762
http://gonnavis.com/threejs_test/pmrem/new/

**Comment by mrdoob** [comment]
Uh?

**Comment by ManishJu** [comment]
Yes they look different. @gonnavis are the material same in both ?

**Comment by mrdoob** [comment]
Yes, the new PMREM will give different results than the previous one.
The previous PMREM was not correct.
