### ISSUE TITLE
Broken shader feature?

### ISSUE THREAD

**Issue by ssgstarter** [mrdoob/three.js#18117]
When replacing used ThreeJS version by a newer one (110) everything is crashing with this example https://codepen.io/zadvorsky/pen/VaXqRW

Is there a fix for this?

**Comment by Mugen87** [comment]
Update fiddle: https://jsfiddle.net/zouxps2d/

Please use the forum if you need more help in context of migration tasks. In you example, it was just necessary to handle the attribute `color` as part of the geometry, not of the shader material.
