### ISSUE TITLE
CSS3DObject is not clickable on Firefox

### ISSUE THREAD

**Issue by tranquyetdev** [mrdoob/three.js#18115]
##### Description of the problem
Hi team,
I've been experiencing this issue on Firefox latest (haven't tested previous versions). After I set my CSS3DObject a position:
{ "x": 86.72438691726555, "y": 59.24408563389257, "z": -400.84457553626225 }
then I can not click on that object anymore on Firefox (but Chrome works). But when we rotate the camera to other positions then it works.

I've created a fiddle on Codepen to reproduce the issue, Please see in **fullscreen** mode:
* [codepen](https://codepen.io/tranquyetdev/full/povgBPz) (latest release branch)

Can someone tell me when a CSS3DObject can be clickable?
Thank you

##### Three.js version

- [ ] Dev
- [x] r111
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Um, I can also reproduce this with the official example:

https://threejs.org/examples/css3d_youtube

It seems Firefox (unlike Chrome and Safari) is not able to detect the mouse hover correctly.

**Comment by WestLangley** [comment]
Have a look at [this](https://stackoverflow.com/a/59293013/1461008) SO answer.

>I can reproduce this with the official example:

Hmm... That example does not reproduce the issue for me.

**Comment by yomotsu** [comment]
Here is a simplified pure CSS version to reproduce in Firefox.
It seems nested 3D Object with negative-z causes the problem, as WestLangley mentioned.
https://codepen.io/yomotsu/pen/vYEKLwj

**Comment by mrdoob** [comment]
> Should we add `pointer-events: none` to scene and camera element

I think that sounds right to me.
