### ISSUE TITLE
FileLoader : type error

### ISSUE THREAD

**Issue by 1147079942** [mrdoob/three.js#18116]
##### Description of the problem

type error

FileLoader.setWithCredentials( value: string ): FileLoader;

the type of value should be boolean in FileLoader.d.ts

##### Three.js version

- [x] All of them
- [ ] Dev
- [ ] r111
- [ ] ...

##### Browser

- [x] All of them

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
That's correct! Do you want to make this change?

**Comment by 1147079942** [comment]
It's an honor for me to do it.
