### ISSUE TITLE
Example broken: Box Projected CubeMap Environment Mapping 

### ISSUE THREAD

**Issue by Paulexe** [mrdoob/three.js#18111]
The Example [BPCEM Example](https://threejs.org/examples/#webgl_materials_envmaps_parallax) seem to be broken for me since r108.

Expected result as in #15897 :
<img width="709" alt="53699441-d9766e80-3e1a-11e9-8b87-e756a069f18c" src="https://user-images.githubusercontent.com/38528017/70478891-779b1180-1adc-11ea-9362-02f9fbde43a2.png">

##### Behavior in r108 to dev:

Windows 10 Chrome/Firefox/Edge Gtx1060 + 1050 in Laptop:
 (Wall missing in reflection):
![windows](https://user-images.githubusercontent.com/38528017/70479069-e4161080-1adc-11ea-9561-be691cf4a185.PNG)

Android Galaxy s9 Android 9 Chrome/Firefox (Light missing in reflection and wierd wall reflection, but something like a cube gets reflected):
![android](https://user-images.githubusercontent.com/38528017/70479279-4a9b2e80-1add-11ea-9081-a9b3e2c0b52e.PNG)

iOS iPad Pro Safari (Wall missing in reflection):
![ios](https://user-images.githubusercontent.com/38528017/70479421-96e66e80-1add-11ea-8c77-6c3b101ebfd8.PNG)

##### Three.js version
- [x] Dev
- [x] r108 - r111
- [ ] r107

(First github Issue ever for me)

**Comment by Mugen87** [comment]
For testing:

[R107](https://rawcdn.githack.com/mrdoob/three.js/r107/examples/webgl_materials_envmaps_parallax.html) (still working)
[R108](https://rawcdn.githack.com/mrdoob/three.js/r108/examples/webgl_materials_envmaps_parallax.html) (broken)
