### ISSUE TITLE
ThreeJS and the transparent problem

### ISSUE THREAD

**Issue by agentsmis** [mrdoob/three.js#18126]
I know there are many issues about the transparent problem in the internet, but I need a solution.

The Problem:
I create some mesh objects with a simple transparent material. And when the objects are overlaps, sometimes (ok always) when I rotate the camera the objects not displaying correct.

The mesh objects has 2-4 Units space between. When I increase the space it works, but I must rotate the objects. Means i cannot increase the space between the objects.

Here some informations I test it:
 - depthWrite: false
 - depthTest: false
 - transparent: true
 - alphaTest: 0.5
 - nearPlane : 100
 - many more...
(From many issues I found in the internet)

I use threejs v101 (Same Problems with the newest v111).

See attachment (The close button, the texte are and the big button has all transparent (alpha) values. And when i rotate the camera, sometime it looks correct and often damaged.

Thanks for helping :-)
![screen](https://user-images.githubusercontent.com/1710882/70628231-141dfa80-1c28-11ea-93e6-703b90d82ee0.gif)

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests. Github is for bugs and feature requests only.
