### ISSUE TITLE
DataTexture2DArray mipmaps

### ISSUE THREAD

**Issue by lp249839965** [mrdoob/three.js#18134]
I use array textures to merge multiple textures for performance reason, but I see that THREE.DataTexture2DArray do not support mipmaps in WebGLTextures.js, which leads to artifacts and moire

**Comment by mrdoob** [comment]
Can you create a jsfiddle we can use as reference?

**Comment by FunFetched** [comment]
I'll hook you up, as I'm having a problem with this as well.

[https://jsfiddle.net/zywmxLd6/](https://jsfiddle.net/zywmxLd6/)

If you un-comment the minFilter setting, or use any of the mipmap filters, the texture comes out blank.

**Comment by FunFetched** [comment]
Ah. I found the problem.

At the bottom of WebGLTextures.uploadTexture(), we find this:

`
generateMipmap( 3553, texture, image.width, image.height );
`

3553 is GL_TEXTURE_2D. A simple change:

`
generateMipmap( textureType, texture, image.width, image.height );
`
... and everything works as expected.
