### ISSUE TITLE
PLYExporter and Alpha channel support

### ISSUE THREAD

**Issue by ua4192** [mrdoob/three.js#18133]
##### Description of the problem

Hi.

The current version available of PLYExporter and previous ones don't support PLY files with alpha channel. I have read that alpha vertex property is possible.

Best regards.

##### Three.js version

all

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
NA

**Comment by Mugen87** [comment]
> I have read that alpha vertex property is possible.

No, you can only define `opacity` on material level. The `color` attribute is `RGB`.
