### ISSUE TITLE
Importing examples (e.g. orbital controls) doesn't work

### ISSUE THREAD

**Issue by JeroenDelcour** [mrdoob/three.js#18140]
##### Description of the problem

Using the [three npm module](https://www.npmjs.com/package/three) I can't seem to be able to import examples. Running the code below, straight from the [documentation](https://threejs.org/docs/#manual/en/introduction/Import-via-modules):

```javascript
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
```

Results in `Module not found: Error: Can't resolve 'three/examples/jsm/controls/OrbitControls.js''`.

I'm not an expert on npm module packaging, but I did notice there is no examples directory in `node_modules/three`.

Am I missing something, or is this not working as intended?

##### Three.js version

- [ ] Dev
- [x] r111
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Please, use the [forum](https://discourse.threejs.org/) for help.
