### ISSUE TITLE
MeshStandardMaterial default roughness and metalness values.

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#18151]
After years of using `MeshStandardMaterial` I'm thinking that we picked the wrong default values for `roughness` and `metalness`.

I'm confident that `roughness` should be `1` by default.
I'm unsure whether `metalness` should be `0` or `1` by default, .

This is how a sphere with the default values looks like at the moment:

<img width="1197" alt="Screen Shot 2019-12-13 at 9 22 04 AM" src="https://user-images.githubusercontent.com/97088/70819090-2d3ebc80-1d8a-11ea-9708-39672014e2cb.png">

This is how it looks like with `roughness: 1` and `metalness: 0`:

<img width="1197" alt="Screen Shot 2019-12-13 at 9 24 06 AM" src="https://user-images.githubusercontent.com/97088/70819167-5f501e80-1d8a-11ea-929c-9ea03dc00680.png">

This is how it looks like with `roughness: 1` and `metalness: 1`:

<img width="1197" alt="Screen Shot 2019-12-13 at 9 25 28 AM" src="https://user-images.githubusercontent.com/97088/70819240-91618080-1d8a-11ea-9da2-446dbb22f478.png">

The reason it gets dark is because currently the material is not reflecting the scene environment.

**Coding ergonomics**

Currently, if someone uses a `roughnessMap` they need to change `roughness` to `1`.

Same applies for `metalnessMap`, but I can see two situations:

`0` by default: The user tries to use `metalnessMap` but it "doesn't work".
`1` by default: Currently looks darker if a `envMap` is not provided.

@WestLangley @Mugen87 @elalish @bhouston Anyone has any thoughts?

**Comment by Mugen87** [comment]
The default values of Babylon.js's `PBRMetallicRoughnessMaterial` are `1` for `metallic` and `roughness`.

https://www.babylonjs-playground.com/#2FDQT5#155

In filament however, the defaults are `1` for `roughness` and `0` for `metallic` (see section [4.4.2 Material fragment inputs](https://google.github.io/filament/Materials.html#materialdefinitions/fragmentblock/materialfragmentinputs)).

I think I prefer the latter one. I've often seen users in the past how use `MeshStandardMaterial` without env maps. For these use cases, a `metalness` value of 0 seems preferable.

**Comment by mrdoob** [comment]
Yeah, I think I vote for `metalness: 0` by default too.
