### ISSUE TITLE
update homepage

### ISSUE THREAD

**Issue by felixmariotto** [mrdoob/three.js#18155]
Hi !

I started fiddling with three.js about two years ago, and I've never seen any change on the website homepage since then. It could give the impression that the project is dead or unmaintained. Some very exciting and good-looking projects have been released in the recent years, for instance I'm amazed that a game like https://krunker.io that has seen millions of players is not showcased on the front page, it would persuade a lot of people to learn to use three. Whereas showcased projects like http://voxeljs.com , while probably having been impressive in the past, have been unmaintained for years and therefore give a bad impression of three.

It's important to sell the project a little bit. I think this is the major difficulty an open-source project has to face, there is no marketing team behind to sell it, no professional designer to take care of the brand's identity...

Suggestions :
- Update showcased projects on the homepage.
- Colourful banner somewhere that state the major upgrades of the last release, and date of this release

**Comment by mrdoob** [comment]
All in good time. More publicity means more users and we already struggle with the current load.

**Comment by mrdoob** [comment]
> I'm amazed that a game like https://krunker.io that has seen millions of players is not showcased

Where does it say it has seen millions of players? 🤔

**Comment by felixmariotto** [comment]
> > I'm amazed that a game like https://krunker.io that has seen millions of players is not showcased
> 
> Where does it say it has seen millions of players?

I don't know if there was millions of player, I just assume this given the popularity on YouTube, Discord, etc...
I said that only to make a point about adding new popular projects to the homepage, not to point to this particular game. Other projects diserve attention.

**Comment by mrdoob** [comment]
> I don't know if there was millions of player, I just assume this given the popularity on YouTube, Discord, etc...

I see. For these kind of suggestions, the more objective you can be the better.

**Comment by mrdoob** [comment]
Also...

> no professional designer to take care of the brand's identity

A professional designer took care of the website redesign some months ago.

**Comment by felixmariotto** [comment]
Well... I didn't mean to offend anybody. If your are satisfied with three.js communication, I close this issue.
To be clear, Krunker.io is not my project ( I wish it was ).
