### ISSUE TITLE
Nodes feature request: PointsNodeMaterial

### ISSUE THREAD

**Issue by martinRenou** [mrdoob/three.js#18153]
cc. @sunag 

I would be really interested in a `PointsNodeMaterial`, for using in a `THREE.Points` object. Which would have a `size` node attribute the same way `THREE.PointsMaterial` has one.

I could come up with a PR myself, could it somewhat inherit from the `SpriteNodeMaterial` in order to factorize some code?

**Comment by sunag** [comment]
Hi @martinRenou 
It was added here: https://github.com/mrdoob/three.js/pull/22538
Do you think we can close this issue?

**Comment by martinRenou** [comment]
Fantastic, thanks!
