### ISSUE TITLE
SMAA pass not working on Ubuntu 17.10

### ISSUE THREAD

**Issue by nimloth05** [mrdoob/three.js#18163]
##### Description of the problem

It seems that the SMAA pass is not working on linux, Ubuntu 17.10. I've looked at the `webgl_postprocessing_smaa` example and could not detect any difference while enabling, disabling or removing the SMAA pass. Its always aliased (so the pass doesn't seem to do anything). The only difference is when I enable browser alias (instantiate renderer with `antialias: true`

renderer antialias: true
![browser-antialias](https://user-images.githubusercontent.com/9193180/70862240-02936600-1f3a-11ea-91f9-7c13e79aef2b.png)

pass not added
![pass-removed](https://user-images.githubusercontent.com/9193180/70862241-02936600-1f3a-11ea-8cf6-bfa8cbd8e339.png)

pass.enabled = false
![pass-disabled](https://user-images.githubusercontent.com/9193180/70862242-02936600-1f3a-11ea-816e-e42a711e9917.png)

Original example
![pass-enabled](https://user-images.githubusercontent.com/9193180/70862243-032bfc80-1f3a-11ea-823f-35f637b7b6bb.png)

##### Three.js version

- Tested with r106 and current version from github (r111)

- [ X ] Dev
- [X ] r106

##### Browser

- [X ] Chrome (Version 78.0.3904.108 (Official Build) (64-bit))
- [X ] Firefox (61.0.1 (64-bit))

##### OS

- [X] Linux

##### Hardware Requirements (graphics card, VR Device, ...)

Dell XPS 9560, Ubuntu 17.10. I have a nvidia card installed: GTX 1050 Mobile. 
I'm not sure how I can print out the browser webgl stats and info, which card (intel or nvidia) is used.

**Comment by Mugen87** [comment]
The anti-aliasing works on macOS and Chrome:

no SMAA
![image](https://user-images.githubusercontent.com/12612165/70910132-663b9300-200f-11ea-942c-9acee5f53684.png)
SMAA 
![image](https://user-images.githubusercontent.com/12612165/70910148-6cca0a80-200f-11ea-9ff6-364ab8cb2ec2.png)

You might want to comment out `renderer.setPixelRatio( window.devicePixelRatio );` to better see the difference.

**Comment by nimloth05** [comment]
What I did was the following: I checkout the threejs git repo and executed demo webgl_postprocessing_smaa.html without modification (well, I commented out the rotation, so I can take screenshots)

If I comment out `renderer.setPixelRatio( window.devicePixelRatio );` the example still looks the same:
![pixel-ratio-commented-out](https://user-images.githubusercontent.com/9193180/70915541-52e1f500-201a-11ea-8834-b228a3e08395.png)

Thats why I concluded SMAA doesn't seem to work on linux...

**Comment by Mugen87** [comment]
Strange. Unfortunately I don't have a Linux system at hand so I can't reproduce the issue right now.

Do you see any warnings or errors in the browser console?

**Comment by nimloth05** [comment]
No, sadly not

**Comment by Mugen87** [comment]
> I'm not sure how I can print out the browser webgl stats and info, which card (intel or nvidia) is used.

When using Chrome, enter `chrome://gpu/` in the address bar. Can you please share the result in this issue? 

You might also try to update your GPU driver.

**Comment by nimloth05** [comment]
Here is the output:


Data exported | 2019-12-16T17:06:33.582Z
-- | --
Chrome version | Chrome/78.0.3904.108
Operating system | Linux 4.13.0-46-generic
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/4b26898a39ee037623a72fcfb77279fce0e7d648/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/4b26898a39ee037623a72fcfb77279fce0e7d648/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | 0cc6d390272a
2D graphics backend | Skia/78 dba5c993df3fb95fed01f8131aa0401e83c9198f
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end

**Comment by Mugen87** [comment]
Can you please also share the text below the `Copy Report to Clipboad` button? I'm especially interested in `GL_VENDOR`, `GL_RENDERER` and `GL_VERSION`.

**Comment by nimloth05** [comment]
# Driver Information

Initialization time | 109
-- | --
In-process GPU | false
Passthrough Command Decoder | false
Sandboxed | true
GPU0 | VENDOR = 0x10de, DEVICE= 0x1c8d *ACTIVE*
GPU1 | VENDOR = 0x8086, DEVICE= 0x591b
Optimus | true
AMD switchable | false
Driver vendor | Nvidia
Driver version | 384.130
GPU CUDA compute capability major version | 0
Pixel shader version | 4.50
Vertex shader version | 4.50
Max. MSAA samples | 32
Machine model name |  
Machine model version |  
GL_VENDOR | NVIDIA Corporation
GL_RENDERER | GeForce GTX 1050/PCIe/SSE2
GL_VERSION | 4.5.0 NVIDIA 384.130

GL_EXTENSIONS | GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_AMD_vertex_shader_viewport_index GL_AMD_vertex_shader_layer GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_locations GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_sparse_texture2 GL_ARB_sparse_texture_clamp GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_minmax GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXTX_framebuffer_mixed_formats GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_post_depth_coverage GL_EXT_provoking_vertex GL_EXT_raster_multisample GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_sparse_texture2 GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_filter_minmax GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback2 GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_EXT_x11_sync_object GL_EXT_import_sync_object GL_NV_robustness_video_memory_purge GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KHR_context_flush_control GL_KHR_debug GL_EXT_memory_object GL_EXT_memory_object_fd GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_EXT_semaphore GL_EXT_semaphore_fd GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_bindless_multi_draw_indirect GL_NV_bindless_multi_draw_indirect_count GL_NV_bindless_texture GL_NV_blend_equation_advanced GL_NV_blend_equation_advanced_coherent GL_NVX_blend_equation_advanced_multi_draw_buffers GL_NV_blend_square GL_NV_clip_space_w_scaling GL_NV_command_list GL_NV_compute_program5 GL_NV_conditional_render GL_NV_conservative_raster GL_NV_conservative_raster_dilate GL_NV_conservative_raster_pre_snap_triangles GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_draw_texture GL_NV_draw_vulkan_image GL_NV_ES1_1_compatibility GL_NV_ES3_1_compatibility GL_NV_explicit_multisample GL_NV_fence GL_NV_fill_rectangle GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_coverage_to_color GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_fragment_shader_interlock GL_NV_framebuffer_mixed_samples GL_NV_framebuffer_multisample_coverage GL_NV_geometry_shader4 GL_NV_geometry_shader_passthrough GL_NV_gpu_program4 GL_NV_internalformat_sample_query GL_NV_gpu_program4_1 GL_NV_gpu_program5 GL_NV_gpu_program5_mem_extended GL_NV_gpu_program_fp64 GL_NV_gpu_shader5 GL_NV_half_float GL_NV_light_max_exponent GL_NV_multisample_coverage GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering GL_NV_path_rendering_shared_edge GL_NV_pixel_data_range GL_NV_point_sprite GL_NV_primitive_restart GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_sample_locations GL_NV_sample_mask_override_coverage GL_NV_shader_atomic_counters GL_NV_shader_atomic_float GL_NV_shader_atomic_float64 GL_NV_shader_atomic_fp16_vector GL_NV_shader_atomic_int64 GL_NV_shader_buffer_load GL_NV_shader_storage_buffer_object GL_NV_stereo_view_rendering GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback GL_NV_transform_feedback2 GL_NV_uniform_buffer_unified_memory GL_NV_vdpau_interop GL_NV_vertex_array_range GL_NV_vertex_array_range2 GL_NV_vertex_attrib_integer_64bit GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NV_viewport_array2 GL_NV_viewport_swizzle GL_NVX_conditional_render GL_NVX_gpu_memory_info GL_NVX_nvenc_interop GL_NV_shader_thread_group GL_NV_shader_thread_shuffle GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum
-- | --
Disabled Extensions | GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent
Disabled WebGL Extensions |  
Window system binding vendor | NVIDIA Corporation
Window system binding version | 1.4
Window system binding extensions | GLX_EXT_visual_info GLX_EXT_visual_rating GLX_EXT_import_context GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGI_video_sync GLX_SGI_swap_control GLX_EXT_swap_control GLX_EXT_swap_control_tear GLX_EXT_texture_from_pixmap GLX_EXT_buffer_age GLX_ARB_create_context GLX_ARB_create_context_profile GLX_EXT_create_context_es_profile GLX_EXT_create_context_es2_profile GLX_ARB_create_context_robustness GLX_NV_delay_before_swap GLX_EXT_stereo_tree GLX_EXT_libglvnd GLX_ARB_context_flush_control GLX_NV_robustness_video_memory_purge GLX_ARB_multisample GLX_NV_float_buffer GLX_ARB_fbconfig_float GLX_EXT_framebuffer_sRGB GLX_NV_copy_image
Window manager | GNOME Shell
XDG_CURRENT_DESKTOP | ubuntu:GNOME
GDMSESSION | ubuntu-xorg
Compositing manager | Yes
Direct rendering version | direct but version unknown
Reset notification strategy | 0x8252
GPU process crash count | 0
System visual ID | 109
RGBA visual ID | 206
gfx::BufferFormats supported for allocation and texturing | R_8: not supported, R_16: not supported, RG_88: not supported, BGR_565: not supported, RGBA_4444: not supported, RGBX_8888: not supported, RGBA_8888: not supported, BGRX_8888: not supported, BGRX_1010102: not supported, RGBX_1010102: not supported, BGRA_8888: not supported, RGBA_F16: not supported, YVU_420: not supported, YUV_420_BIPLANAR: not supported, P010: not supported

# GpuMemoryBuffers Status

R_8 | Software only
-- | --
R_16 | Software only
RG_88 | Software only
BGR_565 | Software only
RGBA_4444 | Software only
RGBX_8888 | Software only
RGBA_8888 | Software only
BGRX_8888 | Software only
BGRX_1010102 | Software only
RGBX_1010102 | Software only
BGRA_8888 | Software only
RGBA_F16 | Software only
YVU_420 | Software only
YUV_420_BIPLANAR | Software only
P010 | Software only

**Comment by Mugen87** [comment]
It seems your Nvidia card is used. I wonder if you can force the usage of the integrated Intel GPU and then compare the visuals.

**Comment by nimloth05** [comment]
It doesn't work with the intel card as well... Maybe I should ask on the threejs forum if someone else has this problem on linux? Maybe we see some commonalities ...?

**Comment by Mugen87** [comment]
Sounds good 👍.

**Comment by nimloth05** [comment]
After some more testing and playing around with the example (also under windows, to get a better understanding) it seems the SMAA is actually working on linux, buts its so weak, that is only visible on some of the lines (from the wireframe cube). I was expecting the same quality of AA as I get from the browser, thats why I was convinced its not working properly.
 I'm sorry for taking up your time Mugen87
