### ISSUE TITLE
Raycaster intersectObjects returns wrong results

### ISSUE THREAD

**Issue by SBRK** [mrdoob/three.js#18170]
##### Description of the problem
I'm trying to find meshes between two points, so I use a Raycaster and set `far` to be the distance between those points. The result intersections seem to all be of greater distance than the `far` value I set, and all `distance` values in those intersections are different than `intersection.point.distanceTo(origin)` (and smaller than the distance between my points)

I'm gonna try and do a repro

##### Three.js version
- [x] r111

**Comment by SBRK** [comment]
I couldn't repro my exact problem, but I had other issues with `Raycaster` here:
https://jsfiddle.net/SBRK/vh4x5foq/4/

`intersections1` should intersect only with `mesh1`, so should have a length of 1, but it has 4 interesections, two with object `mesh1` and 2 with object `mesh2`, yet all with similar `distance` and `point`
`intersections2` should have no intersections, because `mesh2` is outside of the near/far, but somehow it intersects with

**Comment by Mugen87** [comment]
- You have to ensure an up-to-date world matrix before perform intersection tests.
- In some special cases, rays can intersect two or more faces at the same time. Shifting the ray's origin with a slight epsilon produces just one intersection.

https://jsfiddle.net/83ujmng6/1/

**Comment by SBRK** [comment]
> * You have to ensure an up-to-date world matrix before perform intersection tests.
Seems like it fixed my problem, thanks !
