### ISSUE TITLE
Strange syntax in polyfill.d.ts - leading | when defining a union type

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#18172]
I was surprised by the leading `|` in the https://github.com/mrdoob/three.js/blob/f6aae66d07eafb88e2d188d47cf67ce80ee56606/src/polyfills.d.ts#L8 

```
export type TypedArray =
	| Int8Array
	| Uint8Array
...
```

 I have checked [Typescript grammar](https://github.com/microsoft/TypeScript/blob/master/doc/spec.md#3.8.6) and it does not seem correct to me. I guess TS parsers somehow cope with this, but perhaps it would be safer to follow the specs?

**Comment by Mugen87** [comment]
Yeah, it's more clear to clean this up 👍 . Do you want to make a PR?

**Comment by OndrejSpanel** [comment]
Sure.
