### ISSUE TITLE
proto planet gpu example not working on firefox android 68.3.0 (on a Nexus 5X)

### ISSUE THREAD

**Issue by frading** [mrdoob/three.js#18177]
##### Description of the problem

Hi all,

This is probably related to https://github.com/mrdoob/three.js/issues/11196

The proto planet gpu example (https://threejs.org/examples/?q=gpu#webgl_gpgpu_protoplanet) is not working on Firefox Android. The canvas remain black and the particles never appear. The output I get in the console is:

```
Error: WebGL warning: drawElements: Framebuffer not complete. (status: 0x8cd6) Bad status according to the driver: 0x8cd6
Error: WebGL warning: drawElements: Framebuffer must be complete.
Error: WebGL warning: clear: Framebuffer not complete. (status: 0x8cd6) Bad status according to the driver: 0x8cd6
Error: WebGL warning: clear: Framebuffer must be complete.
Error: WebGL warning: drawElements: Framebuffer not complete. (status: 0x8cd6) Bad status according to the driver: 0x8cd6
Error: WebGL warning: drawElements: Framebuffer must be complete.
Error: WebGL warning: clear: Framebuffer not complete. (status: 0x8cd6) Bad status according to the driver: 0x8cd6
Error: WebGL warning: clear: Framebuffer must be complete.
Error: WebGL warning: drawElements: Framebuffer not complete. (status: 0x8cd6) Bad status according to the driver: 0x8cd6
Error: WebGL warning: drawElements: Framebuffer must be complete.
Error: WebGL warning: clear: Framebuffer not complete. (status: 0x8cd6) Bad status according to the driver: 0x8cd6
Error: WebGL warning: clear: Framebuffer must be complete.
Error: WebGL warning: drawElements: Framebuffer not complete. (status: 0x8cd6) Bad status according to the driver: 0x8cd6
Error: WebGL warning: drawElements: Framebuffer must be complete.
Error: WebGL warning: clear: Framebuffer not complete. (status: 0x8cd6) Bad status according to the driver: 0x8cd6
Error: WebGL warning: clear: Framebuffer must be complete.
Error: WebGL warning: drawElements: Framebuffer not complete. (status: 0x8cd6) Bad status according to the driver: 0x8cd6
Error: WebGL warning: drawElements: Framebuffer must be complete.
Error: WebGL warning: clear: Framebuffer not complete. (status: 0x8cd6) Bad status according to the driver: 0x8cd6
Error: WebGL warning: clear: Framebuffer must be complete.
Error: WebGL warning: drawElements: Framebuffer not complete. (status: 0x8cd6) Bad status according to the driver: 0x8cd6
Error: WebGL warning: drawElements: Framebuffer must be complete.
THREE.WebGLRenderer: WEBGL_draw_buffers extension not supported.
```
So it looks like a hardware limitation, but can you confirm this is the case and that there is no way around it (except upgrading my phone ) ?

##### Three.js version

r111

##### Browser

Firefox android 68.3.0

##### OS

Android (on a Nexus 5X)

##### Hardware Requirements (graphics card, VR Device, ...)

N/A

**Comment by Mugen87** [comment]
I can confirm this issue on a Pixel (1) with Firefox android 68.3.0. However, there are no problems when using Chrome 78 or when using Firefox 71.0 on macOS.

**Comment by frading** [comment]
ah yes, that's correct. Thanks a lot for checking. I've just tried on Chrome on my  Nexus 5X, and it works, so indeed a browser issue, not a hardware one.

**Comment by mrdoob** [comment]
@frading do you mind reporting the issue in the Firefox bugtracker?

**Comment by Mugen87** [comment]
Here is the respective link 😇 : https://bugzilla.mozilla.org/home

**Comment by frading** [comment]
@mrdoob @Mugen87 Sounds good, just submitted it: https://bugzilla.mozilla.org/show_bug.cgi?id=1604622

Also, the problem disappears when switching the renderer to webgl2 instead of webgl1. I assumed that webgl2 would not be supported if WEBGL_draw_buffers wasn't, but it actually is. So that's one possible work around to get the GPUComputationRenderer working on firefox 68.3.0 for android.

**Comment by Mugen87** [comment]
The devs from Mozilla can reproduce. It's now a Prio 1 bug. Better to track the issue at bugzilla.
