### ISSUE TITLE
threejs crash on latest chrome browser

### ISSUE THREAD

**Issue by qkaibo** [mrdoob/three.js#18198]
Chrome  79.0.3945.88   
Windows 10/1903
CPU I5-5200U    Memory: 16GB
when I use chrome to open the url https://threejs.org/examples/#webgl_animation_keyframes
browse report those error in console
![image](https://user-images.githubusercontent.com/20093077/71144603-8ced0a00-2259-11ea-838b-1f77a7ed3c86.png)

then threejs crash.

##### Three.js version

- [ ] Dev
- [ ] r111
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
1. What graphics card do you have?
2. Do all the examples crash?
3. Did the crash in Chrome 78?
4. Do they crash in Firefox too?
5. Do they crash in Edge too?

**Comment by qkaibo** [comment]
@mrdoob 
1.What graphics card do you have?
      NVIDIA GeForce GT 240

2.Do all the examples crash?
   When I roate scene , always crash.

3.Did the crash in Chrome 78?
   No
4.Do they crash in Firefox too?
 No
5.Do they crash in Edge too?
  No

**Comment by Mugen87** [comment]
Um, the warning reports an internal D3D11 error which means it's related to DirectX. Do you also have crashes with other 3D engines like Babylon.js? Please test with the following examples:

https://doc.babylonjs.com/examples/

**Comment by mrdoob** [comment]
> 3.Did the crash in Chrome 78?
> No
> 4.Do they crash in Firefox too?
> No
> 5.Do they crash in Edge too?
> No

Seems like it's a Chrome issue then...

You should report the bug here instead: http://new.crbug.com/
