### ISSUE TITLE
glTF SkinnedMesh memory leak

### ISSUE THREAD

**Issue by PaulKElliott** [mrdoob/three.js#18199]
##### Description of the problem

When I load the [CesiumMan.glb](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/CesiumMan/glTF-Binary/CesiumMan.glb) sample file in [Don's glTF Viewer](https://gltf-viewer.donmccurdy.com/):
Chrome Dev Tools' Memory tab says the heap keeps growing as long as the tab its visible.  

Besides the glTF Viewer, Memory leaks in boilerplate script that loads a SkinnedMesh via glTFLoader.

Snapshot points at glpMipmapViewer perhaps? A couple tests suggests rate of heap growth depends on texture size maybe?  Heap size stays steady in Firefox v71.

##### Three.js version

- [ ] Dev
- [x] r111
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
Could you share specifically what you're seeing that indicates a memory leak?  The render loop in my viewer has exactly one line of code:

https://github.com/donmccurdy/three-gltf-viewer/blob/1b1cbafdfd75ea02e2e12b87d8f8f8b7a33d0641/src/viewer.js#L140-L144

A SkinnedMesh loaded from glTF should not be any different from another SkinnedMesh, it's just a three.js objects once it's been loaded.

What is glpMipmapViewer?

**Comment by donmccurdy** [comment]
^And could you try the same test in an incognito window, to rule out any Chrome extensions as the cause?

**Comment by PaulKElliott** [comment]
Ah, disabling the WebGL Insight extension stops the heap from growing.  Thanks.
