### ISSUE TITLE
How have you designed the eyebrows movement for animation_skinning_morph

### ISSUE THREAD

**Issue by aishjain** [mrdoob/three.js#18190]
I couldn't even find it in the models/gltf/RobotExpressive/RobotExpressive.glb file, I am trying to have a 3D image of a robot arm that rotates from 0 to 180 and vice versa,I have used blender2.8.1 for animation and have exported the glb file and called it in an html file with three.js module, till here things are fine but now I want to stop it at some degree let's say if I give in the value 30 then the robot arm should move by 30, and if the previous state was at 60 then it should add 30 and move to 90.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests. You can easily login with you github account. Github itself is for bugs and feature requests only.
