### ISSUE TITLE
Key input doesn't work on Trackball controls example

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#18205]
##### Description of the problem

Trackball controlls example mentions that you can control the camera not only with the mouse but also the key A/S/D. But key input on the example does nothing.

https://threejs.org/examples/#misc_controls_trackball

##### Three.js version

- [ ] Dev
- [x] r111
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> But key input on the example does nothing.

Normally the layout is like so:

- Left Mouse: Orbiting
- Wheel: Zooming
- Right Mouse: Panning

When you press one of the keys e.g. D, you can pan with any mouse button you press. Same for A and S.

**Comment by takahirox** [comment]
Ah, ok. I think I misunderstood.
