### ISSUE TITLE
js->ts

### ISSUE THREAD

**Issue by wardenfeng** [mrdoob/three.js#18206]
我是feng3d引擎的作者，设计feng3d时多有参考three.js，非常感谢three.js的作者们，你们是我的敬爱老师！

希望three.js能够有typescript版本，能够更方便某些人阅读与贡献，因此有了该行为。

希望mrdoob能够开个分支或者其他方式使得这部分代码能够排上用场。

https://github.com/wardenfeng/three.js/tree/typescript

该分支是基于一个月前版本转换的。

我已经把src下js文件转换ts文件，并且能够使得webgl_animation_keyframes示例能够正常运行。

但是由于时间有限，现在做得很粗糙，很多地方还是使用any类型。

I am the author of feng3d engine. When designing feng3d, we often refer to three.js.
Hopefully, three.js will have typescript versions that are easier for some people to read and contribute to, hence the behavior.
Hopefully the mrdoob will branch off and make this part of the code useful.
https://github.com/wardenfeng/three.js/tree/typescript
This branch is based on the previous version of a month ago.
I've converted the SRC js file into a ts file, and I've been able to get the webgl_animation_keyframes example to work.
However, due to limited time, it is very rough to do now, and many places still use any type.

**Comment by mrdoob** [comment]
Sorry, but I'm personally not interested in ts.

The main reason I chose to do it in a js was because it doesn't require a compiler.

If in the future browsers add support for ts we could reconsider.

**Comment by donmccurdy** [comment]
Further details in https://github.com/mrdoob/three.js/issues/15545.
