### ISSUE TITLE
Editor can't export a ShadowMaterial to GLTF

### ISSUE THREAD

**Issue by Thomas-6freedom** [mrdoob/three.js#18203]
##### Description of the problem

Describe the bug or feature request in detail.

Steps to reproduce :

1. Open the [threeJS Editor](https://threejs.org/editor/).
2. Create a box
3. Change its material to ShadowMaterial
4. Export To GLB

Current behavior :
It does not export the GLB and it displays an error in the console.

Expected behavior : 
The GLB is exported and downloaded (and no error in the console)

![image](https://user-images.githubusercontent.com/49686866/71192997-a312be80-2289-11ea-94c2-c2debae5fe77.png)

##### Three.js version

- [X ] r111

##### Browser

- [X ] Chrome
- [X ] Opera

##### OS

- [X ] Windows

**Comment by donmccurdy** [comment]
Not all features of three.js exist in the glTF format, and ShadowMaterial is one of those. Perhaps this could be fixed so the model exports without a material, but the material itself cannot be exported.

**Comment by Fangh** [comment]
Thank you for the explanation.
Do you have any idea how I can have shadow on a "invisible" plane in a glTF scene ?

**Comment by donmccurdy** [comment]
The shadow itself is not bundled into the glTF file. You'd need to bake the shadow into an actual mesh or texture, if you want it to look a particular way, which understandably would not update with animation. Alternatively, some glTF viewers like [model-viewer](https://github.com/GoogleWebComponents/model-viewer/) can create a nice shadow automatically.

**Comment by makc** [comment]
@Fangh you could just render the shadow material into the texture:
```javascript
        const floor = new THREE.Mesh(
            new THREE.PlaneBufferGeometry( 2 * sizeLength, 2 * sizeLength ),
            new THREE.ShadowMaterial()
        );
        floor.rotation.x = -0.5 * Math.PI;
        floor.receiveShadow = true;
        floor.material.color = new THREE.Color( 0x777777 );
        ....

            const camera = new THREE.OrthographicCamera( -sizeLength, sizeLength, sizeLength, -sizeLength,
                0.0001 * sizeLength, 0.0003 * sizeLength );
            camera.position.y = 0.0002 * sizeLength;
            camera.rotation.x = -0.5 * Math.PI;
            const target = new THREE.WebGLRenderTarget( 1024, 1024 );
            renderer.setRenderTarget( target );
            renderer.render( viewer.world.scene, camera );
            renderer.setRenderTarget( null );
            floor.material = new THREE.MeshBasicMaterial({ map: target.texture, transparent: true });
```
