### ISSUE TITLE
Size capped at 256 for PointsMaterial

### ISSUE THREAD

**Issue by Karolusrex** [mrdoob/three.js#18200]
##### Description of the problem

Any value above 256 for the "size" parameter of PointsMaterial is not respected. Instead, the actual size will be capped at 256. 

The problem can be reproduced by running the example with billboard points and then changing the size parameter at line 57: https://github.com/mrdoob/three.js/blob/master/examples/webgl_points_billboards.html#L57.

##### Three.js version

- dev
- r108

##### Browser

- [x] Chrome

##### OS

- [x] Linux

**Comment by Mugen87** [comment]
Can you please report what values are logged with the following fiddle:

https://jsfiddle.net/b89njg3d/

**Comment by Karolusrex** [comment]
> Float32Array(2) [1, 255]

**Comment by Mugen87** [comment]
In this case you hit a WebGL/hardware limitation. Please follow the advices in this issue: https://github.com/mrdoob/three.js/issues/293#issuecomment-1450344

**Comment by Karolusrex** [comment]
Thank you for the information. I've been googling quite some time without finding anything on this. I think it could be valuable to include this in the documentation as a sidenote for the PointMaterial size.

**Comment by Mugen87** [comment]
Feel free to add a note if you like 👍

**Comment by mrdoob** [comment]
@Karolusrex here's the link if you would like to document it:

https://github.com/mrdoob/three.js/edit/dev/docs/api/en/materials/PointsMaterial.html
