### ISSUE TITLE
There seems to be no map property in MeshDepthMaterial.d.ts file.

### ISSUE THREAD

**Issue by kazz0913** [mrdoob/three.js#18228]
##### Description of the problem
At first, I’m sorry for my poor English and if there is a same issue.
I’m tracing [webgl_animation_cloth](https://threejs.org/examples/#webgl_animation_cloth) from the official website with typescript to practice three.js and typescript.
When i used `MeshDepthMaterial` class, I got the following error.

```
Argument of type
 '{ depthPacking: THREE.DepthPackingStrategies; map: THREE.Texture; alphaTest: number; }'
 is not assignable to parameter of type 'MeshDepthMaterialParameters'.
Object literal may only specify known properties, and 'map' does not exist in type 'MeshDepthMaterialParameters'.
```

My code
```
object.customDepthMaterial = new THREE.MeshDepthMaterial({
    depthPacking: THREE.RGBADepthPacking,
    map: clothTexture,
    alphaTest: 0.5
 })
```

Then I checked [`MeshDepthMaterial.d.ts`](https://github.com/mrdoob/three.js/blob/master/src/materials/MeshDepthMaterial.d.ts), but I didn’t find `map` property.

##### Three.js version
- [x] r111

##### Browser
- [x] All of them

##### OS
- [x] All of them

**Comment by Mugen87** [comment]
It seems the property is missing in the type declaration file. Do you want to make a PR with the change? `MeshDistanceMaterial` would need the same fix.

**Comment by kazz0913** [comment]
OK, I'm going to make a PR with this change and `MeshDistanceMaterial` together.
