### ISSUE TITLE
webgl_materials_envmaps_exr does not work on ios

### ISSUE THREAD

**Issue by FishOrBear** [mrdoob/three.js#18232]
##### Three.js version
- [x] r111

##### Browser
- [x] All of them

##### OS
- [x] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
iphone8 plus

If you use exr, then it will be completely black and use png to display graphics.

**Comment by Mugen87** [comment]
Can you please verify if the following units tests pass on your iPhone?

https://www.khronos.org/registry/webgl/sdk/tests/conformance/extensions/oes-texture-float.html?webglVersion=1&quiet=0&quick=1

**Comment by FishOrBear** [comment]
![image](https://user-images.githubusercontent.com/19372111/71430327-11ca9e80-2706-11ea-864d-c5ca7bc913f1.png)

**Comment by Mugen87** [comment]
In this case, you should file a bug at https://bugs.webkit.org/

The failing unit tests prove that something with the WebGL implementation is wrong.

**Comment by donmccurdy** [comment]
I'm getting the same problem on...

- iPhone SE
- iPhone 11 Pro
- iPad Pro

...so this may be affecting all iOS devices. 😕

**Comment by Mugen87** [comment]
Related: https://bugs.webkit.org/show_bug.cgi?id=204676

I'm afraid nobody takes care so far...

**Comment by marquizzo** [comment]
I found that checking for the `OES_texture_float` extension in the iOS rendering context misleadingly says it exists, even though it doesn't work. However, setting the EXR loader's dataType to `THREE.HalfFloatType` on iOS seems to do the trick:

```lang-js
if (isIOS) {
	this.loaderEXR.setDataType(THREE.HalfFloatType);
} else {
	this.loaderEXR.setDataType(THREE.FloatType);
}
```
How you find out if it's iOS is up to you. I like to look up the `navigator.userAgent` string, but it's not foolproof.
