### ISSUE TITLE
What about InstancedMesh.setPositionAt, setRotationAt, and setScaleAt?

### ISSUE THREAD

**Issue by marcofugaro** [mrdoob/three.js#18230]
I've been using the new InstancedMesh, and I love it! It's so simple to use.

Was there any decision against implementing `setPositionAt`, `setRotationAt`, and `setScaleAt` (and their counterpart `getPositionAt`, `getRotationAt`, and `getScaleAt`)? I found myself using `getMatrixAt` to retrieve every component of the matrix, applying it to the dummy, and then changing only the rotation.

```js
instancedMesh.getMatrixAt(i, dummyMatrix)
dummyMatrix.decompose(dummy.position, dummy.quaternion, dummy.scale)

dummy.rotation.x += 0.1
dummy.updateMatrix()
instancedMesh.setMatrixAt(i, dummy.matrix)
```

This could be easier if it was like this

```js
var rotation = instancedMesh.getRotationAt(i)
rotation.x += 0.1
instancedMesh.setRotationAt(i, rotation)
```

What do you think? Internally this would change only the rotation components of the matrix. I am guessing the same operations `Matrix4.extractRotation` and `Matrix4.makeRotationFromEuler` do, but taking into consideration also the `i` offset.

**Comment by Mugen87** [comment]
> var rotation = instancedMesh.getRotationAt(i)

The signature has to look like so or you would perform unnecessary object creation:
```js
instancedMesh.getRotationAt(i, rotation);
```
> I am guessing the same operations Matrix4.extractRotation and Matrix4.makeRotationFromEuler do, but taking into consideration also the i offset.

Unfortunately no. Compose and decompose operation with matrices can be expensive, so it's better to do this only once and not per property (position, rotation, scale). Hence, the matrix approach is easier since the user can decide when to update the matrix and `InstancedMesh.instanceMatrix`.

BTW: This topic was already discussed here: #17505

**Comment by marcofugaro** [comment]
Oh ok, so this would be expensive to do because you can't update rotation/scale without creating a new Matrix object. That makes sense.

Do you have a suggestion to make my code faster since I'm doing a matrix decomposition for each element in the render loop?

**Comment by Mugen87** [comment]
Have you considered to represent each instance as an `Object3D` that you manage in a separate array? You can then transform the objects, update the matrix and copy it over to the instanced mesh.

**Comment by marcofugaro** [comment]
Ended up saving just the positions and the rotations, which are the only things I need later. Thank you for your advice!
