### ISSUE TITLE
Editor: Selection box should reflect current animation state

### ISSUE THREAD

**Issue by WREQI** [mrdoob/three.js#18245]
![image](https://user-images.githubusercontent.com/35467304/71453066-66345380-27c4-11ea-9494-9e19f1c1f96f.png)

The parameterized model created by blender, the bounding box calculated by the box after the import is the largest, and does not surround the actual model size
[Breaker_NM1630S.glb.zip](https://github.com/mrdoob/three.js/files/4001716/Breaker_NM1630S.glb.zip)

**Comment by donmccurdy** [comment]
Could you share a model so that we can reproduce this?

You can drag .ZIP files into GitHub comments.

**Comment by WREQI** [comment]
> 您可以共享一个模型以便我们重现吗？
> 
> 您可以将.ZIP文件拖到GitHub注释中。

**Comment by WREQI** [comment]
I uploaded this model, sorry, I accidentally closed the comment, thank you

**Comment by Mugen87** [comment]
It seems the bigger AABB is related to: #17940

R111:

![image](https://user-images.githubusercontent.com/12612165/71473830-0dbb8100-27d9-11ea-987b-dab238d972e6.png)

R110:

![image](https://user-images.githubusercontent.com/12612165/71473822-05634600-27d9-11ea-9791-3a3dbee441f9.png)

**Comment by WREQI** [comment]
This is a parametric model. The bounding box obtained after the model deformation is still incorrect.

**Comment by WREQI** [comment]
[Breaker_NM1630S.glb 2.zip](https://github.com/mrdoob/three.js/files/4002433/Breaker_NM1630S.glb.2.zip)
![image](https://user-images.githubusercontent.com/35467304/71475029-6a3e9080-2819-11ea-94b1-63bf14d2e3ed.png)
This is a parametric model. The bounding box obtained after the model deformation is still incorrect.Tested with version 110

**Comment by WREQI** [comment]
![image](https://user-images.githubusercontent.com/35467304/71475077-a114a680-2819-11ea-849f-ffe3a4e1e94a.png)

**Comment by zeux** [comment]
Note that in r110, morph targets weren’t included into the bounding box calculation at all in expandByObject, so the result could be too small.

r111 computes the conservative maximum that takes into account all targets with assumed boundary weights of +-1. The result could be too large if the requird weight ranges are smaller.

Neither r110 nor r111 has a way to compute a precise bounding box using currently assigned morph weights.

**Comment by donmccurdy** [comment]
Our definitions of "incorrect" and "too small" here depend on some assumptions of what the bounding box is being used for... for culling and raycasting, a conservative maximum accounting for skinning and morph targets is a good thing. For UI manipulation in the editor, a snapshot of the objects bounds _now_ is probably what users expect.

I think the changes in #17940 are right, and a conservative `geometry.boundingBox` is best for internal usage like culling and raycasting. Perhaps this should be considered a feature request for the Editor, to use a tighter bounding box for the UI?

Alternatively, I could imagine having an API that lets users access an approximate bounding box for an object given the current frame _without_ iterating over all vertices for that frame, based on cached min/max values on BufferAttribute properties and some special handling for Skeletons. But that's not the API we have currently, and I don't know how many applications would practically need that.

**Comment by zeux** [comment]
Just to clarify that #17940 is not at fault; before that change the bounding box was computed irrespective of morph targets,

What is causing this is that in this model, the morph targets are used for major changes to the model's size; the bounding box is computed assuming worst case parameters L & W & H (1), but of course if you set them to their initial values (0), the object is much smaller.

L&W&H = 0:

![image](https://user-images.githubusercontent.com/1106629/71492714-70c40c80-2807-11ea-8466-3e6d9a46fc83.png)

Before #17940, the bounding box was always equal to the extents of this object, even if L/W/H were larger.

L&W&H = 1:

![image](https://user-images.githubusercontent.com/1106629/71492728-8d604480-2807-11ea-9d63-d5647380b313.png)

After #17940, the bounding box is now always equal to the extents of this object, even if L/W/H are smaller.

So I believe that now the behavior in three.js is actually as intended, and returning the bounding box that can be used for culling. The previous behavior seems strictly worse.

The only way to achieve "intuitive" behavior for editor here is to implement a feature that computes a precise bounding box that takes into account all morph targets (and probably skinning transformation?).

**Comment by donmccurdy** [comment]
Not suggesting any problem with #17940, but I think the OP was expecting a bounding box that ignored the presence of morph targets entirely... The three.js Editor doesn't support direct manipulation of morph targets, although you can play/pause animations that could affect them.

**Comment by zeux** [comment]
I guess, although since GLTF files can specify arbitrary starting values for morph weights, ignoring morph targets seems wrong even for the existing editor.

**Comment by donmccurdy** [comment]
The Editor is using BoxHelper, rather than displaying `geometry.boundingBox` directly. I think it would be appropriate for BoxHelper to use the current frame's bounding box rather than the more conservative box used in the renderer — it already has an `.update()` method that we expect users to call when the content changes.

**Comment by WREQI** [comment]
Not only the bounding box is correct, but also the center coordinates of some objects are incorrectly obtained after deformation.The central bid of the child object obtained by updateMatrixWorld(true),getWorldPosition has not changed

**Comment by WREQI** [comment]
> I guess, although since GLTF files can specify arbitrary starting values for morph weights, ignoring morph targets seems wrong even for the existing editor.

Not only the bounding box is correct, but also the center coordinates of some objects are incorrectly obtained after deformation.The central bid of the child object obtained by updateMatrixWorld(true),getWorldPosition has not changed
@WREQI
 
 
Leave a comment
Attach files to your comment
Attach files by dragging & dropping, selecting or pasting them.
Assignees
No one assigned
Labels
Editor
Feature Request
Projects
None yet
Milestone
No milestone
Notifications
Customize
You’re receiving notifications because you modified the open/close state.
4 participants
@donmccurdy
@Mugen87
@zeux

**Comment by donmccurdy** [comment]
@WREQI The box you see is accounting for all possible deformations of the morph targets on the mesh. So the box may look much larger than the shape you see on screen, and the center may be off. I've updated the issue's title to clarify this.

**Comment by sotrh** [comment]
How would one go about getting a bounding box using the currently active morphs? I'm trying to align objects in my scene using bounding boxes. I know I can get the vertex data from the BufferedGeometry, but I don't know if the data there is accurate for the currently active morph targets, or if that's just the default vertex data.
