### ISSUE TITLE
Inconsistent behaviour of the logarithmic depth buffer on the desktop and mobile devices

### ISSUE THREAD

**Issue by EddiG** [mrdoob/three.js#18258]
##### Description of the problem
There is a different result I have on desktop and mobile devices. I have a large scene that has a pretty big scale range. On that scene, I have a couple of third party shapes that I should render one on top of another (they are mostly coplanar). That requires to solve a famous z-fighting problem, which I solved for the desktop by using the gap between shapes and logarithmic depth buffer.

There is an [example](https://codesandbox.io/s/threejs-z-fighting-mobile-issue-pn211) and [preview](https://pn211.csb.app/)(which easier to test on mobile)

You can see on the screenshot below a rendered scene on the desktop
![image](https://user-images.githubusercontent.com/4124316/71544541-afda9500-29a2-11ea-97a9-56007cfc362e.png)

And the same scene on the mobile device
![image](https://user-images.githubusercontent.com/4124316/71544568-0647d380-29a3-11ea-89fc-1812d84ef35d.png)

Maybe there should be some special tunings for the mobile which I don't know, but in general, I think it should work the same for desktop and mobile.

##### Three.js version

- [ ] Dev
- [x] r112
- [x] r111

##### Browser

- [] All of them
- [x] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [x] Android
- [x] iOS

**Comment by Mugen87** [comment]
> I have a large scene that has a pretty big scale range

A `near` value of `1` and a `far` value of `1000` do not define a scene with big scale. Your issue can be used without using logarithmic depth buffer. Check out the usage of [Object3D.renderOrder](https://threejs.org/docs/index.html#api/en/core/Object3D.renderOrder) and [Material.depthWrite](https://threejs.org/docs/index.html#api/en/materials/Material.depthWrite) in the following updated live example that solves the issue (at least on my Pixel).

https://codesandbox.io/s/threejs-z-fighting-mobile-issue-yub5r

Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need more help with z-fighting issues. These are usually not caused by engine bugs but user errors.

**Comment by EddiG** [comment]
Thanks a lot @Mugen87  
Sorry, for posting that here. I've tried both a `depthWrite` and `renderOrder` on my project but for some reason, they didn't work alone for my scene (btw, depth write alone solves a problem in an example above). I didn't tried them together, my fault 🙄

**Comment by Mugen87** [comment]
> (btw, depth write alone solves a problem in an example above)

This really depends on how you add your objects to the scene. They might be rendered automatically in the right order. However, you can always force the _correct_ order via `Object3D.renderOrder`.

**Comment by EddiG** [comment]
Thanks @Mugen87  I also read that and checked that few times and I believe that the order is correct.
As you can notice I'm not very familiar with three.js (which is an amazing library) and a solving problem like that gets painful because there is no good reference article. There are few ways to solve `z-figthing` problem I noticed so far, `depthWrite`, `renderOrder`, `logarithmicDepthBuffer`, `polygonOffset`, `custom shaders` and it's really hard to understand how they all correspond with each other. I spent a few days for tries to make it work. Sadly, I have not enough competence in that question, but if someday there will be an article that can provide some brief description of each of those options, how they affect rendering process and some scenarios in which they are more suitable, it would be great and helpful for all newbies.
