### ISSUE TITLE
Performance on Firefox vs Chrome

### ISSUE THREAD

**Issue by HHammerite** [mrdoob/three.js#18255]
##### Description of the problem

I'm using Threejs with React and have noticed a major performance gap with different browsers. I mainly use Firefox (personal preference) and have noticed it has far worst performance than Chrome running an indentical part of my app. I also found that Firefox (on my Windows 10 PC with a GTX 1080) has worst FPS performance than a Ipad Pro using Safari. This doesn't seem right to me. 

On Chrome I get a solid 10-11ms for my animation frame whereas on Firefox it is up to around 25ms. This was running identical code and content within the three scene. 

My animation function for three looks like this. Nothing exciting happening here. 

`animate = () => {
    this.frameId = requestAnimationFrame(this.animate);

    const delta = this.clock.getDelta();
    const hasControlsUpdated = this.controls.update(delta);

    if (hasControlsUpdated) {
      this.onCameraChange();
    }

    this.renderer.render(this.scene, this.camera);
  }`

Could this be a bug in Firefox or Threejs?

##### Three.js version
- [x] r107

##### Browser
- [x] Safari
- [x] Chrome
- [x] Firefox

##### OS

- [x] All of them
- [x] Windows
- [x] iOS

##### Hardware Requirements (graphics card, VR Device)
- Ryzen 3900x
- GTX 1080

**Comment by mrdoob** [comment]
Please, report the issue to Firefox instead.
