### ISSUE TITLE
Type issue in Texture.type

### ISSUE THREAD

**Issue by mikialex** [mrdoob/three.js#18269]
##### Description of the problem

I'm working on migrate threejs to pure ts and I have encounter some issue. 

now we have these enum in constants.d.ts

```ts
// Data types
export enum TextureDataType { }
export const UnsignedByteType: TextureDataType;
export const ByteType: TextureDataType;
export const ShortType: TextureDataType;
export const UnsignedShortType: TextureDataType;
export const IntType: TextureDataType;
export const UnsignedIntType: TextureDataType;
export const FloatType: TextureDataType;
export const HalfFloatType: TextureDataType;

// Pixel types
export enum PixelType { }
export const UnsignedShort4444Type: PixelType;
export const UnsignedShort5551Type: PixelType;
export const UnsignedShort565Type: PixelType;
export const UnsignedInt248Type: PixelType;
```
and in Texture.d.ts, the type of Texture.type is TextureDataType; but in webglTextures.js, ts complains that `This condition will always return 'true' since the types 'TextureDataType' and 'PixelType' have no overlap.` 

I did roughly search that PixelType is not used at all. So. I think maybe the two enum TextureDataType and PixelType should merge together?

##### Three.js version

- [ ] Dev
- [ ] r112
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> I did roughly search that PixelType is not used at all. So. I think maybe the two enum TextureDataType and PixelType should merge together?

Yes, I think this makes sense. These packed types are currently not used in the examples however you use them like any other `Texture.type` property:

https://jsfiddle.net/fsxgwoya/

**Comment by Mugen87** [comment]
@mikialex Do you want to make the PR with the change?
