### ISSUE TITLE
Everything stopped working on IOS a week (maybe two) ago...

### ISSUE THREAD

**Issue by gonzzza007** [mrdoob/three.js#18282]
Hi! I was developing a 3d scene for my website but at some point i couldn't see anything on my iPhone. I continued to develop on my PC hoping to fix it later. Today i discovered that none of the official three.js examples work on IOS as-well. So I guess that's not my phone, but something in the latest three.js update.

I am testing on iPhone SE, IOS 10, latest Chrome/Safari,  latest NPM three.js package (revision 112).

**Comment by Mugen87** [comment]
> Today i discovered that none of the official three.js examples work on IOS as-well.

Can you please verify if this basic example works:

https://threejs.org/examples/webgl_geometry_cube

If not, please try to find out if any error messages or warnings are logged in the browser console. You can do this with Chrome by following the instructions here:

https://blog.chromium.org/2019/03/debugging-websites-in-chrome-for-ios.html

**Comment by gonzzza007** [comment]
Thanks for a reply. The basic example gives me black screen on both - Chrome and Safari. 
I will try to get the console information and will post it here.

**Comment by mrdoob** [comment]
IPhone SE is stuck in iOS 10?

**Comment by donmccurdy** [comment]
Tested on iPhone SE with iOS 13.3, and the examples are working fine here.

**Comment by gonzzza007** [comment]
I have checked examples and my website on wife's iphone 7 ios 12 - and it worked fine. I don't want to update the phone, next ios usually makes it slower, but yes, compatibility and security is a drawback. Probably i should close the issue and think of 'latest ios' as a requirement of three.js

**Comment by donmccurdy** [comment]
@gonzzza007  I would also suggest that when developing your website, you lock in a particular version of three.js (like https://unpkg.com/three@0.112.0/build/three.js) — if you're hotlinking the latest version of the library, future changes _will_ eventually break your application, as the three.js API does evolve over time.

If you can help identify the problem (e.g. find a JavaScript or GLSL error in your device's logs) we may be able to fix the issue, but without that I'm not sure we can reproduce or debug this. We do not intend to strictly require the most recent OS, although keeping the OS and browsers up to date definitely helps. iOS 10 is three years old and it is impossible for us to test all combinations of devices, GPUs, browsers, and operating system versions.
