### ISSUE TITLE
Where is the Google+ content now for "lab" examples?

### ISSUE THREAD

**Issue by roschler** [mrdoob/three.js#18287]
Hello,

I wanted to look at the source code for this advanced ThreeJS example by `mrdoob`:

https://mrdoob.com/lab/javascript/threejs/css3d/periodictable/

When I clicked on the `info` link, I got a screen telling me that the Google+ content was gone.  Is there a new home for this `lab` project and for the other lab projects?

**Comment by mrdoob** [comment]
Ugh.. Google...
Maybe it's indexed on the Way Back Machine?

**Comment by roschler** [comment]
Unfortunately not.  Here is the Wayback Machine's record of the `info` page:

https://web.archive.org/web/20160601000000*/https://plus.google.com/113862800338869870683/posts/QcFk5HrWran

I tried many of the captures and they all redirected to a 404 page.  Only the most recent snapshot worked but it went to a 90 second YouTube video of the demo.

**Comment by mrdoob** [comment]
Meh...
I did do a backup though. I'll try to rescue it somehow when I get back home.

**Comment by roschler** [comment]
Ok thanks.  I've never really had much luck with those archive sites historically.

**Comment by roschler** [comment]
Any luck with rescuing the backup?

**Comment by mrdoob** [comment]
Seems like Google Takeout didn't include that post... 🤦‍♂️

However, I just noticed that in web archive link, even if it says "Not Found", the source code has the post!

---

Some weeks ago some people pointed me to <span class="proflinkWrapper"><span class="proflinkPrefix">+</span><a href="https://web.archive.org/web/20130614180807/https://plus.google.com/106071287226678709490" class="proflink" oid="106071287226678709490">Steve Newcomb</a></span>&#39;s &quot;game engine&quot; <a href="https://web.archive.org/web/20130614180807/http://famo.us/" class="ot-anchor">famo.us</a> ($1.1M funding).<br/><br/>If you haven&#39;t seen it, here&#39;s their presentation at TechCrunch Disrupt:<br/><br/><a href="https://web.archive.org/web/20130614180807/http://techcrunch.com/2012/09/10/famo-us-is-a-gaming-engine-for-3d-interfaces/" class="ot-anchor">http://techcrunch.com/2012/09/10/famo-us-is-a-gaming-engine-for-3d-interfaces/</a><br/><br/>The way it was presented, &quot;this is not X, this is not Y... but I&#39;m not going to tell you what it is&quot; reminded me to Euclideon videos:<br/><br/><a href="https://web.archive.org/web/20130614180807/http://www.youtube.com/watch?v=00gAbgBu8R4" class="ot-anchor">Unlimited Detail Real-Time Rendering Technology Preview 2011 [HD]</a><br/><br/>Back to <a href="https://web.archive.org/web/20130614180807/http://famo.us/" class="ot-anchor">famo.us</a> &quot;game engine&quot;. Ok, so It&#39;s not WebGL and is not Canvas. It can only be CSS3D it seems to run without plugins in the browser. Also, if you look at the video carefully, only when the demo is running as an app the elements use additive blending, when it&#39;s running on the browser there is no additive blending.<br/><br/>Now, lately I&#39;ve been working on the CSS3DRenderer for <span class="proflinkWrapper"><span class="proflinkPrefix">+</span><a href="https://web.archive.org/web/20130614180807/https://plus.google.com/104300307601542851567" class="proflink" oid="104300307601542851567">three.js</a></span> as a solution for the current iOS situation. So, I just got curious and decided to try to replicate the demo and see if it could be CSS3D.<br/><br/>For testing the waters I first did a simple panorama test:<br/><br/><a href="https://web.archive.org/web/20130614180807/http://mrdoob.com/lab/javascript/threejs/css3d/panorama/" class="ot-anchor">http://mrdoob.com/lab/javascript/threejs/css3d/panorama/</a><br/><br/>Performance seemed pretty decent. So next I spent quite a while writing the array with all the elements (I can&#39;t believe they made me memorise all these in school...) and after a bit of actual code I got something pretty similar:<br/><br/><a href="https://web.archive.org/web/20130614180807/http://mrdoob.com/lab/javascript/threejs/css3d/periodictable/" class="ot-anchor">http://mrdoob.com/lab/javascript/threejs/css3d/periodictable/</a><br/><br/>Yeah, I didn&#39;t bother to replicate all the interaction, neither to add the Ironman picture on the background. I guess it&#39;s good enough as it is. But hey, while I was at it I made TrackballControls touch-friendly ^^<br/><br/>Attached is a video of how it runs on an iPad 2. (Sorry for the cheesy music, but the original video had the same.)

https://www.youtube.com/watch?v=nPEYdw2Ssa8

**Comment by roschler** [comment]
Thanks @mrdoob that's great!
