### ISSUE TITLE
SoftShadows turn MeshStandardMaterial yellow on Pixel 3

### ISSUE THREAD

**Issue by elalish** [mrdoob/three.js#18315]
##### Description of the problem

I assume this is a driver bug on the Pixel 3, and it's probably long-standing; it repros on dev, as well as r112 and r110. I haven't tried any more versions. Try this [fiddle](https://jsfiddle.net/elalish/51Lbtuck/9/); normally it's just a white sphere:
![image](https://user-images.githubusercontent.com/1649964/71842923-9e1a8100-3077-11ea-9b59-1dac05daaf85.png)
But on Pixel 3, specifically with this line enabled:
`renderer.shadowMap.type = THREE.PCFSoftShadowMap;`
We get yellow:
![image](https://user-images.githubusercontent.com/1649964/71843101-fc476400-3077-11ea-954d-7a8cf43a3b36.png)

##### Three.js version

- [x] Dev
- [x] r112
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Pixel 3

**Comment by soraryu** [comment]
I can confirm getting the same issue on Xiaomi Mi 9.
![IMG_20200106_211855](https://user-images.githubusercontent.com/2693840/71846169-35102900-30ca-11ea-8118-acbc909d6608.jpg)

**Comment by Mugen87** [comment]
Can't reproduce this on a Pixel 1, Android 10.

**Comment by Mugen87** [comment]
> But on Pixel 3, specifically with this line enabled:
renderer.shadowMap.type = THREE.PCFSoftShadowMap;

So the problem does not happen when using `THREE.BasicShadowMap`, `THREE.PCFShadowMap` or `THREE.VSMShadowMap` ?

**Comment by elalish** [comment]
Yeah, that's what I was thinking too. I'm testing with a different example, but I'm finding if I either remove this line: https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/shadowmap_pars_fragment.glsl.js#L82 and return either `a` or `b` instead, it starts working. Or instead I can fix it by commenting out 3 or more of these lines: https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/shadowmap_pars_fragment.glsl.js#L150

Maybe just hitting some complexity limit that confuses the driver?

**Comment by elalish** [comment]
Honestly, it seems like that softShadow function could be more efficient anyway; I'll see if I can refactor it and fix this in the process.
