### ISSUE TITLE
Using ExtrudeBufferGeometry to generate a model, world coordinates are not on the model?Does anyone know why?

### ISSUE THREAD

**Issue by WREQI** [mrdoob/three.js#18318]
![image](https://user-images.githubusercontent.com/35467304/71866257-8824c300-3140-11ea-9e57-6b82481a6ab6.png)
![image](https://user-images.githubusercontent.com/35467304/71866265-8d820d80-3140-11ea-97ae-255f3458479a.png)

**Comment by WestLangley** [comment]
This is not a help site. Please use the [forum](https://discourse.threejs.org) for help.
