### ISSUE TITLE
Canvas textures black on mobile devices

### ISSUE THREAD

**Issue by QuintonMostert** [mrdoob/three.js#18311]
I am having a Issue were the textures on my 3d model viewer are coming up black on android devices.
I have tested it on android 8.0.0 
here is a screenshot:
https://imgur.com/GI46BFp

Here is the viewer : http://mcpecore.com/single.php?u=Humanoid

on computers it works fine with no issues but seeing as my website is mainly for mobile users this black textures is a huge issue.

the viewers code is here : http://mcpecore.com/scripts/BBModelLoader2.js

I could really use any help I can get on getting this issue resolved

here is a codepen it also has the same black textures issue on mobile:
https://codepen.io/pneuma01/pen/PowqRwQ

**Comment by Mugen87** [comment]
I can' reproduce the issue on a Pixel 1 with Android ten. 

/cc https://stackoverflow.com/questions/59605314/three-js-canvas-textures-black-on-mobile-devices

**Comment by QuintonMostert** [comment]
I fixed it by changing the lighting and the texture resolution :P

**Comment by Mugen87** [comment]
In this case, I suggest you delete your question at stackoverflow.
