### ISSUE TITLE
Is the requestFrameAnimation/render loop supposed to nest on the stack?

### ISSUE THREAD

**Issue by roschler** [mrdoob/three.js#18316]
I am using this version of ThreeJS:

https://cdnjs.cloudflare.com/ajax/libs/three.js/110/three.min.js

I am using what appears to me from samples I've seen, to be a typical requestFrameAnimation/render loop in my ThreeJS app:

```
function render() {
    // Render the updated scene.
    g_Renderer.render(g_Scene, g_Camera);
    
    // Next animation iteration.
    requestAnimationFrame(render);
}
```

During a tracing session, I noticed that the render call was deeply nested on the stack where my breakpoint was being hit.  At that time, about 17 calls deep.  Is this supposed to happen?  Below is an example where I captured the stack in the Chrome debugger at 5 nested calls deep.  Each time I resume the app it will nest another level down:

![image](https://user-images.githubusercontent.com/4660487/71849551-52c89880-30a0-11ea-8dd9-380974013d7d.png)

Doesn't this end up in an out-of-stack space error eventually?  This seems a bit odd to me.

**Comment by donmccurdy** [comment]
See https://github.com/mrdoob/three.js/issues/18240. The calls are not actually nested on the stack, but Chrome's developer tools present them that way when the "async" debugging mode is enabled. In other words, Chrome re-constructs the nesting from async calls that were not actually nested. This should not affect performance or debugging under normal circumstances, although a possible bug in Chrome developer tools was suggested in that issue.

**Comment by roschler** [comment]
Thanks Don.  As a veteran programmer that explanation helps a lot.  Infinite recursion is one of those things that are really hard to just "ignore"", but your explanation makes perfect sense so I can relax.

Is there really a big difference between using `requestAnimationFrame()` and a `setInterval()` based call instead?

**Comment by donmccurdy** [comment]
The main problems with `setInterval` are described in https://github.com/mrdoob/three.js/issues/18240#issuecomment-569349448. You can work around some of those issues with more code, and user agent sniffing for different devices, and so on. But in the end that's what `requestAnimationFrame` is for, and it's best practice to use it. Some features (like reduced FPS when iOS is in low battery mode) would be impossible to support otherwise.

**Comment by roschler** [comment]
Thanks again Don.
