### ISSUE TITLE
Docs: CurvePath overwrited Curve's getPoint, getPoints, getSpacedPoints functions.

### ISSUE THREAD

**Issue by gonnavis** [mrdoob/three.js#18323]
Docs: 
CurvePath overwrited Curve's getPoint, getPoints, getSpacedPoints and copy functions, and has different behavior.
Should we write documentation about these functions?
Or, at least add function names in CurvePath to inform users about the overwriting?

**Comment by Mugen87** [comment]
The class description says:

> A CurvePath is simply an array of connected curves, but retains the api of a curve.

Hence, I would not describe the methods again in `CurvePath`. If you think it's helpful, I would just enhance the introductory paragraph with something like:

> The class ensures that derived `Curve` methods also work with an array of connected curves.

**Comment by gonnavis** [comment]
But when I use Path(inherited from CurvePath), I get stuck by the doc in Curve, it say divisions default is 5.
```
.getSpacedPoints ( divisions : Integer ) : Array
divisions -- number of pieces to divide the curve into. Default is 5.
```

I can't find getSpacedPoints in CurvePath and Path's docs, so I think Path use Curve's getSpacedPoints and divisions default is 5.
However, when I dig into the source code, I found it actually is 40 defined in CurvePath.
```
getSpacedPoints: function ( divisions ) {
    if ( divisions === undefined ) divisions = 40;
```

**Comment by Mugen87** [comment]
Um yes, it's unfortunate that the default values are different. 

Okay, I've @mrdoob approves the duplication all the related docs to avoid this discrepancy, we can make a PR.

**Comment by gonnavis** [comment]
Thanks a lot！

**Comment by mrdoob** [comment]
Yeah, I think duplication would clear things up here.

**Comment by Mugen87** [comment]
@gonnavis In this case, feel free to make a PR with the fix 😇.

**Comment by gonnavis** [comment]
OK, I'll try.

**Comment by Mugen87** [comment]
@gonnavis Are you still interested in doing this change? It seems only `getSpacedPoints()` and `getPoints()` have a different `divisions` default and thus need a definition on `CurvePath`.

**Comment by gonnavis** [comment]
Thanks! I'm wondering how many palces need to be changed.
Is this pr https://github.com/mrdoob/three.js/pull/18593 ok?
