### ISSUE TITLE
webgl2: GLSL usampler2d/usampler3d cannot be used for textures using integer internalFormat

### ISSUE THREAD

**Issue by pavan-d** [mrdoob/three.js#18329]
##### Description of the problem

GLSL usampler2d/usampler3d cannot be used for textures using integer internalFormat.

https://github.com/mrdoob/three.js/blob/5f74ae5dc3e2e073e06afcf4a6a2b74a762f9d69/src/renderers/webgl/WebGLUniforms.js#L470-L495

##### Three.js version

- [ ] Dev
- [x] r112
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Can you please demonstrate this issue with a live demo? https://jsfiddle.net/f2Lommf5/

/cc @DavidPeicho

**Comment by DavidPeicho** [comment]
I think we are missing some setter yes. I can do another PR for that.

**Comment by DavidPeicho** [comment]
@pavan-d @Mugen87  implemented here #18336

@pavan-d If you want to give it a shot using a local version, you can clone the branch, `npm run build` and install it locally.

**Comment by pavan-d** [comment]
> @pavan-d @Mugen87 implemented here #18336
> 
> @pavan-d If you want to give it a shot using a local version, you can clone the branch, `npm run build` and install it locally.

Works great.

**Comment by pavan-d** [comment]
> Can you please demonstrate this issue with a live demo? https://jsfiddle.net/f2Lommf5/
> 
> /cc @DavidPeicho

https://jsfiddle.net/4dujhrL1/1/
