### ISSUE TITLE
'Uncaught ReferenceError: d is not defined ...', Error with vue project  'npm run build'

### ISSUE THREAD

**Issue by cs64188** [mrdoob/three.js#18335]
##### Description of the problem

Tthe latest version of OBJLoader2Parallel
`import { OBJLoader2Parallel } from 'three/examples/jsm/loaders/OBJLoader2Parallel.js'`
@vue/cli 4.1.1

when I run 'npm run build' to pack my project

```
Uncaught ReferenceError: d is not defined
    at DefaultWorkerPayloadHandler.handlePayload (a3ceb20b-b062-47b0-b0f2-38112620b4de:94)
    at WorkerRunner.processMessage (a3ceb20b-b062-47b0-b0f2-38112620b4de:113)
    at n (a3ceb20b-b062-47b0-b0f2-38112620b4de:100)
```

but in the dev environment(`npm run server`) was fine.

##### Three.js version

- [ ] Dev
- [x] r112
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
@kaisalmen Can you please have a look here?

**Comment by kaisalmen** [comment]
This is also seems to be a build/tool-chain issue. Can you please provide a link to repository and instructions how to reproduce the problem? This is not directly a three.js issue, but there are now multiple reports where people face issues when packing projects, so I want to understand the issue and include a fix here if possible, but therefore I need to be able to reproduce the issue myself. Thanks.

**Comment by cs64188** [comment]
there is a simple demo [https://github.com/cs64188/threejs-objloader2.git](url) can reproduce the issue.
After build the project and run with `http-server ./dist` , There's error looking like loading the `OBJLoader2Parallel` module. but the other module like `MtlObjBridge, OrbitControls` was fine.
Thanks.

**Comment by kaisalmen** [comment]
@cs64188 this and a regression @geoff-harper reported here #17769 have the same root cause. Independent of react and vue once the app gets build and uglified the `CodeSerializer` creates broken code for the worker as it expects the names of the classes to be unchanged.

I will investigate whether this limitation can be removed...

**Comment by cs64188** [comment]
I replace modify the sourcecode , replace the `manipulator.applyProperties` funcion.
modify `three\examples\jsm\loaders\obj2\worker\paralle\WorkerRunner.js` like this:

**Comment by cs64188** [comment]
I modify the source code ( `\node_modules\three\examples\jsm\loaders\obj2\worker\parallel.WorkerRunner.js`) and it worked.
there is the file content [https://github.com/cs64188/threejs-objloader2/blob/master/public/WorkerRunner.js](url).
I took the 'applyProperties' function to the `DefaultWorkerPayloadHandler.prototype`.

**Comment by kaisalmen** [comment]
I think I have a fix for `CodeSerializer` which resolves the issue globally. I will open a PR possibly later today and ask both of you to verify it then.
