### ISSUE TITLE
Remove console.log messages on renderer initialization

### ISSUE THREAD

**Issue by ludwig801** [mrdoob/three.js#18339]
##### Description of the problem

Any initialization of WebGLRenderer and CSS3DRenderer should not log anything to the console or, if anything, messages such as "THREE.WebGLRenderer <version>" could be logged as verbose (with console.debug, for example).

Such logging may have to be disabled in production environments and, as such, such control should be given.

##### Three.js version

- [x] All up to r112

##### Browser

- [x] All of them

**Comment by Mugen87** [comment]
On  which messages are you referring? The `REVISION` message was removed some time ago. Official examples like the following do not log anything to the console:

https://threejs.org/examples/webgl_animation_skinning_blending
https://threejs.org/examples/css3d_periodictable

**Comment by mrdoob** [comment]
@ludwig801 do you happen to have the Three.js DevTools installed?

**Comment by ludwig801** [comment]
@mrdoob Yeah I do. Darn it, never mind, I'll close this topic right away.
