### ISSUE TITLE
Losing performance with Oculus Quest and r112

### ISSUE THREAD

**Issue by arturitu** [mrdoob/three.js#18338]
##### Description of the problem
I have a VR project that is loading a glTF scene and it was running between 72fps and 62fps (if it is showing more than 40k tris) using r111, but when I changed to r112 it runs at 52fps to 42fps.

I have been testing to edit and back to something similar to r111 code on some of the changes that are listed on [https://github.com/mrdoob/three.js/releases](https://github.com/mrdoob/three.js/releases) but I haven't gotten any improvement.

I think is related to 'WebGLRenderer' but I couldn't test it.

##### Three.js version

- [X] Dev
- [X] r112

##### Browser

- [x] Oculus Browser

##### OS

- [x] Android

##### Hardware Requirements (graphics card, VR Device, ...)
- [x] Oculus Quest

**Comment by Mugen87** [comment]
> loading a glTF scene

Are you using `MeshStandardMaterial` then? The implementation has been changed in `R112` to solve some conceptual issues with this material. It was reported elsewhere that the performance is a bit worse than before. However, the rendering is now "more correct".

If you have performance issues, try to use a cheaper material like `MeshPhongMaterial` or even `MeshLambertMaterial` and see if it helps.

**Comment by arturitu** [comment]
Yes, I'm using MeshStandardMaterial because is the default that is assigned by Blender when you export a Mesh with Principled BSDF material. I could try to change to PhongMaterial when is parsing but I will lose metalness and roughness. Thanks for the explanation.

**Comment by arturitu** [comment]
In any case, I tried to revert #18171 on my three.module.js to test if the performance is better but it continues worse than r111. Are there any other changes that affect the *MeshStandardMaterial* performance?

**Comment by Mugen87** [comment]
Yes, there were a bunch of PR that changed the PBR shader code. And I do not recommend to revert single PRs. Better to use `R111` in this case.

**Comment by arturitu** [comment]
I think I got it, #18178 causes this drops in performance. By default gl.getContextAttributes() with Oculus browser are:
`antialias: true,
alpha: false,
depth: true,
stencil: true`

But the default initLayer on the API is [https://www.w3.org/TR/webxr/#xrwebgllayer-interface](https://www.w3.org/TR/webxr/#xrwebgllayer-interface):

`dictionary XRWebGLLayerInit {
  boolean antialias = true;
  boolean depth = true;
  boolean stencil = false;
  boolean alpha = true;
  boolean ignoreDepthValues = false;
  double framebufferScaleFactor = 1.0;
};
`

If you only set alpha to false it works with better performance.

`var layerInit = {
				antialias: attributes.antialias,
				alpha: false,
				depth: attributes.antialias,
				stencil: attributes.stencil
			};`

I don't know if is ok to force it, or it is something that is on the Oculus Browser side. But it should be good if we could have this fixed to have a better performance on VR.

**Comment by Mugen87** [comment]
I'm not sure I understand. The WebGL context parameter `alpha` is `false` by default. As long as the application does not set it to `true`, `false` is passed to `XRWebGLLayer`.

**Comment by arturitu** [comment]
Sorry, my mistake, if you force to set alpha to true it works better:
`var layerInit = { antialias: attributes.antialias, alpha: true, depth: attributes.antialias, stencil: attributes.stencil };`
Because by default gl.getContextAttributes().alpha is false with Oculus Browser.

**Comment by Mugen87** [comment]
Um, maybe we should report this issue to Oculus instead. It's strange that the `alpha` setting has such a noticeable impact on performance 🤔

/ping @Artyom17

**Comment by arturitu** [comment]
Ok, opened > https://developer.oculus.com/bugs/bug/463364237921559/ thanks

**Comment by Artyom17** [comment]
Default state of alpha in gl context should be set to 'true' and I just have verified it with a simple test.
It is known that setting alpha to false for QCOM chipsets (at least for SD821 and SD835) decreases the perf by up to 30%. I've tried to mitigate that by enforcing alpha internally, and I need to verify that this mitigation is still working.
It would be super helpful if you can provide a test case for profiling.

**Comment by Mugen87** [comment]
> So, someone sets the alpha to false, it seems to me.

That would be `three.js`. As mentioned before, the renderer sets the `alpha` context parameter to `false` by default:

https://github.com/mrdoob/three.js/blob/6c8c7e75f0f04888a814fbebd395cb2055151711/src/renderers/WebGLRenderer.js#L58

**Comment by arturitu** [comment]
I made a test case here:
[https://pacific-globeflower.glitch.me/](https://pacific-globeflower.glitch.me/) It is working around 50fps on Oculus Quest.

![image](https://user-images.githubusercontent.com/5744112/72066142-197e6b80-32e0-11ea-82bb-f2c093383eb3.png)


And here is fixed, with only changed on three.js file is the line 22998 (Forcing alpha: true instead alpha: attributes.alpha) and it is working around 72fps:
[https://pacific-globeflower.glitch.me/fixed.html](https://pacific-globeflower.glitch.me/fixed.html)

![image](https://user-images.githubusercontent.com/5744112/72066152-200ce300-32e0-11ea-9a2b-ce1d0008cf7b.png)

**Comment by toji** [comment]
Confirmed that I'm observing this makes a big difference on Oculus hardware as well. (Thanks for digging up the cause, @arturitu!)

In my case I'm seeing a scene that's running pretty consistently on a Quest at 56-60 FPS with `alpha: false` rock a super steady 72 FPS with `alpha: true` on the `XRWebGLLayer`.

**Comment by mrdoob** [comment]
@Artyom17 

Any chance the Oculus Browser could emulate `alpha: false` using `alpha: true` on relevant headsets/GPUs? I think it would be great if we could hide this from users.

**Comment by Artyom17** [comment]
@mrdoob this is what i am (was) trying to do as aforementioned mitigation strategy, but it seems that something went wrong with it. I am investigating.

**Comment by Artyom17** [comment]
Ok, found the issue, and yeah the issue was indeed in the broken workaround for the slow RGB render targets. I've fixed it and now it seem to work as fast as RGBA. 
The fix will be released in OB 7.2 (ETA - Feb 2020).

**Comment by CamAnNguyen** [comment]
> Ok, found the issue, and yeah the issue was indeed in the broken workaround for the slow RGB render targets. I've fixed it and now it seem to work as fast as RGBA.
> The fix will be released in OB 7.2 (ETA - Feb 2020).

Sorry for opening this one back, I am debugging a display bug in Oculus browser due to the `alpha` attribute (which works fine on Chrome  in desktop), and it is missing from the console log of `XRWebGLLayer` 

```
console.log(xrSession.renderState.baseLayer);
XRWebGLLayer {antialias: true, ignoreDepthValues: true, framebufferWidth: 2432, framebufferHeight: 1344, framebuffer: WebGLFramebuffer}
  antialias: true
  framebuffer: WebGLFramebuffer {}
  framebufferHeight: 1344
  framebufferWidth: 2432
  ignoreDepthValues: true
```

[Chrome image](https://imgur.com/a/YxIUsxy)
[Oculus image](https://imgur.com/a/WWAPV7s)

If I set `alpha` to `false`, the result in Chrome is the same as Oculus (latter image). Is it because of the Oculus or my code?

**Comment by cabanier** [comment]
@CamAnNguyen Is this happening during an immersive session or directly on the page?
Can you send us a reduced test case?

**Comment by CamAnNguyen** [comment]
@cabanier  it happens during the immersive session, you can check this glitch: https://skitter-celestial-danger.glitch.me/ . I think it is a little bit complicated since I am using offscreen canvas then send the imagebitmap to the main thread for texture.

**Comment by CamAnNguyen** [comment]
Hi @cabanier , could you please have a check with my issue ?

**Comment by cabanier** [comment]
@CamAnNguyen I was investigating it yesterday but was pulled into other things today.
What would really help is a reduced test case. Is there a way to reproduce it with an image?
Also, did you say that the problem goes away if the canvas is initialized with `alpha = true`?

**Comment by CamAnNguyen** [comment]
@cabanier I will try to check it with image then.
Regarding the `alpha=true`, is the render setting from A-FRAMEL: 
With: `<a-scene renderer="alpha: false">` ==> Chrome is displaying the same as in Oculus Browser

**Comment by CamAnNguyen** [comment]
@cabanier  I am sorry to bother you, it seems my problem is because of the transparency of the final image, similar to this issue: https://github.com/mrdoob/three.js/issues/12148

**Comment by cabanier** [comment]
Is this problem only happening on Oculus Quest, or does it also show on other devices?

**Comment by CamAnNguyen** [comment]
@cabanier I have tested again, it happens with the Chromium Edge also

**Comment by cabanier** [comment]
OK. Then it's most likely a bug in three.js

**Comment by mrdoob** [comment]
@CamAnNguyen Please, open a new issue for it.
