### ISSUE TITLE
The mesh of GLTF model cannot be recongnized as type Mesh or Object3D

### ISSUE THREAD

**Issue by Rakujitsu** [mrdoob/three.js#18346]
##### Description of the problem

I need to load external GLTF models and unpack them to use their Mesh object in my scene. I use following code to unpack child:
```
      this.gltfLoader.load(url, (gltf) => {
        const model = gltf.scene.children[0];
        Object.defineProperty(res, 'entity', { value: model });
      });
```
But when I was about to remove them from scene and dispose their resources such as material or texture, I found its type is strange:
```
      gltf instanceof Object3D; // false
      gltf instanceof Mesh; // false
      gltf.isMesh; // true
```
I guess the gltf model should be an instance of Mesh, but it isn't. Is this a bug?

##### Three.js version

- [ ] Dev
- [x] r112
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Please redirect your question to the three.js [forum](https://discourse.threejs.org).
