### ISSUE TITLE
All vertex colors are white if BufferAttribute is backed by Uint8Array

### ISSUE THREAD

**Issue by mauve** [mrdoob/three.js#18341]
##### Description of the problem

I am trying to render a point cloud from a Kinect device. My colors are coming from a `Uint8Array` of RGBA data. However all my points are always white. I adopted the example at https://threejs.org/examples/?q=points#webgl_buffergeometry_points and managed to get it to work with the vertex positions but cannot get the colors from my Uint8Array.

I found this bug #8358 which has been closed as fixed. The jsfiddle mentioned in that bugreport has the same problem I am seeing.

https://jsfiddle.net/huningxin/594jjzb9/3/ (original fiddle from bug #8358)
https://jsfiddle.net/h3c62gs5/ (version which also sets normalized to false)

The fiddle has code for both `Float32Array` and `Uint8Array` and if I switch back and forth the vertices get colors (float32) or turns all white (Uin8t).

##### Three.js version

- [x] Dev
- [x] r111

##### Browser

- [x] Electron 7.1.1
- [x] Edge Insider (based on Chromium)

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mauve** [comment]
Screenshot showing white color (`Uint8Array`)

![image](https://user-images.githubusercontent.com/795800/72013280-d7144a80-325d-11ea-9327-fba67084aa5a.png)

Screenshot showing working colors (`Float32Array`)

![image](https://user-images.githubusercontent.com/795800/72013388-075be900-325e-11ea-8838-93a0d5584827.png)

**Comment by Mugen87** [comment]
You have to set `BufferAttribute.normalized` to `true` if you define colors like that. It also a bit more correct to wrap each generated color value into a `Math.floor()` call.

https://jsfiddle.net/bfq530ps/1/

**Comment by makc** [comment]
@Mugen87 isnt `[]=` flooring it any way, since this is integers array?

**Comment by mauve** [comment]
I now get colors in my point cloud when I set `geometry.attributes.color.normalized = true;` but I am a little confused not because first I initialize with `geometry.setAttribute('color', new THREE.BufferAttribute(pointcloud.colors, 4, false));` i.e. I set `normalized = false` when I add the attribute because my data is not normalized (my data is 0-255 rather than 0.0-1.0).

Why do I need to set `geometry.attributes.color.normalized = true;` if my data is non-normalized?

Disclaimer: I am a total noob and have no idea what I am doing, I am probably mixing up everything.

**Comment by Mugen87** [comment]
> @Mugen87 isnt []= flooring it any way, since this is integers array?

Yes, but I just want to highlight that this type of array represents integers. It seems more right to me to provide integers to the array in the first place.

> hy do I need to set geometry.attributes.color.normalized = true; if my data is non-normalized?

`Uint8Array` holds values in the range of '[0,255]`. You need to normalized this data into the range of `[0,1]` so the shader is able to correctly process the color values. Please read the docs for more information about this topic:

https://threejs.org/docs/index.html#api/en/core/BufferAttribute

**Comment by Mugen87** [comment]
Closing. Please use the [fourm](https://discourse.threejs.org/) if you need more help.
