### ISSUE TITLE
WebXR: Set `isPresenting` flag before dispatching `sessionstart` event

### ISSUE THREAD

**Issue by KabirSheemul** [mrdoob/three.js#18350]
##### Description of the problem

While starting an XR session, `sessionstart` event is dispatched from [WebXRManager.js](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webxr/WebXRManager.js#L111) after a successful XR session has been established. After that, the [`isPresenting`](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webxr/WebXRManager.js#L113) flag is set to true. As a result when we add an event listener for `sessionstart`, in the callback function `isPresenting` is returning false. 

```
function onRequestReferenceSpace( value ) {
    referenceSpace = value;
    animation.setContext( session );
    animation.start();
    scope.dispatchEvent( { type: 'sessionstart' } );
    scope.isPresenting = true;
}
```
Is this behavior intentional? I think we should set the flag true before dispatching the event.

##### Three.js version

- [x] r112

**Comment by Mugen87** [comment]
If the order is change, it's also necessary to switch the order when `sessionend` is fired. Meaning `isPresenting` should be set to `false` first and then `sessionend` is dispachted.

**Comment by timothyallan** [comment]
> If the order is changed, it's also necessary to switch the order when `sessionend` is fired. 
Meaning `isPresenting` should be set to `false` first and then `sessionend` is dispachted.

This would solve some hacks I'm currently doing. In particular, I currently have to do a timeout hack on `sessionend` to get around this. My canvas needs to be resized after the session is ended, but I can't resize it as presenting is true still on `sessionend`.
