### ISSUE TITLE
Raycaster page example code: coordinates need to be adjusted by canvas element bounding rect size?

### ISSUE THREAD

**Issue by roschler** [mrdoob/three.js#18352]
My comment is in reference to the code shown in the raycasting example shown on this doc page:

https://threejs.org/docs/#api/en/core/Raycaster

This code calculates the current mouse 2D location with this code in the document mouse move event:
```
    g_Mouse.x = ( event.clientX / window.innerWidth ) * 2 - 1;
    g_Mouse.y = - ( event.clientY / window.innerHeight ) * 2 + 1;
```

I found that I had to modify that code to account for the offset of the ThreeJS canvas element within the HTML page, especially if it is nested inside other elements.  Here is the modified code.  Of course, you have to assign an ID to your canvas for this to work.  I assign the ID 'three-js-canvas' to my renderer DOM element::
```
    g_Mouse.x = ( event.clientX / window.innerWidth ) * 2 - 1;
    g_Mouse.y = - ( event.clientY / window.innerHeight ) * 2 + 1;
    
    let canvasBoundingRect = document.getElementById('three-js-canvas').getBoundingClientRect();
   
    let adjX = canvasBoundingRect.width / window.innerWidth;
    g_Mouse.x *= adjX;
    
    let adjY = canvasBoundingRect.height / window.innerHeight;
    g_Mouse.y *= adjY;
```
Without the adjustments for the difference in size between the canvas bounding rect dimensions and the window client area dimensions, the subsequent calculations are wrong because the 2D translations result in calculations that place the mouse closer to the center of the canvas than it actually is, throwing off any intersecting object code.

Is my premise correct?  Or am I doing something wrong that is causing me to need this adjustment?  The original code appears to work fine if the canvas is the only element on the page.  For me at least, the trouble started when the canvas was smaller than the page client area.

**Comment by Mugen87** [comment]
I believe this topic was already discussed several time at the forum and stackoverflow e.g.

https://stackoverflow.com/questions/34831626/three-js-raycaster-is-offset-when-scollt-the-page

**Comment by Mugen87** [comment]
Feel free to improve the documentation by clarify the assumptions of the code.
