### ISSUE TITLE
Normal issue with double sided StandardNodeMaterial

### ISSUE THREAD

**Issue by njarraud** [mrdoob/three.js#18363]
##### Description of the problem

A new issue appeared with double sided StandardNodeMaterial when I was moving from r108 to the latest development version.

When using a mesh modeled with symmetry in mind and uvs of mirrored sections on top of each other, normals are not displayed properly when StandardNodeMaterial is doubled sided (one sided works properly).

In the jsfiddle example below, I used a cube with no top. The one on the left uses MeshStandardMaterial and is displayed properly. The one on the right uses StandardNodeMaterial and has normal issues. 

If you comment line 85 `materialNode.side = THREE.DoubleSide;` normals are back to normal.

* [jsfiddle](https://jsfiddle.net/supavrkn/2/)

![blender](https://user-images.githubusercontent.com/45501180/72197561-85e79f00-3487-11ea-8fec-9bdf17fc66c5.jpg)
![double sided](https://user-images.githubusercontent.com/45501180/72197583-cf37ee80-3487-11ea-85c3-8fdb2837b813.jpg)

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

/ping @sunag

**Comment by Mugen87** [comment]
Closing since the old node material has been removed. It can be reopened if the new `MeshStandardNodeMaterial` shows the same issue.
