### ISSUE TITLE
Normal issue with new pmremGenerator and StandardNodeMaterial

### ISSUE THREAD

**Issue by njarraud** [mrdoob/three.js#18360]
##### Description of the problem

In the process of moving my app to the latest version of Threejs to have access to the new pmremGenerator, I found an issue with StandardNodeMaterial which wasn't existing before when I was using r108.

When an environment map is used, the normal input is sort of washed away/faded.
When no environment map is used and other types of lights are in the scene, it is back to normal.

I also made a comparison between StandardNodeMaterial and MeshStandardMaterial.
The object with MeshStandardMaterial is correctly rendered with the new pmremGenerator but not the one with StandardNodeMaterial.

I made two jsfiddle. First one is using an environment map - left is MeshStandardMaterial, right is StandardNodeMaterial. Second one is using point lights only:
* [Environment Map](https://jsfiddle.net/23Lzwr1k/)
* [Point Lights](https://jsfiddle.net/5rk90atp/)

![env](https://user-images.githubusercontent.com/45501180/72183271-684c1280-3452-11ea-8216-75da6344bb44.jpg)

![point](https://user-images.githubusercontent.com/45501180/72183274-6aae6c80-3452-11ea-9d2c-fa7b793e72aa.jpg)

##### Three.js version

- [x] Dev

/ping @sunag

**Comment by njarraud** [comment]
I am really looking forward to finding a solution to this issue. If anybody has even a rough idea of which part of the code I shall look into I am really keen.

/ping @sunag

**Comment by WestLangley** [comment]
@njarraud Thanks for this, and for your other excellent Node test cases!

I do not know where the problem is, but I do know that it has been a challenge to keep Node up-to-date with all the changes in the core library. @sunag has done a great job making those change whenever he is able, but if you'd like to have a go at it, comparing glsl chunks is one reasonable place to start.

BTW, the differences you refer to are subtile enough not to readily be apparent -- at least to me. One thing you could do is create two scenes, each with one light, and then make two render passes. That way, each model is identically-lit. Describing what you see as different is helpful.

**Comment by sunag** [comment]
I think that this issue already had detect in PREM Update https://github.com/mrdoob/three.js/pull/18161#issue-353226273 ( Unsolved issues ) 

> @njarraud Thanks for this, and for your other excellent Node test cases!

Yes. Thanks, too.

>  @sunag has done a great job making those change whenever he is able

Thank you @WestLangley.  I hope soon I can work it out in full time for it will be faster... 
You help aways been instrumental in doing a great job.

> if you'd like to have a go at it, comparing glsl chunks is one reasonable place to start.

@njarraud This is exactly what you would do too.

**Comment by njarraud** [comment]
@sunag has created an awesome system and unlocked new possibilities. He is my man. I cannot thank him enough for what he created :-)

However this issue makes everything fall down for my use case. The new pmremGenerator is so much better, faster and not buggy compared to the old one but on the other hand the whole system that I developed for the past 6 months and the wow factor resulting is kinda gone because of it.

I do not expect sunag to solve it for me and your pointer is very welcome. I'll investigate.

I made a couple of examples to get a better idea of the visual differences between both material systems (both used to look identical).

Environment texture:
![envmap](https://user-images.githubusercontent.com/45501180/72304899-e7ea1380-36d6-11ea-8ec9-606d7992a04e.gif)
Here are the non compressed images:
![envmap_MeshStandardMaterial](https://user-images.githubusercontent.com/45501180/72304942-0f40e080-36d7-11ea-8804-a6de4db2e3df.jpg)
![envmap_StandardNodeMaterial](https://user-images.githubusercontent.com/45501180/72304945-10720d80-36d7-11ea-803c-071256e0074e.jpg)

The whole benefit of baking round edges on a normal map is gone. It is even more obvious for brighter colours where you cannot almost not see at all the normals.
![envmap_StandardNodeMaterial_lines](https://user-images.githubusercontent.com/45501180/72305152-c2a9d500-36d7-11ea-86d7-ab59c468064c.jpg)


Point Light - No difference at all. They are identical to the pixel
![pointLight_MeshStandardMaterial](https://user-images.githubusercontent.com/45501180/72304990-34cdea00-36d7-11ea-96dd-0d424d6cd54e.jpg)

**Comment by njarraud** [comment]
So I spent hours trying to understand more about how the shader system works and how to compare both. It looks like the issue comes from the irradiance calculation. The radiance seems to be correct.

Radiance only (irradiance = vec3(0.0)) - Both are exactly identical:
![radiance](https://user-images.githubusercontent.com/45501180/72319894-4d54f900-3705-11ea-83ae-c5fc01693b64.jpg)

Irradiance only (radiance = vec3(0.0)):
![irradiance](https://user-images.githubusercontent.com/45501180/72320002-973ddf00-3705-11ea-8563-006c0e28297e.gif)

**Comment by njarraud** [comment]
I finally managed to get the same result with MeshStandardMaterial and StandardNodeMaterial.
I replaced:
`nodeT23 = vWNormal;`
by 
`nodeT23 = inverseTransformDirection( geometry.normal, viewMatrix );`
for the calculation of the irradiance.

This is the calculation used by the standard material system as found in the file **envmap_physical_pars_fragment.glsl.js** at line 10 in the **getLightProbeIndirectIrradiance** function:
`vec3 worldNormal = inverseTransformDirection( geometry.normal, viewMatrix );`

Does it mean that the normal node with the world scope shall be updated or simply that the irradiance calculation requires something else?

**Comment by WestLangley** [comment]
@njarraud  Nice detective work!

/ping @elalish 
/ping @sunag

**Comment by elalish** [comment]
@njarraud I think you're on the right track. It looks like the reflection is being passed the output of NormalNode (which is only the vertices' contribution) rather than NormalMapNode, which adds the effect of the normal map. In the core shaders I use the first for anti-aliasing and the second for building the reflection vector. That's a likely source of confusion, but I'm not familiar enough with the Node system to fix it myself. @sunag Does that make sense to you?

**Comment by sunag** [comment]
> I finally managed to get the same result with MeshStandardMaterial and StandardNodeMaterial.

@njarraud Wow, you did things get easy now... I should publish a PR in the next few days.

> @sunag has created an awesome system and unlocked new possibilities...

@njarraud I don't know how to thanks for this. You are contributing a lot too.
I am very happy with this, thank you :-)

> @sunag Does that make sense to you?

@elalish Yeah, It makes a lot of sense.

**Comment by sunag** [comment]
@elalish Wherein I can find the `anti-aliasing` code in `shader`?

**Comment by elalish** [comment]
@sunag It's [here](https://github.com/mrdoob/three.js/blob/c466bb3336f494514b537798d9be7f98ad807f25/src/renderers/shaders/ShaderChunk/lights_physical_fragment.glsl.js#L9)
