### ISSUE TITLE
Why is RawShaderMaterial slower than ShaderMaterial?

### ISSUE THREAD

**Issue by ramirofages** [mrdoob/three.js#18380]
Hello, I was hoping to optimize my shader by using the RawShaderMaterial and only send the uniforms that I need, but when I was doing a quick test to see if it was going to be worth it, I noticed that the RawShaderMaterial was actually slower than the ShaderMaterial. The test I'm using just spawns 10000 cubes into the scene and then I run the profiler. Here is the sample code:

```javascript
<script src="js/three.js"></script>
<script src="js/orbit.js"></script>
		
		<script>
			var renderer = new THREE.WebGLRenderer({antialias: true});
			renderer.setSize( window.innerWidth, window.innerHeight );
			document.body.appendChild( renderer.domElement );

			var scene = new THREE.Scene();
			var camera = new THREE.PerspectiveCamera( 75, window.innerWidth/window.innerHeight, 0.1, 1000 );

			
			var controls = new THREE.OrbitControls( camera );
			controls.update();

			camera.position.z = 3;
			camera.updateMatrixWorld();
			camera.updateProjectionMatrix();
			camera.matrixWorldInverse.getInverse(camera.matrixWorld);


let vert = `
// attribute vec3 position;
// uniform mat4 modelMatrix;
// uniform mat4 viewMatrix;
// uniform mat4 projectionMatrix;

void main(){
	gl_Position = projectionMatrix * viewMatrix * modelMatrix * vec4(position, 1.0);
}
 `;

let frag = `
 void main(){	
   gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
}
 `;

	    

			let material = new THREE.ShaderMaterial({
	      uniforms: {
	         modelMatrix: {value: new THREE.Matrix4()},
	         viewMatrix: {value: new THREE.Matrix4().copy(camera.matrixWorldInverse)},
	         projectionMatrix: {value: new THREE.Matrix4().copy(camera.projectionMatrix)}
	      },
	      vertexShader: vert,
	      fragmentShader: frag
	    });

			var geometry = new THREE.BoxBufferGeometry( 1, 1, 1 );


			let cubes = [];
			for(let i=0; i< 10000; i++)
			{
				var cube = new THREE.Mesh( geometry, material.clone() );
				scene.add( cube );
				cubes.push(cube);
			}




			var animate = function () {
				controls.update();
				renderer.render(scene, camera);
				requestAnimationFrame( animate );

			};

			animate();
		</script>
```

To test the RawShader material just uncomment the uniforms in the vertex shader, and add the "Raw" to the ShaderMaterial name. In the profiler I can see that the shadermaterial takes around 28ms, while the RawShaderMaterial takes 35ms!

##### Three.js version

- [ ] Dev
- [X] r112
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Demo with `RawShaderMaterial`: https://jsfiddle.net/501gom3j/
Demo with `ShaderMaterial`: https://jsfiddle.net/501gom3j/1/

I see no difference on my iMac. I have 21 FPS in both cases.

**Comment by ramirofages** [comment]
Hmmm weird but ok. Are these the expected results though? I was hoping that setting less uniforms would provide some benefits but it looks I was wrong

**Comment by Mugen87** [comment]
I doubt that the few less uniforms will be noticeable in the framerate.

In genreal, the FPS in the example is so bad because you have 10.000 draw calls which is an extreme amount. Using `THREE.InstancedMesh` will be a much greater performance boost than using  `RawShaderMaterial` over `ShaderMaterial`. Of course using instanced rendering only works if you have to render many objects of the same type in your scene.

**Comment by ramirofages** [comment]
I see.. alright thank you! My use case has 66 different objects and each one of them is setting around 10-12 uniforms (all of them vec3 or vec4) so I wanted to see if reducing that amount was going to make a significant difference. The app needs to run on a specific android computer (heavily underpowered, sadly). Thanks for your time
