### ISSUE TITLE
three.min.js from CDN download is broke

### ISSUE THREAD

**Issue by greentec** [mrdoob/three.js#18381]
##### Description of the problem

If I load from cdn download of three.min.js, it broke.
But if I load from three.js, it worked.

source code ↓
```
<script src='https://cdn.rawgit.com/mrdoob/three.js/master/build/three.min.js'></script>
```

error meessage ↓
```
Uncaught SyntaxError: Unexpected end of input
```

##### Three.js version

- [ ] Dev
- [ ] r112
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by greggman** [comment]
rawgit was deprecated a while ago

https://rawgit.com/

> # RawGit has reached the end of its useful life
>
>  October 8, 2018
>
> RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.

you probably want to use jsdeliver or unpkg

**Comment by greentec** [comment]
Thank you for your help!
