### ISSUE TITLE
How to check if STL is loading if I use .parse instead of .load?

### ISSUE THREAD

**Issue by daydream05** [mrdoob/three.js#18388]
I'm using this [STLLoader](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/STLLoader.js) to load STL files. But instead of using
```js
new STLLoader().load(url, geo => geo)
```
I'm using the parse method instead instead since I load the STL files as data array buff.

```js
new STLLoader().parse(arrayBuff)
```

The problem, however, is that I lose access to the `LoadingManager` to check if my stl started loading. Is there a way to check if file is loading when I used  the `.parse` method?

**Comment by donmccurdy** [comment]
STLLoader's `parse` method is synchronous — it will return a result directly and immediately, or throw an error, rather than using a callback.

For help questions we recommend using the forum (discourse.threejs.org/) as we use GitHub for bugs and feature discussion.
