### ISSUE TITLE
Three.js not working on IE 11

### ISSUE THREAD

**Issue by EugeneFitzher** [mrdoob/three.js#18392]
##### Description of the problem

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/hyok6tvj/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/c5m1kazu/) (dev branch)

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

Hello!
I have an issue that Three.js is not working on IE 11 ( Windows 10 ).
IE11 version is : 11.535.18362.0.
Microsoft Edge, chrome, firefox is working fine but  IE 11 does not.
I also tried to [https://threejs.org/examples](url), it doesn't work too.
I have 4 computers, but all of them have same issue.

Can somebody help me?

**Comment by donmccurdy** [comment]
The website has dropped support for IE11, although the threejs library itself still supports IE11. If you're having trouble getting a project that depends on threejs running in IE11 correctly, please use the forums (https://discourse.threejs.org/) for help.
