### ISSUE TITLE
request for lerp(a, b, c)

### ISSUE THREAD

**Issue by drcmda** [mrdoob/three.js#18404]
##### Description of the problem

currently objects are defined

```jsx
object.set(a, b, c)
```

but, for some reason, the lerp function goes ... 🤷‍♂️

```jsx
object.lerp(new ObjectConstructor(a, b, c), alpha)
```

all that i have seen, vectors, colors, etc. the constructor is unnecessary, creates memory overhead (in a loop, class construction every frame), makes it harder to operate (dummy objects to save memory), **and conflicts with the set method**.

if this api would be consistent it would open crazy possibilities in the react world. it could behave like apples swiftUI basically, which would be a game changer:

```jsx
function AnimatedPingPong() {
  // define state
  const [x, set] = useState(true)
  // flip state every second
  useEffect(() => void setInterval(() => set(x => !x), 1000), [])
  // write out state as x swinging between -1 and 1
  return (
    <mesh position={[x ? -1 : 1, 0, 0]} position-lerp={0.1}>
      <sphereBufferGeometry attach="geometry" />
    </mesh>
}
```

automated animation would not be possible today, because due to the api the reconciler must know how the constructor is shaped, which it can't. it doesn't what what a color is or that the argument needs to be shaped { x: 1, y: 2, z: 3 }.

##### Suggestion

just allow both:

```jsx
vector.set(1, 2, 3)
vector.lerp(1, 2, 3, 0.1)
vector.lerp(new Vector(1, 2, 3), 0.1)

color.set("red")
vector.lerp("red", 0.1)
vector.lerp(new Color("red"), 0.1)
```

- very easy to implement
- can be made typesafe in TS
- it's backwards compatible
- saves memory
- makes threejs easier
- enables swiftUI-like behaviour in the declarative world. 👍

or:

```jsx
vector.set(1, 2, 3)
vector.lerp(1, 2, 3, 0.1)
vector.lerpVector(new Vector(1, 2, 3), 0.1)

color.set("red")
vector.lerp("red", 0.1)
vector.lerpColor(new Color("red"), 0.1)
```

could at least be made backward compatible for a couple of months by testing against props.

**Comment by donmccurdy** [comment]
Our usage pattern is fairly consistent: `set(...)` re-initializes an object from its primary member properties, `copy(...)` re-initializes an object from another object of the same type. `lerp(...)` is consistent with the latter, as are most modifier methods, so I don't quite follow the consistency argument on this.

On memory usage, we universally discourage creating objects in the render loop — but we accomplish that with an inversion of the order you're suggesting. The *caller* is responsible for reusing a parameter across calls:

```javascript
var _v = new THREE.Vector3(...);

function hot ( x, y, z ) {
  _v.set( x, y, z );
  mesh.position.lerp( _v, 0.5 );
}
```

So this proposal doesn't inherently save memory, it shifts the responsibility for saving memory. Not saying that as an argument against your suggestion, but to clarify the effects here. I couldn't tell you whether that pattern is compatible with a reconciler, and maybe that's the core question.

Is this request specific to the `lerp` method? Or would the same argument apply to Vector3's `addScaledVector`, `applyAxisAngle`, `applyEuler`, `applyMatrix3`, `applyMatrix4`, `clamp`, `cross`, `distanceTo`, `divide`, `dot`, `max`, `min`,`muliply`, ... ? The application to `lerp()`, specifically, doesn't seem unique. Supporting primitive values interchangeably with Math classes would be a pretty major change, library-wide. 🤔

**Comment by drcmda** [comment]
hmmm, raw values would be a welcome addition for sure, haven't thought about the others, just the two were sticking out to me. but yes, i've wished countless of times i could skip object creation when dealing with state or raw data values.

**Comment by donmccurdy** [comment]
> isn't this easier to grasp?

It's ergonomic, I agree. Other possible effects though:

1. Some methods won't directly operate on primitive arguments, and will have to check the type and populate a temporary object to complete their work. In some cases, like parsing CSS colors, that would have performance cost.

2. Performance-critical functions should ideally be monomorphic. Using inconsistent types (polymorphism) can prevent V8 from optimizing that function, or cause it to throw out optimized versions of the function. See the section on *The Optimizing Compiler* from [Performance Tips for JavaScript in V8](https://www.html5rocks.com/en/tutorials/speed/v8/):

> Monomorphic functions and constructors can be inlined entirely (that's another reason why monomorphism is a good idea in V8).

See also, [Why do monomorphic and polymorphic matter in JavaScript?](https://stackoverflow.com/a/37059056/1314762) and [What's up with monomorphism](https://mrale.ph/blog/2015/01/11/whats-up-with-monomorphism.html). I'm under the impression that the advice still holds for modern browsers, but I haven't done profiling on this myself.

**Comment by drcmda** [comment]
I see. Yes, it looked too good and easy but I didn't consider the consequences.

**Comment by gkjohnson** [comment]
Could you automatically create cached versions of these objects for the sake of lerping here? If I'm understanding what you want this might help -- you wouldn't need to know the object type ahead of time if you used the types constructor:

```js
const cache = new Map();
const hot = ( x, y, z ) => {

  const cons = mesh.position.constructor;
  let tmp= cache.get( cons );
  if ( ! tmp ) {
    
    tmp = new cons();
    cache.set( cons, tmp );

  }
  cache.set( x, y, z );
  mesh.position.lerp( tmp, 0.5 );

}

```

**Comment by drcmda** [comment]
position is basically written like `<mesh position={[1, 2, 3]} />`. it doesn't know position is a vector3, only typescript does and would complain if i do `position="red"`. but the reconciler just sees the array and notices that the target prop has a `.set` function, so it spreads it over the object: `object.set(...prop)`. that's why i thought lerp wouldn't work, but you're right, a constructor map with temp objects could indeed work, nice idea!
