### ISSUE TITLE
RoughnessMipmapper fails to restore the renderer's viewport, scissor, and scissor-test settings

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#18409]
`RoughnessMipmapper` fails to restore the renderer viewport, scissor, and scissor-test.

##### Three.js version

- [ x ] Dev

/ping @elalish

**Comment by elalish** [comment]
@WestLangley I'm fixing the viewport and scissor issues, but RoughnessMipmapper ignores the outputEncoding and tonemapping settings by using a RawShaderMaterial, I believe. Am I incorrect?

**Comment by WestLangley** [comment]
Oh. You are correct. It is only the viewport and scissor.
