### ISSUE TITLE
PMREMGenerator fails to properly restore the renderer's viewport

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#18408]
The actual viewport must be saved and restored. Possibly, the same goes for `scissor` and `scissorTest`.

Unfortunately, we reuse the same renderer for multiple purposes...

##### Three.js version

- [ x ] Dev

/ping @elalish

**Comment by elalish** [comment]
I'm fixing this, but it would be awesome if more of this state could live in the render targets so that we wouldn't have to constantly set and reset the renderer state.

**Comment by elalish** [comment]
Ha, nevermind! Seems this is already true. I'm pretty sure that wasn't there last time I looked...

**Comment by jpmolla** [comment]
Once my Windows 10 NVidia drivers updated (for Nvidia GeForce GTX 960M) the issue still remain on [this link](https://raw.githack.com/mrdoob/three.js/dev/examples/?q=nodes#webgl_materials_envmaps_pmrem_nodes). Here are the result I noticed on browsers console.
![Chrome console](https://user-images.githubusercontent.com/1607511/72661920-90062200-39e0-11ea-8214-8202c8912283.png)
![Firefox console](https://user-images.githubusercontent.com/1607511/72661964-1b7fb300-39e1-11ea-9655-304f906fc11a.png)

I also tried on an Ubuntu 19.10 (hardware computer not VM) and there is no issue. Ironically I have an integrated Intel HD Graphic card on it, not the most powerfull.
