### ISSUE TITLE
PCDLoader using a worker?

### ISSUE THREAD

**Issue by geoff-harper** [mrdoob/three.js#18417]
How feasible is it to adapt a multi-thread approach to this loader similar to how OBJLoader2Parallel does it? What would be involved? I see that @kaisalmen as mentioned something similar in previous issues but don't see anything recent.

**Comment by Mugen87** [comment]
Related #18234

**Comment by kaisalmen** [comment]
I tried that in scope of the `WorkerLoader` that I never finished, because the approach was not good. The linked issue and jsm in workers can make your request potentially easy to code in the future, I think.

**Comment by Mugen87** [comment]
Let's track all loader/worker issues in #18234.
