### ISSUE TITLE
Dissapearing objects

### ISSUE THREAD

**Issue by celine3d** [mrdoob/three.js#18412]
##### Description of the problem

When moving camera(drag or zoom) at some point instances of InstancedMesh become invisible, although other objects are visible(Axis helper or pink box in the example shown below:)

The issue is presented in demo below:
https://jsfiddle.net/1s0wehk6/10/

##### Three.js version

- [ ] Dev
- [ ] r112
- [ ] ...

##### Browser
- [ X] Chrome

##### OS
- [ X] Windows

**Comment by DrMcMarco** [comment]
It's because the mesh is frustum culled. If the "original" mesh disappears from the view frustum every other instance disappears as well.

You can prevent this by disabling frustum culling for the mesh:

``
mesh.frustumCulled = false;
``

**Comment by celine3d** [comment]
Oh thank you a lot!!!!

**Comment by DrMcMarco** [comment]
By the way, I'm not sure if this is actually a bug or not.
I just use this as a workaround since I ran into the same issue.

**Comment by WestLangley** [comment]
Either of the following patterns are appropriate, depending on your use case:

```js
mesh.frustumCulled = false; // optional
```
or
```js
mesh.geometry.boundingSphere = new THREE.Sphere( new THREE.Vector3( 0, 0, 0 ), 10 ); // optional
```

**Comment by donmccurdy** [comment]
Related: https://github.com/mrdoob/three.js/issues/18334
