### ISSUE TITLE
any way to enable the "taper" in "modules/three-tube-geometry.js" again?

### ISSUE THREAD

**Issue by benjaminadrom** [mrdoob/three.js#18423]
i saw it at:
https://github.com/mrdoob/three.js/pull/5679/commits/79a082a0f60eb63393b3b547f8bf75422c135653

but it seems to be deprecated

**Comment by Mugen87** [comment]
Yes, `taper` was removed with `R82`, see migration guide:

https://github.com/mrdoob/three.js/wiki/Migration-Guide#r81--r82

The parameter was removed for good reasons, see #9841.

**Comment by benjaminadrom** [comment]
oh no... thanks!
any other way to create such a tapered geometry??

**Comment by Mugen87** [comment]
Maybe this PR could be useful to you: https://github.com/mrdoob/three.js/pull/13971

**Comment by benjaminadrom** [comment]
Not quite sure, that PR is not in the master right?  because it's still an open PR... :)
but thanks i will check if i can alter that current code with that pr-code...
