### ISSUE TITLE
Doc issue: "Creating-a-scene" misleads.

### ISSUE THREAD

**Issue by dcromley** [mrdoob/three.js#18440]
Threejs is so great -- I hope I'm helping.  It's not a big deal anyhow, but:

threejs.org/docs/#manual/en/introduction/Creating-a-scene
has the <style>
  canvas { width: 100%; height: 100% }
which is unreferenced.  Leaving it out makes no difference.  It is mis-leading.  
I was pursuing if there was a difference between rendering to a "canvas" or a "div".
Regards, Dave

**Comment by Mugen87** [comment]
Yes, it might be better to replace the existing CSS with:
```css
canvas { display: block;  }
```
