### ISSUE TITLE
webgl_postprocessing_godrays example - "sun" jumps & flips "downwards"!

### ISSUE THREAD

**Issue by wolfgangvonludwigsburg** [mrdoob/three.js#18446]
In the **webgl_postprocessing_godrays.html** example
I've put in an **OrbitControl** ..

Under some view angles the position of the "sun" jumps & flips "downwards"!
(see image)
     
![sun_flipped](https://user-images.githubusercontent.com/9339385/72839029-d0d89200-3c91-11ea-80e4-be033748c63a.jpg)

The sun, instead of standing "above" the grid, and raying shadows "downwards",
it throws its rays "upwards" ..

Maybe you've like to have a look at:

https://wolfgangvonludwigsburg.github.io/three.js/examples/webgl_postprocessing_godrays.html

I love 3js,
Thank you!

**Comment by Mugen87** [comment]
Um, this can also be reproduced in the official examples without modifications. You just have to move the camera as far as possible to the top or sides.

It seems the jump happens because the signs of the sun's screen space position vector components change.

**Comment by wolfgangvonludwigsburg** [comment]
Hi Michael,

thx for your fast reply!

I've built in a **"Matrix display"** showing the **camera matrix.elements**,
you've like to have a look at, here:

https://wolfgangvonludwigsburg.github.io/three.js/examples/webgl_postprocessing_godrays_2.html

Maybe you experts just "see" immediately looking at the matrix, what' going wrong .. ;-)

**Comment by makc** [comment]
@wolfgangvonludwigsburg like @Mugen87 says, it is probably when screenSpacePosition.copy( sunPosition ).project( camera ); fails due to the sun going behind the camera. there needs to be a flag passed to the shader that this is the situation.

**Comment by makc** [comment]
[here](https://github.com/wolfgangvonludwigsburg/wolfgangvonludwigsburg.github.io/pull/1): it looks kinda weird when you fix it...
![Screen Shot 2020-03-06 at 23 04 47 ](https://user-images.githubusercontent.com/242577/76126318-101f3000-5fff-11ea-95d9-ad59d48beb6c.png)
![Screen Shot 2020-03-06 at 23 05 03 ](https://user-images.githubusercontent.com/242577/76126319-11505d00-5fff-11ea-81a2-f27d96f342ec.png)

**Comment by makc** [comment]
oh wow, github has bugs too:
![Screen Shot 2020-03-06 at 23 11 05 ](https://user-images.githubusercontent.com/242577/76126610-d569c780-5fff-11ea-9c76-f7f96db045b4.png)
