### ISSUE TITLE
Docs - LightProbe, LightProbeGenerator entries are missing!

### ISSUE THREAD

**Issue by wolfgangvonludwigsburg** [mrdoob/three.js#18459]
It seems that **documentation entries** for
- **THREE.LightProbe**
- **THREE.LightProbeGenerator**
are missing ..
(missing entries in <three.js>/docs/list.js)

LightProbe were integrated around r104.

What I only found is a doc entry for
- THREE.LightProbeHelper

BTW, maybe a tiny tool would be helpful,
that could check the accordance between
the source code classes tree,
and their corresponding doc entries/file existance .. ?

Pls drop me a word, if I could contribute ..
(.. is LightProbe developer Info available ?)

**Comment by Mugen87** [comment]
Feel free to create the doc pages for `LightProbe` and  `LightProbeGenerator`. You may want to start just with the technical skeleton (method names, signature etc.) and add the description with a subsequent PR. From my experience, adding the description will take noticeable more time for review.

**Comment by wolfgangvonludwigsburg** [comment]
Ok, I will try my best to do it ..
Since I am new, it will take a little time ..

**Comment by Mugen87** [comment]
@wolfgangvonludwigsburg Are you still planning to make this change?

**Comment by wolfgangvonludwigsburg** [comment]
yes, I am on research, one more week, please ..

**Comment by DolphinIQ** [comment]
Hey @wolfgangvonludwigsburg Any progress with the docs? :innocent:

**Comment by wolfgangvonludwigsburg** [comment]
I'm sorry - due to Corona issues in my company I've had to shift acitivity priorities ..
- but I'll manage it 'til end of this week.

**Comment by DolphinIQ** [comment]
Thanks :) Would be awesome if this was included in r115

**Comment by mindinsomnia** [comment]
Could anyone give a, for example, 2 sentence explanation of what a LightProbe in Three.js is, and how Three.js uses them? I've found almost no information after going through the docs, the source code and the examples.

I mean I'm just guessing but would I be correct in saying you can create and place lightprobes throughout a scene and Three.js will somehow interpolate between them for indirect light? I'm guessing that's what they do but I can't find any information to confirm that or any information on how Three.js interpolates between them if that is indeed how they work.

Just a real quick summary from perhaps whoever wrote the code for LightProbes would be nice.

**Comment by Mugen87** [comment]
@wolfgangvonludwigsburg Any updates on this issue? If you have no time, I suggest someone else adds the documentation.

**Comment by mrdoob** [comment]
> I mean I'm just guessing based on experience from other engines, but would I be correct in saying you can create and place lightprobes throughout a scene and Three.js will somehow interpolate between them for indirect light?

Not yet. That's what #18371 is trying to implement.

Currently `LightProbe` and `PMREMGenerator` kind of serves the same purpose.

However, WebXR/AR provides the light estimation from the user's camera using Spherical Harmonics which is what `LightProbe` uses and that'll give it more use.

**Comment by mrdoob** [comment]
@mindinsomnia

> I mean I'm just guessing based on experience from other engines, but would I be correct in saying you can create and place lightprobes throughout a scene and Three.js will somehow interpolate between them for indirect light?

Not yet. That's what #18371 is trying to implement.

Currently `LightProbe` and `PMREMGenerator` kind of serves the same purpose.

However, WebXR/AR provides the light estimation from the user's camera using Spherical Harmonics which is what `LightProbe` uses and that'll give it more use.
