### ISSUE TITLE
Drawing lines documentation refers to Geometry instead of BufferGeometry

### ISSUE THREAD

**Issue by NicolasRannou** [mrdoob/three.js#18452]
##### Description of the problem

The ["Drawing lines"](https://threejs.org/docs/#manual/en/introduction/Drawing-lines) documentation uses **Geometries** in the code snippet. It should be updated to use **BufferGeometries**.

Using **BufferGeometry** is pretty much the same number of lines of code:
```
const geometry = new THREE.BufferGeometry();
  
const points = [];
points.push(new THREE.Vector3( -10, 0, 0) );
points.push(new THREE.Vector3( 0, 10, 0) );
points.push(new THREE.Vector3( 10, 0, 0) );

geometry.setAttribute( 'position', new THREE.Float32BufferAttribute( points, 3 ) );
```

##### Three.js version

- [ ] Dev
- [ ] r112
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I'm afraid this code snippet is correct. It should be:
```js
const geometry = new THREE.BufferGeometry();
  
const points = [];
points.push(new THREE.Vector3( -10, 0, 0) );
points.push(new THREE.Vector3( 0, 10, 0) );
points.push(new THREE.Vector3( 10, 0, 0) );

geometry.setFromPoints( points );
```
But yes, I does make sense to clean this up 👍 .

**Comment by Mugen87** [comment]
Thanks for reporting!

**Comment by NicolasRannou** [comment]
O, the text of the documentation should also be updated! (it was using regular Geometry because it was easier, which is not the case anymore)

**Comment by Mugen87** [comment]
Good catch!

**Comment by Mugen87** [comment]
54011b6c0fbd324d2dcff98d53485deb869be2d4
