### ISSUE TITLE
Feature Request: sRGBPass for EffectComposer

### ISSUE THREAD

**Issue by viperphase1** [mrdoob/three.js#18468]
I'm in need of a post process pass that does the same thing as renderer.outputEncoding = THREE.sRGBEncoding.

To be used like so:
```
composer.addPass(renderPass);
composer.addPass(outlinePass);
composer.addPass(new THREE.sRGBPass())
```

See https://discourse.threejs.org/t/srgb-encoding-as-a-postprocess-pass/12278/4

**Comment by WestLangley** [comment]
You can do that yourself right now.

Replace
```glsl
gl_FragColor = LinearToGamma( tex, float( GAMMA_FACTOR ) );
```
with
```glsl
gl_FragColor = LinearTosRGB( tex );
```

**Comment by WestLangley** [comment]
@donmccurdy What new API would you suggest for the Gamma pass? Keep the name but change to sRGB? Create a new pass with a new name?

**Comment by Mugen87** [comment]
Maybe something like `EncodingPass` or `ColorSpacePass` which can be configured similar to `WebGLRenderer.outputEncoding`. Default would be `sRGB`.

**Comment by gkjohnson** [comment]
Are there docs about how to properly manage and use color space now? I'd be happy to help write something up but I'm not sure I entirely understand how it works right now. I was also under the impression that gamma 2.2 was the same as sRGB but [apparently that's not exactly the case!](https://en.wikipedia.org/wiki/SRGB#The_sRGB_transfer_function_(%22gamma%22))

**Comment by donmccurdy** [comment]
Here's an attempt: https://gist.github.com/donmccurdy/fefb35c5ba033e7dcd641f9684e47a82. I've also written a bit about it in https://github.com/aframevr/aframe/issues/3509 and https://github.com/aframevr/aframe/pull/3757.

> Maybe something like EncodingPass or ColorSpacePass which can be configured ..

I like that suggestion. Although, I don't know if a gamma pass is really necessary... is it that much cheaper than sRGB?

**Comment by WestLangley** [comment]
@donmccurdy Thanks for your reply. Looks like we were working concurrently. I filed #18477, which I think is fine for now.

>Although, I don't know if a gamma pass is really necessary...

I think you mean gamma _transfer function_... No, it may not be. It just depends on whether we are going to deprecate support for the gamma-based form  in core, or continue to support it. 

I know some users _do_ use the gamma-based form for artistic control.

**Comment by donmccurdy** [comment]
Thanks, #18477 looks good for now I agree.
