### ISSUE TITLE
SpecularGlossiness materials no longer reflect the environment

### ISSUE THREAD

**Issue by elalish** [mrdoob/three.js#18463]
##### Description of the problem

Something happened between r110 and dev, where glTF with SpecularGlossiness aren't playing well with PMREM anymore (other lights work).

To repro, put [this model](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SpecGlossVsMetalRough) in Don's [viewer](https://gltf-viewer.donmccurdy.com/) and turn off the ambient and direct lights and you'll see this:
![image](https://user-images.githubusercontent.com/1649964/73026611-9af8f200-3de6-11ea-90bb-0c066489fa0e.png)

##### Three.js version

- [x] Dev
- [ ] r112
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by elalish** [comment]
Ping @donmccurdy @Mugen87

**Comment by WestLangley** [comment]
@elalish Does the [three.js example](https://threejs.org/examples/webgl_loader_gltf_extensions.html) work for you?

**Comment by donmccurdy** [comment]
Loading the model in my viewer...

https://gltf-viewer.donmccurdy.com/#model=https://rawcdn.githack.com/KhronosGroup/glTF-Sample-Models/130fe585dd2133fee6dc79d22ecddd3e73ea7af0/2.0/SpecGlossVsMetalRough/glTF-Binary/SpecGlossVsMetalRough.glb

... I've confirmed that copying `scene.environment` to `material.envMap` fixes the issue. Run this in the JS console to see the fix:

```js
var envMap = content.parent.environment;
content.traverse((o) => {
  if (o.isMesh) {
    o.material.envMap = envMap;
    o.material.needsUpdate = true;
  }
});
```

So https://github.com/mrdoob/three.js/pull/18465 really does look like the right solution, but I'm not sure why it doesn't seem to be working.

**Comment by mrdoob** [comment]
I'll take a look tomorrow.

**Comment by Mugen87** [comment]
The reason why `Scene.environment` does not work for the specular/glossiness material is explained here: https://github.com/mrdoob/three.js/issues/18265#issuecomment-570775147

**Comment by elalish** [comment]
@WestLangley indeed, that model works, since the problem is restricted to scene.environment. Thanks for bringing that test to my attention though!
