### ISSUE TITLE
Texture Loader always returned image: undefined property

### ISSUE THREAD

**Issue by lucidsleepy** [mrdoob/three.js#18462]
##### Description of the problem

Hello, I'm using the code example from the threejs docs to load a texture, and use it as alphaMap for my Material. However, I tried the process with several grayscale images and it just doesn't work. The Texture properties logged show me that "image: undefined".

##### Three.js version

- [ ] Dev
- [x ] r112
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests. If you do so, please share your code so it's easier to provide feedback.

**Comment by vucenovic** [comment]
Hello @Mugen87, coming back here as I'm sure its an issue: I can only load images from the web, local paths are still not working.

**Comment by Mugen87** [comment]
Please demonstrate a bug in the forum first before reporting an issue at github. In many cases, it's a problem on app level.

BTW: You can login to the forum with your existing github account.
