### ISSUE TITLE
Unexpected tilted ShapeGeometry

### ISSUE THREAD

**Issue by Peque** [mrdoob/three.js#18482]
### Description of the problem

I have a list of points in the X-Y (horizontal) plane:

```js
var points = [
    new THREE.Vector2(-20, 0),
    new THREE.Vector2(-20, -20),
    new THREE.Vector2(20, -20),
    new THREE.Vector2(20, 20),
    new THREE.Vector2(0, 20),
    new THREE.Vector2(0, 0),
    new THREE.Vector2(-20, 0),
];
```

I then project these points in the Z (up) direction until they intersect with a plane:

```js
var plane = new THREE.Plane().setFromNormalAndCoplanarPoint(
    new THREE.Vector3(0.7071067811865475, 0, 0.7071067811865475),
    new THREE.Vector3(20, 0, 0)
);
```

Then I create a mesh with these projected points:

```js
var shape = new THREE.Shape(projectedPoints);
var shapeGeom = new THREE.ShapeGeometry(shape);
var mesh = new THREE.Mesh(
    shapeGeom,
    new THREE.MeshBasicMaterial({
        color: 0x0000ff,
        side: THREE.DoubleSide,
        wireframe: false,
        transparent: true,
        opacity: 0.3,
    })
);
```

I would expect the mesh to look like the unprojected points when looked from above, like so:

![Screenshot from 2020-01-25 19-32-49](https://user-images.githubusercontent.com/526577/73125652-8a44a980-3fa9-11ea-9435-e66f7780ef83.png)

But instead it looks like this:

![Screenshot from 2020-01-25 19-33-07](https://user-images.githubusercontent.com/526577/73125656-903a8a80-3fa9-11ea-8859-6c4a8d55532c.png)

### Life example

https://jsfiddle.net/Peque/Lcn7g2ah/

### "Raw" source code

<details>

```js
var renderer, controls, scene, camera;

init();

function init() {

    // Scene
    scene = new THREE.Scene();
    scene.background = new THREE.Color(0xb0b0b0);

    // Camera
    camera = new THREE.PerspectiveCamera(30, window.innerWidth / window.innerHeight, 1, 1000);
    camera.position.set(0, 0, 400);
    camera.up.set(0, 0, 1);

    // Light
    var ambientLight = new THREE.AmbientLight(0xcccccc, 0.2);
    scene.add(ambientLight);

    // Helpers
    var helpers = new THREE.Group();
    var grid = new THREE.GridHelper(200, 10);
    grid.rotation.x = Math.PI / 2;
    var axis = THREE.AxisHelper(100);
    helpers.add(grid);
    helpers.add(axis);
    scene.add(helpers);

    // Renderer
    renderer = new THREE.WebGLRenderer({ antialias: true });
    renderer.setPixelRatio(window.devicePixelRatio);
    renderer.setSize(window.innerWidth, window.innerHeight);
    document.body.appendChild(renderer.domElement);

    // Controls
    controls = new THREE.OrbitControls(camera, renderer.domElement);

    // Event listeners
    controls.addEventListener("change", render, false);

    // Draw projected mesh
    var points = [
        new THREE.Vector2(-20, 0),
        new THREE.Vector2(-20, -20),
        new THREE.Vector2(20, -20),
        new THREE.Vector2(20, 20),
        new THREE.Vector2(0, 20),
        new THREE.Vector2(0, 0),
        new THREE.Vector2(-20, 0),
    ];
    var plane = new THREE.Plane().setFromNormalAndCoplanarPoint(
        new THREE.Vector3(0.7071067811865475, 0, 0.7071067811865475),
        new THREE.Vector3(20, 0, 0)
    );
    var mesh = projectPoints(points, plane);
    scene.add(mesh);

    // Render
    render();
}

function projectPoints( points, plane ) {
    var projectedPoints = [];
    const upDirection = new THREE.Vector3(0, 0, 1);
    points.forEach(p => {
        const r = new THREE.Ray(new THREE.Vector3(p.x, p.y, 0.0), upDirection);
        let intersection = new THREE.Vector3();
        r.intersectPlane(plane, intersection);
        projectedPoints.push(new THREE.Vector3(p.x, p.y, intersection.z));
    });
 
	var shape = new THREE.Shape(projectedPoints );
    var shapeGeom = new THREE.ShapeGeometry(shape);
    var mesh = new THREE.Mesh(
        shapeGeom,
        new THREE.MeshBasicMaterial({
            color: 0x0000ff,
            side: THREE.DoubleSide,
            wireframe: false,
            transparent: true,
            opacity: 0.3,
        })
    );
    console.log(projectedPoints);
    mesh.geometry.vertices = projectedPoints;
    return mesh;
	
}

function render() {
    renderer.render(scene, camera);
}
```
</details>

##### Three.js version

- [ ] Dev
- [x] r112
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

None.

**Comment by Peque** [comment]
Interestingly, this does not happen with any list of points.

This, for example, works fine:

```js
var points = [
    new THREE.Vector2(-20, 0),
    new THREE.Vector2(-20, -20),
    new THREE.Vector2(20, -20),
    new THREE.Vector2(20, 40),
    new THREE.Vector2(-10, 40),
    new THREE.Vector2(-10.0, 0.0),
    new THREE.Vector2(-20, 0),
];
```

But this does not (notice the change in points 2 and 3, where I only change their x attribute from 20 to 10):

```js
var points = [
    new THREE.Vector2(-20, 0),
    new THREE.Vector2(-20, -20),
    new THREE.Vector2(10, -20),
    new THREE.Vector2(10, 40),
    new THREE.Vector2(-10, 40),
    new THREE.Vector2(-10.0, 0.0),
    new THREE.Vector2(-20, 0),
];
```

Also, replacing the `(0, 0)` point in the first example provided in the issue to `(-0.00001, 0.00001)`, does not reproduce the error:

```js
var points = [
    new THREE.Vector2(-20, 0),
    new THREE.Vector2(-20, -20),
    new THREE.Vector2(20, -20),
    new THREE.Vector2(20, 20),
    new THREE.Vector2(0, 20),
    new THREE.Vector2(-0.00001, 0.00001),
    new THREE.Vector2(-20, 0),
];
```

But if we replace the `(0, 0)` with `(0.00001, -0.00001)` instead, it does. :confused:

**Comment by Mugen87** [comment]
Why are you overwriting `mesh.geometry.vertices` with `projectedPoints`? That does not seem to make sense to me since you want to use the projected points to generate a shape geometry. If you don't overwrite the resulting vertices, the result looks okay: https://jsfiddle.net/g0ajckve/

**Comment by Peque** [comment]
@Mugen87 I want the shape to be in the projected plane.

It seems your fiddle looks like the original (not-projected) shape:

![Screenshot from 2020-01-25 21-22-23](https://user-images.githubusercontent.com/526577/73126913-df3bec00-3fb8-11ea-9920-fe445c3376b9.png)

The expected result is an inclined shape:

![Screenshot from 2020-01-25 21-22-31](https://user-images.githubusercontent.com/526577/73126919-eb27ae00-3fb8-11ea-85b0-22dd4d1b3316.png)

**Comment by Peque** [comment]
Basically, I want to create coplanar shapes in the 3D space out of a list of 3D points.

**Comment by WestLangley** [comment]
@Peque `THREE.Shape` takes an array of 2D points, not 3D points.

I expect you will have to rotate your points into the XY plane after projecting, create your `Shape`, then create your `ShapeBufferGeometry`,  and then rotate the geometry vertices back into the projection plane.

**Comment by Peque** [comment]
@WestLangley Why should that make any difference? I mean, that is another way to do it but, what is wrong with my approach? If nothing, then this is a bug, right? :blush:

**Comment by WestLangley** [comment]
@Peque Perhaps you can create your `Shape` with 2D points as designed, and then project the resulting `Mesh` onto the plane.

https://jsfiddle.net/4m0gfhck/

If you need more help with implementation details, please use the [forum](https://discourse.threejs.org).

**Comment by Mugen87** [comment]
> If nothing, then this is a bug, right?

I'm afraid no. `Shape` and `ShapeGeometry` work as expected.

The forum is actually an ideal place to discuss such implementation specific help requests.

**Comment by Peque** [comment]
@WestLangley @Mugen87 Thanks for your feedback. I already asked in the forum before opening this issue. After some feedback I got there, I thought this could be really considered an issue.

It would be great if you could share your thoughts on:

https://discourse.threejs.org/t/2d-object-in-3d-space-by-vertices/2795/18

Specifically:

- Why, using the method above, some points work just fine but others do not?
- Is there a recommended/canonical way to do that?

Would it make sense to transform this issue into a feature request? In example: an easier way (API) to create flat shapes in the 3D space.

**Comment by Mugen87** [comment]
TBH, I think the API is fine as it is. But let's discuss the other points in the forum.
