### ISSUE TITLE
Custom FileLoader

### ISSUE THREAD

**Issue by Paril** [mrdoob/three.js#18486]
FileLoader is extremely limited with it being hardcoded and stuck to using XHR. I want to load from other sources that aren't URLs on the visible web, and having data that I already have in memory moved/copied to an Object URL seems like a hack rather than a solution to this issue (not to mention that a urlHandler is too limited for this task if the request to load a file requires asynchronous behavior) - JSZip's latest versions, for instance, are async-only, meaning previous LoadingManager-based solutions can't work.

**Comment by makc** [comment]
```javascript
THREE.FileLoader.prototype = <your implementation here>
```

you are welcome :)

**Comment by donmccurdy** [comment]
Would [LoadingManager.addHandler](https://threejs.org/docs/#api/en/loaders/managers/LoadingManager.addHandler) work for you?

**Comment by Paril** [comment]
Good point about just replacing the prototype, I hadn't considered that one! I was trying to think of a way to do that with modules but forgot about my ol' ES5 roots.

@donmccurdy: addHandler is higher level. The issue is FileLoader, which happens way before LoadingManager is even used, but @makc's solution would indeed work for my purposes. The only issue left is that a lot of loaders "abuse" the file system by prepending the current URL to the file so that it resolves to a proper URL, but I guess I can figure out a hack to undo that.

**Comment by Mugen87** [comment]
Um, it's not clear from your posts how your intended implementation would look like. Things might get more clear if you could share some code.

**Comment by Paril** [comment]
@Mugen87 I don't have any code because I ended up going for a self-rolled solution as this was a bit of a deal-breaker for getting something up and running in time.

Basically, imagine that your only method of handling files through JS is through blobs and/or ArrayBuffers, and you are attempting to use a loader that requires subsequent file loads (ObjLoader2 is an immediate example because it requires loading .mtl as a dependency, which then loads textures as dependencies). There's no mechanism for supporting these sorts of file systems at all. The only workaround I could think of is to push all of the blobs out as Object URLs and use a urlHandler to re-write the URLs to point to the proper Object URLs, which is a bit problematic too because a lot of the Loader subclasses change the format of the paths by, say, prefixing the current address bar URL, since it is basically running on the assumption that every file being loaded through it is a loose file in a folder somewhere.

It's just fighting against the system to try to load something from anything that isn't loose files in a directory on a folder on the server, that's the main issue here. I think the FileLoader should be designed in such a way that, on a base level, all it expects is to input path -> output string/arraybuffer (depending on whether the requested file needs to be loaded as text or binary), and to build XHR on top of that in such a way that it is an optional subsystem. Consider an ecosystem that isn't necessarily running on a website and doesn't have URL (as a hypothetical; obviously this isn't the case here but it points out the reliance on FileLoader).

JSZip's most recent implementation is entirely asynchronous, which means that a urlHandler can't be used for on-demand decompression because urlHandlers must be synchronous. Replacing FileLoader's prototype as described above would probably work but since I went in a different direction I can't test this right away. I hope the concept ends up helping somebody down the road that needs to load models/textures from an abstract filesystem though!

**Comment by Mugen87** [comment]
> Basically, imagine that your only method of handling files through JS is through blobs and/or ArrayBuffers, and you are attempting to use a loader that requires subsequent file loads (ObjLoader2 is an immediate example because it requires loading .mtl as a dependency, which then loads textures as dependencies). There's no mechanism for supporting these sorts of file systems at all. 

`GLTFLoader` already resolves such dependencies with a Promise-based solution. AFAICS, this works quite well. TBH, I don't understand why you want to shift this logic into a much more low level `FileLoader` class which should be only responsible for loading single files. 

I have to apologize, but I'm still not sure I completely understand your issue. If you have some time in the future, it would be interesting to see an alternative `FileLoader` class that implements your presented approach. I'm sure things will become more obvious then.

**Comment by Paril** [comment]
GLTFLoader does have logic to handle this, but you can see with usage of createObjectURL that it still requires that it pass through as a URL and through XHR even though the data may already be a blob in memory. It's an unnecessary round trip.

The best I can suggest for showing you the issue is to attempt to implement an efficient, zero-copy (as in, no usage of createObjectURL to make a dummy to re-download ArrayBuffer/string data through XHR to a Loader) model loader that loads models contained inside of a zip using the latest version of JSZip. That was the main problem I was presented with attempting to solve. Any solution I could think of was essentially a hack which required butchering URLs or decompressing every file in the zip and storing them as object URLs *before* attempting to actually load a model (since the dependencies of an obj file for instance need to be at the ready and can't be handled asynchronously without modification of FileLoader).

**Comment by makc** [comment]
@Paril another option would be to enable THREE.Cache or what was its name, and put all your ArrayBuffer-s there under proper URLs before you start to actually loading anything.

**Comment by Paril** [comment]
@makc That's actually clever too, but that requires copies - again I feel like this is a hack to work around something that shouldn't be an issue to begin with. I already *have* the data ready for JS to work with, I shouldn't need to expose it externally via an Object URL for THREE to then re-download and store as a second ArrayBuffer/string.

**Comment by Mugen87** [comment]
Closing since it was never clarified how the API should look like to handle the OP's use case. Like mentioned before, a concrete API suggestion or even an initial implementation would make this whole more clear.

BTW: If asset data are already in memory in form of a string or `ArrayBuffer`, it's possible to directly call the `parse()` methods of loaders. The [editor](https://github.com/mrdoob/three.js/blob/14612de944fce98d721e392aabf2ee4f87aafdaf/editor/js/Loader.js#L113-L114) already follow this approach.

**Comment by alexpineda** [comment]
I have this same issue because I'm loading assets in electron (node) and need to use the "fs" package (or if I were to be doing it the safe way, an  ArrayBuffer object transferred from the main process). I'm not sure why but sometimes a module will load from build/three.js and other times from build/three.module.js. In the case of three.js I'm able to override the load function of the FileLoader prototype, but when it loads from three.module it seems to be the case that it's immutable? I'm not certain. Either way an approach to use a different FileLoader would be useful to me.

**Comment by tr3ysmith** [comment]
I'm in the exact same boat as @alexpineda except I'm using [Tauri](https://tauri.app) which is like Electron but for Rust. It too requires me to use their API to fetch local resources. I really which that there was an easier way to specify your own custom file loader without all these hacks. I have a separate project that will be running into this in the future where the URL's are protected and required Authentication. This would also be helpful in that scenario as well.

**Comment by mrdoob** [comment]
@tr3ysmith I'm sure someone has made some sort of polyfill to emulate the browser `fetch`.

Found this: https://github.com/tauri-apps/tauri/issues/4490
