### ISSUE TITLE
Quaternion: Minor code comment alteration suggestion.

### ISSUE THREAD

**Issue by minviable** [mrdoob/three.js#18489]
https://github.com/mrdoob/three.js/blob/95fb8e348948679014f4c6afe2aefc4043b16703/src/math/Quaternion.d.ts#L20

This currently says:
`* @param w w coordinate`

I believe it should be more like:
`* The multiplier of the real quaternion basis vector.`
See here: https://github.com/schteppe/cannon.js/blob/master/src/math/Quaternion.js#L32

I could be completely incorrect, i tried to check wikipedia on Qauternion's but got lost if i'm honest.

**Comment by makc** [comment]
@minviable it says on line 6
> The Quaternion is mathematically defined as Q = x\*i + y\*j + z\*k + w

or, if you want, x\*i + y\*j + z\*k + w\*1 - here i, j, and k are not real, and 1 is - hence w is real vector (0,0,0,1) multiplier, and x is (i,0,0,0) vector multiplier, for example. this is probably the only time you will think about these vectors, so I`d say they should do the opposite and remove any mentions of basis vectors.

**Comment by Mugen87** [comment]
I think both approaches (the one of `three.js` and the one of `cannon.js`) are fine. So I don't see a need for action.

**Comment by minviable** [comment]
Sure, i said it was minor - just that it's not technically a coordinate 

https://docs.unity3d.com/ScriptReference/Quaternion-w.html
```
w is a scalar that stores the rotation around the vector. More details about quaternions can be located at https://scriptinghelpers.org/blog/how-to-think-about-quaternions.
```

**Comment by Mugen87** [comment]
If you feel more comfortable with the term `component`, feel free to make a PR 👍
