### ISSUE TITLE
Feature: Unique colors for InstancedMesh

### ISSUE THREAD

**Issue by telematrix** [mrdoob/three.js#18500]
Curious if unique colors for InstancedMesh is on the three.js team's radar? I've looked through the source and it's not a quick patch. I believe shaders amongst other parts would have to be updated. I'd be more than happy to take on the work. Any tips would be appreciated.

**Comment by telematrix** [comment]
Closing the issue because it's possible to render what I need using InstancedBufferGeometry with custom shaders. My main concern was using the DOF post processing shader which I believe would also have to be updated to work with unique colors. So I think it would be faster to use RawShaderMaterial and then write a custom DOF post processing shader as well (plenty of examples out on the interwebz). Sorry to bother you guys.

**Comment by WestLangley** [comment]
On the r.113dev branch:
https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_instancing_modified.html

**Comment by donmccurdy** [comment]
Alternatively, without a custom shader:

https://github.com/mrdoob/three.js/blob/45418089bd5633e856384a8c0beefced87143334/examples/webgl_instancing_scatter.html#L82-L98

**Comment by WestLangley** [comment]
@donmccurdy You can change the example if you want. I thought it would be nice to show how to hack the shader, though. Adding instanced color seemed to be a good option at the time. :-)

**Comment by donmccurdy** [comment]
Definitely agreed it's helpful to show how to hack the shader cleanly! At some point I think it might be nice to hack the UVs instead of the color (or both?) to use different textures from an atlas texture to each instance. Since that can't be done otherwise. But I don't have a good example yet, and I don't think it's urgent.

**Comment by telematrix** [comment]
@WestLangley @donmccurdy thank you so much for the examples!! I had tried InstancedBufferAttribute with InstancedMesh and had some issues but definitely it was on my end. It seems I did not have this this line: ` blossomMaterial.vertexColors = THREE.VertexColors; ` but will need to implement it first.
Thank you again, you have saved me so much time and trouble. Not sure where I can help three.js development, but if there are issues that you'd like to see worked on please let me know.

**Comment by telematrix** [comment]
@donmccurdy I realize now that I overlooked that section of the webgl_instancing_scatter example. Thank you thank you

**Comment by telematrix** [comment]
@WestLangley @donmccurdy sorry to bother you guys again but this is what you helped me out with [Matrix Body Simulation](https://tellerm.com/demo/m-body/). Again, thank you so much. 🙏
