### ISSUE TITLE
Feature Request: Add source uri to texture properties

### ISSUE THREAD

**Issue by viperphase1** [mrdoob/three.js#18509]
I have a web app where users can load models and edit them in the browser. If a texture is missing I would like to be able to tell the user the name of the missing texture file.

**Comment by Mugen87** [comment]
Can you solve this issue on application level? Why do you need an extra property for this?

**Comment by viperphase1** [comment]
I suppose when the user is done selecting files I could try and load an image from each image file uri to make sure it works before attempting to put the files through the model loader. But that would mean loading images twice. Once as a pre check and again when the loader creates the texture objects.

**Comment by viperphase1** [comment]
Basically when texture.image is undefined it would be nice to know what would have been the src of the image element.

**Comment by viperphase1** [comment]
Is there a way of quickly checking what additional files a model needs? If I can accrue a list of required files I could check to make sure they all exist/work before attempting to load the model.

**Comment by viperphase1** [comment]
Now that I've thought about it, what I really need is a validation step in all the model loaders that checks for missing texture files. What I'm having to do right now is wait until the loader is finished and then check each texture to see if it has an image element.

**Comment by Mugen87** [comment]
Have you considered to use [LoadingManager](https://threejs.org/docs/index.html#api/en/loaders/managers/LoadingManager) for this? If you create a manager and pass it to the loader, you can use the respective `onLoad()` callback to wait until all resources are loaded. In this way, your textures will automatically have valid image elements.

**Comment by viperphase1** [comment]
Yes we are using LoadingManager. It's the case when the user selects a model file (say a .obj for example) but omitted a texture file referenced in the .obj file. The files that the user selected will load fine but the model won't look correct because a file wasn't included. Does that make sense?

**Comment by viperphase1** [comment]
When that happens I want to be able to tell the user the name of the file that the .obj needs. As far as I know that information is not stored anywhere in the OBJLoader.

**Comment by Mugen87** [comment]
> I want to be able to tell the user the name of the file that the .obj needs.

I think you can use the `onError()` callback of `LoadingManager` for this. As you see at the following fiddle, the callback reports the URL which produces a 404 error. It should be no problem to derive the file name from it.

https://jsfiddle.net/48my2aes/

**Comment by viperphase1** [comment]
Perfect, just what I needed. Thanks so much for your help! @Mugen87
