### ISSUE TITLE
What is `setUsage` and how to i replace the deprecated `setDynamic`?

### ISSUE THREAD

**Issue by DusanBosnjakKodiak** [mrdoob/three.js#18517]
The console in my project is complaining that `BufferAtttribute.setDynamic( boolean )` is deprecated. It says to use `setUsage( value )` instead. 

My problem is that i don't know what usage is and how to use the usage. The description is not helpful to me, because i can sort of tell from the name of the method and the argument that it sets, usage to some value, but i'm unable to find out what the value type should be. With dynamic it seemed straightforward, it's on or off. 

> .setUsage ( value : Usage ) : BufferAttribute
> Set usage to value.

**Comment by Mugen87** [comment]
The documentation for `usage` says:

< Defines the intended usage pattern of the data store for optimization purposes. Corresponds to the usage parameter of [WebGLRenderingContext.bufferData()](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bufferData). Default is THREE.StaticDrawUsage.

**Comment by Mugen87** [comment]
https://discourse.threejs.org/t/what-is-setusage-on-bufferattribute/12441

It seem @DusanBosnjakKodiak is @pailhead's new github account^^.

**Comment by DusanBosnjakKodiak** [comment]
Yes, is this a problem? I don't want to log in and out to ask questions when im at work.

**Comment by mrdoob** [comment]
Please, use the [forum](https://discourse.threejs.org/) for help.

**Comment by pailhead** [comment]
I think i was confused by looking for the method first. The argument is clickable, but it doesn't take you anywhere. On closer inspection, neither does the property.
Here for example, with `.copy()` you can click both on the argument and the return type. 
https://threejs.org/docs/#api/en/core/Face3

The link under property refers to webgl, but there it's all upper and snake case, three's are pascal. Maybe this could be addressed by either having the method link to the property, or both link to the consts?

Sorry bout posting with two accounts, i find it really tedious to log in and out when my phone is always dead.
