### ISSUE TITLE
GLTFLoader/SkinnedMesh: Mesh rotated by +/- 90º

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#18526]
##### Description of the problem

As reported in https://github.com/KhronosGroup/glTF-Blender-IO/issues/856, the model below appears rotated by 90º around the X axis in three.js, when any of the included animations are played. In several other viewers (BabylonJS, glTF-Sample-Viewer, Blender), the model appears upright.

- .blend: https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2545811/game_man_sketchbookb1.zip
- .glb: https://github.com/KhronosGroup/glTF-Blender-IO/files/4141446/Archive.zip

^The second link also contains a second version of the model, `game_man_packed.glb`. The only difference is that the second has been optimized by gltfpack — and for some reason it then renders correctly. 🤔

| expected | three.js |
|----|---|
| ![babylon](https://user-images.githubusercontent.com/1848368/73585284-940c5800-4454-11ea-806f-c9d8000fc046.png) | ![three](https://user-images.githubusercontent.com/1848368/73585285-95d61b80-4454-11ea-8b65-9aa2e50b0199.png) |

The [glTF validator](https://github.khronos.org/glTF-Validator/) reports several possible issues with this model (joint weights should be normalized, and so on) but nothing that looked like an obvious cause to me.

For a quick way to preview the problem, drag the model into https://threejs.org/editor/ or https://gltf-viewer.donmccurdy.com/, then play the *Idle* animation (or any animation with an obvious upright pose). In my viewer, the model itself is accessible as `content` from the JS console.

##### Three.js version

- [ ] Dev
- [x] r113
- [ ] ...

**Comment by mrdoob** [comment]
It's resting... 🤡

**Comment by Mugen87** [comment]
> The only difference is that the second has been optimized by gltfpack — and for some reason it then renders correctly. 🤔

I've tried to compare both `glb` today but noticed that the asset data are extensively change by `gltfpack`. Meaning geometry, transformation and even the animation data are different. That makes it really hard to compare both assets. Although they represent the same character, they are totally different from a technical point of view.

The other github issue in context of `glTF-Blender-IO` mentions a rotation of the root bone by 90° around the x axis. Indeed, removing this transformation makes the animation look correct. The must be a place in the `three.js` code base where this transformation is not honored correctly.

**Comment by donmccurdy** [comment]
^That 90º rotation sounds like the right place to look, yes. The [glTF skinning spec](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#skins) mentions that:

> Client implementations should apply only the transform of the skeleton root [joint] node to the skinned mesh while ignoring the transform of the skinned mesh node.

As far as I can tell we're doing that – moving the SkinnedMesh has no effect (except to trigger frustum culling at some point) and moving the root bone does. Why it's 90º off, I'm still not sure.

**Comment by Mugen87** [comment]
It seems it works if the bone `root` is renamed to something different. Can someone please verify^^? This is my updated `glb` exported from Blender 2.81a: [game_man_sketchbookb1.glb.zip](https://github.com/mrdoob/three.js/files/4154967/game_man_sketchbookb1.glb.zip)

**Comment by donmccurdy** [comment]
Wow... that's... yeah. Confirmed, renaming the node (I edited the original `.glb` by hand) fixes the issue. 

(╯°□°)╯︵ ┻━┻

Either we need to escape this name in [PropertyBinding.sanitizeNodeName](https://github.com/mrdoob/three.js/blob/c23b245814ac71999d8303c07434fcfd244288dd/src/animation/PropertyBinding.js#L145), or remove the [special case](https://github.com/mrdoob/three.js/blob/master/src/animation/PropertyBinding.js#L201) entirely. I think I'd vote for the latter.

Thanks for finding that! Had not occurred to me at all.

**Comment by takahirox** [comment]
"root" name issue has been discussed here, too https://github.com/mrdoob/three.js/issues/16693

**Comment by Mugen87** [comment]
I think we should finally fix this issue for the next release. I think I still favor enhancing `PropertyBinding.sanitizeNodeName()`.
