### ISSUE TITLE
texSubImage2D: ArrayBufferView not big enough for request

### ISSUE THREAD

**Issue by dslming** [mrdoob/three.js#18534]
##### Description of the problem
in [demo](https://threejs.org/examples/?q=texture#webgl_materials_texture_partialupdatel), when use .png format image, don't work.

warning info: texSubImage2D: ArrayBufferView not big enough for request

##### Three.js version

- [ ] Dev
- [x ] r113
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
When using a PNG texture, `Texture.format` is `RGBA`. That means you have to setup the data textures as `RGBA`, too. That would look like so:

```js
var data = new Uint8Array( width * height * 4 );
dataTexture = new THREE.DataTexture( data, width, height, THREE.RGBAFormat );
```
When updating the data texture with new color values, you now have to set the alpha channel e.g. with a fix value:
```Js
var stride = i * 4;

data[ stride ] = r;
data[ stride + 1 ] = g;
data[ stride + 2 ] = b;
data[ stride + 3 ] = 1;
```
Please use the [forum](https://discourse.threejs.org/) if you need more help.
