### ISSUE TITLE
GLTFLoader with an object

### ISSUE THREAD

**Issue by PaoloCisly** [mrdoob/three.js#18532]
##### Description of the problem

Currently, when we want to load an object with GLTFLoader, we have to enter the URL of the directory path.
I would like to know if there is a way to input the object instead of the path.

Example:

HTML:
```html
<input id="object" type="file" />
```

Javascript:
```javascript
var obj = document.getElementById('object');

var loader = new THREE.GLTFLoader();

loader.load(
	// insert the object here instead of the url
	obj,

	function ( gltf ) {

		scene.add( gltf.scene );
		gltf.animations;
		gltf.scene;
		gltf.scenes;
		gltf.cameras;
		gltf.asset;

	},
	function ( xhr ) {

		console.log( ( xhr.loaded / xhr.total * 100 ) + '% loaded' );

	},
	function ( error ) {

		console.log( 'An error happened' );

	}
);
```

I am aware that it gives error.
I ask this question to find out if anyone can advise me on how to get around this problem, if it can be done.
Thanks in advance.

**Comment by Mugen87** [comment]
I suggest you study how the [editor](https://threejs.org/editor/) handles this use case. The idea is to directly call `GLTFLoader.parse()` with the respective asset data.

https://github.com/mrdoob/three.js/blob/ce686fd491a989c00809fe84e0a60ea4d5a5d082/editor/js/Loader.js#L174-L192

Please use the [forum](https://discourse.threejs.org/) if you need more help/guidance for this use case.
