### ISSUE TITLE
DRACOLoader fails only on iOS Safari, only in production build

### ISSUE THREAD

**Issue by SBRK** [mrdoob/three.js#18540]
When loading a draco gltf model on a development build, I have no issue anywhere. When loading a draco gltf model on Safari iOS in production, I have a load of errors (`THREE.DracoLoader: Unexpected attribute type`). It works on any other device/browser, and fails only on my production build. 

In my experience, minification and optimization of code for production sometimes produces code that will fail on specific browsers, but I'm a bit clueless for this one. Did anyone ever experience that, and what would be a fix? 
The build is made with webpack 4.41.2, and it fails with both wasm and js draco decoders.

**Comment by donmccurdy** [comment]
Would you be able to share a demo of the broken production build? Or, if not, the webpack configuration you're using? I haven't heard of this issue before, but DRACOLoader uses Web Workers, and the error is coming from inside a Worker, so perhaps minification is interfering with that somehow.

If you'd be able to modify DRACOLoader locally, changing this line:

https://github.com/mrdoob/three.js/blob/daedcccfa3d9e50f49a949abf9dc6e3124518857/examples/js/loaders/DRACOLoader.js#L511

... to ...

```js
var attributeType = attributeTypes[ attributeName ];
```

... might be worth a try. That `self[ ... ]` reference looks like it may be incorrect.

**Comment by SBRK** [comment]
It took me almost all my day of work, but I got it. Here's the Webpack config I used to fix the issue: 
```
{
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          keep_fnames: /Float32Array/,
        },
      }),
    ],
  }
}
```
I'm still not completely sure what happened. I think on iOS Safari (at least older versions, up to 11.2 according to caniuse.com), Float32Array is polyfilled, and when the code is minified, Float32Array's name gets lost somehow. The problem itself was not in DRACOLoader but in GLTFLoader, in the part of `decodePrimitive` that fills `attributeTypeMap`.
I don't know if this could be mitigated in three.js directly.

**Comment by donmccurdy** [comment]
In any case, glad you got this working!

Maybe Float32Array did get polyfilled, just to patch some missing behavior, like `.fill`? Safari [still doesn't have that](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/fill). I don't think we use that method, but webpack wouldn't know. 

Hard to guess exactly what's happening but if this comes up again, maybe we could try replacing the constants here...

https://github.com/mrdoob/three.js/blob/daedcccfa3d9e50f49a949abf9dc6e3124518857/examples/js/loaders/GLTFLoader.js#L1013-L1020

... with strings, and using a switch block to choose a constructor.

**Comment by SBRK** [comment]
Yes that would be better. I'm guessing something similar could come up with other typed arrays, but since DRACO only uses Float32Array, I didn't have to put the rest of them in the webpack configuration

**Comment by PaulBouisset** [comment]
Hello, I run into the same issue in production, my project works great on Chrome but on Safari and Safari IOS the DRACO loader return the same error message `THREE.DracoLoader: Unexpected attribute type`. I tried @SBRK solution with the TerserPlugin but with no luck. 

What would you recommend to solve this issue ?

**Comment by Nickman87** [comment]
@SBRK Had the same issue and your fix solved it for us! Thank you so much for the search 👍

**Comment by silvainSayduck** [comment]
> In any case, glad you got this working!
> 
> Maybe Float32Array did get polyfilled, just to patch some missing behavior, like `.fill`? Safari [still doesn't have that](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/fill). I don't think we use that method, but webpack wouldn't know.
> 
> Hard to guess exactly what's happening but if this comes up again, maybe we could try replacing the constants here...
> 
> https://github.com/mrdoob/three.js/blob/daedcccfa3d9e50f49a949abf9dc6e3124518857/examples/js/loaders/GLTFLoader.js#L1013-L1020
> 
> ... with strings, and using a switch block to choose a constructor.

Actually, doing that an only that (ie. replacing the Constructors with their names as Strings)
```js
var WEBGL_COMPONENT_TYPES = {
  5120: "Int8Array",
  5121: "Uint8Array",
  5122: "Int16Array",
  5123: "Uint16Array",
  5125: "Uint32Array",
  5126: "Float32Array"
};
```

was enough for me to get the DRACOLoader worker to work on Safari (iOS and desktop).
In fact, in https://github.com/mrdoob/three.js/blob/c5560e5f94a9c40cba74fdb5f64b3794fecf0a4b/examples/jsm/loaders/DRACOLoader.js#L520

this will be evaluated to the Constructor, even if the passed in value is a String.

**Comment by makc** [comment]
@silvainSayduck @donmccurdy did any of this make its way intto 3js

**Comment by donmccurdy** [comment]
I'm not sure what there is to fix here, it seems more like a bug in Webpack. If you understand what is wrong and want to open a PR that's okay with me.

**Comment by makc** [comment]
> If you understand what is wrong and want to open a PR that's okay with me.

indeed I dont; doing what is described in https://github.com/mrdoob/three.js/issues/18540#issuecomment-661831346 gives me
> Error: THREE.DRACOLoader: Unexpected attribute type.

and, even if it did not, why would webpack minify F32A in `5126: Float32Array` but not in `return Float32Array` ?

I am going to try different workaround, namely `5126: window["Float32Array"]`

**Comment by makc** [comment]
...so this gets minified to window.Float32Array and does not fix ios issue at all, according to the client. maybe it is not in GLTFLoader, after all?

**Comment by makc** [comment]
Aaaand the mobile issue reported by the client was not related to draco at all.
