### ISSUE TITLE
Errors in the threejs.org editor

### ISSUE THREAD

**Issue by Tazshelby2016** [mrdoob/three.js#18553]
##### Description of the problem
In the r113 editor (https://threejs.org/editor/), the following issues occured:
```
Menubar.Edit.js:161 Uncaught TypeError: Cannot read property 'isShaderMaterial' of undefined
    at Menubar.Edit.js:161
    at Scene.traverse (three.module.js:5707)
    at UIRow.<anonymous> (Menubar.Edit.js:157)
```
```
Sidebar.Object.js:571 Uncaught TypeError: Cannot set property 'needsUpdate' of undefined
    at UIBoolean.update (Sidebar.Object.js:571)
```
```
Sidebar.Object.js:571 Uncaught TypeError: Cannot set property 'needsUpdate' of undefined
    at UIBoolean.update (Sidebar.Object.js:571)
```
This was from attempting to click objects and set the shadows flags to true in the 'Camera' example scene.
A log warning found 15 times when looking in the log:
```
three.module.js:18347 THREE.WebGLProgram: gl.getProgramInfoLog() C:\fakepath(231,25-83): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
```
Two 'not cached' errors from google analytics showed up at the top of the log:
```
[SW] Not cached: https://ssl.google-analytics.com/ga.js
[SW] Not cached: https://ssl.google-analytics.com/__utm.gif?utmwv=5.7.2&utms=14&utmn=1003831722&utmhn=threejs.org&utmcs=UTF-8&utmsr=1536x864&utmvp=1211x700&utmsc=24-bit&utmul=en-us&utmje=0&utmfl=-&utmdt=three.js%20%2F%20editor&utmhid=1226119357&utmr=0&utmp=%2Feditor%2F&utmht=1580941272269&utmac=UA-86951-15&utmcc=__utma%3D88431582.1846809080.1557700072.1580870481.1580938466.12%3B%2B__utmz%3D88431582.1580938466.12.8.utmcsr%3Dgithub.com%7Cutmccn%3D(referral)%7Cutmcmd%3Dreferral%7Cutmcct%3D%2Fmrdoob%2Fthree.js%3B&utmjid=&utmu=qAAAAAAAAAAAAAAAAAAAAAAE~
```

##### Three.js version
- [ ] Dev
- [ ] r113
- [x] https://threejs.org/editor/

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Unknown

**Comment by mrdoob** [comment]
Thanks for sending these!

However, unless we know what action you did that caused these errors is hard for us to fix them.

**Comment by Tazshelby2016** [comment]
A mix between accidentally enabling the shadow tags on the scene and
camera. The analytics issue was there from the start if I understood that
log correctly... As for the warnings, I don't know. I do know, however,
that it is stating that certain mathematical operators which require
positive/negative only are allowing both.

**Comment by Mugen87** [comment]
> The analytics issue was there from the start if I understood that log correctly.

Yes. However, this only occurs on the hosted editor and not when using the code from the `master` or `dev` branch. I'm not sure it worth to author a different `sw.js` file in the `github-pages` branch to avoid at least the first warning about `ga.js`. AFAIK, the second auto-generated URL can't be cached anyway.

I've played around with the camera example by enabled/disabled various shadow related flags but I was unable to reproduce the issue:

![image](https://user-images.githubusercontent.com/12612165/73926790-79146a80-48d0-11ea-91e1-0577dc51b70f.png)

It would be great if you can list the exact steps that are necessary to reproduce the issue.

**Comment by Mugen87** [comment]
Ah, now I can reproduce one issue. If you select 3D objects without materials and then change `receiveShadows`, the following block produces a runtime error:

https://github.com/mrdoob/three.js/blob/9c9d05a2b91b2a76dd1e5b7409af39ed5205f49d/editor/js/Sidebar.Object.js#L569-L574

This should be an easy fix.

**Comment by Tazshelby2016** [comment]
Reading the warning, it states that somewhere, you are using the `pow()` command without checking if `f` is negative.

**Comment by Tazshelby2016** [comment]
![download (12)](https://user-images.githubusercontent.com/54291363/73994751-41331480-491c-11ea-8c59-7fddd040e293.png)
![download (13)](https://user-images.githubusercontent.com/54291363/73994858-95d68f80-491c-11ea-9856-6124e27bcb2a.png)
![download (14)](https://user-images.githubusercontent.com/54291363/73994859-9707bc80-491c-11ea-98dd-4d4acdeb1fab.png)


This is the triangle on my end. Is this normal?

**Comment by Tazshelby2016** [comment]
![download (15)](https://user-images.githubusercontent.com/54291363/73994884-abe45000-491c-11ea-86f2-4dd98eb66679.png)
![download (16)](https://user-images.githubusercontent.com/54291363/73994935-cb7b7880-491c-11ea-8e46-e97bd705eb12.png)
![download (17)](https://user-images.githubusercontent.com/54291363/73994936-cc140f00-491c-11ea-9f23-270b85b12212.png)

**Comment by Mugen87** [comment]
> Reading the warning, it states that somewhere, you are using the pow() command without checking if f is negative.

This is a DirectX warning since you are on Windows. It does not appear e.g. on macOS or Linux.

Do you know how the following error can be reproduced?

> Menubar.Edit.js:161 Uncaught TypeError: Cannot read property 'isShaderMaterial' of undefined

**Comment by Mugen87** [comment]
@mrdoob I've investigate the DirectX warning a little bit more. It's actually possible to avoid it if certain places in the shader code are enhanced with an `abs()` statement. E.g. here:

https://github.com/mrdoob/three.js/blob/347c799b37cf23bfb249f5927260f929dc6d2a46/src/renderers/shaders/ShaderChunk/encodings_pars_fragment.glsl.js#L21

So instead of `pow( value.rgb, vec3( 0.41666 )` it would be `pow( abs( value.rgb ), vec3( 0.41666 )`.

There are 13 places in the core where such an enhancement would be necessary. I don't think the additional calls of `abs()` would noticeably affect performance. However, since it's only a DirectX issue, other platforms actually don't need these calls so they would be redundant.

As mentioned in this [thread](https://www.gamedev.net/forums/topic/646341-error-in-glsl-powf-e-will-not-work-for-negative-f/5083832/), the warning is only produced if the shader compiler deduces the first argument given to `pow()` _can_ be negative. In other words, the warning does not automatically appear when using `pow()` but only when the compiler thinks so based on the processed code. To avoid confusion at other places (see https://github.com/mozilla/hubs/issues/1086), I think it's okay to accept the small overhead and prevent the warnings in the first place.

**Comment by mrdoob** [comment]
@Mugen87 Thanks for digging into this! Do you mind doing a PR with the `abs()` change so we can get a better picture of the changes?

**Comment by mrdoob** [comment]
@Mugen87 reported it to Chrome too.
https://bugs.chromium.org/p/chromium/issues/detail?id=1050238

**Comment by Mugen87** [comment]
The discussion at `bugs.chromium.org` is already interesting 🤓. It would be great if ANGLE could automatically injects `abs()` into into a `pow()` statement.

**Comment by Mugen87** [comment]
Um, should I wait with a PR until it's clear how the Chromium bug is resolved?

**Comment by mrdoob** [comment]
Yes. Seems like they're going to try to hide that message.

**Comment by mrdoob** [comment]
> It would be great if ANGLE could automatically inject `abs()` into into a `pow()` statement.

I think doing a `max( 0, f )` would be safer, but we'll see what they do.

**Comment by Tazshelby2016** [comment]
These 15 warnings look like a variation of ones seen in @18422. It may be valid to continue tracking this there.

**Comment by Mugen87** [comment]
The `pow()` warning is unrelated to #18422.

**Comment by Tazshelby2016** [comment]
They are a result of the same source - Both this warning, and the errors involve sign-specific operations failing to, or intentionally checking for incorrect signs.
