### ISSUE TITLE
examples/js/tween.min.js is gone?

### ISSUE THREAD

**Issue by nimeso** [mrdoob/three.js#18554]
This file used to be there?
examples/js/tween.min.js

**Comment by Mugen87** [comment]
Yes, it was removed during the module migration. The examples now use the lib from `examples/jsm/libs/tween.module.min.js`.

In any event, if your app requires `tween.js`, it's better to grab the lib from a CDN or by using the respective npm package: https://www.npmjs.com/package/@tweenjs/tween.js
