### ISSUE TITLE
Collada Exporter doesn't handle InstancedMeshes

### ISSUE THREAD

**Issue by marekjedrzejewski** [mrdoob/three.js#18572]
When using InstancedMesh for repeating objects and then exporting it through ColladaExporter, only the base mesh appears in exported model, no instances.

**Comment by mrdoob** [comment]
As far as I know, Collada doesn't support instancing:
https://www.khronos.org/files/collada_spec_1_4.pdf

GLTF has a proposal though:
https://github.com/KhronosGroup/glTF/pull/1691

**Comment by donmccurdy** [comment]
^we could also export InstancedMesh by writing:

- Group
  - Mesh
  - Mesh
  - ...

... where all the Meshes share the same Geometry. That would avoid duplicating geometry data in a glTF file at least, and I'd guess COLLADA would do the same. But in any format, it's going to import back without the draw call savings.

**Comment by marekjedrzejewski** [comment]
Maybe, if the conversion would be optional, `ColladaExporter` should have one option like `convertInstancesToMeshes` passed to `parse()` instead of having to convert meshes before exporting them?

**Comment by Mugen87** [comment]
> Depending of the use case we could do a utility that converts a InstancedMesh to multiple Meshes and leave it up to the dev to use it on their use case before exporting.

I vote for a utility method. Maybe something like `SceneUtils.createMeshesFromInstancedMesh()`?

**Comment by Mugen87** [comment]
First approach:
```js
THREE.SceneUtils = {

	createMeshesFromInstancedMesh: function ( instancedMesh ) {

		var group = new THREE.Group();

		var count = instancedMesh.count;
		var geometry = instancedMesh.geometry;
		var material = instancedMesh.material;

		for ( var i = 0; i < count; i ++ ) {

			var mesh = new THREE.Mesh( geometry, material );

			instancedMesh.getMatrixAt( i, mesh.matrix );
			mesh.matrix.decompose( mesh.position, mesh.quaternion, mesh.scale );

			group.add( mesh );

		}

		group.position.copy( instancedMesh.position );
		group.quaternion.copy( instancedMesh.quaternion );
		group.scale.copy( instancedMesh.scale );

		group.updateMatrixWorld();

		return group;

	},

        //

};
```

**Comment by makc** [comment]
once you put it in collada exporter, all the other exporters are going to want it. so yes, +1 for utility

**Comment by Mugen87** [comment]
Okay, since the helper is now available I think we can close this issue. If necessary, users can perform the conversion by themselves before performing the export.

**Comment by d3tr0id** [comment]
> First approach:
> 
> ```js
> THREE.SceneUtils = {
> 
> 	createMeshesFromInstancedMesh: function ( instancedMesh ) {
> 
> 		var group = new THREE.Group();
> 
> 		var count = instancedMesh.count;
> 		var geometry = instancedMesh.geometry;
> 		var material = instancedMesh.material;
> 
> 		for ( var i = 0; i < count; i ++ ) {
> 
> 			var mesh = new THREE.Mesh( geometry, material );
> 
> 			instancedMesh.getMatrixAt( i, mesh.matrix );
> 			mesh.matrix.decompose( mesh.position, mesh.quaternion, mesh.scale );
> 
> 			group.add( mesh );
> 
> 		}
> 
> 		group.copy( instancedMesh );
> 		group.updateMatrixWorld(); // ensure correct world matrices of meshes
> 
> 		return group;
> 
> 	},
> 
>         //
> 
> };
> ```

How could I use this to maintain the colors of the instancedMesh? In my code I set the colors for each mesh.count and then using this function I can also export it to GLTF, but without colors. Do you have an idea? Thanks!

**Comment by Mugen87** [comment]
> How could I use this to maintain the colors of the instancedMesh?

The method does currently not support colors. Can you please try if this solves your issue:
```js
THREE.SceneUtils = {

	createMeshesFromInstancedMesh: function ( instancedMesh ) {

		var group = new THREE.Group();

		var count = instancedMesh.count;
		var geometry = instancedMesh.geometry;

		for ( var i = 0; i < count; i ++ ) {

			var material = instancedMesh.material.clone();
			instancedMesh.getColorAt( i, material.color );

			var mesh = new THREE.Mesh( geometry, material );

			instancedMesh.getMatrixAt( i, mesh.matrix );
			mesh.matrix.decompose( mesh.position, mesh.quaternion, mesh.scale );

			group.add( mesh );

		}

		group.copy( instancedMesh );
		group.updateMatrixWorld(); // ensure correct world matrices of meshes

		return group;

	},

        //

};
```

**Comment by d3tr0id** [comment]
It works! Thank you very much 👍 Now I get a drawCall for every Sphere in my GLTF Export, but thats another topic 🥲

**Comment by Mugen87** [comment]
Sidenote: The above code can be implemented a bit smarter if a material per mesh is only used when colors per instance are defined. 

@mrdoob A material per mesh is not ideal but do you think it's still worth adding such an addition?
