### ISSUE TITLE
Broken DOF Example 

### ISSUE THREAD

**Issue by mirohristov-com** [mrdoob/three.js#18607]
##### Description of the problem

The first DOF example doesn't seem to be producing the desired result.
https://threejs.org/examples/webgl_postprocessing_dof.html

It's as if the depth buffer is scaled and is being repeated a 100 times or something. Idk.
![image](https://user-images.githubusercontent.com/7188826/74287057-115a8700-4cf7-11ea-9006-cb50214b325e.png)

Here's a working demo with the desired result but it's running on r32:
http://www.ro.me/tech/demos/4/index.html
No banding here.

Using Spector.js I was able to see the depth map for each example:
Current r113 example depth map:
![image](https://user-images.githubusercontent.com/7188826/74298072-b2a50580-4d16-11ea-9483-66b895522055.png)
Old r32 example depth map:
![image](https://user-images.githubusercontent.com/7188826/74298090-bfc1f480-4d16-11ea-940d-4c785198a906.png)

This is where the issue might be I think.

Sorry, I'm a total noob and can't contribute anything else than point out the bug.

##### Three.js version

- [x] r113

**Comment by makc** [comment]
@mirohristov-com maybe try to replace this code
```
		"	#if DEPTH_PACKING == 1",
		"	return unpackRGBAToDepth( texture2D( tDepth, screenPosition ) );",
		"	#else",
		"	return texture2D( tDepth, screenPosition ).x;",
		"	#endif",
```
in examples/jsm/shaders/BokehShader.js with
```
		"	return unpackRGBAToDepth( texture2D( tDepth, screenPosition ) );",
```
and see if it fixes it.

**Comment by mirohristov-com** [comment]
@makc This just blurred the entire scene equally. No banding but also DOF.
![image](https://user-images.githubusercontent.com/7188826/74302463-a0ca5f00-4d24-11ea-854c-a6b3d75188d2.png)

**Comment by makc** [comment]
well if defines do not work somehow, then
```
		"	#if PERSPECTIVE_CAMERA == 1",
		"	return perspectiveDepthToViewZ( depth, nearClip, farClip );",
		"	#else",
		"	return orthographicDepthToViewZ( depth, nearClip, farClip );",
		"	#endif",
```
also needs to change into
```
		"	return perspectiveDepthToViewZ( depth, nearClip, farClip );",
```

**Comment by mirohristov-com** [comment]
This makes no difference to the scene. Could it be what the unpackRGBAToDepth() returns?

**Comment by makc** [comment]
I dont know, I was just poking at random lines here. Sometimes Im good at this. This time I was not
