### ISSUE TITLE
wiki doesn't make sense, can't use orbitcontrols.js

### ISSUE THREAD

**Issue by cubetronic** [mrdoob/three.js#18609]
```While importing three.js via script tags is a great way to get up and running fast```

how?!?!?!?!

i can't get orbitcontrols.js to work. the wiki assumes deep knowledge of javascript, npm, node.js three.js, etc. 

https://threejs.org/docs/#manual/en/introduction/Import-via-modules

this is super frustrating.. i _hate_ npm. i _do not_ want to do anything like installing package managers or node.js or any other crap like that.

the rest of the wiki just doesn't make any sense.. `importing the module` what module? i want to use orbitcontrols.js. i found the file, i tried to link it. it doesn't work. firefox throws a "can't import" error.

the title of the wiki page itself is super confusing and ambiguous:
`Import via modules`
import what?
is there something called `via` that i'm supposed to import?
why are you talking about modules? i just want to use a file.

**Comment by cubetronic** [comment]
https://discoverthreejs.com/book/introduction/get-threejs/
that page has a tutorial that brings up the concept i'm talking about, but it is no help either. what it does show is that there are 3 ways to use things:
1. download the files
2. from a CDN
3. install as an NPM package

i downloaded all the files, but there's no way to use them because it's a maze of dependencies and imports/exports which firefox won't allow.

how am i supposed to use the orbitcontrols.js file? it seems like i'm missing something simple that everybody knows and i don't.

**Comment by makc** [comment]
> how?!?!?!?!

what do you mean, the answer is in the text you are quoting:

> via script tags

aka
```
<script src="..."></script>
```

**Comment by cubetronic** [comment]
SyntaxError: import declarations may only appear at top level of a module

**Comment by cubetronic** [comment]
this allows me to use three.js:
```
<script src="three.js"></script>
```
but that is it. it does not allow me to use OrbitControls.js

**Comment by makc** [comment]
OrbitControls is in separate js file in examples/js/controls

**Comment by cubetronic** [comment]
```
<script src="three.js"></script>
<script src="OrbitControls.js"></script>
```
does not work. it gives the error:
```
SyntaxError: import declarations may only appear at top level of a module OrbitControls.js:10
TypeError: THREE.OrbitControls is not a constructor
```

**Comment by cubetronic** [comment]
yes, i found the file "OrbitControls.js" and placed it in the folder with my html, javascript, and three.js files

**Comment by cubetronic** [comment]
"OrbitControls.js" contants the commands `import` and `export`... it first wants to `import` from `three.modules.js`, so i _also_ put that in my local folder, but it _still_ does not work.

**Comment by cubetronic** [comment]
so the errors are just stacking up:
```
    <script src="three.js"></script>
    <script src="OrbitControls.js"></script>
    <script src="three.module.js"></script>
```
results in:
```
SyntaxError: import declarations may only appear at top level of a module OrbitControls.js:10
SyntaxError: export declarations may only appear at top level of a module three.module.js:49975
TypeError: THREE.OrbitControls is not a constructorMY-PROGRAM.html:397:14

**Comment by makc** [comment]
Yeah well, your problem is that you do not want to read too much, not when it comes to learning how to work with modules, not when it comes to how to use this lib, and not even my replies in this thread :D

I clearly wrote examples/js/controls not examples/jsm/controls

**Comment by cubetronic** [comment]
the wiki clearly says `import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';`

**Comment by makc** [comment]
I rest my case :P

**Comment by cubetronic** [comment]
i can't read the whole internet. i don't know how this works, and the wiki did not help me. that's what wiki's are _for_

**Comment by cubetronic** [comment]
i tried `import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'` and _that_ didn't work either

**Comment by cubetronic** [comment]
i have _no idea_ how to get it to work

**Comment by cubetronic** [comment]
is there something you're suggesting i should read?!

**Comment by cubetronic** [comment]
```
OrbitControls

Orbit controls allow the camera to orbit around a target.
To use this, as with all files in the /examples directory, you will have to include the file seperately in your HTML. 
```
that is not clear. what does it mean by "include"? is there special javascript syntax like "import" that is supposed to "include" files?
and it says "the file". what file is "the file"? perhaps OrbitControls.js is "the file". i had to do a search to find it. so i found "the file" and tried "including" it in several ways, but it didn't work.

**Comment by cubetronic** [comment]
perhaps what it means is i just copy and paste the file contents into my own .... nope, that doesn't work

**Comment by donmccurdy** [comment]
@cubetronic please use the forums for help (https://discourse.threejs.org/). You'll likely need to share enough information to fully reproduce what you are doing, for us to help you know what is going wrong.

**Comment by donmccurdy** [comment]
While we understand that some users do not want to use NPM, or to use JavaScript `import` statements, we cannot fully document all ways of creating a project and our examples and documentation focus on the more modern approaches.

If you'd prefer to copy files into a project by hand, that is supported too, but the forums are a better way to get help with that workflow.
