### ISSUE TITLE
three.js is not easy to use

### ISSUE THREAD

**Issue by cubetronic** [mrdoob/three.js#18619]
The first part of the first sentence of the readme:
> The aim of the project is to create an easy to use

From Wikipedia:
The Three.js library is a single JavaScript file. It can be included within a web page by linking to a local or remote copy.
`<script src="js/three.min.js"></script>`

This gave me the impression that that is all I would need to do, apart from learning about how it works, reading documentation, etc. But this impression is wrong.

My specific complaint is that THREE.js cannot load an image. It cannot preform one of the most trivial tasks of the World Wide Web since 1995. Instead, it ***requires*** setting up a web server, like Node.js, using a package manager like npm, and I don't know if that's the tip of the iceberg or not.

From the docs:
> While importing three.js via script tags is a great way to get up and running fast...

That is patently not true. THREE.js has a serious dependency problem. After asking for help on the forum, my only 2 replies were "set up a web server" and "use data URL's". Neither should be necessary.

If it's harder than this:
```
<img src="cat.jpg">
```
you're doing it wrong

**Comment by donmccurdy** [comment]
This has nothing to do with threejs — modern browsers do not load images from local disk for security reasons.  No JavaScript library can change that.

As we have said, please use the forum for help: https://discourse.threejs.org/
