### ISSUE TITLE
eslint finds errors

### ISSUE THREAD

**Issue by wercool** [mrdoob/three.js#18616]
Expected an assignment or function call and instead saw an expression

			// empty tracks are forbidden, so keep at least one keyframe
			if ( from >= to ) to = Math.max( to, 1 ), from = to - 1;
should be 
if ( from >= to ) to = Math.max( to, 1 ); from = to - 1;

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/blob/dev/src/animation/KeyframeTrack.js#L257

**Comment by wercool** [comment]
Yes, exactly this!
I'm sorry, I've found out this while linting, and eslint points me to the line inside a bundle, so was hard to find exact file where exactly it in three.js.

**Comment by wercool** [comment]
One more, from the same story:

						if ( 'THREE' in window && 'LegacyJSONLoader' in THREE ) {

							var geometryLoader = new THREE.LegacyJSONLoader();

in a given context THREE is undefined

**Comment by mrdoob** [comment]
> I'm sorry, I've found out this while linting, and eslint points me to the line inside a bundle, so was hard to find exact file where exactly it in three.js.

```shell
cd src
grep "if ( from >= to ) to = Math.max( to, 1 ), from = to - 1;" * -r
```

**Comment by wercool** [comment]
I have already applied rollup plugin. Let registry.npmjs.org  be a single source of truth. It was just FYI.

**Comment by Mugen87** [comment]
> should be
if ( from >= to ) to = Math.max( to, 1 ); from = to - 1;

Um, I don't think this is right. It should be:
```js
if ( from >= to ) {

     to = Math.max( to, 1 );
     from = to - 1;

}
```
Otherwise `from = to - 1;` is always executed.

**Comment by RemusMar** [comment]
> `if ( from >= to ) to = Math.max( to, 1 ), from = to - 1;`

That "lazy" kind of syntax should be always avoided.
If you still want a clean single line:

`if ( from >= to ) { to = Math.max( to, 1 ); from = to - 1; }`
