### ISSUE TITLE
We need glTF model including lights extension

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#18629]
##### Description of the problem

We have removed glTF Monster model in #18579. It was the only glTF model which has lights extension in our examples. I think we need a new model (or another existing model) which has lights extension for the test and showing we support lights extension.

##### Three.js version

- [x] Dev
- [ ] r113
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by cx20** [comment]
The only glTF model that corresponds to the Lights extension I know is the following PR.
https://github.com/KhronosGroup/glTF-Sample-Models/pull/210

**Comment by donmccurdy** [comment]
Yeah, the current examples available aren't really clear — you can see that there _is_ light, but it's not obvious whether the lighting configuration is right. It would probably be best to create a new example in Blender, with clear success/failure modes like this sample: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest.

**Comment by cx20** [comment]
Of course, it is desirable that there is a cool model. Unfortunately, I still don't know that.

@emackey Do you have any advice?

**Comment by emackey** [comment]
Someday I hope to find the time to make such a sample model for punctual lights.  Right now I seem to have my hands full with clearcoat and other PBR Next extensions.

**Comment by Mugen87** [comment]
We could make a new example with https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/LightsPunctualLamp. 

The asset also makes use of `KHR_materials_transmission`. When testing, I have noticed some light glitches on the lampshade though when moving the camera (the surfaces sometimes flickers at the top of the lampshade). 

The glitch only seem to appear when a transmissive surface also reacts on the point lights in the scene. When turning off the punctual lights, the glitch is gone.

https://raw.githack.com/Mugen87/three.js/dev72/examples/webgl_loader_gltf_lights.html
