### ISSUE TITLE
setPoseTarget not migrated from WebVRManager to WebXRManager

### ISSUE THREAD

**Issue by ashconnell** [mrdoob/three.js#18633]
WebVRManager used to have a `setPoseTarget` method to control which object (instead of the camera) would be oriented based on the session viewers pose.

This method was used by A-Frame and there is a [small discussion here](https://github.com/mrdoob/three.js/pull/18012) proposing it wasn't needed because they were the only ones using it.

There is [another discussion](https://github.com/mrdoob/three.js/pull/15242) about monkey-patching and/or dealing with this stuff outside of three.

**There are actually various projects out there that are using setPoseTarget not just A-frame.** 

When using WebXR with Three, the orientation of the viewer is directly applied to the camera. This is problematic in all but the simplest of situations:

1. When you want users to start VR facing a certain direction, the pose orientation Y should be multiplied by the initial orientation Y
2. When you want to teleport users from one place to another, facing a different direction, the same method as above is required
3. When the camera is attached as a child of an object that represents the players model (eg in a networked environment). In this case, the head object is already oriented correctly from the pose (outside three) and the camera should just follow suit.

So.... should we bring this back?

~~An alternative is to offer an option to disable three from forcing the camera orientation to allow us to manage it ourselves. This may be a better option since @mrdoob said it was nightmare managing the setPoseTarget implementation.~~ - scratch that, i was thinking way too outside the box here

@dmarcos has A-Frame landed on a solution to this yet? Your team likely faces similar problems to the above in regards to teleporting/initial orientation

**Comment by ashconnell** [comment]
I do wonder why WebXRManager even updates the camera based on the pose at all.

Ideally WebXRManager should just help with rendering XR (eg multiview and camera array matrixes) instead of providing opinions on how poses should be processed. Every implementation is going to handle poses (viewers and inputs) differently

**Comment by dmarcos** [comment]
@ashconnell Did you find a solution?

A-Frame is on a [THREE fork](https://github.com/supermedium/three.js/commit/716720eef7bbd62f3a4717daae05411e330a17db)

**Comment by ashconnell** [comment]
@dmarcos I closed the issue because I'm not entirely sure anymore that the problem I'm having with orientation offsets is actually fixed by having a pose target. 

That being said, I could reopen this if you're using a fork? I also have another project that uses pose targets which I don't think I can update without it.
