### ISSUE TITLE
DOF only works as last pass

### ISSUE THREAD

**Issue by mirohristov-com** [mrdoob/three.js#18634]
I'm not sure if this is a bug or something I'm missing.
After looking around, I could only find [an old question](https://stackoverflow.com/questions/22019985/bokehpass-mix-with-other-postprocessing-three-js) on SO without any answers.

Here's a demo based on @Mugen87 DOF example that he fixed earlier: https://jsfiddle.net/mirohristov/w4L0u1b8/20/

```
        composer.addPass( bokehPass ); // dof doesn't work here 
        composer.addPass( effectGrayScale );
        composer.addPass( effectSobel );
        //composer.addPass( bokehPass ); // dof works only as last shader
```

In this example it doesn't matter much if it's last or not but when adding film grain, sharpen,  or bloom it does.
Thanks!

##### Three.js version

- [x] r113

**Comment by Mugen87** [comment]
`BokehPass` set `needsSwap` to `false`. That means the result of the buffer is not available in the read buffer for the subsequent post processing pass. This is done for performance reasons since usually the pass is used on its own. So adding the following line of code should solve the issue:

```js
bokehPass.needsSwap = true;
```

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.

**Comment by makc** [comment]
btw
```
        composer.addPass( effectGrayScale );
        composer.addPass( effectSobel );
```
adding effectGrayScale before effectSobel is rather pointless, the change is barely noticeable.  this is degrading performance for no reason.

**Comment by Mugen87** [comment]
The [example](https://threejs.org/examples/webgl_postprocessing_sobel) uses a grayscale pass  because Sobel is by definition a grayscale operator. It is designed to  detect changes in intensity.

Yes, you can run it on color but it's not academically correct.

**Comment by makc** [comment]
real time graphics was built on math that was not academically correct. until PBR people came )
