### ISSUE TITLE
Don't assume that an inputsourceschange event will be fired at the start of the session

### ISSUE THREAD

**Issue by Manishearth** [mrdoob/three.js#18638]
##### Description of the problem

Currently, the three.js code setting up XR controllers only does this setup when an `inputsourceschange` event is fired. However, it is possible for a session to start with controllers already attached. My understanding is that Chrome will always fire `inputsourceschange` events at the beginning of the session, but I don't think this is necessary according to the spec. Servo currently just starts off with the correct input sources, only spawning events when things change.

We should instead initialize the controller map when the session is created.

https://github.com/mrdoob/three.js/blob/fb29d21e65c2cb8a0bf8b797c0deefa5fe8c8cde/src/renderers/webxr/WebXRManager.js#L233

##### Three.js version

- [x] Dev
- [ ] r113
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

 - VR Device

**Comment by mrdoob** [comment]
> My understanding is that Chrome will always fire `inputsourceschange` events at the beginning of the session, but I don't think this is necessary according to the spec. 

@toji any opinion?

**Comment by Manishearth** [comment]
On further investigation it seems like what Servo does is incorrect, however the spec _currently_ does not guarantee that the `inputsourceschange` event will fire at a time when threejs will be able to catch it. The spec needs fixing here, based on the fix there it might depend as to what threejs should do here. Worth holding off on making any changes till we decide something there.

https://github.com/immersive-web/webxr/issues/961

**Comment by Manishearth** [comment]
Thinking about it more, the exact scheduling here is super dicey (https://github.com/immersive-web/webxr/issues/961#issuecomment-586557889). While we do guarantee that the input sources change event will be fired after the session is _created_, it's not necessary that the input sources change event will be fired after the microtask from the resolution happens, and while we can _perhaps_ guarantee that, it would require relying on how task scheduling works in the DOM, so perhaps ... not worth doing. It might be a safe bet to land #961 _anyway_.

I now more strongly suspect that even if Chrome seems to work with the current threejs impl, there are probably hidden races involved, since I can't find explicit code dealing with the scheduling.

**Comment by paulmasson** [comment]
@Manishearth as another data point on this issue, I found that Oculus browsers don't always fire the `inputsourceschange` event [consistently, ](https://github.com/mrdoob/three.js/pull/18608#issuecomment-585065218), so I proposed a check in #18608 to prevent that from crashing the renderer

**Comment by Manishearth** [comment]
Yeah that seems like something we could land with this. I hope to have this fixed upstream though.

**Comment by Manishearth** [comment]
Unnecessary due to upstream spec changes (https://github.com/immersive-web/webxr/issues/961).

**Comment by Mugen87** [comment]
> Unnecessary due to upstream spec changes (immersive-web/webxr#961).

As far as I understand, this issue and the respective PR #18639 can be closed then, right? The tweaks to the specs ensures that `inputsourceschange` should be fired on start by WebXR implementations, correct?

**Comment by Manishearth** [comment]
Yes.
