### ISSUE TITLE
PointLight: fade effect not working in latest version

### ISSUE THREAD

**Issue by allan-almeida** [mrdoob/three.js#18650]
Hello,

Being new to `three` (long-time fan) I am experimenting with this online example:
[https://codesandbox.io/s/alligatordemoreact-three-fiber-r5i7p](https://codesandbox.io/s/alligatordemoreact-three-fiber-r5i7p)

The example contains a `PointLight`, with the light effect fading in intensity the further away from the point it gets. However this effect doesn't seem to work the same way as with the latest version which I am running locally.

Can be reproduced in the example itself by updating the version in `package.json` :

Works with `0.111.0`:

<img width="1680" alt="111" src="https://user-images.githubusercontent.com/24609799/74625547-c631ef80-51a0-11ea-8e99-443adc11cbeb.png">

Not with `0.112.0`:

<img width="1680" alt="112" src="https://user-images.githubusercontent.com/24609799/74625564-d944bf80-51a0-11ea-9269-8aa4db30977d.png">

I've inspected the `PointLight.js` files from both versions and they look identical, and also could not see any PointLight related changes in the `r112` release notes, although being new to `three` I may have missed something relevant.  Could you please let me know if this is expected behaviour and if so, how I can reproduce the effect in the latest version?

Thanks!

##### Three.js version
- r111 works
- r112 doesnt

##### Browser
- [x] Chrome

##### OS
- [x] macOS

**Comment by Mugen87** [comment]
The default values of metalness/roughness have changed in R112 (see https://github.com/mrdoob/three.js/wiki/Migration-Guide#r111--r112). By using the previous values (notice the change in `index.js`), the result looks as expected.

https://codesandbox.io/s/alligatordemoreact-three-fiber-rm09d

**Comment by allan-almeida** [comment]
thank you @Mugen87 !!
