### ISSUE TITLE
Audio pause still not working properly

### ISSUE THREAD

**Issue by SUDOCS** [mrdoob/three.js#18659]
##### Description of the problem

Hello.
When paused and resumed twice, the audio will start from the beginning.
```js
audio.play()
...
audio.pause()
...
audio.play()
...
audio.pause()
...
audio.play() // issue occurs
```

* [jsfiddle](https://jsfiddle.net/SUDOCS/vxbk4162/) (latest release)

##### Three.js version

- [x] r113

##### Browser

- [x] Chrome
- [x] Firefox

##### OS

- [x] Windows
- [x] Android

**Comment by SUDOCS** [comment]
I override the audio pause function in my project, and it's behavior meets my expectation. The only change is variable `this._pauseAt`

```js
THREE.Audio.prototype.pause = function () {
  if (this.hasPlaybackControl === false) {
    console.warn('THREE.Audio: this Audio has no playback control.')
    return
  }

  if (this.isPlaying === true) {
    // this._pausedAt = ( this.context.currentTime - this._startedAt ) * this.playbackRate;
    this._pausedAt = this.context.currentTime * this.playbackRate

    this.source.stop()
    this.source.onended = null

    this.isPlaying = false
  }

  return this
}
```

- [jsfiddle](https://jsfiddle.net/SUDOCS/jmdsnv7p/)

**Comment by Mugen87** [comment]
Yes, I can confirm that the current implementation is not correct if you start/stop the audio more than once. However, your change is not 100% correct since it does not work if you pass in a delay when first calling `play()`.

https://jsfiddle.net/vwbnoey6/

Now the first usage of `pause()` is wrong.

**Comment by Mugen87** [comment]
I think this is the correct change: https://jsfiddle.net/8gyfszbL/

@SUDOCS Can you please verify? The idea is to implement the line like so:
```
this._pausedAt += Math.max( this.context.currentTime - this._startedAt, 0 ) * this.playbackRate;
```
In this way, `this._pausedAt` should always point to the right position in the audio buffer. The usage of `Math.max()` ensure that it can't be negative. This could happen when using `play()` with a delay and immediately pause the audio.

**Comment by SUDOCS** [comment]
@Mugen87 I have tried your method. Each time `play/pause` clicked, the audio starts from right position. Thank you a lot.😀
