### ISSUE TITLE
Energy loss at grazing angles?

### ISSUE THREAD

**Issue by Domenicobrz** [mrdoob/three.js#18669]
I've noticed with different hdr envmaps that reflections at grazing angles look darker than with other renderers with comparable settings (a simple sphere with roughness and metalness set to 0) 

![1](https://user-images.githubusercontent.com/25647854/74794151-bf030280-52c2-11ea-93ab-14dff5823042.jpg)
![2](https://user-images.githubusercontent.com/25647854/74794152-c0342f80-52c2-11ea-9405-c96c5ba94431.jpg)
![3](https://user-images.githubusercontent.com/25647854/74794154-c0ccc600-52c2-11ea-8f47-7b73ed876cf1.jpg)

This might as well be my eyes playing tricks with me, is there a way to confirm the output is correct? Anyone else noticed the same thing?

Here's a simplified test scene (will render the first sphere in the screenshots):
[test.zip](https://github.com/mrdoob/three.js/files/4222729/test.zip)

Pastebin of the code I'm using:
https://pastebin.com/jGRv6BWn

##### Three.js version

- [x ] Dev
- [x ] r113

##### Browser

- [x] All of them

##### Hardware Requirements (graphics card, VR Device, ...)

- GPU: RX580

**Comment by mrdoob** [comment]
How does it look on Blender? Arnold? ...?

**Comment by Domenicobrz** [comment]
After a closer look this seems like the perceptual result of using a completely white background over a material that uses an indoor environment map
