### ISSUE TITLE
ConvexGeonetry exist in the documentation, but not in the package.

### ISSUE THREAD

**Issue by Zen3515** [mrdoob/three.js#18660]
##### Description of the problem

I was following the documentation of [ConvexGeometry](https://threejs.org/docs/#examples/en/geometries/ConvexGeometry)

but when I try to 
```Javascript
new THREE.ConvexGeometry( ... )
```
It's not working I got this message,
```
Property 'ConvexGeometry' does not exist on type 'typeof import(".../node_modules/three/src/Three")'. Did you mean 'ConeGeometry'?
```

Here is the [live example link](https://runkit.com/embed/5gcnf3i38q8l)

Which produce this error

```Javascript
TypeError: THREE.ConvexGeometry is not a constructor
```

##### Three.js version

- [ ] Dev
- [x] r113
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
`THREE.ConvexGeometry` is no part of the core library. Meaning you have to import the class separately. It's best to do this with a ES6 import like so:
```js
import { ConvexGeometry } from 'three/examples/jsm/geometries/ConvexGeometry.js';
```
More information about this topic right here:

https://threejs.org/docs/index.html#manual/en/introduction/Import-via-modules

If you need more help about including example files, please use the [forum](https://discourse.threejs.org/) instead.
