### ISSUE TITLE
Do not call window.requestAnimationFrame when in webxr mode

### ISSUE THREAD

**Issue by paulrouget** [mrdoob/three.js#18666]
If I'm not mistaken, running https://threejs.org/examples/webxr_vr_rollercoaster.html in webxr mode will still run the initial webgl loop.

The webxr loop uses session.rAF, and doesn't need window.rAF to be looping.

**Comment by Mugen87** [comment]
Check out the section https://www.w3.org/TR/webxr/#animation-frames, Example 3. It seems it's no problem if two animation loops run in parallel as long as `window.rAF` does not trigger a rendering when XR is used. `three.js` ensures this can't happen with the following line:

https://github.com/mrdoob/three.js/blob/d665e52a4a48a69fcbc86a961da830b769609193/src/renderers/WebGLRenderer.js#L1096

As long as there is no measurable performance overhead I think it's okay to keep the code as it is.

**Comment by mrdoob** [comment]
> If I'm not mistaken, running https://threejs.org/examples/webxr_vr_rollercoaster.html in webxr mode will still run the initial webgl loop.

What makes you think that?

**Comment by paulrouget** [comment]
That's right, the animation is not rendered because of `if ( xr.isPresenting ) return;` but the rAF loop is still ongoing, while it's not necessary.

> What makes you think that?

We are doing some tests of our webxr implementation in Servo, and we noticed the calls to rAF.

I think it's fine if the window.rAF loop is still running. In term of performance, it won't impact much.

Just thought I would mention it.

**Comment by Mugen87** [comment]
I think this issue needs more investigation. It would be good to have some performance numbers so it's easier to evaluate the overhead of an additional animation loop.
