### ISSUE TITLE
Performance issue with intersection clippingPlanes

### ISSUE THREAD

**Issue by ricardoreiter** [mrdoob/three.js#18675]
##### Description of the problem

I'm clipping an object with clippingPlanes and clipIntersection = true.
Depending on the situation I get a massive FPS drop because the renderer starts to reinitialize some materials every frame.

I’ve found out that for this to happen you need at least three meshes and two materials (W/ shadows and clipShadows enabled):
 - MaterialA - No clipping whatsoever.
 - MaterialB - Clipping planes and clipIntersection = true.

Adding three meshes to the scene in this specific order causes the issue:
 - Mesh 1 w/ MaterialA
 - Mesh 2 w/ MaterialB
 - Mesh 3 w/ MaterialA

The issue seems to be happening in WebGLRenderer#setProgram
https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1638
 - First run with Mesh 1 has `materialProperties.numIntersection = 0`. Call to `_clipping.setState()` makes no effect. Current `_clipping.numIntersection` is 0. Mesh not reinitialized.
 - Second run with Mesh 2 calls `_clipping.setState()` which changes `_clipping.numIntersection` property to 1.
 - Third run with Mesh 3 has `materialProperties.numIntersection = 0`. Call to `_clipping.setState()` doesn’t clear out `_clipping.numIntersection`. It falls into this line https://github.com/mrdoob/three.js/blob/f7dd2f0e487094bb3297c2f2b3a7f4e1b5b8b569/src/renderers/webgl/WebGLClipping.js#L69
projectPlanes() doesn't clear out numIntersection prop. Current `_clipping.numIntersection` is 1 (because of the second run that set it to 1). As the `numIntersection` stored in materialProperties is different than the one in `_clipping` state. Material is reinitialized, see line https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1689 `materialProperties.numIntersection` for MaterialA is set to 1.

 - Fourth run (Next frame) with Mesh 1 has `materialProperties.numIntersection = 1`. `_clipping` was reseted so it has `numIntersection = 0`. Mesh gets reinitialized and `materialProperties.numIntersection` sets back to 0.

It looks like a bug to me, as it seems that in the third run `_clipping.setState` should have cleared out the last `numIntersection`. Maybe it should be setting this prop in `WebGLClipping.projectPlanes()`? Depending on the order of the elements I don't see the issue. If you add the clipped mesh before or after the other elements I get no frame rate drop.

Live example:
https://codepen.io/ricardoreiter/pen/ZEGpYPy
Disable the clipIntersection checkbox and see the FPS going up (no more material reinitialization). Changing the order that the elements get added to the scene also seems to fix it.

##### Three.js version

- [x] Dev
- [ ] r113
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by ricardoreiter** [comment]
I was able to fix this issue by resetting `WebGLClipping.numIntersection` in `projectPlanes` method. Though I'm not sure that's correct.
Commit in my forked repo: https://github.com/ricardoreiter/three.js/commit/cf9357b8e1cfd1a3e0287ed87aef66b707d72b9d

**Comment by Mugen87** [comment]
> Material is reinitialized, see line https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1689

Just for clarification: I open the codepen and add a breakpoint here:

https://github.com/mrdoob/three.js/blob/d2a4ed6c98a1621df65b7b5081715170add884fe/src/renderers/WebGLRenderer.js#L1689

However, the debugger never starts. I though executing this line per frame would cause the performance issue?

**Comment by ricardoreiter** [comment]
I was testing a few things in that codepen and saved the wrong order of adding the elements to the scene. Just changed it back to the order that causes the issue. Sorry, won't touch that codepen anymore. You should be able to debug that line now.

**Comment by Mugen87** [comment]
Thanks for updating the fiddle. Now I'm actually able to reproduce the issue.

I'm unfortunately not familiar with `WebGLClipping` so I don't know the exact semantics of `numIntersection`. However, adding the suggested line to `projectPlanes()` planes does not seem to break the examples. Espeically [webgl_clipping_intersection](https://threejs.org/examples/webgl_clipping_intersection) is important here. And I can confirm that `initMaterial()` is not called per frame anymore.

Feel free to make a PR with your patch since it seems to solve the issue.
