### ISSUE TITLE
Rethink or clean up VRButton

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#18679]
##### Description of the problem

`VRButton.createButton()` takes `options` but it's used just only for [renderer.xr.setReferenceSpaceType()](https://github.com/mrdoob/three.js/blob/r113/examples/jsm/webxr/VRButton.js#L10-L14).

Does `VRButton.createButton()` really need to take options? Even if it doesn't, the following user code can be rewritten 

```javascript
renderer = new WebGLRenderer();
renderer.xr.enabled = true;
const button = VRButton.createButton(renderer, {referenceSpaceType: 'foo'});
```

to 

```javascript
renderer = new WebGLRenderer();
renderer.xr.enabled = true;
renderer.xr.setReferenceSpaceType('foo');
const button = VRButton.createButton(renderer);
```

and I think the latter one looks simpler. What do you think of removing `options` parameter from `VRButton.createButton()`?

##### Three.js version

- [x] Dev
- [ ] r113
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
It seems `WebXRManager.setReferenceSpaceType()` is only internally used by the engine and not intended for app level code. AFAICS, if a user would try to call this method during rendering, it won't have any effect.  `referenceSpaceType` is required when `WebXRManager.setSession()` is called and that only happens when the users enters XR. Against this backdrop, it makes more sense to me if the user can apply this value only once.

**Comment by takahirox** [comment]
Thanks for the comment. You mean it's safer for users to pass `referenceSpaceType` via `VRButton.createButton()` than they call `renderer.xr.setReferenceType()` because it should be guaranteed that `renderer.xr.setReferenceType()` is called before starting a session? If so, that would make sense to me, too...

I guess originally @mrdoob added `options` to `VRButton.createButton()`? If he agrees with it, or there is any other reasonable reasons, I think it's ok to close this issue.

**Comment by Mugen87** [comment]
> You mean it's safer for users to pass referenceSpaceType via VRButton.createButton() than they call renderer.xr.setReferenceType() because it should be guaranteed that renderer.xr.setReferenceType() is called before starting a session?

Exactly 👍

**Comment by mrdoob** [comment]
I don't remember anymore to be honest. Maybe this is something WebVR needed but WebXR no longer needs.

Moving it out of `VRButton.createButton()` sounds okay to me. `VRButton` may benefit of some rethinking too.

**Comment by takahirox** [comment]
> VRButton may benefit of some rethinking too.

Agreed. Changed the title so far.
