### ISSUE TITLE
MeshPhysicalMaterial: Support clearcoatMap, clearcoatRoughnessMap

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#18677]
MeshPhysicalMaterial currently offers:

- clearcoat
- clearcoatRoughness
- clearcoatNormalMap

The [glTF extension `KHR_materials_clearcoat`](https://github.com/KhronosGroup/glTF/pull/1756) will also require texture versions of the first two, which I'd propose adding to (only) MeshPhysicalMaterial:

- clearcoatMap
- clearcoatRoughnessMap

**Comment by donmccurdy** [comment]
In progress: https://github.com/mrdoob/three.js/pull/18682

**Comment by donmccurdy** [comment]
Fixed by https://github.com/mrdoob/three.js/pull/18769.

**Comment by WestLangley** [comment]
@donmccurdy What support do you intend for clearcoat/roughness map `offset/repeat` settings?

Currently, it is not considered in the offset/repeat priority list.

**Comment by WestLangley** [comment]
https://stackoverflow.com/questions/63559688/three-meshphysicalmaterial-clearcoatnormalmap-repeatwrapping

**Comment by donmccurdy** [comment]
Hm. My first reaction would be uv2 for clearcoatNormalMap, uv1 for everything else. It would be nice to get out of having to hardcode those pairings. 😅

**Comment by WestLangley** [comment]
Should the clearcoat normal/roughness map be added to the priority list so -- at a minimum -- `offset/repeat` is honored if it is the only map.

**Comment by PaulMitch** [comment]
Are there any known limitations apart from performance that is stopping repeat texturing of the clear coat normal?
I'm happy to have a look into it if someone can point me where to start.

**Comment by WestLangley** [comment]
This is a long-standing issue. For the primary uv set, three.js only supports one offset/repeat pair per material. See #8278.

https://github.com/mrdoob/three.js/blob/c3c03a7628fd4a63d28f3a544b63546188231c48/src/renderers/webgl/WebGLMaterials.js#L177-L183

**Comment by PaulMitch** [comment]
Ok, thanks for the info. So in a perfect world we'd need 3 UV sets as AO works great on UV set 2. So the clearcoat normals would have to be moved to UV set 3 :)

**Comment by donmccurdy** [comment]
On second thought, I don't know why I suggested uv2 for clearcoat normals... all of these could be uv1, as far as I can tell. More flexibility would be nice of course, but clearcoat has no unique need for uv3, compared to other maps.

I don't know what's in your model, @PaulMitch, does it require a 3rd UV set?

If reusing the existing uv1 is enough, then my answer to @WestLangley's question ...

> Should the clearcoat normal/roughness map be added to the priority list so -- at a minimum -- offset/repeat is honored if it is the only map.

... would be yes.

**Comment by PaulMitch** [comment]
Ok so when  @WestLangley says "the only map", does that mean the only map using offset/repeat for that UV set. 
So we could potentially have an aoMap (non repeating) and a clearcoatNormalMap that repeats on UV set 2.
Is this something that could be done already using Node materials?

**Comment by donmccurdy** [comment]
The change we should probably make would be to update the code that @WestLangley linked to and ensure that if any clearcoat-related texture has a UV transform, three.js will use it. Because clearcoat maps are not in that list, they currently only get a UV transform if _another_ texture using UV1 has a transform.

My original suggestion of putting `clearcoatNormalMap` on UV2 was probably a bad idea, I don't know of any reason `clearcoatNormalMap` is more likely to share UVs with AO and lightmaps than with other clearcoat-related textures.

The NodeMaterial system has (much) more flexibility — it can pair any texture slot with any UV map, and supports an arbitrary number of UV attributes. However, (1) I don't know if we can consider it stable, and (2) I'm not sure whether new features like clearcoat, clearcoat roughness, and clearcoat normals have been added to the NodeMaterial shaders yet.

**Comment by PaulMitch** [comment]
Yeah it looks like MeshStandardNodeMaterial is added to the master branch,  Thanks for your quick responses guys, much appreciated.

**Comment by PaulMitch** [comment]
Wow adding a map texture with a transform worked great, The clearcoatnormal is now repeating. 
I was just using a colour as there was no map texture, so making that colour as an 8x8 map and making it a repeating texture worked a treat.
Thanks
