### ISSUE TITLE
Flipping BufferGeometry through BufferGeometryUtils

### ISSUE THREAD

**Issue by reimund** [mrdoob/three.js#18683]
I was doing some buffer geo flippin' yesterday when I came across this nice utility function:
https://stackoverflow.com/questions/16824650/#answer-54496265

Wouldn't this be handy to have in BufferGeometryUtils? Or is there a more convenient way to flip BufferGeometries?

**Comment by Mugen87** [comment]
Related #17361.

**Comment by Mugen87** [comment]
Closing as duplicate of #17361.
