### ISSUE TITLE
Missing some properties in MeshPhysicalMaterial document

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#18680]
##### Description of the problem

It seems lack of some properties in `MeshPhysicalMaterial` document.

https://threejs.org/docs/#api/en/materials/MeshPhysicalMaterial

Ever what I noticed are
- clearcoatNormalScale
- clearcoatNormalMap
- sheen
- transparency

We should update.

##### Three.js version

- [x] Dev
- [ ] r113
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
There might be some justification for leaving them undocumented if we think the API is still evolving... that might be true of sheen? But I think clearcoatNormalScale and clearcoatNormalMap are unlikely to change. I have no idea about ".transparency" 😓

**Comment by takahirox** [comment]
Oh, I forgot that there may be a chance that it is intentional.. Anyone knows about it?

Off topic, it may be helpful to devs if we add note in the code if we intentionally undocument certain properties/methods.

**Comment by donmccurdy** [comment]
✨ super secret, tell no one 😎 ✨

**Comment by Mugen87** [comment]
I think it's safe to document `clearcoatNormalScale`, `clearcoatNormalMap` and `transparency`. I would wait with `sheen` until #17700 is resolved.

**Comment by QuidCode** [comment]
<h3>[property:Float clearcoatNormalMap]</h3>

Incorrectly documented as a Float  - minor issue, yet clearly, and correctly specified in the Class

**Comment by Mugen87** [comment]
Thanks fir reporting. Fixed!

**Comment by rock125** [comment]
https://tech4two.com/huawei-releases-shanghai-flagship-store-as-us-pressure/ click this link to get interesting tech news and articles.
