### ISSUE TITLE
webxr AR Can not work with FBXLoader

### ISSUE THREAD

**Issue by ItIsArmin** [mrdoob/three.js#18693]
##### Description of the problem
FBXLoader is not working with webxr / Ar / hittest , I'm running the current example but simply replacing the cylinder mesh with an object loaded with FBXLoader, and I'm receiving the following WebGL warnings:
- three.module.js:16000 THREE.WebGLRenderer: EXT_frag_depth extension not supported. `three.module.js:16000`
- THREE.WebGLRenderer: WEBGL_draw_buffers extension not supported. `three.module.js:16000`
- three.module.js:16000 THREE.WebGLRenderer: EXT_shader_texture_lod extension not supported. `three.module.js:16000`

- WebGL: INVALID_ENUM: bufferData: invalid usage  `three.module.js:14449 `
- [.WebGL-0xcbb07700]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 0 

##### Three.js version

- [ ] Dev
- [x] r113
- [ ] ...

##### Browser
- [x] Chrome Dev
##### OS
- [x] Android

**Comment by mrdoob** [comment]
Please, use the [forum](https://discourse.threejs.org/) for help.

**Comment by ItIsArmin** [comment]
> Please, use the [forum](https://discourse.threejs.org/) for help.

I was hoping for a **Feature Request** Lable, but thank you anyways

**Comment by mrdoob** [comment]
There is no reason `FBXLoader` shouldn't work with WebXR.

If you want us to take a look into it you need to create a jsfiddle that proves that it doesn't work, otherwise you're asking us to debug your own code.

**Comment by ItIsArmin** [comment]
Sorry it turned out to be my mistake using the older versions of FBXLoader
A working scene just for reference with Glitch: [Live ](https://momentous-aphid-nweqid0qn4.glitch.me/), [Code](https://glitch.com/edit/#!/momentous-aphid-nweqid0qn4)

**Comment by Mugen87** [comment]
https://discourse.threejs.org/t/fbxloader-in-webxr-ar/12902

**Comment by mrdoob** [comment]
> Sorry it turned out to be my mistake using the older versions of FBXLoader

🙃
