### ISSUE TITLE
Need an example of text via texture

### ISSUE THREAD

**Issue by dcromley** [mrdoob/three.js#18698]
Documentation:
The page [https://threejs.org/docs/#manual/en/introduction/Creating-text] says:
"2. Draw text to canvas and use as a Texture
"Use this method if you wish to draw text easily on a plane in your three.js scene.
But there is a dire need for a simple example of this.
I offer this example: [http://dbarc.net/yr2020/threejstextexample.html]
I hope you take this and modify it to your standards.  I release all rights to the code.
Thanks for a great library.  Dave

**Comment by Mugen87** [comment]
There is already [webgl_materials_texture_canvas](https://threejs.org/examples/webgl_materials_texture_canvas) that shows how you can use a canvas as a texture. You can draw a lot of stuff on a canvas and I'm not sure it's worth to add an example for all these use cases (including text).

In any event, thanks for sharing your code.
