### ISSUE TITLE
Examples: add tags support to search

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#18700]
e.g. rename webgl_postprocessing_unreal_bloom_selective.html to webgl_postprocessing_glow_unreal_bloom_selective.html, and the other one too.

because people typing "glow" in examples search box get nothing.

**Comment by Mugen87** [comment]
This suggestion does make sense. It's just a bit unfortunate how long the file names are now.

Do we really need the bit `unreal` in these names? AFAIK, we normally do not encode the name of an approach into the example. Exchanging `unreal` with `glow` seems a nice tradeoff.

**Comment by mrdoob** [comment]
I don't think we need `unreal`, but I don't know how to solve `glow` vs `bloom`.

**Comment by makc** [comment]
well unless you are going to implement some tags syste, it has to be file names, right?

**Comment by mrdoob** [comment]
We could implement some internal query replacement code.

Pseudo code:
```js
if ( search === 'glow' ) search = 'bloom';
```

**Comment by makc** [comment]
@mrdoob then there will be no results until full word is typed. what if someone types `glo` and, seeing there is nothing, stops typing?

**Comment by mrdoob** [comment]
With the current code that is correct. We could make the code a bit smarter too.

Just trying not to end with `webgl_postprocessing_glow_bloom_shine_foo_bar_selective.html`.

**Comment by makc** [comment]
so the tag system then? such that every example would have a number of tags
attached to them, and these tags would be searchable as well

**Comment by Mugen87** [comment]
> With the current code that is correct. We could make the code a bit smarter too.

I vote for this approach instead of introducing a real tag system.

**Comment by mrdoob** [comment]
So in https://github.com/mrdoob/three.js/blob/dev/examples/files.js we could add:

```js
var tags = {
    "webgl_postprocessing_unreal_bloom_selective.html": [ "glow" ]
};
```

**Comment by munrocket** [comment]
Want to solve this with tag system. I will create a PR.

**Comment by munrocket** [comment]
@makc I make draft PR #18773, can you finish it using this [reference](https://rawcdn.githack.com/callumprentice/three.js/877624e65ea4cee51a272440cd6f43b0f2dc593e/examples/index_thumbs.html)?
It is ok that I am added tags into a file definition?

**Comment by makc** [comment]
@munrocket Im not sure how do I finish somebody elses PR. or do you mean forking your fork and then submitting PR into your fork?
![😨](https://cdn.discordapp.com/emojis/650833439313887263.png?v=1)

**Comment by munrocket** [comment]
You can copypaste it and make it as your on PR and I will close draft.

**Comment by munrocket** [comment]
I don’t want to wipe all the history in this file by myself. So help me please.

**Comment by makc** [comment]
ok np, I will take a look tonight, let me know what does not work there as of now

**Comment by munrocket** [comment]
Run `git cherry-pick 68f1ee6` to grab all changes in your repo.

**Comment by makc** [comment]
bump!
![Screen Shot 2020-04-27 at 20 49 49 ](https://user-images.githubusercontent.com/242577/80409259-d238dc80-88c8-11ea-9e84-37bd1193b555.png)

**Comment by munrocket** [comment]
I am thinking about:
* adding a bigger list
* adding a new section "searched by tags" in UI, now some of the examples appearing silently

**Comment by munrocket** [comment]
Sorry, but still not fixed, sometimes we can’t find anything in documentation and examples. Searching filter is too basic and also we need thumbnails.

One girl said that searched one example 1 hour, it’s exactly the same that we all doing when forgot proper name. Even experienced programmers sometimes forgot something.

Probably additional DOM lines that I added in «searched by tags» was too laggy, but I am thought about users when I done it. This changes in a proper direction.

**Comment by Mugen87** [comment]
I'm fine with improving the example search as long as not over-engineering happens. Please keep it simple even if the search has to forgo a few advanced features.

**Comment by munrocket** [comment]
Ok, but searching algos sometime not an easy task. This operation is O(1) in general.
That's why double sized DOM was laggy little bit, if you about this.

**Comment by makc** [comment]
ha, @munrocket looks really pissed that you guys did not like his commits. look, munrocket, my code did not make it either - mrdoob ended up committing his own version - and guess how upset I am?
![not at all](https://i.pinimg.com/originals/a4/78/2a/a4782a8b4287de937b3363ee1f75dab9.jpg)
take notes, and keep adding them tags.

**Comment by munrocket** [comment]
Kek, the chad contributor here.
He don't care about his commits and dump dumbest version.
MrDoob take it and ended up committing edited version.

**Comment by makc** [comment]
That was what happened, yes.

![](https://media.giphy.com/media/55SfA4BxofRBe/giphy.gif)

**Comment by munrocket** [comment]
That issue was not fixed for 2 month. It's happening.

**Comment by makc** [comment]
@munrocket I remember firefox had issues not fixed in 20 years, so it is not that bad yet

**Comment by munrocket** [comment]
```
Mozilla should support the scrollbar-(blah)-color properties implemented in IE5.5
```
lol, they achieved IE5.5 level.
