### ISSUE TITLE
Update contribution guide in Wiki

### ISSUE THREAD

**Issue by munrocket** [mrdoob/three.js#18712]
##### Description of the problem

We have [e2e testing](https://github.com/mrdoob/three.js/pull/18574) with puppeteer and screenshots, it's good to mention how to generate a new screenshots for contributors. I make a draft [here](https://github.com/munrocket/three.js/commit/dbffee8d1e111f50455003804b92b0d99f618748?short_path=84674fb#diff-84674fb93abf7e00c5950dbf8a08a0e4) where I am add one line in the end and reordered items in list with small correction (deleted Atom suggestion from it).

**Comment by mrdoob** [comment]
Would you like to do a PR with that draft?

**Comment by munrocket** [comment]
Don't know how to do it in Wiki page. Seems that we don't have a mirror in main repo.

**Comment by mrdoob** [comment]
Just invited you as collaborator.

**Comment by munrocket** [comment]
Updated. Give feedback if I have spelling error or something.

**Comment by munrocket** [comment]
https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js

**Comment by mrdoob** [comment]
Diff: https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js/_compare/c4c53850fa54993595ec04d78dbd3f9923194337
