### ISSUE TITLE
OBJExporter object.name

### ISSUE THREAD

**Issue by gonnavis** [mrdoob/three.js#18727]
It seems .obj format's **o** tag must has a name, because I find, if has not name, Blender importer will fail to import all objects, 3DsMAX will only import last object.
But OBJExporter not auto add **name** to o tag if the Object3D hasn't name property, and not alert user.
Shall we add auto-name ability to it all at leaset alert user about the absent of Object3D.name?

error_with_Blender2.80.obj
```
o 
v 70 50 0
v 170 50 0
v 70 -50 0
v 170 -50 0
vt 0 1
vt 1 1
vt 0 0
vt 1 0
vn 0 0 1
vn 0 0 1
vn 0 0 1
vn 0 0 1
f 1/1/1 3/3/3 2/2/2
f 3/3/3 4/4/4 2/2/2
o 
v -50 -50 0
v 50 -50 0
v 50 50 0
vn 0 0 1
vn 0 0 1
vn 0 0 1
f 5//5 6//6 7//7
```

success_with_Blender2.80.obj
```
o 1
v 70 50 0
v 170 50 0
v 70 -50 0
v 170 -50 0
vt 0 1
vt 1 1
vt 0 0
vt 1 0
vn 0 0 1
vn 0 0 1
vn 0 0 1
vn 0 0 1
f 1/1/1 3/3/3 2/2/2
f 3/3/3 4/4/4 2/2/2
o 2
v -50 -50 0
v 50 -50 0
v 50 50 0
vn 0 0 1
vn 0 0 1
vn 0 0 1
f 5//5 6//6 7//7
```

##### Three.js version

- [x] Dev
- [ ] r113
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
According to this [source](https://en.wikipedia.org/wiki/Wavefront_.obj_file), object names are optional.

```
o [object name]
  ...
  g [group name]
  ...
```
So it seems it's more a problem of the Blender OBJ importer.

> It seems .obj format's o tag must has a name,

Can you please share a reference that says that object names are mandatory?

**Comment by gonnavis** [comment]
Oh, It's a problem with Blender2.8.0.
After updated to Blender2.8.1, all OK!
