### ISSUE TITLE
npm cant resolve package in azure

### ISSUE THREAD

**Issue by GrimZero** [mrdoob/three.js#18725]
##### Description of the problem
When adding threejs as a dependency on a project and trying to build it (tested both locally and in azure) the tsc cannot resolve these 2 errors. I have asked about this about a month ago and have since been working around the issue. However as we are setting up a pipeline to automatically compile our project, this no longer works as needed. Whenever an `npm install` command is performed the issue returns on the tsc, presumably this is some kind of compilation issue related to using npm with threejs.

The error:
`node_modules/three/src/geometries/ExtrudeGeometry.d.ts(2,10): error TS2440: Import declaration conflicts with local declaration of 'UVGenerator'.
node_modules/three/src/materials/ShaderMaterial.d.ts(1,10): error TS2440: Import declaration conflicts with local declaration of 'ShaderMaterialParameters'.
`

The origin of the error:
`import { ShaderMaterialParameters } from './ShaderMaterial';
export interface ShaderMaterialParameters extends MaterialParameters {
//...
}`

##### Three.js version
- Tested with multiple versions from 104 - 113

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Related: https://discourse.threejs.org/t/tsc-error-2440-when-using-three-108-uv-generator-and-shadermaterialparameters/11937

**Comment by Mugen87** [comment]
> When adding threejs as a dependency on a project and trying to build it (tested both locally and in azure) the tsc cannot resolve these 2 errors.

What version of TS are you using in your project?

**Comment by GrimZero** [comment]
> > When adding threejs as a dependency on a project and trying to build it (tested both locally and in azure) the tsc cannot resolve these 2 errors.
> 
> What version of TS are you using in your project?

Version number for tsc is 3.7.4, Angular CLI is 8.3.23, Node 10.16.0

**Comment by Mugen87** [comment]
Then it seems unrelated to the TS version since `three.js` has defined `3.7.4` as a package dependency, too.

**Comment by Mugen87** [comment]
Is it possible for you to reproduce these two errors with a small test repository? The problem does not appear when we are linting the project with `tsc`.

**Comment by GrimZero** [comment]
For local compilation I have removed the lines from the node module and that works just fine, but on azure it runs the install command and the modules are outside of my control while the pipeline compiles. This is not letting us compile the artifact and deploying to out application.

**Comment by Mugen87** [comment]
> I have removed the lines from the node module and that works just fine

Um, on what lines are you referring? 🤔

**Comment by GrimZero** [comment]
The exact lines that are causing the error. If they are removed (locally) it works.

**Comment by Mugen87** [comment]
> import { ShaderMaterialParameters } from './ShaderMaterial';

Where does this line comes from? Is it from app-level code?

**Comment by GrimZero** [comment]
https://github.com/mrdoob/three.js/blob/dev/src/materials/ShaderMaterial.d.ts

**Comment by Mugen87** [comment]
Probably this commit: eeebbaa6ff2c551eac9fa974cfc133e24cb819f7

But this is in production since `R110`.

**Comment by GrimZero** [comment]
Hmm the ECL3D library seems to be using `R108`. There is a possibility that this version is overriding the `R113`

**Comment by Mugen87** [comment]
Well, it seems this is no issue in the library...

**Comment by GrimZero** [comment]
Appears not, forums would probably have been a more appropriate place to re-raise the issue
