### ISSUE TITLE
Cannot update the texture

### ISSUE THREAD

**Issue by Momohanfeng** [mrdoob/three.js#18729]
##### Description of the problem
I want to change texture on a cube, but I cannot watch the texture update when I load the image and set the needsUpdate=true.
```
let geometry=new THREE.BoxGeometry(2,2,2)；
let material = new THREE.MeshBasicMaterial();
let cube =new THREE.Mesh(geometry,material);
scene.add(cube);
let loader = new THREE.TextureLoader();
loader.load(url, function(tex){
            material.map = tex;
            material.map.needsUpdate=true
}};
```

these code cannot update the texture on the cube, how to change the cube textures dynamically, thank you！

##### Three.js version

- [ ] Dev
- [x] r113
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

Tip: You can login with your github account.
