### ISSUE TITLE
orbitControls mouseDown prevent onBlur of elements inside dropdown

### ISSUE THREAD

**Issue by hphu3** [mrdoob/three.js#18733]
##### Description of the problem

DOM element's `onBlur` does not fire when a user clicks away from a dropdown and onto a THREE.js canvas with orbitControls in Safari/Firefox. This is due to the `onMouseDown` calling `event.preventDefault` here: https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/OrbitControls.js#L756

Here's a minimal reproduction:
* [jsfiddle](https://jsfiddle.net/k1syj3vn/2/) (latest release branch)
1. open the dropdown
2. click inside the text input
3. click onto the threejs canvas
4. observe onBlur alert not fired in Safari/Firefox, it is fired in Chrome.

##### Three.js version

- [ ] Dev
- [x] r113
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [x] Firefox
- [x] Safari
- [? ] Internet Explorer

##### OS

- [?] All of them
- [?] Windows
- [x] macOS
- [?] Linux
- [?] Android
- [?] iOS

**Comment by mrdoob** [comment]
```html
<script src="https://unpkg.com/three@0.85.0/examples/js/controls/OrbitControls.js"></script>
```

You're using r85 which is 3 years old. Please, report issues with the last version only.
