### ISSUE TITLE
Fringing with premultiplied alpha rendering

### ISSUE THREAD

**Issue by JordyvanDortmont** [mrdoob/three.js#18730]
##### Description of the problem

We encountered a possible bug with premultiplied alpha rendering when rendering transparent hair. The hair uses a diffuse PNG texture that is premultiplied and compressed with pngquant. Below is the result when rendering with Three.js in Chrome, Firefox and IE11. Notice the green color fringing through, found in areas that are normally made transparent by the alpha layer.

![green alpha fringing](https://user-images.githubusercontent.com/13318975/75249998-abcac800-57d7-11ea-9067-609c2c90809e.png)

@kornelski pointed us towards a possible solution in this issue: https://github.com/kornelski/pngquant/issues/353#issuecomment-590547775

So we tried the following possible solutions for blending:

```
material.premultipliedAlpha = true;
material.needsUpdate = true;
```

and manually:

```
material.blending = THREE.CustomBlending;
material.blendEquation = THREE.AddEquation;
material.blendSrc = THREE.OneFactor;
material.blendDst = THREE.OneMinusSrcAlphaFactor;
material.needsUpdate = true;
```

We also tried to set `premultiplyAlpha` to `true` on the texture in combination with the above, but then the result is too dark, although it has no green bleeding.

Compressed hair PNG:
![Classic_Taper_Diffuse](https://user-images.githubusercontent.com/13318975/75250133-f3e9ea80-57d7-11ea-8784-96ce43962bda.png)

##### Three.js version

- [?] Dev
- [x] r113
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [?] macOS
- [?] Linux
- [x] Android
- [?] iOS

**Comment by mrdoob** [comment]
Any chance you can provide a jsfiddle we can work with?

**Comment by JordyvanDortmont** [comment]
Sorry for not getting back to this issue earlier. We couldn't reproduce it with simple geometry for a jsfiddle and we still haven't found a way to fix this by adjusting the blending.

Nevertheless we have fixed the issue today by setting `texture.premultiply` to `true` in the `GLTFLoader` and adding the line `if (texelColor.a > 0.0) texelColor.rgb /= texelColor.a;` right after sampling the texture. This is basically what is stated in the epilogue of [this article](https://www.realtimerendering.com/blog/gpus-prefer-premultiplication/).

I don't know why this is necessary for non-IE11 browsers and why other fixes don't work. If you'd like I can close the issue for now.

**Comment by mrdoob** [comment]
Yes, lets close it for now.
