### ISSUE TITLE
WebGLRenderer.copyTextureToTexture() does not automatically generate mipmaps

### ISSUE THREAD

**Issue by frankolivier** [mrdoob/three.js#18736]
##### Description of the problem

WebGLRenderer.copyTextureToTexture() does not automatically generate new mipmaps (from the full size texture) when Texture.generateMipmaps == true) 

Repro steps:
Create a texture
Set .generateMipmaps = true
Copy a smaller texture to it with WebGLRenderer.copyTextureToTexture()
When the camera gets further away, the region of the texture you copied 'fades out' as the smaller (unchanged...) mipmap gets sampled.

See:
https://frankolivier.github.io/bugs/copyTextureToTexture-and-mipmaps/before/
(Notice how the green tile fades out)

Correct behavior:
https://frankolivier.github.io/bugs/copyTextureToTexture-and-mipmaps/after/

##### Three.js version

- [X] Dev
- [X] r113

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by mrdoob** [comment]
Thanks a lot for the example! Really helps to understand what the issue is.

**Comment by mrdoob** [comment]
Do you know if it's possible to copy mipmap by mipmap instead of having to generate them again?

**Comment by Mugen87** [comment]
> Do you know if it's possible to copy mipmap by mipmap instead of having to generate them again?

 Right now, the method is not designed to do this since it expects the mipmap level as a parameter.

To recap: `WebGLRenderer.copyTextureToTexture()` is just a thin layer over [WebGLRenderingContext.texSubImage2D()](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texSubImage2D). The `level` parameter is defined like so:

> A GLint specifying the level of detail. Level 0 is the base image level and level n is the nth mipmap reduction level. 

So if you want to copy mipmap by mipmap, you have to call `WebGLRenderer.copyTextureToTexture()` for each mipmap level. This is something app level code has to delegate.

**Comment by frankolivier** [comment]
The simple / default path for developers that don’t want think about mipmaps:

`// dstTexture.generateMipmaps = true;` (the default value)
`...`
`renderer.copyTextureToTexture(position, srcTexture, dstTexture);`
`// mipmaps are recreated on every call to .copyTextureToTexture()`

For developers that want to manage mipmaps themselves:

`dstTexture.generateMipmaps = false;`
`renderer.copyTextureToTexture(posA , textureA, dstTexture, levelA);`
`renderer.copyTextureToTexture(posB , textureB, dstTexture, levelB);`
`...`
`// No automatic mipmap generation`

If they want to return to  automatic mipmap generation:
`dstTexture.generateMipmaps = true;`
`// The next call to .copyTextureToTexture() will generate mipmaps from level 0`
`renderer.copyTextureToTexture(position , srcTexture, dstTexture /*, 0 */);`
