### ISSUE TITLE
canvastexture Tainted canvases may not be loaded.

### ISSUE THREAD

**Issue by caoshiwen** [mrdoob/three.js#18737]
##### Description of the problem
canvastexture.
![image](https://user-images.githubusercontent.com/20206516/75303054-98246d80-587a-11ea-8c50-9989b9fba5f0.png)

^0.113.2

**Comment by mrdoob** [comment]
https://stackoverflow.com/questions/30945945/tainted-canvases-may-not-be-loaded-cross-domain-issue-with-webgl-textures
