### ISSUE TITLE
Add warning logs to .mergeBufferGeometries() when method fails.

### ISSUE THREAD

**Issue by marquizzo** [mrdoob/three.js#18763]
When using `BufferGeometryUtils.mergeBufferGeometries()`, the method could fail silently without informing the user which part went wrong. See [in the source code](https://github.com/mrdoob/three.js/blob/master/examples/js/utils/BufferGeometryUtils.js#L178), there are many situations where the method defaults to `return null;`. However, with the granularity of the `if()` statements, we could be more specific about which step of the process failed by adding a `console.warn()` in each case.

In the example below, I'm merging geometries twice. In the first attempt I'm successfully merging a torus, box, and sphere. But in the second attempt, when I try to merge a torus, box, and an icosahedron, it returns `null` without explanation (I was later informed after asking in the forum that the icosahedron failed because it's not indexed).

```
const geom1 = new THREE.TorusBufferGeometry( 3, 1, 16, 100 );
const geom2 = new THREE.BoxBufferGeometry(5, 5, 5);
const geom3 = new THREE.SphereBufferGeometry(3, 32, 32);
const geom4 = new THREE.IcosahedronBufferGeometry(7, 0);

const geomA = THREE.BufferGeometryUtils.mergeBufferGeometries([geom1, geom2, geom3], false);
const geomB = THREE.BufferGeometryUtils.mergeBufferGeometries([geom1, geom2, geom4], false);
console.log("geomA: ", geomA); // <- this logs the merged geometry
console.log("geomB: ", geomB); // <- this logs null
```

Live link:
https://codepen.io/marquizzo/pen/jOPBRGv

##### Three.js version
- [x] r113

##### Browser
- [x] All of them

##### OS
- [x] All of them

**Comment by Mugen87** [comment]
More precise logging makes definitely sense. Do you want to a PR with your suggested changes?

**Comment by marquizzo** [comment]
@Mugen87 Sure! I could probably tackle this next week.
