### ISSUE TITLE
NodeMaterial: needsUpdate needs to be reset post-build

### ISSUE THREAD

**Issue by rclankhorst** [mrdoob/three.js#18772]
##### Description of the problem

When using a NodeMaterial, setting `needsUpdate` to `true` because of a change made to the material will not yield the expected result as it's not recompiled. The change related to #17968 produces this result, and when reverting [this blob in specific](https://github.com/mrdoob/three.js/pull/17968/commits/b521945d95d261f200c11c1c6ecf5fe8840eda46#diff-e7ff19643959b771a35742c5e98f7c5fL120), the material updates as expected. This issue is present from r111 and up, possibly relating to the fact that the `needsUpdate` flag is never reset to `false`.
In relation, [this proposed change by @sunag](https://github.com/mrdoob/three.js/issues/18347#issuecomment-572404500) (coming from #18347) seems to work as well:

```javascript
this.onBeforeCompile = function ( shader, renderer ) {
	var materialProperties = renderer.properties.get( this );

	if ( this.version !== materialProperties.__version ) {

		this.build( { renderer: renderer } );

		shader.uniforms = this.uniforms;
		shader.vertexShader = this.vertexShader;
		shader.fragmentShader = this.fragmentShader;

		this.needsCompile = false;
	}
};
```
##### Three.js version

- [x] Dev
- [x] r113
- [x] r112
- [x] r111
- [ ] r110

##### Browser

- [x] All of them

##### OS

- [x] All of them

Paging @sunag.

**Comment by Mugen87** [comment]
> In relation, this proposed change by @sunag (coming from #18347) seems to work as well:

@njarraud mentioned that this change would not work? Would you still be willing to make a PR?

**Comment by Mugen87** [comment]
In any event, it seems this issue is a duplicate of  #18347 so I guess it's better to close it and proceed the discussion there.

**Comment by rclankhorst** [comment]
I'm looking into making a PR, but I suppose you're right in proceeding in #18347.
