### ISSUE TITLE
Cube is sometimes clipped when using DataTexture3D

### ISSUE THREAD

**Issue by chabb** [mrdoob/three.js#18781]
##### Description of the problem
First, thanks for three.js, it's a really awesome piece of work.

I'm using DataTexture3D  [and this example](https://threejs.org/examples/webgl2_materials_texture3d.html) as a baseline 

I'm filling the texture array with 1, and I'm using a box geometry; the goal is to just render a cube to check if it works. I've changed the underlying shader to not use another texture for getting the color, but just the value provided in the DataTexture3D array.

The cube is correctly rendered, but is sometimes clipped, depending on the orientation of the camera ( try rotating the camera in the provided examples )

[see here ](https://stackblitz.com/edit/three-js-start-kxcpoa?file=index.ts)

Is it expected ( if yes, why ) or is it a bug ?  I suspect something is happening in the shaders code.

Thanks, 

##### Three.js version

0.113.2
##### Browser
- [X ] Chrome
##### OS
- [X ] macOS

**Comment by Mugen87** [comment]
> The cube is correctly rendered, but is sometimes clipped, depending on the orientation of the camera ( try rotating the camera in the provided examples )

Can you please demonstrate this issue with a live example?  https://jsfiddle.net/hyok6tvj/

**Comment by chabb** [comment]
@Mugen87 

https://stackblitz.com/edit/three-js-start-hpyq8e

**Comment by Mugen87** [comment]
Yeah, I can reproduce.

@artur-trzesiok Do you mind having a look at this issue?

**Comment by artur-trzesiok** [comment]
It's related to shader rather than DataTexture3D. 

change shader to

```
		// Decide how many steps to take
		"				int nsteps = int(-distance / relative_step_size + 0.5);",
		"				if ( nsteps < 1 ) {",
		"						gl_FragColor = vec4(1.0, 0.0, 1.0, 0.0);",
    "           return;",
    "       }",
```

And you will see that those nasteps <1 condition is resposible for that cutting.

**Comment by Mugen87** [comment]
@chabb Please use the [forum](https://discourse.threejs.org/) if you need more help with shader adjustments.

**Comment by checksummaster** [comment]
Any news about this problem? Or some discussion start somewhere to fix VolumeRenderShader1?
