### ISSUE TITLE
logarithmicDepthBuffer polygonoffset rendering issues

### ISSUE THREAD

**Issue by FishOrBear** [mrdoob/three.js#18807]
demo
Turn off logarithmicDepthBuffer and it will display fine.

* [jsfiddle](http://jsfiddle.net/jkc0dozL/1/) 

logarithmicDepthBuffer : false
![image](https://user-images.githubusercontent.com/19372111/75851828-9c75fb00-5e25-11ea-9f7c-7bb9fa87324e.png)

logarithmicDepthBuffer : true
![image](https://user-images.githubusercontent.com/19372111/75851815-941dc000-5e25-11ea-968b-ae4c1220849f.png)

##### Three.js version
- [ x ] r114

##### Browser

- [x] All of them
- [x] Chrome

##### OS

- [x] All of them
- [x] Windows10

**Comment by Mugen87** [comment]
I see no difference with Chrome 80.0.3987.132 on macOS 10.15.3.

**Comment by FishOrBear** [comment]
@Mugen87 
That may be a problem with Windowns. I have the same problem with both of my Windowns, both are NVIDIA graphics cards.

**Comment by Mugen87** [comment]
I'm afraid in this case there is nothing that the library can do. `three.js` only sets the polygon offset parameters directly to the WebGL state. So if the WebGL implementation of the driver are unable to correctly implement polygon offset, you have to file a bug elsewhere. For example here:

https://bugs.chromium.org/p/chromium/issues/list

**Comment by yaserOSource** [comment]
This is an issue now, so why close it?

**Comment by Mugen87** [comment]
@yaserOSource We close issues when it turn out the browser implementation is the root cause. As mentioned earlier it's better to file a bug at the browser vendor's bug tracker in such cases.
