### ISSUE TITLE
Material has stencilWrite but not stencilTest

### ISSUE THREAD

**Issue by khlorghaal** [mrdoob/three.js#18805]
stencil test and write should be separate from eachother, to be consistent with both the gl spec and how 3js handles depth test/write separately.

Currently stencil test is equal to material.stencilWrite, but **the documentation does not specify this**, which caused me significant troubleshooting time.

**Comment by WestLangley** [comment]
The OP is suggesting adding
```js
material.stencilTest
```
/ping @gkjohnson

**Comment by gkjohnson** [comment]
> to be consistent with both the gl spec

The material is consistent with the spec. The spec allows for [setting an integer mask](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/stencilMask) which allows you to write specific bits in the stencil buffer but there is no function for just enabling stencil testing and disabling writing other than that.

You can disable stencil writing by either setting `stencilWriteMask` to 0 or setting `stencilFail`, `stencilZFail`, and `stencilZPass` to `KeepStencilOp`, which they do by default. 

> how 3js handles depth test/write separately.

The materials `depthWrite` field maps to the [gl.depthMask function which takes a boolean](
https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLState.js#L99) so there is no real direct equivalent for stencils. We could fake it by enabling stencils if `stencilTest` is true and setting the mask to all 0 if `stencilWrite` is false but that doesn't reflect the way stencils work. I don't have strong opinions on it either way, though.

Updating the docs would make sense either way if you have suggestions on how to make it more clear.

**Comment by khlorghaal** [comment]
Helpful correction. Stencils can be quite confusing.
> You can disable stencil writing by either setting stencilWriteMask to 0 or setting stencilFail
