### ISSUE TITLE
webgl_camera_logarithmicdepthbuffer bug

### ISSUE THREAD

**Issue by FishOrBear** [mrdoob/three.js#18800]
The MeshBasicMaterial material seems to be causing this problem, I have not tested other materials.

**Comment by Mugen87** [comment]
I've have switched from `MeshPhongMaterial` to `MeshBasicMaterial` and everything looks as expected: https://jsfiddle.net/o7hxq4bj/1/

What do you mean with "causing this problem". Can you please be more specific and exactly describe the intended and expected outcome.

**Comment by FishOrBear** [comment]
I use an orthogonal camera and I have time to make a demo

**Comment by Mugen87** [comment]
Closing for now. Please open only issue if you can actually demonstrate an issue.

**Comment by FishOrBear** [comment]
@Mugen87 
https://discourse.threejs.org/t/using-webglrenderer-with-logarithmicdepthbufferset-option-set-to-true-together-with-shadermaterial/5051
May be this problem, this demo can no longer run
https://jsfiddle.net/f2Lommf5/16068/

**Comment by FishOrBear** [comment]
update: ```#include <common>``` seems to work afterwards, but there is another problem, I will solve it myself
