### ISSUE TITLE
'draco/gltf' in Vue

### ISSUE THREAD

**Issue by xyzgy** [mrdoob/three.js#18814]
i use 'draco/gltf' in Vue，but there is a Syntax error ,'Unexpected token '<';
![image](https://user-images.githubusercontent.com/21964169/75941493-d947fd80-5eca-11ea-95e4-18afacf1b112.png)

**Comment by donmccurdy** [comment]
Please use the forums for help with your code: https://discourse.threejs.org/. You will likely also need to include enough of your code and project setup for someone to reproduce the error you are seeing.
