### ISSUE TITLE
Feature request: ObjectControls

### ISSUE THREAD

**Issue by kmturley** [mrdoob/three.js#18815]
##### Feature request

OrbitControls were originally created to rotate a camera around a point in a scene:
<img width="400" alt="Screen Shot 2020-01-28 at 3 32 16 PM" src="https://user-images.githubusercontent.com/1710493/73314867-6cfb1f80-41e3-11ea-9e44-597ca914f2ba.png">
https://threejs.org/examples/#misc_controls_orbit

TransformControls were originally created for rotating individual objects within a scene:
<img width="400" alt="Screen Shot 2020-01-28 at 3 32 26 PM" src="https://user-images.githubusercontent.com/1710493/73314876-74222d80-41e3-11ea-93e0-fa89beb1b987.png">
https://threejs.org/examples/#misc_controls_transform

However in most examples and in web apps, we seem to be using OrbitControls to rotate objects? e.g.
https://threejs.org/examples/#webgl_materials_normalmap_object_space
https://threejs.org/examples/#webgl_clipping_intersection
https://threejs.org/examples/#webgl_clipping_stencil
https://threejs.org/examples/#webgl_decals
etc...

This usage creates confusion when you actually do want to rotate an object (and control the camera separately). In my case I needed the user to spin a globe, while the camera pans to a certain viewing angle.

Neither OrbitControls or TransformControls fully support the actual needed functionality needed for object spinning:
- OrbitControls locks your camera.lookAt to controls.target, and is spinning the camera not the object, which also spins the scenes.
- TransformControls correctly spins the object, but doesn't support damping / free spinning / hiding the gizmo gui.

So with that in mind, could we add an example for ObjectControls?

The controls implementation of Autodesk Forge viewer is probably a good benchmark:
https://forge-rcdb.autodesk.io/configurator?id=5904729b0007f5ead5b1196d

Some ideal features:
- Selecting an object
- Rotate object
- Lock axis
- Free spin in any direction
- Damping to slowly spin to a stop

Here is my attempt at a potential solution by using TransformControls as a reference:

index.html
```
control = new ObjectControls(camera, renderer.domElement);
control.enableDamping = true;
control.freeMode = true;
control.setMode('rotate');
control.showX = false;
control.showY = false;
control.showZ = false;
```

ObjectControls.js line 69
```
// Set to true to enable damping (inertia)
// If damping is enabled, you must call controls.update() in your animation loop
defineProperty( "enableDamping", false );
defineProperty( "dampingFactor", 0.05 );
defineProperty( "freeMode", false );
defineProperty( "rotateSpeed", 1.0 );
```

line 128:
```
var rotateStart = new Vector2();
var rotateEnd = new Vector2();
var rotateDelta = new Vector2();
```

line 255:
```
this.pointerHover = function ( pointer ) {
  if ( this.object === undefined || this.dragging === true || ( pointer.button !== undefined && pointer.button !== 0 ) ) return;
  if (this.freeMode === true) {
    this.axis = 'XYZE';
    return;
  }
  ray.setFromCamera( pointer, this.camera );
  var intersect = ray.intersectObjects( _gizmo.picker[ this.mode ].children, true )[ 0 ] || false;
  if ( intersect ) {
    this.axis = intersect.object.name;
  } else {
    this.axis = null;
  }
};
```

line 523:
`var ROTATION_SPEED = 2 / worldPosition.distanceTo( _tempVector.setFromMatrixPosition( this.camera.matrixWorld ) );`

line 724:
```
this.update = function () {
  if (this.dragging === false && scope.enableDamping && (Math.abs(rotateDelta.x) > 0.01 || Math.abs(rotateDelta.y) > 0.01)) {
    quaternionStart.copy( this.object.quaternion );
    offset = new Vector3(
      rotateDelta.x * 5,
      - rotateDelta.y * 5,
      0
    );
    rotateDelta.x *= 1 - scope.dampingFactor;
    rotateDelta.y *= 1 - scope.dampingFactor;
    var ROTATION_SPEED = .1 / worldPosition.distanceTo( _tempVector.setFromMatrixPosition( this.camera.matrixWorld ) );
    rotationAxis.copy( offset ).cross( eye ).normalize();
    rotationAngle = offset.dot( _tempVector.copy( rotationAxis ).cross( this.eye ) ) * ROTATION_SPEED;
    rotationAxis.applyQuaternion( parentQuaternionInv );
    this.object.quaternion.copy( _tempQuaternion.setFromAxisAngle( rotationAxis, rotationAngle ) );
    this.object.quaternion.multiply( quaternionStart ).normalize();
  }
};
```

line 644:
```
function onPointerDown( event ) {
  if ( ! scope.enabled ) return;
  rotateStart.set( event.clientX, event.clientY );
  document.addEventListener( "mousemove", onPointerMove, false );
  scope.pointerHover( getPointer( event ) );
  scope.pointerDown( getPointer( event ) );
}
function onPointerMove( event ) {
  if ( ! scope.enabled ) return;
  rotateEnd.set( event.clientX, event.clientY );
  rotateDelta.subVectors( rotateEnd, rotateStart ).multiplyScalar( scope.rotateSpeed );
  scope.pointerMove( getPointer( event ) );
  rotateStart.copy( rotateEnd );
}
```

line 1178:
```
if (this.freeMode === true) {
  this.gizmo[ "translate" ].visible = false;
  this.gizmo[ "rotate" ].visible = false;
  this.gizmo[ "scale" ].visible = false;

  this.helper[ "translate" ].visible = false;
  this.helper[ "rotate" ].visible = false;
  this.helper[ "scale" ].visible = false;
} else {
  this.gizmo[ "translate" ].visible = this.mode === "translate";
  this.gizmo[ "rotate" ].visible = this.mode === "rotate";
  this.gizmo[ "scale" ].visible = this.mode === "scale";

  this.helper[ "translate" ].visible = this.mode === "translate";
  this.helper[ "rotate" ].visible = this.mode === "rotate";
  this.helper[ "scale" ].visible = this.mode === "scale";
}
```

Live example:
* [jsfiddle](https://jsfiddle.net/kmturley/2p1v6bcw/20/)
* [Somone else's example](http://projects.defmech.com/ThreeJSObjectRotationWithQuaternion/)

##### Three.js version

- [x] Dev
- [x] r112

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

None

**Comment by JJGerrish** [comment]
I came across this after looking for a solution for the exact same problem - I have a globe that I want to be able to spin and orbit around but I have multiple different "scenes" where the camera position and `lookAt` changes.

The work you've done here looks great but just thought it was worth adding that having the ability to set the controls to `autoRotate` (being able to choose the speed independently from the `rotateSpeed` and stopping the auto rotation on click & hold) and also the ability to have the up vector be constant  like `OrbitControls` so that you can't "over-rotate" the object would be very useful, as well as maybe max/min polar/azimuth angles to further limit rotation like `OrbitControls` would be very useful as that would be closer to replicating `OrbitControls`.

I'm not skilled enough to implement any of that into your code so hopefully you or someone else can if you agree.

**Comment by looeee** [comment]
You can (almost) do this using OrbitControls:

Demo:
https://codepen.io/discoverthreejs/pen/eYNeRWY?editors=0010

The only problem is that the left/right rotation is swapped. Maybe there is some way to reverse these in the controls? 

It seems wasteful to create a whole new control type when OrbitControls basically does this anyway. 
There's nothing in the name "OrbitControls" that says it's a camera that has to be orbiting, in any case.
 
Maybe we could just update the controls to switch the left/right axes in the case when it's a normal object rather than a camera?

**Comment by Mugen87** [comment]
> It seems wasteful to create a whole new control type when OrbitControls basically does this anyway.

`ObjectControls` would be a bit more different to `OrbitControls` than one would think. For instance if you pan the camera, `ObjectControls` would still rotate the attached object around its center point.  `OrbitControls` instead translate its `target` and thus its focus point. Besides, similar to `TransformControls`, `ObjectControls` could orbit across the poles which  is not possible with `OrbitControls`.

I would rather consider to "evolve" `TransformControls` to some sort of `ObjectControls`.

**Comment by looeee** [comment]
> For instance if you pan the camera, ObjectControls would still rotate the attached object around its center point.

When you attach the controls to an object, they have nothing to do with camera panning. They are attached to the object, not the camera, and should continue to rotate the object around the control's target no matter where the camera is positioned. 

Currently, when you attach the orbit controls to an object (as in my example) panning simply doesn't work. If you need to "pan" (translate) the object as well then the controls would need more work than simple reversing the direction. 

> Besides, similar to TransformControls, ObjectControls could orbit across the poles which is not possible with OrbitControls.

This is a fair point. In that case ObjectControls woulds basically be TransformControls with the gizmo hidden I guess.

**Comment by kmturley** [comment]
As this functionality can be implemented in multiple ways, I opened two previous issues (related to modifying existing Controls) to support the functionality. See these closed feature requests:

Ability to set OrbitControls different camera.lookAt vs controls.target
https://github.com/mrdoob/three.js/issues/18476

TransformControls enable Damping / hide gui / free spin
https://github.com/mrdoob/three.js/issues/18503

Both were considered to be adding complexity to common functionality, so we agree that creating a new set of ObjectControls would probably make more sense

**Comment by systemsincode** [comment]
This would be awesome to see as I agree this is a pretty common set of use cases imho..

**Comment by Fluqz** [comment]
I also need this functionality in my projects!

**Comment by Mugen87** [comment]
For all users who are looking for a solution, there is now [SpinControls](https://github.com/paulhax/spin-controls).

Since this project is already maintained at GitHub, it's not required to include the controls to the `three.js` repository. Please post feature requests or bugs at the above repo.

**Comment by badde-media** [comment]
For the sake of completeness, I've just found this one, which also supports multiple objects to be rotated with the same control, the list of the affected objects to be manipulated, and some other options:
https://github.com/albertopiras/threeJS-object-controls

**Comment by octan123** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
