### ISSUE TITLE
BufferGeometry applyMatrix4 fails for flipping z

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#18828]
##### Description of the problem

Make a 2d geometry like plane or circle, its normals face in one direction, try to flip the direction by applying a -1 scale.

In other words

```
geo = new THREE.CircleBufferGeometry();
```

makes a circle with normals facing +Z so

```
geo = new THREE.CircleBufferGeometry();
geo.applyMatrix4(new THREE.Matrix4().makeScale(1, 1, -1));
```

should make the normals face -Z

The issue seems to be the inverse function returning negative zeros though I didn't look deep into it.

* [jsfiddle](https://jsfiddle.net/greggman/2maru50L/)
##### Three.js version

- [x] Dev
- [x] r114
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
You can find an answer in this thread:

https://stackoverflow.com/questions/16824650/three-js-how-to-flip-normals-after-negative-scale

By using the suggested code at the end of the thread, the result is: https://jsfiddle.net/wr39m16n/2/

**Comment by Mugen87** [comment]
Related: #18683, #17361.

**Comment by OndrejSpanel** [comment]
I remember solving other issue with mirroring (negative scale in one axis): #15825. I think mirroring is useful and should be supported unless the support burden is too high.
