### ISSUE TITLE
WebGLRenderer.copyTextureToTexture() does not support compressed textures

### ISSUE THREAD

**Issue by frankolivier** [mrdoob/three.js#18821]
##### Description of the problem

`WebGLRenderer.copyTextureToTexture()` does not support compressed textures

When using regular PNGs, I can use `WebGLRenderer.copyTextureToTexture()` to add a green tile to the face of a rotating cube:
https://frankolivier.github.io/bugs/copyTextureToTexture-and-compressed-textures/png/

When using (Basis) compressed textures, it does not work:
https://frankolivier.github.io/bugs/copyTextureToTexture-and-compressed-textures/basis-broken
(Observe: no green tile)

The fix is to add 

`if ( srcTexture.isCompressedTexture ) {`
`_gl.compressedTexSubImage2D( 3553, level, position.x, position.y, srcTexture.mipmaps[0].width, srcTexture.mipmaps[0].height, glFormat, srcTexture.mipmaps[0].data );`
`}`

...to `.copyTextureToTexture()`

See a fixed example in https://frankolivier.github.io/bugs/copyTextureToTexture-and-compressed-textures/basis-fixed/

##### Three.js version

- [x] Dev
- [x] r114
- [ ] ...

##### Browser
- [x] All of them

##### OS
- [x] All of them

##### Hardware Requirements
Any

**Comment by Mugen87** [comment]
Feel free to make a PR with the fix.
