### ISSUE TITLE
3MFLoader not easily use

### ISSUE THREAD

**Issue by zfavourite99** [mrdoob/three.js#18838]
##### 3MFLoader dependency DOMParser

3MFLoader can not use in some environment which has no dom environment.

I try to use [xmldom](https://github.com/jindw/xmldom). but xmldom have no querySelector method.

That is depressing. 😞

**Comment by Mugen87** [comment]
Similar to `ColladaLoader`, `3MFLoader` depends on `DOMParser` which is not available e.g. in a node environment. However, this is not the only browser dependency. `3MFLoader` also relies on `Blob` and the `URL` interface. 

In general, `three.js` does not ensure that its loaders can be used in any possible JS environment. The browser (or more precisely the web platform) is the primary target platform.  If you want to use the loader elsewhere, you have to make the necessary changes by yourself.

**Comment by Floppy** [comment]
For anyone looking for this in future, I've taken @coder-free's suggestion, combined with another comment on from @morrisallison on xmldom that fixes querySelector, and created a worker-compatible fork of the 3MF loader, which anyone can pull in easily to replace the normal one:

https://github.com/manyfold3d/threejs-webworker-3mf-loader
