### ISSUE TITLE
scene.environment set to anything other than PMREMGenerator output is unuseable - bug or feature?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#18840]
for example,
```
var envMap = new THREE.Texture( whatever );
envMap.mapping = THREE.EquirectangularReflectionMapping;
envMap.needsUpdate = true;
scene.environment = envMap;
```
will creaate ridiculously dark scene, while running same texture through PMREMGenerator performs as expected.

**Comment by makc** [comment]
Relevant [forum thread](https://discourse.threejs.org/t/hdr-environment-map-doesnt-work-unless-i-convert-it-to-a-pmrem/13378) by @looeee with the codes

**Comment by looeee** [comment]
> Relevant forum thread by @looeee with the codes

I'll copy the text from my post here:

MeshStandardMaterial doesn't work with a HDR equirectangular environment map unless I convert it to a PMREM. 

Not sure if this ever worked, but I feel like I would have noticed before if it was not possible. 

Here's a pen that demonstrates what I mean:

https://codepen.io/discoverthreejs/pen/QWbaLVa?editors=0010

This fails:

``` js
const envMap = await loadEnvironment();
scene.environment = envMap;
```

![1](https://user-images.githubusercontent.com/5307958/76195795-acbe1980-621b-11ea-868d-e0f58016a786.png)

This works:

``` js
const envMap = await loadEnvironment();
const envMapPMREM = createPMREM(pmremGenerator, envMap);
scene.environment = envMapPMREM;
```

![2](https://user-images.githubusercontent.com/5307958/76195800-af207380-621b-11ea-90dc-471b46deb504.png)

Is it required to use PMREM with MeshStandardMaterial now? I know it's required for correct results, but I'm sure it used to at least work previously. 
Or perhaps I need to change some settings on the loaded texture?

**Comment by Mugen87** [comment]
It's already noted in the [docs](https://threejs.org/docs/index.html#api/en/materials/MeshStandardMaterial.envMap) that you can only use an env map in cube map format with `MeshStandardMaterial`:

> Note: only cube environment maps are supported for MeshStandardMaterial. If you want to use an equirectangular map you will need to use WebGLCubeRenderTarget.fromEquirectangularTexture().

**Comment by looeee** [comment]
Ah, that was it. Thanks 😄

**Comment by makc** [comment]
So, feature then.
