### ISSUE TITLE
skeleton boneTexture won't dispose?

### ISSUE THREAD

**Issue by cjsjy123** [mrdoob/three.js#18844]
when support floatVertexTextures and enable skinning ,it will create DataTexture in the webglrender,but i dont find any place to release it

**Comment by WestLangley** [comment]
Do you mean this?
```js
skinnedMesh.skeleton.boneTexture.dispose();
```

**Comment by cjsjy123** [comment]
、

> Do you mean this?
> 
> ```js
> skinnedMesh.skeleton.boneTexture.dispose();
> ```

yes. But shouldn't it be to add a function dispose in skeleton? Instead of such special release, it should be consistent with other objects

**Comment by Mugen87** [comment]
Yeah, adding `Skeleton.dispose()` makes indeed sense 👍 .

**Comment by Mugen87** [comment]
@cjsjy123 Do you want to make a PR and add `Skeleton.dispose()`?

**Comment by cjsjy123** [comment]
@Mugen87 of course
