### ISSUE TITLE
Update or remove LGTM badge?

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#18845]
![Screen Shot 2020-03-08 at 8 52 14 PM](https://user-images.githubusercontent.com/1848368/76181542-b2195680-617e-11ea-8b3c-25d50e6f9cf4.png)

^The 202 alerts are useful, and it'd be great if someone wanted to fix them, but I'm not sure the project readme is the right place to discover such issues. Do we want to use the [version of the badge showing code quality](https://lgtm.com/help/lgtm/adding-badges-to-project-readme-files) instead, or remove it?

**Comment by makc** [comment]
you mean sweep under the carpet badge version 😉 fwiw, I have fixed [a couple of them](https://github.com/mrdoob/three.js/pull/18786) last week.

![doing my part](https://media.tenor.com/images/4719d1698f8da4f000ed0ce109703e74/tenor.gif)

**Comment by donmccurdy** [comment]
Glad they're being fixed! But still, think the code quality rating would be better than an exact number of linter errors, especially when lgtm.com cannot differentiate examples/js and src/.

**Comment by Mugen87** [comment]
The other problem with lgtm is explained here: https://github.com/mrdoob/three.js/pull/14681#issuecomment-545837402. It lists a lot of Python errors although the code was removed years ago.

Originally, the badge did not show the amount of lgtm errors but the general language grade ( e.g. `A`, `B` etc.). It seems this kind of badge is now available anymore.

**Comment by Mugen87** [comment]
How about using this one: [![Language grade: JavaScript](https://img.shields.io/lgtm/grade/javascript/g/mrdoob/three.js.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/mrdoob/three.js/context:javascript)

**Comment by mrdoob** [comment]
The badge used to be in code quality mode, I changed it recently because I thought showing the number of warnings would be a way for people to discover "little fixes" they can help with.

> you mean sweep under the carpet badge version 😉 fwiw, I have fixed [a couple of them](https://github.com/mrdoob/three.js/pull/18786) last week.

I guess it worked?

**Comment by donmccurdy** [comment]
Huh, ok! If it's intentional, and we think there's a good chance of actually bring the number to zero, that sounds good. Maybe we switch it for the "code quality: A+" version once there are no bugs left to fix. 😇

**Comment by Mugen87** [comment]
> and we think there's a good chance of actually bring the number to zero,

The current 202 consist of 140 JavaScript and 62 Python alerts. As long as the mentioned issue with Python is not fixed, the project will never achieve zero alerts.

Unfortunately, it seems the maintainers of lgtm.com do not really care about this issue.

**Comment by gkjohnson** [comment]
> The current 202 alerts consist of 140 JavaScript and 62 Python alerts. As long as the mentioned problem with Python is not fixed, the project will never achieve zero alerts.
>
> Unfortunately, it seems the maintainers of lgtm.com do not really care about this issue.

Have you tried contacting LGTM about it? It's a little discouraging knowing there's no way to hit 0 at the moment!

**Comment by Mugen87** [comment]
> Have you tried contacting LGTM about it? 

see https://github.com/mrdoob/three.js/pull/14681#issuecomment-411781576

**Comment by donmccurdy** [comment]
Down to 140, no Python errors, maybe new badge is good. 😬

![Screen Shot 2020-03-22 at 9 19 20 PM](https://user-images.githubusercontent.com/1848368/77280898-dac34500-6c82-11ea-812e-d5d99f30e7c5.png)

**Comment by gkjohnson** [comment]
Did anyone do anything to remove the python errors or did LGTM just resolve itself behind the scenes? I'm seeing a similar issue of delayed LGTM updates on another project.

**Comment by mrdoob** [comment]
@gkjohnson https://github.com/mrdoob/three.js/pull/14681#issuecomment-601991674
