### ISSUE TITLE
GLB + Displacement Map = bug ?

### ISSUE THREAD

**Issue by Thomas-6freedom** [mrdoob/three.js#18857]
##### Description of the problem

In the editor, exporting then importing an object as GLB with a Displacement Map, does not keep the displacement map.

Describe the bug or feature request in detail.

Steps to reproduce :

1.  Download the [Ninja OBJ and its 3 textures](https://github.com/mrdoob/three.js/tree/master/examples/models/obj/ninja).
2. Open the [Three.JS Editor ](https://threejs.org/editor/)
3. Import the Ninja model and its 3 textures

![image](https://user-images.githubusercontent.com/49686866/76320537-1e13d000-62e1-11ea-8a2d-d07d63d90abe.png)

4. Export as GLB

5. In threeJS editor : File => New

6. In ThreeJS editor : File => Import

7. Import the GLB of the ninja you created at Step 4

Current Behavior : 
There is no Displacement map.
![image](https://user-images.githubusercontent.com/49686866/76320846-82369400-62e1-11ea-9128-5746a89ade2e.png)

Expected Behavior :
The displacement map is kept

**Comment by Mugen87** [comment]
`glTF` does not support displacement maps yet. However, there is:

https://github.com/KhronosGroup/glTF/issues/948

**Comment by donmccurdy** [comment]
That's the proposal, yes. Unless/until it is added, displacement maps cannot be exported to glTF.
