### ISSUE TITLE
AnimationMixer does not accept AnimationObjectGroup

### ISSUE THREAD

**Issue by Longi94** [mrdoob/three.js#18851]
##### Description of the problem

Due to #17870, AnimationMixer does not accept AnimationObjectGroup anymore. Producing a ` Argument of type 'AnimationObjectGroup' is not assignable to parameter of type 'Object3D'.` error with typescript.

##### Three.js version

- [x] Dev
- [x] r114

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Good catch! Would you like to make a PR with the fix?

**Comment by Longi94** [comment]
Sure.
