### ISSUE TITLE
Drawing Text Around Meshes and Moving Objects in the Scene

### ISSUE THREAD

**Issue by bmd0031** [mrdoob/three.js#1885]
I would like to add a label to a round meshed sphere that floats above the surface of the sphere. When the scene is manipulated and the spheres rotated, the text needs to stay facing the user while the mesh and scene rotate respectively. 

I have also tried to make each mesh object draggable, but it's not working and I'm only getting 'undefined' from the console when printing INTERSECTED and SELECTED.

If you could help me learn ways to enter labels that would be great. The JS Fiddle here, http://jsfiddle.net/bmd0031/AjTJZ/4/

Brent

**Comment by dubejf** [comment]
There are many examples for using sprites:
http://stemkoski.github.io/Three.js/Labeled-Geometry.html
http://threejs.org/examples/#webgl_sprites
