### ISSUE TITLE
EXRLoader Limited map size 

### ISSUE THREAD

**Issue by threethreenine** [mrdoob/three.js#18878]
##### Description of the problem

I baked the scene in Unity and showed it in three.js, and loaded the lightmap in .exr format in three.js. As a result, the exr map of 512 * 512 pixels and below were displayed normally, and the map of 1024 * 1024 pixels and above were displayed normally. Display with red, green and blue noise. for example:

1 exr maps baked by Unity to use as a lightmap，size 1024*1024
![image](https://user-images.githubusercontent.com/23252535/76506800-b5feee80-6486-11ea-869b-94ddb7c8736b.png)

1 exr maps baked by Unity to use as a lightmap for the model, size 1024*1024
![image](https://user-images.githubusercontent.com/23252535/76508923-1fccc780-648a-11ea-8915-d21f5f979e24.png)

4 exr maps baked by Unity to use as a lightmap for the model, size 512*512
![image](https://user-images.githubusercontent.com/23252535/76518153-932a0580-6499-11ea-8d56-4026120471a0.png)

##### Three.js version

- [ ] Dev
- [x] r113
- [ ] ...

##### Browser

- [x ] Chrome

##### OS

- [x ] Windows

##### Hardware Requirements (graphics card, VR Device, ...)
NVIDIA GeForce GTX 1060 5GB;
Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz

**Comment by sciecode** [comment]
@threethreenine Thank you for letting us know about the problem.

Is it possible to share the .exr file in question? 
Also, report the values inside `TextureData.header`, please.

```js
new EXRLoader()
    .load( 'textures/file.exr', function ( texture, textureData ) {

	console.log( textureData.header )

    } );

```

**Comment by threethreenine** [comment]
@sciecode If possible, please give me an email address and I will send the documents to this email.
I screenshot the value of` textureData.header`as follows
![image](https://user-images.githubusercontent.com/23252535/76582669-e5a70880-6511-11ea-9248-6c8be3470f6e.png)

**Comment by sciecode** [comment]
Sent you an email, to which you can reply with the file.
Nothing stands out in the header info, so I'm guessing this is yet another bug with PIZ compression.

**Comment by threethreenine** [comment]
@sciecode  I have shared files on Google Cloud, here is the link https://drive.google.com/file/d/12yK5C-4k2a7Ah9v1C-xciaCZFzdhTDNN

**Comment by sciecode** [comment]
Yes, the issue is indeed related with the compression algorithm used internally.

It might take a while to debug exactly the cause, but I've saved the file using a different compression that works correctly. You might want to use that while I try to find the cause of the bug. 

[baked_lightmap.zip](https://github.com/mrdoob/three.js/files/4327548/baked_lightmap.zip)

If unity allows control over the internal compression for the .exr file, prefer using ZIP or DWA in the meanwhile.

**Comment by threethreenine** [comment]
@sciecode Thanks for your help and suggestions. I will try to replace the compression method of .exr files in Unity.
Or save the .exr file generated in Unity again using image processing software similar to Photoshop, I think you should use Photoshop to help me change its compression method.

**Comment by sciecode** [comment]
Just filed a PR to solve this issue, would appreciate if you could test it @threethreenine.

**Comment by threethreenine** [comment]
@sciecode  I have tested it, the effect is normal;
![image](https://user-images.githubusercontent.com/23252535/83369180-0df62300-a3ee-11ea-871a-5c787f5f25d2.png)
