### ISSUE TITLE
Transform Controls lose interaction after layer change

### ISSUE THREAD

**Issue by notchris** [mrdoob/three.js#18870]
##### Description of the problem

When changing the layer (default: 0) of Transform Controls, they lose their interaction (mouse events etc). They still render correctly with camera changes.

Expected: Control layer to update and maintain interaction.

* [jsfiddle](https://jsfiddle.net/notchris/fy9h64js/)

##### Three.js version

- 0.114.0

##### Browser

- [x] All of them
- [] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/pull/11312#issuecomment-597796298.
