### ISSUE TITLE
Squeeze events not fired for HTC Vive

### ISSUE THREAD

**Issue by Longi94** [mrdoob/three.js#18873]
##### Description of the problem

`squeeze`, `squeezestart` and `squeezeend` events do not get fired in VR when using the HTC Vive. In the example below nothing happens when squeezing the controller. Breakpoints are not reached in the handler. Select events (trigger button) work fine. Manually getting the `Gamepad` object also works fine as the `pressed` property of the buttons are correctly set.

https://threejs.org/examples/webxr_vr_paint.html

##### Three.js version

- [ ] Dev
- [x] r114
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

HTC Vive

**Comment by avaer** [comment]
Also not fired on Index.

**Comment by Mugen87** [comment]
I've tested today the example with Oculus Quest and the `squeezestart` and `squeezeend` events fire as expected. I can use them to scale the painter as intended.

When input devices do not fire specific events (or if there are tracking related problems), it is usually best to file a bug at the respective browser vendor. 

When using the Chromium bug tracker, select the component [Blink>WebXR>VR](https://bugs.chromium.org/p/chromium/issues/list?q=component%3ABlink%3EWebXR%3EVR&can=2) when authoring the meta tags of the issue.
