### ISSUE TITLE
STLLoader Giving "errorRangeError: Invalid typed array length: 17576829549" Reading Wrong Number of Faces

### ISSUE THREAD

**Issue by polishdude20** [mrdoob/three.js#18889]
I've got an STL file with 4811 faces but STLLoader.js is detecting 1818587680 faces.
It says 1818587680 faces no matter which STL file I choose.

I see in STLLoader.js, it detects the file is in binary format and it looks at offset 80 here:

```
  function parseBinary(data) {
      var reader = new DataView(data);
      var faces = reader.getUint32(80, true);
```

I'm using three and STLLoader in React. 
I'm importing the modules STLLoader needs using:

```
import {
  BufferAttribute,
  BufferGeometry,
  FileLoader,
  Float32BufferAttribute,
  Loader,
  LoaderUtils,
  Vector3
} from "three";
```
I installed three using "yarn add three"

**Comment by mrdoob** [comment]
How about sharing the STL file?

**Comment by polishdude20** [comment]
Sorry!
Here it is :)
https://drive.google.com/file/d/1UJltCvyxs4qHKDmsjgJjaSshSgsfWyYU/view?usp=sharing

**Comment by WestLangley** [comment]
The model seems to load fine for me using the code in the three.js example.  r.115dev

![Screen Shot 2020-03-12 at 10 12 43 PM](https://user-images.githubusercontent.com/1000017/76583127-c32fd380-64ae-11ea-9a9c-cd58793c587a.png)

**Comment by polishdude20** [comment]
I've got the loader being called in a promise:

```
const loader = new THREE.STLLoader();
  //16367289120
  console.log("Loading Geometry");
  const loadTopArm = () =>
    new Promise(resolve => {
      console.log("Loading TopArm");
      loader.load(
        "./wheel.stl",
        resolve,
        () => console.log("progress"),
        err => console.log("error" + err)
      );
    });
  const promises = [loadTopArm()];
```

Not sure if the way react bundles things is causing this problem though? I'm using the STLLoader jsm file.

**Comment by WestLangley** [comment]
If you need help, you can try the three.js [forum](https://discourse.threejs.org).

**Comment by makc** [comment]
> It says 1818587680 faces no matter which STL file I choose.

![lolz](https://user-images.githubusercontent.com/242577/76585040-a3fc6a80-64dd-11ea-9d49-bb83fbfdc518.png)

maybe it is an error message saying you need to add the file type hand**LER** or something

**Comment by polishdude20** [comment]
Alright thanks :)
