### ISSUE TITLE
Vive Tracker not detected

### ISSUE THREAD

**Issue by KennyBarraud** [mrdoob/three.js#18883]
Hello all,

I'm currently facing the next problem : I'm  developing a project on Windows 10 - Chrome 80 with THREE JS 113. Web XR is working fine with my HTC Vive and the Vive controllers are well detected.

However when I pair one of my Vive Tracker, there seems to be some trouble. Indeed, the event 'inputsourceschange' is not triggered, therefore my Vive Tracker is not moving in the simulation.

As I was testing it on the vr paint example, I noticed that sometimes I have an error on the session, and when I click again on the VRButton the tracker is detected.

Do you have any ideas on why the 'inputsourceschange' is not triggered ? Do I need to enable another flag on Chrome ? I'll try to get the exact message of the session error.

**Comment by Mugen87** [comment]
Do you have the same issues with other WebXR demos which are not using  `three.js`? E.g.:

https://immersive-web.github.io/webxr-samples/input-tracking.html
https://immersive-web.github.io/webxr-samples/input-selection.html

**Comment by KennyBarraud** [comment]
Yes I have the same issues on those examples.

**Comment by Mugen87** [comment]
In this case I suggest you file an issue at the Chromium bug tracker.

Select the component [Blink>WebXR>VR](https://bugs.chromium.org/p/chromium/issues/list?q=component%3ABlink%3EWebXR%3EVR&can=2) when authoring the meta data of the issue.
