### ISSUE TITLE
Partial animation loaded from glb

### ISSUE THREAD

**Issue by Flip535** [mrdoob/three.js#18884]
the following glb model from sketch fab seems to have missing parts of an animation when loaded with the GLTFLoader

Model:
https://sketchfab.com/3d-models/3d-printable-air-balloon-engine-for-lego-1879711af3664ef7bc150f90139e8d2a

Download and try it out on https://gltf-viewer.donmccurdy.com/
Compare the animation to whats on sketch fab. Notice that there are two pieces that are stationary that are supposed to pop out with threejs

Seems to work correctly on babylon https://sandbox.babylonjs.com/

##### Three.js version

- [ ] Dev
- [ x] r114
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
See https://github.com/mrdoob/three.js/issues/15087 — this model contains multiple nodes with the same name, which isn't necessarily bad, but our animation system relies on unique names for animation to play back correctly.

Proposed fix in https://github.com/mrdoob/three.js/pull/16639, which has stalled.
