### ISSUE TITLE
where extensions for materials are not included in the list of all model extensions.

### ISSUE THREAD

**Issue by tnormandao** [mrdoob/three.js#18880]
https://github.com/mrdoob/three.js/blob/e3d60b17c0497a08ecb166eae799eb5cf6d9e7f5/examples/jsm/loaders/GLTFLoader.js#L222

    if( json.materials ){
      for( const nextMaterial of json.materials ){
        if( nextMaterial.extensions ){
          for( const nextExtensionKey in nextMaterial.extensions ){
            if( json.extensionsUsed.indexOf( nextExtensionKey ) === -1 ){
              json.extensionsUsed.push( nextExtensionKey );
            }
          }
        }
      }
    }

In my case, additional parsing of materials helped to avoid errors in case they have extensions that are not considered in the general list.

**Comment by donmccurdy** [comment]
@tnormandao if an extension is used in a material but not included in `json.extensionsUsed`, then it's an invalid glTF file and we cannot support it here. See [glTF • Specifying Extensions](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#specifying-extensions):

> All extensions used in a glTF asset must be listed in the top-level extensionsUsed array...

You can also check your models using the [glTF validator](https://github.com/KhronosGroup/glTF-Validator).
