### ISSUE TITLE
Reflector: Clipping when using Scene.background.

### ISSUE THREAD

**Issue by visus100** [mrdoob/three.js#18897]
##### Description of the problem
Hi, 
according to @Mugen87 request of demonstrating issue (clipping mesh when distance beetween reflector and object is over 75 units [sometimes its more please experiment] when hdri background is on) at [stackoverflow post](https://stackoverflow.com/questions/60664343/three-js-reflector-mirror-clipping-object-when-hdri-background-is-set?noredirect=1#comment107342216_60664343) for live example i prepared one on [codesandbox](https://codesandbox.io/s/kind-greider-f1zrm). I created with react, hope it's not the problem.

For change mirror distance line - 51
``` verticalMirror.position.y = -130; ```

For disable hdri background line- 94
```scene.background = envMap;```

image preview for issue:
![clipping box](https://user-images.githubusercontent.com/22850382/76677753-40079e00-65d2-11ea-9c64-080922cf9c06.jpg)

**Also i notticed that there is one more problem with reflector**
when setting otputEncoding there is really big fps drop (i dont know its only on my machine please compare that also) i included this as a commented "feature" in the same codesandbox

**I noticed the same behavior on**  [Water2.js example](https://threejs.org/examples/?q=water#webgl_water) **propably based on same reflection scripts**

line- 86
```this.renderer.outputEncoding = THREE.sRGBEncoding;```

##### Three.js version

- [x] r114

##### Browser

- [x] All of them

**Comment by visus100** [comment]
Ok topic about encoding: THREE.sRGBEncoding  [18893](https://github.com/mrdoob/three.js/issues/18893) so please ignore this part of post.

**Comment by Mugen87** [comment]
This issues is unrelated to HDR backgrounds. It happens even with LDR env maps. However, the issue can be easily fixed by setting `renderOrder` to `1` for the reflector: 

https://jsfiddle.net/k8L167z5/1/

There was a similar issue in the past, see #14006.

**Comment by visus100** [comment]
Thans. this helps
