### ISSUE TITLE
Error with Three.js in camera.lookAt method

### ISSUE THREAD

**Issue by davidmartinezros** [mrdoob/three.js#18900]
##### Description of the problem

In the last changes done, Three.js is generating errors. In particular, the method camera.lookAt is not a function ERROR.

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/hyok6tvj/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/c5m1kazu/) (dev branch)

##### Three.js version

- [ ] Dev
- [ ] r114
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> In the last changes done, Three.js is generating errors. In particular, the method camera.lookAt is not a function ERROR.

Can you please demonstrate the issue with a live example? According to the examples, `lookAt()` seems to work fine.

**Comment by davidmartinezros** [comment]
You can find the component : https://www.npmjs.com/package/app3d-three-template

And the demo: https://next.plnkr.co/edit/B1IDXBOaY8OvFYQI?preview

**Comment by Mugen87** [comment]
The runtime error happens at this line in `MyRenderService.createObjects()`: 
```js
camera.lookAt(0,0,0);
```
When debugging, it shows that the variable `camera` is an instance of `WebGLRenderer`. Probably because you are doing this: 
```js
 this.renderService.createObjects(this.scene, this.renderer, this.camera, this.light);
```
`MyRenderService.createObjects()` only has three parameters, not four.

Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need more help.

**Comment by davidmartinezros** [comment]
Eiii,

Very thanksss!!

Now works fine...

https://plnkr.co/edit/B1IDXBOaY8OvFYQI?preview

See you,

David
