### ISSUE TITLE
LineSegments geometry groups not work

### ISSUE THREAD

**Issue by 1147079942** [mrdoob/three.js#18909]
##### Description of the problem

LineSegments geometry groups not work.
If clear the geometry's groups, the LineSegments still can render

##### Three.js version

- [ ] Dev
- [ ] r114
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> If clear the geometry's groups, the LineSegments still can render

That is the expected behavior. If no group are present, the entire geometry is rendered.

**Comment by 1147079942** [comment]
I see,if use the material array, the groups will work like i think
