### ISSUE TITLE
BufferGeometry.merge or BufferGeometryUtils.mergeBufferGeometries: Add support for transformation matrix

### ISSUE THREAD

**Issue by finnbear** [mrdoob/three.js#18918]
##### Summary of feature request

`.addScaledVector` but instead of *adding* a *scaled* *vector*, *merging* a *transformed* *BufferGeometry*

##### Description of feature request

For optimization purposes, I want to render a single buffer geometry instead of rendering each object in my scene separately

```javascript
const geometry = THREE.BufferGeometryUtils.mergeBufferGeometries(this.children.map(child =>
    child.geometry.clone().applyMatrix4(child.matrix) // The issue
));
this.add(new THREE.Mesh(geometry, this.children[0].material));
for (const child of this.children) {
     child.visible = false;
}
```
(simplified code, not tested but should convey my point)

Unfortunately, the existing buffer geometry merge methods don't support transforming each merged vertex by a custom matrix. That means I have to clone each child's geometry and apply the matrix to the entire clone at once.

This is a waste of memory, and could be avoided with
- `BufferGeometry.merge(bufferGeometry, optionalMatrix)`
- `BufferGeometryUtils.mergeBufferGeometries(bufferGeometries, optionalMatrices)`

The 2nd option is slightly more awkward but is preferred because BufferGeometryUtils is lossless (doesn't require manual index argument)

If a matrix is passed in, each vertex being merged in should have it applied.

Note: I know I could get around this by pre-applyMatrix4-ing all my objects' geometries, but I don't want to do that...I want them to share a single, applyMatrix4'd buffer geometry instance.

Note 2: For my use case, each child's BufferGeometry is the same. A solution specific to my case is :
- `BufferGeometryUtils.stamp(bufferGeometry, matrices)`

Which would take a single geometry and stamp it at multiple locations/rotations/scales defined by each matrix.

##### Three.js version

- [ ] Dev
- [x] r114

**Comment by gkjohnson** [comment]
> `BufferGeometry.merge(bufferGeometry, optionalMatrix)`

Can you explain how this function signature would work?

> BufferGeometryUtils is lossless (doesn't require manual index argument)

What do you mean by this?

> Note 2: For my use case, each child's BufferGeometry is the same. A solution specific to my case is :
> ...
> Which would take a single geometry and stamp it at multiple locations/rotations/scales defined by each matrix.

It seems like [InstancedMesh](https://threejs.org/docs/#api/en/objects/InstancedMesh) is much better suited for your use case, then, and will use significantly less memory than merging a bunch of geometries.

**Comment by donmccurdy** [comment]
> What do you mean by this?

`bufferGeometry1.merge(bufferGeometry2)` overwrites data rather than doing a union. This is rarely what users want.

> That means I have to clone each child's geometry and apply the matrix to the entire clone at once. ... This is a waste of memory ...

I'm not sure how we'd implement it _in_ BufferGeometryUtils any other way, without duplicating a fair bit of code from:

- `BufferGeometry.prototype.applyMatrix4`
- `BufferAttribute.prototype.applyMatrix4`
- `BufferAttribute.prototype.applyNormalMatrix`
- `BufferAttribute.prototype.transformDirection`

I agree with @gkjohnson that InstancedMesh may be a better fit for this use case.

**Comment by finnbear** [comment]
@gkjohnson thanks for the reply
@donmccurdy you're right, that's what I meant by the first thing

As for using an instanced mesh, I think that would be very wasteful for my usecase. Each child object is simply a plane (4 vertices). While I haven't tested it, and while merged geometry and instanced geometry would be the same amount of drawcalls, I think 100000 merged planes will render faster than 100000 instanced planes.

**Comment by finnbear** [comment]
I guess it would be interesting to quantify at what point instancing becomes more efficient than merging. A plane? A box? An icosphere? A monkey head?

**Comment by finnbear** [comment]
I guess I'll try using the InstancedMesh approach, so closing this issue for now. I'll open up another issue if something goes seriously wrong with that approach, and maybe I'll submit a PR for this.

**Comment by donmccurdy** [comment]
For something as simple as quads, you may also just want to write the data into a large BufferGeometry directly... the work of transforming geometry _without_ constructing any of the usual three.js primitives (BufferGeometry, BufferAttribute) is not something I'd want to maintain inside of `BufferGeometryUtils.mergeBufferGeometries`, which is meant to do only one thing.  But perhaps a separate utility function could be written. Let us know how that goes, or if you want to consider a PR!

**Comment by finnbear** [comment]
I was almost finished implementing Instanced Mesh usage and the performance was promising (relative to each quad being a separate mesh).

Unfortunately, I am running into errors like this:
```javascript
Failed to execute 'uniform3fv' on 'WebGL2RenderingContext': No function was found that matched the signature provided. at TypeError: Failed to execute 'uniform3fv' on 'WebGL2RenderingContext': No function was found that matched the signature provided.
    at WebGL2RenderingContext.uniform3fv (<anonymous>)
    at lk.Gj [as setValue] (https://mazean.com/js/lib/three.js/three.min.js:52:470)
    at Function.Eb.upload (https://mazean.com/js/lib/three.js/three.min.js:674:476)
    at x (https://mazean.com/js/lib/three.js/three.min.js:193:436)
    at Renderer_Renderer.renderBufferDirect (https://mazean.com/js/lib/three.js/three.min.js:209:207)
    at k (https://mazean.com/js/lib/three.js/three.min.js:176:309)
    at m (https://mazean.com/js/lib/three.js/three.min.js:176:6)
```

**Comment by gkjohnson** [comment]
You'll have to post a small snippet of your code that sets the mesh or material uniforms -- it sounds like a uniform isn't being set to a valid value. The [forum](https://discourse.threejs.org/) might be a better place to ask.

**Comment by finnbear** [comment]
> You'll have to post a small snippet of your code that sets the mesh or material uniforms -- it sounds like a uniform isn't being set to a valid value. The [forum](https://discourse.threejs.org/) might be a better place to ask.

Turned out it was simply a case of `material.color.set(0xffffff)` instead of `material.color = 0xffffff`
That always gets me :laughing:

**Comment by finnbear** [comment]
Alright, the results are in. I implemented two functions, one that converts my scene to 5 instanced meshes and one that converts it to 5 merged buffer geometries. Instanced meshes were marginally faster (around 18ms per frame instead of 19ms). Mixing the two techniques, using merging for quads and instancing for more complex objects (cubes), seemed like a good idea but the performance was worse for some reason (21ms per frame). However, one clear difference with the two approaches is that with merged buffer geometries, there was a 50-100ms spike in frame latency when it is recompiled (in part due to having to clone each child buffer geometry, the original problem behind this feature request). That doesn't seem to exist with instanced meshes, even when the entire instanceMatrix is resized and rewritten. I'll probably use instanced meshes.

Side note: Using BufferGeometryUtils.mergeVertices actually made the merged scene faster, at 17ms per frame. However, the rebuilding latency increases to 200ms and the memory usage goes from 22mb to 85mb for some reason. Not worth it.

@gkjohnson @donmccurdy pinging you because you might find this interesting, although you did recommend instanced meshes from the beginning. Thanks :)

**Comment by donmccurdy** [comment]
@finnbear both your results and your code look reasonable to me.

I expect that a carefully designed function could write arbitrary objects, with arbitrary transforms, into a large geometry buffer efficiently enough to make the 50-100ms latency go away. For an imaginary `BufferGeometryBuilder` example:

```js
var merged = new BufferGeometry();
merged.setAttribute( 'position', new Float32Array( 1e6 ), 3 );
merged.setAttribute( 'normal', new Float32Array( 1e6 ), 3 );
merged.setAttribute( 'uv', new Float32Array( 1e6 ), 2 );
merged.setIndex( new Uint8Array( 1e6 ), 3 );

var builder = new THREE.BufferGeometryBuilder( merged );
var offset1 = builder.append( geometry, matrix1 );
var offset2 = builder.append( geometry, matrix2 );
var offset3 = builder.append( geometry2, matrix1 );

// later
builder.update( offset2, geometry, matrix3 );
```

However, this sort of API seems better as a new thing, rather than a change to `mergeBufferGeometries`.

**Comment by titansoftime** [comment]
> @finnbear both your results and your code look reasonable to me.
> 
> I expect that a carefully designed function could write arbitrary objects, with arbitrary transforms, into a large geometry buffer efficiently enough to make the 50-100ms latency go away. For an imaginary `BufferGeometryBuilder` example:
> 
> ```js
> var merged = new BufferGeometry();
> merged.setAttribute( 'position', new Float32Array( 1e6 ), 3 );
> merged.setAttribute( 'normal', new Float32Array( 1e6 ), 3 );
> merged.setAttribute( 'uv', new Float32Array( 1e6 ), 2 );
> merged.setIndex( new Uint8Array( 1e6 ), 3 );
> 
> var builder = new THREE.BufferGeometryBuilder( merged );
> var offset1 = builder.append( geometry, matrix1 );
> var offset2 = builder.append( geometry, matrix2 );
> var offset3 = builder.append( geometry2, matrix1 );
> 
> // later
> builder.update( offset2, geometry, matrix3 );
> ```
> 
> However, this sort of API seems better as a new thing, rather than a change to `mergeBufferGeometries`.

Now that THREE.Geometry is being removed this suggestion/idea is even more important.

**Comment by donmccurdy** [comment]
Following up on this idea in https://github.com/mrdoob/three.js/issues/22376.
