### ISSUE TITLE
Possibility to fine tune requests on loaders

### ISSUE THREAD

**Issue by DavidPeicho** [mrdoob/three.js#18910]
Hey!

I wanted to open a discussion about the current Loader system. Right now, most of the loaders use the `FileLoader` class, containing convenient setters such as `setRequestHeader()`. The current issue is that loader such as [VTKLoader](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/VTKLoader.js), [PLYLoader](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/PLYLoader.js) don't expose the `FileLoader`. It's indeed possible for a user to make custom requests, and is actually quite easy for those two loaders.

However when using more complex loaders, such as the [GLTFLoader](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js), it becomes harder because the format can depends on external resources. The same issue arises with [OBJLoader2](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/OBJLoader2.js).

I am not sure yet about what would be the best way to handle that, but it would be a nice idea to try to standardize a common way of achieving that. What do you think?

**Comment by Mugen87** [comment]
Related: https://github.com/mrdoob/three.js/pull/18662#issuecomment-592478822

**Comment by DavidPeicho** [comment]
Erf, missed it! Thanks!

**Comment by DavidPeicho** [comment]
So basically when #18662 is merged, I guess we then need to update each format loader (OBJLoader, etc...) to set the HTTP headers on the internal loaders as well

**Comment by Mugen87** [comment]
That is the plan. It seems the OP of the PR is willing to do this, see https://github.com/mrdoob/three.js/pull/18662#issuecomment-592679449.
