### ISSUE TITLE
Disabling the shadow map doesn't clear the shadow map texture.

### ISSUE THREAD

**Issue by nzjony** [mrdoob/three.js#18926]
##### Description of the problem

Disabling the shadow map should clear the shadow map texture, otherwise its contents are used to shadow the scene.

I disable the shadows here: https://github.com/heremaps/harp.gl/blob/5d3888c964aa7671f399b1da8de65aee5ed64d54/%40here/harp-mapview/lib/MapView.ts#L2543

See the following video: https://youtu.be/POThB_VwtHE

I was able to "fix", it by moving the line: `if ( scope.enabled === false ) { return; }` to after

```
				_renderer.setRenderTarget( shadow.map );
				_renderer.clear();
```

Of course this is not a real fix.

Using three.js on dev branch, commit: db87ac02d716ce4aea76456c522d5f7aa6517e4e

Can be reproduced:
- Check out: https://github.com/heremaps/harp.gl
- `gh pr checkout 1224`
- `yarn && yarn start`
- go to: `http://localhost:8080/#threejs_shadows.html`
- set some x direction for the light, then click the "enabled" checkbox and move the map.

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer (Can't test)

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
When you turn of shadows, it's necessary to set `needsUpdate` to `true` for all materials in your scene (and materials which are stored on application level and not currently used for rendering). Doing this will recompile the respective shader since shadow rendering is hard-wired in the GLSL code.

So the real fix for you app is:
```js
scene.traverse( object => {

	if ( object.material ) {

		const material = object.material;

		if ( Array.isArray( material ) ) {

			for ( let m of material ) m.needsUpdate = true;

		} else {

			material.needsUpdate = true;

		}

	}

} );
```

**Comment by nzjony** [comment]
Thanks @Mugen87 , I think this should at least be in the documentation for https://threejs.org/docs/index.html#api/en/renderers/WebGLRenderer.shadowMap, otherwise, others who are new to three.js may have a similar issue.

**Comment by Mugen87** [comment]
Um, there is already a note in [How-to-update-things](https://threejs.org/docs/index.html#manual/en/introduction/How-to-update-things). It states that materials have to be updated when the usage of shadow maps change.

This is also true for all textures. And it seems a bit redundant to add such a note for each texture type in all material pages. Hence, the idea was to focus on this topic in a separate guide.

**Comment by nzjony** [comment]
@Mugen87 , thanks a lot, ok I will close the issue.
