### ISSUE TITLE
CurvePath getPointAt, missing optionalTarget

### ISSUE THREAD

**Issue by luruke** [mrdoob/three.js#18920]
From the documentation and typescript definition, curvePath.`getPointAt()` has 2 params, with the second being `optionalTarget`, but in reality this isn't implemented.

https://github.com/mrdoob/three.js/blob/master/src/extras/core/CurvePath.js#L58

**Comment by Mugen87** [comment]
Seems like copy/paste error in the documentation. Let me fix this.

**Comment by WestLangley** [comment]
The purpose of the "easy" tags was to alert contributors of so-called "easy" fixes.

It does not work that way, and serves no purpose.  Plus, "easy" is subjective.

I propose we remove the easy tags going forward.

**Comment by Mugen87** [comment]
Other project like React also have a similar tag system to encourage contribution. React uses these ones:

![image](https://user-images.githubusercontent.com/12612165/76969834-3dd37580-692b-11ea-8c3c-3221d08cf97a.png)

So no, I do not vote to remove them. But I'm open to replace them with something different.

**Comment by WestLangley** [comment]
>Other projects like React also have a similar tag system

So? Other projects like DRACO do not have "easy" tags.

"Easy" tags have not encouraged contribution from others here.

Labeling a bug as "easy" is a statement about yourself -- about what you know how to do. It is not a statement about the problem, it is a statement that you know how to solve the problem.

"Bug" works fine as a label.

**Comment by mrdoob** [comment]
> Labeling a bug as "easy" is a statement about yourself -- about what you know how to do. It is not a statement about the problem, it is a statement that you know how to solve the problem.

That's fair.

I think I agree. In reality I do not think people look for easy bugs. It's more common to see people reporting an issue with a proposed fix, and then we just ask them "how about making a pr?".

Happy to unify these two labels. It will also simplify our work so we don't have to judge whether something is "easy" or not.

**Comment by mrdoob** [comment]
@Mugen87 Do you think we're missing something?

**Comment by WestLangley** [comment]
>Happy to unify these two labels.

Perhaps it was implied, but I would also support unifying "Feature Request" and  "Feature Request (easy)".

**Comment by Mugen87** [comment]
> Do you think we're missing something?

I'm fine with having only `Feature Request` and `Bug`. 

It may not be that important but I still think it would be good to have something like `Good First Issue` or something like that. Just to show goodwill for people who are looking for contributing. 

At least I know that students sometimes look for such labels in project they are interested in.

**Comment by WestLangley** [comment]
Maybe the forum is a good place to provide suggestions (and help) for students interested in making a contribution. The contribution guidelines could mention the forum as a resource.

//

"Good First Issue" is also subjective. You can't make that statement unless you know the skills of the contributor.

I would be inclined to keep the labels factual.

**Comment by mrdoob** [comment]
> It may not be that important but I still think it would be good to have something like `Good First Issue`. Just to show goodwill for people who are looking for contributing. 

Worth a try, we can have an additional label for it. `[Bug] [Good First Issue]`

**Comment by mrdoob** [comment]
> Happy to unify these two labels. 

Done ✌️

**Comment by WestLangley** [comment]
>[Bug] [Good First Issue]

I do not think anyone would want their bug report to be assigned that label.

There is no point in adding that label and fixing the bug right away.

>In reality I do not think people look for easy bugs. It's more common to see people reporting an issue with a proposed fix, and then we just ask them "how about making a pr?".

Exactly. That is an excellent way to give new users the opportunity to contribute.
