### ISSUE TITLE
//!\ DECLARE ALIAS AFTER assign prototype ! are put in our .LICENSE files

### ISSUE THREAD

**Issue by Friksel** [mrdoob/three.js#18925]
When using Terser, which is practically modernized UglifyJs, to minimize Javascript and remove all comments in the go with a Webpack build, only the license-comments inside the code will be kept, but put in a seperate .LICENSE-file. 
Comments after `//` and between `/* */` will be removed to never show up in the distributables nor the .LICENSE files. But comments starting with `/*!` do (and need to) to allow us to insert license-information with these comments in our code.

This is working with and respected by all libs and frameworks I use and know of, but not with Threejs. Because Threejs has some 'license styled'-comments inside the code. Just regular comments, but not starting with `//` or use `/* */`, but use `//!\` instead, so start with `//!` and will therefore rightfully be seen as license-comments and therefore put inside our .LICENSE files by the minifier. 

Now we see comments like `DECLARE ALIAS AFTER assign prototype !` in our license files, and that's obviously now we want.

Comments found in the threejs lib like this in threejs r114:
three/build/three.js: lines 33920 and 43349,
three/build/three.module.js: lines 33912 and 43341,
three/src/animation/PropertyBinding.js: line 705,
three/src/math/Interpolant.js: line 247:
`//!\ DECLARE ALIAS AFTER assign prototype !`

Could you guys please change these all comments into normal js comments by replacing the `//!\` with `//` or using `/* */` so we don't get `DECLARE ALIAS AFTER assign prototype !` all over the place in our .LICENSE files. That should be a small effort to you guys, but would help us a lot, as we obviously don't like to have these comments in our .LICENSE files.

Thanks a lot in advance!

**Comment by Mugen87** [comment]
Okay, I've filed a PR that should remove the problematic comments from the source files.

The build files are updated when the PR is merged.

**Comment by Friksel** [comment]
Thanks for this quick action @Mugen87 !
