### ISSUE TITLE
MeshStandardMaterialSG - Only available to GLTF loader?

### ISSUE THREAD

**Issue by polarathene** [mrdoob/three.js#18938]
The material doesn't appear to be listed in the official docs, and according to [the related PR](https://github.com/mrdoob/three.js/pull/11038), it seems to be only implemented in the GLTF loader?

Is there a reason it is only supported for assets loaded in via GLTF?

**Comment by donmccurdy** [comment]
@polarathene yes, the material is only created by GLTFLoader. There are two common PBR workflows: metal/rough and spec/gloss. MeshStandardMaterial implements metal/rough, but glTF allows both, and so MeshStandardMaterialSG is used when a model contains spec/gloss materials.

There is very little difference between the two, and I do not believe it is worth supporting both as official three.js materials.
