### ISSUE TITLE
editor does not open draco gltf files

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#18930]
I think it should
![Screen Shot 2020-03-19 at 16 36 00 ](https://user-images.githubusercontent.com/242577/77084932-e3581900-69ff-11ea-9e0f-9ca72b617ed4.png)

**Comment by Mugen87** [comment]
Can you please share the asset in this issue?

Besides, does it work with `glb`?

**Comment by makc** [comment]
try this: 
[draco.gltf.zip](https://github.com/mrdoob/three.js/files/4355547/draco.gltf.zip)

see, @donmccurdy viewer can open it, so why not 3js editor?

**Comment by makc** [comment]
Thanks @Mugen87

**Comment by ozgurduygu** [comment]
This issue still persists on the editor. I haven't tried .glb draco compressed files yet but I can't seem to open .gltf draco compressed files. 

> sw.js:223 [SW] Not cached: https://threejs.org/examples/js/libs/draco/gltf/draco_wasm_wrapper.js
cacheFirst @ sw.js:223
async function (async)
cacheFirst @ sw.js:219
(anonymous) @ sw.js:213
sw.js:223 [SW] Not cached: https://threejs.org/examples/js/libs/draco/gltf/draco_decoder.wasm
cacheFirst @ sw.js:223
async function (async)
cacheFirst @ sw.js:219
(anonymous) @ sw.js:213
GLTFLoader.js:2039 Uncaught (in promise) TypeError: Cannot read property 'associations' of undefined
    at GLTFLoader.js:2039
    at async Promise.all (/editor/index 0)
    at async Promise.all (/editor/index 0)
    at async Promise.all (/editor/index 0)
    at async Promise.all (/editor/index 0)
    at async Promise.all (/editor/index 0)
    at async Promise.all (/editor/index 0)

**Comment by Mugen87** [comment]
There is a bug in `GLTFLoader` which is already fixed in `dev`. Try it with:

http://raw.githack.com/mrdoob/three.js/dev/editor/index.html
