### ISSUE TITLE
Animation incorrect when exporting GLTF from Blender

### ISSUE THREAD

**Issue by benolayinka** [mrdoob/three.js#18944]
##### Description of the problem

Animation "PersonMovement" appears incorrectly in threejs, double checked at [Don McCurdy's gltf viewer](https://gltf-viewer.donmccurdy.com/).

<img width="840" alt="Screenshot 2020-03-22 at 08 58 51" src="https://user-images.githubusercontent.com/6963436/77245032-b41df380-6c1b-11ea-896f-18691fe5b44d.png">

Animation appears correctly in Babylon's viewer. The blue dot goes up the stairs, and then turns left. In threejs, the location and rotation keyframes appear to be scaled by 50%, so the rotation is only 45 degrees and the dot moves half the intended distance. Animation in question is "PersonMovement."

<img width="767" alt="Screenshot 2020-03-22 at 08 59 40" src="https://user-images.githubusercontent.com/6963436/77245039-c7c95a00-6c1b-11ea-8bed-7e0fe5b4c851.png">

Here are the glb and blend files

[office.blend.zip](https://github.com/mrdoob/three.js/files/4364840/office.blend.zip)
[room_full.glb.zip](https://github.com/mrdoob/three.js/files/4364838/room_full.glb.zip)

##### Three.js version
- [x ] r114

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Just disable the checkbox `PersonAction` in the `three.js` based glTF viewer and the result is as expected. 

Right now, both animations are played at the same time and get mixed up.

**Comment by benolayinka** [comment]
Ah, of course! Thank you!

Am So., 22. März 2020 um 12:51 Uhr schrieb Michael Herzog <
notifications@github.com>:

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need more help.
