### ISSUE TITLE
InstancedMesh how to change color for every instance?

### ISSUE THREAD

**Issue by elewen** [mrdoob/three.js#18949]
This is my previous question of #17906，It's great that the author soon added features.

With this example （https://threejs.org/examples/#webgl_instancing_modified）, I can set different colors for each instance at the beginning.

But in my project, I also need to change the color of an instance at a certain time in the future. However, I haven't found relevant methods in the documents and other places. Who can help me? Thank you.

Does the author consider adding this feature to instancemesh? Thank you again.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need more help.
