### ISSUE TITLE
Please do not ask help question at github. Use the [forum](https://discourse.threejs.org/) or stackoverflow instead.

### ISSUE THREAD

**Issue by elewen** [mrdoob/three.js#18956]
Please do not ask help question at github. Use the [forum](https://discourse.threejs.org/) or stackoverflow instead.

_Originally posted by @Mugen87 in https://github.com/mrdoob/three.js/issues/18955#issuecomment-602536516_

**Comment by Mugen87** [comment]
Sorry, but these are the project guidelines:

> This form is for three.js bug reports and feature requests only.
This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
