### ISSUE TITLE
Editor script file being blocked by CORS policy

### ISSUE THREAD

**Issue by zjx2007** [mrdoob/three.js#18951]
![image](https://user-images.githubusercontent.com/43273440/77297027-a784c280-6d23-11ea-9317-75c3b4e68e6c.png)
The editor script file is blocked by the CORS policy.

**Comment by Mugen87** [comment]
You are opening the editor directly from file which is not supported (to be more precise the respective `file` protocol. Ensure to host the editor on a web server and the error should be gone.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need more help.
