### ISSUE TITLE
Typo in extension name for drawBuffers

### ISSUE THREAD

**Issue by NataliaDSmirnova** [mrdoob/three.js#18957]
In spite of fixing the previous typos in https://github.com/mrdoob/three.js/pull/18592 the problem isn't solved completely . There is a code reference https://github.com/mrdoob/three.js/search?q=extensionDrawBuffers&type=Code where the problem can be found easily: the word 'Buffers' versus 'buffers'.

##### Three.js version

- [ ] Dev
- [x] r114
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Good catch! /cc @OndrejSpanel
