### ISSUE TITLE
InstanceMesh does not support changing the color of an instance after being instantiated

### ISSUE THREAD

**Issue by elewen** [mrdoob/three.js#18959]
As the title.

Another problem is that if instancemesh uses raycast, the callback is still executed even if it has not been added to the scene. No matter what you think, I think this is a bug. Otherwise you can just close the question, and i spoken is null, thx.

**Comment by Mugen87** [comment]
> InstanceMesh does not support changing the color of an instance after being instantiated

Demo: https://jsfiddle.net/0ets3xdn/ (fiddle is based on [webgl_instancing_modified](https://threejs.org/examples/webgl_instancing_modified))

> Another problem is that if instancemesh uses raycast, the callback is still executed even if it has not been added to the scene.

It's intended that raycasting works even when 3D objects are not part of the scene graph.

**Comment by elewen** [comment]
> > InstanceMesh does not support changing the color of an instance after being instantiated
> 
> Demo: https://jsfiddle.net/0ets3xdn/ (fiddle is based on [webgl_instancing_modified](https://threejs.org/examples/webgl_instancing_modified))
> 
> > Another problem is that if instancemesh uses raycast, the callback is still executed even if it has not been added to the scene.
> 
> It's intended that raycasting works even when 3D objects are not part of the scene graph.

It's very nice, thank you. 
Maybe you need more developers to supplement the documentation. Threejs itself has many good features, but they are hidden, ordinary users will not know at all, and can not know the details of this part. Maybe you can do better,
