### ISSUE TITLE
WebGL.isWebGLAvailable should force context loss once it is done with the context

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#18979]
According to the [WebGL best practices guide](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices) which was just released by Kronos:

> WEBGL_lose_context.loseContext() can be used to release a WebGL context and its resources eagerly. Use this if you are finished with any contexts, such as probe contexts, or if you hit a fallback case

I'm assuming by "probe context" they mean a context that will never be visible to the user, such as the contexts created by `WEBGL.isWebGLAvailable` and `WebGL.isWebGL2Available`. 

Related: #17588

**Comment by Mugen87** [comment]
Good idea! I think it's worth trying this out 👍

**Comment by mrdoob** [comment]
#17588 was reverted...

**Comment by Mugen87** [comment]
In this case it's probably better to close the issue for now.
