### ISSUE TITLE
Matrix added to instance mesh on subsequent frame doesn't work

### ISSUE THREAD

**Issue by TheBunyip** [mrdoob/three.js#18975]
I found that if I try to add another instance to an InstancedMesh on a frame(?) after the one on which the InstancedMesh is created, the second instance it doesn't appear.

http://jsfiddle.net/vm4zpdx1/2/

**Comment by Mugen87** [comment]
Updated fiddle: http://jsfiddle.net/d4oq5ahx/

If you modify instanced data, you also have to set `InstancedMesh.instanceMatrix` to `true`.

Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need more help.

**Comment by TheBunyip** [comment]
Ah OK. The documentation says this..

.instanceMatrix : BufferAttribute
Represents the local transformation of all instances. For internal use only.

**Comment by Mugen87** [comment]
Yes, the documentation should be better in this case. How about:

> Represents the local transformation of all instances. You have to set its *needsUpdate*  flag to *true* if you modify instanced data via [page:.setMatrixAt()].

**Comment by Mugen87** [comment]
Let's give this a try.
