### ISSUE TITLE
3MF exporter

### ISSUE THREAD

**Issue by ryans1224** [mrdoob/three.js#18984]
I see there is a 3MF loader but no 3MF exporter. Would certainly be useful for 3D printing purposes to be able to export a mesh or group of meshes to 3MF

**Comment by looeee** [comment]
You could export models as glTF and then convert to 3MF. 

There's a glTF to 3MF converter here:

https://3d-convert.com/en/convert/gltf-to-3mf.html

**Comment by Mugen87** [comment]
IMO, 3MF is a quite specific format and I don't see a respective exporter in this repository. `three.js` used to provide only exporters for the most common 3D formats like OBJ, Collada or glTF. And I think that's a good policy (assuming that importers are more important than exporters for a 3D engine).

**Comment by mrdoob** [comment]
Agreed 👍

**Comment by LittleSound** [comment]
I have the same need. So I wrote a 3MF exporter for ThreeJS. If you need it, you can try it on NPM:

https://www.npmjs.com/package/three-3mf-exporter

I tested it in the slicing software of BambuStudio, and it works fine. 

I wrote this exporter for my [Bekuto3D](https://github.com/LittleSound/bekuto3d) project, you can also try it. This can well demonstrate its normal functionality. ⬇️

![Image](https://github.com/user-attachments/assets/14b10931-e85f-4e5a-8665-6037b37723b2)


❤️ This is the first time I wrote this thing, so if you encounter any issues, feel free to submit an Issue or Pull Requests.
