### ISSUE TITLE
InstancedBufferGeometry: maxInstancedCount property

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#18990]
The `maxInstancedCount` property is poorly-named, IMO.

I suggest that the property be renamed to `.instanceDrawCount`, which specifies the number of instances to render. That is how the property is being used.

Also, the renderer should silently ensure the draw count does not exceed the maximum possible, based on the buffer size -- as we currently do with `BufferGeometry.drawRange`.

- [ x ] Dev
- [  x ] r115

**Comment by WestLangley** [comment]
I am not sure if #11209 is related or not...

**Comment by Mugen87** [comment]
Um why not just `count` (similar to `InstancedMesh.count`)?

**Comment by WestLangley** [comment]
OK. Does #11209 have any bearing on this issue?

Do you think `.count` should be initialized to `Infinity`, as is `.drawRange.count`?

**Comment by Mugen87** [comment]
If would make it a mandatory parameter similar to `InstancedMesh`.
