### ISSUE TITLE
In-between stitchings or gaps on the edges of closely adjacent tile boxes

### ISSUE THREAD

**Issue by Fang3s** [mrdoob/three.js#19001]
##### Description of the problem

I want to create a 3D tile-based map. For most of the time, they are static, no transform matrix need to be applied. But, sometimes some of them also need to be animated if some switches are triggered. 

> [How to update things](https://threejs.org/docs/#manual/en/introduction/How-to-update-things)  
> if you know object will be static, you can disable this and update the transform matrix manually just when needed.
> ```js
> object.matrixAutoUpdate  = false;
> object.updateMatrix();
> ```

Unfortunately, on the make, I found a bug: even if I computed and set the correct positions for `Mesh` or `InstancedMesh` used as tile boxes of my map, we can see though the edges of those closely adjacent tile boxes, just like stitchings or gaps between them, when I moved, rotated or zoomed using `TrackballControls`. After google, Nobody go so far as to pay any attention to this issue in three.js.

```js
box.position.set(mapX + iCol * CELL_WIDTH, mapY + iRow * CELL_HEIGHT, 0);
```

I guess that when `position` is passed to Vertex Shader, those box vertexes on the left and right edge (on the x-y plane) from the top view (positive z towards to us) are not properly calculated with the `Model` matrix, the `View` matrix and the `Projection` matrix (see also [Learn OpenGL: Coordinate Systems](https://learnopengl.com/Getting-started/Coordinate-Systems), [The Model matrix](http://www.opengl-tutorial.org/beginners-tutorials/tutorial-3-matrices/#the-model-matrix), [Coordinate Transformations](https://www.khronos.org/opengl/wiki/Coordinate_Transformations)). As a result, the vertexes at the same position have slightly different x, y, z values when applying those calcaulations on closely adjacent tile boxes.

* [Object3D.matrix : Matrix4](https://threejs.org/docs/#api/en/core/Object3D.matrix)  
  The local transform matrix.
* [Object3D.matrixWorld: Matrix4](https://threejs.org/docs/#api/en/core/Object3D.matrixWorld)  
  The global transform of the object. If the Object3D has no parent, then it's identical to the local transform `.matrix`.
* [WebGLProgram: Built-in uniforms and attributes](https://threejs.org/docs/#api/en/renderers/webgl/WebGLProgram)
* [three.js/src/renderers/shaders/ShaderChunk/default_vertex.glsl.js](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/default_vertex.glsl.js)

In fact, we should, 
* let Box A and Box B closely next to each other,
* define position form `Box (x_value_on_the_left, y_value_on_the_right)`,
for example, `boxA (0, 24)` and `boxB (24, 48)`, when applying those matrixes, `24` should have the same result. 

If I reuse those vertexes at the same position using index by [BufferGeometry.setAttribute](https://threejs.org/docs/#api/en/core/BufferGeometry.setAttribute). it will be complicated for boxes that need to be animated.

Please also include a live example if possible. You can start from these templates (provided two online previews in case one site is blocked):

* [jsbin](https://output.jsbin.com/nabeqeq) (live preview)
* [codepen](https://codepen.io/kekkou/full/vYObzgp) (full page view)

Related:

* [opengl, Black lines in-between tiles](https://stackoverflow.com/questions/19611745/opengl-black-lines-in-between-tiles)
* [OpenGL - white edges on cubes](https://gamedev.stackexchange.com/questions/45821/opengl-white-edges-on-cubes)
* [White stitching on polygon edges / White lines or black dots between blocks](https://bugs.mojang.com/browse/MC-1794)
* [Black lines on the edges of tiled sprites](https://forum.unity.com/threads/black-lines-on-the-edges-of-tiled-sprites.226919)
* [Tile Map Tearing Problems](https://forum.unity.com/threads/tile-map-tearing-problems.225777)
* [Tile Map Tilemap has tearing between tiles, even with pixel snap](https://forum.unity.com/threads/tilemap-has-tearing-between-tiles-even-with-pixel-snap.499154)
* [Shading problems with cubes next to each other?](https://answers.unity.com/questions/466353/shading-problems-with-cubes-next-to-each-other.html)

##### Three.js version

- [ ] Dev
- [ ] r115
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Increase the value of your camera `near` plane to at least 1. Small values of the near plane can result in depth precision errors with a perspective camera. Keep your scene elements near the front of the frustum.

See http://www.songho.ca/opengl/gl_projectionmatrix.html.

If you need more help, please use the three.js [forum](https://discourse.threejs.org).

**Comment by Fang3s** [comment]
Good! It turns out to be an issue about stitching or [z-fighting](http://en.wikipedia.org/wiki/Z-fighting). I'm in the wrong direction.

[OpenGL Projection Matrix](http://www.songho.ca/opengl/gl_projectionmatrix.html)
> Before we move on, please take a look at the relation between z<sub>e</sub> and z<sub>n</sub>, eq.(3) once again. You notice it is a rational function and is non-linear relationship between z<sub>e</sub> and z<sub>n</sub>. It means there is very high precision at the <em>near</em> plane, but very little precision at the <em>far</em> plane. If the range [-n, -f] is getting larger, it causes a depth precision problem (z-fighting); a small change of z<sub>e</sub> around the <em>far</em> plane does not affect on z<sub>n</sub> value. The distance between <em>n</em> and <em>f</em> should be short as possible to minimize the depth buffer precision problem.

Other related links:

* [Three.js/WebGL: Large spheres appear broken at intersection](https://stackoverflow.com/questions/21080619/three-js-webgl-large-spheres-appear-broken-at-intersection/21106656#21106656)
* [Polygon Offset](http://www.zeuscmd.com/tutorials/opengl/15-PolygonOffset.php)
* [How to avoid Z-fighting/stitching/surface flickering](https://modelo.zendesk.com/hc/en-us/articles/222697548-How-to-avoid-Z-fighting-stitching-surface-flickering-)
* [Alternatives to Using Z-Bias to Fix Z-Fighting Issues](https://software.intel.com/en-us/articles/alternatives-to-using-z-bias-to-fix-z-fighting-issues)
* [[OpenGL][SharpGL]用Polygon Offset解决z-fighting和stitching问题](https://www.cnblogs.com/bitzhuwei/p/polygon-offset-for-stitching-andz-fighting.html)
* [3D渲染中的Z-fighting现象](https://zhuanlan.zhihu.com/p/78769570)
* [threejs- z-fighting 问题（模型的重叠部位便不停的闪烁起来。这便是Z-Fighting问题）](https://www.cnblogs.com/lst619247/p/9098845.html)
