### ISSUE TITLE
Depreciated function: initMaterial

### ISSUE THREAD

**Issue by DefinitelyMaybe** [mrdoob/three.js#19009]
##### Description of the problem
[PR which found the issue](https://github.com/mrdoob/three.js/pull/19008)
copied description from PR:

> I noticed #6089 but not sure how related it is.
>
>The Issue:
>Ok. hey everyone. In this next attempt at introducing classes, I've come up against a bit of trouble with the initMaterial function.
>This particular function is part of the depreciated list.
>When I run my npm dev script the local build/three.module.js file is built and the initMaterial function is there and has not been overwritten with the appropriate warning.
>When I browse to http://localhost:8080/build/three.module.js and check out that initMaterial function, it has been overwritten with the appropriate warning.
>Browse to https://threejs.org/examples/..., open the developer tools, look into the sources tab, find the build/three.module.js script. The initMaterial has not been overwritten.
>
>It turns out there are quite a large number of examples still using the depreciated function.
>materials / texture3d is a good example to try because it's not continually calling the depreciated function.
>
>could I please have some help? I have yet to find the docs corresponding with what function calls or other things should be done instead. I mean, I could start with copying the depreciated function but that'd defeat the purpose of depreciating it.

**Comment by Mugen87** [comment]
[initMaterial()](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1472) is a pure internal function and can't be called over a renderer reference. The existing function in [three.legacy.js](https://github.com/mrdoob/three.js/blob/07415e28c52afb21e5eee9dab095cc0823b3b8bb/src/Three.Legacy.js#L1661-L1665) is not used once in the example code (since it is deprecated and has obviously no effect).

**Comment by DefinitelyMaybe** [comment]
Ah. thank you for the clarification. When I said it was used by examples, I did mean that the function was called indirectly. There is no example which calls `initMaterial` directly. This did confuse me somewhat initially as my initial presumptions around what depreciating a function means conflicted with what was going on there.
