### ISSUE TITLE
about fragment code?

### ISSUE THREAD

**Issue by aibinMr** [mrdoob/three.js#19002]
`        
        #if 0 > 0
          vec4 plane;           
          #if 0 < 0
                bool clipped = true;
                if ( clipped ) discard;
            #endif
        #endif
`
when i learn the code of threejs fragment,i find the code 'if 0>0',What is it used for

**Comment by WestLangley** [comment]
@aibinMr This is not a help site, but you can get help at the three.js [forum](https://discourse.threejs.org). Please re-post your question there.
