### ISSUE TITLE
The CSS2DObject is always display=‘none’; 

### ISSUE THREAD

**Issue by pxim** [mrdoob/three.js#19004]
##### Description of the problem
https://discourse.threejs.org/t/the-css2dobject-is-always-display-none/13961
##### Three.js version

- [ ] Dev
- [x] r110
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please do not link to your forum post at github.
