### ISSUE TITLE
Video texture mapping error

### ISSUE THREAD

**Issue by zyf-2016** [mrdoob/three.js#19007]
VideoTexture doesn't work properly on Android WeChat browser.

function addVideo(config) {
            var video = document.getElementById(config.id);
            var texture = new THREE.VideoTexture(video);
            var planeGeometry = new THREE.PlaneGeometry(config.width, config.height);
            
            texture.minFilter = THREE.LinearFilter;
            texture.magFilter = THREE.LinearFilter;
            texture.format = THREE.RGBFormat;
            
            var material = new THREE.MeshBasicMaterial( { map: texture } );
            material.map = texture;
            
            var mesh = new THREE.Mesh(planeGeometry, material);
            mesh.position.set(config.x, config.y, config.z)
            mesh.rotation.y = config.rotate
            scene.add(mesh);
}

**Comment by Mugen87** [comment]
That means the following example does also not work, right?

https://threejs.org/examples/webgl_materials_video

If so, please file an issue at the respective browser vendor.
