### ISSUE TITLE
SpriteMaterial without sizeAttenuation

### ISSUE THREAD

**Issue by NeoJones** [mrdoob/three.js#19017]
Hi, so i create a sprite like this and set minFilter in the material like this:
`var spriteMap = new THREE.TextureLoader().load("tex/plates/mytest.png");`
`var spriteMat = new THREE.SpriteMaterial({map:spriteMap, transparent:true, sizeAttenuation:false});`
`var sprite = new THREE.Sprite(spriteMat);`
`spriteMat.map.minFilter = THREE.NearestFilter;`

The result looks like [this](https://i.stack.imgur.com/JiR95.png) and i got some artifacts what i dont want. If i set minFilter to Linear, its to blurry and no sharpen edges. It should look like [this example](https://i.stack.imgur.com/htF6j.png)
So is there a problem with the filter?

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests. 

It's best to share  a live example so it's easier to provide help. If there is actually an issue with the engine, this issue can be reopended.
