### ISSUE TITLE
Potree getPosition and Target Camera

### ISSUE THREAD

**Issue by GarridoM** [mrdoob/three.js#19025]
Hi!

I am using Potree and three to visualize a lidar. The problem is that I need to calculate the position and target of the camera from the cloud points, but I dont find the formula to get this.

I have debug all the code, and I have try some formulas but It does not work propertly.

Thanks in advance!

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
