### ISSUE TITLE
Docs: Facilitate indexing of the docs by certain search engines

### ISSUE THREAD

**Issue by finnbear** [mrdoob/three.js#19031]
## Description of the problem

When I want to look at the docs for a particular Three.js class, I type 'three.js [classname]` into my search engine of choice (DuckDuckGo). The only relevant result is the docs, but not the specific docs page.
![image](https://user-images.githubusercontent.com/20015102/78394998-7ddc5e80-75a1-11ea-90c3-4e595336f328.png)
I then have to click the docs and search for the class again.

## Feature request

If possible, facilitate indexing of all three.js docs pages. This may mean switching from '/docs/#api/etc' to '/docs/api/etc' urls, which could replace or forward to the existing pages.

## Search engine

- [ ] All of them
- [ ] Google (only one I tried that worked)
- [x] DuckDuckGo
- [x] Bing
- [x] Yahoo

**Comment by donmccurdy** [comment]
It used to be the case that `#!` was recommended with Google Search, and `#` basically wasn't supported. Redirecting from one to the other is just a JavaScript change.

Now it doesn't matter with Google Search. I don't know about DuckDuckGo. But you're right, if the hashbang thing doesn't work and we need to use real `/docs/foo` paths, we can't do this on GitHub Pages.

**Comment by finnbear** [comment]
Something I probably should have mentioned is that you already have URLs without the hashbangs that can be found with a slightly longer search term.
![image](https://user-images.githubusercontent.com/20015102/78403460-407fcd00-75b1-11ea-887d-ed1998ee9730.png)

However, their title of "[name]" makes them difficult to see at first glance.
![image](https://user-images.githubusercontent.com/20015102/78403641-8d63a380-75b1-11ea-9d29-a5f44740a80b.png)

If you just fixed these pages to have the proper title, maybe duck duck go and the other search engines I mentioned would index them more readily.

**Comment by mrdoob** [comment]
So their crawler doesn't support javascript?

**Comment by finnbear** [comment]
I can't speak to what DuckDuckGo or any other engine does internally, and I'm not suggesting you break any links or do the impossible. It seems like it would be possible to fix the missing [name]. 
https://github.com/mrdoob/three.js/blob/3c13d929f8d9a02c89f010a487e73ff0e57437c4/docs/api/en/math/Matrix4.html#L11

@mrdoob If you would be open to a PR, I would be willing to go through and add a <title> to each html file or replace the [name] (which is currently templated in by https://github.com/mrdoob/three.js/blob/dev/docs/page.js#L59)

**Comment by Mugen87** [comment]
Have you considered to report this issue to DuckDuckGo first? Fixing the issue on their side seems more appropriate. It then works for all websites using the current docs approach.

**Comment by mrdoob** [comment]
> @mrdoob If you would be open to a PR, I would be willing to go through and add a <title> to each html file

Sure! As long as you are willing to continue updating all the relevant files for the rest of your life 😁

More seriously, this is an issue with DuckDuckGo's crawler.

**Comment by finnbear** [comment]
What was I thinking? There is a much easier, standards-compliant way to fix this issue: adding a sitemap. Please review #19037 :smiley:

**Comment by looeee** [comment]
It's the same on Bing: 

![bing](https://user-images.githubusercontent.com/5307958/78518756-8fb14200-77eb-11ea-9368-4fea7225a045.png)

Maybe DDG uses Bing?

**Comment by finnbear** [comment]
> Maybe DDG uses Bing?

Well, technically yes.
> DuckDuckGo's results are a compilation of "over 400" sources, including Yahoo! Search BOSS, Wolfram Alpha, Bing, Yandex, its own web crawler (the DuckDuckBot) and others.

From: https://en.wikipedia.org/wiki/DuckDuckGo

I don't think either Bing or DuckDuckGo is to blame though. By using google analytics, you may be giving Google an advantage when it comes to indexing the page as the user sees it :wink: 

Having a proper sitemap is a good first step for any search engine, hence the PR. By having the sitemap point to the urls with the '#', and thus the proper title, instead of the raw html pages, the [name] issue may be fixed.

In the unlikely event that it doesn't fix the [name] issue, some sort of <title> would have to be baked into the HTML. I'm still willing to do that, unless the resulting PR would be rejected if it lacked a mechanism to keep the titles 100% up to date.

**Comment by Mugen87** [comment]
> More seriously, this is an issue with DuckDuckGo's crawler.

Yes, I don't think we need a PR in any form. Hence, I also think that the sitemap is not necessary.

Again, this needs to be fixed on search-engine website.

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/issues/19031#issuecomment-609000135.
