### ISSUE TITLE
Sound pause and play not working correctly with looped audios.

### ISSUE THREAD

**Issue by yatharth1706** [mrdoob/three.js#19045]
##### Description of the problem
I started learning threejs recently. I tried using audio Api of it. I made a button for pause and play

I added following code:
```js
        var audioListener = new THREE.AudioListener();

	var sound = new THREE.Audio(audioListener);

	var audioLoader = new THREE.AudioLoader();

	audioLoader.load('sound/music1.mp3', function(buffer){
			sound.setBuffer(buffer);
			sound.setLoop(true);
			sound.setVolume(0.5);
			sound.play(); 	
			sound.detune =1100;
	});
        var btn = document.querySelector('#btn1');
        btn.addEventListener('click', function(){
	        if(sound.isPlaying == true){
			sound.pause();
		}else{
			sound.play();
		}
			
	})
```

Now after running it on browser i am playing and pausing by clicking on button but song is played sometimes from very back or from very forward in time. Its not accurate when paused and played again.

##### Three.js version

- [x] Dev
- [x] r115
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Realted: https://github.com/mrdoob/three.js/pull/18676#issuecomment-605713023
