### ISSUE TITLE
Fixing remaining lgtm alerts.

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#19057]
##### Description of the problem

I'd like to use this issue to track the remaining lgtm alerts. After a series or PRs, there are only three left. 

- [ ] One alert in [editor/js/libs/ternjs/doc_comment.js](https://lgtm.com/projects/g/mrdoob/three.js/snapshot/be1bba95d8a08161e114a3bb783f9e3c787ead9f/files/editor/js/libs/ternjs/doc_comment.js?sort=name&dir=ASC&mode=heatmap#x907de5f7941e4112:1).
-  [ ] The other one in [examples/js/misc/Volume.js](https://lgtm.com/projects/g/mrdoob/three.js/snapshot/be1bba95d8a08161e114a3bb783f9e3c787ead9f/files/examples/jsm/misc/Volume.js#x883cebd691ecdba7:1) which counts double (because of the module file). Related: https://github.com/mrdoob/three.js/pull/8364#discussion_r403685974.

##### Three.js version

- [x] Dev
- [ ] r115
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Both alerts are actually not easy to fix. Let's see if the original developer of `NRRDLoader` can help with the latter one.

The first one in `doc_comment.js` is strange. I really don't understand the usage of the `madeUp` variable and the respective assignments.

**Comment by mrdoob** [comment]
Seems like tern.js no longer has that issue:
https://lgtm.com/projects/g/ternjs/tern/

**Comment by Mugen87** [comment]
Um, they actually deleted the mentioned line: https://github.com/ternjs/tern/commit/3f8a2bc7c2e9a4ac55e8c6f6c60c0634cbe71326

Let's apply this hotfix 🤓

**Comment by Mugen87** [comment]
![image](https://user-images.githubusercontent.com/12612165/78685832-95de1600-78f2-11ea-800c-95383f1dba3d.png)
 Yay! 🎉 🎉 🎉

**Comment by mrdoob** [comment]
👏👏👏
