### ISSUE TITLE
Definition of Intrinsic Tait-Bryan Euler Angles does not reflect actual behavior

### ISSUE THREAD

**Issue by Carpetfizz** [mrdoob/three.js#19059]
##### Description of the problem

In the [documentation](https://threejs.org/docs/#api/en/math/Euler.order), the description of Three's rotation system is as follows:

> Three.js uses intrinsic Tait-Bryan angles. This means that rotations are performed with respect to the local coordinate system. That is, for order 'XYZ', the rotation is first around the local-X axis (which is the same as the world-X axis), then around local-Y (which may now be different from the world Y-axis), then local-Z (which may be different from the world Z-axis).

Please open the [jsfiddle](https://jsfiddle.net/ux968gjo/) to follow along.

1. Initialize a red vector representing the x-axis of some local coordinate system.
2. Initialize the magenta vector representing the x-axis of the world coordinate system.
Initially, the local X and world X coincide.
3. Change the local coordinate system of the red vector by rotating it around its Y and Z'.
4. In the animation, rotate about the local X axis, which should point along the direction of the red vector.

Based on the description in the documentation, the red vector should just rotate about itself (since its visualizing its local x-axis) and the rotation shouldn't be visible (except for maybe some aliasing artifacts).

But instead, it appears as though the red vector is rotating about the world x-axis (magenta vector).

I'm sure the Euler rotation function has been thoroughly vetted by now, so perhaps this isn't a real bug. But it still appears as though there's an inconsistency between the documentation and the behavior I see on screen.

##### Three.js version

- [x] r110

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
You appear to have some fundamental misconceptions. See if [this SO post](https://stackoverflow.com/questions/17517937/three-js-camera-tilt-up-or-down-and-keep-horizon-level/17518092#17518092) helps.

If not, then you can get additional help at the three.js [forum](https://discourse.threejs.org).

**Comment by Carpetfizz** [comment]
Hi @WestLangley thank you for the reply. I'm glad this is just a misconception on my part. In the linked SO post,

> Rotations are performed with respect to the object's internal coordinate system -- not the world coordinate system. This is important. So, for example, after the x-rotation occurs, the object's y- and z- axes will generally no longer be aligned with the world axes. Rotations specified in this way are not unique.

Am I wrong in thinking that the red arrow is visualizing the new local x-axis of the vector after its been rotated about Y and Z?

**Comment by WestLangley** [comment]
@Carpetfizz Yes, please try the forum. There are plenty of users there who understand these concepts and can help you.
