### ISSUE TITLE
exporting the json with same suggested settings not give the same file which already created as in demo. I have tried for face.obj my file is of 69 pages and the available face.json file is 569 pages. and thus when i replace glasses model with my own it dont display. what to do plz?

### ISSUE THREAD

**Issue by yasirjutt683** [mrdoob/three.js#19063]
exporting the json with same suggested settings not give the same file which already created as in demo. I have tried for face.obj my file is of 69 pages and the available face.json file is 569 pages. and thus when i replace glasses model with my own it dont display. what to do plz?

**Comment by donmccurdy** [comment]
Please use the forum (https://discourse.threejs.org/) for help. You will also need to provide further details about which models you are referring to, and how you are exporting and loading them.
