### ISSUE TITLE
doesn't get a proper value on the multi scene sample

### ISSUE THREAD

**Issue by shunp** [mrdoob/three.js#19066]
##### Description of the problem

In the sample scene named Multiple Scenes Comparison, I encountered the error below.
`Cannot read property '0' of undefined`

I found that `e.touches` becomes `undefined`.

```javascript
function slideMove( e ) {
  if ( ! clicked ) return false;
  sliderMoved = true;

  // e.touches is undefined
  sliderPos = e.pageX || e.touches[ 0 ].pageX;

  if ( sliderPos < 0 ) sliderPos = 0;
  if ( sliderPos > window.innerWidth ) sliderPos = window.innerWidth;
  slider.style.left = sliderPos - ( slider.offsetWidth / 2 ) + "px";
}
```

https://github.com/mrdoob/three.js/blob/master/examples/webgl_multiple_scenes_comparison.html

##### Three.js version

- [ ] Dev
- [x] r115
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Well, on desktop (you reported this issue with macOS) `e.touches` is undefined unless your device has touch capabilities and you perform touch input. Hence, the logic directly works with `e.pageX`.

**Comment by shunp** [comment]
@Mugen87 Thank you for your comment!
I faced the issue that when the `e.pageX` turns out to be zero, `e.touches` becomes activated and it happens the error.
