### ISSUE TITLE
  WebGLRenderer .setClearColor is not Work   context:WebGL2ContextRenderer

### ISSUE THREAD

**Issue by JMccain** [mrdoob/three.js#19076]
在webgl2 里  
设置 WebGLRenderer .setClearColor 无效。
  
1. WebGLRenderer .setClearColor is not Work,

- [ ] Dev
- [ ] r115

**Comment by Mugen87** [comment]
It seems there is an issue in your code. 

As demonstrated by the following live example, using `WebGLRenderer.setClearColor()` with a WebGL 2 rendering context works without issues. https://jsfiddle.net/t4wm98uv/
