### ISSUE TITLE
WebXR seems to render everything twice for immersive-ar

### ISSUE THREAD

**Issue by edankwan** [mrdoob/three.js#19071]
WebXR seems to render everything twice for `immersive-ar`

jsfiddle doesn't seem to work with WebXR. I did a some tests, by doing

```js
mesh.onBeforeRender = function (renderer, scene, camera) {
    console.log(camera._idx); // 
}

function render () {
    if (renderer.xr.enabled && renderer.xr.isPresenting) {
        console.log('render');
        var cameraVR = renderer.xr.getCamera(camera);
        cameraVR.cameras[0]._idx = 0;
        cameraVR.cameras[1]._idx = 1;
    }
}

render
0
1
render
0
1
...
```

I also tried adding a lot of meshes and test the performance. By adding the following, it seems smoother:

```js
function render () {
    if (renderer.xr.enabled && renderer.xr.isPresenting) {
        renderer.xr.getCamera(camera).cameras.length = 1;
    }
}
```

##### Three.js version

- [ ] Dev
- [x] r115
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Pixel 2

**Comment by edankwan** [comment]
Added the source codes of the test here:
[test.zip](https://github.com/mrdoob/three.js/files/4449167/test.zip)

I simply modified the `webxr_ar_cones` example, removed the cone creation and simply added a `Torus Knot`. Like the following:
```
var mesh = new THREE.Mesh(new THREE.TorusKnotBufferGeometry( 0.5, 0.15, 128, 24 ), new THREE.MeshNormalMaterial());
mesh.position.z = -2;
mesh.onBeforeRender = function (renderer, scene, camera) {
    console.log(camera._idx); // 
}
scene.add(mesh);
```

At the `renderer.render()`, I added
```
console.log('render');
if (renderer.xr.enabled && renderer.xr.isPresenting) {
    var cameraVR = renderer.xr.getCamera(camera);
    cameraVR.cameras[0]._idx = 0;
    cameraVR.cameras[1]._idx = 1;
}
renderer.render( scene, camera );
```

I cloned the three.module.js(v115) and before the `gl.drawElements( mode, count, type, start * bytesPerElement );` at line 16273, I added a `console.log('drawElements');`

Within non-webxr console, I got..
```
render
-1
drawElements
render
-1
drawElements
render
-1
drawElements
...
```


Within webxr console, I got..
```
render
0
drawElements
1
drawElements
render
0
drawElements
1
drawElements
render
0
drawElements
1
drawElements
...
```

It indicates that the `gl.drawElements()` triggers twice in one frame.

**Comment by Mugen87** [comment]
Probably related #18525.
