### ISSUE TITLE
Have Mesh.d.ts use Generics to retreive Geometry and Material types

### ISSUE THREAD

**Issue by samuelint** [mrdoob/three.js#19072]
##### Description of the problem
Hi, it would be really great to be able to specify generics from `Geometry | BufferGeometry` and `Material` in `Mesh.d.ts`.

In my current project, I need to change the `Material` property dynamically and I always need to keep an external reference on the `Material` class used to avoid casting. This change would avoid to always keep the reference and avoid casting.

Change request:
```
export class Mesh<TGeometry extends Geometry | BufferGeometry = Geometry | BufferGeometry, TMaterial extends Material  | Material[] = Material  | Material[]> extends Object3D {

	constructor(
		geometry?: TGeometry,
		material?: TMaterial
	);

	geometry: TGeometry;
	material: TMaterial;
	morphTargetInfluences?: number[];
	morphTargetDictionary?: { [key: string]: number };
	readonly isMesh: true;
	type: string;

	updateMorphTargets(): void;
	raycast( raycaster: Raycaster, intersects: Intersection[] ): void;
}
```

Usage
```
const mesh = new Mesh<BufferGeometry, MeshPhongMaterial>(myGeometry, myMaterial);

const material: MeshPhongMaterial = mesh.material;

```

##### Three.js version
- [ X ] r115

##### Browser
- [x] All of them

##### OS
- [x] All of them

It would be my first time to make a feature request? Can I do a pull request by myself? What's the procedure?

Thank you

**Comment by Mugen87** [comment]
Are you looking for something like this? #18720

The PR was not merged so far since nobody of the core team is a TS expert^^. If you can review and approve the change, there might be a chance to get it merged.

**Comment by samuelint** [comment]
Yes, that PR seem pretty much like my suggestion. I can review typescript in #18720 :)
Thank you!
