### ISSUE TITLE
Shapes with holes are sometimes rendered incorrectly

### ISSUE THREAD

**Issue by eulertour** [mrdoob/three.js#19077]
##### Description of the problem

A Shape which has holes (an infinity symbol) and is created with ShapePath is rendered incorrectly when drawn from one position but correctly when drawn from others. The linked fiddle shows the incorrect rendering by default, but will display the rendering correctly after the points are shifted.

Repro: https://jsfiddle.net/dkvo0uxn/1/

##### Three.js version

- [x] Dev
- [x] r115

##### Browser

- [x] Chrome 80.0.3987.149
- [x] Firefox 74.0
- [ ] Internet Explorer

##### OS

- [ ] Windows
- [ ] iOS
- [x] Linux
- [x] Android
- [ ] macOS

##### Hardware Requirements (graphics card, VR Device, ...)

None that I know of.

**Comment by Mugen87** [comment]
How do you figured out the value `0.3664`? 

Here is an update version of your fiddle which makes it easier to inspect the shape: https://jsfiddle.net/916xyuf8/

The three.js related code looks fine however I'm not going to debug the curve sequences. I've imported the following [SVG file](https://upload.wikimedia.org/wikipedia/commons/c/c8/Infinite.svg) into the [editor](https://threejs.org/editor/) and the result is just fine:

![image](https://user-images.githubusercontent.com/12612165/78764522-f61e9780-7986-11ea-8e19-59383d5f2394.png)

`SVGLoader` also uses shape API so it there is an issue in your code. So there seems be a problem in the way you draw your curves.

**Comment by eulertour** [comment]
> How do you figured out the value 0.3664?

I ran into this while building an app and noticed that it only seemed to render incorrectly around a certain spot. From there it was just trial and error. The problem is specific enough that it isn't a huge deal for me, but I just wanted to let you know.

Since the shape is composed entirely of M and C commands it wouldn't be hard to convert it into an SVG. If the problem also occurred with the SVGLoader would it then be considered a bug?

**Comment by Mugen87** [comment]
> Since the shape is composed entirely of M and C commands it wouldn't be hard to convert it into an SVG. If the problem also occurred with the SVGLoader would it then be considered a bug?

I think this would make it more likely to investigate the issue. Any chances to provide a SVG with your shape?

**Comment by eulertour** [comment]
I verified that the SVG that the data was originally taken from is rendered correctly. It's attached here if you're curious. In my use case I ended up parsing this SVG in another program and only then passing the data to three.js.

I was more asking if it would be considered a bug if I were to take this data, make an SVG from it, and reproduce the error after passing it to the SVGLoader.

[infinity.txt](https://github.com/mrdoob/three.js/files/4449849/infinity.txt)

**Comment by Mugen87** [comment]
> I verified that the SVG that the data was originally taken from is rendered correctly.

Yeah, I've imported the SVG into the editor and it looks as expected (I've just added a nice color so it's easier to see it):

![image](https://user-images.githubusercontent.com/12612165/78776781-b52f7e80-7998-11ea-9f96-53d5dcb82fdd.png)

So it seems it works fine when using `SVGLoader`.

**Comment by eulertour** [comment]
I don't know if you saw in my previous comment, but I meant to ask if it would be considered a bug were I able to reproduce the problem with an SVG created from the custom path data. Essentially to see if it's possible for the SVGLoader to run the same commands that are run in the jsfiddle. The one attached there is from the original SVG.

To be clear, I think it would be reasonable if you didn't consider something like this to be a valid use case, but I wanted to ask about it.

**Comment by Mugen87** [comment]
Well, if the browser would be able to render the SVG correctly but not `three.js` via `SVGLoader`, it would be worth further investigations.

**Comment by mrdoob** [comment]
> Yeah, I've imported the SVG into the editor and it looks as expected 

Seems like it's not a bug in the library then..
