### ISSUE TITLE
threejs.org broken for IE11

### ISSUE THREAD

**Issue by vector3** [mrdoob/three.js#19082]
Hi,

not sure if this is the right place to post this issue. Feel free to point me to the correct place if not :)

When opening the site, the layout is all over the place and the examples don't work at all.
Tested with IE11, version 11.0.9600.19650.

Cheers.

**Comment by Mugen87** [comment]
Yes, the examples do not work in IE11 anymore since they are using ES6 modules now. The homepage itself uses the CSS grid property which is not fully supported by IE11.

**Comment by vector3** [comment]
Hm, ok. I used to open the examles page on ie11 just to validate that some functionality/rendering feature works correctly on that browser. I guess I have to find another way to quickly check then.

**Comment by Mugen87** [comment]
Yes, IE 11 support will not be added back. It's actually best to not use this browser anymore if possible.

**Comment by vector3** [comment]
Got it. Thanks.
