### ISSUE TITLE
Please update camera's position and quaternion in XR mode

### ISSUE THREAD

**Issue by marcofugaro** [mrdoob/three.js#19084]
Hey, I've been trying the XR mode (specifically `immersive-ar`) and I have some feedback.

Currently, each time you have to get the camera's position and quaternion, you have to do it like this:

```js
const cameraPosition = new THREE.Vector3().setFromMatrixPosition(camera.matrixWorld)
const cameraQuaternion =  new THREE.Quaternion().setFromRotationMatrix(camera.matrixWorld)
```

Because just the `camera.matrixWorld` is updated directly from the `XRViewerPose`, the position and quaternion are never updated.

https://github.com/mrdoob/three.js/blob/043e5c932da1da2a581b2887219ac708bfd838f7/src/renderers/webxr/WebXRManager.js#L415

Can this be solved just by setting the position and quaternion from the matrixWorld each frame and setting `camera.matrixAutoUpdate = false`?

**Comment by Mugen87** [comment]
I believe this issue is related to https://github.com/mrdoob/three.js/issues/18448#issuecomment-577339080.

If so, is it okay for you to mark this issue as a duplicate and continue the discussion in #18448?

**Comment by marcofugaro** [comment]
Yeah sure. So are `camera.position` and `camera.quaternion` be updated automatically when that issue will be fixed?

**Comment by Mugen87** [comment]
Let's see how this PR goes: #19085
