### ISSUE TITLE
Whats happening now? ES6 classes

### ISSUE THREAD

**Issue by DefinitelyMaybe** [mrdoob/three.js#19080]
Hi there,

I wanted to create this issue to try and tease out everyone's thoughts on how we'd like to move forward with class migration.

My quick summary of what I've come across so far:
- We should deprecate the `examples` folder before doing anything else
- There are parts of `src/` that aren't extended by any of the examples that could be converted
- With some changes to the modularize.js script we could get started on `examples/js/` which generates the corresponding `examples/jsm` scripts.

Have I missed anything?

**Comment by Mugen87** [comment]
I'm not sure why you create a new issue when there is already #11552?

Sorry, but creating new issues in this way is no good style to draw attention to a topic.

**Comment by DefinitelyMaybe** [comment]
happy to repost there. we can simply agree to disagree here as I thought adding to the issue there would've distorted that discussion as we'll be needing to talk about deprecation of examples/js.
