### ISSUE TITLE
WebXRManager: getController() and getControllerGrip() should return false if there is no controller.

### ISSUE THREAD

**Issue by shenzhuxi** [mrdoob/three.js#19086]
getController();
getController(0);
getController(1);
getController(100);
getController('abc');

getController() and getControllerGrip() always return a Group type object no matter what the argument is. 
Did I miss anything or just no way to tell how many controllers are there?

**Comment by Mugen87** [comment]
Internal WebXR controllers are mapped to WebXR input sources. This mapping happens during runtime. Meaning when you call `getController()` or `getControllerGrip()` like in this [example](https://threejs.org/examples/webxr_vr_ballshooter), the controller is not mapped yet to an input source. Hence, with the current API there is no other way than always return a group. This group will receive tracking information as soon as an input source is mapped to it.

**Comment by Mugen87** [comment]
> getController('abc');

I'm afraid this code is invalid. The idea is to use only integers in an ascending pattern (meaning 0,1,2 for indexing the first, second and third controller).

**Comment by shenzhuxi** [comment]
Thanks @Mugen87.  
I understand that there is no way to get the controllers' information before XRInputSource. 
If you put console.log(renderer.xr.getController(  )) and console.log(renderer.xr.getController( 'abc' )) in webxr_vr_ballshooter example (with three.js r115), there will be no error. I think it should check the whether the argument is an integer.

**Comment by Mugen87** [comment]
> I think it should check the whether the argument is an integer.

`three.js` does in general not validate parameters for performance reasons. However, there is #19090. Naming the parameter as `index` should imply that it's an integer whereas `id` can be for example a string, too.
