### ISSUE TITLE
Per-material shadow bias

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#19094]
It currently sits in the light, but as it happens the same value of bias would fix one object in the scene while causing problems for another. How hard would it be to add an optional bias to the material, and will this work for e g [#12919](https://github.com/mrdoob/three.js/issues/12919#issuecomment-544023839)

Looking at the code, ~~it is just passed as the uniform parameter,~~ so altering it should not be a problem?
![Screen Shot 2020-04-09 at 19 54 39 ](https://user-images.githubusercontent.com/242577/78925686-1ee48100-7a9c-11ea-9b80-0cfb14ecda6f.png)

Ok no, looks like those are some different uniforms, for shadow pass or something. ~~It is not on material uniforms in onBeforeCompile :(~~

It is actually in param.uniforms.directionalLights.value[0]

Ok, so I was able to do this hack:
```
material.onBeforeCompile = function(stuff) {
	var chunk = THREE.ShaderChunk.shadowmap_pars_fragment
		.split ('z += shadowBias')
		.join ('z += shadowBias - 0.001');
	stuff.fragmentShader = stuff.fragmentShader
		.split ('#include <shadowmap_pars_fragment>')
		.join (chunk);
};
```
so this is definitely possible.

**Comment by gkjohnson** [comment]
#18915 should hopefully lead to some improvements in this area without having to tweak individual materials. I think ideally the user wouldn't have to modify shadow properties per material.

**Comment by makc** [comment]
> ideally the user wouldn't have to modify shadow properties per material

ideally I should not set the bias either - just enable shadows and have nice shadows. this ticket, however, was born out of the situation that was far from ideal.

**Comment by Mugen87** [comment]
>  ideally I should not set the bias either 

Even engines like Unity can't provide perfect shadows automatically. If you closely study how shadow mapping works, it should be clear that manual adjustments are  inevitable.

Regarding the feature request itself: I do not vote for supporting shadow properties on material level. Unity also provides shadow bias and shadow normal bias only on [lights level](https://docs.unity3d.com/Manual/class-Light.html). That should be sufficient.

**Comment by makc** [comment]
Maybe it should be, but it is not. Unfortunately.

**Comment by makc** [comment]
...that said, I do not insist on this feature, as long as the onBeforeCompile is there we can hack any feature we want in. If you do feel like that this is too much work for making people lives only o much easier, feel free to close the ticket.

**Comment by mrdoob** [comment]
@makc Have you tried the new `normalBias`?

**Comment by makc** [comment]
@mrdoob nope, is there an example?

**Comment by mrdoob** [comment]
I don't think so. It's a new property in the shadow.

You can try it in the editor:

`shadow.normalBias = 0`:

<img width="1216" alt="Screen Shot 2020-07-27 at 6 40 47 PM" src="https://user-images.githubusercontent.com/97088/88568163-7cb0cf00-d073-11ea-90e2-e229ca38e958.png">

`shadow.normalBias = 0.05`:

<img width="1216" alt="Screen Shot 2020-07-27 at 6 41 11 PM" src="https://user-images.githubusercontent.com/97088/88568181-84707380-d073-11ea-95d4-47edab731807.png">

**Comment by Mugen87** [comment]
Instead of moving shadow properties to materials, it's better to focus on #13108. Meaning investigating and introducing new shadow approaches for tweaking shadows (like `normalBias`).
