### ISSUE TITLE
SVGs are sometimes rendered incorrectly

### ISSUE THREAD

**Issue by eulertour** [mrdoob/three.js#19102]
##### Description of the problem

This is a follow-up to #19077. The following svg is rendered correctly in firefox, chrome, and android, but incorrectly in three.js.

[infinity.txt](https://github.com/mrdoob/three.js/files/4461027/infinity.txt)

Repro: https://jsfiddle.net/L3krx9ho/

##### Three.js version

- [x] Dev
- [x] r115

##### Browser

- [ ] All of them
- [x] Chrome 80.0.3987.149
- [x] Firefox 74.0
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [x] Android
- [ ] iOS

**Comment by Mugen87** [comment]
This is the result if we use a similar approach like in the [SVGLoader example](https://threejs.org/examples/webgl_loader_svg):

https://jsfiddle.net/s7denhm3/

Probably related to #16950

**Comment by WestLangley** [comment]
@eulertour 

Do you know if your shape is specified as (a) shape-hole-hole, or (b) hole-shape-hole, or (c) hole-hole-shape?

Do you know if the winding order of the holes is opposite that of the shape?

**Comment by eulertour** [comment]
It's shape-hole-hole (infinity outline, right hole, left hole), with the infinity outline going clockwise and the two holes going counterclockwise.

**Comment by WestLangley** [comment]
Well, that sounds correct...

**Comment by WestLangley** [comment]
I stumbled on the source of the problem...
```js
let geometry = new THREE.ShapeBufferGeometry( shape, 11 ); // 10, and the default 12, break
```
...but I have no idea what is causing the triangulation to break. FWIW, there are a lot of duplicate points that are removed.

fiddle: https://jsfiddle.net/m4sn6gcq/

I will likely not be spending any more time on this.
