### ISSUE TITLE
Can only open and run examples and programs in Microsoft Edge Fails in any other browser

### ISSUE THREAD

**Issue by Nivlac8334** [mrdoob/three.js#19128]
I attempted to clone and download the three.js folder to then view the examples and change them to get started of how this works. However when opening the examples in chrome or firefox they fail to load and are blank screens. However when running them in microsoft edge they are able to load.

**Comment by DefinitelyMaybe** [comment]
try ask around on [the forum](https://discourse.threejs.org/).

you may be able to get better help there if you describe your problem with more details.
