### ISSUE TITLE
question: efficient way to render point cloud

### ISSUE THREAD

**Issue by weidezhang** [mrdoob/three.js#19134]
Hi, 

I am wondering what's the most efficient to render the point cloud. The point cloud is updated every 100ms with both per point position change and universal location and rotation change. 

Current implementation is at:
https://github.com/ApolloAuto/apollo/blob/master/modules/dreamview/frontend/src/renderer/point_cloud.js

Currently I'm using three.js version 0.56. 
I'm not sure if it's the most efficient way to do that or if there is better way ? say using instancedmesh ?

Thank you, 

Weide

**Comment by mrdoob** [comment]
Please, use the [forum](https://discourse.threejs.org/) for questions and help.
