### ISSUE TITLE
Three js lightweight version

### ISSUE THREAD

**Issue by viking58** [mrdoob/three.js#19148]
I want to know if there is any version of three.js that has smaller size than  400K version ?

**Comment by Mugen87** [comment]
As mentioned in the release notes, a gzipped version of the library is way smaller than 400KB. It should be ~150 KB.

**Comment by viking58** [comment]
great thanks for your fast reply

**Comment by mrdoob** [comment]
There is also [Shree.js](https://github.com/sawa-zen/shree) which is `Three.js` but only with `BufferGeometry` and `ShaderMaterial`.
