### ISSUE TITLE
Typecast fails if `getObjectByName` method returns objects other than Object3D

### ISSUE THREAD

**Issue by sarthak-saxena** [mrdoob/three.js#19150]
Please refer the example mentioned below:

```
const scene = new THREE.scene()
const upperPlaneCloudMaterial = new THREE.PointsMaterial({
            vertexColors: THREE.VertexColors,
            size: 0.08,
            clippingPlanes: []
        })
const pointsObject = new THREE.Points(this.cloudGeometry, upperPlaneCloudMaterial)
const pointsObject.name = 'pointsObject'
scene.add(this.cloudField)
```

Now while getting cloud field by method `getObjectByName()` 
```
const pointsObject = scene.getObjectByName('pointsObject')
pointsObject.geometry.attributes.position.needsUpdate = true
pointsObject.geometry.attributes.position.setArray(attributesData.position)
pointsObject.geometry.computeBoundingSphere()
```
It gives type error as mentioned below:
`Property 'geometry' does not exist on type 'Object3D'`

##### Three.js version

- [x] Dev
- [x] r115
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by sarthak-saxena** [comment]
PR for fix: https://github.com/mrdoob/three.js/pull/19149

**Comment by donmccurdy** [comment]
I don't see a cast in your code above — does this also fail to compile in TypeScript?

```ts
const points = scene.getObjectByName('pointsObject') as THREE.Points;
const position = points.geometry.getAttribute('position');
```

**Comment by sarthak-saxena** [comment]
> I don't see a cast in your code above — does this also fail to compile in TypeScript?
> 
> ```ts
> const points = scene.getObjectByName('pointsObject') as THREE.Points;
> const position = points.geometry.getAttribute('position');
> ```

**Comment by Mugen87** [comment]
@sarthak-saxena It seems @donmccurdy solutions is more appropriate than changing the declaration of `getObjectByName()`. Can this issue be closed?

**Comment by sarthak-saxena** [comment]
> @sarthak-saxena It seems @donmccurdy solutions is more appropriate than changing the declaration of `getObjectByName()`. Can this issue be closed?



> I don't see a cast in your code above — does this also fail to compile in TypeScript?
> 
> ```ts
> const points = scene.getObjectByName('pointsObject') as THREE.Points;
> const position = points.geometry.getAttribute('position');
> ```

Yes got it. Thanks for the help :)

**Comment by sarthak-saxena** [comment]
> @sarthak-saxena It seems @donmccurdy solutions is more appropriate than changing the declaration of `getObjectByName()`. Can this issue be closed?

Yes we can close this issue now
