### ISSUE TITLE
Using div to make sprite map

### ISSUE THREAD

**Issue by yanwencheng** [mrdoob/three.js#19166]
Div contains the pop-up style and dynamic text. What do I need to do if I want to use this as a sprite map. Thank you very much.

**Comment by looeee** [comment]
Please put help requests on the forum, and read over this post for instructions on how to ask a good question:

https://discourse.threejs.org/t/please-read-this-before-posting-a-question/24/2

**Comment by yanwencheng** [comment]
> 请在论坛上提出帮助请求，并仔细阅读此帖子以获取有关如何提出一个好问题的说明：
> 
> https://discourse.threejs.org/t/please-read-this-before-posting-a-question/24/2

Connection timed out, unable to access

**Comment by looeee** [comment]
It's working fine for me. You can also try asking on Stackoverflow:

https://stackoverflow.com/questions/tagged/three.js
