### ISSUE TITLE
'Cannot read property "precision" of null.' on Brave browser.

### ISSUE THREAD

**Issue by wntiv-main** [mrdoob/three.js#19173]
'Cannot read property "precision" of null' in `new THREE.WebGLRenderer();` on Brave browser (works on Chrome... ):
![image](https://user-images.githubusercontent.com/60457971/79712205-5c5bd080-831e-11ea-8f20-3480642948dd.png)
![image](https://user-images.githubusercontent.com/60457971/79712256-74cbeb00-831e-11ea-93c0-7a77fefafc95.png)

* [jsfiddle](https://jsfiddle.net/mkba0ecu/) (three.js live example as seen on threejs.org documentation)

##### Three.js version

- [x] r115
- [ ] Dev

##### Browser

- [x] Brave
- [ ] Chrome
- [ ] All of them
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] All of them

**Comment by mrdoob** [comment]
Please, report this to Brave browser instead.
