### ISSUE TITLE
Slowness after tab reload

### ISSUE THREAD

**Issue by kpeeters** [mrdoob/three.js#19182]
##### Description of the problem

I am suspecting this is a browser bug, but just in case someone has encountered it before and knows about a workaround, I thought I'd ask here.

I have a three.js app which is fine on first start, but as soon as I reload the tab, performance goes down the drain. 100% reproducible. It seems like something is not cleaned up, and while one would expect the browser to take care of that on tab reload, it obviously doesn't. 

Is there a recommended way to tear down the webgl context in `onbeforeunload` that may avoid this problem?

##### Three.js version

r115

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Only seems to happen on discrete GPUs; can't reproduce on integrated Intel GPUs.

**Comment by Mugen87** [comment]
This is indeed a browser issue and unrelated to the engine. Please ask such question at the [forum](https://discourse.threejs.org/) or stackoverflow.

**Comment by Mugen87** [comment]
https://discourse.threejs.org/t/slowdown-after-tab-reload/14487
