### ISSUE TITLE
[Docs] Question about lang.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#19189]
```
threejs\docs\api\zh\**\*.html
threejs\docs\examples\zh\**\*.html
threejs\docs\manual\zh\**\*.html
```

Should be those files change `<html lang="en">` to `<html lang="zh">` .

**Comment by Mugen87** [comment]
I've noticed this in the past too and think this makes sense 👍

**Comment by linbingquan** [comment]
https://github.com/mrdoob/three.js/pull/19190

**Comment by zlf2002171** [comment]
unsubscribe


2020-05-18 

zlf2002171 



发件人：linbingquan <notifications@github.com>
发送时间：2020-04-22 22:52
主题：Re: [mrdoob/three.js] [Docs] Question about lang. (#19189)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

#19190
