### ISSUE TITLE
Issue with MeshToonMaterial and z-order transparency rendering

### ISSUE THREAD

**Issue by andrewplummer** [mrdoob/three.js#19209]
Hello,

I'm noticing an issue with MeshToonMaterial. Under certain occasions the transparency layers will be rendered in incorrect order. This doesn't seem to happen when using other kinds of material. Essentially I have 2 simple meshes that do not intersect and are transparent. It seems that the topmost layer gets rendered first (my understanding is that as a transparent material topmost should be rendered last).

You can repro here: https://github.com/andrewplummer/three-z-order-test

Zoom out and move around a bit and it should look something like this:

<img width="815" alt="Screen Shot 2020-04-24 at 05 17 40 AM" src="https://user-images.githubusercontent.com/74646/80145304-f192e980-85ea-11ea-83ed-e28125ec74ed.png">

Where sometimes it will look like this (expected):

<img width="820" alt="Screen Shot 2020-04-24 at 05 18 13 AM" src="https://user-images.githubusercontent.com/74646/80145381-0e2f2180-85eb-11ea-94d4-7d672ef67c67.png">

Messing with renderOrder can fix, however this becomes rather unmanageable for complex scenes.

Version: r115
Browser: Chrome
OS: Mac OSX 10.15.4

**Comment by Mugen87** [comment]
> This doesn't seem to happen when using other kinds of material.

It actually happens with other materials as well. 

`GLTFLoader` automatically set `depthWrite` to `false` when setting `transparent` to `true`. Doing the same in your code seems to solve the issue.

**Comment by andrewplummer** [comment]
Sorry you're right it does seem to happen with other kinds of material. So you're saying that the correct fix here is to be settings `depthWrite` to `false`? Apologies I know this isn't a help desk but I've been through the docs multiple times as well as SO and other online resources, but no matter what I try `depthWrite` and `renderOrder` are still not behaving in a way that's clear to me. I was using GTLFLoader to make the issue reproducible but I'm actually not using it normally.

https://drive.google.com/file/d/15IRgZ8HF37IoGHN7blpCeBbrh4BKmeDO/view?usp=sharing

This is an example of what I'm trying to accomplish. These are simple geometries all with transparent material being being layered on top of one another. With the default of `depthWrite` as `true` you can see that the objects closer to the camera are being correctly drawn with additive transparency, however as I swivel the camera around the distant objects no longer "stacking" their transparency but instead appear cut out.

Given that I am working with layers and there should be no intersecting geometries (I've made sure of that for the example), does it make sense to always have `depthWrite` off? In the docs it says "When drawing 2D overlays it can be useful to disable the depth writing in order to layer several things together without creating z-index artifacts.", however in my case although the layers themselves could be considered "2D" in the sense that they are always on the same plane, the camera is free to swivel such that some geometries may be closer to the camera. Setting `depthWrite` to `false` does fix this issue however it results in other issues such as some geometries not being rendered at all (difficult to demo here).

It seems that messing with `renderOrder` may be a fix for me, however there are a lot of layers and keeping track of this manually feels like the wrong approach. Also of note: although the camera can pan around, there is a `minPolarAngle` set, so it is not free to show the underside.

**Comment by andrewplummer** [comment]
For more clarity: everything in the video is an extruded geometry and there are multiple geometries resting on top of a very large extruded "floor" geometry underneath. The timemark at 4s shows an example of everything rendering perfectly.
