### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by RaviAtTTN** [mrdoob/three.js#19211]
##### Description of the problem

even by default the crossOrigin is set to anonymous, and the image stored in AWS S3 is allowed for every request from any origin, still I am getting this error while using Texture Loader. 
This case doesn't appears when I hard refresh the page, but when I run it for the first time in my React Application. Can you tell me what's the exact issue with it?

##### Three.js version

- [ ] Dev
- [x] r115
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
Please use the forums (https://discourse.threejs.org/) for help with projects. Thanks!

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Don McCurdy <notifications@github.com>
发送时间：2020-04-24 13:18
主题：Re: [mrdoob/three.js] No 'Access-Control-Allow-Origin' header is present on the requested resource. (#19211)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Closed #19211.
