### ISSUE TITLE
Files exported using DRACOExporter are 3 times the original size

### ISSUE THREAD

**Issue by TejaSwaroopArukoti** [mrdoob/three.js#19216]
##### Three.js version

- [x] Dev
- [x] r115

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

I have imported 'bunny.drc' [94KB] using DRACOLoader and exported using DRACOExporter. 
The new file loads without loosing any geometry but to my surprise, it is 281KB  (almost three times the original file size).

Then, I have tested with other DRC files as well. All exported files are exactly three times the size of original file. 

As a developer, I have debugged and thought issue can be in DRACOExporter.js in below lines.

	
```
                var faces = geometry.getIndex();

		if ( faces !== null ) {

			builder.AddFacesToMesh( mesh, faces.count, faces.array );

		} 
```

   Here, geometry.getIndex() returns 'index' object. 

From official [Google DRACO Project](https://github.com/google/draco#javascript-encoder-api),

```
const numFaces = mesh.indices.length / 3;
const numPoints = mesh.vertices.length;
meshBuilder.AddFacesToMesh(dracoMesh, numFaces, mesh.indices);
```

I have fixed it by below snippet 
       `  builder.AddFacesToMesh( mesh, faces.count, faces.array );`
                    to
         `builder.AddFacesToMesh( mesh, faces.count/3, faces.array );`

Let me know are there any other things I am missing by this?

**Comment by WestLangley** [comment]
Nice find!

`AddFacesToMesh()` is called twice, so there should be two changes required.

Would you like to file a PR to fix both the `/js` and `/jsm` files?

**Comment by TejaSwaroopArukoti** [comment]
Sure. I will a file a PR for two files in `/js` and `/jsm` files.

**Comment by mrdoob** [comment]
Nice find indeed!
