### ISSUE TITLE
GLTFExporter exports the same texture image for all textures.

### ISSUE THREAD

**Issue by prominentdetail** [mrdoob/three.js#19210]
##### Description of the problem

When exporting a gltf file with a material array, using multiple textures. All the texture images output the same image data. The object in the scene in three.js looks fine with all the textures, but opening the exported gltf file will show the same image data for all textures- it appears like only the first image is being used for all textures.

edit: This appears to be a bug with the non-module version. The module version works. Can we get a fix for the non-module version? I've attached a zip containing an application you can run to see for yourself. Just run the index.html file. I've also linked to a jsfiddle below of a module version that runs fine for comparison.

edit2: I don't know if its the texture images or what. Seems like the image data holds each one, but the geometry just utilizes one texture.

##### Three.js version

- [x] r115

##### Browser

- [x] All of them

##### OS

- [x] All of them

##### Hardware Requirements (graphics card, VR Device, ...)
[threeBug.zip](https://github.com/mrdoob/three.js/files/4525927/threeBug.zip)

**Comment by prominentdetail** [comment]
I made an example:
https://jsfiddle.net/jzbq874r/

however, it works fine with the `import { GLTFExporter } from "https://threejs.org/examples/jsm/exporters/GLTFExporter.js";`
but if I modify this to run with the js version (not the jsm module), it won't export correctly.

**Comment by prominentdetail** [comment]
I've added a zip to the original post containing an example application you can run to see for yourself the problem.

**Comment by prominentdetail** [comment]
false alarm.. I was using the wrong version.. I didn't download the r115 version..
Now it works.. x_x

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Alex Hanson-White <notifications@github.com>
发送时间：2020-04-24 08:04
主题：Re: [mrdoob/three.js] GLTFExporter exports the same texture image for all textures. (#19210)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

I've added a zip to the original post containing an example application you can run to see for yourself the problem.
