### ISSUE TITLE
PDBLoader - instanced

### ISSUE THREAD

**Issue by acx70** [mrdoob/three.js#19226]
When you load a molecule which contains a very large amount of atoms ( like : [this one](https://www.rcsb.org/structure/5xnl) ), the loader slows down. 

It would be better to have a version of PDBLoader with THREE.InstancedMesh.

**Comment by Mugen87** [comment]
> It would be better to have a version of PDBLoader with THREE.InstancedMesh.

`PDBLoader` does not build any meshes. It only returns PDB data as an instance of `BufferGeometry`. The example `webgl_loader_pdb` contains the code that creates meshes based on these data. For example the following code section creates a sphere mesh for each atom.

https://github.com/mrdoob/three.js/blob/3c0ec00aa5541332824bdef86fe5a0b4245144de/examples/webgl_loader_pdb.html#L197-L226

Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need help in transforming the example code into a more optimized version.

BTW: Using `THREE.InstancedMesh` is not the only solution. It might make also sense to just merge geometries via [BufferGeometryUtils.mergeBufferGeometries()](https://threejs.org/docs/index.html#examples/en/utils/BufferGeometryUtils.mergeBufferGeometries) .

**Comment by acx70** [comment]
Sorry I still have a lot to learn about three.js and I ended to mixing things up.

BTW: thanks for the hints because I really needed to create a mesh for each atom (even if it does not resolve the problem of TERs not implemented in the PDBLoader).

Since now on I going to use only the forum.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：acx70 <notifications@github.com>
发送时间：2020-04-26 18:33
主题：[mrdoob/three.js] PDBLoader - instanced (#19226)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

When you load a molecule which contains a very large amount of atoms ( like this one: this molecule ), the loader slows down.
It would be better to have a version of PDBLoader with THREE.InstancedMesh.
