### ISSUE TITLE
Hello, may I ask why when we are dealing with clipping

### ISSUE THREAD

**Issue by cgusercom** [mrdoob/three.js#19224]
Hello, may I ask why when we are dealing with clipping, we will convert the plane and vertex to camera coordinates before we decide whether to discard them or not? Is there anything bad if we directly compare the world coordinates?

**Comment by WestLangley** [comment]
It was more efficient to transform one clipping plane to camera space than to transform each texel position to world space.

FYI, this may be useful for your use case: https://github.com/mrdoob/three.js/issues/14463#issuecomment-404598018.

**Comment by cgusercom** [comment]
First of all, thank you for your answer, but it's not what I need. I didn't make it clear myself, but what I want to say is that the clipping shader USES vViewPosition for judgment instead of WorldPosition.

Like this,
vs：
`
varying vec3 vViewPosition;
mvPosition= modelViewMatrix * vec4( position, 1.0 );
vViewPosition=-mvPosition.xyz;
`
fs：
`
varying vec3 vViewPosition;
if ( dot( vViewPosition, plane.xyz ) > plane.w ) discard;
`

The intuitive feeling in my subconscious is that the comparison in world coordinates is ok. When I studied the source code, I found that it was in camera coordinates. I wonder, is there any good in doing this?

**Comment by cgusercom** [comment]
Thank you for your answer. I'll study it

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人："cguser.com" <notifications@github.com>
发送时间：2020-04-27 10:21
主题：Re: [mrdoob/three.js] Hello, may I ask why when we are dealing with clipping (#19224)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Thank you for your answer. I'll study it
