### ISSUE TITLE
GLB transparent animation bug

### ISSUE THREAD

**Issue by lo-th** [mrdoob/three.js#19239]
##### Description of the problem

Hi; sometime with glb model i add full scene 
when i play animation object become transparent and flickering.
problem that appeared recently on dev version of three.
I can't understand where it comes from, if someone has already noticed this problem ?

##### Three.js version

- [X] Dev
- [ ] r115
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by lo-th** [comment]
is only for keyframe animation 
skinning work well

**Comment by lo-th** [comment]
is since new propriety in AnimationClip blendMode: 2500

**Comment by lo-th** [comment]
Find something
is appen when export from blender and disable 
Always Sample Animation

**Comment by Mugen87** [comment]
The model works correctly in [Babylon.js sandbox](https://sandbox.babylonjs.com/) and [gltf-viewer](https://gltf-viewer.donmccurdy.com/) (using `r112`). It also works correctly with this commit a0535a3e1b4eeaacbf22f8bc7c9673efc885c785 which is one of the commits right before #18822 was merged.

/ping @c-morten

**Comment by donmccurdy** [comment]
Note that GLTFLoader uses a custom interpolant (cubic spline) for some animations. The `Always Sample Animation` option in Blender would force linear interpolation, and avoid that custom interpolant. Perhaps it's this interpolation that got broken by the change?

@lo-th if you're avoiding the "Always Sample Animation" option to reduce file size, you may want to consider exporting with sampling, then using [gltfpack](https://github.com/zeux/meshoptimizer/tree/master/gltf) to downsample and reduce file size. Exporting with sampling tends to work better in general, so (while I agree this is a bug), it's worth considering too.

**Comment by lo-th** [comment]
yes i also think is a better option, is enable by default in last blender.   
i also use babylone exporter from 3ds and i don't have any problem

**Comment by Mugen87** [comment]
@mrdoob Should we consider to revert #18822 until this issue is fixed?

**Comment by Mugen87** [comment]
@mrdoob Maybe it's better to revert #18822 until this bug is fixed. IMO, it's somewhat a blocker for `r116`.

**Comment by c-morten** [comment]
I was able to repro this issue and find a fix, it was a one line change to #18822. @mrdoob please advise on next steps I need to take since the PR has been reverted.

**Comment by Mugen87** [comment]
> @mrdoob please advise on next steps I need to take since the PR has been reverted.

The PR was not reverted, it was just a suggestion. Feel free to make a new PR with your change.

**Comment by c-morten** [comment]
Here is the PR with the fix: https://github.com/mrdoob/three.js/pull/19256

**Comment by Mugen87** [comment]
Side note: We should add a `glTF` asset to the repo that uses `GLTFCubicSplineInterpolant`. Or do we already have something appropriate around?

**Comment by donmccurdy** [comment]
I'm pretty sure there are a few, but I'd have to dig into the binary files to figure out which ones. 😅

A unit test on PropertyMixer for custom interpolants might also help avoid this issue in the future.

**Comment by donmccurdy** [comment]
Thanks @c-morten!

**Comment by donmccurdy** [comment]
And thanks @lo-th for the report. :)

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：lo-th <notifications@github.com>
发送时间：2020-04-28 03:37
主题：Re: [mrdoob/three.js] GLB transparent animation bug (#19239)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

yes i also think is a better option, is enable by default in last blender.
i also use babylone exporter from 3ds and i don't have any problem
