### ISSUE TITLE
[Box3.js] Question about default value.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#19230]
https://github.com/mrdoob/three.js/blob/3c0ec00aa5541332824bdef86fe5a0b4245144de/src/math/Box3.js#L40-L45

Why the `.min` default value is not `new Vector3( - Infinity, - Infinity, - Infinity )` and the `.max` default value is not `new Vector3( + Infinity, + Infinity, + Infinity )`.

I think the `.max` is bigger or equal to `.min`, it makes sense. Am I right, maybe I miss some infomation.

**Comment by Mugen87** [comment]
> Why the .min default value is not new Vector3( - Infinity, - Infinity, - Infinity ) and the .max default value is not new Vector3( + Infinity, + Infinity, + Infinity ).

Because in this case you would have an infinitely large bounding volume enclosing the entire 3D space. This is not a good default for an instance of a bounding volume class.

**Comment by linbingquan** [comment]
> Because in this case you would have an infinitely large bounding volume enclosing the entire 3D space. This is not a good default for an instance of a bounding volume class.

This means setting `Box3.min` bigger or equal to `Box3..max` for improve rendering efficiency?

**Comment by Mugen87** [comment]
This has nothing to do with rendering performance. Newly created bounding volumes should be in a state where methods like `containsPoint()` return `false` for any point.

**Comment by linbingquan** [comment]
Thank you, I think it is not necessary (nothing) to change.
