### ISSUE TITLE
Current Typescript type definitions for CubeTexture's mipmaps are not correct

### ISSUE THREAD

**Issue by sirxemic** [mrdoob/three.js#19236]
##### Description of the problem

Currently when I want to set custom mipmaps for a `CubeTexture`, I have to do it this way:

```ts
cubeTexture.mipmaps = mipmaps as unknown as ImageData[]
```

This is because the current type definition of `cubeTexture.mipmaps` is `ImageData[]` even though cube maps also accept `CubeTexture[]` as the mipmap array, [functionally at least](https://threejs.org/examples/?q=mipm#webgl_materials_cubemap_mipmaps).

I was thinking of changing `mipmaps: ImageData[]` to `mipmaps: ImageData[] | CubeTexture[]` in `Texture.d.ts`, because unfortunately we cannot just add `mipmaps: CubeTexture[];` to `CubeTexture.d.ts` (Typescript will complain). It feels like a hack, but I don't see an other way to fix it... I'm wondering how others think about this.

##### Three.js version

- [x] Dev

**Comment by Mugen87** [comment]
> I was thinking of changing mipmaps: ImageData[] to mipmaps: ImageData[] | CubeTexture[] in Texture.d.ts,

I think that sounds appropriate.

**Comment by Mugen87** [comment]
Do you want to make a PR with the change?
