### ISSUE TITLE
Cannot run webXR AR examples on iOS device

### ISSUE THREAD

**Issue by cuinjune** [mrdoob/three.js#19243]
I tried running https://threejs.org/examples/#webxr_ar_cones example on my iPad(iOS 14.4.1).

I tried to run it in XRViewer, Chrome, and Safari but the example's AR button says "WEBXR NOT AVAILABLE".

![IMG_AD4BCF373CEA-1](https://user-images.githubusercontent.com/24947986/80413851-19f63e80-889e-11ea-83fa-69110bf205ef.jpeg)

So is it currently not possible to run webXR (AR) apps on an iOS device?

**Comment by marcofugaro** [comment]
@cuinjune Yes, the WebXR API is available only on Chrome for Android in the time being.

https://caniuse.com/#feat=webxr
