### ISSUE TITLE
mmd loader not play audio in Safari (Mac) and all Browsers (Ios >13)

### ISSUE THREAD

**Issue by tag3r** [mrdoob/three.js#19258]
ex:
https://threejs.org/examples/?q=mmd#webgl_loader_mmd_audio

##### Three.js version

- [ ] Dev
- [x] r115
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

**Comment by Mugen87** [comment]
To sum up the findings of #19259: It seems the problem on Apple devices is caused by the following Webkit issue:

https://stackoverflow.com/questions/58306894/has-ios13-broken-audio-tags-used-as-audio-buffers-connected-to-the-audio-conte

**Comment by tag3r** [comment]
One more question .
why https://threejs.org/examples/webaudio_timing works fine and https://threejs.org/examples/?q=mmd#webgl_loader_mmd_audio don't ?
Both of them used audioloader. I really don't understand. Maybe it some kind of magic ?=))

**Comment by Mugen87** [comment]
Good point. The Webkit issue explains why `webaudio_timing` works but not other Web Audio demos using `audio` tags. `webgl_loader_mmd_audio` can't be affected by this bug. Investigating....

**Comment by Mugen87** [comment]
@tag3r Can you please test #19265? It solves the issue on Safari, macOS.

**Comment by tag3r** [comment]
> @tag3r Can you please test #19265? It solves the issue on Safari, macOS.

yep, it's works fine, thanks

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：tag3r <notifications@github.com>
发送时间：2020-05-01 02:32
主题：Re: [mrdoob/three.js] mmd loader not play audio in Safari (Mac) and all Browsers (Ios >13) (#19258)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

@tag3r Can you please test #19265? It solves the issue on Safari, macOS.
yep, it's works fine, thanks
