### ISSUE TITLE
OBJLoader loads vertex colors incorrectly

### ISSUE THREAD

**Issue by cedemax** [mrdoob/three.js#19254]
##### Description of the problem

The OBJLoader loads vertex colors incorrectly for files with multiple objects, some of which have vertex colors and others not. This becomes an issue if the objects lacking vertex color are not last in the file. 

A smallish example file that reproduces the issue:

[mesh.obj](https://cetopomedia.s3.eu-north-1.amazonaws.com/Media/News/mesh+(26).obj)

![image](https://user-images.githubusercontent.com/22392271/80608941-3500b400-8a40-11ea-99e8-eab648ff88eb.png)

The result looks quite scrambled, and it seems that the second mesh (that has vertex colors, starts using colors after an "offset" (the number of vertices on the first mesh?), and thus this shift causes all colors to be wrong, and the last vertices to become black (no colors left?). 

The blue mesh is the one without colors. 

![image](https://user-images.githubusercontent.com/22392271/80609232-87da6b80-8a40-11ea-960e-5118d5cec4c4.png)
Here is the same file opened in MeshLab, which seems to correctly load such files. 

##### Three.js version

I initially used r89 when i detected this issue, now i migrated to the latest revision to see if it had already been fixed, since the OBJLoader had changed a good deal, but it had not. 

##### Browser

- [x] Chrome
Probably all browsers, can't see how this would be a browser issue

##### OS

- [x] Windows

**Comment by Mugen87** [comment]
This is the result from Sketchfab:

![image](https://user-images.githubusercontent.com/12612165/80613456-9c693480-8a3d-11ea-9ff7-9d1f8a74c570.png)

**Comment by Mugen87** [comment]
OBJ has no official specification document but even in the most referenced ones like [this here](http://paulbourke.net/dataformats/obj/) vertex colors are not specified. Hence, their usage in context of `OBJ` is fragile. 

Can you work with another 3D format like `PLY` or even `glTF`? Both should handle vertex colors more robust.

**Comment by WestLangley** [comment]
More info about Wavefront OBJ: https://www.loc.gov/preservation/digital/formats/fdd/fdd000507.shtml.

**Comment by cedemax** [comment]
> `OBJ` has no official specification document but even in the most referenced ones like [this here](http://paulbourke.net/dataformats/obj/) vertex colors are not specified. Hence, their usage in context of `OBJ` is fragile.
> 
> Can you work with another 3D format like `PLY` or even `glTF`? Both should handle vertex colors more robust.

Yes I can work around the issue easily by just adding vertex colors to the meshes that currently lack them, or I could add such code to the loader that it would assume default color for all vertices, but this would bloat the file. I will look into the other formats, but I like the simplicity of specifying sharp/smooth edges using per face vertex normals in obj.

**Comment by Mugen87** [comment]
The problem is this pattern:
```
o object1
x y z
x y z
x y z
o object2
x y z r g b
x y z r g b
x y z r g b
```
Since the loader manages continuous vertex indices are, the color indices do not match with the vertex indices for the second object. An easy fix is to keep the length of vertex and color arrays equal so the indices are correct again. I'll file a PR so it's easier to see the respective changes.

**Comment by mrdoob** [comment]
Yet another case of... OBJ is definitely not an easy file format.
