### ISSUE TITLE
ObjLoader2 not parsing the last line?

### ISSUE THREAD

**Issue by erbuka** [mrdoob/three.js#19262]
##### Description of the problem

Hi,

As the title says, it seems that the obj parser ignores the last line if LF is missing. I didn't dive deep into the code, I just noticed when loading a simple cube that le last face declared in the file was missing from the loaded mesh. After adding a LF it would load correctly. 

##### Three.js version

- [ ] Dev
- [ ] r115
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by kaisalmen** [comment]
Thanks for spotting the. The parser requires the LF to understand a line is complete when running over the arraybuffer. Before parsing terminates there must be a check if something is left in intermediate storage. I will analyse and let you know.

**Comment by kaisalmen** [comment]
Ok, I have a working fix. PR comes tomorrow. Need to check again I did not brake something. As I suspected the last buffer content is not checked if last character of last line is not LF.
