### ISSUE TITLE
r114 or newer not working on iOS 9.x

### ISSUE THREAD

**Issue by anibarro** [mrdoob/three.js#19267]
Hi,

Since r114 nothing is displayed on the screen when running on iOS 9.x (iPad 2 or iPhone 4S), but with r113 or older works fine.
Example of non-working attached, replace the Threejs version by 110 for example and it works.

Is that intended or a bug?

Thank you!

[r115.zip](https://github.com/mrdoob/three.js/files/4561736/r115.zip)

**Comment by mrdoob** [comment]
I think it's probably https://github.com/mrdoob/three.js/pull/18402#issuecomment-622160914

**Comment by anibarro** [comment]
> I think it's probably [#18402 (comment)](https://github.com/mrdoob/three.js/pull/18402#issuecomment-622160914)

You're right, works again in r116, thank you!

**Comment by WeiFree** [comment]
At last how to fixed it？i have  the same question

**Comment by anibarro** [comment]
> At last how to fixed it？i have the same question

I's working in the latest 116 revision

**Comment by mrdoob** [comment]
Yes, `master` and the latest published package on npm should work.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：anibarro <notifications@github.com>
发送时间：2020-05-09 16:06
主题：Re: [mrdoob/three.js] r114 or newer not working on iOS 9.x (#19267)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

At last how to fixed it？i have the same question
I's working in the latest 116 revision
