### ISSUE TITLE
TypeError: scope.domElement is undefined

### ISSUE THREAD

**Issue by c14180082** [mrdoob/three.js#19276]
error in OrbitControls.js:1102:2

**Comment by Mugen87** [comment]
How are you creating `OrbitControls`? Are you aware that in the latest version the second parameter of `OrbitControls` ctor is mandatory? It seems you creating your instance like
```js
const controls = new THREE.OrbitControls( camera );
```
which is not correct.

**Comment by zlf2002171** [comment]
unsubscribe


2020-05-18 

zlf2002171 



发件人：c14180082 <notifications@github.com>
发送时间：2020-05-02 02:52
主题：Re: [mrdoob/three.js] TypeError: scope.domElement is undefined (#19276)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Closed #19276.
