### ISSUE TITLE
Add more PCD tests?

### ISSUE THREAD

**Issue by brawer** [mrdoob/three.js#19271]
[PCDLoader.js](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/PCDLoader.js) seems to have integrated support for binary compressed PCD from [three-pcd-loader](https://gitlab.com/taketwo/three-pcd-loader/). However, downstream has additional [test files](https://gitlab.com/taketwo/three-pcd-loader/-/tree/master/test/data) that apparently did not get added to the [three.js example models](https://github.com/mrdoob/three.js/tree/dev/examples/models/pcd). Would it make sense to bring those additional test files into three.js codebase? See also [downstream bug report](https://gitlab.com/taketwo/three-pcd-loader/-/issues/1).

**Comment by Mugen87** [comment]
Um, `three.js` already has a test file for each type of PCD file (ASCII, Binary, Binary compressed). I would say this is sufficient for now.

How about adding new test files if bugs occur so it's possible to verify the fix?
