### ISSUE TITLE
Contribution guide is obsolete

### ISSUE THREAD

**Issue by munrocket** [mrdoob/three.js#19279]
##### Description of the problem

* Currently all examples with es modules and `examles/jsm` path
* Contribution guide says that we need to use only `examples/js` folder for new PRs
* Also contribution guide says that better to cover it with examples

*Triggered.*

##### Here two new commits with different styles:
#19156
#19196

Can some native speaker update it temporarily? As I understand current rules is to include two versions.

![](https://habrastorage.org/webt/gm/iw/go/gmiwgogrv4zmbuv60wgz2zbb64c.png)

**Comment by munrocket** [comment]
https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js/_compare/c4c53850fa54993595ec04d78dbd3f9923194337...df4e170349b7cd9d77af4954a6e2c59aa645026a

**Comment by munrocket** [comment]
Fixed for now.

**Comment by DefinitelyMaybe** [comment]
related #19112
