### ISSUE TITLE
Don't blindly create WebGL contexts with { xrCompatible: true }.

### ISSUE THREAD

**Issue by toji** [mrdoob/three.js#19275]
Currently Three is setting the `xrCompatible` context creation arg to `true` for every WebGLRenderer instance, regardless of whether or not the application will have any VR/AR content. This flag is to ensure that the context is created on the graphics adapter that will be powering the XR device (ie: in a multi-GPU system it's often the one that the headset is physically plugged into.)

On many devices, like mobile phones, standalone headsets, and the majority of PCs it will effectively be a no-op because there's only one GPU. On devices like high performance laptops, however, it's possible that setting this flag will cause the entire system to switch over to rendering on a battery hungry discreet GPU rather than a more power efficient integrated GPU. This is probably fine for most XR-oriented experiences and a great many other non-XR WebGL apps, since they're naturally going to want the higher performance, but it's also likely something that developers will want to opt into or out of, similar to how `powerPreference` is currently handled.

(Coincidentally, using `xrCompatible: true` may override any `powerPreference` that the developer set.)

My suggestion would be to have a flag passed into the renderer creation, which then flips the `renderer.xr.enabled = true;` flag for you. If `renderer.xr.enabled` is set to true after a context is created without `xrCompatible` being set it could call `context.makeXRCompatible()` internally, but developers should be aware that this may cause a context loss/restore in the dual GPU case. (That's probably worth a console warning at least.)

**Comment by mrdoob** [comment]
What do you think about calling `gl.makeXRCompatible()` here...

https://github.com/mrdoob/three.js/blob/dev/src/renderers/webxr/WebXRManager.js#L174

**Comment by toji** [comment]
That heavily depends on how good Three is at handling context loss? I'd suggest allowing devs to pass it in at renderer creation time and using `gl.makeXRCompatible()` there only if it wasn't set initially. That'd give developers better control over the overall flow of things.

**Comment by mrdoob** [comment]
I find it strange that the user has to express their intent twice: `new THREE.WebGLRenderer( { xrCompatible: true } )` and `renderer.xr.enabled = true`. I think we can hide this detail in the current design (directly or indirectly triggered by `renderer.xr.enable`).

Question: If we call `gl.makeXRCompatible()`, will `gl.getContextCreationAttributes().xrCompatible` return `true`?

**Comment by mkeblx** [comment]
With the general parameter-passed-to-renderer solution & PR, you wouldn't have to express twice. The `renderer.xr.enabled = true` would be redundant and removed from all examples/docs. Just pass param, and include AR/VRButton.js etc.

**Comment by mrdoob** [comment]
Hmm...

So the current way to enable xr is to call `renderer.xr.enabled = true`. You are proposing removing `renderer.xr.enabled = true` and making users update their code and call `new THREE.WebGLRenderer( { xrCompatible: true } )` instead.

I think I am missing something.

**Comment by Mugen87** [comment]
> You are proposing removing renderer.xr.enabled = true

BTW: It's necessary to enable/disable XR for RTT. A parameter-only approach does not work.

https://github.com/mrdoob/three.js/blob/89438bb39cde275ed1024fdb527b3ed75bdae68b/examples/jsm/objects/Reflector.js#L167-L178

**Comment by toji** [comment]
> Question: If we call `gl.makeXRCompatible()`, will `gl.getContextCreationAttributes().xrCompatible` return `true`?

It should, yes.

> BTW: It's necessary to enable/disable XR for RTT.

Good to know! I don't see any reason to remove `renderer.xr.enabled`, but having it set initially based on the parameter seems sensible.

**Comment by mkeblx** [comment]
Yes I saw that used by Reflector.js/Water.js, etc and removed from examples only.

I'm not sure how to exactly handle the make compatible case. I'm leaning towards it not being needed as it's an edge case (multi-GPU) that can be handled by correctly passing `xrCompatible` parameter. Perhaps just a warning log.

Chromium `makeXRCompatible` behavior doesn't implement spec currently:
https://bugs.chromium.org/p/chromium/issues/detail?id=876140
https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/modules/webgl/webgl_rendering_context_base.cc#L820

**Comment by toji** [comment]
> Chromium makeXRCompatible behavior doesn't implement spec currently

Technically it's current implementation is valid, just not optimal. There's work from Microsoft happening to fix that, though, which is exactly what prompted this request. :) Once that change is landed anything marked as `xrCompatible` will be able to switch GPUs when needed, so we only want it used for XR-enabled content.

**Comment by mrdoob** [comment]
How about this?

```diff
diff --git a/src/renderers/webxr/WebXRManager.js b/src/renderers/webxr/WebXRManager.js
index 883111998..dbeb69e63 100644
--- a/src/renderers/webxr/WebXRManager.js
+++ b/src/renderers/webxr/WebXRManager.js
@@ -182,6 +182,12 @@ function WebXRManager( renderer, gl ) {
 
 			var attributes = gl.getContextAttributes();
 
+			if ( attributes.xrCompatible !== true ) {
+
+				gl.makeXRCompatible();
+
+			}
+
 			var layerInit = {
 				antialias: attributes.antialias,
 				alpha: attributes.alpha,
```

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Brandon Jones <notifications@github.com>
发送时间：2020-05-14 02:14
主题：Re: [mrdoob/three.js] Don't blindly create WebGL contexts with { xrCompatible: true }. (#19275)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Chromium makeXRCompatible behavior doesn't implement spec currently
Technically it's current implementation is valid, just not optimal. There's work from Microsoft happening to fix that, though, which is exactly what prompted this request. :) Once that change is landed anything marked as xrCompatible will be able to switch GPUs when needed, so we only want it used for XR-enabled content.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Michael Blix <notifications@github.com>
发送时间：2020-05-13 08:03
主题：Re: [mrdoob/three.js] Don't blindly create WebGL contexts with { xrCompatible: true }. (#19275)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Yes I saw that used by Reflector.js/Water.js, etc and removed from examples only.
I'm not sure how to exactly handle the make compatible case. I'm leaning towards it not being needed as it's an edge case (multi-GPU) that can be handled by correctly passing xrCompatible parameter. Perhaps just a warning log.
Chromium makeXRCompatible behavior doesn't implement spec currently:
https://bugs.chromium.org/p/chromium/issues/detail?id=876140
https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/modules/webgl/webgl_rendering_context_base.cc#L820

**Comment by toji** [comment]
That happens when you first access `renderer.xr`, right? That works, but it seems like if you didn't set the context creation flag your intent would be to delay this as long as necessary, so this might be a bit premature? I'd think that when the session is being set or when `renderer.xr.enabled` is set to `true` might be more timely, but I could be missing some architectural reason why that's not desirable.

**Comment by mkeblx** [comment]
It's not in `WebXRManager` constructor but in `setSession` which looks like an appropriate place to put in.

Is this meant to be a backup for developers who forgot to set the `xrCompatible` parameter or an intentional flow of "on a dual GPU system I want the non-VR GPU to be used for reason X, until user jumps into XR then I want to switch GPU"?

**Comment by mrdoob** [comment]
> Is this meant to be a backup for developers who forgot to set the `xrCompatible` parameter

It's meant to shield the users of having to know yet one more thing (`xrCompatible`) 😇
