### ISSUE TITLE
lerp vs slerp clamping inconsistency

### ISSUE THREAD

**Issue by speigg** [mrdoob/three.js#19285]
Just noting that the Vector `lerp` methods are unclamped (which is maximally useful), whereas the Quaternion `slerp` methods are clamped (which limits their usefulness).

It would be clearer if both of these interpolation methods were unclamped, or (if more appropriate), explicitly unclamped variations were introduced (e.g., `lerpUnclamped` and `slerpUnclamped`). There is some prior discussion around this  (see #17035).

**Comment by speigg** [comment]
Actually, after taking a closer look at the source, it seems it's just `Quaternion.rotateTowards` that is clamped, which internally uses `Quaternion.slerp`. In which case, I should be able to use `slerp` directly to avoid the clamping.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Gheric Speiginer <notifications@github.com>
发送时间：2020-05-03 07:56
主题：Re: [mrdoob/three.js] lerp vs slerp clamping inconsistency (#19285)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Closed #19285.
