### ISSUE TITLE
WebGLRenderer: move uniforms refresh logic to WebGLMaterials

### ISSUE THREAD

**Issue by taphos** [mrdoob/three.js#19292]
##### Description of the problem

I am implementing a custom Renderer and I would like to make it compatible with builtin Materials and Object types. Currently it is very hard to do without copy-pasting a large parts existing WebGLRenderer, as it contains alot of logic not directly related to rendering.

i.e. material uniform refresh logic could be moved to separate helper WebGLMaterials, so it can be shared between Renderers

##### Three.js version

- Dev

**Comment by WestLangley** [comment]
I think the reason for not doing that was to keep the renderer logic from polluting the materials. three.js supports multiple renderers.

Related: #18399.

**Comment by taphos** [comment]
@WestLangley I see, 
but this makes it hard to make custom materials and custom renderers

I.e. custom material uniform refresh logic must be added to renderer, would be much easier just to make it part of material itself, without changing renderer.

On the other hand renderer is currently aware of all materials, means all renderers must include the refresh logic for each material.

**Comment by WestLangley** [comment]
Yes, three.js has "built-in" materials, and non-built-in materials.

There are a number of pull requests related to this topic. I updated my post above with another link.

This decision is up to @mrdoob.

**Comment by taphos** [comment]
@WestLangley thanx for the update
Do I understand it correctly that material Uniforms are WebGL specific, thats why uniforms refresh should not be in materials?

**Comment by Mugen87** [comment]
> Do I understand it correctly that material Uniforms are WebGL specific, thats why uniforms refresh should not be in materials?

When I remember correctly, that was the main reason for not doing this change.

**Comment by taphos** [comment]
@Mugen87 how about moving it to WebGL specific helper WebGLUniforms?
So the refresh logic could be reused by other webgl-based renderers?
Was it discussed?

**Comment by Mugen87** [comment]
> Was it discussed?

AFAIK no. But `WebGLUniforms` is no good place for this logic since the class should not have any knowledge about materials. It just takes care about the actual WebGL uniform update calls and the respective caching.

**Comment by taphos** [comment]
> `WebGLUniforms` is no good place for this logic

Hm. How about creating a `WebGLMaterials` helper for that?

**Comment by mrdoob** [comment]
> Hm. How about creating a `WebGLMaterials` helper for that?

That sound good to me 👌

**Comment by taphos** [comment]
Updated title and description accordingly

**Comment by taphos** [comment]
https://github.com/mrdoob/three.js/pull/19304

**Comment by pailhead** [comment]
>I.e. custom material uniform refresh logic must be added to renderer, would be much easier just to make it part of material itself, without changing renderer.

>On the other hand renderer is currently aware of all materials, means all renderers must include the refresh logic for each material.

Is this new, or am i misinterpreting something? I never had to refresh uniforms when working with custom shaders OR when modifying built in shaders, yet i've seen this approach appear lately. I even refactored the GLTF loader not to do this. How does this become a problem going from kinda "fire and forget" when mutating shader uniforms?

**Comment by taphos** [comment]
>I never had to refresh uniforms when working with custom shaders

Example: I would like to have a global (or per scene/model..) parameter, which would influence all materials on change. 
As threejs doesnt have a concept of global uniforms, like i.e. Unity, current solution is traversing all existing materials and changing uniforms manually each time global parameter is changed. This is slow and ugly. 

Refreshing uniforms before rendering would be a better solution, currently not possible for custom materials.

**Comment by taphos** [comment]
> ` const __foo = outside_object.bar || __bar.get(outside_object)`

Something similar we already discussed here #19305 , the `componentOverrides`

**Comment by taphos** [comment]
> when you say "each" material, you're referring to each webgl related material?

I dont really understand what is non-webgl material? I havent seen threejs used without webgl, and I didnt know it is possible.

**Comment by pailhead** [comment]
I'm not sure. `ShaderMaterial` is most definitely a WebGL material, but i didn't think of it when i said "**each** material". What i mean by each is basic, phong, lambert, pbr, pbr2, pbr3... etc etc. 
I also do not understand the needs of uniform refreshing. I know that i can have a scene rendering with `ShaderMaterial` alone and with an arbitrary number of uniforms with arbitrary names. From what i've seen in this and related issues, it's a bunch of code that is aware of `map`, `specular` , `alpha`, `shininess` `metalness` (my favorite!). 
My assumption is that it's way more optimal to render one of these with these known paths, than it is the shader material, otherwise, why is there a problem of refreshing specific uniforms when the renderer seems to resolve arbitrary uniforms when provided by SM. 

Anway, to solve your problem posted above:

```

const myGlobalUniforms  = {
  uMyGlobalParameter : { value: new THREE.Vector4() } //eg
}

const myOnBeforeCompile = shader=>{
  shader.uniforms.uMyGlobalParameter = myGlobalUniforms.uMyGlobalParameter //reference a single source
  shader.vertexShader = `
    uniform vec4 uMyGlobalParameter
    ${ shader.vertexShader }

  shader.vertexShader.replace( 'something', myGLSL } 
}

scene.traverse( o=>{
  if( o.material ) {
    o.onBeforeCompile = myOnBeforeCompile
  }
})
```

The trick is to modify the shader, which is quite tricky. For example you can look for the final `}` if you want to add something after `gl_FragColor` like `gl_FragColor.xyz *= myAO;`. Otherwise you can replace shader chunks.
