### ISSUE TITLE
Some kind of a depth buffer regression from 114

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#19302]
##### Description of the problem

I've submitted a depth peel example a while back: https://github.com/mrdoob/three.js/pull/15312
This example depends on this proposal https://github.com/mrdoob/three.js/pull/15490

So i'm not sure if this counts as a regression since i don't have a meaningful case without using this proposal, but i'd like to point it out regardless, and inquire about what work happened in this area.

This demo runs on r98 and the proposal and everything runs fine. Up to r113 i can apply this diff and get the same behavior:

R113:
![peel113](https://user-images.githubusercontent.com/4681282/81050287-94155d00-8e74-11ea-9c8b-cfe081fa55e8.PNG)

When bumping to R114, the framerate remains, but i get some depth artifacts:
![peel114](https://user-images.githubusercontent.com/4681282/81050313-a0011f00-8e74-11ea-8cd6-7310ffd6a7c6.PNG)

In the dev branch, my frame rate drops tremendously, and i've oddly traced it down to an ordinary render call that happens after all this crazy depth peeling logic, and before the results are shown on the screen. I can actually even render the results with no frame drop, its just when i try to render a partial normal scene in the process, it really goes down. 

![image](https://user-images.githubusercontent.com/4681282/81050592-10a83b80-8e75-11ea-9cfb-bea66b337a9d.png)

Ie. this is caused by

```
function complexRenderLogic (){
  // gl stencil stuff
  // gl mask stuff
  // scene overrides
  // many renderer.render( X, Y )
  // many renderer.setRenderTarget( foo )
}

function displayResult(){
  renderer.render( full_screen_quad_scene, camera)
}

function render(){
  complexRenderLogic()
  renderer.render( scene, camera ) // <----- FRAME RATE DROP`
  displayResult()
}
```

Please let me know if additional information is needed. I could serve the demo with r113, r114 and dev. If this is of no interest since it's appearing in something thats using a proposal, i'd appreciate it if you could point me in some direction where some recent changes could have affected this. Thank you.

##### Three.js version

- [X] Dev
- [X] r116
- [X] r115
- [X] r114

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by pailhead** [comment]
The specles are caused by `unpackRGBAtoDepth` with something like:

```
float prevDepth = unpackRGBAToDepth(texture2D(uPrevDepthTexture,screenPos));
if(prevDepth + uDepthOffset - gl_FragCoord.z >= 0. ){
     discard;
}
```
Where `uDepthOffset` can be `0.0` up to r113, but then starts to cause specles.

**Comment by mrdoob** [comment]
Would be great if you could isolate what commit in r114 broke your example.

**Comment by WestLangley** [comment]
A reasonable guess is #18696.

**Comment by pailhead** [comment]
Yes, this seems like the culprit. @WestLangley any ideas about these stalling calls? I've never encountered them before.

**Comment by WestLangley** [comment]
I expect you should avoid saving depth to a texture having a lower precision -- if that is, in fact, what you are doing.

**Comment by pailhead** [comment]
Sorry, i'm realizing now that this is completely unrelated to the depth stuff. The issue i was having was due to the PR you linked (thanks!). This other issue is in a different version, ill investigate better and open a new one.
