### ISSUE TITLE
Blender model not loading due to skipping texture warning

### ISSUE THREAD

**Issue by mishael17** [mrdoob/three.js#19306]
I'm new to animation and three.js. I used a model from mixamo which works perfectly fine. But when I import the mixamo model and add some key frames without making any other changes to the model, export it as .fbx file and use it in the code, the model does not load. I get the following errors.

**Errors:**
FBXLoader.js:3301 THREE.FBXLoader: FBX binary version: 7400
**FBXLoader.js:665 THREE.FBXLoader: SpecularFactor map is not supported in three.js, skipping texture.**
(anonymous) @ FBXLoader.js:665
parseParameters @ FBXLoader.js:609
parseMaterial @ FBXLoader.js:501
parseMaterials @ FBXLoader.js:470
parse @ FBXLoader.js:171
parse @ FBXLoader.js:147
(anonymous) @ FBXLoader.js:99
(anonymous) @ three.module.js:36216
load (async)
load @ three.module.js:36194
load @ FBXLoader.js:95
init @ howw.html:75
(anonymous) @ howw.html:32
**FBXLoader.js:665 THREE.FBXLoader: ShininessExponent map is not supported in three.js, skipping texture.**
(anonymous) @ FBXLoader.js:665
parseParameters @ FBXLoader.js:609
parseMaterial @ FBXLoader.js:501
parseMaterials @ FBXLoader.js:470
parse @ FBXLoader.js:171
parse @ FBXLoader.js:147
(anonymous) @ FBXLoader.js:99
(anonymous) @ three.module.js:36216
load (async)
load @ three.module.js:36194
load @ FBXLoader.js:95
init @ howw.html:75
(anonymous) @ howw.html:32
**FBXLoader.js:665 THREE.FBXLoader: SpecularFactor map is not supported in three.js, skipping texture.**
(anonymous) @ FBXLoader.js:665
parseParameters @ FBXLoader.js:609
parseMaterial @ FBXLoader.js:501
parseMaterials @ FBXLoader.js:470
parse @ FBXLoader.js:171
parse @ FBXLoader.js:147
(anonymous) @ FBXLoader.js:99
(anonymous) @ three.module.js:36216
load (async)
load @ three.module.js:36194
load @ FBXLoader.js:95
init @ howw.html:75
(anonymous) @ howw.html:32
**FBXLoader.js:665 THREE.FBXLoader: ShininessExponent map is not supported in three.js, skipping texture.**
(anonymous) @ FBXLoader.js:665
parseParameters @ FBXLoader.js:609
parseMaterial @ FBXLoader.js:501
parseMaterials @ FBXLoader.js:470
parse @ FBXLoader.js:171
parse @ FBXLoader.js:147
(anonymous) @ FBXLoader.js:99
(anonymous) @ three.module.js:36216
load (async)
load @ three.module.js:36194
load @ FBXLoader.js:95
init @ howw.html:75
(anonymous) @ howw.html:32
**FBXLoader.js:665 THREE.FBXLoader: SpecularFactor map is not supported in three.js, skipping texture.**
(anonymous) @ FBXLoader.js:665
parseParameters @ FBXLoader.js:609
parseMaterial @ FBXLoader.js:501
parseMaterials @ FBXLoader.js:470
parse @ FBXLoader.js:171
parse @ FBXLoader.js:147
(anonymous) @ FBXLoader.js:99
(anonymous) @ three.module.js:36216
load (async)
load @ three.module.js:36194
load @ FBXLoader.js:95
init @ howw.html:75
(anonymous) @ howw.html:32
**FBXLoader.js:665 THREE.FBXLoader: ShininessExponent map is not supported in three.js, skipping texture.**
(anonymous) @ FBXLoader.js:665
parseParameters @ FBXLoader.js:609
parseMaterial @ FBXLoader.js:501
parseMaterials @ FBXLoader.js:470
parse @ FBXLoader.js:171
parse @ FBXLoader.js:147
(anonymous) @ FBXLoader.js:99
(anonymous) @ three.module.js:36216
load (async)
load @ three.module.js:36194
load @ FBXLoader.js:95
init @ howw.html:75
(anonymous) @ howw.html:32
**FBXLoader.js:665 THREE.FBXLoader: SpecularFactor map is not supported in three.js, skipping texture.**
(anonymous) @ FBXLoader.js:665
parseParameters @ FBXLoader.js:609
parseMaterial @ FBXLoader.js:501
parseMaterials @ FBXLoader.js:470
parse @ FBXLoader.js:171
parse @ FBXLoader.js:147
(anonymous) @ FBXLoader.js:99
(anonymous) @ three.module.js:36216
load (async)
load @ three.module.js:36194
load @ FBXLoader.js:95
init @ howw.html:75
(anonymous) @ howw.html:32
**FBXLoader.js:665 THREE.FBXLoader: ShininessExponent map is not supported in three.js, skipping texture.**
(anonymous) @ FBXLoader.js:665
parseParameters @ FBXLoader.js:609
parseMaterial @ FBXLoader.js:501
parseMaterials @ FBXLoader.js:470
parse @ FBXLoader.js:171
parse @ FBXLoader.js:147
(anonymous) @ FBXLoader.js:99
(anonymous) @ three.module.js:36216
load (async)
load @ three.module.js:36194
load @ FBXLoader.js:95
init @ howw.html:75
(anonymous) @ howw.html:32
**FBXLoader.js:665 THREE.FBXLoader: SpecularFactor map is not supported in three.js, skipping texture.**
(anonymous) @ FBXLoader.js:665
parseParameters @ FBXLoader.js:609
parseMaterial @ FBXLoader.js:501
parseMaterials @ FBXLoader.js:470
parse @ FBXLoader.js:171
parse @ FBXLoader.js:147
(anonymous) @ FBXLoader.js:99
(anonymous) @ three.module.js:36216
load (async)
load @ three.module.js:36194
load @ FBXLoader.js:95
init @ howw.html:75
(anonymous) @ howw.html:32
**FBXLoader.js:665 THREE.FBXLoader: ShininessExponent map is not supported in three.js, skipping texture.**
(anonymous) @ FBXLoader.js:665
parseParameters @ FBXLoader.js:609
parseMaterial @ FBXLoader.js:501
parseMaterials @ FBXLoader.js:470
parse @ FBXLoader.js:171
parse @ FBXLoader.js:147
(anonymous) @ FBXLoader.js:99
(anonymous) @ three.module.js:36216
load (async)
load @ three.module.js:36194
load @ FBXLoader.js:95
init @ howw.html:75
(anonymous) @ howw.html:32
**FBXLoader.js:665 THREE.FBXLoader: SpecularFactor map is not supported in three.js, skipping texture.**
(anonymous) @ FBXLoader.js:665
parseParameters @ FBXLoader.js:609
parseMaterial @ FBXLoader.js:501
parseMaterials @ FBXLoader.js:470
parse @ FBXLoader.js:171
parse @ FBXLoader.js:147
(anonymous) @ FBXLoader.js:99
(anonymous) @ three.module.js:36216
load (async)
load @ three.module.js:36194
load @ FBXLoader.js:95
init @ howw.html:75
(anonymous) @ howw.html:32
**FBXLoader.js:665 THREE.FBXLoader: ShininessExponent map is not supported in three.js, skipping texture**.
(anonymous) @ FBXLoader.js:665
parseParameters @ FBXLoader.js:609
parseMaterial @ FBXLoader.js:501
parseMaterials @ FBXLoader.js:470
parse @ FBXLoader.js:171
parse @ FBXLoader.js:147
(anonymous) @ FBXLoader.js:99
(anonymous) @ three.module.js:36216
load (async)
load @ three.module.js:36194
load @ FBXLoader.js:95
init @ howw.html:75
(anonymous) @ howw.html:32
3FBXLoader.js:1882 THREE.FBXLoader: Vertex has more than 4 skinning weights assigned to vertex. Deleting additional weights

**Comment by Mugen87** [comment]
> export it as .fbx file and use it in the code, the model does not load.

Can you please try to export to `glTF` instead.

**Comment by mishael17** [comment]
@Mugen87 Thanks. I will definitely try that.
