### ISSUE TITLE
Scene is distorted until the mouse is moved on Firefox

### ISSUE THREAD

**Issue by bbarn3y** [mrdoob/three.js#19311]
On Firefox my three.js scene is completely distorted until I move the mouse somewhere on the site.

You can see the nature of the distortion on the image below:
![image](https://user-images.githubusercontent.com/8375284/81155233-037a7200-8f85-11ea-9d70-fd07f5582c44.png)

When I move the mouse, the scene suddenly pops and everything is fine. It doesn't seem to matter where exactly the cursor is within the site, it doesn't have to be over the canvas where my scene is rendered.
This is how the scene looks after moving the mouse:
![image](https://user-images.githubusercontent.com/8375284/81155916-bb0f8400-8f85-11ea-890e-61b36b3733db.png)

The following three.js related dependencies are used:

- "three": "^0.108.0"
- "three-orbitcontrols": "^2.102.2",
- "three.meshline": "^1.2.0"

I tried updating three to the latest version (0.116.1), but that didn't solve the issue either. I only managed to replicate this issue on Firefox, works perfectly on Chrome and Edge.

##### Three.js version

- [ ] Dev
- [x] r116

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Edge

Couldn't replicate the issue on Chrome or Edge, only Firefox. My Firefox version is 75.0.

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

Only tested on Windows.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：bbarn3y <notifications@github.com>
发送时间：2020-05-06 16:50
主题：[mrdoob/three.js] Scene is distorted until the mouse is moved on Firefox (#19311)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

On Firefox my three.js scene is completely distorted until I move the mouse somewhere on the site.
You can see the nature of the distortion on the image below:

When I move the mouse, the scene suddenly pops and everything is fine. It doesn't seem to matter where exactly the cursor is within the site, it doesn't have to be over the canvas where my scene is rendered.
This is how the scene looks after moving the mouse:

The following three.js related dependencies are used:
"three": "^0.108.0" 
"three-orbitcontrols": "^2.102.2", 
"three.meshline": "^1.2.0" 
I tried updating three to the latest version (0.116.1), but that didn't solve the issue either. I only managed to replicate this issue on Firefox, works perfectly on Chrome and Edge.
Three.js version
 Dev 
 r116 
Browser
 All of them 
 Chrome 
 Firefox 
 Edge 
Couldn't replicate the issue on Chrome or Edge, only Firefox. My Firefox version is 75.0.
OS
 All of them 
 Windows 
 macOS 
 Linux 
 Android 
 iOS 
Only tested on Windows.
