### ISSUE TITLE
Problem with Shadows: GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 0

### ISSUE THREAD

**Issue by PaulSlocum** [mrdoob/three.js#19317]
##### Description of the problem

`[.WebGL-0x7fee3a016200]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 0`

I'm getting the above error in the console, but I'm having a difficult time tracking it down or reducing it to a simple example.  It seems to be a problem with the shadow map renderer because I get garbage or missing shadows when the error occurs, and the error goes away if I turn shadows off.  Most of the objects have correct shadows, but a few of them have broken shadows that look like the shadow camera had garbage vertex data.

In this screenshot the sphere shadows are correct, but the cube shadows don't make any sense:

![badShadows](https://user-images.githubusercontent.com/244341/81341084-cf2ab280-9065-11ea-85df-a28ee734e401.jpg)

My program overall is pretty simple: it loads one GLTF model from Blender, has a particle system that only uses only three unmodified primitives (SphereGeometry, BoxGeometry, and ConeGeometry), and it has an environment cube that's also a BoxGeometry.  It's all worked great for 2 months, but for some reason when I finally added one more primitive shape to the particle system like TorusGeometry or CylinderGeometry, then I start getting the error above and messed up shadows.  

I have two custom shaders, but disabling them didn't have any effect.  Substantially reducing the complexity of my Blender model and reducing the number of particles didn't seem to have any effect (the most particles I've used is 200).  The only way I've found to stop the problem is to turn off the casting or receiving of shadows, or to just turn off the shadow map entirely.

My working project is linked below, and I get the error consistently after a few seconds in Chrome (81.0.4044.122) and Safari (12.1.2) on MacOS (10.14.6).  I'm using r116 but it also happens with r115 and dev: 

http://www.qotile.net/3dplayer/

Source is here:
https://github.com/PaulSlocum/3dplayer

I'm willing to work to reduce this issue to a simpler example, but I could use a little help narrowing it down.  Thanks!

##### Three.js version

- [x] Dev
- [x] r116
- [x] r115

##### Browser

- [ ] All of them
- [x] Chrome  (I've only tried Chrome and Safari)
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS  (I've only tried MacOS)
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
The warning `glDrawArrays: attempt to access out of range vertices in attribute 0` often indicates a user error. Meaning you are trying to render a buffer which is too small compared to the actual draw call. Something like this can easily happen in particle systems.

Anyway, can you please try to use the `BufferGeometry` versions of the geometry generators (e.g. `SphereBufferGeometry` instead of `SphereGeometry`? Using `BufferGeometry` is better for startup performance anyway.

If this issue is really related to shadows, can you please also try to demonstrate the problem with a smaller piece of code? Unfortunately, your app and the glTF asset are very complex so it's hard to get an overview of your app.

**Comment by PaulSlocum** [comment]
Thank you for the response.  Would you mind elaborating a bit on your first paragraph?  What kind of user error would cause this error message aside from actually manipulating geometry or vertex buffers?  I just thought that everything I was doing with three.js was a full level of abstraction above that.  My particle system just adds and removes simple sphere and cube meshes to/from the scene, and I don't have that many particles (less than 200).

Switching everything to BufferGeometry seems to have stopped or at least suppressed the error and shadow problems for now.  I'll probably just close this issue unless I discover new information or find a simple way to reproduce it (especially since I've seen talk of deprecating the non-buffer geometries) but I'd appreciate any additional details you can provide since I'm still not totally clear what mechanism was causing the error to appear.

**Comment by Mugen87** [comment]
>  My particle system just adds and removes simple sphere and cube meshes to/from the scene, and I don't have that many particles (less than 200).

Okay, not after studying your code it seems the error is unrelated to your particle system.

It would be still good if you were able to reproduce the issue in a smaller test case. Until then, closing the issue for now.
