### ISSUE TITLE
Safari requestAnimationFrame slow performance vs. setInterval / setTimeout

### ISSUE THREAD

**Issue by dustinkerstein** [mrdoob/three.js#19322]
_FYI, this appears to be a WebKit / Safari issue and not directly related to Three.js - https://bugs.webkit.org/show_bug.cgi?id=211624 but I wanted to post here for informational purposes. Feel free to close this as you see fit._

https://jsfiddle.net/wxe5pk8c utilizes Three.js and video seeking using a file with 100% I-Frames. You can switch between requestAnimationFrame, setAnimationLoop, and setInterval by setting animationStrategy to 1,2,3, respectively.

Note that as this JSFiddle uses iFrames, you'll need to click into the result iFrame to get Safari to avoid using its low power mode (meant for ads) which limits rendering to 30fps.

Below are average framerates from various devices I have tested:

1st Gen iPad Pro

   requestAnimationFrame: 55fps
   setAnimationLoop: 55fps
   setInterval: 60fps

2011 Macbook Pro

   requestAnimationFrame: 3fps
   setAnimationLoop: 3fps
   setInterval: 60fps

2019 Macbook Pro

   requestAnimationFrame: 60fps
   setAnimationLoop: 60fps
   setInterval: 60fps

##### Three.js version
- Tested on 92, 105, and 110

##### Browser
- [x] Safari

##### OS
- [x] macOS
- [x] iOS

**Comment by dustinkerstein** [comment]
Quick update - This can be replicated on many of the Three.js examples (not just the somewhat esoteric video seeking example above). Try https://threejs.org/examples/#webgl_interactive_cubes_gpu and switch from `requestAnimationFrame` to `setInterval` - I see around a 10-15fps difference on both my iPad Pro and older Macbook Pro.

**Comment by Mugen87** [comment]
Further infos here: https://discourse.threejs.org/t/safari-webgl-issues-with-video-playback-and-requestanimationframe-performance/15452
