### ISSUE TITLE
how to use toJSON ?

### ISSUE THREAD

**Issue by pisyell** [mrdoob/three.js#19324]
##### Description of the problem

When I use loader's result  toJSON, and then use the loader.parse (JSON) model map to lose and the elements in the model are disordered

##### Browser
- [81.0.4044.129 ] Chrome
##### OS
- [ 10] Windows

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：pisyell <notifications@github.com>
发送时间：2020-05-09 11:11
主题：[mrdoob/three.js] how to use toJSON ? (#19324)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Description of the problem
When I use loader's result toJSON, and then use the loader.parse (JSON) model map to lose and the elements in the model are disordered
Three.js version 0.111.0
Browser
[81.0.4044.129 ] Chrome 
OS
[ 10] Windows
