### ISSUE TITLE
fxaa goes on and off

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#19331]
I have a hardware-browser combo here where fxaa goes on and off all the time, but I have no knowledge of its inner workings to debug it:

![Screen Shot 2020-05-10 at 12 29 46 ](https://user-images.githubusercontent.com/242577/81496821-c2eb6300-92ba-11ea-8100-879b732abee4.png)

If you tell me what kind of test could I do to help to resolve this, I will.

**Comment by munrocket** [comment]
Have you tried other browsers?

**Comment by makc** [comment]
@munrocket I could try other 3D libs, too. will it solve my problem?

**Comment by munrocket** [comment]
Looks like a bug in window.devicePixelRatio(), you can try to set ratio=1-4

**Comment by makc** [comment]
devicePixelRatio is always 1 - what kind of bug could be there

**Comment by makc** [comment]
I think I am going to close this for now as there are other issues not related to fxaa, it is not clear what is up with 3js and that browser

**Comment by zlf2002171** [comment]
unsubscribe


2020-05-18 

zlf2002171 



发件人：makc <notifications@github.com>
发送时间：2020-05-11 15:11
主题：Re: [mrdoob/three.js] fxaa goes on and off (#19331)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Closed #19331.
