### ISSUE TITLE
Preload/prefetch in examples

### ISSUE THREAD

**Issue by munsocket** [mrdoob/three.js#19336]
##### Description of the problem

Pretty sure that examples not teach us for the best practice and should be fixed.
We downloading resources only after Three.js was loaded.

![](https://aws1.discourse-cdn.com/standard17/uploads/threejs/original/2X/a/a0ca747f9b27614245f2f1c0faa892ff661d8da0.png)

We should investigate this problem and fix it. HTTP/2 support parallel download.

https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content
https://developers.google.com/web/fundamentals/performance/http2

**Comment by donmccurdy** [comment]
It's kind of a complexity tradeoff between having the examples be simple to understand and having them be fully optimized as if they were standalone apps. If you load textures with `THREE.TextureLoader`, you have to wait until the three.js script is loaded. If you load them any other way, it is more complicated. An example or two of preloading might be good, but I don't know if I'd rewrite every example this way.

**Comment by makc** [comment]
@donmccurdy but it is worth next o nothing to add those link tags

**Comment by donmccurdy** [comment]
You mean it costs next to nothing, correct?

For images, ok. I'm not sure if those tags are going to work with 3D models if browsers don't recognize the media types, but would be curious to find out.

**Comment by makc** [comment]
I`d think as=fetch should work for the models:
![Screen Shot 2020-05-11 at 7 32 43 ](https://user-images.githubusercontent.com/242577/81527105-b702ae00-9359-11ea-98ea-fe2b4d275c84.png)

**Comment by donmccurdy** [comment]
Missed that option, nice! Ok, that does sound pretty easy.

**Comment by munrocket** [comment]
Probably for images also “fetch”, because I get warnings in console.

**Comment by munrocket** [comment]
@Mugen87 why you set thumbs up on first comment? Obviously current solution it's a bad practice and can be fixed in 1-2 line.

**Comment by munrocket** [comment]
@donmccurdy can I push this into all examples? It's working.

Here an [example](https://rawcdn.githack.com/munrocket/three.js/ab8ec09c9824166e569f4ea1472ef2b3318022cd/examples/index.html).

**Comment by makc** [comment]
@munrocket how do you collect the list of files it loads? with some headless browser script?

**Comment by munrocket** [comment]
No, just `jimp`  + `jimp/blit`

**Comment by makc** [comment]
I mean the files you are going to PR here. There could be gltf files, bin files, obj files, jpeg files, dds files, etc in every example, and with hundreds of them it would suck to go over every example by hand

**Comment by donmccurdy** [comment]
@munrocket could you make a PR that updates just one example (for now) preloading both textures and models? Let's see what that looks like.

**Comment by munrocket** [comment]
@makc doesn’t thought about this yet.

Here two questions:
How different browser support this?
Doesn't they download resources twice?

Second question is tricky, nobody will see any error.

**Comment by makc** [comment]
what I see here is firefox not reporting the preload, but when actual request happens, it loads fast. chrome does load it twice, and it complains if the rquest does not happen within short time after the page was loaded.

**Comment by munrocket** [comment]
@makc All is ok for me in Chrome.

![](https://habrastorage.org/webt/su/9h/js/su9hjspsrndoymkdj7h5jwwcyki.png)

Here another [link](https://munrocket.github.io/three.js/examples/)

**Comment by makc** [comment]
> could you make a PR that updates just one example (for now) preloading both textures and models? Let's see what that looks like.

here goes #19483 / [live link](https://rawcdn.githack.com/mrdoob/three.js/a44f67f02345d4cd132788ffa9b7c481fce30208/examples/webgl_animation_skinning_blending.html) - note the glb file is now the 1st thing that gets loaded:
![Screen Shot 2020-05-28 at 4 40 09 ](https://user-images.githubusercontent.com/242577/83092442-977bbd00-a09d-11ea-9c10-85d6d387d2c4.png)

**Comment by munrocket** [comment]
As we checked in #19483 it's a good opportunity to improve loading speed (~200ms on simple project and even more on a complex one). But we blocked by bug in webkit, I make a bug report here https://bugs.webkit.org/show_bug.cgi?id=213683

**Comment by Mugen87** [comment]
Because of the findings in #19483 and for simplicity reasons, let's keep `rel="preload"` and `async` out the example.
