### ISSUE TITLE
Documentation search on client [proposal]

### ISSUE THREAD

**Issue by munrocket** [mrdoob/three.js#19342]
Related Issues: #13025 and #19038

Here I propose an algorithm of future documentation search that can be used on clients.
We can build before each release the data structure called [trie](https://en.wikipedia.org/wiki/Trie), save it on a documentation server (/docs/files.js) and then use it as finite-state machine on a client to quickly get a result. All of the additional dependency for release build we can store in own pakage.json in /build/ folder.

![](https://habrastorage.org/webt/-c/gw/gq/-cgwgqztz_3igdqscmlsjxhdoxy.png)

Prototype: https://pastebin.com/3hXnVA7v

I am drop it here because I don't want to get rejected PR and probably somebody will take it for implementation.

**Comment by looeee** [comment]
Possibly we could use [lunr.js](https://lunrjs.com/) rather than creating our own system. I think that would be pretty easy to set up.

**Comment by munrocket** [comment]
Looks interesting, we have 303 file in /en/ and articles stored in .html.

**Comment by munrocket** [comment]
lunr.js ~3500 line of code and store pre-build index
trie-search ~390 line of code and store state machine for each article
suffix-tree ~200 line of code but finished for pages

They have different algorithms definitely, lunr based on words and score system.

**Comment by munrocket** [comment]
To complex to compare, we can just benchmark it.

**Comment by munrocket** [comment]
![](https://habrastorage.org/webt/vy/t0/7w/vyt07wubjt2ih9bnlm2dlx6vsdu.png)
They [exists](https://github.com/nextapps-de/flexsearch)

**Comment by donmccurdy** [comment]
Would this mean downloading the text content of all ~300 documentation pages to the browser when any page of documentation is loaded? Or potentially `300 * k` if the trie index adds some overhead? That cost seems like more of a problem than the relative speed of the search. 😕

**Comment by munrocket** [comment]
Yep you right here, looks like an overhead in memory consumption.
We can search only a headers and bold text.

But do we actually need this?
I realized that request `textureloader site:https://threejs.org/docs/` in google search works well.

**Comment by munrocket** [comment]
Feels like if we have a search button, we need to make it better. I will leave this issue here as a list of ideas and small prototype.

**Comment by looeee** [comment]
> Would this mean downloading the text content of all ~300 documentation pages to the browser when any page of documentation is loaded

For lunr.js, an `index.json` file is generated. I previously tested this out with my book, and the generated file was pretty small (around 50kb, uncompressed). I have fewer pages but a lot more words than the docs, so I'm not sure how that would compare to the results here. 

All you include with each page is `index.json` and `lunr.min.js` (29kb) plus whatever extra logic is required to connect that to the docs, which should be fairly simple. 

One complication is all the `[name]`,  `[page:Light Light]` etc. throughout the docs. I'm not sure how we can handle those. I guess we could somehow run the index generator on the live pages after the `[name]` stuff has been replaced. @munrocket could puppeteer be used for that?

**Comment by munrocket** [comment]
Interesting. I did not know about JS in the docs, yes.
```js
await page.$eval('#my-id', e => e.innerText);
await page.$eval('#my-id', e => e.innerHTML);
```

**Comment by looeee** [comment]
@munrocket thanks for the list of JS search libraries. I didn't see [flexsearch](https://github.com/nextapps-de/flexsearch) before, it looks promising.

**Comment by munrocket** [comment]
![](https://habrastorage.org/webt/8m/kx/pv/8mkxpv5hqtqn8ft4hj5kvasec4o.png)
FlexSearch much better.
After creating an integer index I get 1.3MB of serializated .json data.

**Comment by looeee** [comment]
Could you test lunr.js as well? I'd say that the speed is less important than the index.json size. 
At least, I've used lunr.js powered search before and never noticed any delay in getting results. 
Also, is there any way to tune the index so that, for example, you get fewer results but smaller size? 

By the way, any idea how these will handle the Chinese docs?

**Comment by munrocket** [comment]
Usually Lunr gives more reliable score system out of the box.
But Flexsearch is flexible and can be 0.5MB in size with `new FlexSearch('memory')` initialization.
Here results:
```
Flexsearch
size: 555065
time(ms): 0.8701920062303543
[
  'docs/api/en/math/Color.html',
  'docs/api/en/core/Raycaster.html',
  'docs/api/en/math/Ray.html',
  'docs/examples/en/math/convexhull/ConvexHull.html',
  'docs/api/en/renderers/webxr/WebXRManager.html',
  'docs/api/en/core/Object3D.html',
  'docs/api/en/textures/DataTexture.html',
  'docs/manual/en/introduction/Useful-links.html',
  'docs/api/en/animation/AnimationAction.html',
  'docs/api/en/core/BufferAttribute.html',
  'docs/api/en/core/BufferGeometry.html',
  'docs/api/en/objects/Mesh.html',
  'docs/api/en/objects/Points.html',
  'docs/api/en/objects/Sprite.html',
  'docs/manual/en/introduction/How-to-run-things-locally.html'
]
Lunr
size: 1051914
time(ms): 3.0550110042095184
[
  'docs/api/en/core/Raycaster.html',
  'docs/api/en/math/Ray.html',
  'docs/examples/en/math/convexhull/ConvexHull.html',
  'docs/api/en/renderers/webxr/WebXRManager.html',
  'docs/api/en/lights/DirectionalLight.html',
  'docs/api/en/objects/Points.html',
  'docs/api/en/objects/Sprite.html',
  'docs/api/en/objects/Mesh.html',
  'docs/api/en/lights/shadows/DirectionalLightShadow.html',
  'docs/api/en/core/Object3D.html'
]
SEARCHED: ray
```

```
Flexsearch
size: 555065
time(ms): 0.7363520041108131
[
  'docs/api/en/core/Object3D.html',
  'docs/api/en/textures/Texture.html',
  'docs/manual/en/introduction/Matrix-transformations.html'
]
Lunr
size: 1051914
time(ms): 2.3225070014595985
[
  'docs/manual/en/introduction/Matrix-transformations.html',
  'docs/api/en/helpers/CameraHelper.html',
  'docs/api/en/helpers/HemisphereLightHelper.html',
  'docs/api/en/helpers/SpotLightHelper.html',
  'docs/api/en/helpers/DirectionalLightHelper.html',
  'docs/api/en/helpers/PointLightHelper.html',
  'docs/examples/en/helpers/VertexNormalsHelper.html',
  'docs/examples/en/helpers/VertexTangentsHelper.html',
  'docs/examples/en/helpers/FaceNormalsHelper.html',
  'docs/api/en/textures/Texture.html',
  'docs/api/en/core/Object3D.html'
]
SEARCHED: matrixAutoUpdate
```

```
Flexsearch
size: 555065
time(ms): 0.7589409947395325
[
  'docs/api/en/cameras/PerspectiveCamera.html',
  'docs/examples/en/utils/SkeletonUtils.html',
  'docs/api/en/audio/AudioListener.html',
  'docs/api/en/cameras/ArrayCamera.html',
  'docs/api/en/cameras/OrthographicCamera.html',
  'docs/api/en/constants/Renderer.html',
  'docs/api/en/extras/core/Curve.html',
  'docs/api/en/extras/core/CurvePath.html',
  'docs/api/en/materials/LineBasicMaterial.html',
  'docs/api/en/materials/MeshBasicMaterial.html',
  'docs/api/en/materials/MeshLambertMaterial.html',
  'docs/api/en/materials/MeshPhongMaterial.html',
  'docs/api/en/materials/MeshStandardMaterial.html',
  'docs/api/en/materials/MeshToonMaterial.html',
  'docs/manual/en/introduction/Animation-system.html',
  'docs/manual/en/introduction/How-to-dispose-of-objects.html'
]
Lunr
size: 1051914
time(ms): 1.6449149996042252
[]
SEARCHED: matri
```

**Comment by looeee** [comment]
OK, thanks for checking that out. Flexsearch.js looks better than lunr from those examples. 

@mrdoob what do you think about adding client-side search using Flexsearch.js? It would involve adding flexsearch.min.js (6.6kb) + index.json (~500kb) to the docs.

**Comment by munrocket** [comment]
Here script with generator: https://pastebin.com/FVY8V4DW
And here a worker that search results: https://pastebin.com/aS6FPvcv

After generating data and adding some lines in the end of `/docs/index.html`
```js
var worker = new Worker( 'searchWorker.js' );
worker.onmessage = function( e ) {
        if ( e.data.msg == 'result' ) {
	        console.log( e.data.result );
        }
};
worker.postMessage( {
	msg: 'search',
	str: 'Float32Array'
} );
```
It's possible to try how it works in console.

**Comment by GmBodhi** [comment]
I'll create a pr. I'm testing something locally (tell me if someone has already made a pr for this [not a closed one])

**Comment by Mugen87** [comment]
@GmBodhi Before making a PR we should first clarify if the additional complexity of a more advanced search is wanted. I don't think this was decided yet.

**Comment by GmBodhi** [comment]
It's is necessary, as the bot([Three.js Helper]()) needs to search the methods and props. 
My suggestion is that dynamically generate the `list.json`.

**Comment by GmBodhi** [comment]
I've generated a new [`list.json`](https://1drv.ms/u/s!Anjkicy8SUsDgZJKzNAEIPsmdud6Wg?e=0zxroy) (213 KB). Where there are (url, methods, props) for each base key.


> @GmBodhi Before making a PR we should first clarify if the additional complexity of a more advanced search is wanted. I don't think this was decided yet.

**Comment by GmBodhi** [comment]
![image](https://user-images.githubusercontent.com/71921036/115141555-afb04e00-a05a-11eb-80de-b111937780c7.png)
Making something like this will be cumbersome for sure. So we need to hide it I guess.
@Mugen87

**Comment by marcofugaro** [comment]
@GmBodhi good job making that `list.json`! The approach is similar to [files.json](https://github.com/mrdoob/three.js/blob/dev/examples/files.json).
However, since this is generated, the script should be included in the three.js codebase as well.

Here is how it should work on the frontend, this was discussed in https://github.com/mrdoob/three.js/pull/19038.

1. All properties and methods are hidden by default in the documentation sidebar.
2. When the user types, the properties/methods that match what the user is typing should appear. It's cleaner to not repeat the class name (`Animation`) but rather indent the property/method to make it clear its parent.

Here is a mockup:

<img src="https://user-images.githubusercontent.com/7217420/79513908-4790eb80-8045-11ea-82e9-379e4cb9d9c8.png" width="300" />

**Comment by GmBodhi** [comment]
Well, this is my suggestion. The new `list.json` will be helpful to the `Three.js-Helper bot` for validating methods and props without fetching the docs page.

**Comment by GmBodhi** [comment]
>All properties and methods are hidden by default in the documentation sidebar.
>When the user types, the properties/methods that match what the user is typing should appear. It's cleaner to not repeat the class name (Animation) but rather indent the property/method to make it clear its parent......

It'll be better if we query the methods/props only when the user input has a `#` or a `.` (**in terms of performance**).
When I tried to query them all together, it took a while. 
So it'll be better if we use `.find` or something to get the Class and then query the methods/props with the part after `(#|.)`

**Comment by marcofugaro** [comment]
Shouldn't be, judging by your file there are ~3500 between method/properties tops. Doing a loop of 3500 entries should be pretty fast.

**Comment by CodyJasonBennett** [comment]
We have a pretty performant successor of my proposal (which implements @marcofugaro's mockup) in #22542.

**Comment by munrocket** [comment]
@CodyJasonBennett I think regex not scalable.

You could write Github Action .yml script that makes PR with file that was generated by FlexSearch. Here [reference](https://github.com/narze/THIS_REPO_HAS_2848_STARS) how to make it.

**Comment by Mugen87** [comment]
Both PRs #21674 and #22562 introduce a noticeable complexity and make maintenance harder. 

`three.js` has a custom implementation for its documentation. Not using template with auto generation from JSDoc means less dev dependencies. On the other hand it's not possible to have all features from a generated documentation without writing complex code. I do not vote to do that. We want to write a 3D engine and not a documentation library or template. Hence, I suggest to close this issue and both PRs and just accept the current limitations.
