### ISSUE TITLE
Safari video-based textures aren't updating when using high resolution source

### ISSUE THREAD

**Issue by dustinkerstein** [mrdoob/three.js#19343]
_FYI, as with the somewhat related #19322, this issue appears to be a WebKit / Safari issue and not directly related to Three.js - https://bugs.webkit.org/show_bug.cgi?id=211750 but I wanted to post here for informational purposes. Feel free to close this as you see fit._

See here for a Three.js demo - https://jsfiddle.net/yj9vpfkr - Depending on a device's capabilities, the texture update won't complete before the next render loop which results in frozen frames. Strangely on iOS when this issue appears, sometimes touching the screen will force a texture refresh. And further, on iOS, the severity of this issue can be reduced by using setInterval (which overlaps with issue #19322).

Note that as this JSFiddle uses iFrames, you'll need to click into the result iFrame to get Safari to avoid using its low power mode (meant for ads) which limits rendering to 30fps.

You can use the video.playbackRate control to fine-tune the threshold where the frames stop updating. On my first gen iPad Pro, the video plays perfectly at 0.5, starts to play erratically at 0.75, and is almost entirely frozen at 1.0

##### Three.js version
Tested on 92, 105, and 110

##### Browser
- [x] Safari

##### OS
- [x] macOS
- [x] iOS

**Comment by Mugen87** [comment]
Further infos here: https://discourse.threejs.org/t/safari-webgl-issues-with-video-playback-and-requestanimationframe-performance/15452
