### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by PRAKHAR-bit** [mrdoob/three.js#19356]
Upon uploading the mtl file
newmtl unposedgament
ka 0.329412 0.223529 0.027451
kd 0.780392 0.568627 0.113725
ks 0.992157 0.941176 0.807843
illum 0
map_Ka unposedgament.jpg
map_Kd unposedgament.jpg
map_Ks unposedgament.jpg

I get a rendering in which my whole model is just black . no depth just black.

But using on meshjs.net i get depths and the object loads fine(though without textures and I cant figure out why)

i am using chrome web browser.

**Comment by mrdoob** [comment]
Please, use the [forum](https://discourse.threejs.org/) or the [chat](https://discord.gg/HF4UdyF) for help.

**Comment by WestLangley** [comment]
For the record, I do not believe `MTLLoader` supports `illum 0` (un-lit), or `illum 1` (Lambert) materials.
