### ISSUE TITLE
Negative coordinate can not be used in vrml model

### ISSUE THREAD

**Issue by gaorongfu** [mrdoob/three.js#19361]
##### Description of the problem
I write a test file with Rhino 7 and export as vrml file . when I use VRMLLoader to load it, many errors raised as below:
column: 26
length: 1
line: 29
message: "unexpected character: ->-<- at offset: 376, skipped 1 characters."
offset: 376

and the lines in vrml file around line 29 is :
coord DEF Line02-COORD Coordinate { point [
          -1.284 0 0.3363, -0.938 0 0.6823, -0.1168 0 0.6822, 0.1549 0 0.9538, 
          0.4757 0 0.9538, 0.7828 0 0.6465, 0.7828 0 -0.2076, 
          0.5859 0 -0.4011, 0.5859 0 -0.9949, 0.255 0 -1.326, 
          -1.284 0 -1.326, -1.284 0.8661 0.3363, -0.938 0.8661 0.6823, 
          -0.1168 0.8661 0.6822, 0.1549 0.8661 0.9538, 0.4757 0.8661 0.9538, 
          0.7828 0.8661 0.6465, 0.7828 0.8661 -0.2076, 0.5859 0.8661 -0.4011, 
          0.5859 0.8661 -0.9949, 0.255 0.8661 -1.326, -1.284 0.8661 -1.326, 
          1.165 0 -0.9862, 1.165 0 -0.5913, 1.665 0 -0.09973, 
          1.665 0 0.5683, 2.109 0 1.013, 2.715 0 1.013, 3.163 0 0.5642, 
          3.163 0 -1.326, 1.504 0 -1.326, 1.165 0.8661 -0.9862, 
          1.165 0.8661 -0.5913, 1.665 0.8661 -0.09973, 1.665 0.8661 0.5683, 
          2.109 0.8661 1.013, 2.715 0.8661 1.013, 3.163 0.8661 0.5642, 
          3.163 0.8661 -1.326, 1.504 0.8661 -1.326, -1.284 0 3.45, 
          3.163 0 3.45, 3.163 0 2.47, 2.815 0 2.123, 2.028 0 2.123, 
          1.698 0 2.454, -0.5289 0 2.454, -0.7179 0 2.265, -1.284 0 2.265, 
          -1.284 0.8661 3.45, 3.163 0.8661 3.45, 3.163 0.8661 2.47, 
          2.815 0.8661 2.123, 2.028 0.8661 2.123, 1.698 0.8661 2.454, 
          -0.5289 0.8661 2.454, -0.7179 0.8661 2.265, -1.284 0.8661 2.265]
        }

Since the negative coordinate is unavoidable in some case, could the VRMLLoader support it ?

**Comment by gaorongfu** [comment]
[zx.zip](https://github.com/mrdoob/three.js/files/4631715/zx.zip)

**Comment by WestLangley** [comment]
Your `.wrl` file loads for me without errors using the three.js example.

![Screen Shot 2020-05-14 at 9 20 37 PM](https://user-images.githubusercontent.com/1000017/82001522-57422680-9629-11ea-8fc5-7c0d104deb68.png)

**Comment by gaorongfu** [comment]
Oo, sorry , I use the origin example file add test ok just now. It maybe something wrong in my code. Thanks very much.

**Comment by Mugen87** [comment]
Phew! 😅

**Comment by gaorongfu** [comment]
[floor3.zip](https://github.com/mrdoob/three.js/files/4641582/floor3.zip)
Attach file is which I exported with 3dMax，same exception reoccured.

**Comment by Mugen87** [comment]
The problem in your VRML file is these node name: `Line010-FACES` and `Line010-COORD`. Both contain the `-` sign. According to the [specs](http://gun.teipir.gr/VRML-amgem/spec/part1/concepts.html#SyntaxBasics), this character is not allowed in node names. 

When I remove the minus sign the file loads without issues. Seems to be an exporter issue to me.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：gaorongfu <notifications@github.com>
发送时间：2020-05-15 09:34
主题：Re: [mrdoob/three.js] Negative coordinate can not be used in vrml model (#19361)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Oo, sorry , I use the origin example file add test ok just now. It maybe something wrong in my code. Thanks very much.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：WestLangley <notifications@github.com>
发送时间：2020-05-15 09:29
主题：Re: [mrdoob/three.js] Negative coordinate can not be used in vrml model (#19361)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Your .wrl file loads for me without errors using the three.js example.

**Comment by zlf2002171** [comment]
unsubscribe


2020-05-18 

zlf2002171 



发件人：Michael Herzog <notifications@github.com>
发送时间：2020-05-18 16:33
主题：Re: [mrdoob/three.js] Negative coordinate can not be used in vrml model (#19361)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

The problem in your VRML file is these node name: Line010-FACES and Line010-COORD. Both contain the - sign. According to the specs, this character is not allowed in node names.
When I remove the minus sign the file loads without issues. Seems to be an exporter issue to me.

**Comment by gaorongfu** [comment]
Thx a lot! the vrml file is exported by 3dmax 2021, and I have not modified anything. It seemed I should change the node name when export everytimes.
