### ISSUE TITLE
raycaster.intersectObjects() return null

### ISSUE THREAD

**Issue by amjackfan** [mrdoob/three.js#19364]
##### Description of the problem

Hi mrdoob, I use GltfRoader road a gltfmodel  and I want to use raycaster.intersectObject() to pick the node in glt view.  but it return null, the Group  type object of Gltf form which roaded in scene can not support the raycaster? only mesh ? but how could I do that?

var intersects = raycaster.intersectObjects(scene.children）

##### Three.js version

- [ ] Dev
- [-] r116
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help reqeusts.
