### ISSUE TITLE
Using Material.onBeforeCompile on multiple materials causes cache conflicts

### ISSUE THREAD

**Issue by pwmarcz** [mrdoob/three.js#19377]
##### Description of the problem

Creating multiple materials using `onBeforeCompile` breaks when the source code of `onBeforeCompile` is exactly the same.

It looks like the compiled programs are cached based on the `onBeforeCompile` source code (looking at `material.program.cacheKey`).

Here is an example:

* [jsfiddle](https://jsfiddle.net/5b6zndjh/7/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/401w8dbu/) (dev branch)

The `makeMaterial` function is supposed to create two different materials (based on parameters), but the two objects render in the same color.

As a workaround, redefining `material.defines` works. In the above example, adding the following line to `makeMaterial` fixes the issue and makes the two object render differently:

    material.defines = {'FOO': ''+r};

I realize that it might not be so easy to disambiguate the two materials, but maybe this could be documented as part of `Material.onBeforeCompile`?

##### Three.js version

- [x] Dev
- [x] r116

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Can you please check if #17567 would solve your issue?

**Comment by pwmarcz** [comment]
Yes, it would! I would just add a short warning to the description of `onBeforeCompile` as well.

**Comment by Mugen87** [comment]
> I would just add a short warning to the description of onBeforeCompile as well.

You mean to the documentation so this behavior becomes more clear, right?

**Comment by pwmarcz** [comment]
> I would just add a short warning to the description of onBeforeCompile as
> well.
>
> You mean to the documentation so this behavior becomes more clear, right?
>
Yes.

>

**Comment by zlf2002171** [comment]
unsubscribe


2020-05-18 

zlf2002171 



发件人：Paweł Marczewski <notifications@github.com>
发送时间：2020-05-17 21:04
主题：Re: [mrdoob/three.js] Using Material.onBeforeCompile on multiple materials causes cache conflicts (#19377)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

> I would just add a short warning to the description of onBeforeCompile as
> well.
>
> You mean to the documentation so this behavior becomes more clear, right?
>
Yes.

**Comment by sjpt** [comment]
Can't the cache use the results of the shader code as substituted by onBeforeCompile as (part of) the key in the case of non-trivial onBeforeCompile? That would have an overhead of long keys, but only in the case where onBeforeCompile was used, and would not burden the coder with the need for customProgramCacheKey.

Also would not burden the user with wasted debug time from the current unexpected behaviour. He would eventually find the relevant changed documentation (as I eventually found this issue thread) and be able to fix the code, but only after some time.
