### ISSUE TITLE
Feature Request: Merge utils funtion together and export them.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#19388]
Merge `src\utils.js` into `src\math\MathUtils.js`, `arrayMax` and `arrayMin` is simple and useful.

```js
src\utils.js => src\math\MathUtils.js
```

But I am not sure it is better, because of `arrayMin`, it is not be referenced in three.js source code, it can be Tree-Shaking when rollup building code.

https://github.com/mrdoob/three.js/blob/b79dec9d74664e035cc52b641d8991c63906ce12/src/utils.js#L5

**Comment by Mugen87** [comment]
> arrayMax and arrayMin is simple and useful.

Both functions are no math helpers so I don't think it's correct to put them in `MathUtils`. They are only used in context of determining the type of the index buffer attribute. I see them as on part of the public API. Hence, I think it's better if they are not exposed.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：linbingquan <notifications@github.com>
发送时间：2020-05-18 17:18
主题：Re: [mrdoob/three.js] Feature Request: Merge utils funtion together and export them. (#19388)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Closed #19388.
