### ISSUE TITLE
WebXR implementation is capped at two views

### ISSUE THREAD

**Issue by Manishearth** [mrdoob/three.js#19387]
##### Description of the problem

https://github.com/mrdoob/three.js/blob/f76e149e681cdf33a16623248376c04a1038dae7/src/renderers/webxr/WebXRManager.js#L31-L43##### Three.js version

This code caps the webxr implementation at two views.

However, the webxr spec [allows for any number of views!](https://immersive-web.github.io/webxr/#views)

CAVE displays will have a high number of views. Within head-mounted displays, "first person observer" views for AR capture exist (e.g. on the Hololens 2), as well as "bionic displays" on the Varjo VR-2.

The camera object should perhaps preallocate two cameras but append additonal cameras as more views are discovered.

(I came across this issue after implementing the "first person observer" view for Hololens 2 in Servo and had to patch threejs to be able to run demos)

- [x] Dev
- [ ] r116
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Manish Goregaokar <notifications@github.com>
发送时间：2020-05-18 15:08
主题：[mrdoob/three.js] WebXR implementation is capped at two views (#19387)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Description of the problem
https://github.com/mrdoob/three.js/blob/f76e149e681cdf33a16623248376c04a1038dae7/src/renderers/webxr/WebXRManager.js#L31-L43##### Three.js version
This code caps the webxr implementation at two views.
However, the webxr spec allows for any number of views!
CAVE displays will have a high number of views. Within head-mounted displays, "first person observer" views for AR capture exist (e.g. on the Hololens 2), as well as "bionic displays" on the Varjo VR-2.
The camera object should perhaps preallocate two cameras but append additonal cameras as more views are discovered.
(I came across this issue after implementing the "first person observer" view for Hololens 2 in Servo and had to patch threejs to be able to run demos)
 Dev 
 r116 
 ... 
Browser
 All of them 
 Chrome 
 Firefox 
 Internet Explorer 
OS
 All of them 
 Windows 
 macOS 
 Linux 
 Android 
 iOS 
Hardware Requirements (graphics card, VR Device, ...)

**Comment by mrdoob** [comment]
> (I came across this issue after implementing the "first person observer" view for Hololens 2 in Servo and had to patch threejs to be able to run demos)

Where can I read more about that?

**Comment by Manishearth** [comment]
https://microsoft.github.io/OpenXR-MixedReality/openxr_preview/specs/openxr.html#XR_MSFT_first_person_observer_preview

**Comment by Manishearth** [comment]
I've also filed https://github.com/immersive-web/webxr/issues/1045 to have more information about such views in the spec itself

**Comment by mrdoob** [comment]
It would be nice if the WebXR spec could help with frustum culling somehow.

Right now we create a single frustum so we don't do the frustum culling pass twice. This works when both cameras are pointing the the same direction but would break in the CAVE case.

This 3rd person view seems to also complicate things.

**Comment by Manishearth** [comment]
The third person view in most cases is a secondary view that cannot see things that left/right cannot, so culling should not be an issue.

**Comment by asajeffrey** [comment]
A case when we'd need this is recording 360 video from webxr content. This is implemented in Servo, by rendering the webxr using six views which are the faces of a cubemap, then post-processing via gstreamer. An example is at https://www.youtube.com/watch?v=74mX-FB4FdA

In order to do this, I modified three.js to hard-wire six cameras rather than two, but ideally that shouldn't be necessary! One wrinkle is that in webxr you don't know how many views there are until you begin a session, so the three.js cameras can't be allocated until the session is created.

See also https://twitter.com/mrdoob/status/1284340064521199618 :smile:

**Comment by Manishearth** [comment]
Oh, an update:

The spec now [talks about this explicitly](https://immersive-web.github.io/webxr/#primary-and-secondary-views). There is now a `"secondary-views"` feature that can be used to opt in to extra views showing up. Threejs should be tweaked to handle `views > 2` and set the `"secondary-views"` optional feature unconditionally.

As @asajeffrey mentions you'll need to handle this anyway for rendering to non-binocular systems like CAVE systems and cubemap rendering. These are not considered secondary views and may be surfaced even if the feature isn't requested.

**Comment by mrdoob** [comment]
So seems like in order to cull only once we'll have to parse the frustums for each view provided by the WebXR API every frame. Is that correct?

**Comment by asajeffrey** [comment]
@mrdoob yeah, at the moment webxr doesn't provide any data about the views saying whether or not they can share culling. Moreover the relative transforms between the views are allowed to change every frame, even though for most devices they don't change much (or indeed at all).

**Comment by Manishearth** [comment]
@mrdoob You can cache it though.


But this is already the case, you can change the frustum of a view by e.g. changing IPD on the oculus using the slider.

**Comment by mrdoob** [comment]
> @mrdoob You can cache it though.

Hmm, how? Does the view have an id?

**Comment by Manishearth** [comment]
Oh, no it doesn't.

**Comment by BryanChrisBrown** [comment]
Hey all! Just wanted to chime in here! The multi-view spec of WebXR is super useful for next gen 3D displays like the [The Looking Glass](https://lookingglassfactory.com/portrait) https://github.com/kainino0x and @brianpeiris worked on a WebXR prototype that works really well with threejs

The general WebXR project is here: 

https://github.com/kainino0x/holoplay-webxr

And the threejs fixes made are here: 

https://github.com/kainino0x/holoplay-webxr/issues/9#issuecomment-955620666

I’d be happy to help facilitate/turn this into a PR if it looks good to you all :)

**Comment by mrdoob** [comment]
A PR would be great indeed 👍

**Comment by BryanChrisBrown** [comment]
just updating here, but we've got a Pull Request ready that should work for this! https://github.com/mrdoob/three.js/pull/23972
