### ISSUE TITLE
LWOLoader: better handling of metalness with transparency and opacity

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#19383]
Copied from https://github.com/threejs/lwoloader/issues/30, initially reported by @onthez:

> Near line 667, when attributes.transparent && attributes.opacity < 0.999
Currently the behavior is to use the transparency from the Lightwave material as the opacity.
If refraction does not equal 1, then attributes.opacity should be set to 1.
opacity fades out the refraction. 1 is almost always a closer visual result to the material settings from Lightwave in these cases.

> Also just a few lines down, near 679, when attributes.metalness !== undefined
Currently the behavior is to delete the metalness attribute.

> A better handling of this case is to set
attributes.metalness = 1;

**Comment by Mugen87** [comment]
Should be fixed via #22776.
