### ISSUE TITLE
LWOLoader: should set material.morphtargets automatically

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#19384]
Copied from https://github.com/threejs/lwoloader/issues/29, initially reported by @onthez:

> If an object is loaded with morphTargets, it would be ideal if they were enabled.

> if(typeof object.morphTargetDictionary !== 'undefined') { material.morphTargets = true; }

**Comment by Mugen87** [comment]
This issue can be closed since `morphTargets` and `morphNormals` have been removed.
