### ISSUE TITLE
LWOLoader: Roughness value should equal 1 when material.roughnessMap is not null

### ISSUE THREAD

**Issue by looeee** [mrdoob/three.js#19381]
Copied from https://github.com/threejs/lwoloader/issues/28, initially reported by @onthez:

> I notice that when a roughnessMap is used, the roughness value remains at 0 so the map is effectively disabled.

> When a roughnessMap is present, roughness should default to 1

> Thanks!

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Lewy Blue <notifications@github.com>
发送时间：2020-05-18 09:26
主题：[mrdoob/three.js] LWOLoader: Roughness value should equal 1 when material.roughnessMap is not null (#19381)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Copied from threejs/lwoloader#28, initially reported by @onthez:
I notice that when a roughnessMap is used, the roughness value remains at 0 so the map is effectively disabled.
When a roughnessMap is present, roughness should default to 1
Thanks!

**Comment by Mugen87** [comment]
Should be fixed via #22776.
