### ISSUE TITLE
THREE.FBXLoader: Cannot find the version number for the file given

### ISSUE THREAD

**Issue by MwStar** [mrdoob/three.js#19382]
##### Description of the problem

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/hyok6tvj/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/c5m1kazu/) (dev branch)

##### Three.js version

- r116

##### Browser

- Chrome

##### OS

- macOS

##### Hardware Requirements (graphics card, VR Device, ...)

react, typeScript
import { FBXLoader } from 'three/examples/jsm/loaders/FBXLoader';
class Three extends Component<any, any> {
...
...
...
const fbx_loader: any = new FBXLoader(manager);
fbx_loader.load('./9.fbx', function (object: any) {_this.scene.add(object);}, onProgress, onError)
}

**Comment by looeee** [comment]
Can you share the FBX file here?

**Comment by zlf2002171** [comment]
unsubscribe


2020-05-18 

zlf2002171 



发件人：Lewy Blue <notifications@github.com>
发送时间：2020-05-18 14:41
主题：Re: [mrdoob/three.js] THREE.FBXLoader: Cannot find the version number for the file given (#19382)
收件人："mrdoob/three.js"<three.js@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Can you share the FBX file here?

**Comment by MwStar** [comment]
I have solved this problem, please close it




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lewy Blue"<notifications@github.com&gt;; 
发送时间: 2020年5月18日(星期一) 下午2:40
收件人: "mrdoob/three.js"<three.js@noreply.github.com&gt;; 
抄送: "&amp;#x1F433;小尾巴"<2397560398@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mrdoob/three.js] THREE.FBXLoader: Cannot find the version number for the file given (#19382)





 
Can you share the FBX file here?

**Comment by MwStar** [comment]
```
import { FBXLoader } from 'three/examples/jsm/loaders/FBXLoader';
class Three extends Component<any, any> {
...
...
...
const fbx_loader: any = new FBXLoader(manager);
fbx_loader.load('./9.fbx', function (object: any) {_this.scene.add(object);}, onProgress, onError)
}
```
改为：
```
import { FBXLoader } from 'three/examples/jsm/loaders/FBXLoader';
const path = require('./9.fbx')
class Three extends Component<any, any> {
...
...
...
const fbx_loader: any = new FBXLoader(manager);
fbx_loader.load(path, function (object: any) {_this.scene.add(object);}, onProgress, onError)
}
```
