### ISSUE TITLE
WebGLRenderTarget: Null texture in shader texture Uniform

### ISSUE THREAD

**Issue by MrOrangeSky** [mrdoob/three.js#19399]
##### Description of the problem

While using THREE.WebGLRenderTarget to pass rendered scene as texture to a second shader, the value received in the Shader texture uniform variable is always null.

Flow of code: 
1.Shader1 is used for renderingDepthMap(Working fine while being rendered on screen)
2.The rendered depthMap is passed as texture uniform to shader2 that is finally rendered on screen.

Relevant Code Snippet:
//Initialize the renderTarget
	
var options = {
    		
			minFilter : THREE.LinearFilter,
    			magFilter : THREE.LinearFilter,
    			format : THREE.RGBAFormat,
    			type : /(iPad|iPhone|iPod)/g.test(navigator.userAgent) ? THREE.HalfFloatType : 
                        THREE.FloatType
    		};

	renderTarget1 = new THREE.WebGLRenderTarget(window.innerWidth, window.innerHeight, 
                                   options);
	renderTarget1.stencilBuffer = false;
	renderTarget1.texture.needsUpdate = true;
	renderTarget1.texture.generateMipmaps = false;

	//Define the Shader2 uniforms
        uniforms = {
			depthMap : { type: "t", value: renderTarget1.texture},
			O_SIZE : { type: "float", value: 0.000375},
		   };

        //Creating Material for Shader2
        materialShader2 = new THREE.ShaderMaterial({
				uniforms: uniforms,
				vertexShader : document.getElementById('vertex2_Shader').textContent,
				fragmentShader : document.getElementById('fragment2_Shader').textContent
			});

	materialShader2.needsUpdate = true;

	//Animate function
	function animate()
	{
		// render depth map in renderTarget1
		renderer.setRenderTarget(renderTarget1); //setting render target
		renderer.render(sceneDepthMap, shadowCamera); // rendering depthmap to framebuffer
		renderer.setRenderTarget(null);
		renderer.render(scene2, shadowCamera);
		requestAnimationFrame( animate );
	}

##### Three.js version

- [ ] Dev
- [x] r101
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by NicolasRannou** [comment]
How do you initialize the WebGL renderer? Could `renderer.autoClear = false;` be missing? You may also adjust the animation loop after turning off auto-clear:

```
function animate()
{
       renderer.clear();

	// render depth map in renderTarget1
	renderer.setRenderTarget(renderTarget1); //setting render target
	renderer.render(sceneDepthMap, shadowCamera); // rendering depthmap to framebuffer
	renderer.setRenderTarget(null);
	renderer.render(scene2, shadowCamera);
	requestAnimationFrame( animate );
}
```

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.

**Comment by Mugen87** [comment]
https://discourse.threejs.org/t/webglrendertarget-null-texture-in-shader-texture-uniform/15378
