### ISSUE TITLE
VRMLoader prevents setting a DRACOLoader

### ISSUE THREAD

**Issue by stewe** [mrdoob/three.js#19401]
##### Description of the problem
There is a typo in the VRMLoader line 44:

`this.glTFLoader.setDRACOLoader( dracoLoader );`

It should be: `this.gltfLoader.setDRACOLoader( dracoLoader );`

##### Three.js version

- 0.116.1

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Good find! Would you like to make a PR with the fix?

**Comment by stewe** [comment]
Sure, I will do it on friday.

**Comment by Mugen87** [comment]
@stewe Ignore my PR. I thought you would not do the change anymore. I just wanted to ensure the fix lands in `r117`.

**Comment by stewe** [comment]
Oh sorry, I didn't have enough time on Friday to fix it.
