### ISSUE TITLE
GLTFLoader - support reuse of the same Texture if external image reference is identical between two or more models?

### ISSUE THREAD

**Issue by supermoos** [mrdoob/three.js#19402]
I have two GLB models that both reference the same external image (jpg) as a texture used in their materials - currently this results in two Textures created and uploaded to the GPU, is there a way to reuse the (identical) Texture's between models, like checking in the TextureLoader if that Texture has already been loaded and created? There's a similar question here for Babylon - but it gives a bit of more context: https://www.html5gamedevs.com/topic/37130-loading-gltf-files-that-share-same-textures/

##### Three.js version
- [x] r116

##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
Are you setting `THREE.Cache.enabled = true;`? I think that would do what you need, in most cases. The exception is if the models use different UV transforms on the same texture - currently there's no way to prevent duplicate GPU uploads in that case. I think @Mugen87 had proposed a PR to fix that, but I'm having trouble finding it at the moment.

**Comment by Mugen87** [comment]
>  I think @Mugen87 had proposed a PR to fix that, but I'm having trouble finding it at the moment.

It's this one: #17949
