### ISSUE TITLE
DRACOLoader not working on iOS11

### ISSUE THREAD

**Issue by luruke** [mrdoob/three.js#19405]
##### Description of the problem
Current example `webgl_loader_draco` is not working under iOS11

![Screenshot 2020-05-20 at 23 58 17](https://user-images.githubusercontent.com/61326/82501954-6b3ccb00-9af6-11ea-9851-a84138719b64.png)

##### Three.js version

- [x] Dev
- [x] r116
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

**Comment by sciecode** [comment]
Example loads correctly on iOS 13.4.1. Chrome, Firefox and Safari.

Is this only happening in Safari? I'm gonna guess that iOS Safari didn't have support for [Promise.finally()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally) back in version 11. This is likely a browser-related problem.

**Comment by donmccurdy** [comment]
I think @sciecode has the right guess here, yes. Users need a Promise polyfill for IE11, probably the same fix would work on Safari 11 as well? 

A PR to replace the `.finally` call with `.catch(...).then(...)` would be OK with me, but I do not currently have time to write and test that fix. There is some longer-term work underway to rewrite DRACOLoader, in https://github.com/mrdoob/three.js/issues/18234.

**Comment by luruke** [comment]
Same bug spotted in Chrome 59 (ah, the pleasure of supporting webview and old devices).

For a more detailed list where this bug can happen:
https://caniuse.com/#feat=promise-finally

**Comment by luruke** [comment]
For info, who needs a quick fix can just polyfill `finally`.
I did via `import 'core-js/features/promise/finally'`

**Comment by Mugen87** [comment]
I vote to leave the code as it is and just update the browser support doc page instead.

https://threejs.org/docs/index.html#manual/en/introduction/Browser-support
