### ISSUE TITLE
Add Mixins into Math Classes

### ISSUE THREAD

**Issue by munrocket** [mrdoob/three.js#19410]
##### Description of the problem

Core by yourself not uses all math that exist in a library.
This is an easy way how to improve three-shaking and potentially save ~60kb.

![](https://aws1.discourse-cdn.com/standard17/uploads/threejs/original/2X/e/ea9cd6e6caa53773c23fec6ed09fbc961ad45622.png)
Yes this is a breaking change, but we have a reason.

**Comment by looeee** [comment]
I don't understand what you're suggesting here. Can you expand on it a bit? What are the mixins you want to add?

**Comment by munrocket** [comment]
At least to WebXR it’s fit perfectly, but for Math classes it’s questionable. Right now looks like this part of library in core too big for all of the cases.

The idea to make Math plugins somehow. It’s much more easy than shaderLib refactoring.

**Comment by looeee** [comment]
Hopefully once we convert the library to use classes, tree-shaking will work. I don't think there's any point in attempting to address this issue until we reach that milestone.

**Comment by munrocket** [comment]
Yeah, but WebXR will be not tree-shakable after migration because it imported in renderer. I think we need mixins at least for it.

If Ray.js and Sphere.js will disappear after ES6 classes migration it will be cool!

**Comment by looeee** [comment]
JavaScript doesn't have official mixins, so people often mean different things when they use the word "mixin". Can you give an example of what you mean in code?

**Comment by munrocket** [comment]
Here a way how we can improve tree shaking with WebXR mixins
```js
//before
let renderer = new THREE.WebGLRenderer( { antialias: true, alpha: true } );
renderer.xr = true;

//after
let renderer = new THREE.WebGLRenderer( { antialias: true, alpha: true } );
Object.assign(renderer, { xr: new THREE.WebXR() });
```
I will make a PR.

With Math classes all become more complicated. Basically we don't have any heavy math in core, sure that current architecture can be lighter, but don't have exact suggestion. Inheritance? Hook?

**Comment by munrocket** [comment]
Mixins exists in Typescript. I maid a PR with same ideas for WebXR. #19513

**Comment by DefinitelyMaybe** [comment]
That looks like the old style being used across the repo already. For folks that are knowledgeable around js it makes sense but part of the ideas behind moving to classes was to not encourage that style by default

**Comment by munrocket** [comment]
This is an open question how to make Math smaller. It's pretty old API and hard to change something here. But this idea is much better than simple renaming Math -> MathUtils.

**Comment by looeee** [comment]
> renaming Math -> MathUtils.

This was done to prevent the name clash with the JS Math object after moving to modules. 

> `Object.assign(renderer, { xr: new THREE.WebXR() });`

I would say this is composition rather than a mixin. But perhaps some authors call this pattern a mixin. 

In any case, how would this look later once we move to classes?

``` js
class WebGLRender { 
   ...
}
```

**Comment by munrocket** [comment]
Just a property. Thanks for conversation, I will close this issue as too revolutionary. Hope after moving to classes we will get it smaller.
