### ISSUE TITLE
VRMLLoader parse error

### ISSUE THREAD

**Issue by d-packs** [mrdoob/three.js#19415]
I have two sample wrl files, both do not load correctly (tested in Firefox and Chromium).
Error is `Uncaught Error: THREE.VRMLLoader: Parsing errors detected.`

![capture-200521-203144](https://user-images.githubusercontent.com/33980111/82587576-1c4c6f80-9ba2-11ea-95fe-7595259b930b.png)
To test I have replaced the model in examples/webgl_loader_vrml.html with my models.

#### Test files:
[File 1 wrl.zip](https://github.com/mrdoob/three.js/files/4663856/test2.wrl.zip)
[File 2 .wrl.zip](https://github.com/mrdoob/three.js/files/4663844/gaz.wrl.zip)

##### Three.js version
0.115.0
##### Browser
- [x] Chrome
- [x] Firefox

##### OS
- [x] Linux
(Manjaro Linux - Arch based - kernel 5.6)

**Comment by Mugen87** [comment]
Your files are VRML 1.0 files which are not supported by the loader. You have to use VRML 2.0.

Unfortunately, I can't even import the files to Blender or Meshlab since I wanted to test a conversion to 2.0.

**Comment by d-packs** [comment]
thank you for the clarification.

**Comment by Mugen87** [comment]
Please let me know if you find a way to convert them from 1.0 to 2.0. Such a tool could be useful in future support cases.

**Comment by WestLangley** [comment]
@Mugen87 It seems the version check needs to occur earlier.

**Comment by cecilemuller** [comment]
@Mugen87 For converting VRML1 to VRML2:
 - this has two CLI tools (and the links are still working): http://www.interocitors.com/polyhedra/vr1tovr2/
 - there is also Okino PolyTrans, although I haven't used it since 2011: https://www.okino.com/conv/imp_iv.htm

**Comment by Mugen87** [comment]
@cecilemuller Thank you!

**Comment by d-packs** [comment]
Update: I've used the converter in the first link above and produced vrml v2 files. 
Also I've used other converters to transform the file to a collada file and then back to vrml (thus ensuring a supposedly correct vrml v2 format).
The file is still not displayed correctly. 

This is how it should look like
![capture-200522-105452](https://user-images.githubusercontent.com/33980111/82644958-cf58af80-9c1a-11ea-98e3-3e5dc44451aa.png)

And this is how it looks in three (again i've just replaced the file from the vrml-loader-demo with my file, no other change to the code).
![capture-200522-105542](https://user-images.githubusercontent.com/33980111/82644972-d384cd00-9c1a-11ea-8cc5-f93fbf82bd3a.png)

I've used https://cadexchanger.com/downloads which is a commercial tool but provides an unrestricted demo for 30 days, sufficient for testing purposes.

[test.wrl.zip](https://github.com/mrdoob/three.js/files/4666752/test.wrl.zip)

**Comment by d-packs** [comment]
I've used the converter at (http://www.interocitors.com/polyhedra/vr1tovr2/) to generate v2 files. But the file won't display at all. No parsing error this time. The file is being retrieved by the script., no CORS error or anything.
![capture-200522-115248](https://user-images.githubusercontent.com/33980111/82650117-e69b9b00-9c22-11ea-9eeb-66dece42f0dc.png)



**Here are the converted files** 
[test-modelsvrml-v2.zip](https://github.com/mrdoob/three.js/files/4667002/test-modelsvrml-v2.zip)

**Comment by cecilemuller** [comment]
I looked at the files from the zip in Vrmlpad to check for code errors and BS Contact to check for visual errors, but the converted files look valid indeed.

I'll make a small test to try them them in threejs as well in a bit, perhaps it's just a Viewpoint position issue.

**Comment by Mugen87** [comment]
Ah, the problem is that `VRMLLoader` does not process the `Collision` node yet. I think we can easily fix this by treating such nodes like other grouping nodes.
