### ISSUE TITLE
Safari requestAnimationFrame conflict with video playback

### ISSUE THREAD

**Issue by dustinkerstein** [mrdoob/three.js#19422]
_FYI, this is more of a WebKit / Safari issue and not directly related to Three.js - https://bugs.webkit.org/show_bug.cgi?id=212260 but I wanted to post here for informational purposes. Feel free to close this as you see fit._

Check out https://jsfiddle.net/9sfr8dj3 using Safari. 

This one is a little quirky. When the issue happens (about 20% of the time on my 2018 Macbook Pro), texture updates will freeze and the entire tab becomes sluggish (rAF drops to ~5fps on my device). Note that if you are unable to replicate at first using the JSFiddle, just keep hitting the 'Play Again' button until it does replicate. 

Some additional notes:

1. Happens with both video.src as URL video.src as and Blob (try toggling 'useBlob' in the JSFiddle)
2. Using setInterval/setTimeout avoids this issue (try toggling 'useRAF' in the JSFidddle)
3. Having the <video> tag visible on the page avoids this issue (try toggling 'showBothCanvasAndVideoTag' in the JSFidddle)

##### Three.js version

- [x] r105, r110

##### Browser
- [x] Safari

##### OS
- [x] macOS
- [x] iOS

**Comment by Mugen87** [comment]
How about sharing your finds in a new topic at the [forum](https://discourse.threejs.org/)? Maybe calling it !Safari WebGL issues"? In this way, the issues at GitHub keep focused on `three.js` related bugs and feature requests.

**Comment by dustinkerstein** [comment]
Sure thing. Sorry for the noise. Feel free to close these "browser" issues. 

Also, FYI, I just confirmed this issue also happens when using WebGL directly - https://jsfiddle.net/bm67yk9x

**Comment by dustinkerstein** [comment]
Here's the forum post - https://discourse.threejs.org/t/safari-webgl-issues-with-video-playback-and-requestanimationframe-performance/15452

**Comment by Mugen87** [comment]
Perfect!
