### ISSUE TITLE
Cannot view three.js webxr examples, but can view other webxr such as toji.github.io/webxr-particles

### ISSUE THREAD

**Issue by josefK128** [mrdoob/three.js#19433]
This issue is an update and/or extension of the closed issue #18431 by @omgisraven January 19 titled: 'Examples claim "webxr not available" but immersive.dev works'.

In that discussion @Mugen87 suggested Chrome (not used by @omgitsraven and no further reply), and @mrdoob noted that Firefox (used by @omgitsraven) had not yet implemented webxr - and then closed the issue.

I have been away from web3D for a year and want to re-implement much webvr work in webxr in order that my past and future work be most generally viewable.

I use:
Alienware R17 running Windows 10
Firefox Nightly 78.0a1  (current as of May 23 2020)
Chrome 81.0.4044.138  (current as of May 23 2020)
Oculus Rift

Note that I enabled all Chrome webxr flags (including webxr runtime - Oculus, and I also tried default in the discussion below)
Note that I also tried Chrome Canary and Chromium/dev but found Chrome the closest to running webxr (see below).

First - Firefox Nightly (and apparently Firefox Reality 10) can run both webxr and webvr - I can verify this for Firefox Nightly by my own webvr examples and by running toji.github.io/webxr-particles/ (webxr).

However Firefox Nightly displays 'webxr not available' on  three.js/examples/webxr_vr_*.html 
[1] this is my first 'sub-issue' (Firefox Nightly)

Second, running Chrome on three.js/examples/webxr_vr_*.html or toji.github.io/webxr-particles/ gives the behavior:
shows 'enter vr'
clicking on 'enter vr' brings up a security panel:
'Enter VR from localhost:8000 (using python httpserver on port 8000 - same
behavior for live-server on port 8080) While in VR this site may learn about
* your physical features such as height
* the layout of your room'
The panel also displays 2 buttons: <enter vr>  <cancel>

Clicking on <enter vr> generates a web console flagged error:
'DOMException: the specified session configuration is not supported' and there is no split-screen VR.
[2] this is my second 'sub-issue' (Chrome)

I went into the Toji code to find differences - whereas the 'examples' code made no mention of session, the toji-code fetched a 'renderer.vr.getSession()' object, but this was in a function 'inAR()'
so I doubt is relevant.

Further, there was an object argument to a function 'WEBVR.createButton' which contained a field 'sessionInit' set to {requiredFeatures: ['local-floor']} but this doesn't suggest much.

Finally, there are event-listeners defined for 'sessionstart' and sessionend'.

I'm curious if others can view the three.js/examples/webxr_vr_*.html what
browsers and setting are being used?

I think I do not need to say that I am not being critical at all, but I would really appreciate a find a way to view the examples on Firefox Nightly and/or Chrome, and verify a software path for viewing webvr content in a webxr context.

Thanks

**Comment by Mugen87** [comment]
When using Chrome, it's not necessary to enable any flags. Just use the default configuration.

Besides, if you want to test with Firefox, use [Firefox Reality](https://mixedreality.mozilla.org/firefox-reality/).

> I'm curious if others can view the three.js/examples/webxr_vr_*.html what
browsers and setting are being used?

It works for me without issues on a Google Pixel and Oculus Quest. I've also tested lately with an Oculus Go and everything worked. Unfortunately, I have no Oculus Rift at hand so I can't verify this issue.

**Comment by josefK128** [comment]
Thanks @mugen87 for your very quick reply - I appreciate it.

I tried your suggestions. However, I can't report success as of yet:

* I tried Chrome on examples with flag-defaults and received 'vr not supported'

* I downloaded Firefox Reality (which displayed 'get it for Oculus Go' - which
I am not using (Oculus Rift) - but I tried and received as before: 'webxr not
available' (and no useful errors in the web console)

It seems maybe using Oculus Rift is the immediate problem since you have had success with Google Pixel/Chrome and Oculus Quest/Oculus Browser.

It seems however, that it would be highly desirable to make the examples viewable more generally - that is on Oculus Rift and S and on the main browsers - Firefox and Chrome (that's assuming my experience is not just an outlier)

In any case I appreciate the great work of the three.js community, such as yourself.

Maybe the software is just unsettled as of now and there are mismatches which will be resolved over time.

If you or anyone has any further pointers please post.

Thanks

**Comment by josefK128** [comment]
I'm sorry - I didn't mean to close the issue - I hit a wrong button  - very sorry.

**Comment by MichaelHazani** [comment]
@josefK128  In an unannounced (as far as I can tell) move, latest chrome removed Oculus runtime support (because it's apparently insecure and Oculus is about to roll their OpenXR integration) thus - again, as far as I can tell - killing all desktop WebXR on Chrome for Oculus hardware users, at least. 

You can re-enable with launch flags: See this tweet and related conversation for more info and potential workarounds: https://twitter.com/michaelhazani/status/1263615036146278405?s=20

I can also confirm anecdotally that OpenXR support via SteamVR doesn't seem to work either on latest Chrome. "VR Not Found", etc. 

It's really hard to verify because not too many folks seem to be working on WebXR. Either way, I've resorted to [Metachromium](https://github.com/webaverse/metachromium-bin/releases) - an AR-in-VR WebXR-friendly browser - for all my work for now; even though it's an indie project, it seems to be the most WebXR-robust browser I can find for now. And since Firefox Reality isn't available for desktop, and Firefox is still stuck in WebVR land, I'm pretty sure it's the only viable desktop WebXR path at the moment (although I'd love to be corrected on this, especially if anyone has gotten WebXR to work via the OpenXR runtime on latest chrome - 83.0.4103.61).

**Comment by Mugen87** [comment]
I'm now irritated a bit by this issue. @MichaelHazani says support for Oculus runtime has been removed. But the OP says the other WebXR examples on the web work for him. Just not the `three.js` demos from the official website.

**Comment by MichaelHazani** [comment]
If my impression of this mess is true (and a mess it _is_), OP was talking about Brandon Jones's former example which uses the webvr polyfill - fwiw I've had some luck with that too. I can confirm *all* WebXR fails on latest chrome (because the authoritative [WebXR Samples page](https://immersive-web.github.io/webxr-samples/) is my first go-to for WebXR sanity checks. 

@josefK128 - perhaps check on your end and confirm they don't work on chrome desktop/oculus?

**Comment by Mugen87** [comment]
> perhaps check on your end and confirm they don't work on chrome desktop/oculus?

Good idea. If these examples don't work, it's not a `three.js` related problem and hence the issue should be closed.

**Comment by MichaelHazani** [comment]
agreed. fwiw I'm running into _all kinds_ of issues going back to the WebXR spec implementation, _as I see them in threejs_ ([conflated input events](https://github.com/webaverse/metachromium-bin/issues/14), for example), but lovely as the threejs community is:),  there's no use flagging them here, it goes deeper.

Can confirm three webxr example work well w/Oculus on MetaChromium - I've been referencing them plenty in daily dev work.

**Comment by josefK128** [comment]
@MichaelHazani and @Mugen87 - my experience (which is reported in detail in the initial post) is that I can run the toji example in Firefox Nightly/Oculus but not the three.js webxr examples, and can't run either in Chrome/Oculus, with all flags variations - which seems to confirmed by @MichaelHazani, and on more than just Oculus.

What I have seen is that both the toji example and the three.js examples use the 'HelioWebXRPolyfill' which raises the question why the toji example displays in Firefox Nightly but not the three.js examples. (I am essentially restating my first 'sub-issue' which is specific to Firefox Nightly)

@MichaelHazani wrote that 'not too many folks seem to be working on desktop WebXR'. If this is true it is unfortunate - best performance and artistically critical use of shaders is enabled by GPU. I have always believed that working on good hardware was a view of the future everywhere. That should be a strong motivation for ensuring that high-resolution headsets with powerful cpu/gpu
bases are supported as early as possible by new standards and implementations.

**Comment by Mugen87** [comment]
@josefK128 Can you please test with these examples:

https://immersive-web.github.io/webxr-samples/

**Comment by josefK128** [comment]
@mugen87 - I'll give a quick report on example one - immersive VR Session:

Chrome/Oculus - first indication is that the combination is flagged as supporting webxr. However trying the link yields 'VR not found' and clicking on that button does nothing.

Firefox Nightly/Oculus - first indication is that webxr is NOT supported. However clicking the link brings up a small panel with google cardboard icon prompting to 'Allow Virtual Reality Access' - clicking this option brings up 'Enter VR' on the 'Immersive VR' page - clicking on 'Enter VR' brings up the world in Oculus - GOOD.

I hope this may be a helpful experiment.

**Comment by MichaelHazani** [comment]
As mentioned, this seems to be an issue with chrome, not ThreeJS. Not sure
what's in the Helio polyfill that mitigates this but I had the exact same
issue with chrome *except* when running with the Oculus runtime CLI flags
as mentioned above. In any case, I agree with @Mugen87 that this is not a
ThreeJS issue, as restoring the Oculus runtime support makes chrome desktop
WebXR work again with Oculus, including the ThreeJS examples - confirmed
this myself earlier today.

**Comment by josefK128** [comment]
@mugen87 - a further note

When the examples page comes up the message for Firefox Nightly is: 'Your browser does not support WebXR, but does support the deprecated WebVR API. You may be able to run Virtual Reality experiences on sites that use the WebXR Polyfill, like this one!

It seems Firefox Nightly/Oculus runs with polyfill, and not without.

**Comment by josefK128** [comment]
It seems there may be issues with Chrome which are independent of three.js.

However, a question remains - why do the Toji and immersive-web webxr examples run in Firefox Nightly/Oculus (with polyfill) but not the three.js webxr examples (using the same polyfill) ?

**Comment by Mugen87** [comment]
Sorry, but I think it's best if the discussion is shifted to stackoverflow or the [forum](https://discourse.threejs.org/). This issue represents no `three.js` bug.
