### ISSUE TITLE
Canvas Texture Seams/Artifact Lines at Repeat Border

### ISSUE THREAD

**Issue by Workruft** [mrdoob/three.js#19445]
##### Description of the problem

Hi, I'm using CanvasTexture like in the examples here:
https://threejs.org/examples/?q=canvas#webgl_materials_texture_canvas
https://threejsfundamentals.org/threejs/lessons/threejs-canvas-textures.html

My problem is I'm seeing seams/artifact lines at the repeat border of the texture, like in these images:
![image](https://user-images.githubusercontent.com/63685547/82763030-906d5a00-9dd2-11ea-9c62-12e9904a97b0.png)
![image](https://user-images.githubusercontent.com/63685547/82763044-a4b15700-9dd2-11ea-96e5-8413e4ac1153.png)
![image](https://user-images.githubusercontent.com/63685547/82763047-abd86500-9dd2-11ea-9311-d80124a7b214.png)

It's only supposed to have lines at the actual borders where there are height differences.

What I'm doing is I have a set of 16 different canvases that turn into 16 different textures + materials (which material I use doesn't change anything), and then I have a texture for each type of grid cell border in my game: border in the back, right, front, left, etc. It seems that when it repeats these textures, it's sampling very slightly from the opposite side of the texture, or something like that.

![image](https://user-images.githubusercontent.com/63685547/82763131-5e102c80-9dd3-11ea-8d42-24a86c1f9c30.png)

I've tried using canvas `context.rect()` and `context.clip()`, and I've also tried using canvas `context.drawImage()` from one canvas onto another (not depicted here), in order to see if maybe there's some kind of overdraw in the out-of-bounds area of the canvas. That's simply not the case.

Also, notably, if I change the color I'm using to draw the borders on the canvases to white, the seams/artifact lines become white as well:
![image](https://user-images.githubusercontent.com/63685547/82763140-7bdd9180-9dd3-11ea-9d4c-3ed12258a403.png)
![image](https://user-images.githubusercontent.com/63685547/82763143-7f711880-9dd3-11ea-951c-84f0f0ba607e.png)

The entire map is using these same 16 textures, using the material index (the Mesh has an array of 16 materials). I have 2 triangle Face3's per grid cell, and I assign a material index to each pair of triangles, each grid cell. I've tried not adding the cliff/side mesh as well, to see if maybe that was causing any issues, to no avail.

I would just use the clipping/padding, but it looks weird this way and looks way better if the borders are right on the edge of the texture.

Feel free to ask any questions you think may be relevant. My code is also open source, if you want to test.

Thanks.

##### Three.js version

- [x] r115

##### Browser

- [x] Firefox

##### OS

- [x] Linux Mint

**Comment by WestLangley** [comment]
A reasonable guess is your problem is caused by mipmapping.

However, this is not the appropriate site for help. If you need help with your app, you can post your question on the three.js [forum](https://discourse.threejs.org).

**Comment by Workruft** [comment]
I already tried turning mipmapping off and using `LinearFilter`, it didn't fix it.

I'm not asking for help, I'm reporting a bug and seeing if there's a fix or workaround.

**Comment by Workruft** [comment]
https://discourse.threejs.org/t/canvas-texture-seams-artifact-lines-at-repeat-border/15512

**Comment by Workruft** [comment]
I solved it:
![image](https://user-images.githubusercontent.com/63685547/82778015-0a770080-9e1e-11ea-8e58-5579a0c21275.png)
Info is in my [comment here](https://discourse.threejs.org/t/canvas-texture-seams-artifact-lines-at-repeat-border/15512/13).
