### ISSUE TITLE
OrbitControls: docs have no information about Events

### ISSUE THREAD

**Issue by Dragon3DGraff** [mrdoob/three.js#19444]
##### Docs have no information about Events
https://threejs.org/docs/index.html#examples/en/controls/OrbitControls

```
var changeEvent = { type: 'change' };
var startEvent = { type: 'start' };
var endEvent = { type: 'end' };
```

##### Three.js version

- [ ] Dev
- [x] r116
- [ ] ...

**Comment by DefinitelyMaybe** [comment]
True. they are custom event's using an older declaration style. I had a look around the controls not too long ago and was able to put together what was happening.

would you be interested in creating the info your looking for?

**Comment by Dragon3DGraff** [comment]
I was needed events of OrbitControls to fix some bugs in my app. I'm already using events of DragControls and TransformControls, but when I checked docs of OrbitControls I thought they have no events. I couldn't believe and checked source code. I think it would be more convenient if this info will be in the docs. This is very useful feature
