### ISSUE TITLE
GLTFExporter: when exporting single objects, the type is overridden to "Object3d"

### ISSUE THREAD

**Issue by zaino** [mrdoob/three.js#19453]
##### Description of the problem

Hi there.
I'm using GLTFExporter to convert an FBX into GLTF. While it works fine with an entire FBX scene, I'm trying to export one object at a time, and I'm seeing 2 issues:
- there's always an AuxScene in the output, I think it would be nice to add the option to not have it in the options, but this one is no biggie;
- it seems that when I export a single object, its type gets lost, and it becomes simply an Object3D.
No more Group, Bone, Mesh, always Object3D.
To be precise, I'm exporting the object as binary, postMessage the arraybuffer, then parse it with GLTFLoader on the main thread.

Cheers

##### Three.js version

- [x] Dev
- [ ] r116
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
Could you share code that reproduces the problems you're seeing? 

Is the single object you export missing entirely? Or just nested inside of a parent Object3D?

Note that glTF does not have 1:1 object types for three.js objects. For one thing, there is no Object3D/Group distinction, and Bones are only represented if there is a skinned mesh that is using them. I would expect exporting a single Mesh to work fine though...

**Comment by zaino** [comment]
Thanks for the quick reply @donmccurdy !

On the worker side:
-  load an FBX (I'm using the samba_female.fbx from Mixamo), then traverse the scene;
- for each node, I remove the children temporarily to avoid recursion, and then export it.

The export looks something like this:
```
exporter.parse( node, function ( gltf ) {
    gGLTFLoader.parse(gltf, undefined, function(recObj) {
        postMessage(gltf);
    });
}, options);
```
with options:
```
let  options = {
    binary: true,
    trs: false,
    onlyVisible: false,
    truncateDrawRange: true,
    embedImages: true,
    maxTextureSize: Infinity,
    animations: fbxScene.animations,
    forcePowerOfTwoTextures: false,
    includeCustomExtensions: false
};
```
As you can see, as a test, I load it right back to check the difference between the original node and the reconstructed `recObj`. `Node `is present in `recObj`, as a child of `AuxScene`. All good. But the type is always `Object3D`, even for `Bone`. That leads to all sort of problems in my existing code (used to just load an FBX in the main thread).

Now that you explained it to me, I understand the `Group` type will be gone, since the format does not distinguish it from `Object3D`, and `Bone` type is probably lost because the three.js objects for the bones and the actual skinned mesh are not exported together. 

I'm thinking that bundling up `Bones `and `SkinnedMesh ` nodes in the same export could be all I need. Or maybe I could disable the check that bones are actually being used, if you could point out where that code is.
Do you have any other suggestion?

Thanks in advance!

**Comment by donmccurdy** [comment]
> I'm thinking that bundling up Bones and SkinnedMesh nodes in the same export could be all I need.

I think that would be the way to go, yes. An isolated bone cannot really be exported as glTF.

**Comment by zaino** [comment]
My only fear is that would amount in enough nodes to make the main thread chug when parsing the arraybuffer with the GLFTLoader. If that's the case, I might drop the whole "load-on-web-workers-experiment", since my goal was to have loading in the background with no render frames skips...

My dream would be to have a way to serialize a three.js scene directly to SharedBuffers, without even going through JSON, which is something I believe I could achieve with some work and reflection magic, if only I thought it was worth all the effort. :)

**Comment by donmccurdy** [comment]
I don't think GLTFLoader does as much work while parsing as your comment suggests... in particular it doesn't generally have to parse ArrayBuffers — they can be uploaded directly from a GLB to the GPU without much or any modification. There is some overhead in creating many Bone or Object3D JS objects, but creating even 100 Object3D instances should not cost enough time to drop a frame when rendering at 60 FPS.

In nearly every case I've ever seen where loading was really slow, it was because of non-parsing work: uploading textures to the GPU, downloading a large amount of data over a network, or perhaps decompressing Draco geometry. 

It doesn't seem like there is a bug that needs to be fixed here, but if you would like to share more detail (code or a demo perhaps?) about what you're trying to optimize, I think you can get more help on the forums: https://discourse.threejs.org/.

**Comment by zaino** [comment]
Thanks, @donmccurdy I'll head over to the forums.
I've been playing around with three.js very recently, and have never written a line of javascript before, so I'm definitely inexperienced.  I thought it could be a bug, that's why I started here first.
I agree with you now that there isn't any bug to fix!

Thanks and sorry if I wasted your time!

Cheers

**Comment by zaino** [comment]
Also, assuming I'm doing this correctly:
```
let t0 = performance.now();
gltfLoader.parse(gltf, undefined, function(result) {
        console.log("Parsed GLTF in: " + (performance.now() - t0));
});
```
Reports ~34ms, which is indeed very fast, but not as fast at the 16ms needed to render at 60fps.
This should be parsing alone, I think.

**Comment by donmccurdy** [comment]
That may measure parsing alone, or may not — the operation is asynchronous, and so depends on the browser's event loop and possibly (though probably not, with a total time of just 34ms) loading remote resources. The browser's profiling tools should give more detail on where time is spent.
