### ISSUE TITLE
How to fit two geometries together?

### ISSUE THREAD

**Issue by jxnx888** [mrdoob/three.js#19465]
How to fit two geometry together?
 
Hello Developers,

I want to ask if you do have this feature. 

If there are two geometries( maybe more) move to closer, they will fit together automatically. No matter how to fit together, just directly fit to make sure there is no gap between the two geometries.
 
Thanks,
Alan

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help.
