### ISSUE TITLE
why  function intersectObject  deleted  "if ( object.visible === false ) return;"?

### ISSUE THREAD

**Issue by Arkitoy** [mrdoob/three.js#19475]
function intersectObject( object, raycaster, intersects, recursive ) {
               

>  if ( object.visible === false ) return;

		if ( object.layers.test( raycaster.layers ) ) {

			object.raycast( raycaster, intersects );

		}

		if ( recursive === true ) {

			var children = object.children;

			for ( var i = 0, l = children.length; i < l; i ++ ) {

				intersectObject( children[ i ], raycaster, intersects, true );

			}

		}

	}

........................................................................................................................................................................

**Comment by Mugen87** [comment]
This was discussed and decided here: #14700

`Raycaster` no longer evaluates `Object3D.visible`. You now have to use layers to filter out unwanted objects.

**Comment by Arkitoy** [comment]
fine!
