### ISSUE TITLE
Question: Why not use same floating point number in common.glsl.js

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#19472]
I think it will be better, why not use same floating point number in common.glsl.js

```diff
--- a/src/renderers/shaders/ShaderChunk/common.glsl.js
+++ b/src/renderers/shaders/ShaderChunk/common.glsl.js
@@ -1,9 +1,9 @@
 export default /* glsl */`
 #define PI 3.14159265359
 #define PI2 6.28318530718
-#define PI_HALF 1.5707963267949
+#define PI_HALF 1.570796326795
 #define RECIPROCAL_PI 0.31830988618
-#define RECIPROCAL_PI2 0.15915494
+#define RECIPROCAL_PI2 0.15915494309
 #define LOG2 1.442695
```

**Comment by Mugen87** [comment]
Well, for consistency reasons it's of course better to follow a common approach for decimal places. At least for the PI constants.

**Comment by mrdoob** [comment]
@WestLangley any preferences?

**Comment by WestLangley** [comment]
Not really. @linbingquan can file a PR and fix it.

**Comment by WestLangley** [comment]
It looks like LOG2 is poorly-named. Maybe it is not used and can be removed here.
```glsl
#define LOG2 1.442695041  // 1 / ln( 2 )
```

**Comment by linbingquan** [comment]
@WestLangley I don't know `RECIPROCAL_PI` what does it relationship with `PI`.

In the Chrome83, the `Math.PI` value is `3.141592653589793`, I want to use it.
And I removed `LOG2`.

```diff
diff --git a/src/renderers/shaders/ShaderChunk/common.glsl.js b/src/renderers/shaders/ShaderChunk/common.glsl.js
index 947fd3c05..5ebcbe29d 100644
--- a/src/renderers/shaders/ShaderChunk/common.glsl.js
+++ b/src/renderers/shaders/ShaderChunk/common.glsl.js
@@ -1,10 +1,9 @@
 export default /* glsl */`
-#define PI 3.14159265359
-#define PI2 6.28318530718
-#define PI_HALF 1.5707963267949
+#define PI 3.141592653589793
+#define PI2 6.283185307179586
+#define PI_HALF 1.5707963267948966
 #define RECIPROCAL_PI 0.31830988618
-#define RECIPROCAL_PI2 0.15915494
-#define LOG2 1.442695
+#define RECIPROCAL_PI2 0.15915494309
 #define EPSILON 1e-6
```

**Comment by WestLangley** [comment]
RECIPROCAL_PI = 1 / PI

**Comment by linbingquan** [comment]
@WestLangley Excuse me, I don't know `EPSILON`, why it define `1e-6`,  does it has relationship with `Number.EPSILON`.

https://github.com/mrdoob/three.js/blob/b993f5c99341b1b483c6bdf94fdc4fbac61aa0f1/src/renderers/shaders/ShaderChunk/common.glsl.js#L8

**Comment by WestLangley** [comment]
In the shaders, `EPSILON` is not based on the hardware precision. It has been used to avoid instabilities in the calculation. Perhaps it should be defined only where is it used.

/ping @bhouston for 2nd opinion

**Comment by bhouston** [comment]
Just remember that glsl currently is precision limited to float32 or lower, where as JavaScript uses doubles for all mathematical calculations.  Thus JavaScript's Math.PI and other math constants will have more precision than needed for GLSL.  Probably don't hurt though as GLSL probably just truncates.

I am okay with removing EPSILON.  I had a friend in university who could analyze any floating point calculation and tell you the exact epsilon you should use in that case.  But it is a lot of work to do that on a per mathematical equation basis.
