### ISSUE TITLE
Suggested fix for OrbitControls pop-up window support

### ISSUE THREAD

**Issue by d-danger** [mrdoob/three.js#19478]
**Suggestion:**
Changing "document" to "scope.domElement.ownerDocument" in the OrbitControls.js code.

**Issue:**
Use in a popup window causes the orbit controls to fail because they use event listeners 'mousemove' and 'mouseup' on the main document and not the owner document of the element.

Testing codepen: https://codepen.io/pen/eYparRZ

**Comment by mrdoob** [comment]
That sounds good to me. Would you like to do a PR with the fix?

**Comment by d-danger** [comment]
Embarrassingly, I don't understand how Github works and I don't know how to do that.  I just found this problem when I was developing something using THREEJS and didn't know the best way to suggest the fix.

**Comment by Mugen87** [comment]
If `OrbitControls` is changed, would it also make sense to update `TrackballControls`, `TransformControls` and `PointerLockControls`? They also add their `mousemove` /`mouseup` event listeners to `document`.
