### ISSUE TITLE
TransformControls arrow head not reversed as needed

### ISSUE THREAD

**Issue by kevinresol** [mrdoob/three.js#19470]
##### Description of the problem

When camera is moved so that TransformControls get near the screen edge, its arrows will swap to the opposite direction in order not to overflow the screen. However, the arrow head is not reversed.

Note the wrong direction of the red arrow head below:
<img width="210" alt="Screenshot 2020-05-26 at 11 34 19 PM" src="https://user-images.githubusercontent.com/1103788/82920217-9bc6ae00-9fa9-11ea-962b-65adcc7a1884.png">

Can be reproduced on the official demo:
https://threejs.org/examples/#misc_controls_transform

##### Three.js version

0.116.1 from npm

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
I think this could be intended. In this case, the cones represent the direction of the positive axis.

**Comment by kevinresol** [comment]
Ahhh, ok. If that's the case please feel free to close :)

**Comment by mrdoob** [comment]
This was intentional, right @arodic?

**Comment by arodic** [comment]
Yes, it was intentional.
