### ISSUE TITLE
The combination of DirectionalLight and Environment Maps results in material artifacts in the Pixel 3

### ISSUE THREAD

**Issue by jgsacris** [mrdoob/three.js#19479]
##### Description of the problem

When combining DirectionalLight and Environment Maps with GLTF models results in very noticeable surface artifacts on the 3D model when viewed on the Pixel 3 

Start model with environment map and directional light:
![envMap-direct-light (2)](https://user-images.githubusercontent.com/3586410/83033887-f27ac900-a037-11ea-917c-85a09ec6aae7.png)

Start model with only directional light:
![direct-light-no-envMap (2)](https://user-images.githubusercontent.com/3586410/83034046-1b9b5980-a038-11ea-9cc0-3415c6619a0a.png)

Star model with only environment map:
![envMap-no-direct-light (2)](https://user-images.githubusercontent.com/3586410/83034734-dd526a00-a038-11ea-93b2-73b14dcb54c3.png)

Different model with directional light and environment map:
![envMap-direct-light2 (2)](https://user-images.githubusercontent.com/3586410/83034179-41c0f980-a038-11ea-95ed-73e86cad20cb.png)

##### Three.js version

- [ ] Dev
- [x] r116
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Problem only seen on Google Pixel 3 
The device is running Android version 10

**Comment by mrdoob** [comment]
Could you create a jsfiddle that reproduces the issue on the device?

**Comment by jgsacris** [comment]
Here is a jsFiddle where this problem can be reviewed:

https://jsfiddle.net/jg4inr/vy7qsnok/41/

**Comment by Mugen87** [comment]
I've tested the fiddle on a Pixel 1 (with Android 10) and it looks like on my Desktop. So no rendering artifacts like in your third screenshot.

**Comment by jgsacris** [comment]
We tested on two different Pixel 3's that we have in the office for development and both have this issue so it is not particular to one device. We are getting hold of a Pixel 4 and we will report the findings here.

**Comment by mrdoob** [comment]
Yes, this is a Pixel 3 issue. I've bumped on this before. Thanks for the jsfiddle! 🙏

**Comment by elalish** [comment]
Indeed, this is a problem I'm hitting all the time now in model-viewer, since I only have a Pixel 3 to test on. I think it's very closely related to a bug I fixed a few months ago by refactoring a shadow shader: #18315. It was pretty clear the shader wasn't wrong, but any small change would make this driver bug appear or disappear.

**Comment by Mugen87** [comment]
Does this issue still appear with Android 11?

**Comment by mrdoob** [comment]
Seems like we can!

This screenshot is from a Pixel 3 running Android 11:

![Screenshot_20210216-122502](https://user-images.githubusercontent.com/97088/108118257-fd79fb80-7095-11eb-94a9-f77b1f59cb22.png)
