### ISSUE TITLE
TypeError: "Materials[json.type] is not a constructor"

### ISSUE THREAD

**Issue by iAtomPlaza** [mrdoob/three.js#19480]
##### Description of the problem
```error
TypeError: "Materials[json.type] is not a constructor"
    parse http://localhost:3000/js/three.js:40095
    load http://localhost:3000/js/three.js:40057
    load http://localhost:3000/js/three.js:36378
```
#### Describe the bug or feature request in detail.
I'm trying to load a Material from json which I generated from blender

#### Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.
```js
// object loader
const objLoader = new THREE.OBJLoader();
objLoader.setPath("/blender/sun/");

// material loader
const materialLoader = new THREE.MaterialLoader();
materialLoader.setPath("/blender/sun/");

new Promise((resolve) => {
    materialLoader.load("SunMaterial.json", (m) => resolve(m));
}).then((materials) => {
    materials.preload();
    objLoader.setMaterials(materials);
    objLoader.load("sun.obj", (obj) => {
        scene.add(obj);
    });
});
```

##### Three.js version
- [x] Dev

##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Mugen87** [comment]
> I'm trying to load a Material from json which I generated from blender

How do you generate `SunMaterial.json` from Blender? If you are loading an OBJ asset, it seems you want to use `MTLLoader` in order to load a MTL file.

**Comment by iAtomPlaza** [comment]
> How do you generate SunMaterial.json from Blender? If you are loading an OBJ asset, it seems you want to use MTLLoader in order to load a MTL file

i wrote a script to generate the json, `MTLLoader` didnt load the materials anyway...

**Comment by Mugen87** [comment]
GitHub is not the right place for debugging user-level code. Please try it with the [forum](https://discourse.threejs.org/) instead. GitHub is for bugs and feature requests only.

BTW: If you create a topic you have to share more information so users are able to help you. For example share the resulting JSON file.
