### ISSUE TITLE
Error of MMDLoader.js in Native

### ISSUE THREAD

**Issue by jxnx888** [mrdoob/three.js#19484]
Hello Developers,

I am using MMDLoader to load the MIKI. When I am using the MMDloader.js （three.js-master\examples\jsm\loaders\MMDLoader.js） in ES6  is good, but there is an error when I using the MMDLoader.js in Native(three.js-master\examples\js\loaders\MMDLoader.js) 。 

I'm not sure if I'm using it in the wrong way or if there's something wrong with the js.
I hope I'm using it in the wrong way
`var MLoader = new THREE.MMDLoader();`
`
function loadPost( poseIndex ) {

		MLoader.load( modelFile, function ( object ) {
			MMDmesh = object;
			MMDmesh.position.y = - 150;
			MMDmesh.scale.set( 12, 12, 12 );
			MMDmesh.name = 'miku';
			scene.add( MMDmesh );
			initMMDGui();
		}, onProgress, null );
	}
`

![image](https://user-images.githubusercontent.com/22604980/83092488-0245ec00-a0d0-11ea-9c4b-4fa914280096.png)

![image](https://user-images.githubusercontent.com/22604980/83092471-f78b5700-a0cf-11ea-892d-c1fc48f6eaaf.png)

**Comment by takahirox** [comment]
Try to load https://github.com/takahirox/mmd-parser

(Non-module version of mmd-perser seems to have been removed in three.js repository, so please get from the link above).

**Comment by Mugen87** [comment]
Please use the forum if you need more help.
