### ISSUE TITLE
GLTFloader.parse can't parse glb file correctly

### ISSUE THREAD

**Issue by constantank** [mrdoob/three.js#19496]
![image](https://user-images.githubusercontent.com/24249173/83236388-08b68f80-a1c6-11ea-8319-160163c991ed.png)
this is how i read the glb file,
![image](https://user-images.githubusercontent.com/24249173/83236452-1f5ce680-a1c6-11ea-9048-deb9c5e0d6e7.png)
then i pass the buffer and path to gltfLoader
![image](https://user-images.githubusercontent.com/24249173/83236529-3d2a4b80-a1c6-11ea-8ec9-c6e323ca41ef.png)
then this error comes up..
![image](https://user-images.githubusercontent.com/24249173/83236694-7ebaf680-a1c6-11ea-84d3-78b9a4f1d7aa.png)
this is in the gltfLoader.parse excute context, seems like the content produced by loaderUntils.decodeText wasn't producing the correct JSON string .. please let me know how to fix this... thanks....
![image](https://user-images.githubusercontent.com/24249173/83237032-1b7d9400-a1c7-11ea-9d5f-6819e42bc92c.png)
this is part of the content produced by the loaderUtils.decodeText ,  is that corretct?  i use the same glb file and use gltfloader.load  it worked perfectly

**Comment by constantank** [comment]
![image](https://user-images.githubusercontent.com/24249173/83243993-4ff64d80-a1d1-11ea-89ee-c52fe54047bd.png)
i tried to convert file to ArrayBuffer , still not working ... T.T  anybody please help out,, thanks ,,,,,

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
