### ISSUE TITLE
glTF Loader hard crashes complete macOS !

### ISSUE THREAD

**Issue by indexofrefraction** [mrdoob/three.js#19501]
hi,

the threejs glTF loader immediately crashes my mac
total system freeze, i have to reboot by **hard reset** !!!

this link for example works fine to kill my mac:
https://threejs.org/examples/webgl_loader_gltf.html

macos 10.12.6, safari 12.1.2

**Comment by Mugen87** [comment]
Does this only happen with Safari or with other browser, too?

**Comment by mrdoob** [comment]
A website shouldn't be able to crash a an OS. Please, report this to Apple.

**Comment by indexofrefraction** [comment]
same thing in Firefox (76.0.1), ThreeJS hard crashes the system.
this does not happen with BabylonJS loading / showing a glTF

**Comment by mrdoob** [comment]
Thank you but, unless you mail us your computer, there isn't much we can do about it.
If you want this issue to be fixed, you should report it to Apple and Mozilla as soon as possible.
