### ISSUE TITLE
Question: Why not use typescript file extension in .d.ts

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#19510]
I used `.d.ts` in VSC, it can link `Vector` to `Vector2.d.ts` in this case.

```diff
--- a/src/math/Vector3.d.ts
+++ b/src/math/Vector3.d.ts
@@ -6,7 +6,7 @@ import { Camera } from './../cameras/Camera';
 import { Spherical } from './Spherical';
 import { Cylindrical } from './Cylindrical';
 import { BufferAttribute } from './../core/BufferAttribute';
-import { Vector } from './Vector2';
+import { Vector } from './Vector2.d.ts';
 /**
  * 3D vector.
  *
```

**Comment by donmccurdy** [comment]
I'm not aware that it matters at all, the two should be the same. Is the current syntax causing a problem for anything?

**Comment by linbingquan** [comment]
> I'm not aware that it matters at all, the two should be the same. Is the current syntax causing a problem for anything?

Thank you for your reply.

With you reply, I disabled all plugins in VSC, and I found why it doesn't work, because of `denoland.vscode-deno`.

名称: Deno
ID: denoland.vscode-deno
说明: Deno support for VSCode
版本: 1.24.0
发布者: denoland
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno
