### ISSUE TITLE
Suggestion: Check about tpescript is right or wrong in .d.ts files.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#19524]
I think we need a tool, like `tsc`. Sorry I don't know how to do it...

**Comment by linbingquan** [comment]
related: https://github.com/mrdoob/three.js/issues/11552

**Comment by Mugen87** [comment]
The project is already doing this. Checkout how `tsc` is used in `test-lint`.

https://github.com/mrdoob/three.js/blob/b4473c25816df4a09405c7d887d5c418ef47ee76/package.json#L56

**Comment by linbingquan** [comment]
> The project is already doing this. Checkout how `tsc` is used in `test-lint`.
> 
> https://github.com/mrdoob/three.js/blob/b4473c25816df4a09405c7d887d5c418ef47ee76/package.json#L56

Thank you for your reply. I tried this script `npm run test-lint`, it doesn't work very well, it can't found any error/warning. May be I missed something.

**Comment by Mugen87** [comment]
It works well on my system. Besides, I'm not sure why you refer to #11552. The discussion about TypeScript in this issue is off-topic and unrelated to ES6 classes.

**Comment by linbingquan** [comment]
> It works well on my system.

On my system is:
![image](https://user-images.githubusercontent.com/23699926/83438745-89021c80-a474-11ea-9d17-46bdc55ceeac.png)

> I'm not sure why you refer to #11552. The discussion about TypeScript in this issue was off-topic and unrelated to ES6 classes.

I am sorry, I deleted the related comment, It didn't unrelated with https://github.com/mrdoob/three.js/issues/11552

**Comment by Mugen87** [comment]
Well, right now the command does not produce an output since everything is clean. If you for example remove an import in a `d.ts` file, a respective error should be reported.

**Comment by donmccurdy** [comment]
Note that the `tsc` command is looking at the example and unit test code, and comparing that against the type definitions, to ensure that these uses of the three.js APIs match the uses that the type definitions would allow. This will catch many issues, but not all issues — it cannot guarantee that the type definitions match the actual JS source code completely.

Unfortunately, the TypeScript project has not provided any robust way to compare `d.ts` type definitions to JavaScript source code to detect mismatches more directly.
