### ISSUE TITLE
Error loading OrbitControls through node.js

### ISSUE THREAD

**Issue by flyon** [mrdoob/three.js#19534]
My code is run both in the browser (as bundles) and in nodejs (initial page rendering)

In webpack everything bundles fine and executes fine on the browser.
But when I import OrbitControls.js in NodeJS like so:

    const OrbitControls_1 = require("three/examples/jsm/controls/OrbitControls");

It gives the following error:

    C:\web\resourceful\daCore\node_modules\three\examples\jsm\controls\OrbitControls.js:10
    import {
           ^
    SyntaxError: Unexpected token {

**Comment by Mugen87** [comment]
> const OrbitControls_1 = require("three/examples/jsm/controls/OrbitControls");

`examples/jsm/controls/OrbitControls.js` is a ES6 module so you can't import it via `require`.

It's probably best if you use `esm` and ES6 import syntax for your node script similar to [obj2three.js](https://github.com/mrdoob/three.js/blob/dev/utils/converters/obj2three.js).

Please use the [forum](https://discourse.threejs.org/) if you need more help.
