### ISSUE TITLE
CopyShader opacity does not work as expected

### ISSUE THREAD

**Issue by generesque** [mrdoob/three.js#19531]
##### Description of the problem

In examples/js/shaders/CopyShader.js, there is an issue with the fragment shader:

```
               "void main() {",

		"	vec4 texel = texture2D( tDiffuse, vUv );",
		"	gl_FragColor = opacity * texel;",

		"}"
```

Because `texel` is multiplied by `opacity` directly, all elements of the color are scaled by the opacity value. This means on a black background, the opacity is effectively applied twice. On any other background, the resulting color will end up darker than expect.

Proposed Solution: 

Multiply only the alpha component by opacity:
```
		"void main() {",

		"	vec4 texel = texture2D( tDiffuse, vUv );",
		"	texel.a = opacity * texel.a;",
		"	gl_FragColor = texel;",

		"}"
```

##### Three.js version

- [x] Dev
- [ ] r117
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Yes, likely.

One needs to check the three.js examples where this is used -- used both directly and indirectly.

Check `BlendShader.js`, too.

**Comment by WestLangley** [comment]
I have second thoughts on this...

I trust the original author knew what he was doing back in 2011.

`CopyShader` was designed to copy render target textures, which by default, have premultiplied alpha.

If you want to further scale the opacity, you need to scale all four components.

I would be inclined to revert https://github.com/mrdoob/three.js/pull/23671, and look elsewhere if there are issues.

**Comment by Mugen87** [comment]
> I would be inclined to revert https://github.com/mrdoob/three.js/pull/23671, and look elsewhere if there are issues.

Yes, it seems better to revert the PR. That means however shader materials using `CopyShader` should set their `premultipliedAlpha` property to `true`. Doing this in `TexturePass` fixes the issue mentioned in https://github.com/mrdoob/three.js/pull/23671#issue-1161877574.

https://github.com/mrdoob/three.js/blob/e9b9783c743688ded2c0987751b420b83581c7f7/examples/jsm/postprocessing/TexturePass.js#L23-L31

**Comment by WestLangley** [comment]
I am not sure that is correct. Maybe no-blending.

1. Every post-processing pass needs to have the blending function set properly. I would _not_ use the `transparent` flag -- just set the blending function directly.

2. I expect some of these effects were written assuming no alpha channel. They need to be checked to makes sure the alpha channel is handled properly.

**Comment by Mugen87** [comment]
The problem is that `webgl_postprocessing_backgrounds` blends a textured background with whatever is behind it. Not setting `premultipliedAlpha` to `true` with the previous version of `CopyShader` produces a too dark image.

What is the downside of always setting `premultipliedAlpha` to `true` when `CopyShader` is used?
