### ISSUE TITLE
rollup: npm run dev-test broken.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#19533]
##### Description of the problem

1. `npm run dev-test` happened the entry could not resolve.
2. `npm run test-unit` is not problem.
3. Those are script use the same config file `rollup.unit.config.js`

```
[ROLLUPTEST] rollup v2.10.0
[ROLLUPTEST] bundles unit/three.editor.unit.js → unit\build\three.editor.unit.js...
[ROLLUPTEST] [!] Error: Could not resolve entry module (unit/three.editor.unit.js).
[ROLLUPTEST] Error: Could not resolve entry module (unit/three.editor.unit.js).
```

##### Three.js version

- [x] Dev
- [ ] r117
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Probably related to 3c41b9d59a2362bef3c0e08e8917a461515831b5.

**Comment by munrocket** [comment]
@linbingquan interesting... It's possible to execute rollup in another context?
