### ISSUE TITLE
ArrowHelper: updateMorphTargets is not a function

### ISSUE THREAD

**Issue by geoynomous** [mrdoob/three.js#19540]
##### Description of the problem

 this.updateMorphTargets is not a function
    at new Line (three.module.js:27671)
    at new ArrowHelper (three.module.js:47872)

- [x] r117

##### Browser

- [x] Chrome
- [x] Firefox

##### OS

- [x] macOS

##### Misc

- bundled with parceljs

**Comment by Mugen87** [comment]
Can you please demonstrate the issue with a live example? I've prepared the following fiddle for you: https://jsfiddle.net/fvt1zy8x/1/

**Comment by geoynomous** [comment]
It doesn't show up in the fiddle - only in my setup ... when bundled with parceljs - r116 worked perfect

**Comment by Mugen87** [comment]
`R117` added support for morph target to lines. But I don't understand how this addition could produce the above runtime error. Without the possibility of reproducing, it will be hard to investigate this issue.

**Comment by geoynomous** [comment]
Surely ... I will try to minimize the problem ...

**Comment by geoynomous** [comment]
@Mugen87  sorry .... I found out that LONG time ago, someone enhanced the Line prototype (and thus replacing the one given in r117).
