### ISSUE TITLE
Make WebXR tree-shakable

### ISSUE THREAD

**Issue by munsocket** [mrdoob/three.js#19558]
The current implementation/design of `WebXRManager` (12kb uncompressed) is not tree-shakeable.

Current rollup-bundle-visualizer:

![](https://aws1.discourse-cdn.com/standard17/uploads/threejs/original/2X/e/ea9cd6e6caa53773c23fec6ed09fbc961ad45622.png)

**Comment by munrocket** [comment]
Some discussions have been here #19513

**Comment by munrocket** [comment]
@mrdoob any ideas how to exclude it?

**Comment by Mugen87** [comment]
Closing for now, see https://github.com/mrdoob/three.js/issues/19986#issuecomment-819434208.
