### ISSUE TITLE
WebGLRenderer render type definition

### ISSUE THREAD

**Issue by martinRenou** [mrdoob/three.js#19563]
##### Description of the problem

When using ThreeJS in JavaScript I was able to render only one mesh (without using a Scene) doing:
```javascript
renderer.setRenderTarget(my_target);
renderer.clear();

renderer.render(my_mesh, camera);
```

This is very useful for doing some pre-processing things (in my case, rendering water caustics in shaders using a water mesh as input).

My issue is that I cannot perform the same in TypeScript, the `render` method takes a `Scene` as first argument, so my code does not compile.

Should I open a PR fixing the type definition? I don't see any documentation specifying that my code is valid (that the render method can actually take a mesh as input).

##### Three.js version

r112

**Comment by Mugen87** [comment]
Yes, please update the TS file and docs. It was lately discussed that your approach is valid, see #19477.

**Comment by martinRenou** [comment]
Perfect. I will do that today. Thanks you
