### ISSUE TITLE
BufferAttribute applyMatrix3 method presumes itemSize equals 3

### ISSUE THREAD

**Issue by dumaron** [mrdoob/three.js#19567]
`applyMatrix3` method of `BufferAttribute` presumes that `itemSize` equals 3. This can be seen in the [BufferAttribute source code on line  202](https://github.com/mrdoob/three.js/blob/master/src/core/BufferAttribute.js#L202).
I'm a newbie of three.js and maybe I miss something, but I think that's not always true.
For example, UVs in `ShapeBufferGeometry` have only 2 dimensions.

This led to some `NaN` in the `BufferAttribute`'s array after applying `applyMatrix3`. Maybe it's possible to do a check `itemSize` inside the function to handle this case. For instance, we can use something similar to `Vector2`'s `applyMatrix3` if `itemSize === 2`.

[Here's a sandbox](https://codesandbox.io/s/agitated-cannon-lr7u9?file=/src/index.js) that shows the problem and a simple function based on `Vector2`.

Three.js version: r117
Browser: All of them

**Comment by Mugen87** [comment]
Okay, so your use case is to transform texture coordinates (the `uv` attribute) once by using `BufferAttribute.applyMatrix3()`?

**Comment by dumaron** [comment]
Exactly.

I need to assign a high-res texture to many meshes, but every mesh has its own texture offset/rotation. While I think that the solution proposed in #17766 would be better, I've learned that the only way to achieve this effect without duplicating the texture is by updating geometry's uv coordinates.

`setUvTransform` can prevent difficult calculations (especially when the rotation point isn't 0,0).
Applying the matrix to the `uv` attribute would end in a very simple way to achieve the effect.

I don't have enough knowledge of three to say if this would be useful with `Matrix4`.

**Comment by WestLangley** [comment]
Your use case seems compelling to me. It sounds like a texture atlas.

Can you explain why you are making the uv mods in three.js rather than in a modeling app?

**Comment by dumaron** [comment]
It's not texture atlas, my textures are large photos of marble.
And there's no modeling app: I'm creating my `ShapeBufferGeometry` from svg files.

**Comment by Mugen87** [comment]
> Your use case seems compelling to me.

Agreed. @dumaron Do you want to make PR with your proposed fix?

**Comment by dumaron** [comment]
Yeah, of course, I'll make it during this week Thanks!
