### ISSUE TITLE
Duplicated imports in output bundle

### ISSUE THREAD

**Issue by Zydnar** [mrdoob/three.js#19571]
##### Description of the problem
When using webpack and babel  in compiled code I see a lot of duplicated code mostly because of inconsistent import paths, so some modules are imported more than once.
![obraz](https://user-images.githubusercontent.com/20562545/83895807-7f6a0480-a753-11ea-986a-1427cbe278b5.png)
For eg. `Matrix4` is imported twice and it takes a lot of space. I'll investigate it further, it may be mainly problem with loaders I took from examples. Because some of them import directly modules (how it should be done to minify output bundle) and some import the modules from `src/three.js` what causes importing everything.
These are all three imports in my project:
![obraz](https://user-images.githubusercontent.com/20562545/83897427-e1c40480-a755-11ea-8c7e-63a7c34fb3e4.png)

##### Three.js version

- [x] Dev
- [x] r117
- [x] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
We do not recommend importing directly from the `three/src` directory — instead, use the npm package:

```js
import { Scene, WebGLRenderer, Mesh, ... } from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
// ... similar for other examples/jsm/... imports
```

All packages in `examples/jsm` reference the core library's build output, not the unbundled source code, so the syntax above is required to avoid duplicate imports.

**Comment by Zydnar** [comment]
Ok, thanks for the tip :)
