### ISSUE TITLE
Questions: Vector object's properties.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#19579]
Excuse me, I have two simple questions, maybe I missing sommting.

1. Why `Vector3` doesn't have `width` and `height` properties like `Vector2` and `Vector4`.
2. Why use `Vector4.z` alias width `Vector4.w` alias height, not like `Vector2.x` alias width  `Vector2.y` alias height.

https://github.com/mrdoob/three.js/blob/5eb71d512248a35a9d30cf9e5c6bfc294a16f9bd/src/math/Vector2.js#L15-L49

https://github.com/mrdoob/three.js/blob/5eb71d512248a35a9d30cf9e5c6bfc294a16f9bd/src/math/Vector4.js#L18-L52

**Comment by WestLangley** [comment]
`Vector4` can be used to size a viewport: `x`, `y`, `width`, `height`.

`Vector2` can be used to size a canvas: `width`, `height`.

**Comment by DefinitelyMaybe** [comment]
ah. I was wondering about these extra property names too. makes sense now.
