### ISSUE TITLE
Error while getting pixel data from image

### ISSUE THREAD

**Issue by Dvasik** [mrdoob/three.js#19578]
##### Description of the problem
Hi, I'm trying to get pixel data from image using code from #7647, but I'm getting an error
TypeError: Cannot read property 'width' of undefined
But image data loads successfully.
Here is a snapshot
```
getImageData = (image) => {
    let canvas = document.createElement('canvas');
    canvas.width = image.width;
    canvas.height = image.height;

    let context = canvas.getContext('2d');
    context.drawImage( image, 0, 0 );

    return context.getImageData( 0, 0, image.width, image.height );
  };

  getPixel = (imageData, x, y) => {
    let position = ( x + imageData.width * y ) * 4; 
    let data = imageData.data;
    return { r: data[ position ], g: data[ position + 1 ], b: data[ position + 2 ], a: data[ position + 3 ] };
  };
```
```
import heightmap from '../bin/textures/hm2.jpg';
. . . 
let loaderImg = new THREE.ImageLoader();
    loaderImg.load(heightmap, (image) => {
      this.imagedata = this.getImageData(image);
    });
```
##### Three.js version

- [ ] Dev
- [x] r117
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Seems to work just fine: https://jsfiddle.net/e4Lr5xzp/1/

Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need more help.
