### ISSUE TITLE
The build wiki seems outdated

### ISSUE THREAD

**Issue by CgGraphic** [mrdoob/three.js#19586]
##### Description of the problem

The three.min.js is not generated as the Wiki/Build instructions suggest

```
Run the build script.
npm run build
The compiled file is at three.js/build/three.min.js, with three.js being the uncompressed concatenated file.
```

**Comment by DefinitelyMaybe** [comment]
So yes, the wiki is very out-of-date. As to getting a min-script, I think you'll find `npm run build-closure` is what you're looking for

**Comment by Mugen87** [comment]
Updated `Build instructions` right now. The build artifacts should be explained now correctly.

https://github.com/mrdoob/three.js/wiki/Build-instructions

**Comment by DefinitelyMaybe** [comment]
There is the question as to whether we keep using the github wiki for this kind of dev info or use the `.github` folder instead? your thoughts?

**Comment by Mugen87** [comment]
Wiki seems fine to me.
