### ISSUE TITLE
Support for TrackballControls to lock rotation about axes

### ISSUE THREAD

**Issue by Sairony** [mrdoob/three.js#19597]
I need camera controls similar to how it's done in popular 3D modelling programs, TrackballControls seems to be the one which is the closest. However it rolls, which makes it hard to use for that purpose, it would be nice if it was possible to constrain the rotation around certain axes. OrbitControls are pretty close as well but can't pan in the Y axis it seems.

**Comment by Mugen87** [comment]
You're post is a bit vague and the feature request is not clear to me yet. Can you please describe the expected result in more detail?

**Comment by WestLangley** [comment]
Try `orbitControls.screenSpacePanning = true;` to pan in any direction.

**Comment by Sairony** [comment]
`screenSpacePanning` was the way to go for my case!

What I meant about locking rotation about axes is that you'd have something like:
`controler.lockRotation( ENUM_Z );` in the update loop you'd then remove all the delta Z rotation, which would make it impossible for the controller to introduce unwanted yaw. Yaw overall for a lot of use cases seems unwanted for cameras, since you generally want to be aligned with the XZ plane ( looking at things up side down is often not needed for example ).

**Comment by mrdoob** [comment]
> Try `orbitControls.screenSpacePanning = true;` to pan in any direction.

I keep struggling with this one. I feel like this should be the default. It makes sense for this to be `false` on `MapControls` but on `OrbitControls` it doesn't feel right to me.

**Comment by WestLangley** [comment]
@mrdoob OK, I can change it...

Thing is, I do not like having a property `foo: true`, unless it is obvious what "not foo" is.

I prefer `foo: false` by default in that case.

**Comment by mrdoob** [comment]
I see...

What do you think about doing it like this?

```js
			if ( scope.isMapControls === true ) {

				v.setFromMatrixColumn( objectMatrix, 0 );
				v.crossVectors( scope.object.up, v );

			} else {

				v.setFromMatrixColumn( objectMatrix, 1 );

			}
```

**Comment by WestLangley** [comment]
I see. You are hardwiring the panning method.

Given that you want to make a change, I think I prefer #19602, which retains flexibility.
