### ISSUE TITLE
InstancedBufferGeometry.instanceCount incorrectly

### ISSUE THREAD

**Issue by sanddyl** [mrdoob/three.js#19595]
##### Description of the problem
When I changed InstancedBufferGeometry.instanceCount, I found that the _maxInstanceCount not changed. This will cause the InstancedBufferGeometry to display incorrectly.
![W99N1@YTXLI_7BMX7TOGX51](https://user-images.githubusercontent.com/1051839/84094329-2fc75980-aa2f-11ea-9ca8-c33b52ab7238.png)

##### Three.js version

- [ ] Dev
- [x] r117
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
@sanddyl Can you please provide a simple, live demo to show exactly what you did to cause the issue?

**Comment by sanddyl** [comment]
> @sanddyl Can you please provide a simple, live demo to show exactly what you did to cause the issue?

https://jsfiddle.net/s3xco4hk/95/

**Comment by WestLangley** [comment]
You are resizing the attribute buffer. That is not supported.

See https://threejs.org/docs/#manual/en/introduction/How-to-update-things.

/ping @Mugen87 for confirmation.

**Comment by sanddyl** [comment]
> You are resizing the attribute buffer. That is not supported.
> 
> See https://threejs.org/docs/#manual/en/introduction/How-to-update-things.
> 
> /ping @Mugen87 for confirmation.

I quite agree,but when I need to modify maxInstanceCount, instanceCount can not achieve my purpose, even if this is rare. I mean, the instanceCount in version 117 is not equal to the maxInstancedCount in the previous version.

**Comment by sanddyl** [comment]
> You are resizing the attribute buffer. That is not supported.
> 
> See https://threejs.org/docs/#manual/en/introduction/How-to-update-things.
> 
> /ping @Mugen87 for confirmation.

Maybe both maxInstancedCount and instanceCount are required.

**Comment by Mugen87** [comment]
Yes, buffers can't be resized. The idea is to create a sufficient sized buffer and then control via `drawRange` or `instanceCount` the rendering. This approach is demonstrated by [webgl_buffergeometry_instancing](https://threejs.org/examples/webgl_buffergeometry_instancing).

> Maybe both maxInstancedCount and instanceCount are required.

Nope. It does work by just using `instanceCount`. Check out how the updated fiddle controls the amount of rendered instances. 

https://jsfiddle.net/brs1f5oa/

**Comment by sanddyl** [comment]
Thanks a lot ! I will avoid such problems in the future.
