### ISSUE TITLE
WebGLRenderTarget: .clone() does not clone framebuffer/texture data.

### ISSUE THREAD

**Issue by JohannesDeml** [mrdoob/three.js#19598]
##### Description of the problem

When cloning an equirectangular CubeTexture the result is a black texture. 
The same operation does work with a CubeTextureLoader loaded texture (with 6 images).

![grafik](https://user-images.githubusercontent.com/4518980/84148048-afb8e800-aa5e-11ea-9f32-e9c07968c1c6.png)
No map after clone()

* [jsfiddle clone](https://jsfiddle.net/JohannesDeml/46z8w0bg) (latest release branch)
* [jsfiddle clone](https://jsfiddle.net/JohannesDeml/yq15zdcn) (dev branch)

##### Three.js version

- [ ] Dev
- [ ] r117

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

## Resolved

When using refraction for an equirectangular texture with `EquirectangularRefractionMapping`, using it as a background does not work, an the mapping has wrong seams. For CubeTextureLoader with `CubeRefractionMapping` both of that works (see [cubemap refraction](https://github.com/mrdoob/three.js/blob/master/examples/webgl_materials_cubemap_refraction.html)).

![grafik](https://user-images.githubusercontent.com/4518980/84149220-65386b00-aa60-11ea-800b-75d5c9f002cd.png)
wrong background rendering & seam 

* [jsfiddle refraction](https://jsfiddle.net/JohannesDeml/fo4ny2dv/5/) (dev branch)

**Comment by Mugen87** [comment]
> When cloning an equirectangular CubeTexture the result is a black texture.

This use case is a bit tricky since you are actually cloning a texture from a render target (meaning `WebGLRenderTarget.texture`). This clone does not automatically clone the render targets contents (meaning the respective frame- and renderbuffers and their data).

**Comment by JohannesDeml** [comment]
> 
> 
> > When cloning an equirectangular CubeTexture the result is a black texture.
> 
> This use case is a bit tricky since you are actually cloning a texture from a render target (meaning `WebGLRenderTarget.texture`). This clone does not automatically clone the render targets contents (meaning the respective frame- and renderbuffers and their data).

Thanks a lot for your response! Hm, I see. My idea was to point two CubeTextures on the same underlying texture. This seems to be necessary, because I have materials with reflections and some with refractions. I tried setting cubeTexture.image, but that didn't do the trick either.

**Comment by Mugen87** [comment]
When looking closely the returned render target of `PMREMGenerator` is actually of type `WebGLRenderTarget` and the texture of type `Texture`.

**Comment by Mugen87** [comment]
Besides, `EquirectangularRefractionMapping` and `EquirectangularReflectionMapping` can only be used with equirectangular textures (see [webgl_materials_envmaps](https://threejs.org/examples/webgl_materials_envmaps). When using `PMREMGenerator`, the environment map is in a different format after the conversion process (`CubeUV`). 

You also want to use the output only with a PBR material (`MeshStandardMaterial` and `MeshPhysicalMaterial`) and not with e.g.  `MeshBasicMaterial`. Such a material does not have the shader code to evaluate such an env map.

**Comment by JohannesDeml** [comment]
> the environment map is in a different format after the conversion process (`CubeUV`)

Ah, thanks a lot for pointing me in the right direction here. This solves one of the described problems (the seams). Still, I think there are a few inconsistencies here:

* using the cubetexture for background does not work when mapping is set to `CubeUVRefractionMapping` (For Cube Textures this works)
* cloning does not work

I updated the refraction version:
https://jsfiddle.net/JohannesDeml/fo4ny2dv/
![grafik](https://user-images.githubusercontent.com/4518980/84159951-f235f100-aa6d-11ea-8eed-bbf221fd2ce0.png)

**Comment by Mugen87** [comment]
> using the cubetexture for background does not work when mapping is set to CubeUVRefractionMapping (For Cube Textures this works)

As you can see here `CubeUVRefractionMapping` has no impact on the shader code yet since applying it to an env map does change the environment map mode.

https://github.com/mrdoob/three.js/blob/9ca100f2d84d5f24e8877d29f920637cae415f9a/src/renderers/webgl/WebGLProgram.js#L335-L354

In any event, I'm not sure I understand the use case of applying refraction mapping to a skybox. Do you mind explain in more detail why this is useful?

**Comment by JohannesDeml** [comment]
My idea is to load just one env map (preferably a PMREM to do IBL) which I can use for reflections, refractions and the skybox.

As for the skybox: I do understand, that a refraction mapping background does not make that much sense, but it is working for [CubeRefractionMapping example](https://threejs.org/examples/?q=refraction#webgl_materials_cubemap_refraction) as well as [CubeUVReflectionMapping example](https://threejs.org/examples/?q=gltf#webgl_loader_gltf), so I would expect it also works for `CubeUVRefractionMapping`. So for the skybox I just feel that it is inconsistent with other behavior. I would expect, that it is rendered as a reflection map as it does for `CubeRefractionMapping `.

**Comment by Mugen87** [comment]
I have not investigated yet why `CubeRefractionMapping` works when using an envmap as a skybox but it shouldn't. I guess I would prefer to report a warning in this case.

For me the only valid feature request is the ability to clone render targets. I have not found an existing issue that discussed this topic in the past. Using this one to track the feature request might be sufficient for now.

**Comment by JohannesDeml** [comment]
> I guess I would prefer to report a warning in this case.

Sounds like a good solution. I agree, that it is kind of strange that it works.

> For me the only valid feature request of this issue is the ability to clone render targets. 
Yes, I'm with you on that. Thanks for pointing me in the right direction with the mapping type. The docs are missing that description, I will add that today :)

**Comment by Mugen87** [comment]
The `clone()` methods in `three.js` turned out to be problematic in various classes. They work well with math primitives but cloning more complex objects is problematic since it is not always possible to replicate the "correct" object state. This is especially true for render targets. After reconsidering this issue, it's just not feasible to copy framebuffer data for cloned render targets. So `WebGLRenderTarget.clone()` just creates a new render target with the same configuration but not with copied data.
