### ISSUE TITLE
I expect have a controls can support zoomed and rotated with the current mouse position in screen

### ISSUE THREAD

**Issue by liuyehua** [mrdoob/three.js#19599]
such as navisworks viewer behavior。。。

**Comment by WestLangley** [comment]
Do you mean #17145? It zooms to cursor, but rotates around center -- not the projected cursor position.

**Comment by liuyehua** [comment]
> Do you mean #17145? It zooms to cursor, but rotates around center -- not the projected cursor position.

yes...this question some example google can find all have rotate problem... I feel it is very difficult for me to realize this function...

**Comment by WestLangley** [comment]
>all have rotate problem

Sorry, I do not understand what rotation behavior you want. A video would be helpful.

**Comment by liuyehua** [comment]
> > all have rotate problem
> 
> Sorry, I do not understand what rotation behavior you want. A video would be helpful.

https://api.bimface.com/preview/16442f9e ，such as this site you will find  you can make current mouse cursor position in screen  as zoom and rotate‘s  center.  

The autodesk's navisworks is the same logic。。。

**Comment by liuyehua** [comment]
> > all have rotate problem
> 
> Sorry, I do not understand what rotation behavior you want. A video would be helpful.

the orbitcontrols rotate target always in the center of screen，

> > all have rotate problem
> 
> Sorry, I do not understand what rotation behavior you want. A video would be helpful.

such as obrit controls the rotation center always in the center of screen,  it have many problems when I want to zoom by the mouse cursor position。。。

**Comment by WestLangley** [comment]
Sorry, I find the rotation behavior in https://api.bimface.com/preview/16442f9e very confusing.

Zooming to cursor makes sense to me; rotating around the cursor does not. Maybe someone else has a different opinion...

**Comment by marquizzo** [comment]
I'm with @WestLangley on this one. Rotating around the cursor is very un-intuitive and can quickly move the model off-screen, making it difficult to bring it back on.

![rotate](https://user-images.githubusercontent.com/7864858/84200369-7f237f00-aa5b-11ea-8efb-4d4b604e2604.jpg)

**Comment by WestLangley** [comment]
>The autodesk's navisworks is the same logic

This video explains how zooming and rotating work in Navisworks: https://youtu.be/9CAoruSqA4A?t=78

A "pivot point" is set using a raycaster-like feature.

I do not see three.js implementing an API like that.

**Comment by liuyehua** [comment]
> > The autodesk's navisworks is the same logic
> 
> This video explains how zooming and rotating work in Navisworks: https://youtu.be/9CAoruSqA4A?t=78
> 
> A "pivot point" is set using a raycaster-like feature.
> 
> I do not see three.js implementing an API like that.

yes...The other important feature is you can directly zoom in or out at your mouse position ，and the orbit controls you must use mouse right button move the you want scene to the screen center。。。

**Comment by Mugen87** [comment]
> The other important feature is you can directly zoom in or out at your mouse position 

But this should be implemented via #17145.

**Comment by Mugen87** [comment]
Closing. I think it makes senes to focus on #17145 in order to bring "zoom-to-cursor" in production.
