### ISSUE TITLE
WebXRManager - Allow changing/setting the reference space

### ISSUE THREAD

**Issue by dbuck** [mrdoob/three.js#19615]
##### Description of the problem
As a dev, I'd like to align the XR view to an arbitrary space. It would help to be able to set an offset reference space for the WebXRManager, to be used when reading the getViewerPose and getPose from the XRFrame.

Proposing:
```
// add an override reference space to use for reading XR poses
renderer.xr.setOffsetReferenceSpace(space: XRReferenceSpace);

// reset to the initial reference space
renderer.xr.resetReferenceSpace();
```

WebXRManager.onAnimationFrame : if there is an offsetReferenceSpace set, prefer that space while reading the poses for the player/controllers during the `onAnimationFrame`
```
frame.getViewerPose(offsetReferenceSpace || referenceSpace)
frame.getPose(offsetReferenceSpace || referenceSpace)
```

Usage:
```
// Shift to an arbitrary position/alignment!

// From the base tracking space.
const baseReferenceSpace: XRReferenceSpace = renderer.xr.getReferenceSpace();

// offset the rotation by 30 degress
const playerRotation = new Quaternion().setFromAxisAngle(new Vector3(0, 1, 0), MathUtils.DEG2RAD * 30);
const offsetRotation = { x: playerRotation.x, y: playerRotation.y, z: playerRotation.z, w: playerRotation.w };

// offset the tracking to center on our player
const playerPosition = new Vector3(100, 1, 30);
const offsetPosition = { x: playerPosition.x, y: playerPosition.y, z: playerPosition.z, w: 1 };

const transform = new XRRigidTransform(offsetPosition, offsetRotation);
const viewerSpace = baseReferenceSpace.getOffsetReferenceSpace(transform);

renderer.xr.setOffsetReferenceSpace(viewerSpace);
```

This will enable use of the native webxr XRRigidTransform and XRReferenceSpace for locomotion/movement without requiring the controllers + cameras conform to a specific hierarchy with the camera.parent to be placed at the guess of the floor location.

The controllers already support alternate reference frames now by way of the `WebXRController.update(inputSource, frame, referenceSpace)` call, which is great, however without a way to set a referenceSpace on the WebXRManager:
1: It only has a visible effect on the view if done in the scene.onBeforeRender (?)
2: Shifting the controllers to a custom reference space duplicates the updates for everything in that hierarchy, which was more perf impactful than I'd imagined when using the XRControllerModelFactory controllers attached.

Note: It *is* technically possible to use XRTransforms/XRReferenceSpace style currently, but requires a lot of ugly workarounds and intimate knowledge of what WebGLRenderer/WebXRManager is doing and when.
- Noticing that the WebXRManager onAnimationFrameCallback includes the XRFrame in the callback, and storing/referencing the XRFrame in your setAnimationLoop.
- Inserting a callback into scene.onBeforeRender to read the `frame.getViewerPose(myCustomReferenceSpace)`, and apply to the cameras.
- very fragile!

**Comment by traviskaufman** [comment]
FWIW babylon.js has a [setTransformationFromNonVRCamera](https://github.com/BabylonJS/Babylon.js/blob/e4543e597f4a651ecca4f00fb93c72a123c0353b/src/XR/webXRCamera.ts#L128) function, as well as it looks like a [compensateOnFirstFrame](https://github.com/BabylonJS/Babylon.js/blob/e4543e597f4a651ecca4f00fb93c72a123c0353b/src/XR/webXRDefaultExperience.ts#L109) property that seems to enforce this behavior when you enter the scene. I'm wondering if there's any chance of adding similar functionality in THREE? Sorry if this is the wrong place to raise this issue, but they seem related!

**Comment by arodic** [comment]
Hey @mrdoob I closed #20949 because I was under the impression that WebXRLayers will solve this problem. But after looking into it I'm not even sure I understand what WebXRLayers are. Will this feature enable reference space offsets?

**Comment by mrdoob** [comment]
@arodic no idea...
@cabanier do you know?

**Comment by cabanier** [comment]
I don't think WebXR Layers will help in this regard as projection layers have the same semantics as the WebGL Layers.
This sound more like a three.js refactor so the author can pass offset reference spaces to do locomotion.

**Comment by sophiabaldonado** [comment]
I'm interested in setting an offset reference space, as well. Will #20949 be reopened?

**Comment by carstenschwede** [comment]
This is a must have if you do any AR with THREE.js and you want to align a scene with the real world. Transforming the scene instead of the XRCamera will change world transforms. Setting an *OffsetReferenceSpace* is the only correct way to do this. #20949 (without the controllermove events) should be an uncontroversial change. It doesn't break previous behaviour and adds a functionality suggested by the WebXR spec which helps tremendously with aligning AR scenes.

**Comment by arodic** [comment]
I removed the controversial change (controllermove events) from #20949.

**Comment by lvignals** [comment]
+1
Same here, I need to change the scene offset using an XRRigidTransform object as a paramter to xrReferenceSpace.getOffsetReferenceSpace(xrRigidTransform);  to simulate a player movement in space, but then no matter how I try to apply the returned adjusted XRReferenceSpace, it does not update the position of the player in the immersive-xr session. Player remains on top of the origin no matter what?

**Comment by danrossi** [comment]
Is this not possible ? Ive made a question elsewhere. My headset session starts the camera at the wrong position compared to the position it is in non webxr. 

The examples produce the behaviour I am seeing on my own videos. starts tilted to the right of the front. I have to turn my head to the left to get the front. 

https://dev.electroteque.org.s3.amazonaws.com/three/examples/webgl_video_panorama_equirectangular.html

https://discourse.threejs.org/t/initial-webxr-position-same-as-camera-position/36682/2

**Comment by danrossi** [comment]
This is very strange, without a position set, the video starts 90 degrees to the real front of the camera. but in webxr it starts 180 degrees from that position. WebXR camera really needs to take the initial position from the non webxr camera. Even if I shift the geometry instead. It will show flipped in webxr and you need to turn the headset to the left. 

https://dev.electroteque.org.s3.amazonaws.com/three/examples/webgl_video_panorama_equirectangular.html

**Comment by danrossi** [comment]
Another test with a rotated mesh. WebXR starts in the opposite direction. https://dev.electroteque.org.s3.amazonaws.com/three/examples/webgl_video_panorama_equirectangular3.html

**Comment by danrossi** [comment]
I made another test that provides a quick fix. I position the camera to the front. Then I have to flip the mesh in webXR and the opposite direction. Then move it back. 

    renderer.xr.addEventListener('sessionstart', () => {

                    mesh.rotation.y =  -pos;

                    renderer.xr.getCamera().position.copy( camera.target);

                    renderer.xr.getCamera().lookAt( camera.target );

                  

                });

                renderer.xr.addEventListener('sessionend', () => {

                    mesh.rotation.y =  0;

                    camera.position.x = pos;

      
                });

https://dev.electroteque.org.s3.amazonaws.com/three/examples/webgl_video_panorama_equirectangular4.html

**Comment by Mugen87** [comment]
Fixed via #20949.

**Comment by danrossi** [comment]
I dont know what this is supposed to do but I cant shift the webxr camera back to where it is in the non webxr camera. Its rotated to the left or right of the camera. I was assuming this offset can change it back but doesn't do it as expected.

**Comment by DLGL99GL** [comment]
setReferenceSpace setted offset on baseReferenceSpace; but can i create a new referenceSpace and change its position and rotation by scripts，not used offset?   
I tested it, but found that most of the API was read-only and couldn't be modified，is other way to implement this function？

**Comment by cabanier** [comment]
> setReferenceSpace setted offset on baseReferenceSpace; but can i create a new referenceSpace and change its position and rotation by scripts，not used offset? I tested it, but found that most of the API was read-only and couldn't be modified，is other way to implement this function？

`getOffsetReferenceSpace` passes in a transform so you can use it to change position and rotation.
Wouldn't that work for you?

**Comment by DLGL99GL** [comment]
> > setReferenceSpace setted offset on baseReferenceSpace; but can i create a new referenceSpace and change its position and rotation by scripts，not used offset? I tested it, but found that most of the API was read-only and couldn't be modified，is other way to implement this function？
> 
> `getOffsetReferenceSpace` passes in a transform so you can use it to change position and rotation. Wouldn't that work for you?
it worked,but not what I expected;
i want change Hittest -orgin/direction;i tried to use the API: OffsetRay, So far ,it seems to offsetReferenceSpace too;
so i tried to change ReferenceSpace by getOffsetReferenceSpace ;
as you see ,i change the origin.z,and the same diretion that facing down horizontally in the world system;
what i wanted is that all the result of hittest ,It's under thehorizontal  axis; But it's slowly going above the horizontal axis;
i think there may same error in Hittest offset ReferenceSpace,so i  wanted to set the position or ratition by ReferenceSpace.position.set(x,y,z) not by offset

![4E71FA95-C3D7-4835-A9DA-36B53D9BFFA8](https://user-images.githubusercontent.com/69023459/182659951-c7569e4b-6ff3-4091-9c60-a2aec06cf52e.png)
```
					let origin = new THREE.Vector3(0,0,times/10)
					console.log(origin)
					let direction = new THREE.Vector3(0,-0.2,-1)
					direction.normalize()
					let _x = direction.x
					let _y = direction.y
					let _z = direction.z
	
					const transform = new XRRigidTransform( {x : origin.x, y : origin.y, z : origin.z, w : 1.0} , {x : _x, y : _y, z : _z, w : 0.0});
					const teleportSpaceOffset = baseReferenceSpace.getOffsetReferenceSpace( transform );

					session.requestHitTestSource( { space: teleportSpaceOffset } ).then( function ( source ) {

						hitTestSource = source;

					} );
					times--;
```
