### ISSUE TITLE
PMREM Refraction support

### ISSUE THREAD

**Issue by JohannesDeml** [mrdoob/three.js#19611]
##### Description of the problem

PMREM seems to miss support for refraction mapping even though the mapping option `CubeUVRefractionMapping` exists.

Comparison between enabled refraction of Equirectangular vs PMREM:

![firefox_2020-06-10_12-26-46](https://user-images.githubusercontent.com/4518980/84258921-02a2a600-ab18-11ea-9dd9-fa5745289849.jpg)
Equirectangular with `EquirectangularRefractionMapping`

![firefox_2020-06-10_12-27-00](https://user-images.githubusercontent.com/4518980/84258966-1221ef00-ab18-11ea-94ba-d054d6d553de.jpg)
PMREM with `CubeUVRefractionMapping`

I extended the envmaps example to show the problem:
* [demo](https://deml.io/three/examples/webgl_materials_envmaps.html) (dev branch)
* [file](https://github.com/JohannesDeml/three.js/blob/test/pmrem-refraction/examples/webgl_materials_envmaps.html)

##### Three.js version

- [ x ] Dev
- [ x ] r117
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Related: Does GLTF support refraction?

**Comment by donmccurdy** [comment]
> Related: Does GLTF support refraction?

Not yet, and the upcoming [KHR_materials_transmission](https://github.com/mrdoob/three.js/pull/19690) doesn't either, but refraction is on the roadmap and will build on the `transmission`/`transmissionMap` parameters. A very rough guess would be sometime in 2021.
