### ISSUE TITLE
 How about adding the makeScaleAlong method to the matrix4？

### ISSUE THREAD

**Issue by sanddyl** [mrdoob/three.js#19624]
```
// matrix that scales along normalized vector n by scale value k
Matrix4.prototype.makeScaleAlong = function ( n, k ) {
    var _k = k-1;
    var xy = n.x * n.y;
    var xz = n.x * n.z;
    var yz = n.y * n.z;
    var xAxis = new Vector3(
      1 + _k * n.x * n.x,
        _k * xy,
        _k * xz
    );
    var yAxis = new Vector3(
        _k * xy,
        1 + _k * n.y * n.y,
        _k * yz
    );
    var zAxis = new Vector3(
        _k * xz,
        _k * yz,
        1 + _k * n.z * n.z
    );
    return this.makeBasis(xAxis, yAxis, zAxis);
};
```

**Comment by Mugen87** [comment]
I'm afraid this method is way to use-case specific.

**Comment by sanddyl** [comment]
Calculate the miter of TubeGeometry.
![image](https://user-images.githubusercontent.com/1051839/84455787-d0688400-ac90-11ea-8525-2055b6c9e9b6.png)

**Comment by Mugen87** [comment]
Thanks for sharing the code. But as long as no more people request such a method, it's more appropriate to not include in the library.

Please keep in mind that `three.js` is not a math library. The existing math API represents the actual amount of methods frequently used in the library and app level code.
