### ISSUE TITLE
Line2 disappears if scale is set to negative on a single axis

### ISSUE THREAD

**Issue by jacopocolo** [mrdoob/three.js#19629]
As the title say: a [Line2](https://github.com/mrdoob/three.js/blob/r98/examples/js/lines/Line2.js) disappears completely when the scale is set to negative on a single axis `line2.scale.set(-1, 1, 1)`. The line is obviously still there but it's not rendered. 

Weirdly, if the scale is set to negative on more than one axis `line2.scale.set(-1, -1, 1)`, the line appears again. 

Here's a jsfiddle that demonstrates the issue: https://jsfiddle.net/jacopocolo/5fsotdpw/16/
Toggling `wireframeToggle` on line 7 to true shows two Line2 in wireframe but if `wireframeToggle` is set to false, only one is visible. 

##### Three.js version

- [ ] Dev
- [x] r117
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS (only tested here)
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by WestLangley** [comment]
Set
```js
side: THREE.DoubleSide
```

**Comment by jacopocolo** [comment]
😍 thank you so much! Closing this!

**Comment by nkallen** [comment]
Hi,

Have you guys considered making renderBufferDirect a little more modular? Like

```js
 		const frontFaceCW = ( object.isFrontFaceWhenNegativeDeterminant && object.matrixWorld.determinant() < 0 );
```

Which would allow solutions like Line2 to override this value without it having to migrate from examples to the main codebase?

**Comment by WestLangley** [comment]
@nkallen I do not think we would be inclined to modify the renderer to accommodate an example.
