### ISSUE TITLE
MeshSurfaceSampler does not use last triangle

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#19632]
It seems that MeshSurfaceSampler doesn't sample the last triangle in the list.

It's not noticeable in geometry with a lot of triangles but when using it on a simple mesh it's pretty clear. You can see the issue here:

https://jsfiddle.net/veL98dgm/

I haven't dug too deeply into it but the distribution winds up being set to `[ 0.5, 1.0 ]` in this case but the `binarySearch` function is always returning 0.

/ping @donmccurdy 

Also thanks for adding this class -- it's an awesome tool!

**Comment by Mugen87** [comment]
This only happens when the geometry has a triangle count of 2. In all other cases, it works as expected:

https://jsfiddle.net/f7gah0dn/

**Comment by gkjohnson** [comment]
It seems to happen with this cube, as well, so there must be some other pattern that it occurs with:

https://jsfiddle.net/cywfp5em/1/

**Comment by Mugen87** [comment]
Maybe it makes a difference if the triangle count is odd or even?

**Comment by donmccurdy** [comment]
That sounds like the right diagnosis, thanks — likely an edge case in the binary search implementation for an even number of triangles.
