### ISSUE TITLE
A GUI Editor & framework for three.js 

### ISSUE THREAD

**Issue by xiaoguzhu** [mrdoob/three.js#19633]
HI, I have created a GUI Editor & framework for three.js. It greatly reduces the difficulty of using three to make complex UI. It's also open source.

[](https://github.com/fairygui/FairyGUI-threejs)

**Comment by Mugen87** [comment]
The [forum](https://discourse.threejs.org/) is the best place for sharing such showcases/resources.

https://discourse.threejs.org/t/a-gui-editor-framework-for-three-js/16156
