### ISSUE TITLE
MTLLoader doesn't work properly

### ISSUE THREAD

**Issue by amir04lm26** [mrdoob/three.js#19643]
Hi there,
I've been trying to load an image using OBJLoader and MTLLoader but the texture doesn't load properly.

Also created an issue in discourse.threejs.org, No solution's found there. And here it's the link:
https://discourse.threejs.org/t/texture-doesnt-load-correctly/16131/10

This is the image that I want to load :
https://free3d.com/3d-model/rose-31675.html

It's load correctly in windows 3DLoader but in three.js, It's a black rose.

![image](https://user-images.githubusercontent.com/40991530/84560581-ac717500-ad5a-11ea-8b3c-274a1a01b9ae.png)

![photo_2020-06-11_23-01-06](https://user-images.githubusercontent.com/40991530/84560543-7502c880-ad5a-11ea-87b8-4f55b65bfbd2.jpg)

**Comment by Mugen87** [comment]
I originally wanted to answer in the forum but you have already created this issue at GitHub^^. Please give the community a bit more time to answer at your forum posts before creating a bug report here.

In any event, the `MTLoader` only implements strictly the "inofficial" standard. Your model contains a `Kd` entry which represents the diffuse color and a `map_Kd` entry which represents a diffuse color texture. E.g.

```
Kd 0.00 0.00 0.00
map_Kd grass_texture225.jpg
```
So the diffuse color is black. The [MTL spec](http://paulbourke.net/dataformats/mtl/) says: `material diffuse is multiplied by the texture value`. And that means all final color values are black in your case.

You can easily fix the issue my making all `Kd` values to `1.00 1.00 1.00`. Actually it's the same issue like #13728.

Please use the forum if you need more help.

**Comment by amir04lm26** [comment]
Thanks, It's working.
