### ISSUE TITLE
Feature Request: Additional algebraic operations for matrices

### ISSUE THREAD

**Issue by Bgeninatti** [mrdoob/three.js#19657]
I noticed that there are no addition or subtraction methods for `Matrix3` or `Matrix4`, but there are for `Vector3` and `Vector4`. 

This features implies a minor changes in code and ends to be basic algebraic operations with several use cases.

i.e.: I would like to implement [Classic Rodrigues Paramters](https://en.wikipedia.org/wiki/Rodrigues%27_rotation_formula) and [Modified Rodrigues Paramters](https://link.springer.com/epdf/10.1007/s10851-017-0765-x?author_access_token=BtihXbCvDW565MIUIn0J5ve4RwlQNchNByi7wbcMAY7AH-pgW8pWvli9IdibeaB5wRzTRnKtlbXW5EO_TnYSEAxs0p4dihIwK8RCqBngFEMooJg0hWvTX39JrNoyl3Bi3wSbNb8-msaGtM_EoMkxiQ%3D%3D) attitude representations for a simulation tool. Addition and subtraction are crucial for this purpose.

Thanks and regards.

**Comment by WestLangley** [comment]
`Matrix4` in three.js represents an affine transformation or projection for which multiplication makes sense; addition does not. Similarly for `Matrix3`.

Are you using these classes to represent something else in your app?

Also, I assume you are familiar with the axis-angle methods in `Vector4` and they are not adequate for your specific use case.

**Comment by Bgeninatti** [comment]
Thanks for your answer @WestLangley .
Yes, I'm familiar with the axis-angle methods in Vector4. Those are not adequate for my use case because one of my purposes is to plot in real-time the evolution of the MRP attitude parameters during some maneuvers. (I implemented this MRP parameters myself)
 Axis-angle will produce the same result, but I can not represent what values will have the parameters that I want overtime during the simulation.

I understand your point that `Matrix3` and `Matrix4` represent transformations or projections, but that would only be in the context of a rotation. For example, the `matrix` attribute of a `Geometry` instance.

A standalone instance of `Matrix3` can or can not represent a rotation, and in that (more general) context matrices addition do makes sense.

I want to implement a method that will convert my custom attitude parameters to a DCM rotation matrix, and to do so I need matrix addition. In the middle steps that matrices will not represent rotation, but the final product will be a DCM matrix in the same way that you are describing.

**Comment by WestLangley** [comment]
three.js is not a math library, otherwise there would be more methods. Also, we have not had a request for your specific methods -- probably for the reasons I stated above.

Plus, `.addMatrix()` and `.addMatrices()` naturally leads to `.subMatrix()` and `.subMatrixes()`, and perhaps `.negate()`.

Can you add your desired methods to the prototype from within your app? Does that work for you?

**Comment by Mugen87** [comment]
Agreed. Adding these methods would justify to add even more methods to the math classes. And this would quickly bloat the API which is undesirable according to the present policy of the library.

**Comment by Bgeninatti** [comment]
I understand your reason to refuse my request. Just wanted to explain my point, thank you for the space.

It is true that Three.js is not a math library, but it has a math module. I would expect to use the available classes as a data structure for something else but rotations, or to obtain rotation matrices in different ways rather than the common cases, but it seems it is out of the scope of the project.

 I'll include my methods to the prototype within my app as @WestLangley mentioned, or I will use [this library](http://glmatrix.net/) to compute the desired math operations. Not decided yet.

**Comment by WestLangley** [comment]
@Bgeninatti Thank you for your understanding, and good luck!
