### ISSUE TITLE
Confusing behavior: Stencil Test is disabled unless Stencil Write is true

### ISSUE THREAD

**Issue by Tomcc** [mrdoob/three.js#19654]
This is a minor issue, but it forced me to read the three.js source to figure it out so it may be something to fix...

Anyway, enabling/disabling the stencil test for an object is currently [the same as disabling or enabling `stencilWrite`](https://github.com/mrdoob/three.js/blob/0950e5b6e8bceb520c154f45b5c240af45f0ed11/src/renderers/webgl/WebGLState.js#L710).

The problem with this is that when using stencil it's very common to have objects that don't write stencil, they only test against what's already in the buffer... so I ended up wasting some time trying to figure out why my object with `stencilWrite = false` was not affected by the stencil func at all.

I think it may make more sense to have a separate `stencilTest` bool, so that testing can be enabled without writing, or just assume that the test must be on if `stencilFunc` is not `Always`.

Again, this is not a big deal - `stencilWrite = true` doesn't actually change anything because all Ops default to `Keep`, so it's not too bad to use that one.

**Comment by gkjohnson** [comment]
I see it can be confusing. I think exposing the `stencilMask` field made it a bit less clear how to handle this. At the least I think the docs could be updated.

I suppose it could make sense to follow the same pattern as the dpeth buffer, though.

`stencilTest` -> enables reading / writing stencil buffer (defaults to `false`)
`stencilWrite` -> sets the stencil write mask to 0 if false, uses `stencilMask` if true (defaults to `true`)
`stencilMask` -> the write mask used when `stencilWrite` is true.

The difference is that right now depth mask is not exposed. I think generally a write mask for stencil has more utility.

Thoughts?

**Comment by Tomcc** [comment]
Hmm, I'm used to just plain GL so I think it would be best to avoid using GL terms while overriding what they mean.
For example in your new proposal, having test enable write and write change the mask would really confuse me :P

What I had in mind was more like, leaving everything unchanged (it already maps 1:1 to OpenGL, besides `stencilWrite`) and just adding `stencilTest`. 
Otherwise, the intent to stencil test could be deduced by having any non-default value for all the existing parameters? It would be one less thing to worry about for users.

**Comment by gkjohnson** [comment]
The behavior I suggested is more consistent with the behavior of three.js already:

If `material.depthTest = false` but `material.depthWrite = true` then the depth buffer will still not be written to. It seems like if this is going to be changed it should be made more consistent with the existing behaviors. The nature of stencil effects might warrant some different thinking, though.

I'll defer to the maintainers of the project but I'm thinking at least the documentation could be updated to be more clear.

**Comment by mrdoob** [comment]
@Tomcc Would you like to do a PR with your proposed behaviour?

**Comment by Tomcc** [comment]
@mrdoob I mean, I guess I got volunteered :)
But I don't know if I have much time, I'll get to it when I can.

**Comment by pailhead** [comment]
How much code currently uses stencil testing? As far as i know, this is much newer than say the transparency api.

**Comment by mrdoob** [comment]
> How would you deal with the fact that the change will break existing code? Eg. existing code relies on the fact that `stencilWrite` by default turns on `stencilTest`. Should that behavior stay?

Not sure. I think doing a PR will your proposed behaviour will help inform the discussion.

**Comment by Mugen87** [comment]
It seems updating the docs helped to clarify the issue since it never was reported since that time.
