### ISSUE TITLE
Using Three.js with TypeScript and Netlify: Euler.d.ts error

### ISSUE THREAD

**Issue by justrealmilk** [mrdoob/three.js#19656]
#### Problem description

So I recently added TypeScript to my project and `create-react-app` autogenerated a `tsconfig` much alike the one below. I found the Three docs for TypeScript and adjusted `es5` to `es6` and the include path from `"src"` to `"./src/**/*.ts"` as it wouldn't work without the change when deployed with Netlify.

```json
{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "./src/**/*.ts"
  ]
}
```

Including `"src"` in the `"include"` value causes Netlify to fail to deploy with the same message each time while **locally there's no build issue**.

![image](https://user-images.githubusercontent.com/156681/84592610-4257ed80-ae8a-11ea-9ac2-ea5fe856e6bf.png)

I checked my local copy of the declaration and it seemed straight forward and I don't know much about maths but Euler's number seems like one of the last things to have errors.

##### Three.js version

- [ ] Dev
- [x] r117

##### OS

- [ ] All of them
- [ ] Windows
- [x] Netlify

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverlfow for help requests.

**Comment by justrealmilk** [comment]
This isn't a help request, this is an issue with the repo.

**Comment by Mugen87** [comment]
If there would be an issue with the type declaration file of `Euler.d.ts`, it should be reported while checking the typings via `tsc`.
