### ISSUE TITLE
Ripples when displaying shadows

### ISSUE THREAD

**Issue by archerl84** [mrdoob/three.js#19669]
At certain angles, I observe these waves on the surfaces of the model when shadows are turned on. How to overcome it?

[See screenshot](http://prntscr.com/t0k7zp)

**Comment by Mugen87** [comment]
What you see are shadow artifacts sometimes called as shadow acne. There are many existing thread at stackoverflow about how to mitigate this issue. E.g.

https://stackoverflow.com/questions/30799206/stripped-shadows-on-collada-objects
https://stackoverflow.com/questions/56034734/three-js-what-causes-shadow-acne-and-how-to-fix-it

Using [LightShadow.bias](https://threejs.org/docs/#api/en/lights/shadows/LightShadow.bias) can often completely remove the issues.
