### ISSUE TITLE
GLTFExporter mixed float and string in output

### ISSUE THREAD

**Issue by shenzhuxi** [mrdoob/three.js#19662]
##### Description of the problem

If I create a simple cube with string in the position like 
```
          var geometry = new THREE.BoxGeometry( 1, 1, 1 );
          var cube = new THREE.Mesh( geometry, material );
          cube.position.copy(new THREE.Vector3( "3.693559", 0, 0));
```
Vector3 can be created without any error, although the number should be a float. 

The JSON from GLTFExporter will just use "3.693559" as a string while other numbers as the float. 

Numbers in string format causes Blender3d failed to Impot GLTF file. 
https://gltf-viewer.donmccurdy.com/ can import the file but shows errors like "ARRAY_TYPE_MISMATCH	Type mismatch. Array element '3.693559' is not a 'number'.	/nodes/1/matrix". 

```
  "nodes": [
    {
      "matrix": [
        1,
        0,
        0,
        0,
        0,
        2.220446049250313e-16,
        1,
        0,
        0,
        -1,
        2.220446049250313e-16,
        0,
        0,
        0,
        0,
        1
      ],
      "mesh": 0
    },
    {
      "matrix": [
        1,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        1,
        0,
        "3.693559",
        0.2155,
        "-8.029183",
        1
      ],
      "mesh": 1
    },
  ]
```
##### Three.js version

- [ ] Dev
- [x] r117
- [x] r116

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Can you please add some more details to the issue?

**Comment by mrdoob** [comment]
> If I create a simple cube with string in the position like 
> ```
>          var geometry = new THREE.BoxGeometry( 1, 1, 1 );
>          var cube = new THREE.Mesh( geometry, material );
>          cube.position.copy(new THREE.Vector3( "3.693559", 0, 0));
> ```

The library does not support numbers in string format.
