### ISSUE TITLE
ExtrudeGeometry  custom Material

### ISSUE THREAD

**Issue by lizhongkun** [mrdoob/three.js#19660]
I want to use pictures to make materials, and how to implement them in extrudegeometry，
[https://stackblitz.com/edit/angular-ivy-rzi2un?file=src%2Fapp%2Fapp.component.ts](url)

**Comment by WestLangley** [comment]
Sorry, this is not a help site.

Are you able to post on the [three.js forum](https://discourse.threejs.org)?
