### ISSUE TITLE
Theree.js contests / grants with OpenCollective fund

### ISSUE THREAD

**Issue by munrocket** [mrdoob/three.js#19670]
I am suggesting to create opencollective and spent this money to contests and grants.

For example:
* grant for new Three.js UI
* contest with particles
* etc.

**Comment by makc** [comment]
FYI #11318

**Comment by Mugen87** [comment]
Yes, this is actually a duplicate of #11318.

**Comment by munrocket** [comment]
> Yeah, I wouldn't know how to distribute the money..

I am suggested how to spend it.
