### ISSUE TITLE
Three.js contests / grants with OpenCollective fund

### ISSUE THREAD

**Issue by munsocket** [mrdoob/three.js#19672]
I am suggesting to create opencollective and spent this money to contests and grants.

For example:

* grant for new Three.js UI
* contest with particles
* etc.

This is not duplicate of #11318 because this issue more about contests than OpenCollective and suggesting how to spend this fund.

**Comment by munrocket** [comment]
This also related to demoscene little bit, we have a page in wiki: https://github.com/mrdoob/three.js/wiki/Demoscene

**Comment by Mugen87** [comment]
Moving this discussion to the [forum](https://discourse.threejs.org/).
