### ISSUE TITLE
GLTFLoader/GLTFExporter - Add KHR_XMP Extension

### ISSUE THREAD

**Issue by arodic** [mrdoob/three.js#19688]
[Khronos glTF working group approved KHR_xmp](https://github.com/KhronosGroup/glTF/pull/1553)

This allows metadata to be added to glTF.

**Comment by donmccurdy** [comment]
tl;dr, I think it's important that three.js users creating viewers are able to use the XMP extension. But XMP data doesn't seem to affect the three.js library directly  — it doesn't change how anything renders.

So, I am hoping someone whose project uses the XMP data can just let us know if anything critical is missing from GLTFLoader / GLTFExporter to let them do that.
