### ISSUE TITLE
scene background orientation is different between the browsers

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#19697]
happens with both flipY = true and false

https://jsfiddle.net/odrupzvt/

firefox:
![Screen Shot 2020-06-21 at 10 07 25 ](https://user-images.githubusercontent.com/242577/85219844-4fec0680-b3a7-11ea-8000-ebc008af52e5.png)

chrome:
![Screen Shot 2020-06-21 at 10 07 39 ](https://user-images.githubusercontent.com/242577/85219845-59756e80-b3a7-11ea-80c8-16d74ea8bff8.png)

**Comment by makc** [comment]
here is a version where you can check correct image orientation: https://jsfiddle.net/6uw0sghy/

**Comment by Mugen87** [comment]
What happens if you load an external texture? Can you confirm it looks good in both browsers?

https://jsfiddle.net/07qrLzns/

**Comment by makc** [comment]
@Mugen87 it [seems to work](https://jsfiddle.net/nckvpbq2/) but I am not sure if imgur recompresses the image

**Comment by makc** [comment]
so I tried re-compressed image and [the issue disappeared](https://jsfiddle.net/b0h5fjxv/). so what does make the file special then 🤔

**Comment by Mugen87** [comment]
I guess that would be a good question for stackoverflow 😉 . Not seeing a relation to `three.js`.

**Comment by makc** [comment]
I have found that going through the intermediate canvas avoids the bug. I suppose I should report this on the webkit tracker, but I dont feel like.
