### ISSUE TITLE
FontLoader needs letter-spacing

### ISSUE THREAD

**Issue by Lutz0815** [mrdoob/three.js#19698]
Hello,
I miss an important feature, letter-spacing at FontLoader.

**Comment by Mugen87** [comment]
It's probably better to use Bitmap Fonts for this use case, see https://github.com/Jam3/three-bmfont-text

`FontLoader` would also be the wrong place for such a property. It could be `Font` or `TextGeometry` although I'm not in favor of adding such text styling properties to these classes.

**Comment by Lutz0815** [comment]
Hello Mugen87,
Thanks for your quick reply. I am working on a 3d text editor. Please look here then you know what I mean. 
https://funid.de/editor/3dtext/
Change the fund to: Anton Reg

**Comment by Mugen87** [comment]
Isn't that a problem of the font itself?

**Comment by Lutz0815** [comment]
I do not know. But the LetterSpace option would be cool.

**Comment by Mugen87** [comment]
I think providing advanced text formatting options for `Font` or `TextGeometry` is out of the scope of this project.
