### ISSUE TITLE
 HDR cubemap background banding artifacts

### ISSUE THREAD

**Issue by Ben-Mack** [mrdoob/three.js#19716]
The artifacts shown right in current three.js HDR envmap example: https://threejs.org/examples/?q=hdr#webgl_materials_envmaps_hdr
It only appears in HDR envMap, RGBM16 is fine. 
![image](https://user-images.githubusercontent.com/6309393/85378811-3a244000-b565-11ea-95c8-f39b75b0ec16.png)
It's not browser or device specific as I've checked on Chrome, Firefox, Desktop and Android.

**Comment by WestLangley** [comment]
The cause is this:
```js
hdrCubeMap.magFilter = THREE.LinearFilter;
```

You will get artifacts applying linear filtering to RGBE-encoded images. You can do this:
```js
hdrCubeMap.magFilter = THREE.NearestFilter;
```
 but that will lead to blocky artifacts.

If it is supported by the browser/hardware, you can use this pattern with linear filtering:
```js
hdrCubeMap = new HDRCubeTextureLoader()
	.setDataType( THREE.FloatType ) // or THREE.HalfFloatType
```
