### ISSUE TITLE
issue with ShaderPass typescript declaration

### ISSUE THREAD

**Issue by jhlee4** [mrdoob/three.js#19714]
##### Description of the problem
fxaa example: https://threejs.org/examples/?q=fxaa#webgl_postprocessing_fxaa
fxaa example code: https://github.com/mrdoob/three.js/blob/master/examples/webgl_postprocessing_fxaa.html

I was trying out FXAA pass example, but I encountered an error saying 
`"Property 'uniforms' does not exist on type 'Material'"`

I have looked into the declaration file for ShaderPass and I notice that material type is 'Material'.
I am not 100% sure but I feel like its suppose to be 'ShaderMaterial' instead of 'Material'

ShaderPass.d.ts
```
import {
	Material
} from '../../../src/Three';

import { Pass } from './Pass';

export class ShaderPass extends Pass {

	constructor( shader: object, textureID?: string );
	textureID: string;
	uniforms: object;
	material: Material;//<=============this part
	fsQuad: object;

}
```
ShaderPass.js
```
var ShaderPass = function ( shader, textureID ) {

	Pass.call( this );

	this.textureID = ( textureID !== undefined ) ? textureID : "tDiffuse";

	if ( shader instanceof ShaderMaterial ) {

		this.uniforms = shader.uniforms;

		this.material = shader;

	} else if ( shader ) {

		this.uniforms = UniformsUtils.clone( shader.uniforms );

		this.material = new ShaderMaterial( {

			defines: Object.assign( {}, shader.defines ),
			uniforms: this.uniforms,
			vertexShader: shader.vertexShader,
			fragmentShader: shader.fragmentShader

		} );

	}
```
##### Three.js version
- [x] r116.1
- [x] types/three.js 103.2

##### Browser
- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> I am not 100% sure but I feel like it suppose to be 'ShaderMaterial' instead of 'Material'

You are right. Do you want to make a PR with the fix?

**Comment by jhlee4** [comment]
> > I am not 100% sure but I feel like it suppose to be 'ShaderMaterial' instead of 'Material'
> 
> You are right. Do you want to make a PR with the fix?

I would love to do it.
