### ISSUE TITLE
Problem with FBX model units (cm/meters), when converted to GLTF

### ISSUE THREAD

**Issue by zaino** [mrdoob/three.js#19713]
##### Description of the problem

Hello,
I have an FBX viewer that is a modified version of the example provided in the repo.
It loads the _Samba_female.fbx_ model from Mixamo correctly, including the animation.

I'm testing a workflow where FBX files are converted to GLTF with Blender, since some of the FBX files we are using are odd and complex, and the FBXLoader fails to open them correctly.

The converted _Samba_female.glb_ is loaded fine in the viewer,  but the model is super-tiny: hacking a scale of (100, 100, 100) at the root, the proportions are correct, and that leads me to think that the original file was in meters, but that piece of information is somehow lost.
Note that when imported in Blender, the original FBX and the converted GLTF have the same scale.

I looked into the GLTF loader to see if units are looked up in the file, but I couldn't find anything. I'm not even sure if the file format include information about units.

Any suggestion will be of great help!

##### Three.js version

- [x] Dev
- [ ] r117
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [x] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
A glTF file's units are always in meters — does the model have the right scale in Blender, or is it small before you export it too? The issue could be there. 

Also note that sometimes an animated model has a scale associated with its animation. You may want to try playing the animation (or playing the first frame) to see if that brings the model up to the size you expect.

**Comment by zaino** [comment]
Thanks for the reply!
When I overlap the original fbx and the converted glb in blender, they appear to be same size, while in my viewer the glb is 1/100 of the original fbx model.
If GLTF doesn't have units, I wonder how blender is able to figure it out...

**Comment by Mugen87** [comment]
> Do you know if FBXLoader can get units out of an FBX file?

AFAIK, no.

If this is an issue of Blender exporter, I suggest to close the issue and file one here instead: https://github.com/KhronosGroup/glTF-Blender-IO

**Comment by zaino** [comment]
Sounds good. I’ll close this one.
