### ISSUE TITLE
0 normalMap value when using a single UV value on a mesh

### ISSUE THREAD

**Issue by SBRK** [mrdoob/three.js#19727]
##### Description of the problem
If on a mesh you have a single UV value for all vertices, the sampled `normalMap`  seems to be 0

Here's a jsfiddle illustating the problem:
https://jsfiddle.net/tyb6fz41/

Comment line 72 to see the normal behaviour with several uv values for each vertices

**Comment by WestLangley** [comment]
Related: #18871.

I doubt we will be supporting degenerate UVs when a normal map is present -- unless adding attribute tangents to your model solves the issue.

Also, see if you can make your example more illustrative. It is too trivial to demonstrate what you are trying to show, IMO.

**Comment by SBRK** [comment]
@WestLangley yes, seems to be the exact same problem, although we use degenerate UVs on purpose, for the usecase @donmccurdy described [here](https://github.com/mrdoob/three.js/pull/18871#issuecomment-599884091) (texture atlas with a palette of colours). [This fix](https://github.com/google/model-viewer/pull/1078/files) seems to work for me, because I always have 3 similar UV values. 
I'll see where to go from here, either using the model-viewer fix, getting rid of the normal map on those meshes or compute the tangents
