### ISSUE TITLE
Example renderers should implement setAnimationLoop

### ISSUE THREAD

**Issue by shaunco** [mrdoob/three.js#19733]
SVGRenderer, CSS2DRenderer, and CSS3DRenderer rely on window.requestAnimationFrame rather than implementing the new setAnimationLoop pattern that is used in WebGLRenderer. It would be nice for the pattern to be consistent across renderers.

**Comment by Mugen87** [comment]
`setAnimationLoop()` was mainly implement because when WebVR. Meaning `requestAnimationFrame()` can be called on different context objects, not only on `window`.

However, this is not relevant for SVG and CSS renderers. And, I'm not sure it's good to blow up the API just because of consistency.

**Comment by shaunco** [comment]
Fair enough on this one.

For #19732, I'll respond over there.
