### ISSUE TITLE
SVGRenderer does not implement getSize()

### ISSUE THREAD

**Issue by shaunco** [mrdoob/three.js#19732]
examples/js/renderers/SVGRenderer.js does not implement getSize(), whereas all of WebGLRenderer, CSS2DRenderer, and CSS3DRenderer implement getSize(). Given that it implements setSize(), it would be nice to have the getSize counterpart.

**Comment by shaunco** [comment]
Having a getSize counterpart to setSize seems pretty different from #19733. getSize() is very useful when trying to make the container responsive. Take a look at https://codepen.io/scscscsc/pen/zYrwxBj . The getFrustrum() function has the following:
```javascript
	var renderSize;
	if(useSVGRenderer) {
		var containerBox = container.getBoundingClientRect();
		renderSize = new THREE.Vector2(containerBox.width, containerBox.height);
	} else {
		renderSize = renderer.getSize(new THREE.Vector2());
	}
```

I'd much rather call renderer.getSize(), which is just stuffing two internal variables in to a Vector2, whereas getBoundingClientRect() is slow and I generally try to avoid it.

**Comment by Mugen87** [comment]
I agree having `getSize()` makes senes. Would you like to make a PR?
