### ISSUE TITLE
SVGRenderer.setSize should have an updateStyle parameter to prevent element size updates

### ISSUE THREAD

**Issue by shaunco** [mrdoob/three.js#19743]
When using CSS to size the canvas in WebGLRenderer responsively, you can pass updateStyle=false to setSize() to ensure the three.js doesn't lock the canvas element size. Similar functionality is needed for SVGRenderer, but SVGRenderer's setSize() doesn't offer an updateStyle parameter.

**Comment by mrdoob** [comment]
> When using CSS to size the canvas in WebGLRenderer responsively, you can pass updateStyle=false to setSize() to ensure the three.js doesn't lock the canvas element size. 

To ensure three.js doesn't lock the canvas element size?

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/pull/19741#discussion_r446678121.
