### ISSUE TITLE
AR Examples KO

### ISSUE THREAD

**Issue by CGriffoin** [mrdoob/three.js#19755]
##### Description of the problem

Hi,

Since last week, after a ARCore update, all AR examples doesn't work ( webxr_ar_*.html ).

Caused by ARCore Depth API ?

My device is a Pixel 3 XL.

I tried in **private browsing**... Same result.

**Use case**
1. Launch [webxr_ar_hittest](https://threejs.org/examples/#webxr_ar_hittest) from Chrome, in a Android device ( Android 10 ).
2. Accept authorizations
3. Press "START AR"
4. Nothing is happening, we stayed on the HTML page ( screenshot below ).

![image](https://user-images.githubusercontent.com/912641/86007643-fd9a8d80-ba17-11ea-895c-f76369fbd21e.png)

No errors in the console (screenshot below).

![image](https://user-images.githubusercontent.com/912641/86009953-148eaf00-ba1b-11ea-8582-8ecb0e1ab4ae.png)

ARCore version 1.18.2000603036

![image](https://user-images.githubusercontent.com/912641/86010879-494f3600-ba1c-11ea-96e2-ff9251128e48.png)

Best regards.

##### Three.js version

- [ ] Dev
- [x] r118
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

ARCore device ( Pixel 3 XL or other compatible device )

**Comment by Mugen87** [comment]
I have the same _Google Play Service for AR_ version installed on a Pixel 1 and all three AR examples work.

Can you try to reinstall Chrome and _Google Play Service for AR_?

**Comment by CGriffoin** [comment]
Thanks @Mugen87, I've uninstalled updates and reinstalled them (I can't remove Chrome & ARCore from my device)... 
Same issue... 
When I press on "START AR" nothing appears, I stay on the HTML page.
I try with a onePlus 7T and it's work !
Hum... Why on my Pixel 3 XL it doesn't works ?... I going to try a hard reset...

**Comment by Mugen87** [comment]
> Hum... Why on my Pixel 3 XL it doesn't works ?... I going to try a hard reset...

If the reset does not help, it might be a good idea to report a bug here:

https://bugs.chromium.org/p/chromium/issues/list

Closing this issues since it is unlikely a `three.js` related problem.

**Comment by CGriffoin** [comment]
Hi @Mugen87 the hard reset as solved the issue... 
I don't know what's happened after ARCore updates :/

It wasn't a three.js issue.

Thanks for your help.
