### ISSUE TITLE
Feature projects broken links

### ISSUE THREAD

**Issue by AnnieTaylorCHEN** [mrdoob/three.js#19753]
Hi, there are some broken links in the demo projects on the home page. I think they can be removed so people don't click to see nothing. 

Status | URL | Source link text
-- | -- | --
-1 Not found: The date in the certificate is invalid or has expired | https://www.harp.gl/ | <No Text>
404 Not Found | https://worlddraw.withgoogle.com/ | <No Text>
-1 Not found: The server name or address could not be resolved | http://www.veilhymn.com/ | <No Text>
-1 Not found: The server name or address could not be resolved | https://weather.withspotify.com/ | <No Text>
-1 Timeout | http://topotopo.io/ | <No Text>
404 Not Found | http://www.robertadicamerino.com/index-archived.html | <No Text>
404 Not Found | http://www.gsmlondon.ac.uk/global-oil-map/ | <No Text>
-1 Timeout | https://masteredfromchaos.com/ | <No Text>
-1 Timeout | http://annualreport.airbusgroup.com/ | <No Text>
-1 Timeout | http://www.360syria.com/ | <No Text>
-1 Timeout | https://uniqueflow.me/ | <No Text>
404 Not Found | http://www.cryptarismission.com/ | <No Text>
-1 Timeout | http://lacostewinter.seeourwork.cn/en/ | <No Text>
-1 Not found: The server name or address could not be resolved | http://breakthrough.nationalgeographic.com/ | <No Text>
404 Not Found | http://campaign.au.kddi.com/hello/ | <No Text>
-1 Timeout | http://thedivergentseries.com/ | <No Text>
-1 Timeout | http://witnessgotham.com/ | <No Text>
-1 Not found: The server name or address could not be resolved | https://www.batmanarkhamknight.com/en_US/batmobile | <No Text>
404 Not Found | http://i-remember.fr/en | <No Text>
-1 Timeout | http://hellorun.helloenjoy.com/ | <No Text>
404 Not Found | http://www.chromeweblab.com/ | <No Text>
404 Not Found | http://www.playmapscube.com/ | <No Text>
-1 Not found: The server name or address could not be resolved | http://inear.se/beanstalk/ | <No Text>

**Comment by Mugen87** [comment]
These two links are working for me:

http://vrdust.org.uk/
https://facebook.github.io/react-vr/

**Comment by marcofugaro** [comment]
Some links could be retrieved using the wayback machine

https://archive.org/web/

Here is a snapshot of the global oil map:

https://web.archive.org/web/20170513101710/http://www.gsmlondon.ac.uk/global-oil-map/


-------------------

Harp.gl is still an active open-source project, the certificate just expired, It will probably be fixed soon.

To access non-https website you can still click `Proceed (unsafe)`

https://www.harp.gl/

**Comment by AnnieTaylorCHEN** [comment]
http://vrdust.org.uk/
https://facebook.github.io/react-vr/
those works for me now too. 

As for ones that aren't directly accessible but can be accessed through archive, then I suggest that they should be directly linked to those links. What do you think?

**Comment by mrdoob** [comment]
I wouldn't link to web archive. If the website died... it was meant to die 😕

**Comment by mrdoob** [comment]
@AnnieTaylorCHEN I usually comment out the links that died:
https://github.com/mrdoob/three.js/blob/5a9813a58fa644427a0374a2e86678235251342a/index.html#L200

Would you like to do a PR against the `gh-pages` branch with the dead projects commented out?

**Comment by AnnieTaylorCHEN** [comment]
@mrdoob  Sure, I can do that tmr. :)
