### ISSUE TITLE
CatmullRom3 Sets tension=0.5 if initialized with tension=0

### ISSUE THREAD

**Issue by dskeithbuck** [mrdoob/three.js#19757]
##### Description of the problem

If I generate a [`CatmullRomCurve3`](https://github.com/mrdoob/three.js/blob/master/src/extras/curves/CatmullRomCurve3.js) with `tension=0`, the curve will actually initialize with a `tension=0.5`

```javascript
        const curve = new THREE.CatmullRomCurve3(
          points,  // Tension
          true,  // Closed
          "catmullrom",  // Type
          0  // Tension
        )
```

**Bug**: `Tension = 0.0` looks like `Tension = 0.5`

![image](https://user-images.githubusercontent.com/39964241/86058848-5ec16180-ba16-11ea-98a6-fea46b22bc4d.png)

**Expected**: Tension = 0.0

![image](https://user-images.githubusercontent.com/39964241/86059019-c7104300-ba16-11ea-82fc-4102877b92cf.png)

_I'm achieving this look for the screenshot by setting `tension=0.001`_

I believe this is caused by this code in the initializer:

`this.tension = tension || 0.5;`

Which should be something like:

```
const defaultTension = 0.5;
// Handle `0` as a valid input
this.tension = (tension === 0 || tension) ? tension : defaultTension;
```

##### Three.js version

- `0.109.0`

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by WestLangley** [comment]
Nice find. We use this pattern to fix that:
```js
this.tension = ( tension !== undefined ) ? tension : 0.5;
```

Would you like to file a PR and fix it?
