### ISSUE TITLE
make MaterialLoader Materials list extendable

### ISSUE THREAD

**Issue by JakubDmochowski** [mrdoob/three.js#19761]
When using https://github.com/spite/THREE.MeshLine library, which is often recommended as extension for drawing thick lines, the MaterialLoader returns an error when trying to parse non-standard material. It would be nice to have an extendable list of materials used by this loader, for now it uses only standard materials and there is no possibility to add new ones from external libraries. 
Error:
![image](https://user-images.githubusercontent.com/35743552/86113728-ecaa5480-bac9-11ea-9a33-e7c46cf77911.png)

In MaterialLoader.js
![image](https://user-images.githubusercontent.com/35743552/86113899-1e232000-baca-11ea-8552-013cff68f63e.png)
![image](https://user-images.githubusercontent.com/35743552/86113945-2aa77880-baca-11ea-8f25-bf043d3e853d.png)
![image](https://user-images.githubusercontent.com/35743552/86113864-15cae500-baca-11ea-993b-9ed93510ce42.png)

**Comment by Mugen87** [comment]
If we start doing this for materials, users could expect the same feature for 3D objects, geometries, textures and other library entities. 

Besides, it's not only the object creation that needs to be handled by `MaterialLoader`. With the current architecture, the loader tests all existing material properties and sets them if necessary. So code like:
```js
if ( json.roughness !== undefined ) material.roughness = json.roughness;
```
`MaterialLoader` would have to do the same for custom material properties which is obviously hard to implement.

**Comment by Mugen87** [comment]
Closing. I suggest you keep an eye on #11266. When it's resolved, doing what you are looking for should be easier.
