### ISSUE TITLE
Sprite and SpriteMaterial

### ISSUE THREAD

**Issue by rochaallanc** [mrdoob/three.js#19775]
I am using Sprites to draw tags over a terrain for visualization purposes and right now I am limited by the current Sprite implementation. Here are the issues: 

1. I need to support a fixed Sprite size (sizeAttenuation: false) for both perspective and orthographic camera, which is based on user choice in our software. So I am curious, why is it not supported for orthographic camera? since it seems to be the same implementation. 

2. Sprites only accept SpriteMaterial but I need to implement a customized material to work with our customized transparency algorithm. Would be possible to pass a ShaderMaterial instead (or a generalization) of a SpriteMaterial? 

My current alternative is to implement my own Sprite object using a Mesh with two triangles and customized ShaderMaterial. However it seems addressing 1 and 2 may be useful to someone out there as well, so I am reporting it. 

Thanks a lot.

**Comment by WestLangley** [comment]
For a given frustum size, orthographic cameras do not attenuate size.

Please redirect your questions to the three.js forum where you can further describe your use case, explain what you have tried, and get advice on your many options. Look at `SpriteNodeMaterial` or `.onBeforeCompile()` for example.
