### ISSUE TITLE
VSM shadow map with outline pass introduces drop in framerate 

### ISSUE THREAD

**Issue by ManishJu** [mrdoob/three.js#19778]
When using effect composer for outline creation using outline pass along with VSMShadowMap I saw a 33% drop in framerate.
This is not happening with other shadowmap types like PCFSoftShadowMap and this starts happening only when you just hover over the object without even moving it. **The framerate remains consistent when using other shadowmap types and using orbital control to move camera in three v117 without hovering on objects**  (slight drop in three v118.) 

Here is the code snippet :
https://jsfiddle.net/24svu6gn/17/
commenting line 84 makes the framerate drop less when hovering over objects.

Here is the file to run locally by replacing contents of the misc_controls_drag example from which I recorded the video :

[misc_controls_drag.zip](https://github.com/mrdoob/three.js/files/4865914/misc_controls_drag.zip)

Here is the video showing the issue ( see the frame rate on top left and mouse pointer position) :

[content.zip](https://github.com/mrdoob/three.js/files/4865907/content.zip)

My point : If the framerate is not dropping while using orbital control it should not drop while hovering on objects just when we use VSM shadows.

##### Three.js version

- [ ] Dev
- [x] r118
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Nvidia 20series card

**Comment by Mugen87** [comment]
I've checked this again on my iMac with `r126` and I can't confirm the reported issue.

VSM: https://jsfiddle.net/qew14h3v/show
No VSM: https://jsfiddle.net/0uq3nve2/show

The VSM fiddle actually performs better.
