### ISSUE TITLE
THREE.JS does not push attributes to GPU when mesh.visible = false

### ISSUE THREAD

**Issue by that-ben** [mrdoob/three.js#19770]
##### Description of the problem

THREE.JS does not push attributes to GPU when mesh.visible = false, e.g.:

```js
mesh.visible = false;
// Next frame
mesh.geometry.attributes.my_attribute.array[0] = 123;
mesh.geometry.attributes.my_attribute.needsUpdate = true;
// Next frame
mesh.visible = true;
// GPU does not draw my_attribute as 123.
```

For performance optimization reasons, I toggle a bunch of meshes visibility on and off often (and randomly, based on users interaction).  I discovered this because sometimes I would see mesh attributes updated and sometimes I would not, solely based on the fact that the mesh.visible was set to false on the frame when the needsUpdate = true happened.

Is this desired behavior? If so, then how are we supposed to update mesh attributes when it's invisible? Are we forced to display the mesh for a frame, then update its attributes, then hide it again?

##### Three.js version

- [x] r111

##### Browser

- [x] Firefox

##### OS

- [x] Windows

##### Hardware Requirements (graphics card, VR Device, ...)

AMD Radeon R9 200 series

**Comment by gkjohnson** [comment]
> ```js
> mesh.visible = false;
> // Next frame
> mesh.geometry.attributes.my_attribute.array[0] = 123;
> mesh.geometry.attributes.my_attribute.needsUpdate = true;
> // Next frame
> mesh.visible = true;
> // GPU does not draw my_attribute as 123.
> ```

This behavior should not be happening. Data isn't uploaded to the GPU until it has to be used but that doesn't mean changes while a mesh is not visible are ignored.

Can you demonstrate your problem in a [jsfiddle](https://jsfiddle.net/8kubjpL5/)?

**Comment by mrdoob** [comment]
`mesh.material.visible = false` may do the trick...

**Comment by Mugen87** [comment]
I'm unable to reproduce: https://jsfiddle.net/v9wbqe0L/

**Comment by that-ben** [comment]
@Mugen87 Specifically, in my app, it's a THREE.InstancedMesh and the attribute is a THREE.InstancedBufferAttribute, not sure if this actually makes any difference compared to a plain THREE.Mesh.

**Comment by that-ben** [comment]
I'm embarrassed to say that upon trying to make a small test case with a THREE.InstancedMesh + THREE.InstancedBufferAttribute, I couldn't reproduce the problem.  It still happens in my app tough, so it must be for some other reason.  But it works as intended in a test case.  Sorry for this.  Thanks.

**Comment by that-ben** [comment]
This is extremely ugly, but in 1 minute, I "fixed the issue" with:
```
mesh.visible = true;
mesh.geometry.attributes.my_attribute.array[0] = 123;
mesh.geometry.attributes.my_attribute.needsUpdate = true;
setTimeout("mesh.visible = false", 20);
```
