### ISSUE TITLE
LineMaterial.js - is it possible to turn off diffuse color ? 

### ISSUE THREAD

**Issue by mgs20190702** [mrdoob/three.js#19772]
when running https://threejs.org/examples/?q=line#webgl_lines_fat , i found the color is always diffuse between 2 points  

So , i edited LineMaterial.js :
			#ifdef USE_COLOR
				// vColor.xyz = ( position.y < 0.5 ) ? instanceColorStart : instanceColorEnd;
				**vColor.xyz = instanceColorStart ;**
			#endif

but both color showing at the intersection of 2 points. 

thank you for any help.
![image_2020_07_02T09_19_47_752Za](https://user-images.githubusercontent.com/60082606/86343597-c03e3600-bc8b-11ea-8fd5-cd0d3f7956d1.jpg)

**Comment by WestLangley** [comment]
Sorry, this is not the proper site for help.

Please redirect your help questions to the three.js [forum](https://discourse.threejs.org). Be sure to show sufficient code so your problem can be reproduced.
