### ISSUE TITLE
Clean up suggestion for methods that optionally return

### ISSUE THREAD

**Issue by allsey87** [mrdoob/three.js#19784]
Just wanted to ask about/point out that most methods in this library denote an optional return type by conditionally returning `null` in the function body. There are the following exceptions though that seem to express the same concept but instead return `undefined`.

1. `intersectLine` from `Plane`
2. `getObjectById` from `Object3D`
3. `getObjectByName` from `Object3D`
4. `getObjectByProperty` from `Object3D`

Is this intentional? What is the rational behind this?

**Comment by allsey87** [comment]
Additional information: the cases where `null` is used to denote an optional return are as follows:

1. `getHandler` from `LoadingManager`
1. `existingAction` from `AnimationMixer`
1. `intersectSphere` from `Ray`
1. `intersectPlane` from `Ray`
1. `intersectBox` from `Ray`
1. `intersectTriangle` from `Ray`
1. `getRenderTarget` from `WebGLRenderer`
1. `getCurrentRenderTarget` from `WebGLRenderer`
1. `getIndex` from `BufferGeometry`
1. `getObjectForDistance` from `LOD`

**Comment by mrdoob** [comment]
You mean that we should unify all these to return `null`?

**Comment by allsey87** [comment]
I would suggest `null` over `undefined`. In my mind, `null` better represents the concept of nothing being returned. 

It's just a minor nitpick. I came across it while doing the Rust bindings, but thought I would make a note of it in case you were interested in fixing these things.

**Comment by Mugen87** [comment]
Changing this now is a bit tricky since a lot of user code already relies on the current patterns. I think I would prefer backwards compatibility in this case and keep the implementation as it is.
