### ISSUE TITLE
Add text/content to examples entry page

### ISSUE THREAD

**Issue by karanganesan** [mrdoob/three.js#19786]
Is it possible add some text or something that says "Choose an example to open an experience from the menu button"?
It empty on both mobile and desktop.

![Screenshot (80)](https://user-images.githubusercontent.com/6049925/86469183-88e88b80-bd56-11ea-9e65-e5a0b6218509.png)
![Screenshot (81)](https://user-images.githubusercontent.com/6049925/86469186-8a19b880-bd56-11ea-803f-fa09a194ba0a.png)

**Comment by looeee** [comment]
Related: #19644

**Comment by Mugen87** [comment]
> Choose an example to open an experience from the menu button

I vote for a subtle placeholder text in the center/middle of the page. Something like:

![image](https://user-images.githubusercontent.com/12612165/86586873-f24fe080-bf88-11ea-9316-3811ed6e5132.png)

Indeed, you are not the first user which is irritated by the empty page. A small hint should clarify the page's functionality.
