### ISSUE TITLE
Is it possible to open a three.js example (or put the entire examples site) in codesandbox? 

### ISSUE THREAD

**Issue by unphased** [mrdoob/three.js#19780]
I find it difficult to do the first thing that I want to do when I look at a three.js example, which is to jump in and quickly modify it. Sometimes this can be done directly in the devtools but usually what we're tweaking is something during init so reloading the page will lose our local changes.

I've been impressed by tooling environments like codesandbox, but I am not well-versed enough in it to create a workflow around this. 

It seems like the standard way to dig into the examples in a "persistent" way is to clone it and out of the git repo.

This scratches the itch really well, the dev server starts up really quick, so hats off to you, but I keep wanting more. Has anyone set the whole thing up in codesandbox? I could start to do this kind of experimentation on my ipad if that is the case!

**Comment by mrdoob** [comment]
You mean that you would like to mess with the code directly in the examples page?

**Comment by unphased** [comment]
Yeah i've messed around with three.js a lot over the years. But didnt try actually running the dev server till today and it really works well. I think being able to manipulate an example directly is much better for rapid prototyping and experimentation and is the best way to leverage the examples, which I think are this project's largest asset.

I'm more wondering if someone's already figured out a way to run it with even less effort than that, in codesandbox or something similar.

**Comment by looeee** [comment]
I was hoping you could do this, but the repo is too large :( 

https://codesandbox.io/s/github/mrdoob/three.js/

Somebody did create a live editable version of the examples a while back, as I recall it was rejected for being too heavy since it used React. It should be possible to implement the same functionality without adding extra libraries though.

**Comment by Mugen87** [comment]
Related: #10481

The proposed solution at that time was indeed over-engineering. Unfortunately, https://threejs.live/ is still active using a legacy version of `three.js` (`R84`).

**Comment by unphased** [comment]
Thanks for connecting the dots! I am in total agreement with all the discussions that went down. It does seem to me that given how beautifully the dev server works, a live-editing interface has to really work well before it should be considered for overhauling the examples as they work now. Not only that it has to merely work, but also perform well, as several of the examples really push the boundaries if your browser.  I'm satisfied and will close the issue.
