### ISSUE TITLE
KTX2Loader calls init() for each texture being loaded

### ISSUE THREAD

**Issue by zeux** [mrdoob/three.js#19793]
Using this live demo that integrates KTX2 into GLTF loading process, loading 4 textures total:

https://raw.githack.com/zeux/three.js/gltf-ktx2/examples/webgl_loader_gltf_ktx2.html

It looks like every call to load a texture redundantly reinitializes the transcoders despite the fact that webworkers don't seem to be used (or at least execution is serialized):

![image](https://user-images.githubusercontent.com/1106629/86523174-71280a80-be1d-11ea-864e-cf6d7c1e732f.png)

4 calls to initTranscoders with each call taking ~45ms here. I believe the .wasm module is also instantiated 4 times.

**Comment by donmccurdy** [comment]
Yeah, the `init()` function should be storing a reference to the first promise it creates and returning that on future calls, but isn't doing so yet:

https://github.com/mrdoob/three.js/blob/3ca144cac1c81ada7496e2f4790877848c6b4aa9/examples/jsm/loaders/KTX2Loader.js#L91-L110

We haven't set up Web Workers for this loader either.
