### ISSUE TITLE
Mouse helper covers whole object

### ISSUE THREAD

**Issue by aturkkan94** [mrdoob/three.js#19808]
Hi,

I tried to use indoor controllers and change your default 3d object for room. And for my room mouse helper covers whole room. What can be the reason for it?

Reference : https://prnt.sc/tdmroy

Thankss

**Comment by WestLangley** [comment]
As it states in the instructions:

>This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
