### ISSUE TITLE
A DepthTest false material is not writing in the Depth

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#19807]
##### Description of the problem

I'm not sure if that is something fixable, if I'm doing something wrong in there, or if it supposed to behave like this by design.

I've got a plane, a ring and a sphere.

![render](https://i.imgur.com/qaVscQM.png)

Rendered in order : 

1 ) The plane is rendered a bit behind.

2 ) The ring got no depthTest, but a depthWrite. So, it goes through the plane because it is not testing the depth, all logical until now and this is the behavior I need.

3 ) The sphere is rendered,  but does not consider the ring depth.

Does it mean the ring depthTest material set to false prevents it to being written on the depth ?
If yes, is there a workaround to that ? 

[jsfiddle](https://jsfiddle.net/tf2yhndz/)

##### Three.js version

- [ ] Dev
- [x] r118
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Samsy** [comment]
It seems that disabling depth test will also disable the depth updating in the z-buffer.

**Comment by Mugen87** [comment]
I don't think this is right. In your fiddle, it's a matter or render order. Is that what you are looking for?

https://jsfiddle.net/a1fckm2u/

BTW: You have to make the plane double sided so the disabled depth test of the ring shows effect. Also note that transparent and opaque objects are rendered sorted separately.

**Comment by Samsy** [comment]
I'm looking to render the ring without a depthtest, and the sphere rendered after it to consider the depth of the ring.
