### ISSUE TITLE
A material bug with TDSLoader

### ISSUE THREAD

**Issue by lilypen** [mrdoob/three.js#19817]
##### Description of the problem

The attached 3ds file is loaded with one mesh and one material by TDSLoader. But actually it has not only one material. The picture 1 shows what's loaded in three.js .  And picture 2 shows what is right.

[PETERBIL.zip](https://github.com/mrdoob/three.js/files/4895015/PETERBIL.zip)

![image](https://user-images.githubusercontent.com/16899430/87006915-ffbcd300-c1f3-11ea-90bb-3a7b7eacf2ba.png)

![16WKWYD$3UXU3TEB~OMKOJX](https://user-images.githubusercontent.com/16899430/87006955-1105df80-c1f4-11ea-95f6-fbf4ef7f9ade.png)

##### Three.js version

- [x] Dev
- [ ] r118
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Result when importing at Sketchfab:

![image](https://user-images.githubusercontent.com/12612165/95760019-cee4b200-0caa-11eb-8a32-e6dd516163f4.png)

According to the Sketchfab 3D inspector, the model uses multiple materials to achieve the different colored parts. However, `TDSLoader` only loads the mesh with a single material.

**Comment by danLawrence** [comment]
> Result when importing at Sketchfab:
> 
> ![image](https://user-images.githubusercontent.com/12612165/95760019-cee4b200-0caa-11eb-8a32-e6dd516163f4.png)
> 
> @tentone According to the Sketchfab 3D inspector, the model uses multiple materials to achieve the different colored parts. However, `TDSLoader` loads the mesh with just a single material. Maybe this helps to isolate the issue.

I met the same problem! 
So is there any solution?   
or i should just use another format

**Comment by Mugen87** [comment]
> or i should just use another format

Better to use another format. Try it with glTF whenever possible.

**Comment by Mugen87** [comment]
@mrdoob Against the backdrop that 3DS is badly documented and the original developers don't maintain `TDSLoader`, I think it's better to remove it and recommend users other 3D formats instead.

**Comment by mrdoob** [comment]
Aww, but I grew up with 3DS... 😅
Lets leave this open and hope that someone is able to fix it in the future.

**Comment by tentone** [comment]
@Mugen87 

I have been spending some time figuring out how to relate the multiple loaded materials with a single mesh. As you have said the 3DS file format is badly documented.

I have been using this page as a reference http://faydoc.tripod.com/formats/3ds.htm, I will keep you up to date with any progress.

I don't think that you should drop the loader, it is still a widely used format. I think that we can improve it to support more features.

**Comment by Mugen87** [comment]
As long as it is maintained, I'm fine with keeping the loader^^.
