### ISSUE TITLE
FrontFaceDirectionCW and FrontFaceDirectionCCW can be removed?

### ISSUE THREAD

**Issue by nzjony** [mrdoob/three.js#19811]
##### Description of the problem

I searched in the code base for usages of: FrontFaceDirectionCCW and FrontFaceDirectionCW, but couldn't find it being used anywhere, I suppose it can be removed?

##### Three.js version

- [x] Dev
- [x] r118
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by Mugen87** [comment]
Yes, this legacy code can be removed.

**Comment by mrdoob** [comment]
Indeed! @nzjony would you like to do a PR?

**Comment by nzjony** [comment]
@mrdoob , cool, will do.
