### ISSUE TITLE
Warning has outdated link to the documentation

### ISSUE THREAD

**Issue by marcotama** [mrdoob/three.js#19810]
##### Description of the problem

Hi, thanks for this awesome library.

The comment up the top of CSS3DRenderer has a `console.warn` call which states the file will be deprecated and points to [a broken link](https://threejs.org/docs/index.html#manual/en/introduction/Import-via-modules) for more information.

Could yo please update the link?

##### Three.js version
- [X] master

##### Browser
- [X] Does not apply

##### OS
- [X] Does not apply

##### Hardware Requirements (graphics card, VR Device, ...)
- [X] Does not apply

**Comment by marcotama** [comment]
Specific line: https://github.com/mrdoob/three.js/blob/dev/examples/js/renderers/CSS3DRenderer.js#L1

**Comment by donmccurdy** [comment]
Ah, sorry about that. The correct link should be https://threejs.org/docs/#manual/en/introduction/Installation, with additional resources coming.

**Comment by marcotama** [comment]
Thanks!

**Comment by Mugen87** [comment]
@marcotama Thanks for reporting!
