### ISSUE TITLE
Suggestion: Add option to disable the rendering of light helpers in the Editor

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#19828]

**Comment by Mugen87** [comment]
So you want the option to disable the rendering of light helpers? Can you please explain why you want this feature?

**Comment by linbingquan** [comment]
> So you want the option to disable the rendering of light helpers?

Yes.

> Can you please explain why you want this feature?

I edited a product model with five directional lights, and recorded a video or make a screenshot sended the other people, it has the light helper impacted render effect(serveral white line). People asked me what's this, I allway to explain at the first time.

**Comment by Mugen87** [comment]
How about introducing a new checkbox in the `SETTINGS` tab called `Helpers`. If checked, helpers are rendered. If not, they are excluded. Default would be `true`. So it would work similar to the `Grid` helper.

**Comment by linbingquan** [comment]
> How about introducing a new checkbox in the `SETTINGS` tab called `Helpers`. If checked, helpers are rendered. If not, they are excluded. Default would be `true`. So it would work similar to the `Grid` checkbox.

It sounds good to me.
