### ISSUE TITLE
Remove ESM Node support mention from the installation doc

### ISSUE THREAD

**Issue by TomasHubelbauer** [mrdoob/three.js#19830]
Citing from https://threejs.org/docs/#manual/en/introduction/Installation:

> Second, Node.js support for ES modules is ... complicated. As of Node.js v12, the core library can be imported as a CommonJS module, with require('three'). However, most example components in examples/jsm cannot. Future versions of Node.js may resolve this, but in the meantime you may need to use workarounds like esm to enable your Node.js application to recognize ES modules. 

As of latest Node (14.5.0 at the time of writing), ESM support in Node works as expected and nothing special is required (like using CLI flags or MJS extension). Therefore I would like to discuss whether it's appropriate to remove this section of the document.

If it is deemed so, I'll be happy to send in a PR removing it or rewording it.

**Comment by cecilemuller** [comment]
Perhaps a good time would be once 14 becomes LTS (in October I think) ?

**Comment by TomasHubelbauer** [comment]
Yeah, that makes sense. I'll ping this issue when it does.

**Comment by donmccurdy** [comment]
It might also be necessary to use older versions of node until [headless-gl](https://github.com/stackgl/headless-gl) has a prebuilt binary for v14. Building it from source has been iffy for me, and a WebGL alternative is important for three.js.

**Comment by looeee** [comment]
People are likely to be using Node v12 for at least another few years, judging from previous Node releases.

We could change the paragraph: 

> Support for modules in older versions of Node is... complicated. If you're using Node v14 or higher, you should have no problems. However, for Node.js v12 and below, while the core library can be imported as a CommonJS module using `require('three')`, most example components in examples/jsm cannot. For these, you may need to use workarounds like esm to enable ES modules in your Node.js application.

**Comment by Mugen87** [comment]
> As of latest Node (14.5.0 at the time of writing), ESM support in Node works as expected and nothing special is required (like using CLI flags or MJS extension).

Sorry for asking but you say nothing special is required. I have just upgrade to node `v14.6.0` and if I now try to execute one of the `three.js` converter scripts, I get:

> Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

It works if I do one of these things. But it appears it does not "just work".

**Comment by TomasHubelbauer** [comment]
@Mugen87 I think (but I might be wrong) that that's expected - that it is a Node thing. Similarly to how in browser JavaScript when you want to use ESM, you need to use `<script type="module">`. I am not aware of any plans on the Node's side to make the `module` package type the default (and I don't think it would happen without it also happening on the browser side which I find even more unlikely as it would be a big breaking change).

**Comment by Mugen87** [comment]
Okay, thanks for the clarification. I think the documentation should reflect this since many users (especially beginners) will do the same (naive) thing I did^^. So it should at least mention that it's required to configure `package.json` in order to run ES6 scripts like above.

**Comment by TomasHubelbauer** [comment]
It's true, I will patch this PR to include this when I have a chance.

**Comment by Mugen87** [comment]
I think this is an issue, not a PR 😇 .

**Comment by TomasHubelbauer** [comment]
Oh yeah, sorry, I have an associated PR for this somewhere.

**Comment by donmccurdy** [comment]
Related: https://github.com/mrdoob/three.js/pull/18498

**Comment by mrdoob** [comment]
I guess this can be closed then?

**Comment by Mugen87** [comment]
TBH, I don't feel strong about this. I suggested https://github.com/mrdoob/three.js/issues/19830#issuecomment-664913548 but one could also argue that it's not the task of the `three.js` documentation to explain how to use ES6 modules with node.

**Comment by Mugen87** [comment]
Closing for now.
