### ISSUE TITLE
JPG to GLTF 

### ISSUE THREAD

**Issue by deepakkhanna18** [mrdoob/three.js#19832]
##### Description of the problem

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.: 
Trying to convert JPG to GLTF , however even Not able to upload file

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/hyok6tvj/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/c5m1kazu/) (dev branch)

##### Three.js version

- [ ] Dev
- [ ] r118
- [ ] ...

##### Browser

- [x] All of them
- [x] Chrome Yes
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [x] Windows Yes
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> Trying to convert JPG to GLTF , however even Not able to upload file

JPG is an image format whereas glTF is a 3D format. You can convert between both,
