### ISSUE TITLE
CSS3DRenderer offset for Safari on High DPI displays with odd resolution

### ISSUE THREAD

**Issue by JohannesDeml** [mrdoob/three.js#19854]
##### Description of the problem

When combining a webgl renderer with a cssrenderer (by punching holes through the webgl renderer to show the css renderer below, there is sometimes a missmatch between the renderers. It looks as if the cssRenderer has a slight offset compared to the webglrenderer. Interestingly enough, this happens on iPhoneX, but not iPhoneSE or iPad Mini4 and also not on android and desktop. Not sure about newer iPhones. The problem is especially present when looking at the css area at a very shallow angle.

The problem is not bound to the css object present (also tried it with a simple <img>).
There should be no white area around the youtube video:
[Video](https://youtu.be/SV2P5B5U1jg)
![Screenshot 1](https://user-images.githubusercontent.com/4518980/87684517-a1a76700-c782-11ea-8165-27c0bfe022f2.jpeg)
![Screenshot 3](https://user-images.githubusercontent.com/4518980/87684522-a2d89400-c782-11ea-9446-15e20f08e0e7.jpeg)

* [codepen](https://codepen.io/JohannesDeml/pen/NWxdXEM) (latest release branch)

##### Three.js version

- [x] Dev
- [x] r118
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
- [ ] iPhone SE
- [ ] iPhone 8
- [x] iPhone X
- [x] iPhone 11 Pro
- [x] MacBook Pro with external High DPI Display
- [x] iMac

**Comment by yomotsu** [comment]
Confirm and reproduced the problem on my iPhoneX too.
I also checked another example: https://threejs.org/examples/?q=css#css3d_sandbox but seems to work with no gap.

**Comment by JohannesDeml** [comment]
> 
> 
> Confirm and reproduced the problem on my iPhoneX too.
> I also checked another example: https://threejs.org/examples/?q=css#css3d_sandbox but this seems to work with no gap on the same iPhoneX

That is very interesting, thanks a lot for pointing it out! I somehow missed that example. I will need to dig a bit deeper to find out why that example works as expected. Interestingly enough I also get some small offset there as well (even on windows):
![grafik](https://user-images.githubusercontent.com/4518980/87757826-9cdac580-c80b-11ea-831a-5a81e498ed0a.png)

Maybe there is a precision problem for handling matrix3d css stacks that is even more apparent for my example (since it is scaled by a factor of 100). I will try to expose the difference that creates the very visible problem in my example.

**Comment by JohannesDeml** [comment]
I was able to check the example @yomotsu posted with an iPhoneX and the offset also happens there.
![css3d-sandbox-screenshot1](https://user-images.githubusercontent.com/4518980/87785710-ec83b600-c838-11ea-9a88-a157c72a77ad.png)
![css3d-sandbox-screenshot2](https://user-images.githubusercontent.com/4518980/87785712-edb4e300-c838-11ea-83b4-422b7f9563da.png)

So I guess it is safe to say that the problem does exist (since I built my example without knowing of the other example) and it is a device specific limitation for iPhone X (and maybe newer, sadly I don't have a newer iOS device at hand).

**Comment by JohannesDeml** [comment]
I was able to reproduce the problem on an iPhone 11 Pro as well. Could this have something to do with the notch / Rounded corners? I am already using the cover meta tag to avoid such problems, but it's really strange that the problem starts to appear on iOS devices with a notch...
`<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0, initial-scale=1.0, viewport-fit=cover" />`

**Comment by mrdoob** [comment]
I've seen similar issues in the past and I think the issue was something like not being able to match CSS's perspective code with the current `PerspectiveCamera` `matrix` code. Didn't end up digging deeper.

**Comment by WestLangley** [comment]
FWIW, on Safari on my iMac, showing the favorites bar causes a similar offset artifact (refresh required). It also occurs with page zoom not equal to 100%.

**Comment by JohannesDeml** [comment]
> I've seen similar issues in the past and I think the issue was something like not being able to match CSS's perspective code with the current `PerspectiveCamera` `updateProjectionMatrix` code. Didn't end up digging deeper.

Hm, I think that might be a different issue, I built a [repro with a orthographic camera](https://codepen.io/JohannesDeml/pen/dyMyRyb), which shows the same problem.


> FWIW, on Safari on my iMac, showing the favorites bar causes a similar offset artifact (refresh required). It also occurs with page zoom not equal to 100%.

Interesting, thanks for pointing it out. I dug a bit deeper, and I get the same issue when using a MacBook connected to a high DPI monitor with scaling set to the smallest value (might be needed just to get to a higher css resolution).

As for zooming, that might be connected to this [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=242685) [(Repro)](https://bl.ocks.org/mbostock/c02ccf25704d434cebd1), which was fixed in every browser except safari.

Anyways, I think I might have a lead on how to fix the problem:
As mentioned, the problem can be reproduced on MacOS. There I took a closer look at the css styling of the camera element. I noticed that changing the last translate value (which is half width, halfHeight) by 0.5-1.0 pixels seems to fix the problem. I haven't found out, when we have to change it in one other the other direction. I need to dig a bit deeper there.

If that is the case and the fix is to handle the transform values differently in the camera on safari, where would I need to put the user agent read to validate if the browser is safari? Should I put that in the Camera code, or somewhere else?

**Comment by WestLangley** [comment]
On your [orhto example](https://codepen.io/JohannesDeml/pen/dyMyRyb) on iMac, resizing the window _vertically_ only or _horizontally_ only is illustrative.

![Screen Shot 2020-08-05 at 10 47 11 AM](https://user-images.githubusercontent.com/1000017/89427321-1ed25600-d709-11ea-8c7c-4e0f4e7778bb.png)

Maybe try
```js
_widthHalf = Math.round( _width / 2 );
_heightHalf = Math.round( _height / 2 );
```
Just a guess.

**Comment by JohannesDeml** [comment]
> Maybe try
> 
> ```js
> _widthHalf = Math.round( _width / 2 );
> _heightHalf = Math.round( _height / 2 );
> ```
> 
> Just a guess.

Yep, that does it for safari 🎉

![grafik](https://user-images.githubusercontent.com/4518980/89508828-bcdc2400-d7ce-11ea-98ac-c674dc044fee.png)

So we will need to implement a check for safari (similar to what is done for ie) and use rounded values there.
I will also port my perspective example to a test branch to see, if the rounding fixes that problem as well.

**Comment by JohannesDeml** [comment]
Okay, so I fixed the orthographic problem, sadly it seems that it does not have too much to do with the perspective problem other than having problems with odd resolutions.

I made a playground branch with a perspective and orthographic css scene which show the problem quite well:
[Orthographic](https://rawcdn.githack.com/JohannesDeml/three.js/test/css3d-playground/examples/css3d_sandbox_orthographic.html)
[Perspective](https://rawcdn.githack.com/JohannesDeml/three.js/test/css3d-playground/examples/css3d_sandbox_perspective.html)

As for perspective, I managed to get the image to fit perfectly when the camera hasn't been rotated. This is achieved by moving the camera up one pixel, if the render height is odd. The very strange thing here is, that the debug overlay agrees that that does not make too much sense:

![grafik](https://user-images.githubusercontent.com/4518980/89522428-8360e400-d7e1-11ea-91fa-d360af7436c4.png)

The problem that still exists now is:

CSS rendering for safari with odd width and or height. In that case the css looks like it is pushed away a bit from the camera:
![grafik](https://user-images.githubusercontent.com/4518980/89522661-e05c9a00-d7e1-11ea-8c75-2e6eb6ef886a.png)

This is not a translation problem anymore. Has anybody any idea how to tackle that one? Maybe perspective or scaling at some point?

**Comment by JohannesDeml** [comment]
@mrdoob my PR sadly only fixed the problem for the orthographic camera, but not the perspective camera. Should I open another issue for that, or should we keep that one open?

**Comment by manthrax** [comment]
I've encountered similar problems on a past product. The "page zoom" controls also affect these transforms. We ended up setting preferred min-zoom/max-zoom in the CSS to mitigate problems..
I also recall that chromes handling of the CSS transforms changed somewhat arbitrarily a number of times over the course of 6 months of work on the feature, requiring it to be addressed many times, only to have chrome revert the breaking changes, or, alternatively, respond to our bug reports of the issue.

**Comment by Mugen87** [comment]
This needs to be fixed in Webkit: https://bugs.webkit.org/show_bug.cgi?id=215590

**Comment by zh-pan** [comment]
This issue beset me too, I debug a few hours. The result I've come to is this, you need set canvas width/height as even number at first, and set css3DObject's element width/height as even number too. The code maybe like this:
```
css3DRenderer.setSize(
  width % 2 === 0 ? width : width - 1,
  height % 2 === 0 ? height : height - 1
 );
----------------------------------
css3DObject.element.style.width = (width % 2 === 0 ? width : width - 1)+'px'
css3DObject.element.style.height= (height% 2 === 0 ? height: height- 1)+'px'
```

**Comment by kekkorider** [comment]
> This issue beset me too, I debug a few hours. The result I've come to is this, you need set canvas width/height as even number at first, and set css3DObject's element width/height as even number too. The code maybe like this:
> 
> ```
> css3DRenderer.setSize(
>   width % 2 === 0 ? width : width - 1,
>   height % 2 === 0 ? height : height - 1
>  );
> ----------------------------------
> css3DObject.element.style.width = (width % 2 === 0 ? width : width - 1)+'px'
> css3DObject.element.style.height= (height% 2 === 0 ? height: height- 1)+'px'
> ```

Today, on November 28th, 2025, this issue is still a thing on both Safari desktop and iOS (all browsers), so is this fix.

**Comment by Makio64** [comment]
iOS26 & this bug still around.. @mrdoob
