### ISSUE TITLE
Unable to load a OBJ file of size 1.6GB

### ISSUE THREAD

**Issue by ravidsp** [mrdoob/three.js#19865]
Is there any limitation of the file size that the threejs can render?

**Comment by Mugen87** [comment]
No. This primarily depends on your system.

**Comment by donmccurdy** [comment]
A browser tab memory limit of 1GB would not be uncommon, though. I wouldn't expect a 1.GB OBJ to open reliably in a web browser. You may need to reduce its size with optimization tools.
