### ISSUE TITLE
There is no `normalized` parameter to vertexAtrribIPointer

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#19861]
https://github.com/mrdoob/three.js/blob/86ae53f8c25f6c0898f64c0f5d47c446a66f9211/src/renderers/webgl/WebGLBindingStates.js#L285

I think this just running by luck with the last normalized being false so it gets converted to 0 and stride and offset are probably 0

**Comment by Mugen87** [comment]
Good catch! Indeed, the [example](https://threejs.org/examples/webgl2_buffergeometry_attributes_integer) was not affected by this.
