### ISSUE TITLE
Support custom buffer/attribute management

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#1987]
I'm happy to write this but would love your feedback before I start.

I think based on the code I see I would basically use ShaderMaterial for my material and then make some new kind of Geometry? CustomGeometry? WebGLCustomGeometry? It would require the user to allocate its own buffers? I guess the question then it should it have a say a "draw" function that WebGLRenderer calls or should it setup some map of attributes/buffers/offsets/strides to allow WebGLRenderer to do he setup?

Or something else?

Thoughts?

**Comment by mrdoob** [comment]
Closing this as BufferGeometry can now handle interleaved buffer attributes.

http://threejs.org/examples/?q=buffergeometry#webgl_buffergeometry_instancing_interleaved_dynamic
