### ISSUE TITLE
kinect example is running by luck

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#19879]
##### Description of the problem

The kinect demo declares a video in HTML. Then in JavaScript it calls `video.addEventListener('loadedmetadata`)` but if the video loads before the JavaScript gets to that line then the `loadedmetadata` event has already fired before JavaScript has had a change to add the listener.

Here's a repo

https://jsfiddle.net/greggman/6arbL09q/

The only thing changed is I added 

```
<script>
console.log('wait 3 seconds');
while(performance.now() < 3000);
console.log('start');
</script>
```

at the top. Another way to repo is to add more scripts to the page which is how I stumbled on the issue

##### Three.js version

- [X] Dev

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Moved the video creation inside the script: https://github.com/mrdoob/three.js/commit/95db0342deeb7c99b6abb66e31abc272df83908c
