### ISSUE TITLE
Unset uniforms with NodeMaterial

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#19878]
##### Description of the problem

I hope this isn't being annoying.  I added a check that all uniforms are set (except samplers)
 to the [webgl checker](https://github.com/greggman/webgl-helpers#webgl-gl-error-checkjs) I've been working on.

It's not wrong to not set a uniform, they default to 0, in fact it's common not to set a sampler uniform in a simple program. Still, it could be a sign of a lurking issue so I thought I'd post this.

~~Pretty much all the samples that use PBR materials get an error that `maxMipLevel` is not set. Of course it defaults to 0 but whatever is trying to use it is not setting it to 0 which suggests it's whatever something else set it if that makes any sense? In other words there's 2 possibilities. (1) it's not used therefore it doesn't matter what the value is (2) it is used but is not being set sometimes so it's whatever value is left over from the last object that actually set it. Examples include, https://threejs.org/examples/webgl_animation_keyframes.html, https://threejs.org/examples/webgl_materials_car.html, https://threejs.org/examples/webgl_materials_displacementmap.html, https://threejs.org/examples/webgl_materials_physical_clearcoat.html, etc...~~

Otherwise:

* https://threejs.org/examples/webgl_sprites_nodes.html doesn't set a uniform called "nodeU2"
* https://threejs.org/examples/webgl_loader_nodes.html doesn't set a uniform called "nodeU4"

Again no idea if these are lurking bugs or working as intended.

##### Three.js version

- [X] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
I have a fix for the `maxMipLevel` issue. Would be good if @sunag can have a look at the node material examples.
