### ISSUE TITLE
'textureCubeLodEXT' : no matching overloaded function found

### ISSUE THREAD

**Issue by Renhj90520** [mrdoob/three.js#19872]
##### Description of the problem

This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/hyok6tvj/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/c5m1kazu/) (dev branch)

##### Three.js version

- [ ] Dev
- [x] r118
- [ ] ...

##### Browser

- [] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

I'm working on a PBR Material, extensions.shaderTextureLOD=true works fine on r117, but r118 and later fragment shader fails compilation.
ERROR: 0:253: 'textureCubeLodEXT' : no matching overloaded function found
ERROR: 0:253: '=' : dimension mismatch
ERROR: 0:253: '=' : cannot convert from 'const mediump float' to 'mediump 4-component vector of float'

253:         vec4 rgba = textureCubeLodEXT(texture, dir, lod);

**Comment by Mugen87** [comment]
This happens because starting with `r118`, `three.js` uses by default a WebGL 2 rendering context and assumes GLSL 3.0 by default.

The above line of code is not GLSL 3.0 conform. It has to look like so:
```js
vec4 rgba = textureLod(texture, dir, lod);
``` 
Instead of upgrading your shader code, you can also use [WebGL1Renderer](https://threejs.org/docs/index.html#api/en/renderers/WebGL1Renderer) which was introduced with `r118``, too. This renderer enforces a WebGL 1 rendering context.

**Comment by mrdoob** [comment]
We do have this:

https://github.com/mrdoob/three.js/blob/b5c272cf408cb33153190fa715d81581bd95ee47/src/renderers/webgl/WebGLProgram.js#L704

But the OP is probably using `RawShaderMaterial`?

**Comment by Mugen87** [comment]
Yes, there were similar issues at the forum and stackoverflow.

**Comment by Mugen87** [comment]
Yes, there were similar issues at the forum and stackoverflow.

**Comment by mrdoob** [comment]
Hmm... I think we should be able to prepend a string to the shader?

Pseudo-code:

```js
if ( material.isRawShaderMaterial ) {

    const version = isWebGL2 ? '#version 300 es' : '#version 100 es';
    fragment = version +'\n' + fragment;

}

**Comment by mrdoob** [comment]
Hmm, we have some similar code already... 🤔

https://github.com/mrdoob/three.js/blob/0de94ab9574097328db6cab0dddd98786bb16fca/src/renderers/webgl/WebGLProgram.js#L671-L686

**Comment by Mugen87** [comment]
I guess prepending such a string to `RawShaderMaterial` might break code since users already had to define the GLSL version when using WebGL 2. So if the engine starts doing this, it will be done twice which will require a migration task.

**Comment by Mugen87** [comment]
Besides, there might be user who want to use GLSL 1 with WebGL 2. [The above code](https://github.com/mrdoob/three.js/issues/19872#issuecomment-660990112) would not allow this setup anymore.

**Comment by Renhj90520** [comment]
Yes, I'm using the RawShaderMaterial. I think it's time to move forward to update my knowledge. Thank you very much.

**Comment by mrdoob** [comment]
@Mugen87 Agreed.

On that note, I do not thing we need this code at all?

https://github.com/mrdoob/three.js/blob/0de94ab9574097328db6cab0dddd98786bb16fca/src/renderers/webgl/WebGLProgram.js#L673-L686

/cc @fernandojsg

**Comment by Mugen87** [comment]
Not sure why this check is there since the `version` directive has to be the first statement of the shader code. When using `ShaderMaterial`, this never can be true since the renderer always prepends prefix code. 

I would we be good to know if there was a specific reasons why this code was added.

**Comment by mrdoob** [comment]
> Not sure why this check is there since the `version` directive has to be the first statement of the shader code. When using `ShaderMaterial`, this never can be true since the renderer always prepends prefix code. 

Yes, that's what I though. Thanks for double checking!
I think I'm going to remove that code for now...

**Comment by mrdoob** [comment]
#19889
