### ISSUE TITLE
obj/mtl model is suddenly shown black

### ISSUE THREAD

**Issue by cuinjune** [mrdoob/three.js#19903]
My three.js app used to work fine but when I tried the app today, the obj/mtl model is suddenly shown just black.

So this is how it used to look like:
[![enter image description here][1]][1]

But now it looks like this although I didn't change any code:
[![enter image description here][2]][2]

Here's my relevant code:

**HTML:**

      <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/110/three.js"></script>
      <script src="https://threejs.org/examples/js/loaders/OBJLoader.js"></script>
      <script src="https://threejs.org/examples/js/loaders/MTLLoader.js"></script>

**Three.js:**

    const scene = this.scene;
            const modelPath = 'assets/models/stereo/';
            const mtlLoader = new THREE.MTLLoader();
            mtlLoader.setCrossOrigin(true);
            mtlLoader.setPath(modelPath);
            mtlLoader.load("1281_HIFI_Stereo.mtl", function (materials) {
                materials.preload();
                const objLoader = new THREE.OBJLoader();
                objLoader.setCrossOrigin(true);
                objLoader.setMaterials(materials);
                objLoader.setPath(modelPath);
                objLoader.load("1281_HIFI_Stereo.obj", function (object) {
                    object.name = "stereo";
                    object.position.set(0, -15, -60);
                    object.rotation.set(0, THREE.Math.degToRad(-90), 0);
                    scene.add(object);
                });
            });

  [1]: https://i.stack.imgur.com/hIDwR.png
  [2]: https://i.stack.imgur.com/dVLNv.png

You can see my full code from https://glitch.com/edit/#!/cuinjune-face-dj

I also tried using the old version of `OBJLoader.js` and `MTLLoader.js` but it still doesn't fix the problem. 

What could be causing this issue and how can I fix this?

**Comment by mrdoob** [comment]
``

**Comment by mrdoob** [comment]
Please, do not hotlink js files from https://threejs.org/.

Also, you're mixing addons from different versions than the library, do this instead:

```html
<script src="https://unpkg.com/three@0.110.0/build/three.js"></script>
<script src="https://unpkg.com/three@0.110.0/examples/js/loaders/OBJLoader.js"></script>
<script src="https://unpkg.com/three@0.110.0/examples/js/loaders/MTLLoader.js"></script>
```
