### ISSUE TITLE
Crash bug: SyntaxError: Unexpected token < in JSON at position 0 in GLTFLoader.js

### ISSUE THREAD

**Issue by fantasticsoul** [mrdoob/three.js#19904]
##### Description of the problem

I download the demo [https://codesandbox.io/s/react-three-fiber-untitled-game-vrsp2] zip to my local computer, and then push it to my server and then error occurred.

```text
react_devtools_backend.js:2273 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at e.parse (GLTFLoader.js:97)
    at Object.onLoad (GLTFLoader.js:57)
    at XMLHttpRequest.<anonymous> (three.module.js:24679)
```

I dedug it in file `GLTFLoader.js`, found content is a html string like `<html> ......`, 

```js
var json = JSON.parse( content );	
```

what I do in my code is I config  `react`，`react-dom`, `react-recociler` in webpack config externals to let them not bundled, just use my lib supplied from cdn.

can you just add a try catch block to resolve this problem, because the content may be a html string sometimes.

```js
var json = {};
try{
  json = JSON.parse( content );	
}catch(err){
 // pass
}
```

##### Three.js version

three@0.109.0

##### Browser

- [ ] Chrome

##### OS

- [ ] macOS

**Comment by donmccurdy** [comment]
This error usually means the glTF file was not found, and that your server returned an HTML page instead. A try/catch won’t fix the issue, you’ll need to make sure the file is located at the right URL. See your browser’s developer tools network tab for more information about the error.

**Comment by SeanOverton** [comment]
I found putting the model in the public folder fixed it for me
