### ISSUE TITLE
ShaderPass module import does not work

### ISSUE THREAD

**Issue by UstymUkhman** [mrdoob/three.js#19918]
#### Custom postprocessing doesn't work when importing `ShaderPass` as ES6 module but only when using `THREE` as global object and requiring it as CommonJS module.

I'm trying to update a project from `r96` to `r118`. Initially I used `three.js` as global object, so now I'm migrating to module imports. I've investigated a little this issue, and the problem seams to rely in one of the following modules: `ShaderPass`, `Pass` or `ShaderMaterial`. The point is that when importing like this:

```
import * as THREE from 'three/build/three.min.js';
window.THREE = THREE;

require('three/examples/js/postprocessing/CopyPass');
require('three/examples/js/postprocessing/EffectComposer');
require('three/examples/js/postprocessing/RenderPass');
require('three/examples/js/postprocessing/ShaderPass');
```

custom shaders will work with `EffectComposer`, but not when importing like this:

```
import { ShaderMaterial } from '@three/materials/ShaderMaterial';
import { EffectComposer } from '@postprocessing/EffectComposer';
import { RenderPass } from '@postprocessing/RenderPass';
import { ShaderPass } from '@postprocessing/ShaderPass';
```

This issue is reproducible with both `WebGLRenderer` and `WebGL1Renderer`. I'm sorry for not providing a complete demo, but you can check the source code [here](https://github.com/UstymUkhman/color-grading/blob/master/src/ColorGrading.js) and test it [here](https://ustymukhman.github.io/color-grading/public/).

##### Three.js version

- [x] r118

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Um, what is `@postprocessing/EffectComposer`?

I suggest you import the post-processing modules like in the examples. They all work without issues.

https://threejs.org/examples/webgl_postprocessing_advanced

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need help fixing your imports.

**Comment by UstymUkhman** [comment]
Hi @Mugen87 ! Thanks for a quick response. That's just an alias I use in [webpack configs](https://github.com/UstymUkhman/color-grading/blob/master/webpack.config.js#L95), never encountered problems with this.

**Comment by UstymUkhman** [comment]
**Update:** for those having similar issues, the fix I found was to use `VideoTexture` instead of a `Texture` even if I was using `texture.needsUpdate = true` in my render loop. Also, for some reason the `Texture` uniform isn't set correctly in `TextureLoader.load` callback, so this didn't work for me:

```
this.textureLoader.load(`./lut_table.png`, texture => {
  texture.minFilter = LinearFilter;
  texture.magFilter = LinearFilter;

  this.grading = new ShaderPass(
    new ShaderMaterial({
      fragmentShader: fragGrading,
      vertexShader: vertGrading,

      uniforms: {
        frame: { value: this.videoTexture },
        grading: { value: texture }
      }
    })
  );

  this.composer.addPass(this.grading);
});
```

But setting the uniform once again like this:

```
this.grading.material.uniforms.grading.value = texture;
```

did the trick. You can check full source code [here](https://github.com/UstymUkhman/color-grading/blob/master/src/ColorGrading.js).
