### ISSUE TITLE
Invalid Internal Format gl.DEPTH_STENCIL

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#19928]
Safari WebGL2 context only

    WebGL: INVALID_ENUM: renderbufferStorage: invalid internalformat

in `WebGLTextures.js`
```js
_gl.renderbufferStorage( _gl.RENDERBUFFER, _gl.DEPTH_STENCIL, renderTarget.width, renderTarget.height );
```

Disabling the stencil buffer for shadows removes the symptoms, but I expect that is not the proper fix.

/ping @aardgoose 
/ping @gkjohnson 

https://threejs.org/examples/webgl_shadowmap.html (EDIT: With #19927, this example is no longer an issue.)

![Screen Shot 2020-07-25 at 5 03 18 PM](https://user-images.githubusercontent.com/1000017/88468114-ef238280-ceac-11ea-880c-9883cb7c800a.png)

https://threejs.org/examples/webgl_clipping_stencil.html (EDIT: This is now working with Safari 14.)

![Screen Shot 2020-07-25 at 5 38 42 PM](https://user-images.githubusercontent.com/1000017/88468118-f9de1780-ceac-11ea-8850-43abf75628df.png)

##### Three.js version

- [ x ] Dev
- [ x ] r118

##### Browser

- [ x ] Safari - 13.1.2

##### OS

- [ x ] macOS
- [ x ] iOS

**Comment by WestLangley** [comment]
It may be this is NOT a device issue. Other browsers may be converting the specified internal format to something acceptable.

**Comment by gkjohnson** [comment]
I can't test with safari at the moment but presumably this happens with any example that uses a render target and doesn't disable the stencil buffer?

I'm less familiar with the difference in browser implementations of webgl but [according to the spec](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/renderbufferStorage) `DEPTH_STENCIL` should be a valid value for WebGL2 which makes it sound like a browser issue unless there's something more to it.

> When using a WebGL 2 context, the following values are available __additionally__:
> ...

Maybe it's worth trying some other depth buffer types new to WebGL2? `gl.DEPTH_COMPONENT24`, `gl.DEPTH_COMPONENT32F`, `gl.DEPTH24_STENCIL8`, or `gl.DEPTH32F_STENCIL8`.

**Comment by Mugen87** [comment]
I've tested https://threejs.org/examples/webgl_shadowmap.html on macOS 10.15.6 with Safari 13.1.2 and it runs correctly on my iMac. Same for https://threejs.org/examples/webgl_clipping_stencil.html.

**Comment by mrdoob** [comment]
@WestLangley Is this using Safari's WebGL2 experimental setting?

**Comment by WestLangley** [comment]
>I guess this is using Safari's WebGL2 experimental setting?

Correct.

>Safari 13.1.2 and it runs as expected.

With a WebGL2 context?

**Comment by mrdoob** [comment]
I don't know if this is a case of WebGL2 in Safari being more strict or being incomplete.
FWIW, Safari 14 has a different WebGL 2 implementation (ANGLE based).

**Comment by WestLangley** [comment]
>I don't know if this is a case of WebGL2 in Safari being more strict or being incomplete.

well-said.   :-)

**Comment by Mugen87** [comment]
> With a WebGL2 context?

Checked this now and it uses WebGL 1.

**Comment by WestLangley** [comment]
@Mugen87 Please enable experimental WebGL2 in the Develop method. This PR is about Safari WebGL2 context only.

**Comment by Mugen87** [comment]
Okay, now I can reproduce. I was not aware that it's necessary to enable the flag.

**Comment by Mugen87** [comment]
How about revisiting this topic with Safari 14? I mean if the implementation will be a new one, does it makes sense to invest now time in this issue?

**Comment by gkjohnson** [comment]
I just tested this in Safari 14 and the stencil clip planes example seems to work, now.

**Comment by mrdoob** [comment]
@WestLangley Is there any issue left?

**Comment by WestLangley** [comment]
I do not think so. Closing.
