### ISSUE TITLE
 When i was loading a Revit model, the model in three.js was all BLACK...

### ISSUE THREAD

**Issue by 674019130** [mrdoob/three.js#19941]
##### Description of the problem
The model is from Revit, I tried to export its model info to a .json file.
When I was loading the json file, there's no error in Chrome console, but my model was all black.
I've changed parameters about "materials", but it didn't work.
I also changed the three.js's version, it still didn't work.

This is my .json file: 
https://paste.ubuntu.com/p/J8sYXbvxYf/

And this is my .html file: 
https://paste.ubuntu.com/p/bgHmHPppGc/

![image](https://user-images.githubusercontent.com/26924933/88639851-d0f99480-d0ef-11ea-9c88-9766f7feca30.png)
![image](https://user-images.githubusercontent.com/26924933/88639901-e078dd80-d0ef-11ea-96c5-2dda4647b0c5.png)

##### Three.js version

- [x] r95
- [x] r103
- [x] r106
- [x] r107
- [x] r108

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

graphics card: NVIDIA GeForce GTX 1650

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help reqeusts.
