### ISSUE TITLE
WebGL GPGPU Birds + GLTF Mesh Loading Example Fails to Render in Safari

### ISSUE THREAD

**Issue by jonobr1** [mrdoob/three.js#19957]
##### Description of the problem

Stemming off of the work from this issue: https://github.com/mrdoob/three.js/issues/19837

This example on the Three.js site doesn't work in Safari (Mobile or otherwise). There aren't any errors it just hangs on a light blue screen: https://threejs.org/examples/?q=gpgpu#webgl_gpgpu_birds_gltf

<img width="1552" alt="Screen Shot 2020-07-30 at 10 00 19 AM" src="https://user-images.githubusercontent.com/220033/88932008-84c36700-d24b-11ea-9af3-383ac7839739.png">
Screenshot from my 2018 13" MacBook Pro.

##### Three.js version

- [ ] Dev
- [x] r119
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

**Comment by Mugen87** [comment]
I can no longer reproduce this issue with Safari 14 on macOS 10.15.6.
