### ISSUE TITLE
How does threejs load CAD drawing, such as DWG format file

### ISSUE THREAD

**Issue by aixue0909** [mrdoob/three.js#19961]
##### Description of the problem

How does threejs load CAD drawing, such as DWG format file

##### Three.js version
r119

##### Browser

- [ ] Chrome

##### OS

- [ ] Windows

**Comment by donmccurdy** [comment]
Please use the forum for questions (I’ve replied to https://discourse.threejs.org/t/how-to-load-cad-drawing-with-threejs/17523/2).
