### ISSUE TITLE
NodeMaterial: FunctionNode not able to parse function signature containing /n

### ISSUE THREAD

**Issue by martinRenou** [mrdoob/three.js#19971]
##### Description of the problem

cc. @sunag

When creating a `FunctionNode` as following:

```javascript
var node = new Nodes.FunctionNode(
  `vec3 test(vec3 in1,
             float in2) {
     return in1;
   }`
);
```

followed by a `FunctionNodeCall`, the `FunctionNodeCall` generated result is `"(  )"` and the code is `""`.

It's only when removing the `/n` that it works as intended.

```javascript
var node = new Nodes.FunctionNode(
  `vec3 test(vec3 in1, float in2) {
     return in1;
   }`
);
```

The generated result here is `"test(nodeU1, nodeU2)"` and the code is `"vec3 test(vec3 in1, float in2) {
     return in1;
   }"`.

I'd be happy to open a PR for this issue.

##### Three.js version

r118

**Comment by sunag** [comment]
I think that It modify the regexp this shoud be work? A PR should be great.
