### ISSUE TITLE
Fragment shader rendering glitchy on MacOS

### ISSUE THREAD

**Issue by raray** [mrdoob/three.js#19973]
##### Description of the problem

I am experiencing an odd glitch when trying to implement an adapted fragment shader from Shadertoy. Everything renders correctly on when I have a cinema display plugged into my Macbook:

![image](https://user-images.githubusercontent.com/1738632/89049336-b9502500-d316-11ea-96fa-acd8fee3a07d.png)

It also appears to render correctly, although somewhat differently on my Windows machine. However, when I unplug the monitor (and re-render) the shader becomes glitched:

![image](https://user-images.githubusercontent.com/1738632/89049457-eac8f080-d316-11ea-8e7b-64e0bba5e726.png)

I cannot reproduce the issue at all when viewing the Shadertoy that I adapted from: https://www.shadertoy.com/view/4slXzs

* [codepen](https://codepen.io/r-a-ray/pen/ExPqyyj) (latest release branch)

##### Three.js version

- [ ] Dev
- [x] r119
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] macOS (10.15.6)
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
> However, when I unplug the monitor (and re-render) the shader becomes glitched:

Um, I'm not able to reproduce this on a windows machine with your codepen. Meaning I have unplugged the external monitor, plugged in again and everything rendered fine.

I also can't imagine a root cause for this glitch in `three.js` 🤔 . Do you see similar rendering issues with the official `three.js` examples? Can you also test with other 3D engines e.g. BabylonJS (https://doc.babylonjs.com/examples/)?

**Comment by mrdoob** [comment]
I can reproduce on MacOS and I spent 2 hours debugging this.

The shader you're using in three.js has `#define USE_PROCEDURAL`, but in ShaderToy is commented.

If you remove the comment you'll get this:

<img width="1189" alt="Screen Shot 2020-08-01 at 6 31 26 PM" src="https://user-images.githubusercontent.com/97088/89105867-ecea9680-d45f-11ea-8a47-aad9002c17fe.png">

Please, use the forum or discord the net time you have a glsl issue.
