### ISSUE TITLE
Remove `examples` from NPM package

### ISSUE THREAD

**Issue by ogonkov** [mrdoob/three.js#20019]
##### Description of the problem

For latest (`three@0.119.1`) package version `examples` folder in NPM package is took around 19 mb (mac Finder shows 17.7 mb).

I believe it's a lot and should not be included in NPM package. Anyone could checkout repo and run any examples it need.

```
% du -hsx ./node_modules/three/examples | sort -n -r | head -n 10 
 19M    ./node_modules/three/examples
```

I can create PR.

##### Three.js version

- [x] r119

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

-

**Comment by Mugen87** [comment]
Sorry, it's not possible to do this. Many important modules are in the `examples/jsm` directory.

When `examples/js` is going to be removed at the end of the year, the `npm` package will be smaller, too.

**Comment by ogonkov** [comment]
@Mugen87 Package will stop work without `examples/js`?

**Comment by Mugen87** [comment]
Removing `examples/jsm` will break a lot of code so it's not something that is going to be removed.

**Comment by donmccurdy** [comment]
It's worth noting that a significant part of that size is not the _source code_ in `examples/js` and `examples/jsm`, but the third-party libraries in `examples/js/libs` and `examples/jsm/libs`. The source code may depend on libraries, though, so it's still not trivial to delete. Maybe sourcemap support (and removing `examples/js`) will eventually allow us to not bundle those.

**Comment by ogonkov** [comment]
I still didn't get why a significant part of package is inside `examples` folder, but I guess you better know.

**Comment by donmccurdy** [comment]
See the [Installation – Examples](https://threejs.org/docs/#manual/en/introduction/Installation) section in the docs. The three.js library includes many optional modules that are not bundled into the main build.

**Comment by ogonkov** [comment]
Looks like three.js required to be split to few `@three/*` packages, it's strange to keep them in a single package and let people download 20mb extra.

**Comment by donmccurdy** [comment]
Publishing each module separately would require hundreds of packages, and much more complicated maintenance. I don't think that's likely to happen. The download only happens during `npm install three` step, and only the parts you need are actually bundled into your final application.

Per https://github.com/mrdoob/three.js/issues/20019#issuecomment-669395305, there may be ways to improve this in the next year or two.

**Comment by ogonkov** [comment]
The reason for this issue way the fact that we save `node_modules` as artifact in CI workflow, and today it reach limit. I start investigate and found three.js package.

I guess I should rm -rf some parts before archiving it, since it's not possible to reduce package size the other way.

**Comment by LeviPesin** [comment]
I think we can remove all folders in examples except the `examples/jsm` folders -- that means, all assets and examples themselves.

**Comment by LeviPesin** [comment]
Oh wait... They are already not included:
```json
"files": [
    "build",
    "examples/jsm",
    "examples/fonts",
    "LICENSE",
    "package.json",
    "README.md",
    "src"
  ],
```
Maybe we could remove fonts, will it shake off some size?
Also maybe we could remove `src` and maybe even, for example... Create a directory `build/addons` (to which we'll point `three/addons`) where minified addons could be stored and publish only them?

**Comment by LeviPesin** [comment]
If we decide to do that, I think it would be useful to report how much size NPM package takes... @marcofugaro Can you add this to the CI size reporting?

**Comment by mrdoob** [comment]
Why do we have to reduce npm package size?

**Comment by marcofugaro** [comment]
Oh we can't remove `fonts` and `src` folders, people are currently using them.

Reducing npm package size produces no real direct benefits apart from reducing the memory occupied on the user's hard disk, which is not a really important metric to worry about.
