### ISSUE TITLE
Doesn't save rigging coordinates in editor using animations.

### ISSUE THREAD

**Issue by joesnows** [mrdoob/three.js#20020]
I've been trying to work with animations in threeJS editor recently, and i tried several files and methods to see which was better, and it works majorly well with most of them, *fbx, *dae, *gls, etc. Upon loading it reads the animation flawlessly, with very good results, can edit everything as well.
When i try to save the scene to a *json file it automatically removes the bones of characters and any animation info that was assigned to them. This happens only with bones.

 This is when working in the editor (i disabled the view of bones)

![image](https://user-images.githubusercontent.com/56345803/89434646-afc22500-d73b-11ea-84ba-01e154e375bf.png)

This is what happens when reopening the browser(with cache on) or the exported *json scene:

![image](https://user-images.githubusercontent.com/56345803/89434818-ec8e1c00-d73b-11ea-8532-286f60f0acd3.png)

Hope it was helpfull, this would solve some problems for me as a digital artist.
Thank you, 
best regards.

**Comment by Mugen87** [comment]
That because `SkinnedMesh` does not yet support serialization/deserialization. There was already a PR trying to implement this feature in the past (#15413) though.

**Comment by Mugen87** [comment]
We've lately added serialization/deserialization support for `SkinnedMesh` (see #20589) so it's now possible to save/reload an editor project without loosing bones anymore.

However, exporting to `three.js` JSON format does not yet honor animations. But this missing feature is tracked here: #16234
