### ISSUE TITLE
How to display and use buttons in an AR Scene ?

### ISSUE THREAD

**Issue by CGriffoin** [mrdoob/three.js#20037]
##### Description of the problem

Hi team,

I'm working on a AR project, where I load a simple glTF object.
I would like to use buttons (like ARButton)  in my AR scene to do some stuff (rotations, change mesh color ,etc...).
I don't want to use a GUI folder system, I juste need a simple button and attach an handler (using click event, select event or touch event).

I'm started from [hittest example](https://threejs.org/examples/#webxr_ar_hittest).

Best regards.

##### Three.js version

- [ ] Dev
- [x] r119
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Mobile phone with Android 10.

**Comment by CGriffoin** [comment]
Here my simple AR scene

My HTML "START AR" page look like this :
![image](https://user-images.githubusercontent.com/912641/89652701-2b4fdd80-d8c6-11ea-88f3-00140e2c9a60.png)

When the AR scene is started, it look like that :
![image](https://user-images.githubusercontent.com/912641/89652200-6a316380-d8c5-11ea-9d3e-e3e29719eb76.png)

When I try to add arguments `optionalFeatures` in ARButton to show him in the scene, like this :

```javascript
var arButton = ARButton.createButton(renderer, { requiredFeatures: ['hit-test'], optionalFeatures: [ 'dom-overlay', 'dom-overlay-for-handheld-ar' ], domOverlay: { root: document.body } });
```

I've this result :
![image](https://user-images.githubusercontent.com/912641/89652548-e88e0580-d8c5-11ea-9058-db5f957a6419.png)

... Ok, I can see the button "STOP AR"... But I don't know what's going on with the scene...

**Comment by PalashBansal96** [comment]
It looks like a black DOM overlay over the camera, below you can see the floor. 

You can try to inspect the webpage content by going to `chrome://inspect/#devices` on desktop and connecting an android phone with USB debugging enabled. It will then mention all the tabs on your mobile Chrome app.  Clicking on anyone you can inspect the webpage exactly as you would on the desktop.

**Comment by PalashBansal96** [comment]
Instead of using `document.body` in `domOverlay.root`, you could try a transparent full-screen div that's over or after the canvas.

**Comment by WestLangley** [comment]
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

**Comment by PalashBansal96** [comment]
In case someone comes here looking for a solution, there is a need to set `renderer.domElement.style.display = 'none'` when the session starts and back to default when it ends `renderer.domElement.style.display = ''`
