### ISSUE TITLE
No antialiasing with .clippingPlanes property of Material

### ISSUE THREAD

**Issue by msc5** [mrdoob/three.js#20052]
##### Description of the problem

This bug occurs when using the .clippingPlanes property of a Material. Antialiasing does not occur at the edges of clipped objects, even when the renderer is configured with 'antialias' = true.

The bug is visible in the example for .clippingPlanes.

link: https://threejs.org/examples/#webgl_clipping_intersection

**Comment by gkjohnson** [comment]
This is a limitation of WebGL and a product of using `discard` to reject pixels during rendering so unfortunately three.js can't do anything about this when relying on the built-in WebGL AA. You'll have to use a different AA method like [FXAA](https://threejs.org/examples/webgl_postprocessing_fxaa.html) or a super sampling approach.
