### ISSUE TITLE
GLTFLoader: Alpha mode should default to Blend when material color has transparency

### ISSUE THREAD

**Issue by diegoescala** [mrdoob/three.js#20058]
##### Description of the problem
Some software exports GLTFs without setting alpha mode, even in materials with transparency. Blender correctly renders these materials as transparent, but the GLTFLoader defaults to opaque even when an alpha < 1.0 is specified in the material.

##### Suggested solution
When alpha < 1.0, if no `alphaMode` is specified, default to `BLEND` rather than `OPAQUE`.

**Comment by donmccurdy** [comment]
The glTF specification is pretty specific than when alphaMode=OPAQUE, any transparency in the baseColorTexture or baseColorFactor must be ignored by implementations. I think it would be necessary to report bugs to software exporting glTF without setting alpha mode. Do you have an example?

**Comment by diegoescala** [comment]
Yes, OnShape does not appear to be setting the flag when exporting.
    On Wednesday, August 12, 2020, 12:27:45 PM CDT, Don McCurdy <notifications@github.com> wrote:  
 
 


The glTF specification is pretty specific than when alphaMode=OPAQUE, any transparency in the baseColorTexture or baseColorFactor must be ignored by implementations. I think it would be necessary to report bugs to software exporting glTF without setting alpha mode. Do you have an example?

**Comment by WestLangley** [comment]
>When alpha < 1.0, if no alphaMode is specified, default to BLEND rather than OPAQUE.

According to glTF spec 2.0, the `alphaMode` property specifies how alpha is interpreted -- not the other way around.

Also, `alphaMode` is not required, and defaults to `OPAQUE`.

**Comment by diegoescala** [comment]
Thanks. Sounds like the implementation in the loader conforms to the spec then. I fail to see the logic behind defaulting to opaque when a material is clearly transparent, but that is a question for a different forum.

On August 12, 2020 1:11:39 PM CDT, WestLangley <notifications@github.com> wrote:
>>When alpha < 1.0, if no alphaMode is specified, default to BLEND
>rather than OPAQUE.
>
>According to glTF spec 2.0, the `alphaMode` property specifies how
>alpha is interpreted -- not the other way around.
>
>Also, `alphaMode` is not required, and defaults to `OPAQUE`.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrdoob/three.js/issues/20058#issuecomment-673030293

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by WestLangley** [comment]
>I fail to see the logic behind defaulting to opaque when a material is clearly transparent

It is not always so clear. Transparency can be set in the alpha channel of the texture. The loader is not expected to discern that.

**Comment by diegoescala** [comment]
Yes, good point.
    On Wednesday, August 12, 2020, 01:51:17 PM CDT, WestLangley <notifications@github.com> wrote:  
 
 



I fail to see the logic behind defaulting to opaque when a material is clearly transparent


It is not always so clear. Transparency can be set in the alpha channel of the texture. The loader is not expected to discern that.
