### ISSUE TITLE
WebGLBindingState crash if cachedAttribute does not exist

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#20054]
##### Description of the problem

I don't know if this is wrong or just different. All I know is my code broke in multiple ways between r115 and r119

One way is it crashes here

https://github.com/mrdoob/three.js/blob/d46af62ef74fc03ff398551115cf44d9c709e745/src/renderers/webgl/WebGLBindingStates.js#L178

What I'm doing is I have a morph target that uses position (which three.js supports) and do that I add color (which three.js does not support so I modify the shaders). Three.js adds or removes morphTarget attributes based on their influence so what my code does is in `onBeforeRender` I check which morphTargets are being used by iterating over them. For each one that exists I add my color target attribute. Pseudo code

 ```
for (i = 0; i < maxTarget; ++i) {
   // check if three is using a certain position morph target
   const attribute = geometry.getAttribute(`morphTarget${i}`);
   if (attribute) {
     // figure out which position data is assigned to this morphTarget
     const positionTargetNdx = computePositionTargetIndex(attribute);
     // add in the corresponding color target
     geometry.setAttribute(`morphColor${i}`, arrayOfColorAttributes[positionTargetNdx]);
   }
}
```

Until r115 this worked. At r119 it crashes at this line

https://github.com/mrdoob/three.js/blob/d46af62ef74fc03ff398551115cf44d9c709e745/src/renderers/webgl/WebGLBindingStates.js#L178

Is that intended? It seems like these lines

```
			if ( cachedAttribute.attribute !== geometryAttribute ) return true;

			if ( cachedAttribute.data !== geometryAttribute.data ) return true;
``` 

should be proceded  by this?

```
            if (!cachedAttribute) return true;
```

Though also even if I add that in my code no longer works. I guess that's a separate issue though. Is adding the check that `cachedAttribute` actually exists a correct change?

##### Three.js version

- [ ] Dev
- [X] r119
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by takahirox** [comment]
Thanks for the bug report!

> should be proceded by this?
> ```
>    if (!cachedAttribute) return true;
> ```

It seems you are right. `cachedAttribute` can be `undefined` if one removes an attribute from a geometry and adds another one with different name to it. We should fix.

> Though also even if I add that in my code no longer works.

Could you share your app? It would help us look into the problem.

**Comment by greggman** [comment]
> Could you share your app? It would help us look into the problem. Error console logs or explanation about how weird it will be also helps.

Yes, it seemed irrelevant to this particular issue. I'm still trying to figure out what else is wrong but I will post it when I figure it out.

**Comment by takahirox** [comment]
I see, thanks.

Regarding adding

```javascript
if (!cachedAttribute) return true;
```

Would you like to make PR? Or do you want me to do that?
