### ISSUE TITLE
GLTFLoader: Option to enable/disable ImageBitmapLoader

### ISSUE THREAD

**Issue by amitgithub1** [mrdoob/three.js#20055]
Feature request for options for handling texture images in GLTFImporter and other importers / exporters as well

1) Image type selection (option between : data:image and URI/CanvasTexture)

2) Option to have source data and its properties, exported as well (can be done as a separate helper function, what is required is a defined storage variables, which can be also used by exporters)
     For the case of GLTFImporter: bufferview and mimeType can be stored and used when exported

Reason for request:
Importers and Exports needs to be flexible for optimizing between data store and speed and efficiency, this option enable to select as desire .. eg: I need to export the scene with minimum size so option to use source data as storage data is good for my requirement ... While while importing for displaying the scene importing in process efficient method is good.

Corresponding options to use additional source data can be used by exporters to export scene data and images.

At present i have added code to add data:image ( Filereader(blob) ) to image.src option in GLTFLoader.js, which is used but Texture.toJSON() (which inturn uses ImageUtils), the GLTFLoader otherwise loads as CanvasTexture and uses it for rendering . 

using r119

ref : https://discourse.threejs.org/t/gltf-loader-where-do-we-find-the-image-src-and-the-source-image-data-threejs-r119/17808/3

##### Three.js version

- [ ] Dev
- [ ] r119
- [ ] All

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by donmccurdy** [comment]
> Image type selection (option between : data:image and URI/CanvasTexture)

For full context, I think the request here is to have the option of turning _off_ the use of ImageBitmapLoader in browsers where it's supported, in order to have the same type of Texture instance as before. Maybe this could be done with https://threejs.org/docs/#api/en/loaders/managers/LoadingManager.addHandler, but I'm not sure? It may need an option added to GLTFLoader itself.


> Option to have source data and its properties, exported as well ...

I think preserving all of the internally source data of a glTF file in the three.js scene graph is not something we can support. It would massively complicate the loader and exporter. You may need to create custom versions of the loader and exporter for this. Or you can write whatever data you need into `.userData` on an object in three.js, and it will be added to the `.extras` metadata in the glTF file when exported to glTF.

**Comment by amitgithub1** [comment]
> think preserving all of the internally source data of a glTF file in the three.js scene graph is not something we can support.

No issues there, its can be done with some helper function after parsing (since we have access to parser variable) .. but addition of relation between 'reference to the actual image (like source.bufferView in GLTFLoader) to the image' would be helpful (as part of the parsed data metadata)

> For full context, I think the request here is to have the option of turning off the use of ImageBitmapLoader in browsers where it's supported, in order to have the same type of Texture instance as before

If we are including an option why not have option to select the type of texture!

Anyways **including of "BufferData to Texture Image" link somewhere in parsed data metadata (parser variable of the parse data) would be an ideal as this would enable us a solution with no changes to the Importer.**
something like (image/texture uuid -> source.bufferView) links in parsed_data.parser.image_buffer_relation_array
(don't mind my naming sense)

**Comment by donmccurdy** [comment]
> If we are including an option why not have option to select the type of texture Image, data:image or URI/CanvasImage!

I'm having a difficult time understanding what you are asking for, sorry. If GLTFLoader is loading a glTF file with Data URIs, it has to use the Data URIs... The only real thing this option can influence is whether GLTFLoader uses THREE.TextureLoader or THREE.ImageBitmapLoader to create the texture:

https://github.com/mrdoob/three.js/blob/d46af62ef74fc03ff398551115cf44d9c709e745/examples/js/loaders/GLTFLoader.js#L1578-L1587

If you are trying to edit a glTF file without _any_ changes to the file that come from converting to/from three.js' scene graph, you may want to consider using something like https://gltf-transform.donmccurdy.com/, which lets you edit the glTF file more directly.

**Comment by amitgithub1** [comment]
I was talking abt having the source data association available somehow:

This is what i am suggesting is something like:

```
                        if(parser.image_to_bufferView === undefined){ parser.image_to_bufferView = [] }

                        texture.image.uuid = MathUtils.generateUUID();
			parser.image_to_bufferView[texture.image.uuid] = source.bufferView
```
at https://github.com/mrdoob/three.js/blob/d46af62ef74fc03ff398551115cf44d9c709e745/examples/js/loaders/GLTFLoader.js#L2208

The above is a cleaner suggestion,

if you want to know what i mean for
>I'm having a difficult time understanding what you are asking for

i can give a dirty code changes i made for myself .. basically i added .. )
```
                              (async function () {
					data_image = await new Promise((resolve) => {
						let fileReader = new FileReader();
						fileReader.onload = (e) => resolve(fileReader.result);
						fileReader.readAsDataURL(blob);
					});
				})()
```
after https://github.com/mrdoob/three.js/blob/d46af62ef74fc03ff398551115cf44d9c709e745/examples/js/loaders/GLTFLoader.js#L2169
where data_image is a data:image which i use

https://gltf-transform.donmccurdy.com/ is a great solution, it also exports Animation (with JSON, i have to make changes to make Animations work) ..  but had same issues where GLTF->THREEJS->GLTF leaves me with reencoded and extra copies 
 images

**Comment by donmccurdy** [comment]
Sorry, I don't think we can preserve these image-to-bufferview mappings for you. This is too specific of a use case for GLTFLoader. You may need to customize GLTFLoader for this. Perhaps the extension API can be used to do that without forking the loader, take a look at how the KHR_texture_basisu extension is implemented:

https://github.com/mrdoob/three.js/blob/d46af62ef74fc03ff398551115cf44d9c709e745/examples/js/loaders/GLTFLoader.js#L610

**Comment by amitgithub1** [comment]
no issues :) i'd be customizing GLTFLoader

**Comment by Mugen87** [comment]
@donmccurdy Can this issue be closed?
