### ISSUE TITLE
GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 1

### ISSUE THREAD

**Issue by lesssn** [mrdoob/three.js#20062]
##### Description of the problem

I created a mesh with 153,000 points，when I call `geometry.computeVertexNormals()`, the following error occurred `GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 1`，The key code snippets are as follows。

```js
 // points contains 153000 vertices
 geometry.setAttribute('position', new THREE.Float32BufferAttribute(points, 3))

 //  computeFacesNodes is a custom function 
let faceIndexes = computeFacesNodes(points, lineItemLength)

geometry.index = new THREE.Uint32BufferAttribute(faceIndexes, 1)

// error occurred ！！
geometry.computeVertexNormals()
```

##### Three.js version

- [ ] Dev
- [x] r114  
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
Please, use the [forum](https://discourse.threejs.org/) or the [chat](https://discord.gg/HF4UdyF) for help.
