### ISSUE TITLE
Example "WebGL / Materials / Physical / Transparency" is missing

### ISSUE THREAD

**Issue by youyi1996** [mrdoob/three.js#20091]
In the documentation of Material ([https://threejs.org/docs/index.html#api/en/materials/Material](https://threejs.org/docs/index.html#api/en/materials/Material)), it mentions example WebGL / Materials / Physical / Transparency in the description of property `.premultipliedAlpha`.
However, there's no such example in r119.

**Comment by donmccurdy** [comment]
Thanks for letting us know! This example has been renamed, to WebGL / Materials / Physical / Transmission: https://threejs.org/examples/?q=transmission#webgl_materials_physical_transmission

**Comment by youyi1996** [comment]
Thanks for your reply. :)
