### ISSUE TITLE
EXRLoader improvement - PXR24 compression

### ISSUE THREAD

**Issue by photopea** [mrdoob/three.js#20096]
The PXR24 compression is similar to a ZIP compression, there is just a different predictor and interleaving.

I implemented it below, but it still shows some artifacts. Would you be able to find a bug?

    function uncompressPXR24( info ) {
        var compressed = info.array.slice( info.offset.value, info.offset.value + info.size );
        var inflate = new Inflate( compressed, { resize: true, verify: true } ); // eslint-disable-line no-undef
        var rawBuffer = new Uint8Array( inflate.decompress().buffer );

        // predictor
        var dec = rawBuffer, w=width;
        for(var o=0; o<dec.length; o+=w) {
            var v = 0;
            for(var j=0; j<w; j++) {
                v = (v+(dec[o+j]))&255;  dec[o+j]=v;
            }
        }
        // interleave
        for(var o=0; o<dec.length; o+=2*w) {
            var v = 0;
            for(var j=0; j<w; j++) {
                tmpBuffer[o+2*j  ]=dec[o+j+w];
                tmpBuffer[o+2*j+1]=dec[o+j];
            }
        }
        return new DataView( tmpBuffer.buffer );
    }

I tested it on [this image](https://github.com/AcademySoftwareFoundation/openexr-images/blob/master/TestImages/SquaresSwirls.exr) . The right result is on the left, the result of my code is on the right side.

![image (2)](https://user-images.githubusercontent.com/15955558/90382743-7795dd00-e07f-11ea-9f57-786c1fc158e6.png)

**Comment by sciecode** [comment]
@photopea according to [OpenEXR implementation](https://github.com/AcademySoftwareFoundation/openexr/blob/master/OpenEXR/IlmImf/ImfPxr24Compressor.cpp), ZIP compression is indeed used for PXR24, but the predictor step is type and channel dependant. At a quick glance, I wasn't able to spot any similarity between your code and OpenEXR.

Try to double check if your implementation is indeed following `Pxr24Compressor::uncompress`

**Comment by photopea** [comment]
Oh, I did not know there exists any open implementation of EXR format. I created my code by trial and error.

So here is a correct implementation, in case you want to use it in your library :) (use it the same way as uncompressZIP)

    function uncompressPXR24( info ) {
        var compressed = info.array.slice( info.offset.value, info.offset.value + info.size );
        var inflate = new Inflate( compressed, { resize: true, verify: true } ); // eslint-disable-line no-undef
        var rawBuffer = new Uint8Array( inflate.decompress().buffer );

        var dec = tmpBuffer, w=width;
        for(var o=0; o<dec.length; o+=2*w) {
            for(var j=0; j<w; j++) {
                dec[o+2*j  ]=rawBuffer[o+j+w];
                dec[o+2*j+1]=rawBuffer[o+j];
            }
            var uarr = new Uint16Array(dec.buffer,o,w);
            for(var j=1; j<w; j++) uarr[j] = (uarr[j-1]+uarr[j])&0xffff;
        }
        return new DataView( tmpBuffer.buffer );
    }

**Comment by sciecode** [comment]
Alrighty! Thanks for that. Apparently we have to deal with the uncompression step differently depending if the underlying data is HALF or FLOAT, but that's already a great step forward. Thanks for that @photopea.

Do you want to create a PR yourself? or would you prefer if I did it?

**Comment by photopea** [comment]
I don't use GIT, so you can do it :) If you have any EXR files which the code can not handle, share them wiht me and I will fix it :)

It is really hard to write a proper code without having actual files to test it on.

**Comment by sciecode** [comment]
Yeah, I've been using the OpenEXR test files for that.

But, not worries. I'll prepare the PR until the end of the day. I'll make sure to ping you for testing as well ❤️
