### ISSUE TITLE
PointLightShadow is not exported

### ISSUE THREAD

**Issue by dmnsgn** [mrdoob/three.js#20109]
##### Description of the problem

https://github.com/mrdoob/three.js/blob/5a8c62fe37420429377de25885acf8878f2bcb1e/src/Three.js#L56-L63 LightShadow, DirectionalLightShadow and SpotLightShadow are exported but not **PointLightShadow**.

##### Three.js version

- [X] Dev

##### Browser

- [x] All of them
##### OS

- [x] All of them

##### Hardware Requirements (graphics card, VR Device, ...)

N/A

**Comment by Mugen87** [comment]
I don't think any `LightShadow` class should be exported. They are for internal use only.

**Comment by WestLangley** [comment]
>I don't think any LightShadow class should be exported. They are for internal use only.

Actually, I use this pattern:
```js
// setting a custom shadow frustum
light.shadow = new THREE.LightShadow( new THREE.PerspectiveCamera( 22.5, 1, 200, 700 ) );
```
The default frustum is unnecessarily oversized for my preference.

**Comment by Mugen87** [comment]
In this case, I think it's better to modify the existing frustum instead. Besides, none of the examples uses this pattern.

Don't get me wrong, I don't want to criticize your coding style. I'm just having problems with replacing such properties with new objects. We also don't do this for `position`, `rotation` and `scale`. 

This approach might break renderer internal code if shadow objects are cached.

**Comment by Mugen87** [comment]
Another reasons why the engine should not promote this style: User might assign wrong light shadow classes to lights. The default assignment is correct.

**Comment by WestLangley** [comment]
OK. This works fine:
```js
light.shadow.camera.fov = THREE.MathUtils.RAD2DEG * 2 * light.angle / 2; //  half as big as the default
```
Maybe what I referenced was a legacy pattern...

**Comment by WestLangley** [comment]
#20139 Has now broken my app.

    Uncaught TypeError: THREE.LightShadow is not a constructor

I think we should continue to export these classes until we can develop an appropriate alternate API.

**Comment by Mugen87** [comment]
> This code block changes the shadow camera helper, but not the shadow camera itself -- likely because the shadow camera is auto-sized each frame.

I would like to investigate this use case more clear. Do you mind creating a live example that demonstrates the issue?

I think we should give the removal a try. If more users complain, we can still to the revert.

**Comment by mrdoob** [comment]
Reminds me to when we used to allow `mesh.position = new THREE.Vector3()` or `mesh.position = mesh2.position`.

**Comment by mrdoob** [comment]
@WestLangley 

> So what is the recommended pattern to focus the shadow camera frustum -- both prior to rendering, and after rendering at least once?

Yes, we desperately need something like `light.shadow.contain( scene )` or something like that.

**Comment by Mugen87** [comment]
Instead of reverting #20139 we could also only add `LightShadow` back in the meanwhile. I just feel we should not expose `LightShadow` classes for the long-term.

**Comment by RemusMar** [comment]
@WestLangley @Mugen87 @mrdoob 
> Actually, I use this pattern:
>
> // setting a custom shadow frustum
> light.shadow = new THREE.LightShadow( new THREE.PerspectiveCamera( 22.5, 1, 200, 700 ) );
> 
> The default frustum is unnecessarily oversized for my preference.

+1 (for many years).
I had to remove the THREE.LightShadow from my samples a couple of days ago.
And I didn't like that (Michael, the backwards compatibility !?!)
On top of that, the default frustum does not provide the best results in any scenario.
The bottom line: if LightShadow is not exported, an alternative API is a must.
My 2 cents.

**Comment by WestLangley** [comment]
ref: Restore LightShadow export for now #20171

**Comment by Mugen87** [comment]
I suggest to close this issue and create a new one which focuses on a replacement for exporting `LightShadow`. It seems the engine only needs to find out a way so users can actually set the `fov` value of a spot light's shadow camera. One possible solution is presented here:

https://github.com/mrdoob/three.js/pull/20147#issuecomment-679092113

**Comment by Mugen87** [comment]
Closing in favor of #20216.
