### ISSUE TITLE
Black screen after toggling fullscreen mode

### ISSUE THREAD

**Issue by sahilmob** [mrdoob/three.js#20188]
##### Description
I'm using a library called [panolens](https://github.com/pchen66/panolens.js) to show a panoramic (360 dgree) view, which depends on three.js, my app has two views, one of them has custom content and the other used as a container for panolens, by default the first view is visible (has `display: block`) and the panolens container is hidden (has`display: none`) and there is two buttons to toggle between the two views (flips the display property for each container), also there is a button to switch to full screen mode using the `requestFullscreen` method.

When I toggle full screen mode (enter then exit full screen mode) and then switch to the panoles view, it shows a black screen.

#### Live example

* [codepen](https://codepen.io/sahilmob/pen/YzqydyP)

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by Mugen87** [comment]
Sorry, but this is not a help site. Please use the [forum](https://discourse.threejs.org/) or stackoverflow instead.
