### ISSUE TITLE
THREE.InstancedMesh: instanceCount property

### ISSUE THREAD

**Issue by xjindf** [mrdoob/three.js#20180]
When I set the . count property of InstancedMesh to fill the buffer, I notice that it draws all instances. However, I want to dynamically control the number of drawing instances. It is similar to the instanceCount property of InstancedBufferGeometry. When I extend InstancedMesh and add such attributes as instanceOpacity, modifying the updateRange of BufferAttribute seems to have no effect! I hope instancedmesh can add the same API as InstancedBufferGeometry. Thank you!

**Comment by xjindf** [comment]
if ( object.isInstancedMesh ) {

                      ****const instanceCount = Math.min( object.instanceCount, object.count );
			renderer.renderInstances( drawStart, drawCount, instanceCount  );****

		} else if ( geometry.isInstancedBufferGeometry ) {

			const instanceCount = Math.min( geometry.instanceCount, geometry._maxInstanceCount );

			renderer.renderInstances( drawStart, drawCount, instanceCount );

		} else {

			renderer.render( drawStart, drawCount );

		}

**Comment by Mugen87** [comment]
Please continue the discussion at the forum.

https://discourse.threejs.org/t/modified-three-instancedmesh-dynamically-instancecount/18124
