### ISSUE TITLE
ObjLoader2 fails with Google Poly Models

### ISSUE THREAD

**Issue by jkelleyrtp** [mrdoob/three.js#20187]
##### Description of the problem

Google Poly is a solid source for 3D objects. I want to use them in my scene, loaded dynamically, and instance them. ObjLoader is really slow, but ObjLoader2 seems faster. Unfortunately, loading the .obj files and running them through the parsing fails without much context. I have to assume it's a configuration issue.

My Model (s):
https://poly.googleapis.com/downloads/fp/1598349081707035/5oKgAeAjy4L/aZe9YOozU9V/StorageFacility.obj
https://poly.googleapis.com/downloads/fp/1598348780086706/5UU85o2PgY6/fhRJu_OZEZp/model.obj

It's really any google poly model. If these links don't work, then pick any model off poly.google.com.
```
oh no! loading failed TypeError: meshOutputGroup.vertices is undefined
    _finalizeRawMesh OBJLoader2Parser.js:808
    _processCompletedMesh OBJLoader2Parser.js:857
    _checkFaceType OBJLoader2Parser.js:664
    _processLine OBJLoader2Parser.js:559
    executeLegacy OBJLoader2Parser.js:430
    parse OBJLoader2.js:349
```

##### Three.js version

- [x] r119

##### Browser

- [x] All of them

##### OS

- [x] All of them

##### Code
jsfiddle seems to be down (or just really slow?) 
Here's what I have in the fiddle:
```
// Simple three.js example

import * as THREE from "https://threejs.org/build/three.module.js";
import { OrbitControls } from "https://threejs.org/examples/jsm/controls/OrbitControls.js";
import { OBJLoader2 } from "https://threejs.org/examples/jsm/loaders/OBJLoader2";

var mesh, renderer, scene, camera, controls;

init();
animate();

function init() {

    // renderer
    renderer = new THREE.WebGLRenderer();
    renderer.setSize( window.innerWidth, window.innerHeight );
    renderer.setPixelRatio( window.devicePixelRatio );
    document.body.appendChild( renderer.domElement );

    // scene
    scene = new THREE.Scene();
    
    // camera
    camera = new THREE.PerspectiveCamera( 40, window.innerWidth / window.innerHeight, 1, 10000 );
    camera.position.set( 20, 20, 20 );

    // controls
    controls = new OrbitControls( camera, renderer.domElement );
    
    // ambient
    scene.add( new THREE.AmbientLight( 0x222222 ) );
    
    // light
    var light = new THREE.DirectionalLight( 0xffffff, 1 );
    light.position.set( 20,20, 0 );
    scene.add( light );
    
    // axes
    scene.add( new THREE.AxesHelper( 20 ) );

		let loader = new OBJLoader2();
    
    loader.load("https://poly.googleapis.com/downloads/fp/1598348780086706/5UU85o2PgY6/fhRJu_OZEZp/model.obj", (model) => {
	    scene.add(model);
      console.log('hello');
    });
    
}

function animate() {

    requestAnimationFrame( animate );
    
    //controls.update();

    renderer.render( scene, camera );

}
```

**Comment by mrdoob** [comment]
Do they load with `OBJLoader`?

**Comment by jkelleyrtp** [comment]
> Do they load with `OBJLoader`?

They do, but it lags and blocks the page for 15-20 seconds.

**Comment by mrdoob** [comment]
> I've got it working in a jsfiddle, but not in my webpack project.

What have you got working?

**Comment by jkelleyrtp** [comment]
> > I've got it working in a jsfiddle, but not in my webpack project.
> 
> What have you got working?

I've got OBJLoader2 loading the model and inserting it into the scene using unpkg's 119.1:
https://jsfiddle.net/8hcp75q3/

However, in webpack code,

```javascript
const objLoader = new OBJLoader2();
  objLoader.load(
    "https://poly.googleapis.com/downloads/fp/1598348780086706/5UU85o2PgY6/fhRJu_OZEZp/model.obj",
    f => {
      console.log("loaded fine");
    }
  );
```
Fails with 
```
oh no! loading failed TypeError: meshOutputGroup.vertices is undefined
    _finalizeRawMesh OBJLoader2Parser.js:807
    _processCompletedMesh OBJLoader2Parser.js:856
    _processLine OBJLoader2Parser.js:594
    executeLegacy OBJLoader2Parser.js:429
    parse OBJLoader2.js:348
```

**Comment by mrdoob** [comment]
I see. Better to use the [forum](https://discourse.threejs.org/) or the [chat](https://discord.gg/HF4UdyF) for this then.

**Comment by WestLangley** [comment]
Both files load for me.

**Comment by jkelleyrtp** [comment]
> Both files load for me.

In a local project, or just the JSFiddle? Is there any documentation around differences in three in a TS project rather than just in an html script? It seems that importing these modules add by not importing the whole module, the side-effects don't take place. 

I believe I am having the same issue as in

https://github.com/mrdoob/three.js/issues/18335

which took a PR to fix, and

https://github.com/mrdoob/three.js/pull/18356

and seems to be affecting other people in different forms.

In my case, importing OrbitControls/etc is fine, but ObjLoader2 and ObjLoader2 parallel both break. 

It's hard to get a minimum repro here because it's build-system based, but my project isn't doing anything particularly inane, just normal old webpack + typescript.

FWIW it works fine in create-react-app.

Here's the smallest bit of code that fails:

```javascript
import("three/examples/jsm/loaders/OBJLoader2").then(module => {
  let loader = new module.OBJLoader2();
  loader.load(
    "https://poly.googleapis.com/downloads/fp/1598348780086706/5UU85o2PgY6/fhRJu_OZEZp/model.obj",
    f => { console.log("loaded fine"); }
  );
});
```
There's really not a whole lot of knobs for me to twist here.

**Comment by mrdoob** [comment]
Please, use the [forum](https://discourse.threejs.org/) or the [chat](https://discord.gg/HF4UdyF).

**Comment by tianmiaomiao1** [comment]
I have met a problem of  OBJLoader2 like this in my webpack project. Is three any solution to adopt?

**Comment by tianmiaomiao1** [comment]
It is like this:
![image](https://user-images.githubusercontent.com/48432365/99612251-2ddadb00-2a50-11eb-895e-5a1bd2c441a8.png)
