### ISSUE TITLE
More subdivision options for icosahedron geometry

### ISSUE THREAD

**Issue by felixmariotto** [mrdoob/three.js#20198]
About the icosahedron geometry, I understand that the `detail` parameter is an option for subdividing each edge into more vertices, which are projected onto a sphere. However it seems that some possible subdivision are not allowed.

For example, this is the subdivision with `detail = 1` :  

![2020-08-27_125429](https://user-images.githubusercontent.com/46470486/91435029-fa7c1c00-e865-11ea-9741-82a3884da5c0.jpg)

And this is with `detail = 2` :

![2020-08-27_125402](https://user-images.githubusercontent.com/46470486/91435042-fea83980-e865-11ea-8c40-791abcbf8a38.jpg)

It looks like the following in-between subdivision would be possible but is not currently allowed : 

![Untitled-1](https://user-images.githubusercontent.com/46470486/91435335-75453700-e866-11ea-8847-f090f556e423.jpg)

Is there an issue with this kind of subdivision ? If not, would you be interested in a PR ?

**Comment by Mugen87** [comment]
The current algorithm uses this code to perform the subdivision of a face:
```js
const cols = Math.pow( 2, detail );
```
Meaning `cols` is POT. I don' think you can implement this feature request backwards-compatible so existing parametrization would still produce the same result.

**Comment by marcofugaro** [comment]
I use this code to generate a sphere with more fine-tuned picking of the level of detail, maybe this can be useful to you

```js
const segments = 2000
const geometry = new THREE.BufferGeometry()
const positions = new Float32Array(segments * 3)

// Uniform distribution of points on the surface of a sphere
// https://gist.github.com/AngeloYazar/6091095
let inc = Math.PI * (3 - Math.sqrt(5))
let off = 2 / segments
let radius = 1.5

for (let i = 0; i < segments; i++) {
  let y = i * off - 1 + off / 2
  let r = Math.sqrt(1 - y * y)
  let phi = i * inc

  positions[3 * i] = radius * Math.cos(phi) * r
  positions[3 * i + 1] = radius * y
  positions[3 * i + 2] = radius * Math.sin(phi) * r
}

geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3))
```

**Comment by mrdoob** [comment]
Hmm, if we changed this, the worst thing that can happen is that user's code will have less subdivisions, correct?

**Comment by Mugen87** [comment]
I'm not sure if the code in `PolyhedronGeometry` needs a POT `cols` value. If this is changed, the resulting vertex data have to be closely verified.

**Comment by mrdoob** [comment]
@felixmariotto would you like to have a look at it?

**Comment by felixmariotto** [comment]
Oops sorry for the delay.

@mrdoob yes I will do some testing

**Comment by felixmariotto** [comment]
Here is a live example showing the difference before and after the update : https://jsfiddle.net/felixmariotto/1aqorz7f/215/

![2020-09-01_235854](https://user-images.githubusercontent.com/46470486/91910571-8d2a1a00-ecaf-11ea-9770-7d0e719a3d65.jpg)

[here](https://github.com/felixmariotto/three.js/blob/460a1a501f1d05ceafbbf42dcef47714d4632cec/src/geometries/PolyhedronGeometry.js#L115) I set `cols = detail`.   
[here](https://github.com/felixmariotto/three.js/blob/460a1a501f1d05ceafbbf42dcef47714d4632cec/src/geometries/PolyhedronGeometry.js#L49-L51) I had to default `detail` to 1 and ensure that it's not 0 ( it was previously implied by `Math.pow` ).

An alternative could to set `cols = detail + 1`, and maybe rename `detail` into `division`.

At first glance it looks fine, but I can write some specific tests if you tell me what to check exactly 😊

**Comment by mrdoob** [comment]
I like it! You had to be careful with the detail parameter in the old primitive because you could easily freeze your system.

**Comment by mrdoob** [comment]
I think a PR would be great 🙏
