### ISSUE TITLE
Examples: Adding a "new" tag to examples released in the last major

### ISSUE THREAD

**Issue by gsimone** [mrdoob/three.js#20199]
Hi 👋
The three examples page is a fun place to just spend an afternoon exploring, and it's fun to see what's new. 

What would you think about adding a small tag on the new examples?

Something linke this:
![image](https://user-images.githubusercontent.com/1862172/91436041-9e19fc00-e867-11ea-81b7-d3eb9fc85ad7.png)

It would be easy to handle the special case of `#new` in the searchbar to show all new examples. 

### Maintaining it
This is of course something that would have to be changed between releases, it could be stored as an object in `files.js`:

```js
const newExamples = ['webgl2_volume_cloud', 'webgl2_volume_instancing', 'webxr_vr_haptics'];
```

They would have to be changed every major release ( or two? ).

Looking for thoughts and comments, If it feels like something interesting I'll work on the PR 👍

**Comment by Mugen87** [comment]
I like this idea 😊 .

**Comment by mrdoob** [comment]
Sounds good to me too! 👍

**Comment by gsimone** [comment]
Alright, imma get coding 👍

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/20207#issuecomment-968339757
