### ISSUE TITLE
Transform Controls Example is unresponsive to mouse input

### ISSUE THREAD

**Issue by torinmb** [mrdoob/three.js#20193]
The [Transform Controls](https://threejs.org/examples/?q=controls#misc_controls_transform) example isn't responding to any mouse input when you try to move the box around. 

This is working however on mobile Safari and mobile Chrome.
##### Three.js version / on the live site
- [ X] r120

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [X ] macOS

**Comment by Mugen87** [comment]
Same issue like https://github.com/mrdoob/three.js/issues/20191#issuecomment-680936598.

**Comment by Mugen87** [comment]
https://threejs.org/examples/webgl_geometry_spline_editor is broken for the same reason.

**Comment by mrdoob** [comment]
https://threejs.org/examples/misc_controls_transform.html and https://threejs.org/examples/webgl_geometry_spline_editor.html should now be fixed.
