### ISSUE TITLE
Suggestion: Editor can edit examples like https://mrdoob.neocities.org/

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#20192]
I am not sure this suggestion is very necessary, but it awesome.

**Comment by mrdoob** [comment]
I'm not sure I understand the suggestion.

**Comment by linbingquan** [comment]
> I'm not sure I understand the suggestion.

Add a `EDIT` button for `/examples/**.html` file.

![image](https://user-images.githubusercontent.com/23699926/91369803-436caa00-e83f-11ea-81fe-3515b5c5332f.png)

**Comment by mrdoob** [comment]
Sorry, that only works with scenes made with the editor.
