### ISSUE TITLE
Suspicious handling of a number (result of area) as a boolean

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#20200]
Is handling the number result of the `area` call as a boolean value intended in the snippet below?

https://github.com/mrdoob/three.js/blob/daf9cd232a6303e604ace07236ec98b729ad2580/src/extras/Earcut.js#L601

As I understand the code now, it checks that at least one of the triangles **a.prev, a, b.prev** and **a, b.prev, b** has non zero area. I do not understand the intent well enough, the comment says "does not create opposite-facing sectors".

This is the only place in the whole three.js code where the result of area is not compared explicitly. If the code is correct, perhaps an explicit comparion using `!== 0` would make the intent clearer?

```
area( a.prev, a, b.prev ) !== 0 || area( a, b.prev, b ) !== 0
```

**Comment by Mugen87** [comment]
Better to discuss this at the official repo of Earcut: 

https://github.com/mapbox/earcut/blob/36742a5a24497f56d89f024a7b44a0a4f8e07128/src/earcut.js#L476-L481

`three.js` just ported the code over.
