### ISSUE TITLE
Change the compile target for Type Script to ES6

### ISSUE THREAD

**Issue by ThreeDfish** [mrdoob/three.js#20203]
Since ThreeJS is moving to using ES6 exclusive features... modules...   could we please change the compile target to ES6?

There are no current browsers that don't support ES6

**Comment by donmccurdy** [comment]
I don't think I understand what you mean by changing the compile target _for TypeScript_. The three.js project is written in JavaScript, and provides TypeScript typings, but I don't think we can offer a different compile target specifically to users who are themselves using TypeScript. We have two outputs the `three` npm package: 

- **build/three.js**: CommonJS/UMD module, transpiled to ES5.
- **build/three.module.js**: ES module, as untranspiled ES6.

If you are using ES modules in your TypeScript project, it should be using the latter.
