### ISSUE TITLE
Missing CSM Implementation

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#20215]
It appears that the CSM example code is only available for module based js code? I do not see it in the examples/js directory only examples/jsm.

I would like to add this to my project but refactoring the whole thing to use modules seems like a rather daunting task.

Is there a plan to add this to the standard js folder?

**Comment by gkjohnson** [comment]
There's not -- and according to the warning in the `/js` scripts the non module example files will be removed from future releases starting in December.

If you need some of the `examples/jsm` scripts in something like a UMD or global script format I'd use [rollup.js](https://rollupjs.org/guide/en/) to convert just the files you need.

**Comment by titansoftime** [comment]
Oof... Ok, thanks man.

**Comment by mrdoob** [comment]
You can't please everyone 🤷‍♂️

**Comment by titansoftime** [comment]
All good. I now have a working test build of my app using modules. Wasn't all that bad actually once I learned it (damn three.js always making me learn stuff).

**Comment by mrdoob** [comment]
> damn three.js always making me learn stuff

that's what I tell myself every day 😁
