### ISSUE TITLE
Node Material: Logical expressions

### ISSUE THREAD

**Issue by martinRenou** [mrdoob/three.js#20212]
##### Description of the problem

cc. @sunag 

It looks to me that logical expressions are missing in the Node materials.

I would see the benefits of being able to do something like:
```javascript
material.mask = new Nodes.LogicalNode(mask1, mask2, Nodes.LogicalNode.AND);
```

I would be happy to come up with a PR when I find time, if that is something you would like to see introduced. Feel free to close the issue if this is out of scope.

**Comment by sunag** [comment]
Interesting... I think that this could be added to `CondNode` in `op` property?

https://github.com/mrdoob/three.js/blob/c6d62fa599e154bd19fdf8c47995a22871cf6300/examples/jsm/nodes/math/CondNode.js#L17-L22

**Comment by martinRenou** [comment]
How would you implement the example I shown using CondNode?

IMO that does not fit well in CondNode, as CondNode is an if condition, but my example is just a small logical expression,

**Comment by martinRenou** [comment]
Oh, I see not providing an `ifNode` will simply generate the logical expression. I will come up with a PR containing what you suggested then :)

**Comment by martinRenou** [comment]
Just for the record, the following can now be achieved:

```javascript
material.mask = new CondNode(mask1, mask2, CondNode.AND);
```
