### ISSUE TITLE
Suggestion: Add nginx server for How-to-run-things-locally.html

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#20211]

**Comment by Mugen87** [comment]
Next to Apache, NGINX is already noted in the guide. I don't think we should explain how to use both web servers. Users should be able to find existing tutorials on the web.

> Many programming languages have simple HTTP servers built in. They are not as full featured as production servers such as Apache or NGINX, however they should be sufficient for testing your three.js application.

**Comment by donmccurdy** [comment]
I agree with @Mugen87. Apache and NGINX are much harder to use than the other options on that list, and the list is already quite long. If anything I would say this page should aim for fewer, easier-to-use options.
