### ISSUE TITLE
ColorKeyframeTrack does not support color in string or color in hex

### ISSUE THREAD

**Issue by XiyuZhai97** [mrdoob/three.js#20229]
##### Description of the problem
I'm trying to use `ColorKeyframeTrack` to change the `.material.color` of an object. But found that it only supports for color in RGB format. `StringKeyframeTrack` also doesn't support color in string.

```
new THREE.ColorKeyframeTrack('.material.color', time, colors, THREE.InterpolateDiscrete)
```
This form is for three.js bug reports and feature requests only.

This is NOT a help site. Do not ask help questions here.
If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Describe the bug or feature request in detail.

Always include a code snippet, screenshots, and any relevant models or textures to help us understand your issue.

Please also include a live example if possible. You can start from these templates:

* [jsfiddle](https://jsfiddle.net/hyok6tvj/) (latest release branch)
* [jsfiddle](https://jsfiddle.net/c5m1kazu/) (dev branch)

##### Three.js version

- [x] Dev
- [ ] r120
- [x] r115

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

**Comment by Mugen87** [comment]
What is your use case for not using color values in RGB format?

**Comment by XiyuZhai97** [comment]
I got some color constants in string format. So I'd like to reuse them, instead of creating more constants...

**Comment by Mugen87** [comment]
You could convert the color values with [THREE.Color](https://threejs.org/docs/index.html#api/en/math/Color).

I don't think it makes sense to add type conversion to the animation system (or the keyframe tracks). If you author the tracks by yourself, you have to ensure valid input.
