### ISSUE TITLE
videotexture bug in IOS12.2 wechat app webview

### ISSUE THREAD

**Issue by ouzhou** [mrdoob/three.js#20238]
i test my code in pc ,mobile android/ios 

i find _VideoTexture_ is not work in wechat app webview  IOS12.2 

If I add a line it will work as other devices
just add `this.needsUpdate = true;` in this [line](https://github.com/mrdoob/three.js/blob/4944e56c06ed284abe11b7654348fb1ea3ac04d4/src/textures/VideoTexture.js#L42)

so why `this.needsUpdate = true;` run twice can fix this bug? any idea?

**Comment by Mugen87** [comment]
> so why this.needsUpdate = true; run twice can fix this bug? any idea?

Not sure but this seems like a bug in the webview implementation. Adding `needsUpdate` twice to `VideoTexture` is definitely no valid fix.

**Comment by ouzhou** [comment]
# Only not work in IOS12.2 wechat app webview 

## this code can work
![image](https://user-images.githubusercontent.com/7693866/91856705-809ac700-ec99-11ea-80f1-9f8d1f313730.png)

## this code can not work
![image](https://user-images.githubusercontent.com/7693866/91856875-b5a71980-ec99-11ea-984d-38f209d884f0.png)

my log shows this line of code `console.log('oops')`  is running

I am confused, where this code is written should be the same, but the performance does seem to be different.

**Comment by mrdoob** [comment]
I am confused too.

**Comment by ouzhou** [comment]
I figured out the reason
in IOS12.2 wechat app webview , if you dont set this.needsUpdate = true in the first time, even if it’s set later , it will not work

so i can fix it because i add `this.needsUpdate = true` before `if ( hasVideoFrameCallback === false && video.readyState >= video.HAVE_CURRENT_DATA )`

this line `if ( hasVideoFrameCallback === false && video.readyState >= video.HAVE_CURRENT_DATA )` can be false then be true , so you can see...

its also need to be fixed, i believe this is a bug

**Comment by ouzhou** [comment]
so,  in some phone , it  should always call `this.needsUpdate = true`

**Comment by mrdoob** [comment]
What phones does this affect?

**Comment by ouzhou** [comment]
Maybe you can ignore this,  there are only a few cases (only one)

**Comment by mrdoob** [comment]
I see. Maybe better to close this for now then.
