### ISSUE TITLE
Rotating camera on Y axis Make the Camera Rotate on Z axis

### ISSUE THREAD

**Issue by playbyan1453** [mrdoob/three.js#20244]
##### Description of the problem
Hi. Im new on three.js and i was use it for my own project but when I was trying rotate camera using
`
camera.rotation.y =1.0;
`
and it seems the camera rotate on Z axis not Y axis

##### Three.js version

- [ ] Dev
- [x] r120
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by WestLangley** [comment]
Beginners may find [this explanation](https://stackoverflow.com/questions/17517937/three-js-camera-tilt-up-or-down-and-keep-horizon-level/17518092#17518092) helpful.
