### ISSUE TITLE
NodeMaterial: PositionNode.PROJECTION not usable in the fragment shader

### ISSUE THREAD

**Issue by martinRenou** [mrdoob/three.js#20248]
##### Description of the problem

cc. @sunag 

The PositionNode.PROJECTION is not usable in the fragment shader, it is set to be a vec4(0.), see [this line](https://github.com/mrdoob/three.js/blob/c6d62fa599e154bd19fdf8c47995a22871cf6300/examples/jsm/nodes/accessors/PositionNode.js#L96).

I would like to suggest that we define a varying for it, so that we can use its value in the fragment shader, what do you think? We might want to do the same for PositionNode.VIEW.

I'd be happy to push a PR.

##### Three.js version

- [x] Dev
- [x] r120
- [ ] ...

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by sunag** [comment]
> I'd be happy to push a PR.

Sounds great. For curiosity, you imagine this used for some species of shader?

**Comment by martinRenou** [comment]
Yes, I'd like to store the projected position's `z` component into the alpha channel :)

**Comment by Mugen87** [comment]
Closing. The new implementation of `PositionNode` does not have a `PROJECTION` scope anymore. Valid values are:

https://github.com/mrdoob/three.js/blob/4e68936c2edef7f4984dd3b68e3420eae9e9d116/examples/jsm/nodes/accessors/PositionNode.js#L10-L14
