### ISSUE TITLE
NodeMaterial: BypassNode order of execution issue

### ISSUE THREAD

**Issue by martinRenou** [mrdoob/three.js#20249]
##### Description of the problem

cc. @sunag 

An issue (at least for me) is that the only way to call a function in the vertex shader is to attach a `BypassNode` to the `position` property, if my function call takes the `transformed` position as input it will generate the following code:

JS code:
```javascript
material.position = new Nodes.BypassNode(myFunctionNodeCall);
```

Generated code:
```glsl
vec3 transformed = position;
myFunctionNodeCall(transformed);

transformed = ...  // The actual transformation happens AFTER the function call, hence the function call does not take the expected input
```

Should I open a PR and fix the BypassNode to call the function after the `transformed` assignment?

**Comment by martinRenou** [comment]
Another way of calling arbitrary expressions would be to have new properties like:

```javascript
material.vertex_expressions = [myFunctionNodeCall1, myFunctionNodeCall2];
material.fragment_expressions = [myFunctionNodeCall3];
```

This would call the functions at the end of the vertex/fragment shader, what do you think?

**Comment by sunag** [comment]
Maybe for this case, it wouldn't be easier add the function directly without `BypassNode`?

Example: I do not test this code...
```js
var transformPosFunction = new Nodes.FunctionNode( [
	"vec3 transformPos(vec3 pos) {",
	"	return pos;", // add some variation
	"}"
].join( "\n" ) );

var transformPos = new Nodes.FunctionCallNode( transformPosFunction );
transformPos.inputs.pos = new Nodes.PositionNode();

material.position = transformPos;
```
