### ISSUE TITLE
VideoTexture m3u8 url bug in Safari IOS 13

### ISSUE THREAD

**Issue by ouzhou** [mrdoob/three.js#20247]
online demo
https://codepen.io/ouzhou-the-bashful/pen/mdPBRBQ

you can test it _only_ in **mac safari** or **ios safari**， beacause only safari can play m3u8 url in video tag directly, other bowser need extra js to decode the m3u8 video stream 

in other version, like ios12, it works well, but in ios13+(ios14) it not work

related
https://github.com/mrdoob/three.js/issues/9754

**Comment by Mugen87** [comment]
Do you mind describing in more detail the expected and actual behavior?

**Comment by ouzhou** [comment]
I can not supply more infomation,because the demo code is very simple, the screen is blank, seems the VideoTexture is not work as my expect

mac safari works well, ios13+ safari is not work, you can compare with them

**Comment by mrdoob** [comment]
Sounds like you should be reporting this to Apple/Safari instead.

**Comment by ouzhou** [comment]
@Mugen87 @mrdoob 
I test other vr player, they can play m3u8 in ios13 safari
try it in ios13 safari https://www.utovr.com/

**Comment by Mugen87** [comment]
Are you sure the website uses WebGL?

**Comment by ouzhou** [comment]
I read part of the encrypted code, this player is indeed used webgl

**Comment by mrdoob** [comment]
Let us know know what you find 👌

**Comment by arpu** [comment]
i had some trouble since https://github.com/vrlandio/three.js/commit/0cf9a5f636c8d26dd48dc28fbdd613436792bf0f

if the video is shown in webxr session ( chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=1107578&q=webxr&can=2)

**Comment by mrdoob** [comment]
@arpu Video not playing in WebXR is a known issue Chrome is working on and it's unrelated to this bug report.
