### ISSUE TITLE
Editor: Expanded menu bar options don’t minimise when you click in the 3D viewport on mobile

### ISSUE THREAD

**Issue by GamerWael** [mrdoob/three.js#20252]
##### Description of the problem

The expanded menu bar options don’t minimise when you click in the 3D viewport. They only minimise when you click somewhere in the Scene/Project/Settings tab or in an empty space in the menu bar.

##### Three.js version

- [ ] Dev
- [ ] r120
- [ ] ...
- [x] Editor

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

**Comment by Mugen87** [comment]
It seems this broke with `r120`. It worked with `r119`:

https://rawcdn.githack.com/mrdoob/three.js/r119/editor/index.html

@GamerWael Can you confirm, please?

**Comment by Mugen87** [comment]
It seems this is a side effect from having the following line in `TransformControls`:
```js
domElement.style.touchAction = 'none';
```

**Comment by GamerWael** [comment]
Can confirm it works with `r119`

**Comment by mrdoob** [comment]
Okay, I think this fixes it: https://github.com/mrdoob/three.js/commit/7f8b59f149c886fa874508c9c6e88345f337ef7b
https://raw.githack.com/mrdoob/three.js/dev/editor/

**Comment by Mugen87** [comment]
Works like a charm! 😊

**Comment by GamerWael** [comment]
Yup!

**Comment by mrdoob** [comment]
Sweet! Will push to gh-pages too.

**Comment by mrdoob** [comment]
Pushed, should be live in a few minutes.
Thanks for reporting! 🙏
