### ISSUE TITLE
memery leak in the android webview

### ISSUE THREAD

**Issue by cgq1053180073** [mrdoob/three.js#20265]
##### Description of the problem

![image](https://user-images.githubusercontent.com/24696642/92234845-52112c00-eee5-11ea-944a-c0b58b01dd37.png)

##### Three.js version

- [ ] Dev
- [x] r113
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
`
var container, stats, clock, gui, mixer, actions, activeAction, previousAction;
			var camera, scene, renderer, model, face;

			var api = { state: 'Walking' };

			init();
			animate();

			function init() {

				container = document.createElement( 'div' );
				document.body.appendChild( container );

				camera = new THREE.PerspectiveCamera( 45, window.innerWidth / window.innerHeight, 0.25, 100 );
				camera.position.set( - 5, 3, 10 );
				camera.lookAt( new THREE.Vector3( 0, 2, 0 ) );

				scene = new THREE.Scene();
				scene.background = new THREE.Color( 0xe0e0e0 );
				scene.fog = new THREE.Fog( 0xe0e0e0, 20, 100 );

				clock = new THREE.Clock();

				// lights

				var light = new THREE.HemisphereLight( 0xffffff, 0x444444 );
				light.position.set( 0, 20, 0 );
				scene.add( light );

				light = new THREE.DirectionalLight( 0xffffff );
				light.position.set( 0, 20, 10 );
				scene.add( light );

				// ground

				var mesh = new THREE.Mesh( new THREE.PlaneBufferGeometry( 2000, 2000 ), new THREE.MeshPhongMaterial( { color: 0x999999, depthWrite: false } ) );
				mesh.rotation.x = - Math.PI / 2;
				scene.add( mesh );

				var grid = new THREE.GridHelper( 200, 40, 0x000000, 0x000000 );
				grid.material.opacity = 0.2;
				grid.material.transparent = true;
				scene.add( grid );

				// model

				var loader = new THREE.GLTFLoader();
			    loader.parse(base64DecToArr(base64Data_robot).buffer,'www.baidu.com',function(gltf){
                   model = gltf.scene;
					scene.add( model );

					mixer = new THREE.AnimationMixer( model );

					actions = {};

					var animations = gltf.animations ;

					for ( var i = 0; i < animations.length; i ++ ) {

						var clip = animations[ i ];
						var action = mixer.clipAction( clip );
						actions[ clip.name ] = action;

						action.clampWhenFinished = true;
						action.loop = THREE.Loop;

					}

					activeAction = actions[ 'Walking' ];
					activeAction.play();
                });

				renderer = new THREE.WebGLRenderer( { antialias: true } );
				renderer.setPixelRatio( window.devicePixelRatio );
				renderer.setSize( window.innerWidth, window.innerHeight );
				renderer.outputEncoding = THREE.sRGBEncoding;
				container.appendChild( renderer.domElement );

				window.addEventListener( 'resize', onWindowResize, false );

				// stats
				// stats = new Stats();
				// container.appendChild( stats.dom );

			}

			function fadeToAction( name, duration ) {

				previousAction = activeAction;
				activeAction = actions[ name ];

				if ( previousAction !== activeAction ) {

					previousAction.fadeOut( duration );

				}

				activeAction
					.reset()
					.setEffectiveTimeScale( 1 )
					.setEffectiveWeight( 1 )
					.fadeIn( duration )
					.play();

			}

			function onWindowResize() {

				camera.aspect = window.innerWidth / window.innerHeight;
				camera.updateProjectionMatrix();

				renderer.setSize( window.innerWidth, window.innerHeight );

			}

			//

			function animate() {

				var dt = clock.getDelta();

				if ( mixer ) mixer.update( dt );

				requestAnimationFrame( animate );

				renderer.render( scene, camera );

				//stats.update();

			}

			function base64DecToArr(base64Data) {
                var padding = '='.repeat((4 - base64Data.length % 4) % 4);
                var base64 = (base64Data + padding)
                    .replace(/\-/g, '+')
                    .replace(/_/g, '/');

                var rawData = window.atob(base64);
                var outputArray = new Uint8Array(rawData.length);
                var i= 0;
                var l = rawData.length ;
                for (i ; i < l; i++) {
                    outputArray[i] = rawData.charCodeAt(i);
                }
                return outputArray;
            };
`

**Comment by mrdoob** [comment]
Please, use the [forum](https://discourse.threejs.org/) or the [chat](https://discord.gg/HF4UdyF) for help.
