### ISSUE TITLE
fat lines for linesegments?

### ISSUE THREAD

**Issue by d3x0r** [mrdoob/three.js#20271]
There are examples ... examples/webgl_lines_fat.html (for instance) which indicate that thick lines can work.... but they only work for a line geometry.  I have a bunch of line segments https://d3x0r.github.io/STFRPhysics/3d/indexArmProper.html  which are not lines... but just segments; can't the same thing be done for those?

I don't really want to add 150,000 objects to the scene, but rather 1 object with 150,000 point/color pairs is much more reasonable.  (depending on options a LOT of segments can be shown).

##### Three.js version

- [X] Dev
- [X] r120
- [X] r115

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by gkjohnson** [comment]
There's no example for them but both [LineSegments2](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/lines/LineSegments2.js) and [LineSegmentsGeometry](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/lines/LineSegmentsGeometry.js) in the `examples/jsm/lines` folder should do what you want.

**Comment by WestLangley** [comment]
As @gkjohnson said, what you want is already supported.
