### ISSUE TITLE
Documentation: Consider generating website docs from JSDoc in .d.ts files

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#20299]
Given prior decisions...

- Maintain `.d.ts` typings, do not convert to TypeScript. (https://github.com/mrdoob/three.js/issues/15545)
- Keep JSDoc and default values in `d.ts` files, not source code. (https://github.com/mrdoob/three.js/issues/19919)
- Support i18N in documentation.

... I think there might be an easier option to maintain documentation, typings, and support i18n. The basic workflow would be:

1. Put full documentation (not just default values) in the JSDoc in `.d.ts` files.
2. Allow translators to use [jsdoc-i18n](https://www.npmjs.com/package/jsdoc-i18n) to maintain text translations in a simple sqlite file.
3. Generate documentation — and all translations — from the sqlite file.

One advantage of this is that the documentation and typings are in the same place. I suspect it will also make things much easier for translators, but — to be clear — I don't know how robust json-i18n's workflow is. You can find some discussion of this on https://github.com/jsdoc/jsdoc/issues/1127 and https://github.com/documentationjs/documentation/issues/899.

The other effect of this, which could be a downside depending on our preferences, is that it does require a build step for generating the documentation. It's entirely possible to include headers and example code in JSDoc ([example](https://github.com/donmccurdy/glTF-Transform/blob/e0ccb0ea85976e7425c909c2ead1ffe81051d975/packages/core/src/document.ts)) but this may still limit the customization possible on individual docs pages.

**Comment by Mugen87** [comment]
TBH, I don't like the idea of coupling TS declaration files with the documentation. If for some reasons the TS files are moved out of the repo (maybe for pure organizational reasons), the documentation would be gone, too.

**Comment by donmccurdy** [comment]
We'd still have the generated HTML output, which (in theory) would be identical to the HTML files we're maintaining by hand today. Coupling JSDoc to generated documentation is also common. But, yes, it's a fair concern if you'd rather not combine these things!

**Comment by Mugen87** [comment]
I'm afraid my view on this topic is biased since I'm not a TS fan^^.

**Comment by mrdoob** [comment]
What made you think of suggesting this change?

**Comment by donmccurdy** [comment]
I've assumed in the past that we were willing to pay the cost maintaining HTML files for all documentation pages, because we disliked having JSDoc in source code. If we were already maintaining JSDoc, there wouldn't be much point in also maintaining HTML documentation by hand.

But based on https://github.com/mrdoob/three.js/issues/19919, we _are_ committing to maintain documentation, in English, in two duplicate places (JSDoc in `.d.ts` files, and HTML). And I worry that the cost of keeping docs up to date is going to increase as we support more languages, too.

In a project where you're already maintaining JSDoc it would be rare to also maintain another copy of docs elsewhere, when you can use one of many JSDoc->HTML tools to generate them. I guess I'm not sure why we want to maintain English docs in two places, or have I misunderstood? Does https://github.com/mrdoob/three.js/issues/19919 mean that the JSDoc in `d.ts` files should have default values but no English descriptions of methods?

**Comment by mrdoob** [comment]
> And I worry that the cost of keeping docs up to date is going to increase as we support more languages, too.

I've been thinking about this. In the past we have updated the Chinese docs ourselves.

Now that we have Arabic and Korean, it's clear to me that we should stop doing that and let the maintainers of the localized docs keep these up to date themselves.

> Does #19919 mean that the JSDoc in `d.ts` files should have default values but no English descriptions of methods?

Yes. That was my understanding.

**Comment by donmccurdy** [comment]
I see, thanks. If JSDoc (or Documentation.js, or similar projects) ever make a really well-supported documentation+i18n workflow we may want to consider it — i don't think mixing docs and typings would be inherently bad. But it's not clear that the tools work well enough today to justify switching, especially if we have misgivings about it. I'll close this suggestion!
