### ISSUE TITLE
OrbitControls: disable in mousedown, no events triggered in mousemove

### ISSUE THREAD

**Issue by joshua-gould** [mrdoob/three.js#20294]
In r120, disabling orbit controls on mousedown no longer triggers mousemove events when dragging. To reproduce add the following code to misc_controls_orbit.html. This worked in the last several releases. Thanks.

```
renderer.domElement.addEventListener('mousemove', ()=>{
   console.log('mousemove');
});
renderer.domElement.addEventListener('mousedown', (e)=>{
   controls.enabled = false;
});
renderer.domElement.addEventListener('mouseup', ()=>{
   controls.enabled = true;
});		
```

**Comment by Mugen87** [comment]
`OrbitControls` was moved to the Pointer Events API. Please try to register your event listener on the respective counterparts (e.g.`pointerdown`, `pointermove` etc.).

**Comment by joshua-gould** [comment]
Everything works as expected when I changed to the Pointer Events API. Thanks.
