### ISSUE TITLE
NodeMaterial: Using usampler2D with node materials

### ISSUE THREAD

**Issue by AlexDaniel** [mrdoob/three.js#20297]
It seems like there's no way to use usampler2D uniforms in node materials (note the `u`). With standard materials, one can just create a `THREE.DataTexture` and pass it as a uniform (e.g. `THREE.RedIntegerFormat`, `THREE.UnsignedByteType`, and `.internalFormat = "R8UI"`). It's not clear how to do something like this with nodes. My initial guess was that creating a `Nodes.TextureNode` with a given DataTexture will work, but it generates glsl code for a uniform like this:

```
uniform sampler2D nodeU1;
```

It seems like it can only create sampler2D's.

Maybe there needs to be a `Nodes.DataNode` or something like that?

**Comment by AlexDaniel** [comment]
Interestingly, it is possible to do some monkey patching on Nodes too:

```js
const material = new Nodes.PhongNodeMaterial();
const oldBeforeCompile = material.onBeforeCompile;
material.onBeforeCompile = function (shader, renderer) {
    oldBeforeCompile.call(this, shader, renderer)
    this.fragmentShader = this.fragmentShader.replace("uniform sampler2D nodeU1;",
                                                      "uniform usampler2D nodeU1;");
    shader.fragmentShader = this.fragmentShader;
    // do more tweaks if you need
}
```

However, even after getting all of the code right, I am getting this error:
```
GL ERROR :GL_INVALID_OPERATION : glDrawArrays: Texture bound to texture unit 0 with internal format GL_RGBA is not compatible with sampler type GL_UNSIGNED_INT_SAMPLER_2D
```

So it seems like the texture is uploaded with the wrong format, or something like that. For regular materials this works:

```js
const data = new Uint8Array(1000 * 1000);
data.fill(5.0);
myDataTexture = new THREE.DataTexture(data, 1000, 1000, THREE.RedIntegerFormat, THREE.UnsignedByteType);
myDataTexture.internalFormat = "R8UI";
```

Something is different when you're working with node materials.

**Comment by LeviPesin** [comment]
`isampler2D` also should be added.

**Comment by mrdoob** [comment]
@sunag This is for the old system, right?

**Comment by sunag** [comment]
Yes, but we don't have this features in new system.
I think it's better to leave it open for now?

**Comment by LeviPesin** [comment]
In the new system there is a function `texture(someTexture, someVec2, someBias)`, which has the same issue.

**Comment by AlexDaniel** [comment]
Hey! I just had to rewrite my code using the new node system, and it's much easier now. Basically, now I can do this:
```js
const voxelsDataUniform = new UniformNode(voxelsDataTexture, 'usampler2D');
```
And the usampler2D uniform is available in the fragment shader, just as expected. Then I'm able to pass it around into function call nodes and so on.

The only remaining trouble for me now is that the precisions for usampler2D and isampler2D are not specified. So, right now, I'm forced to do this:

```js
material.onBeforeCompile = function patchShader(shader, renderer) {
    shader.fragmentShader = `
    precision highp usampler2D;
    precision highp isampler2D;
    precision highp sampler2D;
    ${shader.fragmentShader}
    `;
  };
```

If there was a better way to achieve that without plugging into onBeforeCompile, then I'd consider this ticket resolved.

**Comment by LeviPesin** [comment]
Maybe it's something that should be patched on the core level, similar how to `precision ${ largestAvailablePrecision } float` is already done there...

**Comment by sunag** [comment]
> Maybe it's something that should be patched on the core level, similar how to precision ${ largestAvailablePrecision } float

This can affect performance and memory usage in core level, I think better add an API like:

```js
const myDataUniform = new UniformNode(myDataTexture, 'usampler2D');

myDataUniform.setPresicion( 'high' );
```

**Comment by sunag** [comment]
@AlexDaniel Can you confirm if [this PR](https://github.com/mrdoob/three.js/pull/25561) fix this issue?

**Comment by LeviPesin** [comment]
Should we close this issue now?
