### ISSUE TITLE
Disabling a light forces rebuild of all programs

### ISSUE THREAD

**Issue by Sairony** [mrdoob/three.js#20304]
We have a night / day setup for lights in our scene & have a button to switch between them. The problem is that when you change visibility of lights via `light.visible` the number of lights doesn't match up anymore. This would seem to causes a `program.code` mismatch for all programs present in the scene since the number of lights seems to be a part of the hash, which leads to recompiling all those programs. On my rather high end machine that seems to take about 100ms per program, which in turn means that it takes about 1.5 second to switch ( sometimes way longer due to system load I presume ), which gives a rather bad user experience. So essentially I'm bringing up the question of whether this could be changed. I realize it might be a trade off for having the number of lights as a uniform instead since it would lead to worse optimization. In our setup there's just 2 distinct setups which are identical between the switches, so one solution in these circumstances would be to not release the old programs & simply switch between them as well. So a setting on the renderer would help for our use case as well.

Three.js version is 0.109.0, but the code seem to be the same on dev as well.

**Comment by Mugen87** [comment]
Have you considered to just modulate the intensity of your lights?

**Comment by Mugen87** [comment]
I could image that #20135 also will help you since with this change there is no need anymore to always recompile programs.

**Comment by mrdoob** [comment]
Until then, setting `light.intensity = 0` should do the trick 👌
