### ISSUE TITLE
 Videotexture issue hevc with alpha in Safari

### ISSUE THREAD

**Issue by player11en** [mrdoob/three.js#20309]
hevc with alpha wont play as video Texture or jumping back to first frame not sure.

other videos, working fine and hevc without alpha also plays normally.
( <video> html Tag works fine with alpha )

##### Three.js version

- [ ] Iphone 11, 7   Ipad pro iOS 13.5
- [ ] perhaps related https://github.com/mrdoob/three.js/issues/15732
- [ ] ...

##### Browser
-[x] Safari

##### OS

- [x ] macOS
- [ x] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

Iphone or Ipad

**Comment by Mugen87** [comment]
I don't think this is `three.js` related issue. Have you considered to report this issue to Apple instead?

**Comment by player11en** [comment]
thank, where do i send ios related issues ?

**Comment by Mugen87** [comment]
Webkit related issues: https://bugs.webkit.org/
Safari-only issues: https://www.apple.com/feedback/safari.html

**Comment by player11en** [comment]
thank you will try it there
