### ISSUE TITLE
MarchingCubes/Metaballs shadows?

### ISSUE THREAD

**Issue by phaseIV** [mrdoob/three.js#20303]
I'm having some difficulties to make marchingcubes/metaballs cast shadows on a ground plane.
Are shadows supported/calculated for the marchingcubes effect?

**Comment by Mugen87** [comment]
Objects of type `ImmediateRenderObject` (which is the base class of `MarchingCubes`) do not support shadows.

**Comment by phaseIV** [comment]
I figured it would be something like that. Thank you very much for the explanation.
