### ISSUE TITLE
DragControls, mouse-click-events not working properly r120

### ISSUE THREAD

**Issue by obrhaberer** [mrdoob/three.js#20310]
I've noticed you switched to pointer-events in some modules. DragControls in r120 does not work properly for some reason in r120. No click-events are fired on renderer.domElement.

##### Three.js version

- [ ] Dev
- [x] r120
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by Mugen87** [comment]
`DragControls` does not use Pointer Events yet. Are you using the controls in combination with another one?

**Comment by obrhaberer** [comment]
I'm using DragControls and OrbitControls inside a project for 2 years now and recognized this "bug" after the update to r120. When I switch to r119 everything works fine.

**Comment by Mugen87** [comment]
Do you mind demonstrating the issue with a live example? In this one, the intergration of both controls seems to work. And the `click` event is triggered:

https://jsfiddle.net/7jk50Lxm/

**Comment by obrhaberer** [comment]
just add for example
renderer.domElement.addEventListener('onmousedown', () => console.log('down')) 

https://jsfiddle.net/uLfcwt7a/

**Comment by Mugen87** [comment]
`OrbitControls` calls `preventDefault()` on pointer down and move events. This automatically cancels the respective mouse events. You can only fix this by using `pointerdown`.

https://jsfiddle.net/zwt2rfvm/

**Comment by obrhaberer** [comment]
sure I can fix after initialization, but the DragControls module internally uses the mouse-events. maybe something to fix in the nearer future.

**Comment by Mugen87** [comment]
Definitely. Although you should always disable `OrbitControls` when `DragControls` become active. In this case, `OrbitControls` will not cancel its pointer events and thus `DragControls` should not be affected.

**Comment by obrhaberer** [comment]
To use the hover-event as helper to enable/disable the OrbitControls does the trick. Thanks a lot.
