### ISSUE TITLE
Outline pass exhibits strange behavior when used with both skinned meshes and non skinned meshes

### ISSUE THREAD

**Issue by viperphase1** [mrdoob/three.js#20318]
I'm using an outline pass to highlight objects.
Here is the code for the outline pass:
```
    const outlinePass = new THREE.OutlinePass(
      new THREE.Vector2( this.rendererContainer.offsetWidth, this.rendererContainer.offsetHeight ),
      this.viewer.modelScene,
      this.viewer.camera
    );
    outlinePass.visibleEdgeColor.set(color);
    outlinePass.hiddenEdgeColor.set(color);
    outlinePass.overlayMaterial.blending = THREE.NormalBlending;
    outlinePass.depthMaterial.skinning = true;
    outlinePass.prepareMaskMaterial.skinning = true;
```
If I start with a model with skinned meshes and then replace it with a model without skinned meshes I get a whole bunch of dots.

Outline pass on first model
![Screenshot from 2020-09-10 20-39-29](https://user-images.githubusercontent.com/18685519/92847353-51c1d680-f3a6-11ea-8ef9-fdcbb3fcee07.png)

Outline pass on second model
![Screenshot from 2020-09-10 20-40-51](https://user-images.githubusercontent.com/18685519/92847375-56868a80-f3a6-11ea-8c4a-50b4b52402f5.png)

There is also an issue when applying the outline pass to a model that contains both skinned meshes and non skinned meshes. I combined the two into one model and loaded it into a fresh three js environment.
As you can see the outline pass is no longer accurate for the first model (the one with skinned meshes)
![Screenshot from 2020-09-10 20-42-42](https://user-images.githubusercontent.com/18685519/92847566-85046580-f3a6-11ea-9210-fd5d949b0ced.png)

**Comment by Mugen87** [comment]
AFAICS, `OutlinePass` can't handle both types of objects (skinned vs. non-skinned mesh) in the same pass. #18427 added support for only outlining a skinned or morphed mesh. But is does not work with a mixed setup (since the internal depth and mask materials can't be shared in this context).
