### ISSUE TITLE
Issue with orthographic camera

### ISSUE THREAD

**Issue by ua4192** [mrdoob/three.js#20314]
Hi

I have realized that in versions previous to R108 orthograpich camera behaved properly. When you set camera.near to a positive value (0.001), you could orbit to an specific object without being ocluded by objects previous from camera position to object geometry.

But since this version camera.near is behaving as it was set to -Infinity, I mean when you orbit to an specific object you are ocluded by objects that are previous from the camera position to object geometry.

This is very annoying because you cannot orbit to objects that are incide of other objects.

Could you please check this behavior?

Many thanks in advanced.

Here the piece of code to demonstrate the issue:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>three.js webgl - orbit controls</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
        <link type="text/css" rel="stylesheet" href="main.css">
        <style>
            body {
                background-color: #ccc;
                color: #000;
            }

            a {
                color: #f00;
            }
        </style>
    </head>

    <body>
        <div id="info">
            <a href="https://threejs.org" target="_blank" rel="noopener">three.js</a> - orbit controls
        </div>

        <script type="module">

            import * as THREE from '../build/three.module.js';

            import { OrbitControls } from './jsm/controls/OrbitControls.js';

            var camera, controls, scene, renderer;

            init();
            //render(); // remove when using next line for animation loop (requestAnimationFrame)
            animate();

            function init() {

                scene = new THREE.Scene();
                scene.background = new THREE.Color( 0xcccccc );
                scene.fog = new THREE.FogExp2( 0xcccccc, 0.002 );

                renderer = new THREE.WebGLRenderer( { antialias: true } );
                renderer.setPixelRatio( window.devicePixelRatio );
                renderer.setSize( window.innerWidth, window.innerHeight );
                document.body.appendChild( renderer.domElement );

                camera = new THREE.PerspectiveCamera( 60, window.innerWidth / window.innerHeight, 1, 1000 );
                camera.position.set( 400, 200, 0 );

                // controls

                controls = new OrbitControls( camera, renderer.domElement );

                //controls.addEventListener( 'change', render ); // call this only in static scenes (i.e., if there is no animation loop)

                controls.enableDamping = true; // an animation loop is required when either damping or auto-rotation are enabled
                controls.dampingFactor = 0.05;

                controls.screenSpacePanning = false;

                controls.minDistance = 100;
                controls.maxDistance = 500;

                controls.maxPolarAngle = Math.PI / 2;

                // world

                var geometry = new THREE.CylinderBufferGeometry( 0, 10, 30, 4, 1 );
                var material = new THREE.MeshPhongMaterial( { color: 0xffffff, flatShading: true } );

                for ( var i = 0; i < 500; i ++ ) {

                    var mesh = new THREE.Mesh( geometry, material );
                    mesh.position.x = Math.random() * 1600 - 800;
                    mesh.position.y = 0;
                    mesh.position.z = Math.random() * 1600 - 800;
                    mesh.updateMatrix();
                    mesh.matrixAutoUpdate = false;
                    scene.add( mesh );

                }

                // lights

                var light = new THREE.DirectionalLight( 0xffffff );
                light.position.set( 1, 1, 1 );
                scene.add( light );

                var light = new THREE.DirectionalLight( 0x002288 );
                light.position.set( - 1, - 1, - 1 );
                scene.add( light );

                var light = new THREE.AmbientLight( 0x222222 );
                scene.add( light );

                //

                window.addEventListener( 'resize', onWindowResize, false );

            }

            function onWindowResize() {

                camera.aspect = window.innerWidth / window.innerHeight;
                camera.updateProjectionMatrix();

                renderer.setSize( window.innerWidth, window.innerHeight );

            }

            function animate() {

                requestAnimationFrame( animate );

                controls.update(); // only required if controls.enableDamping = true, or if controls.autoRotate = true

                render();

            }

            function render() {

                renderer.render( scene, camera );

            }

        </script>

    </body>
</html>
```

You can test it against the version 108 and to the current one.

The feeling of the user is that he cannot go through an specific object if there is any object in the path from object to camara position extending to Infinity.

Here some attachments:

![image](https://user-images.githubusercontent.com/29919345/92725554-9a5c9e00-f36c-11ea-8483-84c7854b16ba.png)
![image](https://user-images.githubusercontent.com/29919345/92725570-a0527f00-f36c-11ea-83fa-d5d3e6b9bbed.png)

**Comment by Mugen87** [comment]
r120: https://jsfiddle.net/Lofxnb2y/
r108: https://jsfiddle.net/Lofxnb2y/1/

I've copied your code snippet into these live example but I'm afraid I don't see any differences. Do you mind updating the examples?

BTW: I think it's confusing that you talk about orthographic cameras but share code with perspective ones. 🤔

**Comment by ua4192** [comment]
Hi

Sorry.

Just change the line:
camera = new THREE.PerspectiveCamera( 60, window.innerWidth / window.innerHeight, 1, 1000 );
by 
camera = new THREE.OrthographicCamera( window.innerWidth / - 2, window.innerWidth / 2, window.innerHeight / 2, window.innerHeight / - 2, - 500, 1000 );

Now try to go through any geometry, you will se than you are not able to.

![image](https://user-images.githubusercontent.com/29919345/92733247-c2053380-f377-11ea-8420-f3600a6fe2ce.png)
![image](https://user-images.githubusercontent.com/29919345/92733272-c7fb1480-f377-11ea-8f80-5c82accc6c86.png)

It seem as the camera.near frustum plane was set as -Infinity


Best regards

**Comment by Mugen87** [comment]
r120: https://jsfiddle.net/ur6ge5yd/
r108: https://jsfiddle.net/c5wm7ske/

Sorry, but it seems both fiddles behave the same. I see no difference.

**Comment by Mugen87** [comment]
Keep in mind that when using `OrbitControls` with an orthographic camera, the zoom is no dolly. Meaning the camera does not move along the view direction. Instead the `zoom` property of the camera is modulated which only affects the projection matrix. But not the transformation of the camera in 3D space.

**Comment by ua4192** [comment]
Many thanks.

Now I understand.

And I guess it is not possible to achieve a dolly action when zooming from an orthographic camera using OrbitControls, isn't it?

Best regards and many thanks for your support.

**Comment by WestLangley** [comment]
@ua4192 See [this SO post](https://stackoverflow.com/questions/17558085/three-js-orthographic-camera/17567292#17567292) so you understand how to instantiate an orthographic camera correctly.

**Comment by Mugen87** [comment]
> And I guess it is not possible to achieve a dolly action when zooming from an orthographic camera using OrbitControls, isn't it?

Not sure how this should work.

**Comment by mrdoob** [comment]
@ua4192 You can achieve that by using `PerspectiveCamera` with a `fov` of `5` or so.

**Comment by ua4192** [comment]
Hi.

Finally I decided to try to implement the same behaviour than for perspective camera, I mean that zoom in and zoom out will update camera position when orthographic camera is used:

Here my changes in OrbitControls.js library , it seems to work quite well:

      ```
function dollyIn( dollyScale ) { 
		if ( scope.object.isPerspectiveCamera ) {
			scale /= dollyScale;
		} else if ( scope.object.isOrthographicCamera ) {
			scale /= dollyScale;
			var distance = scope.target.distanceTo(scope.object.position);
			var normalizedVector = scope.object.position.clone().sub(scope.target).normalize();
			var deltaVector = normalizedVector.clone().multiplyScalar(distance * scale);
			var newPosition = scope.target.clone().add(deltaVector);
			scope.object.position.copy(newPosition)
			scope.object.position.set(newPosition.x, newPosition.y, newPosition.z);	
			var v3_camera = newPosition;
			var line_of_sight = new THREE.Vector3();
			scope.object.getWorldDirection( line_of_sight );
			var v3_distance = scope.target.clone().sub( v3_camera );
			var depth = v3_distance.dot( line_of_sight );
			var height_ortho = depth * 2 * Math.atan( 30 *(Math.PI/180) / 2 )
			var width_ortho  = height_ortho * pCamera.aspect;
			scope.object.left = width_ortho  / -2;
			scope.object.right = -width_ortho  / -2;
			scope.object.top = height_ortho /  2
			scope.object.bottom = height_ortho  / -2;
			scope.object.updateProjectionMatrix()
		} else {
			console.warn( 'WARNING: OrbitControls.js encountered an unknown camera type - dolly/zoom disabled.' );
			scope.enableZoom = false;
		}
	}

	function dollyOut( dollyScale ) {
		if ( scope.object.isPerspectiveCamera ) {
			scale *= dollyScale;
		} else if ( scope.object.isOrthographicCamera ) {
			scale *= dollyScale;
			var distance = scope.target.distanceTo(scope.object.position);
			var normalizedVector = scope.object.position.clone().sub(scope.target).normalize();
			var deltaVector = normalizedVector.clone().multiplyScalar(distance * scale);
			var newPosition = scope.target.clone().add(deltaVector);
			scope.object.position.copy(newPosition)
			scope.object.position.set(newPosition.x, newPosition.y, newPosition.z);	
			var v3_camera = newPosition;
			var line_of_sight = new THREE.Vector3();
			scope.object.getWorldDirection( line_of_sight );
			var v3_distance = scope.target.clone().sub( v3_camera );
			var depth = v3_distance.dot( line_of_sight );
			var height_ortho = depth * 2 * Math.atan( 30 *(Math.PI/180) / 2 )
			var width_ortho  = height_ortho * pCamera.aspect;
			scope.object.left = width_ortho  / -2;
			scope.object.right = -width_ortho  / -2;
			scope.object.top = height_ortho /  2
			scope.object.bottom = height_ortho  / -2;
			scope.object.updateProjectionMatrix()
		} else {
			console.warn( 'WARNING: OrbitControls.js encountered an unknown camera type - dolly/zoom disabled.' );
			scope.enableZoom = false;
		}
	}
```


Best regards

**Comment by dberardo-com** [comment]
i need to reproduce this example using an orthographic camera: https://[codesandbox.io/p/sandbox/6oei7](https://codesandbox.io/p/sandbox/6oei7)

in particular i need to lazy load the markers as soon as they come close enough to the camera, but because the orthographic camera is only zooming, i would to calculate the distance from the focal point and not the position ... how to achieve this ?

---

UPDATE:

seems like calculating the distance from the camera position and then multiplying it by 1 / camera.zoom results in a similar result as in  using perspectivecamera ... hopefully this is also correct
