### ISSUE TITLE
Three.js rendering geometries weirdly when tab is not focused

### ISSUE THREAD

**Issue by bianyunzhi95** [mrdoob/three.js#20315]
![Screen Shot 2020-09-10 at 9 24 32 PM](https://user-images.githubusercontent.com/42105279/92735809-4b365d80-f3ac-11ea-93cf-7603c8b9731e.png)

URGENT: 
this is three.js example of 5000 box meshes.
i am running this on latest version of google chrome on Mac but it occurred on previous versions on PCs too. it starts blinking when you moved focus to other window.

any advice why this is happening?

**Comment by bianyunzhi95** [comment]
this happens well especially when I have several tabs with threejs scene open.
I attached mp4 recording file zipped.
[blink.mp4.zip](https://github.com/mrdoob/three.js/files/5202011/blink.mp4.zip)

**Comment by Mugen87** [comment]
I'm not able to reproduce with latest Chrome on macOS. This could be an issue of your GPU/driver. 

What GPU are you using on your Mac system? Is it on the latest OS version?

**Comment by bianyunzhi95** [comment]
Macbook Air (Retina, 13-inch, 2019)
Graphics: Intel UHD Graphics 617 1536MB
I think Chrome exclusive.

**Comment by Mugen87** [comment]
> Is there any similar issue reported so far? 

Not that I am aware of. 

Um, maybe it's also a browser related issue. Can you make a test with Chrome Canary? Besides, are you on the latest macOS version?

**Comment by bianyunzhi95** [comment]
macOS version is 10.15.6. I don't think these versions matter as i have realized and have been experiencing this for over 3 months on various computers on various chrome, macOS, three.js versions.
I will try with Chrome Canary.

**Comment by Mugen87** [comment]
Okay. I've just asked since system updates in mac also upgrade the GPU driver (which could be a potential root cause).

**Comment by bianyunzhi95** [comment]
Same issue happens on macOS Mojave 10.14.6.

I think it's Google Chrome or Three.js version upgrade. Mostly Google Chrome. Firefox and Safari didn't have this issue. Any possible fixes on three.js side?

**Comment by Mugen87** [comment]
> Any possible fixes on three.js side?

I don't this is fixable on JS level. I suggest you report this as an issue at the Chromium bug tracker:

https://bugs.chromium.org/p/chromium/issues/list

**Comment by bianyunzhi95** [comment]
I remember i didn't notice this issue when i was using three.js r103. was there any big change in rendering since then?

**Comment by bianyunzhi95** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1126933
issue reported on chromium.

**Comment by Mugen87** [comment]
> I remember i didn't notice this issue when i was using three.js r103. was there any big change in rendering since then?

A lot of things happens in 17 releases but I can only think of the default usage of WebGL2. Do you see the same glitch when using [WebGL1Renderer](https://threejs.org/docs/index.html#api/en/renderers/WebGL1Renderer)?

**Comment by bianyunzhi95** [comment]
Yeah, that's it. I changed renderer to WebGL1Renderer and it disappeared!!!
Thank you.

**Comment by Mugen87** [comment]
Would be good to know for the Chromium team that this is a WebGL 2 issue.
