### ISSUE TITLE
WebGLRenderTarget.copy Bug: Copying from render target results in targets sharing .texture.image

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#20328]
Here's a snippet to reproduce the issue:

```js
const x = new THREE.WebGLRenderTarget();
const y = new THREE.WebGLRenderTarget();

console.log( x.texture.image === y.texture.image ); // false

x.copy( y );

console.log( x.texture.image === y.texture.image ); // true
```

What this means is that when `x.setSize` is called the object at `y.texture.image` is inadvertently modified but and is now out of sync with the true dimensions of render target `y`.

[This line](https://github.com/mrdoob/three.js/blob/dev/src/textures/Texture.js#L94) is the problem in `Texture.copy`:

```js
this.image = source.image;
```

I assume this was originally intended to handle moving over an `<img>` tag without duplicating it -- ~maybe it makes sense to duplicate the image tag? Or maybe it should clone the object in some cases:~

```js
this.image = source.image instanceof Image ? source.image : { ...source.image };
```

~I imagine copy would behave a bit confusingly for `DataTexture`, as well.~

_Edit: I see now that retaining the image data reference is important for dealing with cloning textures before they've been fully loaded and is valuable for minimizing data duplication._

**Comment by Mugen87** [comment]
`WebGLRenderTarget.copy()` and `WebGLRenderTarget.clone()` is tricky mainly because of #19598. I wonder if it's not better to remove `copy()` and `clone()` from `WebGLRenderTarget`.

**Comment by gkjohnson** [comment]
I mean I think it's a useful feature -- [the docs specify](https://threejs.org/docs/#api/en/renderers/WebGLRenderTarget.copy) that only the settings of the render target are copied, which is all I'm expecting:

> Adopts the settings of the given render target.

**Comment by gkjohnson** [comment]
And this is an issue with DataTexture, as well:

```js
x = new THREE.DataTexture( [ 1, 2, 3 ], 3, 1 );
y = new THREE.DataTexture( [], 0, 0 );

console.log( x.image === y.image ); // false

y.copy( x );

console.log( x.image === y.image ); // true
```

**Comment by Mugen87** [comment]
> I mean I think it's a useful feature -- the docs specify that only the settings of the render target are copied, which is all I'm expecting:

Maybe. But nevertheless the methods are problematic. As soon as a render target was processed by `WebGLRenderer`, they do not produce the result users might expect. Meaning a deep copy of the custom frame/renderbuffers. I have the feeling it's a more consistent if such a "half-working" API does not exist.

**Comment by gkjohnson** [comment]
Maybe it's because I'm more familiar with graphics but I've never expected copy to copy the contents but clearly there's been some confusion before. Perhaps it's better in the render target case to change the copy function name to something more specific like `copySettings` or `copyParameters`:

```js
x.copyParameters( y );
```

**Comment by Mugen87** [comment]
Good catch. Let me fix this with a PR.
