### ISSUE TITLE
 I encountered an animation error

### ISSUE THREAD

**Issue by cgusercom** [mrdoob/three.js#20323]
# I encountered an animation error

This is the case, I exported a gltf model with animation through the 3dmax export plugin provided by babylon.js. It plays normally in the 3d viewer that comes with windows, and it plays normally in the online gltf viewer provided by babylon.js, but when I use three.js, it plays incorrectly. Looks like a matrix transformation error. I really try to fix it. I don’t know if any friends have encountered similar problems. . .

## In the three.js

![304a47830036cec5157908b893ad7a0](https://user-images.githubusercontent.com/45628282/92949210-49909680-f48d-11ea-99b1-a8064de7bc5a.png)

## In the windows 3D viewer

![5fd0b72089e585132194626dda89bfb](https://user-images.githubusercontent.com/45628282/92949174-38478a00-f48d-11ea-9768-1c3e3ca05029.png)

## In the babylon.js sandbox 

![7d57625e88fadfe90ba0955d6d8a545](https://user-images.githubusercontent.com/45628282/92949342-852b6080-f48d-11ea-9f11-f907cb7a0f72.png)

**Comment by cgusercom** [comment]
Oh, I just forgot to say, only when the animation starts, the models will be arranged incorrectly

**Comment by donmccurdy** [comment]
Would you be able to share the model? GitHub comments allow you to attach .zip files. Thanks!

**Comment by takahirox** [comment]
Yes we need the model to investigate, but I guess it could be from duplicated names issue... We should resolve that.

**Comment by cgusercom** [comment]
> Would you be able to share the model? GitHub comments allow you to attach .zip files. Thanks!

Ok, but because the glb file is too large, I will upload a model compressed with draco later

**Comment by cgusercom** [comment]
> Yes we need the model to investigate, but I guess it could be from duplicated names issue... We should resolve that.

I thought of this possibility at first, but after checking it, I found that no nodes with duplicate names exist.

**Comment by cgusercom** [comment]
[model.zip](https://github.com/mrdoob/three.js/files/5211058/model.zip)

**Comment by donmccurdy** [comment]
It looks like there are some duplicate names: 827 of 987 objects parsed into the three.js scene graph have unique names. A lot of the node names contain `????` in the exported model, so perhaps they were unique in BabylonJS but converted to ASCII characters and no longer unique in the exported model? glTF does allow UTF-8 names, so that might be a bug in the exporter. But, we should also support duplicate names here.

**Comment by cgusercom** [comment]
> > Yes we need the model to investigate, but I guess it could be from duplicated names issue... We should resolve that.
> 
> I thought of this possibility at first, but after checking it, I found that no nodes with duplicate names exist.

Oh, maybe my eyes are not so good, so I didn't find the node with the same name. I just renamed all the nodes in 3dmax, and after exporting it, it works normally in three.js. But I think it is necessary to resolve this issue. . .

**Comment by cgusercom** [comment]
> It looks like there are some duplicate names: 827 of 987 objects parsed into the three.js scene graph have unique names. A lot of the node names contain `????` in the exported model, so perhaps they were unique in BabylonJS but converted to ASCII characters and no longer unique in the exported model? glTF does allow UTF-8 names, so that might be a bug in the exporter. But, we should also support duplicate names here.



> It looks like there are some duplicate names: 827 of 987 objects parsed into the three.js scene graph have unique names. A lot of the node names contain `????` in the exported model, so perhaps they were unique in BabylonJS but converted to ASCII characters and no longer unique in the exported model? glTF does allow UTF-8 names, so that might be a bug in the exporter. But, we should also support duplicate names here.

Yes, you are right. My initial guess was that the name was repeated. I took a cursory look and didn't find the repeated name. In addition, I thought about it carefully. Three.js shouldn't be so cute to do this kind of thing. . . It turns out that I was wrong

**Comment by donmccurdy** [comment]
Ok, thanks! In that case https://github.com/mrdoob/three.js/pull/16639#issuecomment-691256401 should fix this issue as well.

**Comment by cgusercom** [comment]
I am about to close this issue, it has been resolved. All that is left is to adjust in future versions

**Comment by cgusercom** [comment]
> Ok, thanks! In that case #16639 should fix this issue as well.

I should thank you. It is true that after exporting, all the characters are converted to ???, which results in a node with the same name. . .

**Comment by donmccurdy** [comment]
The names definitely had a lot of "????" characters in them... but I don't know for sure whether that was the reason for the duplicate names, or if they would have had duplicate names anyway.

**Comment by cgusercom** [comment]
The duplicate node name in the model file (after export) is the cause of the animation error.
