### ISSUE TITLE
WebGLBakground.setClearColor: Do not set alpha to 1 by default

### ISSUE THREAD

**Issue by inear** [mrdoob/three.js#20320]
I had a problem with making a transparent render target correctly. Called setClearAlpha(0) and setClearColor(0x000000) on the active rendertarget, but alpha was then returned to 1 because of the method below (in WebGLBackground). Could it be a better idea to use the value that setClearAlpha saved instead of 1? It might break code where users used a wrong setClearAlpha and the overwrote it with setClearColor by mistake (but with the wanted visual result), making some render targets transparent again when updating three.js.  

```js
setClearColor: function ( color, alpha ) {

	clearColor.set( color );
	clearAlpha = alpha !== undefined ? alpha : 1;
	setClear( clearColor, clearAlpha );

}
``` 

https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLBackground.js#L210

##### Three.js version

- [x ] Dev
- [x] r120
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by mrdoob** [comment]
You mean doing this, right?

```js
setClearColor: function ( color, alpha ) {

	clearColor.set( color );
	if ( alpha !== undefined ) clearAlpha = alpha;
	setClear( clearColor, clearAlpha );

}
```

**Comment by WestLangley** [comment]
I understand the concern, but since `clearAlpha` defaults to zero, I think it is best to retain the current behavior.
```js
renderer.setClearColor( 0xff0000 );
```

**Comment by inear** [comment]
Ok, I see. The majority does not care about the transparency, and when setting just the color the background would be gone if it would not overwrite clearAlpha with 1 in setClearColor. 

This problem is more about using render targets for something else because we have to switch state before the render (Which EffectComposer/RenderPass handles nicely). I just wish the color and alpha was a property of the render target and not the renderer because its often used for different things. Using format RBGA for example could be defaulting alpha to 0 on a render target regardless of the main scene) I learned my mistake, and there does not seem to be any other issues pointing this out, so let's close it.

**Comment by mrdoob** [comment]
> I just wish the color and alpha was a property of the render target and not the renderer because its often used for different things.

Indeed, a whole ago we added `viewport` and `scissor` to `WebGLRenderTarget` for the same reason.
Would you like to give it a go?

**Comment by inear** [comment]
Sure! Can put some thoughts into a PR, at least as a discussion starter.

**Comment by inear** [comment]
After looking into it some more I'm not sure it's a good approach to store color/alpha on the rendertarget. It's gonna be confusing with the current state machine approach (with existing code using setClearColor in the update loop vs. letting each rendertarget set state when rendering). Maybe a overrideBackground could be an option to indroduce a way of letting a render target handle its own color/alpha. But I feel I don't have the history and knowledge of the current system to have a say about it.

**Comment by mrdoob** [comment]
@inear what if `renderTarget.clearColor` and `renderTarget.clearAlpha` was `null` by default so the current behaviour wouldn't change?

**Comment by WestLangley** [comment]
The renderer was implemented as a state machine. If you want the drawing buffer and render targets to retain their own states, that is fine, but I suggest making the transition a complete one, and avoid implementing it piecemeal.

**Comment by mrdoob** [comment]
What other properties should be add to make it a complete transition?

**Comment by WestLangley** [comment]
Some suggestions: `encoding`, `toneMapping`, `toneMappingExposure`, `viewport`, `pixelRatio`, `scissor`, `scissorTest`....

**Comment by inear** [comment]
Using render-target-stored values needs to change the state of the background each render if a render target is active and if values exists, swapping back to default afterwards and keep the state machine approach globally. As the RenderPass does, but in webglbackground instead. But will it be confusing with WebGLRenderer.setClearColor? Will that save state in the active rendertarget or just the "regular" background state?  In any case it will change the behavior of existing code when it starts saving values that earlier was a temporary state. Even if we use "null" as default  to avoid breaking things, the behavior of setClearColor will change. If we don't show a warning if trying to use it while a rendertarget is active, and say that "you have to use renderTarget.setClearColor() instead". But I'm on deep water here, have just recently been checking in the inner workings so don't have the full picture as you.

(Btw, I noticed that setting setRenderTarget(null) in combination with a scene.background=color, will trigger a webgl clear warning because of the forced clear. But probably an edge case with my current setup)

**Comment by mrdoob** [comment]
> Some suggestions: `encoding`, `toneMapping`, `toneMappingExposure`, `viewport`, `pixelRatio`, `scissor`, `scissorTest`....

`viewport`, `pixelRatio`, `scissor` and `scissorTest` are done already. `encoding`, `toneMapping` and `toneMappingExposure` put us in program recompilation land.

**Comment by mrdoob** [comment]
> Even if we use "null" as default to avoid breaking things, the behavior of setClearColor will change.

How so?

**Comment by inear** [comment]
I mean if renderer.setClearColor() would save the state in the renderTarget.  
```
renderer.setRenderTarget(myRendertarget)
renderer.setClearColor(0x000000, 0) //will save the state on myRendertarget instead?
renderer.render(camera, scene)
renderer.setClearColor(0xff0000, 1)
renderer.setRenderTarget(null)
renderer.render(camera, scene)
```
Right now, the second setClearColor call changes the color for any render that comes next, but the new behaviour will just change the rendertarget. If renderer.setClearColor would not save to renderTargets, existing code will work as before (if background is updated to get state from renderatargets), but might be confusing when the rest is statemachine-driven 
```
renderer.setRenderTarget(myRenderTarget)
myRenderTarget.setClearColor(0x000000,1)
renderer.setClearColor(0xff0000, 1) //will not change bg to red next render since myRenderTarget is active
renderer.render(camera, scene)
```
(But, my comments are based on an (novise) theoretical implementation that might not be relevant at all if doing a refactor of rendertargets state)

**Comment by mrdoob** [comment]
I'm having a hard time to understand your posts 😕

**Comment by mrdoob** [comment]
> ```
> renderer.setRenderTarget(myRendertarget)
> renderer.setClearColor(0x000000, 0) //will save the state on myRendertarget instead?
> ```

No, will save the state on renderer, but will apply to `myRenderTarget` if the values are `null`.

**Comment by inear** [comment]
Ha ha, yeah I can figure. I think I'm actually in the wrong position to tinker about this stuff, so I'm slowly backing out from this discussion

**Comment by mrdoob** [comment]
Understood 👌
