### ISSUE TITLE
How can I use a model to create a new mesh?

### ISSUE THREAD

**Issue by 1455667325** [mrdoob/three.js#20345]
hello:
I have loaded a dae model, 
I want to use the material in the model to create a other new mesh,
but I failed,
How can i do it.

the code :
codestart
var loader = new ColladaLoader();
loader.load('./demomodels/001.dae', function (collada) {
var elf = collada.scene;
var m = new THREE.MeshPhongMaterial()
var g = new THREE.Geometry();
var qq = []

                elf.traverse(item => {
                    if (item.isMesh) {
                        item.geometry = new THREE.Geometry().fromBufferGeometry(item.geometry)
                        THREE.GeometryUtils.merge(g, item);
                        qq = item.material
                        console.log(qq)
                    }
                })
               
                var mesh = new SceneUtils.createMultiMaterialObject(g,
                    [
                        //  new THREE.MeshPhongMaterial().fromBufferMaterial(qq),
                        new THREE.MeshPhongMaterial(),
                        //  new THREE.MeshPhongMaterial(qq[2]),
                        // new THREE.MeshBasicMaterial({ color: 0x00ff00 }),
                        // new THREE.MeshBasicMaterial({ color: 0xffffff, wireframe: true, transparent: true })
                    ]);
codeend

the qq in the code is model's material ,and i can't ues it in the mesh;( I use the mesh as a node,to create new mesh failed)

**Comment by donmccurdy** [comment]
Hi! We use GitHub issues to track confirmed bug reports and feature development. If you need help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

**Comment by 1455667325** [comment]
thanks
