### ISSUE TITLE
PVRTC-II 2bpp and PVRTC-II 4bpp not supported

### ISSUE THREAD

**Issue by CyangYu** [mrdoob/three.js#20359]
The PVRLoader dont't support PVRTC-II 2bpp and PVRTC-II 4bb pixel format

**Comment by WestLangley** [comment]
Would you like to file a PR to add support for those formats?

**Comment by Mugen87** [comment]
@CyangYu Is it actually possible to use PVRTC2 with WebGL? AIFACS, the extension [WEBGL_compressed_texture_pvrtc](https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_pvrtc/) only exposes the four existing PVRTC1 formats.
