### ISSUE TITLE
CORS settings not passed down to internal Loaders

### ISSUE THREAD

**Issue by amosbyon1224** [mrdoob/three.js#20350]
##### Description of the problem

I am trying to load a .glb file from a remote server. The .glb file references an external texture file that also lives on the server.

I can successfully load the .glb file from the remote server with:
```
const loader = new GLTFLoader(manager);
loader.setCrossOrigin('use-credentials');
```
 but I am running into CORS issues when `GLTFLoader` is trying to  load the texture image.

It seems like `GLTFLoader` is using `ImageBitmapLoader` but `ImageBitmapLoader` is using `fetch` but not passing any options to properly set the `credentials` option:
https://github.com/mrdoob/three.js/blob/2299282085b48ffa9174cce5542c5041bd0ed7c0/src/loaders/ImageBitmapLoader.js#L66-L89

I've also noticed this in `STLLoader` and I'm currently not sure how many other Loaders have a similar issue:
https://github.com/mrdoob/three.js/blob/2299282085b48ffa9174cce5542c5041bd0ed7c0/examples/jsm/loaders/STLLoader.js#L76-L80

Also I'm noticing that some loaders will include an extra `withCredentials` member variable when `Loaders` already has `crossOrigin` which makes it a little confusing for me to know which one to set. (See `FileLoader`)

##### Three.js version

- [x] Dev

##### Browser

- [x] Chrome

##### OS

- [x] macOS

**Comment by Mugen87** [comment]
FYI: `crossOrigin` is only important for loaders which load textures. `STLLoader` does not do this and hence `crossOrigin` is not relevant in this context.
