### ISSUE TITLE
Mouseup/down event listeners not working with orbit controls.

### ISSUE THREAD

**Issue by PalashBansal96** [mrdoob/three.js#20361]
##### Description of the problem

If we add event listeners for `mouseup` and `mousedown` and also have orbit controls enabled in the scene, they don't seem to fire in `r120` and `dev`. It was working with `r119` and below.

I have created a small example showing this. 

[jsfiddle] (https://jsfiddle.net/r0yedmtq/2/) 
Here, I have commented different three.js versions at the top. And I am logging `up` and `down`. All code is same as the default example except lines at the top.
with r120 and dev builds, nothing is logged in the console. with r119 logging works on every mouse interaction.

##### Three.js version

- [x] Dev
- [x] r120
- [ ] r119

##### Browser
Tested on: 
- [x] Chrome 85
- [x] Firefox

##### OS

- [x] macOS 10.14.6

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/20294#issuecomment-689035894

Updated fiddle: https://jsfiddle.net/67u3ymgb/1/

**Comment by PalashBansal96** [comment]
Thanks. Please consider mentioning in the changelog/docs.

**Comment by Mugen87** [comment]
This change is noted in the migration guide:

https://github.com/mrdoob/three.js/wiki/Migration-Guide#r119--r120

And the release notes:

https://github.com/mrdoob/three.js/releases/tag/r120
