### ISSUE TITLE
GLTFExporter: A mesh carries multiple materials, but the geometry index is NULL,the export's gtlf file has problem.

### ISSUE THREAD

**Issue by threethreenine** [mrdoob/three.js#20372]
##### Description of the problem

 A mesh carries multiple materials, but the geometry index is NULL.
 Then use GltfLoader to load into the scene, the material display is wrong.

If you need help, please use the [fbx](https://drive.google.com/file/d/1bdz90i4BXpbmlmPZ0Zf-L3FGU7rmqRhs/view?usp=sharing)  it is a .zip file。

##### Three.js version
- [x]  r120

##### Browser
- [x]  Chrome
##### OS
- [x]  Windows

**Comment by Mugen87** [comment]
> If you need help, please use the fbx it is a .zip file。

The asset has not public access. 

Besides, the following live example uses `GLTFExporter` to export a box with multiple materials. It is correctly imported in the `three.js` editor which uses `GLTFLoader`.

https://jsfiddle.net/94a0shrg/2/

Please use the [forum](https://discourse.threejs.org/) if you need help with your glTF export.

**Comment by threethreenine** [comment]
> 
> 资产没有公共访问权限。
> 
Sorry, the asset is now shared.
