### ISSUE TITLE
CompressedTextureLoader wrong load method declaration

### ISSUE THREAD

**Issue by damienHervault** [mrdoob/three.js#20370]
Hello, it seems there is a declaration error on the following load method : 

```js
export class CompressedTextureLoader extends Loader {

	constructor( manager?: LoadingManager );

	load(
		url: string,
		onLoad: ( texture: CompressedTexture ) => void,
		onProgress?: ( event: ProgressEvent ) => void,
		onError?: ( event: ErrorEvent ) => void
	): void;
}
```

it's return type is void while the code is returning the texture (which seems homogenous with other loaders).

Congrats for the great work and thanks in advance for your attention

##### Three.js version

- [X ] Dev
- [X ] r120

**Comment by mrdoob** [comment]
Would you like to do a PR with the fix?

**Comment by damienHervault** [comment]
Hello guys, amazed by your reactivity :)

> "Would you like to do a PR with the fix?"

Assuming PR stands for something that carries the fix, yes I'd be happy to contribute in the future.
I couldn't find a doc of your "PR process", did I missed something ?

**Comment by Mugen87** [comment]
Check out:

https://github.com/mrdoob/three.js/blob/dev/.github/CONTRIBUTING.md
