### ISSUE TITLE
Is a Sprite can set a  circle?

### ISSUE THREAD

**Issue by 1455667325** [mrdoob/three.js#20388]
const material = new THREE.SpriteMaterial({ map: imgTexture });
                const sprite = new THREE.Sprite(material);
                sprite.scale.set(12, 12);

that sprite is a rect ,can I set it  circle? thanks

**Comment by DefinitelyMaybe** [comment]
please use the [forum ](http://discourse.threejs.org/)or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js) for questions.
