### ISSUE TITLE
Update unclear doc for Quaternion.setFromRotationMatrix()

### ISSUE THREAD

**Issue by FlorentMasson** [mrdoob/three.js#20391]
The doc for [Quaternion.setFromRotationMatrix](https://threejs.org/docs/#api/en/math/Quaternion.setFromRotationMatrix) should indicate that it only works for unscaled matrix like [Euler.setFromRotationMatrix](https://threejs.org/docs/#api/en/math/Euler.setFromRotationMatrix) does (or that it returns a scaled quaternion? Not sure why but normalizing the quaternion afterwards did not work)
I repeateadly had issues with this.

BTW I'm using this placeholder function which I probably found a while ago on the forums or stackoverflow

```js
var tmpSetFromScaledRotationMatrix = new THREE.Matrix4();
var tmp2SetFromScaledRotationMatrix = new THREE.Vector3();

THREE.Quaternion.prototype.setFromScaledRotationMatrix = function (matrix) {
    var te = matrix.elements;

    var sx = tmp2SetFromScaledRotationMatrix.set(te[0], te[1], te[2]).length();
    var sy = tmp2SetFromScaledRotationMatrix.set(te[4], te[5], te[6]).length();
    var sz = tmp2SetFromScaledRotationMatrix.set(te[8], te[9], te[10]).length();

    // if determine is negative, we need to invert one scale
    var det = matrix.determinant();
    if (det < 0) sx = -sx;

    // scale the rotation part
    tmpSetFromScaledRotationMatrix.copy(matrix);

    var invSX = 1 / sx;
    var invSY = 1 / sy;
    var invSZ = 1 / sz;

    tmpSetFromScaledRotationMatrix.elements[0] *= invSX;
    tmpSetFromScaledRotationMatrix.elements[1] *= invSX;
    tmpSetFromScaledRotationMatrix.elements[2] *= invSX;

    tmpSetFromScaledRotationMatrix.elements[4] *= invSY;
    tmpSetFromScaledRotationMatrix.elements[5] *= invSY;
    tmpSetFromScaledRotationMatrix.elements[6] *= invSY;

    tmpSetFromScaledRotationMatrix.elements[8] *= invSZ;
    tmpSetFromScaledRotationMatrix.elements[9] *= invSZ;
    tmpSetFromScaledRotationMatrix.elements[10] *= invSZ;

    return this.setFromRotationMatrix(tmpSetFromScaledRotationMatrix);
}
```

**Comment by Mugen87** [comment]
A pure rotation matrix has by definition no scaling. I don't think this needs to be highlighted in the docs.

**Comment by FlorentMasson** [comment]
My point is, the "pure" rotation is mentioned for Euler, but not for Quaternion

**Comment by Mugen87** [comment]
Well, if there is already the formulation for `Euler.setFromRotationMatrix()`, I think it's okay to copy it over to `Quaternion`. Do you want to make this change?

**Comment by FlorentMasson** [comment]
What is misleading too is this : I came there from the description in Matrix4
![image](https://user-images.githubusercontent.com/9975455/93889830-f7037580-fce9-11ea-85ff-b648385c04cc.png)
While for instance you can extract position or scale for a (non-pure) world matrix with Vector3.setFromMatrixPosition and Vector3.setFromMatrixScale, it doesn't work "out of the box" for Quaternion.setFromRotationMatrix
