### ISSUE TITLE
Strange behavior with texture when extending MeshStandardMaterial as a ShaderMaterial

### ISSUE THREAD

**Issue by mqnc** [mrdoob/three.js#20418]
**Describe the bug**

I wanted to extend the MeshStandardMaterial with my own code and used this:
https://github.com/mrdoob/three.js/blob/dev/examples/webgl_gpgpu_water.html
as an example on how to do that. There, MeshPhongMaterial is adapted.

First the texture just didn't appear at all on the adapted material so in order to test if the texture is loaded at all, I created a minimal example with a custom ShaderMaterial and displayed it in the scene as well, there it works.
Then I tested if it works with the spread syntax and surprisingly it did.
I then tested if I get a usual complaint in the console if I don't define myTex in the uniforms at all but weirdly, it becomes myOtherTex from the minimal ShaderMaterial instead.

Now I can just work with the spread syntax but it would still be good to know what's going on here.

**To Reproduce**

Go to:
https://github.com/mqnc/threejs_custom_shader_texture_issue
and click the three links in the readme.

***Code***

https://github.com/mqnc/threejs_custom_shader_texture_issue/blob/master/uniformsutils_merge.html

***Live example***

https://mqnc.github.io/threejs_custom_shader_texture_issue/uniformsutils_merge.html
https://mqnc.github.io/threejs_custom_shader_texture_issue/spread_uniforms.html
https://mqnc.github.io/threejs_custom_shader_texture_issue/undefined_becomes_other.html

**Expected behavior**

I expect the first and the second link to display myTex on the left and myOtherTex on the right and the third link to display a black square on the left and some error about the missing myTex uniform in the console.

**Platform:**

 - Device: Desktop and Mobile
 - OS: Linux and Android
 - Browser: Chrome and Firefox
 - Three.js version: 121dev

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests. GitHub is for bugs and feature requests only.

**Comment by mqnc** [comment]
I apologize for my overhaste. I have asked in the forum and it turns out someone wrote a library to extend the built-in materials: https://github.com/Fyrestar/THREE.extendMaterial

I have often found myself wanting to modify the built-in materials and I'm wondering if this is maybe such a common use case that this library should be in the examples. Especially since the way that is actually demonstrated in the examples (MeshPhongMaterial in GPGPU water) doesn't seem to be straight forward to generalize.
