### ISSUE TITLE
Object3D: Add removeAll or clear.

### ISSUE THREAD

**Issue by bianyunzhi95** [mrdoob/three.js#20414]
I'd like to have removeAll or clear method in Object3D.

```
	remove: function ( object ) {

		if ( arguments.length > 1 ) {

			for ( let i = 0; i < arguments.length; i ++ ) {

				this.remove( arguments[ i ] );

			}

			return this;

		}

		const index = this.children.indexOf( object );

		if ( index !== - 1 ) {

			object.parent = null;
			this.children.splice( index, 1 );

			object.dispatchEvent( _removedEvent );

		}

		return this;

	}
```

`remove` find child within children with `indexOf` and remove it using `splice` which becomes bottleneck when there are a lot of children objects and I need to remove them all which I am experiencing now.

So i suggest to add `removeAll` method.

```
	removeAll: function ( ) {

		for ( let i = 0; i < this.children.length; i ++ ) {

			let object = this.children[i];

			object.parent = null;

			object.dispatchEvent( _removedEvent );

		}

		this.children = [];

		return this;

	}
```

**Comment by mrdoob** [comment]
Sounds good to me.

I thing I would prefer something like this:

```js
clear: function () {

	while ( this.children.length > 0 ) {

		const object = this.children.pop();
		object.parent = null;
		object.dispatchEvent( _removedEvent );

	}

	return this;

}
```

**Comment by bianyunzhi95** [comment]
`this.children.pop` spends more time than `this.children = []`, doesn't it?
Unless this.children is referenced in remove event handler, i think latter one is better for performance. What is your thought?

**Comment by mrdoob** [comment]
If a user referenced `scene.children` somewhere in their code things would break because with `this.children = []` it would be a different array.

**Comment by bianyunzhi95** [comment]
Then how about `this.children.length = 0`?

**Comment by mrdoob** [comment]
I think that works 👍

**Comment by mrdoob** [comment]
Would you like to do a PR with the new method?

**Comment by bianyunzhi95** [comment]
By the way, I found that invisible objects affect rendering performance too.

![image](https://user-images.githubusercontent.com/42105279/94279312-7f9a4400-ff7e-11ea-9d69-9ecd217726e8.png)

This is what render performance stack looks like when about 10000 objects are on the scene with all invisible.
It takes about 30ms 100x times slower than no objects on the scene.

Is there any way i can make invisible objects as fast as none at all?

**Comment by Mugen87** [comment]
> Is there any way i can make invisible objects as fast as none at all?

Please do not mix topics in issues. This question should maybe discussed at the forum first.

**Comment by Mugen87** [comment]
In order to get this issue closed, I've filed a PR 😇 .

**Comment by bianyunzhi95** [comment]
is this gonna added soon or removed forever?

**Comment by Mugen87** [comment]
#20478 was merged but there are some considerations about the method name. I guess this should be solved before the next release so expect to have this method with `r122`.
