### ISSUE TITLE
Editor : Enable ES class syntax in scripts by updating esprima

### ISSUE THREAD

**Issue by devingfx** [mrdoob/three.js#20417]
The editor is currently bundled with esprima 2.0 to validate script written in the Script panel.

User can't write some ES classes (even if natively understood by the current browser), esprima detect a syntax error!

I could locally update the esprima script to version 3.1 and it worked well...

Could you please update your bundled version of esprima to 3.1? (a plain switch of file `/editor/js/libs/esprima.js` is working like a charm! )

Thanks!

**Comment by mrdoob** [comment]
Would you like to do a PR with the changes you did?

**Comment by devingfx** [comment]
Why not!  
Do you want me to put that in a specific branch?
I get latest esprima 3.1 but it was months agodo you want me to get/audit the current latest, or we stick to 3.1 ?

**Comment by mrdoob** [comment]
> Do you want me to put that in a specific branch?

Yes, `dev` branch 👍

> I get latest esprima 3.1 but it was months agodo you want me to get/audit the current latest, or we stick to 3.1 ?

No preference.

**Comment by Mugen87** [comment]
Fixed via #20425.
