### ISSUE TITLE
RectAreaLightUniformsLib.js is broken on iOS 14

### ISSUE THREAD

**Issue by yellowtailfan** [mrdoob/three.js#20415]
**Describe the bug**

`examples/js/lights/RectAreaLightUniformsLib.js` does not work in iOS 14. It used to work on iOS 13 (with some linear banding artefacts in the reflection of the area light), but under iOS 14 an area light created using this library is simply black and gives no light.

**To Reproduce**

1. Go to https://threejs.org/examples/?q=area#webgl_lights_rectarealight
2. On desktop, the area light is completely white
3. On iOS 13, the area light reflection has horizontal bands
4. On iOS 14, the area light is black and does not illuminate the scene and an error message says "OES_texture_float_linear not supported"

**Screenshots**

Desktop (Chrome on Win 10):

![image (9)](https://user-images.githubusercontent.com/36425185/94251307-b0ba4a80-ff65-11ea-892b-bc0c71e6fdd0.png)

iOS 13 (iPad Air 2019 model):

![File (1)](https://user-images.githubusercontent.com/36425185/94251271-a7c97900-ff65-11ea-8f1d-1ed243246746.jpg)

iOS 14 (iPhone 11):

![File](https://user-images.githubusercontent.com/36425185/94251341-badc4900-ff65-11ea-8365-1b4c4ca716fc.jpg)

**Diagnosis:**

The problem seems to be caused by a [change in Webkit in Safari on iOS 14](https://bugs.webkit.org/show_bug.cgi?id=212005). Previously in iOS 13 Webkit would claim it supported the WebGL extension `OES_texture_float_linear` but it actually didn't. Now in iOS 14, Webkit correctly reports that it does not support that extension. 

**Suggested fix:**

Change RectAreaLightUniformsLib to fallback from `THREE.LinearFilter` to `THREE.NearestFilter` when the `OES_texture_float_linear` WebGL extension is not available.

**Comment by Mugen87** [comment]
> Change RectAreaLightUniformsLib to fallback from THREE.LinearFilter to THREE.NearestFilter when the OES_texture_float_linear WebGL extension is not available.

Sounds good. Do you mind creating a PR with the fix?

**Comment by yellowtailfan** [comment]
Thanks @Mugen87 we'll look into that. It's nice to know a PR would be welcome!

**Comment by yellowtailfan** [comment]
I've added a draft pull request (see above). However, to access the renderer I changed the API. I'd love suggestions on how to avoid changing the API if possible.

**Comment by Mugen87** [comment]
Reconsidering this issue: I'm not sure anymore if using `NearestFilter` is actually an appropriate fix.

Maybe it would be better to check if `OES_texture_half_float` and `OES_texture_half_float_linear` can be used. This is also mentioned in the original PR: #9234

> explore using HalfFloat textures instead of Float to increase mobile support

**Comment by yellowtailfan** [comment]
I agree that would be a better approach, as it would avoid rendering area lights with visible artefacts, but it would take a little bit longer to implement.

From a quick test on iOS 13 and 14 using [Khronos comformance tests](https://www.khronos.org/registry/webgl/sdk/tests/conformance/extensions/), it looks like `OES_texture_half_float` and `OES_texture_half_float_linear` are supported.

Using half-float for area lighting involves converting the two 16k float32 arrays in `examples/jsm/lights/RectAreaLightUniformsLib.js` to uint16 arrays via a function like toHalf() (https://github.com/mrdoob/three.js/blob/ff48de58e216bc72abb4085a080c5acb66f2f584/examples/js/loaders/RGBELoader.js#L348).

**Comment by yellowtailfan** [comment]
I've created PR #20477 which uses half-float instead of float and renders area lighting without artefacts on Windows, iOS 13 and iOS 14.

I've put some to-do items and questions in the PR.

**Comment by kamalk151** [comment]
Is it helpful with jsQR library? because i am using jsQR library to scan the QR code so its not working with latest release version 14 on iOS device.
Can anyone suggest me?
