### ISSUE TITLE
WebGLProgram shader error X3512: sampler array index must be a literal expression

### ISSUE THREAD

**Issue by matt383** [mrdoob/three.js#20416]
In the latest Chrome Canary build, D3D shader compilation fails sometimes with an X3512 error:

`THREE.WebGLProgram: shader error:  0 35715 false gl.getProgramInfoLog C:\fakepath(228,12-35): error X3512: sampler array index must be a literal expression`

It's quite possible that it's an issue with the Canary build itself, but I could not find anything related in their issue tracker and did not know what to report there exactly.

The easiest repro is just to open the _webgl_animation_cloth_ example with the latest Chrome Canary build:
https://threejs.org/examples/#webgl_animation_cloth

**Platform:**

 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome Canary 87.0.4274.0
 - Three.js version: [dev, r120]

**Comment by Mugen87** [comment]
Please report this issue here: https://bugs.chromium.org/p/chromium/issues/list

>  and did not know what to report there exactly.

I think sufficient if you say the same like here: That the D3D shader compilation fails sometimes with an X3512 error.
