### ISSUE TITLE
The current build is broken

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#20411]
@mrdoob @Mugen87 

Not sure if you are aware or not:
For the current (2 days old) three.min.js build I get errors everywhere:

Uncaught TypeError: scene.add is not a function
and
Uncaught TypeError: i.setIndex is not a function

**Comment by mrdoob** [comment]
Oh! Thanks! I'll have a look tomorrow.

**Comment by mrdoob** [comment]
Okay, should be fixed after https://github.com/mrdoob/three.js/commit/8d2c35c173fe7dcead8b8a8567705c537af2f9c1.
I've added a new example `misc_legacy` so we'll know if we break the build again.

**Comment by mrdoob** [comment]
Thanks again!
