### ISSUE TITLE
Points cloud gets unwanted outline pass

### ISSUE THREAD

**Issue by JarSeal** [mrdoob/three.js#20428]
**Describe the bug**

When having at least one object in the outline pass selectedObjects array and a scene that also has a points object, the outline pass gets rendered in the middle of the points. This does not happen in desktop chrome in windows nor could I reproduce it in a new iPad or iPhone. It does happen in all of the Android Chromes that I have tested and also on an iMac (tested by @Mugen87 ).

**To Reproduce**

1. Create a simple object and add it to the scene
2. Create a points cloud and add it to the scene
3. Add effect composer, render pass, and outline pass
4. Add the simple object to the outline selectedObjects array
5. Make the particles move a little to make the bug appear more clearly
6. Render the scene with the composer

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/Norppa/04t6rjoh/3/show)

**Expected behavior**

I would expect the outline pass artefact not to show up on points on any of the platforms and browsers.

**Screenshots**

![a18aac64ab90c4cb82e709ba18a2d48a7d0e08d5](https://user-images.githubusercontent.com/4513523/94448049-0e0c0100-01dd-11eb-8f57-0da68e43d382.png)

**Platform:**

 - Device: mobile and desktop (iMac)
 - OS: Android (could not reproduce this on iOS)
 - Browser: Chrome (not Windows desktop)
 - Three.js version: r120 (latest at this point)

**Comment by Mugen87** [comment]
From the forum: https://discourse.threejs.org/t/points-rendering-problem-on-mobile-with-outline-pass/19173

**Comment by Mugen87** [comment]
I've debugged this bug today and it seems points and lines are not compatible with `OutlinePass`. Even when using point sprites it is not possible to produce an outline around the sprite.

Looks like it's necessary to do the same like with `SSAOPass` and exclude points and lines.

**Comment by Mugen87** [comment]
@Kangz In context of point sprites I have a related question in context of WebGPU: I've noticed that when using the `point-list` primitive topology, points always have the size of 1 px. Is this going to change in the future? Will the size be configurable? Or is it necessary to render triangles if you want sprite/billboard-like entities? 

Related WebGL examples:

https://threejs.org/examples/webgl_points_billboards
https://threejs.org/examples/webgl_points_sprites

**Comment by Kangz** [comment]
Point size will be fixed to 1. This is because like for WebGL there is no guarantee that HW supports bigger points, and because the clipping behavior of large points is inconsistent between HW.
