### ISSUE TITLE
IOS14 safari m3u8 live stream using VideoTexture can not render success

### ISSUE THREAD

**Issue by guoguicheng** [mrdoob/three.js#20424]
**Describe the bug**

I get some probleam in my project,videoTexture render mp4 video is successed,but using m3u8 live stream is render black in my ios14 safari browarse,mac safari version 14.0 render success. I'm trying test the m3u8 live stream using canvas drawImage also success,it's make me confuse,gave me any idea please,thx.

***Live example***

* [https://www.mxreality.cn](https://www.mxreality.cn)

**Platform:**

 - Device: [Mobile]
 - OS: [iOS14]
 - Browser: [Safari]
 - Three.js version: [dev, r103]

**Comment by Mugen87** [comment]
Please report this issue to Apple instead.

**Comment by lixiaojun99** [comment]
I still have this problem in safari ios14.1

**Comment by Mugen87** [comment]
@lixiaojun99 Please use the following URL to report the issue: https://webkit.org/reporting-bugs/

**Comment by atomarch** [comment]
Existing webkit bug: https://bugs.webkit.org/show_bug.cgi?id=215908

Looks to be fixed in iOS 14.2 beta

**Comment by luzh0422** [comment]
Hello, @guoguicheng. Is this problem solved? I am also troubled by this problem, or is there any other alternative solutions.

**Comment by luzh0422** [comment]
@Mugen87 hi，is this problem solved?  Or is there any other alternative solutions.

**Comment by guoguicheng** [comment]
try upgrade ios version to 14.6, [https://bugs.webkit.org/show_bug.cgi?id=215908](https://bugs.webkit.org/show_bug.cgi?id=215908)

**Comment by luzh0422** [comment]
@guoguicheng Thank you very much. Finally there is a conclusion.
