### ISSUE TITLE
Matrix4.decompose docs and #15079

### ISSUE THREAD

**Issue by lucasdomanico** [mrdoob/three.js#20435]
Hello, I think is worth commenting in the [Matrix4.decompose](https://threejs.org/docs/#api/en/math/Matrix4.decompose) docs the issue related to #15079
In particular when decomposing the [Object3D.matrixWorld](https://threejs.org/docs/#api/en/core/Object3D.matrixWorld)

**Comment by Mugen87** [comment]
Feel free to enhance the docs with a note 👍 .

**Comment by mrdoob** [comment]
Indeed 👍
