### ISSUE TITLE
Feature request: support InstancedMesh.setOpacityAt(index,color)

### ISSUE THREAD

**Issue by XiangLiLiang** [mrdoob/three.js#20431]
I want to set the opacity of each item by index , It's like InstancedMesh.setColorAt()

**Additional context**

I've found a way to do it ,but it's not work very well
https://discourse.threejs.org/t/instance-geometry-opacity/9164
![image](https://user-images.githubusercontent.com/17902501/94510260-ece0fa00-0248-11eb-8890-9b54e164ff92.png)
![image](https://user-images.githubusercontent.com/17902501/94510269-f10d1780-0248-11eb-8810-748221dbbeda.png)

**Comment by mrdoob** [comment]
I think adding per-instance opacity support to `InstancedMesh` brings more problems than it solves...

https://discourse.threejs.org/t/is-it-possible-to-set-varying-opacity-for-objects-inside-a-instancedmesh-filled-with-boxbuffergeometry-meshpongmaterial-cubes/19181/2

**Comment by Mugen87** [comment]
Yeah, I'm afraid this feature will be very "support-intensive"...

**Comment by XiangLiLiang** [comment]
> I think adding per-instance opacity support to `InstancedMesh` brings more problems than it solves...
> 
> https://discourse.threejs.org/t/is-it-possible-to-set-varying-opacity-for-objects-inside-a-instancedmesh-filled-with-boxbuffergeometry-meshpongmaterial-cubes/19181/2
> 
> > It’s not possible, mainly because if that was allowed the first thing people bump into is that the order in which transparent objects get renderer is incorrect.
> > In order to render them correctly the instances will need to be reordered every time the camera moves.

Thank you for your reply

**Comment by Bug-Reaper** [comment]
I have a use-case where render-order is unimportant (or rather can be the same fixed priority for all instances). Godot has some fancy dynamic dithering to fake opacity without as many renderorder headaches. Unsure if relevant but this rabbit hole reminded me.

InstancedMesh in TSL seems to readily support arbitrary per instanced attributes via `instanceIndex` and `sharedbufferattributes`.

**Comment by Bug-Reaper** [comment]
https://github.com/user-attachments/assets/e2f52e5c-e816-42aa-b876-d028d91ddb07

I forgot I actually did this fairly recently:
```js
 const colsty = storage(new THREE.StorageInstancedBufferAttribute(new Float32Array(totalInstances * 3), 3, instancedMesh.count));
// Doing flat .5 opacity here, but could easy to a vec4 StorageInstancedBufferAttribute
const cripNode=Fn(()=>{
    return vec4(colsty.element(instanceIndex),.5)
  })
  instancedMesh.material.colorNode = cripNode()
```

It's not an efficient work-around and took like a day+ to figure out. At this point I'd almost prefer instanceMesh have:
- No `setXYZAt` functions and instead you create what you need.
Or:
- An arbitrary ability to add your own `setXYZAt` and that registers a new StorageInstancedBufferAttribute property on the root instanced mesh.

I have an even more niche use-cases with InstancedMesh with morph-targets and per-instance opacity, wish me luck 👍

---

Note to maintainers: Keep an eye out for when I squeeze enough free-time to PR some improved DX around `instancedMesh`.
