### ISSUE TITLE
Wrong Oculus Rift controller direction

### ISSUE THREAD

**Issue by davnec** [mrdoob/three.js#20447]
**Describe the bug**

With the latset version of Threejs with Oculus Rift and Touch controller I noticed that the direction of the beam aere rotated up of 90 degree.

**To Reproduce**

ThreeJs WebXR examples (version 120, 121)

**Screenshots**
![oculus issue](https://user-images.githubusercontent.com/2360891/94860876-f465f600-0436-11eb-8968-c756fbdc6c49.JPG)

**Platform:**

 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome canary Version 87.0.4279.0 (It's the only browser that works, for me, with threejs examples and Oculus Rift)
 - Three.js version: r120, r121

**Comment by Mugen87** [comment]
Probably related to https://bugs.chromium.org/p/chromium/issues/detail?id=1129495.

I don't believe this issue is fixable on `three.js` level.

**Comment by davnec** [comment]
> Probably related to https://bugs.chromium.org/p/chromium/issues/detail?id=1129495.
> 
> I don't believe this issue is fixable on `three.js` level.
> 
> I've tested today with Oculus Quest and the official examples work fine.

Thanks, I agree with you! I have found the sample https://immersive-web.github.io/webxr-samples/input-tracking.html with the same issue!
Of course It's a nonsense correct this in threejs i wait for the fix.
Every time I update the browsers I have a surprise with oculus rift... :(
