### ISSUE TITLE
why not update the npm publish anymore ?

### ISSUE THREAD

**Issue by xgqfrms** [mrdoob/three.js#20440]
# why not update the npm publish anymore ?

> Last publish, 4 years ago ❓ 

https://www.npmjs.com/package/three.js

```sh
# yarn add three.js
# OR
$ npm i three.js

```

![image](https://user-images.githubusercontent.com/7291672/94772548-72e97600-03ec-11eb-8dad-bdb13d7a793e.png)

**Comment by cecilemuller** [comment]
Because it has been deprecated, the correct package is [three](https://www.npmjs.com/package/three) as shown in https://threejs.org/docs/index.html#manual/en/introduction/Installation

**Comment by mrdoob** [comment]
![image](https://user-images.githubusercontent.com/97088/94793482-7cd39f00-0415-11eb-91b7-e165be36f067.png)

**Comment by xgqfrms** [comment]
# still has question, this link is 404 and can not find it.

https://www.npmjs.com/packages/three

![image](https://user-images.githubusercontent.com/7291672/94994045-acc2a400-05c7-11eb-95e3-c21ffe0597d0.png)

**Comment by xgqfrms** [comment]
@cecilemuller Thanks a lot!

https://www.npmjs.com/package/three ✅

https://www.npmjs.com/package`s`/three ❌

https://www.npmjs.com/search?q=three
