### ISSUE TITLE
SSAOPass: Lines and points should be excluded.

### ISSUE THREAD

**Issue by blfunex** [mrdoob/three.js#20443]
**Is your feature request related to a problem? Please describe.**

A grid on my scene was contributing the depth buffer and nomals buffer of the SSAOPass, I mitigated it by disabling depthWrite and making the grid material transparent, but the normal contribution is still there and is visible in the far distance of the camera, when I inspect the .

**Describe the solution you'd like**

For the line basic material, not to output black in the normal buffer of SSAOPass.

**Describe alternatives you've considered**

I considered postprocessing, but I was thrown off by the [lack of type support](https://github.com/vanruesc/postprocessing/issues/166) ... but that's unrelated.

**Additional context**

![image](https://user-images.githubusercontent.com/11468624/94805185-dd49e880-03e3-11eb-9d2c-34454b4f38d6.png)
![image](https://user-images.githubusercontent.com/11468624/94805237-f5ba0300-03e3-11eb-9aca-c65c120f0c55.png)
![image](https://user-images.githubusercontent.com/11468624/94805327-1f732a00-03e4-11eb-8fdb-cddb90a9d837.png)
![image](https://user-images.githubusercontent.com/11468624/94805354-2b5eec00-03e4-11eb-98d2-276f810dad94.png)

**Comment by blfunex** [comment]
It just does not seem logical to me for those materials to contribute to the pass, I am not that experienced with the internals of three, I would of fixed it.

**Comment by Mugen87** [comment]
You could try the following: Move all objects which should not be affected by SSAO to layer 1:

```js
grid.layers.set( 1 );
```
Then modify the `render()` method of `SSAOPass` like so:
```js
// render beauty and depth

this.camera.layers.enable( 1 );

renderer.setRenderTarget( this.beautyRenderTarget );
renderer.clear();
renderer.render( this.scene, this.camera );

this.camera.layers.disable( 1 );
```
Does this improves the result? The modification will ensure that the objects are honored by the beauty pass but not when the actual AO and blur is applied.

**Comment by Mugen87** [comment]
> It just does not seem logical to me for those materials to contribute to the pass,

The contribution of objects with `MeshBasicMaterial` is required to compute proper SSAO for other object in the scene.

**Comment by blfunex** [comment]
Oh, I did not take that into consideration.

**Comment by blfunex** [comment]
But we can the situation showcased by the screenshots faulty ? the line material outputting black for normal buffer ?

**Comment by Mugen87** [comment]
Lines and points should probably not be taken into account by `SSAOPass`. The problem is that the pass relies like many other passes on `Scene.overrideMaterial`. And this property affects all materials in the scene. So it will require some refactoring to properly exclude them. However, other issues like #20428 might require something similar.

For now, I'm afraid you have to solve this on app level.

**Comment by blfunex** [comment]
Could you point me in some direction, I tried a lot of monkey patching to no avail.

**Comment by blfunex** [comment]
At one point I thought I could get away with having two render passes, and I would separate the editor gizmos from the editor model.
This is a rather quirky requirement by my contractor to have SSAO, when they should bake AO to the models.

**Comment by Mugen87** [comment]
If you tried the approach with the layers? Did it help? I've tested it on my system and the normal pass is not affected anymore by the lines.

**Comment by blfunex** [comment]
I did not read that initial comment, sorry. I will try it thanks for the help.

**Comment by blfunex** [comment]
That suggestion fixed my issue, I tried to be clever and set the layer on a `Group` of gizmos and failed miserably. Might open issue later.

Not sure if I should close this issue, I will leave to one of the maintainers.

**Comment by blfunex** [comment]
Thanks a lot @Mugen87  for your assistance

**Comment by Mugen87** [comment]
>  I tried to be clever and set the layer on a Group of gizmos and failed miserably.

You have to set the layer to all objects in the group of gizmos.

**Comment by Mugen87** [comment]
> Not sure if I should close this issue, I will leave to one of the maintainers.

I've renamed it for better tracking. I think it's appropriate to leave it open.
