### ISSUE TITLE
A SSAOShader uniform is invalid

### ISSUE THREAD

**Issue by blfunex** [mrdoob/three.js#20445]
This [line](https://github.com/mrdoob/three.js/blob/7bc80c5a84e277cef288fe2a5d35b1d1347fc10b/examples/jsm/shaders/SSAOShader.js#L91) is out of sync with the rest of the shader references depthSampler while the uniform is tDepth.

**Comment by Mugen87** [comment]
Good catch! Would you like to make a PR with the fix?

**Comment by blfunex** [comment]
I am deep in a project I can not open PR now.

**Comment by blfunex** [comment]
Thanks 😄  👍

**Comment by Mugen87** [comment]
Done 7db62b06f8b879a6101bc3dbb408c84a807c276d

**Comment by blfunex** [comment]
and `coord` should be `vUV` I suppose.

**Comment by Mugen87** [comment]
It should be `screenPosition`.

**Comment by Mugen87** [comment]
Solved eccad97efff01c18c3602fd24939e32eb3fdf61a.
