### ISSUE TITLE
Editor: Honor animations when exporting to glTF.

### ISSUE THREAD

**Issue by Gaurav-chopra** [mrdoob/three.js#20452]
I tried exporting a gltf file from threejs editor but it doesnt export the animations. The animations are visible and do play in the editor but when exported they are not there. Could you tell any steps that i am missing or is this a bug?

**Comment by Mugen87** [comment]
It's not a bug, just a feature which is not implemented yet. `GLTFExporter` does support animation export however the editor does not assign existing animations when a glTF export is executed.

**Comment by Gaurav-chopra** [comment]
Okay thanks. Could you suggest any online editor to export the GLTF with animations?
