### ISSUE TITLE
[BUG] TS2339: Property 'nodes' does not exist on type 'GLTF'.

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [mrdoob/three.js#20469]
"three": "^0.121.1",

```ts
export interface GLTF {
	animations: AnimationClip[];
	scene: Group;
	scenes: Group[];
	cameras: Camera[];
	asset: {
		copyright?: string;
		generator?: string;
		version?: string;
		minVersion?: string;
		extensions?: any;
		extras?: any;
	};
	parser: GLTFParser;
	userData: any;
}
```

But nodes exists:

![image](https://user-images.githubusercontent.com/69426460/95295457-c9890100-087f-11eb-8d46-4f2855c961e4.png)

**Comment by mrdoob** [comment]
What is TS2339?

**Comment by MaxmaxmaximusAWS** [comment]
@mrdoob its TypeScript error code, to identify errors whatever text messsages

**Comment by Mugen87** [comment]
I've tested a few example (like https://threejs.org/examples/webgl_loader_gltf) but I don't see `nodes` in the `gltf` object 🤔 .

**Comment by mrdoob** [comment]
Closing this. Please, do not ignore the issue when reporting bugs.

<img width="822" alt="Screen Shot 2020-10-07 at 11 55 24 AM" src="https://user-images.githubusercontent.com/97088/95322190-13e99c80-08d7-11eb-9bbf-59dae907cc90.png">
