### ISSUE TITLE
[BUG] typescript declaration error:

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [mrdoob/three.js#20462]
```ts
class MeshPhongMaterial {
	normalScale: Vector2;
}
```

but `MeshPhongMaterial` can assept `[1,1]` array end create vector by this

**Comment by Mugen87** [comment]
I'm afraid this is not true. When you look at the following fiddle, using an array overwrites the type of  `MeshPhongMaterial.normalScale`. It's not a `Vector2` anymore but an array.

https://jsfiddle.net/gm0x87co/
