### ISSUE TITLE
new texture ignores UV map.

### ISSUE THREAD

**Issue by mshamaseen** [mrdoob/three.js#20486]
**Describe the bug**

I'm trying to reassign a new texture to a material, but the new texture is not respecting the UV map! I tried to use the same texture of the object by reloading it, and it also doesn't respect the UV map.

**To Reproduce**

1. load the glb file
2. update the texture of the main body material.
3. the texture will be updated with a strange UV mapping.

***Live example***

the object:
https://drive.google.com/file/d/1Cd17YhsNN7Tru13I87xUh1Fgibk8NGr8/view?usp=sharing

the texture used:
https://drive.google.com/file/d/1-wIgJ-d3TTHoWvCSb6GLr8KiCB13uJ_G/view?usp=sharing

**Expected behavior**
the texture should respect the UV map.

**Screenshots**
here is how it looks when first upload the object in the editor
![image](https://user-images.githubusercontent.com/38951661/95608551-f0089100-0a65-11eb-8911-aff0cf9770ad.png)

here is how it looks when choosing the map with the exact same texture
![image](https://user-images.githubusercontent.com/38951661/95608609-0c0c3280-0a66-11eb-90c9-68b615ca0f55.png)

I also tried it via coding because I thought it might be the editor issue, but it also didn't work with custom coding!

**Platform:**
 - Device: Desktop
 - OS:  Linux
 - Browser: Chrome, Firefox
 - Three.js version: r120

**Comment by donmccurdy** [comment]
Note the texture section here — https://threejs.org/docs/#examples/en/loaders/GLTFLoader ... if you are loading a texture outside of the glTF model, you will need to set `.flipY=false` on the texture to have it match glTF's UV convention. Does that fix your issue?

**Comment by mshamaseen** [comment]
@donmccurdy Yep that fix it! I was looking at Texture and Material sections of the documentation, I didn't expect it will be GLTF limitation.
Thank you very much, man!
