### ISSUE TITLE
Incorrect animation movement from Mixamo/Unity fbx file

### ISSUE THREAD

**Issue by rem0g** [mrdoob/three.js#20499]
I've been trying to import model and animation in three.js via FBX importer, from model/animation that I made in Unity and exported in FBX format i'm getting movements all over the place. From Mixamo I'm getting the same behavior.

I'm using sample files from three.js (webgl_loader_fbx.html)
I'm using characters named Remy and Mouse.  https://www.mixamo.com/#/?page=1&type=Character 
The animation is captured from Glycon Mocap, but animation from Mixamo is also producing wrong movements with Three.js.

This is not what it should be doing.
https://www.nt2doven.nl/three/examples/webgl_loader_fbx.html

This is expected behavior from Unity WebGL.
https://www.nt2doven.nl/webgl/

I don't know if this is bug, so please correct me if I'm wrong.  If i'm missing anything, i'm glad to read to learn.

Thank you very much.

Unity 2020.1.8f1
Unity FBX exporter 3.2.1-preview.2

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests. If it turns out this is a bug, we can reopen this issue.
