### ISSUE TITLE
User option to send lights in a different space

### ISSUE THREAD

**Issue by DavidPeicho** [mrdoob/three.js#20491]
## Description

When writing custom shaders, it can sometimes be a good idea to send lights in another space than the ModelView one.
For instance, performing ray marching of a volume and accessing light info would be much much faster by having all the lights in inverse ray space.

## How To

I have to admit I am not sure how this could fit in the pipeline. 

#### 1. Changing WebGLLights

One idea could be to have a way to select from multiple common frames, such as `inverse(modelView)`, `modelView`, maybe `world` has well. This could be implemented in [WebGLLights](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLLights.js). Problem is that it's more code to maintain.

#### 2. Changing `onBeforeRender`

Another idea, includes less changes as well as less code to maintain, would be to give the user the access to the [currentRenderState](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLLights.js) so the user can do whatever he wants. It doesn't need to be in `onBeforeRender`, it could be in another callback I guess? `onLightSetup()` or something.

## Current "Fix"

The current fix is often to send manually the lights and what I need to the shader. However, there is no easy way to access the lights and the lights state, making things messy and less optimized.

**Comment by gkjohnson** [comment]
Is there a reason that providing the transform matrix from ModelView frame into the frame you want as a uniform so you can transform the light vectors before raymarching isn't sufficient?

**Comment by DavidPeicho** [comment]
So that's possible and I also do that, but it creates an overhead, because each light will need to be transformed in the vx or fx shader. So, when there are like N directional, N point lights, etc... that's a lot.

I need either to transform them on the fly when sampling (for every step):

```glsl
// Marching.
for (int i = 0; i < 100; ++i)
{
  PointLight light = ...;
  vec3 lightInRaySpace = toRaySpace * light.position;
}
```

 or I would need to basically re-create the positions array for instance:

```glsl
void
main()
{
  ...
  vec3[ NUM_DIR_LIGHTS ] directionalsRaySpace;
  vec3[ NUM_POINT_LIGHTS ] positionsRaySpace;

  // Marching.
  for (int i = 0; i < 100; ++i)
  {
    ...
  }
}
```

**Comment by gkjohnson** [comment]
> So that's possible and I also do that, but it creates an overhead, because each light will need to be transformed in the vx or fx shader. So, when there are like N directional, N point lights, etc... that's a lot.

It doesn't actually seem like that much to me. Computing the transformed light direction / position vector outside the for loop in the fragment or vertex shader would seem to be the better way to do it. How many lights do you have in your scene? The common case might be a few directional or point lights tops and at that point it seems like a minor optimization to avoid a few vector transformations relative to performing 100+ raymarch steps with texture sampling and other lighting computations. Are you seeing measurable performance benefits when removing those calculations and using a uniform?

**Comment by DavidPeicho** [comment]
I am going to close this as it looks like there is not much demand except myself, and as gkjohnson noted I can just compute it once.
