### ISSUE TITLE
video webcam input texture example freezes on iPhone Safari

### ISSUE THREAD

**Issue by ionif** [mrdoob/three.js#20497]
**Describe the bug**
The video webcam input texture example freezes when you visit it on Safari on my iPhone 11. I want to be able to use the webcam texture in my own project. I thought it was an issue with getUserMedia on my end but the example doesn't work either. 

**To Reproduce**
Navigate to: https://threejs.org/examples/?q=cam#webgl_materials_video_webcam on your iPhone.

**Expected behavior**

The webcam video should always be updated. Right now on mobile, it loads the first frame of the video and then freezes. 

**Screenshots**

![IMG_3164](https://user-images.githubusercontent.com/19884625/95773138-86fe6480-0c83-11eb-935e-25f88a03528a.PNG)

**Platform:**

 - Device: Mobile
 - OS: iOS
 - Browser: Safari

**Comment by Mugen87** [comment]
> The webcam video should always be updated. Right now on mobile, it loads the first frame of the video and then freezes.

Unfortunately, I have no iOS device for debugging but maybe you can check if the browser logs any warnings or errors into its console. 

Besides, does it work if you use Chrome on iOS?

**Comment by ionif** [comment]
I tried using chrome, but it doesn't request camera permissions at all so the screen in black for the example. 
![IMG_3165](https://user-images.githubusercontent.com/19884625/95774062-53bcd500-0c85-11eb-91ae-5709ea8b0fc0.PNG)

**Comment by Mugen87** [comment]
Can't reproduce this with a Pixel and Chrome on Android. 

I'm not familiar with iOS but can you please make sure that you have actually allowed camera access on system level?

**Comment by ionif** [comment]
Pretty sure it's an iOS specific issue since there's a lot of weird hoops to jump through for getUserMedia to work. Another thing is that this exact example was working on my phone a bit ago and I updated my phone to iOS 14 today but that didn't fix the issue either.

**Comment by Mugen87** [comment]
Do you mind performing remote debugging with your iPhone? Inspecting the browser's console log might help to analyze this issue.

**Comment by ionif** [comment]
Yep sorry, here's the console output: "THREE.WebGLRenderer: OES_texture_float_linear extension not supported."

This happens on page load, not after you confirm camera permissions.

**Comment by ionif** [comment]
Looks to me like it may be related to #20415.

**Comment by Mugen87** [comment]
Um, I don't think #20415 is related to this issue. Can you please check if other media stream related demos work on your system. E.g. https://davidwalsh.name/demo/camera.php

**Comment by ionif** [comment]
Sorry I'll reopen this then, my mistake. I attached a screenshot of the website on my phone and the console.
<img width="1226" alt="Screen Shot 2020-10-12 at 2 18 26 PM" src="https://user-images.githubusercontent.com/19884625/95782685-e7969d00-0c95-11eb-8f43-336accef293d.png">
![IMG_3166](https://user-images.githubusercontent.com/19884625/95782676-e4031600-0c95-11eb-871f-7acad3454730.PNG)

**Comment by Mugen87** [comment]
Okay, since the canvas above the `Snap Photo` button is black, this problem is not related to WebGL or `three.js`. I suggest you report this issue at the WebKit bugtracker:

https://webkit.org/reporting-bugs/

**Comment by ionif** [comment]
just found a solution so figured I'd post, seems to be related to the framerate fo the video, so [the solution I found in the jsQR issues](https://github.com/cozmo/jsQR/issues/185) fixes it, navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment", frameRate: {ideal: 5, max: 10} } }) fixes it.
