### ISSUE TITLE
How to make the surface smoother?

### ISSUE THREAD

**Issue by wangyu-97** [mrdoob/three.js#20493]
**My problem:**

Recently, I am learning THREE.js to visualize a chemical structure, like this:
https://pic2.zhimg.com/48ff373fcf584e28ac59336d8053b094_r.jpg

However, in order to make the painted surface appeared more smooth, I choose to use as many triangles as possible which is stored in BufferGeometry data structure. This cause a big problem: the json file which stores the Triangular coordinates turn out to be very large even more than 200MB, which is bad for network transmission and it takes up large amount of storage space. 

So, I wonder if there are any solutions in THREEJS to this problem? I once wonder whether I can use small amount of triangles' coordinates, then use the interpolant to make more triangles, but there seems no example to illustrate the process of my assumption, so I find it hard to do this kind of experiment. This problem can be interpreted as how to make the surface in the below picture more smooth. In this way, I don't need big file but can still visualize a smooth surface.

![image](https://user-images.githubusercontent.com/32156765/95722856-0f423100-0ca7-11eb-8589-2e1ef6248e76.png)

This really confuse me for a long time, can you give me some suggestion? Thank you very much if you can~

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by wangyu-97** [comment]
Ok, thanks~
