### ISSUE TITLE
DRACO transcoder lib update should be mentioned in migration guide

### ISSUE THREAD

**Issue by SBRK** [mrdoob/three.js#20506]
The Draco loader lib files were updated in r121, but there's no mention of it on the [migration guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide).
It was a breaking change for us, since using the old lib doesn't work with r121 DRACOLoader, and in our code the draco lib is fetched from our server, so we have to update it manually.
I had to guess what was happening from the error, and check with the last commit of the lib files to understand that the lib was updated.
I think maybe it should be mentioned in the migration guide ?

**Comment by Mugen87** [comment]
So you are referring on #20399, right?

Examples files like `DracoLoader` and the respective libs always have to be from the same release. We highlighted this multiple times in the past and it's also noted in the [documentation](https://threejs.org/docs/index.html#manual/en/introduction/Installation).

> It's important that all files use the same version.

**Comment by donmccurdy** [comment]
I think I agree with @SBRK on this — and sorry for the breakage! The WASM files have to be copied into a serving directory by the user, which is an extremely unusual method of dependency management in the JS world, as a user I would not intuitively know to do that every time I run `npm update`. A note in the migration guide seems like a good idea to me.

**Comment by Mugen87** [comment]
Okay, agreed 👍 .

**Comment by SBRK** [comment]
> So you are referring on #20399, right?
> 
> Examples files like `DracoLoader` and the respective libs always have to be from the same release. We've highlighted this multiple times in the past and it's also noted in the [documentation](https://threejs.org/docs/index.html#manual/en/introduction/Installation). I don't think we need a separate note in the migration guide for this.

True, but the draco  lib has to be manually copied like @donmccurdy mentioned and it very rarely changes (last update before that was in January 2019 iirc), so I don't think anyone bothers copying or just checking the files at every new version.

**Comment by Mugen87** [comment]
Added a note in the migration guide: https://github.com/mrdoob/three.js/wiki/Migration-Guide#r120--r121
