### ISSUE TITLE
add to Migration-Guide#r110--r111  tip

### ISSUE THREAD

**Issue by dslming** [mrdoob/three.js#20519]
**Is your feature request related to a problem? Please describe.**
when i use like this don't working:
```js
// ...
this.geometry.addAttribute('charIndex', charIndicesBufferAttribute);
this.material = new THREE.RawShaderMaterial()
this.mesh = new THREE.Points(this.geometry, this.material);
```

i find r111 add code:

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/23415941/96221235-c2b76800-0fbc-11eb-9c82-d8a8d40e3f4f.png)

add a tip:
- must be set BufferGeometry index and position,like this:
```js
  this.geometry.addAttribute('charIndex', charIndicesBufferAttribute);
  this.geometry.setIndex(new THREE.BufferAttribute( new Uint32Array([0]), 1));
  this.geometry.setAttribute( 'position', new THREE.Float32BufferAttribute( [0,0,0], 3 ) );
  this.geometry.setDrawRange(0, strlen);
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Mugen87** [comment]
How about: _Instances of `BufferGeometry` require at least a `position` attribute now._

**Comment by Mugen87** [comment]
Updated the migration guide! Should be okay now 👍 .
