### ISSUE TITLE
MaterialLoader: Error when loading MeshToonMaterial.

### ISSUE THREAD

**Issue by sir-aureus** [mrdoob/three.js#20521]
I have a scene I had been working on, which previously worked fine in the editor.  As of a recent update, however, it fails to load with the following console errors:

> [Error] TypeError: undefined is not an object (evaluating 'material.specular.setHex')
> 	parse (three.module.js:40084)
> 	parseMaterials (three.module.js:41083)
> 	parse (three.module.js:40721)
> 	handleJSON (Loader.js:598)
> 	(anonymous function) (Loader.js:333)

> [Error] ReferenceError: Cannot access uninitialized variable.
> 	(anonymous function) (three.module.js:40716)
> 	(anonymous function) (three.module.js:36133)
> 	onImageLoad (three.module.js:36816)

Looking at the code, it looks like the issue stems from an instance of MeshToonMaterial which has a specular parameter in its serialized data, but specular appears to have been removed from the MeshToonMaterial class.

The serialized material in question is:
"{\"uuid\":\"86936197-6FFA-4E61-B36E-9CEC7890DFB1\",\"type\":\"MeshToonMaterial\",\"color\":15986151,\"emissive\":0,\"specular\":1118481,\"shininess\":30,\"depthFunc\":3,\"depthTest\":true,\"depthWrite\":true,\"stencilWrite\":false,\"stencilWriteMask\":255,\"stencilFunc\":519,\"stencilRef\":0,\"stencilFuncMask\":255,\"stencilFail\":7680,\"stencilZFail\":7680,\"stencilZPass\":7680}"

**Comment by sir-aureus** [comment]
Modifying the exported json file of the scene and reimporting is a viable workaround, but not something someone would think of without being able to read and understand the errors and the code that generated the errors.

**Comment by Mugen87** [comment]
Since `r118` the toon material does not support `shininess` and `specular/specularMap` anymore, see #19722. These properties were originally present since `MeshToonMaterial` was derived from `MeshPhongMaterial` at the beginning.

These changes are noted in the migration guide however it would be possible to handle such import problems more gracefully in `MaterialLoader.parse()`. E.g. instead of:
```js
if ( json.specular !== undefined ) material.specular.setHex( json.specular );
```
it could be:
```
if ( json.specular !== undefined && material.specular !== undefined ) material.specular.setHex( json.specular );
```

**Comment by Mugen87** [comment]
BTW: Here is a live example demonstrating the runtime error: https://jsfiddle.net/heowdn1g/1/
