### ISSUE TITLE
GLTFLoader unqiue name dedupe issue

### ISSUE THREAD

**Issue by drcmda** [mrdoob/three.js#20520]
It looks like a recent change that affects GLTFLoader dedupes names wrong, adding additional indices which is a hard breaking change.

Previously:

```jsx
function Sheep(props) {
  const { nodes, materials, animations } = useGLTF('/sheep.glb')
  return (
    <group {...props}>
      <group position={[0, -19.998, 0]} rotation={[0, 0, 1.5]} scale={[3, 3, 3]}>
        <primitive object={nodes.Spine} />
        <skinnedMesh
          material={materials.Hoof}
          geometry={nodes.Plane_0.geometry}
          skeleton={nodes.Plane_0.skeleton}
        />
        <skinnedMesh
          material={materials.Fur}
          geometry={nodes.Plane_1.geometry}
          skeleton={nodes.Plane_1.skeleton}
        />
        <skinnedMesh
          material={materials.Face}
          geometry={nodes.Plane_2.geometry}
          skeleton={nodes.Plane_2.skeleton}
        />
      </group>
    </group>
  )
}
```

current version:

```jsx
function Sheep(props) {
  const { nodes, materials, animations } = useGLTF('/sheep.glb')
  return (
    <group {...props}>
      <group position={[0, -19.998, 0]} rotation={[0, 0, 1.5]} scale={[3, 3, 3]}>
        <primitive object={nodes.Spine} />
        <skinnedMesh
          material={materials.Hoof}
          geometry={nodes.Plane_0.geometry}
          skeleton={nodes.Plane_0.skeleton}
        />
        <skinnedMesh
          material={materials.Fur}
          geometry={nodes.Plane_1_1.geometry}
          skeleton={nodes.Plane_1_1.skeleton}
        />
        <skinnedMesh
          material={materials.Face}
          geometry={nodes.Plane_2_2.geometry}
          skeleton={nodes.Plane_2_2.skeleton}
        />
      </group>
    </group>
  )
}
```

the jsx is just for easier illustration, "nodes" is just a collection of meshes. so in the scene that the gltfloader returns you'll find meshes named Plane_0, and so on.

notice how it doubles the index (Plane_0, Plane_1_1, Plane_2_2), which it doesn't have to and didn't do before. that means all apps relying on the old name break when updating threejs. 

i've seen this in pretty much all cases, but here's the glb from the example above: https://www.dropbox.com/s/jrrmgy1306b8e81/sheep.glb?dl=0

**Comment by donmccurdy** [comment]
Fixed in https://github.com/mrdoob/three.js/pull/20504. However, note that the deduping method may still cause some parts of a group (mesh primitives) to end up with different indices appended to their names than they had before this release.
