### ISSUE TITLE
#ffffff hex notation for Colors

### ISSUE THREAD

**Issue by jordaneast1** [mrdoob/three.js#20531]
Is there a reason Three does not use the #ffffff syntax for it's color hex values, like in CSS? It would be super useful if Three.Color could recognise this format as well, it gets tedious to add 0x, as many browsers, image editors and IDE's ( I use VSCode) all mostly use the # syntax.

Not a huge problem but would be a nice to have!

**Comment by Mugen87** [comment]
Hex color notation should already work, see https://jsfiddle.net/dbgaLzsq/.

**Comment by jordaneast1** [comment]
ahh thank you!! I obviously didnt try hard enough haha. And I didnt read far enough down the Color doc... thanks

**Comment by mrdoob** [comment]
@jordaneast1 please, do not create an issue and ignore the template again.
