### ISSUE TITLE
Incorrect intersection point with scaled mesh

### ISSUE THREAD

**Issue by pakhuta** [mrdoob/three.js#20550]
**Describe the bug**

Raycaster calculate different points of object intersection depends on object scale and camera size.

**Steps to reproduce the behavior:**
1. In provided live example I created `CircleBufferGeometry` and put it to scene.
1. Find the point of intersection at some mouse coordinate.
1. Then I set circle mesh scale as `2`.
1. Then I again find the point of intersection at the same mouse coordinate.

**Actual behavior**

Point of intersection of circle mesh are different:
- `x: -0.11896542449286218, y: 0.1189654244928623` the first time:       
- `x: -0.1189654244928622,   y: 0.118965424492862` the second time: 

***Live example***

https://stackblitz.com/edit/js-7ygwkb?devtoolsheight=33&file=index.js

**Expected behavior**

Point of intersection of circle mesh in both cases should be the same

**Screenshots**
<img width="1790" alt="Screen Shot 2020-10-22 at 20 19 10" src="https://user-images.githubusercontent.com/19973665/96907478-f2c2a780-14a3-11eb-9ebb-632cd0089201.png">

**Additional info:**
In particular provided example value of `window.innerWidth` and `window.innerHeight` also have influence on the result. For example in this fork https://stackblitz.com/edit/js-jqwfwu?devtoolsheight=33&file=index.js mesh scale changed to `1.5` and point of intersection if both cases are equal.
But if you change the size of "window" they become different.
![size_1080p](https://user-images.githubusercontent.com/19973665/96908693-a4160d00-14a5-11eb-8ab5-7bf4b7239c43.gif)

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: 0.121.1

**Comment by Mugen87** [comment]
It seems what you are seeing in the console is the result of floating point inaccuracies which are inevitable when computing with floats.

**Comment by pakhuta** [comment]
My perplexity was related to influence of mesh scale on the result, but now I understood: it's because I use OrthographicCamera where can say that mouse coordinates === intersection coordinates. But in common terms it's not.
Thank you.
