### ISSUE TITLE
Color.getHexString() produces unexpected output

### ISSUE THREAD

**Issue by Malte-Hansen** [mrdoob/three.js#20552]
**Describe the bug**

Using the getHexString() function of the threejs Color objects yields unexpected (wrong?) results.

**To Reproduce**

***Code***

```js
    const blue = new THREE.Color(0, 0, 255); //blue
    console.log("Blue as object: ", blue); // still blue
    console.log("Blue as hex string: ", blue.getHexString()); // yields 00fe01, which represents a bright green
```

***Live example***

* [Demo with latest release](https://jsfiddle.net/62uk3nr1/)

**Expected behavior**

In this example I would expect the resulting string to be "0000ff".

**Screenshots**

![Capture](https://user-images.githubusercontent.com/38311128/96956844-6fcc3c00-14f9-11eb-8891-3245135a1890.PNG)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [r119]

**Comment by gkjohnson** [comment]
> ```js
> const blue = new THREE.Color(0, 0, 255); //blue
> ```

If you're passing R, G, and B arguments to `Color` they must be in the range [ 0, 1 ]. Alternatively you can pass a hex value to color directly:

```js
blue = new THREE.Color( 0, 0, 1 );
blue = new THREE.Color( 0x0000ff );
```

**Comment by Malte-Hansen** [comment]
In my case, printing the object did not help me find the cause of the problem. It seemed so obvious that 255 is a valid value.
Thanks a lot for the clarification! I think this is still quite unusual but I can see that changing this is not sensible and that there are plenty of alternative formattings available.
