### ISSUE TITLE
Multi-material instanced meshes don't work on Mac (all browsers!)

### ISSUE THREAD

**Issue by Vanilagy** [mrdoob/three.js#20559]
**Describe the bug**

InstancedMeshes with multiple materials don't work properly on Mac; only the first material is renderered and all others are ignored (invisible). Multi-material non-instanced meshes work just fine. The bug is present on Safari, Chrome and Firefox. It works flawlessly on Windows.

**To Reproduce**

1. Go to https://jsfiddle.net/xm538ato/26/ using a Mac
2. Click on Run
3. The output canvas should show a single, red triangle. In reality, the mesh consists of a red AND a green triangle, but only the red triangle is showing. It should look something like:
![image](https://user-images.githubusercontent.com/1696106/97105746-aeaaef00-16bd-11eb-826f-879c9a94ca7b.png)

***Code***

```js
let renderer = new THREE.WebGLRenderer();
renderer.setSize(256, 256);
document.documentElement.appendChild(renderer.domElement);

let camera = new THREE.PerspectiveCamera(60, 1);
let scene = new THREE.Scene();

let geometry = new THREE.Geometry();
geometry.vertices.push(
	new THREE.Vector3( -1,  1, 0 ),
	new THREE.Vector3( -1, -1, 0 ),
	new THREE.Vector3(  1, -1, 0 ),
	
	new THREE.Vector3( 0,  2, 0 ),
	new THREE.Vector3( 0, 0, 0 ),
	new THREE.Vector3(  2, 0, 0 ),
);
let f1 = new THREE.Face3(0, 1, 2);
let f2 = new THREE.Face3(3, 4, 5);
f2.materialIndex = 1;
geometry.faces.push(f1, f2);

let materials = [new THREE.MeshBasicMaterial({color: 0xff0000}), new THREE.MeshBasicMaterial({color: 0x00ff00})];

let mesh = new THREE.InstancedMesh(geometry, materials, 1);
scene.add(mesh);
mesh.setMatrixAt(0, new THREE.Matrix4());

camera.position.z = 5;
renderer.render(scene, camera);
```

***Live example***

https://jsfiddle.net/xm538ato/26/

**Expected behavior**

Both a red and green triangle should be showing, as such:
![image](https://user-images.githubusercontent.com/1696106/97105803-13fee000-16be-11eb-9621-d5b022cf5e75.png)
This is the image shown on all Windows and Android browsers, as well as on iOS Safari.

**Platform:**

 - Device: Desktop
 - OS: Mac OS X Yosemite 10.10.5 (but also broken on Catalina)
 - Browser: Chrome, Firefox, Safari
 - Three.js version: r121

**Comment by Mugen87** [comment]
Your fiddle works as expected on my iMac with macOS 10.15.7 with latest Chrome, Firefox and Safari.

I suspect this is a device/driver issue. Please report this to issue to Apple/WebKit instead.
