### ISSUE TITLE
MeshPhysicalMaterial rendering is strange when flatShading is on.

### ISSUE THREAD

**Issue by bianyunzhi95** [mrdoob/three.js#20561]
MeshPhysicalMaterial rendering is strange when flatShading is on. MeshStandardMaterial is the same.

Here is screenshot.
![image](https://user-images.githubusercontent.com/42105279/97147326-5569bb00-17a4-11eb-972b-dc11b625fcc0.png)

Here is screenshot of wireframe.
![image](https://user-images.githubusercontent.com/42105279/97147600-b6918e80-17a4-11eb-95c1-271c9de23091.png)

Is this expected behavior?

 - Device: Desktop + Mobile
 - OS: Windows + MacOS + iOS
 - Browser: Chrome + Firefox + Safari
 - Three.js version: r120

**Comment by Mugen87** [comment]
And chances to demonstrate this issue with a live example?

**Comment by mrdoob** [comment]
Closing this until a live example is provided.

**Comment by bianyunzhi95** [comment]
https://jsfiddle.net/57nvgdhr/15/

I found that it happens with orthographic camera with large zoom. Could you tell me what the origin of this issue is and how we can fix this, please? Thank you.
