### ISSUE TITLE
VideoTexture got poor performance in iOS 14, but fine in iOS 13. 

### ISSUE THREAD

**Issue by LoS-Light** [mrdoob/three.js#20560]
**Describe the bug**
VideoTexture got poor performance in iOS 14, but fine in iOS 13. 

**To Reproduce**
Navigate to official demo: https://threejs.org/examples/?q=pano#webgl_video_panorama_equirectangular
or my demo: https://storage.googleapis.com/test_unity_360/Unity360BVR/index_blend_4k.html
Run these demo on both iOS 14 and iOS 13.

**Expected behavior**
These demo should run smoothly, but now runs in low fps and the phone became very hot in iOS 14.
In addition, console shows this warning: THREE.WebGLRenderer: OES_texture_float_linear extension not supported.

**Platform:*
 - Device: [Mobile]
 - OS: [iOS 13, iOS 14]
 - Browser: [Chrome, Safari]
 - Three.js version: [r121]

**Comment by mrdoob** [comment]
Wouldn't you think that this is a iOS regression and should be reported to Apple instead?

**Comment by LoS-Light** [comment]
Ok. I will report it to Apple.
Thank you for your reply.
