### ISSUE TITLE
Grid/line flickering on ThreeJS paint example

### ISSUE THREAD

**Issue by dxdc** [mrdoob/three.js#20573]
**Describe the bug**

Grid/line flickering in ThreeJS default WebXR example

**To Reproduce**

- Use Oculus Quest (v1)
- Use Roomscale guardian/boundary. Not sure if it matters, I only did a 3ftx3ft boundary.
- Use Oculus Browser
- Open https://threejs.org/examples/webxr_vr_paint.html
- Go into "Immersive" mode

***Live example***

* https://threejs.org/examples/webxr_vr_paint.html

**Screenshots**

When looking around (especially at floor), very bad line flicker is observed. See attached video.

[cut.mp4.zip](https://github.com/mrdoob/three.js/files/5452157/cut.mp4.zip)

**Comment by dxdc** [comment]
(This is easily to reproduce on any Oculus Quest. Running latest software on Quest with all applications up to date.)

**Comment by Mugen87** [comment]
Related discussion at the forum: https://discourse.threejs.org/t/grid-helper-lines-flicker-on-oculus-quest/20164

I'm afraid this is a device issue and not fixable on `three.js` level.

**Comment by dxdc** [comment]
@Mugen87 Thanks - how do you know it's a device issue and not a frame rate issue? Frame rate mismatches can cause flickering and per the ThreeJS docs setAnimationLoop must be used instead of requestAnimationFrame for webXR content. Wondering about some approach like this:

- https://stackoverflow.com/questions/11285065/limiting-framerate-in-three-js-to-increase-performance-requestanimationframe

Have you been able to reproduce on an Oculus Quest?

**Comment by Mugen87** [comment]
Closing since this issue is unrelated to `three.js`. Please proceed the discussion at the forum.
