### ISSUE TITLE
Docs: Inline property word-space style problem.

### ISSUE THREAD

**Issue by gonnavis** [mrdoob/three.js#20584]
**Describe the bug**

I'm confused in a moment by the docs because white space between `<span>` and `text` is ignored.
Not sure what's the best way to solve this problem, add `margin-right` or `&nbsp`, etc?

**To Reproduce**

1. Go to https://threejs.org/docs/index.html#examples/en/controls/OrbitControls
2. Search `.autoRotateSpeed`
3. See error

**Screenshots**

![QQ截图20201030015534](https://user-images.githubusercontent.com/10785634/97613280-7441a900-1a53-11eb-96f2-85343ab58051.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [r122]

**Comment by Mugen87** [comment]
Looks like the documentation page does not use the markup correctly. Something like:
```
[property:Boolean autoRotate]
```
should not be used within text.

**Comment by gonnavis** [comment]
I guess the main purpose is to use the auto-linking function，then hilighting and style-unification。
All reasonable。

**Comment by Mugen87** [comment]
Solved via cf0b35d65304d9c37f116a872a650473c78d1e6c.
