### ISSUE TITLE
GLTFLoader UV import bug

### ISSUE THREAD

**Issue by SoundAndColour** [mrdoob/three.js#20590]
Imported UVs are incorrect for both gltf & glb.

**Exported with** 
Blender & Cinema4D exporter

**Imported with**
r122

**Tested against**
https://nme.babylonjs.com/ shows correct UVs
Importing with three's OBJLoader shows correct UVs

<br><br>

THREE Editor:

![THREE_Editor](https://user-images.githubusercontent.com/73383855/97721095-50b94580-1ac9-11eb-80f5-65799bf07822.jpg)

BABYLON Node Editor:

![Babylon_NodeEditor](https://user-images.githubusercontent.com/73383855/97720996-354e3a80-1ac9-11eb-9998-312c6517425c.jpg)

**Comment by Mugen87** [comment]
Please share the glTF asset in this thread. Otherwise it's not possible to investigate the issue.

**Comment by SoundAndColour** [comment]
Sure, thanks for taking the time :)

[car.zip](https://github.com/mrdoob/three.js/files/5467072/car.zip)

**Comment by donmccurdy** [comment]
It looks like the texture is not embedded in the glTF file here? If that's the case, and you're loading the texture separately and then applying it, be sure to set `texture.flipY = false` to match the glTF UV coordinate space.

See: https://threejs.org/docs/#examples/en/loaders/GLTFLoader

**Comment by SoundAndColour** [comment]
Oh my... that does the trick. I'm terribly sorry :/

Thanks for your help!
