### ISSUE TITLE
About Implement Pointer Events on OrbitControls

### ISSUE THREAD

**Issue by cgusercom** [mrdoob/three.js#20594]
When I was using the new version of three.js today, I found that Pointer Events was implemented for OrbitControls.[#20161](https://github.com/mrdoob/three.js/pull/20161#issue-472145656)
But it has a bad effect on me, when I need to use the mousedown event.
If I use OrbitControls to make it listen to "renderer.domElement",and I  listen to "mousedown" on "renderer.domElement" again, it will not execute。
So I checked the current three.js and made this change.And I did an experiment:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      const canvas = document.createElement("canvas");
      canvas.width = 500;
      canvas.height = 500;
      const ctx = canvas.getContext("2d");
      ctx.fillStyle = "#f00";
      ctx.fillRect(0, 0, 500, 500);
      document.body.appendChild(canvas);
      canvas.addEventListener("pointerdown", (event) => {
        console.log("pointerdown 1");
        // Only if you annotate this line, the mousedown event will be executed
        event.preventDefault();
      });
      canvas.addEventListener("mousedown", () => {
        console.log("mousedown");
      });
      canvas.addEventListener("pointerdown", () => {
        // Will always execute
        console.log("pointerdown 2");
      });
    </script>
  </body>
</html>
```
I found on mdn that not all browsers support Pointer Events,such as safari.[mdn: pointerdown_event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerdown_event)
Should I still use "mousedown" for better compatibility?

**Comment by Mugen87** [comment]
You have to use to Pointer Events when using `OrbitControls`. `mousedown` does not work anymore in this case.

**Comment by cgusercom** [comment]
> You have to use to Pointer Events when using `OrbitControls`. `mousedown` does not work anymore in this case.

Thank you for your answer, I am just out of compatibility considerations. I believe that more people will adjust OrbitControls for safari, at least I will. hahaha. . .

**Comment by arodic** [comment]
> You have to use to Pointer Events when using OrbitControls. mousedown does not work anymore in this case.

@Mugen87 @mrdoob we can implement controls in such way that it does not break mouse events. If instead of `event.preventDefault()` in OrbitControls we can set:
`this.domElement.style.touchAction = 'none';` on `"pointerdown"` and
`this.domElement.style.touchAction = '';` on `"pointerup"`

For multi-touch events it is a little bit trickier because you have to to do the later only when the last remaining pointer is up. I tried this in all controls and appears to be working fine without preventing any mouse events.

**Comment by arodic** [comment]
Oh, keep forgetting Safari :(
