### ISSUE TITLE
ThreeJS not working on recent iPad when password protected

### ISSUE THREAD

**Issue by GSORF** [mrdoob/three.js#20595]
**Describe the bug**

Recently I noticed a weird issue on the recent iPad (e.g. iPadOS 14) while working on a client project. The ThreeJS examples are working fine using Firefox, Safari and Chrome when the website is not password protected. But if the website is using password protection (using htaccess and htpasswd files), the samples are not working anymore (i.e. the website remains black and no 3D models are shown). I have set up an example website using 1.) no password and 2.) with a password so that you can reproduce it yourself. Unfortunately I do not have an iPad available and can therefore only work with feedback from my client (which is very unfortunate, I know...). When navigating to the website from Windows, Android and MacOSX Desktop OS using for example the Firefox browser, everything works as expected. The issue seems to be merely related to iPads.

**To Reproduce**

1. a) Navigate to the ThreeJS examples on your website using Firefox on the iPad (you can use my website for the test, go to: http://gsorf.lwtv.de/ThreeJS_noPassword/examples/)
1. b) Click on one of the following examples: **webgl_animation_cloth**, **webgl_decals**, **webgl_loader_collada_skinning**
1. c) You should be able to see most of the examples working
2. a) Navigate to the ThreeJS examples on your website using Firefox on the iPad (you can use my website for the test, go to: http://gsorf.lwtv.de/ThreeJS_Password/examples/)
2. b) Type in the following authentication data when promted: Username: "**threejs**", Password: "**threejs**"
2. c) Click on one of the following examples: **webgl_animation_cloth**, **webgl_decals**, **webgl_loader_collada_skinning**
2. d) See error (blank screen)

***Code***

The used .htaccess file is as follows
```js
AuthType Basic
AuthName "restricted area"
AuthUserFile ./.htpasswd
require valid-user
```

The used .htpasswd file is as follows
```js
threejs:{SHA}PVKmSMJBzRzJwDnGqWgN92PcDc4=
```

Both files are placed in the "ThreeJS_(No)Password" directory.

***Live example***

* [Working](http://gsorf.lwtv.de/ThreeJS_noPassword/examples/)
* [Not Working](http://gsorf.lwtv.de/ThreeJS_Password/examples/)

**Expected behavior**

Instead of seeing a ThreeJS example, you should only see a blank screen. I seems like the website is stuck in a loading loop.

**Platform:**

 - Device: [Mobile]
 - OS: [iPadOS]
 - Browser: [Chrome, Firefox, Safari]
 - Three.js version: [dev, r122]

**Comment by mrdoob** [comment]
Please, report this to Apple first.
If Apple concludes the bug is in Three.js then we can reopen this.
