### ISSUE TITLE
the Static Methods .parse of KeyframeTrack not exist

### ISSUE THREAD

**Issue by x1911** [mrdoob/three.js#20599]
code like this
```
const j = THREE.KeyframeTrack.toJSON( i )  
           
const t = THREE.KeyframeTrack.parse( j )
```
it shows error
" THREE.KeyframeTrack.parse is not a function"

In doc it shows this method
https://threejs.org/docs/#api/en/animation/KeyframeTrack

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, iOS]
 - Browser: [Chrome]
 - Three.js version: [dev, r122]

**Comment by gkjohnson** [comment]
It looks like the docs are out of date and the parse function is no longer exposed as of this commit: https://github.com/mrdoob/three.js/commit/f8965d4621517b0c6c5bf9828df15e4fe0f82732#
