### ISSUE TITLE
Stability of tags in this repository

### ISSUE THREAD

**Issue by paulmasson** [mrdoob/three.js#20591]
@mrdoob I'm gearing up to provide a regular custom build for the international open source project [SageMath](https://www.sagemath.org/), for which I am the main author of its Three.js viewer. Because this is an academic project, I would like to make the entire process completely reproducible at any time for verification of the build. I am hoping to base the process off tags but have noticed a problem with them.

Looking back over the last ten versions, six of them have had modifications after the initial release: one modification for r116, r119, r120 and r121; two modifications for r113; and three modifications for r118. In two cases the modification happened on the same day (r113 and r121); in two cases the modifications happened a day later (r116 and r119); in one case three days later (r118); and in the final case (r120) four days later. Since all of the modifications appear to be tagged with the original version number, I can only assume you are deleting GitHub tags and reusing them with each update, but correct me if I am wrong. This unfortunately means that the tags currently are not unique indicators of the state of the repository at each initial release.

The question is: do you have a strict time limit beyond which you will not modify a release, but instead wait for the next? I can easily wait until the release is actually stable to perform the custom build, but I need to know how long to wait.

Thank you for your time in answering this question!

**Comment by mrdoob** [comment]
> Since all of the modifications appear to be tagged with the original version number, I can only assume you are deleting GitHub tags and reusing them with each update, but correct me if I am wrong.

That's correct.

> The question is: do you have a strict time limit beyond which you will not modify a release, but instead wait for the next?

Releases are usually the last wednesday of the month.
It's not strict rule but... if we missed something, we update the release for up to a week.
