### ISSUE TITLE
Fix Box3 expandByObject issue 

### ISSUE THREAD

**Issue by pepitoxxx** [mrdoob/three.js#20603]
**Describe the bug**

The latest optimize for .expandByObject() #17940 (#17940) in r111 has caused an issue for the BoxHelper update() function. The boundingbox property will be set by expandByObject() at first and would not be updated afterwards.
If mesh attributes are updated dynamically, the BoxHelper will not reflect this change without explicitly call mesh.geometry.boundingBox= null or mesh.geometry.computeBoundingBox() before BoxHelper.update()

**To Reproduce**

1. create BufferGeometry with position BufferAttribute
2. create Mesh from this BufferGeometry
3. create BoxHelper from this Mesh
4. update position BufferAttribute during render loop

***Live example***

Here a jsfiddle to illustrate the problem:
https://jsfiddle.net/2b1sLun5/29/
A check box allowing to solve the problem is proposed but is not, in my opinion, an acceptable answer.

**Expected behavior**

BoxHelper should be updated according to the mesh geometry without explicitly compute or reset mesh geometry bounding box

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome, Firefox]
 - Three.js version: [r121]

**Comment by wal0x** [comment]
I had the same issue after updating thrrejs with a mesh with changing geometry... The only solution I had is to nullify the bounding box as you said, which is a bit of a hack IMHO, giving qlso the fqct thqt it was working before.

**Comment by Mugen87** [comment]
> The only solution I had is to nullify the bounding box as you said, 

This is not the correct workflow. If you create a geometry from scratch, bounding boxes are `null` and will be automatically computed by the engine. However if you change the geometry, it's your responsibility to recompute the bounding volumes, too.

#17940 just made this topic more clear. So the proper fix is to call `computeBoundingBox()` and `computeBoundingSphere()`. If you miss the latter one, view frustum culling might not work, too.

https://jsfiddle.net/1kn5h3cg/3/

BTW: This code is not valid:
```js
posAttribute.array = new Float32Array(newPos);
```
The `array` attribute is considered to be read-only. You should always change the values of the existing array.

**Comment by Mugen87** [comment]
The documentation says:

> If you change the position data values after the initial render, you may need to call `.computeBoundingSphere()` in order to recalculate the geometry's bounding sphere.

**Comment by Mugen87** [comment]
Maybe the following makes it more generic:

> If you change the position data values after the initial render, you may need to recompute bounding volumes so other features of the engine like view frustum culling properly or helpers work.

**Comment by pepitoxxx** [comment]
Ok, so nothing concernant computeBoundingBox()...

**Comment by Mugen87** [comment]
Check out the PR, I've considered `computeBoundingBox()` in the code example.

**Comment by pepitoxxx** [comment]
Tanks for your reactivity. I think this topic can be closed.

**Comment by Mugen87** [comment]
That happens automatically when the PR gets merged 👍 .
