### ISSUE TITLE
PLYLoader : RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by daker** [mrdoob/three.js#20622]
**Describe the bug**

RangeError when displaying a .ply mesh

***Stack***

```js
RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (<anonymous>)
    at binaryRead (PLYLoader.js:418)
    at binaryReadElement (PLYLoader.js:441)
    at parseBinary (PLYLoader.js:492)
    at PLYLoader.parse (PLYLoader.js:516)
    at Object.onLoad (PLYLoader.js:61)
    at XMLHttpRequest.<anonymous> (three.module.js:36513)
(anonymous) @ PLYLoader.js:71
```

***Live example***

Mesh example [plyloader_bug.zip](https://github.com/mrdoob/three.js/files/5490945/plyloader_bug.zip)

**Expected behavior**

Mesh is displayed on the 

**Platform:**

 - Device: all
 - OS: all
 - Browser: all
 - Three.js version: all

**Comment by Mugen87** [comment]
I can confirm the bug. Besides, the import does work with Blender and Sketchfab.

**Comment by Mugen87** [comment]
Um, it seems the loader has problem to compute the correct header length in your case. It should be 528 bytes but it only outputs 518. 

I have notice that when I remove a specific in the header, the file can be loaded. The comment looks like so:
> comment TextureFile C:\ProgramData\TW\AcqAltair\temp\06864e88768dfdda70fc8b9ed0949c2e[2020-10-22_11-15-22]\云平台_测试_Maxillary_[2020-10-22_11-15-22]_texture.jpg

The length is computed by just evaluating the `length` property of the string. It does not seem to work in this case. Using `Blob` seems to fix the issue.

**Comment by Mugen87** [comment]
I suppose this is related  to the octal escape sequence which is represtend by `\06864e88768dfdda70fc8b9ed0949c2e`. The are allowed in strings but not in template strings. https://jsfiddle.net/4ergnuoq/ 

I suppose they influence the length computation via `String.length`.
