### ISSUE TITLE
THREE.PointerLockControls(camera).getObject().position.set(x, y, z);This API (x, y, z)cannot set negative numbers

### ISSUE THREAD

**Issue by tangdou369098655** [mrdoob/three.js#20629]
***Code***

```js
control1 = new THREE.PointerLockControls(camera); 
// control1.getObject().position.set(22, 10, 48); // this can run well
control1.getObject().position.set(1999, 10, -900); // this can not run well
scene.add(control1.getObject());
```
Three.js version:  103dev

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests. 

GitHub is for feature requests and bugs only. And you have not demonstrated a bug so far.

**Comment by tangdou369098655** [comment]
> Please use the [forum](https://discourse.threejs.org/) for help requests.
> 
> GitHub is for feature requests and bugs only. And you have not demonstrated a bug so far.

thank you     
The problem has been solved. I sent it to the wrong place

so sorry
