### ISSUE TITLE
 Object3D.clone The mesh material array is copied？

### ISSUE THREAD

**Issue by vblegend** [mrdoob/three.js#20634]
Object3D.clone The mesh material array is copied？

**Comment by vblegend** [comment]
var obj = loadobj(.....);

var obj2 = obj.clone();
//obj.children[0].material  is a material array.
consolt.log(obj.children[0].material === obj2.children[0].material )// true

**Comment by vblegend** [comment]
This results in modifying the texture of one model and changing the texture of the other

**Comment by Mugen87** [comment]
If you are copy a mesh, they will share the same material and geometry. If you don't want that, you have to clone materials and or geometries separately.

**Comment by Mugen87** [comment]
Please use the forum or chat if you have more questions about that topic.

**Comment by vblegend** [comment]
thank you

> Please use the [forum](https://discourse.threejs.org/) or [chat](https://discordapp.com/invite/HF4UdyF) if you have more questions about that topic.
