### ISSUE TITLE
Property `clear` does not exist on type `Object3D`

### ISSUE THREAD

**Issue by alexpreynolds** [mrdoob/three.js#20631]
**Describe the bug**

When calling the `clear` method on an instance of `Object3D`, a TypeScript error is returned stating that the `clear` property does not exist on type `Object3D`. 

However, this method is specified in the documentation (https://threejs.org/docs/#api/en/core/Object3D) and appears to be described in the source code (https://github.com/mrdoob/three.js/blob/dev/src/core/Object3D.js#L373-L387). 

Adding `clear() : this` to the `Object3D` type definition and calling the `clear()` method on an Object3D instance returns the error that `clear` is not a function, even though it appears to be defined in source.

**To Reproduce**

```jsx
import * as THREE from 'three';
...
this.cubePointStyledGroup = new THREE.Object3D();
...
// set up scene, camera, `cubePointStyledGroup` material/geometry/meshes, add group to scene, etc.
...
// in an event handler, for example, try to remove the child objects of `cubePointStyledGroup`
try {
  this.cubePointStyledGroup.clear();
}
...
```

Console reports the following error on the call to `clear()`:

```
Property 'clear' does not exist on type 'Object3D'.  TS2339
```

***Investigation***

Adding the following to the `Object3D.d.ts` file allowed the app to build:

```
  /**
   * Removes all child objects
   */
  clear() : this;
```

However, calling the `clear()` method then raises a `TypeError` exception:

```
TypeError: this.cubePointStyledGroup.clear is not a function
```

**Expected behavior**

Because the `clear()` method appears to be in the `Object3D` source and documentation, calling it should ideally remove/release the children in this group (geometry, material, mesh, etc.), unless it is preferred that other methods should be used, instead.

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: r122

**Comment by makc** [comment]
```js
// just
this.cubePointStyledGroup.children.length = 0;
// or, if you need events
while(this.cubePointStyledGroup.children.length) {
    this.cubePointStyledGroup.remove(
        this.cubePointStyledGroup.children[
            this.cubePointStyledGroup.children.length -1
        ]
    );
}
```

**Comment by makc** [comment]
wait a sec
> appears to be described in the source code (https://github.com/mrdoob/three.js/blob/dev/src/core/Object3D.js#L373-L387).

it is actually there 😶

**Comment by alexpreynolds** [comment]
I think `THREE.Scene` and `THREE.Object3D` are two different classes? (Unless I'm missing something?)

**Comment by Mugen87** [comment]
`THREE.Scene` is derived from `THREE.Object3D`. So `clear()` should also work with scenes.

**Comment by mrdoob** [comment]
> Adding the following to the `Object3D.d.ts` file allowed the app to build:

It should be there already:

https://github.com/mrdoob/three.js/blob/e1ef121363f15876070731561d4c06a4f4e6a311/src/core/Object3D.d.ts#L319-L322

**Comment by alexpreynolds** [comment]
Hmm. I cleared out my modules and reinstalled them, and that seems to fix this. I apologize for filing this issue.

**Comment by jimver04** [comment]
In threejs v119 there is no "clear :" for Object3D, however in v124 there is as below.
The problem is that in reference guide there is no version number when each function was added. Perhaps to add it as a future characteristic ?

```
clear: function clear() {
			for (var i = 0; i < this.children.length; i++) {
				var object = this.children[i];
				object.parent = null;
				object.dispatchEvent(_removedEvent);
			}

			this.children.length = 0;
			return this;
		},
```

**Comment by mrdoob** [comment]
Or, you can check the docs for r119 instead:
https://raw.githack.com/mrdoob/three.js/r119/docs/
