### ISSUE TITLE
Vertices are missing when running example from the documentation [MacOS, Safari]

### ISSUE THREAD

**Issue by gramotei** [mrdoob/three.js#20640]
**Describe the bug**

Vertices are missing when running example from the documentation. You can see it from the screenshot. 

**To Reproduce**

1. I go to documentation - https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene

2. There is a link to example - https://jsfiddle.net/mkba0ecu/

3. You can see cube is broken and the warning appears: 

> THREE.WebGLRenderer: OES_texture_float_linear extension not supported

**Expected behavior**

The cube is fully visible

**Screenshots**

**r117** - works

<img width="400" alt="threejs-r117" src="https://user-images.githubusercontent.com/1360632/98450117-9a95d180-2142-11eb-865e-a0c7598d899e.png">

**r122** - doesn't work

<img width="400" alt="threejs-r122" src="https://user-images.githubusercontent.com/1360632/98450118-9e295880-2142-11eb-9131-a4a89600fc1c.png">

**Platform:**

 - Device: Desktop
 - OS: [MacOS]
 - Browser: [Safari 13.1.1]
 - Three.js version: [r122]

**Comment by Mugen87** [comment]
Can't reproduce this on macOS 10.15.7 with Safari 14.0. 

Have you turned on experimental WebGL 2 support in Safari?  Notice that `WebGLRenderer` uses a WebGL 2 rendering context since `r118`.

**Comment by gramotei** [comment]
@Mugen87, thanks! And yeah. It was enabled. it works when I either disable `WebGL2 experimental support` or use `WebGL1Renderer`.

**Comment by Mugen87** [comment]
Okay, then let's only open Safari related WebGL 2 issues when the implementation is actually stable.
