### ISSUE TITLE
MeshBasicMaterial reflection mapping is broken

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#20651]
So that it is not lost in discord: envMap is not being reflected correctly by MeshBasicMaterial (and probably Lambert too).

https://jsfiddle.net/hpox0a65/

![Screen Shot 2020-11-09 at 11 02 21 ](https://user-images.githubusercontent.com/242577/98527536-72f65480-227b-11eb-9f5b-04d0a8287ece.png)

whereas the same code works fine with Phong (and probably Standard) material:

https://jsfiddle.net/3mprbLc9/

![Screen Shot 2020-11-09 at 11 01 43 ](https://user-images.githubusercontent.com/242577/98527716-a638e380-227b-11eb-92e6-72a7ef048a54.png)

the root cause being vReflect not suitable for interpolation

**Comment by Mugen87** [comment]
Tessellating the plane seems also to mitigate the issue:

https://jsfiddle.net/e6utLhd0/1/

**Comment by makc** [comment]
> mitigates the issue:

![Screen Shot 2020-11-09 at 11 44 03 ](https://user-images.githubusercontent.com/242577/98531658-f1a1c080-2280-11eb-9872-0c830cf22cfc.png)

😂

**Comment by Mugen87** [comment]
https://jsfiddle.net/4ajuy0oc/

**Comment by makc** [comment]
![](https://lh3.googleusercontent.com/proxy/Lk7msdHUMlJqT65AXB99gDx4Fn-454dcmBrR95xiqZzHFZNQdBX7KKPCGmkbre-rwhkQ4UsnATyzUx9kHkJ2qSPLRTTFpP_O4ehCtVA-y0HeK0E33IsxD3l_fcM0oe2ojkhnvXKkIFDylgpIvlJcimfNwBv0XLo9wbgGpw)

**Comment by mrdoob** [comment]
Looks like `envMap` somehow doesn't have perspective correct texture mapping?
https://webglfundamentals.org/webgl/lessons/webgl-3d-perspective-correct-texturemapping.html

**Comment by makc** [comment]
doob well yes, you could say vReflect varying interpolation is not perspective correct. but world position is, so just passing word position and calculating reflecion vector from it (just like phong material does) solves the issue.

**Comment by makc** [comment]
mugen not sure why would you want to keep faster but broken code in there. you could as well remove envMap support from basic matrial just like you dont support normalMap there

**Comment by Mugen87** [comment]
> not sure why would you want to keep faster but broken code.

I  don't think the term "broken" is appropriate. The implemented was done on purpose and and the limitations should be clear similar to how Gouraud shading has its limitations. If not, one can consider to clarify the documentation.

**Comment by makc** [comment]
> clarify the documentation

by saying that it is... broken, intentionally? it does not work on 4 vertices quad, you had to make 2500 vertices before getting acceptable result, at which point it is questionable if the speed gain was not offset by doing extra 2496 vertices that you do not normally need.

but ok, in the end of the day it is your call

**Comment by makc** [comment]
Since the team is not interested in fixing this, I shall close it with a ~~fix~~ [hack](https://jsfiddle.net/09c7mojx/) for people who will run into this in the future.
