### ISSUE TITLE
node material examples are broken under webgl 1

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#20653]
I see this on mac firefox right now:

![Screen Shot 2020-11-09 at 12 18 51 ](https://user-images.githubusercontent.com/242577/98535137-e3a26e80-2285-11eb-89ff-63e113149da7.png)

**Comment by Mugen87** [comment]
Tested the Firefox 82.0.2 and macOS 10.15.7 without issues.

**Comment by Mugen87** [comment]
BTW: It would be nice if you would not delete the issue template but fill it out instead.

**Comment by makc** [comment]
ok well, this is osx 10.11.6, the code you have in your repo, the expected result is what you see. just tried different browser (chrome) with the same result:
![Screen Shot 2020-11-09 at 13 53 52 ](https://user-images.githubusercontent.com/242577/98543755-38001b00-2293-11eb-8d75-5cbcfbe3baa2.png)

maybe that extension is automagically enabled in webgl2 which is why you do not see any problems

**Comment by makc** [comment]
ok, some more input: same issue in https://threejs.org/examples/?q=node#webgl_materials_nodes so this is something about node materials, not mirror... weird, they used o work before I think

**Comment by Mugen87** [comment]
Any chances to update your OS to the latest version?

**Comment by makc** [comment]
I need new hardware for that. Even if I could, how does it help 3js? Or do you mean to say, webgl 1 is no longer supported?

**Comment by Mugen87** [comment]
> Even if I could, how does it help 3js?

Sometimes such issues are caused by GPU driver bugs. If you upgrade macOS, you also upgrade the GPU driver. In general, we want to avoid implementing fixes for GPU driver bugs.

In any event, I can reproduce the issue when using `WebGL1Renderer` and node material.
