### ISSUE TITLE
Use Loader With WebWorker to load the model, the image disappears

### ISSUE THREAD

**Issue by misitetong** [mrdoob/three.js#20661]
**Describe the bug**

Normally, using GLTFLoader to load the model in js does not cause any problems. But when I use webworker, I use GLTFLoader in the worker to load the model. I found that the model obtained in the onload function lacks pictures. After my analysis, I found that when this piece of picture information was loaded in the FILELoader inside GLTFLoader, it had disappeared in its onload function. The magic is that I can temporarily solve this problem through the onprogress method. I added a load stage judgment to onprogress, and then obtained the correct arraybuffer data from this event.

**To Reproduce**

1. use webWorker
2. use GLTFLoader
3. See error on GLTFLoader.onload()

***Code***

```js
// code goes here
function initGltf(gltfInfo) {
  new GLTFLoader().load(gltfInfo.url, (e) => {
    //I will get wrong data here
  }, (e) => {
    if (e.loaded === e.total) {
      let data = e.target.response
      //I will get right data here
    }
  })
}
```

**Expected behavior**

GLTFLoader.onload function can run well when i use webworker

**Screenshots**
![E780B82CBD181967D9C2B77E923A605F](https://user-images.githubusercontent.com/56953866/98652580-d1ecc400-2376-11eb-9013-6bc316bcc59d.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows, MacOS,]
 - Browser: [Chrome, Firefox]
 - Three.js version: [dev, r0.122.0]

**Comment by Mugen87** [comment]
At least with latest Chrome, `GLTFLoader` should use `ImageBitmapLoader` for loading textures.  Unlike `TextureLoader`, `ImageBitmapLoader` does work in a worker. 

It also has no dependency to `FileLoader`. Hence, I'm a bit irritated why you are mentioning this:

>  I found that when this piece of picture information was loaded in the FILELoader inside GLTFLoader

There is also no official web worker support for `GLTFLoader`, see https://github.com/mrdoob/three.js/issues/15090#issuecomment-431463709.

**Comment by misitetong** [comment]
I am sorry for my analysis, maybe there are some errors.I don't have a deep understanding of the source code. But the phenomenon I mentioned above does exist, how should I solve it.Can you help me ?

**Comment by misitetong** [comment]
> At least with latest Chrome, `GLTFLoader` should use `ImageBitmapLoader` for loading textures. Unlike `TextureLoader`, `ImageBitmapLoader` does work in a worker. It also has no dependency to `FileLoader`. Hence, I'm a bit irritated why you are mentioning this:
> 
> > I found that when this piece of picture information was loaded in the FILELoader inside GLTFLoader
> 
> Independently, there is no official web worker support for `GLTFLoader`, see [#15090 (comment)](https://github.com/mrdoob/three.js/issues/15090#issuecomment-431463709).

I am sorry for my analysis, maybe there are some errors.I don't have a deep understanding of the source code. But the phenomenon I mentioned above does exist, how should I solve it.Can you help me ?

**Comment by Mugen87** [comment]
@misitetong Please use the [forum](https://discourse.threejs.org/) for help requests. You can login with your GitHub account.
