### ISSUE TITLE
Slower OutlinePass starting in r116

### ISSUE THREAD

**Issue by canadaduane** [mrdoob/three.js#20660]
**Describe the bug**

Beginning with r116, the OutlinePass is quite a bit slower under certain circumstances. Like #19778 noted, VSMShadowMap appears to be one cause; however, it is not the only interaction causing slowdown (see 2nd repro github repo, below). I have been unable to isolate additional causes of the slowdown; however, if the cause is identified, the following repo can be used to confirm a solution.

**To Reproduce**

Steps to reproduce the VSMShadowMap-caused slowdown in r116:
1. Clone https://github.com/canadaduane/three-outline-slowdown
2. `yarn && yarn dev` and see slow framerate (around 45 fps on my MPB)
3. Edit `package.json` and use version `0.115.0` of three and speed is 60 fps.

Steps to reproduce non-VSMShadowMap (additional) slowdown in r116:
1. Clone https://github.com/relm-us/relm-experimental/tree/r116-slow-outlinepass
2. `yarn && yarn dev` and see slow framerate (around 40 fps on my MPB)
3. Edit `package.json` and use version `0.115.0` of three and speed is 60 fps.

(go to `src/world/creation.ts` to modify renderer, scene; go to `src/ecs/plugins/effects/Effects.ts` to modify OutlinePass params).

***Code***

```js
    this.outlinePass = new OutlinePass(
      new Vector2(window.innerWidth, window.innerHeight),
      scene,
      camera
    );
    this.outlinePass.visibleEdgeColor.set(0xffffff);
    this.outlinePass.hiddenEdgeColor.set(0x444444);
    this.outlinePass.edgeGlow = 0;
    composer.addPass(this.outlinePass);
```

***Live example***

See Repro steps.

**Expected behavior**

A small scene with only a few cubes should be able to render at 60fps with just one object included in OutlinePass.

**Screenshots**

none

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Firefox
 - Three.js version: r116

**Comment by Mugen87** [comment]
I get the following runtime error when opening `http://localhost:8080` using your second repo `r116-slow-outlinepass`.

> hecs-plugin-three.js:1 Uncaught ReferenceError: regeneratorRuntime is not defined
    at hecs-plugin-three.js:1
    at Module../node_modules/hecs-plugin-three/dist/hecs-plugin-three.js (hecs-plugin-three.js:1)
    at __webpack_require__ (hecs-plugin-three.js:1)
    at Module.<anonymous> (hecs-plugin-three.js:1)
    at __webpack_require__ (hecs-plugin-three.js:1)
    at ./node_modules/hecs-plugin-three/dist/hecs-plugin-three.js (hecs-plugin-three.js:1)
    at hecs-plugin-three.js:1
    at webpackUniversalModuleDefinition (hecs-plugin-three.js:1)
    at Object../node_modules/hecs-plugin-three/dist/hecs-plugin-three.js (hecs-plugin-three.js:1)
    at __webpack_require__ (bootstrap:921)

When comparing the official `OutlinePass` example from `r115` and `r116`, I can see no difference in FPS.

https://rawcdn.githack.com/mrdoob/three.js/r116/examples/webgl_postprocessing_outline.html
https://rawcdn.githack.com/mrdoob/three.js/r115/examples/webgl_postprocessing_outline.html

**Comment by mrdoob** [comment]
I can see no difference either...

**Comment by mrdoob** [comment]
@canadaduane If you don't see a performance difference in Chrome and/or Safari, you may want to report this to Mozilla instead.
