### ISSUE TITLE
RoundedBoxBufferGeometry is buggy

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#20665]
`RoundedBoxBufferGeometry` should render correctly for the default argument values.

```js
geometry = new RoundedBoxBufferGeometry(); // no args
```
![Screen Shot 2020-11-10 at 8 16 27 PM](https://user-images.githubusercontent.com/1000017/98753571-a8da2c80-2392-11eb-9a8e-150adb3b1c91.png)

//

`RoundedBoxBufferGeometry` should be a box with rounded edges. That means the six sides should have faces that are coplanar. That is, the vertex _positions_ are not correct.

```js
geometry = new RoundedBoxBufferGeometry( 10, 10, 10, 6, 2 ); // number of segments is even
```
![Screen Shot 2020-11-10 at 8 15 08 PM](https://user-images.githubusercontent.com/1000017/98753906-6fee8780-2393-11eb-8d6b-6a1ad45908ed.png)

//

UVs are not correct.

![Screen Shot 2020-11-10 at 8 14 40 PM](https://user-images.githubusercontent.com/1000017/98754013-b47a2300-2393-11eb-9143-3a965a1411a7.png)

//

The normals for the triangles in the six primary faces must be parallel to the coordinate axes. That is, the vertex _normals_ are not correct.

![Screen Shot 2020-11-10 at 8 40 01 PM](https://user-images.githubusercontent.com/1000017/98754579-066f7880-2395-11eb-99b3-e85e64aa1696.png)

 - Three.js version: [r.123dev]

/ping @gkjohnson If you want to have a look at this, that is fine with me. I am not going to pursue this.

**Comment by gkjohnson** [comment]
Yeah I noticed the normals weren't exactly right when I was working on it given how the box is generated but I think it's still a useful as a primitive. I don't think I'll be investing more time into this since I just wanted to get the UVs looking reasonable but thanks for bringing it up. If I think of a simple solution I may add it.

Regarding the particularly poor quality with an even segment number per side we could just enforce that the arguments be odd (add 1 if it's even) or document that it needs to be odd to get the expected look. If the rounded box is being generated from a segmented cube I'm not sure what the "right" thing to do for an even number of segments would be -- you want an even number of segments for the rounding corners on each side and one segment for the plane in the middle.

**Comment by gkjohnson** [comment]
@WestLangley thought of something 😁

#20666

![image](https://user-images.githubusercontent.com/734200/98761731-f05cba80-238a-11eb-9d92-5cbe865b9984.png)

**Comment by mrdoob** [comment]
@gkjohnson Does #20666 fix all the issues WestLangley reported here?

**Comment by WestLangley** [comment]
>Does #20666 fix all the issues WestLangley reported here?

It is better, but the default values are not fixed, and passing in 1 for segments is buggy.

Also, the bounding box is too small. It should be the same size as the equivalent `BoxBufferGeometry`.

I'd suggest reopening this, or creating a new issue.

**Comment by gkjohnson** [comment]
@mrdoob It should fix everything listed in the first post, yes.

@WestLangley 

> It is better, but the default values are not fixed, and passing in 1 for segments is buggy.

Can you explain a bit more? There is now special handling for when `segments === 1` which will cause it to be exactly the same as a cube (also oops typo on "we'r" 😁):

https://github.com/mrdoob/three.js/blob/b19cc35a01267ae87ba4e013ec6eb2010076ca90/examples/jsm/geometries/RoundedBoxBufferGeometry.js#L47-L54

Here's what I see now when using default values `new RoundedBoxBufferGeometry()`:

![image](https://user-images.githubusercontent.com/734200/98837426-cb526100-23f7-11eb-9a84-43ea0a2966de.png)

> Also, the bounding box is too small. It should be the same size as the equivalent BoxBufferGeometry. In other words, the vertex positions are still not correct.

The bounding box is slightly smaller -- this is probably not difficult to fix either. I'll look into addressing that.

**Comment by gkjohnson** [comment]
Fixed the total size issue in #20672.

Now afaik the remaining issue is if `radius` is more than half the half of any of the given sides:

![image](https://user-images.githubusercontent.com/734200/98839410-57658800-23fa-11eb-9a05-127cd852a7a7.png)

**Comment by WestLangley** [comment]
>Can you explain a bit more?

I suggest you do this so the default looks like a box with rounded edges:

```js
constructor( width = 1, height = 1, depth = 1, segments = 4, radius = 0.1 ) {
```

Also, I think setting 15 for `segments` in the example is overkill. Four to six should be adequate when using smooth normals.

**Comment by gkjohnson** [comment]
I've just changed the defaults in the other PR to what you suggested. I'll leave the segment count in the example up to @mrdoob -- lower segments counts can be noticeable in the box silhouette, though.

**Comment by mrdoob** [comment]
@gkjohnson instead of doing `segments = segments % 2 === 0 ? segments + 1 : segments;` would it make sense to just multiply `segments * 2`?

**Comment by gkjohnson** [comment]
@mrdoob

> just multiply `segments * 2`

You'd have to do `segments * 2 + 1` because it needs to be odd. I'm not sure if I feel that's better, though, and it would give less granular control over the segment count.

**Comment by mrdoob** [comment]
I see. Makes sense yes...
Anything left from this issue?

**Comment by gkjohnson** [comment]
Just what I mentioned in https://github.com/mrdoob/three.js/issues/20665#issuecomment-725532600 -- I don't know if you want to do anything about it or leave it as is. An easy way to address it is to force the radius to be at most half the width of any dimension:

```js
radius = Math.min( width / 2, height / 2, depth / 2, radius );
```

I'm fine with leaving it as is, though.

**Comment by WestLangley** [comment]
I think `segments` should refer to the number of segments defining the curved corners of each of the primary faces. In that regard, it can take values of 1, 2, 3, ...

As the code is written, different inputs can generate the same rendered output.

**Comment by mrdoob** [comment]
> As the code is written, different inputs can generate the same rendered output.

Yes, that's what I found confusing. That's what made me suggest multiplying by 2.

**Comment by gkjohnson** [comment]
> Consequently, I disagree with that statement.

You're right now that I've thought about it more I agree. That means the code should change to `segments = segments * 2 + 1` and the lottie example should change to set the segments to `7`. @mrdoob do you want to just make the change? Otherwise I can make another PR.

**Comment by mrdoob** [comment]
I'll do the change 👌

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/2d1723fd7ed98deecb9acd1484f9fe49154ddfcd

**Comment by mrdoob** [comment]
Fixed radius: https://github.com/mrdoob/three.js/commit/4c0e435e8f413378eeb0e22131e0a3508a6463b7
