### ISSUE TITLE
renderer.info.frame should not be compared to flag a geometry attribute update

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#20671]
Setting  renderer.info.autoReset  to  false and not calling  renderer.info.reset() afterward is preventing geometries attribute updates.

Renderer.info.frame is incremented only on renderer.info.reset()
The renderer.info.frame is compared to the version of the geometry attributes.

Not calling renderer.info.reset() is preventing geometries to update attributes.

I may be wrong, but updating geometries should not rely on this as the user is not aware of the consequences of not calling renderer.info.reset() manually, unless the user is fully knows the consequences of not calling the reset on the doc.

**Comment by Mugen87** [comment]
The idea of using `renderer.info` is to only update certain entities per frame. E.g. geometries or skeletons. This is something that is not going to be changed.

The [documentation](https://threejs.org/docs/index.html#api/en/renderers/WebGLRenderer.info) about `WebGLRenderer.info` already has mentions the usage of `renderer.info.reset();`. Do you think it's more clear if we add that this method has to be called for each produces frame?

**Comment by Samsy** [comment]
I think we need to add it and make sure people are aware of it of course !
