### ISSUE TITLE
Curve modifier does not work with certain materials (undocumented)

### ISSUE THREAD

**Issue by mattrossman** [mrdoob/three.js#20687]
**Describe the bug**

The newly added curve modifier [(see this example)](https://threejs.org/examples/#webgl_modifier_curve) does not work with `MeshNormalMaterial` or `MeshBasicMaterial`

**To Reproduce**

1. Create a `Flow` by following [the author's guide](https://ada.is/blog/2020/10/29/curve-modifiers-in-threejs/)
2. Set the `objectToCurve` material to either `THREE.MeshBasicMaterial` or `THREE.MeshNormalMaterial`
3. The `objectToCurve` does not appear in the scene

***Code***

```js
const geometry = new THREE.BoxBufferGeometry();
const material = new THREE.MeshBasicMaterial()
const objectToCurve = new THREE.Mesh(geometry, material)

const points = [
  new THREE.Vector3(1, 0, -1),
  new THREE.Vector3(1, 0, 1),
  new THREE.Vector3(-1, 0, 1),
  new THREE.Vector3(-1, 0, -1)
]
const curve = new THREE.CatmullRomCurve3(points)
curve.curveType = "centripetal"
curve.closed = true
const flow = new Flow(objectToCurve)
flow.updateCurve(0, curve)
scene.add(flow.object3D)
```

***Live example***

Here are two examples, the first with a working material and the second with an unsupported material:
* [MeshPhysicalMaterial (working)](https://jsfiddle.net/mattrossman/svd79txn/)
* [MeshBasicMaterial (not working)](https://jsfiddle.net/mattrossman/Logh38xr/3)

**Expected behavior**

The curve modifier will work with all built in materials, otherwise this behavior (and rationale) would be documented somewhere in the example.

**Screenshots**

n/a

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Firefox
 - Three.js version: r122

**Comment by AdaRoseCannon** [comment]
I'll take a look this week.

**Comment by AdaRoseCannon** [comment]
The issue for the Basic Material was clear and fixed in the PR above.

I have no idea why it is not working for the normal material, as it's not showing any errors just nothing gets rendered.
