### ISSUE TITLE
MeshStandardMaterial (roughness 0) cube envmap is blurry

### ISSUE THREAD

**Issue by nilsmoh** [mrdoob/three.js#20700]
**Describe the bug**

From ThreeJS R108 a MeshStandardMaterial with roughness=0 shows a blurred Cube Envmap.
Till 107 the Envmap looked like a mirror, as expected for roughness 0.

**To Reproduce**

1. Go to http://ksaechsstseb.de/github/cubeblur/webgl_materials_envmaps_122.html
2. See error

The left cube is a MeshStandardMaterial with roughness 0 and a CubeTexture build from 6 jpegs as Envmap.
The right cube shows a MeshPhongMaterial for comparison and looks like what i expect from a roughness 0 cube.
Both Envmaps are the same.

3. Go to http://ksaechsstseb.de/github/cubeblur/webgl_materials_envmaps_107.html 

The code is exactly the same (except js references to older version) and shows my expected behaviour.

***Code***

```js
var r = 'textures/cube/Bridge2/';
var urls = [ r + 'posx.jpg', r + 'negx.jpg',
		 r + 'posy.jpg', r + 'negy.jpg',
		 r + 'posz.jpg', r + 'negz.jpg' ];

textureCube = new THREE.CubeTextureLoader().load( urls );
var geometry = new THREE.BoxBufferGeometry( 400.0, 400, 400);
sphereMaterial = new THREE.MeshStandardMaterial( { envMap: textureCube, roughness:0, metalness:1 } );
sphereMesh = new THREE.Mesh( geometry, sphereMaterial );
scene.add( sphereMesh );
```
**Expected behavior**

I expected to get a clear, not blurred envmap on the left cube with roughness=0.

The code is based on example
https://threejs.org/examples/?q=envmap#webgl_materials_envmaps
But this example uses MeshLambertMaterial and works because of this.

R108 changed some MipMap handling that might cause this but no hint in the Migration Guide for a needed flag or something. 

**Screenshots**
![cubeblurry](https://user-images.githubusercontent.com/2269737/99508515-f94e1d00-2984-11eb-86a4-1464fedd0b81.png)
Combination of 2 screenshots:
First row expected behaviour (R107)
Second row actual behaviour (R122)

**Platform:**

 - Device: Desktop
 - OS: Windows 10, OpenBSD
 - Browser: Chrome, Firefox
 - Three.js version: 108 - 122

**Comment by Mugen87** [comment]
> But this example uses MeshLambertMaterial and works because of this.

When you switch to `MeshStandardMaterial`, you should also `PMREMGenerator` to preprocess the environment map. Besides, the usage of a HDR environment map (instead of LDR) is recommended. Otherwise it does not really make sense to use a PBR material here.
