### ISSUE TITLE
Error creating WebGL Context on latest Firefox (83.0)

### ISSUE THREAD

**Issue by jreus** [mrdoob/three.js#20708]
**Describe the bug**
After updating to the latest version of Firefox (83.0 on Linux Mint), all Three.js functionality is broken. This includes my own code as well as examples on the threejs.org website.

Here is a console log with common error messages I am seeing...
```
Failed to create WebGL context: WebGL creation failed: 
* AllowWebgl2:false restricts context creation on this system.

```
THREE.WebGLRenderer: Error creating WebGL context. three.module.js:23316:11
    WebGLRenderer https://threejs.org/build/three.module.js:23316
    init https://threejs.org/examples/webgl_animation_cloth.html:552
    <anonymous> https://threejs.org/examples/webgl_animation_cloth.html:410
WebGL warning: <Create>: AllowWebgl2:false restricts context creation on this system. three.module.js:23247:28
Failed to create WebGL context: WebGL creation failed: 
* AllowWebgl2:false restricts context creation on this system. three.module.js:23247:28
WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system. three.module.js:23247:28
Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system.
* Exhausted GL driver options. three.module.js:23247:28
WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system. three.module.js:23247:28
Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system.
* Exhausted GL driver options. three.module.js:23247:28
WebGL warning: <Create>: AllowWebgl2:false restricts context creation on this system. three.module.js:23247:28
Failed to create WebGL context: WebGL creation failed: 
* AllowWebgl2:false restricts context creation on this system. three.module.js:23247:28
WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system. three.module.js:23247:28
Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system.
* Exhausted GL driver options. three.module.js:23247:28
WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system. three.module.js:23247:28
Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system.
* Exhausted GL driver options. three.module.js:23247:28
Uncaught Error: Error creating WebGL context.
    WebGLRenderer https://threejs.org/build/three.module.js:23294
    init https://threejs.org/examples/webgl_animation_cloth.html:552
    <anonymous> https://threejs.org/examples/webgl_animation_cloth.html:410
```

**To Reproduce**

Steps to reproduce the behavior:
1. update to Firefox 83.0
2. visit a site using three libraries

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: Desktop
 - OS: Linux Mint 19.3 Cinnamon
 - Browser: Firefox
 - Three.js version: whatever is being used at https://threejs.org/examples/#webgl_animation_cloth

**Comment by Mugen87** [comment]
I'm unable to reproduce this with Firefox 83 on macOS.

Please report this issue to Mozilla instead. You can do this here: https://bugzilla.mozilla.org/home

**Comment by jreus** [comment]
> I'm unable to reproduce this with Firefox 83 on macOS.
> 
> Please report this issue to Mozilla instead. You can do this here: https://bugzilla.mozilla.org/home

done!
