### ISSUE TITLE
Incorrect Behavior of depth Test  material property on Local Clipping  

### ISSUE THREAD

**Issue by omkarap55** [mrdoob/three.js#20719]
**Describe the bug**

When local clipping is enabled for one mesh (e.g. BoxGeometry mesh) and there is one Line Entity for which depthTest is set to false. Initially when the local clipping is enabled for BoxGeometry Mesh and depthTest is set to false for Line Entity, it gives expected behavior of Line Entity appearing over BoxGeometry Mesh. 
But if local clipping is toggled using localClippingEnabled property of WebGLRenderer, the Line Entity no longer appears always on top although its material's depthTest  property is set to false. 

**To Reproduce**

1. Go to https://jsfiddle.net/51jmdtc0/5/
2. Observe the initial state of the scene. (Refer Image 1)
2. Click on Local Clipping and click on Enabled Checkbox multiple times
3. Observe the scene every time you click on the checkbox. (Refer Image 2 & 3) 
 

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/51jmdtc0/5/)

**Expected behavior**

The Line Entity whose depthTest is set to false should always appear on the top irrespective of enabling or disabling local clipping of other meshes.

**Screenshots**

Initial State (Image 1)
![image](https://user-images.githubusercontent.com/17846063/99761878-351bea80-2b1d-11eb-94db-fcb86c5cf7f4.png)

After toggling localClippingEnabled property 
Image 2
![image](https://user-images.githubusercontent.com/17846063/99762222-06524400-2b1e-11eb-8fca-c3f5685f6e30.png)

Image 3
![image](https://user-images.githubusercontent.com/17846063/99761933-5b418a80-2b1d-11eb-8477-18d696ecbf75.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [ r122]

**Comment by WestLangley** [comment]
>The Line Entity whose depthTest is set to false should always appear on the top

Only if it is rendered last in your example.

Set

```js
line.renderOrder = 1;
```
