### ISSUE TITLE
TrackballControls not responding

### ISSUE THREAD

**Issue by dermaku-dardan** [mrdoob/three.js#20716]
Hi,
can anyone tell me why can't I use TrackballControls for this example: https://threejs.org/examples/?q=multiple#webgl_multiple_elements_text. When I try to switch to TrackballControls, they simply do not respond. I am really new to ThreeJS. Any help would be appreciated. Thanks!

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
