### ISSUE TITLE
Drag + Trackball controls

### ISSUE THREAD

**Issue by vasturiano** [mrdoob/three.js#20723]
**Describe the bug**

Hi there!

While setting up a scene with both Trackball and Drag controls active I noticed it has stopped working since version `0.120.0`.

I've created an example here which demonstrates the issue: https://codepen.io/vasturiano/pen/GRqazYq

As you can see, no drag pointer events are triggered if Trackball controls is enabled on the element.

After diving in a bit, I believe the change was introduced in this particular commit: https://github.com/mrdoob/three.js/commit/f86fcc092aa8459e7b78b3244e02df923f2d4753

The core of the issue is that this `pointerdown` [preventDefault call](https://github.com/mrdoob/three.js/commit/f86fcc092aa8459e7b78b3244e02df923f2d4753#diff-d481b098157c6deb25016249d868abb58a8cccba025ca41e6da9841c9d8fabfeL444) has a different behavior than when it was applied to the prior `mousedown` events. As documented [here](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onpointerdown):
> If the pointerdown event isn't canceled through a call to preventDefault(), most user agents will fire a mousedown event, so that sites not using pointer events will work.

So, this `preventDefault` call is essentially stopping the `mousedown` events from being triggered in the `DragControls` (because that module is [still using mouse events](https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/DragControls.js#L22), not pointer events).

Perhaps the solution is as simple as removing the `preventDefault` statement, since I think that is a no-op for `mousedown` events, so it would be in line with the previous behavior. 

Or migrate `DragControls` to use pointer events, that would in theory also solve it.

Btw, I believe `OrbitControls` has the same effect, since it had a [similar change applied](https://github.com/mrdoob/three.js/commit/1422e36e9facbdc5f9d86cf6b97b005a2723a24a).

Just for comparison, [here's a fork](https://codepen.io/vasturiano/pen/oNLRVjj) of the same example but importing `v0.119.1` of `TrackballControls` instead. You'll notice that both work simultaneously and can coexist reasonably well.
For a seamless experience `TrackballControls` is disabled dynamically during a drag, so the interactions don't interfere with each other.

**To Reproduce**

1. Go to https://codepen.io/vasturiano/pen/GRqazYq
2. Try to drag one of the nodes (it won't work)
3. Disable Trackball
4.  Drag successful

***Code***

Relevant portion of the code:
```js
// trackball controls
const tbControls = new THREE.TrackballControls(camera, renderer.domElement);

// drag controls
const dragControls = new THREE.DragControls(objs, camera, renderer.domElement);
dragControls.addEventListener('dragstart', () => tbControls.enabled = false); // Disable trackball controls while dragging
dragControls.addEventListener('dragend', () => tbControls.enabled = true); // Re-enable trackball controls
```

***Live example***

Not-working (TrackballControls latest version):
https://codepen.io/vasturiano/pen/GRqazYq

Working (v0.119.1):
https://codepen.io/vasturiano/pen/oNLRVjj

**Expected behavior**

Like in versions `<0.120.0`, be able to have both Drag and Trackball controls active simultaneously.

**Comment by Mugen87** [comment]
> Or migrate DragControls to use pointer events, that would in theory also solve it.

I guess we should try this first. @mrdoob What do you think?

**Comment by Mugen87** [comment]
I've made a PR that introduces Pointer Events in `DragControls` so it's easier to see the changes and verify them. The PR indeed fixes your codepen.

**Comment by vasturiano** [comment]
That's awesome, thanks @Mugen87 for the quick fix!

I confirm the example works properly with pointer events on drag controls. 👍 

I suppose this will go out with the `r123` release?

**Comment by Mugen87** [comment]
> I suppose this will go out with the r123 release?

Correct!

**Comment by pfarnach** [comment]
Was this ever released? I'm seeing a similar issue where pointer events outside of the `TrackballControls` do not get triggered in >=r120, including r123 and the most recent release. See [this codepen](https://codesandbox.io/s/r3f-demo-6-ffrme?file=/package.json) (from [this tutorial](https://medium.com/cortico/3d-data-visualization-with-react-and-three-js-7272fb6de432)) and try changing the three version in package.json. In older versions, you can click on a disc and it turns green, but the onClick is never called in newer versions of threejs.

**Comment by Marviel** [comment]
Hey @pfarnach would you care to open a new issue with your codepen? I'm seeing the same issue and would love a resolution. If I need to open my own, I can.

**Comment by Mugen87** [comment]
I can't reproduce. I've changed the version to `0.128.0` and it seems it works as expected. Please verify the following sandbox:

https://codesandbox.io/s/r3f-demo-6-forked-m8yqj?file=/package.json

**Comment by Mugen87** [comment]
I would say #21674 did the trick.
