### ISSUE TITLE
EffectComposer.js add function removePass()

### ISSUE THREAD

**Issue by Sany18** [mrdoob/three.js#20737]
**Is your feature request related to a problem? Please describe.**

I need to conveniently and dynamically enable/disable effects. I am doing this by adding functionality, but it would be nice to have it initially

**Describe the solution you'd like**

```js
EffectComposer.prototype.removePass = function(targetPass) {
  this.passes = this.passes.filter(pass => {
    return pass.constructor.name != targetPass.constructor.name
  })
}
```

**Describe alternatives you've considered**

did not met

**Comment by Mugen87** [comment]
> I need to conveniently and dynamically enable/disable effects.

Have you considered to just set `Pass.enabled` to `false` if the composer should skip a pass?

**Comment by mrdoob** [comment]
Done. https://github.com/mrdoob/three.js/commit/3cda712be8b605c9e3ef50edc76eb44cd13a90be

**Comment by mrdoob** [comment]
@Sany18 Do you mind checking that the new method behaves as expected?

**Comment by Sany18** [comment]
My solution and Mugen87 works as expected. Apparently I missed that there is Pass.enabled. Thanks)

**Comment by Mugen87** [comment]
The method is definitely a nice addition and makes the API more complete.
