### ISSUE TITLE
it seemed that there is a bug in example webgl_shaders_tonemapping

### ISSUE THREAD

**Issue by yejun81** [mrdoob/three.js#20740]
the fragmentShader of atmoShader in webgl_shaders_tonemapping used viewMatrix multiply the direction light's direction, while the direction light's direction is alreadly transformed by viewMatrix

**Comment by Mugen87** [comment]
You are referring on this line, right?

https://github.com/mrdoob/three.js/blob/5e46e96c7cde254e55cd9c4c5f9db9f917dca429/examples/webgl_shaders_tonemapping.html#L161

Even when fixing this, I don't see any visual difference at all. How does the `sphereAtmoMesh` supposed to look?

**Comment by yejun81** [comment]
> You are referring on this line, right?
> 
> https://github.com/mrdoob/three.js/blob/5e46e96c7cde254e55cd9c4c5f9db9f917dca429/examples/webgl_shaders_tonemapping.html#L161
> 
> Even when fixing this, I don't see any visual difference at all. How does the `sphereAtmoMesh` supposed to look?

yeah, that's the line.i am just a litter confused about it

**Comment by mrdoob** [comment]
Better to discuss this in the [forum](https://discourse.threejs.org/) instead.
