### ISSUE TITLE
Downsampling pointclouds (the same voxel grid filter on PCL library)

### ISSUE THREAD

**Issue by duclinhfetel** [mrdoob/three.js#20741]
Hi everyone,

I have a problem using ThreeJS to load the *.pcd map (it's about 5GB). Browser is lag and can't be manipulated on it.
I still don't know how to apply downsampling points on threejs.
Could anyone help me.

Thanks for all support!

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
