### ISSUE TITLE
SAOPass.OUTPUT is being used as a namespace

### ISSUE THREAD

**Issue by Fluqz** [mrdoob/three.js#20769]
**Describe the bug**

Using SAOPass in Typescript throws following error: 
in SAOPass.d.ts:
> 'SAOPass' only refers to a type, but is being used as a namespace here.
> output: SAOPass.OUTPUT;

**To Reproduce**

Use SAOPass in Typescript r122

***Code***

```


interface SAOPassParams {
	
       output: SAOPass.OUTPUT;

       ...
}

export class SAOPass extends Pass {

       ...
      
       static OUTPUT: {
		Beauty: number;
		Default: number;
		SAO: number;
		Depth: number;
		Normal: number;
	};

}
```

**Expected behavior**

No typing error

 - Three.js version: r122

**Comment by Mugen87** [comment]
Yeah, I was not sure how to define the following JS in TS:
```js
SAOPass.OUTPUT = {
	'Beauty': 1,
	'Default': 0,
	'SAO': 2,
	'Depth': 3,
	'Normal': 4
};
```

**Comment by Fluqz** [comment]
Could be a enum. Just tested it in my project

export enum OUTPUT: {
	Beauty: 1,
	Default: 0,
	SAO: 2,
	Depth: 3,
	Normal: 4
}

export interface SAOPassParams {
  output: OUTPUT
  ...
}

export class SAOPass extends Pass {

  static OUTPUT: OUTPUT
}

**Comment by Mugen87** [comment]
That looks better than the current solution. Do you mind creating a PR with your change?
