### ISSUE TITLE
getPoints description in (Curve)Path documentation incomplete

### ISSUE THREAD

**Issue by SeeDoubleYou** [mrdoob/three.js#20771]
The documentation for curvePath says that the method `getPoints(decisions: integer)` returns a set of (decisions + 1) points:
https://github.com/mrdoob/three.js/blob/de35b3922ff420c958c6930572ddd3e7cf00fa23/docs/api/en/extras/core/CurvePath.html#L65

However, it depends on the path because it calls `getPoints` from `Curve` with a resolution (decisions) that is based on the Path type:
https://github.com/mrdoob/three.js/blob/9694de0fb9d9e45f36b2943642d534365e6d5965/src/extras/core/CurvePath.js#L165-L168

I noticed this when I tried to get `n` points for a path created with `absArc()` from `Path` and I got `n*2+1` points returned

**Comment by Mugen87** [comment]
Maybe we could add at the `CurvePath` documentation page the following sentence to `getPoints()`:

> The actual number of divisions depends on the used curve types.

Would this make the documentation more clear?

**Comment by SeeDoubleYou** [comment]
Yes, I think so, but it could use some more explanation. The underlying question is "Why does the number of divisions double for en ellipse". Because when I have an ellipse, and I want to divide it into `n` decisions, I would need `n+1` points, so why is it different here? 
I can understand that for a line all you need is two points in the end so that resolution becomes 1. This can be explained. 

> The actual of divisions depends on the used curve types. For example, for a LineCurve, the returned number of points is always just 2.

**Comment by Mugen87** [comment]
> Because when I have an ellipse, and I want to divide it into n decisions, I would need n+1 points, so why is it different here?

I'm not sure about the motivation of implementing a different resolution for ellipse curves. 

In most cases, the exact resolution does not matter if the result "looks good". But I understand that it is confusing if you rely on a certain pattern.

Your suggested description sounds good to me. An example with `LineCurve` is definitely helpful.
