### ISSUE TITLE
When Loading glb file with sample code, GLTF loader returns Infinite loading time 

### ISSUE THREAD

**Issue by Twiggeh** [mrdoob/three.js#20779]
This is not breaking code or anything scary.

```js
const loader = new GLTFLoader();

loader.load(
	jet_model,
	(gltf) => {
		scene.add(gltf.scene);
	},
	(xhr) => {
		console.log((xhr.loaded / xhr.total) * 100 + '% loaded');
	},
	(error) => {
		console.error(error);
	}
);
```

The model loads fine, everything is good, its just that xhr.total is 0.

![image](https://user-images.githubusercontent.com/23149166/100476079-f66dcd80-30e4-11eb-943c-6a4f881f8cdd.png)

**Comment by gkjohnson** [comment]
What is your server setup?

The `onProgress` event is directly from the [http request progress callback](https://github.com/mrdoob/three.js/blob/dev/src/loaders/FileLoader.js#L212-L223) and according to mdn the `total` field is [derived from the Content-Length header](https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent/total) which as far as I know is not required. If the content length is isn't provided it's possible that the progress event `total` field is set to 0.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
