### ISSUE TITLE
Color's getHex returns wrong result

### ISSUE THREAD

**Issue by Dimous** [mrdoob/three.js#20781]
Hello!
I noticed that getHexString e.g. for green (0, 255, 0) returns "fe0100" but shoud "00ff00". 

https://github.com/mrdoob/three.js/blob/9602dee62612a9c2a34795711159abe0afae6317/src/math/Color.js#L379

Here is correct formula -- https://stackoverflow.com/a/5623914
You can test it -- https://www.typescriptlang.org/play?#code/MYGwhgzhAEDCD2J4CdoG8BQBIY8B2EALsgK7CEoAUADsgJYBuYhAptMgFzR4kC2ARi2QAaaLUbM2Acy48BQ0eKato-WX0HIAlOgC+GbFJaEAEiwAelEhBYAlOlIAWhAGIpeJcF37xELMHg6mFhYyMYkyHjQ1nYOzm7IHuDQAPzQlISOdBAAdKgAPPnQAIwAbDoA1OmZ2TlS0IXQAByV0DW5-NBclG1ZuagAVNAATACso9A6jWXQAHrpvbX1Q2MTU0VNcwvtOZ0r45MNRQAMANzY+obGZuYAysR0eFJWNvZOru6eYN6+IP5RAF5oAAzMAgGxBbChcKRBYAcmOiKRcOgVR2RlMFhesXeCSSYC0OQo93oTx6Mx0hIgIDowBYPQAtNBSpNzlh9JcsH9CNBzNAgXgWAB3OCIKjHYSrYTHLTnbBgoSESgAIiFyHwMmgytRvLq1wsJMez1aytE9HeXG1VXMesxdweZOIJBYWllQA

**Comment by Mugen87** [comment]
I'm unable to reproduce: https://jsfiddle.net/juno2r1g/1/

**Comment by Dimous** [comment]
🤷

**Comment by Dimous** [comment]
https://jsfiddle.net/3r04wz1p/

Lol, am I doing it right?

**Comment by Mugen87** [comment]
https://threejs.org/docs/index.html#api/en/math/Color.setRGB

`setRGB()` expects values between 0 and 1.

https://jsfiddle.net/Lrcgk7o4/
