### ISSUE TITLE
NodeMaterial: Rationalize built-in Node materials & mirror supported properties from Three.js materials

### ISSUE THREAD

**Issue by s3ththompson** [mrdoob/three.js#20794]
I'm trying to understand the difference between various NodeMaterials, such as `MeshStandardNodeMaterial` and `StandardNodeMaterial`.

Is the ultimate goal to offer the same built-in materials as Three.js proper? (e.g. `THREE.MeshBasicMaterial`, `THREE.MeshDepthMaterial`, `THREE.MeshDistanceMaterial`, `THREE.MeshLambertMaterial`, `THREE.MeshMatcapMaterial`, `THREE.MeshNormalMaterial`, `THREE.MeshPhongMaterial`, `THREE.MeshPhysicalMaterial`, `THREE.MeshStandardMaterial`, `THREE.MeshToonMaterial`)

I'd also hope to be able to expect the same properties between normal materials and NodeMaterials. For example, does `MeshStandardNodeMaterial` accept an `alphaMap` (or `alpha`) input like `THREE.MeshStandardMaterial`? I'm having a hard time following the supported properties from the inheritance chain... it looks like there are references to a `transparency` property or an `alpha` property on `StandardNode`, but no support for a `Nodes.TextureNode` to replicate `alphaMap` functionality?

cc @sunag

Thanks! I'm really excited by the possibilities that NodeMaterials unlock 😄

**Comment by sunag** [comment]
> Is the ultimate goal to offer the same built-in materials as Three.js proper? (e.g. THREE.MeshBasicMaterial, THREE.MeshDepthMaterial, THREE.MeshDistanceMaterial, THREE.MeshLambertMaterial, THREE.MeshMatcapMaterial, THREE.MeshNormalMaterial, THREE.MeshPhongMaterial, THREE.MeshPhysicalMaterial, THREE.MeshStandardMaterial, THREE.MeshToonMaterial)

@s3ththompson This is a problem that I had post development of `NodeMaterial` design about extended the current materials in `WebGL`. Currently the new version of `NodeMaterial` is a rereading for hybrid plataform, using `includes` for `snippets` it will be easy to extend the current materials with properties like: `standardMaterial.colorNode = ...` and preserve the current properties. 

Related: https://github.com/mrdoob/three.js/pull/20421

After maturing this new NodeMaterial version, I think about making this change in current NodeMaterial version of WebGL.

**Comment by LeviPesin** [comment]
Is this still an issue with the new Nodes system?
