### ISSUE TITLE
GLTFExporter not accounting for SkinnedMesh bindMatrix

### ISSUE THREAD

**Issue by zach-capalbo** [mrdoob/three.js#20803]
**Describe the bug**

Using `THREE.GLTFExporter` to export a `SkinnedMesh` with a `bindMatrix` that is not the identity matrix results in the `bindMatrix` being lost. If the exported mesh is later imported, 

**To Reproduce**

1. Use `FBXLoader` to load the model from https://sketchfab.com/3d-models/mannequin-anatomy-aid-free-download-2f67c4384e7f4a5b86d84ae9199b7d3b
2. See that mesh is properly aligned with skeleton (See Screenshot 1 below)
3. Export mesh using `THREE.GLTFExporter`
4. Import model exported in step 3
5. See that mesh is improperly aligned with skeleton (See Screenshot 2 below)

***Code***

Fix proposed in: #20804

***Live example***

None at the moment. I can put one together if necessary.

**Expected behavior**

Skeleton should be properly aligned after being exported and re-imported.

**Screenshots**

1. Mesh is properly aligned (on original import):

![image](https://user-images.githubusercontent.com/1325621/100803428-2379f300-33f9-11eb-9f4c-d122e71f2669.png)

2. Mesh is improperly aligned after importing exported GLB:

![image](https://user-images.githubusercontent.com/1325621/100803479-38ef1d00-33f9-11eb-88f4-0f0b0b0c07c6.png)

**Platform:**

 - Device: Any
 - OS: Any
 - Browser: Any
 - Three.js version: Noticed in 0.111.6/A-FRAME 1.0.4. Still appears to be present in dev

**Comment by Mugen87** [comment]
> Export mesh using THREE.GLTFExporter

How have you exported the model? When I'm trying this from the editor, I get the following error:

> Uncaught Error: THREE.GLTFExporter: Morph target name not found: 0

**Comment by zach-capalbo** [comment]
Thanks for looking into this. There may be some unrelated version differences. I'll set up a runnable demo as soon as I get a chance.

**Comment by zach-capalbo** [comment]
The export error you mentioned seems to be a separate error with animations on morph targets in a number of models that come from FBX files. I'm investigating that as well, but will report it separately & submit a fix if I can pin down the issue.


For this issue here I've created a minimal live example here: https://glitch.com/edit/#!/transparent-brassy-mercury?path=index.html%3A55%3A2

The glitch also demonstrates a manual application of the proposed fix in: https://github.com/mrdoob/three.js/pull/20804

Let me know if there's any thing else you need for this.

**Comment by Mugen87** [comment]
Thanks for the examples! Yes, I suspect this issues was noticed since certain many assets have an identity matrix as the bind matrix.
