### ISSUE TITLE
vertexColors not working properly when color defined

### ISSUE THREAD

**Issue by brupelo** [mrdoob/three.js#20808]
Consider this snippet:

```
import * as THREE from "three";

var camera, scene, renderer;
var geometry, material, mesh;
init();
animation();

function init() {
  camera = new THREE.PerspectiveCamera(
    75,
    window.innerWidth / window.innerHeight,
    1,
    1000
  );
  camera.position.z = 500;

  scene = new THREE.Scene();
  scene.add(new THREE.AmbientLight("white"));

  geometry = new THREE.IcosahedronGeometry(200, 1);
  geometry.computeFaceNormals();
  for (let f of geometry.faces) {
    f.vertexColors = [
      new THREE.Color("green"),
      new THREE.Color("green"),
      new THREE.Color("green")
    ];
  }

  let test = 1; // TWEAK THIS ONE FOR DIFFERENT CASES!!!
  if (test===0) {
    material = new THREE.MeshLambertMaterial({
      side: THREE.DoubleSide,
      vertexColors: THREE.VertexColors
    });
  } else if (test===1) {
    material = new THREE.MeshLambertMaterial({
      side: THREE.DoubleSide,
      vertexColors: THREE.VertexColors,
      color: new THREE.Color(0xff00ff)
    });
  } else if (test===2) {
    material = new THREE.MeshLambertMaterial({
      side: THREE.DoubleSide,
      color: new THREE.Color(0xff00ff)
    });
  }

  mesh = new THREE.Mesh(geometry, material);
  scene.add(mesh);

  renderer = new THREE.WebGLRenderer({
    antialias: true
  });
  renderer.setSize(window.innerWidth, window.innerHeight);
  document.body.appendChild(renderer.domElement);
}
function animation() {
  window.requestAnimationFrame(animation);
  mesh.rotation.x += 0.01;
  renderer.render(scene, camera);
}

```

If you set the variable `test` to 1 you'll get a black screen while if you set it to either 0 or 2 you'll get the Icosahedron drawn
as expected.

What I was trying to accomplish here is being able to enable/disable an object colormap by using vertexColors (ie: vertexColors + colorNeedsUpdate) but it seems if you've defined the material's color that'll be conflicting somehow.

Is this a bug or intended behaviour? And if it's intended behaviour how you'd be able to achieve what I'm asking for... Being able to toggle between material's and material's vertexColors.

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: 0.123.0

**Comment by Mugen87** [comment]
> Being able to toggle between material's and material's vertexColors.

It's best if you are using two different materials in order to avoid recompilations of the shader. If you are using only a single material, you have to set the `needsUpdate` flag of the material to `true`.

**Comment by brupelo** [comment]
@Mugen87 First of all, thanks for your fast reply... I've tried your suggestion and it didn't make any difference. To make the issue more clear I've created a sandbox [here](https://codesandbox.io/s/nifty-volhard-18urf?file=/src/index.js) where you can give it a shot.

Just change the variable `test` at line 30 to see the other working cases... Also, be aware I've carefully chosen material's color to `0xff00ff` while all the vertexColors being `0x00ff00`... if I changed material's color to `0xffffff` the bug wouldn't show up.

Btw. I'm telling this is a bug but that's just pure speculation as I don't know anything about three.js's internal.

**Comment by Mugen87** [comment]
> Also, be aware I've carefully chosen material's color to 0xff00ff while all the vertexColors being 0x00ff00

Since vertex colors and the material color are multiplied, it's not surprising that the resulting color will be 0x000000. So it's not a bug but the intended behavior.

**Comment by brupelo** [comment]
> Since vertex colors and the material color are multiplied, it's not surprising that the resulting color will be 0x000000. So it's not a bug but the intended behavior.

Ok, thanks for the clarification, I guess it makes kind of sense... i suposse that behaviour is living somewhere in any of these chunks https://github.com/mrdoob/three.js/tree/dev/src/renderers/shaders/ShaderChunk . My intuition tells me maybe this one https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/color_vertex.glsl.js but who knows, I'd need to trace where those macros are used in the code, getting familiar with the codebase, etc...

Anyway, next I need to figure out why vertexColors are not displayed properly even if I'm switching the material array to a new one, my code looks like this:

```
class Foo extends THREE.Mesh {
  constructor(geometry) {
    super(geometry, []);

    // Scalar field display
    if (!Foo.scalarMaterials) {
        Foo.scalarMaterials = [];
        for(let i=0;i<16;i++) {
            Foo.scalarMaterials.push(new THREE.MeshLambertMaterial({
              side: THREE.DoubleSide,
              vertexColors: THREE.VertexColors
            }));
        }
    }
    this.scalarFieldEnabled = false;

    this.material = this.genMaterials();
  }

  toggleScalarField = (field) => {
    if (this.scalarFieldEnabled) {
      this.disableScalarField();
    } else {
      this.setScalarField(field);
      this.enableScalarField();
    }
  }

  setScalarField = (field) => {
    for (let f of this.geometry.faces) {
      f.vertexColors = [
        new THREE.Color("red"),
        new THREE.Color("green"),
        new THREE.Color("blue"),
      ];
    }
    this.geometry.colorsNeedUpdate = true; // https://threejs.org/docs/#api/en/core/Geometry.colors
  }

  enableScalarField = () => {
    if (this.scalarFieldEnabled) {
      return;
    }
    this._material = this.material;
    this.material = Foo.scalarMaterials;
    for (let material of this.material) {
      // https://threejs.org/docs/#api/en/materials/Material.needsUpdate
      material.needsUpdate = true;
    }
    this.scalarFieldEnabled = true;
  };

  disableScalarField = () => {
    if (!this.scalarFieldEnabled) {
      return;
    }
    this.material = this._material;
    this._material = null;
    this.scalarFieldEnabled = false;
  }
}
```

when I call `toggleScalarField` I'll just see greyed objects instead ones with triangles using the interpolation of red/green/blue... I must be doing something clearly wrong there but I dunno what. Cos If I set a color in the scalarMaterials that will be displayed correctly :/

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help. GitHub is for bugs and feature requests only.
