### ISSUE TITLE
Support Encoding in DataTexture

### ISSUE THREAD

**Issue by sipickles** [mrdoob/three.js#20807]
**Is your feature request related to a problem? Please describe.**

DataTexture class is consistent with Texture class EXCEPT for lacking encoding support.

**Describe the solution you'd like**

I'd like to be able to set a DataTexture to use THREE.sRGBEncoding, just as is possible with Texture.

**Describe alternatives you've considered**

Performing colorspace conversion manually. I am anticipating THREE to do a better job :)

**Additional context**

None

**Comment by sipickles** [comment]
My IDE reports this signature for the DataTexture ctor:

``` DataTexture(data: THREE.TypedArray, width: number, height: number, format?: THREE.PixelFormat, type?: THREE.TextureDataType, mapping?: THREE.Mapping, wrapS?: THREE.Wrapping, wrapT?: THREE.Wrapping, magFilter?: THREE.TextureFilter, minFilter?: THREE.TextureFilter, anisotropy?: number, encoding?: THREE.TextureEncoding): THREE.DataTexture```

Looks like its a documentation issue in that case.

**Comment by Mugen87** [comment]
TBH, I'm confused. `DataTexture` only hold texture data in a different way than instances of `Texture`. Everything else should be identical.

**Comment by gkjohnson** [comment]
@Mugen87 I don't think there's an issue -- just confusion over the documentation. The constructor on the [DataTexture](https://threejs.org/docs/#api/en/textures/DataTexture) docs page does not include that the `encoding` field in the parameters which is present in the [source](https://github.com/mrdoob/three.js/blob/master/src/textures/DataTexture.js#L4).

@sipickles The docs do specify that `DataTexture` inherits all properties from `Texture`, though, so encoding is already supported.
