### ISSUE TITLE
OrbitControls keydown events not firing

### ISSUE THREAD

**Issue by joshuaellis** [mrdoob/three.js#20805]
**Describe the bug**

the keydown event is attached to the dom node as should be, but when you use the arrow keys no event is fired. I can see in the PR #17819 that you added the following code:

```js
if ( scope.domElement.tabIndex === -1 ) {
  scope.domElement.tabIndex = 0;
}
```

but in the latest release r123, this code is no longer there. If I re-add the code above the keydown events work as expected. After some digging I can see in #20617 this issue is known, but i've already written this bug so at least it's visible to others.

If I understand right, is it that the canvas isn't focussed so the keydown events don't fire? I'm happy to work on a PR to fix this.

**To Reproduce**

1. Go to - https://threejs.org/examples/?q=controls#misc_controls_orbit
2. try use the arrow keys

**Expected behavior**

The keydown events should fire moving the camera.

**Platform:**

 - Device: [Desktop, Mobile] desktop
 - OS: [Windows, MacOS, Linux, Android, iOS] macOS
 - Browser: [Chrome, Firefox, Safari, Edge] chrome/firefox
 - Three.js version: r123

**Comment by Mugen87** [comment]
There are already proposal to fix this issue, see https://github.com/mrdoob/three.js/pull/20617#issuecomment-724804245 and the subsequent comment. 

As mentioned in the post, I vote for a third optional ctor parameter that represents the target for the keydown event listener.

**Comment by joshuaellis** [comment]
If you the parameter isn't set and no event listener is added, doesn't that make the boolean `enableKeys` redundant? Why wouldn't it default to window?

I'd also like to hear what @mrdoob's reasoning why
>Changing the page's tabIndex when constructing OrbitControls was definitely not the right thing to do.
just for some more context.

**Comment by Mugen87** [comment]
> just for some more context.

https://github.com/mrdoob/three.js/pull/20616#issuecomment-721730887

> Why wouldn't it default to window?

Because using `window` is problematic, too see https://github.com/mrdoob/three.js/pull/16676#issue-284846233.

**Comment by joshuaellis** [comment]
Okay I think the third parameter makes sense, but if you don't supply one then `enableKeys` should be false and it should probably give a warning if the user sets it to true without there being an event listener attached?

Is it also worth exposing a method to set the event listener on an element post constructor? e.g.
```js
OrbitControls.setKeyEventListener(element)
```

But I suppose the controls wouldn't work still if you supplied the canvas element as that third parameter would it? Because that wouldn't fix the focussing issue.

**Comment by Mugen87** [comment]
I personally would prefer to completely remove the key support since it turned out to be a fragile feature. And it was not possible so far to find a solution that makes everyone happy. It's probably best if it is implemented on app level if required.

If @mrdoob wants to keep this feature, I vote for a simple solution. We could add a getter and setter to `enableKeys` and log a warning if the third parameter was not supplied. I'm not a fan of `setKeyEventListener()`. Users could request a similar method for all other events. Since the controls should stay simple, this is not something desirable.

**Comment by joshuaellis** [comment]
>We could add a getter and setter to enableKeys and log a warning if the third parameter was not supplied. 

I think this is a good solution

>I'm not a fan of setKeyEventListener(). Users could request similar methods for all other events. Since the controls should stay simple, this is not something desirable.

That's fair.

I'm happy to do a PR for this issue, depending on what @mrdoob thinks on the subject. Personally even though it's fragile I do think people like/want it. My own discovery of this issue was from an issue on `@react-three/drei` so there's some form of demand.

**Comment by joshuaellis** [comment]
@mrdoob do you have any thoughts on this or can I go ahead an create a PR based on https://github.com/mrdoob/three.js/pull/20617#issuecomment-725303765?

**Comment by mrdoob** [comment]
I do not like adding more parameters to the constructor. We end up with APIs like `Texture` which is not pretty.

I prefer this API:

```js
const controls = new OrbitControls( camera );
controls.listenPointerEvents( renderer.domElement );
controls.listenKeyEvents( window );
```

> Okay I think the third parameter makes sense, but if you don't supply one then `enableKeys` should be false 

Good point. `listenKeyEvents` would make `enableKeys` redundant. We can just remove `enableKeys`.

**Comment by Mugen87** [comment]
I admit that long signatures like the `Texture`'s ctor are problematic. 

If it is mandatory to call `listenPointerEvents()`, it means the change is not backwards compatible. I hoped for a solution that does not break existing code.

**Comment by mrdoob** [comment]
> Besides, I find it a bit confusing if you create an instance of `OrbitControls` but you can't use the controls right away. I suspect all use cases require to call `listenPointerEvents()`. That feels like the logic should be executed by default.

I used to think that too, but #20575 made me reconsider. Also, as you know, that "magic" has caused quite a few issues in the past...

But I think we can start with `listenKeyEvents()` for now and see how it works out.

**Comment by Mugen87** [comment]
> I used to think that too, but #20575 made me reconsider. Also, as you know, that "magic" has caused quite a few issues in the past...

I see. Yeah, against this backdrop separate methods for activating/deactivating (or connecting/disconnecting) do make sense. 

I just try to look at this issue from the perspective of an average `three.js` user. I fear the additional call of `listen*()` methods could be considered as inconvenient. Especially if one says it "worked before without issues".

> But I think we can start with listenKeyEvents() for now and see how it works out.

👍

**Comment by mrdoob** [comment]
> I just try to look at this issue from the perspective of an average `three.js` user. I fear the additional call of `listen*()` methods could be considered as inconvenient. Especially if one says it "worked before without issues"

Yeah, but I think it's not too bad and teaches the user about pointer events.

Also, code editors also gave me issues when doing this:

```js
var controls = new THREE.OrbitControls( camera );
```

They would complain that `controls` is not used and had to do this:

```js
new THREE.OrbitControls( camera );
```

Which was always weird 😅

**Comment by joshuaellis** [comment]
>Which was always weird 😅

I have to admit, I thought it was weird.

**Comment by TiagoCavalcante** [comment]
@mrdoob @Mugen87 it should be re-opened, this stopped working again.

**Comment by mrdoob** [comment]
@TiagoCavalcante Do you have a jsfiddle to prove it?

**Comment by TiagoCavalcante** [comment]
@mrdoob [here](https://codepen.io/TiagoCavalcanteTrindade/pen/oNombyW) is a CodePen, that is the simplest example I have achieved.

**Comment by mrdoob** [comment]
Works fine here... Chrome 98 MacOS.

**Comment by TiagoCavalcante** [comment]
@mrdoob another person also commented that it isn't working: https://github.com/pmndrs/drei/issues/186#issuecomment-1046220405

**Comment by WestLangley** [comment]
@TiagoCavalcante `OrbitControls` listens for arrow keys, not WASD.

Do this:
```js
controls.listenToKeyEvents( window );

controls.keys = { LEFT: 'KeyA', UP: 'KeyW', RIGHT: 'KeyD', BOTTOM: 'KeyS' };
```

**Comment by TiagoCavalcante** [comment]
@WestLangley thanks, that was my mistake.
