### ISSUE TITLE
PMREMGenerator: FromScene behavior differs with renderer clear color vs scene.background

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#20819]
**Describe the bug**

The resulting environment map from PMREMGenerator.fromScene differs when calling `renderer.setClearColor( 0xffffff )` beforehand vs calling `scene.background = new Color( 0xffffff );`.

**To Reproduce**

You can see the difference in behavior in this fiddle:

https://jsfiddle.net/0saxwg6n/

Uncomment this line to see the behavior difference:

```
// NOTE: Uncomment this line to make it work
// scene.background = new THREE.Color( 0xffffff );
```

***Code***

Setting clear color:

```js
renderer.setClearColor( 0xffffff );
const generator = new THREE.PMREMGenerator( renderer );
const rt = generator.fromScene( scene );
scene.environment = rt.texture;
```

Setting scene background:

```js
scene.background = new THREE.Color( 0xffffff );
const generator = new THREE.PMREMGenerator( renderer );
const rt = generator.fromScene( scene );
scene.environment = rt.texture;
```

**Expected behavior**

The look of the resulting map is the same regardless of whether or not the background color is set via scene.background or renderer clear color.

**Screenshots**

renderer.setClearColor( 0xffffff );

![image](https://user-images.githubusercontent.com/734200/101092363-64dfdf00-356e-11eb-92a6-7f49bfc26b51.png)

scene.background = new Color( 0xffffff );

![image](https://user-images.githubusercontent.com/734200/101092420-7cb76300-356e-11eb-8f41-f352ee018ae2.png)

(an aside but is it expected that the background become so much darker when rendering to the environment map?)

**Platform:**

 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Three.js version: dev

**Comment by mrdoob** [comment]
> (an aside but is it expected that the background become so much darker when rendering to the environment map?)

Hmm, should be fairly fixable actually... We should just take `renderer.outputEncoding` into account when rendering the background color?

**Comment by gkjohnson** [comment]
> We should just take `renderer.outputEncoding` into account when rendering the background color?

Is it so simple? I'm unfamiliar with exactly how all of this should work when it comes to generating (HDR?) environment maps but `0xffffff` in srgb is `0xffffff` in linear and vice versa so I wouldn't expect color space conversion to affect the resulting color in the map.

It looks to me like this is probably the section of code responsible for darkening the color (and is not being applied to renderer clear color when scene.background is not defined):

https://github.com/mrdoob/three.js/blob/9694de0fb9d9e45f36b2943642d534365e6d5965/src/extras/PMREMGenerator.js#L269-L276

**Comment by WestLangley** [comment]
The renderer clear color and scene background color do not respond to tone mapping or encoding settings; textured backgrounds do. That is by design. Related: #15382.

**Comment by gkjohnson** [comment]
> The renderer clear color and scene background color do not respond to tone mapping or encoding settings

I thought I'd recalled that. So do we know why a background of pure white results in such a medium gray color? Is that intended?

And to the original point of the issue -- is it intended that setting the clear color to white and setting the scene background to white results in a different color environment map? Or just an oversight that the clear color is not converted to RGBE the same way that scene.background is?

Perhaps @elalish knows?

**Comment by elalish** [comment]
So the trick with HDR is that it is on a floating-point scale, which goes vastly beyond the [0, 1] range of sRGB. Tone mapping is required to map back to [0, 1]. Think of 1 as a white piece of paper, and 10,000 as a light bulb. When you're looking at both of these, it would be odd to map them each to an sRGB of 1, right? In fact the paper will come out looking kind of a medium gray by comparison, depending on the light incident on it. Anything in the [0, 1] range will have very little effect on a PMREM, as the light is so dim. You really need to make use of the floating-point range if you want to define sources of light.

**Comment by gkjohnson** [comment]
@elalish I do understand that HDR represents lighting data far outside the the typical 0-1 color range but what I'm trying to get at is there's different behavior when rendering PMREM using `renderer.clearColor` vs `scene.background`. From the first post you can see the difference when setting the scene background to white vs just setting the clear color to white:

**renderer.setClearColor( 0xffffff );**

![image](https://user-images.githubusercontent.com/734200/101092363-64dfdf00-356e-11eb-92a6-7f49bfc26b51.png)

**scene.background = new Color( 0xffffff );**

![image](https://user-images.githubusercontent.com/734200/101092420-7cb76300-356e-11eb-8f41-f352ee018ae2.png)

As a user it's confusing to me that these are different and I believe it's an oversight. The difference stems from [this section of the code](https://github.com/mrdoob/three.js/blob/9694de0fb9d9e45f36b2943642d534365e6d5965/src/extras/PMREMGenerator.js#L266-L278) that only converts the background color to an exponential representation but does not if it's using the renderer.clearColor. The behavior in these two cases should be the same, right? I'm happy to make the change I just want to confirm.

Behavioral difference aside I question whether or not it makes sense to map the background colors to an exponential representation considering they don't respond to lighting. It's odd to set the background to white and have it render as dull gray. If I want the background color to be "lightbulb" intensity should I set background color to values > 1.0? The docs state the range used for [Color](https://threejs.org/docs/#api/en/math/Color) should be between `[ 0.0, 1.0 ]`.

**Comment by elalish** [comment]
I agree it's a bit confusing, but I'm not sure what would be less confusing. Anything rendered into a PMREM should be HDR, which means colors restricted to the [0, 1] space are the confusing thing to me. To generate area lights, I use boxes with large emissive intensities to accomplish this. If you want something like a hemisphere light by setting a constant background color, I would tend to expect it to be >1, though I agree this sounds like a hack. 

I'm actually more surprised that setting the clear color to white gives a white background, since PMREM is calculated in RGBE space. I don't know what `#fffffff` is in RGBE, but I don't think it's what you're expecting.

**Comment by gkjohnson** [comment]
> I agree it's a bit confusing, but I'm not sure what would be less confusing.

What was getting me was that [this section of code](https://github.com/mrdoob/three.js/blob/9694de0fb9d9e45f36b2943642d534365e6d5965/src/extras/PMREMGenerator.js#L266-L278) is specifically designed to be the inverse of the [RGBEToLinear](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/encodings_pars_fragment.glsl.js#L24-L26) shader function which means that setting a white background should get converted to RGBE when writing to the cube map and get converted back to white when sampling but instead we're getting the tinted gray color.

After some testing this seems to be related to the `premultipliedAlpha` setting on the renderer and the fact that the alpha component is being overloaded to represent the exponent in this case. Setting it to `false` in [the example above](https://jsfiddle.net/0saxwg6n/) yields more expected results:

**PremultipliedAlpa : True**

![image](https://user-images.githubusercontent.com/734200/103418214-91bdec80-4b42-11eb-8ba3-4b31cad5e11e.png)

**PremultipliedAlpha : False**

![image](https://user-images.githubusercontent.com/734200/103418185-6e933d00-4b42-11eb-8210-646a3977428f.png)

[This StackOverflow answer](https://stackoverflow.com/questions/20362023/webgl-why-does-transparent-canvas-show-clearcolor-color-component-when-alpha-is) mentions that there can be quirks when the premultiplied alpha color used to clear is invalid (white to RGBE is `1.0, 1.0, 1.0, 0.5...`) and ultimately the result shouldn't be dependent on the premultiplied alpha setting. I think this can be fixed and made resilient to the setting by clearing the background with a flat color mesh with opacity rather than using the renderer clear color but I have to do more testing.

> 'm actually more surprised that setting the clear color to white gives a white background, since PMREM is calculated in RGBE space. I don't know what #ffffff is in RGBE, but I don't think it's what you're expecting.

Heh I think it's just an _extremely_ blown out white, which is why we're not seeing the red tinting from the plane in the example image above.

**Comment by whatisor** [comment]
> to account when render

I wonder why we didn't follow this, but need to keep current? What is advantage(or difficulty) of it?
