### ISSUE TITLE
frustumCulled description inaccurate?

### ISSUE THREAD

**Issue by SeanPedersen** [mrdoob/three.js#20811]
**Describe the bug**
The documentation states following about frustumCulled property:

When this is set, it checks every frame if the object is in the frustum of the camera before rendering the object. Otherwise the object gets rendered every frame **even if it isn't visible.** Default is true.

I just set for all my Points frustumCulled = false and basically replaced it with my frustum code that just toggles the visibility property. I then logged the renderers draw calls ( renderer.info.render.calls ) and I observed that the number of visible objects produced by my frustum matches exactly the number of draw calls. So I conclude the documentation is wrong or I am missing something. Anyway I hope to learn something, curious what"s up with that.

**To Reproduce**

1. Disable frustumCulled
2. Roll own frustum culler that works with visibility properties
3. log draw calls

***Code***

Can not share my code right now, sorry. I could try to create a small example for reproducibility if needed.

**Expected behavior**

That visibility would have no impact on number of draw calls when frustumCulled is disabled.

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome, Firefox
 - Three.js version: 0.123.0

**Comment by gkjohnson** [comment]
> I just set for all my Points frustumCulled = false and basically replaced it with my frustum code that just toggles the visibility property.

If you are setting the visibility for an object to `false` then it will not be drawn and therefore not increment the drawcall counter.

> Can not share my code right now, sorry. I could try to create a small example for reproducibility if needed.

I think it's best to provide a reproduce-able example to show the issue and so this can be examined if there's actually a bug here.

**Comment by SeanPedersen** [comment]
> > I just set for all my Points frustumCulled = false and basically replaced it with my frustum code that just toggles the visibility property.
> 
> If you are setting the visibility for an object to `false` then it will not be drawn and therefore not increment the drawcall counter.
> 

If you are 100% certain that "visibility for an object to `false` then it will not be drawn" is a true statement, then follows that "When this is set, it checks every frame if the object is in the frustum of the camera before rendering the object.Otherwise the object gets rendered every frame even if it isn't visible" is **false**. So the documentation is just wrong. Do you see my point? I can create a pull request to correct the part of the documentation.

**Comment by gkjohnson** [comment]
It think it depends on how you read it but I can see how it can be ambiguous. If you want to improve that part of the docs feel free to make a PR!

**Comment by SeanPedersen** [comment]
Done!
