### ISSUE TITLE
Convert to Haxe

### ISSUE THREAD

**Issue by Modcat** [mrdoob/three.js#20810]
To me this seems logical to convert ThreeJS to Haxe which would be an amazing framework to Haxe which wouldn't take long. Then you can export this Library to Javascript, C#, C++, Java and pretty much any language you wanted! This will future proof for WSAM native supported languages in the browser which offer even faster rendering. Don't limit yourself to Javascript, Haxe will allow all programming languages and you only have to write it once.

[Haxe](https://haxe.org/)
[Haxe ThreeJS Port](https://lib.haxe.org/p/threejs/)

I know the port is here but it'd be nice to support this officially. For me it makes no sense to just write this for JS but inclusive of all languages now that all languages can run on the web using WSAM!

**Comment by mrdoob** [comment]
Sorry. I have no interest in learning more programming languages.
It's hard enough already to deal with ES5/ES6, CSS, GLSL, WebXR, WebGPU and WGSL.
