### ISSUE TITLE
RGBELoader magic header check

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#20839]
**Describe the bug**

RGBELoader checks for magic token at the start of the file:
https://github.com/mrdoob/three.js/blob/1e161eaeedee694861ec480f04b632443f64dbb4/examples/jsm/loaders/RGBELoader.js#L149-L154

I have a file that has the said header:
![image](https://user-images.githubusercontent.com/5939063/101245085-aefdc780-370a-11eb-8686-88965aeb66f9.png)
Loader doesn't recognize the magic token though.

Here's what `line` contents are when printed to console:
![image](https://user-images.githubusercontent.com/5939063/101245112-d5236780-370a-11eb-97ae-e315b5745ce3.png)

Now the curious part here is if you try to copy that and check the match again:
![image](https://user-images.githubusercontent.com/5939063/101245125-f3896300-370a-11eb-984e-c68fd6c2a0bc.png)
All looks good, however, if you try it on the `line` directly, you will see this:
![image](https://user-images.githubusercontent.com/5939063/101245145-0c921400-370b-11eb-93b0-6b978e6c0875.png)

The problem is that there's a `&#13;` at the end (carriage return):
![image](https://user-images.githubusercontent.com/5939063/101245190-495e0b00-370b-11eb-81d5-92e29bde323f.png)
![image](https://user-images.githubusercontent.com/5939063/101245195-53800980-370b-11eb-9035-d3230a813815.png)

A bit extra:
![image](https://user-images.githubusercontent.com/5939063/101245263-ce492480-370b-11eb-8304-7efd3ca5b107.png)
It looks like both 13 and 10 are interpreted as NEW_LINE char by the ingestion function `fget`

**To Reproduce**

- can't share the file at this moment

***Code***

```js
```

***Live example***

- can't share the file at this moment

**Expected behavior**

I'm not sure, I believe this should be treated as a valid header. This problem did not occur when using r107, so it looks like a regression bug. But perhaps someone more familiar with the RGBE spec can clarify.

**Screenshots**

see above

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [r??? - yes, 123]

**Comment by gkjohnson** [comment]
I can't find anything online that states the bytes that come after `#?RADIANCE` should be restricted. [This reference on the spec](http://paulbourke.net/dataformats/pic/) seems to indicate that it's enough for the first bytes be `#?RADIANCE` and that a newline does not need to follow.

Changing `magic_token_re` from this

```js
magic_token_re = /^#\?(\S+)$/
```

to this

```js
magic_token_re = /^#\?(\S+)/
```

seems like a fix.

**Comment by mrdoob** [comment]
@Usnul do you mind testing that fix?

**Comment by Usnul** [comment]
Yes, this works.
