### ISSUE TITLE
Example - webgl_shadow_contact artifacts

### ISSUE THREAD

**Issue by Fluqz** [mrdoob/three.js#20848]
**Describe the bug**

[The contact shadow example](https://threejs.org/examples/?q=contact#webgl_shadow_contact) from @marcofugaro, when viewed from further away or with increased plane size, starts to flimmer and get distorted shadows.

**To Reproduce**

Basicly just dolly out far enough in the example. 
I made a live example which shows it better.

https://jsfiddle.net/h0jmwvpd/2/

**Expected behavior**

The shadows should stay static. No artifacts, no flimmering.

**Platform:**

 - Device: Desktop
 - OS: Windows, MacOS
 - Browser: Chrome
 - Three.js version: r123

**Comment by gkjohnson** [comment]
It looks like a depth precision issue because two planes are added on top of eachother with a small offset:

https://github.com/mrdoob/three.js/blob/9694de0fb9d9e45f36b2943642d534365e6d5965/examples/webgl_shadow_contact.html#L138

I think using polygonOffset should fix this.

**Comment by Fluqz** [comment]
Yep, that worked! Thanks
I can make a PR to update the example if you want

**Comment by gkjohnson** [comment]
@Fluqz That would be great!
