### ISSUE TITLE
Underscores removed from node names in GLTFLoader de-duplication process

### ISSUE THREAD

**Issue by ryans1224** [mrdoob/three.js#20843]
**Describe the bug**

I see in (#16639) that duplicate node names are now appended with `_i` when using GLTFLoader. I have noticed in my application though that when i use an underscore `_` in the node name string, the de-duplicated node process is removing them, which is breaking my application.

***Live example***
The duplicated node name in the below jsfiddle is `cool_box`

Note that the 2nd and 3rd node names are then renamed `cool box_1` & `cool box_2` (first underscores removed)
https://jsfiddle.net/vthyra4c/

**Expected behavior**

De-duplicated node names are appended with `_i` but the rest of the name string should remain intact. 

**Screenshots**

![image](https://user-images.githubusercontent.com/7398104/101275271-46f7c180-379c-11eb-9ec3-ebfafc7f3f7e.png)

**Platform:**

 - Device: Deskto
 - OS: Linux
 - Browser: Chrome
 - Three.js version: r123

PS. this is one of my first bug reports, let me know if i should have done something differently or included some other helpful info!

**Comment by donmccurdy** [comment]
Hi @ryans1224 — GLTFLoader does certain renaming to ensure that node names are (1) unique and (2) compatible with the three.js animation system's naming requirements, but I think that's actually not the cause here. If you open your glTF file directly and search for the "nodes" section, the object names have spaces in them already:

https://raw.githubusercontent.com/ryans1224/cool_box/main/coolboxtest.gltf

![Screen Shot 2020-12-06 at 1 29 11 PM](https://user-images.githubusercontent.com/1848368/101292882-08c3c780-37c7-11eb-999d-30286f88dfbf.png)

GLTFLoader is adding a suffix to those to make them unique, but not otherwise changing them.

And, thanks for the detailed explanation in the bug report! That does make it much easier to diagnose things quickly, and is appreciated. 👍

**Comment by ryans1224** [comment]
@donmccurdy Thanks for looking into this! Ah yes i should have spotted that the node names where already changed in my file (exported from clara.io). 

So, contrary to my initial issue description, a potential problem must be that  GLTFLoader is editing the **first** node name by _adding_ an underscore to the first node? (see below image comparing your screenshot of the actual GLTF file, and the console.log of the object from the scene)

![image](https://user-images.githubusercontent.com/7398104/101323274-4f193500-3860-11eb-9e16-0c00f361b9aa.png)

**Comment by donmccurdy** [comment]
Hm, I see. It ought to be replacing all spaces with underscores, in order to make the names compatible with three.js' animation system, which does not allow spaces in object identifiers. I'm not sure why the second two nodes are not renamed this way, that appears to be a bug.

**Comment by ryans1224** [comment]
Tried to track it down:

```
/** When Object3D instances are targeted by animation, they need unique names. */
	GLTFParser.prototype.createUniqueName = function ( originalName ) {

		var name = THREE.PropertyBinding.sanitizeNodeName( originalName || '' );

		for ( var i = 1; this.nodeNamesUsed[ name ]; ++ i ) {

			name = originalName + '_' + i;

		}

		this.nodeNamesUsed[ name ] = true;

		return name;

	};
```


In the for loop here, should `name = originalName + '_' + i;` be `name = name + '_' + i` ... otherwise the sanitized node name is thrown out and not used, which correlates to what we are seeing

**Comment by donmccurdy** [comment]
That looks right, yes — thanks for investigating!  The fix would be a little different to ensure name doesn't have repeated suffixes like `foo_0_1_2_3_...` but that's easy enough. Could you open a PR for this?

**Comment by ryans1224** [comment]
@donmccurdy gave it a go... let me know if you would have done it differently and also if i did everything correctly regarding the PR! I ran it locally and it fixed the issue loading the example gltf above and a couple of other files I had lying around
(first timer :+1: )

**Comment by mrdoob** [comment]
@ryans1224 can this be closed?

**Comment by ryans1224** [comment]
@mrdoob Yes, thanks to all
