### ISSUE TITLE
allow FileLoader to read Cache even if it is disabled

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#20850]
I want to load zipped version of bin file referenced by gltf, and put this into Cache before gltf is loaded, so that it reads bin file from Cache. However, if the Cache is enabled, any other file that is loaded in parallel will be saved there for no reason.

**Describe the solution you'd like**

remove [line 19](https://github.com/mrdoob/three.js/blob/master/src/loaders/Cache.js#L19)

**Describe alternatives you've considered**

alternatively separate write and read permissions

**Additional context**

n/a

**Comment by Mugen87** [comment]
> remove line 19

Do you mind explaining in more detail how removing the mentioned line solves your issue? It seems to me the feature request is the possibility to configure the caching behavior per load request.

**Comment by makc** [comment]
I did no actually remove line 19 here but did this:
```js
THREE.Cache.get = function(key) { return this.files[key]; };
```
which has the same effect.
> how removing the mentioned line solves your issue

because Cache.set still checks enabled, which is set to false, none of the files loaded via FileLoader are cahced, at the same time the buffer I manually place in Cache is being read when gltf is parsed.

**Comment by makc** [comment]
> It seems to me the feature request is the possibility to configure the caching behavior per load request.

yes, if we had a way to decide which request is cached it would also solve this, but that seems like a more complex change, no?

**Comment by Mugen87** [comment]
> the buffer I manually place in Cache

Ah, that was the missing bit. Except for `THREE.Cache.enabled`, the class is an internal thing and not intended for user access. So a different solution is required here.

**Comment by makc** [comment]
> a different solution

well, I could be loading gltf maually, replacing buffer links with base64, and then have the loader load data uri again even though I already had a buffer. all of this just to keep your Cache private? I dont think so :)

**Comment by Mugen87** [comment]
If `Cache.enabled` is set to `false`, it means it is disabled. So you can't add nor read objects from it. This semantic won't be changed.

Like I said above, it seems the actual (more consistent) feature request is the ability to configure the cache per request. I think it's better to make a new feature request for this than pursuing the idea from this issue.
