### ISSUE TITLE
GLTFLoader: Objects not found under original name, regression from r119 -> r123

### ISSUE THREAD

**Issue by Friksel** [mrdoob/three.js#20867]
**Describe the bug**
After upgrading three to r123 on a working project, that was before using r119, three cannot find some Camera's anymore. Strangely enough it can find some cameras, but not others. It doesn't seem to be related to ortographic vs perspective. It looks like the problem arrises only with nested camera's, so cameras within other 3D objects. But I'm not completely sure yet.

I've read all migration guides from r119 -> r120 up to the last one, but cannot find anything in there that should cause this IMO.

I'm still debuging, but so far this seems to be the issue: `getObjectByName()` can find some camera's, but others return `undefined` so cannot be found in the scene loaded by gltf. Before this was working fine, the only thing I needed to do before was traverse this object, because for some reason camera's are wrapped inside some object in gltf. But now even the wrapper object cannot be found. It is still in the gltf or glb though, nothing changed to the data.
```
const cameraWrap = scene.getObjectByName(camName);
```

I keep you informed if I know more when exactly this happens. But for now please let me know if something has changed that could cause this that I should be aware of! Thanks

**To Reproduce**

1. Create a scene with objects and camera's in blender (probably the problem occurs when cameras are nested (and nested) within 3D objects, but not sure yet)
2. Use the blender gltf or glb export to export to gltf or glb
3. Import the gltf or glb in three to get the scene
4. Try to get the cameras by using `scene.getObjectByName(camName)`

***Code***

```js
scene.getObjectByName(camName)
```

**Expected behavior**

Nothing changed in three version according to the migration guide around cameras or objects AFAIK, so I would expect this to still work in r123.

**Platform:**

 - Device: Desktop/Mobile
 - OS: Windows
 - Browser: Edge Chromium
 - Three.js version: r123

**Comment by Friksel** [comment]
Ah, I've just notices another issue here on github about the loader which could be very much related to and the cause of the gltf camera issue here:

https://github.com/mrdoob/three.js/issues/20843

The other issue is talking about issues where the loader is stripping underscores from object-names during gltf import.

The camera wrappers the gltf exporter inside Blender is creating around cameras is also using underscores. It creates objects like 'TopCam0_Orientation'.

So I wouldn't be surprised if the exact same cause is creating this issue.

**Comment by donmccurdy** [comment]
Could you share an example of a model affected by this issue?

**Comment by donmccurdy** [comment]
>  That issue is talking about problems where the loader is stripping underscores from object-names during gltf import.

The loader does not strip underscores from object names — issue #20843 is incorrect in that regard. The loader does replace spaces and other characters that are invalid in the three.js animation system. It also appends a suffix to some object names to prevent duplicates, and the logic for de-duplication was updated in recent versions of three.js. The safest way to ensure that your objects have the expected name is to ensure that the object has a unique and valid name. If you can share an example we would be able to determine more specifically what may be going wrong here.

**Comment by makc** [comment]
> The loader does replace spaces and other characters....  It also appends a suffix to some object names to prevent duplicates

[related](https://github.com/mrdoob/three.js/issues/15087#issuecomment-740310839)

**Comment by Friksel** [comment]
> Could you share an example of a model affected by this issue?

Sorry, it would take too much to strip the project down and create something I can send you and I don't have the time for that. But I described above how to recreated it so you should be able to see the issue after doing that. 

For now I had to switch back to the old version to make it work again.

**Comment by donmccurdy** [comment]
The issue I'm aware needs to be fixed is what's mentioned in https://github.com/mrdoob/three.js/issues/20843#issuecomment-740085335 — sometimes the object name sanitization is _not_ applied to names when it should be. I plan to fix that.

I have no idea whether that will fix the issue you're seeing, though. The process generating objects names — if they don't already have unique, valid names — has changed intentionally in recent versions, and there is no plan to revert #16639 from r121. The cams that cannot be found anymore in your example presumably didn't have unique names, and now have a suffix appended to uniquely identify them. If that's the case, then because `getObjectByName` depends on scene traversal order, it would have been arbitrary which object was returned for the given name.

**Comment by Friksel** [comment]
>The cams that cannot be found anymore in your example presumably didn't have unique names, and now have a suffix appended to uniquely identify them. If that's the case, then because `getObjectByName` depends on scene traversal order, it would have been arbitrary which object was returned for the given name.

All cameras have unique names in Blender and I'm using the blender built in gltf exporter (blender 2.9). This project I'm working on for some years now and the camera's didn't change for at least 2 years. If there were duplicated names the camera's wouldn't work and I would have noticed years ago.

If I get you right duplicate names get a suffix. But than I would expect the first one to not get a suffix, so still to be found by `getObjectByName`, but it's not finding these objects anymore. So it's not finding the wrong object, it's finding no object at all with those camera's.

The issue only seems to be there when camera's are nested inside other objects.

Hope this helps

**Comment by donmccurdy** [comment]
> So even if I would have duplicate names than I would still expect the first one to not get a suffix, so still to be found by getObjectByName...

Can't guarantee that the object `getObjectByName` finds first is also the object that the hierarchy construction finds first, but  yeah, it does seem like at least one object should still have the original name if this were the cause. 

Perhaps this is https://github.com/mrdoob/three.js/issues/20843#issuecomment-740085335 after all then. Sorry, I can't say for sure, without knowing the original names in the glTF file and what they're actually getting renamed to.

**Comment by Friksel** [comment]
@donmccurdy 

I just dove deeper into this issue and compared the behaviour of r117 with r123. They are clearly different as expected, so I tried to understand what's the difference.

I created a new file in Blender with this hierarchy:
```
group (= empty object)
   subgroup (= empty object)
     cam (= blenders camera instance (orange icon))
        cam (= blender actual camera (green icon), blender always creates two steps in hierarchy for a camera)
```

And tested two scenarios both in r117 (where both work) and in r123 (where the issue is):
1) One with both the camera instance as well as the actual camera in Blender having different names
2) One with both the camera instance as well as the actual camera in Blender having both the same name


**Scenario 1: both the camera instance as well as the actual camera in Blender having different names**
hierarchy names in Blender/gltf:
```
group (= empty object)
   subgroup (= empty object)
     camInstance (= blenders camera instance (orange icon))
        cam (= blender actual camera (green icon), blender always creates two steps in hierarchy for a camera)
```
**both r117 as well as r123 work the same and work as expected:**
•	`this.scn.getObjectByName('cam')` --> `undefined`
•	`this.scn.getObjectByName('camInstance')` --> returns object3D object with name `camInstance`
•	`this.scn.getObjectByName('camInstance').isCamera` --> returns `undefined`
•	`this.scn.getObjectByName('camInstance').children` --> returns `[PerspectiveCamera object]`
•	`this.scn.getObjectByName('camInstance').children[0].isCamera` --> returns `true`


**Scenario 2: both the camera instance as well as the actual camera in Blender having the same name**
hierarchy names in Blender/gltf:
```
group (= empty object)
   subgroup (= empty object)
     cam (= blenders camera instance (orange icon))
        cam (= blender actual camera (green icon), blender always creates two steps in hierarchy for a camera)
```
**r117**
r117 still works exactly the same as in scenario 1, so as expected:
•	`this.scn.getObjectByName('cam')` --> `undefined`
•	`this.scn.getObjectByName('camInstance')` --> returns object3D object with name `camInstance`
•	`this.scn.getObjectByName('camInstance').isCamera` --> returns `undefined`
•	`this.scn.getObjectByName('camInstance').children` --> returns `[PerspectiveCamera object]`
•	`this.scn.getObjectByName('camInstance').children[0].isCamera` --> returns `true`

**r123**
r123 on the other hand cannot even complete the first step; cannot find the camera:
•	`this.scn.getObjectByName('cam')` --> returns `undefined`

See below for gltf files used for this test.

**Conclusion:**
There is no way to let threejs find the camera in the latest versions (for example r123) when the cameraInstance and the camera object in Blender/Gltf/glb have the same name. This was not an issue and perfectly possible in r117/r120 though. 

IMO there is no need to have different names for the cameraInstance object and the camera object itself, as in the gltf/glb one is always in the `nodes` section together with its child (the actual camera) and one (the camera settings) will only be available in the `cameras` section in the gltf/glb. This is IMO the reason why it could work fine in the older version without a problem.

Still one thing I don't get though, and that is why some camera's DID work in the original project in r123. So my guess is there is another issue at play here too and that that's another thing to check that's besides this point. If I know more about that I'll let you know.

**GLTF files used**

**gltf where camInstance and cam have different names**
``` json
{
    "asset" : {
        "generator" : "Khronos glTF Blender I/O v1.3.48",
        "version" : "2.0"
    },
    "scene" : 0,
    "scenes" : [
        {
            "name" : "Scene",
            "nodes" : [
                3
            ]
        }
    ],
    "nodes" : [
        {
            "camera" : 0,
            "name" : "camInstance_Orientation",
            "rotation" : [
                -0.7071067690849304,
                0,
                0,
                0.7071067690849304
            ]
        },
        {
            "children" : [
                0
            ],
            "name" : "camInstance",
            "rotation" : [
                0.7071068286895752,
                0,
                0,
                0.7071068286895752
            ],
            "translation" : [
                8.766791343688965,
                0.8265642523765564,
                -15.014936447143555
            ]
        },
        {
            "children" : [
                1
            ],
            "name" : "subgroup",
            "translation" : [
                0.45298290252685547,
                -0.18702220916748047,
                -0.7950639724731445
            ]
        },
        {
            "children" : [
                2
            ],
            "name" : "group"
        }
    ],
    "cameras" : [
        {
            "name" : "cam",
            "perspective" : {
                "aspectRatio" : 1.7777777777777777,
                "yfov" : 0.564243568051773,
                "zfar" : 28,
                "znear" : 0.009999999776482582
            },
            "type" : "perspective"
        }
    ]
}
```

**gltf file where camInstance and cam have the same name**
``` json
{
    "asset" : {
        "generator" : "Khronos glTF Blender I/O v1.3.48",
        "version" : "2.0"
    },
    "scene" : 0,
    "scenes" : [
        {
            "name" : "Scene",
            "nodes" : [
                3
            ]
        }
    ],
    "nodes" : [
        {
            "camera" : 0,
            "name" : "cam_Orientation",
            "rotation" : [
                -0.7071067690849304,
                0,
                0,
                0.7071067690849304
            ]
        },
        {
            "children" : [
                0
            ],
            "name" : "cam",
            "rotation" : [
                0.7071068286895752,
                0,
                0,
                0.7071068286895752
            ],
            "translation" : [
                8.766791343688965,
                0.8265642523765564,
                -15.014936447143555
            ]
        },
        {
            "children" : [
                1
            ],
            "name" : "subgroup",
            "translation" : [
                0.45298290252685547,
                -0.18702220916748047,
                -0.7950639724731445
            ]
        },
        {
            "children" : [
                2
            ],
            "name" : "group"
        }
    ],
    "cameras" : [
        {
            "name" : "cam",
            "perspective" : {
                "aspectRatio" : 1.7777777777777777,
                "yfov" : 0.564243568051773,
                "zfar" : 28,
                "znear" : 0.009999999776482582
            },
            "type" : "perspective"
        }
    ]
}
```

**Comment by makc** [comment]
@Friksel 
> IMO there is no need to have different names for the cameraInstance object and the camera object itself

in your case, but not the others (which involve animation). which is why I was asking about opt-out mechanism in https://github.com/mrdoob/three.js/issues/20867#issuecomment-742450497

**Comment by Friksel** [comment]
> @Friksel
> 
> > IMO there is no need to have different names for the cameraInstance object and the camera object itself
> 
> in your case, but not the others (which involve animation). which is why I was asking about opt-out mechanism in [#20867 (comment)](https://github.com/mrdoob/three.js/issues/20867#issuecomment-742450497)

Not sure what you mean by 'Your case'. This is not a special case, but always the case when using Camera's from gltf. Nothing to do with animations.
The lib is changing names of cameras under the hood which isn't needed, as, like I wrote before, the objects are in completely different sections in the gltf. So it can only cause confusion and errors.

Next to the issue that it's not possible now to have the same name for the camera and the camera instance (which was working before so changed for the worse):
IMO renaming stuff under the hood without us knowing is not only extra code in the lib that doesn't fix any issue, it's also causing confusion and potential errors when objects cannot be found.
As a developer I don't like the idea of a lib being forgiving to issues and tries to fix them (that can lead to other errors), so the real issues in the file don't get fixed.

So if with opt-out mechanism you mean to be able to turn this 'auto-correct' feature off, I'm all for it!

**Comment by donmccurdy** [comment]
An opt-out method is proposed in https://github.com/mrdoob/three.js/pull/16639#issuecomment-797653487, if someone would like to open a PR and confirm it fixes this issue.

> it would be better to never rename and just throw an error message to the user ... it's better to think of a developer as a mature developer, not as a beginner...

I'm afraid even experienced developers will disagree on whether duplicate names are "errors." The glTF specification does not require unique names, so the file is 100% valid and will play animation in other glTF viewers. three.js does require unique names for animation to work, and so GLTFLoader has the responsibility of turning a valid glTF file into valid three.js objects. No single perfect solution here, so I think the opt-out method is a reasonable choice.

**Comment by Friksel** [comment]
@donmccurdy I'm very sorry for the late response. For some reason I didn't get that last message with the opt-out method, so I didn't know about it until I found it today.

That opt-in method `setUniqueNames()` is a great solution and it's solving my workflow, thanks a lot for this!

However, the method cannot be found in the whole threejs lib (anymore) in r136. It's also missing in the docs, at least I cannot find it anywhere: https://threejs.org/docs/#examples/en/loaders/GLTFLoader

To keep things organized I open a new thread for this.

**Comment by Friksel** [comment]
@donmccurdy according to @Mugen87 the `setUniqueNames()` function was never implemented. It's now pretty much a year later. I wouldn't say there's any problem to implement this setting to whoever likes to have the same behaviour as it is now, as it's only optional to set it to `false`.

Could the `setUniqueNames()` please be implemented like you wrote in https://github.com/mrdoob/three.js/pull/16639#issuecomment-797653487 ?

Thanks!

**Comment by donmccurdy** [comment]
Hi @Friksel – sorry for the confusion here. In the comment https://github.com/mrdoob/three.js/issues/20867#issuecomment-812722442 I was trying to say that if someone would like to implement this, I would be OK with a pull request adding the `setUniqueNames(...)` method to GLTFLoader. I am not planning to implement the new method myself however. 

On second thought, a property `loader.allowDuplicateNames = true` might be better.

**Comment by donmccurdy** [comment]
We're still open to accepting a PR for an opt-out method, to prevent GLTFLoader from de-duplicating names. But I think someone who has a use case for the feature will need to implement and test it, this is not otherwise on the roadmap.
