### ISSUE TITLE
MeshStandardNodeMaterial doesn't render mask properly

### ISSUE THREAD

**Issue by n2k3s2it** [mrdoob/three.js#20868]
**Describe the bug**
Setting the `mask` property of a `MeshStandardNodeMaterial` doesn't seem to be properly rendered.
Tested in r123

**To Reproduce**
See the live example below:
https://codesandbox.io/s/infallible-buck-w15hg?file=/src/index.js
A fully rendered teapot is visible.

**Expected behavior**
I expected the bottom half of the teapot pixels to be masked (i.e. not rendered).

This works when using a `PhoneNodeMaterial`.
And can be seen in the example by changing line 62 `usePhongNodeMaterial` to `true`.

**Comment by Mugen87** [comment]
Using `StandardNodeMaterial` instead of `MeshStandardNodeMaterial` fixes the issue.
