### ISSUE TITLE
async animationloop

### ISSUE THREAD

**Issue by sjpt** [mrdoob/three.js#20886]
**Is your feature request related to a problem? Please describe.**
Yes, the extra complication coding of certain animation loops, in particular those containing streamed reads.

In order to keep responsiveness and frame rate as high as possible, the code inside most animation loops need to be as short as possible, and to avoid asynchrony.
However, there are some scenarios where it is more efficient (and easier to code) to have asynchrony within the animation loop.

An example is where a large file of 'frame parameters' is streamed (note !!! below) from the server to the client to generate an animation. Each frame, the client reads the next frame's parameters from the stream, and renders the frame using these parameters. The available methods for reading from the stream are all asynchronous, but are generally likely to be resolved extremely fast once the stream is established, as the data will already have been transmitted to the client. The easiest way to code for this is for the client to code the animation loop as `async`, and to include `await` on the stream read function. However, this does not behave if the loop controller (`onAnimationFrame`)  does not call the loop with `await`.

Despite reservations about asynchrony, an async animation loop may also provide  the most responsive solution. Where rendering a frame takes a significant time it is quite likely that certain frames will get rendered more than once if the `requestAnimationFrame()` is issued too soon; the overhead of this may well be greater than the overhead of the `await` within the loop.

**Describe the solution you'd like**
I'd like the call to `animationLoop` in `onAnimationFrame` to include 'await', requiring `onAnimationFrame` to be `async`.
Complications of XR mean this needs to be done in three places: `WebGLAnimation`, `WebXRManager` and `WebGLRenderer`.

This will not change what happens in the majority of situations, the animation loop will return in it's usual way and the awaits will never need to await. However, it will permit the programming pattern outlined above.

**Describe alternatives you've considered**
It is fairly easy enough to organize one's own animation loop with appropriate `await`; though made more complicated by XR animation, to ensure the other features implemented in `WebXRManager.onAnimationFrame` are applied.

(We often code our own animation loop control anyway to resolve the wasted rendering issues of https://github.com/mrdoob/three.js/issues/20131)

The user animation loop code (eg 'render') can start with `renderer.setAnimationLoop(null);` and end with  `renderer.setAnimationLoop( render );` but this risks two requests to `context.requestAnimationFrame()` for each frame, which may be an issue (not sure on details here).

It is possible (but awkward and possibly inefficient) to arrange the asynchrony in some other way

**Additional context**
(!!!) The source of the stream may be realtime code at the server rather than a file; and there are different ways the client may arrange to read the incoming stream, but these do not affect the principle.

There is a similar scenarios where the render loop needs to synchronize with work done in WebWorkers.

**Comment by sjpt** [comment]
I have realized this will not work in XR because of the strict XR rendering rules.

**Comment by sjpt** [comment]
This `async/await solution` _will_ work after all, as long as all user rendering (at least, all rendering to the XR framebuffer) is performed before any `await` in the user code, and remains a robust and simple solution to the issue.

I have been looking a bit more into the current WebGLAnimation for alternative solutions.  It is quite confusing in XR with two WebGLAnimation animation instances running in parallel, one firing sensible `requestAnimationFrame()` to the XR context, and one firing `window.requestAnimationFrame()` calls which return almost immediately. This confusion makes it more difficult to write alternative animation loop sequences.

One small change that would also help is if the code in `WebXRManager.onAnimationFrame` (minus the final callback) was exposed as helper code (maybe `WebXRManager.prepareAnimationFrame`) that alternative animation loop code could share.

**Comment by Mugen87** [comment]
TBH, I'm not sure I fully understand your use case. Please show with a simple [live example](https://jsfiddle.net/f2Lommf5/) why your proposed change is required.

**Comment by mrdoob** [comment]
Sorry, animation loops can't be async.

You can achieve what you're trying to do by having two loops. One synchronous for rendering and a asynchronous one for fetching/streaming the data.
