### ISSUE TITLE
Animation issues with threejs, interpreted incorrectly

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#20889]
[Donkey-play-Violin.zip](https://github.com/mrdoob/three.js/files/5692438/Donkey-play-Violin.zip)
**Describe the bug**

I exported an animation from one of our current projects but noticed that modelviewer/threejs have trouble with it; it seems that the animation is interpreted incorrectly. There are some warnings but I think they should not cause this behaviour, especially as it works fine in other viewers.

**To Reproduce**

1. Go to https://gltf-viewer.donmccurdy.com/
2. Import the attached file
3. Go to https://sandbox.babylonjs.com/
4. Import the attached file
5. Note that Babylon exhibits the correct (desired) behaviour, same as Microsoft 3D Viewer.

**Expected behavior**

Correct animation playback.
![20201215-014603](https://user-images.githubusercontent.com/2693840/102153382-61eec380-3e77-11eb-9ab7-dcf2c299d08d.gif) 
(correct, Babylon sandbox)

**Screenshots**

![20201215-014550](https://user-images.githubusercontent.com/2693840/102153386-64e9b400-3e77-11eb-91cf-1b1976bca562.gif)
(Incorrect, threejs)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]

**EDIT:** I believe this is because objects have different hierarchies but the same object names that are differently animated, and seems three doesn't take the object hierarchy into account when animating, only the object name?

**Comment by donmccurdy** [comment]
Hm, object naming shouldn't be the issue, in recent versions we append a suffix to object names to ensure they're unique for this reason. There are a few warnings printed by the glTF-Validator on this one:

![Screen Shot 2020-12-14 at 7 22 54 PM](https://user-images.githubusercontent.com/1848368/102166924-21288780-3e42-11eb-96d9-7b64a7e2c489.png)

The file's not invalid (the skinned mesh doesn't _have_ to be at the root of the scene) but viewers have to treat it as though it were, so it's often better and safer to put it there. I thought we handled these cases correctly either way, but it's possible something fails here.

**Comment by hybridherbst** [comment]
Thank you!

Two more thoughts,
- could it be that other viewers are "overachieving" in a sense and (despite the warning) correctly interpreting local transforms for skinned meshes? I tried an entire group of characters (placed next to each other, so with a moved skinned mesh each) and it worked fine in others while breaking threejs
- for this particular example, I'm pretty certain that the two skinned meshes (the donkey and the violin - I'm not sure why it was built that way) are placed at the same position, so the warning shouldn't really be relevant (they are separate skinned meshes but with no offset to each other)

**Comment by Mugen87** [comment]
@hybridherbst This issue seems to be fixed on `dev`. Please double-test this by drag'n'drop the asset into the editor:

https://raw.githack.com/mrdoob/three.js/dev/editor/index.html

You can start playing the animation from the sidebar (`ANIMATIONS` section).

**Comment by Mugen87** [comment]
It seems #20880 did the trick.

**Comment by hybridherbst** [comment]
@Mugen87 you could have at least given me a chance to try this out before closing 🙃

Can confirm it works for the attached model. I'll try a more complex one over the next days and open another issue if necessary.

**Comment by hybridherbst** [comment]
Complex example also seems to work :) Happy Holidays!
![201217-130922](https://user-images.githubusercontent.com/2693840/102486282-1996f780-4069-11eb-8edb-bd2fee5a80fa.gif)
