### ISSUE TITLE
Draco decoding errors result in uncaught promise rejections.

### ISSUE THREAD

**Issue by twastvedt** [mrdoob/three.js#20883]
**Describe the bug**

When decoding a GLTF model with Draco compression, in some cases if the decoding process fails a promise in GLTFLoader is rejected but not caught. Thus in my code neither the onError nor the onLoad arguments are ever executed. 

I believe I have a fix here: https://github.com/mrdoob/three.js/compare/dev...twastvedt:dracoCatchPromise. Tested with the Draco example. I'm happy to create a PR, but I'm sure I'm ignorant of what all is at play here, so wanted to make sure first. My fix substitutes the current use of `decodeDracoFile`, which is marked deprecated in DRACOLoader, with `decodeGeometry`, which returns a promise that we can catch.

**To Reproduce**

1. Go to https://jsfiddle.net/srq463dg/
2. Note that in the console the onError method (line 58) never executes.
3. Open developer tools and note that an error has occurred in the Draco loader ("THREE.DRACOLoader: Decoding failed: Failed to decode point attributes").

Note: The `errorModel` data url in the fiddle is a valid gltf model that has been truncated. In my app's environment there is a string length limit imposed on models, thus this entire investigation.

***Code***

```js
loader.load(errorModel, function (data) {
    		console.log("Loaded model");
        scene.add(data.scene);
    }, null, function (error) {
    	console.log(`In error handler: ${error}`);
    });
```

**Expected behavior**

Any error in the Draco loader should cause the `onError` argument of `GLTFLoader.load` to be executed.

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: dev

**Comment by donmccurdy** [comment]
Thanks for the report!

I agree we should try to get GLTFLoader to not call the older `decodeDracoFile` method. Using `decodeGeometry` looks like a good choice, although I'm not sure we want to expose the details of the `taskConfig` object, maybe the method signature should change to hide that.

Aside — the error sounds like your Draco-compressed data contains points and not just triangles, which wouldn't ordinarily be valid in the glTF Draco extension... is that something you're aware of?

**Comment by twastvedt** [comment]
OK, that makes sense. I could do that. Something similar to `decodeDracoFile`? I'm not sure of the protocol for breaking changes - is that a concern?

Thanks for the note. I'm making these models elsewhere programatically, so I'm pretty sure they don't actually contain points. Might chopping off an arbitrary number of characters at the end of the data url cause such a misread? I did get a variety of other errors trying to create a smaller failing demo string.

**Comment by donmccurdy** [comment]
It'd be OK to keep `decodeDracoFile` around in its current form for now, and just have GLTFLoader use a different method. So no breaking change until we eventually decide to remove the deprecated method. 👍

> Might chopping off an arbitrary number of characters at the end of the data url cause such a misread?

Ah, it might. I'm not sure how the internals of the Draco decoder works but it sounds plausible.

**Comment by twastvedt** [comment]
@donmccurdy Sorry for the delay, but I'm hoping to get back to this and resolve it. I'm uncertain how to follow your comment though:

> Using `decodeGeometry` looks like a good choice, although I'm not sure we want to expose the details of the `taskConfig` object, maybe the method signature should change to hide that.

(methods in question: https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/DRACOLoader.js#L91-L203)

My best guess is this, but maybe I'm missing something:

1. Creating a third method (`decodeDracoGeometry`?) with the preferred signature: `decodeDracoGeometry( buffer, attributeIDs, attributeTypes, useUniqueIds )`.
2. Move the contents of `decodeGeometry` into the new method.
3. Make `decodeGeometry` call the new method, as `decodeDracoFile` does now.

Thanks!

**Comment by donmccurdy** [comment]
I think we may need to overhaul DRACOLoader a bit anyway (see https://github.com/mrdoob/three.js/issues/22445 ...) and have it use the new WorkerPool utility. Probably better to resolve this all at the same time, I'll self-assign it in that case.

**Comment by fanciful-marmot** [comment]
I've run into a similar unhandled promise rejection error with DRACO decoding in some environments where there isn't enough memory for the wasm decoder to run properly. I get an unhandled promise rejection with `memory access out of bounds`. I can setup an example that illustrates the problem if needed but it's similar to what's described in the issue. 

It would be great if I could handle the error properly and fallback to something else. Is there an update on this issue?
