### ISSUE TITLE
XYZLoader not loading colours

### ISSUE THREAD

**Issue by elliottkember** [mrdoob/three.js#20893]
**Describe the bug**

When importing an XYZRGB point cloud, the pixels are all white instead of the expected colors.

The XYZLoader seems to be loading the values, and setting the colours, including calling `geometry.setAttribute` correctly, but the WebGLRenderer isn't rendering the particles with their values.

**To Reproduce**

• Update the `helix_201.xyz` file to include RGB values after the XYZ values on each line:
• Load the XYZ file using the XYZLoader
• See that all the XYZ coordinates are white!

***Code***

helix_201.xyz with RGB values (all purple):
https://github.com/elliottkember/three.js/blob/elliottkember-xyz-rgb/examples/models/xyz/helix_201.xyz

![image](https://user-images.githubusercontent.com/42827/102294305-de2bea00-3efd-11eb-8ae0-e0b23668f675.png)

Loader implementation:
```js
  const loader = new XYZLoader();
  loader.load("./helix.xyz", function (geometry) {
    geometry.center();

    const material = new THREE.PointsMaterial({ size: 0.1 });

    points = new THREE.Points(geometry, material);
    scene.add(points);
  });
```

***Live example***

https://elliottkember.github.io/three.js/examples/webgl_loader_xyz.html

**Expected behavior**

The dots should all be purple.

**Screenshots**

![image](https://user-images.githubusercontent.com/42827/102294284-ceaca100-3efd-11eb-9cf0-bb49b646a4ac.png)

![image](https://user-images.githubusercontent.com/42827/102294626-948fcf00-3efe-11eb-83fe-52405f6d98a5.png)

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: 123

**Comment by elliottkember** [comment]
I figured it out!

The example file has:

`const material = new THREE.PointsMaterial( { size: 0.1 } );`

What I needed was:

`const material = new THREE.PointsMaterial( { size: 0.1, vertexColors: THREE.VertexColors } );`

**Comment by Mugen87** [comment]
> const material = new THREE.PointsMaterial( { size: 0.1, vertexColors: THREE.VertexColors } );

The new style looks like so:
```js
const material = new THREE.PointsMaterial( { size: 0.1, vertexColors: true } );
```

**Comment by mrdoob** [comment]
@Mugen87 Maybe we can use a xyz sample file with colors?

**Comment by Mugen87** [comment]
I could not one I've used for testing so I went for the existing free helix asset. However, we could also add this in the example code to improve clarity:
```js
const vertexColors = ( geometry.hasAttribute( 'color' ) === true );

const material = new THREE.PointsMaterial( { size: 0.1, vertexColors: vertexColors } );
```

**Comment by mrdoob** [comment]
Yeah, I think that works 👍
