### ISSUE TITLE
Rotation on world axis unreliable

### ISSUE THREAD

**Issue by brez422** [mrdoob/three.js#20898]
**Describe the bug**

A quaternion is being applied in Local Space when I expect it to be applied in World Space. What's odd is that subsequent rotations are being applied to World Space as expected. If I swap the order in which the rotations are applied, the first rotation will always be in Local Space, with the following rotations in World Space as expected.

**To Reproduce**

1. Set up and run https://pastebin.com/G3FEqSv4
2. Use e s d f w r Keys to move it around
3. After the axesHelper has moved off the World Space axes, stop it with "q".
4. Press e or d. The axesHelper will rotate in Local Space instead of World Space. This is a problem. I need to rotate it in World Space.
5. Press q, then s or f. It will rotate in World Space as expected.
6. Press q, then w or r. It will rotate in World Space as expected.

***Code***

```js
  nav.applyQuaternion( new THREE.Quaternion().setFromAxisAngle(
    new THREE.Vector3( 1, 0, 0 ), xSpinTotal ) );
```

***Live example***

* See https://pastebin.com/G3FEqSv4

**Expected behavior**

I expect it to rotate in World Space.

**Screenshots**

N/A. This is an animation issue.

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Firefox 83.0
 - Three.js version: [dev, r123]

**Comment by brez422** [comment]
I went looking for help on stack exchange to no avail:
https://stackoverflow.com/questions/65329175/how-can-i-reliably-rotate-in-world-space-in-three-js

Perhaps my question was to convoluted so I asked a simpler question:
https://stackoverflow.com/questions/65345087/how-to-rotate-on-world-axes-in-three-js

I've looked at similar questions and answers, but nothing seems to speak to the level of complexity involved in my case.

**Comment by Mugen87** [comment]
GitHub is not intended for help requests.
