### ISSUE TITLE
GLTFExporter：threejs exported glTF file is not valid glTF file？

### ISSUE THREAD

**Issue by salamander-mh** [mrdoob/three.js#20917]
this is my glTF file：

[sample.gltf.zip](https://github.com/mrdoob/three.js/files/5722366/sample.gltf.zip)

I have tested the file in `gltf-viewer.donmccurdy.com`, and got many errors： 

<details>

<summary>Errors: </summary>

|Error|Message|Pointer|
|--- |--- |--- |
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/accessors/104/min|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/accessors/104/min|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/accessors/104/min|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/accessors/104/max|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/accessors/104/max|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/accessors/104/max|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/nodes/2/matrix|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/nodes/2/matrix|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/nodes/2/matrix|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/nodes/2/matrix|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/nodes/2/matrix|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/nodes/2/matrix|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/nodes/2/matrix|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/nodes/2/matrix|
|ARRAY_TYPE_MISMATCH|Type mismatch. Array element null is not a 'number'.|/nodes/2/matrix|
|MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS|accessor.min and accessor.max must be defined for POSITION attribute accessor.|/meshes/26/primitives/0/attributes/POSITION|
|ACCESSOR_INVALID_FLOAT|Accessor element at index 0 is NaN.|/accessors/104|
|ACCESSOR_INVALID_FLOAT|Accessor element at index 1 is NaN.|/accessors/104|
|ACCESSOR_INVALID_FLOAT|Accessor element at index 2 is NaN.|/accessors/104|
|ACCESSOR_INVALID_FLOAT|Accessor element at index 3 is NaN.|/accessors/104|
|ACCESSOR_INVALID_FLOAT|Accessor element at index 4 is NaN.|/accessors/104|
|ACCESSOR_INVALID_FLOAT|Accessor element at index 5 is NaN.|/accessors/104|
|ACCESSOR_INVALID_FLOAT|Accessor element at index 6 is NaN.|/accessors/104|
|ACCESSOR_INVALID_FLOAT|Accessor element at index 7 is NaN.|/accessors/104|
|ACCESSOR_INVALID_FLOAT|Accessor element at index 8 is NaN.|/accessors/104|

</details>

**Comment by donmccurdy** [comment]
Could you share the code used to create your scene and to export it to glTF? Not all features in three.js that can be exported to standard file formats.

(Note: I've edited the comment to make it easier to read – you can attach ZIP files to GitHub comments with files needed to understand the issue 🙂 )

**Comment by salamander-mh** [comment]
@donmccurdy thks, I've found some problem in the exported file：
### bufferView max/min have null value
```
{
      "bufferView": 104,
      "componentType": 5126,
      "count": 8,
      "max": [
        null,
        null,
        null
      ],
      "min": [
        null,
        null,
        null
      ],
      "type": "VEC3"
    },
```

### matrix have null value
if I change `null` to `0`, the VS Code glTF extension tell me `Matrix must be decomposable to TRS.glTF`

```
{
      "matrix": [
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        0,
        null,
        null,
        null,
        0,
        0.45,
        2.47,
        0,
        1
      ],
      "name": "H_HL",
      "children": [
        0,
        1
      ]
    },
```

**Comment by Mugen87** [comment]
@salamander-mh The idea is to share your application code. If you don't do this, it is not possible to investigate this issue.

**Comment by mrdoob** [comment]
Closing until @salamander-mh is able to provide that code that is generating the gltf.
