### ISSUE TITLE
The WASM DRACOLoader silently fails on OSX Safari intermittently

### ISSUE THREAD

**Issue by paul-gauthier** [mrdoob/three.js#20914]
Loading a GLB with draco compression will randomly fail on OSX Safari when using the WASM decoder. It works reliably with the JS decoder, but decoding is much slower. The failure seems to happen more frequently with large GLB files.

**To Reproduce**

Simply load a large draco GLB model in the recommended way in OSX Safari. Occasionally the onLoad callback will fail to fire. It may take 20+ attempts to see the failure. It is randomly intermittent.

Grab one of these large GLBs that use draco compression:

https://storage.googleapis.com/wallspice-assets/draco/poeng_draco.glb
https://storage.googleapis.com/wallspice-assets/draco/christmas_tree_deco_draco.glb

```
const loader = new GLTFLoader().setPath('path/to/glb/');
const dracoLoader = new DRACOLoader();
dracoLoader.setDecoderPath('//www.gstatic.com/draco/v1/decoders/');
loader.setDRACOLoader( dracoLoader );
loader.load('christmas_tree_deco_draco.glb', function ( gltf ) { console.log('loaded!'); });
```

I have traced the execution, and when it fails the code seems to call into `decoder.DecodeBufferToMesh` and never comes back.

https://github.com/mrdoob/three.js/blob/d92c3085aa6e6c373d339a7fdd9bccf8b9e4c5f5/examples/jsm/loaders/DRACOLoader.js#L489

***Live example***

This issue is reproducible on the public McCurdy viewer. Open Safari and reload the following URL repeatedly. It fails to load them model every so often. It make take 20+ reloads to see the failure.

https://gltf-viewer.donmccurdy.com/#model=https://storage.googleapis.com/wallspice-assets/draco/poeng_draco.glb
https://gltf-viewer.donmccurdy.com/#model=https://storage.googleapis.com/wallspice-assets/draco/christmas_tree_deco_draco.glb

**Expected behavior**

The model should load correctly every time.

**Platform:**

 - Device: Desktop
 - OS: MacOS 10.15.7
 - Browser: Safari Version 14.0
 - Three.js version: dev

**Comment by mrdoob** [comment]
This looks like should be reported to Safari instead: https://bugs.webkit.org/

**Comment by satazor** [comment]
@paul-gauthier I'm having the same issue. Did you managed to circumvent the problem somehow or did you end up reporting the bug?
