### ISSUE TITLE
Be able to use rotation matrix of 3x3 : THREE.Quaternion().setFromRotationMatrix(matrix3)

### ISSUE THREAD

**Issue by remmel** [mrdoob/three.js#20921]
Currently `THREE.Quaternion().setFromRotationMatrix(matrix4)` uses a `THREE.Matrix4`
As a rotation can be stored in a `Matrix3`, it could be great to be able to use also directly a `THREE.Matrix3`

Currently I convert myself the matrix using something like:
```
var m3arr = m3.elements;
var m4 = new Matrix4().fromArray([
    m3arr[0], m3arr[1], m3arr[2],0,
    m3arr[3], m3arr[4], m3arr[5],0,
    m3arr[6], m3arr[7], m3arr[8],0,
    0,0,0,1
]);
m4.transpose();
var q = new THREE.Quaternion().setFromRotationMatrix(m4);
```

Also, this not clear, why currenlty the expected matrix4 is transposed.

Same problem with `Euler().setFromRotationMatrix()`

**Comment by gkjohnson** [comment]
> Also, this not clear, why currently the expected matrix4 is transposed.

This is outlined in [Matrix3 docs](https://threejs.org/docs/#api/en/math/Matrix3) in the "A Note on Row-Major and Column-Major Ordering" section.

A Matrix4.setFromMatrix3 equivalent for [Matrix3.setFromMatrix4](https://threejs.org/docs/#api/en/math/Matrix3.setFromMatrix4) might reduce some of headache here, as well, if the `setFromRotationMatrix` functions cannot be changed to support Matrix3 as well as Matrix4.

**Comment by mrdoob** [comment]
Adding support for `Matrix3` in `THREE.Quaternion().setFromRotationMatrix()` sounds good to me 👍

**Comment by WestLangley** [comment]
>Adding support for Matrix3 in THREE.Quaternion().setFromRotationMatrix() sounds good to me 👍

I think that is a bit of a slippery slope, as these methods would also have to be supported -- and they only support _pure_ rotation matrices:
```js
quaternion.setFromRotationMatrix()
euler.setFromRotationMatrix()
vector4.setAxisAngleFromRotationMatrix()
```

As @gkjohnson suggested, I think a better, and more general, option is to simply add
```js
 matrix4.setFromMatrix3()
```

**Comment by Mugen87** [comment]
I'm using a custom `Matrix4.fromMatrix3()` as an extension in another project. Hence, I'm fine with adding it here 😊 .

**Comment by remmel** [comment]
Just a suggestion, an alternative could be to use in thoses places (`quaternion.setFromRotationMatrix()`, euler.setFromRotationMatrix(), ...) a `Matrix3` as expected type. But to still handle (deprecated) the `Matrix4` for a couple a versions. I don't know if this is more common when calling setFromRotationMatrix to have a `Matrix3` or `Matrix4` instance

**Comment by Mugen87** [comment]
> But what should be the signature of that method? Matrix4.setFromMatrix3(Matrix3 rotation, Vector3 position, float scale) ?

Just this: `Matrix4.setFromMatrix3(Matrix3 matrix)`.
