### ISSUE TITLE
Rollup.js: Can't generate the least change code.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#20944]
Maybe this question is very simple or I missed something about it.

**Describe the bug**

`npm run build` script can't generate the least change code.

**To Reproduce**

1. Fixed `rollup.config.js` to single quotes.
2. Run `npm run build` in terminals.

***Code***

```diff
diff --git a/utils/build/rollup.config.js b/utils/build/rollup.config.js
index 3d27cb76f8..df8a3ff8d3 100644
--- a/utils/build/rollup.config.js
+++ b/utils/build/rollup.config.js
@@ -1,5 +1,5 @@
-import babel from "@rollup/plugin-babel";
-import { terser } from "rollup-plugin-terser";
+import babel from '@rollup/plugin-babel';
+import { terser } from 'rollup-plugin-terser';
 
 if ( String.prototype.replaceAll === undefined ) {
 
@@ -260,7 +260,7 @@ function header() {
 
 		renderChunk( code ) {
 
-			return "// threejs.org/license\n" + code;
+			return '// threejs.org/license\n' + code;
 
 		}
 
@@ -276,7 +276,7 @@ function polyfills() {
 
 			if ( filePath.endsWith( 'src/Three.js' ) ) {
 
-				code = "import './polyfills';\n" + code;
+				code = 'import \'./polyfills\';\n' + code;
 
 			}
```

**Expected behavior**

I want to see the least change code after use single quotes.

**Screenshots**
<img width="1251" alt="three" src="https://user-images.githubusercontent.com/23699926/103099880-260fe700-464b-11eb-99c5-f1f89dbbea17.png">
<img width="1252" alt="three module" src="https://user-images.githubusercontent.com/23699926/103099891-2a3c0480-464b-11eb-8484-7a9153c03279.png">

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Three.js version: [r124]

**Comment by mrdoob** [comment]
Sorry, I don't understand what the question is... 🤔

**Comment by linbingquan** [comment]
> Sorry, I don't understand what the question is... 🤔

Sorry, I am not good at English, I am speak Chinglish...
TBH, I want to know how to publish release about `three.js` library, it can help me to know I am right or not, when I changed `rollup.config.js`.

**Comment by mrdoob** [comment]
Oh, you tried to use single quotes on rollup.config.js and now it doesn't build?

**Comment by linbingquan** [comment]
> Oh, you tried to use single quotes on rollup.config.js and now it doesn't build?

It worked, but I don't know what happened to it after I tried using single quotes with npm script `npm run build`.
With `npm run build` or `npm run dev` script, the code changes a lot.

Please tell me which script you use to publish release `three.js` library.

**Comment by mrdoob** [comment]
I just do `npm run build` and `npm publish` (on MacOS),

**Comment by linbingquan** [comment]
I run `npm run build` the code changes a lot... (on Window 10)

One part of `three.module.js`

```diff
diff --git a/build/three.module.js b/build/three.module.js
index c544dfe96b..2530a0b21e 100644
--- a/build/three.module.js
+++ b/build/three.module.js
@@ -11687,9 +11687,17 @@ function mergeUniforms( uniforms ) {
 
 const UniformsUtils = { clone: cloneUniforms, merge: mergeUniforms };
 
-var default_vertex = "void main() {\n\tgl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );\n}";
+var default_vertex = /* glsl */`
+void main() {
+	gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );
+}
+`;
 
-var default_fragment = "void main() {\n\tgl_FragColor = vec4( 1.0, 0.0, 0.0, 1.0 );\n}";
+var default_fragment = /* glsl */`
+void main() {
+	gl_FragColor = vec4( 1.0, 0.0, 0.0, 1.0 );
+}
+`;
 
 /**
  * parameters = {
```

**Comment by mrdoob** [comment]
We use GitHub issues to track confirmed bug reports and feature development.
If you need help, please use the [forum](https://discourse.threejs.org/), the [chat](https://discord.gg/HF4UdyF) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
