### ISSUE TITLE
Gltf object clone is not visible

### ISSUE THREAD

**Issue by PetrTT** [mrdoob/three.js#20945]
**Describe the bug**

Gltf object clone is not visible
Have a static mesh in gltf scene with BufferGeometry 

if  clone() method applyed to Mesh object and added to scene it is not visible

Trying to create clone of geometry and creating new THREE.Mesh with cloned geometry - result is the same

**Platform:**

 - Device: [Desktop]
 - OS: [Windows 7]
 - Browser: [ Firefox]
 - Three.js version: [dev, r124]

**Comment by donmccurdy** [comment]
For help, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). If you believe there is a bug with the three.js library, we would need an example or demo reproducing this to investigate.
