### ISSUE TITLE
Needs to remove flicker effects from object - three js

### ISSUE THREAD

**Issue by kaushikpitroda** [mrdoob/three.js#20955]
![image](https://user-images.githubusercontent.com/30293848/103238529-05100480-4971-11eb-968b-339e8cb00c6f.png)

Hello I am new beginner in three js.

I want to add normal map in my existing object.

I tried lot and normal map is also appear but it seems flickering the object.

I used following code for normal map.

```js
// NOTE: My three js version is 
// var THREE = { REVISION: '73' };

var shellCustomMap = loader.load( shell_media, function ( texture ) {
		texture.wrapS = texture.wrapT =	THREE.RepeatWrapping;
		texture.offset.set( 0,0 );
		texture.repeat.set( 2, 2 );
} );
				
var shellCustom = new THREE.MeshPhongMaterial({
            shininess: 100,
			specular:0x111111,
			normalMap: shellCustomMap
		});
		
		
var currentMat = shellMesh.material;
shellMesh = child;
shellMesh.material = currentMat;
var shellInside = shellMesh.clone(); // Cloning procedure.
shellInside.material = shellCustom;
mesh.add(shellInside);
```

Can you please help me out to remove flicking and getting normal map properly without any flickering effect.

My output would be like this.

![image](https://user-images.githubusercontent.com/30293848/103238958-3d641280-4972-11eb-88ed-d33b6b96b900.png)

**Comment by mrdoob** [comment]
We use GitHub issues to track confirmed bug reports and feature development.
If you need help, please use the [forum](https://discourse.threejs.org/), the [chat](https://discord.gg/HF4UdyF) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
