### ISSUE TITLE
broken link for Vector3

### ISSUE THREAD

**Issue by tusharjain0022** [mrdoob/three.js#20950]
**Describe the bug**

Link for Vector3 inside Vector3 info/help box in VsCode is taking me to the broken.
link : https://github.com/mrdoob/three.js/blob/master/src/math/Vector3.js%7Csrc/math/Vector3.js%7D

**To Reproduce**

1. Go to 'VsCode'
2. Use Vector3 in threejs
3. hover over Vector3 to see the help box
4. link provided to visit for more info on Vector3 is broken

***Code***

```js
let star = new THREE.Vector3(
          Math.random() * 600 - 300,
          Math.random() * 600 - 300,
          Math.random() * 600 - 300
        );
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hyok6tvj/)
* [jsfiddle-dev](https://jsfiddle.net/c5m1kazu/)

**Expected behavior**

 Link should not take to 404 error page.

**Screenshots**
![1609089910641](https://user-images.githubusercontent.com/59157988/103176342-c1f54a80-4825-11eb-9e2c-01626a623914.jpg)

![Screenshot (173)](https://user-images.githubusercontent.com/59157988/103176321-80649f80-4825-11eb-8af5-21c153a67b54.png)

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: r124

**Comment by marcofugaro** [comment]
This is the line the issue is referring to

https://github.com/mrdoob/three.js/blob/579d0e3e3b0b8a5167e04c3a8844770744d732c2/src/math/Vector3.d.ts#L23
