### ISSUE TITLE
Using webGlRenderer with big width and height or ratio crops the shader.

### ISSUE THREAD

**Issue by Sonic803** [mrdoob/three.js#20957]
Using webGlRenderer with big width and height or ratio crops the shader with chrome.

    <body>

    <div id="container"></div>
    <script src="libraries/three.min.js"></script>

    <script id="vertexShader" type="x-shader/x-vertex">
	varying vec2 vUv;

        void main() {
					vUv = uv;

            gl_Position = vec4( position, 1.0 );
        }
    </script>
    <script id="fragmentShader" type="x-shader/x-fragment">
				varying vec2 vUv;

        uniform vec2 u_resolution;
        uniform float u_time;

        void main() {
            vec2 st = gl_FragCoord.xy/u_resolution.xy;

            gl_FragColor=vec4(st.x,st.y,1.0,1.0);
        }
    </script>
    <script>
        var container;
        var camera, scene, renderer;
        var uniforms;
				let ratio=1;
				let a=7000;
        init();
        animate();

        function init() {
            container = document.getElementById( 'container' );

            camera = new THREE.Camera();
            camera.position.z = 1;

            scene = new THREE.Scene();

            var geometry = new THREE.PlaneBufferGeometry( 2, 2 );

            uniforms = {
                u_time: { type: "f", value: 1.0 },
                u_resolution: { type: "v2", value: new THREE.Vector2() },
                u_mouse: { type: "v2", value: new THREE.Vector2() }
            };

            var material = new THREE.ShaderMaterial( {
                uniforms: uniforms,
                vertexShader: document.getElementById( 'vertexShader' ).textContent,
                fragmentShader: document.getElementById( 'fragmentShader' ).textContent
            } );

            var mesh = new THREE.Mesh( geometry, material );
            scene.add( mesh );

            renderer = new THREE.WebGLRenderer();
            renderer.setPixelRatio( ratio );

            container.appendChild( renderer.domElement );

            onWindowResize();
            window.addEventListener( 'resize', onWindowResize, false );

            document.onmousemove = function(e){
              uniforms.u_mouse.value.x = e.pageX
              uniforms.u_mouse.value.y = e.pageY
            }
        }

        function onWindowResize( event ) {
            renderer.setSize( a,a);
            uniforms.u_resolution.value.x =a*ratio;
            uniforms.u_resolution.value.y = a*ratio;
        }

        function animate() {
            requestAnimationFrame( animate );
            render();
        }

        function render() {
            uniforms.u_time.value += 0.05;
            renderer.render( scene, camera );
        }
    </script>
</body>

I expect the top right corner to be white like in firefox.

**Screenshots**

![image](https://user-images.githubusercontent.com/58883857/103241737-6b3a5e80-4954-11eb-9079-a65e9b7599c7.png)
![image](https://user-images.githubusercontent.com/58883857/103242664-5f03d080-4957-11eb-863c-10be2e4e8a4a.png)

First image in chrome, second in firefox
**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: r124

**Comment by gkjohnson** [comment]
It's possible this is a browser issue? It seems that that `gl_FragCoord` is not reporting above `~5750` or so in Chrome. Here is a js fiddle with a basic repro using the above code:

https://jsfiddle.net/fm0ej76k/1/

The shader has been modified to color any pixels `gl_FragColor.x > 5700` red and you can see after scrolling to the right that only a small amount of the canvas is colored as opposed to the `1300` pixel columns expected even though the viewport is definitely set to 7000 x 7000. The result looks as expected in FireFox. You can check the viewport directly from the WebGL API like so:

```js
const gl =renderer.getContext();
gl.getParameter( gl.VIEWPORT ); // [ 0, 0, 7000, 7000 ]
```;

**Comment by Mugen87** [comment]
This is not a `three.js` issue. Chrome can not handle arbitrary large resolutions. The browser has a limit of 5760 x 5760 total backbuffer area.

https://bugs.chromium.org/p/chromium/issues/detail?id=756347#c12
