### ISSUE TITLE
Potential Photosensitive epilepsy at demo pages

### ISSUE THREAD

**Issue by FrodoLuo** [mrdoob/three.js#20968]
**Describe the bug**

This [demo page](https://threejs.org/examples/webgl_postprocessing_glitch) contains extremely strong blinks and flashes, which may cause a potential Photosensitive epilepsy. Better to add a warning at the entry of this demo.

**To Reproduce**

1. Go to 'https://threejs.org/examples/webgl_postprocessing_glitch'

***Code***

none

***Live example***

none

**Expected behavior**

Add a warning at the entry of this demo page.

**Screenshots**

none

**Platform:**

none

**Comment by mrdoob** [comment]
Reducing the speed of the effect could work too. Would you like to do a Pull Request?

**Comment by FrodoLuo** [comment]
> Reducing the speed of the effect could work too. Would you like to do a Pull Request?

I'm still studying how to use three.js, but I can add some waring text to the documents...

**Comment by Mugen87** [comment]
Alternatively, we could also add the same screen like in the [audio demos](https://threejs.org/examples/webaudio_timing) and add a respective warning there. Something like:

> Exposure to the following post-processing effect may trigger epileptic seizures or blackouts.
