### ISSUE TITLE
cubeTexture set dataTexture

### ISSUE THREAD

**Issue by 11zouzouzou** [mrdoob/three.js#20960]
borwer: iphone safari ,THREE.js_version:r124.

When I set the dataTexture to Cubetexture the system will warn me and not work. My source MIpMap data is RGB,
warning:
![屏幕快照 2020-11-10 上午11 20 00](https://user-images.githubusercontent.com/40816121/103278383-50c0bd80-4a06-11eb-8c9e-fc2fdc77b99f.png)
loadingCode:
![屏幕快照 2020-12-29 下午6 49 58](https://user-images.githubusercontent.com/40816121/103278549-b4e38180-4a06-11eb-8dc5-d853ddd34bab.png)

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by 11zouzouzou** [comment]
i found it.The modification code has been committed.I hope to adopt
