### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by SongBana** [mrdoob/three.js#20962]
**Image links are not supported, but will work in the HTML image tag. I switch a link and it doesn't sound wrong**

eorror Info : ccess to image at 'https://uimgproxy.suning.cn/uimg1/sop/commodity/YNCzdQuIZ5BQTiZ6FstvsQ.png' from origin 'http://localhost:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

`url:https://uimgproxy.suning.cn/uimg1/sop/commodity/YNCzdQuIZ5BQTiZ6FstvsQ.png`

```
const textureLoader = new TextureLoader();
	var sphereGeo = new SphereBufferGeometry(100, 32, 32);
	var sphereMaterial = new MeshBasicMaterial({
		map: textureLoader.load(imagePath),
		side: DoubleSide,
		transparent: false,
		opacity: 1,
		depthWrite: false
	});

	var mainMesh = new Mesh(sphereGeo, sphereMaterial);
```

**Comment by CodyJasonBennett** [comment]
This is a CORS issue, not a THREE issue.

Anyways, this has to do with your server configuration.
See https://discourse.threejs.org/t/no-access-control-allow-origin-header-is-present-on-the-requested-resource/14589

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by dozortsev** [comment]
Hey @CodyJasonBennett @Mugen87 @mrdoob

can we allow disable cors in [underlying fetch](url)?

```diff
const req = new Request( url, {
	headers: new Headers( this.requestHeader ),
	credentials: this.withCredentials ? 'include' : 'same-origin',
+      mode: this.requestMode,
} );

// start the fetch
fetch( req )
```

so consumers could control cors mode on their end, e.g

```js
const lights = useLoader(ObjectLoader, 'https://url/to/my/asset/image.png', (loader: ObjectLoader) => {
  loader.setRequestMode('no-cors');
});
```

**Comment by mrdoob** [comment]
Feel free to do a PR so others can have a look.
