### ISSUE TITLE
rotateOnWorldAxis does not rotate

### ISSUE THREAD

**Issue by ognjen-petrovic** [mrdoob/three.js#20972]
**Describe the bug**

rotateOnWorldAxis does not rotate around world axis, it rotates locally.

**To Reproduce**

Go to example..blue sphere does not rotate around the yellow one.

***Live example***

[codepen example](https://codepen.io/ognjen-petrovic/pen/gOwvPVQ)

**Expected behavior**

Expected to see the blue sphere rotating around world's y axis

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome, Firefox
 - Three.js version: r.124

**Comment by WestLangley** [comment]
You appear to be using the wrong method.

Instead use the method `rotateAroundWorldAxis( point, axis, angle )`, which you can find in [this SO answer](https://stackoverflow.com/questions/31953608/rotate-object-on-specific-axis-anywhere-in-three-js-including-outside-of-mesh/32038265#32038265).

```js
bluePlanet.rotateAroundWorldAxis( sun.position, yAxis, 0.005 );
```

Also, avoid instantiating a new `THREE.Quaternion()` inside the render loop. Create one and reuse it.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.

**Comment by ognjen-petrovic** [comment]
Just to be sure that I do not miss method...I cannot find "rotateAroundWorldAxis"

**Comment by WestLangley** [comment]
Yes. Paste the code in the above SO link into your app.

**Comment by mrdoob** [comment]
@WestLangley Should I add that method to the library?

**Comment by WestLangley** [comment]
@mrdoob I think that would be reasonable.

To improve clarity of the docs, something like the following is the best I can think of so far. The words are carefully-chosen...

	rotateOnAxis()

	Rotate the object on an axis in object space. The axis is assumed to be normalized.


	rotateOnWorldAxis()

	Rotate the object on an axis in world space. The axis is assumed to be normalized.

	This method does not support objects having rotated parent(s).


	rotateAroundWorldAxis()

	Rotate the object around an axis in world space. (The axis passes through point.) The axis is assumed to be normalized.

	This method does not support objects having rotated parent(s).
