### ISSUE TITLE
Object3D.worldToLocal() returning incorrect vectors

### ISSUE THREAD

**Issue by eulertour** [mrdoob/three.js#20992]
**Describe the bug**

`Object3D.worldToLocal()` sometimes returns [NaN, NaN, NaN]

**To Reproduce**

Call `Object3D.worldToLocal()`

***Code***

```js
function animate(t) {
  requestAnimationFrame( animate );
  
  let start = new THREE.Vector3(0,-10,0);
  let end = new THREE.Vector3(5,-10,0);
  let offset = new THREE.Vector3(0,0,0);
  start.lerp(end, t / 1000).add(offset);


  if (t < 1000) {
  	// Restuls in start = [NaN, NaN, NaN]
    circle.worldToLocal(start);
    console.log(start);
    
    let matrixWorldCopy = new THREE.Matrix4().copy(circle.matrixWorld);
    // These are different in the console.
    console.log(matrixWorldCopy);
    console.log(circle.matrixWorld);
  }
	circle.position.copy(start);

  renderer.render( scene, camera );
  stats.update();

}
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/e25g4ayw/)
* [jsfiddle-dev](https://jsfiddle.net/bcha0fr7/1/)

**Expected behavior**

The input vector should be converted to the local coordinates of the Object3D.

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome
 - Three.js version: dev and latest release

**Comment by Mugen87** [comment]
When you initially call `animate()`, you pass in no `t` argument. Meaning `t` is `undefined` which produces a `start` vector consisting of `NaN` values.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.

**Comment by eulertour** [comment]
It's good the fix is simple because the problem I meant to solve was the jittering that occurs when the function is called properly, which you can see on either demo if you replace the first call to animate with requestAnimationFrame(animate). Should I open a new issue for that?

**Comment by Mugen87** [comment]
Please no. This is an issue in your app. GitHub is for bugs and feature requests only. Please use the forum.

**Comment by mrdoob** [comment]
Another reason for promoting `renderer.setAnimationLoop()` 🤓

**Comment by eulertour** [comment]
The example from the documentation uses requestAnimationFrame if you decide to change it there https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene
