### ISSUE TITLE
WebXRManager: Provide API for getting VR Camera transform, joined Frustum

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#21002]
**Is your feature request related to a problem? Please describe.**

I just started on some WebXR development and I was surprised to find that you cannot currently get the VR camera transformation and joined frustum used for culling at all. 

This information can be used generally for VR UI where you float UI elements into place with the frustum being useful for placement. My use case was for implementing a VR example in the [3dTilesRendererJS](https://github.com/NASA-AMMOS/3DTilesRendererJS/) project which requires the transform and frustum of the camera to compute custom frustum culling and error calculations to determine tile visibility.

**Describe the solution you'd like**

I would like the option to update the VR camera explicitly and get the VR Camera instance so I can update the VR Camera, update my scene based on the head position, then render. To retain the current behavior an `autoUpdate` flag could be added to `WebXRManager`:

```js
renderer.xr.autoUpdate = false;
renderer.xr.updateVRCamera( camera );

const vrCamera = renderer.xr.getVRCameraInstance();

// update stuff using the transform, frustum

renderer.render( scene, camera );
```

**Describe alternatives you've considered**

My workaround right now is to call `renderer.xr.getCamera( camera )` to get the VR Camera before rendering but as far as I can tell that's not intended to be public and it's redundant because the renderer calls it, too:

```js
let currentCamera = camera;
if ( renderer.xr.isPresenting ) {

    // this camera has the correct transform and frustum information
    currentCamera = renderer.xr.getCamera( camera );

}
```

_EDIT: This is also a problem with controllers, which seem to be updated in the xr animation loop. Meaning we can't get the latest controller poses to update objects in the scene before render resulting in a single frame delay._

**Comment by felixmariotto** [comment]
I'm encountering the same problem in my attempt to make an ImmersiveControls class, the more straightforward way of getting the camera transform in XR mode is
```javascript
renderer.xr.getCamera( camera );
```

Another method is to get the transform like this : 
```javascript
renderer.setAnimationLoop( (time, frame) => {

	const referenceSpace = renderer.xr.getReferenceSpace();
	
	const viewerPose = frame.getViewerPose( referenceSpace );

	viewerPose.transform.position
	viewerPose.transform.orientation
	viewerPose.transform.matrix

});
```
This is clumsy though and feels even more like a hack, plus you don't get an Object3D with its nice API.
