### ISSUE TITLE
TypeError: Window.createImageBitmap: 2 is not a valid argument count for any overload.

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#21003]
Sometimes I get this error.

1. Load a gltf model with r124, Idk
2. Look into browser console
3. See error

***Code***

```js
let manager = new THREE.LoadingManager, loader = new GLTFLoader( manager );
...
loader.load( config.path, function( result ) {
// nothing special here
```

***Live example***

n/a

**Expected behavior**

The error never happens

**Screenshots**

![gltfloader stack](https://user-images.githubusercontent.com/242577/103602373-2ee69f80-4f0c-11eb-9a4d-21621c0812f6.png)

![gltfloader code](https://user-images.githubusercontent.com/242577/103602413-40c84280-4f0c-11eb-8b11-447fb2c40caa.png)

**Platform:**

 - Device: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Three.js version: r124

**Comment by makc** [comment]
> Sometimes 

Ok, I was able to narrow it down - it happens when FF is in iOS simulation mode:
![ff](https://user-images.githubusercontent.com/242577/103605482-432e9a80-4f14-11eb-9c04-f4ba4e2a757f.png)

**Comment by makc** [comment]
so there is [createImageBitmap fails when providing options object](https://bugzilla.mozilla.org/show_bug.cgi?id=1335594) closed as a duplicate of [Wrong results with UNPACK_FLIP_Y_WEBGL and createImageBitmap imageOrientation](https://bugzilla.mozilla.org/show_bug.cgi?id=1367251) 
> Looks the patches in bug 1367251 is adding the options, so close as duplicate.

which is still open after 4 years. not sure if you want to do anything about it.

**Comment by Mugen87** [comment]
`GLTFLoader` does not use `ImageBitmapLoader` with Firefox, see:

https://github.com/mrdoob/three.js/blob/210c33f35766fad3d20e4b7c55925024a67e0ed1/examples/js/loaders/GLTFLoader.js#L1846-L1856

**Comment by makc** [comment]
a ha @Mugen87 that makes sense now. since FF fakes user agent and pretends to be an iPhone, this fails

**Comment by Mugen87** [comment]
Closing then.

**Comment by aardgoose** [comment]
FWIW, I have submitted patches to FF to add options support for createImageBitmap. Pending review on latest revision at the moment.

**Comment by mrdoob** [comment]
@aardgoose 🙏🙏🙏

**Comment by joshua3D** [comment]
I was using the latest version of GLTFLoader and, inexplicably, a three.js app that was working fine previously on firefox 87.0 hit a snag with this error. I had to force the loader to use THREE.TextureLoader to get everything working again.

**Comment by Zorrow1212** [comment]
Eve _[![image](https://user-images.githubusercontent.com/59420910/114259087-6d6f7880-9999-11eb-9f94-7a7c6a0946c8.jpeg)](http://github.com/)_****

**Comment by Zorrow1212** [comment]
> Eve _[![image](https://user-images.githubusercontent.com/59420910/114259087-6d6f7880-9999-11eb-9f94-7a7c6a0946c8.jpeg)](http://github.com/)_****
![image](https://user-images.githubusercontent.com/59420910/114259096-7eb88500-9999-11eb-8dee-90481789ff35.jpeg)

**Comment by mrdoob** [comment]
@joshua3D can you create a jsfiddle that reproduces the issue?

**Comment by aardgoose** [comment]
The createImageBitmap patches have now landed in Firefox nightly and the flipY and premulitplyAlpha options are supported.
The resize and colorSpaceConversion options aren't supported yet.

The gl.pixelStorei gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL and gl.UNPACK_FLIP_Y_WEBGL parameters are ignored as per latest spec.

**Comment by mrdoob** [comment]
Nice!

**Comment by mrdoob** [comment]
When do you think we'll be able to remove this code?

https://github.com/mrdoob/three.js/blob/f0583761c530e7ee16360530182655ff5672dacc/examples/jsm/loaders/GLTFLoader.js#L2190-L2200

**Comment by aardgoose** [comment]
It's targeted for Firefox 93 due in early October unless it hits problems.
