### ISSUE TITLE
funky primitives in Safari

### ISSUE THREAD

**Issue by Fabrice3D** [mrdoob/three.js#21029]
**Describe the bug**
Some problem in Safari... Here your own examples page
![Screenshot 2021-01-08 at 15 42 31](https://user-images.githubusercontent.com/550453/104028589-31295200-51c9-11eb-89b3-9862873f0de7.jpg)

**To Reproduce**
 make a sphere geom and view in Safari

***Code***
 

***Live example***
 
**Expected behavior**

See a sphere as in other browsers

**Screenshots**

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser:Safari
 - Three.js version: latest

**Comment by mrdoob** [comment]
Do you have WebGL2 enabled?

**Comment by mrdoob** [comment]
Actually, better report the issue to Apple instead.

**Comment by Fabrice3D** [comment]
Yeah sure, they listen so well :D
