### ISSUE TITLE
Working on SkeletonAnimation - JSONFormat

### ISSUE THREAD

**Issue by codeart1st** [mrdoob/three.js#2106]
Hey guys, I'm working on SkeletonAnimation, but I don't understand how the bones will stored in JSONFormat.

```javascript
{
  parent: BXindex,  // -1 for root bone
  pos: [x,y,z],
  rotq: [x,y,z,w], // quaternion
  scl: [x,y,z]
}
```

To understand it, I started to present the bones as THREE.Lines.

http://www.fiesta-library.bplaced.net/test/webgl_animation_skinning.html

But something is wrong with that.

In the JSONFormat is only one position for each bone. In Blender bones have two positions - tail and head. So how works the Three.js Bones?

**Comment by yazancash** [comment]
i want to understand how "rotq" array of bones working?

`rotq: [x,y,z,w], // quaternion`

[x, y, z] are angles in Radian? (based on my tests, i guess not)

and what is [w] ? I find it is '1' in most examples.

**Comment by empaempa** [comment]
Hey! Quaternions is whole different beast than Euler angles but SO much better in every mathematical way. Pick any result from this [search](https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=quaternion+explained) to get up to speed.

**Comment by yazancash** [comment]
i got it, thank you!
http://answers.unity3d.com/questions/645903/please-explain-quaternions.html

**Comment by yazancash** [comment]
in JSON format, is there anyway to store transform/quaternion data in 4x4 matrix ?
example
```
"bones":[
	{
	"parent":0,
	"name":"mixamorig_Hips",
	"matrix4x4":[1.000000, -0.000142, -0.000005, 0.000000, 0.000142, 1.000000, -0.000002, 0.000000, 0.000005, 0.000002, 1.000000, 0.000000,0.000057, 6.098754, 0.036233, 1.000000]
	}
```
is this possible somehow?
