### ISSUE TITLE
GLTF type implementation 

### ISSUE THREAD

**Issue by joshuaellis** [mrdoob/three.js#21070]
**Describe the bug**

GLTF type is missing materials & nodes which seems to be returned from a lot of GLTF models. Is this a bug where they should be put into `userData` or are they missing from the type?

***Code***

Current type: 
```ts
export interface GLTF {
	animations: AnimationClip[];
	scene: Group;
	scenes: Group[];
	cameras: Camera[];
	asset: {
		copyright?: string;
		generator?: string;
		version?: string;
		minVersion?: string;
		extensions?: any;
		extras?: any;
	};
	parser: GLTFParser;
	userData: any;
}
```

Rough, proposed type:
```ts
export interface GLTF {
	animations: AnimationClip[];
	scene: Group;
	scenes: Group[];
	cameras: Camera[];
	asset: {
		copyright?: string;
		generator?: string;
		version?: string;
		minVersion?: string;
		extensions?: any;
		extras?: any;
	};
	parser: GLTFParser;
	userData: any;
	materials: {
		[key: string]: Material;
	};
	nodes: {
		[key: string]: Object3D;
	};
}
```

**Expected behavior**

Should either be able to use `materials` and/or `nodes` or they should be moved to `userData` on parsing.

I was going to make a PR for this but I wasn't sure whether that suggested implimenation would correctly cover materials.

**Comment by donmccurdy** [comment]
The result object is constructed here:

https://github.com/mrdoob/three.js/blob/4457273fe29f5b4b56dee33270986ee94947c0f2/examples/js/loaders/GLTFLoader.js#L1907-L1915

I don't think `materials` and `nodes` are returned, are you seeing them somewhere else?

**Comment by joshuaellis** [comment]
Sorry, my mistake they're added in a function in `react-three-fiber` to models. Thank you though.
