### ISSUE TITLE
WebXR always asks for hands support

### ISSUE THREAD

**Issue by cabanier** [mrdoob/three.js#21084]
When entering an immersive session, the framework always asks for hand tracking. See [here](https://github.com/mrdoob/three.js/blob/66b9fa344ce01581033d171e1de09dd86bd5a3d7/examples/jsm/webxr/VRButton.js#L71).

This should only be done if the experience will make use of this feature because it might slow down JavaScript execution.

**Comment by mrdoob** [comment]
Can you share any numbers of how much the slow down might be?

**Comment by cabanier** [comment]
I don't have exact numbers. 
I was told that it has *some* impact on performance and battery life.

**Comment by mrdoob** [comment]
Okay, closing until there are numbers.
