### ISSUE TITLE
character . in _RESERVED_CHARS_RE constant

### ISSUE THREAD

**Issue by Botchal** [mrdoob/three.js#21097]
Hi all!
Any one tell me, what is a track binding syntax?
src/three/build/three.js:32341 _RESERVED_CHARS_RE
`// Characters [].:/ are reserved for track binding syntax.
const _RESERVED_CHARS_RE = '\\[\\]\\.:\\/';
const _reservedRe = new RegExp( '[' + _RESERVED_CHARS_RE + ']', 'g' );`

The Blender default naming containts a dot charactes for uniqueize node names
http://joxi.ru/J2bnxl7CVB1aG2

but after import from some loaders i have a cleared node names http://joxi.ru/vAW5WZ0uOaz4Lm 
that do not contain a dot characters

What is it for?

thx!

**Comment by Mugen87** [comment]
Certain characters like the dot are reserved for the internal track binding syntax. Meaning a syntax which is used to target specific nodes and properties from a keyframe track. This makes it possible to define "what" in the scene should be animated.
