### ISSUE TITLE
Examples: remove addEventListener third parameter

### ISSUE THREAD

**Issue by marcofugaro** [mrdoob/three.js#21100]
**Is your feature request related to a problem? Please describe.**

In examples, you may find event listeners like this:

```js
window.addEventListener( 'resize', onWindowResize, false );
```

The third parameter, the `useCapture` parameter, is already false by default.
**This confuses newcomers**, also combined with the fact that event capturing is a not so easy concept to grasp.

This pattern comes from around 2012, when you needed to define the third parameter explicitly.

![image](https://user-images.githubusercontent.com/7217420/104843141-5a349b80-58c9-11eb-805c-b9bfbb4b8cba.png)

Nowadays browsers, already default the parameter to `false`, so it can safely be omitted.

<img src="https://user-images.githubusercontent.com/7217420/104842913-2f961300-58c8-11eb-985b-7ac74c589c91.png" width="450" />

Reference: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Describe the solution you'd like**

Instead set:

```js
window.addEventListener( 'resize', onWindowResize );
```

I can contribute with some PRs if we decide to go forward with this change.

**Comment by mrdoob** [comment]
> I can contribute with some PRs if we decide to go forward with this change.

Sounds good to me 👍

**Comment by Mugen87** [comment]
> This confuses newcomers, also combined with the fact that event capturing is a not so easy concept to grasp.

Indeed. It's better to not confront the user with this topic by just removing the arguments.
