### ISSUE TITLE
index.html:42 Uncaught ReferenceError: OBJLoader is not defined

### ISSUE THREAD

**Issue by rruvira9191** [mrdoob/three.js#21119]
i have this simple code and when I try to run I get the error of the subject OBJLoader is not defined

<!DOCTYPE html>
<html>
<head>
  <style>
	  
    body { margin: 0; }
canvas { width: 100%; height: 100% }
	

  </style>
</head>

<body><h1>Model custom element: Aircraft 3D</h1>

    

    
    <script type="module" src="./js/three.min.js"></script>
    <script  src="js/three.js"></script>
    <script type="module" src="js/OBJLoader.js"></script>
      

<script>

  
</script>

  <script>
var scene = new THREE.Scene();
var camera = new THREE.PerspectiveCamera( 75, window.innerWidth/window.innerHeight, 0.1, 1000 );
 
var renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );
document.body.appendChild( renderer.domElement );

const loader = new OBJLoader();

// load a resource
loader.load(
	// resource URL
	'Skull.obj',
	// called when resource is loaded
	function ( object ) {

		scene.add( object );

	},
	// called when loading is in progresses
	function ( xhr ) {

		console.log( ( xhr.loaded / xhr.total * 100 ) + '% loaded' );

	},
	// called when loading has errors
	function ( error ) {

		console.log( 'An error happened' );

	}
);

  </script>

</body>
</html>

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
