### ISSUE TITLE
GLTFLoader: Add an example for `EXT_meshopt_compression`

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#21111]
Since https://github.com/mrdoob/three.js/pull/20508 by @zeux, we've had support for using the `EXT_meshopt_compression` extension in GLTFLoader. We don't yet have any examples of how to use that, and I think it would be helpful to show ([context thread on twitter](https://twitter.com/0xca0a/status/1351460547431198722?s=20)).

**Comment by zeux** [comment]
I can contribute an example, I had a tweaked version of the original GLTF loader example when I was testing the PR.

**Comment by donmccurdy** [comment]
That'd be great, thank you! I think my suggestion would be to make a separate standalone example rather than rolling it into `loader / gltf / extensions`. That example is probably already doing too much.

Perhaps name it `loader / gltf / compression` for now, and we can extend it later to also include `.ktx2` Basis compressed textures.

**Comment by wallabyway** [comment]
That fixed it - thanks !
Loads very quickly.
https://github.com/wallabyway/quicklook-example

**Comment by wallabyway** [comment]
Here's an example of MeshOpt working with the USDz exporter for Quicklook:
https://github.com/wallabyway/quicklook-example

The coffeeCart example looks good with it's metallic reflections, which work well with QuickLook's real-time IBL approximation.
I used glTFPack which merged and compressed the meshes, bringing down the draw calls to just 2.  So the performance under quicklook is very smooth.
