### ISSUE TITLE
Normal is not correct when switching Variant in webgl_loader_gltf_variants

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#21136]
**Describe the bug**

I tried the sample [KHR_materials_variants](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_variants/README.md) extension of `glTF`.
However, when I switch the Variant from `midnight` to `beach`, Normal does not seem to be correct.

**To Reproduce**

1. Go to https://threejs.org/examples/?q=variant#webgl_loader_gltf_variants
2. Switch the Variant from `midnight` to `beach`
3. Look at the logo on the side of the shoe.

**Expected behavior**

Since this model refers to the same `normal.jpg`, the expected behavior is that the unevenness will not change.

**Screenshots**

|Variant|image|
|:-----:|:------:|
|midnight|![image](https://user-images.githubusercontent.com/1833979/105639207-3e795880-5eba-11eb-8c94-dd847f5b6ead.png)|
|beach|![image](https://user-images.githubusercontent.com/1833979/105639211-49cc8400-5eba-11eb-8285-d10493e83b94.png)|

**Platform:**

 - Device: MacBook Air
 - OS: Windows 10 (BootCamp)
 - Browser: Chrome 87.0.4280.141
 - Three.js version: r124

**Comment by Mugen87** [comment]
For some reasons, the `normalScale` value of `midnight` is `1, -1` whereas the other two materials have a value of `1, 1`.

**Comment by mrdoob** [comment]
is this an issue on the khronos model?

/cc @donmccurdy

**Comment by cx20** [comment]
The original models used here can be found in Khronos [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models) repository.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MaterialsVariantsShoe

If I remember correctly, I reduced the texture size to save space. but I think the rest of the model structure is the same.

For reference, the normal problem does not seem to occur when displaying this model in Babylon.js.
[Babylon.js + MaterialsVariantsShoe.gltf result:](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=MaterialsVariantsShoe&scale=10&type=glTF)
|Variant |image|
|:--:|:--:|
|midnight| ![image](https://user-images.githubusercontent.com/1833979/105703739-06712480-5f51-11eb-80e6-e5f89ac8efab.png)|
|beach|![image](https://user-images.githubusercontent.com/1833979/105703759-0ec95f80-5f51-11eb-8f2c-3e7654bc5aed.png)|

**Comment by donmccurdy** [comment]
As @Mugen87 points out, the `assignFinalMaterial` would normally do some adjustments to materials based on the mesh they're attached to, as we need to know whether the geometry has tangents or not. See https://github.com/mrdoob/three.js/issues/11438#issuecomment-501942328. Variants are applied well after the model was loaded, outside of GLTFLoader, and the example wouldn't know about these details.

Ideally this model would contain vertex tangents... Blender can generate them, but won't read/write the variants, so unfortunately that's difficult to add at the moment. With vertex tangents this would not be an issue.

Perhaps https://github.com/mrdoob/three.js/pull/20789 would also help fix this, but I'm still worried about several parts of that.

**Comment by elalish** [comment]
Looks like it might have been a simple oversight. `assignFinalMaterial` should probably be called right after `getDependency` when loading a new variant. It seems `assignFinalMaterial` isn't included in GLTFLoader.d.ts, but I guess it should be?

**Comment by donmccurdy** [comment]
That could work I think — might try to think of a more descriptive name before we consider it a public API, but sounds like a good solution.

**Comment by elalish** [comment]
Well, I gave it a try and no such luck. `assignFinalMaterial` negates `normalScale.y` every time, so it ends up switching back and forth as you swap back to already-loaded variants. I think that line needs to move inside the cached ClonedMaterial block. I'll work up a PR.
