### ISSUE TITLE
Anaglyph Shader Matrix Values

### ISSUE THREAD

**Issue by jdeboi** [mrdoob/three.js#21135]
**Is your feature request related to a problem? Please describe.**
I noticed that the anaglyph effect really didn't look good with my red cyan glasses-lots of ghosting that doesn't appear when using an anaglyph Processing library based on the Dubois red/cyan algorithms. I did some digging, and (I think, but totally correct me if I'm wrong) the current three.js anaglyph shader uses right/left matrices that prioritize color purity over 3D. 

I'm pretty sure the [angler matrices this.colorLeft and this.colorRight](https://github.com/tschw/angler.js/blob/gh-pages/app/classes/AnaglyphShadertoyPlayer.js) (at least in the linked shader) are Dubois. I replaced the three.js matrices in the AnaglyphShader with these angler values (below), which helped with the ghosting of my models.

```
this.colorMatrixLeft = new Matrix3().fromArray( [
     0.456100, -0.0400822, -0.0152161,
     0.500484, -0.0378246, -0.0205971,
     0.176381, -0.0157589, -0.00546856
] );

this.colorMatrixRight = new Matrix3().fromArray( [
     -0.0434706, 0.378476, -0.0721527,
     -0.0879388, 0.73364, -0.112961,
     -0.00155529, -0.0184503, 1.2264
] );
```

**Describe the solution you'd like**
I think a simple comment [in the AnaglyphEffect.js](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/effects/AnaglyphEffect.js ) mentioning what type of anaglyph matrix / algorithm is being used (e.g. red/cyan or red/amber? Dubois or something else?). A more complete and complex solution might be an extra parameter to the anaglyph effect to set the type of matrices used in the shader based upon glasses color or desired effect.

**Describe alternatives you've considered**
As mentioned, I was able to copy the Dubois angler matrix values [here](https://github.com/tschw/angler.js/blob/gh-pages/app/classes/AnaglyphShadertoyPlayer.js), so maybe this isn't a feature request as much as a documentation request. 
  
I've been trying to find a good resource w/ the computed matrix values. This is the best I've been able to find so far:
[Processing lib](https://github.com/hx2A/Camera3D/blob/master/src/camera3D/generators/AnaglyphGenerator.java) and [optimized anaglyph](http://stereo.jpn.org/eng/stphmkr/help/stereo_13.htm).

Anyway, thanks!

**Comment by Mugen87** [comment]
> I think a simple comment in the AnaglyphEffect.js mentioning what type of anaglyph matrix / algorithm is being used (e.g. red/cyan or red/amber? Dubois or something else?).

Improving the inline documentation is a good start.

@tschw Do you mind clarifying the differences between the matrices used in [AnaglyphEffect.js](https://github.com/mrdoob/three.js/blob/f4f930cd724d8aaae61fb5304cd917b75007b325/examples/jsm/effects/AnaglyphEffect.js#L20-L36) and the matrices from [angler.js](https://github.com/tschw/angler.js/blob/43d9c408d0e61727165388e8eed7c947ca7971d8/app/classes/AnaglyphShadertoyPlayer.js#L4-L15)?

**Comment by makc** [comment]
@Mugen87 the angler matrix seems to be coming from [this paper](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.7.6968&rep=rep1&type=pdf#page=4) where they took Dubois method and applied it to LCD spectral  distribution instead of CRT

**Comment by Mugen87** [comment]
Good to know. But the theoretical background of the matrices used in `AnaglyphEffect.js` are still not clear, right?

**Comment by makc** [comment]
Those seem to be the values dumped to the console by [tschw script](http://tschw.github.io/angler.js/app/frames/main.html) under default settings:
![Screen Shot 2021-02-17 at 4 58 18 ](https://user-images.githubusercontent.com/242577/108154236-d85cab80-70dc-11eb-9f68-4c897ee366ac.png)

tschw comment about them is [here](https://github.com/mrdoob/three.js/pull/8456/files#r57347716) (but does not really explain much :~)

**Comment by Mugen87** [comment]
What do you think about replacing the matrices with the one from the paper? This is essentially what the OP did in his first post.

The example will look different with the new matrices but at least we have a clear resource we can link to.
