### ISSUE TITLE
Typescript support about material.map

### ISSUE THREAD

**Issue by xuekai-china** [mrdoob/three.js#21133]
**Is your feature request related to a problem? Please describe.**

Typescript support error'.

**Describe the solution you'd like**

When I want to destroy a Mesh, VSCode prompts me that the property "map" does not exist on the type "material".

**Describe alternatives you've considered**

I've seen it. There's no "map"  in 'Material.d.ts'.

**Additional context**

![1611418866967](https://user-images.githubusercontent.com/49433924/105608059-b1ac9d00-5ddc-11eb-89b0-6ebaf0fe8977.jpg)

**Comment by Mugen87** [comment]
> There's no "map" in 'Material.d.ts'.

And this is also correct since not every material has a `map` property. I suspect you have to cast the material to a more concrete type. And then access `map`.

**Comment by xuekai-china** [comment]
> > There's no "map" in 'Material.d.ts'.
> 
> And this is also correct since not every material has a `map` property. I suspect you have to cast the material to a more concrete type. And then access `map`.

Yes, as you said. 
If 'map' is not necessary, it can be expressed as
```ts
class Material {
   // for Texture and undefined
   map?: Texture;
   // or
   // for Texture and null
   map: Texture | null;
}
```
Last, `Material.color` is the same problem.

**Comment by xuekai-china** [comment]
> ```ts
> class Material {
>    // for Texture and undefined
>    map?: Texture;
>    // or
>    // for Texture and null
>    map: Texture | null;
> }
> ```

This mode is more friendly to TS development, Developer can do this:

```ts
// for Texture and undefined
Material.map && Material.map.dispose()

// for Texture and null
Material.map?.dispose()
```
You can choose which mode to use！

**Comment by xuekai-china** [comment]
Also 'emissive'、'emissiveIntensity'、'emissiveMap' 、'specularMap'...

**Comment by donmccurdy** [comment]
Material is a base class, and is not intended to list nullable properties for all of its many subclasses. You will need to cast the material to the correct type to get TypeScript to understand the available properties. For example:

```ts
const material = mesh.material as MeshStandardMaterial;
material.map = texture;
```

**Comment by xuekai-china** [comment]
> Material is a base class, and is not intended to list nullable properties for all of its many subclasses. You will need to cast the material to the correct type to get TypeScript to understand the available properties. For example:
> 
> ```ts
> const material = mesh.material as MeshStandardMaterial;
> material.map = texture;
> ```

I know. I wrote it wrong. thank you！
