### ISSUE TITLE
Unable to run `node utils/modularize.js` at HEAD.

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#21138]
On the dev branch, after a clean install of dependencies, I'm getting an error when trying to update the jsm files:

```
▸ node utils/modularize.js

/Users/donmccurdy/Projects/three.js/build/three.js:36867
	if (window) {
	^

ReferenceError: window is not defined
    at /Users/donmccurdy/Projects/three.js/build/three.js:36867:2
```

Anyone else seeing this issue, or know what might have caused it?

**Comment by Mugen87** [comment]
I'm afraid this is a side effect of 2a853ac822aa396f8cafedb30b6693b9a87cd848.

`if (window)` does not work in a node environment. It should be `if ( typeof window !== 'undefined' ) {`.

**Comment by Mugen87** [comment]
87e6d9ee726afe240856d699e026fdcf55127138

Okay, the script works now again.

**Comment by mrdoob** [comment]
Thanks @Mugen87 🙏

**Comment by remmel** [comment]
I was looking for the command, this is now `npm run build-examples`
