### ISSUE TITLE
For HELP~

### ISSUE THREAD

**Issue by helloCheng09** [mrdoob/three.js#21141]
**Describe the bug**

In vue-cli , test unit, warning from Eslint when I import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls'

**To Reproduce**

import
![image](https://user-images.githubusercontent.com/41097785/105673923-b333ad80-5f21-11eb-983f-a8c45e54e125.png)

npm run test:unit
warning! fail! ~~

![image](https://user-images.githubusercontent.com/41097785/105673977-c777aa80-5f21-11eb-8d96-1a56032d53ba.png)

How can I right import the OrbitControls module ?

**Comment by helloCheng09** [comment]
This problem has been eating up my whole day. I'm sick

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
