### ISSUE TITLE
does three.js supports subdivision modifier and shape keys (morph targets) on same model?

### ISSUE THREAD

**Issue by arslan1991** [mrdoob/three.js#21147]
does three.js supports subdivision modifier and shape keys (morph targets) on same model? if no then is there any solutions for this ? thanks in advance :)

**Comment by donmccurdy** [comment]
SubdivisionModifier is not very compatible with more recent versions of the library, and will be removed in the next release. I'm afraid there is not any current solution for what you're asking, and you may want to consider applying subdivision in a tool like Blender before bringing the model into three.js. If you need help looking for other ways to handle this, please use the [forum](https://discourse.threejs.org/) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
