### ISSUE TITLE
HDR Background becomes a tiny cube when using Three.OrthographicCamera and is unable to properly light meshes. 

### ISSUE THREAD

**Issue by dewball345** [mrdoob/three.js#21140]
**Describe the bug**

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.
When using `THREE.OrthographicCamera` and HDR Lighting, The HDR Lighting does not cover the background, and it is instead a tiny cube that is hard to spot at first but can be seen.

A problem with this is that the mesh does not get the proper lighting that it needs. It appears to be black, and the colors are hard to find.

**To Reproduce**

1. Go to 
https://glitch.com/edit/#!/invincible-voltaic-mandible and remix the project. Do this to edit it.
2. Change the `want_to_see_bug` variable to `false`
2. Click on "show"
3. Use your mouse to find the glasses mesh. They shouldn't be visible at first, so you will have to use OrbitControls to find them. You will have to move your cursor to the right while clicking the screen to find them. You can clearly see the HDR Background as well.

Picture of Expected results:
![image](https://user-images.githubusercontent.com/30184788/105644657-81501780-5e4b-11eb-824a-ac944eb02d25.png)

4. To see the bug, change the `want_to_see_bug` variable to `true`
5. You will be able to see the glasses immediately. They will be darker this time. If you look closely, you may notice a little speck.

Picture of Expected results:
![image](https://user-images.githubusercontent.com/30184788/105644676-a47ac700-5e4b-11eb-9854-0c3482409bd8.png)

6.Zoom into the speck. You will see the hdr background.

What you should see:
![image](https://user-images.githubusercontent.com/30184788/105644698-be1c0e80-5e4b-11eb-83b6-6128233a0ada.png)

***Code***

```js
import {RGBELoader} from "https://cdn.jsdelivr.net/npm/three@0.116.1/examples/jsm/loaders/RGBELoader.js"
import {OrbitControls} from "./OrbitControls.js"
import {GLTFLoader} from 'https://threejsfundamentals.org/threejs/resources/threejs/r122/examples/jsm/loaders/GLTFLoader.js';
// client-side js
// run by the browser each time your view template is loaded

// Extract globals, otherwise linting gets angry
const { THREE } = window;

// Create a scene
const scene = new THREE.Scene();

const want_to_see_bug = true;

var camera;

if(!want_to_see_bug){
  camera = new THREE.PerspectiveCamera(
    50, window.innerWidth / window.innerHeight, 0.1, 1000
  );  
} else {
  camera = new THREE.OrthographicCamera(-window.innerWidth/2, window.innerWidth/2, -window.innerHeight/2, window.innerHeight/2, -1000, 1000);
}



const renderer = new THREE.WebGLRenderer();
renderer.setClearColor(0xdfdfdf);
renderer.setPixelRatio(window.devicePixelRatio);
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 0.8;
renderer.outputEncoding = THREE.sRGBEncoding;
document.body.appendChild(renderer.domElement);

var orbitControls = new OrbitControls(camera, renderer.domElement);

// Add a cube to the scene
// Position our camera so we can see the cube
camera.position.z = 5;

async function createGLTF(objPath) {
    return new Promise(async (resolve, reject) => {
        const gltfLoader = new GLTFLoader();
//            objLoader.setMaterials(material);
        var loader = gltfLoader.load(objPath, (result) => {
//                root.children[0].material = material.materials['TextureAtlas_1001.001'];
            var root = result.scene
            root.scale.setScalar(10);
            root.name = "goggles";
            root.castShadow = true; 
            root.receiveShadow = true;
            //root.rotation.x = -90;
            resolve(root);
            console.log("Called!")
        });
    });
}


function setLighting(){
//    const light = new THREE.PointLight(0xffffff, 2, 10);
//    light.position.set(0, 10, 0);
//    scene.add(light);
//    var hemiLight = new THREE.HemisphereLight( 0xffffbb, 0x080820, 2 );
//    scene.add( hemiLight );
    //Stop undoing here
    new RGBELoader()
		.setDataType( THREE.UnsignedByteType )
		.setPath( 'https://threejs.org/examples/textures/equirectangular/' )
		.load( 'royal_esplanade_1k.hdr', function ( texture ) {

		var envMap = pmremGenerator.fromEquirectangular( texture ).texture;

		scene.background = envMap;
		scene.environment = envMap;

		texture.dispose();
		pmremGenerator.dispose();
    })
    var pmremGenerator = new THREE.PMREMGenerator( renderer );
	pmremGenerator.compileEquirectangularShader();

}
setLighting()
// Start the render loop 
function render() {
  window.requestAnimationFrame(render)
  
  // cube.rotation.x += 0.01
  // cube.rotation.y += 0.01
  
  renderer.render(scene, camera);
}

async function main(){
  let gltf = await createGLTF("https://cdn.glitch.com/e1eb5a31-da47-44de-8b80-fce800254b45%2Fsungoggles3.glb?v=1611366831655");
  scene.add(gltf)
  render();
}

main();
```

***Live example***

* https://glitch.com/edit/#!/invincible-voltaic-mandible

**Expected behavior**

I expected to see the glasses, with the expected color and texture, as well as the HDR Background actually acting like a background and not as a little speck.

**Screenshots**

![image](https://user-images.githubusercontent.com/30184788/105644657-81501780-5e4b-11eb-824a-ac944eb02d25.png)
Expected Result(but i want it to be like that for OrthographicCamera)

![image](https://user-images.githubusercontent.com/30184788/105644676-a47ac700-5e4b-11eb-9854-0c3482409bd8.png)
How the glasses actually look like with Orthographic Camera

![image](https://user-images.githubusercontent.com/30184788/105644698-be1c0e80-5e4b-11eb-83b6-6128233a0ada.png)
How the HDR Background looks like.

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r???]
 - I am not sure about the THREE.js version as I used `https://threejs.org/build/three.js`. I assume it gives the latest version. Also, For my RGBELoader(which loads texture for hdr background) I used `three@0.116.1` and for my GLTFLoader(which loads the 3d model) I used `threejs/r122`. Not sure if those mean versions but they were present in the links.

**Comment by Mugen87** [comment]
More simplified demo: https://jsfiddle.net/sou890km/

It seems `Scene.background` does not work with orthographic cameras.

**Comment by WestLangley** [comment]
@dewball345 Also see [this SO answer](https://stackoverflow.com/questions/17558085/three-js-orthographic-camera/17567292#17567292) for how to instantiate an orthographic camera properly.
