### ISSUE TITLE
Hand meshes no longer appearing

### ISSUE THREAD

**Issue by DaveSeidman** [mrdoob/three.js#21150]
**Describe the bug**

Hand tracking demos from https://threejs.org/examples/ no longer display hands. I noticed the issue starting today and suspect there's been an update to the Oculus browser. However I can't find any actual dates on their release notes page: https://developer.oculus.com/documentation/oculus-browser/browser-release-notes/

I'm assuming the change is on Oculus's end as I've not changed versions of threejs (r124) for the past few weeks and the issue began today. I also noticed that previously, I needed to enable hand tracking in the oculus browser's chrome://flags however when I tried loading the demos today, the browser displays a permissions dialog at the bottom to allow hand tracking.  

Maybe Oculus is moving this out of experimental and into a normal feature with permissions which would be nice, however they might have changed their implementation and now `WebglRenderer.xr.getHand()` will need to be updated. Aside from not being able to see the hands, I'm also getting errors trying to read the joint information inside the render loop. 

**To Reproduce**

Visit any of the VR hand tracking demos from http://threejs.org/examples
Pay attention to whether the browser prompts you to enable hands or not (I believe this is related to the issue)
See if your hands appear or not.

**Platform:**

 - Device: Oculus Quest 1 _(waiting for colleagues to test Quest 2, will update issue after)_
 - Browser: Oculus Browser 13.4.0.3.15.268829550
 - Three.js version: Assuming latest (whichever version examples are currently using)

**Comment by Mugen87** [comment]
see https://discourse.threejs.org/t/webxr-demos-not-working/22676/3

This should be fixed with the next `three.js` release `r125` this week.

In the meanwhile, you can work with the examples on `dev`.

https://raw.githack.com/mrdoob/three.js/dev/examples/index.html

**Comment by DaveSeidman** [comment]
Ah thanks! I should have searched the forums as well the github issues. Glad you're aware of it and thanks for the hard work!
