### ISSUE TITLE
Documentation for Vector3.clampLength() should say what it does.

### ISSUE THREAD

**Issue by j13ag0** [mrdoob/three.js#21152]
**Is your feature request related to a problem? Please describe.**
Doc for Vector3.clampLength() needs to explain what it does to the Vector3.
I assume that it scales the Vector3 so that it conforms to the minimum or maximum length value as required, but that's not what the doc says.

The doc is unclear on what happens to the Vector3.

**Describe the solution you'd like**
Please describe what happens to the Vector3 itself.

**Describe alternatives you've considered**

**Additional context**

**Comment by Mugen87** [comment]
> I assume that it scales the Vector3

Can you please explain why? The method just clamps the vector's length to the given min/max values.

**Comment by mrdoob** [comment]
Agreed 👍

@j13ag0 Please, fill the issue template properly next time.

**Comment by j13ag0** [comment]
My apologies for not filling the entire template.  I thought my question / request was clear, but I guess not.

What I'm suggesting is that the documentation explain how  clampLength()  operates on the vector.

My assumptions:
.clampLength() is a one-time operation where the length of the vector is compared against the specified minimum and maximum length values. 
For the case where the length is less than the minimum, the vector would be scaled up so that its length is now the minimum.
For the case where the length is greater than the maximum, the vector would be scaled down so that its length is now the maximum.

If .clampLength() does something different, what would that be ?

My suggestion is that the docs provide enough information that the user doesn't need to read the code for clampLength() to understand how it operates.

**Comment by mrdoob** [comment]
If you need help, please use the [forum](https://discourse.threejs.org/), the [chat](https://discord.gg/HF4UdyF) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

**Comment by j13ag0** [comment]
Thanks for the pointers to the information sources.  

After looking at the code for Vector3.clampLength(), I may come back here to submit a properly filled suggestion.

In my view the documentation could be better.
