### ISSUE TITLE
Documentation for Vector3.clampLength() should say what it does to the Vector3.

### ISSUE THREAD

**Issue by j13ag0** [mrdoob/three.js#21153]
**Is your feature request related to a problem? Please describe.**

I suggest that the Docs explain how  .clampLength()  operates on the  Vector3  to achieve the clamp.

Docs says:
<p><samp>
min - the minimum value the length will be clamped to
max - the maximum value the length will be clamped to

If this vector's length is greater than the max value, it is replaced by the max value.
If this vector's length is less than the min value, it is replaced by the min value.
</samp></p>

"...it is replaced by the max value":  What is replaced by  max value ?

**Describe the solution you'd like**

The Docs could say:
<p><samp>
min - the minimum value the length will be clamped to
max - the maximum value the length will be clamped to

If this vector's length is greater than the max value, the vector will be scaled up so its length is the max value.
If this vector's length is less than the min value, the vector will be scaled down so its length is the min value.
</samp></p>

**Describe alternatives you've considered**

**Additional context**

Users who understand operations on vectors will probably make correct assumptions about how .clampLength() needs to work. 
With that said, being explicit about how it works is an easily made enhancement to the docs to help users who don't necessarily have the math background.

In my view API documentation should provide a shortcut for API users so they don't need to look at the source for every question they have about how the API does its job.

**Comment by mrdoob** [comment]
You can edit the page directly by clicking the edit button (bottom-right):

<img width="1238" alt="Screen Shot 2021-01-26 at 5 41 59 PM" src="https://user-images.githubusercontent.com/97088/105882656-cd42be00-5ffd-11eb-9ba9-628ce24fee6c.png">
