### ISSUE TITLE
Editor: Memory leak when loading 4096x4096 texture several times

### ISSUE THREAD

**Issue by RealTecWare** [mrdoob/three.js#21151]
**Describe the bug**

I tried to edit the [MaterialsVariantsShoe.glb](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MaterialsVariantsShoe/glTF-Binary) file from the KhronosGroup git in the [editor](https://threejs.org/editor/) and changed the normalMap and aoMap textures several times to a 4096x4096 texture.

I could use the same texture several times and the memory starts to increase after ~9-10 times (in my tests the value of changes sometimes were even smaller).
That causes the webgl context to crash after enough changes.

**To Reproduce**

1. Go to [ThreeJS Editor](https://threejs.org/editor/)
2. Import [MaterialsVariantsShoe.glb](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MaterialsVariantsShoe/glTF-Binary)
3. Change material to MeshPhysicalMaterial
4. Set the normalMap / aoMap >10 times to a 4096x4096 texture 
5. The leak begins to grow after every following change 

**Expected behavior**

After my analysis this only happens in 64bit browsers. 
The following lines of `WebGLState.js` causes the increasment.

	function texImage2D() {

		try {

			gl.texImage2D.apply( gl, arguments ); //After this function call the memory was increased highly and is only freed after closing or reloading the tab / browser.

		} catch ( error ) {

			console.error( 'THREE.WebGLState:', error );

		}

	}

**Screenshots**

After 30 changes with the same texture:

| Browser  | Taskmanager Image |
| ------------- | ------------- |
| Vivaldi 32bit | ![image](https://user-images.githubusercontent.com/11577704/105855606-8dbda700-5fe8-11eb-9e63-5fd1c43a3e4b.png)  |
| Vivaldi 64bit | ![image](https://user-images.githubusercontent.com/11577704/105855598-8c8c7a00-5fe8-11eb-946e-94b3a505f463.png)  |
| Chrome 32bit | ![32bit_30times](https://user-images.githubusercontent.com/11577704/105855602-8d251080-5fe8-11eb-945f-f889147fc3db.png)  |
| Chrome 64bit | ![64bit_30times](https://user-images.githubusercontent.com/11577704/105855603-8d251080-5fe8-11eb-84c4-e0867e7f3e2d.png)  |

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, Android, IPadOS]
 - Browser: [Chrome, Canary Chrome, Firefox, Safari, Edge, Opera, Vivaldi, Opera GX, Chrome for Android]
 - Three.js version: r117 - r124

**Comment by mrdoob** [comment]
What happens if you load it more than 30 times? Are you able to crash the browser?

**Comment by RealTecWare** [comment]
I'm able to crash the webgl context with this, after the memory is over ~8GB (set the normalMap ~90-100 Times in my test).

![context_lost](https://user-images.githubusercontent.com/11577704/105868408-708fd500-5ff6-11eb-97f5-7a0773bb35b1.png)

**Comment by RealTecWare** [comment]
I have created a small [example](https://www.realtecware.de/memory-overflow/), where I simulate the situation.  (~53 secounds - ~53 changes to the same texture) 

If you use this [example without ao change](https://www.realtecware.de/memory-overflow/#withoutAO=true) it only change the normalMap. (95 secounds - 95 changes to the same texture)

**Comment by Mugen87** [comment]
Can you please call `Texture.dispose()` every time you replace an existing texture?

**Comment by RealTecWare** [comment]
Thanks, that fixes the problem in my example. 
Could it be that the editor never dispose the textures that are loaded?

**Comment by Mugen87** [comment]
> Could it be that the editor never dispose the textures that are loaded?

Yes, I guess this is the problem. A quick search shows that `dispose()` is never used on a texture.

**Comment by RealTecWare** [comment]
The biggest question in my mind is at the end, why does the 64 bit browsers crash and 32 bit don't?
Maybe better garbage collection or less caching on the nativ side, because memory is a bigger thing with 32 bit.

But for now the problem can be solved by disposing and that's all what matters.
