### ISSUE TITLE
Removing Generics from Meshes causes a lot of headaches

### ISSUE THREAD

**Issue by joshuaellis** [mrdoob/three.js#21172]
**Describe the bug**

For some context, i'm using `react-three-fiber`. My use case is when i'm loading a `GLTF` model, to TS it's a black box, So I know it's a mesh & can typecast the return of the `gltf` to be `Mesh`. However, when I want to edit the properties of the mesh materials, I now have to typecast the material because `Mesh` is no longer a generic. This is quite a headache. I'm not saying i'm right, it'd be good to get some clarity on why this [commit](https://github.com/mrdoob/three.js/commit/8c4ff573de466cd97d1074c73b7d8e675a0fe1f5) was done?

***Old Code***

```ts
type GLTFResult = GLTF &
  ObjectMap & {
    nodes: {
      [name: string]: Mesh<BufferGeometry, MeshStandardMaterial>
    }
  }

  const { nodes } = useGLTF(
    `${ENV_MODEL_PATH}/rain/RainPond_Droplets_Polyredux.gltf`
  ) as GLTFResult

  const instanceMeshes = React.useMemo(
    () =>
      meshes
        .filter((mesh) => mesh.material)
        .map((mesh, i) => {
          mesh.material.metalness = 0 // all good here, no typecast needed
          mesh.material.transparent = true
          mesh.material.onBeforeCompile = compileMaterialForInstance

          mesh.geometry.setAttribute(
            'instOpacity',
            new InstancedBufferAttribute(
              new Float32Array(new Array(INSTANCE_COUNT).fill(0)),
              1
            )
          )

          return (
            <instancedMesh
              ref={(ref: THREE.InstancedMesh) =>
                setKeyValue(instanceRefs.current, i, ref)
              }
              key={mesh.name}
              args={[mesh.geometry, mesh.material, INSTANCE_COUNT]}
            />
          )
        }),
    [meshes]
  )
```

***New Code***

```ts
type GLTFResult = GLTF &
  ObjectMap & {
    nodes: {
      [name: string]: Mesh
    }
  }

  const { nodes } = useGLTF(
    `${ENV_MODEL_PATH}/rain/RainPond_Droplets_Polyredux.gltf`
  ) as GLTFResult

  const instanceMeshes = React.useMemo(
    () =>
      meshes
        .filter((mesh) => mesh.material)
        .map((mesh, i) => {
          mesh.material.metalness = 0 // this now throws an error because metalness does not exist on type Material[]
          mesh.material.transparent = true
          mesh.material.onBeforeCompile = compileMaterialForInstance

          mesh.geometry.setAttribute(
            'instOpacity',
            new InstancedBufferAttribute(
              new Float32Array(new Array(INSTANCE_COUNT).fill(0)),
              1
            )
          )

          return (
            <instancedMesh
              ref={(ref: THREE.InstancedMesh) =>
                setKeyValue(instanceRefs.current, i, ref)
              }
              key={mesh.name}
              args={[mesh.geometry, mesh.material, INSTANCE_COUNT]}
            />
          )
        }),
    [meshes]
  )

```

**Expected behavior**

Ideally i'd like to pass the Generics back in, because even if it was able to figure out if it was `Material` or `Material[]` I know the material is `MeshStandardMaterial` so `metalness` will still throw a typescript error.

***disclaimer*** 
I'm happy to work on a solution if we want to fix this.

**Platform:**

 - Three.js version: r125

**Comment by mrdoob** [comment]
@drcmda help 😅

**Comment by joshuaellis** [comment]
I can recreate it in `three` if that's more helpful to understand @mrdoob?

**Comment by mrdoob** [comment]
Please do 🙏

**Comment by joshuaellis** [comment]
Okay, so please forgive me if it's a bit scruffy, I've done a *rough* translation.

```ts
type GLTFLoaded = GLTF  {
    nodes: {
      [name: string]: THREE.Mesh;
    };
  };

const loader = new GLTFLoader();
loader.load("/public/RainPond_Droplets_Polyredux.gltf", function (gltf) {
  function buildGraph(object) {
    const data: ObjectMap = {
      nodes: {}
    };

    if (object) {
      object.traverse((obj) => {
        if (obj.name) data.nodes[obj.name] = obj;
      });
    }

    return data;
  }

  const data = Object.assign(gltf, buildGraph(gltf.scene));

  const { nodes } = data as GLTFLoaded;

  const meshes = Object.values(nodes)
    .filter((mesh) => mesh.material)
    .map((mesh, i) => {
      mesh.material.metalness = 0;
      mesh.material.transparent = true;

      return mesh;
    });

  meshes.forEach((mesh) => scene.add(mesh));
});
```

The issue being is I need to mutate the mesh objects coming from the GLTF, which I can do, but it the `material` type is set incorrectly, being just `Material | Material[]` it 
a. thinks it's `Material[]`.
b. the basic `Material` does not have the property metalness. I know that my meshes are using `MeshStandardMaterial` so metalness will do something.

So bringing back generics, my type can be:
```ts
type GLTFLoaded = GLTF  {
    nodes: {
      [name: string]: THREE.Mesh<THREE.MeshStandardMaterial>;
    };
  };
```

Which would resolve my errors. In the commit I posted above, these generics were all removed :(

**Comment by mrdoob** [comment]
I do not understand how removing `THREE.Geometry` has anything to do with the `Material | Material[]` type.

**Comment by mrdoob** [comment]
Ah, I guess you mean this?

https://github.com/mrdoob/three.js/commit/8c4ff573de466cd97d1074c73b7d8e675a0fe1f5#diff-8519e7ab01aba393f7e26bfd50c685ec61c3f49d771d367f600688d732149390L7-L10

**Comment by joshuaellis** [comment]
Yes, I was just replying. It's that, but it also applies to other meshes likes `InstancedMesh`

**Comment by joshuaellis** [comment]
TBF we only(?) required 1 generic now for the material.

**Comment by mrdoob** [comment]
I have the feeling this is going to end like https://github.com/mrdoob/three.js/pull/19702

**Comment by mrdoob** [comment]
I'm very tempted of moving the d.ts files back to https://github.com/DefinitelyTyped/DefinitelyTyped.
The amount of time that maintaining these types takes is starting to be not worth it.

**Comment by joshuaellis** [comment]
It's definitely hard work and a trendous under taking to manage them yourself. Have you thought about trying to recruit TS people to help out on the repo? At minimum, I am happy to redo the Generic work on Meshes, if I understood why you took them out in the first place?

I suppose the reason you might have moved away from DefinitelyTyped is because they weren't being updated quick enough & people had issues?

**Comment by mrdoob** [comment]
> It's definitely hard work and a trendous under taking to manage them yourself. Have you thought about trying to recruit TS people to help out on the repo?

I have. But no one has stepped up so far. Do you want to take ownership?

> I suppose the reason you might have moved away from DefinitelyTyped is because they weren't being updated quick enough & people had issues?

@bhouston suggested doing so and I trusted him.

**Comment by joshuaellis** [comment]
> I have. But no one has stepped up so far. Do you want to take ownership?

I think it would be good to set out the expectations, but I'm no `THREE` expert. But I am happy to take a level of ownership, my only worry is that the library moves really quickly and I won't be able to keep up with the level of demand it takes. I suppose if someone fixes something they should surely update the `.d.ts` file at the same time? (obviously if they need support it can be given)

Thoughts?

**Comment by mrdoob** [comment]
> I suppose if someone fixes something they should surely update the `.d.ts` file at the same time?

And that's how you force JavaScript people learn TypeScript. Makes contributing harder.

I'm not liking this at all.

**Comment by joshuaellis** [comment]
> And that's how you force JavaScript people learn TypeScript. Makes contributing harder.

This isn't my intention. I was more suggesting that if a PR is made that changes something that *requires* a `.d.ts` change, then it should be done at the same time, whether that is someone like myself introducing the change, or if the original contributor is able to, doing so themself.

**Comment by mrdoob** [comment]
#21174

**Comment by bhouston** [comment]
> > I suppose the reason you might have moved away from DefinitelyTyped is because they weren't being updated quick enough & people had issues?
> 
> @bhouston suggested doing so and I trusted him.

We could move them back to definitely typed if that is the best solution.  When we moved them into the repository there was a lot of coverage missing that we added.

I did sort of thing that it was the first step towards moving to TS fully for the project.  But I think Three.js is not going in that direction.

**Comment by mrdoob** [comment]
@bhouston Yeah, I think that'd be best thing to do: #21174

**Comment by joshuaellis** [comment]
Fair enough.
