### ISSUE TITLE
为什么模型缩小以后 有黑色的描边？？

### ISSUE THREAD

**Issue by a6965921** [mrdoob/three.js#21179]
为什么模型缩小以后 有黑色的描边？？
![image](https://user-images.githubusercontent.com/1198840/106352832-1ad26a00-6321-11eb-9e7e-5b8581b847dc.png)
wo我这个图是几个模型拼起来的 单独模型是用黑边的 但是不缩小就没有

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests. Besides, please write your posts in English.
