### ISSUE TITLE
WebXR: Provide way to get XR viewport resolution when presenting

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#21188]
**Is your feature request related to a problem? Please describe.**

The [3DTilesRenderJS](https://github.com/NASA-AMMOS/3DTilesRendererJS) project requires information about the screen resolution in order to derive screen error and determine which 3d tiles data to render. Right now `WebGLRenderer.getResolution` and `WebGLRenderer.getViewport` both provide the resolution of the canvas rather than the render resolution of the VR device.

**Describe the solution you'd like**

I would like a supported way to read the viewport or resolution of the XR device when XRManager is presenting or for `WebGLRenderer.getResolution` to return the resolution of the XR device when presenting. This information is already available on the [camera.viewport](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webxr/WebXRManager.js#L436) vector for each eye camera but is not exposed in any documented way.

**Describe alternatives you've considered**

Related to #21002 to work around this I use the undocumented `WebXRManager.getCamera( camera )` and wait until the list of cameras is populated in order to read the viewport of one of the eye cameras. The viewport is not available for the first frame after beginning presenting.

**Comment by dbuck** [comment]
Is the framebuffer resolution useful there, that's a documented property of the baseLayer?
```
    if (session.renderState.baseLayer) {
      const { framebufferWidth, framebufferHeight } = session.renderState.baseLayer;
      console.log(`Session framebuffer`, { framebufferWidth, framebufferHeight });
    }
 ```
 
A couple other non documented routes:

Stash the XRFrame, which is the second arg to setAnimationLoop when xr is presenting, and use getViewerPose / reference spaces to read the viewports from there :|

Another is hackily checking in a scene.onBeforeRender whether the camera is an ArrayCamera && xr.isPresenting and reading them from there heh.

**Comment by CodyJasonBennett** [comment]
This will need to be re-opened unless you pick changes to `EffectComposer` from #26160 which was reverted.

**Comment by Mugen87** [comment]
It would be great if you could file a separate PR with the code related to this issue.
