### ISSUE TITLE
Strict type check on geometry object before accessing key like  isGeometry

### ISSUE THREAD

**Issue by anilarya** [mrdoob/three.js#21189]
**Describe the bug**

Application throwing error **Cannot read property 'isGeometry' of null** .

**To Reproduce**
 
Send/pass geometry object as null.

***Code snippet***

https://raw.githubusercontent.com/mrdoob/three.js/dev/build/three.js

```js
_proto.expandByObject = function expandByObject(object) {
			// Computes the world-axis-aligned bounding box of an object (including its children),
			// accounting for both the object's, and children's, world transforms
			object.updateWorldMatrix(false, false);
			var geometry = object.geometry;

			if (geometry !== undefined) {// There should be strict type check here.  Why you are not handling null condition.  
				if (geometry.boundingBox === null) {
					geometry.computeBoundingBox();
				}

				_box.copy(geometry.boundingBox);

				_box.applyMatrix4(object.matrixWorld);

				this.union(_box);
			}

			var children = object.children;

			for (var i = 0, l = children.length; i < l; i++) {
				this.expandByObject(children[i]);
			}

			return this;
		};
```
 

**Expected behavior**
There should be strict type check on geometry object before fetching any key inside object.
.

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).
![image](https://user-images.githubusercontent.com/6001096/106548664-68272500-6535-11eb-92cd-1d8a0ffe06a5.png)

**Platform:**

 - Device: [Desktop ]
 - OS: [ MacOS ]
 - Browser: [Chrome ]

**Comment by donmccurdy** [comment]
The argument to `expandByObject` is expected to be an Object3D or a subclass. The [Mesh.geometry](https://threejs.org/docs/index.html#api/en/objects/Mesh.geometry) property is not nullable. We do not typically include validation of incorrect inputs to three.js methods, as this creates performance costs paid even by users who are using the APIs correctly.

**Comment by anilarya** [comment]
@donmccurdy :  There are few places in same file where null/undefined/emptiness checks  exist for **geometry**

Example:   
 Inside function **SkinnedMesh**
`if (geometry && geometry.isGeometry) {`

Cannot have similar condition everywhere ?  How will it effect performance ?

**Comment by donmccurdy** [comment]
Checking for `.isGeometry` has a different effect — until r125, three.js had two different geometry implementations, Geometry and BufferGeometry. They are not subclasses of one another, and the `.isGeometry` check was there to detect the older type.

With Geometry now removed, perhaps we should be checking these properties differently... I'm not sure on that.

**Comment by Mugen87** [comment]
> Cannot have similar condition everywhere ? How will it effect performance ?

I would rather remove the checks in `SkinnedMesh` that adding them elsewhere in the code.

The checks for `isGeometry` were introduced so the engine can specifically log a warning if user still use `Geometry` in context of certain engine features like raycasting. After a while, we can delete them and always assume instance of `BufferGeometry`.
