### ISSUE TITLE
geometry: .center() vs .computeBoundingBox

### ISSUE THREAD

**Issue by JHB101** [mrdoob/three.js#21196]
Hi,
For fonts created in ThreeJS, when I use .center() and it computes the bounding box automatically it is different than then I manually calculate it. This is an inconsistent result that is breaking my code where I have to display text in pixel perfect boxes. I need to handle vertical centered calculations differently so I cannot use .center() for all text, but now the x axis varies.

Steps to reproduce:
1. Create a font geometry with .generateShapes() using any word.
2. Center the geometry using .center() command.
3. Display the bounding box in the console.
4. Now repeat steps 1 & 2, but compute the bounding box manually using .computeBoundingBox() command.
5. Display the bounding box in the console.

You will notice a difference after the decimal point on the x axis. Subtracting the boundingBox.max.x from the boundingBox.min.x and dividing it by two for step 4 does not give you the same center point as obtained from the .center command.

```js
let a=new THREE.ShapeBufferGeometry(SomeFont.generateShapes('Testicle',30));
a.computeBoundingBox();
let b=a.clone().center();//or create it manually like a. It makes no difference.
console.log('a :',a.boundingBox);
console.log('b :',b.boundingBox);
console.log((a.boundingBox.max.x-a.boundingBox.min.x)/2.0);
/*The last line should log the same as b.boundingbox's x axis allready in
the console, but it is not resulting in text moving slightly horizontally.*/
```

Kind Regards
Jayson

 - Device: Desktop
 - OS: Windows
 - Browser: Firefox
 - Three.js version: r120

**Comment by Mugen87** [comment]
> The last line should log the same as b.boundingbox's x axis allready in the console,

Sorry, but I'm afraid this assumption is wrong. When you center a geometry, an existing bounding box will be recomputed based on the translated (centered) vertex data. 

The following live example demonstrated this: https://jsfiddle.net/ontmckr5/1/

Even if the geometry was already centered, the new bounding box might deviate because of minor floating point inaccuracies.

**Comment by JHB101** [comment]
Hi @Mugen87 

Thanks for the response.

Keep in mind that I am only interested and referring to the x axis of the bounding box from this point onward.

Neither of my two geometries ([a] and [b] in my code above) have an existing bounding box. Your wiki clearly states the bounding box starts off as null when you create a geometry for the first time. At this point if I use the .computeBoundingBox() command on both [a] and [b] individually they give identical numbers which is correct. No minor floating point inaccuracies here.

Say now instead I use the .center() command on [a], I imagine your code will create a bounding box from scratch and then center it via translation and some math.
console.log(a.boundingBox) reveals:
max: Object { x:  26.607500076293945,...
min: Object { x: -26.607500076293945,...
Perfectly centered.

Seeing as I cannot use the .center() command, I use the .computeBoundingBox() command on [b] instead and then manually center [b] using the .translate(-((b.boundingBox.max.x-b,boundingBox.min.x)/2.0)) its bounding box's x axis should now be exactly the same as that of [a] which was auto centered (unless the .center() command uses different math).
console.log(b.boundingBox) reveals:
max: Object { x:  26.83949851989746,...
min: Object { x: -26.375499725341797,...

I don't know where to find your .center() command in your files, but it is doing something different than the standard math being advocated everywhere on the net to get the center.

Kind Regards

Jayson

**Comment by Mugen87** [comment]
The code for `center()` is here:

https://github.com/mrdoob/three.js/blob/ef6a69160b795b7a03b676f6b9708d0a358736d4/src/core/BufferGeometry.js#L251-L261

**Comment by JHB101** [comment]
Hi @Mugen87 

Thanks for the reply.

I discovered the .getCenter() command shortly after my last reply and it has greatly improved my experience regarding this. It is good to see the .center() command also uses it. It keeps the math standard throughout.

PS: I may very well have wasted your time on this, since I am still not so very sure if this is even a bug or just because I was trying to put a square peg in a round hole. I will probably run to the forum first next time as I should have done.

Kind Regards

Jayson
