### ISSUE TITLE
Optimize calls to render

### ISSUE THREAD

**Issue by SntsDev** [mrdoob/three.js#21228]
**The "problem"**

Our projects render on mobile phones, tablets and laptops. WebGL consumes the battery so rapidly and, on my laptop, the fans start spinning so fast that I sometimes believe it's a drone and I worry about it start flying.

**Describe the solution you'd like**

I have implemented a library for my own projects that I call it "**ShouldRender**". It's a very simple singleton (an object) with a little number of properties and methods that allow me to omit calls to `renderer.render(camera, scene)` by providing a flag that it should be used as a condition for calling `renderer.render` or not.

Conceptually, it just keeps track of the render time that your scene requires in the immediate future (with some default value) and updates that flag.

In it's most simple use case, you tell it how many seconds (or fractions) you need it to keep rendering. For instance, if you have a Tween from gsap, you can call it on the `onStart` callback or `onRepeat`.  It also has some methods to facilitate things. For instance,  you can connect it to controls that emit `onchange`, like the `OrbitControls`, so it does it automatically. There are some occasions that you need your scene to keep rendering because you're changing parameters on every call, or you have a Model with an Animation that repeats with the `AnimationMixer`. It has a property called `dontStop` that when set to true keeps the flag to be true until you set it `dontStop` to false again. Another property called `forceStop` overrides any time ahead, useful for those situations where you're preparing materials or making hard calculations. 

If you implement some sort of reactive store, like MobX, where the objects (or a class that wraps the Meshes, for instance) emit changes, will allow you to set the rendering time automatically without missing anything.

Example of manually setting the time-ahead:
```
//on init()
    THREE.ShouldRender.listenTo(orbitControls);
    ...
    ...
//anywhere
    THREE.ShouldRender.addTime(1000); // 1 second
    ...
    ...
//when you animate
    gsap.to(object.position, { 
        duration, 
        x: 10, 
        /* more attributes */,
        onStart: _ => THREE.ShouldRender.addTime(duration * 1000);
    });
    ...
    ...
//Later, on the "render" function of your app
    
    render() {
    
        //Whatever your app needs
        ...
        
        if (THREE.ShouldRender.flag) {
            renderer.render(camera, scene);
        }
    
    }
```

**Describe alternatives you've considered**

I have discarded GPU solutions because the idea is to stop rendering. When you do it, How does your app know that it needs rendering back again?

**Additional context**

It doesn't intend to substitute the `setAnimationLoop`. It doesn't set or require the animation-frames.

It's an object and a singleton that is available with a simple _import_, without needing to be instantiated or be passed, to allow this logic in places where it's needed easily.

**Summary and Question**

Does it make sense to create this as a *feature* of **THREE** or just keep it as a personal solution?

I'd like to make that contribution to the community if you think it's a good idea. 

I'd also like to know if there are simpler and better ideas that we all can profit from.

**Comment by mrdoob** [comment]
> Does it make sense to create this as a feature of THREE or just keep it as a personal solution?

Better to keep it as a personal solution.
