### ISSUE TITLE
Add texture exporting functionality in USDZExporter

### ISSUE THREAD

**Issue by probator1059** [mrdoob/three.js#21241]
- Description of the problem
  This is relating to the current threejs exporting functionalities.
  The current USDZexporter provided in threejs library is able to parse the scene and export it as the usdz format as in gltf-exporter.
  The only issue I found is that it does not support the exporting texture. 
  The USDZ format is for AR experience, especially in iOS, iPad. Much of USDZ producing tools are just for macOS users.
  Even though it is not so popular as gltf/glb, it is necessary for those who use Apple devices. 
  It would be great if this new feature would be added as soon as possible.

**Comment by mrdoob** [comment]
> The only issue I found is that it does not support the exporting texture.

It doesn't support lights either, nor skinning, morphs, animations, ...
