### ISSUE TITLE
Three.js freezes CSS animated background images and transitions

### ISSUE THREAD

**Issue by richardevcom** [mrdoob/three.js#21255]
**Describe the bug**

Three.js (WebGL) freezes background animations (.gif in my case) and CSS transitions. Bascially when i don't trigger any CSS transition, the background GIF seems to freeze... but when I do trigger CSS transition (literally any), everything seems to move/animate/transition like it should.

**To Reproduce**

I'm running localhost dev server (https://github.com/h5bp/html5-boilerplate) with parcel, where i simpy load index.html file, with one CSS and one JS file.
I'm using Firefox Browser Developer edition 86.0b8 (64-bit) to view this project.

CSS contains Tailwind CSS and JS file contains Three.js (nothing fancy, really basic code).

***Code & Live example & Video Screenshot***
Code example and video screenshot available here: https://stackoverflow.com/questions/66144168/three-js-freezes-css-animated-background-images-and-transitions

**Expected behavior**

No background gif animation or transition freezing should happen. I've tested on Chrome, Edge, Safari and Opera (all latest) and this issue happens only on Firefox Browser Developer edition 86.0b8 (64-bit)

**Platform:**

 - Device: Desktop
 - OS: Windows 10 (latest updates)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0 (Firefox Developer latest)
 - Three.js version: 0.125.2
 
 P.S. I've also submited this to Bugzilla, just in case it's a browser support issue. https://bugzilla.mozilla.org/show_bug.cgi?id=1692194

**Comment by mrdoob** [comment]
If the issue only happens in one browser, the issue is in the browser.

**Comment by richardevcom** [comment]
> 
> 
> If the issue only happens in one browser, the issue is in the browser.

I agree, that's why I submited it on Bugzilla, yet.. i've tested only 3-4 latest browsers (not developer ones with upcoming new changes) so it would be in your interest to follow this issue because with OGL or other 3D js libraries this issue doesn't happen.

**Comment by donmccurdy** [comment]
three.js, like any WebGL library, must do some tasks synchronously. Synchronous JavaScript execution will block some other functionality, like event handlers, but should not block CSS transitions on modern browsers. If JavaScript or WebGL execution is capable of blocking CSS transitions at all, that seems like a problem for the browser vendor to resolve. The fact other WebGL libraries, making different calls to JS and WebGL APIs, do not trigger the bug would indicate that only certain functions or APIs trigger the bug, and not that three.js is necessarily in the wrong.

Firefox Developer Edition also has some experimental features enabled, which may be affecting things.

**Comment by richardevcom** [comment]
@donmccurdy You do make sense, but after inspecting this issue more it appears that either somehow three.js generated canvas stops gif from playing as background image (that can only be controlled via JS) or as you mentioned before some experimental features are optimizing background gif animation causing it to freeze on no movement or transition.

I still don't agree with "If the issue only happens in one browser, the issue is in the browser." I tested only on 3 different browsers and libraries similar scenario, where only one actually stops working. There are way too many factors that may cause it, so I'd say its too early to judge and close this. Don't get me wrong, I appreciate this awesome (free) solution and I know you get many submissions, but I think this should stay open until its resolved on Bugzilla and can be confirmed as browser bug.

**Comment by mrdoob** [comment]
If the bugzilla discussion identifies an issue in Three.js we'll reopen this. Until then, better to keep this closed so we can focus on confirmed issues.
