### ISSUE TITLE
differences in stencil test behavior between webgl1 and webgl2

### ISSUE THREAD

**Issue by robertoranon** [mrdoob/three.js#21264]
Hi, I came across a weird issue using the stencil test to draw the outline of an object.

The issue can be seen here:

https://jsfiddle.net/robertoranon/u0o5hqej/64/

In a browser with only WebGL1 (e.g., Safari), this correctly draws a green box with an orange outline.

In a browser with also WebGL2 (e.g., Chrome), the box is all orange, as if the stencil test is not performed.

If one comments the line 

const gl2context = ourcanvas.getContext("webgl2");

it works in both browsers. My understanding is that the line causes the WebGL context to be a WebGL2 one, for some reason, because the same bug happens if I create the WebGL renderer passing the gl2context as context.

I'm not even sure the issue is related with three.js, it could also be due to differences between WebGL1 and WebGL2 regarding the stencil test, but I could not find any such explanation ... 

 - Device: Desktop
 - OS: MacOS
 - Browser: any
 - Three.js version: r124

**Comment by Mugen87** [comment]
TBH, I don't understand the purpose of that line. `three.js` creates a WebGL 2 rendering context by default. It fallbacks to WebGL 1 if WebGL 2 is not available (like in Safari). If I remove the line, the fiddle produces the same output in Chrome and Safari.

https://jsfiddle.net/afj6butn/

**Comment by robertoranon** [comment]
Ok, I was not sure about three.js creating a WebGL 2 context when available. That line was part of a if statement where, if gl2context was not undefined (i.e. a WebGL2 context is available), I was creating the renderer explicitly passing the context, but, if I understand correctly, that is not necessary. 

Why that line is making the stencil test behave differently, I would be curious to know, but never mind.

**Comment by Mugen87** [comment]
The problem is that the fiddle calls `getContext()` twice but the first time without any context parameters. If the render calls getContext()`, it gets the existing context.

You can easily verify this passing parameters to the first context creation.

https://jsfiddle.net/gsc4m38j/
