### ISSUE TITLE
TrackballControls: constrain movement via pan to x or y axis

### ISSUE THREAD

**Issue by mlenton** [mrdoob/three.js#21269]
> **Is your feature request related to a problem? Please describe.**

The application we are building requires camera motion via trackball control, with the direction of movement able to be constrained to the x or y axis.

> **Describe the solution you'd like**

Currently the TrackballControls example does not provide for this constraint of motion and it would be great if the current example were extended to include this.

> **Describe alternatives you've considered**

We have implemented this by duplicating/modifying the example in our own repository but consider it may be useful to others as well as a more concise solution if it were included in the example.

> **Additional context**

We've also included these options in the on-screen controls.  Happy to work through this to a solution with feedback.

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/21270#issuecomment-778868761
