### ISSUE TITLE
CSS3D "artifacts" in Three.js examples

### ISSUE THREAD

**Issue by tussiez** [mrdoob/three.js#21263]
**Describe the bug**

Displaying the Aluminum Oxide molecule in the css3D renderer example sometimes causes stripes and other shapes to be filled outside of the tab in Chrome.

**To Reproduce**

1. Go to the css3D molecules example:  https://threejs.org/examples/?q=css#css3d_molecules
2. Click on "Aluminum Oxide"
3. See error

***Live example***

* https://threejs.org/examples/?q=css#css3d_molecules

**Expected behavior**

The molecules to render correctly

**Screenshots**

![image](https://user-images.githubusercontent.com/49251771/107785020-15f6b880-6d1a-11eb-8569-97a360cd14f8.png)
![image](https://user-images.githubusercontent.com/49251771/107785149-3aeb2b80-6d1a-11eb-98b9-001557aa6300.png)
![image](https://user-images.githubusercontent.com/49251771/107785183-46d6ed80-6d1a-11eb-8a2d-9eb77d9c8bb8.png)

**Platform:**

 - Device: Lenovo laptop w/ Integrated Graphics
 - OS: Windows
 - Browser: Chrome 88
 - Three.js version: r125

**Comment by Mugen87** [comment]
It is indeed strange that these artifacts spread over the entire screen (and are not limited to a tab).

I suggest you report this issue to the Chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/list

This issue is unrelated to `three.js`.

**Comment by foolip** [comment]
This sounds similar to an issue that @chrishtr was telling me about with artifacts potentially overlapping the omnibox, which @progers has fixed. @tussiez do you see this with Chrome Canary as well? If so it would be great to have a bug filed, as @Mugen87 suggests.

**Comment by tussiez** [comment]
Yeah, I suspected this was an issue with Chrome itself. I can post a bug
report, and I'll check Chrome Canary as well.

**Comment by progers** [comment]
I've filed this at https://crbug.com/1177833. Please star for updates! I think this is likely the same bug as https://crbug.com/1174186 (sorry, it is temporarily restricted) which has a fix rolling out.

**Comment by mrdoob** [comment]
https://crbug.com/1177833 has been fixed 👍

**Comment by tussiez** [comment]
Nice!
