### ISSUE TITLE
Raycaster.intersectObjects() recursive flag

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#21278]
Perhaps it would be a good idea to default the recursive flag to `true` in `Raycaster.intersectObjects( objects, recursive, optionalTarget )`.

Failure to set the flag to true has caused confusion with users on StackOverflow for a long time.

I wonder how many current users are relying on the fact that the default value is something other than `true`?

**Comment by OleksiiMaksymovVBT** [comment]
I think it only depends on type of user, if user uses three in commercial projects, then def recursive flag is defined in code. If just newcommers, they are using default values.

**Comment by Mugen87** [comment]
I vote to give this a try and see how it goes. It seems the more appropriate default to me.

**Comment by optimus007** [comment]
so if you do recursive raycasting on every Animate frame and the model used is a gltf with a big node tree the cpu fan starts ramping up..,maybe we can mention this in the docs as a warning


_so as an alternative i put all the 'isMesh' objects from the gltf into a array and pass this to the raycaster with recurrsive off (is this valid?)_

**Comment by Mugen87** [comment]
I don't think this statement is correct. A big scene hierarchy has not necessarily a noticeable influence on the racasting performance.  The `raycast()` method is not implemented for `Object3D`, `Group` or `Bone` so there is no processing overhead for these types of objects. 

Besides, like mentioned by @WestLangley most users expect that raycasting works with the entire asset and are confused why `raycaster.intersectObject( gltf.scene );` only tests the top most node.

`Object3D.copy()` is also a deep copy. The documentation of `recursive` should be sufficient that users figure out alternative workflows by themselves.

**Comment by Mugen87** [comment]
Another user stumbled across this issue:

https://discourse.threejs.org/t/three-js-raycaster-doesnt-detect-intersection-with-gltf-object/27746

**Comment by thc282** [comment]
The default is set to true
but i dunno why is still cannot do the recursive check for me

I need to manually use IntersectObjects(array, true), then it work

- Scene
   - Group
      - Group
         - Mesh
      - Group
         - Mesh
      - Group
      - Group
      - .....
   - Light
