### ISSUE TITLE
Use getCoalescedEvents() in example controls

### ISSUE THREAD

**Issue by cshenton** [mrdoob/three.js#21273]
**Is your feature request related to a problem? Please describe.**

On Chrome 60+ (and other browsers), continuous events (mousemove, scroll) are coalesced and synced with animation frames. This causes an additional frame of input lag/smoothing which is detrimental to user experience in 3D applications.

To see what I mean, open [the pointer lock example](https://threejs.org/examples/misc_controls_pointerlock.html), move around then open and close chrome devtools (f12), which disable the event throttling (so it should be smoother, less laggy when devtools are open).

**Describe the solution you'd like**

To fix this, chrome and safari provide `PointerEvent.getCoalescedEvents()` which returns all events that occurred since the previous animation frame, rather than collapsing them. So the solution would be to replace the existing event processing code in the example controls with a loop that processes all raw events rather than processing just the single, coalesced event.

**Additional context**

- https://www.vsynctester.com/testing/mouse.html
- https://developers.google.com/web/updates/2017/06/aligning-input-events

**Comment by Mugen87** [comment]
TBH, don't get the point of this issue.

The controls in the example transform the camera. Since `mousemove` events are are coalesced and synced with animation you get exactly on event per frame that represents the user's interaction. 

It seems to me it does not make any differences to process an array of events in order to transform the camera incrementally instead of processing a single coalesced event. The final transformation will be the same. It's actually more performant to process just a single event.

**Comment by cshenton** [comment]
Yep, you're correct. What I was observing was simply a 2 frame input delay which is a result of a long-standing deficiency in chrome. Switching to firefox reduced that to 1 frame... but firefox has a long-standing where pointer lock in a non fullscreen window suffers from mouse drift.

Browsers!

So my actual problem, which is that browsers have substantial input delay, seems to be only resolvable via launch settings, which isn't something that can be done from library code, only by the user setting command line options on chrome / settings flags in firefox.

Closing.

**Comment by mrdoob** [comment]
> To see what I mean, open [the pointer lock example](https://threejs.org/examples/misc_controls_pointerlock.html), move around then open and close chrome devtools (f12), which disable the event throttling (so it should be smoother, less laggy when devtools are open).

This is actually a devtools bug: https://bugs.chromium.org/p/chromium/issues/detail?id=992954
