### ISSUE TITLE
Stop reverse animation once it reaches end

### ISSUE THREAD

**Issue by asarra** [mrdoob/three.js#21272]
**Is your feature request related to a problem? Please describe.**

I want to make my animation with timescale of -1 stop once it has looped once, but it seems like there is no such thing as stopping an animation when it is in reverse of the original animation in Three JS.

**Describe the solution you'd like**

Stop the animation once it has played the reverse animation already.

**Describe alternatives you've considered**

Well... I have lots of searches and it led me to a gist solution which does only work if my animation already was executed previously. But in my case, it should stop independently.

**Comment by Mugen87** [comment]
I'm afraid `timeScale` is not intended for this use case.

Its purpose is to modify the _advance in time_. And since the code assumes the local length of an animation is always between 0 and `duration`, a negative time scale can only be used to bring back the local time to `0`.

**Comment by asarra** [comment]
So, setting the start of the animation to the animation length, using timescale -1 and stopping it when it reaches 0 won't be a solution then. Did I understand it properly?

If that is the case, could one use a for loop that counts down manually, work as a workaround?

**Comment by Mugen87** [comment]
Maybe it's easier to demonstrate what I mean with an example: https://jsfiddle.net/azhgt7ce/

Do you mind applying your workaround oto the fiddle?

**Comment by Mugen87** [comment]
Try it with this approach: https://jsfiddle.net/7vxam4qr/1/

Relevant code:
```js
const action = mixer.clipAction( clip );
action.setLoop( THREE.LoopOnce );
action.time = clip.duration;
action.timeScale = - 1;
action.play();
```
