### ISSUE TITLE
Zbuffer rendering issues in webXR context

### ISSUE THREAD

**Issue by jtanant** [mrdoob/three.js#21298]
**Describe the bug**

I was having issues with rendering on my current webXR AR app. The 3d models are randomly rendered inside out (I thought that I was seing the backfaces instead of the front faces) but actually I have the exact same rendering when I put depthWrite or depthTest to false in the material, so it seems to be related to depth Z buffer.
I was able to reproduce on the official Three.js webXR AR paint example, which is what I describe here.
We have a similar but not identical issue on another device, where we can see Z buffer ghosting and also the same "inside out" Z buffer issue.

**To Reproduce**

Go to the official webXR AR paint example with a webXR AR compatible android device (I am using a Samsung S8) https://raw.githack.com/mrdoob/three.js/dev/examples/index.html#webxr_ar_paint

Go into AR, touch to draw a 3D paint trajectory. 
And randomly, the model is rendered apparently ignoring the depth (like with depthTest=false in the material). Sometimes it is back for a few second when you draw something else, or randomly. Sometimes you need to go out of AR mode and back in.

**Expected behavior**

The model should be rendered correctly, taking into account depth correctly.

**Screenshots**

Correct rendering of the 3d model, we see the outside of the model:
![Screenshot_20210217-173653_Chrome](https://user-images.githubusercontent.com/77788265/108237601-5efaa280-7148-11eb-92be-66850bb3ecb6.jpg)

Incorrect rendering (randomly happening), we see the inside because apparently Z is ignored:

![Screenshot_20210217-173621_Chrome](https://user-images.githubusercontent.com/77788265/108237701-746fcc80-7148-11eb-9fe9-c8b74dca5164.jpg)

**Platform:**

 - Device: Android device Samsung S8
 - OS: Android 8.0.0
 - Browser: Android Chrome 88
 - Three.js version: r125 and also tested on dev 126

Thanks!

**Comment by jtanant** [comment]
I am adding that in my app, when I add new objects to the Three js scene, it is back to normal for a few seconds for all the renderered objects, then we see the issue again.
We were suspecting a bad clearing of Z buffer, so I tested a manual renderer.clear(true, true, true) before rendering but issue is still here.

**Comment by jtanant** [comment]
I don't know if that helps, but on another device (I can't share the screen because the content is for now confidential) it really seems like the depth buffer and the color buffer are completely out of sync : we can see the camera feed + the objects renderer in color (with some rendering order issues because of depth issue) + a "mask" of the same objects (we can recognize the shapes) in "cutout" (camera feed visible on the object surface)... as if the depth buffer used for depth test was one from the frame before...

**Comment by Mugen87** [comment]
I can't reproduce on a Pixel 4a. 

It seems this is a device/browser specific issue. In this case, it's better to report the issue to the respective browser vendor.

I can't imagine that depth related issues  are produced by the way `three.js` uses the WebXR API.

**Comment by jtanant** [comment]
I understand. I will try to reproduce on another device. What is weird is that in our app, the issue is "fixed" for a few seconds when I change the scene (adding an object or setting an object to visible) then the issue is back again.
At some point I was suspecting some issues with Z-sorting, and also with the camera matrix that is overwritten in webXR context (negative scale?) but was not able to pinpoint the issue.
I am also suspecting the space anchors, because I noticed that my objects are not very well anchored since the last Chrome 88 + Three.js 125 update. I know, it sounds a bit crazy.
I will try to pinpoint.

**Comment by toji** [comment]
If it was an issue with the buffers not clearing I would expect that the geometry would either start leaving "trails" or begin clipping inappropriately, as if it were behind an invisible object. That doesn't seem to be the case here. (Additionally, the color/depth buffers supplied by WebXR will be cleared by the browser, so it should be nearly impossible to have cross-frame artifacts unless you are using an intermediate render target.)

The behavior you describe sounds more like the WebGL `cullFace()` mode is manually being set to something unexpected (probably `gl.FRONT`) and Three.js doesn't realized it needs to set it back. As an experiment, try calling `gl.cullFace(gl.BACK);` at the beginning of every frame and see if the effect stops. If so it would indicate that either Three is internally "leaking" the culling state somehow or you've got another piece of code that's changing that state without Three's knowledge.

**Comment by jtanant** [comment]
Thanks!
I tried this but it does not fix anything.
I am pretty sure this is related to Z buffer (test/write function) because I have the exact same "model distorsion" unchecking depth test or depth right in Three js editor material. Not all the faces are reversed as you would expect with inverting the face culling.
At least on my device (Samsung S8) (and my colleagues one a Pixel3 XL), it seems that at some point (after a few second), the Z buffer test or write is just disabled (or the Z buffer does not behave the same anymore). And this is fixed for a few seconds when I add elements to the Three.js scene. And then this is back again after a few seconds.
I tried to force this before my `renderer.render(scene, camera);`

```
gl.enable(gl.DEPTH_TEST);
gl.depthFunc(gl.LEQUAL);
```

But this does not change anything. Of course these states are overriden in the render()...
Maybe I can try to log further what is happening in the render(), especially the Z buffer related state changes?

And of course maybe this is in my code, but I just don't see it. It should be in the material anyway...

**Comment by jtanant** [comment]
I also had a look at the GL states before and after each object render (in onBeforeRender() and onAfterRender() callbacks), and nothing in particular, the depth states look good...
```
gl.getParameter(gl.DEPTH_FUNC);
gl.getParameter(gl.DEPTH_TEST);
```

**Comment by Mugen87** [comment]
Babylon.js also provide WebXR AR features. Do you mind testing if you can reproduce the issue on your device with Babylon.js, too?

https://doc.babylonjs.com/divingDeeper/webXR/webXRARFeatures

**Comment by mrdoob** [comment]
I think it's this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1167450

**Comment by jtanant** [comment]
Yes! Thanks @mrdoob 
I am confirming this is the same symptoms.
Do you think we could find a workaround waiting for the fix? Maybe it is possible because the Babylon demos work fine on these devices (from my tests), so it seems that they maybe do things a bit differently and the "side effect" is slightly different.

**Comment by Mugen87** [comment]
Since it's a pri 1 one bug, I don't think it makes sense to invest much time in a workaround. This needs to be fixed on browser level.

**Comment by br-matt** [comment]
> Babylon.js also provide WebXR AR features. Do you mind testing if you can reproduce the issue on your device with Babylon.js, too?
> 
> https://doc.babylonjs.com/divingDeeper/webXR/webXRARFeatures

Can confirm this is happening there as well as three.js. Been trying to find a cause for this for a while :C

**Comment by jtanant** [comment]
The workaround is now known (see linked Chromium issue).
On my side, I am doing this in my app in my main loop:
```
let gl = this.renderer.getContext();
gl.depthMask(false);
gl.clear(gl.DEPTH_BUFFER_BIT);
gl.depthMask(true); 
this.renderer.render(this.scene, this.camera);
```
And the issue is gone! yay! ;-D

**Comment by Mugen87** [comment]
I think this can be closed then.
