### ISSUE TITLE
docs: Add info about mipmaps in WebGLRenderTarget docs

### ISSUE THREAD

**Issue by gsimone** [mrdoob/three.js#21304]
WebGLRenderTargets sets generateMipmaps to false for the related texture, which differs from the default behaviour of the Texture object, where generateMipmaps is `true` by default:

https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderTarget.js#L35

https://github.com/mrdoob/three.js/blob/master/src/textures/Texture.js#L53

Should we add that to WebGLRenderTarget list of options or at least as a side note?

**Comment by Mugen87** [comment]
> Should we add that to WebGLRenderTarget list of options

Yes, that's a good idea. `generateMipmaps` should not missing in that list. Do you want to make a PR?

**Comment by gsimone** [comment]
Sure 🙏
