### ISSUE TITLE
Feature Request: OnBeforeRender on Material

### ISSUE THREAD

**Issue by DavidPeicho** [mrdoob/three.js#21305]
**Is your feature request related to a problem? Please describe.**

Let's say I have a custom material that is shared by two meshes. This material uses the inverse transform of the mesh. In this case, I have no way to send the inverse transform because it's dependent from the actual bound mesh.

When creating an app with Three.js, it's not really an issue because we control the flow of data. However, when wrapping Three.js in another library, it makes it somewhat difficult to share a ShaderMaterial whose parameters aren't independent from the camera / mesh drawn.

**Describe the solution you'd like**

On the top of my mind:

* Create a `onBeforeRender` callback on the material, that would be in charge of updating per-object uniforms. This is similar
  to the `onBeforeCompile` callback, but called each time something is rendered with this material.

**Describe alternatives you've considered**

* Use `onBeforeRender` on each meshes. Annoying because all meshes using this material must be updated and a user would need to attach the callback himself
* Clone the material for each mesh

**Additional context**

This is highly related to the issue #16922. I think the problem is similar.

**Comment by mrdoob** [comment]
> * Use `onBeforeRender` on each meshes. Annoying because all meshes using this material must be updated and a user would need to attach the callback himself

I was going to suggest that...

This whole `onBefore*`, `onAfter*` is ugly. Have you tested `NodeMaterial`?

**Comment by DavidPeicho** [comment]
I haven't because I will most likely just add my entire GLSL in one node 😄 Also Right now I like how my shaders are clearly separated and I just use includes. Maybe I should take a closer look at `NodeMaterial`, any feature there that could help me achieve that on a material level?

I wish I could just do it on the meshes but that's not that easy, because I just don't know in advanced where my material will be attached.

It's fragile I agree, but right now what's happening is that there is a custom path basically for the default materials. Ideally I think it would be nice to be able to do exactly the same thing with any custom material, including having a way to modify transforms / camera.

**Comment by mrdoob** [comment]
@sunag how do you think this could be done with `NodeMaterial`?

**Comment by sunag** [comment]
> @sunag how do you think this could be done with NodeMaterial?

Yes. This already is possible in the new `NodeMaterial` system.
https://github.com/mrdoob/three.js/blob/ea11ddad1e92e2cfdb1b6a03ba30225fe6fdef2a/examples/jsm/renderers/nodes/accessors/ModelNode.js#L17

You can update a `shared uniform` for each `render object`.
https://github.com/mrdoob/three.js/blob/ea11ddad1e92e2cfdb1b6a03ba30225fe6fdef2a/examples/jsm/renderers/nodes/accessors/ModelNode.js#L39-L55

Is possible `update per frame` too with objects like `camera`
https://github.com/mrdoob/three.js/blob/ea11ddad1e92e2cfdb1b6a03ba30225fe6fdef2a/examples/jsm/renderers/nodes/accessors/CameraNode.js#L16

**Comment by sunag** [comment]
I can implement a solution for `WebGL` too after this PR ( https://github.com/mrdoob/three.js/pull/21117 )... I am currently implementing a `light system` for selective lights or global using `NodeMaterial`.

**Comment by DavidPeicho** [comment]
I had a look a bit at the Node system today. I still need to connect myself the mesh to the update though no? I don't see how that would work automatically.

Where is the `frame.object` attribute field?

**Comment by sunag** [comment]
https://raw.githack.com/sunag/three.js/nodematerial-shared-uniforms/examples/webgpu_instance_uniform.html 

Source: https://github.com/sunag/three.js/blob/8f9cbfa9c15d45a5ce8d3edba8cebc246c039592/examples/webgpu_instance_uniform.html

I made a example, the color is updated per `mesh.color` in render object moment.
But it seems there is a problem... `WebGPURenderer` still does not support material instance? @Mugen87

**Comment by Mugen87** [comment]
> WebGPURenderer still does not support material instance?

What do you mean with "material instance"?

**Comment by sunag** [comment]
> What do you mean with "material instance"?

A single material for multiples meshes.

**Comment by sunag** [comment]
If replace `materialTemp` to `material` in `addMesh()` only a mesh is renderer at a time.
https://github.com/sunag/three.js/blob/8f9cbfa9c15d45a5ce8d3edba8cebc246c039592/examples/webgpu_instance_uniform.html#L104-L109

**Comment by Mugen87** [comment]
Okay, after investigating this issue a refactoring of how bindings are managed is required. Right now, the binding and the actual data  are handled in a single object. E.g.

https://github.com/mrdoob/three.js/blob/cb99e7e08cc97cb7a22f17e32cc7a22082022d67/examples/jsm/renderers/webgpu/WebGPUUniformsGroup.js#L22-L23

If a material is shared among multiple 3D objects, there is only one instance of bindings objects and thus only one data storage. This is not a problem for textures (because textures are defined on material level) however model related data like the MVP matrix can't be processed this way. They have to be managed per 3D object and the UBO needs to be updated per object with the correct data.

I need some time to think about a possible solution for this...

**Comment by DavidPeicho** [comment]
@sunag let me know if you need any help for the WebGL version (or even WebGPU).

**Comment by sunag** [comment]
@Mugen87 I found the problem, is related with the implementation of `NodeMaterial`... I will create um PR to fix this.

**Comment by Mugen87** [comment]
I'm curious about your PR 🤓. This can also be fixed having multiple `WebGPUUniformsGroup` objects share a single `bufferGPU`. The render and material system just have to inject an existing UBO (`bufferGPU`) that is shared across multiple 3D objects. It is not required that such a UBO needs to exist per 3D object. If multiple 3D objects share a program, they can also share all WebGPU resources.

**Comment by sunag** [comment]
> They have to be managed per 3D object and the UBO needs to be updated per object with the correct data.

I mean in case of just update the uniforms with the new `mesh` and `draw` again with the same `material` and `uniforms` but objects differents... This approach work with `WebGL` but with `WebGPU` I never tested.

**Comment by Mugen87** [comment]
Ah okay, I only focus on WebGPU in this topic^^.

**Comment by sunag** [comment]
> I'm curious about your PR 

I did not do anything particular... I just made `WebGPUNodes` work via `.get( objects )` instead of `.get( material )`. A `NodeBuilder` for each `object`.

**Comment by Mugen87** [comment]
If this works, it's a good start! Fell free to file the PR 👍 

I'd like to find out if it is possible to further optimize the renderer and material system by only having different bindings if required. However, this will take a while and some experimenting.

**Comment by DavidPeicho** [comment]
Any news on the WebGL side? I am available few hours a week to help on that 😄

**Comment by Mugen87** [comment]
@DavidPeicho In context of WebGL, we have to solve #21117 first.

**Comment by DavidPeicho** [comment]
Any news here now that #21117 is solved?
If you need any help to go forward with that, let me know what you want me to work on and I can give some of my time for that!

**Comment by WestLangley** [comment]
@DavidPeicho 

>This material uses the inverse transform of the mesh

If the transform is unscaled, this may help you avoid passing the inverse transform to the shader:
https://en.wikibooks.org/wiki/GLSL_Programming/Applying_Matrix_Transformations

**Comment by DavidPeicho** [comment]
@WestLangley  thanks for the link but it was just one example out of several. It can happen that some data comes from the mesh and isn't easily accessible.

**Comment by Mugen87** [comment]
The idea is to apply the pattern from the following WebGPU example to `WebGLRenderer`.

https://threejs.org/examples/webgpu_instance_uniform

However, this requires a deeper integration of the node material into `WebGLRenderer` so it's possible to process to trigger the node updates per frame. #21117 was a first step but `WebGLRenderer` needs to call a similar method like below (which is currently used by `WebGPURenderer`) so it can utilize more features of the new node system:

https://github.com/mrdoob/three.js/blob/8837fac2a910f8ed18d956e53963e197db6c3074/examples/jsm/renderers/webgpu/nodes/WebGPUNodes.js#L44-L61

**Comment by Mugen87** [comment]
`WebGPURenderer` uses a node system by default. However, we can not include the entire node system in the main build of `three.js` so we have to find another way so `WebGLRenderer` can use the new node system.

Right now, it's required that the app includes a certain file ([WebGLNodes](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/renderers/webgl/nodes/WebGLNodes.js). However, I'm thinking about a different approach based on dependency injection. Meaning if users want to use the node path of `WebGLRenderer`, they would have to call a new method that injects node classes for further usage.

**Comment by DavidPeicho** [comment]
Thanks for the info. That sounds good. Something like `renderer.setNodeBuilder()` would be great.

I recently tried to start new shaders using the node system, but I have to admit it's a bit difficult and time consuming to use in WebGL in its current state.

**Comment by sunag** [comment]
@DavidPeicho Look like we have a WebGL version for that :) https://github.com/mrdoob/three.js/pull/22504

**Comment by DavidPeicho** [comment]
That's amazing news, thanks! I guess now I will have to convert my custom materials to the node system

**Comment by DavidPeicho** [comment]
`Material.onBeforeRender` is actually implemented now. Howerver, it's missing some doc. Will try to make a PR.

**Comment by Mugen87** [comment]
Unfortunately, you can't use `Material.onBeforeRender()` to update per-object uniforms.

https://jsfiddle.net/03xm49dp/

Material.onBeforeRender()` was only introduced to make the new node material system work with `WebGLRenderer`. At some point, we should maybe stop this support and refer user to `WebGPURenderer` with its WebGL backend instead. And then remove `Material.onBeforeRender()` since I don't think it adds any additional value (and right now produces only confusing).

**Comment by Mugen87** [comment]
Closing. With the removal of the node material integration in `WebGLRenderer`, the related material callbacks `onBuild()` and `onBeforeRender()` have been removed as well (see #28702).

Please use `WebGPURenderer` if you need per object uniforms for materials.
