### ISSUE TITLE
Font Loader accept JSON object

### ISSUE THREAD

**Issue by kylegoines** [mrdoob/three.js#21312]
When loading typeface.json files with import, some bundlers will produce a fully formed JSON object rather than a path. I think allowing the FontLoader, and potentially any loader to accept an JSON Object (im not as versed with the other loaders so i cant speak to them)

The current implementation of FontLoader.ts `load` method will trigger an error of 
```
Uncaught SyntaxError: Unexpected token > in JSON at position 0
    at JSON.parse (<anonymous>)
```
when passed a direct JSON object

**Describe the solution you'd like**
Looking at the FontLoader.ts file it looks to try to parse the path, if there was a conditional to try to just use the json Object would be helpful :)'

**Describe alternatives you've considered**
Other options are to obviously config your bundler to generate paths. But i think this update would allow more flexibility with modern module workflows.

**Comment by gkjohnson** [comment]
Does [FontLoader.parse](https://threejs.org/docs/#api/en/loaders/FontLoader.parse) not do what you're looking for?

**Comment by kylegoines** [comment]
@gkjohnson it is exactly what im looking for, thank you for such a quick response
sorry!
