### ISSUE TITLE
TextureEncodingTest.gltf is different from expected result

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#21318]
**Describe the bug**

I tried Khronos' new test model [TextureEncodingTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/encoding/2.0/TextureEncodingTest) with Three.js.
However, it seems to be different from the expected result.

**To Reproduce**

[Three.js r125 + TextureEncodingTest.gltf result:](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=TextureEncodingTest&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/108600778-64701b00-73dc-11eb-9c93-b10a17b18338.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/1833979/108509779-06bad080-7301-11eb-8e7c-3e93a524f679.png)

**Platform:**

- Device: MacBook Air
- OS: Windows 10 (BootCamp)
- Browser: Chrome 88.0.4324.182
- Three.js version: r125

**Comment by donmccurdy** [comment]
For our reference, more details on this test here: https://github.com/KhronosGroup/glTF-Sample-Models/pull/296

**Comment by takahirox** [comment]
It seems custom gamma and icc profiles embedded in image file should be ignored in glTF.

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#images

> Any colorspace information (such as ICC profiles, intents, etc) from PNG or JPEG containers must be ignored. Effective transfer function is defined by a glTF object that refers to the image.

https://github.com/KhronosGroup/glTF-Sample-Models/tree/encoding/2.0/TextureEncodingTest#description

> Additionally, this asset tests that gamma values and/or ICC profiles embedded with image files are ignored as the glTF spec requires.

So, we need to turn off color space conversion for glTF. I added `this.textureLoader.setOptions( { colorSpaceConversion: 'none' } );` after `this.textureLoader = new ImageBitmapLoader( this.options.manager )` in `GLTFLoader` and the result looks correct.

![image](https://user-images.githubusercontent.com/7637832/108617065-236e0b80-73c8-11eb-9b06-e4a34d680e03.png)

For platforms where `ImageBitmap` is not available `GLTFLoader` uses regular `TextureLoader` but currently `WebGLRenderer` doesn't manage `gl.UNPACK_COLORSPACE_CONVERSION_WEBGL` then we may need to add a new property for color space conversion to `Texture` like `Texture.colorSpaceConversion (BROWSER_DEFAULT_WEBGL or None).

**Comment by takahirox** [comment]
I made two PRs #21323 and #21324 which resolve this issue.
