### ISSUE TITLE
CurveModifier.js is missing in js 

### ISSUE THREAD

**Issue by rahulscp** [mrdoob/three.js#21333]
i am using curve modifer in my project. i am not using the jsm versions i am following the normal javascript files because of some other dependencies in my library.

is there any possibility to provide the js version of CurveModifier?

**Comment by Mugen87** [comment]
> is there any possibility to provide the js version of CurveModifier?

For newly created components, `examples/js` files are not provided anymore. Only modules. You have to wait for https://github.com/mrdoob/three.js/pull/20527.
