### ISSUE TITLE
Broken URL for Three.js Example Code Source

### ISSUE THREAD

**Issue by ybinstock** [mrdoob/three.js#21343]
If you go to the three.js example for [multi-variant gltfs](https://rawcdn.githack.com/cx20/three.js/57432daae6a714b4752fa56f7b2575994d2ef3c6/examples/index.html?q=gltf#webgl_loader_gltf_variant
) and then go to the bottom right to click to see the source [code](https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_gltf_variant.html), you get a 404 error.

**Comment by Mugen87** [comment]
Your URL is not from the original repository. The source link works fine with this example:

https://threejs.org/examples/#webgl_loader_gltf_variants

**Comment by DefinitelyMaybe** [comment]
Was this phishing the devs?

Who links to githack calling it a three.js example?
