### ISSUE TITLE
Change the radius of a TubeGeometry along its path

### ISSUE THREAD

**Issue by Aqro** [mrdoob/three.js#21391]
By passing an array of radius instead of a simple float, we could have different thicknesses along the path.

Even better:
How about having a method that loops through each tubular segment to pass attributes. This way, it would give the possibility to change the thickness dynamically in a shader?

**Comment by WestLangley** [comment]
See #13971.

**Comment by Aqro** [comment]
I was surprised not to see this suggestion in the issues, that's because it was already in the PR section 😁 Thanks @WestLangley

**Comment by WestLangley** [comment]
It used to be supported, and was referred to as `taper`.  #5679
