### ISSUE TITLE
Ocean Example - Alpha Not Working

### ISSUE THREAD

**Issue by habanoz** [mrdoob/three.js#21392]
In the ocean example, the alpha slider does not affect the scene. 

https://threejs.org/examples/#webgl_shaders_ocean

In an older version, changing the alpha value has visible effects. 

https://edumet.cat/areatac/three.js/examples/webgl_shaders_ocean.html

**Comment by WestLangley** [comment]
See https://github.com/mrdoob/three.js/pull/18932#issuecomment-607116767.

**Comment by habanoz** [comment]
@WestLangley 

Thanks for the quick answer. 

It would be awesome if someone adds the line to the example. I tried to send a PR but not authorized to do so. 

Closing.

**Comment by Mugen87** [comment]
How about removing the `alpha` option from the GUI? If a water implementation has no refractive component, it feels more consistent to consider it as an opaque object. `THREE.Reflector` is opaque, too.

**Comment by habanoz** [comment]
I would argue against this idea. Examples are there to showcase what is available. In this particular case, water is a transparent substance and it is quite probable that someone needs to display the transparency. If you argue ocean is not transparent I would say it is see through near costs and ocean has different depth levels where deeper sections are darker.

**Comment by Mugen87** [comment]
As I said before, `Water` has no refractive component so any kind of transparency used with this implementation looks odd.
