### ISSUE TITLE
docs: Broken Link( Using the viewport meta tag )

### ISSUE THREAD

**Issue by na2shell** [mrdoob/three.js#21405]
**Describe the bug**

I found Broken Link in FAQ document.
That is "MDN: Using the viewport meta tag".

**To Reproduce**

Change URL from "now" to "expect".

now: https://developer.mozilla.org/en/Mobile/Viewport_meta_tag
expect: https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r???]

**Comment by Mugen87** [comment]
Thanks for reporting. Fixed on `dev`.
