### ISSUE TITLE
Uncaught TypeError: class constructors must be invoked with 'new'

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#21419]
The animations using older loaders (SEA3D for example) don't work in the current beta.
They worked just fine in r126

**Comment by Mugen87** [comment]
Can you please share the line where the runtime error is thrown?

**Comment by RemusMar** [comment]
Hi Michael,

r126: https://necromanthus.com/Test/html5/Lara.html 

r127: https://necromanthus.com/Test/html5/Lara_127b.html
The console error is related to AnimationClip

**Comment by RemusMar** [comment]
```
THREE.SEA3D.AnimationClip = function ( name, duration, tracks, repeat ) {

	THREE.AnimationClip.call( this, name, duration, tracks );

	this.repeat = repeat !== undefined ? repeat : true;

};
```

THREE.AnimationClip.call fails in r127

**Comment by Mugen87** [comment]
Thanks for sharing the code! The problem is that `AnimationClip` is now a ES6 class which means it is now possible anymore to derive a custom class like shown above. The `SEA3D` code also has to use the class syntax.

**Comment by RemusMar** [comment]
The following change did the trick:

```
THREE.SEA3D.AnimationClip = function ( name, duration, tracks, repeat ) {

	var aniclp = new THREE.AnimationClip( name, duration, tracks);
	aniclp.repeat = repeat !== undefined ? repeat : true;
	return aniclp;

};
```

Now both r126 and r127 samples work.

**Comment by RemusMar** [comment]
@Mugen87 
Michael,
This function worked just fine in the previous r127.
How do we make it work in the current r128beta ?

```
THREE.SEA3D.SkinnedMesh = function ( geometry, material ) {

	THREE.SkinnedMesh.call( this, geometry, material );

	this.bind( new THREE.Skeleton( this.initBones() ), this.matrixWorld );

	this.updateAnimations( geometry.animations, new THREE.AnimationMixer( this ) );

};

THREE.SEA3D.SkinnedMesh.prototype = Object.assign( Object.create( THREE.SkinnedMesh.prototype ), THREE.SEA3D.Mesh.prototype, THREE.SEA3D.Animator.prototype, {

	constructor: THREE.SEA3D.SkinnedMesh,

	initBones: function () {

		var bones = [], bone, gbone;
		var i, il;

		if ( this.geometry && this.geometry.bones !== undefined ) {

			// first, create array of 'Bone' objects from geometry data

			for ( i = 0, il = this.geometry.bones.length; i < il; i ++ ) {

				gbone = this.geometry.bones[ i ];

				// create new 'Bone' object

				bone = new THREE.Bone();
				bones.push( bone );

				// apply values

				bone.name = gbone.name;
				bone.position.fromArray( gbone.pos );
				bone.quaternion.fromArray( gbone.rotq );
				if ( gbone.scl !== undefined ) bone.scale.fromArray( gbone.scl );

			}

			// second, create bone hierarchy

			for ( i = 0, il = this.geometry.bones.length; i < il; i ++ ) {

				gbone = this.geometry.bones[ i ];

				if ( ( gbone.parent !== - 1 ) && ( gbone.parent !== null ) && ( bones[ gbone.parent ] !== undefined ) ) {

					// subsequent bones in the hierarchy

					bones[ gbone.parent ].add( bones[ i ] );

				} else {

					// topmost bone, immediate child of the skinned mesh

					this.add( bones[ i ] );

				}

			}

		}

		// now the bones are part of the scene graph and children of the skinned mesh.
		// let's update the corresponding matrices

		this.updateMatrixWorld( true );

		return bones;

	},

	boneByName: function ( name ) {

		var bones = this.skeleton.bones;

		for ( var i = 0, bl = bones.length; i < bl; i ++ ) {

			if ( name == bones[ i ].name )
				return bones[ i ];

		}

	},

	copy: function ( source ) {

		THREE.SkinnedMesh.prototype.copy.call( this, source );

		this.attribs = source.attribs;
		this.scripts = source.scripts;

		if ( source.animator ) this.animator = source.animator.clone( this );

		return this;

	}

} );
```

**Comment by Mugen87** [comment]
You have to convert this code to class syntax since it is not possible to derive from a ES6 class via:
```js
THREE.SkinnedMesh.call( this, geometry, material );
```
It seems however this pattern is problematic though:
```js
Object.create( THREE.SkinnedMesh.prototype ), THREE.SEA3D.Mesh.prototype, THREE.SEA3D.Animator.prototype, {
```
Not sure how to transform this to pure class syntax. 

If necessary, you have to transpile `three.js` to ES5. You can then use your code as before.

**Comment by RemusMar** [comment]
> Not sure how to transform this to pure class syntax.

I had the same problem.

Anyway, I tried the above replacement for CALL and I got two errors:
- initBones() has been removed
- this.matrixWorld is undefined

**Comment by marcofugaro** [comment]
> @marcofugaro Do you have any ideas how this mixin style could look with ES6?

ES6 classes have no native support for multiple inheritance, but you can put any expression after the `extends` keyword, so it would look something like this

```js
class SkinnedMesh extends combine(SEA3D.Mesh, SEA3D.Animator) {
```

[Reference article for full example](https://www.codeproject.com/Articles/1189466/JavaScript-ES-Multiple-Inheritance-Class)

**Comment by RemusMar** [comment]
> ES6 classes have no native support for multiple inheritance, but you can put any expression after the extends keyword, so you have to write your own class combiner function.

Can you please show us how the beginning part will look like?

```
THREE.SEA3D.SkinnedMesh = function ( geometry, material ) {

	THREE.SkinnedMesh.call( this, geometry, material );

	this.bind( new THREE.Skeleton( this.initBones() ), this.matrixWorld );

	this.updateAnimations( geometry.animations, new THREE.AnimationMixer( this ) );

};

THREE.SEA3D.SkinnedMesh.prototype = Object.assign( Object.create( THREE.SkinnedMesh.prototype ), THREE.SEA3D.Mesh.prototype, THREE.SEA3D.Animator.prototype, {

	constructor: THREE.SEA3D.SkinnedMesh,

	initBones: function () {

		var bones = [], bone, gbone;
		var i, il;
```

**Comment by marcofugaro** [comment]
With multiple inheritance it would looks something like this

```js
// Function for creating multi inheritance.
function combine(..._bases) {
  class classes {
    
    // The base classes
    get base() { return _bases; }
    
    constructor(..._args) {
      var index = 0;

      for (let b of this.base) {
        let obj = Array.isArray(_args[index++]) ? new b(..._args[index++]) : new b(_args[index++]);
        copy(this, obj);
      }
    }
  
  }

  // Copy over properties and methods
  for (let base of _bases) {
    copy(classes, base);
    copy(classes.prototype, base.prototype);
  }

  return classes;
}

// Copies the properties from one class to another
function copy(_target, _source) {
  for (let key of Reflect.ownKeys(_source)) {
    if (key !== "constructor" && key !== "prototype" && key !== "name") {
      let desc = Object.getOwnPropertyDescriptor(_source, key);
      Object.defineProperty(_target, key, desc);
    }
  }
}


THREE.SEA3D.SkinnedMesh = class SkinnedMesh extends combine(THREE.SkinnedMesh, THREE.SEA3D.Mesh, THREE.SEA3D.Animator) {
   

  constructor ( geometry, material ) {

    super([[geometry, material]])

    this.bind( new THREE.Skeleton( this.initBones() ), this.matrixWorld );

    this.updateAnimations( geometry.animations, new THREE.AnimationMixer( this ) );
  }

  initBones() {

    var bones = [], bone, gbone;
    var i, il;
```

**Comment by RemusMar** [comment]
@marcofugaro 

Marco,
Any idea why do I get this console error?

Uncaught TypeError: _args[(tonumeric index)] is undefined

**Comment by marcofugaro** [comment]
I tested it and it seemed to work, pay attention to the `super` call, it's an array of array, since there is the possibility to pass arguments to the other extended classes.

```js
super([[geometry, material]])
```

**Comment by RemusMar** [comment]
Marco,

Now I get another error:
Uncaught TypeError: can't redefine non-configurable property "id"
in
Object.defineProperty(_target, key, desc);

**Comment by RemusMar** [comment]
@marcofugaro 

After getting rid of all those non-configurable properties with this line:
`    if (key !== "constructor" && key !== "prototype" && key !== "name" && key !== "id" && key !== "modelViewMatrix" && key !== "normalMatrix") {`

I got an old console error:
Uncaught TypeError: this.updateMatrix is not a function

**Comment by marcofugaro** [comment]
@RemusMar I think it's an issue of nested prototypes, because SkinnedMesh is extending Mesh which is extending Object3D, you'd have to go a level deeper here:

```js
  // Copy over properties and methods
  for (let base of _bases) {
    copy(classes, base);
    copy(classes.prototype, base.prototype);
  }
```

You could use a [while loop like in this answer](https://stackoverflow.com/a/40575545) to go up the parents tree.

**Comment by RemusMar** [comment]
I think we could use some help from @sunag here.

**Comment by RemusMar** [comment]
> If necessary, you have to transpile three.js to ES5. You can then use your code as before.

@marcofugaro  @Mugen87 @mrdoob 
Just tested the current beta converted to ES5 and the old SEA3D runs perfect.
Until we convert SEA3D to ES6, this is the best solution so far.
cheers

**Comment by Mugen87** [comment]
> Until we convert SEA3D to ES6, this is the best solution so far.

Better to tackle this issue at the respective repo.
