### ISSUE TITLE
Incorrect polymorphism

### ISSUE THREAD

**Issue by The-Podsiadly** [mrdoob/three.js#21424]
**Describe the bug**

While creating a morphing blob, the curvature is straight, triangle based rather than being soft and round. I used v0.126.1 and had to downgrade to 120.1 to get the rounded effect.

**To Reproduce**

1. Upgrade to a version **121.x** or higher

***Code***

The code is too long, therefore I liked it below in ***Live example***.

***Live example***

* [Blob Experiment--Fixed](https://codepen.io/the-podsiadly/pen/MWbqGzx)
* [Blob Experiment--Broken](https://codepen.io/the-podsiadly/pen/zYoJjyO)

**Expected behavior**

The blob should have nice, curved edges rather than being triangulated on such a small **n**.

**Platform:**

 - Device: Desktop
 - OS: Windows]
 - Browser: Chrome
 - Three.js version: r121+

**Comment by WestLangley** [comment]
See #20255 and https://github.com/mrdoob/three.js/wiki/Migration-Guide#r120--r121.
