### ISSUE TITLE
BufferGeometry.applyMatrix4 throws for normals from InterleavedBufferAttributes

### ISSUE THREAD

**Issue by devnev** [mrdoob/three.js#21433]
**Describe the bug**

Calling `applyMatrix4` on a `BufferGeometry` may throw a `TypeError` if the attributes are from an `InterleavedBufferAttribute` object, as `InterleavedBufferAttribute` doesn't have `applyNormalMatrix` or `transformDirection`.

**To Reproduce**

3. See error

***Code***

```js
// code goes here
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hyok6tvj/)
* [jsfiddle-dev](https://jsfiddle.net/c5m1kazu/)

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Chrome]
 - Three.js version: [dev, r121]

**Comment by Mugen87** [comment]
Similar to `applyMatrix4()` both methods can be copied over. Do you want to make a PR with the fix?

**Comment by devnev** [comment]
@Mugen87 Happy to!
