### ISSUE TITLE
Envmap too shiny on android

### ISSUE THREAD

**Issue by SBRK** [mrdoob/three.js#21438]
**Describe the bug**
Models loaded on desktop and mobile (android) don't have the same look. On android, everything is shiny

**To Reproduce**
I have found this Reddit post, with a good example from 11 months ago that still displays badly on Android https://www.reddit.com/r/threejs/comments/fsms6d/gltf_roughness_texture_inverted_on_mobile/

**Expected behavior**
Both desktop and android should display the same

**Example**
Model from the reddit post above:
https://welvt43di5csz8w33jig9a-on.drv.tw/PLANE2/

**Screenshots**
![image](https://user-images.githubusercontent.com/119354/110612267-510cd000-8190-11eb-869d-c1ba5cf1b5fa.png)

**Platform:**
 - Device: Google Pixel 4
 - OS: Android
 - Browser: Chrome
 - Three.js version: r124

**Comment by mrdoob** [comment]
This was fixed in r126: https://github.com/mrdoob/three.js/pull/21205

**Comment by SBRK** [comment]
Oh, really nice! As a coincidence, I updated to r126 yesterday, gonna give it a try.
