### ISSUE TITLE
Octree.fromGraphNode  cannot  calculate scaled position when the mesh was in a group

### ISSUE THREAD

**Issue by hazenoeasy** [mrdoob/three.js#21439]
**Describe the bug**
I added a group into the scence.
The group contained  MESH1,MESH2,MESH3.

After I set the group scale  like this, I implyed  the collision dection by ...
```
 const model = gltf.scene;
      model.scale.set(SCALE * model.scale.x, SCALE * model.scale.y, SCALE * model.scale.z);
      const result = this.Octree.fromGraphNode(model.children[2]);
      this.scene.add(model);
```

However, the dection was not compatible with MESH1.

MESH1 was bigger, but the collision dection area was not.

After debugging, I found out that the  WorldMtrix was not updated

cuz in Octree.js  updateWorldMatrix function params were empty.
<img width="1096" alt="截屏2021-03-10 下午8 17 57" src="https://user-images.githubusercontent.com/39185940/110629445-2138e900-81df-11eb-872e-b09417f6697e.png">
<img width="1103" alt="截屏2021-03-10 下午8 17 23" src="https://user-images.githubusercontent.com/39185940/110629469-26963380-81df-11eb-94d8-6effe1d5d918.png">

I apologize for my poor English...
If you are confused by my description, please contact me...

**Comment by Hoodgail** [comment]
YES!!!! i'm getting the same issue

**Comment by Hoodgail** [comment]
```js
const model = gltf.scene;
      model.scale.set(SCALE * model.scale.x, SCALE * model.scale.y, SCALE * model.scale.z);
      const result = this.Octree.fromGraphNode(model.children[2]);
      this.scene.add(model);
``` wait why would it get the scene's scale if you're intersecting an other object even if its a child of the object being scaled
