### ISSUE TITLE
webgl2_materials_texture3d not working on Samsung S9

### ISSUE THREAD

**Issue by kofifus** [mrdoob/three.js#21444]
The example here

https://threejs.org/examples/webgl2_materials_texture3d.html

Does not work on my Samsung S9 - no image appears

(many others examples do work)

Thanks!

**Comment by Mugen87** [comment]
Please provide more information about your issue:

- What do you mean with "does not work"? Please describe in more detail what happens on your device.
- What browsers have issue with `webgl2_materials_texture3d`? Please test at least with Chrome and Firefox.
- Please check if the are warnings in the browser console.
- Can you please try to update to the latest Android version?

**Comment by Mugen87** [comment]
Closing until the OP provides more feedback.

**Comment by kofifus** [comment]
Hi sorry for the delay

>    What do you mean with "does not work"? Please describe in more detail what happens on your device.

The image doesn't show, the screen looks like this:

![image](https://user-images.githubusercontent.com/3926071/111061019-3c646b00-84f5-11eb-9eb9-ef35313b0b4b.png)

>    What browsers have issue with webgl2_materials_texture3d? Please test at least with Chrome and Firefox.

Same result on both Chrome and Firefox

>    Please check if the are warnings in the browser console.

Please tell how to access those ?
 
>    Can you please try to update to the latest Android version?

updated (Android 10)

Thanks!

**Comment by Mugen87** [comment]
> Please tell how to access those ?

https://developers.google.com/web/tools/chrome-devtools/remote-debugging

**Comment by kofifus** [comment]
The console only shows a few warnings:

![image](https://user-images.githubusercontent.com/3926071/111228559-873acb80-8638-11eb-839e-335ca9425ad4.png)

Can the issue please be reopened ?

**Comment by Mugen87** [comment]
The example works without issues on my Pixel4a (Android 11). And there is no indication that the engine does not use 3D textures in the wrong way.

I suggest you use the [WebBGL conformance tests](https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html) to verify which test from the `all/deqp/functional/gles3/texturespecification` section fail on your device.

**Comment by kofifus** [comment]
Thanks, all 90 tests in `all/deqp/functional/gles3/texturespecification` have passed successfully.

**Comment by mrdoob** [comment]
@kofifus Can you try with Firefox?
https://play.google.com/store/apps/details?id=org.mozilla.firefox

**Comment by kofifus** [comment]
@mrdoob same result (see pic above) for firefox thanks

**Comment by mrdoob** [comment]
This is probably a device/driver issue and there isn't much we can do about it.
Also, I currently do not have any Samsung phones at hand. Maybe someone in the community can try to debug this?

**Comment by Mugen87** [comment]
I've tested the example today on a Samsung Galaxy A70 with Android 10 and latest Chrome. It works as expected.

**Comment by kofifus** [comment]
I can also confirm it works on the Galaxy S20, I hope someone else can check with the S9 ?

**Comment by Mugen87** [comment]
@kofifus I suggest you report this issue here: https://bugs.chromium.org/p/chromium/issues/list

If the Chromium team can reproduce the issue, they can properly redirect the issue to Samsung or Qualcomm.

I'm sure we can't fix this at engine level.

**Comment by kofifus** [comment]
ok got it thanks for the help.
