### ISSUE TITLE
MeshLambertMaterial do not receive shadow from a SpotLight

### ISSUE THREAD

**Issue by gbaptista** [mrdoob/three.js#21457]
**Describe the bug**

A `Mesh` with a `MeshLambertMaterial` does not receive shadows from a `SpotLight`. If I change the light to a `DirectionalLight` or change the `Mesh` to a `MeshPhongMaterial`, the shadow appears as I believe that is the expected.

**To Reproduce**

1. Go to https://jsfiddle.net/catsvo8q/
2. Check that the shadow does not appear in the plane.

Two approaches to see the shadow:

3. Change line `55` to use a `MeshPhongMaterial` instead of a `MeshLambertMaterial`, and you can see the shadow.

Or:

3. Change the line `62` to a `DirectionalLight` (`const focusLight = new THREE.DirectionalLight(0xFFFFFF, 1);`) instead of a `SpotLight`,  and you can see the shadow.

***Code***

```js
const renderer = new THREE.WebGLRenderer({antialias: true});
renderer.shadowMap.enabled = true;

const cube = new THREE.Mesh(
  new THREE.BoxBufferGeometry(),
  new THREE.MeshLambertMaterial({color: 0x4287f5})
);
cube.castShadow = true;

const floor = new THREE.Mesh(
  new THREE.PlaneBufferGeometry(10, 10),
  new THREE.MeshLambertMaterial({
    color: 0xFFFFFF,
    side: THREE.DoubleSide
  })
);
floor.rotation.x = THREE.MathUtils.degToRad(-90);
floor.receiveShadow = true;

const focusLight = new THREE.SpotLight(0xFFFFFF, 20, 10, 0.4);
focusLight.position.y = 4;
focusLight.castShadow = true;
focusLight.target = cube;
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/catsvo8q/)

**Expected behavior**

A `Mesh` with a `MeshLambertMaterial` should display shadows from a `SpotLight`.

**Screenshots**

MeshLambertMaterial:
![floor-with-lambert](https://user-images.githubusercontent.com/29520/111012584-8a993300-836a-11eb-8440-c8fa8c0f3cf7.png)

MeshPhongMaterial:
![floor-with-phong](https://user-images.githubusercontent.com/29520/111012607-98e74f00-836a-11eb-8c64-0af25c637204.png)

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome
 - Three.js version: [dev, r0.126.1] (I checked the dev version directly from GitHub, and it has the same behavior.)

**Comment by WestLangley** [comment]
See [this SO answer](https://stackoverflow.com/questions/15801971/three-js-what-is-the-exact-difference-between-lambert-and-phong/15809154#15809154).

In the case of `MeshLambertMaterial`, the illumination calculation in only being performed at the four corners of the plane.

Tessellate your geometry and you will be able to see what is happening:
```js
new THREE.PlaneBufferGeometry( 10, 10, 25, 25 )
```
