### ISSUE TITLE
Sprite material with ".sizeAttenuation" ON does not take fov into account

### ISSUE THREAD

**Issue by optimus007** [mrdoob/three.js#21456]
[.sizeAttenuation](https://threejs.org/docs/#api/en/materials/SpriteMaterial.sizeAttenuation) property works great at any zoom level but when perspective camera fov is changed ..the size is not maintained.

fiddle https://jsfiddle.net/orion_prime/exfmp6nw/92/

**Comment by Mugen87** [comment]
Duplicate of #12150.
