### ISSUE TITLE
Lit GLB material with vertex colors applies light incorrectly

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#21467]
**Describe the bug**

When importing a GLB file that has vertex colors, ambient lighting does not affect the model at all and directional light seems to apply only half as strong as for materials that use diffuse color or texture.

**To Reproduce**

1. Go to https://threejs.org/editor/
2. Import the attached file 
[LightAffectBug.zip](https://github.com/mrdoob/three.js/files/6137905/LightAffectBug.zip)
3. Add an ambient light via <kbd>Add/AmbientLight</kbd>
4. Note that the top part stays black
5. Add a directional light via <kbd>Add/DirectionalLight</kbd>

**Expected behavior**

Ambient light affects material and directional light affects material same as other materials.

**Screenshots**

Expected:
![image](https://user-images.githubusercontent.com/2693840/111088734-e6111f80-8528-11eb-84fd-2cfe6a3acd82.png)

Actual: Ambient Light Intensity 10
![image](https://user-images.githubusercontent.com/2693840/111088702-b9f59e80-8528-11eb-9404-cf9b97f3cdcd.png)

Actual: Directional Light Intensity 2
![image](https://user-images.githubusercontent.com/2693840/111088728-dbef2100-8528-11eb-89da-73f52205d1a7.png)

**Platform:**

 [X] Device: [Desktop, Mobile]
 [X] OS: [Windows, MacOS, Linux, Android, iOS]
 [X] Browser: [Chrome, Firefox, Safari, Edge]
 [X] Three.js version: [r126]

**Comment by donmccurdy** [comment]
The materials in the top section have metalness values (`metallicFactor` in glTF) of 1.0. To quote @WestLangley, who phrased this well in an older comment:

> The diffuse reflectance of a pure metallic material is zero. Metals only reflect specularly, so the pure metal in our model should not respond to the AmbientLight.

So, it's correct that fully metallic materials appear dark under fully ambient lighting. For best results you'd want to provide an environment map (`scene.environment` or `material.envMap`), which the three.js Editor does not include by default.

**Comment by donmccurdy** [comment]
@mrdoob have we considered including some kind of basic IBL in the editor by default?

**Comment by hybridherbst** [comment]
Oh, interesting. This is an export issue somewhere else then - they are not supposed to have metallicFactor=1. Somehow it seems to be not specified in the file at all, which is a bug. Thanks!

(I'll leave this open for mrdoob to respond but it can be closed)

**Comment by Mugen87** [comment]
> @mrdoob have we considered including some kind of basic IBL in the editor by default?

This would be a good opportunity to merge #18834. Right now, it's not possible to save/reload background and environment setups.

**Comment by Mugen87** [comment]
Closing since the original question is solved.
