### ISSUE TITLE
"envMap" change has no effect on "MeshPhysicalMaterial"

### ISSUE THREAD

**Issue by magamig** [mrdoob/three.js#21463]
**Describe the bug**

An "envMap" change has no effect on "MeshPhysicalMaterial".

**To Reproduce**

1. Go to https://threejs.org/docs/scenes/material-browser.html#MeshPhysicalMaterial
2. Chose an `envMap`
3. See error - there is no effect on the material.

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: latest stable

**Comment by Mugen87** [comment]
That's because of the default material configuration. Try setting `metalness` to `1` and `roughness` to `0` and you will see a difference.
