### ISSUE TITLE
Vertex color alpha is ignored for GLB files

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#21466]
**Describe the bug**

Vertex color alpha seems to be ignored for lit and unlit materials.

**To Reproduce**

1. Go to https://threejs.org/editor/
2. Import one of the attached files 
[VertexColorTransparency.zip](https://github.com/mrdoob/three.js/files/6137892/VertexColorTransparency.zip)
3. Note that the top right and top middle meshes don't have a transparency gradient (they use vertex color with alpha)
4. (note: the middle section is Lit, add a directional light to see the colors there as well)

**Expected behavior**

Vertex color alpha should affect rendering when the material has "alphaMode": "BLEND"
Renders correctly in Bablyon.js and Filament

**Screenshots**

Expected:
![image](https://user-images.githubusercontent.com/2693840/111088250-96315900-8526-11eb-9450-25256084aec6.png)

Actual (note top middle and top right don't have gradients):
![image](https://user-images.githubusercontent.com/2693840/111088284-bcef8f80-8526-11eb-88f2-b6ecd2306788.png)

**Platform:**

 [X] Device: [Desktop, Mobile]
 [X] OS: [Windows, MacOS, Linux, Android, iOS]
 [X] Browser: [Chrome, Firefox, Safari, Edge]
 [X] Three.js version: [r126]

**Comment by donmccurdy** [comment]
three.js does not support vertex alpha yet — see https://github.com/mrdoob/three.js/issues/16403. We hope this will be addressed by https://github.com/mrdoob/three.js/pull/20975.

**Comment by hybridherbst** [comment]
Oh, ok - thanks! Good to know that it's known and in the pipeline :) Sorry for not finding it while searching for the issue.
