### ISSUE TITLE
Quaternion.setFromUnitVectors lacks precision for close to opposite vectors

### ISSUE THREAD

**Issue by iaxyz** [mrdoob/three.js#21477]
**Describe the bug**

A Quaternion calculated using `setFromUnitVectors` doesn't align the two unit vectors precisely if it get's applied.

**To Reproduce**

run the following code using node (I've tested with 14.7.0) or check the live example on JSFiddle.

***Code***

```js
const three = require("three");

const zAxis = new three.Vector3(0, 0, 1);
// just 3 example Vectors that fail
const normals = [
  new three.Vector3(0.00001630279256671349, 0.00021101192465278993, -0.9999999776040931).normalize(),
  new three.Vector3(-0.00011854270500476976, 0.00027142141201982574, -0.9999999561390212).normalize(),
  new three.Vector3(0.000042675541323141565, -0.00040869364504498944, -0.9999999155741478).normalize(),
];

normals.forEach(normal => {
  const alignNormalsRotation = new three.Quaternion().setFromUnitVectors(normal, zAxis);
  console.log(normal.clone().applyQuaternion(alignNormalsRotation).angleTo(zAxis));
});
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/uxegtkso/1/)

**Expected behavior**
I would expect the calculations to have higher precision. I've only encounterd this amount of error with Vectors that are close to being opposite.

Result of the code:
```
0.00021164076687348634
0.000296178929600093
0.00041091569275236077
```

Expected result:
```
0
0
0
```

**Platform:**
Tested locally with:
 - Device: Desktop
 - OS: Windows 10
 - NodeJS: v14.7.0
 - Three.js version: three@0.110.0

and in the browser with:
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chromium, Firefox, Edge (via jsfiddle see link above)
 - Three.js version: "https://threejs.org/build/three.module.js" (17.03.2021)

**Comment by WestLangley** [comment]
This is an edge-case.

In `Quaternion.setFromUnitVectors()` the constant EPS would have to be changed from
```js
const EPS = 0.000001;
```
to
```js
const EPS = 0.00000001;
```
I am not sure of the ramifications -- or advisability -- of doing that.

**Comment by Mugen87** [comment]
How about adding a third epsilon parameter with the existing `0.000001` as a default value?

**Comment by WestLangley** [comment]
I do not think users should be expected to set such parameters. That's our job.

This is a numerical-stability issue.

**Comment by Mugen87** [comment]
The problem is that a fixed epsilon is not always obvious to determine. I mean why was `0.000001` chosen and not something else? 

The desired precision in context of floating point computations is in general use case specific. For some use cases the precision is "good enough". For others not. By making it configurable, a proper epsilon can be picked at app level.

I've seen configurable epsilons in other math libraries, too.

**Comment by WestLangley** [comment]
This is not about a desired precision, it is about avoiding a singularity.

Furthermore, we should not expect users to know how to properly set `EPS`. It is our job to do that.

If a smaller `EPS` is numerically stable, we should use it.

If a smaller `EPS` is  is not numerically stable, we should not allow the user to set it.

//

Ideally, `EPS` should be the smallest value that results in numerically-stable results for the given platform.

**Comment by Mugen87** [comment]
Anyway...

Couldn't we implement the method like so:

https://www.html5gamedevs.com/topic/29839-rotation-between-two-unit-vectors/?tab=comments#comment-171556

**Comment by WestLangley** [comment]
@Mugen87 Thanks for working on it!

The links you are looking for are hidden in here: https://github.com/mrdoob/three.js/pull/4580/files.

You can also check out a glm implementation:
https://github.com/g-truc/glm/blob/ace16e47780dcef815294715237f51e9129b6eb3/glm/gtx/quaternion.inl#L121-L158

**Comment by Mugen87** [comment]
glm uses [std::numeric_limits<T>::epsilon](https://en.cppreference.com/w/cpp/types/numeric_limits/epsilon). From the documentation:

> Returns the machine epsilon, that is, the difference between 1.0 and the next value representable by the floating-point type T.

If we want to use a comparable approach in JS, we have to use [Number.EPSILON](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/EPSILON).

> The Number.EPSILON property represents the difference between 1 and the smallest floating point number greater than 1.

**Comment by WestLangley** [comment]
>`EPS` should be the smallest value that results in numerically-stable results for the given platform.

...meaning the cross-product calculation must be correct. That _may_ be related to `Number.EPSILON` in some complex way...

//

Maybe just implement https://github.com/mrdoob/three.js/issues/21477#issuecomment-801112315 and move on...

```js
const EPS = 1e-8;
```

**Comment by Mugen87** [comment]
I've tested the fiddle with the `Number.EPSILON` approach and it works as expected. I vote for the  `glm` approach since that is indeed a good reference.

**Comment by WestLangley** [comment]
If you feel your testing is exhaustive, give it a go. :-)  I was just opting to be a bit more conservative.

**Comment by nkallen** [comment]
I realize this is an old, closed bug. Nevertheless - I think using Number.EPSILON (1e-16) is perhaps (way) too precise. It means that this branch is basically unreachable if ANY floating point computation has happened on the input vectors, in part because the dot product introduces its own numerical error. I also don't think the solution is having the user pass in an epsilon. But there are numerically more stable ways to test for vectors facing opposite directions (for example, maybe adding the vectors and checking lengthSq() is stabler than the dot product). 

consider this example:

```
const Z = new THREE.Vector3(0,0,1);
const a = new THREE.Vector3(0, 2.2204460492503128e-16, -0.9999999999999996);
const q = new THREE.Quaternion().setFromUnitVectors(Z, a);
```

This is the result:

```
_w: 0.8944271909999159
_x: -0.44721359549995787
_y: 0
_z: 0
```

This does not seem like desirable behavior:

```
console.log(new THREE.Vector3(0,0,1).applyQuaternion(q));
Vector3 {x: 0, y: 0.7999999999999998, z: 0.6000000000000001}
```

Should I open a new issue?
