### ISSUE TITLE
canvas.toDataURL() fails with fragment shader with zero alpha in gl_FragColor

### ISSUE THREAD

**Issue by audas** [mrdoob/three.js#21479]
When I create a fragment shaderMaterial and the fragmentShader text has a zero alpha on the gl_FragColor which allows the background to be transparent, the canvas.toDataURL() is transparent. See below code and the final 0.

`gl_FragColor = vec4(newColour * newColour, 0.);`

To make this a bit more clear - the canvas is definitely being rendered, I am preserving drawing buffer (   preserveDrawingBuffer: true,) we can "see" the canvas. I can alter the  gl_FragColor  to say 0.1   

`gl_FragColor = vec4(newColour * newColour, 0.1);`

And the canvas will render at that alpha. I am just perplexed as to why it renders on the screen / canvas correctly with the gl_FragColor at 0. however the toDataURL is transparent ?

**Comment by Mugen87** [comment]
How is this issue related to `three.js`?

**Comment by audas** [comment]
I'm using Three.js creating three shader material with the fragment shader. As mentioned I am trying to use the preserveDrawingBuffer: true in order to ensure it is available, I have tested with multiple variations of "when" I send the captured canvas to data url etc.

It is only with Three, using the three.shadermaterial with the fragment shader where this occurs. Have not been able to reproduce this outside of Three.js

**Comment by Mugen87** [comment]
Please demonstrate this with a live example.

**Comment by Mugen87** [comment]
You can reopen the issue when the live examples are ready 👍 .
