### ISSUE TITLE
Feature: Quaternion.slerpQuaternions()

### ISSUE THREAD

**Issue by gsimone** [mrdoob/three.js#21498]
It's already possible to easily interpolate between two quaternions by using the static helper, but the Vector classes already implement a .lerpVectors, would it make sense to also have the same API for quaternions?

```js
const q = new Quaternion()
q.slerpQuaternions(quatA, quatB, 0.6)
```

Please understand that this is just to keep the API predictable for end users

**Comment by Mugen87** [comment]
I'm fine with such a method. It should be:
```js
slerpQuaternions( qa, qb, t ) {

    this.copy( qa ).slerp( qb, t );

}
```

**Comment by gsimone** [comment]
I'll PR it later today 👍

**Comment by WestLangley** [comment]
Yes, and I would suggest having it replace the static method:
```js
static slerp( qa, qb, qm, t ) {

	return qm.copy( qa ).slerp( qb, t );

}
```

Retain the static method `slerpFlat()`.

**Comment by Mugen87** [comment]
> and I would suggest having it replace the static method:

What is your motivation behind a removal? I've seen this method used in code multiple times. E.g.

https://github.com/mrdoob/three.js/blob/27def9d26a56e80fd3cb2739598e9716bab123b0/examples/jsm/webxr/XRControllerModelFactory.js#L89-L94

**Comment by gsimone** [comment]
Removing is not necessary, but that example could also be rewritten as 

```js
valueNode.quaternion.slerpQuaternions(minNode.quaternion, maxNode.quaternion, value)
```

**Comment by WestLangley** [comment]
https://github.com/mrdoob/three.js/blob/27def9d26a56e80fd3cb2739598e9716bab123b0/examples/jsm/webxr/XRControllerModelFactory.js#L89-L100

**Comment by Mugen87** [comment]
If we remove it, we have to explain the users why. So if we say we do it for consistency reasons, I'm fine with it.

**Comment by WestLangley** [comment]
Yes, for consistency. This PR is a great suggestion.

**Comment by Mugen87** [comment]
@gsimone I've filed a PR in order to make sure it lands in `r127`.

**Comment by gsimone** [comment]
Awesome, ty 🙏
