### ISSUE TITLE
TransformControls do not show axios when showX, showY, showZ when has large position

### ISSUE THREAD

**Issue by sungle3737** [mrdoob/three.js#21497]
**Describe the bug**
TransformControls do not show axios when `showX`, `showY`, `showZ` when has large position
```js
      updateTransform(xyz) {
        const cloud = cloudRef.cloud
        const transform = cloud.transform
        transform.position.x = xyz[0] - cloud.offset[0]
        transform.position.y = xyz[1] - cloud.offset[1]
        transform.position.z = xyz[2] - cloud.offset[2]
        const pos = transform.position

        const divider = Math.abs(pos.x) + Math.abs(pos.y) + Math.abs(pos.z)
        let factor = 3 / divider
        if (factor > 0.2) factor = 0.2

        transform.setSize(factor)
        transform.attach(cloudRef.selectedLayer)
        transform.visible = state.visible.transform
        transform.enabled = state.visible.transform

        const object = cloudRef.selectedLayer
        object.updateMatrix()
        object.geometry.applyMatrix4(object.matrix)
        object.position.set(0, 0, 0)
        object.updateMatrix()
      }
```
I use this code to change only transform's position.
But when some position of transform is big (even not to large), axis disappear with that axis' property `show${axios}` is true

**Screenshots**
![image](https://user-images.githubusercontent.com/27716524/112103102-9b5c6b00-8bec-11eb-9f03-8755bbefd503.png)

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) first in order to clarify whether this is a user error or not.

Also demonstrate the issue with a [live example](https://jsfiddle.net/f2Lommf5/).
