### ISSUE TITLE
RectAreaLightHelper missing update method or docs are wrong

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#21490]
**Describe the bug**

[The docs for `RectAreaLightHelper` say there is an `update` function](https://github.com/mrdoob/three.js/blob/94f043c4e105eb73236529231388402da2b07cba/docs/examples/en/helpers/RectAreaLightHelper.html#L56) but no such function exists in [the implementation of `RectAreaLightHelper`](https://github.com/mrdoob/three.js/blob/master/examples/jsm/helpers/RectAreaLightHelper.js)

**To Reproduce**

See Links above

***Code***

N/A

***Live example***

N/A

**Expected behavior**

Either an update method is added (would make it consistent with other helpers?) or the method is removed from the docs

**Screenshots**

N/A

**Platform:**

 - Device: Desktop, Mobile
 - OS: Windows, MacOS, Linux, Android, iOS
 - Browser: Chrome, Firefox, Safari, Edge
 - Three.js version: [dev, r126]

**Comment by Mugen87** [comment]
I guess it was missed to remove the method in #21016.

**Comment by greggman** [comment]
Should probably be added to the migration guide too?

**Comment by Mugen87** [comment]
Done!
