### ISSUE TITLE
BufferGeometry: Calling computeVertexNormals() after adding vertices results in incorrect normal attribute size.

### ISSUE THREAD

**Issue by tcannon686** [mrdoob/three.js#21508]
**Describe the bug**

Calling `computeVertexNormals()` after adding more vertices and faces to a `BufferGeometry` object results in the normal attribute having the wrong size. This means that the added vertices don't have normals assigned to them, and results in WebGL warnings like the following when drawing the geometry  with MeshStandardMaterial:
```
WebGL warning: drawElementsInstanced: Indexed vertex fetch requires 537 vertices, but attribs only supply 263.
```

**To Reproduce**

1. Create a BufferGeometry with some vertex data.
2. Call `geometry.calculateVertexNormals()`
3. Add more vertices to `geometry` using `geometry.setAttribute('position', array)`
4. Add more faces using the added vertices using `geometry.setIndex(array)`
5. Call `geometry.calculateVertexNormals()` again
6.  Run `console.log(geometry.attributes.position.count, geometry.attributes.normal.count)`.
7. You should see that the first number is not the same as the second number.

In addition, if you are using any material that uses the normals, you should see WebGL errors about the missing vertices.

***Code***

```js
import * as THREE from "https://threejs.org/build/three.module.js";

const geometry = new THREE.BufferGeometry()

/* Start with a single triangle. */
{
  const vertexData = new Float32Array([
    0, 0, 0,
    1, 0, 0,
    0, 1, 0
  ])
  const indexData = [0, 1, 2]
  geometry.setAttribute('position', new THREE.BufferAttribute(vertexData, 3))
  geometry.setIndex(indexData)
  geometry.computeVertexNormals()
}

/* Add a second triangle to the same geometry by adding a fourth vertex. */
{
  const vertexData = new Float32Array([
    0, 0, 0,
    1, 0, 0,
    0, 1, 0,
    1, 1, 0
  ])
  const indexData = [0, 1, 2, 1, 3, 2]
  geometry.setAttribute('position', new THREE.BufferAttribute(vertexData, 3))
  geometry.setIndex(indexData)
  geometry.computeVertexNormals()
}

const positionCount = geometry.attributes.position.count
const normalCount = geometry.attributes.normal.count

/*
 * Throws an error because both positionCount and normalCount should be 4, but
 * positionCount = 4 and normalCount = 3.
 */
if (positionCount !== normalCount) {
  throw new Error(`positionCount (${positionCount}) !== normalCount (${normalCount})`)
}
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/1hwtuy4o/)
* [jsfiddle-dev](https://jsfiddle.net/n6wvztx4/1/)

**Expected behavior**

Check the console. You should see `Error: positionCount (4) !== normalCount (3)` due to the bug.

**Screenshots**

N/A

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Firefox
 - Three.js version: dev, r126

**Comment by Mugen87** [comment]
Instances of `BufferGeometry` are considered to have a fixed size. You can't resize buffers.

The solution for this issue is to call `dispose()` on the old geometry and create a new one with the larger buffers.
