### ISSUE TITLE
Regression in r127dev MultiRenderTarget GL_INVALID_OPERATION: Blit feedback loop: the read and draw framebuffers are the same.

### ISSUE THREAD

**Issue by arpu** [mrdoob/three.js#21517]
r127dev
https://raw.githack.com/mrdoob/three.js/dev/examples/webgl2_multisampled_renderbuffers.html

works on stable r126
https://threejs.org/examples/?q=webgl2_multisampled_renderbuffers.#webgl2_multisampled_renderbuffers
**To Reproduce**

***Live example***

**Expected behavior**

should work on r127dev 

**Screenshots**
![Bildschirmfoto von 2021-03-25 15-06-37](https://user-images.githubusercontent.com/14173/112485955-ba3d3780-8d7b-11eb-901e-fbbb4197ed5b.png)

**Platform:**

 - Device: [Desktop]
 - OS: [ Linux]
 - Browser: [Chrome 89]
 - Three.js version: [dev]

**Comment by Mugen87** [comment]
Good catch! It seems the E2E tests are not yet able to detect this issue.

**Comment by arpu** [comment]
i see this problem on testing MultiRenderTarget on webgl2 for MSSA >4  would be nice to add this to the example?   with gl.MAX_SAMPLES

**Comment by mrdoob** [comment]
> i see this problem on testing MultiRenderTarget on webgl2 for MSSA >4 would be nice to add this to the example? with gl.MAX_SAMPLES

Would you like to do a PR for it?

**Comment by arpu** [comment]
i have some problems on this, i always get 0 Samples used in Spector.js

**Comment by arpu** [comment]
would be nice to get some hints how i can use this 
testing on https://jsfiddle.net/xgw4705v/13/

**Comment by arpu** [comment]
looks like i need this https://github.com/mrdoob/three.js/pull/16895 to get this done

**Comment by mrdoob** [comment]
Feel free to do a new PR to replace #16895 👍
