### ISSUE TITLE
DeviceOrientationControls: add warning about the need of https on documentation or code

### ISSUE THREAD

**Issue by ieskudero** [mrdoob/three.js#21525]
**Is your feature request related to a problem? Please describe.**

using `deviceOrientationControls `with http calls doesn't work, and it is not explained anywhere (or I didn't see it anywhere). I wasted a lot of time that could be avoided if there was a warning on the documentation page or code that said it is a must to use the controls with https calls.

**Describe the solution you'd like**

Add a warning to documentation explaining the need of https protocol.

**Describe alternatives you've considered**

add a warning in code also.

**Comment by Mugen87** [comment]
SSL is required for other modern Web APIs like WebXR, too. However, I do not vote to enhance the documentation in that regard since you could then argue to add all Web API specific requirements to the documentation. This is clearly out of scope.

**Comment by mrdoob** [comment]
@Mugen87 We can add this to the code though:

```js
if ( window.isSecureContext === false ) {

console.error( 'THREE.DeviceOrientationControls: DeviceOrientationEvent is only available in secure contexts (https)' );

}
```

[We do similar things for WebXR](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/webxr/VRButton.js#L143-L148).

**Comment by Mugen87** [comment]
I was not aware of this check in `VRButton`. Okay, let me file a PR with this code^^.
