### ISSUE TITLE
GLTFLoader and Morph Influences Inconsistent with Blender 

### ISSUE THREAD

**Issue by seflless** [mrdoob/three.js#21521]
*Excuse the length of the bug report, just trying to be thorough*

Hi,

The morphInfluence system in three.js or the GLTFLoader do something where when certain blend shapes are non zero it seems to cancel out. In particular I've been focusing on jaw/mouth opening to pick a use case. 

**For context:**
I'm building a web based mocap solution for sending ARKit face tracking data to a web app that uses it to animate ReadyPlayer.me avatars. I thought it might be my code

 (and maybe it still is), but I found this GLTF viewer based on three.js (https://gltf-viewer.donmccurdy.com/ / [Source](https://github.com/donmccurdy/three-gltf-viewer/blob/master/src/viewer.js)) and it exhibits the same issue. 

Here are the same blend shape weights applied in Blender vs three.js based GLTF Viewer:

The exact weight settings to reproduce this example (For the Wolf3D_Teeth Morph Target)
  - noseSneerLeft: 0.15
  - noseSneerRight: 0.15
  - mouthLowerDownLeft: 0.15
  - mouthLowerDownRight: 0.15
  - jawOpen: 1.0

*It should look like how Blender renders it here (notice the jaw/mouth is open)*
<img width="750" alt="blender-avatar-morph-targets" src="https://user-images.githubusercontent.com/1845/112512634-efd92500-8d69-11eb-9fcc-711f77c8fa60.png">

*It looks like this though instead (notice the jaw/mouth is closed)*
<img width="750" alt="three-js-gltf-morph-targets" src="https://user-images.githubusercontent.com/1845/112512630-ef408e80-8d69-11eb-8d17-1e37a3614ed7.png">

**Note: If you set all of the 0.15 values to 0.0 the mouth suddenly opens, which is odd. Them being near zero should already have barely any affect on the final results.

Attached is the GLB used in these screenshots above.
[avatar-fullbody.glb.zip](https://github.com/mrdoob/three.js/files/6206502/avatar-fullbody.glb.zip)

**Comment by Mugen87** [comment]
Your asset defines morph targets and morph normals. In this case, only four targets can influence a single vertex at the same time.

If you would remove morph normals, you could use eight morph targets for influencing vertices.

Related issue: #14441

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.

**Comment by Francois-Laberge-Bose** [comment]
Thanks for the quick answer. Good to know I shouldn't bang my head against the wall and it's known. I'll follow those threads and think about a work around if possible.
