### ISSUE TITLE
GLTFExporter does not honor groups with non-indexed geometry.

### ISSUE THREAD

**Issue by wnayes** [mrdoob/three.js#21538]
**Describe the bug**

A model that uses multiple materials on a single mesh does not always export to glTF in a way that preserves the multiple materials.

Specifically, I noticed the problem with non-indexed geometry. It looks like it does work for indexed geometry.

**To Reproduce**

1. Go to https://codesandbox.io/s/pensive-microservice-iq2vp
2. See that the cube has different colors on each side, due to multiple materials each assigned to a group on the geometry.
3. Click the "Download .gltf" button. (Unfortunately couldn't get the fancy download button to work. But it logs the glTF JSON to the console in the code sandbox. And [here's a gist](https://gist.github.com/wnayes/da34358701951667cf8407d10a10bba4) with what the JSON result is.
3. Import the cube gltf into something like Blender and observe that all sides are one color.

***Code***

The full example is in the sandbox:
https://codesandbox.io/s/pensive-microservice-iq2vp

But the important parts are as follows:
```js
  const geometry = new THREE.BoxBufferGeometry( 10, 10, 10 );
  geometry.clearGroups();
  geometry.addGroup( 0, 6, 0 );
  geometry.addGroup( 6, 6, 1 );
  geometry.addGroup( 12, 6, 2 );
  geometry.addGroup( 18, 6, 3 );
  geometry.addGroup( 24, 6, 4 );
  geometry.addGroup( 30, 6, 5 );
  geometry = geometry.toNonIndexed(); // Important for repro

  const materials = [
    new THREE.MeshBasicMaterial( { color: 0xFFFFFF, visible: true } ),
    new THREE.MeshBasicMaterial( { color: 0xFF0000, visible: true } ),
    new THREE.MeshBasicMaterial( { color: 0x00FF00, visible: true } ),
    new THREE.MeshBasicMaterial( { color: 0x0000FF, visible: true } ),
    new THREE.MeshBasicMaterial( { color: 0xFFFF00, visible: true } ),
    new THREE.MeshBasicMaterial( { color: 0x00FFFF, visible: true } )
  ];

  const mesh = new THREE.Mesh(geometry, materials );
  scene.add( mesh );
```
```js
  const exporter = new GLTFExporter();
  exporter.parse(scene, function (gltfJson) {
    console.log(gltfJson);
  }, { binary: false });
```

**Screenshots**
Cube in code sandbox rendered by three.js:
![three-cube-codesandbox](https://user-images.githubusercontent.com/1417866/112762682-94f03980-8fc6-11eb-8c8f-e37ec31b773e.png)

Cube in Blender after glTF export with GLTFExporter:
![three-cube-blender](https://user-images.githubusercontent.com/1417866/112762690-9e79a180-8fc6-11eb-89fa-63f159415d69.png)

**Platform:**

 - Browser: [Chrome]
 - Three.js version: [0.126.1]

**Observations**
In the glTF file that is created, the primitives of the mesh all use different `material`s as expected, but they all share the same `attributes` which appears to be the cause of the render issue.

In GLTFExporter `processMesh`, I think we'd need to create separate accessors for each group. This is done when `geometry.index !== null` in the groups loop towards the bottom of `processMesh`, but for non-indexed there is no equivalent handling.

**Comment by knightcube** [comment]
I tweaked your code a bit and tried downloading GLB instead of GLTF. The GLB model didn't even load though. I wonder why🤔

This is what I tried. I set the value of binary to true rather than false to download the model in GLB format rather than GLTF.-

function download() {
  const exporter = new GLTFExporter();
  exporter.parse(scene, function (gltfJson) {
    console.log(gltfJson);
    const jsonString = JSON.stringify(gltfJson);
    console.log(jsonString);

    // The following doesn't seem to work due to iframe sandboxing.
    // But please save the gltf json from the Console to obtain the file.
    const blob = new Blob([jsonString], { type: "application/json" });
    saveAs(blob, "colored-square.glb");
    console.log("Download requested");
  }, { binary: true});
}

The reason I thought that GLB will be better to use rather than GLTF is that GLB has all the materials and other metadata of the model embedded inside one binary file i.e colored-square.glb

**Comment by jtbandes** [comment]
I have a proposed fix at https://github.com/mrdoob/three.js/pull/23333. Feedback welcome!

**Comment by Lipacinp** [comment]
It solves my problem at #25729. 

I hope this PR will be accepted.

Thanks @jtbandes.

**Comment by LeviPesin** [comment]
Maybe at some time we should even remove the geometry groups/multi-material API?
