### ISSUE TITLE
GLTFLoader: Vertex color alpha support

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#21533]
**Is your feature request related to a problem? Please describe.**

Now that we support vertex colors with alpha (#20975, #21530) how should `GLTFLoader` handle it?

**Describe the solution you'd like**

I can see that it's supposed to be supported:

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0

<img width="1013" alt="Screen Shot 2021-03-27 at 8 40 15 PM" src="https://user-images.githubusercontent.com/97088/112734276-a55bd200-8f3c-11eb-8070-993b4b785e80.png">

But should the loader automatically set `transparent: true` in the material when we find a `VEC4` attribute?

@donmccurdy @takahirox

**Comment by donmccurdy** [comment]
That's exciting! :)

> But should the loader automatically set transparent: true in the material when we find a VEC4 attribute?

No, the logic for setting `transparent: true` can remain as it is now. The <kbd>A</kbd> component should have no effect if the glTF material does not use one of `alphaMode: BLEND` or `alphaMode: MASK`.

**Comment by takahirox** [comment]
And we don't hardcode accessor type for vertex color attribute but we refer to [accessor.type to determine the type (vec3, vec4, or so on)](https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/GLTFLoader.js#L2337) so vec4 vertex color attribute is already supported.

So, my understanding is vertex color alpha + glTF loader should be workable even without any change in the loader if Three.js core supports it, shouldn't it?

**Comment by mrdoob** [comment]
Sounds good!

**Comment by mrdoob** [comment]
I guess it'd be nice to have a new gltf model test.

Right now they only have this one:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/VertexColorTest
