### ISSUE TITLE
Octree: Memory overload.

### ISSUE THREAD

**Issue by Hoodgail** [mrdoob/three.js#21568]
https://github.com/mrdoob/three.js/blob/e48fc94dfeaecfcbfa977ba67549e6108b370cbf/examples/jsm/math/Octree.js#L90

If you look at this line you will notice that its making a loop until the triangle is the same as the octree's last triangle
but, .pop runs a loop, so each while loop is running an other loop and a normal map will have 400 triangles so you can already figure out how much loops are being made.

i kinda resolved this issue by using this argument ``--max-old-space-size=4096`` so i dont get this error
![image](https://user-images.githubusercontent.com/45743294/113481869-00745400-946a-11eb-8ee9-4bb68372e6d7.png)

i updated the code to
```js
split(level) {

	if (!this.box) return;

	let subTrees = [];
	let halfsize = _v2.copy(this.box.max).sub(this.box.min).multiplyScalar(0.5);

	for (let x = 0; x < 2; x++) {

		for (let y = 0; y < 2; y++) {

			for (let z = 0; z < 2; z++) {

				let box = new Box3();
				let octree = new Octree(box)

				let v = _v1.set(x, y, z);

				box.min.copy(this.box.min).add(v.multiply(halfsize));
				box.max.copy(box.min).add(halfsize);

				subTrees.push(octree);

			}

		}

	}

	for (let k = 0; k < this.triangles.length; k++) {

		let triangle = this.triangles[k];

		for (let i = 0; i < subTrees.length; i++) {

			let tree = subTrees[i]

			let intersection = tree.box.intersectsTriangle(triangle);

			if (intersection) tree.triangles.push(triangle);

		}

	}

	this.triangles.length = 0;

	for (let i = 0; i < subTrees.length; i++) {

		let tree = subTrees[i]

		let len = tree.triangles.length;

		if (len > 8 && level < 16) tree.split(level + 1);

		if (len != 0) this.subTrees.push(tree);


	}

	return this;


}
```

Now it does the process in 57.333 seconds witch is better but meh....

There is an other issue that i will point out in an other post

**Comment by Hoodgail** [comment]
@Mugen87 I have fixed the isssue

```js
for (let k = this.triangles.length; k > 0; k--) {

	let triangle = this.triangles[k - 1];

	for (let i = 0; i < subTrees.length; i++) {

		let tree = subTrees[i]

		let intersection = tree.box.intersectsTriangle(triangle);

		if (intersection) tree.triangles.push(triangle);

	}

}
```

there, now it does the process in 140MS :)

**Comment by Mugen87** [comment]
@Hoodgail I've checked out your code but instead of a `for` loop nested in a `while` loop there is now a `for` loop nested in a `for` loop. I suggest the following approach:

- Please demonstrate the current memory issue with a live example.
- Share a second live example with your code that shows how it improves performance.

**Comment by mrdoob** [comment]
Closing this until more information is provided.
