### ISSUE TITLE
WebGLMultisampleRenderTarget causes blit feedback loop

### ISSUE THREAD

**Issue by vanruesc** [mrdoob/three.js#21569]
**Describe the bug**

Rendering to a `WebGLMultisampleRenderTarget` and then copying the contents to screen no longer works in r127 because it incorrectly produces a framebuffer feedback loop:

```sh
Firefox: blitFramebuffer: DRAW_FRAMEBUFFER may not have multiple samples.
Chrome: [.WebGL-00005D4000163C80] GL_INVALID_OPERATION: Blit feedback loop: the read and draw framebuffers are the same.
```

The internal framebuffer feedback loop causes rendering to get stuck - the render output doesn't refresh as expected when the user interacts with the scene. Resizing or disposing the render target does update the output.

The issue does not occur when using a simple `WebGLRenderTarget`. It can also be worked around by ping-ponging two identical `WebGLMultisampleRenderTarget` instances. The [webgl2_multisampled_renderbuffers](https://threejs.org/examples/?q=msaa#webgl2_multisampled_renderbuffers) still works because it uses the `EffectComposer` which always swaps render targets each frame. The same setup worked fine in earlier versions of `three`, such as `0.126.1`.

This issue is likely related to the recent framebuffer state management changes: #21447, #21442, #21518

**To Reproduce**

1. Create an instance of `WebGLMultisampleRenderTarget`
2. Render a scene into the multisampled render target
3. Use a fullscreen quad/triangle to draw the contents of the render target to screen
5. Open the console (F12) to see the unexpected warnings/errors

***Live example***

* [CodeSandbox](https://codesandbox.io/s/upbeat-monad-mzt3t?runonclick=1&file=/src/App.js)

**Expected behavior**

Since the rendering pipeline does not contain any feedback loops, there should be no warnings and rendering should be responsive. Frame buffer swapping with an additional render target should not be necessary for this setup.

**Platform:**

 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome, Firefox, Edge
 - Three.js version: dev, r127

**Comment by Mugen87** [comment]
One framebuffer bind is currently missing due to the new caching. The handling of `DRAW_FRAMEBUFFER` is actually a bit tricky. But the above PR should solve the issue.

**Comment by vanruesc** [comment]
Awesome, thanks for the quick fix!
