### ISSUE TITLE
add somthing like .intersectOBBs to raycaster 

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#21560]
Well, right now it is easer for me to have an array of actual box meshes and use .intersectObjects than to write the code to intersect a bunch of OBB objects. This is not good.

**Describe the solution you'd like**

What the title says - it would be nice to reuse camera->ray logic and have something to run loops for me and sort the results by distance.

**Describe alternatives you've considered**

I could, of course, write my own code, but I dont want to.

**Additional context**

Nope.

**Comment by Mugen87** [comment]
The `OBB` class is located in the examples and we do not usually implement logic in the core that relies or refers to example code.

However, enhancing the interface of `OBB` is of course possible. Would this be okay for you at the moment?

**Comment by makc** [comment]
> The OBB class is located in the examples

ah, I saw them in /docs and from there assumed they are 1st class api - my bad
>  enhancing the interface of OBB

I think it is okay if the methods sit in OBB instead, but people would be less likely to find them there. Unless the example is modified to use them I guess.
> Would this be okay for you at the moment?

at the moment I am on r125 for this particular task so it does not matter much for me personally, but if this was added before I would use it today.

**Comment by WestLangley** [comment]
@Mugen87 

I would suggest renaming `OBB.rotation` to `OBB.rotationMatrix`, as 'rotation' is an Euler angle in three.js.

Also, function `matrix4FromRotationMatrix()` is not required. You can use the existing `Matrix4.setFromMatrix3()`, instead.

**Comment by Mugen87** [comment]
> Also, function matrix4FromRotationMatrix() is not required. You can use the existing Matrix4.setFromMatrix3(), instead.

Good hint! When `OBB` was implemented, `setFromMatrix3()` was not yet available. I'll update the code.

**Comment by Mugen87** [comment]
I favor to keep `rotation` as it is. As long as it represents the rotation of an entity it's fine. `SpriteMaterial.rotation` is a scalar.

**Comment by Mugen87** [comment]
I've realized today that the example already contains the code that you are looking for. Meaning finding the closest intersection out of an array of objects based on their OBBs:

https://github.com/mrdoob/three.js/blob/f994a92b3436e23156dc23f84d74236c0efd317f/examples/webgl_math_obb.html#L121-L165

When I look at this code know, I think it is too high-level in order to add it to a `OBB` class which should be nothing more than a basic math entity providing methods for intersections and other related tests. The example feels like the right place for this code.

**Comment by makc** [comment]
@Mugen87 unfortunately I cant import anything from webgl_math_obb.html (it is not even a part of npm three package), nor can I copy-paste this code without editing like half of it, so it basically means I need to write it myself in my project - which was exactly what I would like to avoid.
