### ISSUE TITLE
Inconsistent existence of `dispose()` across API

### ISSUE THREAD

**Issue by acu192** [mrdoob/three.js#21572]
# Describe the bug

Documentation states ([here](https://threejs.org/docs/#manual/en/introduction/How-to-dispose-of-objects)):
> In general, it's recommended to check the API or documentation of a class and watch for `dispose()`. If present, you should use it when cleaning things up.

However, the existence of `dispose()` across API is inconsistent. E.g. `SpotLightHelper` has `dispose()` but `CameraHelper` does not. Based on the above statement from the documentation, one might assume a `CameraHelper` does not need to be disposed, but such a conclusion would leak one material and one geometry that the `CameraHelper` creates _internally_ (probably unknown by the user). To know this, you must look at the source code of `CameraHelper` to see how it works, which is _doable_ but not _optimal_.

I propose that any object which creates materials/geometries/textures *internally* should have a `dispose()` method to dispose of those internally-created-resources (like `SpotLightHelper` already does ... but others do not).

If this is of interest to the maintainers, I can volunteer to send in a PR. If not, I will not send in a PR. :) Let me know. I have an SPA site so I've found many of these missing-`dispose()` objects and have runtime patches to fix them already in my app.

**Comment by Mugen87** [comment]
> I propose that any object which creates materials/geometries/textures internally should have a dispose() method to dispose of those internally-created-resources

This is indeed the established policy. If a `dispose()` method is missing, it should be added.

It would be great if you file a PR for `CameraHelper`! 😊

**Comment by acu192** [comment]
`AxesHelper` is another one I'll include in my PR.

A harder question is what to do about lights? I need the maintainers' opinion. I propose:
1. `LightShadow` has a `dispose()` for disposing of `map` and `mapPass`.
2. `Light` has a `dispose()` that checks for the existence of `this.shadow` and calls dispose on it, if it exists.

Alternatively for \#2 above, we could have only `PointLight`, `SpotLight`, and `DirectionalLight` implement `dispose()`, because only those have shadows. Thoughts?

**Comment by Mugen87** [comment]
It vote for option 2. Adding an empty `dispose()` in `Light` and implement it in all shadow casting light classes.
