### ISSUE TITLE
OpenGL error when bundeling three.js with Deno

### ISSUE THREAD

**Issue by wrnrlr** [mrdoob/three.js#21576]
Honestly don't know if this is related to three or deno

I have a module that draws a cylinder and box geometry.
When I directly include this file with a script tag it draws both cylinder and box.
But, when I first bundle the file it only show the box, and logs this error:

    [.WebGL-0x7f9fab819e00]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0

![screenshot](https://user-images.githubusercontent.com/24570434/113589110-47607600-9631-11eb-9574-128df862d628.png)

The code is very straightforward, simple html and js

index.html

```
<style>html,body { height: 100%;}</style>
<script type="module" src="main.js"></script>
```

broken.html

```
<style>html,body { height: 100%;}</style>
<script type="module" src="bundle.js"></script>
```

main.js
```
import {Scene,PerspectiveCamera,WebGLRenderer,Mesh,MeshBasicMaterial,BoxGeometry,CylinderGeometry}
from 'https://unpkg.com/three/build/three.module.js'
const container = document.body
const width = 300, height = 300;
const canvas = document.createElement('canvas')
const gl = canvas.getContext("webgl") || canvas.getContext("experimental-webgl")
if (!(gl && gl instanceof WebGLRenderingContext)) throw new Error('OpenGL not supported')
const scene = new Scene()
const camera = new PerspectiveCamera(5, width / height)
container.appendChild(canvas)
const renderer = new WebGLRenderer({ canvas, antialias: true })
renderer.setSize(width, height)
const greenStuff = new MeshBasicMaterial( {color: 0x00ff00, wireframe: true})
scene.add(new Mesh(new BoxGeometry(), greenStuff))
scene.add(new Mesh(new CylinderGeometry(), greenStuff))
camera.position.set(5, 20, 22)
camera.lookAt(0, 0, 0)
scene.add(camera)
renderer.render(scene, camera)
```

This command to bundle the code into bundle.js (doesn't work with either --watch --unstable or without):

```
deno bundle ./main.js ./bundle.js
```

server.js:

```
import {Application, send} from "https://deno.land/x/oak@v6.5.0/mod.ts";
const app = new Application()
app.use(async (context) => {
  await send(context, context.request.url.pathname, {
    root: `${Deno.cwd()}`,
    extensions: ['html'],
    index: "index.html",
  })
})
await app.listen({port: 8000})
```

Run it with: `deno run --allow-net --allow-read server.js`

Handy zip with everything:

[three-problem.zip](https://github.com/mrdoob/three.js/files/6258838/three-problem.zip)

deno 1.7.0 (release, x86_64-apple-darwin)
v8 8.9.255.3
typescript 4.1.3

three js version: 127

Tested in both safari and chrome

**Comment by wrnrlr** [comment]
(Deno cross post)[https://github.com/denoland/deno/issues/10022]

**Comment by mrdoob** [comment]
https://github.com/denoland/deno/issues/10022#issuecomment-813446837
