### ISSUE TITLE
Behavior of Object3D EventDispatcher for added/removed event 

### ISSUE THREAD

**Issue by jfeick** [mrdoob/three.js#21582]
**Describe the bug**

I am not sure if this is really a bug, but I would like to clarify if this is intended behavior?

You can add event listeners to an `Object3D` for the type `added` and `removed`. I would assume, that this would dispatch an event to the object that is adding/removing another object but the code handles it so, that it dispatches the event for the child that is to be added/removed. Semantically I would assume that the event should be dispatched for the parent object, especially when we are dealing with a `Scene` object, for example to trigger a render request.

The code in question is here: https://github.com/mrdoob/three.js/blob/e48fc94dfeaecfcbfa977ba67549e6108b370cbf/src/core/Object3D.js#L334

**To Reproduce**

***Code***

```js
const scene = new THREE.Scene();
scene.addEventListener("added", () => { console.log("something was added to the scene") });
const someObject = new THREE.Object3D();
scene.add(someObject);

```

**Expected behavior**

I would expect the event to be dispatched for the `Scene`.

**Platform:**

 - Device: Desktop
 - OS: Windows, MacOS, Linux, Android, iOS
 - Browser: Chrome, Firefox, Safari, Edge
 - Three.js version:  dev

**Comment by Mugen87** [comment]
> but I would like to clarify if this is intended behavior?

Yes, this is the intended behavior. The events `added` and `removed` are dispatched for objects that are added or removed.
