### ISSUE TITLE
BUG!,In lastest 127.0 version when I use WebGLMultisampleRenderTarget, only can add one pass

### ISSUE THREAD

**Issue by liuyehua** [mrdoob/three.js#21580]
In lastest 127.0 version when I use WebGLMultisampleRenderTarget, I find I only can add one composer pass, if more than one such as outline or bloom, the scene will not update , in 126.0 version is ok.

**Comment by Mugen87** [comment]
This should be already fixed in `r128dev`, see #21570.

**Comment by liuyehua** [comment]
> This should be already fixed in `r128dev`, see #21570.

thank you
