### ISSUE TITLE
Expand support for GLSL integer attributes

### ISSUE THREAD

**Issue by davidkarp** [mrdoob/three.js#21595]
Expanding on the `vertexAttribIPointer` support added in https://github.com/mrdoob/three.js/pull/19019, I would like to propose a new property:

`BufferAttribute.targetType = FloatType` (default)

This property would support values of the existing constants `FloatType` (default) and `IntType`.

This would expand support for integer attributes (beyond the current `int32` and `uint32`) without changing any existing behavior.

The property would ultimately get passed through to `WebGLBindingStates.vertexAttribPointer()` where the code impact is minimal:

```diff
-function vertexAttribPointer( index, size, type, normalized, stride, offset ) {
+function vertexAttribPointer( index, size, type, normalized, stride, offset, targetType ) {

-    if ( capabilities.isWebGL2 === true && ( type === 5124 || type === 5125 ) ) {
+    if ( capabilities.isWebGL2 === true && ( type === 5124 || type === 5125 || targetType == IntType ) ) {

        gl.vertexAttribIPointer( index, size, type, stride, offset );

    } else {

        gl.vertexAttribPointer( index, size, type, normalized, stride, offset );

    }

}
```

Alternatively, this could be a boolean attribute such as `BufferAttribute.toIntegers = true`, as it looks like WebGL only supports `vertexAttribPointer` (float) and `vertexAttribIPointer` (int) – not `vertexAttribLPointer` (double).

Apologies if I'm missing anything obvious. Thank you!

**Comment by Mugen87** [comment]
Adding a new property to `BufferAttribute` just for this specific use case seems not appropriate to me.

Do you mind explaining in more detail the benefit of this PR? Why can't you just use `Int32BufferAttribute` or `Uint32BufferAttribute`?

**Comment by davidkarp** [comment]
Perhaps I'm missing something obvious, but there doesn't appear to be a way to map an 8 or 16-bit buffer to a GLSL integer attribute. A declaration such as `in int groupId` on a `Uint8BufferAttribute` will incorrectly call `vertexAttribPointer()` and trigger the following error:

```
GL ERROR :GL_INVALID_OPERATION : glDrawArraysInstancedANGLE: vertexAttrib function must match shader attrib type
````

> Why can't you just use `Int32BufferAttribute` or `Uint32BufferAttribute`?

In my case, 8-bit buffers are being used to dramatically **cut memory overhead**. For example:

1. Large collections of instance geometry where characteristics of each instance can be inferred from an 8-bit value. (eg. pre-defined material properties, voxel face/orientation, bone group, etc.)

2. Mesh vertices are all whole numbers limited to a 100x100x1000 bounding box, allowing each vertex to be packed into an `ivec3` that gets masked to a 7, 7, and 10-bit integer.

Thank you for taking the time to look at this! ♥️

**Comment by Mugen87** [comment]
Thanks for the additional information! That made it more clear. To sum up:

- The renderer currently only supports `Int32BufferAttribute` (`gl.INT`) and `Uint32BufferAttribute` (`gl.UNSIGNED_INT`) in context of `vertexAttribIPointer()`. Other types of integer attributes (`gl.BYTE`, `gl.UNSIGNED_BYTE`, `gl.SHORT`, `gl.UNSIGNED_SHORT`)  are currently not supported.
- The purpose of this issue is to add support for the above types.

How about add a new flag to `Int8BufferAttribute`, `Uint8BufferAttribute`, `Uint16BufferAttribute` and `Int16BufferAttribute` to control how the data should be interpreted? I would prefer this instead of changing `BufferAttribute`.

**Comment by davidkarp** [comment]
You're the best.

A new flag would absolutely work. Just to confirm, you're describing a boolean parameter like this?
```
Int8BufferAttribute( array, itemSize, normalized, mapToInteger )
````
Any suggestion for the variable name?

**Comment by Mugen87** [comment]
Maybe `asInteger`? Or just `integer`?

@mrdoob Do you have a preference here?

**Comment by 0X-JonMichaelGalindo** [comment]
I was trying this exact thing. For int8/uint8, I didn't need a flag, just a check.

```if ( capabilities.isWebGL2 === true && ( type === 5124 || type === 5125 || ( type === gl.UNSIGNED_BYTE && normalized === false ) )```

1. Int arrays cannot be normalized. 
2. JS has no 8-bit floats. 
Therefore, if and only if normalized = false on an 8bit array, it must be an integer attribute, guaranteed.

This also resolves the common issue: "my 8bit color arrays all come through as white" / "you must set normalized=true to use 8bit arrays at all."

This does not resolve the int16 case.

**Comment by donmccurdy** [comment]
> The renderer currently only supports Int32BufferAttribute (gl.INT) and Uint32BufferAttribute (gl.UNSIGNED_INT) in context of vertexAttribIPointer(). Other types of integer attributes (gl.BYTE, gl.UNSIGNED_BYTE, gl.SHORT, gl.UNSIGNED_SHORT) are currently not supported.

I think I am misunderstanding something, I use u8/i8/u16/i18 buffer attributes pretty often and they appear to work fine ... in what context does `vertexAttribIPointer` come into play and they aren't supported? Aren't these attributes always interpreted as integers unless the 'normalized' flag is `true`?

**Comment by gkjohnson** [comment]
> Aren't these attributes always interpreted as integers unless the 'normalized' flag is true?

This isn't the case - they're uploaded as floats even when "normalized" is false. When gltfpack generates quantized attributes, for example, it does not normalize the buffer. It instead uses the integer values directly as position values and scales the mesh appropriately. 

This request is to enable uploading the buffers to the gpu (and therefore reading them in shaders) as integers. Of course users could cast the floats to ints or uints as needed but you lose a lot of precision doing so and will wind up using more memory than necessary. In the past, non-three.js projects I've used int attributes to associate and render triangle ids to a buffer.

I'm happy with the `attribute.integer = true` solution in #21606 but it seems to have not had a lot of extended discussion recently. But I am supportive of the addition.

**Comment by donmccurdy** [comment]
> This isn't the case - they're uploaded as floats even when "normalized" is false. When gltfpack generates quantized attributes, for example, it does not normalize the buffer. It instead uses the integer values directly as position values and scales the mesh appropriately.

Sorry, I'm still lost here. Suppose we have a 10x10x10 mesh —

- gltfpack uses u8 and u16 vertex positions with "normalized=false", meaning the (integer-valued) vec3 components in the vertex shader are in the range [0, 255] or [0, 65536], and a corrective scale (<1) is applied to the mesh
- gltf-transform uses i8 and i16 vertex buffers with "normalized=true", meaning the (float-valued) components in the vertex shader are in the range [-1, 1], and a corrective scale (>1) is applied to the mesh

Both of these things appear to work today, though I haven't inspected the internal WebGL calls. Are you saying three.js expands 8-bit integers to 32-bit floats? Or that the 8-bit integers are technically being stored and used in the vertex shader as 8-bit floats that happen to only have whole integer values? Do you mind being more specific about the GL types and memory footprint three.js is using here, and what we would like it to use instead?

**Comment by gkjohnson** [comment]
> Are you saying three.js expands 8-bit integers to 32-bit floats? Or that the 8-bit integers are technically being stored and used in the vertex shader as 8-bit floats that happen to only have whole integer values? Do you mind being more specific about the GL types and memory footprint three.js is using here, and what we would like it to use instead?

I'm unfamiliar with all the low level details here but this is the practical effect when writing a shader and should help with the disconnect. Consider the attribute buffer "intData" that is composed of an Int32Array:

```js
geometry.setAttribute( 'intData', new BufferAttribute( new Int32Array( data ), 3 ) );
geometry.attribute.intData.normalized = false;
```

Here is how you'd access the data in the shader:

```js
attribute vec3 intData; // floats
```

However if it were uploaded as an integer data type:

```js
geometry.attribute.intData.integer = true;
```

You'll be able to access the data like so in the shader:

```js
attribute int3 intData; // ints
```

From my perspective it's a small but meaningful difference. As I mentioned above it's possible to cast the floats to an int using `float( round( value ) )` but int32 and uint32 can store a larger maximum whole number without error which is important when dealing with the full range of integers. See the following behavior:

```js
const val = 2**31 - 1;
const arr = new Float32Array( [ val ] );
console.log( val === arr[ 0 ], val, arr[ 0 ] );
// false 2147483647 2147483648
```

I'm not sure how precision or memory footprint is affected when using something like an int 16 or int 8 and uploading these values to the gpu. Perhaps @davidkarp can speak to the memory use case.

**Comment by donmccurdy** [comment]
This comment and https://github.com/mrdoob/three.js/pull/21606#issuecomment-1225172386 filled in the gaps here — thanks!

I think the most compelling alternative to a new property like `.integer=true` would be:

1. Begin automatically using `attribute int# data` for integer-based arrays with `.normalized=false`
2. For 'native' vertex attributes like 'position', which our shaders assume must be floats, either make an exception to (1), or explicitly cast from int to float in the shader. 

This would mean users can work with the full range of int-typed BufferAttributes in custom shaders easily, but the `position` attribute may not be able to use the larger max values of int32. 

If this seems more complicated then i'm fine with `.integer=true`. I was hoping perhaps to avoid the overlapping/conflicting meanings of typed arrays, BufferAttribute subclasses, `.normalized`, and `.integer`.

**Comment by gkjohnson** [comment]
> For 'native' vertex attributes like position, which our shaders assume to be floats, _**either make an exception to (1)**_, or explicitly cast from int to float in the shader.

I commented [here](https://github.com/mrdoob/three.js/pull/21606#issuecomment-1241238399) but to expand a bit on this comment - I'd prefer to not to have this kind of "magic" used internally (ie providing an exception only for `position`, etc). It feels like a recognition that this capability and flexibility is valuable while precluding users from being able to take advantage of it.
