### ISSUE TITLE
Improved Soft Shadow Mapping

### ISSUE THREAD

**Issue by zz85** [mrdoob/three.js#2159]
I always find myself reading up on interesting topics and then finding it way challenging for a noob. This time, its shadow mapping and so I'll try summoning expert ninja @alteredq for help on this. What we have currently for shadowing mapping is

1. hard shadow mapping - which is the simplest form of shadowing mapping
2. percentage-closer filtering (PCF) - a implementation of soft shadows by sampling a kernel (right now 3x3 which is 9 point)

I'm attempting/proposing 3 changes that would give better shadows
1. linear depth map - this helps to reduce shadow acne, due to improved precision
2. exponential shadowing mapping (ESM) - this does a box blur on the shadow map so that shadows are softer. i've read that the results might be good enough that SSAO is unnecessary.
3. percentage-closer soft shadows (PCSS) - uses a variable penumbra that give good performance with realistic soft shadows.

Starting off with change no. 1 - linear depth map, it currently seems like I would need the far/near of light to remapped the linear depth map? Currently I can map write linear values to the depth map, but it seems like I cannot pull it out from the shadow map :( See https://github.com/zz85/three.js/blob/d55bef9406a88d2195bdaec5e85e49bebc8b847a/src/renderers/WebGLShaders.js#L1122

note to @mrdoob avoiding merging this branch. contains experimental/dangerous/fail stuff.

references:
Shadow mapping in general - http://www.nutty.ca/?page_id=352&link=shadow_map#tabs-4
Integrating PCSS (with code) - http://developer.download.nvidia.com/whitepapers/2008/PCSS_Integration.pdf
Nvidia paper on PCSS - http://developer.download.nvidia.com/shaderlibrary/docs/shadow_PCSS.pdf
GLSL implementation of VSM, ESM, PCSS - http://code.google.com/p/dretchstorm/source/browse/base/glsl/deferredLighting_fp.glsl
GDC presentation of soft shadowing mapping techniques - http://developer.download.nvidia.com/presentations/2008/GDC/GDC08_SoftShadowMapping.pdf

possibly related issues: #1927

**Comment by tranek** [comment]
@zz85 Did you ever get a chance to implement VSM?

**Comment by pyalot** [comment]
doh :)

**Comment by wlalele** [comment]
:(

**Comment by mrdoob** [comment]
Yeah... Maybe @zz85 would like to give it another go now that the `WebGLRenderer` has been cleaned up though 😊
