### ISSUE TITLE
Editor: Video export doesn't work in Firefox

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#21603]
tried to record a video in the editor but it silently fails with this error (below) in console

**To Reproduce**

1. Go to editor project tab
2. Press the button to render the video
3. See error

***Live example***

* [editor](https://threejs.org/editor/)

**Expected behavior**

A video is rendered

**Screenshots**

![Screen Shot 2021-04-06 at 18 51 42 ](https://user-images.githubusercontent.com/242577/113880855-26785c00-97bc-11eb-9104-162e9161a521.png)

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Firefox
 - Three.js version: r127?

**Comment by Mugen87** [comment]
This seems to be a Firefox issue. I see the following error:
```js
ReferenceError: SharedArrayBuffer is not defined
```
It works in Chrome.

**Comment by Mugen87** [comment]
Maybe related: https://stackoverflow.com/questions/64962224/how-to-use-ffmpeg-wasm-in-firefox-without-getting-the-sharedarraybuffer

**Comment by makc** [comment]
Maybe related to related: https://github.com/ffmpegwasm/ffmpeg.wasm/issues/137#issuecomment-760114056

**Comment by mrdoob** [comment]
Sorry, maintaining one video renderer is hard enough. https://github.com/mrdoob/three.js/commit/71ffae30b3c75407d87696f726392215885dd8f9
