### ISSUE TITLE
Fix light helpers: change `updateMatrixWorld()` to `updateWorldMatrix()`

### ISSUE THREAD

**Issue by acu192** [mrdoob/three.js#21608]
Continuing the spirit of fixing issues like #19962 (see PR https://github.com/mrdoob/three.js/pull/19969 and https://github.com/mrdoob/three.js/pull/20224 as example fixes), we need to update these lines:

 - https://github.com/mrdoob/three.js/blob/0b608ec69ab413eb17eb9b93a2e780e9ab072f53/src/helpers/DirectionalLightHelper.js#L18
 - https://github.com/mrdoob/three.js/blob/0b608ec69ab413eb17eb9b93a2e780e9ab072f53/src/helpers/HemisphereLightHelper.js#L19
 - https://github.com/mrdoob/three.js/blob/0b608ec69ab413eb17eb9b93a2e780e9ab072f53/src/helpers/SpotLightHelper.js#L16
 - https://github.com/mrdoob/three.js/blob/0b608ec69ab413eb17eb9b93a2e780e9ab072f53/src/helpers/PointLightHelper.js#L15

**AS A BONUS:** There are a two related issues to fix:
1. Remove [this line](https://github.com/mrdoob/three.js/blob/0b608ec69ab413eb17eb9b93a2e780e9ab072f53/src/helpers/SpotLightHelper.js#L65) ... because it is already done in the constructor.
2. For both `DirectionalLightHelper` and `SpotLightHelper`, we need to do `this.light.target.updateWorldMatrix(true, false)` ... because currently `this.light` is updated but not `this.light.target`, so you get a bug because the helper shows the wrong direction for these lights (this happens in my app -- I have a runtime patch right now to fix this bug).

If this all sounds good to the maintainers, I will send a PR. Let me know.

**Comment by WestLangley** [comment]
`RectAreaLightHelper` must be added as a child of the light, but the other helpers must be added as children of the scene. (Unless this requirement has been changed since the inception of the helpers).

>Remove this line ... because it is already done in the constructor.

I don't think so. `.update()` is an external method.

>we need to do this.light.target.updateWorldMatrix(true, false)

Maybe. The the light target must be a scene element, currently. There has been a desire for many years to remove targets from the lights. I would prefer that route instead.

**Comment by acu192** [comment]
> helpers must be added as children of the scene

Yes, good point. So with that in mind, I agree we do not _need_ to change `updateMatrixWorld()` to `updateWorldMatrix()` here, because the behavior is the same either way. I'll close this issue.

> I don't think so. `.update()` is an external method.

Whatever we do, we should at least be consistent in all the light helpers. Currently only `SpotLightHelper` has this behavior in its `.update()`. I'll open a new issue to continue this discussion.

> Maybe. The the light target must be a scene element, currently. There has been a desire for many years to remove targets from the lights. I would prefer that route instead.

While removing targets from lights is a solution, I propose we still address the bug as the code stands today. I'll open a new issue to continue this dicussion.

**Comment by acu192** [comment]
> > helpers must be added as children of the scene

> Yes, good point. So with that in mind, I agree we do not need to change updateMatrixWorld() to updateWorldMatrix() here, because the behavior is the same either way. I'll close this issue.

Oh shoot, actually, no! The light (i.e. `this.light` inside the helper) is the object in question here. It does _not_ need to be added as a direct child of the scene.

Therefore I'm back to proposing that we change `this.light.updateMatrixWorld();` to `this.light.updateWorldMatrix(true, false);` as you've smartly already done in other places (@WestLangley). Thoughts?

**Comment by Mugen87** [comment]
Related #21427.

**Comment by acu192** [comment]
I'm closing this (again) and will instead contribute to the discussion @Mugen87 linked above (https://github.com/mrdoob/three.js/pull/21427).
