### ISSUE TITLE
Change in depthTest behavior breaks stencil buffer opertations

### ISSUE THREAD

**Issue by bsgbryan** [mrdoob/three.js#21634]
In versions 0.107.0+, the behavior of the depthTest flag on a Material seems to have changed in a way that breaks operations on the stencil buffer.

**To Reproduce**

1. Go to https://jsfiddle.net/50cysg9x/
2. Change **three@0.106.2** on line 28 to **three@0.107.0** (_or any higher version, including current; 0.127.0_)
3. See that the stencil shadow no longer renders correctly.

***Code***

The line in question is **171**: changing this line to `tintMaterial.depthTest  = true` changes the output but it is not correct. As far as I can tell, the stencil buffer operations, `buffer.setFunc (gl.ALWAYS, 0, 0xff)` etc, are executed whether `tintMaterial.depthTest` is `true` or `false`. They just don't contribute to the output in r0.107.0+.

***Live example***

* [jsfiddle](https://jsfiddle.net/50cysg9x/)

**Expected behavior**

All stencil buffer operations should be executed.

**Screenshots**

Please see live example above

**Platform:**

 - Device: [Desktop]
 - OS: [Windows, macOS]
 - Browser: [Chrome, Firefox]
 - Three.js version: [r0.107.0+]

**Comment by Mugen87** [comment]
> const buffer = r.state.buffers.stencil

I'm afraid it is not intended that user work directly with the depth, stencil or color buffers of `WebGLState`. It's a bit unfortunate that these are publicly accessible.

Have you tried to define the stencil state via the stencil properties of `Material`?

https://threejs.org/docs/index.html?q=materia#api/en/materials/Material.stencilWrite

**Comment by bsgbryan** [comment]
I have. That doesn't seem to have any effect.

**Comment by bsgbryan** [comment]
Something changed between r0.106.2 and r0.107.0 that introduced this issue. I looked through the changelog and the migration guide, but didn't see anything about the stencil buffer.

Is there an order of operations guide that may have changed? I looked though some of the post processing effects and saw that they used the stencil buffer in ways similar to what I'm trying. I attempted to mimic the patterns they were using but, again, that didn't seem to have any effect.

**Comment by bsgbryan** [comment]
> I'm afraid it is not intended that users directly work with the depth, stencil or color buffers of `WebGLState`.

Is there an abstraction I could work with that would accomplish the same thing?

**Comment by bsgbryan** [comment]
Here is the effect of using Material attributes: https://jsfiddle.net/md86ax1f/1/

**Comment by gkjohnson** [comment]
> Something changed between r0.106.2 and r0.107.0 that introduced this issue. I looked through the changelog and the migration guide, but didn't see anything about the stencil buffer.

If you look at the changelog the addition of stencil parameters is [listed as the third item in the r107 changes](https://github.com/mrdoob/three.js/releases/tag/r107).

> Here is the effect of using Material attributes: https://jsfiddle.net/md86ax1f/1/
> ...
> From what I can see, whether I use Material attributes or not, in r0.107.0+ the stencil operations simply don't contribute to the output.

You haven't set all the stencil options correctly for the effect you're trying to render. If you add the following options for `tintMaterial` you get a stenciled shadow effect:

```js
tintMaterial.stencilWrite = true;
tintMaterial.side = FrontSide;
tintMaterial.stencilFunc = NotEqualStencilFunc;
```

Also note that because this is a render order-dependent effect you'll want to set `tintMaterial.renderOrder` to a higher number to ensure the tint material renders last.

**Comment by bsgbryan** [comment]
Thank you for the explanation!

I think it would be helpful to call out in the documentation not to use the stencil buffer directly.

I saw the line about the addition of stencil parameters to materials when I was researching this initially. Nowhere is it said that the stencil parameters on materials are the _only way_ to interact with the stencil buffer. It's not just that the parameters were added, the existing direct interaction with the stencil buffer was broken. Nowhere that I can see in any of the documentation is that stated.

Again, to make sure no one else falls into this issue, I think an update to the documentation would be a good idea.

I'd be happy to do the update. Is there a guide to documentation standards/guidelines?

**Comment by Mugen87** [comment]
> Is there a guide to documentation standards/guidelines?

The only guideline about contribution in general is:

https://github.com/mrdoob/three.js/blob/dev/.github/CONTRIBUTING.md

> I'd be happy to do the update.

Clarifying things is of course welcome! 

The exposed buffers in `WebGLState` are in some sense a protected part of the API. E.g. the `MaskPass` class still works with it. However, as far as I know it was never intended that users work directly with this API. At least with `WebGPURenderer` such access will not be possible anymore.

**Comment by bsgbryan** [comment]
Thanks! I'll see what I can come up with documentation-wise!

**Comment by Mugen87** [comment]
Closing. Feel free to improve the documentation with PRs at any time!
