### ISSUE TITLE
[Doc] Whether the properties and methods inherited from the parent class can be listed in the document of a class.

### ISSUE THREAD

**Issue by puxiao** [mrdoob/three.js#21640]
... Although I know it's a lot of work.

**Comment by Mugen87** [comment]
Indeed. And that's the reasons why I not vote to do this. This approach would require a lot of manual effort and thus is error prone when things change. 

The documentation pages contain references like:

> See the base Material class for common properties.

Same for methods. Considering that the documentation is not generated, I think it's okay to go with this approach.
