### ISSUE TITLE
SideEffects false

### ISSUE THREAD

**Issue by DefinitelyMaybe** [mrdoob/three.js#21663]
Re package.json with `sideEffects = false`, there are a bunch of `/*@__PURE__*/` comments around the code that I think we can safely get rid of? would that be correct @marcofugaro ?

I can make a PR for it if so.

**Comment by Mugen87** [comment]
Related #16059.

**Comment by marcofugaro** [comment]
Not quite, `sideEffects: false` just tells the bundler that we don't attach anything to the window or any other global scopes.

It's up to the bundler to understand what to remove and what not to. From [the webpack tree-shaking guide](https://webpack.js.org/guides/tree-shaking/):

> Terser actually tries to figure it out, but it doesn't know for sure in many cases. This doesn't mean that terser is not doing its job well because it can't figure it out. It's just too difficult to determine it reliably in a dynamic language like JavaScript.


We can actually test this now, the `test-treeshake` script is testing importing three.js like if it was a npm module:

https://github.com/mrdoob/three.js/blob/c9350382c50e549c0d2960041448ffe652bbbd9b/test/treeshake/index.js#L1

If you remove all `/*@__PURE__*/` and run `npm run build && npm run test-treeshake` you can see the threeshaken bundle size actually increase.

**Comment by Mugen87** [comment]
It seems there was also some confusion about the `sideEffects` flag in #16059. According to my understanding, we can safely ignore it since the key for better tree-shaking is code refactoring (what we did in the last couple of month).

**Comment by marcofugaro** [comment]
@Mugen87 better to test its effects with common bundlers first.

I tested it months ago with webpack (just by removing the flag in `node_modules/three/package.json`) and it was tree-shaking correctly even without the flag. Have to check if it's the same with this next release.

**Comment by Mugen87** [comment]
Sounds good!

**Comment by DefinitelyMaybe** [comment]
thank you all
