### ISSUE TITLE
ShaderMaterial does not recompile with the proper `TexelToLinear` encoding when changing `.map`

### ISSUE THREAD

**Issue by Noobulater** [mrdoob/three.js#21672]
**Describe the bug**
Any Customs shaders built with ShaderMaterial do not respect the uniform 'map' texture encoding. There needs to be a way to change this on the material when the map changes otherwise we can't use some `ShaderChunk` includes which is super annoying. 

***Live example***
https://jsfiddle.net/noobulater/sxdog5y0/8/ - Read the comments on line 57

**Expected behavior**
We need a way to change the 'expected' texture encoding in order to allow ShaderMaterial to leverage ShaderChunk.
I'd expect something like a setter method like `.texelEncoding` or something specific to ShaderMaterial that would trigger a recompile when changed.

**Comment by Mugen87** [comment]
Sorry, but this is a user error. All what you have to do is to add `map` property to your material. The renderer can then derive the respective texel decoding function.

You also had a lot of unnecessary statements in your fiddle. Try it with: https://jsfiddle.net/egdtq6fs/2/

Please use the forum if you need more help.
