### ISSUE TITLE
Points and gl_PointSize incorrect render

### ISSUE THREAD

**Issue by ua4192** [mrdoob/three.js#21676]
**Describe the bug**
A Points object using a variable gl_PointSize in shader gets incorrect rendered.
I have a Points object with vertex point attribute size which is used in a shader to compute gl_PointSize
Sometimes a point that is occluded by other starts to be visible

**To Reproduce**

1.- Open the fiddle https://jsfiddle.net/d0nwj25r/
2.- Zoom In / Zoom out

***Live example***

https://jsfiddle.net/d0nwj25r/

**Expected behavior**
A point that is occluded by other point in a specific point of Camera should not change by zooming out.

**Screenshots**

Not  possible to attach screenshots from my office. But can be easily reproducible in the provided fiddle.

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, all]

**Comment by Mugen87** [comment]
Please ask this question at the [forum](https://discourse.threejs.org/) first. This is not a three.js bug.
