### ISSUE TITLE
Enhanced search: for methods and props

### ISSUE THREAD

**Issue by GmBodhi** [mrdoob/three.js#21670]
**Is your feature request related to a problem? Please describe.**

Right now, three.js docs search only searches the titles inside the search panel:
![image](https://user-images.githubusercontent.com/71921036/115098412-a2f20400-9f4d-11eb-9407-edfe8ac41806.png)

**Describe the solution you'd like**

Instead of that kind of search, it'll be better if we could search among the whole methods and props of an object, (ex: Similar results, suggestions, etc.) so that we can make the three.js Helper bot work better.
After inspecting the page, I've understood the search work on the basics of `list.json`.
Making that file bigger may not be a good idea, as this library's development is super active.
If we're doing the things in the list.json then, we may need to update the file accordingly.

**Describe alternatives you've considered**

For the bot, we're using puppeteer for crawling the site and getting results.

**Additional context**

`null`

**Comment by Mugen87** [comment]
Merging this into #19342.
