### ISSUE TITLE
Editor not showing equirect background

### ISSUE THREAD

**Issue by swoker** [mrdoob/three.js#21689]
**Describe the bug**

Uploading an equirect image to the ThreeJS Editor (https://threejs.org/editor/) does not show the image as the background anymore. This has worked at least until March 15th 2021.

**To Reproduce**

1. Open https://threejs.org/editor/ in anonymous tab
2. Select Background -> Equirect
3. Upload the example image below as an example
4. There are no errors shown and no errors in console or network tab (see below). The last image shows the image correctly in preview mode

**Expected behavior**

If I upload an image as equirect background, it gets shown as the background :)

**Screenshots**

![dome-showroom-medium](https://user-images.githubusercontent.com/130419/115527785-abba4100-a291-11eb-8608-17b13e42a7a4.jpg)
![image](https://user-images.githubusercontent.com/130419/115527761-a5c46000-a291-11eb-92a0-523eaff4756f.png)

**Platform:**

- Windows 10
- Chrome Version 90.0.4430.72 (Offizieller Build) (64-Bit), incognito mode

Also tried with a colleague who has the same problem:
- macOs Catalina 10.15.7 (19H524)
- Chrome Version 89.0.4389.128 (Offizieller Build) (x86_64)
- Safari Version 14.0.3 (15610.4.3.1.7, 15610)

**Comment by mrdoob** [comment]
Cherry-picked #21690 into `gh-pages`.
Should update in ~10 minutes. You'll need to clear the site's cache (or incognito).

**Comment by swoker** [comment]
works fine again, thank you very much :)
