### ISSUE TITLE
Add a Material.DefaultTransparent property

### ISSUE THREAD

**Issue by asbjornlystrup** [mrdoob/three.js#21682]
**Is your feature request related to a problem? Please describe.**
I'm working on a quite large 3D visualization application, and issues with render order and z-fighting etc. show up regularly. Eventually we decided to set transparent to "true" for all materials in the project so that we get more control over the render order ourselves; because when everything is transparent, the sorting is done in one list, and blend modes are more customizable.

An example of a specific problem that requires this solution is when you have a non-transparent decal object that "sticks" to a transparent object. Since it's a decal, I have depthWrite disabled (to allow additional decals on top of it etc.), and I have it render immediately after the transparent object. However, since the transparent object is forced to be rendered after the non-transparent one, the decal gets hidden behind the other mesh (since depthWrite is disabled). The solution was to set the decal to transparent even though it doesn't have any transparent parts. However, in some cases the object the decal sticks to is non-transparent, and in those cases the decal should also be non-transparent, otherwise the decal could cover up other meshes. Having the two separated render lists internal to three.js made things more complicated than it needed to in this case.

Another example is that our application has both a 2D and a 3D mode to view the world. 2D mode is an orthographic view of the world from above, and here we need to order things differently. E.g. we render all our huge "terrain meshes" first, and then the smaller "machinery" and "cable" meshes on top, since the cables and machines are the focus of the application. These two groups both have transparent and non-transparent objects. Currently we have every material set to transparent = true. This way, switching between 2D and 3D mode doesn't require complicated re-structuring of the scene graph or such.

**Describe the solution you'd like**

Our current solution is to manually set all materials to transparent in our code. However, I recently had a colleague not do this, and it took me some time to figure out that "transparent = false" on his material was the issue. To avoid trouble like this and to avoid having to explain the "transparent = true" rule to new employees, it would be nice with a Material.DefaultTransparent akin to Object3D.DefaultUp (which by the way has helped us greatly because we have Z and Y flipped in our application). I looked through the source code for materials and transparent was set to false directly there. Adding a Material.DefaultTransparent property to the Material base class would greatly help.

**Describe alternatives you've considered**

I have tried thinking of alternatives to the "transparent = true for everything" approach, but they seem to just complicate things. One solution was to have the "decals" copy the transparency of what they stick to. But sometimes (if the decal is the transparent one) it has to be the other way around. And in our application, the decal can be toggled on and off, and updating "transparent" accordingly adds a lot of extra code. As for the 2D mode problem, an alternative might be to re-structure the scene when switching between 2D and 3D mode. E.g. creating two subgroups of the scene, or splitting the scene into two. But it would make the code more complicated, and the switch between 2D and 3D would be slower, and other things that operate on the scene might need to have additional code for the two separate cases. Currently we just have a very simple scene traversal across our "transparent = true" scene that sets all render orders appropriately, and it's easy to understand, and doesn't require re-structuring.

Thank you for your consideration! I think this additional property can benefit larger projects and advanced users greatly, and it won't be in the way for other users.

**Comment by mrdoob** [comment]
Hmm... TL;DR? 😇

**Comment by asbjornlystrup** [comment]
Yes :) TL;DR:
Sometimes you want more control over render order, and the transparent/non-transparent render order separation makes this difficult. Setting "transparent = true" for every material manually solves this, but is error-prone and tedious, so a static "Material.DefaultTransparent" property that can be set to true (but is false by default) would be great, for the Material base class. Akin to Object3D's static DefaultUp and DefaultMatrixAutoUpdate.

(Sticking to the default "false" and keeping everything as non-transparent is not an option in our case, as alpha blending won't work.)

**Comment by mrdoob** [comment]
Thanks for the TL;DR 🙏

`Material.DefaultTransparent` static property seems like a good solution for this indeed.

**Comment by WestLangley** [comment]
To me, this suggestion seems like hack to accommodate a user who does not want two sort lists.

>Setting "transparent = true" for every material manually solves this, but is error-prone and tedious

With all due respect, I think that is an overstatement.

Also, how are the loaders going to accommodate `Material.DefaultTransparent`? Will they honor it, or override it?

Also, recall we have considered setting `depthWrite` to false by default for transparent materials. Where does that stand?

**Comment by RemusMar** [comment]
> recall we have considered setting depthWrite to false by default for transparent materials. 

That wasn't a good idea.
Just click on the stage and you'll see why:
https://necromanthus.com/Test/html5/head.html

**Comment by asbjornlystrup** [comment]
> Also, how are the loaders going to accommodate `Material.DefaultTransparent`? Will they honor it, or override it?
> Also, recall we have considered setting `depthWrite` to false by default for transparent materials. Where does that stand?
I don't exactly see why the Material.DefaultTransparent would have to affect anything other than two lines of code in the Material class itself? The code that does "this.transparent = false" would be turned into a "this.transparent = Material.DefaultTransparent" and "Material.DefaultTransparent = false" would be defined statically outside.

> To me, this suggestion seems like hack to accommodate a user who does not want two sort lists.

I guess the idea that DefaultTransparent is a means of getting one sort list is what feels like a hack, but just adding a default for that property shouldn't complicate things as far as I know. And I think the simplicity of the solution makes it easy to grasp, although you might have to get hinted at DefaultTransparent being a way to get one sort list from somewhere other than the variable name.

> With all due respect, I think that is an overstatement.

Already had a somewhat time-costly bug hunt in our application for it. I guess I will get used to it, but other colleagues will have to learn that "set transparent to true everytime" rule as well. It's not the most tedious work, but it does add complication.

**Comment by gkjohnson** [comment]
I tend to agree with @WestLangley here. This seems like something that should be dealt with by the application. Will we add global `Default*` settings for every material property?

> Already had a somewhat time-costly bug hunt in our application for it. I guess I will get used to it, but other colleagues will have to learn that "set transparent to true everytime" rule as well. It's not the most tedious work, but it does add complication.

If you have an easily misunderstood or forgotten concept (three.js or otherwise) it can be dealt with in PR reviews, tests, documentation, or even run time checks that are disabled in production. In my applications where we need a specific material configuration we try to ensure that all model loading and material instantiation goes through a common function so all expected material properties are initialized correctly and that mistakes are less easily made.

**Comment by WestLangley** [comment]
The reason for this proposed feature is to force a single sort list, and hence make it easier for the application to control rendering order.

If you want a single sort list, then perhaps we can add a renderer setting that will prevent separating opaque and transparent objects into separate lists.

If that is not acceptable to the managers, you still have a work-around for your use case. You could also consider having multiple scenes, rendering them sequentially.

**Comment by asbjornlystrup** [comment]
> If you want a single sort list, then perhaps we can add a renderer setting that will prevent separating opaque and transparent objects into separate lists.

Yes, an explicit solution like this would solve my problem too. If it's easy to implement and doesn't complicate other code, then I'd appreciate this solution just as much or even more than the other. Part of the reason for suggesting DefaultTransparent was that it seems to be just 2 lines of code, which also are quite disconnected from any other code. But this might be the case for the explicit solution as well, or at least somewhat close. A renderer property that explicitly prevents separation of sort lists would probably be more intuitive as well, at least in the variable name sense.

> If that is not acceptable to the managers, you still have a work-around for your use case. You could also consider having multiple scenes, rendering them sequentially.

Yes, setting transparent to true everywhere is okay, just somewhat tedious and error-prone as mentioned. Multiple scenes would be too constraining I think. We have two scenes to separate gizmos from real world meshes in our application, because they never intersect. But the "transparent = true" thing works better for more dynamic things like decals being attached and detached (no need to switch scenes).

**Comment by Mugen87** [comment]
I vote to close this issue. Sorting and rendering opaque and transparent objects separately is a proper default for a 3D engine. I would not introduce an additional complexity by making this process configurable since a) having a single render list is an edge case and b) it can easily be forced by setting the `transparent` material property to `true` everywhere.

I also share the concerns of https://github.com/mrdoob/three.js/issues/21682. Better to keep the policy simple and not introduce configurable default values for materials (and potentially other object types like 3d object or geometries).
