### ISSUE TITLE
OimoPhysics utils and wrappers

### ISSUE THREAD

**Issue by OleksiiMaksymovVBT** [mrdoob/three.js#21686]
Currently is a bit hard to use OimoPhysics with three.js. This issue is part of this PR #21679 
Actually you can assign us: @VBT-YTokan @OleksiiMaksymovVBT

**Comment by Mugen87** [comment]
Since the addition of `physics_oimo_instancing` was reverted, it's better to close this issue for now to avoid confusion. It can be reopened when the example is added again.
