### ISSUE TITLE
Svg rendering issues & possible fix

### ISSUE THREAD

**Issue by mwolf-eu** [mrdoob/three.js#21697]
Test svg won't render. (See attached)

Add the attached svg to webgl_loader_svg.  
Rendering throws two errors.

**FIX?:**
I didn't get through all the aHole code  in SVGLoader but adding the bolded checks worked for me.

Line 1914
**if ( !baseIntersections[ 0 ] ) return;**
const firstXOfPath = baseIntersections[ 0 ].point.x;

Line 2061
if ( **amIAHole  &&** ! amIAHole.isHole )

 Three.js version: r127

[test.svg.zip](https://github.com/mrdoob/three.js/files/6356797/test.svg.zip)

**Comment by Mugen87** [comment]
@Ttommeke Do you mind having a look at this? The runtime error happens in `SVGLoader.createShapes()`.

**Comment by Ttommeke** [comment]
Yes I'll do.

**Comment by Ttommeke** [comment]
@Mugen87 "Defs" and "Defs2" also don't work. I haven't looked into the problem with those yet, but could you recall that they where working with our new Loader? If they did, do you know of any changes that might have had an effect on this?

**Comment by Mugen87** [comment]
> "Defs" and "Defs2" also don't work.

Strange. They work fine for me. Are you testing with the latest version of the loader? Please try it with this link:

https://threejs.org/examples/#webgl_loader_svg

**Comment by Ttommeke** [comment]
Yeah, sorry i wasn't up to date with my dev branch.

**Comment by Ttommeke** [comment]
This issue happens when there is a path with only one point. We could filter those out because they are useless to display.
Or as @mwolf-eu suggests we could implement his change. But i fear then that; if there is another issue in the intersection code, it will slip under the radar.

**Comment by Ttommeke** [comment]
@Mugen87 Shall we add this svg to the test files?
@mwolf-eu May we add it to the test files?

**Comment by mwolf-eu** [comment]
You can add my svg.

**Comment by Mugen87** [comment]
> @Mugen87 Shall we add this svg to the test files?

That would be great!

**Comment by Ttommeke** [comment]
I believe this is fixed with the pull request.
