### ISSUE TITLE
SVGLoader Path decoding Bug & Fix

### ISSUE THREAD

**Issue by mwolf-eu** [mrdoob/three.js#21693]
**SVGLoader bug:  parseFloats() ~ line 893**

When a command in d has an exponent Eg:  "15 -1.1368683772161603e-13"
It gets decoded by the first parseFloats() regex as:
  [ "15", "-1.1368683772161603e", "-13"]  and not 
  [ "15", "-1.1368683772161603e-13"]  

Which leads to the second arg being set to -1.13... instead of something closer to 0.
 
**FIX**: I've changed the line 
var array = string.split( /[\s,]+|(?=\s?[+\-])/ );
to 
var array = string.split( /[\s,]+|(?=\s?(?<![eE])[+\-])/ )

Which adds a lookback to [+\-] and **won't** match if either is preceeded by 'e|E'.

It seems to work for me.

**Comment by Mugen87** [comment]
Um, it seems you are not using the latest version of `SVGLoader`. This code was refactored with `r126`.
