### ISSUE TITLE
IFCLoader with React

### ISSUE THREAD

**Issue by AJTech2002** [mrdoob/three.js#21696]
**Describe the bug**

I am implementing Three.JS into my React project and the one main issue I am having with the IFCLoader is that the web-ifc package that it is derived on top of utilises an `import.meta.url` statement, this is not yet supported in Webpack and hence cannot be compiled or run, after some experimentation I am able to remove the `import.meta.url` and replace it with the local file URL of that package and that works fine.

Are there any work arounds for this that you are aware of?

**To Reproduce**

1. Use Create-React-App to create a new React project
2. Import 'three/examples/jsm/loaders/IFCLoader'
3. Create an IFCLoader
4. Load in example IFC

**Expected behavior**

Expected behaviour would be that the IFCLoader is able to load IFC files without having to replace the 'import.meta.url' section in the `web-ifc.js` in the `node-modules/three/examples/jsm/loaders/ifc`.

**Platform:**

 - Device: Desktop

**Comment by mrdoob** [comment]
This has been fixed in `dev` already: #21683
