### ISSUE TITLE
Use of import maps is non-portable

### ISSUE THREAD

**Issue by kvark** [mrdoob/three.js#21695]
WebGPU examples started using import maps in #21364

**Describe the bug**

Import maps are not a standard yet, and using it means taking a hit on portability. I don't think this is required for ThreeJS examples to function, unless you are dropping support for non-Chrome browsers.
Of course, WebGPU is not a standard yet, either, but coupling it with yet another unrelated technology is not going to make it easier for anybody to ship (namely, Firefox and Safari, which [don't have](https://caniuse.com/import-maps) import maps right now).

**Comment by mrdoob** [comment]
Import maps simplify the development experience considerably and, considering all the work we have to do for supporting WebGPU, we have no other option than to sacrifice cross-browser support during this phase.

When we get closer to the WebGPU launch date we'll change the bare specifiers to relative paths if necessary.

**Comment by sedubois** [comment]
Can this be solved by a [shim](https://github.com/guybedford/es-module-shims) as Rails [does](https://github.com/rails/importmap-rails/blob/247b35aba3765d94e01cbeeb86a6c55fe5e33568/app/helpers/importmap/importmap_tags_helper.rb#L3)?

**Comment by mrdoob** [comment]
@sedubois https://github.com/mrdoob/three.js/pull/23163
