### ISSUE TITLE
Uncaught TypeError when accessing OrbitControls from unpkg.com 

### ISSUE THREAD

**Issue by neilgd** [mrdoob/three.js#21707]
With version 128, the following code:

```
<script type="module">
import * as THREE from 'https://unpkg.com/three@0.128.0/build/three.module.js';
import { OrbitControls } from 'https://unpkg.com/three@0.128.0/examples/jsm/controls/OrbitControls.js';
</script>
```
causes the following error:

```
Uncaught TypeError: Failed to resolve module specifier "three". Relative references must start with either "/", "./", or "../".
```

It worked fine in 127 though.

**Comment by GmBodhi** [comment]
Use https://cdn.skypack.dev/three instead

**Comment by Mugen87** [comment]
This is due to #21654.

As mentioned by @GmBodhi you have to use other CDNs like skypack. A respective fiddle looks like so:

https://jsfiddle.net/uwpcs2ob/

**Comment by x1911** [comment]
the loading is too slow, and it reload everytime. 

how can we use the faster version with this cdn?

**Comment by GmBodhi** [comment]
I think It'll be better to host it on your webserver for the time being.

**Comment by x1911** [comment]
@GmBodhi so loss the meaning of cdn, cdn should load it faster and save the bandwidth of own webserver

**Comment by donmccurdy** [comment]
Looks like unpkg has an experimental `?module` option you can add to the URL that allows it to work with three.js too:

https://discourse.threejs.org/t/importing-jsm-modules-using-explicut-urls-no-longer-works-for-basic-jsfiddle-examples-since-r128/25858/3

I'd be curious if you are seeing loading time differences between Skypack and Unpkg?

That said, yes, local development will allow you to work much faster. So far https://www.skypack.dev/ seems like one of the more user-friendly options. Then you can deploy to something with a CDN cache (e.g. [netlify](https://www.netlify.com) handles this automatically) when you are finished working locally.

**Comment by x1911** [comment]
today new error
![image](https://user-images.githubusercontent.com/8219031/117420023-c528e180-af4f-11eb-9cdd-c92f30b83726.png)

**Comment by Mugen87** [comment]
@x1911 Please demonstrate the issue with a live example. 

BTW: Just sharing a screenshot of the error is not helpful if you don't share more information about your setup.

**Comment by x1911** [comment]
@Mugen87 
https://jsfiddle.net/x1911/3x0rv8y9/

**Comment by donmccurdy** [comment]
@x1911 your example worked for me the first time I tried, but failed the next time. In my case it was OBJLoader that failed to load, and even directly accessing https://cdn.skypack.dev/three@v0.128.0/examples/jsm/loaders/OBJLoader.js shows an error. This appears to be a temporary problem with the Skypack CDN, and is reported on their status page here: https://status.skypack.dev/. Skypack claims that only development URLs are affected and their production URLs are fine, but I'm not sure what that means. The unpkg `?module` option may also be worth a try.

**Comment by Mugen87** [comment]
I'm not able to reproduce the issue. Seems Skypack fixed the issue on their side.

**Comment by x1911** [comment]
it works now, thanks  

@donmccurdy unpkg ?module option works now, seems also a better choice than skypack.dev


https://jsfiddle.net/x1911/ca5jLzyq/

**Comment by x1911** [comment]
this libs from skypack.dev seems not cached, it reload all files after refresh the webpage in several times, which is pretty normal in development.

and unpkg works very well like a normal CDN, load once, work month

**Comment by donmccurdy** [comment]
Reading the documentation at the top of this URL...

https://cdn.skypack.dev/three@v0.128.0/examples/jsm/loaders/OBJLoader.js

... there is a separate, optimized URL you can use for production. The default URL is probably meant for easier debugging and less aggressive caching.

**Comment by x1911** [comment]
![image](https://user-images.githubusercontent.com/8219031/118392916-a5d83580-b66e-11eb-89a3-73ace17a9f15.png)

the URL shows ...

i have tried the url from https://docs.skypack.dev/skypack-cdn/code/optimize-for-production
but it shows error and dosent work

and i have tried the pinned version, which Optimized for Production, but sometimes the url hash isnt the same
```
https://cdn.skypack.dev/pin/three@v0.128.0-SXSuUzgcVxHzCfF3m6eh/mode=imports,min/unoptimized/examples/jsm/loaders/OBJLoader.js

https://cdn.skypack.dev/pin/three@v0.128.0-mdxNJqSFIu40tgtjPy6F/mode=imports,min/unoptimized/

```

its not so dynamic for using await import() function,
