### ISSUE TITLE
WebGL Uniforms does not support array of 3D textures

### ISSUE THREAD

**Issue by skbizport** [mrdoob/three.js#21716]
WebGLUniforms does not seem to support array of sampler3D or usampler3D. A method like setValueT3D1Array is needed for this to work. 

Is this fix planned soon?

Regards

**Comment by mrdoob** [comment]
I was not aware that was possible.
Would you like to do a PR with the feature?

**Comment by Mugen87** [comment]
Out of curiosity: What is your use case for having an array of 3D textures?

**Comment by Mugen87** [comment]
I've searched a bit and I did not found a resource that proves you can use an array of 3D textures.

@skbizport Do you mind sharing some sort of reference or WebGL 2 demo that demonstrates this feature?

**Comment by skbizport** [comment]
Some context. I was using 3D textures embedded in structs and it worked fine on Linux versions of Chrome/Edge/Firefox, etc. In my program i was using arrays of such structs. However, ANGLE on windows reported errors. Apparently ANGLE cannot handle this and results in syntax errors, i.e. texture as a struct member. So, i was forced to convert code to array of textures. GLSL compiler itself did not complain about such declarations, however, sounds like webgl 2.0 does not support this. I was mistaken in thinking THREEJS is lacking this support.

Anyway, appreciate quick response on this.

Regards
sk
