### ISSUE TITLE
 computeFaceNormals not documented

### ISSUE THREAD

**Issue by wrnrlr** [mrdoob/three.js#21717]
I was trying to get raycasting to work on a plane geometry but couldn't get it to work.
Was trying out random suggestions I found on stackoverflow like add `plane.computeFaceNormals()`,
and sure enough it worked.

This method is not documented anywhere I could find.
Also, they said on chat normals are computed automatically in most cases.
This situation is unclear to me, like when are they computed,  and that is why  raised this question.

**Comment by GmBodhi** [comment]
I think it's not only about this Class Many classes like `CSS2DObject`, `CSS3DObject`, `CSS3DSprite`, `MapControls` etc. doesn't even have a documentation page. I think it'll be better to check the source of the Class and BaseClass for those pieces of information.

**Comment by Mugen87** [comment]
`computeFaceNormals()` is not relevant anymore since it was a method from the deprecated `Geometry` calls.

Please ask such help questions at the [forum](https://discourse.threejs.org/).
