### ISSUE TITLE
unreal_bloom_selective 's `gui` not work.

### ISSUE THREAD

**Issue by gonnavis** [mrdoob/three.js#21720]
**Describe the bug**

https://threejs.org/examples/?q=selective#webgl_postprocessing_unreal_bloom_selective 's `gui` not work.
If comment `event.preventDefault();`, the `gui` works, but don't know what other influences will be.

**To Reproduce**

1. Go to https://threejs.org/examples/?q=selective#webgl_postprocessing_unreal_bloom_selective
2. Click on `gui`'s parameters
3. See error

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [dev, r128]

**Comment by Mugen87** [comment]
It's best to remove the call of `preventDefault()`. There are multiple examples with `onPointerDown()` event listeners and  only `webgl_postprocessing_unreal_bloom_selective` seems to call `preventDefault()`.

**Comment by gonnavis** [comment]
Sure! My pleasure. 😇
