### ISSUE TITLE
examples/jsm/lines/LineSegmentsGeometry.js refactor typo

### ISSUE THREAD

**Issue by obsius** [mrdoob/three.js#21724]
Refactor has misnamed a method in master for: https://github.com/mrdoob/three.js/blob/master/examples/jsm/lines/LineSegmentsGeometry.js

Most recent commit to this file has renamed `fromLineSegments` to `romLineSegments`.

**Comment by Mugen87** [comment]
Good catch! 

Sorry, I've overlooked this bug when migrating the file to ES6. Let me immediately fix it.
