### ISSUE TITLE
THREE.CSS3DRenderer does not respect THREE.PerspectiveCamera.setViewOffset

### ISSUE THREAD

**Issue by marciot** [mrdoob/three.js#21723]
**Describe the bug**

I would like to use both the WebGLRenderer and CSS3DRenderer in an application, however that application calls "setViewOffset" to adjust the vanishing point of the drawing. This has the effect of moving the viewport as I desire, but the CSS3DRenderer layer does not shift.

**To Reproduce**

Please see the attached zip file.

[THREE.js Bug Report.zip](https://github.com/mrdoob/three.js/files/6378674/THREE.js.Bug.Report.zip)

**Expected behavior**

The setViewOffset should apply to the CSS3DRenderer.

**Screenshots**

This is what I expect:

![Example1](https://user-images.githubusercontent.com/6752228/116119747-fd8d0d80-a67b-11eb-8e5e-826f3eebe97c.PNG)

This is what I get:

![Example1](https://user-images.githubusercontent.com/6752228/116118426-860aae80-a67a-11eb-976a-27b7bcf47f64.PNG)

I have included a modified version of "CSS3DRenderer.js" that almost corrects the problem and which I used to generate the "good" image. It works by applying an additional transform to the domElement, like so:

```
				if (camera.view && camera.view.enabled) {
					const style = 'translate(' + (-camera.view.offsetX) + 'px,' + (-camera.view.offsetY) + 'px)';
					if ( cache.domElement.style !== style ) {
						domElement.style.transform = style;
						cache.domElement.style = style;
					}
				}
```

While this works when the CSS elements are at the center of the page, it works by shifting the entire parent DOM element and causes cropping of the CSS elements to happen on the edges of the screen when the camera is close up, as seen in this screen shot:

![Example3](https://user-images.githubusercontent.com/6752228/116119443-af780a00-a67b-11eb-8667-23a379f5e775.PNG)

I tried to work the translation into the cameraCSSMatrix, which seemed like a better place to do this, but I could not get it to work right. I am by no means an expert in CSS transforms. I would love it if someone could propose a better fix and incorporate it into THREE.js

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: dev

**Comment by Mugen87** [comment]
Live example demonstrating the issue: https://jsfiddle.net/5arugcwn/

**Comment by yomotsu** [comment]
Sorry for the delay. Ill take a look!

**Comment by yomotsu** [comment]
If we shift  `cameraCSSMatrix` with view offset, the [CSS `perspective-origin`](https://developer.mozilla.org/en-US/docs/Web/CSS/perspective-origin) should be shifted too.
(The default value of `perspective-origin` is `50% 50%`, which means looking from the center)

e.g:
```js

cameraElement.style.transform += `translate( ${ - _viewOffset.x }px, ${ - _viewOffset.y }px)`;
domElement.style.perspectiveOrigin = `calc( 50% - ${ viewOffset.x }px ) calc( 50% - ${ viewOffset.y }px )`;
```
see the result: https://jsfiddle.net/4cy5atvq/

---

However, if the camera is rotated, the calcination of `perspective-origin` will be complicated (sorry, I have no idea...😢).

I think the easiest way is adding one more div as the view.
```diff
└domElement
+  └viewElement
    └cameraElement
```

Then shift the viewElement with CSS translate 2d.
-> https://jsfiddle.net/7fcs93a2/

What do you think?
@Mugen87 @mrdoob

**Comment by Mugen87** [comment]
I'm unsure whether we should add this complexity to `CSS3DRenderer` or not just to support `setViewOffset()`. It's a very special use case that was never demanded so far...

**Comment by yomotsu** [comment]
Anyway, I can manage this by adding a div. if this feature is needed feel free to let me know.

**Comment by marciot** [comment]
> I'm unsure whether we should add this complexity to `CSS3DRenderer` or not just to support `setViewOffset()`. It's a very special use case that was never demanded so far...

Well, let me just chime in and say that as documented, "setViewOffset()" is supposed to allow multi-screen applications. This indeed is very niche. But AFAIK, there is no way in THREE.js to set the position of the vanishing point (which normally is in the center of the viewport). By accident, I found out I could use "setViewOffset()" to accomplish this. The situation where this is useful is when there is a floating toolbar that takes up a portion of the screen on the right. In this case, it is nice to be able to shift the origin to the left so things look centered:

![image](https://user-images.githubusercontent.com/6752228/118023581-ed7f5a00-b31a-11eb-871f-5d6c386d232f.png)

Using "setViewOffset" was the only way I was able to accomplish it.

**Comment by Mugen87** [comment]
Reopening this when more users request the feature.

**Comment by chrisraff** [comment]
@Mugen87 I am a user requesting the feature 🖐️

I have run into the same use case described by marcoit, I have floating content on the bottom of my view and I adjusted the vanishing point to be about slightly above where it normally would be, but now the CSS3DRenderer doesn't line up

**Comment by mrdoob** [comment]
@chrisraff What are you using `CSS3DRenderer` for? Text rendering or for interactive dom?

**Comment by chrisraff** [comment]
@mrdoob I'm using CSS3DRenderer for labels in the 3D view. To be clear, the floating content I mentioned at the bottom is in a normal div, outside of anything three.js interacts with

**Comment by jcarpenter** [comment]
> > I'm unsure whether we should add this complexity to `CSS3DRenderer` or not just to support `setViewOffset()`. It's a very special use case that was never demanded so far...
> 
> Well, let me just chime in and say that as documented, "setViewOffset()" is supposed to allow multi-screen applications. This indeed is very niche. But AFAIK, there is no way in THREE.js to set the position of the vanishing point (which normally is in the center of the viewport). By accident, I found out I could use "setViewOffset()" to accomplish this. The situation where this is useful is when there is a floating toolbar that takes up a portion of the screen on the right. In this case, it is nice to be able to shift the origin to the left so things look centered:
> 
> ![image](https://user-images.githubusercontent.com/6752228/118023581-ed7f5a00-b31a-11eb-871f-5d6c386d232f.png)
> 
> Using "setViewOffset" was the only way I was able to accomplish it. In this case, the vanishing point is roughly positioned at the smoke stack of the boat.

+1. This is exactly my use case as well.

**Comment by mrdoob** [comment]
@greggman Do you know is CSS3DRenderer can support this?

**Comment by mrdoob** [comment]
@yomotsu 

> Anyway, I can manage this by adding a div. if this feature is needed feel free to let me know.

Could you give it a go?

**Comment by yomotsu** [comment]
Okay! I'll take a look!
