### ISSUE TITLE
Using html canvas element as 2D text

### ISSUE THREAD

**Issue by alper21** [mrdoob/three.js#21738]
**Describe the bug**

I'm using html canvas element to get 2D text on screen but, it does not rendered at the same position in google chrome and safari. 

**Steps**

1. create a THREE.Texture object with canvas element.
2. create a THREE.SpriteMaterial object with this THREE.Texture object as its map.
3. create a THREE.Sprite object with this THREE.SpriteMaterial object
4. render this THREE.Sprite object.

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r127]

**Comment by Mugen87** [comment]
Please share a live example to demonstrate issue (https://jsfiddle.net/f2Lommf5/). It can then be reopened.

**Comment by alper21** [comment]
> Please share a live example to demonstrate issue (https://jsfiddle.net/f2Lommf5/). It can then be reopened.

https://jsfiddle.net/mjpx4hsf/1/

also i provide ss:
Google Chrome:
<img width="102" alt="googleChrome" src="https://user-images.githubusercontent.com/83345808/116876743-9cd67580-ac25-11eb-82ef-ef0e9ae8e863.png">

Safari:
<img width="104" alt="safari" src="https://user-images.githubusercontent.com/83345808/116876783-ac55be80-ac25-11eb-97a9-51e00570073a.png">

**Comment by Mugen87** [comment]
I'm unable to reproduce. If both windows in Chrome and Safari have the same size, the scene looks identical.

**Comment by mrdoob** [comment]
This is how it looks like in Chrome 90.0.4430.85 / MacOS 11.2.3 🤔

<img width="114" alt="Screenshot 2021-05-03 at 14 14 50" src="https://user-images.githubusercontent.com/97088/116880449-ef119980-ac19-11eb-8edc-7c62f312b1f0.png">

**Comment by alper21** [comment]
https://jsfiddle.net/mjpx4hsf/5/ 
I added middle line and decreased font size to see it clearly.

Also another ss, google chrome:
<img width="114" alt="googleChromeWithLine" src="https://user-images.githubusercontent.com/83345808/116893400-99e58000-ac39-11eb-9e61-fc9d18a1b4fe.png">

safari:
<img width="118" alt="safariWithLine" src="https://user-images.githubusercontent.com/83345808/116893434-a5d14200-ac39-11eb-8e77-f90c3a72adfd.png">

MacOS 11.2.3 / Google Chrome 90.0.4430.93 / Safari 14.0.3 (16610.4.3.1.7)

**Comment by mrdoob** [comment]
Chrome:

<img width="152" alt="Screenshot 2021-05-03 at 16 38 40" src="https://user-images.githubusercontent.com/97088/116898252-0d819000-ac2e-11eb-908d-67181466965e.png">

Safari:

<img width="165" alt="Screenshot 2021-05-03 at 16 39 25" src="https://user-images.githubusercontent.com/97088/116898320-20946000-ac2e-11eb-8344-284c14f14d35.png">

Firefox:

<img width="162" alt="Screenshot 2021-05-03 at 16 39 52" src="https://user-images.githubusercontent.com/97088/116898363-31dd6c80-ac2e-11eb-815c-dea1ec5761ad.png">

**Comment by mrdoob** [comment]
As you can see, browsers render text differently when using the Canvas2D API.
Unfortunately there is nothing we can do about this in Three.js
