### ISSUE TITLE
TransformControls setSpace() does not update gizmo transform [r128 regression]

### ISSUE THREAD

**Issue by davcri** [mrdoob/three.js#21731]
**Describe the bug**

TransformControls setSpace() does not update gizmo transform as it did in Three r127.

**To Reproduce**

1. Go to https://threejs.org/examples/?q=transform#misc_controls_transform
2. Select the cube
3. Rotate it by ~30 degrees on one axis
4. Press `Q` to toggle world/local space
5. Gizmos are not updated

This is a video of trying to move the rotated cube while changing between local and world space. The transformation is applied correctly, but the gizmos are not oriented correctly.

https://user-images.githubusercontent.com/6860637/116264406-8ee2a980-a77a-11eb-988e-f4c3c319f826.mp4

**Expected behavior**

Gizmos updated to match world/local space.

**Platform:**

 - Device: Desktop computer
 - OS: Linux Manjaro
 - Browser: Chrome 90
 - Three.js version: r128

**Comment by Mugen87** [comment]
Thanks for the detail bug report. Should be fixed with the next release.

**Comment by davcri** [comment]
HI @Mugen87 thanks for the quick fix! 

Actually I wanted to contribute by making a PR but I didn't manage to fix it by myself. Is there anyone in the ThreeJS community that I can ping in the future to ask for help/suggestions?

**Comment by Mugen87** [comment]
It's best to as help requests in the [forum](https://discourse.threejs.org/).
