### ISSUE TITLE
GLTF to USDZ converter doesn't work with my GLTF files

### ISSUE THREAD

**Issue by lilyntalmers** [mrdoob/three.js#21739]
**Describe the bug**

I am trying to convert GLTF to USDZ. For this I am using [misc_exporter_usdz](https://github.com/mrdoob/three.js/blob/dev/examples/misc_exporter_usdz.html). It works completely fine when I use the default DamagedHelmet.gltf file. But when I use my GLTF or GLB files it doesn't work. It doesn't even show the files.

**To Reproduce**

1. Go to  [misc_exporter_usdz](https://github.com/mrdoob/three.js/blob/dev/examples/misc_exporter_usdz.html)
2. Copy it to local machine
3. See error

***Live example***

[CodeSandbox](https://codesandbox.io/s/gltf-to-usdz-3kguu?file=/index.html)

**Expected behavior**

When I use my GLTF files it should be able to show them and convert them to USDZ file.

**Platform:**

 - Device: [Any]
 - OS: [Any]
 - Browser: [Any]
 - Three.js version: [Any]

**Comment by Mugen87** [comment]
It seems your model is DRACO compressed but you did not inject an instance of `DRACOLoader` to `GLTFLoader`.

Fixed sandbox: https://codesandbox.io/s/gltf-to-usdz-forked-z3g3m?file=/index.html

Do you mind trying the USDZ export with the fixed code?

**Comment by lilyntalmers** [comment]
Thanks you very much @Mugen87. I have tried the USDZ export with the fixed code and I can confirm that it works with both GLTF and GLB file(DRACO compressed).
