### ISSUE TITLE
OBJExporter not working correctly with InstancedMesh

### ISSUE THREAD

**Issue by Degubi** [mrdoob/three.js#21733]
**Describe the bug**

When exporting a scene that contains an InstancedMesh, the exported model is wrong.
It seems that none of the instances get exported, only the original geometry positioned at 0, 0, 0.

**Code**

https://github.com/Degubi/ThreeJS-InstancedMesh-Exporting

**Steps**

1: Clone the repo
2: npm install, npm run start
3: Open http://localhost:8080/
4: Press the export button
5: Check the .obj file

**Expected behavior**

All three cubes are in the exported .obj model

**Screenshots**

Original scene:
![image](https://user-images.githubusercontent.com/13366932/116288025-5c907680-a791-11eb-8e62-69eba7f9f277.png)

Result after export:
![image](https://user-images.githubusercontent.com/13366932/116287510-cceac800-a790-11eb-9aac-63c937efea02.png)

**Platform:**

 - Device: [any]
 - OS: [any]
 - Browser: [any]
 - Three.js version: [r128]

**Comment by Mugen87** [comment]
We decided in #18572 to only add support for `InstancedMesh` to an exporter if the respective format supports the concept of instancing. Please use the utility function [SceneUtils.createMeshesFromInstancedMesh()](https://threejs.org/docs/index.html#module-SceneUtils) before you export your scene.
