### ISSUE TITLE
SSAARenderPass does not respect the original view object of the PerspectiveCamera.

### ISSUE THREAD

**Issue by msimpson** [mrdoob/three.js#21735]
[`SSAARenderPass` unintentionally overwrites any original, user-specified `view` of the `PerspectiveCamera` to apply jitter.](https://github.com/mrdoob/three.js/blob/d4aa9e00ea29808534a3e082f602c544e5f2419c/examples/jsm/postprocessing/SSAARenderPass.js#L107)

This could be resolved by caching the original `view`, using it to translate each jitter, and restoring it afterward.

**To Reproduce**

1. Clone the repository.

2. Edit the [postprocessing ssaa example](https://github.com/mrdoob/three.js/blob/d4aa9e00ea29808534a3e082f602c544e5f2419c/examples/webgl_postprocessing_ssaa.html) to include line `cameraP.setViewOffset( width, height, width / 2, 0, width, height );` [between lines 93 and 94](https://github.com/mrdoob/three.js/blob/d4aa9e00ea29808534a3e082f602c544e5f2419c/examples/webgl_postprocessing_ssaa.html#L93).

3. Observe the lack off horizontal offset which should have occurred.

**Platform:**

 - Device: Any
 
 - OS: Any
 
 - Browser: Any
 
 - Three.js version: r128

**Comment by Mugen87** [comment]
I'm not sure `SSAARenderPass` supports an already existing view offset. In such a case, shouldn't the pass add a view offset to the existing offset instead of overwriting it?
