### ISSUE TITLE
Material Assignments missing under the Projects Menu

### ISSUE THREAD

**Issue by ArvindSharda78** [mrdoob/three.js#21745]
**Describe the bug**

In the earlier releases of Threejs Editor once could see all the materials used in the current scene, this is not available now. I am not sure which release it used to have. But I used it to assign same material to multiple geometries. Now i cannot do it, do let me know if this option has been moved to some different menu or so.

**To Reproduce**

1. Go to 'Three js editor'
2. Open a scene which have various materials
3. Click on Projects at the top right tabs
4. Earlier there used to be list of materials now i see only "VIDEO" option there

***Code***

```js
// code goes here
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hyok6tvj/)
* [jsfiddle-dev](https://jsfiddle.net/c5m1kazu/)

**Expected behavior**

I should see list of materials and also 'Assign' button

**Screenshots**

![image](https://user-images.githubusercontent.com/60726530/116503903-cbc2b380-a8d4-11eb-8251-3d7ad002a3a1.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [r128]

**Comment by Mugen87** [comment]
The material browser was removed with `r126`, see e5139eb6d699c7e17dab669771007eb971d6a0a4.

Please follow #21369 where a replacement is discussed.
