### ISSUE TITLE
"Exposure" control not working for sheen and reflectivity examples

### ISSUE THREAD

**Issue by sirxemic** [mrdoob/three.js#21758]
**Describe the bug**

The "exposure" control of the sheen and reflectivity examples doesn't do anything.

**To Reproduce**

Try changing the exposure. Nothing happens.

**Expected behavior**

The exposure to change.

**Additional information:**

The fix looked pretty simple: set `renderer.toneMapping`. Since all other "physical" examples use `ACESFilmicToneMapping`, I figured we should use that for these two examples as well. However, when you use that for the reflectivity example, the front side of the gem becomes basically 100% transparent, making it look very strange. So I wasn't sure how to deal with that: should the model be changed? It's material? Or should we use a different tone mapping?

**Platform:**

 - Device: [Desktop]
 - OS: [Linux]
 - Browser: [Chrome, Firefox]
 - Three.js version: [dev]

**Comment by Mugen87** [comment]
> Since all other "physical" examples use ACESFilmicToneMapping, I figured we should use that for these two examples as well. 

`webgl_materials_physical_sheen` does not use HDR env map so I don't think it's necessary to enable tone mapping. The exposure control can just be removed.

`webgl_materials_physical_reflectivity` should use tone mapping, even if the scene looks different. I think the new visual appearance is okay.
