### ISSUE TITLE
OBB.applyMatrix4 method forgets to scale the center point ?

### ISSUE THREAD

**Issue by shawn0326** [mrdoob/three.js#21753]
Why does OBB.applyMatrix4 not scale obb.center here? 

https://github.com/mrdoob/three.js/blob/6de8abafb4ddb8063279da38cfec663ee743ebf5/examples/jsm/math/OBB.js#L413

Is this a bug ? Looks like this would be more reasonable:

```js
obb.center.x *= sx;
obb.center.y *= sy;
obb.center.z *= sz;

obb.center.add(_vec3_1);
```

**Comment by Mugen87** [comment]
Since the `halfSize` vector is scaled, I don't think it's necessary to scale `center, too.

Please provide a live example that shows this issue if you are uncertain.

**Comment by shawn0326** [comment]
My reason is that if an `Object3D` (which origin point is not exactly in the center of the bounding box) and its `OBB` apply a same matrix, the result will be different if OBB is not scaled to the center. And this may cause confusion.

**Comment by Mugen87** [comment]
Can you please show this effect with a live example?

**Comment by Mugen87** [comment]
Closing until a live example is provided.

**Comment by shawn0326** [comment]
Sorry for the late reply, here is the live example: 

https://codepen.io/shawn0326/pen/ExZBLPW?editors=1001

As you can see, this example is from [webgl_math_obb.html
](https://github.com/mrdoob/three.js/blob/6de8abafb4ddb8063279da38cfec663ee743ebf5/examples/webgl_math_obb.html). And there are only two modifications in it:

````javascript
const size = new THREE.Vector3( 10, 5, 6 );
const geometry = new THREE.BoxGeometry( size.x, size.y, size.z );
geometry.translate( 0, 10, 0 ); // Modify the geometry so that the center is not exactly at the origin

// setup OBB on geometry level (doing this manually for now)

geometry.userData.obb = new OBB();
geometry.userData.obb.halfSize.copy( size ).multiplyScalar( 0.5 );
geometry.userData.obb.center.y = 10; // Modify the center point of obb similarly
````

Then, collision detection is completely messed up！This example can only be completely correct when the center of the geometry is exactly at the origin.

And I made a mistake too. In the calculation of OBB.applyMatrix4, it should be:

````javascript
this.center.applyMatrix4(matrix);
````

Then, everything goes right.

**Comment by Mugen87** [comment]
> geometry.userData.obb.center.y = 10; // Modify the center point of obb similarly

Sorry, but that is not right. The center of a OBB is always the center of the box. It can't be shifted at a different point like with meshes.

**Comment by shawn0326** [comment]
Ok, i see.

just BTW, although I noticed that there is no `OBB.setFromObject()` method, but i used it like this and got the problem: (-.-!)

````javascript
box3.setFromObject(object);
obb.fromBox3(box3);
````

**Comment by jonlo** [comment]
> @Mugen87 Sorry for the late reply, here is the live example:
> 
> https://codepen.io/shawn0326/pen/ExZBLPW?editors=1001
> 
> As you can see, this example is from [webgl_math_obb.html ](https://github.com/mrdoob/three.js/blob/6de8abafb4ddb8063279da38cfec663ee743ebf5/examples/webgl_math_obb.html). And there are only two modifications in it:
> 
> ```js
> const size = new THREE.Vector3( 10, 5, 6 );
> const geometry = new THREE.BoxGeometry( size.x, size.y, size.z );
> geometry.translate( 0, 10, 0 ); // Modify the geometry so that the center is not exactly at the origin
> 
> // setup OBB on geometry level (doing this manually for now)
> 
> geometry.userData.obb = new OBB();
> geometry.userData.obb.halfSize.copy( size ).multiplyScalar( 0.5 );
> geometry.userData.obb.center.y = 10; // Modify the center point of obb similarly
> ```
> 
> Then, collision detection is completely messed up！This example can only be completely correct when the center of the geometry is exactly at the origin.
> 
> And I made a mistake too. In the calculation of OBB.applyMatrix4, it should be:
> 
> ```js
> this.center.applyMatrix4(matrix);
> ```
> 
> Then, everything goes right.

Thanks for this workaround, it actually helped me, Im loading some 3d objects with translated geometry and center was not being calculated correctly.
