### ISSUE TITLE
Option to use 4 channel (32 bit) height map for `displacementMap`

### ISSUE THREAD

**Issue by ItaiAxelrad** [mrdoob/three.js#21759]
**Is your feature request related to a problem? Please describe.**
I would like to utilize additional color channels (32 bit) when creating a displacement map to increase level of detail in my renders. I believe currently,  only RGB 8-bit image is supported.

From wikipedia:
_"a standard RGB 8-bit image can only show 256 values of grey and hence only 256 heights. By using colors, a greater number of heights can be stored (for a 24-bit image, 2563 = 16,777,216 heights can be represented (2564 = 4,294,967,296 if the alpha channel is also used))."_

**Describe the solution you'd like**
I'd like to see the option to pass in a displacement map with more channels (32 bit). A solution has been suggested on [this StackOverflow thread](https://stackoverflow.com/questions/45979286/changing-three-js-displacement-map-shader-to-use-all-rgb-values-not-just-red) but I think others would benefit from an official implementation.

Current displacementmap_vertex.glsl:
```
transformed += 
	normalize( objectNormal ) * (
		texture2D( displacementMap, vUv ).x * displacementScale + displacementBias
	);
```

If I'm not mistaken, three.js uses the RGBA color representation (vs say ARGB), so this could be done something like so for three channels:

```
transformed +=
	normalize(objectNormal) *
		(
			texture2D(displacementMap, vUv).r * 256.0 * 256.0  +
			texture2D(displacementMap, vUv).g * 256.0  +
			texture2D(displacementMap, vUv).b 
		) * displacementScale + displacementBias;
```
Four channels:
```
transformed +=
	normalize(objectNormal) *
		(
			texture2D(displacementMap, vUv).r * 256.0 * 256.0 * 256.0  +
			texture2D(displacementMap, vUv).g * 256.0  * 256.0 +
			texture2D(displacementMap, vUv).b * 256.0 +
                         texture2D(displacementMap, vUv).a
		) * displacementScale + displacementBias;
```

**Describe alternatives you've considered**
It is possible to convert 4 channel height maps to single channel before using, but at the cost of accuracy and detail.

**Additional context**

An example of non vs colored height maps:

![6127bw](https://user-images.githubusercontent.com/51974602/116756986-6355fe00-a9ca-11eb-845d-93f63db0f987.png)
![6127](https://user-images.githubusercontent.com/51974602/116756989-63ee9480-a9ca-11eb-84cb-ca9f36fcadee.png)

**Comment by Mugen87** [comment]
Since this feature request is a bit specific, I do not vote to change the shader code but let the user patch the `displacementmap_vertex.` shader chunk via `Material.onBeforeCompile()` for now.

If more users come up with this, we can reconsider this approach. Or just share a solution based on node material.

**Comment by makc** [comment]
dont standard formats like png pre-multiply alpha (thus killing any precision gains)

**Comment by ItaiAxelrad** [comment]
@makc yes I believe so but there is still improved precision from 3 channel, right? I could be wrong 🤷
Fair enough @Mugen87 I will use `onBeforeCompile()` for now. Thanks for the quick replies!

**Comment by Mugen87** [comment]
Closing for now.

**Comment by WestLangley** [comment]
Something like this should work.

```js
const displacementMapChunk = [

	'#ifdef USE_DISPLACEMENTMAP',

		'transformed += normalize( objectNormal ) * ( unpackRGBAToDepth( texture2D( displacementMap, vUv ) ) * displacementScale + displacementBias );',

	'#endif'

].join( '\n' );

material.onBeforeCompile = function( shader ) {

	shader.vertexShader = shader.vertexShader
		.replace( '#include <common>', '#include <common>\n#include <packing>' )
		.replace( '#include <displacementmap_vertex>', displacementMapChunk );

};
```
