### ISSUE TITLE
Y component of Rotation does not operate in the same range as X and Z

### ISSUE THREAD

**Issue by prominentdetail** [mrdoob/three.js#21762]
When the rotation of an object changes, the Y component does not operate in the same range as X and Z

I created a jsfiddle showing the issue:
https://jsfiddle.net/45ho9xmL/ 1

I need to retrieve the value of Y in the same range as the X and Z does, but for some reason it only holds a value half of that and also in a strange pattern… It seems to have the peak of its value when 90/-90 degrees from the starting rotation, and then goes back down to 0 as it goes towards the 180 degree position.

https://discourse.threejs.org/t/y-component-of-rotation-does-not-operate-in-the-same-range-as-x-and-y/25849

**Comment by Mugen87** [comment]
Please discuss this question at the forum.
