### ISSUE TITLE
Feature Request: AR Image Tracking/Targets

### ISSUE THREAD

**Issue by FriskyBishop** [mrdoob/three.js#21771]
The AR functions on threeJS are great but Image Tracking would be super useful. 

Its available on AR js so it would be nice to have it on threejs.

**Comment by marcofugaro** [comment]
There won't be support for image tracking inside the library itself.

I think you're asking if there will be support for the WebXR Image Tracking API.

Example:
https://twitter.com/mrmaxm/status/1330232934192853003

**Comment by FriskyBishop** [comment]
yeah i guess thats what i was looking for but its a shame the WebXR Image Tracking examples just dont work on any device/browser I try them on. Oh well >.<
