### ISSUE TITLE
Introduce a Perlin/Simplex Noise class.

### ISSUE THREAD

**Issue by FarazzShaikh** [mrdoob/three.js#21773]
**Is your feature request related to a problem? Please describe.**

No, rather this feature is about adding something new that is useful.

**Describe the solution you'd like**

I'd like to work on an inbuilt Perlin/Simplex noise module that generates 2D and 3D noise for procedural animation, landscapes and maybe textures. This would be immensely useful as the current state of such modules in JavaScript is limited to small not well maintained projects on GitHub. I think including this in ThreeJS along with detailed documentation would be a good idea.

**Describe alternatives you've considered**

Alternatives include other not well maintained GitHub repositories with little to no documentation.

**Additional context**

I have been working on a Perlin noise algorithm and library (find it [here](https://github.com/FarazzShaikh/three-noise)), It would be noise to have something like this build into ThreeJS. I can help port my library over to ThreeJS and submit a PR for it if you'd be interested.

**Comment by Mugen87** [comment]
There are already two noise implementations in the repository:

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/math/SimplexNoise.js
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/math/ImprovedNoise.js (Perlin)

I think these are sufficient. It's okay to have other implementations in third-party repositories.
