### ISSUE TITLE
Line2 negative scale

### ISSUE THREAD

**Issue by arthur7921** [mrdoob/three.js#21772]
when i set a object(which instanced Line2).scale.x < 0, Line2 disappeared? is it normal?

***Live example***

* [jsfiddle-latest-release](https://codesandbox.io/s/lucid-browser-36v9e)

**Comment by arthur7921** [comment]
just change public/client.js lione 100: -1 to 1, you will see Lines

**Comment by Mugen87** [comment]
What is your use case for using a negative scale for lines?

**Comment by WestLangley** [comment]
Duplicate of #19629.

**Comment by WestLangley** [comment]
>What is your use case for using a negative scale for lines?

Oh, it would be nice to know the answer to that question. :-)

**Comment by arthur7921** [comment]
> > What is your use case for using a negative scale for lines?
> 
> Oh, it would be nice to know the answer to that question. :-)

draw a box line containes a object，and then mabey mirror the object

**Comment by arthur7921** [comment]
> Duplicate of #19629.

Thx,  sovle my problem!
