### ISSUE TITLE
Question / Documentation on example/fonts

### ISSUE THREAD

**Issue by hrieke** [mrdoob/three.js#21776]
Hi,

Could you update the Readmes in the example/fonts directory to include where the fonts have been retrieved from?

To start off with, the Droid Fonts are good.

Kenpixel, from look of things, appears to be from:
https://www.kenney.nl/assets/kenney-fonts
-or- 
https://opengameart.org/content/kenney-fonts

Licensed under the Creative Commons Universal 1.0 License

No idea what the Vera Bitstream-like License covers (Gentilis, Helvetiker, and Optimer), or who MAGENTA Ltd is.

The Google-ing parts of the license, points to:
https://en.m.fontke.com/foundry/10307/family/

But it would be great if you could verify that or offer a proper website address.

Thank you,

**Comment by hrieke** [comment]
Believe the Magenta fonts are from:
https://web.archive.org/web/20050528114140/https://ellak.gr/fonts/mgopen/index.en

Yes?

**Comment by Mugen87** [comment]
@tentone It seems `kenpixel.ttf` was added with #9867. However, the PR did not add a license file like for the font similar to `droid`. Is the suggested license of the OP the correct one?

@hrieke A license should be sufficient. I don't think it's necessary to state where the font was retrieved from.

**Comment by tentone** [comment]
@Mugen87  Booth the license and the source of the font are correct. The font is from kenney.nl.

**Comment by Mugen87** [comment]
> No idea what the Vera Bitstream-like License covers (Gentilis, Helvetiker, and Optimer), or who MAGENTA Ltd is.

These fonts were added ten years ago (cbd31ddf89fd7453444d9d6981312c7382a85cc5). I doubt it's possible to figure out the original source.

**Comment by mrdoob** [comment]
This just got published today:
https://github.com/components-ai/typefaces

**Comment by hrieke** [comment]
My research shows that the Magenta fonts are from the URL that I listed.
Interesting history, right up there with the Denmark font used in Boost in lore.
Thanks!

**Comment by Mugen87** [comment]
> My research shows

What does that mean? How did you come up with that URL?

**Comment by hrieke** [comment]
The licenses in the project and on the archived page are identical.
Downloading the fonts and reviewing the metadata stored using Exiftool, I see again the same license and vendor information, plus URL ties out as well, along with the history.
How did I come up with the URL?  I am really good at research.

**Comment by Mugen87** [comment]
See 12147ee9a1b0867e276d8375935419f89e22c8ea.

Should be okay now.
