### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by w7rus** [mrdoob/three.js#21789]
https://github.com/mrdoob/three.js/blob/d4aa9e00ea29808534a3e082f602c544e5f2419c/src/math/Matrix4.js#L124

Shouldn't this method rather called as copyRotation? since only this.elements are being assigned rather than a matrix that comes as a param.
Aka compare to extractBasis where the params and their values are being altered rather than self...

**Comment by WestLangley** [comment]
A _pure_ rotation matrix is computed from the given matrix `m`, hence the nomenclature `extractRotation` is used.
