### ISSUE TITLE
lights_physical_fragment was not correct when I switched to use WebGL1Renderer

### ISSUE THREAD

**Issue by jiywang3** [mrdoob/three.js#21799]
lights_physical_fragment is fine in the default WebGLRenderer. But when I switched to WebGL1Renderer, I got the following errors from chrome:

THREE.WebGLProgram: shader error:  0 35715 false gl.getProgramInfoLog Fragment shader is not compiled.
ERROR: 0:712: 'geometryNormal' : undeclared identifier
ERROR: 0:712: 'GL_OES_standard_derivatives' : extension is disabled
ERROR: 0:712: 'geometryNormal' : undeclared identifier
ERROR: 0:712: 'GL_OES_standard_derivatives' : extension is disabled
ERROR: 0:712: '=' : dimension mismatch
ERROR: 0:712: '=' : cannot convert from 'const highp float' to 'highp 3-component vector of float'

If I replaced lights_physical_fragment with the content from r103, it worked:
    var lights_physical_fragment = "PhysicalMaterial material;\nmaterial.diffuseColor = diffuseColor.rgb * ( 1.0 - metalnessFactor );\nmaterial.specularRoughness = clamp( roughnessFactor, 0.04, 1.0 );\n#ifdef STANDARD\n\tmaterial.specularColor = mix( vec3( DEFAULT_SPECULAR_COEFFICIENT ), diffuseColor.rgb, metalnessFactor );\n#else\n\tmaterial.specularColor = mix( vec3( MAXIMUM_SPECULAR_COEFFICIENT * pow2( reflectivity ) ), diffuseColor.rgb, metalnessFactor );\n\tmaterial.clearCoat = saturate( clearCoat );\tmaterial.clearCoatRoughness = clamp( clearCoatRoughness, 0.04, 1.0 );\n#endif";

**Comment by Mugen87** [comment]
I'm not able to reproduce: https://jsfiddle.net/x4q9fLpy/

Do you mind updating the fiddle so the runtime error occurs?

**Comment by jiywang3** [comment]
The error appeared in this page with the original three. r128: https://www.ncbi.nlm.nih.gov/Structure/icn3d2/index.html?mmdbid=1kq2&command=style%20proteins%20stick. But it worked with a fix of lights_physical_fragment: https://www.ncbi.nlm.nih.gov/Structure/icn3d2/full.html?mmdbid=1kq2&command=style%20proteins%20stick.

**Comment by Mugen87** [comment]
Sorry, but this is an application level issue. Please ask for help at the [forum](https://discourse.threejs.org/). Thanks!
