### ISSUE TITLE
All materials render black on some mobile devices

### ISSUE THREAD

**Issue by Supernuija** [mrdoob/three.js#21805]
**Describe the bug**

Testing on various mobile devices (phones and pads) indicates that depending on the drivers, GPU:s and browser versions three.js may render all objects pitch-black. Mobile device having the same GPU/processor may behave differently depending on the phone model and year; older may work while newer doesn't. The same device may operate correctly with Chrome but not with Firefox etc. 

**To Reproduce**

Since this is due to false positive value given by three.js checking on device capabilites, there is no easy way to reproduce it without the correct hw/sw combination. Using the simple test below, it can be reproduced on all devices that have this issue.

***Live example***

This will show a white cube on all devices: 
` var material = newTHREE.MeshPhongMaterial( { precision: 'mediump' } ); `
https://jsfiddle.net/f2Lommf5/6721/embedded/result
 
This will not show a white cube on some devices, rendering it pitch-black on some phones/pads:  
` var material = new THREE.MeshPhongMaterial( { precision: 'highp' } ); `
https://jsfiddle.net/f2Lommf5/6722/embedded/result

***Possible solution***

One solution to this would be using material precision: `mediump` on all mobile devices as a default value. This has first been suggested in 2018 by @Mugen87 mrdoob/three.js#14570. There has been some arguments against this as a solution, and therefore **perhaps a better solution to this would be some kind of automatic pre-testing whether the device really supports `highp` in practise or not, e.g. rendering a white test material sample and if it fails then defaulting material precision to `mediump`.** 

**Platforms (tested, but there can be more):**

 - Device: [Mobile]
 - OS: [Android]
 - Browser: [Chrome, Firefox]
 - Three.js version: r126 (min-126)

**Comment by mrdoob** [comment]
Another option would be to set `mediump` by default and update all the required shader code so the lighting doesn't break (https://github.com/mrdoob/three.js/issues/14570#issuecomment-408579871)

**Comment by mrdoob** [comment]
@Supernuija Would you like to give it a go?

**Comment by mrdoob** [comment]
@Mugen87

> It also seems to me that this issue a duplicate of #14570.

It sure is!
