### ISSUE TITLE
Three.JS WebGLRenderer fails to create when canvas is not initialized.

### ISSUE THREAD

**Issue by swittk** [mrdoob/three.js#21824]
**Describe the bug**
I'm using Expo React-Native with Three.JS, and just recently noticed a new bug that happens when I'm initializing the Three.JS renderer. ````TypeError: null is not an object (evaluating 'gl.canvas.width')````.

Same as mentioned in [this thread](https://github.com/expo/expo-three/issues/202).

I've pinpointed the source of the issue to be due to this change https://github.com/mrdoob/three.js/commit/f5c6b1c944a2dba2c7abb9fb780719a8fbe46ab0, specifically

The changing of the following lines in its initialization from
````
	const currentScissor = new Vector4();
 	const currentViewport = new Vector4();
````
to
````
 	const currentScissor = new Vector4( 0, 0, gl.canvas.width, gl.canvas.height );
 	const currentViewport = new Vector4( 0, 0, gl.canvas.width, gl.canvas.height );
````

I've tested by replacing these lines with the original ones (the Vector4 without parameters) and this issue is gone.

I'm filing this issue to ask if it will be ok if I create a pull request to change these lines to be
````
 	const currentScissor = gl.canvas ? new Vector4( 0, 0, gl.canvas.width, gl.canvas.height ) : new Vector4();
 	const currentViewport = gl.canvas ? new Vector4( 0, 0, gl.canvas.width, gl.canvas.height ) : new Vector4();
````
This change causes everything to work again.

**To Reproduce**

1. Go to https://snack.expo.io/@switt/threejs-renderer-initialization-bug-example
2. Use a mobile device running Expo Go client to scan the QR code to run it.
3. See Alert "Renderer failed", with error message of "null is not an object (evaluating 'e.canvas.width')"
4. Change package.json version of "three" to something like "~0.122"
5. See a spinning cube.

***Code***

```tsx
import { ExpoWebGLRenderingContext, GLView } from 'expo-gl';
...
      <GLView
        style={{ flex: 1 }}
        onContextCreate={async (gl: ExpoWebGLRenderingContext) => {
          const {
            drawingBufferWidth: width,
            drawingBufferHeight: height,
          } = gl;

          const renderer = new Renderer({ gl }) // This will fail
          renderer.setSize(width, height)
          renderer.setClearColor(sceneColor)
      }}
/>
```

***Live example***

* [expo snack](https://snack.expo.io/@switt/threejs-renderer-initialization-bug-example)

**Expected behavior**

- Renderer created successfully

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: Mobile Expo React-Native, SDK 39-41
 - OS: iOS and Android
 - Browser: Expo GLView React-Native
 - Three.js version: "^0.128.0" (not sure what last working version was, but 0.122 did work)

**Comment by Mugen87** [comment]
Wouldn't it be better to fix this issue in Expo? I mean why is the `canvas` property of `ExpoWebGLRenderingContext` `null` at this point?

**Comment by swittk** [comment]
I'm not sure, but according to the Mozilla docs ([here](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext)) the canvas property can be null when it's the WebGL context is not associated with a <canvas> element.

I'm not sure why the Expo team went with this decision of giving null as the value (maybe because it doesn't technically have a canvas element associated with it), and I'm aware this change may seem like simply adding redundant checks in the code. But the Expo code base seemed to work for years without a canvas.

There are currently 2 ways to fix this and I'd like to ask for your opinion on it.
1. Add check for undefined/null of the canvas property
2. Edit the Expo GLView initialization to have a canvas

For the 2nd choice I'd like to provide more info. From what I've inspected, after GLView itself is initialized it calls the ````onContextCreate```` callback as you see above here ([link](https://github.com/expo/expo/blob/ea03dc248a52d1e8bcc4de7f56990eabeea984a0/packages/expo-gl/src/GLView.tsx#L110)). Which it does after generating the WebGL context from the function here ([link](https://github.com/expo/expo/blob/ea03dc248a52d1e8bcc4de7f56990eabeea984a0/packages/expo-gl/src/GLView.tsx#L515)).
I see a line mentioning there that ```gl.canvas = null```, and seems canvas is never set in React-Native distributions (It however seems to be set in the Web version). (In older versions it seems ExpoWebGLRenderingContext doesn't even seem to have canvas defined).

Expo-THREE with Expo-GL is a package that a number of developers currently use to render 3D in React-Native. I believe this would be a breaking change to anyone updating Three in those projects.

If you firmly believe Expo GLView initialization should be changed, then could you recommend a workaround? I know simply doing ```(gl as any).canvas = { width: gl.drawingBufferWidth, height: gl.drawingBufferHeight }``` before calling any THREE functions is enough to get it to work on Expo, so maybe I could make a pull request to add a shim like that to the Expo code. But this seems like it might be prone to breaking in case there are any actual functions that may truly require a canvas object to be referenced at ```gl.canvas```.

However, I see other places in Three code checking for canvas and creating it or providing default values if it doesn't exist  (like [here](https://github.com/mrdoob/three.js/blob/5dd3e7c36dd2f8d14290db0b072945927a4bcea7/src/renderers/WebGLRenderer.js#L55)), so personally I believe adding checks for canvas should be the preferred method.

**Comment by Mugen87** [comment]
> However, I see other places in Three code checking for canvas and creating it or providing default values if it doesn't exist (like here),

I don't think you can use this code piece as an argument since the renderer always requires a canvas. If the user does not pass it as an argument, the renderer will create one.

**Comment by gkjohnson** [comment]
It would be good to understand why expo-gl sets the `context.canvas` field to null considering it [does seem to expect an HTMLCanvasElement to be passed in](https://github.com/expo/expo-three/blob/master/src/Renderer.ts#L5). Perhaps it's just an oversight in the webgl context implementation (I'm not really familiar with how expo works)?

But either way the MDN docs do state that in some unspecified scenarios `gl.canvas` can be null... @Mugen87  would it be better to use [gl.drawingBufferWidth](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/drawingBufferWidth) and [gl.drawingBufferHeight](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/drawingBufferHeight) instead? The viewport and scissor vector initialization are the only references to `gl.canvas` I see in the project.

**Comment by Mugen87** [comment]
I have used `canvas` since the default viewport values are the width and height of the canvas. Note that the MDN docs also state that `drawingBufferWidth` is not always equal `canvas.width`.

**Comment by gkjohnson** [comment]
> I have used canvas since the default WebGL viewport values are the width and height of the canvas. Note that the MDN docs also state that drawingBufferWidth is not always equal canvas.width.

Right but I don't think those docs really account for the subtlety in behavior when the system can't match the drawing buffer to the canvas size. Consider the following test that tries to create a webgl context from a canvas with a width and height that is larger than the browser can handle:

```js
canvas = document.createElement('canvas');
canvas.width = canvas.height = 20000;
gl = canvas.getContext('webgl');

// Chrome: null gl context is returned
// Firefox: resizes draw buffer, logs 20000, 10000
console.log( canvas.width, gl.drawingBufferWidth );

// Firefox: logs [ 0, 0, 10000, 10000 ]
console.log( gl.getParameter(gl.SCISSOR_BOX) );
```

So in chrome if you try to initialize a gl context to something too large it just fails. But in Firefox the draw buffer is resized and you can see that the default scissor box size matches the `gl.drawingBuffer*` value rather than the canvas dimensions.

Perhaps the most robust thing to do here is just initialize the scissor and viewport vectors using the returned `gl.getParameter` values, instead, which should also fix the compatibility issue with expo.

**Comment by Mugen87** [comment]
> Perhaps the most robust thing to do here is just initialize the scissor and viewport vectors using the returned gl.getParameter values, instead, which should also fix the compatibility issue with expo.

That sounds good! Let me file a PR.
