### ISSUE TITLE
USDZExporter does not work with multi-materials.

### ISSUE THREAD

**Issue by AndrePereira321** [mrdoob/three.js#21830]
When exporting an indexed geometry (with multiple groups and multiple materials), the exporter launches an error.

**Screenshots**

The received error
![image](https://user-images.githubusercontent.com/72091931/118164877-e42de480-b423-11eb-89de-90ed130b4160.png)

The offending line in USDZExporter
![image](https://user-images.githubusercontent.com/72091931/118164985-07589400-b424-11eb-9d90-48a94cd924c3.png)

**Platform:**

 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Three.js version: [dev, r128]

**Comment by Mugen87** [comment]
The issue is unrelated to indexed geometries. It's the missing multi material support that causes the runtime error.

As a workaround, do you have the chance to avoid multi material objects in your app?

**Comment by Mugen87** [comment]
@mrdoob One could implement this logic in `USDZExporter`. However I wonder if it's useful to have a reusable function which splits a multi material object into a group with multiple objects. Maybe in `SceneUtils`?

**Comment by coldbr3w-lab** [comment]
scene utils sounds like love. now how do i set up rapid deployment of host servers & processes of cmd ftps ipv6 varnish 6 proxy and hidden dns

**Comment by donmccurdy** [comment]
@coldbr3w-lab server configuration is unrelated to this javascript library; you may have better luck finding these answers on https://serverfault.com/.

**Comment by mrdoob** [comment]
#21847 should fix this crash.
