### ISSUE TITLE
WebXR squeeze event is not working in any of the three.js examples.

### ISSUE THREAD

**Issue by SrinivasPrabhu794** [mrdoob/three.js#21841]
Squeeze event does not work in WebXR projects anymore on desktop browsers. Tested on tetherable headsets like Oculus Rift S

1. Go to a VR example where the squeeze button is used for example: 'https://threejs.org/examples/webxr_vr_paint.html' on desktop chrome/edge browsers. (version 90+)
2. Click on 'Enter VR'
3. Press the squeeze button on the painter to reduce the size of the painting ball. Previously this worked very well but with the latest update, it does not.

**Expected behavior**

Squeeze event need to be invoked on press of squeeze button on the VR controller.

**Platform:**

 - Device: [Desktop (with Oculus Rift S) ]
 - OS: [Windows]
 - Browser: [Chrome 90+, Edge 90+]
 - Three.js version: [r127]

**Comment by Mugen87** [comment]
I can reproduce with a Quest 2 that the squeeze event does not work in `webxr_vr_paint.html`. It's not possible to change the size of the painter.

**Comment by SrinivasPrabhu794** [comment]
Is this got something to do with oculus's openxr implementation?

**Comment by Mugen87** [comment]
Sorry, it seems everything works as expected. The `squeeze` event is fired as expected. When pressing the button, you also have to increase/decrease the controller in order to change the size of the painter.

**Comment by SrinivasPrabhu794** [comment]
@Mugen87  Did you test it on a desktop browser with oculus link ? :)

**Comment by SrinivasPrabhu794** [comment]
> Sorry, it seems everything works as expected. The `squeeze` event does fire. But when pressing the button, you also have to increase/decrease the height of the controller in order to change the size of the painter.

Yes, I know that we need to move the pointer up or down to increase or decrease the painter size.

**Comment by Mugen87** [comment]
If it does not work on desktop, I suggest you report the issue directly Oculus.

**Comment by SrinivasPrabhu794** [comment]
Not sure If I need to report this to Oculus or the browser vendors :) maybe ill do both.

Thanks!
