### ISSUE TITLE
USDZ export is upside-down

### ISSUE THREAD

**Issue by elalish** [mrdoob/three.js#21867]
**Describe the bug**

Some GLB models seem to be exported upside-down by USDZExporter.

**To Reproduce**

1. Go to https://modelviewer.dev/examples/augmentedreality/#wall on an iPhone in Safari
2. Click on 'View in your space'
3. Note the tree shows up upside-down

***Code***

This is part of model-viewer, which creates a USDZ and pushes that blob into Quick Look.

**Expected behavior**

Tree is upright, like all the other AR examples on that site. This is the only model we've found so far with this behavior. 

**Screenshot**

![PlacingOnWall](https://user-images.githubusercontent.com/1649964/119061827-1ee6ce00-b98a-11eb-964b-6fce986b4a5b.png)

**Platform:**

 - Device: Mobile
 - OS: iOS
 - Browser: Safari
 - Three.js version: r128

**Comment by mrdoob** [comment]
Seems like there is something with the model. Apple's own `usdzconvert` can't convert it either:

<img width="366" alt="Screen Shot 2021-05-21 at 11 35 05 AM" src="https://user-images.githubusercontent.com/97088/119124498-a420c000-ba28-11eb-903a-95515070a45d.png">

**Comment by mrdoob** [comment]
Do you have any other file that exports upside down?

**Comment by elalish** [comment]
No, I don't, but USDZExporter isn't converting from glTF, it's converting from three's own scene graph. This is a perfectly valid scene graph that renders fine, so it ought to be possible to export it, right?

**Comment by elalish** [comment]
Also, that file passes the glTF validator, so even if Apple's software doesn't like it, I think it's their bug.

**Comment by mrdoob** [comment]
Seems like Reality Converter is able to handle it.

<img width="1012" alt="Screen Shot 2021-05-21 at 5 43 19 PM" src="https://user-images.githubusercontent.com/97088/119171119-0cd56000-ba5c-11eb-82b9-ab774376b297.png">

**Comment by mrdoob** [comment]
But the native viewer can't display it 😁
<img width="918" alt="Screen Shot 2021-05-21 at 5 44 52 PM" src="https://user-images.githubusercontent.com/97088/119171333-558d1900-ba5c-11eb-9c09-c6296b1f066c.png">

**Comment by mrdoob** [comment]
One of the parents have a scale of (-1,1,1) and the z rotated 180 degress.

<img width="767" alt="Screen Shot 2021-05-21 at 5 48 49 PM" src="https://user-images.githubusercontent.com/97088/119171690-cfbd9d80-ba5c-11eb-9add-fc1acaf73fd1.png">

The exporter is using `matrixWorld`. I don't understand why it ends up upside down.

https://github.com/mrdoob/three.js/blob/55f98ce4938b652d082d13f536217352a6f1adc6/examples/jsm/exporters/USDZExporter.js#L152

**Comment by mrdoob** [comment]
My guess is that, somehow, when decomposing the matrices into `position`, `rotation` and `scale` we end up in some sort of situation with a `rotation.z = - Math.PI` that we don't know how to compose back into a matrix.

I think these are the matrices int he gltb file:

"nodes" : [{"matrix" : [1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1], "mesh" : 0}, {"children" : [0], "matrix" : [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 585.6757049560547, -405.7232093811035, -1, 1]}, {"children" : [1], "matrix" : [0.001, 0, 0, 0, 0, 0.001, 0, 0, 0, 0, 0.001, 0, -69.34124944960212, 89.4197407716864, 0, 1], "name" : "SVG"}]

**Comment by WestLangley** [comment]
>One of the parents have a scale of ( - 1, 1, 1 ) and the z rotated 180 degress

That is equivalent to a scale of ( 1, - 1, 1 ).

**Comment by mrdoob** [comment]
@elalish I don't think we can do much about this one. Unless we stop using `Euler`...

**Comment by elalish** [comment]
What, killed by gimbal-lock? Yeah, definitely time to stop using Euler!

**Comment by mrdoob** [comment]
I'm not even sure we go through `Euler` actually....

Relevant pieces of code:
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js#L3577-L3583
https://github.com/mrdoob/three.js/blob/dev/src/core/Object3D.js#L119-L125

**Comment by WestLangley** [comment]
>Unless we stop using Euler...

I would not say we are using Euler. We are using quaternions. Euler rotation is provided for user convenience.

>What, killed by gimbal-lock?

Unless the `eulerOrder` is something other than the default `XYZ`, I do not see how this is Gimbal Lock issue...

Try a `+2` scale in the glb file instead of a `-1` scale and see what happens.

**Comment by elalish** [comment]
I've started using the three.js editor to export these USDZs; it's working in the Preview fine for me, but interestingly it is not upside-down like Quick Look, however the triangle winding order is definitely wrong so we're looking at the inside:
![image](https://user-images.githubusercontent.com/1649964/119579200-cbea8d80-bd72-11eb-92e2-9e1c5c2ffe8d.png)
Whereas in QuickLook it is upside-down but the winding order is correct. Definitely seems like several Apples bugs to me, and the mirroring transform problem is noted here: https://github.com/google/usd_from_gltf#compatibility

**Comment by elalish** [comment]
This won't repro anymore because I just fixed the model: https://github.com/google/model-viewer/pull/2427

Indeed, the inverting transform was the offender as best I can tell.

**Comment by WestLangley** [comment]
>I've started using the three.js editor ... however the triangle winding order is definitely wrong so we're looking at the inside:

@elalish three.js has special handling for reflection transforms. We assume the user does not want an inside-out model, so three.js reverses the winding order when the determinant of the world matrix is negative, in which case, the model _should_ render correctly.

**Comment by mrdoob** [comment]
Looks like this is a QuickLook issue after all.
