### ISSUE TITLE
TransformControls: Arrows misaligned in "world" space

### ISSUE THREAD

**Issue by diredev** [mrdoob/three.js#21860]
**Describe the bug**

The axis arrows of the TransformControls are aligned with the component's local coordinate system, even if the default "world" space is used. Dragging the arrows still works as normal, so the movement of the object does not match the drag direction of the arrows if the transformed object is rotated.

Could be related to #21840, but does not require any parent object or snap configuration.

**To Reproduce**

This can be easily reproduced using the [Transform Example](https://threejs.org/examples/#misc_controls_transform):
1. Switch to Rotate mode
2. Rotate your object in any way
3. Switch back to Translate mode -> Notice that the axes are aligned to the cube, even though we are in "world" space
4. Drag the red arrow -> Note that the object still moves on the global X axis
5. Change to "local" space -> Note that the arrows are still aligned the same (correct)
6. Drag the red arrow again -> Movement follows the arrow (correct)

***Live example***

See steps explained above and the [Transform Example](https://threejs.org/examples/#misc_controls_transform).

**Expected behavior**

I believe that the arrows should be aligned to world axes in "world" space. They also have done so in past versions, IIRC.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/33150734/118851561-2fd40880-b8d2-11eb-8f0a-7ccfcb277c88.png)

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome, Firefox
 - Three.js version: r128

**Comment by Mugen87** [comment]
Do you mind if coordinate space related problems are discussed in #21840? I'd like to mark this issue as a duplicate.

**Comment by diredev** [comment]
No, I don't mind. 👍

**Comment by Mugen87** [comment]
Sorry, this issue is actually a duplicate of #21731 (which is already fixed on `dev`) 👍 .
