### ISSUE TITLE
MeshPhysicalMaterial: .clearcoat -> .clearcoatIntensity

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#21877]
Discussion continued from #18684

I suggest renaming `MeshPhysicalMaterial.clearcoat` to `.clearcoatIntensity`. It is an intensity value in [0, 1].

**Comment by donmccurdy** [comment]
I think I'd prefer to see this keep the name "clearcoat". Other software and formats with the feature (Blender Principled Shader, Houdini Principled Shader, glTF, Autodesk Standard Surface) use either "clearcoat" or "coat" for the property name, always as a 0-1 range. 

There are reasons that artists might need to use values in between 0 and 1, but practically this represents a necessary ability transition smoothly between two opposite states, and not a spectrum of equally-useful intensity values. When somethings has a clear coat, it's value should generally be 1, and I worry that the term "intensity" gives the opposite impression.

**Comment by WestLangley** [comment]
>and not a spectrum of equally-useful intensity values ... its value should generally be 1

Then we should change `clearcoat` to a boolean, no?

>I worry that the term "intensity" gives the opposite impression

Then how is the strength/intensity/reflectivity of the clearcoat layer to be controlled?

As-coded, it _is_ an intensity. It is not "on-off".

**Comment by donmccurdy** [comment]
The value should _usually_ be one, but not always, and I've never seen a boolean checkbox for this value in another tool... maybe @bhouston has thoughts here?

**Comment by WestLangley** [comment]
>The value should usually be one

Well, not in this model. We can implement a different model if you want.

We have to have a way to control the reflectivity or strength of the clearcoat layer.

Our physical models were implemented years ago, so perhaps someone is interested in revisiting them.

**Comment by RemusMar** [comment]
> Then how is the strength/intensity/reflectivity of the clearcoat layer to be controlled?
> As-coded, it is an intensity. It is not "on-off".

From 3DS Max:
![3DSMax_clearcoat](https://user-images.githubusercontent.com/11772787/119341737-075e5c80-bc8c-11eb-9bb3-5ff3a7588eb7.png)

I would go with:
MeshPhysicalMaterial.clearcoat.intensity
MeshPhysicalMaterial.clearcoat.reflectivity
etc

**Comment by bhouston** [comment]
If we were to make any change, I would suggest following the nomenclature of glTF:

```
clearcoatFactor: [0..1]
clearcoatTexture: [optional texture, otherwise defaults to 1.0], modulates with clearcoatFactor.
clearcoatRoughnessFactor: [0..1]
clearcoatRoughnessTexture: [optional texture, otherwise defaults to 1.0], modulates with clearcoatRoughnessFactor.
clearcoatNormalTexture: [optional normal texture]
```

Source:
https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_clearcoat/schema/glTF.KHR_materials_clearcoat.schema.json

**Comment by RemusMar** [comment]
> If we were to make any change, I would suggest following the nomenclature of glTF:
>
> clearcoatFactor: [0..1]
> clearcoatTexture: [optional texture, otherwise defaults to 1.0], modulates with clearcoatFactor.
> clearcoatRoughnessFactor: [0..1]
> clearcoatRoughnessTexture: [optional texture, otherwise defaults to 1.0], modulates with clearcoatRoughnessFactor.
> clearcoatNormalTexture: [optional normal texture]

That glTF nomenclature is not even correct.
The clearcoat is a property of the material.
And intensity, roughness, etc are parameters of that property.
You'll find the correct inplementations in 3DS Max, Unreal or even BabylonJS:
https://doc.babylonjs.com/divingDeeper/materials/using/masterPBR#clear-coat 
```
var pbr = new BABYLON.PBRMaterial("pbr", scene);
pbr.metallic = 0.0;
pbr.roughness = 1.0;

pbr.clearCoat.isEnabled = true;
pbr.clearCoat.intensity = 0.5;
```

**Comment by donmccurdy** [comment]
Nested sub-properties (`material.clearcoat.intensity`) are one naming pattern, prefixed properties (`material.clearcoatIntensity`) are another. Neither is incorrect, but the latter is more consistent with e.g. `material.emissiveIntensity` and the many `.____Map` properties.

To date, we don't have any `.fooIntensity` properties _except_ those that are paired with a `.foo` property they modify, like emissive or envMap. I'd prefer that our long term goal be to align with other PBR models rather than creating new models and new names, so IMHO the term `.clearcoat` is more future-proof.

>  You'll find the correct inplementations in 3DS Max, Unreal or even BabylonJS:

Unreal engine [calls this "clear coat"](https://docs.unrealengine.com/4.26/en-US/RenderingAndGraphics/Materials/MaterialInputs/#clearcoat), as far as I can see, and states: "Amount of clear coat layer, 0 acts like the standard shading model, 1 is the full clear coat model."

**Comment by RemusMar** [comment]
material.emissiveIntensity is correct.
material.clearcoatIntensity is not!

IDidNeverLikeThisJuniorApproach.

but I will give up here.

**Comment by WestLangley** [comment]
OK, closing...
