### ISSUE TITLE
USDZExporter has broken textures

### ISSUE THREAD

**Issue by elalish** [mrdoob/three.js#21871]
**Describe the bug**

This glTF uses the variants extension, though I doubt this is the cause of its textures being scrambled in USDZ, since that doesn't do much to three's scene graph.

**To Reproduce**

1. Go to https://modelviewer.dev/examples/scenegraph/#variants on iOS Safari
2. Click on the AR button
3. Quick Look opens after auto-generating the USDZ, but the textures are random and greyscale.

***Code***

This is part of model-viewer

**Expected behavior**

The models renders more or less as it does on the web, and should reflect either of the chosen variants.

**Screenshots**

![C071D5E7-4116-4397-982B-200D6F1F63B6](https://user-images.githubusercontent.com/1649964/119171320-420c8e80-ba19-11eb-8e41-743016b1983f.png)

**Platform:**

 - Device: Mobile
 - OS: iOS
 - Browser: Safari
 - Three.js version: r128

**Comment by mrdoob** [comment]
This is already fixed in `dev`. (Probably thanks to #21852)

<img width="918" alt="Screen Shot 2021-05-21 at 6 07 19 PM" src="https://user-images.githubusercontent.com/97088/119173612-64c19600-ba5f-11eb-9ecd-f892dd47bc3b.png">

**Comment by elalish** [comment]
It should be either orange or purple.

**Comment by elalish** [comment]
Unless that's an issue of multiplying the texture by a color factor? I guess that's a known limitation of USDZ.

**Comment by mrdoob** [comment]
I think it is a limitation indeed. @kolodi may know...

**Comment by kolodi** [comment]
Theoretically, color can be applied to USDZ by using the bias of the texture fo a specific material. I have tried this approach but unfortunately it does not work, at least not in QuickLook. The only other solution is to multiply texture by a material color. I have already a working prototype for it. Gonna make another PR soon.

**Comment by elalish** [comment]
@kolodi You're my hero!

**Comment by kolodi** [comment]
> ![C071D5E7-4116-4397-982B-200D6F1F63B6](https://user-images.githubusercontent.com/1649964/119171320-420c8e80-ba19-11eb-8e41-743016b1983f.png)
 
Here we still have another problem with AO map. It does not want to be tiled separately from the diffuse map (as always a limitation related to QuickLook, it works well in other USD viewers). The only way to overcome this limitation as I can see now is to duplicate geometry 😖
