### ISSUE TITLE
Support for texStorage

### ISSUE THREAD

**Issue by skbizport** [mrdoob/three.js#21874]
Can we please add support for texStorage2D & texStorage3D for more efficient uploading of data (not images).  

WebGL 2.0 spec has a comment on this topic in section 3.7.6 Texture objects: "texStorage2D should be considered a preferred alternative to texImage2D. It may have lower memory costs than texImage2D in some implementations."  

This is also mentioned in MDN.

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices.
https://www.khronos.org/registry/webgl/specs/latest/2.0/

Some discussion on this on stackoverflow
https://stackoverflow.com/questions/63353873/how-to-handle-3d-texture-on-webgl2

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mrdoob** [comment]
Interesting...

How do you propose the API for it to look like?

**Comment by skbizport** [comment]
One possibility is DataStorageTexture, DataStorageTexture3D, DataStorageTexture2DArray. Another could be to pass additional parameters to existing class. E.g. 

DataTexture( data, width, height, format, type, mapping, wrapS, wrapT, magFilter, minFilter, anisotropy, encoding, storage (true|false)).

Thx

**Comment by Mugen87** [comment]
Would it be possible to use `texStorage2D()` automatically with a WebGL 2 rendering context? It's easy to check for a WebGL 2 rendering context in the rendere classes (via `capabilities,isWebGL2`).

**Comment by mrdoob** [comment]
@Mugen87 You mean when using `DataTexture`?

**Comment by Mugen87** [comment]
I thought the method could always be used when mipmaps are defined.

**Comment by mrdoob** [comment]
Right... After reading [greggman's explanation](https://stackoverflow.com/questions/63353873/how-to-handle-3d-texture-on-webgl2), seems to me that we should use `texStorage2D` and `texStorage3D` when possible indeed.

**Comment by mrdoob** [comment]
@DavidPeicho @mbredif do you guys agree?

**Comment by DavidPeicho** [comment]
Using `texStorage*` API whenever WebGL2 is used is the way to go I believe 👌

**Comment by mrdoob** [comment]
Something to be aware of is that, Chrome currently doesn't have optimised support of `texStorage*` for video textures.

**Comment by Mugen87** [comment]
I've started to experiment with `texStorage2D` today and want to clarify one thing that confused be at the beginning: 

`texStorage2D` is no 1:1 replacement for `texImage2D`. A call of `texImage2D` for uploading a single texture has to be replaced with a combination of `texStorage2D` and `texSubImage2D`. `texStorage2D` only allocates the memory whereas `texSubImage2D` actually defines the data. `texImage2D` does this all in one method call. 

Besides, the approach looks different depending on the use case in `WebGLTexture`. A texture with manual mipmaps just needs a single call of `texStorage2D` but multiple ones with  `texSubImage2D`. With `texImage2D`, one can treat all API calls uniformly. That makes the introduction of `texStorage2D` a bit trickier.
