### ISSUE TITLE
Object3D position coordinates in screen space.

### ISSUE THREAD

**Issue by jmcginty15** [mrdoob/three.js#21881]
**Is your feature request related to a problem? Please describe.**

I've been having an absolute hell of a time trying to project the positions of some objects from 3D world space into 2D screen space. The full story is [here on the Three.js forum](https://discourse.threejs.org/t/how-to-understand-vector3-project-and-ndc-space/26535). There is probably something I'm missing, but I keep thinking that getting an object's coordinates in screen space shouldn't be this complicated. The renderer has to have this information anyway to even show the objects on screen, so it seems like it ought to be readily available in a simple way.

**Describe the solution you'd like**

A property on Object3D that gives the object's coordinates in 2D screen space.

**Describe alternatives you've considered**

I've been trying to use the Vector3.project() method, but as described in the forum post linked above, this method has been giving me values that make no sense. I'm probably missing something, but the whole thing has been not even a little bit straightforward, and there has to be a simpler way.

**Additional context**

**Comment by Mugen87** [comment]
Sorry, but the existing methods in the math class should be sufficient for converting between different spaces.

Please keep using the forum for help requests.
