### ISSUE TITLE
Broken AOMap in USDZ with Transform2d

### ISSUE THREAD

**Issue by kolodi** [mrdoob/three.js#21906]
After introducing support for texture repeat and offset in #21852, the ambient occlusion map is repeated many times, despite the fact that we are setting the scale separately for each texture:
`float2 inputs:scale = ${ buildVector2( texture.repeat ) }`

**To Reproduce**

1. Have a model with tiled diffuse map and (obviously not tiled) AO map.
2. Export to USDZ
3. unzip USDZ archive and open USDA file
4. notice different scaling for each textures, diffuse texture may have scale major/minor from (1,1) and AO map should have a scale of (1,1)
5. Transfer USDZ file to iPhone/iPad
6. Open it in QuickLook and see AO map being tiled multiple times (probably as many as diffuse)

**Expected behavior**

AO map should not be tiled/repeated.

**Screenshots**

from #21871
![image](https://user-images.githubusercontent.com/28507944/119883060-01d07300-bf27-11eb-8951-139dfce3e014.png)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r129]

**Comment by donmccurdy** [comment]
If you hand edit the file to have the transform you expect, is it working in QuickLook? Based on the notes in https://github.com/google/usd_from_gltf#emulated-functionality-for-ar-quick-look, I'd thought it didn't support this:

> - Texture UV transforms [are not supported]. These are emulated by baking transforms into vertex UVs.
> - Multiple UV sets [are not supported]. 

^Since three.js _requires_ multiple UVs for AO, and QuickLook apparently doesn't support them, that's a bit of an obstacle. 😕

**Comment by elalish** [comment]
This all sounds great, but I wonder if we could have a simpler solution short-term? Like detect when the AO map is not going to work right and just disable it? The render above is a big problem, but without AO at all, it would be decent, if not ideal.

**Comment by kolodi** [comment]
> 
> 
> This all sounds great, but I wonder if we could have a simpler solution short-term? Like detect when the AO map is not going to work right and just disable it? The render above is a big problem, but without AO at all, it would be decent, if not ideal.

Looking in GLTF loader, it assumes that AO map should be on the second UV channel and if a geometry where there is a material with AO map does not have one, there is a workaround to create the second UV channel from the first one. The information about whenever the workaround was applied is unknown during the USDZ export. AO map won't work correctly in USDZ if it was initially on secondary UV channel by design. Maybe @Mugen87 knows how to extend the workaround in the way we can preserve the information about initial UV set used by AO map so we can use it to decide to exclude AO map from USDZ export. Please also correct me if any of the assumption I've made is wrong.

There is another deciding factor to exclude AO map from export - when diffuse map is repeated more than once. I will make PR with this workaround soon.

**Comment by mrdoob** [comment]
This should be now fixed: #25996
