### ISSUE TITLE
RuntimeError: index out of bounds   ---->    IFCLoader.js:54:15

### ISSUE THREAD

**Issue by cumalotrecords** [mrdoob/three.js#21907]
**Describe the bug**

Hello everybody i'm having this error while loading ifc files with three.js

**To Reproduce**

1. I'm running three.js on my local machine
2. i copied this https://threejs.org/examples/webgl_loader_ifc.html and i just edit the path for the file **"HERE"**

				//Setup IFC Loader
				const ifcLoader = new IFCLoader();
				ifcLoader.setWasmPath( 'jsm/loaders/ifc/' );
				ifcLoader.load( '**"HERE"**', function ( model ) {

					scene.add( model );
					render();

				} );
3. i get this error on the console

RuntimeError: index out of bounds   ---->    IFCLoader.js:54:15

***Code***

```js
	load( url, onLoad, onProgress, onError ) {

		const scope = this;

		const loader = new FileLoader( scope.manager );
		loader.setPath( scope.path );
		loader.setResponseType( 'arraybuffer' );
		loader.setRequestHeader( scope.requestHeader );
		loader.setWithCredentials( scope.withCredentials );
		loader.load(
			url,
			async function ( buffer ) {

				try {

					onLoad( await scope.parse( buffer ) );

				} catch ( e ) {

					if ( onError ) {

						onError( e );

					} else {

		------------>		console.error( e );         <-------------

					}

					scope.manager.itemError( url );

				}

			},
			onProgress,
			onError
		);

	}

```

**Platform:**

 - Device: [Desktop]
 - OS: [Windows 10]
 - Browser: [Firefox]
 - Three.js version: [lts]

**Comment by mrdoob** [comment]
Can you share the ifc file?

**Comment by mrdoob** [comment]
@agviegas any idea of what causes this?

**Comment by agviegas** [comment]
Hey, usually you have two ways to load an IFC: either loading it with an HTML input element or loading it from a local folder within the project, as shown in the [official example](https://threejs.org/examples/webgl_loader_ifc.html) 🤔 I'm not familiar with the method you are using to load the IFC, but I'd say that you have to make sure that you are giving the load function exactly the same input as when using the other two methods.

**Comment by cumalotrecords** [comment]
@mrdoob i tried with other links like this [http://openifcmodel.cs.auckland.ac.nz/_models/202103162102_cira.ifc](http://openifcmodel.cs.auckland.ac.nz/_models/202103162102_cira.ifc)  from [http://openifcmodel.cs.auckland.ac.nz/](http://openifcmodel.cs.auckland.ac.nz/) and it works 
the problem is when i try to reach link of sources from my website
i guess this is just a problem of mine and i just have to fix this somehow... it is not fault of three
but the very weird thing is that 2 days ago it workerd also with my website's link so probablly i changed some settings but i cannot understand the cause of this error

@agviegas  i'm gonna check [dropbox example](https://github.com/agviegas/web-ifc-viewer/blob/c73e3895a4636ce0fd041283a93c5bd2ab6e8bd0/viewer/src/IO/dropbox.ts#L27) now and i hope this will help
anyway i'm just putting the link of an ifc file in ifcURL of ifcLoader.load( ifcURL , function ( model ) {...}) ... the pity is that the firsts times i tried it worked  :(

i leave this open just in case you have some good idea with this specifications but i think we can also close this cause it is not three's fault

thanks for the for your works and advices in the meanwhile
