### ISSUE TITLE
load and save stl files in node.js

### ISSUE THREAD

**Issue by lucaskmiyazaki** [mrdoob/three.js#21915]
I am trying to apply the changes the user makes in the model in the frontend to the model in stl that is in the backend. The changes the user is allowed to apply are rotate, translate and scale. One idea was to transfer the stl via json file, but the files are too big. The other idea was to just pass the parameters and make all the modifications via node. Is it possible to load the stl in node, use three functions to modify my model and then save it to the filesystem?

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
