### ISSUE TITLE
Transmission anti aliasing

### ISSUE THREAD

**Issue by Lipacinp** [mrdoob/three.js#21913]
Hello everyone,

**Describe the bug**

I've updated ThreeJS in my project and test the new implementation of transmission.

I don't know if this is a bug or if it is a limitation of WebGl. I noticed that all objects behind an object with transmission to 1.0 no longer have anti-aliasing.

***Live example***

* [jsfiddle](https://jsfiddle.net/Lucnrbta/)

![image](https://user-images.githubusercontent.com/83960969/119957858-c1163f80-bfa2-11eb-8803-66d7c53569cb.png)

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome, Firefox
 - Three.js version: r129

**Comment by mrdoob** [comment]
It sure is a limitation of WebGL 1...
But we should be able to use `WebGLMultisampleRenderTarget` in WebGL 2 mode.

/cc @takahirox

**Comment by takahirox** [comment]
Like this (until we switch to "copy the framebuffer to texture")?

```javascript
const renderTargetType = _antialias && capabilities.isWebGL2 ?
  WebGLMultisampleRenderTarget : WebGLRenderTarget;
_transmissionRenderTarget = new renderTargetType( 1024, 1024, {				 
    ...
} );
```

**Comment by mrdoob** [comment]
If I remember correctly, WebGL2 doesn't need power of two to to get mipmapping, right?
So I guess we should be able to create a rendertarget that has the same size as the framebuffer?

**Comment by takahirox** [comment]
> If I remember correctly, WebGL2 doesn't need power of two to to get mipmapping, right?

I think it's right.

> So I guess we should be able to create a rendertarget that has the same size as the framebuffer?

For the quality, it should be good. But I'm not sure if it's good for the performance..

**Comment by Lipacinp** [comment]
Hello @mrdoob, @takahirox !

It looks like with the latest version of THREEJS (131), the problem is back again. It seems I can't reopen this issue. Should I open a new one ?

It could be the new Transmission features that broke the patch or something else, I can't say for sure.

**Comment by mrdoob** [comment]
Seems to be working fine here:

<img width="493" alt="Screen Shot 2021-08-15 at 7 10 23 PM" src="https://user-images.githubusercontent.com/97088/129488224-5ef84d80-c40f-46c7-b0b0-c6f4e978a957.png">
