### ISSUE TITLE
ShaderMaterial/SpriteMaterial does not work in WebXR immersive mode

### ISSUE THREAD

**Issue by SrinivasPrabhu794** [mrdoob/three.js#21914]
ShaderMaterial/SpriteMaterial does not work in the WebXR immersive mode.  We have a WebXR application that worked well up to r127. Today when I upgrade to 0.129.0 I get this error because of my custom object/material. If I create the object/shadermaterial or spritematerial not at startup but at a much later at runtime (after loading a gltf object).

1. Create a WebXR example with an object and ShaderMaterial class
2. Enter VR
3. You will see an error that looks like this:

![image](https://user-images.githubusercontent.com/817112/119976259-79a8a700-bfd4-11eb-995e-c18691fa37c9.png)

Likely broken because of the change at these commits ?
https://github.com/mrdoob/three.js/commit/f2e4e0fe94d927ed9712f1189bd66d20992f061e#diff-fc94afb5da943fea9e01a4a16adf82b5433aa6d61af5855f296158a98ed4dcfd

https://github.com/mrdoob/three.js/pull/21117/commits/acb1dd46ac9ff7208070c86726984aebce11a27f

**Expected behavior**

ShaderMaterial should have an onBuild method which it inherits from the base Material class. Although it does have the onBuild() method available at creation time, during render() the method seems to vanish after pushing to it the renderListStack @ line 24504 

**Screenshots**

![image](https://user-images.githubusercontent.com/817112/119976259-79a8a700-bfd4-11eb-995e-c18691fa37c9.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [r128,r129]

**Comment by Mugen87** [comment]
Please continue the discussion of the following topic at the forum. It seems the suggested solution solved the issue of the OP.

https://discourse.threejs.org/t/uncaught-typeerror-material-onbuild-is-not-a-function/26071

**Comment by SrinivasPrabhu794** [comment]
The link helped, thank you.
