### ISSUE TITLE
FPS Example (Capsule and Octree)

### ISSUE THREAD

**Issue by daarong** [mrdoob/three.js#21921]
The [FPS example](https://threejs.org/examples/?q=fps#games_fps) (capsule collision against octree) seems to reliably fail, the player can walk through walls.

1. Open [FPS example](https://threejs.org/examples/?q=fps#games_fps)
2. Walk into wall (keep pointing and pressing into wall until you teleport through).
3. Seems more likely on flat ground and walls orthogonal to x-z axes.
4. Seems more likely when running lower frames per second (lower your machine speed or otherwise drop frames per second by whatever means)

I uploaded a quick [video](https://www.youtube.com/watch?v=eX7IpSn81BU) of walking through two walls.

 - Device: Desktop
 - OS: Win10
 - Browser: Chrome
 - Three.js version: r129

**Comment by daarong** [comment]
I noted the velocity does not reduce when you hit walls, rather you simply stop moving based on the collision test. I 'corrected' this problem by adjusting the velocity based on the collision result, that is

	const deltaPosition = playerVelocity.clone().multiplyScalar( deltaTime );
	playerCollider.translate( deltaPosition );

	playerCollitions();

	/// MY ADDITION
	if (deltaTime > 0)
		playerVelocity.subVectors(playerCollider.end, camera.position).multiplyScalar( 1.0 / deltaTime );

	camera.position.copy( playerCollider.end );

I think this prevents the run-through-wall effect, though more likely it has only much reduced the chance of it happening. This also has the (negative?) effect of going up stairs more slowly.

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/21755#issuecomment-842570740

I think we should consider to completely remove the example since the collision detection is indeed not reliable (and thus not usable for a real app).

**Comment by felixmariotto** [comment]
@Mugen87 The problem would be easily fixed if the loop ran substeps for collision detection. It's a simple and common trick to avoid this kind of issue, even an engine like Cannon seem to run [10 substeps by default](https://schteppe.github.io/cannon.js/docs/classes/World.html#method_step).

We could just change [the example render loop](https://github.com/mrdoob/three.js/blob/d39d82999f0ac5cdd1b4eb9f4aba3f9626f32ab6/examples/games_fps.html#L361-L377) like so : 

```javascript
const STEPS_PER_FRAME = 10;

function animate() {

	const deltaTime = Math.min( 0.1, clock.getDelta() ) / STEPS_PER_FRAME;

	for ( let i=0 ; i<STEPS_PER_FRAME ; i++ ) {

		controls( deltaTime );

		updatePlayer( deltaTime );

		updateSpheres( deltaTime );

	}

	renderer.render( scene, camera );

	stats.update();

	requestAnimationFrame( animate );

}
```

**Comment by daarong** [comment]
Yes, substeps should certainly help. I'll probably just hack this... add a raycaster check on every capsule movement to cancel the movement if they go through a wall (not worrying about small objects). The hack is both lighter weight and guaranteed to not allow wall warping.

**Comment by Mugen87** [comment]
@felixmariotto I think it's okay to add this code snippet although I personally consider it as a hack. There are other approaches for restricting player movements which are not that fragile.

**Comment by felixmariotto** [comment]
@Mugen87 sure, I will file a PR 😊
