### ISSUE TITLE
Suggestion: Add children param to Group constructor

### ISSUE THREAD

**Issue by ieskudero** [mrdoob/three.js#21920]
**Is your feature request related to a problem? Please describe.**

When using `Group` we always end up using the same pattern:

```
//create group
let group = new Group();

//create meshes
let m1 = new Mesh( geom, mat );
let m2 = new Mesh( geom, mat );
...

//add meshes
group.add( m1 );
group.add( m2 );
...

return group;
```
I think this can be simplified if `Group` accepted children as parameter in constructor, as `Mesh` accepts `Geometry` and `Material`.

**Describe the solution you'd like**

Using the proposed change the code would look like:

```
//create meshes
let m1 = new Mesh( geom, mat );
let m2 = new Mesh( geom, mat );

return new Group( [ m1, m2, ... ] );
```

I think `Group` should accept children as parameter since its purpose is precisely that, having children. And it would simplify the code.

**Comment by Mugen87** [comment]
Are you aware that you can do this:
```js
group.add( m1, m2 );
```
This works with an arbitrary number of arguments. Against this backdrop, I do not vote to change the API.

**Comment by ieskudero** [comment]
I wasn't aware of that way of adding children, thank you!

Anyway, I see a children parameter logical in `Group`, since its purpose is precisely that. It would be coherent with all the other objects (having their main parameters added in constructor), wouldn't break anything and would simplify the code.

**Comment by Mugen87** [comment]
If we do this, users could expect the constructor of `Bone` accepts an array with child bones, too. Simply because in many cases bones do have children.

I think it's better if 3D objects only accept a geometry and/or material parameter. And that's it.

**Comment by ieskudero** [comment]
With all due respects, I can't see why the comparison with `Bone`. If any, the comparison should be done with `Skeleton`, which, in fact, has `Bone` as constructor parameter.
A group of bones = `Skeleton`
A group of object3d = `Group`

**Comment by Mugen87** [comment]
A skeleton is no 3D object. I was referring to the semantics of `Object3D` and its derivatives.

**Comment by ieskudero** [comment]
I really can't follow you.

You compare `Group` with `Bone`, because both of them are `Object3D`, so we can't compare it with `Skeleton`. That's OK.

But you stated that it is better if 3d objects only accepts a geometry and/or material, which `Bone`, been an Object3D, doesn't.

I understand that this can be a matter of preferences, and it is OK, So I'm closing this issue. We don't gain anything by arguing eternally :)
