### ISSUE TITLE
WebGLLights references to missing UniformsLib constants for rect area lights

### ISSUE THREAD

**Issue by stopyransky** [mrdoob/three.js#21926]
It's not a bug but an inconsistency in the code that hopefully is not causing a bug...

**Describe the bug**

 In [WebGLLights], in the part for RectAreaLights: https://github.com/mrdoob/three.js/blob/89f0b932ae3664a377b09a0c3bf1604fae1980e9/src/renderers/webgl/WebGLLights.js#L380
 there are references to UniformsLib.LTC_FLOAT_1 and LTC_FLOAT_2 constants which are not defined in the [UniformsLib](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/UniformsLib.js). 

When doing a type check (ie. rewrite of component to typescript) there is an error "Property does not exist on the type UniformsLib". Investigation of `UniformsLib` also reveals missing constants. There are `ltc_1` and `ltc_2` properties of lights there...

**Expected behavior**

The code in WebGLLights should point to the right constants in the UniformsLib.
Either remove references to the missing constants, include the constants in the UniformsLib, or point the references to existing values (`ltc_1`, `ltc_2`).

**Comment by Mugen87** [comment]
`RectAreaLight` is no part of the core. The idea is to include `RectAreadLightUniforms` and call the respective `init()` before using this type of light.

https://github.com/mrdoob/three.js/blob/89f0b932ae3664a377b09a0c3bf1604fae1980e9/examples/jsm/lights/RectAreaLightUniformsLib.js#L33-L68

The mentioned uniforms will then exist.
