### ISSUE TITLE
EffectComposer: Deduplicate code

### ISSUE THREAD

**Issue by ycw** [mrdoob/three.js#21936]
There're duplicate code:

- https://github.com/mrdoob/three.js/blob/dev/examples/jsm/postprocessing/EffectComposer.js#L246-L316
- https://github.com/mrdoob/three.js/blob/dev/examples/jsm/postprocessing/Pass.js#L8-L78

**Describe the solution you'd like**

Re-export Pass and FullScreenQuad in EffectComposer.js

**Comment by Mugen87** [comment]
Embedding `Pass` in `EffectComposer` was done so in order to avoid breakage in `examples/js` files. It's important to know that `Pass` was added years after the introduction of `EffectComposer` to ensure a common interface for passes.

**Comment by ycw** [comment]
@Mugen87 so are they supposed to be identical?

**Comment by Mugen87** [comment]
Yes.

**Comment by ycw** [comment]
@Mugen87 how about 're-export `Pass` and `FullScreenQuad` (from EffectComposer.js) in Pass.js'?

**Comment by Mugen87** [comment]
TBH, we only talk about a few lines of code here. And I think it's more clear to have `Pass` in its own file with its own implementation. I favor the current approach instead of a DRY solution.

**Comment by Mugen87** [comment]
Closing for now. If we ever get rid of `examples/js`, this (minor) issue will go automatically away.
