### ISSUE TITLE
Should WebGLMultipleRenderTargets extend WebGLMultipleRenderTarget?

### ISSUE THREAD

**Issue by joshuaellis** [mrdoob/three.js#21930]
**Is your feature request related to a problem? Please describe.**

Introduced here – #16390, WebGLMultipleRenderTargets extends WebGLMultipleRenderTarget which on the surface works, however when we came to create the .d.ts file – https://github.com/three-types/three-ts-types/pull/85 we began to discuss how maybe this shouldn't be the case. Calling `WebGLMultipleRenderTargets.setTexture` would fail because you'd either have to supply an array which would break:

```js
texture.image = {
	width: this.width,
	height: this.height,
	depth: this.depth
};
```

see: 
https://github.com/mrdoob/three.js/blob/d39d82999f0ac5cdd1b4eb9f4aba3f9626f32ab6/src/renderers/WebGLRenderTarget.js#L46

Alternatively not passing an array of Textures, would break the `WebGLMultipleRenderTargets`.

**Describe the solution you'd like**

Whilst I appreciate how helpful it is to extend a lot of the features already written in WebGLMultipleRenderTarget, maybe there should be a utility/base class that they both inherit from, this would reduce duplication (which is why we extend classes in the first place) and equally avoid the edge cases described above that will impact users.

**Additional context**

For anyone interested, the `.d.ts` file will probably just duplicate the properties and methods included in `WebGLMultipleRenderTarget`

**Comment by joshuaellis** [comment]
Would it be better if I mocked up a proposal in a PR? Or would we rather discuss the issue here first?

**Comment by Mugen87** [comment]
I guess it's easier to see the impact of a change with a PR.

**Comment by mbredif** [comment]
Does #22089 solves this issue ?

**Comment by Mugen87** [comment]
Since #23498 removes `WebGLRenderTarget.setTexture()`, there is no inconsistency with `WebGLMultipleRenderTargets.setTexture()` anymore. So the inheritance itself should not cause any (type) issues anymore.
