### ISSUE TITLE
Bump Map Not Working

### ISSUE THREAD

**Issue by d-w-d** [mrdoob/three.js#21939]
**Describe the bug**

I am working on a solar-system viewer. In the past, I have been able to give the Earth a bump map following [this guide](http://learningthreejs.com/blog/2013/09/16/how-to-make-the-earth-in-webgl/) from 2013. However, it uses patterns/methods that are now deprecated. I have been trying to get bump maps working with the more modern pattern:

```
const getTexture = (url: string): Promise<THREE.Texture> => {
  return new Promise(resolve => {
    new THREE.TextureLoader().load(url, texture => {
      texture.encoding = THREE.GammaEncoding;
      resolve(texture);
    });
  });
};

this._material = new THREE.MeshPhongMaterial();
const bumpTexture = await getTexture('https://sbn-solar-system-viewer.s3.amazonaws.com/earthbump2.jpg');
this._material.bumpMap = bumpTexture;
this._material.bumpScale = 0.95;
this._geometry = new THREE.SphereGeometry(this._radius, 32, 32);
this._mesh = new THREE.Mesh(this._geometry, this._material);
this._mesh.receiveShadow = true;
this._mesh.castShadow = true;
...
this._scene.add(this._mesh);
``` 

... but the bump-map stuff has no effect. I have tried different materials, different image sizes/resolutions, different types of light, etc., and nothing seems to work. Moreover, I cannot find any online example of a bump map using modern patterns. **It would be very helpful for someone to create an example of a bump map in action with the latest and most recommended patterns/threeJs to build off of.**

**To Reproduce**

***Code***

My code so far is [here](https://github.com/Small-Bodies-Node/sbn-solar-system-viewer/tree/bump-map-not-working). To view on dev server: 
- `git clone ...`
- `npm i`
- `./_library_manager --dev` <-- requires `bash`

Salient code:
`src/threejs/scene-entities/planet.ts` in block `if (this._name === 'EARTH') { ... }`

***Live example***

To see demo zoomed-in on earth with an exaggerated directional light (trying to emphasize bump effect):
`https://small-bodies-node.github.io/sbn-solar-system-viewer/demo-umd-2021-06-01-12:37:32/`

**Expected behavior**

The earth will have bump-induced shadows over Himalayas, etc.

**Platform:**

 - Device: Desktop 
 - OS: MacOS 
 - Browser: All browsers
 - Three.js version: 128

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
