### ISSUE TITLE
Extruding a shape with a hole results in weirdness

### ISSUE THREAD

**Issue by Martinusius** [mrdoob/three.js#21940]
While extruding a shape with a hole, the inner walls of the hole are not created. Furthermore the hole is ignored by the extrusion bevel.

1. Create a shape.
2. Add a hole to the shape.
3. Extrude the shape and bevel it

***Code***

```js
const shape = new THREE.Shape();
const hole = new THREE.Path();

const length = 5, width = 5;

shape.moveTo(0, 0);
shape.lineTo(0, width);
shape.lineTo(length, width);
shape.lineTo(length, 0);
shape.lineTo(0, 0);

hole.moveTo(length / 4, width / 4);
hole.lineTo(length / 4, width / 4 * 3);
hole.lineTo(length / 4 * 3, width / 4 * 3);
hole.lineTo(length / 4 * 3, width / 4);
hole.lineTo(length / 4, width / 4);

shape.holes.push(hole);

const geometry = new THREE.ExtrudeGeometry(shape, {
	steps: 1,
	depth: 1,
  	bevelEnabled: true,
  	bevelThickness: 0.4,
  	bevelSize: 0.4,
  	bevelOffset: -0.4
});

const material = new THREE.MeshPhongMaterial({ color: 0x00ff00, side: THREE.DoubleSide });
const mesh = new THREE.Mesh(geometry, material);
scene.add(mesh);
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/a9umwqhk/17/)
* [jsfiddle-dev](https://jsfiddle.net/wvzd70sy/)

**Expected behavior**

The inner walls should be created and the edges around the hole should be beveled.

**Screenshot**

![shape](https://user-images.githubusercontent.com/46503828/120373325-813fb700-c318-11eb-8b21-81974b9e0201.png)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, Android]
 - Browser: [Chrome, Firefox, Edge]
 - Three.js version: both latest-release and dev (see "Live example")

**Comment by WestLangley** [comment]
The winding order of holes must be the opposite of the winding order of shapes.

https://jsfiddle.net/5nd7kax8/

**Comment by Martinusius** [comment]
Thanks for the help! I was wondering, is this mentioned somewhere in the documentation? I wasn't able to find it anywhere in Shape or ExtrudeGeometry.

**Comment by WestLangley** [comment]
@Martinusius The code tries to be smart and infer what the user intends, even if the user does not follow the convention. It would be worth looking into the code again to confirm the current requirements.

Adding a note to the docs sounds like a good idea -- as long as the requirements can be clearly stated.
