### ISSUE TITLE
Can't get SSAO filter, through composer, to work on this example

### ISSUE THREAD

**Issue by FurrballMcDuff** [mrdoob/three.js#21945]
I was trying to apply SSAO to this example of the walking soldier:
https://threejs.org/examples/#webgl_animation_skinning_blending

Although with a different model. The model works, it animates as intended. But the SSAO layer seems "stuck" in a way that processes the model in its "rest" position, i.e. as if skeletal morphing was not applied at all. Since I'm a complete newbie to three.js, I was wondering if that's a bug, something that's not yet been implemented (combining SSAO with skeletal animations), or (most likely) me not understanding how the composer should be fed.

To apply the composer and the SSAO pass to the existing example code, I've basically copy/pasted the relevant modifications from this other example:
https://threejs.org/examples/webgl_postprocessing_ssao.html

If I let the camera move around, the SSAO pass is correctly updated, but the outline from the AO shading is always that of the model in its "rest" position.

**To Reproduce**

I guess... try combining the two examples mentioned above, the goal would be applying SSAO to the walking soldier scene.

***Code***

As I said, it's a matter of merging the two examples and see if that works.
If that works, then it's me. If it doesn't, then it's a bug.

If you CAN get it to work with the soldier, I'd be glad to see the working code, and where I was doing it wrong.

***Live example***

Would be hard to provide one with my exact model, being a 49MB file.
But it mightn't be necessary: it's just a different model loaded out of that example's code. Plus the SSAO pass.

**Expected behavior**

An animated scene with SSAO shading.

**Screenshots**

Well, that I can easily do: see this prototype "kitty" character?
He's sitting in that animation frame, but the SSAO shading still reflects his silhouette in rest position, which is an A-pose.

![ssao_bug](https://user-images.githubusercontent.com/85259159/120556072-4c0c9500-c3fc-11eb-942c-97ada75e0bad.PNG)

**Platform:**

 - Device: Desktop
 - OS: Windows 10
 - Browser: Edge
 - Three.js version: r129, the latest as I'm writing this

**Comment by Mugen87** [comment]
It seems to work with the soldier model: https://glitch.com/edit/#!/brash-momentous-celestite?path=index.html%3A103%3A117

You can debug the SSAO effect by changing line 103. This allows you to output the (blurred) SSAO to the screen.

Consider to share your model via Drive or a similar service.

**Comment by Mugen87** [comment]
Also make sure that you are really using `r129`? It does not work in earlier versions of `three.js`.

**Comment by Mugen87** [comment]
Please move the conversation to the [forum](https://discourse.threejs.org/). We can reopen the issue if it turns out to be a bug in `three.js`.

**Comment by FurrballMcDuff** [comment]
Uh, thank you everyone!
Will check all points in a while, sorry for missing the correct place to ask.

**Comment by FurrballMcDuff** [comment]
> Also make sure that you are really using `r129`. It does not work with earlier versions of `three.js`.

AAARGH! it was THAT!

```
  "name": "three",
  "version": "0.128.0",
  "description": "JavaScript 3D library",
```

Wow, really! My bad, I didn't check but guessed it was unlikely I wasn't using the latest one, given I had downloaded the master ZIP file like... maybe 5 days ago.

Most sincere apologies, I'm a dolt.
Hoping to improve, even though I'm an old clock as a programmer.
Time to get more careful before bothering people for help. :)

**Comment by FurrballMcDuff** [comment]
p.s. the linked sample project works, but doesn't really apply the SSAO pass because it throws an error:

![ssao_err](https://user-images.githubusercontent.com/85259159/120641388-d5ab7980-c473-11eb-8a5e-625e2e9cd07c.PNG)


The only solution that seems to be working, found by inspecting what the code expects as valid formats for "depthTexture", is the following one (the other possibility, THREE.DepthStencilFormat, is accepted by the renderer but has WebGL throw an error):

```
        ssaoPass.normalRenderTarget.depthTexture.format = THREE.DepthFormat;
```

Aside all that, eeeh... well, it does work but it's rather prone to depth artifacts.
I'll be looking to see what's going on in the SSAO shader and if it can be improved.

**Comment by Mugen87** [comment]
I've updated the glitch in order to avoid the warning. Also fine-tuned the parameters a bit.

Maybe just using an AO map is the better choice.
