### ISSUE TITLE
ExtrudeGeometry with high negative bevelOffset produces weird geometry (shape with a hole)

### ISSUE THREAD

**Issue by Martinusius** [mrdoob/three.js#21950]
When extruding a shape with a hole with a high negative bevelOffset, artifacts start appearing on the geometry. The more negative the bevelOffset is, the more pronounced the artifacts are. The artifacts appear to become smaller with decreasing size of the shape.

I also posted this on the [forum](https://discourse.threejs.org/t/extrudegeometry-bevel-fails-with-high-negative-beveloffset-shape-with-a-hole/26904) but haven't gotten any response since. That is why I'm assuming this is a bug.

1. Create a circular shape with a radius of 40.
2. Create a smaller circular shape with a radius of 32 (with opposite winding order) and set it as a hole of the first shape.
3. Extrude the shape with a bevelOffset of 3.

***Code***

```js
const shape = new THREE.Shape();
const hole = new THREE.Path();

shape.absarc(0, 0, 40, 0, 2 * Math.PI, false);
hole.absarc(0, 0, 32, 0, 2 * Math.PI, true);
shape.holes.push(hole);

const geometry = new THREE.ExtrudeGeometry(shape, {
    steps: 1,
    depth: 10,
    bevelEnabled: true,
    bevelThickness: 0,
    bevelSize: 0,
    bevelOffset: -3,
    bevelSegments: 10
});

const material = new THREE.MeshPhongMaterial({ color: 0x00ff00, side: THREE.DoubleSide });
const mesh = new THREE.Mesh(geometry, material);
scene.add(mesh);
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/ur7y10bg/)
* [jsfiddle-dev](https://jsfiddle.net/5p02oy1m/)

**Expected behavior**

Unless the bevelOffset is more than half of one of the shape's dimensions I would expect the extrusion to shrink the geometry as it does with lower negative values.

**Screenshots**

![kuwu](https://user-images.githubusercontent.com/46503828/120827396-b0923600-c55b-11eb-9aaf-4108bee7fea6.png)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, Android]
 - Browser: [Chrome, Firefox, Edge]
 - Three.js version: both latest-release and dev

**Comment by Mugen87** [comment]
Let's discuss this at the forum first.
