### ISSUE TITLE
Program files created world writable

### ISSUE THREAD

**Issue by dittyroma** [mrdoob/three.js#21960]
**Describe the bug**

Some program files are created world writable. On a multiuser system this may allow an attacker to control behavior by modifying the files (eg a config file). On Linux the umask should usually prevent this but it's not guaranteed. [Secure coding standards](https://wiki.sei.cmu.edu/confluence/display/c/FIO06-C.+Create+files+with+appropriate+access+permissions) recommend always specifying a restricted mode so files are secure in any environment. MITRE calls this [CWE-732](https://cwe.mitre.org/data/definitions/732.html), one of the [top 25 most dangerous](https://cwe.mitre.org/top25/archive/2020/2020_cwe_top25.html) vulnerabilities.

Findings are listed here:
https://lgtm.com/query/308122751628928618/

If this prepublish usage is part of a deployment, it could allow an attacker to control what is eventually published.
https://lgtm.com/projects/g/mrdoob/three.js/snapshot/604037f62e2b2b6a530484aa2d33defb1e1bb015/files/utils/prepublish.js?sort=name&dir=ASC&mode=heatmap#L10

This came out of research with CodeQL.

**To Reproduce**

- Use the prepublish functionality with umask cleared to 000.
- World writable file is created.

**Expected behavior**

Program files are created with secure permissions.

**Comment by gkjohnson** [comment]
@dittyroma I just want to make sure that I'm not missing something but the repro steps don't seem to work. The `prepublishOnly` script will only ever overwrite existing files and the behavior of nodes `fs.writeFileSync` seems to be to retain existing file permissions which are `-rw-r--r--`, at least on my Mac, even when `mode` is explicitly set to something different. Is the behavior different on other machines?

**Comment by dittyroma** [comment]
You're right, it should always be there. As far as I know that permissions behavior is the same across platforms too.
