### ISSUE TITLE
Geometry with white alphaMap and transparency=true, opacity=1, is not rendered fully opaque

### ISSUE THREAD

**Issue by stephent** [mrdoob/three.js#21987]
**Describe the bug**

A geometry with a standard material which has BOTH an alpha mask set and transparency set to true is not rendered fully opaque as expected.

Even though the alpha mask is solid white (i.e. fully opaque) and the opacity of the geometry is set to 1, the geometry is rendered partially transparent.

**To Reproduce**

1. Attach a standard material with an alpha mask  which includes some part fully opaque area (i.e. white) to a geometry
2. Set transparent to true and opacity=1 on the same geometry
3. The geometry is not rendered fully opaque, even though the alpha mask is fully opaque AND the opacity is set to 1

***Code***

Example using react-three-fiber: a red plane is masked to circular area via the alpha mask, and is expected to be fully opaque. Behind the plane is a white box which should not be visible at all from default camera position, but it is in Case 1 below.

Case 1 (displays bug): Plane should be masked to a circle (via alphaMap) and should be solid red, but is rendered partially transparent:
```js
      <Plane args={[2, 2, 1, 1]}>
        <meshStandardMaterial attach="material" color="red" alphaMap={alphaTarget.texture} transparent={true} opacity={1} />
      </Plane>
```

Case 2 (as expected): Plane rendered to solid red, no transparency
```js
      <Plane args={[2, 2, 1, 1]}>
        <meshStandardMaterial attach="material" color="red" /*alphaMap={alphaTarget.texture}*/ transparent={true} opacity={1} />
      </Plane>
```

Case 3 (as expected): Plane masked and rendered to solid red, no transparency
```js
      <Plane args={[2, 2, 1, 1]}>
        <meshStandardMaterial attach="material" color="red" alphaMap={alphaTarget.texture} transparent={false} opacity={1} />
      </Plane>
```

***Live example***

* [CodeSandBox](https://codesandbox.io/s/r3f-programmatic-alpha-map-f8lhi?file=/src/index.js)
* See material element on line 56.

**Expected behavior**

Plane should be masked and solid red (i.e. as per Case 3 screenshot below) when both alphaMap is set AND transparent=true and opacity=1. Or if transparent=true is not valid in conjunction with use of an alphaMask, update docs to clarify.

(I'm not sure if there's any valid real world use case for using an alphaMap in conjunction with transparent=true, but somehow I stumbled into this situation in my own code, and was confused by the result I saw.)

**Screenshots**

Case 1:
![Screenshot 2021-06-14 at 15 43 25](https://user-images.githubusercontent.com/898090/121963453-5cd7d780-cd27-11eb-87a8-7cca8fb40d48.png)

Case 2:
![Screenshot 2021-06-14 at 15 43 40](https://user-images.githubusercontent.com/898090/121963454-5e090480-cd27-11eb-8519-caa5fdcdf55b.png)

Case 3:
![Screenshot 2021-06-14 at 15 43 59](https://user-images.githubusercontent.com/898090/121963456-5e090480-cd27-11eb-8498-429cf24a4c00.png)

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Safari
 - Three.js version: 129

**Comment by Mugen87** [comment]
> A geometry with a standard material which has BOTH an alpha mask set and transparency set to true is not rendered fully opaque as expected.

I'm unable to reproduce this issue with the following fiddle: https://jsfiddle.net/vsoLhmq6/2/

BTW: When sharing a live example, it's better to use pure `three.js` code and not libraries like react-three-fiber. That makes it only harder for us to investigate issue inside the engine.

**Comment by WestLangley** [comment]
>Even though the alpha mask is solid white

It would appear it is not. One reasonable guess is this is due to react-three-fiber tone mapping, sRGB encoding, and/or gamma correction in the render target.

**Comment by stephent** [comment]
> > Even though the alpha mask is solid white
> 
> It would appear it is not. 

Except in Case 3 - same map, but fully opaque.

> One reasonable guess is this is due to react-three-fiber tone mapping, sRGB encoding, and/or gamma correction in the render target.

I guess next step is to try to update @Mugen87 's fiddle to use a Render Target instead of an image for the alphaMap to see if that reproduces the issue.

**Comment by drcmda** [comment]
> > Even though the alpha mask is solid white
> 
> It would appear it is not. One reasonable guess is this is due to react-three-fiber tone mapping, sRGB encoding, and/or gamma correction in the render target.

if does autoconvert colors to srgb. so either `<Canvas linear` which is the threejs default

or `<xxxMaterial toneMapped={false} .... />`

**Comment by Mugen87** [comment]
@stephent Please use the [forum](https://discourse.threejs.org/) if you need more help.

**Comment by stephent** [comment]
Quick follow up on this comment in my original post:

>> I'm not sure if there's any valid real world use case for using an alphaMap in conjunction with transparent=true, but somehow I stumbled into this situation in my own code, and was confused by the result I saw.

The answer is "yes" - without transparent=true, even though the alpha mask is applied, the full geometry occludes other objects (depth buffer, I assume? - not totally up to speed on the terminology here...).
