### ISSUE TITLE
InstancedMesh first two arguments are optional

### ISSUE THREAD

**Issue by joshuaellis** [mrdoob/three.js#21982]
**Describe the bug**

`InstancedMesh`'s first two arguments – `geometry` and `material` are in-fact option because the class inherits from `Mesh` which has defaults provided:

https://github.com/mrdoob/three.js/blob/2383c1c0e48c3a966926f28a5acdb4b09f5dd35e/src/objects/Mesh.js#L37

Therefore when you try and use typescript with `three` you get issues with not providing the first two arguments. We can change these arguments to optional however the `third` argument `count` is required as it has no default. This then throughs an error in Typescript which sort of makes sense, using `new InstancedMesh(undefined, undefined, 3)` is a bit silly. 

This issue has propogated from the following issues:
* pmndrs/racing-game#128
* three-types/three-ts-types#92

**To Reproduce**

Check out the issue in order to see the chain of events

**Expected behavior**

You could argue this is an API design issue, I believe we can resolve it one of two ways:
* move count to be the first argument, simplest solution although I imagine this might be undesirable because it's not uniform to `new Mesh`
* give a default to `count` e.g. 1 probably makes the most sense and then use a `setter` of some kind to update `count` and also recreate the correct `instanceMatrix`
https://github.com/mrdoob/three.js/blob/2383c1c0e48c3a966926f28a5acdb4b09f5dd35e/src/objects/InstancedMesh.js#L18

**Screenshots**

Image of the trying to make the arguments optional (because they are): 
![image](https://user-images.githubusercontent.com/37798644/121803849-4bb19c80-cc3b-11eb-8efa-c1ce22f93d56.png)

**OTHER**
If we can come to a decision on how we want to tackle this issue and if implementation work is required, I'll happily do the work 👍🏼  don't want to raise an issue to not volunteer to resolve it 😅

**Comment by Mugen87** [comment]
Wouldn't it be possible to just make the first and second parameters mandatory in the type declaration file?

The problem is that we want to keep the parameter order `geometry`, `material` and `count` since this is more consistent to other 3D objects. And since `count` is a fixed value, applying it in the ctor is the most robust approach. A setter suggest the count can arbitrarily changed (which is not something that should be promoted).

**Comment by joshuaellis** [comment]
So currently they are mandatory, but then we get issues where perhaps someone doesn't want to add the geometry and material straight away to the `InstancedMesh`, my own example is [here](https://github.com/pmndrs/racing-game/pull/128/files#diff-29dd95facd05ae84b0c022e05d4cfb6c04e153490a2b63a8b58554f9f4823442R41) where we can add the geometry and material as children the component tree, albeit this example is `react-three-fiber` orientated, by I don't think its an unrealistic use-case.

The issue stems from `mesh.material` and `mesh.geometry` being mutable. Whilst I appreciate keeping `geom` & `mat` in the same order as other 3D objects for consistency, they're not required parameters so the practice should be that required parameters are before optional...

I'd be interested why `count` should not be arbitrarily changed, just for my own knowledge.

**Comment by Mugen87** [comment]
The allocation of the instanced buffer data depends on the `count` property. In general, we consider buffer attributes as fixed size. They can't be resized after their creation. For performance reasons, the project decided to not provide APIs for resizing buffer attributes (e.g. the former `setArray()` method). Adding `InstancedMesh.setCount()` would be contradictory against this backdrop.

**Comment by joshuaellis** [comment]
Interesting, thanks for telling me! Our only solution would be to re-order the constructor args so count is first. If you don't want to do that then feel free to close the issue 😄

**Comment by mrdoob** [comment]
Another solution is to set `count` to `1` by default.

**Comment by Mugen87** [comment]
But why somebody create an instanced mesh with just one instance^^? It would be more a technical default value with not much usability. And increasing `count` after creating the instanced mesh is not really supported.

**Comment by mrdoob** [comment]
Indeed. But I guess at least it wouldn't crash(?) if someone forgot it. Maybe 100?

This question/suggestion has come up a couple of times.

**Comment by joshuaellis** [comment]
It doesn't crash currently, but it also doesn't give feedback... If you were to supply a default, it'd make sense to then provide a way of changing that `count` value...

**Comment by mrdoob** [comment]
That count property is, basically, memory. How much memory do you want to allocate? 10000? 

I could also see the case where the user increases the count every frame. That'll result in uploading all the data every frame. The gpu doesn't let you expand buffers, you need to upload them again.

**Comment by mrdoob** [comment]
> It doesn't crash currently, but it also doesn't give feedback...

What feedback do you want?

**Comment by joshuaellis** [comment]
> That count property is, basically, memory. How much memory do you want to allocate? 10000?
> 
> I could also see the case where the user increases the count every frame. That'll result in uploading all the data every frame. The gpu doesn't let you expand buffers, you need to upload them again.

This feels a bit out of my depth so i'm happy to leave this if you want to keep as is

> What feedback do you want?

I think it could be as simple as "Failed to provide count value to InstancedMesh constructor", that way if you don't have Typescript (complaining about the type error) you'll know that you forgot to pass something?

**Comment by Mugen87** [comment]
I don't think we should start validating mandatory parameters.

**Comment by joshuaellis** [comment]
> I don't think we should start validating mandatory parameters.

Why do you think that?

**Comment by Mugen87** [comment]
Because we've agreed in the past to not do this for performance and code readability reasons (see #21990).

**Comment by joshuaellis** [comment]
Thats fair enough, I hadn't seen that PR (understandably) 😄

**Comment by bjornstar** [comment]
> Wouldn't it be possible to just make the first and second parameters mandatory in the type declaration file?

They are currently mandatory in the type declaration file, but in the code they are optional. The problem is the disconnect between the types and the code.

We end up doing things like turning off type checking:
``` tsx
    // @ts-expect-error - https://github.com/three-types/three-ts-types/issues/92
    <instancedMesh ref={ref} args={[null, null, count]}>
      <planeGeometry args={[size, size * 2]} />
      <meshBasicMaterial color="black" transparent opacity={opacity} depthWrite={false} />
    </instancedMesh>
```

When we'd very much like to do this:
``` tsx
    <instancedMesh ref={ref} args={[count]}>
      <planeGeometry args={[size, size * 2]} />
      <meshBasicMaterial color="black" transparent opacity={opacity} depthWrite={false} />
    </instancedMesh>
```

> The problem is that we want to keep the parameter order `geometry`, `material` and `count` since this is more consistent to other 3D objects. And since `count` represents the maximum number if instances, applying it in the ctor is the most robust approach.

One option could be to overload the constructor so that the last argument is always count since it is mandatory.

If the answer is "We don't overload in this project" that's fine. I'm willing to accept the "silly" solution which is to change the types to allow undefined or null in args.

**Comment by mrdoob** [comment]
Wait, is this what r3f does?

```js
const mesh = new THREE.Mesh();
mesh.geometry = new THREE.PlaneGeometry( 1, 1, 1 );
mesh.material = new THREE.MeshBasicMaterial();
scene.add( mesh );
```

If so... for every instance of a `Mesh`, `Line` and `Points`, r3d creates two `BufferGeometry` classes and 2 `*Material` classes:

https://github.com/mrdoob/three.js/blob/34d4516570c20e153f2d9644e2d07b6a9a7e600c/src/objects/Mesh.js#L37

/cc @drcmda

**Comment by joshuaellis** [comment]
Yes because the reconciler can't know the children of an element until the parent has been created. So mesh's are created with their default and their default is then replaced before a commit to rendering.

You can pass `args` as a prop in r3f which would be the equivalent of:

```js
const mesh = new THREE.Mesh(new THREE.PlaneGeometry( 1, 1, 1 ), new THREE.MeshBasicMaterial());
scene.add( mesh );
```

But then it's not very declarative and updating the geometry or material becomes more difficult than it would be just passing props.

**Comment by drcmda** [comment]
https://github.com/mrdoob/three.js/issues/17714 🤪 i kinda suspected that this could become a real issue in typescript. it was a design issue.

> If so... for every instance of a Mesh, Line and Points, r3d creates two BufferGeometry classes and 2 *Material classes

it does that. i've measured it out and these are just empty shells that the GC immediately takes out. but should that become a problem one day, it would be easy to fix, it could just inject `null` into the constructor args and then take the declarative versions.

the above is a typescript error though.
