### ISSUE TITLE
VRButton.js needs "hand-tracking" removed

### ISSUE THREAD

**Issue by hamishtodd1** [mrdoob/three.js#21981]
Hey, so in e.g. WebXr sculpt https://threejs.org/examples/webxr_vr_sculpt the browser complains because of line 72 in VRButton.js, and the context can't be created

It's a simple fix, you just need to remove "hand-tracking" from the parameters on that line, it doesn't appear to be needed anymore.

**Comment by Mugen87** [comment]
`hand-tracking` is required so the Hand Input API does work, see https://github.com/immersive-web/webxr-hand-input/blob/main/explainer.md.

Please use the [forum](https://discourse.threejs.org/) to clarify why the XR session can't be created on your device. If there is an issue with `three.js`, this issue can be reopened.

**Comment by hamishtodd1** [comment]
"hand-tracking" isn't mentioned here https://www.w3.org/TR/webxr/

I was testing on chrome. It wasn't exactly an issue with three.js but with VRButton.js. It went away when I removed 'hand-tracking' - but hand tracking **still worked!!**
