### ISSUE TITLE
Camera Feed Not working All the Time.

### ISSUE THREAD

**Issue by sikandernoori** [mrdoob/three.js#21985]
**Describe the bug**

https://threejs.org/examples/webxr_ar_hittest.html

I clone the repository and published as it is on firebase.
Now when hit "START AR" camera feed show black screen and hangs, But if I Keep the Mobile default camera App Open in Parallel then it works. Tested on Multiple devices, Samsung, Infinix and NExus. Result is Same.

but when I try the Official Example there is No Need for Cmera to be Opened in Parallel

**To Reproduce**

1. Go to https://threejs.org/examples/webxr_ar_hittest.html
2. Clone Repository.
3. Test Locally using ngrok or Published it to firebase

***Code***

**Expected behavior**

Camera Feed Should Open regardless Default Camera App is Opened or not.

**Platform:**

Chrome for Mobile. Android.

**Comment by Mugen87** [comment]
Please ask for help at the [forum](https://discourse.threejs.org/).
