### ISSUE TITLE
logarithmicDepthBuffer causes Reflector to be rendered incorrectly

### ISSUE THREAD

**Issue by jonas-kell** [mrdoob/three.js#21980]
**Describe the bug**

When rendering a scene with a Reflector that has an opaque surface behind it, the surface get's rendered after the reflector and overwrites it, seemingly neglecting the depth buffer (That is set correctly).

**To Reproduce**

This was caused in a giant project that is not open source and therefore it ranges from very complicated to impossible to reproduce the exact scene. I will however provide many screenshots to make clear what the issue is.

The reason for the using of the logarithmicDepthBuffer was, that I was encountering z-Fighting earlier. And the logarithmicDepthBuffer took care of it quite swiftly. Therefore it caused quite a headache to figure this out as the cause of my problem.

Explanation for some artifacts: some objects are rendered in mirrors, that aren't visible in the scene itself, as there is quite complicated logic to hide sections of wall depending on the viewport. This is not the cause of the problem and was tested. In the mirror all elements are always rendered.

**Expected behavior**

logarithmicDepthBuffer probably shouldn't change the render-order for Reflector specifically. (I understand the logarithmicDepthBuffer is supposed to change the render order, however as it works with solid materials in the same range and only fails on the Reflector, I think this is caused by a unwanted prioritization somewhere).

**Screenshots**

First of all, this is what the scene should look like. This is rendered with **logarithmicDepthBuffer=false**. A slanted mirror traverses the whole cabin and reflects the floor, backwall (that is transparent seems to affect changes some render-order things) and the right sidewall (not visible to the camera, but the mirror).
![image](https://user-images.githubusercontent.com/62432375/121788159-60eee280-cbcb-11eb-9935-ade2a18aaeee.png)

Now for the second picture EVERYTHING is exactly the same, except for **logarithmicDepthBuffer=true**.
![image](https://user-images.githubusercontent.com/62432375/121788254-276aa700-cbcc-11eb-82ab-689769d1f75c.png)

The outside of the door gets reflected correctly, as there is no opaque mesh behind the reflector, that overwrites the buffers.
Also the section of the mirror over the back wall (with brick texture) get's rendered correctly. As all transparent things get rendered AFTER the solid materials this puzzles me, but whatever. 

Now for the problem: In the center (left grey wall) the opaque mesh is drawn OVER/AFTER the mirror, overwriting it. 
This is for sure not a problem with render order or disabled depthWrite, as I can assure you the only thing that changed between the two pictures is the logarithmicDepthBuffer value.

As pointed out earlier, all opaque and transparent materials in the same range of distance are unaffected and rendered correctly in any case. Only Reflector objects are affected in that way.

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome, Firefox]
 - Three.js version: [r129]

**Solution**

I sadly do not have any idea what could cause this behavior, but I wanted to document this as it caused me quite a headache. If it is not fixable, it probably should be addressed in the documentation, that the logarithmicDepthBuffer can cause more issues than just a decrease in performance. As I was under the impression this setting would just trade higher computation times for a more secure detection of depth over a bigger range of distances. And not cause layer index issues.

**Comment by Mugen87** [comment]
> logarithmicDepthBuffer probably shouldn't change the render-order for Reflector specifically. (I understand the logarithmicDepthBuffer is supposed to change the render order, however as it works with solid materials in the same range and only fails on the Reflector, I think this is caused by a unwanted prioritization somewhere).

The usage of `logarithmicDepthBuffer` has not influence on the render order.

I guess the problem is that `Reflector` does not include the `logdepthbuf*` shader chunks. Do you mind checking if the following reflector shader solves the issue?
```js
Reflector.ReflectorShader = {

	uniforms: {

		'color': {
			value: null
		},

		'tDiffuse': {
			value: null
		},

		'textureMatrix': {
			value: null
		}

	},

	vertexShader: /* glsl */`
		uniform mat4 textureMatrix;
		varying vec4 vUv;

		#include <common>
		#include <logdepthbuf_pars_vertex>

		void main() {

			vUv = textureMatrix * vec4( position, 1.0 );

			gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );

			#include <logdepthbuf_vertex>

		}`,

	fragmentShader: /* glsl */`
		uniform vec3 color;
		uniform sampler2D tDiffuse;
		varying vec4 vUv;

		#include <logdepthbuf_pars_fragment>

		float blendOverlay( float base, float blend ) {

			return( base < 0.5 ? ( 2.0 * base * blend ) : ( 1.0 - 2.0 * ( 1.0 - base ) * ( 1.0 - blend ) ) );

		}

		vec3 blendOverlay( vec3 base, vec3 blend ) {

			return vec3( blendOverlay( base.r, blend.r ), blendOverlay( base.g, blend.g ), blendOverlay( base.b, blend.b ) );

		}

		void main() {

			#include <logdepthbuf_fragment>

			vec4 base = texture2DProj( tDiffuse, vUv );
			gl_FragColor = vec4( blendOverlay( base.rgb, color ), 1.0 );

		}`
};
```

**Comment by jonas-kell** [comment]
With **logarithmicDepthBuffer=true** and the modified ReflectorShader:
![image](https://user-images.githubusercontent.com/62432375/121811207-fe95f080-cc63-11eb-904b-044720bba402.png)

Works like a charm. 😄😄
