### ISSUE TITLE
Editor cannot load .ifc files anymore

### ISSUE THREAD

**Issue by xawill** [mrdoob/three.js#21988]
**Describe the bug**

The IFCLoader in the three.js editor is broken. It is not possible to load .ifc files in the three.js editor anymore.

I am pretty sure this got introduced with PR #21683, as the issue looks like the web-ifc WASM file is not correctly loaded (or maybe it is not even served on a web server at all). Am I right, @agviegas ?

As I know somebody will ask eventually, the file I used is the one of the IFCLoader example (rac_advanced_sample_project.ifc), but I am confident the issue is the same for any .ifc file.

**To Reproduce**

1. Open the three.js editor
2. Drag and drop an .ifc file
3. See error

**Expected behavior**

The loaded .ifc file displays in the three.js editor.

**Screenshots**

Here is the output of the console.
<img width="1195" alt="Capture d’écran 2021-06-15 à 09 50 55" src="https://user-images.githubusercontent.com/2658206/122014580-96f4b800-cdbf-11eb-8d78-e9b4fb3ec4a4.png">

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Safari
 - Three.js version: Version currently used on the editor

**Comment by agviegas** [comment]
Yes, it looks like the reference to the WASM is not correct. Is there anything we can do to solve this? I'm not sure how/ where the code of the editor is generated.

**Comment by xawill** [comment]
The web.ifc wasm file is mentioned in the assets of the editor:
https://github.com/mrdoob/three.js/blob/d39d82999f0ac5cdd1b4eb9f4aba3f9626f32ab6/editor/sw.js#L44

But I think the issue is that the path to the wasm file is not set to the IFCLoader instance used in the editor:
https://github.com/mrdoob/three.js/blob/342946c8392639028da439b6dc0597e58209c696/editor/js/Loader.js#L356

But I am not sure how the editor is served, so I don't know what would be the path. `ifcLoader.setWasmPath('examples/jsm/loaders/ifc/')`  ?

**Comment by agviegas** [comment]
Yep, I agree, and that is the correct format for the route, so it should work!

**Comment by xawill** [comment]
Actually, I just tested [http://threejs.org/examples/jsm/loaders/ifc/web-ifc.wasm](http://threejs.org/examples/jsm/loaders/ifc/web-ifc.wasm) and got the file, confirming this. Opening the PR.
