### ISSUE TITLE
BufferGeometry.toNonIndexed() doesn't work with InterleavedBufferAttributes

### ISSUE THREAD

**Issue by xawill** [mrdoob/three.js#21992]
**Describe the bug**

The new Geometry created from the `toNonIndexed` function doesn't work if the attributes of the original geometry are interleaved. This is because the position of the element corresponding to the current index being considered doesn't take into account the stride of the `InterleavedBufferAttribute`.

**To Reproduce**

1. Create a mesh with an indexed geometry having (for instance) position and normal attributes interleaved (this is the case of all the geometries of the .ifc model loaded in the IFCLoader example)
2. Make the geometry non-indexed with the `BufferGeometry.toNonIndexed()` function.
3. Notice that the geometry is completely screwed up, as the `convertBufferAttribute` function confuses some normals with positions and vice-versa, due to the `InterleavedBufferAttribute.data.stride` not being taken into account.

***Code***

Here is the function which has to be corrected in `BufferGeometry.js`:

```js
function convertBufferAttribute( attribute, indices ) {
  const array = attribute.array;
  const itemSize = attribute.itemSize;
  const normalized = attribute.normalized;
  const array2 = new array.constructor( indices.length * itemSize );
  let index = 0, index2 = 0;
  for ( let i = 0, l = indices.length; i < l; i ++ ) {
    index = indices[ i ] * itemSize; // FIXME: Should be index = indices[ i ] * attribute.data.stride;
    for ( let j = 0; j < itemSize; j ++ ) {
      array2[ index2 ++ ] = array[ index ++ ];
    }
  }
  return new BufferAttribute( array2, itemSize, normalized );
}
```

I didn't submitted a PR because I don't know how you want to proceed for the check if the attribute is interleaved or not. But see my fix inlined in the code block for what it should be in the case of an interleaved attribute.

**Expected behavior**

The new geometry resulting from `BufferGeometry.toNonIndexed()` should be the same as the original one.

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: r129

**Comment by WestLangley** [comment]
Nice find.

See if you think this is correct:
```js
if ( attribute.isInterleavedBufferAttribute ) {

	index = indices[ i ] * attribute.data.stride + attribute.offset;

} else {

	index = indices[ i ] * itemSize;

}
```
If @Mugen87 agrees, would you like to file a PR?

**Comment by xawill** [comment]
Regarding the check if the attribute is interleaved, it's trivial, I just forgot three.js is not written in typescript so this works perfectly.

Regarding your addition of `attribute.offset`, I am new to interleaved buffer attributes, so you definitely know better than me. But I think indeed you are correct. I missed that. Without the offset the code would be correct only for the first attribute in the stride, right ?

I can definitely create the PR for this. Should I wait for @Mugen87 approval first ?

**Comment by Mugen87** [comment]
https://github.com/mrdoob/three.js/issues/21992#issuecomment-861920965 looks good!
