### ISSUE TITLE
USDZ exporter with target wall placement

### ISSUE THREAD

**Issue by ThorstenBux** [mrdoob/three.js#21995]
**Is your feature request related to a problem? Please describe.**

When exporting to USDZ currently there is the possibility missing to define the tracking target for AR view (AR Quick-look)

**Describe the solution you'd like**

I'm thinking of a way to make the exporter configurable so that it accepts the different tracking targets supported by Apple AR Quick-look

**Additional context**
Reading through the schema definition here: https://developer.apple.com/documentation/arkit/usdz_schemas_for_ar 
It is possible to encode into the USDZ which tracking target should be used. Hence, I've extended the USDZExporter to support configuration for targets. For now, wall target is integrated but more can be added in the future.

Please see this branch for more context.

Also, I'd like to add that this is my first approach to contribute to this amazing project. And I'm sure I need to do many rounds before this is even close to acceptable but I'd like to give it a go.

My WIP branch: https://github.com/ThorstenBux/three.js/tree/feat/wall-placement-usdz

**Comment by enzyme69** [comment]
In that case maybe we should also enable: 
- Image Marker Anchor 
- Face Anchor

Also on top of that, if we could embed Custom Shader like "Occlusion shader"?

**Comment by ThorstenBux** [comment]
Sure, happy to. I'd just like to keep it small and one step after the other. 
We need to agree on the options object first and then move forward with further improvements. (In my humble opinion)
