### ISSUE TITLE
Failed to resolve module specifier "three"

### ISSUE THREAD

**Issue by ankit-alpha-q** [mrdoob/three.js#22008]
In the latest r129 even with the correct path of three module and its component still getting the error message :
Uncaught TypeError: Failed to resolve module specifier "three". Relative references must start with either "/", "./", or "../"

However the files get loaded properly in network tab.

I tried to lower my version to 127, the issue was gone.

To Reproduce
1. Shift to version 129 in any existing working project.

Screenshots
Error in console:
![image](https://user-images.githubusercontent.com/59704077/122395282-6fa31400-cf94-11eb-8b4f-fad880595ac1.png)

No error while loading resources:
![image](https://user-images.githubusercontent.com/59704077/122395337-7fbaf380-cf94-11eb-8b8a-f86043801bad.png)

Platform:
 - Three.js version: [dev, r129]

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by ankit-alpha-q** [comment]
@Mugen87 Have updated the misleading title, I don't need help coz shifting to r127 resolved my issue, don't know what is the issue with r129

**Comment by mrdoob** [comment]
Can't wait for all browsers to support bare specifiers...

**Comment by Mugen87** [comment]
This change is listed in the migration guide https://github.com/mrdoob/three.js/wiki/Migration-Guide#127--128

> NPM: ES6 modules in examples/jsm now import using the bare specifier three.
This change breaks working with modules in cdns such as https://www.jsdelivr.com/ and https://unpkg.com/. Please use https://www.skypack.dev/ instead.

That means loading modules in web apps from `node_modules` is not supported anymore.
