### ISSUE TITLE
Materials with emissiveIntensity under 1 are exported with an emissive way too bright with GLTFExporter

### ISSUE THREAD

**Issue by SBRK** [mrdoob/three.js#22000]
Starting with r129 and the modification for #21849 the emissiveFactor exported with GLTFExporter ignores `emissiveIntensity`

I'm not sure to undestand exactly why the `emissiveIntensity` is now ignored completely at GLTF export, but it broke something for us. Materials with an `emissiveIntensity` that is between 0 and 1 are now exported like their `emissiveIntensity` would be 1 on three <= r128, so they're way too bright. 
Shouldn't the exporter rather multiply by the `emissiveIntensity` then clamp the result or something ?

**Comment by Mugen87** [comment]
As mentioned in the code comments, ignoring `emissiveIntensity` was done to accommodate the glTF specification. Instead of working with `emissiveIntensity` you have to modulate the color value instead.

**Comment by WestLangley** [comment]
I think the exporter should instead scale `emissive` by `emissiveIntensity` -- but limit the scaling, so no color component exceeds one.

Doing so will prevent hue shifts. It will also prevent issues like this one from being raised.

Alert with an appropriate warning if the intensity was limited during export.

**Comment by SBRK** [comment]
I agree with @WestLangley 
The current behavior is bad for everyone:
- If your `emissiveIntensity` is between 0 and 1, before r129 it would multiply the emissive and when you import the gltf elsewhere the value would reflect the one you had in threejs. After r129 the exporter exports something that is too bright.
- If your `emissiveIntensity` is above 1, before r129 you'd (maybe) get an error when importing the generated gltf and get a chance to understand what to do. After r129 you'll just get an emissive that is too dim.

In both cases, you might end up with something too bright or too dim and have little to no clue why.

**Comment by donmccurdy** [comment]
I'd be fine with scaling and then clamping, yes. FWIW there is a proposal upcoming (still a draft though) to allow an "emissive strength" parameter in glTF as well: https://github.com/KhronosGroup/glTF/pull/1994.

**Comment by Mugen87** [comment]
@SBRK Would you like to make a PR in order to add the suggested change?

**Comment by SBRK** [comment]
@Mugen87 sure! Will do tomorrow

**Comment by SBRK** [comment]
What do you think is the best method:
- Multiply then clamp each emissive component between 0 - 1
- Clamp `emissiveIntensity` then multiply

I reckon clamping `emissiveIntensity` is better because clamping after might denaturate the color (say you multiply `r: 0.5, g: 0.5, b: 1` (light purple)  by 2, with the first method, you'd end up with `r: 1, g: 1, b: 1` (white) )

**Comment by WestLangley** [comment]
@SBRK See https://github.com/mrdoob/three.js/issues/22000#issuecomment-862532750.
