### ISSUE TITLE
Examples: webgl_loader_gltf_transmission issues

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#22009]
Reposting https://github.com/mrdoob/three.js/issues/21000#issuecomment-862597968 so as to consolidate some remaining issues.

1. `webgl_loader_gltf_transmission` has the `transparent` property of each sphere to set to `false`. Is that what the loader should be doing? What should `transparent` be set to when `transmission` is non-zero?

2. After setting `transparent` to `true`, only front-faces show the hot-spot. (This may be a known limitation, but @mrdoob just added support for properly rendering back-faces of double-sided meshes.) There should be two hot-spots.
<img width="123" alt="Screen Shot 2021-06-16 at 1 53 43 PM" src="https://user-images.githubusercontent.com/1000017/122269153-e4018880-ceaa-11eb-8e14-65e9c56f8866.png">

3. ~~FIXED: This is caused by issue 7. below.~~
<img width="113" alt="Screen Shot 2021-06-16 at 1 51 42 PM" src="https://user-images.githubusercontent.com/1000017/122269137-e06e0180-ceaa-11eb-991e-6d51fd134415.png">

4. ~~FIXED Also, in Chrome and Firefox (not Safari)~~
>~~THREE.WebGLProgram: gl.getProgramInfoLog() WARNING: Output of vertex shader 'vUv' not read by fragment shader~~

~~Transmission always sets the `USE_UV` flag.~~

5. ~~FIXED: If performant, I think the dimensions of the "transmission render target" should match the dimensions of the "current render target".~~ Doing so will prevent artifacts like the following:

<img width="555" alt="Screen Shot 2021-06-21 at 9 04 34 PM" src="https://user-images.githubusercontent.com/1000017/123011145-ddcd4980-d38d-11eb-9a14-6284ed3ed306.png">

6. ~~FIXED In the following code snippet, `transmissionFactor` is applied to `getIBLVolumeRefraction()` twice. I expect that is a physical modeling error.~~

https://github.com/mrdoob/three.js/blob/dd6ab3cf310f78a8375b8b2037db12ce8e31e82c/src/renderers/shaders/ShaderChunk/transmission_fragment.glsl.js#L23-L28

7. ~~FIXED Also in the above snippet, `totalSpecular` has units of radiance, and therefore cannot be the correct argument because the function expects a unit-less quantity. A reasonable guess would be `material.specularColor`, instead.~~

 - Device: Desktop
 - OS: macOS 11.4
 - Browser: Chrome, Firefox, Safari
 - Three.js version: r130dev

/ping @takahirox @donmccurdy

**Comment by donmccurdy** [comment]
I think that displaying transmissive materials (as defined by `KHR_materials_transmission`) through other transmissive materials may be considered a feature request. Displaying opaque materials and the environment map through the transmission — as we do now — was priority (1), displaying alpha blend materials through transmission is probably second (2), and transmission through transmission third (3). 

Similarly, I believe I'm seeing (1) in https://sandbox.babylonjs.com/ and https://github.khronos.org/glTF-Sample-Viewer-Release/, with reflections only from the nearest transmission material. Adding (2) and (3) requires techniques like depth peeling; see comment by @MiiBond in https://github.com/mrdoob/three.js/issues/16977#issuecomment-836197846. This would certainly be a welcome addition, but we'd want the flexibility to configure the number of layers, or disable that entirely for performance.

**Comment by mrdoob** [comment]
> 4. Also, in Chrome and Firefox (not Safari)
>>THREE.WebGLProgram: gl.getProgramInfoLog() WARNING: Output of vertex shader 'vUv' not read by fragment shader
>
> Transmission always sets the `USE_UV` flag.

Fixed https://github.com/mrdoob/three.js/commit/ac6d30a393e6974c3cb15e8113303b99cbb18e72

**Comment by mrdoob** [comment]
> 5. If performant, I think the dimensions of the "transmission render target" should match the dimensions of the "current render target". Doing so will prevent artifacts like the following:

Worth noting that this would only work in WebGL2 as we do need mipmaps.

**Comment by mrdoob** [comment]
Another problem with the current transmission implementation is that it "breaks" when setting the `alpha: true` in the renderer.

Here I'm setting `alpha: true` and `renderer.domElement.backgroundColor = 'red'`:

<img width="490" alt="Screen Shot 2021-06-23 at 6 42 18 PM" src="https://user-images.githubusercontent.com/97088/123144254-6661ed80-d453-11eb-90f6-a7fb4b0cf9e4.png">

/cc @elalish

**Comment by elalish** [comment]
I consider this pretty important. The DOM uses transparency pretty extensively which is why model-viewer uses alpha: true. This way DOM backgrounds and gradients and such fit nicely into the scene and the 3D doesn't have to look like a rectangle. Of course this is non-physical, so we'll need some kind of simple approximation. I'm hoping we can just get the shader to set the alpha to whatever the transmission % of the pixel was, though we'll have to be careful to keep it opaque if it was already drawn to by something opaque. It won't blur the DOM background, but I think that's fine, and more or less in line with not seeing transparent objects through each other.

**Comment by gonnavis** [comment]
Hello @takahirox, Thanks for the PR! I found that [current example](https://raw.githack.com/takahirox/three.js/d6fcfa5606539967a77b6b84fbab239206054d14/examples/webgl_loader_gltf_transmission.html) has gaps if look from side view or back view:
![image](https://user-images.githubusercontent.com/10785634/126074155-3b8aee90-f0f4-446c-ab7f-603ba66dc17e.png)
But front view is OK.
I tried with a [simple box](https://raw.githack.com/gonnavis/three.js/a8f44798c557f36a9296943e907bc7a123097c39/examples/webgl_loader_gltf_transmission_test_2.html), seems all refracted pixel are pushed to +Z axis a little?

**Comment by mrdoob** [comment]
> I tried with a [simple box](https://raw.githack.com/gonnavis/three.js/a8f44798c557f36a9296943e907bc7a123097c39/examples/webgl_loader_gltf_transmission_test_2.html), seems all refracted pixel are pushed to +Z axis a little?

@takahirox Any ideas?

**Comment by takahirox** [comment]
Unfortunately I currently have lack of time to tackle this problem.

> I tried with a simple box, seems all refracted pixel are pushed to +Z axis a little?

This guess sounds right to me. The ray is calculated in 

https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/transmission_pars_fragment.glsl.js

I'm happy if anyone can help the investigation in the details.

**Comment by mrdoob** [comment]
I've made a model that shows the issue: [TransmissionThickness.gltf.zip](https://github.com/mrdoob/three.js/files/6889124/TransmissionThickness.gltf.zip)

https://github.khronos.org/glTF-Sample-Viewer-Release/
<img width="824" alt="Screenshot 2021-07-27 at 23 54 16" src="https://user-images.githubusercontent.com/97088/127237935-1459801d-ff5d-4a66-ae73-fe93ce3484ec.png">

https://sandbox.babylonjs.com/
<img width="741" alt="Screenshot 2021-07-27 at 23 54 43" src="https://user-images.githubusercontent.com/97088/127237956-e6a1a7b1-bf20-4eb5-9708-66964e147fbc.png">

https://raw.githack.com/mrdoob/three.js/dev/editor/
<img width="652" alt="Screenshot 2021-07-27 at 23 55 50" src="https://user-images.githubusercontent.com/97088/127238021-e969730f-8c88-45ce-9ba6-f1e9989a0c51.png">

**Comment by takahirox** [comment]
Thanks for making the test model! The model looks correct in glTF sample viewer to which I referred for the transmission shader code.

![image](https://user-images.githubusercontent.com/7637832/127241125-ae0f0b5a-70ba-427d-a936-1732f14dc0fe.png)

So I guess I have wrongly editted the shader code calculating the ray or passed wrong parameters to the function.

**Comment by mrdoob** [comment]
@UX3D-eckerlein Any ideas of what we got wrong?

**Comment by mrdoob** [comment]
@whatisor Is this something you dealt with in your implementation?

**Comment by takahirox** [comment]
Probably I figured out the root issue. I have passed wrong normal parameter to the function. The function requires world normal but I have passed world normal applied view matrix.

This is the screenshot of Three.js + test model with the fix.

![image](https://user-images.githubusercontent.com/7637832/127600921-bfbff9b6-d3f3-42cc-bf84-97789d3bf4e9.png)

I will make a PR maybe tomorrow.

**Comment by takahirox** [comment]
#22224

**Comment by cx20** [comment]
Thank you for fixing the shader. I tried again with the latest version of the library. Looks good.

|Library|IridescentDishWithOlives.gltf - closed|IridescentDishWithOlives.gltf - open|
|:-----:|:-----:|:-----:|
|[glTF Sample Viewer](https://github.khronos.org/glTF-Sample-Viewer-Release/)|![image](https://user-images.githubusercontent.com/1833979/125325172-98dc7780-e37b-11eb-89fa-cf6bd7c678c6.png)|![image](https://user-images.githubusercontent.com/1833979/125325206-a3970c80-e37b-11eb-869b-b30ff4fd14e3.png)|
|[Three.js r131dev](https://rawcdn.githack.com/cx20/gltf-test/f1f30bbc31b35a15e2ede7a68d3d501c680f2d35/examples/threejs/index.html?category=tutorialModels&model=IridescentDishWithOlives&scale=8&type=glTF)|![image](https://user-images.githubusercontent.com/1833979/126012663-12b92386-9ceb-4917-b3d4-3a3ad9ecfdea.png)|![image](https://user-images.githubusercontent.com/1833979/126012675-08f9594e-bec1-4076-a7a5-3b37817d7c1c.png)|
|[Three.js r131.1](https://rawcdn.githack.com/cx20/gltf-test/3e7f6b221ff83599137185b3bc1061478fd020cf/examples/threejs/index.html?category=tutorialModels&model=IridescentDishWithOlives&scale=8&type=glTF)|![image](https://user-images.githubusercontent.com/1833979/127723183-377c6fba-0170-4bec-8285-79ebce6fd2ab.png)|![image](https://user-images.githubusercontent.com/1833979/127723190-0c8e6dd4-e87e-417e-baa7-e1057f0442b5.png)|

**Comment by rohan-percept** [comment]
@mrdoob What will it entail for WebGLRenderer getting updated to support this? Please let me know. I am ideally after (3), but even (2) would work well for the time being. I'd definitely want to contribute, but would love to get some directions or know where to start.

**Comment by rohan-percept** [comment]
I have a pair of acrylic spectacles that I am working on to show on WebGL container. See the image below.

Babylon-
![Screenshot 2021-10-15 at 17 52 46](https://user-images.githubusercontent.com/64609221/137524516-d3f0c19c-ed27-4e84-a238-bd61e10f3572.png)

Three-
![Screenshot 2021-10-15 at 17 52 31](https://user-images.githubusercontent.com/64609221/137524527-c9d2b86f-33ba-4e2e-ad23-45f501aeaf2d.png)

Only the stem has double mesh (frame will also have it). One has volume, transmission and ior, while other has only opacity via basecolourfactor property. This setup will enable me to see the stems through the frame and vice versa. 

The ideal scenario would be to have (3), so I can have half of the polycount, but this also works for the time being.

**Comment by rohan-percept** [comment]
Hi @mrdoob @donmccurdy, Would it be possible to get an idea or pointer in the right direction with regards to getting the alpha blend materials to show through transmission? I am pretty much new to three js and would appreciate some help.

**Comment by donmccurdy** [comment]
@rohan-percept sorry, I don't have pointers to get things started on (2) or (3).

**Comment by WestLangley** [comment]
Related: #23448

**Comment by mrdoob** [comment]
I think we could achieve something decent by doing:

1. Render all opaque meshes into the framebuffer.
2. Render all opaque meshes into RT1
3. Copy RT1 into RT2.
4. Use RT2 as transmission input and render the backside of all doublesided transmissive meshes into RT1.
5. Use RT1 as transmission input and render transmissive meshes into the framebuffer.
6. Render transparent meshes into the framebuffer.

Hmm, now that we're moving into WebGL2... Sooner or later we'll have to investigate rendering everything into a multisampled RT in linear and copying the RT into the framebuffer while applying gamma and tonemapping.

Although I think @Mugen87 tried this recently and it was slower than the current setup.

**Comment by gkjohnson** [comment]
> 4. Use RT2 as transmission input and render the backside of all doublesided transmissive meshes into RT1.
> 5. Use RT1 as transmission input and render transmissive meshes into the framebuffer.

I don't know if this is going to have all that great of an effect and probably wouldn't work well on the sun glasses example above. If backfaces are rendered first and used for transmission when rendering front faces then _every_ frontface transmission fragment is effectively going to have the transmission tint doubly applied (once for backside, once for frontside). And with refraction you'll probably get artifacts at the edges of the mesh when the refracted sample doesn't line up with the back face mesh edges.

And if only backfaces are used in the transmission then continuity of things like the top highlight caused by the front ridge of glasses side piece will be lost:

![image](https://user-images.githubusercontent.com/734200/153518212-e44ccbb7-4940-43ae-b8c3-60664ada6270.png)

Might be worth trying out I just expect there to be more issues than you might expect.

**Comment by Mugen87** [comment]
> Although I think @Mugen87 tried this recently and it was slower than the current setup.

Correct. Applying gamma and tone mapping in an additional render pass was noticeably slower than doing it inline. In certain examples, performance dropped from 60 to 40 FPS when using a FP32 render target, see https://github.com/mrdoob/three.js/issues/23019#issuecomment-1020493869.

**Comment by WestLangley** [comment]
Most of the issues raised in the original post have been addressed, so I think it is OK to close this now.
