### ISSUE TITLE
WebGLProgram: Make cacheKey human-readable

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#22011]
Make the program `cacheKey` more human-readable -- e.g., key-value pairs -- and then, for the purpose of programatic key comparisons,  use a _hash_ created from `cacheKey` instead.

**Comment by Mugen87** [comment]
May I ask why you think it's preferable to have the cache-key human readable? 

Right now, the implementation is focused on simplicity and performance. Having two different representations of the same thing means more code and potentially additional overhead.

**Comment by WestLangley** [comment]
In debugging three.js, I look at `renderer.info` to see what programs are created -- or disposed of. The cache-keys are very similar.

TBH, it is probably only worth it when I need it -- which is not that often anymore.
