### ISSUE TITLE
Possible TypeError with NRRDLoader

### ISSUE THREAD

**Issue by kirevdokimov** [mrdoob/three.js#22018]
# Description

`scan(type, chunks)` from [NRRDLoader](https://github.com/mrdoob/three.js/blob/a5ce030b9c692125e88f01cb978351766e5da590/examples/js/loaders/NRRDLoader.js) returns entity with type Array or number
https://github.com/mrdoob/three.js/blob/a5ce030b9c692125e88f01cb978351766e5da590/examples/js/loaders/NRRDLoader.js#L116-L118

https://github.com/mrdoob/three.js/blob/a5ce030b9c692125e88f01cb978351766e5da590/examples/js/loaders/NRRDLoader.js#L127-L131

but then `.length` is called over scan result
https://github.com/mrdoob/three.js/blob/a5ce030b9c692125e88f01cb978351766e5da590/examples/js/loaders/NRRDLoader.js#L294-L298

that can produce undefined value to _length variable.

Also .subarray could be called over number and throw an Error.
https://github.com/mrdoob/three.js/blob/a5ce030b9c692125e88f01cb978351766e5da590/examples/js/loaders/NRRDLoader.js#L319

**Comment by mrdoob** [comment]
@geoffkflee @IsseiMori @stity looks good?

**Comment by geoff-kf-lee** [comment]
I don't believe these lines of code have not been touched during the fix of the transformation of slices. We can do a deeper dive and clean out more of the assumptions made within the logic, but from what I understand this is a pre-existing issue and can be considered a separate investigation from issue #21898 

There's definite room for improvement for the NRRDLoader and am excited to help it grow!
