### ISSUE TITLE
Setting precision to lowp results in black objects in Safari

### ISSUE THREAD

**Issue by arthur7921** [mrdoob/three.js#22016]
**Describe the bug**

I change my WebglRenderer's precision to 'lowp',Evevrything is OK on my desktop's chrome, but in safari, some things became black(my scene image)

**Screenshots**
![c5c2c7c92363df7937f3c86e3105ff7](https://user-images.githubusercontent.com/51526225/122518431-c3b90180-d043-11eb-8599-d284921401fb.jpg)

**Platform:**

 - Device: [ipad]
 - OS: [iOS]
 - Browser: [Chrome,  Safari]
 - Three.js version: [r129]

**Comment by mrdoob** [comment]
I think desktop always use highp even if you set it to mediump or lowp. Objects rendering black sounds like something to expect.

Lowp is something you should only set when you wrote the shader yourself and you know lowp is enough for it.

**Comment by arthur7921** [comment]
> I think desktop always use highp even if you set it to mediump or lowp. Objects rendering black sounds like something to expect.
> 
> Lowp is something you should only set when you wrote the shader yourself and you know lowp is enough for it.

sorry, i forget to say: not only some Objects is black,but also shadow from directionLight, and i dont konw is it normal or an issue

**Comment by arthur7921** [comment]
> I think desktop always use highp even if you set it to mediump or lowp. Objects rendering black sounds like something to expect.
> 
> Lowp is something you should only set when you wrote the shader yourself and you know lowp is enough for it.

and i use ` console.log(renderer.capabilities.getMaxPrecision());` on my desktop's chrome, it shows 'lowp'.

**Comment by Mugen87** [comment]
Please shift the conversation to the [forum](https://discourse.threejs.org/). This is no `three.js` bug.
