### ISSUE TITLE
Missing argument on addEventListener for 'drop' event.

### ISSUE THREAD

**Issue by zuul** [mrdoob/three.js#22033]
On the dev branch, on [ui.three.js](https://github.com/mrdoob/three.js/blob/dev/editor/js/libs/ui.three.js#L39), and also on the master branch same [ui.three.js](https://github.com/mrdoob/three.js/blob/master/editor/js/libs/ui.three.js#L39) file, there's an event listener being added that uses the `event` variable inside the callback function, but that parameter isn't present.

***Code***

```
canvas.addEventListener( 'drop', function () {

	event.preventDefault();
	event.stopPropagation();
	loadFile( event.dataTransfer.files[ 0 ] );

}, false );
```

**Expected**

Callback function with the parameter `event` as used inside.

```
canvas.addEventListener( 'drop', function ( event ) {

	event.preventDefault();
	event.stopPropagation();
	loadFile( event.dataTransfer.files[ 0 ] );

}, false );
```

**Platform:**

Detected on Three.js version [master, r126], still present on [dev, r129] and [master, r129].

**Comment by Mugen87** [comment]
Good catch! Should be fixed via c55e5591aef8f6d56386297174cbfbb6b6c42859.
