### ISSUE TITLE
AnimationMixer uncache bug

### ISSUE THREAD

**Issue by mfkwgizhoujian** [mrdoob/three.js#22036]
**Describe the bug**

When calling the uncacheAction, uncacheClip, and uncacheRoot methods, an exception will be thrown.

**To Reproduce**

1. Load robot model in webgl_animation_skinning_morph example
2. Call the following js code
3. See error

***Code***

```js
clipCtrl.onChange( function () {
	fadeToAction( api.state, 0.5 );
        // The error will appear after two seconds
	setTimeout(() => {
		mixer.uncacheRoot(model);
	}, 2000);
} );

```

**Screenshots**

![D148A648-0A0B-44DE-B364-B7C0D547DB1C](https://user-images.githubusercontent.com/33543763/123023114-6dfca480-d409-11eb-9c16-ea59beb25e0a.png)

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: r129

**Comment by Mugen87** [comment]
Sorry, but what you have shared so far is not sufficient to understand the issue. If the code is used as intended, no runtime error appears. https://jsfiddle.net/hoy26z3a/2/

In the fiddle, the animation is stopped after 2 seconds and the related cached data are removed. Also notice that it does not make sense to call all three methods at the same time.

**Comment by mfkwgizhoujian** [comment]
> Sorry, but what you have shared so far is not sufficient to understand the issue. If the API is used as intended, no runtime error appears. https://jsfiddle.net/hoy26z3a/2/
> 
> In the fiddle, the animation is stopped after 2 seconds and the related cached data are removed. Also notice that it does not make sense to call all three methods at the same time. If you are using `uncacheRoot()` the other two are not required.

I updated the full test code. The problem lies in calling methods in the robotDo object. As long as the method in the robotDo object is called, and then the uncache operation is performed, an error will appear.

**Comment by Mugen87** [comment]
Please share your code as a live example. It's best to update the fiddle I have shared with my previous post: https://jsfiddle.net/hoy26z3a/2/

**Comment by mfkwgizhoujian** [comment]
> Please share your code as a live example (and without any dependencies like react). It's best to update the fiddle I have shared with my previous post: https://jsfiddle.net/hoy26z3a/2/

Sorry I can't visit this website, and I upload the code again. This problem is very easy to reproduce. Modify the official example of threejs "webgl_animation_skinning_morph.html", I added a timer to the state change event, and you can see the error after two seconds of state change.

**Comment by Mugen87** [comment]
I've debugged the issue for a while and can confirm that internals of `AnimationMixer` seem to get out-of-sync when bindings are added/removed. This needs more investigation.

As a workaround, call `stop()` on all animations before using `AnimationMixer.uncacheRoot()`.

**Comment by mfkwgizhoujian** [comment]
> I've debugged the issue for a while and can confirm that internals of `AnimationMixer` seem to get out-of-sync when bindings are added/removed. This needs more investigation.
> 
> As a workaround, call `stop()` on all animation actions before using `AnimationMixer.uncacheRoot()`.

OK,thanks.

**Comment by Mugen87** [comment]
Right now, it's hard to tell whether this is a bug or the expected behavior. Meaning the `uncache*` methods should only be used after certain or all animation actions are stopped.

For now, I think it's better to just update the documentation and mentioned the usage of `stop()`.
