### ISSUE TITLE
[GLTFLoader]: cache gltf texture which have same source, sampler and extensions but different textureIndex

### ISSUE THREAD

**Issue by deepkolos** [mrdoob/three.js#22037]
## Problem

using the same normalMap texture bewteen diffrent material in blender

blend file: [https://github.com/deepkolos/lazy-gltf-loader/blob/main/examples/banzi2.blend](https://github.com/deepkolos/lazy-gltf-loader/blob/main/examples/banzi2.blend)

![图片](https://user-images.githubusercontent.com/12824616/123108839-5820cb00-d46d-11eb-9823-deb042716d4c.png)

but the exported gltf file will look like this

gltf flile: [https://github.com/deepkolos/lazy-gltf-loader/blob/main/examples/banzi2/banzi2.gltf](https://github.com/deepkolos/lazy-gltf-loader/blob/main/examples/banzi2/banzi2.gltf)

```json
{
  ...
  "textures" : [
      {
          "sampler" : 0,
          "source" : 0
      },
      {
          "sampler" : 0,
          "source" : 1
      },
      {
          "sampler" : 0,
          "source" : 2
      },
      {
          "sampler" : 0,
          "source" : 3
      },
      {
          "sampler" : 0,
          "source" : 1
      },
      {
          "sampler" : 0,
          "source" : 2
      }
  ],
  ...
}
```

which means it will create duplicated texture with same source, sampler and extensions, upload duplicated texture to WebGL memory.

## Solution

update texture cache key

```js
/**
* Requests the specified dependency asynchronously, with caching.
* @param {string} type
* @param {number} index
* @return {Promise<Object3D|Material|THREE.Texture|AnimationClip|ArrayBuffer|Object>}
*/
getDependency( type, index ) {

  let cacheKey = type + ':' + index;

  // maping same source, sampler and extensions to the same texture
  if ( type == 'texture' ) {
    
    const textureDef = this.json.textures[index];
    cacheKey = type + ':' + textureDef.sampler + ':' + textureDef.source + ':' + JSON.stringify( textureDef.extensions );

  }

  let dependency = this.cache.get( cacheKey );
  ...
}
```

**Comment by deepkolos** [comment]
duplicated #21559

**Comment by deepkolos** [comment]
but the current solution may

**Comment by deepkolos** [comment]
maybe it is a common case that cache doesn't care about extensions. in this case, loadTexture, maybe so does other like loadMesh, loadBufferView, loadMaterial

**Comment by donmccurdy** [comment]
See https://github.com/mrdoob/three.js/pull/22038#issuecomment-867349612 — I think I would prefer to consider this a bug in the exporting software, rather than trying to detect deeply duplicated resources in a file.
