### ISSUE TITLE
[Feature request] Add show/hide booleans for 2-axis handles on TransformControls

### ISSUE THREAD

**Issue by MajorSquirrelTVS** [mrdoob/three.js#22045]
**Is your feature request related to a problem? Please describe.**

The TransformControls is a really helpful tool to manipulate/transform 3D objects directly from the scene. Its properties & events make it really easy to use, but sometimes I feel frustrated when I miss-click on the axis I want to manipulate because I just clicked on the 2-axis handles (the magenta / cyan / yellow ones) and it messed up everything. Usually, I don't need those handles at all, because I like to manipulate each axis separately.

I think those handles would deserve the same booleans to show/hide them as it already exists for each axis (showX, showY, showZ)

**Describe the solution you'd like**

The best option for me would be to have a boolean for each 2-axis handle to show/hide them.

**Describe alternatives you've considered**

I haven't considered any alternative yet as the proposed class is already suiting my needs, but my feature request would add up a nice cherry on the cake.

**Additional context**

Some screenshots to highlight the square handles (magenta / cyan / yellow)

![Screenshot from 2021-06-25 14-58-14](https://user-images.githubusercontent.com/10291631/123428511-2e2eec00-d5c6-11eb-9a26-51c4c676a2b0.png)
![Screenshot from 2021-06-25 14-57-57](https://user-images.githubusercontent.com/10291631/123428515-2e2eec00-d5c6-11eb-889a-0fdffcfc18c8.png)

**Comment by Mugen87** [comment]
Not sure about this feature request. Right now, I tend to leave the API as it is unless more people request it.

**Comment by mrdoob** [comment]
@MajorSquirrelTVS What do you think about the redesign? https://github.com/mrdoob/three.js/pull/22061

**Comment by MajorSquirrelTVS** [comment]
@mrdoob To be honest, I showed the new gizmo to my colleagues and we are quite mitigated between both old and new designs:

- About the 'translate' state, the new arrow tip that replaced the old inverted arrow seems less elegant and not really intuitive, but the inverted arrow also looked weird and it seems confusing for new users. I think we could simply display the extension of the existing arrow instead of a tip or an inverted arrow ?
- About the 'rotate' state, I think removing the old diamond shapes on the rotation circles make the tool less clear to use, as if we simply removed some visual reference to rotate an object properly. Having those shapes back may be better, especially when an user wants to switch its local/world space on-the-fly.
- Yellow-ing the hovered/selected axis + having a blank line to show the vector is really helpful, the old way was not intuitive as it seemed faded but not enough to be clear. Maybe de-saturate the non-hovered/non-selected axis could help more in the visualization ?
- Spacing the 2-axis handles from the origin also helps: the tool looks less compact and more easy to use. But it would be awesome to be able to enable/disable them separately also. :wink:

**Comment by tomeof** [comment]
@Mugen87 I would also suggest to use setter methods to apply the transformations in `TransformControls`:
`object.scale.x = Math.round( object.scale.x / this.scaleSnap ) * this.scaleSnap || this.scaleSnap;`
:point_down:
`object.scale.setX(Math.round( object.scale.x / this.scaleSnap ) * this.scaleSnap || this.scaleSnap);`
That way is easier to override the setter and apply min/max constraints.

**Comment by Mugen87** [comment]
Closing. The controls are already quite configurable (especially compared to other controls of the repo) and this specific feature request did not came up so far anymore. So if users need more gizmo customizations, it's best to create a custom version of `TransformControls`.
