### ISSUE TITLE
Color.getHSL returns lightness within 0..255 range instead of 0..1

### ISSUE THREAD

**Issue by maksnester** [mrdoob/three.js#22044]
**Describe the bug**

getHSL returns lightness within 0..255 range instead of 0..1

**To Reproduce**

```js
const { l: lightness } = new THREE.Color(255, 255, 255).getHSL({ h: 0, s: 0, l: 0});
expect(lightness).toBe(1) // fails
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/akc5vbwy/)

**Expected behaviour**

`.getHSL()` gives lightness within 0..1 range

**Comment by WestLangley** [comment]
In your example, it should be
```js
new THREE.Color( 1, 1, 1 )
```
or
```js
new THREE.Color( 'rgb( 255, 255, 255 )' )
```
