### ISSUE TITLE
OBJLoader should automatically load the materials

### ISSUE THREAD

**Issue by remmel** [mrdoob/three.js#22052]
In order to load an object it is required to first load the material `MTLoader` and then load the object `OBJLoader`
Because the name of the .mtl is written in the .obj (eg `mtllib male02.mtl`), I'd expect the OBJLoader to automatically load the material

https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_obj_mtl.html#L75

Currenlty I have to do :

```js
  var materials = await new MTLLoader()
    .loadAsync("https://example.com/obj/male02.mtl")
  materials.preload() //load imgs
  var group = await new OBJLoader()
    .setMaterials(materials)
    .loadAsync("https://example.com/obj/male02.obj")
```

but I'd like to do 
```js
  var group = await new OBJLoader()
    .loadAsync("https://example.com/obj/male02.obj")
```

To avoid complexifing too much OBJLoader, we could think having OBJMTLLoader something like :
```js
class OBJMTLLoader extends OBJLoader {
  load(url, onLoad, onProgress, onError) {
   // make sure that path is set
    if(!this.path) { //if the url provided is full url not fn
      this.setPath(url.substr(0,url.lastIndexOf('/'))) //FIXME dirname
      url = url.substr(url.lastIndexOf('/')) //url is fn
    }

    const scope = this
    const loader = new FileLoader(this.manager)
    loader.setPath(this.path)
    loader.setRequestHeader(this.requestHeader)
    loader.setWithCredentials(this.withCredentials)
    loader.load(url, text => {
      this.parseMtlAndLoad(text,  () =>{
        try {
          onLoad(scope.parse(text))
        } catch (e) {
          if (onError) {
            onError(e)
          } else {
            console.error(e)
          }
          scope.manager.itemError(url)
        }
      })
    }, onProgress, onError)
  }

  parseMtlAndLoad(text, onLoadMtl) {
    if(!this.materials) { //do not load a material if already provided
      let idxStart = text.indexOf("mtllib ")
      let idxEnd = text.indexOf(".mtl")
      if (idxStart !== -1 && idxEnd !== -1 && idxEnd - idxStart > 7) {
        var mtlFn = text.substring(idxStart + 7, idxEnd + 4); //to be improved, regex with end/start line; if has multiple mtl?
        new MTLLoader().loadAsync(this.path + "/" + mtlFn).then(materials => {
          materials.preload()
          this.setMaterials(materials)
          onLoadMtl()
        })
      }
    } else {
      onLoadMtl()
    }
  }
}
```

**Comment by Mugen87** [comment]
There was once an `OBJMTLLoader` but it was removed in favor of having two separate loaders.

Keep in mind that the OBJ format has separate material definitions because it assumes MTL files are shared between multiple OBJ assets. Having two separate loaders actually better maps to this specific design goal of OBJ.

TBH, I do not vote to bring `OBJMTLLoader` back but rather encourage devs to use glTF instead of OBJ/MTL.

**Comment by remmel** [comment]
Thanks for your reply, I see, the problem I get is that I need to parse the obj to know what it the name of the mtl and later the OBJLoader will load and parse again the same file; thus the .obj file is loaded and read twice.
I agree with your point of view but in my case it's more than .mtl is dependant of .obj
[OBJMTLLoader ](https://github.com/mrdoob/three.js/commits/master/examples/js/loaders/OBJMTLLoader.js) was able to create itself the .obj, we could instead have an OBJMTLLoader dependent of OBJLoader and MTLLoader to avoid duplicating code.
Another solution could be to add to OBJLoader callback when a .mtl is detected in file:
```js
var group = await new OBJLoader()
    .onMtlFnParsed((path, mtlFilename,onMtlLoaded) => { 
      new MTLLoader().loadAsync(path+"/"+mtlFilenmae).then(material => onMtlLoaded)
    }
    .loadAsync("https://example.com/obj/male02.obj")
```
It looks a little complicated to implement because of callbacks ([parse ](https://github.com/mrdoob/three.js/blob/d39d82999f0ac5cdd1b4eb9f4aba3f9626f32ab6/examples/jsm/loaders/OBJLoader.js#L724)should returns a Group and not a promise), or we should be able to re-set the material after the Group creation. Maybe this is not so great as we mix Loader and Parse parts

I agree with you that we should use glTF instead, if possible

**Comment by mrdoob** [comment]
Would something like this help?

```js
const loader = new OBJLoader();
loader.setMTLLoader( new MTLLoader() );
```
