### ISSUE TITLE
使用es6的方式导入loaders，webpack5编译时报错。

### ISSUE THREAD

**Issue by llj0028** [mrdoob/three.js#22058]
![image](https://user-images.githubusercontent.com/32165861/123779213-84709780-d904-11eb-8e9a-9e84ca755ca5.png)
根据报错提示安装了@babel/runtime后仍然报相同的错。

**Comment by llj0028** [comment]
使用的导入方式如下：
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

**Comment by llj0028** [comment]
奇怪的是，使用commonJS的方式导入就不会报错；CommonJS导入方式如下所示：
const THREE = window.THREE = require('three');
require('three/examples/js/loaders/OBJLoader');

**Comment by mrdoob** [comment]
Sorry, we do not speak Chinese...
