### ISSUE TITLE
WebGLMultisampleRenderTarget's antialiased color blends with background even though NoBlending is set

### ISSUE THREAD

**Issue by asbjornlystrup** [mrdoob/three.js#22078]
The problem:
When you render into a `WebGLMultisampleRenderTarget` whose alpha is cleared to 0, the antialiased pixels are blended with the destination color even though the mesh material used has blending set to `NoBlending`. With no blending, it's expected that the antialiased pixels should get the same color as the mesh. In the first image below, the destination color before the mesh render (RGBA) is (0, 0, 0, 0), hence the antialiased pixels get darkened, but they should really become green. With e.g. (1, 0, 0, 0) instead, the antialiased pixels get tinted with red as seen in the second screenshot. Reducing the mesh's opacity works correctly and renders without darkening/color tint, so this seems to be an issue with the antialiasing, not a general blending issue. I've also tried with `CustomBlending` with `OneFactor` and `ZeroFactor` as an alternative, but that didn't work either.

Live demo: https://jsfiddle.net/v4w78dt1/33/

![image](https://user-images.githubusercontent.com/9470947/124260651-37710900-db30-11eb-9fe7-d6759ba11792.png)

![image](https://user-images.githubusercontent.com/9470947/124260870-7acb7780-db30-11eb-9160-23b8dcc67ba9.png)

I found the bug as I was converting my old screen-space outline shader to improve its antialiasing (FXAA has disadvantages). I need to be able to render multiple colors to the render target, so I can't just work around it by clearing the render target to the same color. In my project, the mesh material I use is a `ShaderMaterial` with my own vertex and fragment shader, and I don't use any imports inside it (apart form logarithmic depth). Here's the fragment shader:
```
uniform vec3 color;
uniform float opacity;

#include <logdepthbuf_pars_fragment>

void main() {
  #include <logdepthbuf_fragment>
  
  gl_FragColor = vec4(color, opacity);
}
```
So it does not seem to be a shader issue. I've messed around with the `premultipliedAlpha` toggles and other parameters as well with no luck.

I have not found any work-around, so I'm curious about work-arounds as well. (I will mention that I ran into another `WebGLMultisampleRenderTarget` bug as well, but I found a work-around for that, so I haven't posted it. The lines I've commented out at the end of the jsfiddle is related to that other bug; it's a bug with `renderer.setClearColor` not working correctly when alpha < 1)

 - Device: Desktop
 - OS: Linux Ubuntu
 - Browser: Chrome
 - Three.js version: r128

**Comment by Mugen87** [comment]
Can you please verify first if this also happens with plain WebGL? 

In general, we only investigate bugs in the `three.js` implementation. If the above result also happens without `three.js` or with other 3D engines, it's better to discuss this topic elsewhere (e.g. at stackoverflow).

**Comment by asbjornlystrup** [comment]
As for now, I went back to FXAA, and it's not as bad as I remembered. I will keep the issue in mind and write some WebGL to test if I get time. Seems like a pretty general bug to have for WebGL, but who knows, you might be right.

**Comment by Mugen87** [comment]
A pure WebGL test case would be fantastic since if this is a potential bug, a test case would be very useful for filing an issue at the browser vendors.

**Comment by Mugen87** [comment]
Let's reopen the issue if it turns out to be a `three.js` bug.
