### ISSUE TITLE
WebXR (Oculus) Line Geometry abnormal visibility 

### ISSUE THREAD

**Issue by meh301** [mrdoob/three.js#22088]
**Describe the bug**

When drawing a line between the webXR controllers, this line will only be visible if you tilt your head down to a certain angle (this angle is the same in all scenarios I think). 

Here is a video demonstrating the issue: https://youtu.be/wSSep5m87KM

**To Reproduce**

1. Draw a BufferGeometry Line with two arbitrary vertexes.
2. in the animation loop, update the Line's position array with controller positions.
3. enter VR mode and look up a certain angle.

***Code***

```js
let distpoints = [];
distpoints.push(new THREE.Vector3(0, 0, 0));
distpoints.push(new THREE.Vector3(0, 0, 0));
let linegeometry = new THREE.BufferGeometry().setFromPoints(distpoints);
let distmaterial = new THREE.LineBasicMaterial({ color: 0xff0000 });
let distanceline = new THREE.Line(linegeometry, distmaterial);
scene.add(distanceline);

[...]
function animation(time) {

let leftpos = controllerGrip1.position;
let rightpos = controllerGrip2.position;
distanceline.geometry.attributes.position.array[0] = leftpos.x;
distanceline.geometry.attributes.position.array[1] = leftpos.y;
distanceline.geometry.attributes.position.array[2] = leftpos.z;

distanceline.geometry.attributes.position.array[3] = rightpos.x;
distanceline.geometry.attributes.position.array[4] = rightpos.y;
distanceline.geometry.attributes.position.array[5] = rightpos.z;
distanceline.geometry.attributes.position.needsUpdate = true;

}

```

***Live example***
https://youtu.be/wSSep5m87KM

**Expected behavior**

Visibility of line unaffected by the direction of where the user is looking.

**Platform:**

 - Device: Quest 2
 - OS: user-17007100222900000
 - Browser: quest browser
 - Three.js version: r124

**Other nodes:**
I am not a programmer (well I wasn't supposed to be >__>) so if I am missing something blatantly obvious, don't hesitate to say so!
I only tested this on the Oculus Quest 2 and without utilizing the official webXR controller models.

**Comment by Mugen87** [comment]
Does it work if you add this line to your code:
```js
distanceline.frustumCulled = false;
```

**Comment by meh301** [comment]
> Does it work if you add this line to your code:
> 
> ```js
> distanceline.frustumCulled = false;
> ```

Yes this ensures that the line is rendered! Thanks! Though from the documentation this boolean simply forces it to be rendered regardless of occlusion right? What could be occluding said line in the first place? Maybe the head bounding box?

**Comment by Mugen87** [comment]
It's not about occlusion. When a 3D object is fully outside of the camera's view frustum, the object is not rendered by default. The test is also optimistic since it is based on the object's bounding sphere.

Whenever you modify the `position` attribute of vertices, it's important to recompute the bounding sphere (and bounding box). Otherwise they do not represent the real bounds of the object.

Can you fix the issue by adding this line after the vertex update:
```js
distanceline.geometry.computeBoundingSphere();
```

**Comment by meh301** [comment]
I see... I did not know that I also needed to recompute the bounding box/sphere in such a situation. It works when it is recomputed!
