### ISSUE TITLE
Animations running at different FPS between browsers

### ISSUE THREAD

**Issue by ryancalizadeh** [mrdoob/three.js#22080]
**Describe the bug**

In a video game I am developing, there appears to be a rendering issue on non-chromium based browsers which causes frame rate issues. Specifically, the game consistently runs at ~50 fps on chromium based browsers (tested on Opera, Chrome, Chromium, and Edge) versus Firefox, where it runs at ~20 fps. On Firefox, I observed that the average frame rendering time scales at a 1:1 ratio with window size/resolution, which suggests the bottleneck is Fragment Processing (per [this source](https://paroj.github.io/gltut/apas04.html)). This was observed across 2 devices, one Linux and one Windows. [This thread](https://bugzilla.mozilla.org/show_bug.cgi?id=1517916) on Bugzilla describes a similar issue.

**To Reproduce**

I've observed the issue in example code taken straight out of the [ThreeJS Docs](https://threejs.org/docs/#manual/en/introduction/Creating-a-scene), which I've slightly modified to include a Stats object (Pasted below). To reproduce, simply run the following Javascript in Firefox in fullscreen (or at least 1920x1080) and compare with Chrome (or any chromium based browser) at the same resolution. I've provided a live example in jsfiddle as well, but because it renders the scene in a smaller window (lower resolution) you might not observe the issue.

***Code***

```js
import * as THREE from "https://threejs.org/build/three.module.js";
import Stats from "https://threejs.org/examples/jsm/libs/stats.module.js";

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );
const stats = Stats();

const renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );
document.body.appendChild( renderer.domElement );
document.body.appendChild( stats.dom );

const geometry = new THREE.BoxGeometry();
const material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
const cube = new THREE.Mesh( geometry, material );
scene.add( cube );

camera.position.z = 5;

const animate = function () {
  stats.update();
	requestAnimationFrame( animate );

	cube.rotation.x += 0.01;
	cube.rotation.y += 0.01;

	renderer.render( scene, camera );
};

stats.begin();
animate();
```

***Live example***

* [jsfiddle](https://jsfiddle.net/hmLx6de8/11/)

**Platform:**

 - Device: Desktop
 - OS: reproduced on Windows and Linux
 - Browser: Firefox
 - Three.js version: 0.130.0

**Comment by Mugen87** [comment]
Sorry, but this is not a `three.js` issue. Better to report this to Mozilla: https://bugzilla.mozilla.org/
