### ISSUE TITLE
HTMLMesh is creating a lot of canvas objects.

### ISSUE THREAD

**Issue by sigmaxipi** [mrdoob/three.js#22093]
1. Open https://threejs.org/examples/?q=vr#webxr_vr_sandbox or another example using `HTMLMesh`.
2. Set a breakpoint on [`var canvas = document.createElement( 'canvas' );`](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/interactive/HTMLMesh.js#L250) or log at `document.createElement` via `ce = document.createElement; document.createElement = function() { console.log('ce' + arguments[0]); return ce.apply(document, arguments)}` in the console.
3. Interact with the GUI and hit the breakpoint.

Are all these canvases required?

I [cached the canvas](https://github.com/sigmaxipi/three.js/commit/c9625673e71d06144bcd5fa8241a5c29ed2504ac) and both the webxr_vr_sandbox demo and threejs/editor appeared to work without any issues.

I can submit a PR if you're OK with the changes.

***Live example***
https://threejs.org/examples/webxr_vr_sandbox.html vs https://raw.githack.com/sigmaxipi/three.js/dev/examples/webxr_vr_sandbox.html

https://threejs.org/editor/ vs https://raw.githack.com/sigmaxipi/three.js/dev/editor/

**Platform:**
 - Device: Quest
 - Three.js version: dev

**Comment by Mugen87** [comment]
My comment: https://github.com/sigmaxipi/three.js/commit/c9625673e71d06144bcd5fa8241a5c29ed2504ac#r53096778

**Comment by mrdoob** [comment]
No wonder the fps were dropping when interacting with these... 😅

**Comment by mrdoob** [comment]
I think I prefer to let `html2canvas` handle this.

**Comment by Degubi** [comment]
Hi!
I was looking at HTMLMesh (for absolutely no specific reason)
I noticed that we read from the canvas cache, but we never set anything anywhere?

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/interactive/HTMLMesh.js#L474

We read here, but we never set it in the else branch, I think this might be a mistake
I commented here because it was this PR that added the canvas cache
