### ISSUE TITLE
MRT with ShaderMaterrial

### ISSUE THREAD

**Issue by DavidPeicho** [mrdoob/three.js#22092]
**Is your feature request related to a problem? Please describe.**

Right now, we can only use MRTs with `RawShaderMaterial`.

**Describe the solution you'd like**

I believe it should be possible to extend that to ShaderMaterial, by using a specific set of defines for instance.

**Describe alternatives you've considered**

Basically using `RawShaderMaterial` directly 😄 

## Ideas

I think it could look something like:

```js
material.outputs = {
  'myOutput1': 'vec3',
  ...
  'myOutputN': 'vec4',
};
material.needsUpdate = true;
```

Obviously, trying to use invalid outputs with the wrong shader will lead to errors, but that's expected.
I guess @takahirox  should be involved in the discussion.

**Comment by RenaudRohlinger** [comment]
MRTs already works with ShaderMaterial @DavidPeicho. Or am I misunderstanding the issue?

**Comment by Mugen87** [comment]
Yes, it should already work. Here is the official example with `ShaderMaterial`: https://jsfiddle.net/mw7jsgqz/

**Comment by DavidPeicho** [comment]
My bad then! I think I missed this part. I will close this then!

**Comment by mrdoob** [comment]
@Mugen87 Should we change the example in the repo so it uses `ShaderMaterial` instead?

**Comment by DavidPeicho** [comment]
I think it's better to use ShaderMaterial whenever possible, but it was still my mistake 🤦
