### ISSUE TITLE
Add option to not call `event.preventDefault()` in the example controls?

### ISSUE THREAD

**Issue by will-ca** [mrdoob/three.js#22091]
**Is your feature request related to a problem? Please describe.**

`event.preventDefault()` is currently called by the example camera controls. This prevents using those examples for building apps where you still want to react to all cursor and touch inputs.

**Describe the solution you'd like**

A flag should be available to control whether `.preventDefault()` gets called by each control object.

It should be enabled by default, so it will be a non-breaking change.

Users that desire more control over their event handling can then unset it and manually handle bubbling events elsewhere in their code.

I suggest adding `.suppressEvents : Boolean` property to the camera control examples. I think all of the calls can then be quickly wrapped with a simple REGEX:

`(.*)(event.preventDefault\(\))(.*)`
`\1if (this.suppressEvents) {\n\1\t\2\3\n\1}`

**Describe alternatives you've considered**

None, since it's hardcoded into the controls and I don't think there's really any way to undo it from outside.

If this change would be accepted, I'll do the PR myself.

Is there a process for keeping the `.js` and `.jsm` modules in sync? Or would I have to just manually make the changes to both of them?

**Additional context**

Old discussion: https://discourse.threejs.org/t/mouseup-event-does-not-work-along-with-orbitcontrols/20432

Maybe a related issue: https://github.com/mrdoob/three.js/issues/20191

**Comment by Mugen87** [comment]
Are you aware that with `r130` the calls of `preventDefault()` were removed from most control classes?

Please read #21889 for more information. In general, we have the goal to remove these calls whenever possible.

**Comment by will-ca** [comment]
Oh, cool! It came less than out an hour before I opened this issue, haha.

I did search for related discussion, but didn't spot that PR. Thanks for pointing me to it. Closing this issue, as the new release fixes the issues in my own app and it looks like adding an extra option is moot now.
