### ISSUE TITLE
FBX file clone bug with animation

### ISSUE THREAD

**Issue by mfkwgizhoujian** [mrdoob/three.js#22105]
**Describe the bug**

After loading the FBX model with animation, clone the model, the animations attribute of the model is empty, and the cloned new model cannot be displayed.

**To Reproduce**

1. Open the official example 'webgl_loader_fbx.html'
2. Modify the original code to the following JS code
3. Only the original model is displayed

***Code***

```js
loader.load( 'models/fbx/Samba Dancing.fbx', function ( object ) {

	mixer = new THREE.AnimationMixer( object );

	const action = mixer.clipAction( object.animations[ 0 ] );
	action.play();

	object.traverse( function ( child ) {

		if ( child.isMesh ) {

			child.castShadow = true;
			child.receiveShadow = true;

		}

	} );

	scene.add( object );

        // add the following code
	let cloneObj = object.clone();
	cloneObj.position.x += 50;
	scene.add(cloneObj);

} );
```

**Screenshots**

<img width="1557" alt="iShot2021-07-09 10 12 54" src="https://user-images.githubusercontent.com/33543763/125013347-46126f80-e09e-11eb-835a-0ba2b3847f57.png">
![Uploading iShot2021-07-09 10.10.54.png…]()

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: r130

**Comment by NewKrok** [comment]
I had similiar issue and I found this thread as a solution, maybe it could help for you too:
https://discourse.threejs.org/t/cloning-a-skinned-mesh/4775
https://github.com/mrdoob/three.js/issues/11574

```
const clonedFBX = THREE.SkeletonUtils.clone(fbxModel);
```

**Comment by Mugen87** [comment]
Yes, cloning an skinned mesh requires the usage of `SkeletonUtils.clone()`.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.
