### ISSUE TITLE
Selection in desktop browsers on CSS3DRenderer

### ISSUE THREAD

**Issue by tom-adsfund** [mrdoob/three.js#22104]
I just updated my app to use r128 (via CDN), and when using CSS3DRenderer and OrbitControls (the latest code from examples), there is now unwanted selection while dragging the mouse.

**Comment by Mugen87** [comment]
This seems to be a side effect of removing `preventDefault()` from the control classes. As a workaround, set the `user-select` CSS class of all instances of `CSS3DObject` to `none`.

@mrdoob Are you okay with adding `this.element.style.userSelect = 'none';` to the `CSS3DObject` and `CSS2DObject` ctor?

**Comment by tom-adsfund** [comment]
There's an additional problem: if it's an image being dragged, it causes the drag and drop to start, which also breaks it.

**Comment by Mugen87** [comment]
In this case, the `draggable` attribute of the DOM element can be set to `false`.

**Comment by tom-adsfund** [comment]
Does this work properly with child elements? I think I tried adding draggable, but it didn't apply to the children too.

**Comment by Mugen87** [comment]
It seems this edge case has to be fixed on app level.

**Comment by tom-adsfund** [comment]
Why was it changed from r127? Because I'm using that and it works perfectly. Would it be possible to just revert?

**Comment by tom-adsfund** [comment]
Also it doesn't really seem to be an edge case, since it should be assumed regular compositions of elements would be used. If it's required, my guess is that propagation should be at the library level.

**Comment by Mugen87** [comment]
> Would it be possible to just revert?

No, sorry. The calls of `preventDefault()` in control classes were much more problematic. Besides, the only way to change the behavior was updating library code.

The remaining issue reported here can easily be fixed on app level.

**Comment by tom-adsfund** [comment]
OK, wouldn't it be better to have the propagation in the library so other people don't have to work it out? I'm not clear immediately how to do it.

**Comment by tom-adsfund** [comment]
Actually, it's probably not possible because of children being added dynamically. I'll just have to work it out for my case.
