### ISSUE TITLE
[Shaders] ColorCorrectionShader has default uniform value as (2,2,2) instead of (1,1,1) which leads to darker color 

### ISSUE THREAD

**Issue by optimus007** [mrdoob/three.js#22129]
**Describe the bug**
While using the ColorCorrectionShader , just enabling it without changing any values is leading to darker colors 
then i noticed the default power vector value is set to 2,2,2  when i changed it to 1,1,1 default value behavior seems correct

settings used :
renderer.outputEncoding=Linear
Passes which were Added 
- renderpass
- colorCorrectionPass
- gammaCorrectionPass

Line 14 in ColorCorrectionShader :
https://github.com/mrdoob/three.js/blob/d0340e3a147e290fa86d14bc3ed97d8e1c20602e/examples/jsm/shaders/ColorCorrectionShader.js#L14

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [r129]

**Comment by Mugen87** [comment]
A default value does not mean that it produce "no effect". So I'm not sure it's worth to change the default value and risk breakage.
