### ISSUE TITLE
Auto-generated files in the /js directory place comments in the wrong place

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#22130]
This can be a bit confusing, I think. Maybe there is an easy fix?

https://github.com/mrdoob/three.js/blob/c97a3e5598597b4f96365b1ff0323e04b8e92b8e/examples/js/controls/OrbitControls.js#L54-L66

**Comment by marcofugaro** [comment]
No easy fix that I know of. They are messed up by [babel](https://github.com/mrdoob/three.js/blob/c97a3e5598597b4f96365b1ff0323e04b8e92b8e/utils/build/rollup.examples.config.js#L175-L179), which is there in case users want to compile the examples with IE11 support.

**Comment by WestLangley** [comment]
@marcofugaro Oh well, thanks for your reply. :-)
