### ISSUE TITLE
Editor: Support for PLY point clouds

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#22133]
When this PLY file is dropped into the Editor, it is treated as a Mesh -- selecting `PointsMaterial` is not available as an option.

```code
ply
format ascii 1.0
element vertex 3
property float x
property float y
property float z
property uint8 red
property uint8 green
property uint8 blue
end_header
10.0 10.0 0.0 255 100 0
-10.0 10.0 0.0 0 100 255
0.0 0.0 0.0 100 255 0
```

`BufferGeometry` does not have a property to indicate what kind of geometry it represents.

**Comment by Mugen87** [comment]
I think we can use the same approach like for `drc` files. If a PLY file contains faces, the loader produces an index. If not index is set, it's a point cloud:

https://github.com/mrdoob/three.js/blob/c97a3e5598597b4f96365b1ff0323e04b8e92b8e/editor/js/Loader.js#L185-L201
