### ISSUE TITLE
Animating objects using animations in other fbx files

### ISSUE THREAD

**Issue by shadowredwine** [mrdoob/three.js#22158]
hello

**Is your feature request related to a problem? Please describe.**

Your Three.js is no problem. but My situation requires your help.
I have been using unity for a long time.
In particular, the dependence on the Asset Store is quite high.
The fbx files in the asset store are often divided into one mesh file and multiple animation files.
Of course, all extensions are .fbx.
The fbx file provided with mesh and animation integrated works well without any problems.

**Describe the solution you'd like**

I want to utilize the split fbx data.

**Describe alternatives you've considered**

I need a function that reads an fbx file containing animation, adds it to an object with only a mesh, and plays the mesh.

**Additional context**

I am attaching the split fbx file sample and the source code I tried.
[ask.zip](https://github.com/mrdoob/three.js/files/6848181/ask.zip)

**Comment by WestLangley** [comment]
Sorry, this is not a help site. You can use the three.js [forum](https://discourse.threejs.org) for help.
