### ISSUE TITLE
fail to fbx load

### ISSUE THREAD

**Issue by shadowredwine** [mrdoob/three.js#22154]
hello I has fbx file. but has not merged with texture file.
This file load without texture on  your three.js editor.
but, Has loaded with animation
plz check, my fbx file attached
[Lady Fish.zip](https://github.com/mrdoob/three.js/files/6844510/Lady.Fish.zip)
[Lady Fish.zip](https://github.com/mrdoob/three.js/files/6844511/Lady.Fish.zip)

**Comment by WestLangley** [comment]
In the Editor, set the texture as the material `map` and add a `DirectionalLight` to the scene.

<img width="502" alt="Screen Shot 2021-07-19 at 8 27 53 PM" src="https://user-images.githubusercontent.com/1000017/126244287-34ed9f61-a7f3-4d4e-addd-dd559b245883.png">

**Comment by shadowredwine** [comment]
thank you. I see too.
I can see by a texture apply to material
