### ISSUE TITLE
InstancedBufferGeometry.instanceCount becomes undefined after copy()

### ISSUE THREAD

**Issue by paulsmirnov** [mrdoob/three.js#22151]
**Describe the bug**

In r117 (#19135) you renamed `maxInstancedCount` to `instanceCount` AND changed the default value from `undefined` to `Infinity`. However, there is a rare case when it still becomes undefined: copying from a non-instanced geometry.

**To Reproduce**

If you call `instancedGeo.copy(simpleGeo);` it overwrites `Infinity` with `undefined`. Then, during rendering, it is converted to `NaN` and passed to `drawElementsInstancedANGLE`.

See [the changes](https://github.com/mrdoob/three.js/pull/19135/files):

![20210719-121610](https://user-images.githubusercontent.com/11373544/126136677-d47c1c44-b0b3-404f-8fab-201ff21150d1.png)

In r116 this undefined value perfectly worked, so we have a regression here.

I cannot provide a small working example yet, just a code review.

**Expected behavior**

`InstancedBufferGeometry.copy()` should be able to copy from any `BufferGeometry`, instanced or not.

**Platform:**

 - Device: any
 - OS: any
 - Browser: any
 - Three.js version: r117 and up

**Comment by Mugen87** [comment]
> InstancedBufferGeometry.copy() should be able to copy from any BufferGeometry, instanced or not.

Sorry, but this is not the expected behavior. Copy methods in `three.js` expect the given object is from the same type.

**Comment by paulsmirnov** [comment]
Hi @Mugen87. Sorry to hear that. Would you add a type check then? Quite a surprise in five years of three.js usage :)

`InstancedBufferGeometry` inherits this method from `BufferGeometry`, and it explicitly states type requirements:

```plain
.copy ( bufferGeometry : BufferGeometry ) : BufferGeometry
```

which are true for any BufferGeometry, not only instanced. See https://threejs.org/docs/index.html?q=Insta#api/en/core/BufferGeometry.copy

**Comment by Mugen87** [comment]
The class actually overwrites the method:

https://github.com/mrdoob/three.js/blob/d6fcfa5606539967a77b6b84fbab239206054d14/src/core/InstancedBufferGeometry.js#L14-L22

But yes, it would be more correct to update the documentation and add an entry to the `InstancedBufferGeometry` page with the correct type.

**Comment by paulsmirnov** [comment]
Thanks for clarifying.
