### ISSUE TITLE
Docs: BufferGeometry link broken.

### ISSUE THREAD

**Issue by gonnavis** [mrdoob/three.js#22159]
**Describe the bug**

https://threejs.org/docs/?q=buffer#api/en/core/BufferGeometry 
auto-redirected to 
https://threejs.org/docs/?q=buffer#api/en/core/Geometry and broken.

Other links, eg: 
https://threejs.org/docs/?q=buffer#api/en/core/BufferAttribute works well.

**To Reproduce**

1. Go to https://threejs.org/docs/?q=buffer#api/en/core/BufferGeometry
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/10785634/126327094-c09cf232-04fa-4b76-b338-14afef5f87f6.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows 10]
 - Browser: [Chrome]
 - Three.js version: [r130]

**Comment by Mugen87** [comment]
This was introduced by #22153. I'll have a look.

**Comment by Mugen87** [comment]
Fixed 35bdc42a8115c7404997b9ef9b9e7fdb832a5099.

**Comment by Mugen87** [comment]
@mrdoob I've patched `gh-pages`, too 👍 .

**Comment by Mugen87** [comment]
We might want to remove the redirect at the end of the year or so. Code like that is a bit error-prone.

**Comment by mrdoob** [comment]
> @mrdoob I've patched `gh-pages`, too 👍 .

Thanks!

**Comment by mrdoob** [comment]
@Mugen87 Maybe this is more readable?

```js
if ( /Instanced/.exec( window.location.hash ) && /([\w]+)BufferGeometry$/.exec( window.location.hash ) ) {
```

**Comment by Mugen87** [comment]
I think the first part has to be negated since the code in the `if` clause should not be executed when `Instanced` is part of the URL. Adding ` !== null` to the first test might work. What do you think?

**Comment by mrdoob** [comment]
Ah! Yes 👍

```js
if ( /Instanced/.exec( window.location.hash ) !== null && /([\w]+)BufferGeometry$/.exec( window.location.hash ) ) {
```

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/ec5fb63a0b557474844f458065e5b26a22667e4e
