### ISSUE TITLE
GLTFExporter: Lacks an ability to support shader materials by plugins

### ISSUE THREAD

**Issue by 0b5vr** [mrdoob/three.js#22163]
### Is your feature request related to a problem? Please describe.

I'm currently working on [@pixiv/three-vrm](https://github.com/pixiv/three-vrm), trying to export VRM using GLTFExporter.

In VRM, we are using a custom material called `MToonMaterial` (`VRMC_materials_mtoon` as a glTF extension) which inherits `ShaderMaterial` .
I have tried to support export of MToonMaterial using GLTFExporter plugin system but this line prevents doing so:

https://github.com/mrdoob/three.js/blob/d0340e3a147e290fa86d14bc3ed97d8e1c20602e/examples/jsm/exporters/GLTFExporter.js#L1121-L1126

`_invokeAll` of `writeMaterial` is far below from these lines.

An instance of `MToonMaterial` has both `.isShaderMaterial` and `.isMToonMaterial` .

### Describe the solution you'd like

I want to give a way to export specific `ShaderMaterial` s when appropriate plugins exist.

Before working on, I have to hear the policy about GLTFExporter.
I should probably ping @donmccurdy and @takahirox .

### Describe alternatives you've considered

My other options are:

- Create a fork of `GLTFExporter`
    - Don't want to do if I don't have to since plugin system exists
- Change the base class of MToonMaterial to `MeshStandardMaterial` or something GLTFExporter supports
    - I can do this if we use `material.onBeforeCompile`

### Additional context

-

**Comment by phillip-mcnallen-tfs** [comment]
I've handled this sort of thing by packing information into gltf extras fields by extending GLTFExporter since its a behavior outside the gltf 2.0 spec.  Likewise for loading GLTF with application specific behaviors.

**Comment by donmccurdy** [comment]
Do you have an idea of what new hook(s) would be needed in GLTFExporter to support this? If that's 1-2 small hooks I think this would be reasonable, but forking GLTFExporter for use cases as serious as VRM is not a bad idea either, in my opinion.

**Comment by DepponYangRui** [comment]
I meet the same question when I export the line mesh created by line2 to glTF, and console print the same warn. Because the LineMaterial class extends ShaderMaterial. Do you have any solution?

**Comment by donmccurdy** [comment]
The code that processes and exports materials in GLTFExporter is not particularly complex. If someone would like to make a PR that allows it to export line and point materials, that'd be great:

https://github.com/mrdoob/three.js/blob/1c553914ace73127cc67660597806b2c7c013548/examples/jsm/exporters/GLTFExporter.js#L1204-L1221

As for the original issue — if we plugin hooks for GLTFExporter are needed to userland extensions for materials, PRs are also welcome. But I don't know what hooks are needed, and I don't think we need a GitHub issue tracking that unknown feature.
