### ISSUE TITLE
PMREM Debug Map Regression

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#22197]
#22178 has broken the debug map on `webgl_materials_envmaps_exr.html`.

The `render()` method should not reset the GUI parameters every frame, but given the current implementation,  a start at a fix is:

```js
const cubeUVMap = renderer.properties.get( torusMesh.material ).envMap;
planeMesh.material.map = cubeUVMap;
```
Thing is, the cubeUV maps are generate lazily and are not yet available, so some other implementation is required.

/ping @Mugen87 

 - Three.js version: [dev131]

**Comment by WestLangley** [comment]
In other use cases, in my own fork, I am temporarily using this hack in `init()`, prior to the first render:

```js
renderer.compile( scene, camera );
const cubeUVMap = renderer.properties.get( mesh.material ).envMap;
```

That is unappealing to me, though.

**Comment by mrdoob** [comment]
@WestLangley

Rather than a regression, am I right thinking that what you're looking for is for a way of looking at the generated PMREMs inside the renderer?

**Comment by Mugen87** [comment]
I wonder if `three` dev utils could visualize the PMREMs in some way? 🤔

**Comment by WestLangley** [comment]
I want to visualize the PMREM created by the _renderer_ for a given material.

I have no desire to visualize a PMREM created by the app.
