### ISSUE TITLE
It is recommended to add a callback function for Texture loading success

### ISSUE THREAD

**Issue by Jeggery** [mrdoob/three.js#22192]
For example, when the model is loaded, there are automatically guided maps in the model, but we cannot externally monitor when the map is loaded, only the model is loaded, so this function is proposed

**Comment by Mugen87** [comment]
You can use `THREE.LoadingManager.onProgress()` for this use case. https://jsfiddle.net/tkyvxLn5/

**Comment by Jeggery** [comment]
> 用于

You may have misunderstood my needs，What I want is that the external monitor map load is complete, and then notify, as shown in the following figure
![贴图功能](https://user-images.githubusercontent.com/39072827/127123355-f157c536-1730-45c3-b169-ba65a258a2d1.png)
In this way, the external can confirm that the map loading is done by redefining the oncomplete function.
This is the simple way I personally want, but I don't want to change the source code. I hope the official can add similar functions
