### ISSUE TITLE
Simple four-point NURBS Curve is interpreted badly.

### ISSUE THREAD

**Issue by msimpson** [mrdoob/three.js#22198]
**Description**

A NURBS curve is being interpreted badly by the `FBXLoader`.

The curve is a simple four-point diamond:

```
Geometry: 1714157613440, "Geometry::", "NurbsCurve" {
	GeometryVersion: 124
	Type: "NurbsCurve"
	NurbsCurveVersion: 100
	Order: 2
	Dimension: 3
	Form: "Closed"
	Rational: 0
	Points: *16 {
		a: 857.9216016,0,-0,1,0,0,-857.9216016,1,-857.9216016,0,-0,1,0,0,857.9216016,1
	} 
	KnotVector: *7 {
		a: 1,1,2,3,4,5,5
	} 
}
```

However, the intermediate points in the resulting `Line` geometry are off near the corners (see below).

Assuming @looeee can help/advise.

**EDIT**

FYI, this was exported from C4D.

So I'll understand if `NURBSCurve` is being misled by something with the `knots`, etc. and it's not Three's fault.

**To Reproduce**

Load the following FBX ([diamond.zip](https://github.com/mrdoob/three.js/files/6887800/diamond.zip)) in the three.js editor.

_Note that you'll need to scale down quite a lot (0.005 or more) as it was pulled from a separate scene._

![image](https://user-images.githubusercontent.com/730334/127207134-3fbb4ab5-cbf3-4788-8f87-557765305d4a.png)

**Platform:**

 - Device: Any
 - OS: Any
 - Browser: Any
 - Three.js version: r130

**Comment by WestLangley** [comment]
This code block is a bit verbose.
https://github.com/mrdoob/three.js/blob/e0000acdb5c72a1992f545b87c1f7436a6ac2855/examples/jsm/loaders/FBXLoader.js#L2298-L2309
It can be rewritten as
```js
const geometry = new BufferGeometry();
geometry.setFromPoints( curve.getPoints( controlPoints.length * 7 ) );
```
A reasonable guess is `controlPoints.length * 7` is not enough to accurately represent the curve in this case.

**Comment by msimpson** [comment]
Thanks!
