### ISSUE TITLE
Updating Chrome browser to v92 from v86 results in very bad performance issue

### ISSUE THREAD

**Issue by niuge8905** [mrdoob/three.js#22195]
**Describe the bug**

After updating Chrome browser from v86 to v92, it exits a very bad performance issue. as it autmatically generates many InstancedMesh objects.

**To Reproduce**

1. apply newest three.js 
2. apply newest chrome

**Expected behavior**

expect less than 30ms. However, according to screenshot, it takes 300ms

**Screenshots**
![94B582E4-12DC-4b72-B072-72AF4D891DA1](https://user-images.githubusercontent.com/31625395/127135132-3a346971-44ab-4cc6-9668-9737df6afd1e.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows,]
 - Browser: [Chrome]
 - Three.js version: [dev, ^0.130.1]

**Comment by mrdoob** [comment]
Can you create a jsfiddle that reproduces this and then create an issue in https://bugs.chromium.org/p/chromium/issues/list?

**Comment by makc** [comment]
There is no need for jsfiddle, I see a major fps drop for every webgl content in chrome 92 vs firefox at the same mac. I just accepted this as something I cannot do anything about 😭

**Comment by arpu** [comment]
you can try chrome canery  with the VAO fix https://bugs.chromium.org/p/chromium/issues/detail?id=1192082

**Comment by mrdoob** [comment]
Sorry, we can't do much without some code that clearly shows the performance regression.

**Comment by niuge8905** [comment]
Since this is a relatively large project, it is not good to extract the JS code alone. We use a lot of instancedmesh, and the model is large, so the performance decreases greatly.And I think&nbsp;no need for jsfiddle.


I have tested that the main influencing factors are the APIs in my screenshot. These api look like the api of webgl, so I can't modify the code. Is there any other way to solve this problem?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mrdoob/three.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 晚上10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mrdoob/three.js] Updating Chrome browser to v92 from v86 results in very bad performance issue (#22195)





 
Sorry, we can't do much without some code that clearly shows the performance regression.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mugen87** [comment]
The only way to track down the issue is to create a small test case with plain WebGL in order to demonstrate costly WebGL commands. 

If the performance problem does not appear with other browsers like Firefox, it's best to file and issue at the Chromium bugtacker.
