### ISSUE TITLE
webgl read float buffer error on IOS device

### ISSUE THREAD

**Issue by Tasaddar12** [mrdoob/three.js#22207]
**Describe the bug**

I recieve the following error in the console (Checked by connecting the device to my computer and used the dev console):
THREE.WebGLRenderer.readRenderTargetPixels: readPixels from renderTarget failed. Framebuffer not complete.

This bug occurs when I attempt to read pixels from the RenderTarget.

IOS : 14.4.1
MODEL: iPad mini 4
TESTED BROWSERS: Chrome, Safari

**To Reproduce**

This error can be found simply by opening with an IOS mobile device : 
https://threejs.org/examples/#webgl_read_float_buffer
or
https://threejs.org/examples/webgl_read_float_buffer.html

***Code***

```js
function render() {

				const time = Date.now() * 0.0015;

				if ( zmesh1 && zmesh2 ) {

					zmesh1.rotation.y = - time;
					zmesh2.rotation.y = - time + Math.PI / 2;

				}

				if ( material.uniforms[ "time" ].value > 1 || material.uniforms[ "time" ].value < 0 ) {

					delta *= - 1;

				}

				material.uniforms[ "time" ].value += delta;

				renderer.clear();

				// Render first scene into texture

				renderer.setRenderTarget( rtTexture );
				renderer.clear();
				renderer.render( sceneRTT, cameraRTT );

				// Render full screen quad with generated texture

				renderer.setRenderTarget( null );
				renderer.render( sceneScreen, cameraRTT );

				const read = new Float32Array( 4 );
				renderer.readRenderTargetPixels( rtTexture, windowHalfX + mouseX, windowHalfY - mouseY, 1, 1, read );

				valueNode.innerHTML = 'r:' + read[ 0 ] + '<br/>g:' + read[ 1 ] + '<br/>b:' + read[ 2 ];

			}
```
Specifically the renderer.readRenderTargetPixels seems to be the main issue.

***Live example***

https://threejs.org/examples/#webgl_read_float_buffer
or
https://threejs.org/examples/webgl_read_float_buffer.html

**Expected behavior**

I was hoping to get the pixel from the readRenderTargetPixels without any error.

**Screenshots**

![Screenshot from 2021-07-28 13-45-58](https://user-images.githubusercontent.com/61332370/127371777-3c50ccb8-a0f3-4c38-ad27-718cbc0823cd.png)

**Platform:**

 - Device: iPad mini 4
 - OS: IOS 14.4.1
 - Browser: Safari, and Chrome tested
 - Three.js version: Github version

**Comment by Mugen87** [comment]
Can you please try the solution in #15762?

As soon as WebKit supports WebGL 2, this issue should automatically disappear.

**Comment by Tasaddar12** [comment]
I have tried to do that on my own code and it still failed with the same error.
I am assuming the following is your reference:
https://github.com/mrdoob/three.js/issues/15762#issuecomment-462823333 

This has not solved my issue.

**Comment by mrdoob** [comment]
I can confirm the example works correctly with Safari/iOS 15 🎉

**Comment by robertoranon** [comment]
I get a black screen on both Safari/IOS 17 and Safari / iPad OS 17 when running this example from latest three.js: is this a known issue?

**Comment by Mugen87** [comment]
@robertoranon Please report this to Apple/WebKit instead. Especially when things worked with earlier iOS versions.

**Comment by robertoranon** [comment]
done: https://bugs.webkit.org/show_bug.cgi?id=264404
I have also confirmed, through browserstack, that the example works in iOS 16

**Comment by robertoranon** [comment]
an update on this, Webkit people say that OES_texture_float_linear is not supported on iOS devices, despite iOS 16 incorrectly advertising so (and thus probably working on some devices only?):

https://bugs.webkit.org/show_bug.cgi?id=264404#c2

This example should be probably updated to use HalfFloats to work on iOS
