### ISSUE TITLE
Usdz exporter transparency not applied on iOS

### ISSUE THREAD

**Issue by pikilipita** [mrdoob/three.js#22205]
It seems the usdz textures transparency is indeed supported in the preview app on macOS, 
but on iphone, on AR quick look, the transparency is gone.

Tested on iPhone 11, ios 14.6 + ios 14.7

![ios usdz no alpha](https://user-images.githubusercontent.com/1799792/126642514-d3153ad3-1b35-4355-b339-ad99b019c4a8.jpeg)
<img width="1020" alt="macos preview alpha ok" src="https://user-images.githubusercontent.com/1799792/126642560-f9b80af1-44da-488d-a89e-ecf6af9ff739.png">

live test:
[https://xr.plus/9tb](https://xr.plus/9tb)

**Comment by mrdoob** [comment]
Have you seen any working usdz file that uses transparent textures?
I don't think the iOS viewer support it.

**Comment by pikilipita** [comment]
On this sport car example linked from Apple, the back red lights have a semi transparent cover:
https://www.lamborghini.com/en-en/models/huracan/huracan-evo-rwd-spyder#ar

**Comment by mrdoob** [comment]
What do you mean transparent cover? Do you mean the windshield?

**Comment by pikilipita** [comment]
To keep the comparaison simple, 

I've now produced an usdz from the same png image, but made with the 'Reality composer' app, and the transparency is indeed fine on the iOS viewer.

link:
https://xr.plus/t56

**Comment by mrdoob** [comment]
Can you share the usdz file you created with Reality composer?

**Comment by pikilipita** [comment]
Sure, here's a direct link to the file:
https://xr.plus/s/202107/t56/model.usdz

**Comment by sercandemirtas** [comment]
@mrdoob @pikilipita Hey guys, 

I created this cube with Blender. Used png image for texture and converted glb to usdz with macos terminal. It works fine and there is no black part on quick-look. 

Live link--
https://www.basebros.com/usdz-test.html. (via model-viewer)

Usdz file link---
https://www.basebros.com/assets/test.usdz

Glb file link---
https://www.basebros.com/assets/test.glb

I think problem is on USDZ Exporter.
