### ISSUE TITLE
Broken geometry on subsurface scattering exemple with safari

### ISSUE THREAD

**Issue by Nicoooooo** [mrdoob/three.js#22216]
Hello,

**Bug description**

The rabbit geometry is broken in the subsurface scattering exemple with Safari (macOS Big Sur 11.4, Safari 14.1.1 (16611.2.7.1.4)). Ils seems to work fine with Google Chrome.

**To Reproduce**

Open https://threejs.org/examples/?q=tran#webgl_materials_subsurface_scattering with Safari 14 on MacOS

**Platform:**

 - Device: MacBook Pro 16 2019
 - OS: MacOS Big Sur 11.4
 - Browser: Safari

**Screenshot**
<img width="1599" alt="Capture d’écran 2021-07-29 à 18 31 09 1" src="https://user-images.githubusercontent.com/15833774/127530127-07d23cfd-7e4c-4df3-a7a9-1396a6c88487.png">

**Comment by mrdoob** [comment]
I can't reproduce this.

Can you try with Safari Beta and with Safari Technology Preview?

https://developer.apple.com/safari/download/

**Comment by marcofugaro** [comment]
I can't reproduce this either. The only difference for me is the device.

<img width="931" alt="Screenshot 2021-07-29 at 18 40 45" src="https://user-images.githubusercontent.com/7217420/127531418-b4984267-709f-4b81-8104-c23c91d13469.png">

**Comment by Nicoooooo** [comment]
The example works correctly with Safari Technology Preview on my computer (but is much slower)
I guess it's specific to the model used then.

<img width="1585" alt="Capture d’écran 2021-07-29 à 19 11 18" src="https://user-images.githubusercontent.com/15833774/127535736-d36957dc-6fef-4ad4-8405-05a7573f4516.png">

**Comment by mrdoob** [comment]
Seems like this is a Safari issue. Please, report it to Apple if you can.
