### ISSUE TITLE
THREE.Box3().setFromObject()  is Error

### ISSUE THREAD

**Issue by peterpanBest** [mrdoob/three.js#22223]
const _box = new THREE.Box3().setFromObject(obj)
_box.getSize()

I use this method to get my model size, but have some error.

Cannot read property 'set' of undefined -- Box3.getSize

I used three.js version is 0.131.x

Thanks !

**Comment by WestLangley** [comment]
Sorry, this is not a help site. Use the [three.js forum](https://discourse.threejs.org) for help.

I expect you can use the debugger and find your error yourself, however.
