### ISSUE TITLE
Transmission examples not working on Galaxy M30

### ISSUE THREAD

**Issue by optimus007** [mrdoob/three.js#22226]
**Describe the bug**

On Chrome on my android phone both transmission examples https://threejs.org/examples/?q=transmission seems to be loading a black page. With USB debugging I took the screen shot below of the error displayed.

**Screenshots**

![transmission example](https://user-images.githubusercontent.com/6885294/127650739-c2eb8882-c07a-49ce-9ac0-295f13008ce2.png)

**Platform:**

 - Device: [ Mobile]
 - Samsung Galaxy M30 (does not support ARcore but webgl stuff runs fine )
 - OS: [ Android]
 - Browser: [Chrome]
 - Three.js version: [r131]

**Comment by mrdoob** [comment]
Hmm, this is going to be hard to figure out with a device...

**Comment by optimus007** [comment]
After some local testing
i found out that the problem is due to the hdri .
i changed the hdri url to "https://threejs.org/examples/textures/equirectangular/quarry_01_1k.hdr" and its working now 

![hdrc](https://user-images.githubusercontent.com/6885294/127669318-66e23aa1-8e4a-4801-a821-1a79333305a0.png)

**Comment by Mugen87** [comment]
There are certain mobile devices which do not support filtering of floating point textures. We were aware of that when changing the texture type to `THREE.FloatType`. 

To verify, can you please open https://webglreport.com/?v=2 and share a screenshot of the result? I bet `OES_texture_float_linear` is not supported.

**Comment by optimus007** [comment]
Oh 

![Screenshot_20210730-202731_Chrome](https://user-images.githubusercontent.com/6885294/127672322-a51f9028-be7a-43a3-a293-021da5470a63.jpg)

**Comment by Mugen87** [comment]
As expected `OES_texture_float_linear` is missing. Hence only filtering with half float point textures work.

**Comment by Mugen87** [comment]
@mrdoob It depends a bit on your preference but I would do nothing for now unless more users complain.

**Comment by WestLangley** [comment]
https://caniuse.com/?search=OES_texture_float_linear

**Comment by Mugen87** [comment]
Notice that checking the browser support for WebGL extensions is not meaningful. It's a matter of device support. Unfortunately, I'm not aware of statistics how good `OES_texture_float_linear` is supported on mobile devices.

E.g. `OES_texture_float_linear` is supported on a Pixel 4a but not on the latest iPad.

**Comment by Mugen87** [comment]
Reconsidering this issue. I vote to use this pattern in the examples:
```js
const dataType = renderer.extensions.has( 'OES_texture_float_linear' ) ? THREE.FloatType : THREE.HalfFloatType;
const loader = new RGBELoader().setDataType( dataType );
```
The additional line of code seems acceptable to me. It also shows the users the solution for supporting as many devices as possible.

**Comment by Mugen87** [comment]
@mrdoob Should we give this code a try or keep the exclusive usage of `THREE.FloatType`?

**Comment by mrdoob** [comment]
@Mugen87 

> Notice that checking the browser support for WebGL extensions is not meaningful. 

If I remember correctly that was mainly a iOS issue, right? If so, I think that will go away in Safari 15.

Leaving that case aside... Could `WebGLRenderer` automatically use `THREE.HalfFloatType` when trying to use `THREE.FloatType` in a context that doesn't have `OES_texture_float_linear` support?

**Comment by Mugen87** [comment]
Yes, that should be possible.

The information about the data type is currently required in the loader to properly prepare the data texture. Assuming a texture of type `THREE.FloatType` is returned, the renderer would have to convert the resulting single precision floating point data texture to half precision by converting each texel via `DataUtils.toHalfFloat()`.

**Comment by Mugen87** [comment]
Small downside of this approach. It's less precise than converting from a JavaScript number (which is a double) to half float. However, I don't know relevant the respective precision loss is.

**Comment by mrdoob** [comment]
> You also process texture data twice. It's faster if the loader knows the texture type in advance.

Ah, true. Then I think [your approach](https://github.com/mrdoob/three.js/issues/22226#issuecomment-890312612) is best 👍
