### ISSUE TITLE
Provide option to merge common vertices in Text and Extrude Geometery 

### ISSUE THREAD

**Issue by optimus007** [mrdoob/three.js#22232]
**Is your feature request related to a problem? Please describe.**
I'm Making a realtime text & shapes exporter for AR and the glb file size seems to quite high .
In blender i noticed that each triangle is a unique face and and the duplicate vertices were piling up leading to increased glb size
![text](https://user-images.githubusercontent.com/6885294/127745915-03f62686-b505-431a-951d-bf3b57a48d74.png)

**Describe the solution you'd like**
An option/update if possible to merge common vertices on extruded text and shape meshes

Extra:
Before And after removing duplicate vertices in blender
Before
![b4](https://user-images.githubusercontent.com/6885294/127745656-0722e2b0-5d3c-490a-9c86-60961837be7d.png)

After
![afta](https://user-images.githubusercontent.com/6885294/127745657-f0593d2a-259d-49bc-8ce5-e9024324b70d.png)

**Comment by WestLangley** [comment]
Shared vertices have shared normals. Did you consider that case?

**Comment by Mugen87** [comment]
> Shared vertices have shared normals.

Also true for texture coordinates. 

@optimus007 Sorry, but providing and option for blindly merging vertices would quickly lead to unwanted behavior with lit and textured materials.

**Comment by optimus007** [comment]
yeah ... vertices need to be merged , new custom normals need to be created and then uvs need to be handled  ...the complexity is close to a 3d software now .. so leave it 

also what will [mergeVertices](https://threejs.org/docs/#examples/en/utils/BufferGeometryUtils.mergeVertices) do on this geometry ? will it have any effect ?

**Comment by Mugen87** [comment]
Please ask help questions at the forum.
