### ISSUE TITLE
Matcap with Normal map not working on sketchfab gltf but works with gltf exported from blender

### ISSUE THREAD

**Issue by optimus007** [mrdoob/three.js#22245]
**Describe the bug**

All gltfs from sketchfab which i tested are not able to turn on matcap + normalmap . 
If i open the same model  in blender & re export as gltf then matcap + normalMap works

**To Reproduce**

1. Get these models:
-  from sketchfab: [ZIP](https://github.com/mrdoob/three.js/files/6917844/modular_sci-fi_wall_test_2.zip) taken from [here](https://sketchfab.com/3d-models/modular-sci-fi-wall-test-2-060031f51d7246379186bbc626be13b9)

- blender version : [blenderExport.zip](https://github.com/mrdoob/three.js/files/6917876/blenderExport.zip)

2. turn on matcap 
3. set model's normalmap as matcapMaterial.normalMap

**Screenshots**

gltf from sketchfab
![error](https://user-images.githubusercontent.com/6885294/127882084-33725abb-c2ca-4ae8-9522-d381b0eb3368.png)

same gltf from blender
![after](https://user-images.githubusercontent.com/6885294/127882813-3bcee29a-fa52-403c-8abd-35db55a89941.png)

**Platform:**

 - Device: [Desktop,]
 - OS: [Windows,]
 - Browser: [Chrome]
 - Three.js version: [r131]
 
 _if anyone can let me know how to add an external model(in this case gltf+bin+textures)  into jsfiddle ...i'll setup a fiddle also_

**Comment by WestLangley** [comment]
`MeshMatcapMaterial` does not support vertex tangents.

Unfortunately, the renderer now requires the vertex tangents to be used if they are present in the model.

Try modifying the geometry and removing the attribute tangents.

**Comment by WestLangley** [comment]
`MeshMatcapMaterial` currently does not support vertex tangents.

Unfortunately, the renderer now requires the vertex tangents to be used if they are present in the model.

Previous to that change, the mesh would have rendered without a problem.

I will add vertex tangent support to `MeshMatcapMaterial`.

In the mean time, if you modify the geometry and remove the attribute tangents, it should render.

**Comment by optimus007** [comment]
Cool


_Here's the code to implement the temporary fix mentioned above , add this bit before using matcap with normal map_ 

`if(mesh.geometry.hasAttribute ('tangent')){
mesh.geometry.deleteAttribute('tangent')
}`
