### ISSUE TITLE
Morphtargets comparison causes a new Program to be created each frame

### ISSUE THREAD

**Issue by Donitzo** [mrdoob/three.js#22256]
The morphTargets comparison for any material appears to return false no matter what, causing a new program to be created each frame.

```js
if ( materialProperties.morphTargets !== morphTargets )
```

To reproduce, add a breakpoint before program changes due to needsProgramChange === true.

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/22255#issuecomment-891808725
