### ISSUE TITLE
Transparent double-sided materials causes a new Program to be created each frame

### ISSUE THREAD

**Issue by Donitzo** [mrdoob/three.js#22255]
As the title says, if a material uses side = THREE.DoubleSide and transparent, it causes the material properties version to increment each frame creating a new program.

To reproduce, add a breakpoint before program changes due to needsProgramChange === true, and use the following material:
```js
const material = new THREE.MeshBasicMaterial({
  transparent: true,
  side: THREE.DoubleSide,
});
```

Due to an additional issue which I will submit, the morphTargets will also cause a new program to be created each frame. That issue hides this issue.

**Comment by Mugen87** [comment]
> Due to an additional issue which I will submit, the morphTargets will also cause a new program to be created each frame. 

This should already be fixed on `dev`, see #22244.

**Comment by Mugen87** [comment]
> it causes the material properties version to increment each frame creating a new program.

I don't think that's true. Programs are internally cached and you can see in the debugger that material holds two programs for each render pass. They are reused and not recreated.

**Comment by Donitzo** [comment]
Ah, I understand. I thought that it was constantly updating the material since the material version is incrementing by 1 each frame.

**Comment by Mugen87** [comment]
>  since the material version is incrementing by 1 each frame

The `version` updates are a small side effect in using `needsUpdate` in `renderObject()`: 

https://github.com/mrdoob/three.js/blob/434b33e5d6811d82082172ed8a18d787818d930a/src/renderers/WebGLRenderer.js#L1355-L1367

However, it does not recompile shaders.

**Comment by Donitzo** [comment]
Ah, now I get it.

Then all that remains is a mystery lag when a transparent double-sided object enters the screen the first time, despite calling compile on the entire non-frustum culled scene. Are these materials not pre-compiled?

**Comment by Mugen87** [comment]
AIFACS, `compile()` does not precompile the shader programs for double sided materials. The method would require a similar code like `renderObject()`.

Good catch! Do you mind creating a new issue for this?
