### ISSUE TITLE
Bad performance and stutters on iOS when using lights + shadows

### ISSUE THREAD

**Issue by larsvdv** [mrdoob/three.js#22254]
**Describe the bug**

Some of the light + shadows on iOS Safari cause stutters while showing 50+ fps in the fps graph. Also the lightmap is not working on iOS Safari and MacOS Safari: https://threejs.org/examples/?q=light#webgl_materials_lightmap

**To Reproduce**

1. Go to: https://threejs.org/examples/?q=light#webgl_lights_physical on your iPad using Safari.
2. Move around and watch at it begins to stutter while maintaining 50+ fps according to the fps graph.
3. Turn of shadows to make the stutters go away.

Steps to reproduce the behavior 2:
1. Go to: https://threejs.org/examples/?q=light#webgl_lights_hemisphere on you iPad using Safari.
2. With the both the lights turned on the demo starts stuttering aswell as the examples bar on the left. This is stuttering while maintaining 60fps according to the fps graph.
3. Try this again with the directional light turned off and it runs at it should.

***Live example***

https://www.youtube.com/watch?v=vNbH2IKNVH4&ab_channel=Lars

**Expected behavior**

The expected behavior is that it runs smoothly without stutters when it shows a constant 60fps in the fps graph while using lighting + shadows.

**Platform:**
- Device: iPad 2020 7th generation
- OS: iOS 14.7.1
- Browser: Safari

**Comment by Mugen87** [comment]
> Also the lightmap is not working on iOS Safari and MacOS Safari

Safari does not support to use `await` at module top level. This will be fixed with Safari 15 🎉 .

**Comment by mrdoob** [comment]
Seems like Apple usually releases a new version of iOS around September 15.

Depending of how many reports we get we could try to fix some before then...

I've been told https://threejs.org/examples/#webgl_loader_gltf is also [broken](https://user-images.githubusercontent.com/97088/128021140-d740863a-5527-493c-b8e6-d3a2b8354905.png).

(Currently I only have a iOS device with iOS 15 beta so I can't repro)

**Comment by larsvdv** [comment]
> I've tested `webgl_lights_physical` and `webgl_lights_hemisphere` on an iPad (8. generation) with iOS 14.7 and I can't reproduce the performance issue demonstrated in the YouTube video.

That's odd. Do you think the A12 chip is that much better then the A10 or is there something wrong with my device?

**Comment by Mugen87** [comment]
I guess it would be helpful if someone else with an iPad 7th generation could test both examples. TBH, it seems strange if the hardware would be the reason for the performance difference. Especially since `webgl_lights_hemisphere` is not a complex scene. It should definitely run without lags.

**Comment by stefandouw** [comment]
I have the exact same issue, also with a 2020 7th gen iPad.

**Comment by Mugen87** [comment]
If other iOS don't show this issue, it's probably related to this particular iPad model. In this case, one should consider to report the issue here: https://bugs.webkit.org/

**Comment by Mugen87** [comment]
Sorry, this issue can't be fixed in `three.js`. Please report the issue to Apple instead.
