### ISSUE TITLE
 WebGLRenderer#compile does not precompile transparent double sided materials

### ISSUE THREAD

**Issue by Donitzo** [mrdoob/three.js#22258]
Double sided materials in a scene are not pre-compiled using WebGLRenderer#compile. The material is compiled the first time the object is rendered, and may cause a significant lag during runtime.

To reproduce the issue:
```js
const renderer = new THREE.WebGLRenderer();

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera();

const geometry = new THREE.BoxGeometry();
const material = new THREE.MeshBasicMaterial({
  side: THREE.DoubleSide,
  transparent: true
});

const mesh = new THREE.Mesh(geometry, material);
mesh.frustumCulled = false;
scene.add(mesh);

renderer.compile(scene, camera);
renderer.render(scene, camera);
```

**Comment by Mugen87** [comment]
Details: https://github.com/mrdoob/three.js/issues/22255#issuecomment-891843883

**Comment by WestLangley** [comment]
>Double sided materials in a scene are not pre-compiled using WebGLRenderer#compile.

I think it is only for double-sided and _transparent_ materials that is this an issue.

The material _is_ precompiled as double-sided -- it is just never rendered as such. It is rendered as front-sided and back-sided. Those cases are not precompiled.
