### ISSUE TITLE
Suggestion for improving renderer.info

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#22251]
This has been considered in #19888 and #19894, but can we reconsider it?

Instead of
```js
WebGLProgram {name: "RawShaderMaterial", id: 0, …}
WebGLProgram {name: "RawShaderMaterial", id: 1,  …}
WebGLProgram {name: "ShaderMaterial", id: 2, …}
WebGLProgram {name: "MeshStandardMaterial", id: 3, …}
WebGLProgram {name: "MeshStandardMaterial", id: 4, …}
```
This would be more informative
```js
WebGLProgram {name: "PMREMSphericalGaussianBlur", id: 0, …}
WebGLProgram {name: "PMREMCubemapToCubeUV", id: 1, …}
WebGLProgram {name: "BackgroundCubeMaterial", id: 2, …}
WebGLProgram {name: "MeshStandardMaterial", id: 3, …}
WebGLProgram {name: "MeshStandardMaterial", id: 4, …}
```

In WebGLPrograms.js, do something like this:

```js
function ReplaceNonAscii( str ) {

	return str.toString().replace( /[^\x20-\x7E]/g, '_' );

}

shaderName: ReplaceNonAscii( material.name ) || material.type, // or encodeURIComponent( material.name )
```

**Comment by Mugen87** [comment]
Interestingly, the reproduction test case of #19888 does not fail for me on Chrome and Safari anymore.  Only Firefox breaks. Tested on macOS. Can somebody please verify?

https://jsfiddle.net/b7op6yku/1/

**Comment by WestLangley** [comment]
[WebGL Specification: Characters Outside the GLSL Source Character Set](https://www.khronos.org/registry/webgl/specs/latest/1.0/#6.21).

**Comment by WestLangley** [comment]
[WebGL Specification: Characters Outside the GLSL Source Character Set](https://www.khronos.org/registry/webgl/specs/latest/1.0/#6.21).

**Comment by makc** [comment]
> does not fail for me on Chrome and Safari anymore. Only Firefox breaks.

same, FF says
> WebGL warning: shaderSource: `source` contains illegal character 0xffffffc3.

weslagleys link thing, for quick ref.:
![Screen Shot 2021-08-07 at 2 02 58 ](https://user-images.githubusercontent.com/242577/128581182-60f7e373-c3f3-4973-ba85-d3ba91389dc9.png)
