### ISSUE TITLE
Fontloader on Chromium-Based Browsers does not load TextGeometry with custom fonts 

### ISSUE THREAD

**Issue by heytdep** [mrdoob/three.js#22262]
Hey, Three team. I'm reporting a bug happening on Chromium-based browsers preventing Custom Fonts(TTF converted to JSON with https://gero3.github.io/facetype.js/) to be displayed and throwing the following error:
```
THREE.Object3D.add: object not an instance of THREE.Object3D
```
This does not occur on Firefox. I have not yet found anything about this one in the issues, so I'm reporting(apologies if duplicate).

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**To Reproduce**

1. Download any TTF online and convert it using [this tool](https://gero3.github.io/facetype.js/)
2. Load it using the code below
3. See error on console

***Code***

The code I am using is the following:

```js
const loader = new THREE.FontLoader()
    loader.load('../assets/fonts/Style Script_Regular.json', function (font) {
        // About Me Descr Text 2
        let buildAboutMeDescrTextWall2;
        (buildAboutMeDescrTextWall2 = function (){
            const mainColor = 0xF3B3A6;
            const matDark = new THREE.LineBasicMaterial( {
                color: mainColor,
                side: THREE.DoubleSide,
            } );
            const mainMessage = "text"
            const mainTextgeometry = new THREE.TextGeometry(mainMessage, {
                font: font,
                size: 30,
                height: 5,
            });
            mainTextgeometry.computeBoundingBox();
            const xMid = - 0.5 * ( mainTextgeometry.boundingBox.max.x - mainTextgeometry.boundingBox.min.x );
            mainTextgeometry.translate( xMid, 0, 10 );
            window.aboutMeDescrTextWall2 = new THREE.Mesh( mainTextgeometry, matDark );
            aboutMeDescrTextWall2.position.set(-830, 1450, 1880);
            aboutMeDescrTextWall2.rotation.y = Math.PI/2 +1;
            aboutMeDescrTextWall2.rotation.x = 0;
            aboutMeDescrTextWall2.rotation.z = 0;
        })();
    })

// some code

scene.add(window.aboutMeDescrTextWall2)

```
**Expected behavior**

The text should show as happens on Firefox 

**Platform:**

The issue occurs on both Ubuntu-based latest popOS and on macOS High Sierra. The browsers with this issue are Safari, Chrome and Brave

**Comment by heytdep** [comment]
Hey, I just confirmed that when loading the `helvetiker_regular.typeface.json` font, the Mesh displays correctly

**Comment by Mugen87** [comment]
I've dowloaded `Sable Lion` from http://www.myfont.de/fonts/alphabet/ttf-fonts-S.html for verification.

I've converted the font via `Facetype.js` and imported it in `webgl_geometry_text`. The result looks like so:

![image](https://user-images.githubusercontent.com/12612165/128143671-dc814cd1-e699-4c59-814a-e02d5efbb334.png)

I've also loaded the TTF file directly via `TTFLoader` by adding it to `webgl_loader_ttf`.

![image](https://user-images.githubusercontent.com/12612165/128143742-4f2f5779-27a9-4d77-a2a6-be480d58c24f.png)

Both results look as expected.

Tested on macOS 10.15.7 with latest Chrome (92.0.4515.131).

**Comment by heytdep** [comment]
Hi, just tested with sable lion following your steps. I've found that when loading the Mesh locally on the function that creates the geometry etc, it works also on chrome. But when I make the variable global and add it later with the other Meshes, it does not work.

Maybe there is a difference on how Firefox processes global variables compared to chrome?

**Comment by Mugen87** [comment]
Sorry, this is not a help site. Please use the [forum](https://discourse.threejs.org/) or stackoverflow.
