### ISSUE TITLE
Cannot read property 'traverse' of undefined

### ISSUE THREAD

**Issue by Brucewu998** [mrdoob/three.js#22273]
**Describe the bug**

When I use `Object3D.traverse ` to traverse object in the scene and remove it, I get an error: 
![image](https://user-images.githubusercontent.com/23524793/128300876-0eedf2a0-d902-4ca8-ad5b-fc9c51bbba64.png)

***Code***

```js
scene.traverse((item) => {
      if (item.isMesh) {
          this.meshes.remove(item);
          item.geometry.dispose();
          item.material.dispose();
      }
});
```

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by Brucewu998** [comment]
> Please use the [forum](https://discourse.threejs.org/) for help requests.

thanks
