### ISSUE TITLE
Bug when importing a 3d model of gltf format made in blender 

### ISSUE THREAD

**Issue by roshan1230** [mrdoob/three.js#22283]
I was trying to import this model from a scene and I was exporting the trampolines placed but apparently. it doesn't import and throws an error on the callback function. Even though the model itself was being imported in different editors for example three.js editor and babylon.js.please let me know why this is an issue and how can it be solved

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
