### ISSUE TITLE
TypeError: Cannot read property 'transparent' of undefined (renderObjects)

### ISSUE THREAD

**Issue by total3dx** [mrdoob/three.js#22281]
**Describe the bug**
Bug appears when I use EffectComposer. More precisely in the RenderPass.
**To Reproduce**
In my scene I use (from 131.3)
```
import * as THREE from 'three';
import { EffectComposer } from '../vendor/postprocessing/EffectComposer.js';
import { RenderPass } from '../vendor/postprocessing/RenderPass.js';
...
var renderer = new THREE.WebGLRenderer();
var composer = new EffectComposer(renderer);
...
composer.addPass(renderPass);
composer.addPass(copyPass);
...
composer.render(delta);
```
Code above worked without any issues on an older version of Three.

I was able to find and fix the issue. In function **renderObjects**(renderList, scene, camera) you can find an assignment 
`const material = overrideMaterial === null ? renderItem.material : overrideMaterial;`
If **overrideMaterial** material is undefined, then it will assign undefined to the material and crash later in **renderObject** function. Probably, it's better to use "==" instead of "===". It fixes the problem.

**Platform:**

 - Device: desktop
 - OS: [Windows, MacOS]
 - Browser: [Chrome]
 - Three.js version: [dev, r131.3]

**Comment by WestLangley** [comment]
Maybe this is would be a safer pattern:
```js
const material = overrideMaterial ? overrideMaterial : renderItem.material;
```

**Comment by Mugen87** [comment]
Can you please demonstrate the runtime error first? I've tried to reproduce the issue with a live example based on your code but without success: https://jsfiddle.net/uow0jcpL/

**Comment by Mugen87** [comment]
> import { EffectComposer } from '../vendor/postprocessing/EffectComposer.js';
import { RenderPass } from '../vendor/postprocessing/RenderPass.js';

These imports look wrong. You can import both classes from the `three` npm package.

**Comment by total3dx** [comment]
@Mugen87 Let me try to put it in the fiddle. There's no EffectComposer in **three** npm module. Yes, there's inconsistency, like for example in UnrealBloom effect where suddenly getClearColor needs a color input var. 

For this case, in previous versions, in renderObjects was used this assignment:
`var material = overrideMaterial === undefined ? renderItem.material : overrideMaterial;`
And, as blame shows it was changed just recently by @davehill00

**Comment by Mugen87** [comment]
> There's no EffectComposer in three npm module 

That's not true. I suggest you read the following guide for more details:

https://threejs.org/docs/index.html#manual/en/introduction/Installation

**Comment by total3dx** [comment]
@Mugen87 I use an npm module and it's not there. And as I remember, EffectComposer is not a part of three and never was.

**Comment by WestLangley** [comment]
@Mugen87 

>I do not vote to change the code in WebGLRenderer since overrideMaterial should never be undefined.

The user can do this:

```js
scene = new THREE.Scene();
scene.overrideMaterial = undefined;
```

**Comment by Mugen87** [comment]
Yes, but that is a user error. `undefined` is not a valid type for ` Scene.overrideMaterial `. The property is nullable and can hold a material.

**Comment by Mugen87** [comment]
> I use an npm module and it's not there. And as I remember, EffectComposer is not a part of three and never was.

My above fiddle imports `EffectComposer` from the `three` npm package.

**Comment by total3dx** [comment]
@Mugen87 try this repo https://github.com/total3dx/shaderExpES

**Comment by Mugen87** [comment]
Sorry, this is not a help site. We only support the `three.js` repository and you have not demonstrated a bug so far. 

I suggest you use the [forum](https://discourse.threejs.org/) for help.

**Comment by total3dx** [comment]
I'm not asking for help, I'm pointing the bug that was resolved by me by changing 1 symbol

**Comment by total3dx** [comment]
and here you can find a version done using the latest npm package that shows the error, you can also see that it happens in **renderObjects** function that was modified 24 days ago https://total3dx.com/work/ps/

**Comment by Mugen87** [comment]
Sorry, this is not how you demonstrate a bug. I've asked you to update the above fiddle to show the issue.  We do not search for issues in user applications.

**Comment by total3dx** [comment]
switch to Babel you already will see an issue
