### ISSUE TITLE
PMREMGenerator.fromScene() alters background color

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#22286]
In `PMREMGenerator.fromScene( scene )`,  `scene.background` is changed and not restored.

In `webgl_materials_car.html`, do this:

```js
scene = new THREE.Scene();
scene.background = new THREE.Color( 0x0000ff );

scene.environment = pmremGenerator.fromScene( scene ).texture;
console.log( scene.background ); // null
```

Also, 

```js
renderer.setClearColor( 0x0000ff, 1 );
```
has different behavior. I would have expected them to be equivalent.

three.js r131

**Comment by Mugen87** [comment]
see #20819

**Comment by WestLangley** [comment]
The furnace test now makes no sense. Reduce the environment background color to 0x202020 and the spheres render even brighter.

`PMREMGenerator` is doing something really wrong...

Also, colors in three.js are assumed to be in linear space. It appears `PMREMGenerator` assumes otherwise.

Also, FYI, setting the `scene.background` to a simple `Color` should render the same as setting `renderer.clearColor` to the identical color. Consequently, neither are affected by `renderer.outputEncoding`.

/ping @gkjohnson Can you please have a look?

**Comment by gkjohnson** [comment]
> /ping @gkjohnson Can you please have a look?

It'll take me a bit before I can put look into this but when I have time I can.

> Also, colors in three.js are assumed to be in linear space. It appears PMREMGenerator assumes otherwise.

This is kind of sort of true. My understanding was that the renderer clear color or scene background color were intended to be in the final color space already as they do not have a color space transformation applied to them unless that's changed. And with the final color space typically being SRGB it seems like a fine assumption to make. Of course the caveat is when using postprocessing every pixel including the background so you need to set them with linear colors in that case. Changing the renderer to assume linear background and clear colors and automatically transforming accordingly would be a good change, I think.

> Also, FYI, setting the scene.background to a simple Color should render the same as setting renderer.clearColor to the identical color.

#20819 and #21034 should have ensured this was the case. Is this a new issue?

**Comment by WestLangley** [comment]
You are correct. Renderer clear color is neither tone-mapped nor output-encoded, so it is assumed to be in whatever colorspace the renderer renders to -- but that is not necessarily sRGB.

**Comment by Mugen87** [comment]
The difference in behavior of `scene.background = new THREE.Color( 0x0000ff );`  and `renderer.setClearColor( 0x0000ff, 1 );` is the following line:

https://github.com/mrdoob/three.js/blob/42abf866501f51e78c62be1cf92b2beab915848a/src/renderers/webgl/WebGLBackground.js#L52

Meaning when `Scene.background` is configured with a color, `WebGLBackground` forces a clear. This does not happen when using `setClearColor()`. This affects `PMREMGenerator` since it require no clearing when generating the IBL. So setting `WebGLRenderer.autoClear` is not enough, it is necessary to set `Scene.background` to `null`:

https://github.com/mrdoob/three.js/blob/42abf866501f51e78c62be1cf92b2beab915848a/src/extras/PMREMGenerator.js#L300

The issue could be fixed by removing this line and the one above. However, the `forceClear = true;` was surely added on purpose and it might be required for some reason.

**Comment by gkjohnson** [comment]
I took a quick look at things. I don't know much about the furnace tests but regarding color differences in clear color vs background I don't see a whole lot unless I'm missing something.

> The difference in behavior of scene.background = new THREE.Color( 0x0000ff ); and renderer.setClearColor( 0x0000ff, 1 ); is the following line

When rendering the solid color background with PMREMGenerator the same approach of rendering a box geometry for the background (to work around the premultiplied alpha issue) regardless of whether scene.background and renderer.clearColor are used (see [here](https://github.com/mrdoob/three.js/blob/dev/src/extras/PMREMGenerator.js#L295-L316)) so I don't think the force clear should affect the background color end result (at least I didn't observe it)

@WestLangley 
> Also, FYI, setting the scene.background to a simple Color should render the same as setting renderer.clearColor to the identical color.

Can you elaborate on what difference you're seeing here? The only difference I saw was a result of of the background color not being reset. Once that was fixed the scenes looked the same to me.

> The furnace test now makes no sense. Reduce the environment background color to 0x202020 and the spheres render even brighter.
>
> PMREMGenerator is doing something really wrong...

This is the bigger mystery. The first thing I notice is that when setting the background color to `0x202020` the converted RGBE color is around `0.92, 0.92, 0.92, 0.48` while the color `0xcccccc` converts to `0.6, 0.6, 0.6, 0.5`. I know the second is supposed to to yield a brighter color with a larger exponent but the RGB colors seem to correspond directly to the displayed colors which makes it seem like the RGBE sampling isn't being applied correctly somewhere but my knowledge is limited in this area.

Here are some images showing the furnace test using a perspective camera and using the PMREM output as the scene background as well as the environment map:

| Furnace w/ 0x202020 | Furnace w/ 0xcccccc |
|---|---|
| ![image](https://user-images.githubusercontent.com/734200/128972285-f5a1eb87-9582-459d-a281-e5e4185d460c.png) | ![image](https://user-images.githubusercontent.com/734200/128972259-9a5cd6b6-837f-4765-87f9-de44232fa54f.png) |

**Comment by Mugen87** [comment]
Your PR is fine! 

However, it would also be possible to implement the approach mentioned in https://github.com/mrdoob/three.js/issues/22286#issuecomment-896281087. Meaning remove `forceClear` from `WebGLBackground`. In this way, `PMREMGenerator` does not need to set `Scene.background` to `null` (which means it's also not necessary to restore it later). I tested it on my machine and it worked fine in the modified version of `webgl_materials_car`. However, I'm not sure how the removal of `forceClear` affects other use cases.

**Comment by mrdoob** [comment]
Oh, sounds like we should still keep this open?

**Comment by Mugen87** [comment]
The original issue reported in https://github.com/mrdoob/three.js/issues/22286#issue-962896352 is actually solved. How about discussing the remaining topics in separate issues?

**Comment by Mugen87** [comment]
> For simplicity, maybe consider only linear and sRGB,

That sounds like a good start!

**Comment by Mugen87** [comment]
Continuing the discussion in #22326.
