### ISSUE TITLE
Inaccurate interpolation curves with MMD motion data.

### ISSUE THREAD

**Issue by Kikasuru** [mrdoob/three.js#22282]
**Describe the bug**

Three.JS's MMDAnimationHelper produces incorrect interpolation curves compared to MikuMikuDance.

***Code***

Posted [here.](https://github.com/Kikasuru/mmd-interp-bug)

***Live example***

* [Github Pages](https://kikasuru.github.io/mmd-interp-bug/)

**Expected behavior**

This is rendered straight from MMD.
[Download MP4](https://cdn.discordapp.com/attachments/867824974014185522/873029994543198248/koa_float.mp4)

PMM and VMD files are also provided in [the assets folder.](https://github.com/Kikasuru/mmd-interp-bug/tree/main/assets/mmd)

See how with MMD, her arms slowly go into place, as with the live example, they jolt when they're going to the next keyframe.

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: @0.131.3, loaded from SkyPack.

**Comment by takahirox** [comment]
Hi, thanks for the report. I am the author of Three.js MMD stuffs.

Unfortunately I'm not really sure if I can make time for MMD soon. If you are in hurry, I'd be please if you or someone else investigates the problem.

By the way, do you like Touhou? If so, you are my friend.

**Comment by Kikasuru** [comment]
> Hi, thanks for the report. I am the author of Three.js MMD stuffs.
> 
> Unfortunately I'm not really sure if I can make time for MMD soon. If you are in hurry, I'd be pleased if you or someone else investigates the problem.

No problem! I should probably focus on other parts of my project anyways lol

> By the way, do you like Touhou? If so, you are my friend.

![image](https://i.kym-cdn.com/entries/icons/original/000/012/468/shakeee.jpg)

**Comment by Kikasuru** [comment]
Status update in this?

**Comment by takahirox** [comment]
I'm still busy

**Comment by Usnul** [comment]
Without knowing what code is used for interpolation here, I can't say for sure. But it looks like curve data is interpreted incorrectly, what the video suggests - is that a spline is used for animation, something like this:
![image](https://user-images.githubusercontent.com/5939063/141959767-0b307aa3-b84d-4ce2-836a-d03efbcf669b.png)

the implementation of MMD here seems to default to linear interpolation instead, resulting in sharp transitions where curves meet, like the up and down motion.

**Comment by Kikasuru** [comment]
That's what I presumed as well.

**Comment by takahirox** [comment]
> the implementation of MMD here seems to default to linear interpolation instead,

No, IIRC I didn't implement the interpolation as linear, but I implemented it as cubic bezier interpolation.

https://blog.goo.ne.jp/torisu_tetosuki/e/bc9f1c4d597341b394bd02b64597499d

https://github.com/mrdoob/three.js/blob/0a4f02b86a98403cf63ec227bbcf77a05805a164/examples/jsm/loaders/MMDLoader.js#L1939-L2076

If it moves as linear, it's a bug for sure.

**Comment by takahirox** [comment]
Simpler model and animation data will help the investigation.

**Comment by Kikasuru** [comment]
I'd say to quickly whip one up using one of the default models that MMD comes with, showing different curves with each motion.

I would but I've been a little busy myself unfortunately...

**Comment by Mugen87** [comment]
`MMDLoader` has been deprecated, see #29698.
