### ISSUE TITLE
reference three in global scope

### ISSUE THREAD

**Issue by felixmariotto** [mrdoob/three.js#22295]
Hi,

I'm trying to load three conditionally from a CDN, and I'm having trouble because three is not referenced in global scope.

If I do this, three is successfully loaded but I don't have a reference to it : 
```javascript
const promise = new Promise( ( resolve, reject ) => {
	const script = document.createElement( 'script' );
	script.type = 'module';
	script.src = 'https://cdn.skypack.dev/three@0.130.0/build/three.module.js';
	script.addEventListener( 'load', resolve );
	script.addEventListener( 'error', e => reject( e.error ) );
	document.head.appendChild( script );
} );
```
[Dynamic import](https://v8.dev/features/dynamic-import) is an alternative but not entirely satisfactory because of inconsistent browsers and bundlers support.

Can we add three to window.THREE ?
Like : 
```javascript
if ( window && !window.THREE ) window.THREE = three;
```

**Comment by Mugen87** [comment]
> script.src = 'https://cdn.skypack.dev/three@0.130.0/build/three.module.js';

Why don't you load the UMD version instead? Meaning:
```js
script.src = 'https://cdn.skypack.dev/three@0.130.0/build/three.min.js';
```

**Comment by felixmariotto** [comment]
@Mugen87 I tried that but couldn't find three in `window.THREE`, but then I just tried the same with unpkg and it works ! I don't really know the difference between skypack and unpkg, so I can't explain...

Here are two fiddles :
- [loading three UMD with unpkg](https://jsfiddle.net/felixmariotto/5bntcaxz/5/) ( three is referenced in global scope )
- [loading three UMD with skypack](https://jsfiddle.net/felixmariotto/5bntcaxz/6/) ( three is not referenced in global scope and errors are logged )

It seems it's not a problem with three, so I'm closing.

**Comment by Mugen87** [comment]
I've never used skypack for UMDs, just with modules. However `unpkg` or `jsdelivr` should work as expected.

**Comment by mrdoob** [comment]
I think skypack only supports modules.
