### ISSUE TITLE
Issues with alphamap

### ISSUE THREAD

**Issue by WilliamLiu-1997** [mrdoob/three.js#22321]
**Set alphamap will make transparent material behind invisible**

In the screenshot, an aphamap is applied on the pink patch and set the transparent = true. The blue patch also set transparent = true. It can be seen that the part of the blue patch that behind the pink patch is invisible. If the transparent = false (like purple patch), everything is fine.

**Screenshots**

![image](https://user-images.githubusercontent.com/77861330/129310910-10715e2b-bbb7-4f2a-af29-226ac40b8033.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [dev]

**Comment by Mugen87** [comment]
Can you please share a screenshot of the expected result?

**Comment by WilliamLiu-1997** [comment]
Yeah, and I just found that it seems to be an issue on transparent and opacity, not only on alphaMap.
![image](https://user-images.githubusercontent.com/77861330/129344032-93eed467-07f2-40ff-b545-54b49b5fe16d.png)
And I just made a live example here: https://rawcdn.githack.com/WilliamLiu-1997/three.js/ef74e4830e7dd15653da8df7065b3dec779bf4ca/examples/alphamap_issue.html
In the demo, when you set all the material to be transparent=true and opacity <1, and look from the bottom of the plane, you can see some of the cylinders will disappear.
Thanks.

**Comment by Mugen87** [comment]
This is in fact a know issue of how transparent objects are rendered in `three.js`. It's a matter of render order, sorting and depth testing.

I suggest you search in the forum for solutions. This was already often discussed e.g. in https://discourse.threejs.org/t/multiple-transparent-materials-rendering-issue/3599.

I suggest to mark this issue as a dulpicate of #9977.
