### ISSUE TITLE
Triangle.setFromPointsAndIndices buffer attribute version?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#22337]
I just noticed that while geometry.vertices is gone, triangle.setFromPointsAndIndices is still there, and only used in unit test. It seems that accepting geometry.attributes.position would make more sense now, no?

**Comment by Mugen87** [comment]
I don't think the method was intended to directly work on `geometry.vertices`. It needs three points to setup the triangle and it seems okay to have them defined as an array of `Vector3`s.

**Comment by makc** [comment]
It is super obvious that the method was intended to work on clicked face, but you can always ask @bhouston who had [added it](https://github.com/mrdoob/three.js/commit/c5d38e8993a56fa7c2fc964a3ee7e946b69f01a1#diff-3f643cee94a92b6bf2260109a4c1092c7ce645e8f72d1f0b01aaf08647eaff6bR35)

**Comment by Mugen87** [comment]
Makes sense. Let me file a PR.

**Comment by bhouston** [comment]
This makes sense!
