### ISSUE TITLE
Docs: Inconsistency method return type this

### ISSUE THREAD

**Issue by servinlp** [mrdoob/three.js#22333]
**Describe the problem**

As discussed in https://github.com/mrdoob/three.js/pull/22237 we want to documentation to be consistent with the return type when nothing is returned in a method. While working on fixing this inconsistency I came across another.

In, for example, [BufferAttribute](https://threejs.org/docs/index.html#api/en/core/BufferAttribute) the `applyMatrix3`, `applyMatrix4` and `applyNormalMatrix` methods all return `this`. On the other hand the `copy` method also returns `this` ([code](https://github.com/mrdoob/three.js/blob/dev/src/core/BufferAttribute.js#L50-L62)) but has a return type of `BufferAttribute` while then `clone` method also has the return type of `BufferAttribute` while actually constructing a new BufferAttribute ([code](https://github.com/mrdoob/three.js/blob/dev/src/core/BufferAttribute.js#L383-L387)).

My question, while i'm changing the return types to undefined when nothing is returned do we also want to fix this? (We meaning I'll do it together with the undefined return types.)
And if we want to do this, how should it be.

What I would like to propose is the usage of `this` when this is actually returned and only the current type (in this case `BufferAttribute`) when a new class is being constructed.

Love to hear everybody's opinions.

**Comment by Mugen87** [comment]
Thanks for bringing this topic up! It would be indeed good to clean up the return types.

> What I would like to propose is the usage of this when this is actually returned and only the current type (in this case BufferAttribute) when a new class is being constructed.

This is also my preference 👍 .
