### ISSUE TITLE
GLTFLoader: Quaternions not normalized after cubic interpolation

### ISSUE THREAD

**Issue by scurest** [mrdoob/three.js#22339]
**Describe the bug**

GLTFLoader should normalize quaternions after applying cubic interpolation when doing a cubic rotation animation, in accordance with

> [When the sampler targets a node's rotation property, the resulting p(t) quaternion must be normalized before applying the result to the node's rotation.](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#appendix-c-spline-interpolation)

Because the quaternions aren't normalized, a pure rotation animation stretches and squishes while rotating.

If they're normalized, everything looks correct to me (tested by sticking normalization code [here](https://github.com/mrdoob/three.js/blob/918c364b117cde98bf70f91afaae1fbe64058c13/examples/jsm/loaders/GLTFLoader.js#L1775)). 

**To Reproduce**

Can repro in https://gltf-viewer.donmccurdy.com/. See test file at https://github.com/donmccurdy/three-gltf-viewer/issues/261.

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Firefox
 - Three.js version: r131

**Comment by Mugen87** [comment]
I can confirm that normalizing the quaternion fixes the issue. Would you like to make a PR?

**Comment by WestLangley** [comment]
> When the sampler targets a node's rotation property, the resulting p(t) quaternion must be normalized before applying the result to the node's rotation.

What that says is: _if it is a quaternion_ being interpolated, then the output quaternion must be normalized prior to being used.

**Comment by scurest** [comment]
@Mugen87 Rather someone else did.

@WestLangley Yes.

**Comment by WestLangley** [comment]
Right. And could a position be interpolated?

**Comment by scurest** [comment]
Yeah. Is there a problem with doing it only for rotations?

**Comment by WestLangley** [comment]
If the method can be applied to a position, then normalizing the output _inside the method_ would be a bad idea.

**Comment by scurest** [comment]
You can just pass whether its a rotation to the constructor and stuff it into this and then check that in `interpolate_`. Don't know if there's some problem with that, or want to do a different class, or whatever.

**Comment by Mugen87** [comment]
> You can just pass whether its a rotation to the constructor and stuff it into this and then check that in interpolate_.

That sounds like a pragmatic solution to me.
