### ISSUE TITLE
MeshPhysicalMaterial: Volume attenuation in world or local units?

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#22343]
I've constructed two versions of the Khronos [AttenuationTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AttenuationTest) sample model. Both have the same world scale (viewable in the "Inspect" tab of https://gltf.report/), but one uses float32 vertex attributes with world units, and the other uses normalized int16 vertex attributes with scale on the parent object used to achieve the same world scale. Rendered results are quite different:

![Screen Shot 2021-08-16 at 5 45 50 PM](https://user-images.githubusercontent.com/1848368/129646713-e7bcbbd7-6205-49e3-919c-0baac4d6e044.png)

> *Left: world units in vertex attributes. Right: scale on parent object.*

[Archive.zip](https://github.com/mrdoob/three.js/files/6996178/Archive.zip)

According to the glTF specification, these two glTF models should look the same. They don't here, but I'm not sure if that's the responsibility of MeshPhysicalMaterial or GLTFLoader to solve. Do we expect that the MeshPhysicalMaterial shader should understand the world transform of the object? Or that GLTFLoader should output different versions of the same material, with different attenuation distance and/or thickness or each? I think it's the former — the node's transform appears to affect a normal map, for instance — but would like to confirm this is correct.

/cc @takahirox

**Comment by WestLangley** [comment]
FWIW

https://github.com/mrdoob/three.js/blob/a4f742c7d7b61f3efae147235efb0b5bc73e6e03/src/renderers/shaders/ShaderChunk/transmission_pars_fragment.glsl.js#L32-L46

**Comment by takahirox** [comment]
To be honest I just copied it from the shader in glTF Sample Viewer without deeply thinking. Probably we should revisit it.

**Comment by donmccurdy** [comment]
Looks like my quantized sample is broken in babylon.js as well (same issue), and just doesn't render at all in the khronos sample renderer (probably a viewport bounding box issue?). Reported at https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/345. 

/cc @emackey, @bghgary – Does it seem correct that these two models should appear the same, given the same world scale?

**Comment by donmccurdy** [comment]
Hm, that second model appears the same in three.js, babylon.js, and gestaltor. Thinking about it more, that's expected — thickness is given "in the coordinate space of the mesh". If we quantize and normalize vertex attributes to a [-1,1] bounding box, and rescale the parent node to cancel it out, that scale on the parent is also affecting the material whereas vertex scaling is not.

Practically, this means that any vertex quantization method needs to also adjust the thickness property. Attenuation distance can be left alone, it is given in world units by glTF.

I'll consider this a bug in glTF-Transform's quantization implementation, then, at https://github.com/donmccurdy/glTF-Transform/issues/330.
