### ISSUE TITLE
Add an AnnotationHelper class

### ISSUE THREAD

**Issue by FarazzShaikh** [mrdoob/three.js#22345]
**Is your feature request related to a problem? Please describe.**

When building interactive WebGL experiences for clients I receive requests to add some kind of an Annotation or label to objects. 

Quickly googling around I found that ThreeJS does have an inbuilt solution for this. Instead it is recommended to use the `CSS3DRenderer` to implement a solution on your own.

**Describe the solution you'd like**

I’d like to provide a solution in the form of an `AnnotationHelper` class. I have already built a basic implementation based on [Manuel Wieser’s blog post](https://manu.ninja/webgl-three-js-annotations/) (attached below). 

Would it make sense to include this into ThreeJS atleast as an example?

**Describe alternatives you've considered**

There aren’t any ThreeJS based libraries that do this. The best implementation I found was from `model-viewer` And their [Annotations](https://modelviewer.dev/examples/annotations/index.html).

**Additional context**

Here is a GIF of my current implementation and what I’d like `AnnotationHelper` to look like.

https://user-images.githubusercontent.com/55190601/129671597-a4374146-cf0e-44eb-b27e-19b9e3fdd4a0.mov

People really seem to want something like this as evident by [my Reddit post](https://www.reddit.com/r/threejs/comments/p5jemk/was_in_need_of_an_annotation_component_in_threejs/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) and [my Twitter post](https://mobile.twitter.com/CantBeFaraz/status/1427301266858856452)

**Comment by Mugen87** [comment]
TBH, I don't see such a feature in the `three.js` repository. A basic example for labels is already demonstrated with `CSS2DRenderer`, see https://threejs.org/examples/css2d_label.

More advanced labels are often use case specific. I would leave this up for the application.

**Comment by FarazzShaikh** [comment]
@Mugen87 fair enough, and you're right my implementation is basically what the `CSS2DObject` class does.
