### ISSUE TITLE
EdgesGeometry: Additional, unnecessary line is added to the geometry, since the last release (r131)

### ISSUE THREAD

**Issue by soadzoor** [mrdoob/three.js#22341]
**Describe the bug**

When using "EdgesGeometry" for a circle, an additional line is added from the center of the circle to the right edge since r131.

Before r131:
![130](https://user-images.githubusercontent.com/10392261/129571219-de9ffc47-8097-4993-be13-7e0b2c24505d.PNG)

After r131:
![131](https://user-images.githubusercontent.com/10392261/129571237-c80f27e7-b009-4d94-bfcf-2b05a198fdd1.PNG)

**Steps to reproduce**
```
const geometry = new THREE.CircleGeometry(0.4, 16);
const material = new THREE.LineBasicMaterial({color: 0x00ff00});
    
const edgesGeometry = new THREE.EdgesGeometry(geometry);
const lineSegments = new THREE.LineSegments(edgesGeometry, material);
```

***Live example***

https://jsfiddle.net/soadzoor/o5rbvj4p/19/

Note that if you change only the version number of three.js in the beginning, then the circle appears okay.
Change this line:
```
import * as THREE from 'https://cdn.skypack.dev/three@0.131';
```

To this:
```
import * as THREE from 'https://cdn.skypack.dev/three@0.130';
```

And vica versa to check

**Comment by Mugen87** [comment]
Seems to be a side effect of #22099. Related discussion #22094.

**Comment by Mugen87** [comment]
Indeed. Removing the rounding means comparing opponent edges does not work anymore like before because of floating point inaccuracies. Below hashes represent an edge and its counterpart in reverse direction. With the implementation `EdgesGeometry` can not detect them as siblings anymore.
```
0,0,0_0.4000000059604645,0,0
0.4000000059604645,-9.797174158936853e-17,0_0,0,0
```

**Comment by Mugen87** [comment]
It's probably best to revert #22099. 

@mrdoob @WestLangley Okay with you?

**Comment by WestLangley** [comment]
I guess we have to...

**Comment by mrdoob** [comment]
Yep.. 👍
