### ISSUE TITLE
Sheen not working in combination with hdr env?

### ISSUE THREAD

**Issue by vector3** [mrdoob/three.js#22359]
**Describe the bug**
Sheen rendering doesn't seem to work in combination with an HDR environment map.

**To Reproduce**

1. Load an HDR environment map
2. Set the scene's *environment* property to that map
3. Add some generic mesh (e.g. sphere) to the scene
4. Create a MeshPhysicsMaterial and set its sheen property to some color value.
5. Assign the material to the mesh.

**Expected behavior**

The sheen should render even when using an HDR environment map, Instead, you have to set the *envMapIntensity* property of the material to a very small value or zero to be able to see the sheen at all.

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: 131

**Comment by Mugen87** [comment]
Related #17303.

**Comment by elalish** [comment]
Agreed; this is the last remaining gap in supporting the glTF PBRNext extensions. Here are some test cases: 
https://modelviewer.dev/fidelity/#khronos-ToyCar
https://modelviewer.dev/fidelity/#khronos-SheenChair
https://modelviewer.dev/fidelity/#khronos-GlamVelvetSofa
https://modelviewer.dev/fidelity/#khronos-SheenCloth

**Comment by elalish** [comment]
@WestLangley Any interest in trying your hand at this? I'm kicking myself I haven't found time for this yet, but I may have to this release cycle if no one else does...

**Comment by SixBytesUnder** [comment]
HI @elalish 
Did you have a chance to look into this one?
I'd love to know if you have any idea of a timeline to fix this.
