### ISSUE TITLE
Cannot send scene as a message to a worker

### ISSUE THREAD

**Issue by somePythonProgrammer** [mrdoob/three.js#22354]
I am making a game with web workers.
I need to copy the scene to a worker, but it shows an error:

        Uncaught DOMException: Failed to execute 'postMessage' on 'Worker': HTMLCanvasElement object could not be cloned.

Code:

          //inbuilt variables
          let RENDER_STARTLOGGEDONCE = false;
          let LOCKED = false;
          let frameCount_ = 0;
          
          console.log("[Threading] Render thread started!");
          
          const scene = new THREE.Scene();
          const camera = new THREE.PerspectiveCamera(
            75,
            window.innerWidth / window.innerHeight,
            0.1,
            1000
          );
          const renderer = new THREE.WebGLRenderer({
            canvas: document.querySelector("#bg"),
          });
          renderer.setSize(window.innerWidth, window.innerHeight);
          renderer.setPixelRatio(window.devicePixelRatio);
          renderer.setSize(window.innerWidth, window.innerHeight);
          
          const simplex = new SimplexNoise();
          
          const chunkworker = new Worker("./classes/Chunk.js");
          
          chunkworker.postMessage({  simplex: simplex });
          
          scene.background = new THREE.Color("#a3fffd");
          let player;
          
          const loader = new THREE.CubeTextureLoader();
          const texture = loader.load([
            "./assets/textures/gui/title/background/panorama_2.png",
            "./assets/textures/gui/title/background/panorama_0.png",
            "./assets/textures/gui/title/background/panorama_4.png",
            "./assets/textures/gui/title/background/panorama_5.png",
            "./assets/textures/gui/title/background/panorama_1.png",
            "./assets/textures/gui/title/background/panorama_3.png",
          ]);
          scene.background = texture;
          
          function animate() {
            requestAnimationFrame(animate);
            frameCount_ += 1;
            if (!RENDER_STARTLOGGEDONCE) {
              console.log("[RenderThread] rendering...");
              RENDER_STARTLOGGEDONCE = true;
            }
          
            renderer.render(scene, camera);
            if (GAMESTATE === "play>game") {
              if (!LOCKED) {
                player = new Player();
                player.lock();
                LOCKED = true;
              }
              player.update();
            } else {
              camera.rotation.y -=
                0.001 +
                simplex.noise2D(
                  simplex.noise2D(frameCount_ / 60, _mouseX / 1500),
                  simplex.noise2D(_mouseY / 1500, frameCount_ / 60)
                ) *
                  0.0012;
              camera.rotation.x = simplex.noise2D(frameCount_ / 60, _mouseX / 150) * 0.02;
              camera.rotation.z = simplex.noise2D(_mouseY / 150, frameCount_ / 60) * 0.02;
              //camera.rotation.x += 0.001;
            }
          }
          
          animate();

**Screenshots**

![image](https://user-images.githubusercontent.com/74598401/129839551-c14a3e7a-1b13-43c2-adce-d639401b9184.png)

[repo link](https://github.com/somePythonProgrammer/WebCraft) (Note that I have not posted the scene in the repo)
@mrdoob

**Comment by CodyJasonBennett** [comment]
Contexts / functions are not safe to serialize between threads or over a network.

Maybe try sending as JSON and [consult the forum](https://discourse.threejs.org) if you run into further issues. GitHub issues are used to track features and issues within the library.
