### ISSUE TITLE
Behavior change caused by introduction of setPointerCapture()

### ISSUE THREAD

**Issue by Degubi** [mrdoob/three.js#22353]
**Describe the bug**

The changes made in #22118 affected the behavior of the buttons placed above my scene. On build 130 they were working as intended, however on build 131 the buttons' 'click' events don't fire anymore.

**To Reproduce**

1. Go to the first example url (using build 130)
2. Click the 'Click me' button
3. The alert pops up
4. Repeat everything for the second url (using build 131)
5. The alert doesn't pop up

***Code***

Repo with build 130: https://github.com/Degubi/ThreeJS-Bug-130
Repo with build 131: https://github.com/Degubi/ThreeJS-Bug-131

(Difference only in the package.json)

***Live example***

Deployment with build 130: https://threejs-bug-130.herokuapp.com/
Deployment with build 131: https://threejs-bug-131.herokuapp.com/

**Expected behavior**

When I click the button the click event of the button should fire as it did before the changes made in #22118

**Platform:**

 - Device: [tested: Desktop]
 - OS: [tested: Windows]
 - Browser: [tested: Chrome]
 - Three.js version: [it depends]

Edit: Made the code much simpler

**Comment by WestLangley** [comment]
The r131 example works fine on MacOS 11.5 Safari and Firefox -- but not with Chrome.

**Comment by Mugen87** [comment]
Same here. Firefox and Safari work, Chrome not. Tested on macOS, too.

@Degubi Any chances to demonstrate the issue without model-viewer? Ideally with plain `three.js` live demo: https://jsfiddle.net/f2Lommf5/

**Comment by Degubi** [comment]
@Mugen87 
Hi! I already trimmed the code down, the current code is this:

```html
<!DOCTYPE html>
<html>
    <head>
        <script type = "module">
            import { WebGLRenderer, Scene, PerspectiveCamera } from './node_modules/three/build/three.module.js';
            import { OrbitControls } from './OrbitControls.js';

            const camera = new PerspectiveCamera(60, 1, 1, 150);
            const scene = new Scene();
            const cameraControls = new OrbitControls(camera, document.getElementById('viewer'));

            scene.add(camera);
        </script>
    </head>
    <body style = "margin: 0; overflow: hidden;">
        <div id = "viewer" style = "width: 100%; height: 100%; display: inline-block; position: absolute;">
            <button style = "position: absolute; height: 256px; width: 256px; left: 300px; top: 30px;" onclick = "alert('click')">Click Me</button>
        </div>
    </body>
</html>
```

**Comment by Mugen87** [comment]
Thanks for updating the live examples!

Do you mind changing `onclick` with `onpointerdown` and check if this solves the issue?

**Comment by Degubi** [comment]
That seems to work as expected! @Mugen87

**Comment by Mugen87** [comment]
Glad to hear that! Still it is strange that browser behave differently.

Can you please make another test? Please use `onclick` again but modify the `onPointerDown` function in `OrbitControls` like so:
```js
function onPointerDown( event ) {

	if ( scope.enabled === false ) return;

	if ( pointers.length === 0 ) {

		event.target.setPointerCapture( event.pointerId );

		event.target.addEventListener( 'pointermove', onPointerMove );
		event.target.addEventListener( 'pointerup', onPointerUp );

	}

	//

	addPointer( event );

	if ( event.pointerType === 'touch' ) {

		onTouchStart( event );

	} else {

		onMouseDown( event );

	}

}
```
Does now the `click` event listener work?

**Comment by Mugen87** [comment]
Related: https://github.com/GoogleChromeLabs/pointer-tracker/issues/4

**Comment by Degubi** [comment]
> Glad to hear that! Still it is strange that browser behave differently.
> 
> Can you please make another test? Please use `onclick` again but modify the `onPointerDown` function in `OrbitControls` like so:
> 
> ```js
> function onPointerDown( event ) {
> 
> 	if ( scope.enabled === false ) return;
> 
> 	if ( pointers.length === 0 ) {
> 
> 		event.target.setPointerCapture( event.pointerId );
> 
> 		event.target.addEventListener( 'pointermove', onPointerMove );
> 		event.target.addEventListener( 'pointerup', onPointerUp );
> 
> 	}
> 
> 	//
> 
> 	addPointer( event );
> 
> 	if ( event.pointerType === 'touch' ) {
> 
> 		onTouchStart( event );
> 
> 	} else {
> 
> 		onMouseDown( event );
> 
> 	}
> 
> }
> ```
> 
> Does now the `click` event listener work?

This code also fixes the problem for me!

**Comment by Mugen87** [comment]
Thanks! TBH, I don't feel so well with patching the controls with code I don't understand^^. I would like to know first why `event.target` works but not `scope.domElement` although both should refer to the same DOM element.

@jakearchibald Do you mind helping us? 😇 I've used your approach from https://github.com/GoogleChromeLabs/pointer-tracker/issues/4#issuecomment-593929716.

**Comment by jakearchibald** [comment]
I'm not really familiar with threejs. Is there a reduction of the issue?

**Comment by Mugen87** [comment]
The OP provided a test case: https://threejs-bug-131.herokuapp.com/

The interaction is implemented in the `OrbitControls` file.

**Comment by jakearchibald** [comment]
Is that definitely reduced? As in, can the issue only be recreated with the whole of threejs + `OrbitControls.js`?

**Comment by Degubi** [comment]
This code seems to do it for me. Alert appears in firefox, no alert in chrome

```html
<!DOCTYPE html>
<html>
    <head>
        <script type = "module">
            const divElement = document.getElementById('viewer');

            divElement.addEventListener('pointerdown', onPointerDown);

            function onPointerUp(event) {
                divElement.releasePointerCapture(event.pointerId);
                divElement.removeEventListener('pointerup', onPointerUp);
            }

            function onPointerDown(event) {
                divElement.setPointerCapture(event.pointerId);
                divElement.addEventListener('pointerup', onPointerUp);
            }
        </script>
    </head>
    <body style = "margin: 0; overflow: hidden;">
        <div id = "viewer" style = "width: 100%; height: 100%; display: inline-block; position: absolute;">
            <button style = "position: absolute; height: 256px; width: 256px; left: 300px; top: 30px;" onclick = "alert('click')">Click Me</button>
        </div>
    </body>
</html>
```

**Comment by Mugen87** [comment]
@Degubi Thanks, that's a perfect repro case!

**Comment by jakearchibald** [comment]
Ahh I see now. Yeah, I'm not sure what the correct behaviour is here – I'll create a spec issue for it.

If you mousedown on a button, then move your pointer off the button and release, you don't get a click. I think that's universally expected and accepted.

In the demo, the parent element to the button captures all events, that means the mouseup doesn't go to the button, it only goes to the parent. If the button doesn't get the mouseup, does that make it like the previous example where the pointer has moved away? If so, then the Chrome behaviour makes sense.

Here's a different demo, where the button no longer gets the mouseup event, but via a different method https://jsfiddle.net/9rakt7yd/. In this case no browser shows the alert, making me think Chrome is right in the other example.

**Comment by jakearchibald** [comment]
Looks like there's already a discussion on this https://github.com/w3c/pointerevents/issues/356

**Comment by Mugen87** [comment]
Closing then. This needs to be fixed on app level.
