### ISSUE TITLE
MeshPhysicalMaterial: Transmission not working if initialized with 0.

### ISSUE THREAD

**Issue by WilliamLiu-1997** [mrdoob/three.js#22365]
**Describe the bug**

If the transmission is set 0 at beginning on meshphysicalmaterial, and then I change the tranmission, it won't work.

The following is a live example, the two balls both have meshphysicalmaterial. But one of them has transmission=0 at beginning and another one is set transmission=0.01. Then, if you try to change the transmission through the GUI, the one with transmission=0.01 at beginning will work, and another won't work.

***Live example***

https://rawcdn.githack.com/WilliamLiu-1997/three.js/b2d2068453b1c09363afc8dd295d4e7822b1b3b0/examples/transmission_issue.html

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [dev]

**Comment by Mugen87** [comment]
Does it work if you set `Material.needsUpdate` to `true` after the value change? It seems a material compile is missing...

**Comment by WilliamLiu-1997** [comment]
> Does it work if you set `Material.needsUpdate` to `true` after the value change? It seems a material compile is missing...

Yeah, that works. Thank you so much!

**Comment by Mugen87** [comment]
Setting `Material.needsUpdate` should not be required. It's best to let this issue open.
