### ISSUE TITLE
VideoTexture updates material even if video is paused.

### ISSUE THREAD

**Issue by Robpayot** [mrdoob/three.js#22380]
Hi there,

I was using multiple `VideoTexture` for a project and I realize that even if all the videos were paused, I was getting a huge drops of fps. 
So I did a little bit of research and I've seen that all the textures are updated with the `this.needsUpdate = true;` at every frames, which shouldn't be required since the videos were paused and nothing needed to be updated in my case.

I've overriden the `VideoTexture.update()` method by adding a condition to prevent calls if the video is paused and the fps increased to 60. 

Maybe it would be nice to add an option to not call the "needsUpdate = true" if the video is paused which seems to add a lot of calculations. Something like :

```
VideoTexture.prototype = Object.assign( Object.create( Texture.prototype ), {

	constructor: VideoTexture,

	isVideoTexture: true,

	update: function () {

		var video = this.image;

		if ( video.readyState >= video.HAVE_CURRENT_DATA && video.currentTime > 0 && !video.paused && !video.ended) {

			this.needsUpdate = true;

		}

	}

} );
```

Version of three.js used: 0.113.2

I'd be happy if it could help!

**Comment by Mugen87** [comment]
This issue was already discussed in #16946. 

Does https://github.com/mrdoob/three.js/issues/16946#issuecomment-793946128 not work for you?

**Comment by Mugen87** [comment]
>  Version of three.js used: 0.113.2

Closing. The issue should be resolved by upgrading to at least `r119`.
