### ISSUE TITLE
Wrong array size in RGBELoader

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#22388]
I think I see another trivial bug, but this time I would like to confirm before I prepare a PR, because I am not quite sure. In `RGBELoader` there is a computation `numElements = image_rgba_data.length / 4 * 3`. The `numElements` obtained this way is a total number of RGB items in the result. Still the iteration is done as:

```js
numElements = image_rgba_data.length / 4 * 3;
const floatArray = new Float32Array( numElements );

for ( let j = 0; j < numElements; j ++ ) {

	RGBEByteToRGBFloat( image_rgba_data, j * 4, floatArray, j * 3 );

}
```

I think the target array is accessed with 3x times larger indices than expected and it should be:

```js
for ( let j = 0; j < numElements / 3; j ++ ) {

	RGBEByteToRGBFloat( image_rgba_data, j * 4, floatArray, j * 3 );

}
```

Can anyone confirm?

**Comment by WestLangley** [comment]
Nice find. How about like this:

```js
numElements = image_rgba_data.length / 4;

const floatArray = new Float32Array( numElements * 3 );

for ( let j = 0; j < numElements; j ++ ) {

	RGBEByteToRGBFloat( image_rgba_data, j * 4, floatArray, j * 3 );

}
```

**Comment by OndrejSpanel** [comment]
That looks even better, easier to understand. I will prepare a PR.
