### ISSUE TITLE
Render SVGObjects with depth in SVGRenderer

### ISSUE THREAD

**Issue by bpstrngr** [mrdoob/three.js#22392]
**Describe the bug**

When rendering an SVGObject in SVGRenderer, the depth of the Object3D object's position is ignored, 
and they're just placed as last children of the SVG. 

**To Reproduce**

Add SVGObject and other geometry (eg. sprite) to scene, 
move SVGObject behind other geometry before or after 
rendering with SVGRenderer, 
see SVGObject still in foreground 
as last child of renderer.domElement svg.

***Code***

function svg3d()
{let circle=new SVGObject(node);
 circle.position.set(0,0,0);
 let sprite=new Sprite(new SpriteMaterial({color:"blue"}));
 sprite.scale.set(height,height,0);
 sprite.position.set(height,0,0);
 let scene=[circle,sprite].reduce((scene,child)=>
 scene.add(child),new Scene());
 let renderer=new SVGRenderer();
 render(renderer);
 return Object.assign(renderer.domElement,{scene,camera});
}

render(renderer)
{let {scene,camera}=renderer.domElement;
 scene.children.forEach(child=>
 child.rotateOnWorldAxis(new Vector3(0,1,0),0.05));
 renderer.render(scene,camera);
 render(renderer);
};

***Live example***

Here's a codepen demonstrating the issue: 
https://codepen.io/bpstrngr/pen/yLXBQXb?editors=1010

**Expected behavior**

SVGObject's Object3d renders behind geometry's path element when its position.z is lower. 

**Screenshots**

example with Sprite vs. SVGObject:

https://user-images.githubusercontent.com/26650418/130371549-b2064ea2-12fd-4915-81bb-896fc589d72f.mp4

...or the use case where i struggled with this, but its a bit more complex, it contains SVGObjects with foreignObject: 
![image](https://user-images.githubusercontent.com/26650418/130456446-16894261-174f-48c2-b7ec-621ee350b987.png)

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome 93
 - Three.js version: 131.3

**Comment by Mugen87** [comment]
What you see is currently a limitation of `SVGRenderer`. Instances of `SVGObject` are not processed by `Projector` which means sprites and raw SVG objects are sorted and rendered separately.

As a workaround, try to avoid the usage of `SVGObject` in your app and represent the 3D object in a different way. E.g. with an other instance of `THREE.Sprite`. https://jsfiddle.net/L0nr715j/

**Comment by bpstrngr** [comment]
Thanks for the detail! 
In the screenshot i included, 
i use more advanced SVGObjects, which can't be reproduced with geometries, specifically a foreignObject, but they could be more humble elements simply with textures or complex shapes (i have gotten as far as wrapping SVGObjects in `defs/pattern` and digging the domElement for respective Sprites to apply fill pattern). I notice i can apply rotation and transformation on SVGObjects containing svg `text` elements though, but not on ones with `g` or `foreignObject` directly, because the elements don't support the x/y/transform attributes applied. 
So if the element in SVGObjects supports transforms, it would be nice to include them in Projector's transformations. 
I understand it can be complicated to define these cases, and could take long for feature completeness, 
but some rudimentary implementation seems reasonable if SVGObjects possess all relevant properties like position, rotation etc. 
Achieving the same capabilities in SVGRenderer through implementing texture patterns support and other missing features would take even longer, and recommendation against SVGObjects would just become less necessary. 
What do you think? (at least in theory)

**Comment by Mugen87** [comment]
The idea of `Projector` is to be independent of specific renderer components like `SVGObject`. So I don't think it's a good idea to implement this feature requests. Better to keep `SVGRenderer` and `Projector` decoupled as good as possible.

**Comment by bpstrngr** [comment]
Yea that's what i was thinking to do too. 
I'll need to see how SVGObjects are sorted before the Projector to know how exactly they are incompatible. 
Thanks for the supportive comments!

**Comment by Mugen87** [comment]
Closing this for now. Let's reconsider this issue if more users bump into this.
