### ISSUE TITLE
Editor: Error when using "Tab" in textarea

### ISSUE THREAD

**Issue by ostatni5** [mrdoob/three.js#22396]
**Describe the bug**

In the r131 editor (https://threejs.org/editor/), the following issue occured:

```
Uncaught TypeError: this.dom is undefined
    UITextArea https://threejs.org/editor/js/libs/ui.js:318
    UITextArea https://threejs.org/editor/js/libs/ui.js:310
    SidebarObject https://threejs.org/editor/js/Sidebar.Object.js:365
    SidebarProperties https://threejs.org/editor/js/Sidebar.Properties.js:14
    Sidebar https://threejs.org/editor/js/Sidebar.js:19
    <anonymous> https://threejs.org/editor/:104
```

**To Reproduce**

1. Select object on the scene
2. Navigate to object properties sidebar
3. Select "User data" textarea
4. Press "Tab"
5. See the error in the console

**Expected behavior**

Instead of dropping the error in the console, it should put tab-character in the textarea.

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Firefox
 - Three.js version:  editor - r131 

**Proposed fix:**

In _ui.js:310_ change function to arrow function.

from:
~~this.dom.addEventListener( 'keydown', function ( event ) {~~

to:
this.dom.addEventListener( 'keydown', ( event ) => {

Or use in that function `this` instead of `this.dom`.

**Comment by Mugen87** [comment]
Good catch! Would you like to make a PR with the fix? Using `this` instead of `this.dom` sounds good to me.

**Comment by Mugen87** [comment]
@ostatni5 Sorry, I fixed it right now so the PR lands in the next release `r132`.

**Comment by ostatni5** [comment]
Ok no problem :)
