### ISSUE TITLE
Different Threejs versions will make different results in mapbox custom layer

### ISSUE THREAD

**Issue by sknightq** [mrdoob/three.js#22407]
I was using Threejs and Mapbox to display 3d objects on the map. But I found using different Threejs versions will make different results. One is can display a cube correctly, the other is a cube will be created but disappear immediately.

I have created two demos to compare.

1. Go to the following address of two demo
2. Find a red cube displayed on the map
3. But in v118.0，the cube disappears.
4. If you click the "RUN" button again and again in V118.0, you will find the cube is appeared and disappeared immediately

```js
// control the Threejs version
import * as THREE from 'https://unpkg.com/three@0.118.0/build/three.module.js';

```

***Live example***

* [Threejs-v117.1](https://jsfiddle.net/sknight127/0uzmoLwx/) 
* [Threejs-v118.0](https://jsfiddle.net/sknight127/6mrv8xtg/2/)

**Expected behavior**

A red cube displayed on the map

**Screenshots**

<img width="1482" alt="compare" src="https://user-images.githubusercontent.com/8033144/130635044-74e1dae9-c119-4369-b06d-6443a957d010.png">

**Comment by Mugen87** [comment]
Try it with this fixed fiddle which uses the latest version of `three.js`: https://jsfiddle.net/a392snx5/

Notice that your `render()` function now uses a new method called `WebGLRenderer.resetState()`. This new methodimproves the interoperability between `three.js` and other WebGL libraries.

**Comment by sknightq** [comment]
@Mugen87 Thanks for your reply and explanation ！！！
