### ISSUE TITLE
Send removed event to descendants

### ISSUE THREAD

**Issue by avatar-studio** [mrdoob/three.js#22416]
**Is your feature request related to a problem? Please describe.**

It often happens that the main child objects of a parent object move together (eg group).
Because child objects are primary, properties are often referenced in ui, etc. (Particle effect, etc.)
In this case, when the parent object is removed, the child objects do not know that the parent object has been deleted, so the number keeps changing.
The problem is that the program manager has to double the code that manages it.
It would be easier to manage if the descendant objects were also notified of the deletion of their ancestors.
Since particles are modularized and used in various ways, there are many cases where it is difficult to estimate the hierachy.
* If you think about it, there can also be a risk of a memory leak.

**Describe the solution you'd like**

Send events to descendants of objects as well.

**Describe alternatives you've considered**

When deleting an object, it would be good to send a separate event to the descendant objects. (removed_ancestor, etc.)
It would be nice to send the uuid of the object to be deleted as a variable.

**Additional context**

Nothing

**Comment by Mugen87** [comment]
Merging this into #16934.

I don't think we need a separate issue for this topic. The discussion can happen directly in the PR.
