### ISSUE TITLE
WebGLRenderer - use alpha: true by default

### ISSUE THREAD

**Issue by CreativeTechGuy** [mrdoob/three.js#22418]
**Describe the bug**

As shown in the docs [here](https://threejs.org/docs/#api/en/renderers/WebGLRenderer), the WebGLRenderer has `alpha: false` by default. But also in the same page there is a list to [WebGL best practices from MDN](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices) which has a section specifically [saying to avoid alpha: false](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#alpha_false_can_be_expensive).

It looks like this decision was originally made in #1104 and maybe should be re-evaluated.

**To Reproduce**

N/A

***Code***

N/A

***Live example***

N/A

**Expected behavior**

The WebGLRenderer should use the most optimized/recommended settings by default.

**Screenshots**

N/A

**Platform:**

N/A

**Comment by mrdoob** [comment]
> On some platforms, this capability unfortunately comes at a significant performance cost.

In order to reconsider we would need a complete list of affected platforms. GPU model, OS version, driver version, ...

**Comment by Mugen87** [comment]
When implementing an experimental removal of `THREE.RGBFormat` on my system, I've also investigated the impact of this suggestion.

One problem is that it breaks certain blending scenarios. For instance the following example fails when `alpha` is set to `true`:

https://threejs.org/examples/webgl_materials_blending

I was not able to apply a quick fix. After this finding, I've stopped a more detailed investigation and performance comparison and focused on other topics.

`webgl_materials_blending` with `alpha: true`: https://jsfiddle.net/snL1cpxd/

**Comment by WestLangley** [comment]
>One problem is that it breaks certain blending scenarios. For instance the following example fails when alpha is set to true:

I do not think "fails" is the correct interpretation. It is just different.

Setting the CSS background color to red makes it more clear what is happening.

**Comment by Mugen87** [comment]
With failing I've meant that the visual output is different and the E2E screenshot comparison fails which eventually indicates a breakage.

**Comment by mrdoob** [comment]
Yeah, I do not think it's worth investing any time in this.
It would help if the article on MDN had specified a list of affected devices and how many of them there are.

**Comment by arpu** [comment]
```
WebGL backbuffers are almost always RGBA behind the scenes. RGB is neither smaller nor as fast as using RGBA directly. Emulating RGB-on-RGBA has real overhead, regardless of implementation approach. Instead, use alpha:true (the default) and simply write 1.0 alpha from your fragment shaders.
```



from: https://hackmd.io/@jgilbert/WebGLBestPractices#Avoid-alpha-false-for-perf-reasons

**Comment by mrdoob** [comment]
Why did they add the option to WebGL if they don't want people to use it?

**Comment by Mugen87** [comment]
Related Chromium issue: https://crbug.com/1103485

**Comment by mrdoob** [comment]
> At least it is not possible with WebGPU 😁 .

Hmm, if it's not possible in WebGPU maybe it makes sense to investigate more making `alpha: true` the default so we have parity...?

**Comment by Mugen87** [comment]
Sounds good! 

Would it be an option to remove the `alpha` context parameter, too? I'm not sure if it is possible to replicate all `alpha: false` blending setups  with `alpha: true`. But if it would be possible, would something block this idea?

**Comment by Mugen87** [comment]
Having less possible framebuffer permutations would also simplify things. We could avoid code like:

https://github.com/mrdoob/three.js/blob/5346f4ec18eeaa7359ae0da64cd3ec12a8eb9599/src/renderers/webxr/WebXRManager.js#L323

**Comment by mrdoob** [comment]
Hmm, I think one way of replicating `alpha: false` would be doing `_canvas.style.background = '#000'` 😬
