### ISSUE TITLE
onBeforeRende and onAfterRender are executed and then rendered.

### ISSUE THREAD

**Issue by avatar-studio** [mrdoob/three.js#22423]
**Describe the bug**

The order of action of Object3D in the document is onBeforeRender -> Rendering -> onAfterRender .
However, it is actually guessed in the order onBeforeRender -> onAfterRender -> rendering.
To check the operation, I made a sample.
The order of operation is: positioning particles, rendering, and initializing particle positions.
According to the documentation, the particles should always be moving.
However, it always stops.
Press the toggle button once every 2 seconds to confirm.

**To Reproduce**

1. extract attached file.
2. run 'index.html'
3. Press the toggle button once every 2 seconds to confirm.

***Code***

    points.onBeforeRender = function(){

        pointElapsed += delta;
        let runRate = (pointElapsed % speed) / speed;
        let easing = Math.sin( (Math.PI * 2) * runRate );
        positions[0] = easing * radius;

        geometry.setDrawRange(0, maxParticles);
        geometry.attributes.position.needsUpdate = true;

    }
    points.onAfterRender = function(){
        if( ignoreAfter ) return;
        positions[0] = 0;
    }

***Live example***

nothing.

**Expected behavior**

We can't get callbacks right after rendering.

**Screenshots**

nothing.
[003_onAfterRender.zip](https://github.com/mrdoob/three.js/files/7046564/003_onAfterRender.zip)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox,, Edge]
 - Three.js version: [dev, r131]

**Comment by Mugen87** [comment]
I've checked your code and the callbacks are executed as expected by the renderer.  I suggest you use the [forum](https://discourse.threejs.org/) for further help.

Besides, please never share a test case as a zip (or archive in general). Devs could easily donwload malware. Always use a live example like a fiddle. I've transferred your code to demonstrate this: https://jsfiddle.net/gt57Lh6d/
