### ISSUE TITLE
DisposableMesh

### ISSUE THREAD

**Issue by CreativeTechGuy** [mrdoob/three.js#22448]
**Is your feature request related to a problem? Please describe.**

When I remove a `Mesh` I want to clean up everything that was created with it. So that means all materials and geometry which are part of the mesh.

**Describe the solution you'd like**

This is the implementation I've been using. This could be a separate class as shown below or better yet part of the base Mesh class so all types of Meshes could benefit from this.

```ts
class DisposableMesh extends Mesh {
    public dispose(): void {
        this.geometry.dispose();
        const materials = Array.isArray(this.material) ? this.material : [this.material];
        materials.forEach((material) => {
            material.dispose();
        });
        this.removeFromParent();
    }
}
```

**Describe alternatives you've considered**

The class shown above can easily be implemented in userland and repeated in each project that it is used.

**Additional context**

Since garbage collection cannot be automatic for these things, having a single easy way to remove everything is very helpful when you have scenes that are constantly creating and destroying objects.

**Comment by mjurczyk** [comment]
While, like probly everyone at some point, I also fought angrily against having to write [disposing mechanics per-project](https://threejs.org/docs/index.html?q=dispo#manual/en/introduction/How-to-dispose-of-objects) - imo it's still best to keep it out of three.

What would `DisposableMesh` do if other meshes reuse some / all its materials 🤔 ?
What about texture disposal 🤔?
What about material disposal, where material wasn't reused but specific textures were 🤔?

In apps / demoscene it doesn't really happen - but in games disposing reusable materials will result in constant recompilation stutter, and, effectively, death of the entire gamedev genre within approximately 3-4 workdays 💀

**Comment by CreativeTechGuy** [comment]
I totally get all of those concerns. But just like disposing each material/geometry manually, it's on the user to only dispose when appropriate. This still would be a manual process to dispose and people should not use it in the cases that you described.

It's really not changing anything that exists, just providing a helper mechanism to do the same thing that already exists.

In the event someone does want to dispose of everything, it'd be great if there was some easy way to do that. It may not be this, but disposing of everything is non-trivial. I even didn't realize about disposing of textures on the materials haha so now I need to add that.


Maybe the proposal is twofold:

* Add `dispose` to `Mesh`
* Add a boolean argument to all `dispose` methods which when true will do a recursive dispose. This way you can dispose of anything and optionally dispose of any dependent resources which may need to be disposed.

**Comment by Mugen87** [comment]
Sorry, but @mjurczyk's objections are correct. Putting `dispose()` to 3D objects would lead to unexpected side effects. The idea of `three.js` disposal API is to provide a `dispose()` method for the building blocks which can actually be reused. Textures, materials, geometries etc. A 3D object is a higher level entity and implement `dispose()` at this place is out of the scope of the project.

**Comment by CreativeTechGuy** [comment]
Does calling `dispose` on the renderer cleanup everything? Or even in that case do you need to find every resource that was created to dispose each individually?

**Comment by Mugen87** [comment]
> Does calling dispose on the renderer cleanup everything?

No it does not. You still have to clean up the scene separately. That's because a scene could be rendered by more than one renderer. Coupling renderer and scene would have side effects, too.

**Comment by CreativeTechGuy** [comment]
Maybe I should ask this way. If you want to clean up **everything** because you know that none of it will be reused, how can you ensure that everything has been removed?

Here's my best guess:
* Dipose the renderer
* Recursively traverse every child in the scene and dispose of every light, material, texture, skeleton, and geometry.

Is that it? Or is there something else that I'm missing?

**Comment by Mugen87** [comment]
That sounds correct. Also check out the related discussion at the forum. E.g.

https://discourse.threejs.org/t/when-to-dispose-how-to-completely-clean-up-a-three-js-scene/1549
