### ISSUE TITLE
GCODELoader contains wrong travel visualization

### ISSUE THREAD

**Issue by YvonnevH** [mrdoob/three.js#22469]
When using the GCODELoader, the travel moves of the gcode are not shown correctly. When opening the same GCODE in another program like Repetier or Cura, the travel moves are shown differently than when using the GCODELoader of ThreeJS. 

***Live example***
It can also be seen in the [example on the ThreeJS website](https://threejs.org/examples/?q=gcode#webgl_loader_gcode), for example if you zoom in on the travel moves between the 3 skirt lines. The travel moves are always shown a line too late. 

**To fix**
To fix this issue, change line 155 from `line.extruding = delta( state.e, line.e ) > 0;` to `state.extruding = delta( state.e, line.e ) > 0;`

**Comment by Mugen87** [comment]
@tentone Does this fix sound correct to you?

**Comment by tentone** [comment]
Hi,

Yes, this change seems correct to me. 

Thanks a lot!

**Comment by Mugen87** [comment]
@YvonnevH Would you like to make a PR with your proposed fix?

**Comment by mrdoob** [comment]
I'll apply the fix directly.

**Comment by mrdoob** [comment]
Thanks!

| Before | After |
| --- | --- |
| <img width="932" alt="Screen Shot 2021-09-01 at 6 57 46 PM" src="https://user-images.githubusercontent.com/97088/131720525-d1dfad27-4443-4f07-8c0e-d3b5559ff4d8.png"> | <img width="932" alt="Screen Shot 2021-09-01 at 6 57 29 PM" src="https://user-images.githubusercontent.com/97088/131720553-fa5464db-365d-4381-b690-938836dc4e5f.png"> |
