### ISSUE TITLE
Bug about IFCLoader

### ISSUE THREAD

**Issue by adrianlx** [mrdoob/three.js#22467]
**Describe the bug**

Mesh generated by 'IFCLoader.ifcManager.createSubset()' has not mulitply modelMatrix.

**To Reproduce**

Here is the thing. I try to load ‘IFC’ File by IFCloader and align the mesh to the original point by modify the position of the model.
then, i need to highlight some part of the model by calling IFCLoader.ifcManager.createSubset() .but the mesh generated is not in the right position. because its not mulitply modelMatrix.

***Code***

```js
//align model to original point
    let box=new THREE.Box3();
    box.setFromObject(ifcModel);
    let center=new THREE.Vector3();
    box.getCenter(center);
    ifcModel.position.copy(center.clone().negate())

//highlight some part
let highlightMesh=ifcLoader.ifcManager.createSubset({
      modelID: modelId,
      ids: Array.isArray(ids)?ids:[ids],
      material: ifcHighlightMat,
      scene: scene,
      removePrevious: true,
    });
```

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [132.2]

**Comment by agviegas** [comment]
Hey! If you pass your mesh as `scene` parameter, it should attach the subset to it, thus applying the transformation. Let us know how it goes! 😄
