### ISSUE TITLE
Adopt await/async/fetch?

### ISSUE THREAD

**Issue by DefinitelyMaybe** [mrdoob/three.js#22468]
related #19060

Howdy folks!

Hope all of your current projects are going well, I've seen some great work come up via my twitter feed.

After a little searching through previous issues, I've found a couple regarding async/await and have also spotted relevant sections within the code base however my searches have come up empty regarding the use of [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). What is everyone's thoughts on some movements  towards async/await/fetch?

Currently the only thing within `src` that uses async/await is the `loaders/ObjectLoader.js`
Within `examples` there's the `LDrawLoader.js`
...but that's about it.

Yes, yes, I can see the old functions have been wrapped in `new Promise`'s ... but, oh I dunno, does that seem like only half the job done?

**Comment by mrdoob** [comment]
Using async/await wherever it makes sense sounds good to me.

But keep in mind that it removes paralelism. Currently the HDR image and the model can load at the same time with simple code.

**Comment by Mugen87** [comment]
Since we have already invested quite a lot of time this year in modernizing the code base, I'm hesitant in doing more in that regard in the next time. Especially if no concrete problem is solved with new language features.

**Comment by looeee** [comment]
> Currently the HDR image and the model can load at the same time with simple code.

`Promise.All` is quite simple to use and solves this problem. 

```
const [model, envMap] = await Promise.all([
   gltfLoader.loadAsync('DamagedHelmet.gltf'),
   rgbeLoader.loadAsync('royal_esplanade_1k.hdr'),
])
```

**Comment by mrdoob** [comment]
That would change how most of the examples are structured now though.

**Comment by makc** [comment]
@looeee then what do you gain from having a single await statement in the example

**Comment by DefinitelyMaybe** [comment]
structure would be my guess. Loading resources is an async operation and currently we're tackling that with call-backs, `addEventListener`'s and a `handlers` array. The JS community didn't come up with the term 'call-back-hell' for nothing.

**Comment by looeee** [comment]
@makc you gain control of exactly when to wait for the model to load. You can control what parts of the scene to set up first and what parts to set up after adding the model. Also no callbacks.

**Comment by DefinitelyMaybe** [comment]
closing with #22510 merged.
