### ISSUE TITLE
Scene.environment / background is only rendered by renderer used to create pmrem textures

### ISSUE THREAD

**Issue by LinoPhil** [mrdoob/three.js#22472]
**Describe the bug**

Hi ThreeTeam,

in my viewer i use a 2nd temporary renderer to render screenshots for endusers. Currently I am implementing hdri workflow with pmremGenerator... Now I stumbled over the problem that just rendering the scene, which has been provided with environment and background, which where produced from pmremGenerator, by a 2nd renderer, is not showing the environment and background.

It seems that renderTarget.texture is still somehow connected to the generating renderer.

**To Reproduce**

Checkout Live example

***Live example***

https://jsfiddle.net/2u39rsoh/60/

**Expected behavior**

Both renderer use environment and backround. Or information how to fix this.

**Screenshots**

![image](https://user-images.githubusercontent.com/25367101/131536962-6bd12752-89a9-438b-8d38-8861613d3c34.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [r132]

Thanks
Philipp

**Comment by WestLangley** [comment]
Is this what you are trying to do?

https://jsfiddle.net/nq5z2f9t/

**Comment by LinoPhil** [comment]
> Is this what you are trying to do?
> 
> https://jsfiddle.net/nq5z2f9t/

I am afrait this way the generated pmrem is not used.

**Comment by Mugen87** [comment]
We've decided in #22178 not to add PMREMs to `Scene.background` anymore. 

Do it like in the fiddle of @WestLangley . It will ensure that `Scene.environmet` does use a PMREM since it's internally created by the renderer. If you want to avoid the blocky background image, don't use `THREE.UnsignedByteType` for the env map's data type.

https://jsfiddle.net/t72fo30w/

**Comment by LinoPhil** [comment]
So one does not need to use pmremGenerator at all? What about equirectangular input?

**Comment by Mugen87** [comment]
> So one does not need to use pmremGenerator at all?

Not in your fiddle, no.

> What about equirectangular input?

Equirectangular maps are also converted to PMREMs if used as an environment map for PBR materials.

**Comment by LinoPhil** [comment]
> Equirectangular maps are also converted to PMREMs if used as an environment map for PBR materials.

And also when provided as scene.environment ? For me this seems not to work, pbrs are black. And it is also not projected correctly as background. Not when loaded as jpg with TextureLoader not when loaded as hdr whith RGBELoader.

**Comment by Mugen87** [comment]
> But not for equirectangular single jpg, hdr

You probably forgot this line:
```js
envMap.mapping = THREE.EquirectangularReflectionMapping;
```
You have to add it in the `onLoad()` callback similar to:
https://github.com/mrdoob/three.js/blob/e62b253081438c030d6af1ee3c3346a89124f277/examples/webgl_loader_gltf.html#L46
