### ISSUE TITLE
Camera Projection Matrix Inverse gives NaN 

### ISSUE THREAD

**Issue by ksaluja24** [mrdoob/three.js#22476]
**Describe the bug**

Initalising THREE.PerspectiveCamera gives **projectionMatrixInverse** as  
```js
elements: (16) [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]
```
**To Reproduce**
This code can not be reproduced as on some machines , it gives such values.  I tried with various Node Versions, different Three js versions from v0.111.0 to v0.131.0
***Code***

```js
  persCameraTHREE = new THREE.PerspectiveCamera(
    50,
    window.innerWidth / window.innerHeight,
    0.1,
    1000
    );
```

**Platform:**

 - Device: [Desktop,]
 - OS: [ Linux]
 - Browser: [Chrome]
 - Three.js version: [r131]

**Comment by Mugen87** [comment]
Please continue to investigate the issue at the forum until the root cause is clear:

https://discourse.threejs.org/t/vector3-unproject-camera-returns-nan/29419
