### ISSUE TITLE
Editor: View Helper does not align the camera to the selected axis

### ISSUE THREAD

**Issue by ostatni5** [mrdoob/three.js#22470]
**Describe the bug**

In the editor(r132), when clicking chosen axis in "view helper" the camera is not aligning to that axis. 

**To Reproduce**

1. Go to [editor](https://threejs.org/editor/)(r132)
2. Click on an axis on "view helper"
3. Nothing happens

**Expected behavior**

The camera is aligning to the clicked axis. 

**Screenshots**
View helper:
![view helper](https://user-images.githubusercontent.com/26521377/131524249-9753c23b-8187-43e0-8bd9-5193bba79f58.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Firefox]
 - Three.js version: [editor, r132]
 
**Observations:**
When clicking on "view helper" only `mousedown` event fires,  `mouseup` is not fired. (in `mouseup` is handled clicking on an axis)

**Comment by Mugen87** [comment]
Can you please verify if the PR fixes the issue? I've shared a link for testing here: https://github.com/mrdoob/three.js/pull/22480#issuecomment-910056360

**Comment by ostatni5** [comment]
@Mugen87 Yes, that PR fixed the issue for me.
