### ISSUE TITLE
Error while merging Text Geometry and Sphere Geometry 

### ISSUE THREAD

**Issue by suryakumara** [mrdoob/three.js#22477]
I got an error when merging text and sphere geometry. Because the viewer fromAutodesk Forge Viewer, the threejs used is R71 and must be a BufferGeometry. 
![image](https://user-images.githubusercontent.com/51102773/131636086-900a830e-55e9-4935-9785-c3976a577fdd.png)

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
