### ISSUE TITLE
Performance problems on Chrome with simple scenes

### ISSUE THREAD

**Issue by rawnsley** [mrdoob/three.js#22490]
**Describe the bug**

We are seeing low FPS in three.js on different versions of Chrome on PC and Mac. Simple examples such as [webgl_animation_skinning_morph](https://threejs.org/examples/#webgl_animation_skinning_morph) run at 40 FPS on a 2019 MacBook Pro using Chrome 94 (currently in the beta channel). On a 2013 PC with decent specs and a dedicated graphics card we see 4 FPS at best. In Firefox this is more like 30 FPS on the PC, but still much lower in all cases than I would expect from such a simple scene.

**To Reproduce**

1. Go to https://threejs.org/examples/#webgl_animation_skinning_morph
2. Check the FPS counter

***Live example***

Both of these scenes are bad on the PC, but on the Mac only the second one drops frames:

* [webgl_animation_skinning_blending](https://threejs.org/examples/#webgl_animation_skinning_blending)
* [webgl_animation_skinning_morph](https://threejs.org/examples/#webgl_animation_skinning_morph)

**Expected behavior**

Double-digit FPS for simple scenes on reasonable spec computers.

**Performance Traces**

[2019 MacBook Pro on Chrome 94](https://github.com/mrdoob/three.js/files/7104326/Profile-20210903T091539.json.zip)

In this trace the rendering appears to be fine with no frame taking more than about 6ms to render. However, it drops about one frame in three for no obvious reason.

[AMD A4-6300 with Windows 7 and a Radeon 8370D on Chrome 92](https://github.com/mrdoob/three.js/files/7104351/Profile-20210903T091744.json.zip)

This trace has some similar characteristics to the first one, but with a much longer pause after frame rendering. Typically 100s of milliseconds.

**Comment by Mugen87** [comment]
I've checked your performance profiles of both machines but I can't see something unusual regarding the execution of `three.js`. Especially the long pauses in the second trace look unrelated to `three.js`.

Do you see a similar performance problem with other WebGL engines, too? For example have you tested with some Babylon.JS demos?

If this performance issue is unrelated to `three.js`, I have to ask you to report this issue to the Chromium project instead: https://bugs.chromium.org/p/chromium/issues/list

**Comment by rawnsley** [comment]
@Mugen87 You are quite right, we see the same behaviour on similar examples with BabylonJS: [Example1](https://www.babylonjs.com/demos/chibirex/) [Example2](https://www.babylonjs.com/demos/yeti/). Thanks for the quick response.
