### ISSUE TITLE
Sprite fails to listen to flipY in Chrome

### ISSUE THREAD

**Issue by paulmelis** [mrdoob/three.js#22495]
**Describe the bug**

I'm using a Blender scene that gets exported to a .glb file. In this scene a few textured quads are named "sprite-..." and are intended to be turned into THREE.Sprite's for text labels (the rest of the geometry stays static, but positioning the labels in convenient in Blender). After loading the .glb with GLTFLoader I traverse the scene and find the "sprite-..." mesh nodes and replace them with a Sprite using the original Texture. In both Firefox and Chrome this results in a quad that is upside-down (text-wise), so I flip them with setting `flipY` on the texture. This works in Firefox:

![image](https://user-images.githubusercontent.com/1408287/132025356-379cb3b7-5c9a-4ea8-b04b-7f67b59902ec.png)

But fails in Chrome:

![image](https://user-images.githubusercontent.com/1408287/132025425-87842140-b3d5-416d-b331-fa478937ace1.png)

**To Reproduce**

1. Unzip test.html and test.glb from [sprites.zip](https://github.com/mrdoob/three.js/files/7106816/sprites.zip)
2. Serve test.html, e.g. with `python -m http.server`
3. Load test.html in browser

***Code***

Relevant excerpt for setting up the sprites:

```js
                const loader = new THREE.GLTFLoader();

                loader.load(
                    // resource URL
                    '/test.glb',
                    // called when the resource is loaded
                    function ( gltf ) {

                        // Enable sprites
                        let sprite_nodes = [];
                        gltf.scene.traverse((node) => {     
                            console.log(node);           
                            if (node.isMesh && node.name.startsWith("sprite-")) {                    
                                sprite_nodes.push(node);
                            }
                        });
                        sprite_nodes.forEach(function (node, idx) {
                            console.log(node);
                            // Replace node with sprite
                            // We assume the node is a Blender mesh created with Import -> Images as Planes,
                            // which is then only uniformly scaled and positioned in the scene.
                            // Such a quad will have a height of 1 and width dependent on the image aspect.
                            console.log(node.material);
                            let map = node.material.map;
                            map.flipY = true;
                            map.needsUpdate = true;
                            let material = new THREE.SpriteMaterial( { map: map } );
                            let sprite = new THREE.Sprite(material);                
                            let pos = node.position;                
                            sprite.position.set(pos.x, pos.y, pos.z);
                            let scale = node.scale; 
                            let imgaspect = map.image.width / map.image.height;                
                            sprite.scale.set(scale.x*imgaspect, scale.y, 1.0);
                            
                            gltf.scene.add(sprite);
                            gltf.scene.remove(node);
                        });
                        scene.add( gltf.scene );

                    },
```

**Platform:**

 - Device: Desktop
 - OS: Linux (Arch)
 - Browser: Chrome 92.0.4515.107, Firefox 90.0.2
 - Three.js version: https://threejs.org/build/three.min.js

**Comment by Mugen87** [comment]
> map.flipY = true;

You can't set the `flipY` property since the image of the texture is of type `ImageBitmap`. When using this type of image, the image orientation can only be specified when the image is loaded. Not afterwards. For more details, check out the `imageOrientation` option of [createImageBitmap()](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap).

Firefox behaves differently since `GLTFLoader` does not use `ImageBitmap` for this browser yet.

**Comment by paulmelis** [comment]
Thanks ! Didn't know about either `ImageBitmap` or that Firefox was different in this respect for `GLTFLoader`. Worked around this by tweaking texture coordinates :wink:
