### ISSUE TITLE
GLTFExporter example doesn't work

### ISSUE THREAD

**Issue by hamidb80** [mrdoob/three.js#22498]
**Describe the bug**
[this example](https://threejs.org/examples/#misc_exporter_gltf) is supposed to export a gltf/glb file, but it gives me an error
**when i click on these buttons:**
- Export Scene1
- Export Scene1 and THREE.Scene 2
- Export WaltHead
- Export Scene1 and Sphere

**error code:**
```js
GLTFExporter.js:968 Uncaught TypeError: Cannot read property 'width' of undefined
    at GLTFWriter.processImage (GLTFExporter.js:968)
    at GLTFWriter.processTexture (GLTFExporter.js:1104)
    at GLTFWriter.processMaterial (GLTFExporter.js:1192)
    at GLTFWriter.processMesh (GLTFExporter.js:1583)
    at GLTFWriter.processNode (GLTFExporter.js:1870)
    at GLTFWriter.processScene (GLTFExporter.js:1946)
    at GLTFWriter.processInput (GLTFExporter.js:2002)
    at GLTFWriter.write (GLTFExporter.js:405)
    at GLTFExporter.parse (GLTFExporter.js:105)
    at exportGLTF (misc_exporter_gltf.html:44)

```

**if works fine when click on these buttons:**
- Export Sphere
- Export Sphere and Grid

**To Reproduce**
1. Go to [this example](https://threejs.org/examples/#misc_exporter_gltf) 
2. Click on one of these buttons: [ `Export Scene1`, `Export Scene1 and THREE.Scene 2`, `Export WaltHead` `Export Scene1 and` Sphere`
3. See error on the console

***Live example***
[this example](https://threejs.org/examples/#misc_exporter_gltf)

**Expected behavior**
saves files as gltf/glb

**Platform:**
 - Device: Desktop
 - OS: Windows 10 64bit
 - Browser: Chrome V 92.0.4515.159 
 - Three.js version: [dev, r???]

**Comment by Mugen87** [comment]
I've tried the exact same steps but I'm unable to reproduce a runtime error. The browser console just shows the usual logs.

Tested on Windows 10 with Chrome 92.0.4515.159.

**Comment by Mugen87** [comment]
I've also tested on macOS with Chrome but with the same result. No runtime error.

@hamidb80 Can you please try it with a different browser and also with another computer?

**Comment by hamidb80** [comment]
I tested on another computer with windows 10 64bit and chrome v93

Everything works fine
