### ISSUE TITLE
background color is always black in VR (Oculus Browser)

### ISSUE THREAD

**Issue by felixmariotto** [mrdoob/three.js#22508]
Since [this commit](https://github.com/mrdoob/three.js/commit/3defafa0cee715701117657a3938a28a8379f20b) by @cabanier, some scenes background show full black whereas they should not. This only happens when the background was set like this :

```javascript
scene.background = new THREE.Color( 0x505050 );
```
In [this example](https://threejs.org/examples/#webxr_vr_rollercoaster) for instance the sky is black behind the clouds ( in VR ).

If instead the background was set with a texture, like in [this example](https://threejs.org/examples/?q=sandb#webxr_vr_sandbox), it works fine.

Tested on : Oculus Browser (16.6.0.1.52.314146309) on Quest 1

**Comment by cabanier** [comment]
It's possible that the layer is not blending correctly. 
thanks for the test case!

**Comment by cabanier** [comment]
I found that this was an issue on the browser's side. It will be fixed in an upcoming release.
If needed, you can manually clear the color each frame to work around it.
