### ISSUE TITLE
How add custom table in threejs Editor UI

### ISSUE THREAD

**Issue by parisa-hr** [mrdoob/three.js#22505]
I clone threejs from [Github](https://github.com/mrdoob/three.js/tree/master) In [Editor project](https://threejs.org/editor/)  I want to add a table from [Grid.js](https://gridjs.io/) 

This Editor creates UI Elements from the `ui.js` file and I don't know how should I add one custom Item there.

I createElement `div` and import Grid.js 

     import {
    	UISpan
    } from './libs/ui.js';
    import {
    	Grid,
    	html
    } from "https://unpkg.com/gridjs?module";
    
    function SidebarTable(editor) {
    	var container = new UISpan();
    
    	const grd = document.createElement('div');
    
    	const tb = new gridjs.Grid({
    		columns: ['Name', 'Email', 'Phone Number'],
    		data: [
    			['John', 'john@example.com', '(353) 01 222 3333'],
    			['Mark', 'mark@gmail.com', '(01) 22 888 4444']
    		]
    	}).render(grd);
    
    
    
    	container.setInnerHTML(grd.innerHTML);
    
    	return container;
    
    }
    
    export {
    	SidebarTable
    };

when I add it, It damaged the style and cant load data :

![image](https://user-images.githubusercontent.com/44742050/132474025-cb05d1ce-66cf-4748-a08f-469865704191.png)

how can I fix this? I'm a beginner in web and three.js too and I will be grateful if help me.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by parisa-hr** [comment]
> 
> 
> Please use the [forum](https://discourse.threejs.org/) for help requests.

nobody answer me , I asked it in [stackoverflow](https://stackoverflow.com/questions/69099069/how-add-custom-table-in-threejs-editor-ui) too , but nobody answer , as programmer of this project please help me .
