### ISSUE TITLE
GLTFExporter doesn't provide a way to write extras to the root of the json when serializing to GLB

### ISSUE THREAD

**Issue by wlinna** [mrdoob/three.js#22512]
**Is your feature request related to a problem? Please describe.**

Our application needs to write `extras` to the root of the exported glTF. However, `GLTFExporter` provides no access to the JSON  root. Yes, it invokes plugins for meshes, nodes, scenes etc., but not for the root of JSON data. When serializing to glTF, `onDone` 'returns' the JSON, but if `binary: true`, it returns `ArrayBuffer`.

**Describe the solution you'd like**

Since `GLTFWriter` already supports plugins, it would make sense to extend it to invoke extensions for the root of the JSON data. Something like this could be called before calling `onDone`
```
this._invokeAll( function ( ext ) {

    ext.afterJson && ext.afterJson(json);

} );
```
**Describe alternatives you've considered**

`extras` could be passed in options to  `GLTFExporter`, which would then assign them to `json.extras`. Or maybe `GLTFExporter.parse` could be extended to read and object containing scenes and extras, e.g. 

```
{ 
    scenes: [..],
    extras: { .. }
}
```

**Additional context**

Thanks!

**Comment by phillip-mcnallen-tfs** [comment]
I second this, and will probably be working on the same thing very soon as it's something we need also.  Your solution for how to pass the field makes sense to me.  If everybody likes this I'll do a PR when I have time to implement.

**Comment by donmccurdy** [comment]
I'm happy with either of these suggestions. 👍
