### ISSUE TITLE
ThreeJS Editor spotlight loses target on GLTF export

### ISSUE THREAD

**Issue by phillip-mcnallen-tfs** [mrdoob/three.js#22515]
I think this may be a regression because I seem to remember this not always being an issue but when you open r132 editor and add a spotlight it will add to scene like this:
![image](https://user-images.githubusercontent.com/71730392/132756043-231adc30-458c-46dd-a167-18dac1c2f9d7.png)

After exporting as .glb and importing the file you just exported, it will load in like this:
![image](https://user-images.githubusercontent.com/71730392/132756194-2790054c-fc73-4b18-99e6-d523392cfa91.png)

It seems to me that the position and other parameters are still accurate, though the direction of the spotlight is totally lost.

In the past I remember SpotLight having a nameless "target" child under it after adding it to the scene.  This does not occur anymore: 
![image](https://user-images.githubusercontent.com/71730392/132756545-eaad2aaa-fafc-4e9c-9b3f-553c410c9c3c.png)

**Comment by Mugen87** [comment]
> In the past I remember SpotLight having a nameless "target" child under it after adding it to the scene. This does not occur anymore:

I'm not aware that the `target` child object was ever part of the outliner. At least it does not pop up even if we go far back in history:

https://raw.githack.com/mrdoob/three.js/r80/editor/index.html

When exporting a scene with a spotlight to glTF, the following warning is logged by the exporter:

>  THREE.GLTFExporter: Light direction may be lost. For best results, make light.target a child of the light with position 0,0,-1.

`three.js` has a special way how certain light types are oriented. Spotlights and directional lights are always "targeted" meaning their orientation is derived by letting them look at their target object. You can't change the light direction by modifying its `rotation` property. Hence, it's hard right not to properly export light setups to glTF from the editor. 

This issue can be resolved by adding a solution like in #14658.

**Comment by Mugen87** [comment]
Merging this into #5079.
