### ISSUE TITLE
Significant slowdown from r0.127.0 to r.0.128.0

### ISSUE THREAD

**Issue by oveddan** [mrdoob/three.js#22517]
I know this is going to be hard to reproduce without any code. But we recently upgraded our codebase from using t0.124.0 to 0.132.2, and noticed a significant slowdown.

We tried every release before that to see which one slowed things down, and came to the conclusion that 0.128.0 was the release that caused the slowdown.  0.127.0 runs fast.   

We tested this out by deploying the same exact code, with just different releases of three.js

We are using react-three-fiber, and an application that uses a combination of gltf loading, lights, image textures, video textures, and raycasting.  So it's hard to pinpoint exactly where things are slowing down.

Again, between 0.127.0 and 0.128.0 our code has not changed at all.
Feel free to block camera access if opening the links below:
You can see 0.127.0 deployed here: https://613a77977f9b8600070ec883--arium.netlify.app/spaces/templo-solar
And 0.128.0 deployed here: https://613a8f05ff551c0007feccd6--arium.netlify.app/spaces/templo-solar

This is Occuring on Chrome 93.0.4577.63 on Mac OS

We use buffer geometry everywhere.

What would you suggest to help track down the slowdown?
The migration guide doesnt mention anything that could potentially cause this.

**Comment by oveddan** [comment]
And I just want to add thank you for creating and maintaining this amazing framework

**Comment by octopoulos** [comment]
The 0.127.0 example seems to be running three.js r124, not r127...
0.128.0 is indeed r128.
What I would do is just disable as many things as possible, and then compare both builds, and then only enable 1 feature at a time, until the slowdown appears, then you know what's happening.

**Comment by Mugen87** [comment]
Sorry, we can't investigate the performance issue of an entire app, especially not when it is written with `react-three-fiber`. As mentioned by @octopoulos, try to reproduce the issue with a small test case. You can then reopen the issue.

**Comment by oveddan** [comment]
Totally get it and makes sense!  Better to be more specific about where the problem lies.  Thanks anayways!
