### ISSUE TITLE
FBXLoader bug: Offset is Outside the bounds of the DataView

### ISSUE THREAD

**Issue by SerFerBla** [mrdoob/three.js#22524]
**Describe the bug**

I am not able to load large .FBX models. I have a 240M model that I'd like to load but everytime I want to load it, I get the following error: 
`RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at BinaryReader.getUint32 (FBXLoader.js:3722)
    at BinaryParser.parseNode (FBXLoader.js:3360)
    at BinaryParser.parseNode (FBXLoader.js:3390)
    at BinaryParser.parseNode (FBXLoader.js:3390)
    at BinaryParser.parse (FBXLoader.js:3322)
    at FBXLoader.parse (FBXLoader.js:119)
    at Object.onLoad (FBXLoader.js:93)
    at XMLHttpRequest.<anonymous> (three.module.js:36609)`

I'm afraid I can't share the model with you because of the content it includes but it's a model that I can view in any 3D editing tool but Three JS doesn't load. 

To check that it was not my fault, I tried to load my model into the Online editor but I got the same error. 

Do you know how could I solve this issue? It seems to be a restriction/bug in the loader. The only thing that comes to my mind is to reduce its size by splitting the model but I'd prefer not to do that.

Could it be something like this: https://github.com/mrdoob/three.js/issues/20622 ?

Thanks in advance.

**Expected behavior**
The model should load successfully but it doesn't.

**Platform**:

Device: all
OS: all
Browser: all
Three.js version: all

**Comment by Mugen87** [comment]
> I have a 240M model

Can you try to significantly lower the size of the model and try again?

**Comment by makc** [comment]
@Mugen87 well it is said that
>  it's a model that I can view in any 3D editing tool 

maybe it is unsupported fbx version? too old, or too new

**Comment by Mugen87** [comment]
I'm afraid without a test asset it will be hard to investigate the issue.

**Comment by zlatnaspirala** [comment]
I have working at localhost but on public server not.
Same logs.
