### ISSUE TITLE
upgrading three.js from r131 to r132 breaks three.js demo using custom fragment shader

### ISSUE THREAD

**Issue by kimbaudi** [mrdoob/three.js#22520]
**Describe the bug**

upgrading three.js from v0.131.3 to v0.132.2 breaks three.js demo (blank page & fragment shader error). need to know how to update custom fragment shader so it works with latest three.js r132.

**To Reproduce**

1. Go to https://github.com/kimbaudi/threejs-test and clone repo
2. Run `yarn install && yarn build && yarn serve` or `yarn install && yarn start`
3. See working three.js demo
4. Update three.js from v0.131.3 to v0.132.2 in `package.json`
5. After updating three.js, run `yarn install && yarn build && yarn serve` or `yarn install && yarn start`
6. See blank page and error message in console.

***Code***

shader.frag

```c
uniform float opacity;

// Shader Chunks
#include <common>
#include <bsdfs>
#include <lights_pars_begin>
#include <lights_phong_pars_fragment>

void main() {

	vec3 diffuse = vec3(0.7);
	vec4 diffuseColor = vec4(diffuse, opacity);

	vec3 specular = vec3(1.0);
	float shininess = 30.0;
	float specularStrength = 0.5;

	vec3 normal = normalize(vNormal);

	ReflectedLight reflectedLight = ReflectedLight(vec3(0.0), vec3(0.0), vec3(0.0), vec3(0.0));

	GeometricContext geometry;

	geometry.position = - vViewPosition;
	geometry.normal = normal;
	geometry.viewDir = normalize(vViewPosition);

	BlinnPhongMaterial material;
	material.diffuseColor = diffuseColor.rgb;
	material.specularColor = specular;
	material.specularShininess = shininess;
	material.specularStrength = specularStrength;

	IncidentLight directLight;

	// Directional Light
	#if NUM_DIR_LIGHTS > 0

		DirectionalLight directionalLight;

		for (int i = 0; i < NUM_DIR_LIGHTS; i++) {

			directionalLight = directionalLights[i];

			getDirectionalDirectLightIrradiance(directionalLight, geometry, directLight);

			#ifdef USE_SHADOWMAP
				directLight.color *= all(bvec2(directionalLight.shadow, directLight.visible)) ? getShadow(directionalShadowMap[i], directionalLight.shadowMapSize, directionalLight.shadowBias, directionalLight.shadowRadius, vDirectionalShadowCoord[i]) : 1.0;
			#endif

			RE_Direct(directLight, geometry, material, reflectedLight);
		}

	#endif

	// Point Light
	#if (NUM_POINT_LIGHTS > 0)

		PointLight pointLight;

		for (int i = 0; i < NUM_POINT_LIGHTS; i++) {

			pointLight = pointLights[i];

			getPointDirectLightIrradiance(pointLight, geometry, directLight);

			#ifdef USE_SHADOWMAP
				directLight.color *= all(bvec2(pointLight.shadow, directLight.visible)) ? getPointShadow(pointShadowMap[i], pointLight.shadowMapSize, pointLight.shadowBias, pointLight.shadowRadius, vPointShadowCoord[i]) : 1.0;
			#endif

			RE_Direct(directLight, geometry, material, reflectedLight);
		}

	#endif

	// Ambient Light
	vec3 irradiance = getAmbientLightIrradiance(ambientLightColor);
	RE_IndirectDiffuse(irradiance, geometry, material, reflectedLight);

	// Accumulated Light
	vec3 outgoingLight = reflectedLight.directDiffuse + reflectedLight.indirectDiffuse + reflectedLight.directSpecular + reflectedLight.indirectSpecular ;

	gl_FragColor = vec4(outgoingLight, diffuseColor.a);
}
```

**Expected behavior**

Upgrading three.js to r132 should not break my three.js demo using custom fragment shader. Either that or I should be able to update my custom fragment shader so it doesn't throw error when using it with three.js r132.

**Screenshots**

before upgrading three.js to r132, my three.js demo works:

![aaaa](https://user-images.githubusercontent.com/1864092/132812655-6546b787-d93a-4171-b77d-faaf54d3a5fc.png)

after upgrading three.js to r132, three.js demo no longer works.

![bbbb](https://user-images.githubusercontent.com/1864092/132812692-cbdc8ec6-db84-4f90-8f72-e722532f38ae.png)

I need to update my `shader.frag` file to work in three.js r132, but I don't know how. At the moment, I am just commenting out the fragment shader. This temporarily gets rid of the error and shows the cubes in red color.

![cccc](https://user-images.githubusercontent.com/1864092/132812883-059de50b-d8f7-4aab-b9a7-f6847cc08ef2.png)

Any idea how to update my `shader.frag` to work with three.js r132?

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [dev, r132]

**Comment by Mugen87** [comment]
I've responded to your topic at the forum. The solution is mentioned here: https://discourse.threejs.org/t/threejs-r111-it-normal-but-threejs-r131-it-error-using-shadermaterial-error-maptexeltolinear-no-matching/29544/10
