### ISSUE TITLE
some particle renderers

### ISSUE THREAD

**Issue by avatar-studio** [mrdoob/three.js#22528]
**Is your feature request related to a problem? Please describe.**

I've been making particles for a few weeks now.
While I was making this, I figured that adding some features would make it easier for people to use three.js.
So I have a few requests.

**Describe the solution you'd like**

1. vertical material
A vertical billboard is often used to enhance the completeness of particles.
I've been working on this through the community, but it's not perfect yet.
![vertical](https://user-images.githubusercontent.com/88191844/132944170-ef684e4c-6376-4c0d-911c-310235a79d3c.png)

2. trail renderer
A trail renderer that follows the trajectory of missile particles will definitely make the particles look elegant.
However, this is very difficult for an individual to implement.
I also solved most of the problems by creating particles, but this one wasn't as easy.
![trail renderer](https://user-images.githubusercontent.com/88191844/132944465-258f477d-9f41-45b9-85bd-7cea5bc49762.png)

**Describe alternatives you've considered**

I thought the above features were needed for weeks, but I found the answer today.
If you look closely, the above functions were to map a texture to the line renderer, specify the thickness, and let the camera adjust the thickness as it moves.
If you adjust the vertices of the line renderer with bufferGeometry, etc., the trail renderer seems to be easily applied.

**Additional context**

The line renderer I suggested may not be the definitive answer. Even so, please make a vertical material and a trail renderer.
It is too hard for an individual to implement.

**Comment by Mugen87** [comment]
It seems the forum is the better place for this post: https://discourse.threejs.org/
