### ISSUE TITLE
OrbitControls - Zoom to cursor

### ISSUE THREAD

**Issue by philippb** [mrdoob/three.js#22522]
# Related problem
**Is your feature request related to a problem? Please describe.**
We're working on a Sigma style editor for electrical engineering and PCB design. Navigating within a design by zooming is a big part of our application.
The current zoom controls always force the user to pan and then to zoom. This is a sub-optimal experience

# Solution
## Describe the solution you'd like
Zoom to cursor allows you to zoom a screen to the current position of the cursor. The movement is a combination of pan and zoom. The cursor stays during the entire operation at the same position and the scene zooms in around the objects of the cursor.
The behaviour is the same as it is implemented in [Google Maps web interface in 3D view](https://www.google.com/maps/@52.4894322,13.3981528,2101a,35y,358.43h,47.16t/data=!3m1!1e3!5m1!1e4) or Apple’s macOS Maps app in 3D view for zooming IN and OUT.

## Describe alternatives you've considered
We have hacked the zoom to cursor in the OrthographicCamera and are looking to have a better version that also supports the PerspectiveCamera in the main repo.
You can find the solution in https://github.com/buildwithflux/three-orbitcontrols/blame/master/OrbitControls.js when looking. for the commit _Zoom to cursor_.

## API spec proposal
There are different ideas on how the API interface for this functionality could look like.

### Proposal 1
`zoomToCursor: Bool` - Requires `enableZoom` to be set to true as a prerequisite. When true, changes the zoom mode from the center of the scene to zooming to the cursor.

### Proposal 2 - preferred 
`zoomMode: Enum { .center, .cursor }` - Defines the zoom mode of the `enableZoom` flag. `.center` behaves like existing zoom functionality while `.cursor` allows for zooming to the cursor. Default: `.center`.

Personal opinion: I prefer proposal 2, as it will play nice with the “Zoom to objects” proposal and other future zoom functionality as well. Maintaining multiple booleans where the behavior is not clear defined is always messy. 

## Tasks
- Implement zoom to cursor in OrthographicCamera, [initial implementation](https://github.com/buildwithflux/three-orbitcontrols/blame/master/OrbitControls.js) can be used as a starting point.
- Define with maintainers of this project how zoom to cursor in the PerspectiveCamera should behave.
- Implement zoom to cursor in PerspectiveCamera 
- Add documentation: https://threejs.org/docs/#examples/en/controls/OrbitControls 

References
Google Maps 3D view with zoom to cursor
![Screen Shot 2021-09-10 at 12 36 22 PM](https://user-images.githubusercontent.com/374326/132841244-886dd5ad-0a9a-47eb-83c6-fe2f21bbea90.jpg)

# Implementation plan
We aim to implement this feature ourselves. We're filing a GitHub issue to be able to communicate about the implementation details with the projects core maintainers.

**Comment by Mugen87** [comment]
There us already a PR for this: #17145

**Comment by philippb** [comment]
@Mugen87 Thanks, I didn't see that. How do you think we can help best getting this to a state that is where i can be merged in? The linked PR has been open for 2 years. We're happy to help getting this over the finish line or just to make a clean version from scratch. 
Your guidance is appreciated.

**Comment by Mugen87** [comment]
I think it's best if you continue the discussion at #17145. Looking at the code, I'm not sure what prevented the PR from becoming "ready-to-review".

**Comment by looeee** [comment]
@philippb you can also check out [yomotsu/camera-controls](https://github.com/yomotsu/camera-controls) which has zoom to cursor.

**Comment by jiannanya** [comment]
hi, I have a feature for this, it has already been implemented at [#23254](https://github.com/mrdoob/three.js/pull/23254)  both for perspective camera and orthographic camera but not for docs so far, please give me some advice if you are interested in it.
