### ISSUE TITLE
BOUNTY: WILL PAY YOU TO DO OPEN SOURCE | Parallax/heightmap Shader

### ISSUE THREAD

**Issue by kylebakerio** [mrdoob/three.js#22529]
**Is your feature request related to a problem? Please describe.**

Would like to be able to implement a parallax texture /heightmap without geometry easily. This would enable richer ground elements, creating the illusion of depth without the weight of adding the appropriate geometry in many cases--likewise with building textures. (If I'm not mistaken--if I am, let me know!)

**Describe the solution you'd like**

It should be equivalent to the functionality present out-of-the-box in Babylon described here: https://doc.babylonjs.com/divingDeeper/materials/using/parallaxMapping
and the end result should (I think) be what is achieved here in this THREE demo: https://mebiusbox.github.io/contents/pixyjs/samples/shader_parallax_occlusion.html

Personally, I'll immediately be trying to figure out how to include it in A-Frame, as that's the context in which I use THREE. I just want it to be as easy to add as any other map/texture stuff.

**Describe alternatives you've considered**

I've tried finding a THREE dev to pay to build this. I've asked for instructions on how to build this, though I'm out of my depth here. Clearly it is possible using THREE, just not made easy. I can find old issues discussing this, but it seems to have never been prioritized.

**Additional context**

[Here](https://github.com/kylebakerio/grass) are the assets I have that I'd like to turn into a parallax shader effect--if other assets are needed, I have an artist that can produce them, let me know how this should be designed and come up with an 'input' spec to produce the desired output.

**I'm happy to put a bounty on this--tell me your hours and rate, and if it's reasonable, I can get it covered in our dev budget.** If you can produce it within the next week or so, I will provide a bonus on top of pay. I'd love to see this be a reusable open source component. Also willing to pay to have this implemented as an A-Frame component.

![image](https://user-images.githubusercontent.com/6391152/132953423-7dab3165-536d-4523-b032-0416b260cf5e.png)

**Comment by RenaudRohlinger** [comment]
@kylebakerio 👋

Here is the shader (and for free 😄 ): https://codesandbox.io/s/r3f-parallax-map-forked-s4shn?file=/src/parallaxMap.js

**Comment by RenaudRohlinger** [comment]
😬 https://github.com/mrdoob/three.js/pull/22370

**Comment by mrdoob** [comment]
Yeah, if you don't need lighting you can find the code here:
https://raw.githack.com/mrdoob/three.js/r131/examples/webgl_materials_parallaxmap.html

**Comment by Mugen87** [comment]
Also please use the `Jobs` category in the [forum](https://discourse.threejs.org/) for such requests.

**Comment by kylebakerio** [comment]
I did post in jobs first, and also posted in Reddit as well as the discord. I got two leads in jobs, but neither followed up.

I didn't have capacity in this job to go deep enough into THREE to figure out how to follow that example myself within an A-Frame context, unfortunately. Sadly, this project is wrapping up now. Grass was a nice-to-have, guess we'll go without and I'll look into implementing it myself next time.

**Comment by mrdoob** [comment]
When did you start working in the project?

**Comment by kylebakerio** [comment]
Yeah... this client does really rapid dev, to put it in kind terms, haha. I'm building two for them simultaneously, while managing a third. we even had to pass on a fourth. somehow, all have their deadlines this week.

 We weren't able to find another dev in time, which is why two fell on me to do, and we only had a little over a month to negotiate, plan, and implement all of them, so... it's been quite a sprint. ¯\_(ツ)_/¯

pretty stressful, but can't complain about the pay.

**Comment by mrdoob** [comment]
Please, do not unload that stress into open source libraries. Imagine if everyone did that.

**Comment by kylebakerio** [comment]
I just saw what looked like a missing feature in a library I enjoy and gain from utilizing, and a chance to pay someone to contribute. I'm not sure what you mean by unloading stress... It was an urgent window of opportunity, but I'm not unloading anything on anyone.

I love chances to do things like this.
