### ISSUE TITLE
SVGLoader: Support <text> node

### ISSUE THREAD

**Issue by wxyer** [mrdoob/three.js#22535]
**Describe the solution you'd like**

i have a svg ,it has some content like this
`<text data-5="AE773" x="447.2511" y="-76.3672" fill="#00ff00" font-size="8.75" stroke="none" style="white-space:pre">4-3号强变形区</text>` ,
when using svgloader,the text not appeared.

**Comment by wxyer** [comment]
i have a svg ,it has some content like this "<text data-5="AE773" x="447.2511" y="-76.3672" fill="#00ff00" font-size="8.75" stroke="none" style="white-space:pre">4-3号强变形区</text",when using svgloader,the text not appeared.

**Comment by wxyer** [comment]
i have a svg ,it has some content like this "<text data-5="AE773" x="447.2511" y="-76.3672" fill="#00ff00" font-size="8.75" stroke="none" style="white-space:pre">4-3号强变形区</text",when using svgloader,the text not appeared.

**Comment by wxyer** [comment]
i have a svg ,it has some content like this "<text data-5="AE773" x="447.2511" y="-76.3672" fill="#00ff00" font-size="8.75" stroke="none" style="white-space:pre">4-3号强变形区</text",when using svgloader,the text not appeared.

**Comment by wxyer** [comment]
i have a svg ,it has some content like this "</text data-5="AE773" x="447.2511" y="-76.3672" fill="#00ff00" font-size="8.75" stroke="none" style="white-space:pre">4-3号强变形区</text",when using svgloader,the text not appeared.

**Comment by mrdoob** [comment]
Doesn't sound like an easy thing to do...

**Comment by wxyer** [comment]
> Doesn't sound like an easy thing to do...

“data-5” should be not a normal attribute,thanks a lot

**Comment by Mugen87** [comment]
Regarding the complexity of text generation, it seems to me this feature request is out of scope. Probably better to focus on the open points mentioned in https://github.com/mrdoob/three.js/issues/21330#issuecomment-806367989

**Comment by mrdoob** [comment]
Indeed. Better to not support for text.
