### ISSUE TITLE
node material examples is borken

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#22532]
Just saw this on discord - https://threejs.org/examples/webgl_materials_standard_nodes.html fails to compile the shader
![Screen Shot 2021-09-12 at 13 26 34 ](https://user-images.githubusercontent.com/242577/132985732-3dc5ac78-e21e-4614-bfdc-b452fa589961.png)

**Comment by Mugen87** [comment]
Should be fixed on `dev`:

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_materials_standard_nodes.html

**Comment by makc** [comment]
ha ha @Mugen87 why did you guys switch to importmap?  its dead in my firefox now
![Screen Shot 2021-09-12 at 19 31 01 ](https://user-images.githubusercontent.com/242577/132997121-d4e73c0f-a720-4aa7-9049-ad5afac6e69d.png)

granted, it is 1 year old firefox, but it is the last one supported on this mac os x (10.11) 😭

**Comment by mrdoob** [comment]
[Import maps will eventually land in Firefox](https://github.com/mozilla/standards-positions/issues/146). But you'll sure need to update to a newer MacOS...

**Comment by mrdoob** [comment]
More info here: https://github.com/mrdoob/three.js/pull/21364

**Comment by makc** [comment]
> update to a newer MacOS

@mrdoob which means buying new mac basically because 10.11 is last os that supports mbp'09 😅 so it is probably going to be win11 for me
