### ISSUE TITLE
Left hand side of operator '=' must be a reference. Only in Webkit/Safari in Angular production build

### ISSUE THREAD

**Issue by VITOLDO** [mrdoob/three.js#22537]
**Describe the bug**

Receiving this error when trying to run Angular application on Webkit/Safari (iPad or iPhone)
Left hand side of operator '=' must be a reference

Note: Android works ok, PC works ok.

**To Reproduce**

1. Build up an Angular application that uses three js lib.
2. Open any stl/ply file by this lib.
3. Open page on iPhone/iPad device.

***Code***

```js
(self.webpackChunkfrontend = self.webpackChunkfrontend || []).push([[179], {
3597: t => {
    function e(t) {
        return Promise.resolve().then(() => {
            var e = new Error("Cannot find module '" + t + "'");
            throw e.code = "MODULE_NOT_FOUND", e
        })
    }
    e.keys = () => [],
    e.resolve = e,
    e.id = 3597,
    t.exports = e
},
88642: (t, e, n) => {
    "use strict";
    n.d(e, {
        T: () => l
    });
```

***Live example***

Issue has stackoverflow good description:
https://stackoverflow.com/questions/68224800/left-hand-side-of-operator-must-be-a-reference-only-in-webkit-safari-in-ang

**Expected behavior**

Webkit/Safari doesn't throw exception upon opening page that is using three js lib.

**Platform:**

 - Device: [Mobile]
 - OS: [iOS]
 - Browser: [Chrome, Safari]
 - Three.js version: [r129]

**Note:**
Version: 0.125.2 - seems work on Webkit/Safari but it would be good to have latest and greatest Three.js used in application!

**Comment by Mugen87** [comment]
I'm afraid your issue does not explain the problem in the code base. Please clarify your description.

**Comment by mrdoob** [comment]
Sounds like the issue is somewhere else.
