### ISSUE TITLE
Does not load IFC models while using OCULUS QUEST 2

### ISSUE THREAD

**Issue by andreacarpibomber** [mrdoob/three.js#22534]
**Describe the bug**

Does not load IFC models while using OCULUS QUEST 2 (I could try only with this device)

**To Reproduce**
Run the threejs example of ifc loader from OCULUS QUEST 2.

https://threejs.org/examples/webgl_loader_ifc

**Platform:**

 - Device: OCULUS QUEST 2
 - Three.js version: current

**Comment by Mugen87** [comment]
The example's IFC model `rac_advanced_sample_project` is quite big (>40MB). Maybe you have tested with a bad internet connection and not waited long enough?

Besides, have you tried to connect the Quest 2 to your computer in order to read out the console logs of Oculus Browser? Maybe there are runtime errors logged which could be useful for investigating the issue.

**Comment by andreacarpibomber** [comment]
Thanks for the prompt response. I have been waiting for a while, more than five minutes, before giving up. My internet connection is pretty fast, and I can run the same page on my mac and the model is visible in less than ten seconds.
I could not connect my visor to the computer becasue i have never done this before. If you think this could help we could schedule a call or i can follow your further instructions!

Andrea Carpi

**Comment by Mugen87** [comment]
> Besides, have you tried to connect the Quest 2 to your computer in order to read out the console logs of Oculus Browser?

I've tried this today but realized that the former `Settings` tab is gone with the latest Oculus App version. I could not figure out so far how to enable dev mode...

**Comment by Mugen87** [comment]
But yes, I can confirm the issue. For some reasons, the IFC asset is not loaded with Oculus Browser.

**Comment by agviegas** [comment]
Hi, could you please create this issue in one of our repos to track it down? Thank you!

**Comment by mrdoob** [comment]
I don't think this is related to `IFCLoader`...

Tested on my Quest 2 and the file doesn't load indeed. With `chrome://inspect` I see this:

<img width="1136" alt="Screen Shot 2021-09-17 at 12 41 37 AM" src="https://user-images.githubusercontent.com/97088/133702431-64c36e21-1147-4ee1-b6ff-f1cec6e1e891.png">

However, if I reload the example with the devtools open then the file loads correctly:

<img width="1136" alt="Screen Shot 2021-09-17 at 12 42 29 AM" src="https://user-images.githubusercontent.com/97088/133702478-b52508a6-0f93-486c-85cc-7a9f8f1627fa.png">

@cabanier @davehill00 Any ideas?

**Comment by davehill00** [comment]
Most of the WASM hiccups we've seen on Oculus Browser have been related to memory issues. 

We recently hit one where the stack size specified when generating the WASM wasn't big enough and caused things to fail. 

We've also seen some issues where allocations on the heap are big and blow through whatever limit is set for WASM.

**Comment by mrdoob** [comment]
But is it expected that the scene loads only when DevTools is open?

**Comment by davehill00** [comment]
No, definitely not. That is very strange. I wonder if there's a timing/race condition that causes things to run slightly differently when dev tools are open?
________________________________

**Comment by davehill00** [comment]
Hmm... FWIW, it looks like it loads consistently for me in about 20-25 seconds regardless of whether Dev Tools are connected or not.

**Comment by cabanier** [comment]
I'm also unable to reproduce it. I wiped my device and it still loaded with no issues.
We're currently rolling out a new browser release (17.0). Please try again with that version.

**Comment by andreacarpibomber** [comment]
The issue unfortunately seems to be still there. here is a video. This is the version of oculus I am running! I can't update to 17.0, maybe it is not yet available in Italy?
<img width="350" alt="Schermata 2021-09-20 alle 08 46 01" src="https://user-images.githubusercontent.com/49713228/133964928-17ac553f-583a-4960-96b7-d0f797c49faa.png">


https://user-images.githubusercontent.com/49713228/133964868-375c5916-545f-4010-8ff1-e93a53175bda.mp4

**Comment by Mugen87** [comment]
>  I can't update to 17.0, maybe it is not yet available in Italy?

Please try it again when 17 is available. As long as you are not on that version, additional tests are not necessary.

**Comment by cabanier** [comment]
We just moved 17.0 to 100% of all users. You should have it in a couple of hours.

**Comment by cabanier** [comment]
@andreacarpibomber did you get the new release?

**Comment by andreacarpibomber** [comment]
It does work now! Brilliant!

**Comment by andreacarpibomber** [comment]
I am getting a New Error when I try entering VR from my OCULUS QUEST 2, someone might help? I think this is a new problem but is quite related to the previous one. This is the link to the environment I am using https://www.andreacarpi.it/three/ 
![unnamed-1](https://user-images.githubusercontent.com/49713228/135430981-d042fbfc-8071-489e-8a90-106b36ebdd9d.png)

**Comment by mrdoob** [comment]
We use GitHub issues to track confirmed bug reports and feature development.
If you need help, please use the [forum](https://discourse.threejs.org/), the [chat](https://discord.gg/HF4UdyF) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
