### ISSUE TITLE
Points Error

### ISSUE THREAD

**Issue by avatar-studio** [mrdoob/three.js#22546]
**Describe the bug**

In additive mode, low index particles hide high index particles.

**To Reproduce**

Please go to the url below.
https://jsfiddle.net/avatar_studio/6zdfkbxg/39/

***Code***

    let map = new THREE.TextureLoader().load("https://i.imgur.com/t67jhSj.png");
    let maxParticles = 3;
    let positions = new Float32Array( maxParticles * 3 );
    let mat = new THREE.PointsMaterial({map, blending:THREE.AdditiveBlending});
    let geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.BufferAttribute( positions, 3 ).setUsage( THREE.DynamicDrawUsage ) );
    let points = new THREE.Points(geometry, mat);

***Live example***

https://jsfiddle.net/avatar_studio/6zdfkbxg/39/

**Expected behavior**

When creating particles, you cannot use the transparency due to black in additive blending.

**Screenshots**

![addtive error](https://user-images.githubusercontent.com/88191844/133762085-21ffe8ab-39b0-4d9e-8bf4-e01d0098dec5.png)

**Platform:**

 - Device: [all]
 - OS: [all]
 - Browser: [all]
 - Three.js version: [dev, r132]

**Comment by Mugen87** [comment]
In this setup, set `depthWrite` to `false`: https://jsfiddle.net/1adgu73y/

**Comment by avatar-studio** [comment]
Of course I know.
However, I get an error when interacting with 3dObject.
Both depthWrite and depthTest throw an error.

https://jsfiddle.net/avatar_studio/6zdfkbxg/35/

**Comment by avatar-studio** [comment]
The particle is in front, but the box behind it hides it.
![hide error](https://user-images.githubusercontent.com/88191844/133768148-44c8aecb-5425-4968-9d9f-5f6361472761.png)

**Comment by Mugen87** [comment]
Try it like so: https://jsfiddle.net/uygasq6v/

By defining a manual render order you can force the points to render last.

**Comment by avatar-studio** [comment]
It works without problems. thank you.
==> points.renderOrder = Infinity;

**Comment by Mugen87** [comment]
Please use the forum first next time.
