### ISSUE TITLE
gltf darker in 0.132.2 compared to 0.131.3

### ISSUE THREAD

**Issue by epouliquen** [mrdoob/three.js#22545]
Hi, please see my model in 0.131.3 and 0.132.2 (see revision in js console on pictures.

Both are using linear tonemapping, code copied from tonemapping example. output is sRGB in both cases. Only threeJS revision has changed.

it seems 0.131.3 looks better, compared to other viewers, using same model.

Is it a bug or maybe I missed something in 131 -> 132 migration ? Nothing about this in migration notes.

Thanks

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/50987570/133758503-1ea899bc-29ba-4cf8-8fcb-2caa1db7364c.jpg)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/50987570/133758508-f3ccf890-77d7-4a0d-81e0-0e9f2221a8c7.jpg)

**Comment by Mugen87** [comment]
Can you please share a live example that shows the issue? Without seeing the entire code it's hard to provide feeedback.

Shaders were refactored and corrected at various places in `r132`. It could be possible that these changes are responsible for the different (but more correct) output.

**Comment by mrdoob** [comment]
I think this is due to #22308.

I'd be hard to come up with a clear and understandable description of this change for the migration notes...

**Comment by Mugen87** [comment]
Maybe something like: _Lighting computations of `MeshStandardMaterial` are more physically correct now. In certain use cases, less environmental lighting will be reflected which means models could be rendered darker than before._

**Comment by mrdoob** [comment]
Thanks!

Reworded it to this:

*`MeshStandardMaterial` and `MeshPhysicalMaterial` shaders are now more correct and may result in less shinny renders for models using rough materials.*

https://github.com/mrdoob/three.js/wiki/Migration-Guide
