### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [mrdoob/three.js#22543]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by mrdoob** [comment]
You can DM me on Twitter (https://twitter.com/mrdoob).

**Comment by mrdoob** [comment]
I'll add the file in the repo later today.

**Comment by mrdoob** [comment]
They didn't contact me either.

**Comment by JamieSlome** [comment]
@mrdoob - https://huntr.dev/bounties/eaf7f323-66ab-483a-b986-bee11008ca25/

**Comment by JamieSlome** [comment]
@amammad - can you address the above ☝️

**Comment by mrdoob** [comment]
I think it'll be better to move this conversation to the forum.

Feel free to reopen this issue once you guys have a clear explanation of the security issue.

**Comment by amammad** [comment]
Hey makc, sorry for late
someone change the payloads I think!!
this is the bad crafted payload :
https://regexr.com/676tc

and this is a good input that have a very very length against bad payload too:
https://regexr.com/676tf

If you see 'ERROR' for payload 2  then reduce some letters from the end of input.

**Comment by makc** [comment]
@amammad I could reproduce in FF. basically an input like `"ddddddddddddddddd` (no closing quote) takes a lot of time after certain length 🤔

**Comment by amammad** [comment]
Can i ask you validate my report and make me happy please ? if the severity or any information in my report should be changed just tell me, for example tell me to set a low or medium cve score for it.

https://huntr.dev/bounties/eaf7f323-66ab-483a-b986-bee11008ca25/

**Comment by makc** [comment]
ask @mrdoob  - I am just passing by here.

the slowness of the reg is caused by asterisk - you can see that `/"([^"]+)*"/` is also slow on the same input, but `/"([^"]+)"/` is not. would be nice if someone who remembers VRML format did check if that asterisk could be dropped by adding a + somewhere inside the group, for example

**Comment by mrdoob** [comment]
How about just doing a PR with the fix so we can move on?

Issues like this one shouldn't need so much discussion.

**Comment by amammad** [comment]
no problem, after that you can submit the PR on huntr report too
