### ISSUE TITLE
background color not being set in oculus browser

### ISSUE THREAD

**Issue by driescroons** [mrdoob/three.js#22553]
**Describe the bug**

It seems that ever since `0.132.0` setting your background color on the oculus browser is broken.

I've tried setting it using setClearColor renderer method, setting the background color directly on the scene, but nothing seems to be working.

Everything is working fine on my Valve index.

***Live example***

For those who have a quest headset, I've setup following example:
https://codesandbox.io/s/bitter-violet-ejbv7

You can switch between the versions, and see how it's still working on `0.131.3`

In your headset, go to:
https://ejbv7.csb.app/

It is written in react-three-fiber, but bug should still apply.

**Expected behavior**

Background should be able to be set.

**Screenshots**

`0.131.3`: https://imgur.com/O34oUTx
`0.132.0`: https://imgur.com/8QhS05t

**Platform:**

 - Device: Quest 2
 - OS: Android
 - Browser: Oculus browser
 - Three.js version: from `0.132.0`

**Comment by CodyJasonBennett** [comment]
See #22508.

**Comment by driescroons** [comment]
Only noticed just now. Thanks for the quick reply!
