### ISSUE TITLE
Provide multi-material support in exporters.

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#22555]
**Describe the bug**
USDZExporter does not work with material arrays ( multi-material)

**To Reproduce**
Any sample with multi-material ( mesh.material as array)
***Code***
three.js/examples/js/exporters/USDZExporter.js 
```js
if ( object.isMesh && object.material.isMeshStandardMaterial ) 
```

**Platform:**
All

**Comment by mrdoob** [comment]
Does USDZ support multi materials?

**Comment by whatisor** [comment]
No, I don't think so.
I overcame this by splitting geometry base on material index.

**Comment by whatisor** [comment]
For ref, if someone gets same issue:

`//utilities
    //split geometry by material index
    function splitByMaterialIndex(mesh,materials){
        let result = new THREE.Group();
        //split groups by material index
        materials.forEach((mat,index) =>{
            let singleIndexGroups = mesh.geometry.groups.filter(g => g.materialIndex == index);
            let singleIndices = mesh.geometry.index.array.filter((val,index)=> {
                let belong = false;
                singleIndexGroups.forEach(g => {
                    belong |= (g.start <= index && g.count + g.start > index);
                })
                return belong;
            })
            let singleGeo = mesh.geometry.clone();
            singleGeo.setIndex(new THREE.BufferAttribute(new Uint16Array(singleIndices),1));
            let singleMesh = new THREE.Mesh(singleGeo,mat);
            singleMesh.visible = mesh.visible;
            result.add(singleMesh);
        })
		result.position.copy(mesh.position);
		result.rotation.copy(mesh.rotation);
		result.scale.copy(mesh.scale);
		result.name = mesh.name
        return result;
    }`

**Comment by mrdoob** [comment]
Nice! Would you like to do a PR with that?

**Comment by Mugen87** [comment]
That could be the foundation for a new utility method in [SceneUtils](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/utils/SceneUtils.js).

**Comment by mrdoob** [comment]
That sounds good to me 👍

**Comment by Mugen87** [comment]
@whatisor Are you interested in making a PR with your code?

**Comment by whatisor** [comment]
I've made it. I've not ever made a PR for this, so please help to review.
