### ISSUE TITLE
BufferAttribute Set/Get Methods access data at invalid indexes for itemSize < 4

### ISSUE THREAD

**Issue by keroiber** [mrdoob/three.js#22565]
**Describe the bug**

I use a BufferGeometry with 2d positions. The positions are generated by an external lib as Float32Array. It's perfectly ok for rendering to use that for a BufferAttribute with itemSize of 2, but the Set/Get methods of BufferGeometry do not completely honor the itemSize: In the case of itemSize==2 GetZ always returns the x value of the next vertex and (at least in my case) a NaN for the last entry (it reads one beyond the end).

**To Reproduce**

1. Create a 'position' BufferAttribute with itemSize = 2
2. You get this exception: `THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values.`

**Expected behavior**

- Get.. Methods should return 0 for the values that are not present in the buffer
- Set... Methods should at least ignore the value but maybe they should throw an exception

**Platform:**

 - Three.js version: found in r127, but the code still seems to be the same in dev

**Comment by keroiber** [comment]
I see that this bug was reported numerous times now. Please consider at least to return 0 from the Get-Methods for the values that are not set. I can prepare a PR for that.
This would solve the primary problem with the bounding box but also the more general problem that the geometry may come from a different piece of code than the part that handles it. This is not unusal for bigger projects and the current behavior is imho totally unexpected and a major pitfall.

**Comment by Mugen87** [comment]
I don't vote for doing that. `three.js` is a 3D library and does not fully support the 2D space. Even if getters and setters of `BufferAttribute` are fixed, there will be other places we changes are necessary, too.

The solution for your use case is to convert your 2D buffer data into 3D.

**Comment by mrdoob** [comment]
> I see that this bug was reported numerous times now. Please consider at least to return 0 from the Get-Methods for the values that are not set. I can prepare a PR for that.

I'm curious to see how the PR would look like 🤔

**Comment by keroiber** [comment]
> `three.js` is a 3D library and does not fully support the 2D data space.

OpenGL/WebGL are 3D rendering engines and support 2D vertex data...

**Comment by mrdoob** [comment]
@keroiber Feel free to do a PR with the approach you're proposing.
