### ISSUE TITLE
Editor: `#script` and `#player` dom.width does not right.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#22575]
**Describe the bug**

`#script` and `#player` dom.width does not change when dragged the `#sidebar` dom to the right direction.

**To Reproduce**

1. Go to https://threejs.org/editor/
2. Click on `#resizer` to the right direction.
3. See `#script` and `#player` dom.width does not right.

**Expected behavior**

`#script` and `#player` dom.width = `#viewport` dom.width

**Screenshots**

![image](https://user-images.githubusercontent.com/23699926/134539433-d8bdc20a-e60c-4cf5-bccb-807100745ebb.png)
![image](https://user-images.githubusercontent.com/23699926/134539625-013c2394-9f9b-422c-8474-a9ba832bc7ba.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome, Firefox, Edge]
 - Three.js version: [dev, r132]

**Comment by Mugen87** [comment]
I can confirm the issue. The script and player panels do not take the variable width of the side panel into account.
