### ISSUE TITLE
SSR Pass only reflection on the floor working in Firefox and chrome 

### ISSUE THREAD

**Issue by optimus007** [mrdoob/three.js#22579]
**Describe the bug**
When i open the ssr example in firefox and chrome on my laptop the reflections on the cubes and rabbit are not visible.
On my old phone it works , and on another desktop PC with gtx 1080 it works.

![sssr](https://user-images.githubusercontent.com/6885294/134663062-b8076636-12fe-4118-b7fe-fed62bd387ef.png)

Output "SSR only" shows full black
![outp ssr only](https://user-images.githubusercontent.com/6885294/134664057-12d6a4ab-3517-4c9c-9963-968bbd124462.png)

on firefox i got these two warnings in console and on chrome there's no errors/warnings
```
Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. 2 examples
Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”.
```
**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - GPU: [GTX 1650]
 - CPU: [ryzen 5]
 - Browser: [Chrome, Firefox]
 - Three.js version: [examples page]
 
 Another note : my monitor is 120hz , and this laptop has dual gpu, a radeon vega 8 inbuilt in the CPU and a GTX 1650

**Comment by gonnavis** [comment]
@optimus007 Hello, could you please take screenshots of Depth / Normal / Metalness outputs too?

**Comment by optimus007** [comment]
@gonnavis 

here you go ...they seem fine , 

Another note : my monitor is 120hz , and this laptop has dual gpu, a radeon vega 8 inbuilt in the CPU and a GTX 1650 

![dep](https://user-images.githubusercontent.com/6885294/134780430-36fe5fb6-e1c3-4966-ade5-420dc871abba.png)
![norm](https://user-images.githubusercontent.com/6885294/134780434-47091e8f-e64a-4703-9018-0d1a7c0fe064.png)
![met](https://user-images.githubusercontent.com/6885294/134780436-bfb20265-d706-470f-9b5a-ad2c40fe6c65.png)

**Comment by gonnavis** [comment]
Hello, in this case, the problem is likely to be in SSRShader.js.
But since I can't reproduce this problem, and there is no useful error message (  I did not use 'xr' ).
I think it will be very difficult to troubleshoot, I can only blindly guess where the problem is.

Please help me try different settings first, such as switching `infiniteThick` / `blur` / `fresnel` / `distanceAttenuation` / `groundReflector`, to see if it is possible to make the SSR effect display? Because these settings can bypass some of the glsl codes, might be able to avoid error-causing code. 
https://threejs.org/examples/?q=ssr#webgl_postprocessing_ssr

**Comment by optimus007** [comment]
@gonnavis 
`SSR toggle` and `Ground Reflector` Toggle  disables the ground reflection 

- `infiniteThick `/ `blur `/ `fresnel  ` cannot notice any difference
- `distanceAttenuation `& `max distance` slider works works
![distance att](https://user-images.githubusercontent.com/6885294/134850218-6690b4bc-2944-4f8d-85d8-e344292c1583.png)
  


SSRef pass seems fine
![ssr](https://user-images.githubusercontent.com/6885294/134850379-1c22dea2-90de-4da5-aa55-ac6d4d88774a.png)

**Comment by gonnavis** [comment]
Seems not related to SSRPass' settings.
I'll try to seek what difference between SSR and SSRr will cause this problem.

I have not js fiddle version now, but there's a codepen version, is it useful?
https://codepen.io/ycw/full/jOyyGGX

**Comment by optimus007** [comment]
no luck  with `powerPreference: "high-performance"`

![cpen](https://user-images.githubusercontent.com/6885294/134896046-d8bfc9b2-dfd2-4da0-ac2d-a2edf29dc468.png)

**Comment by VrTech** [comment]
@optimus007 Not sure If it is related but, can you try to use SSAO with your SSR?

**Comment by ycw** [comment]
@gonnavis try `gl_FragColor=something` in fs `main()`

https://github.com/mrdoob/three.js/blob/b1ede8160b5aefe18c7ec29f2af80f78b0ffd911/examples/jsm/shaders/SSRShader.js#L115

**Comment by gonnavis** [comment]
> try `gl_FragColor=something` in fs `main()`

@ycw Thanks!

Hello @optimus007 , does this works? https://raw.githack.com/gonnavis/three.js/SSRPassCompatibleIssue/examples/webgl_postprocessing_ssr.html

**Comment by optimus007** [comment]
@gonnavis no luck
![githack](https://user-images.githubusercontent.com/6885294/135709994-f25d2e32-e311-46a5-a31f-d7e18501c6ed.png)

**Comment by ycw** [comment]
> 
> 
> > try `gl_FragColor=something` in fs `main()`
> 
> @ycw Thanks!
> 
> Hello @optimus007 , does this works? https://raw.githack.com/gonnavis/three.js/SSRPassCompatibleIssue/examples/webgl_postprocessing_ssr.html

@gonnavis i mean ' try assigning sthm to gl_fragcolor ' before quitting from main(), i remembered that w/o explicitly set gl_fragcolor or use 'discard' is bugged in some drivers.

**Comment by gonnavis** [comment]
@optimus007 Please give another try:

Add transparent color before quitting from main():
https://raw.githack.com/gonnavis/three.js/987c1ed8d435acc1adf161f36c575b809f104fd5/examples/webgl_postprocessing_ssr.html

Add reddish color before quitting from main():
https://raw.githack.com/gonnavis/three.js/ec48daf13aeb7cd2ef2e9b812b73e7dd770fb126/examples/webgl_postprocessing_ssr.html

**Comment by optimus007** [comment]
Link 1 on the left ,link2 on the right (on the right one i can see some reflections !)
![two links](https://user-images.githubusercontent.com/6885294/135725645-eca083b3-4860-4b0f-8061-b4c06d4019ab.png)

**Comment by gonnavis** [comment]
@optimus007 How about these?

Set gl_FragColor to vec4(0.,0.,0.,0.) at the end of `main()`, if not already set:
https://raw.githack.com/gonnavis/three.js/e7c7e7b10ea19a29a5434c510cca92401d95da14/examples/webgl_postprocessing_ssr.html

Set gl_FragColor to vec4(0.,0.,0.,1.) at the end of `main()`, if not already set:
https://raw.githack.com/gonnavis/three.js/48255f9851e2d6ede2e906f3aacd2c7542910a79/examples/webgl_postprocessing_ssr.html

Set gl_FragColor to vec4(1.,0.,0.,1.) at the beginning of `main()`:
https://raw.githack.com/gonnavis/three.js/041659d55182c6c082f491489ca782197dcd1b05/examples/webgl_postprocessing_ssr.html

**Comment by optimus007** [comment]
@gonnavis 
link 1
![link1](https://user-images.githubusercontent.com/6885294/135727594-aefb54ab-fa7d-400f-a491-5e773787e117.png)

link2 
![link 2](https://user-images.githubusercontent.com/6885294/135727601-1537d4b0-44c6-4c42-b665-419f1220f91c.png)

link 3
![link 3](https://user-images.githubusercontent.com/6885294/135727607-e31aba0e-48d7-4f8b-98e7-10963274e7ce.png)

**Comment by gonnavis** [comment]
@optimus007 One more, please.

Set `red` at the beginning. And set transparent at the end, if not set.
https://raw.githack.com/gonnavis/three.js/906707894f220be557dd328fe515ab76bbb23c02/examples/webgl_postprocessing_ssr.html

**Comment by optimus007** [comment]
@gonnavis h
![gglg1ggg](https://user-images.githubusercontent.com/6885294/135728203-597d608b-f7bd-43a2-a192-2f026753d73f.png)

**Comment by gonnavis** [comment]
@optimus007 How about this?

Use variable `resultColor` & set gl_FragColor before every `return`:
https://raw.githack.com/gonnavis/three.js/da2917a07f94e291c08c74f2c75c35ac5a3d6836/examples/webgl_postprocessing_ssr.html

**Comment by optimus007** [comment]
@gonnavis 

![Uploading lllllllll.png…]()

**Comment by gonnavis** [comment]
@optimus007 One more, please.

Set red at the beginning. And set transparent at the end, if not set. Version2:
https://raw.githack.com/gonnavis/three.js/3821a5e656d91cf8ee4d86845e14f8f52ff883fa/examples/webgl_postprocessing_ssr.html

**Comment by optimus007** [comment]
@gonnavis 
![one more](https://user-images.githubusercontent.com/6885294/135729087-da7267d7-94da-4804-a44c-7bfc95df4ea1.png)
s

**Comment by Mugen87** [comment]
@optimus007 Do you still experience the issue with your laptop? 

https://threejs.org/examples/webgl_postprocessing_ssr

Maybe recent drivers for your device have fixed the issue?

**Comment by optimus007** [comment]
![dd c](https://user-images.githubusercontent.com/6885294/195980000-47575a8c-b97d-4d2f-89b6-0d8cbe301029.png)


on chrome it looks correct now!

on firefox all the examples are showing up black ???
![FF](https://user-images.githubusercontent.com/6885294/195980168-c024d253-5e8c-484d-8baf-b40ddd4e79ea.png)

**Comment by Mugen87** [comment]
Firefox works fine for me? Do you maybe have some dev flags enabled? Can you tried it with a fresh installation?

**Comment by optimus007** [comment]
I do all the dev stuff on chrome but re-installing firefox did fix the issue and ssr also looks correct ! 

thank you for catching up on this issue !

![fffix](https://user-images.githubusercontent.com/6885294/195983371-b1bdd934-eb78-4cfd-bb0d-4151f9d2d325.png)

**Comment by Danilkat** [comment]
I've also stumbled onto similiar bug. 
### Description
SSR works when rendering to screen, but has a lot of artifacts/flickering:
![image](https://github.com/user-attachments/assets/c15456af-cd81-4bd5-bd4e-4f542120fe38)

Flickering increases when i enable `distanceAttenuation`, `bouncing` and/or `infiniteThick`.
`infiniteThick` + `distanceAttenuation` results in completely black screen. All the other pairs are valid and only increasing flickering.

When rendering to framebuffer/RT (e.g. enabling blur or setting `output` to Default) screen also goes compelety black.

### My specs:
GPU: RX 6800 XT, latest drivers
CPU: Intel 13th gen KF
Chrome ver: 131.0.6778.140
Mozilla ver: 133.0.3
OS: Windows 10

### What ive tried:
- fiddling with `WebGLRenderTarget` options for `ssrRenderTarget` and `blurRenderTarget` - using different mag filters and/or buffer types.
- debugging all the shaders after SSRShader (including SSRShader). 

Problem lies within SSR fragment shader, to be precise - somewhere in the for-loop. I wasnt digging further.

### Fix
Changing ANGLE backend from `Default` to `OpenGL` or `D3D11on12` in the `chrome://flags` page fixes the issue.
![image](https://github.com/user-attachments/assets/78c4be79-3c37-451f-bfba-ea53e7a4ad52)
