### ISSUE TITLE
Altering the values of parameters of Geometries after initializing.

### ISSUE THREAD

**Issue by nishu-murmu** [mrdoob/three.js#22588]
After the values of the parameters of a Geometry is assigned, I want to alter/change its value in the tick/animate function. Want to suggest an idea to have a functionality where I can change it's value.

**Comment by Mugen87** [comment]
You have to re-create the geometry object in this case. Also don't forget to call `dispose()` on the former geometry.

Please use the [forum](https://discourse.threejs.org/) if you need more help.
