### ISSUE TITLE
Bounding box mismatch between OBJ and glTF Loaders

### ISSUE THREAD

**Issue by schwyzl** [mrdoob/three.js#22580]
I have a model exported out of Blender to .obj and .glb. The bounding box is being reported differently for each file. I would expect the bounding box to match.

The model is a static; no skinning or morphing/animation. It is not centred around the origin.

**Screenshots**
These are the bounds reported for both files: https://imgur.com/a/wTkGYq7

**Files**
These are the files:
[objAndglTF.zip](https://github.com/mrdoob/three.js/files/7226111/objAndglTF.zip)

**To Reproduce**
Load the files in an OBJLoader and glTF Loader. Print the resulting objects and compare the mesh geometry bbox (and bsphere) values.

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome
 - Three.js version: r130

**Comment by donmccurdy** [comment]
(Discussed a bit offline earlier)

If I load the same GLB in https://gltf-viewer.donmccurdy.com/ and run the following line in the JS console...

```js
content.children[0].geometry.boundingBox.min
```

... I'm seeing the same minimum as the OBJ:

```
{ x: -26.536691665649414, y: -169.27279663085938, z: -236.02914428710938 }
```

That's three.js r131 and not r130, which could be the difference ... is there anything else going on after loading the model that might have altered the geometry?

**Comment by schwyzl** [comment]
I ran that same test before submitting the report :) But I think the imgur image labels are confusing matters! 

The obj boundingBox values are:

`max: Vector3 {x: 64.6628646850586, y: 236.02914428710938, z: -92.29078674316406}`
`min: Vector3 {x: -26.536691665649414, y: 158.9622039794922, z: -169.2727813720703}`

and the glTF:

`max: Vector3 {x: 64.6628646850586, y: -92.29064178466797, z: -158.96348571777344}`
`min: Vector3 {x: -26.536691665649414, y: -169.27279663085938, z: -236.02914428710938}`

**Comment by schwyzl** [comment]
...another way to write it would be glTF bounds are:

`max: Vector3 {x: obj.max.x, y: obj.max.z, z: -obj.min.y}`
`min: Vector3 {x: obj.min.x, y: -obj.min.z, z: -obj.max.y}`

It seems like they are using different coordinate systems.

**Comment by donmccurdy** [comment]
Oh that would explain it! Hadn't noticed the Y/Z swap. glTF uses a +Y=Up convention, so Blender's glTF exporter converts +Z=Up (Blender's convention) to +Y=Up. OBJ files are not consistent with any particular convention, I guess Blender doesn't do the conversion there perhaps.

That correction when exporting glTF is usually what you will want, but I think there's also a way to turn it off in the Blender export settings too.

**Comment by schwyzl** [comment]
OK, thanks, that makes sense.

However, the models are drawn in exactly the same place. So they exist in the same world space, look exactly the same, but have different bounding boxes.

Blender OBJ exporter defaults to -Z forward and +Y Up, so I checked that the OBJ I have been referencing was exported with -Z forwards and +Y up... which it was. As a sanity check; I exported with +Z forward and the model moved position when I imported this version.

Is this (-Z forward and +Y Up) the same as the glTF correction? 

I read [somewhere](https://github.com/KhronosGroup/glTF/issues/566) that glTF is right handed, but if it was an issue with handedness it would surely be the x axis that had the discrepancy?

I guess the question is, which bounding box is correct? I thought maybe the bounding box is incorrectly written into the file (obj or gltf), so I ran a test where I print the bounding box, then compute the bounding box in Three (`node.geometry.computeBoundingBox();`) and print again. In this test neither bounding box changed, both still are reported as different, even though the models look the same. So, I am still a little confused.

This is all purely theoretical now because I think my original issue (mentioned offline) stems from something else. So I'm happy enough that the models look the same when imported... I just don't understand why the bbox would be different.

**Comment by scurest** [comment]
Both bounding boxes are correct (checked by computing the max/min of the .glb POSITION array and the .obj `v x y z` lines). The models are, in fact, different. Maybe you have a transform that brings them to the same world space? I think you probably did something when exporting, because when you export a model out of Blender as a .glb and .obj, they will both import back into Blender in the same spot. But if I import your .glb and .obj they are clearly at different spots.

> Is this (-Z forward and +Y Up) the same as the glTF correction?

Yes.

**Comment by schwyzl** [comment]
Oh, apologies, the models in that zip had their transforms frozen in Blender (I believe what happens in that operation is the transforms are applied directly to the vertices).

[heart_transformations_not_frozen.zip](https://github.com/mrdoob/three.js/files/7236576/heart_transformations_not_frozen.zip)

These models are the same model without the frozen transformations. These are the ones that appear in the same position but have differing bounding boxes. Both the same model exported from the same scene, both positioned in the same place when loaded in three, but each having a different boundingBox.

**Comment by scurest** [comment]
Yeah, the node in the GLB has a rotation. boundingBox is calculated in mesh space, unaffected by any transforms. So that's why they're different.

**Comment by schwyzl** [comment]
Ahhh... that's it. Makes sense now. Many thanks.
