### ISSUE TITLE
Safari v15 (on desktop) -> threejs bug

### ISSUE THREAD

**Issue by nicholaswagner** [mrdoob/three.js#22582]
## As of Safari 15 (Desktop) something having to do with OpenGL causes a total browser failure.
(Sorry I don't have better information, feel free to delete this and create a more helpful ticket once more info becomes available)

> A problem repeatedly occurred with "site url" [ reload webpage button ]

notes:  
- Mobile safari v15 works fine.
- Chrome / Firefox browsers appear unaffected by whatever this is.

***Live examples***

1. visit one of the following `official three js showcase websites` in safari v15 on OSX
- https://www.aquarium.ru/en
- https://billie.withyoutube.com
- https://voiceofracism.co.nz
- https://augmentedperception.github.io/deepviewvideo/

**Screenshots**
![Screen Shot 2021-09-24 at 11 22 04 AM](https://user-images.githubusercontent.com/220143/134708527-8851b443-d81e-469d-9710-a838ee706086.png)

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Safari]

**Comment by mrdoob** [comment]
Better to report this to Apple directly:
https://webkit.org/reporting-bugs/

**Comment by nicholaswagner** [comment]
@mrdoob I feel like dad just told me to go ask my mother.  ;P
Just filed the report, thanks!

**Comment by walpolea** [comment]
I found that enabling `Develop > Experimental Features > GPU Process: WebGL` in Safari 15 fixes the error. Why it's not enabled by default is a whole separate question, but I'm hoping this will get fixed by Apple soon.
![webgl-flag](https://user-images.githubusercontent.com/133423/134966512-13385218-b57b-45df-b6ba-b600722775bf.png)

**Comment by walpolea** [comment]
One more update here. With `GPU Process: WebGL` turned off in Safari 15, and updating my project's three version to `"0.132.2"` (from `"0.112.1"`) the error is fixed for me.

**Comment by 61315** [comment]
@walpolea Rollback to `r112` really helped. All the anomalies brought by `Safari on iOS 15` have disappeared. Thanks.

**Comment by skalexet** [comment]
> One more update here. With `GPU Process: WebGL` turned off in Safari 15, and updating my project's three version to `"0.132.2"` (from `"0.112.1"`) the error is fixed for me.

done :)

**Comment by nh2** [comment]
Can anybody summarise the situation?

On https://bugs.webkit.org/show_bug.cgi?id=231423,

* Some people claim that a THREE ugprade fixes it (if yes, which version and which commit?)
* other say a Safari upgrade fixes it, simultaneously stating that that is not "GA and released"
* others say it's unfixed
* others say that `xrCompatible: true` causes the issue

Meanwhile, in the latest **iOS** Safari 15.2 (as well as 15.1 and 15.0), I still see crashes that look like the one in the issue description.

**Comment by willmorgan** [comment]
@nh2 Hi Niklas, long time no speak (last time was some hack day in 2012...)

I am using "three": "0.133.1" in my SDK and this is no longer an issue.

However for various reasons I would recommend not supporting 15.0 of Safari as it seems to have been a botched release - Apple seems to have quickly put 15.1 out which solves this and other issues.

**Comment by nh2** [comment]
Hi @willmorgan, didn't expect to meet you here :D Yes, on the Treevee project :D

I have figured it out now:

I had a separate bug in a shader that apparently also managed to make Safari crash the entire tab. Have not investigated it fully yet, only rolled back that shader change.
