### ISSUE TITLE
IE11, setViewport not work

### ISSUE THREAD

**Issue by bandiandou** [mrdoob/three.js#22605]
**Describe the bug**

this.renderer.setViewport(50, -50, this.width, this.height);
why not work on IE browser?

Chrome, Firefox and edge is ok.  Only IE

***Code***

```js
this.renderer.setViewport(50, -50, this.width, this.height);
```
![image](https://user-images.githubusercontent.com/86463809/135208530-583f847d-cce5-44b4-abf0-5d48a3443f3d.png)

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - OS: [Windows]
 - Browser: [IE]
 - Three.js version: [dev, r129]

**Comment by mrdoob** [comment]
Sorry, IE11 is no longer supported.

**Comment by bandiandou** [comment]
> Sorry, IE11 is no longer supported.

But this can be painted successful, only 'setviewport' not to work

**Comment by mrdoob** [comment]
We are not going to investigate this because we no longer support IE11.
