### ISSUE TITLE
how to get intersection of bones by using raycaster

### ISSUE THREAD

**Issue by Frankling** [mrdoob/three.js#22604]
how to get intersection of bones by using raycaster

**Comment by donmccurdy** [comment]
In three.js bones do not have geometry or volume, and the Raycaster cannot intersect them. An alternative would be to attach a box or other simple geometry to each bone, at the desired size, and raycast against the parent object. If you need help getting this to work I would recommend asking on the forums (https://discourse.threejs.org/), Slack, or Discourse.
