### ISSUE TITLE
Low FPS for large videos since v131 on WebXR Oculus Quest2

### ISSUE THREAD

**Issue by aantonru** [mrdoob/three.js#22606]
I found really strange behavior at latest versions .131 and .132

Its about WebXR aseptically for Oculus and large vr-video textures.

I spend a week for double, triple and quad check and finally:
1) three.130 can play large vr videos at high fps (~90) on Oculus Quest2 with h264 codec
2) three.132 (and 131) for those videos maximum fps is about 40, av. is 30-35
3) for v131 and v132 - additionally there is glitch comes from time to time like little portions of color-sand flyes at video, and none of these at v130

That all without any use of new Layers just simple video in WebVR
*not any changes were made - only reinstall modules with other three version

Sorry for no js-fiddle to test - my code has a lots of not relevant parts and I have to finish it in time - already close to deadline while was looking where those bugs come from

**Comment by capnmidnight** [comment]
For #3, the "colored sand" is likely the GPU on the Quest overheating.

**Comment by aantonru** [comment]
> For #3, the "colored sand" is likely the GPU on the Quest overheating.

sand comes from fist frames of video - time-to-time I mean every N-frames at each start - not overheating

**Comment by mrdoob** [comment]
Closing this until a jsfiddle is provided.
