### ISSUE TITLE
Fat line example doesn't work with negative scale

### ISSUE THREAD

**Issue by Julianouyang** [mrdoob/three.js#22608]
**Describe the bug**

The official [fat line example ](https://threejs.org/examples/?q=fat#webgl_lines_fat) doesn't work if we change the line scale to include negative.

**To Reproduce**

1. Go to Three.js official examples in the repo
2. Find the source file of webgl_lines_fat.html
3. At [line 109](https://github.com/mrdoob/three.js/blob/master/examples/webgl_lines_fat.html#L109), change to any negative scale.

***Code***

```js
line.scale.set(-1, 1, 1);
```

**Expected behavior**

With a negative scale, lines are disappeared. 

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: dev

**Comment by Julianouyang** [comment]
It's trivial to set negative scales on lines but assuming there is a parent object with a negative scale, then the lines are gone.

**Comment by WestLangley** [comment]
Duplicate of #19629.

**Comment by Julianouyang** [comment]
> Duplicate of #19629.

Oops. Thanks for pointing this. I'll close it.
