### ISSUE TITLE
Line2's raycaster threshold not compatable with LineMaterial's 'worldUnits'

### ISSUE THREAD

**Issue by ariel-resonai** [mrdoob/three.js#22611]
**Describe the bug**

When using LineMaterial with worldUnits (worldUnits: true), and raycaster.params.Line2.threshold,
zooming in and out changes the threshold in which the line can be clicked. This is a result of the threshold being related to pixels and the linewidth being constant in the scene.

**Expected behavior**

Zooming in and out doesn't change the threshold in which the line can be clicked.

 - Three.js version: .132

**Comment by gkjohnson** [comment]
Yes support for perspective attenuated fat lines were added recently (see #16912) but raycasting support was not. Would you like to take a crack at a PR to add raycasting support for lines with `worldUnits = true` and maybe an example for demonstrating and testing raycasting with fat lines?
