### ISSUE TITLE
THREE.js RGBELoader: Access to XMLHttpRequest fails because hdr binary is added to the link

### ISSUE THREAD

**Issue by dewball345** [mrdoob/three.js#22614]
**Describe the bug**

I was recently trying to load an .hdr file into three.js. 

This was my code:

```js
new RGBELoader()
    .setDataType( UnsignedByteType )
    .load( royal_esplanade_1k, function ( texture ) {
    var envMap = pmremGenerator.fromEquirectangular( texture ).texture;
    this.scene.background = envMap;
    this.scene.environment = envMap;
    texture.dispose();
    pmremGenerator.dispose();
})
```
Code to import the hdr file

```js
import royal_esplanade_1k from './assets/royal_esplanade_1k.hdr'
```
I am using the Snowpack bundler, if that helps. 

I received this error:

[![error][1]][1]

  [1]: https://i.stack.imgur.com/H67KH.png

It looks to me that the hdr file binary was added to the link, but that's not what is supposed to happen.

Why is this happening, and how can I fix it?

**To Reproduce**

1. Go to https://codesandbox.io/s/lively-resonance-it4nf?file=/src/index.js

The weird thing is that it works in that example when it didn't on my computer. Same code, same asset path, everything. The only difference is that I am using Snowpack as my bundler, whereas code sandbox uses rollup. I'm not sure how to change that. 

***Code***

```js
new RGBELoader()
    .setDataType( UnsignedByteType )
    .load( royal_esplanade_1k, function ( texture ) {
    var envMap = pmremGenerator.fromEquirectangular( texture ).texture;
    this.scene.background = envMap;
    this.scene.environment = envMap;
    texture.dispose();
    pmremGenerator.dispose();
})
```

Code to import the hdr file

```js
import royal_esplanade_1k from './assets/royal_esplanade_1k.hdr'
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hyok6tvj/)
* [jsfiddle-dev](https://jsfiddle.net/c5m1kazu/)

**Expected behavior**

**Screenshots**

[![error][1]][1]

  [1]: https://i.stack.imgur.com/H67KH.png

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [^0.132.2]

**Comment by donmccurdy** [comment]
This appears to be a Snowpack configuration issue. Your usage looks correct to me (https://www.snowpack.dev/reference/supported-files#other-assets) but as you mention, the import is returning the content of the file rather than its URL. Since that's not related to three.js itself I'm not sure we can help here, but feel free to post on the forums (https://discourse.threejs.org/) and hopefully other Snowpack users can help there.
