### ISSUE TITLE
Skypack CDN down

### ISSUE THREAD

**Issue by GingerIndustries** [mrdoob/three.js#22623]
**Describe the bug**

The Skypack CDN is down. [See here](https://cdn.skypack.dev/error/build:three@v0.133.0-crothxwblMdYyEkUnmAx) Maybe a deployment failure?

I think this deserves a nomination for the Melted the Internet award

**Comment by Mugen87** [comment]
It seems a user already reported this to skypack: https://github.com/skypackjs/skypack-cdn/issues/226

**Comment by jimaek** [comment]
Consider using jsDelivr too, its built specifically for production use with multiple [failover systems](https://www.jsdelivr.com/network/infographic) https://www.jsdelivr.com/package/npm/three
There are already 21 million monthly hits
