### ISSUE TITLE
Example code updating with the resize feature?

### ISSUE THREAD

**Issue by nishu-murmu** [mrdoob/three.js#22626]
Adding the window resize code in the example code. Might help a lot of beginners.

**Comment by Mugen87** [comment]
Almost all examples should already have the following piece of code or a similar logic:

https://github.com/mrdoob/three.js/blob/b1ede8160b5aefe18c7ec29f2af80f78b0ffd911/examples/webgl_geometry_cube.html#L47-L54

**Comment by makc** [comment]
@Mugen87 maybe he means jsfiddle

**Comment by nishu-murmu** [comment]
I actually meant the example with standard cube one in the starting of the documentation (Creating a Scene).

**Comment by Mugen87** [comment]
The intention is to keep this particular example as simple as possible. It should only contain the buildings block for a minimal 3D scene.

**Comment by makc** [comment]
@Mugen87 
> as simple as possible

but then [it could be simplified by another 20% 😂](https://jsfiddle.net/3u0c9fm7/)

**Comment by Mugen87** [comment]
I think the starter example is okay as it is. Please let's focus on other topics.
