### ISSUE TITLE
Minecraft example has a minor glitch(es ?)

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#22620]
![image](https://user-images.githubusercontent.com/242577/135542135-2cf1dc16-2bd6-4a91-a2de-3f7402c20968.png)
![image](https://user-images.githubusercontent.com/242577/135542153-cb38859c-37c4-4c53-9280-7f0d93211dfd.png)

**Comment by B-AYUSHMAN-PRUSTY** [comment]
Hey i am interested to contribute you but i don't know coding but can you help me to resolve this problem

**Comment by makc** [comment]
yay @Mugen87 I am lucky again https://jsfiddle.net/fvhs246t/2/ I feel like it happens when tiles height difference is at least 2

**Comment by Mugen87** [comment]
Just for demonstrating, here is a fiddle with a much more steep terrain. There issue becomes very obvious here: https://jsfiddle.net/pqmrbh1t/
