### ISSUE TITLE
moveObject Command in the editor improvements

### ISSUE THREAD

**Issue by JSmithOner** [mrdoob/three.js#22632]
I've been looking at the THREE.js editor source code also I'm not sure to understand how the moveObject command really works. seems to me like a lot of array manipulations and looping for such a usual action.

references: [moveObject](https://github.com/mrdoob/three.js/blob/b1ede8160b5aefe18c7ec29f2af80f78b0ffd911/editor/js/Editor.js#L187), [moveObjectCommand](https://github.com/mrdoob/three.js/blob/master/editor/js/commands/MoveObjectCommand.js)

I'm thinking of making a pull request but I'm afraid to break something

Wouldn't it be easier to save x,y,z positions and undo/redo as wanted

thanks in advance for your answers

**Comment by Mugen87** [comment]
> Wouldn't it be easier to save x,y,z positions and undo/redo as wanted

The command is used to move objects in the 3D hierarchy (e.g. adding an existing object as a child to another one).

**Comment by JSmithOner** [comment]
@Mugen87  Gotcha my bad! Thnak you for your time
