### ISSUE TITLE
CSS2DRenderer / CSS3DRenderer: allow usage of existing DOM element

### ISSUE THREAD

**Issue by pimdewit** [mrdoob/three.js#22634]
**Is your feature request related to a problem? Please describe.**

When working with the `CSS2DRenderer` I often find myself rendering static DOM which I tie to `CSS2DObject` instances.
The current `CSS2DRenderer` setup requires moving DOM around, or alternatively creating DOM dynamically with javascript.

**Describe the solution you'd like**

I would like to pass an optional element to the `CSS2DRenderer` constructor which will act as the `CSS2DRenderer.domElement`.
**Describe alternatives you've considered**

N/A

**Additional context**

This allows for better interoperability with a plethora of javascript frameworks, and increases performance.

**Comment by Mugen87** [comment]
I would only agree to change `CSS2DRenderer` if `CSS3DRenderer` is changed, too.

Besides, unlike in your PR we should add a generic `parameters` object like in `WebGLRenderer`. Meaning:
```js
const renderer = new CSS2DRenderer( { element: myElement } );
```

**Comment by pimdewit** [comment]
Agreed, including `CSS3DRenderer` would've been my next step 👍
