### ISSUE TITLE
Orbitcontrols animate to updated target

### ISSUE THREAD

**Issue by joshon** [mrdoob/three.js#22637]
I would like to be able to set a new target, and rather than the camera jumping directly to it, have it lerp to the new position.

**Comment by Mugen87** [comment]
Sorry, but this needs to be solved on application level. Please use the [forum](https://discourse.threejs.org/) for more help.

BTW: There are some existing topics about combining `OrbitControls` with animations, e.g.

https://discourse.threejs.org/t/tweening-with-orbitcontrols/17356
https://discourse.threejs.org/t/need-help-with-gsap-camera-and-orbitcontrols-animations/17420

**Comment by joshon** [comment]
Thank you!
