### ISSUE TITLE
about shadowmap pcss

### ISSUE THREAD

**Issue by lo-th** [mrdoob/three.js#22638]
The shader from [webgl_shadowmap_pcss](https://threejs.org/examples/webgl_shadowmap_pcss) throws the following warning: 

> warning X3595: gradient instruction used in a loop with varying iteration; partial derivatives may have undefined value
 
a easy fix is to remove line 98 of  webgl_shadowmap_pcss.html
if( avgBlockerDepth == -1.0 ) return 1.0;

and remplace line 71
if( numBlockers == 0 ) return -1.0;
by 
if( numBlockers == 0 ) return 1.0;

Also PCF_Filter function can be done in same loop
```
float PCF_Filter(sampler2D shadowMap, vec2 uv, float zReceiver, float filterRadius ) {
    float sum = 0.0;
    float top = 0.0;
    float low = 0.0;
    for( int i = 0; i < PCF_NUM_SAMPLES; i ++ ) {
        top = unpackRGBAToDepth( texture2D( shadowMap, uv + poissonDisk[ i ] * filterRadius ) );
        low = unpackRGBAToDepth( texture2D( shadowMap, uv + -poissonDisk[ i ].yx * filterRadius ) );
        if( zReceiver <= top ) sum += 1.0;
        if( zReceiver <= low ) sum += 1.0;
     }
    return sum / ( 2.0 * float( PCF_NUM_SAMPLES ) );
}
```

that's all for me :)

**Comment by Mugen87** [comment]
Um, when I remember correctly it was planned to remove such DirectX warnings from the log. Are you on latest Chrome/Windows?

**Comment by Mugen87** [comment]
@kenrussell Should we fix this issue in the engine? Or will Chrome stop at some point to log the waning?

**Comment by lo-th** [comment]
that a good question :) in fact this throw warning randomly  
so i think it solve issue in engine 

yes i'm on latest chrome / win 11
