### ISSUE TITLE
OrbitControls can send nested start and end events

### ISSUE THREAD

**Issue by nkallen** [mrdoob/three.js#22658]
**Describe the bug**

OrbitControls is an EventDispatcher. It sends 'start', 'change', and 'end' events. If you mouse wheel while rotating it will send nested 'start' and 'end' events. This is (probably) incorrect, because clients relying on this code to e.g., enable/disable functionality in their app will incorrectly reenable/re-disable things.

**To Reproduce**

1. Add an event listener for 'start' and 'end' events
2. Rotate, holding down the mouse button (default: left)
3. While holding down the button use the mouse wheel

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hyok6tvj/)

**Expected behavior**

It should send change events during mouse wheel, not start stop

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).
<img width="563" alt="Screenshot 2021-10-08 at 12 48 15" src="https://user-images.githubusercontent.com/699/136543989-72e9fa53-6002-4f4b-99b2-cd9d8f17819b.png">

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r???]

**Comment by Mugen87** [comment]
It seems you did not provide a live example as shown in the screenshot. Let's use this one: https://jsfiddle.net/b610qohy/

**Comment by Mugen87** [comment]
I guess a note in the migration guide is sufficient.
