### ISSUE TITLE
Will the mapped object be pulled up when Reflector uses its geometry?

### ISSUE THREAD

**Issue by Imagine-Tom** [mrdoob/three.js#22664]
When I use the geometry I create, I cause the map to shift and pull up, and only map half?

I don't know what the cause of the problem is. （BufferGeometry)

There is no such problem when I manually create a CircleGeometry parameter to Reflector.

Does it depend on the matrix?

When camera is mapping, the matrix is transformed, right?
***Code***

```js
let newGeo = new THREE.CircleGeometry(140, 140);
let geo = [];
this.engine.nodeManager.meshes.map((i) => {
            if (i.mesh.name === "di") {
                geo.push(i.geometry);
            }
        });
        let geo3 = geo[0].geometry.clone();

        this.groundMirror = new Reflector(geo3, {
            clipBias: 0.003,
            textureWidth: window.innerWidth * window.devicePixelRatio,
            textureHeight: window.innerHeight * window.devicePixelRatio,
            color: 0x777777,
        });
```

help me

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).
![image](https://user-images.githubusercontent.com/37398245/136689975-8f8f6d38-f5e7-4c6e-aa69-f7893cbe8e18.png)

![image](https://user-images.githubusercontent.com/37398245/136690090-a9bf5c9c-a080-4f19-be04-e4a5c361e611.png)

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [0.133]

**Comment by Imagine-Tom** [comment]
Picture 1 is a floor that I imported myself
Picture 2 is an arc that I created directly with THREE

**Comment by Mugen87** [comment]
Please use the forum for help requests: https://discourse.threejs.org/
