### ISSUE TITLE
Adding 'image-tracking' feature support for the ARButton module 

### ISSUE THREAD

**Issue by ShirinStar** [mrdoob/three.js#22682]
Hi, I was wondering if there is a way/intention to add support for the 'image-tracking 'webXR API feature? 🙌🏾

**Comment by ShirinStar** [comment]
Hi @Mugen87! Thanks so much for this! Huge, huge help!!
It took me a while to understand it doesn't work on ios, so the 'missing feature' error I kept receiving was because I am developing on a mac. I then added https://github.com/liriliri/eruda as a mobile debugger for Android, and it works! 

Here is a full code sample: 
https://github.com/ShirinStar/webAR_experiments/tree/main/16-webxr-image_tracking

(and so sorry for the late response!! work got in the way:) )

**Comment by fabian-muff** [comment]
Hi @Mugen87 and @ShirinStar 
This works quite well on android smartphones. However, it does not work yet on HoloLens, since it is an experimental feature and the edge does not yet support the image-tracking, nor the camera-access features. 
Has one of you an idea if this is going to be an official part of the webxr api?
Or will there be a specific three.js functionality/module to support image-tracking?

**Comment by Mugen87** [comment]
> Has one of you an idea if this is going to be an official part of the webxr api?

Not sure but it seems the [spec](https://immersive-web.github.io/marker-tracking/) is still in draft mode and thus marked as unstable. Your probably want to ask your question at the respective [GitHub repo](https://github.com/immersive-web/marker-tracking).

**Comment by wyliefoxxx** [comment]
It does seem to work great on Android, but sadly, for now at least, only when the experimental flag is enabled:

chrome://flags/#webxr-incubations

I figure this is a good thing to mention in this thread. Please, anyone, correct me if I'm wrong.

I feel like we all might need to figure out the best way to nudge it off the experimental flag list as a community - it's a painfully powerful feature to be in a so-close-yet-so-far state.

**Comment by orioncho45** [comment]
> Hi @Mugen87! Thanks so much for this! Huge, huge help!! It took me a while to understand it doesn't work on ios, so the 'missing feature' error I kept receiving was because I am developing on a mac. I then added https://github.com/liriliri/eruda as a mobile debugger for Android, and it works!
> 
> Here is a full code sample: https://github.com/ShirinStar/webAR_experiments/tree/main/16-webxr-image_tracking
> 
> (and so sorry for the late response!! work got in the way:) )

Hi @ShirinStar Can you please tell us the device that this image-tracking project is working on. Because I have been in trouble to find perfect device on where it works.

**Comment by fabian-muff** [comment]
This seems to be a privacy problem on HMDs. 
Meta Quest does not and Apple Vision Pro will not allow access to the camera stream for custom computer vision algorithms. 
In my opinion this is a crucial feature to allow for XR applications.
So far however no one dares to do the first step.

**Comment by marcusdiy** [comment]
> This seems to be a privacy problem on HMDs. Meta Quest does not and Apple Vision Pro will not allow access to the camera stream for custom computer vision algorithms. In my opinion this is a crucial feature to allow for XR applications. So far however no one dares to do the first step.

There is camera api support today on Quest 3 at least for sure
