### ISSUE TITLE
iOS 14.8: Only sound with VideoTexture when using HLS/m3u8 (works with Babylon.js)

### ISSUE THREAD

**Issue by funwithtriangles** [mrdoob/three.js#22693]
**Describe the bug**

`VideoTexture` displays black with .m3u8 stream on iOS 14.8. Sound is working. Same device with similar webGL example in Babylon isn't broken.

**To Reproduce**

1. Go to https://tis0u.csb.app/
2. Click to start playing video
3. Audio plays, but no image appears on cube

A similar example in Babylon can be found here and works on the same device:
https://www.babylonjs-playground.com/#9FSDC7#49

***Code***

https://codesandbox.io/s/cranky-mountain-tis0u?file=/src/index.js

***Live example***

https://tis0u.csb.app/

**Expected behavior**

Both audio and video should play on the cube

**Fails on:**
 - Device: iPhone 8
 - OS: 14.8
 - Browser: Safari
 - Three.js version: r133

**Tested and works on:**
- OSX Chrome
- OSX Safari
- Android Chrome

**Comment by TheAwesome98-Real** [comment]
> > I've got an iPhone 6S running iOS 14.0.1, and it plays audio, and no video. My desktop plays both fine.
> 
> Can you test this example, also? https://www.babylonjs-playground.com/#9FSDC7#49

Same result as the last one.

**Comment by mrdoob** [comment]
So the Babylon version doesn't work either?

**Comment by TheAwesome98-Real** [comment]
> So the Babylon version doesn't work either?

yeah, which is weird since OP said that one worked on their device

**Comment by mrdoob** [comment]
Closing for now...

**Comment by mzvast** [comment]
Watch on this, iOS 15 still render black.
