### ISSUE TITLE
Automatically material.transparent = true when material.opacity<1

### ISSUE THREAD

**Issue by peterqliu** [mrdoob/three.js#22697]
**Is your feature request related to a problem? Please describe.**

It would be nice to have Material's `transparent` flag track its `opacity` automatically, instead of having to keep both in sync.

**Describe the solution you'd like**

Instead of a simple [material property](https://github.com/mrdoob/three.js/blob/master/src/materials/Material.js#L26), instantiate `opacity` in the Material class with a setter that updates `transparent` internally.

**Comment by peterqliu** [comment]
This is potentially a breaking change for people who update 'opacity' as a hidden state store while keeping `transparent` to false, without actually rendering the transparency. This is probably an antipattern though.

**Comment by Mugen87** [comment]
There are actual rendering use cases where `opacity` is set to `< 1` without setting `transparent` to `true`.

E.g. by setting the `alpha` property of `WebGLRenderer` to `true` for special compositing setups. In this way, the final result can become translucent although the WebGL scene itself is considered as opaque.

https://jsfiddle.net/dwhzub5q/

Always setting `transparent` to `true` when `opacity` is `< 1` could break such scenes (depending on how objects are sorted/overlap).
