### ISSUE TITLE
Additional animation blending mode support

### ISSUE THREAD

**Issue by Kairarara** [mrdoob/three.js#22713]
**Is your feature request related to a problem? Please describe.**

I wanted to play a series of animations targeting the same object and i could not help but notice that three.js only supports two types of blending mode, NormalAnimationBlendMode and AdditiveAnimationBlendMode
I think it would be pretty useful to implement other kinds of blending modes such as Replace, Subtract and Multiply (the ones present in blender)

**Describe the solution you'd like**

A good solution would be to add new methods to change a clip blend mode to AnimationUtils, similar to makeClipAdditive, as well as eventually add native loader support where possible

**Comment by Mugen87** [comment]
Additive animation was added since it is a common technique in game engines like Unity or Unreal. Since other types of blending modes are not supported, I think it's out of scope to add replace, subtract or multiply to `three.js`.

**Comment by donmccurdy** [comment]
I'm also not sure which formats (if any?) support these modes. We don't have any loaders that support additive blending today.
