### ISSUE TITLE
parasolid exporter

### ISSUE THREAD

**Issue by foobarbecue** [mrdoob/three.js#22723]
FYI I'm working on a parasolid exporter (x_t to begin with). Just posting an issue to avoid duplicating effort or in case anyone wants to discuss / collaborate. I expect to have a PR ready in a few weeks.

**Comment by huangdade** [comment]
Do you want to import x_t files as mesh, or export mesh to x_t files?

**Comment by foobarbecue** [comment]
@Mugen87 you're correct on all counts. Parasolid is CAD, x_t is the text version of it, and it could be considered an alternative to STEP.

@huangdade I want to export threejs mesh to x_t.

The challenge is that Parasolid describes a full topology, with halfedges and regions and loops and everything, so the first step is to construct a topology from the geometry. For this I was hoping to get a headstart by using https://github.com/stemkoski/stemkoski.github.com/blob/master/Three.js/js/topology.js

**Comment by Mugen87** [comment]
Feel free to file a new (external) example similar to [webgl_raycaster_bvh](https://threejs.org/examples/webgl_raycaster_bvh.html) or [webgl_loader_ifc](https://threejs.org/examples/webgl_loader_ifc) when your exporter is ready. The idea would be to maintain the exporter itself in a separate repository and then just include the library ideally from a CDN (e.g. `unpkg`).

**Comment by foobarbecue** [comment]
Ah, sorry for trailing off on this one and thanks for closing. I wasn't making quick enough progress on it and ended up using an 3d file conversion web API. So I probably won't get around to it.
