### ISSUE TITLE
Object3D.attach: Rotated child inside non-uniformly scaled parent causes issues

### ISSUE THREAD

**Issue by funwithtriangles** [mrdoob/three.js#22769]
**Describe the bug**

In certain circumstances, when using `Object3D.attach`, there is a visible difference in the child object before and after the method has been called. From what I can tell, this is an issue when:

- The parent object has been scaled in a non-uniform way (e.g. only on the X axis)
- The child object has been rotated

**To Reproduce**

1. Go to https://codesandbox.io/s/vibrant-brahmagupta-i0nlv?file=/src/index.js:0-956
2. Click on the page to attach the cube to scene (starts in a group)
3. The box changes appearance

***Code / Example***
https://codesandbox.io/s/vibrant-brahmagupta-i0nlv?file=/src/index.js:0-956

**Expected behavior**

The box shouldn't have any visible differences after being attached to the scene

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: r134

**Comment by Mugen87** [comment]
The engine does not fully support non-uniform scale. At least not this particular use case, see https://github.com/mrdoob/three.js/issues/15079#issuecomment-431232639.

This limitation is known and noted in the [Matrix4](https://threejs.org/docs/index.html?q=matrix#api/en/math/Matrix4.decompose) doc page.

**Comment by WestLangley** [comment]
@funwithtriangles Attaching a child to a non-uniformly-scaled parent should work if you set `matrixAutoUpdate` to `false` for the child.

```js
cube.updateMatrix();
cube.matrixAutoUpdate = false;
```

**Comment by funwithtriangles** [comment]
> @funwithtriangles Attaching a child to a non-uniformly-scaled parent should work if you set `matrixAutoUpdate` to `false` for the child.
> 
> ```js
> cube.updateMatrix();
> cube.matrixAutoUpdate = false;
> ```

Thanks! Unfortunately this doesn't work in my case, where the child is moving from a non-uniformly scaled parent to a uniformly scaled parent.

**Comment by WestLangley** [comment]
>Unfortunately this doesn't work in my case

@funwithtriangles I believe my suggestion should always work regardless of the parent's scale settings.

**Comment by funwithtriangles** [comment]
Ah yes, I got it working now, thanks! Updated example:
https://codesandbox.io/s/pensive-mestorf-3te0z
