### ISSUE TITLE
Gamma encoding makes inconsistent between background color and material color

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#22764]
**Describe the bug**

If we enable output encoding as Gamma, MeshBasicMaterial and Background color is not same definition

**To Reproduce**

1. Create renderer with gamma encoding output
2. Set background color as 0xeeeeee
3. Create a mesh with MeshBasicMaterial and color as 0xeeeeee

***Code***
link below

***Live example***
https://codepen.io/karoshi/pen/QWMqKvp

**Expected behavior**

Background color and MeshBasicMaterial should get same color with same input color

**Screenshots**

![screenshot-codepen io-2021 10 31-14_56_28](https://user-images.githubusercontent.com/6780177/139573677-a48596a6-2737-4d1e-81c9-2e4aa06041fa.png)

**Platform:**

 - Device: [Desktop,]
 - OS: [Window]
 - Browser: [Chrome]
 - Three.js version: [128]

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/20819#issuecomment-739066689
