### ISSUE TITLE
Documentation Discrepancy - WebGLShader

### ISSUE THREAD

**Issue by Dannie226** [mrdoob/three.js#22773]
**Describe the bug**

The discrepancy is in the documentation, but I didn't know how to put it as a documentation issue, so any help with that would be appreciated in the future

**To Reproduce**

1. Go to the THREE.js documentation page
2. Click on 'WebGLShader'
3. You will see in the code example that you have 'new THREE.WebGLShader(...),' but below that, you said as the shader is a function, don't use new before it.

**Expected behavior**

I expected to either not see new before THREE.WebGLShader, or there to not be the note sentence at the bottom

**Screenshots**

![Screenshot 2021-11-02 6 11 13 AM](https://user-images.githubusercontent.com/77417944/139827879-23cdcedb-ace0-4493-ad97-cc5830bfab40.png)

**Platform:**

 - Error in the HTML code

**Comment by Mugen87** [comment]
I suggest to delete the entire `WebGLShader` page. The documentation should focus on the public part of the API and not on internal details.

**Comment by Mugen87** [comment]
I would also remove the page for `WebGLState` and `WebGLProgram`.

**Comment by Dannie226** [comment]
To be fair, the program page is kind of useful when writing with a THREE.ShaderMaterial, because I have not memorized the names of all the uniforms yet, so I can go there for reference and get all the names I need.

**Comment by Mugen87** [comment]
Agreed. In context of `ShaderMaterial` the page is useful. Although I think it would be better to move the relevant part the `WebGLProgram` page to the `ShaderMaterial` page instead.
