### ISSUE TITLE
Line2 Raycasting with Orthographic camera

### ISSUE THREAD

**Issue by nkallen** [mrdoob/three.js#22782]
Line2 raycasting with an orthographic camera ignores zoom and the size of the clipping volume. The computed bounding box, in particular, can be too small for the line width and the Raycaster.params. The is very noticeable when the line segment is a an axis aligned straight line (e.g., a line segment from (0,0,0) to (1,0,0)), and so the bounding box is very "precise". 

The bounding box check adds a margin-of-error that includes the screen space max width of the line and the Raycaster.params.

https://github.com/mrdoob/three.js/blob/00a692864f541a3ec194d266e220efd597eb28fa/examples/jsm/lines/LineSegments2.js#L140-L146

**Describe the solution you'd like**

I would like the switch on the camera type and factor in zoom/left/right/top/bottom in the case of orthographic camera.

```js
        let cameraScale = 1;
        if ( camera.isPerspectiveCamera ) {
            // get the w component to scale the world space line width
            _clipToWorldVector.set( 0, 0, - distanceToBox, 1.0 ).applyMatrix4( camera.projectionMatrix );
            _clipToWorldVector.multiplyScalar( 1.0 / _clipToWorldVector.w );
            _clipToWorldVector.applyMatrix4( camera.projectionMatrixInverse );
            cameraScale = 1 / _clipToWorldVector.w;
        } else if ( camera.isOrthographicCamera ) {
            // combine the zoom and clipping volume size to scale the world space line width
            _clipToWorldVector.set( 1, 1, - distanceToBox, 1.0 ).applyMatrix4( camera.projectionMatrix );
            cameraScale = 1 / Math.max(_clipToWorldVector.x, _clipToWorldVector.y);
        }

        // increase the sphere bounds by the worst case line screen space width
	const boxMargin = Math.abs( ssMaxWidth * cameraScale ) * 0.5;
```
**Describe alternatives you've considered**

**Additional context**

Here is an example of me trying to "mouseover" an axis aligned edge with the NEW code. Raycaster.params.line2 = 15 (screen space px)

<img width="458" alt="Screenshot 2021-11-04 at 10 48 54" src="https://user-images.githubusercontent.com/699/140292963-208f4fab-d191-4425-9ebe-ea4e3456bade.png">

As a side note, the same problem applies to points.

**Comment by nkallen** [comment]
Hi,

I just wanted to give more context. The following GIFs are made with the latest version of three.js.

This first gif shows raycasting with orthographic camera. One box is axis aligned and the other is at an angle. You can see that the raycasting margin for the axis aligned box is significantly smaller than for the angled box.

![ortho-camera](https://user-images.githubusercontent.com/699/140498054-39964b93-4cba-4d41-8ae4-a9d233b43f55.gif)

This second gif shows a perspective camera. You can see that the raycasting margin is effectively identical for both boxes.

![perspective-camera](https://user-images.githubusercontent.com/699/140498241-07936561-f01c-4512-894a-39e39a1ed2ce.gif)

The difference is that the raycasting bounding box test for an axis aligned Line2 generates a bounding box that's basically identical to the line, since the bounding box is also axis aligned. Whereas for a diagonal line, the bounding box is much much bigger than the Line2.

But the bounding box "margin" code for an orthographic camera is "wrong", since dividing by the homogeneous coordinate .w does nothing to factor in zoom and the ortho "frustum". 

I'll try to write a jsfiddle soon.

**Comment by nkallen** [comment]
OK -- please check out this jsfiddle:

https://jsfiddle.net/a5hdpL2t/37/

Note in particular:

    raycaster.params.Line2 = { threshold: 50 };

Only one of the two lines respects this threshold

**Comment by gkjohnson** [comment]
@mrdoob I think this can be closed, now!
