### ISSUE TITLE
Ability to select alpha channel of Diffuse or Emissive for transparency

### ISSUE THREAD

**Issue by optimus007** [mrdoob/three.js#22787]
**Is your feature request related to a problem? Please describe.**

I would like to use a emission surface with transparency ,like illustrated in this blender node setup. (and also export it as gltf)
![transEmission](https://user-images.githubusercontent.com/6885294/140508757-4ab8cf5c-996a-4d30-96dc-12c9fea7e78a.png)

So the image is png and color part goes to emissiveMap and alpha goes to alphaBlend.

**Describe the solution you'd like**
Have the ability to select which texture's alpha channel is used for transparency

- Maybe use alphaMap channel to determine which texture is to be used for transparency 
- that way if diffuse texture is used in alphaMap use that, if emmisiveMap is in alpha channel use that, or if a unique texture is in alphaMap channel then use black and white &  export another texture

**Comment by WestLangley** [comment]
>...and also export it as glTF.

The alpha channel of an emissive texture is ignored according to the glTF spec, so what you are requesting would not be glTF-compliant.

Regarding three.js, maybe you can achieve what you want by using `.onBeforeComplie()`.

**Comment by RemusMar** [comment]
> So the image is png and color part goes to emissiveMap and alpha goes to alphaBlend.
> Describe the solution you'd like
> Have the ability to select which texture's alpha channel is used for transparency

The PNG container does not contain alpha channel, only alpha transparency.
Using the same image with transparency as Diffuse, Emissive & Alpha channels is another story.
As @WestLangley already suggested, I would go on the NodeMaterial route for that.
