### ISSUE TITLE
Support 16 bit (u)int textures 

### ISSUE THREAD

**Issue by NicolasRannou** [mrdoob/three.js#22780]
Hi,

Are the 16 bit (u)int textures supported? It is part of the WebGL2 standard but looking at the [code](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLTextures.js#L135) this seems ignored. Is it a right assumption or I am missing something?

Is there a recommended way to work around that?

```
// create a 3d texture from an array buffer
   const image = new DataTexture3D(
      new Uint16Array(arrayBuffer),
     Columns,
     Rows,
      NumberOfFrames
    );
    
  // set the type information
  // single channel
  image.format = RedIntegerFormat;
  // 16 bit unsigned integer
  image.type = UnsignedShortType;

  // force it has no effect
  image.internalFormat = 'R16UI';
  ```
  
  and the fragment shader
  ```
precision highp float;
precision mediump usampler3D;

varying vec3 vPos;
varying vec2 vUv;

uniform vec3 uDataDimensions;
uniform usampler3D uImage;
uniform mat4 uWorldToData;

void main(void) {
  vec4 dataCoordinates = uWorldToData * vec4(vPos, 1.);

  vec3 norm = dataCoordinates.xyz / uDataDimensions;
  uvec4 dataValue = texture( uImage, dataCoordinates.xyz);

  // Probably needs normalization
  gl_FragColor = vec4(dataValue);
  gl_FragColor.a = 1.;
}`;
  ```
  
  And we pass the image texture uniform as:
  ```
    const uniforms = {
    uImage: { value: image },
    ...
  };
  ```
  
  At compile time, the shader returns:
<img width="592" alt="Screenshot 2021-11-03 at 09 31 07" src="https://user-images.githubusercontent.com/214063/140029289-d9cd1be5-b7b0-4df4-bfda-e8a0503afb1b.png">

**Comment by Mugen87** [comment]
Please let you help at the [forum](https://discourse.threejs.org/) first. This use case should be supported.

**Comment by Mugen87** [comment]
When you post at the forum, please share a live example that demonstrates the issue.

**Comment by NicolasRannou** [comment]
OK will do! I posted here first because I thought it was more of a bug / feature request after looking at the source code!

Thanks

**Comment by passvvord** [comment]
I found a solution which can be useful if you need to use Uint16 graystyle data 
The solution is using THREE.RGFormat (Red 8 bit, Green 8 bit) to store your texture, and after that you can use sheder to get 16 bit graystyle color value

**in JS you can easyly create another view of your buffer and after it create THREE.RGFormat texture**
![image](https://user-images.githubusercontent.com/60948866/223219265-46265262-b695-4301-b883-f89f6499c3b7.png)

**After splitind Uint16 into 2 Uint8 values you can get your Uint 16 value by next formula**
![image](https://user-images.githubusercontent.com/60948866/223219719-b03e39fb-041f-4558-99a9-bee957b7506f.png)
**example with getting Uint8 by 2 Uint4** 
![image](https://user-images.githubusercontent.com/60948866/223220121-2de6c932-db84-4ced-932b-de33b3d8c4c6.png)

**But for shader formula must be a little changed**
![image](https://user-images.githubusercontent.com/60948866/223221011-5ffe53a4-9789-45f3-b68a-5a92791c41a8.png)

**in code tis formula will look like:**
```GLSL
float greystyle = (texture.r+texture.g*256.0)/257.0;
```
**so in THREE js you can create material and use it on object you need**
```javascript
const shaderMaterial = new THREE.ShaderMaterial({
	uniforms: {
		u_image: {
			type: 't', 
			value: getDefaultTexture(16,16)
		}
	},
	vertexShader: `
varying vec2 vUV;

void main() {
	vUV = uv;
	gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}`,
	fragmentShader: `
uniform sampler2D u_image;
varying vec2 vUV;

void main() {
	vec4 texture = texture2D(u_image,vUV);
	float greystyle = (texture.r+texture.g*256.0)/257.0;
	gl_FragColor = vec4(greystyle, greystyle, greystyle, 1.0);
	
}` 
});
```
**also you can change texture**
```javascript
shaderMaterial.uniforms.u_image.value.dispose()
shaderMaterial.uniforms.u_image.value = getDefaultTexture(30,30)
```
(default texture func)
```javascript
function getDefaultTexture(w=10,h=10) {
	const tempdist = ((h-1)**2 + (w-1)**2)**0.5
	const uint16max = 2**16-1
	const temp = new Uint16Array(h*w)

	for (let hi = 0; hi < h; hi++) {
		for (let wi = 0; wi < w; wi++) {
			const pos = hi*w+wi
			temp[pos] = Math.sqrt(wi**2 + hi**2)/tempdist*uint16max	
		}
	}

	const defaultTexture = new THREE.DataTexture(
		new Uint8Array(temp.buffer),
		w,
		h,
		THREE.RGFormat
	)
	defaultTexture.needsUpdate = true;
	return defaultTexture
}
```
**for example getDefaultTexture(32,32) with shader will look like:**
![image](https://user-images.githubusercontent.com/60948866/223227778-8dcff33f-2b58-43af-84e3-aa8dee87e37b.png)

**and without shader**
![image](https://user-images.githubusercontent.com/60948866/223227926-3c979a01-5e65-43db-829c-d8959a35d739.png)

**getDefaultTexture(500,1)**
![image](https://user-images.githubusercontent.com/60948866/223227266-34c28213-48ae-4625-84d7-4731a21edc91.png)

**and without shader**
![image](https://user-images.githubusercontent.com/60948866/223227195-7462fbdb-ecfa-4c78-9659-010572a6efd2.png)

and this method must also work for 3d textures
