### ISSUE TITLE
generateUUID() is slow after the introduction of crypto.randomUUID()

### ISSUE THREAD

**Issue by larsmoa** [mrdoob/three.js#22803]
**Describe the bug**

After the introduction of use of `crypto.randomUUID()` in `MathUtils.generateUUID()` performance has dropped drastically.

**To Reproduce**

After v133, we're seing `generateUUID()` being a significant factor (20-40%) of the time setting up ThreeJS Meshes and objects during parsing. Turns out the culprit is `crypto.randomUUID()` which is very slow.

Please see comparison of performance in https://jsbench.me/8ekvsektki/1 (`cryoto.randomUUID()`-based solution is 97% slower than the old solution).

My suggestion is to roll back #22556 since there is no real need for crypto-quality UUIDs in ThreeJS. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6741854/140980482-800547af-1838-4721-a051-973c385b0259.png)

**Platform:**

 - Device: Desktop
 - OS: MacOS (Intel)
 - Browser: Chrome
 - Three.js version: r133

**Comment by Mugen87** [comment]
It was the intention to replace the custom UUID generation with something build-in. Since `crypto.randomUUID()` is actually that much slower, it's probably better to revert. Maybe we can give it a new go in the feature when `crypto.randomUUID()` is more optimized.

**Comment by mrdoob** [comment]
Sounds good to me. I should have tested that it was actually faster.

**Comment by mrdoob** [comment]
The code has now been reverted.
