### ISSUE TITLE
Problems with ArcballControls

### ISSUE THREAD

**Issue by drcmda** [mrdoob/three.js#22809]
#### scale

```error
TypeError
Cannot assign to read only property 'scale' of object '#<ArcballControls>'
new ArcballControls
/src/ArcballControls.js:66:48
  63 |  * @param {Scene} scene The scene to be rendered
  64 |  */
  65 | class ArcballControls extends Object3D {
> 66 |   constructor(camera, domElement, scene = null) {
```

It extends Object3D which has made `scale` a configured prop that can't be replaced, but then it defines a `scale` function. It should be renamed `setScale` as it is in conflict with the base class (O3D).

#### target

current arcball can't be controlled generically from outside like other controls. this is because exposing `this.target` was not enough. it has a `setTarget` function that sets gizmos, and for some reason the update function takes the gizmo position into account, not the target.

#### changeset

i have made the [necessary changes in three-stdlib](https://github.com/pmndrs/three-stdlib/commit/c7cc48c1f7436618259314e0f7cd2d479036da24?diff=unified) but for the sake of coherency maybe it would be good to bring them over.

```diff
@@ -189,6 +189,8 @@ class ArcballControls extends Object3D {
 
     //trackball parameters
     this.target = new Vector3(0, 0, 0)
+    this._currentTarget = new Vector3(0, 0, 0)
+
     this._tbRadius = 1
 
-  /**
-   * Set the trackball's center point
-   * @param {Number} x X coordinate
-   * @param {Number} y Y coordinate
-   * @param {Number} z Z coordinate
-   */
-  setTarget = (x, y, z) => {
-    this.target.set(x, y, z)
-    this._gizmos.position.set(x, y, z) //for correct radius calculation
-    this._tbRadius = this.calculateTbRadius(this.camera)
-
-    this.makeGizmos(this.target, this._tbRadius)
-    this.camera.lookAt(this.target)
-  }
-
   /**
    * Set values in transformation object
    * @param {Matrix4} camera Transformation to be applied to the camera
@@ -2497,12 +2484,23 @@ class ArcballControls extends Object3D {
   update = () => {
     const EPS = 0.000001
 
+    if (!this.target.equals(this._currentTarget)) {
+      this._gizmos.position.set(this.target.x, this.target.y, this.target.z) //for correct radius calculation
+      this._tbRadius = this.calculateTbRadius(this.camera)
+      this.makeGizmos(this.target, this._tbRadius)
+      this._currentTarget.copy(this.target)
+    }
+
```

**Comment by Mugen87** [comment]
> It extends Object3D which has made scale a configured prop that can't be replaced, but then it defines a scale function. It should be renamed setScale as it is in conflict with the base class (O3D).

This will be fixed with `r134`, see #22737.

**Comment by drcmda** [comment]
nice! i will rename to applyScale then. would you bring over target as well? that's the critical part - without it you can't steer this control (viewcube gizmo, focus on point etc).

**Comment by Mugen87** [comment]
> imo setTarget should be deleted. changing control.target and calling update will then re-orient gizmos and set the arc radius.

@danielefornari Does this look good to you?

**Comment by drcmda** [comment]
fixed the diff up there since applyScale is already fixed. makes it easier to see the proposed change. thanks!

**Comment by danielefornari** [comment]
Sure, it's fine with me.

**Comment by Mugen87** [comment]
@drcmda Do you want to add the patch to `ArcballControls`?

**Comment by drcmda** [comment]
no problem. will do it ... just working on some other arcball issues i'm profiling right now, but will come back to this.

**Comment by Mugen87** [comment]
In the meanwhile, I've fixed the target issue with a PR so it's definitely part of `r136`.

**Comment by drcmda** [comment]
excuse the long wait, i noticed some much deeper issues that kept us from progressing. it turns out setting the target is not enough because it uses internal variables and gizmo positions. atm we have given up, whatever i tried i couldn't fix it.

**Comment by Mugen87** [comment]
Feel free to create another PR with your fixes. However, removing `setTarget()` makes the controls more similar to the others so we wanted to do this anway.
