### ISSUE TITLE
GLTFLoader onError handler receiving ProgressEvent - not error as documentation specifies

### ISSUE THREAD

**Issue by jedleslie** [mrdoob/three.js#22806]
GLTFLoader onError handler receiving ProgressEvent - not error as documentation specifies

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

Load any model with the GLTFLoader using .load(url, onSuccess, onProgress, onError).  Have the model throw an error (or give a bad url to load the model).  Notice that the onError handler receives a "ProgressEvent" as the parameter, not an "error". 

**Expected behavior**

Expects to receive an error message or collection.

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: 0.131.1

**Comment by Mugen87** [comment]
It seems the following fiddle does not reproduce this issue: https://jsfiddle.net/q04jcy2r/

The code requests a glTF asset from invalid URL. After some time, a connection timeout is logged. The error event can be processed in the respective callback.
