### ISSUE TITLE
Unmuting video's causing performance issues on iOS

### ISSUE THREAD

**Issue by leeuwisarvin** [mrdoob/three.js#22814]
I'm currently building a scene including video textures. When a user is trying to unmute the video's the scene is stuttering. This happens when you set the muted prop false. This only happens on Safari, especially mobile Safari.

**To Reproduce**

1. Go to https://zesnullen.vercel.app/ on a iOS Safari Browser (iPhone)
2. Scroll (Should be smooth)
3. Click on 'Toggle Sound'
4. Scroll (Should be laggy)

***Code***
The texture.element is the video node

```js
state.textures.forEach(texture => {
  if (texture.element.muted) {
    texture.context.resume()
    texture.element.muted = false
  } else {
    texture.element.muted = true
  }
})
```

**Live example**

* [Vercel staging link](https://zesnullen.vercel.app/)

**Platform:**

 - Device: Mobile
 - OS: iOS
 - Browser: Safari

**Comment by mrdoob** [comment]
> This only happens on Safari, especially mobile Safari.

You should report the issue to Safari directly then:
https://webkit.org/reporting-bugs/
