### ISSUE TITLE
OffscreenCanvas support broken

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#22811]
**Describe the bug**

OffscreenCanvas no longer works

**To Reproduce**

Use any example with OffscreenCanvas

** Reason **

This commit

https://github.com/mrdoob/three.js/commit/6056cbfc22b3675b65d5109a5a096ec39c91cdc6

tries to call `_canvas.setAttribute` but `OffscreenCanvas` does not have a function `setAttribute`

**Comment by Mugen87** [comment]
For testing: https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_worker_offscreencanvas.html

**Comment by Mugen87** [comment]
It seems simply checking for `OffscreenCanvas` should fix the issue.

**Comment by greggman** [comment]
or checking that `typeof _canvas.setAttribute === "function"` or is non-null, etc..

**Comment by Mugen87** [comment]
When checking for `OffscreenCanvas` we need:
```js
( typeof OffscreenCanvas !== 'undefined' ) && ( _canvas instanceof OffscreenCanvas === false )
```
`OffscreenCanvas` can be `undefined` in certain environments.

**Comment by Mugen87** [comment]
Or we just do it the other way around:
```js
( typeof HTMLCanvasElement !== 'undefined' && _canvas instanceof HTMLCanvasElement ) _canvas.setAttribute( 'data-engine', `three.js r${REVISION}` );
```
I favor this one.

**Comment by greggman** [comment]
I'd favor

```
if ( typeof _canvas.setAttribute === "function" ) _canvas.setAttribute( 'data-engine', `three.js r${REVISION}` );
```

I have no idea what new types of elements will be passed in the future but my guess is if they have a `setAttribute` function you'd want to call it vs checking specifically for a certain type of element?

**Comment by mrdoob** [comment]
How about this?

```js
// OffscreenCanvas does not have setAttribute
if ( 'setAttribute' in _canvas ) _canvas.setAttribute( 'data-engine', `three.js r${REVISION}` );
```

**Comment by Mugen87** [comment]
Looking good! Let's use this approach. And hope that future types of elements having a `setAttribute()` won't have different semantics 😅 .

**Comment by mrdoob** [comment]
> Looking good! Let's use this approach. And hope that future types of elements having a `setAttribute()` won't have different semantics 😅 .

At this point I wouldn't be surprised... 😬

Done! https://github.com/mrdoob/three.js/commit/fe71b47232accbe26a5acc2e2c5bffe74219e551
