### ISSUE TITLE
Env maps on editor don't show

### ISSUE THREAD

**Issue by tfreifeld** [mrdoob/three.js#22819]
I know that the support for env maps on the editor is limited. But unless I'm missing something, it seems that the situation now is worse than it was a few revisions ago.

The env maps don't seem to show at all.

Add a simple box (or something) to the scene. 
Add an env map to it.
 
The env map isn't shown. I've tried both standard and basic materials. With basic, changing the reflectivity parameter makes a visible change, but the env map is still seemed to be ignored.

![image](https://user-images.githubusercontent.com/31798283/141316049-1f3f2996-04fa-4198-828c-4a6ce70ae9ef.png)

**Comment by Mugen87** [comment]
> it seems that the situation now is worse than it was a few revisions ago.

Do you mind modifying the following URL so we can see how it worked in the past? Just change the `r134` part of the URL.

https://raw.githack.com/mrdoob/three.js/r134/editor/index.html

The only way environment maps can be defined right now is via the `Scene` tab and by selecting `EQUIRECT` from the `Environment` select box. This only works for `MeshStandardMaterial` and `MeshPhysicalMaterial` though.

AFAICS, the env map field in the materials tab is broken right now. I'm not even sure it ever worked. The editor would have to set the mapping property of the texture to `EquirectangularReflectionMapping` but I don't find place where this is currently done.

**Comment by tfreifeld** [comment]
> Do you mind modifying the following URL so we can see how it worked in the past? Just change the `r134` part of the URL.

Sure. This the result with the same textures being applied in r128.

![image](https://user-images.githubusercontent.com/31798283/141331811-d44be73f-b2ec-492f-aca3-dea93526aa80.png)

**Comment by Mugen87** [comment]
Okay, it seems this broke when the material sidebar was refactored with `r131`. The `THREE.EquirectangularReflectionMapping` assignment is indeed missing.
