### ISSUE TITLE
The mask attribute of Layers is -2147483648

### ISSUE THREAD

**Issue by 1337816495** [mrdoob/three.js#22817]
**Describe the bug**
If I call set(31) on an entity of Layers, the entity's mask attribute value is -2147483648, I think it is more appropriate to change the value of the mask attribute to 2147483648.
I put forward my modification ideas in the "Change code" section.

***Code***
```js
const layers = new Layers();

layers.set(31);
layers.mask; // -2147483648
```

**Expected behavior**
```js
const layers = new Layers();

layers.set(31);
layers.mask; // 2147483648
```

**Change Code**
original：
```js
class Layers {
    set(channel) {
        this.mask = 1 << channel | 0;
    }
}
```
new：
```js
class Layers {
    set(channel) {
        this.mask = (1 << channel | 0) >>> 0;
    }
}
```

**Platform:**

 - Three.js version: [r134]

**Comment by Mugen87** [comment]
The value of `mask` should not be relevant for users? It should be considered as a private property.

Why are you relying on it?

**Comment by Mugen87** [comment]
In any event, the change looks correct: https://jsfiddle.net/s3bp4yod/

Do you mind filing a PR with the fix?

**Comment by 1337816495** [comment]
> The change looks correct: https://jsfiddle.net/s3bp4yod/
> 
> Do you mind filing a PR with the fix?

it's my pleasure, I will submit a PR this weekend :D
