### ISSUE TITLE
typo in doc on .bezierCurveTo of ShapePath

### ISSUE THREAD

**Issue by hopezh** [mrdoob/three.js#22826]
**Describe the bug**

As stated in the doc on [.bezierCurveTo of ShapePath](https://threejs.org/docs/?q=quadraticCurveTo#api/en/extras/core/ShapePath.bezierCurveTo):  

```
.bezierCurveTo ( cp1X : Float, cp1Y : Float, cp2X : Float, cp2Y : Float, x : Float, y : Float ) : this

This creates a bezier curve from the currentPath's offset to x and y with cp1X, cp1Y and cp1X, cp1Y as control points and updates the currentPath's offset to x and y.
```

Shouldn't it be "...with cp1X, cp1Y and **_cp2X_**, **_cp2Y_** as control points..." for the last sentence? 

**To Reproduce**

***Code***

***Live example***

**Expected behavior**

**Screenshots**

**Platform:**

**Comment by Mugen87** [comment]
Indeed! Would you like to fix this with a PR?

**Comment by hopezh** [comment]
Thanks for the verification. However, I'm still very new to Git, and not familiar at how to make a pull request. The last thing I want to do is messing up the source code of the three.js' doc accidentally. So, I'd appreciate if you or any other core developers can kindly help to fix this minor issue.

**Comment by Mugen87** [comment]
Okay, should be fixed now. 09696e5454046bc5478f3f58339e654b5b8e7e4b 741dbef445dcf6f65d2d759e6e75fd1bf0b163be
