### ISSUE TITLE
TorusGeometry's Chinese translation error

### ISSUE THREAD

**Issue by 1337816495** [mrdoob/three.js#22827]
**Describe the bug**
In "Constructor", the Chinese translations of "radialSegments" and "tubularSegments" are wrong:

① The Chinese translation of "radialSegments" is "圆环的分段数，默认值为8", which means "the number of segments of the torus, the default value is 8". But its correct meaning is "the number of segments of the tube, the default value is 8".

② The Chinese translation of "tubularSegments" is "管道的分段数，默认值为8", which means "the number of segments of the tube, the default value is 6". But its correct meaning is "the number of segments of the torus, the default value is 6".

**Old translation**
radialSegments — 圆环的分段数，默认值为8。
tubularSegments — 管道的分段数，默认值为6。

**New translation**
radialSegments — 管道的分段数，默认值为8
tubularSegments — 圆环的分段数，默认值为6

**Platform:**

 - Three.js version: [dev, r134]

**Comment by Mugen87** [comment]
Would you like to fix this with a PR?

**Comment by Mugen87** [comment]
After reading your translation more closely, it seems the current writing is correct. `radialSegments` refers to the number of radial segments of the torus whereas `tubularSegments` refers to the segments of the tube.

Maybe it would be less confusing if the term `tube` is completely removed from the `TorusGeometry` page and just `torus` is used.

**Comment by 1337816495** [comment]
> After reading your translation more closely, it seems the current writing matches the terms used in the English page. `radialSegments` refers to the number of radial segments of the torus whereas `tubularSegments` refers to the segments of the tube.
> 
> Maybe it would be less confusing if the term `tube` is completely removed from the `TorusGeometry` page and just `torus` is used.

In the Chinese document of TorusGeometry, 
① `radius` is translated as "the radius of the ring"(圆环的半径).
② `tube` is translated as "the radius of the pipe"(管道的半径).
This makes me think "ring" refers to the entire geometry (torus).
Then
① `radialSegments` is translated as "the number of segments of the ring"(圆环的分段数).
② `tubularSegments` is translated as "the number of segments of the pipe"(管道的分段数).
Finally
I  _**mistakenly**_ thought I could control the smoothness of the torus through `radialSegments,` and `tubularSegments` to control the smoothness of the pipe, but things backfired.

The root cause of the misunderstanding is: _**both `radius` and `radialSegments` describe the "ring"(圆环) as the target object**_, 
The use of the term "ring" in the definition of `radius` is inaccurate("torus" should be used instead of "ring"), but the user can still understand the correct meaning. Continuing to use "ring" in the definition of `radialSegments` will cause misunderstandings.

"`radialSegments` refers to the number of radial segments of the torus" is an accurate definition.

### Suggest
①`radius` 
current:

> 圆环的半径，从圆环的中心到管道（横截面）的中心。默认值是1 (It measn "The radius of the ring, from the center of the ring to the center of the pipe (cross section). The default value is 1")

new:

> 环面的半径，从环面的中心到管道横截面的中心。默认值是1 (It means "The radius of the torus, from the center of the torus to the center of the pipe cross section. The default value is 1")

②`radialSegments`
current:

> 圆环的分段数，默认值为8（It means "The number of segments of the ring, the default value is 8"）

new:

> 管道横截面的边数，默认值为8（It means "The number of sides of the pipe cross section, the default value is 8"）

**Comment by mrdoob** [comment]
@linbingquan can you help with this?

**Comment by moshuying** [comment]
In Chinese, a curved pipe with a radius of 360 degrees can be called a `甜甜圈`, but a curved pipe with a radius of less than 180 degrees and less than 90 is called a `大半径弯管` bend, and a curved pipe with a radius of less than 90 degrees is called a `小半径弯管`. This ambiguity is actually caused by setting the radius to 360 degrees in the example. At present, this translation is not very ambiguous and will not cause too many problems, because even in China, we also call it `torus`.

**Comment by linbingquan** [comment]
> Describe the bug
> In "Constructor", the Chinese translations of "radialSegments" and "tubularSegments" are wrong:

It means just want to change `radialSegments` and `tubularSegments` describe in Chinese translations.

I found they are managed one to one. `radius` -> `radialSegments`, `tube` -> `tubularSegments`.
Just switched two Chinese nouns in `radialSegments` and `tubularSegments`, which is not quite right in my opinion.

**Comment by 1337816495** [comment]
> > Describe the bug
> > In "Constructor", the Chinese translations of "radialSegments" and "tubularSegments" are wrong:
> 
> It means just want to change `radialSegments` and `tubularSegments` describe in Chinese translations.
> 
> I found they are managed one to one. `radius` -> `radialSegments`, `tube` -> `tubularSegments`. Just switched two Chinese nouns in `radialSegments` and `tubularSegments`, which is not quite right in my opinion.

I made a new suggestion on the 2nd floor to replace the old suggestion (with detailed reasons) , now it is no longer the exchange of Chinese nouns in `radialSegments` and `tubularSegments`.

Hope you can take a look at it.

**Comment by linbingquan** [comment]
@mrdoob TBH, I am not good at English,  Will it be modify in English docs? If it will be, is that ok like this?

```diff
// English Docs - TorusGeometry.html - Constructor

- radius - Radius of the torus, from the center of the torus to the center of the tube. Default is 1.
+ radius - Radius of the torus, from the center of the torus to the center of the pipe cross section. Default is 1.
tube — Radius of the tube. Default is 0.4.
radialSegments — Default is 8
tubularSegments — Default is 6.
arc — Central angle. Default is Math.PI * 2.
```

The `radialSegments` has more detail In Chinese docs. If we use the term "pipe" to describe `radius` parameter, which I think it works in Chinese docs context.

**Comment by Mugen87** [comment]
Is somebody willing to make a PR so this issue can be closed?

**Comment by 1337816495** [comment]
> Is somebody willing to make a PR so this issue can be closed?

Hi, i can! And can I use the translation I proposed?
I actually proposed two versions of translation, the first version is the issue itself, the second version is in the comment area (2nd floor). I want to use the second version.

**Comment by Mugen87** [comment]
> And can I use the translation I proposed?

I don't speak Chinese so I can't decide that. It's probably best if @linbingquan makes a decision.

@linbingquan I suggest to not alter the English docs since the description is  already clear.

**Comment by 1337816495** [comment]
@linbingquan Hi, do you think my second suggestion is right? (2nd floor of the comment area)

**Comment by linbingquan** [comment]
@1337816495 Please provide your PR for Cinese docs.

**Comment by linbingquan** [comment]
@1337816495 Please provide your PR for Chinese docs.

**Comment by 1337816495** [comment]
> @1337816495 Please provide your PR for Chinese docs.

OK!  :D
