### ISSUE TITLE
MeshPhysicalMaterial: clearcoatMap does not properly work.

### ISSUE THREAD

**Issue by epouliquen** [mrdoob/three.js#22837]
**Describe the bug**

MeshPhysicalMaterial : setting a map in clearcoatmap doesn't affact the coating rendering

seen in 0.133.1 , also in 0.134.0

**To Reproduce**

1. Create a MeshPhysicalMaterial
2. set clearcoat value to one
3. put a map in clearcoatMap
4. see that the map has no impact on rendering

**Expected behavior**

the clearcoatMap red channel should multiply the cleacoat value locally

**Screenshots**

can also see the issue on the 'clearcoattest.glb' model provided in three.js-dev\examples\models\gltf\ClearcoatTest 

![image](https://user-images.githubusercontent.com/50987570/141809073-e2bcc64d-5514-479c-8553-aaae593377b6.png)

**Platform:**

 - Device: Desktop
 - OS: Window
 - Browser: Chrome
 - Three.js version: r134

**Comment by Mugen87** [comment]
Indeed, I can confirm that this particular test (partial coating) fails.

**Comment by Mugen87** [comment]
For comparison:

https://raw.githack.com/mrdoob/three.js/r131/editor/index.html
https://raw.githack.com/mrdoob/three.js/r132/editor/index.html

Just drag the [ClearcoatTest](https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf/ClearcoatTest) and set the environment to `MODELVIEWER` to see the issue.
