### ISSUE TITLE
Add setAzimuthalAngle, setPolarAngle , setDistance functions in Orbitcontroller

### ISSUE THREAD

**Issue by optimus007** [mrdoob/three.js#22836]
**Is your feature request related to a problem? Please describe.**

instead of doing position math while trying to fit the object in the viewport these methods could simplify the process.

ex: 45 deg vertical ,30 deg to the left to the side and 4 meter distance to the target.

**Describe the solution you'd like**
In orbitcontroller new additions will be

.setAzimuthalAngle () : radians
Set the current horizontal rotation, in radians.

.setPolarAngle () : radians
Set the current vertical rotation, in radians.

.setDistance () : Float
Set the distance from the camera to the target.

**Comment by Mugen87** [comment]
This was already discussed here: #22174
