### ISSUE TITLE
Adding GLSL style swizzling to vectors

### ISSUE THREAD

**Issue by mrmola** [mrdoob/three.js#22849]
I love [glsl swizzling](https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Swizzling), and I was wondering if we could get the same thing in threejs? I mean this sort of thing: 
`u.set(new THREE.Vector3(v.x,v.x,v.y))`

**Describe the solution you'd like**

Something that works the same as the following code but isn't run afterwards added:
```js
array = ["x","y","z"]
swizzle2d = array.map(e=>array.map(f=>[f,e])).flat(1)
swizzle3d = array.map(e=>array.map(f=>array.map(g=>[e,f,g]))).flat(2)
swizzle2d.forEach(e=>{
			Object.defineProperty(this, e[0]+e[1], {
				get: function() {
					return new THREE.Vector2(this[e[0]],this[e[1]]);
				},
				set: function(vec2) {
					this[e[0]] = vec2[e[0]];
					this[e[1]] = vec2[e[1]];
				}
			})
})

swizzle3d.forEach(e=>{
			Object.defineProperty(this, e[0]+e[1]+e[2], {
				get: function() {
					return new THREE.Vector3(this[e[0]],this[e[1]],this[e[2]]);
				},
				set: function(vec3) {
					this[e[0]] = vec3[e[0]];
					this[e[1]] = vec3[e[1]];
					this[e[2]] = vec3[e[2]];
				}
			})
})
```

**Additional context**

Will this cause performance issues?  I am unclear on how getters and setters work.

**Comment by mrdoob** [comment]
> I mean this sort of thing: 
`u.set(new THREE.Vector3(v.x,v.x,v.y))`

Can't you do that already?

**Comment by mrdoob** [comment]
Could you explain what the code you shared does?

**Comment by mrmola** [comment]
It adds a getter and setter to the vector prototype for every possible permutation of x, y, and z. The getter returns whatever permutation of x, y, and z you have requested; For instance:
`
let u = new THREE.Vector3(1,2,3);
let v = u.xzy //v is now 1,3,2
`
The setter allows you to do the same with setting, for instance
` let v = new THREE.Vector3(1,2,3);
v.xz = new THREE.Vector2(9,8); //v is now 9,2,8`

**Comment by Mugen87** [comment]
TBH, I find this API style confusing and error-prone. You have to read the code really closely to understand how an assignment influences vector components.

You also allocate a new vector instance in your getters at every call which is a no-go in context of performance.

**Comment by makc** [comment]
does not seem to work in chrome 96
![Screen Shot 2021-11-21 at 12 02 25 ](https://user-images.githubusercontent.com/242577/142759220-24077ea5-7e06-4baf-b7e2-d96499b9f399.png)
https://jsfiddle.net/db7heup9/

**Comment by makc** [comment]
ah sorry it was about `this` https://jsfiddle.net/hogrs8uz/

**Comment by makc** [comment]
> You also allocate a new vector instance in your getters at every call 

there is no way around it, consider
```js
let b = a.xyy;
let c = a.xyy;
b.x = 1;
console.log(c.x); // what now ?
```
if you will not allocate new instance, you would get 1 there

**Comment by Mugen87** [comment]
> > You also allocate a new vector instance in your getters at every call

> there is no way around it

That's why I think it's a bad programming pattern. `clone()` is controversial in this regard, too. I've noticed in the past that some users (in any skill level) use it as a convenience method for creating objects without knowing the performance implications.

**Comment by mrmola** [comment]
Not in this specific context, but how do I make it so it doesn't make new objects? Like I know the performance implications, i just don't see any other way around them even in other contexts.

**Comment by gkjohnson** [comment]
> Not in this specific context, but how do I make it so it doesn't make new objects? Like I know the performance implications, i just don't see any other way around them even in other contexts.

Most other math functions take a "target" object that is used to get the result of an operation which ultimately I think would defeat the simplicity of your swizzle functions. That target function can be global so it's reused without having to be remade in any frequently evaluated contexts. Something like:

```js
const target = new Vector3()
const v = new Vector3( 1, 2, 3 );
v.yyx( target );

console.log( target ); // 2, 2, 1
```

I agree these types of fields are convenient and it's nice that they align with glsl behavior but unfortunately I think the nature of Javascript makes them difficult to implement elegantly.

Also FYI you don't need to pass a Vector3 into the `set` function. You can pass in numbers directly which makes the set function a fairly readable one liner:

```js
u.set( v.x, v.x, v.y );
```

**Comment by mrdoob** [comment]
Hmm... Seems like we should not go down this path.
