### ISSUE TITLE
DragControls: Expose raycaster.

### ISSUE THREAD

**Issue by draibolit** [mrdoob/three.js#22844]
**Is your feature request related to a problem? Please describe.**

I need to access the raycaster of drag control to handle the objects when they are not in the default layer.
I see that the transform control can access its raycaster to set to different layer, why it isn't the same with drag control?

**Describe the solution you'd like**
How about ?
```
		getRaycaster() {

			return _raycaster;

		} 
```

**Comment by Mugen87** [comment]
Sounds good! Would you like to make a PR?
