### ISSUE TITLE
OrbitControls: "Sticky" remedy when disabling then enabling controls is removed

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#22848]
**Describe the bug**

It seems that the changes from #20735 intended to deal with the issue raised in #20380 are no longer present in OrbitControls.js. Maybe the changes lost in the conversion to es6 modules? Or perhaps with some refactoring? Or did they cause other issues so they were removed? The issue is that currently when the user is dragging orbit controls then they are disabled, the use releases, then enabled again, the orbit controls continues to follow the mouse.

**To Reproduce**

--

***Live example***

--

**Expected behavior**

The OrbitControls do not "stick" when disabling then enabling them while the user is dragging.

**Screenshots**

--

**Platform:**

- All versions

**Comment by Mugen87** [comment]
It seems this got lost when `OrbitControls` was fully migrated to pointer events.

After looking at #20380 , it looks like the PR was not 100% correct either. It missed to set `state = STATE.NONE;` and to dispatch the end event. Just removing the event listener leaves the controls in a wrong state, too. How about implementing `onPointerUp()` like so:
```js
function onPointerUp( event ) {

    removePointer( event );

    if ( pointers.length === 0 ) {

        scope.domElement.releasePointerCapture( event.pointerId );

        scope.domElement.removeEventListener( 'pointermove', onPointerMove );
        scope.domElement.removeEventListener( 'pointerup', onPointerUp );

    }

    scope.dispatchEvent( _endEvent );

    state = STATE.NONE;

}
```
`onMouseUp()`, `onTouchEnd()`, `handleMouseUp()` and `handleTouchEnd` can be removed and the code inlined.

**Comment by mysterybear** [comment]
Aha, was trying to understand why I'm experiencing this! Hoping I can safely leave this until upstream fix then!

**Comment by gkjohnson** [comment]
> It missed to set state = STATE.NONE; and to dispatch the end event. Only removing the event listener leaves the controls in a wrong state.

Yes there were still issues with that PR but the approach for #20735 was preferred anyway so I never got to fixing them. At a quick look the change you're suggesting looks good to me and looks closer to #20735 than my original solution did. But I won't have the bandwidth to contribute or test more thoroughly until later in December, unfortunately!
