### ISSUE TITLE
Three js Extremely  laggy on chrome canary on OSX

### ISSUE THREAD

**Issue by jasan-s** [mrdoob/three.js#22850]
**Describe the bug**
 Opening [This Example](https://threejs.org/examples/#webgl_shadowmap_pointlight) 
 
 works smooth on all other Devices and Browsers. 
 
 But on the latest Chrome canary, it has extremely laggy performance( Version 98.0.4708.0 (Official Build) (x86_64))  on MAC. 
 
NOTE  The latest canary on Windows loads the example smoothly
 

**Platform:**

 - Device: Desktop, Mobile
 - OS: MacOS
 - Browser: Version 98.0.4708.0 (Official Build) canary (x86_64)
 - Three.js version: [This Example](https://threejs.org/examples/#webgl_shadowmap_pointlight) whatever this example uses

**Comment by mrdoob** [comment]
Please, report this to Chromium instead: https://crbug.com/wizard

**Comment by mrdoob** [comment]
Please, report this to Chromium instead: https://crbug.com/wizard
