### ISSUE TITLE
Unreal Bloom Pass Doesn't Work Without Meta on Android

### ISSUE THREAD

**Issue by DeeElGee** [mrdoob/three.js#22873]
Sharing this for reference in case anyone else comes across this issue.

I tried using Unreal Bloom Pass for a project, and it was working fine on everything but Chrome on Android (v96). Turns out this was all because I had missed the following line in the `<head>` tag:

`<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">`

Without this html element the Unreal Bloom Pass just showed up as black, and I received an error about textures. Seems slightly odd that a meta tag would result in such an error, but at least there's a solution.

Steps to repeat:
1. Copy HTML from https://threejs.org/examples/webgl_postprocessing_unreal_bloom.html
2. Ensure all resources are appropriately linked
3. Delete `<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">` line from top of HTML
4. View on android (notice nothing is shown)

**Comment by Mugen87** [comment]
Do you mind sharing a live link for testing?

**Comment by DeeElGee** [comment]
Sure.
https://www.dlgordon.co.uk/test/three-bloom-meta.html (with meta tag)
https://www.dlgordon.co.uk/test/three-bloom-no-meta.html (no meta tag)

On my Samsung Galaxy S20+ these show the behaviour described.

**Comment by Mugen87** [comment]
I can confirm the issue. In mobile Firefox however both pages can be rendered (although the one without the meta tag runs slower). Thanks for reporting this here but this is not an issue in the engine but a browser issue. 

If you want to find out the root cause for this, it's better to report it to the browser vendors. 

Just adding the meta tag avoids this issue in the first place. There is not really a reason why you don't want it.

**Comment by DeeElGee** [comment]
Yeah, understood. Was mostly posting for reference in case anyone else comes across this problem. Thanks for investigating though.

**Comment by mrdoob** [comment]
It's probably because if you don't use `<meta>` the canvas ends up being very big.

I think eventually we'll handle the sizing internally in the render using [devicePixelContentBox](https://web.dev/device-pixel-content-box/).
