### ISSUE TITLE
ICOSAHEDRON BUFFER GEOMETRY TRIANGLES UPDATE

### ISSUE THREAD

**Issue by ayekoleke** [mrdoob/three.js#22871]
**This is not exactly a bug report, but a question I can't find answer to elsewhere**

I want to write some simulations that involve editing the position of vertices of an icosahedron. I can use ‘attributes’ to get access to each vertices, but I need to deal with the triangles that make up the icosahedron; getting access to the three vertices per triangle because the simulation require I process the vertices in order according to the triangles.
.
How do I go about it?

**Comment by Mugen87** [comment]
Please use the forum for help.

https://discourse.threejs.org/
