### ISSUE TITLE
PositionalAudio breaks in webxr when moving the user

### ISSUE THREAD

**Issue by praedeth** [mrdoob/three.js#22884]
Adding THREE.PositionalAudio to a mesh inside a group (Object3D or Group)  alongside the user (camera) works as expected, but if the group is then moved the audio breaks.

**To Reproduce**

1. create a container to hold the "vehicle"
2. create and add a webxr "user" to the container
3. create an AudioListener and add it to the camera
4. create and add a PositionalAudio to the container
5. move the container "vehicle"

***Code***

```js
let carContainer = new THREE.Object3D();
scene.add(carContainer);

// create a "user" so that the webxr camera moves with the carContainer
let user = new THREE.Group();
carContainer.add(user);
user.add( camera );

// create an AudioListener and add it to the camera
const listener = new THREE.AudioListener();
camera.add( listener );

function tick() {
carContainer.position.z += 0.01;
}
```

***Live example***

(for some reason the fiddle doesn't show the VRButton button. I don't use jsfiddle much sorry...)
[https://jsfiddle.net/mayamoss/zgj5cvpk/90/](https://jsfiddle.net/mayamoss/zgj5cvpk/90/)

**Expected behavior**

Audio follows the user in local(sic) space.

**Platform:**

 - Device: Oculus Quest 2
 - Browser: Chrome
 - Three.js version: dev

**Comment by Mugen87** [comment]
> the audio breaks.

Can you please describe in more detail what "breaks" means? According to your expected behavior, I assume the positional audio just keeps its transformation in 3D space. Or do you experience some sort of the audio stutter or cracks?

**Comment by praedeth** [comment]
"Breaks" in this case means "goes weird", "glitches out", "crackles", "distorts"... Sorry!

**Comment by Mugen87** [comment]
Can you please apply #22362 to your app and see if it solves the issue?

**Comment by arpu** [comment]
we have the same problem with  newer webxrManger ,  using webxrManger from r129 in three r134  works

**Comment by arpu** [comment]
oh i see r129 use the decompose https://github.com/mrdoob/three.js/blob/r129/src/renderers/webxr/WebXRManager.js#L385

**Comment by arpu** [comment]
can confirm apply  #22362 to r135 fixed it

**Comment by praedeth** [comment]
I don't know what I'm doing wrong but it's still glitching (crackling) for me when I move the container even with r135 + #22362...
I'll simplify my example to try and get to the bottom of it and report back...

**Comment by remmel** [comment]
On my oculus quest 2, also got that problem introduced in Threejs 0.130 and still present in 0.136 (and all versions between). Everything is fine on 0.129

**Comment by Mugen87** [comment]
`r130` introduced #21964. AFAICS the related changes to `WebXRManager` are the root cause of this issue. #22362 shold fix this.
