### ISSUE TITLE
Since r132, I can't replicate MeshPhongMaterial’s new displacementMap-based self-shadowing using ShaderMaterial (with ShaderLib.phong) 

### ISSUE THREAD

**Issue by molzer** [mrdoob/three.js#22881]
**Describe the bug**

Since **r132**, it seems to be possible to have self-shadowing in geometry that has a `displacementMap` applied (see [DisplacementMap with Shadow - Three.js Tutorials 1](https://sbcode.net/threejs/displacmentmap_shadow/)).

Using `MeshPhongMaterial` in **r132**, I get the following (correct) result: the shadow casts from the grid structures – please ignore the block structures in the front):
<img width="521" alt="Bildschirmfoto 2021-11-23 um 21 27 19" src="https://user-images.githubusercontent.com/2663714/143233702-892780ec-10d1-4418-884b-5419449f4b29.png">

Up to **r131**, I had a custom depth material that enabled the same functionality (customized to an RGBA elevation texture that I’m decoding in the shader – which is why I can’t work with out-of-the-box `MeshPhongMaterial`), which now stopped working since **r132**. In one of many attempts to fix this, I tried to get a custom `ShaderMaterial` up and running, based on `ShaderLib.phong`. While the displacement mapping happens (displaced geometry can be seen in the following screenshot’s grid lines), there is no shadowing:
<img width="522" alt="Bildschirmfoto 2021-11-23 um 21 26 37" src="https://user-images.githubusercontent.com/2663714/143236132-995cc17f-134a-4768-88cd-0562334dff94.png">

Up to now, I tried out various `defines`, I’m setting the textures at “material level”, etc. – but I can’t get self-shadowing to work. It seems that there’s some define missing or some other flag off. I feel like I’m almost there but I’m not.

**To Reproduce**

In Three.js >= 132, create a `ShaderMaterial` with `ShaderLib.phong`. Set a `displacementMap`. While the mesh geometry gets distorted accordingly, there is no self-shadowing.

***Code***

```js
this.mesh.receiveShadow = true;
this.mesh.castShadow = true;

const terrainMaterial = new THREE.ShaderMaterial(THREE.ShaderLib.phong);
//I maxed out on defines in an attempt to get this to work:
terrainMaterial.defines = {
    USE_UV: "",
    USE_MAP: "",
    USE_BUMPMAP: "",
    USE_DISPLACEMENTMAP: "",
    VERTEX_TEXTURES: "",
};
terrainMaterial.lights = true;
terrainMaterial.fog = true;
terrainMaterial.extensions.derivatives = true;
terrainMaterial.extensions.fragDepth = true;

terrainMaterial.map = TerrainTile.TextureLoader.load("img/grid512.png");
terrainMaterial.uniforms.map.value = TerrainTile.TextureLoader.load("img/grid512.png");
terrainMaterial.displacementMap = TerrainTile.TextureLoader.load("img/grid512.png");
terrainMaterial.uniforms.displacementMap.value = TerrainTile.TextureLoader.load("img/grid512.png");

this.mesh.material = terrainMaterial;
this.mesh.material.needsUpdate = true;
```

**Expected behavior**

As self-shadowing got integrated into displacement mapped materials in r132, this should work with ShaderMaterial as well.

**Platform:**

 - Device: Desktop, Mobile
 - OS: MacOS
 - Browser: Chrome, Firefox, Safari
 - Three.js version: since r132

**Comment by Mugen87** [comment]
Do you mind demonstrating the issue with an editable live example? https://jsfiddle.net/f2Lommf5/

**Comment by molzer** [comment]
I created https://jsfiddle.net/cmLt475w/ to demonstrate the issue:
- `material` (`MeshPhongMaterial`) casts shadows on itself where
- `customShaderMaterial` (`ShaderMaterial`) does not

**Comment by Mugen87** [comment]
You have not created your shader material correctly. Try it like so: https://jsfiddle.net/o8f7qps1/1/

Meaning add all displacement properties to the shader material, avoid setting defines manually and also clone the uniforms.

BTW: At first glance,the issue's title sounds like a regression. In fact, this was a help request^^.

**Comment by molzer** [comment]
Thank you @Mugen87 for the general advice and making this work! 🙏 

To my defense 😅, it started as a help request (https://discourse.threejs.org/t/cannot-replicate-meshphongmaterials-new-displacementmap-based-self-shadowing-using-custom-shadermaterial-with-shaderlib-phong/32027) and the boss asked me to create an issue here.

I want to emphasize that the change that made the difference was to **_set all displacement properties – beside the displacementMap – explicitly_** (i.e., my laymen intuition was, that that's not required since these are default values – but they are required to toggle defines, I assume?):
```
customShaderMaterial.displacementScale = 1;
customShaderMaterial.uniforms.displacementScale.value = 1;
customShaderMaterial.displacementBias = 0;
customShaderMaterial.uniforms.displacementBias.value = 0
```

Anyways, hallelujah!

**Comment by gkjohnson** [comment]
```js
  customShaderMaterial.map = texture;
  customShaderMaterial.uniforms.map.value = texture;
  customShaderMaterial.displacementMap = texture;
  customShaderMaterial.uniforms.displacementMap.value = texture;
  customShaderMaterial.shininess = 50;
  customShaderMaterial.uniforms.shininess.value = 50;
  customShaderMaterial.displacementScale = 10;
  customShaderMaterial.uniforms.displacementScale.value = 10;
  customShaderMaterial.displacementBias = 0;
  customShaderMaterial.uniforms.displacementBias.value = 0;
```

Is this much redundancy expected to be required? This seems at least like unexpected behavior. Why is it that the map or displacementMap must be set on both the uniforms object _and_ the root material object in order for it to work?

**Comment by Mugen87** [comment]
The renderer works with both material properties and uniform values. At least when you want to use the built-in shaders.

I'm not sure but I don't think the approach of the fiddle is the recommended way of the project to enhance built-in materials. IMO, the OP should use `onBeforeCompile()` instead.

**Comment by WestLangley** [comment]
@gkjohnson @Mugen87 

This pattern:
```js
customShaderMaterial.map = texture;
customShaderMaterial.uniforms.map.value = texture;
```
was a user hack to get code injection for non-built-in materials to work. In code was injected by the now-removed `getTexelDecodingFunction()`, which injected per-pixel color-space decoding into the shader. The code injector tested for the presence of a ".map" property in this case.

See #15187 for a better way to achieve the same.

**Comment by easyfrog** [comment]
> You have not created your shader material correctly. Try it like so: https://jsfiddle.net/o8f7qps1/1/
> 
> Meaning add all displacement properties to the shader material, avoid setting defines manually and also clone the uniforms.
> 
> BTW: At first glance,the issue's title sounds like a regression. In fact, this was a help request 😉 .

The jsfiddle link is broken!
