### ISSUE TITLE
Enable usage of SRGB8_ALPHA8

### ISSUE THREAD

**Issue by Peque** [mrdoob/three.js#22892]
It was disabled due to [performance issues while decoding sRGB textures under Windows](https://github.com/mrdoob/three.js/issues/22631#issuecomment-954979978).

The goal would be to revert https://github.com/mrdoob/three.js/pull/22759 some day. Probably after [Chromium Issue 1256340](https://bugs.chromium.org/p/chromium/issues/detail?id=1256340) is fixed.

Opening this issue to track the status and future updates.

**Comment by Mugen87** [comment]
We can also enable `SRGB8_ALPHA8` when `gl.texStorage2D()` is fully adapted.
