### ISSUE TITLE
SVGLoader: Paint order

### ISSUE THREAD

**Issue by tangobravo** [mrdoob/three.js#22898]
#21330 mentions paint order as one of the currently unsolved issues in the SVGLoader.

I've been digging into how complex SVGs like the tiger seem to render in the right order, when the example code still has the default of the renderer sorting all meshes. This brought me to the painterSortStable function, which provides the solution - the meshes each get their own materials with incrementing IDs, which is one of the sort keys for opaque objects.

However I did notice that meshes that have opacity < 1 are set transparent: true:
https://github.com/mrdoob/three.js/blob/890c35d31468200b1c8b04a2d0fef89ac8d96289/examples/webgl_loader_svg.html#L168

That's going to get those meshes into a separate sort list, and have them all rendered after the other ones.

Even the opaque objects are set `depthWrite: false` which I think probably breaks the general assumption that render order doesn't matter for opaque objects. So I think it might actually work better to set all of these SVGLoader materials as `transparent: true`. I think that will also likely sort them all in a consistent way. With the default transparent sort function ` reversePainterSortStable` I think all the SVGLoader meshes will be equal on the first three keys, resulting in a sort by object.id which should be in incrementing order for the whole path list.

Wanted to write up before forgetting but will try it out now and see if I can come up with a simple test case that it improves.

**Comment by tangobravo** [comment]
I've added a PR to switch to setting all materials `transparent: true` in the SVGLoader example.

Example SVG file - layered rects 20% opacity red, opaque black, 50% opacity green, opaque blue:
<img width="281" alt="Screenshot 2021-11-29 at 14 59 02" src="https://user-images.githubusercontent.com/770066/143890899-16d39fe9-b7ff-40b9-a9b5-f30d29194abe.png">

Before - non-opaque shapes rendered last:
<img width="733" alt="Screenshot 2021-11-29 at 14 56 05" src="https://user-images.githubusercontent.com/770066/143890438-a1c84c4d-ad4b-4789-a9db-5102a7b60177.png">

After - correct ordering:
<img width="740" alt="Screenshot 2021-11-29 at 14 57 04" src="https://user-images.githubusercontent.com/770066/143890552-5cec929a-1ca9-4f4f-be3a-3e0003b00fe9.png">

The other thing this changes is how the SVG meshes interact with other opaque 3D meshes. As all the SVG materials have `depthWrite: false`, they could appear behind other 3D objects depending on render order.

Before this change, adding a cube to the SVGLoader demo:
<img width="617" alt="Screenshot 2021-11-29 at 15 03 01" src="https://user-images.githubusercontent.com/770066/143891521-c2f8160f-79c2-4f48-a64c-251061dea32f.png">

After the change, all SVG meshes are rendered after all opaque objects in the render list, giving a more correct result:
<img width="668" alt="Screenshot 2021-11-29 at 15 02 26" src="https://user-images.githubusercontent.com/770066/143891609-f6c7699c-6961-4d5d-ba78-118ea64e1d8b.png">

**Comment by mrdoob** [comment]
#22912 addressed this.
