### ISSUE TITLE
painterSortStable no longer sorts by program

### ISSUE THREAD

**Issue by tangobravo** [mrdoob/three.js#22897]
The painterSortStable function uses materialProperties.program here:
https://github.com/mrdoob/three.js/blob/baf652649f2f0a2807c2a1065f38e060b9275aa7/src/renderers/webgl/WebGLRenderLists.js#L87

Since merging PR #20135 it seems that key is never set, as there are now potentially multiple programs per-material.

In practice that seems to mean everything is now sorted just ignoring the program.id (as it is defaulted to -1).

If sorting by program is still desired (guess it could reduce state changes?) then it looks like a fix is needed.

**Comment by Mugen87** [comment]
Thanks for reporting! The mentioned line is indeed obsolete and can be removed.

**Comment by Mugen87** [comment]
Fixed via 890c35d31468200b1c8b04a2d0fef89ac8d96289.

**Comment by tangobravo** [comment]
That was quick! Thanks :)
