### ISSUE TITLE
Add CanvasTexture support to GLTFExporter

### ISSUE THREAD

**Issue by morandd** [mrdoob/three.js#22896]
First, thank you to everyone for three.js! It is amazing. 

The feature request: Allow the GLTF exporter to support CanvasTexture in a Node environment.

Use case: Using THREE.CanvasTexture with node-canvas to generate GLTF files on a headless node.js server.

Proposed solution:
Add support for canvas images in GLTFExporter. I have hacked my copy using the following, but there must be a better way to test whether the incoming item is a canvas which supports getContext('2d').  Preferably the test should be done in a manner that supports both browser canvas and the node-canvas module ( https://github.com/Automattic/node-canvas ). I am using try/catch to do the test but there must be a more elegant way.

line 978 in examples/jsm/exporters/GLTFExporter.js:

```
processImage( image, format, flipY ) {
// If 'image' is a canvas, here we convert it to an ImageData object
try {
  image = image.getContext('2d').getImageData(0,0,image.width,image.height);
  console.log('Custom edit to GLTFLoader: convert canvas to image');
} catch (e){
  // Do nothing in this case, since the incoming item was not a canvas
}
// Proceed with processImage normally
```

**Comment by morandd** [comment]
ps. I am using the canvas polyfill which I saw suggested elsewhere by mrdoob, to replace document.createElement('canvas') with the node-canvas createCanvas() function. This is critical to get anywhere with GLTFExporter in nodejs.

global.document = {
  createElement: (nodeName) => {
    if (nodeName == 'canvas') return createCanvas(256, 256) else throw new Error(`Cannot create node ${nodeName}`);
  }
};
global.ImageData = function ImageData(data, w, h){
    return createImageData(data,w,h);
}

**Comment by Mugen87** [comment]
To be clear: Canvas textures are already supported if you use `GLTFExporter` in the browser.

You are asking for support in a node environment.

**Comment by Mugen87** [comment]
The `global` keyword is not defined in browsers. How is your polyfill supposed to work outside of node?

**Comment by morandd** [comment]
The polyfill goes in my app. It would be a possible to update gltfexporter to autodetect the availability of document.createElement('canvas') vs createCanvas from node-canvas.

I don't think it's crazy to want to do three on the server, since it's a very easy tool to build simple gltf models and those gltfs can then be used in lots of places (three in the browser, unity, blender, PowerPoint, etc).

**Comment by Mugen87** [comment]
>It would be a possible to update gltfexporter to autodetect the availability of document.createElement('canvas') vs createCanvas from node-canvas.

The problem is that `GLTFExporter` will not import `node-canvas` so the app would have to manage this dependency. This half-way solution is not good in my opinion. If `createCanvas()` would be a global node function then fine. But we do not implement modules which rely on other node libs.

So I think it's better if you keep applying your polyfill on app level.

**Comment by morandd** [comment]
Yes, agreed. Maybe gltfexporter could even detect if it's in a environment without document.createelemrent and offer a reference to this thread, to help future folks who stumble into this issue? 

But the above code lines I offered are needed even with the polyfill, hence my suggestion to include them into the three main branch.

**Comment by Mugen87** [comment]
I would rather suggest to make a central manual page about node.js instead of spreading information all over the code base. E.g. a canvas polyfill would be required at different places, too, depending on what components and code you are using.
