### ISSUE TITLE
Manual: Editor is obscured.

### ISSUE THREAD

**Issue by ycw** [mrdoob/three.js#22890]
**Describe the bug**

editor is obscured when 'expand'

![layout bug ](https://user-images.githubusercontent.com/1063018/143593499-e37f17d8-c363-4334-8a7a-a3c345b67ed0.gif)

**Expected behavior**

editor ontop side panel ; or expand editor upto the frame it resides.

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [r135]

**Comment by Mugen87** [comment]
This is a know issue, see https://github.com/mrdoob/three.js/pull/22807#issuecomment-979785954.

**Comment by makc** [comment]
you probably could fix it with something like this:
![Screen Shot 2021-12-03 at 13 16 20 ](https://user-images.githubusercontent.com/242577/144601259-0feac4bb-1654-4d38-a713-7010bfa72934.png)
+ left = 0 for mobiles with media query

**Comment by Mugen87** [comment]
@makc Do you mind filing a PR with your idea?
