### ISSUE TITLE
Ray casting engine 

### ISSUE THREAD

**Issue by nodefordgame** [mrdoob/three.js#22913]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by donmccurdy** [comment]
A bit short on details here. :) 

If you're looking for help, I'd suggest the forums: https://discourse.threejs.org/

If you're looking for an engine to accelerate raycasting, try: https://github.com/gkjohnson/three-mesh-bvh
