### ISSUE TITLE
TGALoader ignoring magFilter

### ISSUE THREAD

**Issue by stirante** [mrdoob/three.js#22922]
**Describe the bug**

When loading TGA files using `TGALoader` and setting `texture.magFilter = Three.NearestFilter;` it's still using linear one. I rendered a simple cube, where sides are TGA texture and top and bottom are PNG and the difference is clear.

**To Reproduce**

1. Create a mesh with `BoxGeometry` and `MeshBasicMaterial`, that uses a texture loaded from `TGALoader`
2. Set `texture.magFilter = Three.NearestFilter;`
3. See cube texture filtered with Linear filter instead of Nearest filter

***Code***
This is roughly the code I'm using (with app specific bits removed)
```js
      const loader = new Three.TextureLoader();
      const tgaLoader = new TGALoader();
      const textures = [
        "/north.tga",
        "/east.tga",
        "/up.png",
        "/down.png",
        "/west.tga",
        "/east.tga"
      ].map(side => {
        let tex;
        if (side.endsWith('.tga')) {
          tex = tgaLoader.load(side);
        } else {
          tex = loader.load(side);
        }
        tex.magFilter = Three.NearestFilter;
        return new Three.MeshBasicMaterial({map: tex});
      });
      let geometry = new Three.BoxGeometry(0.5, 0.5, 0.5);
      object.add(new Three.Mesh(geometry, textures));
```

**Screenshots**

![obraz](https://user-images.githubusercontent.com/2420740/144047993-0d927779-45ab-4d00-a589-e4aafff9ed80.png)

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Firefox
 - Three.js version: 0.135.0

**Comment by Mugen87** [comment]
Apply your configuration in the `onLoad()` callback of `TGALoader.load()`.

Some data texture loaders apply texture settings based on the loader configuration and the file itself. If you configure your texture after the load, your settings won't be overwritten.

**Comment by stirante** [comment]
Thank you, that seems to be working well.
