### ISSUE TITLE
Using webglmultisamplerendertarget with outlinepass can cause problems

### ISSUE THREAD

**Issue by pai16858** [mrdoob/three.js#22929]
I'm on webgl_postprocessing_outline.html line 241 added

**const parameters = {

format: THREE.RGBFormat

};

const size = renderer.getDrawingBufferSize( new THREE.Vector2() );

const renderTarget = new THREE.WebGLMultisampleRenderTarget( size.width, size.height, parameters );

composer = new EffectComposer( renderer,renderTarget );**

code
It will cause problems similar to delay effect.
R134 does not have this problem

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r135]
![5dm1qxlnoz3igrt79d43kxi66_0](https://user-images.githubusercontent.com/26533053/144235937-92070a21-b00b-4a5f-8742-1a67b1c70625.jpg)

**Comment by pai16858** [comment]
![5dm1qxlnoz3igrt79d43kxi66_0](https://user-images.githubusercontent.com/26533053/144235872-113b96c9-2083-4ff6-a337-3d503f43362d.jpg)

**Comment by Mugen87** [comment]
`OutlinePass` is currently not compatible with `WebGLMultisampleRenderTarget`. If you need antialiasing, use a FXAA pass for now.

**Comment by Mugen87** [comment]
Merging this into #22967. It's actually a duplicate.
