### ISSUE TITLE
FileLoader: Incorrect error handling.

### ISSUE THREAD

**Issue by leyiang** [mrdoob/three.js#22923]
**Describe the bug**

Error inside the onLoad callback of fileloader will show `TypeError: Cannot read property 'length' of undefined` instead of real error.

**To Reproduce**

1. Instantiate FileLoader
2. Throw an error insdie onLoad function intentionally
3. Check the error inside DevTools

***Code***

```js
// Simple three.js example

import * as THREE from "https://threejs.org/build/three.module.js";

const loader = new THREE.FileLoader();
const resourceURI = "https://picsum.photos/200/300";

loader.load( resourceURI, object => {
  console.log("some stuff...");
  
  // Error inside onLoad callback
  throw new Error("encounter error");
  
  console.log("other stuff...");
});
```

***Live example***

* [jsfiddle](https://jsfiddle.net/e34n5zu2/1/)

**Expected behavior**
Display the real error when there are no callbacks to call.

**Screenshots**
![image](https://user-images.githubusercontent.com/39115827/144058627-b607d51b-fe93-45ac-a830-632ae5a78c0c.png)

**Comment by Mugen87** [comment]
So the issue is that internal `catch()` statement of `FileLoader` is executed when an error is thrown in the `onLoad()` callback. And it seems the mentioned `catch()` statement was not developed with this use case in mind.
