### ISSUE TITLE
135 version  GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete

### ISSUE THREAD

**Issue by x1911** [mrdoob/three.js#22935]
**Describe the bug**

in version  135 it shows this error sometimes, not everytime, but with version r 134 it works good

it happens in Mac and iOS

***Live example***

here is the link:
https://c3.dogfightx.com/test/

**Screenshots**
![image](https://user-images.githubusercontent.com/8219031/144406110-da997073-9d3b-4d89-8760-697a0727e59f.png)

**Platform:**

 - Device: Desktop, Mobile
 - OS: [MacOS Big Sur 11.5.2, iOS 13, iOS 14 ]
 - Browser: [Chrome, Safari]
 - Three.js version: [ r135 ]

**Comment by Mugen87** [comment]
Please don't share your entire app. Instead reproduce the issue with a small live example: https://jsfiddle.net/vy29n6aj/

Besides, please ask for help at the forum first. If it turns out to be a bug, we can reopen this issue.
