### ISSUE TITLE
NodeMaterial MathNode overload ARCTAN or create ARCTAN2

### ISSUE THREAD

**Issue by joergjaeckel** [mrdoob/three.js#22930]
**Is your feature request related to a problem? Please describe.**

There is no atan2 in the MathNode/Node System.

**Describe the solution you'd like**

In GLSL we use a two-argument overload for the atan function, which is equivalent to atan2. But the MathNode prevents passing more than one argument to the ARCTAN node. Is it better to allow more arguments or create a new node type? @sunag

**Comment by sunag** [comment]
@joergjaeckel I think that is better to allow more arguments because the way of `NodeMaterial` get the most similar to `GLSL` as possible.

**Comment by joergjaeckel** [comment]
Generally, would it be a good idea to create alias nodes for better programming/visual editor experience? In this case it would be VectorToRadial or similar. I think there should be such a node/kind of nodes in Unreal for example.

Can I just fix this topic by adding ARCTAN to the getNumInputs function? I try to understand nodes more and more and get into contributing.

**Comment by sunag** [comment]
> Generally, would it be a good idea to create alias nodes for better programming/visual editor experience?

Yes, it is good. I create a `TrigonometryEditor`, I think we could use it to add `arctan`?

![image](https://user-images.githubusercontent.com/502810/144744227-dc28afa4-90f8-4a08-8671-0ece3168084e.png)


> Can I just fix this topic by adding ARCTAN to the getNumInputs function?

It will be great.
