### ISSUE TITLE
NodeMaterial custom UV Mapping

### ISSUE THREAD

**Issue by joergjaeckel** [mrdoob/three.js#22958]
**Is your feature request related to a problem? Please describe.**

I want to have create or manipulate a UV map to fit a RingGeometry nicely. The math and GLSL way is clear but it seems to me there is no way to use Nodes input.
UVNode takes a UVTransformNode what sounds like the right place to do so. But this Node accepts only numeric input and no Nodes, same with Vector2Node for example? Don't know if I'm completly right with this and if there are good reasons why its like that.

**Describe the solution you'd like**

In GLSL we just use any vec2 value with the freedom of putting together two floats if we need so.

**Describe alternatives you've considered**

Stick it together in a FunctionNode. But we want Nodes to avoid GLSL 🙄  And further manipulation of mapping needs to be done in your custom GLSL function too. 

**Additional context**

To give you a clearer idea.
```
// radians remapped to 1 - 0
// distance from center remapped from inner/outer size of the ring to 0 - 1

return texture2D( uvTexture, vec2(radians, distance) );
```

![image](https://user-images.githubusercontent.com/9137061/144726552-8bae1648-0ebe-4a5a-81a0-58d582cfcbcf.png)

Mentioning @sunag

**Comment by sunag** [comment]
@joergjaeckel What `NodeMaterial` version you are using?

New - https://github.com/mrdoob/three.js/tree/dev/examples/jsm/renderers/nodes
Lagacy - https://github.com/mrdoob/three.js/tree/dev/examples/jsm/nodes

**Comment by mrdoob** [comment]
@sunag Should we remove legacy?

**Comment by joergjaeckel** [comment]
Oh, looks like I used the legacy and did not even registered theres a new place for nodes 🙄  We should start documentation soon, every example out there imports the old ones. To test the new UVNode for this problem takes me some time, need to rewrite everything. Same will happen to the node examples example https://threejs.org/examples/?q=nodes#webgl_materials_nodes ?

**Comment by sunag** [comment]
@mrdoob Yes, but first I need to add support to IBL and `serialization` in new `NodeMaterial` system mainly to `WebGL` version, I noticed in Twitter too devs still use the legacy version. I will focus more in this development in the next week.

**Comment by sunag** [comment]
@joergjaeckel if you use the legacy, It should be?
```js
const uv = new JoinNode( radians, distance );
```

**Comment by joergjaeckel** [comment]
@sunag thank you for everything! Legacy solution works but of course I want to use the new one in the future. I think I tried the JoinNode but didnt worked for some other reason.
