### ISSUE TITLE
Add .pow(exponent) and .multiplyByExponentiatedQuaternion(quat2, exponent) methods to the Quaternion class

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#22959]
**Is your feature request related to a problem? Please describe.**

Hello!
I want to be able to handle rotations in my engine in similar way to the positions - I can write `position.addScaledVector(velocity, timePassed)` if I want to program moving with some velocity frame-by-frame and I want to be able to do similar thing for quaternions (or at least thing similar to `position.add(velocity.clone().scale(timePassed))`), i.e. `rotation.multiplyByExponentiatedQuaternion(rotationalVelocity, timePassed)` (or `rotation.multiply(rotationalVelocity.clone().pow(timePassed))`).

**Describe the solution you'd like**

I suggest that methods `.pow(exponent)` and `.multiplyByExponentiatedQuaternion(quat2, exponent)` would be added to the Quaternion class.

**Describe alternatives you've considered**

These methods could be added just by monkey-patching the prototype of the Quaternion class (and it is how I do it currently).

**Additional context**

The methods could be implemented similar to glMatrix's `pow(out, a, b)` function: https://github.com/toji/gl-matrix/blob/master/src/quat.js#L280.

**Comment by Mugen87** [comment]
Would it be possible to [Quaternion.rotateTowards()](https://threejs.org/docs/index.html?q=quat#api/en/math/Quaternion.rotateTowards) for your use case? The first argument is the target orientation whereas the second one is the angular step (which you can easily compute based on the maximum turn rate in radians per second of your vehicles).

**Comment by LeviPesin** [comment]
Thank you! It is possible to write something like `rotation.rotateTowards( rotation.clone().multiply(rotationVelocity), ( new THREE.Quaternion() ).angleTo(rotationVelocity) * timePassed )`, but it will break if `timePassed` is greater than one.

**Comment by Mugen87** [comment]
Sorry, but I'm afraid I don't understand your use case and the motivation for the above computation. Do you mind sharing a simple live example based on [webgl_math_orientation_transform](https://threejs.org/examples/webgl_math_orientation_transform) that shows what you are actually doing in your app?

**Comment by LeviPesin** [comment]
It would be something like this: https://jsfiddle.net/r1xwb2o8/

**Comment by WestLangley** [comment]
@Mugen87 Conceptually, `quaternion.pow()` is the same as

```js
const _vec3 = new THREE.Vector3();
const _vec4 = new THREE.Vector4();

//

_vec4.setAxisAngleFromQuaternion( q );

q.setFromAxisAngle( _vec3.set( _vec4.x, _vec4.y, _vec4.z ), _vec4.w * alpha );
```
Add `pow()` if you want, if it can be made efficient. I would not support adding the other method.

**Comment by Mugen87** [comment]
Okay, that sounds good!

@LeviPesin Would you be willing to add `Quaternion.pow()`?

**Comment by LeviPesin** [comment]
Here it is: https://github.com/mrdoob/three.js/pull/22970

**Comment by WestLangley** [comment]
@LeviPesin FYI, avoid calling `.clone()` in tight loops. Create one instance and reuse it.

```js
//position.add( velocity.clone().scale( timePassed ) ) ) );

position.add( workingVec.copy( velocity ).scale( timePassed ) ) ) );
```

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/22970#issuecomment-991583290
