### ISSUE TITLE
CSS3DRenderer: Element con't be select/click/hit test at small scales on safari

### ISSUE THREAD

**Issue by Emiyaaaaa** [mrdoob/three.js#22964]
**Describe the bug**

CSS3DRenderer: Element con't be select/click/hit test at small scales on safari

**To Reproduce**

safari and CSS3DObject.scale.set(0.002, 0.002, 0.002)
after my test, just reproduce on scale small than 0.00215

**Platform:**

 - Device: MacBookPro 2020,  iphone12
 - OS: MacOS bigsur, iOS 15
 - Browser: Safari
 - Three.js version:  r117

**Comment by Mugen87** [comment]
I can reproduce the issue on macOS with Safari. Here is a fiddle with plain HTML/CSS/JS (you have to find the small red quad in the viewport first): https://jsfiddle.net/9yposagq/2/

It works in Chrome and Firefox though.

If others can reproduce the issue I can reported it here: https://bugs.webkit.org/

**Comment by Mugen87** [comment]
Filed an issue: https://bugs.webkit.org/show_bug.cgi?id=233917
