### ISSUE TITLE
Weird rendering with EffectComposer in v135

### ISSUE THREAD

**Issue by nkallen** [mrdoob/three.js#22967]
Somehow mostof my EffectComposers, which use WebGLMultisampleRenderTargets, have become broken with v135.

NOTE: this problem only occurs on windows. On my mac it is fine.

You can see from the picture that things are pixelated. It seems to me that some render target isn't being cleared, whether it's color or depth I'm not sure yet.

![Screenshot 2021-12-06 134538](https://user-images.githubusercontent.com/699/144848438-ce7fe21b-67fd-4f39-becc-b7e506aa2059.png)

I have custom Passes, but even using having two vanilla RenderPasses triggers the problem

I have narrowed it down to this commit using git bisect and (and rebuilding):

d16a6085ad

https://github.com/mrdoob/three.js/commit/d16a6085ad632d46139f2de042d583d42d3d1deb

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r???]

**Comment by Mugen87** [comment]
> I have narrowed it down to this commit using git bisect and (and rebuilding):

This is the respective PR: #22558

Any chances to share a live example that makes it possible to debug the issue? It seems the official multisampling demo does not show this issue: 

https://threejs.org/examples/webgl2_multisampled_renderbuffers

**Comment by nkallen** [comment]
![GIF 12-6-2021 2-01-40 PM](https://user-images.githubusercontent.com/699/144850608-d3241691-869e-470a-ba38-fc1847bf5045.gif)

I don't know if this video is any help ....

**Comment by nkallen** [comment]
To make a live demo may be difficult. This is an electron app. You can download an alpha of it here: https://github.com/nkallen/plasticity/releases/tag/v0.1.17

Again the problem is windows

**Comment by Mugen87** [comment]
Thanks, it's definitely more informative than a screenshot. But I'm afraid without the possibility of reproducing the issue on a local computer, it will be hard to investigate and fix it.

**Comment by nkallen** [comment]
I'll try to create a jsfiddle and see if i can reproduce, ...

**Comment by nkallen** [comment]
GOT IT!

https://jsfiddle.net/am79c6f2/

**Comment by nkallen** [comment]
![Screenshot 2021-12-06 145021](https://user-images.githubusercontent.com/699/144857634-be69f1e7-1296-471b-9783-9c7c72469893.png)

**Comment by WestLangley** [comment]
>Again the problem is windows

Your fiddle on M1 iMac macOS 12.0.1 Safari 15.1

<img width="833" alt="Screen Shot 2021-12-06 at 8 56 42 AM" src="https://user-images.githubusercontent.com/1000017/144858811-54b9de7c-4935-4444-acb7-dde830ff84cd.png">

**Comment by nkallen** [comment]
- It's fine on Mac intel I guess
 - It's not just outline pass. It seems to be any pass that isn't clearing color or depth or something

**Comment by Mugen87** [comment]
I can confirm that it works with `r134`. Seems this regression was introduced when the processing of multisampled render targets was refactored in #22558.

/cc @cabanier

**Comment by nkallen** [comment]
> Your fiddle on M1 iMac macOS 12.0.1 Safari 15.1

Yours looks like a mipmap ...

**Comment by cabanier** [comment]
> BTW: The fiddle is broken on Windows but works on macOS with Chrome and Firefox.

Maybe there's a bug when discarding the framebuffer aftter blitting it. I'll take a look.

**Comment by cabanier** [comment]
FYI it works fine on Windows Chrome but is broken on Edge.

**Comment by cabanier** [comment]
I verified it was caused by the introduction of [invalidateFramebuffer](https://github.com/mrdoob/three.js/blob/25c7f7a1c9349a652cc8fb0d7645593991756bf9/src/renderers/webgl/WebGLTextures.js#L1591). This looks like a browser bug because we discard the color pixels after copying them to another buffer.
@Mugen87 Is there conditional code to skip this call?

**Comment by cabanier** [comment]
This looks like it fixed the issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1234829
Maybe we just need to wait until Edge is updated and file a bug against Safari on M1?

**Comment by nkallen** [comment]
@cabanier I know my vote doesn't count for anything but I'd definitely prefer a workaround (or if impossible, a rollback). This is a showstopper for me ... And there is a bug fix on 135 that I would very much like to have.

**Comment by cabanier** [comment]
> @cabanier I know my vote doesn't count for anything but I'd definitely prefer a workaround (or if impossible, a rollback). This is a showstopper for me ... And there is a bug fix on 135 that I would very much like to have.
> 
> (Also fyi I'm using a several month old version of Electron where this came up)

If three.js has conditional code, we code disable that line on desktop.
I prefer not to remove it for mobile because that would force a pixel resolve which is costly.

**Comment by nkallen** [comment]
I would be ok with that ... Maybe three.js already has a policy on bugs/regressions like this on major platforms (m1+safari, windows+edge) ?

**Comment by cabanier** [comment]
> @cabanier The linked Chromium bug is a security issue. Do you know how this is related to multisampled rendertargets?

The bug fixes where angle didn't track the discard status of the framebuffer. This is a security issue but it also solves a timing issue with blitting,

> AFAICS, the only safe workaround right now is to avoid the usage of `WebGLMultisampleRenderTarget` and use a normal one, correct?

Yes. We *could* provide a temporary option that skips the discard.
@nkallen, just to be sure, does your problem go away when removing the invalidateFrameBuffer call?

**Comment by nkallen** [comment]
@cabanier Just to be clear, you want me to test commenting out gl.InvalidateFramebuffer in WebXRManager.js?

**Comment by cabanier** [comment]
> @cabanier Just to be clear, you want me to test commenting out gl.InvalidateFramebuffer in WebXRManager.js?

No, in WebGLTextures.js. This line: https://github.com/mrdoob/three.js/blob/25c7f7a1c9349a652cc8fb0d7645593991756bf9/src/renderers/webgl/WebGLTextures.js#L1591

**Comment by makc** [comment]
post more glitch art gifs, they are so good 😍

**Comment by nkallen** [comment]
@cabanier hey yes commenting out that line seems to fix the problem

**Comment by cabanier** [comment]
> @cabanier hey yes commenting out that line seems to fix the problem

@Mugen87 Should I put up a PR that lets the user opt out of the discard?

**Comment by Mugen87** [comment]
@mrdoob What do you think?

**Comment by mrdoob** [comment]
@cabanier Yeah, would be good to have a PR with whatever API you come up for it.

**Comment by JiDW** [comment]
FYI I have this issue with rev136 on Chrome 97 and Canary 99 on Windows, so it seems to be more spread than what is suggested here. I don't think the underlying browser bug has been fixed.

For someone who's merely a user and not skilled in WebGL, what kind of impact should I expect from disabling the "invalidateFramebuffer" line please? Thank you!

**Comment by cabanier** [comment]
> For someone who's merely a user and not skilled in WebGL, what kind of impact should I expect from disabling the "invalidateFramebuffer" line please? Thank you!

If you take it out, multisampled output will be a lot slower on mobile devices.

**Comment by tomfree** [comment]
I guess this may be related and may cover another aspect potentially since rendering in my case is a bit different from what is initially described in the post 
https://codepen.io/thogu/pen/ExwBQRp - v.136 with WebGLMultisampleRenderTarget -> results in black cubes on Chrome with Android is ok on Windows with Chrome
https://codepen.io/thogu/pen/xxXNBmV - v.136 with WebGLRenderTarget -> same results with Windows&Chrome and Android&Chrome
https://codepen.io/thogu/pen/jOGjZJL - v.134  WebGLMultisampleRenderTarget - same results with Windows&Chrome and Android&Chrome
Hope this helps

**Comment by cabanier** [comment]
I made a PR to make the invalidate optiona so certain UAs could disable itl: https://github.com/mrdoob/three.js/pull/22992
@mrdoob , I guess it was never merged :-\

**Comment by cabanier** [comment]
@tomfree can you check to make sure that removing `invalidateFramebuffer` fixes the problem on Android? I thought this was just an issue on M1 Safari.

**Comment by JiDW** [comment]
Just to confirm that removing invalidFrameBuffer also fixed the issue for me on windows Chrome. Thank you!

**Comment by tomfree** [comment]
> @tomfree can you check to make sure that removing `invalidateFramebuffer` fixes the problem on Android? I thought this was just an issue on M1 Safari.

Tested it however also with that chagne it doesn't work. Here the steps I did in two approaches since I am not so confident and I dont wanna waste your time when I just might have made a mistake

1.) Just changed the line in WebGLTextures.js in my node_modules and rebuild my project -> no change

2.)
a.) Clone Three Repo 
b.) Change line in WebGLTextures.js and run build
c.) copy the contents of build folder to my project structure three/build 
d.) rebuild my project 
-> Again no change on this matter unfortunately

**Comment by edankwan** [comment]
I noticed that the upgrading from v134 -> v135, the depthTexture attached to WebGLMultisampleRenderTarget won't work anymore.

**Comment by Mugen87** [comment]
> I noticed that the upgrading from v134 -> v135, the depthTexture attached to WebGLMultisampleRenderTarget won't work anymore.

Should be fixed with `r138.3`.  Note that `WebGLMultisampleRenderTarget` has been removed. Multisampling now works by setting `WebGLRendererer.samples`.

Apart from that, I can still produce the original issue on Windows 10 with latest Chrome and Edge.

**Comment by mrdoob** [comment]
@rcabanier What's the status of this? Chrome Windows and Chrome Android is supposed to get a fix soon, right?

**Comment by nkallen** [comment]
I don't know if this works in 138, but I've been on my own fork with some of @cabanier 's code, using skipInvalidateFramebuffer: true, and this works

**Comment by JiDW** [comment]
138 has the same issue, yes. I'm on my own fork too.

**Comment by cabanier** [comment]
> @rcabanier What's the status of this? Chrome Windows and Chrome Android is supposed to get a fix soon, right?

It seems that the angle patch should be in Chrome Windows and Android by now. Maybe it's time to file a bug?

**Comment by mrdoob** [comment]
Oh no 😟

**Comment by Mugen87** [comment]
I've file a new bug: https://crbug.com/1304758

**Comment by mrdoob** [comment]
This should be fixed now: https://github.com/mrdoob/three.js/pull/23692

**Comment by WestLangley** [comment]
@mrdoob yay! https://jsfiddle.net/m6g1329q/

@Mugen87 I noticed the three.js example fiddles do not support import maps yet. The above link shows one way to do it.

**Comment by mrdoob** [comment]
@cabanier what do you think of @kenrussell's [comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1304758#c2)?

> Is Three.js clearing the multisampled renderbuffer at the beginning of the next frame, after invalidating it at the end of the previous frame? If not - that is an application bug in Three and must be fixed. The contents of the invalidated framebuffer are defined by the WebGL 2.0 specification as either being cleared to black, or the previous contents. See https://www.khronos.org/registry/webgl/specs/latest/2.0/#5.29.

**Comment by cabanier** [comment]
I'm unsure. Doesn't three start drawing by clearing the framebuffer?

**Comment by mrdoob** [comment]
Yes. 

Have not gone into the code yet, but maybe `__webglMultisampledFramebuffer` is not bound at clearing time?

If so... Does this mean that the bug is actually in Oculus Browser?

**Comment by cabanier** [comment]
No. The buffer that is invalidated is created and managed by three.

**Comment by mrdoob** [comment]
Ken is saying the artifacts are because we're not clearing the buffer. Shouldn't Oculus Browser show artifacts too?

**Comment by cabanier** [comment]
> Ken is saying the artifacts are because we're not clearing the buffer. Shouldn't Oculus Browser show artifacts too?

I think it's implementation dependent what is in the buffer after you invalidate it.

**Comment by kenrussell** [comment]
To clarify - I'm not sure yet where the artifacts are coming from. There may well be bugs in the browser or drivers causing this behavior. However, if Three.js weren't clearing the framebuffer at the start of drawing - that might explain the behavior on Windows.

We'll investigate this more on the browser side in http://crbug.com/1304758 . Thanks for reporting it and for the self-contained test case.
