### ISSUE TITLE
Restore DeviceOrientationControls to "experimental" folder

### ISSUE THREAD

**Issue by dstults** [mrdoob/three.js#22996]
## The Issue

DeviceOrientationControls works with most devices and is fun to play with, but now it's gone.

## The Solution

Restore most recent version into "experimental" folder, maybe with comment at top why it's experimental and/or estimated scope of incompatibility.

## Alternatives

Keep deleted. Get identical code from older versions or similar code from elsewhere.

## Additional Context

Three.js is an industry standard and simply having a known, good DeviceOrientationControls in the official repo will encourage devices to not break things in future without good reason.

Removing PR: https://github.com/mrdoob/three.js/pull/22654
Related Issue(s):
- https://github.com/mrdoob/three.js/issues/22613#issuecomment-931995086
- https://github.com/mrdoob/three.js/issues/15828

**Comment by Mugen87** [comment]
I do not vote to restore the class since the `experimental` directory was intended as place for code that will be used in the future. That is not true for `DeviceOrientationControls` and the underlying API.

It should be no problem for users to restore the code from the #22654 if they need the class for their applications.

**Comment by dstults** [comment]
I guess the real trouble of finding the class from said PR is not knowing that it once existed. I guess hopefully this will be at least one more breadcrumb for people to follow.

Thanks for your feedback, that makes perfect sense.

**Comment by WestLangley** [comment]
>It should be no problem for users to restore the code from the #22654 if they need the class for their applications.

I do not think we should _ever_ suggest users include files from different releases of the library.

I think it is best to say the owner chooses to no longer support the feature.

If someone offers to host the file elsewhere -- and maintain it -- that would be ideal.

**Comment by dataexcess** [comment]
If I'd want to integrate DeviceOrientationControls in my current project.. Where can I get it from?
Thnx

**Comment by LeviPesin** [comment]
You can find it here: https://github.com/mrdoob/three.js/blob/1ee2fca970e3afdc26e6c2a47c14e9e2b784ae48/examples/jsm/controls/DeviceOrientationControls.js

**Comment by dataexcess** [comment]
> You can find it here: https://github.com/mrdoob/three.js/blob/1ee2fca970e3afdc26e6c2a47c14e9e2b784ae48/examples/jsm/controls/DeviceOrientationControls.js

Thank you! 🙏
