### ISSUE TITLE
Three js Expo Three : Example Model Loaders giving [TypeError: undefined is not an object (evaluating 'response.body.getReader')] error in react-native

### ISSUE THREAD

**Issue by AlanSmithGit** [mrdoob/three.js#23011]
I am trying to use three js and expo-three to load 3D models in mobile apps.
But every time I run a particular loader from " three/examples/jsm/loaders/ ..... " I get an error " [TypeError: undefined is not an object (evaluating 'response.body.getReader')] " and the 3d model fails to load. 
I have tried GLTFLoader ( import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader" ) and also OBJLoader ( import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader') and others but all giving the same " TypeError: undefined is not an object " error. 
I am using three ( v 0.135 ), expo-three ( 6.0.1 ), expo-gl ( 11.0.3), expo ( 43.0.2 ), react ( 17.0.1 ) and react-native ( 0.64.3 ). 

1. Create an expo app 
2. yarn add  three expo-three expo-gl
3. expo eject ( to convert to bare react native app)
4. In App.js add the necessary imports
5. Add 3D models ( like I used .obj file and .gltf file ) 
6. import OBJLoader and GLTFLoader from three examples in App.js
7. Run the code and it produces the error
8.

 Below is the App.js code: 
=================================

import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { PixelRatio } from 'react-native';
import ExpoTHREE, { Renderer, THREE } from 'expo-three';
import { GLView } from 'expo-gl';
import { ExpoWebGLRenderingContext } from 'expo-gl';
import { PerspectiveCamera, AmbientLight, Scene, MeshPhongMaterial, MeshBasicMaterial } from 'three';
import { TextureLoader } from 'expo-three';
import { STLLoader } from 'three/examples/jsm/loaders/STLLoader';
import { Asset } from 'expo-asset';
import RNFetchBlob from 'rn-fetch-blob';
import * as RNFS from 'react-native-fs';
import resolveAssetSource from 'react-native/Libraries/Image/resolveAssetSource';
import { decode, encode } from 'base-64';
import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader';
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export default function App() {

  return (
    <View style={styles.container}>
      {/* <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" /> */}
      <GLView style={{ width: 500, height: 500 }} onContextCreate={onContextCreat} />
    </View>
  );
}

const onContextCreat = async (gl) => {

  const { drawingBufferWidth, drawingBufferHeight } = gl;
  const scale = PixelRatio.get()

  // Create a WebGLRenderer without a DOM element

  const renderer = new Renderer({ gl });
  renderer.setSize(drawingBufferWidth / scale, drawingBufferHeight / scale);
  renderer.capabilities.maxVertexUniforms = 52502;
  renderer.setPixelRatio(scale);
  renderer.setClearColor(0x0c000);

  const scene = new Scene();
  const camera = new PerspectiveCamera(75, drawingBufferWidth / drawingBufferHeight, 0.1, 1000);
  camera.position.set(0, 2, 5);

  const ambientLight = new AmbientLight(0x101010);
  scene.add(ambientLight);

  const geometry = new THREE.BoxGeometry(1, 1, 1);

  const imageURI = Asset.fromModule(require('./assets/icon.png')).uri;

  const material = new THREE.MeshBasicMaterial({
    map: new TextureLoader().load(imageURI),
  });

  const cube = new THREE.Mesh(geometry, material);
  scene.add(cube);

 

  const asset = Asset.fromModule(
    require("./assets/v_knife_karam/v_knife_karam.gltf")
  );
  await asset.downloadAsync();

  const loader = new GLTFLoader();

  loader.load(
    asset.uri,
    (gltf) => {
      scene.add(gltf.scene);
    },
    (xhr) => {
      console.log(`${(xhr.loaded / xhr.total) * 100}% loaded`);
    },
    (error) => {
      console.error("An error happened", error);
    }
  );

  
  // const assets = Asset.fromModule(require('./assets/IronMan.obj'));
  // await assets.downloadAsync();

  // //instantiate a loader
  //  const loader = new OBJLoader();

  //    loader.loadAsync(assets.uri,function ( xhr ) {

  //     console.log( ( xhr.loaded / xhr.total * 100 ) + '% loaded' );

  // }).then((object)=> {
  //   console.log(`async load of 3d obj: ${object}`)
  // }).catch((err) =>{
  //   console.log(`the async load object error: ${err}`)
  // })

  renderer.render(scene, camera)
  gl.endFrameEXP()

}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

=====================================

Error produced in Simulator:

![Simulator Screen Shot - iPhone 12 - 2021-12-13 at 12 00 59](https://user-images.githubusercontent.com/96042167/145772107-cde7501d-b7db-4bbb-a994-d6e43ffae7c0.png)

Console Error Log:

<img width="932" alt="Screenshot 2021-12-13 at 12 24 08 PM" src="https://user-images.githubusercontent.com/96042167/145772138-1e6c6f83-4d43-4bf3-8b66-c160a7afe57d.png">

* Platforms tested on : *
Mobile - iPhone
OS: iOS, MacOS
Three.js version 0.135.0
expo-three version  6.0.1 
expo-gl version 11.0.3
expo version 43.0.2 
react version 17.0.1 
react-native version 0.64.3  

package.json screenshot

<img width="585" alt="Screenshot 2021-12-13 at 12 13 45 PM" src="https://user-images.githubusercontent.com/96042167/145772158-1c923956-742f-420f-a9de-a771a18e53d8.png">

* Have been stuck on this issue since last many days so an urgent response and help would be highly appreciable. *

**Comment by Mugen87** [comment]
Sorry, but GitHub is not intended for help requests. Please use stackoverflow or the [forum](https://discourse.threejs.org/).

**Comment by AlanSmithGit** [comment]
but this is a bug

**Comment by AlanSmithGit** [comment]
> Sorry, but GitHub is not intended for help requests. Please use stackoverflow or the [forum](https://discourse.threejs.org/).

But this is a Bug

**Comment by CodyJasonBennett** [comment]
This is related to #22510 where FileLoader swapped over to the fetch API, but there is no fallback for environments that don't support streaming.

I outline how polyfills that aren't 1-1 with the fetch spec can clash in https://github.com/mrdoob/three.js/pull/22510#issuecomment-956314115 and how that pertains to native.
