### ISSUE TITLE
ArcballControls steals ctrl-C/V keyboard shortcuts

### ISSUE THREAD

**Issue by mgroeneweg** [mrdoob/three.js#23023]
**Describe the bug**

ArcballControls has the ability to copy/paste state. It also allows ctrl-C/V keyboard shortcuts to be used for that purpose.

We have a business app that shows a model on the right and a treeview of that model and other details on the left. Having the ArcballControls active prevents regular copy/paste actions on the input elements that are on the same page.

This can also be seen in the example.
[https://threejs.org/examples/?q=arcb#misc_controls_arcball](https://threejs.org/examples/?q=arcb#misc_controls_arcball)

**To Reproduce**

1. Go to [https://threejs.org/examples/?q=arcb#misc_controls_arcball](https://threejs.org/examples/?q=arcb#misc_controls_arcball)
2. Click on `Scale factor` in the `Controls UI`.
3. Use ctrl-C to attempt to copy the value
4. Use ctrl-V in any text editor
5. You will get the controls state rather than the scale factor value

***Code***

```js
// code goes here
```

***Live example***

* [https://threejs.org/examples/?q=arcb#misc_controls_arcball](https://threejs.org/examples/?q=arcb#misc_controls_arcball)

**Expected behavior**

One of:
* The Arcball state functionality should not interfere with other elements on the page
* Provide a property to turn off the keyboard shortcuts so ArcballControls does not capture the keystrokes.

**Screenshots**
![image](https://user-images.githubusercontent.com/6723899/146002966-d7ba3df0-1707-428d-b37a-807cbadedff8.png)
Scale factor selected for copying.

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: [0.135.0]

**Comment by Mugen87** [comment]
I vote to remove the `keydown` event listener. `copyState()` and `pasteState()` are part of the public API. If users really need this kind of reset functionality, they can implement the following on app level.
```js
window.addEventListener( 'keydown', function( event ) {

	if ( event.key == 'c' ) {

		if ( event.ctrlKey || event.metaKey ) {

			controls.copyState();

		}

	} else if ( event.key == 'v' ) {

		if ( event.ctrlKey || event.metaKey ) {

			controls.pasteState();

		}

	}

} );
```

**Comment by mgroeneweg** [comment]
Of course removing the keydown listener would solve the issue for me but that would mean a (small) breaking change. I would be perfectly happy to add a parameter value to the constructor to prevent adding the listener.

**Comment by mgroeneweg** [comment]
That was quick! Thanks!
