### ISSUE TITLE
GLTFLoader  cannot  set material  opacity

### ISSUE THREAD

**Issue by chenlinming** [mrdoob/three.js#23020]
for(let mesh of gltf.scene.children){
            mesh.material.transparent = true;
            mesh.material.opacity = 0.5;
        }
invalid

**Comment by donmccurdy** [comment]
Sorry for the trouble, we're working on this. There's a longer discussion in https://github.com/mrdoob/three.js/issues/22598 so I'll close this issue as a duplicate. The workaround for now is to also set `mesh.material.format = THREE.RGBAFormat`.
