### ISSUE TITLE
Remove instanceMatrix requirement for instanced mesh rendering

### ISSUE THREAD

**Issue by tim-depthkit** [mrdoob/three.js#23056]
**Is your feature request related to a problem? Please describe.**

There appears to be no way to invoke an instanced draw call without supplying a transformation matrix _per instance_. This feels unnecessarily restrictive, as one may want to use other attributes to determine the transformation per-instance, such as computing a transformation procedurally in the vertex shader via the gl_InstanceID or some other method.

**Describe the solution you'd like**

I feel the current API for instanced meshes is too opinionated about how one may want to use instanced drawing, and is overly restrictive in some cases. I would prefer that there be no hard requirement to have specific attributes set for instanced drawing, especially the current requirement of matrices per-instance which are quite data heavy.

**Describe alternatives you've considered**

The only alternative is to not use instanced drawing which would result in more draw calls than are necessary, or to upload unnecessary data to the GPU as a work-around.

**Comment by WestLangley** [comment]
>The only alternative is to not use instanced drawing

Actually, the natural alternative would be to use `THREE.InstancedBufferGeometry` directly.

**Comment by donmccurdy** [comment]
Some alternatives are possible with NodeMaterial as well. But for the example given ("computing a transformation procedurally in the vertex shader") I think InstancedBufferGeometry is probably best.

**Comment by tim-depthkit** [comment]
> Actually, the natural alternative would be to use `THREE.InstancedBufferGeometry` directly.

Great, I'm glad to know it should be possible by working with the InstancedBufferGeometry directly. Unfortunately the documentation does not provide any examples for how to use InstancedBufferGeometry directly. I was not able to get anything to appear when I tried to do this, but I will take another stab at it now that I know it should be possible.

**Comment by donmccurdy** [comment]
One example here: [code](https://github.com/donmccurdy/three-shadenodeloader/blob/7a0ca931ec17f048942eb3e5141f4fb8247fd156/index.html#L307-L322), [demo](https://three-shadenodeloader.donmccurdy.com/).

**Comment by tim-depthkit** [comment]
Thank you! this is very helpful

**Comment by tim-depthkit** [comment]
Based on your example code I was able to get something rendering, thank you!

I see in your example that you're specifying the `instanceID` attribute. Ideally we'd be able to use the built in `gl_InstanceID` attribute without creating a redundant instanced attribute. I managed to get this working, however I had to explicitly set the `_maxInstanceCount` property on the geometry object to be the same as the `instanceCount`.

It seems that this property is only automatically computed in the case that at least one instanced attribute is specified. I take it based on the underscore prefix that I should not be setting this property as a user of the API. I think this could be considered either a bug or deficiency of the API.

**Comment by Mugen87** [comment]
`gl_InstanceID` is only available when you write your shaders with GLSL 3.0. The following example demonstrate the usage:

https://jsfiddle.net/uaz0xgtw/3/

Also notice that no properties of `InstancedBufferGeometry` (meaning `instanceCount` or `_maxInstanceCount `) have to  be defined in order to use `gl_InstanceID`.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.
