### ISSUE TITLE
[VR] threejs-based VR experiences go into a bad state and never recover in some cases

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#23058]
**Describe the bug**

It seems that something might not be quite correct with the way threejs VR works: after repeatedly entering/exiting VR via the VRButton, the VR image is "stuck" on a single frame and doesn't recover until browser restart (page refresh is not enough).
Its unclear to me how to trigger this with 100% repro rate, but one way to do that is to refresh the page while in VR.

**To Reproduce**

1. Attach Oculus Quest 2 via Link and enable Link
1. Go to https://threejs.org/examples/#webxr_vr_dragging in Chrome (96.0.4664.110)
2. Click on "Enter VR"
3. VR should work
4. While still in VR (headset on head), refresh the page (F5), VR exits
5. click on "Enter VR"
6. Note that you only get a single frame with timewarping. _< This is the bug, the following shows more conditions and info_
7. Click on "Exit VR"
8. Click on "Enter VR", same behaviour
9. Click on "Exit VR"
9. Refresh the page
10. Click on "Enter VR"
11. Note that it works
12. Click on "Exit VR"
13. Click on "Enter VR"
14. Note that it's now broken despite no inbetween page refresh
15. This will stay until a browser full restart (not just the page)

**Live example**

https://threejs.org/examples/#webxr_vr_dragging

**Expected behavior**

Expected is the same behavior as on https://immersive-web.github.io/webxr-samples/inline-session.html, where I wasn't able to ever reproduce this.

**Screenshots**

![20211220-210454](https://user-images.githubusercontent.com/2693840/146826022-7dba572b-e1ad-4baf-a7a2-52b271f06215.gif)

**Platform:**

 - Device: [Desktop + Quest 2 + Link, desktop machine(s): 2070 RTX, 3080 RTX, 3070 RTX]
 - OS: [Windows 10]
 - Browser: [Chrome]
 - Three.js version: [dev]

**Additional info:** when the page is in the "broken state" as seen in the GIF above, closing the tab results in a full Chrome crash like 50% of the time. I'm not sure if a bug in three alone can cause this behaviour.

**Additional info, part 2:** To me it seems like the behaviour is also dependant on order of operations: when the VR headset is already on the user's head (e.g. the sensor covered), the "chance of this going wrong" is higher than when the sensor is not covered, "Enter VR" is selected and then the headset is put on.

CC @cabanier, to me some of the above (Chrome crashes, dependence on user presence sensor) sound like worth investigating on the hardware/runtime level

Maybe also @toji for the random Chrome crash when closing a tab while in VR.

**Comment by hybridherbst** [comment]
@cabanier any ideas? This makes WebXR development on Desktop in threejs pretty cumbersome (needs constant browser restarts, sometimes browser crashes)

**Comment by cabanier** [comment]
I'll forward this issue to our team that works on the OpenXR runtime for PC.

**Comment by hybridherbst** [comment]
@mrdoob I _think_ this is a threejs-related issue so I think the issue should stay open - as written in the description this works fine in https://immersive-web.github.io/webxr-samples/inline-session.html but breaks in threejs.

**Comment by cabanier** [comment]
The fact that you need to restart the browser points to a runtime issue, not a problem with three.js

**Comment by hybridherbst** [comment]
I'm just concerned that when this issue is closed there's no way for others to see that this is an issue when using threejs right now (compared to using another engine that doesn't have this issue), and no way to follow progress on this.

Is there another repo/place to link to?

**Comment by cabanier** [comment]
@toji We looked into this and this seems to be a problem on the chromium side. When the failure occurs, we stop getting calls from Chrome.
We can also repro with Rift which has a different runtime.

**Comment by johnkearney** [comment]
I've looked into this from the Oculus PC Runtime side. I've been able to replicate the issue with Link and with Rift S (I didn't try Rift but I suspect it would replicate with any headset using our runtime). When I could replicate the issue, it seems liked we stopped getting most calls from Chrome (except xrPollEvent calls) - @toji could there be some state cached between refreshes here?

**Comment by hybridherbst** [comment]
@cabanier @johnkearney we're finding more issues/bugs/strangeness with the Oculus Browser on Quest, related to color spaces, hand tracking, crashes, sessiongranted, ... Is there a good place to contact you that doesn't clutter the threejs repo? From past experience the Oculus Developer Hub bug reporting nor posting in the Oculus dev forums seem to have any effect.

**Comment by cabanier** [comment]
The dev forums *should* work as we check those.
Most of us are on the WebXR discord and can provide support there.

**Comment by hybridherbst** [comment]
Any news on this? @toji / @johnkearney
