### ISSUE TITLE
Hopf torus parametric geometry

### ISSUE THREAD

**Issue by stla** [mrdoob/three.js#23067]
During [this discussion](https://github.com/mrdoob/three.js/pull/23065), @Mugen87 and me proposed to add the Hopf torus in the built-in parametric geometries. I'm going to do a PR.

### References

- [The Hopf torus of the tennis ball curve](https://laustep.github.io/stlahblog/posts/HopfTorusTennisBall.html)
- [Back to the parametric Hopf torus](https://laustep.github.io/stlahblog/posts/HopfTorus2.html)

**Comment by Mugen87** [comment]
No need to file a separate issue for this.

**Comment by stla** [comment]
Sorry, this was to have a reference issue for the PR, and also in case someone wants to discuss about it.
