### ISSUE TITLE
ERROR: too many uniforms

### ISSUE THREAD

**Issue by ZengRun** [mrdoob/three.js#23073]
**Describe the bug**

HREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Program Info Log: invalid shaders�
VERTEX

ERROR: too many uniforms

**To Reproduce**

Load the attached glb file will get this error。
But an open source application( https://github.com/Adjam93/threejs-model-viewer ) using the old version Threee.js can render the model successfully.

***Code***

***Live example***

**Expected behavior**

Render the glb model successfully

**Screenshots**

<img width="726" alt="企业微信截图_49f47bd4-d58b-45c7-8140-bc8252492ab6" src="https://user-images.githubusercontent.com/10266846/147184692-ceeee2ba-c38b-4e63-a6c3-f8c6bd0b3e9d.png">

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Chrome]
 - Three.js version: [0.135.0]
[mm_project.glb.zip](https://github.com/mrdoob/three.js/files/7766542/mm_project.glb.zip)

**Comment by mrdoob** [comment]
We use GitHub issues to track confirmed bug reports and feature development.
If you need help, please use the [forum](https://discourse.threejs.org/), the [chat](https://discord.gg/HF4UdyF) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
