### ISSUE TITLE
Memory release.

### ISSUE THREAD

**Issue by luzh0422** [mrdoob/three.js#23078]
Why can't we add a destruction method to Scene to empty the entire tree? 

In this way, there is no need to destroy each object one by one

**Comment by Mugen87** [comment]
The engine can't safely assume that materials and geometries are used in other scenes. So this task needs to be implemented on app level. I suggest you read the following thread at the forum for more information about this topic:

https://discourse.threejs.org/t/when-to-dispose-how-to-completely-clean-up-a-three-js-scene/1549
