### ISSUE TITLE
webgl_loader_ldraw.html has strange "black piece".

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#23085]
**Describe the bug**

In #22957 see strange "black piece" like screenshot. I am not sure it is bug.

**To Reproduce**

1. Run `git reset --hard 2a3e413f93dbedd431718aa0943bad0074df9005` in CMD.
2. Open `http://localhost:8080/examples/#webgl_loader_ldraw` in Browser.
3. See strange "black piece" like screenshot.

**Screenshots**

<img width="830" alt="1" src="https://user-images.githubusercontent.com/23699926/147356344-8318deaf-bfd7-487c-9e66-446e5bb6c81a.png">

**Platform:**

 - Device: [Desktop]
 - OS: [Windows11]
 - Browser: [Chrome96, Edge96]
 - Three.js version: [dev #22957]

**Comment by Mugen87** [comment]
BTW: On `dev` the progress bar looks like so:

![image](https://user-images.githubusercontent.com/12612165/147357492-248e3d8c-a556-41a3-a3a8-1b928ffc1412.png)

It looks fine in `prod`. Seems the calculation broke at some point in this dev cycle.

**Comment by Mugen87** [comment]
I can't see the mentioned dark pieces on `dev`:

https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_loader_ldraw.html

**Comment by gero3** [comment]
> BTW: On `dev` the progress bar looks like so:
> 
> ![image](https://user-images.githubusercontent.com/12612165/147357492-248e3d8c-a556-41a3-a3a8-1b928ffc1412.png)
> 
> It looks fine in `prod`. Seems the calculation broke at some point in this dev cycle.

It is just githack that sends the mpd file in gzip compression while threejs.org doesn't send it compressed. The calculation stayed the same.

**Comment by mrdoob** [comment]
@Mugen87 

> I can't see the mentioned dark pieces on dev using Chrome on macOS:
> 
> https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_loader_ldraw.html

I can in Chrome on macOS 🤔

<img width="1243" alt="Screen Shot 2021-12-24 at 11 59 42 AM" src="https://user-images.githubusercontent.com/97088/147365917-6df8b653-f221-4119-a35d-d99e8222e7d6.png">

**Comment by gkjohnson** [comment]
I see this too -- looks like it's related to normal smoothing because it disappears when you disable that setting.
