### ISSUE TITLE
Box3.SetFromObject() does not always return the minimal AABB

### ISSUE THREAD

**Issue by huangyulin** [mrdoob/three.js#23083]
**Is your feature request related to a problem? Please describe.**

When I load a model, I find that the rotation of all objects is 0, but the model rotates. At this time, the box selection range displayed by boxhelper is much larger than the actual area of the model. The evidence shows that the actual angle of the model is deflected. If the rotation of the model is modified by the program, I find that the box selection range of boxhelper will be larger. After verification, import the model into 3DMAX, adjust the model angle, reset it with resetxform, and then use boxhelper to box it for normalization. I want to know if threejs has a function like resetxform in 3DMAX
![image](https://user-images.githubusercontent.com/16285625/147337066-b552538a-78fb-41c0-ba7c-c9018b7e39ab.png)
![1](https://user-images.githubusercontent.com/16285625/147337345-a2c3c21d-4cb9-4339-93da-9a191ba84a1a.png)
![2](https://user-images.githubusercontent.com/16285625/147337348-6ba8d3bc-27cd-4348-8b0a-db4c4de22531.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mugen87** [comment]
Please write your post in English. It can then be reopened.

**Comment by WestLangley** [comment]
I assume this will be reopened...

For computational efficiency, the computed AABB may be larger than the minimal AABB.

Here is a similar example.

```js
const geometry = new THREE.PlaneGeometry( 10, 10 );
geometry.rotateX( - Math.PI / 2 );
geometry.rotateZ( - Math.PI / 4 ); // rotate geometry

mesh = new THREE.Mesh( geometry, new THREE.MeshBasicMaterial( { color: 0x0080ff, side: THREE.DoubleSide } ) );
mesh.rotation.set( 0, 0, Math.PI / 4 ); // apply inverse rotation to mesh
scene.add( mesh );

const helper = new THREE.Box3Helper( new THREE.Box3().setFromObject( mesh ), 0xffff00 );
scene.add( helper );
```

<img width="704" alt="Screen Shot 2021-12-24 at 11 19 07 AM" src="https://user-images.githubusercontent.com/1000017/147364658-b17cd632-a548-4afd-9655-3da100b803b7.png">


related: #20024

**Comment by huangyulin** [comment]
After two angle flips, the plane looks horizontal, but the range calculated by box3 is the range after two angles. I want to know how to get the horizontal time range. Do you have a good way

**Comment by WestLangley** [comment]
@huangyulin #20024 adds support for `Box3.setFromObject( object, minimalAABB ) `, which should produce the correct answer for your use case.

>I want to know if threejs has a function like resetxform in 3DMAX

I am not familiar with 3ds Max. Maybe someone else can answer...

**Comment by huangyulin** [comment]
> @huangyulin #20024 adds support for `Box3.setFromObject( object, minimalAABB ) `, which should produce the correct answer for your use case.
> 
> > I want to know if threejs has a function like resetxform in 3DMAX
> 
> I am not familiar with 3ds Max. Maybe someone else can answer...

Do you know the difference between expandByObject  and setFromObject? I tested them and got the same results

**Comment by WestLangley** [comment]
>Do you know the difference between expandByObject and setFromObject?

https://github.com/mrdoob/three.js/blob/1a241ef10048770d56e06d6cd6a64c76cc720f95/src/math/Box3.js#L112-L118

**Comment by huangyulin** [comment]
Thank you for your contribution. A parameter has been added to expandbyobject in box3, whether to calculate the minimum boundary range; The problem of my premise is solved perfectly; Thank you for your contributions
