### ISSUE TITLE
OrbitControls: Rendering on Demand when `controls.enableDamping = true`.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#23090]
**Is your feature request related to a problem? Please describe.**

Animation loop is unnecessery when `OrbitControls.enableDamping = true` in some three.js examples.

**Describe the solution you'd like**

Rendering on demand when `OrbitControls.enableDamping = true`.

**Describe alternatives you've considered**

It is not the best way to resolve damping animation;

```javascript
const controls = new OrbitControls( camera, renderer.domElement );

// animation need scene and renderer
controls.setScene( scene );
controls.setRenderer( renderer );

// Call damping animation when `orbitControls.enableDamping = true` in OrbitControls.update() function.
```

**Additional context**

https://github.com/mrdoob/three.js/pull/23088

**Comment by looeee** [comment]
I don't know of any way to do this with OrbitControls, but you can do with with @yomotsu's [CameraControls](https://www.npmjs.com/package/camera-controls) since the `CameraControls.update` method will return true if any actual update occurred, and false otherwise. 

``` js
import * as THREE from 'three';
import CameraControls from 'camera-controls';

CameraControls.install({ THREE: THREE });

const clock = new THREE.Clock();
const controls = new CameraControls(camera, renderer.domElement);

function animate () {
	const delta = clock.getDelta();
	const controlsDidUpdate = controls .update(delta);

	requestAnimationFrame(animate);

	if ( controlsDidUpdate) {
		renderer.render(scene, camera);
	}
};

animate()
```

CameraControls works in a similar manner to OrbitControls so it's usually easy to switch over.

**Comment by Mugen87** [comment]
> since the CameraControls.update method will return true if any actual update occurred, and false otherwise.

`OrbitControl.update()` returns a boolean which indicates whether the camera's transformation has been changed or not.

**Comment by Mugen87** [comment]
@sciecode I have an animation loop that I used for updating `OrbitControls`(with damping enabled). The scene gets rendered only when `OrbitControls.update()` returns true. That works fine when rotating and panning the camera but not when dolly in/out. Zooming with orthographic cameras shows the same issue.

Live demo: https://jsfiddle.net/c5rk18zj/2/

Do you know what's going on?

**Comment by Mugen87** [comment]
@sciecode I have an animation loop that I used for updating `OrbitControls`(with damping enabled). The scene gets rendered only when `OrbitControls.update()` returns `true`. That works fine when rotating and panning the camera but not when dolly in/out. Zooming with orthographic cameras shows the same issue.

Live demo: https://jsfiddle.net/c5rk18zj/2/

Do you know what's going on?

**Comment by sciecode** [comment]
I do know what's happening actually.

All motions pan/rotate/zoom are dispatched once the underlying event triggers, so the camera changes immediately. However, only rotate and pan have built-in systems that respond to dampening.

This means the `controls.update` will only return true for actions updating based on remaining dampening response. Which in turns makes it unresponsive to the zoom action alone. 

If instead we listen to the `change` event to control rendering, all actions will respond appropriately.

[https://jsfiddle.net/a4jex3wb/](https://jsfiddle.net/a4jex3wb/)

**Comment by Mugen87** [comment]
Thanks for the explanation! Your fiddle solves my issue and I think it's a valid approach for all devs who want to do the same with `OrbitControls` like the OP.
