### ISSUE TITLE
VTF morph targeting with multiple meshes sharing same position/normal attributes

### ISSUE THREAD

**Issue by 0b5vr** [mrdoob/three.js#23095]
### Describe the bug

Context: I'm a contributor of VRM, which is a humanoid-oriented glTF extension which is intended to be used as humanoid avatars.

I noticed vram consumptions of glTF models are increasing starting from Three.js r133, sometimes loading single humanoid glTF is enough to knock-off my WebGL context.
I compared between r132 and r133 using [greggman/webgl-memory](https://github.com/greggman/webgl-memory) and and I spotted an unforgivable difference at the texture memory consumption between them.
(I can't provide the model I used for the experiment since reasons, I'm sorry)

![image](https://user-images.githubusercontent.com/7824814/147446227-1472c04f-f7eb-4b42-9e17-d9004b19c275.png)

r133 has a big improvement on morph targeting part, enabling using 8 or more morph targets at the same time using VTF morph targeting (I mean, I appreciate this change a lot).
https://github.com/mrdoob/three.js/pull/22293

I've looked into the code behind the VTF morph targeting, and I noticed that, despite the model shares a single position/normal attributes between meshes the morph target textures are generated for each meshes.

https://github.com/mrdoob/three.js/blob/1a241ef10048770d56e06d6cd6a64c76cc720f95/src/renderers/webgl/WebGLMorphtargets.js#L53-L156

I can blame the structure of model itself of course, since it should have only necessary part of VBOs for each meshes plus morph targets should only be applied to necessary parts, but since the issue does not happen in r132 or prior, I want to fix this from Three.js side.

I think I can try to fix this part.

### Tangential issues

I also noticed I can't free these textures when I unload the model.
Is there any way to unload the morph target textures?

### Live example

https://glitch.com/edit/#!/three-r133-vtf-morph-memory-leak

### Platform

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: **r133, r135**
     - DOES NOT REPRODUCE in `WebGL1Renderer`. Only happens with WebGL2.

**Comment by 0b5vr** [comment]
Ok this is way harder than I thought.

I was thinking about changing the key of the WeakMap `morphTextures` to `Geometry.morphAttributes` but it requires us to care about uniqueness of morphAttributes' object, which would be a dangerous design,,,
Actually models loaded via GLTFLoader has different `morphAttributes` objects for each geometries despite the content is identical.

I need your help @Mugen87 . First of all is this a problem that is worth resolved?
It might be better to just reconstruct VBOs and IBOs.

**Comment by Mugen87** [comment]
Why can't you share a single geometry if position and normal data are identical?

> First of all is this a problem that is worth resolved?

In my opinion, no. The implementation assumes that vertex data are organized on a geometry level. It was planned to expand the data support in `WebGLMorphtargets` to honor colors and texture coordinates. The geometry object is the logical component that holds all these data together.

**Comment by 0b5vr** [comment]
I completely forgot to explain about the structure of the model, I'm sorry.
The model shares a same VBOs for multiple meshes while each mesh has different indices.

I hope these figures explain my circumstance well, this is how GLTF structure of the model look like:

![image](https://user-images.githubusercontent.com/7824814/147459083-29b410e4-508c-4f07-a66e-5e41b1265fd7.png)

![image](https://user-images.githubusercontent.com/7824814/147459296-892f002f-9325-45fd-9637-b8ab2836e9ef.png)

**Comment by Mugen87** [comment]
I'm afraid we can't support this use case in `WebGLMorphtargets`. Consider to split up you buffers so each geometry has its unique set of (smaller) attributes.

**Comment by 0b5vr** [comment]
> In my opinion, no. The implementation assumes that vertex data are organized on a geometry level.

That sounds very reasonable.

I was not sure how common this kind of buffer structure is among the scene.

> Consider to split up you buffers so each geometry has its unique set of (smaller) attributes.

I probably have to implement this as my next action.

Thank you for your quick response as usual!

**Comment by 0b5vr** [comment]
> I also noticed I can't free these textures when I unload the model.
> Is there any way to unload the morph target textures?

Let me ask about this in a separated discussion.

**Comment by 0b5vr** [comment]
posted: https://discourse.threejs.org/t/how-do-i-free-morph-textures/33033

**Comment by donmccurdy** [comment]
> I'm afraid we can't support this use case in WebGLMorphtargets. Consider to split up you buffers so each geometry has its unique set of (smaller) attributes.

For the reasons described in https://github.com/mrdoob/three.js/issues/17089, having one buffer per BufferGeometry is not as efficient as sharing buffers. I don't think we need to solve that now, but it's a pretty common layout for glTF files and if there are problems with using morph targets we'll eventually run into that again. Perhaps we can discuss it in #17089.

**Comment by 0b5vr** [comment]
fyi, I've added a utility function to three-vrm, that makes morph textures compact against such models

https://github.com/pixiv/three-vrm/pull/880
