### ISSUE TITLE
miss binding.referenceCount++ error when AnimationMixer._bindAction 

### ISSUE THREAD

**Issue by walton007** [mrdoob/three.js#23096]
**Describe the bug**
When use AnimationMixer.clipAction to generate an AnimationAction, referenceCount may be wrong when encounter this sub-branch code:
![image](https://user-images.githubusercontent.com/2437648/147456821-05730006-e466-48dd-91c2-c62390f32c3c.png)

I don't know it's by design or it's a potential error.  I think it should be in this way 
![image](https://user-images.githubusercontent.com/2437648/147457046-96feec4d-ffc7-4efb-8751-f65e648efc4e.png)

This bug (if it's a bug) may lead to error in my project like following shows:
![image](https://user-images.githubusercontent.com/2437648/147458486-d467c69c-4978-4e4f-a20e-614cdaba7b01.png)

**To Reproduce**
1. create 2 different AnimationClip, and apply to the same object. For example, build 2 animation clip to move the same cube. This will trigger the code enter the sub-branch code mentioned above 
   now we can see. _bindings[0].useCount = 2 and _bindings[0].referenceCount = 1, which is not correct now! 
![image](https://user-images.githubusercontent.com/2437648/147461507-0bedf02d-af0a-4171-a91e-608fd3921e56.png)

2. some seconds later, let's stop the first animation and clear the cache resource using _mixer.uncacheAction(clip, root); 
   now,  _bindings is empty array, but _nActiveBindings =1, which will cause error when update!
![image](https://user-images.githubusercontent.com/2437648/147461888-3bf597f1-d733-414e-893b-94563cd2f225.png)

3. update error occur!
![image](https://user-images.githubusercontent.com/2437648/147462085-e8759427-fe44-4faa-a687-7f1da0d70c0f.png)

***Code***

```js
// code goes here
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hyok6tvj/)
* [jsfiddle-dev](https://jsfiddle.net/c5m1kazu/)

**Expected behavior**

I've tried to fix this issue with one line code below:
![image](https://user-images.githubusercontent.com/2437648/147462270-6ae0f579-1e04-4740-99ef-8bd2cbab05e9.png)

If this is indeed a bug, can we fix and merge it into the master branch?

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [ MacOS]
 - Browser: [Chrome]
 - Three.js version: [ "0.134.0"]

**Comment by Mugen87** [comment]
Can you please verify if this issue is the same like discussed in #22036?

If so, I suggest you file a PR with your fix so we can closely test it.

**Comment by walton007** [comment]
> Can you please verify if this issue is the same like discussed in #22036?
> 
> If so, I suggest you file a PR with your fix so we can closely test it.

It's not the same issue. 

 I'll file a PR later.

**Comment by Mugen87** [comment]
> It's not the same issue.

Do you mind explaining in more detail why not?

**Comment by Mugen87** [comment]
Here is a minified live example that demonstrates the issue: https://jsfiddle.net/sgL6obhz/1/

Your findings made it much easier to finally reproduce this issue in a small test case. The idea is to create two keyframe tracks animating the same property (e.g. `Object3D.position`) and then create for each track a clip. Uncaching a mesh while both animations are playbacked produces the issue. After some debugging, I'm sure this is the same root cause for #22036.

 A missing statement in `AnimationMixer._bindAction()` produces a wrong reference count which potentially breaks `_removeInactiveBindingsForAction()`. Your PR fixes the issue.

**Comment by walton007** [comment]
> d explaining in more detail

Your small test case is exactly the same like what happened in my project,  **except that:** 
 Your test case is using '**mixer.uncacheRoot(mesh)**'
 But my case is using '**mixer.uncacheClip(clip)'**
 . 

for #22036. I think it's the problem of not **stopping clipAction** before uncacheRoot.  So i said tt's not the same issue.
