### ISSUE TITLE
Performance Regression: `getProgram` & `getProgramCacheKey` been called too many times.

### ISSUE THREAD

**Issue by gonnavis** [mrdoob/three.js#23106]
**Describe the bug**

Hello, I noticed that `getProgram` & `getProgramCacheKey` been called too many times on r135, caused severe performance issue on some projects.
After a deep research, found that maybe the many new added `needsProgramChange = true;`s caused this problem.
Comparing between r129 & r135:
![image](https://user-images.githubusercontent.com/10785634/147599768-957a9475-c163-4f09-9644-ca010bffc280.png)

**To Reproduce**

1. Go to
    https://raw.githack.com/gonnavis/annihilate/threejsR129GetProgram/index.html
    and
    https://raw.githack.com/gonnavis/annihilate/threejsR135GetProgram/index.html
2. Open devtool
3. See r129 call 8 times per frame, r135 call 17 times per frame.
![image](https://user-images.githubusercontent.com/10785634/147600466-0886958c-e4bc-43e2-9492-77f39f232cdf.png)
![image](https://user-images.githubusercontent.com/10785634/147600501-0a1372b0-7265-4f4c-858d-5ddb15e7af95.png)

**Expected behavior**

Because just changed threejs lib, no other codes changed, and all works well.
So I want r135 also call same times as r129 in these situations.

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [r135]

**Comment by donmccurdy** [comment]
See https://github.com/mrdoob/three.js/issues/22530 – this was improved in r136, so if you can upgrade from r135 to r136 that may help.

**Comment by gonnavis** [comment]
@donmccurdy Sorry that update to r136 does not reduce the call many, still get 13 ~ 17 times.
Not the same as r129 which only 8 times.
![image](https://user-images.githubusercontent.com/10785634/147605409-0863b8bb-855c-40ed-8570-55d34454482c.png)

And in another more complex project, even get worse performance, lower fps after upgrade to r136.

**Comment by donmccurdy** [comment]
Reusing a material for both skinned and non-skinned meshes will trigger this performance regression (or it did, I haven't tested in r136 yet). There are likely some other situations that may also trigger it. See https://github.com/mrdoob/three.js/issues/22530#issuecomment-924600397. Let's continue discussion in #22530?
