### ISSUE TITLE
Remove sRGB inline decoding.

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#23109]
I'm currently working on a PR to remove the inline sRGB decode from the shader. We want to do this to avoid wrong texture filtering which was discussed in earlier issues. The removal also simplifies the code base at various places (especially the WebGL 2 code paths).

The idea is to use `SRGB8_ALPHA8` with WebGL 2 and a fallback for WebGL 1. In order to use `SRGB8_ALPHA8`, textures have to be in RGBA format and must use unsigned byte which is true for most color textures. However, there are a couple of issues with that approach and I want to discuss them step by step. The first problem is processing compressed textures holding sRGB encoded values like in:

https://github.com/mrdoob/three.js/blob/d10d1be864f5e08c9d13dc098dd07af61c39de53/examples/webgl_loader_texture_basis.html#L53-L58

How should we handle this use case? Decoding compressed texels values on the CPU is by definition no option. If you do a separate render pass and decode the texture into a render target, we would loose the compression (unless we compress it again  which is no good idea either).

As far as I understand we can only support compressed textures with sRGB values if formats like `SRGB8_ALPHA8_ASTC_4x4_Format` are used. Or we have to keep the inline decode. Are there any other options?

**Comment by mrdoob** [comment]
Maybe @richgel999 and/or @zeux have recommendations for what to do here?

**Comment by richgel999** [comment]
Not sure I fully follow you (as I'm not super familiar with three.js internals). It sounds like you're currently sampling sRGB textures using linear filtering (i.e. not telling the GPU's texture filtering unit that the texture is actually sRGB), then converting from sRGB->linear in the shader. (Right?)

It should be simple to just change the texture formats you're feeding WebGL to use the sRGB variants, and let the GPU do the filtering itself, with no inline sRGB decode. It shouldn't be necessary to decode the .basis/.ktx2 texture data on the CPU - the texture data should remain unchanged.

**Comment by Mugen87** [comment]
> It sounds like you're currently sampling sRGB textures using linear filtering (i.e. not telling the GPU's texture filtering unit that the texture is actually sRGB), then converting from sRGB->linear in the shader. (Right?)

Yes, that is right.

> It should be simple to just change the texture formats you're feeding WebGL to use the sRGB variants, and let the GPU do the filtering itself, with no inline sRGB decode.

That is what I had in mind, too. However, this means code like in the above example needs be changed. And `three.js` has to establish a policy that only certain texture setups support the sRGB workflow.

Looking at the current constants that would be all `SRGB8_ALPHA8_ASTC*` formats and `RGBAFormat` (both `UnsignedByteType`). For all other textures `sRGBEncoding` can't be used.

**Comment by donmccurdy** [comment]
> Looking at the current constants that would be all SRGB8_ALPHA8_ASTC* formats and RGBAFormat (both UnsignedByteType). For all other textures sRGBEncoding can't be used.

For Basis and KTX2 to work properly, we need the ability to transcode to the [formats listed here](https://github.com/KhronosGroup/3D-Formats-Guidelines/blob/main/KTXDeveloperGuideWebGL.md). The rough prioritization of those formats is given in a series of charts from the [KTX2 guidelines](https://github.com/KhronosGroup/3D-Formats-Guidelines/blob/main/KTXDeveloperGuide.md#transcode-target-selection-rgb-and-rgba). Can WebGL not do sRGB conversion for compressed formats other than ASTC? 😕

**Comment by Mugen87** [comment]
> Can WebGL not do sRGB conversion for compressed formats other than ASTC? 😕

Yes, it can. However, `three.js` does not support them yet. After looking at the extensions the following sRGB formats could be added:

- `WEBGL_compressed_texture_etc`
  - `COMPRESSED_SRGB8_ETC2`
  - `COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2`.
- `WEBGL_compressed_texture_s3tc_srgb`
  - `COMPRESSED_SRGB_S3TC_DXT1_EXT`
  - `COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT`
  - `COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT`
  - `COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT`
- `EXT_texture_compression_bptc`
  - `COMPRESSED_SRGB_ALPHA_BPTC_UNORM_EXT`

**Comment by donmccurdy** [comment]
At least internally within the rendered I think we should use those, yes – thanks! In terms of the user-facing API, I do have a concern. See https://github.com/mrdoob/three.js/pull/23116#issuecomment-1003141952.

**Comment by mrdoob** [comment]
Hmm... `VideoTextures` will be affected by this, right?

**Comment by Mugen87** [comment]
Are video textures supposed to be in sRGB? Maybe we can just state to always use `LinearEncoding`?

**Comment by mrdoob** [comment]
Well, if someone is doing a video player (think YouTube in VR) would be a hard talk to recompress their whole library... 🤔

**Comment by Mugen87** [comment]
It seems when changing the format of a video textures to `RGBAFormat`, they can use `SRGB8_ALPHA8`. Tested with `webgl_video_panorama_equirectangular`.

**Comment by Mugen87** [comment]
Live example: https://jsfiddle.net/uzgo9fh4/3/

**Comment by mrdoob** [comment]
Could we add inline sRGB decoding only for `VideoTexture`s until that crbug is solved?

**Comment by Mugen87** [comment]
I've added a solution here: 57ac4776ac7328f7fd239c5b24b61a96171e8419

Should be easy to revert when the Chromium bug is solved.

Just for the protocol: `VideoTexture` do not use `gl.texStorage2D()` right now and with the above commit no `SRGB8_ALPHA8` format. The sRGB decode happens inline.

**Comment by Mugen87** [comment]
BTW: Is https://github.com/mrdoob/three.js/issues/21874#issuecomment-859398117 still true? In what way has Chrome not optimized support for video textures?

**Comment by Mugen87** [comment]
> VideoTexture does not use gl.texStorage2D() right now and with the above commit no SRGB8_ALPHA8 format. 

A usage is basically possible if we know the dimensions of the texture in advance. Right now, when a video texture is marked for an update in `VideoTexture` for the first time, the dimensions are `0`. However, it is possible to change the code such that `videoWidth` and `videoHeight` report the correct dimensions and `gl.texStorage2D()` does not complain.

**Comment by mrdoob** [comment]
> I've added a solution here: https://github.com/mrdoob/three.js/pull/23129/commits/57ac4776ac7328f7fd239c5b24b61a96171e8419

Excellent!

> BTW: Is https://github.com/mrdoob/three.js/issues/21874#issuecomment-859398117 still true? In what way has Chrome no optimized support for video textures?

I'll check.
