### ISSUE TITLE
Raycaster's code example: the normalized result is wrong

### ISSUE THREAD

**Issue by 1337816495** [mrdoob/three.js#23115]
# Description

In the code example of raycaster, the example wants to project the coordinates of the cursor to `[-1,1]` , which is achieved by the following code:
```js
mouse.x =   ( event.clientX / window.innerWidth  ) * 2 - 1;
mouse.y = - ( event.clientY / window.innerHeight ) * 2 + 1;
```
Unfortunately, the cursor coordinates will actually be projected to `[-1, 1)` , The reasons for the error are as follows:
( assuming that the resolution of the screen is `1920*1080` )
∵ `event.clientX ∈ [0, 1919]`
∵ `window.innerWidth = 1920`
∴ `event.clientX / window.innerWidth ∈ [0, 1)`
∴ ` (event.clientX / window.innerWidth ) * 2 - 1 ∈ [-1, 1)`
The same can be obtained `- ( event.clientY / window.innerHeight ) * 2 + 1 ∈ [-1, 1)`
<Br/><Br/>

# Solution

∵ The normalization formula is `value_norm = ( value - value_min ) / ( value_max - value_min )`
∴ `mouse.x =   ( event.clientX / ( window.innerWidth  - 1 ) ) * 2 - 1`
∴ `mouse.y = - ( event.clientY / ( window.innerHeight - 1 ) ) * 2 + 1`
  <Br/><Br/>

# Platform

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome 96.0.4664.110]
 - Three.js version: [r136]

**Comment by mrdoob** [comment]
What example are you referring to?

**Comment by 1337816495** [comment]
> 

https://threejs.org/docs/index.html?q=ray#api/en/core/Raycaster
![Snipaste_2021-12-31_13-37-26](https://user-images.githubusercontent.com/50298406/147805544-8b558c36-4b9b-4ab0-8f5b-e2da3ea0f78c.png)

**Comment by 1337816495** [comment]
> What example are you referring to?

here👇
https://threejs.org/docs/index.html?q=ray#api/en/core/Raycaster
![Snipaste_2021-12-31_13-37-26](https://user-images.githubusercontent.com/50298406/147805584-1a8fb6e3-e937-47a1-8885-5736339861a4.png)

**Comment by Mugen87** [comment]
I suggest we are changing the code example to use pointer events. `event.clientX` will become a float and depending on the device hold values which converge to `innerWidth`.  The remaining deviations are so minor that they are negligible.

**Comment by 1337816495** [comment]
> I suggest we are changing the code example to use pointer events. `event.clientX` will become a float and depending on the device hold values which converge to `innerWidth`. The remaining deviations are so minor that they are negligible.

As you said, `clientX` has been redefined as `double float`, so the current calculation method is completely correct, which is more important.
Thank you for telling me this new knowledge.
