### ISSUE TITLE
When in VR mode video is slightly of they dont match give a blurry view with Google Cardboard.

### ISSUE THREAD

**Issue by s3bubble** [mrdoob/three.js#23112]
**Describe the bug**

I am trying to get something up an running for videojs vr. Everything thing works I just have one issue when running the project on a google cardboard the image is slightly of.

See this image.
![Screenshot 2021-12-29 at 21 15 29](https://user-images.githubusercontent.com/17534854/147704971-33fad345-85d1-46db-930a-154a5fa6c13f.png)

You should notice the swans are not aligned.

**To Reproduce**

Clone this repo. https://github.com/s3bubble/videojs-vr

git clone https://github.com/s3bubble/videojs-vr.git

npm start.

Open in Safari browser with user agent iphone set.

Click play and then the enter vr button overlayed 

You should then see the issue I am getting with the images being slightly off.

This is the same issue I am getting when using a Google cardboard.

All the code is in this file.

https://github.com/s3bubble/videojs-vr/blob/d565c9865fbc69a7283a4397549677e8a3f57a98/src/plugin.js#L148

Thanks

**Comment by mrdoob** [comment]
Please, provide a working jsfiddle.

**Comment by s3bubble** [comment]
Sure thing here you go I have used jsbin you can see the code in the javascript tab.

https://output.jsbin.com/fuqiyawatu/8

Open in Safari and set the user agent. It will show the same issue I am getting on iPhone.

<img width="383" alt="Screenshot 2021-12-30 at 10 07 59" src="https://user-images.githubusercontent.com/17534854/147742084-f9f08e82-f154-422d-8de2-8e9bfc64e6b9.png">

Thanks

**Comment by s3bubble** [comment]
Can this issue be reopened now?

**Comment by Mugen87** [comment]
You are using `three.js` in version `r83` as well as `VREffect` and `VRControls`. We do not maintain this code anymore.

Please redirect your question to the [forum](https://discourse.threejs.org/).

**Comment by s3bubble** [comment]
Hi,

Thanks for the response happy to use the latest version but I cant find one example that works on my phone with three.js.

I know you have the examples.

https://threejs.org/examples/?q=video#webxr_vr_video

But none of these work on my phone.
![IMG_1126](https://user-images.githubusercontent.com/17534854/147789527-1b6edf95-6e92-4e36-8b72-a033d06b9fd2.PNG)
![IMG_1127](https://user-images.githubusercontent.com/17534854/147789530-e7d700a9-d4e1-4e22-bc48-ff69d220ccf5.PNG)
![IMG_1128](https://user-images.githubusercontent.com/17534854/147789532-dd6224ed-0342-4709-8fc1-5d54137e790b.PNG)

The only tutorial I could get to work was from here.

https://hermionewy.github.io/webVR_tutorial/

Do you have any working three.js video vr examples?

**Comment by mrdoob** [comment]
No, we don't. Sorry.

**Comment by s3bubble** [comment]
It will work tho right? There are just no examples?

**Comment by mrdoob** [comment]
We do not support Cardboard anymore. Sorry.

**Comment by s3bubble** [comment]
Ok thanks @mrdoob at least I know where we stand so the only way to get this working with cardboard or iPhone 360 video vr is to use the old webvr setup.

This guy seems to have attempted something https://github.com/thomasdeppisch/videojs-xr maybe I can grab something from this.

I guess people are no longer using Google cardboard for vr? need to get up to speed with this not really looked into vr much just have a Google cardboard lying about to test with. 

Just prototyping and testing some stuff at the moment.
