### ISSUE TITLE
CSS Format of deleted code lines probably needs to be a changed?

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#23117]
The code in the manual has lines that are supposed to show as deleted 

This is how it used to look

<img width="754" alt="Screen Shot 2021-12-30 at 02 13 50" src="https://user-images.githubusercontent.com/234804/147742768-b494c849-770a-4f15-a38e-cade0742a7d6.png">

This is how it looks now

<img width="846" alt="Screen Shot 2021-12-30 at 02 03 27" src="https://user-images.githubusercontent.com/234804/147742787-f0197d38-fe8e-47be-9b12-f2aab89859f0.png">

It seems hard to tell those lines are deleted

**Comment by mrdoob** [comment]
It was intentional. I followed GitHub's own diff styling:

<img width="608" alt="Screen Shot 2021-12-30 at 11 02 53 AM" src="https://user-images.githubusercontent.com/97088/147768245-d702442b-2a77-42a6-8962-cbdd7c21e9f5.png">

Maybe the colors are too subtle in dark mode though.

**Comment by greggman** [comment]
You could add + and - like this

```
pre.prettyprint ul.modifiedlines li.linedeleted:before {
  content: '-';
}

pre.prettyprint ul.modifiedlines li.lineadded:before {
  content: '+';
}
```

which would be closer to github?
<img width="864" alt="Screen Shot 2021-12-30 at 08 22 38" src="https://user-images.githubusercontent.com/234804/147769832-dd7701a1-c5f2-4d8e-aebe-4dbcd4cfe40f.png">

**Comment by greggman** [comment]
If you want to be closer to github you could do something like

```
pre.prettyprint ul.modifiedlines li.linedeleted {
    list-style-type: '-';
    background-color: #ffebe9;
}

pre.prettyprint ul.modifiedlines li.lineadded {
    list-style-type:  '+';
    background-color: #e6ffec;
}
```
<img width="840" alt="Screen Shot 2021-12-30 at 08 38 29" src="https://user-images.githubusercontent.com/234804/147771009-6d65b980-e9b4-4826-97b6-a670ad4f8a5d.png">

**Comment by mrdoob** [comment]
Yeah, that works! 👍

**Comment by Mugen87** [comment]
Minor style feedback:

- A little bit of padding between `+`/`-` and the code would be good.
- With the suggested styles, the symbols have no background color. Using a combination of `:before` and `content` could solve this issue.
