### ISSUE TITLE
threejs.org/manual navigation

### ISSUE THREAD

**Issue by pikachub2005** [mrdoob/three.js#23111]
**Describe the bug**

Selected page isn't shown on navigation if you didn't get there from the navigation

**To Reproduce**

1. Go to on of the manual pages (like https://threejs.org/manual/#en/cameras.html)
2. Cameras link isn't blue
3. Click on camera link from navigation (It should change color), then the shadows link on the bottom of the page
4. Shadows link isn't blue, but the cameras link still is

**Expected behavior**

It should show what page you're on

**Screenshots**

![image](https://user-images.githubusercontent.com/74213212/147698189-ceda8cf1-65ef-4530-aed0-c6204f1da950.png)

**Platform:**

 - Device: Mobile
 - OS: Chrome
 - Browser: Chrome

**Comment by greggman** [comment]
FYI: a similar issue exists in docs

1. Go to https://threejs.org/docs/index.html#api/en/cameras/Camera
2. Click PerspectiveCamera under constructor
3. PerspectiveCamera in the nav panel is not highlighted
