### ISSUE TITLE
Uncorrect raycaster examples

### ISSUE THREAD

**Issue by Botchal** [mrdoob/three.js#23120]
In the raycaster examples (e.g. https://github.com/mrdoob/three.js/blob/dev/examples/webgl_instancing_raycast.html#L112), the mouse coordinates are not calculated correctly. Сode in the example works when the width of the canvas is equal to the width 
 window. And its position is 0 0. 

***Code***

This is correct example for raycaster with https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect :

```js
const rect = this.renderer.domElement.getBoundingClientRect();
mouse.x = ( ( event.clientX - rect.left ) / ( rect.width - rect.left ) ) * 2 - 1;
mouse.y = - ( ( event.clientY - rect.top ) / ( rect.bottom - rect.top) ) * 2 + 1;
```

**Screenshots**

[example.](http://joxi.ru/V2Vl6K1H85EdRr)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [r136]

**Comment by Mugen87** [comment]
The example makes certain assumptions in order to simplify the code. If you alter these assumptions it is only natural that certain features might break.

I do not vote to add your suggestion code since it would be necessary to add it in all examples which introduces an unnecessary complexity.

**Comment by mrdoob** [comment]
> Сode in the example works when the width of the canvas is equal to the width window. And its position is 0 0.

The canvas width in the example equals the window width and the position is 0 0.

**Comment by WestLangley** [comment]
Note that `.getBoundingClientRect()` also includes the padding and border-width, which must zero for the calculation to be exact.
