### ISSUE TITLE
css3drender cannot be displayed on iPhone x (IOS v12.0)

### ISSUE THREAD

**Issue by zhaowei-1234** [mrdoob/three.js#23128]
With three's css3drender, it cannot be displayed on iPhone x (IOS 12.0), but it can be displayed on iPhone x (IOS 14.5). Can anyone encounter this problem and provide some good solutions

**Comment by Mugen87** [comment]
Please clarify this issue at the forum:

https://discourse.threejs.org/t/with-threes-css3drender-it-cannot-be-displayed-on-iphone-x-ios-12-0-but-it-can-be-displayed-on-iphone-x-ios-14-5-can-anyone-encounter-this-problem-and-provide-some-good-solutions/33177
