### ISSUE TITLE
three/examples/jsm/utils/SceneUtils.js is not namespaced

### ISSUE THREAD

**Issue by Kyohei-Ishihara** [mrdoob/three.js#23136]
**Describe the bug**

SceneUtils is defined as namespace in SceneUtils.d.ts.
SceneUtils.js does not support it

**To Reproduce**

3. See error

***Code***

```js
// code goes here
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hyok6tvj/)
* [jsfiddle-dev](https://jsfiddle.net/c5m1kazu/)

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r???]

**Comment by Kyohei-Ishihara** [comment]
```
import
{
	Group,
	Mesh
} from 'three'


const SceneUtils = {
	createMeshesFromInstancedMesh: function ( instancedMesh )
	{

		const group = new Group()

		const count = instancedMesh.count
		const geometry = instancedMesh.geometry
		const material = instancedMesh.material

		for ( let i = 0;i < count;i++ )
		{

			const mesh = new Mesh( geometry, material )

			instancedMesh.getMatrixAt( i, mesh.matrix )
			mesh.matrix.decompose( mesh.position, mesh.quaternion, mesh.scale )

			group.add( mesh )

		}

		group.copy( instancedMesh )
		group.updateMatrixWorld() // ensure correct world matrices of meshes

		return group

	},

	createMultiMaterialObject: function ( geometry, materials )
	{

		const group = new Group()

		for ( let i = 0, l = materials.length;i < l;i++ )
		{

			group.add( new Mesh( geometry, materials[ i ] ) )

		}

		return group

	},

	detach: function ( child, parent, scene )
	{

		console.warn( 'THREE.SceneUtils: detach() has been deprecated. Use scene.attach( child ) instead.' )

		scene.attach( child )

	},

	attach: function ( child, scene, parent )
	{

		console.warn( 'THREE.SceneUtils: attach() has been deprecated. Use parent.attach( child ) instead.' )

		parent.attach( child )

	}
}



export
{
	SceneUtils
}
```

Change SceneUtils.js to this

**Comment by gkjohnson** [comment]
Three.js types are maintained in a separate project now so the issue should be directed there. I'm sure they'd appreciate a PR to update the types to match three.js' SceneUtils implementation!

https://github.com/three-types/three-ts-types

**Comment by Kyohei-Ishihara** [comment]
Thank you for teaching me.
