### ISSUE TITLE
r133 -> r134 = error: Fetch API cannot load file:///C:/Users/Name/Downloads/boxtest.fbx. URL scheme "file" is not supported.

### ISSUE THREAD

**Issue by prominentdetail** [mrdoob/three.js#23138]
I tried updating from r133 to r134, however I now get errors when trying to load things. I assume it is due to this change: FileLoader now uses fetch instead of XMLHttpRequest.
It was working perfectly fine in r133.

The error occurs here: 
load | @ | three.module.js:38595

I am using NW.js to run my application locally/natively across windows/mac/linux

**Comment by gkjohnson** [comment]
I think this is an issue / question that should be raised with NW.js if the "file://" protocol does not work with fetch.
