### ISSUE TITLE
Allow background texture to stay unaffected by WebGLRenderer.tonemapping

### ISSUE THREAD

**Issue by chubei-oppen** [mrdoob/three.js#23141]
**Is your feature request related to a problem? Please describe.**

Currently if we set `Scene.background` to a `Texture`, the background is always tone mapped according to `WebGLRenderer.toneMapping` setting. Other objects in the scene can escape from this by setting `Material.toneMapped`. It would be great if we can do the same thing to the background.

**Describe the solution you'd like**

Add a `Scene.backgroundToneMapped` property. Its values get propagated to the actual `Material` used in `WebGLBackground`.

**Describe alternatives you've considered**

Add a fullscreen quad/cube to the scene in app code with a `ShaderMaterial` (basically copying code from `WebGLBackground`) and carefully manage render order.

**Comment by Mugen87** [comment]
Duplicate, see https://github.com/mrdoob/three.js/issues/13066#issuecomment-424564427.
