### ISSUE TITLE
Typo in the randomDirection() function in Vector3.js

### ISSUE THREAD

**Issue by erichlof** [mrdoob/three.js#23146]
**Describe the bug**
Typo in the randomDirection() function in Vector3.js:
https://github.com/mrdoob/three.js/blob/dev/src/math/Vector3.js#L720

@brianpeiris 

Shouldn't it read ?:
const f = Math.sqrt( 1 - u * u );

Thank you!

**Comment by gkjohnson** [comment]
`**` is the [exponentiation operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Exponentiation) so these lines are functionally identical:

```js
const f = Math.sqrt( 1 - u ** 2 );
```

```js
const f = Math.sqrt( 1 - u * u );
```

**Comment by erichlof** [comment]
@gkjohnson 
Whoops! My bad. I didn't know about this operator in JS.

Thanks Garrett!
