### ISSUE TITLE
Add applyQuaternion to Vector4

### ISSUE THREAD

**Issue by chubei-oppen** [mrdoob/three.js#23140]
**Is your feature request related to a problem? Please describe.**

Sometimes we need to apply a `Quaternion` to `Vector4`, only changing its `xyz` components, keeping the `w` componnet unchanged.

**Describe the solution you'd like**

Add `applyQuaternion` to `Vector4`, calling `Vector3.applyQuaternion`.

**Describe alternatives you've considered**

Keep the status quo and modifying `Vector4` prototype in app code.

**Comment by Mugen87** [comment]
Sorry, but we do not add this type of convenient methods to the math classes. You have to use `Vector3` if you need `applyQuaternion()`.
