### ISSUE TITLE
Editor: Suported `window-controls-overlay` feature.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#23153]
**Is your feature request related to a problem? Please describe.**

Not related to a problem.
TBH, I wanted to implement this feature, but I wasn't sure it will be accepted.

**Describe the solution you'd like**

Editor suported window-controls-overlay feature.

**Describe alternatives you've considered**

Followup Chrome 97's new feature about `window-controls-overlay`.

**Additional context**

Screenshot:

![image](https://user-images.githubusercontent.com/23699926/148647266-fdcf9668-2ab7-4a6b-99bb-5c49418a8a21.png)

Feature info links: 

https://github.com/WICG/window-controls-overlay/blob/main/explainer.md

https://wicg.github.io/window-controls-overlay/

https://web.dev/window-controls-overlay/

https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/window-controls-overlay

**Comment by mrdoob** [comment]
What should go up there?

**Comment by linbingquan** [comment]
> What should go up there?

```diff
diff --git a/editor/css/main.css b/editor/css/main.css
--- a/editor/css/main.css
+++ b/editor/css/main.css
@@ -341,12 +341,14 @@ select {
        margin: 0;
        right: 0;
        top: 0;
+       app-region: drag;
 }

        #menubar .menu {
                float: left;
                padding-right: 8px;
+               app-region: no-drag;
        }

        #menubar .menu.right {
diff --git a/editor/manifest.json b/editor/manifest.json
--- a/editor/manifest.json
+++ b/editor/manifest.json
@@ -10,5 +10,6 @@
       "type": "image/png",
       "sizes": "144x144"
     }
-  ]
+  ],
+  "display_override": ["window-controls-overlay"]
 }
```

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/pull/23172#issuecomment-1010322390
