### ISSUE TITLE
WebGLRenderer: Distance culling

### ISSUE THREAD

**Issue by ligaofeng0901** [mrdoob/three.js#23154]
**Is your feature request related to a problem? Please describe.**

Distance culling is a common feature in game engine. In my use case, I load some gltf models, I wanna hide some models when camera is far enough to reach a threshold.  I know I can update `.visible` before render, but it's more convinient if engine supports this feature.

**Describe the solution you'd like**

if I can use code like `object.maxDistance=1000;` or other property on `Object3D`. Then the renderer will automatically show or hide a object.

**Comment by mrdoob** [comment]
This can also be achieved with LOD too.
https://threejs.org/examples/webgl_lod.html
