### ISSUE TITLE
Vector3 applyQuaternion(q) function missing underscores for quaternion members (_x, _y, _z, _w)

### ISSUE THREAD

**Issue by erichlof** [mrdoob/three.js#23160]
**Describe the bug**

https://github.com/mrdoob/three.js/blob/dev/src/math/Vector3.js#L280

The above line from the applyQuaternion( q ) function in Vector3.js currently reads:
const qx = q.x, qy = q.y, qz = q.z, qw = q.w;

Quaternions in three.js do not have x,y,z, or w members, but rather _x, _y, _z, and _w members.
The above line should read instead:
const qx = q._x, qy = q._y, qz = q._z, qw = q._w;

**Comment by gkjohnson** [comment]
Quaternions do have x, y, z, and w members. They are declared with getters and setters here:

https://github.com/mrdoob/three.js/blob/3843183c5466fc291b8b76d367a8e54dc45518c4/src/math/Quaternion.js#L122-L172

**Comment by erichlof** [comment]
@gkjohnson 

Hi Garrett, yes you can get and set the quaternion's 'x,y,z, and w' members through those methods, but the issue here is that the applyQuaternion(q) function inside Vector3.js is trying to access variables that don't exist.  When the argument (q) is passed in as a quaternion to this function, there is no such q.x, q.y, q.z, or q.w to even reference - they are undefined, according to Quaternion.js.  I think this is just a typo, and rather it should directly access the quaternion's q._x, q._y, q._z, and q._w values - which are indeed defined. 

When I made this change in my own copy of the math library, the methods that use this applyQuaternion (not very many) started to work instead of giving NaNs in the inspector.
