### ISSUE TITLE
Nodes: Cannot make different code flows with CondNode

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#23170]
**Describe the bug**

Cannot make different code flows with CondNode.

**To Reproduce**

If I want to program some shader like
```
a = /* some calculations */;
if (a > 0.0) {
    b = 0.0;
} else {
    b = /* some heavy calculations */;
}
```
with NodeMaterial and I do something like
```
const ZERO = new FloatNode(0.0).setConst(true);
const a = /* here are some calculations with nodes */;
const resultOfHeavyCalculations = /* here are some heavy calculations with nodes */;
const node = new CondNode(new OperatorNode('>', a, ZERO), ZERO, resultOfHeavyCalculations);
```
then this code is transformed into shader code like
```
a = /* some calculations */;
c = /* some heavy calculations */;
d = ( a > 0.0 );
if ( d ) {
    b = 0.0;
} else {
    b = c;
}
```
which is obviously not what I want (because there are no need to make these calculations if they are not needed).

**Comment by sunag** [comment]
I made a test with flow in `WebGPU` and I had this result which seems correct at the level of flow with `CondNode`.

```js
// FLOW -> Color
nodeVar1 = ( 0.0 > 0.0 );
if ( nodeVar1 ) {

	nodeVar0 = mix( ( textureSample( nodeUniform0, nodeUniform0_sampler, ( nodeVary0 + ( vec2<f32>( NodeUniforms.nodeUniform1 ) * vec2<f32>( -0.5, 0.1 ) ) ) ) ), vec4<f32>( vec3<f32>( sign( mod( ( floor( ( ( nodeVary0 + ( vec2<f32>( NodeUniforms.nodeUniform1 ) * vec2<f32>( -0.5, 0.1 ) ) ) * vec2<f32>( 2.0 ) ).x ) + floor( ( ( nodeVary0 + ( vec2<f32>( NodeUniforms.nodeUniform1 ) * vec2<f32>( -0.5, 0.1 ) ) ) * vec2<f32>( 2.0 ) ).y ) ), 2.0 ) ) ), 1.0 ), NodeUniforms.nodeUniform2 );

} else {

	nodeVar0 = vec4<f32>( vec3<f32>( 0.0 ), 1.0 );

};
Color = nodeVar0;
```

Maybe your problem has other origins too, could you share a live example in `jsfiddle` or other platform to I can confirm?

**Comment by LeviPesin** [comment]
I think this only happens with VarNode... Here are examples:
https://jsfiddle.net/37eu2Lrf/1/
https://jsfiddle.net/37eu2Lrf/2/

**Comment by sunag** [comment]
Fixed here https://github.com/mrdoob/three.js/pull/23828

**Comment by LeviPesin** [comment]
Confirmed that this is fixed.
