### ISSUE TITLE
Translucent scene rendered to an image using toDataURL() displays wrong/dark colours (Firefox)

### ISSUE THREAD

**Issue by k-j0** [mrdoob/three.js#23181]
---

### Edit: bug reported to Mozilla [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1749202).

---

**Bug description**

Rendering translucent objects without a solid background and then rendering the results to a base 64 image using `renderer.domElement.toDataURL()` causes the resulting image to contain distorted and much darker colours than the original scene; only happens in Firefox on Windows as far as I can tell, although the same code does cause a similar rendering issue on Chrome and Safari on Mac (can't test that myself, so I'll focus on the Firefox issue here - Chrome and Edge on Windows don't have any issues rendering the correct colours).

**To Reproduce**

Steps to reproduce the behaviour (or see Fiddle linked below):
1. Create a `WebGLRenderer` with settings `{ alpha: true, preserveDrawingBuffer: true }`.
2. Add geometry to a scene with a transparent material (e.g. `new THREE.MeshBasicMaterial({ color: 'white', opacity: 0.5 })`, but this happens with any type of material, including `ShaderMaterial`) and render the scene. Preview the results in the renderer's `domElement` directly, which should display the correct colours.
3. Convert the result to a base64 image with `renderer.domElement.toDataURL()` and append the image somewhere on the document; in Firefox, the resulting image will contain distored colours.

***Code***

```js
// Setup renderer
const renderer = new THREE.WebGLRenderer({ alpha: true, preserveDrawingBuffer: true });
renderer.setSize(512, 512);
document.body.append(renderer.domElement);

// Create a scene with a translucent plane facing the camera
const scene = new THREE.Scene();
const camera = new THREE.OrthographicCamera(-0.5, 0.5, -0.5, 0.5, 0.1, 10);
const plane = new THREE.Mesh(new THREE.PlaneGeometry(), new THREE.MeshBasicMaterial({
    color: 'red',
    opacity: 0.8
}));
plane.position.z = -1;
plane.rotation.x = Math.PI;
scene.add(plane);

// Render the scene directly and then to an image
renderer.render(scene, camera);
const img = renderer.domElement.toDataURL(); // <- this image will be wrong in Firefox and will not reflect the state of the original canvas
```

***Live example***

* [JS Fiddle](https://jsfiddle.net/mh0v5r7s/)

**Expected behavior**

The translucent pixels should keep their original colours when converting to a data URI image.

**Screenshots**

![img](https://user-images.githubusercontent.com/20354645/148662644-a605d2b4-be78-43ff-8689-67ef10fb7556.png)

The top red square is a plane rendered with a transparent material (opacity = 0.8) directly to a canvas; the bottom square is the canvas contents exported as an image, which should be displaying the same exact colour but appears much darker.

**Platform:**

 - Device: Desktop
 - OS: Windows 10
 - Browser: Firefox 95.0.2
 - Three.js version: r135 (same issue currently happens with all Three.js versions I've tried)

**Comment by Mugen87** [comment]
Do you mind reporting this to Mozilla instead? https://bugzilla.mozilla.org/

**Comment by Mugen87** [comment]
I can confirm the fiddle works with Chrome and Edge on Windows 10 but not with Firefox.

**Comment by k-j0** [comment]
Bug reported to Mozilla [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1749202), thanks. Shall we close this issue here then?

**Comment by Mugen87** [comment]
Yes.
