### ISSUE TITLE
Using multiples WebGLMultiTargetRenderer will not render more than one layout

### ISSUE THREAD

**Issue by RenaudRohlinger** [mrdoob/three.js#23183]
**Describe the bug**
If we use two `WebGLMultiTargetRenderer`, the second MRT will only show the first layout. I suspect that only the first texture is bind / unbind properly when using `setRenderTarget()` on a MRT.

```js
// mrt = WebGLMultipleRenderTargets
// mrtClone = mrt.clone()
renderer.setRenderTarget( mrtClone );
renderer.render( scene, camera );

renderer.setRenderTarget( mrt );
renderer.render( scene, camera ); // or we could try to apply a postprocess with 2 channels by using postScene, postCamera here

renderer.setRenderTarget( null );
renderer.render( postScene, postCamera );
// result --> only layout 0 will be visible 🐛 

```

Weirdly enough if I invert the MRT order on this example it works?
```js
// mrt = WebGLMultipleRenderTargets
// mrtClone = mrt.clone()
renderer.setRenderTarget( mrt );
renderer.render( scene, camera );

renderer.setRenderTarget( mrtClone );
renderer.render( scene, camera ); // or we could try to apply a postprocess with 2 channels by using postScene, postCamera here

renderer.setRenderTarget( null );
renderer.render( postScene, postCamera );
// result --> both layout are visible ✅ 

```

Example: https://jsfiddle.net/3jswhaez/36/

**Screenshots**
Expected behavior:
![image](https://user-images.githubusercontent.com/15867665/148675030-565e277a-f7e2-4a3b-86c7-9e69151841a7.png)

Result:
![image](https://user-images.githubusercontent.com/15867665/148675009-1afcb2ff-a3a0-4775-a98c-d7e17f5d6ca7.png)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [r136]

**Comment by Mugen87** [comment]
It seems a call of `gl.drawBuffers( )` is missing for the second custom framebuffer.

The call defines the draw buffers to which fragment colors are written into. _This config belongs to the current bound framebuffer_. This bit is actually not checked in the source code. It only does this:

https://github.com/mrdoob/three.js/blob/ccaf9de909145879fe1058fa8c9281c62b84f51b/src/renderers/WebGLRenderer.js#L1900

However, this should be a framebuffer dependent check and not a global one.

**Comment by Mugen87** [comment]
You can easily verify the fix by forcing the following statement to always evaluate to `true`:

https://github.com/mrdoob/three.js/blob/ccaf9de909145879fe1058fa8c9281c62b84f51b/src/renderers/WebGLRenderer.js#L1940-L1952
