### ISSUE TITLE
XR example suggestion

### ISSUE THREAD

**Issue by callumprentice** [mrdoob/three.js#23189]
I have been experimenting with the three.js XR support via my Quest 2 and having a lot of fun writing small experiments. It occurred to me to ask if any of them would be interesting and acceptable for inclusion in the examples section. For example, this one displays an equirectangular image and lets you interact with it via the left controller and trigger. Perhaps there is some code there that others might find useful?

Demo: https://expxr.surge.sh/revealxr.html
Source: https://expxr.surge.sh/revealxr.js

If anyone thinks it's worth pursuing, I'm happy to take the time to clone the three.js dev branch and generate a PR.

Otherwise, understood if it's not interesting or up to standard and thanks for making an SDK that's so much fun to use.

**Comment by mrdoob** [comment]
Thanks. But at this point we are in need of more interactivity in XR examples (ie. physics + hands in vr).
