### ISSUE TITLE
Textures loading feature that has been in "5fa3d1d954dd320466cb75ea09884b5d8fb2317c" commit on Apr 7 in GLTFLoader.js file is now not  working

### ISSUE THREAD

**Issue by grpnpraveen** [mrdoob/three.js#23196]
**About The Bug:**
    The GLTF formatted 3d model that needs to access its textures from the textures folder is not possible now but which is possible in the commit "5fa3d1d954dd320466cb75ea09884b5d8fb2317c" that has been done on Apr 7th. The textures are not loading using the present GLTFLoader.js .

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to 'Any 3d model downloading website and download a gltf formatted 3d model'
2. place those files from the zip into the project folder.
3. Finally, load the model to the website . The error is displayed in the console.

**Code:**
const loader =new THREE.GLTFLoader();
loader.load('./scene.gltf',function(gltf){
   var model=gltf.scene.children[0];
   model.scale.set(1,1,1)
   model.position.set(0,0,-1);
//    model.rotation.x=90;
   scene.add(model);
    // renderer.render(scene,camera);
});

**Platform:**

 - Device: [Desktop,]
 - OS: [Windows]
 - Browser: [Chrome,]
 - Three.js version: [dev]

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
