### ISSUE TITLE
Opacity for MeshStandardNodeMaterial works in WebGLRenderer, but not in WebGPURenderer

### ISSUE THREAD

**Issue by geolehmann** [mrdoob/three.js#23198]
**Describe the bug**

It looks to me after some testing that the opacity of a MeshStandardNodeMaterial only works in the WebGLRenderer, but not in the WebGPURenderer. I tried both with just setting the **opacity** property directly, or setting a **opacityNode** via a **FloatNode**.

**To Reproduce**

I created two minimal pens for testing:

One with a WebGLRenderer: https://codepen.io/geo_coder/pen/JjrmpJr
Same code, modified for a WebGPURenderer: https://codepen.io/geo_coder/pen/eYGPVGB

**Screenshots**

WebGLRenderer:
<img src="https://user-images.githubusercontent.com/9590338/148905586-23da8707-14f6-4e75-9492-81710564fa51.png" width="300"> 
(shows the expected behaviour with opacity)

WebGPURenderer:
<img src="https://user-images.githubusercontent.com/9590338/148906283-aa87cff7-7db1-465a-97f2-fce5880ee649.png" width="300">
(opacity is missing)

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome Canary, Webview
 - Three.js version: dev, r136

@sunag, could you have a look maybe? Thanks in advance!

**Comment by sunag** [comment]
> @sunag, could you have a look maybe? Thanks in advance!

Of course. Thanks for examples, I will analyze.

**Comment by geolehmann** [comment]
thanks ❤

**Comment by sunag** [comment]
Hi @geolehmann. Fixed https://github.com/mrdoob/three.js/pull/23216

![image](https://user-images.githubusercontent.com/502810/149283703-317e79b9-1dd6-4a8b-8ced-77e3750b1089.png)

**Comment by geolehmann** [comment]
Many thanks sunag :-)
