### ISSUE TITLE
`setUniqueNames()` missing in GLTFLoader

### ISSUE THREAD

**Issue by Friksel** [mrdoob/three.js#23199]
**Describe the bug**

After filing an issue here (https://github.com/mrdoob/three.js/issues/20867) on cameras being renamed by the GLTFLoader and therefore couldn't be found anymore @donmccurdy was so kind to add a method to the GLTFLoader to turn off the (here) unneeded renaming behaviour to prevent issues and to accept the GLTF as is. Also other people had issues with this auto renaming behaviour.

So I was glad to see this was implemented, just to find out that it's not there (anymore) in r136.
Like this: https://github.com/mrdoob/three.js/pull/16639#issuecomment-797653487

I can't find anything about it in the whole lib of threejs nor in the documentation nor in the change logs. And AFAIK there is no alternative method or option to turn this auto-renaming behaviour off.

Please, could somebody tell me where the option to turn off this unwanted (and issues causing) auto-renaming-behaviour has gone?

Thanks in advance!

**To Reproduce**

1. Try to use `loader.setUniqueNames(false);`
2. Find out the method is missing

***Code***

```js
loader.setUniqueNames(false);
```

**Platform:**

 - Three.js version: 0.136.0

**Comment by Mugen87** [comment]
AFAICS, `setUniqueNames()` was never implemented. Let's continue the discussion at #20867.
