### ISSUE TITLE
Morph targets is broken for large number of vertices

### ISSUE THREAD

**Issue by kareemkermad** [mrdoob/three.js#23204]
Morph target animation breaks the mesh apart when there is over about 100K coordinates (~33K vertices). The image below is taken from the [webgl_morphtargets](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_morphtargets.html) example. I created the box geometry with 75 segments in each dimension. This results in just over 100K coordinates.

`const geometry = new THREE.BoxGeometry( 2, 2, 2, 75, 75, 75 );`

![image](https://user-images.githubusercontent.com/37254625/148998072-34fd884b-0896-4e15-a25d-c7ae507a5dd2.png)

**Platform:**

 - Device: Dekstop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: dev

**Comment by Mugen87** [comment]
Do you mind sharing a screenshot of the result from the following site? https://webglreport.com/?v=2

Does it work if you are using `WebGL1Renderer`?

I've tested your geometry setup on my system and the morphed mesh is rendered as expected.

**Comment by kareemkermad** [comment]
Thanks for responding,
I updated my graphics driver and it seems to work fine now.

**Comment by mrdoob** [comment]
Out of curiosity, what graphics card / drivers?

**Comment by kareemkermad** [comment]
@mrdoob It's a GTX 1080. Looking at the logs, I believe the driver was [471.68](https://www.nvidia.com/Download/driverResults.aspx/179681/en-us), but I'm not certain. It wasn't extremely out of date.

**Comment by zhuyingSeu** [comment]
We met the same problem.The morph target annimation worked well with WebGLRenderer in Ubuntu(GPU:1070Ti,Driver:418.74).But it didn't work with WebGLRenderer in Windows(GPU:1080Ti,Driver:510.06).We tried  WebGL1Renderer in Windows, it worked. @mrdoob @Mugen87
![WebGL2](https://user-images.githubusercontent.com/37655124/151283208-42abda95-ffc3-4856-bca3-8fc19ed8e474.png)

**Comment by Nurygus** [comment]
We also faced the same problem. The morph targets don't work properly with WebGLRenderer in Windows (GPU:RTX3060 Laptop, Driver:27.21.14.6221). Doesn't work on phone too (Adreno 618). Simple [scene](https://v3d.net/3j3) showing the error. @mrdoob @Mugen87
Phone:
![on_phone_same_in_Brave_Chrome_Yandex](https://user-images.githubusercontent.com/100143317/155141161-baf60521-7d49-4293-91ac-0e141e2cff74.jpg)
![phone_webglreport](https://user-images.githubusercontent.com/100143317/155141170-6af9ef95-cd74-4b13-9c56-be529a379eaf.jpg)
Laptop:
![pc_webglreport](https://user-images.githubusercontent.com/100143317/155141181-dda278ec-8445-4e49-aeec-4c98f8a85161.jpg)
