### ISSUE TITLE
Improve example code regarding deep nested code

### ISSUE THREAD

**Issue by jellehak** [mrdoob/three.js#23220]
**Is your feature request related to a problem? Please describe.**

Currently many example use callbacks which lead to a lot of nesting. This makes reading the example harder than it should be. Moreover as most 'extensions' ( aka the jsm folder) already support promises this should also be reflected in the examples. 

**Describe the solution you'd like**

1. Indicate which example could/should be rewritten.
2. Rewrite the example to use 'async / await'. 

**Describe alternatives you've considered**

An alternative solution is to use promises aka 'then(() => {})'.

**Additional context**

Origin of this issue is a discussion in PR #23021

**Comment by mrdoob** [comment]
I prefer async/await better than Promises.

**Comment by looeee** [comment]
There is currently at least one example using async/await.

https://github.com/mrdoob/three.js/blob/dev/examples/webgl_tonemapping.html

**Comment by mrdoob** [comment]
I guess it could just be this?

```js
const texure = await rgbeLoader.loadAsync( 'venice_sunset_1k.hdr' );
const gltf = await gltfLoader.loadAsync( 'DamagedHelmet.gltf' );
```

**Comment by DefinitelyMaybe** [comment]
@looeee 's code above let's both resources start loading at the same time where as yours waits for one before starting the other 😅

**Comment by mrdoob** [comment]
Ah yeah, I forgot about that...

**Comment by jellehak** [comment]
@mrdoob Yes adding async/ awaits would make it look much better. One question: I see that the current `load` methods don't return anything. Wouldn't it better to use this function to return a promise ? ( So the `loadAsync` could be deprecated ). What are your thought on this ?

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/23221#issuecomment-1018685698
