### ISSUE TITLE
Improve example code regarding text contrast

### ISSUE THREAD

**Issue by jellehak** [mrdoob/three.js#23221]
**Is your feature request related to a problem? Please describe.**

Some example overlay text disappears or has very little contrast with the background. For example: 
- https://threejs.org/examples/#webgl_depth_texture

**Describe the solution you'd like**

1. Indicate which examples have low text contrast.
2. Apply a background color to the text.

> Perhaps a global approach is feasibly by changing in https://threejs.org/files/main.css
> (Nice to have) use "prefers-color-scheme" to apply a dark or light theme. https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme. 

**Additional context**

Origin of this issue is a discussion in PR #23021

![image](https://user-images.githubusercontent.com/1216650/149310483-bdd01c38-07f9-42ee-9733-f6b7bd88434c.png)

**Comment by looeee** [comment]
This extension can be useful for testing if text is accessible to color blind people. 

https://chrome.google.com/webstore/detail/lets-get-color-blind/bkdgdianpkfahpkmphgehigalpighjck

**Comment by mrdoob** [comment]
> Some example overlay text disappears or has very little contrast with the background. For example:
>
> * https://threejs.org/examples/#webgl_depth_texture

Can you make a list of all the examples that need fixing?

**Comment by looeee** [comment]
@mrdoob what do you think of adding a semi-opaque background to `#info` in all examples? That would be more foolproof than manually checking all examples now and in the future. 

Quick mockup (I probably made this more opaque than it needs to be though)

![2022-01-14 07_25_04-three js examples](https://user-images.githubusercontent.com/5307958/149430153-070e2ccb-6f47-48c9-a781-5d3a9164711d.png)

**Comment by mrdoob** [comment]
I'd rather add a 1 pixel text shadow to `#info` 😇

**Comment by looeee** [comment]
Like this? 

`text-shadow: 1px 1px 3px black;`

![shadow](https://user-images.githubusercontent.com/5307958/149443078-1f298bee-b0ef-4342-bb8d-c68e97862dfa.png)

**Comment by looeee** [comment]
Definitely an improvement, although it won't help for black text

![shadow2](https://user-images.githubusercontent.com/5307958/149448208-484fd348-97c5-456d-9413-b464eec32af5.png)

Changing the text to white with shadows doesn't help much against a pure white background either. 

![shadow3](https://user-images.githubusercontent.com/5307958/149448350-47607c5d-7679-4f33-b89e-7e9474008af2.png)

**Comment by mrdoob** [comment]
I still think it would be good to have a list of the examples that have this issue before "making all the examples pay".

**Comment by gkjohnson** [comment]
Not necessarily beautiful but using css `mix-blend-mode: difference` ensures the text contrasts with what's under it. I imagine readability would suffer a bit on noisy backgrounds but in a different way to what's happening now:

![image](https://user-images.githubusercontent.com/734200/149453067-8f01fd1c-ca4c-4953-b758-620e7ca502e5.png)

**Comment by Mugen87** [comment]
Maybe we can try to find a more mobile friendly solution which eliminates the text at the top.

How about a new "info" icon that holds information about the example. Meaning when you click/tap it, a separate view/modal/overlay opens and shows the text. The icon could be designed similar to the "source code" icon and placed next to it. 

This design would avoid cluttering when viewing examples like [webgl_animation_skinning_morph](https://threejs.org/examples/webgl_animation_skinning_morph) on mobile. However, when the icon is implemented like the "source code" icon, it would be only visible in the iFrame view.

**Comment by mrdoob** [comment]
I'm also tempted of removing all the info texts from all the examples... less things to maintain... 😇

**Comment by jellehak** [comment]
@mrdoob I went through some examples but almost each where you can move the camera would require changes.

Here are some more examples.

- https://threejs.org/examples/#webgl_animation_keyframes ![image](https://user-images.githubusercontent.com/1216650/150541122-0bdf06a3-c39a-4b48-9125-1a994c625513.png)

- https://threejs.org/examples/#webgl_animation_skinning_additive_blending
![image](https://user-images.githubusercontent.com/1216650/150541232-0d3ec37b-649b-4d5d-93fb-0630b52261d6.png)

- https://threejs.org/examples/#webgl_camera_cinematic
![image](https://user-images.githubusercontent.com/1216650/150541302-914e3517-23ab-487e-8ecf-00473025367d.png)

- https://threejs.org/examples/#webgl_depth_texture
![image](https://user-images.githubusercontent.com/1216650/150542136-72d25a69-0257-48a1-8e25-fd53290bbdfa.png)

Note that also the link color changes amongst various examples.
- https://threejs.org/examples/#webgl_geometry_colors_lookuptable
![image](https://user-images.githubusercontent.com/1216650/150541467-63146195-f62e-4954-968b-5b55cd14b411.png)

**Comment by jellehak** [comment]
@mrdoob Perhaps indeed the best solution is to drop the info text and keep a description in the source code. Or as most example have a dat.gui use it instead like: 

![image](https://user-images.githubusercontent.com/1216650/150545225-43d69d0c-b847-4779-9167-b3deee7d5dd3.png)

**Comment by Mugen87** [comment]
I like the idea of removing the info test. Less to maintain and we don't have to think about an alternative approach.

**Comment by mrdoob** [comment]
Honestly... I think you're trying to find issues where there are not and it's making us waste time.

I'm sure you have good intentions but be aware that our time is limited and we have many other issues to deal with.
