### ISSUE TITLE
TextureLoader has the wrong type for the `url` argument

### ISSUE THREAD

**Issue by TheDutchCoder** [mrdoob/three.js#23224]
**Describe the bug**

The typings for TextureLoader are currently:
```ts
export class TextureLoader extends Loader {
    constructor(manager?: LoadingManager);

    load(
        url: string,
        onLoad?: (texture: Texture) => void,
        onProgress?: (event: ProgressEvent) => void,
        onError?: (event: ErrorEvent) => void,
    ): Texture;

    loadAsync(url: string, onProgress?: (event: ProgressEvent) => void): Promise<Texture>;
}
```

However, the `url` argument can also be of type `File` (like a selected file through an input).

**To Reproduce**

See code.

***Code***
Contrived example in Vue
```html
<input type="file" ref="file" @change="load" />
```

```ts
const file = ref()

const load = (e: Event) => {
  const files = (e.target as HTMLInputElement).files

  if (files.length) {
    const file = files[0]
    const loader = new textureLoader()
    
    loader.load(
      file, // This will throw a type error because it only expects a String.
      (texture) => {},
      undefined,
      (error) => {}
    )
  }
}
```

**Expected behavior**

The type for url to be expended to `String|File`

**Screenshots**

![image](https://user-images.githubusercontent.com/1668207/149344452-5487d9b0-9f1b-40bd-b9a8-3d2d0735f1fb.png)

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: N/A
 - Three.js version: r0.134.0

**Comment by TheDutchCoder** [comment]
Ok that was silly, it was a refactoring issue

**Comment by Mugen87** [comment]
TS related issues should be reported here: https://github.com/three-types/three-ts-types
