### ISSUE TITLE
Controller data changes

### ISSUE THREAD

**Issue by wizVR-zhangjun** [mrdoob/three.js#23250]
addControllLine(scene) {

        //添加手上的两条线

        const geometry = new THREE.BufferGeometry();

        geometry.setFromPoints([new THREE.Vector3(0, 0, 0), new THREE.Vector3(0, 0, - 1)]);

        const line = new THREE.LineSegments(geometry, new THREE.LineDashedMaterial(

            {

                color: 0xffffff,

                dashSize: 0.004,

                gapSize: 0.004

            }));

        line.computeLineDistances();

        line.name = "line";

        line.scale.z = 5;

        this.leftController.add(line);

        scene.add(this.leftController);

        // 在射线的末端添加一个圆球

        const tableGeometry = new THREE.SphereGeometry(0.005);

        const tableMaterial = new THREE.MeshBasicMaterial({

            color: 0xffff00,

        })

        const spheresTag = new THREE.Mesh(tableGeometry, tableMaterial);

        spheresTag.name = 'sphereTag';

        let vect3 = this.leftController.position;

        let inputEndPosition = new THREE.Vector3(vect3.x, vect3.y, vect3.z);

        inputEndPosition.add(this.leftController.getWorldDirection(new THREE.Vector3(0, 0, -1)).multiplyScalar(5 * -1));

        spheresTag.position.copy(inputEndPosition);

        this.leftController.attach(spheresTag);
}
I just generate a 5m line right in front of the left hand controller, and then generate a ball at the other end of the line, and then put my left hand out of the hololens' field of vision, and extend my right hand to make it appear in the field of vision, why the line and the ball Will run to the right hand, I don't know what this is, asking for help.

**Comment by Mugen87** [comment]
> I don't know what this is, asking for help.

Please ask for help at the [forum](https://discourse.threejs.org/).
