### ISSUE TITLE
ShaderMaterial for scene background

### ISSUE THREAD

**Issue by AdilRabbani** [mrdoob/three.js#23259]
Hi, Three.js devs! 👋 I would like to make a feature request. If this has been already requested please ignore and close this issue and link me to the original issue.

What I want to have is the ability to add [ShaderMaterial](https://threejs.org/docs/#api/en/materials/ShaderMaterial) to [scene.background](https://threejs.org/docs/#api/en/scenes/Scene.background). I have been working on an editor similar to [Threejs editor](https://threejs.org/editor/) and would love to add a background with user specified gradient using ShaderMaterial. This would allow a nice gradient as a scene background combining two (or more) colors set by the user, seamlessly. Unfortunately, I couldn't find a straightforward way to achieve this effect. 

I have tried moving the whole scene in a sphere and then applying the shader material to the sphere. This works but since the scene also has OrbitControls, the user can potentially move out of the sphere. I can again set limits to how far the user can zoom out but I don't want to add that restriction.

I have also tried using the [sky shader](https://threejs.org/examples/webgl_shaders_sky.html) implementation which is a really good example of what I would like to achieve but still a little different. I would like to have two (or more) colors as a gradient while the sky shader adds tone mapping and other effects. Of course if I can tweak this example somehow to achieve what I want to do, that would be great! A little guidance in order to achieve that, would be nice! 😄 

I have also tried a very easy implementation for this for a static gradient background which to just change the canvas css property to gradient and change the css itself. I do not want to use a static gradient though. I would like a gradient that is close to a skybox but combining colors as a gradient.

I think the closest example of what I want is to set the background in Threejs editor to `EQUIRECT` and adding a gradient texture to it. This is again a texture and not color using a shader material.

![Capture](https://user-images.githubusercontent.com/15272015/149799941-3e41f78e-6f18-47d6-bd1b-6abe565f2790.PNG)

PS. I am also interested to add this as a feature but haven't delved much into Threejs codebase. With a little guidance on where to add the shader code in order to have this effect for scene background, I might also be able to make a pull request.

**Comment by Mugen87** [comment]
We do not know in advance how a custom material is going to be implemented and if it is appropriate for a scene background. Hence, I do not vote to allow `ShaderMaterial` for `Scene.background`. Your issue can be solved with existing approaches. E.g.

a) Create a gradient texture and assign it to `Scene.background`.
b) Create a plane mesh with your shader material on app level and render it with an orthographic camera.

> I think the closest example of what I want is to set the background in Threejs editor to EQUIRECT and adding a gradient texture to it.

The option `TEXTURE` is the correct one. `EQUIRECT` makes only sense if a texture uses the equirectangular format which is not true for a gradient texture.

**Comment by gkjohnson** [comment]
If you'd like to render a dynamic background using something like a shader material you should also render to a render target and set the scene.background to it, as well. As I see it this is already do-able.
