### ISSUE TITLE
outputEncoding not handled correctly when using sRGB render target in WebGL2

### ISSUE THREAD

**Issue by chubei-oppen** [mrdoob/three.js#23251]
**Describe the bug**

In #23129, the `outputEncoding` is calculated differently from before. I believe the previous way is correct.

**To Reproduce**

See following code and fiddle.

***Code***

```js

const renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );
renderer.outputEncoding = THREE.sRGBEncoding;
renderer.setPixelRatio( window.devicePixelRatio );
document.body.appendChild( renderer.domElement );

const geometry = new THREE.PlaneGeometry( 2, 2 );
const material = new THREE.MeshBasicMaterial();
const mesh = new THREE.Mesh( geometry, material );

const renderTarget = new THREE.WebGLRenderTarget( window.innerWidth, window.innerHeight, { encoding: THREE.sRGBEncoding } );

const camera = new THREE.OrthographicCamera();
camera.position.set( 0, 0, 1 );

new THREE.TextureLoader().load( 'https://threejs.org/examples/textures/crate.gif', (texture) => {

  texture.encoding = THREE.sRGBEncoding;

  material.map = texture;
  renderer.setRenderTarget( renderTarget );
  renderer.render( mesh, camera );

  material.map = renderTarget.texture;
  renderer.setRenderTarget( null );
  renderer.render( mesh, camera );

} );

```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/st06pgbc/)
* [jsfiddle-dev](https://jsfiddle.net/0wjhn1pu/1/)

**Expected behavior**

`dev` should behave the same as `r136`.

**Screenshots**

`r136`
![image](https://user-images.githubusercontent.com/31505943/149701139-46401698-d82d-4954-b133-88b629ea99fd.png)

`dev`
![image](https://user-images.githubusercontent.com/31505943/149701144-de1b2277-b38d-4b92-8172-2358bc90bcd6.png)

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome
 - Three.js version: dev

**Comment by chubei-oppen** [comment]
Looks like the same problem also exists at https://github.com/mrdoob/three.js/blob/6f7a821dfab7501f461db9c977560ac11afd14e5/src/renderers/WebGLRenderer.js#L1418.

**Comment by Mugen87** [comment]
The inline shader sRGB encode only needs to be done for the default framebuffer. Let me fix this with a PR.

**Comment by Mugen87** [comment]
I want to make clear that the fiddles are great for reproducing the issue.

However, the fiddles are probably no good approach for code used in production. In almost all cases, you only want to apply sRGB encoding when rendering to screen. Otherwise you encode/decode sRGB values in each pass since normally you want linear values in the shaders. This is waste from my point of view.

The fiddle should actually look like so: https://jsfiddle.net/2j4nzcra/

**Comment by Mugen87** [comment]
Just a heads up:

The plan is to remove all the inline output encoding and tone mapping from all materials. The renderer will internally use an additional FX pass to apply sRGB conversion and tone mapping but ONLY if rendering to screen.

All other use cases have to be handled by the application.

**Comment by Mugen87** [comment]
Related #23019.

**Comment by chubei-oppen** [comment]
> The fiddle should actually look like so: https://jsfiddle.net/2j4nzcra/

In production I'll still use code like the original fiddle.

Per my understanding, the purpose of allowing framebuffer color attachment format to be `srgb8` is to make the limited representation power of 8 bit color better fit the perception of human eye. Encoding and decoding have performace overhead but often is worth it, especially when the scene is dark. I can make a fiddle with dark gradients to show the difference but you probably know what it's going to be like so I'll save the effort.

**Comment by Mugen87** [comment]
I've referred with my comment to FX setups with multiple passes. sRGB should be applied at the end. Intermediate frame buffers should be linear.

**Comment by chubei-oppen** [comment]
> I've referred with my comment to FX setups with multiple passes. sRGB should be applied at the end. Intermediate frame buffers should be linear.

Sorry which comment?

**Comment by Mugen87** [comment]
https://github.com/mrdoob/three.js/issues/23251#issuecomment-1014267819

**Comment by chubei-oppen** [comment]
Yes, we want linear values in the shaders, but srgb values in 8 bit images. I'll make a fiddle tomorrow to show the case.

**Comment by vanruesc** [comment]
To provide some additional information on the topic:

Storing linear colors in 8bit buffers causes color degradation and banding. Linear colors should only be stored with at least 12 bits of precision per channel to avoid this ([reference](https://blog.demofox.org/2018/03/10/dont-convert-srgb-u8-to-linear-u8/)).

> I've referred with my comment to FX setups with multiple passes. sRGB should be applied at the end. Intermediate frame buffers should be linear.

This is correct, but it requires `HalfFloatType` buffers to avoid banding which can have an impact on performance and may not be supported on some devices. Unity stores intermediate results in 8bit buffers for non-HDR post-processing setups by converting colors from linear to sRGB and back to linear ([reference](https://docs.unity3d.com/Manual/LinearRendering-GammaTextures.html), see "Linear color space and non-HDR"). This obviously works best with hardware encoding/decoding support via [SRGB8_ALPHA8](https://developer.mozilla.org/en-US/docs/Web/API/EXT_sRGB) buffers, which was only recently added to `three`.

**Comment by chubei-oppen** [comment]
To show how the effect looks like in three:

[linear framebuffer](https://jsfiddle.net/nyqvdjf2/2/). Color is quantized in linear space then converted to sRGB space for displaying. Notice the banding effect.
![image](https://user-images.githubusercontent.com/31505943/149861705-f3d8286c-cbf3-4d32-a337-8cf043694849.png)

[srgb framebuffer](https://jsfiddle.net/nyqvdjf2/3/). Color is first converted to sRGB space then quantized and displayed. Much smoother.
![image](https://user-images.githubusercontent.com/31505943/149861747-7a63a6dc-0f9d-4b4a-a420-8b28721c000e.png)
