### ISSUE TITLE
How to set big texture image it's size is greater than canvas allowed size(8192x4096) in browser.

### ISSUE THREAD

**Issue by Tuvshinzaya-Mendbayar** [mrdoob/three.js#23266]
Hi everyone,
I have a issue for big canvas texture issue. I'm trying to set (16384x8192) canvas material to SphereGeometry. But it's auto resized 8192x4096). Is there any chance to set huge size texture ?

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
