### ISSUE TITLE
WebGLTextures: Unsupported texture encoding: 3001 on VideoTexture and THREE.sRGBEncoding

### ISSUE THREAD

**Issue by arpu** [mrdoob/three.js#23270]
webgl_materials_video_webcam.html with
renderer.outputEncoding = THREE.sRGBEncoding;

VideoTexture is to light setting texture.encoding = THREE.sRGBEncoding;
 Video looks fine but get many errors in the console:

```
three.module.js:23719 THREE.WebGLTextures: Unsupported texture encoding: 3001
```

**Expected behavior**
no console error from https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLTextures.js#L1677

**Platform:**

 - Device: [Desktop]
 - OS: [Linux]
 - Browser: [Chrome]
 - Three.js version: [dev, d938b69cfba64c8858d53b12b5d59c382636c0fd]

**Comment by Mugen87** [comment]
Thanks for reporting!
