### ISSUE TITLE
darker textures in WebxrSession in latest dev git 

### ISSUE THREAD

**Issue by arpu** [mrdoob/three.js#23278]
darker textures in WebxrSession in latest dev git 

**To Reproduce**

https://raw.githack.com/mrdoob/three.js/dev/examples/?q=webxr#webxr_vr_ballshooter

**Screenshots**

![Bildschirmfoto von 2022-01-19 18-35-50](https://user-images.githubusercontent.com/14173/150184156-9b2845ed-ff87-4958-9524-aef0095f6d87.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Linux, Android]
 - Browser: [Chrome]
 - Three.js version: [dev, 3280febab086be367ee80d8fbf15361872c64a8e]

**Comment by arpu** [comment]
revert https://github.com/mrdoob/three.js/commit/63f7bebed6b1dd287110b56989e34cd6008aa695 fixed the problem

**Comment by cabanier** [comment]
@Mugen87 Is it because the default framebuffer for WebXR isn't `null`?

**Comment by Mugen87** [comment]
The mentioned line only influences the output decode in the shader. If a render target is set, the output decode is disabled.

When using a sRGB encoded render target, WebGL should automatically convert to sRGB. Is the default framebuffer for WebXR a sRGB framebuffer?

**Comment by cabanier** [comment]
It depends on the output encoding. See https://github.com/mrdoob/three.js/blob/dev/src/renderers/webxr/WebXRManager.js#L284

It's needed  there because the framebuffer that is created for multisampling, is created with that encoding. Maybe it shoudn't in case of the default framebuffer?

**Comment by Mugen87** [comment]
> Maybe it shoudn't in case of the default framebuffer?

Can we give this a try?

**Comment by Mugen87** [comment]
If we can't fix this in `WebXRManager`, we have to add a flag to the XR render targets so we can identify them in `WebGLRenderer` and `WebGLPrograms`. It would then be possible to restore the old behavior and add the now missing linear-sRGB conversion (the reasons why the image is too dark).

**Comment by cabanier** [comment]
WebXR Layers do allow you to specify the encoding. However, the oculus implementation has some bugs in this area that I'm trying to fix. For now, you can assume that you always write linear values.
However, the implementation of three before I added multisample_render_to_texture rendered to a framebuffer backed by renderbuffers which was then blitted to a non-multisample WebXR texture. This did gamma correction which resulted in lighter colors that some people preferred. I suspect that is where @HexaField's original bug and sRGB changes to the WebXRManager came from.

> If we can't fix this in WebXRManager, we have to add a flag to the XR render targets so we can identify them in WebGLRenderer and WebGLPrograms.

I *think* that's what we need to do. Ideally, I fix the bugs in our WebXR implementation so three doesn't need this special behavior.

**Comment by mrdoob** [comment]
> which resulted in lighter colors that some people preferred

In the world of PBR 3D, it's not about "preference"... it's about "correctness" 🤓

**Comment by Mugen87** [comment]
I've filed a PR to restore the old behavior. 

I agree with @mrdoob that we should head for the correct solution which means a proper sRGB workflow. If colors are perceived as too dark, devs have to update their lighting.

However, it's not clear to me whether the sRGB workflow in WebXR is right and the colors as they should be. I did not have the chance so far to test this with a Quest 2.

**Comment by cabanier** [comment]
The issue is that there is no correct behavior defined in the spec.

The Oculus browser sets the primaries to sRGB and the gamma correction *should* come from the texture type. However, the gamma correction seems to be incorrectly applied inside the compositor. I'm working with that team to get to the bottom of this.
Once the workflow is fixed/clarified, I will update the spec and our implementation.
