### ISSUE TITLE
Loaders: Ensure all loaders properly label and convert color textures and colors to sRGB / Linear correctly

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#23283]
**Is your feature request related to a problem? Please describe.**

From what I can tell these are the loader examples that still are not setting renderer.outputEncoding = sRGBEncoding on the page meaning they don't appropriately set the model color spaces for linear lighting calculations on load where I think the color space should be known at parse time:

**Material Colors & Textures**
- [x] ColladaLoader examples (#23401)
- [x] OBJLoader examples (#23296)
- [x] SVGLoader (example logic only) (#23280)
- [x] ColladaExporter (#23400)
- [x] KMZLoader Example (#23401)
- [x] FBXLoader examples (#25441)
- [ ] IFCjs example (#25442)
- [x] MMDLoader example (#25889)
- [x] VOXLoader example (#25849)
- [x] LottieLoader example (#25849)
- [x] VRMLLoader example (#26111) 

**Vertex Colors**
- [x] ColladaLoader (#23401)
- [x] ColladaExporter (#23400)
- [x] DRACOLoader (#25390)
- [x] DRACOExporter (#25390)
- [x] FBXLoader(#25441)
- [x] OBJLoader (#23340)
- [x] OBJExporter (#23374)
- [x] PCDLoader (#26119) 
- [x] PLYLoader (#23342)
- [x] PLYExporter (#23399)
- [x] STLLoader (#26120)
- [x] VRMLLoader (#26111) 
- [x] VTKLoader (##26120)
- [x] XYZLoader (#26119) 

I was taking a look at ColladaLoader and OBJLoader, as well. It doesn't look like there's very explicit documentation on color spaces for these formats and they're more specification by convention. Given that our demos don't adjust the default output color space for the renderer it seems like the assumption is that the textures and colors are sRGB. Is there any evidence or example models that show this isn't always the right thing to do?

**Describe the solution you'd like**

All loaders look correct when setting `WebGLRenderer.outputEncoding` to `sRGBEncoding` by appropriately labeling all color textures and converting colors to Linear before setting materials.

**Describe alternatives you've considered**

--

**Additional context**

#23272

#23280

**Comment by Mugen87** [comment]
> I was taking a look at ColladaLoader and OBJLoader, as well. It doesn't look like there's very explicit documentation on color spaces for these formats and they're more specification by convention.

There is a note in the [Collada spec](https://www.khronos.org/files/collada_spec_1_5.pdf) that color space information can added to `<hint>` attribute. It says:

> If this element or a higher precedence element is not present then use a common format R8G8B8A8 with linear
color gradient, not sRGB.

**Comment by Mugen87** [comment]
The model is correct and the left image is right.

If you just set `outputEncoding` to `sRGBEncoding`, the sRGB workflow is incomplete.

**Comment by Mugen87** [comment]
Meaning we have to update the loader to hack in sRGB support.

**Comment by Mugen87** [comment]
I wonder if it is really a good idea to force sRGB with 3D formats that do not properly support it 🤔 .

**Comment by gkjohnson** [comment]
> If you just set outputEncoding to sRGBEncoding, the sRGB workflow is incomplete.

Can you explain this? It should _never_ be correct to display the canvas as Linear on the page. Is the Collada format assuming a linear output color to the display? If interpreting Collada textures as linear colors only looks correct if you are not transforming them before outputting to an sRGB display then I don't understand how they can correctly be considered linear.

**Comment by Mugen87** [comment]
AFAICT, the Collada spec does not really care about color spaces. Most times applications just load the Collada, parse the colors/load textures and display the values as they are.

You are right with your assumption that the textures are not linear. When you inspect the color profiles of Collada textures, they are usually sRGB.

If we want to display sRGB colors, we have to make assumptions when loading the Collada asset which are not necessarily true. For example the standard does not explain in what color space material or light colors are. 

Because of this,  I would not touch loaders with no clear color space specification. If we default `outputEncoding` to `sRGBEncoding` at some point, I suggest to set `LinearEncoding` to all Collada examples.

Devs who want a proper color space workflow should work with glTF.

**Comment by gkjohnson** [comment]
I'm certainly not advocating against preferring glTF when possible but the point of this issue is to get the three.js loaders to behave consistently in the correct labeling and conversion of colors. If it's demonstrable that Collada files are specifying colors and textures in sRGB then they should be loaded such that they behave consistently with the three.js renderer settings. As it is you cannot just load a glTF model and Collada model in the same scene and have them look correct. I see there was an [issue on the forum related to the editor in this regard](https://discourse.threejs.org/t/color-space-issue-with-collada-models-in-editor/27096), as well.

When it comes to some of these specs that are ambiguous about color spaces (OBJ, Collada) my assumption has always been that colors and color textures were specified as sRGB just because of the limitations of Linear colors when converting to sRGB for display and the age of the formats. In my experience OBJ files are the same. If it really is ambiguous in practice and there are use cases, example files, or exporters out there using linear textures and colors then maybe a Loader flag can be added to set the color space to load as. Otherwise it sRGB colors seems like the more likely assumption.

**Comment by mrdoob** [comment]
I agree with @gkjohnson. I think it's fair to assume that the colors and textures in obj and collada files are in srgb (unless specified somehow).

And yes, we should aim to set `WebGLRenderer.outputEncoding` to `sRGBEncoding` by default. It'll be easier to assume that anything that it's passed to the renderer is in linear. Easier to spot bugs that way.

**Comment by gkjohnson** [comment]
It occurs to me that Vertex colors would need to be converted, as well, which might not be such an easily "undoable" change for anyone relying on them being sRGB right now since three.js relies on them being linear. I imagine this would affect both ColladaLoader and PLYLoader, at least. Not sure if we have any vertex colored test models, though.

**Comment by scurest** [comment]
FWIW, you may want to know that Blender (at least recent versions) exports material colors (eg. Kd) as linear (obj, dae), but vertex colors as sRGB (dae). I don't think this is by intent (this is how it stores it internally, so probably just no one ever thought about it) but it is how it works.

(Personally I agree with gkjohnson that sRGB should be the default assumption.)

**Comment by gkjohnson** [comment]
> FWIW, you may want to know that Blender (at least recent versions) exports material colors (eg. Kd) as linear (obj, dae)

Oh interesting... Is it documented anywhere? Here's a Blender help post from 2019 that seems to discuss the issue and identifies that the output color space changed in Blender 2.8:

https://blenderartists.org/t/rgb-values-wrong-when-exporting-as-obj/1179228/9

The answers from the post are a bit disappointing with the solutions basically amounting to "edit the files directly so they conform to your engine". So much for standards 😁. Either way it doesn't sound like there's a strong rationale for their output color space there.

It would be good to look at what other environments do in terms of interpreting color spaces for these formats but unfortunately I don't have the bandwidth to put a list like that together.

**Comment by gkjohnson** [comment]
At this point I've updated all the loaders I'm familiar with. It's possible that externally maintained loaders (IFC) should wait to upgrade until something like #23392 is figured out. This should get most all of the canonical three.js loaders loading into a consistent color space so it should be easier to transition / catch issues with any future color space management changes.

@looeee would you be able to convert FBXLoader to convert all material and light Color instances and vertex color to Linear on load? And label all color texture maps as sRGB? According to [this documentation](https://docs.microsoft.com/en-us/azure/remote-rendering/reference/material-mapping) all colors in FBX are expected to be sRGB (credit to WestLangley for the link).

And @takahirox maybe MMDLoader should do the same so everything works with `renderer.outputEncoding = sRGBEncoding`?

Other than that I'm unfamiliar with the remaining loaders I listed (Vox, VRML, VTK, PCD, GCode) so I'm not sure if they need to be changed.

**Comment by donmccurdy** [comment]
The `.drc` files (created by the Draco library) don't have textures or materials, so I think you must be talking about a model with vertex colors? I don't think there is any rule about what color space its vertex colors must be in, so custom conversions may sometimes be necessary. But since the Draco library only accepts PLY and OBJ files as input, and we already do conversions for those formats...

https://github.com/mrdoob/three.js/blob/7fc4d1e93360fc31aa783466cb2c5b6f3c6361f6/examples/jsm/loaders/OBJLoader.js#L534-L538

https://github.com/mrdoob/three.js/blob/7fc4d1e93360fc31aa783466cb2c5b6f3c6361f6/examples/jsm/loaders/PLYLoader.js#L477-L481

... I think it would be appropriate for us to do the same conversion in DRACOLoader *if* we are loading a .drc file. The conversion is not necessary when using DRACOLoader to decode the contents of a Draco-compressed glTF file with the `dracoLoader.decodeDracoFile(...)` method.

@Takieddin would you want to provide an example file, and/or open a PR for the conversion?

**Comment by Takieddin** [comment]
@donmccurdy 
here are the files
[loot.zip](https://github.com/mrdoob/three.js/files/10548668/loot.zip)

**Comment by donmccurdy** [comment]
@Takieddin thanks! I've opened a PR:

- https://github.com/mrdoob/three.js/pull/25390

One goal of this issue is for all loaders to assign the correct color space information, where "correctness" involves the definitions and assumptions given on the [color management guide](https://threejs.org/docs/#manual/en/introduction/Color-management). You'll want to keep this renderer output setting enabled, unless you're (a) not rendering to a display, or (b) have some other color management workflow defined.

```javascript
renderer.outputEncoding = sRGBEncoding
```

**Comment by nightgryphon** [comment]
Got trouble with mandatory unconditional color conversion sRGB->Linear while loading OBJ+MTL model exported by Blender to AFRAME. Is it possible to add an option to specify/override the color space assumed for OBJ+MTL while loading so all relying projects can achieve correct color management?

The code causing trouble is `examples/jsm/loaders/MTLLoader.js` method `createMaterial_( materialName )` which perform unconditional color conversion

```
case 'kd':
		// Diffuse color (color under white light) using RGB values
		params.color = new Color().fromArray( value ).convertSRGBToLinear();

...etc...
```

**Comment by donmccurdy** [comment]
Confirmed (in Blender 3.5) that the exported MTL file writes the diffuse color in sRGB-Linear, not sRGB.  I haven't checked what it does for vertex colors yet.

I don't believe there's any canonical answer for what OBJ/MTL _should_ use, unfortunately, so this might easily vary from exporter to exporter. We didn't edit any OBJ/MTL files when doing these updates, so presumably our own OBJ/MTL files use sRGB as originally expected.

Possible workaround would be to create an option like:

```js
const loader = new OBJLoader();
loader.sourceColorSpace = THREE.LinearSRGBColorSpace;
loader.load( 'path/to/scene.obj', ... );
```

This defines the _source_ color space, the _target_ is (always) the current three.js working color space. I certainly wouldn't want to provide this option for file formats that do have a well-established color space convention. But I'm open to providing the option for OBJ/MTL, if others agree.

**Comment by nightgryphon** [comment]
I've also found recent Blender can export PBR extensions in MTL so it also can be perfect to get an extra option to use MeshPhysicalMaterial instead of MeshPhongMaterial 
https://benhouston3d.com/blog/extended-wavefront-obj-mtl-for-pbr/

**Comment by nightgryphon** [comment]
Automatic detection and switch to non-MeshPhongMaterial in general sounds good BUT it will unexpectedly affect code assuming MeshPhongMaterial for OBJ loaded models. So there should be an option to force specify the exact material model to use.

Right now i'me trying to implement custom MTLLoader and  faced exactly this issue with automatic material model switch. My existing code use envMap and envMapIntensity for OBJ models and switching some materials to non-PhongMaterial significantly change SOME RANDOM MODELS which trigger automatic model change while others stay as intended. This can confuse a lot. So there should be the way to exactly contros what is going on while load OBJ.

**Comment by donmccurdy** [comment]
I would recommend continuing discussion in the thread linked here; support for PBR materials in OBJ is not particularly to this color management thread.

- https://github.com/mrdoob/three.js/issues/7519
