### ISSUE TITLE
mmdloader can't load single pose properly

### ISSUE THREAD

**Issue by Xposeder** [mrdoob/three.js#23287]
**Describe the bug**

mmdloader can't load single pose properly

**To Reproduce**

1. Go to [this example](https://threejs.org/examples/?#webgl_loader_mmd_pose)
2. change the pose to any
3. nothing happened, that's the problem

***Live example***

[webgl_loader_mmd_pose](https://threejs.org/examples/?#webgl_loader_mmd_pose)
**Expected behavior**

load pose properly ,like 0.130 version

**Screenshots**

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome97
 - Three.js version: [r136]

**Comment by Mugen87** [comment]
It seems it works up to `r133`: 

https://raw.githack.com/mrdoob/three.js/r133/examples/webgl_loader_mmd_pose.html

With `r134`, the post can't be changed anymore.

https://raw.githack.com/mrdoob/three.js/r134/examples/webgl_loader_mmd_pose.html

**Comment by takahirox** [comment]
Probably this one https://github.com/mrdoob/three.js/pull/22510#discussion_r714240430

**Comment by Mugen87** [comment]
Reverting the usage of `fetch()` in `FileLoader` actually solved the issue.

/ping @gkjohnson @DefinitelyMaybe

**Comment by ycw** [comment]
preview
https://raw.githack.com/ycw/three.js/fileloader-encoding-preview/examples/webgl_loader_mmd_pose.html

**Comment by Xposeder** [comment]
Thank you for your willingness to solve this problem!

**Comment by DefinitelyMaybe** [comment]
I'm glad this was found and I'm sorry as I didn't know about this case beforehand.
