### ISSUE TITLE
Rendering a scene with OutlinePass differs between THREE versions 0.126 and 0.136 given the same scene setup

### ISSUE THREAD

**Issue by tomfree** [mrdoob/three.js#23284]
Rendering a scene with OutlinePass differs between THREE versions given the same code 

Three@0.126: https://codepen.io/thogu/pen/RwLmOXd - is pretty light 
Three@0.136: https://codepen.io/thogu/pen/xxXNBmV - is pretty dark 

The colors at 136 seem to match the result I get when not  using WebGLMultisampleRenderTarget  with 126. See:
https://codepen.io/thogu/pen/poWmmzN

Steps to reproduce the behavior / code : see the codepens

**Expected behavior**
- same rendering for 0.126 and 0.136 version of three.js

**Screenshots**
- see the codepens

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: 0.126 and 0.136

Thanks for the awesome Three.js - really love it

**Comment by Mugen87** [comment]
You need a gamma correction pass at the end of your pass chain: https://jsfiddle.net/uja3pL7e/

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for more help.

**Comment by tomfree** [comment]
Really? Shouldn't this be the same in both cases?
And thanks for the fast reply

**Comment by Mugen87** [comment]
The sRGB workflow has changed in that regard is now more consistent.
