### ISSUE TITLE
GLTFLoader parsing with createImageBitmap

### ISSUE THREAD

**Issue by Diyou** [mrdoob/three.js#23299]
I found a check in the GLTFParser to exclude Safari and Firfox to use the TextureLoader instead of the ImageBitmapLoader in the code
```js
if ( typeof createImageBitmap !== 'undefined' && /Firefox|safari/.test( navigator.userAgent ) === false ) {

	this.textureLoader = new ImageBitmapLoader( this.options.manager );

} else {

	this.textureLoader = new TextureLoader( this.options.manager );

}
```

The regex unfortunately filters any chromium based browser because they include 'safari' in their userAgent.

I'd prefer to pass a Loading Manager for the parser but expanding the regex would be a quick fix.
```js
if ( typeof createImageBitmap !== 'undefined' && /Firefox|^((?!chrome|android).)*safari/i.test( navigator.userAgent ) === false ) {
...
```

**Comment by Mugen87** [comment]
That's indeed an issue. Verified with Chrome on macOS.

Do you mind creating a PR with your fix? It seems the suggested regex is commonly used to detect Safari: https://stackoverflow.com/a/23522755/5250847

**Comment by Diyou** [comment]
Added a PR #23305
