### ISSUE TITLE
Duplicated AR button in misc_exporter_usdz  example

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#23306]
Redundant AR button on Safari

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**To Reproduce**

1. Go to ['AR sample'](https://threejs.org/examples/?q=usdz#misc_exporter_usdz)
2. See 2 icon of AR overlaid

**Expected behavior**

Single AR button

**Screenshots**

**Platform:**

 - Device: [Mobile]
 - OS: [iOS 15]
 - Browser: [Safari]
 - Three.js version: [main]

**Comment by tasamai** [comment]
Hey, Looks fine to me. Can only see one button on all platforms

**Comment by rawwerks** [comment]
![image](https://user-images.githubusercontent.com/19483938/150709753-e1273082-8e99-401c-95b4-9a546a999b3a.jpeg)

There is a smaller icon overlaid for me as well.

**Comment by tasamai** [comment]
What browser are you using?

**Comment by rawwerks** [comment]
> What browser are you using?

Mine is from iPad | iOS 14.8.1 | Safari

**Comment by whatisor** [comment]
this behavior is very strange.
I overcome it by using empty image. Safari detect file with usdz format and auto add icon for it.

**Comment by Mugen87** [comment]
This guide https://webkit.org/blog/8421/viewing-augmented-reality-assets-in-safari-for-ios/ says:

> Safari decorates such links with a 3D-cube badge in the top-right corner, to show the user there is an AR experience.

I can confirm that this badge appears correctly with the following examples:

https://developer.apple.com/augmented-reality/quick-look/

It's the same badge that appears now in the `three.js` demo. So the solution is to update `examples/files/arkit.png`.

**Comment by Mugen87** [comment]
After a closer look at the documentation it seems `misc_exporter_usdz` somewhat misuses the badge. The badge is mainly intended for links with thumbnails and does not when you already viewing the asset in WebGL/WebGPU.

**Comment by mrdoob** [comment]
Yep... It's a hack.

But it's the only way to display a button that launches into AR...

**Comment by elalish** [comment]
We do the  same as  @whatisor; just create an empty  image to avoid Safari's default behavior.

**Comment by mrdoob** [comment]
Ah, I missed that comment 👍

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/464a5f0381924cb7448f8f51cd8ffe1ee0dc243d should fix this.

**Comment by mrdoob** [comment]
@whatisor what's the width/height of the transparent image?

**Comment by whatisor** [comment]
can be 128x128 but need some align for centering.
However, I saw you applied Fix to example. You need to check if it is Safari.
Chrome and other browser will not have this auto icon.
