### ISSUE TITLE
Why Migration Guide 135 → 136 has two `DataTexture2DArray`s ?

### ISSUE THREAD

**Issue by gonnavis** [mrdoob/three.js#23303]
Hello, why Migration Guide 135 → 136 has two `DataTexture2DArray`s ?

https://github.com/mrdoob/three.js/wiki/Migration-Guide

> If you create an instance of DataTexture, DataTexture2DArray or DataTexture2DArray, you have to set needsUpdate to true as soon as the texture data are ready.

Is the second redundant or should be `DataTexture3D` ?

**Comment by Mugen87** [comment]
It should be `DataTexture3D`. Already fixed.
