### ISSUE TITLE
Raycasting inaccuracy with Line BufferGeometry. Undocumented hidden bounding box?

### ISSUE THREAD

**Issue by Jakobud** [mrdoob/three.js#23313]
**Describe the bug**

When drawing lines using `LineBasicMaterial` and `BufferGeometry`, Raycasting on the Lines seems very inaccurate. It's almost as if the lines have a large invisible bounding box around them that triggers the raycasting.

When using a typical raycasting example using the mouse cursor, the Lines appear to trigger raycasting when the mouse cursor gets near the line instead of directly on top of it.

**To Reproduce**

1. Here is an example JSFiddle: https://jsfiddle.net/3hrqmke8/3/
2. The scene contains 3 objects: two spheres and one line (BufferGeometry) between them
3. Raycasting intersection detection occurs when the mouse cursor is moved
4. Intersected objects are highlighted red
5. Move the cursor in the scene. When you get near the line (but not on top of it) intersection is triggered when it shouldn't be.
6. The intersection of the spheres appears to be working fine.

***Code***
(this is just a copy of the JSFiddle)
```js
import * as THREE from 'https://cdn.skypack.dev/three';

import { OrbitControls } from 'https://cdn.skypack.dev/three/examples/jsm/controls/OrbitControls.js';

let camera, scene, renderer, controls;
const amount = 10

const raycaster = new THREE.Raycaster();
const mouse = new THREE.Vector2(1, 1);
const red = new THREE.Color().setHex(0xff0000);

init();
animate();
  
function init () {
  camera = new THREE.PerspectiveCamera(60, window.innerWidth / window.innerHeight, 0.1, 100);
  camera.position.set(amount, amount, amount);
  camera.lookAt(0, 0, 0);

  scene = new THREE.Scene();

  const light = new THREE.HemisphereLight(0xffffff, 0x888888);
  light.position.set(0, 1, 0);
  scene.add(light);

  (function () {
    const geometry = new THREE.SphereGeometry(1, 16, 16);
    const material = new THREE.MeshBasicMaterial({ color: 0xffffff });
    material.wireframe = true;
    const cube = new THREE.Mesh(geometry, material);
    cube.position.set(5, 0, 0);
    scene.add(cube);
  })();

  (function () {
    const geometry = new THREE.SphereGeometry(1, 16, 16);
    const material = new THREE.MeshBasicMaterial({ color: 0xffffff });
    material.wireframe = true;
    const cube = new THREE.Mesh(geometry, material);
    cube.position.set(-5, 0, 0);
    scene.add(cube);
  })();

  (function () {
    const material = new THREE.LineBasicMaterial({ color: 0xffffff });
    const points = [
      new THREE.Vector3(-5, 0, 0),
      new THREE.Vector3(5, 0, 0)
    ];
    const geometry = new THREE.BufferGeometry().setFromPoints(points);
    scene.add(new THREE.Line(geometry, material));
  })();

  // Renderer
  renderer = new THREE.WebGLRenderer();
  renderer.setPixelRatio(window.devicePixelRatio);
  renderer.setSize(window.innerWidth, window.innerHeight);
  document.body.appendChild(renderer.domElement);

  // Orbit Controls
  controls = new OrbitControls(camera, renderer.domElement);
  controls.enableZoom = true;
  controls.enablePan = true;

  document.addEventListener('mousemove', onMouseMove);
}

function onMouseMove (event) {
  event.preventDefault();

  mouse.x = (event.clientX / window.innerWidth) * 2 - 1;
  mouse.y = -(event.clientY / window.innerHeight) * 2 + 1;
}

function animate () {
  requestAnimationFrame(animate);

  controls.update();

  raycaster.setFromCamera(mouse, camera);

  const intersection = raycaster.intersectObjects(scene.children);

  if (intersection.length > 0) {
    intersection[0].object.material.color = red;
  }

  renderer.render(scene, camera);
}
```

***Live example***

* https://jsfiddle.net/3hrqmke8/3/

**Expected behavior**

Raycasting intersection for a line should only happen when you are directly on the line, not when you are near it.

** Screenshots **

![image](https://user-images.githubusercontent.com/87356/150742035-d7850a8a-c55e-414a-b106-209cb116169f.png)

**Platform:**

 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Three.js version: r136

**Comment by Jakobud** [comment]
As I'm investigating this behavior, it almost appears that Lines created in this way have almost like some sort of invisible bounding box around them. Line a cylinder of radius 1, with the Line projecting through the center of the cylinder. I don't see anything like this in the documentation.

**Comment by Mugen87** [comment]
There is no invisible bounding volume in place. It's just a threshold value that influences the intersection test of lines. You can modify this threshold by updating the respective property of [Raycaster.params](https://threejs.org/docs/index.html?q=raycas#api/en/core/Raycaster.params).

**Comment by Jakobud** [comment]
Yo! I did not realize this was a thing. Thank you! I have been knocking my head like crazy on this one. So it looks like ya the threshold is default to 1 world unit, which means that it was intersecting when within 1 world unit of the line, which is exactly what I was estimating it at. Thank you!
