### ISSUE TITLE
HTMLMesh from VR Example not able to dispose texture

### ISSUE THREAD

**Issue by Fluqz** [mrdoob/three.js#23319]
**Describe the bug**
Im using the HTMLMesh class from this [VR Examples](https://threejs.org/examples/?q=vr#webxr_vr_sandbox). I notice heavy lags when instanciating multiple HTMLMeshes. When Trying to dispose the texture, the following error occurs.

```
ERROR TypeError: event.data is undefined
dispatchEvent HTMLMesh.js:54
dispose three.module.js:1648
```

I bypass the error. see other discussion [here](https://discourse.threejs.org/t/examples-htmlmesh-dispose-texture/34040), but the lag remains. Im not able to dispose the whole Mesh.

It can be reproduced by instanciating a HTMLMesh and trying to dispose the texture.

`HTMLMesh.material['map'].dispose()` This will throw the error.

To reproduce lag
  ```
  let array: HTMLMesh[] = []

    for(let i = 0; i < 200; i++) {

         let mesh = new HTMLMesh(element)

      array.push(mesh)
    }

    for(let mesh of array) {

        mesh.geometry.dispose()
        mesh.material.map.dispose() // <- Error
        mesh.material.dispose()
    }
```

I noticed that the lag is mostly noticable when orbiting around. There are probably too many Events registered! But its not possible to remove the eventlisteners!

 - Device: Macbook Pro 21
 - OS: Macos Monterey
 - Browser: Firefox
 - Three.js version: r131 (Also tested HTMLMesh.js version from r136)

**Comment by Fluqz** [comment]
Hey thanks for the fast fixing! 

Is this fixing the lag issue as well? 
HTMLMesh is registering four events, but they are never removed anywhere. I was able to avoid lag by removing the events of HTMLMesh completely.

Lag always occurs when using OrbitControls between mousedown and mouseup. While OrbitControls damping afterwards is rendering smoothly. 

```

	constructor( dom ) {

                ...

		function onEvent( event ) {

			material.map.dispatchEvent( event );

		}

                // Removing these lines fixes lag
		this.addEventListener( 'mousedown', onEvent );
		this.addEventListener( 'mousemove', onEvent );
		this.addEventListener( 'mouseup', onEvent );
		this.addEventListener( 'click', onEvent );

	}

```

Should I make a new Issue for this?

**Comment by Mugen87** [comment]
NO, not necessary. I've updated the PR so it does not automatically close the issue when merged.

The PR only ensures that `dispose()` works as expected and does not throw a runtime error.
