### ISSUE TITLE
RGB565 textures broken since r136

### ISSUE THREAD

**Issue by Ithamar** [mrdoob/three.js#23318]
**Describe the bug**

Since r136,  RGB565 textures will be rendered black instead of their proper colors.

**To Reproduce**

Use the code below to show a simple RGB565 texture. See only blackness. Change threes version to any version before r136, see the plane with a red, green, blue, and white rectangle.

***Code***

```js
      import * as THREE from 'https://cdn.skypack.dev/three@0.135.0'

      const scene = new THREE.Scene();
      const camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );
      
      const renderer = new THREE.WebGLRenderer();
      renderer.setSize( window.innerWidth, window.innerHeight );
      document.body.appendChild( renderer.domElement );
      
        const data = new Uint16Array([
          0x001F, 0xF800,
          0x07E0, 0xFFFF,
        ])
        const map = new THREE.DataTexture(data, 2, 2, THREE.RGBFormat, THREE.UnsignedShort565Type)
      
      const geometry = new THREE.PlaneGeometry();
      const material = new THREE.MeshBasicMaterial( { map } );
      const obj = new THREE.Mesh( geometry, material );
      scene.add( obj );
      
      camera.position.z = 1;
      
      function animate() {
      requestAnimationFrame( animate );
      
      renderer.render( scene, camera );
      };
      
      animate();
```

**Expected behavior**

Not display any RGB565 texture as black.

**Comment by sciecode** [comment]
This appears to be an unintended side effect of deprecating `RGBFormat` - #23228

As `GL_UNSIGNED_SHORT_5_6_5` relies exclusively on `GL_RGB`.

**Comment by Mugen87** [comment]
Yeah, we will not continue the support of RGB formats. Please use `UnsignedShort5551Type` or `UnsignedShort4444Type`.

**Comment by Mugen87** [comment]
But yes, the usage of `texStorage2D()` broke the packed types. I'll fix that.

**Comment by Ithamar** [comment]
Is there any documentation on why RGBFormat is being dropped? Maybe it is just me, but I think it deserves a little more "focus" in the migration guide as I'm sure this will trip many people up....

**Comment by Mugen87** [comment]
> Is there any documentation on why RGBFormat is being dropped?

You find the information at the respective PR: https://github.com/mrdoob/three.js/pull/23228#issue-1102180015

We usually put only the migration tasks in the migration guide and not the reasoning behind each change. That would just too much management.
