### ISSUE TITLE
adding the type key "module" on the root will make threejs ESM-only

### ISSUE THREAD

**Issue by RenaudRohlinger** [mrdoob/three.js#23324]
**Describe the bug**

Hello! 
I was worried about [this change](https://github.com/mrdoob/three.js/pull/23315/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R5) of #23315 so I tested it and it validated my concern. By adding the type key on the root  `"type": "module"` it will make threejs ESM-only and break all non-ESM libraries.

It should only be used in directories/user projects using ESM features such as test/package.json for example.
Can we simply remove this line:
`  "type": "module",`
or does the new paths ./ will break? @marcofugaro

**Comment by Mugen87** [comment]
Agreed, that needs to be resolved. However, removing the line breaks the `npm test` command.

**Comment by CodyJasonBennett** [comment]
Yes, this key is rather dangerous to put on the published package.json. We don't necessarily need to revert though. Removing this line and confining ESM scripts to test should do.

Which scripts are affected? You'll need to set the type key in test/package.json ([already done](https://github.com/mrdoob/three.js/pull/23315/files#diff-b9188cc104c28fc06ff913ef07a9fa1a038b3f4de944a86c32f85fe3df17efafR7)) instead and prefix scripts/execution to that directory.

This should already work with:

```js
"test-unit": "npm run unit --prefix test",
"test-unit-examples": "npm run unit-examples --prefix test",
```

But the following will need to mirror the above:

```js
"test-e2e": "node test/e2e/puppeteer.js",
"test-e2e-cov": "node test/e2e/check-coverage.js",
```

**Comment by Mugen87** [comment]
> and prefix scripts/execution to that directory.

Isn't that solution already in place?

https://github.com/mrdoob/three.js/blob/464a5f0381924cb7448f8f51cd8ffe1ee0dc243d/package.json#L93-L94

This result in the following error when executing `npm test`:

> message: "No tests matched the filter \"!-webonly\"."

**Comment by marcofugaro** [comment]
> By adding the type key on the root "type": "module" it will make threejs ESM-only and break all non-ESM libraries.

Not true, my attempt was to make three.js work both in esm and commonjs environment, [according to the docs](https://nodejs.org/api/packages.html#conditional-exports), I just forgot to provide a file with the `.cjs` extension.

Creating a new build output with the `.cjs` file fixes this.

**Comment by CodyJasonBennett** [comment]
> Isn't that solution already in place?

Yes.

> This results in the following error when executing npm test:

Indeed. Additionally, although the e2e scripts will run, they assume the working directory is always the root instead of test.

Removing the key on publish would be a bit simpler though.

**Comment by Mugen87** [comment]
I would say we give @marcofugaro's solution a try and see how it works.

**Comment by marcofugaro** [comment]
Made a PR for this, you can test it out

**Comment by marcofugaro** [comment]
> Indeed. Additionally, although the e2e scripts will run, they assume the working directory is always the root instead of test...

This is because the paths in the e2e file are not relative to the file itself... but this problem is not related to this issue.
