### ISSUE TITLE
Attempted import error: 'FramebufferTexture' is not exported from 'three'

### ISSUE THREAD

**Issue by leminhtuanlc92** [mrdoob/three.js#23349]
**Describe the bug**
![Screen Shot 2022-01-27 at 16 53 20](https://user-images.githubusercontent.com/34678201/151335166-2ded98bb-1c5b-4f97-8fb9-6c4e1ffecae7.png)

In Lensflare.js, there are import of FramebufferTexture
![Screen Shot 2022-01-27 at 16 55 56](https://user-images.githubusercontent.com/34678201/151335611-7a2de1fc-64a7-4bec-99bb-be2c2c6b027a.png)

but in type check of three, no FramebufferTexture at all
![Screen Shot 2022-01-27 at 16 56 56](https://user-images.githubusercontent.com/34678201/151335844-0e7e1bc7-39a3-4287-b804-010249d95da8.png)

**Platform:**
 - Device: [Desktop]
 - OS: [ MacOS]
 - Browser: [Chrome]
 - Three.js version: 0.134.0

**Comment by Mugen87** [comment]
Please report this issue here instead: https://github.com/pmndrs/three-stdlib
