### ISSUE TITLE
Request for synopsis blurb at the top of each source file maybe

### ISSUE THREAD

**Issue by tripdragon** [mrdoob/three.js#23355]
**Problem:**
Waiting for documentation on classes or files don't yet have official documentation html files.

**Description:** 
Simply, a one liner at the top of source files for what the Class or Library might be used for or its original intent. Not for every function, just its class or library.
Example Vector3: "3d Vector Class with traditional linear algebra functions for convenience. Is used all across the library"

**Alternatives considered:** 
Reading source as I am doing now and inspecting example files and spending time trying to figure out files as I can.

**Additional context:**
The remainder is original verbiage of the request.

I understand docs are separate from source by design, and I understand code should be self documenting and most times docs are a last step process for reaching stable feature. But you also have a lot of examples that use some internal or not documented classes and there is little to go on at times. Mind you its redundant and unnecessary for files that already have docs I would guess.

Examples: All of Node Materials individual nodes
Or singularly RGBELoader.js

As I understand RGBELoader is to handle the HDR aspect of .hdr files for skyboxes or light maps. I only figured that out from the example files and when Blender was outputting HDR files for light map baking and after texture loader was not working.

As for Nodes Materials, its looking like it will never exit examples so there is still no form of documentation, so little blurbs would go a long way towards just reading its source, in the case of all Nodular projects like to name same functions various different names so you have to have worked with so many to piece it all together.

Apologies for a long winded explainer

**Comment by mrdoob** [comment]
Did you notice that in the issue template you ignored it says this in the first line?

```
<!-- Ignoring this template may result in your feature request getting deleted -->
```

**Comment by tripdragon** [comment]
Apologies for that, I updated and broke up sections to follow the template

**Comment by Mugen87** [comment]
Please understand that we have already a hard time to maintain the current multi-lingual documentation. Asking for even more documentation (even if it is just a one-liner per file) is somewhat out of scope, IMO.

**Comment by mrdoob** [comment]
Indeed...

Documenting things as we go is 2x the effort. Also, we don't always know what the right design is.
We're still figuring out what's the right way to deal with HDR textures. Same about the NodeMaterial.

In the meantime, you can always ask questions in the [forum](https://discourse.threejs.org/) or the [chat](https://discord.gg/HF4UdyF).

**Comment by tripdragon** [comment]
I understand those concerns, let me clarify really. Its just a simple line of what this file might do. Not a doc just a helper line in the case that the naming might not be enough or the name might only be obvious to the original author. 

It's always clear after you know, but its also a waste of peoples time for both parties when submitting in the forums. The submitter hoping for an answers and the replier for writing what could have been there in the first place.

I can start a bit of this but I felt I should bring up the discussion before I even start. But I for sure don't know every files job.

**Comment by mrdoob** [comment]
Sorry but that will be extra maintenance.
* People will do typos.
* There will be discussions about the right explanation.
* More PRs to triage, more energy not spent fixing all other the issues we already have.
