### ISSUE TITLE
Texture bug on r137

### ISSUE THREAD

**Issue by Karbust** [mrdoob/three.js#23353]
**Describe the bug**

DDS and PNG textures lose all color, I don't know how to really explain, I attached screenshots bellow. Since I only use these 2 types of textures, I can't test other types.

If the browser has DDS support, it will be used, otherwise fallback to PNG. This happens on all browsers and devices I tested.

**To Reproduce**

Go to either of the live examples below and press on a weapon or amor icon, the differences will be visible.

***Code***

A code snippet of how I'm using it.
```ts
		const manager = new THREE.LoadingManager(() => {
			const loadingScreen = document.getElementById('loading-screen')
			if (loadingScreen) {
				loadingScreen.classList.add('fade-out')

				loadingScreen!.addEventListener('transitionend', onTransitionEnd)
			}
		})
		manager.addHandler(/\.dds$/i, new DDSLoader())

		const mtlLoader = new MTLLoader(manager)
		mtlLoader.setPath(url!)
		mtlLoader.load(`${model}.mtl`, (materials) => {
			materials.preload()

			const objLoader = new OBJLoader(manager)
			objLoader.setMaterials(materials)
			objLoader.setPath(url!)
			objLoader.load(`${model}.obj`, (object) => {
				object.scale.setScalar(1 / 200)

				object.traverse((child) => {
					child.frustumCulled = false
					if ((child as any).material instanceof THREE.MeshPhongMaterial) {
						(child as any).material.side = THREE.DoubleSide
					}
				})
				scene.add(object)
			}, undefined, (error) => console.error(error))
		})
```

***Live example***

* [Public version with r136](https://m2icondb.com/)
* [Dev version with r137](https://ade9a260.m2icondb.pages.dev)

**Screenshots**

Public version with r136:
![Public version with r136](https://user-images.githubusercontent.com/20361229/151404622-ad16b417-a7ea-49af-b9bb-e508e91d0c10.png)

Dev version with r137
![Dev version with r137](https://user-images.githubusercontent.com/20361229/151404707-10332177-661c-4608-8d52-a5caa1201ee8.png)

**Platform:**

 - Device: Desktop, Mobile
 - OS: Windows, Android
 - Browser: Tested on Vivaldi (both Desktop and Android), Chrome, Firefox and Edge
 - Three.js version: r137

**Comment by Mugen87** [comment]
This issue is related to the latest `alpha` change, see #23230.

The problem is that your assets are blended with the HTML background since for some reason the texture holds alpha values < 1.

One workaround to solve the issue is to add this block to your `onLoa()` callback:
```js
object.traverse( function ( child ) {

     if ( child.material ) child.material.alphaWrite = false;

} );
```
This will define the material as opaque by setting a `1` alpha value to all fragments.

**Comment by Mugen87** [comment]
Here is a complete code example that should load the sword as expected. Note that since `r137` you have to use an sRGB workflow when loading assets with OBJ/MTL loader.

```js
import * as THREE from 'three';

import { MTLLoader } from './jsm/loaders/MTLLoader.js';
import { OBJLoader } from './jsm/loaders/OBJLoader.js';
import { DDSLoader } from './jsm/loaders/DDSLoader.js';
import { OrbitControls } from './jsm/controls/OrbitControls.js';

let camera, scene, renderer;

init();
animate();

function init() {

	const container = document.createElement( 'div' );
	document.body.appendChild( container );

	camera = new THREE.PerspectiveCamera( 45, window.innerWidth / window.innerHeight, 1, 2000 );
	camera.position.set( 250, 250, 0 );
	camera.lookAt( 0, 0, 0 );

	// scene

	scene = new THREE.Scene();
	scene.background = new THREE.Color( 0xcccccc );

	const ambientLight = new THREE.AmbientLight( 0xcccccc, 0.4 );
	scene.add( ambientLight );

	const pointLight = new THREE.PointLight( 0xffffff, 0.8 );
	camera.add( pointLight );
	scene.add( camera );

	// model

	const onProgress = function ( xhr ) {

		if ( xhr.lengthComputable ) {

			const percentComplete = xhr.loaded / xhr.total * 100;
			console.log( Math.round( percentComplete, 2 ) + '% downloaded' );

		}

	};

	const onError = function () { };

	const manager = new THREE.LoadingManager();
	manager.addHandler( /\.dds$/i, new DDSLoader() );

	new MTLLoader( manager )
		.setPath( 'models/obj/temp1/' )
		.load( '00270.mtl', function ( materials ) {

			materials.preload();

			new OBJLoader( manager )
				.setMaterials( materials )
				.setPath( 'models/obj/temp1/' )
				.load( '00270.obj', function ( object ) {

					object.traverse( function ( child ) {

						if ( child.material ) child.material.alphaWrite = false;

					} );

					scene.add( object );

				}, onProgress, onError );

		} );

	//
	//

	renderer = new THREE.WebGLRenderer();
	renderer.outputEncoding = THREE.sRGBEncoding;
	renderer.setPixelRatio( window.devicePixelRatio );
	renderer.setSize( window.innerWidth, window.innerHeight );
	container.appendChild( renderer.domElement );

	//

	window.addEventListener( 'resize', onWindowResize );

	const controls = new OrbitControls( camera, renderer.domElement );

}

function onWindowResize() {

	camera.aspect = window.innerWidth / window.innerHeight;
	camera.updateProjectionMatrix();

	renderer.setSize( window.innerWidth, window.innerHeight );

}


//

function animate() {

	requestAnimationFrame( animate );
	render();

}

function render() {

	renderer.render( scene, camera );

}
```

**Comment by Karbust** [comment]
Perfect, it worked.

I was reading the migration guide but I wasn't able to pinpoint where the problem was coming from.

Thank you.

**Comment by mrdoob** [comment]
Makes me wonder if this line:

> https://github.com/mrdoob/three.js/blob/63650755e03cfe983a42bca3a489f71930fff3b7/src/renderers/webgl/WebGLPrograms.js#L181

Should be this instead:

```js
alphaWrite: material.alphaWrite && material.transparent,
```

This stuff hurts my brain a bit.

/cc @donmccurdy

**Comment by Mugen87** [comment]
> I was reading the migration guide but I wasn't able to pinpoint where the problem was coming from.

I've added a note that `OBJ/MTLLoader` now requires a sRGB workflow and also the `alphaWrite` solution.

But I fear many user will not understand that 3D objects are potentially blended with the background. It seems these cases will require some support.

**Comment by Karbust** [comment]
> alphaWrite: material.alphaWrite || material.transparent,



> Makes me wonder if this line:
> 
> > https://github.com/mrdoob/three.js/blob/63650755e03cfe983a42bca3a489f71930fff3b7/src/renderers/webgl/WebGLPrograms.js#L181
> 
> Should be this instead:
> 
> ```js
> alphaWrite: material.alphaWrite && material.transparent,
> ```
> 
> This stuff hurts my brain a bit.
> 
> /cc @donmccurdy

It didn't work, I edited it on the node_modules folder, also tried setting it to false, it stayed the same...  (I kept the sRGBEncoding, only removed the alphaWrite's on the my side).

![image](https://user-images.githubusercontent.com/20361229/151434838-3ece1b4d-2a4d-4caa-a30c-5704c708cc50.png)
![image](https://user-images.githubusercontent.com/20361229/151434921-c7ba80c7-88e3-4316-b6b0-e66acb0ac9cd.png)

![image](https://user-images.githubusercontent.com/20361229/151434966-b820479c-7a60-414c-b141-de4b573917ef.png)

**Comment by mrdoob** [comment]
Oh, hmm...

Then maybe the problem is that `material.blending` is set to `NormalBlending` by default.

Maybe if `transparent === true` it should use `NoBlending` internally?

**Comment by Mugen87** [comment]
Having a different value of `material.blending` will not solve this particular issue. If the fragment shader writes fragments with alpha values < 1, they will be blended with the HTML background. To only way to prevent this is to write `1` alpha values.

**Comment by mrdoob** [comment]
You're right: https://jsfiddle.net/zfgebmux/

**Comment by mrdoob** [comment]
So if `transparent === true` we have to add `gl_FragColor.a = 1.0` chunk at the end then.

**Comment by Mugen87** [comment]
Maybe we should reconsider https://github.com/mrdoob/three.js/pull/23166#issuecomment-1009379966 for a long-term and glTF compliant solution.

**Comment by mrdoob** [comment]
> So if `transparent === false` we have to add `gl_FragColor.a = 1.0` chunk at the end then.

Hmm, [I already tried that](https://github.com/mrdoob/three.js/pull/18631).

And now that we are setting `alpha: true` in the context I'm reading [this conversation](https://github.com/mrdoob/three.js/pull/18631/files#r383042011) with new eyes...

**Comment by mrdoob** [comment]
As far as I can see the only issue of #18631 is that it broke this use case:

> Confirmed. This breaks `AdditiveBlending` when `texture.a` < 1 and `material.transparent` is `false`.

I think I'm totally okay with breaking that use case if we're able to solve this regression.

And then we'll be able to get rid of `material.alphaWrite`.

**Comment by mrdoob** [comment]
#23361

**Comment by mrdoob** [comment]
Fixed: https://jsfiddle.net/wsuhyr52/ 😬

**Comment by mrdoob** [comment]
@Karbust If you update to `0.137.4` you shoudn't need the `alphaWrite` code anymore.

**Comment by Karbust** [comment]
> @Karbust If you update to `0.137.4` you shoudn't need the `alphaWrite` code anymore.

Correct, it's working without alphaWrite. Thank you
