### ISSUE TITLE
Failing import in CSS3DRenderer.js

### ISSUE THREAD

**Issue by gogela** [mrdoob/three.js#23382]
In the latest release (137) the CSS3DRenderer.js import fails with message :
Uncaught TypeError: Error resolving module specifier “three”. Relative module specifiers must start with “./”, “../” or “/”. CSS3DRenderer.js:6:7

Release136 works fine.

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

According to github in the last release the import statement in the CSS3DRenderer.js module, has been changed:
} from '../../../build/three.module.js';
to
} from 'three';

import * as THREE from 'https://cdn.skypack.dev/three@0.137.5/build/three.module.js';
import { CSS3DRenderer, CSS3DObject } from 'https://cdn.skypack.dev/three@0.137.5/examples/jsm/renderers/CSS3DRenderer.js';

vs (working in the previous version).
import * as THREE from 'https://cdn.skypack.dev/three@0.136.0/build/three.module.js';
import { CSS3DRenderer, CSS3DObject } from 'https://cdn.skypack.dev/three@0.136.0/examples/jsm/renderers/CSS3DRenderer.js';

**Expected behavior**
module imported w/o error

**Screenshots**

**Platform:**
all

**Comment by marcofugaro** [comment]
Related to https://github.com/skypackjs/skypack-cdn/issues/261

**Comment by Mugen87** [comment]
Let's continue the discussion at the skypack repo.
