### ISSUE TITLE
Doc: No page links in list.json for some existing korean docs

### ISSUE THREAD

**Issue by jiwonMe** [mrdoob/three.js#23389]
**Is your feature request related to a problem? Please describe.**

In [three.js homepage](threejs.org), there is no page lists for already translated korean docs.

**Describe the solution you'd like**

Just add page links in `list.json`

**Comment by Mugen87** [comment]
I'm not I understand. If you open the [documentation](https://threejs.org/docs/index.html) and select the Korean language, all translated pages should be listed.

**Comment by jiwonMe** [comment]
Some translated korean pages are not listed on https://github.com/mrdoob/three.js/blob/dev/docs/list.json, so those pages are not listed on homepages too.
For example, translated page (https://github.com/mrdoob/three.js/blob/dev/docs/api/ko/core/BufferAttribute.html) is exist on repository, but not listed on `list.json`, so there is no link for it. (https://threejs.org/docs/index.html#api/ko/core/BufferAttribute page is empty.)

**Comment by Mugen87** [comment]
Now I understand. Let me make a PR.
