### ISSUE TITLE
three.js ShaderMaterial plane disappearing

### ISSUE THREAD

**Issue by Dannie226** [mrdoob/three.js#23413]
**Describe the bug**

Using a ShaderMaterial, at certain angles a plane disappears.

**To Reproduce**

1. Go to the top link below
2. Zoom in so you can see both the white box and the plane behind it
3. Rotate the camera a bit
4. at certain angles the plane disappears.

***Code***

```js
//setting up renderer goes above here
const box = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial());
scene.add(box);

const planeMat = new THREE.ShaderMaterial({
    vertexShader`
        varying mediump vec3 vPos;
        
        void main(void){
            gl_Position = projectionMatrix * modelMatrix * vec4(position, 1.0);
            vPos = position;
        }`,
    fragmentShader:`
        varying mediump vec3 vPos;
        
        void main(void){
            //Coloring not needed. Just here to show the difference between the box and the plane
            gl_FragColor.rgb = mix(vec3(0.1), vec3(0.5), vPos.y / 2.0 + 0.5);
            gl_FragColor.a = 1.0;
        }`
});

const plane = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), planeMat);
plane.position.z = -5;
scene.add(plane);

//animation loop
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/cbuxkqdf/)

**Expected behavior**

The plane should be seen at all times.

**Screenshots**
![Screenshot 2022-02-02 10 26 45 AM](https://user-images.githubusercontent.com/77417944/152184062-48e50d6a-d0e0-4db2-8e0f-46936160406d.png)
![Screenshot 2022-02-02 10 26 34 AM](https://user-images.githubusercontent.com/77417944/152184065-8046a132-91f6-4387-9c0a-ebf9a87c8d6f.png)

**Platform:**

 - Device: Laptop
 - OS: Linux
 - Browser: Chrome
 - Three.js version: r137

**Comment by mrdoob** [comment]
We use GitHub issues to track confirmed bug reports and feature development.
If you need help, please use the [forum](https://discourse.threejs.org/), the [chat](https://discord.gg/HF4UdyF) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
