### ISSUE TITLE
Vector[2,3,4] divideScalar does not match documentation.

### ISSUE THREAD

**Issue by kmaxaurora** [mrdoob/three.js#23429]
**Describe the bug**

The documentation states that divideScalar will set the vector to zero if the input is zero, but actually it gets set to NaN. Is documentation wrong or the code? I'd be happy to submit a PR either way. Thanks!

**To Reproduce**

1. Get three.js
2. Run the code below.

***Code***

```js
const centroid = new Vector3(0, 0, 0);
centroid.divideScalar(0);
```

***Live example***

* [jsfiddle-dev](https://jsfiddle.net/7ozpd3v9/)

**Expected behavior**

Either it does not generate NaN or the documentation is changed.

**Platform:**
 - Same on all platforms
 - Three.js version: [dev]

**Comment by kmaxaurora** [comment]
Related code: https://github.com/mrdoob/three.js/blob/master/src/math/Vector3.js

**Comment by kmaxaurora** [comment]
Related:
https://github.com/mrdoob/three.js/issues/11241
https://github.com/mrdoob/three.js/issues/9387

**Comment by WestLangley** [comment]
Also see the discussion in #11253

**Comment by Mugen87** [comment]
I suggest to remove `Set[s]() vector to ( 0, 0, 0 ) if *s = 0*.` from the docs.
