### ISSUE TITLE
docs(Installation): import OrbitControls from Skypack CDN is not working

### ISSUE THREAD

**Issue by g1eny0ung** [mrdoob/three.js#23427]
**Describe the bug**

Try using the `OrbitControls` from Skypack CDN according to the installation section but not working now.

Seems after #23255 merged, it also needs to use `import maps` before importing modules in examples.

And also I found the Skypack CDN will still try to export the default even though a js module has no default export.

After I tried, I solved these two problems with the following code:

```html
<script type="importmap">
  {
    "imports": {
      "three": "https://cdn.skypack.dev/three"
    }
  }
</script>

<script type="module">

  // Find the latest version by visiting https://cdn.skypack.dev/three.

  import { OrbitControls } from 'https://unpkg.com/three/examples/jsm/controls/OrbitControls.js';

  const controls = new OrbitControls( camera, renderer.domElement );

</script>
```

I think the related docs can be updated to this, what do you think? But in my solution, I'm using two different CDNs. In case Skypack is currently unavailable, I wonder if we can switch all to unpkg (`https://unpkg.com/three/build/three.module.js`)?

**To Reproduce**

1. Create a new pen from https://codepen.io
2. Paste below code

***Code***

```html
<script type="module">

  // Find the latest version by visiting https://cdn.skypack.dev/three.

  import { OrbitControls } from 'https://cdn.skypack.dev/three/examples/jsm/controls/OrbitControls.js';

  const controls = new OrbitControls( camera, renderer.domElement );

</script>
```

**Expected behavior**

Successful import.

**Comment by marcofugaro** [comment]
This is a bug with skypack-cdn: https://github.com/skypackjs/skypack-cdn/issues/263

**Comment by g1eny0ung** [comment]
> This is a bug with skypack-cdn: [skypackjs/skypack-cdn#263](https://github.com/skypackjs/skypack-cdn/issues/263)

Got it!

**Comment by mrdoob** [comment]
Should we just change the links to use https://unpkg.com/ instead?

**Comment by Mugen87** [comment]
Probably the best solution to avoid more confusion.

**Comment by mattrossman** [comment]
Is the intention to wait for skypack-cdn to be fixed, or update the docs with a new recommended pattern? Perhaps this issue can be re-opened until the docs include working instructions for CDN usage. I haven't had success using Three from any CDN with the current documentation.

I've seen a couple patterns for CDN usage floating around, including the one shown above as well as setting up a `three-addons` alias for the examples directory https://github.com/mrdoob/three.js/pull/23368#issuecomment-1024645696. It sounds like that pattern is [still under discussion](https://github.com/mrdoob/three.js/pull/23560#issuecomment-1048822436) though. Some official guidance in the docs would help clear things up.

Additionally, if import maps are indeed a requirement for CDN usage, it would be helpful to make the polyfill instructions more explicit in the docs.

**Comment by Mugen87** [comment]
I think it makes sense to add a note to the `Installation` guide about Import maps.
