### ISSUE TITLE
Three js editor does not export alpha maps in glb/gltf format

### ISSUE THREAD

**Issue by kyndle-ozzo** [mrdoob/three.js#23431]
**Steps to reproduce:**
1. Open https://threejs.org/editor/
2. Create a plane
3. Edit its material to type MeshBasicMaterial
4. Select Map and Alpha Map and check them.  Note that these take effect.
5. Export the model from the menu. File -> Export GLB
6. File -> New
7. File -> Import and select the outputted .glb from above
8. Select the plane and view the MATERIAL tab

**Results**
The Alpha Map texture is missing.

**Expected Results**
Both Map and Alpha map should still be there.

I also opened the .glb in Window's 3D viewer to confirm the problem is on the export, not import.

**Comment by donmccurdy** [comment]
Hi @kyndle-ozzo – glTF is an independent standard and doesn't include every feature of three.js. It supports an alpha channel in the base color map (`material.map`) but not a separate Alpha Map. So, THREE.GLTFExporter and the three.js Editor cannot write the information you're looking for here.

If you need to be sure no information is lost, use the three.js custom JSON format. If you need a portable file that works in other software, use glTF and refer to the exporter implementation to see which features it can support:

https://github.com/mrdoob/three.js/blob/efbfc67edc7f65cfcc61a389ffc5fd43ea702bc6/examples/jsm/exporters/GLTFExporter.js#L1204-L1212
