### ISSUE TITLE
Editor: Support plugins API.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#23464]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I want to write some feature with `Editor`, it's not easy to do.

**Describe the solution you'd like**

I want to `Editor` support plugin API, then we can reuse editor code.

**Describe alternatives you've considered**

I'm not sure it's a good implementation.

We add `plugins.events.intersects( intersects );` in `Viewport.js` line 199. 

https://github.com/mrdoob/three.js/blob/0138219a7fb7f1e9f8ee6ebe33f8c8236b85496a/editor/js/Viewport.js#L198

We can get the required objects.

**Additional context**

```js
// MyAddons.js
editor.registerPlugin(new MyPlugin(/* options */));
```

**Comment by mrdoob** [comment]
Feel free to give it a go 👍

**Comment by linbingquan** [comment]
> > editor.registerPlugin(new MyPlugin(/* options */));
> 
> A generic `registerPlugin()` is not really doable since a plugin an application is going to implement has to somehow interact with editor's logic. And depending on what the plugin should do, an integration into the editor has to look totally different.
> 
> So without more concrete implementation details from the OP, I don't think this issue is much useful.

Thank you for your reply. 

Sorry, I haven't spent time thinking about this feature from this PR mention. TBH, Mentioned this PR is a relatively old project, it has been completed. If you want to turn off this PR, it's not a problem.

The idea behind this plugin is to reuse code from the editor to reduce development time.

Finally thank you for your time reading.

**Comment by Mugen87** [comment]
Closing then. We can reopen the issue at any time when a more detailed blueprint is provided.
