### ISSUE TITLE
Minimum pixelRatio of 2 on manual.

### ISSUE THREAD

**Issue by lgmsantos** [mrdoob/three.js#23474]
Shoudn't this be `min` instead of `max`?

https://github.com/mrdoob/three.js/blob/0946935372f79e100ebeb2e3883d144d4ca5f80e/manual/resources/threejs-lesson-utils.js#L20

It is causing some tutorial pages (Fundamentals -> Primitives, for instance) to crash on firefox with a 2k monitor.

**Comment by pacyfist** [comment]
This most definitely can't be `min`. Most phones have really high pixel ratios. For example Samsung S6 has pixel ratio of 4 and iPhone 13 has pixel ration of 3. But it makes no sense to force this value to be 2 since most PCs run with pixel ratio of 1 and it seems like due to this you can run out of VRAM.

**Comment by Mugen87** [comment]
@greggman What is your intention for always using a pixel ratio value for at least 2 in `threejs-lesson-utils.js`?

**Comment by Mugen87** [comment]
The problem is that forcing a minimum pixel ratio of two might lead to drawing buffer sizes that the device can't handle. I think it's more safe to always use `window.devicePixelRatio` like in the examples.

**Comment by greggman** [comment]
Of course do whatever you want but just fyi

> forcing a minimum pixel ratio of two might lead to drawing buffer sizes that a device can't handle.

(1) WebGL will limit the size to the canvas backing buffer to the max size it can handle. That's the entire point of drawingBufferWidth and drawingBufferHeight

(2) Even you use a dpr of one you can still EASILY get sizes larger than the GPU can handle. 2 examples (1) have multiple monitors, stretch a window across monitors (2) zoom out (press Ctrl/Cmd+Minus) and either (a) don't update your dpr calculation or (b) be on safari where dpr doesn't change based on zoom

**Comment by greggman** [comment]
Oh, and my original comment was wrong. It's Math.max because things looked crappy on a dpr 1 monitor and so 2 min was for extra antialiasing
