### ISSUE TITLE
Realistic rendering

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#23482]
**Is your feature request related to a problem? Please describe.**

We always use fixed assets to make some good/photorealistic visual 3D model likes PBR GLTF ( amazing visual, thanks talent team ).
With high speed explosion of software technology, we want more than just static models viewer. We want everything is flexible, dynamic, amazing user interaction,...
Ray-tracing is too slow in progress for web application to make a dynamic photorealistic 3D model rendering.

How can we make a photorealistic rendering for a dynamic geometry( we are doing so good at this with buffer geometry)?

We need some best-practice or easy-to-use api to make it  simple photorealistic dynamic geometry like a just a box on the table? 
For example, this sample https://threejs.org/examples/?q=material#webgl_materials may should look photorealistic?

**Describe the solution you'd like**
Just idea, not technical solution ( too hard? )
We need one of these or both:
1. Best-practice for photorealistic rendering of dynamic geometry( not load all from gltf by other designing tool)
2. Best API such as photorealsitic material? Another version of PBR but not fixed assets ( static image ). We have lighting, we have shadow, we have reflection from dynamic rendering buffer, we have opacity,... However, it needs to be more amazing realistic like PBR GLTF model (https://threejs.org/examples/?q=gltf#webgl_tonemapping)

**Additional context**
 I am so excited with how threejs helps w3 world to go to next level until now.
With this, we are going more pioneer, I think.

**Comment by donmccurdy** [comment]
Hi @whatisor! Because this appears to be a help/support request, we'd prefer that you post these questions on the forums (https://discourse.threejs.org/) or in the three.js Slack, Discord, or other channels. Thanks!
