### ISSUE TITLE
Add a hint to the docs not to use negative values with the BufferGeometry.scale method or do a fix?

### ISSUE THREAD

**Issue by Molay** [mrdoob/three.js#23497]
**Describe the bug**

Sometimes when we need to reverse the geometry on the XYZ axis, some people (like me :p) may use BufferGeometry.scale method with the -1 value on the target axis, and it will cause error in the normal vector calculation after applying the matrix.

**To Reproduce**

Use BufferGeometry.scale method with negative values.

***Code***

```js
// Reverse geometry on the X axis
// OH NO
geometry.scale(-1, 1, 1);
// Yep
geometry.rotateY(Math.PI);
```

***Live example***

**Expected behavior**

1. Add a hint to the docs

File: docs/api/en/core/BufferGeometry.html
Line: 271

```html
		<h3>[method:this scale] ( [param:Float x], [param:Float y], [param:Float z] )</h3>
		<p>
		Scale the geometry data. This is typically done as a one time operation, and not during a loop.
		Don't use this method with negative values otherwise it will cause the normal vector calculation error when the matrix is applied.
		Use the rotation method instead of this method with negative values.
		e.g. use rotateY(Math.PI) instead of scale(-1, 1, 1).
		Use [page:Object3D.scale] for typical real-time mesh scaling.
		</p>
```

2. Do a fix

Handle negative values in BufferGeometry.scale method? Doesn't feel like a good idea.

**Screenshots**

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r???]

**Comment by Mugen87** [comment]
```js
geometry.scale(-1, 1, 1);
```
This pattern is used multiple times in the examples e.g. here:
https://github.com/mrdoob/three.js/blob/02cf0df1cb4575d5842fef9c85bb5a89fe020d53/examples/webgl_panorama_equirectangular.html#L53-L54

A note in the docs like suggested is no good idea. As long as the users knows the consequences of it's okay if this operation is used. It is not the task of the API reference to educate the user about general 3D topics.

Besides, we can't gracefully handle all possible matrix permutations in the library. So I do not vote for suggestion 2.

**Comment by WestLangley** [comment]
>Besides, we can't gracefully handle all possible matrix permutations in the library.

@Mugen87 It is either an inversion or not an inversion. So it is not that complicated... We already handle inversions in the object matrix.

//

@Molay Did you try `mesh.scale.set( - 1, 1, 1 )` instead of `mesh.geometry.scale.set( - 1, 1, 1 )`.

//

Also, Instead of doing this:
```js
const geometry = new THREE.SphereGeometry( 500, 60, 40 );
// invert the geometry on the x-axis so that all of the faces point inward
//geometry.scale( - 1, 1, 1 );

const material = new THREE.MeshBasicMaterial( { map: texture } );

const mesh = new THREE.Mesh( geometry, material );
```

You can do this, instead:

```js
const geometry = new THREE.SphereGeometry( 500, 60, 40 );

const material = new THREE.MeshBasicMaterial( { map: texture, side: THREE.BackSide } );

const mesh = new THREE.Mesh( geometry, material );
mesh.scale.set( - 1, 1, 1 );
```

**Comment by Molay** [comment]
@WestLangley Thanks for the reply, but I need a one-time transform operation on the geometry (by using transform matrix), not a runtime adjustment, so your example doesn't meet my needs.

@Mugen87 You're right, it's a user error. Maybe we can create a separate page describing caveats in geometry manipulation to inform users of possible errors?
After all, there are many examples, and users may not notice this description in example "three.js/examples/webgl_panorama_equirectangular.html".
