### ISSUE TITLE
Manually generated data texture mipmaps uploaded wrongly

### ISSUE THREAD

**Issue by MatejJan** [mrdoob/three.js#23490]
After switching to WebGL 2 by upgrading to latest three.js, my data texture with custom mipmap levels stopped working correctly. 

Here's a debug image showing a normal map of a floor that has a texture with custom mipmaps. On the main level you can see the floor texture and for debugging I put just different colors on the other levels. Instead of the colors appearing as the floor recedes into the distance, they appear overlaid on the main level.

<img width="695" alt="Screen Shot 2022-02-14 at 13 48 07" src="https://user-images.githubusercontent.com/565736/153867067-e64e52b8-9a1c-430d-9deb-dbf998a04bf4.png">

I traced the issue down to the uploading process in case of WebGL 2 which seems to use tex storage:
https://github.com/mrdoob/three.js/blob/56a39221193a80a6c0a4e37da6f7757596007fe4/src/renderers/webgl/WebGLTextures.js#L806

I'm guessing the line should have the index `i` as the second parameter:

```
state.texSubImage2D( _gl.TEXTURE_2D, i, 0, 0, mipmap.width, mipmap.height, glFormat, glType, mipmap.data );
```

I'll try and see if this is indeed the fix. I'm a bit confused because the [texture manual mipmapping example](https://threejs.org/examples/?q=mipmap#webgl_materials_texture_manualmipmap) seems to be working just fine, so maybe that line is supposed to be like this (I have no experience with tex storage yet).

**Comment by Mugen87** [comment]
> I'm a bit confused because the [texture manual mipmapping example](https://threejs.org/examples/?q=mipmap#webgl_materials_texture_manualmipmap) seems to be working just fine, so maybe that line is supposed to be like this (I have no experience with tex storage yet).

The example works because it uses no data textures. The buggy line is in the data texture branch.

Would you like to file a PR with the fix?
