### ISSUE TITLE
WebGLRenderer: background is not set to transparent on 0.137.0 version

### ISSUE THREAD

**Issue by japie1235813** [mrdoob/three.js#23495]
**Describe the bug**
We upgrades the threejs version recently from  `0.131.3` to `0.137.0` https://github.com/tensorflow/tensorboard/commit/420916a6e4c80740432f1e2bd0c83d6dd145da10. It breaks our repo by not setting the background to black. (see screenshots before)
After debugging we found the cause is from the background is not set to transparent by "alpha: true". (which means, we can fix our issue by adding `renderer.setClearColor(0x000000, 0);`) 
Is there any changes from the version that makes this stop working?

**To Reproduce**
You can reproduce the issue by clone our repo. Checkout to the upgrade comment and run TensorBoard (https://github.com/tensorflow/tensorboard).
However it requires some demo data to run the card. Let me know how I can assist.

***Code***
[code point](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts#L289)
```ts
//ts
   this.renderer = new THREE.WebGLRenderer({
      canvas: canvas as HTMLCanvasElement,
      context: canvas.getContext('webgl2', {
        antialias: true,
        precision: 'highp',
        alpha: true,
      } as WebGLContextAttributes) as WebGLRenderingContext,
    });

```
**Screenshots**
before (0.131.3)
<img width="461" alt="Screen Shot 2022-02-14 at 3 50 06 PM" src="https://user-images.githubusercontent.com/1131010/153967505-02fd6757-cf32-4897-8cde-8cb6e85c2a8a.png">

after (0.137.0)
<img width="438" alt="Screen Shot 2022-02-14 at 4 04 13 PM" src="https://user-images.githubusercontent.com/1131010/153967558-97ee6026-f831-4aa9-b94b-bd1087633259.png">

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version:  0.131.3 (works) 0.137.0 (breaks)

**Comment by Mugen87** [comment]
```js
this.renderer = new THREE.WebGLRenderer({
  canvas: canvas as HTMLCanvasElement,
  context: canvas.getContext('webgl2', {
    antialias: true,
    precision: 'highp',
    alpha: true,
  } as WebGLContextAttributes) as WebGLRenderingContext,
});
```
Instead of creating the `context` by yourself, do you mind if the following fixes the issue:
```js
this.renderer = new THREE.WebGLRenderer({
  canvas: canvas as HTMLCanvasElement,
  antialias: true,
  alpha: true,
});
```
BTW: AFAIK, `precision` is not WebGL context attribute.

In `r137` the renderer always uses `alpha: true` when creating the WebGL rendering context. A fallback was implemented however it does not work for your case since you create the context by yourself. Meaning since you pass no `alpha` parameter the following line assigns `false` to `_alpha`:

https://github.com/mrdoob/three.js/blob/766b95bad6ae2c98c5bf1c4c775c7c9e8f72f2d2/src/renderers/WebGLRenderer.js#L62

And this value leads to a wrong alpha clear value in `WebGLBackground`:

https://github.com/mrdoob/three.js/blob/766b95bad6ae2c98c5bf1c4c775c7c9e8f72f2d2/src/renderers/webgl/WebGLBackground.js#L13

**Comment by Mugen87** [comment]
@mrdoob We could fix this issue on our side however it means we have call `getContextAttributes()` on the user provided `context` and then evaluate the defined `alpha` context attribute.

**Comment by japie1235813** [comment]
Thanks for the reply! Moving the params out of context fixes the issue.

**Comment by mrdoob** [comment]
> @mrdoob We could fix this issue on our side however it means we have to call `getContextAttributes()` on the user provided `context` and then evaluate the defined `alpha` value.

That sounds good 👍

**Comment by Mugen87** [comment]
@japie1235813 The PR you have filed at `tensorboard` is not entirely correct. If you pass in context parameters, you have to let `three.js` create the rendering context. You have to use:
```js
this.renderer = new THREE.WebGLRenderer({
  canvas: canvas as HTMLCanvasElement,
  antialias: true,
  alpha: true
});
```

**Comment by japie1235813** [comment]
so after https://github.com/mrdoob/three.js/pull/23504
it's one of the two usage?
```
this.renderer = new THREE.WebGLRenderer({
  canvas: canvas as HTMLCanvasElement,
  antialias: true,
  alpha: true
});
```
or
```
this.renderer = new THREE.WebGLRenderer({
      canvas: canvas as HTMLCanvasElement,
      context: canvas.getContext('webgl2', {
        antialias: true, // this looks not being taken?
        alpha: true,
      } as WebGLContextAttributes) as WebGLRenderingContext,
    });
```

**Comment by Mugen87** [comment]
Correct. I recommend the first one though. Creating a rendering context manually should only be done if there is a compelling reason.
