### ISSUE TITLE
Any PolyhedronGeometry tanks the GPU

### ISSUE THREAD

**Issue by TheDutchCoder** [mrdoob/three.js#23493]
**Describe the bug**

I'm building a small game that uses some primitive shapes for things.
Whenever I use a PolyhedronGeometry (like DodecahedronGeometry or IcosahedronGeometry) in an instancedMesh, my GPU tanks to ~5FPS (depending on the amount of instances).

I've spent hours figuring out what is happening and yesterday it looked like `powerPreference: 'high-performance'` was the issue (disabling solved the issue), but today it's back again with the same issues.

So this might not be threejs directly, but rather a webgl problem?

it's very hard to reproduce, because in FireFox this doesn't happen, only in Chrome, on my 2016 MacBook pro, so I feel like it might even be the webgl implementation of Chrome itself.

Interestingly enough FPS are just fine with other geometries (like box, or cone, etc), just not any of the PolyhedronGeometry based ones.

**To Reproduce**

You can clone my repo (https://github.com/TheDutchCoder/atc-gjk) and on the `convert-to-native-js` branch you can run `npm run dev`.

If you see good FPS, please let me know which browser and OS you're using, because again I feel like this might even be a browser problem.

Disclaimer: code is a bit of a mess currently because I'm moving things around and trying to fix this issue.

***Code***

See repo.

***Live example***

N/A (see repo)

**Expected behavior**

When using a PolyhedronGeometry I should not see a huge drop in FPS.

**Screenshots**

![image](https://user-images.githubusercontent.com/1668207/153903237-5989947d-16c9-422a-b737-63fea8f00ab4.png)
Note that the performance stats seem normal

**Platform:**

 - Device: Desktop, MacBook Pro 2016
 - OS: MacOS 12.1
 - Browser: Chrome 98.0.4758.80
 - Three.js version: r137 (latest)

**Comment by mrdoob** [comment]
Sorry, we are not able to clone repos and debug user's code.
Please, provide a jsfiddle that shows the issue. Closing until then.

**Comment by TheDutchCoder** [comment]
Well that's unfortunate, because it really does happen. Here's a GPU profile:
![image](https://user-images.githubusercontent.com/1668207/153904707-571fc306-d648-4d95-a291-98270223555b.png)

The throttled start is using DodecahedronGeometry, the spiked usages is using BoxGeometry.

I'm not sure if this is reproducible in a service like JSFiddle, as it's not the same as running a local instance, but I might give it a shot.

**Comment by mrdoob** [comment]
> Disclaimer: code is a bit of a mess currently because I'm moving things around and trying to fix this issue.

We try to give you (and all the library users) clear code.
Would be nice if you could help us back by giving us clear code too.
