### ISSUE TITLE
Snowpack showing "Package "three" exists but package.json "exports" does not include entry"

### ISSUE THREAD

**Issue by Bassadin** [mrdoob/three.js#23507]
**Describe the bug**

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**To Reproduce**

1. I'm using [snowpack](https://www.snowpack.dev/) as a bundle tool
2. When trying to build my application, I get the error `Package "three" exists but package.json "exports" does not include entry for "./examples/jsm/webxr/ARButton.js".`

***Code***

Feel free to pull my repo to reproduce: https://github.com/Bassadin/Three.LS

**Expected behavior**

Being able to build without the error occurring.

**Screenshots**

![image](https://user-images.githubusercontent.com/1810902/154368060-d39f8d04-71b3-47b8-b604-7f4d98d8bd2d.png)

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome, not important
 - Three.js version: 0.137.5

**Comment by mrdoob** [comment]
We use GitHub issues to track confirmed bug reports and feature development.
If you need help, please use the [forum](https://discourse.threejs.org/), the [chat](https://discord.gg/HF4UdyF) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

**Comment by marcofugaro** [comment]
> Although I can see that in your package.json, you're exporting [the examples](https://github.com/mrdoob/three.js/blob/dev/package.json#L14). So you're saying it's something on the end of snowpack?

Exactly

**Comment by Bassadin** [comment]
https://github.com/withastro/snowpack/issues/3867

I'll leave this here as a reference, should anyone encounter this as well :)
