### ISSUE TITLE
Add normal orientation of cylinders in webxr_ar_hittest example

### ISSUE THREAD

**Issue by nosy-b** [mrdoob/three.js#23506]
The _webxr_ar_hittest_ example is great to show XR capabilites with a reticle and when tapping it generates cylinders at the position raycasted in your room.

Just a suggestion, It would be nice to set the cylinder to be in the direction of the hit because we have this information and not using it could mislead the user.

It would be 1 line to change: `cylinderMesh.matrix = reticle.matrix.clone();`
like: 
![webxrHitTest](https://user-images.githubusercontent.com/158514/154366776-1b885c40-21de-492c-8152-1f71300aa275.jpg)

Would be happy to PR :)
Thanks!

**Comment by mrdoob** [comment]
A PR would be great indeed 🙏
