### ISSUE TITLE
Docs: Some APIs are Undocumented

### ISSUE THREAD

**Issue by ycw** [mrdoob/three.js#23509]
[0.137.5](https://ycw.github.io/glue/www/)

### math/Quaternion
 - [x] multiplyQuaternionsFlat

### animation/PropertyMixer
 - [x] cumulativeWeightAdditive
 - [x] accumulateAdditive

### audio/Audio
 - [x] setDetune
 - [x] getDetune

### extras/ImageUtils
 - [x] sRGBToLinear

### lights/RectAreaLight
 - [x] width
 - [x] height

### materials/MeshPhysicalMaterial
 - [ ] thickness
 - [ ] thicknessMap
 - [ ] attenuationDistance
 - [ ] attenuationColor

### math/Matrix3
 - [x] scale
 - [x] rotate
 - [x] translate

### math/Triangle
 - [x] isFrontFacing
 - [x] getUV

### renderers/webxr/WebXRManager
 - [x] getFoveation
 - [x] setFoveation

**Comment by Mugen87** [comment]
`Euler.toVector3()` has been removed via #23494.

**Comment by lizzyd710** [comment]
Want any help working on this? I'd be happy to document the last five remaining tasks.
