### ISSUE TITLE
Css3drenderer and css2drenderer exist at the same time. Click events can only detect one layer with higher level

### ISSUE THREAD

**Issue by huangyulin** [mrdoob/three.js#23519]
I have a problem. When I use css2drenderer and css3drenderer at the same time, when adding click events to the instantiated css2dobject and css3dobject tag elements, because the dom of css2drenderer and css3drenderer have levels, click events can only detect one of them; Is there a raycaster method to detect css3dobject / css2dobject objects to add click events; Or there's a better way

**Describe alternatives you've considered**

**Additional context**

![QQ截图20220218094755](https://user-images.githubusercontent.com/16285625/154603876-65942188-dd8f-4aee-894c-4274e74dd2ae.png)

**Comment by mrdoob** [comment]
We use GitHub issues to track confirmed bug reports and feature development.
If you need help, please use the [forum](https://discourse.threejs.org/), the [chat](https://discord.gg/HF4UdyF) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

**Comment by huangyulin** [comment]
thanks
