### ISSUE TITLE
Nodes: Add BoolNode and UintNode

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#23520]
**Is your feature request related to a problem? Please describe.**

I want to be able to work with booleans and unsigned integers with Nodes system.

**Describe the solution you'd like**

I suggest adding BoolNode and UintNode (and their vector and possibly matrix versions) to other input nodes.

**Describe alternatives you've considered**

The alternatives are to not use booleans and unsigned integers at all or to manually create BoolNode and UintNode classes.

**Comment by LeviPesin** [comment]
Also I suggest that with them functions bool() and uint() (and corresponding vector types) and mat2(), mat3(), and mat4() (analoguous to float(), int(), and vec2(), vec3(), and vec4()) would be added to the ShaderNode.

**Comment by sunag** [comment]
> bool() and uint() 

Yeah. In fact this will be necessary.
