### ISSUE TITLE
Docs: Missing API Docs for Type Assertion `.is*` ??

### ISSUE THREAD

**Issue by ycw** [mrdoob/three.js#23527]
`.is*` are used throughout the `examples/` codes, ex [`.isMesh`](https://github.com/mrdoob/three.js/search?o=desc&q=isMesh&s=indexed&type=code), but some of them are undocumented. Are they missing docs? or are they for internal use only?

- [x] isAnimationObjectGroup
- [x] isArrayCamera
- [x] isCamera
- [x] isOrthographicCamera
- [x] isPerspectiveCamera
- [x] isBufferAttribute
- [x] isBufferGeometry
- [x] isInstancedBufferGeometry
- [x] isInterleavedBufferAttribute
- [x] isObject3D
- [x] isSkeletonHelper
- [x] isAmbientLight
- [x] isAmbientLightProbe
- [x] isDirectionalLight
- [x] isDirectionalLightShadow
- [x] isHemisphereLight
- [x] isHemisphereLightProbe
- [x] isLight
- [x] isLightProbe
- [x] isRectAreaLight
- [x] isSpotLight
- [x] isSpotLightShadow
- [x] isImageBitmapLoader
- [x] isLineDashedMaterial
- [x] isMaterial
- [x] isMeshStandardMaterial
- [x] isShaderMaterial
- [x] isSpriteMaterial
- [x] isBox3
- [x] isColor
- [x] isEuler
- [x] isPlane
- [x] isQuaternion
- [x] isSphericalHarmonics3
- [x] isVector2
- [x] isVector3
- [x] isVector4
- [x] isBone
- [x] isGroup
- [x] isInstancedMesh
- [x] isLine
- [x] isLineLoop
- [x] isLineSegments
- [x] isLOD
- [x] isMesh
- [x] isPoints
- [x] isSkinnedMesh
- [x] isSprite
- [x] isWebGL1Renderer
- [x] isWebGLMultipleRenderTargets
- [x] isWebGLRenderTarget
- [x] isFog
- [x] isFogExp2
- [x] isScene
- [x] isCanvasTexture
- [x] isCompressedTexture
- [x] isCubeTexture
- [x] isDataTexture
- [x] isDepthTexture
- [x] isFramebufferTexture
- [x] isRenderTargetTexture
- [x] isVideoTexture

[Report 2a5f97220108ec2ca8b65edc092a061e7dda8899](https://ycw.github.io/glue/www/)

**Comment by mrdoob** [comment]
We could document these, but I don't know how to describe them.

**Comment by Mugen87** [comment]
Maybe something like this with a generic description:
```
<h3>[property:Boolean isMesh]</h3>
<p>
    Whether a given object is of type [name] or not. More compact alternative to the *instanceof*  operator.
</p>
```

**Comment by mrdoob** [comment]
Sounds good 👍

**Comment by mrdoob** [comment]
Simpler:

```html
<h3>[property:Boolean isMesh]</h3>
<p>
    Read-only flag to check whether a given object is of type [name].
</p>
```
