### ISSUE TITLE
Nodes: Add possibility to use for/while loops

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#23524]
**Is your feature request related to a problem? Please describe.**

I want to be able to use for/while loops with the Nodes system.

**Describe the solution you'd like**

I suggest that the possibility for using them will be added.

**Describe alternatives you've considered**

Just the FunctionNode could be used instead, but this obviously limits the shader to only one of the GLSL and WGSL.

**Comment by Mugen87** [comment]
Merging this into #28569. `for` loops are implemented via #25967.
