### ISSUE TITLE
Nodes: Nodes system often generates unneccesary variables

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#23537]
**Describe the bug**

When using the Nodes system it often generates unneccesary variables. For example, in example https://jsfiddle.net/5rxbck2n/1/ from https://github.com/mrdoob/three.js/issues/23170 there is an unnecessary variable `nodeVar5` which is defined as `nodeVar5 = nodeVar4` - i.e. it can safely be deleted and its occurences changed to `nodeVar4`.

***Live example***

* [jsfiddle-dev](https://jsfiddle.net/5rxbck2n/1/)

**Expected behavior**

There should not be such variables.

**Comment by sunag** [comment]
Fixed here https://github.com/mrdoob/three.js/pull/23828

**Comment by LeviPesin** [comment]
Confirmed that this is fixed.
