### ISSUE TITLE
Nodes: Add functions for conversions between types

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#23534]
**Is your feature request related to a problem? Please describe.**

I want to be able to convert values to different types in the Nodes system. This is needed, for example, for nearly all shader PRNG's.

**Describe the solution you'd like**

I suggest adding to the MathNode functions for conversion between bool, int, uint, and float types (functions bool, int, uint and float in GLSL, but I am unsure what are their analogs in WGSL) (see https://github.com/mrdoob/three.js/issues/23520 about bool and uint types).

**Describe alternatives you've considered**

I don't think that there are any alternatives.

**Comment by LeviPesin** [comment]
They could be called makeBool(), makeInt(), makeUint(), and makeFloat() in the ShaderNode (so that they wouldn't be confused with bool(), int(), uint(), and float()).

**Comment by LeviPesin** [comment]
Here is an example of a PRNG using the Nodes system:
```
import { nodeObject, float, uint, add, mul, shiftRight, xor, makeFloat } from 'nodes/ShaderNode.js';
import VarNode from 'nodes/core/VarNode.js';

const UONE = uint( 1 );

const ONE_OVER_POW = float( 1 / 2 ** 32 );

const FOUR = uint( 4 );
const n22 = uint( 22 );
const n28 = uint( 28 );
const n27e = uint( 277803737 );
const n28e = uint( 2891336453 );
const n74e = uint( 747796405 );

function makeVarNode( node ) {
	if ( node.node ) // node is a VarNode
		return nodeObject( node );
	return nodeObject( new VarNode( node ) );
}

const seed = makeVarNode( uint( 1234 ) );

function hash( num ) { // taken from pcg-random.org
	const state = makeVarNode( add( mul( num, n74e ), n28e ) );
	const word = makeVarNode( mul( xor( shiftRight( state, add( shiftRight( state, n28 ), FOUR ) ), state ), n27e ) );
	return makeVarNode( makeFloat( xor( shiftRight( word, n22 ), word ) ) );
}

function getNextHash() {
	return hash( makeVarNode( assign( seed, add( seed, UONE ) ) ) );
}

function random() { // returns a value between 0 (inclusive) and 1 (exclusive)
	return makeVarNode( mul( getNextHash(), ONE_OVER_POW ) );
}
```

The function `makeVarNode` (possibly, with different name) could also be added to the ShaderNode.

**Comment by LeviPesin** [comment]
Actually, maybe for this just the third parameter of the VarNode (i.e. nodeType) could be used...

**Comment by sunag** [comment]
@LeviPesin You already try to use `ConvertNode`?
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/renderers/nodes/utils/ConvertNode.js

**Comment by LeviPesin** [comment]
No, I didn't; thank you!

So then something like this can be added?
```
export const makeBool = ( node ) => nodeObject( new ConvertNode( nodeObject( node ), 'bool' ) );
export const makeFloat = ( node ) => nodeObject( new ConvertNode( nodeObject( node ), 'float' ) );
export const makeInt = ( node ) => nodeObject( new ConvertNode( nodeObject( node ), 'int' ) );
export const makeUint = ( node ) => nodeObject( new ConvertNode( nodeObject( node ), 'uint' ) );
```
Or just `export const convert = ( node, type ) => nodeObject( new ConvertNode( nodeObject( node ), type ) )`?

**Comment by sunag** [comment]
I would like to preserve a GLSL similar style if possible. I was already added type conversion in `vec2( someNode )`, `vec3()` and `vec4()`.

https://github.com/mrdoob/three.js/blob/31df72c8b528a8ef28c94fa926c843f789f3c0e5/examples/jsm/renderers/nodes/ShaderNode.js#L248-L254

**Comment by LeviPesin** [comment]
Like so? https://github.com/mrdoob/three.js/pull/23544

**Comment by sunag** [comment]
> I.e. something like this?

Yeah, exactly this!
