### ISSUE TITLE
Shadows produce edge highlights

### ISSUE THREAD

**Issue by fraguada** [mrdoob/three.js#23551]
**Describe the bug**

OOTB Shadows are producing light leak artifact on mesh edges. Most, if not all, answers related to this issue are related to tweaking the shadow bias on the light. No amount of tweaking seems to resolve the highlight. I've posted this first on the discourse: https://discourse.threejs.org/t/remove-edge-highlighting-when-using-shadows/34763

This issue can also be seen in many threejs examples.

- https://threejs.org/examples/?q=pcss#webgl_shadowmap_pcss (rotate model)
- https://threejs.org/examples/?q=shadow#webgl_shadowmap (sneak behind the plinth)

**To Reproduce**

Place two meshes near and overlapping each other, have them receive and cast shadows. Create a directional light and have it cast shadows.

I've created a small reproduction: 
Live: https://fraguada.github.io/issues/1/

***Code:***

* [sample-r137](https://github.com/fraguada/issues/blob/main/1/script.js)
* [sample-r138dev](https://github.com/fraguada/issues/blob/main/1/dev/script.js)

***Live example***

* [sample-r137](https://fraguada.github.io/issues/1/)
* [sample-r138dev](https://fraguada.github.io/issues/1/dev/)

**Expected behavior**

I would expect for these highlights to not appear, or have a useful workaround for cases where OOTB shadows produce these artifacts.

**Screenshots**

![image](https://user-images.githubusercontent.com/1014562/155127016-d6ddeabb-0942-4e0c-a444-91356d5911ad.png)
![image](https://user-images.githubusercontent.com/1014562/155127038-4935af7a-9e22-49e1-a932-31af7222e37d.png)
![image](https://user-images.githubusercontent.com/1014562/155127066-4346e006-5c94-4a16-854d-c916c9c2b231.png)
![image](https://user-images.githubusercontent.com/1014562/155127598-0a8bb606-5b87-4484-86ac-a5587d2cea00.png)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Android are the ones I've checked]
 - Browser: [Chrome, Firefox, Safari, Brave]
 - Three.js version: [r137, r138dev, and previous versions from r126+, at least]

**Comment by mrdoob** [comment]
This is a classing problem in computer graphics. It's called *peter panning*:

https://docs.microsoft.com/en-us/windows/win32/dxtecharts/common-techniques-to-improve-shadow-depth-maps
https://digitalrune.github.io/DigitalRune-Documentation/html/3f4d959e-9c98-4a97-8d85-7a73c26145d7.htm

At the moment we only have [`bias`](https://threejs.org/docs/#api/en/lights/shadows/LightShadow.bias) and [`normalBias`](https://threejs.org/docs/#api/en/lights/shadows/LightShadow.normalBias) to try to work around this.
