### ISSUE TITLE
THREE.Color getHex() sometimes returns negative values

### ISSUE THREAD

**Issue by verybigelephants** [mrdoob/three.js#23552]
**Describe the bug**

Sometimes, when creating a Threejs Color from 3 separate rgb values the color gets created in a strange way that all the color manipluation related to getting hex values returns wrong values. 

**Code to Reproduce**

var r = [Math.random()*256, Math.random()*256, Math.random()*256];
var rand_color = new THREE.Color(r[0], r[1], r[2]);

```
console.log(r);
console.log(rand_color);
console.log(rand_color.getHex());//this is sometimes negative
console.log(rand_color.getHexString()); //this string is then affected too 
```

For example, these are values that create such negative color:
```
var c = new THREE.Color(172.10908897579378, 171.64128648818325, 101.05378373805644);
console.log(c.getHex()); //returns -1413112664
console.log(c.getHexString()); //returns '3a6358', which is different color than what THREE.js internally represents
```

edit: This does not always happen with decimals only as i previously thought, it happens with integers too, for example
```
var c = new THREE.Color(241, 52, 177);
console.log(c.getHex()) // -264471473
```

**Expected behavior**

Getting the same hex value as the one that THREE.js represents internally too.

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome, Firefox
 - Three.js version: r124

**Comment by Mugen87** [comment]
> var c = new THREE.Color(172.10908897579378, 171.64128648818325, 101.05378373805644);

This is no valid instantiation. The RGB values are supposed to be in the 0-1 range.

**Comment by verybigelephants** [comment]
thank you, my bad :(

**Comment by mrdoob** [comment]
Maybe we could clamp values in `getHex()` and `getHexString()`?

**Comment by mrdoob** [comment]
Yes, I don't think the values in `Color` should be clamped. Only the relevant methods.

Would you like to try doing a PR for it?

**Comment by verybigelephants** [comment]
okay! https://github.com/mrdoob/three.js/compare/dev...verybigelephants:patch-1

**Comment by mrdoob** [comment]
We have a `clamp()` in `MathUtils`.

This is simpler: 

```js
getHex() {

	return clamp( this.r * 255, 0, 255 ) << 16 ^ clamp( this.g * 255, 0, 255 ) << 8 ^ clamp( this.b * 255, 0, 255 ) << 0;

}
```

**Comment by verybigelephants** [comment]
Oh ok, i didn't know. It looks nice, but the issue i have with this patch is that it doesn't inform the user that some of the colors were out of the clamped values. I think this is definitely something that a user should be notified about otherwise it calls for some bugs.

**Comment by mrdoob** [comment]
We can reconsider if we get any reports.

**Comment by WestLangley** [comment]
> it doesn't inform the user that some of the colors were out of the clamped values

@verybigelephants three.js does not validate inputs. It is your app's responsibility to do that.

@mrdoob @Mugen87 What is your objective by clamping? Doing so just obfuscates the problem, and silently returns an incorrect answer.

**Comment by mrdoob** [comment]
Both answers are incorrect.

But I think returning black when the color is below 0, and white when the color is above 1 is easier to understand than returning a negative hex.

That's also how the web behaves:

```js
// Makes the background white and doesn't warn the user that colors go from 0 to 255
document.body.style.backgroundColor = 'rgb(512, 512, 512)'

// Makes the background black and doesn't warn the user that colors go from 0 to 255
document.body.style.backgroundColor = 'rgb(-512, -512, -512)'
```

There may be other methods where this may make sense but I do not think we should clamp `Color`.

**Comment by verybigelephants** [comment]
> > it doesn't inform the user that some of the colors were out of the clamped values
> 
> @verybigelephants three.js does not validate inputs. It is your app's responsibility to do that.
> 
> @mrdoob @Mugen87 What is your objective by clamping? Doing so just obfuscates the problem, and silently returns an incorrect answer.

I'm not implying to validate inputs. I am saying that the library should provide me with invalid returns for invalid answers but throw an exception/at least a warning like i provided in the PR. I also don't think that the current patch is good
