### ISSUE TITLE
Uncaught TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by charles-hay** [mrdoob/three.js#23568]
My application was running properly across multiple branches and then I started getting the following error repeatedly shown in the console. 
```
Uncaught TypeError: Invalid value used as weak map key
```
this error occurred locally and from the site hosting on S3

***Live example***

* [S3 static site hosting](https://avatar-prod-src.s3.amazonaws.com/index.html)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/89037936/155403425-dbbbbc29-1ef4-4c06-b9d3-2276ec64f52b.png)

**Platform:**

 - Device: Desktop
 - OS: Windows, MacOS, Linux, Android, iOS]
 - Browser: Chrome
 - Three.js version: the source is https://threejs.org/build/three.min.js

**Comment by Mugen87** [comment]
Can you please use the unminified version in your app?

BTW: Do never use `https://threejs.org/build/three.min.js` to include `three.js`. `https://threejs.org` is no CDN. Always use a versioned link this one to avoid unexpected breakage:

https://cdn.jsdelivr.net/npm/three@0.137.5/build/three.js

**Comment by Mugen87** [comment]
You have this line in your app:

> WARNING: Multiple instances of Three.js being imported.

I suggest you resolve this first and then reopen the issue. Right now, your library files are out of sync since you use library files from different releases.

**Comment by charles-hay** [comment]
Thank you so much! @Mugen87

**Comment by lovesossa** [comment]
This error also throws when you use wrong loader for texture. Might be useful to someone.
