### ISSUE TITLE
Feature Suggestion: CapsuleGeometry

### ISSUE THREAD

**Issue by gsimone** [mrdoob/three.js#23579]
More of an RFC than a proper suggestion, I was wondering why we don't have a built-in generator for a Capsule geometry and if there's an argument to be made against adding it.

### Pro
- it's a widely used geometry in games (eg. for colliders), meaning it would be useful being able to also have a mesh representing the same info
- we already ship a math version of the capsule related to the FPS example
- there are solid existing implementations that might be adopted without many changes:
	- https://github.com/maximeq/three-js-capsule-geometry
	- https://codepen.io/prisoner849/pen/qBaNKNM 

### Con
- something else to maintain and document, this is never free
- creates a slippery slop of "so why don't we add *insert random geometry*" (although this is a bit of a strawman argument)

Curious to know everyone's opinion on this.

Stay safe, hugs ❤️ 

EDIT:

@WestLangley mentioned #21301 as a prev. proposal. 
@mrdoob suggested here ( https://github.com/mrdoob/three.js/pull/21301#issuecomment-781503538 ) that we could use lathe geometry to make the capsule, much like the codepen linked above. 
Could this be a good road to follow? People get the geometry and the additional code is minimal, could be a win-win

**Comment by WestLangley** [comment]
Related: #21301

**Comment by gsimone** [comment]
Thanks, updated the issue description. Using lathe looks like something we could pursue

**Comment by gsimone** [comment]
Made a quick draft of the geometry, based on the codepen by @cywarr

https://codesandbox.io/s/three-js-lathe-capsulegeometry-9iey6z?file=/src/CapsuleGeometry.js

**Comment by mrdoob** [comment]
Yep yep! Adding a `CapsuleGeometry` would be great! 👍👍👍

**Comment by gsimone** [comment]
Made a PR 👍 👍

**Comment by WestLangley** [comment]
I think `radius` and `length` are sufficient. Capsules typically have the same radius at both ends.

**Comment by mrdoob** [comment]
I think I agree. It matches physics engines too.
