### ISSUE TITLE
MathUtils.seededRandom() returned value is linearly correlated to the parameter

### ISSUE THREAD

**Issue by thibka** [mrdoob/three.js#23575]
Hey,

According to the doc, MathUtils.seededRandom() should return a (pseudo random) float in the interval [0, 1]. 
However the returned value is linearly correlated to the provided integer parameter: the bigger the seed, the bigger the result.

For instance: 
```javascript
MathUtils.seededRandom(1); // returns 0.000007825903601782307
MathUtils.seededRandom(10); // returns 0.00007826322696941274
MathUtils.seededRandom(100); // returns 0.0007826364606457171
MathUtils.seededRandom(1000); // returns 0.00782636879740876
```

As far as I know, the results of a prng function shouldn't be so predictable, but maybe I'm misunderstanding something.

Three.js version: 0.138.0

Cheers

**Comment by mrdoob** [comment]
I guess that's an issue with the Park-Miller algorithm:

https://github.com/mrdoob/three.js/blob/a7863bd6d249ab735cb4c4a255f5dc1b9994c4b0/src/math/MathUtils.js#L133-L144

Do you know of a better one?

**Comment by thibka** [comment]
So far I've been happily using this mulberry32 prng function.

https://gist.github.com/tommyettinger/46a874533244883189143505d203312c

```javascript
function mulberry32(a) {
    return function() {
      var t = a += 0x6D2B79F5;
      t = Math.imul(t ^ t >>> 15, t | 1);
      t ^= t + Math.imul(t ^ t >>> 7, t | 61);
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    }
}

var seed = 1;
var prng = mulberry32( seed );
console.log(prng()); // 0.6270739405881613
console.log(prng()); // 0.002735721180215478
```

As you can see it works a bit differently than the current MathUtils.seededRandom function, since providing a seed here actually returns a function, instead of a number. 
I think this approach would better suit the needs of a user working with pseudo random numbers though, but I could be wrong.

**Comment by Mugen87** [comment]
> As far as I know, the results of a prng function shouldn't be so predictable

Does the current behavior introduce any issues on app level? 

The result of `seededRandom()` should be a number and not a function in order to keep the usage simple.

**Comment by thibka** [comment]
> Does the current behavior introduce any issues on app level?

Well the current behavior just doesn't work as it should. So I'm not sure the current seededRandom function could be used in a scenario where a PRNG would be needed.

> The result of seededRandom() should be a number and not a function in order to keep the usage simple.

That's true. In that case you could always rewrite the MathUtils.seededRandom function with the mulberry32 algorithm this way:

```javascript
// Deterministic pseudo-random float in the interval [ 0, 1 ]
function seededRandom( s ) {

	if ( s !== undefined ) _seed = s;

	// Mulberry32 generator

	var t = _seed += 0x6D2B79F5;

	t = Math.imul(t ^ t >>> 15, t | 1);

	t ^= t + Math.imul(t ^ t >>> 7, t | 61);

	return ((t ^ t >>> 14) >>> 0) / 4294967296;

}
```

The behavior would then be fixed:

```javascript
THREE.MathUtils.seededRandom(); // 0.6074679309967905 (depends on the previous value of the private _seed variable)
THREE.MathUtils.seededRandom(); // 0.19144689152017236 (depends on the previous value of the private _seed variable)
THREE.MathUtils.seededRandom(1); // 0.6270739405881613 (always)
THREE.MathUtils.seededRandom(10); // 0.5019920116756111 (always)
THREE.MathUtils.seededRandom(100); // 0.2043598669115454 (always)
THREE.MathUtils.seededRandom(); // 0.3148212195374071 (depends on the previous value of the private _seed variable)
```

**Comment by thibka** [comment]
Actually, I overlooked this minor fix, which is probably preferable 

```javascript
// Deterministic pseudo-random float in the interval [ 0, 1 ]
function seededRandom( s ) {

	//if ( s !== undefined ) _seed = s % 2147483647;
	if ( s !== undefined ) _seed = s * 16807 % 2147483647; // FIX

	// Park-Miller algorithm

	_seed = _seed * 16807 % 2147483647;

	return ( _seed - 1 ) / 2147483646;

}
```

Results would then be: 

```javascript
THREE.MathUtils.seededRandom(); // 0.6621772173439872 (depends on the previous value of the private _seed variable)
THREE.MathUtils.seededRandom(); // 0.21249454395146533 (depends on the previous value of the private _seed variable)
THREE.MathUtils.seededRandom(1); // 0.13153778773875702 (always)
THREE.MathUtils.seededRandom(10); // 0.3153778811128604 (always)
THREE.MathUtils.seededRandom(100); // 0.15377881392257178 (always)
THREE.MathUtils.seededRandom(); // 0.5605322192986796 (depends on the previous value of the private _seed variable)
```

**Comment by Mugen87** [comment]
Okay, let's give this a try then 👍 .

**Comment by mankeheaven** [comment]
https://stackoverflow.com/questions/521295/seeding-the-random-number-generator-in-javascript

It includes many pseudorandom number generator functions

**Comment by saolda** [comment]
The idea of seeded pseudo random number generators (SPRNGs) is to produce a sequence of seemingly random numbers, where the same sequence is generated each time, given the same seed. Different seeds generate different sequences. I could use a SPRNG to generate "worlds" and the seed as an index for each "world," so I could have world(1), world(2) etc. This is why seedRandom() needs to return a *function* (which I would use to generate a sequence of "random" numbers). Returning a single number does *not* simplify. It just misses the point.

**Comment by saolda** [comment]
I think this needs to be reopened. I'm new here though, don't know how to do that. Hopefully someone will eventually see this.

**Comment by mrdoob** [comment]
@saolda Have you studied how we're using it?
