### ISSUE TITLE
`UniformUtils` does not set `needsUpdate` to true for Texture uniforms

### ISSUE THREAD

**Issue by FarazzShaikh** [mrdoob/three.js#23572]
**Describe the bug**

As [explained by the docs](https://threejs.org/docs/index.html?q=textu#api/en/textures/Texture.clone), when a texture is cloned, the `needsUpdate` flag must be set to true. Else, the texture appears black.

`UnifromUtils.clone` and by extension, `UnifromUtils.merge`, do not set this flag even though they clone Texture and other uniform types.

https://github.com/mrdoob/three.js/blob/f51dd8a065ad9ca7a346b6fdd8b8e0a7f8f92338/src/renderers/shaders/UniformsUtils.js#L22

Easy fix, will PR in the morning if this is indeed a bug and not intended.

**To Reproduce**

1. Create a unifrom object with a texture property
2. Clone the unifrom
3. Use cloned unifrom, the texture will appear black.

***Code***

```js
// Works
material.uniforms.u_map.value = texture;

// Doesnt work (texture is black)
const clonedUifroms = UniformsUtils.clone(material.uniforms);
material.uniforms.u_map.value = clonedUifroms.u_map.value;

// To fix
material.uniforms.u_map.value.needsUpdate = true;
```

***Live example***

[CodeSandbox](https://codesandbox.io/s/angry-architecture-lnkdb6?file=/src/index.js:1280-1299)

**Expected behavior**

The "To fix" line shouldn't be required, `UniformsUtils.clone` should set `needsUpdate` automatically. 

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [0.138.0]

**Comment by WestLangley** [comment]
See https://github.com/mrdoob/three.js/issues/22718#issuecomment-948579908

**Comment by FarazzShaikh** [comment]
Fair enough, cheers!
