### ISSUE TITLE
Feature Request: Break out loaders into independent module

### ISSUE THREAD

**Issue by gm112** [mrdoob/three.js#23570]
**Is your feature request related to a problem? Please describe.**
No, it is not. This is more of a distribution thing in relation to code.

Why aren't the loaders isolated into their own module, and why do all references to say - the GLTFLoader, recommend you just directly reference the code? This seems to be the case for all loaders that are maintained by the threejs team, and it seems like an odd choice from an outsiders perspective. The loaders are coupled within threejs and are therefore tied to the release cadence of threejs itself. And, hosting the loader code within the `examples` folder may give the wrong impression for other users of threejs that this code is actually a library to use with threejs.

It seems counter productive to have the loaders by tucked away inside of the examples folder when a lot of the documentation makes use of any threejs loader that is maintained by the threejs team.

**Describe the solution you'd like**
A new ES Module that contains all of the officially supported(as in threejs team currently actively maintains) loader classes for threejs.

All of the threejs loaders that are considered to be first-class support status by the threejs team to be isolated into its own ES Module, with a separate release cadence from threejs proper.

**Describe alternatives you've considered**
Possibly moving the loader files out of the examples folder, so that its not potentially giving the wrong impression to new developers to not use these loaders, maybe? An import-map can also satisfy the requirement of an ES Module.

N/A; see above.

**Additional context**
I am arguing from the perspective of a user of threejs that it seems unnecessary to require an entire release of threejs for fixes that are specific to the loaders themselves, which is why I argue in favor of a separate release cadence from threejs proper. This wouldn't mean that the two would be completely decoupled; rather, it would just free up the accessibility to new loaders, bug fixes, etc, that are specific to threejs loaders from the rest of the codebase.

N/A

**Comment by mrdoob** [comment]
Sorry, having a hard time to read what you just wrote. Please to rewrite it in a more clear an concise way.

Closing in the meantime.

**Comment by gm112** [comment]
I was following your template for a feature request. The tl;dr is - it would be nice to have the threejs loaders moved out of the `examples` folder and into maybe another folder or repository, so that they can be versioned independently from the rest of threejs.

**Comment by mrdoob** [comment]
Thanks for the tl;dr.

Unfortunately the consequences of such change is something we currently do not have the bandwidth for.

**Comment by gm112** [comment]
Oh, that's totally understandable. Would it be unreasonable for an outside contributor to propose this as a PR, then?

**Comment by mrdoob** [comment]
It's not about the PR, it's about the maintenance work that it would entail for the next few years.

**Comment by gm112** [comment]
Hmm, fair point. You would have to maintain a separate thread of issues, as well as release cycle in addition to threejs, hence the bandwidth problem being a long-term issue. Well, I appreciate you answering and providing additional feedback!
