### ISSUE TITLE
Custom Shader Chunk includes broken since THREEjs v. 138

### ISSUE THREAD

**Issue by jocabola** [mrdoob/three.js#23580]
Hello there!

I have upgraded one project to latest THREEjs 138, and suddenly all my custom shader chunk includes no longer work.

This is what I would usually do:

```
import noise3D from '../../glsl/lib/snoise3D.glsl';
import noise4D from '../../glsl/lib/snoise4D.glsl';

ShaderChunk['noise3D'] = noise3D;
ShaderChunk['noise4D'] = noise4D;

```

Then have `#include <noise4D>` in my shader for example.

This causes a JS error in includeReplacer since v. 138. See screenshot below:

![image](https://user-images.githubusercontent.com/97088/155591686-75580ca4-d6ab-477c-99ed-7175093d5346.png)

THANKS!

**Comment by Mugen87** [comment]
> I have upgraded one project to latest THREEjs 138

From what release have you performed the upgrade? It does not sound like you have switched over from `r137`.

In any event, please share an _editable_ live example that demonstrates the issue.

**Comment by jocabola** [comment]
I was upgrading from v 137.5 to 138. I can't share this example precisely cause it's a WIP client project but will look at creating an isolated example and see. I use 11ty, esbuild and TypeScript as my "boilerplate". Will create a sample and share. Thanks!

**Comment by jocabola** [comment]
OK, I have isolated this scenario into a "clean" test and I no longer get the error happening. There must be another reason why this is happening to me in my other project when upgrading from 137.5 to 138. Will investigate.

Sorry for the confusion and thanks for your time!

Cheers
