### ISSUE TITLE
All CSS2DObjects disappear if one of them gets outside view frustum

### ISSUE THREAD

**Issue by Bierro** [mrdoob/three.js#23593]
**Describe the bug**

When using CSS2DRenderer, if one CSS2DObject gets further than the camera far plane, or closer than the near plane, then all CSS2DObjects disappear and never reappear afterwards.

The issue seems to come from this [line](https://github.com/mrdoob/three.js/blob/master/examples/jsm/renderers/CSS2DRenderer.js#L116):
`const visible = object.visible && _vector.z >= - 1 && _vector.z <= 1 && object.layers.test( camera.layers );`

If `_vector.z` ever gets outside of [-1,1] ,  `visible` will be false in all subsequent render calls and `_vector` never gets reupdated.

**To Reproduce**

1. Go to [CSS 2D Label example](https://threejs.org/examples/?q=label#css2d_label)
2. Zoom as close to the Earth as possible
3. Wait for the moon to get behind camera
4. Watch labels disappear

Before the moon gets behind camera near plane:
<img width="1366" alt="Screen Shot 2022-02-25 at 16 43 50" src="https://user-images.githubusercontent.com/16521410/155822418-c2014414-3039-47fd-aa72-505a9bc43223.png">

After the moon went behind camera near plane:
<img width="1366" alt="Screen Shot 2022-02-25 at 16 43 56" src="https://user-images.githubusercontent.com/16521410/155822847-b89939c3-14b5-4944-88e9-10a1244f9921.png">

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Chrome, Firefox, Safari]

**Comment by Mugen87** [comment]
Another regression that was introduced via #23316. Let me fix it.
