### ISSUE TITLE
RFC: Additional linting rule for import extensions

### ISSUE THREAD

**Issue by gsimone** [mrdoob/three.js#23591]
While doing https://github.com/mrdoob/three.js/pull/23586 I didn't think of using extensions in imports and the docs code worked. The qunit code would instead fail.

Plugin 👉  https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/extensions.md

```
"rules":  {
	...
	      "import/extensions": [
        "error",
        "always"
      ],
   ...
}
```

This would error whenever an import is added without extension. 

1 less thing to think about in PRs

**Comment by mrdoob** [comment]
Sounds good to me 👍
