### ISSUE TITLE
Nodes: Add StorageNode

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#23598]
**Is your feature request related to a problem? Please describe.**

I want to be able to use the WebGPUStorageBuffer in the Nodes system (similarly to the WebGPUUniformBuffer).

**Describe the solution you'd like**

I suggest adding the StorageNode based on the WebGPUStorageBuffer (similarly to how the BufferNode is based on the WebGPUUniformBuffer).

**Comment by sunag** [comment]
https://github.com/mrdoob/three.js/pull/23905#issuecomment-1105669449

**Comment by LeviPesin** [comment]
@sunag Can you please add a `StorageNode.dispose()` function?

**Comment by sunag** [comment]
Can you show me the scenario? Normally we don't use `BufferAttribute.dispose()` in three.js, but classes above like `Geometry`. Maybe I can add this on `ComputeNode`?

**Comment by LeviPesin** [comment]
So that we can dispose the GPU memory of an underlying WebGPUStorageBuffer.

**Comment by LeviPesin** [comment]
Also, I think we need a function for transferring the GPU buffer data to the CPU (like `renderer.readRenderTargetPixels` in WebGL, but based on `buffer.unmap()`) and vice versa...
