### ISSUE TITLE
`camera.getWorldPosition/...` returning the wrong result in XR mode

### ISSUE THREAD

**Issue by yelouafi** [mrdoob/three.js#23597]
Hey guys we recently upgraded our threejs version and encountered some wierd behavior from camera in XR mode. After some debugging turns out this PR was the clurpit

https://github.com/mrdoob/three.js/pull/21964/files#diff-a27b9d3ba68457069cc8ff521208ae9d0cc6d9256f6f48ada6316fc2d732ba7e

So basically before that PR the code was

https://github.com/mrdoob/three.js/blob/ec96437a05b7c3f9f3e64951a9b17f6be6314129/src/renderers/webxr/WebXRManager.js#L381-L385

Which took the position/rotation/scale from the local matrix of VR camera

but after the PR it's doing this now

https://github.com/mrdoob/three.js/blob/31565e65385ec6f61a567dba2678e6689601d4f9/src/renderers/webxr/WebXRManager.js#L381-L389

which updates camera's position/rotation/scale from the global  matrix of the VR camera

But that means that if the camera has got a parent then `camera.getWorldPosition(...)` would return the wrong result since now we'll be counting the transform 2 times. Since the camera's position (same for rotation ...) has already the world position that was copied from VR camera's global matrix

Was this ane expected behavior from the PR? because now every code that relies on `getWorldXXX` would break in XR

**Comment by yelouafi** [comment]
seems related to #22362

hope this will be merged as soon as possible, because I think the current behavior would break other things relying on camera's world coordinates like PositionalAudio

**Comment by Mugen87** [comment]
Indeed. There is actually an issue for `PositionlAudio`: #22884
