### ISSUE TITLE
Failed to Load VTP File 

### ISSUE THREAD

**Issue by gsihaj5** [mrdoob/three.js#23609]
**Describe the bug**

I want to load a vtp file. and i think it failed to load because null type inside VTKLoader

**To Reproduce**

1. i use react js
2. add input type file
3. after selecting a vtp file get the path
4. insert the path inside load(path, onload())

***Code***

it failed from the loader, so i think it doesn't have any problem with three-fiber

```js
	const stlLoader = new STLLoader()
	const vtkLoader = new VTKLoader()
	const file = event.target.files[0]
		const fileType = file.name.split('.').pop()

		function onLoad (geometry) {
			console.log(geometry)
			geometry.center()
			geometry.rotateX(-Math.PI / 2)

			geometry.computeBoundingBox()
			geometry.computeBoundingSphere()
			let mesh = <mesh geometry={geometry}>
				<meshLambertMaterial color={'#cfae55'} side={DoubleSide} transparent={true} clipIntersection={true}/>
			</mesh>
			props.onFileImport(mesh)
		}

		if (fileType === 'stl')
			stlLoader.load(file.path, (geometry) => onLoad(geometry))
		else if (fileType === 'vtp')
			vtkLoader.load(file.path, (geometry) => onLoad(geometry))

```

***Live example***

**Expected behavior**

able to load vtp file inside the scene 
the stl loader works perfectly

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**
using npm start for reactjs and point electron app to localhost:3000

 - Device: Desktop
 - OS: Windows
 - Browser: Electron
 - Three.js version: 0.137.5

**what i have done**

i check the code using debugger and found out in VTKLoader file

that this piece of code not assigning the text attribute
![image](https://user-images.githubusercontent.com/55443217/155924079-45e07cdf-6ed8-471b-9373-60e976241ec3.png)

and it effects to this piece of code can't get the text attribute and returning null value
![image](https://user-images.githubusercontent.com/55443217/155924338-29e553da-3d47-4caa-b3a8-6e640797c605.png)

**Comment by Mugen87** [comment]
Do you mind sharing the VTP file in this issue?

**Comment by gsihaj5** [comment]
owh sorry, here is the vtp file that i tried to import 
[Example_02_predicted_refined.zip](https://github.com/mrdoob/three.js/files/8152407/Example_02_predicted_refined.zip)

**Comment by Mugen87** [comment]
Your VTK files makes use of the "appended" format which is not yet supported by the loader. From the spec:

>  format=”appended” — The data are stored in the appended data section. Since many DataArray elements may store their data in this section, the offset attribute is used to specify where each DataArray’s data begins. This format is the default used by VTK’s writers.

**Comment by gsihaj5** [comment]
thank you, i just don't know vtk have wide variety of type

**Comment by gsihaj5** [comment]
in case someone facing same problem 
vtk consist some part, mine is AppendedData it contains binary encoding

![image](https://user-images.githubusercontent.com/55443217/155984827-f76e6a47-c436-4667-a2d2-242f648dd5c3.png)

**Comment by Mugen87** [comment]
Merging into #13386.
