### ISSUE TITLE
how to use the Spatial mapping of HoloLens

### ISSUE THREAD

**Issue by DLGL99GL** [mrdoob/three.js#23608]
This is mainly to achieve remote video annotation function;Real spatial location is obtained by environmental grid ray collision detection；

it worked in Unity by spatial mapping of HoloLens; How do I implement this feature by Three.js；

THREE.Raycaster    it worked in UI or model，but not worked in real environment

**Comment by Mugen87** [comment]
Please use the forum for such requests: https://discourse.threejs.org/
