### ISSUE TITLE
Nodes: Add node for fetching pixel's position

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#23602]
**Is your feature request related to a problem? Please describe.**

I want to be able to get the pixel's position in a fragment shader using Nodes system.

**Describe the solution you'd like**

I suggest adding a node for that (named e.g. PixelNode) which resolves to the gl_FragCoord in the GLSL and @ builtin(position) * resolution in the WGSL (where resolution could be a defined by the NodeBuilder uniform or just an argument passed to the constructor of PixelNode).
Also I suggest adding a node for fetching normalized pixel's position - i.e. node which is just PixelNode divided by resolution and resolves to gl_Position or @ builtin(position).

**Comment by sunag** [comment]
That wouldn't be the same as `negate( positionView.z )`? https://github.com/mrdoob/three.js/pull/23606
But I think we can move forward with this too.

**Comment by sunag** [comment]
https://github.com/mrdoob/three.js/pull/24934
