### ISSUE TITLE
Response type error when import 'https://jspm.dev/three/examples/jsm/postprocessing/UnrealBloomPass.js'

### ISSUE THREAD

**Issue by viviuolo** [mrdoob/three.js#23615]
**Describe the bug**
we use this file('https://jspm.dev/three/examples/jsm/postprocessing/UnrealBloomPass.js' ) in our program and response is below:
import "/npm:three@0.137.5";
import "/npm:three@0.137.5/examples/jsm/postprocessing/Pass.js";
import "/npm:three@0.137.5/examples/jsm/shaders/CopyShader.js";
import "/npm:three@0.137.5/examples/jsm/shaders/LuminosityHighPassShader.js";
export * from "/npm:three@0.137.5/examples/jsm/postprocessing/UnrealBloomPass.js";

but we got a extra file: 'https://jspm.dev/npm:three@0.137.5/' which caused a response type error
<img width="1662" alt="image" src="https://user-images.githubusercontent.com/22727579/156098805-04a0b3ac-b3f9-4119-93bc-e0106d3342d0.png">

<img width="758" alt="image" src="https://user-images.githubusercontent.com/22727579/156098857-f79b03df-e282-4440-88c3-59af3bc28a46.png">

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**To Reproduce**

3. See error

***Code***

```js
// code goes here
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hyok6tvj/)
* [jsfiddle-dev](https://jsfiddle.net/c5m1kazu/)

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r???]
<img width="767" alt="截屏2022-03-01 上午11 23 50" src="https://user-images.githubusercontent.com/22727579/156098963-28302860-af8f-4c62-a55c-084fd0950380.png">
<img width="1656" alt="截屏2022-03-01 上午11 24 03" src="https://user-images.githubusercontent.com/22727579/156098971-eaf35d33-977d-4520-9e1d-0a25b451db1f.png">

**Comment by Mugen87** [comment]
Um, how are supposed to fix this? Isn't that an issue of `jspm`?
