### ISSUE TITLE
Legacy classes cannot be extended

### ISSUE THREAD

**Issue by vanruesc** [mrdoob/three.js#23612]
**Describe the bug**

Some classes were renamed or replaced by other classes in r138 and legacy wrapper functions were added for backward-compatibility. These functions print a deprecation warning, then use the new class to create an object and finally _return_ it. This is problematic because returning an object from a constructor function messes with the prototype chain and circumvents the `this` object. The result is that any other properties and methods defined in subclasses will be lost.

A lot of the legacy wrappers were added many years ago and can probably be left as-is. The one I'm struggling with now is `DataTexture3D`. The problem is that I can't just use the new `Data3DTexture` because I want my code to support r138 _and_ older versions of `three`.

For completeness' sake, I'll list all affected classes: [PointCloud, Particle, ParticleSystem, PointCloudMaterial, ParticleBasicMaterial, ParticleSystemMaterial, Vertex, DynamicBufferAttribute, Int8Attribute, Uint8Attribute, Uint8ClampedAttribute, Int16Attribute, Uint16Attribute, Int32Attribute, Uint32Attribute, Float32Attribute, Float64Attribute](https://github.com/mrdoob/three.js/blob/62c6fabc5e9c948ffd984192ed8588068f8253ee/src/Three.Legacy.js#L113-L232), [AxisHelper, BoundingBoxHelper, EdgesHelper](https://github.com/mrdoob/three.js/blob/62c6fabc5e9c948ffd984192ed8588068f8253ee/src/Three.Legacy.js#L259-L278), [WireframeHelper](https://github.com/mrdoob/three.js/blob/62c6fabc5e9c948ffd984192ed8588068f8253ee/src/Three.Legacy.js#L292-L297), [WebGLRenderTargetCube](https://github.com/mrdoob/three.js/blob/62c6fabc5e9c948ffd984192ed8588068f8253ee/src/Three.Legacy.js#L1671-L1676), [XHRLoader, BinaryTextureLoader](https://github.com/mrdoob/three.js/blob/62c6fabc5e9c948ffd984192ed8588068f8253ee/src/Three.Legacy.js#L324-L336), [ParametricGeometry and TextGeometry](https://github.com/mrdoob/three.js/blob/62c6fabc5e9c948ffd984192ed8588068f8253ee/src/Three.Legacy.js#L1959-L1971), [WebGLMultisampleRenderTarget, DataTexture2DArray, DataTexture3D](https://github.com/mrdoob/three.js/blob/62c6fabc5e9c948ffd984192ed8588068f8253ee/src/Three.Legacy.js#L1991-L2012).

**To Reproduce**

1. Extend `DataTexture3D` and define a method `foo`
2. Use the subclass to create a `texture` and call `texture.foo()`.
3. See error `TypeError: texture.foo is not a function`.

**Code Example**

```js
function A() {

	return {};

}

class B extends A {

	foo() {}

}

const b = new B();
b.foo();
```

**Expected behavior**

The legacy classes should not break existing code. In this particular case, _subclassing_ is broken for the specific classes mentioned above. To make this more robust, the legacy classes could instead extend the new classes:

```js
// Current approach
export function DataTexture3D( data, width, height, depth ) {

	console.warn( 'THREE.DataTexture3D has been renamed to Data3DTexture.' );
	return new Data3DTexture( data, width, height, depth );

}

// Suggested approach
export class DataTexture3D extends Data3DTexture {

	constructor( data, width, height, depth ) {

		console.warn( 'THREE.DataTexture3D has been renamed to Data3DTexture.' );
		super( data, width, height, depth );

	}

}
```

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Firefox
 - Three.js version: r138

**Comment by LeviPesin** [comment]
Why you can't just do something like `if ( Data3DTexture !== undefined ) { DataTexture3D = Data3DTexture }`? This will also remove warnings.

**Comment by vanruesc** [comment]
@LeviPesin That would work if `three` was included in its entirety as an external library, but I'm importing classes from the `three` module. If I import `Data3DTexture` from "three" in `postprocessing`, then anyone who uses `postprocessing` with an older version of `three` will get a bundler error: `No matching export in "node_modules/.pnpm/three@0.135.0/node_modules/three/build/three.module.js" for import "Data3DTexture"
`.
