### ISSUE TITLE
GLTFLoader: Regressions in PBR rendering with r138

### ISSUE THREAD

**Issue by elalish** [mrdoob/three.js#23627]
**Describe the bug**

I've got two fidelity test failures on [upgrading model-viewer](https://github.com/google/model-viewer/pull/3231) to r138.2: See the .pngs I uploaded in the PR for how the renders changed. The SpecGloss extension has lightened considerably, and we're now failing most of the khronos-TextureSettingsTest. @donmccurdy @Mugen87 Any thoughts on what PRs might have affected this? I'm happy to help, but hoping you might have a pointer first.

**Comment by mrdoob** [comment]
You've upgraded from r136 to r138.
Can you try upgrading to r137 instead so we can narrow down the issue?

**Comment by elalish** [comment]
Okay, git bisect pointed to the #23420 as what broke khronos-TextureSettingsTest, but I haven't looked into why yet. @takahirox Any thoughts? I'm going to check the other one now.

**Comment by elalish** [comment]
Okay, and the other git bisect points to #23129, which makes sense since it has the look of a wrong sRGB conversion for the spec gloss texture, @Mugen87.

**Comment by elalish** [comment]
Here are the changed renderers in case you don't want to dig in my PR: 
<img width="853" alt="image" src="https://user-images.githubusercontent.com/1649964/156274773-d4293950-499c-4b2c-857d-c750d8550a96.png">

**Comment by elalish** [comment]
I'm done for today; if no one has looked into these tomorrow I'll start debugging.

**Comment by Mugen87** [comment]
Sidenote: A texture with different encoded texels components is definitely no good approach.

**Comment by Mugen87** [comment]
> Okay, and the other git bisect points to https://github.com/mrdoob/three.js/pull/23129, which makes sense since it has the look of a wrong sRGB conversion for the spec gloss texture, @Mugen87.

The removal of the inline sRGB decode was done under the assumption the color space for the texture is properly defined. It looks like this is not the case.

**Comment by donmccurdy** [comment]
About the failing texture clamp/wrap/repeat test, I've noticed that if the internal cache here is commented out...

https://github.com/mrdoob/three.js/blob/c5e0fdf05186247efa84b6f2966657ac0330879b/examples/jsm/loaders/GLTFLoader.js#L2905-L2917

... the test cases all pass. So I think the changes by @takahirox in the PR are correct, but there's something about sharing a `Source` that prevents reuse with different clamp/wrap/repeat settings?

**Comment by Mugen87** [comment]
Actually, `GLTFLoader` just misses to set `Texture.needsUpdate` to `true` after the `clone()` operation.

**Comment by elalish** [comment]
Thanks for figuring these out @Mugen87! @mrdoob any chance we could see #23630 and #23637 in an r138.3? Sorry I didn't find these sooner; I thought I had run this test last week, but apparently I forgot to push...

**Comment by Mugen87** [comment]
@mrdoob Please also include #23650 in `r138.3` 😇 .

**Comment by mrdoob** [comment]
Done!

**Comment by mrdoob** [comment]
@elalish `0.138.3` is out.

**Comment by elalish** [comment]
I've merged r138.3 and it's looking good 👍
