### ISSUE TITLE
Avoid bare imports other than 'three'

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#23625]
Related:

- https://github.com/mrdoob/three.js/pull/23560

With r138 the following syntax was introduced:

```js
import { NormalNode } from 'three-nodes/Nodes.js';
```

I do not think we should be using bare imports (except `three`) unless we are publishing it to a separate NPM package. Bundlers cannot resolve `three-nodes` without custom resolution configuration, and we're seeing confusion about this in Discord. By contrast, anything under the `three` import is fine if we configure it in package.json exports:

```js
import { NormalNode } from 'three/nodes/Nodes.js';
```

/cc @sunag

**Comment by marcofugaro** [comment]
Ah yes, about this, I'm awaiting @mrdoob's response in #23406

**Comment by Mugen87** [comment]
It seems this bug is fixed with `r144`, right?

**Comment by donmccurdy** [comment]
Agreed, thanks!
