### ISSUE TITLE
Unify constructor() and set() in Matrix and Color classes

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#23634]
**Is your feature request related to a problem? Please describe.**

Currently, the Matrix and Color classes have the constructor() and set() methods accepting different arguments.

It means that, for example, `new Vector3(x, y, z)` and `new Vector3().set(x, y, z)` will produce the same results, while Matrix and Color will not - Matrix constructor does not accept any arguments (set() accepts), while Color set() method does not support multiple arguments (constructor supports).

One of the problems arising from this is a problem in the ConvertType in the ShaderNode.js in the Nodes system - if it will always use set() method `new class().set( ...args )`, it would not always work with Color, and if it will always use constructor `new class( ...args )`, it will not work with Matrix classes.

**Describe the solution you'd like**

I suggest allowing Matrix constructor to take arguments and allowing Color set() method to take multiple arguments.

**Comment by LeviPesin** [comment]
Also, for some reason Matrix set() method stores values in different order - from this e.g. `new Matrix3().set( ...matrix.toArray() )` would not work.

Color for some reason is not iterable - i.e. `...color`, which works for vectors and matrices does not work.

**Comment by WestLangley** [comment]
>Also, for some reason Matrix set() method stores values in different order...

See https://github.com/mrdoob/three.js/issues/9281#issuecomment-230805870.

**Comment by LeviPesin** [comment]
But why then Matrix.fromArray and Matrix.toArray uses column-major order instead of the row one? It would make more sense to have one order everywhere (at least in the core).
