### ISSUE TITLE
Unstable shadows since r138 

### ISSUE THREAD

**Issue by vanruesc** [mrdoob/three.js#23649]
**Describe the bug**

While upgrading from r137 to r138 I noticed a strange issue where shadows would disappear and come back randomly depending on the view direction and/or camera position. Unfortunately, I wasn't able to reproduce the issue with a simple scene; the problem seems to only occur with complex scenes containing multiple different meshes and materials.

This appears to be a regression related to #23559 as reverting these changes restores the previous behaviour.

**To Reproduce**

1. Open the sandbox below.
2. Use the mouse to change the view direction. Optionally, use WASD to move around the scene.
3. See shadows pop in and disappear randomly.

***Live example***

Sandbox: https://codesandbox.io/s/musing-gagarin-i00twx?file=/src/App.js

The Sponza model comes from https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Sponza and is loaded from https://vanruesc.github.io/postprocessing/public/demo/models/sponza/ because it exceeds the size limit of CodeSandbox.

***Screenshots***

| r137 (correct)  | r138 (broken) |
|------|------|
| ![a](https://user-images.githubusercontent.com/9214917/156612633-48bc0ecb-4da2-4bb5-877a-4f7e09bf6bc6.jpg) | ![b](https://user-images.githubusercontent.com/9214917/156612650-d34a0219-e210-496b-9a09-d3495c76ca74.jpg) |

**Expected behavior**

Shadows should work as before.

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Firefox, Chrome
 - Three.js version: r138

**Comment by Mugen87** [comment]
I've also noticed a performance regression in `webgl_animation_skinning_blending` on my iMac. Reverting the PR solves this issue, too.

I suggest to undo #23559 first and then investigate what's going on.
