### ISSUE TITLE
WebGPUTextureRenderer: Get Depth buffer as TextureNode

### ISSUE THREAD

**Issue by geolehmann** [mrdoob/three.js#23655]
**Is your feature request related to a problem? Please describe.**

For advanced post-processing with a fullscreen quad like in the webgpu_rtt.html example, it is also necessary to have access to the depth buffer of the Rendertarget from the WebGPUTextureRenderer. If I did not miss anything, it is currently not possible to access the depth buffer.

**Describe the solution you'd like**

It would be great to have something for the WebGPUTextureRenderer like:

`let depthTextureNode = new Nodes.TextureNode( textureRenderer.getDepthTexture() );`

**Describe alternatives you've considered**

Similar as in the webgl_depth_texture.html example, I tried to get a `DepthTexture `from a RenderTarget, which didn´t work:

```
    //create a WebGPUTextureRenderer and set a DepthTexture
    textureRenderer = new WebGPUTextureRenderer(renderer);
    textureRenderer.setSize(window.innerWidth * window.devicePixelRatio, window.innerHeight * window.devicePixelRatio);

    let depthTexture = new THREE.DepthTexture();
    textureRenderer.renderTarget.texture.minFilter = THREE.NearestFilter;
    textureRenderer.renderTarget.texture.magFilter = THREE.NearestFilter;
    textureRenderer.renderTarget.stencilBuffer = false;
    textureRenderer.renderTarget.depthTexture = depthTexture;
    textureRenderer.renderTarget.depthTexture.format = THREE.DepthFormat;
    textureRenderer.renderTarget.depthTexture.type = THREE.UnsignedShortType;

    // set up FX
    cameraFX = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
    sceneFX = new THREE.Scene();
    const geometryFX = new THREE.PlaneGeometry(2, 2);
    const materialFX = new Nodes.MeshBasicNodeMaterial({
        side: THREE.DoubleSide
    });

    // this returns an error: "Multiple aspects selected in [TextureView] While validating [BindGroupDescriptor] against [BindGroupLayout]"
    materialFX.colorNode = new Nodes.OperatorNode( '*', new Nodes.TextureNode( textureRenderer.renderTarget.depthTexture ), new Nodes.ColorNode( new THREE.Color("green") ) );
    
    const quad = new THREE.Mesh(geometryFX, materialFX);
    sceneFX.add(quad);
```

**Additional context**

@sunag , maybe you could have a look at this? Many thanks in advance!

**Comment by LeviPesin** [comment]
`TextureNode` is actually a node for _sampling_ the texture. So you should write `new TextureNode( texture, someVec2WithCoordinates )`.

**Comment by LeviPesin** [comment]
Also you can write just `Nodes.texture( yourTexture, yourCoordinates )` because `texture` function is exported from the ShaderNode.

**Comment by LeviPesin** [comment]
But by default the TextureNode would use a UVNode so this should sitll work... Strange.

**Comment by geolehmann** [comment]
> But by default the TextureNode would use a UVNode so this should sitll work... Strange.
> 
> Could you please check if it was working before [4710868](https://github.com/mrdoob/three.js/commit/471086824aefd0eae370eefe5ef166f9d6dbd23d), e.g. at [8323901](https://github.com/mrdoob/three.js/commit/8323901ec2af183d9361d7c50c5d45e731792798)?

Thanks for your help. Yes, going back to an older commit does not fix the error. You are right about the UVNode, by default it should not be necessary to pass it to the TextureNode (actually, all the webgpu examples do not contain it). I´ll try to create a codepen to better demonstrate the issue.

**Comment by geolehmann** [comment]
Okay, you can see the error when you open this example in any browser with WebGPU support: 

[https://rawcdn.githack.com/geolehmann/three.js/8725732cc74cd63d609afc3d6a041f9b59d812ee/examples/webgpu_depth_texture.html](url)

**Comment by sunag** [comment]
> @sunag , maybe you could have a look at this? Many thanks in advance!

@geolehmann Maybe this example work for your need? https://github.com/mrdoob/three.js/pull/23665

**Comment by geolehmann** [comment]
Hi sunag, many thanks for your help. Although the example achieves the same visual effect as the webgl_depth_texture example, it does not resolve my issue. With the depth material from your example, I only get the fragment depth of the mesh the depth material belongs to, but not of the full screen. Basically, I want to access the fragment depth of the WebGPUTextureRenderer´s Rendertarget texture within a WGSL FunctionNode set as ColorNode for the fullscreen quad. This way I hope to set up a post-processing pipeline for the WebGPURenderer.

**Comment by sunag** [comment]
> Basically, I want to access the fragment depth of the WebGPUTextureRenderer´s Rendertarget texture within a WGSL FunctionNode set as ColorNode for the fullscreen quad. 

@geolehmann Would it be possible for you to use `ShaderNode` instead of `FunctionNode`

**Comment by geolehmann** [comment]
@sunag of course a `ShaderNode` would work for me as well, using WGSL and a `FunctionNode` was just some personal preference.

**Comment by sunag** [comment]
@geolehmann No problems, anyway it's important to have some examples using WGSL with textures.

**Comment by mrdoob** [comment]
@sunag Does #23665 resolve this?

**Comment by sunag** [comment]
>  ...using WGSL and a FunctionNode was just some personal preference.

We added support for `sampler` and `texture_2d` in `FunctionNode` [here](https://github.com/mrdoob/three.js/pull/23766).

**Comment by geolehmann** [comment]
Many thanks, I'll try it out today!
