### ISSUE TITLE
envMaps = refraction not working in r131 for PBR materials

### ISSUE THREAD

**Issue by lavond** [mrdoob/three.js#23668]
**Describe the bug**

Since release 131 it's not possible to change the mapping of the `envMap` to RefractionMapping for PBR materials. 
| r130 | r131 |
|--|--|
| ![r130](https://user-images.githubusercontent.com/29681218/157053572-ebc7c28e-9506-4b5d-9366-f6523069cd41.png) | ![r131](https://user-images.githubusercontent.com/29681218/157053583-f0721c33-4da5-4be5-9c65-63ab7c618e99.png) |

Probably it is related to the following adjustment:
> The envMap property of MeshStandardMaterial and MeshPhysicalMaterial is now internally converted to a PMREM. 

See also:
- Migration-Guide: https://github.com/mrdoob/three.js/wiki/Migration-Guide#130--131 
- PR: https://github.com/mrdoob/three.js/pull/22178

**To Reproduce**

1. Checkout tag r130 or r131 
2. Run _three.js/docs/scenes/material-browser.html#MeshStandardMaterial_
3. Change parameter (roughness: 0, metalness: 1, color: ffffff, envMaps: refraction 

(or run material-browser:  https://threejs.org/docs/scenes/material-browser.html#MeshStandardMaterial directly)

**Comment by Mugen87** [comment]
I did not add support for refraction mapping since I thought `CubeUVRefractionMapping` isn't wanted anymore, see #19611. It's physically more correct to model refraction via transmission properties.

**Comment by Mugen87** [comment]
If so, we should remove the refraction option from the material browser's drop down when a PBR material is selected.

**Comment by mrdoob** [comment]
Agreed. Although I would move the code to /examples.

I think it would be handy to have one example that shows a sphere refracting a cubemap so it's possible to do things like the floating panoramas in [hello webxr](https://mixedreality.mozilla.org/hello-webxr/).

**Comment by mrdoob** [comment]
Oh wait, I guess you mean removing it only from the PBR materials but still keep the code for the other materials?

**Comment by Mugen87** [comment]
> Oh wait, I guess you mean removing it only from the PBR materials but still keep the code for the other materials?

Yes, excatly 👍 . Just removing `CubeUVRefractionMapping`.

**Comment by lavond** [comment]
> I did not add support for refraction mapping in WebGLCubeUVMaps since I thought CubeUVRefractionMapping isn't wanted anymore, see https://github.com/mrdoob/three.js/issues/19611. It's physically more correct to model refraction via transmission properties.

This means that mapping type `refraction` has no longer an effect for PBR materials?  So the following visualization is only possible with non PBR materials (like `MeshPhongMaterial` / `MeshLambertMaterial`)? I have not achieved a comparable effect with PBR materials and `transmission` properties.

![refraction](https://user-images.githubusercontent.com/29681218/157241772-8d83694c-505b-4eeb-959c-6a44aaeba8bd.png)
see: https://threejs.org/examples/webgl_materials_envmaps.html

> If so, we should remove the refraction option from the material browser's drop down when a PBR material is selected. And also remove CubeUVRefractionMapping.

Sorry, I don't got it. Why is the adjustment only limited to the mapping type `CubeUVRefractionMapping`? As I understand it, all other mappings (`CubeRefractionMapping`, `EquirectangularRefractionMapping`) are also affected (for PBR materials) when `refraction` is no longer supported? (https://threejs.org/docs/#api/en/constants/Textures)

And is the parameter [`refractionRatio`](https://threejs.org/docs/#api/en/materials/MeshStandardMaterial.refractionRatio) for PBR materials still relevant?

**Comment by Mugen87** [comment]
> This means that mapping type refraction has no longer an effect for PBR materials?

When `CubeUVRefractionMapping` is removed, yes. The automatic PMREM conversion does already support only reflection.

>  I have not achieved a comparable effect with PBR materials and transmission properties.

The effect itself is physically not correct so it using transmission will look different.

> And is the parameter [refractionRatio](https://threejs.org/docs/#api/en/materials/MeshStandardMaterial.refractionRatio) for PBR materials still relevant?

When `CubeUVRefractionMapping` is removed, then no.

>  As I understand it, all other mappings (CubeRefractionMapping, EquirectangularRefractionMapping) are also affected (for PBR materials) when refraction is no longer supported?

PBR materials only supports the cubeUV format. Meaning `CubeRefractionMapping`, `CubeReflectionMapping` as well as `EquirectangularRefractionMapping` and `EquirectangularReflectionMapping` are no valid mappings.

**Comment by mrdoob** [comment]
@Mugen87 

> Yes, exactly 👍 . Just removing `CubeUVRefractionMapping`. Are you fine with that?

Yep!
