### ISSUE TITLE
`npm i --prefix test` fail - puppeteer

### ISSUE THREAD

**Issue by remmel** [mrdoob/three.js#23678]
**Describe the bug**

Cannot install the test packages. `npm i --prefix test` fail. Seems to be something related with puppeteer

**To Reproduce**

1. Checkout the dev branch
2. `npm install`
3. `npm i --prefix test`
4. 
```
$ npm install

removed 28 packages, and audited 590 packages in 2s

72 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ npm i --prefix test
npm ERR! code 1
npm ERR! path /home/remmel/workspace/three.js/test/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/remmel/.npm/_logs/2022-03-08T19_44_42_678Z-debug-0.log
```

Log : [2022-03-08T19_44_42_678Z-debug-0.log](https://github.com/mrdoob/three.js/files/8209180/2022-03-08T19_44_42_678Z-debug-0.log)

Extract
```
207 info run puppeteer@13.1.2 install node_modules/puppeteer node install.js
...
217 verbose stack Error: command failed
217 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
217 verbose stack     at ChildProcess.emit (node:events:520:28)
217 verbose stack     at maybeClose (node:internal/child_process:1092:16)
217 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Platform:**

 - OS: Ubuntu 20.04 LTS
 - Npm 8.3.0
 - Node v16.14.4
 - Three.js version: [dev]

**Comment by remmel** [comment]
this is only related with puppeteer as `npm i puppeteer --save-dev` fail

**Comment by mrdoob** [comment]
Did you try running `npm i` inside the `test/` folder?

**Comment by remmel** [comment]
Doing something like that works:
```
npm i --prefix test  --ignore-script
three.js/test/node_modules/puppeteer$ node install.js
```

same problem than that guy `So the problem is sh -c node install.js opens a node shell instead of downloading chromium`  https://discourse.processing.org/t/npm-ci-showing-error/27735/8

@mrdoob no, I ran npm instal in root / three.js

**Comment by remmel** [comment]
I'll close, the workaround is OK for me

**Comment by mrdoob** [comment]
I wish there was a way to detect if `test/node_modules` exist so we can tell the developer what to do.
