### ISSUE TITLE
Could not resolve "three/examples/jsm/exporters/GLTFExporter" while building three.js app

### ISSUE THREAD

**Issue by soadzoor** [mrdoob/three.js#23696]
**Describe the bug**

I upgraded my app from r137 to r138, and since then I have the following errors (a lot of similar ones):
<img width="754" alt="Screenshot 2022-03-10 at 15 43 24" src="https://user-images.githubusercontent.com/10392261/157640653-418fc931-2fa9-40e6-abc3-829931c1f879.png">

I checked the migration guide (137->138), but it seems it doesn't say anything about this. The strange thing, is that the files are still there, so I don't know why it says "it was not found". I'm using `esbuild` for bundling the js file, if that matters (but it worked flawlessly with r137, so I'm pretty sure something has changed with `three.js`, not `esbuild` ).

Does anyone has an idea what might be the problem?
Thanks

**Comment by soadzoor** [comment]
(might be related to this one? I don't know: https://github.com/mrdoob/three.js/issues/23625 )

**Comment by marcofugaro** [comment]
@soadzoor if you use esbuild, it requires you to import using the `.js` extension as the ESModule spec says:

```js
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'
```

**Comment by soadzoor** [comment]
@marcofugaro Hm, that seems to be working, thanks. But still not sure what changed. 🤔

**Comment by marcofugaro** [comment]
> But still not sure what changed. 🤔

three.js is now a proper ES Module 🙂 

https://github.com/mrdoob/three.js/blob/8e1b5099a09162cd9ae09316c0ec4c89997a45b2/package.json#L5
