### ISSUE TITLE
WebGLRenderer stop updating scene background when its image dimensions  change

### ISSUE THREAD

**Issue by stevexbritton** [mrdoob/three.js#23694]
**Describe the bug**

After release 135 the WebGLRenderer stops updating the scene.background if a DataTexture is used for the background image and its width and hight are swapped. It restarts updating if the width and hight are swapped back again. There is no change in the size of the texture.

**To Reproduce**

1. Go to 'https://codepen.io/stevexbritton/pen/xxPvqZp'.
2. The background colour will flicker, after 5 seconds it will stop and then after another 5 seconds it will restart.
3. If release 135 or earlier is used instead of 136 the colour does not stop changing.

***Code***

```js
// code goes here
```

***Live example***

* https://codepen.io/stevexbritton/pen/xxPvqZp

**Expected behavior**

I wouldn't expected the background colour to stop flashing  just because the width and height of the background image DataTexture are exchanged.

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [MacOS, Android, iOS]
 - Browser: [Chrome, Firefox, Safari]
 - Three.js version: [136 and above]

**Comment by Mugen87** [comment]
Sorry, but what you do is not valid anymore. As stated in the [docs](https://threejs.org/docs/index.html#api/en/textures/Texture), the dimensions, format, and type of a texture cannot be changed after its initial use.

Consider to use two different textures and swap them.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.
