### ISSUE TITLE
Why isn't Semantic Versioning used in this library?

### ISSUE THREAD

**Issue by hichemfantar** [mrdoob/three.js#23704]
**Is your feature request related to a problem? Please describe.**

How are devs supposed to know if an update will break existing code, do we have to read the patch notes of every update after the version currently being used to determine if something is gonna break or not?

**Describe the solution you'd like**

Please consider using semver. It saves a lot of headaches when maintaining project dependencies.

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/3333
https://github.com/mrdoob/three.js/issues/3375
https://github.com/mrdoob/three.js/issues/7726
https://github.com/mrdoob/three.js/issues/11396

**Comment by mrdoob** [comment]
> How are devs supposed to know if an update will break existing code, do we have to read the patch notes of every update after the version currently being used to determine if something is gonna break or not?

Yep!
