### ISSUE TITLE
Rendering of large bufferGeometries is broken in recent chrome releases

### ISSUE THREAD

**Issue by tahahajar** [mrdoob/three.js#23700]
**Describe the bug**

In recent chrome releases, meshes with relatively large bufferGeometries (>= 11k vertices) are distorted.
This is not always reproducible. However, I found out that after I run an example of a GPUComputationRenderer, the bug is 100% reproducible even if I close the GPUComputationRenderer example.

**To Reproduce**

Steps to reproduce the behavior, in Chrome 98 or 99:
1. Go to https://jsfiddle.net/5Lgurtc6/1/ it's supposed to show a red square.
2. Now open a GPUComputationRenderer example, for ex: https://threejs.org/examples/?q=prot#webgl_gpgpu_protoplanet
3. Go back to the red square fiddle https://jsfiddle.net/5Lgurtc6/1/ and re-run the code.
4. Now you see that the red square is not rendered correctly.

I couldn't reproduce the issue in Firefox or Chrome 91.

**Expected behavior**

Rendering of the bufferGeometry meshes shouldn't be distorted.

**Screenshots**
<img width="164" alt="Screenshot 2022-03-10 at 13 59 49" src="https://user-images.githubusercontent.com/12642281/157666991-948fee30-ae44-41bb-b265-daab6e71082a.png">
Expected
<img width="175" alt="Screenshot 2022-03-10 at 13 59 28" src="https://user-images.githubusercontent.com/12642281/157666997-49e8f0a2-112c-47c7-82cc-b92a5dee2847.png">
Output (after running a GPUComputationRenderer example)

**Platform:**

 - Device: [Macbook]
 - OS: [MacOS Monterey, MacOs Big sur]
 - Browser: [Chrome 98, Chrome 99]
 - Three.js version: [r128]
 - GPU: [AMD Radeon Pro 5300M]

**Comment by Mugen87** [comment]
I can't reproduce the issue with Chrome 99.0.4844.51 on macOS. The fiddle renders as expected without distortions.

**Comment by tahahajar** [comment]
> I can't reproduce the issue with Chrome 99.0.4844.51 on macOS. The fiddle renders as expected without distortions.
> 
> Consider to update macOS to the latest version since this will also update the GPU driver.

Thank you. I have been hunting this issue for a couple of weeks and tried updating the OS and the browser but nothing helped. It seems that the issue depends on multiple factors as I can't find a way to reproduce it all the time.

I noticed now that switching the chrome flag "Choose ANGLE graphics backend" to "Metal" - relaunch, then put it back to "OpenGL" - relaunch, then performing the steps above triggers the issue.

**Comment by LeviPesin** [comment]
Does the issue happen with a newer version than r86?

**Comment by Mugen87** [comment]
The fiddle uses `r128`.

**Comment by tahahajar** [comment]
My bad, indeed it's using r128.

**Comment by Mugen87** [comment]
Sorry, I don't think there is something we can do to solve this issue. If you can manage to reliably reproduce the issue, it's best to report it to the browser vendors. 

Please only file an issue here if you are sure it's a `three.js` issue.
