### ISSUE TITLE
Three.js import map not working

### ISSUE THREAD

**Issue by badde-media** [mrdoob/three.js#23702]
Firefox and some other browsers (details below) have problems resolving the importmap. Error:
```
Uncaught TypeError: Error resolving module specifier “three”. Relative module specifiers must start with “./”, “../” or “/”.
```
The line it refers to is

```
import { ... } from /*'three'*/'blob:https://[URL]/c945bbba-09f5-454f-b2a4-508d3d70f89a';
```
which is the Firefox translation of

```
import { ... } from 'three';
```
referring to the import map in the index.html file:

```
	<!-- Import maps polyfill -->
	<!-- Remove this when import maps will be widely supported -->
	<script async src="https://unpkg.com/es-module-shims@1.3.6/dist/es-module-shims.js"></script>

	<script type="importmap">
		{
			"imports": {
				"three": "./vendor/three/build/three.module.js"
			}
		}
	</script>
```
This code works perfectly fine in Chrome Canary.

I have tested the [online version](https://badde.media/threejs/fungi/index.html) in Chrome, Chrome Canary, Chrome Mobile Android, Opera, Opera Mobile Android, Edge, and it worked. I’ve tested it in Firefox, Firefox Mobile Android, Chrome Mobile iOS, Safari Mobile, and it didn’t work - although other projects of mine did, like [this one](https://badde.media/threejs/shapes/index.html)

**To Reproduce**
Try [this link](https://badde.media/threejs/fungi/index.html) in Firefox, Firefox Mobile Android, Chrome Mobile iOS or Safari Mobile.

1. Go to [this link](https://badde.media/threejs/fungi/index.html) 
2. Page should load
3. but doesn't. Or maybe partially, with errors like the black background staying black instead of becoming colored .

***Code***

```html
	<!-- Import maps polyfill -->
	<!-- Remove this when import maps will be widely supported -->
	<!-- <script async src="https://unpkg.com/es-module-shims@1.3.6/dist/es-module-shims.js"></script> -->

	<script type="importmap">
		{
			"imports": {
				"three": "./vendor/three/build/three.module.js"
			}
		}
	</script>
```
```js
import { Vector3, Object3D, Mesh, TextureLoader } from 'three';
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hyok6tvj/)
* [jsfiddle-dev](https://jsfiddle.net/c5m1kazu/)
* THESE ^ two examples actually show the same error.

**Expected behavior**
When the site has loaded, hundred small colored spheres should spread out from the center inside of a black sphere where the camera also is located in. When one of these small spheres hit the big one, the small ones should disappear, the bigsphere should take the color of the hitting sphere (console.logged), and an inner sphere with wireframe shader should appear with the inverted color. In the middle, a patch of grass should occur where a mushroom grows out (mushroom /growing are WIP).

**Screenshots**
![Screenshot_20220310-103929_Opera](https://user-images.githubusercontent.com/19553316/157726950-4b1aa463-a5ad-4fe1-be40-19ba16a36838.jpg)
This screenshot shows the expected behaviour.

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge] Please see above for further information.
 - Three.js version: REVISION = '137' stable build
 
 TB, I don't even think that it's a three.js bug, but probably one in the es-module-shims.js module.

**Comment by mrdoob** [comment]
> TB, I don't even think that it's a three.js bug, but probably one in the es-module-shims.js module.

Please, report the bug here instead: https://github.com/guybedford/es-module-shims

**Comment by badde-media** [comment]
Just in case anyone wants to follow up or contribute:
https://github.com/guybedford/es-module-shims/issues/270
