### ISSUE TITLE
 THREE.Face3 is not a constructor 

### ISSUE THREAD

**Issue by xiaochao00** [mrdoob/three.js#23710]
**Describe the bug**

Failed when use Face3

**To Reproduce**

just run in browser

***Code***

```js
// code goes here
var normal = new THREE.Vector3(0, 0, 1); 
var face0 = new THREE.Face3(0, 1, 2, normal); 
var face1 = new THREE.Face3(0, 2, 3, normal); 

```

***Live example***

**Expected behavior**

How to use Face3?

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Edge]
 - Three.js version: [dev, r138]

**Comment by Mugen87** [comment]
`Face3` is no part of the core anymore. However, you can import the class from the deprecated `Geometry` module.

https://github.com/mrdoob/three.js/blob/4082a1477f2c4dd1f3c6be8bb3eb2a3a288c6a9e/examples/jsm/deprecated/Geometry.js#L1816-L1867

Please use the [forum](https://discourse.threejs.org/) if you need more help.
