### ISSUE TITLE
Nodes: Without using VarNode sometimes node is generated twice

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#23728]
**Describe the bug**

Without using VarNode sometimes a node is generated twice. Here is an example: https://jsfiddle.net/5rxbck2n/ - `dot( nodeVar2, nodeVar3 )` (corresponding to the `denominator` in JS) occurs twice there. If you comment line 22 and uncomment line 21 (https://jsfiddle.net/5rxbck2n/1/), it will be generated only once (but then there will be created an unneccesary variable `nodeVar5 = nodeVar4`, see https://github.com/mrdoob/three.js/issues/23537).

***Live example***

* [jsfiddle-dev](https://jsfiddle.net/5rxbck2n/)

**Comment by sunag** [comment]
Fixed here https://github.com/mrdoob/three.js/pull/23828

**Comment by LeviPesin** [comment]
Confirmed that it is fixed.
