### ISSUE TITLE
Mirror Example broken on iOS 15.4

### ISSUE THREAD

**Issue by bunnybones1** [mrdoob/three.js#23733]
**Describe the bug**

The mirror example does not render correctly on Safari in iOS 15.4 when "WebGL via Metal" is enabled (default).

We're letting WebKit devs know as well. Thought it would be useful for them and you to see if changes to the way that WebGL calls are executed can help smooth over this regression.

https://bugs.webkit.org/show_bug.cgi?id=237906

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to https://threejs.org/examples/webgl_mirror.html
2. Rotate the view to see an odd piece of geometry stuck to the screen

**Screenshots**

![IMG_0357E3C0C353-1](https://user-images.githubusercontent.com/453513/158638012-2c968195-b52a-4c11-a68c-681b4139b5ea.jpeg)

**Platform:**

 - Device: iPhone Xs 
 - OS: iOS 15.4
 - Browser: Safari
 - Three.js version: r138

**Comment by deltakosh** [comment]
Welcome onboard, it seems to be a wide spread issue.

**Comment by bunnybones1** [comment]
> 

Hey,
Yeah, it's a wild day. Some instances of the bug can be worked around by disabling "WebGL via Metal", but in our project, Skyweaver, we do some more complicated offscreen renders between frames that aren't fix by doing this.

**Comment by Mugen87** [comment]
Should be fixed with the recently published iOS 15.5.
