### ISSUE TITLE
Matrix4::lookAt() does not do what its name suggests

### ISSUE THREAD

**Issue by felixniemeyer** [mrdoob/three.js#23736]
I am using three js vector & matrix math. I got stuck for 2 hours because Matrix4::lookAt() is not doing what a function with this name usually does in CG (correct me if I'm wrong). 

Expected: 
As far as I know, lookAt() creates a Matrix that does rotation and translation in a way, as if looking from the eye coordinate towards the target coordinate keeping the up vector pointing upwards. 

What happened: 
This method creates only a rotation matrix. No translation is happening here. 

Proposed solution: 
Rename this method to "lookAtRotation" or so to prevent confusion. 

https://github.com/mrdoob/three.js/blob/c7d06c02e302ab9c20fe8b33eade4b61c6712654/src/math/Matrix4.js#L293

**Comment by mrdoob** [comment]
Please, use the [forum](https://discourse.threejs.org/) for this kind of conversations.

**Comment by felixniemeyer** [comment]
I don't need help, I'm using gl-matrix package now, whose loopAt function does what its name promises:
https://github.com/toji/gl-matrix
Maybe three.js' math classes are rather meant for internal use than for direct use for doing CG matrix and vector stuff.  
Thanks

**Comment by zingxy** [comment]
> I don't need help, I'm using gl-matrix package now, whose loopAt function does what its name promises: https://github.com/toji/gl-matrix Maybe three.js' math classes are rather meant for internal use than for direct use for doing CG matrix and vector stuff. Thanks

Hi man, I also encounter the same issue. Matrix4.lookAt looks like do not compute `translation`. Very confused.

**Comment by mrdoob** [comment]
Why would the translation need to be changed?

**Comment by mrdoob** [comment]
But... why would the camera change position (translation) when looking into another direction?
