### ISSUE TITLE
Types broken for lil-gui

### ISSUE THREAD

**Issue by FractalHQ** [mrdoob/three.js#23738]
It seems types aren't configured properly for `lil-gui`.  Sorry if this is user error- but my google-fu hasn't turned up much advice.

**Describe the bug**

The typescript types for `lil-gui` are not found when importing `{ GUI } from 'three/examples/jsm/libs/lil-gui.module.min.js'`

**To Reproduce**

1. Install `three` and `@types/three`.
2. Import GUI: `import { GUI } from 'three/examples/jsm/libs/lil-gui.module.min.js'`
3. See error:

![Screenshot 2022-03-16 at 7 14 29 PM](https://user-images.githubusercontent.com/55504972/158707603-58626bd2-35af-4f0c-9a54-95fa43157292.png)

> Could not find a declaration file for module 'three/examples/jsm/libs/lil-gui.module.min.js'. '/Users/fractal/dev/Projects/three-webgpu/node_modules/.pnpm/three@0.138.3/node_modules/three/examples/jsm/libs/lil-gui.module.min.js' implicitly has an 'any' type.
If the 'three' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/three'js(7016)

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Three.js version: [latest]

**Comment by mrdoob** [comment]
https://github.com/georgealways/lil-gui
