### ISSUE TITLE
It it possible to remove defineProperty and defineProperties in  Object3D constructor?

### ISSUE THREAD

**Issue by 823639792** [mrdoob/three.js#23745]
It is possible to remove defineProperty and defineProperties in  Object3D constructor?
It's so slow. I have about over 10000 Objects, and the total defineProperty  and defineProperties  time is over 400ms.
![image](https://user-images.githubusercontent.com/12330766/158973893-29b9bbaa-6be1-40e7-a7d3-8274da212603.png)

**Comment by Mugen87** [comment]
No, sorry. We have made the experience that it is important to prevent this pattern:
```js
const object = new THREE.Object3D();
object.position = new THREE.Vector3();
```
`Object.defineProperties()` is an effective way to ensure certain properties are not overwritten with custom objects.

https://jsfiddle.net/tbw4zde3/1/

**Comment by 823639792** [comment]
If my code can guarantee that the properties in it will not be overwritten, can I remove it myself?
I did a test and it looks like nothing is wrong

**Comment by 823639792** [comment]
Will there be other effects?

**Comment by Mugen87** [comment]
AFAIK, no.
