### ISSUE TITLE
ThreeJS module imports give MIME type error

### ISSUE THREAD

**Issue by malith1992** [mrdoob/three.js#23759]
I'm developing a web application using flask and files being served using local flask server

I'm trying to import ThreeJS modules inside my javascript file as follows

```
import * as THREE from '../static/javascript/three.js-dev/build/three.module.js';
import { OrbitControls } from '../static/javascript/three.js-dev/examples/jsm/controls/OrbitControls.js';
import { IFCLoader } from '../static/javascript/three.js-dev/examples/jsm/loaders/IFCLoader.js';
```
I inisialise the js file inside HTML code as fillows.

`<script type="module" src="{{ url_for('static',filename='javascript/index1.js') }}"></script>`

I'm getting the following error

> **Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec**.

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome, Edge]
 - Three.js version: [r138]

**Comment by LeviPesin** [comment]
https://stackoverflow.com/questions/59355194/python-flask-error-failed-to-load-module-script-strict-mime-type-checking-i

**Comment by malith1992** [comment]
Thank you !
