### ISSUE TITLE
skypack build fails for 0.138.3

### ISSUE THREAD

**Issue by Taiwing** [mrdoob/three.js#23757]
**Describe the bug**

I was working on a threejs project a few months back and using skypack to import it as described [here](https://discoverthreejs.com/book/introduction/get-threejs/#use-a-cdn). The build now fails with the latest threejs version.

**To Reproduce**

Go to [https://cdn.skypack.dev/three](https://cdn.skypack.dev/three) or [https://cdn.skypack.dev/three@0.138.3](https://cdn.skypack.dev/three@0.138.3) and see the error message.
If you check [https://cdn.skypack.dev/three@0.138.2](https://cdn.skypack.dev/three@0.138.2), it works as expected.

**Comment by Mugen87** [comment]
Shouldn't this issue be reported to Skypack instead?

**Comment by Taiwing** [comment]
I just checked, and it actually was reported to skypack: [https://github.com/skypackjs/skypack-cdn/issues/275](https://github.com/skypackjs/skypack-cdn/issues/275)

Every other version of threejs works fine with skypack so I though the issue was specific to this one and should therefore be fixed here. Especially since support for skypack seems to be a given in the community resources. However, I honestly don't know enough about threejs or skypack to say where the problem lies and who should fix it.

**Comment by Mugen87** [comment]
AFAICT, we did not something different when publishing `0.138.3`.

**Comment by marcofugaro** [comment]
This is an issue with skypack-cdn.
