### ISSUE TITLE
Interactive examples of website not working correctly in firefox

### ISSUE THREAD

**Issue by Kandreas9** [mrdoob/three.js#23760]
The interactive examples in the website articles either have errors or do not work. I have tested it on chrome and it seems to be only firefox. I am on a macbook but i doubt this has anything to do with it.

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**To Reproduce**

1. Go to 'https://threejs.org/manual/#en/responsive'
2. Scroll down to the interactive examples with the cubes
3. See red error text at the bottom of the window.

**Expected behavior**

Not seeing error and it working

**Screenshots**

![Screenshot 2022-03-22 at 07 13 31](https://user-images.githubusercontent.com/52108266/159412520-e8a1e06c-c535-4fce-aa22-0a63be8fbb5d.png)
![Screenshot 2022-03-22 at 07 13 48](https://user-images.githubusercontent.com/52108266/159412542-598989bd-bc1a-437a-82f4-a0baf591bc3f.png)

**Platform:**

 - Device: Desktop
 - OS: MacOS M1, MacOS Intel Chip
 - Browser: Firefox

**Comment by LeviPesin** [comment]
This error is normal for the browsers that do not support import maps.
The import maps polyfill allows them to work, but does not remove the error.

**Comment by Kandreas9** [comment]
in the second screenshot tho you can see it doesnt work at all, the same thing goes for safari, that part doesnt show at all
