### ISSUE TITLE
GLTFLoader: Blend Shapes are incorrect when only positions are present

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#23764]
**Describe the bug**

Seems that when only positional data is present, morph targets/blend shapes are incorrect.

**To Reproduce**

1. Download [blendshape-bugs.zip](https://github.com/mrdoob/three.js/files/8325401/blendshape-bugs.zip)
2. Go to https://gltf-viewer.donmccurdy.com/ (also broken in model-viewer, three.js editor)
3. Drop unpacked GLB file into viewer
4. Adjust blend weights to see that three.js produces a garbage/noise result
5. Drop the same file into https://sandbox.babylonjs.com/
6. Select the root node
7. Adjust blend weights to see that here it works as expected

**Expected behavior**

_Correctly displays blended shape._
![image](https://user-images.githubusercontent.com/2693840/159512144-829dff82-64bc-4f36-841b-5e1b29f54133.png)

**Actual behaviour**

_Cool looking but incorrect result:_
![image](https://user-images.githubusercontent.com/2693840/159512084-9173739d-da32-495a-91f0-20fde6154e54.png)

**Platforms where this is broken**
- [x] Windows
   - broken in Chrome 99, Firefox 98, Edge 99
   - broken with at least Nvidia RTX 2070 Max-Q and RTX 3060 Ti
- [ ] Android
- [ ] iOS

**Additional Info**

The file doesn't pass glTF validation, Nomad bug report here: https://forum.nomadsculpt.com/t/exported-gltf-is-sometimes-invalid-doesnt-pass-gltf-validation/6287. The corrected file (https://github.com/mrdoob/three.js/files/8325531/blendshape-bugs-v1.glb.zip) exhibits the same problem.

**Comment by donmccurdy** [comment]
I'm seeing correct results on my device (macOS + Chrome), could you share more details about the device and browsers where this appears broken?

And just to check – does this version of the same model look any better for you? The original had a bunch of glTF validation issues, I fixed those in https://gltf.report/. It works correctly before and after on my device.

[blendshape-bugs-v1.glb.zip](https://github.com/mrdoob/three.js/files/8325531/blendshape-bugs-v1.glb.zip)

**Comment by hybridherbst** [comment]
Sorry, should have mentioned, I had also tested with a validation-passing file (I think it's just rounding errors, the file falls like this out of Nomad Sculpt, I'll report a bug there as well).

Your file also fails. I tested on Windows / Chrome on a number of different devices; 
can confirm that the file looks correct on iOS and also on Android, I updated the description.

I suspect the blendshape texture...

**Comment by donmccurdy** [comment]
Thanks - Which browser on Windows? And do you know what GPU is on the device?

**Comment by Mugen87** [comment]
Can you please test `dev`? I've added a PR last week that fixed a similar issue on my Windows laptop, see #23727.

**Comment by hybridherbst** [comment]
Thanks – yes, seems to be solved on dev.
![image](https://user-images.githubusercontent.com/2693840/159542898-08063d05-147d-4872-8af5-acf40ce7b33f.png)

Closing as duplicate
