### ISSUE TITLE
proposal: BufferAttribute.copyVector( )

### ISSUE THREAD

**Issue by gsimone** [mrdoob/three.js#23761]
I was doing some computation on a buffer attribute where I needed to fetch each normal to create a new attribute, so I was looking for a way to copy the values of the attr to a vector, but I see we only have single fetches `getX`, `getY`, `getZ`.

What about adding a `copyVector` method to BufferAttribute that would do the work?

```js
const myVector = new Vector3()
for (let i = 0; etc etc) {
	bufferAttribute // itemSize 3
		.copyVector(index, myVector)
}
```

This could be implemented as

```js
copyVector( index, vector ) {
   const x = this.getX( index )
   const y = this.getY( index ) 

   // either check the vector or check the buffer's itemSize
   if ( vector.isVector3 ) {
     vector.z = this.getZ( index )
  }

  if ( vector.isVector4 ) {
    vector.w = this.getW( index );
  }
}
```

Of course this is trivially done in userland, but it's such a small snippet that it could be nice to have. I did a quick search and we also use this pattern in some examples and lib code: https://github.com/mrdoob/three.js/search?q=.getX (not all of these results apply )

**Comment by Mugen87** [comment]
Why are you not using `fromBufferAttribute()`?
```js
myVector.fromBufferAttribute( bufferAttribute, index );
```
That is the intended way of extracting data into vectors.

**Comment by donmccurdy** [comment]
I'd guess it's pretty natural for users to check the [BufferAttribute API documentation](https://threejs.org/docs/?q=Bufferattr#api/en/core/BufferAttribute) when looking for ways to get data out of a BufferAttribute, rather than the VectorN docs. Maybe we'd want a `getVector` method as well? Or even just a short example at the top of the BufferAttribute page that uses `vector.fromBufferAttribute`.

**Comment by gsimone** [comment]
@Mugen87 didn't occur to me to look at vector's API. I agree with @donmccurdy that we should either add an example or have an explict api method on BufferAttribute that would be even simpler implementation, now that I know this exists:

```js
// BufferAttribute class 
copyVector( vector, index ) {
   vector.fromBufferAttribute( this, index )
}
```

Adding an example is also a good idea, regardless of adding this API or not, as this is a common enough use case.

Further question, should we look for more places where getX/Y/Z could be replaced with this in examples/docs/libraries?

**Comment by Mugen87** [comment]
I would prefer to add a note and not enhance the API.

When I've understood @mrdoob correctly, the new [manual](https://threejs.org/manual/) would be the better place for this detail. The docs should eventually represent a pure API specification.

**Comment by LeviPesin** [comment]
> Further question, should we look for more places where getX/Y/Z could be replaced with this in examples/docs/libraries?

Will file a PR for this tomorrow.

**Comment by donmccurdy** [comment]
@Mugen87 perhaps a sentence like https://github.com/mrdoob/three.js/pull/23772 would not be too intrusive?

**Comment by gsimone** [comment]
Thanks @donmccurdy, good change!
