### ISSUE TITLE
Three. Js could not load FBX model

### ISSUE THREAD

**Issue by nanteqiao** [mrdoob/three.js#23785]
The browser threw an exception when I tried to load the FBX model with the following code

`var loader = new FBXLoader();
				loader.load(`/download?mode=dance_fbx`, function ( object ) {
					mixer = new THREE.AnimationMixer( object );             
					var action = mixer.clipAction( object.animations[ 0 ] );
					action.play();
					object.traverse( function ( child ) {
						if ( child.isMesh ) {
							child.castShadow = true;
							child.receiveShadow = true;
						}
					} );
					scene.add( object );
				});`

The browser reports a warning "FBXLoader.js:2584 THREE.FBXLoader: Encountered an animation stack with multiple layers, this is currently not supported. Ignoring subsequent layers."
Is this the reason why the model cannot be loaded? How to solve this problem

**Comment by Mugen87** [comment]
Can you try to convert the model to glTF instead? One option is to import the FBX asset in Blender and then export to glTF. 

Besides, please always fill out the issue template and don't just delete it.

It would be also good to share the FBX asset in this thread.

**Comment by nanteqiao** [comment]
> Can you try to convert the model to glTF instead? One option is to import the FBX asset in Blender and then export to glTF.
> 
> Besides, please always fill out the issue template and don't just delete it.
> 
> It would be also good to share the FBX asset in this thread.

Sorry, we only have fbx files stored on the server

**Comment by Mugen87** [comment]
> The browser threw an exception

Looking at the code of `FBXLoader`, the mentioned log is no an exception. It's just a warning. There might be another reason why the model can't be loaded. 

In any event, I doubt animation stacks with multiple layers will ever be supported.

> Sorry, we only have fbx files stored on the server

Well, it should not be too hard to save on of the loaded models as a file. With your current provided information, it is not possible to investigate the issue.

**Comment by Mugen87** [comment]
Closing due to lack of feedback.
