### ISSUE TITLE
DataTexture should have needsUpdate = true when constructed with existing data

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#23783]
As shown in[ the documentation](https://threejs.org/docs/#api/en/textures/DataTexture), when using DataTexture one needs to use `needsUpdate = true` explicitly.

This is kind of unexpected, see e.g. comment in https://codepen.io/alexpyzhianov/pen/vNjJWd:

```
dataTex.needsUpdate = true; // somehow this line is required for this demo to work. I have not figured that out yet.
```

Is there any reason why a new `DataTexure` does not have `needsUpdate = true` automatically on construction? Other texture types do not seem to need this.

**Comment by WestLangley** [comment]
See #22947 for the explanation.
