### ISSUE TITLE
135+ washed out sRGB VideoTexture when used as scene's background

### ISSUE THREAD

**Issue by nyan-left** [mrdoob/three.js#23780]
Using a `THREE.VideoTexture` as a scene's `background` alongside `sRGBEncoding` results in a washed-out image. This is also the case when using a device's camera stream. The texture does, however, render as expected on a plane in the scene.

It looks like this is related to the recent `SRGB8_ALPHA8` PR  https://github.com/mrdoob/three.js/pull/22952

**To Reproduce**
1. Install the latest `THREE` version (0.138.3 as of this post)
2. Setup a `VideoTexture` to be used as a scene's background
3. Set the texture's encoding to `sRGBEncoding`
4. Set the renderer's output encoding to `sRGBEncoding`
5. Observe that the video loses quality and becomes washed out.

***Code***

<details>
  <summary>Click to expand</summary>
  
  ```typescript
import * as THREE from "three";

const renderer = new THREE.WebGLRenderer();
document.body.appendChild(renderer.domElement);

renderer.setSize(window.innerWidth, window.innerHeight);

window.addEventListener("resize", () => {
  renderer.setSize(window.innerWidth, window.innerHeight);
});

const camera = new THREE.PerspectiveCamera(
  75,
  window.innerWidth / window.innerHeight,
  0.1,
  1000
);

const scene = new THREE.Scene();
const video = document.querySelector("video");
video.muted = true;
video.play();

const texture = new THREE.VideoTexture(video);
texture.encoding = THREE.sRGBEncoding;
renderer.outputEncoding = THREE.sRGBEncoding;

scene.background = texture;

const plane = new THREE.Mesh(
  new THREE.PlaneGeometry(2, 2),
  new THREE.MeshBasicMaterial({ map: texture })
);
scene.add(plane);
plane.position.set(1.5, 0, -3);

function render() {
  requestAnimationFrame(render);

  renderer.render(scene, camera);
}

requestAnimationFrame(render);

  ```
</details>

***Live example***

* 0.138.3 https://codesandbox.io/s/twilight-snow-vi7dkl?file=/src/index.js
* 0.135.0 https://codesandbox.io/s/brave-hofstadter-uk4ji3?file=/src/index.js

**Expected behavior**

The video quality should not be reduced and the colors should remain unchanged.

**Screenshots**

<details>
  <summary>0.138.3 Click to expand</summary>

![image](https://user-images.githubusercontent.com/5834889/159904076-715274a4-8841-4a1d-85bb-707ea7560bb3.png)
![image](https://user-images.githubusercontent.com/5834889/159904238-89d3468c-0b64-47ee-895b-37f1d6e5c0a4.png)

</details>

<details>
  <summary>0.135.0 Click to expand</summary>

![image](https://user-images.githubusercontent.com/5834889/159904601-825cf5d6-db80-4057-bd3d-c6a93ba24c85.png)
![image](https://user-images.githubusercontent.com/5834889/159904551-d51fc622-8b16-4135-82c6-81d77c9197e3.png)

</details>

**Platform:**

Tested on:

 - Device: Desktop, Mobile
 - OS: Windows, MacOS
 - Browser: Chrome, Safari
 - Three.js version: [0.138.3, 0.135.0]

**Comment by Mugen87** [comment]
It seems I've missed to add the inline sRGB decode to the `background` shader.

https://github.com/mrdoob/three.js/pull/23129/commits/57ac4776ac7328f7fd239c5b24b61a96171e8419
