### ISSUE TITLE
RFC: Making Euler, Color, Quaternions iterable - and consequently spreadable - like Vector*

### ISSUE THREAD

**Issue by gsimone** [mrdoob/three.js#23793]
Vectors are iterable, so they can be spread to an array like `[...vector]`. The same isn't true for Euler, and users ** cough cough me right now ** might expect consistent behaviour.

I was surprised to see this missing, so I'm wondering wether there is a reason we wouldn't make them behave in the same way. 
I know order might be one reason, but then again users could order before spreading.

The code itself would just be the few lines to add the feature and a test, shouldn't take a long time, I'm more interested in why this could be a bad idea.

Have a great weekend and hugs all around!

EDIT: 
- Quaternion
- Color

Are also candidates for this

**Comment by LeviPesin** [comment]
`Color` is also missing an iterator.

**Comment by gsimone** [comment]
@LeviPesin also Quaternion. Let me report all of those in the initial comment, it's a good idea

**Comment by LeviPesin** [comment]
Matrix3/4 also is not iterable, but there is not obvious which order of elements should be returned.

**Comment by Mugen87** [comment]
I don't think matrix classes should be iterable.

**Comment by WestLangley** [comment]
>I don't think matrix classes should be iterable.

Can you explain why you feel that way?

**Comment by gsimone** [comment]
@Mugen87 the matrix classes already do assume column-major when converting to array ( with the `toArray` method ), so I think this wouldn't be that different.

If a user needs them in row-major they'll transpose themselves - I found myself in that position in the past. We'd be assuming the same level of knowledge for both methods

**Comment by Mugen87** [comment]
> Can you explain why you feel that way?

I'm in general no fan of using matrices in user related workflows. I don't think the engine should guide users towards matrices but to the transformation properties of `Object3D`(position, rotation/quaternion, scale).

**Comment by LeviPesin** [comment]
But there any many applications of matrices in users' three.js-related code that are not related to the transformation properties of Object3D...

**Comment by Mugen87** [comment]
That's true but even then I don't understand why someone wants to iterate of the elements of a matrix.
