### ISSUE TITLE
BufferGeometryUtils.computeTangents( geometry ) fails with non-indexed geometry

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#23795]
The error occurs here:
```js
return geometry.copy( _geometry );
```
when `geometry === _geometry`.

The proper solution depends on how you intend the method to be used:
```js
geometry = BufferGeometryUtils.computeTangents( geometry ); // return a new geometry
```
vs.
```js
BufferGeometryUtils.computeTangents( geometry ); // modify the existing geometry
```
/ping @donmccurdy 

 - Three.js version: [r139]

**Comment by donmccurdy** [comment]
Ah thanks for the issue report. It looks like there's another issue (https://github.com/mrdoob/three.js/pull/23716#issuecomment-1079740180) to be fixed as well...
