### ISSUE TITLE
Build error with 0.139.0

### ISSUE THREAD

**Issue by NDKhoi11** [mrdoob/three.js#23807]
**Describe the bug**

I use the globe.gl library and it dependent threejs. But I got an error from this file: three\examples\jsm\libs\mikktspace.module.js in line 121. I try to remove `await` then there're not error occur.

**Expected behavior**

Please help me fix me. Thank you !

**Screenshots**

![image](https://user-images.githubusercontent.com/66565185/160594686-eb8463f2-a5e3-4ce2-b30a-8b9f16be966e.png)

**Comment by geolehmann** [comment]
see #23802
