### ISSUE TITLE
scene.background = Texture only renders with camera on layer 0

### ISSUE THREAD

**Issue by isjackwild** [mrdoob/three.js#23809]
**Describe the bug**

Then using a texture as the `scene.background` property, it will only render with a camera with layer 0 enabled.

**To Reproduce**

1. Create a scene
2. Set background to a texture loaded with the Texture Loader
3. Disable camera layer 0
4. Enable camera layer 1
5. Render scene

***Code***

```js
const scene = new Scene();
const camera = new PerspectiveCamera();

camera.layers.disable(0);
camera.layers.enable(1);

scene.background = await new TextureLoader().loadAsync('my-background.png');

renderer.render(scene, camera);
```

**Expected behavior**

Background texture should render as it does if the camera has layer 0 enabled.

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [r138]

**Comment by Mugen87** [comment]
Since a colored background works with all layers, it's fair to expect that this is also true for any kind of textured background.
