### ISSUE TITLE
Reconsider removal of inline sRGB decode

### ISSUE THREAD

**Issue by tangobravo** [mrdoob/three.js#23803]
Decided to start a new issue rather than adding comments on the closed ones, hope that's OK.

I'd like to request a reconsideration of the inline sRGB decode removal from #23129.

The WebGL1 fallback involves forcibly disabling mipmaps if EXT_sRGB is supported, or a costly CPU-side conversion if not - both of these are significant regressions in WebGL1 functionality.

As discussed over on #22689, it seems like WebGL1 support is still accepted as a current necessity. iOS is the main reason why this is still an important consideration - roughly [20% of iOS users](https://mixpanel.com/trends/#report/ios_15/from_date:-29,report_unit:day,to_date:0) are still not yet on iOS 15 when WebGL2 was first enabled by default (prior to that the implementation was so buggy to be pointless enabling anyway).

iOS 15 uses ANGLE for its WebGL2 implementation, but with the Metal backend which is pretty new - it is usable and works correctly for a fair amount of content, but there are known bugs and regressions even in the latest iOS 15.4. Therefore sticking with WebGL1, even on the latest iOS, is one practical way to avoid the worst implementation bugs whilst Apple's WebGL2 implementation settles down and becomes more reliable.

I understand that doing sRGB decode in the shader leads to incorrect interpolation, and without using the correct sRGB internal formats, mipmap filtering will be incorrect. I think the change in #23129 will lead to worse practical effects for WebGL1 content, especially the CPU-side conversion.

Here are some example values:

| 8-bit sRGB value | [0,1] linear value | 8-bit linear (floating point) | 8-bit linear (rounded) | Linear -> 8-bit sRGB |
| --- | --- | --- | --- | --- |
| 7 | 0.002125 | 0.54 | 1 | 13 |
| 12 | 0.003677 | 0.94 | 1 | 13 |
| 17 | 0.005605 | 1.43 | 1 | 13 |

Essentially any pixel with an sRGB value in the range [7, 17] will end up as 1 in the CPU-converted texture, and be rounded to 13 when the shader encodes as sRGB for output (NB: I've assumed rounding here, whereas it looks like the CPU conversion uses Math.floor - the logic still stands but exact numbers may vary).

In my view this is likely to cause much more severe artefacts than the mathematically incorrect interpolation.

A sampler half-way between two pixels with sRGB values `(7/255)` and `(17/255)` should be computed in the sampler after the conversion of each sample to linear space - ie it should be `0.002125 * 0.5 + 0.005605 * 0.5 = 0.003865`. "Incorrect" linear blending would compute it as `(7 * 0.5 + 17 * 0.5) / 255`, ie `(12/255)` and then do sRGB conversion on that result, giving 0.003677. It's not quite right but it's not *that* bad.

The problem is the linear values are just an intermediate stage (need to be encoded back to sRGB for output anyway) and 8-bits is just not enough precision for storing them. In the shader as long as the precision isn't `lowp` you'd be guaranteed more precision for those intermediate results.

The overall question is what to do about sRGB stuff in WebGL1 contexts. One option is just to not support them - Unity only allows you to use "linear" lighting if WebGL1 is disabled, but that means both webgl1 and webgl2 contexts end up running in "gamma" mode with the mathematically-incorrect lighting calculations.

I think three.js's previous behaviour of emulating in the shader post-sampling was reasonable, which gives mathematically-correct behaviour in WebGL2, plus a visually consistent fallback in WebGL1. What's more as the intermediate values use sufficient precision, it wouldn't introduce banding artefacts for a simple "passthrough" unlit shader, unlike the current CPU fallback.

WebGL1 + EXT_sRGB looks like a reasonable "correct on WebGL1" approach, but the lack of mipmapping is annoying. sRGB-correct mips could be computed on the CPU side but there'd be a performance cost. Perhaps the best balance is to only use EXT_sRGB in the case mipmaps are explicitly disabled, rather than forcing that choice on users.

**Comment by mrdoob** [comment]
> Perhaps the best balance is to only use EXT_sRGB in the case mipmaps are explicitly disabled, rather than forcing that choice on users.

That seems like something we could do. Would that be a good enough solution for you?

**Comment by tangobravo** [comment]
> > Perhaps the best balance is to only use EXT_sRGB in the case mipmaps are explicitly disabled, rather than forcing that choice on users.
> 
> That seems like something we could do. Would that be a good enough solution for you?

I was meaning having that In combination with inline sRGB decode for use-cases that need generateMipmaps() or devices without EXT_sRGB support. IMHO the current fallback in those cases loses too much information due to 8-bit precision issues.

**Comment by tangobravo** [comment]
Also note, even the OpenGL ES 3.0 spec allows implementations to implement the sRGB conversion after interpolation. From 3.8.16 of https://www.khronos.org/registry/OpenGL/specs/es/3.0/es_spec_3.0.pdf contains this:
> Ideally, implementations should perform this color conversion on each sample prior to filtering but implementations are allowed to perform this conversion after filtering (though this post-filtering approach is inferior to converting from sRGB prior to filtering).
So the inline shader sRGB decode is equivalent to something that is still spec-compliant for WebGL2. Using the explicit texture formats gives performance improvements and likely the more correct pre-filtering conversion.

**Comment by Mugen87** [comment]
The inline sRGB decode produces wrong colors, see https://github.com/mrdoob/three.js/issues/22483. The implementation was hacky (compared to `SRGB8_ALPHA8`) and only worked for built-in textures.

TBH, I would rather recommend to remove WebGL 1 support than bringing back the sRGB inline decode. If users don't want the current policy, they have to stick at `r136`.

**Comment by tangobravo** [comment]
> The inline sRGB decode produces wrong colors, see #22483. The implementation was hacky (compared to `SRGB8_ALPHA8`) and only worked for built-in textures.

As @donmccurdy [mentioned](https://github.com/mrdoob/three.js/issues/22483#issuecomment-911835712) in that issue - that example is designed to make this obvious, as it tests 0.5 interpolation between two vastly different pixel values. It really overstates the severity of the issue in general, and as I mention above it's even spec-compliant to do the conversion post-filtering.

In practice if those intermediate values between two pixels are important then just increasing texture resolution will reduce the error introduced by post-filtering conversion. The precision errors introduced in the CPU fallback are likely to have a much more severe real-world impact.

> TBH, I would rather recommend to remove WebGL 1 support than bringing back the sRGB inline decode. If users don't want the current policy, they have to stick at `r136`.

It seems the settled opinion from #22689 that it's too soon to remove WebGL1 support. I'm not suggesting removing use of SRGB8_ALPHA8 or EXT_sRGB where available, but just that the inline shader decode is a much better WebGL1 fallback than CPU-side lossy 8-bit conversion.

If the view of the project is that from r136 the WebGL1 output will be regressed in order to offer code simplifications for WebGL2, and that going forward more divergence can and should be expected, that's certainly a reasonable policy but it is one that would involve us sticking at r136 for our projects until we're prepared to give up on WebGL1.

[There are certain ecosystem issue with react-three-fiber packages that bump peer dependencies in patch versions leading to npm install usually requiring the latest three - it's not a three.js issue, but does bring practical challenges to trying to stick to an early version right now.]

**Comment by chubei-oppen** [comment]
> WebGL1 output will be regressed in order to offer code simplifications for WebGL2, and that going forward more divergence can and should be expected

I feel this is the status quo. Besides the PR discussed in this issue, #23060 makes HDR not usable on devices without `OES_texture_float` support.

I think it'd be benefial that we settle our attitude on WebGL1 support. That is to say, we either formally announce that "three.js is gradually dropping support for WebGL1", or reconsider relevant changes. This way people will be less suprised when they find something not working on WebGL1 devices.

**Comment by tangobravo** [comment]
Here's a fiddle to demonstrate the precision loss introduced by the CPU fallback:
https://jsfiddle.net/z1kxn5pj/81/

<img width="542" alt="Precision Loss" src="https://user-images.githubusercontent.com/770066/160836676-b2b48726-94b7-4727-8d2f-085bbd267f70.png">

There's a 2D canvas on top that renders a radial gradient. The three.js canvas is below, with renderer.outputEncoding set to sRGBEncoding. The texture on the left is set as sRGBEncoding too, and looks good. The one on the right goes through the ImageUtils.sRGBToLinear fallback and is then set to LinearEncoding. You can see banding is apparent in the darker areas due to the precision loss.

@Mugen87 from your [comment in #22483](https://github.com/mrdoob/three.js/issues/22483#issuecomment-911465597) it sounds like your expectation (at that time at least) was that the sRGB formats do something similar to the CPU fallback, where they "decode once". To be clear, that is not what the extensions do - they don't change the underlying bytes, but just change how those bytes are interpreted when sampling from the texture.

sRGB maintains more precision in darker areas than a linear 8-bit encoding, and hence doing this conversion on the CPU (still to an 8-bit texture) leads to information loss. Converting to 16-bit or float would maintain sufficient precision but cost more memory.

One more thing to clarify - the "wrong colors" you refer to from #22483 are only when a sample is interpolated between pixels - sampling on pixels (THREE.NearestFilter) will give identical ("correct") results with the inline decode. The interpolated results with other filters will differ slightly, but the interpolation will still give a smooth, monotonic, transition between the exactly-correct values at pixel-aligned samples. Outside of the conformance test specifically designed to make this obvious, are you aware of any real-world situations where this was a problem?

**Comment by chubei-oppen** [comment]
@tangobravo We have encountered a use case where sRGB formats make a big difference. This happens when you use gpu generated mipmaps with sRGB textures. Apparently, under WebGL2 sRGB textures are filtered in linear space and stored in sRGB, while non-sRGB textures are filtered as is, which is in sRGB space if you stored the same pixel values in the image. At high mipmap levels the difference is very obvious (because the filtering is done repeatedly). We have [a simple example](https://github.com/oppenfuture/three.js/blob/r137-dev/examples/screenshots/webgl_srgb_textures.jpg) to show the case.

This gives another reason to allow users to control whether to use sRGB textures, in case they want to deliver consistent rendering in WebGL1 and WebGL2 environments.

**Comment by makc** [comment]
> [There are certain ecosystem issue with react-three-fiber packages that bump peer dependencies in patch versions leading to npm install usually requiring the latest three - it's not a three.js issue, but does bring practical challenges to trying to stick to an early version right now.]

npm: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

yarn: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

did any of these not work for you @tangobravo

**Comment by tangobravo** [comment]
> > [There are certain ecosystem issue with react-three-fiber packages that bump peer dependencies in patch versions leading to npm install usually requiring the latest three - it's not a three.js issue, but does bring practical challenges to trying to stick to an early version right now.]
> 
> npm: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
> 
> yarn: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/
> 
> did any of these not work for you @tangobravo

I don't want to go too off-topic here, but to provide a bit more context:

Our packages are libraries with three as a peer dependency. There was a peer dependency conflict with three-stdlib due to [this issue](https://github.com/pmndrs/three-stdlib/issues/143). Our users could potentially have resolved this through package overrides but often they're pretty new to npm, and having to document that and communicate it would have been painful. Thankfully three-stdlib have managed to relax their requirements in the peer dependency again in another patch release, so that should have resolved things for now.

**Comment by tangobravo** [comment]
On the main topic of this issue, I can definitely see the arguments for removing the inline decode and agree it's a cleaner and more universal approach to use the texture formats for this. Also after further investigation it seems most of the iOS 15.4 WebGL regressions were in antialiased contexts and affected both WebGL 1 and 2, so it seems WebGL 2 is potentially usable on iOS (just need to avoid antialiased contexts on 15.4).

One remaining practical concern I have even for WebGL 2 contexts is around video - we use a lot of video in our experiences (both from getUserMedia and video files). I haven't tested, but it wouldn't surprise me if many browsers only have a hardware fast path implemented for RGBA formats. I think right now three still assumes RGBA for video and does an inline decode, but the plan is to move that to sRGB internal formats too at some point in future?

For WebGL1 there are now two fallbacks but each with their own drawbacks - on devices with EXT_SRGB you'll get correct texture sampling but no mipmaps, and on devices without the extension you'll get banding in your textures but mipmaps still supported.

**Comment by Mugen87** [comment]
> I think right now three still assumes RGBA for video and does an inline decode, but the plan is to move that to sRGB internal formats too at some point in future?

Yes. Right now, video texture still use inline decodes and also `texImage2D()` instead of `texStorage2D()`. Browser issues and problems with determining the dimensions of a video texture prevent a migration so far. But I guess when we dump WebGL 1 and the related fallbacks and code paths, we are going to reconsider this issue.

In any event, #23129 is not going to be reverted so this issue can be closed.

**Comment by donmccurdy** [comment]
With https://crbug.com/1256340 fixed, does anything block us from removing the DECODE_VIDEO_TEXTURE define blocks and using hardware sRGB decoding for video instead?

- see https://github.com/mrdoob/three.js/commit/57ac4776ac7328f7fd239c5b24b61a96171e8419

**Comment by donmccurdy** [comment]
Attempting in https://github.com/mrdoob/three.js/compare/dev...donmccurdy:three.js:feat/video-texStorage2D. Some errors from WebGL are not obvious to me:

- GL_INVALID_VALUE: Texture dimensions must all be greater than zero.
- GL_INVALID_OPERATION: The destination level of the destination texture must be defined.

It seems that `video.width` and `video.height` are 0 when we attempt to call texStorage2D... I'll look into that more but would be curious if you have ideas how it should be handled.

**Comment by Mugen87** [comment]
Just remove the `DECODE_VIDEO_TEXTURE` path. The usage of `texStorage2D()` does not work with video texture in its current form.

**Comment by tangobravo** [comment]
Definitely worth checking the sRGB path both works as expected and doesn't introduce performance regressions on common hardware / browser / OS combinations, for both media from files and getUserMedia video streams. I don't know for sure but it wouldn't surprise me if there are accelerated codepaths in browsers that might not be tested / verified with sRGB textures.

**Comment by mrdoob** [comment]
@tangobravo could you help by testing that for us?
