### ISSUE TITLE
Move GLTFLoader, OrbitControls, and BufferGeometryUtils to core

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#23819]
**Is your feature request related to a problem? Please describe.**

The GLTFLoader, OrbitControls, and BufferGeometryUtils are the three most imported things from the `examples/jsm` (and the postprocessing-related things are the fourth, I think). I also think that they are stable enough to be moved to the core.

**Describe the solution you'd like**

I suggest they would be moved to the core.

**Describe alternatives you've considered**

They can remain in the examples and then users will still import them from `examples/jsm`.

**Comment by Mugen87** [comment]
I don't think we should start arguing what example modules should be in core or not. We had this discussion in the past and it was just not possible to find a solution that makes everybody happy since the relevance of example files massively varies from user to user. 

Besides, since more and more devs work with bundlers and the `npm` package, this topic has somewhat lost relevance.

In order to keep the UMD build files small, I would not start moving files around. And to be honest, I would appreciate if we could spend our energy on other, more important issues.

**Comment by LeviPesin** [comment]
> it was just not possible to find a solution that makes everybody happy since the relevance of example files massively varies from user to user.

The same then can be said about the core... E.g. it can be said that many users do not need WebXR-related things and that then they should be moved to examples...

As for me, I understand modules in examples as either they have quite low use, they are not stable enough, or they are almost unmaintained. I think all these three conditions are not true for GLTFLoader, OrbitControls, and BufferGeometryUtils.

**Comment by donmccurdy** [comment]
The threshold for "three" vs. "three/examples/jsm/..." should probably not be stability or popularity, but:

1. Is it a building block for the three.js library, or key libraries in the ecosystem? 
2. Is it valuable for three.js to offer exactly [one obvious way](https://en.wikipedia.org/wiki/Zen_of_Python) to solve the problem?

Personally I don't think these modules satisfy those two goals. They're popular, but not not foundational to other things. There are many ways to implement or customize controls, of which OrbitControls is the most popular but not the "best" in any objective way. There are at least two other glTF loaders for three.js, with various pros/cons.

I could see components related to post-processing or node materials needing to be pulled into the core build at some point, for these reasons. Stability is necessary but not sufficient, and popularity is probably orthogonal.

**Comment by donmccurdy** [comment]
> ... But most users are using the three.js' built-in one - and for them it would be just more understandable to import it from the core and not the examples.

I'm not sure I agree with this – isn't it also confusing if some official loaders and controls come from one place, others from another? Why should switching from OrbitControls to MapControls change how you import the module?

It is a real source of confusion that we provide both `examples/js` and `examples/jsm`, and CDNs add another layer of complexity. I think Spotify's concept of a [golden path](https://engineering.atspotify.com/2020/08/how-we-use-golden-paths-to-solve-fragmentation-in-our-software-ecosystem/) ("the opinionated and supported path to build something") is a good thing, and we don't really have that for our examples today. To me that is the underlying problem that leads people to want things moved into core, but I'm not sure it's the right solution. Keeping the core build small also makes it easier to avoid gradually slipping into (unwanted) interdependencies. For example, GLTFLoader's spec/gloss materials are not (and shouldn't be) core three.js materials.

**Comment by mrdoob** [comment]
Personally, I'm a bit nerdy-annoyed that we passed the 150kb gzipped mark so, if anything, I'm on the lookout for things to move out of core instead 🤓
