### ISSUE TITLE
Data texture with LuminanceFormat used as alphaMap broken from r136

### ISSUE THREAD

**Issue by madou** [mrdoob/three.js#23824]
**Describe the bug**

After upgrading from v135 to latest the data texture I was using is now logging WebGL warnings to console, looking through the changelog there doesn't seem to be any breaking changes I should be aware of outside of setting `needsUpdate`. The change that affected this was introduced in v136.

```
WebGL warning: texStorage(Multisample)?: internalformat: Invalid enum value LUMINANCE
WebGL warning: texSubImage: The specified TexImage has not yet been specified.
```

***Code***

```js
import {
  DataTexture,
  LuminanceFormat,
  UnsignedByteType,
} from 'three';

const primaryMask = new Uint8Array(2500);

const texture = new DataTexture(
  primaryMask,
  50,
  50,
  LuminanceFormat,
  UnsignedByteType
);

texture.needsUpdate = true;
```

In v135 - nothing logged to console, alphaMap working as intended (partial transparent)
In v136 - two warnings logged to console, alphaMap not working as intended (everything transparent)

***Live example***

* r135 WORKS https://codesandbox.io/s/wild-microservice-7yobcp?file=/src/index.js
* r139.1 DOES NOT WORK https://codesandbox.io/s/crazy-mcclintock-09k4pb?file=/src/index.js

**Expected behavior**

No warnings logged to console, transparency working as intended.

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Firefox
 - Three.js version: r136

**Comment by Mugen87** [comment]
The problem is that `gl.LUMINANCE` can not be used as an internal format with the new `texStorage2D()` API.

Since the fragment shader samples the green channel of the alpha map, I suggest you use the `RGFormat` instead:

https://jsfiddle.net/qxgezwuj/1/

**Comment by madou** [comment]
Thanks for the info! That is helpful. Previously I could use Luminance data texture for each array item corresponding to a particular coordinate on a 2d grid - with RGFormat obviously it needs double the size of the array now so each array item now would be red/green? So every second array item would be the one I'm interested in for the alpha map? 🤔

**Comment by WestLangley** [comment]
@madou You can use this pattern to support a single-channel alpha map texture using `RedFormat` with three.js r139.

```js
material.onBeforeCompile = function( shader ) {

	shader.fragmentShader = shader.fragmentShader.replace(

		`#include <alphamap_fragment>`,

		`#ifdef USE_ALPHAMAP
			diffuseColor.a *= texture2D( alphaMap, vUv ).r;   // read red channel, instead
		#endif`

	);

};
```

You could also use `NodeMaterial`, I assume.

**Comment by madou** [comment]
That works well @WestLangley, thank you! It would be great if we could update the three docs with all this information 🤔

**Comment by Mugen87** [comment]
>  with RGFormat obviously it needs double the size of the array now so each array item now would be red/green? 

Please keep in mind that `gl.LUMINANCE` is problematic since at least one WebGL implementation (ANGLE) has to expand texture data to four channels to make luminance textures work with Direct 3D. This is not necessary when using `RGFormat` (or `RedFormat`).

> I do get one warning however which is THREE.WebGLTextures: sRGB encoded textures have to use RGBAFormat and UnsignedByteType - is that a benign warning? Everything is working as expected even with this warning.

I suggest you ask this question at the [forum](https://discourse.threejs.org/) or stackoverflow. If it turns out to be a problem of `three.js`, we can reopen this issue.
