### ISSUE TITLE
Docs: Please document MeshPhysicalMaterial.attenuationColor, attenuationDistance

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#23833]
**Is your feature request related to a problem? Please describe.**

New MeshPhysicalMaterial properties are not documented.

**Describe the solution you'd like**

I'd like them to be documented 😁 I'd do it myself but I don't know enough about the properties or implementation to describe them effectively. I'm particularly interested in how the attenuation color and implementation relates to the diffuse color and transmission properties.

**Describe alternatives you've considered**

😭 

**Additional context**

--

**Comment by WestLangley** [comment]
See #23831

**Comment by gkjohnson** [comment]
Ha just saw that, thanks!

**Comment by WestLangley** [comment]
Related: #23448

**Comment by WestLangley** [comment]
.

**Comment by LeviPesin** [comment]
I think https://github.com/mrdoob/three.js/issues/23509 should be closed in favor of this issue.

**Comment by Mugen87** [comment]
Duplicate of #23509.
