### ISSUE TITLE
Problem with centering of a scene in tab devices

### ISSUE THREAD

**Issue by dmitry-izmerov** [mrdoob/three.js#23837]
**Problem with centering of a scene**

A problem happens with centering of a scene on tab devices in emulation mode when viewport is changed.

**To Reproduce**

1. Open dev tools, pick mobile emulation mode, choose a tab device like Ipad, Galaxy Tab S4, etc.
2. Open a page with an example.
4. Click the button with text "Change viewport".
5. Observe that the green object is not centered.

***Code***
https://github.com/dmitry-izmerov/threejs-centering-issue/blob/master/index.html

***Live example***
https://dmitry-izmerov.github.io/threejs-centering-issue/

**Expected behavior**

A scene should be centered on a screen.

**Screenshots**

![Animation](https://user-images.githubusercontent.com/5845913/161537048-fdc57e01-a887-40b0-acf9-7f634fd85aae.gif)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome, Edge] (device emulation mode, tab devices like Ipad, Galaxy Tab S4)
 - Three.js version: [latest]

**Comment by marcofugaro** [comment]
Not sure if this is an issue related to three.js...

**Comment by Mugen87** [comment]
I've tested with latest Chrome but I don't have a Galaxy Tab S4 in my selection. However, the issue appears with the Galaxy Fold entry as well. All others work as expected.

**Comment by dmitry-izmerov** [comment]
@Mugen87 it can be temporarily fixed by setting devicePixelRatio to 1.

**Comment by Mugen87** [comment]
Well, I don't know why this happens but it's definitely no `three.js` related issue. I assume it's an issue in the dev tools or in your `changeViewport()`. 

I suggest you use stackoverflow or the [forum](https://discourse.threejs.org/) to get more feedback. This issue can be reopened if it turns out to be a problem in the engine.

**Comment by Mugen87** [comment]
BTW: You can use your GitHub account to log in at the forum.
