### ISSUE TITLE
USDZ exporter ignores axis translation

### ISSUE THREAD

**Issue by Filippo-Trevisan-RI** [mrdoob/three.js#23842]
**Describe the bug**

In trying to export a glTF model, it looks like the USDZ exporter ignores the previously applied translation. 

**To Reproduce**

1. Load your glTF
2. Set updateMatrixWorld to true (i.e. gltf.scene.updateMatrixWorld(true))
3. Apply translation to an axis (e.g. gltf.scene.translateY(some_value))
4. Export; the USDZ won't be translated.

***Code***

```js
gltf.scene.updateMatrixWorld(true);
const box = new THREE.Box3().setFromObject(gltf.scene);
const lowestPoint = box.min.y;

if (lowestPoint < 0) {
    gltf.scene.translateY(Math.abs(lowestPoint));
}

const exporter = new THREE.USDZExporter();
const arraybuffer = await exporter.parse(gltf.scene);
fsExtra.writeFileSync(fileName + ".usdz", arraybuffer);
```

**Expected behavior**

The USDZ would have its axis translated as well.

**Screenshots**

![USDZ](https://user-images.githubusercontent.com/91926334/161681972-b4ec886f-f89e-48e7-916b-bb5e0b2ffa75.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chromium] (Electron application)
 - Three.js version: [0.133.1]

**Comment by Mugen87** [comment]
Try calling `updateMatrixWorld()` after `translateY()`. So:
```js
gltf.scene.translateY(Math.abs(lowestPoint));
gltf.scene.updateMatrixWorld();
```
