### ISSUE TITLE
GLTFLoader BufferAttribute unable to reference directly in THREE.BufferGeometry.attributes[x] (Suggested Fix)

### ISSUE THREAD

**Issue by Chrisyss** [mrdoob/three.js#23846]
GLTF Loaders BufferAttribute cannot directly be used as references for THREE.BufferGeometry.attributes[x]  such as position  or THREE.BufferGeometry.index

Three.BufferGeometry requires attributes to be typed for example as Float32BufferAttribute or Uint16BufferAttribute

The fix is quite easy.

1. add a new Mapping dict for Buffers ( which currently doesn't exist it seems this is old and hardcoded):

```
	const WEBGL_COMPONENT_TYPES_BUFFER_ATTRIBUTE_MAPPING = {
		5120: THREE.Int8BufferAttribute,
		5121: THREE.Uint8BufferAttribute,
		5122: THREE.Int16BufferAttribute,
		5123: THREE.Uint16BufferAttribute,
		5125: THREE.Uint32BufferAttribute,
		5126: THREE.Float32BufferAttribute,
	};
```

2. later in the GLTFLoader code replace the buffer attribute line with the following:

		
```
const bufferTypeLookUp = WEBGL_COMPONENT_TYPES_BUFFER_ATTRIBUTE_MAPPING [accessorDef.componentType];

bufferAttribute = new bufferTypeLookUp( array, itemSize, normalized );
// bufferAttribute = new THREE.BufferAttribute( array, itemSize, normalized );



//some ifs bellow


const bufferTypeLookUp2 = WEBGL_COMPONENT_TYPES_BUFFER_MAPPING[accessorDef.sparse.indices.componentType];

// bufferAttribute = new THREE.BufferAttribute( bufferAttribute.array.slice(), bufferAttribute.itemSize, bufferAttribute.normalized );
bufferAttribute = new bufferTypeLookUp2( bufferAttribute.array.slice(), bufferAttribute.itemSize, bufferAttribute.normalized );


```

could probably reuse the same lookup for both attribute constructions.

doing a proper commit and pull request would take me too much time so I just write it here for the dedicated developer to pick it up :)

**Comment by donmccurdy** [comment]
> Three.BufferGeometry requires attributes to be typed for example as Float32BufferAttribute or Uint16BufferAttribute

There is no such requirement – using a generic THREE.BufferAttribute with a typed array is normal. Are you seeing some particular error or warning that you're trying to fix?

**Comment by Chrisyss** [comment]
yes you get warnings and errors. because Three looks for typed  versions.       with  the fix above you can simply assign A=B
Which speeds up a lot of use cases.  else you would have to do a prototype copy.

**Comment by Mugen87** [comment]
> yes you get warnings and errors. because Three looks for typed versions.

I don't think that's true. Classes like `Float32BufferAttribute` are pure optional and not mandatory when working with buffer attributes.

> yes you get warnings and errors. 

Please share them. It would be also good to share a [live example](https://jsfiddle.net/f2Lommf5/) that demonstrate the issue.

**Comment by donmccurdy** [comment]
Most three.js contributors are not dedicated maintainers. With very few exceptions, we are doing this for free on their own time. If you are not comfortable making pull requests that's OK, but please respect our time in addition to your own.

Their may be a misunderstanding here — perhaps you're using TypeScript and it's giving warnings and errors in some particular situation? See https://github.com/three-types/three-ts-types if so. But in any case, there is no requirement to use Float32BufferAttribute etc. We can't see these errors, but if they're coming from _three.js itself_ we can fix them. Please share details full details to reproduce the issue (as in the issue report template) if that's the case.

**Comment by Mugen87** [comment]
Closing until the OP provides more information.
