### ISSUE TITLE
Opacity issue when using SSAARenderPass in r139

### ISSUE THREAD

**Issue by wraitii** [mrdoob/three.js#23840]
**Describe the bug**

Using SSAARenderPass is buggy in r139 over non-black backgrounds. Something funky happens with the opacity, and the resulting image appears to have the opacity of a single layer instead of an opacity of 1.0.

This works in r138 and I assume the breaking change was #23671

**To Reproduce**

1. Go on https://threejs.org/examples/?q=ssaa#webgl_postprocessing_ssaa
2. Change the HTML body background to e.g. red
3. Play around with the # of samples: 0 looks normal, and increasing looks broken.

**Expected behavior**

The non-transparent part of the rendering should not bleed the background colour.

**Screenshots**

<img width="569" alt="bug0" src="https://user-images.githubusercontent.com/1927071/161576359-e3cc1faa-245c-48e6-a9b3-bed75dd9599c.png">
<img width="468" alt="bug1" src="https://user-images.githubusercontent.com/1927071/161576380-a8c41e45-8c0a-48d9-aefc-82b61392b50d.png">
<img width="555" alt="bug2" src="https://user-images.githubusercontent.com/1927071/161576383-d91126fe-1ee9-4247-87dd-58f23d4bbd10.png">

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: confirmed in Chrome & Safari
 - Three.js version: r139, likely dev as well. Worked in r138

**Comment by Mugen87** [comment]
Thanks for reporting. For clarification `SSAARenderPass` never supported HTML background colors so the issue just became apparent with #23671.

It seems the class requires a bit refactoring to make this work.

**Comment by Arkitoy** [comment]
Black background cannot be used for some reason.

Has the bug been solved？
