### ISSUE TITLE
GPURenderer fails to set correct transparent background

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#23847]
In the case of `WebGLRenderer`, we can do this:

```js
renderer.setClearColor( 0xff0000, 0.5 );
```

But behind the scenes, the RGB values are premultiplied by alpha.

To achieve the same effect with `WebGPURenderer`, this is required:

```js
renderer.setClearColor( 0x7f0000, 0.5 ); // <== the app must premultiply by alpha
```

//

`WebGPURenderer` sets `compositingAlphaMode: 'premultiplied'`.  (This means that the compositor expects premultiplied alphas in the drawing buffer.)

I think it is sufficient to implement in `WebGPURenderer` similar clear-color logic to that found in `WebGLRenderer`,  `WebGLBackground` and `WebGLState`.

Also, as I suggested [here](https://github.com/mrdoob/three.js/pull/23776#issuecomment-1077562617), `WebGPURenderer._clearAlpha` should be initialized to zero.

/ping @sunag

 - Three.js version: [r139]

**Comment by Mugen87** [comment]
> Also, as I suggested https://github.com/mrdoob/three.js/pull/23776#issuecomment-1077562617, WebGPURenderer._clearAlpha should be initialized to zero.

The clear alpha value in `WebGLRenderer` is `1` by default since the canvas is not blended with the HTML background unless you apply `alpha: true` or use `renderer.setClearAlpha( 0 )`. I don't think `WebGPURenderer` should behave differently.
