### ISSUE TITLE
getWorldScale and getWorldQuaternion return incorrect values when object scale has three negative components

### ISSUE THREAD

**Issue by bennlich** [mrdoob/three.js#23852]
**Describe the bug**

`mesh.getWorldScale` and `mesh.getWorldQuaternion` return incorrect values for a mesh with negative x, y, and z scale components.

If `mesh.scale` is (-1, -1, -1), `getWorldScale` returns (-1, 1, 1), losing two minus signs. If `mesh.quaternion` is (0, 0, 0, 1), `getWorldQuaternion` returns (1, 0, 0, 0).

**To Reproduce**

1. Go to https://codepen.io/bennlich/pen/NWXyLKm
2. Click anywhere on the canvas
3. Notice how the image texture flips, and look at the console to see how the values of mesh.scale differ before and after.
4. Go to https://codepen.io/bennlich/pen/MWrQPWE to see the analogous bug with getWorldQuaternion

**Expected behavior**

In the live example above, I would not expect the mesh to flip. I would expect `getWorldScale` to return the same value as the mesh's current local scale. Same with `getWorldQuaternion`.

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome
 - Three.js version: 0.139.2

**Comment by Mugen87** [comment]
`(-1, -1, -1)` produces a reflection in the object matrix which is not supported. Please stick to positive scaling.

What is your use case for reflecting the geometry?

**Comment by donmccurdy** [comment]
Related:

> ...it is possible to compute a choice of translation 𝑇, rotation 𝑅, and scale 𝑆 with the same combined result as [matrix] 𝑀. But there is no guarantee that these will be the same values originally used to create 𝑀, as we'll see below...

https://gamedev.stackexchange.com/questions/117528/calculate-matrix-transformation-components-separately

Matrix decomposition (or higher-level methods like getWorldScale) cannot be guaranteed to return the same TRS components as the originals. Repeated round-trip conversions between matrixes and TRS components should be avoided.

**Comment by WestLangley** [comment]
Scaling by ( - 1, - 1, 1 ), for example, is equivalent to a rotation-only around the z-axis.

`quaternion` and `scale` are coupled in such cases and you can't consider them individually.

**Comment by bennlich** [comment]
> What is your use case for reflecting the geometry?

@Mugen87 I got here because I'm building a scene editor that uses THREE.TransfromControls to change the scale of objects in a scene. It seems that in scale mode, TransformControls will set the scale dimensions to be negative if you shrink an object beyond the point where it disappears. And this is somewhat useful for turning objects inside out.

> Matrix decomposition (or higher-level methods like getWorldScale) cannot be guaranteed to return the same translation/rotation/scale (TRS) components as the originals. Repeated round-trip conversions between matrixes and TRS components should be avoided.

@donmccurdy My scene editor currently works like this:

1) select one or more objects that you want to transform together
2) add all these objects to a new THREE.Group()
3) use THREE.TransformControls on this group to transform the objects in the group as a whole
4) when you're done with your transformations, re-home the selected objects from the Group back to the Scene. Use getWorldPosition(), getWorldScale(), and getWorldQuaternion() to calculate the correct new values relative to the Scene coordinate system.

This is where my round trips are coming from. Essentially, I am using getWorldScale() to calculate the scale my object should have in the Scene coordinate system. Do you think this is a bad approach? It has worked very well so far except for the case of a negative scale.

**Comment by donmccurdy** [comment]
If you haven't changed the scale or rotation of the TransformControls group, then I think it would be safe to skip the `getWorldScale()` and `getWorldQuaternion()` steps to preserve the original values. But once you start the whole round-trip it's going to be very hard to preserve that specific _representation_ of the original transform.

Some clever math probably exists that might help to restore a TRS representation similar (e.g. in terms of component signs) to the original TRS, but that's beyond the scope of the THREE.Object3D interface I think, it might be worth pursuing on https://discourse.threejs.org/ or even https://math.stackexchange.com/questions/tagged/linear-algebra.
