### ISSUE TITLE
Changing `transparent` property doesn't have any effect on materials, if `true` is not provided in the constructor

### ISSUE THREAD

**Issue by soadzoor** [mrdoob/three.js#23866]
**Describe the bug**

It seems the since r137, the default value for `transparent` prop for materials need to be `true` (provided in the constructor) if you ever want to make the material transparent in its lifetime. If the default value is `false` (or is not provided), then changing it to `true` won't have any effect.

**To Reproduce**

1. Create a mesh
2. Some time later (with `setTimeout`, or by a click event, or anything), attempt to make the material transparent, like this: `mesh.material.transparent = true; mesh.material.opacity = 0.5;`
3. Note how the material remains unchanged

***Live example***

[https://jsfiddle.net/9cjg5ofs/2/](https://jsfiddle.net/9cjg5ofs/2/)

**Expected behavior**

Prior r137, it worked as expected, users could change the `transparent` property from `true` to `false`, and vica versa, and it took effect immediately.

Proof of this (same code, different three.js version (r136)): [https://jsfiddle.net/a7hotpb2/](https://jsfiddle.net/a7hotpb2/)

**Platform:**

 - Three.js version: [dev, r137+]

**Comment by soadzoor** [comment]
@Mugen87 Oh, right, I must've overlooked, sorry. 
But it does work the other way around, though: changing it from `true` to `false`, without settings `needsUpdate = true`. Is that okay?

**Comment by Mugen87** [comment]
It works because blending is disabled. However, the define `OPAQUE` would be still set in your shader which can produce issues. Probably not in your particular case.
