### ISSUE TITLE
RFC: RaycasterHelper

### ISSUE THREAD

**Issue by gsimone** [mrdoob/three.js#23877]
Hey! 👋  
I made a very simple raycaster helper for myself, was wondering if it isn't worth adding this along the other existing helpers.

https://user-images.githubusercontent.com/1862172/162688071-4993e811-2fe0-4b8a-99c6-99c38214d78e.mov

Try it here https://6tc01w.csb.app/

It displays:
- a segment going from origin to near + near to far
- the two near/far points
- optionally displays any hit via instances - this could just be points tbh
- optionally displays wether or not any hit exists

The style is halfway between @gkjohnson 's bvh ray visualizations and three's directional light helper

API is:

```js
const raycaster = new Raycaster(origin, direction, near, far)
const helper = new RaycasterHelper( raycaster, 5 ) // raycaster + max number of hits to display

// in your loop
const hits = raycaster.intersectObjects( scene.children )
helper.hits = hits;
```   

Some boring nuance:
- all the elements created by the helper have their raycast set as null, otherwise they'd always be hit by the ray they are visualizing 😓 
- there's some inefficiency in the way lines are updated, but that should be easily fixed if it's worth doing
- all the components of the visualization are exposed as properties of the object, so they can be easily overridden, eg.
```js
const helper = new RaycasterHelper( raycaster )
// make the hits red instead of white
helper.hitsVisualization.material.color = "#ff005b"
```

**Comment by mrdoob** [comment]
<img width="1070" alt="Screen Shot 2022-04-11 at 12 58 49 PM" src="https://user-images.githubusercontent.com/97088/162819676-5aac8b97-809f-4d9e-977c-358a65e3fad3.png">

🤔

**Comment by mrdoob** [comment]
I'm also confused by these points:

<img width="784" alt="Screen Shot 2022-04-11 at 1 00 12 PM" src="https://user-images.githubusercontent.com/97088/162820321-8050a0f0-c34e-448c-94f2-0b431dbf9f74.png">

🤔

**Comment by mrdoob** [comment]
Looks good though!
Would be nice to put it in `examples/jsm/helpers/`.

**Comment by gsimone** [comment]
@mrdoob ops, that's silly me, I recorded this from a demo where I'm doing some experiments with layers, so there's a third capsule that doesn't show up in the camera layer lol

**Comment by mrdoob** [comment]
Ah I see...

Yeah, sounds good to me!

By the way, I just noticed that `CapsulreGeometry`'s normals seem to have something wrong at the poles 🤔

<img width="330" alt="Screen Shot 2022-04-14 at 11 12 25 AM" src="https://user-images.githubusercontent.com/97088/163451776-f410a03c-023a-4d2b-bda0-1e27539b09ff.png">

**Comment by abernier** [comment]
done in https://github.com/mrdoob/three.js/pull/30088 ;)
