### ISSUE TITLE
Position and Rotation support for toJSON() and ObjectLoader()

### ISSUE THREAD

**Issue by jgphilpott** [mrdoob/three.js#23871]
**Is your feature request related to a problem? Please describe.**

I'm trying to save my three.js meshes to the browser local storage and reload them. This is so that an exact scene can be restored when a user refreshes the page or closes and reopens the tab. It's working great with saving [`mesh.toJSON()`](https://github.com/mrdoob/three.js/blob/dev/src/core/Object3D.js#L629-L869) to local storage and then reloading it with [`THREE.ObjectLoader()`](https://threejs.org/docs/#api/en/loaders/ObjectLoader) except that the meshes position and rotation is ignored and thus gets reset to zero. I've developed a workaround for my use case but it would be great if these functions could have built in support for position and rotation.

**Describe the solution you'd like**

 - Have the `mesh.toJSON()` preserve the meshes position and rotation.
 - Have the `THREE.ObjectLoader()` restore the meshes position and rotation.

**Describe alternatives you've considered**

Users can build a workaround by saving mesh position and rotation elsewhere and then re-applying it after the ObjectLoader has loaded the mesh but this is far from ideal.

**Additional context**

I did a little research on StackOverflow before opening this issue and it seems like i'm [not alone here](https://stackoverflow.com/questions/48425819/three-js-mesh-position-tojson).

**Comment by Mugen87** [comment]
Maybe your code just missed to call `updateMatrix()` before serializing the 3D object? 

https://jsfiddle.net/zLdam0y3/3/

**Comment by jgphilpott** [comment]
Okay that's great, works like a charm! Thanks!

I will try to feed that info back to the StackOverflow posts I read so that people don't open new issues in the future!
