### ISSUE TITLE
WebGLRenderingTarget:Resize function not update depth texture size

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#23875]
**Describe the bug**

When we resize rendering target, it only resizes color texture.

**To Reproduce**

1. Create rendering target to render
2. Call resize to resize rendering target
3. Depth texture size is not updated

***Code***
https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderTarget.js
```js
		if ( this.width !== width || this.height !== height || this.depth !== depth ) {

			this.width = width;
			this.height = height;
			this.depth = depth;

			this.texture.image.width = width;
			this.texture.image.height = height;
			this.texture.image.depth = depth;

			this.dispose();

		}

		this.viewport.set( 0, 0, width, height );
		this.scissor.set( 0, 0, width, height );
```

***Live example***

**Expected behavior**
Depth texture if any should be matched size

**Screenshots**

**Platform:**

 - Device: [All]
 - OS: [All]
 - Browser: [All]
 - Three.js version: [master]

**Comment by Mugen87** [comment]
Depth textures are automatically resized here:

https://github.com/mrdoob/three.js/blob/a31c66ef73809accbee34cf7c72c0b5d0888c619/src/renderers/webgl/WebGLTextures.js#L1384-L1392

**Comment by Mugen87** [comment]
Closing due to lack of feedback.
