### ISSUE TITLE
Enable Depth Sensing for immersive-ar applications.

### ISSUE THREAD

**Issue by listdo** [mrdoob/three.js#23881]
**Is your feature request related to a problem? Please describe.**

In my research project we are looking for a way to use depth sensing and access depth data from immersive ar applications. Currently it seems like it is not possible to enable the optional feature "depth-sensing" provided by the api of modern browsers.

**Describe the solution you'd like**

I would like to be able to use the new "depth-sensing"-feature provided by the modern chrome browser api described in: https://www.w3.org/TR/webxr-depth-sensing-1/

**Describe alternatives you've considered**

All alternatives that lead to the same result.

**Comment by goarblt** [comment]
https://www.evil.com

**Comment by mrdoob** [comment]
@listdo Which modern browsers support this feature?

**Comment by listdo** [comment]
@mrdoob 
As far as i understood it is currently only supported by Chrome and Chrome for Android. In the following link is the feature status for chrome and there are two examples linked that use the browser api.

https://chromestatus.com/feature/5742647199137792

**Comment by julapy** [comment]
here is the WebXR sample:
[](https://storage.googleapis.com/chromium-webxr-test/r1067245/proposals/phone-ar-depth-gpu.html)
this feature is available since Chrome 90 and can be enabled `session.depthDataFormat != "luminance-alpha"`

**Comment by zz85** [comment]
it looks like this is supported today by passing ` { 'optionalFeatures': [ 'depth-sensing'] }` to `XRButton.createButton()`

 https://github.com/search?q=repo%3Amrdoob%2Fthree.js%20depth-sensing&type=code

**Comment by Mugen87** [comment]
A first approach of depth sensing has been implemented via #27586 (`r161`).

**Comment by billleap** [comment]
Hi, I just tried the Dragging demo: https://threejs.org/examples/webxr_xr_dragging.html

and got the following warning:

```
XRButton.js:69 Feature 'depth-sensing' is not supported for mode: immersive-ar
```

**Comment by mrdoob** [comment]
@billleap Any chance you can share the device you got that error with?

**Comment by idrisshah** [comment]
> @billleap Any chance you can share the device you got that error with?

I am seeing the same error on Magic Leap 2 device. I think the issue is because `depth-sensing` implementation in threejs does not use [XRDepthStateInit](https://immersive-web.github.io/depth-sensing/#dictdef-xrdepthstateinit), while using depth-sensing feature.

**Comment by billleap** [comment]
@mrdoob @idrisshah 
I was using S21 5G (SM-G991U) Android 13.
I used ADB and 'chrome://inspect/#devices' to see the warning.

**Comment by mrdoob** [comment]
> I am seeing the same error on Magic Leap 2 device. I think the issue is because `depth-sensing` implementation in threejs does not use [XRDepthStateInit](https://immersive-web.github.io/depth-sensing/#dictdef-xrdepthstateinit), while using depth-sensing feature.

@cabanier Are we missing a check before using `depth-sensing`?

**Comment by cabanier** [comment]
> > I am seeing the same error on Magic Leap 2 device. I think the issue is because `depth-sensing` implementation in threejs does not use [XRDepthStateInit](https://immersive-web.github.io/depth-sensing/#dictdef-xrdepthstateinit), while using depth-sensing feature.
> 
> @cabanier Are we missing a check before using `depth-sensing`?

It looks like the Quest browser is not requiring that this dictionary is passed. Strange, because I would expect the existing Chromium code to enforce this.
We should fix up three.js and pass an empty dict. I'll file an issue to make this optional.

**Comment by idrisshah** [comment]
>  Strange, because I would expect the existing Chromium code to enforce this. 

Chromium does seem to enforce it [here](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/xr/xr_system.cc;l=218?q=xr_system.cc&ss=chromium):
