### ISSUE TITLE
Environment map reflection got poor from release 131 to 132

### ISSUE THREAD

**Issue by nvf33** [mrdoob/three.js#23894]
**Description**
Environment map reflection got blurry from release 131 to 132. This seems to be related to the MeshBasicMaterial and the same MeshStandardMaterial or MeshPhysicalMaterial. MeshLambertMaterial is NOT affected.

**To Reproduce**
Look at this example:
[https://threejs.org/examples/?q=env#webgl_materials_envmaps](https://threejs.org/examples/?q=env#webgl_materials_envmaps) and replace the sphere's material definition line 77 from 
`sphereMaterial = new THREE.MeshLambertMaterial( { envMap: textureCube } );`
to 
`sphereMaterial = new THREE.MeshStandardMaterial( { color: 0xffffff,  metalness: 1, roughness: 0, envMap: textureCube } );`
Then look at the sphere once with a version before or = r131, and once with a version after r131. You will immediately see the difference: The resolution of the reflection has become much more blurry, and this independent on the envmap's resolution.

**Platform:**

 - Device: all
 - OS: all
 - Browser: [Firefox, Safari, Edge]
 - Three.js version: [dev, r132 and newer]

**Comment by Mugen87** [comment]
This is actually indented. Environment maps are now automatically correctly preprocessed with `PMREMGenerator` when used with PBR materials which was not true in earlier releases. So the result was physically not correct.
