### ISSUE TITLE
Wrong documentation for WebGLRenderer.outputEncoding?

### ISSUE THREAD

**Issue by mrpink17** [mrdoob/three.js#23898]
The documentation page of [WebGLRenderer.outputEncoding](https://threejs.org/docs/index.html?q=cubeca#api/en/renderers/WebGLRenderer.outputEncoding) says:

> Defines the output encoding of the renderer. Default is [THREE.LinearEncoding]().
> If a render target has been set using [.setRenderTarget]() then renderTarget.texture.encoding will be used instead.

Looking at [WebGLRenderer source](https://github.com/mrdoob/three.js/blob/f0e2b3453f1412b53389beb04add414e3a80023c/src/renderers/WebGLRenderer.js#L1440) it seems that `renderTarget.texture.encoding` is used only if `renderTarget.isXRRenderTarget` otherwise is used hardcoded `LinearEncoding`

**Comment by Mugen87** [comment]
I don't think this technical detail needs to be documented since the XR render targets are for internal use only.

**Comment by LeviPesin** [comment]
Then it should be written as `If a render target has been set then the linear encoding will be used instead`.

**Comment by Mugen87** [comment]
Fixed via 08ac351d70180ebcb76fc70a7e58706367311499.

**Comment by Mugen87** [comment]
I have reverted the change. `LinearEncoding` is only set to disable the inline encode in the shader. However, if you configure the render target with sRGB encoding, you still get a sRGB encoded output.
