### ISSUE TITLE
Documentation seems broken

### ISSUE THREAD

**Issue by badde-media** [mrdoob/three.js#23895]
[**Describe the bug**]
(https://threejs.org/examples/#webgl_multiple_elements_text)
The three.js elements don't work in Firefox. In Chrome, the first one gets displayed but when I scroll, it hangs - not only its loop hangs, but it also gets stuck at the screen position 

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**To Reproduce**

1. Go to https://threejs.org/examples/#webgl_multiple_elements_text
2. wait until loaded
3. See error

***Live example***
https://threejs.org/examples/#webgl_multiple_elements_text

**Expected behavior**

The text should be combined with 3js elements showing the movement of molecules in waves, or so. These 3d elements should be animated and scroll with the rest of the page
**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).
![image](https://user-images.githubusercontent.com/19553316/163227631-fde32fcc-77bc-489f-ba98-a6e974115f39.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome, Firefox]
 - Three.js version: [???]

**Comment by Mugen87** [comment]
This is already fixed in `dev`, see #23856.
