### ISSUE TITLE
3D object viewer does not show all model faces correctly with three.js web viewer

### ISSUE THREAD

**Issue by skat89** [mrdoob/three.js#23903]
I have created 3D model using Blender and exported to GLB.
The model is cube with 6 faces and applied textures for each of them.
Each texture has opacity and emission definitions.
While trying to embed model on web page I’ve discovered that it displays correctly only with babylon.js but not with three.js.
In case of three.js viewer some faces look completely opaque although opacity definition for all textures is the same.

[Link to the model](https://www.dropbox.com/s/6l31td2aivairoi/funspin.glb?dl=0)

**Comment by Mugen87** [comment]
Since you have also posted at the forum, let's discuss the issue there: https://discourse.threejs.org/t/3d-object-viewer-does-not-show-all-model-faces-correctly-with-three-js-web-viewer/37127

If it turns out to be a new (unknown) issue, this one can be reopened.

**Comment by skat89** [comment]
> Since you have also posted at the forum, let's discuss the issue there: https://discourse.threejs.org/t/3d-object-viewer-does-not-show-all-model-faces-correctly-with-three-js-web-viewer/37127
> 
> If it turns out to be a new (unknown) issue, this one can be reopened.

For me it seems new issue!?
