### ISSUE TITLE
ImageBitmapLoader (GLTFLoader) fails in Firefox ESR

### ISSUE THREAD

**Issue by gernotziegler** [mrdoob/three.js#23906]
**Describe the bug**

GLTF models don´t load in Firefox ESR due to lack of support for ImageBitLoader. 

**To Reproduce**

1. Install Firefox ESR (version number 91) from https://www.mozilla.org/en-GB/firefox/all/#product-desktop-esr
2. Open https://www.geofront.eu/tmp/ironmen_bugreport_fail
3. GLTF model is not being loaded. See also error: THREE.GLTFLoader: Couldn´t load texture tex.webp 

***Code***

The problem lies in the removal of a check for Firefox to avoid usage of ImageBitmapLoader (compare r130). 
The most recent Firefox version works fine with this - but Firefox ESR (used internally in the museum that has published this webpage) is not yet capable of handling ImageBitmapLoader. 
We therefore suggest an additional check for Firefox and its ESR-channel version number 91 in this code snippet of GLTFLoader.js: 

```js
 if ( typeof createImageBitmap !== 'undefined' && /^((?!chrome|android).)*safari/i.test( navigator.userAgent ) === false  && /Firefox\/91/.test( navigator.userAgent ) === false) {
this.textureLoader = new ImageBitmapLoader( this.options.manager );
} else {
this.textureLoader = new TextureLoader( this.options.manager );
}

```

Note: This will have to be extended to later Firefox ESR versions (we did not track down the exact version where Firefox´ ImageBitmapLoader starts working). 

***Live example***

* Fail:  https://www.geofront.eu/tmp/ironmen_bugreport_fail
* Fixed: https://www.geofront.eu/tmp/ironmen_bugreport_fixed

**Expected behavior**

The GLTF should have loaded and displayed, just like in Firefox 99. 

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Firefox ESR release 91.8.0esr (64-bit) https://support.mozilla.org/en-US/kb/firefox-esr-release-cycle
 - Three.js version: r139

**Comment by Mugen87** [comment]
> we did not track down the exact version where Firefox´ ImageBitmapLoader starts working.

see #23742. It seems 98 should be safe.

```js
/Firefox\/91/.test( navigator.userAgent ) === false
```
Probably better to not check for an exact release but something like "all FF releases lower than 98".

> This will have to be extended to later Firefox ESR versions

Looking at the [Firefox Release Calendar](https://wiki.mozilla.org/Release_Management/Calendar), the next ESR version 102 will be released at the end of June. If we decide to add a version check, I would remove it from the loader when 102 has been released.

**Comment by aardgoose** [comment]
Support for options by feature in MDN

https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap

**Comment by Mugen87** [comment]
Suggested fix:
```js
if ( typeof createImageBitmap !== 'undefined' && /^((?!chrome|android).)*safari/i.test( navigator.userAgent ) === false  &&  ( navigator.userAgent.match(/Firefox\/([0-9]+)\./)?.[ 1 ] >= 98 )  ) {

    this.textureLoader = new ImageBitmapLoader( this.options.manager );

} else {

    this.textureLoader = new TextureLoader( this.options.manager );

}
```

**Comment by gernotziegler** [comment]
@Mugen87 Yes, that seems to work, tested in Firefox ESR via URL: 
https://www.geofront.eu/tmp/ironmen_bugreport_fixedversion

**Comment by Mugen87** [comment]
Added a PR. This kind of code isn't really nice so I hope we can remove it after ESR 102 has been released.

**Comment by gernotziegler** [comment]
@Mugen87 You are of course welcome to remove the detection code from three.js whenever you like; I only needed it for the museum and will keep it around in pages we create for them until they have upgraded their systems.

**Comment by Mugen87** [comment]
Let's see if @donmccurdy and @mrdoob are happy with the PR^^.
