### ISSUE TITLE
face.getMesh(rhino.MeshType.Any) return null 

### ISSUE THREAD

**Issue by leifriksheim** [mrdoob/three.js#23912]
Hi! I'm working with the rhino3dm.js library, trying to convert a Brep to a mesh so I can view it in Three.js.

I was looking at the implementation of the 3DMLoader and tried to use the same technique as referenced here:
https://github.com/mrdoob/three.js/blob/f0e2b3453f1412b53389beb04add414e3a80023c/examples/jsm/loaders/3DMLoader.js#L1196.

In my code I seem to only get null back from each face of the Brep. Do I need RhinoCompute for this function call?

**Comment by Mugen87** [comment]
/ping @fraguada Do you know the answer to this question?
