### ISSUE TITLE
`MeshNormalMaterial` does not support fog even though docs says it does.

### ISSUE THREAD

**Issue by FarazzShaikh** [mrdoob/three.js#23915]
**Describe the bug**

The docs mention `MeshNormalMaterial` supporting fog [here](https://threejs.org/docs/index.html?q=normal#api/en/materials/MeshNormalMaterial.fog) and even on the base `Material` class [here](https://threejs.org/docs/index.html?q=normal#api/en/materials/Material.fog). However, it does not support fog as evidant by the the [shader code](https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderLib/meshnormal.glsl.js) not having fog frgments as well as the app crashing if `fog: true` is set in the constructor.

**To Reproduce**

1. Create and add a mesh with this mateiral - `new MeshNormalMaterial({ fog: true })`
2. App will crash

***Code***

***Live example***

https://codesandbox.io/s/sweet-sound-7vi12e?file=/src/App.js

**Expected behavior**

The expected behaviour in the above example is the box on the right with the `MeshNormalMaterial` to be obscured by the fog like the box on left (with the `MeshPhongMaterial`)

**Screenshots**

**Platform:**

 - Device: [Laptop]
 - OS: [Windows]
 - Browser: [All]
 - Three.js version: [r0.139.2]

**Comment by Mugen87** [comment]
I think this is a misunderstanding. The default value of `fog` in the abstract material class is `true` to indicate fog support.

The `fog` property is documented in `MeshNormalMaterial` because the default value is overwritten with `false` indicating no fog support. For built-in materials `fog` is actually a read-only property which should not be changed by users.

**Comment by FarazzShaikh** [comment]
I see, can we instead add Fog support to Normal material? Is there a reason its left out?

**Comment by Mugen87** [comment]
> I see, can we instead add Fog support to Normal material?

The color of a normal material should not be affected by anything (tone mapping, color space conversion or fog).

>  If not we should handle the crash more gracefully

For now, I suggest to update the documentation for `MeshNormalMaterial`, `MeshDepthMaterial` and `MeshDistanceMaterial` and state the `fog` property is read-only and set to `false` to indicate no fog support.
