### ISSUE TITLE
ldraw example does not work in ff

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#23919]
Firefox 99.0.1 (64-bit) on Windows looks like this:
<img width="879" alt="Снимок экрана (238)" src="https://user-images.githubusercontent.com/242577/164189387-ad730e8d-b74b-4ea6-9115-1ad6ededf30b.png">

**Comment by Mugen87** [comment]
Looking good with Firefox 99.0.1 on macOS.

Can you please try it again? I've experienced a few GitHub backend issue this morning.

**Comment by Mugen87** [comment]
@makc Feel free to reopen the issue if the error happens again.

**Comment by makc** [comment]
> GitHub backend issue

ah right, there was 503. I only read package errors above, sorry.
