### ISSUE TITLE
GTLFExporter and Instanced Meshes

### ISSUE THREAD

**Issue by k2xl** [mrdoob/three.js#23916]
When exporting with GTLFExporter for an InstancedMesh, I have to traverse my mesh and create new meshes into a group and pass that into the GTLFExporter for it to work. If I pass my InstancedMesh directly it just shows the base geometry. Is there a way for GTLFExporter to work with InstancedMesh?

**Comment by takahirox** [comment]
Hi.

To export `InstancedMesh` as glTF, glTF [EXT_mesh_gpu_instancing](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_mesh_gpu_instancing) extension needs to be used. But Three.js `GLTFExporter` doesn't support the extension by default yet.

But there is an external `GLTFExporter` plugin for `EXT_mesh_gpu_instancing` exntension.

https://github.com/takahirox/three-gltf-extensions/tree/main/exporters/EXT_mesh_gpu_instancing

If you import it and register to your exporter, `InstancedMesh` will be exported with the extension.

The pluging is still testing phase. When it will be matured and others think it's ok, I may move the plugin into the official Three.js `GLTFExporter` as built-in plugin.

**Comment by k2xl** [comment]
Thanks @takahirox . Sounds promising. Unfortunately, it did not seem to work for me when trying that extension (I lose colors it seems). Even after adding it like so to your library:

```
...
for (let i = 0; i < node.count; i++) {
            node.getMatrixAt(i, mat);

            let p = new Vector3();
            let r = new Quaternion();
            let s = new Vector3();

            mat.decompose(p, r, s);
            let color = new THREE.Color();
            node.getColorAt(i, color);

            col0.push(color.r, color.g, color.b, color.a);
            pos0.push(p.x, p.y, p.z);
            rot0.push(r.x, r.y, r.z, r.w);
            scl0.push(s.x, s.y, s.z);
        };

        const pos = new Float32Array(pos0);
        const rot = new Float32Array(rot0);
        const scl = new Float32Array(scl0);

        extensionDef.attributes = {
            "TRANSLATION": writer.processAccessor(new BufferAttribute(pos, 3)),
            "ROTATION": writer.processAccessor(new BufferAttribute(rot, 4)),
            "SCALE": writer.processAccessor(new BufferAttribute(scl, 3)),
            // unsure if COLOR is the property to put here? what's the official way?
        };

        extensionsUsed[this.name] = true;

    }
    ```

**Comment by takahirox** [comment]
@k2xl Thanks for the problem report. Do you mind if filing an issue at https://github.com/takahirox/three-gltf-extensions/issues ? And we may close this issue for now.
