### ISSUE TITLE
Cannot read properties of undefined (reading 'distanceToCameraSquared')

### ISSUE THREAD

**Issue by Yenmozzi** [mrdoob/three.js#23913]
I'm new in threejs. Now i want to add a text to a mesh. First text to first Mesh, there is no problem. But continuously another text to another Mesh, console appears: Cannot read properties of undefined (reading 'distanceToCameraSquared')

I don't know how to fix this bug. Maybe someone can help. 

HIer is error:
 CSS2DRenderer.js?aea1:193 Uncaught TypeError: Cannot read properties of undefined (reading 'distanceToCameraSquared')
    at eval (CSS2DRenderer.js?aea1:193:1)
    at Array.sort (<anonymous>)
    at zOrder (CSS2DRenderer.js?aea1:190:1)
    at CSS2DRenderer.render (CSS2DRenderer.js?aea1:95:1)
    at VueComponent.animate (Model3D.vue?5936:202:1)

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
