### ISSUE TITLE
Allow "resizing" user in WebXR

### ISSUE THREAD

**Issue by bastecklein** [mrdoob/three.js#23910]
Suppose I have a scene in WebXR of a room that the player can walk around in.  Now suppose I want to press a button and become a fly on the wall of that room.  There does not seem to be a way to make the user seem smaller with respect to the size of the world, without actually scaling the rest of the scene.  Maybe I am just missing something, but it would be nice to be able to scale the VR user down to a tiny size (or a large size).

**Comment by Mugen87** [comment]
Why don't you just scale the scene?

**Comment by bastecklein** [comment]
Thanks, it didn't work right scaling the entire scene, but placing the camera inside of a group and scaling that seemed to work fine, so I will close the issue.  Thanks for pointing me in the right direction @Mugen87
