### ISSUE TITLE
Check exist image in texture before export

### ISSUE THREAD

**Issue by F1shez** [mrdoob/three.js#23929]
Sometimes the image may not be loaded into the texture and then there will be an error during export due to the missing image.
That's why when exporting object or object.toJson(), we can check for the presence of an image in the texture to avoid errors.
example :
`if ( this.map && this.map.isTexture ) data.map = this.map.toJSON( meta ).uuid;`
to
`if ( this.map && this.map.image &&  this.map.isTexture ) data.map = this.map.toJSON( meta ).uuid;`

**Comment by Mugen87** [comment]
We could implement such validation checks but I have the feeling this would go too far. For performance and readability reasons we try to minimize such code whenever possible.

Let's state that it is the responsibility of the application to ensure the asset is _fully_ loaded before calling `toJSON()`.
