### ISSUE TITLE
Model shadow error when `OES_texture_float` extension is unavailable

### ISSUE THREAD

**Issue by cenkai88** [mrdoob/three.js#23921]
**Describe the bug**

Shadow is rendered incorrectly (while the model itself is rendered as normal) when `OES_texture_float` extension is unavailable on some outdated or mobile platform.
Root cause:
The value of maxBone of different skinnedMesh objects is not consistent, in the rendering process of each frame, the check of `needsProgramChange` does not include maxBone. As a result, during generation of  skinnedMesh's shadowMap, the program is created for the first time and reused for all other skinnedMeshes. If some skinnedMesh has larger number of bones than the first program, data in boneMatrices will not be correctly passed to skin's shader(src/renderer/shaders/ShaderChunk/skinning_pars_vertex.glsl.js).

**To Reproduce**

1. Replace the model in `example/webgl_animation_skinning_additive_blending.html` with animated gltf model of multiple parts with different bone number.
2. Open the example on platform that `OES_texture_float` is not supported, or manually disable floatFragmentTextures in `src/renderer/webgl/WebGLCapabilitites.js`
3. See the incorrect shadow.

***Code***

Code to disable floatFragmentTextures:

```js
const floatFragmentTextures = !(isWebGL2 || extensions.has( 'OES_texture_float' ));
```

***Live example***
Sorry I cannot provided the live example since the model is restricted to share publicly.

**Expected behavior**

Shadow is rendered correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/13135428/164214213-cc0c81ea-95a4-4f5d-a129-65409e7cd7cb.png)

**Platform:**

 - Device: [Mobile]
 - OS: [Android]
 - Browser: [Other]
 - Three.js version: [dev]

**Comment by Mugen87** [comment]
@mrdoob Rather than fixing this issue how about we remove the old code path and only support skinning with float textures? Floating point (vertex) textures are support on all WebGL 2 devices and on _most_ WebGL 1 ones. That would allow use to completely remove the `getMaxBones()` code in `WebGLPrograms` and related code in the shaders and renderer.

Also see that we did not merge #20704, too.

**Comment by cenkai88** [comment]
Hi @Mugen87, thank you for your replay. As far as I know three.js is very popular in the development of mini programs(an environment provided by native app) which is common in China. Inside these environment, `OES_texture_float` extension does not have a ideal coverage on Android devices.

**Comment by cenkai88** [comment]
Hi @Mugen87, thank you for your replay. As far as I know three.js is very popular in the development of mini programs(an environment provided by native app) which is common in China. Inside these environment, `OES_texture_float` extension does not have a ideal coverage on Android devices.

**Comment by Mugen87** [comment]
We've talked about this topic in the past (meaning in context of WeChat). Wouldn't it be more productive to ask at the WeChat developers to improve WebGL 2 support? AFAICS, this is not only a device issue.

**Comment by cenkai88** [comment]
In my case, the bug happens on Alibaba's platform, not tested on WeChat yet. 
Yeah, we should push them to improve WebGL2 support but it may take time to achieve. 
Also I just checked caniuse.com, 7% of users still use platform without `OES_texture_float` extension.
