### ISSUE TITLE
How to get index from OBJLoader

### ISSUE THREAD

**Issue by xiaoyxue** [mrdoob/three.js#23924]
**Is your feature request related to a problem? Please describe.**
I use example/OBJLoader to parse obj model, and use traverse to get geometry info, but not get indices
only have position, normal, uv

**Describe the solution you'd like**
Is any one know how to get indices from it? And giving example is best

**Additional context**

<img width="845" alt="image" src="https://user-images.githubusercontent.com/14324742/164381520-3211cd4f-1057-490e-ad98-4f9744adcd1d.png">

**Comment by mrdoob** [comment]
We use GitHub issues to track confirmed bug reports and feature development.
If you need help, please use the [forum](https://discourse.threejs.org/), the [chat](https://discord.gg/HF4UdyF) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
