### ISSUE TITLE
Model load fail in iOS 11 because FileLoader use Promise.finally

### ISSUE THREAD

**Issue by gyq348097872** [mrdoob/three.js#23943]
Related issue:  https://github.com/mrdoob/three.js/pull/22925

Model load fail in iOS 11 because FileLoader use Promise.finally
iOS11 does not support Promise.finally, but in issue https://github.com/mrdoob/three.js/pull/22925, the FileLoader use Promise.finally to load, it means Three.js version higher than 136 can not work on iPhone which OS version below 11.2.

![图片](https://user-images.githubusercontent.com/24505486/165114567-98fbb30c-566f-47e1-9bd7-1be0f75da4bb.png)
<img width="1503" alt="图片" src="https://user-images.githubusercontent.com/24505486/165115629-06d4802c-6bfa-46de-9086-b30e485e3c28.png">

**Expected behavior**
optimize FileLoader without Promise.finally to make it work on low version iOS

**Platform:**

 - Device: iPhone7
 - OS:  iOS11
 - Browser: Safari
 - Three.js version: 0.139.2

**Comment by donmccurdy** [comment]
The number of iOS devices using versions this old is very small, we have to draw a line somewhere for support of old browsers, and iOS <11 seems firmly obsolete. If you need to support much older browsers it will be necessary (for this, and many other reasons) to transpile your application code or use polyfills (https://stackoverflow.com/a/53327815/1314762).
