### ISSUE TITLE
Texture wraps or wrapt changes will cause the map to fail

### ISSUE THREAD

**Issue by pai16858** [mrdoob/three.js#23941]
**Describe the bug**

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**To Reproduce**

1. Go to https://threejs.org/examples/?q=webgl_r#webgl_raycast_texture
2. change wrapS or warpT
3. See error
![image](https://user-images.githubusercontent.com/26533053/165105561-3127112d-0f29-415c-9ffe-6928f3586eef.png)

 - Three.js version: [dev, r139]

**Comment by Mugen87** [comment]
This issue has already been fixed on `dev` via #23808.

**Comment by Mugen87** [comment]
https://raw.githack.com/mrdoob/three.js/dev/examples/webgl_raycast_texture.html

**Comment by pai16858** [comment]
thank you very much
