### ISSUE TITLE
handle empty geometries in BufferGeometryUtils.mergeBufferGeometries()

### ISSUE THREAD

**Issue by fqd511** [mrdoob/three.js#23947]
Is there any chance that BufferGeometryUtils.mergeBufferGeometries can accept an empty array as its first parameter? Normally the array is not empty, but under some circumstances it is. And when that happens, the code will directly crush because BufferGeometryUtils.mergeBufferGeometries accesses the index attribute of its first element in here

https://github.com/mrdoob/three.js/blob/a24e9803738ce7aa571e0cea6a858ed0078a1004/examples/jsm/utils/BufferGeometryUtils.js#L116

**Comment by gkjohnson** [comment]
I think the user code should handle this. Why are you passing an empty array into the function?

**Comment by fqd511** [comment]
ok, that is reasonable
