### ISSUE TITLE
Clone objects with userData that isn't JSON encodable?

### ISSUE THREAD

**Issue by willstott101** [mrdoob/three.js#23956]
**Is your feature request related to a problem? Please describe.**

I cannot clone my scene (which I wanted to do for export purposes, see #23951) because my userData has got cyclic references in it. Now on the one hand I'd concede perhaps it shouldn't, but it does seem like an unnecessary limitation to me.

**Describe the solution you'd like**

A) An extra option to the clone/copy functions to toggle the copying of userData.
B) Use of [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) in environments that support it over `JSON.parse(JSON.stringify(x))`

I think I should have the time to implement one of these if they're likely to get merged.

**Describe alternatives you've considered**

Traversing and removing my userData before cloning, and then re-adding it.

**Comment by Mugen87** [comment]
I don't vote to support this use case. It's over-engineering. I would rather suggest to clarify the documentation.

https://threejs.org/docs/index.html#api/en/core/Object3D.userData

The docs already mentioned a limitation about functions. It should be no deal to enhance this section about cyclic references.

**Comment by willstott101** [comment]
It's not so much about cyclic references, though cyclic references are fairly unique in the fact that the thrown error just completely prevents cloning... it's more about the constraint on JSON serialization.

(Admittedly modern) standard types like `Set` and `Map` just get serialized to `{}` with `JSON.stringify`.

I agree that the extra option is over-engineering, but `structuredClone` is ECMAScript's native answer to this problem, can using it really be considered so?

I guess it would be a breaking change since functions would throw when cloning, rather than simply being ignored. But if three wants to try and deep-clone `userData` why would we not want to use the better, simpler and less hacky function for it? Is it just cause it's new and we don't want to have code that needs to fallback to JSON-cloning?

**Comment by LeviPesin** [comment]
> I agree that the extra option is over-engineering, but structuredClone is ECMAScript's native answer to this problem, can using it really be considered so?

How would you stringify an object using it?

**Comment by Mugen87** [comment]
Sorry, but this feature request is out of scope. `userData` fields should only be used for what you can encode to JSON and not with functions or (cyclic) object references. With that policy, `userData` is supported similar to glTF's `extras` field.

**Comment by wlinna** [comment]
@willstott101  Instead of traversing and removing the cyclical references, why not use Symbols as keys instead? Symbol keys are ignored by JSON.stringify
