### ISSUE TITLE
Would threejs merge gkjohnson posteffect branch in?

### ISSUE THREAD

**Issue by sdarpeng** [mrdoob/three.js#23979]
gkjohnson's posteffect branch solved many problems such as effect frame rate. And it has better integrating usage.
https://github.com/gkjohnson/threejs-sandbox

**Comment by donmccurdy** [comment]
It's mostly up to the maintainers of the code whether they prefer to work on it here or in another repository, assuming a feature is within the scope of three.js (like post-processing). As a project becomes more complex it may be easier to manage in a dedicated repository with a dedicated release cycle, which is totally fine.

So I'd defer to @gkjohnson or @vanruesc (author of https://github.com/pmndrs/postprocessing), but as they're currently using other repositories I'll assume that's their preference.
