### ISSUE TITLE
manual: korean docs shadows page doesn't showing 

### ISSUE THREAD

**Issue by nerdchanii** [mrdoob/three.js#23976]
**Describe the bug**
korean docs shadows page doesn't showing!..I didn't close the tag by mistake🥲

**To Reproduce**

1. Go to https://threejs.org/manual/#ko/shadows
2. See Error

***Code***

https://github.com/mrdoob/three.js/blob/1238a324e081752d9f66219252361f05f73594df/manual/ko/shadows.html#L3

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).
![image](https://user-images.githubusercontent.com/63002393/166102066-da15f0c7-2e15-4836-89a2-584e237a0dbd.png)

I will open PR, ASAP...!

**Comment by nerdchanii** [comment]
@Mugen87 Thanks!... and Sorry.. 🥲

**Comment by Mugen87** [comment]
Don't worry! Things like that happen all the time.
