### ISSUE TITLE
r140 and MAX_BONES

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#23980]
Some custom shaders run just fine in r139.
Now they don't.

![140_error](https://user-images.githubusercontent.com/11772787/166109172-32a8dfd5-02d0-4108-b6d6-762b0d682102.png)

**Comment by linbingquan** [comment]
Do you have a minimum reproducible test case?

**Comment by RemusMar** [comment]
> Do you have a minimum reproducible test case?

You really don't need one because MAX_BONES has been removed from the source code.
And is needed by both WebGL 1 & 2 for skinning:
**uniform mat4 bones[MAX_BONES];  // 1 matrix per bone**

But if you really need a working sample code, here is a r139 one:
https://necromanthus.com/Test/html5/Lara_shader.html

**Comment by linbingquan** [comment]
> You really don't need one because MAX_BONES has been removed from the source code.

https://github.com/mrdoob/three.js/pull/23928

**Comment by RemusMar** [comment]
> #23928

There are dozens/hundreds of samples similar with the one I gave you.
All of them don't work on r140 anymore.
As general rule: broken backwards compatibility = bad development.

**Comment by LeviPesin** [comment]
> As general rule: broken backwards compatibility = bad development.

No.

**Comment by RemusMar** [comment]
> > As general rule: broken backwards compatibility = bad development.
> 
> No.

Yes.
And most of the young people don't understand that.
But they will understand later ...

**Comment by mrdoob** [comment]
@Mugen87 Is this because now we need WebGL2 or floating point textures?

**Comment by Mugen87** [comment]
Custom materials often copy built-in shader code. If this code still refers to `MAX_BONES`, it will break with `r140` because the define does not exist anymore.

Copy built-in shader chunks is problematic since they can break in any release (whenever we refactor or change GLSL).

**Comment by LeviPesin** [comment]
That is a completely unrelated problem to this one. Please create a new issue for it.

**Comment by Mugen87** [comment]
@cloakd Please let you help at the forum first. If it turns out to be a bug in the engine, it's okay to file an issue at GitHub.

**Comment by WestLangley** [comment]
That error comes from `lodMax` in `PMREMGenerator` not being a whole number. PMREMs are now of a different size. You will get that error if you try to load a PMREM texture exported from an earlier three.js version, for example.
