### ISSUE TITLE
Problem with clipping in y-direction

### ISSUE THREAD

**Issue by h1Modeling** [mrdoob/three.js#23999]
**Describe the bug**

Clipping a scene with `renderer.clippingPlanes.push(new THREE.Plane(new THREE.Vector3(0, -1, 0), 0.5));` works as expected.
Doing the same with a clipping plane Normal `new THREE.Vector3(0, 1, 0)`, I would expect that Three shows the scene above y=0.5. 
However Three shows the whole scene.

**To Reproduce**

Look at js Fiddle:
https://jsfiddle.net/061zLx4e/

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/061zLx4e/)

**Expected behavior**

The scene gets clipped and everything above y=0.5 gets shown

**Screenshots**

Clipping with normal y=-1
![clippingBottom](https://user-images.githubusercontent.com/17990673/166420589-e505a7f0-3417-4c82-95fd-ad28b83cb4b6.jpg)

Clipping with normal y=1 (full Cube)
![clippingTop](https://user-images.githubusercontent.com/17990673/166420598-cbdf5e49-d101-4fc5-a8b5-cf4061d4cbf3.jpg)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [r140]

**Comment by Mugen87** [comment]
I think there is a misunderstanding about how planes are defined in 3D space (Hessian normal form). I suggest you always use an instance of `PlaneHelper` to see a visual representation of the (pure mathematical) plane definition.

The clipping plane is where it is supposed to be: https://jsfiddle.net/p7sLgrbk/1/

**Comment by h1Modeling** [comment]
Ah.. sorry for creating the issue and thanks for the clarification!
