### ISSUE TITLE
GLTFExporter output file size regression

### ISSUE THREAD

**Issue by elalish** [mrdoob/three.js#23995]
**Describe the bug**

Importing a glTF with jpeg textures and reexporting it is now causing a major bloat in file size compared to the original (~2.5x for DamagedHelmet). I'm pretty sure this is due to https://github.com/mrdoob/three.js/pull/23857, as we're now using the `convertToBlob` method of OffscreenCanvas instead of the `toBlob` method of Canvas. This feels like it might also be a Chrome bug? It is correctly outputting JPEGs of the proper dimensions, they are just much larger, like the quality setting is defaulting to something a lot higher than the usual 0.85. @donmccurdy @robertlong Thoughts? Our regression tests caught this in `<model-viewer>` when I tried to upgrade. 

**To Reproduce**

1. Go to the model-viewer [editor](https://modelviewer.dev/editor/) and select DamagedHelmet
2. Click on "Download Scene"
3. Open the zip and inspect DamagedHelmet.glb - note it is now 9.3MB

**Expected behavior**

The GLB should be ~4MB, similar to the 3.8MB original

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: r140

**Comment by robertlong** [comment]
It does sound like a Chrome bug but I think the best option is to only use OffscreenCanvas when in a WebWorker context, avoiding this code path entirely for the vast majority of users. I'll work on a patch. Thanks for catching this! I did not notice the large file size regression.

**Comment by robertlong** [comment]
It looks like Blink has a [default JPEG quality](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/image-encoders/image_encoder.cc;l=85;drc=52f06e6b43ff95eccf79e0a5df8d4d83c029130a;bpv=0;bpt=1) of 92% and [default WebP](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/image-encoders/image_encoder.cc;l=100;drc=52f06e6b43ff95eccf79e0a5df8d4d83c029130a;bpv=0;bpt=1) quality of 80%. And yeah for some reason this default quality is not being used when using `convertToBlob`. I can go ahead and use those defaults for those mimetypes if that makes sense? OffscreenCanvas really is only supported in Blink-powered engines right now and those defaults seem like good defaults for us to use for now.

**Comment by robertlong** [comment]
With these default quality levels, I'm only seeing a 4 byte difference between the DamagedHelmet using `Canvas.toBlob` and  `OffscreenCanvas.convertToBlob`. Not sure where the 4 bytes are being reduced 🤔 but I'd put that as acceptable.

![Screen Shot 2022-05-02 at 6 54 43 PM](https://user-images.githubusercontent.com/1753624/166394037-3a2c61b3-9273-41a6-918f-039e007653a7.png)

**Comment by robertlong** [comment]
I've made a patch available here https://github.com/mrdoob/three.js/pull/23998

**Comment by elalish** [comment]
Have you filed this issue on Chrome?
