### ISSUE TITLE
Translation: English Document exist, but Korean do not.

### ISSUE THREAD

**Issue by nerdchanii** [mrdoob/three.js#23994]
**Is your feature request related to a problem? Please describe.**

I often encounter blank pages while reading documents in Korean.

**Describe the solution you'd like**

Even if some of the documents are not translated, I think non-english documents should have all the documents like English documents.

**Describe alternatives you've considered**

So I'm going to copy English documents and put them in Korean documents folder to make Korean documents folder like English documents folder that has whole posses.

After that, I want to translate the files sequentially.

**Additional context**

This work will prevent Korean-speaking users from meeting blank pages.
Instead, they will meet an untranslated page.
I think that needed for korean people using three.js

Please refer to the screenshot below

When Language: en
![화면-기록-2022-05-03-오전-1 36 54](https://user-images.githubusercontent.com/63002393/166289607-41a0759c-50fb-4c6f-93f7-e2fe4a42d6e6.gif)

but when Language: ko,  some docuements of api or others 
![화면-기록-2022-05-03-오전-1 37 40](https://user-images.githubusercontent.com/63002393/166289594-7ea43f63-8395-4a64-b10a-51203a65bdee.gif)

**Comment by Mugen87** [comment]
Please use the existing issue #20683 for discussions about the Korean translation.

> So I'm going to copy English documents and put them in Korean documents folder to make Korean documents folder like English documents folder that has whole posses.

Please don't do that. We've agreed in the past to only add _translated_ documents and no "placeholders" anymore.

**Comment by nerdchanii** [comment]
Oh, I see. I understand!:-) thanks for your answer 👍
