### ISSUE TITLE
WebGLRenderTarget: Inconsistent output with UnsignedByteType + sRGBEncoding

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#24002]
**Describe the bug**

Using WebGLRenderTarget in a post-processing stack with `.type=UnsignedByteType` and `.encoding=sRGBEncoding` causes incorrect final output to canvas:

| type | encoding | result |
|------|----------|--------|
| uint8 | Linear-sRGB | <img width="200" alt="uint8_linear" src="https://user-images.githubusercontent.com/1848368/166557052-89acc07f-7807-4c8b-96c3-4a4af0e04876.png"> |
| float16 | Linear-sRGB | <img width="200" alt="float16_linear" src="https://user-images.githubusercontent.com/1848368/166557038-2ae42724-eace-4d20-9683-64602aad9eb2.png"> |
| uint8 | sRGB | <img width="200" alt="uint8_srgb" src="https://user-images.githubusercontent.com/1848368/166557074-1796aa53-db8f-4222-8f8d-4ee2c24f49f7.png"> |
| float16 | sRGB | <img width="200" alt="float16_srgb" src="https://user-images.githubusercontent.com/1848368/166557067-6b0f69bd-be8f-4b7b-9e84-0d272f58e69b.png"> |

More interestingly, the uint8/srgb output _flickers_ on my device — sometimes showing the expected color for a frame, but mostly showing the incorrect color. Reports in Discord suggest this issue may be specific to macOS devices with M1 chips.

**To Reproduce**

- https://jsfiddle.net/donmccurdy/ctvasr9p/

**Expected behavior**

Same background color as with other render target settings.

**Platform:**

 - Device: Desktop
 - OS: macOS Monterey 12.3.1 
 - GPU: Apple M1 Pro
 - Browser:
     - ✅ Safari (OK)
     - ❌ Chrome (BROKEN)
     - ❌ Firefox (BROKEN)
 - Three.js version: r140

**Comment by Mugen87** [comment]
I can not reproduce this on a Windows laptop with Chrome.

**Comment by donmccurdy** [comment]
Checked on iPhone and iPad, no issue there either... I'm gonna guess this could be an ANGLE problem? Any idea how to report that since it's Chrome + FF, just go through Chromium bug tracker?

**Comment by Mugen87** [comment]
> just go through Chromium bug tracker?

Yes, that should be the correct spot. There is a dedicated component `Internals>GPU>ANGLE` for such issues.

**Comment by Mugen87** [comment]
Tested the fiddle on an older iMac (Intel + AMD) today and can't reproduce in Chrome and Firefox.

**Comment by donmccurdy** [comment]
Reported to Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1329199&q=&can=2

**Comment by Mugen87** [comment]
Similar to #23968, this issue can be closed since it will be automatically fixed when ANGLE uses a Metal backend on M1 devices.
