### ISSUE TITLE
DracoLoader failed to load uv2

### ISSUE THREAD

**Issue by pbsmart** [mrdoob/three.js#24007]
In order to use the lightmap mesh, uv2 is required, but the dracoloader cannot load uv2 normally. I modified the default loading configuration, but the loaded uv2 is not normal
``` js
this.defaultAttributeIDs = {
			position: 'POSITION',
			normal: 'NORMAL',
			color: 'COLOR',
			uv: 'TEX_COORD',
			uv2: 'TEX_COORD1'
		};
		this.defaultAttributeTypes = {
			position: 'Float32Array',
			normal: 'Float32Array',
			color: 'Float32Array',
			uv: 'Float32Array',
			uv2: 'Float32Array'
		};
```
[[Cube.drc](https://discourse.threejs.org/uploads/short-url/ApS4qHryAao38Vdui4QYuuFWLdG.drc)](https://discourse.threejs.org/uploads/short-url/ApS4qHryAao38Vdui4QYuuFWLdG.drc)

**Comment by Mugen87** [comment]
Related: https://discourse.threejs.org/t/dracoloader-does-not-load-multiple-texture-coordinates/19678

According to https://github.com/google/draco/issues/119, it seems DRACO does support multiple set of UVs. Your suggested change looks fine to me. Would you be interested in making a PR?

**Comment by pbsmart** [comment]
> Related: https://discourse.threejs.org/t/dracoloader-does-not-load-multiple-texture-coordinates/19678
> 
> According to [google/draco#119](https://github.com/google/draco/issues/119), it seems DRACO does support multiple set of UVs. Your suggested change looks fine to me. Would you be interested in making a PR?

Sorry, after debugging, I found that the error of loading uv2 is due to Draco_ decoder. There may be a problem with the program encapsulated by wasm. I don't know C + + and can't solve this problem

**Comment by Mugen87** [comment]
Um, if the decoder does not support multiple uvs, we can't fix it in this repository. We just use the builds from https://github.com/google/draco.
