### ISSUE TITLE
CatmullRomCurve3.toJSON() works only once

### ISSUE THREAD

**Issue by HarlausG** [mrdoob/three.js#24010]
When you call scene.toJSON() a second time with CatmullRomCurve3, the toJSON() method is no longer recognized for CatmullRomCurve3, CatmullRomCurve3 prototype changes to Object from Curve

We should be able to call toJSON() with CatmullRomCurve3 several times

**Screenshots**
First execution 
![1](https://user-images.githubusercontent.com/73186172/166942646-f9bb6d54-d9ef-43c1-846e-80ca59d146af.PNG)
Second execution
![2](https://user-images.githubusercontent.com/73186172/166942657-260f021f-cf35-49a2-bceb-4db09ab5da62.PNG)

**Platform:**

 - Device: [Desktop,]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [dev, r140]

**Comment by Mugen87** [comment]
I can reproduce here: https://jsfiddle.net/4hvgLz58/1/
