### ISSUE TITLE
[misc] code redundancy of RGBELoader

### ISSUE THREAD

**Issue by deepkolos** [mrdoob/three.js#24017]
**Describe the bug**

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/RGBELoader.js#L442

<img width="846" alt="image" src="https://user-images.githubusercontent.com/12824616/167148681-746b46bf-6987-425f-b28e-01e7bfab193f.png">

it seem there is a useless switch case

***Code***

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r???]

**Comment by WestLangley** [comment]
Yes, there used to be more cases. Would you like to file a PR and fix it?

**Comment by deepkolos** [comment]
@WestLangley PR submitted
