### ISSUE TITLE
Object3D and Group take `name` as argument in constructor

### ISSUE THREAD

**Issue by nickzshen** [mrdoob/three.js#24020]
**Is your feature request related to a problem? Please describe.**
I often write lines such as
```
this.groupA = new Group();
```
and end up with numerous un-named groups in the scene graph upon inspection with the three js dev tools.

When I realize I should add names for debugging, the extra line for naming adds clutter e.g.
```
this.groupA = new Group();
this.groupA.name = 'Group A';
...
this.groupD = new Group();
this.groupD.name = 'Group D';
```

**Describe the solution you'd like**

I would like `Group` to take in `name?: string` as an optional argument.
```
this.groupA = new Group('Group A');
```

I am happy to make this change if we get agreement that this makes sense.

**Comment by Mugen87** [comment]
`Obect3D` has many properties. If you allow to set `name` via the constructor, one could argue to honor other properties, too. 

In the meanwhile, I would only add parameters to the constructor which represent a configuration that _should not be changeable_ after the object's creation. That is not true for the `name` property (and for most other properties in the project).

**Comment by donmccurdy** [comment]
It's also important to keep in mind that Object3D is the base class for many other things — [Mesh](https://threejs.org/docs/?q=mesh#api/en/objects/Mesh), [Points](https://threejs.org/docs/?q=mesh#api/en/objects/Points), [Line](https://threejs.org/docs/?q=line#api/en/objects/Line), etc. The standard constructor for most of those subclasses is `new Foo(geometry, material)`. I suspect that introducing a `name` parameter for Object3D would be a minor convenience for one case, that creates inconsistency and/or more complex downstream effects in other cases, and so would prefer to keep the Object3D constructor as-is.
