### ISSUE TITLE
Images being automatically resized (and having their quality ruined) when added to a scene

### ISSUE THREAD

**Issue by derekdinan** [mrdoob/three.js#24027]
**Describe the bug**

Images appear to automatically be resized which messes up the quality of the image. I have done some searching and came across both `sizeAttentuation` and `scale.set()` but have had no luck with either of them, alas.

***Code***

```js
function addPart(name) {
    var loader = new THREE.TextureLoader();
    let width, height;

    var texture = loader.load("textures/" + name + ".png", function(tex) {
        width = tex.image.width;
        height = tex.image.height;
    });

    var material = new THREE.SpriteMaterial({
        map: texture
    });
    var part = new THREE.Sprite(material);
    // I have tried both of these and neither work
    //part.sizeAttenuation = false;

    //part.scale.set(1, 1, 1);

    scene.add(part);
    objects.push(part);
}
```

**Screenshots**

![](https://i.imgur.com/1U5170h.png)

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome, Edge, possibly others
 - Three.js version: 0.139.2

**Comment by Mugen87** [comment]
You have to scale the sprites according to the image's dimensions. [webgl_sprites](https://threejs.org/examples/webgl_sprites.html) demonstrates how to do that (check the `render()` function for details)

Please use the [forum](https://discourse.threejs.org/) if you need more help.
