### ISSUE TITLE
Teleport example is broken on Meta Quest 2

### ISSUE THREAD

**Issue by richardanaya** [mrdoob/three.js#24033]
It seems to be offsetting my by strange amounts.

**Comment by ranaya-formant** [comment]
It seems like it only correctly teleports for the first teleport, but every subsequent teleport is wrong.

**Comment by richardanaya** [comment]
It seems like it's correct on the first teleport, but wrong ever subsequent teleport.

**Comment by richardanaya** [comment]
it would appear that the baseReferenceFrame needs to be cached initially and re-used there after instead of being retreived all the time.

**Comment by mrdoob** [comment]
@richardanaya Out of curiosity, why did you ignore the bug report template?

**Comment by richardanaya** [comment]
@mrdoob oh man, sorry, I completely blanked out seeing that, I think my brain was on autopilot thinking that it was just some generic text

**Comment by mrdoob** [comment]
@arodic The issue is that the current code doesn't take into account the current offset of the user.

**Comment by mrdoob** [comment]
@arodic This code only works when the user is at 0,0,0:

https://github.com/mrdoob/three.js/blob/3ac055ce6111b5a63cf81c081e3c5f5940fb4e6a/examples/webxr_vr_teleport.html#L106-L116

**Comment by richardanaya** [comment]
@arodic I noticed a second bug related to this example, the example will fail the second time that you enter into VR

1. enter into VR
2. teleport somewhere
3. exit VR
4. enter VR again
5. black screen

I saw this message on the debugger of oculus quest.

```
Failed to execute 'getViewerPose' on 'XRFrame': XRSpace and XRFrame sessions do not match.
```

**Comment by richardanaya** [comment]
@mrdoob I don't know who to communicate about these issues as they all seem related.

there seems to be a need for `customReferenceSpace` to be set to `null` each time you call a set session on WebXRManager.  Subsequent entering into VR seem be caching old session items.

**Comment by richardanaya** [comment]
It seems like even there's a bunch of event listeners that need to be disconnected on subsequent setSessions too

```
session.addEventListener( 'select', onSessionEvent );
session.addEventListener( 'selectstart', onSessionEvent );
session.addEventListener( 'selectend', onSessionEvent );
session.addEventListener( 'squeeze', onSessionEvent );
session.addEventListener( 'squeezestart', onSessionEvent );
session.addEventListener( 'squeezeend', onSessionEvent );
session.addEventListener( 'end', onSessionEnd );
session.addEventListener( 'inputsourceschange', onInputSourcesChange );
```
even if I null out that value on the second go through, while I do see the screen properly, something bogs down my scene to a halt i think due to lingering executions from the previous session

**Comment by arodic** [comment]
Sorry @mrdoob I accidentally muted this thread. Does #24058 fix strange offset issue as well as session re-entry @richardanaya?

**Comment by richardanaya** [comment]
Yes it does.
