### ISSUE TITLE
EXRLoader: Error thrown but file is supported

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#24042]
**Describe the bug**

For an .EXR file exported from Blender, THREE.EXRLoader throws this error:

https://github.com/mrdoob/three.js/blob/175871e1251b393f2b9ac1238b5f79fc0efe0c76/examples/jsm/loaders/EXRLoader.js#L2059-L2064

I tried to debug that further, but it turns out the image does load just fine if I comment out the error. Anything we can do to make this check more specific? Files attached below.

Original:

[CornellBox.exr.zip](https://github.com/mrdoob/three.js/files/8666501/CornellBox.exr.zip)

Preview:

![CornellBox_srgb](https://user-images.githubusercontent.com/1848368/167763081-3a6918b6-f3bd-4802-9505-429cdca520c1.png)

 - Three.js version: 0.136.x

**Comment by donmccurdy** [comment]
If it's OK I might just switch this line to a `console.warn` and let the loader continue? I'm not sure what part of the file it thinks might be unsupported.

**Comment by sciecode** [comment]
> If it's OK I might just switch this line to a `console.warn` and let the loader continue? I'm not sure what part of the file it thinks might be unsupported.

That won't be necessary. I've identified the problem: 

![image](https://user-images.githubusercontent.com/3927951/167925428-b9245e27-9a69-463a-99f9-a826ca0638e6.png)

File contains special-flag "longName" set, from [OpenEXR File Layout](https://openexr.readthedocs.io/en/latest/OpenEXRFileLayout.html#version-field) : 
![image](https://user-images.githubusercontent.com/3927951/167926454-85575bd6-26f1-43a5-9931-8b47722ade81.png)

The flag was mistakenly set as imperative throw, but we do handle it correctly on either instance. I'll remove it from blocklist shortly, as the other cases are indeed guaranteed errors.
