### ISSUE TITLE
OBJExporter: Support for text sprite exporting

### ISSUE THREAD

**Issue by saru-dev** [mrdoob/three.js#24052]
The OBJExporter is great but is or could there be a helper function to pre convert 2D text sprites to meshes for inclusion in exported OBJ files? 

This is to acknowledge the 2D text will no longer be oriented to camera.

**Comment by Mugen87** [comment]
No exporter supports sprites so far. Converting sprites to meshes and retain the exact scaling/size is tricky.

Can't you use plane meshes instead of sprites in the first place? You can orient a plane mesh towards the camera by executing the following line per frame (before you call `render()`):
```js
plane.quaternion.copy(camera.quaternion);
```

**Comment by Mugen87** [comment]
Closing. We can reconsider this issue if more users request a sprite->mesh converted.

**Comment by saru-dev** [comment]
Thanks this helped, hadn't considered alternative rendering process for text.
