### ISSUE TITLE
Docs: What does the WebGLRenderer "alpha" option actually do now?

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#24051]
**Is your feature request related to a problem? Please describe.**

The docs for the "alpha" option no longer align with the source.

**Describe the solution you'd like**

Update the docs to properly describe what's happening

**Describe alternatives you've considered**

--

**Additional context**

It looks like "alpha" is now always set the true when creating a canvas but the [WebGLBackground instance](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L336) is initialized with the user-passed alpha flag. Does alpha now just set whether the background can be cleared with a transparent alpha?

**Comment by Mugen87** [comment]
> What does the WebGLRenderer "alpha" option actually do now?

Details: #23230

The `alpha` parameter of `WebGLRenderer` controls the default clear alpha value now. This was done to ensure backwards-compatibility as good as possible. If the `alpha` parameter would be completely removed, users would need to use `WebGLRenderer.setClearAlpha()` or `WebGLRenderer.setClearColor()`.

**Comment by LeviPesin** [comment]
> This was done to ensure backwards-compatibility as good as possible. If the `alpha` parameter would be completely removed, users would need to use `WebGLRenderer.setClearAlpha()` or `WebGLRenderer.setClearColor()`.

Why not just deprecate it then?

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/23230#issuecomment-1013395826
