### ISSUE TITLE
Threejs Example Bug -> Duplication of pointers in Example -> VR / HandInput / Pointerclick

### ISSUE THREAD

**Issue by fabian-muff** [mrdoob/three.js#24055]
**Describe the bug**

When running the example with a HoloLens, the example works just fine. However, every pinch, there is a duplicate of the Pointer added somewhere in the scene. The duplicates are only visible, if you move the hand out of the view and back in view again. It seems, as if a click creates a duplicate somehow and adds this duplicate to the scene when the hand gets visible again. I didn't find the problem in the OculusHandPointerModel.js

**To Reproduce**

1. Go to the example on threejs.org VR / HandInput / Pointerclick and start the example. Play around by pinching and moving your hands in and out of view. 
2. Suddenly you will see additional pointers at random places. I did not find a pattern on where they are added to the scene and when exactly they get visible. 

**Expected behavior**

I would expect that there are no additional pointers floating around.

**Screenshots**

![image](https://user-images.githubusercontent.com/77620758/168287972-f7e521fa-3f2d-4d17-bf61-8d4688998fe9.png)
![20220513_145313_HoloLens](https://user-images.githubusercontent.com/77620758/168288015-b6227def-a432-4885-8780-fe1852b865b0.jpg)
![20220513_145155_HoloLens](https://user-images.githubusercontent.com/77620758/168288019-30e59eb0-ad29-42e5-a872-e888830d5c7d.jpg)

**Platform:**

 - Device: [HoloLens2]
 - OS: [Windows HoloLens]
 - Browser: [ Edge]
 - Three.js version: [what is used in the example. However, it happens also on my local dev on version 140]

**Comment by mrdoob** [comment]
@dmliao any ideas?

**Comment by dmliao** [comment]
hybridherbst's observations are correct: in Oculus Quest, we only send the `connected` event once, when we should be sending connected / disconnected events whenever hands go out of view. This behavior should be fixed on Oculus's end in the near(ish) future.

The example was made with the current Quest 2 behavior, so right now it creates a new pointer every time a `connected` event is fired -- to correct it, the pointer should only be created at the first `connected` event. I should have some time later this week to look at it / fix the example, but I don't have a Hololens so will need some help or extra time to verify.

**Comment by fabian-muff** [comment]
@dmliao I can test it on the HoloLens2 next week if that would help.
