### ISSUE TITLE
Creating a CubeTexture from 6 CompressedTextures doesn't work after r136

### ISSUE THREAD

**Issue by umar-ahmed** [mrdoob/three.js#24065]
**Describe the bug**

Prior to version `r136` of the library, creating a `CubeTexture` from 6 `CompressedTextures` used to work just fine. However, it seems like [this change](https://github.com/mrdoob/three.js/pull/22951) introduced in r136 changed the behaviour of how textures are loaded into the GPU when WebGL 2 APIs are available, which broke this use-case.

As a work-around, I have been able to get the cube texture to render by setting `texture.isVideoTexture = true` on the `CubeTexture`. According to [this line](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLTextures.js#L699), that forces Three to opt-out of using `texStorage2D` which seems to be causing the issue

***Code***

```js

const loader = new KTX2Loader()
    .setTranscoderPath( 'js/libs/basis/' )
    .detectSupport( renderer );

const textures = await Promise.all([
  loader.loadAsync( './textures/nx.ktx2' ),
  loader.loadAsync( './textures/px.ktx2' ),
  loader.loadAsync( './textures/ny.ktx2' ),
  loader.loadAsync( './textures/py.ktx2' ),
  loader.loadAsync( './textures/nz.ktx2' ),
  loader.loadAsync( './textures/pz.ktx2' )
]);

textures.forEach((texture) => {
  texture.generateMipmaps = false;
  texture.encoding = THREE.LinearEncoding;
  texture.needsUpdate = true;
});

const cubeTexture = new THREE.CubeTexture(textures);
cubeTexture.encoding = textures[0].encoding;
cubeTexture.format = textures[0].format;
cubeTexture.minFilter = textures[0].minFilter;
cubeTexture.magFilter = textures[0].magFilter;
cubeTexture.generateMipmaps = false;

// HACK: Setting `isVideoTexture` opts-out of using `texStorage2D`
cubeTexture.isVideoTexture = true;

cubeTexture.needsUpdate = true;

// Set scene background
scene.background = cubeTexture
```

***Live example***

* [CodeSandbox](https://codesandbox.io/s/vigilant-proskuriakova-5w6wf0?file=/src/Scene.jsx) (I'm using react-three-fiber, let me know if you want a vanilla Three.js version!)

**Expected behavior**

It should load the `CubeTexture` just fine as the scene background. Instead, the scene background is black and the following errors show in the console:

```
[.WebGL-0x700abe0a00] GL_INVALID_VALUE: Texture dimensions must all be greater than zero.
```

and 

```
[.WebGL-0x700abe0a00] GL_INVALID_OPERATION: Level of detail outside of range.
```

Upgrading to r140.2, also shows this added error:

```
THREE.WebGLTextures: sRGB encoded textures have to use RGBAFormat and UnsignedByteType.
```

**Screenshots**

<img width="665" alt="CleanShot 2022-05-15 at 10 56 44@2x" src="https://user-images.githubusercontent.com/8302959/168479347-3e56aa49-b936-47e9-8e25-0778a8295e64.png">

https://user-images.githubusercontent.com/8302959/168479550-cf0d681d-cd96-40a6-a816-18699047322b.mov

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: r136

**Comment by CodyJasonBennett** [comment]
Can confirm the issue is isolated to changes made in that PR.

Among them, this should be `state.texStorage2D( _gl.TEXTURE_CUBE_MAP, levels, glInternalFormat, cubeImage[0].mipmaps[ 0 ].width, cubeImage[0].mipmaps[ 0 ].height )`:

https://github.com/mrdoob/three.js/blob/5c70435ee8af07036b4d8d02354c047db3adc5e8/src/renderers/webgl/WebGLTextures.js#L1080-L1084

However, the cube texture is still unrenderable in this case (issues with mipmaps?). Setting `.isVideoTexture` to the cube texture will completely bypass this code path as a workaround.

**Comment by Mugen87** [comment]
> (I'm using react-three-fiber, let me know if you want a vanilla Three.js version!)

A vanilla version would be great! Ideally with `jsfiddle`.

> Among them, this should perhaps be state.texStorage2D( _gl.TEXTURE_CUBE_MAP, levels, glInternalFormat, cubeImage[0].mipmaps[ 0 ].width, cubeImage[0].mipmaps[ 0 ].height ):

There is an [example](https://threejs.org/examples/webgl_loader_texture_dds) that uses a compressed cube map and it works fine. Using `image.width` and `image.height` should work with all compressed textures. Otherwise the texture is has not been configured correctly.

**Comment by LeviPesin** [comment]
> There is an [example](https://threejs.org/examples/webgl_loader_texture_dds) that uses a compressed cube map and it works fine.

It does not quite work for me.
![Screenshot_20220516-190115_Samsung Internet](https://user-images.githubusercontent.com/35454228/168563486-5f39fe5c-80d6-49bf-a7b2-3d6fd9b751c9.jpg)
But I think this should be a separate issue?

**Comment by Mugen87** [comment]
Your platform probably does not fully support S3TC.

**Comment by donmccurdy** [comment]
> From my understanding, Three.js's KTX2Loader doesn't support loading cubemaps as a single file ...

Yeah, I guess this is something we should try to support, too. You're just using the cubemaps as backgrounds and not environment maps, correct? 

> THREE.WebGLTextures: sRGB encoded textures have to use RGBAFormat and UnsignedByteType.

Hm we must be using RGB_ETC2_Format and RGBA_ASTC_4x4_Format with sRGB encoding elsewhere... this warning may not be quite right?

**Comment by umar-ahmed** [comment]
> Yeah, I guess this is something we should try to support, too. You're just using the cubemaps as backgrounds and not environment maps, correct?

@donmccurdy That's correct. I'm just using it as a scene background.

> Hm we must be using RGB_ETC2_Format and RGBA_ASTC_4x4_Format with sRGB encoding elsewhere... this warning may not be quite right?

You know what, I think that error goes away when I set `texture.encoding = THREE.LinearEncoding;` on each of the 6 textures. That's probably just my bad since I'm new to the recent color management system changes

**Comment by donmccurdy** [comment]
A background texture probably should be sRGB though -- so I suspect your original code was right and the warning is incorrect for this case.

**Comment by Mugen87** [comment]
> THREE.WebGLTextures: sRGB encoded textures have to use RGBAFormat and UnsignedByteType.

This warning is generate in `WebGLTextures.verifyColorSpace()`. However, there is an early out for all compressed textures. So when `RGBA_ASTC_4x4_Format` is used in combination with `sRGBEncoding`, there is no warning and the renderer should pick `COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR`.

I think the main problem is that compressed cube textures also have to use `CompressedTexture` and not `CubeTexture`. So using `new THREE.CubeTexture(textures);` while `textures` is an array of compressed textures does not work. It's probably better to organize the cube texture similar to how `DDSLoader` produces is cube textures.

**Comment by donmccurdy** [comment]
Possible solution:

- https://github.com/mrdoob/three.js/pull/26369

**Comment by umar-ahmed** [comment]
Thanks @donmccurdy! That indeed does resolve my issue. I think composing the cube texture manually should be possible now. Although, it's probably best to load it as a single .ktx2 cubemap texture, which is now possible thanks to your work on the KTX2Loader to support that 🙏 .

Good to close this ticket out now.
