### ISSUE TITLE
Feature Request Bulk export .js to .gltf

### ISSUE THREAD

**Issue by mrtgray1234** [mrdoob/three.js#24072]
Looking to bulk export hundreds of .js files as .gltf files. Does anybody know if there is a way to accomplish this?

**Comment by donmccurdy** [comment]
three.js provides exporters like [THREE.GLTFExporter](https://threejs.org/docs/?q=gltfe#examples/en/exporters/GLTFExporter), you can export THREE.Scene instances that way. For help when using three.js we recommend the [forums](https://discourse.threejs.org/)
