### ISSUE TITLE
Move SVGLoader to source folder

### ISSUE THREAD

**Issue by arturjzapater** [mrdoob/three.js#24089]
**Is your feature request related to a problem? Please describe.**

It's not so much a problem as ease to find stuff and develop. There is an svg loader in the library, but you need to dig for it in the examples. Moreover, the loader is not documented. So to find it, you need to either think to look through the examples or search for solutions online, which will usually point to the loader in the examples folder.

**Describe the solution you'd like**

It'd be great if the svg loader were in the source folder with the other loaders and if it were described in the documentation.

**Comment by Mugen87** [comment]
The documentation of `SVGLoader` is here: https://threejs.org/docs/index.html#examples/en/loaders/SVGLoader

It was decided in previous discussions to not move loaders into the core.
