### ISSUE TITLE
Mesh raycast function problem

### ISSUE THREAD

**Issue by cnywt** [mrdoob/three.js#24083]
**Describe the bug**

When the BufferAttribute class uses the normalized attribute and is set to true; the raycast function of the Mesh class does not use the normalized Vector3 calculation synchronously
Describe the bug

**To Reproduce**
1、create a BufferGeometry width position attribute data not normailized
2、position BufferAttribute normalized attribute set to true;
3、render this geometry to scene and get it by Raycaster

**Comment by Mugen87** [comment]
Do you mind to properly fill out the issue template? Also please demonstrate the issue with a live example.

**Comment by cnywt** [comment]
Sorry, my English is so bad; so I hope to describe the problem briefly and directly;
This problem was encountered by me helping a stranger solve the inaccurate location of the gltf model by clicking on it, so I don't have an online demo for the time being;

**Comment by cnywt** [comment]
> When the BufferAttribute class uses the normalized attribute and is set to true; the raycast function of the Mesh class does not use the normalized Vector3 calculation synchronously

**Comment by Mugen87** [comment]
> create a BufferGeometry width position attribute data not normailized

What does that mean? How does the position data look like?

**Comment by cnywt** [comment]
> > create a BufferGeometry width position attribute data not normailized
> 
> What does that mean? How does the position data look like?

sorry for disturbing your mind，This refers to any position data that is not normalized，like:
   this triangle position const array= new Float32Array([100 ,100 ,100  ,100, 200,100 ,100, 100 ,200])；
if code like this :
  geometry.attribute.set("position",new BufferAttribute(array ,3 ,true));
then ：
If we obtain the mesh with this geometry through the ray, we will find that the obtained position is wrong

**Comment by Mugen87** [comment]
Your setup is actually not valid. The `normalized` attribute only applies to integer data, not float.

**Comment by cnywt** [comment]
> valid
I'm sorry, this was originally a problem in the gltf model. I used the wrong code for you to simulate. The InterleavedBufferAttribute is used in that gltf.


> Your setup is actually not valid. The `normalized` attribute only applies to integer data, not float.
I'm sorry, this was originally a problem in the gltf model. I used the wrong code for you to simulate. The InterleavedBufferAttribute is used in that gltf.

**Comment by cnywt** [comment]
> Your setup is actually not valid. The `normalized` attribute only applies to integer data, not float.

And thank you for letting me learn something new

**Comment by gkjohnson** [comment]
I think this is related to #22874. It's not valid for float buffers but right now if a position or uv attribute are normalized with integer data then raycasting will not return a correct result. cc @donmccurdy.

**Comment by Mugen87** [comment]
Even if it's a PR, it's better to follow the discussion at #22874. Marking this as a duplicate.
