### ISSUE TITLE
importmap gives Error on webgl_gpgpu_birds_gltf Example

### ISSUE THREAD

**Issue by matthiasulrich** [mrdoob/three.js#24088]
**Describe the bug**

Hi Folks
thanks for all the great examples. It's fun to look at them and play around with them a bit.

When I check the page with the W3C Validator, I get the following error message
Error: Bad value import mapping for the type attribute of the script element: Subtype is missing.

**To Reproduce**

1. Go to 'https://validator.w3.org/nu/?doc=https%3A%2F%2Fthreejs.org%2Fexamples%2Fwebgl_gpgpu_birds_gltf.html'
2. Check 'https://threejs.org/examples/webgl_gpgpu_birds_gltf.html'
3. See error

***Live example***

* [live example](https://threejs.org/examples/webgl_gpgpu_birds_gltf.html)

**Screenshots**
<img width="747" alt="Bildschirmfoto 2022-05-19 um 07 39 29" src="https://user-images.githubusercontent.com/12305781/169218392-0f9cfd8b-5092-4af0-8680-e9327439899b.png">

**Platform:**

 - Device: [Desktop]
 - OS: [Windows, MacOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [?]

**Comment by Mugen87** [comment]
This issue can be ignored, see https://github.com/systemjs/systemjs/issues/2085.
