### ISSUE TITLE
[Suggestion] Replace EventDispatcher with native EventTarget and CustomEvents

### ISSUE THREAD

**Issue by rediche** [mrdoob/three.js#24082]
**Is your feature request related to a problem? Please describe.**

The current EventDispatcher is lacking a lot of functionality that the native EventTarget supports, such as `.stopPropagation`.

**Describe the solution you'd like**

I suggest that the custom EventDispatcher is replaced and having classes like Object3D extend the native EventTarget instead.

This would affect the event objects currently being dispatched, because they would have to be replaced with CustomEvent instances instead.

This would be a breaking change.

As for browser support, then it is the following for extending [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget#browser_compatibility):

- Chrome: 64
- Edge: 79
- Firefox: 58
- Internet Explorer: None
- Safari: 14

**Describe alternatives you've considered**

Alternatively I think the EventDispatcher should be further developed to support relevant APIs like `.stopPropagation`.

**Additional context**

It was previously mentioned in  #12854, that it would be able to be removed "soon".

**Comment by Mugen87** [comment]
This topic was discussed again some time later in #18564. Because of https://github.com/mrdoob/three.js/pull/18564#issuecomment-584457877, the project did not head towards `CustomEvent` anymore.

**Comment by LeviPesin** [comment]
Here is the fiddle:
https://jsfiddle.net/xm3jnkzd/
Three is still about 20 times faster than native on Chrome.

**Comment by rediche** [comment]
I must admit I had completed missed that PR thread when looking into previous issues regarding this. The performance does look quite bad.

I checked the fiddle and it seems there have been quite some improvements on both Chrome and Firefox since the original test, but yes, it is still significantly worse.

```
Chrome:
native dispatch: 2.988037109375 ms
three dispatch: 0.47705078125 ms

Firefox:
native dispatch: 2ms - timer ended
three dispatch: 1ms - timer ended
```

I will close this issue, but I do think it's worth keeping an eye on any performance improvements that the browsers make over time, since the native events come with a lot of features which could significantly improve developer ergonomics.

**Comment by LeviPesin** [comment]
Now the difference is about 10x in my browser:
https://jsfiddle.net/auy1zfkr/1/

**Comment by LeviPesin** [comment]
Not sure if we send so many events so that there is a difference between 0.08 ms and 0.008...

**Comment by mrdoob** [comment]
10x here too... 🧐
