### ISSUE TITLE
Error with webgpu examples

### ISSUE THREAD

**Issue by jrjdavidson** [mrdoob/three.js#24103]
**Describe the bug**

webgpu examples are not loading on page

**To Reproduce**

1. Go to threejs.org/examples/?q=webgpu
2. Choose any example
3. See console

Console report error :
Uncaught ReferenceError: GPUShaderStage is not defined
    at WebGPUNodeBuilder.js:21:12
![image](https://user-images.githubusercontent.com/46798391/169734586-550d2ff3-383a-4897-a380-73f7ebca16b6.png)

**Platform:**

 -Desktop
 - OS: Windows
 - Browser: Chrome, Firefox

**Comment by LeviPesin** [comment]
Use a browser that supports WebGPU, e.g. Chrome with enable-unsafe-webgpu flag enabled.

**Comment by mrdoob** [comment]
I think the problem is that we're using Chrome's origin trial which, realistically, is not useful.

**Comment by mrdoob** [comment]
I've just removed the original trial meta tags locally and the problem is still there.
Looking into this...

**Comment by mrdoob** [comment]
This should solve it: https://github.com/mrdoob/three.js/commit/235e6c354f175f6a5aecc4db0341cc7056a3102a

**Comment by mrdoob** [comment]
Cherry-picked into `gh-pages`: https://github.com/mrdoob/three.js/commit/f2c5357b092c954ec14759753a15fcb6e6eb9693

**Comment by LeviPesin** [comment]
Does Pupeteer actually work now on WebGPU examples?

**Comment by mrdoob** [comment]
I don't think there's a way of using the latest Chrome Canary in Puppeteer so until the WebGPU API stabilizes it won't be able to work I think.

**Comment by LeviPesin** [comment]
But then why it fails now on the black screen with this change?

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/0df8940d046643bbb3859a9beca491356d95af8e 🤞

**Comment by LeviPesin** [comment]
> I don't think there's a way of using the latest Chrome Canary in Puppeteer so until the WebGPU API stabilizes it won't be able to work I think.

I actually think [there is?](https://github.com/puppeteer/puppeteer/blob/v14.1.1/docs/api.md#class-browserfetcher)

**Comment by LeviPesin** [comment]
And it is definitely possible to pass a flag there:
https://github.com/puppeteer/puppeteer/blob/v14.1.1/docs/api.md#puppeteerdefaultargsoptions
I can try to make a PR?

**Comment by mrdoob** [comment]
> I can try to make a PR?

👍

**Comment by jrjdavidson** [comment]
This is what I see now, at least now it's clear:
![image](https://user-images.githubusercontent.com/46798391/169907174-cf7daf51-e19a-4890-b891-8752126b65de.png)

and wow you guys move fast..
