### ISSUE TITLE
Vector3.angleTo() should be from 0 to 2 * Math.PI

### ISSUE THREAD

**Issue by manake** [mrdoob/three.js#24111]
This person explains this issue nicely:
https://stackoverflow.com/questions/62358681/three-js-vector-angleto-how-to-also-get-the-bigger-value

```
var v1 = new THREE.Vector3(0, 0, 1);
var v2 = new THREE.Vector3(1, 0, 0); // Expected Math.PI / 2
var v3 = new THREE.Vector3(-1, 0, 0); // Expected Math.PI * 3 / 2

v1.angleTo(v2)
1.5707963267948966

v1.angleTo(v3)
1.5707963267948966
```

https://github.com/mrdoob/three.js/blob/6e897f9a42d615403dfa812b45663149f2d2db3e/src/math/Vector3.js#L557

Another possibility is to have negative values from `new THREE.Vector3(0, 0, -1);` (exclusive, so it would be positive `Math.PI`) to `new THREE.Vector3(0, 0, 1);` (this is equal to `0` so neither negative nor positive).

**Comment by Mugen87** [comment]
I don't think we should change the method at this point. The assumption of `toAngle()` is totally valid. It the same like Unity's [Vector3.Angle](https://docs.unity3d.com/ScriptReference/Vector3.Angle.html):

> The angle returned will always be between 0 and 180 degrees, because the method returns the smallest angle between the vectors. 

If you need a method that measures the angle CCW or CW, you need a custom implementation.
