### ISSUE TITLE
Errors are not showing the shader code anymore after r140

### ISSUE THREAD

**Issue by marcofugaro** [mrdoob/three.js#24127]
**Describe the bug**
 
Since r140, if there is an error in a shader, the shader code is not logged in the error.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/7217420/170239008-957e33f9-ffbd-4383-b77d-2c750661d12d.png">

Before, all the shader code was logged, this was more useful in understanding the glsl issue.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/7217420/170239558-4a871d9b-66f9-404a-a36e-2948249f92f0.png">

I believe something changed in r139 as well, since only the relevant part of the code is logged in that release.

**To Reproduce**

1. Go to https://7nqxh6.csb.app/
2. Open console
3. No shader code logged

***Code***

Code for the example is here https://codesandbox.io/s/angry-ully-7nqxh6?file=/index.js

**Expected behavior**

Should log some shader code.

**Screenshots**

| r138 | r139 | r140 |
|-----|-------|------|
| <img width="482" alt="image" src="https://user-images.githubusercontent.com/7217420/170240657-4bd819a3-47a3-4fbe-a73e-a896fc028d65.png"> | <img width="483" alt="image" src="https://user-images.githubusercontent.com/7217420/170240147-d787ba6c-21bd-4aab-996e-7bac0eee553e.png"> | <img width="483" alt="image" src="https://user-images.githubusercontent.com/7217420/170240257-0a55844b-caab-4384-ab07-c214153f7168.png"> |

**Platform:**

 - Device: any
 - OS: any
 - Browser: any
 - Three.js version: r140

**Comment by LeviPesin** [comment]
Related: https://github.com/mrdoob/three.js/commit/9d61e463ea09f71edb285857590cbd92f24e2ce2
