### ISSUE TITLE
Unit scale factor

### ISSUE THREAD

**Issue by notghettolenny** [mrdoob/three.js#24123]
did not see UnitScaleFactor participating in the calculation in the FBXLoader code.

Expected behavior

Whether three.js can add a parameter like Unity's fbx model import can control whether to enable the model unit scaling factor.

Platform:

Device: [Desktop]
OS: [Windows]
Browser: [Chrome]
Three.js version: [ r120]

**Comment by Mugen87** [comment]
Duplicate of #20402.
