### ISSUE TITLE
Can scene data be added when compiling materials

### ISSUE THREAD

**Issue by kongxiaojian123** [mrdoob/three.js#24128]
https://github.com/mrdoob/three.js/blob/cf82659440266b66c7c8fa416d84f8f8b07bc3ab/src/renderers/WebGLRenderer.js#L1382-L1384

It may be used when writing custom shaders. For example, if you want to use  Scene.envMap, you must traverse all materials and then add envMap if you don't add Scene data. This is very inconvenient, so it is recommended to add scene data when compiling materials

**Comment by LeviPesin** [comment]
Do you mean passing `scene` as an arguments to these two functions?

**Comment by kongxiaojian123** [comment]
I have such a requirement. I need to use a `THREE.ShaderMaterial` and want to add an `environment map`, but I don't want to traverse every `material` and add an `environment map`.

I want to use the `environment` attribute of `scene`. This can be achieved by directly adding the `scene` to `material.onBuild` or `material.onBeforeCompile`,

If not, I can only add 'world envMap' through `material.onBeforeRender`. In this case, there will be repeated shader compilation, which will affect the performance of the page.

Why does repeated compilation occur?
- When I look at the `envMap` shader code, I find that it will inject the corresponding `#define` code according to the type of environment texture. As long as the `environment texture` is modified, it is likely that the shader will be recompiled due to different types, which will greatly affect the performance.

**Comment by kongxiaojian123** [comment]
> Do you mean passing `scene` as an argument to these two functions?

Yes, that's what I mean

**Comment by Mugen87** [comment]
`Scene.environment` just affects PBR materials (meaning `MeshStandardMaterial` and `MeshPhysicalMaterial`). An instance of `ShaderMaterial` is not necessarily physically correct and there is no way for the engine to detect this. Hence, there will be no `Scene.environment` support for custom materials.

**Comment by mrdoob** [comment]
Looks like we can create forms now... 😮
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by Mugen87** [comment]
A form is probably the best way to ensure the OP provides certain inputs. Especially if it's not possible to send the form without filling out mandatory fields first.

**Comment by kongxiaojian123** [comment]
> `Scene.environment` just affects PBR materials (meaning `MeshStandardMaterial` and `MeshPhysicalMaterial`). An instance of `ShaderMaterial` is not necessarily physically correct and there is no way for the engine to detect this. Hence, there will be no `Scene.environment` support for custom materials.

I want to make a plug-in for `blender` shaderNode export, which will use the world environment texture,
I want to customize the PBR material. I want to get the environment attribute of scene to initialize my customized PBR material,
If I don't add `scene` or `object` data, I can only implement it through `material.onBeforeRender`, which will lead to repeated compilation and affect the performance,
In addition, I think for custom shaders, all data should be given as much as possible during initialization to initialize custom shaders.
Also, I see that `object` data is added to `material.onBuild`. Why? I don't think it's enough to just import `renderer` data.

https://github.com/mrdoob/three.js/blob/cf82659440266b66c7c8fa416d84f8f8b07bc3ab/examples/jsm/renderers/webgl/nodes/WebGLNodes.js#L9

For a custom shader, you should give it more complete data during initialization, shouldn't you?

**Comment by Mugen87** [comment]
Normally you can't retrieve all information from the `parameters` object. It contains all data which are necessary to identify a shader program. Meaning also data from the renderer and the scene (like fog or output encoding).

`Scene.environment` is just not honored because you are using a shader material.

**Comment by kongxiaojian123** [comment]
OK, I can only pass in `envmap` through the `new` method or use `onbeforerender` to append `envmap`. Thanks.
