### ISSUE TITLE
PointerLockControls doesn't rotate horizontally

### ISSUE THREAD

**Issue by andrewchmr** [mrdoob/three.js#24148]
**Describe the bug**

It's not possible to rotate the camera horizontally (only vertically works)

**To Reproduce**

1) Setup PointerLockControls
2) Try to rotate the camera horizontally

***Live example***

https://threejs.org/examples/?q=pointerlo#misc_controls_pointerlock

**Expected behavior**

It should be possible to rotate horizontally

**Video**

https://user-images.githubusercontent.com/43907473/170771398-2f13b362-e5f5-49a9-9590-d74b620aa312.mp4

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome, Firefox, Safari
 - Three.js version: Reproducable on any version

**Comment by codednauk** [comment]
It does rotate horizontally and vertically via mouse movement.

**Comment by andrewchmr** [comment]
It started working for me after restarting my device 🤦‍♂️
