### ISSUE TITLE
Passing a spread empty array to `Object3D.add` should be noop.

### ISSUE THREAD

**Issue by jstoxrocky** [mrdoob/three.js#24147]
**Describe the bug**

Expectation:
Passing a spread empty array to `Object3D.add` should be noop.

Reality:
Throws with: `THREE.Object3D.add: object not an instance of THREE.Object3D. undefined`

***Code***

```js
const objsToAdd: THREE.Object3D[] = []
const obj = new Object3D()
obj.add(...objsToAdd) // should be noop not error
```

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/pull/24149#issuecomment-1140205563.
