### ISSUE TITLE
 Error: export 'XRRigidTransform' (imported as 'XRRigidTransform') was not found in 'three'

### ISSUE THREAD

**Issue by IRobot1** [mrdoob/three.js#24154]
Build fails when referencing XRRigidTransform from Angular project

```ts
import { XRInputSource, XRRigidTransform } from "three";
```

XRInputSource (interface) is found, but XRRigidTransform (class) is not.

 - Browser: [Edge]
 - Three.js version: [r140 or r141]

Any help is appreciated.

**Comment by CodyJasonBennett** [comment]
These are native WebXR APIs. If you're wanting to import types, I believe they've recently become ambient and are no longer exported.

**Comment by IRobot1** [comment]
Please provide link to forum

**Comment by Mugen87** [comment]
https://discourse.threejs.org/
