### ISSUE TITLE
Threejs editor  encoding bug?

### ISSUE THREAD

**Issue by RenderTool** [mrdoob/three.js#24156]
![THREEJS colorspace bug](https://user-images.githubusercontent.com/31579609/170934804-ce39ea7e-0b4a-4e1b-84f9-b9872ef43922.png)

**Comment by mrdoob** [comment]
Can you share the GLB file?

**Comment by mrdoob** [comment]
Maybe #24198 fixes this?

**Comment by Mugen87** [comment]
Closing. @RenderTool Feel free to reopen the issue if the problem still persists with the latest `dev` version.
