### ISSUE TITLE
Take use of static methods/properties

### ISSUE THREAD

**Issue by DaliborTrampota** [mrdoob/three.js#24155]
**Is your feature request related to a problem? Please describe.**

Its annoying to making the same vectors all the time, for example new Vector3(0, 0, 0) or new Vector3(1, 0, 0). I propose to add a static properties on Vector3 class: ZERO, FORWARD, RIGHT, UP
also I dont understand why Vector3.random has to be on already existing vector instance when it overwrites its components. I cant do new Vector3().random() because of immediate value error. yes I could wrap it into a parenthesis but thats really ugly. Better solution would be Vector3.random() and Vector3.randomDirection()

Other classes should take use of static keyword as well.

**Describe the solution you'd like**

Add a static properties into Vector3 class: ZERO, FORWARD, RIGHT, UP and methods: random(), randomDirection()

**Describe alternatives you've considered**

for the static properties, I currently have them in a constants file but the issue with that is that I have to clone them which is also not ideal

(also id appreciate if the isVector3 property on vector3 was hidden, that can be hidden in console log by using Object.defineProperty)

**Comment by mrdoob** [comment]
So the API would look like this?

```js
camera.position.set( THREE.Vector3.RIGHT );
camera.lookAt( THREE.Vector3.ZERO );
```

**Comment by mrdoob** [comment]
> (also id appreciate if the isVector3 property on vector3 was hidden, that can be hidden in console log by using Object.defineProperty)

https://github.com/mrdoob/three.js/issues/24006

**Comment by DaliborTrampota** [comment]
> So the API would look like this?
> 
> ```js
> camera.position.set( THREE.Vector3.RIGHT );
> camera.lookAt( THREE.Vector3.ZERO );
> ```

Exactly but not for this use cases of course :)

**Comment by mrdoob** [comment]
Not that use case? I guess I'm not following then...
Do you mind elaborating a little bit more your proposal?

**Comment by DaliborTrampota** [comment]
you got it right it just not want I want to use this for. not for setting positions. My proposal is like you wrote 
THREE.Vector3.RIGHT = new Vector3(1, 0, 0)
THREE.Vector3.ZERO = new Vector3(0, 0, 0)

**Comment by mrdoob** [comment]
So what do you want to use it for? The more we can relate with your use case the better.

**Comment by DaliborTrampota** [comment]
![image](https://user-images.githubusercontent.com/31895316/170943615-80d3300b-df2a-4fa2-b390-9400eb288517.png)
![image](https://user-images.githubusercontent.com/31895316/170943665-dd0e26ee-0978-40a6-904f-dc161f8c6c11.png)

this is how I use it now. its okay but could be better by using the static properties and I would not need to clone it every time

**Comment by mrdoob** [comment]
I think `UP.clone()` looks better than `THREE.Vector3.UP.clone()`.

**Comment by mrdoob** [comment]
Actually, static classes may not be what you mean.

This may be better?

```js
import { RIGHT, UP, FORWARD, ZERO } from 'src/math/Vector3.js';
```

**Comment by DaliborTrampota** [comment]
yes ^^thats what I was about to write you

**Comment by DaliborTrampota** [comment]
Id import it directly from the vector and I wouldnt have to clone it up since those static properties would call new Vector3() in there anyway

**Comment by mrdoob** [comment]
Hmm... That's not what you said on a previous comment:

> you got it right it just not want I want to use this for. not for setting positions. My proposal is like you wrote
>
> THREE.Vector3.RIGHT = new Vector3(1, 0, 0)
> THREE.Vector3.ZERO = new Vector3(0, 0, 0)

Seems like it's not clear what you want. Neither it's not clear how this will benefit others.

**Comment by DaliborTrampota** [comment]
`import { RIGHT, UP, FORWARD, ZERO } from './src/math/Vector3.js';`

Is this already implemented? Is this part of THREE.Vector3? Or is that some helper class/file? and how would I import it using the skypack? I import vector like so
`import { Vector3 } from 'https://cdn.skypack.dev/three@0.141.0'`

**Comment by mrdoob** [comment]
```c#
using UnityEngine;
using System.Collections;

public class ExampleClass : MonoBehaviour
{
    void Example()
    {
        transform.position += Vector3.forward * Time.deltaTime;
    }
}
```

Sorry but JavaScript doesn't support that.

**Comment by DaliborTrampota** [comment]
It can be implemented using static getter I does support that...

**Comment by mrdoob** [comment]
The closest thing I can think of would be something like this...

```js
// init
const vector = new THREE.Vector3();

// update
mesh.position.add( vector.makeForward( deltaTime ) );
```

So we could add `makeForward( scalar )`, `makeUp( scalar )`, etc

**Comment by mrdoob** [comment]
> It can be implemented using static getter I does support that...

Oh, sounds like you already know how to do it. Feel free to make a PR with your solution 🙏

**Comment by DaliborTrampota** [comment]
I think you misunderstood. Its not about the operations. Its about the vector.forward
Yes js doesnt support defining operations and operators. The whole time i was talking about a way to get new vector created which is facing up, right or forward as those are most common vectors and its useful to have them easily accesible. And I said new because without them being new each time ait would get modified by the methods.
