### ISSUE TITLE
Default fiddle link in issue template has a module resolution error

### ISSUE THREAD

**Issue by kumavis** [mrdoob/three.js#24173]
> "TypeError: Error resolving module specifier “three”. Relative module specifiers must start with “./”, “../” or “/”."

coming from `"https://threejs.org/examples/jsm/controls/OrbitControls.js";`

fiddle link https://jsfiddle.net/c5m1kazu/ appears in issue template
https://github.com/mrdoob/three.js/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Mugen87** [comment]
Thanks for reporting! Should be fixed now!
