### ISSUE TITLE
THREE.Quaternion is not a constructor

### ISSUE THREAD

**Issue by Jodelopa** [mrdoob/three.js#24187]
hello,
im using npm package "photo-sphere-viewer" in my ract project which depents on threejs.
if i update to react-scripts 5.0.1 i get following error messagen:

Uncaught TypeError: THREE.Quaternion is not a constructor
    at photo-sphere-viewer.js:1877:1

the autor of photo-sphere-viewer cant do anything about th error and i have no clue if im right here or if this is a webpack/react-scripts related problem

my package json:
      "photo-sphere-viewer": "^4.6.3",
       "react": "^17.0.2",
       "react-app-polyfill": "^2.0.0",
       "react-dom": "^17.0.2",
       "react-scripts": "^5.0.1",
       "typescript": "^4.7.2"

tsconfig:
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "target": "ES2017",
        "lib": [
            "DOM",
            "DOM.Iterable",
            "ESNext"
        ],
        "allowJs": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noFallthroughCasesInSwitch": true,
        "module": "ESNext",
        "moduleResolution": "Node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "noEmit": true,
        "jsx": "react-jsx"
    },
    "include": [
        "src"
    ]
}

**Comment by LeviPesin** [comment]
I am sure this is not a problem in three.js.

**Comment by Mugen87** [comment]
Please file an issue at the repository of the `npm` package that causes this issue. In this case, `photo-sphere-viewer`.

**Comment by Mugen87** [comment]
No, this issue is not related to the `three.js` repo. I suggest you ask at stackoverflow for help.
