### ISSUE TITLE
Multi-sample Anti-Aliasing cause scene crash on iOS15.4 & 15.5

### ISSUE THREAD

**Issue by Pannic17** [mrdoob/three.js#24188]
**Describe the bug**

When using SSAA and WebGLMultiSampleRenderTarget, in iOS15.4 & 15.5, the scene would show nothing. It was said to be the bug of WebKit that occurs in iOS15.4 and fixed in 15.5. But for my project, the bug remains in iOS15.5

**To Reproduce**

Add SSAA pass from /examples
or Using WebGLMultiSampleRenderTarget for composer render target

***Live example***

https://kaiwu-3d-9g0wg9pse8c68a97-1308399957.ap-shanghai.app.tcloudbase.com/#/viewer?url=https://test-1308399957.cos.ap-shanghai.myqcloud.com/models/KW00110000/KW00110000.json&type=2

**Expected behavior**

using WebGLRenderer's default aa is a expected result. We would expect same aa effect when using post processing.

**Platform:**

 - Device: [Desktop, **Mobile**]
 - OS: [Windows, MacOS, Linux, Android, **iOS**]
 - Browser: [**Chrome**, Firefox, **Safari**, Edge]
 - Three.js version: [dev, **r136**]

**Comment by Mugen87** [comment]
`WebGLMultiSampleRenderTarget` has been deprecated and we do not support outdated `three.js` versions. Please upgrade to `r141` and see if the issue happens again.

BTW: I don't think it make sense to use SSAA and MSAA at the same time.

**Comment by Mugen87** [comment]
> However, it seems like that it doesn't apply to the render composer when using EffectComposer.

The default MSAA enabled by `antialias: true` only works if you directly render to screen.

Try to create `EffectComposer` with custom multisampled render target similar to [webgl2_multisampled_renderbuffers](https://threejs.org/examples/#webgl2_multisampled_renderbuffers).
