### ISSUE TITLE
DDS Loader fails on trying to load dds texture with DX9/DX10+ header encoding.

### ISSUE THREAD

**Issue by winutta** [mrdoob/three.js#24189]
**Unable to load dds with ddsloader**

I am trying to load a envmap dds file but am getting the errors:
“THREE.DDSLoader.parse: Unsupported FourCC code” with the DX9 version
or
“THREE.DDSLoader.parse: Unsupported FourCC code DX10” with the DX10 version
these are the two options provided by the program I am using to export.

Is there any way to load this kind of file in threejs? Is this something the loader needs new functionality to handle?

I would appreciate any help, thanks.

**To Reproduce**

Here is a reproduced example codepen to show the error I am facing. Using the latest version 0.141.0 https://codepen.io/lablr/pen/MWQXGYy

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [0.141.0]

**Comment by donmccurdy** [comment]
/cc @LeviPesin – it looks like you made the most recent updates to DDSLoader, any thoughts on supporting BC6H cubemaps there? 

It's on my to-do list to add BC6H support to KTX2Loader, since the format is helpful for compressed envmaps and lightmaps, but it may be a while before I can start to work on that.

**Comment by donmccurdy** [comment]
Oh, hah – it turns out macOS Preview can open the file and convert to OpenEXR by itself. The file looks "the same" before/after in Preview to me, is this what you expect? I've exported a PNG preview as well, which won't contain the original HDR data, but is visible in github comments:

[bit_bc6h_dx10_cube_specular.zip](https://github.com/mrdoob/three.js/files/8833175/bit_bc6h_dx10_cube_specular.zip)

<img width="954" alt="Screen Shot 2022-06-03 at 10 58 09 AM" src="https://user-images.githubusercontent.com/1848368/171879650-8873a565-95a7-4bd5-af2f-f4e1df3300d3.png">

**Comment by donmccurdy** [comment]
It doesn't look to me like this EXR version contains mipmaps. I think the EXR format supports them, but if the original DDS file had mipmaps then perhaps Preview has ignored them. I guess Preview is not a very robust conversion tool for graphics data. 🥲

**Comment by donmccurdy** [comment]
After checking the files you shared earlier on Discord, OpenImageIO can only read the 8-bit version of the DDS file. OIIO does support 16-bit and 32-bit for other formats so I'm not sure why it has trouble with the DDS version. It does see the mipmaps in the 8-bit version too. But unfortunately 8 bits won't be enough for a correct HDR-to-HDR conversion.

**Comment by donmccurdy** [comment]
> I guess you were trying to convert to another format using enough data to still be HDR, because the dds cubemap isnt supported at this point. Am I understanding correctly?

Yeah, I was hoping I could find a DDS version that (a) OpenImageIO could read, and (b) was still HDR, so we could convert this to a more manageable format.  No luck so far.

I'll defer to @LeviPesin and @Mugen87 on whether cubemap support is something we'd want to (or can) add to DDSLoader.

**Comment by LeviPesin** [comment]
> /cc @LeviPesin – it looks like you made the most recent updates to DDSLoader, any thoughts on supporting BC6H cubemaps there?

I was just fixing a broken check there, sorry. I do not know much about it...

**Comment by Mugen87** [comment]
@donmccurdy I can set this point on my todo list. At least it's worth an investigation since this topic is related to #9688.

@winutta Are you fine when I use your S3TC texture for tests and maybe an official example?

**Comment by Mugen87** [comment]
I've hacked around a bit in the last days but I'm not having a good feeling to implement loader code without a reference 😓 . Does somebody know a better documentation than the [Programming Guide for DDS](https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dx-graphics-dds-pguide) that covers the processing of formats like  `DXGI_FORMAT_R32G32B32A32_FLOAT`? I don't get the final colors right and I assume there is something wrong when extracting the data from the DDS file.

**Comment by donmccurdy** [comment]
Related:

- https://github.com/KhronosGroup/KTX-Software/issues/92
- https://github.com/microsoft/DirectXTex
- https://github.com/KhronosGroup/BC6H-Decoder-WASM

**Comment by Mugen87** [comment]
According to [Unpacking and Packing DXGI_FORMAT for In-Place Image Editing](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-unpacking-packing-dxgi-format) there is a way to extract the raw data from textures but it requires the usage of DirectXTex. 

To be clear, the S3TC support in WebGL is limited on a bunch of formats related to DXT1, DXT3, DXT5 (e.g. `COMPRESSED_RGBA_S3TC_DXT5_EXT`). If we want to load a texture in the `DXGI_FORMAT_R32G32B32A32_FLOAT` format, it's necessary to extract the raw floating point data and produce an uncompressed RGBA texture. However, the extracting/reading is meant to be done with DirectXTex.

So there is the option to rewrite the code based on DirectXTex's implementation or use DirectXTex somewhow in the browser (not sure that is supported at all).

Not sure it's worth the effort if we could redirect the users to other formats.

**Comment by mrdoob** [comment]
Is it time to remove the loader and examples from the repo?

**Comment by Mugen87** [comment]
I've seen the usage of `DDSLoader` quite often in the past so I would not recommend to remove it at this point. Instead, I would suggest the following:

- Define that `DDSLoader` only supports the DDS formats specified in WebGL extensions `WEBGL_compressed_texture_s3tc` and `WEBGL_compressed_texture_s3tc_srgb`. That is already the case so there is no need to further enhance `DDSLoader`.
- Wait until KTX2 is more established and then eventually remove `DDSLoader` and `PVRLoader`.

**Comment by mrdoob** [comment]
That sounds good to me 👍

**Comment by donmccurdy** [comment]
Perhaps we also mark it deprecated [like BasisTextureLoader](https://github.com/mrdoob/three.js/blob/ae284fa425c096f061940b0d8821f662c2998d65/examples/jsm/loaders/BasisTextureLoader.js#L51-L56)? Users can let us know if it provides something the other loaders currently do not.

**Comment by mrdoob** [comment]
That also sounds good 👍👍

**Comment by Mugen87** [comment]
> Perhaps we also mark it deprecated [like BasisTextureLoader](https://github.com/mrdoob/three.js/blob/ae284fa425c096f061940b0d8821f662c2998d65/examples/jsm/loaders/BasisTextureLoader.js#L51-L56)? Users can let us know if it provides something the other loaders currently do not.

How would users convert existing DDS or PVR files to KTX2? Are there tools for doing this?

**Comment by donmccurdy** [comment]
I'm not sure what authoring tools can read DDS or PVR files at all, much less convert them to something else. Given these are older formats, there may not be much to look forward to there.  😢 

I'd keep an eye on https://github.com/KhronosGroup/KTX-Software/issues/92, beyond that OpenImageIO is probably the best tool to investigate, but its DDS support is incomplete as described above.
