### ISSUE TITLE
example broken - WebGPU Sprites

### ISSUE THREAD

**Issue by kumavis** [mrdoob/three.js#24184]
this example is broken https://threejs.org/examples/?q=sprite#webgpu_sprites

example src imports a number of things not exported by the imported nodes/Nodes.js
https://github.com/mrdoob/three.js/blob/0c26bb4bb8220126447c8373154ac045588441de/examples/webgpu_sprites.html#L30
https://github.com/mrdoob/three.js/blob/0c26bb4bb8220126447c8373154ac045588441de/examples/webgpu_sprites.html#L20
https://github.com/mrdoob/three.js/blob/f3888fd5270206abe540e602cdbad166df608abc/examples/jsm/nodes/Nodes.js#L207-L301

**Comment by mrdoob** [comment]
Broken? Seems to work here without problems:

<img width="1376" alt="Screen Shot 2022-06-03 at 3 47 56 PM" src="https://user-images.githubusercontent.com/97088/171802051-ec0f3e37-2f5a-400f-af22-90650a5efe9c.png">

**Comment by Mugen87** [comment]
Works for me, too.

**Comment by mrdoob** [comment]
Closing for now...

**Comment by kumavis** [comment]
on chrome i get `webgpu_sprites.html:169 Error: No WebGPU support`
but on firefox i get `Uncaught SyntaxError: import not found: mul`

**Comment by kumavis** [comment]
![image](https://user-images.githubusercontent.com/1474978/172026119-ea488613-9fab-40ad-a2ef-b8927472dd5d.png)

**Comment by LeviPesin** [comment]
Maybe importmap polyfill somehow breaks with `export * from ...`?

**Comment by kumavis** [comment]
as far as i cant tell the content is being loaded correctly (the fetched strings look correct)

**Comment by kumavis** [comment]
doesnt really make sense, seems like it should work
```js
import(/*'three-nodes/Nodes.js'*/'blob:https://threejs.org/7ff8e24b-0490-4813-8dc6-7dde20d31569').then(m => console.log(Object.keys(m).includes('mul')))
//=> Uncaught (in promise) SyntaxError: import not found: mul

import(/*'./shadernode/ShaderNodeElements.js'*/'blob:https://threejs.org/cbf9541d-01e8-4c5d-8af3-dece2fab91aa').then(m => console.log(Object.keys(m).includes('mul')))
//=> Uncaught (in promise) SyntaxError: import not found: mul

import(/*'./ShaderNodeBaseElements.js'*/'blob:https://threejs.org/f803a14a-2079-4a79-9acd-ddfba56d94ad').then(m => console.log(Object.keys(m).includes('mul')))
//=> true
```

**Comment by kumavis** [comment]
i will add that multiple `import *` or multiple `export *` in the same namespace is a recipe for confusion, because its unclear if an element in the first is shadowed by an element in the second.

**Comment by kumavis** [comment]
@mrdoob @Mugen87 please reopen

**Comment by kumavis** [comment]
broken on firefox 100.0.1

**Comment by kumavis** [comment]
still broken on 101.0

**Comment by mrdoob** [comment]
Please, report the issue to Mozilla instead.

**Comment by kumavis** [comment]
not necessarily a mozilla problem. could be an issue with circular deps

**Comment by mrdoob** [comment]
Please, report the issue to Mozilla.
