### ISSUE TITLE
css3DSprite LOD bug

### ISSUE THREAD

**Issue by Suprhimp** [mrdoob/three.js#24196]
**Describe the bug**

setting cssSprite with LOD, wherever camera far from the LOD object, it dose not change level.
If I turn off auto update and update LOD with manually, it works well!

I have to do this
` 
   scene.traverse((child) => {
      if (child instanceof THREE.LOD) {
        child.update(camera);
      }
    });
`

**To Reproduce**

my code was this (it dose not update)

```
      const image = document.createElement('img');
      let object: CSS3DSprite;
      const spriteLOD = new THREE.LOD();

      image.addEventListener('load', function () {
        object = new CSS3DSprite(image);
        object.scale.set(0.005, 0.005, 0.005);
        image.remove();
        spriteLOD.addLevel(object, 10);
      });
      image.src = IcContentMagnify;
      const midXYZ = new THREE.Vector3().addVectors(box?.max, box.min);

      spriteLOD.addLevel(new THREE.Mesh(), 12);

      spriteLOD.userData['event'] = clonedChild.userData['event'];

      spriteLOD.applyMatrix4(clonedChild.matrixWorld);
      spriteLOD.position.add(midXYZ);

      cssScene.add(spriteLOD);
      console.log(cssScene);
      // spriteLOD.autoUpdate = false;   // I have to turn off autoUpdate!
```

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: 0.141

**Comment by Suprhimp** [comment]
I tested with new version and I checked it works well :)

thanks for comment!

**Comment by 19940901** [comment]
> CSS3DRenderer

Hi. Is there a new version for CSS2DRender?
