### ISSUE TITLE
TransformControls translate 2D pane gets invisible near canvas Border

### ISSUE THREAD

**Issue by deethee** [mrdoob/three.js#24208]
![transformcontrol1](https://user-images.githubusercontent.com/2727230/172599043-a48aa18e-6534-46fa-9c33-807d2a89445b.PNG)
![transformcontrol2](https://user-images.githubusercontent.com/2727230/172599053-028bdc60-5ef1-4a7a-b5d1-bd9b01cfc800.PNG)

This happens in combination with an Orthographic camera and Orbit Controls only.
I can see the effect in realtime. If I pan the camera the yellow pane disappears if translation handles are close to canvas border.

The rest of the handles work ok.

This happens in Three 124 but the latest version is buggy there also.

This is dependent on zoom also. If you are further out the pane is only visible in center of canvas. Is this related to clipping?

**Comment by LeviPesin** [comment]
Can you make a JS fiddle reproducing the issue?

**Comment by deethee** [comment]
https://threejs.org/examples/#misc_controls_transform

Take the example, press c to switch to orthographic camera, zoom out using the mouse wheel. Than use the right mouse button to pan the camera. You will notice the the translation panes are randomly disappearing.

**Comment by Mugen87** [comment]
I'm afraid I can't reproduce the issue. Do you mind showing in a video what you are doing to produce the glitch?

**Comment by arodic** [comment]
> https://threejs.org/examples/#misc_controls_transform
> 
> Take the example, press c to switch to orthographic camera, zoom out using the mouse wheel. Than use the right mouse button to pan the camera. You will notice the the translation panes are disappearing while panning the camera and you get near canvas border.

Couldn't reproduce the behavior but in extreme case, the objects can leave the camera frustum (clippig planes) Perhaps that is what [deethee](https://github.com/deethee) is seeing?

**Comment by WestLangley** [comment]
Is this what I see with `OrthographicCamera`:

![Transform Controls with Orthographic Camera](https://user-images.githubusercontent.com/1000017/173234972-803f85eb-8601-455f-a782-2c27f1471898.gif)

**Comment by WestLangley** [comment]
For `OrthographicCamera`, I expect you will want to use a different calculation.

https://github.com/mrdoob/three.js/blob/f30599ed21818efbbffee6e923957616fd410016/examples/jsm/controls/TransformControls.js#L208

**Comment by Mugen87** [comment]
> Is this what I see with OrthographicCamera:

Interesting! Can you please describe the setup for reproduction?

**Comment by WestLangley** [comment]
@Mugen87 I just followed the instructions [in the above post](https://github.com/mrdoob/three.js/issues/24208#issuecomment-1149815311).

**Comment by Mugen87** [comment]
Now with running the demo in full screen I see the glitch, too. My first test in smaller window with different aspect ratio did not really show it.

**Comment by deethee** [comment]
![transformcontrol3](https://user-images.githubusercontent.com/2727230/173519651-ad7a8915-6d12-47c8-8e6d-7fa5814b1921.PNG)

Sorry for replying late and thank you for uploading the video. It is hard to reproduce but zoom, orthographic camera,  the distance from Canvas border, maybe orbit controls and widow size does matter to reproduce this issue.
I think there are other issues related to it.
E.G. if you use one translation axis to move an object along one axis the dragging of the axis sometimes stops. This seems to happen when  the alignment changes. E.G.  The axis is pointing down, when the axis reaches the bottom canvas the axis alignment flips to up. Often there is only one axis affected mainly y.

**Comment by deethee** [comment]
A camera zoom on a orthographic camera is somehow misleading since a zoom in describes a decrease in the camera angle. This is not the case on an orthographic camera since there is no camera angle. The orbit controls change the zoom.
 I think this is where the problem lies. The zoom changes the projection matrix and frustum and this is not properly adopted for the TransformControls leading to drag and clipping problems.

**Comment by Mugen87** [comment]
@deethee Applying @WestLangley's patch from https://github.com/mrdoob/three.js/issues/24208#issuecomment-1153165586 definitely mitigates the issue for me. Can you give it a try?

**Comment by WestLangley** [comment]
@Mugen87 There may still be a frustum far-pane clipping issue -- or is that considered a user error?

**Comment by Mugen87** [comment]
I'm not sure the clipping issue can properly addressed (apart from configuring the camera differently in the first place).
