### ISSUE TITLE
Have access to the internally generated CubeUVMaps by WebGLRenderer

### ISSUE THREAD

**Issue by danielesteban** [mrdoob/three.js#24200]
**Is your feature request related to a problem? Please describe.**

I would like to have access to the internally generated cubeuvmap that the WebGLRenderer stores when you set Scene.environment.

I tried to use the one that's populated in material.envMap but that is guarded in WebGLRenderer by material.isMeshStandardMaterial:
https://github.com/mrdoob/three.js/blob/a4d7a97260132583a007c922dc0723594f5d5335/src/renderers/WebGLRenderer.js#L1351

I also tried to get it from the WebGLRenderer directly but the WebGLCubeUVMaps storage is not exposed:
https://github.com/mrdoob/three.js/blob/64ac0a2e24a0c02d25ce973611808f9f59ca0e37/src/renderers/WebGLRenderer.js#L328

My goal is to be able to just set `Scene.environment` and use it on a ShaderMaterial just like on a MeshStandardMaterial.
Right now I need to manually create the cubeuvmaps with the PMREMGenerator.

**Describe the solution you'd like**

A posible solution is guarding `materialProperties.envMap` with another constant instead of just `material.isMeshStandardMaterial`, maybe `material.isMeshStandardMaterial || material.defines.ENVMAP_TYPE_CUBE_UV`.
I dunno if that's too hacky of a check hehe, but something like that.

Another simpler one is to just have access somehow to the WebGLCubeUVMaps storage in the WebGLRenderer. Either by exporting it in the renderer or passing it to onBeforeRender.

```js
// Here's an example scenario:
(new RGBELoader()).load(environmentURL, (texture) => {
  texture.mapping = EquirectangularReflectionMapping;
  scene.background = texture;
  scene.environment = texture;

  const meshStandard = new Mesh(new BoxGeometry(), new MeshStandardMaterial());
  scene.add(meshStandard);

  const meshShader = new Mesh(new BoxGeometry(), new ShaderMaterial());
  scene.add(meshShader);

  // This is what I'm trying to avoid:
  meshShader.material.uniforms.cubeUVMap.value = new PMREMGenerator(renderer).fromEquirectangular(texture).texture;

  // This could be a posible solution:
  // Just need a method/way to access the renderer cubeuvmap storage.
  meshShader.onBeforeRender = (renderer, scene, camera) => {
    meshShader.material.uniforms.cubeUVMap.value = renderer.getCubeUVMap(scene.environment);
  };
});
```

**Describe alternatives you've considered**

The alternative is generate the cubeuvmaps manually. But that creates a potential for having 2 of them. One that threejs generates for meshes in the scene with MeshStandardMaterial and the one I need to generate manually for the meshes with a ShaderMaterial.

Of course I can just set `isMeshStandardMaterial = true` in my ShaderMaterial.. But that will also try to set a whole bunch of uniforms besides the envMap that my material lacks and it doesn't seem to be a way to control which one of them you want.

**Additional context**

I dunno if anyone else has this problem. But having access to the internally generated cubeuvmaps somehow will be nice for me and I beleive also for people whom make modules with ShaderMaterial and RawShaderMaterial.

**Comment by WestLangley** [comment]
Related: https://github.com/mrdoob/three.js/issues/22197#issuecomment-888566098 and https://github.com/mrdoob/three.js/issues/22197#issuecomment-887722331.

**Comment by Mugen87** [comment]
So you would be happy if `cubemaps` and `cubeuvmaps` would be public? Or do you rely on more internal changes?

I'm always having troubles with such changes since when we make stuff like that public, we also have to ensure some sort of support and compatibility. However, the entire design was not meant to be for public use. So there might be problems we are currently not aware of.

**Comment by mrdoob** [comment]
@danielesteban 

```js
  // This is what I'm trying to avoid:
  meshShader.material.uniforms.cubeUVMap.value = new PMREMGenerator(renderer).fromEquirectangular(texture).texture;
```

Why are you trying to avoid that?

**Comment by danielesteban** [comment]
> @danielesteban
> 
> ```js
>   // This is what I'm trying to avoid:
>   meshShader.material.uniforms.cubeUVMap.value = new PMREMGenerator(renderer).fromEquirectangular(texture).texture;
> ```
> 
> Why are you trying to avoid that? We're exposing the classes the renderer use internally for cases like this.

I'm trying to avoid to have it to happen twice for a single scene with scene.environment with a MeshStandardMaterial and a ShaderMaterial in it.

```js
scene.environment = texture;
const meshStandard = new Mesh(new BoxGeometry(), new MeshStandardMaterial());
// The moment the above mesh renders, it will create a new cubeuvmap from the envmap and store it inside the renderer

const meshShader = new Mesh(new BoxGeometry(), new ShaderMaterial());
meshShader.material.uniforms.cubeUVMap.value = new PMREMGenerator(renderer).fromEquirectangular(texture).texture;
// This second cubeuvmap is a duplicate of the first internal one. wasting memory and resources.
```

The only way I can avoid being duplicate is:
```
// scene.environment = texture;
meshStandard.envMap = meshShader.material.uniforms.cubeUVMap.value = new PMREMGenerator(renderer).fromEquirectangular(texture).texture;
```

But that doesn't work for me since I'm doing a module that people import in their scenes which already have environments and other meshes with stardardmaterial and such.

**Comment by dBat23** [comment]
Speaking of publicity. Would any of y'all have teams that might be
interested in designing smart turf for the bills and bruins associated
company: Banners Kitchen and Tap? It's in TD Garden.

Your modelling software looks better than my modeling software so that's
why I'm asking.

The procurement team and such are in the wework down the street. The owner
is in MT but the family is associated with MIT Legatum. I already started
the pitch, I just don't think they have time to install turf in the dining
room :/

**Comment by dBat23** [comment]
Since it's a restaurant and in "TD GARDEN" I feel the design can have some
unique creative liberties that normal turf in sports areas usually doesn't.

I'm pretty sure the procurement budget is pretty healthy too..I spoke with
procurement about a year ago and they weren't aware of a max, just as
needed restriction.

**Comment by WestLangley** [comment]
@danielesteban Can you please explain why the solution I linked to above is not adequate for your use case?

**Comment by danielesteban** [comment]
Alrighty. Nobody else seems to have this problem and to tell you the truth neither do I on 99% of what I do with threejs.

It was just a thought that came at the time when updating a module with a material that doesn't inherit from the StandardMaterial but also uses environments. Which I admit is a pretty rare use case.

Also, there's already a bunch of workarounds alredy posted here if anybody is interested on how to get the cubeuvmaps from the renderer.

So.. I'm going to close this out.
Thanks a bunch everybody for your input.
