### ISSUE TITLE
When using nodeFrame, toneMapping and toneMappingExposure does not work

### ISSUE THREAD

**Issue by shihaoning** [mrdoob/three.js#24204]
**Describe the bug**

When using nodeFrame, toneMapping and toneMappingExposure does not work

**To Reproduce**

1. import nodeFrame
2. change toneMapping or toneMappingExposure 
3. See error

***Code***

```js
// when import this , toneMapping and toneMappingExposure not worked
import { nodeFrame } from 'https://threejs.org/examples/jsm/renderers/webgl/nodes/WebGLNodes.js';
gui.add(params, 'toneMapping', Object.keys(toneMappingOptions))

              .onChange(function () {

                    renderer.toneMapping = toneMappingOptions[params.toneMapping];
                    render();

                });
            gui.add(params, 'exposure', 0, 2)

                .onChange(function () {

                    renderer.toneMappingExposure = params.exposure;
                    render();

                });
```

***Live example***
see this demo
[index.zip](https://github.com/mrdoob/three.js/files/8858119/index.zip)

**Expected behavior**

toneMapping and toneMappingExposure can work under nodeFrame

**Screenshots**

![image](https://user-images.githubusercontent.com/28341337/172526743-1dd3f406-3d64-4580-948f-b06d8b7ab9e5.png)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r???]

**Comment by LeviPesin** [comment]
> `from 'https://threejs.org/examples/jsm/renderers/webgl/nodes/WebGLNodes.js'`

Never do that, please. Use at least a CDN.

**Comment by shihaoning** [comment]
> > `from 'https://threejs.org/examples/jsm/renderers/webgl/nodes/WebGLNodes.js'`
> 
> Never do that, please. Use at least a CDN.

Ha ha, I know, just to make it easier to write an offline demo to demonstrate this problem
