### ISSUE TITLE
Morph Target Animations break Reflections

### ISSUE THREAD

**Issue by kevor** [mrdoob/three.js#24201]
**Describe the bug**

When a Morph Target animation is played, the reflections are not updated correctly.

**To Reproduce**

1. Download the following model: https://metaverso.it/demo/static/balla2.glb
2. Open it with any web viewer based on ThreeJS (or Babylon) like this: https://gltf-viewer.donmccurdy.com/
3. See error

**Expected behavior**

The HDR reflection should stay steady instead of rotating with the sphere. The rotation should be unnoticable.

**Platform:**

 - Device: Any
 - OS: Any
 - Browser: Tested on Chrome, but should be any
 - Three.js version: Locally tested on 141

**Link to forum discussion**
https://discourse.threejs.org/t/vertex-animation-breaks-reflections/38953

**Comment by WestLangley** [comment]
Proper reflections require correct morph normals in your model. Try adding morph normals.
