### ISSUE TITLE
Editor: Video renderer no longer available in Chrome

### ISSUE THREAD

**Issue by mattrossman** [mrdoob/three.js#24212]
**Describe the bug**

The editor's video renderer [relies on a global `SharedArrayBuffer` constructor.](https://github.com/mrdoob/three.js/commit/71ffae30b3c75407d87696f726392215885dd8f9) Previously, this was [compatible with Chrome and not Firefox](https://github.com/mrdoob/three.js/issues/21603#issuecomment-814956064).

However [API changes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes#api_changes) have made this condition fail in Chrome too without certain headers present. AFAIK, the video renderer is not visible in any modern browser.

**To Reproduce**

In Chrome (currently v102.0.5005.61), run `'SharedArrayBuffer' in window`. It will evaluate to `false`, and the video renderer UI will not appear on https://threejs.org/editor

**Expected behavior**

The video renderer will be visible and functional in the editor on Chrome at least. I have to read more deeply about the new security restrictions, but hopefully this is an easy fix.

**Platform:**

 - Device: 2018 MacBook Pro
 - OS: MacOS 11.6
 - Browser: Chrome 102.0.5005.61
 - Three.js version: r141

**Comment by LeviPesin** [comment]
The restrictions are:
```
For top-level documents, two headers will need to be set to cross-origin isolate your site:

[Cross-Origin-Opener-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy) with same-origin as value (protects your origin from attackers)[Cross-Origin-Embedder-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy) with require-corp as value (protects victims from your origin)
```

**Comment by LeviPesin** [comment]
So I think this should be directed to GitHub Pages?

**Comment by LeviPesin** [comment]
Or we can just use a version without SharedArrayBuffer:
https://github.com/ffmpegwasm/ffmpeg.wasm/issues/137#issuecomment-1014956114

**Comment by mattrossman** [comment]
https://brunoluiz.net/blog/2022/jan/gif-sane-playback-control-ffmpegwasm/

> On the bright side: WASM applications can be compiled to single-threaded, and FFMPEG.wasm is no different. It removes the need for SharedArrayBuffer with the only caveat being it will be certainly slower.

I didn't get a chance to try the old renderer implementation so I'm not sure how slow it was already.

As for the headers, perhaps the editor could be hosted on Netlify since GitHub Pages doesn't allow for custom headers. The [ffmpeg.wasm site's](https://ffmpegwasm.netlify.app/) `netlify.toml` for reference: https://github.com/ffmpegwasm/ffmpegwasm.github.io/blob/f155bc1906b921333d797a041b493f0b1d7ed47d/netlify.toml

**Comment by mattrossman** [comment]
This looks interesting 👀 https://github.com/gzuidhof/coi-serviceworker

[That's what `canvas-capture` uses](https://www.npmjs.com/package/canvas-capture#caveats) for their demo page hosted on GitHub Pages.

**Comment by mattrossman** [comment]
I tried adding  `coi-serviceworker` and it worked, I just had to make local copies of a couple of scripts (ffmpeg.wasm and es-module-shims). Changes: https://github.com/mattrossman/three.js/commit/bc818a752ae2e3ad13adceaa142608c7c9f56de0

Demo: https://rawcdn.githack.com/mattrossman/three.js/bc818a752ae2e3ad13adceaa142608c7c9f56de0/editor/index.html

Not sure if that's too "hacky", but I could make a PR.

**Comment by Mugen87** [comment]
Right now, the project wants to use GitHub pages for hosting all parts of the website (docs, manual, editor etc.). Distributing parts to other providers only makes our rollout process more complicated.

Using `coi-serviceworker` sounds like a compromise to me. If you add a comment to the import that explains why the editor uses it, there should be no misunderstandings.

**Comment by mrdoob** [comment]
@LeviPesin 

> Or we can just use a version without SharedArrayBuffer:
> https://github.com/ffmpegwasm/ffmpeg.wasm/issues/137#issuecomment-1014956114

This seems worth to try to me.

**Comment by LeviPesin** [comment]
I think it would be much easier (and keeping the speed of ffmpeg) to just add headers in the service worker.

**Comment by mrdoob** [comment]
Ah, I see... Feel free to do a PR so we can give it a try 👍
