### ISSUE TITLE
Applying circle texture to point renders a square; behavior changed from r137.2 to r137.3

### ISSUE THREAD

**Issue by LukasSchwarz4202** [mrdoob/three.js#24229]
**Describe the bug**

When creating a new Three.PointsMaterial using a circle texture loaded from a png image, a square is rendered instead. The behavior has changed from version r137.2 to version 137.3.

**To Reproduce / Live example**

r137.2 behavior: https://codesandbox.io/s/threejs-r137-2-circle-dpvzkk
r137.3 behavior: https://codesandbox.io/s/threejs-r137-3-circle-sie8ny

**Expected behavior**

The Three.PointsMaterial should render a circle instead of a square.

**Screenshots**

r137.2 behavior:
![Screenshot from 2022-06-12 20-23-07](https://user-images.githubusercontent.com/6068270/173248753-ed53a79c-6c3b-474e-ba8e-3cda796f2103.png)
r137.3 behavior:
![Screenshot from 2022-06-12 20-23-23](https://user-images.githubusercontent.com/6068270/173248760-37035624-ea7e-4169-b4af-ea5d9c7bcab0.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Linux]
 - Browser: [Chrome, Firefox]
 - Three.js version: [r137.2, r137.3]
 - React three fiber version: [6.0.13]

**Comment by LeviPesin** [comment]
The only difference between r137.2 and r137.3 is the `Material.alphaWrite` removal...

**Comment by WestLangley** [comment]
r137.2 was buggy, and is not relevant.

You need to set `transparent: true` for your `.png` alpha channel to be honored.

**Comment by LukasSchwarz4202** [comment]
`transparent: true` works. But setting it true leads to a few consequential problems which I could solve with the help of https://discourse.threejs.org/t/material-transparency-problem/3822/5
