### ISSUE TITLE
Three.js is slower than zen-3d

### ISSUE THREAD

**Issue by VanderSP** [mrdoob/three.js#24220]
**Describe the bug**

ThreeJS slower than https://github.com/shawn0326/zen-3d
when animating sky/water shader, i would love if threejs was the same performance

**To Reproduce**

run sky/water on threejs and compare with zen3d... move the sun for example, inclination... see the absurd difference in FPS

***Code***

compare both lib shaders is nearly identical as zen was inspired (not totally forked as others) in three

**Expected behavior**

Same performance, if it´s the same "thing" and shader

**Comment by VanderSP** [comment]
there´s differences... when i found it in 2020, i was desesperate trying to understand why ThreeJS gives black textures in standard material in older devices.... and zen don´t.... but despite old devices... zen3d got carefull with mobile, and threejs sometimes don´t...

as for example in this case im explaining... if it´s the same, why it´s 30+ fps in uniform updating ocean/sun?

i want this performance in three, as im three user, and is the SAME SHADER

**Comment by LeviPesin** [comment]
> trying to understand why ThreeJS gives black textures in standard material in older devices

Are you talking about https://github.com/mrdoob/three.js/issues/14137?

**Comment by VanderSP** [comment]
probably, and in same devices, zen3d runs fine

**Comment by LeviPesin** [comment]
Can you make a fiddle with zen3d and a fiddle with Three.js showing the speed differences?

**Comment by VanderSP** [comment]
I remember all those threads... but at the end of day, zen works at highp, and if u turn mediump on many cases, u got unusable artifacts

**Comment by VanderSP** [comment]
would be a nice a idea creating a fiddle... when i got a bit of time i will surely do!

**Comment by mrdoob** [comment]
Please, don't make me spend time again changing the clickbait title and the exaggerations in your post.

Looking forward for the fiddle 👍

**Comment by VanderSP** [comment]
HAHAHA i was hypnotized by the haunting rules about being deleted if not correctly described, then i asked myself if it´s a feature or bug... is this what so? lol

yeah, the cool would be make a fiddle with 2 canvas, side by side, for practical purposes

**Comment by Mugen87** [comment]
I would also suggest to move this discussion to the [forum](https://discourse.threejs.org/) first. Only when it turns out to be a problem in the engine, a issue at GitHub should be opened.

**Comment by VanderSP** [comment]
ok here we go

threejs one:

[](https://jsfiddle.net/8j2orxy4/87)

zen3d one:

[](https://jsfiddle.net/8j2orxy4/151)

sorry base64 on zen one, i cant managed to put image link didn´t worked

observations:
on my computer three gives oscillations down in fps... but zen3d 60 61 fps stable

on my mobile, threejs capped to 29 30, while zen-3d 30 ~46 fps... but i remember 3 years ago testing, that it´s more on the stable side of 46 when interacting, maybe i forced too hard the auto senoid demo... also jsfiddle i dunno if it make slower on mobile...

veredict: there´s some performance culprit occult inside threejs (i mean even if it´s not a 'slowering feature' we are using)

Thanks.

**Comment by LeviPesin** [comment]
Not actually sure anyone is maintaining the `examples/jsm/objects` code...

**Comment by VanderSP** [comment]
hmm, but i think these discrepancies are more than 3 years ago already when i first discovered

**Comment by LeviPesin** [comment]
What happens if you also disable matrices autoupdate in three's fiddle and update them manually (like in zen3d's fiddle)?

**Comment by VanderSP** [comment]
much probably u tested that in the epoch, i was just lazy to say something about it

**Comment by Mugen87** [comment]
> Not actually sure anyone is maintaining the examples/jsm/objects code...

It is maintained.

**Comment by Mugen87** [comment]
Your life example of `three.js` executes a lot of logic which is not required and makes it unsuitable for a performance comparison. The scene assume an object with PBR material is in place which is not true. So you perform unnecessary tone mapping and you generate an environment map via `PMREMGenerator` per frame which is not used at all.

Like mentioned above, the forum is a better place for such issues.
