### ISSUE TITLE
SSAARenderPass, color tends towards white

### ISSUE THREAD

**Issue by Lipacinp** [mrdoob/three.js#24239]
Hello everyone,

1. **Describe the bug**

I've updated ThreeJS in my project and test the SSAARenderPass seems broken.

When sample level >1.0, scene get brighter and tends toward all white.

The examples at [SSAARenderPass](https://threejs.org/examples/?q=ssaa#webgl_postprocessing_ssaa) is working well but even when I'm copy/pasting the example, I've got the issue.

In the older version of THREEJS (<138), I don't have the problems.

2. **Live example**

[jsfiddle](https://jsfiddle.net/Lipacino/Lkzmt6p0/)

Platform:

Device: Desktop
OS: Windows
Browser: Chrome, Firefox
Three.js version: r141

**Comment by Mugen87** [comment]
Try setting a black background color like so: https://jsfiddle.net/t0ux4d25/

I believe the difference in behavior is the result of the new default usage of RGBA (meaning the renderer's default framebuffer is now always created with an alpha channel).

**Comment by Lipacinp** [comment]
Thanks a lot ! 

Didn't know that the HTML background could influence the rendering with RGBAFormat.
