### ISSUE TITLE
SVGLoader: Support style definitions in `svg` tag.

### ISSUE THREAD

**Issue by lindow2009** [mrdoob/three.js#24248]
**Describe the bug**

load svg error with svgloader，the fill color is black

***Code***

```js
// code goes here
```
for (let i = 0; i < paths.length; i++) {

                            const path = paths[i];
                            //console.log("PATH", path.userData.node.id);
                            const fillColor = path.userData.style.fill;
                            // console.log("fillOpacity", path.userData.style.fillOpacity);
                            if (guiData.drawFillShapes && fillColor !== undefined && fillColor !== 'none') {

                                // console.log("FIILL"+fillColor);
                                const material = new THREE.MeshBasicMaterial({
                                    /* Math.random() * 0xffffff */
                                    color: new THREE.Color().setStyle(fillColor),
                                    opacity: path.userData.style.fillOpacity,
                                    transparent: path.userData.style.fillOpacity < 1,
                                    userData: path.userData.node,
                                    side: THREE.DoubleSide,
                                    depthWrite: false,
                                    wireframe: guiData.fillShapesWireframe,
                                });

                                const shapes = path.toShapes(true);
                                for (let j = 0; j < shapes.length; j++) {
                                    const shape = shapes[j];
                                    const geometry1 = new THREE.ShapeGeometry(shape);
                                    const mesh = new THREE.Mesh(geometry1, material);
                                    group.add(mesh);
                                }
                            }

                            const strokeColor = path.userData.style.stroke;
                            if (guiData.drawStrokes && strokeColor !== undefined && strokeColor !== 'none') {
                                const material = new THREE.MeshBasicMaterial({
                                    color: new THREE.Color().setStyle(strokeColor),
                                    opacity: path.userData.style.strokeOpacity,
                                    transparent: path.userData.style.strokeOpacity < 1,
                                    side: THREE.DoubleSide,
                                    depthWrite: false,
                                    wireframe: guiData.strokesWireframe,
                                    wireframeLinecap: "square"
                                });

                                for (let j = 0, jl = path.subPaths.length; j < jl; j++) {
                                    const subPath = path.subPaths[j];
                                    const geometry2 = THREE.SVGLoader.pointsToStroke(subPath.getPoints(), path.userData.style);
                                    if (geometry2) {
                                        const mesh = new THREE.Mesh(geometry2, material);
                                        group.add(mesh);
                                    }
                                }
                            }
                        }
                        scene.add(group);

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hbfpj2wv/2/)
* [jsfiddle-dev](https://jsfiddle.net/086yzvgc/)

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: r141

**Comment by LeviPesin** [comment]
Please share the SVG being loaded.

BTW, it is not needed to do `color: new THREE.Color().setStyle( style )` - you can write just `color: style`.

**Comment by lindow2009** [comment]
![2022061600000010](https://user-images.githubusercontent.com/1233164/174520716-bf1d2916-cc3e-43fe-8a88-b45fbe6630c6.svg)

**Comment by Mugen87** [comment]
It seems the loader is not able to correctly process the file since the properties for the stroke are globally defined in the `<svg>` tag but not in the actual path definitions. Styles in the `<svg>` are ignored.

This is the "fixed" SVG the loader can process.
![test](https://user-images.githubusercontent.com/12612165/174580201-4dce49d9-31ec-4b8a-9ac6-13aeb68f32dc.svg)

However, it would be more correct to enhance the loader and support these kinds of global styles.
