### ISSUE TITLE
Examples Do Not Load in iOS 14 Simulator Safari

### ISSUE THREAD

**Issue by timnlupo** [mrdoob/three.js#24258]
**Describe the bug**

Examples do not load in iOS 14 simulators (but work on device). They do work in my iOS 15.4 simulator. Curious to understand why.

**To Reproduce**

1. Download iOS 14.4 or 14.5 simulator
2. Open Safari and navigate to https://threejs.org/examples/#webgl_animation_keyframes
3. See error

**Expected behavior**

Examples to load in iOS 14 simulator.

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).
![simulator_screenshot_44030ED0-64A1-4AA1-9E31-2D3CFDB6BEEB](https://user-images.githubusercontent.com/9003282/174687356-2395e60f-a27f-4644-ad26-748b644500d7.png)

**Platform:**

 - Device: Mobile
 - OS: iOS Simulator
 - Browser: Safari
 - Three.js version: N/A

**Comment by timnlupo** [comment]
Also not working on 13.7. Perhaps anything that uses WebGL 1.0. Worth noting I'm on a M1 chip macbook

**Comment by mrdoob** [comment]
> Curious to understand why.

I think the developers of the simulator would know the reason better than us...
