### ISSUE TITLE
Is there any plan to implement volume rendering in three.js

### ISSUE THREAD

**Issue by gzt036** [mrdoob/three.js#24261]
Volume rendering is a basic requirement for many usages, especially in the field of medical image.

Currently the only available solution is through vtk.js, which does a good job at volume rendering. Is there any plan  to implement it in three.js?

**Comment by gkjohnson** [comment]
You are already able to implement rending of volumetric data in shaders. See the [examples](https://threejs.org/examples/?q=vol#webgl2_volume_cloud)

**Comment by donmccurdy** [comment]
Happy to discuss further in https://discourse.threejs.org/, Slack, or Discord. :)

**Comment by gzt036** [comment]
How to use it then, any example or documentation?  How is it implemented, can it be used to show a DICOM image?

**Comment by donmccurdy** [comment]
Examples are linked above. For more detailed help please post to the forums. We use github issues only for feature development and bug tracking.
