### ISSUE TITLE
Transparency in nodejs version of three js

### ISSUE THREAD

**Issue by svoboda200786** [mrdoob/three.js#24268]
I am starting my Three.js script on Node.js headless server. And I want to make transparent backgroud. So I type smth like that:

```
scene.getObjectByName("Circle").material.transparent = true;
scene.getObjectByName("Circle").material.alphaTest = 0.5;
  const texture = new THREE.Texture(image);
  texture.minFilter = THREE.LinearFilter;
  texture.needsUpdate = true;
  texture.flipY = false; 
  scene.getObjectByName("Circle").material.map = texture; 
```

And I expect smth like on pic. 1 (it's screenshot from common js version of my script, not node js version) — transparent picture on black scene background. But instead I have the one from second screenshot (pic. 2). I mean transparancy doesn't work in node js version of threejs. Or it does?

https://i.stack.imgur.com/88CDG.png — pic. 1

https://i.stack.imgur.com/5qvkA.png — pic. 2

**Comment by Mugen87** [comment]
> I mean transparancy doesn't work in node js version of threejs. Or it does?

It actually does since our E2E tests are node.js based and the official examples render just fine. It seems there must be something wrong with your node setup.

Please let you help at the [forum](https://discourse.threejs.org/). We can reopen the issue if there is an actually issue in the engine.

**Comment by Mugen87** [comment]
I was assuming the OP also uses puppeteer.
