### ISSUE TITLE
Error when using textureloader

### ISSUE THREAD

**Issue by CheungBH** [mrdoob/three.js#24297]
Hello. I am trying to use the textureloader to import the background. However, an error occurs to me:
**Uncaught TypeError: THREE.textureLoader is not a constructor.**
How to solve it?

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**To Reproduce**

3. See error

***Code***

```js
// code goes here
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hbfpj2wv/2/)
* [jsfiddle-dev](https://jsfiddle.net/086yzvgc/)

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop]
 - OS: [Linux]
 - Browser: [Chrome]

**Comment by Mugen87** [comment]
> THREE.textureLoader

Try using `THREE.TextureLoader`.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.
