### ISSUE TITLE
The axis extracted from the object quaternion is wrong when the object rotates on both axis

### ISSUE THREAD

**Issue by aDeveloperCase** [mrdoob/three.js#24301]
**Describe the bug**

It can be one of the following:

- The Object3d `quaternion` is not storing the correct axis information.
- The Vector4 method `setAxisAngleFromQuaternion` is not extracting the axis information corretly from the quaternion.
- My code is not correct or I'm using quaternions wrong...

It looks like that the axis of rotation retrieved using the `setAxisAngleFromQuaternion` method is not correct once the object containing the quaternion has been rotated both in the x and the z axis.

If the object is rotated only in the x or z axis, the direction of the axis is correct instead.

**To Reproduce**

1. Go to the [live example](https://jsfiddle.net/aDeveloperCase/u13tpn8h/52/)
2. Comment one and only one of the red rotation update (the one on the z axis or the one on the y).
    For exaple `// red.rotation.y += 0.01;`
3. You will see the blue object rotating correctly around the red one based on the red rotation. And the yellow stick represents the correct rotation axis extracted from the red quaternion

1. Go to the live example again
2. Leave the red rotation updates uncommented
3. You will see the blue object rotation and the yellow stick both diverging almost immediatly from the real red object rotation and axis of rotation.

***Code***

```js
    var geo1 = new THREE.BoxGeometry(5, 1, 1);
    
    // material
    var mat1 = new THREE.MeshPhongMaterial( {
        color: 0xff0000, 
        flatShading: true,
        transparent: true,
        opacity: 0.7,
    } );
    var mat2 = new THREE.MeshPhongMaterial( {
        color: 0x0000ff, 
        flatShading: true,
        transparent: true,
        opacity: 0.7,
    } );
    
    var axisGeo = new THREE.BoxGeometry(0.2, 0.2, 30);
    var axisMat = new THREE.MeshPhongMaterial({
        color: 0xffff00, 
        flatShading: true,
        transparent: true,
        opacity: 0.7,
    });
    
    // mesh
    red = new THREE.Mesh( geo1, mat1 );
    blue = new THREE.Mesh(geo1, mat2);
    
    axisMesh = new THREE.Mesh(axisGeo, axisMat);
    
   	blue.position.set(10, 0, 0)
    scene.add( red, blue, axisMesh );
    
    axisAngle = new THREE.Vector4().setAxisAngleFromQuaternion(red.quaternion);
    oldAxisAngle = axisAngle.clone();
    rotAxis = new THREE.Vector3().set(axisAngle.x, axisAngle.y, axisAngle.z);
    
    axisMesh.lookAt(rotAxis);
    
}

function animate() {

    requestAnimationFrame( animate );
    
    //controls.update();
    
    // Extracting the rotation axis and the angle from quaternion and storing it into a Vector4...
    axisAngle.setAxisAngleFromQuaternion(red.quaternion);
    // Setting the axis values to a Vector3
    rotAxis.set(axisAngle.x, axisAngle.y, axisAngle.z);
    
    // Updating the yellow stick (axis representation)
    axisMesh.lookAt(rotAxis);
    
    // The difference between the old angle value and the current one.
    var theta = axisAngle.w - oldAxisAngle.w;
    // Rotates the blue object around the red pivot point with the axis and angle found
    rotateAboutPoint(blue, red.position, rotAxis, theta);
    
    // Updating the old Vector4
    oldAxisAngle = axisAngle.clone();
    
    red.rotation.y += 0.01;
    red.rotation.z += 0.01;

    renderer.render( scene, camera );

}
```

***Live example***
https://jsfiddle.net/aDeveloperCase/u13tpn8h/52/

**Expected behavior**

I would expect the blue object to rotate correctly around the red object based on the red object rotation.
Meaning that I would expect the axis of rotation computed from the quaternion to coincide with the effective axis of rotation.

**Screenshots**

When the red object rotates only on one axis (the y axis in this case), the direction of the rotation axis extracted from the red quaternion is correct.
![quaternion_rotation_correct](https://user-images.githubusercontent.com/49728944/177002408-02c2b7ed-92fb-48ab-9026-0fcef580e91c.PNG)

When the red objects rotates both on the z and y axis, the direction of the rotation axis extracted from the red quaternion is wrong and diverges.
![quaternion_rotation_wrong](https://user-images.githubusercontent.com/49728944/177002409-599bd703-9d54-4d28-abf1-7f7cb5e89f87.PNG)

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: https://unpkg.com/three@0.142.0/build/three.module.js

**Comment by gkjohnson** [comment]
Rotation axes are not always intuitive. The returned axis is the only axis that needs to be rotated around to reach the target rotation. I recommend asking at [the forum](https://discourse.threejs.org/) if you need help understanding axis-angle rotations.

**Comment by aDeveloperCase** [comment]
Hi @gkjohnson and thanks for your reply.
I will ask the forum, please let me be sure that the error is on my side first.

The returned axis, `rotAxis` in the example code, it is in fact the only axis around which it rotates the blue object.
It happens exactly when this method is called: 

```js
rotateAboutPoint(blue, red.position, rotAxis, theta);
```

If you look into the function in the live example, such function executes the following:

```js
obj.position.applyAxisAngle(axis, theta); // rotate the POSITION
```

Where `obj` is the passed blue object, `axis` is the passed returned axis `rotAxis` and `theta` is the passed `theta` angle.

What I'm trying to say is that the returned rotation axis itself, which is extracted from the red quaternion, is wrong when the red object undergoes a rotation both in the y and z axis.

You can see the expected behavour for the blue object, if you simply comment out one of the red rotations, like the following:

```js
    red.rotation.y += 0.01;
    // red.rotation.z += 0.01;
```

**Comment by makc** [comment]
> When the red objects rotates both on the z and y axis, the direction of the rotation axis extracted from the red quaternion is wrong 

what makes you think that? it is not obvious that it is wrong at all. Rather, your rotateAboutPoint implementation is wrong, as can be seen in [this simple test](https://jsfiddle.net/zbnahe8p/).

**Comment by aDeveloperCase** [comment]
Hi @makc thanks for your reply also.

>what makes you think that? it is not obvious that it is wrong at all.

I think that the rotation axis is wrong because I look at the yellow "line" which costantly looks at the rotation axis itself.
While the red object rotates, there are certain times in which the yellow line is actually parallel to the red object.

![axisOfRotation](https://user-images.githubusercontent.com/49728944/177045633-53ca8270-8b9e-4b69-abb0-520c3aab8ae8.PNG)

If the red object really rotated around the rotation axis retrieved (the yellow line), this would never be parallel to the red object from my understanding. And this happens regardles the use of `rotateAboutPoint` method.

>Rather, your rotateAboutPoint implementation is wrong, as can be seen in this simple test.

From what I see, your example works just because you've translated the geometry of the blue object beforehand but its origin it's still in the same position as the red one, so it's like blue and red are the same thing.

Lastly, I must say that the `rotateAboutPoint` function I've used it comes from  [this answer](https://stackoverflow.com/questions/42812861/three-js-pivot-point/42866733#42866733) on Stackoverflow.

But, I repeat, is not that relevant because I think something is wrong with the rotation axis by also looking at the yellow line.

It is still possible that I did something wrong with the yellow line but it looks okay to me so far.

**Comment by makc** [comment]
@aDeveloperCase 
> there are certain times in which the yellow line is actually parallel to the red object.

yes, these times are when the angle is
```js
    const v = 3.14; // 0, 2 * 3.14, 3 * 3.14, 4 * 3.14 ....
    red.rotation.y = v;
    red.rotation.z = v;
```

if you look at blue object (in my test) you will notice that all of these angles are where red object is not rotated at all - then it does not matter where the axis points to, does it ?

**Comment by makc** [comment]
(or it might still be rotated but we dont see it because 2 of box sides are the same)

**Comment by makc** [comment]
> From what I see, your example works just because you've translated the geometry of the blue object beforehand but its origin it's still in the same position as the red one, so it's like blue and red are the same thing.

exactly! this way I can bypass whatever bugs you have in your code and actually see if the axis is correct or not :D

**Comment by aDeveloperCase** [comment]
Hi @makc ,
Okay, thanks for the explanation.

Maybe opening a bug issue it has been too premature.
I'll open a help request at the forum instead about the blue object rotation.

Closing the issue, thanks everyone.
