### ISSUE TITLE
Use with maps to share webgl context，rendering problems occur

### ISSUE THREAD

**Issue by Phlicess** [mrdoob/three.js#24305]
**Describe the bug**

When multiple types of geometry are together, only one can be drawn

**To Reproduce**

***Live example***

[jsfiddle-r142](https://jsfiddle.net/phlicess/okcnfgdj/9/)

**Screenshots**
![image](https://user-images.githubusercontent.com/11753644/177070628-39ff17ac-b28a-42de-91e2-c08407d18cbf.png)
![image](https://user-images.githubusercontent.com/11753644/177070652-78953077-98c1-4d4e-b651-70898236fe29.png)

I get the warn:
![image](https://user-images.githubusercontent.com/11753644/177070766-971ff966-fe17-444c-b5b7-17967fd920fe.png)

**Platform:**
 - Three.js version: [r142]

IF I use r117, this look like good!

[jsfiddle-r117](https://jsfiddle.net/phlicess/okcnfgdj/16/)

![image](https://user-images.githubusercontent.com/11753644/177070926-fd639efb-6de9-43c4-8db4-07652f7132d4.png)

**Comment by Mugen87** [comment]
You can fix this issue by adding `renderer.resetState();` after the call of `renderer.render(scene, camera);`.

It's best if you reset the state before and after rendering a frame with `three.js` to avoid any side effects to other libraries.

**Comment by Phlicess** [comment]
> You can fix this issue by adding `renderer.resetState();` after the call of `renderer.render(scene, camera);`.
> 
> It's best if you reset the state before and after rendering a frame with `three.js` to avoid any side effects to other libraries.

OK~ THX~
