### ISSUE TITLE
Removed object3d is still present

### ISSUE THREAD

**Issue by manake** [mrdoob/three.js#24316]
```
scene.add(mesh);
scene.remove(mesh);

let raycaster = new THREE.Raycaster();
let intersects = raycaster.intersectObjects(meshes, false);
console.log(intersects[0]);
```

After a mesh is removed from the scene it disappears visually but raycaster is still seeing it.

How to remove it for good?

The documentation for `remove()` and `removeFromParent()` could be updated to clarify this.

**Comment by LeviPesin** [comment]
You should remove the mesh from your `meshes`.
