### ISSUE TITLE
typo in comment - probably not worth fixing!

### ISSUE THREAD

**Issue by msemtd** [mrdoob/three.js#24329]
There is a typo in a comment above the detach method of `TransformControls` - I only spotted it because I now use a cspell extension in vscode which has helped us track down dozens of bugs in our JS codebase!

https://github.com/mrdoob/three.js/blob/c22a74c7f8d58f827bb6136bc79e387a80bf4256/examples/jsm/controls/TransformControls.js#L566

**Comment by Mugen87** [comment]
Thanks for reporting! Should be fixed via 59ba69f0f019fe0fb66d2a510b37ff6c027256c1.
