### ISSUE TITLE
Improvement to PropertyBinding track name parsing and/or documentation

### ISSUE THREAD

**Issue by quiteunhappy** [mrdoob/three.js#24328]
**Is your feature request related to a problem? Please describe.**

I am using a KeyframeTrack to control properties on a ShaderMaterial and had a handful of issues getting things working correctly.
PropertyBinding uses the KeyframeTrack name, but I was limited to the depth of properties I could access. Peeking the [PropertyBinding code](https://github.com/mrdoob/three.js/blob/dev/src/animation/PropertyBinding.js#L148) and parseTrackName, I can see the limit. 

![image](https://user-images.githubusercontent.com/12730229/177956274-5b6a845f-6b28-42c5-9822-279c94982eae.png)

Setting a single float within a materials was fine, but I struggled with anything else. I couldn't directly access the X, Y, Z or W components and trying to set a value to a new Vector4 resulted in a NaN at runtime. 

![image](https://user-images.githubusercontent.com/12730229/177956390-42b57958-a797-4b1c-ae9c-860ec1d1a0fe.png)

The workaround for this was to expose an X, Y, Z and W float, and combine them within the shader.

Additionally, getting to this point took some working out - the syntax (imo) isn't very intuitive, and the [documentation on parseTrackName](https://threejs.org/docs/#api/en/animation/PropertyBinding.parseTrackName) didn't really help until it clicked with me with the help of some errors.

**Describe the solution you'd like**

I believe the limits to parseTrackName should be reviewed, at least for Material/s.

**Describe alternatives you've considered**

As there is a workaround for this as I've described above, updating the documentation to make it a little more clear on how this works and what track names should adhere to would also be ideal.

**Comment by Mugen87** [comment]
>  I couldn't directly access the X, Y, Z or W components and trying to set a value to a new Vector4 resulted in a NaN at runtime.

One of the official examples (https://threejs.org/examples/misc_animation_keys) animates the `color` property of a material. The respective keyframe track targets directly the property, not the individual r,g,b components. 

https://github.com/mrdoob/three.js/blob/191a1ef699a5d53de2cd645c667e7fee184a18fd/examples/misc_animation_keys.html#L82

Do you mind updating `misc_animation_keys` to show what's going wrong with your code?

Independently, the `PropertyBinding` page is not better documented since the manual setup of animation clips is not that common. In most use cases, animations are defined in 3D assets and then just imported in the engine.

**Comment by quiteunhappy** [comment]
The example you highlighted solves my problem, in my case I was passing a `new Vector4(x, y, z, w)` for each keyframe - So I'll take the L on that one for not properly looking through the examples.

As for the documentation, I thought that might be the case - We typically export the animations with the models, but had some specific work to do with Shaders.

**Comment by Mugen87** [comment]
Good to hear that your issue has been solved!

For now, I think it's okay to close the issue. If more users struggle with manually creating keyframe tracks, we can consider to enhance the manual with additional information.
