### ISSUE TITLE
Check if shader compiles

### ISSUE THREAD

**Issue by nopjia** [mrdoob/three.js#2433]
This might already be possible, but there should be a way to check if a shader code would compile, before it is linked and loaded. 

I'm not sure, but from what I've seen, it doesn't seem like there is a way. Right now, if the shader does not compile, the material just goes black. 

This would be similar to how GLSL Sandbox is doing its shader compilation check without linking the shader program. But GLSL is written in plain WebGL. From what I understand, currently there is no way to do that if you are using three.js

**Comment by tschw** [comment]
As explained in #6963, merged #6818 implemented error feedback for shaders.
> I think this is interesting, it could come in play for some more advanced content creation tools, realtime feedback is good for productivity.

And, yeah, you see the errors pop up while typing GLSL in our editor :-). So this one actually is actually closed, right?

**Comment by mrdoob** [comment]
Yeps!
