### ISSUE TITLE
just a typo in some variable names

### ISSUE THREAD

**Issue by msemtd** [mrdoob/three.js#24344]
https://github.com/mrdoob/three.js/blob/3a76bc7d212557422abe33525d2f3e44f79fb406/examples/jsm/controls/TransformControls.js#L1319

Very minor!

"..._TRESHOLD" should be "..._THRESHOLD"

**Comment by Mugen87** [comment]
Should be fixed via cf25a80737db2914f0b36e7c77af23a9981d03c1.
