### ISSUE TITLE
TypeError: THREE.KTX2Loader is not a constructor

### ISSUE THREAD

**Issue by xchellx** [mrdoob/three.js#24343]
**Describe the bug**
`TypeError: THREE.KTX2Loader is not a constructor` even when including `KTX2Loader.js` after `three.min.js`.
Additionally, when self hosting a page that uses KTX2Loader with a CORS supported http server over localhost, I get
`ReferenceError: VK_FORMAT_R32G32B32A32_SFLOAT is not defined` as well as `TypeError: THREE.KTX2Loader is not a constructor`

**To Reproduce**
1. Include `three.min.js` then `KTX2Loader.js` in a web page.
2. `const ktx2Loader = new THREE.KTX2Loader();`
3. Inspect page

***Code***
[example](https://jsfiddle.net/xchellx/ctouzLbx/4/)

***Live example***
[example](https://jsfiddle.net/xchellx/ctouzLbx/4/)

**Expected behavior**
Ability to use `KTX2Loader` constructor

**Screenshots**
N/A

**Platform:**
 - Device: Desktop, Mobile
 - OS: Windows, Android
 - Browser: Chrome
 - Three.js version: r142

**Comment by gkjohnson** [comment]
When using UMD modules with KTX2Loader the KTX module must be included separately though it's generally recommended you use es modules. You can ask for more detail at [the forums](https://discourse.threejs.org/).
