### ISSUE TITLE
Outlinepass wrong face rendering

### ISSUE THREAD

**Issue by doczoidberg** [mrdoob/three.js#24351]
I use outlinepass but get weird rendering on several object edges. The face aren't filled to the edges. The more I zoom in the more right it does look
<img width="208" alt="Bildschirmfoto 2022-07-16 um 00 48 45" src="https://user-images.githubusercontent.com/1972209/179321671-403b61bf-a832-4381-b514-860d758c73fa.png">k

**Comment by Mugen87** [comment]
Any chances to demonstrate the issue by modifying the official outline example?

https://threejs.org/examples/webgl_postprocessing_outline

I'm afraid a single screenshot is not sufficient for investigating this issue.

**Comment by Mugen87** [comment]
I've seen you have also ask a question at the forum: https://discourse.threejs.org/t/outlinepass-wrong-face-rendering/40383

Let's continue the discussion there. We can reopen the issue at GitHub when it turns out to be a bug in `OutlinePass`.

**Comment by WestLangley** [comment]
I expect this is a depth precision problem. You can mitigate it by increasing `camera.near` -- from 0.1 to 1, for example.

**Comment by doczoidberg** [comment]
> I expect this is a depth precision problem. You can mitigate it by increasing `camera.near` -- from 0.1 to 1, for example.

no, that makes no differece

**Comment by WestLangley** [comment]
I have an M1 mac and my suggestion mitigates the artifacts for me. I would not have posted here otherwise.

**Comment by doczoidberg** [comment]
strange. I have camera.near at 1 and changed to different values without effect.
