### ISSUE TITLE
Matrix2

### ISSUE THREAD

**Issue by T4G2** [mrdoob/three.js#24359]
**Missing Matrix2 in ThreeJS**

Im using ThreeJS for my bachelor thesis. In my work I needed to work with planarized faces, and it was quite an overkill to work with Matrix3 in Homogenous coordinates, so I created an custom Matrix2 Class with which I would love to contribute to this project.

**Comment by Mugen87** [comment]
Thanks for your proposal but in all these years there was no demand for a `Matrix2` class and I think it's uncommon to add such an entity to a 3D library.

**Comment by T4G2** [comment]
Well As I wrote to another issue, exactly  Half Edge Structure for Custom Models. #24360 . I'm currently working on MMP Algorithm to find Geodesics on 3D Model, and for sake of the speed i would need to add Matrix2 also with with Planar Tools Part of Library where I would add basic geometric algorithms for working with planar structure.

**Comment by Mugen87** [comment]
Sorry, but your use case is just too specific. `three.js` is not a library for computational geometry or math. We focus on logic that is commonly used in 3D apps. IMO, `Matrix2` does not belong to this scope.

**Comment by T4G2** [comment]
Alright, I get your point. In that case I will probably just create my own repo and I'll push it there. 
Thank you
