### ISSUE TITLE
Windows Mixed Reality causes webgl context loss when requesting WebXR

### ISSUE THREAD

**Issue by danrossi** [mrdoob/three.js#24369]
IT could be a Microsoft OpenXR bug. But I am stumped to what is going on. 

On each fresh page load, the first WebXR session request will flicker a black screen and trigger a webgl context loss. It seems the loss happens after session is opened. But when a context is restored, the webgl context changes internally but the session breaks and fails in the headset. Its trying to reference the old session inside the webxr manager as displayed in the console screenshot.

The only work around I've found is closing the session on context loss and telling the user to try again. Which would be on every single fresh page load.

Its very difficult to replicate and only on Mixed Reality headsets with Edge Chrome. 

Using any webxr example

https://threejs.org/examples/?q=vr#webxr_vr_video

![263FA1C7-D84C-474E-B584-75D6068AF821](https://user-images.githubusercontent.com/710277/179759631-1ef04a0d-7167-4d6f-8cec-dd166e730bb3.jpg)

**Comment by Mugen87** [comment]
> Its very difficult to replicate and only on Mixed Reality headsets with Edge Chrome.

I don't have a Windows Mixed Reality headset but is Edge the only browser you can test with? Is it possible to use just Chrome?

**Comment by danrossi** [comment]
With Occulus any Chrome and Firefox works. With Mixed Reality it's Edge Chrome only that webxr becomes available. It's a HP headset they are testing but there is an Acer one also. 

If it's a Microsoft OpenXR bug I'll wait for their response which I got none yet and I had configured the preview runtime also. I had to teamviewer in to test all this on someones machine. 

The bug is obviously breaking the webxrmanager functionality as the context is lost at the moment of session start. The second request after forcing the session to close can launch. But its every page load it's happening.

**Comment by mrdoob** [comment]
As far as I remember this context loss thing was intentional.

@cabanier Seems like the layers implementation is conflicting with Edge's context loss when going into WebXR.

**Comment by danrossi** [comment]
There is a black layer that flashes up when trying to start a session. Not sure where in the graphics is happening in the browser or external.

**Comment by cabanier** [comment]
> As far as I remember this context loss thing was intentional.
> 
> @cabanier Seems like the layers implementation is conflicting with Edge's context loss when going into WebXR.

Why do you think so?
AFAIK if you get the "there's already an active, immersive session" error, it means that the state in chromium's XRSystem is messed up.

**Comment by mrdoob** [comment]
So the bug is in Edge's implementation?

**Comment by danrossi** [comment]
I'm sorry to cause fuss. I also reported to Microsoft via feedback hub. But they never responded !  This WebXR only functions in Edge Chrome for WMR headsets, the HP and Acer ones.

**Comment by danrossi** [comment]
Some code I've had to do to temporarily work around it until figure out what is going on. 

```
this.renderer.domElement.addEventListener( 'webglcontextlost', () => {

            //console.log("context lost xr enabled: ", this.isVREnabled);

            if (this.isVREnabled) {
                const currentSession = this.renderer.xr.getSession();

               // console.log("context lost stop XR", currentSession);

                this.emit("xrcontextloss", currentSession);

                this.vrViewer.stop();

                const onContextRestored = () => {
                    this.renderer.domElement.removeEventListener( 'webglcontextrestored', onContextRestored);
                    this.emit("xrcontextrestored", this.renderer.getContext());
                };

                this.renderer.domElement.addEventListener( 'webglcontextrestored', onContextRestored, false );
               

                
            } 
        }, false );
  ```

**Comment by Mugen87** [comment]
Closing. We are not going add a fix for this on our side. Better to tackle this issue on the Edge bug tracker.

**Comment by danrossi** [comment]
I tried feedback hub and no response. I dont have a WMR headset to debug myself. I may have to try and get one. Thanks.
