### ISSUE TITLE
Hittest offsetRay--origin  is not position offset in the self coordinate system based on viewerpose

### ISSUE THREAD

**Issue by DLGL99GL** [mrdoob/three.js#24365]
I used Hittest to implement the location marking function in Hololens;
As shown in the picture
I want to change the origin and direction of offsetRay to  get the Hittest result pose   likes "I need"
but final result likes "I get",that maked me wonder "the origin is not 3D position offset in viewerpose local system"
why the distance of the two getHitTestResults is getting smaller and smaller;
when the origin is out of ±1，getHitTestResults  X /Y direction is the opposite of the theory？

![示意说明](https://user-images.githubusercontent.com/69023459/179686684-4d76e9ef-eb98-4625-9680-c997017ffd95.png)

**Comment by Mugen87** [comment]
I'm afraid your issue is not clear. Do you mind explaining in more detail what part of the library needs an enhancement or fix?
