### ISSUE TITLE
css2dObject Mouse event is not effective

### ISSUE THREAD

**Issue by MARIOMARUI** [mrdoob/three.js#24364]
When I used css2dobject to create a tag, I bound the click event to the tag and found that it did not take effect. Finally, I switched to r0.113 and the event took effect. Is there anything missing in the higher version.

This is an official example  css2d_label.html

```js

	window.addEventListener( 'resize', onWindowResize );

	// events handler
	earthDiv.addEventListener( 'click', function ( e ) {

		console.log( 'earthDiv' );
		earthLabel.visible = false;

	} );
	moonDiv.addEventListener( 'click', function ( e ) {

		console.log( 'moonDiv' );
		moonLabel.visible = false;

	} );

```

**Comment by yomotsu** [comment]
Actually, your problem was caused by OrbitControls.
Try removing OrbitControls: https://jsfiddle.net/h8pm6oqc/
