### ISSUE TITLE
three-nodes  cannot  use  in react?

### ISSUE THREAD

**Issue by 596983731** [mrdoob/three.js#24377]
./node_modules/three/examples/jsm/renderers/webgpu/nodes/WebGPUNodeBuilder.js
Module not found: Can't resolve 'three-nodes/core/CodeNode.js' ;
I use  react ,import three from node_modules ,it throws  a  error  like this ;how can i do to solve it? why "three-nodes/": "./jsm/nodes/"  ?

**Comment by LeviPesin** [comment]
Add `three-nodes` pointing to `three/examples/jsm/nodes` to your import map.

**Comment by marcofugaro** [comment]
Yeah the `three-nodes` alias doesn't work if you're using a bundler.

You can just import like this:

```js
import * as Nodes from 'three/examples/jsm/nodes/Nodes.js';
```

**Comment by donmccurdy** [comment]
We should replace this alias with something a bundler can resolve, like "three/nodes"

**Comment by robertlong** [comment]
> We should replace this alias with something a bundler can resolve, like "three/nodes"

I think so, this is really confusing if you're using a bundler.

As a workaround, if you're using Vite add the following to your config:

```js
export default defineConfig({
  resolve: {
    alias: {
      "three-nodes": "three/examples/jsm/nodes",
    }
  },
});
```

**Comment by donmccurdy** [comment]
Proposed:

- https://github.com/mrdoob/three.js/pull/24413

**Comment by lishulincug** [comment]
> 
![image](https://user-images.githubusercontent.com/13003282/185283132-d840e747-645e-4085-8eeb-b62477f4d955.png)
