### ISSUE TITLE
Reflector Color Space Issues

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#24384]
I am opening this as a separate issue in the hope we can keep the discussion focused.

Note that "color space" and "encoding" have still not been decoupled in the shader, so I am using legacy terminology here. Hopefully that will end soon.

1. `Reflector` should render in scene-referred linear color space -- to a float or half-float render target. (Or to an RGBM-encoded `UInt8` render target.) This is true, regardless of the renderer's output encoding. Setting the Reflector's `renderTarget.texture.encoding` to `renderer.outputEncoding` is not the right thing to do.

2. Consequently, it is only correct to include `encodings_fragment` in the reflector's fragment shader if it is needed for something like RGBM encoding. But three.js no longer supports such encodings.

3. When encoding to `sRGB` color space, tone mapping must proceed encoding. This is to ensure the inputs to the encoding step are in LDR. `Reflector` includes the encoding fragment, but not tone mapping fragment. Ideally, it should not include either of them.

Granted, encoding to sRGB and then decoding to linear-sRGB when reading back should not make a vast visual difference, except for rounding due to the Uint8 conversion. But still, it is unnecessary.

Feedback welcome.

three.js version: [r.142]

**Comment by Mugen87** [comment]
> Ideally, it should not include either of them.

`Reflector` renders the scene from a virtual camera to a render target and then projects the respective texture onto its surface. The reflector's shader (which performs the projection) is equivalent to built-in materials, meaning it's fragment shader has to output the color in the same space defined in `renderer.outputEncoding`. 

If `encodings_fragment` is going to be removed, how would be the color conversion be implemented?

**Comment by WestLangley** [comment]
>The reflector's shader (which performs the projection) is equivalent to built-in materials

@Mugen87 You are correct. That is a very good way of thinking about it. Quite frankly, I am not sure what I was thinking...

The reflector should include the tone mapping fragment, however. I hope I at least have that part correct. :-)

**Comment by WestLangley** [comment]
I am inclined to agree with what I intended to say in my original post, but did not say very precisely.

1. When rendering with the virtual camera to the render target texture, rendering should be in scene-referred linear colorspace: no tone mapping, and no encoding (if floating point textures are supported). The render target texture is an HDR texture with linear encoding.

2. When rendering with the real camera, both tone mapping and encoding should be included in the Refractor's shader.
