### ISSUE TITLE
postProcess  TAARenderPass become pale

### ISSUE THREAD

**Issue by luojiong** [mrdoob/three.js#24387]
**Describe the bug**

I am using "taapass" according to the case of threejs' official website, but I find it is different from the example. I have the phenomenon of all white here

sampleLevel =  5.0 
<img width="739" alt="1658916455559" src="https://user-images.githubusercontent.com/28083937/181221790-515a3288-8334-4c52-83d7-bb56aa5143c7.png">
sampleLevel = 0.0
<img width="802" alt="1658916521510" src="https://user-images.githubusercontent.com/28083937/181221988-dff0a8fa-644c-4068-831f-b74074bb8e3d.png">

3. See error

***Code***

```js
 this.composer = new EffectComposer(this.renderer);
        // const pass = new SMAAPass( this.width * this.renderer.getPixelRatio(), this.height * this.renderer.getPixelRatio() );
        // this.composer.addPass( pass );
        let renderPass = new RenderPass(this.scene, state.activeCamera);
        renderPass.enabled = false;
        this.composer.addPass( renderPass );
        let copyPass = new ShaderPass( CopyShader );
        this.composer.addPass( copyPass );
        let taaRenderPass = new TAARenderPass( this.scene, state.activeCamera, 0xffffff,1);
        taaRenderPass.unbiased = false;
        taaRenderPass.sampleLevel = 5;
        this.composer.addPass( taaRenderPass );
        this.renderer.setSize( window.innerWidth,  window.innerHeight);
        this.composer.setSize(  window.innerWidth,  window.innerHeight );
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hbfpj2wv/2/)
* [jsfiddle-dev](https://jsfiddle.net/086yzvgc/)

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: "^0.142.0",

**Comment by donmccurdy** [comment]
Related:

- https://github.com/mrdoob/three.js/issues/24318

You may be able to work around the problem by avoiding the conditions mentioned in that issue.

**Comment by luojiong** [comment]
@donmccurdy  Thank you for your answer, but I also encountered this situation when using SSAA, and I need my background color to be white, which is the demand of design. I have no choice

**Comment by Lipacinp** [comment]
The problem on my side was coming from html background.

Set your canvas background color to black in CSS.

This bugs occurs on my side since the buffer use alpha for SSAA and TAA (RGBFormat --> RGBAFormat).

#24239

**Comment by luojiong** [comment]
@Lipacinp  Thank you for your answer. I'll try it first

**Comment by Mugen87** [comment]
Merging this issue into #24318.

**Comment by luojiong** [comment]
I have solved the problem by setting the background color of "body" to black   thanks ！
