### ISSUE TITLE
 nrrd loader is positioned at origin 0,0,0 of the scene

### ISSUE THREAD

**Issue by ecabaner** [mrdoob/three.js#24393]
When loading an NRRD file is positioned at the origin 0,0,0 of the scene. Its default position is actually defined in the header in the space_origin field and space (LPS, RAS....) but it is not established, losing the reference with the rest of the elements.

**Comment by Mugen87** [comment]
The loader returns an instance of `Volume` so it's not possible to directly set the space origin as the position of the volume meshes.

However, the volume allows access to all header data. Is it possible to solve your issue by extracting the origin from `volume.header.space_origin` and apply these data to the `position` property of volume/slice meshes?

**Comment by ecabaner** [comment]
This is the implementation:

`const loader = new THREE.NRRDLoader();
        loader.load(path, function(volume) {
            const space_origin = volume.header.space_origin;

            let nrrObject = new THREE.Object3D();
            // x plane
            const sliceX = volume.extractSlice('x', Math.floor(volume.RASDimensions[0] / 2));
            nrrObject.add(sliceX.mesh);

            // y plane
            const sliceY = volume.extractSlice('y', Math.floor(volume.RASDimensions[1] / 2));
            nrrObject.add(sliceY.mesh);

            // z plane
            const sliceZ = volume.extractSlice('z', Math.floor(volume.RASDimensions[2] / 4));
            nrrObject.add(sliceZ.mesh);

            let boundingBoxSize = new THREE.Vector3();
            sliceZ.mesh.geometry.computeBoundingBox();
            sliceZ.mesh.geometry.boundingBox.getSize(boundingBoxSize);
            const sizeX = boundingBoxSize.x;
            const sizeY = boundingBoxSize.y;
            sliceY.mesh.geometry.computeBoundingBox()
            sliceY.mesh.geometry.boundingBox.getSize(boundingBoxSize);
            const sizeZ = boundingBoxSize.y;

            const nrrDisplacement = new THREE.Vector3(sizeX / 2, sizeY / 2, sizeZ / 2);

            const nrrReferencePoint = new THREE.Vector3(parseFloat(space_origin[0]), parseFloat(space_origin[1]), parseFloat(space_origin[2]));
            nrrObject.position.copy(nrrReferencePoint.clone().add(nrrDisplacement));
            nrrObject.rotation.z = Math.PI;
            nrrObject.visible = true;

            scene.add(nrrObject);
        }, null, function(e) {
            
        });`
