### ISSUE TITLE
trying to import GLTFExporter in NX after threeJS 136 throws an error

### ISSUE THREAD

**Issue by russ0133** [mrdoob/three.js#24403]
**Describe the bug**

After importing GLTFExporter using the NX Bundler after ThreeJS 136 throws an error regarding needing a loader to load "material.aoMap?.image", this doesn't happen in any version before that.

**To Reproduce**

1. Create an NX project.
2. Install ThreeJS 136+
3. Try importing GLTFExporter
4. Run the app

***Code***

Simply 
`import { GLTFExporter, GLTFExporterOptions } from 'three/examples/jsm/exporters/GLTFExporter.js';.
`
**Expected behavior**

It should import normally as far as everything is concerned.

**Screenshots**

![image](https://user-images.githubusercontent.com/26175960/181771836-b1cda88a-7842-4998-92d0-b5c325ecc116.png)

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome
 - Three.js version: r136

**Comment by Mugen87** [comment]
It seems NX Bundler has problems with the `?.` syntax. I suggest you file an issue at the NX project since there are no plans to revert the usage of optional chaining.

**Comment by russ0133** [comment]
This turned out to be the problem, thanks. I'll make a ThreeJS fork without the ?. syntax until they fix this issue.
