### ISSUE TITLE
Duplication of text on the Installation documentation page

### ISSUE THREAD

**Issue by AngyDev** [mrdoob/three.js#24404]
Hello,

on the Installation page, as we can see in the image there is duplicate text. I'm not sure it is a problem, but maybe it is possible to remove one of the two. 

What do you think?

<img width="730" alt="Schermata 2022-07-29 alle 19 29 59" src="https://user-images.githubusercontent.com/44018650/181814493-e307747b-fe7b-4676-b871-86235e441e77.png">

**Comment by Mugen87** [comment]
Good catch! I think the second paragraph in the `Install from CDN or static hosting` section can be removed.

Would you like to make a PR and remove it from all pages?

**Comment by AngyDev** [comment]
Yes, of course!! 😊
