### ISSUE TITLE
FBXLoader: Fbx Models containing .tif-format textures do not work

### ISSUE THREAD

**Issue by 0x233-lh** [mrdoob/three.js#24416]
hey
When I use an fbx model with a .tif-format texture, I find that the texture is not displayed on the browser. This raises some questions, and I hope to find answers.

1. Why wasn't support for .tif-format textures considered?
  After consulting some information and related issues(#436), I learned that many browsers do not natively support .tif-format textures. By observing the source code of `ImageLoader`, I found that three.js works by displaying images through `img` tags.
  Is it possible to make three.js support .tif-format by extending `ImageLoader`? In fact, I made the image display by modifying the `ImageLoader` component, using `tiff.js` to load the `tiff resource`, and using canvas to convert it to `png`.

2. Another problem is derived from the above problem. `FBXLoader` does not seem to provide any extensibility. Each subcomponent is directly `new` in the method. When I want to modify or extend the logic of some subcomponents, I have to put the entire `FBXLoader` Taking it out for modification alone makes the modification cost very large and is not conducive to subsequent maintenance. May I ask if this is the original intention of the original design (do not want others to modify the source code) or other reasons?

**Comment by Mugen87** [comment]
> Is it possible to make three.js support .tif-format by extending ImageLoader?

No, I don't think that's a good idea. You really should not use `tif` in `FBX` assets but switch to something the browser can understand like JPG or PNG.  It's even better to convert the FBX asset to glTF and compress textures with the respective tools. 

> May I ask if this is the original intention of the original design (do not want others to modify the source code) or other reasons?

Adding extensibility and flexibility means modules tend to become more complex. The project favored simplicity in the past for various reasons. So the idea is that you copy `FBXLoader` to your project and add you custom modifications.

**Comment by 0x233-lh** [comment]
@Mugen87

**Comment by 0x233-lh** [comment]
@Mugen87 
Thank you for your answer.

There are many scenes using .tif-format textures in the game field, and my project is only for previewing character modeling made by game modelers, and their models are all .tif-format textures.

Of course, extra things can be done for a better preview (such as converting the texture format of the model), here is to find a simpler method, so there are the above problems.

**Comment by mrdoob** [comment]
If there's some open source code for loading tiff we could do a `TIFFLoader` like the [`TGALoader`](https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/TGALoader.js)... 🤔

**Comment by 0x233-lh** [comment]
> If there's some open source code for loading tiff we could do a `TIFFLoader` like the [`TGALoader`](https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/TGALoader.js)... 🤔

You can learn about the `tiff.js` project, but this is a compromise solution found on the Internet. I am not sure whether there are bugs or whether there is any performance impact.
Just a suggestion. 😁

**Comment by Mugen87** [comment]
@mrdoob We use a modified version of [UTIF.js](https://github.com/photopea/UTIF.js/) to load LogLuv HDR textures. I guess we could use the unmodified `UTIF.js` inside a `TIFFLoader`.

**Comment by Mugen87** [comment]
If you okay with `UTIF.js`, I'll file a PR 👍 .

**Comment by mrdoob** [comment]
Let's do it 👌
