### ISSUE TITLE
There is a bug in editing page fog switching

### ISSUE THREAD

**Issue by pai16858** [mrdoob/three.js#24438]
![视频](https://user-images.githubusercontent.com/26533053/182585226-c5534ae0-761c-426a-bc47-ade1c9c7fb3c.gif)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r???]

**Comment by LeviPesin** [comment]
Could you please describe the issue?

**Comment by Mugen87** [comment]
@LeviPesin Not necessary. The gif already demonstrates the issue.
