### ISSUE TITLE
merge method in BufferGeometry class should automatically compute correct value for the offset parameter, not default it to zero when it is not provided.

### ISSUE THREAD

**Issue by philipswan** [mrdoob/three.js#24443]
**Is your feature request related to a problem? Please describe.**
Yes, the .merge() method includes an optional "offset" parameter. If this is not provided, then merge defaults this offset to zero, which causes an overwrite instead of a merge. 

Some discussions seem to suggest that the offset parameter is a matrix, which seems like a logical assumption to make. Unfortunately, this is not how the actual implementation works. Therefore the "literature" and "logic" are not consistent with the actual implementation, and this leads to confusion. 

**Describe the solution you'd like**
1) If the "offset" argument is not provided, then a merge should occur, not an overwrite.
2) I do not understand the point of having an optional offset argument that is an integer, so this optional argument should be removed.
3) I do understand the idea of an optional argument that applies a matrix to the merged geometry, but I would rather see an example in the documentation that simply shows users how to apply the matrix transform to the geometry that is being merged.

Fix merge, remove the optional "offset" argument. Add documentation to the .merge method to show the correct procedure for transforming the geometry that is being merged.

**Describe alternatives you've considered**
Fix merge, change the second optional "offset" argument to be a matrix instead of an integer.

**Additional context**

**Comment by Mugen87** [comment]
> If the "offset" argument is not provided, then a merge should occur, not an overwrite.

Instead of changing the semantics of `BufferGeometry.merge()` , I suggest you are just using [BufferGeometryUtils.mergeBufferGeometries()](https://threejs.org/docs/index.html#examples/en/utils/BufferGeometryUtils.mergeBufferGeometries).

**Comment by Mugen87** [comment]
> I do not understand the point of having an optional offset argument that is an integer

The `offset` parameter does not represent an offset in 3D space but an offset in the attribute buffer.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help in context of geometry merging.

**Comment by philipswan** [comment]
I did already figure out that mergeBufferGeometries() works better, and ended up using that. The reason I opened this issue is that the broken state of "merge" (and all the people on StackExchange who have provided broken examples of how to use it) has caused myself and others to waste a lot of time trying to do something that _should_ be relatively simple. I'm not looking for help. I'm trying to correct the root cause of the problem so that in the future other people do not lose time over this. I urge you to keep this issue open until it is properly resolved.

**Comment by Mugen87** [comment]
@mrdoob Should we remove `BufferGeometry.merge()`? I think this method was originally added as a pendant for `Geometry.merge()`

**Comment by gkjohnson** [comment]
For what it's worth I feel like `BufferGeometry.merge` should just be removed at this point. The `BufferGeometryUtils` merge APIs are much more usable.

**Comment by donmccurdy** [comment]
I think I agree with removing it, or moving it (with a new name) to BufferGeometryUtils. The method could be renamed to something like `setBufferAt( geom, offset = 0)`, but I haven't found myself using it. We could do a more expressive geometry-building API in other ways, like #22376.
