### ISSUE TITLE
Color: Support HSL percentage values with decimals.

### ISSUE THREAD

**Issue by JackCA** [mrdoob/three.js#24441]
**Describe the bug**

Using decimal values for `saturation` or `lightness` in an HSL colors lead to `Unknown color` warning

**To Reproduce**

see live example

***Code***

```js
new THREE.Color('hsl(209, 95.0%, 90.1%)')
```

***Live example***

https://jsfiddle.net/4v1rp8d0/9/

**Expected behavior**

The color should be properly parsed. It looks like [this regex is the issue](https://github.com/mrdoob/three.js/blob/dev/src/math/Color.js#L225)

[According to the MDN docs for `percentage`, decimals are supported for `number`](https://developer.mozilla.org/en-US/docs/Web/CSS/number).

**Comment by Mugen87** [comment]
I have always thought percentage values for saturation and lightness are integers. If this is not exactly defined in the CSS spec, I would not change the current implementation.

**Comment by JackCA** [comment]
If I’m reading the spec correctly, `percent` contains `number` which supports decimal values: https://www.w3.org/TR/css-values-4/#number-value

**Comment by Mugen87** [comment]
Related https://stackoverflow.com/questions/5723225/in-css-can-hsl-values-be-floats.

It seems you are right. Consider this issue as a feature request.

**Comment by Mugen87** [comment]
In the meanwhile, I've filed a PR: #24461 😇
