### ISSUE TITLE
Calculate planeGeometry with image size in pixels

### ISSUE THREAD

**Issue by kamildul** [mrdoob/three.js#24449]
**Is your feature request related to a problem? Please describe.**

Yes, i need display image in scene in real size without scale. I dont know how i can add this image in scane with textureLoader and how i can calculate planeGeometry. My image size have 3976px / 2392px. In the moment wen i add image with terture a have very blured result. The problem is serious, i want load terrain map:

![obraz](https://user-images.githubusercontent.com/108399119/182852106-2f375474-1e04-4834-b7bb-c24105c954f3.png)

**Describe the solution you'd like**

Convert pixels to threejs unit. I want to use pixels to define the size planeGeometry

**Describe alternatives you've considered**

--

**Additional context**

--

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
