### ISSUE TITLE
CMYK images don't work as textures on iPhone

### ISSUE THREAD

**Issue by ritwaldev** [mrdoob/three.js#24459]
**Describe the bug**

When an image has CMYK color mode and is used as texture, the texture won't show on iPhone IOS 15.5. Tested with Safari and iPhone Chrome. They work just fine on PC browsers. 

I explicitly tested with images converted to CMYK color mode using Photoshop (from PSD main menu >> image >> mode >> CMYK color).

**To Reproduce**

Use any CMYK image as texture and check from an iphone device.

***Code***

```js
// CMYK img - doesn't work in iphone
const geometry = new THREE.BoxGeometry(1, 1, 1);
const texture = new THREE.TextureLoader().load("img-cmyk.jpg");
const material = new THREE.MeshBasicMaterial({ map: texture });
const cube = new THREE.Mesh(geometry, material);
```

***Live example***

* https://ritwaldev.github.io/testThree/

***repo***

* https://github.com/ritwaldev/testThree

**Expected behavior**

CMYK images should be supported on iPhone. If not, docs should clearly state that to avoid potentially very confusing bugs. 

**Screenshots**

PC:
![PC](https://user-images.githubusercontent.com/94167701/183240654-9d93d1db-4eb0-4417-9664-7da407735755.png)

iPhone:
![iPhone](https://user-images.githubusercontent.com/94167701/183240686-0085e774-4146-4713-9da2-028c9ece76f1.png)

**Platform:**

 - Device: Mobile
 - OS:  iOS 15.5
 - Browser: Chrome, Safari
 - Three.js version: [r143](https://github.com/mrdoob/three.js/releases/tag/r143)

**Comment by Mugen87** [comment]
> CMYK images should be supported on iPhone. If not, docs should clearly state that to avoid potentially very confusing bugs.

We do normally not note device specific restrictions in the API documentation.

What is you motivation for using CMYK in the web?

**Comment by ritwaldev** [comment]
No particular reason. I just used an image I downloaded from somewhere (there are many CMYK images out there) and couldn't get my texture to load. I then went above and beyond trying to debug and was surprised when I used another image in the process and it worked. I then started investigating why that particular image had issues with iPhone and found that CMYK color mode was the root of the issue.

**Comment by Mugen87** [comment]
The thing is that CMYK is not intended for the web. For web and apps in general, stick to RGB and use image formats like JPG or PNG.

**Comment by ritwaldev** [comment]
@Mugen87 I know, just saying that there could be cases where this would can cause some pain.

For example, we are working on a project where mock-ups are automatically generated by three.js from user submitted images.

A lot of users are artists and I would guess a lot of the images will be coming in in CMYK.

Also, I imagine many other devs won't have "RGB vs CMYK" in mind when debugging texture issues.

Knowing this now, I am sure we can figure something out. 

Thanks for your input.

**Comment by Mugen87** [comment]
I'm afraid you have to handle this use case on app level. I don't think it's appropriate to implement something in `ImageLoader` nor enhance the API documentation.

**Comment by donmccurdy** [comment]
The Color Management page mentions that we use the RGB color model, though other inputs are supported for material parameters (not textures). Additionally textures are expected to use one of the supported color spaces. Additions could be made to this page if needed.

**Comment by mrdoob** [comment]
> When an image has CMYK color mode and is used as texture, the texture won't show on iPhone IOS 15.5

Seems like this is an iOS issue anyway. Please, report this to Apple instead.
