### ISSUE TITLE
Raycasting: Wrong intersection point when scene rotated

### ISSUE THREAD

**Issue by JonasGoebel** [mrdoob/three.js#24456]
`THREE.Raycaster.intersectsObject()` returns no or wrong intersection coordinates when the `THREE.scene` is rotated using `scene.rotation.x = 270 * (Math.PI / 180)`.

**To Reproduce**

Steps to reproduce the behavior (or checkout live example):
1. Create a scenario where a Raycaster is set to go clearly through an object
2. Test intersection results => `Raycaster.intersectsObject()` should return the correct intersection coordiates
3. Add `scene.rotation.x = 270 * (Math.PI / 180)` after creating scene or anywhere before calculating intersections
4. Test intersection results => `Raycaster.intersectsObject()` should return no intersections or intersections with wrong coordinates

**Demonstration**
red cube: raycaster starting point  
blue cube:   raycaster destination point  
green point: calculated intersection  
yellow arrow: raycaster direction vector  

***Code***

```js
scene.rotation.x = 270 * (Math.PI / 180)

const raycaster = new THREE.Raycaster(position, p2, 0.1, 10)

const arrowHelper = new THREE.ArrowHelper(raycaster.ray.direction, raycaster.ray.origin, 4, 0xffff00)
scene.add(arrowHelper)

renderer.render(scene, camera)

const intersects = raycaster.intersectObject(cube, false)

// mark each intersection with a little cube
intersects.forEach((intersection) => createCube(intersection.point, 0x00ff00, 0.1))

```

***Live example***

Comment out line 46 (scene rotation) to see the effect
* [jsfiddle-dev](https://jsfiddle.net/6jhpk5vd/)

**Expected behavior**

The cube should have the same coordinates even if the scene is rotated.

**Screenshots**
See demonstration for a legend of the colored cubes
normal scene: intersection works:  
![SceneWithoutRotation](https://user-images.githubusercontent.com/33429771/183129070-0c8f621c-68ec-4396-8e08-2b7230b62f53.png)

rotated scene: intersection is behind intersection:  
![SceneWithRotation](https://user-images.githubusercontent.com/33429771/183129056-1459b9c0-d420-4071-ad50-9054a6fc443e.png)

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome, Firefox
 - Three.js version: r143, dev

**Comment by gkjohnson** [comment]
Raycasting is not performed in the scene frame or root frame. It's performed in the world frame after all `matrixWorld` transformations are applied. If you'd like to get the intersection point in the local frame of the scene you can apply the inverse of scene matrix world to the point.

**Comment by Mugen87** [comment]
@JonasGoebel Please use the [forum](https://discourse.threejs.org/) if you need more help.
