### ISSUE TITLE
Defines in cube_uv_reflection_fragment can break MeshPhongMaterial

### ISSUE THREAD

**Issue by CodyJasonBennett** [mrdoob/three.js#24469]
**Describe the bug**

Short defines such as those in [`cube_uv_reflection_fragment`](https://github.com/mrdoob/three.js/blob/9e5512f067e3a0de8d4069217d20903c1725edf7/src/renderers/shaders/ShaderChunk/cube_uv_reflection_fragment.glsl.js#L119) can clash with user-defined materials via `ShaderMaterial` and built-in materials that use [`bsdfs`](https://github.com/mrdoob/three.js/blob/9e5512f067e3a0de8d4069217d20903c1725edf7/src/renderers/shaders/ShaderChunk/bsdfs.glsl.js#L150) (related: #22728).

**To Reproduce**

The above behavior can be reproduced when passing a texture from `PMREMGenerator` to a `MeshPhongMaterial` via `envMap`.

***Code***

```js
import * as THREE from 'three';
import { RGBELoader } from 'three/examples/jsm/loaders/RGBELoader.js';

const renderer = new THREE.WebGLRenderer();

new RGBELoader().load( '/lago_disola_1k.hdr', ( texture ) => {

  const envMap = new THREE.PMREMGenerator( renderer ).fromEquirectangular( texture ).texture;

  const geometry = new THREE.BoxGeometry();
  const material = new THREE.MeshPhongMaterial( { envMap } );
  const mesh = new THREE.Mesh( geometry, material );
  renderer.compile( mesh );

});
```

***Live example***

* [https://codesandbox.io/s/1b9mv3](https://codesandbox.io/s/1b9mv3)

**Expected behavior**

Defines in `cube_uv_reflection_fragment` should be more specific and probably follow the existing local `cubeUV_*` pattern.

**Screenshots**

![image](https://user-images.githubusercontent.com/23324155/183439750-a7620c49-4474-42dd-8b78-fb63feba99d2.png)

**Platform:**

 - Device: [N/A]
 - OS: [N/A]
 - Browser: [N/A]
 - Three.js version: [r143, since #18004]

**Comment by WestLangley** [comment]
MeshPhongMaterial and MeshLambertMaterial do not support PMREM cube maps.

That shader chunk should not be there. Right?

**Comment by WestLangley** [comment]
@Mugen87 Would you like me to remove `cube_uv_reflection_fragment` from Basic, Lambert, and Phong?

**Comment by Mugen87** [comment]
Yes, that makes sense.

**Comment by WestLangley** [comment]
@Mugen87 ...and what is the current policy on using a PMREM as a background texture? My understanding is the decision was to not support PMREMs as a background. This decision has implications for maintenance of the fragile shader chunks.

**Comment by Mugen87** [comment]
> and what is the current policy on using a PMREM as a background texture?

Since we want to support background blurriness at some point, the engine potentially needs PMREM support for the background shader. #23712 implemented this feature with normal mipmaps, however, other engines actually use PMREM. So this question has to be decided first before we can update the background shader.

**Comment by WestLangley** [comment]
@Mugen87 @mrdoob  Please understand that the issue in this PR was caused by the OP using a PMREM with `MeshPhongMaterial`, which  is not supported.

**Comment by CodyJasonBennett** [comment]
> @Mugen87 @mrdoob Please understand that the issue in this PR was caused by the OP using a PMREM with MeshPhongMaterial, which is not supported.

I think this issue is pretty clearly about loose defines made in `cube_uv_reflection_fragment` which can only cause trouble with built-in materials and user-defined materials -- `bsdfs` being merely an example.

If `MeshPhongMaterial` (and also `MeshLambertMaterial` & `MeshPhysicalMaterial`) aren't supposed to include `cube_uv_reflection_fragment` then remove it, but it's not the focus of this issue.
