### ISSUE TITLE
Suggestion: Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by Shekhar505** [mrdoob/three.js#24473]
Hey there!! I'm a Newbie to this community and like me thousands are interested to join this awesome community based on threeJS. So for a newbie to get started I would like to suggest adding a CONTRIBUTING FILE so that things works smoother and this community gets more talents and smart people's out there. Thank you!

**Comment by gkjohnson** [comment]
There's information on getting started in the wiki:

https://github.com/mrdoob/three.js/wiki

**Comment by mrdoob** [comment]
It's here: https://github.com/mrdoob/three.js/blob/dev/.github/CONTRIBUTING.md
