### ISSUE TITLE
ArcballControls - Extra rotation after recreating the controls

### ISSUE THREAD

**Issue by Yincognyto** [mrdoob/three.js#24476]
**Describe the bug**

If a camera rotation is performed using ArcballControls _before_ recreating the controls, an extra rotation  happens after releasing the mouse on subsequent rotations. If no camera rotation is performed before recreating the controls, everything works fine.

**To Reproduce**

1. Create a basic Three.js setup 
2. Add ArcballControls to it
3. Make some function / logic to recreate the controls on demand
4. Launch the page and rotate camera around
5. Trigger the controls' re-creation function / logic
6. Try to rotate camera around again
7. Notice the extra rotation after releasing the mouse button

***Code***

```js
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <style>
      body {margin: 0;}
    </style>
  </head>
  <body>
    <script type="importmap">
      {
        "imports":
        {
          "three": "http://localhost:8080/three.module.js",
          "ArcballControls": "http://localhost:8080/ArcballControls.js"
        }
      }
    </script>
    <script type="module">
      import * as THREE from "three";
      import {ArcballControls} from "ArcballControls";
      var scene, camera, light, renderer, earth, controls, reqid, paused = false;
      function createcontrols()
      {
        controls = new ArcballControls(camera, renderer.domElement, scene);
        controls.addEventListener("change", function(e) {renderer.render(scene, camera); controls.update();});
      };
      function create()
      {
        renderer = new THREE.WebGLRenderer({antialias: true, alpha: true});
        renderer.setSize(window.innerWidth, window.innerHeight);
        document.body.appendChild(renderer.domElement);
        camera = new THREE.PerspectiveCamera(70, window.innerWidth / window.innerHeight, 0.1, 100);
        camera.position.set(0, 0, 1.75);
        light = new THREE.AmbientLight("rgb(255, 255, 255)");
        light.position.copy(camera.position);
        var geometry = new THREE.SphereGeometry(1, 360, 180);
        var material = new THREE.MeshPhongMaterial();
        material.map = new THREE.TextureLoader().load("http://localhost:8080/Earth.png");
        material.displacementMap = new THREE.TextureLoader().load("http://localhost:8080/Earth - Height.png");
        material.displacementScale = 0.002 * 99;
        earth = new THREE.Mesh(geometry, material);
        scene = new THREE.Scene();
        scene.add(camera);
        scene.add(light);
        scene.add(earth);
        createcontrols();
        document.addEventListener("keyup", function(e)
        {
          switch (e.code)
          {
            case "KeyP": console.log("P"); paused = !paused; if (!paused) {animate();} else {stagnate();}; break;
            case "KeyR": console.log("R"); controls.dispose(); controls = undefined; createcontrols(); renderer.render(scene, camera); controls.update(); break;
          };
        }, {passive: false});
      };
      function animate()
      {
        if (paused) {return;};
        requestAnimationFrame(animate);
        earth.rotation.y += 0.01;
        renderer.render(scene, camera);
      };
      function stagnate()
      {
        if (!paused) {return;};
        cancelAnimationFrame(reqid);
      };
      create();
      animate();
    </script>
  </body>
</html>
```

***Live example***

None

**Expected behavior**

For the simpleton code above, drag to rotate the globe, press the R key to recreate ArcballControls, then rotate again to see how it "jumps" to a new rotation after releasing the mouse. I expect that the jump does not happen (like it doesn't for the other controls). My actual usage scenario is switching from one control to another (all 8 included in my code) on some mouse scroll, by the way - I chose to illustrate recreating the controls in the interest of simplicity. Let me know if this can be replicated, or if by any chance there is something obvious missing from the code above (like updating some matrix and such) that fixes the issue.

**Screenshots**

None

**Platform:**

 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome, Edge WebView2 via the [WebView plugin](https://github.com/khanhas/PluginWebView) for [Rainmeter](https://www.rainmeter.net/)
 - Three.js version: r.140, r.143

**Comment by Mugen87** [comment]
> controls.addEventListener("change", function(e) {renderer.render(scene, camera); controls.update();});

I don't think this code is right. `controls.update();` should not be called at this place.

**Comment by Yincognyto** [comment]
> > controls.addEventListener("change", function(e) {renderer.render(scene, camera); controls.update();});
> 
> I don't think this code is right. `controls.update();` should not be called at this place. Same in the `KeyR` code.

Fair enough, I'm aware that `controls.update();` isn't suited to be placed in a `change` event of the controls, I faced that issue with some of the other controls, which entered an infinite loop because of that (some stack error and such), forcing me to add other mouse event listeners just to place `controls.update();` there and update things outside the animation loop.

However, it doesn't cause any problems for ArcballControls apparently, which is why I used it there (it's my favorite control and I use it often, so I would have noticed any irregularity if that was the case). Not to mention that it doesn't solve the problem - the rotation jump still happens when I comment out `controls.update();`, albeit starting with the second recreation of the controls (right on pressing R to recreate, after rotating stuff), skipping the first. What led me to post it here is that the issue doesn't happen for the other controls, only for this one, which is a pitty cause I like it very much. The others work perfectly when recreating or switching between one another.

**Comment by Mugen87** [comment]
Live example: https://jsfiddle.net/8ohk0376/

**Comment by Yincognyto** [comment]
> Live example: https://jsfiddle.net/8ohk0376/

Thanks for posting a live example - I skipped that since the code and replacing texture sources were trivial.
Now it's quite obvious how starting from the 2nd occurence of a [drag + R] user action, the rotation jump happens.
I assume that based on the posted live example, you were able to reproduce the issue. Will wait for updates on this.

**Comment by Mugen87** [comment]
After some debugging it's now clear what causes the issue.

Unlike `OrbitControls`, `ArcballControls` allows to move the camera over the poles by modifying the camere's up vector. When you just dispose the controls, the camrea's up vector is left modified and not resetted to its original value (normally 0,1,0). When you now recreate the controls, the internal state variables are getting mixed up since you not call `controls.reset()`. 

The reset is mandatory since the controls have to know the original up vector of the camera during their creation. So it's actually best if you perform a manual call of `reset()` before calling `dispose()`. Otherwise you have to modify some internal variables like so: https://jsfiddle.net/umsthaxr/3/

In general, try to avoid to dispose/create controls over and over again and just enable/disable controls via the `enabled` property. Besides, never mix an animation loop with on-demand rendering like in your fiddle. When the animation loop is active, you render more frames than necessary since your `change` event listener still triggers calls of `render()`.

**Comment by Yincognyto** [comment]
> After some debugging it's now clear what causes the issue...

Great to hear that you figured out where the issue came from and what needed to be done to fix it, in such a short time - many thanks! Indeed, it makes sense for the controls to behave that way if the values of some needed variables are lost in the recreating process.

I settled for modifying those internal variables instead of resetting because I just can't have one of my controls messing the user's current rotation (reset or no reset), and after all, it's not the first time I had to do this with ArcballControls, having to toggle the gizmos visibility using a similar internal variable via `controls.setGizmosVisible(!controls._gizmos.visible);`. Right now, in my actual code, I have the global variable `cup = new THREE.Vector3().copy(camera.up);` when instantiating the camera (see, I can reuse variables too), and added `controls._up0.copy(cup); controls._upState.copy(cup);` directly to the ArcballControls section of my controls building function. Everything works perfectly now - I appreciate that you included the alternative in the fiddle.

As for the general advice, it's a good one. Thing is, recreating the controls is part of a bigger function which recreates all kinds of objects in my scene based on user preference (e.g. don't create earth at all, create it the standard Phong way, or create it using shaders for night lights, and similar systems for the rest of the objects) so it made sense to be consistent and approach controls the same way - some things are just not possible to refactor via toggling a `.enabled` or `.visible` setting. I'll consider taking the easy route where possible though.

Yes, I'm aware the animation / on-demand mixing in the code can be done better, and will look to improve the process when the time comes - thanks for pointing that out. Currently, I'm already mixing the (automatic) simulation / animation with on demand actions in practice, since the extra rendering done on demand is not at the same frequency as the animation loop and hardly overkill, not to mention that generally the on demand actions are supposed to be done when the animation is stopped (hence the pause system in the above code).

As a side note, I saw that you corrected some things in the ArcballControls disposing system in r142. You might be interested to know that TransformControls does also leave some leftovers when disposing, mainly the gizmos (named "controls"). Currently I handle that by:

```js
try {
  scene.getObjectByName("controls").traverse(function(o) {
    try {o.geometry.dispose();} catch {};
    try {o.material.dispose();} catch {};
    try {for (var m of o.material) {m.dispose();};} catch {};
  });} catch {};
try {scene.remove(scene.getObjectByName("controls"));} catch {};
```

but you might consider implementing it properly by default via one or two lines added to that control. Not serious enough for a bug report here, I just thought that you should know. Cheers, and thanks to all the team for making Three.js available to us users!
