### ISSUE TITLE
How does masking with EffectComposer work?

### ISSUE THREAD

**Issue by ViliamKopecky** [mrdoob/three.js#2448]
I spent awful lot of time with `examples/webgl_postprocessing.html` but I cannot figure out how to work with masks (EffectComposer, MaskPass, etc.). Maybe I think of them the wrong way - the photoshop way. I'm trying to achieve this:

![Example of masking](https://dl.dropbox.com/u/105619924/three.js/masking.png)

I would expect usage like this

```javascript

function init() {
	// ...

	// full render
	renderSceneA = new THREE.RenderPass(sceneA, cameraA);
	renderSceneB = new THREE.RenderPass(sceneB, cameraB);

	// rendering masks
	renderMaskA = new THREE.RenderPass(maskA, maskCameraA);
	renderMaskB = new THREE.RenderPass(maskB, maskCameraB);

	// MaskPass would crop the rendered scene with mask
	// finalComposer would layer up the passes on each other
	finalComposer.addPass(new THREE.MaskPass(renderSceneA, renderMaskA));
	finalComposer.addPass(new THREE.MaskPass(renderSceneB, renderMaskB));

	// ... render to screen etc.
}

function render() {
	finalComposer.render();
}
```

When I understand this, I would be happy to write some example / tutorial / blogpost about it.

**Comment by tripdragon** [comment]
2015 well 2016 now. If no one has done this I'm about to try and will provide an example. But Soooooo hoping someone has one already.

**Comment by mrdoob** [comment]
`webgl_postprocessing_masking.html` should be a easier example to follow.

**Comment by tripdragon** [comment]
Perfect! Thank you. For others at this time its in the dev branch
