### ISSUE TITLE
Nodes Material UV error

### ISSUE THREAD

**Issue by sdarpeng** [mrdoob/three.js#24484]
- Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [ r130]

The model in blender is like this.
![微信截图_20220810155335](https://user-images.githubusercontent.com/55733077/184016784-4fe0db73-5063-4f4f-b03d-f77fe3a110da.png)

I drew 1,2,3,4,5,6 on each side of the texture.

`			const loader = new GLTFLoader();
			loader.load( 'models/gltf/testbox.glb', function ( gltf ) {
			model = gltf.scene;
			scene.add( model );
                    mixer = new THREE.AnimationMixer( model );
                    const action = mixer.clipAction(gltf.animations[0]);
                    action.play();  
                    face = model.getObjectByName('Cube');
                    mtl = new Nodes.PhongNodeMaterial();
                    var tex1 = new Nodes.TextureNode( getTexture( "cubeA" ) );
                    var tex2 = new Nodes.TextureNode( getTexture( "brick" ) );
    /*                 var offset = new Nodes.FloatNode( 0 );
                    var scale = new Nodes.FloatNode( 1 ); */
                    //var uv = face.geometry.attributes.uv;
    /*                 console.log(uv);

                    var uvOffset = new Nodes.OperatorNode(
                        offset,
                        uv,
                        Nodes.OperatorNode.ADD
                    );

                    var uvScale = new Nodes.OperatorNode(
                        uvOffset,
                        scale,
                        Nodes.OperatorNode.MUL
                    );  */

                    var mask = new Nodes.TextureNode( getTexture( "alpha_mixer"));
                    //var maskAlphaChannel = new Nodes.SwitchNode( mask, 'w' );

                    var blend = new Nodes.MathNode(
                        tex1,
                        tex2,
                        mask,
                        Nodes.MathNode.MIX
                    );
                    mtl.color = blend;
                    face.material = mtl;

`

But the programs works as this.
![微信截图_20220810155350](https://user-images.githubusercontent.com/55733077/184016861-ee76f89d-6cc0-4fcd-b876-6b9c2d4d3b99.png)

Obviously, the UV of the model was mirrored on Y channel and even face 3 and face 6 disappeared.

Here is my source code and resources.
Textures:
![brick_diffuse](https://user-images.githubusercontent.com/55733077/184017315-cd111fb9-8829-447e-907b-ac58837a2ff2.jpg)
![testcube](https://user-images.githubusercontent.com/55733077/184017340-d8c80e3e-f01e-4c9f-bc00-495253e33794.png)
![testcubeA](https://user-images.githubusercontent.com/55733077/184017354-46c54969-cba1-4dad-bc53-16b6f3446704.png)
Model:
[testbox.zip](https://github.com/mrdoob/three.js/files/9303942/testbox.zip)
Source Code.
[gltf_animation_nodes.zip](https://github.com/mrdoob/three.js/files/9303949/gltf_animation_nodes.zip)

**Comment by sunag** [comment]
Can you update your three.js lib and use the NodeMaterial system?

**Comment by CaiFanglin** [comment]
斜拉哈
   辛苦啦

**Comment by mrdoob** [comment]
We use GitHub issues to track confirmed bug reports and feature development.
If you need help, please use the [forum](https://discourse.threejs.org/), the [chat](https://discord.gg/HF4UdyF) or [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

**Comment by sdarpeng** [comment]
> Can you update your three.js lib and use the NodeMaterial system?

I upgraded to r143, The result is correct now. Thanks by the way.
