### ISSUE TITLE
there has some problem when i export my scene to plyfile

### ISSUE THREAD

**Issue by the-didi** [mrdoob/three.js#24499]
**Describe the bug**
there has some problem when i trying to export my scene,there has some mesh whitch has been clipped by clipplane,when i trying to export it as an plyfile, the clipped part has been export too，i think the clipped part should not be export。

**To Reproduce**
1. copy the code of [example](https://github.com/mrdoob/three.js/blob/master/examples/webgl_clipping_stencil.html) to your idea
2. and an event to export the scene of this page
3. open the plyfile whitch you export on cloud compare or other software

***Code***
// export code
```js
function exportFunction() {
	const exporter = new PLYExporter();
	const source = exporter.parse(scene);
	downloadFile(source);
}
function downloadFile(source) {
	let aTag = document.createElement('a')
	let blob = new Blob([source])
	aTag.href = URL.createObjectURL(blob)
	aTag.download = 'untitile.ply'
	aTag.click()
	URL.revokeObjectURL(blob)
}
```

**Expected behavior**

when i export my scene to plyfile the cliped part should not be export into my file 

**Screenshots**

![A5_83OG2$NADH $2FJ68)7B](https://user-images.githubusercontent.com/61458828/184615571-22a3bb2c-71cb-4115-a772-93fe5709449a.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows11]
 - Browser: [Edge]
 - Three.js version: [^143]

**Comment by Mugen87** [comment]
Clipping planes are a rendering technique and implemented in shaders. The actual geometry data are not affected by it. No exporters honor the material clipping settings.

**Comment by gkjohnson** [comment]
> Clipping planes are a rendering technique and implemented in shaders. The actual geometry data are not affected by it. No exporter honors the material clipping settings.

Yes there are other techniques for generating geometric clip planes that can be exported, though. But I think that's a better question for the forum:

https://discourse.threejs.org/
