### ISSUE TITLE
editor visibility bug

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#24529]
The thing has started happening quite recently, perhaps today or over the weekend: when you load the model and select the mesh
<img width="960" alt="Снимок экрана (650)" src="https://user-images.githubusercontent.com/242577/186040292-84f19fb1-432b-4786-9bb6-086042b9fb17.png">
then unckeck "visible" box - the mesh is still there:
<img width="960" alt="Снимок экрана (651)" src="https://user-images.githubusercontent.com/242577/186040329-0358b445-46f1-4f46-b3d6-6f66022fcf2a.png">
but once you move the camera, it is fine:
<img width="960" alt="Снимок экрана (652)" src="https://user-images.githubusercontent.com/242577/186040365-68414ecf-8dd1-4d0c-a8ae-28971f4f63ed.png">
Did you maybe add lazy rendering on controls change event? Well it needs to trigger from UI, too.

**Comment by Mugen87** [comment]
> The thing has started happening quite recently, perhaps today or over the weekend:

Strange, there were no recent changes to the editor in production. 

Can you please share the skinned mesh from your screenshots? I cannot reproduce the issue with simple box or plane meshes.

**Comment by makc** [comment]
mugen you could be right, the glb file was edited around this time, too - [here](https://github.com/mrdoob/three.js/files/9402698/Goblin.v3_TshirtExport.zip).

**Comment by Mugen87** [comment]
There is indeed a bug in the editor. A runtime error prevents the object from updating its visibility. I'll file a PR.
