### ISSUE TITLE
Nodes material UV is fliped on y-axis for -1

### ISSUE THREAD

**Issue by sdarpeng** [mrdoob/three.js#24524]
**Describe the bug**

Nodes material UV is rotated on Z-axis in 180 degree.

***Code***

```js
const myUV = mul( uv() ,1  );
const mtl = new Nodes.NodeMaterial.fromMaterial( face.material );

const alphaTexture = new THREE.TextureLoader().load( 'textures/testcube.png' );
alphaTexture.wrapT = THREE.RepeatWrapping;
alphaTexture.wrapS = THREE.RepeatWrapping;
alphaTexture.encoding = THREE.sRGBEncoding;
const alphaNode = new Nodes.TextureNode( alphaTexture, myUV ); 


const textureA = new THREE.TextureLoader().load( 'textures/brick_diffuse.jpg' );
textureA.wrapT = THREE.RepeatWrapping;
textureA.wrapS = THREE.RepeatWrapping;
textureA.encoding = THREE.sRGBEncoding;
const textureANode = new Nodes.TextureNode( textureA, myUV ); 
blendColor = new THREE.Color(0x00ff00);
const textureCNode = new Nodes.OperatorNode( '*', textureANode, new Nodes.UniformNode( blendColor ) );

const textureB = new THREE.TextureLoader().load( 'textures/M1-05.jpg' );
textureB.wrapT = THREE.RepeatWrapping;
textureB.wrapS = THREE.RepeatWrapping;
textureB.encoding = THREE.sRGBEncoding;
const textureBNode = new Nodes.TextureNode( textureB, myUV ); 

mtl.colorNode = mix( textureCNode, textureBNode, alphaNode);
```

**Screenshots**

The original blend factor texture and the UV.
![微信截图_20220823030632](https://user-images.githubusercontent.com/55733077/185999408-535389db-45d0-425b-9329-6617b5bfda4d.png)
![testcube](https://user-images.githubusercontent.com/55733077/185998861-1c5f90bb-9e85-4f87-bc4a-a448268ab65f.png)

The render result.

![微信截图_20220823031004](https://user-images.githubusercontent.com/55733077/185999973-92b7fc59-dfe4-423c-987a-0d3d5d9c8186.png)

**Platform:**

 - Device: Desktop
 - OS: windows
 - Browser: Chrome
 - Three.js version: [r143]

**Comment by sunag** [comment]
I created a similar model in blender and I didn't find any problem related.
I just added a color to differentiate.

NodeMaterial:
![image](https://user-images.githubusercontent.com/502810/186038388-a0106a7d-40ab-4710-8771-e05924a71152.png)

Standard:
![image](https://user-images.githubusercontent.com/502810/186038435-654a6a21-f048-4bda-a881-dd09d67b2f3b.png)

GLTF Model
[box.zip](https://github.com/mrdoob/three.js/files/9398278/box.zip)

**Comment by sunag** [comment]
@sdarpeng I need to more concrete example. Can you try share this in jsfiddle? You checked something related to `flipY` texture?

**Comment by sdarpeng** [comment]
@sunag  Sorry I don't know how to use jsfiddle but I finally setup a sandbox with threejs r143 here. (Thanks god, It is not easy on this too new threejs version to setup in codesandbox.io ).

https://5bhbv2.csb.app/src/GLTFLoader.js:143:17

Then you can see the code 
`      const myUV = mul(uv(), 1) `

And I tried your model , There was also UV error on your model. 

By the way, my codesandbox still have some error with GLTFLoader.js...Can you fork it and show me how to repair? Thanks very much.

**Comment by sunag** [comment]
Definitely it's not related `NodeMaterial`, just use `MeshStandardMaterial` the result is the same. 
To fix your issue, just add `texture.flipY = false;` as I mentioned.

![image](https://user-images.githubusercontent.com/502810/186298581-bfba061b-d18e-43af-8c11-1740f7485192.png)
