### ISSUE TITLE
SelectionHelper DefinitelyTyped definition diverges from SelectionHelper.js defintion

### ISSUE THREAD

**Issue by cklogs** [mrdoob/three.js#24527]
The SelectionHelper current typescript definition, [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/three/examples/jsm/interactive/SelectionHelper.d.ts) defines three constructor params, whereas the current SelectionHelper.js implementation defines two, [here](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/interactive/SelectionHelper.js).

This is resulting in runtime errors and unit test failures when using the SelectionHelper class.

**Expected behavior**

Typescript definition should reflect implementation.

**Screenshots**

![image](https://user-images.githubusercontent.com/10749074/186007529-d6fa73a1-0006-4bff-9843-b23d9330905c.png)

**Platform:**

 - Device: Desktop
 - OS: Windows 10 Pro
 - Browser: N/A
 - Three.js version: 0.143.0

**Comment by Mugen87** [comment]
Please report the issue at https://github.com/three-types/three-ts-types. The TS type declaration file seems to be out-of-date.
