### ISSUE TITLE
GroundProjectedEnv seems to be some problems

### ISSUE THREAD

**Issue by blokingsmall** [mrdoob/three.js#24520]
**Describe the bug**

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**To Reproduce**

1. Get a 'JPEG image '
2. import GroundProjectdEnv and loaded image
3. See scene has a white line

***Code***

```js
// code goes here

https://codesandbox.io/s/recursing-feather-pe2p11?file=/src/App.js

***Live example***

* https://codesandbox.io/s/recursing-feather-pe2p11?file=/src/App.js

**Expected behavior**

A clear and concise description of what you expected to happen.

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [MacOS]
 - Browser: [Chrome]
 - Three.js version: [dev, 143]

**Comment by blokingsmall** [comment]
.hdr image is not problem~ but .JPG and JPEG has problem;

**Comment by WestLangley** [comment]
As a work-around, try
```js
texture.generateMipmaps = false;
```

**Comment by blokingsmall** [comment]
> As a work-around, try
> 
> ```js
> texture.generateMipmaps = false;
> ```

ok！Looks normal！ so cool！ @WestLangley ~
