### ISSUE TITLE
Return entire Object in .toJSON function

### ISSUE THREAD

**Issue by OldManMeta** [mrdoob/three.js#24530]
**Describe the bug**

The Object3D.toJSON function internal to the object (mesh) does not return the entire object in JSON.

**To Reproduce**

1. Go to  https://codesandbox.io/s/3js-json-x1nbqz?file=/src/index.js
2. Open the console log
3. Observe Object Pure in the console log - note the data fields
4. Observe the Object JSON output - missing all fields outside of basic geometry, meterials etc

***Live example***

https://codesandbox.io/s/3js-json-x1nbqz?file=/src/index.js

**Expected behavior**

That a true 1:1 serialised object is returned in JSON

**Platform:**

All platforms and versions

**Comment by LeviPesin** [comment]
As you can see from the `toJSON` code,
```
if ( this.name !== '' ) object.name = this.name;
if ( this.castShadow === true ) object.castShadow = true;
if ( this.receiveShadow === true ) object.receiveShadow = true;
if ( this.visible === false ) object.visible = false;
if ( this.frustumCulled === false ) object.frustumCulled = false;
if ( this.renderOrder !== 0 ) object.renderOrder = this.renderOrder;
if ( JSON.stringify( this.userData ) !== '{}' ) object.userData = this.userData;
object.layers = this.layers.mask;
object.matrix = this.matrix.toArray();
 if ( this.matrixAutoUpdate === false ) object.matrixAutoUpdate = false;
```
, only properties with non-default values are exported.

**Comment by Mugen87** [comment]
This is done to make the JSON as small as possible. It also has no negative effect when you read the JSON in via `ObjectLoader`.

**Comment by OldManMeta** [comment]
Thanks @Mugen87  & @LeviPesin for the responses.

I can appreciate that approach, but I am confused to how the object model is intended to be used beyond the serialisation.

What I mean by that is, in a strongly typed environment, I need the entire model scheme defined, in order to deserialize the json, regardless if it has null values or not. I can't do that here, because the object model scheme can change from one object to another.

So simple example that I am unable to get to work is precisely around using ObjectLoader.

I grab the Mesh JSON for example - send it over to another part of code to do some stuff, but I am unable to use the ObjectLoader to parse the JSON correctly. If I manually create an Object3D instance and lets say add a JSON model Object.Matrix - I no longer have access to any of the Matrix4, or Vector3 functions in order to get the position from the matrix for example.

Sort of breaking my head.

**Comment by Mugen87** [comment]
Sorry, but we can't accommodate the serialization/deserialization so it works in your specific environment. `three.js` is a JS project and we try to optimize the library for this language.

Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need more help.
