### ISSUE TITLE
Matrix4 is not a Matrix4, Vector3 is not a Vector3

### ISSUE THREAD

**Issue by OldManMeta** [mrdoob/three.js#24531]
Regardless of which language you are targeting, if it doesn't work properly than you have a bug.

Your docs here:
https://threejs.org/docs/#api/en/core/Object3D

This tells me every function and property that should be on an Object3D - accept that isn't what I am seeing, when I am creating one. It isn't what I am seeing when I load a mesh from JSON into it either.

For example - here I have added a box to the scene. I traverse the graph, get the object and save it to a JSON object in order to attempt to get some details from the object.

Simple code - grab any mesh for this:

`       //Convert to the object model
       var objectJSON = mesh.toJSON();

       const newObj = new Object3D();
       console.log("Generated Object =>",newObj); 

       const loader = new ObjectLoader();
       var newObjectMesh = loader.parse(objectJSON,()=>{});

       console.warn("New Object from object =>",newObjectMesh);`

I then load that JSON object in, using ObjectLoader=> parse.

This is the object graph returned:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/107874035/186126221-e97f3f5f-9996-4229-ae01-115076417a4e.png">

You can see on this image, that the box is not in the centre of the screen, yet the loaded object has a zeroed out Position Vector 3.

You can also see that the methods and properties are missing from that Vector3 as described in your docs:
https://threejs.org/docs/#api/en/math/Vector3

Ok, so I then take a look at the Matrix of the object. It has the data in it, but none of the methods or properties described in your docs are actually on the object at all:
https://threejs.org/docs/#api/en/math/Matrix4

<img width="291" alt="image" src="https://user-images.githubusercontent.com/107874035/186126076-9255a22b-f761-411b-8a94-86d20410374a.png">

Now if you tell me that's because of your stripped down JSON scenario - then I say, fantastic. But please do show me in the docs or anywhere else, where I can convert that Matrix4 to a proper Matrix4 object,  or a Vector3 to a proper Vector3 - so I can then call the methods to get the correct position/rotation/scale of the object.

As a reminder also - not everyone uses stackoverflow because of their system of points etc. Your forums are also a fantastic place to understand things, but not a place to raise issues that unless can be explained adequately, are a bug.

I will happily raise as many as these as possible in the coming weeks, with the only goal of helping to make the project better for it, if possible. Thanks for your help.

**Comment by makc** [comment]
can you share a jsfiddle link or something

**Comment by LeviPesin** [comment]
> Ok, so I then take a look at the Matrix of the object. It has the data in it, but none of the methods or properties described in your docs are actually on the object at all:

It is absolutely impossible to convert to JSON a method/function. What you are talking about?

**Comment by LeviPesin** [comment]
> Ok, so I then take a look at the Matrix of the object. It has the data in it, but none of the methods or properties described in your docs are actually on the object at all:
https://threejs.org/docs/#api/en/math/Matrix4

Because class methods in JS are per-prototype, not per-instance, so they are not showed in console.log.
Try `console.log( newObjectMesh.matrix.add )` - the method would be logged.

**Comment by Mugen87** [comment]
Our policy is that GitHub is for bugs only. And what you have reported is not a bug. It seems you have just misunderstood basic concepts of JavaScript. The forum would be an ideal place for questions raised in this topic.
