### ISSUE TITLE
requestAnimationFrame called on "self" might not work on multi-window environments

### ISSUE THREAD

**Issue by SkyBladeCloud** [mrdoob/three.js#24549]
**Is your feature request related to a problem? Please describe.**

On a NW.js application which runs in separated context mode, the global window object corresponds to a background, invisible window where requestAnimationFrame never fires. Additional windows spawned using the NW.js API have their own window variable (different from global.window). This causes problems with this line: 
https://github.com/mrdoob/three.js/blob/8de7680efd897a088efb443ad136b9379ccd5bef/src/renderers/WebGLRenderer.js#L951

Since "self" will be pointing to the global window (background, invisible), the animation callback will never be triggered.

**Describe the solution you'd like**

A mechanism for the WebGLRenderer to set a custom window object, rather than having the global self hard-coded. For instance:

- If a canvas is specified in the constructor of WebGLRenderer, use ownerDocument.defaultView, or ownerDocument.parentWindow to know where to call requestAnimationFrame.
- Perhaps have the WebGLRenderer take an additional parameter to use as window, which would default to "self", even though that would be somewhat redundant considering the previous option.

**Describe alternatives you've considered**

1 -> Overwrite the window.requestAnimationFrame function, so that it's executed by another window: this is very hackish and only works with one window, so if my application spawns two, each with a three.js canvas, it would break.

2 -> Use NW.js in mixed context mode: this way each spawned window has its own global window object. However, this works by running each window on a different process, which makes it hard to pass information back and forth.

4 -> Thanks to https://github.com/mrdoob/three.js/pull/23686 I can do something like:

`window.self = nw.Window.get().window; //Get NW.js child window object into the self reference three.js will use`
`renderer = new THREE.WebGLRenderer({ antialias: true });`
`window.self = window; //Set the original window back to the global self reference`

This seems to work fine as well, but it's also extremely hackish.

4 -> Directly use requestAnimationFrame on the child window object, as it used to be done.
As far as I understand, this is currently discouraged in favor of setAnimationLoop for WebXR compatibility, but so far it's the best I've come up with. I guess it's an acceptable solution if WebXR support is never to be considered, and if everything else works as expected (please confirm?).

**Additional context**

Nw.js is a development platform by Intel which allows application programmers to combine a nodejs back-end with a HTML/CSS/JS front-end into a standalone app (similar to Electron):

https://nwjs.io/
https://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/

In Nw.js, visible HTML interfaces don't use the default, global "window". Rather, the global window corresponds to an invisible, background object. This is an useful design choice for headless environments.

Thanks and kind regards.

~Sky

**Comment by LeviPesin** [comment]
> 4 -> Thanks to https://github.com/mrdoob/three.js/pull/23686 I can do something like:
>
> window.self = nw.Window.get().window; //Get NW.js child window object into the self reference three.js will use
> renderer = new THREE.WebGLRenderer({ antialias: true });
> window.self = window; //Set the original window back to the global self reference
>
> This seems to work fine as well, but it's also extremely hackish.

I think this is the best solution.

**Comment by Mugen87** [comment]
This is a problem of `NW.js` and it's inappropriate to address this issue in the engine. To me, it's annoying if JS environments implement web standards differently so you as a developer can't rely things to just work. Probably better to file an issue at `NW.js`.

**Comment by mrdoob** [comment]
> 4 -> Thanks to https://github.com/mrdoob/three.js/pull/23686 I can do something like:
>
> ```js
> window.self = nw.Window.get().window; //Get NW.js child window object into the self reference three.js will use
> renderer = new THREE.WebGLRenderer({ antialias: true });
> window.self = window; //Set the original window back to the global self reference
> ```
>
> This seems to work fine as well, but it's also extremely hackish.

Seems fine to me 👍

**Comment by upintheairsheep** [comment]
Hello, your Ubuntu Smart TV project has been fun to see, however, can you try doing the opposite of it, porting Samsung’s propriety Smart TV operating system (codenamed Orsay) to Ubuntu or another Linux distrobution, it would be fun to see it running on a modern computer.
