### ISSUE TITLE
Improve the search feature of the docs (by using DocSearch)

### ISSUE THREAD

**Issue by fulopkovacs** [mrdoob/three.js#24547]
**Is your feature request related to a problem? Please describe.**

I've been searching a lot in the docs recently, but many times failed to find what I was looking for. An example: I heard about the `loadAsync()` method, but I couldn't find it by typing `loadAsync` to the search input field ([see the problem here](https://threejs.org/docs/index.html?q=loadAsync)). It would be nice if we could improve the search functionality.

**Describe the solution you'd like**

Algolia's DocSearch is a popular (and free) searching solution for open-source projects. It basically crawls and indexes the doc pages to populate its database, and brings its own (customizable) UI  ([link](https://docsearch.algolia.com/)). Recently I've been involved in adopting DocSearch at work, so I think I'd be able to help you out here! :relaxed: 

**Describe alternatives you've considered**

Honestly, I can't think of any alternatives right now.

**Additional context**

You need to apply here to get access to DocSearch: [https://docsearch.algolia.com/apply](https://docsearch.algolia.com/apply)

This is how DocSearch works in the `vite` docs ([link](https://vitejs.dev/)):

https://user-images.githubusercontent.com/43729152/187046584-2d5ad9b6-71e7-4746-b20f-8511b60d0b0d.mp4

**Comment by Mugen87** [comment]
Merging into #19342.
