### ISSUE TITLE
Morph targets broken on some mobile devices using WebGL 2

### ISSUE THREAD

**Issue by niuin** [mrdoob/three.js#24545]
**Describe the bug**
When I load a glTF model with more than a certain number of shape keys (Morph Targets), the mesh is not visible in the cell phone browser

This is a question I posted in the forum and could not resolve.
https://discourse.threejs.org/t/gltf-morph-animation-retention-limits/41762/3

1. export a mesh with more than a certain number of shape keys (more than 241 in my environment) to glTF in Blender.

2. browse it in any glTF viewer.

3. the mesh will no longer be visible in the mobile web browser.
(However, it will be visible in the desktop web browser.)

The cell phones I am checking are as follows
ViVO iQOO neo3 5G (Android 10 / Chrome 104.0.5112.97 )
ASUS ZenFone 3 ( Android 8 / Chrome 104.0.5112.97 )
AQUOS SHV38 ( Android 8 / Chrome 98.0.4758.101 )

If you have any other additional requests, please let me know.

***Code***
```js
	const loader = new GLTFLoader();
	loader.load( 'test2.glb', function ( gltf ) {

		mesh = gltf.scene.children[ 0 ];
		console.log("mesh.children.length:" + mesh.children.length)

		scene.add( mesh );
		mixer = new THREE.AnimationMixer( mesh );
		for (let i = 0; i < gltf.animations.length; i++ ) {
			mixer.clipAction( gltf.animations[ i ] ).play();
		};

	} );
```

***Live example***
http://niu.re/t/test2.html

**Screenshots**
https://user-images.githubusercontent.com/868060/187014170-e26b4130-1adf-485e-b1c6-7dc989ca234c.mp4

ViVO iQOO Neo3 5G
![0ca4b2f0fee3445a32522d6f2d0230ab1a3d7c76_2_224x500](https://user-images.githubusercontent.com/868060/187014179-48546286-a7e5-40a9-9a50-2c30e8d0f589.jpeg)
![fb1fe7de8f9afc3d0c7a5029218284cfe9f703e9_2_224x500](https://user-images.githubusercontent.com/868060/187014186-908323ee-2b9b-4756-9595-7735ddb71b2f.jpeg)
![69f94f4e1c5aff0e009ff175bd1a7b82fec5b15b_2_224x500](https://user-images.githubusercontent.com/868060/187014189-c6eb9955-1169-48c6-96bb-1424c7331095.jpeg)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, Android]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [r144, r142, r88]

**Comment by Mugen87** [comment]
Is it possible for your to update your Android devices to more recent OS versions?

**Comment by niuin** [comment]
Thank you for your reply.

The Android OS update is available, but I have not applied it because it limits the frequencies that can be used.

I took your advice and changed the code as follows
```js
renderer = new THREE.WebGL1Renderer();
```
[http://niu.re/t/test3.html](http://niu.re/t/test3.html)

I'm not sure what caused it when I tried it, but it did display properly.

On a page where WebGL1Renderer is not specified.
I have an additional report from a friend who also tried it.
Android 12 (probably GALAXY): not displayed
iPhone SE 3rd gen.: displayed
iPhone 12 mini: displayed

It seems to be displayed on iPhone, but not on Android.
I also checked with Nox, an Android emulator on Windows, and it is displayed.
So, there is a possibility that the emulator on a desktop PC may not be able to check it correctly.

**Comment by Mugen87** [comment]
I could not reproduce the issue so far.

Do you mind checking if there are any errors or warnings in the browser console on affected devices (via remote debugging)?

**Comment by niuin** [comment]
Thank you for your reply.

I have checked by connecting my cell phone with debugging.
It seems that I am getting the following error.
````
Program Info Log: invalid shaders 
ERROR: too many uniforms
````
WebGLRenderer ( test2.html )
![2022-08-30 (5)](https://user-images.githubusercontent.com/868060/187441342-b1abb260-d754-425e-9928-944dd88278cf.png)
![2022-08-30 (6)](https://user-images.githubusercontent.com/868060/187441478-440e6347-a1e9-4e60-822f-a80db0585f39.png)


WebGL1Renderer ( test3.html )
![2022-08-30 (4)](https://user-images.githubusercontent.com/868060/187441116-c3e677e2-4c05-4220-95ae-b01ef2c5c2f2.png)



I will upload the console log as well.
[niu.re-1661863509115.log](https://github.com/mrdoob/three.js/files/9452911/niu.re-1661863509115.log)

I sincerely hope this helps!

**Comment by Mugen87** [comment]
When using WebGL 2, the implementation supports _unlimited_ morph targets. _unlimited_ means in this context whatever your device supports.

I suppose the problem on your devices is the maximum number of uniform vectors of 256. Since `morphTargetInfluences` are passed to the shader as an array of floats, you hit a device limitation with such a complex morph target model. Desktop devices have a much larger maximum number of uniform vectors e.g. 1024.

For now, you probably have to reduce the morph target count. Alternatively, we could consider to make `morphTargetInfluences` to a data texture (but only for the WebGL 2 code path), and sample it in the shader.

**Comment by niuin** [comment]
Thank you for your answer.
It is unfortunate that it is a device limitation, but it is good to know the cause.

In the case of WebGL1Renderer, was it possible to reproduce even with Max Vertex Uniform Vectors 256, or is it because you are using a different implementation as an alternative?
Are there any items that might be caught by the limitation if the number of targets is increased in this case?

**Comment by Mugen87** [comment]
> In the case of WebGL1Renderer, was it possible to reproduce even with Max Vertex Uniform Vectors 256, or is it because you are using a different implementation as an alternative?

The renderer uses a different implementation with a smaller maximum number of morph target influences (8). This approach does not render more complex morph target animations correctly though.
