### ISSUE TITLE
WebGL Decal Splatter Example doesn't work on Safari

### ISSUE THREAD

**Issue by defo10** [mrdoob/three.js#24551]
**Describe the bug**

The [WebGL decal splatter example](https://threejs.org/examples/#webgl_decals) shows a blank screen in webkit. Tested on Safari Version 15.6.1 (17613.3.9.1.16) on a Macbook Pro M1 and latest Safari version on iOS. It works using Chrome or Firefox on desktop.

The javascript console prints the error:

`TypeError: Module specifier, 'three' does not start with "/", "./", or "../". Referenced from https://threejs.org/examples/webgl_animation_keyframes.html`

**To Reproduce**

1. [WebGL decal splatter example](https://threejs.org/examples/#webgl_decals)
2. See black screen

**Screenshots**

<img width="1462" alt="Screen Shot" src="https://user-images.githubusercontent.com/5160048/187090122-f7744140-89e0-4254-8aa0-5589bf0462fd.png">

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [MacOS, iOS]
 - Browser: [Safari]
 - Three.js version: [dev, r???]

**Comment by WestLangley** [comment]
This example broke on my M1 mac with the release of `r137` -- the release that introduced the import maps shim. 🤔 

It appears the `load` event is not firing:

```js
window.addEventListener( 'load', init );
```
When calling `init()` directly, the example works correctly.
