### ISSUE TITLE
PlaneGeometry with 65536 vertices is missing last triangle

### ISSUE THREAD

**Issue by kerwizzy** [mrdoob/three.js#24565]
**Describe the bug**

When creating a new `PlaneGeometry` where `(widthSegments+1)*(heightSegments+1) === 65536`, the last triangle (at the +x, -y corner) is missing, making the corner clipped.

***Code***

```js
// Also broken for 127 x 511, 63 x 1023, etc.
const geometry = new THREE.PlaneGeometry(1, 1, 255, 255);
```

***Live example***

* [CodeSandbox](https://codesandbox.io/s/three-js-buffergeometry-uint16-uint32-off-by-one-hwzxlf)

**Expected behavior**

The plane should be square and not missing the last triangle, as seen with other values of `widthSegments` and `heightSegments`.

**Screenshots**

Expected behavior (as seen with 256x256)
![image](https://user-images.githubusercontent.com/18251131/187490931-a74b9de2-a050-40b6-b1ad-5ab8d89af07a.png)

Actual behavior (as seen with 255x255)
![image](https://user-images.githubusercontent.com/18251131/187490746-37c70286-c5cf-4f6c-ac07-7b2d676f39b1.png)

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: r143

**Other Notes:**

The bug seems to have something to do with THREE.js using a `Uint16Array` instead of a `Uint32Array` for the `geometry.index` buffer in this case. If https://github.com/mrdoob/three.js/blob/dev/src/utils.js#L39 in `arrayNeedsUint32` is changed from
```
if ( array[ i ] > 65535 ) return true;
```
to
```
if ( array[ i ] >= 65535 ) return true;
```
a `Uint32Array` is used and the corner renders as expected. I'm not sure why this would be, though, because the last few elements of the index array appear to be unchanged by using a `Uint32Array`.

**Comment by donmccurdy** [comment]
I think you've run into [GL_PRIMITIVE_RESTART](https://registry.khronos.org/webgl/specs/latest/2.0/#5.18). The highest possible vertex index (`2^16 - 1` for uint16) is reserved and indicates a break in connected GL primitives like triangle fans or lines. As a result, you'll need to use uint32 if you have more vertices.

**Comment by Mugen87** [comment]
>  It looks like this should be updated in arrayNeedsUint32 for WebGL 2.

For simplicity, I suggest to change the code for both WebGL 1 and 2 and not introduce different code paths.

**Comment by kerwizzy** [comment]
I reviewed your change in #24569 and manually copy-and-pasted it into my three.module.js and tested that it indeed fixes the bug. Thanks!
