### ISSUE TITLE
EffectComposer can't render in AR Mode

### ISSUE THREAD

**Issue by pagongamedev** [mrdoob/three.js#24563]
EffectComposer can't render in AR Mode

i use RenderPass and BloomPass

but can't show render in android
and
show plane render in ios (XRViewer)
![image](https://user-images.githubusercontent.com/18329411/187453741-988d32fd-d028-4811-ba70-0d6832d2c921.png)

**Comment by Mugen87** [comment]
`EffectComposer` does not yet support WebXR, see #18846.

**Comment by Mugen87** [comment]
Merging this into https://github.com/mrdoob/three.js/pull/18846.
