### ISSUE TITLE
normalized BufferAttribute and  BufferGeometryUtils.mergeVertices get wrong result

### ISSUE THREAD

**Issue by danborutori** [mrdoob/three.js#24575]
Using BufferGeometryUtils.mergeVertices on geometry with normalized attribute cause values in result buffer normalized twice.

line 604:     newarray.push( attribute[ getterFunc ]( index ) );
Using normalized values returned from getterFunc to construct newarray.

line: 637:     const attribute = new THREE.BufferAttribute( buffer, oldAttribute.itemSize, oldAttribute.normalized );
Values are not denormalized when constructing a new BufferAttribute.

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [r144]

**Comment by donmccurdy** [comment]
Thanks @danborutori! I'll look into this.

Though aside, I think it's a good use case for @gkjohnson's proposal in https://github.com/mrdoob/three.js/pull/24515.
