### ISSUE TITLE
TransformControls gizmo is rendered upside down with orthographic camera

### ISSUE THREAD

**Issue by nagyatka** [mrdoob/three.js#24571]
**Description**

I ran into an interesting behavior after I bumped the three.js version from r0.141 to r0.142. In the r0.142 version, the gizmo rendering with orthographic cameras was updated (https://github.com/mrdoob/three.js/pull/24242/commits/c35b2e6b280456fedd0c0fea64c17590b08aeb2b) that turned the rotation gizmo upside down. 

<img width="210" alt="Pasted Graphic 18" src="https://user-images.githubusercontent.com/3961400/187637554-4ff18f07-2630-49da-b8d1-309b28c98b44.png">

<img width="165" alt="Pasted Graphic 17" src="https://user-images.githubusercontent.com/3961400/187637587-e9d0e89f-1455-4dee-beb6-adb15d0b9fc7.png">

I checked the commits and found that in the case of an orthographic camera, the direction is no longer determined from the subtraction of the camera and world positions but is retrieved from the camera using the getWorldDirection method. Unfortunately, the normal vector (from the Camera#getWorldDirection) points to the opposite direction which turns the gizmo orientation upside down: 

<img width="371" alt="x 0 5773502691896257" src="https://user-images.githubusercontent.com/3961400/187637733-35b56f2f-f33e-4a20-8a97-4100a9c758fe.png">

I’m not sure if it is a feature that I don’t handle properly or if it is a bug.

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: r0.142

**Comment by Mugen87** [comment]
I can reproduce with `misc_controls_transform` . As reported only the "rotate" gizmo is affected.
