### ISSUE TITLE
threejs examples(webgpu) is not available in chrome104

### ISSUE THREAD

**Issue by lifegit** [mrdoob/three.js#24582]
hi,

open [threejs examples](https://threejs.org/examples/?q=webgp#webgpu_particles) , `"gpu" in navigator` is false,
open [webgpu-samples](https://austin-eng.com/webgpu-samples/samples/particles) , `"gpu" in navigator` is true.

threejs examples not available in chrome. The prompt information is: `Your browser does not support [WebGPU])`.  but webgpu-samples runs successfully.

chrome version: 104.0.5112.101 (x86_64)
system version: macos 12.5.1

**Comment by Mugen87** [comment]
It's because `webgpu-samples` uses an origin trial token whereas `threejs` examples do not. TBH, using the tokens is quite tedious since they constantly expire so you have to renew them. 

Just use Chrome Canary and enable the flag `Unsafe WebGPU` in `chrome://flags`.

**Comment by lifegit** [comment]
thanks! 
but using Chrome Canary presentation is not convincing. Is there any way to update the token?

**Comment by Mugen87** [comment]
@mrdoob I've seen the tokens were removed via c94e98562ed736b30343e7e2fdacb1f9c198075b. Do you think it's worth to renew them? Or just we delegate users to Chrome Canary instead?

**Comment by lifegit** [comment]
I don't think everyone install Chrome Canary. this is not very convenient for promotion.

**Comment by mrdoob** [comment]
WebGPU is still being developed and things are still changing.
If someone wants to try WebGPU at this point they should install Chrome Canary.
