### ISSUE TITLE
VideoTexture version problem with multiple WebGLRenderer's

### ISSUE THREAD

**Issue by steve-o** [mrdoob/three.js#24597]
**Describe the bug**

On Chrome & Safari, with support for `HTMLVideoElement.requestVideoFrameCallback()` the texture version is updated with video progression.  However when multiple `WebGLRenderer` instances are used, each fails to indepently track the version causing only the first instance to update.

With three `WebGLRenderer` this causes only the first to update with video, however the first frame is rendered.  Firefox presumably not with support for the callback renders correctly.  Old versions of THREE.js render correctly as the callback was not supported.

This may or may not be made worse with use of the `EffectComposer`. 

If I explicitly set `needsUpdate = true` when the texture version changes on the first render call, for each subsequent render, then the desired result is achieved.

This issue was encountered after upgrading from r122 to r144.

***Code***

```js
render() {      
       this.#composers.forEach(composer => {
               composer.render();
       });
       requestAnimationFrame(() => this.render());
}
```
Force texture update alternative:
```js
render() {      
       this.#composers.forEach(composer => {
               this.#mesh.material.uniforms.map1.value.needsUpdate = true;
               tcomposer.render();
       });
       requestAnimationFrame(() => this.render());
}
```

***Live example***

The example starts with an image for a few seconds then transitions to a video which exhibits the problem as described.  The transitions and images all render as expected under the same set of renderer instances.

* https://miffy.dsbunny.com/M1/ (r144 - exhibiting new behaviour)
* https://ahyoomee.miru.hk/canvas/video.html (r122 - functioning as desired)

Please note clicking the mouse on the page will cause the 3 renderers to animate apart, highlighting the different renderer locations.  On a small screen this may cause the second and third renderer to appear missing. simply resize the screen or scroll to the right.

**Expected behavior**

All renderers should update with the full video frame.

**Screenshots**

r144 with top renderer updating, but lower two frozen on first video frame:
<img width="982" alt="Screen Shot 2022-09-03 at 8 04 27 PM" src="https://user-images.githubusercontent.com/258627/188292196-8a2c87a8-41cd-4fe7-aa93-b3887b3adde6.png">

r122 with all renderers updating as desired:
<img width="902" alt="Screen Shot 2022-09-03 at 8 51 51 PM" src="https://user-images.githubusercontent.com/258627/188292558-0929cbfc-b93e-4c99-9d5d-64f92f0e3ebd.png">

**Platform:**

 - Device: Desktop
 - OS: MacOS, Windows
 - Browser: Chrome, Safari, Edge
 - Three.js version: r144

Please comment if a simpler example, or archive of source is desired.

**Comment by steve-o** [comment]
Updating with simpler example:
- https://miffy.dsbunny.com/issue-24597/
Source code:
- https://miffy.dsbunny.com/issue-24597/archive.zip

**Comment by Mugen87** [comment]
The problem is that `requestVideoFrameCallback` can only have a single callback which sets the `VideoTexture.needsUpdate` to true. The first renderer which processes the video texture will raise the internal texture version counter which results in no texture upload in all other renderers.

`requestVideoFrameCallback` is an important mechanism for video textures so the engine relies on it. 

Can't you just use a single instance of `WebGLRenderer` in your project? Using multiple renderers and thus WebGL contexts is not a preferred workflow. You can use a single renderer even if you have multiple canvases in your page.

**Comment by steve-o** [comment]
It's an issue with multiple `WebGLRenderer` for sure, it should also appear with image based textures that are updated.

I will try changing to a single instance 👍

**Comment by steve-o** [comment]
So on an Intel GPU, both `OffscreenCanvas` and the original implementation (`needsUpdate` per frame), are about twice as slow as a 2D canvas copy.

**Comment by steve-o** [comment]
Fix per PR:  https://miffy.dsbunny.com/fix-24597/ 👍
