### ISSUE TITLE
WebXR manual section multiple link selection

### ISSUE THREAD

**Issue by AngyDev** [mrdoob/three.js#24600]
**Describe the bug**

If you click on the first link of the WebXR section in the manual, all three links are selected.

<img width="195" alt="Schermata 2022-09-05 alle 11 04 22" src="https://user-images.githubusercontent.com/44018650/188412548-7a5c8727-68d8-43e5-a1f1-01fd7a5d461c.png">

I think the issue is because the name of the three links starts in the same way and the first has not an accurate match. Maybe it can be useful to rename the first like webxr-intro, to have a perfect match.
<img width="218" alt="Schermata 2022-09-05 alle 11 10 11" src="https://user-images.githubusercontent.com/44018650/188413049-2b74726c-3a77-444f-97d2-8b46ecdfa29e.png">
What do you think?

**Comment by Mugen87** [comment]
Renaming sounds like a good solution! How about `webxr-basics` so it matches the title?

**Comment by AngyDev** [comment]
Yes, sure, it's better!! 😊 Can I make the change?

**Comment by Mugen87** [comment]
That would be great!
