### ISSUE TITLE
IOS /  WebGL 2  / PMREM generator doesnt produce cubemaps

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#24605]
https://threejs.org/examples/webgl_loader_gltf

On IOS  webGL2.0 activated : 
Iphone SE ( 2nd gen 2020 )  14.4

"THREE.WebGLRenderer: EXT_color_buffer_float extension not supported." when allocating the cubeUVRenderTarget into HalfFloatType

![IMG_5084](https://user-images.githubusercontent.com/3786958/188879993-63ed3f05-6953-4882-9bc3-0f9ad71cfa54.jpg)

I guess it should not call : 
EXT_color_buffer_float 

But 
OES_texture_half_float instead ?

**Comment by Mugen87** [comment]
`PMREMGenerator` only uses half float and the default of `RGBELoader` is half float as well. So I don't understand right now  why the error is reported. Do you mind updating iOS to 15?

**Comment by Mugen87** [comment]
Can't reproduce the problem with an iPad (8th generation) with iPadOS 15.4.

**Comment by Mugen87** [comment]
A colleague could not reproduce the issue on an iPhone SE 3 with iOS 15.

@Samsy If the issue still exists after upgrading to iOS 15, please report the issue to Apple/Webkit.

**Comment by trusktr** [comment]
I'm running into this problem on my colleague's iPhone 14 Pro with iOS 16.0.3, but I can't reproduce on any of the remote iPhone 14 devices on BrowserStack.

Looks like there's a bug in Webkit tracker where someone reported the extension to be missing: https://bugs.webkit.org/show_bug.cgi?id=247240

**Comment by trusktr** [comment]
I was able to fix it based on [this comment](https://github.com/mrdoob/three.js/issues/15493#issuecomment-450820195) by calling

```js
    renderer.extensions.get('EXT_color_buffer_float');
```

before doing anything.

Does this mean that some feature detection is not working on a particular iPhone+iOS combination?

**Comment by Mugen87** [comment]
I don't have the issue at hand anymore but remember that certain iOS version had broken extension support. This is not something that can we detect or fix in `three.js`.

**Comment by trusktr** [comment]
How exactly does this fail, so I can report it upstream? Why is it that calling `renderer.extensions.get('EXT_color_buffer_float');` before doing anything allows it to work?
