### ISSUE TITLE
Lights Documentation

### ISSUE THREAD

**Issue by AngyDev** [mrdoob/three.js#24604]
**Describe the bug**

In the SpotLight doc in the intensity property explanation we have this definition:

<img width="777" alt="Schermata 2022-09-07 alle 10 11 32" src="https://user-images.githubusercontent.com/44018650/188826501-f03a1af2-dd62-45c5-a4f2-ab96a951316c.png">

Instead, in the PointLight doc on the same property the definition is different:

<img width="786" alt="Schermata 2022-09-07 alle 10 11 41" src="https://user-images.githubusercontent.com/44018650/188826638-88256e90-2bf2-4b5c-be94-dd7078368cfb.png">

I think that the property is the same, and the correct one is the PointLight definition, but maybe it is not. What do you think?

**Comment by Mugen87** [comment]
Yes, I think the `SpotLight` page should be updated so it matches `PointLight`.

**Comment by WestLangley** [comment]
The correct statement is:

    Note: Changing the light's power will also change the light's intensity.

**Comment by WestLangley** [comment]
Users can set the light's intensity directly, or they can set it indirectly by setting the light's power.

**Comment by Mugen87** [comment]
I don't think there is a right or wrong here since `power` is a property like `intensity` from a user perspective. Setting `power` affects `influence` and vice versa. Maybe rephrasing the descriptions would clarify things.

**Comment by WestLangley** [comment]
@Mugen87 OK, I'll think of something...

**Comment by WestLangley** [comment]
OK, we can leave it as-is.
