### ISSUE TITLE
renderer.setPixelRatio(window.devicePixelRatio); should be default

### ISSUE THREAD

**Issue by andrewhodel** [mrdoob/three.js#24618]
`renderer.setPixelRatio(window.devicePixelRatio);`

Why is this not default?  The renderings are terrible if not.

**Comment by Mugen87** [comment]
On certain devices rendering in the native resolution can quickly downgrade performance. The visual might still be okay though. So it's up to the user to decide, whether to render at full native resolution or not.

**Comment by LeviPesin** [comment]
Related large discussion: https://github.com/mrdoob/three.js/issues/4903

**Comment by andrewhodel** [comment]
Operator, driver, participant, technician, customer of electricity are all users of something but they are called something different in other fields and that creates a massive dilemma for workers programmed with this concept. 



Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment]
I know user is a construct against the medical problems caused by the truth of it meaning simple and is employed to balance the medical profits in the drug market but what they are doing to workers is wrong. 



Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment]
Operator, driver, participant, technician, customer of electricity are all users of something but they are called something different in other fields and that creates a massive dilemma for workers programmed with this concept. 



Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment]
That is why this issue should be fixed, to stop increase hope in learning not make people feel like they made junk. 

Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment]
Someone working with three js is not interacting with the tool in a simple manner when compared to the average education. 

Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment]
For example a user of an internet connection connects and is done with the connection work. 

Then they use the internet. 

If they go to the stock market and trade money, they are a trader using the internet. 

If they are building a 3d tool, they are working not using. 

There is an argument with watching a video vs reading a book and that is with regards to fascism. 



Regardless, it shouldn’t produce broken results on purpose. 



Thank You,
Andrew Hodel
