### ISSUE TITLE
isWebGL2 test failed unexpectedly

### ISSUE THREAD

**Issue by hxmwr** [mrdoob/three.js#24634]
https://github.com/mrdoob/three.js/blob/3a42fffb0635674a229249e6f8d1a7ffa50b7edf/src/renderers/webgl/WebGLCapabilities.js#L55
When the `WebGLRenderer` been created in a `iframe/window`, and its `domElement` appended to a parent DOM in another `iframe/window`, then `isWebGL2` test will failed, because the actual constructor is `window. WebGL2RenderingContext` where window refers to the original `window/iframe`, so `instanceof` always returning `false`

**Comment by Mugen87** [comment]
> When the WebGLRenderer been created in a iframe/window, and its domElement appended to a parent DOM in another iframe/window,

What is the reason for using such a complicated setup? 

How do you propose to fix the issue?

**Comment by hxmwr** [comment]
> What is the reason for using such a complicated setup?

In some cases, our web ui editor's default component library is less flexibility, so we add a hidden `iframe` to host another react project and use `renderToDOM` to  inject some customized components.
> How do you propose to fix the issue?

Maybe this is an issue that don't need to be fixed untill now.  :-)

**Comment by Mugen87** [comment]
TBH, I'm not aware how this can be fixed. You probably have to change your component lib such that the renderer is only created inside the target iframe (and not before).

**Comment by hxmwr** [comment]
Just change to `isWebGL2 = true` for this special situation, so I don't need a library level fix for now. For the future maybe complie a small piece of GLSL which is webgl2 specific and then check the compile status to check if `gl` is really instance of webgl2.
Thank you [Mugen87](https://github.com/Mugen87) as always.

**Comment by Mugen87** [comment]
We can reconsider this issue if more users run into it. For now, I would not prefer to exchange a simple `instanceof` check with an actual render to figure out the WebGL version.
