### ISSUE TITLE
TransformControls: Event not passed through to nested functions (version update 122 => 144)

### ISSUE THREAD

**Issue by Carnageous** [mrdoob/three.js#24630]
**Describe the bug**

After updating the codebase of a medium-sized project from version 122 to 144 (yes, we were stuck for a long time), we have a problem with the TransformControlls class exported from your "examples". When using "addEventListener" for the change event, event targets that are passed through nested functions (for example when using a debounce function for the listener) are `null`. This is not an issue when directly passing the callback function into the `addEventListener` function. In version 122 it worked, and I could not find anything related to this in the changelog. Did I miss something?

**To Reproduce**

1. Add a TransformControll to any mesh
2. Add a `change` event listener
3. Try to pass in a function that wraps another function and then log `event.target` in that wrapped function

***Code***

```js
// Init transform controls
const transformControls = new TransformControls(camera, renderer.domElement);
  tansformControls.mode = 'translate';

transformControls.addEventListener('dragging-changed', event => {
  controls.enabled = !event.value;
});

renderer.domElement.addEventListener('click', e => {
  e.stopPropagation();
});
    
    
// THE IMPORTANT PART:
// works, target is an object
transformControls.addEventListener("change", e => {
  console.log(e.target)
})
    
// does not work! Target is undefined.
ransformControls.addEventListener("change", debounce(console.log, 100))
```

***Live example***

* [jsfiddle](https://jsfiddle.net/deq2m0r6/5/)

**Expected behavior**

The event target should presist when passed into nested functions
**Platform:**

 - Device: Desktop
 - OS: Windows 11
 - Browser: Firefox and Chrome (both latest stable and dev release)
 - Three.js version: 144 (latest)

**Comment by LeviPesin** [comment]
This is not related to three.js. Possibly it is a bug in `debounce`, or, more likely, your code.

**Comment by Carnageous** [comment]
Thank you for the quick response!
However, I was able to verify that the problem was introduced with threejs version 127. (Probably https://github.com/mrdoob/three.js/pull/18564).

The event target seems to be disposed before the eventHandler function can access the event target (as it's passed by reference/sharing).

To show this in an easy way, see this fiddle (three v126)
https://jsfiddle.net/w2q6ft8u/5/
and compare to this one, exact same code but three v127
https://jsfiddle.net/w2q6ft8u/6/

In the last one, you can see the target is `null` in the console.

Anyways, I read through the discussion of the PR above and it was mentioned that a workaround obviously is to pass the event target into the dispatch method (https://github.com/mrdoob/three.js/pull/18564#issuecomment-815343370). 
If found the discussions about switching to CustomEvents from the current Event dispatcher like https://github.com/mrdoob/three.js/issues/24082, but I am fine with the workaround. So if this really is intended, you can close the issue,
