### ISSUE TITLE
The `dispose()` method needs clarification

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#24647]
In the docs, the `dispose()` method has various definitions:

- When a BufferGeometry is rendered, it allocates WebGL resources which can only be disposed of by calling this method.
- Disposes of the PMREMGenerator's internal memory.
- Disposes of the internally-created material and geometry used by this helper.
- Dispose of the directionalLightHelper.
- Dispose of the hemisphereLightHelper.
- Dispose of the pointLightHelper.
- Disposes of the light helper.
- Override of base class's dispose
- Abstract dispose method for lights; implemented by subclasses that have disposable resources.
- Disposes of this shadow's textures map and mapPass.
- This disposes the material. Textures of a material don't get disposed.
- Frees the internal resources of this instance.
- Can be used if an instance of [name] becomes obsolete in an application. The method will free internal resources.
- Dispose of the current rendering context.
- Dispatches a dispose event.
- Frees the GPU related resources allocated by a texture. Call this method whenever a texture is no longer used in your app.

---

Perhaps something similar to the last one would be appropriate?

- Frees the GPU-related resources allocated by this instance.

Or, perhaps

- Frees the GPU-related resources allocated by this instance. Call this method whenever this instance is no longer used in your app.

Suggestions, welcome. :-)

**Comment by Mugen87** [comment]
Agreed. The current descriptions are not consistent nor clear. 

> Frees the GPU-related resources allocated by this instance. Call this method whenever this instance is no longer used in your app.

I vote for this description since it defines what the method does and gives a hint when to use `dispose()`.

**Comment by WestLangley** [comment]
OK, I'll take care of it.

**Comment by erasta** [comment]
Suggestion: would be helpful to mention that `dispose()` is needed only after the geometry is rendered, so intermediate non-rendered geometries don't need to be disposed of.
For instance: [the internal geometry in TessellateModifier](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/modifiers/TessellateModifier.js#L26) 

(although I'm not tech-writer and not sure what's the best phrasing should be...)

**Comment by Mugen87** [comment]
Since a call of `dispose()` does not harm when no rendering has happened, I would not mentioned this detail. Might only confuse users.
