### ISSUE TITLE
ThreeJS Editor doesn't take into account Scene cameras.

### ISSUE THREAD

**Issue by Pourfex** [mrdoob/three.js#24642]
**Describe the bug**

ThreeJS Editor doesn't take into account scene cameras anymore. Before r138, clicking on play would switch to scene camera. now it stay on the editor camera.

**To Reproduce**

1 Open threejs editor
2 Add an unlit cub
3 Press play -> using editor camera is ok here
4 Add camera to scene
5 Press play = still use editor camera, wrong behaviour

**Expected behavior**

After pressing play, it should switch to camera scene view

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Chrome, Firefox]
 - Three.js version: [dev, r144]

**Comment by Mugen87** [comment]
I can't reproduce the previous behavior with `r137`:

https://rawcdn.githack.com/mrdoob/three.js/r137/editor/index.html

The editor always uses the main camera when playing the scene.

**Comment by Mugen87** [comment]
I can't reproduce the previous behavior with `r137`:

https://rawcdn.githack.com/mrdoob/three.js/r137/editor/index.html

The editor always uses the main camera when playing the scene.

**Comment by alan3six5** [comment]
Hi there, please check out this video using the editor that @Mugen87 provides. It has the same problem as well

https://www.loom.com/share/1865a7ed40804d44bbe763572c007e73

**Comment by Mugen87** [comment]
What you see is the intended behavior. The selected camera from the drop down can only be used during the design time. The player always uses the default camera.

**Comment by alan3six5** [comment]
That's odd! I swear this wasn't the original behaviour but I could be wrong. Regardless, I feel like this behaviour should be changed. 

Similar to any 3D software (Blender, Maya, Unreal, Unity, etc), when hit "Play", "Render" or whatever, it should use the Active Camera from the Scene, not the Editor's Camera. 

It defeats the whole purpose of adding another camera because if we can't not use it during playtime, why should we add one?

I hope this feedback helps. 

Or the current editor already has something like this and I am just missing out stuff haha

**Comment by Pourfex** [comment]
I agree with @alan3six5, this behaviour is really weird as in play mode we would like to be in the game's camera view so we can test things out like camera controls for exemple.

I tested 90-140 versions (jumping 10 version at a time) and it's the same as today. Find it very weird as I remember doing all my projects in the editor like this one year ago !

Anyway, do you have a way to change the camera in editor in play mode ? (by adding some script somewhere ?) I tried getting the editor from window and set the viewport camera but it didn't go well.

**Comment by Mugen87** [comment]
Um, it seems the behavior can be updated by just changing the following line:

https://github.com/mrdoob/three.js/blob/cd9057d3beaff6fa8c4a5a99eba9c956e515bd35/editor/js/Editor.js#L684

to:
```js
camera: this.viewportCamera.toJSON(),
```
Can you please check if this works for you?

**Comment by Pourfex** [comment]
Thanks @Mugen87 it does work for me.

I'm wondering if we should change the current behaviour to match other 3D engine. Is there somewhere to make a poll or something like that ?

**Comment by Mugen87** [comment]
I can make a PR if @mrdoob is fine with this change.

I can't think of a downside right but maybe @mrdoob sees a side effect when updating `editor/js/Editor.js` like above.

**Comment by Pourfex** [comment]
Thanks for taking this into next version of threejs !
