### ISSUE TITLE
Favor using WeakRef 

### ISSUE THREAD

**Issue by Mehran7kl** [mrdoob/three.js#24656]
**Is your feature request related to a problem? Please describe.**
I just want to suggest that GC languages like Js always have something known as WeakRef that it's the best for resource-critical libraries to use it and makes the memory management easier and more performant. Consider [this answer ](https://stackoverflow.com/a/48048620/14855128) that describes how much useful a WeakRef can be.

**Comment by gkjohnson** [comment]
This issue is just pointing out a Javascript feature. I think it would be more helpful if you had more focused recommendations or areas of the code that needed it.
