### ISSUE TITLE
CSM.remove() needs to delete target as well as DirectionalLight

### ISSUE THREAD

**Issue by yoshikiohshima** [mrdoob/three.js#24653]
**Describe the bug**

CSM.createLights() adds the DirectionalLight and its target which is automatically created to its parent:

https://github.com/mrdoob/three.js/blob/cd9057d3beaff6fa8c4a5a99eba9c956e515bd35/examples/jsm/csm/CSM.js#L66

But the counter part, remove() only removes lights but not targets:

https://github.com/mrdoob/three.js/blob/cd9057d3beaff6fa8c4a5a99eba9c956e515bd35/examples/jsm/csm/CSM.js#L344

**To Reproduce**

***Code***

```js
// go into an example https://github.com/mrdoob/three.js/blob/master/examples/webgl_shadowmap_csm.html, add csm.remove() and inspect what objects are in the scene.
```

**Expected behavior**

when csm.remove() is called, the target objects are also removed from the scene.

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r???]

**Comment by gkjohnson** [comment]
Would you like to make a PR to fix the issue?

**Comment by yoshikiohshima** [comment]
Ok.. Let me try that sometime today, or over the weekend. Thanks!

**Comment by yoshikiohshima** [comment]
One thing I don't know about is that files under examples/jsm/ and examples/js are edited directly, or there is another place to edit and update those files. Can you enlighten me on that before I make a PR?

**Comment by gkjohnson** [comment]
You will need to edit just the examples/jsm files.
