### ISSUE TITLE
Fix `Uncaught TypeError: (intermediate value).now is not a function` on clock.getDelta()

### ISSUE THREAD

**Issue by Parking-Master** [mrdoob/three.js#24657]
It seems like there is something wrong with the clock now.

On my FPS game, my `clock.getDelta()` works just fine on my animated character.

But on another page, running `clock.getDelta` returns:

> Uncaught TypeError: (intermediate value).now is not a function

I copied the exact code from the other page, still does it.

I event did a shift+reload on my working page to make sure any changes from the three.js library were synced.

It still works on that page.

I clicked the link on the error which brought me to the debug tab in Firefox.

It seems what you're doing though is:
```javascript
function jc(){return("undefined"==typeof performance?Date:performance).now()}
```
And the `clock.getDelta` function is calling that `jc` function.

What I see is right here:
```javascript
("undefined"==typeof performance?Date:performance).now()
```
This is where the error is coming from.

I recommend you fix it with this:
```javascript
("undefined"==typeof performance.now?Date.now():performance.now())
```
I made it check for `performance.now` instead of just `performance` because it seems `performance.now` does not exist anymore.

Running this code in my console runs smoothly and free of errors.

Until you fix this bug I will use the custom code I made.

**Comment by LeviPesin** [comment]
> `("undefined"==typeof performance.now?Date.now():performance.now())`

That will produce error on Node, where `performance` is undefined.
The current code should work as it is.

**Comment by LeviPesin** [comment]
It seems that in your environment `performance` is defined while `performance.now` is not? Can you please elaborate more on your environment?

The correct code is `( ( typeof performance === 'undefined' ) || ( typeof performance.now === 'undefined' ) ) ? Date : performance ).now()` I think.

**Comment by Parking-Master** [comment]
@LeviPesin Yes, the `performance` variable is defined but `performance.now` is not. It used to work because I used it before.

**Comment by Mugen87** [comment]
If `performance.now()` does not exits, something is wrong in the environment. I'm afraid this issue is not going to be fixed in the library.

**Comment by Parking-Master** [comment]
@Mugen87 Is it browser specific? Is the browser corrupted?

**Comment by Parking-Master** [comment]
@Mugen87 I tested it on my other mac desktop. `performance.now()` does exist on there.

**Comment by Mugen87** [comment]
>  Is it browser specific?

https://caniuse.com/?search=performance.now

**Comment by Parking-Master** [comment]
@Mugen87 I took a looka at that link. It says it is supported (both browsers are Firefox 105+)

**Comment by Parking-Master** [comment]
But wierdly enough like I said, the other `clock.getDelta()` on the game works. It is this specific page

**Comment by LeviPesin** [comment]
Maybe some script on that page is removing `performance.now`?

**Comment by Parking-Master** [comment]
@LeviPesin No the page is just a normal 60+ line page

**Comment by Parking-Master** [comment]
When I open a blank tab (or any page), open the console, type `performance.now` it returns `undefined`. Even the page that works. Very strange

**Comment by gkjohnson** [comment]
The first thing you do in your code is declare a "performance" function and overwrite the the global field...

Please use the three.js forums for three.js help or StackOverflow for general Javascript help.

**Comment by Parking-Master** [comment]
> The first thing you do in your code is declare a "performance" function and overwrite the the global field...
> 
> Please use the three.js forums for three.js help or StackOverflow for general Javascript help.

For anyone in the future with this problem...

I did what @gkjohnson said:
```javascript
performance.now = Date.now;
```

This did the trick.

**Comment by gkjohnson** [comment]
> ```js
> performance.now = Date.now;
> ```

To be clear that is not what I recommend. Please use the forum or stackoverflow if you'd like help on what's gone wrong with your javascript.
