### ISSUE TITLE
./nodes is not exported

### ISSUE THREAD

**Issue by servinlp** [mrdoob/three.js#24659]
**Describe the bug**

When importing `WebGPURenderer` I get the following error.

```sh
Module not found: Package path ./nodes is not exported from package /node_modules/three (see exports field in /node_modules/three/package.json)
```

**To Reproduce**

Three version 0.144.0

Import `WebGPURenderer` like so.
`import WebGPURenderer from "three/examples/jsm/renderers/webgpu/WebGPURenderer.js";`

**Cause:**

It seems to break when there is an import from `three/nodes`. This refers to Nodes.js at three/examples/jsm/nodes/Nodes.js. However this doesn't seem to be implemented in the builds or the [exports in the package.json](https://github.com/mrdoob/three.js/blob/dev/package.json#L8).

A quick fix seems to add it to the exports in the package.json.

**Comment by lishulincug** [comment]
version 0.145 has the same problem.
![image](https://user-images.githubusercontent.com/13003282/193213421-37ce6c41-051f-49ed-9f3f-832e2566738e.png)

**Comment by lishulincug** [comment]
> Strange... Is it plain Node.js or something else?

"eslint": "^6.0.0",
    "eslint-config-haomo": "^1.0.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.0.0",
    "eslint-plugin-standard": "^5.0.0",
    "eslint-plugin-vue": "^7.13.0",
