### ISSUE TITLE
Delete Extrusion EndCap Faces

### ISSUE THREAD

**Issue by pha3z** [mrdoob/three.js#24661]
On the surface, this seems like a pretty simple enhancement to Extrude that would create more utility.

It would be super nice if you could pass a 'deleteCapA' flag and a 'deleteCapB' flag that would cause the endcap faces to be removed after extrusion, leaving only the extruded 'sidewalls'.  

Another person asked for something like this on StackOverflow and they've received 5 upvotes and no straight-forward solution.

[https://stackoverflow.com/questions/29964283/extruding-a-line-in-three-js](https://stackoverflow.com/questions/29964283/extruding-a-line-in-three-js)

**Comment by WestLangley** [comment]
Related: #10268, #11118

The currently-suggested workaround for this feature request is to set the front material opacity to zero.

```js
const geometry = new THREE.ExtrudeGeometry( shapes, extrusionSettings );

const materials = [ materialFront, materialSide ];

const mesh = new THREE.Mesh( geometry, materials );
```

**Comment by WestLangley** [comment]
Related: #10268, #11118

A workaround for this feature request is to edit the `.groups` property of the extruded geometry.

For example, you could do something like the following prior to rendering:

```js
geometry.groups.shift(); // render only the side walls
```

**Comment by LeviPesin** [comment]
Also related: https://github.com/mrdoob/three.js/issues/12390

**Comment by Mugen87** [comment]
I do not vote to enhance `ExtrudeGeometry` any further since the class is already quite complex. 

Updating the groups sounds like a good solution.

**Comment by pha3z** [comment]
@WestLangley  It looks like you edited your post... originally you mentioned the "materials" work around but you've changed it to the "groups" workaround.  I didn't know about either one of them, so they're both useful.

Can you edit your post to include both workarounds?  I linked the stackoverflow question to this issue so it may benefit many people.

**Comment by WestLangley** [comment]
@pha3z The workarounds I posted above are the workarounds users should use. Simply setting the material opacity to zero is a bit of a hack.

**Comment by GeorgeBekh** [comment]
It's probably a good idea to add these workarounds to the docs

https://threejs.org/docs/#api/en/geometries/ExtrudeGeometry

Since naturally people will look there for a setting to disable caps
