### ISSUE TITLE
orbitController in mobile found pointer count error

### ISSUE THREAD

**Issue by LYunLong** [mrdoob/three.js#24678]
I create a simple scene, use orbitController to controll camera, when i try double finger action, i found "pointers.length" return 1, and it make camera move as rotate but not zoom or pan, it not happen every time ,but happens often

 - Device: [ Mobile ( iPhone X )]
 - OS: [iOS]
 - Browser: [ Safari]
 - Three.js version: [0.114.0]

**Comment by Mugen87** [comment]
> Three.js version: [0.114.0]

Can you please try it with the current version of `three.js`? The issue might already be fixed.

> Browser: [ Safari]

Does it only happen in Safari or can you reproduce with Firefox or Chrome, too?

Can you reproduce the issue with the following example? https://threejs.org/examples/misc_controls_orbit

**Comment by LYunLong** [comment]
Thanks for response !
I upgrade three version to lastest version (  0.144.0 ) and test my page on mobile safari / chrome / Firefox ,  still found error ,
I set debugger,  found that when i do double finger action,  sometime "pointerdown" event only catch once,  then action like touchmove between two finger position, cause camera do some rotate fastly  but not zoom.
I also test your example link, not found this happen ,at least not happen these times, so i begin to review me page code try to find where may cause pointerdown event wrong.

**Comment by LYunLong** [comment]
Problem resolved, I bind a blank function to touchstart event, found pointerdown event run well, error not happen again, I search all my page code ,still not found any code to change default touchstart event,  so weird but resolved, Thanks again~
