### ISSUE TITLE
DataTexture3D doesn't work with NRRD UINT8 Volume

### ISSUE THREAD

**Issue by jrmartin** [mrdoob/three.js#24679]
**Describe the bug**

I want to load a NRRD file whose data is formatted as UINT8, but when I try to load it onto THREE.DataTexture3D I don't see it on the canvas, and don't see any errors on the console. If I try the same thing with a NRRD file formatted as FLoat32, it works and I see it on the canvas.

**Expected behavior**

I would expect to see the NRRD on the canvas. 

**Platform:**

 - All platforms have same behavior

**Comment by Mugen87** [comment]
Can you please share a NRRD file with UInt8 data for testing and development?

**Comment by jrmartin** [comment]
Hi @Mugen87 , here is one NRDD file as UINT8 

https://v2.virtualflybrain.org/data/VFB/i/0010/1567/VFB_00101567/volume.nrrd

**Comment by Mugen87** [comment]
I've imported the file in `webgl2_materials_texture3d`, removed `texture.type = THREE.FloatType;` from the 3D data texture configuration and updated the camera settings a bit. The model loads and renders as expected, see:

<img width="1864" alt="image" src="https://user-images.githubusercontent.com/12612165/191942347-7568fb3f-7afd-44ba-bb11-8ebdacad557b.png">

**Comment by jrmartin** [comment]
@Mugen87 Thanks for that, I will retry it. One thing I did different from the webgl2_material_texture3D, is that I use a perspective camera instead of orthogaphric camera, which I'm reading doesn't work well with the volume rendering. 

https://github.com/mrdoob/three.js/blob/dev/examples/webgl2_materials_texture3d.html#L64

**Comment by Mugen87** [comment]
Yes, there is an issue for tracking this problem: #19308

**Comment by jrmartin** [comment]
Thanks for confirming this should work @Mugen87, save me some headaches. I tried it again and it worked, it threw me off at first that I didn't see it render but that was because my laptop's graphic's card doesn't support textures this big. I confirm it work on my phone. I'm closing the issue.
