### ISSUE TITLE
An unknown request about GLTFLoader

### ISSUE THREAD

**Issue by hcxmj** [mrdoob/three.js#24683]
Hello author, when I use the GLTFLoader in three/examples/jsm/loaders/GLTFLoader.js to load a glft link, a request is made every time [https://market-assets.fra1.cdn.digitaloceanspaces.com/ /market-assets/hdris/potsdamer-platz/potsdamer_platz_1k.hdr](https://market-assets.fra1.cdn.digitaloceanspaces.com/ /market-assets/hdris/potsdamer-platz/potsdamer_platz_1k.hdr), and this often causes value timeouts to cause parsing and rendering to fail. The error is shown in the figure below. I don't know how to avoid or solve this problem. I hope you can help me. Solution
This is not a must, but it occurs more frequently
![image](https://user-images.githubusercontent.com/58494807/191919983-a59bc200-bc11-4797-9b9b-9eb200f8edd8.png)
![image](https://user-images.githubusercontent.com/58494807/191920028-d824c678-de93-4655-be7f-89044202d58b.png)
`import React, { Suspense, useLayoutEffect, useRef } from 'react'
import { Canvas } from '@react-three/fiber'
import { OrbitControls, Stage } from '@react-three/drei'
import useStore from '@/utils/store'

export default function Viewer({ shadows, contactShadow, autoRotate, environment, preset, intensity } : any) {
  const scene: any = useStore((store) => store.scene)
  const ref = useRef()
  useLayoutEffect(() => {
    scene.traverse((obj: any) => {
      if (obj.isMesh) {
        obj.castShadow = obj.receiveShadow = shadows
        obj.material.envMapIntensity = 0.8
      }
    })
  }, [scene, shadows])

  return (
    <Canvas style={{ width: '100%', height: '100%' }} gl={{ preserveDrawingBuffer: true }} shadows dpr={[1, 1.5]} camera={{ position: [0, 0, 150], fov: 50 }}>
      <ambientLight intensity={0.25} />
      <Suspense fallback={null}>
        <Stage
          // @ts-ignore
          controls={ref}
          preset={preset}
          intensity={intensity}
          contactShadow={contactShadow}
          shadows
          adjustCamera
          environment={environment}>
          <primitive object={scene} />
        </Stage>
      </Suspense>
      {/* @ts-ignore */}
      <OrbitControls ref={ref} autoRotate={autoRotate} />
    </Canvas>
  )
}
`

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by hcxmj** [comment]
> Please use the [forum](https://discourse.threejs.org/) for help requests.

ok,thank you @Mugen87
