### ISSUE TITLE
Examples: webgl_worker_offscreencanvas doesn't load

### ISSUE THREAD

**Issue by Degubi** [mrdoob/three.js#24685]
**Describe the bug**

The 'webgl_worker_offscreencanvas' example doesn't load.

**To Reproduce**

1. Go to https://threejs.org/examples/?q=offs#webgl_worker_offscreencanvas
2. Get an error in console saying 'Uncaught TypeError: Failed to resolve module specifier "three/addons/offscreen/jank.js". Relative references must start with either "/", "./", or "../".'

**Expected behavior**

The example should load

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]

**Comment by Mugen87** [comment]
It seems the import map is missing in this example. Let me fix this...
