### ISSUE TITLE
FBXLoader might have wrong onLoad callback

### ISSUE THREAD

**Issue by ukhack** [mrdoob/three.js#24697]
**Describe the bug**

When xxx.FBX  downloaded , onLoad callback will be call。
but the application still download the jpg textTure with the model and i dont know when complate
when i add fbx in scene,model will be black.  
version0.144.0

**To Reproduce**

***Code***

```js
new FBXLoader().load('/zhulou3/zhulou.FBX', function (obj) {
      obj.position.set(0, 0, 0);
      scene.add(obj);
      setTimeout(() => {
        render();
      }, 1000)
    })
```

***Live example***

**Expected behavior**

after jpg done call onLoad

**Screenshots**

![image](https://user-images.githubusercontent.com/17568491/192225986-96779375-ebbd-4aa4-81a8-d239941640de.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [0.144.0]

**Comment by Mugen87** [comment]
If you want to wait until all resources have been loaded, use `THREE.LoadingManager`. 

Also see #12105.

**Comment by ukhack** [comment]
> 

thanks a lot!!
