### ISSUE TITLE
Posibility to change zoom style for OrbitControls

### ISSUE THREAD

**Issue by surdu** [mrdoob/three.js#24702]
**Is your feature request related to a problem? Please describe.**

There are some cases where it is useful to have a `PerspectiveCamera` that when you zoom in/out it will change the FOV of the camera, not the position (dolly) as it is now.

**Describe the solution you'd like**

Add a property called `.zoomStyle` on the `OrbitControls` instance, which will default on `'dolly'` and can be changed to `'zoom'`. This property will have effect only on a `PerspectiveCamera`

**Describe alternatives you've considered**

Use an `OrthographicCamera`, but that doesn't work for us, as we have to match perspective from a generated object.

**Additional context**

I could make a PR for this, if this is something that would be desired

**Comment by Mugen87** [comment]
If the implementation is compact, I would be fine with adding this feature. Ideally, you only have to update the ctor as well as `dollyIn()`/`dollyOut()`.

**Comment by Mugen87** [comment]
The problem with having different zoom styles for perspective cameras is that it makes the zoom restriction more complicated. Right now, you use `minDistance` and `maxDistance` for perspective cameras and `minZoom` and `maxZoom` for orthographic ones. With different zoom styles, perspective cameras would need both property sets. 

Having different min/max zoom properties for perspective and orthographic cameras is already somewhat unfortunate. I don't like the idea of making this even more complicated. So it's probably best to implement this feature on app level.
