### ISSUE TITLE
Offscreen example not working on Firefox 105.0.1

### ISSUE THREAD

**Issue by fraguada** [mrdoob/three.js#24709]
**Describe the bug**

FF [105+ apparently supports the Offscreen Canvas API](https://caniuse.com/offscreencanvas). Testing the Offscreen Canvas example, I only get canvas 1 rendering and canvas 2 is blank. This works fine in Chrome Version 106.0.5249.61 (Official Build) (arm64). 

For context, I was running firefox 104.x.x and I would get the message that the browser does not support Offscreen Canvas, then I updated to 105.0.1 and the message went away.

There are two errors in the console, the first is expected on Firefox, the second might be important, but it seems offscreen.js adheres to this already:

```
Uncaught TypeError: Error resolving module specifier “three/addons/offscreen/jank.js”. Relative module specifiers must start with “./”, “../” or “/”. webgl_worker_offscreencanvas.html:82:24

SyntaxError: import declarations may only appear at top level of a module offscreen.js:1
```

**To Reproduce**

1. Open Firefox 105+
2. Navigate to https://threejs.org/examples/?q=off#webgl_worker_offscreencanvas
3. See only canvas1 rendering

***Live example***

* https://threejs.org/examples/?q=off#webgl_worker_offscreencanvas

**Expected behavior**

The expectation is that canvas 2 renders as it does on Chrome.

**Screenshots**
<img width="1727" alt="Screenshot 2022-09-29 at 10 09 40" src="https://user-images.githubusercontent.com/1014562/192978478-3de0268a-a12f-4812-b936-22633ee70910.png">

**Platform:**

 - Device: Desktop, M1 mbp
 - OS: macOS Monterey 12.2.1 
 - Browser: Firefox 105.0.1 64-bit
 - Three.js version: r145

**Comment by Mugen87** [comment]
It seems Firefox has issue with module support in workers. I see the following error in the browser console.

> SyntaxError: import declarations may only appear at top level of a module

**Comment by marcofugaro** [comment]
Firefox doesn't support module workers yet: `new Worker('...', { type: 'module' })`

https://caniuse.com/mdn-api_worker_worker_ecmascript_modules

**Comment by Mugen87** [comment]
I guess there is not much we can do here. Or is there some sort of polyfill like for import maps?

**Comment by marcofugaro** [comment]
[There an old polyfill](https://gist.github.com/developit/220246bc99044af74a6680ce13284f59), but I tested it and it doesn't seem to work that well.

**Comment by Mugen87** [comment]
Closing then. I think it makes more sense at this point to ask Mozilla to improve the module support in Firefox.

**Comment by fraguada** [comment]
@Mugen87 Is there a protocol to do this? Happy to do it myself if there is nothing in place.

FWIW, I found this: https://bugzilla.mozilla.org/show_bug.cgi?id=1247687

**Comment by Mugen87** [comment]
> Is there a protocol to do this?

Normally you would file a bug at the browser's bug tracker. Since there is already an active issue, I would wait if the feature gets implemented in the next time. It seems they are working on it.

If nothing happens, feel free to comment at the issue at bugzilla.
