### ISSUE TITLE
Emissive color is not applied when using Bloom

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#24703]
**Is your feature request related to a problem? Please describe.**

I want to get the effect of Bloom similar to Babylon.js.
https://github.com/cx20/gltf-test/issues/621

**Describe the solution you'd like**

I would like emissive color to be applied when the following glTF model is displayed.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/EmissiveStrengthTest

**Describe alternatives you've considered**

I have prepared a similar sample to compare whether three.js can achieve the same effect as Babylon.js.
Babylon.js Bloom Test : https://jsfiddle.net/cx20/ky0tcgr6/
three.js Bloom Test : https://jsfiddle.net/cx20/x1g2j07y/

However, in three.js, the emissive color set in the glTF model is not reflected, resulting in a white bloom effect.

**Additional context**

|Library|result|
|:------------:|:------------:|
|Babylon.js|![image](https://user-images.githubusercontent.com/1833979/192137768-a82ed9c4-88af-46d7-8e0f-102070a78376.png)|
|three.js|![image](https://user-images.githubusercontent.com/1833979/192114262-dfd3e5bc-a3d7-46af-b179-aa9fad5432e9.png)|

**Comment by donmccurdy** [comment]
For reference, from [KhronosGroup/glTF-Sample-Models/2.0/EmissiveStrengthTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/EmissiveStrengthTest):

> The basic emissive color of all the cubes is [0.1, 0.5, 0.9] in the glTF file, which is expected to undergo the usual linear-to-sRGB transfer before being shown to the viewer. The cube on the far left has no emissive strength extension (1x), and each subsequent cube doubles the strength (2x, 4x, 8x, and 16x).

Unfortunately, our post-processing stack does not implement HDR fully. I think you'll find that a lower `bloomThreshold` will display the emissive color in the glow on the left boxes up until the lowest component, <kbd>R</kbd>, is ≥1, after which point the glow is simply white:

<img width="495" alt="bloom_color" src="https://user-images.githubusercontent.com/1848368/192656556-bda9bbf9-8b21-4c1c-8393-71a494bbbeb4.png">

Two problems here are straightforward, and I've attempted to fix them in a fork of the JSFiddle:

1. Tone mapping de-linearizes RGB components (as it should) and clamps them to the closed domain [0,1] (probably incorrect). Neither the tone mapping, nor the clamp, can happen before a bloom pass — disable `renderer.toneMapping`. If you'd like to add `ACESFilmicToneMappingShader` or another tone map _after_ the bloom pass, I believe that's OK.
2. The default WebGLRenderTarget used by EffectComposer has `type: UnsignedByteType`. This again clamps RGB components to the closed domain [0,1], and will break the bloom pass. Use a custom render target with `type: HalfFloatType` or `type: FloatType` instead.

https://jsfiddle.net/donmccurdy/jmfc9wgs/

Unfortunately the effect remains incorrect, for what I assume are limitations in the current post-processing stack. It would be interesting to see whether https://github.com/pmndrs/postprocessing has the same problem, though I haven't tried that experiment yet. /cc @vanruesc as FYI.

**Comment by vanruesc** [comment]
Looks as expected in `postprocessing` with a hard lum threshold of `1.0` and bloom strength `1.0`:

![screenshot](https://user-images.githubusercontent.com/9214917/192887802-d5e44498-cde6-493a-bdba-7d07221e3b7d.png)

**Comment by donmccurdy** [comment]
Thank you @vanruesc! 

@cx20 I think I would use the `postprocessing` package for the bloom effect comparison here. Planning for HDR support in three.js post-processing and how that relates to the `postprocessing` package is a longer discussion.

**Comment by cx20** [comment]
@vanruesc  Thank you for trying it.
The execution results you have tried are similar to the Babylon.js execution results and look good.
Is it possible for me to try that sample with `jsfiddle`?

@donmccurdy Thank you for clarifying the issue.
I need to learn more about EffectComposer and tone mapping as I don't understand enough about it.

**Comment by vanruesc** [comment]
@cx20 https://jsfiddle.net/2b95fL1c/

**Comment by Mugen87** [comment]
This issue sis fixed with `r153` which contains a number of improvements of the FX pipeline.

https://jsfiddle.net/zrjsxLc8/1/
