### ISSUE TITLE
Option to disable two-pass rendering of transparent objects

### ISSUE THREAD

**Issue by dmikis** [mrdoob/three.js#24711]
**Is your feature request related to a problem? Please describe.**

There's a [hardcoded path](https://github.com/mrdoob/three.js/blob/d081c5a3501d272d19375fab1b01fedf9df29b22/src/renderers/WebGLRenderer.js#L1334) for rendering transparent objects with doublesided materials. However it's not particularly suitable for our use-case since our models are optimized for a single blended pass with backface fulling disabled. That leads to artifacts.

**Describe the solution you'd like**

An option for materials to override this behaviour.

**Describe alternatives you've considered**

Right now we're forced to patch by hand and commit into our repo a copy of threejs build.

**Comment by Mugen87** [comment]
Related #21967.

**Comment by Mugen87** [comment]
Since this feature request came up multiple times in the past, I'm inclined to support this request. 

Finding a nice and compact property name might be difficult though since only double-sided, transparent materials are affected.

**Comment by dmikis** [comment]
`twoPassTransparentRendering`? `separateFrontAndBackSide`? Both defaulting to `true` to preserve compatibility. I think a descriptive name would be better that a short one TBH :)

**Comment by Mugen87** [comment]
`twoPassTransparentRendering` sounds good to me. Would you be interested in making a PR?

**Comment by dmikis** [comment]
Will do.

**Comment by WestLangley** [comment]
Adding this feature is up to @mrdoob.

But if it is added, I think it should be a property of the _object_, as is `.renderOrder` and `.frustumCulled`.

Double-sided, transparent, _planar_ objects are a use case.

**Comment by dmikis** [comment]
@WestLangley TBH I don't have any preference in the matter, I just want the option to exist.

**Comment by Mugen87** [comment]
I'm okay with making this a property of `Object3D`. But let's leave #24719 open until @mrdoob tells his preference.

**Comment by dwoodruffsf** [comment]
I'd like to vote for this too. We are using the threejs runtime for the spine animation library, which exposes this problem. Spine uses 2-sided, transparent triangle batches, and it relies on those triangle batches being rendered in exactly the order they are submitted. But the winding-order of triangles in the list is heterogeneous (because it's driven by animations which can do funny things like scaling by -1). This creates artifacts where some parts of a character sort out of order.

**Comment by Mugen87** [comment]
@mrdoob Given that the two-pass rendering introduces performance issues for certain users and an issue in context of `gl_FrontFacing`, I think we should make it optional. Are you okay with @WestLangley's suggestion in https://github.com/mrdoob/three.js/issues/24711#issuecomment-1263530851 and introduce a new property for `Object3D`?

**Comment by mrdoob** [comment]
How about adding a new `material.side` named `THREE.TwoPassDoubleSide`?

**Comment by Mugen87** [comment]
Sounds good to me, too!
