### ISSUE TITLE
Documentation: Add a warning when raycasting on the same frame than a change in position/scale/rotation.

### ISSUE THREAD

**Issue by 0xAxiome** [mrdoob/three.js#24727]
Hello,

I recently had a problem with the raycasting that I was not aware of. 
A lot of method rely on the prior that the world matrix is updated. In the default case, it is done on each frame by the renderer.

But when you are translating for example a Mesh on frame 1, and raycasting on the same frame, you will miss the target even if the ray should have intersect the Mesh. 

I added to the doc a note on the Raycaster setFromCamera and intersectObjects methods, and also in the Mesh and LOD raycast method, to make it clear for the user to be sure that when he uses one of these methods, he must be absolutely certain that the world matrix is up-to-date. Otherwise, the behaviour would be unpredictable. I will link this to my pull request.

In order to make 3D concepts even more accessible, I think it is a good warning to newcomers. It would have save me some time if I would have known that prerequisite from the start.

**Comment by WestLangley** [comment]
I would prefer to modify the library to update the world matrix prior to its use.

**Comment by 0xAxiome** [comment]
Could be both. If we base our update by checking if `matrixWorldNeedsUpdate` is set to true before casting a ray, it could work, if the user did not deactivate the matrixWorldAutoUpdate. In that case, he should be aware of the requirement of the raycasting to work properly, because he is maintaining the world matrix himself. 

What do you think about it?

**Comment by WestLangley** [comment]
I prefer calculating the correct answer, so edge-case explanations in the docs are not needed.

**Comment by Mugen87** [comment]
Yes, we really should ensure that matrices are up-to-date when they are used in code, see #21427.

**Comment by Mugen87** [comment]
Closing in favor of #24736.

**Comment by gkjohnson** [comment]
> I would prefer to modify the library to update the world matrix prior to its use.

If this is going to be added then we need some method to disable it or more intelligently update matrices. Updating matrix transforms every time a raycast is performed, which can many times per frame, is incredibly performance prohibitive.

**Comment by 0xAxiome** [comment]
Just checking if matrixWorldNeedsUpdate at the beginning of the raycast method should be enough. I don't see the point to raycast if the boolean is set to true, because the object world matrix is outdated anyway. 

Currently the world matrices in the general case are automatically recomputed on the next frame by the renderer. We are just one frame late. 

If someone wants to disable the computation, by disable matrix auto update, I guess matrixWorldNeedsUpdate would have to be set manually anyway, so we have our way to disable it. 

Do you see any flaws in my logic ?
