### ISSUE TITLE
Cannot reproduce DOF2 example

### ISSUE THREAD

**Issue by Cecile-Lebleu** [mrdoob/three.js#24720]
**Describe the bug**

After copying the code line by line, and all required files, the DOF2 example shows a black screen. 

**To Reproduce**

1. Go to [DOF2 CodeSandbox](https://codesandbox.io/s/dof2-j7593u?file=/src/index.js)
2. Click on Controls → `enabled` to toggle postprocessing
3. When postprocessing is enabled, the screen is black

***Code & Live example***

[DOF2 CodeSandbox](https://codesandbox.io/s/dof2-j7593u?file=/src/index.js)

**Expected behavior**

[DOF2 Example](https://threejs.org/examples/?q=dof2#webgl_postprocessing_dof2)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [MacOS, iOS]
 - Browser: [Chrome, Firefox, Safari]
 - Three.js version: [dev, r145]

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) or stackoverflow for help requests.
