### ISSUE TITLE
Docs: Object3D: Missing documentation about force parameter in updateMatrixWorld()

### ISSUE THREAD

**Issue by 0xAxiome** [mrdoob/three.js#24725]
Hello,

I updated the documentation of the Object3D for the updateMatrixWorld(), because the force boolean was not documented.
I'm using it a lot in my own code, and I was always wondering what is the consequences of forcing the update. 
I'm opening this issue to be able to reference it in the commit and the pull request I'm intending to do next.

**Comment by WestLangley** [comment]
>I'm using it a lot in my own code

Perhaps you should be using `.updateWorldMatrix( updateParents, updateChildren )`.

`.updateMatrixWorld()` does not do what its name says it does.

**Comment by 0xAxiome** [comment]
I think I understand what you mean. It multiplies the child and the parent matrix without checking that the parent itself is up-to-date no?

updateWorldMatrix is following the whole tree from the current object and updating both side if both booleans are to true?
