### ISSUE TITLE
FBXLoader sometimes floods console with invalid material index warnings

### ISSUE THREAD

**Issue by philipswan** [mrdoob/three.js#24732]
The following line of code ... 

console.warn( 'THREE.FBXLoader: Invalid material index:', materialIndex );

... is generating 10's of thousands of lines of console output on (at least) models produced by exporting from Blender and Fusion360 to FBX. Chrome's debugger also seems to have trouble coping with the amount of spew, leading to a need for frequent forced restarts.

Note: I believe that this problem started occurring after we upgraded from three.js version 0.133.1 to a more recent version.

**To Reproduce**
1. Sync and run [this project](https://github.com/philipswan/TetheredRing) according to the instructions in the ReadMe.
2. Launch in Chrome, using localhost url.
3. Open a debug console by using <cntrl>+C to observe warning messages.

***Code***
The following code in TransitSystems.js is the only place where the fbxloader is called. Commenting out these lines of code will cause the problem to go away.
```js
    const fbxloader = new FBXLoader()
    fbxloader.load('models/RingTerminus.fbx', addRingTerminuses, progressFunction, errorFunction )
    fbxloader.load('models/GroundTerminus.fbx', addGroundTerminuses, progressFunction, errorFunction )
    fbxloader.load('models/RingTerminus.fbx', addHabitats, progressFunction, errorFunction )  // This is hacky - borrowed RingTerminus model and modified it to make a habitat
    fbxloader.load('models/Elevator.fbx', addElevatorCars, progressFunction, errorFunction )
```
Note: RingTerminus.fbx was exported from Fusion360. GroundTerminus.fbx and Elevator.fbx were exported from Blender.

**Expected behavior**

Possibly there is no "real problem" with the models and thus no warning error messages actually need to be printed out. Alternatively, there was always a real problem with these models (note: they seemed to work fine before), in which case perhaps we likely need to file bugs with both the Blender Team and Autodesk teams. Possibly there is yet another explanation for the observed behavior. Documenting instruction of how to avoid and/or resolve this issue (added to this bug report or official docs) may help others.

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: Desktop and Mobile
 - OS: Windows 10 (others unknown)
 - Browser: Chrome and Edge (other unknown)
 - Three.js version: 0.144.0 (but not on 0.133.1)

**Comment by Mugen87** [comment]
The warning was added since certain FBX assets use `-1` as a material index. There is no indication in the unofficial FBX spec that such an index is valid nor how it should be interpreted. In any event, `three.js` can't process it since certain parts of the mesh would render with an `undefined` material.

It's probably best to avoid FBX exports in the first place that contains negative integers as material indices.

**Comment by philipswan** [comment]
My experience with this has me thinking that the "lesser of two evils" here would be to continue doing whatever three.js did before, even though perhaps the past decision on how to handle the "-1" material index was not informed by a good FBX spec and may have been, in fact, totally arbitrary. We aren't the world's quickest debuggers here, and trying to root cause and fix these warning messages did flummox both of us. Best outcome here might be to avoid having other people get stumped as we did - better, at least, than people learning by experience not to mix FBX files and three.js.
It might be a good idea to also add a note to the docs to say that three.js support for the FBX format was a "best effort" situation due to the lack of publicly available FBX specs, and suggest/recommend gITF instead.
Or, add a default material to be used if the format contains a "-1" material index, and provide a way for the user of the loader to override the default if they want to.
In our case, regenerating the models in another format is not an easy option to implement as the people that contributed some of them have moved on.

**Comment by philipswan** [comment]
BTW, It looks like Fusion360 doesn't support exporting to gITF.
![image](https://user-images.githubusercontent.com/29994403/193730259-a1d7a9a9-766d-4139-b0dc-897525e787b5.png)
![image](https://user-images.githubusercontent.com/29994403/193730361-2ec64e32-ac8a-43d3-bc09-bd3065b89256.png)

**Comment by Mugen87** [comment]
The problem is that we normally want to inform the user when something with the asset is wrong. If we don't log a message and just use a default material, the user could assume "everything is right". 

Besides, the loader actually assign the `0` material index in invalid cases as a fallback. So it's just the question whether we should refactor the warning or not.

How about we rewrite the log so the loader reports it just once. So instead of reporting `Invalid material index` every time an invalid material index was found, we could report the following warning once:
```
The FBX file contains invalid (negative) material indices.
```

**Comment by Mugen87** [comment]
I've filed a PR to implemented the outlined approach.

**Comment by philipswan** [comment]
Yes, it would be helpful to have a one-time warning and this would solve the "flooding" problem.

Also, just a heads up - in parallel we tried to re-export two separate models from Blender to gITF, but in both cases the models appeared incomplete when they were rendered in three.js. However, they do look complete when I use Windows 3D viewer to look at the files.
[FilesThatDontWork.zip](https://github.com/mrdoob/three.js/files/9704366/FilesThatDontWork.zip)

**Comment by Mugen87** [comment]
I can only compared the models with [BabylonJS](https://sandbox.babylonjs.com/) right now and both assets render like with https://gltf-viewer.donmccurdy.com/ (which is `three.js` based).

What do you mean with complete/incomplete?

**Comment by philipswan** [comment]
Part of the model shows up in three.js, but not all of it. For example all of the legs are missing in the triangular shaped object.

**Comment by Mugen87** [comment]
Can you please try to disable view frustum culling for all nodes of the glTF object? You can do this by traversing through the glTF scene (via `Obejct3D.traverse()`)  and then set the `frustumCulled` to `false` for each node.

**Comment by philipswan** [comment]
Sorry to be slow responding - I was working on publishing a paper by a deadline.
If I implemented your experiment correctly, then unfortunately it didn't work.

However, three.js + node.js + Chrome seems to have become unstable for me. Not sure what's going on but now I'm getting an error "TypeError: object.updateMatrixWorld is not a function". It did not go away when I reverted my changes. Sigh, everything was great before I updated a few weeks back. I should never update. I always end up regretting it.

Please see below.
![image](https://user-images.githubusercontent.com/29994403/196053719-22ee2050-319b-4e62-b775-1e3ba08dde86.png)
``
        object.traverse(child => {
          child.frustumCulled = false
          if (child!==object) {
            child.name = objName+'_'+child.name
          }
        })

``

**Comment by philipswan** [comment]
Ok, I think I figured something out. When I first implemented the callback for the GLTFLoader, the model I was debugging it on came from Fusion360, and the model's scene looked like this...
![image](https://user-images.githubusercontent.com/29994403/196066037-e581e2c7-db3d-4901-8703-b6ccf0a8cc45.png)
To get it to work, I implemented added this line of code 
`        const object = scene.children[0]
` 
When I added the GLTF model from blender, the model's scene was different...
![image](https://user-images.githubusercontent.com/29994403/196066213-c3e0e9fa-60de-4696-99b7-f9fb921c47b0.png)

So, the line of code I added only picked up the first mesh.

I think this latest issue comes down to me not knowing how to write a callback function that should work for all GLTF files. Here's what I wrote. Any tips would be appreciated...
`    function prepareACallbackFunctionForGLTFLoader(myScene, myList, objName, scale_Factor, n, perfOptimizedThreeJS) {
      return function( {scene} ) {
        console.log(objName)
        console.log(scene)
        const object = scene.children[0]
        object.visible = false
        object.name = objName
        object.traverse(child => {
          if (child!==object) {
            child.name = objName+'_'+child.name
          }
        })
        if (perfOptimizedThreeJS) object.children.forEach(child => child.freeze())
        object.scale.set(scale_Factor, scale_Factor, scale_Factor)
        for (let i=0; i<n; i++) {
          const tempModel = object.clone()
          myScene.add(tempModel)
          myList.push(tempModel)
        }
      } 
    }`
