### ISSUE TITLE
Custom build failing as of r137

### ISSUE THREAD

**Issue by paulmasson** [mrdoob/three.js#24759]
For the last two years I have been producing a custom `three.min.js` bundled with `OrbitControls` by adding one line to `Three.js`:

`export { OrbitControls } from '../examples/jsm/controls/OrbitControls.js';`

As of r137 this no longer works because the build process cannot automatically locate the module `three`. One gets errors like

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
three (imported by examples/jsm/controls/OrbitControls.js)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
three (guessing 'three')
```

While I'm sure there's an easy workaround (and I would appreciate if someone could point me in the right direction), this seems to me like an error in the build process. Since one gets an output build file, which unfortunately doesn't function, this is basically a silent failure.

I can see how to resolve this in the context of example files, but shouldn't there be a way to have this happen automatically when using features from example modules?

**Comment by marcofugaro** [comment]
`OrbitControls.js` imports from the built files, so before you were probably including the three.js source twice in your custom build.

To make it work properly, you should add `three` as a dependency to your project (`npm i three`), and have this as the main file of the custom build:

```js
export * from 'three'
export { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
```

Also, this is an help request, I'd advise you to post to the [forum](https://discourse.threejs.org/) instead.

**Comment by paulmasson** [comment]
@marcofugaro thank you for the prompt response. I can assure that my build files have not been including the source twice: worked through that issue two years ago on **#20387**. Every thing was fine until the new `three` module name was introduced.

I consider this more than just a help request. Introducing an explicit dependency changes the build process, and I can find no documentation of that change.

**Comment by paulmasson** [comment]
And for reference, I added `three` as an explicit dependency and I'm still getting the same error messages...

**Comment by paulmasson** [comment]
For anyone who comes across this issue in the future, the build instructions here are not complete. You can find a complete process for building `three.min.js` here:

https://github.com/paulmasson/threejs-with-controls
