### ISSUE TITLE
VideoTexture hold reference to video source

### ISSUE THREAD

**Issue by eXponenta** [mrdoob/three.js#24757]
**Describe the bug**

Follow source:
https://github.com/mrdoob/three.js/blob/dev/src/textures/VideoTexture.js#L19

VideoTexture hold reference to video in closure, that is get bugs when you change a source like:
```
const texture = new VideoTexture(video);

texture.image = otherVideo;

```

In that case new video never be update from `requestVideoFrameCallback` and will wait update from older video instance, that never be removed by GC - memory leak.

Possible solution: forgeting about closure usages and check that listener runned in `update` method, this will garaneed that current watched source and texture source is same.

whey not use a `set image()` ? Becuase texture has `source` propery, that can be changed indirect and we again will lost reference.

Whay not use a `new VideoTexture`? We will loose a reference, because it can be cross shared between different materials.

**Comment by Mugen87** [comment]
> forgeting about closure usages and check that listener runned in update method, this will garaneed that current watched source and texture source is same.

How would this look like?

**Comment by eXponenta** [comment]
So, i looked to source thoroughly and find more simple way:

Like a :
```

function updateVideo() {

	scope.needsUpdate = true;
	scope.image.requestVideoFrameCallback( updateVideo ); // << --- use a scope reference instead of closure
}
```

But if image will null - it will down.

I think that null is valid value for texture, because it means - no source.

VideoTexture not process case when video source is null.

**Comment by eXponenta** [comment]
More safe version, but has a lot of changes:

https://github.com/mrdoob/three.js/compare/dev...eXponenta:three.js:patch-2
