### ISSUE TITLE
[plugin vite:dep-scan] Missing "./examples/js/libs/lottie_canvas.js" export in "three" package

### ISSUE THREAD

**Issue by NSGUF** [mrdoob/three.js#24762]
**Describe the bug**
When I use 
```js
import 'three/examples/js/libs/lottie_canvas.js';
```

show the error

[plugin vite:dep-scan] Missing "./examples/js/libs/lottie_canvas.js" export in "three" package

Can this line be added in package.json?
```js
"exports": {
    
    // this line
    "./examples/js/*": "./examples/js/*", 
    "./addons/*": "./examples/jsm/*",
    "./src/*": "./src/*",
    "./nodes": "./examples/jsm/nodes/Nodes.js"
  },
```
**Platform:**
 - Three.js version: [dev,0.145.0]

**Comment by marcofugaro** [comment]
We should probably import the [esm version](https://unpkg.com/browse/lottie-web@5.9.6/build/player/esm/lottie_canvas.min.js) of lottie-web in LottieLoader.

But for the moment you can do:
```js
import 'lottie-web/build/player/lottie_canvas.js';
```
