### ISSUE TITLE
GLTFLoader: Incorrect bind pose for newly loaded armatures

### ISSUE THREAD

**Issue by mattrossman** [mrdoob/three.js#24772]
**Describe the bug**

`Skeleton.pose()` relies on the initial world matrix of each bone to reset bind pose. However, the world matrices of bones loaded in a glTF asset are not updated when the model first loads, causing `.pose()` to squash the bones into the origin rather than the position they initially appear in.

If I render the scene (or manually call `.updateMatrixWorld()` on the asset) prior to creating the the skeleton, then it sets the correct bind pose.

This issue of non-updated bone matrices also affects the result of calling `.clone()` on newly loaded glTF models.

**To Reproduce**

1. Load a glTF model with an armature
2. Create a skeleton from its bones
3. Call `.pose()` on the skeleton
4. Render the scene

OR

1. Load a glTF model with an armature
2. Clone the glTF scene root and add it to the scene
3. Render the scene

***Code***

```js
const loader = new GLTFLoader()
loader.load("/character.glb", (gltf) => {
  scene.add(gltf.scene)

  const bones = []
  gltf.scene.traverse((o) => (o instanceof THREE.Bone) && bones.push(o))

  const skeleton = new THREE.Skeleton(bones)
  skeleton.pose()
})
```

OR

```js
const loader = new GLTFLoader()
loader.load("/character.glb", (gltf) => {
  const cloned = gltf.scene.clone()
  scene.add(cloned)
})
```

***Live example***

* [example with `.pose()`](https://jsfiddle.net/mattrossman/wa5bz7r8/7/)
* [example with `.clone()`](https://jsfiddle.net/mattrossman/n84t3e5j/1/)

**Expected behavior**

The skeleton should reset to the initial pose as stored in the glTF asset.

While the workaround (manually calling `.updateMatrixWorld()` prior to these operations) is simple, I don't think users should have to know the internals of how `Skeleton.pose()` works to get the expected output.

I suppose the fix is to update the world matrices within `GLTFLoader`. IIUC these matrices are already available in the loader [here](https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/GLTFLoader.js#L4256), they just aren't filled into the bone `.matrixWorld` properties.

**Screenshots**

Incorrect bind pose:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/22670878/194880035-61bd2cf1-cd1d-4dd4-8191-a8ac9d86d8fc.png">

Correct bind pose:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/22670878/194880069-59593b52-eb27-4475-b5ed-b5b890703c68.png">

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Chrome]
 - Three.js version: [r145]

**Comment by mattrossman** [comment]
There is a similar issue with `FBXLoader` too. I haven't tested other loaders. I get a different result with versus without a `.updateMatrixWorld` invocation prior to constructing a skeleton. In my case, the skeleton appears much larger without the updated world matrices.

Maybe the PR should include fixes needed for these other loaders too?

**Comment by Mugen87** [comment]
Let's focus on `GLTFLoader` first otherwise the PR might get more complex to review if more loaders are included.

**Comment by mattrossman** [comment]
Thanks for the feedback. What if instead of copying the bind matrices, we add an `.updateMatrixWorld()` so the joint world matrices match their transform in the glTF doc? I think that addresses the points you bring up.

```diff js
// GLTFLoader.js

+ mesh.updateMatrixWorld()

  mesh.bind( new Skeleton( bones, boneInverses ), mesh.matrixWorld );

```

I'm not sure if there are conventions for when joint world matrices should be initialized. If this doesn't belong in the loader, then alternative the update could be added in `Skeleton.pose()` and somewhere in the `.clone()` flow.

**Comment by donmccurdy** [comment]
I believe that should be OK — even without skinning involved, it does seem better if GLTFLoader's results are initialized with correct world matrices when the loader returns.

Ideally, we'd call `updateMatrixWorld()` once on the root of each scene in the glTF file, propagating updates to all nodes in the scene. I'm not sure whether there's a good place to put that call in the loading process, or if the skeleton is constructed before the full scene hierarchy is assembled. 

/cc @takahirox FYI

**Comment by Mugen87** [comment]
> + mesh.updateMatrixWorld()

Since the skeletons are created during the node hierarchy build, it seems there is not a place where world matrices can be computed once. Hence, the suggested line of @mattrossman seems to be the right spot.

BTW: To make sure the matrices are correct, use `mesh.updateWorldMatrix( true, false );`.

**Comment by takahirox** [comment]
If I'm right, the default `bindMode` `"attached"` doesn't use `bindMatrix` (the second argument of `.bind()`), does it?

https://threejs.org/docs/#api/en/objects/SkinnedMesh.bindMode
https://github.com/mrdoob/three.js/blob/0ccddfd057512e611fe5faa0c3eaee99f3036563/src/objects/SkinnedMesh.js#L101-L103

**Comment by takahirox** [comment]
So, if I read the spec correctly

> Implementation Note
The matrix defining how to pose the skin’s geometry for use with the joints (also known as “Bind Shape Matrix”) should be premultiplied to mesh data or to Inverse Bind Matrices.

> Only the joint transforms are applied to the skinned mesh; the transform of the skinned mesh node MUST be ignored.

https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#joint-hierarchy

I think passing an identity matrix to `SkinnedMesh.bind()` as the second argument seems to match the spec. And I guess the root cause in your case would be that bind shape matrix is not premultiplied to mesh data or to inverse bind matrices in your glTF model?

**Comment by takahirox** [comment]
I think this issue can be closed because `GLTFLoader` follows the core specification. Please reopen with details if it doesn't follow the specification.

**Comment by mattrossman** [comment]
> inserting mesh.updateMatrixWorld() doesn't have any effect, does it?

I didn't understand this part -- `mesh.updateMatrixWorld()` does have an effect from my testing, it fixes the bind pose from being wiped.

I still think there is a bug here, perhaps not with GLTFLoader if it follows the spec but maybe somewhere else. It doesn't make sense to me that [this works](https://jsfiddle.net/mattrossman/0y28oje9/6/) but [this doesn't](https://jsfiddle.net/mattrossman/0y28oje9/7/), the only difference being whether I rendered the scene before posing the skeleton. The bind pose data is there and `.pose()` works most of the time, just not immediately after loading. Furthermore if call `.pose()` directly after loading then the data is lost, and subsequent calls to `.pose()` after rendering don't work.
