### ISSUE TITLE
Material defines won't be set in constructor options

### ISSUE THREAD

**Issue by alexpineda** [mrdoob/three.js#24771]
I ran into this issue while attempting to add the built in vUv varyings to a customized MeshBasicMaterial.

```ts
new MeshBasicMaterial({
                defines: {
                    USE_UV: "",
                },
                onBeforeCompile: (shader: Shader) => {
                    ...
                    );
                },
            })
 ```

In this case it will not work since the defines is not defined in the material. This would work in something like MeshStandardMaterial (albeit it would override `STANDARD` unless merged or also included).

**Expected behavior**

It should always set defines (eg. defaulted in Material), or maybe even merge defines on constructor.

**Platform:**

 - Three.js version: 145

**Comment by WestLangley** [comment]
Does the `defines` pattern in https://github.com/mrdoob/three.js/issues/10764#issuecomment-278507889 solve your issue?

**Comment by alexpineda** [comment]
Yes of course. Just making note as the api seems inconsistent (depending on which material is used). I'm happy to move on.

**Comment by Mugen87** [comment]
Defines are not something that the user is supposed to set when creating a built-in materials (I'm not refering to custom materials via `ShaderMaterial`). I understand that defines might be relevant when using `onBeforeCompile()` but apart from that there should be no need to work with them.

Hence, the approach outlined in https://github.com/mrdoob/three.js/issues/24771#issuecomment-1273307143 is more appropriate.
