### ISSUE TITLE
Are `GLTF`/`KHR_punctual_lights` `intensity`s and `.physicallyCorrectLights` handled correctly?

### ISSUE THREAD

**Issue by will-ca** [mrdoob/three.js#24788]
**Describe the bug**

- [Docs](https://threejs.org/docs/?q=s#api/en/renderers/WebGLRenderer.physicallyCorrectLights) don't give clear light units, and [examples](https://threejs.org/examples/webgl_lights_physical.html) imply total lumens.
- [`KHR_punctual_lights`](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_lights_punctual/README.md#light-types) however specifies lumens divided by square radians for GLTF.
- Meanwhile `GLTFLoader` [allegedly](https://docs.google.com/spreadsheets/d/1Ce9XCC2Ub9eVjAQdYbYdLvlkDBJ_0GtAyRbSF0KJWzE/) and apparently just copies directly from GLTF values (lm/sr if spec-compliant) to Three.JS light nodes (plain lm, apparently).

Since these three things seem to be in contradiction, presumably one of them must be wrong.

`lights/physical` Example:

https://github.com/mrdoob/three.js/blob/034343d97134c55559aa4edbcce3d405eae308da/examples/webgl_lights_physical.html#L47-L56

https://github.com/mrdoob/three.js/blob/034343d97134c55559aa4edbcce3d405eae308da/examples/webgl_lights_physical.html#L294

`GLTFLoader`:

https://github.com/mrdoob/three.js/blob/290f32bcf186e38e8f1de35ebe0f75491d3eda46/examples/js/loaders/GLTFLoader.js#L467

**Comment by WestLangley** [comment]
Have a look at the inline comments in `PointLight.js` and `SpotLight.js`. The source code is correct.

Then have a look at `PointLight.html` and `SpotLight.html`.

Then, perhaps, you can clarify your question?

**Comment by donmccurdy** [comment]
For reference —

https://github.com/mrdoob/three.js/blob/16274d63e89efd39581c3fe7ef6a6d0462d87f2a/src/lights/SpotLight.js#L31-L44

https://github.com/mrdoob/three.js/blob/16274d63e89efd39581c3fe7ef6a6d0462d87f2a/src/lights/PointLight.js#L21-L34

**Comment by will-ca** [comment]
@WestLangley This as a bug report, not a question. Intensities specified in one unit (lm/sr per KHR_punctual_lights) appear to be, as I explain and link in the OP, treated by Three.JS as a different unit (plain lm). If that is what is happening, then it is probably a bug. If it is not, then there is no bug (but the examples are communicating the wrong units then).

Cursorily from the linked code (Thanks `donmccurdy`), it looks like the behaviour is correct, but the example might need to be fixed.

**Comment by donmccurdy** [comment]
For anyone interested in Blender/glTF/three.js lighting compatibility, this discussion is continued in https://github.com/KhronosGroup/glTF/pull/2214.
