### ISSUE TITLE
DRACOLoader: Draco library version and usage is outdated

### ISSUE THREAD

**Issue by Oletus** [mrdoob/three.js#24787]
**Describe the bug**

See https://github.com/google/draco/issues/927 - the deprecated Draco DecoderBuffer API is still in use, even though three.js is suggested to become the official example code for Draco.

**Expected behavior**

three.js will migrate to newer Draco version and won't use deprecated APIs. It's somewhat unclear if the use of the outdated API could be behind Draco loading related bugs. It's also a bit unclear what the new intended API usage is, since there's no up-to-date official example code yet.

**Platform:**

 - Three.js version: dev

**Comment by mrdoob** [comment]
@Oletus Any chance you can help with this?

**Comment by Oletus** [comment]
Unfortunately I don't think I know Draco well enough - if there was some reference documentation I could spare some hours to work on this, but without any up-to-date documentation for the JS API it's tough to get started.

**Comment by donmccurdy** [comment]
I think we'd certainly like to be using the newer version, but as you've said it is going to be more difficult without API docs or examples. This isn't something that I am planning to work on right now, since there doesn't seem to be any urgent reason to upgrade, but would always be happy to review PRs.

**Comment by donmccurdy** [comment]
The changes required in Draco v1.5.6 were not too different from earlier usage — I've updated our implementation in https://github.com/mrdoob/three.js/pull/25475.
