### ISSUE TITLE
ObjectLoader not working with current release r145

### ISSUE THREAD

**Issue by PtrBld** [mrdoob/three.js#24785]
**Describe the bug**

The ObjectLoader load function does not work anymore. When I load an asset with the ObjectLoader I get the following error:
```THREE:ObjectLoader: Can't parse assets/OBJ/ground.json. Unexpected token 'o', "[object ArrayBuffer]" is not valid JSON```

I did some research and found that the problem is likely introduced in commit [55d4f24cb](https://github.com/mrdoob/three.js/commit/55d4f24cb50e995b0dfee73979305e8237384a53) file ``src/loaders/FileLoader.js`` line ``176``, where the default response was changed from `text` to `arraybuffer`

**To Reproduce**

1. Load an asset using ObjectLoader
2. 
***Code***

```js
    const loader = new THREE.ObjectLoader();
    loader.load('asset.json', () => {});
```

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r145]

**Comment by Mugen87** [comment]
The following example uses `ObjectLoader` and it works without issues.

https://threejs.org/examples/webgl_materials_lightmap

How can the example be modified to reproduce your reported issue?

**Comment by PtrBld** [comment]
I´m very sorry... You are right, it works in ThreeJS. It was a problem in a library using ThreeJS and setting the resposeType beforehand.
