### ISSUE TITLE
SVGLoader: Exception in `isHoleTo` when loading an SVG file

### ISSUE THREAD

**Issue by gregsadetsky** [mrdoob/three.js#24780]
**Describe the bug**

When using `SVGLoader` to load a particular SVG file ([file attached](https://user-images.githubusercontent.com/1017304/195216421-5677c5d5-85fd-44a5-9721-3abc176fec05.svg)), an exception is thrown in the internal `isHoleTo` function, at [this line](https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/SVGLoader.js#L2019):

`TypeError: Cannot read properties of undefined (reading 'isCW')`

Full stack trace:
```
SVGLoader.js:2019 Uncaught TypeError: Cannot read properties of undefined (reading 'isCW')
    at isHoleTo (SVGLoader.js:2019:57)
    at SVGLoader.js:2110:41
    at Array.map (<anonymous>)
    at SVGLoader.createShapes (SVGLoader.js:2110:31)
    at main.js?t=1665531910670:16:26
```

**To Reproduce**

See code and JS Fiddles below.

The SVG file is [available here](https://user-images.githubusercontent.com/1017304/195216421-5677c5d5-85fd-44a5-9721-3abc176fec05.svg). It's also embedded in the example below.

(the specific path that's creating the exception was extracted from a larger SVG -- this is why the .svg file in itself doesn't look that "great"..) :-)

***Code***

```js
import { SVGLoader } from "three/addons/loaders/SVGLoader.js";

const loader = new SVGLoader();

let loadedSvg = loader.parse(`
  <svg xmlns="http://www.w3.org/2000/svg">
    <g transform="matrix(5.0000,0.0000,0.0000,5.0000,100,100)">
        <path d="M 5.6 -9.9 L 5.4 -11.9 M 2 -7.3 L 1.7 -6.7 M 2 -7.3 L 2 -7.3 M 2 -7.2 L 2 -7.3 M 2 -7.2 L 2 -7.2 M 2 -7.5 L 2 -7.5 L 1.9 -9.9 L 2.2 -8 L 2.9 -9.6 M 2.4 -8.4 L 2.3 -7.7 L 2.0 -7.2 M 4.4 -6.3 L 4.4 -7.7 L 3.6 -5.4 L 2.7 -2.6 L 3.2 -3.4 L 3.8 -4.7" style="" transform=""/>
    </g>
  </svg>
`);

const path = loadedSvg.paths[0];

// the following line will raise an exception
const shapes = SVGLoader.createShapes(path);

```

***Live example***

Both fiddles below (latest & dev) show the issue:
* [jsfiddle-latest-release](https://jsfiddle.net/gregsadetsky/su710ykn/20/)
* [jsfiddle-dev](https://jsfiddle.net/gregsadetsky/pc2os8ut/1/)

**Expected behavior**

The SVG file should be loaded without any errors.

**Platform:**

 - Device: Desktop
 - OS: macOS
 - Browser: Chrome
 - Three.js version: dev, 0.145.0

**Comment by gregsadetsky** [comment]
Thanks!

While trying to reduce the failing path/code, I found another exception. This is [the line](https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/SVGLoader.js#L2015) that's failing this time (it was line 2019 in the original issue above).

```
Uncaught TypeError: Cannot read properties of undefined (reading 'isCW')
    at isHoleTo (SVGLoader.js:2015:44)
    at SVGLoader.js:2110:41
    at Array.map (<anonymous>)
    at SVGLoader.createShapes (SVGLoader.js:2110:31)
    at main.js?t=1665591924890:14:26
```

Failing code:

```javascript
import { SVGLoader } from "three/addons/loaders/SVGLoader.js";

const loader = new SVGLoader();

let loadedSvg = loader.parse(`
  <svg xmlns="http://www.w3.org/2000/svg">
    <path d="M 2 -7.3 L 2 -7.3 M 2 -7.2 L 2 -7.4"/>
  </svg>
`);

const path = loadedSvg.paths[0];

// the following line will raise an exception
const shapes = SVGLoader.createShapes(path);
```

**Comment by gregsadetsky** [comment]
And a last note :-)

I just created a super simple fuzzer that generates SVG paths (a combo of M/L instructions with random [-10, 10] positions) and both issues (on lines 2015 and 2019) come up almost immediately.

I also tried positive coordinate values for M/L instructions in the [1, 20] range and the same issues came up as well.

Once this issue is fixed, I think that it might be worth integrating a small svg path fuzzer into the test units.

**Comment by Ttommeke** [comment]
Hi everyone

Sorry for the long wait. I found and fixed the issue. it happens when there are paths involved with only one point. I fixed it on my local branch and would like to write a test as @gregsadetsky mentioned, ... But i'm not really sure how i can test this. Do i unit test if the example doesn't crash? Or do we create an e2e test? So if you guys could help me out, that would be great.

FYI, the random points @gregsadetsky do work, but are self intersecting. And the current algorithm does not give the same output as the Chorme browser or Inkscape would. Self intersecting paths are not supported by the svg standard btw.

**Comment by gregsadetsky** [comment]
Hey Tom,

Great news re: fixing it!

To give a bit of context, the SVG paths I was using in my repro example were extracted from a larger file that had itself been exported from the mobile app [Looom](https://www.iorama.studio/looom). If the fix in Three is not too complicated to do, it seems useful to support even "non standard" svg files.

I'm personally not necessarily expecting absolute parity with Chrome or other vector softwares -- the most important would be to not raise an exception. The point being that Chrome does show something for this file.

As for testing, if random points are not a good/representative test, would it be helpful if I tried to find other SVG files in the wild that trigger this same error?

**Comment by Mugen87** [comment]
>  Or do we create an e2e test? 

Ideally, you add a test SVG file to the `webgl_loader_svg` example (so we can select it via the dropdown UI element).

**Comment by gregsadetsky** [comment]
A small update, I downloaded ~8k svg logos/icons from a few sites hoping to see the issue described here, but none of the files failed (i.e. the `createShapes` call always worked)

This does seem to point to the original SVG file (exported from [Looom](https://www.iorama.studio/looom)) as being the origin of the problem. Per @Ttommeke's explanation, it probably had intersecting paths.

I'll check if the full SVG file can be shared in order to be added as a test.

**Comment by Ttommeke** [comment]
Hi

I'm sorry got distracted. feeling like an idiot here: I'm trying to create a pull request. But Github doesn't let me. I need to review the changes made to CONTRIBUTING.md . But I've no clue what i'm doing wrong.

**Comment by gregsadetsky** [comment]
hey @Ttommeke that's great to hear about the fix! what issue are you having when creating the PR?

do you have a fork open with the fix in a branch? if so I could try committing if you'd like. let me know! (my email is in my github profile as well if you want to ping me / debug this)

**Comment by Ttommeke** [comment]
It seemd like i could not create a PR from my dev to the main dev branch... Anyway, used another branch. PR is created. let me know if there is any feedback.
