### ISSUE TITLE
Positional Audio Crackling Distortion on iOS and Safari on Mac

### ISSUE THREAD

**Issue by virtualboys** [mrdoob/three.js#24796]
I added a couple positional audio sources to a scene where I walk around a space and the audiolistener's position is constantly updated, and it works fine on chrome on mac but has issues on my iphone as well as safari on mac. The audio begins crackling after some time and gets progressively worse until it is unbearable. 

Pretty sure it is related to this: [(https://bugs.webkit.org/show_bug.cgi?id=227199)]

**To Reproduce**

In the linked post there are some demos of the issue. I think it happens more quickly when there is a drop in framerate.

I worked around the issue by using THREE.Audio objects and manually lowering the volume based on distance. Seems like a custom implementation of PositionalAudio that doesn't use PannerNode shouldn't be too hard to do & would fix the issue.

**Comment by Mugen87** [comment]
> Seems like a custom implementation of PositionalAudio that doesn't use PannerNode shouldn't be too hard to do

It's more complex than you think since you also have to implement stuff like directional cones. A custom `PannerNode` is clearly out of scope.

This is not something we can fix in `three.js` so it's better to comment at the WebKit bug.
