### ISSUE TITLE
KTX2Loader detaches cached URL response.

### ISSUE THREAD

**Issue by dcervelli** [mrdoob/three.js#24806]
**Describe the bug**

Loading the same URL twice with `KTX2Loader` results in an error because the cached URL response (from the shared `Cache` referred to by `FileLoader`) is sent to a web worker and detached.

***Code***

```js
const url = '/sample.ktx';
const loader = new KTX2Loader();
const handleError = (error) => console.log(error);
const t1 = loader.load(url, undefined, undefined, handleError);
const t2 = loader.load(url, undefined, undefined, handleError);
```

The error will be printed out for the second load.

**Expected behavior**

You should get two distinct textures. You can work around it with a cache breaking parameter, but ideally it wouldn't take two downloads.

**Platform:**

I tested this in Chrome on MacOS on r131 but my reading of the code suggests it's still a problem.

Note this is essentially another instance of the problem addressed in #13710.

**Comment by dcervelli** [comment]
If you're open to a fix similar to #13710 (clone buffer before sending to web worker), I'd likely submit a PR.

**Comment by donmccurdy** [comment]
There's a cache that's supposed to deal with this —

https://github.com/mrdoob/three.js/blob/4e68936c2edef7f4984dd3b68e3420eae9e9d116/examples/jsm/loaders/KTX2Loader.js#L221-L229

Are you able to see why that cache gets missed, or create a demo that allows us to test that?

**Comment by dcervelli** [comment]
My apologies, I should have done more work before reporting: this was fixed in r132. 

I got confused because the `_taskCache` code was present in `BasisTextureLoader` in r131 and then in `KTX2Loader` in r132+ so I assumed behavior would be the same. I see now that with that code in `KTX2Loader`, it's working.

Thank you!
