### ISSUE TITLE
scene.background (regular texture) ignores camera.view

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#24812]
discovered in r129, did not check the latest...

**Comment by makc** [comment]
(tried to use camera.setViewOffset for zoom control - I imagine declared purpose of multi-screen rendering does not work either)

**Comment by Mugen87** [comment]
Considering the way how the background shader is implemented, any camera related settings are ignored right now.

https://github.com/mrdoob/three.js/blob/1a8b53fb93bf79a352bfd645259e75ea5367e5e5/src/renderers/shaders/ShaderLib/background.glsl.js#L7-L9

The idea of assigning a texture to `Scene.background` is to cover the screen. Are you trying to use `camera.view` to zoom into the background (or render parts of it)?

**Comment by makc** [comment]
not specifically zoom into the background, but rather the whole output. it is weird (and looks broken) when 3D part zooms in while background stays in place.

**Comment by Mugen87** [comment]
Fiddle for reproduction: https://jsfiddle.net/7hexb8sc/2/

I've also added a manual background mesh to the code that you can use as a workaround. It should behave similar to how `Scene.background` is processed.

**Comment by Mugen87** [comment]
I'm not sure about this issue. We can only add support for `setViewOffset()` if the projection matrix is evaluated in the shader. This looks like a bigger refactoring to me with various consequences for the background shader.

Right now, I tend to just updates the docs to make clear than `Scene.background` does ignore `setViewOffset()`.
