### ISSUE TITLE
add morph send warning 

### ISSUE THREAD

**Issue by lo-th** [mrdoob/three.js#24815]
look [here](https://jsfiddle.net/8f4cyto2/3/)
we have a warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll
is come with last release of three

**Comment by Mugen87** [comment]
This is a DirectX warning and should not affect the app. Does the log go away if you change the following block:

https://github.com/mrdoob/three.js/blob/c4110f7965483382058a5f6b4fde7e9b65dcdbd4/src/renderers/shaders/ShaderChunk/morphtarget_vertex.glsl.js#L11-L15

to:

```js
#pragma unroll_loop_start
for ( int i = 0; i < MORPHTARGETS_COUNT; i ++ ) { 
  
    if ( morphTargetInfluences[ i ] != 0.0 ) transformed += getMorph( gl_VertexID, i, 0 ).xyz * morphTargetInfluences[ i ]; 
  
} 
#pragma unroll_loop_end
```

**Comment by lo-th** [comment]
hi ok , no is same with patch

**Comment by Mugen87** [comment]
TBH, I'm not sure I understand what you mean. Do you mind elaborate in more detail?

**Comment by lo-th** [comment]
well i'm on glb model export from 3dsmax 
problem is morph export is not compress with draco 
so i apply my morph by code after loading in three.

i apply your change in THREE.ShaderChunk before init renderer

**Comment by lo-th** [comment]
is maybe because i add only one morph ?
i add more morph on other object and some warning disappear

**Comment by lo-th** [comment]
yes is that it only happens on mesh with one morph :)

**Comment by lo-th** [comment]
so it's not really a bug
thanks for your help
