### ISSUE TITLE
make under/overflow prevention 

### ISSUE THREAD

**Issue by Suprhimp** [mrdoob/three.js#24819]
**Is your feature request related to a problem? Please describe.**

Animation mixer update sometimes occur overflow and under flow. in repeat mode, at border time

**Describe the solution you'd like**

I think We have to maintain the time at the same value with duration.

so I suggest remove equal in this line

```
      // three/src/animation/AnimationAction.js,  line : 561
      
      	_updateTime( deltaTime ) {
        ....
        ....
			if ( time > duration || time < 0 ) {.  //originally if ( time >= duration || time < 0 ) 

        ....

```

To compare an animation to a video, If there are total length 3:00 (3 min) video, it goes 0 at 3 minute.

I think It have to be at 3:00 at 3minute after not 0:00.

Thanks for reading my suggestion.

**Comment by Mugen87** [comment]
Merging into #24609.
