### ISSUE TITLE
WebGLRenderer / WebGLRenderList custom sort method

### ISSUE THREAD

**Issue by SeanPeplinski** [mrdoob/three.js#24811]
**Is your feature request related to a problem? Please describe.**

There are many sorting use-cases that aren't possible to implement with only a custom Javascript sort comparison function (via `WebGLRenderer.setTransparentSort` and `WebGLRenderer.setOpaqueSort`). I would suggest an API change to allow the entire `WebGLRenderList.sort` method to be overridden with a callback that accepts parameters for all object lists and the sorting methods (either the default methods, or the custom sorting methods specified in WebGLRenderer).

A quick example use-case is logical grouping. Perhaps objects should be grouped by some condition and then sorted independently as a group by a certain sorting algorithm. Then, all groups should be sorted against each other by some other algorithm, like z-distance to the camera.

**Describe the solution you'd like**

I have a PR here with the suggested API changes to WebGLRenderer and WebGLRenderList: https://github.com/mrdoob/three.js/pull/24809

**Describe alternatives you've considered**

I have considered using renderOrder, Groups, and WebGLRenderer.setTransparentSort to accomplish my goals, but my specific use case is too complex. A further complication of mine is that I don't want to hijack the renderOrder field of any objects. My framework will be used by other developers, and they should be able to set their own renderOrder value, and my custom sorting algorithm should respect it.

**Additional context**

No additional context.

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/24809#issuecomment-1281953817
