### ISSUE TITLE
FontLoader spacing change to question mark in korean language

### ISSUE THREAD

**Issue by jungwoolee-letsee** [mrdoob/three.js#24829]
Hi there.

To use Korean fonts in 3D Mesh, the font.ttf file was converted into a json file using facetype.js. After that, I made a 3D Mesh using fontLoader as shown below.

<img width="2015" alt="sm-ar-board-front_–_tagCloudHandler_js-2_png_및_SMCU_png" src="https://user-images.githubusercontent.com/59555455/197131975-19b47f7b-e90e-44f3-9ba1-83a4c31d43fc.png">

The problem is that when you insert a space character in a Korean font, a question mark is output instead of a space character. (In English, spaces are printed well.)

I searched for the reason, but couldn't find a clear reason.

Any help would be greatly appreciated. thank you.

**Comment by Mugen87** [comment]
This is not an issue in `Font`, `FontLoader` or `ShapePath`. Please file an issue at the `facetype.js` repository: https://github.com/gero3/facetype.js
