### ISSUE TITLE
Geometries closeEnded

### ISSUE THREAD

**Issue by vecerilek** [mrdoob/three.js#24820]
**Is your feature request related to a problem? Please describe.**

It would be great if geometries that use thetaStart, thetaLength, phiStart, phiLength, Arc could close themselves without further modification of the geometry.

**Describe the solution you'd like**

Maybe a new parameter closeEnded as opposite to existing openEnded

**Describe alternatives you've considered**

Manually modifying generated geometry to be closed? Too complex for me :)

**Additional context**

Affected geometries - Cone, Cylinder, Sphere, Torus

**Comment by Mugen87** [comment]
There has been the goal to not overcomplicate geometry generators in the past and only enhance the implementation if there is a compelling reason. The ability to auto-close various geometries seems more like a nice-to-have feature. Hence, I think it's better to close the issue and refer to tools like Blender if you need more specific geometries.

**Comment by Mugen87** [comment]
AFAIK, there is no code for this in the official examples. Depending on whether an index is defined or not you have to close the geometry differently. A good understanding of how geometry data are processed by WebGL is a requirement so something proper can be implemented. I suggest you use the [forum](https://discourse.threejs.org/) if you are looking for help/guidance.
