### ISSUE TITLE
GLTFLoader: Accessor with no bufferView create an error

### ISSUE THREAD

**Issue by julienduroure** [mrdoob/three.js#24838]
**Describe the bug**

glTF accessor with no bufferView create an error

![image](https://user-images.githubusercontent.com/1696020/197395885-840a797f-b9cb-48c9-8586-f818ee9d1af2.png)

**To Reproduce**

Tested on https://gltf-viewer.donmccurdy.com/
Import the attached glTF file. This is a cube with a morph target that is identical to original mesh.
The accessor of target position has no bufferView, as all target position are zero

[bug_empty_bufferview.zip](https://github.com/mrdoob/three.js/files/9846710/bug_empty_bufferview.zip)

**Expected behavior**

glTF specification says 
> https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_accessor_bufferview

No error reported on glTF validator https://github.khronos.org/glTF-Validator/

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Firefox
 - Three.js version:  r145 ? See https://gltf-viewer.donmccurdy.com/

**Comment by Mugen87** [comment]
It seems the following section needs an update:

https://github.com/mrdoob/three.js/blob/c27c5d534974935fba3c1ecbf312c2f175b03de4/examples/jsm/loaders/GLTFLoader.js#L3028-L3035

**Comment by Mugen87** [comment]
It seems changing the above section to the following should fix the issue:
```js
if ( accessorDef.bufferView === undefined && accessorDef.sparse === undefined ) {

    const itemSize = WEBGL_TYPE_SIZES[ accessorDef.type ];
    const TypedArray = WEBGL_COMPONENT_TYPES[ accessorDef.componentType ];

    const array = new TypedArray( accessorDef.count * itemSize );
    return Promise.resolve( new BufferAttribute( array, itemSize ) );

}
```
