### ISSUE TITLE
TransformControls supports input value, not only mouse

### ISSUE THREAD

**Issue by graywhale** [mrdoob/three.js#24832]
Refer to #24830.

I checked out the editor example, and the position/rotation properties' values are in the world space, not local space. My requirement is to change the values both in the world space and the local space.

**Comment by Mugen87** [comment]
> I checked the editor example, and the position/rotation properties' values are in the world space, not local space

I'm afraid that is not true. The transform values in the sidebar are in local space. If you want to transform an object with a parent, use the [forum](https://discourse.threejs.org/) if you need help. `TransfromControls` is not related to this issue.
