### ISSUE TITLE
GLTFLoader light extras object properties not assigned to loaded Light object

### ISSUE THREAD

**Issue by danborutori** [mrdoob/three.js#24839]
**Describe the bug**

Light extras object in KHR_lights_punctual extension is not loaded in Light userData.

Checking the code assignExtrasToUserData is not called in GLTFLightsExtension._loadLight in GLTFLoader.js line 469.

**To Reproduce**

1. In Blender, create a light with custom property
2. Export the scene as GLTF format with lights_punctual and custom property turn on
3. Check the exported .gltf. You should see extras field of the exported light containing custom property defined in Blender.
4. Load the .glft file using GLTFLoader. Light in loaded scene does not contain the custom property.

**Expected behavior**
Custom property should present in Light userdata.

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: r145

**Comment by Mugen87** [comment]
Do you mind sharing a glTF asset that can be used for reproduction?

**Comment by danborutori** [comment]
[lit_w_property.zip](https://github.com/mrdoob/three.js/files/9851741/lit_w_property.zip)
 You may try this file.
The scene only contain one light with custom property propertyA = valueA.
