### ISSUE TITLE
TransformControls supports input value, not only mouse

### ISSUE THREAD

**Issue by graywhale** [mrdoob/three.js#24830]
Is there any way that TransformControls support change transfer/rotation/scale values in the **LOCAL SPACE** from text input, not only controlled by mouse.

Requirements:
1. display the **local space**'s values
2. change the **local space**'s values via text input

<img width="481" alt="iShot_2022-10-21_16 12 18" src="https://user-images.githubusercontent.com/29625655/197150096-1241c5e2-7c5c-4ddf-95d4-c341d3bbaf17.png">

**Comment by Mugen87** [comment]
In this case, you should directly transform the controlled 3D object like done in the [three.js editor](https://threejs.org/editor/).

**Comment by graywhale** [comment]
@Mugen87 Thanks

**Comment by graywhale** [comment]
@Mugen87 I checked the editor example, and the position/rotation properties' values are in the world space, not local space. My requirement is to change the values both in the world space and the local space.
