### ISSUE TITLE
Cross-browser issues; helper functions not particularly helpful

### ISSUE THREAD

**Issue by david-mark** [mrdoob/three.js#24845]
This library is supposed to enable cross-browser WebGL solutions while shielding the developer from the inherent complexity of WebGL, but these helper functions don't seem to be very helpful in that regard:

https://github.com/mrdoob/three.js/blob/master/examples/jsm/capabilities/WebGL.js

Assuming those functions are reliable, developers can detect if WebGL 1.0 is available and if WebGL 2.0 is available. And... then what?

Some library methods require the latter, some don't. Some throw exceptions when 2.0 is unavailable, some log errors to the console. So short of slogging through all of the code, which somewhat defeats the purpose of the library, what is a developer supposed to infer from these results?

For example, if 2.0 is available, then methods A, B and C will work and methods D, E and F work only for specific contexts. How would developers know this without reading the code for each method? Perhaps all of this is documented somewhere, but it shouldn't need to be. In short, users of this library should not need to know much of anything about what the library is doing with WebGL under the hood.

Not sure what to tell you, as the only solution I see would require a major re-design and rewrite. The appropriate cross-browser-enabling pattern that would allow for direct inferences is to detect required features internally, at the outset, and to create only those interfaces that will work in the current context.

Then developers could simply check whether the library features are there or not, without knowing anything about the host features it abstracts away. Inferences don't get much more direct than that and these are the sort that are required for simplified cross-browser scripting.

Instead of something like this:

if (isWebGL2Available) {
   A();
   B();
   C();
}

...calling code would simply check if A, B and C exist (usually at the outset) and proceed (or not) accordingly. For D, E and F, some refactoring would be required, as these will work for some cases and not for others. It's critical that the calling code be able to determine what will work before making the calls, else their script will either blow up or silently (for the user) log a failure.

I see a lot of similar forking inside the library as well, which is obviously subject to change over time and the described pattern allows for such changes without breaking existing projects. It would also simplify the code considerably.

I don't really expect you to do anything about this, as virtually every library seems to suffer from this same affliction and it is obviously very late in the game for this one. Might want to think about a complete overhaul if a sequel is ever considered.

**Comment by Mugen87** [comment]
Developing features that work for both WebGL 1 and 2 is not always possible because of certain major API differences. E.g. we can only provide 3D textures or multisampled render targets in WebGL 2 because there is no proper way to provide an emulated solution in WebGL 1.

Also notice that support for WebGL 1 will be removed at some point, see #22689.

I suggest to use the forum to discuss possible strategies for supporting a wide range of devices.
