### ISSUE TITLE
The PLY file becomes larger when it is rendered and output through BufferGeomerty 

### ISSUE THREAD

**Issue by liskysun** [mrdoob/three.js#24858]
### Project Process
+ 1、PlyLoader load PlyFile return BufferGeometry
+ 2、BufferGeometry use Index Pos to represent Geometry reults in Data Increase！
![image](https://user-images.githubusercontent.com/34642451/198208886-22535d07-0dad-4658-a12b-3181f231e8f0.png)
+ 3、PlyExporter Mesh return Ply ArrayBuffer （Larger）
![image](https://user-images.githubusercontent.com/34642451/198211489-e8a05391-8ff8-44fb-9bb2-7d9ecffbd5f1.png)
### Validation Process
+ 1、use MeshLab check it
**OriginFile： V: 38245 F: 76034
NewFile：  V: 228102 (BufferGeomerty Vertices Index)**
![3WmJLa1zJ9](https://user-images.githubusercontent.com/34642451/198209631-fd5c8408-bb92-4af1-8582-0e70fea43908.jpg)

+ 2、use MeshLab to Romve Duplicate Vertices
![image](https://user-images.githubusercontent.com/34642451/198211047-93ba95b7-ba9a-4bdf-bd08-ccb91bb5f104.png)

+ 3、result
![image](https://user-images.githubusercontent.com/34642451/198210861-1630d02b-4867-4e40-aafd-3ef6433420a0.png)
![image](https://user-images.githubusercontent.com/34642451/198212024-379aba75-57e4-4bce-959e-475f7a643963.png)

# Conclusion
**BufferGeomerty specific rendering structure make files larger！！！！！**

**Comment by Mugen87** [comment]
Do you mind sharing with your original PLY file for testing?

I've done a quick round-trip test with [dolphins.ply](https://github.com/mrdoob/three.js/blob/dev/examples/models/ply/ascii/dolphins.ply). The file size of the exported PLY file is indeed a little bit bigger than the original. The increase in size happens because numbers are exported with a higher precision. So something like `13.6601 0 548.364` becomes `13.660099983215332 0 548.364013671875`. A higher number precision is not necessarily bad.

> BufferGeometry use Index Pos to represent Geometry reults in Data Increase！

FYI: You have marked the wrong spot in your second screenshot. The entries in the arrays are not relevant, it's the `count` property. It's both 228102 for the index and the attributes.

**Comment by liskysun** [comment]
I use [dolphins.ply](https://github.com/mrdoob/three.js/blob/dev/examples/models/ply/ascii/dolphins.ply).
to test（Only position information is saved）
Result:  Files increased from 46kb to 158kb

![image](https://user-images.githubusercontent.com/34642451/198251730-8ea50693-dff3-4af9-930d-c0a742057811.png)

![image](https://user-images.githubusercontent.com/34642451/198251552-9d64aebd-9c63-4ebc-b248-119fef761f76.png)

**Comment by liskysun** [comment]
**This is my export code**

![image](https://user-images.githubusercontent.com/34642451/198253039-667108fd-b167-4d13-97ef-df9224e78394.png)

**Comment by liskysun** [comment]
**The root cause is that the data volume has increased after the file is loaded**

![image](https://user-images.githubusercontent.com/34642451/198253801-56f3b797-c3a5-4efc-a87e-6dce32a2038c.png)

**Comment by Mugen87** [comment]
Do you see the same result when using the [editor](https://threejs.org/editor/)? You can drag'n'drop the PLY file to load it and then export via the menu.

**Comment by liskysun** [comment]
This is my version："three": "^0.145.0"

**Comment by liskysun** [comment]
I used the [editor](https://threejs.org/editor/) you mentioned, and the file became larger
![image](https://user-images.githubusercontent.com/34642451/198257411-8b1922bb-861b-4e0d-bd10-595433427ca9.png)

**Comment by liskysun** [comment]
BufferGeometry does make the original ply file larger. Similarly, other types of files will also become larger when transferred to BufferGeometry

**Comment by Mugen87** [comment]
I'm afraid your post are not super clear so I can't comprehend the issue. As mentioned above, the files get larger because the `PLYExporter` creates numbers with higher precision. 

But it does not generate additional faces or make the geometry more complex. The round-trip result with `dolphins.ply` is as expected and not considered as a bug.

**Comment by LeviPesin** [comment]
Maybe it can export numbers with a smaller precision? Not sure that precision of a one quadrillionth is something worth increasing file size...

**Comment by Mugen87** [comment]
> Using the binary PLY option would probably also solve the issue here.

This would be my preferred suggestion. TBH, I'm not a fan for adding a separate API to define the number of decimal places.

**Comment by liskysun** [comment]
**This is the result of configuring binary: true**
![image](https://user-images.githubusercontent.com/34642451/198431733-df1840dc-79f4-4527-bfb1-38a747bfb4ca.png)

**Comment by liskysun** [comment]
> Maybe it can export numbers with a smaller precision? Not sure that a precision of one quadrillionth is something worth increasing file size...

I have tried to keep 5 decimal places, which has little effect on the file size.

**Comment by liskysun** [comment]
[editor](https://threejs.org/editor/)：Only Pos information is saved
![image](https://user-images.githubusercontent.com/34642451/198445512-4782a33e-e11a-496b-bc78-47472d799649.png)
![image](https://user-images.githubusercontent.com/34642451/198445609-c6091f2b-d841-45a2-a93b-7cfa9e882b30.png)

**Comment by liskysun** [comment]
**If I configure this**
![image](https://user-images.githubusercontent.com/34642451/198447355-fc332c32-0569-4b54-9011-b95abef51684.png)
**I'll get the same result but lose the information 'uv' 'normal'**
![image](https://user-images.githubusercontent.com/34642451/198448712-7b27e068-ded1-42c6-a5e0-c2268f918fff.png)

**Comment by liskysun** [comment]
**At first, I chose the ply file because of its binary storage form.**
**It can make the model file smaller**
**If the ply file becomes larger when exporting without losing key information, this will lose the significance of using it**

**Comment by liskysun** [comment]
**Try importing and exporting a ply file with ‘pos’ ‘uv’ ‘color’ ‘normal’ to see the changes in the file.**
dolphins.ply only contains ’pos‘

**Comment by Mugen87** [comment]
I can only test with [dolphins_colored.ply](https://github.com/mrdoob/three.js/blob/dev/examples/models/ply/ascii/dolphins_colored.ply) which has vertex colors. The increase in file size happens for the same reason as mentioned above.

**Comment by Mugen87** [comment]
If you really care about file sizes, you probably want to use `DRACOExporter`.

https://threejs.org/examples/misc_exporter_draco

**Comment by liskysun** [comment]
**You can try a PLY file with 'uv', 'normal', 'pos'. The file will become large.**
**Because my PLY is generated through 3D reconstruction.**
**If the PLY path fails, I will try OBJ File in the next step.**

**Comment by Mugen87** [comment]
> You can try a PLY file with 'uv', 'normal', 'pos'. The file will become large.

Sorry, I have not a file with all three attributes. Only with position and color. And as mentioned in my comment https://github.com/mrdoob/three.js/issues/24858#issuecomment-1294630522, the result is as expected.

Sorry, I'm not going to investigate more time in this issue. I suggest you use DRACO and not OBJ.

**Comment by liskysun** [comment]
Thank you very much for your answer! I'm going to discard the PLY file temporarily
