### ISSUE TITLE
为什么没有解析usd 模型 或者导出usd模型的loader 

### ISSUE THREAD

**Issue by calmheaded** [mrdoob/three.js#24856]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mugen87** [comment]
Please write issue in English. Also fill out the issue template properly.

**Comment by calmheaded** [comment]
Why didn't you parse the USD model or export the loader of the USD model. Is there any technical problem in developing a library to analyze the USD model
