### ISSUE TITLE
Support Plane Detection API

### ISSUE THREAD

**Issue by richardanaya** [mrdoob/three.js#24853]
**Is your feature request related to a problem? Please describe.**

With Oculus Browser now supporting Plane Detection API, this could be implemented.

**Describe the solution you'd like**

Implement plane detection API into the XRManager as per this reference example: https://immersive-web.github.io/webxr-samples/proposals/plane-detection.html

**Describe alternatives you've considered**

N/A

**Comment by Mugen87** [comment]
Merging this into #24792.
