### ISSUE TITLE
import WebGPURender，but Can't resolve 'three/nodes' in npm

### ISSUE THREAD

**Issue by lishulincug** [mrdoob/three.js#24866]
**Describe the bug**
Three is a grammar bugs in the nodes for a long time,I try it not use in r144、r145、r146 three.js。
input:
import WebGPU from 'three/examples/jsm/capabilities/WebGPU.js'
import WebGPURenderer from 'three/examples/jsm/renderers/webgpu/WebGPURenderer.js'

output:
Failed to compile.

./node_modules/_three@0.146.0@three/examples/jsm/renderers/webgpu/WebGPURenderStates.js
Module not found: Error: Can't resolve 'three/nodes' in 'C:\code\Haomo\car-ui\legacy-render\node_modules\_three@0.146.0@three\examples\jsm\renderers\webgpu'
![image](https://user-images.githubusercontent.com/13003282/198545344-8925c59e-656d-41ba-ac7e-9d82c2c4b8f2.png)

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**To Reproduce**

3. See error

***Code***

```js
// code goes here
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hbfpj2wv/2/)
* [jsfiddle-dev](https://jsfiddle.net/086yzvgc/)

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [r146]

**Comment by donmccurdy** [comment]
I can't tell what your build system (if any) is above, but you'll need to either:

- (a) use a build system like vite or webpack that supports "exports" in package.json
- (b) use an import map defining the path to three/nodes if not using a bundler

If you're having trouble setting that up, feel free to share details on the threejs forums for help!
