### ISSUE TITLE
TransformControl factor calculation when using Orthographic camera

### ISSUE THREAD

**Issue by phantasma2983** [mrdoob/three.js#24861]
When using the Orthographic Camera the zoom level of the camera affects the transformation sensitivity way too much compared to Perspective camera. 

I've built an application similar to a house planner in feature set. In it, you can switch between a Perspective or an Orthographic camera while trying to preserve the perceived view of the object when switching. This means having to approximate the zoom level of the Orthographic camera to the distance to target of the Perspective camera. 

While this is working to some extent (a feature to match these would be nice) I'm having problems with TransformControls on a selected object while in orthographic mode.  When having the zoom to match a close up view of an object in order to rotate the object a few degrees you need to move your mouse and entire screen width. This is not the case with perspective mode where the transformation factor is much higher regardless of the distance to target.

I've narrowed down the code inside TransformControls that is responsible for this: 

https://github.com/mrdoob/three.js/blob/868aee4c3bda29077ba53989cea07948a474782e/examples/jsm/controls/TransformControls.js#L1178-L1188

Because of this, the more you zoom in, on orthographic view it becomes harder (slower) to transform objects and easier (faster) when you zoom out.

There might be a use-case where this makes sense to this extent, I just can't think of it. Is this a bug or is it intended functionality?
It makes sense to be more sensitive when zooming in but not this much. Also it then should also work the same in perspective view.

**Comment by Mugen87** [comment]
This code block was introduced here: #19163

/ping @arodic

**Comment by phantasma2983** [comment]
My bad, that code is for the magnification factor of the Gizmo depending on zoom level. What about the transformation sensitivity from mousemove? That seems to also be dependent on Orthographic camera zoom level.

**Comment by phantasma2983** [comment]
My bad, that code is for the magnification factor of the Gizmo depending on zoom level. What about the transformation sensitivity from mousemove? That seems to also be dependent on Orthographic camera zoom level.
