### ISSUE TITLE
Put `samples` next to `pause` control inside gui

### ISSUE THREAD

**Issue by ycw** [mrdoob/three.js#24860]
in https://threejs.org/examples/?q=trac#webgl_renderer_pathtracer

current: 
![oh no](https://user-images.githubusercontent.com/1063018/198308596-512297f5-f45e-4237-8d4d-a9759d21ec0b.png)

ideal:
![oh better](https://user-images.githubusercontent.com/1063018/198309275-e41be970-5f22-4b64-82b3-1b937be7c23d.png)

**Comment by gkjohnson** [comment]
> Maybe a separate line like in [webgl_instancing_performance](https://threejs.org/examples/#webgl_instancing_performance) (GPU draw calls/memory)?

This sounds good to me!
