### ISSUE TITLE
ReferenceError: DracoEncoderModule is not defined

### ISSUE THREAD

**Issue by liskysun** [mrdoob/three.js#24879]
**This is my code：**
![image](https://user-images.githubusercontent.com/34642451/198967533-b7547321-9060-4cdd-8eb7-a812d23810cd.png)

![image](https://user-images.githubusercontent.com/34642451/198967106-da5c1249-13cf-44ac-aab0-d88154c51c96.png)

**result:**
![image](https://user-images.githubusercontent.com/34642451/198967331-a6616001-f4f6-46b8-b5b9-fd2f1e5903fc.png)
![image](https://user-images.githubusercontent.com/34642451/198967398-67ed27f9-6f08-4f30-816a-8959245e7606.png)

**Comment by Mugen87** [comment]
It looks like you are not importing the DRACO encoder properly. The official example uses:

    <script src="js/libs/draco/draco_encoder.js"></script>
