### ISSUE TITLE
Official Webcam Video Material Demo gradually consumes the full RAM in firefox

### ISSUE THREAD

**Issue by ultWorld** [mrdoob/three.js#24878]
**When using the webcam video demo my RAM gets full and my PC eventually hangs if i stay there for too long**

**To Reproduce**

1. Go to Threejs Webcam demo page 'https://threejs.org/examples/#webgl_materials_video_webcam'
2. Open Ubuntu System monitor on the side or any other memory monitor
3. Observe the ram used value.

**Expected behavior**

To stream the webcam without consuming full RAM.

**Screenshots**

Below two screen shots are of the system monitor of Ubuntu. Red line indicate the % free RAM and green line is % free swap.
![image](https://user-images.githubusercontent.com/104983217/198951640-a63617eb-5539-4b52-93c1-63889270d786.png)

Screenshot with description
![image](https://user-images.githubusercontent.com/104983217/198952587-50d3f79a-02a6-4501-974f-a43d3b4ab0d1.png)

**Platform:**

 - Device: Desktop
 - OS: Ubuntu
 - Browser: Firefox 
 - Three.js version: r146

**Comment by Mugen87** [comment]
Does this only happen with Firefox? How does it look like with Chromium?

Can you also test with Firefox on a different OS? E.g. Windows or macOS?

**Comment by Mugen87** [comment]
Closing. If you can reproduce the issue only in Firefox, please file an issue here: https://bugzilla.mozilla.org/
