### ISSUE TITLE
'ONLY_MODULE' is not recognized as an internal or external command in windows

### ISSUE THREAD

**Issue by mankeheaven** [mrdoob/three.js#24870]
Can not set env 'ONLY_MODULE' in windows.
You can set scripts like this with cross-env module 
` "build-module": "cross-env ONLY_MODULE=true rollup -c utils/build/rollup.config.js",`

**Comment by ycw** [comment]
simply ...

[rollup.config.js](https://github.com/mrdoob/three.js/blob/4cd8eefacac8bfe8ee32245e314a85ff3d719b9d/utils/build/rollup.config.js#L366)
```js
export default (args) => args.configOnlyModule ? builds[0] : builds
```
[package.json](https://github.com/mrdoob/three.js/blob/4cd8eefacac8bfe8ee32245e314a85ff3d719b9d/package.json#L108)
```json
"build-module": "rollup -c utils/build/rollup.config.js --configOnlyModule"
```

:)

**Comment by Mugen87** [comment]
@mrdoob Would you be okay with removing the `build-module` script? For simplicity reasons, I think having a single `build` seems sufficient.

**Comment by mrdoob** [comment]
@Mugen87 I agree 👍

**Comment by WestLangley** [comment]
No, please do not remove that. #22442.

**Comment by Mugen87** [comment]
`three.module.js` is the first build target when executing `npm run build`. So there is no difference in performance unless you make many sequential builds. And when using `npm start`, builds are automatically canceled if something changes in the code base so you really don't loose much time.

**Comment by WestLangley** [comment]
Removing features does not help anybody.

Please do not remove this feature.

**Comment by mrdoob** [comment]
Removing features helps maintainers... Less things to maintain.

Having said that, @ycw's solution seems nice too!

**Comment by WestLangley** [comment]
I would be nice if @Mugen87 or @marcofugaro would retain it somehow.

**Comment by marcofugaro** [comment]
@WestLangley from the understanding, the root of the problem is that the `build` command is slow, right?

We could fix this by switching to esbuild. But is it ok for @mrdoob?
It would be a nice exchange since three.js is featured [on esbuild's homepage](https://esbuild.github.io/) 🤓

**Comment by WestLangley** [comment]
@marcofugaro It is not slow IMO, but I would prefer to build only what I need. If that can continue to be supported, I would appreciate it. :-)

**Comment by mrdoob** [comment]
@marcofugaro The reason I have not switched to esbuild is that it's a native app I'm not allowed to run native apps without permission at Google. And having to ask for permission every time it updates is a pain.

**Comment by mrdoob** [comment]
@WestLangley I've implemented @ycw's approach: https://github.com/mrdoob/three.js/commit/ecba5cc13020b3e480043b6a0be1cc3a38857313

**Comment by WestLangley** [comment]
Many thanks, @mrdoob!
