### ISSUE TITLE
THREE.WebGLProgram: Shader Error 1282,THREE.WebGLRenderer: Context Lost.

### ISSUE THREAD

**Issue by Parisa-DolphinSoft** [mrdoob/three.js#24883]
Hi,I have a problem with WebGL in Three js
I have a scene in three js and I import 3dmodels and add to the scene.
(I download them from sketchfab in gltf format ,some of them with animation and some of them not)
My PC hardware has 8 GB RAM,CPU i5-3,SSD 128 (But I tested again with a laptop that has 16 GB RAM but again I faced with this problem)

When I run my Program in Chrome browser after adding 3-6 models with size 30MB,5MB,25MB,7MB,... for example
(2 of them have animation and I add those animations from gltf.animations to gltf.scene.animations in gltfloader by travers,mixer ... and add gltf.scene to main scene as a group 3dobject with animations)

Sometimes these oprations fill my RAM about 4GB(just add and show 5 3dmoedls that have animations but I do not play them)
And Sometimes I faced with these errors:

 * react_devtools_backend.js:4026 THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false
 * WebGL: INVALID_OPERATION: useProgram: program not valid
 * react_devtools_backend.js:4026 THREE.WebGLProgram: Shader Error 1282 - VALIDATE_STATUS false
 * WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
 * THREE.WebGLRenderer: Context Lost.
 * Sometimes : three.module.js:27177 THREE.WebGLRenderer: Context Restored.
 * Failed to execute 'shaderSource' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLShader'.
 * three.module.js:27169 THREE.WebGLRenderer: Context Lost.

Can you help me please how can I solve this Problem??!!

**Comment by LeviPesin** [comment]
Can you please provide an example reproducing the issue?

**Comment by Parisa-DolphinSoft** [comment]
Look at this picture
I can not send code because they are alot and connected to each other
[https://im.ge/i/2KQTBW](url)

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for such requests. If it turns out to be an problem in the engine, we can reopen the issue.

**Comment by Parisa-DolphinSoft** [comment]
What do you mean by forum?

**Comment by Mugen87** [comment]
https://discourse.threejs.org/ is the `three.js` forum. It's intended for help requests. GitHub is only for bugs and feature requests.

**Comment by Parisa-DolphinSoft** [comment]
Thanks
