### ISSUE TITLE
Materials do not render while all Additional postprocessing disabled in EffectComposer

### ISSUE THREAD

**Issue by sdarpeng** [mrdoob/three.js#24898]
**Describe the bug**

I added 2 passes to my composer, 1 is unreal bloom effect and the other is outline effect.
While I disable all the effects. my model losts some of  materials of it , sometime it will lost all the materials.
![image](https://user-images.githubusercontent.com/55733077/199509047-566e32a4-6817-4b2f-9e80-be51243631fd.png)

![image](https://user-images.githubusercontent.com/55733077/199508699-3bd60cb3-cd28-499a-b102-374002e4327d.png)

While I keep 1 of them, my model looks good.
![image](https://user-images.githubusercontent.com/55733077/199508571-7a614475-98c5-4159-af78-219b4380122a.png)

**To Reproduce**

3. See error

***Code***

```js
// code goes here
```
			function animate() {
				requestAnimationFrame( animate );
				if(stats){
					stats.update();
				}

				render();
				if(controls){
					controls.update();
				}
				bloomPass.enabled =  settings['PostProcessing'];
				outlinePass.enabled = settings['PostProcessing'];
				composer.render();
			}
***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/hbfpj2wv/2/)
* [jsfiddle-dev](https://jsfiddle.net/086yzvgc/)

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: Desktop/Mobile
 - OS: Windows/iOS
 - Browser: [Chrome,  Safari,]
 - Three.js version: [r143]

**Comment by Mugen87** [comment]
Please let you help at the [forum](https://discourse.threejs.org/) first. Also make sure to share to demonstrate the issue with a live example. Screenshots and small code snippet are not sufficient to investigate this issue.
