### ISSUE TITLE
Is TextGeometry deprecated? How do I create Text?

### ISSUE THREAD

**Issue by liskysun** [mrdoob/three.js#24893]
### issues three r145
+ **There is also an introduction in the document**
+ **Cannot find TextGeometry**
### doc
![image](https://user-images.githubusercontent.com/34642451/199385729-7a1567cb-6170-42f9-815c-81ca3889ae5e.png)
### code
![image](https://user-images.githubusercontent.com/34642451/199385792-5a99570f-cf0c-4eee-8d8c-4ccdc0306d12.png)

**Comment by liskysun** [comment]
"@types/three": "^0.144.0"

**Comment by liskysun** [comment]
**Can I use it like this**
![image](https://user-images.githubusercontent.com/34642451/199389415-87bb2059-6882-4c65-80c0-06a6f1a8cdb8.png)

**Comment by Mugen87** [comment]
Pleas use the [forum](https://discourse.threejs.org/) for help requests.
