### ISSUE TITLE
ThreeJs doesn't render, my .pcd file using PCDLoader

### ISSUE THREAD

**Issue by ajitStephen** [mrdoob/three.js#24899]
Gives me empty canvas, no errors on console!
some context on .pcd file >>

original file was .LAZ from PIX4D
.pcd file which created from PDAL v2
renders in viewer just a black screen. Viewer I used : pcl-pcl-1.12.1/pcl_viewer (Working on Ubunty 20.04)

I see this error when viewer is running:
[fromHandlersToScreen] PointCloud </home/ajit/Downloads/point_clouds/low_quality.pcd-0> requested with an invalid geometry handler (PointCloudGeometryHandlerXYZ)!
[updateColorHandlerIndex] PointCloud with id </home/ajit/Downloads/point_clouds/low_quality.pcd-0> doesn’t exist!

Failed to load on this example as well, [pcd loader example](https://threejs.org/examples/?q=pcd#webgl_loader_pcd)

**To Reproduce**

1. Use PCDLoader example with my file
2. File Link: (getting confirmation from boss ~ NDA)
3. See results: Empty Canvas

**Expected behavior**

Loaded 3D Model 

**Screenshots**
![Screenshot from 2022-11-02 18-43-39](https://user-images.githubusercontent.com/12784114/199519840-9ef28f94-10c8-465e-8705-7f55b40f1eb1.png)

[PCLoader Response Object.txt](https://github.com/mrdoob/three.js/files/9921247/PCLoader.Response.Object.txt)

**Platform:**

 - Device: [Desktop]
 - OS: [Ubuntu 20.04]
 - Browser: [Brave(Version 1.45.116 Chromium: 107.0.5304.91), Chrome(107.0.5304.87-1) ]
 - Three.js version: [0.146.0,  0.138.0]

**Comment by Mugen87** [comment]
Please let you help at the [forum](https://discourse.threejs.org/) first. Also make sure to share the actual PCD file. The object you have shared is a JSON asset.
