### ISSUE TITLE
Implement window-controls-overlay

### ISSUE THREAD

**Issue by glitch128** [mrdoob/three.js#24902]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**

I would like the "window-controls-overlay" API to be implemented to give the PWA a more app-like experience.
**Describe alternatives you've considered**

**Additional context**
N/A
[Web.dev - Window controls overlay API](https://web.dev/window-controls-overlay/)

**Comment by donmccurdy** [comment]
I'm not sure how threejs (a library, not a web app) could implement this. You could of course enable these features in your own PWA, and also use threejs in that PWA. I'd recommend using the forms if you're looking for help in setting something like that up.

**Comment by glitch128** [comment]
sorry, I did not clarify. I meant to say to implement the API onto the [threejs editor](https://threejs.org/editor/) website

**Comment by LeviPesin** [comment]
Duplicate of https://github.com/mrdoob/three.js/issues/23153.
