### ISSUE TITLE
Cannot upload a WebGLRenderTarget Texture as a regular texture

### ISSUE THREAD

**Issue by sguimmara** [mrdoob/three.js#24906]
I am using a `WebGLRenderTarget` to render a scene into a texture. Then I want to apply this texture into an object, and render this object in another scene. I have two distinct `WebGLRenderer`s : the one for the render-to-texture, and one for the regular 3D scene.

When uploading the `Texture` created by the `WebGLRenderTarget`, the WebGL(2) context throws an error :

```
THREE.WebGLState: TypeError: WebGL2RenderingContext.texSubImage2D: Argument 7 is not valid for any of the 7-argument overloads.
```

When debugging the function `texSubImage2D()` : 

```javascript
function texSubImage2D() {

		try {

			gl.texSubImage2D.apply( gl, arguments );

		} catch ( error ) {

			console.error( 'THREE.WebGLState:', error );

		}

	}
```

The 7th argument in `arguments` is the render target `Texture.image`, but it's just a simple JS object with no actual data (since the data is only in the GPU memory I figure) :

![image](https://user-images.githubusercontent.com/5512096/199688525-bf8c8998-ac1c-48e2-85b9-14d68d36777d.png)

Note : if `Texture.needsUpdate = false`, then the error does not appear, but the texture is not uploaded.

**To Reproduce**

See fiddle

***Code***

See fiddle

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/yrhsq7cL/2/)

**Expected behavior**

We should be able to use a render target texture like any other texture. Probably also the texture should not need to be "uploaded" as its data is already in GL memory.

**Screenshots**

N/A

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Firefox
 - Three.js version: r135

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

We use render target as textures at different places in the repo without issues. I suggest you modify the following example to demonstrate the issue as a live example.

https://threejs.org/examples/#webgl_rtt

**Comment by sguimmara** [comment]
@Mugen87  But there's a bug though : when setting `texture.needsUpdate` on a RenderTarget's texture, we have this error. I fixed my issue by removing this line, but there should probably be some guard against "updating" render textures.

**Comment by Mugen87** [comment]
I would only vote to add such a check if more users run into this issue.
