### ISSUE TITLE
attenuationDistance causes conflict with MeshPhysicalMaterial

### ISSUE THREAD

**Issue by Creative-Ataraxia** [mrdoob/three.js#24914]
setting `attenuationDistance ` to 0 will cause `MeshPhysicalMaterial` to not render; please see attached screen cast

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome, Firefox]
 - Three.js version: [146]

https://user-images.githubusercontent.com/102127487/200123304-12d5ac77-7c23-4316-929a-9b2a9c969f35.mp4

**Comment by WestLangley** [comment]
The [KHR_materials_volume spec](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_volume)  requires that `attenuationDistance` be greater than zero if present.

> range is (0, +inf)

**Comment by Creative-Ataraxia** [comment]
thank you!

**Comment by WestLangley** [comment]
And thank you for the report. :-)
