### ISSUE TITLE
DragControls should allow user to decide whether to recursively raycast draggable objects

### ISSUE THREAD

**Issue by clintonwoo** [mrdoob/three.js#24915]
**Is your feature request related to a problem? Please describe.**

Drag controls currently always supplies a `true` recursive raycasting value when deciding which object should be dragged (eg. when it calls `_raycaster.intersectObjects( _objects, true, _intersections );` . This means currently there's no way to make an object draggable without making it's children draggable.

In some scene graphs the users want to make the ancestor nodes draggable while their children stay non-draggable. For example to drag groups together while the children stay locked in place.

**Describe the solution you'd like**

`DragControls` should allow the user to set a recursive option like `dragControls.recursive = false;` when the user decides whether they would like to supply the ancestors of draggable nodes or they need fine-grained control around which object is draggable.

**Describe alternatives you've considered**

Perhaps the API could be `dragControls.setRecursive(value);` or `new DragControls(objects, camera, domElement, recursive);` but I think this bloats the API and makes it less simple to use.

**Additional context**

One main use case for this is when the graph is laid out using a layout algorithm (eg. force layout) and we want to drag groups while locking the group children in place without making them draggable.

**Comment by Mugen87** [comment]
> For example to drag groups together while the children stay locked in place.

Um, I don't think you can enforce this by setting `recursive` to `false`. It won't be possible to drag ancestor nodes but they will still be transformed when their top-most node gets dragged.

**Comment by clintonwoo** [comment]
> > For example to drag groups together while the children stay locked in place.
> 
> Um, I don't think you can enforce this by setting `recursive` to `false`. It won't be possible to drag ancestor nodes but they will still be transformed when their top-most node gets dragged.

Sorry if the explanation was not clear. The intention is for the DragControls objects array to control precisely which objects are able to be dragged without allowing their children to be dragged. As you explained it's not a problem for the children to move when the ancestor is dragged since this is intended behavior in the scene graph.

One use case would be having a mesh group as a sphere wrapping around all the children. The ancestor object (a sphere representing a group) would be able to be dragged while the user can't individually drag the children of the sphere since they have a special layout inside the group. So we would have fine-grain control around which children can be dragged if some are locked and some are draggable. If we want the children to be draggable we can add them to the objects array.

**Comment by Mugen87** [comment]
Um, I'm not sure about this proposal. User could find it confusing how the `recursive` flag with a `false` value works. It seems to use case specific to me.

Right now, I vote to not change `DragControls` unless more users request this feature.

**Comment by Mugen87** [comment]
You can achieve the same output via layers. https://jsfiddle.net/9u2es4o3/2/

Meaning you receive the internal raycaster of `DragControls` via `DragControls.getRaycaster()`. You then define a layer so only objects with the respective layer enabled are draggable. In the above fiddle its `1`. 

In this way, no modifications to `DragControls` are necessary.
