### ISSUE TITLE
Drawing TubeGeometry segments at non-equidistant points

### ISSUE THREAD

**Issue by jajetloh** [mrdoob/three.js#24925]
**Is your feature request related to a problem? Please describe.**

Using `TubeGeometry.setDrawRange()` to control the amount of a `TubeGeometry` that is rendered to/from a precise location on the tube's path is difficult, as `TubeGeometry` uses `path.getPointAt()` to find equidistant locations along the path to draw vertices.

For example, consider a `TubeGeometry` constructed from a `CurvePath` with 4 segments (5 vertices) with respective lengths (1,2,3,4), and we wish to display any continuous section between two vertices. This is a small example, and workable with some alternatives explained below, but this breaks down in the general case of not-so-nice coordinates and longer paths.

**Describe the solution you'd like**

This can be fixed relatively easily by allowing the use of `path.getPoint()` instead of `path.getPointAt()` in `TubeGeometry`'s segment generation, triggered by some flag when constructing the `TubeGeometry`. If this is the case, we just need to supply `TubeGeometry` with a path whose vertices are the locations we desire, and the flag, and segments are drawn at the given vertices, and `.setDrawRange()` can easily be used to show segments between vertices. We can then provide the path using a `CurvePath` if issue #24924  is fixed.

**Describe alternatives you've considered**

I've considered two options besides the proposed solution:

1. Choose the `tubularSegments` parameter to be a multiple of the lengths (1,2,3,4) - we can then figure out what values to pass `.setDrawRange()` to show the parts we want
2. Instead use multiple `TubeGeometry` or `CylinderGeometry` instances

Either option is not great for longer paths, as in case 1. we end up with a gigantic number of segments and in case 2. we have to instantiate and manage a large number of geometries.

We also can't just use a map of `t` to `u` values that are then passed to `TubeGeometry.setDrawRange()` as we aren't guaranteed that the generated segments line up with our desired vertices, again unless we have a large value for `tubularSegments`.

**Additional context**

My use case for this is a physics trajectory visualisation, so precise control of the tube vertices shown is required, and `.setDrawRange()` seems to be the most elegant way to deal with this.

This is a relatively easy feature to add, so if there's agreement that this is a good idea, I can submit a PR for this.

**Comment by Mugen87** [comment]
For your specific use case, I suggest you use a custom version of `TubeGeometry` or indeed your proposed solution by using multiple instances of `TubeGeometry`/ `CylinderGeometry` (and then render them via `InstancedMesh`).

I don't think it's appropriate to change the internal curve sampling since this will affected existing use case which rely on the current implementation.
