### ISSUE TITLE
Issues: Inaccuracy NRRD slices' number

### ISSUE THREAD

**Issue by LinkunGao** [mrdoob/three.js#24920]
**Describe the bug**

When we render a NRRD file on threejs, the total slices' number does not match the actual NRRD slices' number.
For example, A 3D dimensional for a NRRD file is 256 x 256 x 113, then if we load it on ITK snap software we can get the z position has 113 slices, the x position has 256 slices, and the y position has 256 slices. See fig1. Then if we render the NRRD file on threejs, we can get the result Fig2. The z position at least has 168 slices, but the x and y position only have 238 slices. 

If threejs render a NRRD file like this, How do we find out how the NRRD slice in threejs corresponds to the actual NRRD slice?

For further debugging (Fig3), I found out the threejs are based on `RASDimensions` to extract Slice and display, why do not use `dimensions` to handle this? 

**Screenshots**
Fig 1: the NRRD file is loaded in ITK snap software:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/80797317/200205975-6ce1430f-a14b-44a9-bed2-14917e96de13.png">
Fig 2: Same Nrrd file is rendered in Threejs environment:
![image](https://user-images.githubusercontent.com/80797317/200206800-3394f4bc-f313-4f67-a02d-e6558d4556a5.png)

Fig 3:
![image](https://user-images.githubusercontent.com/80797317/200207752-dbe1c640-3c8e-4127-b7f1-9330274fca63.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Windows, MacOS,]
 - Browser: [Chrome]
 - Three.js version: [dev, r144]

**Comment by Mugen87** [comment]
> For further debugging (Fig3), I found out the threejs are based on RASDimensions to extract Slice and display, why do not use dimensions to handle this?

@stity @developers-mirrorme3d @sonisourabh Do you know the answer to this question?

**Comment by LinkunGao** [comment]
Thanks @Mugen87

Now I know the answer to my question. Threejs is correct in using RASDimensions, this is better to render volume data, such as when we use Data3DTexture to display data.

As for the index number not matching the real nrrd slice index when loading it in threejs environment, we can simply use `voxel spacing`  to convert the slice index number and let threejs extract the Slice that we wanted. Actually, threejs has already provided the spacing array for us to achieve the converting task.
![image](https://user-images.githubusercontent.com/80797317/201012930-73aabf03-c854-4979-b48f-40f6348a4855.png)

**Comment by Mugen87** [comment]
Since the original developers of `NRRDLoader` seem to be not active anymore, we would appreciate if someone with knowledge of the NRRD format could have a look after the loader. Right now, there are some open issues in context of `NRRDLoader` (you have filed two of them btw^^). 

https://github.com/mrdoob/three.js/issues/22018, https://github.com/mrdoob/three.js/issues/23888, https://github.com/mrdoob/three.js/issues/24501, https://github.com/mrdoob/three.js/issues/24481

**Comment by LinkunGao** [comment]
Happy to have a look at them! : D
