### ISSUE TITLE
Only one 3d model animation run when I export a scene with 2 same 3d models and 2 same animations.

### ISSUE THREAD

**Issue by quangtri3111996** [mrdoob/three.js#24952]
- I use the three editor to export a scene(.glb) with 2 same model and 2 same animation. When I import the scene again, only one of them run the animation.

**Comment by Mugen87** [comment]
How do you create your scene in the editor? Do you import it from a glTF asset?

**Comment by quangtri3111996** [comment]
Hi @Mugen87, thanks for the reply.

I used https://threejs.org/editor/ to create the 3D scene. When I add 2 same models with 2 same animations. Then I export this scene (.glb file) and import that I exported but it doesn't play the animation correctly.

I noticed when I add 2 the same 3d models, this happens. 

Please watch the video (https://www.youtube.com/watch?v=_pIVT--VGPE) for details. Thank you!

**Comment by Mugen87** [comment]
Thanks for the additional details.

This is indeed a current limitation of the editor and exporter. It's a bit complicated to explain the issue briefly but essentially the root/level where animations are executed changes after the export. Meaning animations are not executed on object but scene level which potentially breaks animations (depending on how keyframe tracks target their nodes).

**Comment by quangtri3111996** [comment]
You have any ideas to solve this issue? Can give me some advices.

Thanks you!

**Comment by quangtri3111996** [comment]
Thanks @Mugen87,

Hope, this issue can be fixed soon !

**Comment by Mugen87** [comment]
Merging this into #25179.
