### ISSUE TITLE
controls.autoRotateSpeed is tied to framerate

### ISSUE THREAD

**Issue by 1337faye** [mrdoob/three.js#24956]
Using controls.autoRotateSpeed in object controls creates automatic rotation but is tied to the client framerate, for example on chrome on a PC connected to a 120hz monitor, the auto rotate speed is double the speed of the same scene being rendered on a computer connected to a 60hz monitor.

A clear and concise description of what the bug is. Before submitting, please remove unnecessary sections.

**To Reproduce**

1. Import object controls
2. Enable autorotate [ controls.autoRotate = true; ] 
3. Test the scene at two different refresh rates, the auto rotate speed will change depending on the refresh rate of the host computer.
4. (Make sure to use chrome, firefox caps the framerate  by default)

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/eL7gqyhd/)

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome]
 - Three.js version: [Latest]

**Comment by marcofugaro** [comment]
You can make it framerate independant using the [Clock](https://threejs.org/docs/index.html#api/en/core/Clock):

```js
const speed = 100
controls.autoRotateSpeed = speed * clock.getDelta()
```

**Comment by 1337faye** [comment]
Thanks, you should maybe update the documentation to make it more obvious that it's FPS dependent by default.
Also, what do I import to make this work?

**Comment by looeee** [comment]
> you should maybe update the documentation to make it more obvious that it's FPS dependent by default.

@1337faye the docs are open source, you can click the edit button on any docs page to open a pull request. Would you like to add it?

**Comment by 1337faye** [comment]
> 

Oh, I didn't notice.
I'll make a note to open a pull request later this afternoon.
