### ISSUE TITLE
Problem with GLFTLoader and buttons/links

### ISSUE THREAD

**Issue by itsgigi** [mrdoob/three.js#24969]
Hello, I have an issue I cannot solve. In My three js project I use the GLTFLoader in the script file loading some 3d models and some buttons in the html file. The problem is that my buttons completely stops working and I figured that as soon that I remove the import {GLTFLoader} ... from the script the models obviously disappears but the buttons stars working again. I tried various thing like importing the loader as a script in the html file, but then i get the error that GLTFLoader is not a constructor and try different path (local and external) for the import but nothing seems to work. Does anybody know how to help me?

 - Device: Desktop
 - OS: Windows
 - Browser: Edge
 - Three.js version: 0.146.0

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
