### ISSUE TITLE
FileLoader: Allow custom Content-Length header for file loader total value

### ISSUE THREAD

**Issue by mxsxs2** [mrdoob/three.js#24962]
**Is your feature request related to a problem? Please describe.**

Using Nginx's gzip feature removes the _Content-Length_ header that comes back from the server. This causes the _FileLoader_ to always report 0 as total for every progress event. Therefore, the [onProgress](https://github.com/mrdoob/three.js/blob/e1964f20e4f1d133b2ac0acaec722946af773102/src/loaders/FileLoader.js#L139) callback becomes somewhat useless. In my case it makes it impossible to track progress of loading an OBJ file with the [OBJLoader](https://threejs.org/docs/#examples/en/loaders/OBJLoader)

I know the following line is in the documentation. However, this does not help in my case.
_If the server does not set the Content-Length header; .total will be 0._

**Describe the solution you'd like**

It would be nice to add a secondary header like _X-Content-Length_ or _X-File-Size_ to be also accepted at https://github.com/mrdoob/three.js/blob/e1964f20e4f1d133b2ac0acaec722946af773102/src/loaders/FileLoader.js#L112

Like:
`const contentLength = response.headers.get( 'Content-Length' ) || response.headers.get( 'X-File-Size' );`

**Describe alternatives you've considered**

I am not sure if there is a simpler alternative to this. 

**Additional context**

**Comment by mrdoob** [comment]
I'm okay with adding it too as long as we add https://serverfault.com/questions/482875/why-does-nginx-remove-content-length-header-for-chunked-content as a comment around it.

**Comment by Mugen87** [comment]
@mxsxs2 Would you like to make a PR with your suggested change?

**Comment by mxsxs2** [comment]
@Mugen87 Ill open one today. Thanks!

**Comment by ycw** [comment]
should mention that unlike content-length, 'x-file-size' is not included in cors-safelisted, servers have to include it in `access-allow-expose-headers` for cross-origin reqs, otherwise, its inaccessible in script.
