### ISSUE TITLE
WebComponent ThreeJS

### ISSUE THREAD

**Issue by richardanaya** [mrdoob/three.js#24980]
Would you all be receptive to me adding a section in examples to use WebComponents to build a one to one ThreeJS scene graph?

* will only use vanilla webcomponents only
* follows ThreeJS entities hierarchy (scene, object, etc.) strictly

Inspiration from libraries like react three fiber and a frame indicate to me building ThreeJS with a declarative model could be useful to other people.

**Comment by ycw** [comment]
> will only use vanilla webcomponents only

I admire you for your bravery!

**Comment by Mugen87** [comment]
To me, this is out of scope. Something like this should be managed in separate repositories.

**Comment by donmccurdy** [comment]
We do have the _Wrappers and Frameworks_ section in the [Libraries and Plugins](https://threejs.org/docs/#manual/en/introduction/Libraries-and-Plugins) page, and can always add new things there. A-Frame is an example of the Web Component approach. Perhaps counterintuitively, I think the overhead (in both performance and maintenance cost) is higher than with the approaches taken by [`@react-three/fiber`](https://github.com/pmndrs/react-three-fiber) or [threlte](https://threlte.xyz/).

As for explaining how to "build your own framework" with Web Components, I think it'd be an interesting case study (blog post, github project, etc.) but would agree it probably isn't something we should maintain within the three.js project.

**Comment by richardanaya** [comment]
Thanks for the consideration!

**Comment by mrdoob** [comment]
https://github.com/hmans/three-elements
