### ISSUE TITLE
Instanced meshes where some instances are negatively scaled while others are positively scaled.

### ISSUE THREAD

**Issue by sezze** [mrdoob/three.js#24998]
**Is your feature request related to a problem? Please describe.**

A previous pull request fixed the flipping of faces with negative scales on meshes: [(WIP: Support negative scale factors #12720)](https://github.com/mrdoob/three.js/pull/12720).

This however does not work for _instanced meshes_ where some instances have negative scale factors while others have positive ones. I also do not know of a way to calculate it manually when the geometry can't be updated (as not all instances will be scaled negatively).

**Describe the solution you'd like**

A way of negatively scaling some instances in an instanced mesh, while keeping some instances positively scaled.

**Describe alternatives you've considered**

Creating two instanced meshes, one for flipped meshes and one for non-flipped. This however gets tricky to manage if the user wants to update matrices and therefore move them between the two instanced meshes.

**Comment by WestLangley** [comment]
Support for reflections in the world transform was added in #12787. It is implemented by toggling the front-face winding order.

I think you will have to handle your use case at the app level...

**Comment by Mugen87** [comment]
Also consider to solve your use case without any kind of negative (non-uniform) scale if possible. Depending on what you are doing in your app, the consequences of such a setup can be really problematic and hard to solve.
