### ISSUE TITLE
Objects with alphaClip render opaque shadows when `map` is used instead of `alphaMap`

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#24995]
**Describe the bug**

Seems that while https://github.com/mrdoob/three.js/pull/22410 added support for alpha clipping in shadow maps, it did so only when `alphaMap` is used, not then the alpha channel of `map` is used for transparency. 
This results in, for example, all glTF files loaded at runtime (e.g. with GLTFLoader) not supporting alpha clipping in shadows.

I've seen a few mentions of using `customDepthMaterial` to work around this issue, but in fact this part of the docs was removed when #22410 was merged. Thus I think the missing case for map + clipping may be an oversight / bug here.

**To Reproduce**

1. Go to https://threejs.org/editor
2. Add a cube using "map" with alpha channel and a cube with "alphaMap"
3. Add a Directional Light
4. Add a floor plane
5. Enable Cast shadows on the light
6. Enable Cast+Receive Shadows on the cubes and the plane
7. Note that alpha clipping happens on the object but not on the shadows

**Expected behavior**

Alpha clipping in the shadows.

**Screenshots**

![image](https://user-images.githubusercontent.com/2693840/203051737-e61fa9d1-fe07-4b4d-9ae4-293beb8791ce.png)

**Comment by WestLangley** [comment]
Confirmed. A custom depth material is still required if a `map` with alpha channel is used instead of `alphaMap`.
