### ISSUE TITLE
Can't import Earcut. Keep getting undefined

### ISSUE THREAD

**Issue by below-1** [mrdoob/three.js#24997]
**Describe the bug**

I can't import the Earcut object from 'three'. After closer inspection seems like the Earcut is not re-exported from Three.js.  

**To Reproduce**

1. Set Next.js with Three.js and R3F
2. import Earcut
3. Log the Earcut object. Getting undefined

***Code***

```js
// code goes here
import { 
  Earcut
} from "three";

console.log(Earcut);
// Got undefined
```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/eL7gqyhd/)

**Expected behavior**

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: [Desktop]
 - OS: [Linux]
 - Browser: [Edge]
 - Three.js version: [r144]

**Comment by Mugen87** [comment]
`THREE.Earcut` is not exported since it is meant to be internal. Use `ShapeUtils.triangulateShape()` if you want to use it for triangulation.
