### ISSUE TITLE
`Material.setValues()` does not work properly with `._listeners` and `.alphaTest`

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#25004]
**Describe the bug**
`Material.setValues( values )` function does not work properly with `._listeners` and `.alphaTest` properties if `values` is a material - it produces a warning on the first one (if there is a listener on `values`) and does not copy the second (because it is not enumerable in a `for-in` loop).

**Expected behavior**
Either `_listeners` property should be ignored and no warning should be produced and `alphaTest` should be succesfully copied or it should be explicitly noted that `Material.setValues` does not accept materials, only plain objects.

**Comment by Mugen87** [comment]
The intended usage of `Material.setValues()` is with `parameter` objects. Using a material object (or any other kind of specific type) is not valid.
