### ISSUE TITLE
SpotLightHelper confused by scene.rotateX(-Math.PI/2)

### ISSUE THREAD

**Issue by jackpunt** [mrdoob/three.js#25005]
**Describe the bug**

When the scene is rotated, the SpotLightHelper is confused, shows wrong position & projection lines.

**To Reproduce**

1. create scene with SpotLight & SpotLightHelper: a PlaneGeometry, extent is [X,Y]; normal to Z
2. Observe SpotLightHelper works fine; [although OrbitControls will no rotate plane around Z-axis...]
3. apply: scene.rotateX(-Math.pi)  // so OrbitControls can spin around Z-axis
4. Observe that SpotLightHelper shows the wrong location and projections.

***Code***

```js
// code goes here:
   scene.rotateX(Math.PI/2); // in the fiddle @ line 117
```

***Live example***

https://jsfiddle.net/4azo5bvf/64/

**Expected behavior**

Ideally, the scene would rotate and SLH would "just work as before".
Sadly, given other Issues regarding SpotLightHelper, we can't really *expect* SHL to "work" correctly...
But get it on the record for others who trip across this.

Assuming the technology cannot be fixed, it would be helpful to have documentation:
  It would be nice to an explanation of what are the expectations & constraints when using SHL.

(also: some explanation/constraints regarding OrbitControls... is there an alternative way to spin around Z-axis of a plane.
 sure, one could re-orient the plane; i was hoping to keep "z is up from the plane" because that is so obvious.
 also: is there a API? so I could preset the Azimuth to PI/2 ?
 asking on [stackoverflow](https://stackoverflow.com/questions/74540702/how-to-make-three-orbitcontrols-spin-a-plane-around-z-axis-x-axis))

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: r146

**Comment by WestLangley** [comment]
This question was resolved on StackOverflow.
