### ISSUE TITLE
Cannot check for Object3D inheritance

### ISSUE THREAD

**Issue by ANFADEV** [mrdoob/three.js#25008]
**Describe the bug**

A simple check to know if an object is an instance of a parent class, doesn't work
`THREE.Mesh instanceof THREE.Object3D` returns false, while Mesh extends Object3D

This is counter-intuitive, and counter-productive not only when using OOP, but also when a programmer simply wants to extend Object3D in his own ecosystem

**To Reproduce**

1. Go to a threejs playground, like: https://codesandbox.io/s/threejs-playground-gorrl
2. add `console.log(THREE.Mesh instanceof THREE.Object3D)` as the last line
4. See in the console it returns `false`

***Code***

```js
console.log(THREE.Mesh instanceof THREE.Object3D)
```

***Live example***

* https://codesandbox.io/s/three-js-playground-forked-8ivmt3

**Expected behavior**

return `true`

**Screenshots**

![image](https://user-images.githubusercontent.com/32341740/203747981-d4e2c536-51ee-4b5f-8e46-c6ba22e3ff77.png)

**Platform:**

 - Device: [ All ]
 - OS: [ Windows (should be All ) ]
 - Browser: [ Chrome, Firefox, Edge ]
 - Three.js version: [ All ]

**Comment by Mugen87** [comment]
Try it like so: https://jsfiddle.net/sn5984a3/

**Comment by Mugen87** [comment]
Also consider to do this: `console.log(mesh.isObject3D);`.

**Comment by Mugen87** [comment]
Sorry, we are not going to accommodate the code to TS related issues.

**Comment by ANFADEV** [comment]
Well in the end it's not really an issue, nor its only relates to TS, it's only for consistency
but ok, at least i have isObject3D()

**Comment by ANFADEV** [comment]
Also i noticed there are missing tests for inheritance:
![image](https://user-images.githubusercontent.com/32341740/203814358-aeac7136-8cb9-4ecf-94d2-f9b0fc49aa05.png)
is this related? because i was implementing them to test with `instanceof`

**Comment by Mugen87** [comment]
Yeah, the unit tests are not fully implemented. Feel free to implement missing ones like the inheritance check if you like.

**Comment by ANFADEV** [comment]
Ok going to PR what i did
