### ISSUE TITLE
GLTF exporter doesn't correctly handle normalized attributes

### ISSUE THREAD

**Issue by skillbert** [mrdoob/three.js#25019]
**Describe the bug**

The GLTF exporter currently exports normalized attributes as their 0-1 float value instead of their 0-255 integer values. This affects the attribute buffers themselves as well as the gltf sampler min and max fields.

This probably broke because of c6a80f9bb8411575a50990e35b9a169c8d409b41

**To Reproduce**

1. Use the gltf exporter to download a model (for example the [fiddle](https://jsfiddle.net/7abpk50j/56/))
2. Load the model file into a validator like https://gltf-viewer.donmccurdy.com/
3. Click errors on the bottom left to view the errors

***Code***

```js
import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter';

function exportModel(node){
    let exporter = new GLTFExporter();
    exporter.parse(node, gltf => resolve(gltf), reject, {
  	binary: true
    });
}
```

***Live example***
https://jsfiddle.net/7abpk50j/56/
click download and then load the file into https://gltf-viewer.donmccurdy.com/

**Expected behavior**

The model including the vertex colors load correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/7593843/204064229-92a3cd75-fb54-49ab-be7e-9baf6f7fdc96.png)
**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: r146

**Comment by donmccurdy** [comment]
Thanks @skillbert! To be fixed in:

- https://github.com/mrdoob/three.js/pull/25076
