### ISSUE TITLE
Ability to control `texture.anisotropy` from `GLTFLoader`

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#25010]
**Is your feature request related to a problem? Please describe.**

We were often wondering why textures in three.js looked more blurry than in other engines. See for example the files in https://github.com/google/model-viewer/issues/1505. Turns out that while generally texture anisotropy can be set, GLTFLoader currently doesn't expose a way to control it, so glTF viewers generally look "kind of blurry" from steep angles.  
 
I'm happy to work on a PR for this but would like to align on possible solutions first.  

The renderer has `renderer.capabilities.getMaxAnisotropy` which contains the maximum allowed anisotropy, but I think being able to pass in an override for this into the loader would be nice instead of just setting the max (and there's currently no access to the renderer as far as I can see, minus spawning a new one).  

Currently I'm just adding `texture.anisotropy = 4;` in GLTFLoader.loadTextureImage so that it applies to textures loaded via extensions as well.

**Describe the solution you'd like**

Some way to override texture anisotropy as used by GLTFLoader.  

**Describe alternatives you've considered**

- Adding some texture loading extension. Complexity would be that this would still need to work with all other texture loading extensions, so not entirely sure how that would work.  

- Iterating over all materials and all textures in the glTF file and setting anisotropy there. Harder than it should be in my opinion but maybe I'm missing a convenient way to do that.

If there's a good way to set this without changing GLTFLoader I'm all ears :)

**Comment by donmccurdy** [comment]
> 

I believe this is possible, but I'm not sure exactly what hooks would need to run in what order. This would take some testing to confirm, or @takahirox may know. 

The easiest option might be:

```javascript
const { scene, parser } = new GLTFLoader().loadAsync( 'path/to/scene.glb' );

for (const texture of await parser.getDependencies( 'texture' )) {

  texture.anisotropy = 4;

}
```

I believe that should work in the general case, returning one texture for each `.textures` entry in the glTF file. However it fails when `KHR_texture_transform` is used, as this clones and generates additional variants of those textures.

The `parser.associations` Map is supposed to have all textures in it, too. It currently misses those created by `KHR_texture_transform` as well but that is something we could fix.

**Comment by takahirox** [comment]
I think other loaders have the same problem, don't they? If so, it may be good if we have a solution that is not `GLTFLoader` specific.

A solution I first came up with is adding `Texture.DefaultAnisotropy` static property similar to [Object3D.DefaultUp and Object3D.DefaultMatrixAutoUpdate](https://threejs.org/docs/#api/en/core/Object3D.DefaultUp) if it's ok to add a new static property. (I assume the same anisotropy value is used for (almost) all textures in an application. Let me know if this assumption is wrong.)

Another easy solution that can be done on user end is, (it may be inefficient but) traversing scene, material, textures after loading glTF.

```
const loader = new GLTFLoader();
const scene = await loader.loadAsync('path/to/scene.glb');

scene.traverse(object => {
  if (object.material) {
    const material = object.material;
    for (const key in material) {
      if (material[key] && material[key].isTexture) {
        material[key].anisotropy = 4;
      }
    }
  }
});
```

**Comment by hybridherbst** [comment]
Thanks for the comments! 
Sounds like the global may be the most useful solution here. Typically most textures do indeed have the same aniso value in an app.

Agree that it would be great if there's a regular way to get all textures that were loaded independent of extension; would you consider it a bug that `associations` / `getDependency` contain the wrong texture for `texture_transform` cases?

Iterating over material keys sounds doable but rather slow, plus there may be another fancy case: we have an extension that sets up custom shaders during loading, so theoretically one needs to traverse uniforms as well to really find all textures that way.

**Comment by donmccurdy** [comment]
> would you consider it a bug that associations / getDependency contain the wrong texture for texture_transform cases?

For `getDependency` no (it's intended to return source textures in the file, not all variants cloned while parsing), but for `associations` yes.

I'm happy with the default idea suggested by @takahirox and @WestLangley  as well. (https://github.com/mrdoob/three.js/pull/25015)
