### ISSUE TITLE
Default background for transmissive objects

### ISSUE THREAD

**Issue by deenns** [mrdoob/three.js#25016]
**Problem**

An object with `MeshPhysicalMaterial` and transmission props (`transmission`,  `attenuationColor`, `attenuationDistance`, `thickness`) needs an opaque background to be normally rendered. With a transparent background (and no other opaque objects behind it) it's either invisible or completely transparent, even if it has `attenuationColor` and `thickness`. 

The same problem is [described here.](https://discourse.threejs.org/t/transmission-and-transparent-canvas-workaround/29395)

**Desirable solution**

It would be nice to have something like a `transmissionBackground` prop in the Scene object, that wouldn't be rendered as a normal background, but would be used as a default background for all transmissive objects. 

**Alternatives**

A default background color for transmissive objects (but a texture is preferable of course).

**Additional context**

It seems to be possible. 

If you replace [this line](https://github.com/mrdoob/three.js/blob/146bc1893fd1f8cd4fefeb918977a479752a23c6/src/renderers/WebGLRenderer.js#L1218)

```js
if ( opaqueObjects.length > 0 ) renderObjects( opaqueObjects, scene, camera );
```

with 

```js
const filteredObjects = opaqueObjects.filter( obj => ! obj.material?.name?.startsWith( 'Background' ) );
if ( filteredObjects.length > 0 ) renderObjects( filteredObjects, scene, camera );
```
Then the scene background will not be rendered, but it will still be used for transmissive objects.

Instead of this: 

![with_background](https://user-images.githubusercontent.com/96049300/203970358-bd1d67d8-37f7-405d-9c74-5c6adeca43dc.png)

You will get this: 

![without_background](https://user-images.githubusercontent.com/96049300/203970456-98f3faf3-b340-4894-8724-9d23b74eceaa.png)

**Comment by Mugen87** [comment]
Rendering certain effects with transparent canvas can not always be properly supported (e.g. bloom see #14104). I would recommend to not add a solution for this use case but avoid transparent canvases whenever possible (and define an opqaue background instead). Especially if the app wants to render effects requiring transparency.

**Comment by donmccurdy** [comment]
Aside — there may be future properties on THREE.MeshPhysicalMaterial that require the same render target used by transmission. Translucency ("diffuse transmission") and subsurface scattering would be likely possibilities. If we added such a property its name may need to be more general.
