### ISSUE TITLE
Make exporters work with uninitialized textures (`image=null`). 

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#25020]
**Describe the bug**

GLTFExporter currently assumes that all textures have image data; 
https://github.com/mrdoob/three.js/blob/46fb35af1fb86fb014bf1271c7452c113024420b/examples/jsm/exporters/GLTFExporter.js#L1088-L1089

This fails when any Texture is passed in that doesn't have image data (e.g. `new Texture()`) because it causes an exception on export instead of exporting "no texture" for that slot.

The same happens in USDZExporter and probably also in ColladaExporter; not sure if there are others.

**Expected behavior**

File can be exported and texture slot stays unassigned.

**Screenshots**

![image](https://user-images.githubusercontent.com/2693840/204066717-aacb991e-8221-41b2-85bd-b9c36e07e0ab.png)

**Comment by donmccurdy** [comment]
This does not necessarily sound like a bug to me, could you say more about why you expect the behavior you describe?

At the minimum I think a warning must be logged here; an exception also doesn't sound unreasonable.

**Comment by Mugen87** [comment]
Textures with no image data are a bit special. The renderer does no complain if you assign `new Texture()` to a map property, however, the shader will sample from an empty definition resulting in 0 values (or black color). Example: https://jsfiddle.net/sct9anv8/

I would also like to know how (and why) an app produces assets with empty texture data.

**Comment by hybridherbst** [comment]
At least the FBXLoader produces such files (it creates Textures and loads them async after returning) - I think if any loader can bring that kind of data in, it's safe to assume that someone will try exporting it again. This is exactly how I stumbled upon this issue. Visually everything looked correct.

When loading such a file with FBXLoader, an error is already logged on image loading, and since users could assign empty textures anyway I thought it's better to guard against the result.

Other options here would be:
- Fixing FBXImporter (only solves it for that case)
- Forcing people to manually sanitize after every loader (not great)

**Comment by LeviPesin** [comment]
> The renderer does no complain if you assign new Texture() to a map property, however, the shader will sample from an empty definition resulting in 0 values (or black color). In most cases this visually breaks the material. Example: https://jsfiddle.net/sct9anv8/

But doesn't this change if `Texture.DEFAULT_IMAGE` is used?

**Comment by Mugen87** [comment]
Of course you can add an image to `Texture.DEFAULT_IMAGE` but the question is if assets look good with it. And if you want these default data in your exports.

> Fixing FBXImporter (only solves it for that case)

If you use `LoadingManager` in combination with `FBXLoader`, you can wait until all resources have loaded and don't run into this issue. There is some sort of silent agreement in the past to not update existing loaders to behave like `GLTFLoader` and `ObjectLoader`. These two loaders are the only one which wait until all resources have been load. 

I suggest you use `LoadingManager` on app level and you won't have any issues with empty texture data.

**Comment by Mugen87** [comment]
Related issue: #12105

**Comment by hybridherbst** [comment]
> This is how the library is supposed to be used.
You mean it's by design that these loaders work differently and require different patterns to be used? I thought one goal of the library was to have easy and consistent patterns 🧐

I'll look into the manager approach, thanks. 

Still think it's weird that it's so easy to break exporters and other code (with any kind of code validation, this would need to be checked too - the Texture type simply doesn't have image as field). Independent of what other loaders do I think this check makes sense.

**Comment by Mugen87** [comment]
As @donmccurdy suggested, some sort of check does not hurt. I suggest to log a warning and then ignore the respective texture slot.

**Comment by Mugen87** [comment]
> You mean it's by design that these loaders work differently and require different patterns to be used? I thought one goal of the library was to have easy and consistent patterns 🧐

The loaders evolved over twelve years now and some users rely on the existing behavior of `FBXLoader`, `ColladaLoader` or `OBJ/MTLLoader`. Meaning that they display data as fast as possible, even when no texture data are available yet. `LoadingManager` allows us to support the old way but provides a solution for devs who want to wait until all loaders are done with their work.

**Comment by hybridherbst** [comment]
I'll take a look if I can add that to #25021!

Just to clarify, the issue is not the loading order but that the resulting textures don't have image data. Just using the loading manager doesn't solve that, right? But it gives an opportunity to sanitize data after loading I guess.

**Comment by Mugen87** [comment]
> Just using the loading manager doesn't solve that, right?

If you access the asset in `LoadingManager.onLoad()`, all texture data should be loaded. Of course you have the opportunity to sanitize at that point, too, if required.

**Comment by hybridherbst** [comment]
Sorry, should have clarified: the issue with the textures is similar to what's described in https://github.com/mrdoob/three.js/pull/25014#issuecomment-1328013700. In some cases textures fail to load, are corrupt, etc., in which case the textures returned from FBXLoader have missing image data (they start with missing image data and it's never filled with anything). These in turn cause exceptions in other exporters.

Here's an example file: [Low Poly-1.0.0.zip](https://github.com/mrdoob/three.js/files/10096048/Low.Poly-1.0.0.zip)

I can open a separate issue about "FBXLoader: loaded textures can be empty" if you want, but I don't have an immediate idea on how to fix that in there.

**Comment by donmccurdy** [comment]
> These two loaders are the only ones which wait until all resources have been loaded.

I think if maintainer(s) of any particular loader wanted to update it to await all resources before returning, that would be great. But if the handful of core maintainers were also responsible for making updates like these to all of three.js' loaders, we'd be able to maintain only a small fraction of the loaders three.js currently has.
