### ISSUE TITLE
Unable to load `canvasTexture` synchronously : Texture marked for update but no image data found

### ISSUE THREAD

**Issue by MeRahulAhire** [mrdoob/three.js#25024]
Came here from React-three-fiber from the [conversation](https://github.com/pmndrs/react-three-fiber/discussions/2638#discussioncomment-4243497) with @drcmda. 
I'm actually trying to use [openlayers](https://github.com/openlayers/openlayers)'s canvas as a `canvasTexture` to my gltf object. 

But the problem is since the image is 5MB in size it's taking some time to get loaded in canvas and since the `textureLoader` in Three.js is asynchronous its giving me this error.
```bash
THREE.WebGLRenderer: Texture marked for update but no image data found.
```  
The question is since my `canvasTexture` is dynamic by nature as its changing constantly, Threejs has no way to figure out what happening inside of the canvas so that it can rectify itself. So how do I solve this problem @mrdoob?

Code example : 
```js
const mapContainer = document.getElementById("map");
      const mapCanvas = useRef(mapContainer.getElementsByTagName("canvas")[0]);
      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    
      if (mapCanvas.current) {
        mapCanvas.current.needsUpdate = true;
      }
```
```js
         <mesh
            name="Sphere"
            castShadow
            receiveShadow
            geometry={nodes.Sphere.geometry}
          >
            <meshStandardMaterial>
              <canvasTexture
                ref={textureRef}
                attach="map"
                image={mapCanvas.current}
                flipY={false}
              />
            </meshStandardMaterial>
          </mesh>
```

**Comment by donmccurdy** [comment]
Sorry, we reserve github issues for topics related to development of the library. 

Please use these options for help requests:

- [questions](https://stackoverflow.com/questions/tagged/three.js)
- [discord](https://discord.gg/56GBJwAnUS)
- [forum](https://discourse.threejs.org/)
