### ISSUE TITLE
Tranform controls rotate mode helper guide lines appears at incorrect location

### ISSUE THREAD

**Issue by optimus007** [mrdoob/three.js#25063]
**Describe the bug**
(better explained in the screenshots)
While using transform controls , in translate and rotate mode the white helper lines appears/intersects at the transformControls.position

in rotate mode this helper lines appears wherever  the last translate or rotate happened 
Functionality is not affected , this is just a minor visual bug

**To Reproduce**

1. Go to [misc_controls_transform ](https://threejs.org/examples/?q=transf#misc_controls_transform)
2. Click on box
3. Move it to the side
4. set mode to rotate 
5. hover on the axis to see the lines appear at origin/incorrect location

**Expected behavior**
Just like translate and rotate the lines should intersect at trasformcontrols.position

**Screenshots**
Translate Correct:
![translate](https://user-images.githubusercontent.com/6885294/205318503-dcceda89-23fe-480a-945f-a9fd48f1551c.png)
Scale Correct:
![scale](https://user-images.githubusercontent.com/6885294/205318549-7b875bbe-cd57-4e55-8000-1e72f294d14d.png)
Rotate Incorrect:
![rotate](https://user-images.githubusercontent.com/6885294/205318603-5f64ece6-e6b7-4a0c-9d00-4cdf8e159924.png)
![tcon](https://user-images.githubusercontent.com/6885294/205318632-0e8caf77-e771-4dc0-a0ce-6b46d6d2eaa2.png)
**Platform:**

 - Device: [Desktop ]
 - OS: [Windows]
 - Browser: [Chrome,]
 - Three.js version: [ r147]

**Comment by Mugen87** [comment]
Can you please check if removing the following line solves the issue?

https://github.com/mrdoob/three.js/blob/d7b1ca7446ee21f1e1e3e5f15536e53c97a371dd/examples/jsm/controls/TransformControls.js#L1200

**Comment by optimus007** [comment]
Yes , commenting that line fixes the issue
![fixtest](https://user-images.githubusercontent.com/6885294/205506706-96aa9459-2639-42c2-ac76-52bac4553c76.png)
