### ISSUE TITLE
BufferGeometry.calculateBoundingSphere fails due to NaN values

### ISSUE THREAD

**Issue by Bangybug** [mrdoob/three.js#25069]
**Describe the bug**
		
BufferAttribute.js has this line:
this.count = array !== undefined ? array.length / itemSize : 0;

Under some circumstances, especially on large meshes, in my case array.length was 321544.  And thus the count can be set to 107181.333 due to floating point errors. 

That has brought me other issues, BufferGeometry.calculateBoundingSphere failed to calculate bounding sphere due to NaN values.

**Inplace fix**

```
    const vbVertices = new Float32BufferAttribute(vertices, 3)
    vbVertices.count = Math.floor( vertices.length / 3 )
    geometry.setAttribute('position', vbVertices)
```

**Platform:**

 - Device: Desktop
 - OS: MacOS
 - Browser: Chrome
 - Three.js version: 141

**Comment by Mugen87** [comment]
Having `NaN` values in buffer data is invalid input. You have to ensure on app level your geometry data are sanitized.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you have more questions about that topic.

**Comment by WestLangley** [comment]
>Having NaN values in buffer data is invalid input.

@Mugen87 Perhaps you misread the post? I think the issue is that the OP's attribute buffer is oversized.

I am not sure the docs are clear on that issue...

**Comment by Bangybug** [comment]
@WestLangley  I'm sorry, perhaps I wasn't too clear. The root cause is the floating point math errors.  I moved to the forum https://discourse.threejs.org/t/buffergeometry-calculateboundingsphere-fails-due-to-nan-values/45439

**Comment by Mugen87** [comment]
Let's continue the discussion at the forum 👍 .

**Comment by mrdoob** [comment]
Hmm, maybe we can do a simple check for the user here and log a warning?
