### ISSUE TITLE
Method `dispose()` not available for SelectionHelper but implemented

### ISSUE THREAD

**Issue by autonomobil** [mrdoob/three.js#25090]
**Describe the bug**

Method `dispose()` not available for SelectionHelper but it's implemented

**To Reproduce**

1. Use https://github.com/mrdoob/three.js/blob/dev/examples/misc_boxselection.html as baseline
2. Try to "delete"/"deactivate" box selection (e.g. having a box selection mode, but this should be toggle-able), by
     a. `helper = null;`
     b. `delete helper;` 
3. Deactivates the selection itself but not the SelectionHelper element, this is probably because the EventListeners are not removed and html elements is created again (`dispose() is not called`)

***Code***
I would expect `SelectionHelper.d.ts` to have method:
```js
dispose(): void;
```

***Live example***

* https://jsfiddle.net/bL3efku9/14/  - hit b to switch between modes

**Expected behavior**

`dispose()` function is implemented [here](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/interactive/SelectionHelper.js#L49) but not available in `SelectionHelper.d.ts`

If `dispose()` is manually added to SelectionHelper.d.ts it works as intended.

**Screenshots**
 `SelectionHelper.d.ts` (r147) :
![Screenshot from 2022-12-06 20-35-37](https://user-images.githubusercontent.com/31781343/206005918-8857a27a-9946-4379-9bad-edc787d05a45.png)

expected:
![image](https://user-images.githubusercontent.com/31781343/206026765-08c65f31-4f8b-491b-89f3-90fb6735e2bf.png)

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [r147]

**Comment by Mugen87** [comment]
TS declaration files are maintained here: https://github.com/three-types/three-ts-types

The code in your fiddle is not entirely correct. `dispose()` is not called automatically, it has to be called by the user on application level. Since your fiddle does not call the method, the internal event listeners of the selection helper aren't removed.

**Comment by autonomobil** [comment]
But that's the point, you can't call it. If you use `selectionBox.dispose();` you get an error
```
"<a class='gotoLine' href='#67:22'>67:22</a> TypeError: selectionBox.dispose is not a function"
```
see updated fiddle: https://jsfiddle.net/bc8pq7a3/2/

**Comment by Mugen87** [comment]
You call `dispose()` on the instance of `SelectionBox`. Try it with the instance of `SelectionHelper`.

https://jsfiddle.net/q69gtase/

**Comment by autonomobil** [comment]
Ah you're right, it works in the fiddle now. But in a typescript/angular environment I'm getting the error 
![image](https://user-images.githubusercontent.com/31781343/206180878-35e3fbc2-244d-4c0a-9fb2-89afa3b85ee3.png)


Also compiling error:
```

Error: ....ts:98:28 - error TS2339: Property 'dispose' does not exist on type 'SelectionHelper'.

98       this.selectBoxHelper.dispose();
                              ~~~~~~~
```

Can it be fixed by this? https://github.com/three-types/three-ts-types/pull/292

**Comment by Mugen87** [comment]
The fix looks right to me.
