### ISSUE TITLE
Decide whether class fields can be used in core

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#25105]
Related:
https://github.com/mrdoob/three.js/issues/23480
https://github.com/mrdoob/three.js/pull/24237
https://github.com/mrdoob/three.js/pull/25104

**Is your feature request related to a problem? Please describe.**

We should decide whether class fields (public, private, and static) could be currently used in core or is it still too soon.

**Describe the solution you'd like**

I personally support using class fields, because they will allow us to shoot three birds with one arrow - we would be able to use static fields for properties like in animation and interpolant (I think?) classes, private fields for properties like `Material.#alphaTest`, and public fields for finally solving the .isClass problem - public fields work best because they do not create a boolean for all instances, IIRC.

**Comment by mrdoob** [comment]
We're giving it a try: https://github.com/mrdoob/three.js/pull/24237#issuecomment-1360760530

**Comment by Mugen87** [comment]
This can be closed since he have decided to stick to ES2018 for now.
