### ISSUE TITLE
Potential improvement of "real-world" performance of updateMatrixWorld() 

### ISSUE THREAD

**Issue by diarmidmackenzie** [mrdoob/three.js#25115]
**Is your feature request related to a problem? Please describe.**

When analyzing peformance of applications built using THREE.js, I often find the per-frame call to updateMatrixWorld() to be a key bottleneck.

I've been looking at the updateMatrixWorld() Benchmark tests at /test/benchmark/benchmarks.html

On my system, this test shows ~250 ops/second for the large graph (depth=9, breadth=3), 29524 nodes.

That suggests that at 50fps, updateMatrixWorld for ~30k nodes should be taking ~20% of my CPU.

My experience is that real-world performance is nothing like as good as this.

For example, a recent scene I was looking at had 18k nodes, and 41.6% of CPU spent in updateMatrixWorld().  That's about 1/3rd of the performance shown by that benchmark.

I've been looking at possible reasons for this, and I believe I have found a significant factor in real-world performance, which is:
- not accounted for in the Benchmark test
- could potentially be addressed with some code changes (I have a prototype that shows a ~50% gain in "real world" conditions).

That specific factor is the topic of this issue

**More detail.**

The current Benchmark tests create a homegeneous scene graph, consisting entirely of vanilla Object3Ds.  That's not realistic: most real-world scene graphs will consist of a range of different sub-classes of Object3D: Groups, Meshes, SkinnedMeshes, InstancedMeshes etc.

This matters because the dynamic nature of JavaScript objects means that performance for access to object properties can be highly variable.  I'm by no means an expert on this, but I have found [this article](https://javascript.plainenglish.io/exploration-of-javascript-object-for-performance-optimization-70b20246ab9e) to be a good primer on the topic.

Under PR #25113, I've added an additional benchmark test with a slight modification.  Instead of creating a homogeneuous population of vanilla Object3Ds, it creates a randomized blend with:
- 5% InstancedMeshes
- 5% SkinnedMeshes
- 50% Meshes
- 40% Groups

I don't make any claims that this is the "correct" mix for a "real-world" benchmark, but I think it is extremely notable that when run with this mix, the benchmark performance drops (on my system) from about 250 ops/second to around 125 ops/second - i.e. drops by ~50% (I'm rounding these numbers because in my experience the values output by these tests vary by +/-10% from one run to the next, regardless of the +/- figure reported by the benchmark tool)

![image](https://user-images.githubusercontent.com/16045703/206909092-fc411781-ff2c-4cc0-90c2-41fd6c09fa69.png)

I think this is significant, both for estimating absolute performance of Three.js, and also for assessing gains from fixes in this area - with the current Benchmarks, there is a risk of taking fixes that improve homogeneous performance, but actually make real-world performance worse.

**Why the big difference?**

My understanding (based on the article linked above) is that this is likely to be mostly due to performance reductions when accessing Object3D properties.  To access these properties, the JS engine has to look up a "hidden class" in order to determine the property offsets.  When the object population is homogeneous (or "monomorphic"), this lookup can be cached, and the cache will be hit 100% of the time.  When the object population is heterogeneous (or "polymorphic"), this leads to cache missed, and a significant performance impact.

I think the heterogeneous/polymorphic object population is very probably more representative of "real world" performance than the homogeneous/monomorphic polulation used in the current Benchmark.

Regardless of whether we make any improvements to THREE.js itself, I think it's worth adding a more realistic benchmark here.  I don't claim that the profile offered in #25113 is perfect (I'm sure it's strongly biased to the way I tend to use THREE.js), and would be happy to iterate on the "correct" blend of objects to represent real-world usage under that PR.

**Can we fix this?**

Based on my understanding of the performance difference, I believe we can make some significant improvements here.

I have created a draft PR #25114 that shows a prototype set of changes, that increases the performance of the new benchmark from ~120 ops/sec to ~180 ops/sec, while leaving the previous homogeneous benchmark unchanged at around 250 ops/sec (the slight reduction here seems to be well within the margin of error of these tests).

![image](https://user-images.githubusercontent.com/16045703/206909176-9b802f49-6358-45e3-9fd0-7a9c38dc3f25.png)

You can see the specific code changes in the PR, but in summary:
- I've created a new class Object3DMatrixData, which contains all the properties that needs to be accessed in updateMatrixWorld() - 2 x matrices, some flags, position, quaternion & scale.
- On creation, Object3D instantiates a new instance of Object3DMatrixData, and also sets up a number of properties, getters & setters to map through to these (so that Object3D's external interface is unchanged).
- The implementation of updateMatrixWorld is moved onto the Object3DMatrixData class, with the Object3D.updateMatrixWorld() method mapping through to this

**Why does this work?**

The theory is that this change means that when updateMatrixWorld() iterates through all the children in the scene graph, it will always iterate through a homogeneous/monomorphic set of objects, which are all instances of Object3DMatrixData.

This results in property offsets being accessible via a single hidden class, which will reliably be present in the cache.

The benefits are visible in the ~50% performance gain seen in the "real world" benchmark test.

I am disappointed that this change didn't bring this test up to parity with the homogeneous benchmark test.  I wish I understood this area well enough to imagine why that might be, but I'm not yet at that level... 

**Describe the solution you'd like**

I'd like to see the benchmark tests extended to cover more realistic heterogeneous mixes of Object3D classes.

I think the one test that I have created under #25113 shows the importance of realism in test cases.  I propose further discussion over exactly what the right mix to use for a "real world" benchmark test can occur within #25113.

I'd also like to explore the prospect of a fix along the lines of #25114, as I believe there is potential for a performance gain of around 50% on updateMatrixWorld(), without any major negative side effects.  However there may be downsides to the approach I've taken here that I've not fully considered.

Propose discussion of that should continue in #25114.  Decisions that we reach on the "real world" benchmark in #25113 could potentially have an impact on this, as different benchmark tests may give different indications of the performance gains from #25114 (e.g. if we reject #25113 and just stick with the current benchmarks, #25114 doesn't appear to deliver any benefit at all).

**Describe alternatives you've considered**

I am aware that updateMatrixWorld() performance has been a longrunning topic, dating back to at least 2015.  I've skimmed over a bunch of issues & PRs in this area, and I can see that there have been a lot of proposals in this area.

From what I can tell, most of the focus in this area has been on reducing the number of matrix updates that need to be performed.  I may have missed something but it appears that none of these discussions led to any changes actually being merged.
E.g. #21401, #14138

(only actual change I found in this area that was merged was #14044 which optimized matrix.compose).

There is a lot of cotent on this topic, and I may have missed something, but I've not seen any discussion looking at how to optimize the traversal the scene graph by engineering for monomorphic object access (which is what #25114 attempts to do, I believe with some success).

Therefore I think these changes would be orthogonal to (and additive to), any changes that might be made along the lines of #14138 (although it looks like there's no active work on that topic at the moment).

**Other info**

All testing referred to above has been done on Chrome on a Windows PC.  Testing on other browsers / platforms is absolutely something that's needed if we take this set of issues forwards.

**Comment by takahirox** [comment]
Hi, thanks for writing it up. I have been feeling that the matrices update in Three.js is slower than the expectation in applications. So the explanation makese sense to me.

I get the feeling that I want to hear comments from JavaScript engine teams. For example whether they are thinking of the optimization to reduce the cache miss.

**Comment by vincentfretin** [comment]
I found this twitter thread to be a really simple explanation of what monomorphism is and the implication on the performance, at least I understand it better now, so I wanted to share it here: https://twitter.com/mhevery/status/1622499229813047296

**Comment by donhatch** [comment]
@vincentfretin wrote:
> I found this twitter thread to be a really simple explanation of what monomorphism is and the implication on the performance, at least I understand it better now, so I wanted to share it here: https://twitter.com/mhevery/status/1622499229813047296

I can't access the twitter thread (maybe because reading threads now require logging in? and I don't have a twitter account).   But I found this deeper dive by the same author, which is public: https://www.builder.io/blog/monomorphic-javascript

**Comment by Mugen87** [comment]
Merging this into #21387.
