### ISSUE TITLE
Fetch Error: "https://raw.githubusercontent.com/mrdoob/three/.js/dev/examples/js/libs/draco/draco_wasm_wrapper.js" responded with 404:

### ISSUE THREAD

**Issue by Hartaj-Singh-Dev** [mrdoob/three.js#25111]
So, I was working on integrating a 3d modal in a CTF community website, after a few months, when I tried to update my website, I saw that the 3d modal was not loading on production, and then in the development environment it should be this error (Title), I am assuming this might be a bug in official code 

1. Go to https://www.hugsforbugs.tech/ or for code go to "https://github.com/Hartaj-Singh-Dev/Hugs4Bugs.tech" fork it and test it on your device
3. Run it in the dev environment with the latest version of three.js 0.147.0( according to yarn)
4. See the error

Here is the screenshot of Error in Dev environment
![Screenshot from 2022-12-11 14-46-04](https://user-images.githubusercontent.com/73570165/206895628-780daa8a-b2fc-40d7-80ef-ded7307cb50f.png)

**Platform:**

 - Device: [Desktop]
 - OS: [Ubuntu]
 - Browser: [brave]
 - Three.js version: [dev, v0.147.0]

**Comment by Mugen87** [comment]
`examples/js` has been removed as mentioned in the migration guide (see https://github.com/mrdoob/three.js/wiki/Migration-Guide). The lib files are not located in the `examples/jsm` directory.

https://raw.githack.com/mrdoob/three.js/dev/examples/jsm/libs/draco/draco_wasm_wrapper.js

**Comment by donmccurdy** [comment]
Additionally, it would be better to use a CDN with a versioned copy of the files you need. Unpkg or Skypack for example. The files linked here are for use by the threejs website, not as a stable host for third-party sites. Breaking changes will be the rule, not the exception, when pulling code from a URL that isn't pinned to a version like a CDN would be.
