### ISSUE TITLE
ESP32 Three.JS Project

### ISSUE THREAD

**Issue by Architom12** [mrdoob/three.js#25129]
I am a complete novice with three.js hoping for some help. I have used Random Nerd Tutorial’s guide to set up an ESP32 with an accelerometer which displays as a cube through three.js. https://randomnerdtutorials.com/esp32-mpu-6050-web-server/ I have got this to work on its own.

I now want to add my own 3d model from blender for which I have used sections of code from this tutorial https://www.youtube.com/watch?v=tsMHONmUkvI. I was able to display my model with the sample code from the tutorial alone but it doesn’t work when spliced into Random Nerd Tutorial’s code.

If anyone has a moment to look at where I have got to with the code from the link below it would be greatly appreciated.
https://github.com/Architom12/ESP32-THREE.JS

**Comment by gkjohnson** [comment]
Posting at the forum is the best place to ask for help:

https://discourse.threejs.org/

**Comment by Architom12** [comment]
My new account is on hold on the three is forum so no one can see my post

**Comment by Mugen87** [comment]
Your topic is now visible.

https://discourse.threejs.org/t/esp32-three-js-project/45745
