### ISSUE TITLE
ColladaLoader: load textures from filesystem and http

### ISSUE THREAD

**Issue by TheColorRed** [mrdoob/three.js#25138]
**Describe the bug**

I am using multiple loaders for a little game engine, and I am trying to use the `ColladaLoader`. They issue is that it is trying to load the images from localhost but the files are not stored on a server, they are loaded from file. The application loads files using a file system path:

```plain
C:\Path\To\Models\Female.dae
```

**To Reproduce**

***Code***

```js
new ColladaLoader().loadAsync('C:\Path\To\Models\Female.dae').then(obj => {
  // The object gets loaded, the textures do not.
});
```
![image](https://user-images.githubusercontent.com/1571806/207464591-b557aa16-ca52-4efc-9bfe-4d239855ca07.png)

**Expected Result**

Maybe the loader could be modified to use `createObjectURL` like the fbx loader:

https://github.com/mrdoob/three.js/blob/6db6dd18e91ad8df4b294c77bdd1d1da7d954e46/examples/jsm/loaders/FBXLoader.js#L333

Or maybe there could be a way to tell the loader where it can find files...

 - Device: Desktop Electron
 - OS: Windows
 - Browser: Chrome Electron
 - Three.js version: 1.47.0

**Comment by TheColorRed** [comment]
Looks like I can make my own asset server. Then just set the following values:

```typescript 
   loader.path = 'http://localhost:4201';
   loader.resourcePath = 'http://localhost:4201';
```

I think this might work.

**Comment by TheColorRed** [comment]
After some investigation, it looks like I might have been formatting the path incorrectly... It looks like it is loading local files

**Comment by ycw** [comment]
> Browser: Chrome Electron

try [resolve](https://nodejs.org/api/path.html#pathresolvepaths) the tex urls from relpath to abspath via [loading manager](https://threejs.org/docs/?q=collada#api/en/loaders/managers/LoadingManager.setURLModifier)

```js
new ColladaLoader( /* loading manager */ )
```

**Comment by gkjohnson** [comment]
Can you share the model? I've used ColladaLoader in Electron before so there shouldn't be any three.js changes needed. It's possible this could be better helped on the forum as well.

**Comment by Mugen87** [comment]
Closing. Please continue the discussion at the [forum](https://discourse.threejs.org/). If it turns out that something can be changed in the loader, we can reopen the issue.
