### ISSUE TITLE
Not able to set ImageBitmapLoader options in GLTFLoader - No flipY possible

### ISSUE THREAD

**Issue by dangarfield** [mrdoob/three.js#25132]
**Describe the bug**

It is not possible to `flipY` a texture that has been loaded through the current `GLTFLoader` when it uses `ImageBitmapLoader`.

https://threejs.org/docs/#api/en/textures/Texture.flipY states:
`Note that this property has no effect for ImageBitmap. You need to configure on bitmap creation instead. See ImageBitmapLoader.`

The only arguments that can be passed to the GLTFLoader are the LoadingManager. 

When the `GLTFParser` is constructed, an `ImageBitmapLoader` is created, but there is no allowance in setting any options for it, eg `{ imageOrientation: 'flipY' }`.

https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/GLTFLoader.js#L2278
```js
if ( typeof createImageBitmap === 'undefined' || isSafari || ( isFirefox && firefoxVersion < 98 ) ) {
    this.textureLoader = new TextureLoader( this.options.manager );
    // this.textureLoader is not accessible to set options on,
    // eg, this.textureLoader.setOptions( { imageOrientation: 'flipY' } );
} else {
    this.textureLoader = new ImageBitmapLoader( this.options.manager );
}
```

**Fix**

I'm happy to add a fix by:
- Allowing the passing of an additional options object to the GLTFLoader directly `new GLTFLoader(loadingManager, { textureLoaderOptions: { imageOrientation: 'flipY' } } )`
- Adding an generic options attribute to GLTFLoader `parse` and `load` method that are passed into the `GLTFParser` constructor
- Adding a generic `setOptions` method to GLTFLoader, than will set options, which will be interrogated and retrieved when passing to the `GLTFParser` constructor
- A specific variation of any of the above
- Any other suggestions welcome

Apologies if anything is wrong with this statement.

**Comment by Mugen87** [comment]
Why do you need to configure `flipY` in the first place? `GLTFLoader` use `ImageBitmapLoader` such that the textures are automatically displayed correctly.

**Comment by dangarfield** [comment]
In my use case, which is admittedly specific, the textures are used in multiple places, both as references to textures loaded through GLTF, additional textures loaded independently of the initial GLTF, but added to the models (of which I have an ImageBitLoader where I can set the options), and also as a standard web image.

My current workaround is to store as GLTF expected (flipped), then deal with the non-GLTF problems with flipping the image (to the 'web correct' orientation), with css and canvas/js where applicable.

If you feel as though this is expected and it's a `won't fix`, that's fine.

**Comment by dangarfield** [comment]
Understood, I'll close.
