### ISSUE TITLE
Loaders: `Cache.js` use `new WeakMap()`.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#25148]
**Is your feature request related to a problem? Please describe.**

https://github.com/mrdoob/three.js/blob/6247810b81874e2b531cd1066acd23f9a757b97a/src/loaders/Cache.js#L5

Whether it is better to use `new WeakMap()` replacement here.

**Describe the solution you'd like**

```diff
const Cache = {
-	files: {},
+	files: new WeakMap(),
}
```

`add`, `get`, `remove` and `clear` method needs to be modified accordingly.

**Describe alternatives you've considered**

It maybe reduce memory with `WeakMap`, I'm not sure it's no problem with this change.

**Additional context**

[MDN WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap)

**Comment by donmccurdy** [comment]
Because the keys are strings, we cannot use WeakMap in this case. It releases memory only when the keys may be garbage collected, not the values.
