### ISSUE TITLE
gl_FrontFacing fails when a DoubleSide object is marked as transparent

### ISSUE THREAD

**Issue by sguimmara** [mrdoob/three.js#25149]
**Describe the bug**

I have a fragment shader that uses the OpenGL boolean variable [`gl_FrontFacing`](https://registry.khronos.org/OpenGL-Refpages/gl4/html/gl_FrontFacing.xhtml) to change the color of the fragment for backside faces.

This works fine as long as the material is not `transparent`. This seems to be related to how `WebGLRenderer` handles double-sided transparent objects as two different render calls :

- https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L827
- https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1313

**To Reproduce**

1. Create a material with `transparent` as `true` and `side` as `DoubleSide`.
2. Use the following fragment shader: 
```glsl
void main() {
    if (gl_FrontFacing) {
        gl_FragColor = vec4(1, 0, 0, 1);
    } else {
        gl_FragColor = vec4(0, 0, 1, 1);
    }
}

```
4. The backside of the object should be blue, but it its red instead. Set `transparent` to `false`, and the backside becomes blue.

***Code***

```js
// code goes here
```

***Live example***

* [jsfiddle-dev](https://jsfiddle.net/jmef760t/15/)

**Expected behavior**

The backside should stay blue even when `transparent` is `true`.

**Screenshots**

See the jsfiddle.

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: Tested on MacOS X, Windows 10, and Ubuntu 22.04
 - Browser: Chrome, Firefox
 - Three.js version: all ?

**Comment by WestLangley** [comment]
`gl_FrontFacing` depends on the winding order. When `side = THREE.BackSide`, the winding order is reversed for WebGLRenderer.

Use this pattern, instead
```glsl
void main() {
    #ifndef FLIP_SIDED
        gl_FragColor = vec4( 1, 0, 0, 1 );
    #else
        gl_FragColor = vec4( 0, 0, 1, 1 );
    #endif
}
```

https://jsfiddle.net/ubfpkdr1/

**Comment by WestLangley** [comment]
`gl_FrontFacing` depends on the winding order. When `side = THREE.BackSide`, the winding order is reversed for WebGLRenderer.

Use this pattern, instead
```glsl
void main() {
    #ifdef FLIP_SIDED
        gl_FragColor = vec4( 0, 0, 1, 1 );
    #elif defined( DOUBLE_SIDED )
        gl_FragColor = ( gl_FrontFacing ) ? vec4( 1, 0, 0, 1 ) : vec4( 0, 0, 1, 1 );
    #else
        gl_FragColor = vec4( 1, 0, 0, 1 );
    #endif
}
```

https://jsfiddle.net/Lshtqgz4/

**Comment by sguimmara** [comment]
The `FLIP_SIDED` define is not applicable to  `RawShaderMaterial`s unfortunately. Is there  a way to work around that ?

**Comment by sguimmara** [comment]
> You can define the `FLIP_SIDED` define by yourself in this case. It is true when `material.side === BackSide`.

But I never set `material.side = BackSide`, only `DoubleSide`, and the define should occur when the renderer artificially changes the `side` property right before recompiling it. I tried to implement a `onBeforeCompile` but it didn't work.

**Comment by Mugen87** [comment]
I see. This looks like a limitation since the renderer does not manage the defines for `RawShaderMaterial`. For now, it's seems you have to use `ShaderMaterial` if you want to keep using `gl_FrontFacing`.

**Comment by Mugen87** [comment]
Or we solve #24711 so you can disable the rendering of transparent objects in two passes.

**Comment by sguimmara** [comment]
> Or we solve #24711 so you can disable the rendering of transparent objects in two passes. I guess that would help, too?

I guess so !
