### ISSUE TITLE
The matrixWorld of Bone should be automatically updated

### ISSUE THREAD

**Issue by ShiHongyu6** [mrdoob/three.js#25154]
**Is your feature request related to a problem? Please describe.**

Before call SkinnedMesh.bind(skeleton, undefined), I must set the root bone as a child of skinnedMesh so that the bones' matrixWorld update.
Like this:
```js
mesh.add(rootBone);
mesh.bind(skeleton);
```
But if I code like this: (As a fresher, I do this actually)
```
mesh.bind(skeleton);
mesh.add(rootBone);
```
The bones' matrixWorld is not updated so that skeleton's boneInverses is wrong. And the result rendered is wrong.

**Describe the solution you'd like**

I think that the Bone's add() could be override to update the matrixWorld automatically.

**Describe alternatives you've considered**

Write it in the documentation that is 'please call Bone.updateMatrixWorld() or call mesh.add(rootBone) before call mesh.bind()'.

**Comment by Mugen87** [comment]
Sorry, but we can't do that. The issue you have describe can happen with any kind of 3D objects. If we start to update matrices inside `add()` we introduce potential performance regressions (especially for apps which frequently add and remove nodes to the scene graph).

If you manually setup skinned meshes, you have to know this details and manage your code accordingly.

**Comment by ShiHongyu6** [comment]
Thank you for your prompt reply.
I get it. Could you please update the documentation？And then there will be fewer people who make this mistake.

**Comment by Mugen87** [comment]
TBH, I believe the existing guides should already cover this topic sufficiently.
