### ISSUE TITLE
USDZExporter does not apply min and mag filters to textures.

### ISSUE THREAD

**Issue by esnho** [mrdoob/three.js#25153]
**Is your feature request related to a problem? Please describe.**

Looks like the USDZExporter does not onor the texture's Min and Mag filters but applies the default linear filter to exported files.

**Describe the solution you'd like**

Would be great if the USDZExporter keep Min and Mag filters on exported files.

**Describe alternatives you've considered**

I think there's no alternative to this.

**Additional context**

I've applied `NearestFilter` to my normal maps but if I open the USDZ with xCode the normal map filter is set to Linear.

**Comment by Mugen87** [comment]
Are you sure USDZ supports texture filtering modes? I did not found something related so far on the web...

**Comment by esnho** [comment]
Ohhh, you are right, Xcode editor permits to set a filter mode but the exported file does not apply that... this is confusing but not on Three.js side :)
