### ISSUE TITLE
Remove /> from self-closing tags in the docs

### ISSUE THREAD

**Issue by manake** [mrdoob/three.js#25155]
Example: https://github.com/mrdoob/three.js/blob/dev/docs/manual/en/introduction/FAQ.html

```
<meta charset="utf-8">
<base href="../../../" />
<script src="page.js"></script>
<link type="text/css" rel="stylesheet" href="page.css" />
```

The `<base href="../../../" />` can be rewritten as `<base href="../../../">`.

Void elements: https://html.spec.whatwg.org/multipage/syntax.html#elements-2

**Comment by Mugen87** [comment]
Feel free to update the docs as suggested. Since this issue is so minor and has no effect on the documentation itself, a separate issue is not needed.
