### ISSUE TITLE
Arrow keys doesn't work.

### ISSUE THREAD

**Issue by kolianbolo** [mrdoob/three.js#25157]
**Describe the bug**

Arrow keys doesn't work. 
I up three.js version to 147 and arrows control was broke.

**To Reproduce**

1. Version up to 147 dev.
2. Arrow keys doesn't work.

***Code***

```js
controls = new OrbitControls(camera, renderer.domElement);
controls.enableKeys = true;
controls.keys = {
    LEFT: 'ArrowLeft', 
    UP: 'ArrowUp', 
    RIGHT: 'ArrowRight', 
    BOTTOM: 'ArrowDown'
};
controls.update();
```

**Expected behavior**

Control by arrow keys is worked.

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome
 - Three.js version: 147dev

**Comment by Mugen87** [comment]
`enableKeys` has been removed with `r125`. Use `controls.listenToKeyEvents( window );` instead.

https://jsfiddle.net/jcdsrm6t/1/

**Comment by kolianbolo** [comment]
Thank you!
