### ISSUE TITLE
New YAML based issue report

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#25163]
### Description

It was too easy for someone to file a bug report and we were wasting too much time triaging issues.

GitHub supports YAML based templates that turn the issue into a form. 

Lets hope this reduces the amount of low quality reports 🤞

Any tweaks we should do to the template?

### Reproduction steps

Not relevant

### Code

Not relevant

### Live example

Not relevant

### Version

r148

**Comment by mrdoob** [comment]
This is how it looks like:

<img width="937" alt="Screenshot 2022-12-21 at 15 15 50" src="https://user-images.githubusercontent.com/97088/208834857-018f3efd-81c7-46e9-8fbb-801e2c4e22b7.png">

One downside is that the form doesn't have a way for attaching screenshots 😕

**Comment by Mugen87** [comment]
LGTM. Definitely a step forward compared to the current tempalte.

**Comment by Mugen87** [comment]
Oh, it seems screenshots can still be added to issues, see #25166.

**Comment by mrdoob** [comment]
Oh that's true!

**Comment by mrdoob** [comment]
Added it back: https://github.com/mrdoob/three.js/commit/217926986d8f97ab94082b68398fd6042311c83b

**Comment by Mugen87** [comment]
After three weeks, the new issue templates work quite well! Recent issues seems to be reported in a "more complete" fashion (meaning more details/information are added).
