### ISSUE TITLE
Importing { Geometry } from 'three/examples/jsm/deprecated/Geometry'; does not compile in Angular 14

### ISSUE THREAD

**Issue by paulchill** [mrdoob/three.js#25161]
**Describe the bug**
I need to use the older version of Geometry but i cannot import it or build with Angular 14

**import { Geometry } from 'three/examples/jsm/deprecated/Geometry';**

In visual studio i can click "**Geometry**" and it brings me to the path: 

**node_modules\@types\three\examples\jsm\deprecated\Geometry.d.ts** 

but when i try to ng serve i get :
 
**Error: Module not found: Error: Can't resolve 'three/examples/jsm/deprecated/Geometry' in '**

**Expected behavior**

To be able to import and use the deprecated esm Geometry.js class

**Screenshots**
![image](https://user-images.githubusercontent.com/6987900/208796403-2d1776de-7e90-48e6-9009-d40d686fc43e.png)
![image](https://user-images.githubusercontent.com/6987900/208796471-ad02dc65-6ac2-4ee4-a352-ba408732d3b5.png)
![image](https://user-images.githubusercontent.com/6987900/208796498-176a305f-25c8-4258-99e9-1a4520350282.png)

**Platform:**

 - Device:Desktop
 - OS: windows
 - Browser: chrome
 - Three.js version: latest

**Comment by donmccurdy** [comment]
This file is no longer just deprecated, it has been removed from the library. Perhaps `@types/three` is out of sync here, the types are maintained separately in https://github.com/three-types/three-ts-types.


For help I would recommend any of these links:

- [questions](https://stackoverflow.com/questions/tagged/three.js)
- [discord](https://discord.gg/56GBJwAnUS)
- [forum](https://discourse.threejs.org/)

**Comment by paulchill** [comment]
Ok.

I was under the impression it was under the examples jsm folder as deprecated but still accessible, so i can use the toBufferGeometry methods for existing vertices
  
  
  

e.g

"The upcoming release r125 will contain a major, potentially breaking change. The class THREE.Geometry will be no longer part of the core but moved to jsm/deprecated/Geometry.js. It will only be available as an ES6 module and not as a global script. What does that mean for me? If you are loading your assets with one of the official loaders like GLTFLoader or procedurally generate geometry data with THREE.BufferGeometry, this change won’t affect you. If you are using THREE.Geometry, please note …"

**Comment by paulchill** [comment]
ah ok gotcha thanks v much.
