### ISSUE TITLE
Raycaster doesn't work with flexbox

### ISSUE THREAD

**Issue by eulertour** [mrdoob/three.js#25162]
**Describe the bug**
`THREE.Raycaster` is inaccurate when used on a canvas with a nonzero `flex-grow` property.

**To Reproduce**
Visit https://jsfiddle.net/qbnocgr9/2/

The raycaster detects an intersection with the cube when the mouse is slightly to the left of it rather than when it's directly on top of it.

***Code***
https://jsfiddle.net/qbnocgr9/2/

***Live example***

https://jsfiddle.net/qbnocgr9/2/

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Browser: [Chrome]
 - Three.js version: [release]

**Comment by gkjohnson** [comment]
This is an issue with how you're computing the width of the canvas element given the CSS being used.

Best to ask at the forum for help:

https://discourse.threejs.org/
