### ISSUE TITLE
Support avif as texture image format

### ISSUE THREAD

**Issue by leon** [mrdoob/three.js#25171]
### Description

My Christmas contribution is trying to get AVIF support in GLTF, Three and Babylon.

I Did a PR for the GLTF spec which you can find here
https://github.com/KhronosGroup/glTF/pull/2235

I have also done a PR for three which I'm going to link to from this issue

My thoughts are the following.
Chrome recently gave up on jpeg xl which I personally thought was the superior replacement for gif, png, jpeg, webp.

The next best format after jpeg xl is avif, and since jpeg xl isn't happening I thought I could do a drive trying to improve the file size of gltf files by getting avif support.

### Solution

Add the not yet merged https://github.com/KhronosGroup/glTF/pull/2235 EXT_texture_avif as a supported extension.

### Alternatives

WebP doesn't compress as good as AVIF.

**Comment by donmccurdy** [comment]
Fixed in https://github.com/mrdoob/three.js/pull/25173 – thank you @leon!
