### ISSUE TITLE
VectorKeyframeTrack goes an infinite loop when I give a wrong length of `values`

### ISSUE THREAD

**Issue by 0b5vr** [mrdoob/three.js#25187]
### Description

Related: #25186 

In the constructor of `VectorKeyframeTrack`, when `values.length / times.length` is not dividable, it will go the infinite loop.
I think it also applies to `ColorKeyframeTrack` and `QuaternionKeyframeTrack`.

I think we need validation of the array size of `values` for these keyframe track classes.

Where the infinite loop happens: https://github.com/mrdoob/three.js/blob/309b00afb6dcbc5e6c58e72f10eaa8d2e8888c83/src/math/interpolants/LinearInterpolant.js#L23-L29

The image below is when I give `times = [0, 1]` and `value = [1, 2, 3, 4, 5]` to `VectorKeyframeTrack`:

![image](https://user-images.githubusercontent.com/7824814/209348309-1be47dea-80c4-4d9f-bf5e-4a65ac9fa21c.png)

### Reproduction steps

1. Give a wrong sized array to `values` of the constructor of `VectorKeyframeTrack`
2. Call `AnimationMixer.update();`
3. Go the infinite loop

<details><summary>Stack trace of the `AnimationMixer.update()` part:</summary>
<ol>
<li>`AnimationMixer.update()`</li>
<li>`AnimationAction._update()`</li>
<li>`Interpolant.evaluate()`</li>
<li>`LinearInterpolant.interpolate_()`</li>
</ol>
</details>

### Code

```js
const track = new THREE.VectorKeyframeTrack(
  'sphere.position',
  [ 0.0, 1.0 ],
  [ 1, 1, 0, 1, 1 ], // have to be a multiple of 3, but it's not
  THREE.InterpolateLinear,
);
```

### Live example

**CW: It will go the infinite loop and the thread usage hits 100%**
https://glitch.com/edit/#!/blossom-burly-whip?path=main.js%3A24%3A2

### Version

r147

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by WestLangley** [comment]
three.js does not validate inputs. That is your app's responsibility.

**Comment by Mugen87** [comment]
Indeed. Regarding https://github.com/mrdoob/three.js/issues/25186#issuecomment-1364007700, the same principle applies here.

**Comment by 0b5vr** [comment]
I think the infinite loop is kinda exceptional. Consider you're writing your Three.js on the environment which live reloads as you write your code (like Glitch), you accidentally make the environment go the infinite loop, which is fatal if they are doing live programming, for example.

**Comment by WestLangley** [comment]
As we said, three.js does not validate inputs.

The lesson for you is you need to be more careful.

**Comment by 0b5vr** [comment]
Ok, the exception does not apply and that's the design philosophy of Three.js, got it.

I don't understand why you talk so meanly though.

**Comment by 0b5vr** [comment]
how about changing the loop ending condition from `!==` to `<`?
This does not require any addition of validations.

https://github.com/mrdoob/three.js/blob/309b00afb6dcbc5e6c58e72f10eaa8d2e8888c83/src/math/interpolants/LinearInterpolant.js#L23

**Comment by WestLangley** [comment]
Oh sorry @0b5vr, I did not intend to be mean.

**Comment by mrdoob** [comment]
> how about changing the loop ending condition from `!==` to `<`?
> This does not require any addition of validations.
>
> https://github.com/mrdoob/three.js/blob/309b00afb6dcbc5e6c58e72f10eaa8d2e8888c83/src/math/interpolants/LinearInterpolant.js#L23

That change sounds goo to me 👍
