### ISSUE TITLE
ColorKeyframeTrack does not accept THREE.Color

### ISSUE THREAD

**Issue by 0b5vr** [mrdoob/three.js#25186]
### Description

`values`, the third argument of [ColorKeyframeTrack](https://threejs.org/docs/#api/en/animation/tracks/ColorKeyframeTrack), is intended to be given either `number[]` or `TypedArray`.
However, if end developers give `THREE.Color[]` by mistake, it causes a flashing light.

I don't know why it causes the flashing light, but I think it's not the point.
If possible, I would want to add a validation code to prevent the behavior.
There is no need to actually accept `THREE.Color`s here I think.

For example, the input `[ THREE.Color(), THRE.Color() ]` will be converted to `[ NaN, NaN ]` by `AnimationUtils.convertArray( values, this.ValueBufferType );`.

The call of `AnimationUtils.convertArray()`: https://github.com/mrdoob/three.js/blob/309b00afb6dcbc5e6c58e72f10eaa8d2e8888c83/src/animation/KeyframeTrack.js#L20-L21
The implementation of `AnimationUtils.convertArray()`: https://github.com/mrdoob/three.js/blob/309b00afb6dcbc5e6c58e72f10eaa8d2e8888c83/src/animation/AnimationUtils.js#L19-L33

### Reproduction steps

- Give `THREE.Color[]` to `ColorKeyframeTrack`
- Play the animation
- Flashing lights

I'm 100% sure this is not an intended way to use `ColorKeyframeTrack`, to clarify.

### Code

```js
// ...

const track = new THREE.ColorKeyframeTrack(
  'sphere.material.color',
  [ 0.0, 1.0 ],
  // [ 1, 1, 0, 0, 1, 1 ], // correct one
  [ new THREE.Color( 1, 1, 0 ), new THREE.Color( 0, 1, 1 ) ], // wrong one, causes flashing light
  THREE.InterpolateLinear,
);

// ...
```

### Live example

**CW: FLASHING LIGHT**
https://glitch.com/edit/#!/sleet-yielding-carrot

### Version

r147

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by 0b5vr** [comment]
Ah, the flashing light only happens when I give an array whose element count is multiple of 2.
It even happens when we give `number[]` instead of `THREE.Color[]`.

If the element count is not even a multiple of 2, It seems it does not come back from an infinite loop.
I'm also not sure why.
It's probably a separate issue.

**Comment by 0b5vr** [comment]
Made a separated issue: https://github.com/mrdoob/three.js/issues/25187.

This issue will focus on the `THREE.Color` and `ColorKeyframeTrack` part.

**Comment by Mugen87** [comment]
Yes, an array of with instances of `THREE.Color` is invalid input. The docs state `values` has to be:

> a flat array of color components between 0 and 1.

We usually do not sanitize wrong user input. Hence, I would not change anything unless this becomes to a common issue (which I doubt since most user to not manually create keyframe tracks).

**Comment by 0b5vr** [comment]
Yes, I agree to just leave it as is until users bump into this issue too much. Just want to leave this as an issue.
