### ISSUE TITLE
GLTFExporter can not export correct animations

### ISSUE THREAD

**Issue by fengxinming** [mrdoob/three.js#25198]
### Description

import two object models with the same glb file to threejs editor, and then export the scene as a new glb file. delete these two object models and import that new glb file, play animations and only a object model animating. see this video to describe this issue

https://user-images.githubusercontent.com/6262382/209495984-457d2393-6398-46d0-a338-ea337e7c2206.mp4

### Reproduction steps

1. git clone https://github.com/mrdoob/three.js.git
2. npm install
3. npm run dev
4. after editor server running then import `three.js/examples/models/gltf/Stork.glb` into the threejs editor
5. move the position of the object model, and then import `three.js/examples/models/gltf/Stork.glb` into the threejs editor again
6. export the current scene as a glb file, and delete two object models from the current scene
7. import the above exported glb file
8. play animations of the imported object model, you can see only a stork flying

### Code

none

### Live example

none

### Version

0.147.0

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by donmccurdy** [comment]
- /cc https://github.com/mrdoob/three.js/issues/25179#issuecomment-1365358293

**Comment by Mugen87** [comment]
Merging into #25179. If #25179 is resolved and this issue still occurs, when can reopen it.
