### ISSUE TITLE
Instancing/raycast example on threejs.org uses GPU 100% and make browser freezing

### ISSUE THREAD

**Issue by weareoutman** [mrdoob/three.js#25203]
### Description

When open https://threejs.org/examples/webgl_instancing_raycast.html, the Chrome task manager shows it uses GPU 100%, and Chrome is almost freezing.

And it is still kind of freezing even if I added a search string `?5` to make less instance count.

### Reproduction steps

1. Open Chrome task manager
2. Visit https://threejs.org/examples/webgl_instancing_raycast.html
3.

### Code

```js
// code goes here
```

### Live example

* https://threejs.org/examples/webgl_instancing_raycast.html

### Version

r147

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by mrdoob** [comment]
Works fine on all my devices.

What mac model is that with?

**Comment by weareoutman** [comment]
<img width="235" alt="image" src="https://user-images.githubusercontent.com/2338946/209904921-4de500dc-42bf-4421-abd4-1fdd1cfb8311.png">

**Comment by weareoutman** [comment]
Don't know what's the problem, it seems other instancing examples work fine, but the raycast one doesn't

**Comment by mrdoob** [comment]
Does it happen with Safari too?

**Comment by weareoutman** [comment]
It works fine with Safari...

My Chrome version 108.0.5359.124

**Comment by mrdoob** [comment]
The issue is in Chrome issue then.

Please, report the issue here instead:
https://bugs.chromium.org/p/chromium/issues/list

Make sure you try other browsers before reporting an issue next time.

**Comment by Mugen87** [comment]
It seems you run into https://bugs.chromium.org/p/chromium/issues/detail?id=1245448.
