### ISSUE TITLE
MeshDepthMaterial with alphaTest not working

### ISSUE THREAD

**Issue by xinaesthete** [mrdoob/three.js#25217]
### Description

Trying to cast a shadow with `alphaTest` using a `customDepthMaterial` appears not to be working since ~r0.132. I've provided a link to a sandbox example that is working correctly, but selecting a later version of the library causes it to break.

I have found that if the `customDepthMaterial` is also set as the `material` of the mesh, then the `customDepthMaterial` does work (somewhat), although changing this at runtime has different results than doing so before the mesh gets rendered.

### Reproduction steps

1. create a scene with a mesh and shadow-casting light
2. assign a `customDepthMaterial` with a `map` and some value of `alphaTest` to the mesh.

### Code

```js
const loader = new THREE.TextureLoader();
const texture = loader.load("/whatever.png");
const shadowCasterGeometry = new THREE.PlaneGeometry(10, 10);
const shadowCasterMaterial = new THREE.MeshStandardMaterial({
  color: "#fff",
  side: THREE.DoubleSide,
  map: texture,
  transparent: true
}) as THREE.Material;
const shadowCaster = new THREE.Mesh(shadowCasterGeometry, shadowCasterMaterial);
shadowCaster.customDepthMaterial = new THREE.MeshDepthMaterial(
  {
    map: texture,
    alphaTest: 0.6,
    depthPacking: THREE.RGBADepthPacking,
    transparent: false
  }
);
```

### Live example

* [codesandbox](https://codesandbox.io/s/three-depthmaterialbug-jfwox7?file=/src/index.ts)

### Screenshots

![image](https://user-images.githubusercontent.com/674834/210223359-d86e14cc-8c36-4662-84d9-7857257b3abd.png)
![image](https://user-images.githubusercontent.com/674834/210223392-ca414997-e477-4fe3-b0cf-2874ba2e227c.png)

### Version

r>131

### Device

Desktop

### Browser

Chrome

**Comment by Mugen87** [comment]
That should be fixed with `r148`.

Sidenote: You don't necessarily need a separate depth material for this use case anymore. Defining `alphaTest` on the mesh's material does also affect shadows now.

**Comment by xinaesthete** [comment]
Thanks @Mugen87 I see that `alphaTest` on the mesh material does indeed work. However if you load that sandbox and switch the three.js dependency to `0.148.0`, it does not appear correctly, so I think there is still a bug there.

**Comment by xinaesthete** [comment]
It seems that it does work correctly in `r148` if both the material and depth material have `alphaTest` set.

**Comment by WestLangley** [comment]
>It seems that it does work correctly in r148 if both the material and depth material have alphaTest set.

For your use case, a custom depth material should not be necessary if you set `alphaTest` on the material.
