### ISSUE TITLE
GLTFExporter DataTexture roughness and metalness support

### ISSUE THREAD

**Issue by tom1700** [mrdoob/three.js#25227]
### Description

I'm trying to create a model in the browser and export it using MeshStandardMaterial but the `buildMetalRoughTexture` assumes that the texture is always an Image type texture and not a DataTexture (check the js fiddle).

As a result it tries to do `context.drawImage(image, 0, 0, width, height);` with a DataTexture.image which is not a real image.

It is relatively easy to fix with something like this:
```
    function getTextureData(map, image) {
      if (map.isDataTexture) {
        return image.data;
      }

      context.drawImage(image, 0, 0, width, height);

      const data = context.getImageData(0, 0, width, height).data;

      return data;
    }

    if (metalness) {
      const convert = getEncodingConversion(metalnessMap);
      const data = getTextureData(metalnessMap, metalness);

      for (let i = 2; i < data.length; i += 4) {
        composite.data[i] = convert(data[i] / 256) * 256;
      }
    }

    if (roughness) {
      const convert = getEncodingConversion(roughnessMap);
      const data = getTextureData(roughnessMap, roughness);

      for (let i = 1; i < data.length; i += 4) {
        composite.data[i] = convert(data[i] / 256) * 256;
      }
    }
```

### Reproduction steps

Just open the js fiddle and check the console.

### Code

```js
// code goes here
```

### Live example

https://jsfiddle.net/m6b5scvo/1/

### Version

r148

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
Unfortunately, adding support for data textures is not trivial. Your code _only_ works  if the users creates its data texture with `Uint8ClampedArray`. That is not necessarily true for all use cases.

For now, I think it's better to delegate the task to the app level and let it convert data textures to canvas textures before the export is done.

**Comment by tom1700** [comment]
OK I get it.

Thanks for the explanation.
