### ISSUE TITLE
Unable to export point cloud with normals using plyexporter 

### ISSUE THREAD

**Issue by mandre96** [mrdoob/three.js#25233]
### Description

Hi! I'm trying to export an point cloud using ply exporter. The exportation works fine, however, no attributes (colors and normals) are written to the .ply file. Is this a bug or it's just a missing feature? 

Any help would be immensly appreciated.

### Reproduction steps

1. Export Point Cloud with normals in .ply
2. Open in point cloud software to inspect

### Code

```js


 public exportPLY()
    {   

     
        AngioViewer.singleton().pointSelection.updateGeometry(); //deletes selected points and creates new geometry
        const exporter = new PLYExporter();
        exporter.parse(this._point_cloud, (data) => {this.downloadFile(data); console.log(data);}, { binary: false, excludeAttributes: [], littleEndian: false });
       

    }

private downloadFile(data:any): void { //Downloads file for inspection
    const link = document.createElement( 'a' );
    link.style.display = 'none';
    document.body.appendChild( link );
    
    
    const blob = new Blob( [ data ], { type: 'text/plain' } );	
    const objectURL = URL.createObjectURL( blob );
     
    link.href = objectURL;
    link.href = URL.createObjectURL( blob );
    link.download =  'point_cloud.ply';
    link.click();
 }

```

### Screenshots

Screenshot of the downloaded point cloud in MeshLab:

![image](https://user-images.githubusercontent.com/36490655/210625609-f1fd7619-df14-4771-8fb1-afd7bee757fa.png)

### Version

148

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by WestLangley** [comment]
That is currently not supported. You can hack your copy of the exporter like so:
```js
} else if ( child.isPoints ) {

	const mesh = child;
	const geometry = mesh.geometry;

	const vertices = geometry.getAttribute( 'position' );
	const normals = geometry.getAttribute( 'normal' );
	const colors = geometry.getAttribute( 'color' );

	vertexCount += vertices.count;

	if ( normals !== undefined ) includeNormals = true;

	if ( colors !== undefined ) includeColors = true;

	includeIndices = false;

}
```

I can add something like this if there is interest.

**Comment by mandre96** [comment]
I just looked at the source code, and realised just that. Thank you, i will try your sugestion for now. In point cloud exporting, in most cases, the normals are a crucial attribute, specially for surface reconstruction. So i think that enabling this by default it's going to be a nice feature!

**Comment by mandre96** [comment]
So this should be a feature request, I will close this issue and open a feature request.
