### ISSUE TITLE
Issue rendering transparent objects with lots of vertex nodes

### ISSUE THREAD

**Issue by dipterix** [mrdoob/three.js#25255]
### Description

I recently upgraded my threejs deps from 131dev to 148 (latest as of 2023 Jan7) and found that the newer version had some issues (more aliases) rendering transparent mesh with lots of nodes:

Here is screenshot using 148

<img width="577" alt="image" src="https://user-images.githubusercontent.com/8163576/211134582-9fe53f8b-f9d0-4d48-94c2-ffd073ecd180.png">

This is rendering result using exactly the same parameters in 131dev:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/8163576/211134536-abb59386-b250-42d5-ad19-84af469eb8ea.png">

There was not that many aliases in the old versions.

### Reproduction steps

1. Prepare dense geometry (see wireframe as follows, there are 114063 nodes)

<img width="577" alt="image" src="https://user-images.githubusercontent.com/8163576/211134627-3229a2d7-144b-441d-9df7-fe7ba794e0ef.png">

2. render mesh with `MeshPhongMaterial` (as in screenshot) or `MeshLambertMaterial` with the following parameters:

```
  'transparent' : true,
  'side': DoubleSide,
  'vertexColors' : true
```

(I tried to change side to FrontSide only, but there was no improvement)

3. set mesh transparency to `0.7`

### Code

```js
    this._geometry = new BufferGeometry();

    // construct geometry
    this.__nvertices = vertices.length;
    const vertex_positions = new Float32Array( this.__nvertices * 3 ),
          face_orders = new Uint32Array( faces.length * 3 ),
          vertex_color = new Float32Array( this.__nvertices * 3 ).fill(1);

    // vertex colors are set later... not showing in code, but very smooth
    this._vertex_color = vertex_color;

    vertices.forEach((v, ii) => {
      vertex_positions[ ii * 3 ] = v[0];
      vertex_positions[ ii * 3 + 1 ] = v[1];
      vertex_positions[ ii * 3 + 2 ] = v[2];
    });
    faces.forEach((v, ii) => {
      face_orders[ ii * 3 ] = v[0];
      face_orders[ ii * 3 + 1 ] = v[1];
      face_orders[ ii * 3 + 2 ] = v[2];
    });

    this._geometry.setIndex( new BufferAttribute(face_orders, 1) );
    this._geometry.setAttribute( 'position', new BufferAttribute(vertex_positions, 3) );
    this._geometry.setAttribute( 'color', new BufferAttribute( vertex_color, 3, true ) );


    // gb.setAttribute( 'color', new Float32BufferAttribute( vertex_colors, 3 ) );
    // gb.setAttribute( 'normal', new Float32BufferAttribute( normals, 3 ) );

    this._geometry.computeVertexNormals();
    this._geometry.computeBoundingBox();
    this._geometry.computeBoundingSphere();
    //gb.faces = faces;

    this._geometry.name = 'geom_free_' + g.name;

    this._mesh = new Mesh(this._geometry, new MeshPhongMaterial({
      'transparent' : true,
      'side': DoubleSide,
      'wireframeLinewidth' : 0.1,
      'vertexColors' : true
    });
```

### Live example

Sorry I can't share my data due to work protocol. However, my code to generate mesh was pretty much the same as the threejs examples/tutorials as of r131.

### Screenshots

Please check previous context. 

Also this is the rendering result with no transparency to prove that the aliases are not caused by vertex colors.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/8163576/211135253-59c5b44e-36cc-451a-9dfa-f01eb4770dae.png">

### Version

148

### Device

Desktop

### Browser

Firefox, Safari

### OS

MacOS

**Comment by LeviPesin** [comment]
This may be due to https://github.com/mrdoob/three.js/pull/25165. Does your issue go away if you use `TwoPassDoubleSide` instead of `DoubleSide`?

**Comment by dipterix** [comment]
@LeviPesin Amazing! Thanks, it does go away!!! 


(I'm closing this issue)

**Comment by mrdoob** [comment]
@LeviPesin I guess we'll have to add a warning after all... 😅
