### ISSUE TITLE
ArcballControls not to found in 0.117.0 version

### ISSUE THREAD

**Issue by crithes** [mrdoob/three.js#25266]
### Description

ArcballControls not to found

### Reproduction steps

1.ArcballControls not to found in 0.117.0 version

### Code

```js
// import { ArcballControls } from 'three/addons/controls/ArcballControls.js,无法引入
```

### Live example

ArcballControls not to found

### Version

0.117.0

**Comment by mrdoob** [comment]
`ArcballControls` was added in `r133`.
https://github.com/mrdoob/three.js/commit/a403fda26684d2b8ec5ff8975d3edb960e67d295
