### ISSUE TITLE
textureLoader load svg

### ISSUE THREAD

**Issue by mehrabb74** [mrdoob/three.js#25262]
### Description

as **svg** is lighter than png /jpg then how we can use it as usual **texture** in threejs?

### Solution

```
const textureLoader = new THREE.TextureLoader();
const mySvg = textureLoader.load('./the.svg')
const myMaterial = new THREE.MeshBasicMaterial({map: mySvg });
```

### Alternatives

```
const textureLoader = new THREE.TextureLoader();
const mySvg = textureLoader.load('./the.svg')
const myMaterial = new THREE.MeshSvgMaterial({svg : mySvg });
```

**Comment by LeviPesin** [comment]
There is already an [SVGLoader](https://threejs.org/docs/examples/en/loaders/SVGLoader.html) available as an addon.

**Comment by mehrabb74** [comment]
> There is already an [SVGLoader](https://threejs.org/docs/examples/en/loaders/SVGLoader.html) available as an addon.

hmmm
hope to see simpler way/solution :)
thanks btw
