### ISSUE TITLE
MikkTSpaceTangents: Generating tangents for "NormalTangentTest" glTF sample model breaks normals

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#25263]
### Description

When loading the glTF sample [NormalTangentTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest) model and manually generating tangents using the `BufferGeometryUtils.computeMikkTSpaceTangents` function the computed normals change and the model renders incorrectly.

However according to the [spec](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html) - MikkTSpace tangents should produce the correct result:

> When tangents are not specified, client implementations SHOULD calculate tangents using default [MikkTSpace](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#mikktspace) algorithms with the specified vertex positions, normals, and texture coordinates associated with the normal texture.

It looks like the `computeMikkTSpaceTangents` function inverts the tangent direction by default here specifically noting alignment for glTF files. However disabling this behavior by passing "false" into the function fixes the issue. Is the tangent inversion correct?

https://github.com/mrdoob/three.js/blob/982a715fcb7e18a64aade942b761f3dd1dedb9c1/examples/jsm/utils/BufferGeometryUtils.js#L81-L92

Related to https://github.com/gkjohnson/three-gpu-pathtracer/issues/210#issuecomment-1371769273
cc @donmccurdy 

### Reproduction steps

1. Load the sample model
2. Compute tangents using `BufferGeometryUtils.computeMikkTSpaceTangents`
3. Model renders incorrectly

### Code

See jsfiddle

### Live example

https://jsfiddle.net/kpj76ob0/2/

### Screenshots

**computeMikkTSpaceTangents( geometry, MikkTSpace )**

![image](https://user-images.githubusercontent.com/734200/211231395-75df3ab8-64c6-4970-9a0b-e98ecdb88a58.png)

**computeMikkTSpaceTangents( geometry, MikkTSpace, false ) or no tangent generation**

![image](https://user-images.githubusercontent.com/734200/211231440-d1e8765d-ad30-4d35-a3b3-0f4f2343b116.png)

### Version

r147

### Device

Desktop

### Browser

Chrome

### OS

Windows, MacOS

**Comment by donmccurdy** [comment]
@gkjohnson it looks like the correct way to update the mesh for tangents would be:

```javascript
const geometries = new Set();
const materials = new Set();

gltf.scene.traverse( ( object ) => {

	if ( object.isMesh ) {

		geometries.add( object.geometry );
		materials.add( object.material );

	}


} );

for ( const geometry of geometries ) {
  
	computeMikkTSpaceTangents( object.geometry, MikkTSpace ); 

}

for ( const material of materials ) {

	if ( object.material.normalScale ) object.material.normalScale.y *= - 1
	if ( object.material.clearcoatNormalScale ) object.material.clearcoatNormalScale.y *= - 1;

}
```

The tangent inversion is correct, but does require changes to the material properties. That would also explain why my generating tangents with glTF Transform did not cause the same issue: GLTFLoader sees the tangents in that case, and applies the necessary material changes automatically.

Related:

- https://github.com/mrdoob/three.js/issues/11438#issuecomment-507003995
- https://github.com/KhronosGroup/glTF-Sample-Models/issues/174

**Comment by donmccurdy** [comment]
Perhaps it would also be fine to disable `tangent.w` negation, and leave the material properties as-is. But that would break a round-trip export, if (for example) you want to bake maps in three-gpu-pathtracer.

**Comment by gkjohnson** [comment]
Okay I see - interesting.

>```js
> for ( const material of materials ) {
>
>	if ( material.normalScale ) material.normalScale.y *= - 1;
>	if ( material.clearcoatNormalScale ) material.clearcoatNormalScale.y *= - 1;
>
>}
>```

So if I clear the tangents and then generate them again how can I make sure they line up with the appropriate material properties appropriately? If I clear the tangents would I need to multiple the normal scale - 1 again?

#18112 may answer this question but just to be sure.

**Comment by donmccurdy** [comment]
If we're talking about arbitrary user input, it might be hard to know whether a material has been configured with vertex tangents in mind, or what UV convention has been used (which would have related effects).

If we're talking about glTF source models, then it's helpful to know any `normalScale` specified by the model will be uniform: glTF does not allow different x/y parameters to normalScale. As a result I think you can safely assume:

- `Math.sign(x) === Math.sign(y)` material configured for derivative-based tangents
- `Math.sign(x) !== Math.sign(y)` material configured for vertex tangents

**Comment by gkjohnson** [comment]
Great, thanks!
