### ISSUE TITLE
Clipping planes are projected using the wrong camera in case of XR and ArrayCamera

### ISSUE THREAD

**Issue by mrxz** [mrdoob/three.js#25267]
### Description

Clipping planes defined on the renderer are projected using the (main) camera. In case this camera is an `ArrayCamera` or an XR session is active, the sub cameras will incorrectly use the projected planes from the parent camera.

### Reproduction steps

1. Define a clipping plane on the renderer
2. Render the scene with an ArrayCamera (with different positions and/or orientations for the cameras)
3. Call `renderer.render(scene, arrayCamera)`
4. Observe the clipping being different per camera

### Code

```js
    // camera setup
    const cameras = [];
    
    for ( let i = 0; i < 2; ++ i ) {

    	const subcamera = new THREE.PerspectiveCamera( 40, window.innerWidth / window.innerHeight / 2, 1, 10000 );
        subcamera.position.set( 20 - 40 * i, 20, 20 );
	subcamera.lookAt( 0, 0, 0 );
        subcamera.viewport = new THREE.Vector4( window.innerWidth/2 * i, 0, window.innerWidth/2, window.innerHeight );
        subcamera.updateMatrixWorld();

	cameras.push(subcamera);

    }
    
    camera = new THREE.ArrayCamera(cameras);

    // clipping plane
    renderer.clippingPlanes = [ new THREE.Plane( new THREE.Vector3( 1, 0, 0 ), 0 ) ];
    
    // ...
    
    renderer.render( scene, camera );
```
(Abbreviated, see Live Example)

### Live example

https://jsfiddle.net/1Lo53s2u/5/

### Screenshots

![image](https://user-images.githubusercontent.com/8823461/211643043-9feb00ce-319c-4e49-8de6-9c139844df60.png)
The image is rendered with an `ArrayCamera` with two cameras that have their viewport side-by-side. The cameras have a different position, but are both look at the world origin, where a sphere and axes helper are present.

Notice how the clipping plane is the "same" in both views. In other words, different parts of the scene are being clipped. The clipping plane should result in the same part of the scene being clipped regardless of the camera position and orientation (and it behaves as such when using a singular `PerspectiveCamera`)

### Version

r147

### Device

Desktop

### Browser

Firefox

### OS

Linux

**Comment by Mugen87** [comment]
> In case this camera is an ArrayCamera or an XR session is active, the sub cameras will incorrectly use the projected planes from the parent camera.

That is strange then when debugging, the clipping state configuration does indeed use the sub cameras. I'm referring to the following code section:

https://github.com/mrdoob/three.js/blob/00d426a28005aa4af49eaa0337bf40add6fa3545/src/renderers/WebGLRenderer.js#L1492-L1507

Can you please share a picture of the above scene that shows the expected behavior?

**Comment by Mugen87** [comment]
As a workaround, can you use this approach for now? https://jsfiddle.net/bLo2vnsm/

**Comment by Mugen87** [comment]
That is the problematic line:

https://github.com/mrdoob/three.js/blob/00d426a28005aa4af49eaa0337bf40add6fa3545/src/renderers/WebGLRenderer.js#L985

Global clipping planes use the main camera (in this case `ArrayCamera`) whereas local clipping planes use the sub cameras since they are evaluated at a later point in `setProgram()`.

**Comment by Mugen87** [comment]
It's complicated to move the `init()` call elsewhere since the `_clippingEnabled` flag is required in the early stage of `render()`. We probably have to duplicate the call if `ArrayCamera` is used somewhere in `setProgram()`. Although I'm not yet sure what this means for shadow clipping.

**Comment by mrxz** [comment]
Using local clipping planes as a workaround is do-able in my case, just a bit more work.

> It's complicated to move the init() call elsewhere since the _clippingEnabled flag is required in the early stage of render(). We probably have to duplicate the call if ArrayCamera is used somewhere in setProgram(). Although I'm not yet sure what this means for shadow clipping.

Looking at the code I think it might be possible to keep the `init()` call, but move to projection of the planes to `renderScene()` (so once per (sub)camera). At first I thought they might be needed for shadow rendering, but on closer inspection of  `clipping.beginShadows()` it seems that the global clipping planes are not used in that case. So it won't be a problem if they aren't computed at that point.

Might give it a shot to fix it and open a PR if it works
