### ISSUE TITLE
Implement direct conversion between quaternions and euler angles in any sequence

### ISSUE THREAD

**Issue by evbernardes** [mrdoob/three.js#25275]
### Description

There are two issues with the way Quaternion/Angles conversion are dealt with in three.js:

1. Three.js has two separate methods for the conversion from Euler angles to a quaternion variable:

- A member of the Quaternion class that implements different functions for each non-proper (asymmetric) `order`, like `ZYX`, `ZXY`, etc.
- A function of `Mathutils` that implements different functions for proper (symmetric) sequences, like `ZYZ`, etc.

2. Moreover, the implemented method for converting a quaternion to Euler angles is to first convert it to a rotation Matrix and then to angles, which is not very efficient and only implemented for non-proper sequences.

### Solution

1. For converting Angles to Quaternions, I have two propositions:

- Group everything into `Quaternion.setFromEuler`.
- If it does not make the execution speed higher, then this could all be simply implemented as a multiplication of 3 quaternions constructed from `setFromAxisAngle`.

2. For converting Quaternions to Angles, I propose to implement a whole new method. More info on the **Additional context** section

### Alternatives

I would implement it myself, but I am not a `JavaScript` developer and this would probably be a quick fix for someone familiar with both `JavaScript` and `three.js`.

### Additional context

I recently published an article about a direct formula for the conversion between a quaternion variable to Euler angles in any sequence, which can be read [here](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0276302) (Open Access).

Compared to either having 12 separate formulas (or 24, taking into account both intrinsic and extrinsic rotations) or using the well known quaternion-to-matrix-to-euler method, this has 3 main advantages: 

1. Numerically, it is up to 30 times faster than the previous quaternion-to-matrix-to-euler method (used both originally in `SciPy` and in `transforms3d`, for example).
2. It is a lot simpler to implement, debug and maintain than both methods.
3. It provides simple formulas that can be used for theorerical work.

Because of points 1 and 2, it has already been merged into [Scipy](https://github.com/scipy/scipy/pull/17392). Because point 3, it has also been merged into [SymPy](https://github.com/sympy/sympy/pull/24358).

These Python implementations are (probably) very easily translatable to JavaScript.

**Comment by evbernardes** [comment]
If someone is interested in implementing this, I propose to add this helper function in `MathUtils.js`:
```JavaScript
function get_axes( order ){
    if (!(typeof order === 'string' || order instanceof String)){
        throw new Error( 'Order must be a string.' );
    }

    if (order.length != 3){
        throw new Error( 'Order must have a length of 3.' );
    }

    if (order != order.toUpperCase()){
        throw new Error( 'Order must be an uppercase string.' );
    }

    if (i == j || j == k){
        throw new Error( 'Consecutive axes must be different.' );
    }

    i = order.charCodeAt(0) - 'X'.charCodeAt(0);
    j = order.charCodeAt(1) - 'X'.charCodeAt(0);
    k = order.charCodeAt(2) - 'X'.charCodeAt(0);

    // check if sequence are equivalent to Proper Euler angles
    symmetric = i == k; 
    if (symmetric) {
        k = 3 - i - j;
    }

    parity = (k - j) * (j - i) * (i - k) / 2;

    return [i, j, k, parity, symmetric];
}
```

And then, the implementation of the Quaternion to Euler conversion is probably something like this (if my JavaScript knowledge is correct), to be put into `Euler.js`:
```JavaScript
        // Based on: Bernardes E, Viollet S (2022) Quaternion to Euler angles conversion: 
	// A direct, general and computationally efficient method. PLoS ONE 17(11): e0276302.
	setFromQuaternionDirect( q, order, update ){

		axes = MathUtils.get_axes( order );
		i = axes[0];
		j = axes[1];
		k = axes[2];
		parity = axes[3];
		symmetric = axes[4];

		v = [q.x, q.y, q.z]
		if (symmetric) {
			a = q.w;
			b = v[i];
			c = v[j];
			d = v[k] * parity;
		} else {
			a = q.w - v[j];
			b = v[i] + v[k] * parity;
			c = v[j] + q.w;
			d = v[k] * parity - q[i];
		}

		angles = [0, 0, 0];

		// middle angle is always easy
		angles[1] = Math.atan2(Math.hypot(c, d), Math.hypot(a, b));

		half_sum = Math.atan2(b, a);
		half_diff = Math.atan2(d, c);

		// check if the case is degenerate
		eps = 10E-7
		if (Math.abs(angles[1]) < eps){
			unsafe = 1;
		} else if (Math.abs(angles[1] - Math.PI) < eps){
			unsafe = 2;
		} else {
			unsafe = 0;
		}

		if (unsafe == 0) {
			angles[2] = half_sum - half_diff
			angles[0] = half_sum + half_diff
		} else { // degenerate cases
			angles[2] = 0;
			if (unsafe == 1) {
				angles[0] = 2 * half_sum;
			} else {
				angles[0] = 2 * half_diff;
			}
		}

		if (!symmetric){
			angles[0] *= parity;
			angles[1] -= Math.PI / 2;
		}

		for (let i = 0; i < 3; i++) {
			if (angles[i] < -Math.PI) {
				angles[i] += 2 * Math.PI;
			} else if (angles[i] > Math.PI) {
				angles[i] -= 2 * Math.PI;
			}
		} 

		this._x = angles[0];
		this._y = angles[1];
		this._z = angles[2];
	}
```
The function `get_axes` could also be used in every other related function.

**Comment by evbernardes** [comment]
For the general conversion from Euler to Quaternion, this to `MathUtils.js`:
```JavaScript
function elementary_unit_vector( axis ){
	switch (axis) {
		case 'X':
			return Vector3(x = 1);
			break;
		case 'Y':
			return Vector3(y = 1);
			break;
		case 'Z':
			return Vector3(z = 1);
			break;
		default:
			throw new Error( 'axis must be X, Y or Z.' );
	  }
}
```
And the conversion, inside of `Quaternion.js`:
```JavaScript
	setFromEuler( euler, update ) {
		const x = euler._x, y = euler._y, z = euler._z
		const ux = MathUtils.elementary_unit_vector(order[0]);
		const uy = MathUtils.elementary_unit_vector(order[1]);
		const uz = MathUtils.elementary_unit_vector(order[2]);
		
		q1 = Quaternion.setFromAxisAngle( ux, x );
		q2 = Quaternion.setFromAxisAngle( uy, y );
		q3 = Quaternion.setFromAxisAngle( uz, z );
		
		this = q1 * q2 * q3;

		if ( update !== false ) this._onChangeCallback();

		return this
	}
```

**Comment by Mugen87** [comment]
Very interesting work! I need to study your publication in more detail though before I can provide feedback. However, it's great to see new innovative work in that area.

**Comment by evbernardes** [comment]
I'm glad you're interested!
Don't hesitate to check the Scipy and Sympy implementations if you're also a Python dev, these all have implemented unit tests.

**Comment by WestLangley** [comment]
Closing. see https://github.com/mrdoob/three.js/pull/25277#issuecomment-1432413893.
