### ISSUE TITLE
PBR fragment shader not compiled in > r144 for glass demo

### ISSUE THREAD

**Issue by andreasplesch** [mrdoob/three.js#25274]
### Description

Updating this popular glass tutorial  https://tympanus.net/codrops/2021/10/27/creating-the-effect-of-transparent-glass-and-plastic-in-three-js/ to latest Threejs, I noticed that the fragment shader could not be compiled with versions > r144. The error message is:
```
THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Program Info Log: Fragment shader is not compiled.

FRAGMENT

ERROR: 0:882: 'isinf' : no matching overloaded function found
ERROR: 0:882: '' : boolean expression expected

  877: 		#else
  878: 			return texture2D( transmissionSamplerMap, fragCoord.xy, framebufferLod );
  879: 		#endif
  880: 	}
  881: 	vec3 applyVolumeAttenuation( const in vec3 radiance, const in float transmissionDistance, const in vec3 attenuationColor, const in float attenuationDistance ) {
> 882: 		if ( isinf( attenuationDistance ) ) {
  883: 			return radiance;
  884: 		} else {
  885: 			vec3 attenuationCoefficient = -log( attenuationColor ) / attenuationDistance;
  886: 			vec3 transmittance = exp( - attenuationCoefficient * transmissionDistance );			return transmittance * radiance;
  887: 		}
  888: 	}
```
isinf() is not available. It still works with < r144, eg. could be a regression or a problem with the scene or packaging which was surfaced.

not working: https://codesandbox.io/s/glass-r145-p93p77
working: https://codesandbox.io/s/glass-r144-21ngqn

Here is the git blame page for the perhaps problematic shader line: https://github.com/mrdoob/three.js/blame/c08bcce99a34a0668a96a2e75bb262e74bae7b64/src/renderers/shaders/ShaderChunk/transmission_pars_fragment.glsl.js#L74

tested on Linux, latest Chrome, QuadroP4000 and
on Windows10, latest Chrome, Intel Laptop gfx

### Reproduction steps

1.  https://codesandbox.io/s/glass-r145-p93p77
2.  look at console, notice error
3. compare with https://codesandbox.io/s/glass-r144-21ngqn

### Code

```js
new MeshPhysicalMaterial()
```

### Live example

* [code sandbox r148 not working](https://codesandbox.io/s/glass-r148-4t2jee)
* [code sandbox r145 not working](https://codesandbox.io/s/glass-r145-p93p77)
* [code sandbox r144 working](https://codesandbox.io/s/glass-r144-21ngqn)

### Version

r148

### Device

Desktop

### OS

Windows, Linux

**Comment by andreasplesch** [comment]
The recent PR which introduced the shader line: https://github.com/mrdoob/three.js/pull/24622

**Comment by LeviPesin** [comment]
Can reproduce the issue on Android, Samsung Internet.

**Comment by Mugen87** [comment]
Your codesandbox passes a custom WebGL 1 context to the renderer. However, the shader only works with WebGL 2. Since we have slowly started to deprecate features for WebGL 1, we won't apply a refactoring here. Just remove the `context` parameter from the `WebGLRenderer` ctor call and the shader compilation error goes away.

Besides, `toneMappingExposure` is no WebGL context parameter.

**Comment by andreasplesch** [comment]
Ah, just discovered this myself. I had to find out that isInf became available only with WebGL 2 and did not expect the original demo to use WebGL 1. Thanks for taking a look !

https://codesandbox.io/s/glass-r148-webgl2-g4u007?file=/src/index.js is fixed that way.
