### ISSUE TITLE
Can not use TextureLoader in a module web worker

### ISSUE THREAD

**Issue by sunzhuo** [mrdoob/three.js#25271]
### Description

When I use THREE and TextureLoader in a module web worker, It prompts the following error:
but the ImageBitmapLoader can be used.

```
Uncaught (in promise) ReferenceError: document is not defined
    at createElementNS (three.module.js:1463:2)
    at ImageLoader.load (three.module.js:40755:17)
    at TextureLoader.load (three.module.js:40979:10)
    at self.Init (worker.module.js:112:45)
    at self.onmessage (worker.module.js:217:41)
```

### Reproduction steps

1. Create a web worker with {type : 'module'}
2. Import threejs in the worker and transfer the offcanvas to the renderer
3. Use TextureLoader to load an image file

### Code

```js
const texture = new THREE.ImageBitmapLoader().load( '../res/earth_without_clouds_4k.jpg' );
```

### Live example

no live example

### Version

r148, r149

**Comment by Mugen87** [comment]
Yes, this is known. You can't use `TextureLoader` in a worker context. Use `ImageBitmapLoader` instead.
