### ISSUE TITLE
Error when changing WebGLRenderTarget.samples from 0

### ISSUE THREAD

**Issue by r-flash** [mrdoob/three.js#25278]
### Description

If we render onto a render target with its `samples` property set to 0 and then change the property to anything non-zero, subsequent rendering fails with the error message `TypeError: WeakMap key must be an object, got r` (or similar, telling us that the key - variable `framebuffer` - is undefined).

If the first render onto the render target happens with non-zero `samples`, we can subsequently switch between zero and non-zero values without triggering the error.

### Reproduction steps

1. Create a new WebGLRenderTarget `rt` and leave the `samples` property at the default 0.
2. Call `renderer.setRenderTarget(rt)` and render.
3. Change the `rt.samples` property to 4.
4. Repeat step 2 and observe the error.

### Code

```js
const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera();
const renderer = new THREE.WebGLRenderer();
const renderTarget = new THREE.WebGLRenderTarget();

renderer.setRenderTarget(renderTarget);
renderer.render(scene, camera);

renderTarget.samples = 4;
renderer.setRenderTarget(renderTarget);
renderer.render(scene, camera); // error
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/5c4s3kuz/) (see console output)

### Version

r148

**Comment by Mugen87** [comment]
It is not intended to change the `samples` value once the render target has been in use. Call `dispose()` and create a new render taret.

**Comment by r-flash** [comment]
Thank you, this makes sense and works without problem. A note for anyone using EffectComposer like me: there is a handy method `effectComposer.reset(renderTarget)` which calls `dispose` on the currently used internal render targets and resets them based on the provided one. Simply create a new render target with the required params and this method handles the rest.
