### ISSUE TITLE
PropertyBinding falls back to root node for incorrect paths/nodes

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#25286]
### Description

I'm not sure if this is/was intended, but we've run into a number of cases where slightly wrong animation property names result in horribly broken results, because instead of ignoring incorrect paths three falls back to applying everything to the root node (often resulting in chaos).

If that's not intended, I can take a look at making a PR.

Maybe someone knows why this is used in a number of places (falling back to the root if parsing the path fails):
```
targetObject = PropertyBinding.findNode( this.rootNode, parsedPath.nodeName ) || this.rootNode;
```

### Reproduction steps

1. create a track with a wrong/incorrect path to a child node that animates position
2. play a clip with that track
3. note the parent getting animated instead of the expected result (error logged, nothing happens)

### Code

```js
    mesh.name = "Mesh1";
    mesh2.name = "Mesh2";
    mesh.add(mesh2);

    // this is problematic: the name doesn't match, but instead of being ignored the track gets applied to the root
    const trackName = "Mesh_2.position";
    const track = new THREE.VectorKeyframeTrack(
				trackName,
				[0.0, 1.0, 2.0, 3.0, 4.0],
				[0,0,0,1,0,0,1,1,0,1,1,1,0,0,0],
				THREE.InterpolateLinear
    );

    mixer = new THREE.AnimationMixer( mesh );
    const tracks = [ track ];		
    const clip = new THREE.AnimationClip( "animationclip", undefined, tracks );
    const action = mixer.clipAction( clip );
    action.play();
```

### Live example

https://jsfiddle.net/nqyf79mp/31/

### Version

dev

**Comment by Mugen87** [comment]
The fallback to the root node is present since the new animation system was added via #6934. The specific commit which add `|| this.rootNode` in the constructor was  4985ed03dbfa59fb722af18fa66f4c347d034ae9. So this code was added on purpose. (BTW: The fallback is also used in `bind()` but it is not relevant for the above example).

I'm not sure if there is a use case that breaks if the fallback is removed and an error throw/logged instead. I'm not sure it's worth to find this out since you can easily use `PropertyBinding.findNode()` on app level to verify your track names and act accordingly.

**Comment by hybridherbst** [comment]
I think the behaviour with `|| this.rootNode` is always undesired. Is there a known usecase where this is needed? Could also argue the opposite: on app level, one could decide to use `PropertyBinding.findNode` and then assign the root node if something isn't working as expected.

I ran into this case with files using `KHR_animation_pointer` which use way more complex propery binding (as seen here: #24108). 

Trying to sanitize each and every animation track before playing it on each and every asset doesn't sound like something that should happen on app level to me...

**Comment by Mugen87** [comment]
> . Is there a known usecase where this is needed?

I've searched the history again and couldn't find something. 

When we log a warning, it's at least easy to relate a potential breakage to the removal of the fallback. It's also easy to add the code back if necessary. And we finally know its purpose and can document it (or work on an alternative solution).

So I guess I'm fine with a PR.

**Comment by donmccurdy** [comment]
I think there might be important cases where an _empty_ track name (e.g. `.rotation`) should be resolved to the root node. If the name is present, but incorrect, then I agree it probably doesn't need to fall back to the root, and could throw or log an error instead.

**Comment by hybridherbst** [comment]
@donmccurdy I believe that case is handled explicitly already - empty nodeName (in a couple of combinations) is targeted at root: 
https://github.com/mrdoob/three.js/blob/dev/src/animation/PropertyBinding.js#L196-L202
