### ISSUE TITLE
dynamic cubemap mapping incorrect for transmission > 0 with PBR material

### ISSUE THREAD

**Issue by andreasplesch** [mrdoob/three.js#25281]
### Description

I am trying to use a dynamic cubemap with a PBR material which has also transmission > 0. When I combine the [transmission example](https://threejs.org/examples/?q=tran#webgl_materials_physical_transmission) with the [dynamic cubemap example](https://threejs.org/examples/?q=cubema#webgl_materials_cubemap_dynamic)

here

[transmission_plus_cubemap - CodeSandbox](https://codesandbox.io/s/transmission-plus-cubemap-k80cnd)

it does not quite work out. There is dynamic reflection shown on the transmissive sphere but the texture mapping is quite off.

Interestingly, for zero transmission the shading mode changes and the dynamic cubemap is shown correctly.

This may hint that only minor changes may be needed, either to how the cubemap is used or perhaps the texture mapping application.

Please also see the forum thread at https://discourse.threejs.org/t/pbr-transmission-with-dynamic-cubemaps-incorrect/46789 which kindly suggested to file this issue in addition.

### Reproduction steps

1. compose a PBR material with transmission > 0 and envmap set to a cubemap texture
2. render
3. observe incorrect mapping of envmap

### Code

```js

const material = new THREE.MeshPhysicalMaterial({
          color: params.color,
          metalness: params.metalness,
          roughness: params.roughness,
          ior: params.ior,
          alphaMap: texture,
          //envMap: hdrEquirect,
          envMap: cubeRenderTarget.texture,
          //envMap: pmremTarget.texture,
          envMapIntensity: params.envMapIntensity,
          transmission: 1, // params.transmission, // use material.transmission for glass materials
          specularIntensity: params.specularIntensity,
          specularColor: params.specularColor,
          opacity: params.opacity,
          side: THREE.DoubleSide,
          transparent: true
        });


```

### Live example

* [transmission_plus_cubemap - CodeSandbox](https://codesandbox.io/s/transmission-plus-cubemap-k80cnd)

### Screenshots

![image](https://user-images.githubusercontent.com/6171115/212347015-94250070-be62-4cde-a982-a2f958d5d552.png)

The dynamic cubemap used as envmap is circled. It should not be restricted to the small square area but should cover the complete, striped sphere. Setting transmission to 0 shows the correct mapping for the cubemap. Perhaps the cubemap is using the same UVs as the texture internally used for the transmission if there is transmission ?

### Version

r148

### Device

Desktop

### Browser

Chrome

### OS

Windows, Linux

**Comment by andreasplesch** [comment]
Anything I can do to help here ?

**Comment by WestLangley** [comment]
For what it is worth, here is how to make the problem go away:

```js
mesh.visible = false;
cubeCamera.update( renderer, scene );
mesh.visible = true;
```

https://codesandbox.io/s/transmission-plus-cubemap-forked-biy1jm
