### ISSUE TITLE
An option to suppress context creation error messages.

### ISSUE THREAD

**Issue by jespertheend** [mrdoob/three.js#25292]
### Description

I am creating a `WebGLRenderer` with the following options: `{antialias: true, powerPreference: "high-performance"}`. If this fails because the device has not support for powerPreferences, I `try` `catch` the error and try again with different options:
```js
let renderer;
try {
	renderer = new WebGLRenderer({ antialias: true, powerPreference: "high-performance" });
} catch (e) {
	try {
		renderer = new WebGLRenderer({ antialias: true, alpha: true });
	} catch (e) {
		try {
			renderer = new WebGLRenderer({ antialias: false, alpha: true });
		} catch (e) {
			renderer = new WebGLRenderer();
		}
	}
}
```

However, since #24091 threejs started logging context creation errors, and now my console always contains a bunch of errors on Ubuntu since it doesn't support the `powerPreference` option.

### Solution

An option to suppress these error messages would be nice. I don't really mind if three.js downgrades to WebGL1 internally.

### Alternatives

Escalating the error to a thrown error might be even better, since it would allow you to catch it and handle it accordingly.

**Comment by Mugen87** [comment]
Instead of introducing more configuration options, this use case can handled differently without modifying the library. I suggest you create the context on app level and then pass it to the constructor of `WebGLRenderer`. In this way, you have full control over the context creation process and the respective error handling.

**Comment by jespertheend** [comment]
Thanks @Mugen87! Sounds like a good idea.
