### ISSUE TITLE
Stretched face on Android Chrome (jeelizFaceFilter)

### ISSUE THREAD

**Issue by marcusx2** [mrdoob/three.js#25298]
### Description

If you try out [this example](https://jeeliz.com/demos/faceFilter/demos/threejs/gltf_fullScreen/) on your Android Chrome, your face will be stretched vertically. I was going to report this on the [jeeliz repository](https://github.com/jeeliz/jeelizFaceFilter) but the _Get started_ specifically instructed to report bugs related to threejs here...The problem probably [lies on this file](https://github.com/jeeliz/jeelizFaceFilter/blob/master/helpers/JeelizThreeHelper.js).

The threejs [library used](https://github.com/jeeliz/jeelizFaceFilter/tree/master/libs/three/v112).

### Live example

https://jeeliz.com/demos/faceFilter/demos/threejs/gltf_fullScreen/

### Version

112

### Device

Mobile

### Browser

Chrome

### OS

Android

**Comment by Mugen87** [comment]
> but the Get started specifically instructed to report bugs related to threejs here.

How is this related to `three.js`? Sorry but delegating issues like that isn't right. This needs to be investigated in the jeeliz repository. Only when an issue can be reproduces with a simple `three.js` live demo (https://jsfiddle.net/g3atw6k5/) without any dependencies it's okay to open an issue here.

**Comment by marcusx2** [comment]
@Mugen87 It's related to three.js becaue the jeelizFaceFilter library is platform agnostic, and the webcam feed is sent to a canvas controlled by threejs. I'm guessing the threejs examples were made by the threejs team? It's the only explanation I have why the _Get started_ says that threejs stuff should be here and not in their repo. You can try creating an issue there and you will see the message. If I create the issue there the repo owner will probably just close my issue telling me to create the issue here...

**Comment by Mugen87** [comment]
Sorry but then jeeliz guidelines are highly questionable. We can't support third-party libraries like suggested. We simply don't have that kind of bandwidth.  It's just fair to ask users to reproduce an issue with a simple, isolated code example.

**Comment by Mugen87** [comment]
> I'm guessing the threejs examples were made by the threejs team?

BTW: No, they were not. AFAIK, nobody from the collaborators in involved in jeeliz.

**Comment by mrdoob** [comment]
I'm sure @xavierjs will be happy to help. But please, do it so in the jeelizFaceFilter repo.
