### ISSUE TITLE
Can't find variable: HTMLElement

### ISSUE THREAD

**Issue by obasille** [mrdoob/three.js#25291]
### Description

I've stumbled into a strange issue, using Three in a Expo (React Native) project causes `HTMLElement` to become undefined.

I don't use of `HTMLElement` since I'm targeting mobile only, but some packages that I'm using do and as soon I'm starting to use Three I'm getting this error:
```
ReferenceError: Can't find variable: HTMLElement
```

For example some packages might run this code `ref instanceof HTMLElement` which normally works fine in a Expo (React Native) project, until you start using Three.

I realize that is not the place to talk about Expo / React Native support, but since the issue is not about some rendering problem with React Native but rather with Three seemingly modifying the global context (`HTMLElement` becoming undefined), I'm hoping that people familiar with Three source code will be able to help me understand what's happening.

Any help would be greatly appreciated. thank you!

### Reproduction steps

1. Create a new Expo project: `npx create-expo-app myapp`
2. Add Three: `npm i three@0.145.0 expo-three expo-gl`
3. Modify App.jsx (or .tsx) to import Three and make a call like `new THREE.Scene();`
4. Run with ExpoGo: `npm start`

=> The app throws an error before it has a chance to render the UI: `Can't find variable: HTMLElement`

Note: the same issue happens with r148

### Code

```js
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import * as THREE from 'three';
import { useEffect } from 'react';

export default function App() {
  useEffect(() => {
    new THREE.Scene(); // Comment this line, remove the import and it works!
    console.log(HTMLElement); // Throws "ReferenceError: Can't find variable: HTMLElement"
  });
  return (
    <View style={styles.container}>
      <Text>Open up App.jsx to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Note:
`import * as THREE from 'three';` may be replaced by `import { THREE } from 'expo-three';` but the issue will persist.

### Live example

Unfortunately Expo Snack doesn't work with Three so I can't provide a live example.

### Version

r145, r148

### Device

Mobile

### Browser

Safari

### OS

Android, iOS

**Comment by LeviPesin** [comment]
Three.js does not modify HTMLElement, so this is not a bug in Three.js. I suggest that you report this bug to either Expo or `expo-three`.

**Comment by obasille** [comment]
Thank you for your reply!
I don't see why importing Three.js has anything to do with the disappearance of `HTMLElement` but the strange thing is that I have the issue even if only import Three.
In the example above I'm not using `expo-three` at all. In fact I still have the issue even if I don't have `expo-three` in `package.json`, just Three.js.

**Comment by Mugen87** [comment]
Please post at the [forum](https://discourse.threejs.org/) first. If this is really a `three.js`,  this issue can be reopened. However, it's important to demonstrate then it _without_ any dependencies. We had this problem way to often in the past that a supposed `three.js` bug was actually a problem in the app or a third-party library.

**Comment by obasille** [comment]
My apologies, the issue indeed only happens with expo-three. I though it was also happening with just ThreeJS but that was probably caused by the fact I didn't clear the cache when switching from importing expo-three to just three.

**Comment by obasille** [comment]
For anyone who stumble on this problem, I found the root cause:

`expo-three` is importing `@expo/browser-polyfill` which changes the user agent to "chrome" => `navigator.userAgent = 'chrome'`.

Some libraries that target both the web and React Native check the user agent before using `HTMLElement`. In a normal React Native context the user agent is undefined and those libraries don't use any web specific classes. But once the user agent is changed to "chrome", the library will think it's running in a web environment (and in my case it will use `HTMLElement`).

Note : I was wrong to think that `HTMLElement` should exist in React Native.
