### ISSUE TITLE
导入模型问题

### ISSUE THREAD

**Issue by zhangda-cpu** [mrdoob/three.js#25294]
### Description

载入fbx文件格式模型,会出现骨骼点旋转,后续又测试了glb格式进行导入,又会造成贴图反转问题

### Reproduction steps

1.导入模型渲染后就会出现

### Code

```js
// code goes here
```
1

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)
1

### Screenshots

![lQLPJv_oM5L-YCzNA27NAomwKvtdwkr5bzQDszMqXICfAA_649_878](https://user-images.githubusercontent.com/75289735/212817825-46691c46-7331-456d-8865-8b45530d7da8.png)
![lQLPJxJZY4BUABjNAsHNAjiwqCblxXvF3GMDuVMrD0BOAA_568_705](https://user-images.githubusercontent.com/75289735/212817836-a2536b1f-38b6-4c06-8727-ce80fd520e8b.png)

### Version

0.143.0

### Device

Desktop

### Browser

Chrome

### OS

Android

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

Besides, please write your post here and at the forum in English. Use a translator if necessary.
