### ISSUE TITLE
GLTFExporter: Missing required padding on integer vertex attributes

### ISSUE THREAD

**Issue by rossng** [mrdoob/three.js#25309]
### Description

The glTF 2.0 standard states that:

> For performance and compatibility reasons, each element of a vertex attribute MUST be aligned to 4-byte boundaries inside a bufferView (i.e., accessor.byteOffset and bufferView.byteStride MUST be multiples of 4).

However, three.js - under some circumstances - creates glTF files containing a `byteStride` that is not a multiple of 4.

This happens because of the [following line](https://github.com/mrdoob/three.js/blob/03349e98aa1f57a97433c0a3f17697594fdc0997/examples/jsm/exporters/GLTFExporter.js#L930):

```
bufferViewDef.byteStride = attribute.itemSize * componentSize;
```

For example, you might decide to use single-byte integers for UV coordinates. So each item might be an unsigned byte (and thus have an `itemSize` of 1) and the `componentSize` be 2, leading to an invalid `byteStride` of 1*2 = 2.

### Reproduction steps

1. Generate an invalid glTF using the example code/jsfiddle below
2. Upload it to the [glTF validator](https://github.khronos.org/glTF-Validator/) to see how it is broken

### Code

```js
const geom = new THREE.BufferGeometry()
geom.setAttribute(
  'position',
  new THREE.BufferAttribute(new Float32Array([0, 0, 0, 1, 0, 0, 0, 1, 0]), 3)
)
geom.setAttribute('uv', new THREE.BufferAttribute(new Uint8Array([0, 0, 1, 0, 0, 1]), 2))

const mesh = new THREE.Mesh(geom)

const exporter = new GLTFExporter()
exporter.parse(
  mesh,
  data => {
    const file = new File([JSON.stringify(data)], "mesh.gltf")
    const a = document.createElement('a')
    a.href = URL.createObjectURL(file)
    a.download = file.name
    document.body.appendChild(a)
    a.click()
  },
  err => {
  },
  { binary: false }
)
```

### Live example

* [jsfiddle-latest-release - example gltf creation](https://jsfiddle.net/4nkagz1p/)

### Version

r148

### Device

Desktop

### Browser

Firefox

### OS

MacOS

**Comment by donmccurdy** [comment]
Agreed — GLTFExporter should be padding these vertex attributes to the required stride.

Related:

- https://github.com/mrdoob/three.js/issues/20474
- https://github.com/mrdoob/three.js/pull/25297

**Comment by grzesiekmq** [comment]
I can't find test/s for GLTFExporter, please let me know about it

**Comment by donmccurdy** [comment]
@grzesiekmq if you mean unit tests, files in `./examples/jsm` do not have them. But you can find an example for testing here: https://threejs.org/examples/?q=export#misc_exporter_gltf.
