### ISSUE TITLE
strict mode conflict

### ISSUE THREAD

**Issue by kemp-ke** [mrdoob/three.js#25306]
### Description

Hi, 
Three.js will be blocked as I enabled Content Security Policy which is needed. From the code in the file three.js of release 125, I can see the following comment:
**// This module should not be running in strict mode, so the above**

But in fact it is enabled by three.js itself as I can see the following code:

**}(this, (function (exports) { 'use strict';**

So three.js 125 will not work if CSP is enabled. 

Best Regards

### Reproduction steps

1.Enable CSP by adding Content-Security-Policy http header. This will block "eval", "Function" and so on.
2.Using three.js 125 in the page

### Code

```js
// code goes here
```
	try {
		regeneratorRuntime = runtime;
	} catch (accidentalStrictMode) {

### Live example

No live example.

### Version

125

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
> From the code in the file three.js of release 125, I can see the following comment:

We don't support old `three.js` releases. The mentioned comment is not present in `r148`.

And yes, the UMD builds run in strict mode yes as well as all ES6 modules. That is the expected behavior.

**Comment by kemp-ke** [comment]
> > From the code in the file three.js of release 125, I can see the following comment:
> 
> We don't support old `three.js` releases. The mentioned comment is not present in `r148`.
> 
> And yes, the UMD builds run in strict mode yes as well as all ES6 modules (they do that automatically). That is the expected behavior.
> 
> I'm afraid the issue you are describing is not clear. It would probably be best to demonstrate the issue with a live example.

Thanks for your quick response. The r125 doesn't work for CSP enabled page. I have tried r148 and it works well.
