### ISSUE TITLE
GLTF hierarchy not preserved since 0.148.0

### ISSUE THREAD

**Issue by sgarnotel** [mrdoob/three.js#25323]
### Description

I have a gltf file with the current nodes hierarchy:
```
{
  "nodes": [
    { "mesh": 0 },
    { "mesh": 1 },
    { "mesh": 2 },
    { "mesh": 3 },
    { "mesh": 4 },
    { "mesh": 5 },
    { "mesh": 6 },
    { "mesh": 7 },
    { "mesh": 8 },
    { "mesh": 9 },
    { "mesh": 10 },
    { "mesh": 11 },
    { "mesh": 12 },
    { "mesh": 13 },
    {
      "children": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
      "extras": { "label": 1, "uuid": "89F50827-D874-4599-BDCA-BE1955EC9CA6" },
      "name": "Solid 1"
    },
    { "mesh": 14 },
    { "mesh": 15 },
    { "mesh": 16 },
    { "mesh": 17 },
    { "mesh": 18 },
    { "mesh": 19 },
    {
      "children": [15, 16, 17, 18, 19, 20],
      "extras": { "label": 2, "uuid": "88BD20AC-4A70-432C-8500-4FD15E81C93D" },
      "name": "Solid 2"
    }
  ]
}
```
But when I load it using three 0.148.0, the node hierarchy is not respected:
```
{
  "...": "...",
  "children": [
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Object3D",
      "//": "Empty children here, but previous meshes must be here",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Mesh",
      "...": "..."
    },
    {
      "type": "Object3D",
      "//": "Empty children here, but previous meshes must be here",
      "...": "..."
    }
  ]
}
```
It works fine with three 0.147.0.

### Reproduction steps

1. Just load the gltf file using `GLTFLoader`

### Code

```js
const gltf: GLTF = await new Promise((resolve, reject) => {
      loader.load(
        url,
        (glb) => {
          resolve(glb)
        },
        () => undefined,
        (err) => reject(err)
      )
})

const scene = gltf.scene
```

### Live example

[jsfiddle](https://jsfiddle.net/r70f59ay/10/)

### Version

r148

### Device

Desktop

### Browser

Chrome

### OS

Linux

**Comment by donmccurdy** [comment]
Copying the file here for easier review, with the "nodes" entry extracted:

[magnet.glb.zip](https://github.com/mrdoob/three.js/files/10481016/magnet.glb.zip)

<details>
<summary>nodes</summary>

```
  "nodes": [
    {
      "mesh": 0
    },
    {
      "mesh": 1
    },
    {
      "mesh": 2
    },
    {
      "mesh": 3
    },
    {
      "mesh": 4
    },
    {
      "mesh": 5
    },
    {
      "mesh": 6
    },
    {
      "mesh": 7
    },
    {
      "mesh": 8
    },
    {
      "mesh": 9
    },
    {
      "mesh": 10
    },
    {
      "mesh": 11
    },
    {
      "mesh": 12
    },
    {
      "mesh": 13
    },
    {
      "name": "Solid 1",
      "extras": {
        "label": 1,
        "uuid": "89F50827-D874-4599-BDCA-BE1955EC9CA6"
      }
    },
    {
      "mesh": 14
    },
    {
      "mesh": 15
    },
    {
      "mesh": 16
    },
    {
      "mesh": 17
    },
    {
      "mesh": 18
    },
    {
      "mesh": 19
    },
    {
      "name": "Solid 2",
      "extras": {
        "label": 2,
        "uuid": "88BD20AC-4A70-432C-8500-4FD15E81C93D"
      }
    }
  ],
```

</details>

The file doesn't seem to contain the nesting you were expecting to find, those marked nodes do not have children. Is it possible the file itself has changed?

**Comment by donmccurdy** [comment]
Hm — more detail, I created that snippet by converting the file from .glb to .gltf with glTF Transform. Usually that wouldn't result in any other changes, but there are some serious validation errors on this file, so all bets might be off here. From https://github.khronos.org/glTF-Validator/, you can see a lot of errors with code `SCENE_NON_ROOT_NODE`. This means that the marked nodes are children of _both_ the scene, and of another node. Neither three.js nor the glTF specification allow nodes to have multiple parents, and it's likely to be the cause of the errors you see here.  That would indicate a bug in the software producing this file — the meshes may be reused, but the nodes must not.

**Comment by sgarnotel** [comment]
Yes, I have seen for a long time the validation errors on my glb files.
Is the new implementation of GLTFLoader more compliant with the GLTF format ?

So, I will have a look on the software that produce the GLB file, thanks.

**Comment by donmccurdy** [comment]
We made some changes related to scene graph loading that were intended as cleanup and optimization, but also likely fixed https://github.com/mrdoob/three.js/issues/18774, see more changes here:

https://github.com/mrdoob/three.js/pulls?q=is:pr+GLTFLoader+is:closed+milestone:r148+in:title

However, since a node is not supposed to have two parents, there isn't really any "correct" way to resolve that situation in GLTFLoader, choosing between parent A and parent B. I think the result must have inadvertently changed here as a result.

**Comment by sgarnotel** [comment]
Just for information, once the GLTF file correctly formatted, it works well. Thank you again
