### ISSUE TITLE
multiMaterial error

### ISSUE THREAD

**Issue by N3GIS** [mrdoob/three.js#25321]
### Description

**Why was MultiMaterial support removed after 143 ? removal causes MultiMaterial to fail to load**
![image](https://user-images.githubusercontent.com/7942057/213990166-b9f24d62-cc94-44b8-afd1-f7b78efe3e34.png)

### Reproduction steps

1. I use version 143 or above, and I will report an error when importing MultiMaterial in the editor

### Code

```json
// scene Json file
{"metadata":{"version":"3.0.0","type":"Object","generator":"zhouzf"},"materials":[{"materials":[{"normalMapType":0,"lightMapIntensity":0,"color":"0x2bf800","shininess":0,"reflectivity":0,"emissive":"0x000000","emissiveIntensity":1,"bumpScale":0,"roughness":0.5,"metalness":0,"uuid":"FAFA0030-918B-4AC9-9489-3502B806CE90","name":"Mat_1","type":"MeshStandardMaterial","side":0,"opacity":1,"transparent":false,"alphaTest":0,"userData":{"useHDRLightingMap":false}},{"normalMapType":0,"lightMapIntensity":0,"color":"0xfdbf01","shininess":0,"reflectivity":0,"emissive":"0x000000","emissiveIntensity":1,"bumpScale":0,"roughness":0.5,"metalness":0,"uuid":"74F44F90-760F-460B-B1E0-B7687A5F057B","name":"Mat_2","type":"MeshStandardMaterial","side":0,"opacity":1,"transparent":false,"alphaTest":0,"userData":{"useHDRLightingMap":false}}],"uuid":"D97F26AA-3B03-4010-B119-10153C1F680C","type":"MultiMaterial","side":0,"opacity":0,"transparent":false,"alphaTest":0,"userData":{"useHDRLightingMap":false}}],"geometries":[{"data":{"index":{"itemSize":1,"type":"Uint16Array","array":[0,2,1,1,2,3,1,3,4,4,3,5,6,8,7,7,8,9,7,9,10,10,9,11]},"groups":[{"start":0,"materialIndex":0,"count":12},{"start":12,"materialIndex":1,"count":12}],"attributes":{"position":{"itemSize":3,"type":"Float32Array","array":[-2.3166,0.0001,0,-2.3166,0.0001,-1.6359,0,0.0001,0,0,0.0001,-1.6359,-2.3166,0.0001,-3.2718,0,0.0001,-3.2718,-4.6332,0.0001,0,-4.6332,0.0001,-1.6359,-2.3166,0.0001,0,-2.3166,0.0001,-1.6359,-4.6332,0.0001,-3.2718,-2.3166,0.0001,-3.2718]},"normal":{"itemSize":3,"type":"Float32Array","array":[0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0]},"color":{"itemSize":3,"type":"Float32Array","array":[]},"uv":{"itemSize":2,"type":"Float32Array","array":[-2.3166,0,-2.3166,1.6359,0,0,0,1.6359,-2.3166,3.2718,0,3.2718,-4.6332,0,-4.6332,1.6359,-2.3166,0,-2.3166,1.6359,-4.6332,3.2718,-2.3166,3.2718]},"uv2":{"itemSize":2,"type":"Float32Array","array":[]}}},"uuid":"1380b4ca-f742-4593-ae24-c21bbe43f104","type":"BufferGeometry"}],"object":{"visible":true,"castShadow":false,"receiveShadow":false,"children":[{"visible":true,"castShadow":false,"receiveShadow":false,"children":[{"visible":true,"geometry":"1380b4ca-f742-4593-ae24-c21bbe43f104","material":"D97F26AA-3B03-4010-B119-10153C1F680C","castShadow":true,"receiveShadow":true,"userdata":{"type":"MeshCollider"},"uuid":"52c67a72-2ec1-47d9-a13e-febca5038065","name":"Plane","type":"Mesh","matrix":[1,0,0,0,0,1,0,0,0,0,1,0,-0.6423,0,0.7597,1]}],"uuid":"a4bde1cd-03a7-42f6-a215-db9d8a2b8ccf","name":"Roots","type":"Object3D","matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]},{"visible":true,"castShadow":false,"receiveShadow":false,"children":[{"color":16774358,"intensity":1,"visible":true,"castShadow":true,"receiveShadow":false,"children":[{"uuid":"bfd373c8-6246-4417-b7a5-d82a96dcb515","name":"LightTarget","type":"Object3D","matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,-10,1]}],"uuid":"188C2956-93A8-40EB-BE3E-C241114D7674","name":"Directional Light","type":"DirectionalLight","matrix":[0.866,0,-0.5,0,-0.383,0.6428,-0.6634,0,0.3214,0.766,0.5567,0,0,3,0,1]}],"uuid":"98168b6f-f604-4254-bc4c-eee6ef715502","name":"Lights","type":"Object3D","matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]},{"fov":60,"aspect":1.451058,"near":0.3,"far":1000,"visible":true,"castShadow":false,"receiveShadow":false,"children":[{"uuid":"68c1ae0d-3f99-4cdf-b9a4-f682179bd055","name":"CameraTarget","type":"Object3D","matrix":[1,0,0,0,0,1,0,0,0,0,1,0,-1.192093E-07,2.384186E-07,-4.177822,1]}],"uuid":"66776B84-DF36-4AEB-8613-9877993E9AA7","name":"Main Camera","type":"PerspectiveCamera","matrix":[-0.9025,0,-0.4307,0,-0.2237,0.8546,0.4686,0,0.3681,0.5193,-0.7713,0,-0.4478,2.1694,-2.1626,1]}],"uuid":"c7f53fd2-157c-4773-bad4-3b8495b95cb8","name":"MulMaterialTest","type":"Scene","matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]},"images":[],"textures":[],"backgroundBlurriness":0}
```

### Screenshots
![image](https://user-images.githubusercontent.com/7942057/213995797-97b9a40e-a49e-4237-8714-cbd265c9b2e6.png)

![image](https://user-images.githubusercontent.com/7942057/213991074-7ec2eb37-e7f7-490f-82d9-462456b3b8d4.png)

### Version

r143、r148

**Comment by N3GIS** [comment]
Below is the JSON file used for testing


{
  "metadata": {
    "version": "3.0.0",
    "type": "Object",
    "generator": "zhouzf"
  },
  "materials": [
    {
      "materials": [
        {
          "normalMapType": 0,
          "lightMapIntensity": 0,
          "color": "0x2bf800",
          "shininess": 0,
          "reflectivity": 0,
          "emissive": "0x000000",
          "emissiveIntensity": 1,
          "bumpScale": 0,
          "roughness": 0.5,
          "metalness": 0,
          "uuid": "FAFA0030-918B-4AC9-9489-3502B806CE90",
          "name": "Mat_1",
          "type": "MeshStandardMaterial",
          "side": 0,
          "opacity": 1,
          "transparent": false,
          "alphaTest": 0,
          "userData": {
            "useHDRLightingMap": false
          }
        },
        {
          "normalMapType": 0,
          "lightMapIntensity": 0,
          "color": "0xfdbf01",
          "shininess": 0,
          "reflectivity": 0,
          "emissive": "0x000000",
          "emissiveIntensity": 1,
          "bumpScale": 0,
          "roughness": 0.5,
          "metalness": 0,
          "uuid": "74F44F90-760F-460B-B1E0-B7687A5F057B",
          "name": "Mat_2",
          "type": "MeshStandardMaterial",
          "side": 0,
          "opacity": 1,
          "transparent": false,
          "alphaTest": 0,
          "userData": {
            "useHDRLightingMap": false
          }
        }
      ],
      "uuid": "D97F26AA-3B03-4010-B119-10153C1F680C",
      "type": "MultiMaterial",
      "side": 0,
      "opacity": 0,
      "transparent": false,
      "alphaTest": 0,
      "userData": {
        "useHDRLightingMap": false
      }
    }
  ],
  "geometries": [
    {
      "data": {
        "index": {
          "itemSize": 1,
          "type": "Uint16Array",
          "array": [
            0,
            2,
            1,
            1,
            2,
            3,
            1,
            3,
            4,
            4,
            3,
            5,
            6,
            8,
            7,
            7,
            8,
            9,
            7,
            9,
            10,
            10,
            9,
            11
          ]
        },
        "groups": [
          {
            "start": 0,
            "materialIndex": 0,
            "count": 12
          },
          {
            "start": 12,
            "materialIndex": 1,
            "count": 12
          }
        ],
        "attributes": {
          "position": {
            "itemSize": 3,
            "type": "Float32Array",
            "array": [
              -2.3166,
              0.0001,
              0,
              -2.3166,
              0.0001,
              -1.6359,
              0,
              0.0001,
              0,
              0,
              0.0001,
              -1.6359,
              -2.3166,
              0.0001,
              -3.2718,
              0,
              0.0001,
              -3.2718,
              -4.6332,
              0.0001,
              0,
              -4.6332,
              0.0001,
              -1.6359,
              -2.3166,
              0.0001,
              0,
              -2.3166,
              0.0001,
              -1.6359,
              -4.6332,
              0.0001,
              -3.2718,
              -2.3166,
              0.0001,
              -3.2718
            ]
          },
          "normal": {
            "itemSize": 3,
            "type": "Float32Array",
            "array": [
              0,
              1,
              0,
              0,
              1,
              0,
              0,
              1,
              0,
              0,
              1,
              0,
              0,
              1,
              0,
              0,
              1,
              0,
              0,
              1,
              0,
              0,
              1,
              0,
              0,
              1,
              0,
              0,
              1,
              0,
              0,
              1,
              0,
              0,
              1,
              0
            ]
          },
          "color": {
            "itemSize": 3,
            "type": "Float32Array",
            "array": [
            ]
          },
          "uv": {
            "itemSize": 2,
            "type": "Float32Array",
            "array": [
              -2.3166,
              0,
              -2.3166,
              1.6359,
              0,
              0,
              0,
              1.6359,
              -2.3166,
              3.2718,
              0,
              3.2718,
              -4.6332,
              0,
              -4.6332,
              1.6359,
              -2.3166,
              0,
              -2.3166,
              1.6359,
              -4.6332,
              3.2718,
              -2.3166,
              3.2718
            ]
          },
          "uv2": {
            "itemSize": 2,
            "type": "Float32Array",
            "array": [
            ]
          }
        }
      },
      "uuid": "1380b4ca-f742-4593-ae24-c21bbe43f104",
      "type": "BufferGeometry"
    }
  ],
  "object": {
    "visible": true,
    "castShadow": false,
    "receiveShadow": false,
    "children": [
      {
        "visible": true,
        "castShadow": false,
        "receiveShadow": false,
        "children": [
          {
            "visible": true,
            "geometry": "1380b4ca-f742-4593-ae24-c21bbe43f104",
            "material": "D97F26AA-3B03-4010-B119-10153C1F680C",
            "castShadow": true,
            "receiveShadow": true,
            "userdata": {
              "type": "MeshCollider"
            },
            "uuid": "52c67a72-2ec1-47d9-a13e-febca5038065",
            "name": "Plane",
            "type": "Mesh",
            "matrix": [
              1,
              0,
              0,
              0,
              0,
              1,
              0,
              0,
              0,
              0,
              1,
              0,
              -0.6423,
              0,
              0.7597,
              1
            ]
          }
        ],
        "uuid": "a4bde1cd-03a7-42f6-a215-db9d8a2b8ccf",
        "name": "Roots",
        "type": "Object3D",
        "matrix": [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ]
      },
      {
        "visible": true,
        "castShadow": false,
        "receiveShadow": false,
        "children": [
          {
            "color": 16774358,
            "intensity": 1,
            "visible": true,
            "castShadow": true,
            "receiveShadow": false,
            "children": [
              {
                "uuid": "bfd373c8-6246-4417-b7a5-d82a96dcb515",
                "name": "LightTarget",
                "type": "Object3D",
                "matrix": [
                  1,
                  0,
                  0,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  -10,
                  1
                ]
              }
            ],
            "uuid": "188C2956-93A8-40EB-BE3E-C241114D7674",
            "name": "Directional Light",
            "type": "DirectionalLight",
            "matrix": [
              0.866,
              0,
              -0.5,
              0,
              -0.383,
              0.6428,
              -0.6634,
              0,
              0.3214,
              0.766,
              0.5567,
              0,
              0,
              3,
              0,
              1
            ]
          }
        ],
        "uuid": "98168b6f-f604-4254-bc4c-eee6ef715502",
        "name": "Lights",
        "type": "Object3D",
        "matrix": [
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          1
        ]
      },
      {
        "fov": 60,
        "aspect": 1.451058,
        "near": 0.3,
        "far": 1000,
        "visible": true,
        "castShadow": false,
        "receiveShadow": false,
        "children": [
          {
            "uuid": "68c1ae0d-3f99-4cdf-b9a4-f682179bd055",
            "name": "CameraTarget",
            "type": "Object3D",
            "matrix": [
              1,
              0,
              0,
              0,
              0,
              1,
              0,
              0,
              0,
              0,
              1,
              0,
              -1.192093E-07,
              2.384186E-07,
              -4.177822,
              1
            ]
          }
        ],
        "uuid": "66776B84-DF36-4AEB-8613-9877993E9AA7",
        "name": "Main Camera",
        "type": "PerspectiveCamera",
        "matrix": [
          -0.9025,
          0,
          -0.4307,
          0,
          -0.2237,
          0.8546,
          0.4686,
          0,
          0.3681,
          0.5193,
          -0.7713,
          0,
          -0.4478,
          2.1694,
          -2.1626,
          1
        ]
      }
    ],
    "uuid": "c7f53fd2-157c-4773-bad4-3b8495b95cb8",
    "name": "MulMaterialTest",
    "type": "Scene",
    "matrix": [
      1,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      1
    ]
  },
  "images": [
  ],
  "textures": [
  ],
  "backgroundBlurriness": 0
}

**Comment by LeviPesin** [comment]
It was deprecated and the removed in https://github.com/mrdoob/three.js/pull/24431.

**Comment by N3GIS** [comment]
After removing MultiMaterial, how to write the MultiMaterial material format in the json file？

**Comment by N3GIS** [comment]
![image](https://user-images.githubusercontent.com/7942057/213999817-66b5a039-37c9-42c7-a046-e2adc403c98e.png)

The MultiMaterial code in ObjectLoader is still very important, otherwise it will cause the three.js no longer support  sub-materials, and the application of  sub-materials in three dimensions is very important, I hope to restore the code here.

**Comment by Mugen87** [comment]
There is still multi material support in `ObjectLoader` as you can see here: https://jsfiddle.net/ndfg2aLr/

But it is required to maintain multiple materials in a plain array and not by using the `MultiMaterial` class. The class itself was deprecated 2017 and the example code in the library was migrated to simple arrays.

The workaround for your case is to load the old JSON files with an outdated version of `three.js`, remove the usage of `MultiMaterial` and use arrays instead and then export to JSON again. These files should then load as expected.
