### ISSUE TITLE
KTX2Loader exmaple - Transcode wrong mipmaps size

### ISSUE THREAD

**Issue by zajkowskie** [mrdoob/three.js#25339]
### Description

When i was trying to load texture with size `2000x2118`, basisu converted it to size `2000x2120`. Basisu webgl example shows that header of ktx2 file has stil original size as `2000x2118`. After that i noticed that `mipWidth` and `mipHeight` has still `origWidth` and origHeight which makes problem with displaying CompressedTexture on canvas. So i changed to their `levelInfo.width` i `levelInfo.height`  and after that change all starts working.

### Code

```js
/** transcode */
for (let mip = 0; mip < levels; mip++) {
            const levelInfo = ktx2File.getImageLevelInfo(mip, 0, 0);
            const mipWidth = levelInfo.width; //levelInfo.origWidth;
            const mipHeight = levelInfo.height; //levelInfo.origHeight;
            const dst = new Uint8Array(ktx2File.getImageTranscodedSizeInBytes(mip, 0, 0, transcoderFormat));

            const status = ktx2File.transcodeImage(dst, mip, 0, 0, transcoderFormat, 0, -1, -1);

            if (!status) {
                cleanup();
                throw new Error('THREE.KTX2Loader: .transcodeImage failed.');
            }

            mipmaps.push({ data: dst, width: mipWidth, height: mipHeight });
        }
```

### Version

r147

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by donmccurdy** [comment]
@zajkowskie thank you! That does look like a mistake, would you want to open a PR fixing the lines below?

https://github.com/mrdoob/three.js/blob/daf92262f1a884a6d8316b6baae0aea6fa5fb974/examples/jsm/loaders/KTX2Loader.js#L477-L479

**Comment by zajkowskie** [comment]
@donmccurdy done ! 👌

**Comment by donmccurdy** [comment]
@zajkowskie do you still have the .ktx2 file that was causing the issue by any chance, and is that something you'd be able to share here?
