### ISSUE TITLE
BufferGeometry.copy(BoxGeometry) error when exporting toJSON

### ISSUE THREAD

**Issue by forerunrun** [mrdoob/three.js#25345]
### Description

as suggested by @donmccurdy i'll try to desicribe the issue i experienced from [this](https://discourse.threejs.org/t/object3d-tojson-not-saving-updated-position-attributes/47312/6) post as best possible. 

after creating a simple `BoxGeometry`, modifying its `attributes.position.array` and using `new BufferGeometry().copy(BoxGeometry)` to copy the original geometry i got the following console error when then using `.toJSON` and trying to parse the JSON with `ObjectLoader()`...
![image](https://user-images.githubusercontent.com/50278392/215095177-49f462aa-9de3-4cfb-8131-d3d03d2b845c.png)

i found that this process will work and the error does not exist after running `delete BufferGeometry.parameters`

it's quite an odd error to try to explain but you can see the attached jsFiddle as a live demonstration of the issue

### Reproduction steps

1. create a new `BoxGeometry(16, 1, 1)`
2. modify `geometry.attributes.position.array`
3. create a new `BufferGeometry()` and `.copy()` the modified BoxGeometry... `new BufferGeometry().copy(BoxGeometry)`
4. run `Group.toJSON()`
5. try to parse the resulting JSON object with `ObjectLoader()`

### Code

```
  originalGeometry = new THREE.BoxGeometry( 30, 3, 3, 30, 1, 1 )

  let box = new THREE.Mesh( originalGeometry, mat )
  
  group.add( box )
  scene.add( group )
  
  modifyGeometry( originalGeometry )
  originalGeometry.center()
  
  let newBufferGeometry = new THREE.BufferGeometry().copy( originalGeometry )
  //delete newBufferGeometry.parameters  // uncommenting this line resolves the error as a workaround
  
  originalGeometry.dispose()
  box.geometry = newBufferGeometry
  
  let jsonOutput = group.toJSON()
  
  scene.remove(group)
  
  let loader = new THREE.ObjectLoader();
  loader.parse(jsonOutput, function( object ) {
  
    scene.add( object )
    
  })
```

### Live example

https://jsfiddle.net/forerun/hdtz2uc9/7/

### Screenshots

![image](https://user-images.githubusercontent.com/50278392/215104482-54009ec7-1c6d-4281-8188-36bae789d5d6.png)

### Version

r148

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Related #22586.

Geometry generators just serialize their parameters, not their actual buffer data. When you do this:
```js
let newBufferGeometry = new THREE.BufferGeometry().copy( originalGeometry )
```
you copy the `parameters` objects which is used to detect geometry generators in `BufferGeometry.toJSON()`. If you delete it, the geometry is handled like a normal one.

The problem is the above copy is not valid right now. You have to copy the individual attributes, not the entire geometry.

The output of geometry generators can't be treated like normal instances of `BufferGeometry`. This is a deep conceptual issue and not easy to resolve.

**Comment by forerunrun** [comment]
that makes sense, i was originally copying the individual attributes as you mention like so...
```
newBufferGeometry = new BufferGeometry()
newBufferGeometry.attributes = originalGeometry.attributes
newBufferGeometry.computeBoundingBox()
newBufferGeometry.groups = originalGeometry.groups
newBufferGeometry.index = originalGeometry.index
```
but came across the error after @donmccurdy's suggestion to use the `.copy()` method

i'm way out of my league with this and there is of course the `.copy()` method is written the way that it is but could the following line in three.module.js...

```
// geometry generator parameters
if ( source.parameters !== undefined ) this.parameters = Object.assign( {}, source.parameters );
```
be updated with a needsUpdate condition like so...

```
if ( source.parameters !== undefined && !source.attributes.position.needsUpdate ) this.parameters = Object.assign( {}, source.parameters );
```
appologies in advance for any offence caused by what i think may be a rather naive suggestion, i'm most certainly overlooking very important concepts of this method

**Comment by Mugen87** [comment]
Um, I think the more clean solution would be to implement `copy()` in each geometry generator. In this way, the problematic line could be removed.
```js
if ( source.parameters !== undefined ) this.parameters = Object.assign( {}, source.parameters );
```
Ideally, `copy()` methods do not copy properties of more concrete types. They should only work on data of their type.

However, implementing `copy()` in each generator produces some redundant code. But I guess it's better than what we have now.

**Comment by Mugen87** [comment]
Alternatively, geometry generators could be derived by a new base class `GeometryGenerator` that implements the new `copy()` once.

**Comment by forerunrun** [comment]
ah ok, i was just looking into the related threads on this topic and it seems more extensive than i had thought...

> implement `copy()` in each geometry generator.
> implementing `copy()` in each generator produces some redundant code.

yes that sounds like rewriting many of the same functionalities of `copy()` again and again when the majority of the method seems like it can be reused for most cases?

> geometry generators could be derived by a new base class `GeometryGenerator` that implements the new `copy()` once.

this sounds like a much more efficient way of logically approaching the problem, i could definitely have a look at trying to get my head around it but in all fairness i would have a lot of questions, when you say "geometry generator" is this reffering to all classes that return a type of primitive geometry? and the proposal to make a base `GeometryGenerator` would be like a "header" for all geometry classes that would then be extended to continue to define and generate the type of geometry on top of that?

**Comment by Mugen87** [comment]
Possible implementation:
```js
class GeometryGenerator extends BufferGeometry {

	constructor() {

		super();

		this.type = 'GeometryGenerator';

		this.parameters = {};

	}

	copy( source ) {

		super.copy( source );

		this.parameters = Object.assign( {}, source.parameters );

	}

	static fromJSON( /* data */ ) {

		return GeometryGenerator();

	}

}
```
All generators in the core would derive from this class, not `BufferGeometry` anymore.
