### ISSUE TITLE
docs: Audio.source incorrect type

### ISSUE THREAD

**Issue by gnbl** [mrdoob/three.js#25342]
### Description

The documentation at https://threejs.org/docs/index.html?q=audio#api/en/audio/Audio.source states incorrect type:

> .[source](https://threejs.org/docs/index.html#api/en/audio/Audio.source) : String
> 
> An [AudioBufferSourceNode](https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode) created using > [AudioContext.createBufferSource](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createBufferSource)().

Corresponding sources:
- https://github.com/mrdoob/three.js/blob/master/docs/api/en/audio/Audio.html#L94
- https://github.com/mrdoob/three.js/blob/master/src/audio/Audio.js#L46

Why not generate API docs automatically from source, e.g.

- https://en.wikipedia.org/wiki/JSDoc
- https://jsdoc.app/

### Version

r149

**Comment by Mugen87** [comment]
You are right, it should not be `String` but `AudioNode`.
