### ISSUE TITLE
Rendering to WebGL3DRenderTarget in Chrome with D3D11 backend does not work correctly

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#25353]
### Description

When rendering to a 3D Render Target layer it does not work on Windows 10, Chrome specifically when using the default D3D11 backend with ANGLE. Toggling the `chrome://flags#use-angle` to `OpenGL` fixes the issue. When using D3D11 it actually corrupts the chrome dev UI, as well, and renders to a wrong part of the canvas. This seems to be a browser issue pretty cut and dry but I thought I'd submit here to see if I'm missing a step in rendering to the target layer.

This is causing issues rendering to a 3d texture for sdf generation in [this three-mesh-bvh issue](https://github.com/gkjohnson/three-mesh-bvh/issues/497).

An aside - the D3D11 backend seems to have a variety of issues (see https://github.com/gkjohnson/three-gpu-pathtracer/issues/325#issuecomment-1407232890). I'm sure there's a good reason but I'm naively wondering why the OpenGL backend isn't the default behavior?

### Reproduction steps

1. Render to a WebGL3DRenderTarget layer
2. Render the layer to screen
3. Layer does not render

### Code

See example

### Live example

Live example of the modified version of the "webgl2_rendertarget_texture2darray" page: [live page](https://raw.githack.com/gkjohnson/three.js/3d-render-target-repro/examples/webgl2_rendertarget_texture2darray.html)

And here's a diff of the minimal changes to the example page: [diff](https://github.com/mrdoob/three.js/compare/36a8629...gkjohnson:three.js:3d-render-target-repro).

### Screenshots

Chrome screenshot using default ANGLE D3D11 backend which actually corrupts the Chrome UI, as well:

<img src="https://user-images.githubusercontent.com/734200/215267887-0a3305aa-ffe1-4422-a42a-eb62129fe812.png" width="500px" />

Using ANGLE OpenGL backend:

<img src="https://user-images.githubusercontent.com/734200/215268052-f7c7a607-5cb0-4a81-aa7b-5598dde7f1a1.png" width="500px"/>

### Version

dev

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by epreston** [comment]
The Angle Project runs a discussion group here, with tooling and people who can review browser environments.
https://groups.google.com/g/angleproject

Issues similar to this come up from time to time.  For example:
https://groups.google.com/g/angleproject/c/XMe7w989mUc?pli=1

To answer part of your question, javascript and webpages in general can not change the browsers settings or its operating environment.  Angle maintains a list of blacklisted hardware / driver / system update combos under D3D11 for the types of issues you are describing.

Why is it not default ?  It's a user configurable setting with a default configuration chosen by chrome based on OS, patch level, card type, driver version.  This configuration setting has the following description in chrome, enter the this path in your browser search bar to review: chrome://flags/#use-angle

> Choose the graphics backend for ANGLE. D3D11 is used on most Windows computers by default. Using the OpenGL driver as the graphics backend may result in higher performance in some graphics-heavy applications, particularly on NVIDIA GPUs. It can increase battery and memory usage of video playback.

This library, three.js, only attaches to a canvas element within a webpage and requests a WebGL context.  At best, it can query for supported extensions in WebGL.  If the browser environment has issues, or issues with a particular extension, things fail.  If the extension is not supported by the hardware, things fail.  That's expected.  Not every example is can run on all browser / hardware / os / patch level combinations.  

The examples are written for clarity (most of the time) of a particular technique / technology.  They lack the feature detection and fall-back code that is added when people use this library.  They force a specific behaviour allowing people to see how things perform and catch issues like you have in specific setups.

**Comment by gkjohnson** [comment]
Thanks @epreston but I'm aware that JS can't modify browser settings. My comment was specifically wondering about why OpenGL is not the default backend in ANGLE for Chrome as a browser setting rather than D3D11 since it seems to fix a number of issues which is why I mentioned the Chrome flag. I'm aware this is not a three.js decision to make.

**Comment by gkjohnson** [comment]
I've reported the issue to chrome here:

https://bugs.chromium.org/p/chromium/issues/detail?id=1411048

**Comment by epreston** [comment]
It does not fix a number of issues, at best, it shifts the issues around.  For your current setup, it's a fix.  It has some benefits and drawbacks.

On some of the products I've worked with, D3D11 is used because the native windowing system uses D3D11 leading to a number of efficiencies, acceleration, and broader hardware support.  OpenGL code paths don't receive the same attention at each piece of the technology stack on Windows platforms.  There's no OpenGL certification requirement for Windows hardware, but there is a D3D11 validation requirement for signed drivers on Windows.

**Comment by epreston** [comment]
Highly recommend raising this on Angle Project if you need a detailed / timely answer.  First thing they are going to ask is the graphics driver versions for you 2070 super and if you have the integrated graphics enabled on the i7.  Update the bug report or use the Angle troubleshooting tool dumps to reduce the cycle time on the request.

**Comment by Mugen87** [comment]
>  but I thought I'd submit here to see if I'm missing a step in rendering to the target layer.

Looking at the renderer and specifically the code in `WebGLTextures`, I can't imagine of a WebGL command that is missing right now.

You might want to run the tests from the `all/conformance2/textures` section of the WebGL conformance test suite on your device (https://registry.khronos.org/webgl/sdk/tests/webgl-conformance-tests.html). Maybe there is already a test that fails and catches the issue. Otherwise it could be interesting to add one.

**Comment by Danilkat** [comment]
GOD DAMN! Thank you for your research on this issue, your fix helped me! 
I was trying to implement procedural clouds using worley 3D texture, and ive spent 3 days unsuccessfully
 trying to figure out why it doesn't work on `WebGL3DRenderTarget` but works on `WebGLArrayRenderTarget`. 
 Eventually i gave up and stuck to using 2D arrays, until now.

**Comment by Mugen87** [comment]
Closing. Let's tackle the issue at the Chromium bug tracker.

**Comment by pailhead** [comment]
I just ran into this when attempting to do the same thing, Chrome's UI is corrupted across multiple windows. Is there a workaround on windows by using these array targets?
