### ISSUE TITLE
CreateMaterialColorAnimation() uses hardcoded invalid property binding string '.material[0].color'

### ISSUE THREAD

**Issue by gnbl** [mrdoob/three.js#25362]
### Description

- https://threejs.org/docs/index.html?q=ColorKeyframeTrack#api/en/animation/KeyframeTrack
- https://threejs.org/examples/jsm/animation/AnimationClipCreator.js
- https://github.com/mrdoob/three.js/blob/dev/examples/jsm/animation/AnimationClipCreator.js#L104

Using this to create a AnimationClip for an AnimationMixer for a BoxGeometry Mesh with MeshBasicMaterial fails with 
> THREE.PropertyBinding: Trying to bind to objectIndex of objectName, but is undefined.

The `material` property is not an Array.

### Reproduction steps

see above

### Code

none

### Live example

none

### Version

r149

**Comment by Mugen87** [comment]
Live example for demonstrating the issue: https://jsfiddle.net/f3L9snh7/1/

I think the function should be written like in this updated example so you can pass in an array of `THREE.Color`: https://jsfiddle.net/f3L9snh7/2/

**Comment by gnbl** [comment]
Thanks for verifying!
Sorry, not familiar enough with three.js to give qualified feedback. I don't know whether multiple materials are (were) possible.
You've removed the index so the property is now `'.material.color'` which works in this simple case (and was the cause for this issue). I don't know if there are other cases where testing for type might be required.

Changing the colors parameters from "flat" to Object would probably break the interface and is not consistent with the other functions.
For convenience, add another function that supports this type or do type-checking?

Another thing to consider is that the property does not apply for other THREE Objects, e.g. lights don't have material but color. So maybe expose the binding string as additional parameter (with default)?

**Comment by Mugen87** [comment]
> You've removed the index so the property is now '.material.color' which works in this simple case (and was the cause for this issue). I don't know if there are other cases where testing for type might be required.

Multi-materials are supported but it's okay when the function does not remove it. `AnimationClipCreator` is intended for simple use cases. They should also give users a hint how animation clips can be generated procedurally. But they don't have to cover the entire feature set of `three.js`. That would only make them unnecessarily complicated and bloated.

> Another thing to consider is that the property does not apply for other THREE Objects, e.g. lights don't have material but color. So maybe expose the binding string as additional parameter (with default)?

The function is called `CreateMaterialColorAnimation()` so the relation to `Material.color` should be clear. I would not make the function more complicated by supported other color properties. Like mentioned above, `AnimationClipCreator` are focused on the most common use cases. If users need a different helper, they can easily copy one of the functions and update it according to their needs.

> Changing the colors parameters from "flat" to Object would probably break the interface and is not consistent with the other functions.

`AnimationClipCreator` should make the generation of common keyframe tracks easier. Looking at the other functions, using color objects should still be consistent.
