### ISSUE TITLE
Add translateX, Y, and Z for consistency

### ISSUE THREAD

**Issue by philipswan** [mrdoob/three.js#25368]
### Description

Object3D supports translateX(), Y, and Z so its confusing that BufferGeometry does not. Three.js users have to hunt for a different set of commands (that is, translate(x, y, z)).

### Solution

Implement translateX(), translateY(), and translateZ() for BufferGeometry and update the documentation.

### Alternatives

None

**Comment by WestLangley** [comment]
`Object3D.translateX( dist )` translates on the object's _local_ X-axis.

`BufferGeometry` has no need for such a method. `BufferGeometry.translate( x, y, z )` is sufficient.

**Comment by philipswan** [comment]
I disagree, obviously. I would not have taken the time to submit this request if I thought it was ok APIs to be inconsistent within three.js.

**Comment by Mugen87** [comment]
Having `translateX()`, `translateY()` and `translateZ()` in `Object3D` but not in `BufferGeometry` is appropriate because both classes have different semantics as https://github.com/mrdoob/three.js/issues/25368#issuecomment-1409518865 pointed out. So the APIs are not really comparable. Closing.
