### ISSUE TITLE
IFC code is almost a year old

### ISSUE THREAD

**Issue by wwwouter** [mrdoob/three.js#25371]
### Description

The IFC files (https://github.com/mrdoob/three.js/tree/dev/examples/jsm/loaders/ifc) are from Feb 18th and since then there have been many updates 

For a while I downloaded the web-ifc and IFCLoader files and updated the imports myself. But with every update of Three.js and/or IFC.js this would break. Therefore I chose just to rely on the Three.js repository for the loader and all other IFC dependencies.

Here is mentioned that the IFC dependencies will probably move outside of this repository (https://github.com/mrdoob/three.js/pull/25057/files#r1037975491), but I can't see any changes just yet.

Is it possible to update the IFC dependencies for now, while we wait for the new way of importing dependencies for "external" examples?

For me it would be better if there was a stand-alone IFCLoader package on npm, with all the correct dependencies linked. Is that something has been considered before?

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

148

**Comment by agviegas** [comment]
Woops, sorry. These weeks have been really bloated. As mentioned [here](https://github.com/mrdoob/three.js/pull/25057#discussion_r1039323676), I will update the example to import the loader from [here](https://github.com/ifcjs/web-ifc-three) using importmaps and unpkg. I will start working on this today. Is this correct?

**Comment by mrdoob** [comment]
@agviegas That is correct 👍

**Comment by wwwouter** [comment]
Ok, then I'll wait for this update.

I see that because of https://github.com/IFCjs/web-ifc-three/issues/115 I need to use `--legacy-peer-deps`, because I'm on a recent version of Three.js

Also when I just update the import like stated here https://ifcjs.github.io/info/docs/Guide/web-ifc-three/Introduction#can-i-use-the-threeifcloader-directly, I get this error

<img width="454" alt="image" src="https://user-images.githubusercontent.com/997207/215713271-344c1e29-067e-4b5f-9ed4-13bfff11795d.png">


But that's probably not something that should be reported here.

**Comment by agviegas** [comment]
@mrdoob understood, I will get hands-on with this right away. Sorry for the delay and thanks again!
