### ISSUE TITLE
Support toJSON in Quaternion class

### ISSUE THREAD

**Issue by XorTdsc** [mrdoob/three.js#25424]
### Description

Similarly to [this](https://github.com/mrdoob/three.js/issues/24167) request it would be nice to have a clean toJSON serialization for the Quaternion class. Currently the `JSON.stringify()` results in
`{"isQuaternion":true,"_x":0,"_y":0,"_z":0,"_w":1}`

### Solution

The preferred output should be
`{"x":0,"y":0,"z":0,"w":1}`

### Alternatives

Probably not a viable alternative: Maybe a serialization toolset in a separate class/lib ?

**Comment by Mugen87** [comment]
I vote to reopen #24172 and also apply this change to `Quaternion`. The PR was closed under the assumption we could use `instanceof` for type checking which we not did. So I think adding a `toJSON()` implementation for selected math classes is fine.

**Comment by donmccurdy** [comment]
Maybe as an array, like `[0, 0, 0, 1]`? If we added toJSON on Matrix3 and Matrix4 later they'd be arrays, might as well be consistent.

**Comment by Mugen87** [comment]
I'm fine with arrays, too. In the three.js JSON Object/Scene format, matrix and vector properties like the local matrix or the center of a bounding sphere are already serialized as arrays.

**Comment by XorTdsc** [comment]
I guess that's fine too, as long as everything is consistent (currently Vector3 does not export as an array)

**Comment by epreston** [comment]
You can get what you are after by calling `toArray` on the quaternion.

```js
const quat = new Quaternion(); 
// change rotation
const json = JSON.stringify( quat.toArray() )
```

When you read it back in use `fromArray`

```js
const data = JSON.parse( json )
const quatFromJson = new Quaternion().fromArray( data ); 
```

**Comment by Mugen87** [comment]
The problem with this suggestion is that you often can't execute such code since the JSON serialization happens indirectly when performing certain operations e.g. `console.log( new THREE. Quaternion() );`.

Having a `toJSON()` implementation solve this as well.
