### ISSUE TITLE
GridHelper object missing 'divisions' property.

### ISSUE THREAD

**Issue by YasharSL** [mrdoob/three.js#25438]
### Description

I couldn't find any information on how to change the `divisions` property after initializing a `GridHelper` in either the code or the documentation. It appears that this feature doesn't exist.
For example:
```
const gridHelper = new THREE.GridHelper(50, 50);
gridHelper.divisions = newDivision;
```

### Solution

An ideal solution would be to change the divisions property directly, like this:
```
gridHelper.divisions = newDivision;
```

### Alternatives

If this is not possible, an alternative solution would be to create a method for updating its value and make the divisions property read-only.
```
gridHelper.setDivisions( gridHelper.divisions + 10 );
```

**Comment by Mugen87** [comment]
Once the helper has been created, you can't change its `divisions` parameter anymore. Similar to other helpers or geometry generators. Call `dispose()` on the helper and create a new one if you have to update its appearance.
