### ISSUE TITLE
Update link to "Learn Three.js" 4th ed.

### ISSUE THREAD

**Issue by ycw** [mrdoob/three.js#25446]
### Description

update link, to upcoming ed.

### Solution

4th ed. (February 17, 2023)

https://www.packtpub.com/product/learn-threejs-fourth-edition/9781803233871

### Alternatives

--

**Comment by mrdoob** [comment]
Done! https://github.com/mrdoob/three.js/commit/a6d9662d1b5b4731d620a2e0f90ee6637ef9d9fa

**Comment by ycw** [comment]
thanks.
