### ISSUE TITLE
GLTF exports an AmbientLight as an empty child without lighting information

### ISSUE THREAD

**Issue by Cloov** [mrdoob/three.js#25449]
### Description

Using `threejs.org/editor`, when exporting a scene as GLTF, the AmbientLight doesn't export with any lighting information, and exports only as an empty child named AmbientLight.

### Reproduction steps

1. Open the editor and create a new scene, and place an ambient light in the scene
2. Export the file as GLTF
3. At this point, inspecting of the GLTF file, it seems as though there is no lighting information within the object named AmbientLight
4. Start a new editor session and import the created file
5. Observe that there is an object named AmbientLight, but it has no lighting information.

### Code

{
  "asset": {
    "version": "2.0",
    "generator": "THREE.GLTFExporter"
  },
  "scenes": [
    {
      "name": "Scene",
      "nodes": [
        0
      ]
    }
  ],
  "scene": 0,
  "nodes": [
    {
      "name": "AmbientLight"
    }
  ]
}

### Live example

https://threejs.org/editor/

### Version

r149

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
glTF has no concept of ambient lights so it can support your use case. The light is exported as a normal node in the scene graph which is indented since the light might have childs that can be exported properly.
