### ISSUE TITLE
scene.backgroundBlurriness not working

### ISSUE THREAD

**Issue by surdu** [mrdoob/three.js#25462]
### Description

When I set `backgroundBlurriness` on a scene, the scene background is not blurred.

### Reproduction steps

1. load texture
2. apply texture as background
3. set `backgroundBlurriness` to 1

### Code

```
const map = new THREE.TextureLoader().load("some_image.jpg", tex => {
    tex.encoding = THREE.sRGBEncoding;
});

scene.background = map;
scene.backgroundBlurriness = 1;

```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/bwyrjdav/)
* [jsfiddle-dev](https://jsfiddle.net/m73oqzed/)

### Version

r147

**Comment by Mugen87** [comment]
As mentioned in the [documentation](https://threejs.org/docs/index.html#api/en/scenes/Scene.backgroundBlurriness), `Scene. backgroundBlurriness` only affects environment maps.
