### ISSUE TITLE
MeshPhysicalMaterial: transmission rendering is buggy for high-roughness values

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#25485]
### Description

Small changes in the camera position can cause huge changes in the color of the transmissive material.

### Reproduction steps

See `webgl_materials_physical_transmission.html` and set `roughness` to 0.8 or greater.

### Code

`git bisect` points to #23450 as the start of this behavior.

### Live example

https://threejs.org/examples/webgl_materials_physical_transmission.html

### Screenshots

<img width="737" alt="Screenshot 2023-02-12 at 12 03 41 AM" src="https://user-images.githubusercontent.com/1000017/218294020-19be3cc2-e634-41ec-b393-b4ceb7939913.png">

<img width="738" alt="Screenshot 2023-02-12 at 12 03 55 AM" src="https://user-images.githubusercontent.com/1000017/218294027-d6821696-d8ac-46f5-b3ae-483108f9f62c.png">

### Version

r149

### Device

Desktop

### Browser

Chrome, Firefox, Safari

### OS

MacOS

**Comment by WestLangley** [comment]
https://github.com/mrdoob/three.js/pull/23450 was in r138. For comparison, see r137.

**Comment by Mugen87** [comment]
Thanks for bringing this issue up. I guess I've noticed the same glitch some time ago here: https://github.com/mrdoob/three.js/issues/18629#issuecomment-1321963594

**Comment by Mugen87** [comment]
Restoring how the transmission render target was created before #23450 does not seem to fix the issue.

**Comment by Mugen87** [comment]
It seems going back to a fixed resolution like `1024x1024` fixes the issue.

@WestLangley For testing, can you confirm that the following fixes the glitch?
```js
function renderTransmissionPass( opaqueObjects, scene, camera ) {

		const isWebGL2 = capabilities.isWebGL2;

		if ( _transmissionRenderTarget === null ) {

			_transmissionRenderTarget = new WebGLRenderTarget( 1024, 1024, {
				generateMipmaps: true,
				type: extensions.has( 'EXT_color_buffer_half_float' ) ? HalfFloatType : UnsignedByteType,
				minFilter: LinearMipmapLinearFilter,
				samples: ( isWebGL2 && _antialias === true ) ? 4 : 0
			} );

		}

		//

		const currentRenderTarget = _this.getRenderTarget();
		_this.setRenderTarget( _transmissionRenderTarget );
		_this.clear();

		// Turn off the features which can affect the frag color for opaque objects pass.
		// Otherwise they are applied twice in opaque objects pass and transmission objects pass.
		const currentToneMapping = _this.toneMapping;
		_this.toneMapping = NoToneMapping;

		renderObjects( opaqueObjects, scene, camera );

		_this.toneMapping = currentToneMapping;

		textures.updateMultisampleRenderTarget( _transmissionRenderTarget );
		textures.updateRenderTargetMipmap( _transmissionRenderTarget );

		_this.setRenderTarget( currentRenderTarget );

	}
```

**Comment by Mugen87** [comment]
I could imagine that with a non-squared resolution, the sampling of the lower mips does not work as expected 🤔 .

**Comment by WestLangley** [comment]
>@WestLangley For testing, can you confirm that the following restores the old behavior?

Confirmed -- and in conjunction with #25483, it's visually far superior.

**Comment by Mugen87** [comment]
But if we restore the POT dimensions, we introduce asymmetrical warping glitches back. They are mentioned in https://github.com/mrdoob/three.js/issues/22009#issue-924123388 and https://github.com/mrdoob/three.js/pull/22731#issue-1035507881. 

Not sure what is more severe. These glitches or the problem reported in this issue.

**Comment by WestLangley** [comment]
The artifacts reported in this post are unacceptable, IMO.

I'd have to see a live example of the so-called "asymmetrical warping glitches" to pass judgement on their severity. But I expect they can be mitigated at the app-level by maintaining a canvas that's relatively square (not necessarily perfectly square).

**Comment by LeviPesin** [comment]
Maybe we can set width and height of the render target to both `Math.min( width, height )` or `Math.max( width, height )`?

**Comment by Mugen87** [comment]
> The artifacts reported in this post are unacceptable, IMO.

Agreed! Let's revert to POT for now.
