### ISSUE TITLE
3D rendering of materials no longer works - shader bug that i can't fix myself :(

### ISSUE THREAD

**Issue by NicerEnterprises** [mrdoob/three.js#25499]
### Description

There appears to be a new shader bug that is preventing 3D models from being displayed correctly.

### Reproduction steps

Just load up the page and open up the browser console tab in it's debugger.

### Code

```js
// code goes here
```

### Live example

You can find all the details in the console.log() of https://nicer.app/demo-3D-models
This bug shows up in both firefox and chrome, with *identical* error messages from the browser's WebGL sub-system.

### Version

149

### Device

Desktop

### Browser

Chrome, Firefox

### OS

Linux

**Comment by donmccurdy** [comment]
Please use one of the links below for help / support:

- [questions](https://stackoverflow.com/questions/tagged/three.js)
- [discord](https://discord.gg/56GBJwAnUS)
- [forum](https://discourse.threejs.org/)
