### ISSUE TITLE
how to set anchor in CSS2DObject ?

### ISSUE THREAD

**Issue by jingyuLin1999** [mrdoob/three.js#25509]
### Description

I want to set anchor , so that tooltip will show normal, but i dont know how to do.  I have read #14643  issue.
![1676421853940](https://user-images.githubusercontent.com/30433062/218896173-f2b4d7e0-4ace-451e-86a3-b75091959461.jpg)

version: "three": "^0.124.0"
```js
let div = document.createElement("div");
let bgColor = vm.tooltip.backgroundColor || hex2HexStr(style.color);
div.style = `
    fontSize:8px;
    background:${bgColor};
    padding:3px;
    color:${hex2HexStr(vm.tooltip.textStyle.fill)};
    position:relative;
    minHeight:50px;
    minWidth:50px;`;
div.style.borderRadius = '3px';
div.innerText = `x:${rawData.x}\ny:${rawData.y}\nz:${rawData.z}`;

let divObj = new CSS2DObject(div);
tooltip.add(divObj);
tooltip.position.set(position.x, position.y, position.z); // position from raycaster
```

### Solution

add a method like setAnchor

### Alternatives

null

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by WestLangley** [comment]
Perhaps this was intended as a feature request.

`Sprite` supports `sprite.center( 0, 0.5 )`.

In `CSS2DRenderer`, the anchor point is hardwired:

https://github.com/mrdoob/three.js/blob/b2fdb55fe9e48051c97db28bd9c5fb18dab80c58/examples/jsm/renderers/CSS2DRenderer.js#L128

**Comment by jingyuLin1999** [comment]
@WestLangley Thanks for you reply. I have to use  `element.style.marginLeft="98px";` , although it is not accurate enough.

**Comment by WestLangley** [comment]
@jingyuLin1999 Instead, as a workaround, you can modify your copy of `CSS2DRenderer` like so:

```js
element.style.transform = 'translate(0%,-50%) translate(' + ( _vector.x * _widthHalf + _widthHalf ) + 'px,' + ( - _vector.y * _heightHalf + _heightHalf ) + 'px)'; 
```

**Comment by Mugen87** [comment]
@WestLangley Do you think it's worth adding `CSS2DObject.center` and updating the `translate` CSS property based on its value?

**Comment by WestLangley** [comment]
@Mugen87 I was asking myself the same question...   :-)

There has been no demand for it, but I can see the usefulness of setting the anchor point for a ToolTip. I can add it if you like.

**Comment by Mugen87** [comment]
@mrdoob How do you think about this?

**Comment by mrdoob** [comment]
I think we can follow `Sprite` on this one and add `center` yeah.

**Comment by WestLangley** [comment]
OK, I'll add it.
