### ISSUE TITLE
Unable to get OnPointerEnter and OnPoniterLeave events when hover over on dae model

### ISSUE THREAD

**Issue by ganeshpatil4210** [mrdoob/three.js#25512]
### Description

Hi, 👋

We are loading dae file using ColladaLoader. After loading file, we are rendering using primitive. we also provided onPointerEnter and OnPointerLeave events. But we are not receiving an event callback for this attached dae model. On the top portion of model, we don't receive and on the bottom portion of the model we receive callbacks.

Please refer to attached dae model.
[stormtrooper.zip](https://github.com/mrdoob/three.js/files/10741359/stormtrooper.zip)
the 

### Reproduction steps

1. Load model using ColladaLoader
2. Pass pointer events to primitive
3. hover over the model's top portion like the head, and chest, we don't receive event callbacks.

### Code

```js
// code goes here
```
<primitive
onPointerLeave={() => {

  }}
  onPointerEnter={() => {
   
  }}>

### Live example

*[jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)

### Version

 "@react-three/drei": "9.40.0",     "@react-three/fiber": "8.9.1", "three": "^0.146.0",     "three-stdlib": "^2.17.3",

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by LeviPesin** [comment]
Also, this most probably is a bug in react-three, not in Three.js.

**Comment by mrdoob** [comment]
@drcmda FYI

**Comment by Mugen87** [comment]
https://discourse.threejs.org/t/unable-to-get-onpointerenter-and-onponiterleave-events-when-hover-over-on-dae-model/48061
