### ISSUE TITLE
Light bleeding with shadow maps - back facing geometry used in SM creation instead of front facing

### ISSUE THREAD

**Issue by ikolic** [mrdoob/three.js#25513]
### Description

When enabling shadow mapping on directional light we get light bleed (PCFShadowMap, PCFSoftShadowMap, BasicShadowMap). It seams like shadow map is created using back faces of the geometry instead of front faces. 

![image](https://user-images.githubusercontent.com/43576421/219053604-35b91c50-879c-4683-b118-451ca9a248a7.png)

Setting bias doesn't help because positive bias just makes ugly dark outline around the objects and negative bias causes even bigger light bleed.

![image](https://user-images.githubusercontent.com/43576421/219057344-cbad9bbc-5263-4359-976d-023292abdcb6.png)
![image](https://user-images.githubusercontent.com/43576421/219057398-05d87075-4669-4e17-abd5-4d9e7d894bac.png)

The only fix is to use forward faces when creating shadow map.
I understand that this can cause acne problem on those surfaces that cast and receive shadow but that can be fixed with bias (that would become useful)

### Reproduction steps

1. Create scene with two boxes, smaller one stacked on top of the big one.
2. Create directional light with shadow mapping enabled
3. Render

### Code

```js
// RENDERER:
const renderer = new THREE.WebGLRenderer({antialias: true});
renderer.setSize(innerWidth, innerHeight)
renderer.setPixelRatio(window.devicePixelRatio);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap; // default THREE.PCFShadowMap
document.body.appendChild(renderer.domElement);

// CAMERA:
const camera = new THREE.PerspectiveCamera(75, innerWidth/innerHeight, 0.1, 250);
camera.position.set (-1.5, 1.5, -1.5);
camera.lookAt( 0, 0, 0 );

// SCENE:
const scene = new THREE.Scene();
		
// LIGHTS:
scene.add(new THREE.AmbientLight(0x505050, 1));
const directionalLight = new THREE.DirectionalLight(0xffffff, 1);
directionalLight.position.set(10, 10, 10);

directionalLight.castShadow = true;
directionalLight.shadow.mapSize.width = 512;
directionalLight.shadow.mapSize.height = 512;
directionalLight.shadow.camera.near = 0.5;
directionalLight.shadow.camera.far = 20;
//directionalLight.shadow.bias = 0.005;

scene.add(directionalLight);

// SCENE OBJECTS:
const geometry = new THREE.BoxGeometry( 1, 1, 1 );
const material = new THREE.MeshPhongMaterial({ color: 0xFFFFFF });
const cube1 = new THREE.Mesh( geometry, material );
const cube2 = new THREE.Mesh( geometry, material );
cube1.position.y = -0.5;
cube1.scale.x = 2;
cube1.scale.z = 2;
cube2.position.y = 0.5;
cube1.castShadow = true;
cube2.castShadow = true;
cube1.receiveShadow = true;
cube2.receiveShadow = true;
scene.add( cube1 );
scene.add( cube2 );

renderer.render(scene, camera);
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/ikolic/L4ngky8j/16/)

### Screenshots

![image](https://user-images.githubusercontent.com/43576421/219068018-ea943376-ca4b-4e69-86ab-0c7eecdfa44c.png)

### Version

r149

### Device

Desktop

### Browser

Edge

### OS

Windows

**Comment by WestLangley** [comment]
See https://threejs.org/docs/?q=material#api/en/materials/Material.shadowSide

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.
