### ISSUE TITLE
ShadowMaterial: render-order with logarithmicDepthBuffer is wrong

### ISSUE THREAD

**Issue by IARI** [mrdoob/three.js#25515]
### Description

Using ShadowMaterial and logarithmicDepthBuffer together currently does not work.
The problem [was described on discourse by another user](https://discourse.threejs.org/t/using-shadowmaterial-with-logarithmicdepthbuffer-is-affecting-render-order/37322) using 0.137 but persists to date (0.149)
It can be observed with just 3 elemtns in a scene as described below.

### Reproduction steps

1. Create renderer with `logarithmicDepthBuffer: true`, set it up for shadows
2. Add any shadow-casting object
3. Add a shadow-plane with `ShadowMaterial` right below the object
4. Add some other object/plane further below

### Code

```js
const scene = new Scene();
const camera = new PerspectiveCamera(10, window.innerWidth / window.innerHeight, 0.1, 1000);
const renderer = new WebGLRenderer({
    logarithmicDepthBuffer: true,
});
document.body.appendChild(renderer.domElement);
renderer.setSize(innerWidth, innerHeight);
renderer.setClearColor(0x666666, 1);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = PCFSoftShadowMap;
const shadowMat = new ShadowMaterial({
    opacity: 0.85
});
const stdMaterial = new MeshStandardMaterial({});

function createPlane(planeSize, mat, shadow=true) {
    const planeGeo = new PlaneGeometry(planeSize, planeSize);
    const plane = new Mesh(planeGeo, mat);
    plane.rotateX(-Math.PI / 2);
    plane.receiveShadow = shadow;
    return plane;
}

const shadowPlane = createPlane(10, shadowMat);
shadowPlane.position.y = -1.002;
scene.add(shadowPlane)

const otherPlane = createPlane(10, stdMaterial, false);
otherPlane.position.y = -4.001;
scene.add(otherPlane)

const controls = new OrbitControls(camera, renderer.domElement);
const cubeGeometry = new BoxGeometry(2, 2, 2);
const cube = new Mesh(cubeGeometry, stdMaterial);
cube.castShadow = true;
scene.add(cube);

const mainLight = new DirectionalLight(0xffffff, 1.5)
mainLight.position.set(-9, 17, -15)
mainLight.castShadow = true;
scene.add(mainLight)

camera.position.set(-35, 13, 35)
camera.updateProjectionMatrix()
controls.update()

;(async () => {
    while (true) {
        renderer.render(scene, camera)
        await new Promise(requestAnimationFrame)
    }
})()
```

### Live example

* [codesandbox.io](https://codesandbox.io/s/threejs-shadowmaterial-logarithmicdepthbuffer-rgzrph?file=/src/index.js:252-280)

### Screenshots

<img width="413" alt="image" src="https://user-images.githubusercontent.com/1053417/219331833-e366cd87-b134-49e0-a5b3-960eb2ce7fee.png">

### Version

0.149.0

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
It seems the respective shader chunks are missing in the shader of `ShadowMaterial`. I'll try to fix this with a PR.

**Comment by berkaycirak** [comment]
Hi, I got same issue but for shaderMaterial this time, could you fix or any solution? I want to use logarithmicDepthBuffer in my renderer.

**Comment by LeviPesin** [comment]
Shouldn't you then just use the corresponding shader chunks for that? (Those from https://github.com/mrdoob/three.js/pull/25516)
