### ISSUE TITLE
Brave Image Optimization Bug

### ISSUE THREAD

**Issue by ashconnell** [mrdoob/three.js#25510]
### Description

We've noticed that in Brave, ImageLoader doesn't emit load/error events for some Image elements, even though the network tab shows the image fully loaded and complete.

ThreeJS creates Image elements in a private only scope, unreferenced anywhere else until after the image is loaded.
I suspect that Brave sees this as an opportunity to optimize the users experience since the Image is not referenced anywhere or in the DOM.

Any attempt to debug this issue, eg console logging or storing the Image in global scope immediately fixes the issue.

I'm not sure if this is something we should fix in ThreeJS, but wanted to make sure people find this if they run into similar issues.

I've tweeted Brave about this here: https://twitter.com/hyperfy_io/status/1625479090471059457

### Reproduction steps

Reproduction is not so clear as Brave can choose to "optimize" away an image based on a variety of criteria unknown to us.

We see this in many of our Hyperfy worlds, most recently this one: https://hyperfy.io/love which contains a lot of images. Which image gets evicted is seemingly random.

You can tell when Brave evicts an image when the loading bar never reaches 100% as it gets stuck trying to load an image.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

147

### Device

Desktop

**Comment by ashconnell** [comment]
Side Note: the issue tracker template doesn't contain "Brave" as a browser option

**Comment by mrdoob** [comment]
I've googled "brave bug report" for you and I found this:

https://support.brave.com/hc/en-us/articles/360018228951-How-do-I-submit-a-bug-report-

**Comment by ashconnell** [comment]
@mrdoob if Brave determine that this is a completely valid optimization and leave it as intentional, then we'll need to decide whether three.js:-

A) No longer support Brave.
B) Finds a work around for their image eviction optimization.

Until we determine their decision this ticket serves specifically as a vehicle for discussing the issue.

**Comment by ashconnell** [comment]
Fwiw, I spent 3 days figuring out the cause of this crazy issue so if anyone needs a workaround for it here's what works: https://github.com/hyperfy-io/hyperfy-three/commit/827a25c7d4b12b7cfa39ef0db16d86d604605da8

I could have just said nothing and let everyone else spend 3 days on it... /shrug

**Comment by lalalune** [comment]
> I've googled "brave bug report" for you and I found this:
> 
> https://support.brave.com/hc/en-us/articles/360018228951-How-do-I-submit-a-bug-report-

It's a feature on Brave's part to optimize the browsing experience. IMO this will probably never be fixed on their side, so we'll have intermittent loading of three.js forever. 0.05% of users use brave, which is not many, but our community (Metaverse makers) massively overrepresent usage (more like 10%) so it's enough to be annoying.

**Comment by mrdoob** [comment]
> It's a feature on Brave's part to optimize the browsing experience. 

How's breaking code that works in other browsers a feature? If anything they could emit fake events to avoid breakage.

As far as I understand Brave is based on Chromium where this is not a problem. So they added code on top and they broke the expected behaviour.

Someone will have to give a very detailed explanation of why we need to add a workaround in the library.

**Comment by mrdoob** [comment]
> @mrdoob if Brave determine that this is a completely valid optimization and leave it as intentional

Lets put this issue on hold until Brave determines that.

**Comment by LeviPesin** [comment]
There exists the HTML specification, which, I'm pretty sure, specifies that for each image browser must either fire a load or error event. If Brave doesn't do that, it's a bug in Brave.
