### ISSUE TITLE
Issue #23260, #23267 reopen since the commit #24181

### ISSUE THREAD

**Issue by Kliffh** [mrdoob/three.js#25521]
### Description

On ios14.x, the EXRLoader can not load hdri since the commit #24181. The func parseInt64 caused this. 

### Reproduction steps

1.using r147/r148 EXRLoader to load hdri
2.can not start the loading neither in safari nor chrome

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r148

### Device

Mobile

### Browser

Safari

### OS

iOS

**Comment by LeviPesin** [comment]
It [seems indeed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/getBigInt64) DataView.getBigInt64() is not supported in Safari 14 (but it should be supported in Chrome?). I can revert that change of `parseInt64`.

**Comment by mrdoob** [comment]
@LeviPesin We should probably revert that change yes.
