### ISSUE TITLE
OBB seams not working with custom buffergeometry meshes

### ISSUE THREAD

**Issue by enruilo1** [mrdoob/three.js#25534]
### Description

I use OBB to obtain an box oriented following main axis of object but i still get an AABB box. I dont know why, because i apply same steps as demo example...i think is because in demo example geometries are boxGeometry but when its used with custom geometry buffer that funcionality not work. I attach file of picture not working.
I hope your help, thanks

[IfcClash_v02.zip](https://github.com/mrdoob/three.js/files/10776652/IfcClash_v02.zip)

### Screenshots

![image](https://user-images.githubusercontent.com/46839816/219943149-2301dca7-eca6-4ab8-ba93-c7aafa2bee28.png)

### Version

r145

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Please let you help at the [forum](https://discourse.threejs.org/).
