### ISSUE TITLE
SVGLoader fails on empty paths

### ISSUE THREAD

**Issue by eulertour** [mrdoob/three.js#25548]
### Description

The same error described [here](https://bugs.webkit.org/show_bug.cgi?id=78980). The SVGLoader crashes on SVGs that contain empty paths, such as
```
<svg xmlns="http://www.w3.org/2000/svg" height="100" width="100">
<path d=""/>
</svg>
```

The error occurs with r148 but I couldn't figure out how to import the library with SVGLoader without the skypack cdn which only goes up to r130. 

### Reproduction steps

Attempt to load an SVG with an empty path with SVGLoader.

### Code

```js
let svgString = `
<svg xmlns="http://www.w3.org/2000/svg">
	<circle cx="0" cy="0" r="3"/>
  <path d=""/>
</svg>`;

const material = new THREE.MeshBasicMaterial( { color: 0x000000 } );
const parseData = new SVGLoader().parse(svgString);
for (const shapePath of parseData.paths) {
  const shapes = SVGLoader.createShapes(shapePath);
  for (const shape of shapes) {
    const mesh = new THREE.Mesh(new THREE.ShapeGeometry(shape), material);
    scene.add(mesh);
  }
}

renderer.render(scene, camera);
```

### Live example

* [jsfiddle](https://jsfiddle.net/xp5cbvna/1/)

### Version

latest

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
> The error occurs with r148 but I couldn't figure out how to import the library with SVGLoader without the skypack cdn which only goes up to r130.

In the issue template we provide fiddles that work with the latest version of `three.js`. I've updated your fiddle so the issue is reproduced with `r149`.

**Comment by Mugen87** [comment]
Just to be clear: The SVG spec allows to define empty paths?

**Comment by eulertour** [comment]
Yes, it's mentioned [here](https://www.w3.org/TR/SVG/paths.html#PathData:~:text=Note%20that%20the%20EBNF%20allows%20the%20path%20data%20string%20in%20the%20d%20property%20to%20be%20empty.%20This%20is%20not%20an%20error%2C%20instead%20it%20disables%20rendering%20of%20the%20path.%20Rendering%20is%20also%20disabled%20when%20the%20d%20property%20has%20the%20value%20none.).
