### ISSUE TITLE
USDZExporter - Increase texture max size

### ISSUE THREAD

**Issue by elizaII** [mrdoob/three.js#25557]
### Description

When exporting to a USDZ file, the provided texture will be clamped to 1024px (see [ln 132-136](https://github.com/mrdoob/three.js/blob/29e9f905ff829a6b886ac9c232eb3aee6fab4f8b/examples/jsm/exporters/USDZExporter.js#L132)). **I would like to increase the max-size to 2048px instead, per Apple's recommendation ([source 1](https://developer.apple.com/videos/play/wwdc2018/603/?time=2166), [source 2](https://help.sketchfab.com/hc/en-us/articles/360046421631-glTF-GLB-and-USDZ)).**

With the current limitation, my texture gets too blurry when exporting to `usdz`. My use case is displaying a big print (70 x 100 cm) using AR, and with a max-size of 1024px, the resolution is not enough. 

See the comparison below:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/14200339/220902207-2e4bfd88-d772-4a87-8f3f-7b1228e1504d.png">

Both models are zoomed in to showcase the texture (a use case when displaying the model up close).
To the left is the model exported using THREE.js UsdzExporter, to the right is the model exported with Vectary. Both models have the same texture source. As you can see, the texture on the left is much blurrier due to the downscaling. 

### Solution

Change the max size for the texture when exporting to `usdz`. Change [ln 132](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/exporters/USDZExporter.js#L132) and use `2048` instead of `1024`. This would follow Apple's recommendation and allow users to export high res textures. 

### Alternatives

I've considered splitting the single plane into 4 planes and the texture into 4 images, but this is just a workaround. I prefer changing the max-size.

**Comment by Mugen87** [comment]
Instead of hard-coding a value would it be acceptable to enhance the `options` parameter of `parse()` with a new entry `maxSize`? We could keep `1024` as the default but at least you can easily inject `2048` without modifying the exporter's source code.

**Comment by elizaII** [comment]
It would be a viable solution! What is the reason to keep the default value of `1024` though? I'm not sure it's wise to let `maxSize` be anything above `2048` as it risks creating too big files that can't be opened on mobile devices. I found another [source](https://developer.apple.com/forums/thread/693867) where a graphics engineer from Apple recommend the same rules mentioned in the video.

**Comment by Mugen87** [comment]
> What is the reason to keep the default value of 1024 though?

The `1024` value was added via aa5bb104d2e74a007d19e2f08dcec3a05b134004 and I think this was done with a specific reason. But I guess it makes sense to clarify this and consider `2048` as the new default. 

In any event, enhancing `options` will definitely be a solution that works for everybody.

**Comment by elizaII** [comment]
I see, it would be nice if we were able to clarify why `1024` was chosen. Maybe it was because it was a decent size and a power of 2? Does @mrdoob answer these threads?

Yes, enhancing options could ensure backwards compatibility as well if anyone relies on the texture being clamped to `1024px` 🤔 Will you create a PR or should I try creating one?

**Comment by Mugen87** [comment]
Let's see what @mrdoob thinks about the max texture size. After that, it would be cool if you could file a PR with the change.

**Comment by mamcalli** [comment]
Hey! Just noticed it seems this issue never got resolved. Have there been any updates on what should be done about max texture size or enhancing `options`?

**Comment by hybridherbst** [comment]
I can chime in on the reason: a common use case for USDZExporter is to use these files as-is for AR QuickLook on iOS devices. This is _very_ memory constrained, and 1024x1024 is a relatively safe choice for texture resolution so "medium sized" three scenes can still be converted _and_ run on older iPhones. 2048 and 4096 can work but have a higher risk of crashing these devices. 2-3 4k textures are pretty much guaranteed to crash on older iPhones, sometimes even just one.

We've also added a new `options` parameter to specify max resolution in our fork, so this can be a per-application choice when other limits can be verified for specific scenes.

**Comment by Mugen87** [comment]
> We've also added a new options parameter to specify max resolution in our fork, so this can be a per-application choice when other limits can be verified for specific scenes.

That sounds like a good solution. I think it would be safe to make this change in `three.js` as well. Meaning a new parameter called `maxTextureSize` with default `1024`. Are you interested in making a PR with this change?

**Comment by Sov3rain** [comment]
Hey everyone! How does this issue going? Do you still need someone to take a look a this and propose a PR? I would be **really** interested to have the possibility to bump up the resolution.

My use case is making a 360 spherical view in AR Quicklook. As you may imagine, I only need 1 texture in the model, but a good one. Right now 1024 is too restrictive.

**Comment by Mugen87** [comment]
> ? Do you still need someone to take a look a this and propose a PR? 

Yes, a PR would be welcome!

**Comment by Sov3rain** [comment]
Right, I'll take a look and link to this issue when the PR is ready.
