### ISSUE TITLE
How to update release notes ?

### ISSUE THREAD

**Issue by epreston** [mrdoob/three.js#25569]
### Description

How do we submit an update to release notes ?

My user name is @epreston, theres a few variants in there.  I only have the one personal account.

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r150

**Comment by Mugen87** [comment]
It's best if you note your updates here and I'll change the document.

**Comment by epreston** [comment]
Update all variants of @epreston to @epreston 

epresto is the most common.

**Comment by Mugen87** [comment]
> Update all variants of @epreston to @epreston

Both names are equal. Do you mean @epresto?

**Comment by epreston** [comment]
Yes, thank you.  Anywhere my username is mispelled.

**Comment by Mugen87** [comment]
Okay, should be fixed now. Thanks for reporting and sorry for the inconvenience!

**Comment by epreston** [comment]
Kind of you.  Excited to read what was achieved.
