### ISSUE TITLE
Component of vue3 how insert to the scene of threejs? 

### ISSUE THREAD

**Issue by carveybunt** [mrdoob/three.js#25565]
### Description

I had a scene of `three.js` and a component of `vue3`. I wanna make the component insert into the scene by `CSS2DObject` or `CSS3DObject`, but they just support the `HTMLElement` type。
![截屏2023-02-25 19 01 27](https://user-images.githubusercontent.com/37894474/221353396-7c7ff943-29ce-4973-97fd-243a5fe888a1.png)
My component is dynamic because I need data from backend.

### Solution

Can I use `CSS2DObject` or `CSS3DObject` to make a component of `vue3` become an object supported by threejs?

### Alternatives

Have other methods come true to my idea?

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
