### ISSUE TITLE
HIT TEST WITH ANIMATION

### ISSUE THREAD

**Issue by souradeepAsh** [mrdoob/three.js#25562]
### Description

`import * as THREE from "https://cdn.rawgit.com/mrdoob/three.js/r117/build/three.module.js";
      import { GLTFLoader } from "https://cdn.jsdelivr.net/npm/three@0.121.1/examples/jsm/loaders/GLTFLoader.js";
      import { ARButton } from "https://cdn.rawgit.com/mrdoob/three.js/r117/examples/jsm/webxr/ARButton.js";
      // import Stats from "three/examples/jsm/libs/stats.module.js"
      const scene = new THREE.Scene();
      const camera = new THREE.PerspectiveCamera(
        75,
        window.innerWidth / window.innerHeight,
        0.01,
        1000
      );
      let controller, reticle;
      let hitTestSource = null;
      let hitTestSourceRequested = false;

      const light = new THREE.HemisphereLight(0xffffff, 0xbbbbff, 1);
      light.position.set(0.5, 1, 0.25);
      scene.add(light);

      const renderer = new THREE.WebGLRenderer({
        antialias: true,
        alpha: true,
      });
      renderer.setSize(window.innerWidth, window.innerHeight);
      renderer.xr.enabled = true;

      document.body.appendChild(renderer.domElement);

      document.body.appendChild(
        ARButton.createButton(renderer, { requiredFeatures: ["hit-test"] })
      );
      const geometry = new THREE.BoxGeometry(1, 1, 1);
      const material = new THREE.MeshBasicMaterial({ color: 0x00ff00 });
      const cube = new THREE.Mesh(geometry, material);
      scene.add(cube);

      camera.position.z = 5;

      let loader = new GLTFLoader();
      let model = (async function () {
        try {
          model = await loader.loadAsync("https://raw.githubusercontent.com/mrdoob/three.js/master/examples/models/gltf/Horse.glb");
          console.log("first time", model);
            let newModel = model.scene.clone();
            newModel.position.set(1, 1, 1);
            newModel.scale.set(0.01, 0.01, 0.01);
            scene.add(newModel);            
          return model;
        } catch (error) {
          console.log(error);
        }
      })();

      function onSelect() {
        const material = new THREE.MeshPhongMaterial({ color: 0xff0000 });
        const cube = new THREE.Mesh(geometry, material);
        cube.position.setFromMatrixPosition(reticle.matrix);
        // scene.add(cube);

        let horse = model.scene.clone();
        horse.position.setFromMatrixPosition(reticle.matrix);
        scene.add(horse);
      }

      controller = renderer.xr.getController(0);
      controller.addEventListener("select", onSelect);
      scene.add(controller);

      reticle = new THREE.Mesh(
        new THREE.RingGeometry(0.15, 0.2, 32).rotateX(-Math.PI / 2),
        new THREE.MeshBasicMaterial()
      );
      reticle.matrixAutoUpdate = false;
      reticle.visible = false;
      scene.add(reticle);

      function animate() {
        // requestAnimationFrame(render);
        renderer.setAnimationLoop(render);
      }

      function render(timestamp, frame) {
        if (frame) {
          const referenceSpace = renderer.xr.getReferenceSpace();
          const session = renderer.xr.getSession();

          if (hitTestSourceRequested === false) {
            session
              .requestReferenceSpace("viewer")
              .then(function (referenceSpace) {
                return session.requestHitTestSource({ space: referenceSpace });
              })
              .then(function (source) {
                hitTestSource = source;
              });

            session.addEventListener("end", function () {
              hitTestSourceRequested = false;
              hitTestSource = null;
            });

            hitTestSourceRequested = true;
          }

          if (hitTestSource) {
            const hitTestResults = frame.getHitTestResults(hitTestSource);

            if (hitTestResults.length) {
              const hit = hitTestResults[0];
              reticle.visible = true;
              reticle.matrix.fromArray(
                hit.getPose(referenceSpace).transform.matrix
              );
            } else {
              reticle.visible = false;
            }
          }
        }
        renderer.render(scene, camera);
      }

      animate();`

### Solution

I am working on a small project where i want to access the horse animation and want to show these glb scene using hit test in AR, but i can't access the animation , please some one can help me with this how i will access the animation and show it in AR... 

### Alternatives

You can check the Three Js example where you find some animation.

**Comment by gkjohnson** [comment]
Please use the [forum](https://discourse.threejs.org/) or discord if you need help with a project.
