### ISSUE TITLE
Black outline appear when the renderer sets alpha to 0.0

### ISSUE THREAD

**Issue by mandyice** [mrdoob/three.js#25584]
### Description

Set the color of the renderer to white and the alpha to 0.0
Set the visible edge color to '#000000',the black outline appear
I expect the black outline disappear

### Reproduction steps

...

### Code

```
renderer.setClearColor( 0xffffff, 0.0 );
renderer.clearColor();
...
outlinePass.visibleEdgeColor.set('#000000');
```

### Live example

* [https://jsfiddle.net/kerp40oh/](https://jsfiddle.net/kerp40oh/)

### Screenshots

![image](https://user-images.githubusercontent.com/23150125/221832040-9426cb13-41fa-40fa-ac93-3b78f84c76a7.png)

### Version

r149

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Can you please verify if the issue disappears if you set a white background color via `Scene.background` like so: https://jsfiddle.net/4q1h6akg/?

**Comment by Mugen87** [comment]
I should clarify that certain post processing effects which perform blending have issues with transparent backgrounds. It's best if you define an opaque background via `Scene.background` and don't rely on color values from the HTML background.
