### ISSUE TITLE
devtools tab in the site gives 404

### ISSUE THREAD

**Issue by guyluz11** [mrdoob/three.js#25592]
### Description

devtools tab in the site gives 404

### Reproduction steps

1. Open [https://threejs.org/](https://threejs.org/)
2. click `devtools` in the left navigation bar

### Code

No code, it is like error

### Live example

This is a link error on the site

### Screenshots

![image](https://user-images.githubusercontent.com/9304740/222136785-5ea6fa1c-9ad6-4cde-9ced-4f2cdf8a3dc4.png)

After click 

![image](https://user-images.githubusercontent.com/9304740/222136899-a6b0a3ca-6a83-4faa-bbde-420a5f174354.png)

### Version

Current site

### Device

Desktop

### Browser

Firefox

### OS

Windows

**Comment by Mugen87** [comment]
The extension has been removed from the Chrome Web Store. Probably best to just remove the link from the homepage.

**Comment by Mugen87** [comment]
Should be fixed via 4610e176f039a83cdf793859696bcfc46c586d65.
