### ISSUE TITLE
Raycaster not detecting intersection with SphereGeometry at south pole

### ISSUE THREAD

**Issue by marconett** [mrdoob/three.js#25594]
### Description

Raycaster not detecting intersection with SphereGeometry at south pole.

The live example is pretty simple. Am I missing something obvious here?

### Reproduction steps

1. Put a SphereGeometry at position `(0,0,0)`, add property `side: THREE.DoubleSide` to it's material.
2. Put a Raycaster at position `(0,0,0)`, make it point straight down.

### Code

```js
    const raycasterNorth = new THREE.Raycaster(new THREE.Vector3(), new THREE.Vector3(0, 1, 0).normalize());
    const raycasterSouth = new THREE.Raycaster(new THREE.Vector3(), new THREE.Vector3(0, -1, 0).normalize());
  
    let intersectionNorth = raycasterNorth.intersectObject(mesh, true);
    let intersectionSouth = raycasterSouth.intersectObject(mesh, true);

    // this works was expected
    if (intersectionNorth.length > 0) {
      console.log('NORTH intersects!')
    }

    // we never intersect here, the intersectionSouth Array stays empty
    if (intersectionSouth.length > 0) {
      console.log('SOUTH intersect!')
    }
```

### Live example

https://jsfiddle.net/vs0kfpzt/1/

### Version

r150

**Comment by Mugen87** [comment]
This should be a duplicate of #11449.

**Comment by marconett** [comment]
Thank you for the quick reply!

If it's the same problem, shouldn't `mesh.rotateY( 1 );` be able to fix it? I tried multiple rotation directions and values, but there were still no intersections detected.

**Comment by Mugen87** [comment]
If I change the following line:

https://github.com/mrdoob/three.js/blob/5fcbe5aed264a870087196e54a1c9f8351675298/src/math/Ray.js#L449

to 
```
if ( DdQxE2 + DdE1xQ > ( DdN + Number.EPSILON ) ) {
```
the intersection is detected. Unfortunately, this is not a complete fix for `intersectTriangle()` since all intersection tests have to be updated like that. And I'm still not sure about a proper epsilon value. Maybe using `Number.EPSILON` is already sufficient to mitigate most use cases.

**Comment by Mugen87** [comment]
> If it's the same problem, shouldn't mesh.rotateY( 1 ); be able to fix it? I tried rotating multiple dimensions and values, but there were still no intersections detected.

I've never tested the `rotateY()` workaround but I guess it does not properly work for such a symmetric use case like yours.

**Comment by marconett** [comment]
Haven't tested with the jsfiddle, but in my "real life" use-case, `+ Number.EPSILON` doesn't fix the issue. But `+ 2` does the trick.

I'm fine with patching my local three.js for now, so that's good enough for me as a workaround.

Thank you very much! I'm just going to close this issue, as it's likely a duplicate. Feel free to reopen if needed.
