### ISSUE TITLE
Build Size grows 5x with ThreeJs 0.150.0

### ISSUE THREAD

**Issue by rahulp-open** [mrdoob/three.js#25595]
### Description

I installed **threejs** in a vite project ( **vite ^4.0.0**). 
The threejs version was 0.150.0, the build size was 500kb. 
After changing the the three js version to 0.148.0 the build size reduced to 100kb.

There is a huge difference in build size between these threejs versions. Whats causing this issue?

### Reproduction steps
1. Create a vanilla typescript vite project
2. Install threejs v ^0.150.0 and import it
3. run vite build 
4. remove threejs v ^0.150.0
5. Install threejs v ^0.148.0 and import it
6. run vite build

Check the difference in build size.

### Screenshots

**three V 0.150.0 Build**
![high](https://user-images.githubusercontent.com/122882414/222392969-60b2019d-7fc0-4b2b-9364-3416899493a4.png)

**three V 0.148.0 Build**
![low](https://user-images.githubusercontent.com/122882414/222393091-a0fdd834-e48b-4fe4-ac5a-51a7e0a97da0.png)

**Vite config**
![viteconfig](https://user-images.githubusercontent.com/122882414/222393154-ebf9f2d8-9e53-4531-960a-79a4c94c7fe0.png)

### Version

0.150.0

### Device

Desktop

### Browser

Chrome

**Comment by rahulp-open** [comment]
@epreston Do you know why the issue is happening?

**Comment by epreston** [comment]
You are building a library from a library in ES format.  The expectation is the final application will do the tree-shaking.  It may be as simple as linking cjs in 148 and actual esm in 150.

What's the link to the project ?

**Comment by rahulp-open** [comment]
![image](https://user-images.githubusercontent.com/122882414/222411402-48352067-3f8e-4087-a114-8c35f8c405c8.png)

Im building a ts library with threejs.

**Comment by epreston** [comment]
Yes.  You've got a few issues.

If your project was set up correctly you would expect a maximum of 411 KB for version 148. The maximum for 150 would be 415 KB based on those dependencies.

You're getting something too small for your dependencies to be included on 148 (your 148 is not big enough to contain the required math components) and something too large on 150 for it to be three.js.  I need to see what else you have in there.

**Comment by epreston** [comment]
Link the project, I can run through it.

**Comment by marcofugaro** [comment]
This is actually a problem on our side, it can be replicated simply with:
```js
import { Scene } from 'three'
export { Scene }
```

The tree-shaking issue was introduced in #24975, that `Object.defineProperties` is preventing WebGLRenderer from being tree-shaken when not in use, resulting in the additional 400 kB you see in the bundle.

I have a solution for this, will make a PR shortly.

**Comment by LeviPesin** [comment]
> Just make it a normal member ?

Deprecation warning cannot be logged then.

**Comment by epreston** [comment]
Quick note: unit tests are not run against this on the pull request (as minimal as they are) because it's setup as webonly.  This is not my choice.  For sanity, you may want to to run the unit tests interactively in web mode to check things.

**Comment by rahulp-open** [comment]
@epreston  @marcofugaro 
https://github.com/rahulp-open/demo-proj

This is a demo project. Here you can see the difference in build sizes when we run "npm run build"  for both versions.

**Comment by rahulp-open** [comment]
@marcofugaro If you make a PR  just tag me.

**Comment by marcofugaro** [comment]
@rahulp-open I've already made a PR: #25599.
However it needs to be built to be testable.

**Comment by epreston** [comment]
@rahulp-open that test rig does not include what you are doing in the screenshots above.  It simply creates a scene object and logs it to console at the moment.  Are you done updating it ?

**Comment by epreston** [comment]
Using what you have in that demo now, I'm seeing the following:

**release r148.0**

```sh
dist/assets/index-f5119390.js   49.97 kB │ gzip: 14.47 kB
```

**release r150.1**

```sh
dist/assets/index-a180db9d.js   406.75 kB │ gzip: 103.85 kB
```

For reference, the project is creating a `THREE.Scene` object and logging it to the console.

**Comment by epreston** [comment]
I've updated your project (see https://github.com/rahulp-open/demo-proj/pull/1) to lock dependencies and build off of source instead of bundles.  This allows for consistency between tests and the ability to experiment with the changes referenced above.

Like Marco said above (https://github.com/mrdoob/three.js/issues/25595#issuecomment-1451809995), you can see how removing the `Object.defineProperties( WebGLRenderer.prototype, {` block gets the size back down.

release r150.1 (comment out block holding onto WebGLRenderer).

```sh
dist/assets/index-d7410eb8.js   59.12 kB │ gzip: 17.89 kB
```

At the start, that sounds great.  The concern I have is it's not useful or practical in isolation.  If you think about it for a few minutes, 59 kB for 80 lines of code is still extremely large.  If you want to import and export the set of classes in your screenshots, it can be much smaller with different methods.
