### ISSUE TITLE
Better Canvas handling for grabbing the canvas contents outside of three.js

### ISSUE THREAD

**Issue by BryanChrisBrown** [mrdoob/three.js#25617]
### Description

I'm working on [Looking Glass' WebXR Library](https://github.com/Looking-Glass/looking-glass-webxr) which is an Engine Agnostic platform designed to add support for Looking Glass devices to a variety of webgl based frameworks, like three, babylon, playcanvas, vtk etc. 

One of the issues I've run into with three.js lately is that it is rather difficult to capture the main framebuffer of the canvas for things like screenshots while running outside of the main animation loop. 

I've looked for some solutions however they all reference the three.js renderer, directly. I'd like to build a method that allows me to take a screenshot of the main canvas, without having to reference three's internal renderer class. 

My current screenshot method in this branch [here](https://github.com/Looking-Glass/looking-glass-webxr/blob/fbdba5d64ec3606af35d71968bf3f2c89fc5c42e/src/LookingGlassMediaController.ts#L15-L29): works in Babylon.JS currently, but not in three. 

I was wondering if it'd be possible to either revisit the API for this to make it easier to capture the canvas' contents from outside of three.js, or instead, if there's a way I can override this with the base webgl objects. 

I've tried using `gl.readpixels()` but that gives the same results as the more common `Blob` and `ToDataURL()` methods. 

Would appreciate any advice/feedback here! Thanks! 🙏🏻 

### Solution

I'd like to be able to capture the canvas outside of the main three.js render loop. 

### Alternatives

I've tried using the following methods: 

Canvas.toblob

Canvas.toDataURL

gl.readpixels()

All of these return empty images. 

What is a bit funny, is that I *can* just right click the main canvas and click "save image" but I'd like to be able to do that programmatically.

**Comment by epreston** [comment]
Have you tried queuing your canvas export so it happens in isolation of frame rendering ?  Might be a bit more compatible with all libraries.  You don't have to worry about it being locked, blocked, or corrupted.

Pseudo Code and Notes:

```js
// controllable promise utility file

// make request and cancel generic to support most browsers
const idleOptions = { timeout: 500 };
const request = window.requestIdleCallback || window.requestAnimationFrame;
const cancel = window.cancelIdleCallback || window.cancelAnimationFrame;


// controllable promise
const resolveWhenIdle = {
  request: request,
  cancel: cancel,
  promise: (num) => new Promise((resolve) => request(resolve, Object.assign({}, idleOptions, num))),
};

export { resolveWhenIdle };
```

This is an example of a controllable `promise` which will slide itself in between rendered frames of any library.  It's setup to work in browsers with and without `requestAnimationFrame`. Whatever RAF function or library you use will boil down to this.

I use it to avoid blocking my render loop when I need a delay.  You can modify it get a shot at canvas within a reasonable amount of time from button click ensuring the previous frame has fully rendered.

For example: I want something to happen after a minimum 50 ms delay, on a complete frame boundary:

```js
// my usage when sequencing animations with delays on frame boundaries.
await resolveWhenIdle.promise( 50 );

// continue with code that needs to be executed on a frame boundary
```

For your use case, this is what I would look at.

```js
// use 'then' or 'finally' knowing you allowed enough time to ensure any frame rendering in progress has completed
// and you have queued to run synchronously outside of whatever library is being used for rendering to the canvas element.
await resolveWhenIdle.promise( 10 ).finally( exportHTMLCanvasObjectContents ) ;
```

**Comment by WestLangley** [comment]
Maybe [this SO answer](https://stackoverflow.com/a/30647502/1461008).

**Comment by Mugen87** [comment]
The SO answer seems to explain the topic sufficiently. 

Next to the `preserveDrawingBuffer` approach, it's more a timing issue when you screenshot logic is executed. I can't imagine how a different API should help in this context.

**Comment by epreston** [comment]
Exactly, different API will not help.  

You want to pull the screenshot on a frame boundary as noted in the SO article.  If you don't control the application or render loop, queue up to capture a screenshot the same way the application / renderer queues to render frames.  You don't even need to use any API from any external library.

**Comment by BryanChrisBrown** [comment]
Gotcha, that makes sense!

Thanks all for the responses here, super helpful!
