### ISSUE TITLE
SimplifyModifier

### ISSUE THREAD

**Issue by calmheaded** [mrdoob/three.js#25613]
### Description

The simplified mesh is not smooth with edges and corners

### Reproduction steps

![image](https://user-images.githubusercontent.com/22089884/222684710-63f6bd4b-c2a6-4f93-8900-9aec6341eae5.png)

### Code

```js
		  {
						 
          const loader = new FBXLoader();
          loader.load(
            './static/erji/beats_highpoly.fbx', // 
            function (object) { // 
                                                        console.log(object,'object')
							 object.scale.multiplyScalar(.02);
						  	object.position.x = - 3;
                                                         scene.add(object); 
					  		const mesh = object.children[ 0 ];
								// 
								let baseGeometry = BufferGeometryUtils.mergeVertices( mesh.geometry );
							
							       const modifier = new SimplifyModifier();
							        const simplified = mesh.clone();
								simplified.material = simplified.material.clone();
								simplified.material.flatShading = true
								console.log( simplified.geometry.attributes.position.count,' simplified.geometry.attributes.position.count')
								const count = Math.floor( simplified.geometry.attributes.position.count * 0.01 ); // number of vertices to remove
								console.log(count,'count')
								simplified.geometry = modifier.modify( simplified.geometry, count );
								simplified.scale.multiplyScalar(0.02)
								simplified.position.x = 3;
								simplified.rotation.y = - Math.PI / 2;
								scene.add( simplified );
            },
            function (xhr) { 
              console.log((xhr.loaded / xhr.total * 100) + '% loaded');
            },
            function (error) {
              console.error(error);
            }
          );
					}
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

![image](https://user-images.githubusercontent.com/22089884/222683550-ba9f943b-b6f3-4e04-8b4e-6048a335bd6b.png)
When I simplify the mesh, what is the problem with the edges and corners of the simplified model
![image](https://user-images.githubusercontent.com/22089884/222683842-355d2bd5-2ff3-42e5-bd63-82049ad8c274.png)
here is my code 
![image](https://user-images.githubusercontent.com/22089884/222684289-2471fe69-5164-41d8-bf4f-8e533d77919f.png)

### Version

145dev

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
If you want a smooth surface, why are you set `flatShading` to `true`?

**Comment by calmheaded** [comment]
The gltf model I used yesterday was written in this way, and the model would turn black and no map was seen
![image](https://user-images.githubusercontent.com/22089884/222691838-d402fdc8-45b4-4037-ab54-7492678dbed3.png)
This model is gltf
![image](https://user-images.githubusercontent.com/22089884/222691942-12614fae-ba77-41b5-98fe-2807dd9f9bb6.png)

**Comment by calmheaded** [comment]
What is the reason for the loss of normals?

**Comment by Mugen87** [comment]
The simplifier only support vertices right now. 

Normals have to be recomputed, the following issue tracks the addition for supporting texture coordinates: #14058

**Comment by calmheaded** [comment]
So I wonder why I use the fbx model. The vertex changes and the map is OK, but the gltf model is not.
![Uploading image.png…]()So I wonder why I use the fbx model. The vertex changes and the map is OK, but the gltf model is not.
![Uploading image.png…]()

**Comment by calmheaded** [comment]
So I wonder why I use the fbx model. The vertex changes and the map is OK, but the gltf model is not. 
![image](https://user-images.githubusercontent.com/22089884/222696243-4be471f5-6df6-40c5-91b3-3b6ed7607d61.png)

**Comment by calmheaded** [comment]
In this way, fbx vertex changes. After the normal is recalculated, the texture coordinates change accordingly

**Comment by Mugen87** [comment]
> the texture coordinates change accordingly

I don't think that is true. The output geometry of `SimplifyModifier` has no texture coordinates. And unlike with vertex normals, there is no routine that you can use to recompute them.

**Comment by Mugen87** [comment]
Merging the issue into https://github.com/mrdoob/three.js/issues/14058.

**Comment by donmccurdy** [comment]
@Mugen87 would we be interested in adding an example showing mesh simplification using meshoptimizer? It will preserve all vertex attributes, but would probably need to be an "external" example linked by CDN.
