### ISSUE TITLE
Module parse failed: setter should have exactly one param

### ISSUE THREAD

**Issue by steve-flood** [mrdoob/three.js#25632]
### Description

:bangbang: | Module parse failed: setter should have exactly one param (2247:13)
:---: | :---
➤ | ./node_modules/three/build/three.module.js
```javascript
|         return this.source.data;
|     }
>     set image() {
|         let value = arguments.length > 0 && arguments[0] !== void 0 ? arguments[0] : null;
|         this.source.data = value;
```

### Reproduction steps

1. `npx create-next-app@latest --typescript xxx && cd xxx`
2. `npm install three @react-three/fiber`
3. `npm i -D @types/three`
4. `npm install next-transpile-modules --save-dev`
5. Follow first few steps here https://docs.pmnd.rs/react-three-fiber/getting-started/your-first-scene

### Code

Dependencies
```json
{
  "dependencies": {
    "@react-three/fiber": "^8.11.9",
    "@types/node": "18.14.6",
    "@types/react": "18.0.28",
    "@types/react-dom": "18.0.11",
    "eslint": "8.35.0",
    "eslint-config-next": "13.2.3",
    "next": "13.2.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "three": "^0.150.1",
    "typescript": "4.9.5"
  },
  "devDependencies": {
    "@types/three": "^0.149.0",
    "next-transpile-modules": "^10.0.0"
  }
}
```

### Live example

Only on my local

### Version

^0.150.1

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by marcofugaro** [comment]
The error is caused by `next-transpile-modules`, not related to three.js.

**Comment by marwie** [comment]
i had the same error and updating to `"next": "13.4.10"` fixed it for me
