### ISSUE TITLE
TransformControls attach BoundingBox or Position Offset

### ISSUE THREAD

**Issue by arcasoy** [mrdoob/three.js#25635]
### Description

Some Object3Ds in our environment have origins that are outside the bounds of the mesh. Take, for example, this sphere (mesh) inscribed in a cube (bounding box):
![material-fefnqhga](https://user-images.githubusercontent.com/32803978/223805933-14c4952d-efb8-4d06-97c6-d15653eabcd4.jpg)
Say I perform TransformControls.attach() to this Object3D, where the origin of Object3D is at point A. The TransformControls renders at point A, the origin of the Object3D, as expected. 

Now take the case where the user has zoomed in (we use OrthographicCamera) and the model is now larger inside the canvas.
![material-fefnqhga (2)](https://user-images.githubusercontent.com/32803978/223806794-65018ac4-eb7d-4047-b03f-e24041e15d1b.jpg)
In this case, as you can see, point A is now outside the field of view of the camera. When a TransformControls.attach() is performed, the gizmo renders outside the field of view of the camera. 

This behavior, although working as expected, has led to complaints from our end users that the TransformControls are not attaching, or they are but requires searching around for them.

Unfortunately, in our use case, the origin of the model cannot be modified to be in the center of the Object3D.

### Solution

An option added to the TransformControls.attach() method that renders the gizmo in the center of the bounding box of the mesh as opposed to the origin of the Object3D.

### Alternatives

The ability to perform a TransformControls attachment point offset. This is a more generalized solution that would also allow for programs to place TransformControls anywhere in scene

- The above would solve our issue by performing a bounding box calculation before attaching TransformControls, calculating the required offset from the Object3D's origin to the bounding box center and apply said offset to the TransformControls

**Comment by gkjohnson** [comment]
It's already possible to do this using a dummy object and applying the relative position and rotation offsets to the original object.

**Comment by Mugen87** [comment]
That sounds like an acceptable solution.

**Comment by arcasoy** [comment]
Glad to hear that that's the case. Would the process look something like this?:

- onClick or select of the Object3D, create a new object at the center of the clicked object's bounding box
- Attach TransformControls to new object
- Upon movement of TransformControls, get the translation or rotation offset (_which attributes would I look at in TransformControls to get this information_) and apply that offset to the position or rotation attribute of the original Object.

**Comment by Mugen87** [comment]
> (which attributes would I look at in TransformControls to get this information)

The information are not accessible in the control class itself but the transformed dummy object. Meaning it's position and rotation values.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help with this issue.
