### ISSUE TITLE
shaderMaterial: render-order with logarithmicDepthBuffer is wrong

### ISSUE THREAD

**Issue by berkaycirak** [mrdoob/three.js#25688]
### Description

Hi, In my renderer there is a logarithmicDepthBuffer and also I want to use shaderMaterial on my meshesh. However, when I add shaderMaterial, its renderOrder gets stuck. Could you help ?

### Screenshots

White sphere is without shader while red has a shader.
![Screenshot 2023-03-17 at 13 14 24](https://user-images.githubusercontent.com/81809211/225888138-6b4befa5-cbb5-4e0b-8e57-6cdd9af5e822.png) 
![Screenshot 2023-03-17 at 13 14 10](https://user-images.githubusercontent.com/81809211/225888143-5313d578-532c-4186-99f8-7548bbb4c64f.png)

### Version

0.148.0

### Device

Desktop, Mobile

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows, MacOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
