### ISSUE TITLE
Export Issues

### ISSUE THREAD

**Issue by calmheaded** [mrdoob/three.js#25684]
### Description

"When loading an fbx model and missing two maps, it can be displayed normally. However, during export, when exporting a gltf model, it is not successful. A message appears that exporting without maps is not supported."

### Reproduction steps

![image](https://user-images.githubusercontent.com/22089884/225803362-67927fa2-bc8d-42a5-9ca0-dbd42d627886.png)

result 
![image](https://user-images.githubusercontent.com/22089884/225803451-1b544c2e-12a9-4ffc-abc9-7380fb2868c1.png)

### Code

```js
const gltfExporter = new GLTFExporter();
const options = {
	  binary: false, 
    embedImages: false, 
    animations: input.animations, 
    includeCustomExtensions: true 
};
gltfExporter.parse(
	input,
	function ( result ) {
		console.log(result,'result111212')
		if ( result instanceof ArrayBuffer ) {
			saveArrayBuffer( result, 'scene.glb' );
		} else {
  //  way1
			const output = JSON.stringify( result, null, 2 );
			console.log( output );
			saveString( output, 'scene.gltf' );

		}
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

145dev

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by calmheaded** [comment]
![image](https://user-images.githubusercontent.com/22089884/225803781-e06419f4-e459-4a6f-ac85-4f5689c5437f.png)

Is it related to this part of the code

**Comment by Mugen87** [comment]
If you would use the latest version of `three.js` (or at least `r148`), `GLTFExporter` throws an exception in this case since exporters do not support textures with no image data , see #25106.

So before you export to glTF, you have to preprocess your texture and set all map properties to null when no image data are found. 

Even better would be to fix the FBX import since loading an asset with incomplete resources is an error in the first place.

**Comment by calmheaded** [comment]
Just saw the news, I changed the source code and solved it that day. Does the old version support it? Another new issue has been discovered: After exporting, even if a complete model is exported, the animation will be lost

**Comment by Mugen87** [comment]
> Does the old version support it

Yes, the mentioned fix (setting the map properties to `null`) works with older versions of `three.js`, too.

> After exporting, even if a complete model is exported, the animation will be lost

Make sure to add the animations to the `options` parameter of `GLTFExporter.parse()`, see https://threejs.org/docs/index.html?q=gltfe#examples/en/exporters/GLTFExporter.parse
