### ISSUE TITLE
Warning for "multiple three.js instances import" in Edge

### ISSUE THREAD

**Issue by FireDragonGameStudio** [mrdoob/three.js#25681]
### Description

Hi, I'm currently using VSCode, three.js v0.150.1 NPM import, with Vite bundler 4.1.0 and @vitejs/plugin-basic-ssl 1.0.1 for developing. While working fine in every other browser (Firefox, Chrome, etc...) I always get the warning: "WARNING: Multiple instances of Three.js being imported." in Edge, even though I only import three.js and no other three-dependency libraries. My first thought was, that maybe Vite does smth crazy, but the warning only appears in Edge browser. I'm using the sample code from the README.md. Happens on Glitch example too (link is attached).

It's not a major issue, but I thought it's worth mentioning it here.

br,
Max

### Reproduction steps

1. Setup a Vite project with `npm create vite@latest`
2. Enter project folder
3. `npm install` to install Vite and dependencies
4. `npm install three` to get three.js
5. Replace js code from main.js with sample code from README.md
6. (optional) install Vite basic SSL with `npm i @vitejs/plugin-basic-ssl --save-dev`
7. (optional) create vite.config.js in root and copy content from https://github.com/vitejs/vite-plugin-basic-ssl
8. run `npx vite` from terminal in VSCode

OR

1. Create new Glitch site
2. Import three.js via import map
3. create a js script, import three and e.g. create a scene
4. running the site in Edge will show the multiple instances warning.

Will run fine in most browsers, but show the warning "WARNING: Multiple instances of Three.js being imported." in Edge.

### Code

```javascript
import * as THREE from 'three';
const scene = new THREE.Scene();
```

### Live example

* [https://edge-multiple-instances-warning.glitch.me/](https://edge-multiple-instances-warning.glitch.me/)

### Screenshots

![image](https://user-images.githubusercontent.com/23502690/225606936-d367f7e3-598e-4687-9f24-8fbed4dcc907.png)
![image](https://user-images.githubusercontent.com/23502690/225607046-314496cf-bde9-44b6-a890-a40de89b1b57.png)
![image](https://user-images.githubusercontent.com/23502690/225607284-9594478f-7143-4f84-b179-d4a12b67cef6.png)

### Version

r150.1

### Device

Desktop

### Browser

Chrome, Firefox, Edge

### OS

Windows

**Comment by Mugen87** [comment]
Does the same issue happen with the official examples? https://threejs.org/examples/

If not, then this issue should be discussed at the forum. https://discourse.threejs.org/

**Comment by FireDragonGameStudio** [comment]
It happens with the official exampes too!

![image](https://user-images.githubusercontent.com/23502690/225621027-2a9c3d93-a419-4006-8df1-5ba8118300dc.png)

**Comment by FireDragonGameStudio** [comment]
sry for closing/reopening, my mouse slipped onto the wrong button :/

**Comment by FireDragonGameStudio** [comment]
@Mugen87 You're a genius! I'd never thought of that being the problem. Indeed, when I deactivate the Immersive Web Emulator the warning no longer appears! Thx for finding the cause 👍 I'll close the issue as solved!
