### ISSUE TITLE
Why do I always get an error when loading.tga maps ？

### ISSUE THREAD

**Issue by adela2** [mrdoob/three.js#25694]
### Description

Hi everyone!
I imported .zip files (.obj and .mtl) ,  I need to load a .tga map , but there is an error loading the file ，What should I do？

### Reproduction steps

1.I imported .zip files (.obj and .mtl)
2.  I need to load a .tga map 
3.  There is an error loading the file
![123](https://user-images.githubusercontent.com/27324795/226548184-6b0ab4ee-8d84-46ec-82e4-15f4a990b988.png)

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

new

**Comment by adela2** [comment]
aaa

**Comment by gitshuang** [comment]
事实上

**Comment by Mugen87** [comment]
Do you mind sharing your OBJ/MTL asset with all textures in this thread?

**Comment by adela2** [comment]
> Do you mind sharing your OBJ/MTL asset with all textures in this thread?
I  am  looking forward to your reply 

[model11.zip](https://github.com/mrdoob/three.js/files/11026987/model11.zip)

**Comment by Mugen87** [comment]
Merging this into #19781.

To clarify, the issue with TGA textures can be easily fixed by applying a custom loading manager to `MTLLoader`'s ctor.

```js
const manager = new LoadingManager();
manager.addHandler( /\.tga$/i, new TGALoader() );

const loader = new MTLLoader( manager );
```

However, even with this fix in place the editor can't load the texture definitions from the MTL file yet. Details in #19781.
