### ISSUE TITLE
TransformsControls rotation mode affect all axis despite rotating on one axis.

### ISSUE THREAD

**Issue by Maxensimon** [mrdoob/three.js#25696]
### Description

Hello!

The bug is simple. When I rotate on a single axe using the rotation mode from the TransformControls. All the axis are affected and their value change. It is also the case on the Three.js Editor website.

### Reproduction steps

1. Create a TransformControls instance
2. Attach the TransformControls to a mesh
3. Rotate on axis X for example
4. Now rotate on axis Y or Z
5. All axis become affected.

### Code

```js
// code goes here
```

### Live example

https://threejs.org/editor/

### Version

r0.150.1

### Device

Desktop

### Browser

Chrome, Firefox, Edge

### OS

Windows

**Comment by Mugen87** [comment]
> All the axis are affected and their value change.

This happens because of the quaternion/euler conversion. You can see a similar effect in Blender. This is not something than is going to be changed.
