### ISSUE TITLE
SVGLoader load svg，Coordinate origin problem

### ISSUE THREAD

**Issue by sevenyiran** [mrdoob/three.js#25702]
### Description

```
     const loader = new SVGLoader();
      // const svg = require("@/assets/icons/svg/game.svg");
      const svg = require("@/assets/icons/svg/" + node.icon + ".svg");
      const svgData = loader.parse(svg.default.content);
      const paths = svgData.paths;
```
![image](https://user-images.githubusercontent.com/125232016/226823040-ed8e6f9c-df87-4c73-8bad-489ff35edc9d.png)

![image](https://user-images.githubusercontent.com/125232016/226823181-7b3daf40-fff8-4ac2-a9b4-2b4d7be87993.png)

![image](https://user-images.githubusercontent.com/125232016/226823227-de475d25-d585-4599-9688-01b7d3062b64.png)

### Solution

需要解决SVG元素以自身中心点进行坐标转换的问题，默认svg的坐标为左上角是原点
DC convert to NDC

DC
          0 一一一一一一→
          丨                    x+
          丨
           ↓y+

NDC
                        ↑y+
                       丨
     x-               丨              x+
    ←一一一一      一一一一→
                       丨
                       丨
                        ↓y-

### Alternatives

none

### Additional context

<template>
  <el-container>
    <div id="info">
      W键：视角前进。
      <br />
      S键：视角后退。
      <br />
      A键：视角左移。
      <br />
      D键：视角右移。
      <br />
      Q键：视角上升。
      <br />
      E键：视角下降。
      <br />
      <br />
      鼠标左键长按转动：视角旋转。
      <br />
      鼠标滚轮转动：视角缩放。
      <br />
      <br />
      P键：移动模式。
      <br />
      O键：旋转模式。
      <br />
      I键：缩放模式。
      <br />
      Shift键：捕捉网格。
      <br />
    </div>
    <canvas ref="mainCanvas"></canvas>
  </el-container>
</template>

<style>
#info {
  position: absolute;
  top: 10px;
  left: 10px;
  font-size: 15px;
  color: white;
}
</style>

<script>
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls";
import { TransformControls } from "three/examples/jsm/controls/TransformControls";
import SpriteText from "three-spritetext";
import GUI from "three/examples/jsm/libs/lil-gui.module.min";
import { SVGLoader } from "three/examples/jsm/loaders/SVGLoader";
// import { SVGLoader } from "./SVGLoader.js";
import * as BufferGeometryUtils from "three/examples/jsm/utils/BufferGeometryUtils";
import { nanoid } from "nanoid";

import KEYBOARD from "@/api/3dimensional/utils/keyboardState";

export default {
  name: "Data",
  data() {
    return {
      animationId: null,
      isKeyBroadcast: true,
      person: null,
      mainCanvas: null,
      axesHelper: null,
      scene: null,
      mainCamera: null,
      orbit: null,
      controls: null,
      renderer: null,
      keyboard: null,
      clock: null,
      meshes: [],
      graphSpace: { nodes: {}, links: {} , meshGroups:[]},
      windowSizes: {
        width: window.innerWidth,
        height: window.innerHeight
      }
    };
  },
  created() {
    this.threeStart();
  },
  methods: {
    // 初始化世界
    initWorld: function () {
      // 场景
      this.scene = new THREE.Scene();
      // 辅助线
      this.axesHelper = new THREE.AxesHelper();
      this.scene.add(this.axesHelper);
      // 控制代码
      this.keyboard = new KEYBOARD.State();
      this.clock = new THREE.Clock();
    },
    // 设置星空背景
    starBackground: function () {
      const geometry = new THREE.BufferGeometry();
      const vertices = [];
      const color = new THREE.Color();
      const colors = [];
      const particles = 3000;

      for (let i = 0; i < 10000; i++) {

        vertices.push(THREE.MathUtils.randFloatSpread(2000)); // x
        vertices.push(THREE.MathUtils.randFloatSpread(2000)); // y
        vertices.push(THREE.MathUtils.randFloatSpread(2000)); // z

        color.setHSL(i / particles, 0.6, 0.7);
        color.setHSL(i / particles, 0.6, 0.7);

        colors.push(color.r, color.g, color.b);
      }

      geometry.setAttribute("position", new THREE.Float32BufferAttribute(vertices, 3));
      geometry.setAttribute("color", new THREE.Float32BufferAttribute(colors, 3));

      // 创建材质
      const material = new THREE.PointsMaterial({ size: 2, vertexColors: true });
      const points = new THREE.Points(geometry, material);
      this.scene.add(points);
    },
    // 初始化第三人称
    initPerson: function () {
      // 小滑块（模拟人物），通过设置人物为0来达到隐藏人物的效果
      const personGeometry = new THREE.BoxGeometry(0, 0, 0);
      const personMaterials = [];
      for (let i = 0; i < 6; i++) {
        const personMaterial = new THREE.MeshBasicMaterial({
          color: Math.random() * 0xffffff,
        });
        personMaterials.push(personMaterial);
      }
      // 小块（模拟人物）
      this.person = new THREE.Mesh(personGeometry, personMaterials);
      this.scene.add(this.person);
    },
    // 添加单个几何图
    addMeshGroup(node) {
      const loader = new SVGLoader();
      // const svg = require("@/assets/icons/svg/game.svg");
      const svg = require("@/assets/icons/svg/" + node.icon + ".svg");
      const svgData = loader.parse(svg.default.content);
      const paths = svgData.paths;

      // 将要合并的多个geometry放入到该数组
      let geometryArray = [];
      // 将要赋值的多个material放入到该数组
      let materialArray = [];
      for (let i = 0; i < paths.length; i++) {
        const path = paths[i];
        path.currentPath.currentPoint.x = path.currentPath.currentPoint.x / 2;
        path.currentPath.currentPoint.y = path.currentPath.currentPoint.y / 2;
        const fillColor = path.userData.style.fill;
        if (fillColor !== undefined && fillColor !== "none") {
          const material = new THREE.MeshPhongMaterial({
            color: new THREE.Color().setStyle(fillColor).convertSRGBToLinear(),
            opacity: path.userData.style.fillOpacity,
            transparent: true,
            side: THREE.DoubleSide,
            depthWrite: false,
            wireframe: false
          });

          // TODO 需要解决SVG元素以自身中心点进行坐标转换的问题，默认svg的坐标为左上角是原点
          const shapes = SVGLoader.createShapes(path);
          const geometry = new THREE.ExtrudeGeometry(shapes, {
            // 该属性指定图形沿着什么路径拉伸，如果没有指定则沿着z轴拉伸
            // extrudePath:"z",
            // 该属性提供了UV生成器函数的对象
            // UVGenerator:"",
            // 该属性指定图形可以拉伸多高，默认值是100
            depth: 300,
            // 该属性指定斜角的厚度，默认值是6
            bevelThickness: 6,
            // 该属性指定斜角的高度。默认值是bevelThickness-2
            bevelSize: -2,
            // 该属性指定斜角的分段数，段数越多斜角越光滑，默认值是3
            bevelSegments: 3,
            // 该属性指定是否启用斜角，默认true
            bevelEnabled: true,
            // 该属性指定拉伸曲线的分段数，段数越多曲线越光滑，默认值是12
            curveSegments: 12,
            // 该属性指定拉伸体被分成多少段，默认值是1
            steps: 1
          });
          geometryArray.push(geometry);
          materialArray.push(material);
        }

        const strokeColor = path.userData.style.stroke;
        if (strokeColor !== undefined && strokeColor !== "none") {
          const material = new THREE.MeshPhongMaterial({
            color: new THREE.Color().setStyle(strokeColor).convertSRGBToLinear(),
            opacity: path.userData.style.strokeOpacity,
            transparent: true,
            side: THREE.DoubleSide,
            depthWrite: false,
            wireframe: false
          });

          for (let j = 0, jl = path.subPaths.length; j < jl; j++) {
            const subPath = path.subPaths[j];
            const geometry = SVGLoader.pointsToStroke(subPath.getPoints(), path.userData.style);
            if (geometry) {
              geometryArray.push(geometry);
              materialArray.push(material);
            }
          }
        }
      }
      // 合并模型
      const mergedGeometries = BufferGeometryUtils.mergeBufferGeometries(geometryArray, true);
      const meshGroup = new THREE.Mesh(mergedGeometries, materialArray);
      meshGroup.nodeId = node.id;

      // 物体的局部缩放。默认值是Vector3( 1, 1, 1 )。
      meshGroup.scale.multiplyScalar(0.01);
      meshGroup.scale.y *= -1;

      meshGroup.position.x = node.x;
      meshGroup.position.y = node.y;
      meshGroup.position.z = node.z;

      // 在场景中添加mesh(模型)
      this.scene.add(meshGroup);

      const sprite = new SpriteText(node.text);
      sprite.color = "#fff";
      sprite.textHeight = 5;
      sprite.position.x = meshGroup.position.x;
      sprite.position.y = meshGroup.position.y + 5;
      sprite.position.z = meshGroup.position.z;
      this.scene.add(sprite);

      this.graphSpace.meshGroups.push(meshGroup);

      const box = new THREE.Box3().setFromObject(meshGroup);
      const centerVector3 = meshGroup.position.clone();
      if (box.isBox3) {
        centerVector3.x = meshGroup.position.x + (box.max.x - box.min.x) / 2;
        centerVector3.y = meshGroup.position.y - (box.max.y - box.min.y) / 2;
        centerVector3.z = meshGroup.position.z + (box.max.z - box.min.z) / 2;
        node.centerVector3 = centerVector3;
      }
      this.graphSpace.nodes[node.id] = node;
    },
    // 初始化几何图以及连接线
    initMeshes: function () {
      const graphSpace = require("./json/graphSpace.json");
      // 初始化几何图
      graphSpace.nodes.forEach(node => {
        this.addMeshGroup(node);
      });
      // 初始化连接线
      const pointsArray = [];
      graphSpace.links.forEach(link => {
        this.graphSpace.links[link.id] = link;
        const source = this.graphSpace.nodes[link.source];
        const target = this.graphSpace.nodes[link.target];
        pointsArray.push(source.centerVector3);
        pointsArray.push(target.centerVector3);
      });
      this.drawGraphLine(pointsArray);
    },
    // 画关系图的线条
    drawGraphLine: function (pointsArray) {
      const geometry = new THREE.BufferGeometry();
      //用这个api传入顶点数组
      geometry.setFromPoints(pointsArray);
      const material = new THREE.LineBasicMaterial({ color: "#fff" });
      const mesh = new THREE.Line(geometry, material);
      this.scene.add(mesh);
    },
    // 渲染世界
    renderWorld: function () {
      /*
      建模坐标系（MC）
      建模坐标系是一个局部坐标系，同时可以是一个典型的平面直角坐标系，它的出现主要是为了模型构建与变换的方便。一般而言，我们总是习惯与将基本形体或图形与某些位于物体上的角点、中心点或靠近它们的点联系起来考虑，比如在创建圆形的时候，一般将圆心作为参考点来创建圆周上其他各点，这时实质上就构建了一个以圆心为原点的参考坐标系。在对圆形进行变换时，类似地，一般以圆心为参考点来进行变换，也较为直观与方便。
                 左手坐标系
                     ↑y+
                     丨     ↗ z+
                     丨 ╱          x+
                        一一一一→
                 右手坐标系（opengl或three.js默认坐标系）
                     ↑y+
                     丨
                     丨          x+
                    ╱ 一一一一→
              z+↙
       */
      /*
      世界坐标系（WC）
      一旦对物体进行了建模，下一步就是将各个对象或者图形组合放到我们希望绘制的平面场景中。如上所述，每一个对象在创建时都有自身的建模坐标系，当我们将其组合放置在一起时，为了确定每一个对象的位置及其他对象的相对位置，就必须抛弃每一个对象自身的坐标系，将其纳入到一个统一的坐标系中，这个坐标系称为世界坐标系，也称用户坐标系，它是一个全局坐标系，也是一个典型的平面直角坐标系。这个过程实质上是将一个物体从局部空间组合装配到世界空间的变换过程。
                 左手坐标系
                     ↑y+
                     丨     ↗ z+
                     丨 ╱          x+
                        一一一一→
                 右手坐标系（opengl或three.js默认坐标系）
                     ↑y+
                     丨
                     丨          x+
                    ╱ 一一一一→
              z+↙
       */
      /*
      观察坐标系（VC）
      当二维图形场景确定后，用户可根据图形显示的要求定义观察区域和观察方向，得到所期望的显示结果，这其实是需要定义视点（或照相机）的位置与方向，完成从观察者角度对整个世界坐标系内的对象进行重新定位和描述，简化后续二维图形在投影面成像的推导和计算。因此，有必要引入观察坐标系来完成这件事情。
       */
      /*
      裁剪坐标系（VC）
       */
      /*
      规范化设备坐标系（NDC）
      为了使观察处理独立于输出设备，我们可以将对象描述转换到一个中间坐标系，这个坐标系既独立于设备，又可以容易地转变成设备坐标系。通常将这个中间坐标系称为规范化设备坐标系，其坐标范围为 [0,1]，这样可以使二维观察结果独立于可能使用的各种输出与显示设备，提高应用程序的可移植性与设备无关性。
                       ↑y+
                       丨
            x-         丨         x+
           ←一一一一      一一一一→
                       丨
                       丨
                       ↓y-
       */
      /*
      设备坐标系（DC）
      x、y
      为了便于输出二维观察结果，DC用于定义图像空间，也称为屏幕坐标系或者像素坐标系。它主要是用于某一特殊的计算机图形显示设备表面的像素定义，在多数情况下，对于每一个具体的显示设备，都有一个单独的坐标系。在定义了显示窗口的情况下，可进一步在设备坐标系中定义称为视区的有限区域。视区的成像即为实际所观察到的。设备坐标系一般都与特定的输出设备相联系，其坐标系是离散的整数值。
      浏览器屏幕坐标系(canvas坐标)，原点在左上角,注意和PC客户端的屏幕坐标系Y轴是翻转的
          0 一一一一一一→
          丨           x+
          丨
          ↓y+
      PC客户端屏幕坐标系，即通常非web渲染中的，也是OpenGL中默认的屏幕坐标系，原点在左下角
          ↑y+
          丨
          丨           x+
          0 一一一一一一→
       */
      this.axesHelper.position.x = this.person.position.x;
      this.axesHelper.position.y = this.person.position.y;
      this.axesHelper.position.z = this.person.position.z;

      // 网格物体始终面对场景中的相机
      this.person.lookAt(this.mainCamera.position);

      this.orbit.target = this.person.position;
      this.orbit.update();
      this.renderer.render(this.scene, this.mainCamera);
      // 通知按键监听
      this.keyBroadcast();
      this.animationId = window.requestAnimationFrame(this.renderWorld);
    },
    // 初始化渲染器
    initRenderer: function () {
      /**
       * 实例化透视相机
       * 为了避免边缘变形，这里将fov角度设置小一些，距离拉远一些
       * 固定视域角度，求需要多少距离才能满足完整的视野画面
       * 15度等于(Math.PI / 12)
       *
       * fov：摄像机视锥体垂直视野角度，从视图的底部到顶部，以角度来表示。默认值是50。
       * aspect：摄像机视锥体的长宽比，通常是使用画布的宽/画布的高。默认值是1（正方形画布）。
       * near：摄像机的近端面，默认值是0.1。
       * far：摄像机的远端面，默认值是2000。
       */
      const depth = 1400;
      const fov = 15;
      const aspect = this.windowSizes.width / this.windowSizes.height;
      const near = 0.1;
      const far = 2000;
      const distance = this.windowSizes.width / 2 / Math.tan(Math.PI / 12);
      const zAxisNumber = Math.floor(distance - depth / 2);

      this.mainCamera = new THREE.PerspectiveCamera(fov, aspect, near, far);
      this.mainCamera.position.set(0, 0, zAxisNumber);
      this.mainCamera.lookAt(0, 0, 0);
      this.mainCamera.position.y = 100;
      this.mainCamera.position.z = 150;

      this.scene.add(this.mainCamera);

      this.scene.add(new THREE.GridHelper(100, 10, 0x888888, 0x444444));

      const light = new THREE.AmbientLight(0xffffff, 2);
      light.position.set(1, 1, 1);
      this.scene.add(light);

      this.renderer = new THREE.WebGLRenderer({
        canvas: this.$refs.mainCanvas
      });
      this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
      this.renderer.setSize(this.windowSizes.width, this.windowSizes.height);

      // OrbitControls（轨道控制器）可以使得相机围绕目标进行轨道运动。
      this.orbit = new OrbitControls(this.mainCamera, this.renderer.domElement);

      /**
       * 变换控制器（TransformControls）
       * 该类可提供一种类似于在数字内容创建工具（例如Blender）中对模型进行交互的方式，来在3D空间中变换物体。 和其他控制器不同的是，变换控制器不倾向于对场景摄像机的变换进行改变。
       * TransformControls 期望其所附加的3D对象是场景图的一部分。
       */
      this.controls = new TransformControls(this.mainCamera, this.renderer.domElement);
      this.controls.setSize(this.controls.size + 1);

      this.controls.addEventListener("dragging-changed", (event) => {
        this.orbit.enabled = !event.value;
      });

      this.scene.add(this.controls);

      this.renderWorld();
    },
    addKeyListener: function () {
      document.addEventListener("keyup", (keyboard) => {

      });
      document.addEventListener("keydown", (keyboard) => {
        this.isKeyBroadcast = true;
      });
    },
    addClickListener: function () {
      document.addEventListener("click", (event) => {
        let pointer = new THREE.Vector2();
        // 将鼠标位置归一化为设备坐标。x 和 y 方向的取值范围是 (-1 to +1)
        pointer.x = (event.clientX / this.windowSizes.width) * 2 - 1;
        pointer.y = -(event.clientY / this.windowSizes.height) * 2 + 1;
        let raycaster = new THREE.Raycaster();
        // 通过摄像机和鼠标位置更新射线
        raycaster.setFromCamera(pointer, this.mainCamera);
        // 计算物体和射线的焦点
        // geometries为需要监听的Mesh合集，可以通过这个集合来过滤掉不需要监听的元素例如地面天空
        // true为不拾取子对象
        // intersects几何体合集
        let intersects = raycaster.intersectObjects(this.graphSpace.meshGroups, true);
        // 被射线穿过的几何体为一个集合，越排在前面说明其位置离端点越近，所以直接取[0]
        if (intersects.length > 0) {
          this.controls.attach(intersects[0].object);
        } else {
          // 若没有几何体被监听到，可以做一些取消操作
        }
      });
    },
    keyBroadcast: function () {
      if (!this.isKeyBroadcast) {
        return;
      }

      const delta = this.clock.getDelta();
      // 移动速度
      const moveDistance = 50 * delta;
      // P
      if (this.keyboard.pressed("p")) {
        this.controls.setMode("translate");
      }
      // O
      if (this.keyboard.pressed("o")) {
        this.controls.setMode("rotate");
      }
      // I
      if (this.keyboard.pressed("i")) {
        this.controls.setMode("scale");
      }

      // W键:视角前进。
      if (this.keyboard.pressed("w")) {
        this.person.translateZ(-moveDistance);
        this.mainCamera.translateZ(-moveDistance);
      }
      // S键:视角后退。
      if (this.keyboard.pressed("s")) {
        this.person.translateZ(moveDistance);
        this.mainCamera.translateZ(moveDistance);
      }
      // A键:视角左移。
      if (this.keyboard.pressed("a")) {
        this.person.translateX(-moveDistance);
        this.mainCamera.translateX(-moveDistance);
      }
      // D键:视角右移。
      if (this.keyboard.pressed("d")) {
        this.person.translateX(moveDistance);
        this.mainCamera.translateX(moveDistance);
      }
      // Q键:视角上升。
      if (this.keyboard.pressed("q")) {
        this.person.translateY(moveDistance);
        this.mainCamera.translateY(moveDistance);
      }
      // E键:视角下降。
      if (this.keyboard.pressed("e")) {
        this.person.translateY(-moveDistance);
        this.mainCamera.translateY(-moveDistance);
      }
    },
    // 屏幕坐标转世界坐标
    positionScreenToWorld: function (x, y) {
      // 屏幕坐标转标准设备坐标
      const x1 = (x / window.innerWidth) * 2 - 1;
      const y1 = -(y / window.innerHeight) * 2 + 1;
      //标准设备坐标(z = 0.5这个值并没有一个具体的说法)
      const stdVector = new THREE.Vector3(x1, y1, 0.5);
      // 标准设备坐标转世界坐标
      return stdVector.unproject(this.mainCamera);
    },
    // 世界坐标转屏幕坐标
    positionWorldToScreen: function (worldVector) {
      const centerX = this.windowSizes.width / 2;
      const centerY = this.windowSizes.height / 2;
      const standardVec = worldVector.project(this.mainCamera);

      const screenPosition = {};
      screenPosition.x = Math.round(centerX * standardVec.x + centerX);
      screenPosition.y = Math.round(-centerY * standardVec.y + centerY);
      return screenPosition;
    },
    addResizeListener: function () {
      window.addEventListener("resize", () => {
        this.windowSizes.width = window.innerWidth;
        this.windowSizes.height = window.innerHeight;

        this.mainCamera.aspect = this.windowSizes.width / this.windowSizes.height;
        this.mainCamera.updateProjectionMatrix();
        this.renderer.setSize(this.windowSizes.width, this.windowSizes.height);

        this.renderWorld();
      });
    },
    // 删除group，释放内存
    removeMeshGroup: function (group) {
      if (!group) return;
      // 循环删除掉所有的模型组内的mesh
      group.traverse(function (item) {
        if (item instanceof THREE.Mesh) {
          if (item.geometry instanceof Array) {
            item.material.forEach(geome => {
              // 删除几何体
              geome.dispose();
            });
          } else {
            // 删除几何体
            item.geometry.dispose();
          }
          if (item.material instanceof Array) {
            item.material.forEach(meta => {
              // 删除材质
              meta.dispose();
            });
          } else {
            // 删除材质
            item.material.dispose();
          }
        }
      });
      // 从当前对象的父对象中，删除当前对象
      group.removeFromParent();

      // 从控制器中移除当前3D对象，并确保控制器UI是不可见的。
      this.controls.detach();

      // 删除节点数据
      delete this.graphSpace.nodes[group.nodeId];

      // 删除模型缓存数据
      const new_set = new Set(this.graphSpace.meshGroups);
      new_set.delete(group);
      this.graphSpace.meshGroups = [...new_set];
    },
    initGui: function () {
      const api = {
        count: 2000,
        distribution: "random",
        addMeshGroup: () => {
          this.isKeyBroadcast = false;
          const pos = this.axesHelper.position;
          const node = { id: nanoid(), x: pos.x, y: pos.y, z: pos.z, icon: "safe", text: "待改名" };
          this.addMeshGroup(node);
        },
        removeMeshGroup: () => {
          const msg = "您确定要删除吗？";
          if (confirm(msg) == true) {
            this.removeMeshGroup(this.controls.object);
          }
        },
        surfaceColor: 0xFFF784,
        backgroundColor: 0xE39469,
      };
      const gui = new GUI();
      gui.add(api, "addMeshGroup");
      gui.add(api, "removeMeshGroup");
    }
    ,
    // 启动three
    threeStart: function () {
      // 在dom渲染完毕后，开始处理
      this.$nextTick(() => {
        this.initWorld();
        this.starBackground();
        this.initPerson();
        this.initRenderer();
        this.addKeyListener();
        this.addClickListener();
        this.addResizeListener();
        this.initGui();
        this.initMeshes();
      });
    }
  }
}
;
</script>

**Comment by Mugen87** [comment]
Please write your issue in English and provide a live example to demonstrate the problem.
