### ISSUE TITLE
GLTFExporter : Export multi-materials mesh

### ISSUE THREAD

**Issue by Lipacinp** [mrdoob/three.js#25729]
### Description

Hello everyone,

When I try to export a mesh with GLTFExporter, if the mesh has multi-material, a problem in my case appears.

The exported mesh ends up with a mesh for each material in the multi-material but their geometry is the same for all the meshes. This causes overlapping of geometry and the render will only display one material.

Is this the normal behavior?

Before exporting :
![image](https://user-images.githubusercontent.com/83960969/228501012-ac53c3ed-62b4-4377-9d47-95c2e44bb738.png)

After exporting:
![image](https://user-images.githubusercontent.com/83960969/228501139-b1342829-6142-4f7a-bc6c-932a4cdae55d.png)

### Reproduction steps

1. Export a multi-material mesh with GLTFExporter

### Code
```
 const exporter = new GLTFExporter();
        let gltf = await new Promise(resolve => {
            exporter.parse(
                model,
                async (gltf) => {
                    resolve(gltf)
                },
                function (error) {
                    console.log('An error happened', error);
                },
                {binary: true, onlyVisible: false, includeCustomExtensions: true}
            );
        });
```
### Live example

None

### Version

150

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Is your geometry indexed? Can you please verify if this is a duplicate of #21538?

**Comment by Lipacinp** [comment]
I presume it is not indexed : 
![image](https://user-images.githubusercontent.com/83960969/228530769-19a242eb-61ad-4675-92c6-0236f4d5239c.png)

My bad, I didn't find the issue when looking for the problems.

**Comment by Mugen87** [comment]
> I presume it is not indexed

Correct, because `index` is `null`.
