### ISSUE TITLE
PropertyBinding (animation tracks)

### ISSUE THREAD

**Issue by Caesar-Xiao** [mrdoob/three.js#25731]
### Description

the value of the argument of class PropertyBinding, "path", should be "qauaternion" instead "Mesh.qauaternion".

### Reproduction steps

when I loaded a model with tracks of animation by  r150, it thew a error, while it run normally by r149.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

![ff464041fe51cde175c0ab085123497](https://user-images.githubusercontent.com/102140923/228574617-e977f981-3c1d-43dc-a401-2d3247e12af0.png)

### Version

r150

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Can you please demonstrate the issue with a live example? 

This might be a side effect of #25329.

**Comment by Mugen87** [comment]
Closing. I'm sorry but we can't investigate your report without more information.

Next time, please properly fill out the issue template by providing live code examples.
