### ISSUE TITLE
iOS Safari WebGLRenderer Antialiasing not working from minimum 16.1.1 and up to at least 16.4

### ISSUE THREAD

**Issue by supermoos** [mrdoob/three.js#25736]
### Description

Setting antiAlias: true has no effect.

I've modified to fiddles here to illustrate the issue, and also attached screenshots of both demos taken on an iPhone 14 Pro running 16.4, and confirmed on other devices that it's an issue at least back to 16.1.1.

antiAlias: false; demo: https://jsfiddle.net/qxasef60/1/show
antiAlias: true; demo: https://jsfiddle.net/qxasef60/2/show

As you can see in the screenshots there is no anti aliasing in any of the demos, however they work correctly on desktop and other devices.

I've also attached a side by side screenshot.

![IMG_4515](https://user-images.githubusercontent.com/2298345/228834210-1b7abeb3-b579-47d6-b42c-a17585f642d4.PNG)
![IMG_4514](https://user-images.githubusercontent.com/2298345/228834223-14b4f8e9-133e-4b54-8a62-936c2320dc3e.PNG)
<img width="2672" alt="Screenshot 2023-03-30 at 14 22 28" src="https://user-images.githubusercontent.com/2298345/228834439-ed2882f5-4b02-41af-a8d7-71f12dbbd086.png">

### Reproduction steps

1. Check the demos on iOS safari
2. Confirm that setting antiAlias (true/false) has no effect.

### Code

```js
new THREE.WebGLRenderer({ antialias: true, alpha: true });
```

### Live example

https://jsfiddle.net/qxasef60/1/show
https://jsfiddle.net/qxasef60/2/show

### Version

r150

### Device

Mobile

### Browser

Safari

### OS

iOS

**Comment by supermoos** [comment]
Here's the same demos working correctly on an iPhone SE, running iOS 15.3.1.
antiAlias: true
![IMG_0002](https://user-images.githubusercontent.com/2298345/228837111-0ae1aa98-4a19-402a-9e34-ca55a0772541.PNG)
antiAlias: false
![IMG_0001](https://user-images.githubusercontent.com/2298345/228837115-132fa947-4d9e-48a6-bb49-9b3b99667564.PNG)

**Comment by supermoos** [comment]
I can confirm that on an iPad Pro 12.9" 3rd gen running 16.3.1 the issue is not there. I'll report it on webkit too, I guess the issue here can maybe be left so others can find the issue. I tried my best at googling the issue and couldn't find any reports on it, which seems weird to me given how widespread iPhones are.

**Comment by Mugen87** [comment]
Maybe not all iPhones are affected. Would be good to get more feedback from other iPhone owners.

**Comment by gonshi** [comment]
I'm having this problem on my iPhone 14Pro when I updated to 16.4. As far as I remember, it did not occur with the previous 16.3.

**Comment by Mugen87** [comment]
> I can not reproduce the issue on an iPad with iPadOS 16.3.1 and Safari. 

Funny. I've updated the iPad to iPadOS 16.4 and now the antialiasing is broken, too.

**Comment by Mugen87** [comment]
Closing. It seems this regression has already been fixed in Webkit: https://bugs.webkit.org/show_bug.cgi?id=252585
