### ISSUE TITLE
使用FBXLoader加载外部模型之后有部分内存无法释放

### ISSUE THREAD

**Issue by qaq-qwq-qvq** [mrdoob/three.js#25734]
### Description

我在vue项目中使用threejs，模型是导入的FBX格式的外部模型，模型体积有214MB
我通过FBXLoader将模型添加到场景中时在res结束后，model返回前内存增长了2G+，并且每次进入页面都会再次增长不会减少直到页面崩溃。这个时候可以确认是发生了内存泄漏
之后我在网上找到的都是使用dispose()或者remove()将模型删除，但在删除模型后每次进入页面还有1.5G+的增长，并且查看this.renderer.info的memory已经被清空
之后我还尝试过换模型（214MB和10.2MB）、换浏览器（chrome和edge）、换电脑（台式主机和surface go3）、换系统（windows10、windows11和Ubuntu）在这些情况下这个问题都存在，只是加载10.2MB模型时每次增加的内存较小
同时我还有以下几个疑问：
1、为什么214MB的模型会在加载过程中占用2G+大小？
2、这释放不掉的1.5G+中存放的是什么？
3、是我处理的方式有问题吗?如果是，还请告诉我哪里有解决办法。

### Reproduction steps

1.按照下方的方式使用FBXLoader加载模型
2.在显示模型的页面与另一个页面之间切换
3.通过浏览器的控制栏或任务管理器查看内存增长情况

### Code

```js
//加载模型的部分
const loader = new FBXLoader();
loader.load( '/static/fbx/demo.fbx', model => {
  //这之前，占用大量内存无法释放
  _this.scene.add( model );
}, res => {
  // console.log("res ",res)
 //这之后
}, err => {
  console.log("err",err)
});

//------------------------------------------------

//清除缓存的部分
beforeDestroy () {
  this.modelDispose([this.scene])
  this.scene.environment = null;
  this.scene.clear();
  this.scene.remove();
  this.renderer.dispose();
  this.renderer.forceContextLoss();
  this.renderer.content = null;
  console.log(this.renderer.info)
  this.camera = null
  this.scene = null
  this.renderer = null
  this.stats = null
  //移除div
  window.cancelAnimationFrame(this.animationID)
  let container = document.getElementById('container');
  document.body.removeChild(container);
},
methods: {
  modelDispose(objList){
    // 递归清除子级
    for(let j=0;j<objList.length;j++){
      if("children" in objList[j] && objList[j].children.length>0){
        this.modelDispose(objList[j].children)
      }else{
        objList[j].traverse((child) => {
          if (child.material) {
            child.material.dispose();
          }
          if (child.geometry) {
            child.geometry.dispose();
          }
          child = null;
        });
      }
    }
  },
}

```

### Live example

无

### Screenshots

![屏幕截图 2023-03-30 094510](https://user-images.githubusercontent.com/71418909/228706951-a5cd3da8-9f2d-4d8d-8f0f-2f0436adb7f3.png)
![屏幕截图 2023-03-30 094608](https://user-images.githubusercontent.com/71418909/228706963-e2e6ed10-489e-43b5-aaa6-098015f95bcb.png)

### Version

0.150.1

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by mrdoob** [comment]
Sorry, we can't read Chinese.

**Comment by puxiao** [comment]
this.scene.clear()
this.scene.remove()
this.scene = null

上面 3 行代码仅仅是 清空了 scene 中的子项，子项仅仅是被移除而不是销毁。

虽然你后面贴出来了一个 modelDispose(objList) 函数，但是看不出你什么时候调用了该函数(到底执行了没不能确定)。

还有一点 modelDispose(objList) 里面的代码仅仅对 顶点和材质 进行了销毁，但是 纹理 并没有销毁。
(材质销毁不意味着纹理会跟着销毁)

**Comment by JaneYork** [comment]
> this.scene.clear() this.scene.remove() this.scene = null
> 
> 上面 3 行代码仅仅是 清空了 scene 中的子项，子项仅仅是被移除而不是销毁。
> 
> 虽然你后面贴出来了一个 modelDispose(objList) 函数，但是看不出你什么时候调用了该函数(到底执行了没不能确定)。
> 
> 还有一点 modelDispose(objList) 里面的代码仅仅对 几何体和材质 进行了销毁，但是 纹理 并没有销毁。 (材质销毁不意味着纹理会跟着销毁)
> 
> _为什么214MB的模型会在加载过程中占用2G+大小？_
> 
> 简单来说模型都是 “被压缩的数据”，加载到 three.js 后需要将数据解析，其中包含 “数据解压”、“数据类型转换”，自然所占内存要大于文件本身。

后来怎么解决的？ 有大数据界面和3D模型交互，点击弹窗的案例吗？ @puxiao

**Comment by Mugen87** [comment]
Please write comments in English.
