### ISSUE TITLE
Some memory cannot be freed after loading external models using FBXLoader

### ISSUE THREAD

**Issue by qaq-qwq-qvq** [mrdoob/three.js#25735]
### Description

I use Threejs in the Vue project. The model is an imported external model in FBX format, with a volume of 214 MB

When I added the model to the scene through FBXLoader, after res, the memory increased by 2G+before the model returned, and each time I entered the page, it would grow again without decreasing until the page crashed. At this time, it can be confirmed that a memory leak has occurred

After that, all I found on the internet were using dispose() or remove() to delete the model, but after deleting the model, each time I entered the page, there was a 1.5G+increase, and I checked that the memory of this.render.info had been cleared

After that, I also tried changing models (214MB and 10.2MB), changing browsers (Chrome and Edge), changing computers (desktop and surface go3), and changing systems (Windows 10, Windows 11, and Ubuntu). This problem exists in these cases, but the amount of memory added each time the 10.2MB model is loaded is smaller

I also have the following questions:

1. Why does a 214 MB model take up 2G+size during loading? 
2. What is stored in this unreleased 1.5G+? 
3.Is there a problem with the way I handle it?If so, please also tell me where there is a solution.

I'm not sure if this is smooth because it's machine translated

### Reproduction steps

1. Use FBXLoader to load the model as follows
2. Switch between the page displaying the model and another page
3. View memory growth through the browser's control bar or task manager

### Code

```js
//add model 
const loader = new FBXLoader();
loader.load( '/static/fbx/demo.fbx', model => {
  //Previously, a large amount of memory was consumed and could not be freed
  _this.scene.add( model );
}, res => {
  // console.log("res ",res)
 //After that
}, err => {
  console.log("err",err)
});

//------------------------------------------------

//Clear cached portion
beforeDestroy () {
  this.modelDispose([this.scene])
  this.scene.environment = null;
  this.scene.clear();
  this.scene.remove();
  this.renderer.dispose();
  this.renderer.forceContextLoss();
  this.renderer.content = null;
  console.log(this.renderer.info)
  this.camera = null
  this.scene = null
  this.renderer = null
  this.stats = null
  //div
  window.cancelAnimationFrame(this.animationID)
  let container = document.getElementById('container');
  document.body.removeChild(container);
},
methods: {
  modelDispose(objList){
    // Recursive Clear Children
    for(let j=0;j<objList.length;j++){
      if("children" in objList[j] && objList[j].children.length>0){
        this.modelDispose(objList[j].children)
      }else{
        objList[j].traverse((child) => {
          if (child.material) {
            child.material.dispose();
          }
          if (child.geometry) {
            child.geometry.dispose();
          }
          child = null;
        });
      }
    }
  },
}
```

### Live example

无

### Version

0.150.1

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) to let you help with this issue.

**Comment by qaq-qwq-qvq** [comment]
> 请使用[论坛](https://discourse.threejs.org/)让您帮助解决此问题。

okay, thank you
