### ISSUE TITLE
GLTF import error

### ISSUE THREAD

**Issue by mostafamdy** [mrdoob/three.js#25738]
### Description

Hi I get this error when trying to load a GLTF model
![Screenshot 2023-03-30 173106](https://user-images.githubusercontent.com/76405917/228888166-5b6e91fa-9fc1-4e2c-9cbf-61bce84ae2da.png)

### Reproduction steps

.

### Code

.

### Live example

.

### Version

r

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by donmccurdy** [comment]
@mostafamdy please note that (1) reproducible examples are required when filing an issue on three.js, and (2) for help requests we require you to use the three.js forums, not GitHub issues. As you've commented with this question in a few places, let's continue in https://github.com/donmccurdy/glTF-Transform/issues/882.
