### ISSUE TITLE
r151 throws error when THREE-CustomShaderMaterial is based on materials that have a map

### ISSUE THREAD

**Issue by hamzakubba** [mrdoob/three.js#25742]
### Description

Reference issue: https://github.com/FarazzShaikh/THREE-CustomShaderMaterial/issues/35
Because `#define USE_UV` no longer happens (https://github.com/mrdoob/three.js/pull/25740), this code https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/uv_pars_fragment.glsl.js#L4 never happens and `vUv` is now not defined. Any shaders or logic that previously relied on it will now break, e.g: https://github.com/FarazzShaikh/THREE-CustomShaderMaterial/blob/main/package/src/shaders.ts#L26

### Reproduction steps

1. Create base material that has a texture specified as its map
2. Create a CustomShaderMaterial using that material as the base material
3. Above works on 0.150.x, breaks on 0.151.x

### Code

```js
// roughly:
const material = new MeshStandardMaterial({ map: texture });
const extendedMaterial = new CustomShaderMaterial({ baseMaterial: material });
```

### Live example

* [codesandbox (open console for error)](https://codesandbox.io/s/customshadermaterial-hero-forked-0976xh?file=/src/App.jsx)

### Version

r151

**Comment by FarazzShaikh** [comment]
I fixed it in CSM `5.3.4`, `vUv` was replaced by  `vMapUv` in <map_fragment>. Please close
