### ISSUE TITLE
WebGL issues after iOS 16.4 update.

### ISSUE THREAD

**Issue by IlyaEv25** [mrdoob/three.js#25741]
### Description

Copy of: https://developer.apple.com/forums/thread/727443#727443021

Apps like:

https://www.clicktorelease.com/code/codevember-2017/shredder-redux/ https://lab.cheron.works/webgl-gpgpu-particles/

seem to stop working with the latest iOS update(in Safari and Chrome). Those applications are particle simulations that read from texture(those are hight precision textures, which also may be a lead) in vertex shader. I have my own similar application which is also broken.

Is this a known issue? Anything to do with Three.js? Since all are three.js apps actually.

### Device

Mobile

### Browser

Chrome, Safari

### OS

iOS

**Comment by mrdoob** [comment]
> Is this a known issue?

Not a known issue, but sounds like a Safari issue.

**Comment by Mugen87** [comment]
Related #25736.

When reading the linked bugs at the Webkit bug tracker, it seems there are indeed WebGL regression when updating to iOS or iPadOS 16.4.

**Comment by LeviPesin** [comment]
Maybe we can disable WebGL 2 for some iOS versions?

**Comment by Mugen87** [comment]
Why do you think the regression only occurs with WebGL 2?

IMO, disabling features for certain OS types or even versions is no good idea. This can end up in very confusing behavior on app level. If this is really WebGL 2 related, users can fallback to `WebGL1Renderer`.

**Comment by Mugen87** [comment]
> If this is really WebGL 2 related, 

BTW: It isn't. Even WebGL 1 applications fail.

**Comment by dttrag003** [comment]
i had an error affter update to iOS 16.4, all glb is black when display on sence in threejs on both safari and chrome :( do you have any solution to fix it
