### ISSUE TITLE
primitive tag in "React three fiber" not unmount the 3D model even when destroying the parent component

### ISSUE THREAD

**Issue by bannarisoftwares** [mrdoob/three.js#25765]
### Description

Hello team, Good day. We have react app, have 2 screens and want to render the multiple 3d models on AR screens. While user tap on AR model, we want to update on Main screen. Here model rendered based on targets are working fine. The problem is , On first time, user able to select the model and able to update the Main screen. But on second time, while i am try to open the AR screen, the first time selected 3d model is always rendering on tapped position. I am able to track the second target and second target 3d model also rendering, But the first 3d model is not going and unmounting. So how to  unmount the previously selected 3d model from AR screen on each time open ?.

**SandBox Link**: https://codesandbox.io/s/ar-3d-model-unmount-issue-uf7t68

**Target 1 image url** : https://hiukim.github.io/mind-ar-js-doc/assets/images/bear-3c737546fb0bde7a9c45b45ee999d132.png

**Target 2 image url** : https://hiukim.github.io/mind-ar-js-doc/assets/images/raccoon-2ef571baece2ee4724d0d19edf3de791.png

### Reproduction steps

1. Tap the 3d model.
2. Destroy the parent component
3. Again same 3d model will come

### Code

```<>
        <group dispose={null}>
          <primitive dispose={null} key={model.url} ref={modelRef} object={scene} scale={0.4}  onClick={() => {console.log('clicked with this id '+model.id);onModelCapture(model.id);}} />
        </group>
      </>
```

### Live example

* [SandBox Link](https://codesandbox.io/s/ar-3d-model-unmount-issue-uf7t68)
* [Target 1 image url](https://hiukim.github.io/mind-ar-js-doc/assets/images/bear-3c737546fb0bde7a9c45b45ee999d132.png)
* [Target 2 image url](https://hiukim.github.io/mind-ar-js-doc/assets/images/raccoon-2ef571baece2ee4724d0d19edf3de791.png)

### Version

latest

### Device

Desktop, Mobile

### Browser

Chrome, Firefox, Safari

### OS

Windows, MacOS, Linux, Android, iOS

**Comment by donmccurdy** [comment]
Hi! It appears that you're looking for help with a React Three Fiber project. We only handle bug reports and feature requests for the three.js library via GitHub issues. I would recommend using the R3F Discord Server for this question, instead:

https://pmnd.rs/discord
