### ISSUE TITLE
Define read-only interfaces types for Vector, Box, Matrix, etc.

### ISSUE THREAD

**Issue by viridia** [mrdoob/three.js#25772]
### Description

There are many use cases for which you may want to treat a vector or other object as immutable. Here's an example:

```ts
class Actor {
  private position: Vector3;

  public getPosition(): Vector3 {
    return this.position;
  }

  public setPosition(newPosition: Vector3): {
    if (!this.position.equals(newPosition)) {
      this.position.copy(newPosition);
      this.updatePhysics();
    }
  }
}
```

In this example, whenever we move the Actor to a new location, we also update the actors's physics. The problem, however, is that `getPosition()` returns a mutable object. Mutating this object directly is a bug, since it changes the actor's position without updating the physics. Unfortunately, this is a relatively easy bug to make in a large code base where you are passing vectors around from one function to another (I've made this mistake several times). It's easy to lose track of where a vector came from and what the rules for modifying it should be.

Ideally, we'd like to enforce this in the compiler using readonly types, so as to incur no additional runtime cost. Unfortunately, simply wrapping the return result of `getPosition()` in `Readonly` does not work:

```
  public getPosition(): Readonly<Vector3> {
    return this.position;
  }
```
This is an unfortunate limitation of TypeScript's `Readonly` modifier - it can prevent direct write access to properties such as .x, but it doesn't know which methods mutate the object.

An alternative approach which does work is to declare an interface type which only exposes the immutable properties and methods of Vector3:

```ts
interface Vector3Readonly {
  readonly x: number;
  readonly y: number;
  readonly z: number;

  // Only includes methods that don't modify the vector
  length(): number;
  lengthSquared(): number;
  // etc...
}

class Vector3 implements Vector3Readonly {
   // etc.
}
```

Note: if you don't like the name "Vector3Readonly" alternatives are "IVector3" or "Vector3Like".

However, using this new interface type is very inconvenient when you want to pass it back to three.js - you have to do an explicit cast everywhere:

```ts
tempVector.copy(vec as Vector3);
```

To avoid this, we also need to modify the type signatures of every three.js method that accepts a readonly vector - so for example the signature for `copy` becomes `copy(v: Vector3Readonly)`. Now we can use immutable vectors without having to cast them. Regular `Vector3`s also work, because they have a shape which is compatible with `Vector3Readonly`.

A somewhat different use case involves vectors that are produced by other non-three.js libraries. For example, the Rapier physics library also exports a type called `Vector3` which simply has an x, y, z property and no methods. Passing a vector from one library to another requires converting or casting the vector from one to another. Casting is technically incorrect but works fine:

```ts
   actor.position.copy(rigidBody.translation() as Vector3);
```

Even though the return value of `rigidBody.translation()` is not a three.js `Vector3`, it has the right shape. (There are some other Rapier types like this, such as `Quaternion`). The `copy()` method doesn't actually need a Vector3, it just needs an object with x, y and z properties.

So the general ask here, then, is that three.js methods should declare as their parameter types as the shape they need, rather than a concrete type.

### Solution

(see discussion above)

### Alternatives

n/a

**Comment by LeviPesin** [comment]
This is not the right place to discuss types. Three.js' types are managed by [three-types/three-ts-types](https://github.com/three-types/three-ts-types).
