### ISSUE TITLE
JavaScript wrapper for Three.js module 

### ISSUE THREAD

**Issue by andreasrosdal** [mrdoob/three.js#25770]
### Description

From r160 Three.js will remove the plain vanilla JavaScript build of Three.js, and the module build must be used instead.

However, rewriting existing JavaScript applications to JavaScript modules can be a lot of work. 

### Solution

I therefore propose that a plain JavaScript wrapper be implemented to support existing users of Three.js who want to continue using Three.js in the classic way.

### Alternatives

Rewriting the game to JavaScript modules is too much work at the moment. I am also considering a legacy JavaScript fork of Three.js :)

- Alternative: support legacy JavaScript compatibility forever.

### Additional context

I am currently making www.fciv.net which is a 3D fork of Freeciv: https://github.com/fciv-net/fciv-net

**Comment by donmccurdy** [comment]
The legacy UMD/Global build in build/three.js and build/three.min.js is the most practical way we have to support the classic way, and maintaining it (and all of the usage patterns and support that involves) is a problem. This is why we've been moving toward ESM over the past few years. 

As far as I can see, a "plain JavaScript wrapper" would be the same thing as we are maintaining now, and trying to move away from. Anyone is certainly free to build three.js from source, targeting whatever module format you prefer. But it would do us no good to replace these builds with another version of the same thing.

If you or others would like to create a repository that wraps or repackages three.js in this way, I think that'd be great.

**Comment by andreasrosdal** [comment]
Importing Three.js in the way suggested by @LeviPesin worked worrectly.

However, I need to load these additional modules:
AnaglyphEffect.js  OrbitControls.js  Refractor.js  GLTFLoader.js      Reflector.js        Water2.js

How can I import these modules in a similar way?

**Comment by LeviPesin** [comment]
Just the same.
```html
<script type="module">
import { OrbitControls } from 'path/to/file';
window.THREE.OrbitControls = OrbitControls;
</script>
```
