### ISSUE TITLE
ColladaLoader issue (with DAE meshes)

### ISSUE THREAD

**Issue by yvanblanchard** [mrdoob/three.js#25787]
### Description

Hello,

When using ColladaLoader with DAE meshes files, I have some errors:

> Invalid opaque type 'null' of transparent tag.

Here is the content of one of the DAE file:
![image](https://user-images.githubusercontent.com/63931618/230566233-e598001e-bea7-4600-ab02-73e3b3728672.png)

I used a URDF parser here, that uses the ThreeJS ColladaLoader.

### Reproduction steps

1. Run the URDF parser web app (Chrome borwser) : https://github.com/gkjohnson/urdf-loaders/issues/256#issuecomment-1500032330
2. Drag and drop the folder containing urdf and DAE files : https://github.com/gkjohnson/urdf-loaders/files/11156589/lbr_iiwa7_r800-urdf-package-master.zip
3.Result: error messages in JS script console of Chrome, and 3D viewer is empty.

### Code

None.

### Live example

Use the urdf loader (online web app):
https://github.com/gkjohnson/urdf-loaders/issues/256#issuecomment-1500032330

### Screenshots

Error messages:

![image](https://user-images.githubusercontent.com/63931618/230566109-de9593c1-f60a-4cd7-aa71-37f11445cfb5.png)

### Version

2023

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Can you please share one DAE file that produces the warning in this thread?

**Comment by Mugen87** [comment]
> But this file comes from package linked to the issue of URDF parser web app. Are you able to test this URDF parser yourself ?

No, sorry. We do not support the URDF parser in this repository.

Even with the attached DAE file I can not reproduce the issue by importing it into the [three.js editor](https://threejs.org/editor/). I suggest you continue the discussion at the URDF repository.

Sorry for the back and forth.
