### ISSUE TITLE
fbx loads the bvh animation

### ISSUE THREAD

**Issue by 1229064537** [mrdoob/three.js#25802]
### Description

1：any .fbx  can loads the  any .bvh animation

### Solution

Models and animations are separated from each other and can be loaded dynamically instead of animations being built into the model

### Alternatives

fbx and bvh were respectively loaded and fused through the animation mixer, but the model did not move according to bvh. I checked a lot of materials but failed to find successful cases. Many users have requirements and hope to officially produce a demo

**Comment by Mugen87** [comment]
If this issue is about retargeting, it's better to merge it into #25751.

If retargeting is not required, please let you help at the [forum](https://discourse.threejs.org/).
