### ISSUE TITLE
make traverse async

### ISSUE THREAD

**Issue by ieskudero** [mrdoob/three.js#25829]
### Description

I have an application that renders only on demand (mouse move, button  pressed ...) since it has an static scene an in this way it can have a lower battery consumption. For texture loading I use the call new TextureLoader().loadAsync, but I use it inside a traverse call, since there are children that must have a texture. The problem is that the callback of traverse is not awaited, making the async code delay the texture painting, and since I have a render on demand, there is no texture when I render the scene.

### Solution

The solution would be to make the traverse call async :

	async traverse( callback ) {

		await callback( this );

		const children = this.children;

		for ( let i = 0, l = children.length; i < l; i ++ ) {

			await children[ i ].traverse( callback );

		}

	}

Making it this way there is no broken code and callbacks are awaited.

### Alternatives

An alternative would be to make a new method called traverseAsync, but there are other traverse methods, such as traverseVisible and traverseAncestors that also could be async, so I guess it is cleaner to make them all async instead of creating 3 more methods.

**Comment by LeviPesin** [comment]
In the use case you are describing awaiting callbacks will mean that a texture download can start only after the previous one is finished, which I think isn't what you want. Can't you just create an array, push in each callback a promise to it, and then await them all with `Promise.all`?

**Comment by Mugen87** [comment]
Please ask for the [forum](https://discourse.threejs.org/) for help. You issue can surely be addressed without changing the API.
