### ISSUE TITLE
Compact and combined Transform / Position Controls 

### ISSUE THREAD

**Issue by atomicra** [mrdoob/three.js#25837]
### Description

I would like introduce Compact and combined Transform / Position Controls for Thee Js

### Solution

https://github.com/atomicra/AtomiControl/blob/main/src/AtomiControl.js

### Alternatives

https://github.com/atomicra/AtomiControl/blob/main/src/AtomiControl.js

**Comment by Mugen87** [comment]
One control class that implements object transform abilities should be sufficient. There is also #25619 that might has a higher priority than a compact/alternative version of `TransformControls`. So for now, it's best if your control class is located in its own repository.
