### ISSUE TITLE
WebGLProgram Shader Error when loading glb model in three.js r151

### ISSUE THREAD

**Issue by Victorfy1214** [mrdoob/three.js#25836]
### Description

Although I did not use shaders to render my model, I encountered this error when upgrading the three.js version from r150 to r151.

**THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false
Program Info Log: Vertex shader is not compiled.
VERTEX
ERROR: 0:373: ‘uv2’ : undeclared identifier
ERROR: 0:373: ‘constructor’ : not enough data provided for construction**

### Reproduction steps

1.Change the version number of three. js in the project
2.Load my model which can render normally in the r150 version
3.Check the console and you will see the error message

### Code

_Please check my live examples, I have provided a demo that runs normally under version r150.1 and another that reports errors in version r151.3._

### Live example

* [three.js-r151.3-error](https://jsfiddle.net/VictorFang1214/L069woe7/2/)
* [three.js-r150.1-correct](https://jsfiddle.net/VictorFang1214/znvx68pe/)

### Version

r151.3

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by digitalArt3DTobias** [comment]
Just a quick guess: Since your error says: "_'uv2' : undeclared identifier_": May it be that this info from the [Migration Guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide#150--151) helps?

"_aoMap and lightMap no longer use uv2. Set material.lightMap.channel to 0 for uv and 1 for uv2. Consequently, the uv2\_* shader chunks have been removed._"

**Comment by Victorfy1214** [comment]
> Just a quick guess: Since your error says: "_'uv2' : undeclared identifier_": May it be that this info from the [Migration Guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide#150--151) helps?
> 
> "_aoMap and lightMap no longer use uv2. Set material.lightMap.channel to 0 for uv and 1 for uv2. Consequently, the uv2_* shader chunks have been removed._"

Thank you for your suggestion. The method in the Migration Guide fixed the above errors, but also raised other issues. When I load another model in my project, the texture appears confused. While  set material.lightMap.channel to 0, the render result is 
the first picture below, and the correct result should be the second one.
<img width="368" alt="error" src="https://user-images.githubusercontent.com/36722161/232224921-19a43e7b-e979-4ca9-a8c6-d16189180645.png">
<img width="424" alt="correct" src="https://user-images.githubusercontent.com/36722161/232224929-9db61a61-962d-49cf-8ada-43d03ca38af1.png">

**Comment by donmccurdy** [comment]
The model has validation errors, visible at https://github.khronos.org/glTF-Validator/. The materials specify that the occlusion texture should use the 2nd UV set, but the model contains no 2nd UV set. This worked in previous versions of three.js where mappings to UV sets were hard coded and GLTFLoader automatically copied the 1st UV set into a 2nd UV set if needed, but r151 is more flexible, supports any mapping, and so we removed that automatic creation of a 2nd UV set.

Error | Message | Pointer
-- | -- | --
MESH_PRIMITIVE_TOO_FEW_TEXCOORDS | Material is incompatible with mesh primitive: Texture binding '/materials/0/occlusionTexture' needs 'TEXCOORD_1' attribute. | /meshes/0/primitives/0/material
MESH_PRIMITIVE_TOO_FEW_TEXCOORDS | Material is incompatible with mesh primitive: Texture binding '/materials/1/occlusionTexture' needs 'TEXCOORD_1' attribute. | /meshes/1/primitives/0/material
MESH_PRIMITIVE_TOO_FEW_TEXCOORDS | Material is incompatible with mesh primitive: Texture binding '/materials/1/occlusionTexture' needs 'TEXCOORD_1' attribute. | /meshes/2/primitives/0/material
MESH_PRIMITIVE_TOO_FEW_TEXCOORDS | Material is incompatible with mesh primitive: Texture binding '/materials/2/occlusionTexture' needs 'TEXCOORD_1' attribute. | /meshes/3/primitives/0/material

I don't think this is something we should change in three.js, the new behavior is more useful and more correct than the old. A workaround would be to load the model in https://gltf.report and run the script below:

```js
for (const material of document.getRoot().listMaterials()) {
	const info = material.getOcclusionTextureInfo();
	if (info) info.setTexCoord(0);
}
```

**Comment by donmccurdy** [comment]
Hm, the model was created by THREE.GLTFExporter. This we should definitely fix:

https://github.com/mrdoob/three.js/blob/dfb2b176ba47f224cfeee12ec004cd2093cc3b59/examples/jsm/exporters/GLTFExporter.js#L1476-L1481

**Comment by donmccurdy** [comment]
- cc https://github.com/mrdoob/three.js/pull/25843

**Comment by Victorfy1214** [comment]
> The model has validation errors, visible at https://github.khronos.org/glTF-Validator/. The materials specify that the occlusion texture should use the 2nd UV set, but the model contains no 2nd UV set. This worked in previous versions of three.js where mappings to UV sets were hard coded and GLTFLoader automatically copied the 1st UV set into a 2nd UV set if needed, but r151 is more flexible, supports any mapping, and so we removed that automatic creation of a 2nd UV set.
> 
> Error	Message	Pointer
> MESH_PRIMITIVE_TOO_FEW_TEXCOORDS	Material is incompatible with mesh primitive: Texture binding '/materials/0/occlusionTexture' needs 'TEXCOORD_1' attribute.	/meshes/0/primitives/0/material
> MESH_PRIMITIVE_TOO_FEW_TEXCOORDS	Material is incompatible with mesh primitive: Texture binding '/materials/1/occlusionTexture' needs 'TEXCOORD_1' attribute.	/meshes/1/primitives/0/material
> MESH_PRIMITIVE_TOO_FEW_TEXCOORDS	Material is incompatible with mesh primitive: Texture binding '/materials/1/occlusionTexture' needs 'TEXCOORD_1' attribute.	/meshes/2/primitives/0/material
> MESH_PRIMITIVE_TOO_FEW_TEXCOORDS	Material is incompatible with mesh primitive: Texture binding '/materials/2/occlusionTexture' needs 'TEXCOORD_1' attribute.	/meshes/3/primitives/0/material
> I don't think this is something we should change in three.js, the new behavior is more useful and more correct than the old. A workaround would be to load the model in https://gltf.report and run the script below:
> 
> ```js
> for (const material of document.getRoot().listMaterials()) {
> 	const info = material.getOcclusionTextureInfo();
> 	if (info) info.setTexCoord(0);
> }
> ```

Thank you for your patience and professional explanation. Now I understand the reason for this error.I will modify my model according to the report.Thank you very much for your help!
