### ISSUE TITLE
GroundProjecedEnv Module Not Found

### ISSUE THREAD

**Issue by ayodyln** [mrdoob/three.js#25852]
### Description

I've just installed a new SvelteKit app and installed Three and Threlte libraries. Once I've set up everything, I tested it in my dev server. Following the video example by [Joy of Code](https://www.youtube.com/watch?v=89LYeHOncVk&t=2090s), with the goal to import a .glb file and render it to screen. 

Once I run the dev server, I get an error saying, "Cannot find module 'three/examples/jsm/objects/GroundProjectedEnv' from my local working directory.  After reading that, I looked in my local installed pkg for ThreeJS and found no file exists. After that, I found this pull request [Examples: Rename GroundProjectedEnv to GroundProjectedSkybox. #25645](https://github.com/mrdoob/three.js/pull/25645). 

I changed that local file `GroundProjectedSkyBox` to the name it was searching for and everything started working as normal. Also changed the exported classes to reflect that name. 

This is my first issue with a public repository like this, so I hope I did my best here to provide information or hope this is worth the issue. But I felt like it was a good first chance to try this, if there is any more information needed I can provide that. 

### Reproduction steps

1. npm create svelte
2. npm i
3. npm i @threlte/core @threlte/extras three
4. npm i -D @types/three
5. followed Joy of Code Example
6. Added a GLTF component to render my ThreeJS.glb file I made with Adobe Dimension.
7. npm run dev
8. After compile, it breaks and produces that error mentioned above.

### Code

```svelte
<script lang="ts">
	import * as Threlte from '@threlte/core';
	import * as Three from 'three';
	import * as Extra from '@threlte/extras';

	let obj = {
		position: { x: 0, y: 0, z: 0 },
		scale: 50
	};
</script>

<div>
	<Threlte.Canvas>
		<!-- Camera Code -->
		<Threlte.PerspectiveCamera position={{ x: 20, y: 20, z: 20 }} fov={50}>
			<!-- Controls -->
			<Threlte.OrbitControls autoRotate />
		</Threlte.PerspectiveCamera>

		<!-- Lights -->
		<Threlte.AmbientLight color="white" intensity={0.2} />

		<!-- Light and Shadows -->
		<Threlte.DirectionalLight
			color="white"
			intensity={2}
			position={{ x: 10, y: 10 }}
			shadow={{ camera: { top: 0 } }}
		/>

		<!-- My object -->
		<Extra.GLTF url="/ThreeJS.glb" {...obj} receiveShadow castShadow />

		<!-- floor -->
		<Threlte.Mesh
			geometry={new Three.PlaneGeometry(20, 20)}
			material={new Three.MeshStandardMaterial({ color: 'white', side: Three.DoubleSide })}
			receiveShadow
		/>
	</Threlte.Canvas>
</div>

<style>
	div {
		width: 100%;
		height: 100%;
		position: absolute;
		inset: 0;
		background: radial-gradient(hsl(220 14% 20%), hsl(220 20% 10%));
		background-attachment: fixed;
	}
</style>
```

### Live example

N/A

### Screenshots

![Screenshot 2023-04-16 at 12 08 25 PM](https://user-images.githubusercontent.com/78442693/232335131-1c1047c4-4870-4627-89b6-8e2f194b9474.png)

### Version

0.151.3

### Device

Desktop

### OS

MacOS

**Comment by ayodyln** [comment]
I just now had a thought that this may be an issue with Threlte it self. If that's the case, I can go down that route.

**Comment by Mugen87** [comment]
We have noted in the migration guide for `r151` that the file has been renamed (https://github.com/mrdoob/three.js/wiki/Migration-Guide#150--151). Please file an issue at the Threlte repo so they can use the renamed class.
