### ISSUE TITLE
materials / envmaps / hdr demo: "generated" envMap broken on iOS/Safari 16.4

### ISSUE THREAD

**Issue by rediche** [mrdoob/three.js#25862]
### Description

After upgrading to iOS 16.4 the EnvMap HDR demo's "Generated" environment map breaks in Safari.

The EnvMap does not seem to be generated correctly and causes an entirely black screen.
It would be expected, that the background would be light-gray when choosing the "Generated" EnvMap as it the case in various other browsers.

This is not an issue on iOS 16.3 (See attached screenshots further down for a comparison)-

### Reproduction steps

1. Open [EnvMaps HDR demo](https://threejs.org/examples/?q=envmap#webgl_materials_envmaps_hdr) on Safari 16.4
2. Change `envMap` to `Generated`
3. Screen goes black

### Code

```js
// code goes here
```

### Live example

* [ThreeJS Materials / EnvMaps / HDR demo](https://threejs.org/examples/?q=envmap#webgl_materials_envmaps_hdr)

### Screenshots

iOS Safari 16.4 Generated HDR EnvMap
![iOS Safari 16 4 Generated EnvMap](https://user-images.githubusercontent.com/5726886/232415901-2e72641b-872c-44fd-a3ea-9a99acb64f33.jpg)

iOS Safari 16.3 Generated EnvMap
![iOS Safari 16 3 Generated EnvMap](https://user-images.githubusercontent.com/5726886/232415907-b606b95d-fc18-45c3-8149-cfbe2010593b.png)

### Version

r151

### Device

Mobile

### Browser

Safari

### OS

iOS

**Comment by Mugen87** [comment]
iOS 16.4 has some WebGL regression that we can't fix on engine level. We have to wait until Apple patches Safari/Webkit.

**Comment by rediche** [comment]
@Mugen87 Do you happen to have a reference to a Webkit issue with the problem?

**Comment by Mugen87** [comment]
Related #25741, #25736.

**Comment by rediche** [comment]
An update on our end: Safari 16.5 has released and it seems to have resolved the issue on the above demo.
