### ISSUE TITLE
Virtual Texturing

### ISSUE THREAD

**Issue by elfrank** [mrdoob/three.js#2587]
Hi,

I have a virtual texturing implementation (with some bugs to fix) based on "Virtual Texture Mapping 101" published in GPU Pro.

Virtual Texturing looks like this: http://schumann.elis.ugent.be/ (this is not mine, it's just an example available on internet which is not using three).

I haven't had time to finish the implementation, but it should be ready in the following weeks. I think that it would be a great addition to three. What do you think?

What do I have to do to make a pull request and saving you from refactoring code? I will try to write a standalone example and send you the link as soon as I get it fully working.

Thanks.

**Comment by looeee** [comment]
@elfrank did anything over come of this?

**Comment by WestLangley** [comment]
Closing due to age, outdated links.
