### ISSUE TITLE
CSS3DSprite works on the pc but not on iOS。

### ISSUE THREAD

**Issue by nikolawarren** [mrdoob/three.js#25897]
### Description

I use css3DSprite in my project， it works on the pc but not on iOS。 my three.js version is 151 ，ios version is 14.1 

### Reproduction steps

null

### Code

```
initScene() {
        let container = document.getElementById("container")
        this.width = container.offsetWidth
        this.height = container.offsetHeight
        this.scene = new THREE.Scene();
        this.camera = new THREE.PerspectiveCamera(45, this.width / this.height, 1, 1000);
        this.scene.add(this.camera);
        this.camera.position.set(0, 30, 50)
        //this.setting.this.scene.antialias
        this.renderer = new THREE.WebGLRenderer({alpha: true, antialias: antialias: false, logarithmicDepthBuffer: false});
        this.renderer.outputEncoding = THREE.sRGBEncoding;
        this.renderer.setSize(this.width, this.height);
        // this.renderer.setPixelRatio(window.devicePixelRatio);
        container.appendChild(this.renderer.domElement)

        this.labelRenderer = new CSS3DRenderer();
        this.labelRenderer.setSize(this.width, this.height);
        this.labelRenderer.domElement.style.position = 'absolute';
        this.labelRenderer.domElement.style.top = 0;
        this.labelRenderer.domElement.style.pointerEvents = 'none';
        container.appendChild(this.labelRenderer.domElement)
 },
```

```
loadNameSprite(character, username, color) {
        var div = document.createElement('div');
        div.className = 'label_name';
        div.style.color = color
        div.textContent = username;
        var sprite = new CSS3DSprite(div);
        sprite.name = 'username'
        sprite.scale.set(0.01, 0.01, 0.01)
        character.add(sprite)
        sprite.position.set(0, 2, 0)

      },
```

```
animate() {
        this.renderer.render(this.scene, this.camera);
        this.labelRenderer.render(this.scene, this.camera)

        requestAnimationFrame(this.animate);
}
```

### Live example

null

### Screenshots

![ad244c1f0b6e71cb99d917b67f69296](https://user-images.githubusercontent.com/50712935/233562475-ca3d1d6e-d513-4efc-a3ac-cc182dea37e7.jpg)

the screenshot is on the ios

![1682061016666](https://user-images.githubusercontent.com/50712935/233566244-cff79569-9523-4609-9b8b-382bbcab4aac.jpg)

the screenshot is on the pc (window)

### Version

151

### Device

Mobile

### Browser

Safari

### OS

iOS

**Comment by nikolawarren** [comment]
> Please ask at the [forum](https://discourse.threejs.org/) for help first. If it turns out to be an issue in the engine, we can reopen.

I saw the same issue , but it was closed and there was no solution

**Comment by Mugen87** [comment]
If you referring on #25848, the issue was in Chinese so I was unable to read it.

In any event, the issue would have been closed for the same reasons like this one since the forum is the better place for distinct between app, browser or engine related issue.
