### ISSUE TITLE
Errors loading glb with draco decoder (v1.5.6 on iOS 14.x)

### ISSUE THREAD

**Issue by inear** [mrdoob/three.js#25893]
### Description

Draco decoder v1.5.6 started to throw errors in iOS 14.x:

[Error] Unhandled Promise Rejection: RuntimeError: Aborted(CompileError: WebAssembly.Module doesn't parse at byte 58: invalid opcode 192, in function at index 16). Build with -sASSERTIONS for more info. (evaluating 'new WebAssembly.RuntimeError(e + '. Build with -sASSERTIONS for more info.')')

This is not an issue with the three.js code base, but thought there could be users here that have apps and sites running that might want to test on iOS 14 after migrating to three.js version 151 (where you have to update the draco loader from the examples folder also). Did not see the issue before the migration.

### Reproduction steps

1. Use three version 151 or above and DracoLoader 1.5.6
2. Start a site where you load a glb with the dracoloader on iOS 14 (in Browserstack)

### Code

-

### Live example

-

### Version

151.0.3

### Device

Mobile

### Browser

Safari

### OS

iOS

**Comment by mrdoob** [comment]
Always good to explain why the issue was closed in case someone else ends up here.

**Comment by inear** [comment]
Sure, sorry! I realized the issue was badly written (and draco-example worked) so wanted to remove it quickly before I found the solution to my problem, but could not find a delete-button. 

I just now found a solution to my problem. By adding setDecoderConfig({ type: 'js' }) it worked again, disabling webassembly.
