### ISSUE TITLE
Chrome/Edge bug: texture loading fails on fast devices

### ISSUE THREAD

**Issue by digitalArt3DTobias** [mrdoob/three.js#25905]
### Description

For a given gltf model, gltf imports are working absolutely fine on slower computers, but texture loading fails reliably in Chrome on faster computers (for the same model). 

### Reproduction steps

I purchased this gltf model from Sketchfab for testing purposes: https://sketchfab.com/3d-models/mountain-dragon-animations-347cae9f87104374bc3ac554d9d3fd6e.

Since the problem may be related to specific file sizes, resp. file sizes ratio, here are the model's (sorted) file sizes:

```
 15 KB   emissive map
256 KB   gltf 
  9 MB   diffuse map
 11 MB   normal map
 13 MB   bin
 21 MB   ao/metallic/roughness map
```

I've converted the gltf folder to a glb file using this tool: https://github.com/CesiumGS/gltf-pipeline.

The behavior summarized above is exactly the same, no matter whether I use https://gltf-viewer.donmccurdy.com/ (screenshots 1, 3, 5), https://threejs.org/editor/ (`autosave` disabled, screenshots 2, 4, 6), or my own model viewer, built with threejs, where I first discovered this problem:

1. On my faster computers (a workstation and a fairly fast consumer computer), loading the `ao/metallic/roughness map` fails (almost) always (screenshots 1 and 2).
2. Sometimes the `normal map` doesn't load either on these computers (screenshots 3 and 4). 
3. However, when I set GPU throttling to `6x slowdown` in the Performance tab, texture loading works without any problems (screenshots 5 and 6). - BTW: Network throttling or disabling the cache has no effect.
4. The problem never occurs on any of my slower computers, and the problem never occurs when using Firefox, even on my faster computers (maybe since FF seems to be slower in this regard anyway?).
5. I also made the same tests with the original model folder (not converted to glb). The only difference is that on my faster devices slowing down the GPU speed artificially (see 3.) doesn't help (but 1., 2. and 4. behave exactly like above).

I used several Windows 10/11 computers with the latest Chrome (112.0.5615.138) for my tests.

Since my test model is not available for free on Sketchfab, I guess, I'm not allowed to share it here publicly. 

### Code

.

### Live example

.

### Screenshots

Screenshot 1:

![gltf-problem-1](https://user-images.githubusercontent.com/130747909/233771312-d315b1c5-e1a8-4471-8b85-6df0941bc19d.jpg)

Screenshot 2:

![gltf-problem-2](https://user-images.githubusercontent.com/130747909/233771314-e200616f-8743-4d59-a876-ea834e3f46f2.jpg)

Screenshot 3:

![gltf-problem-3](https://user-images.githubusercontent.com/130747909/233771316-f4c22419-8ecb-4d47-992a-cb2a8aeb5ef8.jpg)

Screenshot 4:

![gltf-problem-4](https://user-images.githubusercontent.com/130747909/233771317-176dc12a-ad0f-4c6f-8fef-1d8b41a121af.jpg)

Screenshot 5:

![gltf-problem-5](https://user-images.githubusercontent.com/130747909/233771318-62764318-8a68-48bb-97be-71190d0d6875.jpg)

Screenshot 6:
![gltf-problem-6](https://user-images.githubusercontent.com/130747909/233774724-f9ca33ca-b5de-4a8e-955c-247611c2cb08.jpg)

### Version

r151

### Browser

Chrome

### OS

Windows

**Comment by donmccurdy** [comment]
While I understand it may not be possible to share the file in question here, I'm not sure there's anything I can do to investigate the issue without that. If you're open to debugging further, I would suggest setting a breakpoint in this section of GLTFLoader, and possibly commenting out the `URL.revokeObjectURL` line, to see if it's possible to narrow down why that error is being thrown:

https://github.com/mrdoob/three.js/blob/2d1621f76a92a5f17527cc0c1d4a9be546ab6416/examples/jsm/loaders/GLTFLoader.js#L3091-L3106

**Comment by digitalArt3DTobias** [comment]
Thanks for your suggestion!

In those cases when texture loading fails, the whole `then` block (starting with line 3087) is not reached.
Thus commenting out the `URL.revokeObjectURL` line has no effect.

**Comment by Mugen87** [comment]
If this is some sort of timing issue, it would be good to try to reproduce the issue without WebGL and `GLTFLoader`. Meaning with plain JS. Since you say the issue does not occur with Firefox, it could be a browser issue that can't be fixed by us. It would be important to further isolate the issue if it is going to be reported at the Chromium bug tracker.

**Comment by digitalArt3DTobias** [comment]
Since the model loads properly with all textures on all computers also in Chrome if I access it via Sketchfab (link above), I assumed that it can't be a Chrome issue.

**Comment by Mugen87** [comment]
> Since the model loads properly with all textures on all computers also in Chrome if I access it via Sketchfab (link above),

Sketchfab probably loads the model completely different and not in the glTF format. So this is no evidence that something is wrong with the browser API.

**Comment by donmccurdy** [comment]
@digitalArt3DTobias shared the model privately with me, but I don't see anything unusual about the model. It loads without errors on my (macOS) computer, including Chrome and Chrome + Incognito mode.


Two more ideas worth trying here would 

1. See if the model loads in https://gltf.report/. It is a three.js-based viewer, but it doesn't use GLTFLoader, so the loading path is a bit different. 
2. Try converting the model on https://sandbox.babylonjs.com/

And just to confirm – you're saying you are able to see the same bug *both* when using the `.glb` here, and the original `.gltf` with textures in separate files?

At the moment I'm inclined to guess this is a Chrome on Windows bug, related to texture or Blob URL memory.

***

> In those cases when texture loading fails, the whole then block (starting with line 3087) is not reached.

Is the `catch` block below it reached, and does the `error` value there contain any additional information?

**Comment by digitalArt3DTobias** [comment]
Yes, the same problem occurs when using the gltf/bin files with an associated texture folder.

In the screenshot below, I've now opened the glb in two Chrome tabs side by side at the same time. In gltf-report everything succeeds reliably (like in the babylonjs sandbox, btw.). But in gltf-viewer at least one texture is always missing (even if I import in gltf-viewer a version exported from gltf-result or from the babylon sandbox).


![2_dragons](https://user-images.githubusercontent.com/130747909/233853854-3c6f0d38-a710-4e68-8df6-521e1624d1a6.PNG)


And here is the full error message from the catch block in GLTFLoader:


![error](https://user-images.githubusercontent.com/130747909/233853908-08b24479-b803-430c-b29f-eeeb188f62cf.jpg)

**Comment by jostschmithals** [comment]
I'm able to reproduce everything @digitalArt3DTobias described, with the same Chrome version on Windows. 

And in fact this seems to be a Chrome bug:

For a small test I've created a series of 4K PNGs with Photoshop, with various file sizes from 5 to 50 MB, and tested the loading behavior with this native code snippet:

```
<input id="fileInput" type="file">

<img id="image1">

<img id="image2" src='./test.png'>

<img id="image3">

<script>

  const reader = new FileReader();
  fileInput.onchange = (event) => {  
    reader.onload = () => image1.src = reader.result;
    reader.readAsDataURL(fileInput.files[0]);
  };

  fetch('./test.png')
    .then((response) => response.blob())
    .then(blob => image3.src = URL.createObjectURL(blob));

</script>
```


When using FileReader (image1), or using the src attribute (image2), even the biggest files load properly in Chrome, as expected. 

But when using the Fetch API (image3), loading in Chrome fails already for 10MB images, on fast Windows computers; in the network tab I get the message "No data found for resource with given identifier" (apparently the faster the machine, the worse the behavior; on slower computers it's no problem).

---

BTW (not directly related, but interesting): 
In FF the FileReader approach doesn't seem to work with file sizes larger than about 20 MB; it then silently fails for me (while in Chrome 50MB files are no problem when using FileReader).

**Comment by jostschmithals** [comment]
I forgot one important observation: When I use an incognito tab, everything works perfectly for me, also in Chrome, on any computer.

**Comment by Mugen87** [comment]
@jostschmithals Thanks for further testing! Do you mind providing a fiddle (https://jsfiddle.net/) with your code snippet and then file an issue at the [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list)?

> When I use an incognito tab, everything works perfectly for me, also in Chrome, on any computer.

That could indicate an issue with internal caching mechanisms. That is definitely something the Chromium devs should be investigating.

**Comment by jostschmithals** [comment]
> Do you mind providing a fiddle (https://jsfiddle.net/) with your code snippet and then file an issue at the [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list)?

Yes, I will do that (tomorrow).
But unfortunately, I noticed now that the issue can't be reproduced with images fetched via network.

Just to sum up the findings so far:

Loading of large textures fails ...
- only in Chrome (and Edge), not in FF
- on Windows, not on Mac
- only on faster computers (and without heavy other tasks in the background)
- only with local images
- only when using the Fetch API
- only in normal tabs (i.e. not in incognito mode)

**Comment by digitalArt3DTobias** [comment]
Thanks to all participants in this thread for your investigations!
I've modified the thread headline accordingly.

**Comment by jostschmithals** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1439777
