### ISSUE TITLE
Points behave differently between r150 and r151

### ISSUE THREAD

**Issue by MissSage** [mrdoob/three.js#25910]
### Description

When the version of three up to 0.151.3, the PointsMaterail with Texture behaved differently

### Reproduction steps

1. just copy the code and view it in vscode and open with live server
2. change the three version @0.151.3 to @0.150.1 and review the page, and you can see the texture of the sphere is different from the before one,

### Code

```html
// code goes here
<!DOCTYPE html>
<html>
  <head>
    <title>Three.js Demo</title>
    <meta charset="utf-8" />
    <style>
      #canvasContainer {
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100vh;
        overflow: hidden;
      }
    </style>
  </head>
  <body>
    <div id="canvasContainer"></div>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script> -->
    <script async src="https://unpkg.com/es-module-shims@1.6.3/dist/es-module-shims.js"></script>

    <script type="importmap">
      {
        "imports": {
          "three": "https://unpkg.com/three@0.151.3/build/three.module.js"
        }
      }
    </script>
    <script type="module">
      import * as THREE from "three"
      // 创建场景和相机
      const scene = new THREE.Scene()
      const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000)

      // 创建渲染器，并将其添加到页面中
      const renderer = new THREE.WebGLRenderer()
      renderer.setSize(window.innerWidth, window.innerHeight)
      document.getElementById("canvasContainer").appendChild(renderer.domElement)

      // 加载纹理图片
      const textureLoader = new THREE.TextureLoader()
      const texture = textureLoader.load("./Group1.png")

      // 创建球体的材质
      const material = new THREE.PointsMaterial({
        size: 0.05,
        map: texture,
        transparent: true
      })

      // 创建球体的几何体
      const geometry = new THREE.SphereGeometry(2, 32, 32)

      // 创建球体的网格并添加到场景中
      const mesh = new THREE.Points(geometry, material)
      scene.add(mesh)

      // 设置相机位置
      camera.position.z = 5

      // 渲染场景
      function animate() {
        requestAnimationFrame(animate)
        mesh.rotation.x += 0.01
        mesh.rotation.y += 0.01
        renderer.render(scene, camera)
      }
      animate()
    </script>
  </body>
</html>
```

### Live example

copy the code to a  html file and open it with vscode and preview it with live server

### Screenshots

![image](https://user-images.githubusercontent.com/46174227/233834766-a7eb3f16-03c5-4f2a-9a2e-d3de79647c69.png)
![image](https://user-images.githubusercontent.com/46174227/233834804-daa7fab5-5a18-4672-b3af-467bf8bf9ffd.png)

### Version

0.151.3

**Comment by WestLangley** [comment]
This change is explained in the [Migration Guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide).

r150
<img width="613" alt="Screenshot 2023-04-23 at 10 55 58 AM" src="https://user-images.githubusercontent.com/1000017/233848813-68d2b389-6a47-4493-a8b5-6b126b01fb08.png">

r151
<img width="607" alt="Screenshot 2023-04-23 at 10 53 33 AM" src="https://user-images.githubusercontent.com/1000017/233848817-3c0fbc67-8594-4348-bb6a-65735707f501.png">

To restore the previous behavior, delete the uv attribute in your geometry.

```js
const geometry = new THREE.SphereGeometry( 2, 32, 32 )
geometry.deleteAttribute( 'uv' );
```

**Comment by MissSage** [comment]
> This change is explained in the [Migration Guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide).
> 
> r150 <img alt="Screenshot 2023-04-23 at 10 55 58 AM" width="613" src="https://user-images.githubusercontent.com/1000017/233848813-68d2b389-6a47-4493-a8b5-6b126b01fb08.png">
> 
> r151 <img alt="Screenshot 2023-04-23 at 10 53 33 AM" width="607" src="https://user-images.githubusercontent.com/1000017/233848817-3c0fbc67-8594-4348-bb6a-65735707f501.png">
> 
> To restore the previous behavior, delete the uv attribute in your geometry.
> 
> ```js
> const geometry = new THREE.SphereGeometry( 2, 32, 32 )
> geometry.deleteAttribute( 'uv' );
> ```

thanks for your reply! resolved
