### ISSUE TITLE
Skeleton updated outside of frustum

### ISSUE THREAD

**Issue by ashconnell** [mrdoob/three.js#25914]
### Description

In [WebGLRenderer.projectObject()](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1151-L1162), SkinnedMesh is left out of the frustum check directly below it. 

I tested moving this inside of the frustum check and saw a large performance increase for scenes with a lot of skinned meshes with no noticable issues.

Does anyone know if this is intentionally left out of the frustum check? 
And would you accept a PR to improve this if there are no side effects?

### Reproduction steps

N/A

### Code

N/A

### Live example

N/A

### Version

0.150.1

**Comment by Mugen87** [comment]
Updating the skeleton only when the skinned mesh is inside the view frustum sounds like a good idea. The method only updates the bones texture which isn't required when the object isn't rendered at all. 

> And would you accept a PR to improve this if there are no side effects?

A PR would be highly appreciated! 😇
