### ISSUE TITLE
Animation disappears when copying or cloning a scene

### ISSUE THREAD

**Issue by activeguild** [mrdoob/three.js#25920]
### Description

Hello, this is my first post.
Thank you for your wonderful library.
I would like to confirm if this behavior is a specification or a limitation.
Clone a Scene with animated objects loaded and the animation is lost.

### Reproduction steps

1. Load animated objects into Scene.
2. Clone a scene.

During Process 1, we make sure that the AnimationClip is set to animations on the Mesh.

### Code

```js
const clonedScene = scene.clone(true)
```

### Live example

* none

### Version

0.145.0

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
