### ISSUE TITLE
Quaternion Serialisation Changed

### ISSUE THREAD

**Issue by epreston** [mrdoob/three.js#25932]
### Description

Quaternions are now serialised in a way that is indistinguishable from Vector4.  

They have changed from being an object to an array in exports.  There is no way to know which data type is required / used when loading exported data or inspecting log dumps.

This breaks all of our tooling.

### Reproduction steps

1.  Attempt to serialise a quaternion
2.  Inspect the output.

### Code

They used to be serialised by default as:

```js
"rotation": Quaternion {
  "_w": 1,
  "_x": 0,
  "_y": 0,
  "_z": 0,
  "isQuaternion": true,
},
```

Now they are serialised as

```js
"rotation": [
  0,
  0,
  0,
  1,
],
```

### Live example

Provided above.

### Version

r151.3

### Device

Desktop, Mobile, Headset

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows, MacOS, Linux, Android, iOS

**Comment by Mugen87** [comment]
```
"rotation": Quaternion {
  "_w": 1,
  "_x": 0,
  "_y": 0,
  "_z": 0,
  "isQuaternion": true,
},
```
This result was never intended and the result of `toJSON()` not being implemented. It is not the task of `toJSON()` to serialized type information. `fromJSON()` methods usually create uninitialized objects and then use a JSON object to restore data. If your app works differently, you have to implement a custom `toJSON()` method.

**Comment by epreston** [comment]
I doubt that is the case.  There's a very good reason it was not implemented, so that it could be distinguished from a Vector4.  It may seem simple to suggest that but in practice, it is not practical.

**Comment by Mugen87** [comment]
The sole data don't have to be distinguishable. What entity the JSON consumes and it knowledge about it matters. Sorry, the current solution is based on #25424 and #24167 and there is no compelling reasons to reconsider the implementation.

**Comment by epreston** [comment]
@mrdoob why do you let this guy randomly and rudely close things ?

**Comment by epreston** [comment]
@mrdoob What is this ?  I'd like you to review a list of thoughtless and abrupt closures like this one.   Now my questions are being marked as "abuse".

**Comment by epreston** [comment]
@donmccurdy That's not a fair summary.

I've only asked for things to get some thoughtful consideration when required and time has shown it was for good reason.  I've always given time and respect to peoples issues, regardless how much thought was put into them.  I don't contribute much any more because I don't get that in return.
