### ISSUE TITLE
How to use polygonOffset solving Z-fighting poblems

### ISSUE THREAD

**Issue by zhangang** [mrdoob/three.js#2593]
I see that THREE.scene.overrideMaterial defines the polygonOffset parameters and THREE.WebGLRenderer  calls glPolygonOffset(). but there are some errors when running  
console.error( _gl.getShaderInfoLog( shader ) );

I use FireFox 16.0 and My code likes this:

```
            var material1 = new THREE.Material();
        material1.polygonOffset = true;
        material1.depthTest = true;
        material1.polygonOffsetFactor = 1;
        material1.polygonOffsetUnits = 0.1;
        _scene.overrideMaterial= material1;
```

How to use polygonOffset  correctly.

Thanks,

http://en.wikipedia.org/wiki/Z-fighting

**Comment by makc** [comment]
btw, I should mention that the full set of properties mentioned above
```
transparent: true, depthTest: true, depthWrite: false, polygonOffset: true, polygonOffsetFactor: -4
```
still fails to make LineBasicMaterial "always on top" for me. I guess either that material is somehow different from mesh materials, or this whole feature has 50/50 chance of working correctly.

**Comment by makc** [comment]
I see this guy have the same problem #5295

**Comment by WestLangley** [comment]
@makc http://stackoverflow.com/questions/31226344/three-js-edgeshelper-showing-certain-diagonal-lines-on-collada-model/31232508#31232508

**Comment by makc** [comment]
@WestLangley ha ha, you pushed other stuff away, clever!

**Comment by MrBlenny** [comment]
Any solution to this? I'm also having an issue where polygonOffset is not working.

**Comment by tomlecoz** [comment]
I'm also looking for a solution....

Here is my code : 

 this.startMc = new THREE.Mesh(new THREE.PlaneGeometry(30,30,1,1), new THREE.MeshBasicMaterial({color:0x00cc00,polygonOffset:true,polygonOffsetFactor:-4,depthWrite:false,depthTest:true,transparent:true}))

I applyed exactly wat @makc said but it doesn"t work... 

I don't understand why there is no "zOffset" property inside the Mesh object (like Away3D) , it would be so usefull and much more confortable to use compared to the obscure "polygonOffsetFactor" that nobody knows how it works...

Any help is very welcome

**Comment by makc** [comment]
@tomlecoz you can still do zOffset thing in vertex shader, if you make custom material.

**Comment by spite** [comment]
@tomlecoz many times, z-fighting problems can be solved by carefully choosing the camera parameters. what's your near-far plane range, and what's your scene size?

**Comment by makc** [comment]
@tomlecoz here: http://jsfiddle.net/hfj7gm6t/2966/ an example for you to start :)

**Comment by makc** [comment]
@spite [like this](https://twitter.com/joachimholmer/status/799602767081848832)?

**Comment by kylebakerio** [comment]
https://stackoverflow.com/questions/49096626/three-js-what-is-more-efficient-to-layer-and-resolve-z-fighting-using-polygono

**Comment by kylebakerio** [comment]
> btw, I should mention that the full set of properties mentioned above
> 
> ```
> transparent: true,
> depthTest: true,
> depthWrite: false,
> polygonOffset: true,
> polygonOffsetFactor: -4
> ```
> 
> still fails to make LineBasicMaterial "always on top" for me. I guess either that material is somehow different from mesh materials, or this whole feature has 50/50 chance of working correctly.

for anyone who encounters this in the future....

> 13.040 Why doesn't polygon offset work when I draw line primitives over filled primitives?

Polygon offset, as its name implies, only works with polygonal primitives. It affects only the filled primitives: GL_TRIANGLES, GL_TRIANGLE_STRIP, GL_TRIANGLE_FAN, GL_QUADS, GL_QUAD_STRIP, and GL_POLYGON. Polygon offset will work when you render them with glPolygonMode set to GL_FILL, GL_LINE, or GL_POINT.

Polygon offset doesn't affect non-polygonal primitives. The GL_POINTS, GL_LINES, GL_LINE_STRIP, and GL_LINE_LOOP primitives can't be offset with glPolygonOffset().

-- https://www.opengl.org/archives/resources/faq/technical/polygonoffset.htm

**Comment by WestLangley** [comment]
@kylebakerio See https://stackoverflow.com/questions/31539130/display-wireframe-and-solid-color/31541369#31541369.
