### ISSUE TITLE
SVG path seems to render weird in some conditions

### ISSUE THREAD

**Issue by mvoila** [mrdoob/three.js#25936]
### Description

I import a SVG with the parse function of SVGLoader.
The result seems to be inconsistent : when i add an ocean shader underneath the imported path, it displays glitches on the shape (built with ShapeGeometry) or the extruded shape (built with ExtrudeGeometry).

Ocean shader came from here : https://threejs.org/examples/webgl_shaders_ocean.html

SVG sample is here
![carto](https://user-images.githubusercontent.com/16825331/234397914-037d33f7-8f74-49b8-a70d-116978563ec9.svg)
### Reproduction steps

1. Import SVG ressource as text (parse function)
2. Add water object (ocean)
3. Create mesh, shape and lines then  add it to the scene
4. Move mouse to activate controls

### Code

**Add Ocean Shader (from three.js example)** 
```javascript
//water
const waterGeometry = new THREE.PlaneGeometry( 10000, 10000 );

  const water = new Water(
    waterGeometry,
    {
      textureWidth: 3000 ,
      textureHeight: 3000,
      waterNormals: new THREE.TextureLoader().load( '../img/waternormals.jpg', function ( texture ) {

        texture.wrapS = texture.wrapT = THREE.RepeatWrapping;

      } ),
      sunDirection: new THREE.Vector3(),
      sunColor: 0xffffff,
      waterColor: 0x001e0f,
      distortionScale: 3.7,
      fog: scene.fog !== undefined
    }
  );
  water.rotation.x = - Math.PI / 2;
  scene.add( water );

//Skybox
const sky = new Sky();
sky.scale.setScalar( 10000 );
scene.add( sky );

const skyUniforms = sky.material.uniforms;

skyUniforms[ 'turbidity' ].value = 10;
skyUniforms[ 'rayleigh' ].value = 2;
skyUniforms[ 'mieCoefficient' ].value = 0.005;
skyUniforms[ 'mieDirectionalG' ].value = 0.8;

const parameters = {
    elevation: 2,
    azimuth: 180
};

const pmremGenerator = new THREE.PMREMGenerator( renderer );
let renderTarget;

function updateSun() {
    const phi = THREE.MathUtils.degToRad( 90 - parameters.elevation );
    const theta = THREE.MathUtils.degToRad( parameters.azimuth );
    sun.setFromSphericalCoords( 1, phi, theta );

    sky.material.uniforms[ 'sunPosition' ].value.copy( sun );
    water.material.uniforms[ 'sunDirection' ].value.copy( sun ).normalize();

    if ( renderTarget !== undefined ) renderTarget.dispose();
       renderTarget = pmremGenerator.fromScene( sky );
       scene.environment = renderTarget.texture;
    }
}
updateSun();
```

 **Render function** 
```javascript
function render() {
    const time = performance.now() * 0.001;
    water.material.uniforms[ 'time' ].value += 1.0 / 60.0;    
    renderer.render( scene, camera );
  }
```

**SVG parse and load.**

```javascript
const loader = new SVGLoader();
  const svgData = loader.parse(svg);
  const svgGroup = new THREE.Group();
  const updateMap = [];

  svgGroup.scale.y *= -1;
  svgGroup.translateY(-0.5)
  svgData.paths.forEach((path) => {
    const shapes =  SVGLoader.createShapes(path);
    
    shapes.forEach((shape) => {
      const meshGeometry = new THREE.ExtrudeGeometry(shape, {
        depth: extrusion,
        bevelEnabled: false,
      });
      const meshGeometryGeo = new THREE.ShapeGeometry(shape);
      meshGeometry.computeVertexNormals();
      const linesGeometry = new THREE.EdgesGeometry(meshGeometry,0.01); 

     //using meshGeometry or meshGeometryGeo lead to the same result
      const mesh = new THREE.Mesh(meshGeometry, fillMaterial);
      const lines = new THREE.LineSegments(linesGeometry, stokeMaterial);

      if(path.userData.node.id.localeCompare('shapedur1_1_0') === 0){
        trackObj = mesh;
        trackMat =  trackObj.matrixWorld; 
      }
      svgGroup.add(mesh,lines);
    });
  });

  const box = new THREE.Box3().setFromObject(svgGroup);
  const size = box.getSize(new THREE.Vector3());

  const yOffset = size.y / -2;
  const xOffset = size.x / -2;

  svgGroup.children.forEach((item) => {
    item.position.x = xOffset;
    item.position.y = yOffset;
  });
  svgGroup.rotateX(-Math.PI / 2);

  scene.add(svgGroup);
```

### Live example

I don't know how to do :(

### Screenshots

With ocean
![2023-04-25_23h03_46](https://user-images.githubusercontent.com/16825331/234403547-3009e39b-086b-44f4-800e-9442427cc398.png)
https://user-images.githubusercontent.com/16825331/234403549-33d6f817-ec7f-4e21-b4c1-e1004e697363.mp4

Without ocean
![2023-04-25_23h06_29](https://user-images.githubusercontent.com/16825331/234404044-08e365fb-8447-40c3-92df-1e2510054af2.png)
https://user-images.githubusercontent.com/16825331/234404048-b253dddd-1a42-497a-80bb-dffec83e1cd9.mp4

### Version

r151.3

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
The SVG is rendered as expected when importing in the editor:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/12612165/234514949-18e408f8-d1b8-4915-a808-4eb53a3b21fd.png">

The z-fighting potentially occurs since the water and the shape are congruent (meaning they lie in the same XZ plane). Lowering the heigh of the water mesh should fix that.

Do you mind sharing the asset of the windmill? I'd like to  closer investigate the reasons for the wrong culling.

**Comment by mvoila** [comment]
**Path troubleshooting** 

Before opening the issue, I tried small z translation on the object.
I tried again with partial success (see screenshot and video).
The bigger the z translation is, the less troubles i have.
Here is  a video with z translation of 50 units. With 100 units, it seems to be 'fine'.

![2023-04-26_11h21_27](https://user-images.githubusercontent.com/16825331/234531984-fae46630-e44a-4ffc-b257-fe301debc7de.png)
https://user-images.githubusercontent.com/16825331/234531989-a68bbf21-74dd-40d4-9214-48b3f1541bec.mp4

I just add z translation on my SVG group :
```javascript
const zOffset = 50;

  svgGroup.children.forEach((item) => {
    item.position.x = xOffset;
    item.position.y = yOffset;
    item.position.z = zOffset;
  });
```
However what seems to be weird is this code translates all of my objects in my scene, even i add objects in the scene (not in the group). Is it normal?
Windmills are added with scene.add

**Culling issues**
For culling troubleshooting, you can find assets here : 
[https://drive.google.com/file/d/1y83kaWGKqOr4rGH2bYaX5WqJsCkKKnC8/view?usp=sharing](url)
[https://drive.google.com/file/d/1t_sFksPre_NFaJdRrs1kiPFuMUgcLLDh/view?usp=sharing](url)

Could it be related to how i import them.
Here is the part of the code i use : 
```javascript 
const loader = new OBJLoader();

    // load a resource
    loader.load(
      // resource URL
      url,
      // called when resource is loaded
      function ( object ) {
        const instances = maxInstances;
        libInstances.url = {};
        libInstances.url.attributes = {};
        libInstances.url.attributes.maxInstanceNum = instances;

        initIBuffGeofromGeoBuff(object.children[0].geometry,libInstances.url);
       
        const shader_basic = {};
        // unifrom values for basic shader
        shader_basic.uniforms = {
            diffuse: { value: new THREE.Color(0xffffff) },
           /*  pMax : ,
            pCons : , */
        };
        // vertex shader for basic shader
        shader_basic.vertexShader = [ 
          'precision mediump float;',
			    'precision mediump int;',
          'uniform mat4 modelViewMatrix;',
			    'uniform mat4 projectionMatrix;',
			    'attribute vec3 position;',
          'attribute vec3 offset;',
          'void main() {',  
          '  vec4 modelViewPosition = modelViewMatrix * vec4(position+offset, 1.0);',
          '  gl_Position = projectionMatrix * modelViewPosition;',
          '}'
        ].join('\n');
        // fragment shader for hatching shader
        shader_basic.fragmentShader = [
            'precision mediump float;',
            'uniform vec3 diffuse;',
            'void main() {',
            '    gl_FragColor = vec4( diffuse, 1.0 );',
            '}'
        ].join('\n');

        var material = new THREE.RawShaderMaterial({
          uniforms: THREE.UniformsUtils.clone(shader_basic.uniforms),
          vertexShader: shader_basic.vertexShader,
          fragmentShader: shader_basic.fragmentShader,
          side: THREE.DoubleSide
        });
      
        let mesh = new THREE.Mesh(libInstances.url.buffer, material);
        scene.add(mesh);

        resolve(libInstances.url)
      }
    );
```

**Comment by Mugen87** [comment]
> Could it be related to how i import them.

Indeed. The fact that you are using a custom shader with offsetting vertices means you don't have correct bounding volumes which breaks view frustum culling. As workaround, set the `frustumCulled` property of your meshes to `false`.

If possible, use `InstancedMesh` instead which supports proper bounding volume computations.

> However what seems to be weird is this code translates all of my objects in my scene, even if i add objects in the scene (not in the group). Is it normal?

Not that is not. But I would like to ask you to use the [forum](https://discourse.threejs.org/) for further investigation since your issue does not look like a bug in the engine or the water shader.

**Comment by simranrizvi777-gif** [comment]
Hi,
Issues like this are often related to how the glTF is exported or how materials and normals are configured for three.js. We have helped teams fix similar rendering problems by optimizing the model and textures for web delivery.

If helpful, happy to share a quick checklist you can try.
