### ISSUE TITLE
CSM constructor cannot take null parameters

### ISSUE THREAD

**Issue by bplu4t2f** [mrdoob/three.js#25956]
### Description

The CSM constructor in the cascaded shadowmap addon is written as if a null (or undefined) parameter object is a valid use case:

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/csm/CSM.js#L27

However, in practice this will just lead to a null dereference a few lines later in the code:

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/csm/CSM.js#L69

Either it should allow a null (or undefined) parameter, or it should fail early and not pretend that it works at first, thus obfuscating the actual problem.

I don't know which of the two matches the API design philosophy in this project.

### Reproduction steps

`new CSM()`

### Code

not applicable

### Live example

not applicable

### Version

r151

**Comment by Mugen87** [comment]
For reproduction: https://jsfiddle.net/3w0zd95x/

I vote to make the `data` parameter mandatory. We can't have a sensible fallback for `camera` and `parent`.
