### ISSUE TITLE
r152 Skinned Mesh and Raycasting issue

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#25953]
### Description

Guys, I found another one.
Everything was just fine in r150 (and before that).
152 sample: https://necromanthus.com/Test/html5/testA_disco.html 

### Reproduction steps

Try to aim at Lara (now it's a real russian roulette).
When red fire a "bullet" and that will freeze her.
Now check out her frozen skinned mesh: the result is a complete mess.
It also depends on your position around her, why is that ???

### Code

// You should be aware of the code changes

### Live example

https://necromanthus.com/Test/html5/testA_disco.html 

### Version

152

### Device

Desktop, Mobile

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows

**Comment by RemusMar** [comment]
This piece of code is involved in all of these:

```
				lasttrg.material.color.set( 0xffffff );
				var camvec = new THREE.Vector3( 0, 0, -1 );
				camvec.applyQuaternion( camera.quaternion );
				raycaster.set ( camP, camvec );
				var intersects = raycaster.intersectObjects( targets.children );
				if ( intersects.length > 0 ) {
					intersects[0].object.material.color.set( 0xff0000 );
					lasttrg = intersects[0].object;
				}
```

**Comment by RemusMar** [comment]
Another (very important) note: in case of static meshes (see Claire), everything is still working fine.

**Comment by RemusMar** [comment]
Here is the working 150 version: https://necromanthus.com/Test/html5/testA_disco_150.html 

> Do you mind using the non-minified version of three.js in testA_disco

I will prepare one asap

**Comment by RemusMar** [comment]
The minified 152bis version is resulted from the current three.js file processed by Google Closure Compiler withg this command line:
java -jar compiler.jar --js "three.js" --js_output_file "three.min.js" --language_out=ES5 

Reason: The SEA3D loader needs ES5.

**Comment by Mugen87** [comment]
Is it possible to share the Lara model as a glTF asset? I want to inspect the skeleton and the bounding sphere of the skinned mesh in the three.js editor in more detail.

**Comment by Mugen87** [comment]
One thing that would be interesting to test is the recomputation of the bounding spheres for the animated dog and Lara. What happens if you add the following two lines in your animation loop:
```js
dog.computeBoundingSphere();
lara.computeBoundingSphere();
```

**Comment by RemusMar** [comment]
> Is it possible to share the Lara model as a glTF asset?
> It seems the dog asset shows the same issue. So sharing this one would also be fine.

Sure.
https://necromanthus.com/Test/html5/Lara_gltf.html
https://necromanthus.com/Test/html5/dog_gltf.html 

> What happens if you add the following two lines in your animation loop

I will try now

**Comment by RemusMar** [comment]
> What happens if you add the following two lines in your animation loop:
>
> dog.computeBoundingSphere();
> lara.computeBoundingSphere();

No change.

**Comment by Mugen87** [comment]
Um, not sure what's going wrong yet.

Do you mind making a quick test with `r151` to ensure everything works with that version?

**Comment by RemusMar** [comment]
> Do you mind making a quick test with r151 to ensure everything works with that version?

Where I can find the r151 three.js file?

**Comment by Mugen87** [comment]
Here: https://github.com/mrdoob/three.js/tree/r151/build

**Comment by RemusMar** [comment]
Yes, I found it.
151 is good!

**Comment by Mugen87** [comment]
That's good! 

Since `r152`, `SkinnedMesh` has an own `raycast()` method: https://github.com/mrdoob/three.js/blob/d50cf0c70ff31309a32cf104a62129bc158d9649/src/objects/SkinnedMesh.js#L100-L111

Could please make a test by removing it from the build so the class uses the implementation from `Mesh.raycast()` again? I just want to make sure the problem comes from https://github.com/mrdoob/three.js/pull/25791 and not elsewhere.

**Comment by RemusMar** [comment]
I've put them all here:
150 good: https://necromanthus.com/Test/html5/testA_disco_150.html
151 good: https://necromanthus.com/Test/html5/testA_disco_151.html
152 bad: https://necromanthus.com/Test/html5/testA_disco.html

**Comment by RemusMar** [comment]
> Could please make a test by removing it from the build so the class uses the implementation from Mesh.raycast() again?

With that part removed ftom 152, everything is perfect again.

**Comment by RemusMar** [comment]
I've updated my 152 and removed those 150 and 151 samples.
Michael, because you found and fixed the issue, here is the gift for you:
play a slot game and win money!
https://necromanthus.com/Test/html5/testA_slot.html
