### ISSUE TITLE
webgpu skinning bad position

### ISSUE THREAD

**Issue by lo-th** [mrdoob/three.js#25985]
### Description

setting possition of skin mesh in webgpu give bad result
position is invers and scaled ?

### Reproduction steps

1. go to webgpu_skinning.html
2. add object.position.set(1,0,0)
3. now position x in view is ~ -1.5

### Screenshots

![bug1](https://user-images.githubusercontent.com/1553208/236153980-f3546c6c-ab25-4eb7-8f07-62fb91b3a55b.jpg)

### Version

153

**Comment by sunag** [comment]
> Reproduction steps...

Hmm... I couldn't reproduce this problem in `Michelle.glb`, can you share an example model? 
Maybe it can be something more complex.

**Comment by lo-th** [comment]
add a box at 1,0,0
on loader add 
scene.add( object );
object.position.set(1,0,0)

now you have 
![f1](https://user-images.githubusercontent.com/1553208/236158867-aea46908-208a-4bbe-bd83-2c60f403944d.jpg)

**Comment by lo-th** [comment]
where skinning position is set for webgpu ?

**Comment by lo-th** [comment]
https://lo-th.github.io/root/skin/index.html

**Comment by sunag** [comment]
Oh I see!! 

> where skinning position is set for webgpu ?

https://github.com/mrdoob/three.js/blob/f75bc4e1de5b84706b52275299a810c3fe37c5f4/examples/jsm/nodes/accessors/SkinningNode.js#L47-L50

**Comment by lo-th** [comment]
ha !    i add skeleton helper to demo

**Comment by lo-th** [comment]
Great thank's
