### ISSUE TITLE
CapsuleGeometry with TextGeometry in one group

### ISSUE THREAD

**Issue by simpy25** [mrdoob/three.js#25980]
### Description

I'm trying to make a capsule with text inside with three js, but receiving just a capsule with cube inside instead of text, what is wrong with my code, can anyone help me pls with this one? 

### Reproduction steps

n/a

### Code

```
 const capsule = new Mesh(new CapsuleGeometry(3, 3, 32), new MeshLambertMaterial({
                    color: 'red',
                    transparent: true,
                    opacity: 0.4
                }))

                const text = new Mesh(new TextGeometry('500', {
                    height: 5, curveSegments: 12, bevelEnabled: true, bevelThickness: 10, bevelSize: 8, bevelOffset: 0, bevelSegments: 5
                }), new MeshBasicMaterial({
                    color: 'black',
                    transparent: false,
                    opacity: 1
                }));

                const group = new Group();
                group.add(capsule);
                group.add(text);
                return group
```

### Live example

n/a

### Screenshots

![image](https://user-images.githubusercontent.com/105854603/236037986-6e0efdc0-3da7-40b2-9677-54a5e5c4c09a.png)

### Version

r152

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by gkjohnson** [comment]
Please ask for help on the forum: https://discourse.threejs.org/
