### ISSUE TITLE
ThreeJs script loading by document.createElement("script") error

### ISSUE THREAD

**Issue by GrandStrateguerre** [mrdoob/three.js#25998]
### Description

Hi,

There is two js script :
![image](https://user-images.githubusercontent.com/86523070/236610984-9c0fdd07-aaaf-4a1c-9e29-9fd4f23f58c2.png)
Script ex1, ex2 almost the same except size and color cube: 
![image](https://user-images.githubusercontent.com/86523070/236614622-b5472f34-eedd-4e47-8e6c-5ba525a4cbae.png)
start loading first :
![image](https://user-images.githubusercontent.com/86523070/236613991-070ac1bd-8b2a-4345-b106-8a892786721d.png)
result :
![image](https://user-images.githubusercontent.com/86523070/236614055-ad1fbf20-352c-48f6-8f20-02ebb7dace5a.png)
load second :
![image](https://user-images.githubusercontent.com/86523070/236614136-aea6f9c5-3ed0-4c06-92d8-73bfc11495c9.png)
result :
![image](https://user-images.githubusercontent.com/86523070/236614114-76a3ab0f-0406-427e-a4e5-376070f81192.png)
code used to load :
![image](https://user-images.githubusercontent.com/86523070/236614472-9f08619b-b55a-4e80-ae96-aa0aec4ed87a.png)

Best regards

### Reproduction steps

1. click on the button which hold the script 1=> the scene is rendered in the canvas
2. click on the button which hold the script 2=> the scene is rendered in the canvas
3. redo this step => the script 1 is not rendered, also the same for script 2
is seems the  canvas is not created by the threeJS :
![image](https://user-images.githubusercontent.com/86523070/236615000-def38446-ec84-432c-b498-e815f33c76e8.png)
![image](https://user-images.githubusercontent.com/86523070/236615070-d60eafec-4307-4360-936f-39aa9903f258.png)
we should have a line under the script tag like the first time:
![image](https://user-images.githubusercontent.com/86523070/236615156-67e9e90e-6529-483a-8154-81f75da2ef88.png)

I don't understand why the the ThreeJs does not create the canvas. It works well only one time ?

### Code

```js
import * as THREE from "three";

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(
  75,
  window.innerWidth / window.innerHeight,
  0.1,
  1000
);

//const canvas = document.getElementById("canvas");
//const renderer = new THREE.WebGLRenderer({ canvas: canvas });
const renderer = new THREE.WebGLRenderer();

renderer.setSize(window.innerWidth, window.innerHeight);
document.body.appendChild(renderer.domElement);

const geometry = new THREE.BoxGeometry(1, 1, 1);
const material = new THREE.MeshBasicMaterial({ color: 0x3cb371 });
const cube = new THREE.Mesh(geometry, material);
scene.add(cube);

camera.position.z = 5;

function animate() {
  requestAnimationFrame(animate);

  cube.rotation.x += 0.01;
  cube.rotation.y += 0.01;

  renderer.render(scene, camera);
}

animate();

//______________________________________________________________
/**
 *
 * @param {*} path
 */
export function LoadFromPath(path) {
  //path like examples/ex1.js

  var canvas = document.getElementsByTagName("canvas")[0];
  //var canvas = document.getElementById("canvas");
  if (canvas != null) {
    document.body.removeChild(canvas);
  }

  var elScript = document.getElementById("threeScript");

  if (elScript != null) {
    document.body.removeChild(elScript);
  }

  var script = document.createElement("script");
  script.type = "module";
  script.id = "threeScript";
  script.async = false;
  //indicates the source script
  script.src = path;
  //append the script to the document
  document.getElementsByTagName("body")[0].appendChild(script);
  console.log("script : " + path + " loaded.");
}
//passes the LoadFromPath function to global scope
window.LoadFromPath = LoadFromPath;

//Html index file
 <a
                  href="#"
                  class="dropdown-item"
                  onclick='(function(){
                    // loads the script into the document from the given path
                    window.LoadFromPath("examples/ex1.js");
                    // loads the source code 
                    window.loadSourceCodeAndHighlight("examples/ex1.js","sourceCode");
                   
                  })()'
                  >Ex1</a>
              <a
              href="#"
              class="dropdown-item"
              onclick='(function(){
                // loads the script into the document from the given path
                window.LoadFromPath("examples/ex2.js");
                // loads the source code 
                window.loadSourceCodeAndHighlight("examples/ex2.js","sourceCode");
             
              })()'
              >Ex2</a>

```

### Version

r152

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by LeviPesin** [comment]
The problem is not in three.js but rather your LoadFromPath function.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
