### ISSUE TITLE
BufferGeometry, morph target leaks even if I call `geometry.dispose()`

### ISSUE THREAD

**Issue by 0b5vr** [mrdoob/three.js#26028]
### Description

It seems morph target buffers are leaking even if I call `geometry.dispose()` after I finish using the geometry.

Checked using [webgl-memory](https://github.com/greggman/webgl-memory).

### Reproduction steps

1. The usual Three.js boilerplate
2. Create a mesh with a morph target
3. Render once
4. Dispose the geometry
5. webgl-memory insists that there is still 1 buffer in the current WebGL context

If the render does not happen, the morph geometry does NOT leak.

### Code

```js
import 'webgl-memory';
import * as THREE from 'three';

// your usual Three.js boilerplate
const canvas = document.getElementById( 'canvas' );

const renderer = new THREE.WebGLRenderer( { canvas } );
const webglMemory = renderer.getContext().getExtension( 'GMAN_webgl_memory' );

const camera = new THREE.PerspectiveCamera( 45.0, 2.0, 0.1, 10.0 );
camera.position.set( 0.0, 0.0, 5.0 );

const scene = new THREE.Scene();

const geometry = new THREE.SphereGeometry();

// assign nonsense morph target
const deformedPositionAttr = geometry.attributes.position.clone();
for ( let i = 0; i < deformedPositionAttr.array.length; i ++ ) {
  deformedPositionAttr.array[ i ] += Math.random() - 0.5;
}
geometry.morphAttributes.position = [ deformedPositionAttr ];

const material = new THREE.MeshNormalMaterial();

const mesh = new THREE.Mesh( geometry, material );

scene.add( mesh );

// render once
renderer.render( scene, camera );

// dispose the mesh
mesh.geometry.dispose();
mesh.material.dispose();
scene.remove( mesh );

// it leaks!
console.log( webglMemory.getMemoryInfo() );
```

### Live example

- https://glitch.com/~three-r152-morph-leaks
- https://glitch.com/edit/#!/three-r152-morph-leaks

### Version

at least r125 - r152

until r137, texture also leaks, which is fixed by https://github.com/mrdoob/three.js/pull/23104

### Device

Desktop

### Browser

Chrome, Firefox

### OS

Windows

**Comment by 0b5vr** [comment]
Gonna do the archeology using recent changelogs around morph targets.

**Comment by 0b5vr** [comment]
WIP, How the leaked morphs created:

- [WebGLAttributes, createBuffer](https://github.com/mrdoob/three.js/blob/r152/src/renderers/webgl/WebGLAttributes.js#L12)
- [WebGLAttributes, update](https://github.com/mrdoob/three.js/blob/r152/src/renderers/webgl/WebGLAttributes.js#L172)
- [WebGLGeometries, update](https://github.com/mrdoob/three.js/blob/r152/src/renderers/webgl/WebGLGeometries.js#L88)
- [WebGLObjects, update](https://github.com/mrdoob/three.js/blob/r152/src/renderers/webgl/WebGLObjects.js#L16)
- ...

**Comment by 0b5vr** [comment]
Here, I think we have to call `attributes.remove` for `morphAttributes` as well as `index` and `attributes`.

https://github.com/mrdoob/three.js/blob/r152/src/renderers/webgl/WebGLGeometries.js#L13-L25

@Mugen87 (I hope you are the right person to ping 😀), if you agree with the direction above I can make a PR for this.

**Comment by Mugen87** [comment]
Yes, this looks like the right fix. A PR is highly welcome!
