### ISSUE TITLE
make Matrix4.makeTranslation accept Vector3

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#26038]
### Description

This came up after #26031 - Matrix4.setPosition supports both x, y, z and vector signatures, but makeTranslation doesnt

### Solution

Why not make it the same as setPosition?

### Alternatives

Do nothing.

**Comment by mrdoob** [comment]
Sure 👍

**Comment by Mugen87** [comment]
@makc Would you like to file a PR with the change?

**Comment by makc** [comment]
@Mugen87 sure, what do you prefer:
```js
makeTranslation( x, y, z ) {
    return this.identity().setPosition( x, y, z );
}
```
or should I just copy-pase if-else logic from setPosition?

**Comment by Mugen87** [comment]
> or should I just copy-pase if-else logic from setPosition?

That one.
