### ISSUE TITLE
Add `Clock.runPeriodically()`

### ISSUE THREAD

**Issue by LeviPesin** [mrdoob/three.js#26050]
### Description

I suggest to add a function `Clock.runPeriodically( function, frequency )`, which would run that function `frequency` times per second (using `setInterval`, for example) and will pass `Clock.getDelta()` to it as an argument. So basically it would work like `requestAnimationFrame` but for arbitrary frequency.

### Solution

Add it.

### Alternatives

Don't add it.

**Comment by Mugen87** [comment]
Do you mind describing in more detail the use cases of `runPeriodically()`? Besides, how would you implement the same logic without this new method?

**Comment by LeviPesin** [comment]
An example use case could be running some simulation or physics loops with some periodicity that may be different from 60 FPS.
Currently it could be implemented like this:
```js
const clock = new Clock();
setInterval( () => func( clock.getDelta() ), 1000 / freq );
```

**Comment by Mugen87** [comment]
This one liner seems is already clear and easy to read. I don't think that justifies the introduction of introducing a new API, tbh. Alternatively, one can implement a logic similar to the following on app level if it is required for a game: https://github.com/Mugen87/yuka/blob/master/src/core/Regulator.js

**Comment by LeviPesin** [comment]
Partially yes. But I think it could be used for other use cases and is quite a simple function to implement.

**Comment by mrdoob** [comment]
> But I think it could be used for other use cases and is quite a simple function to implement.

Please elaborate.

The more compelling the use case you present the more likely we'll be okay with adding more API that we'll need to document in multiple languages and maintain.

**Comment by LeviPesin** [comment]
It could be used for physics loop, not only in RapierPhysics but for example custom physics engines.
It could be used for example for periodically fetching some data and updating the scene.
It could be used for triggering some other update loops, for example processing characters decisions/movements.

**Comment by mrdoob** [comment]
I feel like you could use `setInterval()` for all these?

How is `clock.runPeriodically( step, 1000 / frameRate )` better than `setInterval( step, 1000 / frameRate )`?

**Comment by RemusMar** [comment]
> How is clock.runPeriodically( step, 1000 / frameRate ) better than setInterval( step, 1000 / frameRate )?

Is not better at all.
But he wants to replace all the "obsolete" things from everywhere :grin:

**Comment by mrdoob** [comment]
Hmm, closing until a compelling use case is found...
