### ISSUE TITLE
TrackballControls is not working with OrthographicCamera

### ISSUE THREAD

**Issue by LinkunGao** [mrdoob/three.js#26053]
### Description

When we use TrackballControls and OrthographicCamera together, the rotate/pan functions are not working!

You can easily reproduce the result in this example: https://github.com/mrdoob/three.js/blob/dev/examples/webgl2_materials_texture3d.html

In this example, the rotate/pan/zoom are all not working! 

Do you have any suggestions to let me solve this issue? Or was something I set wrong and made any mistakes somewhere?

Thanks so much!

### Reproduction steps

1. line 41: import { TrackballControls } from "three/addons/controls/TrackballControls.js";
2. comment this code around line 78: // controls = new OrbitControls( camera, renderer.domElement );
3. Line 79: controls = new TrackballControls(camera, renderer.domElement);
4. run the example locally in your browser.

### Code

```js
import { TrackballControls } from "three/addons/controls/TrackballControls.js";
...
 // controls = new OrbitControls( camera, renderer.domElement );
controls = new TrackballControls(camera, renderer.domElement);
```

### Live example

no

### Version

r152

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by WestLangley** [comment]
`TrackballControls` requires an animation loop that calls `controls.update()`.

See https://threejs.org/examples/misc_controls_trackball.html.

Please use the [forum](https://discourse.threejs.org) if you need more help.
