### ISSUE TITLE
webpack can not use webgpu module

### ISSUE THREAD

**Issue by lishu2006ll** [mrdoob/three.js#26065]
### Description

An example of packaging WebGPU using webpack and npm may result in rendering errors, but using an import map works normally. I'm not sure if there is an official solution to this problem, as I've tried many methods that haven't worked

### Reproduction steps

const CopyWebpackPlugin = require('copy-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const MiniCSSExtractPlugin = require('mini-css-extract-plugin')
const path = require('path')

module.exports = {
    //externals: {
    //    '../node_modules/three/examples/jsm/nodes/NodeMaterial': 'NodeMaterial'
    //},
    entry: path.resolve(__dirname, '../src/script.js'),
    output:
    {
        filename: 'bundle.js',
        path: path.resolve(__dirname, '../dist')
    },
    //devtool: 'source-map',
    plugins:
    [
        new CopyWebpackPlugin({
            patterns: [
                { from: path.resolve(__dirname, '../static') }
            ]
        }),
        new HtmlWebpackPlugin({
            template: path.resolve(__dirname, '../src/index.html'),
            minify: true
        }),
        new MiniCSSExtractPlugin()
    ],
    module:
    {
        rules:
        [
            // HTML
            {
                test: /\.(html)$/,
                use: ['html-loader']
            },

            // JS
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use:
                {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env']
                     }
                }
            },
            {
                test: /\.(glsl|vs|fs|vert|frag)$/,
                exclude: /node_modules/,
                use: [{
                        loader: 'raw-loader',
                    },
                    {
                        loader: 'glslify-loader',
                    }
                ]
            },
            {
                test: /\.(wgsl)$/,
                exclude: /node_modules/,
                use: [{
                    loader: 'raw-loader',
                }]
            },
            // CSS
            {
                test: /\.css$/,
                use:
                [
                    MiniCSSExtractPlugin.loader,
                    'css-loader'
                ]
            },

            // Images
            {
                test: /\.(jpg|png|gif|svg)$/,
                use:
                [
                    {
                        loader: 'file-loader',
                        options: { outputPath: 'assets/images/' }
                    }
                ]
            },

            // Fonts
            {
                test: /\.(ttf|eot|woff|woff2)$/,
                use:
                [
                    {
                        loader: 'file-loader',
                        options:
                        {
                            outputPath: 'assets/fonts/'
                        }
                    }
                ]
            }
        ]
    },
    resolve: {
        alias: {
            //'three-addons': path.resolve(__dirname, '../node_modules/three/examples/jsm'),
            //'three-nodes': path.resolve(__dirname, '../node_modules/three/examples/jsm/nodes/Nodes.js'),
            //'three': path.resolve(__dirname, '../node_modules/three/build/three.module.js'),
        }
    }
}

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

146

**Comment by lishu2006ll** [comment]
<img width="985" alt="图片" src="https://github.com/mrdoob/three.js/assets/3477402/f2e3ea41-87b1-43a8-a975-c7083d7e3557">

**Comment by lishu2006ll** [comment]
<img width="1071" alt="图片" src="https://github.com/mrdoob/three.js/assets/3477402/9f7bb3cc-aab6-48b8-9d54-0b2921533343">

**Comment by LeviPesin** [comment]
The problem is in tree-shaking, possibly? NodeMaterials register themselve in each file individually. If you see that `NodeMaterial.fromMaterial()` returns `undefined` this means they didn't register.

I think you must somehow ensure that Webpack imports `three/nodes` (which points to `examples/jsm/nodes/Nodes.js`) and doesn't tree-shake any of its dependencies.

**Comment by marcofugaro** [comment]
Which version of webpack are you using?

**Comment by marcofugaro** [comment]
@lishu2006ll are you using webpack 4? if so you should upgrade to webpack 5 to fix the issue

**Comment by lishu2006ll** [comment]
> @lishu2006ll are you using webpack 4? if so you should upgrade to webpack 5 to fix the issue

oh, now i use webpack 5.24.2, i think not the webpack version problem

**Comment by marcofugaro** [comment]
@lishu2006ll ok, can you share your project? maybe upload it here https://codesandbox.io/

Also the correct import should be:
```js
import * as Nodes from 'three/nodes';
```

**Comment by lishu2006ll** [comment]
> @lishu2006ll ok, can you share your project? maybe upload it here https://codesandbox.io/
> 
> Also the correct import should be:
> 
> ```js
> import * as Nodes from 'three/nodes';
> ```

no problem, do you have facebook?, my facebook no is:York Li,  i can transfer to you , the project is only a demo

**Comment by LeviPesin** [comment]
>
```json
"sideEffects": [
  "three/nodes/*.js"
]
```

This doesn't seem to be correct. Can you try `three/examples/jsm/nodes`? `three/nodes` points to exactly one file, not a directory.

**Comment by lishu2006ll** [comment]
> > 
> 
> ```json
> "sideEffects": [
>   "three/nodes/*.js"
> ]
> ```
> 
> This doesn't seem to be correct. Can you try `three/examples/jsm/nodes`? `three/nodes` points to exactly one file, not a directory.

yes, i use 'three/examples/jsm/nodes' or 'three/nodes', the result is same, but the issue is as followsr:
<img width="778" alt="图片" src="https://github.com/mrdoob/three.js/assets/3477402/1d3f10e1-a7b9-4587-8195-d649f4304ee3">

**Comment by LeviPesin** [comment]
If Webpack converts a perfectly valid JS code without import loops into non-working JS code it is a Webpack issue. I suggest you file an issue at the Webpack repository.

**Comment by mrdoob** [comment]
Please use one of the links below for help / support:

- [questions](https://stackoverflow.com/questions/tagged/three.js)
- [discord](https://discord.gg/56GBJwAnUS)
- [forum](https://discourse.threejs.org)
