### ISSUE TITLE
Need for Latex or Katex in TextGeometry for Mathematical, Physics, Chemistry, Biology etc. equations

### ISSUE THREAD

**Issue by engineer-ece** [mrdoob/three.js#26096]
### Description

Need for Latex or Katex in TextGeometry for Mathematical, Physics, Chemistry, Biology etc. equations

Eg:

1.  \int_1^4{x^2}dx = $\int_1^4{x^2}dx$
2. \frac{x^2+1}{x} = $\frac{x^2+1}{x}$

### Solution

Need for Latex or Katex in TextGeometry for Mathematical, Physics, Chemistry, Biology etc. equations

there is katex rendering library in js

### Alternatives

Need for Latex or Katex in TextGeometry for Mathematical, Physics, Chemistry, Biology etc. equations

### Additional context

Need for Latex or Katex in TextGeometry for Mathematical, Physics, Chemistry, Biology etc. equations

**Comment by mrdoob** [comment]
This is definitely out of scope for `TextGeometry`.

You can try creating an svg with the equation/s and using `SVGLoader`.
