### ISSUE TITLE
Compare `line.startsWith` performance to `lineFirstChar ===`

### ISSUE THREAD

**Issue by hamirmahal** [mrdoob/three.js#26106]
### Description

It could be beneficial to compare the performance of `line.startsWith` to `lineFirstChar ===`, since if `line.startsWith` is the same speed, or faster, than `lineFirstChar ===`, we can use it instead of `lineFirstChar ===` to slightly simplify `examples/jsm/loaders/OBJLoader.js`.

https://github.com/mrdoob/three.js/blob/6c7ff7addf2bc021b9509daffddb88e39517f785/examples/jsm/loaders/OBJLoader.js#L515-L520.

### Solution

Someone can add some test files with a large number of trials comparing `examples/jsm/loaders/OBJLoader.js` using `lineFirstChar ===`, and `line.startsWith`.

### Alternatives

We could just leave the codebase as-is.

### Additional context

It might be nice to have some really large `.obj` files to test this comparison.

**Comment by Mugen87** [comment]
Closing see https://github.com/mrdoob/three.js/pull/26107#issuecomment-1563267958.
