### ISSUE TITLE
Docs: At present, it seems that the CanvasTexture in WebGL1Render rendering will not work properly in the version of IOS16.4+.

### ISSUE THREAD

**Issue by 271642183** [mrdoob/three.js#26118]
### Description

At present, it seems that the CanvasTexture in WebGL1Render rendering will not work properly in the version of IOS16.4+. 

### Solution

Suggest maintainers to document and annotate it, or to be compatible with it. I prefer document annotations.

### Alternatives

Suggest maintainers to document and annotate it, or to be compatible with it. I prefer document annotations.

**Comment by Mugen87** [comment]
I don't have an iOS device at hand but here is a fiddle that uses a canvas texture with WebGL 1 so it's possible to reproduce/verify the issue.

https://jsfiddle.net/ocamsh1t/

**Comment by Mugen87** [comment]
> will not work properly 

Do you mind explaining in more detail what that means? Is the texture just black?

**Comment by 271642183** [comment]
> > 将无法正常工作
> 
> 你介意更详细地解释一下这意味着什么吗？纹理只是黑色吗？

When I render using WebGL1Render instead of WebGLRender, the texture is always black,

When using WebGLRender, creating text using document.createElementNS can display it, but multiple document.createElementNS may not be updated. Unfortunately, the 16.5 OffscreenCanvas has not been fixed yet

> > will not work properly
> 
> Do you mind explaining in more detail what that means? Is the texture just black?

When I render using WebGL1Render instead of WebGLRender, the texture is always black,

When using WebGLRender, creating text using document.createElementNS can display it, but multiple document.createElementNS may not be updated. Unfortunately, the 16.5 OffscreenCanvas has not been fixed yet

**Comment by 271642183** [comment]
> > will not work properly
> 
> Do you mind explaining in more detail what that means? Is the texture just black?

When I render using WebGL1Render instead of WebGLRender, the texture is always black,

When using WebGLRender, creating text using document.createElementNS can display it, but multiple document.createElementNS may not be updated. Unfortunately, the 16.5 OffscreenCanvas has not been fixed yet

**Comment by arpu** [comment]
https://discourse.threejs.org/t/workaround-of-webglstate-texture-error-on-iphone-ipad-macos-16-4/50519/2

**Comment by Mugen87** [comment]
Why do browsers on iOS 16 still use WebGL 1? 

Does the app force a WebGL 1 context or is WebGL 2 not supported for some reasons?

**Comment by arpu** [comment]
Yes in my example we still use webgl1 on ios at the moment ( switching to webgl2 is planned soon for us, but still problems on ios 14/15 with webgl2)

**Comment by Mugen87** [comment]
Since we have deprecated WebGL 1 with the next release, I don't think updating the documentation with WebGL 1 specific workarounds or topics is appropriate anymore. With `r163`, WebGL 1 support will be completely removed so at that point you have to upgrade to WebGL 2 or stick to an older `three.js` release.
