### ISSUE TITLE
Car materiel example broken

### ISSUE THREAD

**Issue by bergden-resonai** [mrdoob/three.js#26112]
### Description

https://threejs.org/examples/?q=car#webgl_materials_car
Worked up until r151: https://raw.githack.com/mrdoob/three.js/r151/examples/webgl_materials_car.html

### Reproduction steps

1. Open the example

### Live example

https://threejs.org/examples/?q=car#webgl_materials_car

### Screenshots

<img width="1920" alt="image" src="https://github.com/mrdoob/three.js/assets/37291459/b02b9f37-a21e-4e73-9bc7-a8ec14d10102">

### Version

r152

### Device

Desktop, Mobile

### Browser

Chrome, Safari

### OS

MacOS

**Comment by bergden-resonai** [comment]
Noting that this example works:
https://threejs.org/examples/#webgl_materials_envmaps_groundprojected

**Comment by bergden-resonai** [comment]
Nevermind, I can't reproduce - might've been a race condition of some sorts, but now it works consistently

**Comment by mrdoob** [comment]
A race condition in the car examples 🤓
