### ISSUE TITLE
SVGLoader example is broken since r152

### ISSUE THREAD

**Issue by bergden-resonai** [mrdoob/three.js#26110]
### Description

Worked till r151: https://raw.githack.com/mrdoob/three.js/r151/examples/webgl_loader_svg.html
Not there's a big amount of z-ordering issues on most examples and the default tiger svg:
https://raw.githack.com/mrdoob/three.js/r152/examples/webgl_loader_svg.html

https://github.com/mrdoob/three.js/assets/37291459/b704d073-1392-4a2b-b08b-8006167e9e2c
(video showing r152 and then r151 and then back to r152)

Worth mentioning there's also a page resize issue but that existed in previous versions as well

### Reproduction steps

1. Open the example: https://threejs.org/examples/#webgl_loader_svg
2. Rotate the scene
3. Look 👀 

### Screenshots

<img width="696" alt="image" src="https://github.com/mrdoob/three.js/assets/37291459/0155a413-2f15-4918-b673-dab8df92da08">
<img width="786" alt="image" src="https://github.com/mrdoob/three.js/assets/37291459/689153c1-c5b6-4b49-a337-56759943c3f7">

### Version

r152

### Device

Desktop, Mobile

### Browser

Chrome, Firefox, Safari

### OS

MacOS, Android

**Comment by Mugen87** [comment]
Um, if we don't want to revert https://github.com/mrdoob/three.js/pull/25913, `SVGLoader` probably needs to define a render order for its shapes.
