### ISSUE TITLE
WebGPU: Support more texture formats transcoded from KTX2

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#26124]
### Description

Seems this example: https://threejs.org/examples/?q=compressed#webgpu_loader_gltf_compressed
produces an error message: `WebGPURenderer: Unsupported texture format. 33776`

### Reproduction steps

1. Go to https://threejs.org/examples/?q=compressed#webgpu_loader_gltf_compressed
2. Note nothing loads
3. Open console and see errors (an initial one and then every frame)

### Code

-

### Live example

https://threejs.org/examples/?q=compressed#webgpu_loader_gltf_compressed

### Version

latest + dev

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by donmccurdy** [comment]
Related:

- #25864
- #25867

I believe our WebGPU implementation is limited to ETC2 at the moment, and DXT1 is not yet implemented. So this demo may or may not work, depending on the device accessing it.

**Comment by hybridherbst** [comment]
I see. Then maybe there should be a note regarding this in the header for now? For someone (e.g. me) looking at "how ready is WebGPU in three.js" a sample just logging exceptions isn't ideal I think.

**Comment by Mugen87** [comment]
S3TC should be supported, more specifically DXT1, DXT3 and DXT5. The following formats are supported right now:

https://github.com/mrdoob/three.js/blob/f9efcb74edb459b1c79f6a852b2668cb1fe0e9eb/examples/jsm/renderers/webgpu/utils/WebGPUConstants.js#L145-L207
