### ISSUE TITLE
Sprites with alphaMaps do not render

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#26127]
### Description

The sprite is not rendered at all. There are no console errors.

Works with r150. Fails with r151.

### Reproduction steps

Paste the code snippet below into the `webgl_sprites.html` example.

### Code

```js
function createHUDSprites( texture ) {

	const material = new THREE.SpriteMaterial( { alphaMap: texture, alphaTest: 0.5, transparent: false } );

	const width = material.alphaMap.image.width;
	const height = material.alphaMap.image.height;
```

### Live example

`webgl_sprites.html` example, modified.

### Version

r151 or later

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
For reproduction: https://jsfiddle.net/4tdLgcv3/

**Comment by Mugen87** [comment]
Maybe related to the multiple UV sets change. I can't see any `Sprite` specific changes in `r151`.

**Comment by Mugen87** [comment]
Okay, the uniform update for `alphaMapTransform` is missing. I'll file a PR.
