### ISSUE TITLE
Unable to use any WebXR AR app on MS Edge

### ISSUE THREAD

**Issue by Julexpuru** [mrdoob/three.js#26133]
### Description

Hello everyone

I'm developing a WebXR app with three.js for HoloLens 2 and at this point the project has different functional stages. While developing a non functional version of it, I reversed the code to a safe, tested and functional branch only to find that it no longer worked. The issue: ARButton for XRSession specifies that AR is not supported (it formerly did in this app version).

After some frustrating debugging process, we've tried to launch a minimal version of the app just with the button. Same result.
Then we started digging in the different Edge updates in order to find if it was related. Even if it's not stated in the logs, we've found that there have been some updates in the past weeks.

Following this browser hypothesis, we've tried to open the app in our cellphones both in chrome and edge. Chrome did indeed allow us to launch the XRSession through the ARButton but in Edge we found the same issues that above.

Finally, in order to discriminate if it was our codes issue, we tried to open all the webxr examples at https://threejs.org/examples/?q=webxr . The behaviour was the previous one, both in the Hololens and our mobile devices.

Both this final steps were tested in different edge an three versions through the different devices, but for the record the Hololens2 Edge current version is 113.0.1774.42 in our headset device.

Is there any known issue about this or any kind of fix? 
Thanks in advance.

### Reproduction steps

1. Open Edge in any AR capable device
2. Try any WebXR example at https://threejs.org/examples/?q=webxr

### Code

Not relevant

### Live example

None

### Version

150.1

### Device

Mobile, Headset

### Browser

Edge

**Comment by Mugen87** [comment]
Do these plain WebXR AR demos work on HoloLens 2? https://immersive-web.github.io/webxr-samples/

I want to make sure that it is not a three.js specific issue that causes the issue.

**Comment by Julexpuru** [comment]
Hi. Thanks for your quick answer.

No, those examples do not work either:
![20230526_112813_HoloLens](https://github.com/mrdoob/three.js/assets/31987441/6c7a797d-7ad8-4ebe-a6e0-9829f88b9abd)

As expected, seems to be something browser related. What I do not know is if it's an issue of three/whichever other library taking compatibility actions with this browser, or at the other end, Edge just shutting down all its AR capabilities.

**Comment by Mugen87** [comment]
It it possible to report such issue to Microsoft directly? I know there is a bug tracker for Chromium (https://bugs.chromium.org/p/chromium/issues/list) but since you don't experience the issue with Chrome, it seems related on the Edge-specific code on top of Chromium.

**Comment by Mugen87** [comment]
That would be good! MS should definitely be informed about this issue.

**Comment by mrdoob** [comment]
Definitely a browser issue. Hope they fix it 🤞
