### ISSUE TITLE
Couldn't load texture blob

### ISSUE THREAD

**Issue by 1593292349** [mrdoob/three.js#26139]
### Description

An error was reported after the scene was loaded several times using iframe on the mobile terminal.
I guarantee that all memory is free.

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

no

### Screenshots

![QQ图片20230526111051](https://github.com/mrdoob/three.js/assets/48791868/1575babc-2942-4da1-86bf-a4b86c6798b5)
![QQ图片20230526111303](https://github.com/mrdoob/three.js/assets/48791868/1ba33392-6575-406a-918c-f248b6304dc5)

### Version

0.152.2

### Device

Mobile

### Browser

Chrome

### OS

Android

**Comment by mrdoob** [comment]
Sorry, we need live example.
