### ISSUE TITLE
Way to control gl.STENCIL_BUFF_BIT in updateMultisampleRenderTarget

### ISSUE THREAD

**Issue by ligaofeng0901** [mrdoob/three.js#26143]
### Description

I notice when we use `WebGLMultipleRenderTargets` with MSAA on, the performance is very bad on Windows platform.
After searching, I found this article https://groups.google.com/g/webgl-dev-list/c/iwIYWPPJwoQ
In short, there is a D3D bug on Windows platform when we use MSAA with depth-stencil blit, 60fps will drop to 10fps, GPU will be blocked about 100ms in each frame.
I found that in https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLTextures.js#L1846. When both 
 depthBuffer and stencilBuffer are set to `true`,  `_gl.blitFramebuffer` will be invoked with mask _gl.DEPTH_BUFFER_BIT|_gl.STENCIL_BUFFER_BIT, which cause the peformance issue. My use case is that I want to keep  depthBuffer and stencilBuffer on, but don't use gl.STENCIL_BUFFER_BIT when blitFramebuffer, so I need some parameter to control the value of mask.

### Solution

The problem only occurs with `WebGLMultipleRenderTargets`, so we can add some extra parameter to it, to control whether to keep  depth or stencil value when blit from framebuffer to renderbuffer

### Alternatives

-

**Comment by Junior2Ran** [comment]
> Is it possible to work around this with multiple blit calls?

Any further explain? I am facing the exactly same problem!! I can not wait to solve the problem!

**Comment by CodyJasonBennett** [comment]
Aside from allowing this behavior to be configurable, blitting stencil separately since that's not hardware accelerated on ANGLE/D3D11.

**Comment by Mugen87** [comment]
Should be fixed since `r164` via #28096.
