### ISSUE TITLE
Matrix3 rotate why (- theta) in premultiply argument

### ISSUE THREAD

**Issue by EslamNemr** [mrdoob/three.js#26158]
### Description

Hi;
in Matrix3 class, rotate method why theta become (- theta) which lead rotation to be clockwise;

### Reproduction steps

1-new Vector2(1,1)
1.new matrix3.makRotation(theta)
2.matrix3.rotate(theta)
3.vec2.applyMatrix3(matrix3)
will return to its starting coordinates (x,y).

the idea is to use matrix3 as 2d object matrix so if I have initial rotation matrix3 then compose to matrix and not set it. 

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r152

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by WestLangley** [comment]
See https://github.com/mrdoob/three.js/pull/24733 for an explanation why they should be removed.

Use the replacement methods, instead. https://github.com/mrdoob/three.js/pull/24985.
