### ISSUE TITLE
Circular dependency in NodeMaterial

### ISSUE THREAD

**Issue by RecuencoJones** [mrdoob/three.js#26161]
### Description

We are currently trying to move from three r144 to r152 and noticed a circular dependency was introduced in `three/examples/jsm/nodes/materials/NodeMaterial.js` with `LightsNode.js`. 

When trying to build with webpack and the CircularDependencyPlugin, we get the following warnings:

```
WARNING in Circular dependency detected:
node_modules/three/examples/jsm/nodes/lighting/AnalyticLightNode.js -> node_modules/three/examples/jsm/nodes/materials/MeshBasicNodeMaterial.js -> node_modules/three/examples/jsm/nodes/materials/NodeMaterial.js -> node_modules/three/examples/jsm/nodes/lighting/LightsNode.js -> node_modules/three/examples/jsm/nodes/lighting/AnalyticLightNode.js

WARNING in Circular dependency detected:
node_modules/three/examples/jsm/nodes/lighting/LightsNode.js -> node_modules/three/examples/jsm/nodes/lighting/AnalyticLightNode.js -> node_modules/three/examples/jsm/nodes/materials/MeshBasicNodeMaterial.js -> node_modules/three/examples/jsm/nodes/materials/NodeMaterial.js -> node_modules/three/examples/jsm/nodes/lighting/LightsNode.js

WARNING in Circular dependency detected:
node_modules/three/examples/jsm/nodes/materials/MeshBasicNodeMaterial.js -> node_modules/three/examples/jsm/nodes/materials/NodeMaterial.js -> node_modules/three/examples/jsm/nodes/lighting/LightsNode.js -> node_modules/three/examples/jsm/nodes/lighting/AnalyticLightNode.js -> node_modules/three/examples/jsm/nodes/materials/MeshBasicNodeMaterial.js

WARNING in Circular dependency detected:
node_modules/three/examples/jsm/nodes/materials/NodeMaterial.js -> node_modules/three/examples/jsm/nodes/lighting/LightsNode.js -> node_modules/three/examples/jsm/nodes/lighting/AnalyticLightNode.js -> node_modules/three/examples/jsm/nodes/materials/MeshBasicNodeMaterial.js -> node_modules/three/examples/jsm/nodes/materials/NodeMaterial.js
```

### Reproduction steps

1. Import `NodeMaterial`
2. Compile or Serve with webpack

### Code

https://github.com/RecuencoJones/threejs-examples-circular-dependency/blob/main/src/index.js

### Live example

* https://github.com/RecuencoJones/threejs-examples-circular-dependency

### Version

r152

### Device

Desktop

### Browser

Edge

### OS

MacOS

**Comment by LeviPesin** [comment]
@sunag Seems like https://github.com/mrdoob/three.js/pull/25822 broke this? Can we somehow remove the import of MeshBasicNodeMaterial from AnalyticLightNode?

**Comment by sunag** [comment]
@LeviPesin Perhaps we should add a test routine to this.

**Comment by sunag** [comment]
Fixed :) 
https://github.com/mrdoob/three.js/pull/26163

**Comment by RecuencoJones** [comment]
That was fast! Thanks a lot! 😄

**Comment by LeviPesin** [comment]
> @LeviPesin Perhaps we should add a test routine to this.

@marcofugaro Can you please add such a test?
