### ISSUE TITLE
WebXR polyfill broken since before 2020. Ok with Babylon

### ISSUE THREAD

**Issue by danrossi** [mrdoob/three.js#26166]
### Description

I have a need to keep supporting the WebXR polyfill due to IOS still not enabling WebXR. The project is vacant and have to maintain some fixes myself. I've struggled to do tests to find where the problem is. It's something to do with missing buffers and wrong programs enabled. 

I was able to produce an AB test with Babylon that shows it working. It can be tested in Firefox Dev with webxr not enabled.

Some of the examples not using SphereGeometry and video seem to work, but then trying equi and stereo video does not. And breaks further exiting XR. 

I went through commits all the way back to 2020 and it's doing the same thing. 

### Reproduction steps

Errors produced

```
WebGL warning: drawElementsInstanced: Vertex attrib array 0 is enabled but has no buffer bound. 
```

### Code

```js
// code goes here
```

### Live example

works https://dev.electroteque.org/three/examples/webxr_vr_rollercoaster.html

Stereo video right eye is broken. Any stereo video setup is missing the right eye

http://dev.electroteque.org/three/examples/webxr_vr_video.html

equi video, no distortion rendering is black then returns as a black frame. Rendering breaks.

http://dev.electroteque.org/three/examples/webgl_video_panorama_equirectangular.html
https://dev.electroteque.org/three/examples/webgl_video_panorama_corrected.html

Babylon AB test works no errors.

https://dev.electroteque.org/three/babylon/index.html

### Version

153dev

### Device

Desktop

### OS

Windows

**Comment by danrossi** [comment]
I know it's a waste of my time but I got complaints depreciating it. I still load it for WebVR polyfill functions. But from my tests in IOS 16.4 sessions are not supported although xr enabled. Its possible they won't support a native cardboard view like Android. And it might land officially in IOS 17 as usual. 

https://electroteque.org/dev/xr/xrcheck.html 

I'll ask their ticket for session support without the headset active. It's highly likely I won't be able to access both an Iphone11+ and headset to even test that. 

https://bugs.webkit.org/show_bug.cgi?id=208988#c18

What I am trying to work out still why its breaking complaining about vertex buffer and the same when exiting. its a trial and error to see what part is causing the problem.

**Comment by danrossi** [comment]
I was going to also mention. Like with experience with the cross origin and HLS texture bugs of which I spent 3 months finding a work around for. They won't release it properly until a major version. IOS 17 is dropping support for some devices including iPhoneX. I believe the polyfill will still be needed as fallback. I've had to spam them due to inability to update comments to ask about screen orientation lock api required for WebXR also. I'm not sure if they will be implementing that. I have a polyfill for that I built that includes a css orientation hack for IOS.

**Comment by mrdoob** [comment]
Supporting Cardboard at this point is like trying to support Commodore Amiga and Nvidia RTX at the same time 😁

**Comment by danrossi** [comment]
Supporting Iphone at all is what you mentioned lol. Don't knock my C128 it was awesome. You would be surprised who want it working again, I got complaints. And it will be needed for devices that won't be able to run IOS 17. 

Until the flags begin working which is not the case in IOS 16.5. I've done further investigation in webkit tickets and what they will be supporting and it's messy. 

There is an active ticket for html fullscreen api support in Iphone that will make it useful again for canvas fullscreen to complement WebXR like every other device out there. Only Ipad supports that right now and it may not be likely to have fullscreen api in IOS 17. It's been sitting there for a good few years and I had to update it in regards WebXR.
 
I've only just discovered screen orientation locking api support not enabled and on enabling it, it requires html fullscreen support so Ipad only. But then in Ipad it breaks in Safari complaining it supports multi tasking. I've tried to let them know. I'm not sure in orientation lock api will begin working when WebXR does. I tried to implement a css orientation fallback but it doesnt work right and too much manipulating elements. 

For legacy support for showing a webgl rendering in native fullscreen as css hacks just dont work and hide address bars in Iphone I had to pull off this incredible hack.  It supports picture in picture for video texture rendering also. 

So even with WebXR which we don't know needs a headset to enable a session, alot of things in Iphone is legacy. 

https://github.com/danrossi/canvas-pip-fullscreen

**Comment by danrossi** [comment]
The headset is $3500USD. There is no update in the webkit ticket if sessions will be supported in safari natively like Android as the api is enabled but no session support yet. There is something going on with buffers and programs in the distorter. I know the project is vacant but have to cover IPhone legacy support.

https://github.com/immersive-web/cardboard-vr-display/blob/main/src/cardboard-distorter.js

**Comment by danrossi** [comment]
I'm back onto this. I have so many asking about it for legacy support for Iphone. There is no information how webxr will work in IOS 17, no movement on the webkit ticket and it currently doesnt enable a session in IOS 16. There is something wrong with the cardboard distorter setting up buffer and fails to renderer an eye / layer. It's obviously broken in Aframe also but works in Babylonjs. It's premature to deprecate this yet.  

I could scrap that deprecated project if I can find a way to put barrel distortion with the StereoEffect ? Then I can make it go fullscreen using my Iphone fullscreen video rendering hack and orientation controls. There is old discussions but not sure how to apply to current stereoeffect.

**Comment by danrossi** [comment]
I'm closing this in favour of trying to get StereoCamera working with EffectComposer. I have a distortion pass that works for one eye so far I just need to figure out how to make stereo work with effect composer. I'll have to build another solution for Iphone using my canvas fullscreen hack to go fullscreen, Iphone is legacy full stop so far but there is nothing that works for threejs out there so far and I can see WebXR and even html fullscreen into Iphone taking a long time. It was all deprecated and abandoned too prematurely thanks to Iphone. 

https://discourse.threejs.org/t/stereoeffect-with-effectcomposer/53598
