### ISSUE TITLE
There is an issue with the GLB model display

### ISSUE THREAD

**Issue by calmheaded** [mrdoob/three.js#26164]
### Description

This is how I load this chassis model using Threejs
![image](https://github.com/mrdoob/three.js/assets/22089884/3417cfeb-7aa2-4ad2-9938-67813284364a)

But opening this model on Blender is like this

![image](https://github.com/mrdoob/three.js/assets/22089884/f5f14753-5438-41de-9e12-fc199687383d)

### Reproduction steps

Just loading the model without any processing

![image](https://github.com/mrdoob/three.js/assets/22089884/56ce3df2-7d02-4d0a-9f98-230d2c21d16d)

    // 添加灯光
				var light = new THREE.HemisphereLight(0xffffff, 0x080808, 1);
				scene.add(light);
				scene.add(new THREE.AmbientLight(0x505050));

### Code

![image](https://github.com/mrdoob/three.js/assets/22089884/1ee39b13-7582-4287-89cf-90e98a520f22)

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

145dev

**Comment by calmheaded** [comment]
![image](https://github.com/mrdoob/three.js/assets/22089884/fb6cf6aa-9421-49bb-a02c-5c64c5cf4803)
If I add a spotlight in front, I can see that this side should not be black
![image](https://github.com/mrdoob/three.js/assets/22089884/71a61fab-ba3a-482a-9685-5150dd0f1a03)
![image](https://github.com/mrdoob/three.js/assets/22089884/64efe165-f481-42a6-856f-6c093715eed5)
But these two sides have turned black again, and it feels like it's not a matter of light, it's a matter of material handling. This material is MeshStandardMaterial

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests. If it turns out to be a problem with the library, we can reopen the issue.
