### ISSUE TITLE
OrbitControls  

### ISSUE THREAD

**Issue by sisiAHAH** [mrdoob/three.js#26192]
### Description

I use OrbitControls  control PerspectiveCamera mouse roll camera move model cannot move

### Reproduction steps

1.OrbitControls  
2.OrbitControls  
3.OrbitControls  

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

I use OrbitControls  control PerspectiveCamera mouse roll camera move model cannot move

### Version

0.145.0

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by sisiAHAH** [comment]
I use OrbitControls control PerspectiveCamera mouse roll camera move model centre cannot move

**Comment by Mugen87** [comment]
Please ask for help at the [forum](https://discourse.threejs.org/).
