### ISSUE TITLE
Trasparency fluctuates per camera position

### ISSUE THREAD

**Issue by obsius** [mrdoob/three.js#26221]
### Description

This may be more of a "bug" in the migration guide from 151 -> 152 then the code itself, but in r152, the following change (and corresponding PR) are mentioned in the release notes:

`
Sort on bounding sphere center, not origin. https://github.com/mrdoob/three.js/pull/25913 (@donmccurdy)
`

What used to be stable sorting for transparency now fluctuates as the camera is rotated:

![example](https://github.com/mrdoob/three.js/assets/20999862/64f05d87-f1cb-4214-861b-dcf48c543506)

It's not immediately clear to me if this is a preexisting issue with my use of THREE.js now revealed, or if this is a known and intended consequence of the change. Is there something I should be doing to restore r151 and earlier behavior? Also, I think it would be beneficial to mention this new behavior in the migration guide to save others the trouble.

Thanks.

### Reproduction steps

Update from r151 to 152.

### Code

Concerning aforementioned PR.

### Live example

See gif above.

### Version

152

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by donmccurdy** [comment]
There's a longer discussion in https://github.com/mrdoob/three.js/pull/25913 that may  be helpful here. Realtime renderers use [painter's sort](https://en.wikipedia.org/wiki/Painter%27s_algorithm) to order objects by distance from the camera, as that tends to be best choice for both performance and transparency rendering. The changes in #25913 allow three.js to find that order in some cases where it previously could not.

There do exist cases where you *don't* want this behavior – particularly where a stable order is critical, or transparent objects are nested within one another. No one-size-fits-all answer there, but `renderer.sortObjects = false` might be what you're looking for.

Upcoming work in https://github.com/mrdoob/three.js/pull/24271 may also be helpful for scenes like yours, with nested or interlocked transparent surfaces.

**Comment by obsius** [comment]
Thanks. Disabling sortObjects helped to an extent, but setting render orders on the topographies and leaving the new sort in place worked best. Look forward to your upcoming PR for overlapping transparent surfaces. Thanks again for the hard work you and the rest of the THREE.js team do.
