### ISSUE TITLE
WebGPURenderer produces washed out colours compared to WebGL

### ISSUE THREAD

**Issue by danrossi** [mrdoob/three.js#26233]
### Description

I've integrated a bundle of the WebGPURenderer to begin testing and I am seeing a difference in the colors produced compared to WebGLRenderer. They are highly exposed. I'm not sure if a property is needed for it. 

The WebXR manager is also not available yet and might need integration. 

### Reproduction steps

live examples

### Code

```
camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 1, 1100 );

scene = new THREE.Scene();

const geometry = new THREE.SphereGeometry( 500, 60, 40 );
// invert the geometry on the x-axis so that all of the faces point inward
geometry.scale( - 1, 1, 1 );

const video = document.getElementById( 'video' );
video.play();

const texture = new THREE.VideoTexture( video );
texture.colorSpace = THREE.SRGBColorSpace;
const material = new THREE.MeshBasicMaterial( { map: texture } );

const mesh = new THREE.Mesh( geometry, material );
scene.add( mesh );

if (await WebGPU.isAvailable()) {
	renderer = new WebGPURenderer();
} else {
	renderer = new THREE.WebGLRenderer();
}



renderer.setPixelRatio( window.devicePixelRatio );
renderer.setSize( window.innerWidth, window.innerHeight );
container.appendChild( renderer.domElement );
```

### Live example

* WebGPU - https://danrossi.github.io/three-webgpu-renderer/tests/webgpu_video_panorama_equirectangular.html
* WebGL - https://danrossi.github.io/three-webgpu-renderer/tests/webgl_video_panorama_equirectangular.html

### Version

153dev

**Comment by Mugen87** [comment]
At first sight it looks like the color space for the video texture isn't honored.

**Comment by danrossi** [comment]
ok a color space issue I am seeing it on other projects. I can help debug it perhaps. So its on any texture setting or the renderer as the renderer as colorSpace and outsideColorSpace.

**Comment by danrossi** [comment]
I'm experiencing high cpu usage with webcam MediaStream based video texture and will make a seperate ticket once I make a demo. 

So I update my examples with those colorSpace property settings or does it need to be updated internally ?

**Comment by danrossi** [comment]
The Linear color space stops the problem but only when configuring outputColorSpace. changing the texture colorspace didn't resolve it.

https://github.com/danrossi/three-webgpu-renderer/blob/master/tests/webgpu_video_panorama_equirectangular.html#L91

**Comment by danrossi** [comment]
This is possibly replated and "washed out" is gamma correction is needed when srb is used ?

https://discourse.threejs.org/t/updates-to-color-management-in-three-js-r152/50791/53

**Comment by Mugen87** [comment]
@danrossi Please wait until @sunag responds to this issue. You will not speed-up this process by posting at every related thread/topic.

**Comment by sunag** [comment]
We're using `GPUExternalTexture` for video, which is recommended by WebGPU, but it doesn't support `UNORM`, so we'll have to me this color space conversion via code. I will work on this fix.

**Comment by danrossi** [comment]
I get carried away and spam sorry guys. It's something to do with video textures but I saw it on images loaded by the TextureLoader also. I can make an example for that. Thanks.

**Comment by Mugen87** [comment]
I suggest you wait until this particular issue is fixed. It's about wrong/missing color space conversion.

The performance issues are something that I would investigate separately _after_ the colors are right. If there are performance issues in the WebGPU implementation, we have to delegate these to the Chromium team in any event. But first, we should make sure the visual results on our side are correct.

**Comment by danrossi** [comment]
OK I found a possible AB test this doesn't have color or cpu resource issues but it's a small canvas. So I will wait to report my findings with chrome. https://webgpu.github.io/webgpu-samples/samples/videoUploading

**Comment by danrossi** [comment]
Confirmed it is working. But I need to figure out how to report the performance problem with videotextures with Chrome. Do I add it here or with chrome ?

**Comment by Mugen87** [comment]
I think it's okay to open an issue here first. When we are sure it's not three.js related, we can delegate the issue to the Chromium bug tracker.

**Comment by Mugen87** [comment]
Oh, you already did^^: https://github.com/mrdoob/three.js/issues/26266
