### ISSUE TITLE
The rate of radiographic inspection has dropped dramatically

### ISSUE THREAD

**Issue by mengyusong** [mrdoob/three.js#26245]
### Description

Starting from version 150, the rate of radiographic inspection has dropped significantly in the scene of a large number of models, and the frame rate has dropped by about 10 frames compared to version 149.

### Solution

In the case of a large number of models, the rate of radiographic inspection increases

### Alternatives

In the case of a large number of models, the rate of radiographic inspection increases

**Comment by donmccurdy** [comment]
Sorry, I'm not sure what radiographic inspection means. If your scene's performance is slower in r150 than in r149, please fill in *all* fields in the bug report template:

https://github.com/mrdoob/three.js/issues/new?assignees=&labels=&projects=&template=bug_report.yml
