### ISSUE TITLE
Some gltf models not rendering properly on Safari (Mac OS)

### ISSUE THREAD

**Issue by tomfelder94** [mrdoob/three.js#26240]
### Description

Some 3D models show obvious artifacts (texture flickering) when rendered in Safari on MacOS. This does not happen with BabylonJS. It might related to the environment map. If one disables it, e.g. on [Don McCurdy's viewer](https://gltf-viewer.donmccurdy.com/), the problem disappears. It only happens on Safari on MacOS.

### Reproduction steps

1. Open Safari 16.5 on Mac OS Ventura 13.4 
2. Go on [model viewer main page](https://modelviewer.dev)
3. See flickering on astronaut model

This happens for different models in different gltf viewers (also on [Don McCurdy's viewer](https://gltf-viewer.donmccurdy.com/)), but the most obvious was to show the example on the model viewer homepage

### Code

none

### Live example

https://github.com/mrdoob/three.js/assets/101552390/c3c84c2a-8658-4e50-88c2-6149e36cfe08

https://github.com/mrdoob/three.js/assets/101552390/b9a78a29-1db1-4484-898d-28bdf06bde3d

### Version

r151

### Device

Desktop

### Browser

Safari

### OS

MacOS

**Comment by Mugen87** [comment]
What kind of hardware are you using? Do you mind sharing more details about the CPU/GPU?

When you go to `Develop`→ `Experimental Features` is there a check at `WebGL via Metal`?

Since it only happens in Safari: Can you give Safari Technology Preview a try?

**Comment by tomfelder94** [comment]
I am using a MacBook Pro, 16 inch, 2019. See details below. Yes, `WebGL via Metal` is checked. Same thing is happening on Safari Technology Preview.

CPU: 2.3 GHz 8-Core Intel Core i9
GPU: AMD Radeon Pro 5500M 4 GB
Intel UHD Graphics 630 1536 MB
Memory: 16 GB 2667 MHz DDR4

**Comment by Mugen87** [comment]
> Yes, WebGL via Metal is checked.

What does happen if you remove the check so Safari uses OpenGL?

**Comment by tomfelder94** [comment]
Yes, only happens on Safari. Actually, the WebGL via Metal was the issue! I removed the check and it looks fine.

**Comment by Mugen87** [comment]
> Actually, the WebGL via Metal was the issue! I removed the check and it looks fine.

Interesting! So there is an issue with Safari + Metal and the AMD GPU.

Can you reproduce the issue with this minimal live example: https://jsfiddle.net/um12ajvh/3/

Probably best to report the issue to the Webkit bug tracker (https://bugs.webkit.org/). The live example could be attached as a reproduction case.

**Comment by tomfelder94** [comment]
Yeah, seems like it. I cannot produce with the minimal live example. It's only happening with certain models in certain lighting conditions...

Will report it on the Webkit bug tracker. Thanks.
