### ISSUE TITLE
Viewport delay after moving, rotating,... 3d model.

### ISSUE THREAD

**Issue by quangtri3111996** [mrdoob/three.js#26257]
### Description

- Use https://threejs.org/editor/
- Add this 3d model to editor: https://drive.google.com/file/d/1kAWqByw_M9Zou5360FSYWhyPcg5eOYeI/view?usp=sharing
- I add the 3d model to the editor and I move the position of the model, when I release the mouse and rotate the camera, a delay occurs. I add more 3d models, the delay gets longer.
- Please watch the video for details: **https://drive.google.com/file/d/1NAAs6i9CnPACK7e9Xx1JjnA89uOqgAtt/view?usp=sharing**

### Reproduction steps

1. Go to https://threejs.org/editor/
2. Download and add the 3d model to editor (https://drive.google.com/file/d/1kAWqByw_M9Zou5360FSYWhyPcg5eOYeI/view?usp=sharing)
3. Move the position of the model. When you release the mouse, please use the mouse to rotate the camera, you will see a delay.

Please watch the video for details: **https://drive.google.com/file/d/1NAAs6i9CnPACK7e9Xx1JjnA89uOqgAtt/view?usp=sharing**

### Code

I use this code **https://github.com/mrdoob/three.js/tree/master/editor**

### Live example

*

### Version

r151

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
First of all, this is maybe the cutest 3D asset I have ever seen in my life! 🐶 

The model itself is only 2MB, it has a low vertex count, produces 3 draw calls, has 1 unlit material with a single 2048x2048 texture. I can't reproduce the stutter on my macMini with M2 Pro and latest Chrome.  But maybe there are serialization issues on your particular system. 

Do you also experience the stutter if you disable the autosave feature of the editor? You can do this by clicking on the checkbox in the top-right corner.

**Comment by quangtri3111996** [comment]
Hi @Mugen87, thanks for your help. It works fine
