### ISSUE TITLE
unable to access contexMenu, while OrbitControls is enabled

### ISSUE THREAD

**Issue by naeem-qv** [mrdoob/three.js#26252]
### Description

![context](https://github.com/mrdoob/three.js/assets/124234450/cebc9482-aedd-4be6-9126-063e680ef292)
While orbitcontrols is enabled we cannot access the default contex menu(inspect, view page source, etc...) in almost all the browsers.

### Reproduction steps

1.Tried the same examples with orbitcontrols enabled and disabled. in enabled one we cannot access default context menu but in disabled example we can access.

### Code

```js
<Canvas>
    <ambientLight />
    <pointLight position={[10, 10, 10]} />
    <Box position={[-1.2, 0, 0]} />
    <Box position={[1.2, 0, 0]} />
    <OrbitControls/>
  </Canvas>
```

### Live example

https://codesandbox.io/s/r3f-outlines-mq5oy?file=/src/index.js

### Version

153

### Device

Desktop

### Browser

Chrome, Firefox, Edge

### OS

Windows, Linux

**Comment by naeem-qv** [comment]
as you can see in the attached screenshot on onContexMenu event its preventing browsers default behavior by calling event.preventDefault()

**Comment by Mugen87** [comment]
This is intended because the right mouse button is in use by the controls. Doing a right mouse click for panning would trigger the context menu as well.
