### ISSUE TITLE
Only one animation works. When having a lot animation in a scene.

### ISSUE THREAD

**Issue by quangtri3111996** [mrdoob/three.js#26272]
### Description

I add 2 3d models with 2 animations(**https://drive.google.com/drive/folders/1rYjHz_pRYHIkHW7ZAwTQIWgbl4-JeuGZ?usp=sharing**) to the editor(**https://threejs.org/editor/**), all animation work in the editor. Then I export this scene with .glb format. And I use a 3d tool to view this scene (Blender,  Google model-viewer, ...). I realize only one animation work.

Please watch the video for details: **https://drive.google.com/file/d/1HEgG89D-0Ts0xPQ1MF_8fWk_Q7f86JoC/view?usp=sharing**

### Reproduction steps

1. Go to **https://threejs.org/editor/**
2. Add 2 models **https://drive.google.com/drive/folders/1rYjHz_pRYHIkHW7ZAwTQIWgbl4-JeuGZ?usp=drive_link**
3. Play animations of all models.
4. Export a scene with glb format.
5. Use a viewer tool to view this scene.
6. You can see only one animation of 2 models works.

Please watch video for details: **https://drive.google.com/file/d/1HEgG89D-0Ts0xPQ1MF_8fWk_Q7f86JoC/view?usp=sharing**

### Code

***

### Live example

***

### Version

r153

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
I guess you have already filed an issue for that: #24952

**Comment by quangtri3111996** [comment]
Hello @Mugen87, the issue #24952 occurs when I add 2 the same 3d models with 2 the same animations. On this issue it occur on 2 the other models with 2 the other animations

**Comment by Mugen87** [comment]
IMO, the root cause of this issue seems still the same. So when https://github.com/mrdoob/three.js/issues/24952 is fixed, this use case should also be handled.

**Comment by quangtri3111996** [comment]
Hi @Mugen87, thanks for your support.

**Comment by quangtri3111996** [comment]
Hi @Mugen87 Any updates on this issue ?

**Comment by Mugen87** [comment]
Not yet, sorry.
