### ISSUE TITLE
Can I offline runthe example html?

### ISSUE THREAD

**Issue by akira32** [mrdoob/three.js#26285]
### Description

I can run all examples of the html in doc folder by using vscode. But I wish offline to directly run the /examples/webgl_loader_mmd.html, but the chrome console appears some error as below:
Can I solve this problem？

`

webgl_loader_mmd.html:1 Access to script at 'file:///C:/WorkSpace/three.js-dev/build/three.module.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
webgl_loader_mmd.html:45 
 GET file:///C:/WorkSpace/three.js-dev/build/three.module.js net::ERR_FAILED
webgl_loader_mmd.html:1 Access to script at 'file:///C:/WorkSpace/three.js-dev/examples/jsm/libs/stats.module.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
webgl_loader_mmd.html:47 
 GET file:///C:/WorkSpace/three.js-dev/examples/jsm/libs/stats.module.js net::ERR_FAILED
webgl_loader_mmd.html:1 Access to script at 'file:///C:/WorkSpace/three.js-dev/examples/jsm/libs/lil-gui.module.min.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
webgl_loader_mmd.html:48 
 GET file:///C:/WorkSpace/three.js-dev/examples/jsm/libs/lil-gui.module.min.js net::ERR_FAILED
webgl_loader_mmd.html:1 Access to script at 'file:///C:/WorkSpace/three.js-dev/examples/jsm/controls/OrbitControls.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
webgl_loader_mmd.html:50 
 GET file:///C:/WorkSpace/three.js-dev/examples/jsm/controls/OrbitControls.js net::ERR_FAILED
webgl_loader_mmd.html:1 Access to script at 'file:///C:/WorkSpace/three.js-dev/examples/jsm/effects/OutlineEffect.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
webgl_loader_mmd.html:51 
 GET file:///C:/WorkSpace/three.js-dev/examples/jsm/effects/OutlineEffect.js net::ERR_FAILED
webgl_loader_mmd.html:1 Access to script at 'file:///C:/WorkSpace/three.js-dev/examples/jsm/loaders/MMDLoader.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
webgl_loader_mmd.html:52 
 GET file:///C:/WorkSpace/three.js-dev/examples/jsm/loaders/MMDLoader.js net::ERR_FAILED
webgl_loader_mmd.html:1 Access to script at 'file:///C:/WorkSpace/three.js-dev/examples/jsm/animation/MMDAnimationHelper.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
webgl_loader_mmd.html:53 
`

### Solution

Using vscode with preview on web server extension can preview html of examples.

### Alternatives

Installing the example to iis or use vscode by preview function can see the html of example correctly.

**Comment by gkjohnson** [comment]
Please use the forum for help and questions:

https://discourse.threejs.org/
