### ISSUE TITLE
Extremely washed out colours when loading any kind of image or canvas as the texture

### ISSUE THREAD

**Issue by cazgp** [mrdoob/three.js#26296]
### Description

With a very basic rendered from the tutorial, I have created some meshes and applied image textures to them. The colours are extremely washed out. I have played around with all sorts of different settings from across the internet (gamma output, encoding, adding different light sources, etc), but nothing has helped.

I'm pretty sure this is a bug because it works properly in older versions of three.

### Reproduction steps

1. View the jsfiddle.

### Code

See the attached jsfiddle.

### Live example

* https://jsfiddle.net/xdwp05bh/

### Screenshots

How it renders:

![Screenshot from 2023-06-19 20-29-31](https://github.com/mrdoob/three.js/assets/658873/0dfd1373-7152-4c7b-b401-38e87c5246fc)

What it should look like (click link) https://placehold.co/600x400/orange/white

### Version

0.153

### Device

Desktop

### Browser

Chrome, Firefox

### OS

Linux

**Comment by Mugen87** [comment]
You have to define the right color space when loading textures. Use `THREE.SRGBColorSpace` to fix the issue.

https://jsfiddle.net/2eq4tj79/
