### ISSUE TITLE
Shadow not updated when object is outside of frustum

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#26292]
### Description

When skinned object casts shadow and the shadow is inside of visible frustum, but the object is outside, the shadow is frozen - its skeleton is never updated.

### Reproduction steps

I have created a modified bones-browser.html demonstrating this. I will include it in the PR together with issue resolution

### Code

---

### Live example

---

### Screenshots

https://github.com/mrdoob/three.js/assets/6927223/670a3cdb-fc7e-4e7c-984b-e3dfad172b5d

### Version

153

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
To clarify, was this issue introduced via #25937? 

Just want to know if this issue should be considered as a bug or a regression.

**Comment by OndrejSpanel** [comment]
I have checked the #25937 and I am a bit concerned how it is supposed to work together with #25612.

After #25612 culling computes a bounding volume by applying the bone transformation to all vertices of the mesh. If the skeleton is not updated, the bone transformation will not be accurate. If the skeleton is updated before culling, #25937 makes no sense.

I do not think it is possible to have BOTH: bounding volume accuracy AND performance. I personally would choose performance and supply only an approximate bounding volume, large enough to accomodate for all animations. One can probably do this by providing a custom class derived from `SkinnedMesh`, which will avoid the computation and store the expanded volume.

**Comment by Mugen87** [comment]
Bounding volumes are only generated if the respective properties are `null`. So if you define a bounding sphere before the first render, the will be no computation by the engine.

**Comment by OndrejSpanel** [comment]
OK. This means the accuracy is not there - if you change the animation, the mesh is still culled based on the bounding volume obtained by the previous skeleton configuration. I think this is not any better then using the bounding volume of the original (non-animated) mesh, at least in my application, and both solutions produce similar amount of false positives and negatives. I think for my application I will implement the custom conservatively expanded bounding volume - and as you have explained, I do not even need a custom mesh class for this, all I need to do is to set the bounding volumes.

Actually, when I have checked this in the debugger, I think #25612 does not seem to do anything now in a typical scenario. The `computeBoundingSphere` is called from culling. As the skeleton is not updated before culling, therefore bone matrices contain all identities and `SkinnedMesh.computeBoundingSphere` will compute the same as simply taking the `boundingSphere` of the geometry would.

The PR says:

> should fix a long-standing culling issue

Is there some repro / test case for the issue, so that we can verify it is still fixed?

**Comment by OndrejSpanel** [comment]
> all bone matrices contain identities

I am afraid I was wrong here and it is ever worse: `Skeleton.boneMatrices` contains all zeros, therefore the bounding volume computed this way will be one point only, not even the geometry bounding volume.

Perhaps someone can convince me I have overlooked something?

**Comment by Mugen87** [comment]
I suggest we revert #25937 for now (which your PR essentially) does and start from there. When I tested https://github.com/mrdoob/three.js/pull/25612, I've noticed it fixed a bunch of use case for me. And it definitely produces a better result than the geometry alone.

**Comment by OndrejSpanel** [comment]
> which your PR essentially does

I would not say that - this PR still keeps updates only inside of a frustum, it just makes sure they are done inside of shadow frustums as well. I might be wrong and it might do something other than I intended, though.

> #25612 definitely fixed a bunch of use cases for me.

Could you document some such case, so that it be verified, now and it the future, if the cases as still fixed?

**Comment by Mugen87** [comment]
> I am afraid I was wrong here and it is ever worse: Skeleton.boneMatrices contains all zeros, therefore the bounding volume computed this way will be one point only, not even the geometry bounding volume.

Wait, `Skeleton.update()` only updates the contents of the bone texture. Whether if this happens before or after the view frustum culling test has no influence on the bounding volumes.

**Comment by OndrejSpanel** [comment]
> One typical was [threejs.org/examples/webgl_loader_collada_skinning](https://threejs.org/examples/webgl_loader_collada_skinning).

For the record (and if anyone not aware what to look for is reading this), here is what I see with the fix removed:

https://github.com/mrdoob/three.js/assets/6927223/c672f3d6-26af-4775-8862-c61046a8be71

The trooper disappears as soon as his knees go out of the screen.

**Comment by ashconnell** [comment]
> @ashconnell What do you think about this issue and @OndrejSpanel's propose fix (#26293)?

Yeah I didn't even consider the issue with shadows here so happy to revert to a better solution. I'm not familiar enough with shadows to weigh in here.

**Comment by OndrejSpanel** [comment]
> happy to revert to a better solution

There is no need to revert. Your optimization is good, only it was not aware shadows can be rendered even when the objects themselves are not - and their rendering is done before the objects. This should be both fixed in PR #26293 (already merged).
