### ISSUE TITLE
Unable to resolve Mapcontrols even if it's installed

### ISSUE THREAD

**Issue by MuttonYung** [mrdoob/three.js#26298]
### Description

I installed three.js and types/three. When I try to build it comes to an ERROR: The following dependencies are imported but could not be resolved: three/examples/jsm/controls/MapControls.js. But actually, I can find this file in node_modules, along with other examples that can be imported currectly.

### Reproduction steps

1. Import three/examples/jsm/controls/MapControls.js.
2. Build the project.

### Code

```js
import { MapControls } from "three/examples/jsm/controls/MapControls.js"
```

### Live example

```js
import { ref, onMounted, reactive } from 'vue';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import Stats from 'three/examples/jsm/libs/stats.module.js';
import { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js';
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js';
import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader.js';
import { STLLoader } from 'three/examples/jsm/loaders/STLLoader.js';
import { RedEnvelopeFilled } from '@vicons/antd';
import { MapControls } from "three/examples/jsm/controls/MapControls.js";
import * as TWEEN from '@tweenjs/tween.js';
```

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/55025557/1b59e27c-c1bf-4333-a82a-aff6ccbfedd6)

![image](https://github.com/mrdoob/three.js/assets/55025557/4a9cc954-e257-4bab-ac6f-13c5a95fee0d)

### Version

@types/three@0.152.1 three@0.153.0

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by gkjohnson** [comment]
Please use the forum if you need to ask for help regarding how to use the project:

https://discourse.threejs.org/
