### ISSUE TITLE
Issue With Import * at THREE from ‘three’

### ISSUE THREAD

**Issue by JacksonUptain** [mrdoob/three.js#26318]
### Description

So I’ve had an issue when launching my three JS website… you can check out the repos code…but the error occurs on the first line: Import * as THREE from ‘three’…

I am using an import map…but I can’t seem to solve the issue.

### Reproduction steps

1. Check the code at:
2. HTTPS://GitHub.com/Jacksonuptain/
3. Navigate to Three Js Space

### Code

```js
Import * as THREE from “three”
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

Latest version 

### Device

Desktop

### Browser

Edge

### OS

Windows

**Comment by donmccurdy** [comment]
Hi! Please use the forums (https://discourse.threejs.org/) for help, we reserve GitHub issues for bug reports and discussion of feature development.
