### ISSUE TITLE
Spatial Audio not working correctly anymore in AR (nor VR)

### ISSUE THREAD

**Issue by marwie** [mrdoob/three.js#26331]
### Description

Hi,

in three 153 spatial / positional audio stopped working in AR. 
152 does still work

Possibly related to https://github.com/mrdoob/three.js/pull/26041

Is it now expected to add synchronization to the AudioListener in the camera in user code?

### Reproduction steps

1. Clone: 
https://github.com/needle-tools/three.js/tree/spatial-audio-doesnt-work-in-ar
2. Start local dev server `npm install && npm start`
3. Open `examples/webxr_vr_teleport.html` on a AR ready device (e.g. phone)
4. Enter AR
5. Audio is playing but doesnt react to AR movement 

### Code

See branch in reproduction steps (basically just added the audio related code from the position audio example)

### Version

r153

### Device

Mobile, Headset

### Browser

Chrome

### OS

Windows, Android

**Comment by mrdoob** [comment]
Can you try again now that it has been reverted? #26350

**Comment by marwie** [comment]
Thanks, it works again on r154
