### ISSUE TITLE
OutputPass: shader does not compile if renderer.toneMapping is set

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#26346]
### Description

Setting, for example,
```js
renderer.toneMapping = THREE.ACESFilmicToneMapping;
```
will cause `OutputPass` shader to fail to compile.

### Reproduction steps

1. Add `renderer.toneMapping = THREE.ACESFilmicToneMapping` to an example using `OutputPass`.

### Code

```js
renderer.toneMapping = THREE.ACESFilmicToneMapping
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r154dev

**Comment by Mugen87** [comment]
This happens because of GLSL redefinitions.

What is your use case for using `OutputPass` with inline tone mapping? I assumed this is no valid use case so I did not add support for this.

**Comment by WestLangley** [comment]
Yes, only `NoTonemapping` is correct when using `RenderPass`. I'm thinking it would be best for render pass to know that...

Also, I find it confusing that it is required to set tone mapping and exposure in two places: (1) for the renderer, and (2) for `OutputPass`.

**Comment by WestLangley** [comment]
Yes, only `NoToneMapping` is correct when using `RenderPass`. I'm thinking it would be best for render pass to know that...

Also, I find it confusing that it is required to set tone mapping and exposure in two places: (1) for the renderer, and (2) for `OutputPass`.

**Comment by Mugen87** [comment]
Indeed, it was mentioned in https://github.com/mrdoob/three.js/pull/26102#issue-1718442553 that `OutputPass` ideally extracts the settings from the renderer. 

I did not implement this yet because of the  mentioned GLSL redefinition in context `ShaderMaterial`. There is no runtime error with `RawShaderMaterial` however we can't include shader chunks with this material type. Not sure how to solve this yet.

**Comment by Mugen87** [comment]
We might want to file a new issue (or renaming this one and reopen) to track the better coupling of `OutputPass` to `WebGLRenderer`.
