### ISSUE TITLE
STLLoader: RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by Sea-DH1** [mrdoob/three.js#26352]
### Description

Scope error when adding stl file to scene

RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at isBinary (STLLoader.js:112:27)
    at STLLoader.parse (STLLoader.js:392:10)
    at FileReader.<anonymous> (Loader.js:577:39)

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r151

### Device

Desktop, Mobile

### Browser

Chrome

### OS

Windows, MacOS

**Comment by mrdoob** [comment]
Please share the file that gives you that error.

**Comment by meszaros-lajos-gyorgy** [comment]
I've got the same error and here's a file I tried loading (zipping it so that github accepts it): 
[618.stl.zip](https://github.com/user-attachments/files/15859850/618.stl.zip)

For comparision here's an online STL viewer that can load the file just fine: https://www.viewstl.com/

**Comment by meszaros-lajos-gyorgy** [comment]
The file I've attached in my previous comment supposedly has `65,021` faces - or at least this is what the `faces` variable has at the beginning of `parseBinary()`. If I multiply that with the 50 bytes mentioned in the [wikipedia article](https://en.wikipedia.org/wiki/STL_(file_format)#Binary) and add the header and triangle size then the resulting number is `3,251,134`, but `reader.byteLength` says that the total length of the file is only `1,711,878`, which seems about right as the stl file is 1.8 MB in size.

**Comment by meszaros-lajos-gyorgy** [comment]
I think the issue here is on my and OP's side, the data needs to be loaded as a Blob and then converted to an ArrayBuffer. The following example seems to return the correct numbers and does not throw an error.

```ts
const response = await axios.get<Blob>(url, {
  responseType: 'blob'
})

const arrayBuffer = await new Promise<ArrayBuffer>((resolve, reject) => {
  var fileReader = new FileReader();
  fileReader.onload = function(event) {
    if (event.target === null || event.target.result === null || typeof event.target.result === 'string') {
      reject()
    } else {
      resolve(event.target.result)
    }
  };
  fileReader.readAsArrayBuffer(response.data);
})

const data = loader.parse(arrayBuffer)
```

**Comment by MadMax888** [comment]
> I think the issue here is on my and OP's side, the data needs to be loaded as a Blob and then converted to an ArrayBuffer. The following example seems to return the correct numbers and does not throw an error.
> 
> ```ts
> const response = await axios.get<Blob>(url, {
>   responseType: 'blob'
> })
> 
> const arrayBuffer = await response.data.arrayBuffer()
> 
> const data = loader.parse(arrayBuffer)
> ```

I have the same issue but load and parse files via jszip. Your solution works for me as well
`
const response  = await zip.file(key).async('blob');
 const content = await response.arrayBuffer();
`
