### ISSUE TITLE
BufferGeometryUtils.toCreasedNormals() produces warning for non-indexed geometries

### ISSUE THREAD

**Issue by kpvhn** [mrdoob/three.js#26378]
### Description

`BufferGeometryUtils.toCreasedNormals()` produces a warning if the provided geometry is non-indexed:

```
THREE.BufferGeometry.toNonIndexed(): BufferGeometry is already non-indexed.
toNonIndexed @ three.module.js:10964
toCreasedNormals @ BufferGeometryUtils.js:1240
```

The method calls `BufferGeometry.toNonIndexed()` to convert possibly indexed geometries to non-indexed ones but does not check whether a geometry is already non-indexed.

It seems that `BufferGeometry.toNonIndexed()` should not be called when the geometry is not indexed, producing the warning.

In this case and contrary to documentation, **no new geometry** is returned but `this` geometry, which may be the reason for the warning, and the functions that trigger such a warning would be working on the original geometry, not on a non-indexed copy.

## Suggested solution

Alternatives:

1. Call `BufferGeometry.toNonIndexed()` only if geometry is indexed. Use the original geometry, as is already the case because `BufferGeometry.toNonIndexed()` returns `this` if the geometry is non-indexed.
  - ✅ Simple solution that removes the warning without changing behavior otherwise
  - ✅ Backwards compatible: drei's `<RoundedBox>` depends on this behavior.
  - ❌ Keeps modifying the original geometry if it is non-indexed.
2. Clone the geometry if it is non-indexed. Always operate on a new geometry.
  - ✅ Simple predictable behavior that follows the immutability pattern
  - ❌ Breaking change
3. Require the provided geometry to be indexed, fail otherwise.
  - ❌ Not very useful
  - ❌ Breaking change
4. Add optional parameter (e.g. `cloneIfNonIndexed`) to control behavior. If missing or falsy, behave like in suggestion **1.** If truthy, clone the geometry if it is already non-indexed like in **2.**
  - ✅ Optional immutability pattern
  - ✅ Backwards compatible (unless someone had been calling `toCreasedNormals()` with a third argument that is truthy)
  - ❌ Redundant additional checks that could run outside the method – the caller may have cloned already
5. Change `BufferGeometry.toNonIndexed()` to return a cloned geometry if it is already non-indexed
  - ❌ The caller can check if a geometry is indexed by checking the `BufferGeometry.index` property, which is what other code does, and clone the geometry if needed
  - ❌ Breaking change
5. Change `BufferGeometry.toNonIndexed()` to throw an error
  - ❌ Same drawbacks as **5.** in addition to:
  - ❌ Breaks all downstream code – `toCreasedNormals()` would need to change, and some code like @react-three/drei's `<RoundedBox>` rely on `toCreasedNormals()` to mutate the original geometry (though I should mention that  **drei** uses `three-stdlib`, not the code from **three.js** examples.

I prefer solution **1.** because it is the simplest.

See PR https://github.com/mrdoob/three.js/pull/26379

## See also

- corresponding issue for the **three-stdlib**:
  https://github.com/pmndrs/three-stdlib/issues/268
- discussion on Three.js discourse:
  [BufferGeometry.toNonIndexed() warns about `BufferGeometry is already non-indexed`](https://discourse.threejs.org/t/buffergeometry-tononindexed-warns-about-buffergeometry-is-already-non-indexed/53497)

### Reproduction steps

1. Create a non-indexed geometry
2. Call `BufferGeometryUtils.toCreasedNormals()` on the geometry
3. See browser Dev Tools console for warning: `THREE.BufferGeometry.toNonIndexed(): BufferGeometry is already non-indexed.`

### Code

```js
import { BoxGeometry } from "three";
import { toCreasedNormals } from "three/examples/jsm/utils/BufferGeometryUtils.js";

// produces warning
toCreasedNormals(new BoxGeometry().toNonIndexed());
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/q69fts5r/)
* [jsfiddle-dev](https://jsfiddle.net/hv5pLmgb/)

### Version

154

**Comment by Mugen87** [comment]
Fixed via #26379.
