### ISSUE TITLE
Color.setRGB and .setStyle are using different color space than .setHex, .setHSL

### ISSUE THREAD

**Issue by SkaceKamen** [mrdoob/three.js#26370]
### Description

Something that I've encountered when messing with `Color` object. Maybe this is intentional? But in that case I'd expect it to be properly documented, currently documentation says all those methods use same color space.

Looking at the code, `.setRGB` and `.setStyle` have default `colorSpace` value `colorSpace = SRGBColorSpace`, but `.setHex` and `.setHSL` have default value `colorSpace = ColorManagement.workingColorSpace` which defaults to `LinearSRGBColorSpace`

This leads to different colors being defined when calling `setRGB` and `setHex` with seemingly same values.

### Reproduction steps

1. Create a colour with `new Color(1, 0.20784, 0.20784)` and `new Color(0xff3535)`
2. Call `getHexString()` on both, get different result

### Code

```js
const color1 = new Color(1, 0.20784, 0.20784)  // 0xff3535 converted to RGB
const color2 = new Color(0xff3535)

console.log(color1.getHexString())  // ff7e7e
console.log(color2.getHexString())  // ff3535
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/a1f72kzs/)
* [jsfiddle-dev](https://jsfiddle.net/35hujow7/)

### Version

r154

### Device

Desktop, Mobile, Headset

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows, MacOS, Linux, Android, iOS

**Comment by gkjohnson** [comment]
> Maybe this is intentional?

It's a deliberate decision for hex colors to be interpreted as sRGB.

> currently documentation says all those methods use same color space.

Where in the documentation? Looking at the docs for `setHex`, `setStyle`, `setHSL`, and `setRGB` on the [Color](https://threejs.org/docs/index.html?q=color#api/en/math/Color) docs page it looks like all the defaults are declared appropriately.

**Comment by SkaceKamen** [comment]
Well I'll be damned, I must've looked at the documentation incorrectly, I though I saw all the default values being `SRGBColorSpace` but looking now I see that's it's properly documented. I'd say this may warrant a bigger warning than default value of argument being different since I wouldn't expect this behaviour to be different, but as you say, it's documented indeed. Sorry for bothering.

**Comment by gkjohnson** [comment]
>  I'd say this may warrant a bigger warning than default value of argument being different since I wouldn't expect this behaviour to be different (especially since it's not documented in the constructor, which is something I was using)

If you'd like to improve the documentation for the constructor feel free to make a PR!

**Comment by SkaceKamen** [comment]
I'll try to think a way to convey this without breaking the "minimalism" of the current documentation, but it'll be hard :D
