### ISSUE TITLE
Raycaster with `.set(origin, direction)`

### ISSUE THREAD

**Issue by romgrk** [mrdoob/three.js#26385]
### Description

I'm trying to raycast from one object to another, the goal is to implement enemy vision. Raycaster works well when used with `.setFromCamera(...)`, for which I've found good documentation and numerous examples. However, I'm unable to make it work with `raycaster.set(...)`. When I do, I get strange results, such as all the objects being returned, or no results returned at all.

### Reproduction steps

1. Add 2 balls, teal and yellow
2. Create a raycaster that passes through the teal ball
3. call `.intersectsObjects([teal, yellow])`

Both teal and yellow are returned, even if the ray is only passing through teal.

### Live example

https://jsfiddle.net/x39v1ktm/3/

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/1423607/ffae7812-d22c-4179-bb17-28f945b890f7)
![image](https://github.com/mrdoob/three.js/assets/1423607/1b571643-aac3-43ed-8307-333a92d8f927)

### Version

latest

**Comment by Mugen87** [comment]
The world matrices of your meshes were outdated: https://jsfiddle.net/x4kaLor0/

Please use the [forum](https://discourse.threejs.org/) or stackoverflow if you need more help.
