### ISSUE TITLE
Idea: use Nlp instead of coding to create visuals

### ISSUE THREAD

**Issue by imvetri** [mrdoob/three.js#26384]
### Description

Current technique of creating visuals require us to know syntaxes to code. Since the modern computing move towards ai ml as human computer interface, let's try text to visuals using nlp layer in-between us and the three js 

### Solution

Pipeline setup
1. Some nlp in js that can run in client side
2. User puts what he/she/it visualises.
3. Transforms turn it to three js code

### Alternatives

Alternative is to write imaginations and idea as text or comics.

**Comment by mrdoob** [comment]
wotsa nlp lyr?

**Comment by imvetri** [comment]
Natural language processing.


For example, let below be my instructions.
1. I see a white 3d space - creates a 3d scene in white
2. I see a moving object - creates a moving object
3. I'm visualizing a constantly shape shifting  object that adheres to below rules.
Etc etc

**Comment by mrdoob** [comment]
I think that should be a different project, which could use three.js for rendering.
