### ISSUE TITLE
Raycaster doesn't intersect Mesh using 2D (Circle, Plane) geometries

### ISSUE THREAD

**Issue by stacker60** [mrdoob/three.js#26396]
### Description

Raycaster can't intersect with Mesh that uses CircleGeometry. In Mesh, the intersection is detected with boundingSphere, but fails the test with boundingBox. Possibly because boundingBox.min.z and boundingBox.max.z are both 0?

### Reproduction steps

1. Create a Mesh using a "2D" geometry like CircleGeometry.
2. Cast a ray to the Mesh.
3. Raycaster finds 0 intersections.

### Code

        import {
          CircleGeometry,
          Mesh,
          MeshBasicMaterial,
          Raycaster,
          Scene,
          Vector3
        } from "https://cdnjs.cloudflare.com/ajax/libs/three.js/0.154.0/three.module.js";

        const scene = new Scene();
        const circleMatl = new MeshBasicMaterial({
          color: 0x0e0eff
        });
        const circleGeom = new CircleGeometry(0.5, 32);

        const mesh = new Mesh(circleGeom, circleMatl);
        mesh.scale.set(5, 5, 0);
        mesh.position.set(10, 10, 10);
        mesh.updateMatrix();

        scene.add(mesh);
        scene.updateWorldMatrix(false, true);

        const rayPos = new Vector3(8, 8, 100);
        const rayDir = new Vector3(0, 0, -1);
        const raycaster = new Raycaster();
        raycaster.set(rayPos, rayDir);

        const hits = [];

        raycaster.intersectObject(scene, true, hits);
        console.log(hits.length > 0 ? 'Hit' : 'Miss');
    </script>

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)
https://jsfiddle.net/stacker60/r2vow641/5/

### Version

r154

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

**Comment by stacker60** [comment]
How is this a help request? The example code is a very specific example of the library not doing what is expected. Is the documentation wrong or incomplete?

**Comment by WestLangley** [comment]
@stacker60

1. The ray in your example bypasses the circle mesh -- it does not hit it.
2. You are setting a `scale` component to zero which results in a non-invertible transform matrix.

@Mugen87 This is the same issue as discussed in https://github.com/mrdoob/three.js/issues/17926#issuecomment-554135342.

**Comment by stacker60** [comment]
@WestLangley thank you for your response. I do think there could be a more user friendly resolution to #17926.

**Comment by Mugen87** [comment]
My personal preference would be to disallow non-uniform scale in principle. It's too late to make `Object3D.scale` to a scalar value but we could at least explicitly state a policy in the documentation. This would solve a series of issues with other methods.
