### ISSUE TITLE
Why are the world coordinates and local coordinates of the box created from the vertex the same and both at the origin

### ISSUE THREAD

**Issue by letmestady** [mrdoob/three.js#26407]
### Description

Why are the world coordinates and local coordinates of the box created from the vertex the same and both at the origin

### Reproduction steps

1.Create geometry vertices
2.Create geometry and textures
3.Update geometry adds to the scene and prints local and world coordinates

### Code

let arr = [
    2, 2, 2, // 0
    4, 2, 2,  // 1
    4, 4, 2,   // 2
    2, 4, 2,  // 3

    2, 2, 1, // 0
    4, 2, 1,  // 1
    4, 4, 1,   // 2d
    2, 4, 1,  // 3
]
let aa: Array<number> = [
    arr[15], arr[16], arr[17],
    arr[3], arr[4], arr[5],
    arr[18], arr[19], arr[20],
    arr[6], arr[7], arr[8],

    arr[0], arr[1], arr[2],
    arr[12], arr[13], arr[14],
    arr[9], arr[10], arr[11],
    arr[21], arr[22], arr[23],

    arr[0], arr[1], arr[2],
    arr[3], arr[4], arr[5],
    arr[12], arr[13], arr[14],
    arr[15], arr[16], arr[17],

    arr[21], arr[22], arr[23],
    arr[18], arr[19], arr[20],
    arr[9], arr[10], arr[11],
    arr[6], arr[7], arr[8],

    arr[12], arr[13], arr[14],
    arr[15], arr[16], arr[17],
    arr[21], arr[22], arr[23],
    arr[18], arr[19], arr[20],

    arr[3], arr[4], arr[5],
    arr[0], arr[1], arr[2],
    arr[6], arr[7], arr[8],
    arr[9], arr[10], arr[11]
]

const material = new THREE.MeshBasicMaterial({ color: 0x00ff00 });
const cube = new THREE.Mesh(new THREE.BoxGeometry(), material);
// 将顶点坐标添加到BufferGeometry对象中
const brush_vertices_buffer = new Float32Array(aa);
cube.geometry.setAttribute('position', new THREE.BufferAttribute(brush_vertices_buffer, 3));
cube.geometry.attributes.position.needsUpdate = true;
cube.geometry.computeVertexNormals();
cube.geometry.computeBoundingSphere();
cube.geometry.computeBoundingBox();
cube.updateWorldMatrix(true, false);
cube.updateMatrix();
rjh_model.scene.add(cube);

let worldPosition = new Vector3();
cube.getWorldPosition(worldPosition)
console.log("position", cube.position);
console.log("worldPosition", worldPosition);

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)
无

### Screenshots

<img width="249" alt="ed9f9ffa64ba6a6070ecc705baa326c" src="https://github.com/mrdoob/three.js/assets/116178387/7be7daf5-86c0-443d-b2a3-1e1cdc58ea11">

### Version

^0.149.0

### Device

Desktop

### Browser

Chrome, Edge

### OS

Windows

**Comment by donmccurdy** [comment]
Please use one of the links below for help requests. We reserve github issues for development-related discussions.

- [questions](https://stackoverflow.com/questions/tagged/three.js)
- [discord](https://discord.gg/56GBJwAnUS)
- [forum](https://discourse.threejs.org/)
