### ISSUE TITLE
editor fails to load meshopt gltf

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#26413]
### Description

It throws this to the console:
```
Uncaught (in promise) Error: THREE.GLTFLoader: setMeshoptDecoder must be called before loading compressed files
```

How come it is not supported 😩

### Reproduction steps

import meshopt gltf

### Code

```js

					const { DRACOLoader } = await import( 'three/addons/loaders/DRACOLoader.js' );
					const { GLTFLoader } = await import( 'three/addons/loaders/GLTFLoader.js' );

					const dracoLoader = new DRACOLoader();
					dracoLoader.setDecoderPath( '../examples/jsm/libs/draco/gltf/' );

					const loader = new GLTFLoader( manager );
					loader.setDRACOLoader( dracoLoader );

					loader.parse( contents, '', function ( result ) {
```

### Live example

https://threejs.org/editor

### Version

r154

### Device

Desktop

### Browser

Firefox

### OS

Windows

**Comment by Mugen87** [comment]
Such compressed files are often produced via `gltfpack` which also compressed textures via KTX2. However, compressed textures can't be serialized/deserialized yet (see #22035). I guess this was the major reason why meshopt wasn't included so far.

When you can share a compressed asset without textures we can try to add `meshopt` support to the editor.

**Comment by makc** [comment]
@Mugen87 
> we can try to add `meshopt` support to the editor

I mean, since you have it working with glb, textures do not seem to be the problem?

> When you can share a compressed asset without textures

That's like 1 minute of effort, I can do that much, lol. Here goes default blender cube:
[blendercube-v1.zip](https://github.com/mrdoob/three.js/files/12026151/blendercube-v1.zip)

**Comment by Mugen87** [comment]
> I mean, since you have it working with glb, textures do not seem to be the problem?

Do you mind elaborating?

**Comment by Mugen87** [comment]
Ah wait, I see now. `MeshoptDecoder` is already in place for glbs but not for gltf files.
