### ISSUE TITLE
TubeBufferGeometry Missing in v154

### ISSUE THREAD

**Issue by amcdnl** [mrdoob/three.js#26415]
### Description

The `TubeBufferGeometry`, `RingBufferGeometry` and `SphereBufferGeometry` are no longer present in v154. I was using v143 previously and all was there. I couldn't find any docs related to the change and how to migrate?

### Reproduction steps

1. Install v154 on a project that had v143 that uses TubeBufferGeometry
2. Compile
3. Note Error

### Code

N/A

### Live example

N/A

### Version

154

**Comment by Mugen87** [comment]
These aliases have been removed since they were deprecated in `r144`, see #24352.

After ten releases deprecated code is removed from the project.

**Comment by amcdnl** [comment]
@Mugen87 - Thanks for the link!

**Comment by JohnBaozi** [comment]
@Mugen87 Excuse me sir, I am confused after updating the threejs v154,and the last version I have used is v126. How to transfer sphereGeometry into sphereBufferGeometry or something else in the latest version?

**Comment by Mugen87** [comment]
You should information about this topic here: https://discourse.threejs.org/t/three-geometry-will-be-removed-from-core-with-r125/22401

**Comment by JohnBaozi** [comment]
，你发的邮件已经收到，我会尽快回复。

**Comment by JohnBaozi** [comment]
> You should information about this topic here: https://discourse.threejs.org/t/three-geometry-will-be-removed-from-core-with-r125/22401

Thanks for your replying sir, it helps me alot !
