### ISSUE TITLE
Models loaded in Three.js 155dev are dark

### ISSUE THREAD

**Issue by andreasrosdal** [mrdoob/three.js#26410]
### Description

The models loaded in Three.js 155dev are dark. They are loaded using the GLTFLoader.
Using Three.js r154 the models had correctly lighting. 

Is there some API change in this build that I need to update the code using Three.js?

### Reproduction steps

1. Build Fciv.net using Three.js 155dev.
2. Start a new game.
3. Observe darkness.

### Code

https://github.com/fciv-net/fciv-net

### Live example

https://github.com/fciv-net/fciv-net

### Screenshots

![Screenshot_20230711_182704](https://github.com/mrdoob/three.js/assets/41650711/2a6d5e24-f4c5-4071-b519-88134cee390e)

### Version

r155dev

**Comment by Mugen87** [comment]
Can you please verify if you are affected by #26392?

More detail explanation: https://discourse.threejs.org/t/updates-to-lighting-in-three-js-r155/53733

**Comment by andreasrosdal** [comment]
Yes, I am affected by [#26392](https://github.com/mrdoob/three.js/pull/26392)

Further, I am using 
>  THREE.ColorManagement.enabled = false;

here: https://github.com/fciv-net/fciv-net/blob/main/freeciv-web/src/main/webapp/javascript/webgl/mapview.js#L69
in order to opt-out of using the new colour model in r152 (described in #25917 where the objects were too bright).

I am interested in doing the correct migrations in order to use Three.js correctly and get as good colours as possible.

Further, I hope to be a good early adopter and tester of new features in Three.js.

**Comment by Mugen87** [comment]
In this case please use the forum if you encounter issues with color management or lighting. There are dedicated topics for both changes. Please files only issues at GitHub if you encounter bugs or have feature requests.
