### ISSUE TITLE
Creash when empty BufferGeometry rendered with wireframe

### ISSUE THREAD

**Issue by wmww** [mrdoob/three.js#26464]
### Description

I'm getting a `geometryPosition is undefined` error thrown when I render a scene that includes an object with an empty geometry and a wireframe material.

I realize it's a bit strange to add a mesh with a material but no geometry to the scene, I was doing it because the geometry I set was dependent on something that hadn't loaded yet.

### Reproduction steps

1. Create a mesh with an empty `BufferGeometry` and a wireframe material (either create a new `BufferGeometry` like in my examples, or create a new `Mesh` instance without any arguments and then set the material)
2. Make sure it's within the camera view
3. Render, and an error is thrown

### Code

```js
const mesh = new THREE.Mesh(
	new THREE.BufferGeometry(),
  new THREE.MeshBasicMaterial({ wireframe: true})
);
scene.add(mesh);
renderer.render(scene, camera);
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/q0gyaurf/3/)
* [jsfiddle-dev](https://jsfiddle.net/4wznscyj/10/)

### Version

154

### Device

Desktop

### Browser

Chrome, Firefox

### OS

Linux

**Comment by Mugen87** [comment]
Since rendering a  geometry without vertex data is gracefully handled, we should ensure the same for this use case. I'll file a PR with a possible fix.
