### ISSUE TITLE
The WebGPURenderer causes the browser to crash while loading the glb model

### ISSUE THREAD

**Issue by mlt131220** [mrdoob/three.js#26469]
### Description

I found that when I used WebGPURenderer to load the glb model, the browser would crash. Under webgl is normal!
I made a simple example,see: [web-gpu3d-preview](https://gitee.com/mlt131220/web-gpu3d-preview)

### Reproduction steps

1. init WebGPURenderer
2. GlTFLoader.load("XXXX.glb")
3. WebGPURenderer.render()

### Code

```js
// code goes here
```

### Live example

[web-gpu3d-preview](https://gitee.com/mlt131220/web-gpu3d-preview)

### Version

r154

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Do you mind sharing your code at GitHub? The zip download at gitee only works with an account and the clone via git takes ages because of a low downloading speed.

**Comment by mlt131220** [comment]
> Do you mind sharing your code at GitHub? The zip download at gitee only works with an account and the clone via git takes ages because of a low downloading speed.

I've shared it on GitHub,see:[WebGPU3dPreview](https://github.com/mlt131220/WebGPU3dPreview)

**Comment by Mugen87** [comment]
Your model has 80.000.000 faces and produces 16000 draw calls. I'm not surprise that this model crashes the renderer.
 I'm sure the WebGL version will also crash on low and mid end devices. 

I suggest you simplify the model and try again.

**Comment by mlt131220** [comment]
> Your model has 80.000.000 faces and produces 16000 draw calls. I'm not surprise that this model crashes the renderer. I'm sure the WebGL version will also crash on low and mid end devices.
> 
> I suggest you simplify the model and try again.

The same model is not stuck on the WebGL version, at 60ms at frame time, but crashes when opened with WebGPU and called render() method.  I looked on the console and found that the render function keeps executing when I'm not rendering, which I'm sure I didn't call.

**Comment by Mugen87** [comment]
Do you mind reproducing the issue with a smaller asset?

**Comment by mrdoob** [comment]
> The same model is not stuck on the WebGL version, at 60ms at frame time

What GPU is that with?

**Comment by mlt131220** [comment]
> > The same model is not stuck on the WebGL version, at 60ms at frame time
> 
> What GPU is that with?

3070TI

**Comment by mlt131220** [comment]
> Do you mind reproducing the issue with a smaller asset?

Performs well in BabylonJS WebGPU and THREEJS WebGL

**Comment by mrdoob** [comment]
@sunag any ideas?

**Comment by sunag** [comment]
@mrdoob I'll be checking this out, @Mugen87 I will reopen until I'm more satisfied with the optimization results I'm working on, this PR could be a good benchmark.

**Comment by sunag** [comment]
@mlt131220 Could you test again?

**Comment by mlt131220** [comment]
> @mlt131220 Could you test again?

There hasn't been any improvement. When my scene is large, using WebGL may seem sluggish, but when I switch to WebGPU, the entire browser window freezes and cannot be closed. Even after waiting for a while, the browser cannot close!

**Comment by mlt131220** [comment]
> @mlt131220 Could you test again?

In my case of GITHUB, we can see that the use of WebGL is very smooth and the mapping is normal. After switching to WebGPU, Catton can not rotate and the map is lost! In the larger scene in my project, the browser faked death directly, and the browser can only be closed from the Task Manager!

**Comment by sunag** [comment]
I found the main problem, it is still related to the `NodeBuilder` cache, the optimization will have to be done using `customProgramCacheKey()` with some improvements too. Currently, if we create 3 x `MeshStandardMaterial` with identical settings it runs `NodeBuilder` 3 times, this can be a problem with scenes like this where there are a huge number of materials with the same type just with different colors. I will be working on this improvement, to keep the high customization of materials in line with this optimization.

**Comment by mlt131220** [comment]
> I found the main problem, it is still related to the `NodeBuilder` cache, the optimization will have to be done using `customProgramCacheKey()` with some improvements too. Currently, if we create 3 x `MeshStandardMaterial` with identical settings it runs `NodeBuilder` 3 times, this can be a problem with scenes like this where there are a huge number of materials with the same type just with different colors. I will be working on this improvement, to keep the high customization of materials in line with this optimization.

Thank you for your reply.
I'll run the local test again after you fix it.
In the current version of R155, I used ten different types of larger scenario tests, all of which had poor performance and were far from webgl.

**Comment by mlt131220** [comment]
> I found the main problem, it is still related to the `NodeBuilder` cache, the optimization will have to be done using `customProgramCacheKey()` with some improvements too. Currently, if we create 3 x `MeshStandardMaterial` with identical settings it runs `NodeBuilder` 3 times, this can be a problem with scenes like this where there are a huge number of materials with the same type just with different colors. I will be working on this improvement, to keep the high customization of materials in line with this optimization.

Is there any new progress

**Comment by sunag** [comment]
> Is there any new progress

This improvement is being discussed [here ](https://github.com/mrdoob/three.js/issues/26673) with others related.

**Comment by mlt131220** [comment]
> > Is there any new progress
> 
> This improvement is being discussed [here ](https://github.com/mrdoob/three.js/issues/26673) with others related.

OK

**Comment by Mugen87** [comment]
Merging this issue into #26673.
