### ISSUE TITLE
lightMap not working with the second UV.  it seems use the first uv.

### ISSUE THREAD

**Issue by TomDDH** [mrdoob/three.js#26474]
### Description

after "three": "^0.151.0",
the lightmap not looking correct. it seems using the first UV.  
I do have two different UV. and it was working correct on other three js version.

### Reproduction steps

1. intall "three": "^0.151.0",
2. loading lightmap texture :
                const lightTexture = textureLoader.load('./assets/images/lightmap.png');
                lightTexture.flipY = false
3. apply lighttexture to material.lightMap attribute:
object.material.lightMap = lightTexture

### Code

```js
// code goes here
```

### Live example

<img width="429" alt="image" src="https://github.com/mrdoob/three.js/assets/69221143/ca2b970f-4b1b-42c9-961a-8b506dc5b80d">

### Screenshots

<img width="429" alt="image" src="https://github.com/mrdoob/three.js/assets/69221143/ca2b970f-4b1b-42c9-961a-8b506dc5b80d">

### Version

r150

### Device

Desktop

### Browser

Chrome

### OS

Windows, MacOS

**Comment by donmccurdy** [comment]
@TomDDH in newer versions of three.js, you can configure which UV channel any particular texture will use. For example:

```js
texture.channel = 0 | 1 | 2 | 3;
```

The default for any newly-created texture is now 0.

**Comment by TomDDH** [comment]
This is really Cool, thanks very much
