### ISSUE TITLE
GLTFExporter: Support clearcoatNormalMap => Scale 

### ISSUE THREAD

**Issue by Yason83** [mrdoob/three.js#26473]
### Description

GLTFExporter.js does not have the capability to export the "Scale" parameter data from the clearcoatNormalMap texture.
Line 2564:
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/exporters/GLTFExporter.js#L2564
`if ( material.clearcoatNormalMap ) {

    const clearcoatNormalMapDef = {
        index: writer.processTexture( material.clearcoatNormalMap ),
        texCoord: material.clearcoatNormalMap.channel
    };
    writer.applyTextureTransform( clearcoatNormalMapDef, material.clearcoatNormalMap );
    extensionDef.clearcoatNormalTexture = clearcoatNormalMapDef;

}`
However, this parameter is successfully read by GLTFLoader.js.
Line 794:
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js#L794C12-L794C12
`if ( extension.clearcoatNormalTexture !== undefined ) {

    pending.push( parser.assignTexture( materialParams, 'clearcoatNormalMap', extension.clearcoatNormalTexture ) );

    if ( extension.clearcoatNormalTexture.scale !== undefined ) {

        const scale = extension.clearcoatNormalTexture.scale;

        materialParams.clearcoatNormalScale = new Vector2( scale, scale );

    }

}`

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [GLTFExporter.js](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/exporters/GLTFExporter.js#L2564)
* [GLTFLoader.js](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js#L794C12-L794C12)

### Version

last

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by donmccurdy** [comment]
It appears that this feature is not implemented in the exporter yet. A PR would be welcome!

**Comment by Yason83** [comment]
> It appears that this feature is not implemented in the exporter yet. A PR would be welcome!

Thank you for the information. I would like to clarify that I am not a developer, but rather a tester for the existing software.

**Comment by 4mishra** [comment]
so, if I'm not wrong! Instead of making any changes to the base layer, the clearcoat attribute will add an additional layer on top of the material base. Clearcoat can have its own properties separate from the base material, in particular, you can assign the clearcoat a roughness value and even define its own normal mapping system.

**Comment by donmccurdy** [comment]
@4mishra that's correct, yes.
