### ISSUE TITLE
OrbitControls are framerate dependent

### ISSUE THREAD

**Issue by Issung** [mrdoob/three.js#26471]
### Description

The OrbitControl provided with three.js is framerate dependent.
Running at 30fps will spin half as fast at 60fps for example. 
This can be accounted for by taking into account the time between frames.

### Reproduction steps

1. Make a default scene with OrbitControls and autoRotate.
2. Limit the FPS to different amounts and observe the rotation effect.

### Code

```js
// code goes here
```

### Live example

[jsfiddle](https://jsfiddle.net/issung/wzjqn9r7/16/)

### Version

latest

### Device

Desktop, Mobile, Headset

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows, MacOS, Linux, Android, iOS

**Comment by Issung** [comment]
I have some experience with issues like this, I will submit a PR for discussion.

**Comment by Mugen87** [comment]
A PR would be great! When I remember correctly this feature was requested in the past although I don't find the discussion right now.

**Comment by Issung** [comment]
I had a search but couldn't find anything. Didn't want to do some work that had already been done 😅

**Comment by Mugen87** [comment]
Another user stumbled across this issue:

https://discourse.threejs.org/t/speed-of-orbitcontrols-autorotate-not-related-to-fps/43910

This was actually the discussion in the forum I was looking for.
