### ISSUE TITLE
when i set model position far away from 0,0,0, such as new Vector3( 13487527.049811473, 3.0885315154125355,  -3741641.995818826), shadow has bug

### ISSUE THREAD

**Issue by liuyehua** [mrdoob/three.js#26487]
### Description

when i set model position far away from 0,0,0, such as new Vector3( 13487527.049811473, 3.0885315154125355,  -3741641.995818826), Shadow distortioned, i know its caused by float32 , how can i fixed it ....

<img width="983" alt="image" src="https://github.com/mrdoob/three.js/assets/27567569/9256b702-d1c0-49f9-8040-b065ee0d6ceb">

### Reproduction steps

1

### Code

1

### Live example

1

### Version

154

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by mrdoob** [comment]
Please use one of the links below for help / support:

- [questions](https://stackoverflow.com/questions/tagged/three.js)
- [discord](https://discord.gg/56GBJwAnUS)
- [forum](https://discourse.threejs.org)
