### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'matrixWorld')

### ISSUE THREAD

**Issue by akbarjanosman** [mrdoob/three.js#26488]
### Description

three.module.js:31580 Uncaught TypeError: Cannot read properties of undefined (reading 'matrixWorld')
    at SkinnedMesh.applyBoneTransform (three.module.js:31580:1)
    at SkinnedMesh.computeBoundingSphere (three.module.js:31418:1)
    at projectObject (three.module.js:29113:1)
    at projectObject (three.module.js:29162:1)
    at projectObject (three.module.js:29162:1)
    at WebGLRenderer.render (three.module.js:28939:1)
    at RenderPass.render (RenderPass.js:61:1)
    at EffectComposer.render (EffectComposer.js:124:1)

### Reproduction steps

1.
2.
3.

### Code

```js
applyBoneTransform( index, vector ) {

		const skeleton = this.skeleton;
		const geometry = this.geometry;

		_skinIndex.fromBufferAttribute( geometry.attributes.skinIndex, index );
		_skinWeight.fromBufferAttribute( geometry.attributes.skinWeight, index );

		_basePosition.copy( vector ).applyMatrix4( this.bindMatrix );

		vector.set( 0, 0, 0 );

		for ( let i = 0; i < 4; i ++ ) {

			const weight = _skinWeight.getComponent( i );

			if ( weight !== 0 ) {

				const boneIndex = _skinIndex.getComponent( i );

				_matrix4.multiplyMatrices( skeleton.bones[ boneIndex ].matrixWorld, skeleton.boneInverses[ boneIndex ] );

				vector.addScaledVector( _vector3.copy( _basePosition ).applyMatrix4( _matrix4 ), weight );

			}

		}

		return vector.applyMatrix4( this.bindMatrixInverse );

	}
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

153

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by mrdoob** [comment]
Please use one of the links below for help / support:

- [questions](https://stackoverflow.com/questions/tagged/three.js)
- [discord](https://discord.gg/56GBJwAnUS)
- [forum](https://discourse.threejs.org)

**Comment by akbarjanosman** [comment]
![image](https://github.com/mrdoob/three.js/assets/17883846/55eb1d6a-33ec-4b8d-8809-7da0529d5377)

i think its just a bug as the above picture shows.

> Please use one of the links below for help / support:
> 
> * [questions](https://stackoverflow.com/questions/tagged/three.js)
> * [discord](https://discord.gg/56GBJwAnUS)
> * [forum](https://discourse.threejs.org)
