### ISSUE TITLE
Memory leak: cannot dispose of a hidden texture

### ISSUE THREAD

**Issue by deenns** [mrdoob/three.js#26484]
### Description

It seems that there is some hidden texture created for certain kind of transparent objects. This texture isn't connected to a scene and cannot be disposed of properly. 

It should be either fixed or the docs should be updated with an instruction how to dispose of such textures.

### Reproduction steps

1. Open [this live example](https://jsfiddle.net/jsdxx/kcLt2q5b/)
2. If you upload a new file or click on the "Dispose" button, the whole scene will be disposed (see the `disposeScene` function).
3. There are no warnings for many models, but certain kind of models cause a warning. 
4. Download [the dragon model](https://www.dropbox.com/scl/fi/5acc5x1ti8ghx6tozxkqw/dragon.glb?rlkey=w56umwqfbja4ppcr6teb5ssi5&dl=0).
5. Open it in the live example above.
6. Click the `Dispose` button, and you will see a warning in the console, because `renderer.info.memory.textures` isn't `0`.

### Version

r154

### Additional info

Also, I tried to update the `Texture` constructor and save all the textures to the a global variable (e.g. `textures.add(this)`). Then I disposed all the textures using that global registry, when the viewer is stopped. However, it didn't help - this global hack could replace the texture disposal logic in the `disposeScene` function, but it didn't affect the hidden texture. So I suspect it's some inner entity created by the renderer for transparent objects.

**Comment by deenns** [comment]
This is at least confusing. Because of this behavior, `renderer.info.memory` cannot be used to check that all resources are properly disposed - sometimes the hidden texture is created, sometimes not - it depends on a model. 

It would be ok, if it were disposed when `renderer.dispose()` is called, but it's not so. And in case of an SPA with a model viewer on a certain page, we need to completely dispose of all Three.js resources, once that page is closed. And once it's opened again, everything will be created from scratch (the old renderer will not be reused).

**Comment by Mugen87** [comment]
> I thought that ([docs](https://threejs.org/docs/?q=dispos#manual/en/introduction/How-to-dispose-of-objects))

Calling `WebGLRenderer.dispose()` is indeed intended for the use case that the renderer isn't used anymore. Using it after the call of `dispose()` is invalid.

The renderer can create internal resources for certain operations and this can be visible in the `renderer.info` object. As long as these objects are not counting up and allocating more and more memory, this is not considered as a memory leak.

**Comment by Mugen87** [comment]
There is of course the option to "hide" internal resources in `renderer.info`. However, this creates confusion for all devs who track WebGL resources with external tools (which ends up in mismatches with what three.js reports).

**Comment by deenns** [comment]
> However, this creates confusion for all devs who track WebGL resources with external tools (which ends up in mismatches with what three.js reports).

It creates confusion now as well. Isn't it possible to just decrement it properly when the resource is released?

>Calling WebGLRenderer.dispose() is indeed intended for the use case that the renderer isn't used anymore

It works well for me. What are the pitfalls? Actually, it would be rather convenient if you make it a standard, so that all Three.js object behave the same way. If it's not possible, then, of course, it should be mentioned explicitly on the docs page as an exception.

**Comment by Mugen87** [comment]
> It works well for me. What are the pitfalls? 

Certain WebGL context and WebXR event listener are removed and not added again when you continuing using the renderer. These listeners are added only once during the construction time.

If it works you, that's fine. However, keep in mind the usage is not officially supported.
