### ISSUE TITLE
Browser crashes when loading large files (dxf, glTF, etc.)

### ISSUE THREAD

**Issue by yanzexuan1** [mrdoob/three.js#26496]
### Description

We are using three.js to load 2d/3d models in BIM domain, like dxf (converted from dwg), glTF/glb, etc. When there are too many entities, browser crashes. Of course, it depends on what devices/gpus we are using. 

Now I'm thinking to reduce the memory three.js uses, for one of my dxf file (1M+ entities, drawcall 20000+), log shows:
- totalJSHeapSize: 1630.15M 
- usedJSHeapSize: 1564.05M
We already merged entities together for the same type and material. Since we don't use objects'/materials' uuid at all, can I simply don't generate UUID for them? As I tried, everything works fine. Do you know any side effect? And please let me know if there is other ideas. Thanks!
Our [example ](https://pattern-x.github.io/gemini-viewer-examples/) and [sample code repo](https://github.com/pattern-x/gemini-viewer-examples): 

### Reproduction steps

1. Open [online sample page](https://pattern-x.github.io/gemini-viewer-examples/#/Upload_your_local_dxf)
2. Upload a dxf file ([this one](https://github.com/pattern-x/gemini-viewer-examples/blob/main/public/demo/models/dxf/building_1_2.dxf) is sort of large, but there are others much larger)
3. 
It is more likely to happen on mobile devices. 

### Code

```js
// code goes here
```

### Live example

* [one of the online example](https://pattern-x.github.io/gemini-viewer-examples/#/Building_1&2)

### Version

r154

### Device

Desktop, Mobile

### OS

Windows, MacOS, Linux

**Comment by Mugen87** [comment]
Please ask for help at the [forum](https://discourse.threejs.org/).

**Comment by yanzexuan1** [comment]
np, thanks!
