### ISSUE TITLE
Renderpass with special material?

### ISSUE THREAD

**Issue by andsve** [mrdoob/three.js#265]
Is it possible to render a scene with a specific material/shader, without modifying the scene itself?
I have peeked into the source a bit, and realize that it could possibly be solved by modifying/creating a new custom render method for the WebGLRenderer, but this feels a bit extreme.

Another option would be to create a separate scene with only one material, but using the same objects from the "original" scene? But I'm loading the scene with the SceneLoader, so I don't have "direct" access to the materials when they are added while the scene is loading.

Thank in advance!
Regards,
Sven

**Comment by looeee** [comment]
@mrdoob do you still intend to look into this further or is it resolved?

**Comment by mrdoob** [comment]
@looeee yeah, I still want to move this to the renderer, somehow...

**Comment by WestLangley** [comment]
This feature was implemented with `scene.overrideMaterial`.

In the interest in keeping the issues focused, we can open another issue if there is a desire to reimplement `scene.overrideMaterial` differently. I hope that is OK.
