### ISSUE TITLE
Merging editor and frame.js

### ISSUE THREAD

**Issue by freealise** [mrdoob/three.js#26501]
### Description

The editor currently only handles manual animation playback without support for sequence editing.

### Solution

Would it at some point be combined with [frame.js](https://github.com/mrdoob/frame.js) for that purpose?

### Alternatives

I've considered Clara.io, but had been very confused by the overly complex interface that looks like they've tried to include everything that's possible to do in Three.js (and it's not open-source so can't be used as a framework).

### Additional context

I'm attempting to make an interface for smooth voxel-based animation with skinned mesh and morphing.

**Comment by Mugen87** [comment]
The `three.js` editor is intended as a _scene editor_. In such an application, you normally don't have the opportunity to author animation data or vertex data in general. Such features are typical for a tool like Blender which is a content creation tool (so different type of application).

Given this argumentation, I think it's better to keep both projects separated.

**Comment by freealise** [comment]
I assumed that moving skeleton bones and setting keyframes could be classified as 'scene editing' and said nothing about vertices, so the distinction is not quite understandable. Anyway, it's not my property.

**Comment by Mugen87** [comment]
I want to make clear that the ultimate decision is up to @mrdoob. You can keep the issue open until he has responded.
