### ISSUE TITLE
wgslFn with textures does not work when addressed to the positionNode

### ISSUE THREAD

**Issue by Spiri0** [mrdoob/three.js#26507]
### Description

I have a simple wgslFn and a simple cube. If I address the wgslFn to a colorNode it works and the vertex positions are interpreted as color and you see the cube with the color gradients according to the vertex coordinates. If I now also want to add the wgslFn to the positionNode to scale the cube, there is an error message, the app no ​​longer works.

Error message:
Tint WGSL reader failure: :49:45 error: unresolved identifier 'nodeUniform0_sampler'
nodeVarying0 = WGSLPosition( nodeUniform0, nodeUniform0_sampler, NodeUniforms.nodeUniform1, position ).xyz;

But if you now delete the texture and the texture sampler from the wgslFn and the parameters, the positionNode also works.

That means if you only address the wgslFn to the colorNode with texture and texturesampler and it works, the wgslFn and the parameters must be correct and the positionNode does not accept any textures in a wgslFn.

My theory if I interpret the error message correctly:
If the wgslFn is addressed to the colorNode, it is interpreted as a kind of fragment shader and all parameters are then something like uniforms and therefore texture and texturesampler also work in connection with the colorNode.

If the wgslFn is now addressed to the positionNode, it is interpreted as a vertex shader and if I interpret the error message correctly, 3js then tries to send all parameters as varyings to the fragment shader as well. That would explain why it works without texture and texturesampler, because attributes are vectors and/or scalars and these can be varyings.
As far as I know, textures are always integrated directly into the fragmentShader or the vertexShader as uniforms and cannot be sent from the vertexShader to the fragmentShader as a varying variable.

However, the use of textures in the vertex shader or in connection with the positionNode is essential for me, since with data textures I have all vertex coordinates available in the vertex shader in glsl in order to be able to calculate connection conditions correctly. When I tried to replicate my glsl app in webgpu, I was confronted with this problem.

I built this particularly simple example in CodePen to make the error easy to understand without unnecessary code ballast.

### Reproduction steps

1. Visit my codePen example. The WGSLPosition and wgslShaderParams work as seen with the colorNode.

2. Now include the positionNode and it won't work anymore. My expectation would be that i can see a 1.5 times larger cube
3. Now delete the displacementTexture and the displacementSampler from the WGSLPosition and the wgslShaderParams. Then the cube, which is 1.5 times larger, appears.

This means the positionNode does not accept textures in wgslFn. My suspicion is, as mentioned above, that 3js tries to make all parameters to varyings if a wgslFn is addressed to a positionNode, which doesn't work with textures.

To solve the problem, I imagine that if the positionNode recognizes textures in its parameters, it doesn't want to treat them as varyings, but as uniforms. That sounds like an easy thing to solve to me.

I hope I can help with this that it will be fixed as soon as possible.
The 3js team is doing a great job.

### Code

```
const textureLoader = new THREE.TextureLoader();
const vertexTexture = textureLoader.load( '../resources/textures/uv_grid_opengl.jpg' );				


const WGSLPosition = wgslFn(`
   fn WGSLPosition(
	displacementTexture: texture_2d<f32>,
	displacementSampler: sampler,		
	time: f32,
	position: vec3<f32>,
   ) -> vec4<f32> {

	return vec4<f32>(position *1.5, 1.0);						
   }
`);


this.wgslShaderParams = {
	displacementTexture: texture(vertexTexture),
	displacementSampler: texture(vertexTexture),
	time: uniform(0),
	position: attribute('position'),
}

//If i include the positionNode line then it crash
const material = new MeshBasicNodeMaterial();
material.colorNode = WGSLPosition(this.wgslShaderParams);
//material.positionNode = WGSLPosition(this.wgslShaderParams);



const geometry = new THREE.BoxGeometry();
this.cube = new THREE.Mesh(geometry, material);
this.scene_.add(this.cube);
```

### Live example

https://codepen.io/Spiri0/pen/vYQzMpL

### Version

r155

### Device

Mobile

### Browser

Chrome

### OS

Android

**Comment by sunag** [comment]
Hi @Spiri0.

I don't think `sampler` is compatible with `Vertex Stage`, you will probably have to use `textureLoad` without `sampler` parameter to work with texture on `Vertex Stage`.

**Comment by Spiri0** [comment]
I tried it like this now:

```
const textureLoader = new THREE.TextureLoader();
const vertexTexture = textureLoader.load( '../resources/textures/uv_grid_opengl.jpg' );				

		
const WGSLPosition = wgslFn(`
   fn WGSLPosition(
      displacementTexture: texture_2d<f32>,		
      time: f32,
      position: vec3<f32>,
   ) -> vec4<f32> {

      return vec4<f32>(position *2, 1.0);						
   }
`);
		

this.wgslShaderParams = {
   displacementTexture: texture(vertexTexture),	
   time: uniform(0),
   position: attribute('position'),
}

const material = new MeshBasicNodeMaterial();
material.colorNode = WGSLPosition(this.wgslShaderParams);
material.positionNode = WGSLPosition(this.wgslShaderParams);

const geometry = new THREE.BoxGeometry();
this.cube = new THREE.Mesh(geometry, material);
this.scene_.add(this.cube);
```

With Firefox nightly then takes a very long time before I see anything. With Chrome dev I never see anything. That doesn't seem right to me. Am I missing something?

**Comment by Spiri0** [comment]
Hm..., if I open my codePen example, it's quick. Local with vite is slowly or not at all possible. I'll test it with webpack too.

**Comment by Spiri0** [comment]
I did the whole setup with webpack instead of vite, because it is illogical that it runs in my browser with my modified codePen code, but not locally with vite as soon as I add the positionNode line. With webpack then the same phenomenon, with the positionNode it doesn't want to. So I set it up without a bundler because if the codePen code is running, the code is excluded as the cause. And behold, without vite or webpack, my codePen code runs on my local server. I find that very strange and a bit disturbing. How can the line of code: 

material.positionNode = WGSLPosition(this.wgslShaderParams); 

have an influence on the way how vite or webpack works? That took me a lot of time to analyse, but at least I can rule out a few things.
In any case, 3js has no problems with my codePen code. But something related to "material.positionNode = WGSLPosition(this.wgslShaderParams);" interferes with vite and webpack and I find that disturbing. 

Unfortunately I don't see a console on my tablet and I don't have a webgpu compatible browser on ubuntu. But I'll keep an eye on it. Maybe I can ask phil to start it on windows with the webpack and vite config to catch an error message.

**Comment by Spiri0** [comment]
I think I've found the cause. I organized a computer with a windows system, because on windows chrome supports webgpu in the normal browser since v114. firefox nightly has very limited support for webgpu and chrome canary and chrome dev are also unstable.
I myself work a lot in android and ubuntu and there is no webgpu support in the normal chrome yet. That cost me a lot of time and nerves, but that didn't let me rest. Firefox nightly, chrome canary, chrome dev, ... should therefore be used with great caution. The normal chrome on Windows works without problems. So I will have to be patient until chrome and other browsers support webgpu on android and linux like in windows.
I hope I didn't generate too much effort with this. The point can be closed with the knowledge that the unstable dev browsers (firefox nightly, chrome dev, chrome canary, edge canary, egde dev) are unsuitable for development with webgpu.

**Comment by Spiri0** [comment]
I must correct myself. I have now ruled out the browsers as a source of error, but the original problem still exists.
@sunag: I didn't find textureLoad in wgsl. Apparently there is only one textureSample command and it requires a sampler to set the sample precision. In wgsl vertex shaders, according to what I've researched, this is done in the same way as in wgsl fragment shaders. So my initially described issue that the positionNode does not work with samplers would still be up to date.

**Comment by sunag** [comment]
> I didn't find textureLoad in wgsl. 

You can find here: https://www.w3.org/TR/WGSL/#textureload

> So my initially described issue that the positionNode does not work with samplers would still be up to date.

Sorry, but the error presented is a WGSL error, the same does not happen when used in `fragment stage`, the sampling should happen in the interpolation process, if you have a working example of this we can reopen the issue.
