### ISSUE TITLE
r152 > draco loader / draco decoder breaks builds on older devices

### ISSUE THREAD

**Issue by forerunrun** [mrdoob/three.js#26504]
### Description

I've recently noticed that using draco loader / draco decoder breaks three scenes on older devices, the device in question i'm using to test is an old iphone 6s, r148's draco decoder version works fine on this device but decoder versions above break the build resulting in a blank screen and no errors in the ios chrome console. I understand support for WebGL1 is deprecated from r153 and being removed with r163 but i'm unsure why this would be affecting the draco loader currently...

### Reproduction steps

1. upgrade a three environment that uses draco loader / draco decoder to any version from r152 and above.
2. try running the scene on older devices such as iPhone 6s in this case.

### Code

```js
// code goes here
```

### Live example

https://jsfiddle.net/forerun/eoz0upgh/

### Version

r152

### Device

Mobile

### Browser

Chrome

### OS

iOS

**Comment by Mugen87** [comment]
What is the exact three.js release when things start to break on your iOS device?  I'm asking since the last time the DRACO libs were updated was `r150`. 

Besides, do you see any errors in the browser console?

**Comment by forerunrun** [comment]
> What is the exact three.js release when things start to break on your iOS device? I'm asking since the last time the DRACO libs were updated was `r150`.
> 
> Besides, do you see any errors in the browser console?

I've tested on r148 which works, r152 upwards doesn't work and there's nothing relative logged in the console, I'll test r149, r150 and r151 now and let you know...

**Comment by forerunrun** [comment]
ok @Mugen87 i've just run some tests... 
r149 works as expected on the older iPhone 6s.
r150 is the earliest revision that breaks on the iPhone 6s when using the `DracoLoader`... 
There is nothing relative logged to the chrome ios console, infact it prevents the code from excecuting anything at all as if threeScene.js is simply not loaded eg. from within the file that loads `DracoLoader` and sets the decoder path - trying to run console.log('anything') even at the highest line after imports is not logged out...

using the `GLTFLoader`, `DracoLoader` and `DracoDecoder` from r148 and building the rest with r155 does work accordingly but feels like a bit of a hackaround...

I'm aware there's progress being made to phase out support for older devices and WebGL1 but wondering if the update to the `DracoLoader` / `DracoDecoder` in r150 was an intentional step towards this?

**Comment by Mugen87** [comment]
Not that I am aware of. At least in #25475 it's not possible to see if the new DRACO library files have issues with older devices. 

It's indeed strange that nothing is logged in the browser console. I don't have an older iOS device at hand so I can't investigate this issue in more detail right now.

**Comment by Mugen87** [comment]
I'm afraid it does not make sense for `three.js` to use an outdated DRACO version. If DRACO does not fix this issue on its side, apps have to apply some sort of fallback (e.g. using an older version of `DRACOLoader`/`three.js` or using uncompressed models for certain devices).

Since older iOS/macOS versions have (to some extend serious) issues with their WebGL implementation, it's probably better to focus on current gen operating systems like iOS 16 which already have a high adoption rate. It seems this is the kind of issue where the best solution is to ask users to upgrade their OS or even hardware.
