### ISSUE TITLE
fbxloader import one hundred zhao The model of lead to browser collapse

### ISSUE THREAD

**Issue by sisiAHAH** [mrdoob/three.js#26517]
### Description

fbxloader import one hundred zhao The model of lead to browser collapse

### Reproduction steps

1. 引入的时候页面会卡顿 模型只有100多兆 只有用fbx 的时候 引起浏览器崩溃
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

0.154.0

**Comment by Mugen87** [comment]
Please let you help at the [forum](https://discourse.threejs.org/) first.

Also don't forget to share the FBX asset and also write the entire text in English.
