### ISSUE TITLE
Cond node doesn't work with both ifNode and elseNode as color nodes

### ISSUE THREAD

**Issue by njarraud** [mrdoob/three.js#26512]
### Description

If both **ifNode** and **elseNode** are ColorNode, the shader doesn't compile and throw an error.
However if any of the **ifNode** or **elseNode** is something else e.g. float or texture, it will work.

Edit: 2 x floats work, 1 x color + 1 x float fails, 2 x texture works, 1 x color + 1 x texture works

```
THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Program Info Log: Fragment shader is not compiled.

FRAGMENT

ERROR: 0:86: 'color' : syntax error

  81: 
  82: // varyings
  83: varying vec3 nodeVarying0; 
  84: 
  85: // vars
> 86: color nodeVar0; 
  87: 
  88: // codes
  89: 
  90: 
  91: // </node_builder>
  92: 
```

### Reproduction steps

1. Assign the material to a Mesh in the scene
2. Shader will fail to compile

### Code

```js
const material = new MeshBasicNodeMaterial();
material.colorNode = cond( bool(true), color(0xff0000), color(0x00ff00));
```

### Live example
https://jsfiddle.net/f1nuracy/

### Version

r155

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by sunag** [comment]
This code work here, maybe I missed something to reproduce the issue?
```js
material.colorNode = cond( bool( true ), color( 0xff0000 ), color( 0x00ff00  ) );
```

![image](https://github.com/mrdoob/three.js/assets/502810/441705d2-0195-406b-8b72-e0e7f8ceb214)

**Comment by njarraud** [comment]
I have found how to create a jsfiddle example with the node addon. Here is a reproduction - 
https://jsfiddle.net/f1nuracy/

**Comment by sunag** [comment]
I didn't realize it was WebGL, fixed.
