### ISSUE TITLE
more Shader Cover One

### ISSUE THREAD

**Issue by z2586300277** [mrdoob/three.js#26515]
### Description

I would like to apply two shaders to the same model by loading it twice, for example, I can apply multiple shaders to objects generated from the same material

### Reproduction steps

Using the material onBeforeComplete method for coloring, for example: (1) I add the same model twice and then assign two different shaders simultaneously, resulting in only one shader being applied to both models,(2) The two models are different, but the materials may be similar. The two models are assigned different shaders and only cover and apply one type of shader.(3) Objects generated using THREE.js materials, such as basic materials, standard materials, etc., have created N objects using these materials and assigned different shaders to each of them. However, there is also a problem where the shaders will only cover one of them

### Code

```js
// code goes here
```
#

### Live example

I dont have

### Version

154

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
