### ISSUE TITLE
Video textures look washed out in safari starting with version 0.152.0

### ISSUE THREAD

**Issue by justinrhodes1** [mrdoob/three.js#26516]
### Description

Video textures look washed out in safari with mesh basic materials (Version 16.3/18614.4.6.1.6). In Chrome the texture colors look fine. Setting the texture colorspace to `SRGBColorSpace` doesn't seem to make any difference. 

Related to the changes in color management in version 0.152.0.

### Live example

* [codesandbox example](https://codesandbox.io/s/dazzling-water-z32d64?file=/src/index.ts) 

### Screenshots

Safari
<img width="811" alt="safari" src="https://github.com/mrdoob/three.js/assets/44810214/16235cf9-9532-4baa-8210-0c168016c0b3">

Chrome
![chrome](https://github.com/mrdoob/three.js/assets/44810214/28795b07-4648-45ad-a23f-666ee1091d19)

### Version

0.155.0

**Comment by Mugen87** [comment]
I can reproduce on macOS 13.4.1 with Safari 16.5.2. It seems the texture indeed ignores the `SRGBColorSpace` definition. Enhancing the built-on shader with a manual sRGB decode seems to fix the issue:

https://codesandbox.io/s/white-snow-77vjd8?file=/src/index.ts:744-1348

Is `SRGB8_APLHA8` broken for video textures in WebKit?

**Comment by Mugen87** [comment]
https://threejs.org/examples/webgl_video_panorama_equirectangular shows the same issue.

**Comment by cankahya** [comment]
Any updates on this? Running into the same problem with a 360 Video – based on  https://threejs.org/examples/webgl_video_panorama_equirectangular

Insights / ideas would be much appreciated.

**Comment by Mugen87** [comment]
@donmccurdy Given the broken Webkit support and #26183, I think it's best for now to revert #25752. I originally did not want to go this route but the current situation is simply not acceptable. The fact is, video textures can't be properly used in production without patching the built-in shaders like in https://github.com/mrdoob/three.js/issues/26516#issuecomment-1658450918. 

I also doubt that the browser vendors will soon fix the errors (which is frustrating enough) so we need a fix in the engine.

**Comment by Mugen87** [comment]
> Insights / ideas would be much appreciated.

Until there is a fix in the engine, use the workaround from https://github.com/mrdoob/three.js/issues/26516#issuecomment-1658450918.

**Comment by justinrhodes1** [comment]
> I can reproduce on macOS 13.4.1 with Safari 16.5.2. It seems the texture indeed ignores the `SRGBColorSpace` definition. Enhancing the built-on shader with a manual sRGB decode seems to fix the issue:
> 
> https://codesandbox.io/s/white-snow-77vjd8?file=/src/index.ts:744-1348
> 
> Is `SRGB8_APLHA8` broken for video textures in WebKit?

Thanks for the quick reply. This solution will do for now! 👍

**Comment by donmccurdy** [comment]
@Mugen87 Agreed — seems like inline sRGB decoding is still necessary for video textures. 😔

**Comment by marcofugaro** [comment]
So this is broken on Webkit, is there already a webkit issue about this?

**Comment by Mugen87** [comment]
It seems there is no bug reported yet. At least when searching for `SRGB8_APLHA8`.

https://bugs.webkit.org/buglist.cgi?quicksearch=SRGB8_APLHA8

**Comment by Mugen87** [comment]
I've filed a bug today: https://bugs.webkit.org/show_bug.cgi?id=259768

**Comment by cgauld** [comment]
I have a worry that there may be no performant way for browsers to implement this on their side. I suspect the issue is that the underlying video texture comes straight from the video decoding hardware. In order for the browser to perform the conversion to linear then I think the only options available to them would be:

1. do the conversion CPU-side, which would be suuuper slow 
2. render the texture into another texture doing this conversion in a shader, which would also be much slower than just doing the conversion after sampling in the final fragment shader (as @Mugen87's fix does)

If they're already doing 2 then it may not incur very much any additional performance cost than there already is, but it does require the browsers to do the correct conversion in that intermediate shader.

**Comment by donmccurdy** [comment]
sRGB decoding is a standardized feature of WebGL, and works in other browsers. If there's a reason browsers _cannot_ implement it, then the feature should be evicted from the standard. But I expect it's just a bug, lots has been changing in Webkit's WebGL implementation over the past few years.

**Comment by cgauld** [comment]
I agree for sure :-) I think the reason things might be different for video textures is that accelerated path straight from the hardware decoder. Hopefully I'm wrong and it can be implemented in a performant way :-)
