### ISSUE TITLE
Nodes module uses class names to register nodes (addNodeClass) which crashes in production

### ISSUE THREAD

**Issue by njarraud** [mrdoob/three.js#26518]
### Description

The `addNodeClass` function exported from `nodes/core/Nodes.js` uses the name property of the nodes classes to register the nodes. The node module works well in development however when the code is packed for production, class names are often modified by the compiler and therefore the whole module crashes.

I believe that this function is mainly used by NodeLoader, but because of this test 
```js
if ( NodeClasses.has( nodeClass.name ) ) throw new Error( `Redefinition of node class ${ nodeClass.name }` );
```
it crashes as soon as any call to this module is made which makes it unusable for production.

### Reproduction steps

1. Import the node module in a file and build for production e.g. webpack

### Code

None

### Live example

None

### Version

r155

**Comment by njarraud** [comment]
Would it be acceptable to use a static property for each node class?

```js
class BitangentNode extends Node {
    static type = "BitangentNode";
    …
}
```

and then for `addNodeClass` -

```js
export function addNodeClass( nodeClass ) {

    if ( typeof nodeClass !== 'function' || ! nodeClass.type ) throw new Error( `Node class ${ nodeClass.type } is not a class` );
    if ( NodeClasses.has( nodeClass.type ) ) throw new Error( `Redefinition of node class ${ nodeClass.type }` );

    NodeClasses.set( nodeClass.type, nodeClass );

}
```

`createNodeFromType` would be working the same way.

Therefore, the code would not require predefined class names and the node loader would be unchanged.

**Comment by njarraud** [comment]
There is the same issue with `addLightNode` and `addNodeMaterial`.

**Comment by danrossi** [comment]
Terser removes the class name entirely. Here is my work around for now placing them in an exemption list. 

https://github.com/danrossi/three-webgpu-renderer/blob/master/rollup.config.js#L75

**Comment by njarraud** [comment]
Terser settings are not always available. e.g. NextJS

**Comment by Alexander-103** [comment]
Где и в какой программе это можно писать?

**Comment by danrossi** [comment]
That does use Terser also so there should be a config for adding something like this

```
keep_classnames: /ArrayUniformNode/
```

**Comment by njarraud** [comment]
Nextjs actually now uses SWC by default but like for Terser, the options are handled internally by the framework and cannot be changed. I know that this is not threejs problem, but I have the feeling that this small change would make the life easier and save troubleshooting time for anybody willing to use the node system seriously in production at the moment.

**Comment by LeviPesin** [comment]
I think we can do it like so:
```js
export function addNodeClass( nodeClass, name ) {
    if ( typeof nodeClass !== 'function' || ! name ) throw new Error( `Node class ${ name } is not a class` );
    if ( NodeClasses.has( name ) ) throw new Error( `Redefinition of node class ${ name }` );

    NodeClasses.set( name, nodeClass );

}

addNodeClass( BitangentNode, 'BitangentNode' );
```

**Comment by njarraud** [comment]
Just looking at it, yes I believe I would work.

**Comment by sunag** [comment]
We must consider serialization in this fix as well.

https://github.com/mrdoob/three.js/blob/d9305538c7e95b3ee2b8ac99db23e5a4c7fc86f5/examples/jsm/nodes/core/Node.js#L29-L33

**Comment by verekia** [comment]
It's not much, but I am offering a $50 bounty for fixing this! That's the last missing bit for shipping WebPGU support to MiniMana.io :)

**Comment by verekia** [comment]
With r157, running in production is now causing a new kind of bug.

It works fine in development mode, but when I build the app in production mode (with Next.js), I am now getting:

`Error: NodeMaterial: Material "MeshStandardMaterial" is not compatible.`

This is coming from:
https://github.com/mrdoob/three.js/blob/181e04eea8b569dc09048f9dc644310ed6b745a6/examples/jsm/nodes/materials/NodeMaterial.js#L506C22-L506C84

Does that seem minification-related?

**Comment by verekia** [comment]
I'll send the bounty either way. @LeviPesin, is it fine to send the money to your GH sponsor account? If not please get in touch! On Twitter or Discord as verekia, or the email on verekia.com.

**Comment by LeviPesin** [comment]
> Does that seem minification-related?

I think it could happen from tree-shaking node materials (and `addNodeMaterial` calls, maybe they could be somehow specifically marked as containing side-effects).

> is it fine to send the money to your GH sponsor account?

Sure!
