### ISSUE TITLE
Setting transparent meshes in WebXR causes weird flickering glitch 

### ISSUE THREAD

**Issue by gabrielwebphy** [mrdoob/three.js#26520]
### Description

I’m currently building an app using THREE in WebXR and I’m not able to set the materials of a mesh to some opacity. As soon as i put transparent = true on the materials, without even setting an opacity, the glitch similar to a flickering already starts.
Already tried attributes such as material.depthWrite = false, material.depthTest = false, and it definitely helped, but didn't solved it.
A simple example in THREE would already help me. I have observed that the more meshes the gltf model has, the more this effect will happen.

### Reproduction steps

1. Create an app using WebXR with THREE
2. Load a glb model into the scene (try one with a relatively high count of meshes)
3. Try setting the transparency of the model to true (you don't even need to set an opacity)
The model will start to flicker when looked from certain angles.

### Code
```
loader.load("./assets/teste.glb", (gltf) => {
  const gltfScene = gltf.scene || gltf.scenes[0];
  arObject = gltfScene;
  arObject.traverse((n) => {
    f (n.isMesh) {
      n.castShadow = true;
      n.receiveShadow = true;
      n.material.transparent = true;
      n.material.opacity = 0.75;
      n.material.depthWrite = false
      n.material.depthTest = false
      if (n.material.map) n.material.map.anisotropy = 16;
    }
  });
});
```
.
.
.
```
    renderer = new THREE.WebGLRenderer({
      alpha: true,
      preserveDrawingBuffer: true,
      canvas: canvas,
      context: gl,
      //sortObjects: false
    });
    renderer.autoClear = false;
    camera.matrixAutoUpdate = false;

    binding = new window.XRWebGLBinding(session, gl);
    session.updateRenderState({
      baseLayer: new window.XRWebGLLayer(session, gl),
    });
    session.requestReferenceSpace("viewer").then((refSpace) => {
      xrViewerSpace = refSpace;
      session.requestHitTestSource({ space: xrViewerSpace }).then((hitTestSource) => {
        xrHitTestSource = hitTestSource;
      });
    });
    session.requestReferenceSpace("local").then((refSpace) => {
      xrRefSpace = refSpace;
      session.requestAnimationFrame(onXRFrame);
    });
```
.
.
.
```
  navigator.xr
    .requestSession("immersive-ar", {
      requiredFeatures: ["camera-access", "hit-test", "local"],
      optionalFeatures: ["dom-overlay"],
      domOverlay: { root: document.getElementById("overlay") },
    })
    .then(onSessionStarted);
```
.
.
.
```
  function onXRFrame(time, frame) {
    let session = frame.session;
    session.requestAnimationFrame(onXRFrame);
    let pose = frame.getViewerPose(xrRefSpace);

    if (pose) {
      gl.bindFramebuffer(gl.FRAMEBUFFER, session.renderState.baseLayer.framebuffer);
      gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
      gl.getError();

      const firstView = pose.views[0];
      const viewport = session.renderState.baseLayer.getViewport(firstView);
      renderer.setSize(viewport.width, viewport.height);

      camera.matrix.fromArray(firstView.transform.matrix);
      camera.projectionMatrix.fromArray(firstView.projectionMatrix);
      camera.updateMatrixWorld(true);

      renderer.render(scene, camera);
    }
  }
```
### Live example

posicao-react.web.app

### Screenshots

https://github.com/mrdoob/three.js/assets/127117445/7b0be14a-0592-4104-bf59-8ef6526e14e2
![WhatsApp Image 2023-08-01 at 10 19 26 (1)](https://github.com/mrdoob/three.js/assets/127117445/d6fc294c-e9a6-40ac-a223-7c4b00c0d154)
![WhatsApp Image 2023-08-01 at 10 19 26](https://github.com/mrdoob/three.js/assets/127117445/cb0c82ef-250b-4fe4-b924-c6fbaaff51c9)

### Version

0.147.0

### Device

Mobile

### Browser

Chrome

### OS

Android

**Comment by gabrielwebphy** [comment]
The screenshots show the flicker of the ceiling, but it will happen a lot also with the outlets and the door. I also included a video to showcase it better.

**Comment by Mugen87** [comment]
So when you move the camera with let's say `OrbitControls`, the flickering does not happen?

**Comment by Mugen87** [comment]
How did you solve the issue?
