### ISSUE TITLE
Issue with Pointlight for renderer -  version 0.155.0

### ISSUE THREAD

**Issue by milindanantwar** [mrdoob/three.js#26531]
### Description

Hello, we have a scene that renders a model from GLTF.  On model load, we are setting the material for GLTF meshes as a MeshStandardMaterial. And scene contains the orbit control with a point light camera. This works fine until version 1.54 and before. However, for version 1.55.0, the mesh faces appear completely black.

   

### Reproduction steps

1. Create a scene with PerspectiveCamera, OrbitControl and Renderer as WebGLRenderer
2. Add some mesh and apply MeshStandardMaterial
3. And point light facing towards added mesh from a certain distance.
4. Notice that mesh does not show the material being applied. 

### Code

```js

const defaultMaterial = new MeshStandardMaterial({ color: 0x90ee90 });

// Add any Mesh and apply the above material

const light = new PointLight(0xffffff, 0.9);
light.position.set(-50, 30, 50);
scene.add(light);
```

### Live example

NA

### Version

r.0.155.0

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
Lighting mode changed in `three.js` with `r155`. Read the following forum topic for all details:

https://discourse.threejs.org/t/updates-to-lighting-in-three-js-r155/53733

If you need further migration help, please file a new topic at the forum.
