### ISSUE TITLE
[OrbitControls] - Documentation with wrong information or type outdated

### ISSUE THREAD

**Issue by sousadiego11** [mrdoob/three.js#26539]
### Description

The [documentation](https://threejs.org/docs/#examples/en/controls/OrbitControls) points the property `zoomToCursor`, but this property is not found using Typescript, and applying it as "`true`" does'nt change anything.

- If this property actually works, and my understanding is mistaken, i think the type is still wrong.
- My package.json is as follows 👇:

### Reproduction steps

try to use the property

### Code

```
{
  "name": "three-portfolio",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "three": "^0.154.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@types/three": "^0.154.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vitejs/plugin-react": "^4.0.3",
    "eslint": "^8.45.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5"
  }
}

```

### Live example

![image](https://github.com/mrdoob/three.js/assets/65742620/117783e5-fbd4-4da6-9c66-aef51a4d9466)

### Version

0.154.0

**Comment by Mugen87** [comment]
TS declaration types for `three.js` are maintained at: https://github.com/three-types/three-ts-types

Please file an issue at this repository.
