### ISSUE TITLE
'#version' cannot be used in RawShaderMaterial

### ISSUE THREAD

**Issue by momo2019** [mrdoob/three.js#26532]
### Description

I want to use '#version 300 es' in RawShaderMaterial, but can't succeed.

throws exception '#version directive must occur 
before anything else, except for comments and white space'

After debugging, I saw the following situation, when RawShaderMatiral cannot add '#version 300 es' to versionString, and there are two '#define' in the prefix, resulting in '#version 300 es' defined in my shader cannot at the top of all code

![WX20230803-142230](https://github.com/mrdoob/three.js/assets/26078793/6cc51ec7-1bb0-42dd-bab9-8d101d73e523)

![WX20230803-142313](https://github.com/mrdoob/three.js/assets/26078793/1440ecf9-d9b9-4d80-9246-da793253deb6)

![WX20230803-142333](https://github.com/mrdoob/three.js/assets/26078793/79d34b52-bb7e-4d18-9fde-cd0792ccc9ca)
 

### Reproduction steps

1. Use RawShaderMaterial
2. write '#version 300 es' in shader
3. run

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r154

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by gkjohnson** [comment]
I believe you're expected to use [.glslVersion](https://threejs.org/docs/index.html?q=raws#api/en/materials/ShaderMaterial.glslVersion) to set the version string.

**Comment by Mugen87** [comment]
Yes, the engine has to control the `version` qualifier so do it like in the examples:

https://github.com/mrdoob/three.js/blob/b1fbdc5034809f88bac08f7e44f74171ed299ccb/examples/webgl2_ubo.html#L251-L260
