### ISSUE TITLE
OrbitControls when zoomToCursor is enabled `updateMouseParameters` should consider object change

### ISSUE THREAD

**Issue by xiaowangxu** [mrdoob/three.js#26548]
### Description

in OrbitControls function `updateMouseParameters` ...dollyDirection.set(...).unproject( `object` )...

it only works with the `object` in new OrbitControls(`object`, ...) which it captured during the constructor

so, if user change the `object` to another camera/object3d (by the way checking object is a Camera is appericated) it won't work.

### Reproduction steps

1.create an orbitcontrols with zoomToCursor set to true
2.set control.object to another camera or object3d after constrcution
3.zoom in the viewport

### Code

```js
// the OrbitControls constructor
constructor(object, domElement) {
		// ...
		function updateMouseParameters( event ) {
			if ( ! scope.zoomToCursor ) {
				return;
			}
			performCursorZoom = true;

			const rect = scope.domElement.getBoundingClientRect();
			const x = event.clientX - rect.left;
			const y = event.clientY - rect.top;
			const w = rect.width;
			const h = rect.height;

			mouse.x = ( x / w ) * 2 - 1;
			mouse.y = - ( y / h ) * 2 + 1;

			// the unproject happens here
			dollyDirection.set( mouse.x, mouse.y, 1 ).unproject( object ).sub( object.position ).normalize();

		}
		// ...
}
```

the `unproject( object )` should be changed to `unproject( this.object )` or `unproject( scope.object )`
of course,  `sub( object.position )` should be change too

### Live example

see the code, i think it's clear enough

### Version

155

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Good catch! Would you like to file a PR and change from `object` to `scope.object`?
