### ISSUE TITLE
Examples:  The `USDZExporter button` is displayed incorrectly in `misc_exporter_usdz.html`

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#26551]
### Description

https://github.com/mrdoob/three.js/blob/67c4225af7339f1970260d022e0de1f605519269/examples/misc_exporter_usdz.html#L34-L36

The `USDZExporter button` is displayed incorrectly in `misc_exporter_usdz.html`, I think the `arkit.png` image transparency causes this problem.

### Reproduction steps

1. Open `https://threejs.org/examples/misc_exporter_usdz.html` in browser.
2. We can't see the `USDZExporter button` in the middle at the bottom of the screen, but we can click it.

### Code

https://github.com/mrdoob/three.js/blob/67c4225af7339f1970260d022e0de1f605519269/examples/misc_exporter_usdz.html#L34-L36

### Live example

https://threejs.org/examples/misc_exporter_usdz.html

### Screenshots

<img width="573" alt="misc_exporter_usdz" src="https://github.com/mrdoob/three.js/assets/23699926/541f1b99-5739-4f24-8455-a575d961a114">

### Version

r155

### Device

Desktop

### Browser

Chrome, Firefox

### OS

Windows

**Comment by Mugen87** [comment]
This examples is mainly intended for iOS where an icon automatically appears by the OS. Hence, #23306 update the example such that a transparent button is behind the icon that triggers the export.
