### ISSUE TITLE
KTX2Loader: Support for ASTC and ETC1 formats

### ISSUE THREAD

**Issue by CITIZENDOT** [mrdoob/three.js#26569]
### Description

ASTC & ETC1 textures generated with [ARM-software/astc-encoder](https://github.com/ARM-software/astc-encoder) and [etc2comp](https://github.com/google/etc2comp) are being rendered inconsistently with threejs versions.

I have a PNG image of resolution 1024x1024. I compressed it into ASTC with below command. (`astcenc-sse2` is built from [ARM-software/astc-encoder](https://github.com/ARM-software/astc-encoder) source)

```bash
❯ astcenc-sse2 -cs texture-1k.png texture-astc-1k.ktx 6x6 -thorough
❯ file texture-astc-1k.ktx
texture-astc-1k.ktx: Khronos KTX texture (little-endian), 1024 x 1024, COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR
```

And I compressed the same PNG into ETC1 texture with below command. (`EtcTool` is built from [google/etc2comp](https://github.com/google/etc2comp) source)

```bash
❯ EtcTool texture-1k.png -format ETC1  -output ./texture-etc1-1k.ktx
❯ file texture-etc1-1k.ktx
texture-etc1-1k.ktx: Khronos KTX texture (little-endian), 1024 x 1024, ETC1_RGB8_OES
```

Since these are in KTX container format, I used [KTXLoader.js](https://unpkg.com/three@0.153.0/examples/jsm/loaders/KTXLoader.js) of `three@0.153.0` to load them. They appeared black (I was testing on mobile).

But when I change the threejs version to older versions, they did appear with colors. Exact specifics below.

- ETC1 texture appeared correctly when `three <= 0.135.0` 
- ASTC texture appeared when `three <= 0.136.0` (although it's darker).

PS:
- It might appear that, I'm mixing up `KTXLoader.js` of `three@.153.0` with different versions. But older threejs seems to render textures without errors, but the newer threejs is not rendering them.
- PNG Image and texture files are in codesandbox repos which are linked below.

### Reproduction steps

Steps to create textures are in description. Concise demo is in Codesandbox repo which is linked below. 

### Code

This is how I'm loading textures.

```js
const ktxLoader = new KTXLoader();
const getKTXTexture = async () => {
  return new Promise((res, rej) => {
    ktxLoader.load("../texture-astc-1k.ktx", (texture) => {
      // Setting to sRGB is making texture super dark
      texture.encoding = LinearEncoding;
      console.log(texture, texture.mipmaps[0].data.length);
      res(texture);
    });
  });
};

getKTXTexture().then((texture) => {
  const material = new MeshBasicMaterial({ map: texture });
})
```

### Live example

1. [ASTC Codesandbox](https://codesandbox.io/s/astc-texture-demo-with-vite-dmw9g3)
2. [ETC1 Codesandbox](https://codesandbox.io/s/etc1-texture-demo-with-vite-ptwmw9)

### Version

0.153.0

### Device

Mobile

### Browser

Chrome

### OS

Android

**Comment by Mugen87** [comment]
Test case are not valid if you mix components from different releases. I've cleaned up the codesandbox demos to make sure the versions of three.js and KTXLoader match.

Links with `r155`:

1. [ASTC Codesandbox](https://codesandbox.io/s/astc-texture-demo-with-vite-forked-mfflv3)
2. [ETC1 Codesandbox](https://codesandbox.io/s/etc1-texture-demo-with-vite-forked-y2kkh2)

**Comment by CITIZENDOT** [comment]
Thank you. I thought it's interesting to note that, older three.js renders the textures correctly. (even if its dark, at least it's rendered)

**Comment by Mugen87** [comment]
With `r136` compressed textures internally use `gl.texStorage2D ()` + `gl.compressedTexSubImage2D()`. This change requires that compressed texture loader properly setup the texture with correct format and color space. `KTXLoader` does not do that. I suggest you switch to the KTX2 format and `KTX2Loader` or configure the format and color space manually. At least the ASTC demo can be fixed like that:

ASTC: https://codesandbox.io/s/astc-texture-demo-with-vite-forked-46tyvf
ETC1: https://codesandbox.io/s/etc1-texture-demo-with-vite-forked-7p2692

My Pixel4a properly shows the ASTC texture but not the ETC1 one.

**Comment by Mugen87** [comment]
You maybe want to target ETC2 instead since this format allows you to define sRGB textures which is required for your use case. The texture's format should be `RGBA_ETC2_EAC_Format` and the color space `SRGBColorSpace`. This ends up natively in `COMPRESSED_SRGB8_ALPHA8_ETC2_EAC`.

**Comment by CITIZENDOT** [comment]
Setting format did fix the ASTC textures for me.

[ARM-software/astc-encoder](https://github.com/ARM-software/astc-encoder)  did not offer support for KTX2 format. I'll look into KTX-Software tools to encode into ASTC format. By the way, When using KTX2 container format with ASTC compression, does it still transcode textures into something? Or does it use them directly? Because the primary reason, we're using these ETC & ASTC is to avoid transcoding.

**Comment by Mugen87** [comment]
AFAIC, KTX2 always compresses to Basis and the transcode to a supported format on the client.

**Comment by Mugen87** [comment]
@donmccurdy Will `KTXLoader` be removed at some point? Or is necessary for some reason to keep in around next to `KTX2Loader`?

**Comment by donmccurdy** [comment]
> > By the way, When using KTX2 container format with ASTC compression, does it still transcode textures into something? Or does it use them directly?
> 
> KTX2 always compresses to Basis and then transcodes to a supported texture format on the client.

This isn't correct — KTX2 is capable of representing texture data in GPU block-compressed formats like ASTC and ETC1 directly as well. In that case, the KTX2 data can be uploaded directly to the GPU without transcoding. However, it's _much_ more common to use the Basis Universal variants (UASTC and ETC1S) instead, which transcode to an appropriate format. Because the Basis Universal formats are so much more common among three.js users, I haven't seen any tools for creating KTX2 files containing raw ASTC and ETC1, and I'm not sure whether KTX2Loader would parse them correctly (would be happy to fix that, given a sample, if not).

@Mugen87 I think we should probably keep KTXLoader around unless/until there are solid workflows for creating KTX2 files containing raw texture data in these formats as well as a few others.

***

Aside – Transcoding from UASTC→ASTC or from ETC1S→ETC1 is supposed to be extremely fast. If that's not the case, I'd love to look more closely at an example and see what we can do to improve this.

**Comment by CITIZENDOT** [comment]
> KTX2 always compresses to Basis and then transcodes to a supported texture format on the client.
> 
> Why do you want to avoid transcoding? Are there performance related concerns?

Yes, when dealing with 2k/4k textures transcoding is taking a significant amount of time. We're rendering a 3D video (say 30fps), and time taken to process frames should be as less as possible. Currently transcoding is our bottleneck.

**Comment by Mugen87** [comment]
@donmccurdy Thanks for clarifying this issue! I wasn't aware of a non-Basis usage of KTX2 since I've simply never seen it in production.

**Comment by Mugen87** [comment]
The ETC1 texture does not work since it is not supported with `compressedTexSubImage2D()` since only the formats from `WEBGL_compressed_texture_etc` are supported. So you need definitely need ETC2/EAC.

**Comment by Mugen87** [comment]
It seems the original question of the issue has been answered. Closing.

**Comment by CITIZENDOT** [comment]
> Aside – Transcoding from UASTC→ASTC or from ETC1S→ETC1 is supposed to be extremely fast. If that's not the case, I'd love to look more closely at an example and see what we can do to improve this.

I'll put together a demo for this.

**Comment by CITIZENDOT** [comment]
> Because the Basis Universal formats are so much more common among three.js users, I haven't seen any tools for creating KTX2 files containing raw ASTC and ETC1, and I'm not sure whether KTX2Loader would parse them correctly (would be happy to fix that, given a sample, if not).

I created ASTC compressed texture in KTX2 container format using [`toktx`](https://github.com/KhronosGroup/KTX-Software/tree/main/tools/toktx).

```bash
❯ toktx --t2 --encode astc texture-astc-1k.ktx2 texture-1k.png
❯ file texture-astc-1k.ktx2
texture-astc-1k.ktx2: Khronos KTX2 texture, 1024 x 1024, ASTC_6x6_SRGB_BLOCK
```

Latest KTX2Loader raises this error: `THREE.KTX2Loader: Unsupported vkFormat.` to load this texture file. Here is the `ktxinfo` log

```bash
❯ ktxinfo texture-astc-1k.ktx2
Header

identifier: «KTX 20»\r\n\x1A\n
vkFormat: VK_FORMAT_ASTC_6x6_SRGB_BLOCK
typeSize: 1
pixelWidth: 1024
pixelHeight: 1024
pixelDepth: 0
layerCount: 0
faceCount: 1
levelCount: 1
supercompressionScheme: KTX_SS_NONE
dataFormatDescriptor.byteOffset: 0x68
dataFormatDescriptor.byteLength: 44
keyValueData.byteOffset: 0x94
keyValueData.byteLength: 132
supercompressionGlobalData.byteOffset: 0
supercompressionGlobalData.byteLength: 0

Level Index

Level0.byteOffset: 0x120
Level0.byteLength: 467856
Level0.uncompressedByteLength: 467856

Data Format Descriptor

DFD total bytes: 44
Vendor ID: KHR_DF_VENDORID_KHRONOS
Descriptor type: KHR_DF_KHR_DESCRIPTORTYPE_BASICFORMAT
Version: KHR_DF_VERSIONNUMBER_1_3
Descriptor block size: 40
Flags: 0x0 (KHR_DF_FLAG_ALPHA_STRAIGHT)
Transfer: KHR_DF_TRANSFER_SRGB
Primaries: KHR_DF_PRIMARIES_BT709
Model: KHR_DF_MODEL_ASTC
Dimensions: 6, 6, 1, 1
Plane bytes: 16, 0, 0, 0, 0, 0, 0, 0
Sample 0:
    Qualifiers: 0x0 ()
    Channel Type: 0x0 (KHR_DF_CHANNEL_ASTC_DATA)
    Length: 128 bits Offset: 0
    Position: 0, 0, 0, 0
    Lower: 0x00000000
    Upper: 0xffffffff

Key/Value Data

KTXorientation: rd
KTXwriter: toktx v4.3.0-alpha3~1 / libktx v4.3.0-alpha3-6-g1ae04f89
KTXwriterScParams: --encode astc
```

The VkFormat of this texture file (`VK_FORMAT_ASTC_6x6_SRGB_BLOCK`) is indeed [missing in KTX2Loader.js](https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/KTX2Loader.js#L62).

[Codesandbox Repo](https://codesandbox.io/s/astc-ktx2-texture-demo-with-vite-jkzldz)

**Comment by CITIZENDOT** [comment]
> I've been hoping to find time to support f16, f32, and BC6H cubemaps in KTX2.

I don't know about f16, f32 and BC6H, but `toktx` supports cubemaps in KTX2.

```
  --cubemap    KTX file is for a cubemap. At least 6 <infile>s must be provided,
               more if --mipmap is also specified. Provide the images in the
               order +X, -X, +Y, -Y, +Z, -Z where the arrangement is a
               left-handed coordinate system with +Y up. So if you're facing +Z,
               -X will be on your left and +X on your right. If --layers > 1
               is specified, provide the faces for layer 0 first then for
               layer 1, etc. Images must have an upper left origin so
               --lower_left_maps_to_s0t0 is ignored with this option.
  ...
  ...

  --t2         Output in KTX2 format. Default is KTX.
```

**Comment by donmccurdy** [comment]
Proposed feature addition for ASTC 6x6 format:

- https://github.com/mrdoob/three.js/pull/26586

We should be able to add more compressed formats by adding to the maps you mentioned after this, if we have a way to create and test the files.

> I don't know about f16, f32 and BC6H, but toktx supports cubemaps in KTX2...

Yes, we support u8 cubemaps now. The upcoming alpha for KTX Software can create cubemaps from OpenEXR inputs, which I expect would mean either f16 or f32 data in the KTX2 file.

**Comment by CITIZENDOT** [comment]
Thank you @donmccurdy for the ASTC support ❤️ .

Reproducing the entire video is little hard since all frame files are not CDN yet. So I made a little tool for measuring transcoding time against the the time taken to play those frames. [It can be accessed here](https://rendering-3d.vercel.app/measure-ktx2). If this tool isn't sufficient to make good remarks, Let me know, I'll try to reproduce the full 3d video demo.

I'm attaching a drive link which contains a series of KTX2 video textures (CompressedArrayTextures). [Drive Link](https://drive.google.com/drive/folders/16Z0d-zPTIgy2T3XCPTRVwni3yeJ1HGVP?usp=drive_link).


Some info about these KTX2 files:
- Each KTX2 file contains 5 frames. So, In the above tool's UI, frame count needs to be set to `5`. We want to play these textures at 25fps. So frameRate should be set to `25` in the UI.
- These files are generated using [`basisu`](https://github.com/BinomialLLC/basis_universal) CLI tool.
- Resolution of these textures is 4k (4096x4096).

Here's a report which loads 2 seconds worth of textures (2 seconds at 25fps => 50 texture frames => 50/5 => 10 texture files)
![image](https://github.com/mrdoob/three.js/assets/52322531/065aad46-6442-40b4-980a-4e6b6891c1e3)

This tool is doing only transcoding and nothing else. When an app is doing other things like loading geometry frames etc... It needs some room for flexibility and transcoding these leaves very little time for other tasks.

[This is the source of above measuring tool](https://github.com/CITIZENDOT/rendering-3d)

And here I'm measuring the transcoding time. If there is any flaw in measuring them, please let me know.
https://github.com/CITIZENDOT/rendering-3d/blob/04201c2d6b785ca61591f05c08d2cceb3673a763/src/routes/measure-ktx2.jsx#L152-L158
