### ISSUE TITLE
The doc for CameraUtils says import incorrect exported name "CameraUtils"

### ISSUE THREAD

**Issue by tomphan** [mrdoob/three.js#26563]
### Description

The doc says:
    import { CameraUtils } from 'three/addons/utils/CameraUtils.js';

However if follow, there will be an error message in the console:
    Uncaught SyntaxError: The requested module 'three/addons/utils/CameraUtils.js' does not provide an export named 'CameraUtils'

Actually the code `CameraUtils.js` exports only the name `frameCorners`. So the import syntax should be:
    import { frameCorners } from 'three/addons/utils/CameraUtils.js';

### Reproduction steps

1. Following the docs: https://threejs.org/docs/index.html#examples/en/utils/CameraUtils    
2. import { CameraUtils } from 'three/addons/utils/CameraUtils.js';

### Code

```js
    import { frameCorners } from 'three/addons/utils/CameraUtils.js';
```

### Live example

---

### Version

0.155.0

**Comment by Mugen87** [comment]
Good catch!

Would you like to file a PR that changes the import similar to `BufferGeometryUtils`? Meaning:
```js
import * as CameraUtils from 'three/addons/utils/CameraUtils.js';
```

**Comment by tomphan** [comment]
If use: `import { frameCorners }`, the code function `frameCorners(...)` can be used as usually.

If you use the `* as CameraUtils `:
```js
 import * as CameraUtils from 'three/addons/utils/CameraUtils.js';
```

The code for calling `frameCorners` should now be:
```js
  CameraUtils.frameCorners(...);
```

**Comment by Mugen87** [comment]
Yes, however we have to stick to one convention and we usually use the `import * as` syntax. Even in code for example:

https://github.com/mrdoob/three.js/blob/0b169138a99655148ed9601f87c685da54997155/examples/webgl_geometry_minecraft.html#L154
