### ISSUE TITLE
WebGLRenderer copyTextureToTexture3D failing on Data3DTexture using Uint32Array

### ISSUE THREAD

**Issue by nhasdarjian** [mrdoob/three.js#26560]
### Description

I'm trying to copy the contents of one Data3DTexture into another,
but I get multiple WebGL warnings in the console and the data is not copied.

Both the source and destination textures are built on Uint32Arrays instead of Uint8Arrays,
other than that I have tried to follow the examples closely.

Please let me know if there are any steps I missed, thanks!

### Reproduction steps

1. Instantiate WebGLRenderer as renderer.
2. Instantiate Box3 as box to represent desired region of source texture.
3. Instantiate THREE.Vector3 as position to represent offset of source texture in destination texture.
4. Instantiate two Uint32Array objects, one as source and one as destination. (destination is of same or larger size)
5. Instantiate two Data3DTexture objects using source and destination Uint32Arrays.
6. Call renderer.copyTextureToTexture3D( box, position, source, destination )

### Code

```js
  const renderer = new THREE.WebGLRenderer()
  
  const box = new THREE.Box3(
    new THREE.Vector3( 0, 0, 0 ),
    new THREE.Vector3( 2, 2, 2 )
  )

  const position = new THREE.Vector3( 0, 0, 0 )

  const source = new THREE.Data3DTexture(
    new Uint32Array( 2 * 2 * 2 ).fill( -1 ),
    2, 2, 2
  )
  source.type = THREE.UnsignedIntType
  source.needsUpdate = true
  
  const destination = new THREE.Data3DTexture(
    new Uint32Array( 4 * 4 * 4 ),
    4, 4, 4
  )
  destination.type = THREE.UnsignedIntType
  destination.needsUpdate = true

  renderer.copyTextureToTexture3D( box, position, source, destination )
```

### Live example

https://codepen.io/nhasdarjian/pen/ZEmNbMq
Scroll to the bottom of the JS panel for relevant code

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/16891041/708cd4cf-ecc2-4fce-a8f9-07b360b83f7d)

### Version

r155

### Device

Desktop

### Browser

Chrome, Edge

### OS

Windows

**Comment by Mugen87** [comment]
According to the documentation of `texSubImage3D()` , `Uint32Array` is no valid pixel source for the texture.

https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/texSubImage3D

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help with using `copyTextureToTexture3D()`.
