### ISSUE TITLE
Proposal: InstancedMesh.updateRanges -> array of update ranges

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#26562]
### Description

It looks like only a [single](https://github.com/mrdoob/three.js/blob/0b169138a99655148ed9601f87c685da54997155/src/objects/InstancedMesh.js#L25) [`updateRange`](https://github.com/mrdoob/three.js/blob/0b169138a99655148ed9601f87c685da54997155/src/core/BufferAttribute.js#L30) is supported, and `gl.bufferSubData` gets called [only once for that range](https://github.com/mrdoob/three.js/blob/0b169138a99655148ed9601f87c685da54997155/src/renderers/webgl/WebGLAttributes.js#L99-L109).

### Solution

To allow higher control of optimization by Threejs users, a new `.updateRanges` property could be an array of update ranges, and in `WebGLAttributes` it call loop on those and call `gl.buffSubData` for each range. 

### Alternatives

n/a

### Additional context

This may allow multiple sets of instances to be updated per frame.

For example, if someone has 1 million instances, maybe they only want to update 10 through 20, 1_000 through 1_100, and 500_000 through 500_005. For this they can define three update ranges, and avoid having to, at minimum, define a single range from 10 through 500_005. The array will allow uploading data for 115 instances instead of (at least) 499_995 instances.

**Comment by Mugen87** [comment]
It was tried to implement this once, see #13393. But it seems there was a performance issue that caused the OP to close the PR.

**Comment by trusktr** [comment]
Yeah that's the idea. Yeah, creating and replacing arrays every frame is not gonna be ideal. With that approach, Threejs users would need to re-use array values (object pool).

Another idea is instead of an array of objects, it could be a Map<number, number> or Record<number, number> (pairs of start,count), then iterating the key-value pairs.

With either approach, to avoid adding/removing start-count pairs (whether objects in an array, or keys-values in a map/object), for utmost performance, perhaps an updateRangeCount would make it easy to specify how many update ranges to iterate over (default to all).

For back compat, updateRange could stay the same, and a new updateRanges (plural) could have multiple ranges.

**Comment by Mugen87** [comment]
Fixed via #27103.
