### ISSUE TITLE
Add more 'made with Three.js' links to featured section on the website

### ISSUE THREAD

**Issue by rpaladin** [mrdoob/three.js#26561]
### Description

# SUGGESTED LINKS
* **ev.io:** https://ev.io
* **Kirka.io:** https://kirka.io
* **JAMIR.io:** https://jamir.io

# VERIFIED HOW
### Wappalyzer
* Browser extension.
  * People can also verify for free without installing the browser extension if they create a web account: https://www.wappalyzer.com.

### In-game proof (using Wappalyzer browser extension)

<details>
<summary><strong>ev.io</strong></summary>
<img src="https://github.com/mrdoob/three.js/assets/69180012/bbe456f0-d6b3-4c6a-9df6-b4b6cd3f2682" />
</details>

<details>
<summary><strong>Kirka.io</strong></summary>
<img src="https://github.com/mrdoob/three.js/assets/69180012/511e5fad-5bc7-4510-9b5c-13871e1525c6" />
</details>

<details>
<summary><strong>JAMIR.io</strong></summary>
<img src="https://github.com/mrdoob/three.js/assets/69180012/222328ec-e6c5-41ed-b8f9-0f0b53c73cef" />
</details>

### Discord
* Joined each of their official Discords respectfully and found evidence.

<details>
<summary><strong>ev.io</strong></summary>
<img src="https://github.com/mrdoob/three.js/assets/69180012/fe780bd5-8e31-4710-9855-1b0311507f7b" />

<img src="https://github.com/mrdoob/three.js/assets/69180012/bee01231-b3af-4c40-8064-26402e8bbd4f" />

<img src="https://github.com/mrdoob/three.js/assets/69180012/3191e0fc-f00f-4b93-b235-a4c4d5d5c4eb" /><br />

<img src="https://github.com/mrdoob/three.js/assets/69180012/1408fed0-e675-4f6b-adc3-4f4efac840ed" />
</details>

<details>
<summary><strong>Kirka.io</strong></summary>
<img src="https://github.com/mrdoob/three.js/assets/69180012/927684cd-b5ad-40e0-a9d9-8142a9ec8aab" /><br />

<img src="https://github.com/mrdoob/three.js/assets/69180012/e1864efc-566e-49f2-9ff0-a43f117781bb" />

<img src="https://github.com/mrdoob/three.js/assets/69180012/ad515a4c-fc55-4ddc-9498-9bfe7380afda" /><br />

<img src="https://github.com/mrdoob/three.js/assets/69180012/c8de830b-3665-4045-83a1-b4a4efe0bab1" /><br />

<img src="https://github.com/mrdoob/three.js/assets/69180012/a6b8ad13-1117-4147-8abd-b298347c4c2a" />
</details>

<details>
<summary><strong>JAMIR.io</strong></summary>
<img src="https://github.com/mrdoob/three.js/assets/69180012/536e0ca6-fb90-4b2d-9cec-e58bb96ff561" />

<img src="https://github.com/mrdoob/three.js/assets/69180012/34276347-607b-4ec6-a8af-6cc40656ca3c" /><br />

<img src="https://github.com/mrdoob/three.js/assets/69180012/06bded52-41a0-46ad-ac36-b6649bcd12d1" />
</details>

### Other
* **ev.io:** https://discourse.threejs.org/t/ev-io-top-blockchain-game-looking-for-game-devs-full-time-paid/43128
* **Kirka.io:** https://www.reddit.com/r/IoGames/comments/zgwj40/kirkaio_is_a_multiplayer_fps_in_the_browser_patch/
* **Jamir.io:** https://discourse.threejs.org/t/latest-gameplay-from-my-multiplayer-three-js-fps-game-jamir/12868

### Solution

Add any links if they're wanted.

### Alternatives

Remove any links if they're not wanted.

**Comment by Mugen87** [comment]
Closing. If you want to promote projects for the three.js homepage, it's best to share a `Showcase` topic at the forum or just tweet about it. @mrdoob scans existing projects from time to time and then updates the homepage.
