### ISSUE TITLE
Support more than 4 UV layers in Nodes

### ISSUE THREAD

**Issue by njarraud** [mrdoob/three.js#26570]
### Description

My understanding is that the standard material system in threejs now handles up to a maximum of 4 uv layers with attribute names ranging from `uv` to `uv3`. It would be great if the node system could handle more. It was the case in older versions.

### Solution

This would only require a minor modification in `WebGLNodeBuilder.js`.

`getAttributes` currently skips any attributes starting by `uv` with one digit or none via a regex in order to prevent redefinitions. It means that for example `uv4` is skipped even if not injected by default.

Regex check
```js
if (/^(position|normal|uv\d?)$/.test(attribute.name)) continue;
```
 could be replaced by
```js
if (/^(position|normal|uv[1-3]?)$/.test(attribute.name)) continue;
```

Therefore only `uv`, `uv1`, `uv2` and `uv3` would be skipped and `UVNode(4)`would yield `uv4` to reach the 5th uv layer. Shader compilation is currently crashing without this fix.

### Alternatives

None

**Comment by Alexander-103** [comment]
Как создавать узлы?
