### ISSUE TITLE
The problem of casting shadows on a geometric plane

### ISSUE THREAD

**Issue by rwjCxgsy** [mrdoob/three.js#26579]
### Description

There are two identical planar geometries in the scene, one of which is inverted by 180 degrees, and the front rendering fails to produce shadows, while the reverse side does

### Reproduction steps

1.Creating two planar geometries
2.One of them rotates 180 degrees.
3.Setting the cast shadow

### Code

```js

  {
    const plane = new THREE.Mesh(
      new THREE.PlaneGeometry(6, 6),
      new THREE.MeshStandardMaterial({
        color: 0x0000ff,
      })
    );
    plane.position.x = 6;
    plane.position.y = 6;
    plane.castShadow = true;
    scene.add(plane);
  }

  {
    const plane = new THREE.Mesh(
      new THREE.PlaneGeometry(6, 6),
      new THREE.MeshStandardMaterial({
        color: 0x0000ff,
      })
    );
    plane.rotateX(Math.PI);
    plane.position.x = -6;
    plane.position.y = 6;
    plane.castShadow = true;
    scene.add(plane);
  }


```

### Live example

https://codesandbox.io/p/sandbox/musing-leakey-3dk23z?file=%2Fsrc%2Fmain.tsx%3A61%2C1-86%2C4

### Version

r151

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows

**Comment by Mugen87** [comment]
You find an explanation for this issue at stackoverflow: https://stackoverflow.com/questions/44989568/three-js-plane-doesnt-cast-shadow

You can solve this issue by using thing boxes or (if you want to retain the planes) try to configure the `shadowSide` material property: https://jsfiddle.net/7wbsjzdt/1/

**Comment by rwjCxgsy** [comment]
> You find an explanation for this issue at stackoverflow: https://stackoverflow.com/questions/44989568/three-js-plane-doesnt-cast-shadow
> 
> You can solve this issue by using thin boxes or (if you want to retain the planes) by configuring the `shadowSide` material property: https://jsfiddle.net/xdLko6ma/


Thank you
