### ISSUE TITLE
Creative Commons Attribution 3.0 License used by a shader

### ISSUE THREAD

**Issue by ben4d85** [mrdoob/three.js#26571]
### Description

As part of auditing the npm packages we use, we have used a tool called FOSSA to run an automated check of the packages in our project.

The check revealed that [examples/jsm/shaders/FilmShader.js](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/shaders/FilmShader.js) uses a Creative Commons Attribution 3.0 License.

Since three.js is marked as using an [MIT license](https://github.com/mrdoob/three.js/blob/dev/LICENSE), I feel it is worth pointing this out, so that you can decide how to resolve it.

### Reproduction steps

1. Open the file https://github.com/mrdoob/three.js/blob/dev/examples/jsm/shaders/FilmShader.js
2. Line 17 states: "This version is provided under a Creative Commons Attribution 3.0 License"

### Code

From https://github.com/mrdoob/three.js/blob/dev/examples/jsm/shaders/FilmShader.js

```js
/**
 * Film grain & scanlines shader
 *
 * - ported from HLSL to WebGL / GLSL
 * https://web.archive.org/web/20210226214859/http://www.truevision3d.com/forums/showcase/staticnoise_colorblackwhite_scanline_shaders-t18698.0.html
 *
 * Screen Space Static Postprocessor
 *
 * Produces an analogue noise overlay similar to a film grain / TV static
 *
 * Original implementation and noise algorithm
 * Pat 'Hawthorne' Shearon
 *
 * Optimized scanlines + noise version with intensity scaling
 * Georg 'Leviathan' Steinrohder
 *
 * This version is provided under a Creative Commons Attribution 3.0 License
 * http://creativecommons.org/licenses/by/3.0/
 */

const FilmShader = {
```

### Version

three@0.150.1

**Comment by Mugen87** [comment]
Thanks for bringing this up!

TBH, I will never understand why somebody uses a CC license for code. On top of my head I would say we remove this code from the repository and replace it with different implementation. It seems there are a couple of film grain shaders with compatible license out there.

**Comment by donmccurdy** [comment]
I am not a lawyer, but it is OK for dependencies of an MIT-licensed project to have other (_compatible_) licenses. CC-BY is a not an ideal one though, as there may be some ambiguities around its application to software. If we are comfortable replacing the code I am in favor of that as well.
