### ISSUE TITLE
map_fragment has missing parts on ShaderChunk

### ISSUE THREAD

**Issue by hamitaksln** [mrdoob/three.js#26587]
### Description

I've developed a custom shader with replacing current fragment shader. I'm using parseIncludes to parse whole fragment and replace some parts for myself. So the shader was working on version 0.149.0 and I wanted to update 0.155.0, I noticed that shader is not working anymore and wanted to deep dive into that. I saw there were little changes like `vUv` is `vMapUv` anymore but fixing that didn't work. I've checked my parseIncludes functions and see it using ShaderChunk. When I checked the ShaderChunk, I see map_fragment has missing parts.
![image](https://github.com/mrdoob/three.js/assets/23298031/7f6b310e-be7b-4fb4-98db-83bd3e009094)

So because of this I cannot make my shader works again in v155. 

### Reproduction steps

1. Import ShaderChunk from "three"
2. Check `map_fragment` 
3. You will see it's not matching with actual `map_fragment`

### Code

```js
const pattern = /#include <(.*)>/gm;

function parseIncludes(string) {
  function replace(_, include) {
    var replace = ShaderChunk[include];
    return parseIncludes(replace);
  }
  return string.replace(pattern, replace);
}
```

### Live example

* [stackblitz-latest-release](https://stackblitz.com/edit/three-js-start-3gjn7k?file=index.ts)

### Version

r155

**Comment by Mugen87** [comment]
The missing inline sRGB decode for video textures will be restored with the next release. In `dev`, the chunks looks like so:

https://github.com/mrdoob/three.js/blob/c849b5da3cb56aff580716450563c6f95f0fb458/src/renderers/shaders/ShaderChunk/map_fragment.glsl.js#L1-L17

If you are still having issues with upgrading then please use the [forum](https://discourse.threejs.org/) first. 

In general we can't guarantee that the shader chunks always keep their structure. If things change, you have to update your app-level modifications as well.

**Comment by hamitaksln** [comment]
I don't have a problem with things changing, the issue is here map_fragment.glsl.js content is not matching with THREE.ShaderChunk.map_fragment. So I cannot parse includes with right way. Please check the stackblitz example. Thanks for details.

**Comment by hamitaksln** [comment]
This is fixed on r156.
