### ISSUE TITLE
ShapeGeometry without uvs, normals

### ISSUE THREAD

**Issue by gewesp** [mrdoob/three.js#26595]
### Description

We're using ShapeGeometry in a very simple 2D context.  We don't need normal vectors nor UVs.

### Solution

A constructor parameter to prevent the creation of normals and UVs.

### Alternatives

Don't compute them by default and require an explicit computeVertexNormals() to do so.  But this would break backwards compatibility.

### Additional context

PR can be provided.

**Comment by mrdoob** [comment]
```js
geomerry.deleteAttribute( 'normal' );
geometry.deleteAttribute( 'uv' );
```

**Comment by Mugen87** [comment]
> Don't compute them by default and require an explicit computeVertexNormals() to do so. But this would break backwards compatibility.

I'm afraid a change like this is not acceptable. For your specific use case, I suggest you create custom geometry generator.

**Comment by gewesp** [comment]
> > Don't compute them by default and require an explicit computeVertexNormals() to do so. But this would break backwards compatibility.
> 
> I'm afraid a change like this is not acceptable. For your specific use case, I suggest you create custom geometry generator.

Yep, that's why I put it under 'alternatives'---The preferred solution mentioned in the issue is to add a new constructor parameter which would maintain backwards compatibility AFAICS.  The implementation would be rather trivial I think.  

But I do understand that our use case is rather special.
