### ISSUE TITLE
Camera rotation getting reset when i use orbit controls three.js

### ISSUE THREAD

**Issue by aakashpdrl** [mrdoob/three.js#26590]
### Description

I am using three js to view 360 images, i have created sphere and overlay an 360 image texture on the sphere, i set camera rotation to the image center, but every time I rotate image, orbit controller resetting the camera rotation to (0,0,0) code is attached, please help me out thanks in advance.

### Reproduction steps

1.Overlay 360 texture image on sphere and set rotation to image center.
2.Rotate image, this will rotate image from center. getting reset on start of rotation.

### Code

```js
const texture = loader.load(img.url, (texture) => {
  texture.wrapS = THREE.RepeatWrapping;
  sphere.material.map = texture;
  sphere.material.needsUpdate = true; // Ensure material updates

  sphere.material.map.dispose();
  
  controls.object.rotation.set(-2.3553, 1.57, 2.3553)
  //tried to camera.rotation as well
  setLoading(false)
});
```

### Live example

https://github.com/mrdoob/three.js/assets/89395069/8c9897e9-b172-488f-a21c-97c7ed2a30dd

### Version

r154

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Please ask for help at the [forum](https://discourse.threejs.org/).
