### ISSUE TITLE
I would be very happy about more examples with wgslFn

### ISSUE THREAD

**Issue by Spiri0** [mrdoob/three.js#26600]
### Description

Currently there is no documentation for the node system and only very few examples. For direct communication between wgsl and the node system, I only know the two mini examples from the webgpu materials example. I think it's good that these are so small, because that's how I was able to understand very quickly how they work. It doesn't need any large, complex examples, just small examples in which the elementary function is conveyed and that's exactly what the two wgslFn and the two tslFn do in the webgpu materials example and that's why I find them so good.

I consider examples of processing data within a shader to be less important, because there are many examples and options with online editors on the web. The problem is the interface
node system <-> wgsl.

### Solution

I have slightly modified an example from the weggpu materials example to illustrate how I imagine it

```
import {uv, texture} from 'three/nodes';
```

```
const textureLoader = new THREE.TextureLoader(); 
const uvTexture = textureLoader.load( './textures/uv_grid_opengl.jpg' ); 
const textureNode = texture( uvTexture ); 


const textureSampleParams{ 
    inputTexture: textureNode, 
    textureSampler: textureNode,
    uv: uv()
}
const getWGSLTextureSample = wgslFn(`
    fn getWGSLTextureSample( 
        inputTexture: texture_2d<f32>, 
        textureSampler: sampler, 
        uv: vec2<f32> 
    ) -> vec4<f32> {

        return textureSample( inputTexture, textureSampler, uv );
    }
`);


const material = new MeshBasicNodeMaterial();
material.colorNode = getWGSLTextureSample(textureSampleParams);
```

This made it easy for me to learn basic workings of the node system. By doing this I understood these elements: (MeshBasicNodeMaterial, texture, uv, colorNode, wgslFn, sampler)
I also learned how to change them at runtime. There is a lot of valuable information in this small example from the webgpu materials example.
An analogous example can be made for the positionNode with "textureLoad". I learned that too.

I would like a similarly minimal compute shader example in which a texture is created and saved. Here is a pure wgsl code that illustrates what I mean:

```
//compute shader
@group(0) @binding(0) var outputTexture: texture_storage_2d<rgba8unorm, write>;

@compute 
@workgroup_size(16, 16, 1) 
fn computeTexture(@builtin(global_invocation_id) id: vec3<u32>) {

    var texelCoord: vec2<u32> = id.xy; 
    var uv: vec2<f32> = vec2<f32>(f32(texelCoord.x) / 511.0, f32(texelCoord.y) / 511.0); 
    var color: vec4<f32> = vec4<f32>(uv.x, uv.y, 0.5, 1.0);
     
    textureStore(outputTexture, texelCoord, color); 
}


//fragment shader
@group(0) @binding(0) var inputTexture: texture_2d<f32>;
@group(0) @binding(1) var textureSampler: sampler;

@fragment
fn main(@location(0) uv: vec2<f32>) -> @location(0) vec4<f32> {
    return textureSample(inputTexture, textureSampler, uv);
}

```
A minimal example in pure wgsl code in which a compute shader creates a simple texture and then a fragment shader reads it and outputs it. The fragment shader is already explained by the mini example above from the webgpu materials example. This example with the compute shader would already be a blueprint to replace everything that had to be done with renderTargets in glsl in webgpu with compute shaders.
I know the webgpu compute example. But that is a bit more extensive because it tries to show how to use javascript code instead of shader code. I think that's a good thing, but it seems to me like the second step before the first is done. Shaders aren't bad! But if you absolutely try to avoid them, then they become something negative in people's minds. The node system is a very good thing! It should therefore also highlight its strengths in conjunction with wgslFn where the full power of wgsl is at your fingertips. I think it will be easier to derive wgsl free examples from this than to consider which ones from the outset.

### Alternatives

I think I covered that in the solutions field. I just wish for more small examples in which I can see the analogies between wgsl code and node system. That helps a lot.

**Comment by Spiri0** [comment]
I took a look at the nodes.js in the three directory (three/examples/jsm/nodes). It's really impressive what you've done there. It reminds me of blender's material node system. If the node system were to develop in such a way that the node systems of three.js and blender would eventually become compatible at some day, that would probably be a gigantic evolutionary step. Being able to use models with their shaders in three.js instead of having to bake the shaders to textures in blender would be like evolving from WebGL2 to WebGPU.

I've been trying to find something that matches the workgroup_size. And something to help me understand how I could use the storage node to store a texture.

line 122/123 in nodes.js r155
```
// gpgpu
export { default as ComputeNode, compute } from './gpgpu/ComputeNode.js';
```

Here I would have guessed something like a workgroup_size element and other compute shader specific elements like the textureStore. It seemed obvious to me to suspect compute shader specific elements there.
Is it possible to influence the workgroup_size in r155?
Can my mini example suggestion from above with the computer shader currently be implemented at all with r155?

**Comment by sunag** [comment]
> Is it possible to influence the workgroup_size in r155?

There is an Array in `ComputeNode` used for `workgroupSize`, is possible to test it in `webgpu_compute` example.

https://github.com/mrdoob/three.js/blob/288d41156c17bb7a35b7445ecf2867d88ab04587/examples/webgpu_compute.html#L101

```js
computeNode = computeShaderNode.compute( particleNum, [ 16, 1, 1 ] );

// The result shoud be: @workgroup_size( 16, 1, 1 )

```

**Comment by Spiri0** [comment]
I experimented a little with the workgroup_size. I recreated your compute example in codePen.

https://codepen.io/Spiri0/pen/rNoNOWL

I've been thinking a lot about how saving textures with the node system could work for the past few days, but I haven't really gotten any further. I then took a look at how babylon.js does this:

https://github.com/Popov72/OceanDemo

in: **assets/ocean**   are the wgsl compute shaders
and in:
**scenes**    are they used.

I also built an ocean in three.js 3 months ago with the same math logic, but in WebGL2 with 6 renderTargets. All the ocean models are essentially based on two dissertations that I know. I would like to port my ocean to WebGPU and therefore my great interest in the possibility of being able to save textures with wgsl in three.js.

I can't estimate to what extent this is currently possible with the r155, since I don't know of any example in which textures are saved. In my case, 6 compute shaders would be executed one after the other, because the compute shaders in turn depend on the texture results of their predecessor compute shader.

What I like is that babylon.js uses wgsl code in its compute shaders even though babylon.js has a node system.
Personally, when I'm working with more complex mathematical equations, I find using shader code more comfortable. But that is my very subjective preference. I think it would be nice to be able to use wgsl code in compute shaderNodes. The shader nodes make my work in three.js easier. But the possibility of being able to use wgsl code in shaderNodes also makes work easier because the number of wgsl examples on the web is already greater.

I hope the information here can be an inspiration if what I want is not yet possible with the r155 and further development work is necessary.

**Comment by sunag** [comment]
I can be checking the implementation of a `textureStore` in `TSL`, it would certainly be useful for computing applications, currently we have `storage()` in `TSL`, which could already animate the vertices of ocean directly leaving the finer details for fragment rendering, but this is just a possible approach.

**Comment by Spiri0** [comment]
The many textures are not necessary for the vertex displacements but for IFFT (inverse fast fourier transformations). It is not possible to calculate the final displacement map with a single shader, since integrals have to be made again and again over entire value ranges of the respective predecessor shader texture. Such an effort is necessary for real water waves, but it is worth. I like physics and mathematics.
 
The power of the compute shaders lies in their ability to make what I'm doing now with a chain of renderTargets in WebGL2 much more efficient in WebGPU. I will then upload the ocean to github.

But then I practice patience and look forward to what you will construct there.
