### ISSUE TITLE
Examples: Add a example for `OutlineEffect.js` module.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#26610]
### Description

`OutlineEffect.js` module has no example display.

### Solution

Add example for `OutlineEffect.js` module.

### Alternatives

None

**Comment by Mugen87** [comment]
The MMD examples use `OutlineEffect`.

**Comment by linbingquan** [comment]
> The MMD examples use `OutlineEffect`.

Yes, I think users only see the source code to know how to use, even the useful `userData.outlineParameters.visible`

```js
material.userData.outlineParameters = {
  visible: false,  //  User does not want to render it
};
```

TBH, I was try write toon material demo with `OutlineEffect` and I does not want to render something with `OutlineEffect`.
The current `OutlineEffect` examples does not use `material.userData.outlineParameters.visible` by now.

I searched `outlineParameters` keyword in code repository, only `MMDLoader.js` module is used.

**Comment by Mugen87** [comment]
Would adding a documentation page for `OutlineEffect` help?

**Comment by linbingquan** [comment]
> Would adding a documentation page for `OutlineEffect` help?

I am not sure documentation page is useful.

In my opinion, a good example would be more intuitive and easier to learn and use on a basic level by now.

Only `OutlineEffect.js` without example by now...

|Effect Module|Example File|
|-|-|
|OutlineEffect.js|None |
|AnaglyphEffect.js|https://threejs.org/examples/webgl_effects_anaglyph.html|
|AsciiEffect.js|https://threejs.org/examples/webgl_effects_ascii.html|
|ParallaxBarrierEffect.js|https://threejs.org/examples/webgl_effects_parallaxbarrier.html|
|PeppersGhostEffect.js|https://threejs.org/examples/webgl_effects_peppersghost.html|
|StereoEffect.js|https://threejs.org/examples/webgl_effects_stereo.html|

**Comment by Mugen87** [comment]
`OutlineEffect` was specifically added for MMD / `MeshToonMaterial`. Compared to the other effects, I'm not sure a usage outside of this context makes sense.

@takahirox What do you think?

**Comment by takahirox** [comment]
**Why MMD needs `OutlineEffect`**

MMD uses "rendering backface of little bigger model" technique for drawing outline. Some MMD models expect this outline technique. For example only sleeves of cloths have front face material (back-face culling) and the inside of them are expected to be rendered as black with the outline.

With outline

![image](https://github.com/mrdoob/three.js/assets/7637832/93da1cc8-6c85-49b4-a5c9-592e584456cb)

Without outline

![image](https://github.com/mrdoob/three.js/assets/7637832/0cd020b4-7602-4f55-8c55-e2618e239561)

This isn't doable with the edge-detection postprocessing approach. So I hope we can keep `OutlineEffect`.

**`OutlineEffect` documents and API**

I can't deny that the current `OutlineEffect` API is a bit too special in Three.js and specific to MMD. And honestly the implementation is a bit too way more complicated than it needs to be.

I'm thinking of reimplementing `OutlineEffect` for more Three.js API friendly. (I already have an idea but just lack of time.) We may document when we reimplement it.

**Comment by Mugen87** [comment]
> I'm thinking of reimplementing OutlineEffect for more Three.js API friendly. (I already have an idea but just lack of time.) We may document when we reimplement it.

Sounds good! In this case, it's okay to not add a documentation page or further examples for the existing `OutlineEffect`.
