### ISSUE TITLE
Docs Typo

### ISSUE THREAD

**Issue by mgroth0** [mrdoob/three.js#26615]
### Description

In the constructor notation for https://threejs.org/docs/index.html#api/en/math/Matrix3, `n22` is duplicated (the second one should say `n23`)

### Reproduction steps

N/A

### Code

N/A

### Live example

N/A

### Version

latest

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
Could catch! Would you like to fix this with a PR?
