### ISSUE TITLE
Using InstancedMesh with ShaderMaterial does not work

### ISSUE THREAD

**Issue by jaspermolgvits** [mrdoob/three.js#26612]
### Description

I'm completely unable to set the positions of an InstancedMesh's instances when using ShaderMaterial. Updating the instance matrix doesn't seem to help either. Am I missing something?

### Reproduction steps

1. Create a ShaderMaterial.
2. Create an InstancedMesh with it and set positions for the instances.
3. Add it to the scene and see it's all at 0,0,0 regardless of set positions.

### Code

```js
const geometry = new THREE.SphereGeometry(0.1, 32, 32);

const shaderMaterial = new THREE.ShaderMaterial({
  vertexShader: `
    void main() {
      gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
    }
  `,
  fragmentShader: `
    void main() {
      gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
    }
  `
});


const instancedMesh = new THREE.InstancedMesh(geometry, shaderMaterial, 100);

for (let i = 0; i < instancedMesh.count; i++) {
  const matrix = new THREE.Matrix4();
  matrix.setPosition(Math.random() * 10 - 5, Math.random() * 10 - 5, Math.random() * 10 - 5);
  instancedMesh.setMatrixAt(i, matrix);
}

scene.add(instancedMesh);
```

### Live example

* [Switch between ShaderMaterial and MeshBasicMaterial](https://codesandbox.io/s/shadermaterial-nv6kgr?file=/src/index.js)

### Version

r155

**Comment by Mugen87** [comment]
You are some GLSL in your custom code. Consider to use the shader chunks of the library like so:

https://codesandbox.io/s/shadermaterial-forked-w8jmft

If you don't want to do that, you have to inline the code like so:
```
vec4 mvPosition = vec4( position, 1.0 );

#ifdef USE_INSTANCING

	mvPosition = instanceMatrix * mvPosition;

#endif

mvPosition = modelViewMatrix * mvPosition;

gl_Position = projectionMatrix * mvPosition;
```

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.
