### ISSUE TITLE
gltf file load error,fltf文件加载报错

### ISSUE THREAD

**Issue by 2513483494** [mrdoob/three.js#26633]
### Description

import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import model from '../hand_low_poly/scene.gltf';
   
const loader = new GLTFLoader();

    loader.load(model, (gltf) => {
      scene.add(gltf.scene);
    }, undefined, (error) => {
      console.error(error);
    });

### Reproduction steps

1.https://sketchfab.com/3d-models/hand-low-poly-d6c802a74a174c8c805deb20186d1877#download 下载资源
2.文件夹放入项目文件
3.import model from '../hand_low_poly/scene.gltf'; 引入gltf文件
4.
const loader = new GLTFLoader();

    loader.load(model, (gltf) => {
      scene.add(gltf.scene);
    }, undefined, (error) => {
      console.error(error);
    });
5. 报错

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

<img width="779" alt="截屏2023-08-23 16 52 51" src="https://github.com/mrdoob/three.js/assets/48058550/ca416eef-6c74-4a29-a11a-f8ab8134daa3">
<img width="871" alt="截屏2023-08-23 16 53 15" src="https://github.com/mrdoob/three.js/assets/48058550/7df17466-b694-4c7b-9c7a-249a25b6181b">

### Version

"three": "^0.155.0"

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
I could import both .glb and .gltf version of the asset into the [three.js editor](https://threejs.org/editor/). So there must be something wrong with your code.

Please let you help at the [forum](https://discourse.threejs.org/).
