### ISSUE TITLE
Store both original and sanitized node names in FBXLoader

### ISSUE THREAD

**Issue by janulis** [mrdoob/three.js#26637]
### Description

I've noticed that the FBXLoader does not include the original node names when loading FBX files. The current implementation only provides sanitized node names, which makes it difficult to identify and manipulate specific nodes in the loaded FBX file based on their original names.

### Solution

I would like the FBXLoader to store both the original node names and the sanitized node names from the FBX file and make them accessible in the resulting three.js objects. This would allow users to easily identify and manipulate specific nodes in the loaded scene using either the original or sanitized node names, depending on their needs.

### Alternatives

One possible alternative is to modify the FBXLoader source code and create a custom version that includes the original node names in addition to the sanitized names. However, this is not an ideal solution because it requires maintaining a separate version of the loader and manually updating it when new versions of three.js are released.

### Additional context

Including both the original and sanitized node names in the FBXLoader would provide a more complete representation of the FBX file structure and improve usability for developers working with FBX files in their projects. This feature would give developers more flexibility in choosing how they want to identify and manipulate nodes in the loaded scene.

**Comment by Mugen87** [comment]
Would you be okay if the loader stores the additional information in the `Object3D.userData` property? 

Other loaders rely on `userData` fields for similar use cases.

**Comment by janulis** [comment]
Thanks for the quick response!

> Would you be okay if the loader stores the additional information in the Object3D.userData property?
>
> Other loaders rely on userData fields for similar use cases.

Yes, sounds good to me.

**Comment by Mugen87** [comment]
Would you like to file a PR?

**Comment by janulis** [comment]
> Would you like to file a PR?

OK, I will do that.
