### ISSUE TITLE
Rollup: Build `WebGPURenderer` module to single file.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#26634]
### Description

Build the `WebGPURenderer` module to a single file to users, it will make the browser network request time shorter.

Single file network info:
![image](https://github.com/mrdoob/three.js/assets/23699926/0a5e473c-2b91-496b-a958-9ee28144df62)

Current network info:
![image](https://github.com/mrdoob/three.js/assets/23699926/6241ac5f-9b32-4d1e-b0cb-6745400cf1db)

### Solution

Add the rollup config.

```js
{
	input: 'examples/jsm/renderers/webgpu/WebGPURenderer.js',
	plugins: [
		addons(),
		glsl(),
		header()
	],
	output: [
		{
			format: 'esm',
			file: 'build/webgpu.module.js' // file name to be announced
		}
	]
}
```

### Alternatives

Users build the 'WebGPURenderer' module themselves.

### Additional context

`WebGPURenderer` single file will make the browser network request time shorter.

**Comment by CodyJasonBennett** [comment]
Have you seen #16440 or #25947?

**Comment by linbingquan** [comment]
> Have you seen #16440 or #25947?

Yes, I was see the #26634 when I opened this issue. Maybe I should closed it...

Sorry about it.
