### ISSUE TITLE
r155 THREE.PointLight only accepting "color" and "distance"

### ISSUE THREAD

**Issue by ERS-Coder** [mrdoob/three.js#26646]
### Description

in r155 I try using the PointLight feature. The light shows only when I enter "color" and "distance"... If I try entering all four (4) parameters, including "intensity" and "decay", The PointLight fails to show.

With only "color" and "distance" the resulting light is very intense, which limits the scenarios in which it can be use now.

### Reproduction steps

1. instantiate a PointLight in your 3D canvas...
2. new THREE.PointLight(0xffffff, 10000); -------> this works
3. new THREE.PointLight(0xffffff, 1, 10000, 2); ------> this doesn't work

### Code

var light = new THREE.PointLight(0xffffff, 10000);
light.visible = true;
light.position.set(42,250,380);
scene.add(light);

### Live example

[* [[jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)](https://www.culturetravelvr.com/bckend/promenadeIndex/massa001.php)]
(https://jsfiddle.net/estiven_sierra/cg7yL61o/57/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)
*

### Version

r155 or r156

### Device

Desktop

**Comment by Mugen87** [comment]
With the latest release, the unit of a point lights intensity is candela. A value of `1` is way too low for most scenarios which means the light does not visually contribute anything to the scene.

BTW: Your live example uses `MeshBasicMaterial` which does not respond to lights in general. It's a so called unit material. If you need more help with lighting, please use the [forum](https://discourse.threejs.org/).
