### ISSUE TITLE
After v0.137 Some module export has conflict on examples/jsm 

### ISSUE THREAD

**Issue by dellwatson** [mrdoob/three.js#26660]
### Description

After version 0.137 has problem. 
I tried to import one of the example/jsm module which is Curve and it is result in undefined since v0.138 - latest
even though the file is exist there.

https://codesandbox.io/s/restless-platform-7p9nrs?file=/src/store.js
I cannot import three/examples/jsm/curves might affect the whole  some of jsm

```
on migration 137-138 
https://github.com/mrdoob/three.js/wiki/Migration-Guide#137--138
has  update The node material in examples/jsm/nodes has been replaced with a new implementation. 
```

seems that upgrade is the culprit, so i will try to check commit there soon.

### Reproduction steps

1. install three on version above 0.137+
2. import { Curves } from "three/examples/jsm/curves/CurveExtras"
3. it will show undefined

### Code

```js
import { Curves } from "three/examples/jsm/curves/CurveExtras";

  // version 138 -> latest will shows undefined
  console.log(Curves, "curves x");
```

### Live example

* [quick-reproduction-to-check](https://codesandbox.io/s/restless-platform-7p9nrs?file=/src/store.js)

### Version

0.138 -> 0.155

**Comment by ycw** [comment]
```diff
- import { Curves } from "three/examples/jsm/curves/CurveExtras";
+ import * as Curves from "three/examples/jsm/curves/CurveExtras";
```

https://github.com/mrdoob/three.js/blob/b447ff2911cbefcd650df5a18a905e7df882fc78/examples/jsm/curves/CurveExtras.js#L407-L422
r155 🫴🏻

**Comment by Mugen87** [comment]
#23402 changed the import syntax. 

I'll updated the migration guide to avoid similar confusion in the future.
