### ISSUE TITLE
Editor: Open editor directly without navigating to its directory.

### ISSUE THREAD

**Issue by AmrAbdelghany** [mrdoob/three.js#26675]
### Description

Hello everyone,

I am working on building an AR studio using three.js and thought I could use the editor as it is and the build on top of it. I have been trying to open the editor directly after running the project but it opens the directory tree first and then I need to navigate to the editor directory to open it. 

I tried editing the package.json file to do, it opens the editor directory but without showing anything as it is trying to access files from the three.js directory and it gives an error that some files could not be found.

Kindly advise how to proceed.

Thank you

### Solution

What do I need to update/edit for the editor to work directly when I run the project?

### Alternatives

What files do I need to copy if I create another project for the editor only? What do I need to replace and what do I need to change?

**Comment by Mugen87** [comment]
Please ask at the [forum](https://discourse.threejs.org/) for help.
