### ISSUE TITLE
FileLoader.js fetch(…).then(…).catch(…).finally(...) finally is not a function. in some android devices.

### ISSUE THREAD

**Issue by DisenLi** [mrdoob/three.js#26676]
### Description

.finally() doesn't supported by all of browsers.
use then() fixed this bug?

### Reproduction steps

in some old android devices.

### Code

.finally( () => {
this.manager.itemEnd( url );
} );

### Live example

nothing

### Version

r154

### Device

Mobile

### Browser

Chrome

### OS

Android

**Comment by Mugen87** [comment]
> in some old android devices.

Older environments do not support `finally()` correctly. Please try using a polyfill.
