### ISSUE TITLE
glTF asset not correctly view frustum culled.

### ISSUE THREAD

**Issue by calmheaded** [mrdoob/three.js#26674]
### Description

![image](https://github.com/mrdoob/three.js/assets/22089884/bad6332d-8a2d-4cef-9b88-e613bb084979)

Within the angle range of the GLB model camera, the leaves of the model can be displayed at a long distance, but disappear when closer. In the upper left corner, you can see that the angle between the camera and the far section is not a problem. This problem has occurred. Is it the reason for the glb shader or the reason for the model vertex normals.

![image](https://github.com/mrdoob/three.js/assets/22089884/60199ae5-3b92-40e0-9054-d7d063b24f3b)

### Reproduction steps

![image](https://github.com/mrdoob/three.js/assets/22089884/bad6332d-8a2d-4cef-9b88-e613bb084979)
normal

![image](https://github.com/mrdoob/three.js/assets/22089884/60199ae5-3b92-40e0-9054-d7d063b24f3b)
As we approached, the leaves were gone, and in the upper left corner, we could see that there was no problem with the camera's auxiliary line. Should it be a model issue or a GLB issue

Model address
https://yuanshu-3d-model-demo.oss-cn-beijing.aliyuncs.com/zhinengkefu/model/jiemi.glb

### Code

```js
				const dracoLoader = new DRACOLoader()
				dracoLoader.setDecoderPath('js/libs/draco/')
				const gltfLoader = new GLTFLoader()
				gltfLoader.setDRACOLoader(dracoLoader)
				gltfLoader.load(
					'models/模型测试/解密后.glb',
					function (gltf) {
						const model = gltf.scene // 获取模型的根对象
						console.log(model, 'model1')
						model.traverse(child => {
							if (child.isMesh) {
								const geometry = child.geometry

							}

						})
```

### Live example

[* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)
](https://jsfiddle.net/aday2023/z8o9c4j0/)

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/22089884/2c879b09-7e69-49c0-b433-9d591a07698e)

If it's a GLTF source code issue, what should be changed

### Version

145dev

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
As a workaround, disabling view frustum culling for the asset solves the issue:
```
model.traverse(child => {
    if (child.isMesh) {
        child.frustumCulled = false;
    }
 })
```

**Comment by Mugen87** [comment]
@calmheaded Can you reproduce the issue with this version of the asset? I have applied some clean up in the object's hierarchy in Blender and then export to glb again.

[jiemi_new.glb.zip](https://github.com/mrdoob/three.js/files/12484459/jiemi_new.glb.zip)

**Comment by calmheaded** [comment]
[jiemi_new.glb.zip](https://github.com/mrdoob/three.js/files/12484459/jiemi_new.glb.zip)  
This model has no issues and can be displayed normally
![image](https://github.com/mrdoob/three.js/assets/22089884/ffec60d3-ccdf-4567-a136-04dc3aef55df)



Thank you very much

**Comment by RemusMar** [comment]
If you center the pivots for those 7 meshes and re-export the GLTF file, you don't need anything else.

**Comment by RemusMar** [comment]
Another solution is to repack the GLTF file with **meshoptimizer** (gltfpack.exe).
So you might be right about some buggy Sketchfab exporter.
