### ISSUE TITLE
AR session origin seems to jump after placement

### ISSUE THREAD

**Issue by marwie** [mrdoob/three.js#26686]
### Description

After placing some content in AR the session orientation / position seems to change after a few seconds

I'm not yet sure if this is a bug in three or actually in chrome. 
Maybe someone can confirm if the issue also happens on another device and / or if happens on other chrome versions than 116.0.5845.164 as well. I already tried on canary 118.0.5987.0 with the same result

I can't really reproduce it in modelviewer for example

### Reproduction steps

1. open https://threejs.org/examples/webxr_ar_hittest.html on android chrome 
2. enter AR and place a cylinder
3. wait a few seconds
4. see that cylinder disappears and is now to the right (in another position)

### Live example

https://threejs.org/examples/webxr_ar_hittest.html

### Screenshots

https://github.com/mrdoob/three.js/assets/5083203/b4fdb210-e3c0-4b4d-a0ba-c5516a0d94fe

### Version

155

### Device

Mobile Pixel 6a

### Browser

Chrome

### OS

Android

**Comment by Mugen87** [comment]
This is a Chromium bug. It is already reported at the respective bug tracker:

https://bugs.chromium.org/p/chromium/issues/detail?id=1475680

**Comment by marwie** [comment]
Oh perfect! Thanks for the fast reply!

**Comment by Mugen87** [comment]
Let's tackle the issue at the Chromium bug tracker.
