### ISSUE TITLE
Customizable cache implementation

### ISSUE THREAD

**Issue by mistic100** [mrdoob/three.js#26685]
### Description

Currently the loaders uses the global Cache instance which is a very basic implementation. I would like to have a cache with a maximum number of items and a TTL.

I don't think such specificities should be included in ThreeJS itself but providing a simple way to change the cache implementation seems a good compromise.

### Solution

I have two ideas

1. Add a "cache" parameter to the loaders, it will use the default cache if not provided, similarly to the loading manager.  
It requires to modify every loader.

2. Integrate to cache mechanism to the loading manager.  
It ony requires to modify the base FileLoader.

The default loading manager would look like:

```js
getCache(url) {
  Cache.get(url);
},

addCache(url, data) {
  Cache.add(url, data);
},
```

Users will be able to provide a custom loading manager implementation and overload the cache methods.

### Alternatives

Overwrite the `Cache.add` and `Cache.get` methods in my library. I don't really like that though in case my library user also uses Three for something else. 

### Additional context

If this proposal is accepted I am willing to submit a PR with either option.

**Comment by gkjohnson** [comment]
Is there a reason you can't implement a cache system on top of the existing loaders? Ie write a cache system around the OBJLoader or GLTFLoader to cache preparsed geometry and mesh hierarchies. The THREE.Cache system is fairly limited and only supports strings and buffers so it's not all that optimal as it is.

**Comment by mistic100** [comment]
I actually only load and cache textures.

Of course I can write my own cache system, but why then having one implemented in the first place ?

**Comment by Mugen87** [comment]
The internal cache system handles basic use cases. The project's components are in general designed to be lean and maintainable so simple implementations are favored against more complex ones.

In earlier version of `three.js`, users could do this (see #16378):
```js
THREE.Cache = THREE.CustomCache;
``` 
With modules, this doesn't work anymore. 

I'm not in favor to add a cache parameter to each loader. Enhancing the loading manager like suggested in option 2 sounds more appropriate to me. However, I wonder if there is another option to globally replace the default cache 🤔 .

**Comment by mistic100** [comment]
option 3 to replace globally in a way compatible with ESM :

```js
export const Cache = {
  enabled: false,

  files: {},

  manager: null,

  setManager(manager) {
    this.manager = manager;
  },

  add(key, data) {
    if (this.manager) {
      this.manager.add(key, data);
    } else {
      this.files[key] = data;
  },

  get(key) {
    if (this.manager) {
      return this.manager.get(key);
    } else {
      return this.files[key];
  },

  // etc...
}
```

**Comment by Mugen87** [comment]
I assume `manager` would be something like `CacheManager`, correct?

Um, I like this design! How about we make it bit more explicit so we don't need all these `if` statements:

```js
class CacheManager {

	constructor() {

		this.files = {};

	}

	add( key, file ) {

		this.files[ key ] = file;

	}

	get( key ) {

		return this.files[ key ];

	}

	remove( key ) {

		delete this.files[ key ];

	}

	clear() {

		this.files = {};

	}

}

//

const Cache = {

	enabled: false,

	manager: new CacheManager(),

	setManager: function ( manager ) {

		this.manager = manager;

	},

	add: function ( key, file ) {

		if ( this.enabled === false ) return;

		// console.log( 'THREE.Cache', 'Adding key:', key );

		this.manager.add( key, file );

	},

	get: function ( key ) {

		if ( this.enabled === false ) return;

		// console.log( 'THREE.Cache', 'Checking key:', key );

		return this.manager.get( key );

	},

	remove: function ( key ) {

		this.manager.remove( key );

	},

	clear: function () {

		this.manager.clear();

	}

};

export { Cache };
```
In this way, `CacheManager` defines a clear interface that apps can overwrite if necessary. What do you think?

I wonder if should export `CacheManager` so users can derive from the class which would a bit more clean from an OO perspective.

**Comment by mistic100** [comment]
> If you're already looking into writing even a little bit more of a complex caching system to keep memory under control you might want to consider something more robust.

Well this is exactly what I am doing, by searching a way to change the cache system without rewriting all my loaders calls.

I admit I have no knowledge (or interest) of other things beside textures.

---

Mugen87 interation on my proposal is great, if the team is okay with this design I will create a PR. If you prefer to enhance the existing cache I will leave it to you, because it obviously involves a lot of conception, and for things I don't master.

**Comment by mistic100** [comment]
I realized that my cache would need to be more complex than that, in a way that is not achievable by having only the request url, I will need to have multiple (unkown number) images sharing some kind of "cache key" and manage the TTL by batch.

So... a cache called inside the loader does not work. Sorry for the hassle :-(

**Comment by Mugen87** [comment]
In this case, let's close the issue until there is a larger demand for custom cache implementations. If so, we can reconsider the solutions discussed so far.
