### ISSUE TITLE
Support for BlockBench Models (JSON)

### ISSUE THREAD

**Issue by SilverPhoenixx** [mrdoob/three.js#26682]
### Description

The current ObjectLoader for loading JSON supports "JSON Object Scene format 4" but you cant load models from BlockBench in json format.

### Solution

Create a ObjectLoader specified to load blockbench models (.geo.json)

### Alternatives

I dont know any other alternatives.

**Comment by Mugen87** [comment]
`ObjectLoader` loads the internal JSON Object Scene format. These files are produces by the engine itself via the `toJSON()` method. `ObjectLoader` is not intended for all other JSON files include `geo.json`.

**Comment by gkjohnson** [comment]
The BlockBench format also looks like a proprietary DCC tool format similar to Blender's .blend or Maya's .ma. The project's wiki even [recommends other export formats from their tool](https://www.blockbench.net/wiki/guides/export-formats#recommended-formats-by-use-case) including glTF so it's already possible to load the content into three.js. I don't think there's a reason to support this format.

**Comment by SilverPhoenixx** [comment]
> The BlockBench format also looks like a proprietary DCC tool format similar to Blender's .blend or Maya's .ma. The project's wiki even [recommends other export formats from their tool](https://www.blockbench.net/wiki/guides/export-formats#recommended-formats-by-use-case) including glTF so it's already possible to load the content into three.js. I don't think there's a reason to support this format.

So its possible to load that .geo.json format without  converting the file to a .blend or .ma format?

**Comment by gkjohnson** [comment]
> So its possible to load that .geo.json format without converting the file to a .blend or .ma format?

I think if you need help getting a file into three.js the [forum](https://discourse.threejs.org/) is the best place to ask for help. But GLTF is the recommended format to use which BlockBench seems to support.

**Comment by SilverPhoenixx** [comment]
Yeah it supports GLTF, thats not the problem. But i want to create a project depending on currently existing files and they are in .geo.json. And because of ThreeJS didnt support that, i recommended that.

**Comment by gkjohnson** [comment]
As I mentioned above - the blockbench file format seems to be proprietary and otherwise undocumented. It's not designed or intended to be used as a portable format for other tools. You will have to convert the files as is recommended by the blockbench documentation.
