### ISSUE TITLE
Suggestion: Public the `WebGLAnimation.isAnimating` variable in `WebGLRenderer`

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#26684]
### Description

I don't wanna to maintain `isAnimating` variable about the current state of the animation, because it already exists when users use `renderer.setAnimationLoop()` function, but users can't get it now...

https://github.com/mrdoob/three.js/blob/8fde3e25fd869033a6ddd64a40f290c584486311/src/renderers/webgl/WebGLAnimation.js#L4

### Solution

Public the `isAnimating` variable in `WebGLAnimation.js`, after then public it  in `WebGLRenderer.js`.

### Alternatives

Users maintain the animation state variable independently, but this variable should not be necessary...

### Additional context

None.

**Comment by Mugen87** [comment]
I'm not sure this is a good idea. User could try to set the variable. Besides, an app should always not whether it's inside an animation loop or not. I don't think an additional status variable would be helpful.

**Comment by linbingquan** [comment]
Thank you for your reply.

> Regarding this, I don't think an additional status variable would be helpful.

Yes, I agree with you. I think this advice is not helpful for on-demand rendering.
But in some cases, exposing this property allows the user to do some logic directly, which can bring a little convenience.

For my following code, I would like to be able to get this `WebGLAnimation.isAnimating` state...

TBH, I try to write a small game, I think it should be rendering on demand (Of course it will be have many detail thing to handle), like `Tween` or `OrbitControls`.

Sample code for my current implementation:

```js
import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import * as TWEEN from "three/addons/libs/tween.module.js";

let isAnimating = false;

const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.addEventListener("change", requestRender);

window.addEventListener("keydown", () => {
  if (isAnimating === true) return;

  new TWEEN.Tween(mesh.position)
    .to(mesh.position.clone().add(new THREE.Vector3(1)), 1000)
    .start();

  requestRender();
});

function requestRender() {
  if (isAnimating === true) return;

  function animate() {
    const success1 = TWEEN.update();
    const success2 = controls.update();
    renderer.render(scene, camera);
    if (success1 === false && success2 === false) {
      renderer.setAnimationLoop(null);
      isAnimating = false;
    }
  }
  renderer.setAnimationLoop(animate);
  isAnimating = true;
}
```

Relative issue:  https://github.com/mrdoob/three.js/issues/23090

**Comment by Mugen87** [comment]
> But in some cases, exposing this property allows the user to do some logic directly, which can bring a little convenience.

The problem is that evaluating `WebGLAnimation.isAnimating` only works when the app makes use of `setAnimationLoop()`. Most apps don't do this but handle the animation loop by themselves. Regarding, I fear exposing `WebGLAnimation.isAnimating` will produce quite some confusion.
