### ISSUE TITLE
make Color accept strings that are numbers

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#26690]
### Description

this actually comes from a case in the user land, where they had a text input for the color value and fed it into Color constructor, and wondered why did it not work when they enter something like 0xFF0000 - it obviously did not work because it was passed as "0xFF0000" and not 0xFF0000.

### Solution

arguably this is not a 3js problem, however since Color already tries to be helpful and decodes strings like "#FF0000" into values I've figured that it maybe won't be much to ask for something like
```js
if(value.startsWith('0x') && !isNaN(parseInt(value, 16)) this.setHex(parseIne(value, 16)); /* this case */ else
if(!isNaN(parseInt(value)) this.setHex(parseInt(value)); /* decimal value */ else
```
right about [here](https://github.com/mrdoob/three.js/blob/dev/src/math/Color.js#L75)?

### Alternatives

these cases where users pass the numbers as strings just take too much attention away from actually interesting work otherwise 😔 every now and then I have to convert the numbers to actually be the numbers in js, and unless Color can be made a tiny bit smarter I will have to keep doing that, I guess? as well as everybody else.

**Comment by Mugen87** [comment]
>  however since Color already tries to be helpful and decodes strings like "#FF0000" into values I've figured that it maybe won't be much to ask for something like

Actually `Color` isn't helpful in this context since the usage of `#` only works inside a string. So parsing/decoding  "#FF0000" is the only way to interpret such (CSS style) color definitions.

The engine can't hide all type conversion from the user and I'm also not a fan of making engine components too "smart". To me, the app is the right place to solve this issue.

**Comment by makc** [comment]
I have figured that `Number(value)` works better than the snippet above (since it handles both decimal and hexadecimal) and with that it is not too bad to put in user code. I wish I thought about it few years earlier 😔
