### ISSUE TITLE
Classes not extendable

### ISSUE THREAD

**Issue by zzador** [mrdoob/three.js#26699]
### Description

I tried to create classes that extend the THREE.Scene, THREE.Mesh and THREE.PointLight to add some specific functionality to these classes. However the instaces of the extended classes aren't recognized by THREE.js. It seems that there are some unnecessary checks with "instanceof" to check if the passed objects are really instances of a specific class. This makes inheritence and clean OOP impossible! Is there another way to extend these classes?

### Reproduction steps

1. Create a new class for PointLight and extend it from it.
2. Create an instance of this class and add it to a valid THREE.Scene object
3. Try to render the scene

### Code

```js
class Light extends THREE.PointLight
{
	constructor(color, intensity, distance, decay)
	{
		super(color, intensity, distance, decay);
        }
}
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r154

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
I'm unable to reproduce the issue: https://jsfiddle.net/pg27uh3k/

The fiddle creates a custom point light class and uses it in the scene without issues.

**Comment by donmccurdy** [comment]
@zzador Using `instanceof` does not interfere with ES6 Classes and inheritance, your subclass should still pass the check. If you are using a build tool (e.g. webpack) that transpiles your code to ES5, that would remove ES6 Classes, and this will certainly cause problems like those you describe. Perhaps check the compiled code, if that's the case.

**Comment by Mugen87** [comment]
@zzador Please use the [forum](https://discourse.threejs.org/) if you need help with your code setup.
