### ISSUE TITLE
Exception when loading files with lights in the editor

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#26702]
### Description

The following files throw exceptions in https://threejs.org/editor:
`Error: Unsupported color space conversion, "1" to "srgb-linear".`

[FilesWithLights.zip](https://github.com/mrdoob/three.js/files/12527861/FilesWithLights.zip)

### Reproduction steps

1. Unpack
2. Visit https://threejs.org/editor and open the console
3. Drop either of the files

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/2693840/368404d3-b5ea-40c9-a9e8-9ca0631f0c41)

### Version

latest

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
This should be fixed via #26691. `0.156.1` has already been published but it seems the `gh-pages` branch does not use the latest version of `GLTFLoader` yet.

**Comment by Mugen87** [comment]
Should be fixed via 1c5834a63c54fabee23b86a2bca35925bb57b613.

**Comment by hybridherbst** [comment]
Ah cool, thanks!
