### ISSUE TITLE
Editor: `#Viewport` should not be change when move the mouse after click `.Select` element.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#26705]
### Description

In the latest Firefox 117, Editor `#Viewport` should not be change when move the mouse after click `.Select` element.

### Reproduction steps

1. Open then editor in Firefox
2. Click `.Select` element.
3. Move the mouse to the `#Viewport`

### Code

None

### Live example

None

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/23699926/ee9ba6ca-f85e-4278-abab-6c20c18786be)

### Version

dev

### Device

Desktop

### Browser

Firefox

### OS

Windows

**Comment by Mugen87** [comment]
It also happens with Firefox Nightly (119.0a1).
