### ISSUE TITLE
Editor: Serialization support for environment dropdown "MODELVIEWER" option

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#26711]
### Description

I find myself often refreshing the three.js editor to load a fresh file, test local changes, and so on.
It's great that the editor tries to keep state (by serializing/deserializing to/from JSON) but the environment options aren't serialized, probably because changing them only has sideeffects and are not values themselves.

Still, it would be great if one could set "MODELVIEWER" as environment and then refresh the page to find the same environment.

<img width="292" alt="image" src="https://github.com/mrdoob/three.js/assets/2693840/ca9a8536-51fd-49f6-941e-4f63aea419b5">

### Solution

If scene values match what the effect of the dropdowns is (e.g. environment is the result of setting MODELVIEWER), serialize some information about that state so it can be brought back on page reload. This would probably go into Editor.js:toJSON and not into scene.toJSON (?).

### Alternatives

-

**Comment by Mugen87** [comment]
>  but the environment options aren't serialized,

`Scene.environment` is support by `toJSON()` but only normal textures (environment maps) are honored.

https://github.com/mrdoob/three.js/blob/1543d95d3e4f4d110d7269d50205f10f0f7662f8/src/core/Object3D.js#L736-L756

When selecting `ModelViewer` in the editor, `Scene.environment` holds a _render target texture_ produced via `PMREMGenerator` and `RoomEnvironment`. The typical pattern for this is:
```js
scene.environment = pmremGenerator.fromScene( new RoomEnvironment( renderer ), 0.04 ).texture;
```
I think we can save the model viewer selection in the editor directly until we figure out a solution for the core.
