### ISSUE TITLE
GLTFLoader: Some clearcoat materials are imported as MeshStandardMaterial

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#26714]
### Description

While trying to fix some USDZ loading/conversion/roundtrip issues I noted that GLTFLoader imports the right column in ClearCoatTest.glb as MeshStandardMaterial without clearcoat parameters, instead of as MeshPhysicalMaterial with clearcoat parameters.

My understanding would be that for example this slot should import with a normal map and coating on top, instead it imports as MeshStandardMaterial without normal map and without clearcoat settings:
<img width="1303" alt="image" src="https://github.com/mrdoob/three.js/assets/2693840/4c919273-cfcd-4ceb-9a88-f6022c92313c">

### Reproduction steps

This can be reproduced in the three.js Editor by importing this file:
[ClearCoatTest.glb.zip](https://github.com/mrdoob/three.js/files/12543207/ClearCoatTest.glb.zip)

### Version

r156

**Comment by donmccurdy** [comment]
This is expected, from the [model's description](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/ClearCoatTest#columns) —

> **Base Layer** - A base material with no coating.
> 
> **Coated** - The combination of the outer two columns, using [KHR_materials_clearcoat](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_clearcoat).
> 
> **Coating Only** - This is a base material with settings copied from just the coating in the central column.

In other words, the center column demonstrates both layers, requiring the clearcoat extension. The left and right column show the lower and upper layer / BRDF, and don't require the clearcoat extension to show a single layer in isolation.

**Comment by hybridherbst** [comment]
Thank you, I had missed that!
