### ISSUE TITLE
ColorManagement: Document which three.js colors are intended to be in linear and sRGB space

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#26721]
### Description

I think it would be useful to note somewhere which colors set throughout three are intended to be in linear or sRGB space.

As an example, the scene background (https://threejs.org/docs/#api/en/scenes/Scene.background) just states it is a color, of course one can experiment if that is passed through as linear or sRGB to the shader. The same applies to e.g. material.color, light.color, and others. At least in the glTF spec there's differences between the color spaces (e.g. diffuse color is in sRGB, light color is in linear), but I'm not sure if in three everything is just sRGB and how that will/will not change once P3 and other wide gamut spaces are available.

**Comment by donmccurdy** [comment]
Do the "Roles of color spaces" and "Working with THREE.Color instances" sections under [Color management](https://threejs.org/docs/#manual/en/introduction/Color-management) clarify this?  In more recent versions of three.js we treat all THREE.Color instances alike, regardless of where they are used. Components (like `color.r`) are always in the working color space (currently "Linear-sRGB"). Certain setters — for hexadecimal and CSS strings — assume their inputs are sRGB by convention, and are converted automatically to the working color space. Other setters assume input is already in the working color space and perform no conversion, but this can be overridden with the `colorSpace` argument to any setter as shown on the THREE.Color documentation:

https://threejs.org/docs/?q=color#api/en/math/Color.getHex

***

> despite the light being in linear space in glTF and the albedo color being in sRGB space in glTF. So I guess that means in three light.color and material.color are also using different color spaces.

The glTF specification has struggled with a technically _precise_ way to explain the color spaces of multiplicands resulting in a Linear-sRGB product. But for all practical purposes, the values going into both `setRGB` calls above are Linear-sRGB, as identified by the colorSpace parameter to the setter.
