### ISSUE TITLE
Strange code: texture.generateMipmaps enabled for one cube face

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#26736]
### Description

Following code looks strange:

https://github.com/mrdoob/three.js/blob/1250397f1867f35f1e4023ac1ed5383d3fb15e50/src/cameras/CubeCamera.js#L148-L157

Why is `generateMipmaps` reset before rendering last (negative Z) cube face? If this is intentional, I think it should be commented, as the code looks strange.

### Reproduction steps

1. look at the code

### Code

none

### Live example

none

### Version

156

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
The idea is to generate mipmaps when the render target is complete, meaning when all sides of the cube render target have been rendered.
