### ISSUE TITLE
webxr hit test

### ISSUE THREAD

**Issue by blueRaining** [mrdoob/three.js#26734]
### Description

when i use webxr hit test in threejs,and i shake the phone quickly,the model in ar   sometimes shifts from its original position

### Reproduction steps

1.open https://threejs.org/examples/?q=webxr#webxr_ar_hittest
2.use hitTest to create model
3.shake the phone quickly

### Code

```js
// code goes here
```

### Live example

 https://threejs.org/examples/?q=webxr#webxr_ar_hittest

### Version

153

**Comment by Mugen87** [comment]
I'm afraid this is not something we can fix in `three.js`. The AR implementation of the phone will recenter/position the scene based on device's tracking. Shaking the phone might mix up the tracking, though.
