### ISSUE TITLE
Issue: Object3D `.attach()` emits `added` too early

### ISSUE THREAD

**Issue by ycw** [mrdoob/three.js#26739]
### Description

`.attach(object)` will dispatch "added" event on `object`, but at user-provided event handler, the descendants' world transforms had not been updated, to work around this, users are required to update manually before accessing them

```js
object.addEventListener('added', () => {
  object.updateWorldMatrix(false, true)
```

the workaround is not ideal because threejs anyhow repeats the same after stepout the handler (=update twice):

https://github.com/mrdoob/three.js/blob/ce0b3d0415c4bc87a8b4ad01c5d21cc26c6ec5eb/src/core/Object3D.js#L419-L421

### Live example

- https://jsfiddle.net/nkfLbc1j/

### Version

r156

**Comment by gkjohnson** [comment]
Adding such checks would have a pretty severe performance penalty for adding children to the hierarchy. I think this is something that needs to be managed by users.
