### ISSUE TITLE
OrbitControls, no pointerdown event with 2nd touch, with 1st touch on another DOM element

### ISSUE THREAD

**Issue by Pl4n3** [mrdoob/three.js#26735]
### Description

If you first touch a DOM element, that is not the Threejs canvas, touch move abit, then while holding the first touch, touch the Three js canvas and touch-move to rotate the camera, rotation doesnt work. It seems that no pointerevents (pointerdown,..) fire, while touchevents still appear. I would like to have this for a game to touchcontrol both a character with an own element and the camera touch-moving the Threejs canvas parallely. Since touchevents still appear, I added the code below extending OrbitControls. Maybe thats useful for others or is this intended behavior for pointerevents?

### Reproduction steps

1. Go to any three.js scene with OrbitControls, as https://threejs.org/examples/#webgl_animation_keyframes and another DOM element, e.g. Stats.
2. First touch Stats and touch-move abit, then while holding first touch, do a second touch on the canvas and try to rotate the camera.
3. Camera doesnt rotate.

### Code

```js
// following code I add before 'scope.domElement.addEventListener( 'pointerdown', onPointerDown );', 
// also add as first lines of onPointerDown() / onPointerMove(): pointerDownE=event; / pointerMoveE=event;
// this seems to fix the issue.

//--- pl follwoing because sometimes not pointerdown but only touchstart events fire
                        let pointerAdded=false,pointerDownE,pointerMoveE;
			scope.domElement.addEventListener('touchstart',function(e) {
                          //onsole.log(e);
                          if ((!pointerDownE)||(pointerDownE.timeStamp!=e.timeStamp)) {
                            //onsole.log('--touchstart--');
                            e.pointerId=2;
                            pointerAdded=true;
                            addPointer(e);
                            onTouchStart(e);
                          }
                        },{passive:false});//pl
			scope.domElement.addEventListener('touchmove',function(e) {
                          //onsole.log(e);
                          if ((!pointerMoveE)||(pointerMoveE.timeStamp!=e.timeStamp)) {
                            //onsole.log('--touchmove--');
                            e.pointerId=2;
                            onTouchMove(e);
                          }
                        },{passive:false});//pl
			scope.domElement.addEventListener('touchend',function(e) {
                          if (pointerAdded) {
                            //onsole.log('touchend pointerAdded -> setting to 0'); 
                            pointers.length=0;pointerAdded=false; 
                          }
                        },{passive:false});//pl
//---- pl end

```

### Live example

 https://threejs.org/examples/#webgl_animation_keyframes

### Version

r156

### Device

Mobile

### Browser

Chrome

### OS

Windows, Android

**Comment by Mugen87** [comment]
TBH, the code feels a bit too hacky to add it to the module.

If you have the time, it would be interest to know why no pointer events are fired. This can be investigated without `three.js` with plain HTML. If you can manage to setup a live example that demonstrates the issue, you can test in different browsers and see if they all behave the same. I would also consider to file a bug at the Chromium bug tracker and ask why touch and pointer events differ in their behavior.

**Comment by Pl4n3** [comment]
Yea, the code is hacky, just an idea to approach the issue. I will search for more information on why thouse events differ.
