### ISSUE TITLE
Feature request: ability to dodge circular references in scene tree

### ISSUE THREAD

**Issue by ycw** [mrdoob/three.js#26738]
### Description

The issue: Object3D `.traverse*()` might enter black hole because circular refs is ignored during insertion, e.g.

```js
import { Object3D } from 'three';

const A = new Object3D()
const B = new Object3D()
const C = new Object3D()

A.add(B)
B.add(C)
C.add(A)

A.traverse(console.log)

/* here unreachable */
```

### Solution

solution 1/ forbids circular refs at insertion apis, `.add()` and `.attach()`:

```js
C.add(A) // noop, logs err instead
```

### Alternatives

solution 2/ introduces new api to help users dodge circular refs

```js
A.isAncestorOf(C) || C.add(A)
```

**Comment by gkjohnson** [comment]
Adding such checks would have a pretty severe performance penalty for adding children to the hierarchy. I think this is something that needs to be managed by users.
