### ISSUE TITLE
STLLoader does not load my STL files properly

### ISSUE THREAD

**Issue by soaringai** [mrdoob/three.js#26755]
### Description

I have many STL models, and when using STLloader.js to load models, some of them cannot be loaded properly. There are no error messages in the browser, and when I check the network tab in the browser, I can see that the STL data has already been loaded.

### Reproduction steps

load stl file

### Code

```js
// code goes here
```
				const loader = new STLLoader();
				loader.load( './models/stl/ascii/a.stl', function ( geometry ) {

					const material = new THREE.MeshPhongMaterial( { color: 0xff0000 } );
					const mesh = new THREE.Mesh( geometry, material );

					// mesh.position.set( 0, - 0.25, 0.6 );
					mesh.rotation.set( 0, - Math.PI / 2, 0 );
					mesh.scale.set(0.1, 0.1, 0.1 );
					mesh.position.copy(cameraTarget)
					console.log(mesh)
					mesh.castShadow = true;
					mesh.receiveShadow = true;

					scene.add( mesh );

				} );

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r156

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
We can't investigate the issue if you don't share one of your problematic STL files.
