### ISSUE TITLE
`MeshPhysicalMaterial.sheenColor` says it defaults to `0xffffff` in the docs, but seems to default to `0x000000`

### ISSUE THREAD

**Issue by Ameobea** [mrdoob/three.js#26757]
### Description

In [the docs](https://threejs.org/docs/#api/en/materials/MeshPhysicalMaterial.sheenColor) for `MeshPhysicalMaterial.sheenColor`, it says the default value is `0xffffff`.  However, when I actually construct a `new MeshPhysicalMaterial()` and check the default sheen color, it seems to be set to `0x0`.

I don't know which is correct - the docs or the code.

### Reproduction steps

1. Construct a new `MeshPhysicalMaterial` and retrieve the default value of `sheenColor`

### Code

```ts
new THREE.MeshPhysicalMaterial().sheenColor.getHex()
// 0
```

### Live example

* [jsfiddle-dev](https://jsfiddle.net/Ameobea/ech0fzpL/1/)

### Version

commit `f98f680b1bce7a4e434501d9566fa8cf474963d0`

### Device

Desktop

### Browser

Chrome

### OS

Linux

**Comment by Mugen87** [comment]
The code is correct. Let's fix this in #26753.
