### ISSUE TITLE
shGetIrradianceAt produces negative values

### ISSUE THREAD

**Issue by vanruesc** [mrdoob/three.js#26767]
### Description

While investigating [this bug](https://github.com/pmndrs/postprocessing/issues/526) I found the root cause in the `lights_pars_begin` shader chunk. It looks like `shGetIrradianceAt` sometimes produces negative values which leads to unexpected behaviour. This happens regardless of whether a light probe is used or not.

The issue becomes more noticeable when the result is stored in a `HalfFloatType` buffer for further processing as this doesn't clamp the values to `[0, 1]` and leads to more errors down the line. When rendered directly to screen, the output will contain black pixels where `shGetIrradianceAt` returns bad values.

### Reproduction steps

1. Open https://codesandbox.io/s/exciting-shape-xv2p7x?file=/src/App.js
2. See black artifacts in the render output.
3. Uncomment line 5 to limit the return value of `shGetIrradianceAt` to at least 0.

### Code

See sandbox example.

### Live example

https://codesandbox.io/s/exciting-shape-xv2p7x?file=/src/App.js

### Screenshots

| Render Output | Bad Fragments | With Post Processing (Bloom) |
|-|-|-|
| ![render](https://github.com/mrdoob/three.js/assets/9214917/3012184c-0e7e-4b38-90e3-10157aeda912) |  ![bad-fragments](https://github.com/mrdoob/three.js/assets/9214917/c6605760-260a-4f92-9905-6be2503989e4)| ![undefined-behaviour](https://github.com/mrdoob/three.js/assets/9214917/baf3d9b9-5f67-471e-99f7-3ee11640a374) |

### Version

r156

### Device

Desktop

### Browser

Chrome, Edge

### OS

MacOS, Linux

**Comment by WestLangley** [comment]
>This happens regardless of whether a light probe is used or not.

That is a red flag.

So far, I am unable to replicate the issue in a separate vanilla three.js example. The probe state in the renderer should initialize to zero and remain zero.

Regardless, I think we should follow what @Mugen87 [suggested](https://github.com/mrdoob/three.js/issues/26668#issuecomment-1706217628):

>getLightProbeIrradiance() should only be executed if there are actually probes in the scene. This can easily be fixed with a new define (maybe USE_LIGHT_PROBES).

**Comment by Mugen87** [comment]
@WestLangley Okay, I have filed a PR to introduce a new define. Would be great if you could review the change 😇 .

**Comment by WestLangley** [comment]
@vanruesc Can you produce a simple, debuggable JSFiddle that reproduces your issue?

**Comment by vanruesc** [comment]
Here's a simplified jsFiddle: https://jsfiddle.net/ofenj465/

The `normalMap` of the original box model is actually a bump map which is probably part of the problem:

<img width="200" src="https://github.com/mrdoob/three.js/assets/9214917/779aba14-f073-4d7d-b2a4-5ec2278ae373">

The jsFiddle example exhibits less artifacts for some reason. The main difference is that it's using a basic `BoxGeometry` mesh. The box model looks fine in Blender though:

<img width="200" src="https://github.com/mrdoob/three.js/assets/9214917/ab4a3cab-1a30-45bd-884a-c2bd32de7075">

**Comment by WestLangley** [comment]
>The normalMap of the original box model is actually a bump map which is probably part of the problem

Part of the problem?

```js
model.children[ 0 ].material.normalMap = null;
```
... and the artifacts disappear completely for me.

**Comment by vanruesc** [comment]
> Part of the problem?

Using a wrong texture as a normal map is definitely the main issue, but the custom geometry somehow produces even more artifacts, so there's probably something wrong with that data too.

Ideally, the material shouldn't glitch like this, but I'm fine with closing this as a user error.
