### ISSUE TITLE
3D model with transparent material rendered incorrectly

### ISSUE THREAD

**Issue by wasabia** [mrdoob/three.js#26762]
### Description

Some parts of the model have z-fighting/stitching artifacts, for example on the legs. 
Is this a bug?

[wasp_GLTF_demo.zip](https://github.com/mrdoob/three.js/files/12616056/wasp_GLTF_demo.zip)

### Screenshots

![screenshot-20230915-133153](https://github.com/mrdoob/three.js/assets/1768228/90c5a196-497a-40f8-9fe7-fecc7a43f507)

### Version

r155

**Comment by Mugen87** [comment]
This is a modeling issue. For some reasons, `depthWrite` is disabled for the legs materials. Enabling it solves the rendering issues.

**Comment by Mugen87** [comment]
Please let you help at the [forum](https://discourse.threejs.org/) first.
