### ISSUE TITLE
More demos

### ISSUE THREAD

**Issue by chiaravalle** [mrdoob/three.js#26771]
### Description

I'd like to have more demos, covering the topics in this list

### Solution

Sculpt (like Z-Brush - show a sculptable mesh)
Bevel modifier (show polygons beveled)
Decimate polycount (procedurally reduce polycount - show original and reduced side by side)
Skin modifier (Automatically produce a mesh based on a skeleton-like structure made of a hierarchy - show the result)
Maintain volume while transforming - show resulting animation
Chamfer - show result
Subdivide geometry - show result wireframe
Revolve (sometimes referred to as lathe) - show revolved curve
Twist - show twisted shape
Taper - show tapered tape
Paint on mesh - interactively paint on mesh

Physics simulation - show a simulation
*	Soft bodies
*	Fluids

### Alternatives

May be finding suitable code one by one on Google

**Comment by Mugen87** [comment]
Most of what you have listed are very complex components. It is out of scope to support all of them in this repository.

**Comment by chiaravalle** [comment]
Maybe you should broaden your horizons?
You could add a "very complex" demo category to the three.js main examples page.
No, I'm just kidding, but hey, why not try? Maybe something ready made already exist, just need to be linked.

I guess the "out of scope" tag for refusing jobs it's a bit misused nowadays, isn't it?

I'm sarcastic. Have a nice day, regards =)

**Comment by Mugen87** [comment]
> Maybe something ready made already exist, just need to be linked.

The project actually uses an approach for this called "external examples". For example the physics engine Ammo.js is not maintained in this repository, but there are official examples using it like

https://threejs.org/examples/physics_ammo_volume (which is btw a demo for soft bodies)

Another external example is the subdivision modifier:

https://threejs.org/examples/webgl_modifier_subdivision

So if someone decide to implement a bevel modifier or sculpt tool for `three.js`, example could be created in a similar fashion.

**Comment by chiaravalle** [comment]
Oh, I see. This is sort of a good news, gonna Googling for stuff I'm interested to and propose to add them to such list.
By the way sorry for my "funny" post, I hope I didn't offend anyone.

**Comment by chiaravalle** [comment]
Ok, here are what I found.

Twist - show twisted shape (https://medium.com/@crazypixel/geometry-manipulation-in-three-js-twisting-c53782c38bb)
Taper - show tapered tape (https://github.com/Sean-Bradley/Bender)
Paint on mesh - interactively paint on mesh (https://rawcdn.githack.com/sciecode/three.js/f4e363a8e0cf6c496f4191192d7eb15110442a7c/examples/webgl_paint_texture.html)

Physics simulation - show a simulation
*	Soft bodies (https://threejs.org/examples/physics_ammo_volume)

Other are already listed in the examples and I didn't noticed (in the rush, excuse me) or are described in the documentation.

Not found stuff: 
Sculpt (like Z-Brush - show a sculptable mesh)
Skin modifier (Automatically produce a mesh based on a skeleton-like structure made of a hierarchy - show the result)
Maintain volume while transforming - show resulting animation
Physics simulation - show a simulation
*	Fluids

Thanks so much, I hope you'll include my found demos in the external examples.

**Comment by Mugen87** [comment]
> I hope you'll include my found demos in the external examples.

This needs to be done by the maintainers of the specific projects. You have to understand that maintenance is a huge issue and without the support of these maintainers things would become quickly out of date.

**Comment by chiaravalle** [comment]
Oh, ok. So I'll have to ask them, right?
Thanks anyhow.
