### ISSUE TITLE
SVGLoader pointsToStroke incorrect result using linecap square

### ISSUE THREAD

**Issue by IRobot1** [mrdoob/three.js#26781]
### Description

When passing a simple 2 point line shape to SVGLoader pointToStroke, when linecap is set to square, the resulting geometry is incorrect.  

![image](https://github.com/mrdoob/three.js/assets/25032599/4ec74360-8fbe-48ba-899b-bcb465e4ea25)

It works correctly when linecap is either butt or round.

### Reproduction steps

create a 2 point line shape
getStrokeStyle passing linecap set to 'square'
pass resulting shape and stroke style to pointsToStroke

### Code

```js
const shape = new Shape();
  shape.moveTo(-12, 0);
  shape.lineTo(12, 0);

  const style = SVGLoader.getStrokeStyle(
    2,
    "white",
    undefined,
    "square",
    undefined
  );

  const geometry = SVGLoader.pointsToStroke(shape.getPoints(), style);
  const material = new MeshBasicMaterial({ side: DoubleSide });
  const rect = new Mesh(geometry, material);
  scene.add(rect);
```

### Live example

https://codesandbox.io/s/three-stroke-square-test-3yn756

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/25032599/a3c2d140-c143-498b-8a3f-436fff193d9e)

### Version

156.1

### Device

Desktop

### Browser

Edge

### OS

Windows

**Comment by WestLangley** [comment]
FWIW, it works if you add an interleaving point.

```js
const shape = new Shape();
  shape.moveTo( - 12, 0 );
  shape.lineTo( 0, 0 );
  shape.lineTo( 12, 0 );
```

**Comment by IRobot1** [comment]
When I rotate the scene (using orbit), the missing triangle is facing backwards.  So likely the normal is just wrong or not being calculated.
