### ISSUE TITLE
Runtime error calling closePath on new Path() 

### ISSUE THREAD

**Issue by IRobot1** [mrdoob/three.js#26827]
### Description

Create Path object. Call closePath before adding anything to path results in runtime error

Cannot read properties of undefined (reading 'getPoint')

```ts
const path = new Path();
path.moveTo(0, 0);
//path.lineTo(1,1)
path.closePath();
```

Looks like the code just needs to check if the curves array is zero length.

### Reproduction steps

Create Path object. 
Call closePath before adding anything to path 

### Code

```ts
const path = new Path();
path.moveTo(0, 0);
//path.lineTo(1,1)
path.closePath();
```

### Live example

https://codesandbox.io/s/three-path-closepath-issue-p3vfrr

### Screenshots

```
// Add a line curve if start and end of lines are not connected
		const startPoint = this.curves[ 0 ].getPoint( 0 );
----------------------------------------------^
		const endPoint = this.curves[ this.curves.length - 1 ].getPoint( 1 );
```

### Version

156.1

### Device

Desktop

### Browser

Edge

### OS

Windows

**Comment by Mugen87** [comment]
What do you think would be the ideal behavior? We could add the following line:
```js
if ( this.curves.length > 0 ) return this;
```
But it seems doing nothing isn't correct for a method that is supposed to close path definitions. Maybe throwing an error?

On the other hand, `three.js` does in general not validate inputs or states. Trying to close a path without any curves in considered as an invalid state and thus a user error.

**Comment by IRobot1** [comment]
Ok, let's stick with user error.  I'll either set autoClose = true or check curves.length > 0
