### ISSUE TITLE
Threejs version 0.151.3 uses a model that parses dracol compression and reports an error THREE. DRACOLoader: Unexpected geometry type, Can load normally in version 0.138.3

### ISSUE THREAD

**Issue by juzhiqiang** [mrdoob/three.js#26825]
### Description

Threejs version 0.151.3 uses a model that parses dracol compression and reports an error THREE. DRACOLoader: Unexpected geometry type, Can load normally in version 0.138.3

### Reproduction steps

1.
2.
3.

### Code

```js
// @ts-ignore
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
// @ts-ignore
import { DRACOLoader } from "three/examples/jsm/loaders/DRACOLoader.js";

 const loader = new GLTFLoader();

  // 模型压缩过需要解压
  const dracoLoader = new DRACOLoader();
  dracoLoader.setDecoderPath("/draco/");
  loader.setDRACOLoader(dracoLoader);
  //  载入模型
  loader.load(
    // resource URL
    "http://localhost:8000/mode/city2.glb",
    // called when the resource is loaded
    function (gltf) {
      console.log(gltf);
    }
  );
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/25214312/6aabea03-ae91-4412-9c1d-8d8a9c44c3ce)

### Version

151.3

**Comment by wlinna** [comment]
Hello, why did you solve the problem? I seem to have the same issue, and would appreciate if you were able to give a hint on how to solve it :)

**Comment by juzhiqiang** [comment]
On the node of the corresponding version of three you are using_ In the modules file node_ Copy the modules three examples jsm libs draco file to your project's static resource file, and then `dracoLoader. setDecoderPath ("/static resource file/")` where you are using it;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mrdoob/three.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月26日(星期二) 下午3:07
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [mrdoob/three.js] Threejs version 0.151.3 uses a model that parses dracol compression and reports an error THREE. DRACOLoader: Unexpected geometry type, Can load normally in version 0.138.3 (Issue #26825)





 
Hello, why did you solve the problem? I seem to have the same issue, and would appreciate if you were able to give a hint on how to solve it :)

**Comment by wlinna** [comment]
Thanks! Though we are not using node for this, your tip was an important clue for us. It seems that we forgot to update the decoder after upgrading DRACOLoader
