### ISSUE TITLE
WebGPU Node system extremely slow startup

### ISSUE THREAD

**Issue by alienself** [mrdoob/three.js#26820]
### Description

Hi, I started exploring webgpu in threejs, however the startup time is just insane,
in the following scene with 4 materials, the scene only shows up after 1.6 seconds.
 
After a bit a profiling, it seems like the culprit is the WGSLNodeBuilder: each material has about 1000 nodes to construct which takes forever (about 400+ms per material). 

https://threejs.org/examples/?q=webgpu#webgpu_clearcoat

Any fixes on the table? Is this going to be a limitation of the node system

At the moment it is not really usable beyond small prototypes but even then having the wait multiple seconds for those node materials to build is definitely not ideal

### Reproduction steps

1. Open https://threejs.org/examples/?q=webgpu#webgpu_clearcoat
2. Profile in the dev console

### Screenshots

![Screenshot 2023-09-21 165039](https://github.com/mrdoob/three.js/assets/87069099/556359cd-5bcb-4030-9b66-3abfe0efbc45)

### Version

156

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by sunag** [comment]
Please test using the JavaScript, it will better represent the result.

Just remove any call to `render()`, and add just one call to measure the rendering time, consider that during this time the compilation of the shader will not be the only thing to be executed, but the creation of textures, geometry, etc… Even so, the result is very different from what is presented above.

```js
const now = performance.now();

renderer.render( scene, camera );

console.log( performance.now() - now );
```

This cost me around `~0.15` milliseconds in my M1 computer, much lower than `16.66` (1000/60) which represent 60 FPS.

The second frame `now - performance.now()` returned `0` because the value was too small, since everything was initialized.

**Comment by mrdoob** [comment]
Maybe the shader compiler on Windows is super slow compared to the one in MacOS?

**Comment by sunag** [comment]
I had `~0.6` on my laptop with Windows and Ryzen 7 processor, less than `1 ms` to render/compile the first frame.

**Comment by sunag** [comment]
In any case, there is a strange behavior, as the frame is taking a long time to appear. I will analyze this more carefully.

**Comment by alienself** [comment]
On my side, the screen stays black for about 2 seconds before displaying the first frame which is not the case when using webgl or even babylon webgpu. I have a solid pc with a nvidia 3090 and the I am having the exact same issue on my macbook (actually worse..). 

The performance issue is happening inside the WGSLNodeBuilder when the materials are being created. I do not believe that this is related to webgpu api as I do not have such issue with babylon nor emscripten. 

As for the benchmark, the load is spread out across multiple frames so it's easier to visualize in the profiler, here is a zoomed out version of the profiler on one of the material during startup (when the page is loaded or material created for the first time):

![Screenshot 2023-09-21 201738](https://github.com/mrdoob/three.js/assets/87069099/ab42c953-9e79-4d6a-b7f6-4e8a904fc02e)

As you can see most of the compute is going toward this traverse method in the Node.js
```js


	traverse( callback, replaceNode = null ) {

		callback( this, replaceNode );

		for ( const { childNode, replaceNode } of this.getChildren() ) {

			childNode.traverse( callback, replaceNode );

		}

	}
	```
	
As for JS benchmark in the console sure:
```
4.399999976158142
0.4000000059604645
0.5999999940395355
0.5
0.4000000059604645
0.5999999940395355
0.5
0.4000000059604645
0.5
0.800000011920929
0.5
0.5999999940395355
0.5
0.6000000238418579
0.5999999940395355
0.5
0.5999999940395355
0.5
0.5999999940395355
0.5
0.7000000178813934
0.5999999940395355
0.5
```

**Comment by alienself** [comment]
@sunag  Any way to reopen this issue?

**Comment by sunag** [comment]
> @sunag Any way to reopen this issue?

Yes, I think it's worth analyzing all these points first.

**Comment by LeviPesin** [comment]
Hmm... I don't think it could be very slow... I think most of the time must be spent in the `callback`?

@alienself -- are the `4.399999976158142` and other values in seconds or milliseconds? `performance.now()` returns milliseconds.

**Comment by sunag** [comment]
If we can replace these `VarNode.assign` with `stack.assign` is better, it follows flow, and there is no need to `traverse`.

**Comment by LeviPesin** [comment]
I think we can close this after https://github.com/mrdoob/three.js/pull/26881 is merged.

@alienself Does the performance become better for you?

**Comment by sunag** [comment]
[This update](https://github.com/mrdoob/three.js/pull/26885) had more impact on my tests.

**Comment by LeviPesin** [comment]
Are you sure you really are testing the latest version? There should not be `assign-traverse-traverse-...` blocks, they were removed in https://github.com/mrdoob/three.js/pull/26881.

**Comment by sunag** [comment]
> If you have 50 materials that's 280ms * 50 = 14 seconds (ouch!)

This logic should not happen, if you create 50 materials and only change the color or texture for example, the cache system must reuse the `NodeBuilder` and the `GPU Program` and this process would only happen once. Compile time should decrease every time new material is created as the cache increases.

Approach like https://github.com/mrdoob/three.js/pull/26889 will do the same thing at a function level.

> Have you though about adding a stress test scene for node materials with many materials created when the page loads as well as instantiated at runtime for instance at the press of a button?

Yes, a good idea.

> There should not be assign-traverse-traverse-... blocks, they were removed in https://github.com/mrdoob/three.js/pull/26881.

Yeah, that's probably it, I did a closer test and placed the `performance.now()` code inside `NodeBuilder.build()`.

In my testes, previously I had an average of `180 ms` and now `14 ms`.
