### ISSUE TITLE
With WebGPU, DirectionalLight + castShadows crashes

### ISSUE THREAD

**Issue by verekia** [mrdoob/three.js#26830]
### Description

With `WebGPURenderer`, `DirectionalLight` works fine but not with `castShadows` enabled.

### Reproduction steps

It crashes on this [line of TextureNode.js](https://github.com/mrdoob/three.js/blob/89e698f56604741244a2f7746edc0d876cec83ed/examples/jsm/nodes/accessors/TextureNode.js#L52).

```
TextureNode.js:52 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'channel')
    at Proxy.getDefaultUV (TextureNode.js:52:12)
    at Proxy.construct (TextureNode.js:87:1)
```

```
    getDefaultUV() {

        return uv( this.value.channel ); ❌

    }
```

### Code

See [reproduction repo](https://github.com/verekia/r3f-webgpu/tree/three-direction-light)

### Live example

I could not reproduce the bug in a live playground due to the top-level await of WebGPURenderer, sorry.

Here is a minimal reproduction repo: https://github.com/verekia/r3f-webgpu/tree/three-direction-light

Branch `three-direction-light`

### Screenshots

<img width="1440" alt="Screenshot 2023-09-24 at 13 32 01" src="https://github.com/mrdoob/three.js/assets/522007/3436c42c-5780-492c-b40d-487624f9bfaf">

### Version

r0.156.1

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by CodyJasonBennett** [comment]
Vanilla reproduction: https://jsfiddle.net/joekm4n2. Narrowed it to the use of a textured material combined with shadow maps.

<img width="302" alt="image" src="https://github.com/mrdoob/three.js/assets/23324155/158bb241-a92b-411c-81ed-151c56a778b5">

**Comment by sunag** [comment]
Thanks for making it easy to reproduce the error. Regarding the example in r3f, I think that for benchmark purposes `r157` brings some important improvements and others we are developing [here](https://github.com/mrdoob/three.js/issues/26673).
