### ISSUE TITLE
Dispose old attribute when it's updated to new one

### ISSUE THREAD

**Issue by CITIZENDOT** [mrdoob/three.js#26835]
### Description

Consider a `BufferGeometry` with an attribute named `customAttr`. 
```js
// const newAttr = new InterleavedBufferAttribute(...) or new BufferAttribute(...)
geometry.attributes.customAttr = newAttr;
geometry.attributes.customAttr.needsUpdate = true;
```
If I update it to `newAttr` like above, A new buffer is created using `gl.createBuffer`, because the `buffers` Weakmap cannot find `newAttr` here⬇️. The issue is, old buffer does not get disposed (using `gl.deleteBuffer`).
https://github.com/mrdoob/three.js/blob/e857553f2a8002f0e9cf6076d3bdc39dd525dbbc/src/renderers/webgl/WebGLAttributes.js#L168-L180 

When attributes are updated constantly, old attribute buffers get piled up in the webgl without disposal (because `gl.deleteBuffer` is only called when geometry is disposed)

### Solution

A `dispose()` method on attributes which calls `gl.deleteBuffer` would probably fix this. `InterleavedBuffer` might need some other changes I do not know of.

### Alternatives

_No Response_

**Comment by Mugen87** [comment]
Adding `dispose()` to `BufferAttribute` was already discussed in the past, see #15261 and #17063. Its implementation has quite some implications for the engine so you have to call `dispose()` on geometry level if you want to free single attributes.

In general, it is not recommended to constantly replace buffer attributes with new ones. The ideal workflow is to setup attributes _once_ and then just update their content. If attributes vary in their size, allocate _large enough_ buffers and use `drawRange` to specify what part of the geometry should be rendered.

**Comment by CITIZENDOT** [comment]
By updating attribute content, do you mean this?
```
customAttr.array.set(newAttr.array)
customAttr.needsUpdate = true
```

I tried this, and the performance is worse when compared to setting the attribute directly. Not sure why.

**Comment by CITIZENDOT** [comment]
> The ideal workflow is to setup attributes once and then just update their content

My workflow does not change these attributes: `position`, `uv` etc.. Creating geometry for every update means uploading all these attributes again (even if they're not changed).

**Comment by Mugen87** [comment]
You should not set the value of the array directly. Please use the dedicated interface of `BufferAttribute` (meaning the set* methods).

I suggest you clarify your issue at the [forum](https://discourse.threejs.org/) first because there is likely an issue in your workflow.

**Comment by CITIZENDOT** [comment]
Posted: https://discourse.threejs.org/t/dispose-update-attribute-efficiently/56399
