### ISSUE TITLE
BumpMapNode produces inverted normals with WebGL renderer

### ISSUE THREAD

**Issue by njarraud** [mrdoob/three.js#26847]
### Description

Code produced by BumpMapNode returns inverted normals.

Current implementation
<img width="338" alt="Capture d’écran 2023-09-26 à 22 11 58" src="https://github.com/mrdoob/three.js/assets/45501180/3a6a3390-aa7c-4c5a-bc6a-a6be885ea6e3">

Fix with negate() removed
<img width="337" alt="Capture d’écran 2023-09-26 à 22 12 36" src="https://github.com/mrdoob/three.js/assets/45501180/3622c9cf-e63b-4948-a707-4d418206cad7">

In Blender - result is the same as with the fix
<img width="540" alt="Capture d’écran 2023-09-26 à 22 17 12" src="https://github.com/mrdoob/three.js/assets/45501180/db8ec69d-2a28-411b-ac20-47226c57cb19">

### Reproduction steps

1. Create a mesh using MeshPhysicalNodeMaterial
2. Plug a BumpMapNode with a texture to normalNode input.
3. The normals seems to be inverted

### Code

The issue comes from `surf_pos: positionView.negate()` which shall be only `surf_pos: positionView`.

```js
return perturbNormalArb({
    surf_pos: positionView.negate(),
    surf_norm: normalView,
    dHdxy,
});
```

### Live example

None

### Version

r156

**Comment by LeviPesin** [comment]
Shouldn't this have been fixed with https://github.com/mrdoob/three.js/pull/26776 and https://github.com/mrdoob/three.js/pull/26807?

**Comment by sunag** [comment]
https://github.com/mrdoob/three.js/pull/26865
