### ISSUE TITLE
VideoTexture doesn't work on my iPhone 13 ( any browser ) iOS 16.3.1

### ISSUE THREAD

**Issue by clearly-outsane** [mrdoob/three.js#26859]
### Description

It's just blank. I tried various examples ( i initially stumbled upon it when making a scene using r3f) and they are all just dark. This one for example - https://threejs.org/examples/webgl_video_panorama_equirectangular is just a blank screen for me

### Reproduction steps

1. Open a scene with a videoTexture in it ( on mobile )
2. Doesn't show the video at all 

### Code

 -- not needed --

### Live example

https://threejs.org/examples/webgl_video_panorama_equirectangular

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/44093134/34afccf3-1c69-4f55-bbf0-c2647e3adf4a)

### Version

0.154.0

### Device

Mobile

### Browser

Chrome

### OS

iOS

**Comment by mrdoob** [comment]
Please report this to Apple instead:
https://www.apple.com/feedback/safari.html
