### ISSUE TITLE
DRACOLoader makes incorrect use of `postMessage`

### ISSUE THREAD

**Issue by jespertheend** [mrdoob/three.js#26863]
### Description

I was trying to parse a glb file with draco compression with Deno, but to my surprise, the returned promise stayed pending forever.
After a lot of debugging, it turns out DRACOLoader uses `postMessage` with an incorrect signature.
It uses it like `postMessage(data, transfer)` but the correct signature is `postMessage(data, targetOrigin, transfer)` (https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)

I'm not sure why this is only an issue in Deno (I've opened up https://github.com/denoland/deno/issues/20727 for this), but either way, it seems like with browsers the buffers get cloned like this rather than transferred.

Note that this was not the only issue I was running into, I had to do a couple of other fixes to make DRACOLoader work with Deno, but this was one issue I found that also seems to affect browsers.
Related: #18765

### Reproduction steps

1. Install [Deno](https://deno.com/)
2. Pass a buffer of gltf with draco compression to `GLTFLoader.parse()`

### Code

https://github.com/mrdoob/three.js/blob/f8863302d7200f02b50dbd3d0014ede46f134e37/examples/jsm/loaders/DRACOLoader.js#L447-L451

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r156

**Comment by donmccurdy** [comment]
It seems that there are two different signatures:

- https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
- https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage

From a Web Worker in a browser, our current usage should be correct... I don't think I understand why Deno would have a different signature, though.

**Comment by jespertheend** [comment]
Hmm yeah I think that comment on the Deno repository might be incorrect.
The signature inside workers seems to be
https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/postMessage
so it seems like the current implementation in threejs is correct.

[The spec](https://html.spec.whatwg.org/multipage/web-messaging.html#posting-messages) has the following two signatures:
- `dedicatedWorkerGlobal.postMessage(message [, transfer ])`
- `dedicatedWorkerGlobal.postMessage(message [, { transfer } ])`

So I guess even mdn is incorrect here. Either way, threejs seems to be doing the right thing 👍
