### ISSUE TITLE
[Documentation] Link to AmbientLightProbe not working

### ISSUE THREAD

**Issue by rowild** [mrdoob/three.js#26866]
### Description

In the lights section, there is a link to AmbientLightProbe, which leads to a 404:
https://threejs.org/docs/#api/en/lights/AmbientLightProbe

### Reproduction steps

Simply open the link https://threejs.org/docs/#api/en/lights/AmbientLightProbe

### Code

None, since documentation-related.

### Live example

https://threejs.org/docs/#api/en/lights/AmbientLightProbe

### Version

r157

### Device

Desktop, Mobile, Headset

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
Sorry, we have missed to remove the links in #26715.
