### ISSUE TITLE
GLTF importer and cubic interpolation

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#26868]
### Description

From my understanding the culprit is minification process which does mangling.

### Reproduction steps

1. got to https://gltf-viewer.donmccurdy.com/
2. upload https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/InterpolationTest

### Screenshots

Here's what it looks like:

https://github.com/mrdoob/three.js/assets/5939063/395f018a-9238-4ed0-a806-514a530fd527

Here's what it should look like:

![screenshot](https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/InterpolationTest/screenshot/screenshot.gif)

### Version

r154

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
To confirm there is no issue when importing the asset in the `three.js` editor.

Shouldn't the problem be reported at https://github.com/donmccurdy/three-gltf-viewer instead? When more than one build tools/minifier produce the same result, it's okay to reopen this issue here.

**Comment by donmccurdy** [comment]
Let's keep the issue here, if that's alright. 

@Usnul could you say more about why code mangling appears related? The bundler I'm using is Vite, fwiw.

**Comment by donmccurdy** [comment]
After upgrading dependencies (three.js + vite) and redeploying (I hadn't updated since r154) the issue on https://gltf-viewer.donmccurdy.com/ is gone. I'm still not sure what the original cause was, but it may have been a bug in an earlier version of Vite or its dependencies.

**Comment by Usnul** [comment]
Seems the problem has magicked away according to you guys. Sorry for the late reply, but I'll add a bit on mangling, just for completeness.

[Vite ](https://vitejs.dev/config/build-options.html#build-minify) and [Webpack](https://webpack.js.org/plugins/terser-webpack-plugin/), which are arguably the most popular packers out there right now, both use [`terser` ](https://terser.org/) when creating a production bundle. `terser` is what used to be called a "minifier", it's job is to make the overall size of the bundle smaller. As part of doing that - it renames things like variables, functions and classes. If your code relies on name of a constructor for example - after `terser` is done with your code - it will probably not work anymore.

2 things I guess that could have happened:
1. either GLTFLoader or some part of three.js used to rely on class names via `constructor.name`
2. GLTFLoader imported things and was delivered separate to three.js bundle, when the user bundled their software - they would end up with mangling from three.js bundle as packaged by three.js project, and mangling from whatever minifier the user uses, such as terser built into vite as in with @donmccurdy , et voilá - you get different symbols for the same things.

I didn't dig too deeply into what has happened myself, but hopefully this little history lesson will be of help to someone.
