### ISSUE TITLE
GLTFLoader: Can't parse .awd files

### ISSUE THREAD

**Issue by MadMax888** [mrdoob/three.js#26888]
### Description

Get the error when trying to load and parse **.awd** file by GLTFLoader (r108->r109: AWDLoader has been removed. Please use glTF instead.)

"SyntaxError: Unexpected token 'A', "AWD p�"... is not valid JSON"

### Reproduction steps

Try to load .awd file by GLTFLoader

### Code

```js
Loader.load(fileUrl, (awd) => {
          console.log("awd -----> ", awd);
        }, (p) => {
        }, (e) => {
          console.log("error");
          console.log(e);
        });
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

<img width="807" alt="image" src="https://github.com/mrdoob/three.js/assets/11533757/611be424-df76-4a03-a684-9deadce10e75">

### Version

0.156.1

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
You have to convert AWD to glTF before you can use `GLTFLoader`.

**Comment by mrdoob** [comment]
![Screenshot 2023-10-03 at 6 13 31 PM](https://github.com/mrdoob/three.js/assets/97088/83a35529-82da-49bb-8b78-5afb6f6cb8f8)

Hopefully that solves it 😇
