### ISSUE TITLE
NodeMaterial: Material "ShaderMaterial" is not compatible.

### ISSUE THREAD

**Issue by mlt131220** [mrdoob/three.js#26925]
### Description

use WebGPU renderer is error!
![image](https://github.com/mrdoob/three.js/assets/48863081/5461c071-ca30-49a4-a6fc-9f346921230c)

debug:
![image](https://github.com/mrdoob/three.js/assets/48863081/4a872a60-91c9-44ac-8437-5bb2bc8fb213)

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r157

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
As previously discussed, `ShaderMaterial` and `RawShaderMaterial` are not supported by `WebGPURenderer`.

**Comment by mlt131220** [comment]
> As previously discussed, `ShaderMaterial` and `RawShaderMaterial` are not supported by `WebGPURenderer` because of their direct dependency to GLSL.

Is there a recommended replacement option for the old project migration

**Comment by LeviPesin** [comment]
The best way is to convert GLSL code to TSL, which can auto-compile to both GLSL and WGSL.

**Comment by mlt131220** [comment]
> As previously discussed, `ShaderMaterial` and `RawShaderMaterial` are not supported by `WebGPURenderer` because of their direct dependency to GLSL.

I'm sorry, I found out today that the report was wrong with more detailed information. 
Call the WebGPURenderer.render () method to render the same scene normally, and call EffectComposer.render () to report the error as shown in the figure.

**Comment by realwugang** [comment]
> > As previously discussed, `ShaderMaterial` and `RawShaderMaterial` are not supported by `WebGPURenderer` because of their direct dependency to GLSL.
> 
> Is there a recommended replacement option for the old project migration


Have you solved it yet

**Comment by ionox0** [comment]
> The best way is to convert GLSL code to TSL, which can auto-compile to both GLSL and WGSL.

Which shader class should be used in this case?
