### ISSUE TITLE
More efficient Ray-AABB intersection test

### ISSUE THREAD

**Issue by Labrium** [mrdoob/three.js#26937]
### Description

I recently learned about a new algorithm used by NVIDIA OptiX and Intel Embree for testing the intersection of a ray and an AABB outlined in [this paper](https://jcgt.org/published/0007/03/04/):

```glsl
bool slabs(vec3 p0, vec3 p1, vec3 rayOrigin, vec3 invRaydir) {
    vec3 t0 = (p0 - rayOrigin) * invRaydir;
    vec3 t1 = (p1 - rayOrigin) * invRaydir;
    vec3 tmin = min(t0,t1), tmax = max(t0,t1);
    return max_component(tmin) <= min_component(tmax);
}
```

In that paper it also claims:
> "To our knowledge, this important efficient slabs method used by industry ray tracers is not widely known."

I checked the [intersectsBox function in `src/math/Ray.js`](https://github.com/mrdoob/three.js/blob/b02c13bdeefddcf48cb9f012dd7695a24fc00ff1/src/math/Ray.js#L389) and it looks like the current method is just essentially catching the exceptions of the [intersection distance function](https://github.com/mrdoob/three.js/blob/b02c13bdeefddcf48cb9f012dd7695a24fc00ff1/src/math/Ray.js#L323C14-L323C14).

### Solution

Is it possible that a form of this new method can be implemented in Three.js?

### Alternatives

None that I am aware of, it looks like this is the most efficient method out there for the time being.

### Additional context

From what I have found, it looks like the current Ray-AABB intersection method was implemented in 2014 (#2735); 4 years before the paper containing this new method was published.

**Comment by Labrium** [comment]
I just realized that if I'm not mistaken, `max_component(tmin)` should be the distance along the ray to the intersection point. In that case, the whole `intersectBox` function could be replaced.

**Comment by Labrium** [comment]
Sure thing! This is my first real contribution, so I'm excited to help with such a ubiquitous project!

**Comment by Labrium** [comment]
Should I create new temporary vectors, or use existing ones even if they don't necessarily make sense semantically?

**Comment by mrdoob** [comment]
These things can be discussed in the PR 👌

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/pull/27048#issuecomment-1808409581.
