### ISSUE TITLE
Backgournd cube bug

### ISSUE THREAD

**Issue by pai16858** [mrdoob/three.js#26932]
### Description

There will be stripe bugs in the background cube in the outlinepass effect.

### Reproduction steps

11

### Code

```js
// code goes here
```
111

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)
111

### Version

r157

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by gkjohnson** [comment]
Please fill out the requested sections to demonstrate the issue or your issue will be closed.
