### ISSUE TITLE
Transparent objects cannot penetrate to cast shadows

### ISSUE THREAD

**Issue by 1187882990** [mrdoob/three.js#26933]
### Description

Transparent objects cannot penetrate to cast shadows, such as transparent Windows, and light cannot pass through clear glass to create shadows in the room.

### Solution

Similar to the effect of lights in unity, lights can penetrate transparent objects to achieve a realistic shadow effect

### Alternatives

null

**Comment by gkjohnson** [comment]
Duplicate of #10600
