### ISSUE TITLE
GLTFLoader can’t parse ArrayBuffer with gltf and throw an error 

### ISSUE THREAD

**Issue by MadMax888** [mrdoob/three.js#26948]
### Description

Hi, here.

In the case of migration lib version v125 to v156.1.  I’ve got an issue with parsing **gltf** zip from ArrayBuffer using GLTFLoader.parse on lib v0.156.1. The same zip archive parsed fine on v0.125.0. In some phase, parsing is going well (see the screenshots below)

PS: Other format(.glb) that is parsed by GLTFLoader.parse from ArrayBuffer works fine after migration to v156.1

### Reproduction steps

1. Download the source of example the [yellow-plaster-3d-model](https://creazilla.com/nodes/7832752-yellow-plaster-3d-model)
2. Try to parse by GLTFLoader

### Code

```js
            const loader = new GLTFLoader();
          
            const parsed = loader.parse(
                 data, // ArrayBuffer
                '',
                (result) => {
                    processObject(result);
                },
                (err) => {
                    throw Error(err); // throw an error on some phase of parsing
                }
            );
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

<img width="431" alt="Screenshot 2023-10-11 at 12 27 22" src="https://github.com/mrdoob/three.js/assets/11533757/b3839b7c-102d-4838-8044-20d588acfac5">
<img width="1487" alt="Screenshot 2023-10-10 at 23 10 24" src="https://github.com/mrdoob/three.js/assets/11533757/35800446-db5f-4623-a875-28776bb23937">
<img width="1498" alt="Screenshot 2023-10-11 at 12 30 03" src="https://github.com/mrdoob/three.js/assets/11533757/01f0ab28-d10a-4e06-a4c0-589ddef10e1c">
<img width="1486" alt="Screenshot 2023-10-11 at 12 25 29" src="https://github.com/mrdoob/three.js/assets/11533757/ff6c5dae-a8b2-41a6-ad10-b0e4d726d5af">

### Version

0.156.1

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
Please let you help at the forum first: https://discourse.threejs.org/t/v156-1-gltfloader-cant-parse-arraybuffer-with-gltf-and-throw-an-error/56897
