### ISSUE TITLE
isWebGL2 determination algorithm is incorrect

### ISSUE THREAD

**Issue by c-smile** [mrdoob/three.js#26968]
### Description

[Here](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLCapabilities.js#L55) `isWebGL2` is determined as 

```js
const isWebGL2 = typeof WebGL2RenderingContext !== 'undefined' && gl.constructor.name === 'WebGL2RenderingContext';
```
is incorrect in the sense that `WebGL2RenderingContext` is an _interface_ but not a class strictly speaking. 
WebGL2RenderingContext is not required to be available in global namespace as there is no option to construct it normally using  `new WebGL2RenderingContext();`

### Solution

Solution could be in simple WebGL2 specific feature probe like:
```js
const isWebGL2 = typeof gl.createVertexArray == "function" ||
                              (typeof WebGL2RenderingContext !== 'undefined' && gl.constructor.name === 'WebGL2RenderingContext');
```

### Alternatives

Another option would be in providing a parameter `isWebGL2` in parameters of WebGLRenderer constructor 

### Additional context

Problem arises in various non-browser WebGL implementations like [NodeJS/ThreeJS](https://github.com/node-3d/webgl-raub) or [Sciter](https://sciter.com) that may use Three.JS on top of it.

**Comment by mrdoob** [comment]
> Problem arises in various non-browser WebGL implementations like [NodeJS/ThreeJS](https://github.com/node-3d/webgl-raub) or [Sciter](https://sciter.com) that may use Three.JS on top of it.

Could you elaborate this?

Please share a specific case where this is a problem and include the code that proves it.

**Comment by CodyJasonBennett** [comment]
> is incorrect in the sense that WebGL2RenderingContext is an interface but not a class strictly speaking. WebGL2RenderingContext is not required to be available in global namespace as there is no option to construct it normally using new WebGL2RenderingContext();

This is incorrect. `WebGL2RenderingContext` and all other WebGL resources are implemented in window scope as per 5.3 of https://registry.khronos.org/webgl/specs/latest/1.0/#5.3. I'd note for downstream that although this is an interface and not a valid class, it is expected to behave via `instanceof` and other means as such. You can find surrounding work in #25733 and an alternate solution in https://github.com/mrdoob/three.js/issues/25638#issuecomment-1461393610.

**Comment by c-smile** [comment]
In any case test for `gl.constructor.name === 'WebGL2RenderingContext'` is highly unreliable.

`object.constructor` is writable property - can be set to null for example or consider this:

```js
function WebGL2RenderingContext() {}
function WebGL2RenderingContextPlus() {}
Object.setPrototypeOf(WebGL2RenderingContextPlus.prototype, WebGL2RenderingContext.prototype);

var obj = canvas.getContext("webgl2");
Object.setPrototypeOf(obj, WebGL2RenderingContextPlus.prototype);
console.log(obj.constructor.name); // outputs WebGL2RenderingContextPlus but it was constructed as WebGL2RenderingContext
console.log(obj instanceof WebGL2RenderingContext); // outputs true
console.log(obj instanceof WebGL2RenderingContextPlus); // outputs true 
```
That above makes sense if someone wants to dynamically subclass WebGL rendering context.

in fact requirement to have WebGL2RenderingContext in global scope is a bug in Khronos specification.
Instead, returned object should have a method like `context.supports("webgl2")` or something like this.

**Comment by c-smile** [comment]
To @mrdoob on
> Could you elaborate this?

In [this project](https://github.com/node-3d/webgl-raub) WebGL2 is implemented as a native _module_ not a class.

In my [Sciter](https://sciter.com) canvas.getContext("webgl2") returns native object that has no normal prototype at all - all methods are just members of the object itself.

In browsers 
```js
WebGL2RenderingContext.prototype.createVertexArray = function() ....
```
and in Sciter glContext is constructed close to this
```js
getContext(...)
    glContext = {}
    glContext.createTexture = function() ....
    glContext.createVertexArray = function() ....
    .... 
    return glContext;
}
```

**Comment by LeviPesin** [comment]
This feels like an issue that should rather be fixed on those projects' side. They should ensure their implementation is closer to the browsers' one.

**Comment by Mugen87** [comment]
Apart from that, the `isWebGL2` flag will be removed in `r163` since WebGL 1 support is stopped. The engine will always assume the device supports WebGL 2 otherwise a error will be throw during context creation. 

Because of that, I would not invest too much time in this issue since it will go away automatically in a few releases.

**Comment by c-smile** [comment]
To @Mugen87 on

> Apart from that, the isWebGL2 flag will be removed in r163 

Radical, but will work too :)
