### ISSUE TITLE
webgpu supports vertex buffers greater than 8

### ISSUE THREAD

**Issue by momo2019** [mrdoob/three.js#26998]
### Description

I encountered the following error when loading a model with multiple morphs

![image](https://github.com/mrdoob/three.js/assets/26078793/a14ac1bd-d52a-40ac-9cec-6117d50b8975)

I would like to ask, is there any plan to solve the problem of the vertex buffer exceeding 8?

### Solution

Process it like in webgl?

### Alternatives

Process it like in webgl?

**Comment by CodyJasonBennett** [comment]
Limits are documented here https://w3.org/TR/webgpu/#limits.

**Comment by sunag** [comment]
I left it until a second moment to do https://github.com/mrdoob/three.js/pull/26325 2/2, it needs to be updated using `DataArrayTexture` to support more morphs.

**Comment by momo2019** [comment]
> I left it until a second moment to do #26325 2/2, it needs to be updated using `DataArrayTexture` to support more morphs.

great，thank you
