### ISSUE TITLE
Inconsistent raycaster intersectObjects results.

### ISSUE THREAD

**Issue by Bobetti** [mrdoob/three.js#26999]
### Description

I've been banging my head against the wall for three days already, and I don't understand what I'm doing wrong or how the raycaster should work.

In short, I have a glb model, which consists of several meshes.
All I need is to get some sort of event when a mouse is over a mesh. Nothing more. Pretty simple. 

But, I see some strange behavior. When the mouse is over the mesh - sometimes raycaster.intersectObjects(objects, true) gives results, sometimes not when the mouse moves over the same mesh.

Technically, if you start moving your mouse over the mesh from one side, intersectObjects gives the correct result. When moving over the same mesh towards the opposite mesh side, somewhere in the middle -intersectObjects shows no intersections. How is it possible?

Here is my git code: https://github.com/Bobetti/RaycasterTest.git
Everything is inside js/index.js

Please watch the attached video for clarifications: 
https://www.loom.com/share/a966a842bcbb4ae8b22dea540ee57fd4

Things I tried with no effect:

- tried obj instead of glb
- raycaster.intersectObjects(objects, true/false)
- played with material side: material.side = THREE.DoubleSide; etc
- played with raycaster.params.Points.threshold = 0.001;
- replicated all meshes using code by building meshes from scratch using BufferGeometry

What I noticed is that if the browser window gets bigger, my model should be scaled proportionally. The "dark area" on the mesh where the raycaster intersects is not working is getting bigger, too.

At some point, on resolution 3840x1600 - almost the whole mesh area shows no intersections. Is it something wrong with how I resize the model? Check Resize() function in the code.

Another thing I noticed. If I build a simple geometry plane - than raycaster intersects working fine, no problem with that.

But if I add a newly created  plane using BufferGeometry to the group, (like glb model is) this way:
let group =  new THREE.Group(); group .add(customGeometry);
raycaster shows the same inconsistent results.

The whole project was stopped because of this. 
Please help!

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

https://github.com/Bobetti/RaycasterTest.git

Loom video: https://www.loom.com/share/a966a842bcbb4ae8b22dea540ee57fd4

### Version

157

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) first. If it turns out to be a bug in the engine, we can reopen this issue.

As a first tip, I would update how you compute your mouse coordinates. Try it with: 
```js
const rect = renderer.domElement.getBoundingClientRect();
mousePos.x = ( ( event.clientX - rect.left ) / ( rect.right - rect.left ) ) * 2 - 1;
mousePos.y = - ( ( event.clientY - rect.top ) / ( rect.bottom - rect.top) ) * 2 + 1;
```
Use these coordinates directly `setFromCamera()`.
