### ISSUE TITLE
3D Models are rotated on its side in new update.

### ISSUE THREAD

**Issue by justindhillon** [mrdoob/three.js#27018]
### Description

I am following [this youtube tutorial](https://www.youtube.com/playlist?list=PLpepLKamtPjguLKYT7c66998iTaWvqSRe). But my 3d models are rotated by 90 degrees. By reverting the npm package for three from 0.157.0 to 0.146.0, this solves the issue. 

### Reproduction steps

1. git clone https://github.com/wass08/r3f-portfolio-responsive
2. update the npm package for three
3. run the project, and see the models rotated by 90 degrees.

### Code

``` bash
$ npm remove three
$ npm install three
```

### Live example

* [working website example](https://r3f-portfolio-responsive.vercel.app/)

### Screenshots

![Screenshot 2023-10-20 14 32 07](https://github.com/mrdoob/three.js/assets/145078271/77104c31-aedf-4878-85f0-0a895d3da047)

![Screenshot 2023-10-20 14 33 55](https://github.com/mrdoob/three.js/assets/145078271/a7c4b03a-9f0f-4dea-a898-d52efaa34163)

### Version

r157 & r146

**Comment by gkjohnson** [comment]
Please create a minimal, editable example in something like JSFiddle demonstrating the problem if you'd like this to be looked at.

**Comment by Mugen87** [comment]
Closing until an test case is available.

@justindhillon Also consider to ask for help at the [forum](https://discourse.threejs.org/). Normally, that is the first step. When it turns out to be a bug in the engine, an issue at GitHub is appropriate.
