### ISSUE TITLE
Unable to switch Environment to Equirect in the Editor

### ISSUE THREAD

**Issue by naoidapatrick** [mrdoob/three.js#27035]
### Description

I encountered a critical issue in the Editor, where I am no longer able to switch the Environment to Equirect. This feature was previously working as expected, but it seems to be broken in the current version.

Expected Behavior:
The Environment should switch to Equirect mode, allowing me to work with it as intended.

Actual Behavior:
The Environment does not switch to Equirect mode, and it remains in its current state. No error message or warning is displayed.

I have tried restarting the Editor and my computer, but the issue persists. This problem is hindering my ability to work on projects that require Equirect functionality.

Please investigate and resolve this issue as soon as possible, as it is affecting my workflow and project timelines.

### Reproduction steps

1. Launch the Editor.
2. Open a project or create a new one.
3. Navigate to the Environment settings.
4. Attempt to change the Environment to Equirect.

### Code

```js
// no coded needed, since it's just the editor
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

https://github.com/mrdoob/three.js/assets/49317186/1505677c-b483-4794-8db8-8210f7747224

### Version

r

### Device

Desktop

### Browser

Chrome, Safari

### OS

MacOS

**Comment by Mugen87** [comment]
The fix isn't live yet. Try it with:

https://rawcdn.githack.com/mrdoob/three.js/dev/editor/index.html
