### ISSUE TITLE
ExtrudeGeometry with SmoothShading

### ISSUE THREAD

**Issue by joergviola** [mrdoob/three.js#27058]
### Description

When extruding, especially along a path, a non-indexed BufferGeometry is created.
This prevents smooth shading, resulting in less-then-optimal render quality.

I have a solution at hand. 
Interested?
Orignal:
<img width="368" alt="Bildschirmfoto 2023-10-16 um 16 32 19" src="https://github.com/mrdoob/three.js/assets/1147908/cfa24aa6-50b5-4fab-91c6-8a7a2cdb9ffe">
Enhanced:
<img width="374" alt="Bildschirmfoto 2023-10-16 um 16 32 38" src="https://github.com/mrdoob/three.js/assets/1147908/642e66f9-f016-47d3-8971-24dbf256868d">

### Solution

I could provide a PR that adds an optional `smoothEps` parameter to the options of the ExtrudeGeometry, e.g.
```
const extrudeSettings: THREE.ExtrudeGeometryOptions = {
    steps: 100,
    curveSegments: 20,
    bevelEnabled: false,
    extrudePath: path,
    smoothEps: 0.00001,
  };
```

When provided, all vertices within the range of `smoothEps` are merged.
Then the `computeVertexNormals();` called provides for smooth shading.

### Alternatives

One could try `BufferGeometryUtils.mergeVertices`.
But that doesn't help with ExtrudeGeometry, since it requires ALL attributes of the vertices to be near of each other.

**Comment by donmccurdy** [comment]
I like the idea! Would it be possible to parameterize this as a crease angle rather than epsilon? /cc  @gkjohnson

**Comment by joergviola** [comment]
Wow - thank you for the fast response!
I'm sorry, I wasn't aware of `BufferGeometryUtils.toCreasedNormals`.
Looks like exactly what I was in need for.
Alas, in my situation, I could not get it to work this way:
```
  const bufferExtrudeGeometry = new THREE.ExtrudeGeometry(
    props.shape,
    extrudeSettings
  );

  const mergedGeometry = BufferGeometryUtils.toCreasedNormals(
    bufferExtrudeGeometry,
    Math.PI / 10
  );
```
It didn't change anything.
Am I using it wrong?

**Comment by gkjohnson** [comment]
> Am I using it wrong?

It's hard to say without a live example. Can you put together jsfiddle?

**Comment by joergviola** [comment]
I'm so sorry, I did not yet succeed in creating a jsfiddle.
Can you point me to a recipe how to create one using the current version of threejs?

**Comment by gkjohnson** [comment]
There's a link to one in the README that uses the latest three.js with an import map. You'll have to set up the example import, though:

https://jsfiddle.net/2nyxkmco/

**Comment by joergviola** [comment]
OMG, sorry I did not find that by myself!

https://jsfiddle.net/3bedrp52/

And there you can see - it works perfectly.
Sorry for having bothered you and thank for the excellent support!

I'll go home and look what happens on my side....

**Comment by joergviola** [comment]
SOlution has been provided. Thanks!
