### ISSUE TITLE
FBXLoader adds rotation discontinuities into animation

### ISSUE THREAD

**Issue by solinehayes** [mrdoob/three.js#27056]
### Description

**FBXLoader adds rotation discontinuities into animation**
When loading the FBX onto threeJS editor (or anything using FBXLoader), the displayed animation has rotation discontinuities. However, when loading the animation onto blender, the animation is good. Similarly if we convert the FBX to GLB and load it onto the threeJS editor, there is not problem either. 

Zip containing both FBX and GLB animation:
[RotationDiscontinuities.zip](https://github.com/mrdoob/three.js/files/13167729/RotationDiscontinuities.zip)

### Reproduction steps

1. Load the fbx provided onto ThreeJS editor 
2. Play the animation

or 

1. Load the FBX with the FBX loader
2. Play the animation

### Code

N/A

### Live example

* [threeJS edior](https://threejs.org/editor/)

### Screenshots

|     | ThreeJS editor | Blender |
|-----|----------------|---------|
| FBX | ![RotationDiscontinuitiesFBXTHREEJS](https://github.com/mrdoob/three.js/assets/48208691/e7c9716c-d5bc-4690-b602-af120d0e5cc1)| ![RotationDiscontinuitiesFBXBlender](https://github.com/mrdoob/three.js/assets/48208691/0bec728e-a42a-4bb3-ab06-29eb328e1d53) |
| GLB | ![RotationDiscontinuitiesGLBTHREEJS](https://github.com/mrdoob/three.js/assets/48208691/675dd526-90d9-4880-9502-9ea276612387) |         |

### Version

r157

### Device

Desktop

### Browser

Chrome

### OS

Linux

**Comment by Mugen87** [comment]
I can confirm the issue after testing with the `dev` version of the editor. Marking it as a bug.
