### ISSUE TITLE
【AxesHelper】Add getColors to obtain the current coordinate axis color

### ISSUE THREAD

**Issue by wc19950724** [mrdoob/three.js#27062]
### Description

Because THREE.AxesHelper currently has the setColors function to modify the color of the coordinate axis, I hope to add getColors to obtain the color of the coordinate axis accordingly, so that GUI and other modules can customize based on the current color of the coordinate axis

### Solution

Add the getColors function

### Alternatives

No Alternatives

**Comment by Mugen87** [comment]
I think it's valid to expect a `get*()` method when there is the respective setter. The method could look like so:
```js
getColors( xAxisColor, yAxisColor, zAxisColor ) {

	const array = this.geometry.attributes.color.array;

	xAxisColor.fromArray( array, 0 );
	yAxisColor.fromArray( array, 6 );
	zAxisColor.fromArray( array, 12 );

}
```
The target colors have to be applied by the app though.

**Comment by Mugen87** [comment]
Or we could also rename `setColors()` to `applyColors()` and let the user extract colors on app level. That works since the user has access to the geometry.

IMO, extracting colors from helpers is not a common feature so I'm not sure it's worth to add `getColors()`.

**Comment by Mugen87** [comment]
Closing this issue for now. We can reconsider on of the approaches mentioned in https://github.com/mrdoob/three.js/issues/27062#issuecomment-1792235728 when more users want `getColors()` as a convenient method. For now, the colors needs to be extracted over the `geometry` reference like demonstrated above.
