### ISSUE TITLE
I am unable to obtain the correct normal vectors.

### ISSUE THREAD

**Issue by DaikiFujiwara22** [mrdoob/three.js#27067]
### Description

I tried to perform raycasting on an IFC model using the following method to obtain the faces of the geometry and get the normal vectors,
 but there are geometries for which I cannot obtain accurate normal vectors.
[IFC.zip](https://github.com/mrdoob/three.js/files/13184199/IFC.zip)

### Code

```js
const result = this.raycaster.castRay(meshes);
const normal = result.face.normal;
```

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/112066769/e1d30367-3701-4398-a0a9-bd6347279996)

### Version

0.157.0

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Please ask at the [forum](https://discourse.threejs.org/) for help first. If it turns out to be a bug in the engine, we can reopen the issue.
