### ISSUE TITLE
webgpu shadow bug

### ISSUE THREAD

**Issue by gameatp** [mrdoob/three.js#27069]
### Description

The example of webgpu_shadowmap.html 
I added a line to turn off the shadow.
```
window.document.addEventListener("keydown", () => {
   spotLight.castShadow = false;
   dirLight.castShadow = false;
})
```
But the shadow doesn't close when I press the button

### Reproduction steps

1.
2.
3.

### Code

```js
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>three.js webgpu - shadow map</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
		<link type="text/css" rel="stylesheet" href="main.css">
	</head>
	<body>
		<div id="info">
		<a href="https://threejs.org" target="_blank" rel="noopener">three.js</a> - webgpu shadow map
		</div>

		<script type="importmap">
			{
				"imports": {
					"three": "../build/three.module.js",
					"three/addons/": "./jsm/",
					"three/nodes": "./jsm/nodes/Nodes.js"
				}
			}
		</script>

		<script type="module">

			import * as THREE from 'three';

			import WebGPU from 'three/addons/capabilities/WebGPU.js';
			import WebGPURenderer from 'three/addons/renderers/webgpu/WebGPURenderer.js';

			import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

			let camera, scene, renderer, clock;
			let dirLight, spotLight;
			let torusKnot, dirGroup;

			init();

			function init() {

				if ( WebGPU.isAvailable() === false ) {

					document.body.appendChild( WebGPU.getErrorMessage() );

					throw new Error( 'No WebGPU support' );

				}

				camera = new THREE.PerspectiveCamera( 45, window.innerWidth / window.innerHeight, 1, 1000 );
				camera.position.set( 0, 10, 20 );

				scene = new THREE.Scene();
				scene.background = new THREE.Color( 0x222244 );
				scene.fog = new THREE.Fog( 0x222244, 50, 100 );

				// lights

				scene.add( new THREE.AmbientLight( 0x444444, 2 ) );

				spotLight = new THREE.SpotLight( 0xff8888, 400 );
				spotLight.angle = Math.PI / 5;
				spotLight.penumbra = 0.3;
				spotLight.position.set( 8, 10, 5 );
				spotLight.castShadow = true;
				spotLight.shadow.camera.near = 8;
				spotLight.shadow.camera.far = 200;
				spotLight.shadow.mapSize.width = 2048;
				spotLight.shadow.mapSize.height = 2048;
				spotLight.shadow.bias = - 0.002;
				spotLight.shadow.radius = 4;
				scene.add( spotLight );


				dirLight = new THREE.DirectionalLight( 0x8888ff, 3 );
				dirLight.position.set( 3, 12, 17 );
				dirLight.castShadow = true;
				dirLight.shadow.camera.near = 0.1;
				dirLight.shadow.camera.far = 500;
				dirLight.shadow.camera.right = 17;
				dirLight.shadow.camera.left = - 17;
				dirLight.shadow.camera.top	= 17;
				dirLight.shadow.camera.bottom = - 17;
				dirLight.shadow.mapSize.width = 2048;
				dirLight.shadow.mapSize.height = 2048;
				dirLight.shadow.radius = 4;
				dirLight.shadow.bias = - 0.0005;

				dirGroup = new THREE.Group();
				dirGroup.add( dirLight );
				scene.add( dirGroup );

				// geometry

				const geometry = new THREE.TorusKnotGeometry( 25, 8, 75, 20 );
				const material = new THREE.MeshPhongMaterial( {
					color: 0x999999,
					shininess: 0,
					specular: 0x222222
				} );

				torusKnot = new THREE.Mesh( geometry, material );
				torusKnot.scale.multiplyScalar( 1 / 18 );
				torusKnot.position.y = 3;
				torusKnot.castShadow = true;
				torusKnot.receiveShadow = true;
				scene.add( torusKnot );

				const cylinderGeometry = new THREE.CylinderGeometry( 0.75, 0.75, 7, 32 );

				const pillar1 = new THREE.Mesh( cylinderGeometry, material );
				pillar1.position.set( 8, 3.5, 8 );
				pillar1.castShadow = true;
				pillar1.receiveShadow = true;

				const pillar2 = pillar1.clone();
				pillar2.position.set( 8, 3.5, - 8 );
				const pillar3 = pillar1.clone();
				pillar3.position.set( - 8, 3.5, 8 );
				const pillar4 = pillar1.clone();
				pillar4.position.set( - 8, 3.5, - 8 );

				scene.add( pillar1 );
				scene.add( pillar2 );
				scene.add( pillar3 );
				scene.add( pillar4 );

				const planeGeometry = new THREE.PlaneGeometry( 200, 200 );
				const planeMaterial = new THREE.MeshPhongMaterial( {
					color: 0x999999,
					shininess: 0,
					specular: 0x111111
				} );

				const ground = new THREE.Mesh( planeGeometry, planeMaterial );
				ground.rotation.x = - Math.PI / 2;
				ground.scale.multiplyScalar( 3 );
				ground.castShadow = true;
				ground.receiveShadow = true;
				scene.add( ground );

				// renderer

				renderer = new WebGPURenderer( { antialias: true } );
				renderer.setPixelRatio( window.devicePixelRatio );
				renderer.setSize( window.innerWidth, window.innerHeight );
				renderer.setAnimationLoop( animate );
				renderer.toneMapping = THREE.ACESFilmicToneMapping;
				document.body.appendChild( renderer.domElement );

				// Mouse control
				const controls = new OrbitControls( camera, renderer.domElement );
				controls.target.set( 0, 2, 0 );
				controls.minDistance = 7;
				controls.maxDistance = 40;
				controls.update();

				clock = new THREE.Clock();

				window.addEventListener( 'resize', resize );

				window.document.addEventListener("keydown", () => {
					spotLight.castShadow = false;
					dirLight.castShadow = false;
				})

			}

			function resize() {

				camera.aspect = window.innerWidth / window.innerHeight;
				camera.updateProjectionMatrix();

				renderer.setSize( window.innerWidth, window.innerHeight );

			}

			function animate( time ) {

				const delta = clock.getDelta();

				torusKnot.rotation.x += 0.25 * delta;
				torusKnot.rotation.y += 0.5 * delta;
				torusKnot.rotation.z += 1 * delta;

				dirGroup.rotation.y += 0.7 * delta;
				dirLight.position.z = 17 + Math.sin( time * 0.001 ) * 5;

				renderer.render( scene, camera );

			}

		</script>
	</body>
</html>

```

### Live example

https://jsfiddle.net/v74rmg16/3/

### Version

r157

**Comment by Mugen87** [comment]
I can reproduce. The shadows should disappear similar when using `WebGLRenderer`.

BTW: I have added a live example so it's easier to reproduce the issue.

**Comment by gameatp** [comment]
> I can reproduce. The shadows should disappear similar when using `WebGLRenderer`.
> 
> BTW: I have added a live example so it's easier to reproduce the issue.


Yes, WebGLRenderer is correct. I looked at the code and it seems that the file AnalyticLightNode.js needs to be modified. colorNode needs to be changed according to the value of castShadow

`this.colorNode = this.colorNode.mul( shadowNode );`

// fullcode
`import LightingNode from './LightingNode.js';
import { NodeUpdateType } from '../core/constants.js';
import { uniform } from '../core/UniformNode.js';
import { addNodeClass } from '../core/Node.js';
import { vec3 } from '../shadernode/ShaderNode.js';
import { reference } from '../accessors/ReferenceNode.js';
import { texture } from '../accessors/TextureNode.js';
import { positionWorld } from '../accessors/PositionNode.js';
import { cond } from '../math/CondNode.js';
import MeshBasicNodeMaterial from '../materials/MeshBasicNodeMaterial.js';

import { Color, DepthTexture, NearestFilter } from 'three';

let depthMaterial = null;

class AnalyticLightNode extends LightingNode {

	constructor( light = null ) {

		super();

		this.updateType = NodeUpdateType.FRAME;

		this.light = light;

		this.rtt = null;
		this.shadowNode = null;

		this.color = new Color();
		this.colorNode = uniform( this.color );

	}

	getHash( /*builder*/ ) {

		return this.light.uuid;

	}

	constructShadow( builder ) {

		let shadowNode = this.shadowNode;

		if ( shadowNode === null ) {

			if ( depthMaterial === null ) depthMaterial = new MeshBasicNodeMaterial();

			const shadow = this.light.shadow;
			const rtt = builder.getRenderTarget( shadow.mapSize.width, shadow.mapSize.height );

			const depthTexture = new DepthTexture();
			depthTexture.minFilter = NearestFilter;
			depthTexture.magFilter = NearestFilter;

			rtt.depthTexture = depthTexture;

			shadow.camera.updateProjectionMatrix();

			//

			const bias = reference( 'bias', 'float', shadow );

			//const diffuseFactor = normalView.dot( objectViewPosition( this.light ).sub( positionView ).normalize().negate() );
			//bias = mix( bias, 0, diffuseFactor );

			let shadowCoord = uniform( shadow.matrix ).mul( positionWorld );
			shadowCoord = shadowCoord.xyz.div( shadowCoord.w );

			shadowCoord = vec3(
				shadowCoord.x,
				shadowCoord.y.oneMinus(),
				shadowCoord.z
			);

			// @TODO: Optimize using WebGPU compare-sampler

			let depth = texture( depthTexture, shadowCoord.xy );
			depth = depth.mul( .5 ).add( .5 ).add( bias );

			shadowNode = cond( shadowCoord.z.lessThan( depth ).or( shadowCoord.y.lessThan( .000001 ) /*@TODO: find the cause and remove it soon */ ), 1, 0 );
			//shadowNode = step( shadowCoord.z, depth );

			//

			this.rtt = rtt;
			this.colorNode = this.colorNode.mul( shadowNode );

			this.shadowNode = shadowNode;

			//

			this.updateBeforeType = NodeUpdateType.RENDER;

		}

	}

	construct( builder ) {

		if ( this.light.castShadow ) this.constructShadow( builder );

	}

	updateShadow( frame ) {

		const { rtt, light } = this;
		const { renderer, scene } = frame;

		scene.overrideMaterial = depthMaterial;

		rtt.setSize( light.shadow.mapSize.width, light.shadow.mapSize.height );

		light.shadow.updateMatrices( light );

		renderer.setRenderTarget( rtt );
		renderer.render( scene, light.shadow.camera );
		renderer.setRenderTarget( null );

		scene.overrideMaterial = null;

	}

	updateBefore( frame ) {

		const { light } = this;

		if ( light.castShadow ) this.updateShadow( frame );

	}

	update( frame ) {

		const { light } = this;

		this.color.copy( light.color ).multiplyScalar( light.intensity );

	}

}

export default AnalyticLightNode;

addNodeClass( AnalyticLightNode );
`
