### ISSUE TITLE
Unify typeof .userData property in @types/three

### ISSUE THREAD

**Issue by hanvit-eazel** [mrdoob/three.js#27070]
### Description

I'm not sure if this topic belongs in three.js or @types/three,
but I'm posting the request there first.

Here are the classes that currently use the userData property in three.js.
(captured from @types/three r155.1)

<img width="520" alt="hasUserData" src="https://github.com/mrdoob/three.js/assets/82128390/0bb2f1c6-a338-4e2c-bbe2-7b0b38957faf">

- Object3D
- BufferGeometry
- Material
- Texture
- (UserDataNode, GLTF)

But as you can see, Object3D, BufferGeometry and Material, Texture have different userData types.

This situation caused me the following type issue.

<img width="570" alt="error" src="https://github.com/mrdoob/three.js/assets/82128390/2e629873-132b-45aa-870e-94867dac5910">

```
type UserDataWrappedObject3D = Object3D & {
    userData: { myCustomValue: number }
}

type UserDataWrappedMaterial = Material & {
    userData: { myCustomValue: number }
}

let a: UserDataWrappedObject3D 
let b: UserDataWrappedMaterial 

a.userData.myCustomValue
b.userData.myCustomValue // error from userData inferred as any
```

### Solution

If we want to allow wrapping of userData in the above manner, I suggest replacing the userData type of Materials and Textures with Object3D or BufferGeometry's userData type.

```
// in Material class
...
userData: { [key: string]: any };
...
```

### Alternatives

Or we can apply `Record` type for userData as it commented in code.

**Comment by mrdoob** [comment]
> I'm not sure if this topic belongs in three.js or @types/three
> but I'm posting the request there first.

I think it'd be better to post it in @types/three first, we already have too many issues/PRs to deal with...

**Comment by hanvit-eazel** [comment]
Thanks!
