### ISSUE TITLE
OutLineEffect causes THREE.doubleSide mesh's backSide alphaTest fail.

### ISSUE THREAD

**Issue by sdarpeng** [mrdoob/three.js#27082]
### Description

Material setting as the following code bracket. But alphaTest will fail whie 

`js
effect = new OutlineEffect( renderer );
`

### Reproduction steps

1.
2.
3.

### Code

```js
		color: 0xffffff,
		map: diffuseMap,
		side: THREE.DoubleSide,
		alphaTest: _alphaTest,
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

157

**Comment by Mugen87** [comment]
@sdarpeng Next time when you report an issue, please invest more time in properly fill out the issue template. Setting up a live example that demonstrates the issue isn't difficult. We already provide the respective templates.

Here is a live example that shows how alpha testing doesn't work with `OutlineEffect`: https://jsfiddle.net/1qvoxek5/ 

Indeed, alpha testing (as well as alpha maps) are not supported when using `OutlineEffect`. The way `OutlineEffect` is implemented makes it complicated to implement this feature. I would consider this issue as a limitation of the current technique.

**Comment by gkjohnson** [comment]
> The way OutlineEffect is implemented makes it complicated to implement this feature. I would consider this issue as a limitation of the current technique.

I don't think it's possible to implement an outline or alpha hash using an inverted hull geometry technique - at least not that I can think of. If you need outlines for such a material you'll have to use another approach like screenspace outline techniques. I recommend asking for help at the forum for this.
