### ISSUE TITLE
PointerEvent can’t be remove on CSS3DObject

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#27093]
### Description

Impossible to remove the user select / user interaction on CSS3DObject 

It’s seems like an iOS bug ( safari/ chrome)
Version tested iPhone / iOS 16.6

### Reproduction steps

1. Try on iOS any css3d example 

### Code

I try using ‘addEventListener’ and other technique to prevent the default but it didn’t work.

### Live example

https://threejs.org/examples/?q=css#css3d_periodictable

### Screenshots

![IMG_4028](https://github.com/mrdoob/three.js/assets/213351/00ed1ccd-04fd-4258-aa61-1371ac532b98)
![IMG_4029](https://github.com/mrdoob/three.js/assets/213351/b691d8b8-ee05-4df6-82ac-eb6311a889cd)

### Version

R158

### Device

Mobile

### Browser

Safari

### OS

iOS

**Comment by Mugen87** [comment]
Does `user-select: none;` applied on the `element` CSS class work?

**Comment by Makio64** [comment]
> Does `user-select: none;` applied on the `element` CSS class work?

I tried adding it on the element but it doesn't work, 

on `iPad / iOS 17.2Beta` it seems to behave correctly

**Comment by Makio64** [comment]
Just tested on `iPhone / iOS17.1,` same error

> Can you make a test with the following site? https://developer.mozilla.org/en-US/docs/Web/CSS/user-select
> 
> In the demo you can choose between `user-select: auto;` and `user-select: none;`. Can you still select the bold text with the `none` setting?

On the demo I can’t select the text with `user-select: none`

 I will check on `iPhone iOS17.2`

**Comment by Mugen87** [comment]
> On the demo I can’t select the text with user-select: none

Um, maybe the issue only appears when CSS 3D transformations are applied to the DOM elements.

**Comment by Mugen87** [comment]
I guess it's better to report this issue to Apple/WebKit instead.
