### ISSUE TITLE
Crash if using OutlinePass in a scene with node materials and standard materials

### ISSUE THREAD

**Issue by TobiasNoell** [mrdoob/three.js#27095]
### Description

Three has problems to render an outline effect (using `OutlinePass`) in a scene with mixed objects, having **both** node materials and standard materials. This happens as soon as there is one object with a node material present in the scene.
As soon as the `outlinePass.selectedObjects` is set to any object, the following runtime error is thrown:

```
three.module.js:17985 Uncaught TypeError: Cannot read properties of undefined (reading 'toArray')
    at flatten (three.module.js:17985:13)
    at PureArrayUniform.setValueV3fArray [as setValue] (three.module.js:18588:15)
    at WebGLUniforms.upload (three.module.js:19017:7)
    at setProgram (three.module.js:29901:19)
    at WebGLRenderer.renderBufferDirect (three.module.js:28759:20)
    at renderObject (three.module.js:29451:11)
    at renderObjects (three.module.js:29420:6)
    at renderScene (three.module.js:29289:36)
    at WebGLRenderer.render (three.module.js:29107:5)
    at RenderPass.render (RenderPass.js:71:12)
```

When all objects **having node materials** are removed from the scene, everything is working as expected.

It is also possible to set `outlinePass.prepareMaskMaterial.lights = true` which enables using the outline effect **for any object having a node material** and makes above error go away. However, as soon as `outlinePass.selectedObjects` is then set to an object **without a node material** Three again crashes with the same error.

### Reproduction steps

1. Create a scene with two objects, one having a standard material, one having a node material
2. Add an outline pass as effect
3. Set `outlinePass.selectedObjects` to the object having the node material
4. Three crashes with said error 
5. Set `outlinePass.selectedObjects` to the object having the standard material
6. Three crashes again with the same error
7. Now remove the object with the node material from the scene
8. The object with the standard material is now rendered including outline without crash

### Code

```js
import * as THREE from 'three';
import { OutlinePass } from "three/examples/postprocessing/OutlinePass";
import { EffectComposer } from "three/examples/postprocessing/EffectComposer";
import { RenderPass } from "three/examples/postprocessing/RenderPass";
import { nodeFrame } from "three/examples/renderers/webgl-legacy/nodes/WebGLNodes";
import * as THREENodes from "three/nodes"

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );

const geometry = new THREE.BoxGeometry( 1, 1, 1 );
const material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
const node_material = new THREENodes.MeshStandardNodeMaterial( { colorNode: THREENodes.color( 0x00ff00 ) } );

const cube = new THREE.Mesh( geometry, material );
cube.position.x = -1;
scene.add(cube);

const node_cube = new THREE.Mesh( geometry, node_material );
node_cube.position.x = 1;
scene.add(node_cube);

const light = new THREE.PointLight( 0xffffff, 30 );
light.castShadow = true
light.position.z = 5;
scene.add(light);

const renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );

const composer = new EffectComposer(renderer);
const renderPass = new RenderPass( scene, camera );
composer.addPass( renderPass );
const outlinePass = new OutlinePass(new THREE.Vector2(window.innerWidth, window.innerHeight), scene, camera);
//outlinePass.selectedObjects = [cube]; // <- !!!!!!!! Crashes if this is uncommented !!!!!!!!
//outlinePass.prepareMaskMaterial.lights = true;
composer.addPass(outlinePass);

document.body.appendChild( renderer.domElement );

camera.position.z = 5;

function animate() {
	requestAnimationFrame( animate );
  
 	nodeFrame.update();

	cube.rotation.x += 0.01;
	cube.rotation.y += 0.01;
  
	node_cube.rotation.x += 0.01;
	node_cube.rotation.y += 0.01;

	composer.render();
}

animate();
```

### Live example

[jsfiddle example](https://jsfiddle.net/TobiasNoell/6qdcb4y3/130/)
(Takes a bit to load, you should see two spinning cubes, you can then uncomment the problematic line to make the error appear)

### Version

r157

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by TobiasNoell** [comment]
For context: In our use case we have multiple objects in the scene, some with node materials and some with classic materials.

Objects can be selected by the user, selected objects are rendered with the `OutlinePass`.
Selection works if the first object selected is an object **with classic material**, afterwards also objects **with node materials** can be selected. If the first selected object happens to have a node material, it crashes.

If setting `outlinePass.prepareMaskMaterial.lights = true` it behaves vice-versa: I.e. it works if the first object selected **has a node material**, afterwards also objects with classical materials can be selected. But if the first object has **a classical material** it again crashes.

**Comment by Mugen87** [comment]
Thanks for reporting! The issue is not specific to `OutlinePass` but to `Scene.overrideMaterial` in general. Here is a simplified live example without post processing:

https://jsfiddle.net/a8hntuok/

**Comment by TobiasNoell** [comment]
Thanks for the feedback! I also had the impression that was is somewhat deeper issue unrelated to `OutlinePass`. Could this also explain the issues we were discussing a while back in [this](https://discourse.threejs.org/t/crash-in-refreshuniformsdistance-when-light-castshadow-is-true/56981) thread?

**Comment by TobiasNoell** [comment]
Yes, I think that's the case as they are rendered with a depth material for the shadow mapping.
https://github.com/mrdoob/three.js/blob/79cc152ddfa7fdd2265782732bcbfdb42b07391e/src/renderers/webgl/WebGLShadowMap.js#L366

**Comment by Mugen87** [comment]
At least we finally know what's going wrong 😇 .

**Comment by TobiasNoell** [comment]
I quickly wanted to test it in my app by locally reproducing your [PR](https://github.com/mrdoob/three.js/pull/27097) in my node_modules folder
I modified node_modules\three\examples\jsm\renderers\webgl-legacy\nodes\WebGLNodes.js accordingly
However, the sources used by the app does not seem to be coming from there. I can even delete this file and still everything can be run. Which file would I need to modify then instead to reproduce your changes?

**Comment by TobiasNoell** [comment]
Ok, never mind, it was a caching issue!
Your PR fixes both issues, the outline rendering and the issue in [this](https://discourse.threejs.org/t/crash-in-refreshuniformsdistance-when-light-castshadow-is-true/56981) thread 👍
