### ISSUE TITLE
InstancedMesh: Tangents are not transformed by instance matrices

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#27116]
### Description

When adding batching shading I noticed that the tangent seemed to not be transformed by the instance matrix - is this a bug?

https://github.com/mrdoob/three.js/blob/0319a2a421aea8ea3aa4b45235ce06da7be8235f/src/renderers/shaders/ShaderChunk/defaultnormal_vertex.glsl.js#L25-L35

### Reproduction steps

Issue found by looking at shader code.

### Code

From `defaultnormal_vertex.glsl.js`:
```js
#ifdef USE_TANGENT

	vec3 transformedTangent = ( modelViewMatrix * vec4( objectTangent, 0.0 ) ).xyz;

	#ifdef FLIP_SIDED

		transformedTangent = - transformedTangent;

	#endif

#endif
```

### Live example

Issue found by looking at shader code.

### Version

dev

**Comment by Mugen87** [comment]
> is this a bug?

IMO, yes. Since the tangent is multiplied with `modelViewMatrix`, the additional transformations of `instanceMatrix` should be honored as well.
