### ISSUE TITLE
Can getObjectsByProperty supports RegExp?

### ISSUE THREAD

**Issue by sdarpeng** [mrdoob/three.js#27124]
### Description

Everytime while loader works, people need to setup workflow by several getObject in traverse cycle.
Such as:
It is really low efficiency,right?
```
                            model.traverse( function ( object ) {
                                if( object.name.indexOf('Head') !== -1 && object.isBone  ){
                                    headBoneStack.push(object);
                                }
                                //if( object.name.indexOf('J_Sec') !== -1 && object.parent.name.indexOf('Head') !== -1) {
                                if( object.name.indexOf('J_Sec') !== -1 ) {
                                    hairBones.push(object);
                                }
                                if( object.name.indexOf( 'collider' ) !==-1 ){
                                    collidersAgent.push(object);
                                }
                            });
```

### Solution

I think RegExp can help us work faster,like:
```
                        headBoneStack = model.getObjectsByProperty( 'name', /Head/i );
                        hairBones = model.getObjectsByProperty( 'name', /J_Sec/i );
                        collidersAgent = model.getObjectsByProperty( 'name', /collider/i );
```

### Alternatives

Support RegExp please.

**Comment by gkjohnson** [comment]
Your proposed solution would be less efficient since `getObjectsByProperty` performs a new traversal of the whole hierarchy.

**Comment by Mugen87** [comment]
> It is really low efficiency,right?

It's totally fine to traverse an asset once after loading and save references to 3D objects in custom data structures. What you have implemented in your first post is actually more performant than multiple calls of `getObjectBy*()` methods. 

But  to be clear using `getObjectBy*()` is also fine as long as you don't call these methods per simulation step (or every time when you need an object reference).
