### ISSUE TITLE
Scenario issues

### ISSUE THREAD

**Issue by SouthChinaHuihuisauce** [mrdoob/three.js#27125]
### Description

I used Vue2 and three. js to render a 3D mesh model. When I created two scenes of different sizes on two different pages, when I switched from a page with a small scene to a page with a large scene, the page with a large scene would become the size of the scene in the page with a small scene.

### Reproduction steps

1.Create two scenes of the same size on two pages
2.Switch from pages in small scenes to pages in large scenes

### Code

```js
      const element2 = document.getElementById("container");
      renderer2 = new THREE.WebGLRenderer({ antialias: true, alpha: true });
      renderer2.setSize(element2.clientWidth, element2.clientHeight); // 设置渲染区域尺寸
      console.log('原本渲染尺寸',element2.clientHeight,element2.clientWidth)
      renderer2.setClearColor(0xCCCCCC, 0.9); // 设置背景颜色
      element2.appendChild(renderer2.domElement);

```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

0.154.0

**Comment by SouthChinaHuihuisauce** [comment]
![hope](https://github.com/mrdoob/three.js/a![small](https://github.com/mrdoob/three.js/assets/95074184/09e0b530-7c5d-45f5-a9fa-4aa871327257)ts/95074184/15e87639-6a99-4834-8e90-82f919e8a6dc)
![res](https://github.com/mrdoob/three.js/assets/95074184/b07b2f38-307b-4f64-8f6a-980b797db11f)

**Comment by SouthChinaHuihuisauce** [comment]
![hope](https://github.com/mrdoob/three.js/assets/95074184/bc5b98a6-4eae-48ff-a9d0-219eacf64a77)
![res](https://github.com/mrdoob/three.js/assets/95074184/16106b37-9032-4aa2-bb4e-a14e50e3c069)
![small](https://github.com/mrdoob/three.js/assets/95074184/9747e2e6-b8c6-4011-833b-0fa1a12edfd2)

**Comment by gkjohnson** [comment]
Please use the forum to ask the community questions if you need help:

https://discourse.threejs.org/
