### ISSUE TITLE
WebGPURenderer: Failed to execute 'copyExternalImageToTexture' on 'GPUQueue' 

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#27126]
### Description

Seems like there's something wrong with texture handling in ChromeOS.

> TypeError: Failed to execute 'copyExternalImageToTexture' on 'GPUQueue': Failed to read the 'source' property from 'GPUImageCopyExternalImage': The provided value is not of type '(HTMLCanvasElement or HTMLVideoElement or ImageBitmap or OffscreenCanvas or VideoFrame)'

All these examples are failing at the moment:
https://threejs.org/examples/?q=webgpu#webgpu_clearcoat
https://threejs.org/examples/?q=webgpu#webgpu_compute_particles
https://threejs.org/examples/?q=webgpu#webgpu_cubemap_adjustments
https://threejs.org/examples/?q=webgpu#webgpu_cubemap_dynamic
https://threejs.org/examples/?q=webgpu#webgpu_cubemap_mix
https://threejs.org/examples/?q=webgpu#webgpu_equirectangular
https://threejs.org/examples/?q=webgpu#webgpu_instance_uniform
https://threejs.org/examples/?q=webgpu#webgpu_lights_phong
https://threejs.org/examples/?q=webgpu#webgpu_lights_selective
https://threejs.org/examples/?q=webgpu#webgpu_materials
https://threejs.org/examples/?q=webgpu#webgpu_multiple_rendertargets
https://threejs.org/examples/?q=webgpu#webgpu_particles
https://threejs.org/examples/?q=webgpu#webgpu_rtt
https://threejs.org/examples/?q=webgpu#webgpu_sandbox
https://threejs.org/examples/?q=webgpu#webgpu_sprites
https://threejs.org/examples/?q=webgpu#webgpu_tsl_editor

### Reproduction steps

1. Visit any of the links in the list

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

![Screenshot 2023-11-06 13 13 47](https://github.com/mrdoob/three.js/assets/97088/d3af8be0-1c38-4a50-abdd-e36629671a54)

### Version

r158

### Device

Desktop

### Browser

Chrome

### OS

ChromeOS

**Comment by sunag** [comment]
Maybe it could be related to https://github.com/mrdoob/three.js/pull/27021

**Comment by mrdoob** [comment]
After updating to ChromeOS 118.0.5993.124 the error is gone... 🫡
