### ISSUE TITLE
Box3.setFromObject doesn't check if object passed by argument has its own computeBoundingBox implementation

### ISSUE THREAD

**Issue by rubeniskov** [mrdoob/three.js#27132]
### Description

I had implement an Object3D with custom `computeBoundingBox` implementation but when I use BoxHelper, to display it internally this helper calls Box3.setFromObject

https://github.com/mrdoob/three.js/blob/5f4f0b29a9045acb6c1ff916d3dc7d241385a5c2/src/helpers/BoxHelper.js#L31-L45

This methods use `expandByObject`
https://github.com/mrdoob/three.js/blob/5f4f0b29a9045acb6c1ff916d3dc7d241385a5c2/src/math/Box3.js#L76-L82

Which doesn't check if the object passed by argument has its own compute boundingBox implementation so the object passed by args can't be un-opionated when using this helper

https://github.com/mrdoob/three.js/blob/5f4f0b29a9045acb6c1ff916d3dc7d241385a5c2/src/math/Box3.js#L155-L237

### Reproduction steps

1. Just pass an object with custom computeBoundingBox this will be never called

### Code

```js
// code goes here
```

### Live example

TODO

### Version

r0.156.1

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
I think it should work if you assign `null` to a `boundingBox` property of your object. Can you give that a try?

**Comment by Mugen87** [comment]
Closing. We can reopen if the above suggestion doesn't work.
