### ISSUE TITLE
USDZExporter flipped Normals

### ISSUE THREAD

**Issue by CrystalDesignMT** [mrdoob/three.js#27158]
### Description

When loading certain GLB's into the Google ModelViewer it show's the model correctly in the three.js viewport.

Only on iPhone the Model has flipped normals in AR. 
Here QuickLook is used which needs USDZ files that are generated by converting the original glb trough the Three.js USDZExporter.
[Issue on google/model-viewer](https://github.com/google/model-viewer/issues/4434)
[Reproduction Demo](https://glitch.com/edit/#!/boatneck-twisty-bellusaurus?path=index.html%3A40%3A0)

### Reproduction steps

1. Open the reproduction scene 
2. Open the link of the preview on iPhone
3. Open the Model in AR

### Code

https://glitch.com/edit/#!/boatneck-twisty-bellusaurus?path=index.html%3A40%3A0

### Live example

* [glitch](https://glitch.com/edit/#!/boatneck-twisty-bellusaurus?path=index.html%3A40%3A0)

### Version

^0.154.0

### Device

Mobile

### Browser

Safari

### OS

MacOS

**Comment by Mugen87** [comment]
When opening the glitch, I see the following alert:

> There was an error starting the editor. Maybe try to reload?

Can you try to share one of your test glbs directly in this issue?

**Comment by CrystalDesignMT** [comment]
hm works for me, anyway here is the glb used in the demo:
https://gwcstoragedservices.blob.core.windows.net/diva3darchiv/quick_look_test.glb

**Comment by Mugen87** [comment]
Sidenote: `USDZLoader` can properly load the file back so there must be a compatibility issue with QuickLook.

**Comment by jabri62018** [comment]
https://m.facebook.com/story.php?story_fbid=pfbid02PxQr4k92s7Ea4eSM2tyT6fq2x4Ym3azpWVS8pYFvnPaqZyUZmVEeKdEa6rAvqLRMl&id=100069268520164&sfnsn=mo

👁️🇵🇸🇵🇸🟤🇾🇪🚓🇾🇪🇾🇪
ياخبرة.....
الذي يعرف ينزل هذا الفيديو ورابطة هو::::

https://www.facebook.com/100025489485753/posts/pfbid0SNe14C7pKXXFybtmrpzmYTe8od7wD9LSq9b2GuFsHTipmavfnwBKWnA765nkQA3Ql/?app=fbl

انا مشغول ومقيد بالصلاحيات....

Who can download that vedio?

👁️🦁🇵🇸
🇾🇪🚓🦁🇵🇸👁️🇵🇸🇵🇸🇵🇸
#Al-Aqsa_Flood
#Here_Yemen
#Here_Palestine
O people, listen and be aware:::

You, not me, not Sanaa, not Aden, not Yemen. We say:::: not Gaza, Al-Aqsa,
Jerusalem, Palestine, and...
We are surrounded, so no:
- Electricity and gas (we have no light)
- Water (And We made from water every living thing)
- Wheat (food)
- Treatment (diseases)
- Salaries (non-income)
- Internet (no connection)
- Petroleum and its derivatives (immobile)
- The entire infrastructure was destroyed. (We have no roof)
9 years ago for the war of aggression against Yemen... and before that 6
years of transitional phase and the Arab Spring and before that 6 years of
the Saada wars, and now you know what today’s events are? ▄ Hunger - thirst
- diseases - siege - killing - kidnapping - displacement - division -
displacement - colonization...

I forgot to mention what we have?
- We have independence and freedom, and there is no guardianship over the
Republic of Yemen, and Bayt Al-Maqdis (Al-Aqsa - Haziz - Bayt Al-Jabri) is
an endowment for all Muslims.

✍ #Abdulla_AlJabri
- Sanaa... 4/24/1445 AH
Wed... 8/11/2023AD
🇾🇪🚓🦁🇵🇸👁️🇵🇸🇵🇸
🇾🇪🚓🦁🇵🇸👁️
#طوفان_الاقصى
#هنا_اليمن
#هنا_فلسطين
ايها الناس اسمعوا وعوا :::

انت بل انا بل صنعاء بل عدن بل اليمن نقول:::: بل غزة والاقصى والقدس وفلسطين
و ...
نحن محاصرون فلا:
- كهرباء وغاز (لا نور لنا)
- ماء (وجعلنا من الماء كل شيئا حيا)
- قمح (طعام)
- علاج (امراض)
- مرتبات (عديمي دخل)
- انترنت (عديمي تواصل)
- بترول ومشتقاتة (عديمي الحركة)
- البنية التحتية بالكامل دمرت.(لا سقف لنا)
منذ 9 سنوات لحرب العدوان لليمن...وقبلها 6 سنوات مرحلة انتقالية والربيع
العربي وقبلها 6 سنوات لحروب صعدة والان تعرفون ماهي احداث اليوم?▄ جوع- عطش-
امراض- حصار-قتل-خطف-تشربد-تقسيم- تهجير-استعمار...

نسيت ان اذكر ماذا نملك?
- نملك الاستقلال والحرية ولا توجد وصاية على الجمهورية اليمنية وبيت
المقدس(الاقصى-حزيز-بيت الجبري) وقف ذرية لجميع المسلمين.

✍ #عبدالله_الجبري
- صنعاء... 24/4/1445 هجري
الاربعاء... 8/11/2023م
🇾🇪🚓🦁🇵🇸👁️🇵🇸🇵🇸

**Comment by WestLangley** [comment]
>Something with the normals isn't right.

It appears to be rendering back faces, which would imply a winding order issue -- not a normals issue.

**Comment by WestLangley** [comment]
>Something with the normals isn't right.

It does appear to be rendering back faces, which would imply a winding order issue.

**Comment by WestLangley** [comment]
In fact, the sample .glb file's hierarchy contains a node with a negative determinant -- i.e., the transform is a reflection matrix.

`WebGLRenderer` handles this gracefully by flipping the front face winding order.

**Comment by Mugen87** [comment]
So I guess the solution here is to fix the asset during the design phase so a negative determinant does not appear in the object hierarchy in the first place.

@CrystalDesignMT The idea is to remove the negative scale from the y-component from the second node of the object hierarchy. If you then reset the node's rotation as well, the asset looks like so in QuickLook:

<img width="964" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/f376e60f-ea02-480e-97ba-1111661cdd93">

Granted, the asset is mirrored but this should be fixed when you create the asset in your DCC tool. Just make sure you don't use negative scaling for that.

**Comment by sreyemnayr** [comment]
I wonder if this is the same/similar issue we're facing with our USDZs appearing face-down only in AR mode: https://codepen.io/strangeruff/full/poGOapO
Something's going wonky with the USDZ generation from the GLB (which appears correctly)
