### ISSUE TITLE
ImageLoader ignores credentials

### ISSUE THREAD

**Issue by arghideutis** [mrdoob/three.js#27173]
### Description

Making a request with a class that implement ImageLoader (e.s. TextureLoader) gives "Unhautorized", even if authorization header is set calling withCredentials() and setRequestHeader() methods. Loading the same file with FileLoader class works.

### Reproduction steps

1. Create a TextureLoader
2. Set bearer token calling withCredentials() and setRequestHeader()
3. Call load or loadAsync methods

### Code

const loader = new THREE.TextureLoader()
loader.setWithCredentials(true)
loader.setRequestHeader({ Authorization: 'Bearer token' })
loader.loadfilepath)

### Live example

No live example

### Version

r158

### Device

Desktop

### Browser

Chrome

### OS

Linux

**Comment by Mugen87** [comment]
`ImageLoader` relies on the HTML5 image element which does not allow to configure `credentials`. Merging this issue into #10439

**Comment by jabri62018** [comment]
👁️🇵🇸🇵🇸🟤🇾🇪🚓🇾🇪🇾🇪
ياخبرة.....
الذي يعرف ينزل هذا الفيديو ورابطة هو::::

https://www.facebook.com/100025489485753/posts/pfbid0SNe14C7pKXXFybtmrpzmYTe8od7wD9LSq9b2GuFsHTipmavfnwBKWnA765nkQA3Ql/?app=fbl

انا مشغول ومقيد بالصلاحيات....

Who can download that vedio?

👁️🦁🇵🇸
🇾🇪🚓🦁🇵🇸👁️🇵🇸🇵🇸🇵🇸
#Al-Aqsa_Flood
#Here_Yemen
#Here_Palestine
O people, listen and be aware:::

You, not me, not Sanaa, not Aden, not Yemen. We say:::: not Gaza, Al-Aqsa,
Jerusalem, Palestine, and...
We are surrounded, so no:
- Electricity and gas (we have no light)
- Water (And We made from water every living thing)
- Wheat (food)
- Treatment (diseases)
- Salaries (non-income)
- Internet (no connection)
- Petroleum and its derivatives (immobile)
- The entire infrastructure was destroyed. (We have no roof)
9 years ago for the war of aggression against Yemen... and before that 6
years of transitional phase and the Arab Spring and before that 6 years of
the Saada wars, and now you know what today’s events are? ▄ Hunger - thirst
- diseases - siege - killing - kidnapping - displacement - division -
displacement - colonization...

I forgot to mention what we have?
- We have independence and freedom, and there is no guardianship over the
Republic of Yemen, and Bayt Al-Maqdis (Al-Aqsa - Haziz - Bayt Al-Jabri) is
an endowment for all Muslims.

✍ #Abdulla_AlJabri
- Sanaa... 4/26/1445 AH
Friday.. 11/10/2023 AD
🇾🇪🚓🦁🇵🇸👁️🇵🇸🇵🇸
🇾🇪🚓🦁🇵🇸👁️
#طوفان_الاقصى
#هنا_اليمن
#هنا_فلسطين
ايها الناس اسمعوا وعوا :::

انت بل انا بل صنعاء بل عدن بل اليمن نقول:::: بل غزة والاقصى والقدس وفلسطين
و ...
نحن محاصرون فلا:
- كهرباء وغاز (لا نور لنا)
- ماء (وجعلنا من الماء كل شيئا حيا)
- قمح (طعام)
- علاج (امراض)
- مرتبات (عديمي دخل)
- انترنت (عديمي تواصل)
- بترول ومشتقاتة (عديمي الحركة)
- البنية التحتية بالكامل دمرت.(لا سقف لنا)
منذ 9 سنوات لحرب العدوان لليمن...وقبلها 6 سنوات مرحلة انتقالية والربيع
العربي وقبلها 6 سنوات لحروب صعدة والان تعرفون ماهي احداث اليوم?▄ جوع- عطش-
امراض- حصار-قتل-خطف-تشربد-تقسيم- تهجير-استعمار...

نسيت ان اذكر ماذا نملك?
- نملك الاستقلال والحرية ولا توجد وصاية على الجمهورية اليمنية وبيت
المقدس(الاقصى-حزيز-بيت الجبري) وقف ذرية لجميع المسلمين.

✍ #عبدالله_الجبري
- صنعاء... 26/4/1445 هجري
الجمعه... 10/11/2023م
🇾🇪🚓🦁🇵🇸👁️🇵🇸🇵🇸
