### ISSUE TITLE
THREE.JS not working on Android 11

### ISSUE THREAD

**Issue by tnluan** [mrdoob/three.js#27186]
### Description

THREE.JS not working on Android 11.
How could I address this issue?

![Image_20231114_150830_074](https://github.com/mrdoob/three.js/assets/7054669/649bc4c7-033f-446f-bc4c-2fd32ca61762)

### Reproduction steps

None

### Code

None

### Live example

https://threejs.org/examples/#webgl_animation_keyframes

### Version

Any

### Device

Mobile

### Browser

Chrome

### OS

Android

**Comment by mrdoob** [comment]
* None of the examples work?
* What phone model is it?
* What version of Chrome?
* Do you have other devices with Android 11?

**Comment by tnluan** [comment]
> * None of the examples work?
Yes.

> * What phone model is it?
I'm using Redmi Note 8 Pro and Samsung Galaxy S21+, both are running on Android 11.

> * What version of Chrome?
87.0.4280.141

> * Do you have other devices with Android 11?
Redmi Note 8 Pro and Samsung Galaxy S21+ are the same issue.

**Comment by mrdoob** [comment]
Chrome 87 is 3 years old and doesn't support [import maps](https://caniuse.com/import-maps) which  the examples now use.

**Comment by mrdoob** [comment]
Do these examples work?
https://raw.githack.com/mrdoob/three.js/r156/examples/index.html

**Comment by tnluan** [comment]
> Do these examples work? https://raw.githack.com/mrdoob/three.js/r156/examples/index.html

Wow, it works. How can I correct it for my web app?

**Comment by Mugen87** [comment]
I suggest you add the import maps polyfill back that had been removed with `r157`, see #26836.


Please use the [forum](https://discourse.threejs.org/) if you need more guidance.

**Comment by Mugen87** [comment]
BTW: Why using a three year old browser? Next to the lack of features, it's nightmare in context of web security.

**Comment by tnluan** [comment]
> BTW: Why using a three year old browser? Next to the lack of features, it's nightmare in context of web security.

Not us, but our end users are using it. We couldn't request all of them to update to the later version.

**Comment by eriksyuan** [comment]
android 14 webview also can't work.

**Comment by mrdoob** [comment]
@tnluan Don't use import maps in the code you're serving to your users.
