### ISSUE TITLE
High gpu usage with WebGPURenderer returned with video textures

### ISSUE THREAD

**Issue by danrossi** [mrdoob/three.js#27199]
### Description

It was corrected a while ago but now has returned again. I am experiencing high gpu usage about 40% with video textures with WebGPURenderer.

### Reproduction steps

https://github.com/danrossi/three-webgpu-renderer/blob/master/tests/webgpu_video_panorama_equirectangular.html

### Code

https://github.com/danrossi/three-webgpu-renderer/blob/master/tests/webgpu_video_panorama_equirectangular.html

### Live example

https://danrossi.github.io/three-webgpu-renderer/tests/webgpu_video_panorama_equirectangular.html

### Version

158

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by mrdoob** [comment]
Wasn't there a issue for this filed already?

**Comment by danrossi** [comment]
There was. I closed it because the issue had corrected itself. After updates it's come back.

**Comment by Mugen87** [comment]
I think it was #26266.

**Comment by danrossi** [comment]
Should I close this and reopen the other. Or comment on #26673

**Comment by Mugen87** [comment]
I can reproduce the issue on macOS with Chrome.

Your example shows no unexpected peaks during a performance analysis with the performance tab. I've attached my trace and it shows no evidence of a bottleneck in `WebGPURenderer`. 

[Trace-20231121T100051.json](https://github.com/mrdoob/three.js/files/13424000/Trace-20231121T100051.json)

When I check the CPU utilization of the entire tab with the Chrome task manager, the WebGPU example actually requires less CPU (about 10%) than [webgl_video_panorama_equirectangular](https://threejs.org/examples/webgl_video_panorama_equirectangular). 

Are you able to make a test on a different OS? It would be good to know if this is a Windows exclusive issue.

**Comment by danrossi** [comment]
I'm sorry. It was gpu usage I've seen problems. There is something wrong on Windows. It seems a reboot had fixed it again. I'll keep this open until I see the issue again. It could be after multiple uses of webgpu it does it. 

![Screenshot 2023-11-22 010947](https://github.com/mrdoob/three.js/assets/710277/87ce97ca-513a-4bc8-acce-b17754d522ab)

**Comment by Mugen87** [comment]
Sorry for misreading 😅 . Even if it comes up again, I doubt we can fix this issue here. If you can (reliably) reproduce the issue in some way, it would be best to report it to the Chromium bug tracker.
