### ISSUE TITLE
Adding a model using THREE InstancedMesh in mapboxgl, losing vertices after modifying and scaling

### ISSUE THREAD

**Issue by xiaxiangfeng** [mrdoob/three.js#27196]
### Description

After adding the mesh of the gltf model to THREE.InstancedMesh, I modified the scaling, and the rendered effect seems to have lost some vertices

### Reproduction steps

1. Adding custom layers using mapboxgl
2. Load the model using three gltfloader in the mapboxgl custom layer
3. Adding gltf mesh using THREE.InstancedMesh

### Code

```js
loader.load(
        "https://threejs.org/examples/models/gltf/Flower/Flower.glb",
        function (gltf) {
          const p = projectToWorld(origin);

          const model = gltf.scene;

          const _stemMesh = model.getObjectByName("Stem");
          const _blossomMesh = model.getObjectByName("Blossom");

          const stemGeometry = _stemMesh.geometry.clone();
          const blossomGeometry = _blossomMesh.geometry.clone();

          const stemMaterial = _stemMesh.material;
          const blossomMaterial = _blossomMesh.material;

          const stemMesh = new THREE.InstancedMesh(
            stemGeometry,
            stemMaterial,
            1
          );
          const blossomMesh = new THREE.InstancedMesh(
            blossomGeometry,
            blossomMaterial,
            1
          );

          stemMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);
          blossomMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);

          const defaultTransform = new THREE.Matrix4()
            .makeRotationX(Math.PI)
            .multiply(new THREE.Matrix4().makeScale(1, 1, 1));

          stemGeometry.applyMatrix4(defaultTransform);
          blossomGeometry.applyMatrix4(defaultTransform);

          stemMesh.instanceMatrix.needsUpdate = true;
          blossomMesh.instanceMatrix.needsUpdate = true;

          const dummy = new THREE.Object3D();

          let pos = projectToWorld([118.61113, 32.06318, 0]);

          for (let i = 0; i < 1; i++) {
            dummy.position.copy(pos);
            dummy.scale.set(10, 10, 10);
            // dummy.scale.set(100, 100, 100);
            dummy.updateMatrix();
            stemMesh.setMatrixAt(i, dummy.matrix);
            blossomMesh.setMatrixAt(i, dummy.matrix);
          }

          const group = new THREE.Group();

          group.add(stemMesh);
          group.add(blossomMesh);

          world.add(group);

          map.triggerRepaint(); }
      );
```

### Live example

* [codepen](https://codepen.io/xiaxiangfeng/pen/KKJyvoV)

### Screenshots

normal
![2](https://github.com/mrdoob/three.js/assets/2898403/21f86c13-f4b3-4946-a5b1-b0a65a7ea00e)
abnormal
![1](https://github.com/mrdoob/three.js/assets/2898403/40d96cff-b667-4639-a8cb-49e0ef6727fc)

### Version

all

**Comment by Mugen87** [comment]
When opening the codepen the asset is rendered like in the "normal" screenshot. How to reproduce the "abnormal" state?

**Comment by xiaxiangfeng** [comment]
> When opening the codepen the asset is rendered like in the "normal" screenshot. How to reproduce the "abnormal" state?
Use the right mouse button to drag and drop the map to select it.
Alternatively, modify the code dummy. scale. set (5, 5, 5);

**Comment by Mugen87** [comment]
I can't reproduce the issue when I move the camera but scaling down the object reveals issues. I don't think this is related to `InstancedMesh` but to the projection matrix which is computed in a special way for mapbox.

However, this isn't a bug in the engine but a mapbox related rendering issue. Please ask at the [forum](https://discourse.threejs.org/) or stackoverflow for advice.
