### ISSUE TITLE
THREE.JS not working on Android 14 Webview

### ISSUE THREAD

**Issue by eriksyuan** [mrdoob/three.js#27192]
### Description

It can run normally in the system browser

Unable to run in webview within the application

### Reproduction steps

1. tiktok open the url
2.
3.

### Code

```js
// code goes here
```

### Live example

* [threejs example](https://threejs.org/examples/#webgl_animation_keyframes)

### Screenshots

![WechatIMG8](https://github.com/mrdoob/three.js/assets/48196760/b4afb7fd-dc6c-4089-b10a-28f1d9a7b3e5)

### Version

r154

### Device

Mobile

### OS

Android

**Comment by mrdoob** [comment]
What's the user agent of that webview?
https://www.whatismybrowser.com/detect/what-is-my-user-agent/

**Comment by eriksyuan** [comment]
> 该 webview 的用户代理是什么？ https://www.whatismybrowser.com/detect/what-is-my-user-agent/

![WechatIMG10](https://github.com/mrdoob/three.js/assets/48196760/d5224a5b-7444-496a-a0d6-4fa23c471dba)

**Comment by mrdoob** [comment]
Can you connect a phone to a computer and see if there's any error in the dev tools console?
https://developer.chrome.com/docs/devtools/remote-debugging/

**Comment by mrdoob** [comment]
Weird...

**Comment by eriksyuan** [comment]
> Weird...

Thanks for your reply

I found a solution
When I set antialias to true for the renderer, it cannot function properly

Unable to work:
`
New THREE. WebGLRenderer ({aliases: true, alpha: true})
`

Can work:
`
New THREE. WebGLRenderer ({alpha: true})
`

When antialias is set to true, it cannot function properly in the webview of the following useragent

Mozilla/5.0 (Linux; Android 14; 23127PN0CC Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/11.0.5563.116 Mobile Safari/537.36 XWEB/1110005 MMWEBSDK/2020805 MMWEBID/8793 MicroMessenger/8.0.42.2460 (0x28002A58) WeChat/arm64 Weixin NetType/WIFI Language/zh_ CN ABI/arm64

**Comment by mrdoob** [comment]
Strange...

But glad that you found a workaround.

Unfortunately, there's nothing we can do from our side.
