### ISSUE TITLE
THREE.Box3 compute has animation GLTF.It causes the model to be messed up

### ISSUE THREAD

**Issue by HappyKent** [mrdoob/three.js#27195]
### Description

When I used box to calculate the size of the model with the bone skin animation, the animation model did not display properly

### Reproduction steps

1.box.setFromObject(gltf.scene)
2.xxx.playAnimation("idle")
3.

### Code

box.setFromObject(gltf.scene)
xxx.playAnimation("idle")

### Live example

null

### Screenshots

![eeeeeeeee](https://github.com/mrdoob/three.js/assets/45218695/cdb3776e-0e33-49e3-a5cf-5806bc76b09d)
![image](https://github.com/mrdoob/three.js/assets/45218695/544bb8cc-299d-4d91-a7b7-67ff6d0cfd5d)

### Version

158.0

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Do you mind sharing the glTF asset in this issue?

**Comment by HappyKent** [comment]
Yes.


秦贺
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mrdoob/three.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月16日(星期四) 下午5:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mrdoob/three.js] THREE.Box3 compute has animation GLTF.It causes the model to be messed up (Issue #27195)





 
Do you mind sharing the glTF asset in this issue?

**Comment by HappyKent** [comment]
I'll prepare a case as soon as live example.

**Comment by Mugen87** [comment]
Closing until a live example has been provided.

**Comment by HappyKent** [comment]
`  import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
    import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
    import {
        AmbientLight,
        Scene,
        Bone,
        Box3,
        Skeleton,
        SkinnedMesh,
        PerspectiveCamera,
        WebGLRenderer,
        ACESFilmicToneMapping,
        AnimationMixer, Vector3
    } from "three";

    let camera, scene, renderer, box, gltfScene;
    let animationAction, animationMixer;
    let now, lastTime;
    let gltfUrl = 'models/gltf/heavy/index.gltf'
    init();
    animate()

    // inconsequential
    function init()
    {
        const container = document.createElement('div');
        document.body.appendChild(container);

        camera = new PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.25, 20);
        camera.position.set(-1.8, 0.6, 2.7);
        box = new Box3()
        scene = new Scene();
        scene.add(new AmbientLight())
        const loader = new GLTFLoader()
        loader.load(gltfUrl, onLoadGltf);

        renderer = new WebGLRenderer({antialias: true});
        renderer.setPixelRatio(window.devicePixelRatio);
        renderer.setSize(window.innerWidth, window.innerHeight);
        renderer.toneMapping = ACESFilmicToneMapping;
        renderer.toneMappingExposure = 1;
        container.appendChild(renderer.domElement);

        const controls = new OrbitControls(camera, renderer.domElement);
        controls.minDistance = 2;
        controls.maxDistance = 10;
        controls.target.set(0, 0, -0.2);
        controls.update();

        window.addEventListener('resize', onWindowResize);
        lastTime = Date.now();

    }

    // inconsequential
    function onWindowResize()
    {
        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();
        renderer.setSize(window.innerWidth, window.innerHeight);
    }

    // inconsequential
    function animate()
    {
        requestAnimationFrame(animate);
        now = Date.now();
        if (animationMixer)
        {
            animationMixer.update((now - lastTime) * 0.001);
        }
        lastTime = now
        renderer.render(scene, camera);
    }


    // It's important to look at this !!!!!!!!!!!!!
    let isOpenBUG = true;

    function onLoadGltf(_gltf)
    {
        if (isOpenBUG)
        {
            box.setFromObject(_gltf.scene)
            box.getSize(new Vector3())
        }

        gltfScene = cloneGroup(_gltf.scene)

        scene.add(gltfScene);
        animationMixer = new AnimationMixer(gltfScene);
        animationMixer.clipAction(_gltf.animations[0]).play();
    }

    // Clone a gltf scene object containing the skeleton skin !!!!!!!!!!!!
    function cloneGroup(gltfScene)
    {
        const group = gltfScene.clone(true);

        const skinnedMeshes = {};
        const cloneBones = {};
        const cloneSkinnedMeshes = {};


        gltfScene.traverse((node) =>
        {
            if (node instanceof SkinnedMesh)
            {
                skinnedMeshes[node.name] = node;
            }
        })


        group.traverse((node) =>
        {
            if (node instanceof Bone)
            {
                cloneBones[node.name] = node;
            }

            if (node instanceof SkinnedMesh)
            {
                cloneSkinnedMeshes[node.name] = node;
            }
        })

        for (const name in skinnedMeshes)
        {
            const skeleton = skinnedMeshes[name].skeleton;
            const cloneSkinnedMesh = cloneSkinnedMeshes[name];
            const orderedCloneBones = [];

            for (let i = 0; i < skeleton.bones.length; ++i)
            {
                const cloneBone = cloneBones[skeleton.bones[i].name];
                orderedCloneBones.push(cloneBone);
            }

            cloneSkinnedMesh.bind(new Skeleton(orderedCloneBones, skeleton.boneInverses), cloneSkinnedMesh.matrixWorld);
        }

        return group;
    }`

**Comment by HappyKent** [comment]
When I use box.setFromObject() then cloneGroup() will have problems,I don't know if it's my "cloneGroup()" method or if it's a problem within threejs
