### ISSUE TITLE
setPositions on LineGeometry doesn't delete _maxInstanceCount, required when adding more points.

### ISSUE THREAD

**Issue by nzjony** [mrdoob/three.js#27205]
### Description

Please see video:

https://github.com/mrdoob/three.js/assets/2533428/97291e3a-c9bd-4b41-9c74-e593c472ba50

I created a small application which has a small select box to add points. Adding more points to the LineGeometry only renders the number of segments equal to the first count set with setPositions.

### Reproduction steps

1. Create a Line2 object
2. Call setPositions with n vertices
3. Render the Line2
4. Call setPositions with m vertices, where m > n
5. Render the Line2

The second rendering of the line2 won't render the new points, however the old ones are rendered.

Workaround: it is possible to fix this by: `delete this.line.geometry._maxInstanceCount;` Search the code below for: `// Uncomment this to fix issue` or look in the jsfiddle.

### Code

```js
import * as THREE from 'three';
import { NURBSCurve } from 'three/examples/jsm/curves/NURBSCurve.js';
import { Line2 } from "three/examples/jsm/lines/Line2.js";
import { LineGeometry } from 'three/examples/jsm/lines/LineGeometry.js';
import { LineMaterial } from 'three/examples/jsm/lines/LineMaterial.js';

// Basic Three.js startup code
const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.01, 1000);
camera.position.set(0, 5, 0);
camera.lookAt(0, 0, 0);
const renderer = new THREE.WebGLRenderer();

// Controls
renderer.setSize(window.innerWidth, window.innerHeight);
document.body.appendChild(renderer.domElement);

class Curve extends THREE.Object3D
{
	/** @type{NURBSCurve} */
	nurbsCurve;

	constructor(controlPoints, knots, count = 20) {
		super();
		const degree = knots.length - controlPoints.length - 1
		this.nurbsCurve = new NURBSCurve(degree, knots, controlPoints);

		const geometry = new LineGeometry()
		const material = new LineMaterial({
			color: "pink",
			linewidth: 20,
			depthTest: false,
			resolution: new THREE.Vector2(window.innerWidth, window.innerHeight),
		});
		this.line = new Line2(geometry, material);
		this.add(this.line);

		const pointMaterial = new THREE.PointsMaterial({ color: "white", size: 4, sizeAttenuation: false   });
		const pointGeometry = new THREE.BufferGeometry();
		this.pointsObj = new THREE.Points(pointGeometry, pointMaterial);
		this.add(this.pointsObj);

		this.updateLineGeometry(count);
	}

	updateLineGeometry(count)
	{
		this.count = count;
		const points = this.nurbsCurve.getPoints(count);
		const flatPoints = points.flatMap(p => [p.x, p.y, p.z]);
		this.line.geometry.setPositions(flatPoints);

		// Uncomment this to fix issue
		// delete this.line.geometry._maxInstanceCount;

		this.pointsObj.geometry.setFromPoints(points);
	}
}

const controlPoints = [
	new THREE.Vector4(-0.5	, 0, 0		, 1),
	new THREE.Vector4(0		, 0, -0.5	, 1),
	new THREE.Vector4(0.5	, 0, 0		, 1),
	new THREE.Vector4(1		, 0, 0.5	, 1),
	new THREE.Vector4(1.5	, 0, 0		, 1),
];
const knots = [0, 0, 0, 1, 1, 2, 2, 2];
const curve = new Curve(controlPoints, knots);
scene.add(curve);

function animate() {
	renderer.render(scene, camera);
}

animate();

let i = 0;
setInterval(() => {
	curve.updateLineGeometry(curve.count === 20 ? 30 : 20);
	animate();

}, 300);
```

### Live example

* [jsfiddle](https://jsfiddle.net/7kr0x5as/2/)

### Screenshots

![Screenshot 2023-11-17 at 16 33 04](https://github.com/mrdoob/three.js/assets/2533428/c0bb6f94-7901-42a4-a7b0-a76f1a442330)

Line 93 fixes the issue

### Version

157

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by donmccurdy** [comment]
If I understand correctly, we don't intend for geometry to be resizable. Instead it can be pre-allocated to a larger size, and then `drawRange` is used to draw a subset of that if the full size is not needed. Unless there's something different about THREE.Line2 here, compared to other three.js objects? You'll see similar results when doing `geometry.merge(otherGeometry)`.

**Comment by Mugen87** [comment]
Merging this into #21488.
