### ISSUE TITLE
Support Struct uniforms

### ISSUE THREAD

**Issue by englercj** [mrdoob/three.js#2720]
I'm currently working on a project where it would make my life hella easy if I could pass an array of structs to my shader. I understand I can do it with just WebGL, but it would be nice if Three.js supported passing in structs, and arrays of structs.

Related to #805 and #678.

Thanks!

**Comment by Aarilight** [comment]
Trying to do this.. is there a way to do it now, or is that old way still supposed to work? It's being initialized as zeros for all the values when I send it this object:

    var uniforms = {
        "stops[0].floatParameter": { type: "f", value: 0.25 },
        "stops[0].vec3Parameter":  { type: "c", value: new THREE.Color( 0x74C6FF ) },
        "stops[1].floatParameter": { type: "f", value: 0.75 },
        "stops[1].vec3Parameter":  { type: "c", value: new THREE.Color( 0x416199 ) }
    };

And in my shader:

    struct stop {
        float pos;
        vec3 col;
    };
        
    uniform stop stops[2];

**Comment by bhouston** [comment]
@Aarilight in the next revision of ThreeJS it supports structs and array structs in this fashion - so you can specify them very easily:

https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/UniformsLib.js#L92

And you set them by setting JavaScript arrays with the same structure as the resulting GLSL struct arrays.  Example of setting these:

https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L2735

**Comment by Aarilight** [comment]
Ah, nice! That's pretty cool. Although I do have a suggestion... having to specify the type is kind of annoying.. why not have a function that can go through and figure out all the types automatically?

    {
        ypos: new THREE.Float(0),
        rad: new THREE.Float(100),
        stops: [
            {
                new THREE.Float(0),
                new THREE.Color(0x74C6FF)
            },
            {
                new THREE.Float(0.75),
                new THREE.Color(0x416199)
            },
            {
                new THREE.Float(0.95),
                new THREE.Color(0x1D2B44)
            },
            {
                new THREE.Float(1),
                new THREE.Color(0x000000)
            }
        ]
    }

The function would recieve that and expand it to the necessary types. Much, much cleaner, shorter code, at the cost of having two new 'types' implemented, `Float` and `Int`

**Comment by mrdoob** [comment]
I started [THREE.Uniform](https://github.com/mrdoob/three.js/blob/dev/src/core/Uniform.js) the other day.
We can now easily do `THREE.ColorUniform` (which basically does `THREE.Uniform.call( 'c', value )`).
