### ISSUE TITLE
Crash in WebGPU: Error: no matching constructor for vec4

### ISSUE THREAD

**Issue by andreasrosdal** [mrdoob/three.js#27208]
### Description

I get a crash in WebGPU: Error: no matching constructor for vec4.

See attached screenshot for the error message.

I am using the Three.js WebGPU build here: https://github.com/danrossi/three-webgpu-renderer

Note that I am not using any custom webgl or glsl shaders in this case.

Related:
https://github.com/danrossi/three-webgpu-renderer/issues/7

### Reproduction steps

1 To reproduce, start a new game at https://www.fciv.net/?webgpu=true
2 then type /observe (+Enter) into the game console after it has started.
3. then observe the black screen and crash

The error is not present in the normal WebGL Three.js build, and the error is not present when using three-webgpu-renderer with the WebGL backend in Firefix.

### Code

Source code:  https://github.com/fciv-net/fciv-net/tree/main/freeciv-web/src/main/webapp/javascript/webgl

### Live example

https://www.fciv.net/?webgpu=true

### Screenshots

![284005230-f0227ff4-2015-476b-ae45-6142fded694c](https://github.com/mrdoob/three.js/assets/41650711/61b6fec4-9067-445a-89dd-9fe997e971ae)

### Version

r159dev danrossi/three-webgpu-renderer

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by andreasrosdal** [comment]
The error message is about the variable **DiffuseColor**, and that there is some exception assigning this variable.

DiffuseColor is for example mentioned here in the Three.js source code:
https://github.com/mrdoob/three.js/blob/master/examples/jsm/nodes/core/PropertyNode.js#L40

**Comment by LeviPesin** [comment]
I'm preparing a PR that I think will solve this issue as part of its changes. (It's quite a large PR so maybe will take a week or two to finish it)

**Comment by andreasrosdal** [comment]
@LeviPesin Excellent. Do you understand what causes the error in this case? Is there some work-around quick-fix I can try? Thank you!

**Comment by LeviPesin** [comment]
Possibly your geometry has a `color` attribute (i.e. storing vertex colors), which is of type `vec4`, not `vec3` (it should be auto-converted to `vec3`, but if not, that's a bug)?

**Comment by andreasrosdal** [comment]
How can I modify the code to get a more accurate error message? How can I get a stacktrace from this? Can I find out which geometry is causing this? There are many models loaded from glTF, so possibly some of these models have color attributes?

**Comment by LeviPesin** [comment]
I now think you can solve the issue just by changing `attribute( 'color' )` in the line https://github.com/mrdoob/three.js/blob/4eecc8906c00f7a9487eb9c4af5344b736d84b1e/examples/jsm/nodes/materials/NodeMaterial.js#L163 to `attribute( 'color', 'vec3' )`. If this works, feel free to file a PR with this change.

**Comment by andreasrosdal** [comment]
Yes, this change worked correctly! Thank you. I can make a PR with this change now.
