### ISSUE TITLE
WebGPU: BufferGeometry position attribute not updating in WebGPU renderer

### ISSUE THREAD

**Issue by andreasrosdal** [mrdoob/three.js#27217]
### Description

WebGPU: BufferGeometry position attribute not updating in WebGPU renderer. I try to update the position attribute, but the shape of the geometry looks the same on the screen, not updated, no error messages.

However, in the normal WebGL 2 renderer the BufferGeometry position attribute is updated correctly.

### Reproduction steps

1. Go to https://fciv.net/?webgpu=true and start a new game using the WebGPU renderer.
2. Move the units around.
3. As the units explore the surrounding area, the terrain geometry should be updated with new shape as the units explore 

The normal WebGL 2 renderer at https://fciv.net doesn't have this problem, there the terrain is updated correctly.

### Code

```
geometry.setIndex( indices );  
geometry.setAttribute( 'position', new THREE.Float32BufferAttribute( vertices, 3 ) );  
geometry.setAttribute( 'uv', new THREE.Float32BufferAttribute( uvs, 2 ) );
```  

The full source code for this update of the BufferGeometry position attribute is here:
https://github.com/fciv-net/fciv-net/blob/main/freeciv-web/src/main/webapp/javascript/webgl/mapview.js#L363

### Live example

https://fciv.net/?webgpu=true

### Version

r159dev danrossi/three-webgpu-renderer

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by andreasrosdal** [comment]
Can I provide more information in order to solve this issue?

Is the position attribute of a geometry object supposed to be updated in the WebGPU renderer? 

This works in the WebGl renderer.

Is there some way to force an update of the geometry shape?

**Comment by Mugen87** [comment]
You are not supposed to recreate existing attributes. Only updated existing buffer data. Are you actually doing this in your app?

**Comment by Mugen87** [comment]
Just overwrite the existing buffer data, ideally with the `set*()` methods from the `BufferAttribute` class. After updating the data, set the `needsUpdate` flag to `true` for all attributes you have updated.

You can even update only parts of the data and use `updateRanges` to define that only the updated data should be uploaded to the GPU (and not the entire buffer).

**Comment by Mugen87** [comment]
If you need a code example that uses one of the `set*()` methods, check out [webgl_geometry_colors](https://threejs.org/examples/webgl_geometry_colors). It define vertex colors via `setXYZ()`.

**Comment by andreasrosdal** [comment]
Thank you! I managed to the the updating of buffer geometry working correctly with the WebGPU renderer using the information provided here.  Next on my Todo-list for https://www.Fciv.net is updating the shader from WebGL to WebGPU.
