### ISSUE TITLE
3DS Loader - possibly use MeshPhysicalMaterial

### ISSUE THREAD

**Issue by GitHubDragonFly** [mrdoob/three.js#27227]
### Description

This is just a suggestion to possibly improve the appearance of 3DS models.

It has been implemented on my end and it seems to be looking a bit better. The `specular` and `specularMap` have been re-routed to `specularColor` and `specularColorMap` properties of the MeshPhysicalMaterial.

For those who would like to try it just use my online [3DS Viewer](https://githubdragonfly.github.io/viewers/templates/3DS%20Viewer.html) and enter the following URL in the viewer's URL textbox:

 - `https://raw.githubusercontent.com/mrdoob/three.js/master/examples/models/3ds/portalgun/portalgun.3ds, https://raw.githubusercontent.com/mrdoob/three.js/master/examples/models/3ds/portalgun/textures/`

Here is the picture of what it might look like:

![3DS Viewer - MeshPhysicalMaterial](https://github.com/mrdoob/three.js/assets/69928501/61006733-eab0-48ad-a7bc-b3f19e83aa44)

### Solution

As suggested above, my 3DS Viewer is already using a customized TDSLoader.js file whose code is available [here](https://github.com/GitHubDragonFly/GitHubDragonFly.github.io/blob/main/viewers/static/jsm/loaders/TDSLoader.js).

### Alternatives

Alternative solution is not to change anything in the TDSLoader.js file and keep using it as it is.

**Comment by Mugen87** [comment]
I'm afraid you can't just assign `specular` and `specularMap` from `MeshPhongMaterial` to the specular of PBR materials since they are different things. 

The specular map of `MeshPhongMaterial` isn't a real color map which is explained in #7290. Besides, I would only use a PBR material for 3DS if the spec explicitly defines its own material definition as physically correct.

**Comment by GitHubDragonFly** [comment]
@Mugen87 thank you for taking the time to reply, I always learn something new.

I will just leave it as it is on my end since, to me, these 3DS models do look better with a bit of metalness and roughness.

Users have nothing to lose by trying their models in my viewer, it shouldn't be much different than if they were making similar changes to their models in the three.js editor.
