### ISSUE TITLE
Imposter.js Not Found

### ISSUE THREAD

**Issue by Strange-tech** [mrdoob/three.js#27224]
### Description

[examples/jsm/objects/Impostor.js](https://github.com/mrdoob/three.js/blob/master/examples/jsm/objects/Impostor.js) cannot be found. 
But there is still a doc about it:https://raw.githack.com/felixmariotto/three.js/impostors/docs/index.html?q=impo#examples/en/objects/Impostor.updateAll
I wonder if that doc is official or not. If it's official, where is the source code of Imposter.js?

### Reproduction steps

1.https://raw.githack.com/felixmariotto/three.js/impostors/docs/index.html?q=impo#examples/en/objects/Impostor.updateAll
2.[examples/jsm/objects/Impostor.js](https://github.com/mrdoob/three.js/blob/master/examples/jsm/objects/Impostor.js)
3.404 not found

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

dev

**Comment by Mugen87** [comment]
> I wonder if that doc is official or not. If it's official, where is the source code of Imposter.js?

It is not. You can find the code here: #22043
