### ISSUE TITLE
Object3D: getObjectsByProperty improvement

### ISSUE THREAD

**Issue by agargaro** [mrdoob/three.js#27223]
### Description

The **getObjectsByProperty** method can be greatly improved by sharing the same array, instead of creating new ones and concatenating them.

I have created an example where performance can be checked.

If you want I can do PR.

### Reproduction steps

I created a scene with 5000 children and called the getObjectsByProperty method to select them all.

### Code

Current function:

```js
getObjectsByProperty( name, value ) {

		let result = [];

		if ( this[ name ] === value ) result.push( this );

		for ( let i = 0, l = this.children.length; i < l; i ++ ) {

			const childResult = this.children[ i ].getObjectsByProperty( name, value );

			if ( childResult.length > 0 ) {

				result = result.concat( childResult );

			}

		}

		return result;

	}
```

Function with shared array reference:

```js
function getObjectsByProperty2(name, value, result = []) {
  if (this[name] === value) result.push(this);

  for (let i = 0, l = this.children.length; i < l; i++) {
    this.children[i].getObjectsByProperty2(name, value, result);
  }

  return result;
};
```

### Live example

https://jsfiddle.net/agargaro/qyh6zxkg/4/

### Version

r158

**Comment by Mugen87** [comment]
I agree this is a good suggestion. We have similar result or target parameters in other methods as well.

> If you want I can do PR.

That would be great!
