### ISSUE TITLE
HTMLMesh throws error if radio element has height of width of 0.

### ISSUE THREAD

**Issue by jrjdavidson** [mrdoob/three.js#27240]
### Description

if a checked radio element that is drawn using HTMLMesh happens to have a width or height of 0, HTMLMesh will throw the following error:
`Uncaught DOMException: Failed to execute 'arcTo' on 'CanvasRenderingContext2D': The radius provided (-2) is negative.`

it seems to be due to this line: 
https://github.com/mrdoob/three.js/blob/1ab4a8a44ab9d2ee3a367b5a53213ca4f63a00d1/examples/jsm/interactive/HTMLMesh.js#L391C9-L391C9

A bit of an edge case, but I feel lucky i caught this one before it broke something later on so thought it might be helpful to report..

A simple fix would be to prevent a negative r value in `buildRectPath()`

### Reproduction steps

draw an element with height:0 or width:0 using HTMLMesh

see jsfiddle

### Code

(https://jsfiddle.net/83wx0f4L/)

### Live example

https://jsfiddle.net/83wx0f4L/

### Version

r157

**Comment by Mugen87** [comment]
There are a couple of thigs:

- The DOM elements you use with `HTMLMesh` must be part of the DOM. So add them to the document like so:

```js
radio.style.visibility = 'hidden';
document.body.appendChild( radio );

https://jsfiddle.net/h8a4rx1v/

**Comment by Mugen87** [comment]
The DOM elements you use with `HTMLMesh` must be part of the DOM. So add them to the document like so:
```js
radio.style.visibility = 'hidden';
document.body.appendChild( radio );
```
Besides, you should create radio inputs like so:
```js
const radio= document.createElement('input');
radio.setAttribute( 'type', 'radio' );
```
The warnings should disappear then: https://jsfiddle.net/h8a4rx1v/

**Comment by jrjdavidson** [comment]
Apologies- i meant to link this fiddle which shows the error: 
https://jsfiddle.net/83wx0f4L/1/

However you are correct that there is no more error when appending the element to the DOM. Thanks!
