### ISSUE TITLE
The webxr_ar_lighting sample does not work

### ISSUE THREAD

**Issue by krzys-h** [mrdoob/three.js#27256]
### Description

I tried running https://threejs.org/examples/webxr_ar_lighting.html, but the environment reflection probe does not seem to work.

This seems to be a regression - it works in r131, but is broken since r132.

### Reproduction steps

1. Open https://threejs.org/examples/webxr_ar_lighting.html on a compatible device
2. Start AR mode
3. The lighting estimation and reflection probe should work, but while the lighting does get updated, the reflections do not appear at all.

### Code

https://github.com/mrdoob/three.js/blob/master/examples/webxr_ar_lighting.html

### Live example

https://threejs.org/examples/webxr_ar_lighting.html
https://rawcdn.githack.com/mrdoob/three.js/r131/examples/webxr_ar_lighting.html

### Screenshots

r132 and r158, not working
![Screenshot_20231127_111456_Chrome](https://github.com/mrdoob/three.js/assets/1517255/5aba5f67-bde3-4f1d-8e0a-1ad586706a08)

r131, working
![Screenshot_20231127_111404_Chrome](https://github.com/mrdoob/three.js/assets/1517255/b10550ed-9b37-4695-84a5-44c649b72436)

### Version

r158, broken since r132

### Device

Mobile

### Browser

Chrome

### OS

Android

**Comment by Mugen87** [comment]
I can confirm the issue. The environmental reflections are missing since `r132`.

**Comment by Mugen87** [comment]
Um, reading #23171 and #23322 it seems the result is actually as expected. 

@krzys-h If you want to see clearer reflections, try to apply `xrLight.environment` to an instance of `MeshPhongMaterial`.
