### ISSUE TITLE
OrbitControls update event always fired if using an Orthographic Camera

### ISSUE THREAD

**Issue by jedleslie** [mrdoob/three.js#27280]
### Description

Hi Three Team -

Just ran across this and am not sure if it's an issue or not.  I have an app that uses both ortho and perspective cameras along with OrbitControls.  I have the OrbitControls update() in my render loop because I am using dampening.  I also have an event listener or the change event of OrbitControls.  

When I'm in perspective camera, I see the change event being fired only when I'm actually orbiting around the scene.  In orthographic mode I see it firing every time the render loop calls update().  

Maybe this is by design and part of how ortho cameras need to work.  Just though I'd let you know.

### Reproduction steps

1. Create a scene and add orthographic and perspective cameras.   Add the orbit controls.
2. Add an event handler on the change event for OrbitControls.
3. Swap between the two cameras and watch it fire constantly when in orthographic mode, and only when the orbit controls are firing when in perspective.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

0.158

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by WestLangley** [comment]
It appears this behavior was introduced in r155 via #26165.

https://github.com/mrdoob/three.js/blob/84424e4f2e0e49fb194e1683b846201f8244cfc7/examples/jsm/controls/OrbitControls.js#L377-L379

`zoomChanged` is always `true`.

**Comment by Mugen87** [comment]
@gkjohnson It seems the mentioned code block was only executed in previous versions in the dolly/zoom event listeners. Now the code is executed per update for orthographic cameras. I'm sure there was a reasons for moving the code block but it be an option to cache the zoom value and only update the projection matrix and set `zoomChanged` to `true` when `zoom` actually changed?
