### ISSUE TITLE
Bug: GTAOPass treats culled faces as occluders

### ISSUE THREAD

**Issue by ycw** [mrdoob/three.js#27292]
### Description

demo: https://jsfiddle.net/6r5dcbsp/ (red box material is `side: BackSide`)

hbaopass yields this:

<img width="311" alt="1" src="https://github.com/mrdoob/three.js/assets/1063018/19b2057e-2c8d-47d3-8579-58f4028d72b9">

but i expected this:

<img width="344" alt="3" src="https://github.com/mrdoob/three.js/assets/1063018/bb7f2a84-e3f8-4b6a-907d-176aeb5c97d8">

### Reproduction steps

n/a

### Code

n/a

### Live example

n/a

### Version

r159

**Comment by Rabbid76** [comment]
> /ping @Rabbid76

will take a look

**Comment by Mugen87** [comment]
I guess this issue is related to #14577 then.

**Comment by Rabbid76** [comment]
@Mugen87 Yes, the problem has the same root cause.

**Comment by mrdoob** [comment]
Does the new GTAOPass have the same issue?

**Comment by Mugen87** [comment]
Yes. All RTT scenarios that use `overrideMaterial` will show the same issue.

I wonder if we should merge this thread into #14577 because that is the actual root cause. It does not make sense to me to file more or less the same bug for each component it appears.

**Comment by Mugen87** [comment]
Merging into https://github.com/mrdoob/three.js/issues/14577.
