### ISSUE TITLE
When used in Vue3, when refreshing with F5, the background of the model scene displays white 

### ISSUE THREAD

**Issue by Xqrrrr** [mrdoob/three.js#27300]
### Description

When used in Vue3, when refreshing with F5, the background of the model scene displays white .Please tell me how to solve this problem

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

0.156.1

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for this request. We do not support Vue3 or other UI library specific issues in this repository.
