### ISSUE TITLE
An error is thrown when a shader uniform array value is set to an empty array.

### ISSUE THREAD

**Issue by justin-omnivor** [mrdoob/three.js#27309]
### Description

The following error is thrown when a uniform value of an array type is set to an empty array:
```Uncaught TypeError: firstElem.toArray is not a function```

The problematic code seems to be [this line](https://github.com/mrdoob/three.js/blob/139cbde28165a6fc4d64ca7289c8b855da45193a/src/renderers/webgl/WebGLUniforms.js#L77). Because there is no prior check to ensure that `array` has a length greater than zero.

### Reproduction steps

1. Create a `ShaderMaterial` with a valid vertex shader fragment shader.
2. modify the fragment shader to use a uniform of any array type (i.e. `uniform vec3 u_array[1]`).
3. Attach the material to an object and render the object.

### Code

```js
// Create material
  var uniforms = {
    // add `new THREE.Vector3(1, 0, 0)`` to the color array to fix this program
    color: { value: [ ] },
    white: { value: true }
  };
  var vertexShader = document.getElementById('vertexShader').text;
  var fragmentShader = document.getElementById('fragmentShader').text;
  material = new THREE.ShaderMaterial({
    uniforms : uniforms,
    vertexShader : vertexShader,
    fragmentShader : fragmentShader
  });

  // Create cube and add to scene.
  var geometry = new THREE.BoxGeometry(200, 200, 200);
  mesh = new THREE.Mesh(geometry, material);
  scene.add(mesh);
```

### Live example

https://jsfiddle.net/tcv038j1/2/

### Version

r159

**Comment by Mugen87** [comment]
Providing an empty array is invalid input. We don not perform validation checks for performance reasons.
