### ISSUE TITLE
Why it's not possible to set WebGLCubeRenderTarget.texture as texture (map) for Material ? 

### ISSUE THREAD

**Issue by bytesbay** [mrdoob/three.js#27314]
### Description

Playing with WebGLCubeRenderTarget and different scenes.
I have 2 scenes. The first one renders a sphere with some noise on it, like planet clouds. 
The second scene is just the main scene for of my app.

Im trying to use the first scene with CubeCamera and separated WebGLCubeRenderTarget

And then displaying this generated texture on another sphere in scene#2 using `map`. 

But i got `WebGL: INVALID_OPERATION: bindTexture: textures can not be used with multiple targets`

The strange thing is if i use for example `envMap` - everything works without error.

### Reproduction steps

1. Setup default threejs scene
2. Insert the code that i added 

### Code

```typescript
const perlin_shader_mat = new THREE.ShaderMaterial({
  vertexShader: `
    
    varying vec3 vPosition;
    varying vec3 vNormal;
    
    void main() {
      vPosition = position;
      vNormal = normal;
      gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
    }
  `,
  fragmentShader: clouds_frag,
  uniforms: {
    uTime: new THREE.Uniform(0)
  },
  side: THREE.BackSide,
});
const perlin_clouds = new THREE.Mesh(
  new THREE.SphereGeometry(GLOBE_RADIUS, 64, 64),
  perlin_shader_mat,
);

const cube_scene = new THREE.Scene();
const cube_rt = new THREE.WebGLCubeRenderTarget(512, {
  format: THREE.RGBAFormat,
  generateMipmaps: true,
  minFilter: THREE.LinearMipmapLinearFilter,
  colorSpace: THREE.SRGBColorSpace,
});
cube_rt.texture.type = THREE.HalfFloatType;
const cube_camera = new THREE.CubeCamera( 0.1, 1000, cube_rt );
cube_scene.add(cube_camera);
cube_scene.add(perlin_clouds);

const clouds = new THREE.Mesh(
  new THREE.SphereGeometry(GLOBE_RADIUS * 1.04, 64, 64),
  new THREE.MeshStandardMaterial({
    map: cube_camera.renderTarget.texture,
  }),
);
scene.add(clouds);

cube_camera.update( renderer, cube_scene );
renderer.render(scene, camera)
```

### Live example

No, sorry 

### Version

r159

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
> The strange thing is if i use for example envMap - everything works without error.

When you are using an instance of `WebGLCubeRenderTarget`, its texture property is an instance of `CubeTexture`. Using a `CubeTexture` in a shader requires a `samplerCube` uniform type and `gl.TEXTURE_CUBE_MAP` as a binding point target. The `map` property uses `sampler2D` uniform type and thus requires `gl.TEXTURE_2D`. 

So in other words you can't use cube textures as 2D textures and vice versa.

**Comment by Mugen87** [comment]
Unfortunately, you can't sample a cube map like a normal texture. A conversion does not seem sense to make either since the special layout of cube requires a specific sampling.
