### ISSUE TITLE
The official examples no longer working on iOS/iPadOS

### ISSUE THREAD

**Issue by 1GR3** [mrdoob/three.js#27328]
### Description

None of the examples are working neither on iPhone nor iPad any more while the websites built on Three.js are still working fine.

### Reproduction steps

1.try to open any of these https://threejs.org/examples/ on iPhone or iPad
2. not working

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

0.159.0

**Comment by Mugen87** [comment]
I've tested the examples yesterday on an iPad with iPadOS 17.1.2 and they work as expected.

What kind of device and OS version are you using?

**Comment by Mugen87** [comment]
Also, as mentioned in https://github.com/mrdoob/three.js/issues/27327#issuecomment-1842841503, saying something "does not work" is not helpful in software development. 

You should always describe the error situation as detailed as possible. We can reopen the issue if you do so.

**Comment by Mugen87** [comment]
Ah okay. That's because your device does not yet fully support import maps yet (see #26836). The issue should go away if you update your OS to at least 16.4.

**Comment by 1GR3** [comment]
I could (and will eventually)update my iPad to 16.4. (and beyond) but I can't, for example update my iPhone anymore, and it is a shame that three.js which was running just fine on it won't be able to run any new projects which might be far less complex than the older ones. Is there a way to maintain the progress without breaking everything for those who're not running it on the latest and greatest devices/OS's? According to Statcounter, it means cutting out roughly 10% of the global users.

**Comment by Mugen87** [comment]
No sorry, we won't do that. We want to move forward without relying on polyfills and fallbacks even if this means a small number of devices will be excluded.

**Comment by 1GR3** [comment]
What was the last version of three.js that was supported on iOS/iPadOS prior to v16.4?

**Comment by 1GR3** [comment]
Thanks for clearing this out! I'm about to start a new project for a client and I'd like to insure it will be supported even on a bit older devices. What would be the easiest way to achieve that?

**Comment by Mugen87** [comment]
It's best if you ask such a question at the https://discourse.threejs.org/.
