### ISSUE TITLE
CSM directional lights are no longer calculated when shadow maps are disabled 

### ISSUE THREAD

**Issue by yfunk** [mrdoob/three.js#27338]
### Description

I've already [commented about this regression](https://github.com/mrdoob/three.js/pull/23631#issuecomment-1790721186) on the related PR, but didn't receive a response. So, in the hope of better visibility, I'm creating this issue for it.

It seems that after the changes made in #23631 the CSM directional lights are no longer being calculated at all when shadow maps are disabled on the renderer. See example below for more details.

Since the usage of CSM inevitably adds additional directional lights that affect scene lighting, turning off shadows while continuing to use these lights seems like a valid use case to me (e.g. in a 3D viewer app that lets the user disable shadows). I would only expect these lights to no longer be computed when the CSM parent node is removed or hidden from the scene.

### Reproduction steps

1. Set up a scene with `CSM`
2. Disabled shadows using `renderer.shadowMap.enabled = false`
3. Notice that the lighting of the whole scene is affected by this (gets darker) instead of just the shadows disappearing

### Code

_None, see example._

### Live example

I've modified the CSM example to add a toggle for shadow maps (`Controls > shadows`).

* [Example before PR](https://raw.githack.com/yfunk/three.js/csm-disable-shadowmap-before/examples/webgl_shadowmap_csm.html)
* [Example after PR (and latest version)](https://raw.githack.com/yfunk/three.js/csm-disable-shadowmap-after/examples/webgl_shadowmap_csm.html)

Previously, turning shadow maps on or off didn't affect the lighting of the scene, only the shadows themselves. Now, the whole scene becomes noticeably darker when shadow maps are turned off.

### Screenshots

| | shadow maps on | shadow maps off|
|-|-|-|
| before | ![before_on](https://github.com/mrdoob/three.js/assets/14955991/a010f735-64b7-4360-8b07-55a4474645a3) | ![before_off](https://github.com/mrdoob/three.js/assets/14955991/286e8a68-752a-411d-a548-db06c146e0b2)
| after | ![after_on](https://github.com/mrdoob/three.js/assets/14955991/6e12ea7f-3885-403e-8055-c7d2f10431d2) | ![after_off](https://github.com/mrdoob/three.js/assets/14955991/0e9664b8-8dc3-40f3-aa9a-4b99736593c0)

### Version

r158

**Comment by Mugen87** [comment]
Agreed, that the current behavior isn't right. Considering this issue as a regression.

@OndrejSpanel It was great to fix the issue you have mentioned in https://github.com/mrdoob/three.js/pull/23631#issue-1157280441 but a solution should ensure to not alter the existing behavior of `CSM`. We maybe have to revert #23631 until a better solution is found.

**Comment by OndrejSpanel** [comment]
I will check it.
