### ISSUE TITLE
Effectively limiting max texture resolution / overriding the capabilities that WebGLCapabilties reports

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#27330]
### Description

The capabilities that some devices report may be technically accurate but not actually practical.
For example, iOS devices happily report that they support 16k textures, but will crash if you actually attempt to use an 8k RGBA texture.

I've seen that there's existing code to, for example, downsize textures if their size exceeds what's been reported by the WebGL capabilities, but I'm unsure how I would override those (globally or per texture) when e.g. using the regular TextureLoader.

See
- https://github.com/mrdoob/three.js/blob/0e054301880a45142dd96b18f520a01a7a76ba10/src/renderers/webgl/WebGLTextures.js#L89

### Solution

Not sure – would like to be able to not have iOS devices crash just because they report a higher supported texture resolution than they actually allow for. In this case I know _better_ than the WebGL capabilities.

### Alternatives

Find each and every case where a texture is loaded and guard that with some resizing - not sure if that is even possible.
I looked into potentially monkey patching `WebGLTextures.resizeImage` but I haven't found a way to do that yet, and it does not feel "right".

**Comment by Mugen87** [comment]
The `capabilities` object is public. Can't you just do something like this:
```
renderer.capabilities.maxTextureSize = 4096;
```
This will override the value derived from `gl.MAX_TEXTURE_SIZE`.

**Comment by Mugen87** [comment]
`maxTextureSize` is only accessed once in `WebGLTextures`. How about we remove the variable so the module reads directly from `capabilities`?
