### ISSUE TITLE
Orbit Controls distance was not included in modifiers

### ISSUE THREAD

**Issue by jasonsturges** [mrdoob/three.js#27352]
### Description

Regarding https://github.com/mrdoob/three.js/pull/22174, why was setting distance left out of Orbit Controls?

API provides access via:
- `getAzimuthalAngle`
- `getDistance`
- `setPolarAngle`

But only mutates via:
- `setAzimuthalAngle`
- `setPolarAngle`

### Solution

Having a distance setter would nicely complete that API. 

### Alternatives

No biggie, just commonly use Orbit Controls and often want to set distance in addition to angle and azimuth.

**Comment by Mugen87** [comment]
The PR was never merged so `setAzimuthalAngle()` and `setPolarAngle()` are not part of the controls.

**Comment by jasonsturges** [comment]
@Mugen87 Bah, so sorry - this is a three-stdlib implementation
https://github.com/pmndrs/three-stdlib/blob/f35f76e67f763903fa11f9d7a413587b6efe2d6b/src/controls/OrbitControls.ts#L130-L168

**Comment by betaupsx86** [comment]
This would've been a great addition. I'm modifying distance/zoom via the camera position directly with my own damping. It would be great to have it as part of the API.

**Comment by mrdoob** [comment]
@betaupsx86 Do you mind elaborating?

**Comment by betaupsx86** [comment]
What the OP mentioned. A **setDistance** function would be nice. Currently I have a scene with orbit controls that resets the zoom to a fixed distance from the target after a few seconds. I also use **setAzimuthalAngle** and **setPolarAngle** in the same manner for the angles which works perfectly. But for the distance/zoom part I'm having to modify the camera manually, which is doable, but I wanted it to have really similar smoothing to the other two functions.
