### ISSUE TITLE
line2 outline Incorrect display.Want to extend the ability to render shapes.

### ISSUE THREAD

**Issue by HappyKent** [mrdoob/three.js#27375]
### Description

When I use line2 or some other custom vertex shader to calculate the texture of the vertex. The stroke will be incorrect.
![image](https://github.com/mrdoob/three.js/assets/45218695/7053293c-5046-40ee-bac2-6a82a804de3d)
![image](https://github.com/mrdoob/three.js/assets/45218695/18940ebf-12e0-40e9-bee1-d73e83d8f13a)
![image](https://github.com/mrdoob/three.js/assets/45218695/14669e13-48f4-4709-8b2c-ce37871a2637)

### Solution

add scene.overrideVertexShader
add scene.overrideFragmentShader
My English is poor, I don't know if I can express myself clearly

### Alternatives

add a renderer that only renders shapes

**Comment by gkjohnson** [comment]
I think it's best to ask a question at the [forum](https://discourse.threejs.org/) if you need help understanding what might be happening. It is recommended to include a live example of the problem using something like JSFiddle so others can understand the problem more easily.
