### ISSUE TITLE
Examples are broken - https://threejs.org/examples/ paths issue? 

### ISSUE THREAD

**Issue by kurtgrung** [mrdoob/three.js#27387]
### Description

Console error 
`TypeError: Module specifier, 'three' does not start with "/", "./", or "../". Referenced from`

See the issue here in `console`
[https://threejs.org/examples/#webgl_animation_keyframes](https://threejs.org/examples/#webgl_animation_keyframes)

### Reproduction steps

Examples are not working 

### Code

```js
// code goes here 
```

### Live example

https://threejs.org/examples/webgl_animation_keyframes.html

### Screenshots

<img width="1440" alt="Screenshot 2023-12-16 at 19 47 38" src="https://github.com/mrdoob/three.js/assets/114594062/06403c44-387a-4cb0-aa63-07b45521fdf2">

### Version

159

### Device

Desktop

### Browser

Safari

### OS

MacOS

**Comment by Mugen87** [comment]
It seems you are using an older version of Safari which does not support import maps. Try it with at least 16.4.

**Comment by kurtgrung** [comment]
Ok thanks for letting me know. 

I have `Safari Version 16.3 (18614.4.6.1.5)` installed ATM.

**Comment by Mugen87** [comment]
Please try to upgrade your system since we expect import maps support in the examples.

**Comment by kurtgrung** [comment]
Ok but anyone visiting [Three](https://threejs.org/) wont be be able to see any examples due to Import maps on an older browser.

**Comment by Mugen87** [comment]
Yes, we are aware of that. But it's always a tradeoff in supporting older systems and use new technology (ideally with no fallbacks). In this case, the latter one is more important to the project.

**Comment by kurtgrung** [comment]
I thought I would bring it to you're attention when I saw the page examples not working. 

As I was sure I visited the examples recently (was working) on `threejs.org`.  

`Safari 16.3 was Released January 23, 2023`. So not that old.  

[import-maps support](https://caniuse.com/import-maps). 

Why not have a fallback in place?
