### ISSUE TITLE
Can't load GLB models when using Deezer API

### ISSUE THREAD

**Issue by artrayd** [mrdoob/three.js#27385]
### Description

When trying to load model with GLTFLoader or Draco loader, I'm getting JSON error.

```
loading error: SyntaxError: Unexpected token 'o', "[object Rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at GLTFLoader.parse (GLTFLoader.js:344:1)
    at Object.eval [as onLoad] (GLTFLoader.js:239:1)
    at eval (three.module.js:43612:1)
```

We have manager to fix that error GLTFLoader by changing way we do fetch request, but Draco loader is much more complex. 

### Reproduction steps

1. Add <script src="https://e-cdn-files.dzcdn.net/js/min/dz.js"></script>
2. Try to load any glb file with or without draco compression

### Code

```js
this.modelLoader = new GLTFLoader()
this.modelLoader.load(
      `${this.cdn}/model/open-superbox.glb`,
      // './../model/open-superbox.glb',
      (gltf) => {
        this.model = gltf.scene
        this.scene.add(this.model)
      }
    )
```

### Live example

* [Demo on stackblitz](https://stackblitz.com/edit/nuxt-starter-7szzze?file=pages%2Findex.vue)

Click on open in new tab, to see the error

### Version

1.5.1

### Device

Desktop, Mobile, Headset

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows, MacOS, Linux, ChromeOS, Android, iOS

**Comment by gkjohnson** [comment]
Please questions at the forum if you need help: https://discourse.threejs.org/

Or a Deezer API forum if you have questions about that project.
