### ISSUE TITLE
Typescript - CSS2DRenderer, CSS3DRenderer does not inherit from Renderer

### ISSUE THREAD

**Issue by samuelint** [mrdoob/three.js#27411]
### Description

typescript `CSS2DRenderer`, `CSS3DRenderer` does not inherit from `Renderer` and force developer to force a cast when using multiple renderers and using polymorphism.

Adding the inheritance & having `domElement` in Renderer set to `HTMLElement` instead of `HTMLCanvasElement`, would avoid to cast where it wouldn't be needed.

Suggestion, have Renderer signature look like:
```
export interface Renderer<TDomElement extends HTMLElement = HTMLElement> {
  domElement: TDomElement;

  render( scene: Object3D, camera: Camera ): void;
  setSize( width: number, height: number, updateStyle?: boolean ): void;
}

export class WebGLRenderer implements Renderer<HTMLCanvasElement> { ... }
export class CSS2DRenderer implements Renderer { ... }
```

---
Updated: I seem that any of the renderers from `three/examples/jsm` inherit from `Renderer`.

### Reproduction steps

1. Use the code of this issue
2. Typescript error: 
  > Type 'CSS2DRenderer' is not assignable to type 'Renderer'.
  >    Types of property 'domElement' are incompatible.

### Code

```typescript
const webglRenderer = new WebGLRenderer()
const css2dRenderer = new CSS2DRenderer()

const renderers: Renderer[] = [webglRenderer, css2dRenderer]

renderers.forEach((renderer) => {
  renderer.render(scene, camera);
})
```

### Live example

Not applicable

### Version

r125

**Comment by Mugen87** [comment]
> CSS2DRenderer, CSS3DRenderer does not inherit from Renderer and force developer to force a cast when using multiple renderers and using polymorphism.

Sorry, we can't fix this since `Renderer` has a interface intended for 3D APIs like WebGL or WebGPU. It is not possible for the CSS renderers to implement of what the `Renderer` defines. It seems you have to find a solution on TS level.

**Comment by samuelint** [comment]
Even if they do not share the same Renderer implementation. Would it be possible to have every renderers to implement a shared interface? And use that interface instead of a base class.

if not possible in the JS implementation. Would it be possible to only adjust the TS types ?

**Comment by Mugen87** [comment]
> Would it be possible to only adjust the TS types ?

I'm not using TS so I can't tell you if this is a good idea. Maybe you can ask this question at https://github.com/three-types/three-ts-types.
