### ISSUE TITLE
成功上传一个模型后,会发现它的颜色不见了,变灰了

### ISSUE THREAD

**Issue by Mrs-zhou-cmd** [mrdoob/three.js#27414]
### Description

![image](https://github.com/mrdoob/three.js/assets/79730160/660dc9ea-affe-47ca-a85b-bad3c1b855f2)

![image](https://github.com/mrdoob/three.js/assets/79730160/b33c3ea1-989c-4dba-9923-c7090f5d8ddf)
[](![image](https://github.com/mrdoob/three.js/assets/79730160/cf7f3c37-54ea-423f-ab99-53732fd4198a))

我是使用了你们官方的两个工具去打开该模型

### Reproduction steps

1.
2.
3.
[](url)

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

0.158.0

**Comment by Mrs-zhou-cmd** [comment]
![image](https://github.com/mrdoob/three.js/assets/79730160/b77d8012-fad2-400a-a5ee-7878dcd4b0d6)

**Comment by skyclouds2001** [comment]
我觉得你应该使用英文提 issue 更好

**Comment by mrdoob** [comment]
Yes please... Use English.
