### ISSUE TITLE
Alternate GroundProjectedSkybox

### ISSUE THREAD

**Issue by elalish** [mrdoob/three.js#27422]
### Description

I recently tried to use `GroundProjectedSkybox` in `<model-viewer>` and utterly failed. I'm not sure I can list all the problems I found, but here are a few:

1) There is a radius parameter, but the object also seems to need to be scaled (possibly to this same radius, possibly independent?).
2) If the parameters have units, then I'm dubious of the math - the example uses a height of 15 (presumably meters, since it's loading a glTF car) and I personally doubt anyone put their camera that high, unless it was a drone.
3) When I tried to apply it to other scenes, I could find no combination of parameters that gave a sensical result, and no system of parenting that allowed a model to appear fixed on the ground. I'm not actually sure it's possible, because I noticed that even in the example, the ground appears to slip under the wheels as the camera zooms, and it doesn't enable pan at all:

https://github.com/mrdoob/three.js/assets/97088/22266465-0d5c-4474-851d-7f489ff9f440

Note the sand ripple under the front tire.

I could find no clear way to fix it, so I just wrote my own. It's dramatically simpler (no custom shaders), and pretty much the only drawback is that it's slower to dynamically update the parameters, though I see no problem with this in practice since the three.js example is pretty much the only place I would imagine actually doing that on a per-frame basis. 

Mine also has the advantage of making a smooth curve from the flat ground to the sky sphere:
<img width="748" alt="image" src="https://github.com/mrdoob/three.js/assets/1649964/cf1b31a5-f30c-4475-a8aa-c4c3892339b1">

It's not much code, but curious if anyone would like to see it upstreamed, and if so, in what form? @mrdoob @WestLangley @bhouston

### Reproduction steps

1. Attempt to pan around a model with a GroundProjectedSkybox.

### Code

See my alternative [here](https://github.com/google/model-viewer/pull/4604/files#diff-988c3121907b851859f7a1cd472cf33174f0b2b88b8cd9ffae1754521df36646)

### Live example

Current: https://threejs.org/examples/?q=ground#webgl_materials_envmaps_groundprojected
Mine: https://modelviewer.dev/examples/lightingandenv/#groundedSkybox and https://modelviewer.dev/examples/augmentedreality/#ar

### Version

r159

**Comment by mrdoob** [comment]
The sand ripple does indeed slip:


https://github.com/mrdoob/three.js/assets/97088/22266465-0d5c-4474-851d-7f489ff9f440

**Comment by mrdoob** [comment]
I would vote for just replacing it with the new code.
The fact that it doesn't require custom shaders makes it easier to maintain and also render with `WebGPURenderer`.

**Comment by bhouston** [comment]
beautiful!

**Comment by hybridherbst** [comment]
Thanks so much!
I assume your version also doesn't have the visible seam from the original?

**Comment by elalish** [comment]
Sure, I can replace this if you want - do you still want it called `GroundProjectedSkybox` or my `GroundedSkybox` or something else? Any other changes you want from [this](https://github.com/google/model-viewer/pull/4604/files#diff-988c3121907b851859f7a1cd472cf33174f0b2b88b8cd9ffae1754521df36646)?
