### ISSUE TITLE
WebGLRenderer: warn on invalid or unsupported texture filtering

### ISSUE THREAD

**Issue by CodyJasonBennett** [mrdoob/three.js#27434]
### Description

A common issue going around previously with iPad and more recently iOS is the lack of support for `OES_texture_float_linear` which makes it very easy to configure unrenderable textures which silently fail on those devices.

### Solution

It would help to warn if an invalid or unsupported filtering combination is used. Mainly, as mentioned above, this would include `FloatType` (custom) + `LinearFilter` (default). Not including invalid options passed to `Texture.magFilter` as that is currently documented, but I linked below related configuration painpoints with mipmaps.

### Alternatives

Document limits with float textures (WebGL only), but there isn't a clear place that I can see to do so.

### Additional context

Related: #18861, https://github.com/mrdoob/three.js/issues/17314#issuecomment-793907661

https://twitter.com/Cody_J_Bennett/status/1737517374935359872 (many such examples recently)

**Comment by aardgoose** [comment]
The issue also exists with WebGPU and requires an extension.

https://www.w3.org/TR/webgpu/#float32-filterable

**Comment by Mugen87** [comment]
A good place for this check in would be in `setTextureParameters()` in `WebGLTextures`. For now, I would specifically catch the `OES_texture_float_linear` issue so maybe this code is sufficient:

```js
if ( texture.type === FloatType && extensions.has( 'OES_texture_float_linear' ) === false &&
	( texture.magFilter === LinearFilter || texture.magFilter === LinearMipmapNearestFilter || texture.magFilter === NearestMipmapLinearFilter || texture.magFilter === LinearMipmapLinearFilter ||
	texture.minFilter === LinearFilter || texture.minFilter === LinearMipmapNearestFilter || texture.minFilter === NearestMipmapLinearFilter || texture.minFilter === LinearMipmapLinearFilter ) ) {

	console.warn( 'THREE.WebGLRenderer: Unable to use linear filtering with floating point textures. OES_texture_float_linear not supported on this device.' );

}
```

**Comment by mrdoob** [comment]
That sounds good to me 👍
