### ISSUE TITLE
Shader rendering black pixels on Mac M2

### ISSUE THREAD

**Issue by andreasrosdal** [mrdoob/three.js#27435]
### Description

The shader is rendering black pixels on a Mac M2. I have seen this same problem in Firefox on Linux sometimes.

The shader renders correct terrain colours on Google Chrome on Windows.

Is there something I can improve in the shader to make it more robust and work cross-platform?

### Reproduction steps

Play Freeciv3D on https://www.fciv.net using a Mac M2.

### Code

The shader source code
https://github.com/fciv-net/fciv-net/blob/main/freeciv-web/src/main/webapp/javascript/webgl/shaders/terrain_fragment_shader.glsl

https://github.com/fciv-net/fciv-net/

### Live example

https://www.fciv.net

### Screenshots

![GB_w9iSXgAAq5ln](https://github.com/mrdoob/three.js/assets/41650711/0664cce2-7b26-42ec-bc99-65558cd61018)

### Version

r160

### Device

Desktop

### Browser

Safari

### OS

MacOS

**Comment by gkjohnson** [comment]
Please ask for help at the forum if you need help writing custom shaders:

https://discourse.threejs.org/
