### ISSUE TITLE
Modifying the position of the scene can cause misalignment of the SpotLight and SpotLightHelper positions

### ISSUE THREAD

**Issue by sheepdragon** [mrdoob/three.js#27437]
### Description

Modifying the position of the scene can cause misalignment of the SpotLight and SpotLightHelper positions

### Reproduction steps

If the scene is not at the origin, it will trigger an error

### Code

```js
// mesh
const plane = new THREE.Mesh(
  new THREE.PlaneGeometry(100, 100),
  new THREE.MeshStandardMaterial({ color: '#ccc' })
);
plane.rotation.x = -Math.PI / 2
plane.receiveShadow = true
scene.add(plane);

const flag = new THREE.Mesh(
  new THREE.BoxGeometry(1, 1, 1),
  new THREE.MeshStandardMaterial({ color: 'red' })
);
flag.position.y = 10;
scene.add(flag);

// light
const spotLight = new THREE.SpotLight('#fff');
spotLight.castShadow = true;
spotLight.angle = Math.PI / 180 * 30
spotLight.intensity = 2
spotLight.distance = 20
spotLight.penumbra = 0.1
spotLight.decay = 0.1
const spotLightHelper = new THREE.SpotLightHelper(spotLight);
scene.add(spotLight, spotLightHelper);
spotLight.position.y = 10

// Trigger
scene.position.y = -2
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/73zhtwdq/)
* [jsfiddle-dev](https://jsfiddle.net/vxnoc5fy/51/)

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/4659052/dc812551-6fe1-463f-9bcb-a24fa7e2231f)
![image](https://github.com/mrdoob/three.js/assets/4659052/3d49aa14-2197-4801-993e-c113c5341973)

### Version

r159

### Device

Desktop

### Browser

Edge

### OS

Linux

**Comment by sheepdragon** [comment]
I found that other helpers also have the same problem. If matrixAutoUpdate=true in the helper, it works fine. I'm not sure why matrixAutoUpdate defaults to false

**Comment by Mugen87** [comment]
`SpotLightHelper` holds the following lines of code:
```js
this.matrix = light.matrixWorld;
this.matrixAutoUpdate = false;
```
These ensure the the light transformation in world space is copied to the helper. However this only works when a) the helper is child of the scene and b) the scene itself is not transformed. If a transformation is applied, it is in fact honored twice.

**Comment by gkjohnson** [comment]
It should be possible to ensure the helper is _always_ positioned at the same point as the target light regardless of hierarchy position, no? You just need to transform the target lights world transformation in the local frame of the helpers parent.

I'd have to test and double check the math but this is roughly what we'd have to do and then I believe it would always work.

```js
const invMatrix = new Matrix4();
const localMatrix = new Matrix4();
const parent = light.parent;
const target = light.target;

// transform into the parents local frame
invMatrix
  .copy( parent.matrixWorld )
  .invert();

// transform the targets frame into the local frame
localMatrix
  .copy( target.matrixWorld )
  .premultiply( invMatrix )
  .decompose( light.position, light.quaternion, light.scale );
```
