### ISSUE TITLE
anisotropy effect looks not that correct

### ISSUE THREAD

**Issue by iefreer** [mrdoob/three.js#27440]
### Description

I have a simple scene on three.js editor:
1. one sphere model with physical material, and set anisotropy strength to 1, roughness to 0.5, position is [0,0,0]
2. camera is the default one
3. one directional light which is put at [0, 0, 7]

I then conducted a comparative test between three.js r159 and khronos glTF-Sample-Viewer, the result attached as below:
![picture 0](https://github.com/mrdoob/three.js/assets/286215/d3cc269e-b360-4df7-8dc3-e2eb176d504c)
![picture 1](https://github.com/mrdoob/three.js/assets/286215/bdc5c680-beac-4126-bc44-1d5fdcae7838)

I found the main difference is at the polar area of the sphere, three.js renders a small part with white colors while gltf sample viewer doesn't.
which in my point of view, the white area at the top is not correct as there shouldn't be highlight at that top point?

The test scene is attached also.

### Reproduction steps

no

### Code

no

### Live example

no

### Version

r159

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by iefreer** [comment]
[scene.json](https://github.com/mrdoob/three.js/files/13764880/scene.json)

**Comment by elalish** [comment]
It looks like your sphere doesn't include tangent vectors - the sample viewer probably computes those automatically since they are not concerned about performance. Try adding them to your model and see if that fixes it.

**Comment by Mugen87** [comment]
I can confirm that computing tangents produces the expected result of the OP:

<img width="788" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/2af5b3d4-eb82-449a-b2f7-d641b16f78a4">
