### ISSUE TITLE
MaterialX: Default input values not being specified results in errors every frame

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#27458]
### Description

It seems that this kind of MaterialX structure currently doesn't work:
```xml
<modulo name="frac" type="vector3" >
    <input name="in1" type="vector3" nodename="mult" />
</modulo>
```

In this particular case, according to the MaterialX spec the second input is optional and has a default value of 1 in all channels; not sure how I'd specify that in the current Nodes codebase. The same issue probably also happens when other nodes (e.g. divide) that have optional inputs are used without that input actually being specified.

>  modulo: [...]
○ in1 (float or colorN or vectorN): the value or nodename for the primary input
○ in2 (same type as in1 or float): the modulo value or nodename to divide by, cannot be 0 in
any channel; **default is 1.0 in all channels**

Here's an example file that currently breaks:
[MyLitGraph-default-inputs.mtlx.zip](https://github.com/mrdoob/three.js/files/13781838/MyLitGraph-default-inputs.mtlx.zip)

And here's a more interesting one (requires #27456) that breaks too:
[MyLitGraph_error_three.mtlx.zip](https://github.com/mrdoob/three.js/files/13781845/MyLitGraph_error_three.mtlx.zip)

Both of them look fine in https://academysoftwarefoundation.github.io/MaterialX/:
<img width="528" alt="image" src="https://github.com/mrdoob/three.js/assets/2693840/024e0437-ff40-45d6-9565-c81ab4fe58b7">

The exception happens in `MathNode.js` which tries to call `.build` on the null `bNode`:
<img width="986" alt="image" src="https://github.com/mrdoob/three.js/assets/2693840/f725bf4b-aad3-4f88-a79a-5bd819e69cf8">

cc @sunag 

### Reproduction steps

1. Load the MaterialX file in three.js
2. Observe error every frame

### Version

r160 dev

**Comment by sunag** [comment]
Maybe we could add a optional field in `MXElement`, for example:

```js
new MXElement( 'modulo', mod, [ 'in1', 'in2' ], { 'in2': float( 1 ) } )

// MXElement( name, nodeFunc, params, optionals )
```
