### ISSUE TITLE
SVGLoader pointsToStroke incorrect UV mapping when texture applied

### ISSUE THREAD

**Issue by IRobot1** [mrdoob/three.js#27464]
### Description

This problem isn't new.  It's been around for a long time.

When adding a texture to the stroke generated by SVGLoader.pointsToStroke, the resulting UV mapping is incorrect for straight parts and the last triangle.

The UV mapping for a Bezier curve look really good except at the end
![image](https://github.com/mrdoob/three.js/assets/25032599/052dda2e-f24b-40f9-be34-0cb0496f2183)

The UV mapping for a straight line doesn't look good at all
![image](https://github.com/mrdoob/three.js/assets/25032599/4cbdee29-8744-4a0b-8869-8c51a193ad6a)

The UV mapping for a curved lines looks good for the bends, but not for the straight lines
![image](https://github.com/mrdoob/three.js/assets/25032599/bac15e7c-c58d-4e42-a316-b15ba65ef3bd)

### Reproduction steps

set stroke style
pass points into SVGLoader.pointsToStroke to get geometry
assign texture to material
add mesh to scene

### Code

```js
const style = SVGLoader.getStrokeStyle(0.12, "black", "miter", "butt");

const texture = new TextureLoader().load("./src/road.png");

  const geometry = SVGLoader.pointsToStroke(
    straightpoints.map((v) => new Vector2(v.x, v.y)),
    style
  );
  const material = new MeshBasicMaterial({ map: texture });
  const rect = new Mesh(geometry, material);
  scene.add(rect);
  rect.position.x = 0.2;
```

### Live example

https://codesandbox.io/p/sandbox/three-stroke-texture-uv-h9w76x?file=%2Fsrc%2Findex.js

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/25032599/052dda2e-f24b-40f9-be34-0cb0496f2183)

![image](https://github.com/mrdoob/three.js/assets/25032599/4cbdee29-8744-4a0b-8869-8c51a193ad6a)

![image](https://github.com/mrdoob/three.js/assets/25032599/bac15e7c-c58d-4e42-a316-b15ba65ef3bd)

### Version

160

### Device

Desktop

### Browser

Edge

### OS

Windows

**Comment by Mugen87** [comment]
@nieyuyao Do you have any ideas how we could improve the situation in `SVGLoader`?

I've created an editable fiddle based on @IRobot1's codesandbox. There is also a new (commented out) line in the code that loads a uv debug texture that might help to investigate the issue. 

https://jsfiddle.net/n47fxmy5/2/

**Comment by nieyuyao** [comment]
@Mugen87  The issue seems to be that the `uv.y` of `currentPointL` and `currentPointR` are incorrect.

https://github.com/mrdoob/three.js/blob/69e8505887d7c0c847515bcea2114a4ab8040c36/examples/jsm/loaders/SVGLoader.js#L2920-L2930

But I don't have a good idea of how to improve the loader.

**Comment by IRobot1** [comment]
Confirmed fixed in v161
![image](https://github.com/mrdoob/three.js/assets/25032599/b17fb53d-9819-4ea4-9d99-b9fceeb9f6f5)
