### ISSUE TITLE
Use `Object.keys(…)` to iterate over "own" properties?

### ISSUE THREAD

**Issue by lgarron** [mrdoob/three.js#27465]
### Description

Someone reported [an issue](https://github.com/cubing/cubing.js/issues/305) with a project that I work on that's based on `three.js`. It turns out they had added a property on `Object.prototype` directly (instead of using `Object.defineProperty(…)`, which means that it shows up as a key for *every* `for (… in someObject)` iterator. For example:

https://github.com/mrdoob/three.js/blob/1b8412c700316e3ed0d3b5f5ab827287e3351bad/src/renderers/webgl/WebGLGeometries.js#L84-L88

This crashes a bit further down the stack due to an unexpected property.

This is a common caveat in JS: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#iterating_over_own_properties_only

### Solution

It's possible to guard against this using [`for…of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) and [`Object.keys(…)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) (both of which are widely compatible at this point):

```
for (const name of Object.keys(geometryAttributes) ) {
	attributes.update( geometryAttributes[ name ], gl.ARRAY_BUFFER );
}
```

### Alternatives

It might not make sense to make this change, since it could be reintroduced by accident at any moment unless it's enforced by a linter in CI.

### Additional context

I don't personally need this change, just reporting it in case you might want to implement it. Since `three.js` is

**Comment by mrdoob** [comment]
Have you done performance tests? I think `Object.keys()` is slower than the current code and the current code needs to run many times per second.

**Comment by lgarron** [comment]
> Have you done performance tests?

Not at all, that would also be a good reason not to do this. (In fact, we’re still using `for…in` in our own code, quite possibly on some hot paths.)

**Comment by gkjohnson** [comment]
I think adding a field to Object.prototype is extremely bad form and of course error prone in all kinds of other contexts outside of this project. I don't think we should encourage it by accommodating the practice in three.js
