### ISSUE TITLE
THREE.BufferGeometryUtils.mergeAttributes fails to merge LineGeometry

### ISSUE THREAD

**Issue by liorGameDev** [mrdoob/three.js#27478]
### Description

I try to merge a list of LineGeometry as in this example:
https://threejs.org/examples/#webgl_lines_fat

And get these errors:
`failed while trying to merge the instanceStart attribute`
And
`InterleavedBufferAttributes are not supported. `

Would appreciate if someone can shad a light on this one and suggest a solution

### Reproduction steps

1. Create several LineGeometry as imported in this example: https://threejs.org/examples/#webgl_lines_fat
2. Use THREE.BufferGeometryUtils.mergeAttribute in order to merge them

### Code

```js
const lineGeometry1 = new LineGeometry();
const lineGeometry2 = new LineGeometry();

lineGeometry1.setPositions([0,0,0,1,1,1])
lineGeometry2.setPositions([2,2,2,3,3,3])

const mergedGeom = BufferGeometryUtils.mergeGeometries([lineGeometry1, lineGeometry2])
console.log('mergedGeom', mergedGeom) // null```


### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)


### Screenshots

_No response_

### Version

160

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by gkjohnson** [comment]
The thick lines class uses `InterleavedBufferAttributes` which are not supported by the mergeGeometries function as the error states.

If have more questions about what this means or how to work around it please ask at the forum:

https://discourse.threejs.org/
