### ISSUE TITLE
bug in Audio.js setDetune

### ISSUE THREAD

**Issue by QuickMick** [mrdoob/three.js#27477]
### Description

see https://github.com/mrdoob/three.js/blob/ccbe74b3338edaa3d55bfc1462d68fbe2cabf40c/src/audio/Audio.js#L273C29-L273C29
```

	setDetune( value ) {

		this.detune = value;

		if ( this.source.detune === undefined ) return; // only set detune when available

		if ( this.isPlaying === true ) {

			this.source.detune.setTargetAtTime( this.detune, this.context.currentTime, 0.01 );

		}

		return this;

	}
```

shoudn't it be 		
`if ( this.detune === undefined ) return;` instead? it will return an error, if u setDetune while it is not playing and that does not seem to be intended?

### Reproduction steps

1. create a new THREE.Audio
2. use the function setDetune

### Code

```js
new THREE.Audio(listender).setDetune(0);
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r160

**Comment by Mugen87** [comment]
> shoudn't it be if ( this.detune === undefined ) return; instead? 

see #15566. The line exists to prevent issues with Safari.

>  it will return an error, if u setDetune while it is not playing and that does not seem to be intended?

The problem is it is not intended to call `setDetune()` without a valid audio source in the first place. You are supposed to set the property `detune`. But I think we can make the code a bit more robust by rewriting the code to:
```js
setDetune( value ) {

	this.detune = value;

	if ( this.isPlaying === true && this.source.detune === undefined ) {

		this.source.detune.setTargetAtTime( this.detune, this.context.currentTime, 0.01 );

	}

	return this;

}
```

**Comment by QuickMick** [comment]
thanks for your fast response!
i would like to ask: why is it not intended then?
if it is not intended to be used, while it is not been playing, why don't the other setters have no issues with that? e.g. setLoop, or setPlaybackRate - it appears to be a bit inconsistent, ìf setDetune is the only one that crashes. Also, it would make no difference, because `this.detune` is set and will be used, when you call .play().
if you want to stay with that decission, maybe you could add that to the documentation https://threejs.org/docs/#api/en/audio/Audio.setDetune

my usecase is, that i currently write an editor and a UI to change these settings. so, when i change the sound settings, i would need to do that:
```
if(sound.isPlaying)sound.setDetune(value)
else sound.detune=value;
```
and in my opinon, it would just be more robust, if you could use just the setter always.

thanks your your time.

**Comment by Mugen87** [comment]
I agree it's inconsistent if some methods work and others don't. I also only wanted to describe how the intended API usage looks like. After #27479, there shouldn't be an issue anymore.
