### ISSUE TITLE
Does three.js currently provide adjustment hubs similar to babylon.js: when dragging the model, the current option is used to determine the hub position of the model.

### ISSUE THREAD

**Issue by WREQI** [mrdoob/three.js#27483]
### Description

Adjusting hub functions

### Solution

babylon.js

### Alternatives

no

**Comment by WREQI** [comment]
babylon.js  positionGizmo
![20190819171516876](https://github.com/mrdoob/three.js/assets/35467304/2a59f6f3-e049-4172-b78b-151adbcdd486)
![20190819175034437](https://github.com/mrdoob/three.js/assets/35467304/d0669609-cb40-4bd2-b209-1c818e705f8a)

**Comment by gkjohnson** [comment]
If you have questions about three.js and what features are available please ask as the three.js forums:

https://discourse.threejs.org/
