### ISSUE TITLE
BufferGeometryUtils.mergeGeometries() throws unclear error

### ISSUE THREAD

**Issue by Matheos96** [mrdoob/three.js#27509]
### Description

The `mergeGeometries` function of `BufferGeometryUtils` throws the following error if (accidentally) given an empty array:

> Cannot read properties of undefined (reading 'index')
TypeError: Cannot read properties of undefined (reading 'index')

I feel like a more appropriate error message would be in place, perhaps 

> Error: mergeGeometries() was provided an empty array. The exepected input is an array of Geometries.

or something.

Not a bug per say but something that had me scratching my head a few times

### Reproduction steps

1. import the `mergeGeometries` function
2. Call `mergeGeometries` with an empty array: `mergeGeometries([])`
3. Unclear error displayed and execution interrupted

### Code

```js
import { mergeGeometries } from "three/addons/utils/BufferGeometryUtils.js";
mergeGeometries([])
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/2b3putjr/2/)
* [jsfiddle-dev](https://jsfiddle.net/Lhr0by14/1/)

### Version

r160

**Comment by sikey-dev** [comment]
It seems like you have identified an issue with the `mergeGeometries` function in the `BufferGeometryUtils` module from the Three.js library. While it's not a bug, per se, you're suggesting that the error message could be more informative.

If you have the ability to modify the library or create a pull request, you could propose an improvement to the error message in the source code. Here's an example of how you might enhance it:

```javascript
function mergeGeometries(geometries) {
    if (!Array.isArray(geometries) || geometries.length === 0) {
        throw new Error('mergeGeometries() was provided an empty array or a non-array. The expected input is an array of Geometries.');
    }

    // rest of the function implementation
    // ...
}
```

This modification checks if the input is an array and if it's not empty before proceeding with the rest of the function. If the input is invalid, it throws a more informative error message.

Remember to test your changes thoroughly before submitting a pull request, and consider creating an issue on the Three.js GitHub repository to discuss the proposed improvement with the community.

**Comment by sikey-dev** [comment]
## Proposed Enhancement: Improved Error Handling in mergeGeometries

### Issue
The current implementation of the `mergeGeometries` function does not provide a clear error message when an empty array is passed as an argument. This can lead to confusion for developers trying to use the function.

### Proposed Change
Enhance the error handling in the `mergeGeometries` function to throw a more informative error message when an empty array or a non-array is provided as input. The suggested error message is:

```plaintext
Error: mergeGeometries() was provided an empty array or a non-array. The expected input is an array of Geometries.

**Comment by Matheos96** [comment]
@sikey-dev Yes of course :) With pleasure, I will create a PR in the near future. I suppose this Issue is already a good basis for community discussion?

**Comment by LeviPesin** [comment]
@itachi9797 Is your comment AI-generated?
