### ISSUE TITLE
In addition to #27508 a new node to readback datas from the GPU to CPU

### ISSUE THREAD

**Issue by Spiri0** [mrdoob/three.js#27515]
### Description

#27508 inspired me to an expansion.
What sunag describes is already possible with wgslFn (combining several shaders in one node):
But what is cumbersome is getting the data that is in the GPU back into the CPU. There are situations in which this is absolutely necessary because certain things only work in the GPU, but are then needed again in the CPU for further processing.

### Solution

I imagine it like this:
```
const shader0 = wgslFn(...);   //or tslFn
const shader1 = wgslFn(...);   //or tslFn
const shader2 = wgslFn(...);   //or tslFn

const material meshBasicNodeMaterial();
material.outputNode = outputStruct(  //or tsl equivalent to outputStruct
   shader0(params),	//Because it comes first, it is perceived as the colorNode shader
   shader1(params),	//additional datas
   shader2(params),	//additional datas
);

const dpr = window.devicePixelRatio;
const width = window.innerWidth * dpr;
const height = window.innerHeight * dpr;

const pixelBuffer = new Float32Array(width * height * 4);

//here the new node
const rtpb = new RTPBNode(material.outputNode.members[1], width, height, pixelBuffer);
rtpb.render(renderer);   //readback data from the GPU to CPU into pixelBuffer
```

That would work with tsl and wgsl. The RTPBNode would correspond to gl.readPixels, only universally there for tsl and wgsl, WebGL and WebGPU.

### Alternatives

At the moment you can do this with multipleRenderTargets. That's why this point is something that is of low priority compared to the other topics that exist in the issues.

**Comment by LeviPesin** [comment]
In my understanding (@sunag please correct me if I'm wrong) each Node in essence is a shader statement or expression -- it can be hugely different, it can be functions, uniforms, or even a result of rendering, but in the end every node is still a *GPU*-side expression -- an expression that on a low level gets put into a shader, and on a high level can be used in other nodes or as a material parameter/anything GPU-side basically.

In my opinion instead of this proposal something like RTTNode (which is already suggested) and a method like `RTTNode.readBuffer()` to read the data would be better. So, basically I mean that we just shouldn't interpret that data as a node -- and maybe use this as a general rule to decide what could be a node by itself and what just can be got from a node/renderer.

**Comment by Spiri0** [comment]
Gladly: My thoughts as a user didn't go that far, but I understand your arguments very well. The RTPBNode would first have to render the shader into a texture anyway like the RTTNode in order to then be able to read out the data. But if the RTTNode already does that, then it makes more sense to make the intended functionality of the RTBPNode to a function of the RTTNode.

P.S. I have implemented the environment with the cubeTexture:

![envmap.png](https://github.com/mrdoob/three.js/assets/69024222/9ade69aa-e845-4254-b242-3fc809b48aab)

From cubeRenderTarget:
![eswird2.PNG](https://github.com/mrdoob/three.js/assets/69024222/1722f6fb-8bde-483b-8241-dbb35c79f1e8)

This meanwhile looks very similar to a Godot and Unity ocean. You once showed a picture from a 3D engine on some topic with a water surface where it could see seaweed and corals through the water. I don't remember what that was about. Maybe shadows. For such subsurface effects the depthTexture is missing in the wgslFn. 

The RTT.readBuffer() would be necessary for buoyancy simulation.
I pass the time doing other things. There is enough to do.

But RTTNode.readBuffer(); 

is definitely a good idea 👍

**Comment by Spiri0** [comment]
Maybe the .readBuffer() function would be senseful for the several texture objects in general?

**Comment by Spiri0** [comment]
I'm wondering if anyone sees a need for the node I suggested?
I ask because I'm personally happy with "await renderer.readRenderTargetPixelsAsync()". I just thought that a node might suit some people more, but if there's no need for it, it's not necessary. Then I close this issue.

**Comment by Makio64** [comment]
@Spiri0 Here a use case I just cross : when the cursor over some zone of the mesh ( needing a readback to see whats under the cursor ) the material react in according way. 
Of course I can do without node but I could done anything of things without node before , so i feel it make sense to make this node!

**Comment by Spiri0** [comment]
@Makio64 If that could help you, I have an alternative to readRenderTargetPixelsAsync. You can also use storageBuffers if you only want to read back datas. You can also use this with Uint32Array.
```
//define buffer
const buffer = new THREE.StorageBufferAttribute( new Float32Array( size * 4 ) , 4 );

//assign to shader 
storage( buffer, 'vec4', buffer.count )  

//readback from gpu
const dataFromGPU = new Float32Array( await renderer.getArrayBufferAsync( buffer ) );
```
