### ISSUE TITLE
Mouse wheel zoom with orbit controls causes scene to fly away

### ISSUE THREAD

**Issue by jedleslie** [mrdoob/three.js#27535]
### Description

Hi - 

This a change that happened between 159 and 160.  I'm betting it has to do with the OrbitControls zoom issue that was being worked out.  

### Reproduction steps

1. Make a scene with orbit controls
2. Use Mouse wheel to zoom the scene
3. See it just fly out of control

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

0.160

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Can you please check if this still happens with the current `dev` version of `OrbitControls`? Maybe #27446 already fixed the issue.

**Comment by jedleslie** [comment]
Yes!  Thank you.  The issue is resolved with that dev version.  Looking forward to 161.  

Thanks for all you do!
