### ISSUE TITLE
Per Object: Transparency / Visibility / Opacity

### ISSUE THREAD

**Issue by Inuniku** [mrdoob/three.js#27547]
### Description

Fading multiple objects in a scene is hard. You have to clone materials and set the opacity or alpha value. If only there was a simple solution like:

```javascript
const mesh = new Mesh(geom, materials);
mesh.visibility = 0.5;
``` 

You should be able to react to any change of the scene graph. If we use "just" cloned materials we have these problems:

```javascript
mesh.visibility = 0.5
``` 
☞Changing visibility of any mesh (could be per frame) would affect the resulting opacity. So we need to clone if transparent, and best reuse initial material if visibility = 1.0.

```javascript
mesh.material.opacity = 0.5
``` 
☞ Changes to the opacity of any (original) material would also affect the resulting opacity (visibility of the mesh * opacity)

```javascript
mesh.material.color.set('red')
``` 
☞ Changes to the properties of original material of the mesh need to affect cloned materials.

```javascript
mesh.material = newMaterial`
``` 
☞ The assignment of a new material to mesh need to create a new cloned material if visibility is not 1.0.

### Solution

![Animation3](https://github.com/mrdoob/three.js/assets/16117001/1433d6bf-527e-4f71-9326-77a3b71f03fe)

Proposal: #27546

### Alternatives

**_Dithering_** could also be used to fade objects quickly. This `dither_fade` parameter would also be best implemented on a per object level.

### Additional context

Decisions that could be discussed:
- **Name (visibility, opacity, transparency, fade)**: `visibility` like in (https://doc.babylonjs.com/typedoc/classes/BABYLON.AbstractMesh#visibility) or 3ds Max 
![image](https://github.com/mrdoob/three.js/assets/16117001/98aa419e-d3b2-41ec-b5bb-6d18265c2492)
- **`Object3D`**: I defined the parameter in `Object3d`. This offers flexibility for traversing. It might be better suited for `Mesh`s (renderable objects).
- **Like opacity**: It behaves exactly like changing the properties `transparent` and `opacity` on the `Material`.
- **No hierarchical inheritance**:  It will only affect the current object. If you want hierarchical fading, you have to handle this in the application. This offers flexibility how to refresh or inherit the visibility value.
- **Behaves not like `visible`**: Setting `visible = false` will prevent the object and hierachy from rendering. However setting the **`visibility`** to `0.0` won't prevent the object from rendering. (This is the same behavior as setting material.opacity to 0.0).
- **No automatic change of the blending**: Blending will be used like defined in the material. (Alpha per default)

**Comment by RemusMar** [comment]
> Fading Objects is hard. You have to clone materials and set the opacity or alpha value. 

It's not a big deal and you have to clone some materials ONLY if they are used by other models.
Here is a fast solution (click on the stage to turn the opacity OFF/ON):
https://necromanthus.com/Test/html5/LittlestTokyo_gltf.html

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/pull/27546#issuecomment-1890408603.
