### ISSUE TITLE
Running local file giving error due to no style on canvas?

### ISSUE THREAD

**Issue by danzen** [mrdoob/three.js#27540]
### Description

In earlier versions of three.js the canvas tag was made with createElementNS( 'http://www.w3.org/1999/xhtml', name ); (not secure) and it worked loading from local file system.  Now the tag is made with createElementNS( 'https://www.w3.org/1999/xhtml', name );  (secure) and it gives the attached error saying that the canvas does not have a style tag - in latest Chrome and Firefox.  If I just remove the s it does not give the error and works.

### Reproduction steps

1. run from file system rather than server
2.
3.

### Code

```js
 const renderer = new THREE.WebGLRenderer({antialias:true});
```

### Live example

NA

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/380281/2a2121b7-b35e-4b9f-9132-c0c17aa89ab8)

### Version

r156

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
We expect `three.js` is executed in a valid environment. Loading directly from the file system is not a workflow we support (and advocate).

However, it seems other developers experienced the same issue in context of other libraries. A typical workaround is to overwrite `document.createElementNS` with a custom function (in your case, one that always forces the usage of HTTP).

**Comment by danzen** [comment]
A weird thing is that R155 uses the  createElementNS with the https and it works.  Whereas R156 does not work with the https but works with the http.  I wonder what in the code is causing that.  Looking up createElementNS - there is a bit on important URIs and they do not use the https.  If anyone with knowledge along these lines ever has a hint they can drop here... that would be nice. 

![image](https://github.com/mrdoob/three.js/assets/380281/3439a679-8bf5-4599-b54e-76895e7c4847)

**Comment by LeviPesin** [comment]
I guess we should either fix it by removing the 's' or remove this code altogether and just use the simple `document.createElement( 'canvas' )`.
