### ISSUE TITLE
Scene Graph Changed Event

### ISSUE THREAD

**Issue by AdamEisfeld** [mrdoob/three.js#27563]
## Description

It would be useful to be able to observe when a given object has been added to or removed from the scene graph.

I have created a subclass of Object3D, and for my purposes I need to be able to detect whenever one of these subclasses gets added to a Scene so that I can add that object to a separate list of objects to be mutated each render loop (as opposed to searching through the entire scene graph each render loop for all objects of my class, which would be slow).

For example's sake, lets say I have created a SpinningObject3D class which inherits from Object3D, and I want to spin all of these instances in the scene on their y axis 1 degree each render loop. This is a simplified example.

I could create a separate array in my program, maybe called spinners, and just add the object to this list any time I knowingly add it to the scene, but it would be a much cleaner API (especially if I was making a plugin for ThreeJS for these spinners) if I could just attach a listener to the Scene object and listen for any time a SpinnerObject3D instance is added / removed (either to the scene directly, or as the child of another object already in the scene).

Eg (pseudo):

```ts

const scene = new Scene(...)
const spinners: Record<string, SpinnerObject3D> = {}

scene.addEventListener('graphUpdated', (event) => {

	const { action: 'added' | 'removed', scene: Scene, object: Object3D } = event;

	// Recursively get a list of any SpinnerObject3Ds in the added/removed object
	const modifiedSpinners = getSpinnersFrom(object); // Pseudo-code

	for (let s = 0; s < modifiedSpinners.length; s += 1) {
		const spinner = modifiedSpinner[s];
		switch (action) {
			case 'added': {
				spinners[object.uuid] = spinner;
				break;
			}
			case 'removed': {
				delete spinners[object.uuid];
				break;
			}
		}   
	}

})

```

This allows a list to be updated as the scene is modified throughout the lifetime of the app, without forcing users of my "spinner library" to remember to call some special "addSpinner(spinner)" function, and without requiring the entire scene graph to be iterated each render loop to extract the objects in question.

### Update Object3D

1. Add a "childAdded" / "childRemoved" event to Object3D.
2. In Object3D, after firing the existing "added" event, get the parent and fire "childAdded", passing the added child.
3. Do the same for "removed", add a "childRemoved" event fired on the parent the child was removed from.

### Opt-In Capabilities

With these 2 added events, developers can opt-in to getting the functionality I described in their projects, by:

1. Subclassing Scene
2. Adding "graphUpdated" event to the subclass
3. Overriding the add() function, configuring the childAdded event on each node being added to the scene (recursively) to dispatch the "graphUpdated" event on the Scene, passing "added" and the added child
4. Do the same for remove() / childRemoved

Now users can monitor when the scene graph changes in order to perform some custom logic on the inserted / removed object(s).

### Require Explicit Call

As mentioned, one method to get around this would just be to require developers to remember to call some function when adding objects of the type they care about. In my fictional spinner library, I could just create some SpinnerScene class (separate of Scene) and require users to ensure they add their spinners to this SpinnerScene along with the main Three Scene.

This is fine, its just not ideal for the API I am trying to expose, as I'd like to prevent adding additional work to users using my library, I'd like it "to just work".

### Iterate Entire Scene

Again, another option is just iterating the entire scene graph in the render loop, searching for the desired objects (any SpinnerObject3D instances). Not ideal when dealing with very large scenes where you don't want to be filtering through the entire scene repeatedly.

### Rebuild Graph Call

Another option would be to add some "rebuildGraph()" call to the spinner library, where it takes a Scene object and iterates over it to build a list of all SpinnerObject3Ds. Users would need to explicitly call this each time they want the system to rebuild it's list of spinners, which could be done less often than every frame.

This just goes back to wanting to create a clean, simple API for my library where I don't require users to ensure they call these things in the correct order / at the right time. 

### Will Render Tracking

For my specific use-case, I could achieve this by listening for the onBeforeRender callback on my Object3D subclass. In this callback I can check if the object has been "tracked" (some flag on the class) and if not, add it to a list.

This will work for my specific needs, but it doesn't solve the general problem, requires the functionality you're going after to be purely visual-based (it is in my case, maybe not for others), and doesn't really solve the problem of knowing when the object no longer needs to be tracked (via being removed from the scene).

## Additional context

In reality I am making a plugin for ThreeJS that simplifies aligning HTML content to the WebGL renderer (similar to CSS3DRenderer, but more powerful, optimized, and a slightly better API in my opinion).

My library requires users to use HTMLObject3D instances for the HTML elements they want to embed in the WebGL renderer.

My library needs to track all of these HTMLObject3D instances so that it can update the transforms of the corresponding HTML elements tied to them each render loop.

Currently, I use a separate HTMLScene class for storing these objects, requiring users to add their HTMLObject3Ds to the main ThreeJS Scene as well as the HTMLScene. I'd like to move towards just subclassing Scene and having it auto-detect when new HTMLObject3Ds are added to the scene in order to track them.

This isn't as simple as "are there any HTMLObject3Ds being added in my add() call?", as it also needs to detect the cases where a user adds some regular Object3D to the scene and then later on adds an HTMLObject3D to that Object3D (unbeknownst to the Scene).

**Comment by gkjohnson** [comment]
This is addressed in #16934

**Comment by AdamEisfeld** [comment]
@gkjohnson thank you, I hadn't seen that PR. That definitely does what I am describing.

**Comment by AdamEisfeld** [comment]
Closing as the discussion can continue in the PR.

**Comment by AdamEisfeld** [comment]
For anyone wanting a temporary solution until a PR is hopefully merged, you can swizzle the logic in by overriding Object3D's dispatchEvent function.

SceneGraphSwizzle.ts:
```ts
import * as THREE from 'three';

export class SceneGraphUpdatedEvent extends Event {

	/**
	 * The type of update that occurred. Either 'added' or 'removed'.
	 */
	public readonly update_type: 'added' | 'removed';

	/**
	 * The object that was added to or removed from the scene.
	 */
	public readonly object: THREE.Object3D;
	
	/**
	 * The uuid of the scene that was updated.
	 */
	public readonly scene_uuid: string;

	constructor(options: { update_type: 'added' | 'removed', object: THREE.Object3D, scene_uuid: string }) {
		super('SceneGraphUpdatedEvent');
		this.update_type = options.update_type;
		this.object = options.object;
		this.scene_uuid = options.scene_uuid;
	}

}

export function useGetRootScene(object: THREE.Object3D): THREE.Scene | undefined {
	let root: THREE.Object3D | undefined = object
	while (root.parent) {
		root = root.parent
	}
	if (root instanceof THREE.Scene) {
		return root
	}
	return undefined
};

export function useSceneGraphSwizzle() {

	console.log('Swizzling');

	// Store a reference to the original dispatchEvent method on Object3D so that we can call it later.
	const original_dispatch_event = THREE.Object3D.prototype.dispatchEvent;

	// Override the dispatchEvent method on Object3D so that we can dispatch our own events when objects are added or removed from the scene graph.
	THREE.Object3D.prototype.dispatchEvent = function(event: THREE.Event) {

		// Attempt to find the root scene of the modified object, using the new lastParent property (since Object3D nulls out the parent before dispatching
		// the removed event)
		const scene = useGetRootScene((this as any).lastParent as THREE.Object3D || (this as any).parent as THREE.Object3D || (this as any));
		if (!scene) {
			original_dispatch_event.call(this, event);
			return;
		}

		// Handle the added / removed events
		switch (event.type) {
			case 'added': {

				// Store the lastParent so we can use it in the removal event later
				(this as any).lastParent = this.parent;

				// Dispatch our custom event
				const graph_event = new SceneGraphUpdatedEvent({
					update_type: 'added',
					object: this,
					scene_uuid: scene.uuid,
				});
				document.dispatchEvent(graph_event);

				break;
			}
			case 'removed': {

				// Clear the lastParent since it is no longer needed (we just need it for finding the root scene)
				(this as any).lastParent = undefined

				// Dispatch our custom event
				const graph_event = new SceneGraphUpdatedEvent({
					update_type: 'removed',
					object: this,
					scene_uuid: scene.uuid,
				});
				document.dispatchEvent(graph_event);

				break;
			}
			default: {
				break;
			}
		}

		// Call the original dispatchEvent method
		original_dispatch_event.call(this, event)
	}

};
```

Then, import it somewhere in your app before modifying a scene's graph, eg:

```ts

import { useSceneGraphSwizzle } from './SceneGraphSwizzle';

useSceneGraphSwizzle();

const scene = new THREE.Scene();

...

```

For the purposes of monitoring if a specific Object3D subclass has been added to or removed from the Scene, something like this would work:

```ts
document.addEventListener('SceneGraphUpdatedEvent', (event: Event) => {

	if (!(event instanceof SceneGraphUpdatedEvent)) {
		return;
	}

	// Assuming you have a reference to someScene which is a Scene you want to monitor for changes
	if (event.scene_uuid !== someScene.uuid) {
		return;
	}

	const getDescendantSpinnerObjects = (object: THREE.Object3D): SpinnerObject3D[] => {
		const desc_spinner_objects: SpinnerObject3D[] = []
		object.traverse((object: THREE.Object3D) => {
			if (object instanceof SpinnerObject3D) {
				desc_spinner_objects.push(object)
			}
		})
		return desc_spinner_objects
	};

	const spinner_objects = getDescendantSpinnerObjects(event.object);

	switch (event.update_type) {
		case 'added': {
			// Handle the addition of spinner_objects
			break;
		}
		case 'removed': {
			// Handle the removal of spinner_objects
			break;
		}
		default:
			break;
	}

});
```
