### ISSUE TITLE
rotate a cube using cubeB.rotateX(1) 40 times and then cubeB.rotateX(-1) 40 times can not turn to initial rotation

### ISSUE THREAD

**Issue by o0olele** [mrdoob/three.js#27573]
### Description

as mention in the title, rotate a cube using cubeB.rotateX(1); cubeB.rotateY(0.1) 40 times and then cubeB.rotateX(-1); cubeB.rotateX(-0.1) 40 times, the rotation is not same as the initial rotation.

### Reproduction steps

1. create a cube.
2. cubeB.rotateX(1); cubeB.rotateY(0.1) 40 times
3. cubeB.rotateX(-1); cubeB.rotateX(-0.1) 40 times

### Code

```js
console.log(cubeB.quaternion.x, cubeB.quaternion.y, cubeB.quaternion.z, cubeB.quaternion.w)
for (var i=0;i<40;i++) {
    cubeB.rotateX(1);
    cubeB.rotateY(0.1);
}
console.log(cubeB.quaternion.x, cubeB.quaternion.y, cubeB.quaternion.z, cubeB.quaternion.w)
for (var i=0;i<40;i++) {
    cubeB.rotateX(-1);
    cubeB.rotateY(-0.1);
}
console.log(cubeB.quaternion.x, cubeB.quaternion.y, cubeB.quaternion.z, cubeB.quaternion.w)
// 0 0 0 1
// 0.9412402975994745 0.08621830095858869 0.047101272483778274 0.32313244480411074
// 0.008121983373078196 -0.08866723145989072 0.030439898662135825 0.9955629402608236
```

### Live example

* [jsfiddle-dev](https://jsfiddle.net/zjywbv9h/)

### Screenshots

![屏幕截图 2024-01-17 004337](https://github.com/mrdoob/three.js/assets/43069191/b8cbd1c4-73b0-4528-92b3-8b050c0b53a7)

### Version

dev

**Comment by gkjohnson** [comment]
Please ask at the forum if you need help understanding rotations:

https://discourse.threejs.org/
