### ISSUE TITLE
Raycaster not detecting objects when using object.layers.set(1) and camera.enable(1)

### ISSUE THREAD

**Issue by wangchao0724** [mrdoob/three.js#27583]
### Description

When I use `object.layers.set(1)` and `camera.enable(1)`,  Raycaster cannot recognize the object

In this example, only red can be recognized

https://stackblitz.com/edit/web-platform-34jep3?file=index.html

### Reproduction steps

1. `camera.enable(1)`
2. `object.layers.set(1)`
3. `raycaster.intersectObjects(scene.children, true)` is empty array

**Comment by Mugen87** [comment]
`Raycaster` also supports layers. Just enable layer 1 on the raycaster and the objects will be detected again.

Documentation: https://threejs.org/docs/index.html#api/en/core/Raycaster.layers

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.
