### ISSUE TITLE
can i use external WebGLBuffer as attribute buffer when I use InstancedBufferGeometry ? 

### ISSUE THREAD

**Issue by anapupa** [mrdoob/three.js#27598]
### Description

I want to use native WebGL transform feedback to calculate a small MLP and pass the result(WebGLBuffer) as instance vertex attribute.  But I did not find something like  InstancedGLBufferAttribute or GLInstancedBufferAttribute...

### Solution

explain how it works or how it could be happen

### Alternatives

not sure

**Comment by gkjohnson** [comment]
Please ask questions at the forum:

https://discourse.threejs.org/
