### ISSUE TITLE
skinned mesh lost webgl1 support

### ISSUE THREAD

**Issue by iefreer** [mrdoob/three.js#27607]
### Description

textureSize & texelFetch are webgl2 new features, not supported in webgl1, the changes done in skinning vertex shader broke webgl1 support, for example, on iOS14 devices, error reported as below:

_HREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Program Info Log: 
VERTEX

ERROR: 0:287: 'textureSize' : no matching overloaded function found_

### Reproduction steps

on iOS14 device, launch a glb with bone animation.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

0.160.0

### Device

Mobile

### Browser

Safari

### OS

iOS

**Comment by Mugen87** [comment]
Yes, we aware of that and won't fall back anymore. Keep in mind that WebGL 1 support will be entirely stopped in March with `r163`. 

So if you need to support older devices, you have to keep using an older version of `three.js`.

**Comment by iefreer** [comment]
> Yes, we aware of that and won't fall back anymore. Keep in mind that WebGL 1 support will be entirely stopped in March with `r163`.
> 
> So if you need to support older devices, you have to keep using an older version of `three.js`.

that's fine, thanks for quick reply.
