### ISSUE TITLE
【TransformControls】Unable to select after setting the layer

### ISSUE THREAD

**Issue by wangchao0724** [mrdoob/three.js#27624]
### Description

When I set a layer for TransformControls, I couldn't select it

```
const transformControl = new TransformControls(camera, renderer.domElement);
transformControl.traverse((node) => {
  node.layers.set(1);
})
```

I found that the internal pointer event_ Raycaster still uses the default layer, so it cannot be selected; I think_ Raycaster should use the same layer as camera

![image](https://github.com/mrdoob/three.js/assets/155077270/85b9d7d5-3d26-4497-9a69-9dcceb0e1419)

### Version

r160

**Comment by Mugen87** [comment]
Layer configuration for raycasters should be independent of camera layers for flexibility reasons. That's why `TransformControls.getRaycaster()` is available. It returns the internal instance of `Raycaster` so you can configure it as you like on app level.
