### ISSUE TITLE
Only render the last viewport normally when setting scene.background

### ISSUE THREAD

**Issue by SADYX** [mrdoob/three.js#27636]
### Description

In [this example](https://github.com/mrdoob/three.js/blob/master/examples/webgl_camera.html) ,renderer only render the last viewport normally when setting `scene.background = new THREE.Color( 0xff0000 ); // any color` 

### Reproduction steps

1. clone [this example](https://github.com/mrdoob/three.js/blob/master/examples/webgl_camera.html)
2. set `scene.background = new THREE.Color( 0xff0000 ); // any color` 

### Code

Check jsfiddle.

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/sadyx/om7csq4x/10/)

### Version

r160

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
When you assign something to `Scene.background` (e.g. a color or texture), it is rendered each time `WebGLRenderer.render()` is called. An assigned background color will force a clear which will not respect viewport settings. You need to use scissor testing as well to make this work:

https://jsfiddle.net/mapu90gt/

Alternatively, you manage the clear color on app level like so:

https://jsfiddle.net/mapu90gt/2/

But that means you do not use `Scene.background` at all.

**Comment by Mugen87** [comment]
@WestLangley Should we update the example and add scissor testing? I doubt most user understand the details between viewport and scissor area. 

Related question at stackoverflow: https://stackoverflow.com/questions/11544608/how-to-clear-a-rectangle-area-in-webgl

**Comment by WestLangley** [comment]
@Mugen87 Good idea. I'll file a PR.
