### ISSUE TITLE
Google Chrome Autoplay policy changes affecting the usage of AudioListener and AudioLoader class

### ISSUE THREAD

**Issue by vedantkingh** [mrdoob/three.js#27637]
### Description

Google Chrome Autoplay policy changes affect the usage of AudioListener and AudioLoader classes as they use the AudioContext class internally, and according to the policy change, if initiate AudioContext without a user gesture(i.e. as soon as the website loads), it should initiate in a suspended state automatically, and should be resumed while usage, which is not the case when it comes to AudioListener, because it initiates the AudioContext in active state, so my solution was to add a separate 'welcome' screen to get user gesture. But please make it so that the AudioListener and AudioLoader can be initiated in a suspended state in case of the absence of user gesture.
Although the web app will run in the development environment, it will not build in case we want to push it into production.
Here are some references:
My use case: https://www.vedantsingh.me/
Autoplay policy: https://developer.chrome.com/blog/autoplay/
Solution for AudioContext being used directly: https://stackoverflow.com/questions/55026293/google-chrome-javascript-issue-in-getting-user-audio-the-audiocontext-was-not

I tried initiating it and then suspending it immediately, but that did not work, as it cannot be initiated in active state without user gesture in the first place.

Solutions I think would work:
1. Initiating the AudioContext internally in a suspended state every time and resume just before using (requires documentation changes).
2. Initiatiation of AudioContext in suspended state only and only in case of absence of user gesture.

If no one is willing to step up for this issue, please reach out to me, I will start working on this.

### Reproduction steps

1. Use the AudioListener class in the first page as soon as the website loads.
2. It will run in development environment but it will not build.
3. In the development environment please check for _The AudioContext was not allowed to start_ message in the console to confirm that the AudioListener is being restricted and will probably be a problem while building the app.

### Code

```js
const listener = new THREE.AudioListener();
```

### Live example

* [That's the reason there is a start 'Play' button here in this official example as well.](https://threejs.org/examples/#webaudio_sandbox)

### Version

0.160.1

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
I'm not sure I understand what we should change in the code.

We have demonstrated in the examples that apps should only instantiate audio classes _after_ a user interaction (e.g. a button press). Then everything should work as expected.

This issue is understood for a long time and there are no plans to handle this issue differently directly the library (since I don't think this is possible).

**Comment by vedantkingh** [comment]
@Mugen87 Have there been no attempts to solve this? And are the high-level solutions I mentioned already attempted to implement? If yes, could you please share the issue? 
And shouldn't it be possible to do it, as the `AudioContext` class, when implemented directly, is initiated in the suspended state in case the page has not received a user gesture? It needs to call the `resume()` function before its usage.
And as we are using the `AudioContext` internally, can't we follow the same principle? Perhaps, a high-level solution might be, that whenever the AudioListener is called in the first page, the user has to resume it first, just like when using `AudioContext` directly:

```js
const listener = new THREE.AudioListener();
listener.getAudioContext().resume()
```

Or something like this. Do you understand what I am trying to say?
I have my purpose fulfilled, I am just trying to help out the future developers using three.js.

**Comment by Mugen87** [comment]
> Have there been no attempts to solve this

The solution is to create audio classes after a user interaction. Not before.

It is the responsibility of the app to make this sure. Requesting a user interaction can look different from app to app so `three.js` can handle this part. If you end up with suspended/paused audio context, it is the responsibility of the app to fix this. 

You can request the global audio context via `THREE.AudioContext.getContext()` and then do with it whatever you want.

**Comment by vedantkingh** [comment]
Okay thanks, did not that the `AudioContext` was global.
