### ISSUE TITLE
GTAO/SSAO alter transparent materials appearence

### ISSUE THREAD

**Issue by LR17** [mrdoob/three.js#27638]
### Description

Using GTAO or SSAO seems to modify the appeareance of transparent materials. When an occlusion pass is active, transparent materials become "brighter". I noticed both passes have the same custom blending settings

### Reproduction steps

1. Add GTAOPass or SSAOPass to EffectComposer

### Code

-

### Live example

-

### Screenshots

<img width="501" alt="Screenshot 2024-01-29 085006" src="https://github.com/mrdoob/three.js/assets/14975024/0a4cbaa0-8221-49f6-9f0e-66f5c56dc884">
<img width="501" alt="Screenshot 2024-01-29 085029" src="https://github.com/mrdoob/three.js/assets/14975024/d470bb83-d1b7-4edc-a538-2637fa7669b3">

### Version

160

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Duplicate of #23019 (and #27184

**Comment by LR17** [comment]
I don't know if this a duplicate of the above issues (Maybe I did not understand properly the comments). I currently have three passes:
1.  RenderPass
2. SSAOPass
3. OutputPass

Just enabling/disabling SSAOPass triggers/removes the issue. Using just RenderPass + OuputPass the ouput is correct

**Comment by Mugen87** [comment]
In this case, we need a closer investigation.

Do you mind demonstrating the issue with a live example?

**Comment by LR17** [comment]
Sorry, you were right, I'm closing the issue
