### ISSUE TITLE
WebGLBackend: Support for Accessing External Elements in StorageBuffer

### ISSUE THREAD

**Issue by RenaudRohlinger** [mrdoob/three.js#27642]
### Description

In the WebGL Backend there is currently no way to create compute programs that need accessing to elements other than themselves. A good example that is impacted by this limitation is `webgpu_compute_audio.html`. 

After conducting research on WebGL, I successfully implemented a method for transferring the contents of the transform feedback array buffer to a texture through a GPU-GPU operation, utilizing Pixel Buffer Object. This approach allows maintaining the dual-buffer transform feedback structure while providing access to other elements via texelFetch, similar to a GPGPU setup (but better in most cases).

For more information and a demonstration, please visit this article:
[https://webgl-compute-pbo.renaudrohlinger.com/](https://webgl-compute-pbo.renaudrohlinger.com/)

The following is an example of what is typically generated by the ArrayElementNode class when fetching an element from a storage buffer in the WebGPU Backend:
```js
// New boolean to indicate the intention to access other elements in the WebGLBackend:
const storagebuffer = storage( new StorageBufferAttribute( waveBuffer, 1, accessOtherElements ), 'float', waveBuffer.length );

// Later in TSL:
const storagebuffer.element( index );
// Code generated by the builder for this node in the WebGPU Backend -->
nodeVarying1[ uint( ( ( float( uint( gl_InstanceID ) ) - ( ( nodeUniform3 * 48000.0 ) * 6.0 ) ) * nodeUniform2 ) ) ]
```

My proposal for the WebGL Backend involves a new `accessOtherElements` parameter. If this parameter is set, the backend would generate a texture associated with the array buffer, using the syntax `${nodeVarying1}_texture`.

Consequently, in the ArrayElementNode class, we could implement a new texelFetch syntax:
```js
const storagebuffer.element( index );
// code generated by the builder for this node in the WebGL Backend -->
texelFetch(nodeVarying1_texture, uvec2(uint( ( ( float( uint( gl_InstanceID ) ) - ( ( nodeUniform3 * 48000.0 ) * 6.0 ) ) * nodeUniform2 ) ), 0)
```

### Alternative solution
Go full `GPGPU` and drop the dual-buffer transform-feedback implementation.

----
I will work on this in the next couple of days and I wanted your opinion on this before adding these changes to threejs /cc @sunag @aardgoose

**Comment by aardgoose** [comment]
I like the mechanism. 

Instead of a user visible flag have you considered detecting a non 'InstanceIndex' index to the element[] in arrayElementNode and setting a flag when a compute shader is built to keep things as simple as possible for the user?

Would the limitations of texture dimensions be significant if buffer swapping is removed?
Obviously there will be some overhead from the PBO copying even though it avoids GPU-CPU.

**Comment by sunag** [comment]
Do you think about transfer data to textures (PBO) only when using this data, such as when calling the `renderer.getArrayBufferAsync()` function for example?

**Comment by LeviPesin** [comment]
> My proposal for the WebGL Backend involves a new accessOtherElements parameter. If this parameter is set, the backend would generate a texture associated with the array buffer, using the syntax ${nodeVarying1}_texture.

I don't think a flag is needed -- I agree with @aardgoose, this feels like something GLSLNodeBuilder could do automatically.

**Comment by RenaudRohlinger** [comment]
Fixed with https://github.com/mrdoob/three.js/pull/27661
