### ISSUE TITLE
Raytracing material & lighting

### ISSUE THREAD

**Issue by Hudsxn** [mrdoob/three.js#27645]
### Description

A good addition to threejs would be a raytracing material and raytracing light, For devices that don't have raytracing capabilities, a property like fallbackMaterial could be used to take all the heavy lifting out for developers. I know different vendors often have their own version of raytracing too, so this could be a polymorphic object with multiple implementations for different GPU vendors. 

### Solution

Create an abstract raytracing material, in which there's a child descendant class based on GPU vendor, This could even have automatic selection based on the hardware:
```javascript
let gl = canvas.getContext("webgl");
let raytracingExtension = gl.getExtension("EXT_rasterization_raytracing");
if (raytracingExtension) {
    // Ray tracing is supported
    console.log("Ray tracing is supported!");
} else {
    // Ray tracing is not supported
    console.log("Ray tracing is not supported.");
}
``` 
The same for lighting too, create a base Raytracing light and have child descendants also based off of vendors.

### Alternatives

N/A

### Additional context

This could then be imported & used via:

```javascript
import { RayTracingMaterial, RayTracingLight } from 'three';
```

**Comment by CodyJasonBennett** [comment]
There are no hardware extensions for raytracing on web, nor will there be with WebGPU https://github.com/gpuweb/gpuweb/issues/535.

Even so, this is complex enough to warrant a library or team of its own to maintain like https://github.com/gkjohnson/three-gpu-pathtracer.

**Comment by mrdoob** [comment]
The hardware is definitely not there...
Maybe in 10 years?
