### ISSUE TITLE
move addons out of the examples folder

### ISSUE THREAD

**Issue by mikaelcolboc** [mrdoob/three.js#27654]
### Description

It's confusing and seems wrong that the addons (jsm) live inside the "examples" directory. It makes deploying or compiling an app tricky as "examples" folder should be skipped/ignored.
See this [issue](https://github.com/electron-userland/electron-builder/issues/7964) that occurs in electron-builder.

### Solution

move the jsm folder to the build folder.

### Alternatives

have a "dist" folder.

**Comment by Mugen87** [comment]
`addons` is just an alias to the physical `examples/jsm` directory. We have added the alias as a compromise since renaming or moving the files will break at lot of paths. Sorry, but it's not realistic to make the suggested change.
