### ISSUE TITLE
WebGLRenderer: Setting Scissor and Viewport is imprecise due to rounding issues

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#27655]
### Description

For [three-gpu-pathtracer](https://github.com/gkjohnson/three-gpu-pathtracer) I've been rendering the image in tiles for the sake of performance but found that it's not possible to set the exact pixels that the renderer rasterize due to the multiplication with the pixel ration and subsequent [rounding that occurs](https://github.com/mrdoob/three.js/blob/1b35d645db0070803e48fb5ba302478c99ac99d7/src/renderers/WebGLRenderer.js#L516) in the setScissor and setViewport functions.

This means that when rendering tiles side by side the rounding can result in pixels being missed when rendering tiles. For three-gpu-pathtracer I've switched to using the WebGLRenderTarget's .scissor property since it affords setting the sciossor via exact pixel values.

### Reproduction steps

1. Try to render in a tiled fashion with a combination of pixel ratio and dimensions that do not cleanly divide
2. See that the tiles miss rows and columns of pixels due to rounding error

### Code

See live example.

### Live example

Demo with selected pixel ratio and dimensions that result in the skipped pixels.

https://jsfiddle.net/cfhwous9/

### Screenshots

<div><img width="250" alt="image" src="https://github.com/mrdoob/three.js/assets/734200/e39f5b7e-67ab-4747-a12b-6f0f5dd3ca4f"/></div>

<div><img width="250" alt="image" src="https://github.com/mrdoob/three.js/assets/734200/ffd485e6-ca16-4665-ba1f-6d82d60e33aa"></div>

https://twitter.com/mrdoob/status/1752366500621746617

### Version

r160

### Device

Desktop, Mobile

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows, MacOS, Android

**Comment by Mugen87** [comment]
According to the WebGL/OpenGL spec the values passed to `gl.viewport()` and `gl.scissor()` are supposed to be `GLint`. To be spec compliant, the engine should round values. So maybe the usage of `floor()` is incorrect? Would using `round()` solve the issue?

**Comment by gkjohnson** [comment]
Yeah perhaps using "round" with a clamp to the max width of the canvas would work best.
