### ISSUE TITLE
3DM Exporter: Possible new addition

### ISSUE THREAD

**Issue by GitHubDragonFly** [mrdoob/three.js#27660]
### Description

This is just a suggestion to include 3DM (Rhino) Exporter.

I could submit the current custom [3DM Exporter](https://github.com/GitHubDragonFly/GitHubDragonFly.github.io/blob/main/viewers/static/jsm/exporters/3DMExporter.js) that, in my opinion, does a decent job exporting textureless meshes and points. The object geometry has to be of the THREE.BufferGeometry type.

Anyone interested can possibly test it on my main [webpage](https://githubdragonfly.github.io/) since most of my 3D Viewers include it - just remember that textures are not supported currently.

### Solution

There is no 3DM Exporter available, to my knowledge.

### Alternatives

Leave everything as it is.

### Additional context

Rhino js library might need some improvements in order to add additional features.

**Comment by Mugen87** [comment]
I vote to develop the exporter in a separate repository and then demonstrate it with an external example.

https://threejs.org/examples/?q=external

**Comment by GitHubDragonFly** [comment]
@Mugen87 that makes it a bit more complex than I expected.

Just to keep things simple, we can leave everything as it is.

This topic itself is informative enough for anyone who might be looking for 3DM Exporter for three.js.
They can always use the one from my repository and hopefully improve it.
