### ISSUE TITLE
After the InstancedMesh instance changes its position once, why can’t the ray hit it again?

### ISSUE THREAD

**Issue by Sea-DH1** [mrdoob/three.js#27667]
### Description

InstancedMesh, if after modifying the matrix of the instance once, it is not selected again, is there something wrong with my usage?

### Reproduction steps

1. Click Box to modify the matrix. After multiple ray interactions, the interaction can no longer continue.
2. When the number of instances is less than 3, the same problem will occur if you click a few more times.
3.

### Code

```js
// code goes here
```

### Live example

[demo](https://jsfiddle.net/seadd/xp7cd2n8/34/)
The above is the demo address.

### Version

r161

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Similar when you translate vertices of geometries, you have to recompute bounding volumes. Try it with:
```
instancedMesh.computeBoundingSphere();
instancedMesh.computeBoundingBox();
```
Updated demo: https://jsfiddle.net/b5nm0sx2/

**Comment by Sea-DH1** [comment]
Thanks for your reply, it can be achieved
