### ISSUE TITLE
render error after WKWebView crash

### ISSUE THREAD

**Issue by MrQinYQ** [mrdoob/three.js#27663]
### Description

system： IOS，15.X 16.X 17.X this problem will occur
i use ktx2loader and uastc.
.ktx2 file rendering effect is 0xff00ff
.jpg file rendering effect is 0x000000
<img width="146" alt="KIM20240202-577633" src="https://github.com/mrdoob/three.js/assets/16348159/922cca9b-0b44-41d1-b392-e57ef17975f6">
I readed three.js code, not find the clue.
The rendering effect is occur after WKWebView crash and reload the HTML
Please help me.

### Reproduction steps

1.open my page
2.open other html page
3.WKWebView crash and my page reload
4.back my page find the problem

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

0.157.2

**Comment by MrQinYQ** [comment]
https://registry.khronos.org/OpenGL/extensions/KHR/KHR_texture_compression_astc_hdr.txt
The color is errorvalue? How do I find this implementation？
<img width="643" alt="KIM20240202-049181" src="https://github.com/mrdoob/three.js/assets/16348159/4ccd407e-b04c-43a3-bccf-aa449ae5f015">

**Comment by MrQinYQ** [comment]
How to catch the render error? How to avoid the render error?

**Comment by Mugen87** [comment]
Please let you help at the forum first: https://discourse.threejs.org/

You might doing something wrong in your texture setup.
