### ISSUE TITLE
Rendering into RGIntegerFormat textures doesn't work

### ISSUE THREAD

**Issue by Aloalo** [mrdoob/three.js#27686]
### Description

When creating a `WebGLRenderTarget` with `RGIntegerFormat` a WebGL error occurs: `WebGL: INVALID_VALUE: texImage2D: invalid internalformat` or (`GL_INVALID_OPERATION: Fragment shader output type does not match the bound framebuffer attachment type.`). Managed to fix the issue by adding the follwing code to [this function](https://github.com/mrdoob/three.js/blob/c0764e9c0407cfffabd0debf5f8b4759cb099a68/src/renderers/webgl/WebGLTextures.js#L135):
```
if ( glFormat === _gl.RG_INTEGER ) {

	if ( glType === _gl.UNSIGNED_BYTE ) internalFormat = _gl.RG8UI;
	if ( glType === _gl.UNSIGNED_SHORT ) internalFormat = _gl.RG16UI;
	if ( glType === _gl.UNSIGNED_INT ) internalFormat = _gl.RG32UI;
	if ( glType === _gl.BYTE ) internalFormat = _gl.RG8I;
	if ( glType === _gl.SHORT ) internalFormat = _gl.RG16I;
	if ( glType === _gl.INT ) internalFormat = _gl.RG32I;

}
```

Not sure if this is the only place this is needed?

### Reproduction steps

1. Create a `WebGLRenderTarget` with `RGIntegerFormat` and `RG8UI` internal format.
2. Render into it.

### Code

[jsfiddle](https://jsfiddle.net/hp7c3nab/37/)

### Live example

[jsfiddle](https://jsfiddle.net/hp7c3nab/37/)

### Version

r160

**Comment by Mugen87** [comment]
Would you mind filing a PR with your fix? The addition looks correct. `getInternalFormat()` is the only place where something is missing for supporting `RGIntegerFormat`.

BTW: In your fiddle, you are not creating the instance of `WebGLCubeRenderTarget` correctly. The ctor has only two parameters, not three. Besides, `position` shader attributes are not of type `vec4` but `vec3`.

**Comment by Aloalo** [comment]
Ok, thanks, I'll create a PR.

Fixed the `WebGLCubeRenderTarget` construction in the fiddle for posterity: https://jsfiddle.net/h3e4zncb/1/
The `position` attribute is `vec4`, I'm using a RawShaderMaterial. Even if the underlying buffer data is `vec3`, WebGL will automatically set the 4th component to `1.0`. 

From https://registry.khronos.org/OpenGL/specs/es/3.0/es_spec_3.0.pdf:

> Unspecified y and z components are implicitly set to 0.0 for floating-point array types and 0 for integer array types.
Unspecified w components are implicitly set to 1.0 for floating-point array types
and 1 for integer array types.
