### ISSUE TITLE
WebGPURenderer: VideoTexture produces multiple warnings in the console

### ISSUE THREAD

**Issue by supermoos** [mrdoob/three.js#27690]
### Description

https://threejs.org/examples/?q=webgpu%20vide#webgpu_materials_video

If you open the console you'll see multiple warnings/errors logged.

```
entries[3] is not an ExternalTexture when the layout contains an ExternalTexture entry.
 - While validating [BindGroupDescriptor] against [BindGroupLayout]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).

webgpu_materials_video.html:1 [Invalid BindGroup] is invalid.
 - While encoding [RenderPassEncoder].SetBindGroup(0, [BindGroup], 0, ...).

webgpu_materials_video.html:1 [Invalid CommandBuffer from CommandEncoder "renderContext_0"] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer from CommandEncoder "renderContext_0"]])
```

### Reproduction steps

1. Open the demo link
2. Open the console in Chrome Devtools
3. See the warnings.

### Code

Check demo link.

### Live example

Check demo link.

### Screenshots

<img width="2552" alt="Screenshot 2024-02-06 at 10 13 59" src="https://github.com/mrdoob/three.js/assets/2298345/1ffb575a-f905-47ee-81c8-9b5db8e354a4">

### Version

r161

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
Fixed via #28894.
