### ISSUE TITLE
Add the same warning in the doc for object3D.applyMatrix4 than for Matrix4.decompose

### ISSUE THREAD

**Issue by jo-chemla** [mrdoob/three.js#27713]
### Description

I've lost a few neurons trying to overcome an issue I've had which involved applying matrices to Object3D (rather than editing the objects position/quaternion/scale), and was seeing precision issues. It appeared after digging through that these were due to me using Object3D.applyMatrix4 which under-the-hood relies on Matrix4.decompose, and my objects had a node-tree with parents with non uniform scale. 

### Solution

Update the doc with the same warning note on object3D.applyMatrix4 than already exists on Matrix4.decompose

### Alternatives

Simple PR upcoming

### Additional context

Add warning on Object3D.applyMatrix4 based on Matrix4.decompose for potentially non-decomposable matrices
Root of the issue described [here](https://github.com/mrdoob/three.js/issues/3845)

Note already added in the docs for Matrix4.decompose following [this issue thread and PR](https://github.com/mrdoob/three.js/issues/20435)

Note: is the same than for Matrix4.decompose: 
Not all matrices are decomposable in this way. For example, if an object has a non-uniformly scaled parent, then the object's world matrix may not be decomposable, and this method may not be appropriate.

**Comment by Mugen87** [comment]
> I would say the matrix transformation guide is the ideal place for documenting non-decomposable matrices. Do you mind updating your PR and remove the modifications to the Object3D page?

In the meanwhile, I have removed the changes to `Object3D` and then merged the PR.

**Comment by jo-chemla** [comment]
Thanks for bringing these updates - sorry was going to do it today. Do you think it would be useful to still link to that new `decompose warning` section of Matrix-transformations.html on `Object3D.applyMatrix4`? No lengthy text since the complete explanation is described in Matrix-Transformation, just something like 
```
Note: In case of any issue, see [page:Matrix-transformations.Object and world matrices] note on non-decomposable matrices.
```
