### ISSUE TITLE
Automatic frustum culling on InstancedMesh does not update correctly

### ISSUE THREAD

**Issue by hamzakubba** [mrdoob/three.js#27733]
### Description

I've seen a handful of reports from folks using react-three-fiber regarding this issue, and have confirmed it happens with a [repro example on codesandbox](https://codesandbox.io/p/sandbox/floating-instanced-shoes-forked-m4mlh3).

If the positions of the instances change after being initially set, then it seems that the frustum culling 

### Reproduction steps

As you can see in the live example:
1. Create some instances and add them to the scene (including setting their matrices)
2. After rendering the instances, move them.
3. Now move the camera, and you will see that the frustum culling is wrong, causing the whole instanced mesh (i.e. all instances) to be culled when it shouldn't.

### Code

See live example or repro steps

### Live example

* [repro on codesandbox w/ r3f](https://codesandbox.io/p/sandbox/floating-instanced-shoes-forked-m4mlh3)
In this repro:
1. Scene renders with boxes at initial position, and red reference box in the distance
2. After 1 second, the boxes are moved to a new position
3. After another second, the camera animates to a new position. the boxes vanish during this transition when they shouldn't.

### Screenshots

![frustum-culling-bug](https://github.com/mrdoob/three.js/assets/518429/06e6950b-1ebb-4ca9-b510-0336f1cb6641)

### Version

r161

**Comment by gkjohnson** [comment]
Your code sandbox links aren't accessible. That aside if you move the the instances you need to regenerate the InstancedMesh bounding box. For more help please ask at the forum:

https://discourse.threejs.org/

**Comment by gkjohnson** [comment]
Asking why instances aren't rendering as expected in an app is a help question. If something is determined to be a bug in the forum then we can make an issue for it.

Regarding the documentation please feel free to make a PR make it more clear!
