### ISSUE TITLE
Camera rotation update stutters when mouse left click

### ISSUE THREAD

**Issue by deviant310** [mrdoob/three.js#27747]
### Description

The bug is bit weird. I don't know exactly whether the problem is in the framework.
The problem was found in yours example https://threejs.org/examples/?q=fp#games_fps
When I try to shoot by clicking left mouse with mouse moving I can see with the naked eye that camera is stuttering

Here are some scenarios below that I've reproduced:
1. mouse moving & mouse left click shooting – stuttering
2. mouse moving & any other mouse click shooting – OK
3. mouse moving & macbook trackpad click shooting – OK
4. macbook trackpad moving & mouse left click shooting – OK (!)

Mouse info:
Razer ProClick (not the worst mouse), bluetooth connect, 2.4 GHz connect, wired connect – doesn't matter.

### Reproduction steps

1. Go to https://threejs.org/examples/?q=fp#games_fps
2. Try moving mouse and shooting at the same time by mouse left click
3. Camera is stuttering

### Code

https://github.com/mrdoob/three.js/blob/master/examples/games_fps.html

### Live example

https://threejs.org/examples/?q=fp#games_fps

### Screenshots

https://drive.google.com/file/d/1b1J1nOAQEXqOQCswVoddEibmaEZh99P1/view?usp=sharing

### Version

0.161.2

### Device

Desktop

### Browser

Chrome, Safari

### OS

MacOS

**Comment by deviant310** [comment]
Yes, `unadjustedMovement: true` solves this issue.
Although this fix leads to different mouse sensitivity on different browsers (on safari camera moves at a snail's pace), but this is another story.
Thanks a lot!

**Comment by Mugen87** [comment]
> Although this fix leads to different mouse sensitivity on different browsers (on safari camera moves at a snail's pace), but this is another story.

Indeed! In my case the mouse gets way more sensitive.

In any event, it's good to hear that using `unadjustedMovement: true` solves the issue. That indicates a problem on OS level so I think we can close this issue.

If you have time, I might be good to report this issue at the Chromium bug tracker. It would be interesting to know if browsers could somehow detect and fix the issue.
