### ISSUE TITLE
WebGPURenderer, NodeMaterial: same variant between different Skeletons?

### ISSUE THREAD

**Issue by 0b5vr** [mrdoob/three.js#27741]
### Description

Currently, the NodeMaterial system creates different shader program variants between different skeletons, resulting in a long compilation time.
Is it possible to use the same program variant between skinned mesh with different skeletons?

Related: https://github.com/mrdoob/three.js/pull/27398

Context:

In three-vrm, we are using a function called `removeUnnecessaryJoints`, which generates skeletons for each mesh to prevent exceeding the maximum uniform count on mobile devices.

The function body:
https://github.com/pixiv/three-vrm/blob/v2.0.10/packages/three-vrm/src/VRMUtils/removeUnnecessaryJoints.ts

### Solution

Currently, we are dispatching variants by adding skeleton uuid to the cache key.

https://github.com/mrdoob/three.js/blob/841d2e791d3e8a2463322c5ca31b16956828b91c/examples/jsm/renderers/common/RenderObject.js#L136

it would be nice if we could put a bone count instead and make it work properly, for example.
Probably we have to modify how we upload bone matrices as a uniform array? since it's not working as is.

### Alternatives

Alternatively, I can change the `removeUnnecessaryJoints` to create less skeletons when there are many meshes but I'm yet to come up with a way.
I can align the bone count between skeletons by adding dummy bones at the tails of arrays.

### Additional context

I think this is pretty much the bare minimum to check the behavior.

https://glitch.com/edit/#!/denim-valley-echinodon

**Comment by sunag** [comment]
> it would be nice if we could put a bone count instead and make it work properly, for example.
Probably we have to modify how we upload bone matrices as a uniform array? since it's not working as is.

Sounds good define a bone count as part of cache key, I think that some modifications will be necessary in `SkinningNode` to this work properly, maybe manage `reference` nodes like we did in `MorphNode`, I will have to check that.

**Comment by 0b5vr** [comment]
I think this is pretty much the bare minimum to check the behavior.

https://glitch.com/edit/#!/denim-valley-echinodon
