### ISSUE TITLE
OrbitControls throws on pointerUp event

### ISSUE THREAD

**Issue by wnr** [mrdoob/three.js#27746]
### Description

* The OrbitControls continue to manipulate the camera if a click+drag is released outside of the OrbitControls' DOM element, as reported in issue https://github.com/mrdoob/three.js/issues/24566. 
* Releases prior to r161 it was possible to reset the state by clicking the canvas again to "release" the camera. With r161 clicking the canvas, in this state, instead throws an exception and does not reset the state. 
* The camera is forever stuck being manipulated by the pointer.

### Reproduction steps

1. Go to any three.js scene using OrbitControls, such as https://threejs.org/examples/?q=orbit#misc_controls_orbit
2. Click and drag starting in the scene and release the click with the cursor out of the scene (like the left examples panel)
3. Return the cursor to the scene without clicking and observe that the camera is still being controlled by the cursor movements.
4. Click the canvas. Notice how the camera is still being controlled by the cursor movements.

### Code

N/A

### Live example

https://threejs.org/examples/?q=orbit#misc_controls_orbit

### Screenshots

<img width="760" alt="Screenshot 2024-02-14 at 13 23 01" src="https://github.com/mrdoob/three.js/assets/719555/71d4412e-0a62-43e5-8d64-666a3de91f7b">

### Version

r161

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by wnr** [comment]
I think this issue should be treated separately as it is much easier to fix than https://github.com/mrdoob/three.js/issues/24566. I believe that reverting https://github.com/mrdoob/three.js/pull/27425/files would fix this particular issue, but of course it would be preferable to keep it while fixing this regression somehow.

I too use a magic mouse. I notice that it is really easy to reproduce like 75% of the times, but sometimes I can't reproduce it a few times in a row. Very strange. Does this video help?

![Kapture 2024-02-14 at 15 45 05](https://github.com/mrdoob/three.js/assets/719555/758d35dd-8cf3-4a17-b6b1-8e32cad3b518)

**Comment by sciecode** [comment]
Unable to reproduce on Windows - FF/Chrome, and Ubuntu - FF/Chrome.

**Comment by sciecode** [comment]
Although I can't reproduce, I can definitely say there's something inconsistent happening either with user agent or magic mouse hardware.

There are two things that shouldn't occur, judging from the reported error. The block that triggers the error is on `OnPointerUp`.

https://github.com/sciecode/three.js/blob/1b8412c700316e3ed0d3b5f5ab827287e3351bad/examples/jsm/controls/OrbitControls.js#L1065-L1071

- Specifically the case where one pointer is lifted and one pointer remains active. However, I'm unaware of anyway this would happen on a mouse interface. So, this is problematic already.

- Furthermore, the error implies the saved pointer-position, that is still in contact with the canvas, has `undefined` coordinates, which should also never happen.

I suspect this isn't an issue on our end, but would need more information of the events and pointerIds/positions to confirm.

**Comment by sciecode** [comment]
I was able to reproduce now, the issue can occur if both left/right buttons are pressed simultaneously. The controls becomes stuck as explained by this issue. I'll investigate ways to solve this behaviour, thanks for reporting.

**Comment by wnr** [comment]
> Can you make a test if Firefox and/or Safari shows the same behavior?

I tried both of them and I'm unable to get the controls stuck (the root issue) so I think this is a Chrome-only issue.
