### ISSUE TITLE
GLTFLoader -- TypeError: `this` is undefined -- thrown internally when attempting to call GLTFLoader.Load - Three.js R161

### ISSUE THREAD

**Issue by ifg-sam** [mrdoob/three.js#27750]
### Description

I am trying to use the GLTFLoader to load .glb files in my project.

In my attempts to do so, an internal `TypeError: this is undefined` is being thrown:

![image](https://github.com/mrdoob/three.js/assets/110469604/9d752421-2c26-437f-af43-e77911ec169d)

### Reproduction steps

1. Import the GLTFLoader from the `"three/examples/jsm/loaders/GLTFLoader"` directory
2. Create an instance of the GLTFLoader
3. Attempt to call GLTFLoader.load()

### Code

```ts
import { GLTF, GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

class MyClass {
    // a bunch of other class stuff that isn't important here...

    private _modelLoader: GLTFLoader = new GLTFLoader();

    private async _loadModel(modelPath: string, isPreloadAsset: boolean = false): Promise<GLTF> {
        try {
            return new Promise((resolve, reject) => {
                this._modelLoader.load(
                    modelPath,
                    (gltf: GLTF) => {
                        resolve(gltf);
                    },
                    (__progress) => {},
                    (error) => {
                        reject(error);
                    }
                );
            });
        } catch (e) {
            console.error("Caught error loading gltf/glb!");
            console.log(e);
            return Promise.reject(e);
        }
    }
}
```

### Live example

.

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/110469604/eb739df9-7ec2-4066-9353-91ad176f0373)

### Version

161

### Device

Desktop

### Browser

Firefox

### OS

MacOS

**Comment by mrdoob** [comment]
We need a live example. Closing until it's provided.

**Comment by ifg-sam** [comment]
Your live example template uses three js imported as a plain script file

Like any sane developer I am using a bundler

Creating a standalone live example with the parcel bundler will be an unreasonable # of hoops to jump through

I am happy to give you access to my actual repo where you can `npm install` and `npm start`

Unless your suspicion is that the bundler might be the cause, in which case... are the three js devs just asking people to use three via script tag and import map now?

**Comment by mrdoob** [comment]
Please, isolate the issue and provide a jsfiddle link that reproduces the bug if you want us to help.

We are not going to debug your project's code.

**Comment by donmccurdy** [comment]
@ifg-sam plenty of projects use GLTFLoader with a bundler, including Parcel -- if bundlers weren't supported, we'd have hundreds of bugs filed about it. As it is, yes, we do need a reasonably simple example to quickly reproduce the issue. Doesn't have to be a JSFiddle: a GitHub repo or a zip with tsconfig.json, package.json, any bundler config, plus the relevant code might be plenty, if it successfully reproduces the issue.

From your description, I'd say there's a fair chance this has something to do with JS transpilation... but it's rarely a good use of time for us to guess at the TypeScript, bundler, Babel, and any other config options you might be using. Please take the time to make it easy for us to help you.

**Comment by CodyJasonBennett** [comment]
You can use [`Loader#loadAsync`](https://threejs.org/docs/#api/en/loaders/Loader.loadAsync) with all loaders and re-use an instance to not risk de-scoping `this`.

```ts
import { type GLTF, GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';

const _modelLoader = new GLTFLoader();

class MyClass {
    private async _loadModel(modelPath: string, isPreloadAsset = false): Promise<GLTF> {
        return _modelLoader.loadAsync(modelPath);
    }
}
```

For further guidance, please see the [forum](https://discourse.threejs.org) and include a [live example](https://jsfiddle.net/g3atw6k5/) or repo, so people can quickly help you.
