### ISSUE TITLE
Using GLTFLoader to load models causes high memory usage, suspected of not releasing memory in time.

### ISSUE THREAD

**Issue by xingxiang1227** [mrdoob/three.js#27792]
### Description

1. High memory usage when loading models with GLTFLoader

2. Using the built-in editor and taking the example of "kira.glb" from "examples/models/gltf/", the memory usage after loading with GLTFLoader is 290,068 kb.

3. After using autosave, which involves converting the data to JSON and then reloading it from indexedDB, the final memory usage is only 73,512 kb.
 
4. It is suspected that the surge in memory usage is caused during the handling of textures.

### Reproduction steps

1. Using the built-in editor and taking the example of "kira.glb" from "examples/models/gltf/", the memory usage after loading with GLTFLoader is 290,068 kb.
![gltfloader](https://github.com/mrdoob/three.js/assets/20619652/4984c287-7a21-426c-b1e7-09be3ede0a15)

2. After using autosave, which involves converting the data to JSON and then reloading it from indexedDB, the final memory usage is only 73,512 kb.
![ObjectLoader](https://github.com/mrdoob/three.js/assets/20619652/092573b4-bd0c-4cae-8fee-2629292c92e5)

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r161

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by mrdoob** [comment]
The editor may be saving the textures as jpeg into indexedDB. Is that what you're trying to report?
And... Is 290,068 kb really high memory usage for you?

**Comment by donmccurdy** [comment]
Might be related to the Web Workers spawned while decoding Draco compression. I'm not sure if the editor keeps those workers around for reuse, or disposes them eventually.

This model also contains two 4K textures, with estimated GPU memory cost of 90 MB each. My confidence is low that Chrome's tab manager reports GPU memory accurately, but the numbers here do seem within reason.

**Comment by xingxiang1227** [comment]
> The editor may be saving the textures as jpeg into indexedDB. Is that what you're trying to report? And... Is 290,068 kb really high memory usage for you?

Hello, in my actual project, a 150MB model, when loaded through GLTFLoader, ultimately occupies 3GB of memory, whereas when stored through indexedDB and rendered again, it only occupies around 700MB. Is there room for optimization in memory management when using GLTFLoader for loading?

**Comment by xingxiang1227** [comment]
> After my testing, for models with many textures, the memory usage when using GLTFLoader for loading is much higher than that after conversion through indexedDB. Is there room for optimization in memory management when using GLTFLoader?

After my testing, for models with many textures, the memory usage when using GLTFLoader for loading is much higher than that after conversion through indexedDB. Is there room for optimization in memory management when using GLTFLoader?

**Comment by xingxiang1227** [comment]
In the GLTFLoader.js file, within the GLTFParser class, the textures are loaded using `this.textureLoader = new ImageBitmapLoader( this.options.manager )`, which results in a high memory footprint. After I replaced it with `this.textureLoader = new TextureLoader( this.options.manager )`, the memory usage became normal. The memory consumption of the former is about 6 times that of the latter. Is there a way to optimize the memory usage of ImageBitmapLoader?
![GLTFLoader-GLTFParser](https://github.com/mrdoob/three.js/assets/20619652/23b02912-db6c-40c3-83ba-361e42a60f9e)

**Comment by donmccurdy** [comment]
@xingxiang1227 high resolution images consume an enormous amount of memory. With TextureLoader, the compressed image is held in CPU memory, and the first time it's rendered, the WebGL API is blocked while decompressing and uploading it to the GPU. For a 4K texture that's 90 MB of memory.

The reason we use ImageBitmapLoader — when possible — is that it moves the decompression of the main thread, allowing us to block rendering for a shorter period of time. The memory cost on the GPU is the same. I'm unsure of the difference in CPU memory, or whether Chrome's Task Manager is able to measure both accurately.

Additionally, the Web Workers used to decode Draco-compressed data will need some unknown amount of CPU memory.

You can opt out of both in your own application – for example, using TextureLoader or (better yet) KTX2 compressed textures. See my blog post, [Choosing Texture Formats for WebGL and WebGPU](https://www.donmccurdy.com/2024/02/11/web-texture-formats/), for more on that. Or you can skip using Draco compression in favor of lighter-weight Meshopt compression or quantization.

These all have tradeoffs, among which CPU memory is just one, so I'm not sure there's much we can change about the Editor here. If you're having particular problems managing memory in your own application, please feel welcome to start a thread in https://discourse.threejs.org/ and we can probably help you optimize memory there.

**Comment by ybf970928** [comment]
我也遇到了, 同一份glb文件, 我在threejs editor里导入内存占用才300多M, 但是在使用react-three-fiber项目当中导入内存直接1.5个G....

**Comment by ybf970928** [comment]
我也遇到了, 同一份glb文件, 我在threejs editor里导入内存占用才300多M, 但是在使用react-three-fiber项目当中导入内存直接1.5个G....有啥解决方法
