### ISSUE TITLE
CurveModifier: Shadow position will not be updated.

### ISSUE THREAD

**Issue by sheepdragon** [mrdoob/three.js#27794]
### Description

After adding shadows in CurveModifier, the position of the shadows will not be updated.

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/hoaxs05f/1/)
* [jsfiddle-dev](https://jsfiddle.net/zLaqewmb/1/)

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/4659052/823a5196-8de7-4f6c-a717-cb379180aa3d)

### Version

r160

### Device

Desktop

### Browser

Edge

### OS

Linux

**Comment by Mugen87** [comment]
`CurveModifier` modifies the vertex shader of built-in materials for its effect. Without applying the same modifications to the depth/distance materials (the materials that are used for shadow map rendering), shadows won't work.

**Comment by WestLangley** [comment]
We no longer have any examples using `.customDepthMaterial` or `.customDistanceMaterial`.

**Comment by sheepdragon** [comment]
I understand
