### ISSUE TITLE
Object center not correct after rotate

### ISSUE THREAD

**Issue by xdekasx** [mrdoob/three.js#27793]
### Description

We are experiencing an issue after rotating an object.

When the object is loaded, then the center of the object is correctly placed but when we rotate it, then this center is not at center anymore.

Is necessary to update something else after rotating the object to update his center? Scaling or translating the object works fine.

Thanks in advance,

### Reproduction steps

1. Load the object.
2. Rotate the object on Z axis.
3. Look the control position, is not at the real center.

### Code

```js
function init() {
   ...
  
  const stlLoad = new STLLoader();
	stlLoad.load('/three-js-161-dev/file.stl',
	function ( geometry ) {
		const material = new THREE.MeshLambertMaterial( { color: 0x4D9F99 } );
                const mesh_added = new THREE.Mesh( geometry, material );		          

		scene.add( mesh_added );
			 
		control.attach( mesh_added );
                scene.add( control );

	        mesh_added.geometry.center();

	        var box = new THREE.Box3().setFromObject( mesh_added, true );
	        var size = new THREE.Vector3();

                var boxHelper = new THREE.Box3Helper(box, '#000000');
		scene.add(boxHelper);
	}
  );

  ...

}
```

### Live example

* [jsfiddle](https://jsfiddle.net/dc_3d/78qnvefa/15/)

That's the file which we get the issue, among others.
[bug-file.zip](https://github.com/mrdoob/three.js/files/14359612/bug-file.zip)

### Screenshots

Original load 
![original](https://github.com/mrdoob/three.js/assets/10883527/f36e26c1-552a-46f0-9eb4-e96e3ad507be)

After rotate
![rotate_error](https://github.com/mrdoob/three.js/assets/10883527/4fe29c5f-5171-45b0-ac44-4f52c174b0ff)

### Version

r161

**Comment by Mugen87** [comment]
I've tested your code and file locally but I can see an erroneous situation. Can you please describe in more detail the expected and actual result?

**Comment by xdekasx** [comment]
Thanks for your fast response.

In our project, we have a tool to place the object on the "floor" which simply does the following.
``` js
let size = new THREE.Vector3();
let box = new THREE.Box3().setFromObject(selected_obj, true);
selected_obj.position.z = box.getSize(size).z * 0.5;
// (In our project axis are changed, the default UP is Z axis ( THREE.Object3D.DefaultUp.set(0, 0, 1) ) )
```

This feature seems to be not accurate after a rotation is made but I don't know if I'm doing something wrong or I'm lefting some code after rotate.

In the following video I show you the real case. After doing the rotation, if I call the "floor" action, then is not correctly placed.


https://github.com/mrdoob/three.js/assets/10883527/9ca65363-e69d-4f77-babe-5623b3dc9a31

**Comment by Mugen87** [comment]
Thanks for sharing the video. That made it more clear!

Translating an object does not change the extend of its bounding box. Rotating does however. So it is not surprising that you get a different bounding box after the rotation and consequently a different size which is incompatible with the way how you calculate the new position.

Sorry, but this not a bug so we don't provide any more feedback here. It's best if you ask at the [forum](https://discourse.threejs.org/) or stackoverflow for help.
