### ISSUE TITLE
Progressive Lightmaps example is broken

### ISSUE THREAD

**Issue by TobiasNoell** [mrdoob/three.js#27809]
### Description

The official progressive lightmaps examples is broken, shows the scene completely black and outputs an error in the console

### Reproduction steps

1. Open https://threejs.org/examples/?q=progr#webgl_shadowmap_progressive
2. Observe black scene
3. Open console

### Code

```js
three.module.js:20327 THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Material Name: 
Material Type: MeshPhongMaterial

Program Info Log: Vertex shader is not compiled.
```

### Live example

* [Example page](https://threejs.org/examples/?q=progr#webgl_shadowmap_progressive)

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/124624771/1ed50463-3840-488a-877f-4431de0a4ed0)
![image](https://github.com/mrdoob/three.js/assets/124624771/2cdb8bdf-449e-4f84-95d7-57460999f577)

### Version

r161

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
This has already been fixed on dev:

https://rawcdn.githack.com/mrdoob/three.js/dev/examples/webgl_shadowmap_progressive.html
