### ISSUE TITLE
VOXLoader.js cannot load MagicaVoxel vox files

### ISSUE THREAD

**Issue by qark** [mrdoob/three.js#27803]
### Description

MagicVoxel saves vox files with version 200 instead of 150 which causes VOXLoader.js to reject such a file due to a check in code.

See https://github.com/ephtracy/ephtracy.github.io/issues/264 for addtional details

See bellow for proposed fix in VOXLoader.js

### Reproduction steps

1. Create VOX (or use pre-created file) in MagicaVoxel
2. Import using VOXLoader.js
3. Filed does not load with "Not a valid VOX file" error printed to console.

### Code

```js
		if ( id !== 542658390 || ( version !== 150 && version !== 200 ) ) {
```

### Live example

N/A

### Version

161

**Comment by Mugen87** [comment]
Can you please share an example file from MagicaVoxel with the version 200?

**Comment by qark** [comment]
Sure, I've attached small cube (3x3x3) that's part of windows distribution of MagicaVoxel.

I tested it that it fails to load.

Ovewriting the version byte with 150 produces file that loads (see file 3x3x3-150.vox).

[3x3x3.zip](https://github.com/mrdoob/three.js/files/14375506/3x3x3.zip)

**Comment by Mugen87** [comment]
It seems both assets have the 150 version. I can load both of them in the three.js editor without issues.

**Comment by Mugen87** [comment]
I can confirm that just adding support for the `200` version number in `VOXLoader` solves the issue.

However, I suppose a higher version means bits in the file format specification have changed. Is there some way to check this?

**Comment by Mugen87** [comment]
Without more information I don't think it's appropriate to support the `200` version in the loader.

The spec maintainer has explain why there is a `200` version and what changes are introduced compared to `150`.

**Comment by qark** [comment]
I agree. Thanks for looking into this!

**Comment by mrdoob** [comment]
Seems like there's a extension to the spec:
https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox-extension.txt

**Comment by mrdoob** [comment]
I've enabled support for version 200.
Lets us know if there are any files that do not load correctly 🙏

**Comment by mrdoob** [comment]
I asked ephtracy about this on twitter and he responded the same day:
https://x.com/ephtracy/status/1997239886164681127
