### ISSUE TITLE
PSD textures are not supported, creating placeholder texture when loading an FBX file

### ISSUE THREAD

**Issue by papiguy** [mrdoob/three.js#27814]
### Description

I am trying to load a FBX file using 3JS. When I load the Samba_Dancing.fbx sample, everything works well. However, when I switch it to some other models which I have downloaded from SketchFab I see the following error

PSD textures are not supported, creating placeholder texture. I have seen some other folks report this issue on stackoverlfow but not sure how to resolve this issue.

### Reproduction steps

Simply try to load a fbx files with embedded textures in threejs 

### Code

```js
const loader = new FBXLoader();
    loader.load('/models/Fighter_Jet04.fbx', (object) => {
      scene.add(object);
});
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

161

### Browser

Chrome

### OS

Windows, MacOS, Linux

**Comment by Mugen87** [comment]
I suppose PSD in this context is the native file format of Adobe Photoshop.

If so, there is no loader for loading these kind of textures. Given that this file saves Adobe Photoshop projects, I don't think it makes sense to support. It's like adding support for loading `blend` files from Blender. These formats are not intended for asset delivery and thus expensive to load and parse.

**Comment by mrdoob** [comment]
There seem to be a couple of PSD parsers in js:

https://github.com/webtoon/psd
https://github.com/meltingice/psd.js

But I'm not sure it's worth it to do a new PSDLoader...
