### ISSUE TITLE
BatchMesh’s maxVertexCount and maxIndexCount, can’t you customize the values yourself?

### ISSUE THREAD

**Issue by Sea-DH1** [mrdoob/three.js#27827]
### Description

BatchMesh’s maxVertexCount and maxIndexCount, can’t you customize the values yourself? If 180000000 is set, an error Array buffer allocation failed will be reported. Is there an upper limit to this value?

[demo](https://jsfiddle.net/seadd/60r3upag/17/)
This is the demo link. 180000000 has been set in it and an error has been reported.

### Solution

Because I have a need to load a large number of the same materials with different geometries, I thought of using BatchedMesh.

But when I use the following code to set the vertices and indexes, the error Array buffer allocate failed will also be reported.

const geometryCount = count;
const maxVertexCount = allGeometryPosCount;
const maxIndexCount = allGeometryIndexCount;

### Alternatives

BatchedMesh, can't maxVertexCount and maxIndexCount be modified through attributes?

**Comment by donmccurdy** [comment]
cc https://discourse.threejs.org/t/batchmeshs-maxvertexcount-and-maxindexcount-cant-you-customize-the-values-yourself/61766

Allocating 180M vertices will cause errors. Upper limits are device-specific and depend on several factors, including how much data per vertex you're storing. A good rule of thumb would be to stay under <100,000 vertices if you can, or certainly not to render more vertices than your screen has pixels. I believe this is a help/support thread - let's continue the existing discussion on the forums if you have additional questions.
