### ISSUE TITLE
OrbitControls choppy zoom with RenderOnDemand

### ISSUE THREAD

**Issue by emkajeej** [mrdoob/three.js#27831]
### Description

When using renderOnDemand instead of an animation loop, OrbitControls' zoom function becomes choppier the closer you zoom on small geometries.
This is on a MacBook's touchpad. Possibly related to the recent change in OrbitControl's zoom speed modulation?

### Reproduction steps

1. Create a scene with a small box (0.01x0.01x0.01). Make sure the camera's near clipping and OrbitControls' minDistance supports this.
2. Use OrbitControls `change` event to render new frames
3. Zoom from far away to minDistance and notice the jumps between frames
4. Optional: when zoomed all the way in, try to zoom out slightly. Note how it seems unresponsive at first.

### Code

Created a CodePen: https://codepen.io/emkajeej/pen/QWPLWOG

renderOnDemand pattern is:

```
// RENDER ON DEMAND
let renderRequested = false;

controls.addEventListener("change", (ev) => {
  requestRender();
});

const requestRender = () => {
  if (!renderRequested) {
    renderRequested = true;
    requestAnimationFrame(render);
  }
};

const render = () => {
  renderRequested = false;
  controls.update();
  renderer.render(scene, camera);
};

render();
```

### Live example

* https://codepen.io/emkajeej/pen/QWPLWOG

### Version

r0.161

### Device

Desktop

### Browser

Chrome, Firefox, Safari, Edge

### OS

MacOS

**Comment by sciecode** [comment]
I'm not able to reproduce. 

I've tried making some changes to the way we respond to zoom-events on a custom branch. Any chance this solves the issue? https://jsfiddle.net/794nhc05/

**Comment by emkajeej** [comment]
Yes, using the updated version seems to fix it. 👍
