### ISSUE TITLE
VRMLLoader ignores transparency for IndexedLineSet Material

### ISSUE THREAD

**Issue by dxdc** [mrdoob/three.js#27838]
### Description

When using `VRMLLoader` to load VRML files that include `IndexedLineSet` geometries with specified transparency in the material, the transparency setting seems to be ignored. Specifically, even though the VRML file specifies a transparency attribute for the `Material`, this does not reflect in the material properties of the loaded `LineSegment` in threeJS. This results in line segments that are fully opaque, regardless of the intended transparency level.

### Reproduction steps

1. Create a VRML file with an `IndexedLineSet` that includes an appearance with a material specified for transparency, such as:

    ```vrml
    appearance Appearance {
        material Material {
            diffuseColor 1 0 0
            transparency 0.80
        }
    }
    geometry IndexedLineSet {
        # IndexedLineSet details omitted for brevity
    }
    ```

2. Load this VRML file into a threeJS scene using `VRMLLoader`.
3. Inspect the material properties of the resulting `LineSegment` object in threeJS.

### Code

Example VRML file, alternatively see Live example.

```vrml
#VRML V2.0 utf8
Transform {
	translation 0 0 0
	children[
      Shape {
          appearance Appearance {
              material Material {
                  diffuseColor 1 0 0
                  transparency 0.8
              }
          }
          geometry IndexedLineSet {
              coord Coordinate {
                  point [
                      0 0 0,   
                      1 0 0,   
                      1 1 0,   
                      0 1 0,   
                      0 0 1,   
                      1 0 1,   
                      1 1 1,   
                      0 1 1,   
                      0.5 0.5 0,   
                      1 0.5 0.5,   
                      0.5 1 0.5,   
                      0 0.5 0.5,   
                      0.5 0 0.5,   
                      0.5 0.5 1   
                  ]
              }
              coordIndex [
                  0, 1, -1, 1, 2, -1, 2, 3, -1, 3, 0, -1,
                  4, 5, -1, 5, 6, -1, 6, 7, -1, 7, 4, -1,
                  0, 4, -1, 1, 5, -1, 2, 6, -1, 3, 7, -1,
                  0, 2, -1, 1, 3, -1, 4, 6, -1, 5, 7, -1,
                  8, 13, -1, 9, 11, -1, 10, 12, -1
              ]
          }
      }
    ]
}
```

In the live example, uncomment the manual override lines to see how it should appear.

```js
    object.traverse(function(child) {
      if (child instanceof THREE.LineSegments) {
        var material = child.material;
        // material.transparent = true; // manual override
        // material.opacity = 0.2  // manual override

        console.log(`Opacity: ${material.opacity}`);
      }
    });
```

### Live example

* https://jsfiddle.net/znap5xku/21/

### Version

r161

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
Indeed this is a bug. The loader does not copy the opacity and transparent properties to lines or points materials. I'll file a PR with the fix.

**Comment by Mugen87** [comment]
>  diffuseColor 1 0 0

According to the [spec](http://gun.teipir.gr/VRML-amgem/spec/part1/nodesRef.html#IndexedLineSet), `diffuseColor` is not evaluate for lines and points. If you want your lines to be red, use `emissiveColor` instead.

> If the color field is NULL and there is a Material defined for the Appearance affecting this IndexedLineSet, then use the emissiveColor of the Material to draw the lines.
