### ISSUE TITLE
DRACOLoader: Use loader.setDRACOLoader(dracoLoader) to configure the decoding library and display 404

### ISSUE THREAD

**Issue by yuxiaoshuai** [mrdoob/three.js#27843]
### Description

I encountered a problem loading a compressed model, I compressed a glb format model file, the compressed model is still a glb format. When loading modelDraco.glb with the latest decoding library, the prompt is 404 for both draco_WASm_wraper.js and draco_decoder.wasm
![Snipaste_2024-02-29_11-06-40](https://github.com/mrdoob/three.js/assets/97014176/c436352e-be66-450d-992b-103fb3835730)

### Reproduction steps

not have

### Code

```js
// code goes here
```
1.import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
   import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js';
2.const loader = new GLTFLoader();
  const dracoLoader = new DRACOLoader();
3.loader.setDRACOLoader(dracoLoader);
4.loader.load('static/glbModels/wineryPlantDraco.glb', (gltf) => {
    const model = gltf.scene;
    Scene.add(model);
  }, undefined, (error) => {
    console.log(error);
  })

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)
no

### Version

^0.160.0

**Comment by gkjohnson** [comment]
Code for initializing GLTFLoader and DRACOLoader is available in the documentation and examples. If you need further help please ask as the three.js forums:

https://discourse.threejs.org/
