### ISSUE TITLE
Visual artifacts in rendering specific GLTF

### ISSUE THREAD

**Issue by dxdc** [mrdoob/three.js#27842]
### Description

When rendering a GLTF file (attached), unexpected visual artifacts appear in the form of distorted mesh patterns on the surfaces of the 3D model. The issue manifests as a series of sharp, triangular shapes that do not align with the intended smooth surface of the model. This phenomenon is particularly evident on the green and blue colored meshes, as observed in the attached screenshot.

This phenomenon is also quite readily apparent using the [glTF Viewer](https://gltf-viewer.donmccurdy.com/). Interestingly, if you toggle `wireframe` in display (for example), these distorted mesh patterns disappear and go back to rendering properly.

[molecule-06 (4).gltf.zip](https://github.com/mrdoob/three.js/files/14439752/molecule-06.4.gltf.zip)

### Reproduction steps

- Load the provided GLTF file into the Three.js environment (see live example).
- Render the model using the standard mesh and material configurations.
- Observe the surfaces of the model, particularly the areas where color transitions occur.

### Code

```js
// code goes here
```

### Live example

* https://jsfiddle.net/joa58Lq0/13/

### Screenshots

<img width="1013" alt="Screenshot 2024-02-28 at 2 19 25 PM" src="https://github.com/mrdoob/three.js/assets/7200365/5bda2a2f-a5cc-4883-b230-f907cd1f90cd">

### Version

r161

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by dxdc** [comment]
(e.g., after toggling the wireframe on/off)

<img width="791" alt="image" src="https://github.com/mrdoob/three.js/assets/7200365/410369af-d265-4bde-9221-99d87e261c34">

**Comment by dxdc** [comment]
@Mugen87 thanks for the quick follow up.

I just updated Chrome to 122.0.6261.94 and running Ventura 13.6.4. 

I don't see this issue on the live example I sent any longer, but I still *do* see it on the [glTF Viewer](https://gltf-viewer.donmccurdy.com/) in Chrome. Are you able to reproduce it there?

Interestingly, Firefox 123.0 does not have this issue nor does Safari 17.3.1.

**Comment by Mugen87** [comment]
> I don't see this issue on the live example I sent any longer, but I still do see it on the [glTF Viewer](https://gltf-viewer.donmccurdy.com/) in Chrome. Are you able to reproduce it there?

I can't reproduce the issue. This is a screenshot from the viewer:

<img width="1386" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/bd03625f-b191-4489-812a-4b2ffe979749">

This looks like a browser or device specific issue. Unfortunately, we don't support them here so ideally this is reported to 
 the respective browser vendors. 

However, investigating such issues is very hard so before your report it would be ideal if you do some additional tests on your side and test on different Apple devices. If there is only an issue on your device, I doubt you will see a fix on the browser side.
