### ISSUE TITLE
convexHull with flat shape

### ISSUE THREAD

**Issue by Code141** [mrdoob/three.js#27867]
### Description

Hi, I try to get a convexHull for a flat cloud points
With X and Y as random and Z as 0
but when i do, only 3vertices (sometime 4) are catched in the hull.
when I put Z as random too, the hull work perfectly.
I have played with `tolerance` without success.

I had to put this ugly hack to get what I want. 

Thanks.

### Reproduction steps

.

### Code

.

### Live example

.

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/15637884/80b7b830-7870-47f6-a965-ac5ddbd2599f)

### Version

162

### Device

Desktop

### Browser

Firefox

### OS

Linux

**Comment by Mugen87** [comment]
The underling algorithm is an implementation of QuickHull 3D which does not work with your input data.

Sorry, but this is not something that is going to be fixed. For a pure 2D data set, there are more efficient convex hull algorithms.
