### ISSUE TITLE
UnsignedIntType THREE.RedIntegerFormat dataTexture not working in wgslFn

### ISSUE THREAD

**Issue by Spiri0** [mrdoob/three.js#27879]
### Description

I think this is also just a minor problem. I have an unsignedIntType THREE.RedIntegerFormat dataTexture and i assign it to a wgslFn. I chose ```<u32>``` as the format and also tested ```<i32>```. I got the information from the webgpu shading language manual.

![Screenshot_20240307_095255_Chrome](https://github.com/mrdoob/three.js/assets/69024222/170bb68c-fbb1-46ba-94f2-6650884cc32e)

Unfortunately this doesn't work and warnings appear in the console. I created a codePen and attached a code snippet here. It just seems to be an internal type mismatch, but I'm just guessing.

### Reproduction steps

1. create an UnsignedIntType data texture
2. assign the data texture to a wgslFn
3. try to include the texture in the wgslFn with ```texture_2d<u32>``` or ```texture_2d<i32>```

### Code

```
const size = 8;
const dataArray = new Uint32Array(size ** 2).fill(255);
const dataTexture = new THREE.DataTexture(dataArray, size, size);
dataTexture.format = THREE.RedIntegerFormat;
dataTexture.type = THREE.UnsignedIntType;
dataTexture.wrapS = THREE.ClampToEdgeWrapping;
dataTexture.wrapT = THREE.ClampToEdgeWrapping;
dataTexture.minFilter = THREE.NearestFilter; 
dataTexture.magFilter = THREE.NearestFilter;
  

const wgslParams = {
  uv: uv(),
  dataTexture: dataTexture
}
  
const wgslColorShader = wgslFn(` 
  fn mainFunction(
    uv: vec2<f32>,
    dataTexture: texture_2d<u32>  //here is the issue
  ) -> vec4<f32> {
    
    var texCoord = vec2<f32>(uv.x * 8, uv.y * 8);
    //var texel = textureLoad(dataTexture, vec2<i32>(texCoord), 0).r;
    return vec4<f32>(1, 0, 0, 1);
  }
`);
  
const material = new MeshBasicNodeMaterial();
material.colorNode = wgslColorShader(wgslParams);
const geometry = new THREE.BoxGeometry();
let cube = new THREE.Mesh(geometry, material);
scene.add(cube);  

```

### Live example

https://codepen.io/Spiri0/pen/XWQmoLV?editors=0010

### Version

161

**Comment by sunag** [comment]
@Spiri0 Thanks for the material, it helps a lot as always. The solution is a little more complex, but I think I should finish it this week.
