### ISSUE TITLE
bloompass bug：flashing black block

### ISSUE THREAD

**Issue by wajjforever1314** [mrdoob/three.js#27878]
### Description

After use the bloompass, the shader and some models with transparent pass will frequently flash black blocks.
Example：
https://github.com/mrdoob/three.js/assets/28917209/c003d339-9b19-474e-9d07-486afb69996a

### Reproduction steps

1. use shader exmaple：webgl_shader.
2. change bloom example：webgl_postprocessing_unreal_bloom code, add mesh with ShaderMaterial

### Code

```js
                         const geometry = new THREE.CircleGeometry(.5, 32);

			uniforms = {
				time: { value: 2. }
			};

			const material = new THREE.ShaderMaterial({
				transparent: false,
				opacity: 0,
				uniforms: uniforms,
				vertexShader: document.getElementById('vertexShader').textContent,
				fragmentShader: document.getElementById('fragmentShader').textContent

			});

			const mesh = new THREE.Mesh(geometry, material);
			scene.add(mesh);


                        animate() {
                                  ...
                                  uniforms['time'].value = performance.now() / 1000
                        }
```

### Live example

https://github.com/mrdoob/three.js/assets/28917209/1c47eacb-22be-4e0d-8d14-263330e45c2b

### Screenshots

https://github.com/mrdoob/three.js/assets/28917209/b23ebc0e-bbf0-4761-89a3-87f9325a7119

### Version

"version": "0.160.0"

### Device

Desktop

### Browser

Chrome

### OS

Windows, MacOS

**Comment by wajjforever1314** [comment]
sometime, I use some other models with very much triangle face, and the material's tranparent is true. this problem will also appear

**Comment by Mugen87** [comment]
I can reproduce the issue on macOS with Chrome, Firefox and Safari.

Live example for testing: https://jsfiddle.net/2tahdqcs/1/

What I find super strange: If you do not animate the `time` uniform in the animation loop, the flickering is gone.

**Comment by Mugen87** [comment]
On a Pixel 4a there is no flashing with Chrome. So this seems to be a device specific issue. Potentially an issue in the browsers or drivers.

@wajjforever1314 Can you please type `chrome://gpu/` in your Chrome's address bar and share the content as a txt file in this issue?

**Comment by Mugen87** [comment]
@wajjforever1314 Can you still reproduce the issue with the following updated live example? https://jsfiddle.net/mpszaf03/

**Comment by Mugen87** [comment]
Made another test on a Window 10 system with a Nvidia 2070 RTX GPU. Unable to reproduce the issue.

So the only system I could reproduce so far was a macMini (M2 Pro) on macOS 14.3.1 with Chrome, Firefox and Safari.

**Comment by wajjforever1314** [comment]
> 在 Pixel 4a 上，Chrome 不会闪烁。所以这似乎是一个设备特定的问题。浏览器或 GPU 驱动程序可能存在问题。
> 
> @wajjforever1314您能否`chrome://gpu/`在本期中输入您的 Chrome 地址栏并将内容以 txt 文件形式分享？

Of course：
[about-gpu-2024-03-08T06-36-09-118Z.txt](https://github.com/mrdoob/three.js/files/14534228/about-gpu-2024-03-08T06-36-09-118Z.txt)

**Comment by wajjforever1314** [comment]
> 我可以在 macOS 上使用 Chrome、Firefox 和 Safari 重现该问题。
> 
> 用于测试的实时示例： https: [//jsfiddle.net/2tahdqcs/1/](https://jsfiddle.net/2tahdqcs/1/)
> 
> 我觉得超级奇怪的是：如果你不在`time`动画循环中为制服设置动画，闪烁就会消失。
> 
> 此外，用于自定义着色器材质的更简单的片段着色器也不会触发该问题： https: [//jsfiddle.net/mxoac23r/](https://jsfiddle.net/mxoac23r/)

It's not the reason for the implementation, it's the reason for the value of the uniform parameter type

> I can reproduce the issue on macOS with Chrome, Firefox and Safari.
> 
> Live example for testing: https://jsfiddle.net/2tahdqcs/1/
> 
> What I find super strange: If you do not animate the `time` uniform in the animation loop, the flickering is gone.
> 
> Besides, are more simple fragment shader for the custom shader material doesn't trigger the issue as well: https://jsfiddle.net/mxoac23r/

It's not the reason for the animation loop, it's the reason for the value of the uniform parameter, you can try:
uniforms = {
	time: { value: 2.0 }
};
and do not animate the time uniform in the animation loop, you will find that the problem is still there.

**Comment by Mugen87** [comment]
> So it's solved, but why, just delete part of the algorithm?

Yes. I've just deleted the term `tan( r * g + h ) *` from the effect. It's really strange that something like that fixes the issue.

And indeed, this is unrelated to the animation loop. Depending on the computations in the fragment shader, the black quads appear at different locations and in different numbers.

Here is a more strip-down version of the above fiddle that renders only a single frame but shows two overlaying black quads: https://jsfiddle.net/z3fu0bLv/

Depending on the `time` uniform, the glitch disappears (with a value of `1`) or appear at different location.

We can can not fix this issue on our side. I'll report it to the Chrome bug tracker.

**Comment by wajjforever1314** [comment]
> > So it's solved, but why, just delete part of the algorithm?
> 
> Yes. I've just deleted the term `tan( r * g + h ) *` from the effect. It's really strange that something like that fixes the issue.
> 
> > and do not animate the time uniform in the animation loop, you will find that the problem is still there.
> 
> Indeed, the issue is unrelated to the animation loop. Depending on the computations in the fragment shader, the black quads appear at different locations and in different numbers.
> 
> Here is a more strip-down version of the above fiddle that renders only a single frame but shows two overlaying black quads on my system: https://jsfiddle.net/rh3dqbgp/
> 
> Depending on the `time` uniform, the glitch disappears (with a value of `1`) or appears at different location.
> 
> We can can not fix this issue on our side. I'll report it to the Chrome bug tracker.

Okay, got it, thanks

**Comment by wajjforever1314** [comment]
> > > So it's solved, but why, just delete part of the algorithm?
> > 
> > 
> > Yes. I've just deleted the term `tan( r * g + h ) *` from the effect. It's really strange that something like that fixes the issue.
> > > and do not animate the time uniform in the animation loop, you will find that the problem is still there.
> > 
> > 
> > Indeed, the issue is unrelated to the animation loop. Depending on the computations in the fragment shader, the black quads appear at different locations and in different numbers.
> > Here is a more strip-down version of the above fiddle that renders only a single frame but shows two overlaying black quads on my system: https://jsfiddle.net/rh3dqbgp/
> > Depending on the `time` uniform, the glitch disappears (with a value of `1`) or appears at different location.
> > We can can not fix this issue on our side. I'll report it to the Chrome bug tracker.
> 
> Okay, got it, thanks

this version on my system is ok 
<img width="654" alt="image" src="https://github.com/mrdoob/three.js/assets/28917209/26bd7c05-41c7-45ce-adb7-b66671a6f0a6">

**Comment by Mugen87** [comment]
Not sure what's going on then.

In any event, I've filed a bug report at the Chromium bug tracker: https://issues.chromium.org/issues/328681369

What is also interesting, an iPad (8. generation) does not show the glitch as well so I assume this is related to M processors.

**Comment by wajjforever1314** [comment]
> 不知道接下来会发生什么。在我的系统上，我可以看到提到的工件。
> 
> 无论如何，我已经在 Chromium 错误跟踪器上提交了错误报告：https://issues.chromium.org/issues/328681369
> 
> 同样有趣的是，iPad（第 8 代）也没有显示该故障，因此我认为这与 M 处理器有关。

Haha, I can understand it this way for the time being. I will continue to track and explore this issue and update it to you simultaneously.

**Comment by wajjforever1314** [comment]
> Not sure what's going on then. On my system, I can see the mentioned artifacts.
> 
> In any event, I've filed a bug report at the Chromium bug tracker: https://issues.chromium.org/issues/328681369
> 
> What is also interesting, an iPad (8. generation) does not show the glitch as well so I assume this is related to M processors.

Haha, I can understand it this way for the time being. I will continue to track and explore this issue and update it to you simultaneously.

**Comment by gkjohnson** [comment]
There's no BloomPass bug here - this is just exposing a problem where NaN values are produced in the custom shader which are then propagated during the bloom effect. Different hardware handle NaN differently so it may or may show up depending on what machine you're trying to reproduce this on.

Adding this to the end of the custom shader produces red flashes instead of black ones:

```js
if ( any( isnan( gl_FragColor ) ) ) {

  gl_FragColor = vec4( 100000000, 0, 0, 1 );

}
```

On hardware that supports it you can usually create a NaN value with `0.0 / 0.0`.

**Comment by Mugen87** [comment]
Interesting! I'll redirect this finding to the Chromium bug tracker. It would be great if a WebGL implementation could ensure `NaN` are treated uniformly for devs users.

**Comment by gkjohnson** [comment]
I don't expect this to be fixable by browsers or three.js. Floating point operations are defined ambiguously in the spec - presumably by design so hardware manufacturers can optimize at their own discretion. See section 2.1.1 in the [OpenGL ES 3.0 specification](https://registry.khronos.org/OpenGL/specs/es/3.0/es_spec_3.0.pdf) that WebGL2 is defined on top of. Specifically:

> the representation of such floating-point numbers, and the details of how operations on them are performed, is not specified.
> ...
> The special values Inf and −Inf encode values with magnitudes too large to be represented; the special value NaN encodes “Not A Number” values resulting from undefined arithmetic operations such as 0 / 0. *Implementations are permitted, but not required, to support Inf s and NaN s in their floating-point computations.*

Perhaps this is different in more modern graphics APIs or WebGPU but I believe this is just the nature of graphics programming. It's something the developer has to be aware of when writing shaders.

**Comment by gkjohnson** [comment]
> But for some models, after turning on the bloom pass, still flashing, how to fix it?

Your custom shader needs to not perform calculations that result in NaN values or check for them and handle them gracefully.

**Comment by wajjforever1314** [comment]
> > But for some models, after turning on the bloom pass, still flashing, how to fix it?
> 
> Your custom shader needs to not perform calculations that result in NaN values or check for them and handle them gracefully.

thanks a lot

**Comment by zzzp9527** [comment]
@wajjforever1314  
When I was using `UnrealBloomPass`, I encountered the same issue.  

Sometimes, when my scene contains a large number of vertices, black blocks appear and disappear as I adjust the camera angle.  

My system specs:  
- CPU: AMD Ryzen 7 7730U  
- GPU: AMD Radeon Graphics  

Here is a screenshot of the issue:

<img width="1568" height="801" alt="Image" src="https://github.com/user-attachments/assets/272d8028-13f2-4958-9bcb-7aa1e7dd664b" />


In the end, I modified the `UnrealBloomPass`. The following change fixed the problem for me, and I hope it may help others who are experiencing the same issue.  

In the `_getSeparableBlurMaterial` function of `UnrealBloomPass`, I updated the blur shader as shown below:  

```glsl
varying vec2 vUv;
uniform sampler2D colorTexture;
uniform vec2 invSize;
uniform vec2 direction;
uniform float maxValue;
uniform float gaussianCoefficients[KERNEL_RADIUS];

void main() {
    float weightSum = gaussianCoefficients[0];
    vec3 diffuseSum = texture2D( colorTexture, vUv ).rgb * weightSum;
    for( int i = 1; i < KERNEL_RADIUS; i ++ ) {
    	float x = float(i);
    	float w = gaussianCoefficients[i];
    	vec2 uvOffset = direction * invSize * x;
    	vec3 sample1 = texture2D( colorTexture, vUv + uvOffset ).rgb;
    	vec3 sample2 = texture2D( colorTexture, vUv - uvOffset ).rgb;
    	diffuseSum += (sample1 + sample2) * w;
    	weightSum += 2.0 * w;
    }
    vec3 result = diffuseSum / weightSum;
    
    // Add this line to clamp 
    result = clamp(result, vec3(0.0), vec3(65504));
    
    gl_FragColor = vec4(result, 1.0);
```

In my case, the issue was caused by the bloom result becoming NaN. I am not sure if others are experiencing the same root cause, but this fix worked for me.
