### ISSUE TITLE
gl_FrontFacing not working in onBeforeCompile

### ISSUE THREAD

**Issue by Sea-DH1** [mrdoob/three.js#27892]
### Description

I am implementing a requirement for back color rendering, but in version 0.148.0 can still use gl_FrontFacing to determine whether it is the back. The latest version of three.js is no longer valid.

### Code

```js
const material = new MeshStandardMaterial({
  color: '#00ff00',
  clippingPlanes: [plane],
  transparent: true,
  side: DoubleSide
})

material.onBeforeCompile = (shader) => {
  shader.fragmentShader = shader.fragmentShader.replace(
    '#include <output_fragment>',

    `
    vec3 backfaceColor = vec3( 0.4,0.4,0.4);
    gl_FragColor =  (gl_FrontFacing)  ?  vec4( outgoingLight, diffuseColor.a ) : vec4( backfaceColor, opacity  );
    `
  )
}
```

### Live example
* [demo](https://jsfiddle.net/seadd/qape3bhk/8/)

### Version

r161

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by WestLangley** [comment]
See https://github.com/mrdoob/three.js/issues/25149#issuecomment-1353614434.

**Comment by Sea-DH1** [comment]
@WestLangley 
Doesn't work, I've tried setting alphaToCoverage and forceSinglePass and it still doesn't work

**Comment by gkjohnson** [comment]
There is no more `output_fragment` in the MeshStandardMaterial shader.

**Comment by Mugen87** [comment]
See #26278.

**Comment by Sea-DH1** [comment]
@Mugen87 @gkjohnson 
Thank you for your reply
