### ISSUE TITLE
A simple change in TextGeometry documentation.

### ISSUE THREAD

**Issue by kkphoenixgx** [mrdoob/three.js#27909]
### Description

FontLoader is not part of the core library anymore since r133. You need an additional import to use this loader in your application. This should be added in the first code block of the documentation, look at solution.

### Solution

`import { FontLoader } from "three/examples/jsm/loaders/FontLoader"`
`import { TextGeometry } from "three/examples/jsm/geometries/TextGeometry"`

### Alternatives

Consider checking documentation after releasing massive changes.

**Comment by Mugen87** [comment]
The [documentation page](https://threejs.org/docs/index.html#examples/en/geometries/TextGeometry) already shows how the import has to be done:
```js
import { TextGeometry } from 'three/addons/geometries/TextGeometry.js';
``` 
There is an equivalent import statement for `FontLoader` in its respective page.

Did you miss these?
