### ISSUE TITLE
Docs: Japanese version

### ISSUE THREAD

**Issue by kaehehehe** [mrdoob/three.js#27902]
### Description

Hi. I am a Japanese front-end developer. While studying, I found that the Three.js doc wasn’t translated into Japanese. Only the manual part has been translated and the rest has no Japanese translation. Do you mind if I translate the rest in Japanese step by step? If you allow me to do that, I’d like to translate it into Japanese for Japanese people. Thank you.

### Solution

For there is no japanese translation of Three.js doc, so I'd like to translate the doc into Japanese.

### Alternatives

Translate the doc into Japanese step by step.

**Comment by Mugen87** [comment]
Thanks for your willingness to help translating the documentation! 

Unfortunately, the current translation workflow is not ideal which is described in the following issue: #24984

Until we find a solution, there is no plan to add larger new sections to the documentation.
