### ISSUE TITLE
Shadowmaterial goes dark when pointlight.distance is set

### ISSUE THREAD

**Issue by sandersdevelopments** [mrdoob/three.js#27916]
### Description

Hello guys,

I might have found a bug related to pointlights and ShadowMaterials. Or maybe I am too dumb.

When I have a Plane with a ShadowMaterial which receives shadows it works when I add a PointLight with pointLight.distance = 0. 
However, when I change the distance to a non zero value, the whole Shadowplane goes dark except for the area that receives light. Why so? Shouldn't it be as transparent as before? 

I tried in the threejs editor aswell, with the same result.. It does feel very odd, so I had a feeling to open this issue

PS: sorry for not providing a fiddle, somehow I can't get the fiddle to work with shadowplanes at all...

### Reproduction steps

1. Add Ambient Light to scene
2. Add a big ground plane to the scene, rotate it by 90° and apply a ShadowMaterial to it
3. Add a PointLight to the scene (default value of pointLight.distance is 0 === infinity)
4. Place a cube above the ground plane to see a that the (until now) transparent shadowplane works
5. Change the pointLight.distance to a non-zero value ===> Whole Shadowplane goes dark

### Code

https://threejs.org/editor/

### Live example

https://threejs.org/editor/

### Screenshots

Before changing pointLight.distance ==> looks good, transparent shadowplane
![pointlightShadowBug1](https://github.com/mrdoob/three.js/assets/69421749/7b74e009-de0b-4800-abe0-719cd9c928aa)

After changing pointLight.distance ==> Why is the rest of the Shadowplane black / shadowed now?
![pointLightShadowBug2](https://github.com/mrdoob/three.js/assets/69421749/99dc8ecb-f086-46bd-830d-e52182133707)

Another example from my own code: 

1. with pointLight distance = 3: 
![image](https://github.com/mrdoob/three.js/assets/69421749/8542d3b8-9586-4766-abee-37e9525d4d04)

2. with pointlight.distance = 0: 

![image](https://github.com/mrdoob/three.js/assets/69421749/89461ae6-d6bf-45fc-900f-9e0bda9a6142)

### Version

r151

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
> Why is the rest of the Shadowplane black / shadowed now?

The black parts are outside of the point light's distance and are thus not illuminated. Check out the following exported application that you can drag'n'drop into the editor:  [app.json](https://github.com/mrdoob/three.js/files/14599667/app.json)

Initially, the point light has a distance of `5` which looks like so:

<img width="1133" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/83ded679-27ca-4a14-8caf-d637778b6d5a">

If you increase it to `10`, you get:

<img width="1040" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/75cf12a0-a43e-4d43-82db-72ec25509e93">

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.

**Comment by Mugen87** [comment]
`SpotLight` works as expected so let's consider this as a bug in `PointLight` (specifically `getPointShadow()`).
