### ISSUE TITLE
Custom Blending in WebGPU

### ISSUE THREAD

**Issue by MrsDarth** [mrdoob/three.js#27929]
### Description

Using custom blending in materials in webgpu will throw an error if the alpha blending is not specified.
![image](https://github.com/mrdoob/three.js/assets/78574223/86574d99-8e94-424e-9c52-aba60f10f3fc)
The cause is because the default values are set to GPUBlendFactor which is then passed to _getBlendFactor which is wrong
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/renderers/webgpu/utils/WebGPUPipelineUtils.js#L192

### Reproduction steps

1. Create a material with custom blending
2. Do not specify blend alpha

### Code

```js
const material = new MeshBasicNodeMaterial();
material.blending = CustomBlending;
material.blendEquation = AddEquation;
material.blendSrc = OneFactor;
material.blendDst = OneMinusSrcColorFactor;
```

### Live example

none

### Version

r162

**Comment by Mugen87** [comment]
Fixed via #28490.
