### ISSUE TITLE
In version # 162, when CSS3DRenderer mounts a click event in the DOM and rotates it to a certain angle, the event cannot respond

### ISSUE THREAD

**Issue by stevengogo** [mrdoob/three.js#27920]
### Description

This issue is not a problem in the old version. I compared the code of CSS3DRenderer.js and found that there is an additional deep perspective detection. Does this parameter cause any issues

### Reproduction steps

1.
2.
3.

### Code

```js
// #162
```
		const scaleByViewOffset = camera.view && camera.view.enabled ? camera.view.height / camera.view.fullHeight : 1;
			const cameraCSSMatrix = camera.isOrthographicCamera ?
				`scale( ${ scaleByViewOffset } )` + 'scale(' + fov + ')' + 'translate(' + epsilon( tx ) + 'px,' + epsilon( ty ) + 'px)' + getCameraCSSMatrix( camera.matrixWorldInverse ) :
				`scale( ${ scaleByViewOffset } )` + 'translateZ(' + fov + 'px)' + getCameraCSSMatrix( camera.matrixWorldInverse );
			const perspective = camera.isPerspectiveCamera ? 'perspective(' + fov + 'px) ' : '';

			const style = perspective + cameraCSSMatrix +
				'translate(' + _widthHalf + 'px,' + _heightHalf + 'px)';

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)
https://threejs.org/examples/?q=css3d#css3d_sprites

### Version

162

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
> This issue is not a problem in the old version.

On what version are you referring to?

You also have to describe in more detail what actually goes wrong. That is not clear from the title. I think it's best if you demonstrate the problem with a live example.

These information are required to investigate the issue. Until you have provided more information, the issue is closed.
