### ISSUE TITLE
EXR: lineOrder Decreasing

### ISSUE THREAD

**Issue by TodicaIonut** [mrdoob/three.js#27927]
### Description

THREE.EXRLoader: Skipped unknown header attribute type 'lineOrder'.

### Reproduction steps

1. lineOrder DecreasingY

### Code

```js
function parseLineOrder( dataView, offset ) {

			const lineOrders = [
				'INCREASING_Y'
				'DECREASING_Y'
				'RANDOM_Y'
			];
```

### Live example

* [gainmap-creator.monogrid.com](https://gainmap-creator.monogrid.com/)

### Screenshots

![Untitled11](https://github.com/mrdoob/three.js/assets/156521906/a6f5a763-14b4-4f56-a69e-b8f83e16ee51)

### Version

r163

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
`EXRLoader` currently supports only `INCREASING_Y`.

According to the [OpenEXR spec](https://openexr.com/en/latest/TechnicalIntroduction.html#header), `lineOrder` is defined like so:

> Specifies in what order the scan lines in the file are stored in the file (increasing Y, decreasing Y, or, for tiled images, also random Y).

@sciecode When I remember correctly the loader does in general not support tiles but do you think adding support for `DECREASING_Y` is feasible?

@TodicaIonut Do you mind sharing an EXR asset in this thread with `DECREASING_Y` line order in its header?

**Comment by sciecode** [comment]
> @sciecode When I remember correctly the loader does in general not support tiles but do you think adding support for DECREASING_Y is feasible?

That would be correct. Unfortunately tiled images would require a major rework of the entire module, as the initial port of loader was based on a version that did not consider tiled images a possibility. I would like to address it eventually, but I don't really see this happening so soon.

`DECREASING_Y` scan-line images would be much simpler to implement, as it only involves re-arranging the output image scan order. I'll see if I can add support for it in the next few days.

**Comment by TodicaIonut** [comment]
[EXR three.zip](https://github.com/mrdoob/three.js/files/14624912/EXR.three.zip)

`THREE.EXRLoader: Skipped unknown header attribute type 'envmap'.`
`THREE.EXRLoader: Skipped unknown header attribute type 'tiledesc'.`

![Untitled12](https://github.com/mrdoob/three.js/assets/156521906/9df90604-e5b9-4071-8138-67877ac9f999)
Error message:
`Error: THREE.EXRLoader: Provided file is currently unsupported.`

**Comment by Mugen87** [comment]
@TodicaIonut We are not planning to implement tiles support soon so it's best to focus on the `DECREASING_Y` change for now. If possible, please share an EXR file that triggers only the `DECREASING_Y` line order header warning.
