### ISSUE TITLE
Error EXR: `tiledimage`. warning: `envmap`, `tiledesc`

### ISSUE THREAD

**Issue by TodicaIonut** [mrdoob/three.js#27933]
### Description

warning:
THREE.EXRLoader: Skipped unknown header attribute type 'envmap'. [here](https://openexr.com/en/latest/OpenEXRFileLayout.html#predefined-attribute-types).
THREE.EXRLoader: Skipped unknown header attribute type 'tiledesc'.

Error message:
type: "tiledimage" [here](https://openexr.com/en/latest/OpenEXRFileLayout.html#multi-part-and-deep-data-header-attributes)
Error: THREE.EXRLoader: Provided file is currently unsupported.

### Reproduction steps

1. warning tiledesc
2. warning envmap
3. Error tiledimage

### Code

```js
type : "tiledimage"
```

### Live example

* [gainmap-creator.monogrid.com](https://gainmap-creator.monogrid.com/)

### Screenshots

chrome:
![Untitled15](https://github.com/mrdoob/three.js/assets/156521906/0bea7c03-d9d8-48d7-8408-774123b177e1)

Natron:
![Untitled16](https://github.com/mrdoob/three.js/assets/156521906/6cf2ce8e-7071-44f4-8a3c-eb5e6b68103f)

### Version

r163

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
I understand that one part of this issue is about adding support for tiled images to `EXRLoader`.

But the `envmap` seems unrelated to that. It seems this attribute is used to distinct between the equirectangular and cube map format. Since the loader does not support loading cube maps, it's probably better to make two issues. 

This issue should focus on tiled images, a second one on cube map support.

**Comment by TodicaIonut** [comment]
[OpenEXR spec](https://openexr.com/en/latest/TechnicalIntroduction.html#header), `lineOrder`, `tiles` is defined like so:

> pecifies in what order the scan lines in the file are stored in the file (increasing Y, decreasing Y, or, for tiled images, also random Y).

> This attribute is required only for tiled files. It specifies the size of the tiles, and the file’s level mode.


adding support for RANDOM_Y is feasible?
adding support for envmap is feasible?
adding support for tiledesc is feasible?
[tiles 256 random Y.zip](https://github.com/mrdoob/three.js/files/14736438/tiles.256.random.Y.zip)
[tiles 512 random Y.zip](https://github.com/mrdoob/three.js/files/14736439/tiles.512.random.Y.zip)
cc @sciecode 
![Untitled27](https://github.com/mrdoob/three.js/assets/156521906/69552016-1d0e-4c6e-a62e-304b8d3a678e)

**Comment by sciecode** [comment]
As mentioned already, we won't be adding support for tiled-images for now.
`tiledesc` and `lineOrder: RANDOM_Y` are all related with tiled-images, so - not feasible.

`envmap`, on the other hand, informs whether the image should be treated as `ENVMAP_LATLONG` Equirectangular, or `ENVMAP_CUBE` CubeMap. I can look into adding support for these. The only trouble is that the orientation conventions used for OpenEXR's envmaps differs from ours. So, the data transformation to conform with three'js will take some effort. WIll see if I can get it done by next weekend.
