### ISSUE TITLE
XRManager.setFramebufferScaleFactor() does not work with Vision Pro.

### ISSUE THREAD

**Issue by michaeldll** [mrdoob/three.js#27968]
### Description

Calling `WebXRManager.setFramebufferScaleFactor()` does not seem to work on our stack nor on the official examples. Also tested on an Apple Vision Pro

### Reproduction steps

1. Fork https://threejs.org/examples/?q=webxr#webxr_xr_cubes
2. Call `renderer.xr.setFramebufferScaleFactor(2);`
3. No visible change, and getting `renderer.xr.getSession().renderState.baseLayer.framebufferWidth` or `renderer.xr.getSession().renderState.baseLayer.framebufferHeight)` confirms that the framebuffer stays at the same dimensions.

### Code

```js
const renderer = new WebGLRenderer();

renderer.xr.enabled = true;

renderer.xr.setFramebufferScaleFactor(2);

console.log(renderer.xr.getSession().renderState.baseLayer.framebufferWidth, renderer.xr.getSession().renderState.baseLayer.framebufferHeight);
```

### Live example

Line 96:
https://codepen.io/sdafsdaf123/pen/dyLWMYy?editors=1111

### Version

r162

### Device

Apple Vision Pro

### Browser

Safari

### OS

VisionOS

**Comment by Mugen87** [comment]
It seems this is a Vision Pro exclusive issue. In this case, would you mind to report it directly to Apple via Feedback Assistant? https://github.com/mrdoob/three.js/issues/27912#issuecomment-1994871785

The engine directly passes `framebufferScaleFactor` to the `XRWebGLLayer` ctor as a part of the `XRWebGLLayerInit` dictionary. If VisionOS does ignore this setting, there is not much we can do on our side.

**Comment by michaeldll** [comment]
Thank you for the reply @Mugen87. I'll try reporting it to Apple.

**Comment by Mugen87** [comment]
I've tested on a Quest 2 today and framebuffer scaling seems to work as expected. So it's indeed best to redirect the problem to Apple.

**Comment by michaeldll** [comment]
Reported under the following ID: FB13707689

**Comment by yourdallaness** [comment]
@michaeldll did they ever patch it? i'd like to try it out
