### ISSUE TITLE
BatchedMesh: Exception with InterleavedBufferAttribute

### ISSUE THREAD

**Issue by marwie** [mrdoob/three.js#27973]
### Description

Batched mesh `addGeometry` throws exception for geometry with InterleavedBufferAttributes

### Reproduction steps

1. checkout https://github.com/needle-tools/three.js/tree/batched-mesh-interleaved-buffer
2. run webgl_mesh_batch example
3. observe error

The mesh was processed with gltf-transform and simplified
```
weld: primitive[0] of mesh "Sphere" → tolerance: 0.0001
weld: Tolerance thresholds: POSITION=0.0001, NORMAL=0.05, TANGENT=0.05, TEXCOORD_0=0.0001, TEXCOORD_1=0.0001
weld: 515 → 515 (+0.00%) vertices.
simplify: primitive[0] of mesh "Sphere" → ratio: 0.0625, error: 0.3, lockBorder: true
simplify: 515 → 92 (–82.14%) vertices, error: 0.1558.
sparse: Updated 0 accessors.
sparse: Complete.
```

### Code

see https://github.com/mrdoob/three.js/commit/54b78a08828f71dca2135c0c52645465aa5eac8c

[Sphere.zip](https://github.com/mrdoob/three.js/files/14728012/Sphere.zip)

### Live example

I have to submit this another time if necessary

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/5083203/4362a62b-40a0-4165-8223-683ea050722e)
![image](https://github.com/mrdoob/three.js/assets/5083203/8bcd21f5-56d2-4d47-864a-15d53a198abb)

![image](https://github.com/mrdoob/three.js/assets/5083203/dad20842-6914-425d-a902-3b4ad592cfa3)

### Version

162

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by marwie** [comment]
Here's a bit more info. Seems like when creating a new instance of the InterleavedBufferAttribute class the passed in `interleavedBuffer` field is actually the array data

**Comment by marwie** [comment]
A quick hack in _initializeGeometry works 
```js
if(srcAttribute instanceof InterleavedBufferAttribute){
					const interleavedBuffer = srcAttribute.data;
					const interleavedBufferAttribute = new InterleavedBufferAttribute( interleavedBuffer, itemSize, srcAttribute.offset, normalized );
					geometry.setAttribute( attributeName, interleavedBufferAttribute );
					continue;
				}
```

But the beautiful lowres sphere renders: https://github.com/needle-tools/three.js/commit/fa7e823a688a3eada21d071adbee07e2e63cfdac

![image](https://github.com/mrdoob/three.js/assets/5083203/d098a9b7-0307-497c-a767-7b38cacc20d2)

**Comment by gkjohnson** [comment]
These lines are the problematic ones:

> ```js
> const dstAttribute = new srcAttribute.constructor( dstArray, itemSize, normalized );
> dstAttribute.setUsage( srcAttribute.usage );
> ```

It looks like these lines were added in #25059 but I don't think there shouldn't be any reason to ensure the data is using an `InterleavedBufferAttribute` if the original geometry is. Likewise I don't believe there's any reason to retain the "usage" setting from the original attribute.

`new srcAttribute.constructor` should be able to be able to be changed to `new BufferAttribute` and the `setUsage` line can be removed, if you'd like to try that out and make a PR.

> Maybe someone can explain why the arrays are created with new array.constructor and suggest a better(?) solution

This is done to retain the original precision used for the attribute data and should not change.

**Comment by marwie** [comment]
Thanks - that seems to work. I'll do some more testing and then open a PR. Thank you

**Comment by marwie** [comment]
Is it expected that the batched mesh looks like this when enabling wireframe on the material?

![image](https://github.com/mrdoob/three.js/assets/5083203/2ada91ba-55cb-4624-8fa2-0b1af1d44c96)

**Comment by gkjohnson** [comment]
> Is it expected that the batched mesh looks like this when enabling wireframe on the material?

It's hard to say without know what the original geometry looks like. I'm not so familiar with how wireframes work internally but it's possible BatchedMesh needs special handling.
