### ISSUE TITLE
unpkg is slow when we're using NodeMaterials

### ISSUE THREAD

**Issue by 0b5vr** [mrdoob/three.js#28002]
### Description

unpkg CDN is very slow to load all the dependent modules when we're using NodeMaterials, sometimes responds 502 Bad Gateway.
We might want to consider switching the [installation doc](https://threejs.org/docs/#manual/en/introduction/Installation) to jsDelivr, or is there better solution?

I have compared four CDNs, and jsDelivr seems to be the best.

- unpkg: Described above, very slow. ~60s when cdn cache misses, 500ms when cdn cache hits. Sometimes responds 502 Bad Gateway
- jsDelivr: Best among them. 4s when cdn cache misses, 500ms when cdn cache hits
- cdnjs: Doesn't work, `/examples/jsm` are unable to fetch
- Skypack: Doesn't work, unable to server-side build since r157

### Reproduction steps

1. Use unpkg as a Three.js CDN
2. Write a code with NodeMaterial
3. Experience a chill coffee time while loading all the sources, or get mad at 502

### Code

See the demo below.

### Live example

Beware that server-side cache must be missed in order to reproduce the behavior described above.

- unpkg: https://glitch.com/edit/#!/three-r162-nodematerial-unpkg
- jsdelivr: https://glitch.com/edit/#!/three-r162-nodematerial-jsdelivr

### Version

r162

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by mrdoob** [comment]
Also reported on Twitter:
https://twitter.com/the_ross_man/status/1767188503136186447

I'd be up for switching 👍

**Comment by 0b5vr** [comment]
Opened a PR if you want to switch! : https://github.com/mrdoob/three.js/pull/28006
