### ISSUE TITLE
Texture Error loading in WebGPU  loader gltf compressed example

### ISSUE THREAD

**Issue by Thakisis** [mrdoob/three.js#28035]
### Description

Work fine in firefox but throw error in chrome/edge

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

![ErrorCompressed](https://github.com/mrdoob/three.js/assets/11295113/27dc2558-6523-4ff0-b8b7-5713bbee699c)

### Version

163

### Device

Desktop

### Browser

Chrome, Edge

### OS

Windows

**Comment by RenaudRohlinger** [comment]
Can't reproduce on MacOS. Could this be related to https://github.com/mrdoob/three.js/pull/28021?

**Comment by Mugen87** [comment]
The OP uses `r163` and #28021 is only on the `dev` branch.

**Comment by Mugen87** [comment]
The numeric value `33776` corresponds to `ext.COMPRESSED_RGB_S3TC_DXT1_EXT` so the texture is using `RGB_S3TC_DXT1_Format`.

**Comment by Thakisis** [comment]
sure i will try in other two computers and tell you if that error persist 
![Canary](https://github.com/mrdoob/three.js/assets/11295113/56c153a0-407f-41e8-96d9-bc34f2d8452d)

**Comment by Thakisis** [comment]
Tried different computers. 2 laptop and other desktop and same problem.

**Comment by GitHubDragonFly** [comment]
If it helps with this issue, I use a Windows 10 laptop and this example works in both Chrome and Edge.

![WebGPU GLTF Compressed - Chrome](https://github.com/mrdoob/three.js/assets/69928501/f36bc5fd-11cf-4c28-aa8c-77dd73c9de80)

**Comment by Mugen87** [comment]
This issue is actually a duplicate of #26124.

On macOS (at least on my system) `KTX2Loader` produces an ETC2 texture (`RGB_ETC2_Format`) which is properly supported in `WebGPURenderer`. However, on Windows I can confirm the loader produces `RGB_S3TC_DXT1_Format` which is an unsupported format in WebGPU. It has to be an RGBA format meaning `RGBA_S3TC_DXT1_Format`.

@donmccurdy Can we tell `KTX2Loader` somehow not to  target  `RGB_S3TC_DXT1_Format` when using WebGPU?

**Comment by Mugen87** [comment]
Closing in favor of #26124.

**Comment by Thakisis** [comment]
If I'm the only one experiencing this issue, I believe it can be closed. I will conduct further tests with additional hardware to identify any factors in my environment that may be causing this behavior.

**Comment by donmccurdy** [comment]
> Can we tell KTX2Loader somehow not to target RGB_S3TC_DXT1_Format in context of WebGPU?

I think we could do that unconditionally for both WebGL and WebGPU. BC1 has a 1-bit alpha channel, which I think would be included regardless of whether we specify RGB or RGBA here.
