### ISSUE TITLE
When using tween for animation with yoyo(true) set, the element flickers briefly upon returning

### ISSUE THREAD

**Issue by senher** [mrdoob/three.js#28031]
### Description

When using tween for animation with yoyo(true) set, the element flickers briefly upon returning；
This will not happen if the version is less than 0.162.0；
I tried switching the screen refresh rate from 60hz-120hz and it still existed；

### Reproduction steps

1.Create box
2.import TWEEN
3.use tween.yoyo(true).repeat(Infinity)

https://github.com/mrdoob/three.js/assets/23719867/4fd990ec-05a7-43ad-8faa-36542885f735

### Code

```js
// code goes here
const tween1 = new TWEEN.Tween(box1.position);
tween1.to({ x: 5 }, 2000).easing(TWEEN.Easing.Quadratic.InOut).yoyo(true).repeat(Infinity).start();
```

### Version

0.162.0

### Live example
* [jsfiddle-latest-release](https://jsfiddle.net/19mpd8zo/11/)

**Comment by Mugen87** [comment]
`tween.js` was updated in `r162` via #27670.

However, we do not support `tween.js` in this repository. It's best if you file an issue at  https://github.com/tweenjs/tween.js.

As a workaround, use a lower `tween.js` version and not the one bundled in the `three` repo.

/cc @trusktr.
