### ISSUE TITLE
Using built-in environment, reporting errors

### ISSUE THREAD

**Issue by WREQI** [mrdoob/three.js#28047]
### Description

![image](https://github.com/mrdoob/three.js/assets/35467304/d8acf600-3b7d-41e0-80f9-6cc0f6b668cb)
       

### Reproduction steps

1.Create a scene and then set up the built-in `environment`
 this.scene.environment = this.pmremGenerator.fromScene(
          new RoomEnvironment(),
          0.04
        ).texture
2.Click the button to switch,   Copying an old scene to create a new one
    const newScene = new scene();
    newScene.copy(this.scene, false);
this.scene = newScene 
3.To render a new scene Will report an error

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

163

**Comment by Mugen87** [comment]
Please ask for help at the forum first. If it turns out to be an bug in the engine, we can reopen the issue.

Besides, when posting at the forum, please share a live example that demonstrates what you are doing.
