### ISSUE TITLE
colorspace issue in WebXR in Apple VisionOS 1.1

### ISSUE THREAD

**Issue by danrossi** [mrdoob/three.js#28044]
### Description

I've noticed that pesky colorspace issue with washed out contrasted colours when in WebXR in visionOS 1.1 simulator. Not sure what the work around is. It's a normal colorspace when not in XR. The video will pause when launching but it should be fine to see the problem. 

### Live example

[https://threejs.org/examples/?q=video#webxr_vr_video](https://threejs.org/examples/?q=video#webxr_vr_video)

### Screenshots

![Screenshot 2024-04-02 054921](https://github.com/mrdoob/three.js/assets/710277/1093b117-7c05-47f3-a1af-2827f9c87897)
![Screenshot (139)](https://github.com/mrdoob/three.js/assets/710277/d356030c-621c-4f79-9f4e-c438fe469c91)

### Version

163dev

### Device

Headset

### Browser

Safari

### OS

iOS

**Comment by donmccurdy** [comment]
Is the problem only happening with video playback examples? And does anyone know if this happens in a physical Vision Pro device, or just the simulator?

**Comment by danrossi** [comment]
Yes it's the same for an image demo. Im trying to make a raw webgl demo launching to webxr and tinker with texture colorspace. It could be another webkit bug. They actually released visionOS 1.1 with a webinspect bug I reported forcing me to build a websocket proxy logger to debug transient-pointer control implementation.

https://threejs.org/examples/?q=pano#webxr_vr_panorama_depth

![Screenshot 2024-04-02 204804](https://github.com/mrdoob/three.js/assets/710277/c7514771-a60a-4cd9-8f04-c00663a024a8)
![Screenshot 2024-04-02 204924](https://github.com/mrdoob/three.js/assets/710277/2e78432a-cb8b-4f54-8ec8-a76c72cd4118)

**Comment by donmccurdy** [comment]
Note that the simulator is trying to represent an HDR, wide-gamut device. That may require additional gamut and tone mapping, depending on the device and display on which you're running the simulator. Can we identify whether this happens on the physical device?

I would also recommend filing a bug for Webkit on VisionOS – it looks unlikely that this is a three.js-specific problem.

**Comment by danrossi** [comment]
I had somebody contact me regards to supporting the transient-pointer which I managed to figure out how it works and make changes for it. But they also mentioned about this issue, I've asked to comment here if they have a headset. I connect over VNC to the mac mini but directly connected and it's the same issue. 

I'll make a webkit bug report. Because it's also happening on the samples site I guess close this. Sorry about that.

**Comment by danrossi** [comment]
Closing. There seems to be a ticket already. Sorry about that mate. https://bugs.webkit.org/show_bug.cgi?id=270465
