### ISSUE TITLE
Vector3.prototype.isVector3 = true is being set inside the constructor of Vector3 class.

### ISSUE THREAD

**Issue by 0xF48** [mrdoob/three.js#28079]
### Description

why is being called every time a Vector3 object is created? shouldn't this be placed outside of the class?

### Reproduction steps

Vector3 class prototype in https://github.com/mrdoob/three.js/blob/dev/src/math/Vector3.js#L8

### Code

import * as MathUtils from './MathUtils.js';
import { Quaternion } from './Quaternion.js';

class Vector3 {

	constructor( x = 0, y = 0, z = 0 ) {

		Vector3.prototype.isVector3 = true;

		this.x = x;
		this.y = y;
		this.z = z;

	}

### Live example

no example

### Version

r163

**Comment by Mugen87** [comment]
This is related to tree-shaking. I suggest you study the related issues and PRs in this context. E.g. #24047, #24219, #24167.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you have more questions about this topic.
