### ISSUE TITLE
Remove voxeljs from homepage

### ISSUE THREAD

**Issue by bastecklein** [mrdoob/three.js#28091]
### Description

I would suggest removing the link to https://voxeljs.com/ from the threejs homepage, it now appears to be a link to a gambling related website and has nothing to do with threejs.

### Reproduction steps

Just go to https://voxeljs.com/ and see.

### Code

no code needed

### Live example

go here https://voxeljs.com/

### Version

r163

**Comment by Mugen87** [comment]
Thanks for letting us know! I've commented out the link. The website should be updated soon.
