### ISSUE TITLE
THREE.SplineCurve incompatible with inherited `computeFrenetFrames()` method

### ISSUE THREAD

**Issue by Bug-Reaper** [mrdoob/three.js#28117]
### Description

When you run the `computeFrenetFrames()` method on a THREE.SplineCurve you get binormals and normals that have all NAN values in their vector3 xyz-attribues. 

### Reproduction steps

1. Create a THREE.SplineCurve.
2. Run `computeFrenetFrames()` method.
3. Log results to observe corrupt NAN values in normals/binormals

### Code

```js
const curve = new THREE.SplineCurve( [
	new THREE.Vector2( -10, 0 ),
	new THREE.Vector2( -5, 5 ),
	new THREE.Vector2( 0, 0 ),
	new THREE.Vector2( 5, -5 ),
	new THREE.Vector2( 10, 0 )
] )
console.log(curve.computeFrenetFrames(10,false))

```

### Live example

No live example, but see 2 line copy-paste above.

### Screenshots

<img width="349" alt="Screenshot 2024-04-11 at 3 57 36 PM" src="https://github.com/mrdoob/three.js/assets/31227781/39fa9cba-3910-44b4-9ab7-3ec0c02ea9c8">

### Version

161

### Device

Desktop

### Browser

Chrome, Firefox

### OS

MacOS

**Comment by Mugen87** [comment]
This is a known restriction of the method. As stated in the [documentation](https://threejs.org/docs/index.html#api/en/extras/core/Curve.computeFrenetFrames): 

>  Requires a curve definition in 3D space.

**Comment by Bug-Reaper** [comment]
Thanks @Mugen87 

For ref, this also happens if you use Vector3s as the SplineCurve points. I had copied the default curve from the docs offhand but updated snippet below also produces NAN binormals/normals when you `computeFrenetFrames()`.

```javascript
const curve = new THREE.SplineCurve([
	new THREE.Vector3( -10, 0, 1 ),
	new THREE.Vector3( -5, 5, 1 ),
	new THREE.Vector3( 0, 0, 1 ),
	new THREE.Vector3( 5, -5, 1 ),
	new THREE.Vector3( 10, 0, 1 )
] )
console.log(curve.computeFrenetFrames(10,false))
```

I guess SplineCurve is still 2D even though it allows for 3D points as inputs and retains them in the `points` property of the curve. Had confused me. 

Unclear if desired for 2D curves to accept 3D points like this, just a heads up.

**Comment by Mugen87** [comment]
`SplineCurve` only works with `Vector2`. That is indeed intentional. For 3D input, sse `CatmullRomCurve3` instead.
