### ISSUE TITLE
Provide a parameter to skip the extension check in MMDLoader

### ISSUE THREAD

**Issue by LancerComet** [mrdoob/three.js#28115]
### Description

There's code in MMDLoader for checking file types by the file ext:

https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/MMDLoader.js#L137

which is neither secure nor convenient. This approach prevents people from loading models using Blob/ArrayBuffer or window.URL.createObjectURL. It would be better to remove it or offer a parameter to skip the check.

### Solution

Remove it or offer a parameter to skip the check.

Also model type should be provided automatically (header checking) or manually.

### Alternatives

None

**Comment by Mugen87** [comment]
If the check for the extension is removed, how does subsequent code decide whether to call `loadPMD()` or `loadPMX()`?

**Comment by LancerComet** [comment]
> If the check for the extension is removed, how does subsequent code decide whether to call `loadPMD()` or `loadPMX()`?

The first three bytes of a pmx file are 50 4D 58, I think it should be done by checking the file header.

Upon further reflection, I realized my requirement is to read an mmd model from a local file (in the form of an arraybuffer, Blob, File, whatever), not via HTTP. Essentially, this would involve uploading a zip file containing a complete set of files, from which the MMDLoader could correctly read the mmd files as if accessing them through a local filesystem. However, a cursory review of the MMDLoader's code indicates it heavily relies on absolute http uri, which is tough to achieve the goal.

**Comment by LancerComet** [comment]
I closed the issue because I now believe that this requirement will be difficult to achieve for some time.
