### ISSUE TITLE
Configure the `Video` in a `VideoTexture` to just read from the alpha channel

### ISSUE THREAD

**Issue by jparismorgan** [mrdoob/three.js#28128]
### Description

Hi there, my goal is to create an effect like this, but a) as a video instead of a still image b) with a single HTML video element holding both RGB and depth:
* https://huggingface.co/spaces/Xenova/depth-anything-web
* https://github.com/xenova/transformers.js/blob/main/examples/depth-anything-client/main.js

I can achieve a) by loading two different video elements and creating two separate `VideoTexture`'s. But this may lead to issues where they get out of sync, so ideally I would be able to encode both RGB and depth in a single video.

I have created an HTML video element with `id="video"`. This HTML video element holds an RGBA video where the alpha channel holds a depth map. I would like to be able to use the same `VideoTexture` as both the `map` and `displacementMap` of a `MeshStandardMaterial`:
```
const video = document.getElementById( 'video' );
const texture = new THREE.VideoTexture( video );
const material = new THREE.MeshStandardMaterial({map: video, side: THREE.DoubleSide})
material.displacementMap = TODO
```

### Solution

I'd like a way to achieve this effect with a single HTML video element.

### Additional context

Thank you!

**Comment by Mugen87** [comment]
This request is so specific that there won't be a default solution inside the engine. I suggest you develop a custom solution by using `onBeforeCompile()` and replace the `map_fragment` shader chunk with different code (the sampling of video textures happens inside `map_fragment`).

Please ask at the [forum](https://discourse.threejs.org/) for more guidance.
