### ISSUE TITLE
Object3D.copy documentation missing description

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#28140]
### Description

Object3D.copy documentation says:

> Copy the given object into this object

It does not specify at all what happens with the children, other than saying:

> recursive -- if true, descendants of the object are also copied

What I see in the implementation is:

- when not recursive, `children` are left unchanged
- when recursive, clones of the source object children are added to the children the object already has

I find the fact existing children are left as they are worth noting, one might expect a bit different behavior.

I guess most prominent use is in `clone`, where there are no children, but the method exists as a separate method.

### Solution

Describe current behaviour in docs

### Alternatives

Do nothing, let the users be surprised

**Comment by Mugen87** [comment]
> I find the fact existing children are left as they are worth noting, one might expect a bit different behavior.

Indeed. Now that I think about it, calling `clear()` before copying over the children makes more sense.

**Comment by OndrejSpanel** [comment]
> calling `clear()` before copying over the children makes more sense.

I guess changing the behavior is not an option, given current behavior exists for very long and someone can rely upon it?

**Comment by Mugen87** [comment]
A breaking change is not a taboo. If the a new behavior is clearly better, it makes sense to change it. 

To me, a copy should be an exact replicate of the source. It seems confusing when aspects of the previous object state (in this case the children) are retained and not overwritten.
