### ISSUE TITLE
MapControls requires enableRotate=false on IOS

### ISSUE THREAD

**Issue by talkingtab** [mrdoob/three.js#28149]
### Description

On a linux or mac, a MapControl does not allow rotation does not, but the same code when run on IOS (latest) Safari, allows two-finger rotation.  I am not sure why, but it is simple to reproduce (if you have an iPhone). I do not know which behavior is correct, but it should be consistent across platforms.

### Reproduction steps

1. Set up Mapcontrols
2. controls.screenSpacePanning = true;
3. control.zoomToCursor = true

This works in web browsers, but rotates with two finger touch on IOS Safari

### Code

```js
const controls = new MapControls(camera, renderer.dom);
controls.screenSpacePanning = true;
control.zoomToCursor = true;
// above code allows a two finger rotation on IOS safari 

// add and it works two finger rotation does not work on IOS safari
control.enableRotate=false
```

### Live example

 I don't know how to set up a fiddle. 

### Version

0.163.0

### Device

Mobile

### Browser

Safari

### OS

iOS

**Comment by gkjohnson** [comment]
> On a linux or mac, a MapControl does not allow rotation 

MapControls do allow rotation when using right click by default. See the `mouseButtons` and `touches` settings the [MapControls documentation](https://threejs.org/docs/?q=Mapcon#examples/en/controls/MapControls)
