### ISSUE TITLE
GLTFLoader addon is missing (import from examples?!)

### ISSUE THREAD

**Issue by damil42** [mrdoob/three.js#28144]
### Description

If I want to load a glb file I need to import from examples which is a part of the package? Seriously? 

```ts
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
```

in [docs](https://threejs.org/docs/#examples/en/loaders/GLTFLoader) it's

```ts
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader';
```

But this does not exist.

### Solution

1. Don't includes examples in package.
2. Provide this addon in package in proper way.

### Alternatives

Update docs.

### Additional context

Btw. it's simply `npm i three` not `npm install --save three` nowadays. Instead of examples, you could include type definitions what current is on `@types/three`.

[three](https://www.npmjs.com/package/three) 0.163.0

**Comment by Mugen87** [comment]
> But this does not exist.

We couldn't rename the examples folder for backwards compatibility reasons so the `addons` exists as an alias. It is defined in the `package.json` right here:

https://github.com/mrdoob/three.js/blob/60e56fd9557869c64d45b45779ee96648ff7dd73/package.json#L16

Your build tool should recognize this alias. If not, there might be an issue with its configuration.

If you don't use a build tool, you have to define in an import map that resolves `three` and `three/addons/`.

This is all explained in the following guide: https://threejs.org/docs/index.html#manual/en/introduction/Installation

If you need more help, please ask at the [forum](https://discourse.threejs.org/) for guidance.
