### ISSUE TITLE
Distortion of the model due to being too far from the origin 

### ISSUE THREAD

**Issue by vci-core** [mrdoob/three.js#28148]
### Description

I created a world map with the world origin at the geographic longitude and latitude origin At this point, I placed a robot in the Chinese region, but the robot was distorted; But when I place the robot at the origin of the world, it can display normally
![IMG_3627](https://github.com/mrdoob/three.js/assets/130562025/46b9dd91-4fb6-4168-9a65-bb8221bf0fe8)
![IMG_3628](https://github.com/mrdoob/three.js/assets/130562025/bbc208aa-6bcb-479c-8d35-3693a0cab4ed)

I want to know why robots are distorted

### Reproduction steps

1. Load your official example robot model through GltfLoader and set a position far from the world origin
2. Move the perspective camera to the position of the robot and look towards the robot
3. At this point, the robot is distorted, and all of its animations will have a sense of tearing fragments! But if I change the robot's position to the origin at this moment, everything will be normal. 

### Code

```js
// code goes here
```
No code required

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)
Sorry, we can't provide it

### Version

163

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by gkjohnson** [comment]
This issue is discussed at the forums here:

https://discourse.threejs.org/t/large-coordinates/50621/21

It's not something that three.js can automatically fix, unfortunately. You'll need to make sure the skinning transformations that are happening on the GPU are not of a huge scale.

**Comment by donmccurdy** [comment]
cc https://stackoverflow.com/q/78333853/1314762
