### ISSUE TITLE
It appears that the resources associated with DRACOLoader may not be completely released, leading to memory consumption issues

### ISSUE THREAD

**Issue by mybraveheart** [mrdoob/three.js#28158]
### Description

I have observed that the DRACOLoader class in Three.js seems to retain memory even after calling dracoLoader.dispose(); and setting dracoLoader = null;. This results in additional memory overhead each time a new instance is created using new DRACOLoader();. It appears that the resources associated with DRACOLoader may not be completely released, leading to memory consumption issues.

I have encountered memory consumption issues with DRACOLoader in Three.js and would appreciate any guidance or solutions to address this problem.

### Reproduction steps

1. Create a new instance of DRACOLoader using new DRACOLoader();.
2. Call dracoLoader.dispose(); and set dracoLoader = null;.
3. Repeat the above steps multiple times and monitor memory usage.

### Code

```js
let gltfLoader2 = new GLTFLoader();
const gltfLoader = (url) => {
  let dracoLoader = new DRACOLoader();
  dracoLoader.setDecoderPath("/draco/gltf/");
  dracoLoader.setDecoderConfig({ type: "js" });
  dracoLoader.preload();
  return new Promise((resolve, reject) => {

    gltfLoader2.setDRACOLoader(dracoLoader);
    gltfLoader2.load(url, (gltf) => {
      resolve({ gltf });
    }, () => {
    }, () => {
    });
  }).finally(()=>{
    dracoLoader.dispose()
    dracoLoader = null
  });
}
```
### Live example

null

### Version

 "three": "^0.163.0",

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by mybraveheart** [comment]
I expect that calling dracoLoader.dispose(); and setting dracoLoader = null; should completely release the resources associated with the DRACOLoader instance, preventing any memory leaks and excessive memory consumption. However, when repeatedly switching scenes and clearing current scene resources, the memory usage continues to increase over time. This leads to a gradual accumulation of memory consumption, as observed in the computer's task manager or Chrome's task manager, rather than in the Heap Snapshot of the Memory panel.
Apply

**Comment by Mugen87** [comment]
I can't reproduce a memory leak with this fiddle: https://jsfiddle.net/hqaev38b/1/

At least Chrome's task manager shows no continuous increase in memory consumption. I've also tested locally with a higher loading internal (100ms) and even then I can't see a memory leak.

Does the memory leak still occur if you remove the usage of `DRACOLoader` from your app?

**Comment by Mugen87** [comment]
I'm unable to reproduce a memory leak with this fiddle: https://jsfiddle.net/bpfxg1dj/

I also did a local test with a higher loading frequency (100ms) but couldn't see a continuous increase in memory consumption in Chrome's task manager. 

Does the memory leak in your app go away if you remove the usage of `DRACOLoader`?

**Comment by mybraveheart** [comment]
Thank you very much for your help. I have found the issue. It seems that when I add the model to the scene, and then manually trigger garbage collection by opening the F12 memory test window, the resources appear to stay in Chrome's memory. However, if I keep the F12 window closed all the time, even after adding the model hundreds of times, and then open the F12 window to trigger garbage collection, the memory growth issue does not occur.

**Comment by Mugen87** [comment]
In this case, it's best to report the issue to the browser vendor.

**Comment by lishu2006ll** [comment]
> Thank you very much for your help. I have found the issue. It seems that when I add the model to the scene, and then manually trigger garbage collection by opening the F12 memory test window, the resources appear to stay in Chrome's memory. However, if I keep the F12 window closed all the time, even after adding the model hundreds of times, and then open the F12 window to trigger garbage collection, the memory growth issue does not occur.

i have the same problem, can't close the memory!!!
