### ISSUE TITLE
Build a grid through custom coordinates

### ISSUE THREAD

**Issue by hanChao-IsBigPenisBoy** [mrdoob/three.js#28189]
### Description

I randomly saved 6 points of vect3 on the plane, and I want to increase the y value of these 6 points by 6 units, so that it becomes 12 points. I want to use these 12 points to form a closed model. How should the code be implemented? Here is my code, but it doesn't feel ideal

### Solution

no

### Alternatives

no

**Comment by Mugen87** [comment]
Please ask for help at the [forum](https://discourse.threejs.org/).
