### ISSUE TITLE
Enhance target type for SpotLight and DirectionalLight

### ISSUE THREAD

**Issue by z4122** [mrdoob/three.js#28188]
### Description

SpotLight and DirectionalLight have an Object3D target type: 
![image](https://github.com/mrdoob/three.js/assets/13222615/4b1da1dc-bd96-4b4e-b4f4-02dac85802f1)
On the other hand, OrbitControl has a Vector3 target type: 
![image](https://github.com/mrdoob/three.js/assets/13222615/3085ee94-c3e4-4787-a5bc-62361f194f86)

It makes users confused, and inconvinent for users. Can I open a PR to unify the targets as either Object3D or Vector3?

### Solution

Unify target to either Object3D or Vector3.

### Alternatives

null

**Comment by Mugen87** [comment]
The idea is to remove `targets` from directional and spot light at some point, see #5079. I've planned to revisit this issue soon

For controls, a target of type `Vector3` seems fine.
