### ISSUE TITLE
`.equals` in class `Spherical` 

### ISSUE THREAD

**Issue by chenxinhang12345** [mrdoob/three.js#28191]
### Description

We have `.equals` in `Vector` classes for all dimensions. Why cant we have `.equals` in `Spherical`?

### Solution

Add comparison method for class `Spherical` just like other `VectorN` classes, should be pretty simple I guess?

### Alternatives

Do nothing but we would definitely want to use something like `JSON.stringify()` or some other workaround to compare two `Spherical`?

**Comment by WestLangley** [comment]
`Spherical` and `Cylindrical` coordinates are not unique, and neither class has an `equals()` method.

Can you please explain your use case?

**Comment by chenxinhang12345** [comment]
Yeah you are right. Those classes shouldn't have `.equals` methods.

**Comment by Mugen87** [comment]
> Spherical and Cylindrical coordinates are not unique, and neither class has an equals() method.

Do you mind explaining this in more detail. Why can we compare euclidian coordinates but not spherical ones? The following does work as expected:
```js
const v1 = new THREE.Vector3( 1, 0, 0 );
const v2 = new THREE.Vector3( 1, 0, 0 );
console.log( v1.equals( v2 ) ); // true

const s1 = new THREE.Spherical().setFromVector3( v1 );
const s2 = new THREE.Spherical().setFromVector3( v2 );
console.log( equals( s1, s2 ) ); // true
 
function equals( s1, s2 ) {

	return ( ( s1.radius === s2.radius ) && ( s1.phi === s2.phi ) && ( s1.theta === s2.theta ) );

}
````
Demo: https://jsfiddle.net/8fbkpr60/1/

**Comment by WestLangley** [comment]
... because `Spherical` and `Cylindrical` coordinates are not unique, just as 2D polar coordinates are not unique.

```js
const s1 = new THREE.Spherical( 1, 0, 0 );
const s2 = new THREE.Spherical( 1, 0, 2 * Math.PI );
```

Likewise, `quaternion.equals( q )` is also incorrect because quaternions are not unique.

//

As a side note, I am not in favor of methods that compare floating point values using equality. I would have preferred

`Vector3.equals( vector, tolerance = 0 )`.

**Comment by chenxinhang12345** [comment]
Instead of adding `.equals()`, would it be a good idea to add `toVector3()` so that we could compare the derived Euclidian coordinates?

**Comment by WestLangley** [comment]
@chenxinhang12345 Do this:

```js
const v1 = new THREE.Vector3().setFromSpherical( s1 );
```
