### ISSUE TITLE
File Export Whole Scene feature was removed 😨

### ISSUE THREAD

**Issue by LAGENCECREE** [mrdoob/three.js#28209]
### Description

The export scene as JSON has been removed! 

Without this feature, the editor loses much of its appeal as an editing tool. 
It allowed for the opening and saving of the root node of the project along with all settings, 
without losing data like the GLB export does for example (alphaMap, userDatas...).

While the JSON format was heavy, it allowed for saving the scene for future changes. 
(localStorage saving is very cool, but it doesnt allow switching between various projects)

I understand that there are many editors available currently, 
but the one coming from three.js/editor was particularly compelling as a swiss knife tiny editor, 
akin to ffmpeg for video in a way, 
albeit significantly less so without the export scene feature.

### Solution

re-add file export whole scene feature 🙏

### Alternatives

fix GLB export to embed all the datas of the scene for reauthoring or beeing complete for futures gltf loader imports

**Comment by Mugen87** [comment]
The export option has not been removed. It has just been moved to a different location in the UI, see: https://github.com/mrdoob/three.js/commit/109c87fbefa8c1ab391d1d7c53abf5b983ab9944

You can now click on an entry in the outliner (like the scene), navigate to the `OBJECT` tab and then hit the `EXPORT JSON` button at the bottom. This button is also available in the `GEOMETRY` and `MATERIAL` tab which makes it now possible to just export geometry and materials.

**Comment by LAGENCECREE** [comment]
Cool !  thanks for your reply :)
Used to the usual export, I hadn't seen it :)

i will try to adopt it :)
the previous version was a bit more efficient and standard for root node

- "file>export" located next to "file>import" 
- 1 click to direct JSON download (vs UX now requires 3 clicks , and a filename edit )
