### ISSUE TITLE
Editor can't import glTF with .ktx2 textures

### ISSUE THREAD

**Issue by bobWinner** [mrdoob/three.js#28202]
### Description

Let's try theses samples :
https://github.com/KhronosGroup/3D-Formats-Guidelines/tree/main/samples/Duck

glTF ; (with .png texture) is ok.

glTF-KTX-ETC1S ; (with .ktx2 texture) don't work.

```
GET http://localhost/_LIBS/three.js-dev/editor/DuckCM.ktx2 404 (Not Found)
GLTFLoader.js:3326 THREE.GLTFLoader: Couldn't load texture DuckCM.ktx2
```

Custom made .glb from glTF-KTX-ETC1S folder imports correctly.
(made with this service http://sbtron.github.io/makeglb)

This is very annoying

### Reproduction steps

none

### Code

none

### Live example

none

### Version

0.163.0

**Comment by Mugen87** [comment]
I can reproduce. `.gltf` files with JPG or PNG can be imported via drag'n'drop by selecting all files and dragging them to the editor's viewport. This does not work if the glTF asset refers to a KTX2 texture.
