### ISSUE TITLE
Editor: drop event in UIOutliner of ui.three.js not being call

### ISSUE THREAD

**Issue by whyqiliao** [mrdoob/three.js#28214]
### Description

Edge 124.0.2478.51 x64

function onDrop(event) not being call when darg and drop things in UIOutliner

### Solution

add event.preventDefault(); in onDragOver()
![image](https://github.com/mrdoob/three.js/assets/23431123/baa7c89a-e316-4eb7-8e5b-4f8824b769f0)

### Alternatives

Version
r153

**Comment by Mugen87** [comment]
> function onDrop(event) not being call when darg and drop things in UIOutliner

I can't reproduce. The event listener is executed, I have verified this by setting a break point. It's also not clear to me how a call of `preventDefault()` in `onDragOver()` should fix an issue in `onDrop()`.

Do you mind explaining what kind of user interaction is currently broken in the editor? Please share step-by-step instructions or a video so it's clear for us how to reproduce the issue.

**Comment by whyqiliao** [comment]
no problem.
First of all ,i modify the editor layout a liitle bit, but didnt change the core things. 
Here is the capture video

https://github.com/mrdoob/three.js/assets/23431123/782e075e-57f1-4a94-90b1-28c273d9608a

**Comment by Mugen87** [comment]
> it also occur that the browser wiredly open a new tab searching 'foo'

Interesting! I've tested with Chrome, Firefox and Safari but I'm unable to reproduce the issue.

Does the tab issue only happen in Edge or it other browser as well?

**Comment by whyqiliao** [comment]
I didnt try other browser, maybe it just occur in Edge?
Here is the edge info 
![image](https://github.com/mrdoob/three.js/assets/23431123/1dbd0443-1b33-499f-93f8-7b9c0b05e678)

**Comment by whyqiliao** [comment]
It also happen in Chrome 88 x64 (i use a clean version)
![image](https://github.com/mrdoob/three.js/assets/23431123/1cf16e7b-b4db-4ff5-aa20-0b73e8f86607)

https://github.com/mrdoob/three.js/assets/23431123/9635434e-e626-479e-ae42-49a7945ec751

**Comment by whyqiliao** [comment]
the unmodified version works well, i should check my code
![image](https://github.com/mrdoob/three.js/assets/23431123/c332da24-e39b-488c-8363-5f05271fc35b)

**Comment by Mugen87** [comment]
As long as the error does not occur in the official (unmodified) version of the editor, there is no need for a patch in this repository.
