### ISSUE TITLE
RectAreaLight passes through material

### ISSUE THREAD

**Issue by dellamonica** [mrdoob/three.js#28212]
### Description

The light from a RectAreaLight passes through (some?) materials. In my use case, I'd like the lights to be properly blocked by the materials that surround it.

This can be observed here [https://threejs.org/manual/examples/lights-rectarea.html](https://threejs.org/manual/examples/lights-rectarea.html) by shrinking the rect dimensions and placing the light inside the box:

### Reproduction steps

1. Set the size and coordinates of the rect light in the manual/examples page so that it is entirely inside the box.

### Code

https://threejs.org/manual/examples/lights-rectarea.html

### Live example

https://threejs.org/manual/examples/lights-rectarea.html

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/6547066/ddc131ea-ecae-40a1-b024-7e2d4e31f1ac)

### Version

r0.157.0

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Merging this into #5180.

**Comment by dellamonica** [comment]
It's fine to merge/close this, but is there a workaround? 

- Is there some type of material that could be used to block the light?
- Is there a way to specify a bounding box to constrain how far the light could go?

**Comment by WestLangley** [comment]
@Mugen87 Perhaps this user is asking about casting shadows, not selective lighting. And of course, `RectAreaLight` currently does not support shadows.
