### ISSUE TITLE
MeshToonMaterial support for WebGPU

### ISSUE THREAD

**Issue by verekia** [mrdoob/three.js#28225]
### Description

Using MeshToonMaterial with WebGPURenderer in Three.js r164 results in the following error:
```
NodeMaterial: Material "MeshToonMaterial" is not compatible.
```

### Solution

Support for MeshToonMaterial

### Alternatives

The alternatives are using a different material or not using WebGPU.

**Comment by RenaudRohlinger** [comment]
r165 will support MeshToonMaterial in the WebGPURenderer thanks to @aargoose https://github.com/mrdoob/three.js/pull/28235!
