### ISSUE TITLE
Editor: Export GLB and GLTF fails to fetch

### ISSUE THREAD

**Issue by Ominai** [mrdoob/three.js#28224]
### Description

Trying to export any scene from the three.js editor to GLB or GLTF formats don't seem to be going through on Brave and Safari.

Over in the Inspector panel I'm seeing the following when I click on either button:
> `Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://threejs.org/examples/jsm/exporters/GLTFExporter.js`

It is worth noting that the other export and import options appear to be working as intended, just GLB and GLTF are struggling.

### Reproduction steps

1. Open three.js editor
2. File > Export GLB or File > Export GLTF
3. Nothing occurs

### Code

`Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://threejs.org/examples/jsm/exporters/GLTFExporter.js`

### Live example

https://threejs.org/editor/

### Version

r164

### Device

Desktop

### Browser

Chrome

### OS

MacOS, Linux

**Comment by RenaudRohlinger** [comment]
https://github.com/mrdoob/three.js/pull/28222 will fix the issue.

**Comment by mrdoob** [comment]
Fixed!
