### ISSUE TITLE
Black/gray outline shows around transparent textures when mipmaps are used.

### ISSUE THREAD

**Issue by Giwayume** [mrdoob/three.js#28238]
### Description

`minFilter = LinearMipmapLinearFilter`

![image](https://github.com/mrdoob/three.js/assets/4075314/589caae3-b525-4c28-b5e9-46227c904a3e)

`minFilter = LinearFilter`

![image](https://github.com/mrdoob/three.js/assets/4075314/fbd1c06e-0aff-451f-8f70-25fe554ac38a)

If a texture with transparency is drawn in front of another object, when mipmaps are in use, an unwanted outline is generated.

### Reproduction steps

1. Map a texture with a transparent background to a plane, and set up the camera so the plane is drawn smaller than the texture (so that minFilter is applied).
2. Enable mipmaps.

### Code

```js
const texture = new TextureLoader().load(
    image.src,
    () => {  },
);
texture.encoding = sRGBEncoding;
texture.magFilter = NearestFilter;
texture.minFilter = LinearMipmapLinearFilter;
```

### Live example

https://jsfiddle.net/b14e3ndf/

### Version

r149

**Comment by gkjohnson** [comment]
This is an asset issue and not something three.js can fix. The texture needs to be adjusted so that the RGB values in the transparent sections are not black. I'd recommend asking at the forums for more help on how to deal with this issue:

https://discourse.threejs.org/

**Comment by Giwayume** [comment]
They aren't, everything that is under partial transparency is fully yellow. Only the fully transparent pixels are black.

This is expected behavior if you're using a drawing brush in something like photoshop, the brush should only affect the color of the pixels underneath it. It won't attempt to change the transparent area of the entire canvas that has nothing to do with where the brush touched.

I don't agree with the assessment that this is something that should be fixed in the asset. But if WebGL has a general issue where it is incorrectly reading values from fully transparent pixels and there is no way to fix that... guess nothing can be done.

![image](https://github.com/mrdoob/three.js/assets/4075314/09d2c983-c029-49b7-a0ec-d1d06872e739)
![image](https://github.com/mrdoob/three.js/assets/4075314/4acbf44b-bc77-464d-8e2c-afc174492458)

**Comment by gkjohnson** [comment]
> They aren't, everything that is under partial transparency is fully yellow. Only the fully transparent pixels are black.

Zooming into the pixels in your image editor is not necessarily representative of what's directly in the saved asset and loaded.

> I don't agree with the assessment that this is something that should be fixed in the asset. But if WebGL has a general issue where it is incorrectly reading values from fully transparent pixels and there is no way to fix that... guess nothing can be done.

It isn't a matter of disagreement - this is a common, well understood issue when linearly interpolating transparent assets and generating mip maps. It occurs in all graphics APIs, not just WebGL. The pixels in the transparent area are black so when texture samples are interpolated or mipmaps are generated the RGB channel result is mixed with black.

**Comment by mrdoob** [comment]
> I don't agree with the assessment that this is something that should be fixed in the asset. But if WebGL has a general issue where it is incorrectly reading values from fully transparent pixels and there is no way to fix that... guess nothing can be done.
> 
> ![image](https://private-user-images.githubusercontent.com/4075314/327197150-09d2c983-c029-49b7-a0ec-d1d06872e739.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyODQ1NTgsIm5iZiI6MTcxNTI4NDI1OCwicGF0aCI6Ii80MDc1MzE0LzMyNzE5NzE1MC0wOWQyYzk4My1jMDI5LTQ5YjctYTBlYy1kMWQwNjg3MmU3MzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDlUMTk1MDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmE0MjAyYTViMWE1NTU5MGZjNjg0OTQyNmFiMjhiYjgwZTU2MDdmMjg5NmQwZGNmMmU2NTIxYjI2MmFmNGZhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uOzYzlsa5RBXk5SJ3BFgK-1gEQ6pDSmZcR38FGv0PW8) ![image](https://private-user-images.githubusercontent.com/4075314/327197238-4acbf44b-bc77-464d-8e2c-afc174492458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyODQ1NTgsIm5iZiI6MTcxNTI4NDI1OCwicGF0aCI6Ii80MDc1MzE0LzMyNzE5NzIzOC00YWNiZjQ0Yi1iYzc3LTQ2NGQtOGUyYy1hZmMxNzQ0OTI0NTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDlUMTk1MDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRmOTliMjQyMWM4ODQwYTNiODkyNmFjNWU4ZDZkNzk2MDhmMGM2ZmIwNzM2ZmNjOGM4ZjZlOWQzMWJkMThiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RfzfbR9kboeJl-l0YZzIMHX07bgUenO0DKcOGaZrAeE)

To avoid the artifacts you're seeing the top image needs to be all yellow.

For me this was a painful concept to learn back in the 90s 😬

**Comment by Giwayume** [comment]
Premultiplied alpha is an issue for handling for semi-transparent pixels, it seems this issue is the color blending occurs across fully transparent pixels. All partially transparent pixels are already yellow. I'm working on an image editor, not a video game, so the answer for me isn't as simple as "fix your asset".

If you open the smiley face asset in Photoshop you don't see the black outline when you zoom out. Maybe the answer is they're using the CPU for scaling, either way there is a solution for display that doesn't involve modifying the fully transparent black pixels.

**Comment by Giwayume** [comment]
I don't want to do something like write a shader that pulls the nearest color values from alpha > 0 pixels into alpha == 0 pixels that operates on each layer. I've seen how terrible the performance of shaders are that do cross pixel reads like a gaussian filter.
