### ISSUE TITLE
why my scene can not showed fully, after wheel scale and drag? who can help me? thanks

### ISSUE THREAD

**Issue by zj91zj** [mrdoob/three.js#28232]
### Description

why my scene can not showed fully, after wheel scale and drag? who can help me? thanks

### Reproduction steps

1. wheel scale the scene
2. drag the canvas
3. wheel scale 

### Code

import React, { useEffect, useRef } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls';

// 监听鼠标拖拽事件来实现平移
var mouseDown = false;
var mouseX = 0;
var mouseY = 0;

function GlowingCube() {
  const rendererRef = useRef();
  const sceneRef = useRef();
  const animateRef = useRef();

  useEffect(() => {
    if (!rendererRef.current) return;
    const { clientWidth, clientHeight } = rendererRef.current

    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setSize(clientWidth, clientHeight);
    rendererRef.current.appendChild(renderer.domElement);

    const scene = new THREE.Scene();
    sceneRef.current = scene;

    // 创建相机
    const camera = new THREE.OrthographicCamera(-clientWidth / 2, clientWidth / 2, clientHeight / 2, -clientHeight / 2, 1, 1000);
    // const camera = new THREE.PerspectiveCamera(90, clientWidth / clientHeight, 0.1, 1000);

    camera.position.set(0, 0, 1000);
    camera.lookAt(0, 0, 0);

    // 设置光源
    const light = new THREE.DirectionalLight(0xffffff, 1);
    light.position.set(0, 0, 10);
    scene.add(light);

    let controls = new OrbitControls(camera, renderer.domElement);
    controls.enablePan = true;
    controls.enableZoom = true;
    controls.enableRotate = false; // 关闭旋转

    let group = new THREE.Group();
    for (let i = 0; i < 4; i++) {
      for (let j = 0; j < 5; j++) {
        let geometry = new THREE.PlaneGeometry(50, 50);
        let material = new THREE.MeshBasicMaterial({ color: 0xff0000, side: THREE.DoubleSide });
        let square = new THREE.Mesh(geometry, material);
        square.isSelectable = true;
        square.name = i + '-' + j
        square.position.set(i * 60, j * 60, 0); // 设置正方形的位置
        group.add(square);
      }
    }
    scene.add(group);

    let requestId = 0
    const animate = () => {
      requestId = requestAnimationFrame(animate);
      renderer.render(scene, camera)
    };
    animateRef.current = animate;
    animate();

    document.addEventListener('pointerdown', function (event) {
      mouseDown = true;
      mouseX = event.clientX;
      mouseY = event.clientY;
    });
    document.addEventListener('pointermove', function (event) {
      if (mouseDown) {
        let deltaX = mouseX - event.clientX;
        let deltaY = event.clientY - mouseY;

        mouseX = event.clientX;
        mouseY = event.clientY;

        // 将 deltaX 转换为相机的水平移动
        camera.position.x += deltaX * 0.5;
        camera.position.y += deltaY * 0.5;

        camera.lookAt(camera.position.x, camera.position.y, 0);
        camera.updateProjectionMatrix();
      }
    });

    document.addEventListener('pointerup', function (event) {
      mouseDown = false;
    });

    return () => {
      cancelAnimationFrame(requestId);
      renderer.dispose();
    };
  }, [rendererRef.current]);

  return <div ref={rendererRef} style={{ height: '100%', width: '100%', background: '#fff' }} />;
}

export default GlowingCube;

### Live example

https://jsfiddle.net/q0ko4j95/1/

### Screenshots

![微信图片11111111111](https://github.com/mrdoob/three.js/assets/41497368/265714c2-504a-4112-9ca3-6c61c1951afc)

### Version

"three": "^0.162.0"

### Device

Desktop, Mobile

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
