### ISSUE TITLE
GLTFLoader does not load external ktx2 textures

### ISSUE THREAD

**Issue by catalin-enache** [mrdoob/three.js#28258]
### Description

Loading this GLTF asset
https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnisotropyBarnLamp/glTF-KTX-BasisU
which has external `ktx2` textures
fails with error: `THREE.GLTFLoader: Couldn't load texture`.  
This is raised by GLTFLoader at line 2658

### Reproduction steps

Just try to load a gltf asset having external ktx2 textures:
https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/AnisotropyBarnLamp/glTF-KTX-BasisU/AnisotropyBarnLamp.gltf

### Code

```js
ktxLoader = new KTX2Loader()
  .setTranscoderPath( 'jsm/libs/basis/' )
  .detectSupport( renderer );

const loader = new GLTFLoader().setPath( 'models/gltf/' );
loader.setKTX2Loader( ktx2Loader );
// loader.setMeshoptDecoder( MeshoptDecoder );
loader.load( 'AnisotropyBarnLamp.gltf', function ( gltf ) {
  scene.add( gltf.scene );
});
```

Looking through the code I found that `ktx2Loader` is not used inside the `GLTFParser` even it is sent in options from `GLTFLoader`

It seems to be fixed with a bit of a patch inside GLTFParser.
If we change these lines from:
```javascript
    if (typeof createImageBitmap === 'undefined' || isSafari || (isFirefox && firefoxVersion < 98)) {
      this.textureLoader = new TextureLoader(this.options.manager);
    } else {
      this.textureLoader = new ImageBitmapLoader(this.options.manager);
    }
```
to
```javascript
const isKTX2 = json.images?.some((img) => img.uri?.split('.').pop() === 'ktx2'); // assuming all images are the same type
if (isKTX2 && this.options.ktx2Loader) {
      this.textureLoader = this.options.ktx2Loader;
    } else if (typeof createImageBitmap === 'undefined' || isSafari || (isFirefox && firefoxVersion < 98)) {
      this.textureLoader = new TextureLoader(this.options.manager);
    } else {
      this.textureLoader = new ImageBitmapLoader(this.options.manager);
    }
```

### Live example

https://codesandbox.io/p/sandbox/young-waterfall-22pkx4?file=%2Fsrc%2Findex.js%3A8%2C61
Please play with different imports (original/patched) (also note that it takes long to load the asset):
![image](https://github.com/pmndrs/three-stdlib/assets/4470065/76b14796-4919-4ede-baf6-6acc40f911ba)

### Version

0.164.1

### Device

Desktop

### Browser

Edge

### OS

MacOS

**Comment by donmccurdy** [comment]
It is working for me dropping this asset into the example from https://threejs.org/examples/?q=gltf#webgl_loader_gltf_compressed. GLTFParser itself does not know about KTX2, and isn't intended to, but the extension implementation passes that in:

https://github.com/mrdoob/three.js/blob/697a873e88ceae9f711fa06042824b3da21fe6a0/examples/jsm/loaders/GLTFLoader.js#L1403-L1434

I'm not sure yet what is happening in the codesandbox though.

**Comment by catalin-enache** [comment]
Thanks for the feedback.
Since you mentioned #webgl_loader_gltf_compressed I tried it now too.

I changed it a bit to load the asset with the issue by removing the `setPath` and by loading the `gltf` from that repo.
![image](https://github.com/mrdoob/three.js/assets/4470065/b633bc3c-60ce-4c87-aa86-667015f65aaa)

The full path to the problem asset is: `https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/AnisotropyBarnLamp/glTF-KTX-BasisU/AnisotropyBarnLamp.gltf`
It doesn't work:
![image](https://github.com/mrdoob/three.js/assets/4470065/648ac622-9379-4353-8057-6d91f9d1cbac)

However in the same page if i change the path to a sibling asset from the same repo (one that uses png as texture) it works:
`https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/AnisotropyBarnLamp/glTF/AnisotropyBarnLamp.gltf`
but it is not visible until adjusted like: `gltf.scene.scale.x = gltf.scene.scale.y = gltf.scene.scale.z = 100;`
![image](https://github.com/mrdoob/three.js/assets/4470065/f437ac0b-5610-45f6-9246-be89e68b1c37)

So, as far as I can see loading a gltf with external textures works only if they are `png` but not for `ktx2`.

**Comment by donmccurdy** [comment]
I am testing a version of the same asset, with embedded ktx2 textures. I downloaded the model you shared with:

```javascript
gltf-transform cp https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/AnisotropyBarnLamp/glTF-KTX-BasisU/AnisotropyBarnLamp.gltf out/lamp.gltf --allow-http
```

This creates a local copy, with the textures still external. I see the issue now, though. The `gltf-transform cp` command reformats the file, and corrects a problem that was embedded in the original.

**before:**

```jsonc
"textures": [
    {
      "sampler": 0,
      "source": 0,
      "name": "AnisotropyBarnLamp_normalbump.ktx2"
    },
    {
      "sampler": 0,
      "source": 1,
      "name": "AnisotropyBarnLamp_occlusionroughnessmetal.ktx2"
    },
    {
      "sampler": 0,
      "source": 2,
      "name": "AnisotropyBarnLamp_basecolor.ktx2"
    },
    {
      "sampler": 0,
      "source": 3,
      "name": "AnisotropyBarnLamp_anisotropy.ktx2"
    }
  ],
```

**after:**

```jsonc
  "textures": [
    {
      "sampler": 0,
      "extensions": {
        "KHR_texture_basisu": {
          "source": 2
        }
      }
    },
    {
      "sampler": 0,
      "extensions": {
        "KHR_texture_basisu": {
          "source": 0
        }
      }
    },
    {
      "sampler": 0,
      "extensions": {
        "KHR_texture_basisu": {
          "source": 1
        }
      }
    },
    {
      "sampler": 0,
      "extensions": {
        "KHR_texture_basisu": {
          "source": 3
        }
      }
    }
  ],
```

The original is invalid, and the second version is correct use of `KHR_texture_basisu`, per requirements from the spec:

https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_texture_basisu/README.md#using-without-a-fallback

So it looks like this example `.gltf` file is not correctly authored, and we'll need to report that issue to Khronos.

**Comment by donmccurdy** [comment]
Filed an issue upstream:

- https://github.com/KhronosGroup/glTF-Sample-Assets/issues/117

**Comment by catalin-enache** [comment]
@donmccurdy I confirm it works after copying with `gltf-transform `as suggested.
The model is loaded with `external` `ktx2` textures after the `gltf` structure is repaired.
Thank you so much for looking into it and raising the issue upstream.
I'll keep `gltf-transform` close. It seems to be very useful.
This issue can be closed now.
