### ISSUE TITLE
Material copy function issue

### ISSUE THREAD

**Issue by YusakuNo1** [mrdoob/three.js#28265]
### Description

As the Material class doesn't include some fields like color, emissive, the following code will crash at [this line](https://github.com/mrdoob/three.js/blob/f2766a0dfc47a790cd64dec6f9b7132d6fee9fa8/src/materials/MeshStandardMaterial.js#L87), and then crash for `normalScale` etc.:

```
const basicMaterial = new MeshBasicMaterial( { color: 0xff00ff } );
const standardMaterial = new MeshStandardMaterial();
standardMaterial.copy( basicMaterial );
```

Fix options:
1. Update the copy functions for materials to check whether the fields are undefined or not
2. Update the copy functions from Color/Vector2 to check whether the fields are undefined or not

I can do the change, but before changing the code, I need some recommendations from the community

### Reproduction steps

1. Run the code in unit test

### Code

```js
const basicMaterial = new MeshBasicMaterial( { color: 0xff00ff } );
const standardMaterial = new MeshStandardMaterial();
standardMaterial.copy( basicMaterial );
```

### Live example

N/A

### Version

0.164.1

**Comment by Mugen87** [comment]
Copying material of different types is not supported. Please make sure to only copy `MeshStandardMaterial` to `MeshStandardMaterial` or `MeshBasicMaterial` to `MeshBasicMaterial`. If you want to copy incompatible types, you have to copy matching properties by yourself.
