### ISSUE TITLE
Clipping is not correct when material enables transparent and spot-light casts shadow [WebGPU]

### ISSUE THREAD

**Issue by Cerberus** [mrdoob/three.js#28267]
### Current behavior
Clipping an geometry with material additive-blending..
Mesh without set transparent ✅
<img width="300" alt="mesh-no-transparent" src="https://github.com/mrdoob/three.js/assets/9087409/571fbc7d-b360-4a0d-9128-cb532744ce81">
Spot-light without casting shadow ✅
<img width="300" alt="spotlight-no-shadow" src="https://github.com/mrdoob/three.js/assets/9087409/92294efc-3277-4f8f-af02-ae32781fa6fb">
Enable transparent & cast-shadow ❌
<img width="300" alt="enable both" src="https://github.com/mrdoob/three.js/assets/9087409/3766479a-201e-4cf3-9487-b72c7dc31033">

### Expected behavior

Clipping correctly with both configs.

---

### Another approach

I've tried to set `opacity` and `alphaToCoverage` on mesh instead and it works. However this way does not allow to use `blending: THREE.AdditiveBlending`.

### Reproduction steps

Try in demo link and orbit around the object to see clipping behavior.

### Code

The clipping behavior is not correct when enable..
```js
spotLight.castShadow = true // spotLight
transparent: true // mesh
```

### Live example

https://stackblitz.com/edit/stackblitz-starters-tezjmh?file=index.html

### Version

0.164.1

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by aardgoose** [comment]
I have a fix for this, and will push a PR soon.
