### ISSUE TITLE
Editor: name of object or its material in the scene graph tree does not refresh after changing name in sidebar

### ISSUE THREAD

**Issue by zoeeer** [mrdoob/three.js#28290]
### Description

After changing the name of an object or its material in the side bar, the name in the scene graph tree does not refresh immediately.  It only refreshes after certain other operation is made, e.g. adding an new object to the scene.

For comparison, the name of an geometry DOES refresh immediately after changing it in the sidebar.

### Reproduction steps

1. add any object (e.g. a box) to the scene
2. in the sidebar, click the "object" tab and change the name of the object, then hit Enter. Observe the Scene window, the object's name is not updated
3. add another object to the scene. Observe the Scene window, the previous object's name is now updated
4. in the sidebar, click the "geometry" tab and change the name of the geometry of the selected object, then hit Enter. Observe the Scene window, the geometry's name associated with the object is updated
5. changing name of material doesn't immediately update in the Scene window either

### Code

none

### Live example

none

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/4843075/e609fa50-2320-4800-a765-f0a4951bbe0c)

### Version

r164

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by ycw** [comment]
#28290 will solve it; 

for testing, https://raw.githack.com/ycw/three.js/tmp-rename/editor/index.html
