### ISSUE TITLE
MMDLoader Still has colorization Issues

### ISSUE THREAD

**Issue by danpaldev** [mrdoob/three.js#28336]
### Description

This is a follow up for an old issue (https://github.com/mrdoob/three.js/issues/26553) that was already closed but seems to be still having problems on r162

As the guy in the original issue reports, problem seems to be with PMX files. Every PMX model I loaded had washed out colors, so I tried to test this by using another renderer as a sanity check.

Using a  C++ renderer from here: https://github.com/benikabocha/saba 
I get this:
![image](https://github.com/mrdoob/three.js/assets/68087075/bc92ab89-0ef8-47d1-889a-d807d94eb2b1)

Using MMDLoader + ThreeJS
![image](https://github.com/mrdoob/three.js/assets/68087075/9f29c01b-578c-4a93-8b36-12d287c4d489)

As requested last time, I uploaded the PMX model here in order to make any possible debugging easier:
https://drive.google.com/file/d/1NCDDCUkThV_PCZtsXpZ81rMzChUpi9Q1/view?usp=sharing

### Reproduction steps

1. Load MMD Loader
2. Import a pmx model

### Code

```js
        import * as THREE from "three";
  
        import { GUI } from "three/addons/libs/lil-gui.module.min.js";
  
        import { OutlineEffect } from "three/addons/effects/OutlineEffect.js";
        import { MMDLoader } from "three/addons/loaders/MMDLoader.js";
        import { MMDAnimationHelper } from "three/addons/animation/MMDAnimationHelper.js";
        import { OrbitControls } from "three/addons/controls/OrbitControls.js";


        const modelFile = "models/mmd/cat_girl/ヨッシー式ラインクラフト.pmx";

        helper = new MMDAnimationHelper();

        const loader = new MMDLoader();

        loader.load(
          modelFile,
          function (object) {
            mesh = object;
            console.log(mesh);
            mesh.position.y = -10;

            scene.add(mesh);

            initGui();
          },
          onProgress,
          null
        );
```

### Live example

No live example 

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/68087075/64f4efa5-c84f-4d0a-844f-4fe2b84b08aa)

![image](https://github.com/mrdoob/three.js/assets/68087075/08fbd417-28be-47d2-aec4-16471ab884fa)

### Version

r162

### Device

Desktop

### Browser

Firefox

### OS

MacOS

**Comment by danpaldev** [comment]
Here's the full code that I used for loading the model in a gist, I just didn't want to pollute the issue description: https://gist.github.com/danpaldev/0d4b62a9b1ebdce66151d400beeafef7

**Comment by Mugen87** [comment]
Your asset has an emissive color applied. You can reset it to the default value `0x000000` like so:
```js
mesh = object;

for ( const material of mesh.material ) {

	material.emissive.set( 0x000000 );

}
```
<img width="1422" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/dbc2c90f-9b38-4141-847b-041059d68f59">

`MDDLoader` honors the ambient setting of MDD by applying it to `emissive`. There is a fix in place to avoid too bright materials when map+ambient is used. 

https://github.com/mrdoob/three.js/blob/4ec57f5014e57199fff3827972474e43cc9450ba/examples/jsm/loaders/MMDLoader.js#L1146-L1154

@takahirox Maybe this fix does not always produce the expected result?

**Comment by takahirox** [comment]
Ambient color stuff is a known issue for me. MMD ambient is not perfectly compatible with Three.js regular materials. I'm thinking of requesting users to adjust color in their user code if they are not satisfied.

Another option in my mind would be, we have MMD specific custom shader material now. So we may be able to implement ambient support more properly in it. The current fallback was introduced when I was thinking of using regular Three.js material.

**Comment by GitHubDragonFly** [comment]
@Mugen87 changing emissive is a neat improvement even for my MMD Viewer which is still using r131 of three js.

I kind of wish it was mentioned before.

**Comment by mrdoob** [comment]
Can we remove the `emissive` code for the time being?

**Comment by takahirox** [comment]
Probably color problem with other models happens if we just remove the emissive hack. At least I remember that color looked very unexpected in some MMD standard(?) models if I ignored MMD material ambient while I was testing.

**Comment by takahirox** [comment]
By the way I'm wondering if this line is executed. https://github.com/mrdoob/three.js/blob/4ec57f5014e57199fff3827972474e43cc9450ba/examples/jsm/loaders/MMDLoader.js#L1323 Can someone create a live example for me?

**Comment by Mugen87** [comment]
I have tested this locally when initially investigating the issue and I can confirm the line is executed. The ambient value in the model is `(1,1,1)` and it is scaled down by the mentioned line to `(0.2, 0.2, 0.2)`.

**Comment by takahirox** [comment]
Thanks. 0.2 is just from my rule of thumbs. Using smaller number would be another option.

And I found that in the example AmbientLight is used. Wondering how it looks like if removing the ambient light. And does the c++ reference uses ambient (or similar) light, too?

**Comment by mrdoob** [comment]
> Probably color problem with other models happens if we just remove the emissive hack. At least I remember that color looked very unexpected in some MMD standard(?) models if I ignored MMD material ambient while I was testing.

The `MMDLoader` was done before all the color spaces, color management and tone mapping work though.

Maybe the `emissive` hack is no longer needed now?
However... even if it is needed, I would avoid using `emissive` as we're "corrupting" the model.

If someone exported the scene as gltf and then rendered it in blender, the character would be emitting light...

**Comment by takahirox** [comment]
If I remember correctly MMD material ambient color is handled very similar to emissive color in MMD (I even don't remember the difference), so

>  the character would be emitting light...

so this might be expected result as model originally made from MMD.

But I need to review the MMD material spec because I saw it last time years ago. (So comment or correction is very welcome who knows MMD spec.)

**Comment by danpaldev** [comment]
> Your asset has an emissive color applied. You can reset it to the default value `0x000000` like so:
> 
> ```js
> mesh = object;
> 
> for ( const material of mesh.material ) {
> 
> 	material.emissive.set( 0x000000 );
> 
> }
> ```
> 
> <img alt="image" width="1422" src="https://private-user-images.githubusercontent.com/12612165/329768294-dbc2c90f-9b38-4141-847b-041059d68f59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjE3OTEsIm5iZiI6MTcxNTYyMTQ5MSwicGF0aCI6Ii8xMjYxMjE2NS8zMjk3NjgyOTQtZGJjMmM5MGYtOWIzOC00MTQxLTg0N2ItMDQxMDU5ZDY4ZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE3MzEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZGUxNDlkYTExMzhiMWYxZDZiOTIzMGViMGE0NDA0NjFiNmZkZmNhOTQzMGY0MDdjODhlYmRiMGU2YjRjZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6mBDtMhLLbaSbKaxcygB0z2W1LFYgpunWB8fWwi3I0A">
> 
> `MMDLoader` honors the ambient setting of MMD by applying it to `emissive`. There is a fix in place to avoid too bright materials when map+ambient is used.
> 
> https://github.com/mrdoob/three.js/blob/4ec57f5014e57199fff3827972474e43cc9450ba/examples/jsm/loaders/MMDLoader.js#L1146-L1154
> 
> @takahirox Maybe this fix does not always produce the expected result?

That did the trick, thanks for the tip. I guess this trick could be documented in the loader's docs in the meantime?

**Comment by takahirox** [comment]
@danpaldev Can you check how your models look like if removing the ambient light in your example?

**Comment by danpaldev** [comment]
@takahirox 
Ambient light off + material.emissive.set( 0x000000 );
![image](https://github.com/mrdoob/three.js/assets/68087075/8bea2a21-f74a-4e9d-8edf-b59130b9c49f)

Ambient light on + material.emissive.set( 0x000000 );
![image](https://github.com/mrdoob/three.js/assets/68087075/7d0439a4-efad-46a7-bb9f-943a6330f454)


Ambient light off with an unmodified `material.emissive`
![image](https://github.com/mrdoob/three.js/assets/68087075/ff0d3dc4-7a51-4d7c-8af7-5c82f199ca6b)

**Comment by takahirox** [comment]
Thanks for sharing the results. But I thought the washed out color problem happened because of applying the both MMD material ambient + ambient light but it seems wrong.

I started to feel that

> The ambient value in the model is (1,1,1)

something seems off. My understanding is MMD material ambient color is very similar to emissive color. So ambient value (1, 1, 1) would make the model always looks white but it doesn't in the reference. I think I need to review the MMD spec again...

**Comment by takahirox** [comment]
It seems that ambient color in MMD seems to be affected by color map, like `(diffuseColor * lighting + ambient) * colorMap.rgb`. Thinking how to simulate in Three.js and also how to make it look expected when exported.

**Comment by takahirox** [comment]
Progress...

![image](https://github.com/mrdoob/three.js/assets/7637832/ea323150-2119-48a8-a3e5-1b3bde0aab53)

**Comment by Mugen87** [comment]
`MMDLoader` has been deprecated, see #29698.
