### ISSUE TITLE
Editor: Usage of `accept` breaks certain asset imports.

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#28394]
### Description

The editor has recently started to use the `accept` field when importing assets. Previously, you could select a file format _and its related resources like textures or bin files_ in the import selection:

<img width="1241" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/c7260de5-be4b-49da-a3df-a630521099f9">

This does not work anymore since I can only select the `.gltf` file:

<img width="1255" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/4c32721f-3c2a-4314-a64c-31cf544501c1">

Just selecting the `.gltf` file is insufficient to load the asset. Many errors are reported in the browser console:

<img width="785" alt="image" src="https://github.com/mrdoob/three.js/assets/12612165/9d7489e3-d2c3-45ea-9a77-214fceb431d0">

The workaround is to fall back to drag'n'drop.

This is a bug that needs to be fixed somehow, e.g. by not using `accept` at all or by allowing all potential resources in the `accept` field.

### Reproduction steps

1. Import the glTF asset from https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf/DamagedHelmet/glTF

### Code

-

### Live example

https://rawcdn.githack.com/mrdoob/three.js/dev/editor/index.html

### Version

r165dev

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
When thinking about it, it's best to revert the `accept` usage. Otherwise we end up maintaining a a large list of file extensions that differs from the extension list in `Loader.js`.

**Comment by ycw** [comment]
The solution should be delete `accept` in file input(=let users select whatever) then lets normalize the path of "file input" and Drag n drop (=using same feedback system, see #28390)

**Comment by ycw** [comment]
> revert the accept usage.

agreed

**Comment by mrdoob** [comment]
Agreed 👍
