### ISSUE TITLE
Editor: Runtime error in history.

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#28395]
### Description

When using persistent history, a runtime error is thrown when deleting an object and refreshing the page.

> RemoveObjectCommand.js:17 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at new RemoveObjectCommand (RemoveObjectCommand.js:17:79)
    at History.fromJSON (History.js:204:16)
    at Editor.fromJSON (Editor.js:674:16)
    at async index.html:115:7

### Reproduction steps

1. Enable persistent history in the settings tab.
2. Add a box.
3. Delete it.
4. Refresh the site and check browser console.

### Code

-

### Live example

https://rawcdn.githack.com/mrdoob/three.js/dev/editor/index.html

### Version

r165dev

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by ycw** [comment]
Already solved by "Editor: Fixed recovery system" #28345 

You can try it at https://raw.githack.com/ycw/three.js/editor-commands-defer-init/editor/index.html 

Was asked to split #28345 into single PRs, I did it but there's no signals after that :D

**Comment by ycw** [comment]
#28360
 #28361
  #28362

**Comment by Mugen87** [comment]
After testing it seems https://github.com/mrdoob/three.js/pull/28360 is sufficient to fix this particular issue.

**Comment by ycw** [comment]
Since the issue isn't material-related #28362 nor about SetGeometryCommand #28361, so yes, its related to #28360 only.
