### ISSUE TITLE
Weird r164 WebGL renderer regression with GLB model

### ISSUE THREAD

**Issue by AndyGura** [mrdoob/three.js#28420]
### Description

After upgrading three.js from `0.163.0` to `0.164.0` or `0.164.1` one particular `GLB` model from my library breaks the renderer when camera looks at it, it leaves the "trail" on the screen, where only the background image visible. I'm not sure how to describe it in a more informative way TBH, see the screenshot and attached codepen

### Reproduction steps

1. open this [CodePen example](https://codepen.io/Andrew-Gura-the-flexboxer/pen/ZENQpjR)
2. move camera to the left and see that lambo car can be seen without issues
3. replace `three@0.163.0` with `three@0.164.1` in HTML
4. move camera to the left again and see the issue 

OR

1. add [this glb](https://gg-web-demos.guraklgames.com/assets/fly-city/lambo/body.glb) to scene
2. add some mesh behind this glb to see the bug
2. add two directional lights (optional?)
3. move camera

### Code

```js
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

// Scenes
const scene = new THREE.Scene();

// Sizes
let width = window.innerWidth;
let height = window.innerHeight;

// Renderer
const renderer = new THREE.WebGLRenderer({ 
  preserveDrawingBuffer: true,
  background: 0xffffff,
});
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    renderer.shadowMap.enabled = true;
    renderer.shadowMap.type = THREE.PCFSoftShadowMap;
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.setSize(width, height);
renderer.setClearColor(0xffffff, 1);
document.body.appendChild(renderer.domElement);

// Camera
const camera = new THREE.PerspectiveCamera(45, width / height, 1, 10000);
camera.position.set(4, 9, 6);
camera.up.set(0, 0, 1);

const controls = new OrbitControls(camera, renderer.domElement);
controls.target.set(0, 0, 5);
camera.lookAt(0, 0, 5);

const sun = new THREE.DirectionalLight(0xffffff, 3);
sun.position.set(200, 150, 120);
scene.add(sun);
const sky = new THREE.DirectionalLight(0xaaaaff, 0.4);
sky.position.set(-200, -150, 20);
scene.add(sky);

for (let i = -2; i < 2; i++) {
  for (let j = -2; j < 2; j++) {
    new GLTFLoader().load(
      "https://gg-web-demos.guraklgames.com/assets/fly-city/city_tile.glb",
      (gltf) => {
        gltf.scene.position.set(i * 70, j * 70, 0);
        scene.add( gltf.scene );
      }
    );
  }
}
new GLTFLoader().load(
  "https://gg-web-demos.guraklgames.com/assets/fly-city/lambo/body.glb",
  (gltf) => {
    gltf.scene.position.set(10, 0, 0);
    scene.add( gltf.scene );
  }
);

const envMap = new THREE.CubeTextureLoader()
  .setPath(`https://gg-web-demos.guraklgames.com/assets/fly-city/`)
  .load([
  'sky_nx.png', 'sky_px.png',
  'sky_py.png', 'sky_ny.png',
  'sky_pz.png', 'sky_nz.png',
]);
envMap.format = THREE.RGBAFormat;
envMap.mapping = THREE.CubeReflectionMapping;
scene.background = envMap;

function render(time) {
  requestAnimationFrame(render);
  renderer.render(scene, camera);
}
render();

// Resize
function resize() {
  width = window.innerWidth;
  height = window.innerHeight;
  camera.aspect = width / height;
  camera.updateProjectionMatrix();
  renderer.setSize(width, height);
}
window.addEventListener('resize', resize);

```

### Live example

[CodePen](https://codepen.io/Andrew-Gura-the-flexboxer/pen/ZENQpjR)

### Screenshots

0.163.0 
![Знімок_20240518_204900](https://github.com/mrdoob/three.js/assets/9253105/f9ea03f3-6336-4f03-ab3e-29fb00a03700)

0.164.0(1)
![Знімок_20240518_204920](https://github.com/mrdoob/three.js/assets/9253105/fb3511ae-839e-4efd-aa1b-7ecedd1b0861)

### Version

r164

### Device

Desktop

### Browser

Chrome

### OS

Linux

**Comment by WestLangley** [comment]
To clarify, the artifacts occur when zooming out.

If I set `preserveDrawingBuffer: false`, the artifacts disappear for me.

Could this have been introduced in #28118?

**Comment by Mugen87** [comment]
More simplified test case: https://jsfiddle.net/uwom15j7/1/

**Comment by Mugen87** [comment]
Strange, this issue also happens with `r163`: https://jsfiddle.net/yjxsed1f/

**Comment by Mugen87** [comment]
@AndyGura Why do you use `preserveDrawingBuffer: true` in your scene?

Did you maybe copy the code from an older demo and now update it to the latest `three.js` release?

**Comment by Mugen87** [comment]
> Or you mean that it was "hidden" somehow up until r164?

Yes. I suspect the same root cause but it was overshadowed up to `r164`. I believe the simplified fiddle would work, the original codepen would work, too.

**Comment by Mugen87** [comment]
I have eventually found the issue. It is indeed a regression!

Thanks for reporting the issue.
