### ISSUE TITLE
Editor keeps rendering video on background even if users had stopped it

### ISSUE THREAD

**Issue by ycw** [mrdoob/three.js#28454]
### Description

When users try to render video by pressing 'PROJECT>VIDEO>Render' in the editor, and then close the popup window in order to stop processing in the middle, editor will still go through the whole path until a mp4 is generated. This is absolutely wasteful.

I've tried to call [`ffmpeg.exit()`](https://github.com/ffmpegwasm/ffmpeg.wasm/blob/v0.10.1/docs/api.md#ffmpegexit) when popup window unloaded, however, it **won't** forbid ongoing API calls. :|

### Reproduction steps

1. Go https://raw.githack.com/mrdoob/three.js/dev/editor/index.html
2. Open console
3. Press PROJECT > VIDEO > RENDER
4. Close the popup window
5. You should see ffmpeg keeps logging(=running) in console.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r164

**Comment by Mugen87** [comment]
> You should see ffmpeg keeps logging(=running) in console.

It does but only the `run FS.writeFile` commands. The exit stops further processing so I would say it works as expected.

Notice that calling `ffmpeg.exit();` throws an exception :

> wa {name: 'ExitStatus', message: 'Program terminated with exit(1)', status: 1}

This exception should be catched and ignored to avoid confusion. For the same reason, I would also turn off logging of `ffmpeg` in general.

**Comment by Mugen87** [comment]
@ycw Using the `unloaded` event worked for me as well. Would you be willing to file a PR implementing your solution?

**Comment by aardgoose** [comment]
@ycy You could check the output.closed property in the for 'frame' loop and exit cleanly there to reduce console noise.

**Comment by ycw** [comment]
> The exit stops further processing so I would say it works as expected.

@Mugen87 The current behavior of `.exit()` is that ffmpeg will flush queued frames via generate empty frames(size=0), meaning that `exit` is scheduled and its account for cleanup. This behavior will trouble users who render a long duration video, even if the popup windows get closed instantly, it'll take times to flush queued frames. This mean that, repeating "press RENDER then close popup before mp4 delivered" will cause multiple ffmpeg instances hanging in the background, how long they last depends on video's frames count. 

FYI recent ffmpeg has added `terminate()` API. (editor depends of relatively old one, v0.10.1)

@aardgoose Polling `closed` can guard writing temporary `.png`, but it can't be used to stop `.run()` in the middle, this will cause the same abovementioned issue. 

FYI recent ffmpeg has added abort signal support for each almost all APIs.
