### ISSUE TITLE
No Pointer Lock

### ISSUE THREAD

**Issue by 2111875** [mrdoob/three.js#28453]
### Description

In the editor on the threejs website, there is no way to request pointer lock. I have tried every method on the docs, but I cant import anything. I cant use await/async because it says invalid identifier.

### Solution

A way to request pointer lock in the editor

### Alternatives

There is no possible alternatives because I need the camera lock for my game.

**Comment by Mugen87** [comment]
Please ask at the [forum](https://discourse.threejs.org/) for help.

**Comment by 2111875** [comment]
there is already a forum open of this post with no responses https://discourse.threejs.org/t/pointerlock-in-editor/57845
