### ISSUE TITLE
copyTextureToTexture using WebGL1 function signature

### ISSUE THREAD

**Issue by richfwebb** [mrdoob/three.js#28465]
### Description

Full description here:
https://discourse.threejs.org/t/error-from-copytexturetotexture-overload-resolution/65836/
https://jsfiddle.net/waqt65y7/

Summary:

WebGLRenderer's using a WebGL1 signature on line 2414 of WebGLRenderer.js in r160, renderer.copyTextureToTexture does:

```_gl.texSubImage2D( _gl.TEXTURE_2D, level, position.x, position.y, glFormat, glType, srcTexture.image );```
which is a WebGL1 signature that was removed in WebGL2 in place of:
texSubImage2D(target, level, xoffset, yoffset, width, height, format, type, pixels)
So it’s just missing the width and height parameters.

This seems like this might be an error, and is the cause of the error in the fiddle:
TypeError: Failed to execute ‘texSubImage2D’ on ‘WebGL2RenderingContext’: Overload resolution failed."

### Reproduction steps

1. Render to a target
2. Call render.copyTextureToTexture with the target.texture as the source
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/waqt65y7/
)

### Version

r0.160.0

### Device

Desktop

### Browser

Chrome

### OS

Linux

**Comment by Mugen87** [comment]
This issue is unrelated to WebGL 1. `texSubImage2D()` can't do what you are looking for. For copying data from a render target into a texture, you would use `copyTexSubImage2D()` which is available via `copyFramebufferToTexture()`.

**Comment by Mugen87** [comment]
This issue is unrelated to WebGL 1. `texSubImage2D()` can't do what you are looking for. For copying data from a render target into a texture use `copyTexSubImage2D()` which is available via `copyFramebufferToTexture()`.

**Comment by Mugen87** [comment]
As explained in this [OpenGL](https://registry.khronos.org/OpenGL-Refpages/es2.0/xhtml/glCopyTexSubImage2D.xml) reference, `texSubImage2D()` requires the data available on the client memory. This is not true when working with framebuffers (render targets). For that there is `copyTexSubImage2D()`.
