### ISSUE TITLE
Not displayed after importing 3MF and AMF files

### ISSUE THREAD

**Issue by kakalangdu** [mrdoob/three.js#28477]
### Description

Not displayed after importing 3MF and AMF files
Check whether the console output model has been loaded successfully and no error has been reported.

### Reproduction steps

 loadAMF() {
            
                const loader1 = new AMFLoader();
                loader1.load('/model/suhuaamf.AMF', object=> {
                    //  object.quaternion.setFromEuler(new THREE.Euler(-Math.PI / 2, 0, 0));
    
                    console.log("object",object);

                      this.scene.add(object);
                     
    
                      
                    })
                    console.log("this.scene",this.scene);
    
                }

### Code

 loadAMF() {
            
                const loader1 = new AMFLoader();
                loader1.load('/model/suhuaamf.AMF', object=> {
                    //  object.quaternion.setFromEuler(new THREE.Euler(-Math.PI / 2, 0, 0));
    
                    console.log("object",object);

                      this.scene.add(object);
                     
    
                      
                    })
                    console.log("this.scene",this.scene);
    
                }

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

![问题](https://github.com/mrdoob/three.js/assets/39682214/6add70fb-8567-4743-b2fc-19afc54fb17c)

### Version

r164

### Device

Desktop

### Browser

Edge

### OS

Windows

**Comment by mrdoob** [comment]
Please use one of the links below for help / support:

- [questions](https://stackoverflow.com/questions/tagged/three.js)
- [discord](https://discord.gg/56GBJwAnUS)
- [forum](https://discourse.threejs.org)
