### ISSUE TITLE
Documentation for TeapotGeometry (add-on)

### ISSUE THREAD

**Issue by hongchristopher** [mrdoob/three.js#28487]
### Description

I noticed that documentation for TeapotGeometry is missing. The path to this feature is ```examples/jsm/geometries/TeapotGeometry.js```

### Solution

I would like to create a fork, write some documentation for TeapotGeometry, and submit a PR. This would result in a new documentation file at ```docs/api/en/geometries/TeapotGeometry.html```. 

I plan to follow the guidelines set by https://github.com/mrdoob/three.js/blob/dev/docs/api/CONTRIBUTING.md and mirror the writing style of the other documentation pages!

### Alternatives

I have not considered alternatives for writing this documentation piece.

**Comment by Mugen87** [comment]
A contribution would be welcome. There are already some modules in `examples/jsm/geomtries` documented so it is probably best to copy one of those pages for `TeapotGeometry`.

`TeapotGeometry` has no own properties and methods so the constructor is the only relevant API to document.

**Comment by Mugen87** [comment]
Merging this issue into #27034.
