### ISSUE TITLE
Editor: Missing `User Data` input in Geometry tab

### ISSUE THREAD

**Issue by ycw** [mrdoob/three.js#28488]
### Description

Unlike Object/Material tabs, there's no input for `User Data`, not sure that this is intended or not.

### Reproduction steps

1. Opens https://threejs.org/editor/
2. Adds a Box
3. Select GEOMETRY property tab
4. You should not see User Data input in there

### Code

n/a

### Live example

n/a

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/1063018/c6e3e0fe-c35f-42b6-a196-86c5541d6d9b)

### Version

r164

**Comment by Mugen87** [comment]
I can't imagine a reason for excluding `userData` just for geometries. So it's probably just an oversight.
