### ISSUE TITLE
OrbitControls 's change Event  dispatch  wrong  when dampling is true

### ISSUE THREAD

**Issue by MrYang614** [mrdoob/three.js#28480]
### Description

In OrbitControls.js line 393
```
lastTargetPosition.distanceToSquared(scope.target) > 0
```

when the dampling is true , pan the controls , the value is always 1e-100  and my camera is static for a long time ,  then dispatch changeEvents all the time

I pull the code into my project , and change  to bolow code , FIXED 
```
lastTargetPosition.distanceToSquared(scope.target) > EPS 
```

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here

```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/107246452/dc76330d-ab92-47c4-81ca-51bc5b7d600c)

### Version

0.162

**Comment by Mugen87** [comment]
Isn't that already fixed via #27620?
