### ISSUE TITLE
Target is not updated when panning the camera in ArcballControls

### ISSUE THREAD

**Issue by Kosuke-KIDO-datalabs** [mrdoob/three.js#28524]
### Description

I want to save the current camera position and the center of rotation of the camera, but cannot get the center of rotation of the camera.
In OrbitControls, it seems that the target of controls is also updated when the camera is panned, but in ArcballControls, it is not updated, so I don't know where the current target is.

### Solution

Update target as in OrbitControls.

### Alternatives

Allow `_gizmos.position` to be retrieved.
Perhaps the center of rotation of the camera is consistent with _gizmos.position, so

**Comment by Mugen87** [comment]
Can't you just use `controls.target`?

**Comment by Mugen87** [comment]
> but in ArcballControls, it is not updated, so I don't know where the current target is.

It is not updated since the focus point (the "lookAt" target) of the controls does simply not change. That also means the center of rotation is equal. So it's correct to use `controls.target`.
