### ISSUE TITLE
TextureBinding includes writable usage and another usage in the same synchronisation scope

### ISSUE THREAD

**Issue by Spiri0** [mrdoob/three.js#28549]
### Description

It's about the use of renderTargets in WebGPU with the wgslFn node and the tslFn will certainly also affect.
If you render a texture with the renderTarget in every frame you cannot use it in the wgsl shader because a read/write conflict occurs.
I noticed this some time ago with the depthTextures, where the problem still exists. Now I wanted to use a normal rendered texture and then I encountered the problem again.
The problem can be easily demonstrate with little code.

The problem is that the renderTarget probably accesses the texture with readwrite. The renderTarget should only access the texture with write access and the shader only with read access to avoid this conflict.
With this issue, the renderTarget in WebGPU can only be used to a very limited extent and unfortunately I can't think of a sensible workaround.

### Reproduction steps

1.create a renderTarget and call it in the renderLoop
2.create a wgslFn shader for the colorNode or vertexNode
3.assign the renderTarget texture to the shader

### Code

```
import * as THREE from "https://esm.sh/three";
import {MeshBasicNodeMaterial, wgslFn, vec4, texture, attribute} from "https://esm.sh/three/nodes";
import {OrbitControls} from "https://esm.sh/three/addons/controls/OrbitControls.js";
import WebGPURenderer from "https://esm.sh/three/addons/renderers/webgpu/WebGPURenderer.js";

let renderTarget;

const renderer = new WebGPURenderer({antialias: true, forceWebGL: false});
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.setPixelRatio( window.devicePixelRatio );
renderer.setSize( window.innerWidth,window.innerHeight );
renderer.setClearColor( 0x000000 );
document.body.appendChild( renderer.domElement );

const camera = new THREE.PerspectiveCamera( 50.0, window.innerWidth/window.innerHeight, 1e-1, 1e6 );
const scene = new THREE.Scene();
scene.background = new THREE.Color( 0x00001f );

camera.position.set( 4, 4, 4 );

const controls = new OrbitControls( camera, renderer.domElement );

window.addEventListener( "resize", onWindowResize, false );
//-----------------------------------------------------------------

await init();
await render();

async function init() {
 
  const renderTargetParams = {
    format: THREE.RGBAFormat,
    type: THREE.FloatType
  }

  renderTarget = new THREE.RenderTarget(window.innerWidth, window.innerHeight, renderTargetParams);  
  
  const shaderParams = {
    uv: attribute("uv"),
    renderTargetTexture: texture(renderTarget.texture),
    renderTargetSampler: texture(renderTarget.texture)
  }
  
  const fragmentShader = wgslFn(`
    fn main_fragment(
      uv: vec2<f32>,
      renderTargetTexture: texture_2d<f32>,
      renderTargetSampler: sampler
    ) -> vec4<f32> {    
      return vec4<f32>(1, 0, 0, 1);
    }
  `);

  const material = new MeshBasicNodeMaterial();
  material.colorNode = fragmentShader(shaderParams);
  
  const geometry = new THREE.BoxGeometry( 1, 1, 1 );
  const box = new THREE.Mesh( geometry, material );
  scene.add( box ); 
}

async function computeRenderTarget() {
  renderer.setRenderTarget( renderTarget );
  await renderer.renderAsync( scene, camera );
  renderer.setRenderTarget( null );
}

async function render() {
  await computeRenderTarget();
  await renderer.renderAsync( scene, camera );
  
  requestAnimationFrame( render );
}

function onWindowResize() {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize( window.innerWidth, window.innerHeight );
}
```

### Live example

https://codepen.io/Spiri0/pen/oNRWBeJ?editors=0011

### Screenshots

![renderTargetIssue](https://github.com/mrdoob/three.js/assets/69024222/57410067-bad2-431a-b6ed-ede9557c4245)

### Version

r165

### Device

Desktop, Mobile

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows, Linux, Android

**Comment by aardgoose** [comment]
This is just the standard limitation that you can't render to a texture that you are reading from in the same pass, eg as in your ComputeRenderTarget() function, note the error is 'writable usage with **another** usage' so it doesn't matter if the other usage is read or write or both.  The same restriction applies to WebGL.

If you want to read and write to a texture in a single pass you will need the feature  #28531 which isn't merged yet.

**Comment by Spiri0** [comment]
Ah ok, learned something again. In WebGL I can do this with the renderTargets and the RawShader.  As far as I can see, #28531 affects the storageTexture. How would that help with the renderTargets?
In the fragment shader I can't write to a storageTexture with the textureStore. 

For the depthTexture I thought I could get it in the wgslFn instead of from a renderTarget with the depthTexture node and viewportDepthTexture node like in the webgpu_backdrop_water example but that only leads to the error message "not a THREE texture"

The issue "with the single pass" with the renderTarget and the wgslFn is an obstacle that has been bothering me for a longer time.
I've been working with the compute shaders and storageTextures since the beginning and it works very well for the wgslFn.

But for the depthTexture and for textures with the fragment shader, as far as I understand, I need the renderTarget to store textures for the wgslFn. Please correct me if I'm wrong.
And the renderTarget is a three.module.js object. Maybe a node equivalent of the renderTarget that can use the storageTexture makes sense? But I can't assess that.

**Comment by aardgoose** [comment]
Can you provide a demo of what you are doing in WebGL, reading from a texture that is bound to a render target isn't supported and you get should get texture feedback loop errors.

See the discussion re Unity:
https://forum.unity.com/threads/opengl-es3-0-shader-issue-texture-written-by-framebuffer.1099492/

**Comment by Spiri0** [comment]
Maybe my cloud repo would be a clear WebGL2 example. I render the depthTexture with the renderTarget and use it in a RawShaderMaterial.

https://github.com/Spiri0/volumetric-clouds

The src/main.js is quite simple. Does it help you?
Unfortunately, this doesn't work similarly with the RenderTarget and the wgslFn in WebGPU. Then comes the warning with the single pass.
I tried this months ago to get the depthTexture I need for my ocean2 repo which is also in github to make the water realistically transparent with scattering and see objects under the surface or the ground. Now this is causing me problems in another project where I need it for scattering the atmosphere.
And in addition I need a texture from the fragment shader as feedback for the vertex shader and for this I used the same method in WebGL2. I render to a RenderTarget and read into the RawShaderMaterial. 
I can meanwhile reproduce everything else with WebGPU what I made with WebGL2 and do much more with WebGPU thanks to the compute shaders.
But this hurdle with the RenderTarget has become a real problem for me.

**Comment by Spiri0** [comment]
The textureStore node was created back then r155/r156 precisely because of the same problem that I had with the compute shaders. Until then there was only the texture node and no storageTexture. @sunag then introduced the textureStore node and the StorageTexture so that I could write into textures with the compute shaders with the textureStore node and read them with the texture node in the fragment shader. 
I think this mechanism could also be useful for the RenderTarget, but this would require a RenderTarget in the Node system, as I find it difficult to imagine doing this with the RenderTarget in three.module.js. But now I'm just speculating. I don't understand the node system well enough for that.

**Comment by Spiri0** [comment]
@aardgoose: This works very well with the WebGLRenderTarget and the RawShaderMaterial as you see in the repo. But I can't tell from the WebGLRenderTarget code, it just inherits the RenderTarget and doesn't do much. This can't be the place where three.js handles it.
I use a pingpong mechanism in the ifft system in my ocean repo. Is it possible that the WebGLRenderer does something similar with framebuffers?
That the WebGLRenderer switch between framebuffers to avoid the conflict? Write to a framebuffer and assign the other framebuffer to the RenderTarget so that it can be read from and vice versa in the next run? Would this be a useful solution for WebGPU to solve this conflict? Then the WebGPURenderer would be the right place.
Maybe @sunag can also assess whether my thoughts are heading in a sensible direction.

**Comment by sunag** [comment]
@Spiri0 Have you tried using `viewportTexture` node?

**Comment by sunag** [comment]
Solved https://github.com/mrdoob/three.js/pull/28568#issuecomment-2156093937
