### ISSUE TITLE
[TSL] Invalid output, missing conversion of type in some cases

### ISSUE THREAD

**Issue by AlaricBaraou** [mrdoob/three.js#28546]
### Description

I can't tell for sure but I'm pretty sure this bug has been introduced in https://github.com/mrdoob/three.js/pull/27828

The early return when `nodeData.nodeProperty !== undefined` cause the node to not be converted in some cases.

### Reproduction steps

1. open https://threejs.org/examples/?q=tsl#webgpu_tsl_editor
2. paste this code in the editor 
```
const { vec2, vec4, clamp, float, cond } = TSL;

const minorTargetWidth = cond( true, float(0.01), float(0.01) );
const minorDrawWidth = clamp(vec2(minorTargetWidth), vec2(0.5), vec2(0.5));

const minorGrid3 = cond(true,minorDrawWidth,minorDrawWidth);

output = vec4( minorGrid3 );
```

3. The output is invalid

```
Error while parsing WGSL: :49:14 error: no matching call to 'clamp(f32, vec2<f32>, vec2<f32>)'

2 candidate functions:
 • 'clamp(vecN<T>  ✗ , vecN<T>  ✓ , vecN<T>  ✓ ) -> vecN<T>' where:
      ✓  'T' is 'abstract-float', 'abstract-int', 'f32', 'i32', 'u32' or 'f16'
 • 'clamp(T  ✓ , T  ✗ , T  ✗ ) -> T' where:
      ✓  'T' is 'abstract-float', 'abstract-int', 'f32', 'i32', 'u32' or 'f16'

    nodeVar0 = clamp( nodeVar1, vec2<f32>( 0.5, 0.5 ), vec2<f32>( 0.5, 0.5 ) );
```

output before the above PR https://github.com/mrdoob/three.js/pull/27828
Some duplicate code but valid and conform to what was written in the node
```
	if ( true ) {
		if ( true ) {
			nodeVar1 = 0.01;
		} else {
			nodeVar1 = 0.01;
		}
		nodeVar0 = clamp( vec2<f32>( f32( nodeVar1 ) ), vec2<f32>( 0.5, 0.5 ), vec2<f32>( 0.5, 0.5 ) );
	} else {
		if ( true ) {
			nodeVar2 = 0.01;
		} else {
			nodeVar2 = 0.01;
		}
		nodeVar0 = clamp( vec2<f32>( f32( nodeVar2 ) ), vec2<f32>( 0.5, 0.5 ), vec2<f32>( 0.5, 0.5 ) );
	}
```

output after the above PR https://github.com/mrdoob/three.js/pull/27828 
Some code run in a single branch instead of both and in the else we get `nodeVar1` instead of `vec2<f32>( f32( nodeVar1 ) )`
```
	if ( true ) {
		if ( true ) {
			nodeVar1 = 0.01;
		} else {
			nodeVar1 = 0.01;
		}
		nodeVar0 = clamp( vec2<f32>( f32( nodeVar1 ) ), vec2<f32>( 0.5, 0.5 ), vec2<f32>( 0.5, 0.5 ) );
	} else {
		nodeVar0 = clamp( nodeVar1, vec2<f32>( 0.5, 0.5 ), vec2<f32>( 0.5, 0.5 ) );
	}
```

@sunag happy to help with a PR but without tests or an example of what the PR I mentionned fix I don't know how to test against regression.
Would you be interested in a PR adding some tests ?

### Version

0.165.0

### Device

Desktop, Mobile, Headset

### Browser

Chrome, Firefox, Safari, Edge

### OS

Windows, MacOS, Linux, ChromeOS, Android, iOS

**Comment by sunag** [comment]
Thanks for reporting, I should replace the old implementation of `tempRead`, `tempWrite`, with a cache that can consider hierarchy, to access its predecessors, this would make the system more stable.
