### ISSUE TITLE
Uncaught (in promise) ReferenceError: Request is not defined

### ISSUE THREAD

**Issue by lingme** [mrdoob/three.js#28582]
### Description

My project is normal, but just now, I upgraded Threejs to 0.165.0, and the uncaut (in promise) Referenceerror: Request is not defined

my nodejs version is 20.14.0

![image](https://github.com/mrdoob/three.js/assets/32844254/f5a598e9-b0b5-4388-a921-b8890513fe33)
![image](https://github.com/mrdoob/three.js/assets/32844254/dc87dc8d-5eda-4fa2-9e19-acaf8501fd1a)
![image](https://github.com/mrdoob/three.js/assets/32844254/b12c353a-20e1-4203-915f-47715ff7286b)

### Reproduction steps

1. install threejs with yarn
2. import threejs
3. use GLTFLoader

### Code

```typescript
public loadCarModel = (): Promise<void> => {
		return new Promise<void>((resolve, _reject) => {
			loadGltf.load('./resources/models/car.glb', (glb) => {
				glb.scene.traverse((node) => {
					if (node instanceof THREE.Mesh) {
						node.name.includes('floor') && (node.receiveShadow = true);
					}
				});
				this.workStudio = glb.scene;
				scene.scene.add(glb.scene);
				resolve();
			});
		});
	};
```

### Live example

no live 

### Version

r0.165.0

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by donmccurdy** [comment]
The relevant code is here:

https://github.com/mrdoob/three.js/blob/7cb5fe43fa879d4fdc3e2de11873a534ec479606/src/loaders/FileLoader.js#L76-L81

three.js depends on various web APIs. For Node.js, you will likely need to use jsdom or another library to provide the web APIs you need. If there's a simple fix, please feel free to open a pull request. For help with upgrading your project or getting it to work in Node.js, please use the forums: https://discourse.threejs.org/ or Discord.

**Comment by lingme** [comment]
Thank you very much, I think I understand the problem, have a nice day
