### ISSUE TITLE
normal z-buffer #webgl_camera_logarithmicdepthbuffer rendering issues cross OS, gpu, browser

### ISSUE THREAD

**Issue by brierjon** [mrdoob/three.js#28581]
### Description

The normal z-buffer half of the threejs example [webgl_camera_logarithmicdepthbuffer example](https://github.com/mrdoob/three.js/blob/master/examples/webgl_camera_logarithmicdepthbuffer.html) after zooming out (by it zooming out itself or if the user uses their mouse to zoom out) results in artifacts being rendered on the normal z-buffer, but not the logarithmic z-buffer across multiple gpus and OS. I was looking into the [Firefox bug 1575211](https://bugzilla.mozilla.org/show_bug.cgi?id=1575211) to see if it was still an active issue and found the issue shown in the screenshots instead of the issue highlighted in the FF bug. Given it occurs across GPU and OS, filing here for investigation. Originally discussed in [Pop OS chat](https://chat.pop-os.org/pop-os/pl/s1d7ktwuab8nfj8bdprzk8rs4h).

### Reproduction steps

1. Visit https://threejs.org/examples/#webgl_camera_logarithmicdepthbuffer in Chrome or Firefox
2. Zoom out watching the normal z-buffer half of the screen
3. rendering artifacts occur across Windows/Linux across AMD, Intel, and NVidia gpus

### Code

https://github.com/mrdoob/three.js/blob/master/examples/webgl_camera_logarithmicdepthbuffer.html

Assuming latest version is what is live for reference if it changes - https://github.com/mrdoob/three.js/blob/027b25f35d512a77b373334d92e7c3820f6d5255/examples/webgl_camera_logarithmicdepthbuffer.html

### Live example

* [threejs.org/examples/#webgl_camera_logarithmicdepthbuffer](https://threejs.org/examples/#webgl_camera_logarithmicdepthbuffer)

### Screenshots

![image](https://github.com/mrdoob/three.js/assets/717866/180a2e44-0079-4299-8481-90da1ecd4c26)
![image](https://github.com/mrdoob/three.js/assets/717866/481c87f7-82ee-41fc-9ee8-84f2880be121)

### Version

??? - whatever is used in the example

### Device

Desktop, Mobile

### Browser

Chrome, Firefox

### OS

Windows, Linux, Android

**Comment by aardgoose** [comment]
The artefacts are illustrate why a logarithmic depth buffer is used in situations handling a large range of scales given that the depth buffer is usually 24bit, this isn't a bug, the example is designed to demonstrate the issues and the potential solution.

https://en.wikipedia.org/wiki/Z-fighting

**Comment by brierjon** [comment]
There is no text on the example that would lead someone to come to that conclusion. It merely looks like a comparison between normal and logrithmic z-buffer. The artifacts should be stated as expected behavior somewhere to make this a clear expected behavior.

**Comment by Mugen87** [comment]
The examples should demonstrate the features of the library. They are not intended as a learning material for computer graphics. We expect a certain degree of knowledge. 

Think about anti-aliasing: In the respective demos we also have side-to-side comparison and do not explain why on one side aliasing occurs and not on the other. The developer should know what MSAA or FXAA is and what issue it tries to solve. If that is not clear, the developer has to read up about the topic.

One simple Google search of "logarithmic depth buffer" reveals that it addresses z-fighting in large-scale scenes. With that bit in mind, the example `webgl_camera_logarithmicdepthbuffer` becomes self-explaining.
