### ISSUE TITLE
what happened？ How can I solve this problem?

### ISSUE THREAD

**Issue by lovewmf** [mrdoob/three.js#28598]
### Description

After scene toJSON, the image address is undefined

### Reproduction steps

![image](https://github.com/mrdoob/three.js/assets/27558071/039ab96b-505e-4cd6-9c3d-b30c93f3da84)

### Code

```js
 const path = new URL('/assets/draco/gltf/', import.meta.url).href
    const dracoLoader = new DRACOLoader();
    const ktx2Loader = new KTX2Loader();
    dracoLoader.setDecoderPath(path);
    dracoLoader.setDecoderConfig({ type: "js" });
    dracoLoader.preload();
    const loader = new GLTFLoader(manager);
    loader.setKTX2Loader(ktx2Loader);
    loader.setMeshoptDecoder(MeshoptDecoder);
    loader.setDRACOLoader(dracoLoader);
    loader.load(url,(res)=>{
        
        const result = res.scene.toJSON()
        console.log(result)
    });
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

0.165.0

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
Serialization/deserialization of compressed textures is not support, see #17974.
