### ISSUE TITLE
WebGPU: WebGPURenderer throws a DOMException error on a non-WebGPU browser

### ISSUE THREAD

**Issue by boytchev** [mrdoob/three.js#28623]
### Description

In the past whenever I try any WebGPU example on a non-WebGPU-enabled browser, there was a graceful message saying that the browser does not support WebGPU. With recent releases the execution breaks inside one of the imported modules, before showing this polite message. No warning or notice is shown in the web page for the user to see. The Javascript console shows this message:
```
Uncaught DOMException: WebGPU is not yet available in Release or Beta builds.
```
If static imports are used, it is impossible to `try...catch` such exceptions.

#### Historical notes
Tried to track releases and the exception happens in Three.js r153-r165. With Three.js r152 and earlier releases the import statements do not break.

#### Origin of exception
The exception is thrown by `await navigator.gpu.requestAdapter()`. In some releases this happens in `WebGPU.js`, in other releases it happens in `WebGPUBackend.js`.

#### Suggestions
* Capture the exception in the module, so that the user still gets some feedback that the browser is not WebGPU-ready.
* Provide info in the documentation what is the recommended way for the user to capture the exception (e.g. via dynamic imports, or some better approach)

#### Additional notes
The exception happens in my Firefox 126.0.1 (64-bit, Windows). It does not happen in my other browsers, because they have WebGPU support. I cannot confirm whether the issue happens in other non-WebGPU browsers.

### Reproduction steps

1. Run any example that has `import WebGPURenderer from 'three/addons/renderers/webgpu/WebGPURenderer.js';`
2. (alternatively you may run the life example with r165)
3. Observe the Javascript console whether there is exception that cancels the program execution

### Code

```js
import * as THREE from 'three';
import WebGPURenderer from 'three/addons/renderers/webgpu/WebGPURenderer.js';

console.log( '^..^' ); // this line is not reached
```

### Live example

* Example with r165 (execution fails): https://codepen.io/boytchev/pen/rNgGdxa?editors=0010
* Example with r152 (execution is OK): https://codepen.io/boytchev/pen/KKLXodY?editors=0010

### Screenshots

Snapshot from an official Three. example ([this one](https://threejs.org/examples/#webgpu_compute_texture)):

![image](https://github.com/mrdoob/three.js/assets/70705048/a4e78185-d494-4c32-a5ad-0728b485a916)

Snapshot from the failing live example with r165 (showing minimal code that triggers the breakage):

![image](https://github.com/mrdoob/three.js/assets/70705048/43f5b6d4-2c26-4d31-8a3f-1eb73667586f)

Snapshot from working live example with r152 (showing ^..^ in the console):

![image](https://github.com/mrdoob/three.js/assets/70705048/69d1e56a-a077-42cc-ad0a-083e5c1c0dd4)

### Version

r153-r165

### Device

Desktop

### Browser

Firefox

### OS

Windows

**Comment by sunag** [comment]
> The exception happens in my Firefox 126.0.1 (64-bit, Windows)

I tested it on Firefox 127.0 on Windows and didn't have the same issues, and the fallback was applied correctly: `THREE.WebGPURenderer: WebGPU is not available, running under WebGL2 backend.`

It seems that for some reason `navigator.gpu` is declared in your browser and is generating this error.

**Comment by boytchev** [comment]
Upgraded to 127.0. The issue still persist.

As it works on your Firefox, but not on mine, this hinted me to also check `about:config`. I found that when `dom.webgpu.enabled=true` the issue appears, when `dom.webgpu.enabled=false` it works as you described. In my previous tests the flag was `true`. I suspect that this flag forced Firefox to act as if it supports WebGPU, even if it cannot.

I'm happy to close the issue.
