### ISSUE TITLE
Improve GPUComputationRenderer performance by using fullscreen triangle

### ISSUE THREAD

**Issue by pedroalmeida415** [mrdoob/three.js#28635]
### Description

The current code for the GPUComputationRenderer class uses a square Plane geometry:
```javascript
class GPUComputationRenderer {
        constructor( sizeX, sizeY, renderer ) {
        .
        .
        .
>>>     const mesh = new Mesh( new PlaneGeometry( 2, 2 ), passThruShader );
``` 

### Solution

Change the geometry to use a fullscreen triangle:

```javascript
    const geometry = new BufferGeometry();

    // Triangle expressed in clip space coordinates
    const vertices = new Float32Array([
      -1.0, -1.0,
      3.0, -1.0,
      -1.0, 3.0
    ]);

    geometry.boundingSphere = new THREE.Sphere()
    geometry.boundingSphere.set(new THREE.Vector3(), Infinity)
    geometry.setAttribute('position', new THREE.BufferAttribute(vertices, 2))
    ...
    mesh.frustumCulled = false
``` 

### Alternatives

Since three.js doesn't offer support for WebGL1 anymore, an alternative is to bypass buffer attributes altogether and create the triangle directly into the vertex shader:

```javascript
// geometry setup
const geometry = new BufferGeometry();
geometry.setDrawRange(0, 3)

// pass through vertex shader
void main(void) {
    gl_Position.x = (gl_VertexID == 2) ?  3. : -1.;
    gl_Position.y = (gl_VertexID == 1) ? -3. : 1.;
    gl_Position.zw = vec2(1.);
}
``` 

Both methods were tested locally and work as expected.

### Additional context

Quoting [pmndrs/postprocessing](https://github.com/pmndrs/postprocessing#performance)

> All fullscreen render operations also use a [single triangle](https://michaldrobot.com/2014/04/01/gcn-execution-patterns-in-full-screen-passes/) that fills the screen. Compared to using a quad, this approach harmonizes with modern GPU rasterization patterns and eliminates unnecessary fragment calculations along the screen diagonal. This is especially beneficial for GPGPU passes and effects that use complex fragment shaders.

**Comment by Mugen87** [comment]
There is already a [FullScreenQuad](https://github.com/mrdoob/three.js/blob/f1f9a1c78eef798cb3296f7257fee5507af529bc/examples/jsm/postprocessing/Pass.js#L61C7-L61C21) class in the repository used for post processing. I guess it can also be used in `GPUComputationRenderer`.

**Comment by pedroalmeida415** [comment]
@Mugen87 Seems like the FullscreenQuad is a little outdated as well, would you mind if I opened a PR to update the implementation there?

**Comment by Mugen87** [comment]
Do you mind explaining what parts of the code you want to update? E.g. the above vertex definition in clip space isn't ideal in my opinion since we officially do not support 2D vertex data.
