### ISSUE TITLE
Bug Collision detection anomaly

### ISSUE THREAD

**Issue by MAFLIXD** [mrdoob/three.js#28661]
### Description

the collision detection fails almost every six seconds.

### Reproduction steps

1.
2.
3.
the collision detection fails almost every six seconds.

### Code

```js
// code goes here
```
the collision detection fails almost every six seconds.

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)
the collision detection fails almost every six seconds.

### Screenshots

the collision detection fails almost every six seconds.

### Version

the collision detection fails almost every six seconds.

**Comment by RenaudRohlinger** [comment]
Duplicated with #28660
