### ISSUE TITLE
games_fps Example: Collision detection anomaly

### ISSUE THREAD

**Issue by Jinxishihenian** [mrdoob/three.js#28660]
### Description

In the games_fps example, when the player is stationary, the collision detection fails almost every six seconds.

### Reproduction steps

In 'https://threejs.org/examples/?q=gam#games_fps' the player stands still and the octree outputs the result of the collision.

### Code

```js
	function playerCollisions() {

		const result = worldOctree.capsuleIntersect(playerCollider);
		// When the player is stationary on the ground, it triggers almost every six seconds or so
		if (!result) {
			console.log('fail');
		}
	 
		playerOnFloor = false;

		if (result) {
	 
			playerOnFloor = result.normal.y >= 0;

			if (!playerOnFloor) {

				playerVelocity.addScaledVector(result.normal, -result.normal.dot(playerVelocity));

			}

			playerCollider.translate(result.normal.multiplyScalar(result.depth));

		}
 
	}
```

### Live example

![111](https://github.com/mrdoob/three.js/assets/44466363/96a6ae43-9860-47ba-bb7b-dfa3ae031a7d)

### Version

0.165.0

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
I'm unable to reproduce the issue with Chrome on macOS. `fail` is only logged at the very beginning of the app when player is still in the air. But as soon as the player is on the ground, there are no additional logs (unless you jump or fall down a platform).

**Comment by ycw** [comment]
It's reproducible when player idles on ramp for a while

**Comment by Mugen87** [comment]
Oh, now I can reproduce as well.

**Comment by Jinxishihenian** [comment]
Very efficient efficiency, thank you very much
