### ISSUE TITLE
GLTFLoader.loadAsync unclear error should clearly state file not found

### ISSUE THREAD

**Issue by pedzed** [mrdoob/three.js#28678]
### Description

When I load a file that does not exist using `GLTFLoader.loadAsync`, I get:

```console
Uncaught (in promise) SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at GLTFLoader.parse (GLTFLoader.js:350:17)
    at Object.onLoad (GLTFLoader.js:245:11)
    at three.module.js:44019:38
```

### Solution

It would help understanding the problem a developer faces if error messages are clearly pointing out what's wrong.

### Alternatives

Wrapping it in a try-catch block and rethrowing is a possibility.

```ts
try {
    const gltf = await loader.loadAsync(filePath);
    return new this(gltf.scene);
} catch (e) {
    throw new Error(`Something went wrong upon loading model '${filePath}'. Does it exist?`);
}
```

**Comment by gkjohnson** [comment]
> Unexpected token '<', "<!doctype "... is not valid JSON

If you're getting this error then it means your server is providing some kind of default HTML for the request and likely not returning an error code the way it should.

**Comment by pedzed** [comment]
I am using Vite and running my dev server through `npm run dev`, nothing out of the ordinary.

Since [Vite is suggested in the docs](https://threejs.org/docs/index.html#manual/en/introduction/Installation), I think it's a good to make sure that error messages are not as vague as this.

**Comment by donmccurdy** [comment]
I can't seem to find anything in Vite's configuration to have it return an HTTP 404 for a missing file like `/not-a-real-folder/scene.glb`, it always seems to return `index.html` (if it exists) with an HTTP 200. That's unfortunate, and would be good feedback for Vite in my opinion. That said, I do think Vite is still the best tool to recommend in the introduction.

Another option is to put models in the `src/` folder and let Vite handle resolving the source path and moving it to the build folder. This also allows using [Vite plugins](https://github.com/nytimes/rd-bundler-3d-plugins?tab=readme-ov-file#3-asset-placement) to optimize the 3D files. But this approach is more specialized to Vite, and may not work in other bundlers, so I'm not sure we should advise it in the introduction at this time.
