### ISSUE TITLE
Should a function be added to distinguish between WebGPU and WebGL in order to run different code?

### ISSUE THREAD

**Issue by z4122** [mrdoob/three.js#28731]
### Description

In the new implementation of WebGPU and WebGL code in jsm, they share the same code in the xxxNode.js files. This makes some code difficult to implement in order to maintain compatibility with different backends. Should a function be added, such as:
``` 
 if (isWebGLBackEnd()) {}

``` 
or 
```
if (getCurrentBackEnd() === 'WebGL') {}
```
to allow us to write different code in the xxxNode.js files?

### Solution

Add 
``` 
 if (isWebGLBackEnd()) {}

``` 
or 
```
if (getCurrentBackEnd() === 'WebGL') {}
```

### Alternatives

None

**Comment by RenaudRohlinger** [comment]
Currently you could use `builder.isFlipY()` as a reference to determine if which backend is running (WebGPU or WebGL).

```js

if (builder.isFlipY() === true) {
  // webgl
} else {
  // webgpu
 }
```

**Comment by Mugen87** [comment]
>  This makes some code difficult to implement in order to maintain compatibility with different backends.

Do you mind explaining on what code you are referring to?

**Comment by z4122** [comment]
> > This makes some code difficult to implement in order to maintain compatibility with different backends.
> 
> Do you mind explaining on what code you are referring to?

Yeah. For example in my PR #28726. 
In WebGPU, we can use bindGroup to upload instanceMatrix to gpu directly, but in WebGL, we need to consider use attribute for compatibility. 
If I can judge which backend it is, I can implement them in different way.

**Comment by Mugen87** [comment]
In this case, a more dedicated method than `isFlipY()` is more readable, imo. `isWebGPU()` as suggested above sounds good to me.
