### ISSUE TITLE
THREE.Line missing morphTargets

### ISSUE THREAD

**Issue by jonobr1** [mrdoob/three.js#2875]
I took the [morphTargets](http://mrdoob.github.com/three.js/examples/webgl_morphtargets.html) example and tried to swap a `THREE.Mesh` with a `THREE.Line`. I got the below errors.

![Screen Shot 2013-01-02 at 2 00 36 PM](https://f.cloud.github.com/assets/220033/39411/e574b6ac-5527-11e2-8997-0391d37dbd51.png)

An example of this can be found [here](http://dl.dropbox.com/u/1595444/experiments/Three.js/THREE-Line-morphTarget.html). I expected it to work because previously I had used `THREE.Line` and `THREE.Mesh` interchangeably. I went looking through the source and `THREE.Line` doesn't look like it has any of the initialization logic for morphTargets that `THREE.Mesh` has.

So I think it's missing and I'm requesting that it be added. Is it as simple as adding these properties to `THREE.Line`?

```
this.morphTargetBase = -1;
this.morphTargetForcedOrder = [];
this.morphTargetInfluences = [];
this.morphTargetDictionary = {};
```

Finally, I'm running Chrome stable on OS X 10.8.2

**Comment by tonymihay** [comment]
Hi there!
I also need this feature. As a workaround I rerender the line in loop, but it's a kind of dirty hack and has performance issues.
