### ISSUE TITLE
WebGPU MeshBatch Example not working

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#28782]
### Description

I got a blue screen on : https://threejs.org/examples/?q=batch#webgpu_mesh_batch
And a warning in the console : `AttributeNode: Vertex attribute "batchId" not found on geometry.`
No problem on other webgpu demo.

### Reproduction steps

1. open https://threejs.org/examples/?q=batch#webgpu_mesh_batch

### Code

none

### Live example

https://threejs.org/examples/?q=batch#webgpu_mesh_batch

### Version

r166

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
This has already been fixed on `dev`, see #28757.
