### ISSUE TITLE
Instanced Buffer Attribute - Can’t set from onBeforeRender callback

### ISSUE THREAD

**Issue by Alforofous** [mrdoob/three.js#28797]
### Description

Can't seem to set InstancedBufferAttribute from onBeforeRender callback to InstancedMesh.

Issue discussed in greater length here: https://discourse.threejs.org/t/instanced-buffer-attribute-cant-set-from-onbeforerender-callback/67548

### Reproduction steps

1. Create InstancedMesh
2. Create InstancedBufferAttribute for that mesh
3. create a function that uses geometry.setAttribute(...) to set created attribute to created instanced mesh, but only from inside onBeforeRender function. 

### Code

import { OrbitControls } from "@three-ts/orbit-controls";
import * as THREE from "three";

const vertexShader = `
attribute float aDrawingColorId;
varying float vColorId;

void main() {
    vColorId = aDrawingColorId;
    mat4 matrix = mat4(1.0);
    matrix *= projectionMatrix;
    matrix *= modelViewMatrix;
#ifdef USE_INSTANCING
    matrix *= instanceMatrix;
#endif
    gl_Position = matrix * vec4(position, 1.0);
}
`;

const fragmentShader = `
varying float vColorId;

vec3 uintToVec3Color(uint id) {
    uint r = id >> 16u;
    uint g = (id >> 8u) & 0xffu;
    uint b = id & 0xffu;
    return vec3(float(r) / 255.0, float(g) / 255.0, float(b) / 255.0);
}

void main() {
    vec3 color = uintToVec3Color(uint(vColorId));
    gl_FragColor = vec4(color, 1.0);
}
`;

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera();
const renderer = new THREE.WebGLRenderer();
renderer.setSize(window.innerWidth, window.innerHeight);
document.body.appendChild(renderer.domElement);
const orbit = new OrbitControls(camera, renderer.domElement);

const geometry = new THREE.BoxGeometry(1, 1, 1);
const material = new THREE.ShaderMaterial({
  vertexShader,
  fragmentShader,
});

const instanceCount = 255;
const instancedMesh = new THREE.InstancedMesh(
  geometry,
  material,
  instanceCount
);

const offset = 1.5;
for (let i = 0; i < instanceCount; i++) {
  const matrix = new THREE.Matrix4();
  matrix.setPosition(i * offset, 0, 0);
  instancedMesh.setMatrixAt(i, matrix);
}

scene.add(instancedMesh);

const grid = new THREE.GridHelper(30, 20);
scene.add(grid);

const attributes: THREE.InstancedBufferAttribute[] = [];
for (let i = 0; i < 5; i++) {
  const newArray = new Float32Array(instanceCount);
  for (let j = 0; j < instanceCount; j++) {
    newArray[j] = Math.random() * (255 << 16);
  }
  const newAttribute = new THREE.InstancedBufferAttribute(newArray, 1);
  attributes.push(newAttribute);
  newAttribute.needsUpdate = true;
}

let currentIndex = 0;
/* instancedMesh.geometry.setAttribute(
  "aDrawingColorId",
  attributes[currentIndex]
); */
instancedMesh.onBeforeRender = (
  renderer: THREE.WebGLRenderer,
  scene: THREE.Scene,
  camera: THREE.Camera,
  geometry: THREE.BufferGeometry,
  material: THREE.Material,
  group: THREE.Group
) => {
  instancedMesh.geometry.setAttribute(
    "aDrawingColorId",
    attributes[currentIndex]
  );
  attributes[currentIndex].needsUpdate = true;
};

camera.position.z = 10;

function animate() {
  requestAnimationFrame(animate);
  renderer.render(scene, camera);
}

animate();

### Live example

https://codesandbox.io/p/sandbox/idmaterial-test-forked-55x2nj?file=%2Fsrc%2Findex.ts%3A1%2C1-107%2C1

### Version

0.165.0

### Device

Desktop

### Browser

Chrome, Edge

### OS

Windows, MacOS

**Comment by Mugen87** [comment]
`onBeforeRender()`  does not work for this use case.

Your code can be considered as invalid since you create buggy state inside the renderer. Attribute data are updated before rendering happens but the VAO when the object is actually rendered. By changing the geometry during the rendering process, the internal state gets out of sync.

You should be able to fix the issue by rendering the object initially with all attributes. Then you can update the data.

In this case, I recommend you do not use `setAttribute()` like in your code. Use `setAttribute()` _once_ when creating the geometry and then just update its buffer data. And avoid doing this in `onBeforeRender()`.
