### ISSUE TITLE
EffectComposer/Transmission: Using scene.background with a texture and having an EffectComposer breaks transmission rendering

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#28796]
### Description

It looks like there's a depth clear issue (?) when using a scene background together with EffectComposer when transmissive objects are rendered.

The result is that only the background is visible in transmission, not the scene content. Sometimes parts of the scene content are visible but then "disappear" (thus my assumption that this is related to some depth buffer not being cleared correctly).

### Reproduction steps

1. Go to https://jsfiddle.net/0zLhsk3u/103/
2. Rotate the camera a bit (first frame likely works because depth buffer is empty before!)
3. Note that the grey object is not visible in the transmission
  <img width="412" alt="image" src="https://github.com/mrdoob/three.js/assets/2693840/11c801ed-a53d-4a56-a331-ea5ccf52f0d8">. 
4. Press "F" which will switch from a background texture to a background color. 
6. Note that the dark green sphere is visible in transmission again. 
  <img width="430" alt="image" src="https://github.com/mrdoob/three.js/assets/2693840/ed604aa0-7f0e-4eac-a30e-dae68da29646">. 
7. Press "F" again to switch to background texture again (dark green sphere disappears from transmission)
8. Press "C to disable the EffectComposer
9. Note that the dark green sphere is visible again

So this combination breaks: 
- **Background texture + EffectComposer + Transmission**

### Code

See https://jsfiddle.net/0zLhsk3u/103/

### Live example

https://jsfiddle.net/0zLhsk3u/103/

### Version

r167dev

**Comment by Mugen87** [comment]
This is a regression since the demo works up to `r164`: https://jsfiddle.net/Lrvkd0s1/

It starts breaking with `r165` which contains a fix for another transmission issue: #28420

I suspect the fix has a side effect that is the root cause for this issue.

**Comment by Mugen87** [comment]
The PR #28434 fixed an issue in context of color spaces in `r165`. #28447 tried to optimized the code but introudced this regression. I'll revert the PR.

**Comment by hybridherbst** [comment]
Thank you!
