### ISSUE TITLE
When Three.js Version bigger than 164, the shadowMap cant be cache,This leads to a decrease in rendering performance,

### ISSUE THREAD

**Issue by liuyehua** [mrdoob/three.js#28804]
### Description

When Three.js Version bigger than 164, the shadowMap cant be cache,This leads to a decrease in rendering performance,

when Three.js Version less than 164, when I render shadowMap, I will set “renderer.shadowMap.enabled = false” after first render, 

such as:
    render = () => {
        this.stats.update();
        this.composer.render();
        **this.renderer.shadowMap.enabled = false;**
    }

the next time the shadowMap persist，This can significantly improve the performance of rendering shadows
But in 165,166 I can not do it…

**Comment by lanvada** [comment]
I think controlling the update of the `ShadowMap` should be done using the `renderer.shadowMap.autoUpdate` and `renderer.shadowMap.needsUpdate` properties.

**Comment by Mugen87** [comment]
I can't reproduce the issue: https://jsfiddle.net/2xqta8sc/1/

As @lanvada said, don't use `shadowMap.enabled` for this use case. There are dedicated properties for controlling the update.
