### ISSUE TITLE
Error encountered when cloning a BatchedMesh: Uncaught TypeError: this._matricesTexture.image.slice is not a function

### ISSUE THREAD

**Issue by lanvada** [mrdoob/three.js#28803]
### Description

While attempting to clone a BatchedMesh, I encountered the following error: Uncaught TypeError: this._matricesTexture.image.slice is not a function.

I noticed that the BatchedMesh source code contains the following lines:

```js
...
// Line 930
this._matricesTexture.image.data = this._matricesTexture.image.slice();
...
// Line 935
this._colorsTexture.image.data = this._colorsTexture.image.slice();
...
```

During debugging, I observed that the `data` property of `image` is a `TypedArray`, but `image` itself does not have a `slice()` method. I am wondering if `image.slice()` should be modified to `image.data.slice()`?

### Reproduction steps

Clone a BatchedMesh

### Code

none

### Live example

none

### Version

r166

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by lanvada** [comment]
I don't quite understand what the data structure of Image is, and whether it is only the Image in the DataTexture created in BatchedMesh that does not have the Slice method

**Comment by ShakhriddinAx** [comment]
It’s good that you noticed, there really should be an `image.data.slice()` here to clone texture data.

**Comment by Shakhriddin** [comment]
It’s good that you noticed, there really should be an image.data.slice() here to clone texture data.
