### ISSUE TITLE
WebGLRenderer: UBO / Uniform Buffer Object - Vec2 is not binded correctly.

### ISSUE THREAD

**Issue by dghez** [mrdoob/three.js#28818]
### Description

I'm trying to give a go to `UBO / UniformBufferObject` but I noticed one weird thing.
I'm setting a vec2 but looks like is keeping only one value (y) and set the other to 0
```js
globalUniforms.resolution = new Uniform(new Vector2(11, 33))
globalUniforms.add(globalUniforms.resolution)
```

But if you check the screenshot, it's correct as vec2 of floats but as you can notice values are 33 and 0, instead of 11 and 33
<img width="202" alt="image" src="https://github.com/mrdoob/three.js/assets/6367879/82c0c58e-f829-48fd-ab5c-b5a897127ddf">

After that i tried to bind a `Vector3` and so far is binded correctly 
```js
globalUniforms.resolution = new Uniform(new Vector3(11, 33, 77))
globalUniforms.add(globalUniforms.resolution)
```

<img width="231" alt="image" src="https://github.com/mrdoob/three.js/assets/6367879/55dbc64b-e62c-4ff4-bae7-2724668d72da">

### Reproduction steps

See above, explained in details

### Code

```js
// code goes here
```

### Live example

* [LIVE-LINK](https://stackblitz.com/edit/vitejs-vite-z3emzj?file=main.js)

### Version

0.166.0

### Device

Desktop, Mobile

### Browser

Chrome, Firefox

### OS

MacOS

**Comment by AlaricBaraou** [comment]
I tried to reproduce on chrome under windows on this example https://threejs.org/examples/webgl_ubo.html 
But I don't have the issue.
![CaptureCode](https://github.com/mrdoob/three.js/assets/7174039/69516783-45fe-48c9-94ed-407ec8f83ddf)
![DebugVec2](https://github.com/mrdoob/three.js/assets/7174039/0f00bdb3-1922-44c6-9c2f-d5756d51ebf2)

**Comment by dghez** [comment]
@AlaricBaraou Weird, any chance to share a live version of that? Might be an hardware issue? I deffo don't think so, but you never know.
Gonna try to create a standalone demo as soon as i have 5 min :)

**Comment by dghez** [comment]
Ok, @AlaricBaraou was able to recreate on a stackblitz (not jsfiddle because i couldn't run spector).
**LINK: https://stackblitz.com/edit/vitejs-vite-z3emzj?file=main.js**

------
So, if I set ONLY the resolution is binded correctly 
```js
    const globalUniforms = new THREE.UniformsGroup();
    globalUniforms.setName('Global');
    globalUniforms.resolution = new THREE.Uniform(new THREE.Vector2(11, 33));
    globalUniforms.add(globalUniforms.resolution);
  ```
  
<img width="351" alt="image" src="https://github.com/mrdoob/three.js/assets/6367879/59f94e9e-ca95-4890-86e3-c4707e966a52">

------
If i add a float before is not working
```js
  const globalUniforms = new THREE.UniformsGroup();
  globalUniforms.setName('Global');
  globalUniforms.time = new THREE.Uniform(0);
  globalUniforms.add(globalUniforms.time);
  globalUniforms.resolution = new THREE.Uniform(new THREE.Vector2(11, 33));
  globalUniforms.add(globalUniforms.resolution);
  ```
<img width="216" alt="image" src="https://github.com/mrdoob/three.js/assets/6367879/a2757b79-b9c6-4598-854e-b8ee89cabb38">

------

IF i switch the order, so resolution THEN time is binded correctly
<img width="360" alt="image" src="https://github.com/mrdoob/three.js/assets/6367879/caf5e288-2f37-43e9-a9af-4234701a7973">

------
I'm not that skilled into native API but i guess the issue is coming from the offset. Looking at the time>resolution example, the VEC2 is binded with an `offset of 8` where it should be `offset 4`, and doing that by 8 essentially is skipping the first value. That makes sense if you think about the fact that if the vec2 is `11,33` is binded `33,0` so essentially shifted by 1 offset.  Hope is understandable ahah

**Comment by dghez** [comment]
I guess i'm wrong because after some researches looks like `8` is the correct place because everything is organised by chunks of 4 spot and vec2 can occupy only the first two OR the last two, not in the middle. 
So i guess it's correct in our case like `[float][null][vec2float1][vec2float2]` but looks like is like in our case `[0][11][33][null]` or better `[time][resolution.x][resolution.y][null]` but when access the data it takes correctly the last two.
So i guess is how we are packing, the write is wrong, the read is correct.

PS: I'm not 100% familiar on native API so please take this with a pinch of salt, might be completely wrong. Hopefully a smarter mind can clear the issue 😆

**Comment by dghez** [comment]
On top of that @AlaricBaraou in your case is working because you are using 4 vec3 and a float that occupy 4 chunks, so the vec2 is in the new chunk, first two slots

```js

lightingUniformsGroup.add( new THREE.Uniform( new THREE.Vector3( 0, 0, 10 ) ) ); // light position
lightingUniformsGroup.add( new THREE.Uniform( new THREE.Color( 0x7c7c7c ) ) ); // ambient color
lightingUniformsGroup.add( new THREE.Uniform( new THREE.Color( 0xd5d5d5 ) ) ); // diffuse color
lightingUniformsGroup.add( new THREE.Uniform( new THREE.Color( 0xe7e7e7 ) ) ); // specular color
lightingUniformsGroup.add( new THREE.Uniform( 64 ) ); // shininess
lightingUniformsGroup.add( new THREE.Uniform( new THREE.Vector2(1,2 ) ); // debug
```


So in chunks
```
[light.x][light.y][light.z][null] // OFFSET:0
[ambient.x][ambient.y][ambient.z][null] //  OFFSET:16
[diffuse.x][diffuse.y][diffuse.z][null] //  OFFSET:32 
[specular.x][specular.y][specular.z][shininess] //  OFFSET:48
[debug.x][debug.y][null][null] //  OFFSET:64
```

**Comment by Mugen87** [comment]
I think the issue is that the the `vec2` data start at the wrong location in the buffer. Normally a 8 byte boundary is required but that is currently ignored. So instead of:
```
4 byte (time) | 8 byte (resolution)
```
the buffer should be:
```
4 byte (time) | 4 byte (padding) | 8 byte (resolution)
```

**Comment by dghez** [comment]
@Mugen87 yeah, you summarized it in 2 lines rather than my explanations that took a lot 😂😂
