### ISSUE TITLE
Scene/Camera Jitter when open in Meta Quest Browser

### ISSUE THREAD

**Issue by mdengmc** [mrdoob/three.js#28835]
### Description

Simply open the example scene: `https://threejs.org/examples/#webgl_animation_keyframes` from Meta Quest browser in Meta Quest 2 and use controllers to drag the scene.

I've uploaded a video to show the jitter - not sure what exactly was going on. It could actually be a bug of the device rather than THREE.js. Video of the jitter: `https://www.youtube.com/watch?v=hEha6OoYvyA`, pretty horrible. :( 

I've also opened a thread in Meta Support Forum. However just in case someone from here who is actively making web apps for Meta Quest with THREE happen to know this issue, so I would also like to duplicate this issue here.

One hint is, the jitter seems only easy to reproduce when the `Passthrough` mode is turned `on`.

Let me know if anyone knows anything about it.

Appreciate so much!

### Reproduction steps

1. Open Meta Quest Browser
2. Navigate to URL: https://threejs.org/examples/#webgl_animation_keyframes
3. Use controllers to drag the scene

### Code

```js
// just open the official sample scene from meta quest browser: https://threejs.org/examples/#webgl_animation_keyframes
```

### Live example

* [issue-video](https://www.youtube.com/watch?v=hEha6OoYvyA)

### Version

166

**Comment by Mugen87** [comment]
I can reproduce the issue with a Quest 2 and Oculus browser. It seems the judder only occurs when the camera is moved. With a static camera, the scene renders as expected.

Since this also happens with other 3D engines like BabylonJS (use https://playground.babylonjs.com/#3I55DK#0 for testing), this is not a three.js specific issue.

Please continue the discussion at the Meta forum.

**Comment by cabanier** [comment]
@mdengmc I'll investigate why this is happening. On my Q3, there is no jitter.

**Comment by cabanier** [comment]
@mdengmc I can only reproduce if passthrough is turned off. Can you verify it's the same for you?
We suspect that the home environment is adding enough overhead that complex shaders in WebGL get overloaded. I forwarded this test case to our graphics team to see if they can get rid of the jitter.

**Comment by mdengmc** [comment]
> @mdengmc I can only reproduce if passthrough is turned off. Can you verify it's the same for you? We suspect that the home environment is adding enough overhead that complex shaders in WebGL get overloaded. I forwarded this test case to our graphics team to see if they can get rid of the jitter.

Hi! Thanks for your investigation! Yea I mentioned it in the description, the `passthrough` mode matters (in the original description I wrote "passthrough on" to reproduce, that was a mistake, embarrassed.  So yes I'm seeing exactly the same - jitter happen when passthrough is turned off.  Sometimes, the headset put me into `travel mode` which can get rid of the jitter as well, but this is not as consistent as setting `passthrough`.

Regarding the overload suspect, you mentioned no jitter on Q3, probably due to better hardware specs. Talking about the performance, the Quest 2 actually renders pretty fast, frame rate even higher than my PC browser (intel i7-12700H, 32G ram, no dedicated GPU) for some larger scenes. I'm wondering if Meta used any special optimizations that could mess up the frame sync or anything, but I'm no expert at all in the rendering theory.  

Again thank you so much for the effort!
