### ISSUE TITLE
Clipping not updated for `RawShaderMaterial` after first render.

### ISSUE THREAD

**Issue by joarfish** [mrdoob/three.js#28836]
### Description

Apparently, it is not possible to set clipping planes for `RawShaderMaterial` or `ShaderMaterial` after they have been used for rendering. When setting up the planes before the material is used to render a mesh, clipping works.

Looking at the code of threejs, it seems to me that the underlying program is not recreated when the `clippingPlanes` is set, which in turn does not replace the `NUM_CLIPPING_PLANES` placeholder of the corresponding clipping related chunks.

### Reproduction steps

1. Make sure the renderer is set up to apply local clipping (`localClippingEnabled = true`)
2. Create a simple `RawShaderMaterial` (e.g. just rendering a box) and set the `clipping` property to `true`
3. Set the clipping planes via `material.clippingPlanes = [...]` after the material has been used to render a mesh

### Code

```js
// ...

const geometry = new THREE.BoxGeometry();

const material = new THREE.RawShaderMaterial( {
    vertexShader: ```
        precision mediump float;
        uniform mat4 modelViewMatrix;
        uniform mat4 projectionMatrix;

        attribute vec3 position;
      
        #include <clipping_planes_pars_vertex>

        void main()	{
                vec3 mvPosition = (modelViewMatrix * vec4(position, 1.0)).xyz;
                #include <clipping_planes_vertex>
                gl_Position = projectionMatrix * vec4( mvPosition, 1.0 );
        }
    ```,
    fragmentShader: ```
        precision mediump float;  
        #include <clipping_planes_pars_fragment>

        void main()	{
      	        #include <clipping_planes_fragment>
                gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
        }
    ```,
    side: THREE.DoubleSide,
    clipping: true,
});

// Clip material after some seconds
setTimeout(() => {
    material.clippingPlanes = [
        new THREE.Plane(new THREE.Vector3(0, -1, 0), 0.1)
    ];
    material.needsUpdate = true;
}, 3000);
       
const mesh = new THREE.Mesh( geometry, material );
scene.add(mesh);
// ...
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/jd1tm6a8/105/)

### Version

r166

**Comment by Mugen87** [comment]
It does work with `ShaderMaterial`: https://jsfiddle.net/5ewqkhj4/

The shader cache key computation is strictly simplified for `RawShaderMaterial` and requires developer input via `customProgramCacheKey()` depending on what you are doing.

I suggest you use `ShaderMaterial` which is better intended for this use case.
