### ISSUE TITLE
Clear only certain stencil bits

### ISSUE THREAD

**Issue by OndrejSpanel** [mrdoob/three.js#28843]
### Description

Tangentially related to #26737

When using stencil to display something per-object like in https://threejs.org/examples/webgl_clipping_stencil.html, one wants to clear the stencil after the object is done:

```js
					po.onAfterRender = function ( renderer ) {

						renderer.clearStencil();

					};
```

In real application only certain bits can be used for the effect in question which other bits are used for something else and should be left untouched. For this one would like to set the stencil mask before clearing it.

### Solution

At the moment color and alpha can be controlled by calls `setClearColor` and `setClearAlpha`. I suggeest adding `setClearStencil` and `setClearStencilMask` to control stencil buffer value and mask used on the clear.

### Alternatives

One can clear the stencil bit by rendering a fullscreen quad with carefully crafted stencil settings of the material. This cannot be used in `onAfterRender` thought, instead one needs to play with render order of the quad and the effect object to make sure the are rendered after each other.

### Additional context

I can try preparing a PR if the functionality looks acceptable.

**Comment by Mugen87** [comment]
Can you just set the stencil mask via:
```js
renderer.state.buffers.stencil.setMask( 0xffffffff );
``` 
`WebGLState` is public on purpose since special components require access to the WebGL state e.g. `MaskPass`.

I'm hesitate a bit with `setClearStencil()` and `setClearStencilMask()` have never been requested in 14 years of `three.js`. Stencil is more comparable with depth which has no `setClear*()` methods on renderer level as well.

**Comment by OndrejSpanel** [comment]
Thanks for the advice, I will check if I can achieve what I want using `renderer.state.buffers.stencil`, I was not sure about this option, as this is not much documented (of it it is, I do not know where).

**Comment by OndrejSpanel** [comment]
I can call `renderer.state.buffers.stencil.setMask`, but how do I perform the clear? Normal `renderer.clear` resets the mask (and rightly so) and I do not see other way to call `gl.clear`.

**Comment by OndrejSpanel** [comment]
Using `buffers.stencil` and `getContext()` works well enough.
