### ISSUE TITLE
Three.js outlinePass add-on not working when implemented with R3F

### ISSUE THREAD

**Issue by MiguelG97** [mrdoob/three.js#28855]
### Description

https://stackoverflow.com/questions/78738437/three-js-outlinepass-add-on-not-working-when-implemented-with-r3f

### Reproduction steps

Sandbox code:
(https://codesandbox.io/p/sandbox/r3f-outlinepass-vdvhm8)

### Code

(https://codesandbox.io/p/sandbox/r3f-outlinepass-vdvhm8)

### Live example

(https://codesandbox.io/p/sandbox/r3f-outlinepass-vdvhm8)

### Version

0.163.0

### Device

Desktop

### Browser

Chrome

**Comment by donmccurdy** [comment]
We use GitHub issues for bug reports about the three.js library itself — for help with three.js and related projects like R3F, please try:

- [questions](https://stackoverflow.com/questions/tagged/three.js)
- [discord](https://discord.gg/56GBJwAnUS)
- [forum](https://discourse.threejs.org/)
