### ISSUE TITLE
Parcel build addons.js fails due to SVGRenderer double definition

### ISSUE THREAD

**Issue by psytron** [mrdoob/three.js#28858]
### Description

```
 npx parcel build --dist-dir ./three_app.html 
🚨 Build failed.

@parcel/optimizer-swc: the name `SVGRenderer` is defined multiple times

/three/addons.js:84412:0
    84411 | 
  > 84412 | SVGCompElement.prototype.createComp = function (data) {
  >       | ^
    84413 |   return new SVGCompElement(data, this.globalData, this);
    84414 | };
```

### Reproduction steps

1. utilize three.js in project
2. run parcel build three_app.html

### Code

```js
// def 1 line 84416
function SVGRenderer(animationItem, config) {

// def 2 line 144786
class SVGRenderer {
```

### Live example

its on local server during build process

### Version

R165

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
> function SVGRenderer(animationItem, config) {

This line is from `lottie_canvas.module.js` . However, the library does not export its internal `SVGRenderer` so this seems like a Parcel issue to me.
