### ISSUE TITLE
TSL: Array of vectors as uniform.

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#28878]
### Description

For the port of `PoissonDenoiseShader` it's necessary to pass an array of `vec3` into the shader. Can this be done with `uniform()` already? Something like:
```js
this.vectors = uniform( [ new Vector3( 1, 0, 0 ), new Vector3( 0, 1, 0 ), new Vector3( 0, 0, 1 ) ]  );
```

The above code produces the following runtime error when I try to access a vector via ` this.vectors.element( i )`.

> Error: Uniform "null" not declared.

**Comment by cmhhelgeson** [comment]
Unless I'm mistaken, I believe the uniforms() functionality allows you to do this?

https://github.com/mrdoob/three.js/pull/27706

**Comment by Mugen87** [comment]
`uniforms()` does the trick!

**Comment by Mugen87** [comment]
> I'm not sure there's a reason the end user would want to differentiate between using uniform() or uniforms().

That's indeed a good point.
