### ISSUE TITLE
GLTF Export Optimization

### ISSUE THREAD

**Issue by myznikovgleb** [mrdoob/three.js#28887]
### Description

I've been receiving a warning concerning optimization of the canvas for readback operations while GLTFExporter's parse method is running. According to the warning, a `getContext` call should contain a `willReadFrequently` context attribute set true. Details are [here](https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently)

It seems like GLTFExporter's source code is missing any context attributes with `getContext` calls
https://github.com/mrdoob/three.js/blob/master/examples/jsm/exporters/GLTFExporter.js#L874
https://github.com/mrdoob/three.js/blob/master/examples/jsm/exporters/GLTFExporter.js#L1276

### Solution

If there are no obstacles, let's add `willReadFrequently` context attributes set true for every `getContext` call inside GLTFExporter's source code

### Alternatives

None for now

**Comment by Mugen87** [comment]
When I understand the spec correctly,  it makes sense to set `willReadFrequently` to `true` in the exporter since the canvas elements are never used for rendering but for processing image data which are then read back.

Do you want to file a PR with the suggested change?

**Comment by myznikovgleb** [comment]
Yes, I do. It seems to be an easy one
