### ISSUE TITLE
Nodes: Line2NodeMaterial dash mode broken

### ISSUE THREAD

**Issue by aardgoose** [mrdoob/three.js#28884]
### Description

The PR #28585 appears to have broken Line2NodeMaterial. Reverting the PR fixes the error.

In dashed mode, the fragment shader fails to compile with the error in 

https://github.com/mrdoob/three.js/blob/0679c557066907c19659697deaa3d2d0b0c7e724/src/nodes/materials/Line2NodeMaterial.js#L269

If the multiplications within the cond() expression are removed, the shader compiles as expected.

### Reproduction steps

1. run the example webgpu_lines_fat
2. select 'dashed' to enable dashed line mode.

### Code

n/a

### Live example

[Line2NodeMaterials example](https://threejs.org/examples/?q=fat#webgpu_lines_fat)

### Version

166

**Comment by Mugen87** [comment]
I had a few issues with `cond()` as well when porting code to TSL. Out of curiosity, does it work if this is used instead?
```js
const lineDistance = float( 0 );

If( positionGeometry.y.lessThan( 0.5 ) ), () => {

    lineDistance.assign( dashScaleNode.mul( instanceDistanceStart ) );

} ).else( () => {

    lineDistance.assign( materialLineScale.mul( instanceDistanceEnd ) );

} );
```

**Comment by aardgoose** [comment]
Yes and no (with a float( 0 ).toVar();

It doesn't produce an invalid shader, but doesn't work as expected. Presumably because If() uses cond() internally.

**Comment by Mugen87** [comment]
Oh yeah, the `toVar()` is required in this case.

In any event, this was just intended as a possible workaround. Of course it's best to make the normal `cond()` usage work.

**Comment by Mugen87** [comment]
If change the following line in `ConditionalNode.setup()`:

https://github.com/mrdoob/three.js/blob/35127e2517c5d0ffe374539abeeabf611d429ad8/src/nodes/math/ConditionalNode.js#L47
to
```js
const ifNode = this.ifNode;
```
the dash mode works again. 

So there is indeed an issue in context of caching. I was not able to further track down the root cause yet but it seems the code uses invalid cache data when generating the shader for the dash mode.
