### ISSUE TITLE
WebGPURenderer error loading GLTF

### ISSUE THREAD

**Issue by Jinxishihenian** [mrdoob/three.js#28898]
### Description

When I load my glb file with THREE.WebGLRenderer, the console gets an error and doesn't show up, while WebGLRenderer works fine
![Snipaste_2024-07-17_08-34-32](https://github.com/user-attachments/assets/5feedf73-e99e-4c83-94a9-6278b4109632)

My glb file
[glb.zip](https://github.com/user-attachments/files/16257850/glb.zip)

### Reproduction steps

1.When I load my glb file using THREE.WebGLRenderer, the glb shows up normally.
2.After switching to WebGPURenderer, glb is not displayed and the console reports an error.

### Code

Normal：
```js
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>THREE.js Parallel Light Shadows</title>
    <style>
        body {
            margin: 0;
        }

        canvas {
            display: block;
        }
    </style>
</head>
<body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/three@0.128/examples/js/loaders/GLTFLoader.js"></script>
</head>

<script>
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
    const renderer = new THREE.WebGLRenderer();
    renderer.setSize(window.innerWidth, window.innerHeight);
    document.body.appendChild(renderer.domElement);
    const directionalLight = new THREE.DirectionalLight(0xffffff, 10);
    // 半球光.
    const fillLight = new THREE.HemisphereLight(0xffffff, 0xffffff, 1);
    scene.add(directionalLight);
    scene.add(fillLight);
    const loader = new THREE.GLTFLoader();
    loader.load(
        'http://192.168.1.37:5173/assets/gltfs/nvyishenghunhe.glb', // 替换为你的 GLB 文件的 URL
        function (gltf) {
            const model = gltf.scene;
            scene.add(model);
            animate(); // Start the animation loop once the model is loaded
        },
        function (xhr) {
            console.log((xhr.loaded / xhr.total * 100) + '% loaded');
        },
        function (error) {
            console.error('An error happened', error);
        }
    );

    const helper = new THREE.CameraHelper(directionalLight.shadow.camera);
    scene.add(helper);


    camera.position.set(0, 0, 5);
    camera.lookAt(0, 0, 0);

    // Animation loop
    function animate() {
        requestAnimationFrame(animate);

        renderer.render(scene, camera);
    }

    animate();
</script>
</body>
</html>

```
![nor](https://github.com/user-attachments/assets/c4348c79-ed8a-4c37-a98b-d6f6d4b8b149)

### Version

0.166.1

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by donmccurdy** [comment]
@Jinxishihenian the code snippet above shows three.js r128, which would be considerably too old to support WebGPURenderer, could you confirm that you are using only imports from three.js r166? The model appears to be working correctly in WebGPURenderer in my local tests.

**Comment by Jinxishihenian** [comment]
> @Jinxishihenian上面的代码片段显示了 three.js r128，它太旧了，无法支持 WebGPURenderer，您能否确认您只使用了来自 three.js r166 的导入？在我的本地测试中，该模型似乎在 WebGPURenderer 中正常运行。
Yes, I'm using the 166 version
This is a dependency in my real project
![Snipaste_2024-07-17_10-19-17](https://github.com/user-attachments/assets/b426ff26-d41c-4328-9423-bdd8d939d820)

**Comment by WestLangley** [comment]
@donmccurdy, does the model render for you with `WebGPURenderer` and the WebGL backend? It does not for me. No console errors.

**Comment by donmccurdy** [comment]
Ah I see, yes if I force the WebGL backend it fails here as well. The problem appears to be related to the vertex attribute format. If I convert the attributes to float32, it renders correctly:

```bash
gltf-transform dequantize in.glb out.glb
```

The original vertex attribute types are:

COLOR_0:u16_norm, JOINTS_0:u8, NORMAL:f32, POSITION:f32, TEXCOORD_0:f32, WEIGHTS_0:f32

**Comment by Jinxishihenian** [comment]
> 我明白了，是的，如果我强制使用 WebGL 后端，它也会失败。问题似乎与顶点属性格式有关。未发现 glTF 验证错误。如果我将属性转换为 float32，它会正确呈现：
> 
> ```shell
> gltf-transform dequantize in.glb out.glb
> ```
> 
> 原始顶点属性类型为：
> 
> COLOR_0：u16_norm，JOINTS_0：u8，正常：f32，位置：f32，TEXCOORD_0：f32，WEIGHTS_0：f32
Thanks, this action solved my problem
