### ISSUE TITLE
Json Parsing changes for Shape/Path/Curves subclasses' CurrentPoint 

### ISSUE THREAD

**Issue by darint916** [mrdoob/three.js#28905]
### Description

fromJson/toJson in Path.js has currentPoint being interpreted from Vector2's fromArray, which doesn't really follow how currentPoint is actually defined if replicating Vector2 class itself. Where it is an object with x and y property.
Currently creating data objects in C# backend in which currentPoints was setup like vector2. People who want to create their own json format of the object will have their data structure slightly different.

### Solution

In the inheritance chain from Curve.js for classes that are taking in arrays to turn into Vector2 in the toJson and fromJson methods and change them to assume that the json is taken in as a vector object with property x, y instead of being a length 2 vector.

### Alternatives

Keep current convention and hopefully an explanation for why it's being read as an array instead.

### Additional context

I get that it is a closed loop with toJson and fromJson, but in some cases people need to optimize for performance and create all the data objects server side, which is serialized to JSON over api requests.

If this change is encouraged, I can make the changes for a PR.

**Comment by Mugen87** [comment]
All vector and matrix objects are stored as arrays when serialized into JSON. The following shows how this is done for the model matrix and up vector.

https://github.com/mrdoob/three.js/blob/ffef51075d125234079aaa494f9da1066f3d3e77/src/core/Object3D.js#L718-L719

It is clear from the object's context what type properties have so it makes no sense to additionally save type information.

I understand your use case but I personally see processing the internal Object/Scene JSON format in different programming language as an edge case. Hence, there is no compelling reason to change the JSON and break backwards compatibilty.
