### ISSUE TITLE
Editor lights are not exported correctly to GLB

### ISSUE THREAD

**Issue by bergden-resonai** [mrdoob/three.js#28908]
### Description

Ambient light reverts to Object3D when saved as a GLB, Directional lights have a weird behavior regarding the direction they're facing
When I move the directional light it's always pointing towards the Origin (this is a desired behavior? I can't rotate the directional light because of this), upon saving the GLB the light gets back the default quaternion

### Reproduction steps

1. Open the editor - https://threejs.org/editor/
2. Add an Ambient light and a Directional light (optionally some Mesh)
3. Export as GLB
4. Reload the GLB - the Ambient light became a regular Object3D and the Directional light lost its direction

### Code

-

### Live example

https://threejs.org/editor/

### Screenshots

https://github.com/user-attachments/assets/2ac14c8f-4f1e-46c6-928c-d54ac2b837d0

### Version

r166

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
> When I move the directional light it's always pointing towards the Origin (this is a desired behavior?

Yes, directional lights and spot lights are targeted by default. There is an issue to make the target transformable in the editor, see #9508.

glTF does only support punctual lights so ambient lights are no valid part of the scene when exporting to glTF.  You should actually see a warning in the browser console that says:

> 'THREE.GLTFExporter: Only directional, point, and spot lights are supported.'

**Comment by Mugen87** [comment]
Merging the issue into #28868 9508 and #5079.
