### ISSUE TITLE
CDN es6 module import requires importmap (Vanilla JS)

### ISSUE THREAD

**Issue by jikkuatwork** [mrdoob/three.js#28919]
### Description

I am trying to use threejs in a vanilla page using es6 imports. But its weird that the latest version doesn't work without importmap! Weirdly an old version's importmap also works!

Check these examples:

1. [Old Version without importmap](https://codepen.io/jikkuatwork/pen/YzowBXY?editors=0010)
2. [New Version that requires importmap](https://codepen.io/jikkuatwork/pen/PorNzaZ?editors=0011)

Also the same code produces starkly different renders, any suggestions?

Note: I am following a no-bundle workflow. I am wondering is it designed with the implicit assumption that it will be used with a bundling system?

### Reproduction steps

I have setup two examples with different versions. Please check.

### Code

```js
import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.166.1/build/three.module.min.js"
import { OrbitControls } from "https://cdn.jsdelivr.net/npm/three@0.166.1/examples/jsm/controls/OrbitControls.js"
```

### Live example

https://codepen.io/jikkuatwork/pen/PorNzaZ?editors=0011
https://codepen.io/jikkuatwork/pen/YzowBXY?editors=0010

### Version

0.166.1

**Comment by Mugen87** [comment]
An import map is required otherwise addons like `OrbitControls` can't resolve the `three` bare module modifier. This has been changed on purpose so we can use a unified import approach in the library.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.
