### ISSUE TITLE
examples/webgpu_morphtargets_face.html uses rgba32-float filtering textures without checking feature

### ISSUE THREAD

**Issue by mwyrzykowski** [mrdoob/three.js#28921]
### Description

Apologies in advance if bug reports are not appropriate for samples.

Float32 filtering is an optional feature in WebGPU: https://www.w3.org/TR/webgpu/#float32-filterable and it is not available on all devices, specifically most iPhones which include a preview for WebGPU support in the iOS 18 developer betas.

It appears the webgpu - morph targets - face example (https://threejs.org/examples/?q=webgpu#webgpu_morphtargets_face) does not fall back to rgba16float textures when the feature is not supported

### Reproduction steps

1. Enable WebGPU on iOS 18 beta via Settings.app -> Apps -> Safari -> Advanced -> Feature Flags -> WebGPU
2. Open https://threejs.org/examples/?q=webgpu#webgpu_morphtargets_face
3. If the device is an iPhone 15 Pro or recent iPad, any one which where -[MTLDevice supports32BitFloatFiltering] returns true, the sample loads correctly
4. If the device is an iPhone 15 (non-Pro) or earlier, any non-M Apple8 device or earlier from https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf the sample is empty

### Code

See code from https://threejs.org/examples/?q=webgpu#webgpu_morphtargets_face

### Live example

https://threejs.org/examples/?q=webgpu#webgpu_morphtargets_face

### Version

live version from samples website

### Device

Mobile

### Browser

Safari

### OS

iOS

**Comment by mwyrzykowski** [comment]
This appears to impact  https://threejs.org/examples/?q=webgpu#webgpu_instancing_morph as well

**Comment by Mugen87** [comment]
`WebGLRenderer` relies on a FP32 morph texture as well, see:

https://github.com/mrdoob/three.js/blob/5d5eb01c27df8fa2f520b76bbe7825b43641fe47/src/renderers/webgl/WebGLMorphtargets.js#L50-L54

`WebGPURenderer` has just copied the texture setup from `WebGLRenderer` so it is not surprising that devices with no FP32 texture support do not support morph target related example code.

Out of curiosity: The [WebGL version](https://threejs.org/examples/webgl_morphtargets_face) of the face demo runs as expected with Safari in iOS, right?

**Comment by mwyrzykowski** [comment]
The WebGL one works as expected. I could be wrong, but it looks like it fails WebGPU validation due to the GPUBindGroupLayout for the float32 texture being specified as:
```
"binding": 3,
"visibility": 1,
"texture": {
  "viewDimension": "2d-array"
}
```
but the corresponding shader only performs reads on the texture so filtering is not needed. 

The default value for [GPUTextureBindingLayout ](https://www.w3.org/TR/webgpu/#dictdef-gputexturebindinglayout).[sampleType](https://www.w3.org/TR/webgpu/#dom-gputexturebindinglayout-sampletype) is [float](https://www.w3.org/TR/webgpu/#dom-gputexturesampletype-float)

I think if the BindGroupLayout was specified like:

```
"binding": 3,
"visibility": 1,
"texture": {
  "sampleType": "unfilterable-float"
  "viewDimension": "2d-array",
}
```

the samples would work on devices which do not support float32-filterable

**Comment by Mugen87** [comment]
Sounds good! Would you be open for a PR?

**Comment by Mugen87** [comment]
Strange, it seems we are using `UnfilterableFloat` by default:

https://github.com/mrdoob/three.js/blob/4e4baddc8d961a949f452ef8d8382eb903319c76/src/renderers/webgpu/utils/WebGPUBindingUtils.js#L96-L100

**Comment by Mugen87** [comment]
Maybe it's because of this line:

https://github.com/mrdoob/three.js/blob/4e4baddc8d961a949f452ef8d8382eb903319c76/src/renderers/webgpu/utils/WebGPUBindingUtils.js#L84

We only define the sample type for data textures but not data array textures. Can you please verify if the following would fix the issue:
```js
 } else if ( binding.texture.isDataTexture || binding.texture.isDataArrayTexture ) { 
```

**Comment by mwyrzykowski** [comment]
I confirmed that worked. I disabled float32-filterable locally in WebKit so I could test on macOS and ran the three.js samples locally. Would you be able to make the PR for three.js with that change @Mugen87?
