### ISSUE TITLE
Chinese document copy error

### ISSUE THREAD

**Issue by qianmo1022** [mrdoob/three.js#28934]
### Description

Chinese document text error.It should be "对于大多数用户而言" , not "对于大多数用户而已"

### Reproduction steps

OPEN this URL: https://threejs.org/docs/index.html#manual/zh/introduction/Installation

Catalogue：安装->方案 1：使用 NPM 和构建工具进行安装->开发

Path:docs/manual/zh/introduction/Installation.html

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

![bugIssues](https://github.com/user-attachments/assets/b795261a-c6c0-4189-9a1c-b7924ffede56)

### Version

the last

**Comment by Mugen87** [comment]
Would you like to open a PR with your suggested change?
