### ISSUE TITLE
WebGPURenderer: errors thrown

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#28933]
### Description

In the `webgpu_materials.html` example, it renders, freezes, throws errors, and then repeats...

<img width="801" alt="Screenshot 2024-07-21 at 7 07 45 PM" src="https://github.com/user-attachments/assets/c5813a4b-18e0-47e4-9454-bd85ee7d07a5">

### Reproduction steps

https://threejs.org/examples/webgpu_materials.html

### Code

```js
```

### Live example

https://threejs.org/examples/webgpu_materials.html

### Version

r166 master, r167 dev

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
It seems this regression was introduced with `r166`. The example works with `r165`:

https://rawcdn.githack.com/mrdoob/three.js/r165/examples/webgpu_materials.html

**Comment by Mugen87** [comment]
After some testing the example starts to break with #28705.
