### ISSUE TITLE
Using GLBufferAttribute with InterleavedBufferAttribute

### ISSUE THREAD

**Issue by nkallen** [mrdoob/three.js#28948]
### Description

GLBufferAttribute allows the user to explicitly manage a GPU buffer (using `gl.bufferSubData`) without needing to maintain a source array on the javascript heap. It's useful in particular when you have a large amount of data that the user wants explicit control over for better performance. It can currently be used for vertex attributes like position or as an index, but not as the data backing `InterleavedBufferAttribute` -- although this is a simple change.

In Plasticity I am using it with BatchedMesh and I am now also using it with LineSegments2, which is where I would like this change.

### Solution

In `WebGLAttributes.js` the check `.isGLBufferAttribute` needs to be repeated after `if ( attribute.isInterleavedBufferAttribute ) attribute = attribute.data;`

In particular, this code just needs to be repeated:

```
		if ( attribute.isGLBufferAttribute ) {

			const cached = buffers.get( attribute );

			if ( ! cached || cached.version < attribute.version ) {

				buffers.set( attribute, {
					buffer: attribute.buffer,
					type: attribute.type,
					bytesPerElement: attribute.elementSize,
					version: attribute.version
				} );

			}

			return;

		}
```

### Alternatives

I'm not aware of any alternatives

### Additional context

I am also using this helper class in Plasticity, but I do not think it is necessary to add it to threejs:

```
class InstancedInterleavedGLBuffer extends THREE.GLBufferAttribute { // conforms to THREE.InstancedInterleavedBuffer
    isInstancedInterleavedBuffer = true;
    stride: number;
    meshPerAttribute: number;

    constructor(buffer: WebGLBuffer,
        type: GLenum, itemSize: number, elementSize: 1 | 2 | 4, count: number,
        stride: number, meshPerAttribute = 1,
    ) {
        super(buffer, type, itemSize, elementSize, count);

        this.stride = stride;
        this.meshPerAttribute = meshPerAttribute;
    }
}

```

**Comment by Mugen87** [comment]
> In WebGLAttributes.js the check .isGLBufferAttribute needs to be repeated after if ( attribute.isInterleavedBufferAttribute ) attribute = attribute.data;

Instead of repeating, isn't it possible to switch both statements? Meaning:

```js
if ( attribute.isInterleavedBufferAttribute ) attribute = attribute.data;

if ( attribute.isGLBufferAttribute ) {

	const cached = buffers.get( attribute );

	if ( ! cached || cached.version < attribute.version ) {

		buffers.set( attribute, {
			buffer: attribute.buffer,
			type: attribute.type,
			bytesPerElement: attribute.elementSize,
			version: attribute.version
		} );

	}

	return;

}
```

**Comment by nkallen** [comment]
Even better!!

**Comment by Mugen87** [comment]
That's great! Feel free to make a PR then.
