### ISSUE TITLE
Transformations and Cloning for Shapes and Curves

### ISSUE THREAD

**Issue by darint916** [mrdoob/three.js#28949]
### Description

Add transformation and cloning functions for the Shape class hierarchy, extending to paths, curves ect. Where transformation on the shape propagates down through all of the components that make it up.

### Solution

Provide Deep transform and clone functions to essentially apply transformation (rotation, translation, and potentially mirroring) and a clone function to duplicate it for transformation. This would be applied to all the different curves, curvepath, path, shape.

### Alternatives

Use instanced mesh style 4x4 transformation matrix to apply to the shape.

### Additional context

Would like to transform the shape before creating a shape buffer geometry or extruded geometry for further manipulation in other libraries. And/or creating a base shape to merge with another shape. Transforming at this level would make it more efficient than having to create all the way to the mesh and transforming it there.

**Comment by Mugen87** [comment]
I understand your use case but I'm afraid this feature request is out of scope. 

Feel free to implement a separate project that provides helper modules for transforming existing curve definitions. But something like that is just too specific for the main repository.
