### ISSUE TITLE
NodeCache breaking change with offscreenCanvas in WebGPURenderer and Point Light

### ISSUE THREAD

**Issue by seancheno** [mrdoob/three.js#28950]
### Description

Since updating our Three version to the latest 0.166.1 version, we are getting a breaking reference error `ReferenceError: parent is not defined` when using an offscreenCanvas with the WebGPURenderer and then adding to our scene anything that uses the NodeCache such as compute shaders or a point light (directional light works fine)

The error occurs in the CacheNode.js file ->

```
	build( builder, ...params ) {

		const previousCache = builder.getCache();
		const cache = builder.getCacheFromNode( this, parent ); // PARENT IS UNDEFINED

		builder.setCache( cache );

		const data = this.node.build( builder, ...params );

		builder.setCache( previousCache );

		return data;
	}
```

In a previous version or Three (0.164.1), this parent reference did not exist in the CacheNode file and we did not get this error.

As a workaround if we remove parent from `const cache = builder.getCacheFromNode( this, parent )` the error is bypassed but we are not sure what side effects this may cause.

The issue occurs on both mac and windows machines, as well as mobile devices.

I hope this is enough info to illustrate the issue, and am happy to provide any additional info needed. Thank you. 

### Reproduction steps

1. Create an offscreen canvas from HTMLCanvas -> `const offscreenCanvas = canvas.transferControlToOffscreen();`
2. Create a WebGPURenderer using the offscreenCanvas -> 
```
this.mainRenderer = new WebGPURenderer({
            antialias: true,
            canvas: offscreenCanvas,
            alpha: true,
});
```
3. Add a point light to the scene.

Fairly certain about this reproducibility.

### Code

```
	build( builder, ...params ) {

		const previousCache = builder.getCache();
		const cache = builder.getCacheFromNode( this, parent ); // PARENT IS UNDEFINED

		builder.setCache( cache );

		const data = this.node.build( builder, ...params );

		builder.setCache( previousCache );

		return data;
	}
```

### Live example

NA

### Screenshots

![Screenshot 2024-07-23 at 12 38 18 PM](https://github.com/user-attachments/assets/5168c6f4-5134-42e8-94d3-fa3231ccc0d3)
![Screenshot 2024-07-23 at 12 38 06 PM](https://github.com/user-attachments/assets/120130f1-fa9e-43cb-9e8f-ad7c5e6b728d)

### Version

0.166.1

**Comment by Mugen87** [comment]
I can't explain myself how the mentioned runtime error should be caused by the type of canvas.

Do you mind trying to demonstrate the issue with a live example and a normal canvas? Try it with this fiddle which has a latest WebGPU setup: https://jsfiddle.net/gxrye3k8/3/

**Comment by seancheno** [comment]
I have spent the last few hours trying to reproduce and am unable to.

main.js
```

const canvas = document.getElementById('canvas');

let supportOffScreenWebGL = 'transferControlToOffscreen' in canvas;

if (supportOffScreenWebGL) {
    console.log("OffscreenCanvas is supported");

    const offscreen = canvas.transferControlToOffscreen();
    const worker = new Worker('worker.js', { type: 'module' });

    offscreen.width = canvas.width;
    offscreen.height = canvas.height;

    worker.onmessage = (e) => console.log("Main thread received message from worker:", e.data);
    worker.onerror = (e) => console.error("Worker error:", e.message);

    worker.postMessage({
        drawingSurface: offscreen,
        width: canvas.clientWidth,
        height: canvas.clientHeight,
        pixelRatio: window.devicePixelRatio
    }, [offscreen]);

    console.log("Message posted to worker");
} else {
    document.getElementById('message').style.display = 'block';
    console.log("OffscreenCanvas is not supported");
}
```


worker.js

```
import * as THREE from "https://raw.githack.com/mrdoob/three.js/dev/build/three.webgpu.js";

self.onmessage = function (event) {
  console.log("Worker received message");

  const { drawingSurface, width, height, pixelRatio } = event.data;

  const scene = new THREE.Scene();
  scene.background = new THREE.Color(0x000000);

  const camera = new THREE.PerspectiveCamera(45, width / height, 0.25, 20);
  camera.position.set(-1.8, 0.6, 2.7);

  const geometry = new THREE.BoxGeometry();
  const material = new THREE.MeshBasicNodeMaterial({ color: 0x00ff00 });
  const mesh = new THREE.Mesh(geometry, material);
  scene.add(mesh);

  const renderer = new THREE.WebGPURenderer({
    canvas: drawingSurface,
    antialias: true,
    alpha: true,
  });

  // Add a point light to the scene
  const pointLight = new THREE.PointLight(0xffffff, 1, 100);
  pointLight.position.set(1, 1, 5);
  scene.add(pointLight);

  function animate() {
    mesh.rotation.x += 0.01;
    mesh.rotation.y += 0.01;
    renderer.render(scene, camera);
    requestAnimationFrame(animate);
  }

  animate();
  console.log("Animation started");
};

```

This runs fine. The issue must be buried deep within our own system. I will close this for now, and reopen if I'm able to reproduce. Sorry for any time you may have spent thinking about this issue, I will ensure I reproduce next time before posting any issues.

**Comment by ulyssesdotcodes** [comment]
Getting a consistent error here: https://nodysseus.io/#@example.compute

Looking at the code - where does `parent` come from in this context?

**Comment by ulyssesdotcodes** [comment]
I do not get an error with OffscreenCanvas on a non-worker. Is there something setting `window.parent` maybe that doesn't get set in a worker's `self`?

**Comment by ulyssesdotcodes** [comment]
<img width="582" alt="image" src="https://github.com/user-attachments/assets/b7042da4-9ad3-4719-8051-20391557f3ae">

Well, that's fun. Can I change it to this.parent?
