### ISSUE TITLE
How to load obj models with group information

### ISSUE THREAD

**Issue by Sunwinds** [mrdoob/three.js#2898]
Hi All, I am trying to use the ObjLoader.js to load OBJ pre-segmented models. Each segment is tagged as a group in the OBJ file.
But the current  ObjLoader.js seems not so capable to read group information.
What I want is loading a mesh and coloring different segments with different colors.

**Comment by gritd** [comment]
I'm a bit late with this but indeed - for me I also need the 'g ' to split information into objects. too bad, obj export is much smaller that .dae but the latter is handling group info much better.

**Comment by doambroa** [comment]
The problem persists, I am having issues to colour different parts of my OBJ (I am using OBJMTLLoader) because it seems that there are created lots of groups, and when I try to colour something concrete, lots of things are colored. As 2pha says, 3DSMax creates unusual "g" in the OBJ file for unique objects, any fix today? Can be different parts of an OBJ colored with Three.js?

**Comment by mrdoob** [comment]
We do support that internally now. However `OBJMTLLoader` is deprecated and we need to implement `g` parsing in `OBJLoader`.

**Comment by 2pha** [comment]
I seem to be having this problem again but have realised that it is because the 3dsMax exporter is not including the line with the object name (line prefixed with o). I'm not sure if this is because I am using the exporter wrong or it is how the 3ds max exporter works. [Stack question here](http://stackoverflow.com/questions/34705690/3dsmax-obj-export-not-including-object-name).
Adding the object names in lines beginning with `o` results in the expected behaviour

**Comment by jonnenauha** [comment]
@mrdoob I think this can also be closed. `g` parsing has been implemented some time ago (dunno which release). Pretty much the same issue as https://github.com/mrdoob/three.js/issues/6682 and seems also touches on the multiple materials inside a group issue discussed in https://github.com/mrdoob/three.js/issues/8203

**Comment by katsuya0719** [comment]
I want to use g attribute after loading obj data through OBJLoader. But looking at console screen,I cannot find any attribute corresponding to g attribute of obj file. Could you tell me in which attribute I can find g attribute? ( I could find o attribute in sc>children>0:ya>name as shown in the below image)
![image](https://cloud.githubusercontent.com/assets/10389953/20662467/7273104c-b58e-11e6-8a63-294ad9fca82d.png)
Thank you for your help!

**Comment by mrdoob** [comment]
`mesh.eometry.groups`?

**Comment by katsuya0719** [comment]
@mrdoob Thank you for your reply. I could not find the `mesh.geometry.groups`. Are there any example which is reading obj file and be able to check `mesh.geometry.groups` in console?

**Comment by mrdoob** [comment]
Can you share your file?

**Comment by katsuya0719** [comment]
@mrdoob Please find the file from following url [https://gist.github.com/katsuya0719/abb3b15270e6e9f509e113d1c3ccf41b](url)

Thank you for your help!

**Comment by mrdoob** [comment]
Weird, that model has both `g` and `o` for every part... 😐

/ping @jonnenauha

**Comment by WestLangley** [comment]
>Weird, that model has both g and o for every part..

Actually, it appears to me to have 124 `o` and 29 `g`.

@katsuya0719 What are you expecting? 124 meshes that each use one of 29 material instances?

**Comment by katsuya0719** [comment]
@mrdoob @WestLangley Thank you for investigating. This obj file is exported from Rhinoceros. Assuming from that file, 124 o is the total number of mesh. 29 g is the total number of layer.
What I am expecting is that I can differentiate imported mesh by group name. Is that possible?
Thank you!

**Comment by jonnenauha** [comment]
`g` and `o` are treated the same in the loader. I believe it should ignore the `g` ones as they don't have any geometry in them.

That file does not use any materials. So you won't get geometry.groups. Should produce a mesh with 125 children. Each having a BufferGeometry and a default material.

Does the parser error out of the file or what is the issue?

**Comment by jonnenauha** [comment]
To answer the latest question of @katsuya0719: We don't do any child groupings with `g`, as said the returned hierarchy is flat. You should have each `o` name in the `.name` property.

It might not be very convenient, but you'll have to differentiate by the 125 unique names with some kind of helper func.

P.S. I believe adding child grouping could be done quite easily, but now people are assuming flat hierarchy, this would change the behavior quite a bit. If we change it to recognize `g` as a start of child grouping of any subsequent `o`s.

**Comment by katsuya0719** [comment]
@jonnenauha Thank you for your clear explanation! I could understand the direction I should go. I am not sure whether I can make it, but will try! Thanks!
