### ISSUE TITLE
URL `https://experience.soletanche-bachy.com/` is not available on projects page

### ISSUE THREAD

**Issue by YasharSL** [mrdoob/three.js#28990]
### Description

The `https://experience.soletanche-bachy.com/` does not open and it seems like it's not available anymore.

### Reproduction steps

1. Open [Threejs Home page](https://threejs.org/)
2. Click on the project with this [image](https://threejs.org/files/projects/soletanche-bachy.png)

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

[Image](https://threejs.org/files/projects/soletanche-bachy.png)
![Screenshot 2024-07-26 213917](https://github.com/user-attachments/assets/9f76a551-2abf-4190-8ef2-571e866a1e44)

### Version

r167

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Should be fixed via: https://github.com/mrdoob/three.js/commit/bb5ad0b57e6110a0d1d2e7a5da6ecabc22471073
