### ISSUE TITLE
Many demos on the internet are no more working since r161

### ISSUE THREAD

**Issue by schoenid** [mrdoob/three.js#29004]
### Description

There are lots of demo sites, which are used by many visitors to learn, how to use three.js

Example: [Fluid](https://codepen.io/kynd/pen/jOXZXWB)

Since r161 all of them are no more working.

Reason:
[Migration-Guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide)

> The build files build/three.js and build/three.min.js have been removed. Please use ES Modules or alternatives: https://threejs.org/docs/index.html#manual/en/introduction/Installation

A change of the code to use three.js as module is possible, but does NOT always work.

One major problem:
Many people are using examples and are operating with local code, without any web server.
Local code will not work with modules.

### Reproduction steps

1. Take the example: [Fluid](https://codepen.io/kynd/pen/jOXZXWB)
2. Copy the code to a local folder
3. Execute the HTML file by double click
4. Modify the code to use Three.js as module
5. Execute the HTML file by double click

### Code

```js
<script language="javascript" type="text/javascript" src="https://threejs.org/build/three.js"></script>
```

### Live example

* [Fluid](https://codepen.io/kynd/pen/jOXZXWB)

### Screenshots

![image](https://github.com/user-attachments/assets/680e2d1f-ef41-4845-9716-d8e35cfe7a03)

### Version

r160

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
> Many people are using examples and are operating with local code, without any web server.

Sorry, but this kind of workflow is outdated and no longer recommended. 

The removed build files won't be restored so you have to find a solution by yourself e.g.  create custom UMD builds or stick to an older version of `three.js`. But I would no suggest doing any of this. Make sure to migrate to a node.js based workflow instead and always host your code on a local server.

**Comment by mrdoob** [comment]
The main issue here is people importing the library from our website like this:

```html
<script src="https://threejs.org/build/three.js"></script> 
```

That's wrong and the solution is to teach people how to import the library using a CDN.

Maybe we could add an `alert()` to those files (with instructions of how to import the library correctly) when loaded from a domain other than `https://threejs.org`...?

**Comment by schoenid** [comment]
> The main issue here is people importing the library from our website like this:
> 
> <script src="https://threejs.org/build/three.js"></script> 
> That's wrong and the solution is to teach people how to import the library using a CDN.
> 
> Maybe we could add an alert() to those files (with instructions of how to import the library correctly) when loaded from a domain other than https://threejs.org...?

Or maybe a script replacement on this URL, which throws a hint in the console, where to find instructions for a correction.

I mean, this was working until r160, just a few months ago.

There are still 100eds of pages out on the internet, which are no more working.
The owners of this pages do mostly not know, that it stopped working, or are not willing, to do corrections.

**Comment by mrdoob** [comment]
> There are still 100eds of pages out on the internet, which are no more working.

How do you know that? Do you have more links other than the one you already provided?

**Comment by schoenid** [comment]
> How do you know that? Do you have more links other than the one you already provided?

At least this one:
[Visible height - width](https://codepen.io/supah/pen/PoPMmMw)

There were more, not only on CodePen, but I didn't save it.

Others are corrected now to use a frozen version on CloudFlare.

Hm, I agree, it's not in the responsability of the three.js team to preserve an actual build for a project.
But just to remove something, that was working, without any hint or message for people, which are not the owners of the web page, which is no more working, is a bit - how can I say - hard for the visitors, if they know that it was working earlier.

**Comment by Mugen87** [comment]
> But just to remove something, that was working, without any hint or message for people, which are not the owners of the web page, which is no more working, is a bit - how can I say - hard for the visitors, if they know that it was working earlier.

With `r150` we have added deprecation warnings to `build/three.js` and `build/three.min.js`, see #25465. We did that so developers are aware that these particular build files were deprecated and be removed with `r160`.
