### ISSUE TITLE
Vite import fails on v0.167.0

### ISSUE THREAD

**Issue by blfunex** [mrdoob/three.js#29009]
### Description

When upgraded to 0.167.0, a bun vite project which worked on 0.166.0, fails with:
```
1:16:01 AM [vite] Pre-transform error: Failed to resolve entry for package "three". The package may have incorrect main/module/exports specified in its package.json.
1:16:01 AM [vite] Internal server error: Failed to resolve entry for package "three". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: /Volumes/SSD/example/src/main.ts
```

### Reproduction steps

1. `bun create vite example --template=typescript`
2. `bun add three@0.166.0`
3. copy demo three js code
4. `bun run dev` works fine
4. `bun add three@0.167.0`
5.  `bun run dev` fails

### Code

```js
import { WebGLRenderer } from "three";

const renderer = new WebGLRenderer();
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

r167

### Device

Desktop

### OS

MacOS

**Comment by blfunex** [comment]
Currently not updating to `r167`, fixed the version to previous minor: `bun add three@~0.166.0`

**Comment by donmccurdy** [comment]
I'm not able to reproduce this locally, `bun run dev` is working for both r166 and r167 for me. Using macOS, and Bun v1.1.21. If you're still seeing the issue, would it be possible to push the broken example project to a new GitHub repo?

**Comment by Mugen87** [comment]
Considering this as a `Can't repro`. We can reopen the issue when an example project for reproduction is shared.
