### ISSUE TITLE
Examples: OrthographicCamera instantiation

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#29024]
### Description

Below are two example files that instantiate an `OrthographicCamera` by passing _pixel_ units into the constructor. The units should be _scene_ units.

__FBXLoader.js__

https://github.com/mrdoob/three.js/blob/ddd1bc654db5fdc3f58a5cbc689065b26864add0/examples/jsm/loaders/FBXLoader.js#L1097

After reading the FBX spec, it is not clear to me how to fix this...

__misc_exporter_gltf.html__

https://github.com/mrdoob/three.js/blob/ddd1bc654db5fdc3f58a5cbc689065b26864add0/examples/misc_exporter_gltf.html#L371

In addition to the pixel issue, the far plane is too limiting, and the camera position likely needs to be changed.

Related: the glTF spec says the near plane distance [must be non-negative](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_camera_orthographic_znear).

### Reproduction steps

n/a

### Code

see above

### Live example

n/a

### Version

r167

**Comment by WestLangley** [comment]
>misc_exporter_gltf.html

It appears the exported `OrthographicCamera` does not render correctly on any online viewer that supports camera selection.

Is anyone interested in having a look at this?

>FBXLoader.js

Same question.

**Comment by WestLangley** [comment]
>misc_exporter_gltf.html

It appears the exported `OrthographicCamera` does not render correctly on any online viewer that supports camera selection.

Is anyone interested in having a look at this?

>FBXLoader.js

Is anyone interested in maintaining `FBXLoader`?

**Comment by Mugen87** [comment]
I have tried fixing the issue in `misc_exporter_gltf` but I'm unsure about a proper fix for `FBXLoader`. Maybe one could use the dimensions of the asset's bounding box to derive a frustum size but even then I don't know if that is what the FBX spec expects from importers.

**Comment by Mugen87** [comment]
How about we remove support for orthographic cameras from `FBXLoader` and print a warning instead? 

Right now, I doubt the view frustum is correct so no developer should rely on exporting orthographic cameras and importing them via `FBXLoader`. The code path for perspective cameras looks good, btw.

Besides, if a developer is going to file a bug in the future, we at least have an FBX asset with an orthographic camera definition which should make debugging easier.
