### ISSUE TITLE
OrbitControls cant move

### ISSUE THREAD

**Issue by nikonikoCW** [mrdoob/three.js#29026]
### Description

1:if i cant set camera.positio or camera.position.set(0,0,0)  。i cant move camera

### Reproduction steps

1.create camera
2.cant set camera position or set camera.position.set(0,0,0)
3.

### Code

<script setup>
import * as THREE from 'three'
// 引入轨道控制器扩展库OrbitControls.js
import { OrbitControls } from './OrbitControls.js';

const scene = new THREE.Scene();

// 创建相机
const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 1, 1000);
// camera.position.set(0,0,0)
window.camera = camera

// 创建渲染器
const renderer = new THREE.WebGLRenderer();
renderer.setSize(window.innerWidth, window.innerHeight);
document.body.appendChild(renderer.domElement);

// 创建蓝色网格
const gridHelper = new THREE.GridHelper(100, 100, 0x0000ff, 0x0000ff);
scene.add(gridHelper);

const light = new THREE.AmbientLight(0xffffff);
scene.add(light);

// 渲染场景
function animate() {
    controls.update();
    renderer.render(scene, camera);
    requestAnimationFrame(animate);
}

// 鼠标控制相机
const controls = new OrbitControls(camera, renderer.domElement);
// controls.target.set(1,0,1)
console.log(renderer.domElement.clientHeight)

animate();

</script>

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

R167

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Please ask the [forum](https://discourse.threejs.org/) or stackoverflow for help.
