### ISSUE TITLE
MeshBasicNodeMaterial bug with scene.environment

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#29031]
### Description

When i set the scene.environment the MeshBasicNodeMaterial take it at 100% when i expected this material to not be affected by the environment map.

expected : 
<img width="808" alt="Screenshot 2024-07-31 at 20 11 03" src="https://github.com/user-attachments/assets/2a286e10-2d28-408f-a4d9-1748f5dd0a4a">

current:
<img width="789" alt="Screenshot 2024-07-31 at 20 11 09" src="https://github.com/user-attachments/assets/d311bc6a-5869-4c07-a401-aa969734ba8d">

### Reproduction steps

see the example bellow.

### Code

`scene.environment = texture; // is apply at 100% on the MeshBasicNodeMaterial like it was a diffuse`

### Live example

https://jsfiddle.net/47hr3cgj/

### Version

r167

**Comment by Mugen87** [comment]
Yes, all materials that support env maps are currently affected by `Scene.environment`.

The expected behavior according to `WebGLRenderer`  is only physical materials should be affected.
