### ISSUE TITLE
Material Attenuation distance defaults to NULL for GLTF export

### ISSUE THREAD

**Issue by Cold5tar** [mrdoob/three.js#29034]
### Description

If there is no `material.attenuationDistance`  property set, then it defaults to `+Infinity`. Now it becomes an issue when exporting to GLTF file, because Three.js writes it as `NULL`, thus property is not being set correctly. In that case I propose not sending that property to GLTF exporter if its not set.

### Reproduction steps

1. Open created example [EXAMPLE](https://playcode.io/1954391)
2. Comment out line 15 `material.attenuationDistance=1.0;` in `script.js` file
3. Press `Download.gltf` button bellow the 3d preview
4. **Notice the 'material.attenuationDistance' is set to `Null` in the output console GLTF json file - this is the actual bug**
5. Uncomment line 15 `material.attenuationDistance=1.0;` in `script.js` file
6. Press `Download.gltf` button bellow the 3d preview
7. Notice the 'material.attenuationDistance' is set to `1` in the output console GLTF json file

### Code

```js
import * as THREE from 'three';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter';

const scene = new THREE.Scene();
const geometry = new THREE.BoxGeometry( 0.2, 0.2, 0.2 );
const material = new THREE.MeshPhysicalMaterial();
material.transmission = 0.01;
//material.attenuationDistance = 1.0;

const mesh = new THREE.Mesh( geometry, material );
scene.add( mesh );

const exporter = new GLTFExporter();
exporter.parse(scene, function (gltfJson) {
    console.log(gltfJson);
    const jsonString = JSON.stringify(gltfJson);
    console.log(jsonString);
  });
```

### Live example

[playcode live example](https://playcode.io/1954391)

### Version

r167

**Comment by Mugen87** [comment]
I think you have mixed the reproduction steps. For me, `attenuationDistance` ends up `null` in the JSON when the value of `MeshPhysicalMaterial.attenuationDistance` is left unchanged (so when it has is default value `Infinity`).

Playcode took very long to load so I added the code to a fiddle instead: https://jsfiddle.net/2k6d3zxp/1/
