### ISSUE TITLE
three0.167.1  vite build bug

### ISSUE THREAD

**Issue by flowers-10** [mrdoob/three.js#29054]
### Description

I have no issues using version 0.166.0.

0.167.1:
yarn run build
yarn run v1.22.19
$ vue-tsc && vite build
node_modules/@types/three/examples/jsm/loaders/KTX2Loader.d.ts:2:42 - error TS2307: Cannot find module 'three/webgpu' or its corresponding type declarations.
  There are types at '/Users/channel1/Desktop/Project/DigitalTwin/node_modules/@types/three/build/three.webgpu.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

2 import { Renderer, WebGPURenderer } from "three/webgpu";
error Command failed with exit code 2.

### Reproduction steps

1.version: "@types/three": "^0.167.1","three": "^0.167.1",
2.yarn run build
3.error Command failed with exit code 2.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Screenshots

![439126896](https://github.com/user-attachments/assets/c3bc6cd0-686a-4e7e-ba07-2d4b71f39656)

### Version

r167.1

**Comment by Mugen87** [comment]
Do you mind trying it with this Vite configuration: https://github.com/mrdoob/three.js/pull/28650#issuecomment-2198568721

**Comment by donmccurdy** [comment]
I think imports from three/webgpu may need to be avoided somehow here:

https://github.com/three-types/three-ts-types/blob/master/types/three/examples/jsm/loaders/KTX2Loader.d.ts

**Comment by Methuselah96** [comment]
It sounds like you're probably using `node`/`node10` which [should no longer be used](https://www.typescriptlang.org/docs/handbook/modules/reference.html#node10-formerly-known-as-node). See [this guide](https://www.typescriptlang.org/docs/handbook/modules/guides/choosing-compiler-options.html) if you're not sure which one to use.

See https://github.com/three-types/three-ts-types/issues/1136 for more info and/or to discuss further

**Comment by Mugen87** [comment]
Merging this issue into https://github.com/three-types/three-ts-types/issues/1136.

**Comment by ydmingg** [comment]
// tsconfig.json
"compilerOptions": {
    "paths": {
        "three/webgpu": ["./node_modules/three/build/three.webgpu.min.js"]
    },
}

**Comment by ydmingg** [comment]
`
// tsconfig.json
"compilerOptions": {
    "paths": {
    "three/webgpu": ["./node_modules/three/build/three.webgpu.min.js"]
},
}
`

**Comment by ydmingg** [comment]
```
// tsconfig.json
import { defineConfig } from 'vite';

{
    "compilerOptions": {
        "paths": {
            "three/webgpu": ["./node_modules/three/build/three.webgpu.min.js"]
            
        },
    }
}

```

**Comment by Makio64** [comment]
Following the answer of @ydmingg to add the auto-completion support for tsl as well : 

```
{
    "compilerOptions": {
        "paths": {
		"three/webgpu": ["node_modules/three/build/three.webgpu.js"],
		"three/tsl": ["node_modules/three/build/three.tsl.js"],
        },
    }
}

```

@Mugen87 @mrdoob should this be added to the doc in installation section ?

**Comment by Mugen87** [comment]
It might make sense to add this to the Option 1 section as a collapse element similar to:

> Installation added node_modules/ and package.json to my project. What are they?

**Comment by donmccurdy** [comment]
I'm a bit surprised TypeScript (or Vite?) can't get this information from `package.json#exports`, at least in the recent 1-2 three.js versions... do we know why that is?

**Comment by Methuselah96** [comment]
It should be able to if you're using a recommended setting for `moduleResolution` (as discussed [above](https://github.com/mrdoob/three.js/issues/29054#issuecomment-2269090426)). Let me know if something's not working for you and I'd be happy to investigate further.

**Comment by menghu1994** [comment]
tsconfig.json
```json
  "compilerOptions": {
    "moduleResolution": "bundler",
    "strict": false,
    "skipLibCheck": true,
    "paths": {
      "three": ["node_modules/@types/three"],
      "three/examples/jsm/*": ["node_modules/three/examples/jsm/*"]
    }
  }
```
