### ISSUE TITLE
Nodes: SelectionPassNode

### ISSUE THREAD

**Issue by cmhhelgeson** [mrdoob/three.js#29052]
### Description

Note: Will provide images later...

I figured I'd make this an issue since I'm not sure of it's overall utility given potential existing solutions that could be achieved with mrtNodes or other masking implementations. I suggest implementing a SelectionPassNode that generalizes the visibility operations performed within the WebGL Outline Pass Post-Process Step. The SelectionPassNode would execute a pass of the scene that either renders a set of selected objects or renders all objects outside the set. Selected objects need not be directly correlated with the mouse hover or other inputs, they can be chosen entirely at the program's discretion, as in the OutlinePass code.

### Solution

The class would look something like this:

```typescript
class SelectionPassNode extends PassNode {
	constructor( scope, scene, camera, selectedObjects ) {
		super( 'color', scene, camera );
		this.selectedObjects = selectedObjects !== undefined ? selectedObjects : [];
		this.scope = scope;
		this._visibilityCache = new Map();
		this.updateBeforeType = NodeUpdateType.RENDER;
	}

	changeVisibilityOfSelectedObjects( bVisible ) // Same as OutlinePass.js
	changeVisibilityOfNonSelectedObjects( bVisible ) // Same as OutlinePass.js

	updateBefore( frame ) {
		this.scope === SelectionPassNode.SELECTED ? ( this.changeVisibilityOfNonSelectedObjects( false ) ) : ( this.changeVisibilityOfSelectedObjects( false ) );

		super.updateBefore( frame );

		this.scope === SelectionPassNode.SELECTED ? ( this.changeVisibilityOfNonSelectedObjects( true ) ) : ( this.changeVisibilityOfSelectedObjects( true ) );
		this._visibilityCache.clear();

	}

}

export const selectedPass = ( scene, camera, selectedObjects ) => nodeObject( new SelectionPassNode( SelectionPassNode.SELECTED, scene, camera, selectedObjects ) );
export const nonSelectedPass = ( scene, camera, selectedObjects ) => nodeObject( new SelectionPassNode( SelectionPassNode.NONSELECTED, scene, camera, selectedObjects ) );
```

With this code, you can implement a simple outline pass like so:

```typescript
     postProcessing = new THREE.PostProcessing( renderer );
     const basePass = pass( scene, camera );
     selectedRenderPass = selectedPass( scene, camera );
     const selectedAlpha = selectedRenderPass.a;
     postProcessing.outputNode = selectedAlpha.mix( basePass, basePass.sepia() );
```

### Alternatives

Alternatively, it might be preferable to utilize the existing MRT approach, but depending on the size and variability of materials within the scene, that may entail more manual management of mrtNodes across the application. For certain use cases, it may be simpler to pass in the affected objects themselves rather than setting their materials on each frame. Of course, the output of the selected object would by default be affected by surrounding occluders in the MRT approach whereas it would not be affected in the selectedPass approach.

MRT approach: 

```typescript
// Initialize materials with uniform values
mesh.material.mrtNode = mrt( { mask: uniform(0) } )

postProcessing = new THREE.PostProcessing( renderer );
const scenePass = pass( scene, camera );
scenePass.setMRT( mrt( {
     output,
     mask: float( 0 ),
} ) );

const maskPass = scenePass.getTextureNode( 'mask' );
selectedRenderPass = selectedPass( scene, camera, undefined );
postProcessing.outputNode = maskPass.sobel().mix( scenePass, 1.0 );

const intersects = raycaster.intersectObject( scene, true );

if ( intersects.length > 0 ) {

     for ( let i = 0; i < selectedObjects.length; i ++ ) {

          const material = selectedObjects[ i ].material;
	  const mask = material.mrtNode.getNode( 'mask' );
	  mask.value = 0;

	  selectedObjects = [];

     }

     const selectedObject = intersects[ 0 ].object;
     addSelectedObject( selectedObject );
     const material = selectedObject.material;
     const mask = material.mrtNode.getNode( 'mask' );
     mask.value = 1;
} else {
   // Set masks back to 0

```

**Comment by sunag** [comment]
Masking the object by ID should still be implemented by MRT, the mask example although used by object does not differ by ID it would not be the same thing, creating a new `pass()` for this would also harm performance. My recommendation is to create a node, `objectId` for example, this should return an equivalent `int` where we could compare the id by object.

```js
const scenePass = pass( scene, camera );
scenePass.setMRT( mrt( {
     output,
     objects: objectId(), // null parameter will consider all objects
} ) );

const objects = scenePass.getTextureNode( 'objects' );
const isMasking = objectId( mesh ).equal( objects );

postProcessing.outputNode = isMasking.cond( basePass, basePass.sepia() );
```
