### ISSUE TITLE
Batch rendering support for lines

### ISSUE THREAD

**Issue by orzel7** [mrdoob/three.js#29114]
### Description

I've been watching the progress of BatchedMesh feature and finally decided to evaluate how to use it in my project. Using this feature greatly improves performance, but, unfortunately, I did not find any way how to perform batched draw for line primitives.
Is it possible to implement somethig like BatchedLine/BatchedLineSegments, similar to BatchedMesh?

### Solution

Not sure

### Alternatives

Not sure

### Additional context

I need to draw about 15000 edge primitives in one draw call. Edges and meshes share the same vertex buffer.

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/29018
