### ISSUE TITLE
Boundingbox + custom position attribute.

### ISSUE THREAD

**Issue by ronaldoklais** [mrdoob/three.js#29139]
### Description

BoundingBox not working when BufferGeometry is set without default attribute 'position' (custom position attribute).

Setting manually 'geometry.boundingBox = new THREE.Box3(new THREE.Vector3(-1, -1, -1), new THREE.Vector3(32, 32, 32))' does affect.

### Reproduction steps

1. go to live example
2. click at scene
3. press D to move
4. when the first pixel go out screen, the object is hidden.
5. remove comment from line 97 and try again. with single 0 in position buffer, all works OK.

### Code

import * as THREE from 'three';
import { PointerLockControls } from 'three/examples/jsm/controls/PointerLockControls'
import Stats from 'three/addons/libs/stats.module.js';

const scene = new THREE.Scene();
scene.background = new THREE.Color(0xffffff);
const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.01, 5000);

const renderer = new THREE.WebGLRenderer({ antialias:true, });
renderer.setSize( window.innerWidth, window.innerHeight );
document.body.appendChild( renderer.domElement );

const debugDom = document.getElementById("debug");

const stats = new Stats();
document.body.appendChild( stats.dom );

const clock = new THREE.Clock();

camera.position.x = 0;
camera.position.y = 0;
camera.position.z = 3;
camera.lookAt(new THREE.Vector3(0, 0, 0))

let moveForward = false;
let moveBackward = false;
let moveLeft = false;
let moveRight = false;
let moveUp = false;
let moveDown = false;

const onKeyDown = function (event) {
    switch ( event.code ) {
        case 'ArrowUp':
        case 'KeyW': moveForward = true; break;

        case 'ArrowLeft':
        case 'KeyA': moveLeft = true; break;

        case 'ArrowDown':
        case 'KeyS': moveBackward = true; break;

        case 'ArrowRight':
        case 'KeyD': moveRight = true; break;

        case 'Space': moveUp = true; break;
        case 'KeyC': moveDown = true; break;
    }
}

const onKeyUp = function (event) {
    switch ( event.code ) {
        case 'ArrowUp':
        case 'KeyW': moveForward = false; break;

        case 'ArrowLeft':
        case 'KeyA': moveLeft = false; break;

        case 'ArrowDown':
        case 'KeyS': moveBackward = false; break;

        case 'ArrowRight':
        case 'KeyD': moveRight = false; break;

        case 'Space': moveUp = false; break;
        case 'KeyC': moveDown = false; break;
    }
};

let controls = new PointerLockControls(camera, renderer.domElement);

renderer.domElement.addEventListener("click", () => {
    controls.lock();
})

window.addEventListener("keydown", onKeyDown.bind(this))
window.addEventListener("keyup", onKeyUp.bind(this))

function createChunkGeometry() {
    const geometry = new THREE.BufferGeometry;

    let positions = new Uint32Array([
        (0 & 255) | ((1 & 255) << 8) | ((1 & 255) << 16), // Vértice 1
        (1 & 255) | ((1 & 255) << 8) | ((1 & 255) << 16), // Vértice 2
        (0 & 255) | ((0 & 255) << 8) | ((1 & 255) << 16), // Vértice 3
        (1 & 255) | ((0 & 255) << 8) | ((1 & 255) << 16) // Vértice 4
    ])

    let colors = new Float32Array([
        1, 0, 0,
        0, 1, 0,
        0, 0, 1,
        1, 0, 1
    ]);
    
    let indices = new Uint32Array([0, 2, 1, 1, 2, 3]);

    geometry.setAttribute('position', new THREE.Uint32BufferAttribute(new  Uint32Array([0]), 1));

    geometry.setAttribute('aPosition', new THREE.Uint32BufferAttribute(positions, 1));
    geometry.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));
    geometry.setIndex(new THREE.Uint32BufferAttribute(indices, 1));
 
    console.log(geometry.boundingSphere)

    return geometry;
}

const material = new THREE.ShaderMaterial({
    vertexShader: `
        attribute uint aPosition;
        varying vec4 vColor;

        void main() {
            uint positionX = aPosition & 255u;
            uint positionY = (aPosition >> 8) & 255u;
            uint positionZ = (aPosition >> 16) & 255u;
            vColor = vec4(color, 1.0);
            vec3 position = vec3(float(positionX), float(positionY), float(positionZ));
            gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
        }
    `,
    fragmentShader: `
        varying vec4 vColor;
        void main() {
            gl_FragColor = vec4(vColor);
        }
    `,
    side:THREE.DoubleSide,
    vertexColors: true,
});

let geometry = createChunkGeometry();
let mesh = new THREE.Mesh(geometry, material);

mesh.geometry.boundingBox = new THREE.Box3(new THREE.Vector3(-4, -4, -4), new THREE.Vector3(4, 4, 4))

scene.add(mesh)

renderer.render( scene, camera );
console.log(mesh.geometry)

function animate() {
	requestAnimationFrame( animate );

    console.log(geometry.boundingSphere)

    let delta = 0.5 * clock.getDelta();

    let calls = renderer.info.render.calls
    let triangles = renderer.info.render.triangles
    debugDom.innerHTML = `Calls: ${calls}<br>Triangles: ${triangles}`;

    if ( moveForward ) controls.moveForward(10 * delta);
    if ( moveBackward ) controls.moveForward(-10 * delta);

    if ( moveLeft ) controls.moveRight(-10 * delta);
    if ( moveRight ) controls.moveRight(10 * delta);

    if (moveUp) camera.position.y += 10 * delta;
    if (moveDown) camera.position.y -= 10 * delta;

    stats.update();

    renderer.render( scene, camera );
}
animate();

### Live example

https://jsfiddle.net/ronaldoklais/kven7tL3/2

### Version

latest release

### Device

Desktop

### Browser

Firefox

### OS

Windows

**Comment by ronaldoklais** [comment]
const geometry = new THREE.BufferGeometry();
geometry.computeBoundingSphere();
geometry.boundingSphere.radius = NaN;

This works too. Think default isSphere need to be false, and if is false, do not auto call computeBoundingSphere().

**Comment by gkjohnson** [comment]
If using custom positioning via shader you must set the bounding volumes yourself including the geometry bounding sphere. For more help please use the forum: https://discourse.threejs.org/
