### ISSUE TITLE
Error creating WebGL context

### ISSUE THREAD

**Issue by DanielLin0516** [mrdoob/three.js#29152]
### Description

I use mobile H5 threejs to do 3D activities in an app. We need to determine whether webgl is supported in advance. We use import WebGL from 'three/addons/capabilities/WebGL.js'; to do the test. In most iOS 13.5-15,and part of android, true is returned and in this website all support https://webglreport.com/?v=2. However, an error is reported when calling new Scene(): Error creating WebGL context

How to detect this situation? Currently wrapped with trycatch
<img width="591" alt="image" src="https://github.com/user-attachments/assets/555fd929-e034-4c25-b2ee-d7e549eb8c8b">

### Reproduction steps

1.any code create webgl scene
2.In most iOS 13.5-15 and Low-end Android models

### Code

```js
// code goes here
```
    if (!isWebGLAvailable()) {
        emitGameEvents(EVENT_MAP.WEBGLERROR, {
            type: 'webGLNotSupport',
        });
        return;
    }

    try {
        gameCanvas.value = new Game(game_canvas.value, toRaw(props.mapInfo));
    }
    catch (e) {
      console.log(e);
    }

### Live example

```js
// code goes here
```
    if (!isWebGLAvailable()) {
        emitGameEvents(EVENT_MAP.WEBGLERROR, {
            type: 'webGLNotSupport',
        });
        return;
    }

    try {
        gameCanvas.value = new Game(game_canvas.value, toRaw(props.mapInfo));
    }
    catch (e) {
      console.log(e);
    }

### Version

   "three": "^0.164.1",

### Device

Mobile

### OS

iOS

**Comment by Mugen87** [comment]
`three.js` does not support WebGL 1 anymore so you always have to check for a WebGL 2 context via `isWebGL2Available()`.

Devices that only support WebGL 1 can't use a latest `three.js` version. If you need to support them, you have to go back to `r162` and stick to this release.

**Comment by DanielLin0516** [comment]
But I tested it on the old IOS system and found that webgl1/2 are supported. Why does this error occur? Is it because of the GPU? And through monitoring, the number is quite large

**Comment by DanielLin0516** [comment]
> `three.js` does not support WebGL 1 anymore so you always have to check for a WebGL 2 context via `isWebGL2Available()`.
> 
> Devices that only support WebGL 1 can't use a latest `three.js` version. If you need to support them, you have to go back to `r162` and stick to this release.

But I tested it on the old IOS system and found that webgl1/2 are supported. Why does this error occur? Is it because of the GPU? And through monitoring, the number is quite large

**Comment by Mugen87** [comment]
Sorry I can't tell you that. You definitely have to use `isWebGL2Available()` and if this method returns `true`, you can safely use a WebGL 2 rendering context.

I suggest you file an issue at the browser vendors if you have issues on older system using WebGL 2. This is not an engine-specific issue.

**Comment by DanielLin0516** [comment]
OK,thank you,So when creating a webgl context, it is safer to wrap it with a trycatch layer to enter the error page?

**Comment by Mugen87** [comment]
Yes, the same approach uses `isWebGL2Available()`.
