### ISSUE TITLE
Examples: TSL Editor doesn't work

### ISSUE THREAD

**Issue by hybridherbst** [mrdoob/three.js#29164]
### Description

I think some imports have changed, currently TSL Editor doesn't load.

### Reproduction steps

1. Visit https://threejs.org/examples/?q=tsl#webgpu_tsl_editor
2. Note nothing happens
3. Console shows error

### Screenshots

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/e779a529-cddf-46e6-a9a8-cdeb175c10b6">

### Version

latest

**Comment by Mugen87** [comment]
This is already fixed on `dev`, see #28997.

https://rawcdn.githack.com/mrdoob/three.js/dev/examples/webgpu_tsl_editor.html

**Comment by hybridherbst** [comment]
Thank you! Didn't find the issue under that name.
