### ISSUE TITLE
InstancedMesh Bug

### ISSUE THREAD

**Issue by 0819gh** [mrdoob/three.js#29182]
### Description

setMatrixAt以后没有重新computeBoundingSphere，导致raycast函数 test with bounding sphere first 计算错误

### Reproduction steps

setMatrixAt以后没有重新computeBoundingSphere，导致raycast函数 test with bounding sphere first 计算错误

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

R168

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
Do you mind writing your post in English?
