### ISSUE TITLE
glTF exported from OnShape with compression on fail to load

### ISSUE THREAD

**Issue by locomoco28** [mrdoob/three.js#29228]
### Description

Trying to load in a glTF exported from OnShape with compression on fails to load in three.js.
It loads the compressed file perfectly fine on https://gltf-viewer.donmccurdy.com/ as well as https://sandbox.babylonjs.com/

### Reproduction steps

1. Export a glTF from OnShape
2. Load it with GLTFLoader()
3. See Error `Error: THREE.GLTFLoader: No DRACOLoader instance provided.` in your browser console

### Code

```js
import * as THREE from "three";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(
  75,
  window.innerWidth / window.innerHeight,
  0.1,
  1000
);

const loader = new GLTFLoader();

loader.load(
  "public/Radio.gltf",
  function (gltf) {
    const s = 100;
    gltf.scene.scale.set(s, s, s);

    scene.add(gltf.scene);
  },
  undefined,
  function (error) {
    console.error(error);
  }
);

const renderer = new THREE.WebGLRenderer();
renderer.setSize(window.innerWidth, window.innerHeight);
document.body.appendChild(renderer.domElement);

const geometry = new THREE.BoxGeometry(1, 1, 1);
const material = new THREE.MeshBasicMaterial({ color: 0x00ff00 });
const cube = new THREE.Mesh(geometry, material);
scene.add(cube);

camera.position.z = 5;

function animate() {
  cube.rotation.x += 0.01;
  cube.rotation.y += 0.01;
  renderer.render(scene, camera);
}
renderer.setAnimationLoop(animate);
```

### Live example

[Code Sand Box](https://codesandbox.io/p/sandbox/flamboyant-browser-9c9xn8) (you can add "_uncompressed" in the file name to see the uncompressed option work)

### Screenshots

Error in console:
![image](https://github.com/user-attachments/assets/245e17ec-f846-4c05-87e5-cbeca3e1de45)

Export window from OnShape:  
![image](https://github.com/user-attachments/assets/13428d02-f081-4585-bd37-80b839dc44a7)

### Version

0.167.0

### Device

Desktop

### Browser

Firefox

### OS

Windows

**Comment by gkjohnson** [comment]
As the error states you need to provide a DRACOLoader instance to GLTFLoader in order to load these kinds of compressed models. You can see how to do so in the [GLTFLoader docs](https://threejs.org/docs/?q=gltfl#examples/en/loaders/GLTFLoader) example snippet.

For more questions please ask at the forum:

https://discourse.threejs.org/

**Comment by locomoco28** [comment]
Maybe a note in the docs would be useful, I had never used ThreeJS and was just following the basic getting started docs https://threejs.org/docs/index.html#manual/en/introduction/Loading-3D-models

Under Troubleshooting it said to check with the two example playgrounds to see if drag-and-dropping the model would work,  and if so to create a ticket. Maybe that's a good place to mention that it might be due to a compressed glTF which would require that DRACOLoader.
