### ISSUE TITLE
Documentation not work locally

### ISSUE THREAD

**Issue by milen-prg** [mrdoob/three.js#29224]
### Description

The I start server in doc folder and open the site, it looks strange and is not functional (links don't work):
![image](https://github.com/user-attachments/assets/7046a010-443b-4d59-bc83-feb445ebf2d8)

If I open with right mouse button link in new tab, it appears with errors:
![image](https://github.com/user-attachments/assets/2eff76c4-2502-46ec-ac47-b5d19037953e)

But at all, the links don't work and even it is impossible to go to the manual.

Is it possible to have the ThreeJS documentation offline?! I see so many people ask about this in years. And the answer is that "the documentation is in the source", but it traditionally NOT work.
I understand that entering in your site is important, but occasionally the developer must work without Internet, which is absolutely impossible without documentation.

### Reproduction steps

.

### Code

.

### Live example

.

### Version

all

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Something in your link isn't right. The `docs` directory is missing. Try it with:
```
http://localhost:8080/docs/#manual/en/introduction/Creating-a-scene
```

**Comment by milen-prg** [comment]
@Mugen87 , not work:
![image](https://github.com/user-attachments/assets/950f5aa4-b386-4963-b800-bdd9e5e2dba9)

I tried different servers, like python http.server, node local-web-server (ws), but no difference.
Also the browser js console returns strange errors:
![image](https://github.com/user-attachments/assets/4dee820d-eba5-4684-ad55-2388b789e350)
 
The console

**Comment by Mugen87** [comment]
Sorry, but this looks like a hosting issue on your side.

I suggest you ask for help at the forum: https://discourse.threejs.org/

**Comment by mjurczyk** [comment]
> [...] Is it possible to have the ThreeJS documentation offline?! I see so many people ask about this in years. [...]

Since the thread on discourse mentions many people have this issue - the problem here is starting a custom server directly in the `docs/` directory, which skips all the other dirs. To run docs locally just:

```bash
cd three.js
npm i
npm run dev
```

Then open `http://localhost:8080/docs/` - 100% working offline then.
