### ISSUE TITLE
The new iPhone browser will have jagged edges

### ISSUE THREAD

**Issue by yaxino** [mrdoob/three.js#29247]
### Description

my codes：
const size = this.renderer.getDrawingBufferSize(new THREE.Vector2());
        const renderTarget = new THREE.WebGLRenderTarget(size.width, size.height,
            {
                samples: 8
            });
 this.composer = new EffectComposer(this.renderer, renderTarget);
 const renderPass = new RenderPass(this.scene, this.camera);
 this.composer.addPass(renderPass);

The above code works well on various mobile platforms before.
Recently, the new iPhone browser has been experiencing jagged edges.
Tell me how to solve it. thank you!

### Reproduction steps

1.
2.
3.

### Code

```js
const size = this.renderer.getDrawingBufferSize(new THREE.Vector2());
        const renderTarget = new THREE.WebGLRenderTarget(size.width, size.height,
            {
                samples: 8
            });
 this.composer = new EffectComposer(this.renderer, renderTarget);
 const renderPass = new RenderPass(this.scene, this.camera);
 this.composer.addPass(renderPass);

```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

https://github.com/user-attachments/assets/78d5979c-fbde-41ca-b3b2-eb20782746e9

### Version

 * @license  * Copyright 2010-2022 Three.js Authors  * SPDX-License-Identifier: MIT

**Comment by Mugen87** [comment]
Does it work if you use a lower sample value like `4`?

**Comment by Mugen87** [comment]
Closing due to lack of feedback.
