### ISSUE TITLE
When an OrthographicCamera is used, increasing the far value (> 3000000) will cause the perspective effect of the model.

### ISSUE THREAD

**Issue by Jenychen1996** [mrdoob/three.js#29264]
### Description

When an OrthographicCamera is used, increasing the far value (> 3000000) will cause the perspective effect of the model.
example: webgl_loader_gltf_avif.html

### Reproduction steps

1.Create an OrthographicCamera 
2.modify the far value: >3000000
3.load model

### Code

```js
let SCREEN_WIDTH = window.innerWidth;
let SCREEN_HEIGHT = window.innerHeight;
let aspect = SCREEN_WIDTH / SCREEN_HEIGHT;
const frustumSize = 600;
camera = new THREE.OrthographicCamera(0.5 * frustumSize * aspect / - 2, 0.5 * frustumSize * aspect / 2, frustumSize / 2, frustumSize / - 2, -100000, 1000000000);
```

### Live example

none

### Version

162

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by mrdoob** [comment]
Missing live example.

**Comment by Jenychen1996** [comment]
Live example:

**Comment by Mugen87** [comment]
@Jenychen1996 A live example is a fiddle, not a link to one of the official examples.

In any event, a negative near value is not supported by the library. So do not use `-100000` but at least `0`.

**Comment by Mugen87** [comment]
The artifacts you see are related to the lack of depth precision. In general, there should be no need for such large scaled view frustums so try to stick to a tighter one and scale the scene instead.
