### ISSUE TITLE
Multiple materials / materialIndex not working when using WebGPURenderer

### ISSUE THREAD

**Issue by segments-tobias** [mrdoob/three.js#29268]
### Description

When using the WebGPURenderer with the WebGL backend, adding multiple materials with a `materialIndex` on the geometry doesn't work properly. It seems like the mapping of the materials is incorrect, leading to invisible sides.

### Reproduction steps

Toggle `forceWebGL` on the `WebGPURenderer` to see the difference.

### Code

```js
    // geometry
    const geometry = new THREE.BoxGeometry();
    
    // material
    const material = new THREE.MeshBasicMaterial( {
        color: 0x00ffff, 
    } );
    
  	const material2 = new THREE.MeshBasicMaterial( {
        color: 0xffffff, 
    } );
    
  	for (let i = 0; i < geometry.groups.length; i++) {
      geometry.groups[i].materialIndex = 0;
    }
    
    // mesh
    mesh = new THREE.Mesh( geometry, [ material, material2 ] );
```

### Live example

* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/gnx18hso/11/)

### Screenshots

WebGPU backend (working as expected):
![image](https://github.com/user-attachments/assets/89ed9b8a-a7f4-4e1a-9470-85c12e9b58e7)

WebGL backend:
![image](https://github.com/user-attachments/assets/18ea99d4-6982-4914-ac96-fb68a9ec1f42)

### Version

r167.1

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by RenaudRohlinger** [comment]
I've identified multiple issues related to this regarding draw ranges and geometry groups on both WebGL and WebGPU backends.

Will push a fix this weekend.
