### ISSUE TITLE
Left eye flickering in webxr

### ISSUE THREAD

**Issue by Ledzz** [mrdoob/three.js#29294]
### Description

WebXR session started flickering in left eye recently.
I'm using Oculus Q2, also reproduces on Q3 and event caught it on Apple Vision Pro a few times (but not that consistent).
I was believing that it was just a buggy update from Meta, but the fact that this is sometimes reproducing on Vision Pro is interesting.

So what's happening, when you enter session, the left eye starts blinking with clearColor.
Sometimes it's just lagging so in left eye I see another part of the application offset for just one frame.
The frequency of blinking (It's only a guess) depends on current CPU / GPU load.

When the load is not very much, it's offsetting.
When you increase the load, it's flickering in left eye.
If increase the load, the right eye also starts flickering but much less often.

It's best reproduced when the video with VideoTexture is playing. I've managed to catch it on [webxr_vr_video example](https://threejs.org/examples/?q=webxr#webxr_vr_video) and in my [stackblitz repro](https://stackblitz.com/edit/vitejs-vite-cfzfaf?file=src%2Fmain.ts).

### Reproduction steps

1. Visit repro
2. Go to VR session (Oculus Q2 or Q3 with latests updates)

### Code

```js
// code goes here
```

### Live example

[stackblitz repro](https://stackblitz.com/edit/vitejs-vite-cfzfaf?file=src%2Fmain.ts).

### Version

latest (r168)

### Device

Headset

**Comment by Ledzz** [comment]
I don't know what happened, but starting today headset reboot fixes the problem. I wonder if anyone faced this problem and is fixed now.

**Comment by Mugen87** [comment]
Closing then. If other devs experienced the same behavior, they can still comment in this issue.
