### ISSUE TITLE
Adding a bounding box using Box3()'s setFromObject yields an error. updateWorldMatrix is not a function

### ISSUE THREAD

**Issue by gitboyzcf** [mrdoob/three.js#29332]
### Description

Adding a bounding box using Box3()'s setFromObject yields an error. updateWorldMatrix is not a function

### Reproduction steps

1. First, loop through three spherical geometries
2. Then create a THREE Box3()
3. Merge bounding boxes in a spherical Mesh object loop using setFromObject and union method with return value
4. Finally, add the bounding box helper THREE to the scene BoxHelper

### Code

```js
  const box = new THREE.Box3();
  for (let i = 0; i < spheres.length; i++) {
    const box3 = new THREE.Box3().setFromObject(spheres[i]);
    box.union(box3);
  }
  const boxHelper = new THREE.BoxHelper(box, 0xffff00);
  scene.add(boxHelper);
};
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

r168

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
> First, loop through three spherical geometries

`setFromObject()` requires 3D objects, not geometries. So make sure you call the method with sphere meshes.

**Comment by WestLangley** [comment]
@gitboyzcf Use `Box3Helper`, instead:
```js
const box3Helper = new THREE.Box3Helper( box, 0xffff00 );
scene.add( box3Helper );
```

**Comment by gitboyzcf** [comment]
@WestLangley Thank you. I made a mistake
