### ISSUE TITLE
Browser module loading does not provide certainty.

### ISSUE THREAD

**Issue by andrewhodel** [mrdoob/three.js#29346]
### Description

If the `import` statements in https://threejs.org/docs/index.html#manual/en/introduction/Installation fail due to HTTP or TCP errors created by a disgraced network connection, there is no event to handle it.

### Reproduction steps

1. Create the example in https://threejs.org/docs/index.html#manual/en/introduction/Installation
2. Block the HTTP request of the module
3.

### Code

```js
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const controls = new OrbitControls( camera, renderer.domElement );
const loader = new GLTFLoader();
```

You can update the documentation to explain this, it prevents network administrators from blocking requests and nobody understanding why.

```js
var load_module(src, name) {

	import(src).then(function(fulfillment) {

		console.log(src, 'import() fulfillment');

		if (name !== undefined) {
			// set the module in the global namespace with the name specified
			// as import * as THREE from 'script.js' does
			window[name] = fulfillment;
		} else {
			// map each exported name to the global namespace
			// as import { ExportName } from 'script.js' does
			for (var f in fulfillment) {
				// loading OrbitControls fails here because the module three is not available in the module loading system
				// only window.THREE is available (read comment https://github.com/mrdoob/three.js/issues/29346#issuecomment-2334993789)
				window[f] = fulfillment[f];
			}
		}

	}, function(rejection) {

		// module was not loaded
		console.log(src, import() rejection', rejection);

		// retry

	});

}

load_module('build/three.module.min.js', 'THREE');

var orPromise = setInterval(function() {
  if (THREE === undefined) {
    // wait
    continue;
  }
  clearInterval(orPromise);
  load_module('examples/jsm/controls/OrbitControls.js');
}, 100);
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

168

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by andrewhodel** [comment]
@mrdoob you were talking about module loading hopes.

**Comment by andrewhodel** [comment]
This would also require `import()` to gain a module name argument, allowing `OrbitControls.js` to access `three` as defined internally.

Or, `importmap` could add support for `load` events as it already supports subresource integrity.

**As it is now, there is no certainty when loading THREE.js resources** other than bundling all of the addons into a `three.js` file that you can load in a `script` element with `XHR` that has a `load` event.

**Comment by donmccurdy** [comment]
This seems like a fundamental limitation of loading any library from a CDN, and not something that each library needs to solve for itself. Personally, I continue to recommend installing dependencies from npm, using a bundler like [Vite](https://vitejs.dev/), and self-hosting bundles. But three.js serves a range of users with different use cases and preferences, many of whom do prefer the simplicity of avoiding a bundler. So we offer both options in the installation guide.

That said, I'm worried that trying to wrap the CDN-based examples in a custom module loader would be an “unhappy medium”, with neither the production-readiness of a bundled application, nor the simplicity of using ESM modules directly.

**Comment by andrewhodel** [comment]
> This seems like a fundamental limitation of loading any library from a CDN, and not something that each library needs to solve for itself. Personally, I continue to recommend installing dependencies from npm, using a bundler like [Vite](https://vitejs.dev/), and self-hosting bundles. But three.js serves a range of users with different use cases and preferences, many of whom do prefer the simplicity of avoiding a bundler. So we offer both options in the installation guide.
> 
> That said, I'm worried that trying to wrap the CDN-based examples in a custom module loader would be an “unhappy medium”, with neither the production-readiness of a bundled application, nor the simplicity of using ESM modules directly.

That's not true, the library could be usable with `<script>` elements and this problem does not exist.

I don't know why you want this to happen to people.

**Comment by andrewhodel** [comment]
@donmccurdy 

> That said, I'm worried that trying to wrap the CDN-based examples in a custom module loader would be an “unhappy medium”, with neither the production-readiness of a bundled application, nor the simplicity of using ESM modules directly.

I can't believe you call a `load` event a custom module loader.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/load_event

**Comment by donmccurdy** [comment]
If we are going to give official advice on how to create a reliable, production-ready application, that advice needs to be "use a bundler, not a CDN."

Yes, it's possible to build reliable applications without a bundler, but it's far more difficult to do so safely. It would be misleading for us to suggest there's any simple way to change that. For example, what happens when you need to load other libraries that depend on three.js, like three-mesh-bvh? Or libraries that have their own additional dependencies?

**Comment by andrewhodel** [comment]
@donmccurdy I already wrote that in the 3rd comment.

`importmap` could add support for `load` events as it already supports subresource integrity.

Talking about a bundler instead of `importmap` that's already in HTML is crazy.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap

Regardless:

1. `importmap` should work
2. `import()` should have subresource integrity and events
3. modules such as `OrbitControls.js` should be able to access window.THREE instead of accessing a module name that is only in the module system.

Including any conversation here about a bundler, or in the documentation is only to confuse.

**Comment by andrewhodel** [comment]
@donmccurdy as far as what THREE.js can do to ensure that it's resources can be loaded and report errors to users correctly is stop using the module loading system until it isn't broken.

**Comment by andrewhodel** [comment]
It would also be acceptable to provide the Three.js addons and utils as CommonJS modules.

For example, `OrbitControls.js`:

```js
module.exports = class OrbitControls {

	constructor(three) {
		this.THREE = three;
	}

}
```

**Comment by andrewhodel** [comment]
This gist is more to read if you are trying to understand.

https://gist.github.com/andrewhodel/780f21c748cc570d96bd92e2655d9e39

**Comment by andrewhodel** [comment]
This is a way you can be certain that the files are loaded and handle errors if there is a network failure.

However, `OrbitControls.js` and any other addons or utils that you use this way must be modified to use `window.THREE` instead of the ECMAScript module system and the **special name** 'three'.

There is a modified `OrbitControls.js` file [THREEOrbitControls.js.txt](https://github.com/user-attachments/files/16919069/THREEOrbitControls.js.txt).  You do not need to modify the `three.module.js` file.

```js
import('/three.module.js').then(function(fulfillment) {

	// set the name in the global namespace
	window['THREE'] = fulfillment;

	// load file with XHR

	var xhr = new XMLHttpRequest();
	xhr.responseType = 'blob';

	xhr.addEventListener('progress', function(e) {

		console.log('progress', e.loaded, e.total);

	});

	xhr.addEventListener('load', function(e) {

		// file loaded

		// make a URL object by default
		var url = URL.createObjectURL(this.xhr.response);

		// loaded javascript file
		var OrbitControls_script_element = document.createElement('script');
		OrbitControls_script_element.src = url;
		document.body.appendChild(OrbitControls_script_element);

		// there are other events
		// error, loadend, timeout
		// or you can use a setInterval to track loading both scripts within a certain amount of time

		OrbitControls_script_element.addEventListener('load', function(e) {

			const scene = new THREE.Scene();
			const camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );

			const renderer = new THREE.WebGLRenderer();
			renderer.setSize( window.innerWidth, window.innerHeight );
			renderer.setAnimationLoop( animate );
			document.body.appendChild( renderer.domElement );

			const controls = new OrbitControls( camera, renderer.domElement );

			const geometry = new THREE.BoxGeometry( 1, 1, 1 );
			const material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
			const cube = new THREE.Mesh( geometry, material );
			scene.add( cube );

			camera.position.z = 5;

			function animate() {

				// required if controls.enableDamping or controls.autoRotate are set to true
				controls.update();

				cube.rotation.x += 0.01;
				cube.rotation.y += 0.01;

				renderer.render( scene, camera );

			}

		});

	});

	// this OrbitControls.js file must be modified to use window.THREE instead of the ECMAScript module system and the special name 'three'
	xhr.open('GET', '/THREEOrbitControls.js', true);
	xhr.send();

}, function(rejection) {

	// this is a load error
	console.log('import() rejection', rejection);

});
```

@mrdoob this allows module loading events and failure handling.

**Comment by andrewhodel** [comment]
The two ideal solutions are browser fixes.

Here are the two bugs I've submitted in hopes of that being fixed.

1. ECMAScript dynamic module import() does not allow internal naming of the module.
https://issues.chromium.org/issues/365168174

2. importmap should work with events and have a retry function
https://issues.chromium.org/issues/365076686

**Comment by Mugen87** [comment]
Sorry, but as mentioned earlier this is not an issue the we are going to address in the engine.

**Comment by andrewhodel** [comment]
> Sorry, but as mentioned earlier this is not an issue the we are going to address in the engine.

@Mugen87 

It's not part of the engine, it's the fact that any network providing internet access to any user of three.js or a product that uses it can make it fail without error.

There's no reason to allow that to be done to people by default.

**Comment by mrdoob** [comment]
Sorry, we do not have the bandwidth to work on this.

**Comment by andrewhodel** [comment]
> Sorry, we do not have the bandwidth to work on this.

Surely you are talking about group sizes regardless, at least you have electricity!
