### ISSUE TITLE
Did `three/addons` move to `three/examples`?

### ISSUE THREAD

**Issue by GniLudio** [mrdoob/three.js#29342]
### Description

The documentation states that addons can be found in the `three/addons` folder: 
See `Addons` section on [Installation Docs](https://threejs.org/docs/#manual/en/introduction/Installation)

But it seems to me that the content of the `three/addons` folder was moved to `three/examples/jsm`.
So the import statements needs to be changed
```js
import { ... } from 'three/addons/....'; // old
import { ... } from 'three/examples/jsm/...'; // new
```

There are a lot of instances of the `three/addons` folder: [Code Search](https://github.com/search?q=repo%3Amrdoob%2Fthree.js%20%22three%2Faddons%22&type=code)

### Reproduction steps

None

### Code

None

### Live example

For the [DragControls](https://threejs.org/docs/#examples/en/controls/DragControls) to work, I needed to change to import statement from
```js
import { DragControls } from 'three/addons/controls/DragControls.js';
```
to
```
import { DragControls } from 'three/examples/jsm/controls/DragControls.js';
```

### Version

0.168.0

**Comment by GniLudio** [comment]
I am using Webpack and TypeScript.

**Comment by donmccurdy** [comment]
To my understanding, Webpack v5+ supports `package.json#exports`. With TypeScript, you may need a newer `moduleResolution` setting or alternatives described in https://stackoverflow.com/a/74551879. Without those, the alias won't work and it's necessary to import from `three/examples/jsm/*` instead.

**Comment by GniLudio** [comment]
Thanks. With `"moduleResolution": "bundler"` it works.
