### ISSUE TITLE
Failed build due to eval in the latest Three.js version

### ISSUE THREAD

**Issue by vukojevicc** [mrdoob/three.js#29356]
### Description

Has anyone experienced failed Netlify builds with the latest Three.js (0.168.0)? → https://prnt.sc/Ca93HasHxjMT

Once I downgraded to 0.163.0 the build was successful.

Also, local builds were successful even on 0.168.0, so this might have something to do with Netlify.

### Reproduction steps

Deploy three.js (0.168.0) app via Netlify.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

0.168.0

**Comment by Mugen87** [comment]
That is strange. The below source file does not show any usage of `eval()`:

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/objects/SkyMesh.js

**Comment by Mugen87** [comment]
I think it's best if you report the issue to Netlify instead. There is no sign of `eval()` usage in your builds and the `SkyMesh` addon.
