### ISSUE TITLE
ThreeJS minimum version is too old

### ISSUE THREAD

**Issue by dmurvihill** [mrdoob/three.js#29365]
### Description

You added imports of `BatchedMesh` recently. This package requires `three >= 0.151` but `BatchedMesh` wasn't added until 0.158. Update the peer dependency in `package.json` to fix.

Recommend adding `three-version` to your matrix strategy in GitHub Actions, to test with different verisions of `three`.

### Reproduction steps

1. `npm install three@1.5.1`
2. `npm test`
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

0.7.7

**Comment by donmccurdy** [comment]
@dmurvihill Was this issue intended for a repository other than the repo for three.js itself?

**Comment by dmurvihill** [comment]
Yes, sorry about that.
