### ISSUE TITLE
It seems that RoundedBoxGeometry has too much vertices and face.

### ISSUE THREAD

**Issue by tocque** [mrdoob/three.js#29370]
### Description

A 2 segments fully beveled box should just have 108 face. But actually the `RoundedBoxGeometry` from addon has 324.

Some investigate:
According to the source code https://github.com/mrdoob/three.js/blob/dev/examples/jsm/geometries/RoundedBoxGeometry.js
`RoundedBoxGeometry` extends `BoxGeometry`, and use `toNonIndexed` to get all vertices. But BoxGeometry's 6 group has some duplicate vertices. So the returned vertices is duplicated too.

### Reproduction steps

just make a RoundedBoxGeometry from addon

### Code

```
const geometry = new RoundedBoxGeometry(1, 1, 1, 1, 0.1);
console.log(geometry);
```

### Live example

https://jsfiddle.net/x2aq5h89/

### Version

r168

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
You can optimize the result with `BufferGeometryUtils.mergeVertices()`:

https://jsfiddle.net/3x89uk26/

> A 2 segments fully beveled box should just have 108 face.

Where does this definition come from? Can you provide source?

**Comment by Mugen87** [comment]
We could use `mergeVertices()` directly in `RoundedBoxGeometry` but depending how you pick the parameters, the merge routine might need a different `tolerance` value for good results. This is usually not something we want to expose to the average user. 

So for the moment, the app level usage of `BufferGeometryUtils.mergeVertices()` seems like a good solution.

**Comment by tocque** [comment]
> Where does this definition come from? Can you provide source?

Sorry, my English is not good, this statement only means my speculation based on the cut-off method `RoundedBoxGemoetry` use.
