### ISSUE TITLE
 Cannot find module 'three'

### ISSUE THREAD

**Issue by zhaopeiym** [mrdoob/three.js#29405]
### Description

Angular CLI: 8.3.6、Node: 10.24.1、threejs 0.160.1 Normal work

Angular CLI: 8.3.6、Node: 10.24.1、threejs 0.161.0 Error：
```
error TS2307: Cannot find module 'three'.     
2 import * as THREE from 'three';
```

I look at the difference between the two versions, the build of the node_modules in v0.160.1 is three.js, and after v0.161.0, it is three.cjs. I don't know if that's the reason? 

### Reproduction steps

1.npm i three@0.161.0
2.npm start

### Code

nothing

### Live example

nothing

### Version

r161

**Comment by donmccurdy** [comment]
The error is coming from TypeScript, which means that your project's configuration (particularly tsconfig.json) will be relevant. Would it be possible to share an example project to reproduce this?

**Comment by zhaopeiym** [comment]
[r160-r161.zip](https://github.com/user-attachments/files/17000393/r160-r161.zip)

But versions before R160 can run normally

**Comment by mrdoob** [comment]
Please use one of the links below for help / support:

- [questions](https://stackoverflow.com/questions/tagged/three.js)
- [discord](https://discord.gg/56GBJwAnUS)
- [forum](https://discourse.threejs.org)

**Comment by zhaopeiym** [comment]
v0.161.0 and later versions three.js the above environment can be compiled and run normally if `import * as THREE from 'three'` is changed to ` import * as THREE from 'three/build/three.module.js'`
