### ISSUE TITLE
Achieve single-slit and double-slit diffraction

### ISSUE THREAD

**Issue by sahil5d** [mrdoob/three.js#29408]
### Description

A recent paper (July 2024) from NVIDIA Research, 
https://research.nvidia.com/labs/rtr/publication/steinberg2024diffraction/steinberg2024_fsd_paper_lowres.pdf, 
demonstrated free-space diffraction, where rays bend around edges and corners of scene objects.

This was achieved with raytracing, not quantum mechanics probability wave theory.

Here's a video summary, 
https://www.youtube.com/watch?v=5jfVn2ABxTo&ab_channel=NVIDIADeveloper.

Can three.js reproduce this?

### Solution

Achieve single-slit and double-slit diffraction, and share it on https://threejs.org/examples.

### Alternatives

.

### Additional context

The implementation would require tracing rays from the light source, not the camera

**Comment by Mugen87** [comment]
Please discuss this topic at the forum: https://discourse.threejs.org/

There is no hardware raytracing support in the web in general and there are no plans to add a software raytracer in the library. So you would have to use third party code or developing everything on app level.
