### ISSUE TITLE
MTL Colors Not Correct on Load

### ISSUE THREAD

**Issue by mattlewer** [mrdoob/three.js#29407]
### Description

I have an MTL file containing the following:
```
newmtl m0
Kd 0.9725490196078431 0.8 0.043137254901960784
```

Upon loading this material, and logging the RGB colors within, I get this:
```
FROM ASSET m0: 0.9386857284565036  0.6038273388475408  0.0033465357620980074
```

As you can see, they're different...

### Reproduction steps

1. Preload an MTL file onto an OBJ
2. Log the color of the material
3. Cross reference with MTL file

### Code

Please don't judge quality...
```
import { OBJLoader } from "three/examples/jsm/loaders/OBJLoader.js";
import { useLoader } from "@react-three/fiber";
import { MTLLoader } from "three/examples/jsm/loaders/MTLLoader.js";
import { useEffect } from "react";
import { GameAsset } from "../interfaces/gameAsset";

interface Asset {
  objFile: string;
  material: string;
}

const useObjLoader = (assets: Asset[], scale: number, gameAsset: GameAsset) => {
  const loadedMaterials = assets.map(asset => useLoader(MTLLoader, asset.material));

  const loadedObjects = assets.map((asset, index) =>
    useLoader(OBJLoader, asset.objFile, (loader) => {
      loadedMaterials[index].preload();
      loader.setMaterials(loadedMaterials[index]);
    })
  );

  useEffect(() => {
    loadedMaterials.forEach((materials) => {
      let i = 0;
      while (true) {
        const mat = materials.materials[`m${i}`];
        if (!mat) break;
        console.log(`FROM ASSET ${mat.name}: ${mat.color.r}  ${mat.color.g}  ${mat.color.b}`)
        i++;
      }
    });
  }, [loadedMaterials]);
}
```

### Live example

N/A

### Version

0.145.0

**Comment by donmccurdy** [comment]
These are equivalent representations of the same color, in different color spaces. three.js uses a linear working color space (by default, Linear-sRGB) for most color operations, and the RGB components of a material color are stored in the working color space for that reason. When loading colors from an external source, the colors are converted automatically to the working color space. I don't think MTL specifies color space, but we assume the MTL colors to be sRGB and convert to Linear-sRGB accordingly.

If the _appearance_ of the color is different than you expect (and not just the RGB values), note that differences in color often relate to lighting and tone mapping. React Three Fiber has tone mapping enabled by default.

**Comment by Mugen87** [comment]
@mattlewer Please use the [forum](https://discourse.threejs.org/) for more guidance.
