### ISSUE TITLE
MaterialX: Add support for Separate2, Separate3, Separate4 nodes in MaterialXLoader

### ISSUE THREAD

**Issue by beersandrew** [mrdoob/three.js#29426]
### Description

Separate nodes are not currently supported in the MaterialXLoader

### Solution

Support for separate2, separate3, and separate4 nodes

### Alternatives

I have not considered alternatives

### Additional context

I've created a [fork](https://github.com/beersandrew/three.js/tree/materialX-separate) with a [sample file](https://github.com/AcademySoftwareFoundation/MaterialX/commit/103c9212b7b8ba39fab0f0cfc7245c9ea657961b#diff-0d3ecede40f381c634d3e6e492723fa8f4d1c1dc989bad47960b442ecc663121)

If you run the fork locally and go to `/examples/?q=materialx#webgpu_loader_materialx` you can see this material shows up as black (2nd shaderball on the top row)  currently with an error that separate2 is not implemented. Images below of this state as well as the working state in the MaterialXGraphEditor

Error state
![Screenshot 2024-09-16 at 16 47 04](https://github.com/user-attachments/assets/ecb11f2c-4d2a-47d9-adba-e77ba2ce18ac)

Expected state
![Screenshot 2024-09-16 at 16 55 06](https://github.com/user-attachments/assets/b094f48f-2042-4ea2-84b5-d8cd13741d3a)

**Comment by hybridherbst** [comment]
cc @sunag, you probably have an opinion on how split nodes should work?
