### ISSUE TITLE
Documentation update, webglcontext events need to be added to render loop documentation.

### ISSUE THREAD

**Issue by andrewhodel** [mrdoob/three.js#29435]
### Description

The "Creating a scene" documentation on the three.js website lacks `webglcontext` events.

Without those `webglcontext` events, the render loop can cause the tab that is displaying the document to appear frozen.

### Reproduction steps

1. Go to https://threejs.org/docs/#manual/en/introduction/Creating-a-scene
2. Go to rendering a scene in that document.
3. Notice that the webglcontext events are missing, without those events the renderer will max a CPU at 100% utilization.

### Code

This fixes the problem.

```js
// https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/webglcontextlost_event
renderer.domElement.addEventListener('webglcontextlost', function() {
  renderer.setAnimationLoop(null);        // pause the animation
});

// https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/webglcontextrestored_event
renderer.domElement.addEventListener('webglcontextrestored', function() {
  renderer.setAnimationLoop(render_function);        // start the animation
});
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

168

### Device

Mobile

### Browser

Safari

### OS

iOS

**Comment by Mugen87** [comment]
The guide `Creating a scene` should show with _minimal code_ the creation of a basic scene. Logic for handling WebGL context loss and restore are too specific for this use case. 

Explaining WebGL context loss and how to handle it might be more appropriate in the FAQ section or a separate manual page.

**Comment by donmccurdy** [comment]
> Notice that the webglcontext events are missing, without those events the renderer will max a CPU at 100% utilization.

If this is in reference to https://github.com/aframevr/aframe/issues/3779#issuecomment-2357209140, then no, an empty requestAnimationFrame loop does not expand to fill all available CPU time.

**Comment by andrewhodel** [comment]
> > Notice that the webglcontext events are missing, without those events the renderer will max a CPU at 100% utilization.
> 
> If this is in reference to [aframevr/aframe#3779 (comment)](https://github.com/aframevr/aframe/issues/3779#issuecomment-2357209140), then no, an empty requestAnimationFrame loop does not increase in frequency to fill all available CPU time. It is limited, among other things, by the refresh rate of the display.

That does not answer if the default frequency is CPU max or not.

I am certain that the CPU lock remains with the `webglcontext` events stopping the animation loop.  That is why there is this issue - https://github.com/mrdoob/three.js/issues/29434
