### ISSUE TITLE
MaterialX: Add support for extract node

### ISSUE THREAD

**Issue by beersandrew** [mrdoob/three.js#29440]
### Description

The MaterialXLoader currently does not have support for the extract node in MaterialX

### Solution

Add an implementation for the extract node

### Alternatives

No alternatives considered

### Additional context

Sample file here: https://github.com/beersandrew/MaterialX/blob/separateNodeExample/resources/Materials/Examples/StandardSurface/extract.mtlx

expected output: 
![Screenshot 2024-09-18 at 16 24 09](https://github.com/user-attachments/assets/52709363-08ca-4a35-91ce-c539205c86e1)

**Comment by sunag** [comment]
Added here: https://github.com/mrdoob/three.js/pull/29443
