### ISSUE TITLE
invalid example links in documentation

### ISSUE THREAD

**Issue by andrewhodel** [mrdoob/three.js#29455]
### Description

https://threejs.org/docs/#manual/en/introduction/How-to-create-VR-content links to 4 invalid examples:

[WebXR / VR / ballshooter](https://threejs.org/examples/#webxr_vr_ballshooter)
[WebXR / VR / cubes](https://threejs.org/examples/#webxr_vr_cubes)
[WebXR / VR / dragging](https://threejs.org/examples/#webxr_vr_dragging)
[WebXR / VR / paint](https://threejs.org/examples/#webxr_vr_paint)

These should be replaced with the examples in `vr/handinput`.

### Reproduction steps

1. Go to https://threejs.org/docs/#manual/en/introduction/How-to-create-VR-content
2. Click the first 4 example links.
3.

### Code

NA

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

168

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
The handinput examples require more setup which is not covered by the guide yet. Hence, let's focusing on fixing the links.
