### ISSUE TITLE
Directional light shadow issue (cameraPosition uniform has incorrect value in depth material shader)

### ISSUE THREAD

**Issue by A2H2** [mrdoob/three.js#29475]
### Description

When rendering depth for Directional light shadow in depth material uniform cameraPosition contains DirectionalLight.position instead of directional vector, e.g. DirectionalLight.position - DirectionalLight.target.position or worldDirection of shadowCamera.

This is causing issue when customDepthMaterial is set on mesh for example when rendering shadows for sprites (custom instanced mesh). Issue is only visible when changing directionalLight.target.position, because when its (0, 0, 0), you kind of get correct direction vector.

There are 2 possible solutions:

1) Good one would be to modify getDepthMaterial final lines to similar to PointLight

```
		if ( light.isPointLight === true && result.isMeshDistanceMaterial === true ) {

			const materialProperties = _renderer.properties.get( result );
			materialProperties.light = light;

		}
``` 
but for DirectionalLight and then add custom uniform similar to referencePosition called lightDirection or similar but for depth in ShaderLib.

```
distanceRGBA ...
...
			{
				referencePosition: { value: /*@__PURE__*/ new Vector3() },
				nearDistance: { value: 1 },
				farDistance: { value: 1000 }
			}
```

Its quite handy to have real directional light direction in shaders, what you think ?

My current workaround is to use onBeforeShadow, but its not ideal.

```
        mesh.onBeforeShadow = (renderer: any, scene: any, camera: any, shadowCamera: any, geometry: any, 
                                               depthMaterial: any, group: any) => {

            const lightDirection = new Vector3();
            shadowCamera.getWorldDirection(lightDirection);
            mesh.depthMaterial.uCameraPosition = lightDirection; // mesh.customDepthMaterial custom uniform
```

edit3: simplified

### Reproduction steps

This is hard to reproduce, because default MeshDepthMaterial is not using "cameraPosition" uniform. You need custom depth material and to modify vertexes according to light direction (billboarding).

### Version

159

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by A2H2** [comment]
update:
Is seems that issue is only present if directionalLight.position XZ is 0. This is really weird.

Workaround:
This seems to be even more strange, it looks like its some rounding issue.

directionalLight1.position.set(0.0, 2, 0);
directionalLight1.target.position.set(2, 0, 0);
=> Shadow is not present

directionalLight1.position.set(0.00001, 2, 0);
directionalLight1.target.position.set(2, 0, 0);
=> Shadow is present,

I am not sure whether or not this is related to my custom billboard depth material or not.

**Comment by A2H2** [comment]
update 2:

So, when I pass real light direction through uniform (directionalLight.position - directionalLight.target.position), shadow is correctly rendered. So I am not really sure what is passed into cameraPosition uniform for depth material, but it is incorrect in case directionalLight.target.position is not (0, 0, 0).

**Comment by Mugen87** [comment]
Sorry, but I don't understand the issue. To me, the uniform values of the directional light and its shadow camera look correct. 

Please provide a live example that demonstrate your problem. Right now, it looks like a user error to me.

**Comment by A2H2** [comment]
> Sorry, but I'm afraid I don't understand the issue. To me, the uniform values of the directional light and its shadow camera look correct.
> 
> Please provide a live example (https://jsfiddle.net/3mrkqyea/) that demonstrate your problem. Right now, it looks like a user error to me.

Thank you for looking into the issue. I will try to demonstrate it, but meanwhile,

when custom depth material is used for mesh, what exactly is being passed into cameraPosition uniform when Diretional light is the only light on scene ?

**Comment by Mugen87** [comment]
The uniform `cameraPosition` always represents the camera position in world space. We are talking about the camera that is used to render the scene meaning that is used when calling `WebGLRenderer.render()`.

**Comment by A2H2** [comment]
I see, I got confused. I though depth material is used to render from the point of view of Directional Light to create depth map so it would contain its position and/or direction.

In this case, cameraPosition is fine and there is no issue with it and there is no bug.

Instead my issue is that there is no information about Directional light (dir or pos & target.pos). For point light, there is extra uniform called referencePosition which has position of point light. There is nothing like referencePosition for depth material.

My current workaround is that I am updating custom uniform in onBeforeShadow to pass information about shadowCamera direction. But I believe, this is quite important information to have available in depth material shaders. Could be called referenceDirection or so.

My use case is I am creating custom billboard material that renders sprite on plane and in order to have correct shadow I have to set customDepthMaterial on mesh and in depth material vertex shader I need to know shadowCamera ray direction to correctly rotate vertex so shadow is always full no matter the rotation of plane.

I already did this for custom distance material, but there was no issue, because the is position of point light in referencePosition uniform. 

Everything works for me now, but I just feel it would be nice to pass directional light info through uniform for depth material in similar way how its done for point light.

Image with 2 directional lights, everything is fine (except the fact that flame is casting shadow :-)
![image](https://github.com/user-attachments/assets/45112199-ef1e-4b09-831f-9ac8425c74f5)

**Comment by Mugen87** [comment]
> I already did this for custom distance material, but there was no issue, because there is position of point light in referencePosition uniform.

`MeshDistanceMaterial` is exclusively used with `PointLight` so it is not surprising you have `referencePosition` in the shader.  However, `MeshDepthMaterial` does not require it for its computations so there is no plan to add it to the uniforms. If you require it in your specific use case, you have to stick to your workaround based on `onBeforeShadow()` which looks appropriate to me.
