### ISSUE TITLE
NURBSCurve.toJSON doesn't serialize points data

### ISSUE THREAD

**Issue by canxerian** [mrdoob/three.js#29478]
### Description

The JSON object returned from `NURBSCurve.toJSON()` doesn't contain data relating points, knots or control points, but instead contains:

```
{
    "metadata": {
        "version": 4.6,
        "type": "Curve",
        "generator": "Curve.toJSON"
    },
    "arcLengthDivisions": 200,
    "type": "Curve"
}
```

### Reproduction steps

1. Create an instance of NURBSCurve (sample code below), 
2. `console.log` nurbsCurveInstance.toJSON()
3. Notice there is no data relating to the instance, e.g points, knots and control points)

### Code

```js
const nurbsControlPoints = [];
const nurbsKnots = [];
const nurbsDegree = 3;

for (let i = 0; i <= nurbsDegree; i++) {
  nurbsKnots.push(0);
}

for (let i = 0, j = 20; i < j; i++) {
  nurbsControlPoints.push(
    new THREE.Vector4(
      Math.random(),
      Math.random(),
      Math.random(),
      1 // weight of control point: higher means stronger attraction
    )
  );

  const knot = (i + 1) / (j - nurbsDegree);
  nurbsKnots.push(THREE.MathUtils.clamp(knot, 0, 1));
}

const nurbsCurve = new NURBSCurve(nurbsDegree, nurbsKnots, nurbsControlPoints);

console.log(nurbsCurve.toJSON());
```

### Live example

https://codesandbox.io/p/sandbox/threejs-nurbscurve-tojson-bug-s298gc

### Version

168

### Device

Desktop, Mobile

### Browser

Chrome, Firefox, Safari, Edge

### OS

MacOS

**Comment by Mugen87** [comment]
`NURBSCurve` is part of the addons and there is no JSON support for this class right now. Only curves classes in the core support that.

Even with a proper `NURBSCurve.toJSON()` implementation you could you also need the `fromJSON()` counterpart to make a deserialization work.

**Comment by Mugen87** [comment]
The next problem is that object deserialized with `ObjectLoader` can't restore instances of `NURBSCurve` because the type is unknown for the core.

**Comment by Mugen87** [comment]
`ObjectLoader` can save and load e.g. instances of `ShapeGeometry` which define their outlines via curves.

**Comment by Mugen87** [comment]
If you configure VS code with an ESLint plugin, it should automatically detect the lint configuration in https://github.com/mrdoob/three.js/blob/dev/.eslintrc.json.
