### ISSUE TITLE
After rotating the x-axis 90 degrees and then rotating the y-axis 90 degrees, the result is an incorrect angle

### ISSUE THREAD

**Issue by scorpio921** [mrdoob/three.js#29487]
### Description

Rotate the x-axis 90 degrees, and then rotate the y-axis 90 degrees at the wrong angle

### Reproduction steps

Rotate the x-axis 90 degrees, and then rotate the y-axis 90 degrees at the wrong angle

### Code

```js
// code goes here
```
function rollCamera(axisName, radians) {
    const axis = new THREE.Vector3();

    if (axisName === "X") {
        axis.set(1, 0, 0);
    } else if (axisName === "Y") {
        axis.set(0, 1, 0);
    } else if (axisName === "Z") {
        axis.set(0, 0, 1);
    }
  
    if (controls instanceof ArcballControls) {
       
        const offset = new THREE.Vector3().subVectors(camera.position, controls.target);
           

        const quaternion = new THREE.Quaternion();
        quaternion.setFromAxisAngle(axis.normalize(), radians);

      
         offset.applyQuaternion(quaternion);
        camera.up.applyQuaternion(quaternion);
        camera.position.copy(controls.target).add(offset);

        camera.lookAt(controls.target);

       
        camera.updateMatrixWorld();
        console.log('之后：',camera.position);
        controls.update();
        viewHelper.update();
    }
}
let dataArray = [];
const animateModel = (type, direction) => {
    console.log(type, direction);
    // Enable rendering
    enableRender();

    if (type == 'reset') {
        controls.reset();
        dataArray = []
        return;
    }
    dataArray.push(type);
    let angle = 90
    console.log(type);
    const radians = type !== 'Z' && direction === 'up' || type === 'Z' && direction !== 'up' ? -(Math.PI/180)*angle : (Math.PI/180)*angle;

    rollCamera(type, radians);

    
}

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

0.163.0

### Browser

Chrome

### OS

Windows

**Comment by mrdoob** [comment]
Please use one of the links below for help / support:

- [questions](https://stackoverflow.com/questions/tagged/three.js)
- [discord](https://discord.gg/56GBJwAnUS)
- [forum](https://discourse.threejs.org)
