### ISSUE TITLE
I have a problem with OrbitControls

### ISSUE THREAD

**Issue by kybex11** [mrdoob/three.js#29490]
### Description

Cannot find module 
 or its corresponding type declarations.
 
"three/addons/controls/OrbitControls"

### Reproduction steps

i installed npm i @types/three three 
and
npm i --save-dev three

### Code

```ts
import { OrbitControls } from 'three/addons/controls/OrbitControls';
```

### Version

0.168.0

### Device

PC

### Browser
Firefox

### OS

Arch Linux

**Comment by Mugen87** [comment]
Maybe just:
```js
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
```

**Comment by donmccurdy** [comment]
Also note that, depending on your `tsconfig.json`, you may need to import from `three/examples/jsm/controls/...` instead of `three/addons/controls/...`.

**Comment by Mugen87** [comment]
Please ask at the [forum](https://discourse.threejs.org/) if you need more help.
