### ISSUE TITLE
FBXLoader: Invalid request to /undefined

### ISSUE THREAD

**Issue by dominicracine** [mrdoob/three.js#29496]
### Description

I'm encountering an issue where a Three.js loader initially fetches an asset correctly, but a few seconds later, it makes a secondary request to /undefined. This behavior is unexpected and leads to 404 errors. (In my case 401, but it doesn't matter)

I think what is happening is that when loading FBX files, Three.js tries to resolve texture paths. If the paths are relative and not correctly handled, it may result in requests to invalid URLs like /undefined.

Three.js version: 10.153.0
Loader: FBXLoader
Environment: Browser
Hosting: Localhost, (my deployed app also reproduce it)

### Reproduction steps

1. Import and use the FBXLoader to load an asset (the asset should contain texture that has invalid url)
2. The loader successfully fetches the asset from the URL, but fails to load the texture.
3. Approximately 3 seconds later, the loader attempts to fetch from <base-url>/undefined.

### Code

```js
import { FBXLoader } from 'three/examples/jsm/loaders/FBXLoader';

const loader = new FBXLoader();
loader.load('/path/to/asset.fbx', (object) => {
  scene.add(object);
});
```

### Live example

https://jsfiddle.net/a2fdh7r8/3/

### Screenshots

![image](https://github.com/user-attachments/assets/39bb9970-5d92-473f-b923-4d721687beef)

### Version

0.153.0

### Device

Desktop

### Browser

Chrome

### OS

Linux

**Comment by Mugen87** [comment]
Do you mind sharing the problematic FBX asset in this thread? 

Your fiddle loads a file from localhost which is inappropriate for reproducing the issue.

**Comment by dominicracine** [comment]
Sadly it's confidential assets so I can't share it. Let me see if I can generate an asset with the same internal problematics

**Comment by dominicracine** [comment]
It was to hard to reproduce, feel free to close the issue.
