### ISSUE TITLE
WebXRManager sessionstart event does not wait for XRReferenceSpace to be fully initialized.

### ISSUE THREAD

**Issue by andrewhodel** [mrdoob/three.js#29494]
### Description

The event dispatched at https://github.com/mrdoob/three.js/blob/17abdb5e4b88368a6c1528743d014e641b32cf85/src/renderers/webxr/WebXRManager.js#L366 does not wait for the [XRReferenceSpace](https://developer.mozilla.org/en-US/docs/Web/API/XRReferenceSpace) of the VR session to be fully initialized before dispatching.

### Reproduction steps

1. Create a VR example with an object that is size 10,10,10 at 0,0,0.
2. Add a `sessionstart` event as shown in the code.
3. Click the VRButton and see that it does not always modify the reference space because the reference space is not available in the `sessionstart` event.

### Code

```js
                                                        renderer.xr.addEventListener('sessionstart', function(e) {

                                                                var currentReferenceSpace = renderer.xr.getReferenceSpace();

                                                                // set initial reference space

                                                                // set initial position
                                                                const offsetPosition = {x: -30, y: -30, z: -30, w: 1};

                                                                const offsetRotation = new THREE.Quaternion();
                                                                const transform = new XRRigidTransform(offsetPosition, offsetRotation);
                                                                const newReferenceSpace = currentReferenceSpace.getOffsetReferenceSpace(transform);

                                                                renderer.xr.setReferenceSpace(newReferenceSpace);

                                                                currentReferenceSpace = newReferenceSpace;

                                                        });
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

168

### Device

Headset

**Comment by andrewhodel** [comment]
My recommendation is removing the event and documenting how to use `renderer.xr.isPresenting` in the render loop.

There is no similar event in the WebXR specification.

**Comment by mrxz** [comment]
An actual live example would help tremendously in reproducing this. Also, what headset, browser version and OS version are you running?

The code snippet as posted should work just fine. The `sessionstart` event is only emitted by the `WebXRManager` _after_ awaiting the `requestReferenceSpace` call, so the reference space is available at that point. Not sure what you meant with "not fully initialized", but per the WebXR spec it shouldn't have resolved if it wasn't initialized.

**Comment by andrewhodel** [comment]
@mrxz you can read the code https://github.com/mrdoob/three.js/blob/17abdb5e4b88368a6c1528743d014e641b32cf85/src/renderers/webxr/WebXRManager.js#L366 and easily understand that it does not wait.  The XRReferenceSpace initialization is non blocking.

It can be accomplished with:

```javascript
this.wait_for_xr_reference_space = setInterval(function() {

  // if XRReferenceSpace is initialiized, emit sessionstart event

}, 20);

new_session() {
  clearInterval(this.wait_for_xr_reference_space);
}
```

**Comment by mrxz** [comment]
Just a couple of lines above it you'll find this:  
https://github.com/mrdoob/three.js/blob/17abdb5e4b88368a6c1528743d014e641b32cf85/src/renderers/webxr/WebXRManager.js#L359

Notice the [`await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) keyword; that ensures that the code after it (including the dispatching of the event) only happens _after_ `requestReferenceSpace` resolves. There should be no reason to replace this with a less reliable and less efficient polling approach.

If there is a bug, you'll really have to provide a (minimal) live example demonstrating the issue, along with relevant information about your environment (device, OS and browser versions).

**Comment by andrewhodel** [comment]
@mrxz regardless of XRSession.requestReferenceSpace being a Promise or not, the `XRReferenceSpace` does not have valid coordinates when line 366 is reached.

https://github.com/mrdoob/three.js/blob/17abdb5e4b88368a6c1528743d014e641b32cf85/src/renderers/webxr/WebXRManager.js#L366

**Comment by andrewhodel** [comment]
@mrxz a render loop needs to execute once before the `XRReferenceSpace` returned at line 366 has valid coordinates.

**Comment by mrxz** [comment]
> a render loop needs to execute once before the `XRReferenceSpace` returned at line 366 has valid coordinates.

Not sure I follow what you mean. The code in your original post creates an offset reference space. The spec is quite clear that this should always work, even if tracking has not been established yet. Retrieving a pose might not (yet) work in that case, but there's no telling if that takes "a render loop" or some arbitrary amount of time.

Unless you provide a (minimal) live example demonstrating the issue and the relevant information about your environment, there's no point going back and forth on this.

**Comment by Mugen87** [comment]
Closing until a live example is provided.
