### ISSUE TITLE
Move some WebGPU modules from core to addons.

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#29505]
### Description

As mentioned in https://github.com/mrdoob/three.js/pull/29483#issuecomment-2376215579, a lot of typical addons are currently placed in core. To minimize the size of build files, some of these should be moved back to the `examples/jsm/` directory.

I have created a table to lists modules in `src/nodes/display` with suggested new locations. We can add modules from other directories as well and of course discuss the intended locations.

| Module   | Location 
|----------|:-------------:|
| src/node/display/AfterImageNode.js | Addons
| src/node/display/AnaglyphPassNode.js | Addons
| src/node/display/AnamorphicNode.js | Addons
| src/node/display/BleachBypass.js | Addons
| src/node/display/BlendMode.js | Core
| src/node/display/BloomNode.js | Addons
| src/node/display/BumpMapNode.js | Core
| src/node/display/ColorAdjustment.js | Core
| src/node/display/ColorSpaceFunctions.js | Core
| src/node/display/ColorSpaceNode.js | Core
| src/node/display/DenoiseNode.js | Addons
| src/node/display/DepthOfFieldNode.js | Addons
| src/node/display/DotScreenNode.js | Addons
| src/node/display/FilmNode.js | Addons
| src/node/display/FrontFacingNode.js | Core
| src/node/display/FXAANode.js | Addons
| src/node/display/GaussianBlurNode.js | Addons
| src/node/display/GTAONode.js | Addons
| src/node/display/Lut3DNode.js | Addons
| src/node/display/MotionBlur.js | Addons
| src/node/display/NormalMapNode.js | Core
| src/node/display/ParallaxBarrierPassNode.js | Addons
| src/node/display/PassNode.js | Core
| src/node/display/PixelationPassNode.js | Addons
| src/node/display/PosterizeNode.js | Core
| src/node/display/RenderOutputNode.js | Core
| src/node/display/RGBShiftNode.js | Addons
| src/node/display/ScreenNode.js | Core
| src/node/display/Sepia.js | Addons
| src/node/display/SobelOperatorNode.js | Addons
| src/node/display/SSAAPassNode.js | Addons
| src/node/display/StereoCompositePassNode.js | Addons
| src/node/display/StereoPassNode.js | Addons
| src/node/display/ToneMappingFunctions.js | Core
| src/node/display/ToonOutlinePassNode.js | Core
| src/node/display/TransitionNode.js | Addons
| src/node/display/ViewportDepthNode.js | Core
| src/node/display/ViewportDepthTextureNode.js | Core
| src/node/display/ViewportSharedTextureNode.js | Core
| src/node/display/ViewportTextureNode.js | Core

Is everyone fine with moving the above addons into `examples/jsm/tsl/display/`?

**Comment by mrdoob** [comment]
These look good to me! 👍
