### ISSUE TITLE
Changing InstancedMesh count from 10000 to 100 throws error with WebGPU.

### ISSUE THREAD

**Issue by gnansai** [mrdoob/three.js#29500]
### Description

I am using InstancedMesh with WebGpu.
https://threejs.org/examples/?q=instance#webgpu_instance_mesh

Changing InstancedMesh count throws error with WebGPU.

create instance mesh with count of 10000 
`mesh = new THREE.InstancedMesh( geometry, material,10000 );`

Then I change  the count to less than 1000 
 `mesh.count = 100;`

**Error**

`Binding size (640000) of [Buffer "bindingBuffer_UniformBuffer_0"] is larger than the maximum binding size (65536).
 - While validating entries[1] as a Buffer.
Expected entry layout: {type: BufferBindingType::Uniform, minBindingSize: 0, hasDynamicOffset: 0}
 - While validating [BindGroupDescriptor "bindGroup_object"] against [BindGroupLayout (unlabeled)]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor "bindGroup_object"]).`

`[Invalid BindGroup "bindGroup_object"] is invalid.
 - While encoding [RenderPassEncoder (unlabeled)].SetBindGroup(0, [BindGroup], 0, ...).
 - While finishing [CommandEncoder "renderContext_0"].`

`[Invalid CommandBuffer from CommandEncoder "renderContext_0"] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer from CommandEncoder "renderContext_0"]])`

### Reproduction steps

1. Create InstancedMesh with three js `mesh = new THREE.InstancedMesh( geometry, material,10000 );`
2. add InstancedMesh  to scene ` scene.add(mesh)`
3. Change the InstancedMesh count to less than 100 `mesh.count = 100;`

### Code

```js
mesh = new THREE.InstancedMesh( geometry, material,10000 );
scene.add(mesh)
mesh.count = 100;
```

### Live example

* [[jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/GnanaSai/0w4b2L5z/17/)

### Screenshots

![image](https://github.com/user-attachments/assets/43bbd9e3-9402-4270-9c05-77d7efa70761)

### Version

r168

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by RenaudRohlinger** [comment]
In the Node Materials the buffers gets created at the node compilation triggered by a render or a compile call.

Which means that this would initialize the count to 100 and not 10000 in your example.

To fix this you can trigger a compilation of the program and then reduce the amount of instance after:
```js
mesh = new THREE.InstancedMesh( geometry, material,10000 );
scene.add(mesh)
await renderer.compileAsync(scene, camera)
mesh.count = 100;
```
Working example:
https://jsfiddle.net/o5nctyu6/4/

**Comment by gnansai** [comment]
Thank you @RenaudRohlinger

**Comment by linorabolini** [comment]
I'm seeing this issue when using postProcessing, the following doesn't seem to help. Any idea ?

```
    await postProcessing.renderAsync();
    await renderer.compileAsync(scene, camera);

    mesh.count = 0;
```
