### ISSUE TITLE
webgpu can't use multiple materials in a cube

### ISSUE THREAD

**Issue by Justnormalguy** [mrdoob/three.js#29504]
### Description

I try the examples in https://threejs.org/manual/#en/textures,but when I replace three.moudle.js to three.webgpu,js ,it doesn't woke. It looks like just  like this：
![wrong](https://github.com/user-attachments/assets/416189a6-4a3f-434d-bba5-97be916f62b5)

when I use three.moudle.js it looks correct. :-)
_

### Reproduction steps

1.copy the code from  https://threejs.org/manual/#en/textures
2.replace three form three.moudle.js to three.webgpu,js
3.replace the image

### Code

const scene = new THREE.Scene();

const boxWidth = 1;
const boxHeight = 1;
const boxDepth = 1;
const geometry = new THREE.BoxGeometry(boxWidth, boxHeight, boxDepth);

const cubes = []; // just an array we can use to rotate the cubes
const loader = new THREE.TextureLoader();

const materials = [
				new THREE.MeshBasicMaterial({ map: loadColorTexture('xxx.jpg') }),
				new THREE.MeshBasicMaterial({ map: loadColorTexture('xxx.jpg') }),
				new THREE.MeshBasicMaterial({ map: loadColorTexture('xxx.jpg') }),
				new THREE.MeshBasicMaterial({ map: loadColorTexture('xxx.jpg') }),
				new THREE.MeshBasicMaterial({ map: loadColorTexture('xxx.jpg') }),
				new THREE.MeshBasicMaterial({ map: loadColorTexture('xxx.jpg') }),
];
const cube = new THREE.Mesh(geometry, materials);
scene.add(cube);

### Version

r168

**Comment by Mugen87** [comment]
This should be fixed via #29278. Do you mind giving the current dev version a try?

**Comment by Justnormalguy** [comment]
Certainly, I'd be happy to have a try.
