### ISSUE TITLE
Access Object3d userData inside the TSL node materials

### ISSUE THREAD

**Issue by gnansai** [mrdoob/three.js#29519]
### Description

Access Object 3d userData inside the TSL node material.
https://threejs.org/docs/?q=mesh#api/en/core/Object3D.userData

Possible use cases
1. Multiple Meshes could share a single material with variations such as color.

Here is an example of possible use case
In blender we can access the mesh data such as color in the shader editor.
In the following screenshot all the cubes share same material but can have different colors. The object color is being accessed inside the material.
![image](https://github.com/user-attachments/assets/29e3acad-722c-4b14-a67d-fe376caf7ebb)     

### Solution

There is this node which gets Mesh position, scale and other Mesh properties inside TSL materials. Probably this node can get extended to get the Mesh userData.
https://github.com/mrdoob/three.js/blob/dev/src/nodes/accessors/ModelNode.js

### Alternatives

![image](https://github.com/user-attachments/assets/2dc031cd-68f4-4ce3-a6cc-401ba2125e0e)
I use any one of the following alternatives to create the colors variations like above.
1. I can create a separate material for each mesh and Change colors for each material.
2. I can create vertex colors and assign it to single Shared material to create the color variations.

**Comment by sunag** [comment]
TSL has `userData()` function for this purpose.

```js
const objectItensity = userData( 'intensity', 'float' );
```

https://github.com/mrdoob/three.js/blob/dev/src/nodes/accessors/UserDataNode.js

**Comment by gnansai** [comment]
Thank you very much @sunag
