### ISSUE TITLE
WebGPURenderer: AxesHelper fails because LineBasicMaterial is not compatible

### ISSUE THREAD

**Issue by boytchev** [mrdoob/three.js#29526]
### Description

When `AxesHelper` is used with `WebGPURenderer` the axes are not rendered. The console shows this message:

>NodeMaterial: Material 'LineBasicMaterial' is not compatible.

The issue appears in r168 and r169 in both WebGPU and WebGL2 fallback. In r167 the axes are rendered.

Previous issues with `AxesHelper` (#26630) and rendering line segments (#28927) are resolved and might be unrelated to this issue.

### Reproduction steps

1. Use `WebGPURenderer`
2. Render `AxesHelper`
3. The helper is not rendered

### Code

```js
import * as THREE from "three";

var renderer = new THREE.WebGPURenderer( ),
    scene    = new THREE.Scene( ),
    camera   = new THREE.PerspectiveCamera( 30, innerWidth / innerHeight );

scene.add( new THREE.AxesHelper( ) );

renderer.renderAsync( scene, camera );
```

### Live example

[https://codepen.io/boytchev/pen/WNVQwGX?editors=1011](https://codepen.io/boytchev/pen/WNVQwGX?editors=1011)

### Screenshots

![image](https://github.com/user-attachments/assets/6a683925-8aab-4dcf-b4e0-c0f2c0c6d32b)

### Version

r169

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by gnansai** [comment]
Hi @boytchev 
It has been fixed in the latest dev version.
https://github.com/mrdoob/three.js/pull/29501

**Comment by Mugen87** [comment]
Indeed, the latest minified builds work as expected: https://jsfiddle.net/2ra549no/
