### ISSUE TITLE
Voice Of Racism.co.nz link is redirected to "Buy this domain"

### ISSUE THREAD

**Issue by DavidGrice** [mrdoob/three.js#29535]
### Description

Line 184 `<a href="https://voiceofracism.co.nz/" target="_blank" rel="noopener"><img src="files/projects/voiceofracism.png" loading="lazy"/></a>` of [index.html](https://github.com/mrdoob/three.js/blob/gh-pages/index.html) is redirecting to a buy this website domain.

I believe the original authors of this project did not renew their domain or updated and did not inform you all of this change.

### Reproduction steps

1. Go to [ThreeJS website](https://threejs.org/)
2. Scroll down to [Voice of Racism url](https://voiceofracism.co.nz/)
3. Click on the image to open in new window.
4. Get redirected to Buy this domain webpage.

### Code

```html
<a href="https://voiceofracism.co.nz/" target="_blank" rel="noopener"><img src="files/projects/voiceofracism.png" loading="lazy"/></a>
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

r/current

### Device

Desktop

### Browser

Firefox

### OS

Windows

**Comment by Mugen87** [comment]
Should be fixed via https://github.com/mrdoob/three.js/commit/6fd28e32ea28631586c9af69d98e16477a0764eb.
