### ISSUE TITLE
WebGLRenderer: `renderer.info.render` data is wrong if use `BatchedMesh._multiDraw`

### ISSUE THREAD

**Issue by agargaro** [mrdoob/three.js#29531]
### Description

Using `BatchedMesh` and `multiDrawElementsInstancedWEBGL`, the **triangles** and **drawcalls** in the `renderer.info.render` are not correct.

### Reproduction steps

1. Create a new `BatchedMesh`
2. Set these multidraw properties (using at least two geometries):
```js
_multiDrawStarts
_multiDrawCounts
_multiDrawInstances
_multiDrawCount
```
3. Check `renderer.info.render`

### Code

```js
this._multiDrawStarts = multiDrawStarts;
this._multiDrawCounts = multiDrawCounts;
this._multiDrawInstances = multiDrawInstances;
this._multiDrawCount = range.length - 1;
```

### Live example

In this example I use multidraw to manage the LODs of an InstancedMesh with a single drawcall

https://stackblitz.com/edit/three-ezinstancedthree-js-bug-drawcall-triangles-infomes?file=src%2Fmain.ts

### Screenshots

![image](https://github.com/user-attachments/assets/e4c3a86f-4a03-4520-8b56-031e3d1e29b7)
Here there should be one draw call and fewer triangles

### Version

r169

**Comment by CodyJasonBennett** [comment]
Thanks! Was looking into a fix since seeing #29488 and noticing the count was wrong here.
