### ISSUE TITLE
3MFLoader: Add support for Volumetric Implicits

### ISSUE THREAD

**Issue by zalo** [mrdoob/three.js#29548]
### Description

3MF files can now contain volumetric implicits defined as operation execution graphs.

The 3MF consortium has released a 3D Modeller for generating .3mf’s with them, similar to nTopology:
https://github.com/3MFConsortium/gladius

![](https://raw.githubusercontent.com/3MFConsortium/gladius/refs/heads/main/gladius/documentation/img/gladius_animation.gif)

This presents an opportunity to make SDF Implicits a first or second-class feature of 3D on the web!

### Solution

My proposal would be to bake the execution graphs out to TSL, where a raymarching shader can evaluate them at runtime.

### Alternatives

Eventually, a WebGPU Marching Cubes compute shader can take them the rest of the way into mesh-land. 🧐

### Additional context

Perhaps PhysicalSDFMaterial can become a default engine material? I imagine they might ingest a TSL graph describing the SDF value and the PBR Rendering properties (diffuse color, normal, specular etc.) given a point in space; enabling it to benefit from improvements made to the main PBRMaterial!   By default, they might just sample from a volumetric texture instead of evaluating the implicit programmatically.

Engine integration provides the interface for standardized cross-system interaction, like possibly with physics engines.

**Comment by zalo** [comment]
I have the roughest beginnings of a node parser implementation here: https://github.com/zalo/three.js/commit/e2790872a5566d65d914715d1b14df0ba88b4265
Once the ops are being read out appropriately, it will be time to hook them up to the equivalent TSL functions...

**Comment by zalo** [comment]
It occurs to me that I'm in over my head a bit ( https://github.com/zalo/three.js/commit/dcabebf045fdd5e5981d9aef8657c733207995cf )... perhaps it makes more sense to add just a `implicitfunction` parser first, and then save the TSL transpilation for a separate PR, once I actually learn about how TSL works...

Does TSL even exist in non-webgpu version of three.js?

**Comment by Makio64** [comment]
@zalo It's confusing but the **WebGPURenderer actually have two Backend** : WebGL & WebGPU. 
It's more like a `Threejs v2` with a new core, and new concepts of Nodes & TSL : a system made to work on both technology seemlesssly.

**Comment by Mugen87** [comment]
@zalo I recommend to keep TSL generation out of `3FMLoader` and return a JSON representation in the callback instead (maybe in the `userData` property of the returned group). In the next step, I would create a separate library that takes the JSON representation and creates node materials from it.

In this way, `3FMLoader` can easier be used with both `WebGLRenderer` and `WebGPURenderer`. Once `WebGLRenderer` is deprecated, a deeper integration can be considered.

**Comment by zalo** [comment]
Gotcha; since TSL isn't guaranteed to be present; it doesn't seem to make sense to compile to it in a default lib.

I'll keep the exposed `implicitfunction` structure simple, but optimized for others (who know more about TSL or some other language 😅 ) to step through and write a node -> node compiler.

I also have it on good authority that [the javascript reference implementation for 3mf parsing](https://github.com/3MFConsortium/lib3mf) will include volumetrics support soon, so the third-party ecosystem should have solutions soon regardless.

**Comment by Mugen87** [comment]
Since https://github.com/mrdoob/three.js/pull/29667 is merged, this can be closed. Once `WebGLRenderer` is deprecated, we can revisit this topic.

**Comment by rawwerks** [comment]
i'm curious about using the implicit extension of 3mf with three.js ...it's a bit tough to follow the current status. 

is this something that is planned? 

other than getting rid of `WebGLRenderer` - what else needs to happen?

**Comment by zalo** [comment]
Implicits were recently added to lib3mf, so perhaps they’re going to get a lot more common:
https://github.com/3MFConsortium/lib3mf/releases/tag/v2.4.1

This PR was reduced to mere parsing of the Implicit AST, but it’s not clear what the final output format should be… presumably, 3MF nodes should be directly mappable to three.js WebGPU Nodes for direct raymarching, but the nodes that incorporate mesh distances may need @gkjohnson ’s three-mesh-bvh to function as expected…

**Comment by rawwerks** [comment]
yes i think @gkjohnson has the key => https://gkjohnson.github.io/three-mesh-bvh/example/bundle/sdfGeneration.html

**Comment by rawwerks** [comment]
i also found this => https://github.com/Metafold3d/metafold-three.js
