### ISSUE TITLE
TransformControls not working correctly in v0.169.0, disappears on interaction

### ISSUE THREAD

**Issue by hamidzare71** [mrdoob/three.js#29546]
### Description

In version 0.169.0 of Three.js, the TransformControls stop functioning correctly when added to the scene. When trying to interact with objects (e.g., clicking or dragging a cube), the control disappears, and the manipulation no longer works as expected. This issue does not occur in version ‍0.168.0‍‍‍‍‍

### Reproduction steps

1. Install Three.js v0.169.0 using npm.
2. Import TransformControls and add them to a simple scene with a cube.
3. Try to interact with the cube using the TransformControls.
4. The control disappears, and the cube cannot be moved as expected.

### Code

```js
import * as THREE from "three";
import { TransformControls } from "three/examples/jsm/controls/TransformControls.js";

const scene = new THREE.Scene();
scene.add(new THREE.AxesHelper(50));

const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
camera.position.z = 5;

const renderer = new THREE.WebGLRenderer();
renderer.setSize(window.innerWidth, window.innerHeight);
document.body.appendChild(renderer.domElement);

// Cube
const geometry = new THREE.BoxGeometry();
const material = new THREE.MeshBasicMaterial({ color: 0x00ff00 });
const cube = new THREE.Mesh(geometry, material);
scene.add(cube);

// TransformControls
const transformControls = new TransformControls(camera, renderer.domElement);
transformControls.attach(cube);
scene.add(transformControls);

// Animation loop
function animate() {
  requestAnimationFrame(animate);
  renderer.render(scene, camera);
}

animate();

// Handle window resize
window.addEventListener("resize", () => {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
});

```

### Screenshots

<img width="1512" alt="Screenshot 1403-07-12 at 18 31 29" src="https://github.com/user-attachments/assets/31f04b4c-a525-4eab-b351-69507d0bec8b">

### Version

169

### Device

Desktop

### Browser

Firefox

### OS

MacOS

**Comment by Mugen87** [comment]
> scene.add(transformControls);

This bit has changed with `r169`. According to the migration guide (https://github.com/mrdoob/three.js/wiki/Migration-Guide#168--169), the visual helpers of the controls must be added to the scene via:
```js
transformControls.add( controls.getHelper() )
```
This has been changed since `TransformControls` is now derived from `Controls` to make the implementation more consistent with all other controls.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help when upgrading `three.js`.
