### ISSUE TITLE
WebGLRenderer: setting `outputColorSpace` to `LinearSRGBColorSpace` throws error

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#29542]
### Description

As the title says.

### Reproduction steps

see code and example below

### Code

```js
renderer.outputColorSpace = THREE.LinearSRGBColorSpace;
```

### Live example

dev branch
https://jsfiddle.net/zvyewL83/ 

### Version

r170dev

**Comment by donmccurdy** [comment]
PR:

- https://github.com/mrdoob/three.js/pull/29543
