### ISSUE TITLE
Postprocessing: OutputPass applies sRGB transfer function even when ColorManagement is disabled

### ISSUE THREAD

**Issue by gkjohnson** [mrdoob/three.js#29550]
### Description

OutputPass currently _always_ checks for the output color space even when ColorManagement is disabled. See [this line](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/postprocessing/OutputPass.js#L58). Additionally that line will throw an error if `outputColorSpace` is set to `LinearSRGBColorSpace`. 

Strangely if I comment that line out the result looks like the LinearSRGBColorSpace image from #29549. Some kind of color transformation seems to be happening somewhere still.

Related to https://github.com/mrdoob/three.js/issues/29429, #29549, this [discourse post](https://discourse.threejs.org/t/wrong-colors-in-transparent-materials-when-using-effectcomposer-post-processing/70895/13).

cc @donmccurdy 

### Reproduction steps

1. Disabled three.js ColorManagement
1. Render a scene with post processing and output pass
2. See colors do not match assigned hex codes

### Code

see jsfiddle

### Live example

https://jsfiddle.net/t7pLhr1c/3/

### Screenshots

**No Postprocessing**

<img width="200" alt="image" src="https://github.com/user-attachments/assets/205726e5-891e-4b94-b957-5eb4a383c7ea">

**Current OutputPass Result**

<img width="200" alt="image" src="https://github.com/user-attachments/assets/d6c7672e-855f-46e6-8b1c-c6cb9238a4fd">

### Version

latest

**Comment by donmccurdy** [comment]
@gkjohnson do you mind if we fold this issue into https://github.com/mrdoob/three.js/issues/29549? I think it will be essentially the same discussion, just hoping to keep it in one place, and no problem if that leads to changes in both WebGLRenderer and post-processing.

**Comment by gkjohnson** [comment]
That's fine - sounds like there's a difference in thinking about what managed color means. It might take me a bit but I'll write up my thinking and why this behavior is unexpected in that other issue. We can reopen this one later if it makes sense.
