### ISSUE TITLE
Example code in the documentation is minified on Firefox

### ISSUE THREAD

**Issue by jessetemp** [mrdoob/three.js#29569]
### Description

Some of the example code blocks in the documentation have incorrect line breaks in Firefox. Here is a screenshot from [Creating a scene](https://threejs.org/docs/#manual/en/introduction/Creating-a-scene):
![Screenshot from 2024-10-06 08-46-44](https://github.com/user-attachments/assets/9863949b-0432-4793-81df-8521325901e8)

I tried cloning the repo to see if I could see if I could fix it but the formatting is correct when I open the page locally:
![Screenshot from 2024-10-06 08-48-34](https://github.com/user-attachments/assets/1ca705ae-81b6-415e-81ce-e701a3908d5c)

Not all code blocks are missing newlines. The Fundamentals section for example looks ok online. The minified blocks also look ok in Chrome.

### Reproduction steps

1. Run Firefox 131 on Debian 12
2. Open the online docs

### Code

NA

### Live example

NA

### Version

Latest

### Device

Desktop

### Browser

Firefox

### OS

Linux

**Comment by Mugen87** [comment]
There might be an issue with the combination of `<code>` and `white-space: pre-wrap;` in Firefox, see:

https://discourse.threejs.org/t/why-format-code-like-this/72406/12

**Comment by Mugen87** [comment]
Does this URL work for you?

https://rawcdn.githack.com/mrdoob/three.js/dev/docs/index.html#manual/en/introduction/Creating-a-scene
