### ISSUE TITLE
Use of eval in "node_modules/three-stdlib@2.33.0/libs/lottie.js" is strongly discouraged as it poses security risks and may cause issues with minification.

### ISSUE THREAD

**Issue by JustFly1984** [mrdoob/three.js#29572]
### Description

I have remix-run app with react-three-fiber and three.js@0.169.0

I'm building it with vite rollup esbuild and terser. I'm getting a warning about eval used in one of dependencies of three.js

node_modules/.pnpm/three-stdlib@2.33.0_three@0.169.0/node_modules/three-stdlib/libs/lottie.js (13062:32): Use of eval in "node_modules/.pnpm/three-stdlib@2.33.0_three@0.169.0/node_modules/three-stdlib/libs/lottie.js" is strongly discouraged as it poses security risks and may cause issues with minification.

### Reproduction steps

1. build vite app with three.js in dependencies.

### Code

node_modules/.pnpm/three-stdlib@2.33.0_three@0.169.0/node_modules/three-stdlib/libs/lottie.js (13062:32): Use of eval in "node_modules/.pnpm/three-stdlib@2.33.0_three@0.169.0/node_modules/three-stdlib/libs/lottie.js" is strongly discouraged as it poses security risks and may cause issues with minification.

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Screenshots

<img width="677" alt="image" src="https://github.com/user-attachments/assets/a37bcd76-4401-4b68-852c-0551d6faeaaf">

### Version

0.169.0

**Comment by Mugen87** [comment]
The issue is about this line:

https://github.com/mrdoob/three.js/blob/efbf25c194054b450b5de3bc79e832909016625d/examples/jsm/libs/lottie_canvas.module.js#L13973

**Comment by Mugen87** [comment]
The `eval()` usage happens in an external library. It's best to merge this issue into:

https://github.com/airbnb/lottie-web/issues/2927

**Comment by mrdoob** [comment]
Also, this is the repo for reporting `three-stdlib` issues:

https://github.com/pmndrs/three-stdlib

**Comment by JustFly1984** [comment]
@mrdoob please reopen, until issue is resolved downstream, and three-stdlib with fix is merged into three.js

**Comment by CodyJasonBennett** [comment]
Is there an actual technical reason or is this one of the many false positives like regex-based DOS that don't actually affect libraries like three.js?

**Comment by JustFly1984** [comment]
@CodyJasonBennett  eval and new Function is basically the same thing - it allows evaluation and execution of any code passed as is, so yes, it is security vulnerability, and the big one.

**Comment by CodyJasonBennett** [comment]
We're not going to do anything if this is effectively linting our code and not surfacing real issues affecting the project. You're welcome to make a PR if a Rollup warning is so bothersome, but it is in no way breaking or a risk factor to three.js code, whether you use LottieLoader or not. In the future, please take inquiries like this offline in the event there is a real vulnerability as this is entirely unproper. I maintain this is both not a security issue affecting three.js, nor a technical issue worth further investment.
