### ISSUE TITLE
WebGPURenderer: NodeMaterialObserver can prevent BufferAttributes from being updated despite needsUpdate

### ISSUE THREAD

**Issue by mrxz** [mrdoob/three.js#29582]
### Description

Noticed a bug in the [`webgpu_animation_retargeting`](https://threejs.org/examples/#webgpu_animation_retargeting) example where under certain camera angles the `SkeletonHelper` would "freeze" and no longer update. Trying to figure out what caused it, I discovered that during a "freeze" the `BufferAttribute` of the helper would not be updated by the renderer, despite its contents having changed and `needsUpdate` being set.

A bisect revealed that this is a regression caused by #29386. Not yet familiar with these parts of Three.js, so not sure if the `SkeletonHelper` is doing something that isn't (or no longer is) supported and that now surfaces, or that the `NodeMaterialObserver` is incorrectly determining that no refresh is needed.

To summarize:

- Happens in the example with both WebGPU and the WebGL fallback backends.
- The `SkeletonHelper` _does_ update the `position` attribute's data and marks it as `needsUpdate` ([SkeletonHelper.js#L91](https://github.com/mrdoob/three.js/blob/dev/src/helpers/SkeletonHelper.js#L91))
- During rendering the `needsRefresh` check prevents the `_geometries.updateForRender` call ([Renderer.js#L1606-L1617](https://github.com/mrdoob/three.js/blob/0c7cf78a64a724c24fcca51500b8f3d1b9931af5/src/renderers/common/Renderer.js#L1606-L1617))
- From testing the fact that there are two `SkeletonHelpers` is relevant for the reproduction. My guess would be that with only a single one, the `needsRefresh` check would return true for other reasons, whereas with two (and the right camera angle) the two `SkeletonHelpers` are rendered immediately after eachother.

Nothing in the above seems specific to the `SkeletonHelper` AFAICT, so this behaviour can likely occur in other situations as well.

### Reproduction steps

1. Open https://threejs.org/examples/#webgpu_animation_retargeting
2. Enable the "helpers" using the checkbox
3. Rotate the camera around and notice the helpers "freezing" with certain camera angles (see screenshot)

### Code

Relevant code in `SkeletonHelper`: https://github.com/mrdoob/three.js/blob/dev/src/helpers/SkeletonHelper.js#L66-L91

### Live example

- [`webgpu_animation_retargeting`](https://threejs.org/examples/#webgpu_animation_retargeting)

### Screenshots

![image](https://github.com/user-attachments/assets/c4548deb-7e93-4337-ac97-3d3b21f6deba)

### Version

r169

### Device

Desktop

### Browser

Chrome, Firefox

### OS

Linux

**Comment by RenaudRohlinger** [comment]
Thanks for this @mrxz! Your input helped me understand an issue on my end, and I’ve submitted a PR with a fix.
