### ISSUE TITLE
displacement map with BoxGeometry dose not  work.

### ISSUE THREAD

**Issue by Justnormalguy** [mrdoob/three.js#29607]
### Description

I want to do something like this:
![Capture](https://github.com/user-attachments/assets/9c63c1f9-de0f-47f0-8ac2-e64c682a0db3)

So I use MeshStandardNodeMaterial with the same displacement map, but it looks like the whole plane shifted. I change the displacementScale and displacementBias, but it still looks not right.  :)
![Capture JPG1](https://github.com/user-attachments/assets/70f1266e-4a16-47f0-98c8-43fafc95cb9e)

### Reproduction steps

copy the code form https://github.com/mrdoob/three.js/blob/master/examples/webgpu_materials_displacementmap.html,and use BoxGeometry instead of OBJLoader.

### Code

```js
loader.load(filePathD, function (texture) {
const material = new THREE.MeshStandardMaterial({
	color: 0xffffff, 
	metalness: 0.0, 
	roughness: 0.5, 
	map: texture,
	displacementMap: texture, 
	displacementScale: -0.2,
	displacementBias: 0,
});

const geometry = new THREE.BoxGeometry(1, 1, 1);
const mesh = new THREE.Mesh(geometry, material);
mesh.scale.multiplyScalar(5);
scene.add(mesh);
mesh.rotation.set(rand(Math.PI), rand(Math.PI), 0);
});
```

### Live example

no

### Version

r169

**Comment by mrdoob** [comment]
```js
const geometry = new THREE.BoxGeometry(100, 100, 100);
```

**Comment by Justnormalguy** [comment]
Thanks for your answer, it's still dose not work, I use PlaneGeometry to finish my job at last.
