### ISSUE TITLE
VideoTexture’s colorSpace not working on Emissive channel

### ISSUE THREAD

**Issue by vis-prime** [mrdoob/three.js#29625]
### Description

When a `videoTexture` is applied on `emissiveMap` of a `MeshStandardMaterial` , `SRGBColorSpace` does not work and it always stays in Linear Color Space.

### Reproduction steps

- create videoTexture
- set its colorspace to SRGBColorSpace
- Apply video texture on `emissiveMap` of `MeshStandardMaterial`
- make emissive color white and diffuse color black so its simulating a real life 'display/screen/tv'
- notice the video's colors look washed out as its displaying in Linear Color Space

### Code

```
 const videoTexture = new THREE.VideoTexture(videoElem)
 videoTexture.colorSpace = THREE.SRGBColorSpace
 
 const emit_mesh = new THREE.Mesh(planeGeometry, new THREE.MeshStandardMaterial({
    color: 0x000000,
    emissive: 0xffffff,
    emissiveMap: videoTexture,
  }))
  scene.add(emit_mesh)
```

### Live example

In this demo [jsfiddle.net](https://jsfiddle.net/n34jm8c0/7/)

The same VideoTexture and an ImageTexture is applied on

`emissiveMap` input of a `MeshStandardMaterial`
`map` input of a `MeshStandardMaterial`
`map` input of a `MeshBasicMaterial`

& GUI controls colorSpace of both

### Screenshots

(look at the top right plane in this video)

https://github.com/user-attachments/assets/416f3fd8-515c-46f2-9131-74aae4c66c1c

### Version

r169

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by donmccurdy** [comment]
Related:

- https://github.com/mrdoob/three.js/pull/26521

Currently VideoTexture is a special case because the browser's sRGB decoding is unreliable for videos. Perhaps we need to extend the inline GLSL sRGB decoding to other slots on default materials.

The underlying [browser issue](https://issues.chromium.org/issues/40915685) remains unfixed.

**Comment by donmccurdy** [comment]
@Mugen87 I don't mind making a PR for this, is it OK to scope the fix only to .emissiveMap? Technically this also applies to .sheenColorMap, .specularColorMap, etc... but I doubt these are being used with video, and I imagine we might not want this chunk appearing everywhere:

```glsl
#ifdef DECODE_VIDEO_TEXTURE

  // use inline sRGB decode until browsers properly support SRGB8_ALPHA8 with video textures (#26516)

  sampledDiffuseColor = vec4( mix( pow( sampledDiffuseColor.rgb * 0.9478672986 + vec3( 0.0521327014 ), vec3( 2.4 ) ), sampledDiffuseColor.rgb * 0.0773993808, vec3( lessThanEqual( sampledDiffuseColor.rgb, vec3( 0.04045 ) ) ) ), sampledDiffuseColor.w );
	
#endif
```

Aside, which of these blocks us from using WebGL's sRGB decoding for video?

- https://issues.chromium.org/issues/40915685
- https://bugs.webkit.org/show_bug.cgi?id=222822

Do we need both fixed, or just the Safari one?

**Comment by Mugen87** [comment]
Supporting just emissive sounds good to me!

AFAICS, we need both browser bugs fixed.

**Comment by donmccurdy** [comment]
PR

- https://github.com/mrdoob/three.js/pull/29657
