### ISSUE TITLE
add demo "examples" 2 different scene in one view: comparison with slider

### ISSUE THREAD

**Issue by manuelsongokuh** [mrdoob/three.js#29635]
### Description

hi

i start to look this awesome threejs, but i see there is missing: comparison slider (2 scene differents in one view)
i did look for in google nothing show in examples.. i wish to look if can threejs does this "comperison slider" so i can start build it..

### Solution

compaerison slider: 2 differents scene

### Alternatives

i wish to try this threejs..

### Additional context

same orbit, same camera...but different is model 3d..

**Comment by Mugen87** [comment]
Try it with: https://threejs.org/examples/webgl_multiple_scenes_comparison

**Comment by manuelsongokuh** [comment]
> Try it with: https://threejs.org/examples/webgl_multiple_scenes_comparison

ok, but can does different model 3d? i see same model 3d...

**Comment by Mugen87** [comment]
Yes, you can have different 3D models per view. Each view has its own scene (`sceneL`, `sceneR`).

**Comment by manuelsongokuh** [comment]
> Yes, you can have different 3D models per view. Each view has its own scene (`sceneL`, `sceneR`).

WOOOWW!!!!  i can download example so i can study and learn how make it?

**Comment by manuelsongokuh** [comment]
> > Try it with: https://threejs.org/examples/webgl_multiple_scenes_comparison
> 
> ok, but can does different model 3d? i see same model 3d...

or is there documentatio for this comparison multiple scene?

**Comment by Mugen87** [comment]
No, but the example isn't really complex. You should be able to figure out what's going on by studying the code.

**Comment by manuelsongokuh** [comment]
hi @Mugen87 i did try many times there is issue: with "GLTFLoader.js" , comparison that you used geometry..
```
loadAccessor http://0.0.0.0:8000/jsm/loaders/GLTFLoader.js:3070
    promise callback*loadAccessor http://0.0.0.0:8000/jsm/loaders/GLTFLoader.js:3025
    getDependency http://0.0.0.0:8000/jsm/loaders/GLTFLoader.js:2827
    assignAttributeAccessor http://0.0.0.0:8000/jsm/loaders/GLTFLoader.js:4617
    addPrimitiveAttributes http://0.0.0.0:8000/jsm/loaders/GLTFLoader.js:4633
```
maybe it is bug.. but i'm not sure

i did done:
```
const loader = new GLTFLoader().setPath('./public/3d-model/');
loader.load('sceneL.gltf', (gltf) => {
  console.log('loading model');
  const meshL = gltf.scene;

  mesh.traverse((child) => {
    if (child.isMesh) {
      child.castShadow = true;
      child.receiveShadow = true;
    }
  });

  mesh.position.set(0, 1.05, -1);
  sceneL.add(meshL);

  document.getElementById('progress-container').style.display = 'none';
}, (xhr) => {
  console.log(`loading ${xhr.loaded / xhr.total * 100}%`);
}, (error) => {
  console.error(error);
});
```

result many errors...so i'm death :-D

**Comment by mrdoob** [comment]
Please use one of the links below for help / support:

- [questions](https://stackoverflow.com/questions/tagged/three.js)
- [discord](https://discord.gg/56GBJwAnUS)
- [forum](https://discourse.threejs.org)
