### ISSUE TITLE
Introduce Structs to the WebGPU node system

### ISSUE THREAD

**Issue by Spiri0** [mrdoob/three.js#29639]
### Description

At the moment we hand each uniform over to the shaders individually. For more complex tasks it is desirable to do this with storageBuffers and structs. Bundling a lot of uniforms in a storageBuffer and then sending them to the GPU in one go is more efficient. By working on the indirectStorageBufferAttribute, I saw how the bindings are created with _getWGSLStructBinding in the WGSLNodeBuilder. I don't think we need any major changes if we generate the struct content with a structBuilder like in my codePen example.

### Solution

I have a codePen here that shows how it could work

![image](https://github.com/user-attachments/assets/3771047d-838f-47b6-892b-453941407482)

Link: https://codepen.io/Spiri0/pen/XWvpVWP?editors=0011

Normally in an app I would just update the values ​​of the uniforms, not create new objects everywhere in the update, as is the case here. Forgive me, my main concern here is struct and the array function. @sunag the pointer you created would probably have to point to the struct in the case of a struct.

I use this code directly in my three.webgpu.js and export and import struct and array. However, it is still unsuitable for a PR because the node system integrates significantly more scope with the other uniforms. Since I haven't dealt with the uniforms that intensively yet, I'd like to ask what you think of the approach. @RenauldRohlinger you will probably be interested in this too.

Of course I will continue to work on it, but if the current status inspires you to make good additions or you see better solutions then let me know.

### Alternatives

Hand over all uniforms individually to shader like now

**Comment by aardgoose** [comment]
uniforms aren't passed to shaders individually, they are already collected into uniform buffers and there is an existing PR that bundles all such uniform buffers into a single buffer object per render pass.: #27388

**Comment by Spiri0** [comment]
That sounds good. Then I'll bother with it for nothing. Well, it helps me understand the node system better, so I don't regret anything. But if you are already working on it then I will close this issue. Thanks for the reference.

**Comment by Spiri0** [comment]
I'm closing this issue due to redundancy to #27388

**Comment by aardgoose** [comment]
For reference, the mapping of uniforms to intermediate buffers uniform buffers is in:  src/renderers/common/UniformsGroup.js using mechanisms quite close to your suggestions.
