### ISSUE TITLE
ColladaLoader problems

### ISSUE THREAD

**Issue by crobi** [mrdoob/three.js#2963]
As discussed in #2954, here is a list of problems and feature requests with the current collada loader. Some of them should be easy to fix, some might require more work, so feel free to divide this into multiple issues.
- [x] The loader supports only one texture per material (last texture wins) and assigns all types of textures to the diffuse channel (see [here](https://github.com/mrdoob/three.js/blob/79c961b772797a3db7ecad8ad7339589c8e957c4/examples/js/loaders/ColladaLoader.js#L3130)).
- [ ] The loader does not support bump and normal maps. This feature is not part of the core collada spec, but both blender and 3dsmax place it under `<effect>/<profile_COMMON>/<technique>/<extra>/<technique>/<bump>`
- [ ] The loader does not support skins with multiple skeletons (see [here](https://github.com/mrdoob/three.js/blob/79c961b772797a3db7ecad8ad7339589c8e957c4/examples/js/loaders/ColladaLoader.js#L421) and [here](https://github.com/mrdoob/three.js/blob/79c961b772797a3db7ecad8ad7339589c8e957c4/examples/js/loaders/ColladaLoader.js#L568))
- [x] The loader does not support lights (see [here](https://github.com/mrdoob/three.js/blob/79c961b772797a3db7ecad8ad7339589c8e957c4/examples/js/loaders/ColladaLoader.js#L1833)).
- [ ] The loader has broken support for cameras. Orthographics cameras are not supported, and perspective cameras use a `fov` parameter (see [here](https://github.com/mrdoob/three.js/blob/79c961b772797a3db7ecad8ad7339589c8e957c4/examples/js/loaders/ColladaLoader.js#L837)), but should use the `yfov` paremeter (see [here](https://github.com/mrdoob/three.js/blob/79c961b772797a3db7ecad8ad7339589c8e957c4/examples/js/loaders/ColladaLoader.js#L3974)). Also note that the field of view parameter and aspect ration might be undefined and have to be computed from other elements (see collada spec, chapter on `perspective`). Also, the `aspect_ratio` is a string and not a number (see [here](https://github.com/mrdoob/three.js/blob/79c961b772797a3db7ecad8ad7339589c8e957c4/examples/js/loaders/ColladaLoader.js#L3983)).
- [ ] It's really difficult to tell from reading the spec, but I am not sure the loader handles bones correctly. Node SIDs do not need to be unique within the scene, and from what I understand, you have to start at the skeleton root node and iteratively perform a breadth-first search for the next SID part. See [here](https://github.com/mrdoob/three.js/blob/79c961b772797a3db7ecad8ad7339589c8e957c4/examples/js/loaders/ColladaLoader.js#L502), the collada spec for `COLLADA Target Addressing` and the `skin` element. No exporter that I know of uses non-unique SIDs, though.
- [ ] Some meshes are incompletely animated. I have one example where the root node of my skeleton is not animated, resulting in the character pelvis being fixed. I just cannot figure out why this happens. I do not own the mesh, so I cannot share it publicly. But send me a private message and I'll send it to you.

**Comment by migpics** [comment]
Hi there.  I am using the sample collada loader from threejs.org found here (http://threejs.org/examples/#webgl_loader_collada)  I am simply replacing the collada with a collada file from blender.
My results yield a static image and no animation.
My consol does not have any errors in it.
I am wondering if there are specs that I am not following for exporting the collada file.
Thanks
Miguel

**Comment by Mugen87** [comment]
`ColladaLoader2` has replaced the old `ColladaLoader` mentioned in this issue.
