### ISSUE TITLE
colorspace_fragment does not work with webgl2

### ISSUE THREAD

**Issue by pranav-pkasthana** [mrdoob/three.js#29645]
### Description

var colorspace_fragment = "gl_FragColor = linearToOutputTexel( gl_FragColor );";
this section uses gl_FragColor 
and gl_FragColor is not supported in webgl2

with version 168 of threejs I am getting this error

**Line2 is not working due to this** 
### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

168

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
> Line2 is not working due to this

But the following example uses `Line2` without issues:

https://threejs.org/examples/webgl_lines_fat

> and gl_FragColor is not supported in webgl2

`three.js` creates a custom define `gl_FragColor` for so it's possible to use it in WebGL 2 as well (except for `RawShaderMaterial`)

**Comment by Mugen87** [comment]
Closing unit a live example is provided.

**Comment by pranav-pkasthana** [comment]
I upgraded threejs version to 168, and found that it started giving error taht webgl1 is not supported. Then I changed to webgl2 and found that my shaders are not compatible and are not getting compiled.  So I changed the shaders to glsl 300 es and adjusted syntax accordingly. I changed LIneMaterial accordingly too.With glsl 300 es - gl_Fragcolor is not defined. This way I could not compile the shaders  and getting errors. Not sure how the LineMaterial is working with webgl2 and shader version less than 300 in Threejs example. Please help in understanding.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
