### ISSUE TITLE
depthNode: the default value of depthNode is invalid

### ISSUE THREAD

**Issue by Lafeu-p** [mrdoob/three.js#29659]
### Description

In the three.js example with a **webgpu_instance_points**, when enabling **logarithmicDepthBuffer**, the example encounters the following error.
<img width="1140" alt="image" src="https://github.com/user-attachments/assets/1d89bd98-6a67-48c9-9df3-c2f2896b1366">
I noticed that the issue was caused by not setting a value for depthNode. When I set **depthNode = depth,** the error disappeared. However, I noticed that three.js does have a default depthNode set.
<img width="825" alt="image" src="https://github.com/user-attachments/assets/2f79187e-20d9-4f90-bbb4-44d2e235964c">
Additionally, although directly setting depthNode = depth eliminates the error, the result is not as expected, as the depth appears to be chaotic.
<img width="326" alt="image" src="https://github.com/user-attachments/assets/92918f71-7b6c-413e-9502-7172cdd3faf8">

I noticed that the configuration for depth in the code didn't take effect, and upon debugging the shader, I found that the logarithmic depth-related shader code wasn't being used.
<img width="365" alt="image" src="https://github.com/user-attachments/assets/da1ba9e3-ea79-425b-8d19-0cb033933680">
If I modify this line of code to 
`depth.valueNode = depthNode`
 then I no longer need to manually set depthNode = node, and the depth behaves as expected. I'm a beginner with NodeMaterial, but I believe this is a bug, and I look forward to further feedback.
<img width="421" alt="image" src="https://github.com/user-attachments/assets/11898a15-7889-4220-860d-2154e7a14f6b">

### Reproduction steps

1.enabling **logarithmicDepthBuffer**,

### Code

```js
logarithmicDepthBuffer = true
```

### Live example

http://localhost:8080/examples/?q=instance#webgpu_instance_points

### Screenshots

<img width="365" alt="image" src="https://github.com/user-attachments/assets/da1ba9e3-ea79-425b-8d19-0cb033933680">

### Version

170dev

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
The runtime error occurs because the following line fails:

https://github.com/mrdoob/three.js/blob/3728a0aafd5ee04a9a4bc66eb3f56f556bd8da15/src/nodes/accessors/ModelViewProjectionNode.js#L27

That happens because `builder.context.mvp ` isn't defined for `InstancedPointsNodeMaterial`.

**Comment by Lafeu-p** [comment]
If I customize a material and have both a vertexNode and a fragmentNode, do I need to manually specify builder.context.mvp for each?

**Comment by Mugen87** [comment]
When I read the code correctly, then you have to define `builder.context.mvp` when defining a custom `vertexNode` and if you want to use logarithmic depth buffer. `ModelViewProjectionNode` is the only component which relies on `builder.context.mvp` and it is used by the logarithmic depth buffer implementation.

@sunag Maybe this bit needs to be revisited since we should not expect `builder.context.mvp` is correctly set in all instances when a custom `vertexNode` is used. If `builder.context.mvp` isn't defined, couldn't `ModelViewProjectionNode` fallback to the result of `vertexNode` (which is essentially `gl_Position`)?

**Comment by sunag** [comment]
> @sunag Maybe this bit needs to be revisited since we should not expect builder.context.mvp is correctly set in all instances when a custom vertexNode is used. If builder.context.mvp isn't defined, couldn't ModelViewProjectionNode fallback to the result of vertexNode (which is essentially gl_Position)?

Yes, this needs a review. When I visited this issue, I also wondered why we don't have a node to create these circles and use them in sprites and thus avoid duplication of code.

**Comment by Mugen87** [comment]
This issue has been fixed via #30108. `webgpu_instance_points` now works with logarithmic depth buffer 🎉
