### ISSUE TITLE
GLTFExporter sets a default metalness of 0.5

### ISSUE THREAD

**Issue by schwyzl** [mrdoob/three.js#29664]
### Description

If an object material is not a MeshStandardMaterial the GLTFExporter sets a default metallicFactor of 0.5. 

```
		if ( material.isMeshStandardMaterial ) {

			materialDef.pbrMetallicRoughness.metallicFactor = material.metalness;
			materialDef.pbrMetallicRoughness.roughnessFactor = material.roughness;

		} else {

			materialDef.pbrMetallicRoughness.metallicFactor = 0.5;
			materialDef.pbrMetallicRoughness.roughnessFactor = 0.5;

		}
```
https://github.com/mrdoob/three.js/blob/752400c13fba9e83dd0291bec8d3e0d4586fd2e1/examples/jsm/exporters/GLTFExporter.js#L1497

This should probably not happen. There is no such thing as semi-metalness in the real world so Three.js should probably choose 1 or 0 in this case. Seeing as this is a generic object exporter I would assume not adding any metalness is the more desirable behaviour.

**Comment by Mugen87** [comment]
How about `metallicFactor = 0;` and `roughnessFactor = 1;`? That would correspond to the default values of `MeshStandardMaterial`.

**Comment by schwyzl** [comment]
Yep, sounds like a good idea to match the standard material defaults.

**Comment by Mugen87** [comment]
Would like filing a PR with the suggested change?

It seems these values exist since the existing of the exporter and they were never discussed (see #11917).

**Comment by Mugen87** [comment]
In the meanwhile, I've filed a PR with the suggested defaults.
