### ISSUE TITLE
WebGPURenderer: `copyFramebufferToTexture()` is broken when called outside of `render()`.

### ISSUE THREAD

**Issue by ligaofeng0901** [mrdoob/three.js#29713]
### Description

In the old version, I use `renderer.copyFramebufferToTexture` to render something to texture. There are many generated textures from offscreen scenes with a shared `RenderTarget`. So I use `renderer.copyFramebufferToTexture` many times before the rendering of main scene.
After switching into WebGPU version, `renderer.copyFramebufferToTexture`  is broken, the reason is that I invoke `copyFramebufferToTexture` out of the `render()` method. The code of this line https://github.com/mrdoob/three.js/blob/48e6e2ee4e769013b911a079a433aecc2686d5b2/src/renderers/common/Renderer.js#L1286 
`this._currentRenderContext` is valid only when the code between the start and end of `render`.  And it always turns out `null` in my use case.

### Reproduction steps

1.
2.
3.

### Code

```js
 let oldRenderTarget = renderer.getRenderTarget();
  renderer.setRenderTarget(renderTarget);
  renderer.clear();
  renderer.render(this._mesh, _camera);
  renderer.copyFramebufferToTexture(outputTexture);
  renderer.setRenderTarget(oldRenderTarget);
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

r169

**Comment by ligaofeng0901** [comment]
> Do you mind sharing a live example that demonstrates the issue with `WebGPURenderer`?

https://jsfiddle.net/ligaofeng0901/xnh8zt1y/

**Comment by Mugen87** [comment]
I can confirm the issue. The problem is that `copyFramebufferToTexture()` requires a render context but it can't query it without a scene and camera.

We would run into the same issue if we would try to migrate [webgl_framebuffer_texture](https://threejs.org/examples/webgl_framebuffer_texture) to `WebGPURenderer`.
