### ISSUE TITLE
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by DongZeMan** [mrdoob/three.js#29711]
### Description

An error was reported when loading the pipeline compressed glb model while being a child of a microapplication

### Reproduction steps

1.  start app
2.  start the dock application for the microApp
3.  Embed the current app using the iframe sandbox into the microApp dock

### Code

```js
// code goes here
```
![image](https://github.com/user-attachments/assets/473e5993-fa8d-4c6c-829b-2ea604e11820)

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)
Don't have a live example I can provide

### Screenshots

![image](https://github.com/user-attachments/assets/a1302695-9651-422a-8e94-9375bc7b7e23)

### Version

0.164.1

### Device

Desktop

### Browser

Edge

### OS

Windows

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.
