### ISSUE TITLE
WebGPURenderer: `Animation.js` runs all the time in requestAnimationFrame.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#29712]
### Description

`renderers/common/Animation.js` runs the internal logic all the time in requestAnimationFrame.

https://github.com/mrdoob/three.js/blob/48e6e2ee4e769013b911a079a433aecc2686d5b2/src/renderers/common/Animation.js#L17-L31

Scene initialization I render once, but debugging found that the internal logic of `Animation.js` keeps running inside.

I'm not sure if there is a problem if this code doesn't run all the time.

### Reproduction steps

1. Run the code
2. Open dev tool
3. `Info` change all the time.

### Code

```js
import { PerspectiveCamera, Scene, WebGPURenderer } from 'three/webgpu';

const scene = new Scene();
const camera = new PerspectiveCamera();
const renderer = new WebGPURenderer();
renderer.render( scene, camera );

setInterval( () => console.log( renderer.info ), 1000 );
```

### Live example

NONE

### Version

r170dev

**Comment by Mugen87** [comment]
Normally, apps are expected to use `setAnimationLoop()`. If they don't and use a custom animation loop or rendering on demand, it would be necessary to update the `frameId` manually. Just a call of `render()` is not sufficient to raise the id counter since a frame often need more than one render call to be generated.

Hence, the current approach seems to be the safest with the least implications for apps.

**Comment by linbingquan** [comment]
> Normally, apps are expected to use `setAnimationLoop()`. If they don't and use a custom animation loop or rendering on demand, it would be necessary to update the `frameId` manually. Just a call of `render()` is not sufficient to raise the id counter since a frame often need more than one render call to be generated.
> 
> Hence, the current approach seems to be the safest with the least implications for apps.

Thank you for your reply and explanation. Now I understand frameId a little bit more.

Right now this logic doesn't pose a performance problem, but I feel like it's a bit of a waste of CUP, even though the hardware is pretty good these days.

I don't know the feasibility of my plan. For example, we can internally update frameId on demand, kind of like a version of WebGLRenderer. I don't have a great idea or plan right now...

In the future, a feasible plan has been proposed, but the cost of change may be large.

**Comment by Mugen87** [comment]
If someone comes up with a proposal, it's best to file a PR. In the meanwhile, I think this issue can be closed.
