### ISSUE TITLE
ConeGeometry has wrong side faces and triangles

### ISSUE THREAD

**Issue by TheWindRest** [mrdoob/three.js#29721]
### Description

when create the conegeometry,set the heightSegments up to 1,example 3,there is a error that side faces show only half of faces and triangles, some triangles disappear
![PixPin_2024-10-22_15-52-44](https://github.com/user-attachments/assets/4217564c-ede2-4673-961b-96ceb5a44be9)

### Reproduction steps

1. Create a cone geometry
2. set the heightSegments to 3, others keep default
3. check the side faces,there is an error

### Code

    const geometry = new THREE.ConeGeometry(1, 1, 32, 3);
    const material = new THREE.MeshBasicMaterial();
    const mesh = new THREE.Mesh(geometry, material);

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Screenshots

![PixPin_2024-10-22_15-52-44](https://github.com/user-attachments/assets/8fbdac26-0b08-4f7c-8124-a5322bdb24c7)

### Version

r169

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
This is actually a regression since this worked with `r168`, see https://jsfiddle.net/vwgLxn63/.

Reverting #29460 fixes the issue.

/ping @gkjohnson
