### ISSUE TITLE
Malware website in the example list

### ISSUE THREAD

**Issue by s-rigaud** [mrdoob/three.js#29758]
### Description

On the example main page https://threejs.org/, the example with a small car as a picture links to a malicious website www.ashortjourney.com.
![image](https://github.com/user-attachments/assets/b572500c-a43f-4bc3-88c2-e3a1b64413ed)

### Reproduction steps

1. Go to https://threejs.org/
2. **_Don't click on the link (unless you are in a safe VM) !_**

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

r169

**Comment by Mugen87** [comment]
I have removed the link from the homepage: https://github.com/mrdoob/three.js/commit/f9fc1fd3e8f00a6a209ac5bbea9b85e365c8c565

It might take a bit until the environment is updated though.

> Don't click on the link (unless you are in a safe VM) !

Thanks for the heads-up!

**Comment by Mugen87** [comment]
@mrdoob We usually comment out links but would you be okay to completely remove it in this instance? Devs might still copy/paste outdated links to check out the content.

**Comment by mrdoob** [comment]
No, I think we should keep it.

Someone advanced enough to look at a html source code, copying a commented out url, and navigating to it most likely can identify if a website is not genuine or not... 🤓
