### ISSUE TITLE
Vector4 missing `divide` method

### ISSUE THREAD

**Issue by kristiker** [mrdoob/three.js#29751]
### Description

Vector4 is missing `divide(Vector4)` method. It only has `divideScalar`, unlike Vector2 which also has `divide`.

### Solution

divide(Vector4)

### Alternatives

create a new Vector4 with component wise division like so
```js
new Vector4(v1.x / v2.x, v1.y / v2.y, v1.z / v2.z, v1.w / v2.w);
```

**Comment by Mugen87** [comment]
And since there is also `Vector4.multiply()`, it makes sense to add `divide()` as well.

@WestLangley Does that sounds okay to you?

**Comment by Mugen87** [comment]
@kristiker Do you want to file a PR? Next to the implementation, it would be good to update the docs and add a unit test.

https://threejs.org/docs/index.html#api/en/math/Vector4
https://github.com/mrdoob/three.js/blob/dev/test/unit/src/math/Vector4.tests.js
