### ISSUE TITLE
Audio cannot be started muted

### ISSUE THREAD

**Issue by trekar99** [mrdoob/three.js#29764]
### Description

My program requires multiple audios to start at the same time at startup, so that they are synchronized, but I need to start them muted. The problem is that they play for a fraction of a second when starting them this way, preventing it from being an initial mute.

### Reproduction steps

// Set mute
for(const sound of sounds) sound.setVolume(0)

// Loop
for(const sound of sounds) sound.loop = true

// Play song
for(const sound of sounds) sound.play()

### Code

```js
// Set mute
for(const sound of sounds) sound.setVolume(0)

// Loop
for(const sound of sounds) sound.loop = true

// Play song
for(const sound of sounds) sound.play()
```

### Live example

https://daftpunkins.vercel.app/

### Version

0.166.1

**Comment by Mugen87** [comment]
Please ask at the [forum](https://discourse.threejs.org/) for help.
