### ISSUE TITLE
EXT_MATERIALS_BUMP is not documented

### ISSUE THREAD

**Issue by rotu** [mrdoob/three.js#29778]
### Description

bumpmaps appear to be supported but aren't mentioned on the docs:
https://threejs.org/docs/?q=EXT_MATERIALS_BUMP#examples/en/exporters/GLTFExporter

### Solution

Document this as a supported extension

### Alternatives

Don't document it, I guess?

**Comment by mrdoob** [comment]
Would you like to make a PR with the fix?
https://github.com/mrdoob/three.js/edit/dev/docs/examples/en/exporters/GLTFExporter.html
