### ISSUE TITLE
Should the documentation for "NearestMipmapLinearFilter" and "LinearMipmapNearestFilter" constants be swapped?

### ISSUE THREAD

**Issue by PoseidonEnergy** [mrdoob/three.js#29787]
Update - this older issue might be related: https://github.com/mrdoob/three.js/issues/6457

### Description

I was reading the _Texture Constants_ documentation (https://threejs.org/docs/index.html#api/en/constants/Textures) and noticed the descriptions for "NearestMipmapLinearFilter" and "LinearMipmapNearestFilter" might be mismatched...

> **NearestMipmapLinearFilter:** chooses the two mipmaps that most closely match the size of the pixel being textured and uses the **NearestFilter** criterion to produce a texture value from each mipmap. The final texture value is a weighted average of those two values.

> **LinearMipmapNearestFilter:** chooses the mipmap that most closely matches the size of the pixel being textured and uses the **LinearFilter** criterion (a weighted average of the four texels that are closest to the center of the pixel) to produce a texture value.

More specifically, the description for **NearestMipmapLinearFilter** mentions choosing two mipmaps and using a nearest filter, even though its name implies choosing a single mipmap **(NearestMipmap)** and using a linear filter **(LinearFilter).**

Likewise, the description for **LinearMipmapNearestFilter** mentions choosing a single mipmap and using a linear filter, even though its name implies choosing two mipmaps **(LinearMipmap)** and using a nearest filter **(NearestFilter).**

![image](https://github.com/user-attachments/assets/7db89e5a-c4ef-4ba4-aea4-19ba5552701e)

### Reproduction steps

-

### Code

-

### Live example

-

### Version

r170

**Comment by Mugen87** [comment]
The texts have been adapted from the OpenGL reference: https://registry.khronos.org/OpenGL-Refpages/es2.0/xhtml/glTexParameter.xml:

> GL_NEAREST_MIPMAP_LINEAR
Chooses the two mipmaps that most closely match the size of the pixel being textured and uses the GL_NEAREST criterion (the texture element nearest to the center of the pixel) to produce a texture value from each mipmap. The final texture value is a weighted average of those two values.

> GL_LINEAR_MIPMAP_NEAREST
Chooses the mipmap that most closely matches the size of the pixel being textured and uses the GL_LINEAR criterion (a weighted average of the four texture elements that are closest to the center of the pixel) to produce a texture value.
