### ISSUE TITLE
WebGPURenderer: error with empty compressed textures

### ISSUE THREAD

**Issue by vlucendo** [mrdoob/three.js#29785]
### Description

It is very common to assign an empty texture to a uniform while the asset loads, and then copy the loaded data to it once it's available. On WebGPU renderer this throws an error due to the lack of mipmaps.

### Reproduction steps

1. Assign an empty compressed texture to a uniform
2. Render something with a shader using that uniform

### Code

```js
const testLoader = new KTX2Loader();
testLoader.detectSupport(webgpurenderer);
testLoader.setTranscoderPath(`libs/basis/`);

const cTexture = new CompressedTexture();
const textureNode = texture(cTexture);

testLoader.loadAsync('url_of_new_texture.ktx2').then((newTexture) => {
    cTexture.copy(newTexture);
    cTexture.needsUpdate = true;
});

 const fs = wgslFn(/* wgsl */ `
  fn test(
      vUv: vec2f,
      tex: texture_2d<f32>,
      tex_sampler: sampler
  ) -> vec4<f32> {
      var lala = textureSample(tex, tex_sampler, vUv);
      return vec4f(lala.rgb, 1.0);
  }
`);

this.material.fragmentNode = fs({
    vUv: varyingvUv,
    tex: textureNode,
    tex_sampler: textureNode,
});

// ... etc

```

### Live example

* [jsfiddle](https://jsfiddle.net/egvoma2x/1/)

### Version

r170

**Comment by Mugen87** [comment]
I think this has been overlooked since we have only tested compressed textures with `KTX2Loader` so far. We then use `loadAsync()` which makes sure the compressed texture is ready on the first usage.
