### ISSUE TITLE
geometry.setAttribute is not working

### ISSUE THREAD

**Issue by Lafeu-p** [mrdoob/three.js#29795]
### Description

I used to work with **WebGLRenderer** and often had requirements for custom meshes, such as defining an **IconMesh** that includes **IconGeometry** (extending from **BufferGeometry**) and an IconMaterial. **IconGeometry** requires an attribute for rendering, and I use `geometry.setAttribute('position', new Float32BufferAttribute(array, 3))` to update the attribute. 
For example, during initialization, I use `geometry.setAttribute('position', new Float32BufferAttribute(array, 3))` with array.length being **1200**. Later, I have an update requirement where the array changes and array.length becomes **2400**. At this point, I again use geometry.setAttribute('position', new Float32BufferAttribute(array, 3)) to update the attribute. This worked well with WebGLRenderer, but recently when using WebGPURenderer, it results in an error
<img width="691" alt="image" src="https://github.com/user-attachments/assets/e16eb54c-7a21-4165-ae45-aed092cc0df0">

At this point, I need to call material.needsUpdate = true to update the material for it to take effect. It doesn’t seem reasonable that updating an attribute would require recompiling the material. 
I understand that it’s best not to modify the size of the buffer in BufferGeometry, as doing so would likely cause the buffer to be recreated. However, in my use case (based on WebGLRenderer), this hasn’t caused any noticeable performance issues, and being able to reset the size of the attribute is what I want.

### Reproduction steps

1. init geometry based on WebGPURenderer
2. geometry.setAttribute('position', new Float32BufferAttribute(array, 3)),array.length being 1200
3. geometry.setAttribute('position', new Float32BufferAttribute(array, 3)),array.length being 2400

### Code

```js
geometry.setAttribute('position', new Float32BufferAttribute(array, 3))
```

### Live example

empty

### Version

170dev

**Comment by Mugen87** [comment]
The mentioned workflow is not supported in `WebGPURenderer` anymore since we don't allow buffer attributes to be overwritten. That was already an anti-pattern with `WebGLRenderer`. 

You have to define attributes once with sufficient size and then just update them. That means it is not allowed to _overwrite_ the buffer attribute with `setAttribute()` since that potentially creates memory leaks. If a resize is required, you have to call `dispose()` on the geometry and then create a new one with new attributes.

Related https://github.com/mrdoob/three.js/issues/29452#issuecomment-2430303542.

**Comment by Lafeu-p** [comment]
I completely agree with your point of view. when I dispose the old geometry and create a new one, and then set the attribute, the error no longer appears, but the setAttribute dose not take effect, and the rendered data is still the old one. It only works when I call `material.needsUpdate=true`. What could be the reason for the?

**Comment by Mugen87** [comment]
Any chances to demonstrate this issue with a live example?

**Comment by Lafeu-p** [comment]
[https://jsfiddle.net/4Lvpcqtz/](url)
I made some modifications to the 'webgpu_instance_point' example in three.js and was able to reproduce this issue. 
I added a **change** method, which, when called, recreates a geometry and updates the positions to make the points offset slightly from their original positions.
`
const config = {
  change: () => {
    const geometry = new InstancedPointsGeometry()
    positions.forEach((_, i) => {
      positions[i] += 1
    })
    positions.push(positions[0], positions[1], positions[2])
    geometry.setPositions(positions)

    instancedPoints.geometry = geometry

    console.log("set positions")

    // material.needsUpdate = true;
  },
}

gui.add(config, "change")
`

When the change method is triggered, nothing happens. However, if I uncomment **material.needsUpdate = true**, the update succeeds.
I sincerely hope to receive your response.

**Comment by Mugen87** [comment]
The problem is that `InstancedPointsGeometry.setPositions()` overwrites the `instancePosition` attribute with `setAttribute()` which should not be done. 

Methods like `setPositions()` and `setColors()` are currently design for a single time usage during construction time.

**Comment by Lafeu-p** [comment]
But here I am creating a new geometry, without modifying the old one.
const geometry = new InstancedPointsGeometry();
```
**const geometry = new InstancedPointsGeometry();**
positions.forEach( ( _, i ) => {

	positions[ i ] += 1;

} );
positions.push( positions[ 0 ], positions[ 1 ], positions[ 2 ] );
geometry.setPositions( positions );

**instancedPoints.geometry = geometry;**

console.log( 'set positions' );

// material.needsUpdate = true;
```

**Comment by Mugen87** [comment]
You're right! This must be related to instancing somehow.

**Comment by Mugen87** [comment]
It seems using normal geometries are also affected. Even setting `needsUpdate = true` does not help.

https://jsfiddle.net/bohv5pag/1/

**Comment by sunag** [comment]
Hmm... I will check this.

**Comment by Mugen87** [comment]
I can confirm the PR https://github.com/mrdoob/three.js/pull/29807 fixed both fiddles 🎉 .

**Comment by Lafeu-p** [comment]
when I update the geometry, it indeed takes effect, but this also causes the material to update. I would like the geometry update to not trigger a material recompile, as the performance overhead from updating the material is too high. Is it by design that materials need to be updated in Node? Is there a way to resolve this issue?
Here's an example to illustrate this problen: when calling change, the material will be re-setup.
[example](https://jsfiddle.net/ubh8o3xq/)

**Comment by Lafeu-p** [comment]
I tried updating the geometry again, but the material still gets updated as well.
[example](https://jsfiddle.net/ubh8o3xq/) @sunag

**Comment by sunag** [comment]
@Lafeu-p I tested with the @Mugen87's example https://github.com/mrdoob/three.js/issues/29795#issuecomment-2454400185 and I checked the `WebGPUBackend.createNodeBuilder()` and `WebGPUBackend.createProgram()`, there is no additional code generation. 

Could you provide a new example of the issue?

**Comment by Lafeu-p** [comment]
[example](https://jsfiddle.net/pvwzkb7y/1/)
When I call the change method, I only want to update the geometry.
```
  change: () => {
    i++
    mesh.geometry.dispose()
    mesh.geometry = new THREE.BoxGeometry(i, i, i)
    //mesh.material.needsUpdate = true;
  }
```
But every time I call the change method, my material updates and the color changes.
 the material updates might be related to whether the material is custom-made. Perhaps the default MeshBasicMaterial does not have this issue.

**Comment by sunag** [comment]
Thanks for the example, [this PR](https://github.com/mrdoob/three.js/pull/29873) should fix it.

**Comment by Lafeu-p** [comment]
@sunag In WebGL, I occasionally use mat4, but WebGPU does not support mat4. Therefore, I have to use 4 attributes instead. I would like to ask how to update these attributes in such a situation.
like this [https://discourse.threejs.org/t/how-to-make-a-mat4-attribute-in-webgpurenderer/74019](https://discourse.threejs.org/t/how-to-make-a-mat4-attribute-in-webgpurenderer/74019)
