### ISSUE TITLE
Batchedmesh does not work with ExtrudeGeometry

### ISSUE THREAD

**Issue by ehtick** [mrdoob/three.js#29808]
### Description

Try to add a ExtrudeGeometry on a BatchedMesh, this will respond with a error 'TypeError: t.getIndex is not a function'

### Reproduction steps

1.
2.
3.

### Code

	const length = 12, width = 8;

  const shape = new THREE.Shape();
  shape.moveTo( 0,0 );
  shape.lineTo( 0, width );
  shape.lineTo( length, width );
  shape.lineTo( length, 0 );
  shape.lineTo( 0, 0 );

  const extrudeSettings = {
    steps: 2,
    depth: 16,
    bevelEnabled: true,
    bevelThickness: 1,
    bevelSize: 1,
    bevelOffset: 0,
    bevelSegments: 1
  };

	const extrudeGeometry = new THREE.ExtrudeGeometry( shape, extrudeSettings );
	const extrudeMesh = new THREE.Mesh( extrudeGeometry, material ) ;

  const extrudeGeometryId = batchedMesh.addGeometry( extrudeMesh );  // THIS GIVES THE ERROR
  // create instances of those geometries
  const extrudeInstancedId = batchedMesh.addInstance( extrudeGeometryId );

### Live example

[* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

https://jsfiddle.net/Maddog_Eddy/z2c0p1b7/14/

### Version

r169

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
> const extrudeGeometryId = batchedMesh.addGeometry( extrudeMesh ); // THIS GIVES THE ERROR

You are adding an instance of `THREE.Mesh` which is invalid. You are supposed to pass a geometry.

Even when doing so you will get a validation error:

> three.module.js:33963 Uncaught Error: BatchedMesh: All geometries must consistently have "index".

That's because `ExtrudeGeometry` produces non-indexed geometries. But you can generate an index quite simple via:
```js
const index = Array.from( Array( positionAttribute.count ).keys() );
extrudeGeometry.setIndex( index );
```

FYI: Wireframes are not supported yet, see #29045.

**Comment by Mugen87** [comment]
Please use the forum if you need more help: https://discourse.threejs.org/

**Comment by ehtick** [comment]
Thought it was an error, will use the forum next time.
