### ISSUE TITLE
ColorManagement does not support treeshake.

### ISSUE THREAD

**Issue by linbingquan** [mrdoob/three.js#29815]
### Description

As the title says.

### Reproduction steps

1. pnpm create vite@latest app --template vanilla
2. replace code to `main.js`
3. pnpm build

```js
// main.js
import { MathUtils } from "three";

const v = MathUtils.clamp(0.5, 0, 1);
console.log(v);
```

### Code

```js
// main.js
import { MathUtils } from "three";

const v = MathUtils.clamp(0.5, 0, 1);
console.log(v);
```

### Live example

None

### Version

dev

### Device

Desktop

### OS

Windows

**Comment by linbingquan** [comment]
@Mugen87 `MathUtils.*` method does not support treeshake. Whether we want to export its methods.

```diff
--- a/src/Three.js
+++ b/src/Three.js
@@ -111,7 +111,7 @@ 
 export { Triangle } from './math/Triangle.js';
-export { MathUtils } from './math/MathUtils.js';
+export * from './math/MathUtils.js';
 export { Spherical } from './math/Spherical.js';
```

**Comment by mrdoob** [comment]
Is this issue about `MathUtils` or about `ColorManagement`?

**Comment by linbingquan** [comment]
> Is this issue about `MathUtils` or about `ColorManagement`?

About `MathUtils`. There are two subproblems in this issue, but I didn't actually mention `MathUtils` before `ColorManagement`.

**Comment by Mugen87** [comment]
I don't think we need to support tree-shaking on that level. `MathUtils` isn't a large component...
