### ISSUE TITLE
Doubts about passing custom renderTarget into EffectComposer

### ISSUE THREAD

**Issue by ElvisWangTech** [mrdoob/three.js#29817]
### Description

If I customize a custom RenderTarget in EffectComposer, devicePixelRatio is multiplied again when calling addPass. This will cause an error to be reported when creating the render of CustomOutlinePass: "FrameBuffer is incomplete". If I do not multiply the devicePixelRatio when creating the RenderTarget, it will not display properly on a high-resolution monitor. So currently I can only not pass RenderTarget. Is this a bug? In what scenarios do I need to pass RenderTarget? If RenderTarget must be passed, can the problem described above be avoided?

### Reproduction steps

1.
2.
3.

### Code

```js
    const parameters = {
      format: THREE.RGBAFormat,
    };

    const size = this.renderer.getDrawingBufferSize( new THREE.Vector2() );
    const renderTarget = new THREE.WebGLRenderTarget( size.width, size.height, parameters );
    this.composer = new EffectComposer(this.renderer, renderTarget);

    const pass = new RenderPass(this.bgScene, this.camera);
    pass.clear = true
    pass.clearDepth = true
    this.composer.addPass(pass);

    // Outline pass.
    this.customOutline = new CustomOutlinePass(
      new THREE.Vector2(size.x, size.y),
      this.bgScene,
      this.camera
    );
    this.composer.addPass(this.customOutline);

    // Antialias pass.
    this.effectFXAA = new ShaderPass(FXAAShader);
    this.effectFXAA.uniforms["resolution"].value.set(
      1 / size.x,
      1 / size.y
    );
    this.composer.addPass(this.effectFXAA);
```
Partial code of render method in CustomOutlinePass
```js
const renderBufferProps = renderer.properties.get( readBuffer );
const _gl = renderer.getContext()
const depthRenderBuffer = renderBufferProps.__webglDepthRenderbuffer || renderBufferProps.__webglDepthbuffer;
if ( depthRenderBuffer ) 
	_gl.framebufferRenderbuffer( _gl.FRAMEBUFFER, _gl.DEPTH_ATTACHMENT, _gl.RENDERBUFFER, depthRenderBuffer );
```
addPass in EffectComposer 
```js
addPass( pass ) {

  this.passes.push( pass );
  pass.setSize( this._width * this._pixelRatio, this._height * this._pixelRatio );

}
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

0.167.1

### Device

Desktop

### Browser

Edge

### OS

Windows

**Comment by Mugen87** [comment]
Instead of using:
```js
const size = this.renderer.getDrawingBufferSize( new THREE.Vector2() );
```
try it with:
```js
const size = this.renderer.getSize( new THREE.Vector2() );
```

**Comment by Mugen87** [comment]
> In what scenarios do I need to pass RenderTarget? 

Normally, you only have to pass a custom render target if you want to configure multisampling. If that is not the case, let the composer create the render target for you.

If you still want to pass a custom render target, you can workaround the issue in your `CustomOutlinePass` module by overwriting `setPass()`.

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) if you need more help.
