### ISSUE TITLE
OrbitControls's changeEvent not dispatch  when change camera.zoom in code , only on mouseWheel can dispatch

### ISSUE THREAD

**Issue by MrYang614** [mrdoob/three.js#29814]
### Description

OrbitControls's changeEvent not dispatch  when change camera.zoom in code , only on mouseWheel can dispatch . 

I use tween to control the attribute `zoom` in orthoCamera , the changeEvent not dispatched .  I check the code , found  the scale will change only in mousewheel .  

why not create an another  `__preZoom` like this , for listening zoomChange , and old preZoom listening for updateProjectionMatrix
```Constructor
let __preZoom = 1
```
```
zoomChange = currentZoom !== __preZoom
__preZoom = currentZoom
```

### Reproduction steps

1. create orthographicCamera and controls 
2. set orthographicCamera.zoom = 2
3. changeEvent not dispatch 

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

0.162

**Comment by Mugen87** [comment]
The events in the control classes honor state changes which are triggered by the class itself. If you manipulate the managed object (e.g. camera) from outside, it is not guaranteed the controls can detect this change. 

IMO, I think it's not the task of the controls to act as a complete observer for managed objects. If you need that, it's best if you observer the object's state on app level or use a custom version of `OrbitControls` that let's you trigger a dolly over the control class (that means you do not directly manipulate `camera.zoom`).
