### ISSUE TITLE
WebGPURenderer: Update for depth texture sampling restrictions

### ISSUE THREAD

**Issue by greggman** [mrdoob/three.js#29852]
### Description

Chrome shipped with a bug where it allowed sampling depth textures with linear filting even though the spec said this is not allowed. They recently added a deprecation warning. You can see this warning by using Chrome Canary 132.0.6830.0 (Nov 10th) or newer.

Several of the WebGPU samples will trigger the deprecation warning. Eventually Chrome will remove support (probably not for several months). Firefox and Safari, when they do actually ship WebGPU, will likely follow the spec and correctly not support this.

### Reproduction steps

1. Use Chrome Canary from Nov 10th or newer
2. Run the https://threejs.org/examples/?q=webgpu#webgpu_backdrop example
3. Open the devtools to the JavaScript console

See ths warning:

> Using a TextureType::Depth with SamplerType::Filtering is deprecated.TextureType::Depth can only be used with SamplerType::NonFiltering or SamplerType::Comparison.

### Code

n/a ---------------

### Live example

https://threejs.org/examples/?q=webgpu#webgpu_backdrop

### Version

r170

**Comment by mrdoob** [comment]
List of affected examples: 

```
backdrop
backdrop/area
backdrop/water
depth texture
postprocessing/ao
postprocessing/pixel
postprocessing/ssr
refraction
shadowmap/vsm
water
```

**Comment by mrdoob** [comment]
@sunag Should TSL workaround this?

**Comment by sunag** [comment]
> @sunag Should TSL workaround this?

I think a TSL workaround will be useful, although most of the examples shouldn't be needed.
