### ISSUE TITLE
WebGPURenderer: incorrect texture dimensions in shaders

### ISSUE THREAD

**Issue by vlucendo** [mrdoob/three.js#29851]
### Description

When creating a `texture` node from a `Rendertarget`'s texture and resizing it via `.setSize`, the texture size is not recognized by wgsl shaders when doing `textureDimensions(...)`.

### Reproduction steps

1. Create a texture node from a RenderTarget's texture
2. Create a wgsl shader that makes use of that texture node
3. Make the shader behave in different ways depending on the size of the texture. It's always the same even if the size of the RenderTarget changes.

### Code

See fiddle

### Live example

* [WebGPURenderer](https://jsfiddle.net/gbLwkphm/3/) - The color of the sphere should change from white to pink every 500ms, but it stays the same

### Version

r170

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by sunag** [comment]
The `RenderTarget` is not updated while it is not rendered, in normal situations this should not happen since the resized RenderTarget will need to be re-rendered after resized, otherwise it would return an empty texture.

```js
const nScene = new THREE.Scene();
...

rt.setSize(size, size);

renderer.setRenderTarget( rt );
renderer.render( nScene, camera );
renderer.setRenderTarget( null );
```

**Comment by vlucendo** [comment]
Oh I see, thanks. My issue still shows up when I am trying to create a custom postprocessing pass based on the code at: `examples/jsm/tsl/display/SMAANode.js` but using `wgslFn` instead.

When creating the pass seems the input scene pass gets wrapped into a RTTNode, and when I use this node as a uniform for the shader that performs the operations, the correct texture size is only recognized at the first render.

Here's a minimal fiddle of what I'm experiencing: [Custom postprocessing fiddle](https://jsfiddle.net/pma2tjc0/) (square should go from red to yellow, but stays red)

I wonder if I'm missing something of if there's a something not updating as expected internally.

**Comment by sunag** [comment]
Thanks for the example, try replacing `const testpass = test( scenepass );` with `const testpass` = `test(scenepass.getTextureNode());`. That way the reference will be a `TextureNode` instead of a procedural Node.

**Comment by vlucendo** [comment]
Thank you, indeed that makes it behave as I was expecting 🎉 
Removing the `convertToTexture(...)` from `nodeObject(new testNode(convertToTexture(node)));` after the change seems to work as well.

[Updated fiddle](https://jsfiddle.net/v4w5faLh/)
