### ISSUE TITLE
DecalGeometry.clone() broken;

### ISSUE THREAD

**Issue by Benjythebee** [mrdoob/three.js#29859]
### Description

Hi,
DecalGeometry.clone() broke since a recent new release;

Here is a reproduction https://jsfiddle.net/0186fxp3/.
See line 92
```
      try{
      	geometryClone = decalGeometry.clone()
      }catch(e){
      	console.error(e.toString())
      }
 ```

It seems the mesh isn't passed to the [constructor of the geometry](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/geometries/DecalGeometry.js#L26).

### Reproduction steps

1. create new decalGeometry
2. call decalGeometry.clone()

### Code

```
      try{
      	geometryClone = decalGeometry.clone()
      }catch(e){
      	console.error(e.toString())
      }
 ```

### Live example

 https://jsfiddle.net/0186fxp3/

### Screenshots

![image](https://github.com/user-attachments/assets/225a3d9e-b8ee-484a-b768-4f6ec1b9ff45)

### Version

0.169, 0.170

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Benjythebee** [comment]
I've been trying to bake decals onto a texture 😓 

Testing with `0.159` I don't see any error in the console, but you're right that nothing is happening.

Maybe throwing an error that explains what you're saying would be an improvement then?

```
	clone() {

		/**
		 * @see https://github.com/mrdoob/three.js/issues/29859#issuecomment-2468818889
		 */
		throw new Error( 'Cannnot clone a DecalGeometry. they are unique so a cloned geometry can\'t be used for other decal mesh instances' );

	}
```

**Comment by Benjythebee** [comment]
I think it's generally a good thing to add defaults to the constructor.
I'm worried that quietly failing
```
if ( positionAttribute === undefined ) return; // empty geometry
```
will cause more people to be confused around why cloning isn't working properly. I can already see more Github issues around it in the future! 😛 

Maybe you could add a warn?


If I were to refactor the class, I'd 

- move the generation code outside of the constructor in a "generate" function,
- give the constructor defaults
- clone () would be no different;
- add a new  setter `mesh()` that will call `generate` on new mesh set;
- add a new setter `position()` that ...
- same for all constructor options

However I'm not sure if it's an accepted Three.JS practice

**Comment by Mugen87** [comment]
> will cause more people to be confused around why cloning isn't working properly

Actually the addition of default parameters should fix the clone.

**Comment by Benjythebee** [comment]
Fair enough then, I haven't really tested it; do you feel comfortable making a PR?

**Comment by Mugen87** [comment]
Yes, I'll file one.
