### ISSUE TITLE
Invalid URL error when loading with GLTFLoader in Vitest

### ISSUE THREAD

**Issue by CraigKnoblauch** [mrdoob/three.js#29869]
### Description

I'm attempting to use GLTFLoader in a vitest test case. Every time I try to load my glb file, I get the following error:
```
Caused by: TypeError: Invalid URL: ./test.glb
 ❯ new URLImpl node_modules/whatwg-url/lib/URL-impl.js:23:13
 ❯ Object.exports.setup node_modules/whatwg-url/lib/URL.js:54:12
 ❯ new URL node_modules/whatwg-url/lib/URL.js:115:22
 ❯ FileLoader.load node_modules/three/build/three.module.js:44831:15
 ❯ GLTFLoader.load node_modules/three/examples/jsm/loaders/GLTFLoader.js:241:10
 ❯ test/GLTFLoader.test.js:7:16
```
I've tried every path combination I can think of. Including an absolute path that I triple checked for accuracy.

### Reproduction steps

Within a vitest test case:
1. `const loader = new GLTFLoader()`
2. `loader.load('./test.glb', (gltf) => { expect(gltf).not.toBeUndefined()  })`

I've prepared a repository that captures this bug. It's a fresh Vite app with vanilla JS. You can access it here: https://github.com/CraigKnoblauch/gltf-loader-with-vitest

After `npm install`, execute `npm run test` to run the test case and produce the error. Please try with an absolute path on your system.

The glb is a plane with a few cubes. I've included a picture below. 

### Code

https://github.com/CraigKnoblauch/gltf-loader-with-vitest
```js
import { it, expect, describe } from 'vitest'
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js'

describe('GLTFLoader', () => {
    it('Should load gltf', () => {
        const loader = new GLTFLoader()
        loader.load('./test.glb', (gltf) => {
            expect(gltf).not.toBeUndefined()  
        })
    })
})
```

### Live example

Sorry I don't think this applies to have a live example

### Screenshots

![image](https://github.com/user-attachments/assets/1de9f376-bbff-451f-8701-0ed1710ca00c)

### Version

r170

### Device

Desktop

### OS

Linux

**Comment by Mugen87** [comment]
Please ask for help at the [forum](https://discourse.threejs.org/) or stackoverflow.
