### ISSUE TITLE
WebGPURenderer default maxBufferSize too small

### ISSUE THREAD

**Issue by AndrewChan2022** [mrdoob/three.js#29865]
### Description

WebGPURenderer backend default device.maxBufferSize = 256M too small, WebGLRenderer has no such limit.

However hardware limit is more than 256M, so user need explicitly get adapter.maxBufferSize to set param.requiredLimits.maxBufferSize.

Also check other limit such as maxStorageBufferBindingSize, ...

### Solution

WebGPUBackend set necessary limit from adapter to device if user not set.

### Alternatives

or a flag to require set limit from adapter to device.

**Comment by Mugen87** [comment]
WebGPU has the concept that when requesting a device, you get by default the minimum limits with no optional features so the app hopefully runs on all WebGPU supporting hardware.

It seems this issue is about always requesting the device limits. However, there are resources on the web which do not recommend this pattern (see https://webgpufundamentals.org/webgpu/lessons/webgpu-limits-and-features.html section "Don't request everything"). However, `WebGPURenderer` already request all supported features (see https://github.com/mrdoob/three.js/pull/25867#discussion_r1169085490 for the reason) so one could argue to do the same for limits.

I wonder if you could get a recommendation of a WebGPU maintainer. Should we always request the limits or leave this up to the developer.

**Comment by mrdoob** [comment]
> Since the developers already have the option to configure the limits, I vote to not change anything right now.

Sounds good.

I also asked WebGPU developers and this is what they said:

> I'd leave it up to the developer. Otherwise you may be lots of apps running on the developer's machine but not the customer's. Requiring the developer to ask is at least supposed to make them aware that they are choosing to have their app not run everywhere.

**Comment by Spiri0** [comment]
@AndrewChan2022 You can increase the limits yourself in three.weggpu.js if you absolutely need them. I tested this and it gave me a buffer size that was almost 8 times larger. I don't need that. I was just curious about the limits my hardware allows and in some parts these are significantly larger. But I don't dare assess how stable it is to push the limits beyond the set limits.

But if this is important to you, look for the device setup in three.webgpu.js and add the highlighted parts to it
	
	
```
let device;

if ( parameters.device === undefined ) {

	const adapterOptions = {
		powerPreference: parameters.powerPreference
	};

	const adapter = await navigator.gpu.requestAdapter( adapterOptions );

	if ( adapter === null ) {

		throw new Error( 'WebGPUBackend: Unable to create WebGPU adapter.' );

	}

	// feature support

	const features = Object.values( GPUFeatureName );

	const supportedFeatures = [];

	for ( const name of features ) {

		if ( adapter.features.has( name ) ) {

			supportedFeatures.push( name );

		}

	}

//---------------------add this to the device setup---------------------------
	const requiredLimits = {};

	for ( const key in adapter.limits ) {

		if ( key !== 'minSubgroupSize' && key !== 'maxSubgroupSize' ) {

			requiredLimits[ key ] = adapter.limits[ key ];

		}

	}
//----------------------------------------------------------------------------

	const deviceDescriptor = {
		requiredFeatures: supportedFeatures,
	//	requiredLimits: parameters.requiredLimits      //deactivate this line
		requiredLimits: requiredLimits    //    include this line
	};

	device = await adapter.requestDevice( deviceDescriptor );

	console.log(device);   // just for test to see the new limits
```

I don't need it, but would it perhaps even be something that could be offered as an option?
Something like ```enableMaximumAdapterLimits = true``` 
what do the others think?

**Comment by AndrewChan2022** [comment]
@Spiri0 Thanks a lot.

The framework also give opportunity to pass limit inside. This is my code.

```js
const paras = {
    canvas: this.canvas,
    antialias: true,
    requiredLimits: {
        maxBufferSize: adapter.limits.maxBufferSize,
        maxStorageBufferBindingSize: adapter.limits.maxStorageBufferBindingSize,
    },
};
this.renderer = new THREERenderer(paras);
```
