### ISSUE TITLE
Exr conversion to ktx2 added to background Mac system render exception

### ISSUE THREAD

**Issue by wzq9** [mrdoob/three.js#29884]
### Description

The problem arises when I assign the material loaded with KTX2Loader to scene.background,
Some devices display successfully on macOS, while others experience anomalies
Here are the versions and devices and GPU
macOS Big Sur 11.7.10 Google Chrome 128.0.6612.138 intel hd graphics 5000 (success)
macOS Ventura 13.6.6 Google Chrome 130.0.6723.92 apple m1 (success)
macOS Monterey 12.6 .3 Google Chrome 130 .0 .6723 .92 apple m1 (failure)
macOS Sonoma 14.4 Google Chrome 130 .0 .6723 .92 Apple M2 (failure)
macOS Sequoia15.0.1 Google Chrome 129 .0 .6668 .59 Apple M2 (failure)

### Reproduction steps

append THREE.EquirectangularReflectionMapping 

### Code

```js
   ktx2Loader.load(
    "./sky.ktx2",
    (envMap) => {
      envMap.mapping = THREE.EquirectangularReflectionMapping
      scene.background = envMap
    },
  )
```

### Live example

https://jsfiddle.net/8hosbtcx/

### Screenshots

I hope to get
![image](https://github.com/user-attachments/assets/ff114240-f9bc-4939-980a-7c6937f0e715)
But in some macos appeared
<img width="1465" alt="975BF3BA-2588-4C5D-ABEA-8147E25DCF55" src="https://github.com/user-attachments/assets/07bdbdfe-9de8-4a5b-b6a6-5d0293b5cca5">

### Version

three.js 170

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
When using the KTX2 texture as a diffuse map for a material, the texture works as expected: https://jsfiddle.net/v7th9bjs/

It seems the issue is related to `Scene.background`(btw, I can reproduce on my mac Mini with Chrome, Firefox and Safari).

**Comment by donmccurdy** [comment]
One extra bit of information (from the [forum post](https://discourse.threejs.org/t/exr-conversion-to-ktx2-mac-system-rendering-exception/73950/8)) is that it may be related to `scene.backgroundBlurriness`.

While KTX2 files can contain mipmaps, this one does not:

```
$ ktx info sky.ktx2

...

Level Index

Level0.byteOffset: 0xb8
Level0.byteLength: 3094993
Level0.uncompressedByteLength: 8388608
```

**Comment by Mugen87** [comment]
>  the issue may be related to scene.backgroundBlurriness.

`backgroundBlurriness` isn't configured in the fiddle so it is effectively ignored. With a value greater than zero, a PMREM is generated which is why the sampling probably works again.

**Comment by Mugen87** [comment]
Probably something is going wrong in `WebGLCubeRenderTarget.fromEquirectangularTexture()`.

**Comment by Mugen87** [comment]
@donmccurdy Do you know why `KTX2Loader` returns the texture with `minFilter` set to `THREE.LinearMipmapLinearFilter` although no mips are defined? Using `THREE.LinearFilter` fixes the issue: https://jsfiddle.net/2q4eac3n/

**Comment by GitHubDragonFly** [comment]
@Mugen87 the fiddle from your previous post was working fine with MeshStandardMaterial, why would that be?

It is an interesting thing to find out that setting `backgroundBlurriness` kind of works as a workaround to force environment reveal itself. I might just keep this in my viewers to try to avoid some other unknown issues that might still be present.

**Comment by GitHubDragonFly** [comment]
Just to mention couple more things:
- I have seen this happening with WebGPU as well, probably caused in the same library code area
- Currently, when setting a KTX2 texture as a scene background it is Y-flipped (all example KTX2 textures from three.js repository)
  - The sky texture from this issue appears to be already encoded as flipped so it sets properly

**Comment by donmccurdy** [comment]
PR:

- https://github.com/mrdoob/three.js/pull/29904

> Currently, when setting a KTX2 texture as a scene background it is Y-flipped...

Note that [`CompressedTexture#flipY`](https://threejs.org/docs/?q=compressed#api/en/textures/CompressedTexture.flipY) has no effect on compressed textures, and defaults to 'false'. For uncompressed textures the default is 'true', so both require different UV conventions. Typically the way to work around this (if using UVs that expect `.flipY=true`) would be to flip the texture prior to compression. With the `basisu` utility, you can use the `-y_flip` flag.

**Comment by GitHubDragonFly** [comment]
@donmccurdy another option that also seems to work is to decompress the texture, convert it to PNG and then change the flipY on it.

This could work for those who are just plain happy to see the picture being set.

**Comment by wzq9** [comment]
On this topic, I found something new: load crashes on ipad and ios, and performance on Android phones just like the macOS mentioned above
(The crash should be a connection reaction caused by me loading other resources)

I updated the latest three versions, and the effect is the same, and I've added envMap.minFilter = LinearFilter; Or scene. BackgroundBlurriness = 0.1
