### ISSUE TITLE
Video Texture makes WebGL context lost on Ubuntu

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#29909]
### Description

Video texture example is black screen because of WebGL context lost on Ubuntu 22.04.

Initial analysis: When video is not ready( not first frame come), rendering is inited wrongly that makes WebGL crashes.

Issue is fixed on example if checking this before rendering.

``
if(video.currentTime > 0)
	composer.render();
``

### Reproduction steps

1. Open https://threejs.org/examples/?q=video#webgl_materials_video
2. Click Play
3. Nothing is show up. WebGL context lost on console log.

### Code

https://threejs.org/examples/?q=video#webgl_materials_video

### Live example

https://threejs.org/examples/?q=video#webgl_materials_video

### Screenshots

![image](https://github.com/user-attachments/assets/35755ae2-3cf4-4317-83b2-cf8e7adc7755)

### Version

r170

### Device

Desktop

### Browser

Chrome

### OS

Linux

**Comment by whatisor** [comment]
I think it is related hardware, but panorama running well without issue.
![image](https://github.com/user-attachments/assets/aa73accf-1fe6-4e0a-858d-3e7cbaf631c7)

**Comment by Mugen87** [comment]
Can you try to remove all post processing of `webgl_materials_video` and check if it works on your machine? Maybe the example is too demanding.

When you are getting asked to share a `chrome://gpu/` report, the idea is not to make a screenshot but click the button "Download Report to File" and then share the resulting text file.

**Comment by whatisor** [comment]
Some more information:
+ it works if remove post-processing.
+ console always log wegl context lost then webgl context restore.
+ should be device issue but video-only demo can restore from error after context restore

**Comment by Mugen87** [comment]
Do you see the same issues in Firefox?

**Comment by Mugen87** [comment]
Please report this issue to the Browser vendor.
