### ISSUE TITLE
React Native New Architecture (0.76.2) is throwing an error in the React Native view: TypeError: WeakMap key must be an Object (three.cjs)

### ISSUE THREAD

**Issue by semsion** [mrdoob/three.js#29903]
### Description

React Native New Architecture (0.76.2) is throwing this error in the React Native view: TypeError: WeakMap key must be an Object.

This is after running `npx expo run:android`

### Reproduction steps

1. npx create-expo-app --template
2. npx expo install expo-gl
3. npm install three @react-three/fiber
4. npm install @react-three/drei
5. npm install @react-three/postprocessing postprocessing
6. npx expo prebuild
7. npx expo run:android

The React Native view error call stack appears to point towards the commented arrows in the code below, inside of node_modules/three/build/three.cjs.

### Code

```js
	function drawBuffers( renderTarget, framebuffer ) {

		let drawBuffers = defaultDrawbuffers;

		let needsUpdate = false;

		if ( renderTarget ) {

			drawBuffers = currentDrawbuffers.get( framebuffer );

			if ( drawBuffers === undefined ) {

				drawBuffers = [];
				currentDrawbuffers.set( framebuffer, drawBuffers ); // <<<<<<<<<<<<<

			}
			// ...
    }

```

### Version

0.170.0

### Device

Mobile

### Browser

Chrome

### OS

Android

**Comment by Mugen87** [comment]
This error message might occur because there is a WebGL context lost on your system. 

It's best if you try to reproduce the issue with a editable live example (https://jsfiddle.net/3mrkqyea/). Otherwise I recommend you redirect this issue to the developer of your runtime environment.

**Comment by semsion** [comment]
Is this something you guys can help with or shall we direct it towards the React Three Fiber guys?

**Comment by mrdoob** [comment]
Better to ask the R3F people, or probably better the React Expo people.
