### ISSUE TITLE
Add support for custom boxes in BoxHelper

### ISSUE THREAD

**Issue by TheBlek** [mrdoob/three.js#29923]
### Description

I recently needed to create a bounding box from an object, expand it a little and do some stuff with it. So I wanted to view this box in debug mode but BoxHelper only supports boxes from an object. But I didn't want to do the debug display myself.

### Solution

Add setFromBox method which sets current box to display for BoxHelper, disabling current object. Something like this maybe:
```
  setFromBox(box) {
    this.object = undefined;
    _box.copy(box);
    this.update();

    return this;
  }
```

### Alternatives

To fix my problem I just copy-pasted BoxHelper into the project and added lines above to it.

**Comment by TheBlek** [comment]
I could do a PR on this over a weekend if this interface change is considered ok

**Comment by Mugen87** [comment]
You can display any instance of `Box3` via https://threejs.org/docs/index.html#api/en/helpers/Box3Helper.
