### ISSUE TITLE
WebGPURenderer: Exception when changing video source.

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#29925]
### Description

In WebGPU rendering with videotexture, it uses external_texture.
When we change video source, it seems the old one is released, so render is crash.

### Reproduction steps

1. Create VideoTexture
2. Start rendering
3. Change video source.

### Code

```
`

// Simple three.js example
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
let mesh, renderer, scene, camera, controls;
const dummy = new THREE.Object3D();
init();
animate();
function init() {
    // renderer
    renderer = new THREE.WebGPURenderer({ antialias: true });
    renderer.setSize( window.innerWidth, window.innerHeight );
    renderer.setPixelRatio( window.devicePixelRatio );
    document.body.appendChild( renderer.domElement );
    // scene
    scene = new THREE.Scene();
    // camera
    camera = new THREE.PerspectiveCamera( 40, window.innerWidth / window.innerHeight, 1, 10000 );
    camera.position.set( 0, 0, 30 );
    // controls
    controls = new OrbitControls( camera, renderer.domElement ); 
    // geometry
    const geometry = new THREE.PlaneGeometry(50,30 );
    // material
    const material = new THREE.MeshBasicNodeMaterial({
    map: new THREE.VideoTexture(document.getElementById("video"))} );
    material.map.colorSpace = THREE.SRGBColorSpace;
    document.getElementById("video").play();
    // mesh
    mesh = new THREE.Mesh( geometry, material );
    scene.add(mesh)
	//document.getElementById("video")
  const newVideo = "https://threejs.org/examples/textures/pano.mp4"
	renderer.domElement.addEventListener("mousedown",()=>{
  	document.getElementById("video").src = newVideo;
     document.getElementById("video").play();
  })
}
function animate() {
    requestAnimationFrame( animate );
    //controls.update();
    renderer.render( scene, camera );
}

`
```

### Live example

[https://jsfiddle.net/1tpkc76u/1/](https://jsfiddle.net/1tpkc76u/1/)

### Screenshots

![image](https://github.com/user-attachments/assets/61e55531-d49a-47b2-9c4e-23e83a15b8ff)

### Version

0.170.0

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
We do not support this use case anymore. If you want to exchange the video, please create a new instance of `VideoTexture` instead and call `dispose()` on the new one. This is also noted in the documentation:

https://threejs.org/docs/index.html#api/en/textures/VideoTexture

**Comment by Mugen87** [comment]
It seems the video texture exchange does not work correctly with `WebGPURenderer` : 

`WebGLRenderer`: https://jsfiddle.net/rL5nj8ke/
`WebGPURenderer`: https://jsfiddle.net/wa3jop0b/

**Comment by whatisor** [comment]
Maybe #29909 will be fixed after this is fixed.

**Comment by whatisor** [comment]
My bad, that issue is webgl,  I will try it soon.

**Comment by whatisor** [comment]
@Mugen87  Seem it does not fix on my project. Do you have some live project it works? Otherwise I will try some new test code on our examples folder.

**Comment by Mugen87** [comment]
The code from the fiddles in https://github.com/mrdoob/three.js/issues/29925#issuecomment-2488191422 worked with the patched version for me.

**Comment by whatisor** [comment]
You are correct, I've noticed you changed to call dispose and create new texture.
