### ISSUE TITLE
KTX2Loader:  Return DataTexture for uncompressed formats

### ISSUE THREAD

**Issue by ligaofeng0901** [mrdoob/three.js#29922]
### Description

So far, KTX2Loader doesn't work with WebGPURenderer. If we forcely use it in WebGPURenderer. some errors occur. 
```
WebGPUTextureUtils.js:642 Uncaught TypeError: Cannot read properties of undefined (reading 'width')
    at WebGPUTextureUtils._copyCompressedBufferToTexture (WebGPUTextureUtils.js:642:1)
    at WebGPUTextureUtils.updateTexture (WebGPUTextureUtils.js:370:1)
    at WebGPUBackend.updateTexture (WebGPUBackend.js:1146:1)
    at Textures.updateTexture (Textures.js:243:1)
    at Bindings._init (Bindings.js:99:1)
    at Bindings.getForRender (Bindings.js:33:1)
    at Bindings.updateForRender (Bindings.js:79:1)
    at WebGPURenderer._renderObjectDirect (Renderer.js:1714:1)
    at WebGPURenderer.renderObject (Renderer.js:1658:1)
    at WebGPURenderer._renderObjects (Renderer.js:1597:1)
```

### Solution

Maybe there is another way to load ktx2?

### Alternatives

-

**Comment by Mugen87** [comment]
`KTX2Loader` does in general work with `WebGPURenderer` (see https://threejs.org/examples/webgpu_loader_gltf_compressed) but it seems you are trying to load a KTX2 texture that holds uncompressed RGBA data.

The issue behind this is explained in https://github.com/mrdoob/three.js/pull/29904#issuecomment-2480526384.

My preferred solution is to return instances of `DataTexture` in this case. `CompressedTexture` should only hold compressed data.

**Comment by ligaofeng0901** [comment]
> `KTX2Loader` does in general work with `WebGPURenderer` (see https://threejs.org/examples/webgpu_loader_gltf_compressed) but it seems you are trying to load a KTX2 texture that holds uncompressed RGBA data.
> 
> The root cause of the runtime error is explained in [#29904 (comment)](https://github.com/mrdoob/three.js/pull/29904#issuecomment-2480526384).
> 
> My preferred solution is that loaders return instances of `DataTexture` in this case. `CompressedTexture` should only hold compressed data.

Thanks! I will dive deeper into it and try to find it out.

**Comment by donmccurdy** [comment]
@Mugen87 I plan to fix the case you're describing, see #29926. 

However, are you sure that's what's happening here, and can we reproduce that? I'm not sure what device that supports WebGPU would not also support _at least one_ of the possible transcode targets for Basis Universal, such that it would fall back to the final option, RGBAFormat.

If the data in the KTX2 was uncompressed to begin with (not Basis Universal) then it should already be creating a DataTexture here:

https://github.com/mrdoob/three.js/blob/de9b967720cbb55d787a726248d4f38e87bd6154/examples/jsm/loaders/KTX2Loader.js#L979-L994

But maybe I've missed something, I'm not sure how to reproduce this.

**Comment by Mugen87** [comment]
Without a correct usage of `detectSupport()`, things can be indeed misleading since the loader does not work as expected to begin with. If you are not encountering any issues anymore when using the method correctly, I vote to close the issue for now.

**Comment by ligaofeng0901** [comment]
Thing goes good now,  close the issue.

**Comment by ligaofeng0901** [comment]
Also, It may be better If we add a warning here If `rendered` is not inited. 
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/KTX2Loader.js#L144
This can help users who migrating from WebGL version, like `render` method in `WebGPURenderer`.

**Comment by ligaofeng0901** [comment]
> The `_initialized` property is private.

It really is, I think it should be an open API. One case we met is, we invoke `dispose` of `WebGPURenderer` before it is inited, it casues some errors.

**Comment by Mugen87** [comment]
@sunag How about adding a `hasInitialized()` method to `Renderer` (since we already have `hasFeature()`). 

It would allow apps to check the state of the renderer without accessing the private `_initialized` which is for internal use only. When we switch to real private properties at some point, to `#initialized` won't be accessible anymore.

**Comment by sunag** [comment]
> @sunag How about adding a hasInitialized() method to Renderer (since we already have hasFeature()).

Yes, it can be useful.👍
