### ISSUE TITLE
Problem with manual update matrix

### ISSUE THREAD

**Issue by bobWinner** [mrdoob/three.js#29949]
### Description

Once an object is attributed with matrixAutoUpdate = false and matrixWorldAutoUpdate = false, it is frozen.
whenver i call updateMatrix() or updateMatrixWorld() or updateMatrixWorld(true).

see : https://discourse.threejs.org/t/preventing-matrix-updates-for-static-objects/74262

### Reproduction steps

1. create a basic scene with basic object.
2. set .matrixAutoUpdate = false and matrixWorldAutoUpdate = false to the object.
3. on loop modify the transforms then updateMatrix() and updateMatrixWorld(true) to the object.

the object is frozen.

### Code

```
// Variables :
let parent;
let child;
let parent_timer = 0;
let child_timer = 0;

// Initialization
const geometry = new THREE.BoxGeometry( 1, 1, 1 ); 

const material = new THREE.MeshBasicMaterial( {color: 0xff0000} ); 
parent = new THREE.Mesh( geometry, material ); 

const material2 = new THREE.MeshBasicMaterial( {color: 0x00ff00} ); 
child = new THREE.Mesh( geometry, material2 ); 

parent.position.set(0, 2, 0)
child.position.set(0, 2, 0)

parent.add( child );
scene.add( parent );

parent.updateMatrix();
child.updateMatrix();

parent.updateMatrixWorld();
child.updateMatrixWorld();

parent.matrixAutoUpdate = false;
child.matrixAutoUpdate = false;

parent.matrixWorldAutoUpdate = false;
child.matrixWorldAutoUpdate = false;

// On loop
parent_timer += 0.1;
parent.position.setX(Math.cos(parent_timer)*2)

child_timer += 0.1;
child.position.setZ(Math.cos(parent_timer)*2)

parent.updateMatrixWorld(true);
parent.updateMatrix();
parent.matrixWorldNeedsUpdate = true;

child.updateMatrixWorld(true);
child.updateMatrix();
child.matrixWorldNeedsUpdate = true;
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Version

170

### Device

Desktop

### Browser

Chrome

### OS

Linux

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/28533#issuecomment-2205892206.

The code works actually as intended. I suggest you ignore `matrixWorldAutoUpdate` and let the engine compute the world matrices. When you are worried about performance, you can already save some overhead if you set `matrixAutoUpdate` to `false` and update local matrices on demand.

https://jsfiddle.net/evtus0pg/
