### ISSUE TITLE
Update instanced buffer attributes array breaks in webGPU 

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#29966]
### Description

1 ) Create an instancedgeometry 

2 ) fill it with instancedattributes 

3 ) update with new values later

This works in WebGL, but not in WebGPU 

This is exactly the break : 

OperationError: Failed to execute 'writeBuffer' on 'GPUQueue': Number of bytes to write is too large

<img width="1006" alt="Screenshot 2024-11-25 at 17 22 21" src="https://github.com/user-attachments/assets/699d46e2-9414-407f-b604-068ad7f1a7ab">

My guess is, once the buffer is created, it cannot be replaced ? 

### Live example

[Live fiddle ](https://jsfiddle.net/23dma5qf/2/)

Uncomment the line 81

### Version

last 

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by RenaudRohlinger** [comment]
Fixed with https://github.com/mrdoob/three.js/pull/29967.

Thanks!
