### ISSUE TITLE
Raycast on a WebGPU Line2  / Line2NodeMaterial breaks 

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#29986]
### Description

Raycasting a Line2 imported from WebGPU + Line2NodeMaterialbreaks

Because Line2NodeMaterial.resolution does not exists

### Live example

[Live Fiddle Link](https://jsfiddle.net/s392ye1b/38/)

### Screenshots

<img width="603" alt="Screenshot 2024-11-28 at 13 43 15" src="https://github.com/user-attachments/assets/dd2e7b62-ad04-4499-beda-6b80d65ce6d9">

### Version

last

### Device

Desktop

### Browser

Chrome

### OS

Windows, MacOS

**Comment by Mugen87** [comment]
`Line2NodeMaterial` does not have a resolution uniform so we may need a different approach for `LineSegments2.raycast()`. Maybe the resolution can be a parameter of the raycasting method?

**Comment by gkjohnson** [comment]
The `resolution` is updated in the Mesh's [onBeforeRender function](https://github.com/mrdoob/three.js/blob/fcde431ddf191173491d3e604788ba75d3b43e18/examples/jsm/lines/LineSegments2.js#L361-L372) but there's no reason that field has to be stored on the material. It could just as easily be stored on the LineSegments2 class itself:

```js
onBeforeRender( renderer ) {

	renderer.getViewport( _viewport );
	this.resolution.set( _viewport.z, _viewport.w );

}
```

**Comment by Mugen87** [comment]
This looks good to me. Would like filing a PR?

**Comment by Samsy** [comment]
@Mugen87 here : 

[PR](https://github.com/mrdoob/three.js/pull/30016)
