### ISSUE TITLE
WebGPU NodeMaterial does not takes any params for contruction

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#29994]
### Description

We cannot pass any params to the NodeMaterial, but every other NodeMaterials do

Just wondering if it is something made by design, or something we miss  ?

https://github.com/mrdoob/three.js/blob/dev/src/materials/nodes/NodeMaterial.js#L43

**Comment by mrdoob** [comment]
Lets keep it like this 🙏

**Comment by mrdoob** [comment]
@sunag @Mugen87 What do you guys think about removing params support from all `*NodeMaterials`?

**Comment by Mugen87** [comment]
Sounds good to me!

**Comment by Samsy** [comment]
Hey there, 
I really dont want to bother you in any way and I am really sorry to jump on this again

The current system provides a consistent  ( except for the nodematerial ) interface across renderers and material and helps with abstraction

What would be the motivations for removing the params functions?

**Comment by Mugen87** [comment]
Avoiding redundancy. Classes like `BufferGeometry` don't accept parameters in the ctor as well.

**Comment by mrdoob** [comment]
Additionally, the parameters object approach is error prone and... ugly 🙃
