### ISSUE TITLE
r171 : Fn is not a function with vite.

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#29996]
### Description

`import {  Fn } from 'three/tsl'` not working in r171

`The requested module '/node_modules/.vite/deps/three_tsl.js?v=dde6d16d' does not provide an export named 'Fn' ` I saw similar problem last week when opening a bug in jsfiddle and using the dev branch. 

Should we change our imports? @mrdoob 

### Reproduction steps

1. try importing Fn 

### Code

X

### Live example

https://jsfiddle.net/Makio64/m5zLofx2/1/

### Version

r171

**Comment by Mugen87** [comment]
Your fiddle is not correct since the import map does not define `three/tsl`. When doing so, the import works as expected:

https://jsfiddle.net/a8xm3fph/5/

**Comment by Spiri0** [comment]
I don't know to what extent it makes sense to want to use Fn with three.module.js, because Fn is not part of three.module.js. I see Fn as part of three.webgpu.js with the ability to generate glsl code in fallback, but not as a tool intended for targeted shader generation in glsl with three.module.js. 
In WebGL, in my opinion, it will be best to create shaders the old way, with RawShaderMaterial. The WebGL examples I looked at were left as they were, without Fn.
@Mugen87 please correct me if I'm wrong.

**Comment by mrdoob** [comment]
`Fn` should be part of `three.tsl.js` now?

**Comment by Makio64** [comment]
> Your fiddle is not correct since the import map does not define `three/tsl`. When doing so, the import of `Fn` works as expected:
> 
> https://jsfiddle.net/a8xm3fph/5/
> 
> Maybe a Vite specific issue? The export in the npm package looks correct.
> 
> https://github.com/mrdoob/three.js/blob/17c59b2c3caa54a991f7b3b6319838da19cf5eb6/package.json#L19

Its the imports of the jsfiddle examples from the Bug Request.
I'm currently using in vite : `'three/tsl': 'three/webgpu'` as suggested by @RenaudRohlinger and it worked well until the r171, why this change ?

**Comment by sunag** [comment]
The alias for `'three/tsl': 'three/webgpu'` would no longer be necessary.

**Comment by Makio64** [comment]
that vite config work for `r171` me now :
```
	resolve: {
		alias: {
			// remap to new threejs version
			'three/addons': 'three/examples/jsm',
			'three/webgpu': path.resolve( __dirname, 'node_modules/three/build/three.webgpu.js' ),
			'three/tsl': path.resolve( __dirname, 'node_modules/three/build/three.tsl.js' ),
			'three': path.resolve( __dirname, 'node_modules/three/build/three.webgpu.js' ),
		},
	},
```

**Comment by marcofugaro** [comment]
@Makio64 your `three/addons`, `three/webgpu`, `three/tsl` aliases are no longer needed. If you're having issues with Typescript not recognizing the three.js custom import you can check out the solution here: https://github.com/three-types/three-ts-types/issues/1136#issuecomment-2258295707

This issue can be closed.

**Comment by Makio64** [comment]
@marcofugaro what do you mean ? In `r171` If i dont setup this in vite.config.js, it doesn't compile.. ( import not found )

**Comment by marcofugaro** [comment]
Yes, because of this issue: https://github.com/three-types/three-ts-types/issues/1136#issuecomment-2258295707

**Comment by Makio64** [comment]
@marcofugaro i'm not using typescript in my project and it worked perfectly on `r170`.
also my jsconfig: 

```js
{
	"compilerOptions": {
		"module": "esnext",
		"target": "esnext",
		"baseUrl": "./",
		"paths": {
			"@/*": [
				"./src/*"
			],
			"three/addons": [
				"./node_modules/three/examples/jsm"
			],
			"three/tsl": [
				"./node_modules/three/build/three.tsl.js"
			],
			"three": [
				"./node_modules/three/build/three.webgpu.js"
			],
		}
	},
	"include": [
		"src/**/*"
	]
}
```

**Comment by marcofugaro** [comment]
@Makio64 `0.171.0` with fine with Vite, typescript or not.
Here is a test: [vite-three-test.zip](https://github.com/user-attachments/files/18037870/vite-three-test.zip)

It's a problem with your configuration, you'd have to share a minimal reproducibe repo with the error.

**Comment by marcofugaro** [comment]
If you're not using Vite but just the native browser modules, here is a version with the correct importmaps: https://jsfiddle.net/3orfn6qd/1/

**Comment by Makio64** [comment]
Removed all and import from 'three/webgpu'  
Also this repo can help : https://github.com/brunosimon/three.js-tsl-template/blob/main/vite.config.js
