### ISSUE TITLE
Weird behaviour in a test

### ISSUE THREAD

**Issue by s-rigaud** [mrdoob/three.js#30014]
### Description

Running `npm run lint-test` will result with this line 

```
three.js/test/unit/src/math/Matrix3.tests.js
  454:18  warning  'Vector2' is not defined  no-undef
```

but running `npm run test-unit` results in no test failing.

When adding the missing import with `import { Vector2 } from '../../../../src/math/Vector2.js'`,   and re-running `npm run test-unit` the test using Vector2 is failing while both assertions are True:

```
not ok 1925 Maths > Matrix3 > makeTranslation
1..2758
# pass 1283
# skip 0
# todo 1474
# fail 1
```
I'm not familiar to QUnit and could not pinpoint the bug :/ 

### Reproduction steps

1.
2.
3.

### Code

run `npm run lint-test`

### Live example

--

### Version

r172dev

**Comment by Mugen87** [comment]
Fixed via https://github.com/mrdoob/three.js/commit/480c4140232d9d16e191f8666f583ec73e666f2e.
