### ISSUE TITLE
WebGPURenderer initially reports WebGPUBackend before falling back to WebGLBackend

### ISSUE THREAD

**Issue by verekia** [mrdoob/three.js#30024]
### Description

When instantiated, `new WebGPURenderer().backend` is `WebGPUBackend`, even when WebGPU is not available. 

This makes it difficult to know which backend is actually used.

### Reproduction steps

1. Open Firefox
2. Log `console.log(new WebGPURenderer().backend)`

### Code

```js
// Running in a browser that doesn't support WebGPU, such as Firefox

const renderer = new WebGPURenderer()
console.log(renderer.backend) // WebGPUBackend <= Should be WebGLBackend immediately

setTimeout(() => {
  console.log(renderer.backend) // WebGLBackend
}, 1000)
```

### Live example

https://jsfiddle.net/Lsruty60/

### Version

171

### Browser

Firefox, Safari

**Comment by Mugen87** [comment]
We can't support this pattern because of the async nature of WebGPU. Do it like so:
```js
renderer = new THREE.WebGPURenderer();
await renderer.init();
console.log(renderer.backend);
```
Fiddle: https://jsfiddle.net/zohvgrkL/

**Comment by verekia** [comment]
Thank you! Would it be practical or make sense to keep `backend` as `undefined` until one is effectively loaded instead? I think it is confusing for people to see the WebGPUBackend there in browsers that don't support WebGPU. They will test `renderer.backend.isWebGPUBackend` and think it works miraculously in Firefox/Safari or that there is a bug in Three.

**Comment by Mugen87** [comment]
Actually the idea is to use `WebGPU.isAvailable()` for testing the support of WebGPU. `WebGPU` is an addon and can be imported from `three/addons/capabilities/WebGPU.js`. Right now, the module relies on top-level await so it might be refactored to work fully async in the future.

I would only consider a refactoring of the renderer if more developers stumble across this issue.
