### ISSUE TITLE
Can not call xxxnode.assign directly

### ISSUE THREAD

**Issue by code-soldier** [mrdoob/three.js#30021]
### Description

Call node.assign directly, it will throw error 'TypeError: Cannot read properties of null (reading 'assign')'. 
This is my actual requirement：
![image](https://github.com/user-attachments/assets/4d2b6aee-89c1-45f0-9447-f3e4185953ee)

### Reproduction steps

1.use addAssgign

### Code

```js
import { float } from 'three/tsl'

const a = float(1).addAssign(2)
```

### Live example

https://jsfiddle.net/ganqian/Lga1f5h6/1/

### Version

r171

**Comment by sunag** [comment]
Currently it is necessary to use `toVar()` to be able to make assignments.

```js

const a = float(1).toVar();
a.addAssign( 2 );
```

Otherwise you can use by directly replacing:

```js
let a = float( 1 );
a = a.add( 2 );
```
