### ISSUE TITLE
PropertyBinding on `.material.color` doesn't set `needsUpdate`

### ISSUE THREAD

**Issue by tommie** [mrdoob/three.js#30035]
### Description

It seems PropertyBinding isn't selecting the right `setValue`, because `Material.needsUpdate` only has a setter defined, not a getter, and the check is against `undefined`.

The solution is probably to use `"material" in targetObject`, since a getter isn't easily defined without knowing the compiled version:

https://github.com/mrdoob/three.js/blob/3df50b769f0a8a9874dbc3b9d1176a9156a82fac/src/animation/PropertyBinding.js#L572-L580

### Reproduction steps

See console of live example.

### Code

```js
import * as THREE from 'three';

const material = new THREE.MeshBasicMaterial();
const mesh = new THREE.Mesh(undefined, material);
const binding = THREE.PropertyBinding.create(mesh, ".material.color");

binding.bind();
binding.setValue([0.5, 0.5, 0.5], 0);

console.log(material.version);
```

### Live example

https://jsfiddle.net/pq1vLgjc/

### Version

r169

**Comment by Mugen87** [comment]
```js
if ( targetObject.needsUpdate !== undefined ) { // material 
```
When this line is only relevant to determine the updating versioning scheme, we could simply do this:
```
```js
if ( targetObject.isMaterial === true ) { // material 
```

@tommie What do you think?

**Comment by Mugen87** [comment]
In general, it seems more clean to check the object types and not the existence of flags. So the entire code block could be written like so:
```js
if ( targetObject.isMaterial === true ) { // material

	versioning = this.Versioning.NeedsUpdate;

} else if ( targetObject.isObject3D === true ) { // node transform

	versioning = this.Versioning.MatrixWorldNeedsUpdate;

}
```

**Comment by tommie** [comment]
> if ( targetObject.isMaterial === true ) { // material 

I don't understand why the comparison to true is required, but yes, that seems good.

The "node transform" comment seems odd, and only `Object3D` has a `matrixWorldNeedsUpdate`: https://github.com/search?q=repo%3Amrdoob%2Fthree.js%20matrixworldneedsupdate&type=code
