### ISSUE TITLE
PMREM generation produce wrong results

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#30048]
### Description

PMREM Generation orientation of cameras bake are probably wrong in both webGL and WebGPU version, or is it the PMREM read node that is wrong ? 

<img width="392" alt="Screenshot 2024-12-06 at 16 02 54" src="https://github.com/user-attachments/assets/230ed94a-95e7-4f4f-a4db-93ee3d67379f">

### Live example

[Live Fiddle](https://jsfiddle.net/5L6x4mdz/40/)

### Version

171

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Spiri0** [comment]
Ah, this story. @mugen87 do you remember when I looked at that? The coordinates in the PMREM module are not correct #28334
