### ISSUE TITLE
Uniform texture not working

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#30050]
### Description

Currently if i want to do a shader with an uniform texture and change the value of the uniform, i cant.

**Case1 A :** 
Using an uniform texture in the texture node trigger an error, but it should be accepted
```js
let map = uniform( img1 )
texture( map, uv() ) // Error : TextureNode: Need a three.js texture
```

**Case1 B :** 
Using an uniform float inside a node work with no problem, for example : 
```js
let percent = uniform( 0.5 )
let opacity = mix( vec3(1), vec3(0), percent ) // work as expected, similar synthax with case1 A
```

Case2 :
If using the value of the uniform ( it's not a node ) then it will not update : 
```js
let map = uniform( img1 )
texture( map.value, uv() ) // no error but then it will not be dynamic, its similar as i pass img1 directly.
setTimeout( ()=> { map.value = img2 } , 2000) // Bug : the uniform is not updated in the shader cause uniform.value is not a node but a Texture
```

### Reproduction steps

[X](https://jsfiddle.net/Makio64/yk5u1h7f/)

### Code

[X](https://jsfiddle.net/Makio64/yk5u1h7f/)

### Live example

https://jsfiddle.net/Makio64/yk5u1h7f/

### Screenshots

@sunag This is a reopening of issue [29974](https://github.com/mrdoob/three.js/issues/29974#issuecomment-2507590792) as I do think it's a bug or a limitation.

### Version

r171

**Comment by sunag** [comment]
I understand your perspective, but I’d like to clarify that this isn’t a bug or limitation—it’s a design choice.  I gave some examples earlier and apparently you completely ignored them.

TSL is designed to facilitate chaining and shorten code, I think it is unanimous that `texture( map, uv() )` is simpler than `texture( uniform( map ), uv() )` and it easier to reuse UVs for TSL functions when UV is a built-in parameter, for example: `texture(map, proceduralUV ).blur().sobel()`.

None of the dynamic texture swapping issues mentioned here are real; the examples wouldn't even work if that were the case, you're just forcing an input that isn't. `uniform`, `uniformArray`, `texture`, `cubeTexture` and `buffer` are all uniforms, but their inputs are different.

Case 1:
```js
// wrong
let map = uniform( img1 )
texture( map, uv() ) // Error : TextureNode: Need a three.js texture

// right
let map = texture( img1 );
map.uv( uv() );
```

Case 2:
```js
// wrong
let map = uniform( img1 )
texture( map.value, uv() ) // no error but then it will not be dynamic, its similar as i pass img1 directly.
setTimeout( ()=> { map.value = img2 } , 2000) // Bug : the uniform is not updated in the shader cause uniform.value is not a node but a Texture

// right
let map = texture( img1 )
map.uv( uv() );
setTimeout( ()=> { map.value = img2 } , 2000) 
```

Case previous:
```js
// wrong
texture( uniform( img1 ), uv() )

// right
texture( img1, uv() )
```

**Comment by Makio64** [comment]
@sunag thanks for your answer, i didnt ignore them, but i have the feeling we re not speaking of the same problem. 
Probably I’m not clear about it so I’ll try to rephrase it.

Here my concrete problem : 
let say i want an uniform for my brush texture and i want to switch this texture many times:

In glsl i will do : uniformBrushMap.value = textureBrush2 

In tsl : I didn’t find the solution as I can’t use uniform in textureNode, also I don’t want to pass the texture directly else I can’t change it.

Maybe I’m totally missing a basic concept, thanks for your patience and all the work! 🙏

**Comment by sunag** [comment]
> should we add a warning message to uniform( Texture ) to say to use sample ?

Yeah, let's do that.
