### ISSUE TITLE
MeshDepthMaterial "fog" property wrong in the documentation?

### ISSUE THREAD

**Issue by ForGoodTech** [mrdoob/three.js#30057]
### Description

In the source code [src/materials/MeshDepthMaterial.js](https://github.com/mrdoob/three.js/blob/dev/src/materials/MeshDepthMaterial.js), there is no "fog" but it shows up in the API documentation https://threejs.org/docs/#api/en/materials/MeshDepthMaterial

How come? I thought the API was generated automatically? If the generator is wrong, that would be more serious.

### Reproduction steps

1. Read https://threejs.org/docs/#api/en/materials/MeshDepthMaterial

### Code

```js
// code goes here
```

### Live example

[* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/mnqr9oj0/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/xno7bmw0/)
](https://github.com/mrdoob/three.js/blob/dev/src/materials/MeshDepthMaterial.js)

### Version

r171

**Comment by Mugen87** [comment]
> How come? I thought the API was generated automatically? If the generator is wrong, that would be more serious.

The current documentation is not automatically built. However, we have recently started to add JSDoc so at some point in the future we can rely on a build.

It seems the issue is a left-over from #23939. The `fog` property should be removed from the docs.
