### ISSUE TITLE
Crashing after adding more than 12 lights to scene

### ISSUE THREAD

**Issue by astruegenius** [mrdoob/three.js#30056]
### Description

Renderer : WebGL
In my project when I add more than 10 point lights I get a console error and everything not only becomes slow, but crashes whole page. This issue started happening when I added post processing.

```
THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Material Name: 
Material Type: MeshStandardMaterial

Program Info Log: FRAGMENT shader texture image units count exceeds MAX_TEXTURE_IMAGE_UNITS(16)
```

### Reproduction steps

1. Import effect composer, render pass, (any pass, my case ssaopass) and render pass
2. add 12 or more point lights
3. check console

### Code

```js
```

### Live example

no live example

### Version

r171

### Device

_Computer_

### Browser

_Edge_

### OS

_Windows_

**Comment by Mugen87** [comment]
I'm unable to reproduce the issue. The following live example adds 20 point lights to the scene and uses post processing.

https://jsfiddle.net/nz07d14x/

Do you mind updating the fiddle so the mentioned runtime issues occur?

**Comment by yuvashrikarunakaran** [comment]
Reduce the Number of Active Point Lights
Consolidate your lighting setup using fewer, but more strategically placed lights.
Use AmbientLight or a single DirectionalLight to simulate global illumination.
javascript

const ambientLight = new THREE.AmbientLight(0xffffff, 0.5);
scene.add(ambientLight);

const directionalLight = new THREE.DirectionalLight(0xffffff, 1);
directionalLight.position.set(5, 10, 5);
scene.add(directionalLight);
2. Use Light Baking
Bake lighting into textures using tools like Blender or Unity. This eliminates the need for multiple dynamic lights.
Apply baked textures to your 3D models in Three.js.
3. Use Deferred Rendering (Alternative Frameworks)
Three.js uses forward rendering, where all lights are processed for every visible object. Deferred rendering calculates lighting in a separate pass and can handle many lights efficiently. However, this requires using extensions or different frameworks like Babylon.js or Filament.

4. Optimize Shadows
If shadows are the main requirement, reduce the number of lights casting shadows:

javascript

pointLight.castShadow = false; // Disable shadows for some lights
Alternatively, combine multiple lights into a single shadow map.

5. Optimize Post-Processing
Minimize the use of post-processing passes, as each one introduces overhead:

javascript

composer.addPass(renderPass);
// Remove SSAOPass or other expensive passes if not critical
Test which passes are essential and remove unnecessary ones.

6. WebGL2 or Custom Shader Solutions
If your GPU and environment support WebGL2, use texture arrays to consolidate data for multiple lights. This requires custom shader programming and isn't directly supported in Three.js out of the box.

7. Fallback for Lower-End Devices
Use GPU capability checks to adjust lighting dynamically:

javascript

const gl = renderer.getContext();
const maxTextureUnits = gl.getParameter(gl.MAX_TEXTURE_IMAGE_UNITS);
console.log(`Max texture units: ${maxTextureUnits}`);

if (maxTextureUnits < 16) {
    // Reduce lights or use simpler materials
}
