### ISSUE TITLE
WebGPURenderer:  WebGL2 backend: moving directional light causes shadow flickering

### ISSUE THREAD

**Issue by srfall** [mrdoob/three.js#30066]
### Description

I am using a DirectionalLight and update its position when the camera has moved. This works fine with the WebGlRenderer, but I try the same thing with the WebGPURenderer (in Firefox), every time the light is moved, the shadows glitch. I would expect the same behavior in the WebGL2 fallback as when directly using the WebGlRenderer.

### Reproduction steps

1. Copy / open the two shadowmap examples for [WebGl](https://github.com/mrdoob/three.js/blob/master/examples/webgl_shadowmap_vsm.html) and [WebGPU](https://github.com/mrdoob/three.js/blob/master/examples/webgpu_shadowmap.html) 
2. Insert e.g:
````js
scene.add(dirLight.target);
const cameraLightOffset = new THREE.Vector3().copy(camera.position).sub(dirLight.position);
controls.addEventListener('change', () => {
    dirLight.position.copy(camera.position).sub(cameraLightOffset);
    dirLight.target.position.copy(controls.target);
});
````
or any other code that updates the dirLight position when the camera position changes.

3. Notice that the shadows look fine in the webGL version, but in the  WebGPU->WebGL2 fallback version, they glitch

### Code

```js
// see live example
```

### Live example

* [jsfiddle-latest-release WebGLRenderer: looks ok](https://jsfiddle.net/40emwz2t/)

* [jsfiddle-latest-release WebGPURenderer: glitch when moving](https://jsfiddle.net/p43q9hs5/)

### Version

r171

### Device

Desktop

### Browser

Firefox

### OS

Windows

**Comment by yuvashrikarunakaran** [comment]
Here's the basic reproduction setup

// Scene setup
const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
const renderer = new THREE.WebGPURenderer(); // or new THREE.WebGLRenderer() for comparison
document.body.appendChild(renderer.domElement);

// Directional light
const dirLight = new THREE.DirectionalLight(0xffffff, 1);
scene.add(dirLight);
scene.add(dirLight.target);

// Adjust light position relative to the camera
const cameraLightOffset = new THREE.Vector3().copy(camera.position).sub(dirLight.position);

// Update light position and target dynamically
controls.addEventListener('change', () => {
    dirLight.position.copy(camera.position).sub(cameraLightOffset);
    dirLight.target.position.copy(controls.target);
});

// Render loop
function animate() {
    requestAnimationFrame(animate);
    controls.update();
    renderer.render(scene, camera);
}
animate();

**Comment by sunag** [comment]
I was fixed in `dev` branch https://github.com/mrdoob/three.js/pull/30064
