### ISSUE TITLE
THREE.WebGPURenderer: WebGPU Device Lost - displaying on all three examples and own project

### ISSUE THREAD

**Issue by Russo-creation** [mrdoob/three.js#30099]
### Description

When I'm opening in one of my laptops three.js examples with WebGPU (happens same with my own project) on Chrome ore Edge scene is not showing up and in the console I received an error `THREE.WebGPURenderer: WebGPU Device Lost`

On Firefox examples are running correctly - I think that in such cases WebGL should trigger during creating instance (or is this more like GPU drivers issues which are harder to detect)?

In my own project when I switched to `forceWebGL=true` then three it's working on chrome and edge 

### Reproduction steps

1. Open any WebGPU three.js example on Chrome or Edge

### Screenshots

![wbgpu lost device](https://github.com/user-attachments/assets/4ae52359-6c72-4023-8eec-e5f3ffa362fa)
![070c4072-8505-479f-a722-e66fc4b54e4a](https://github.com/user-attachments/assets/228741b3-4d7e-409f-ac11-10d07aaef960)

### Version

r0.171.0

### Device

Desktop

### Browser

Chrome, Edge

### OS

Windows

**Comment by mrdoob** [comment]
Do these examples work?
https://webgpu.github.io/webgpu-samples/

**Comment by Russo-creation** [comment]
@mrdoob  No it, doesn't
![image](https://github.com/user-attachments/assets/84cbd92a-ba10-424e-ae5b-381fe9cef797)

In my own project I had to prepare a test with webgpu with reasout `true` when WebGPU Device Lost and if so run WebGPURenderer with `forceWebG ` parmeter

```
async function testWebGPUWithOnDeviceLost() {
  let forceWebGL = false;

  const testRenderer = new THREE.WebGPURenderer({ antialias: true, forceWebGL: false });
  
  const testScene = new THREE.Scene();
  const testCamera = new THREE.PerspectiveCamera(45, 1, 0.1, 10);
  testCamera.position.z = 1;
  const testGeo = new THREE.BoxGeometry(0.1, 0.1, 0.1);
  const testMat = new THREE.MeshBasicMaterial({ color: 0x00ff00 });
  const testMesh = new THREE.Mesh(testGeo, testMat);
  testScene.add(testMesh);

  const tempContainer = document.createElement('div');
  document.body.appendChild(tempContainer);

  return new Promise(async (resolve) => {
    let deviceLostCalled = false;

    // Obsługa utraty urządzenia
    testRenderer.onDeviceLost = (info) => {
      console.warn('Test WebGPU Device lost:', info);
      deviceLostCalled = true;
      forceWebGL = true;
      cleanup();
      resolve(forceWebGL);
    };

    function cleanup() {
      testRenderer.dispose();
      if (testRenderer.domElement && testRenderer.domElement.parentNode) {
        testRenderer.domElement.parentNode.removeChild(testRenderer.domElement);
      }
      if (tempContainer && tempContainer.parentNode) {
        tempContainer.parentNode.removeChild(tempContainer);
      }
    }

    try {
      await testRenderer.init();
      tempContainer.appendChild(testRenderer.domElement);

      let start = performance.now();
      let duration = 300; // 0.3 seconds test

      function testRenderLoop() {
        if (deviceLostCalled) return;

        testRenderer.render(testScene, testCamera);

        if (performance.now() - start > duration) {
    
          cleanup();
          resolve(forceWebGL);
        } else {
          requestAnimationFrame(testRenderLoop);
        }
      }

      requestAnimationFrame(testRenderLoop);
    } catch (error) {
      console.warn('WebGPU initialization test failed, fallback to WebGL:', error);
      forceWebGL = true;
      cleanup();
      resolve(forceWebGL);
    }
  });
}

// Run test
(async () => {
  const forceWebGL = await testWebGPUWithOnDeviceLost();
  
  const threeInit = new ThreeInit(
    container,
    forceWebGL
  );
  threeInit.init();
})();

```

I also noticed that when I run `getGPUTier` test from library `detect-gpu` - fps parameter is set as `undefined` on this particular laptop - I never saw before that in any of device `fps` could returns as `undefined`
![da3f348d-8c8e-44e3-98ca-0138a470e97b](https://github.com/user-attachments/assets/30d8ded2-5a28-4cae-a243-4656d33f989e)

**Comment by Mugen87** [comment]
If the issue happens with non-three.js demos as well, this should be reported to the browser vendor. We can't fix such an issue our side. If this happens in Chromium based browser, report the issue here: https://issues.chromium.org/issues

When doing so, please add a `chrome://gpu/` report to the issue.
