### ISSUE TITLE
TransformControls dispose() crashes when domElement is not passed in constructor

### ISSUE THREAD

**Issue by nidal-rr** [mrdoob/three.js#30096]
### Description

If TransformControls is created without `domElement` parameter, which is marked as optional, and then `dispose()` method is called, "this.domElement is null" error occurs and crashes the application.

### Reproduction steps

1. create TransformControls without the domElement parameter
2. call dispose() method

Quickest way to see this is to change `examples/misc_controls_transform.html` line
```js
				control = new TransformControls( currentCamera, renderer.domElement );
```
to
```js
				control = new TransformControls( currentCamera );
				control.dispose();
```
and reload page, Dev Tools console will show the "this.domElement is null" error inside the `dispose()` method.

The solution to this is to check for `this.domElement` in both `connect()` and `disconnect()` methods like so:

```js
	connect() {

		if( this.domElement == null ) return;

		this.domElement.addEventListener( 'pointerdown', this._onPointerDown );
		this.domElement.addEventListener( 'pointermove', this._onPointerHover );
		this.domElement.addEventListener( 'pointerup', this._onPointerUp );

		this.domElement.style.touchAction = 'none'; // disable touch scroll

	}
```
```js
	disconnect() {

		if( this.domElement == null ) return;

		this.domElement.removeEventListener( 'pointerdown', this._onPointerDown );
		this.domElement.removeEventListener( 'pointermove', this._onPointerHover );
		this.domElement.removeEventListener( 'pointermove', this._onPointerMove );
		this.domElement.removeEventListener( 'pointerup', this._onPointerUp );

		this.domElement.style.touchAction = 'auto';

	}
```
and remove the
```js
if ( domElement !== null ) {
```
check in constructor which only guards call to `connect()`.

### Code

```js
let control = new TransformControls( currentCamera );
control.dispose(); //<-- this crashes with "this.domElement is null"
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/mnqr9oj0/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/xno7bmw0/)

### Version

0.170.0

**Comment by Mugen87** [comment]
Given the policy that the engines usually does not validate user input, there is not necessarily a need for a change. The existing runtime error should make the error situation already clear.

**Comment by nidal-rr** [comment]
I got impression that the `domElement` constructor parameter is optional from the `TransformControls.js` source code, because it seems marked as such:
```js
constructor( camera, domElement = null ) {
```
The documentation also says so.
If that is the case, then statements like:
```js
if ( this.domElement == null ) return;
```
would not constitute validation of user input, but implementation of a code logic that handles optional parameter, IMO.

Just my 2 cents, I might be wrong, haven't dwelled into the threejs source code much, if at all.

**Comment by Mugen87** [comment]
Closing. We can reconsider the issue when if mode devs complain about the current behavior.
