### ISSUE TITLE
Overriding fogNode breaks scene from inline to Fn

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#30104]
### Description

Overriding the fogNode breaks the render 

On a scene using an inline fogNode : 

```
const rangeF = rangeFogFactor(0.0, 100.0 );

scene.fogNode = fog( color(0xff0000),  rangeF);
```

Overriding with a TSL Fn break the engine build : 

```

scene.fogNode = Fn(()=>{

      return fog( color(0xff0000),  rangeF);
})

```

### Live example

This live fiddle uses the latest DEV build targeted in my own fork, since the current repo builds are not updated

[Live fiddle link ](https://jsfiddle.net/sxk9cfme/5/)

### Version

dev build last

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by sunag** [comment]
The fiddle seems to be broken, `Fn()` is a function declaration, it should be called right after, like:

https://jsfiddle.net/k7jhrsb8/3/

```js
scene.fogNode = Fn( ()=>{

      return fog( color( 0xff0000 ),  rangeF );
      
} )(); // call in the final

// instead of 

scene.fogNode = Fn( ()=>{

      return fog( color( 0xff0000 ),  rangeF );
      
} );

```
