### ISSUE TITLE
Manual not up to date

### ISSUE THREAD

**Issue by s-rigaud** [mrdoob/three.js#30140]
### Description

I'm currently reading the manual to learn more about Three.js.

It seems like it has not been updated for at least two weeks, this page still reference the MMDLoader :  https://threejs.org/docs/index.html?q=MMD#manual/en/introduction/Animation-system

while I think it has been removed in this PR https://github.com/mrdoob/three.js/pull/30003/files#diff-8ae70164bf929f8d6ea0f4b3a9225179ddc536ae15baf637de3e4d1f17d45f4dL113

### Reproduction steps

Go to https://threejs.org/docs/index.html?q=MMD#manual/en/introduction/Animation-system

### Code

```js
// code goes here
```

### Live example

https://threejs.org/docs/index.html?q=MMD#manual/en/introduction/Animation-system

### Version

r172

**Comment by Mugen87** [comment]
The documentation is updated per release. The status on `dev` might be different than in production so if you want to be on the safe side, study the code from the current release.
