### ISSUE TITLE
Use JSdoc types for code linting

### ISSUE THREAD

**Issue by s-rigaud** [mrdoob/three.js#30158]
### Description

I tried setting up a JS analyzer in my VsCode config to see if any bug can be easily identified in the source code. And I tried experimenting with `jsconfig.json`.

```json
{
    "compilerOptions": {
        "checkJs": true,
        "lib": [] // Do not include dom ('Node' namespace conflict)
    },
    "include": [
        "src/**/*",
        "examples/**/*"
    ]
}
```

This is just a little experiment but I find out two points in which this type of config might be usefull:

- It allows to elevate types from the JSdoc and see incoherences in the used types, ex: 

// src\nodes\code\ScriptableNode.js::453
// type of getOutput should be a ScriptableValueNode

![image](https://github.com/user-attachments/assets/9a895ae2-767c-42c0-9864-06de9488a681)

- It allows to detect missing/broken call to functions, ex:

// src\nodes\code\ScriptableNode.js::483

![image](https://github.com/user-attachments/assets/3783402a-30b1-4e1a-ac5e-33a40cfe15b6)

There is a lot of false positives or missing type references but I might be handy to look at it from time to time to detect types inconsistency and possible errors.

### Solution

Use this config at the end of a documentation or development cycle to analyze possible errors. 

### Alternatives

Stay with the current config with less visibility on the structure of types but a faster way to document and implement things without taking to much attention to possible errors.
 

### Additional context

Just wanted to share in case it might help the core team :)

**Comment by Mugen87** [comment]
> const method = this.getMethod( this.codeNode );

I'm surprised DeepScan did not detect this issue 🤔 .

**Comment by Mugen87** [comment]
> Stay with the current config with less visibility on the structure of types but a faster way to document and implement things without taking to much attention to possible errors.

I would favor this approach at least for the moment. It's important to get the documentation up and running and then think about a customized template. When this is all done, we can think about utilizing the type informations for code analysis.
