### ISSUE TITLE
The size of an attributeArray

### ISSUE THREAD

**Issue by NikLever** [mrdoob/three.js#30183]
### Description

When creating an attributeArray I found I had to create the array 1 element bigger than required to avoid rendering issues. 

### Reproduction steps

Create an attributeArray from a JavaScript Typed Array

### Code

```js
// This causes problems
const positionArray = new Float32Array((BOIDS) * 3);
//This fixes it
const positionArray = new Float32Array((BOIDS+1) * 3);
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/mnqr9oj0/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/xno7bmw0/)
Problem https://codepen.io/nik-lever/pen/emOWyMq
Solution https://codepen.io/nik-lever/pen/GgKmrXZ

### Version

v171

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by mrdoob** [comment]
I suspect it's an issue in your code and not in the library. 

Please use the forum or the chat get help with your code.

**Comment by mrdoob** [comment]
Found the discussion in the forum: 
https://discourse.threejs.org/t/is-this-a-tsl-bug/75441

**Comment by NikLever** [comment]
It appears to be a Mac Silicon issue.
