### ISSUE TITLE
Shader rendering on Mac

### ISSUE THREAD

**Issue by andreasrosdal** [mrdoob/three.js#30187]
This is a bugreport in the Freeciv 3D version which uses a custom Webgl shader to render the terrain.

Some users on Mac are reporting a bug that the terrain shader-material is always black, when the shader for the terrain mesh should render the terrain in the correct terrain colour depending on the map tile terrain.
This bug never occur on Chrome on Windows.

https://www.freecivx.net/

### Reproduction steps

1. Go to https://www.freecivx.net on a Mac
2. Start a new game
3. Observe black terrain 

### Code

https://github.com/freecivx/freecivx/blob/main/freeciv-web/src/main/webapp/javascript/webgl/mapview_webgl_square.js

https://github.com/freecivx/freecivx/blob/main/freeciv-web/src/main/webapp/javascript/webgl/shaders_square/terrain_fragment_shader.glsl

### Live example

* https://www.freecivx.net

### Screenshots

<img width="1470" alt="Screenshot 2024-12-21 at 4 41 35 PM" src="https://github.com/user-attachments/assets/a8514756-fc62-46bd-9d73-859391645d1e" />

### Version

r171

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by andreasrosdal** [comment]
Mixing `MeshPhysicalMaterial` with a custom shader can cause conflicts due to differences in lighting models, blending, or depth settings. The water rendering correctly suggests these might be interacting. 

**Possible Issues:**
1. **Lighting Conflicts:** `MeshPhysicalMaterial` uses PBR, while your custom shader might not. Align lighting calculations or simplify the water material.
2. **Blending/Depth Issues:** Different blending modes or depth testing can cause z-buffer problems. Ensure proper settings like `depthWrite = false` and adjust `renderOrder` to control rendering sequence.
3. **Color Space:** Ensure both materials use the same encoding, like `sRGBEncoding`.
4. **Rendering Order:** Make sure water renders before terrain.
5. **Shared Uniforms:** Use consistent uniforms for lights and camera.

**Fixes:**
- Temporarily replace `MeshPhysicalMaterial` with `MeshBasicMaterial` to isolate the problem.
- Replace the water material with a custom shader for consistency.
- Align settings like blending, depth testing, and color encoding across both materials.

If issues persist, unify water and terrain rendering under custom shaders to ensure consistency.

**Comment by Mugen87** [comment]
We are not maintaing FreeCiv so it seems you have reported the issue at the wrong repository?

**Comment by andreasrosdal** [comment]
I am maintaining Freeciv 3D, and really really would appreciate help understanding this use of Three.js. 
Thank you.

**Comment by Mugen87** [comment]
Sorry but we do usually not help applications finding their bugs. Please use the forum, Discord or stackoverflow like all other devs.

**Comment by andreasrosdal** [comment]
Ok. This could be an opportunity for improving Three.js, for example performing some kind of shader validation, or colour space validation, and logging a warning in this case.

**Comment by andreasrosdal** [comment]
It's also a case where it works correctly on Windows, and differently on Mac.

**Comment by gkjohnson** [comment]
> It's also a case where it works correctly on Windows, and differently on Mac.

This is likely an issue an issue with the custom shader code. There are a lot of behavioral inconsistencies between platforms that aren't surfaced well and outside of the three.js' scope to be responsible for. And unfortunately with so many other priorities digging into and debugging complex user code to help isn't something the project has the bandwidth to do.

Your best bet is to ask at the forum and try to make a minimal reproduction example showing what's happening and report it to the browser vendor (assuming it turns out the issue isn't out-of-spec shader code).

**Comment by andreasrosdal** [comment]
This bug is fixed now. The shader was combining rgb and rgba in the results Pixel. Switching to using rgba everywhere in the shader solved it. Possibly Mac defaults to transparent pixels.
