### ISSUE TITLE
scene.environment is coloring shadows 

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#30193]
### Description

Scene.environment is coloring shadows

<img width="584" alt="Screenshot 2024-12-23 at 11 10 29" src="https://github.com/user-attachments/assets/a993a29a-5af9-4855-9488-7eb39facd754" />

### Live example

[https://jsfiddle.net/jod9mvLs/37/](https://jsfiddle.net/jod9mvLs/37/)

### Version

last

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Samsy** [comment]
@mrdoob  
Shadow map had issues with Fog and Background, those were coloring the shadow map 

Here this might be a different one

**Comment by Makio64** [comment]
@mrdoob Is there an automatic test with a lot of super simple case screenshoting, to check what change from a version to another ? ( could be run locally if too expensive/long on commit )

With node system it'll be easy to generate case using all node combinaison and see their interactions togethers.

This might prevent future issue and help founding edge cases faster.

**Comment by sunag** [comment]
This is happening because the PMREM's indirect light in `scene.environment` is affecting the physical materials, this is related to the PBR lighting model and not a bug.

The WebGLRenderer version below has the same result.
https://jsfiddle.net/4xwy7u2s/

**Comment by mrdoob** [comment]
@Makio64 Right now we are just using the examples as automated visual tests but could be nice to have a folder dedicated for just tests. Is that something you'll like to work on?

**Comment by Samsy** [comment]
Understood @sunag thought I'm pretty sure things have changed a few version behind, I'm porting a r161 code, and it wasnt coloring at all the scene as it does now ( I'll re-build a r161 and push an example to a fiddle ) 

Also, another thing here : 

[Fiddle](https://jsfiddle.net/dj19co8q/)

This scene has no light, only an environnement, materials are standardmaterial, should'nt they be pitch black ? since there are no light in the scene ? 
@sunag  @mrdoob

**Comment by sunag** [comment]
This scene has no light, only an environnement, materials are standardmaterial, should'nt they be pitch black ? since there are no light in the scene ?
> Removing the background ( line 50 ) produce a pitch black

If you have a black IBL and no analytic light, in a physical material it should reflect no light. So the black materials should be what you expect.

**Comment by Samsy** [comment]
@sunag thank you for your answer, 
The use-case I was wondering about was : 
Red IBL, no analytic light, physical material should be red or black ?

**Comment by sunag** [comment]
If you remove the background line (50) how do you expect to generate a red IBL in your code?

**Comment by Makio64** [comment]
> @Makio64 Right now we are just using the examples as automated visual tests but could be nice to have a folder dedicated for just tests. Is that something you'll like to work on?

Yes, I was thinking about a generative way to do it, combining all node togethers, not sure how many features we want to test as it's getting exponential.. , for example if we have only 4 nodes : 
`env`, `shadow`, `reflector` `gltf`

Then the list would be : 
```
none  
env  
shadow  
env-shadow  
reflector  
env-reflector  
shadow-reflector  
env-shadow-reflector  
gltf  
env-gltf  
shadow-gltf  
env-shadow-gltf  
reflector-gltf  
env-reflector-gltf  
shadow-reflector-gltf  
env-shadow-reflector-gltf
```

Also some features seems to break when render `on` / `off` as reported by @Samsy (forgot which one), if we want to support that for each use case i can render the `on`/`off` combinaison of feature as atlas of 256x256. I think it might be only for the nodes impacting the whole rendering ( env, shadow, etc ).
