### ISSUE TITLE
Add a Method to Convert Between Material Types Without Traversing Object3D

### ISSUE THREAD

**Issue by fullmooooon** [mrdoob/three.js#30195]
## Problem
I have a model where multiple meshes reference the same `MeshStandardMaterial` object. Now, I want to convert the `MeshStandardMaterial` into a `MeshPhysicalMaterial`. However, I found that I need to manually identify and compare references to the `MeshStandardMaterial` due to JavaScript's limitations.

## Suggestion
I suggest adding a method to the `Material` class, named something like `convert`, `transform`, or `mutate` (feel free to choose the most appropriate term). This method would allow materials to be converted from one type to another without requiring traversal of the `Object3D` hierarchy.

## Benefits
This feature would significantly streamline workflows and reduce boilerplate code for scenarios involving material type conversions.

## Note
I'm not sure if adding this function is necessary or if it might cause performance issues. It's just an idea I had.

### Solution

Add a method to the `Material` class that allows direct conversion to another material type. For example:

```javascript
meshStandardMaterial.convertTo(new MeshPhysicalMaterial());
```

### Alternatives

Currently, the solution involves using `.traverse` to iterate through the `Object3D` hierarchy, identify all meshes using the target material, and manually replace their material. For example:

```javascript
scene.traverse((object) => {
  if (object.isMesh && object.material === meshStandardMaterial) {
    object.material = new MeshPhysicalMaterial({
      color: meshStandardMaterial.color,
      metalness: meshStandardMaterial.metalness,
      roughness: meshStandardMaterial.roughness,
    });
  }
});
```

**Comment by mrdoob** [comment]
Doesn't this work? 

```js
material2.copy( material1 )
```

Oh, maybe we should ignore undefineds...

**Comment by fullmooooon** [comment]
@mrdoob  I often use position.copy, and I thought that .copy only affects properties like position.x, position.y, and position.z that can be assigned directly. I didn’t expect that Material.copy could change the type of the material. Thanks for your help! This solution is quite neat!

**Comment by fullmooooon** [comment]
> .[copy](https://threejs.org/docs/index.html#api/en/materials/Material.copy) ( material : material ) : this
Copy the parameters from the passed material into this material.

🤔
