### ISSUE TITLE
Node: onBefore, onAfter events

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#30212]
### Description

Callbacks before a node is rendered, and after a node is rendered would be extremely useful to set renderer state such as autoClear etc.. but also helping for custom instructions 

For example

a reflector, or water, if we need to setup a camera layer before those actually renders for selective render inside a reflector 
this requires a callback before and after the node actually renders 

An issue I mentionned here : 
[https://github.com/mrdoob/three.js/issues/30197](https://github.com/mrdoob/three.js/issues/30197)

### Solution

Provide a onBeforeNode, and onAfterNode render

**Comment by Mugen87** [comment]
Are you aware of the existing possibilities to implement such use cases? The idea is to derive from the built-in node classes and then implement the already existing update methods.

https://github.com/mrdoob/three.js/blob/eb8c334628e6ae895fb6c9da4be2d78a2135c38b/src/nodes/core/Node.js#L532-L558

To let the methods executed per render, you must set `node.updateBeforeType` and `node.updateAfterType` to `NodeUpdateType.RENDER`.

**Comment by Samsy** [comment]
Hey @Mugen87

Thanks for the answer, I was not aware of this mechanism, as it isn't mentioned in the wiki, and not once in the examples ! 

I'll look at it, many thanks

**Comment by Mugen87** [comment]
If you need more example for this pattern, check out the post processing modules in [examples/jsm/tsl/display](https://github.com/mrdoob/three.js/tree/dev/examples/jsm/tsl/display). They use this pattern all over the place.

**Comment by Samsy** [comment]
Thanks @Mugen87
