### ISSUE TITLE
Should `lights_pars_begin.glsl.js` be named `lights_pars_fragment.glsl.js`?

### ISSUE THREAD

**Issue by mhjacobson** [mrdoob/three.js#30216]
### Description

All of the other `pars` shader chunks are named like: `<functionality>_pars_<vertex_or_fragment>.glsl.js`.  Furthermore, other shader chunks with `_begin` have corresponding `_end` or `_maps` or both.

So I'm guessing the name of `lights_pars_begin.glsl.js` was accidental and should instead be `lights_pars_fragment.glsl.js`.

### Reproduction steps

Look at the files in ./src/renderers/shaders/ShaderChunk/.

### Code

N/A

### Live example

N/A

### Version

r170

**Comment by Mugen87** [comment]
`lights_pars_begin` might be located in the vertex shader for materials using Gouraud shading. Hence, including `fragment` in the name would be misleading.
