### ISSUE TITLE
InstanceMesh setColorAt works differently than set material

### ISSUE THREAD

**Issue by xixixao** [mrdoob/three.js#30226]
### Description

`setColorAt` performs differently to set material.

Perhaps this is intended and just missing from docs? I can see that once instanceColor is set WebGLRenderer does something special. Maybe it's just a bug.

### Reproduction steps

If I set a material to an InstanceMesh, like this:

```ts
new THREE.MeshPhongMaterial({ color })
```

and then later `setColorAt` like this:

```
instancedMesh.setColorAt(index, new THREE.Color(color));
```

the result is visibly different.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/bs4oymLr/)

### Screenshots

(the difference is not caused by different position in the scene)
![Screenshot 2024-12-29 at 18 37 39](https://github.com/user-attachments/assets/d3a5bc6b-21c9-4f3a-9c68-4a5807245923)

### Version

r171

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by xixixao** [comment]
One thing I just noticed: If I set the original material color to `0xffffff`, then the instanceColor works as expected.

**Comment by donmccurdy** [comment]
Color of built-in materials in three.js is the product of:

```
<color> = <material color> x <texture color> x <vertex color> x <instance color>
```

This can be used to create different tints while sharing a single texture, for example -- or values set to `#FFFFFF` have no effect (they multiply by 1).
