### ISSUE TITLE
WebGL2 fallback: A possible typo in a function name `gerDrawingBufferSize`

### ISSUE THREAD

**Issue by boytchev** [mrdoob/three.js#30236]
### Description

Recently I found that one of the TSL textures fails when WebGL2 fallback is used: [Water drops](https://boytchev.github.io/tsl-textures/online/water-drops.html). It works fine with WebGPU. The error message is:

```
Uncaught TypeError: this.backend.gerDrawingBufferSize is not a function
```

#### The good news:

I was able to track it down to the function `copyFramebufferToTexture`, which calls `this.backend.gerDrawingBufferSize().y`. Note that the called function starts with `ger`. It might be a typo and the correct name could be `getDrawingBufferSize` with `get` instead of `ger`.

https://github.com/mrdoob/three.js/blob/b78ad4c3c0ba973e4a867034e0c3702f683a7ebc/src/renderers/webgl-fallback/utils/WebGLTextureUtils.js#L734

#### The bad news:

This TSL texture worked fine when it used r168. For the time being I am not able to identify what part of my code is causing the execution to go via `gerDrawingBufferSize`. Also, I am unable to make a minimal reproduction demo that illustrates the issue, I tried, but the minimal demo works fine. 

In any case, if `ger` is a typo, it should be fixed, even if it is not clear when it is executed by "Water drops".

### Reproduction steps

1. Use WebGL2 fall-back
2. Open the texture here: [https://boytchev.github.io/tsl-textures/online/water-drops.html](https://boytchev.github.io/tsl-textures/online/water-drops.html)
3. Look in the console for error messages

### Code

n/a

### Live example

[https://boytchev.github.io/tsl-textures/online/water-drops.html](https://boytchev.github.io/tsl-textures/online/water-drops.html)

#### WebGL2 fall-back and error message:

![image](https://github.com/user-attachments/assets/628a342a-e681-4c0a-bd4c-467da95afefc)

-----

#### WebGPU with correct image and no error message:

![image](https://github.com/user-attachments/assets/7c6ca5fa-91d5-48d5-b582-eb9bbfc1d62e)

### Version

r171

### Device

Desktop

### Browser

Firefox

### OS

Windows

**Comment by Mugen87** [comment]
That is indeed a typo. Do you mind fixing it with a PR?

**Comment by boytchev** [comment]
I'll try (although I have never made any PR, and don't have all needed things installed).

**Comment by EricEisaman** [comment]
> I'll try (although I have never made any PR, and don't have all needed things installed).

If it is as simple as a name change, you may be able to simply fork the repository and hand edit in the GitHub web editor, then submit a PR request.

**Comment by boytchev** [comment]
Thanks, @EricEisaman. Followed your suggestion. Made a PR. All checks passed.
