### ISSUE TITLE
Huge Performances issues / rebuilding node / updating material 

### ISSUE THREAD

**Issue by Samsy** [mrdoob/three.js#30234]
### Description

When rebuilding a material on a node-change ( macbook pro last gen ) 

<img width="488" alt="Screenshot 2024-12-30 at 12 25 03" src="https://github.com/user-attachments/assets/eb1c11e2-9137-41cb-b24b-eefb478bed0d" />

### Live example

updateBuild function in the fiddle : 

[https://jsfiddle.net/hse5xfpd/5/](https://jsfiddle.net/hse5xfpd/5/)

### Version

last

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by sunag** [comment]
You are generating a new shader for the material every time step, should this be a issue? It seems to me more like a bad optimized approach, wouldn't it be better to have two materials and swap them than to have to recompile the same one?

**Comment by sunag** [comment]
This approach should be replaced with multiple materials instead of replacing nodes and forcing a rebuild.

**Comment by mrdoob** [comment]
@Samsy have you been doing that with `WebGLRenderer` all this time? 👀

**Comment by Samsy** [comment]
@mrdoob well no haha 🤣 
I'm sorry then for pushing this issue as this is not an issue indeed
It is hard to grasp the concept of the nodes, and what would be a material re-construction and what isn't, since the gaussian blur is an additional pass but not part of the actual material, for the actual material I guessed this would just be an input change

But after this then, I've been wondering if there is a material cache key comparison to prevent re-building the same material over and over ?

I'll investigate more those before pushing an issue 

Best wishes for the new year !

**Comment by sunag** [comment]
> But after this then, I've been wondering if there is a material cache key comparison to prevent re-building the same material over and over ?

This exists, probably if you had a material/geometry with the same configuration in the scene this step would have been shortened. But this does not apply to all setup either since the node system can use properties of the object itself to help in the construction of the shader.

Best wishes for the new year for you too!
