### ISSUE TITLE
Add examples\js\loaders\* to the npm three package

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#3041]
It would be useful to have the loaders available to those using three via the npm package.  Thus I am looking to add this later today.

I am unsure of the best way to provide multiple three package options to users.  Of course I can keep including everything into the default package but then everyone gets everything whether or not they need it all.  Another alternative is to create many different three packages, such as three-webgl, three-canvas, three-webgl-full, etc, but that seems like it could go on forever.

So right now I am defaulting to including more and more into the default three package unless someone has a better idea.

Thoughts @maxogden?

**Comment by mattdesl** [comment]
For examples/js I find separate modules to be a bit better:

```js
var Controls = require('three-orbit-controls')(THREE)
```

This allows it to be useful outside of the scope of the `three` npm package (i.e. for those using `<script>` tag, browserify-shim, bower, etc) and lets things build on those modules (like `three-orbit-viewer`). 

[relevant](https://github.com/mrdoob/three.js/pull/5888#issuecomment-69931606)

**Comment by shelbyspeegle** [comment]
could we close this issue now? it looks like this was implemented a while back.

**Comment by donmccurdy** [comment]
Good point, thanks!
