### ISSUE TITLE
Recycled Geometry with Different Vertex Colors

### ISSUE THREAD

**Issue by scottgarner** [mrdoob/three.js#3122]
Hi guys,

I know it's best practices to reuse the same geometry when making new meshes where possible, but is there a way to do to use the same geometry with different vertex colors? Right now I'm cloning the geometry and feel like my animation is getting bogged down by all of the individual meshes that are essentially the same geo.

Thanks!

-S

**Comment by dubejf** [comment]
Not currently possible with meshes using standard material. You will need to roll out your own shader, using RawShaderMaterial.
