### ISSUE TITLE
Support DDS files without FourCC

### ISSUE THREAD

**Issue by Henkoglobin** [mrdoob/three.js#3128]
Currently, three.js can only load dds files which have a fourCC, unfortunately, there are dds files around that do not have this. I uploaded an example of such a file here: http://dl.dropbox.com/u/2501002/test.dds . According to the dds documentation, this is allowed behaviour, as this file does not use compression (see http://msdn.microsoft.com/en-us/library/bb943984.aspx, especially the Flag DDPF_RGB). It would be nice if this format could be supported.

Thanks in advance :)

**Comment by seb-mtl** [comment]
Has this ever been addressed? I'm in the same situation at the moment

**Comment by mrdoob** [comment]
I guess not?

**Comment by seb-mtl** [comment]
Thx for the confirmation
