### ISSUE TITLE
How to improve the performance of Ribbon with THREE.GeometryUtils.merge

### ISSUE THREAD

**Issue by jasonji** [mrdoob/three.js#3162]
jsfiddle: http://jsfiddle.net/jasonjifly/D7Tur/.
What I want to improve is that when I'm dragging with mouse, more less cpu usage. I have seen a sample about useing THREE.GeometryUtils.merge to optimize a hundred thousand cubes, it's nearly no cpu usage. But I don't know how to use it on Ribbon.
Thank you, I have submit my question to http://stackoverflow.com/questions/15223150/how-to-improve-the-performance-of-ribbon, but no one answers me.
Thank you very much!

**Comment by dubejf** [comment]
`THREE.Ribbon` has been removed from the library some time ago.
