### ISSUE TITLE
RenderTarget Texture Display on Sprites

### ISSUE THREAD

**Issue by GuyGood** [mrdoob/three.js#3192]
Hey everyone,

i recently ran into a probleme where I wanted to display a rendertarget (texture) on a sprite. 
After review by MrDoob, he suggested to create a Feature Request here :) 

Please check the sample below. By changing the "testmap"-Texture to the "rtTexture" the sprite disappears and is not showing the renderTarget. 

http://jsfiddle.net/Pk85y/40/

It would be nice to know if this is possible at all with WebGL or not. If it is, this is an enhancement request ;) 

Cheerz :) 

For completion,

here is my stackoverflow entry:
http://stackoverflow.com/questions/14334909/sprite-not-showing-rendertotexture-map-rendertarget-map

**Comment by mrdoob** [comment]
#8619
