### ISSUE TITLE
Create a scene - documentation

### ISSUE THREAD

**Issue by philbrookes** [mrdoob/three.js#3203]
The documentation refers to: document.body.appendChild( renderer.domElement );

Although this works, I had to put this inside a (assuming jQuery) $(document).ready(function(){ .... code here .... }

otherwise document.body was null.

I was stuck for a good 30 minutes on this! :) It might be worth mentioning it in the otherwise very helpful documentation.

**Comment by dubejf** [comment]
Nice gotcha!

The *getting started* example shows a correct - and simple - implementation. There are other valid implementation, using `<script defer>` or listening for the `DOMContentLoaded` event, but those are beyond the scope of a simple tutorial.

Closing.
