### ISSUE TITLE
Enhancements for splines in Three.js

### ISSUE THREAD

**Issue by willy-vvu** [mrdoob/three.js#3217]
I have a few feature requests for splines, as what I'm developing might need more functionality.
- Blender Spline import, which means...
- More spline types supported
    - NURBS curves
    - Bezier curves
- An inverse to getPoint, so provided a point, calculates the position on the spline

**Comment by willy-vvu** [comment]
I've gotten simple bezier spline export via a python script from StackOverflow. I've also written my own bezier spline class from scratch. I feel I've grown so much more knowledgeable that I can answer my own questions from two years ago! Wow.

I should probably post some code/info about my process, though I'm not sure who needs it. If you would be helped by it, let me know.

**Comment by mrdoob** [comment]
> I feel I've grown so much more knowledgeable that I can answer my own questions from two years ago! Wow.

😀
