### ISSUE TITLE
controls THREE.TrackballControls causing memory leak

### ISSUE THREAD

**Issue by deethee** [mrdoob/three.js#3223]
Hi, if you instance multiple renderers in multiple div containers, the controls cause a memory leak. For every new instance of the controls they waste about 50mb memory in chrome, wich you can easily see in windows task manager/ressource monitor.

**Comment by kevanstannard** [comment]
@mrdoob I did a quick test to generate a large number of TrackballControls and this appears to be resolved now (r84):

Without `dispose()`

<img width="895" alt="screen shot 2017-03-10 at 8 17 39 am" src="https://cloud.githubusercontent.com/assets/937077/23771193/2ec2d9f0-056a-11e7-8800-5df28e832e00.png">

With `dispose()`

<img width="895" alt="screen shot 2017-03-10 at 8 17 23 am" src="https://cloud.githubusercontent.com/assets/937077/23771204/3980b4de-056a-11e7-81ab-5ead58c376b4.png">
