### ISSUE TITLE
Occlusion culling

### ISSUE THREAD

**Issue by wivlaro** [mrdoob/three.js#3355]
I have a project which is based around a city scene with lots of buildings that occlude each other. I would like to have some kind of occlusion culling.

Here is an idea for an approach:

API
---
Mesh objects have extra boolean fields: occluder, occludable
Renderer has additional boolean field: occlusionCulling, and possibly an integer: maxOccluders

Code
----
* On creation of renderer/on first render with occlusionCulling enabled
  * Create mipmapped occlusionBuffers array, one element per pixel
* After frustum culling and object sort, if occlusionCulling is enabled:
  * Iterate through sorted, opaque meshes to be rendered, front to back:
      * If object is occludable and any occluders already processed this frame:
          * Project vertices (OR optionally bounding box corners) into view space (OR if occluder, use rasterized triangles?)
          * Test each point against each level of occlusionBuffer mipmap from broadest to narrowest
          * If any vertex closer than occlusionBuffer point, stop testing, we have to draw
          * If all vertices further than Z value, object is occluded!
      * If object is an occluder:
          * If first occluder this frame:
              * Ensure occlusionBuffers created
              * Clear occlusionBuffers with far plane value
          * Project vertices into view space
          * Rasterize triangles, for each pixel, if closer than occlusionBuffer value:
              * Set finest occlusionBuffers Z value
          * If there were any changes to occlusion buffer, propagate changes along coarser mipmaps

If anyone has any better ideas for a general solution, I'd like to hear them. Otherwise, at some point in the next few weeks I might have a crack at this myself.

**Comment by kishore25kumar** [comment]
Is it by default occlusion culling enabled in threejs ??

**Comment by ua4192** [comment]
Hi.

This solution is really good for the scene I want to create.
Would it be possible to bring it up in the latest version of threejs  r87?
I don't understand why it has not been adopted by the main branch.
I see that objects have these attributes but the solution is not working.

In r57 it woirks.

Best regards
