### ISSUE TITLE
Intersecting on icosahedron gives error on edge intersect

### ISSUE THREAD

**Issue by lallish** [mrdoob/three.js#3360]
My intersecting works on sphere geometries but not icosahedron geometries. No intersections is returned when a vector shoots at the edge between two triangles.

Like this:
http://i.imgur.com/BwYYs3D.png

Might be hard to see, but I'm shooting 50k vectors from origin inside an icosahedron, and the ones that return no intersect results are on the edge (shown in picture).

Is it intentional or a bug? For my project it would be nice if it chose at least one of the triangles.

**Comment by dubejf** [comment]
Fixed in #3376 by @WestLangley. PolyhedronGeometry now use a more accurate method for face normal calculation. Closing.
