### ISSUE TITLE
THREE.Texture not cloning properly

### ISSUE THREAD

**Issue by SkaceKamen** [mrdoob/three.js#3393]
Hello, maybe it's misunderstanding from my side, but when I clone texture, it doesn't act as it should.
Specifically loading texture using THREE.ImageUtils.loadTextureCube method, then not using loaded texture in THREE and then cloning it.

After some research, I found, that setting needsUpdate to true in cloned texture solves the problem. Is it an issue, or is setting needsUpdate flag after cloning standard procedure?

(using Threejs revision 58)

**Comment by WestLangley** [comment]
> When you declare a new shader, the value of the texture types should always be null, if you set the texture after the UniformsUtils.merge, the shader display the material.

Good point.
