### ISSUE TITLE
Euler3 class equivalent to Blender's

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#3404]
Many math libraries have a EulerRotation class that stores x,y,z rotations along with an order.  There are a number of useful functions for manipulating and converting between Euler angles that can also go on this class.  Right now Three.js does not have a Euler class rather we just pass around a Vector3 along with an order.

Besides the obvious, some useful Euler3 functions are:

* reorder (convert from one euler order to another while maintaining the exist same rotation)
* inverse (obvious)
* clamp (clip rotations to +/-180 degrees)
* alternativeSolution (there are two Euler solutions that are within +/- 180 degrees for each rotation, this switches between the two.)

This is what I am aiming for:

http://www.blender.org/documentation/blender_python_api_2_59_2/mathutils.html#mathutils.Euler

I've written up a draft here that I can complete if there is interest:

https://github.com/bhouston/three.js/blob/euler3/src/math/Euler3.js

**Comment by dubejf** [comment]
It seems like everything has been implemented!
