### ISSUE TITLE
Sprites replaces Object3D.rotation with a single float, but then we do not robustly check for this exceptional case.

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#3417]
Given the Object3D.rotation refactor that is taking place here: #3404, I am concerned about the way that Sprites replace Object3D.rotation with a single float.

It would be better if sprites had a separate rotation value, like Sprite.spriteRotation that was then converted to Object3D.quaternion/rotation on a need basis.

Having Object3D.rotation replacable by a float is likely not a best practice because in most places in the code people do not check if Object3D.rotation is a float or a class, they just assume it is a class.

Here is the place where Object3D.rotation is turned into a float:

https://github.com/mrdoob/three.js/blob/master/src/objects/Sprite.js#L13

**Comment by dubejf** [comment]
Sprite.rotation overload of Object3D.rotation has been removed in 35b2609, circa r63. Sprite rotation is now a property of the material. Closing.
