### ISSUE TITLE
Updating a single object when its geometry changes

### ISSUE THREAD

**Issue by Popov72** [mrdoob/three.js#3472]
(copied from http://stackoverflow.com/questions/16509194/updating-a-single-object-when-its-geometry-changes)
(should be an enhancement request, but I don't know how to do that)

I would like to have a specific object updated because its vertices have changed.

The doc is saying to set `geometry.verticesNeedUpdate` to `true`. However, this is working only if `autoUpdateObjects = true` in the renderer.

If not, it seems the only thing you can do is calling by hand `initWebGLObjects` so that your objects are updated.

However, `initWebGLObjects` is looping over all objects in the scene, which seems overkilled knowing that I have a single (or a couple) of objects to update each frame.

Is there a way to flag my objects as needing an update without having to call `initWebGLObjects` ?

Example of use case: I have a BoxHelper to show the bounding box of an animated element. So this bounding box changes every frame, but if I set `autoUpdateObjects` to `false` on the renderer it will never be updated. As this is the only one element that needs to be updated, calling `initWebGLObjects` (which is what `autoUpdateObjects=true` does) is a bit too much in my opinion.

**Comment by dubejf** [comment]
This doesn't seem to be an issue - scanning the scene for objects flagged out of date is not an expensive computation.

If there is a use case for it, a new Issue should be opened. This 2 year old request doesn't map well with the current implementation of the renderer. I guess a modern equivalent would be to hook update callbacks into WebGLObjects and WebGLProperties?

Also, `renderer.autoUpdateObjects` is gone.(I'll submit a PR to remove it from the API doc later.)
