### ISSUE TITLE
Cloning a scene and using two different renderers

### ISSUE THREAD

**Issue by gaitat** [mrdoob/three.js#3473]
I think that cloning a scene and using the original scene in one renderer and the cloned scene in another renderer should be possible. Currently there is a conflict where the two renderers think they are sharing resources.

I have created a fiddle http://jsfiddle.net/vAxYx/ to demonstrate. At the bottom, if both renderers are enabled you get in the console a lot of warning messages which boil down to sharing resources between the renderers. If either renderer is used then everything is fine.

**Comment by kumavis** [comment]
duplicate of #189
