### ISSUE TITLE
Shadow mapping vs scissor test

### ISSUE THREAD

**Issue by Borisss** [mrdoob/three.js#3532]
Hi!

I've run into issue when trying to use shadows in my scene that is rendered into two separate viewports (separate scenes, based on http://mrdoob.github.io/three.js/examples/webgl_multiple_views.html). The moment I enable shadowing, shadow map (used only in one scene, one viewport) is corrupted. Please see the image attached. There is only one shadow receiver in the screenshot and no object casting shadows, yet, parts of the ground are suggested as in shadow. When I remove renderer.enableScissorTest(true), shadows are ok (but I lose my other viewport rendering of course). 

Can this be done with some workaround?

three.js r58, win7, latest google chrome, latest firefox

Great library btw! Keep up the good work and thanks for any advice!
Regards,
Boris Zapotocky

![bug_shadow](https://f.cloud.github.com/assets/3647854/590845/ad7ba500-c9f1-11e2-8be0-a695bb3a96b7.png)

![bug_shadow_noscissor](https://f.cloud.github.com/assets/3647854/590844/ad71d926-c9f1-11e2-9709-e520c381512a.png)

**Comment by mrdoob** [comment]
Fixed! (2 years later... 😇)

**Comment by Borisss** [comment]
great, thanks! :+1:

**Comment by QuaziKb** [comment]
sure this is fixed? I'm still running into the problem

**Comment by mrdoob** [comment]
Try with the `dev` branch.

**Comment by unphased** [comment]
Confirmed fixed in dev branch. Thanks for fixing this mere weeks before i needed to implement the feature (otherwise i'd have to duplicate the context to render two viewports or settle for shadowmap the same size as my viewport) :+1:

**Comment by QuaziKb** [comment]
Ah okay great!
