### ISSUE TITLE
MTLLoader Example Using "this" inside Static Function Call

### ISSUE THREAD

**Issue by tehdiplomat** [mrdoob/three.js#3539]
I noticed this issue when trying to load textures from Amazon S3 onto my Serve on EC2. 

Inside examples/js/loaders/MTLLoader.js there's a static call at line 356, from MaterialCreature.createMaterial_

```
params[ 'map' ] = THREE.MTLLoader.loadTexture( this.baseUrl + value );
```

Inside of loadTexture() there's a reference to this.crossOrigin. Since "this" is a function and not an object, it returns null instead of whatever crossOrigin is set inside the created MTLLoader. This causes an issue where objects that successfully download from CORS aren't redrawn (because the canvas is dirty and the images crossOrigin attribute never gets set properly) and instead spew out "Uncaught Error: SecurityError: DOM Exception 18 " errors in the console. 

To work around this locally, I just changed the line 436, 
```
//loader.crossOrgin = this.crossOrigin; 
loader.crossOrigin = 'anonymous';
```
but I know that's not a permanent fix for the project.

Anyway, thought you guys should know.

**Comment by dubejf** [comment]
Fixed in #3588 by @gero3. Closing.
