### ISSUE TITLE
TorusKnot.getPos.cv not used

### ISSUE THREAD

**Issue by rhulha** [mrdoob/three.js#3547]
I noticed that the variable cv in TorusKnot.getPos is not used. Which makes sense, because getPos shall return the middle point along the tube I think, regardless of the tube segments ( segmentsT ).

This means the over all code could be made simpler and the two getPos calls could be moved the the outer loop, as the inner loop variable j (v) is ignored.

The parameter v in getPos can be removed therefor as well.

Looks like the whole tang, n, and bitan stuff can be moved to the outer loop as well...

I checked the original away3d code, it is ignored there as well...

**Comment by dubejf** [comment]
Torus knot calculation refactored in #3550 by @rhulha. Closing.
