### ISSUE TITLE
SEA3D File Format - 3ds Max exporter for Three.js

### ISSUE THREAD

**Issue by sunag** [mrdoob/three.js#3568]
Hi.

I am creating a version of SEA3D for Three.js.SEA3D is a cross-platform file format which supports streaming for web, sharing and many features for games 3D.

It is already possible to export of 3ds Max for Three.js:
- Mesh, Multiple Channels, Multi-Sub Object, Skin and Morpher
- Scene Hierarchy with bones
- Materials and Texture including: DiffuseMap, SpecularMap, NormalMap and CubeMap.

Examples:
Rare Seaturtle: http://sea3d.poonya.com/webgl/
Skin and Bone Object: http://sea3d.poonya.com/webgl/skin.html
Morpher: http://sea3d.poonya.com/webgl/morpher.html
LightMap: http://sea3d.poonya.com/webgl/lightmap.html

Introduction to SEA3D for WebGL
http://developers.poonya.com/forum/viewtopic.php?t=55#p155

Project Page:
http://code.google.com/p/sea3d/

Hope you enjoy.

**Comment by prima-meteria** [comment]
I love the 3dsMAX exporter! Awesome work and impressive feature set!

**Comment by DezEbuwa** [comment]
Are there any plans to write any documentation for the sea3d exporter?

**Comment by sunag** [comment]
@prima-meteria Thank you very much.

@DezEbuwa Exporter only? We have some tutorials here about exporter may help:
http://developers.poonya.com/forum/viewtopic.php?f=11&t=25&p=40#p40
http://developers.poonya.com/forum/viewtopic.php?f=11&t=36#p74

A little documentation:
http://translate.google.com.br/translate?hl=en&sl=pt&u=https://code.google.com/p/sea3d/wiki/Intro_3dsMax_Exporter_PT&prev=search

Cheers.
