### ISSUE TITLE
Instancing Meshes, transform & lighting

### ISSUE THREAD

**Issue by jayfield1979** [mrdoob/three.js#3624]
Is it possible yet to instance a mesh so as to apply just transform and lighting updates? 

P.s. well done on getting mentioned by Microsoft themselves on the IE11 preview: http://msdn.microsoft.com/en-us/library/ie/bg182648%28v=vs.85%29.aspx

**Comment by benaadams** [comment]
Exposed/Implemented in this PR #6242

**Comment by dubejf** [comment]
Initial implementation of instancing provided by #6242.
