### ISSUE TITLE
Intersect should not pick invisible objects

### ISSUE THREAD

**Issue by PaulJacobs** [mrdoob/three.js#3647]
#2277 was closed without comment.  A ray should not intersect invisible objects; a cursory reading of the source doesn't appear to show any check for visible at all in that part of the code.  And yes, I realize you could iterate the returned objects but I still maintain that it shouldn't be checking invisible objects at all.  Or at least it could be a parameter somewhere.

**Comment by dubejf** [comment]
@mrdoob Should I close this or do you have a different fix in mind?

**Comment by PaulJacobs** [comment]
I think closing is fine...

**Comment by mrdoob** [comment]
Lets continue in #6757.

**Comment by mrdoob** [comment]
Actually, #6757 mutated...

**Comment by mrdoob** [comment]
Implemented 😅
