### ISSUE TITLE
Angle based vertex normal smoothing

### ISSUE THREAD

**Issue by GuyGood** [mrdoob/three.js#3670]
Hi guys,

I wanted to try and contribute to Three.js and this thread is for discussing about the stuff i wrote.

The questions that are open: 
1) Do you want to use this functionality or do you think three.js needs it?
2) What do you think of my algorithm. I was hoping for some guys to check the functions and maybe try to optimize the functionalty in case question 1) is "yes" ;) 

------------ 

What i caught missing in THree.js is the functionality to smooth dynamically generated geometries based on an angle. (like in 3dsMax for example)
If the angle between two face normals is smaller than 'angle' the faces get smothed and the vertex normal accounts for that smoothing.

I forked the three.js repository and created a new branch.

I provide an example in my github fork:
https://github.com/GuyGood/three.js/blob/AngleBasedSmoothing/examples/webgl_geometry_smoothing.html

The example compares an extruded geometry with bevel applied. 
left: unsmoothed as is, middle: my angle based smoothing, 25°, right: computeVertexNormals(true)
http://img109.imageshack.us/img109/3081/v0jc.png

As I put all my code into Three.GeometryUtils without rebuilding, my example directly uses GeometryUtils.js script. 

New stuff to GeometryUtils briefly explained: 
----------

So, i added the function "calculateVertexNormals"  (should then be renamed to sth else).
It firsts creates new vector3 objects for every vertexNormal for every face of the mesh. (just for having everything at zero).

It then fills an array 'adjacentNormals' with objects so that it contains a face and the vertexNormal, and an empty array for the smoothingGroup stuffs for later on. 

then there is the helper method _sortAdjacentFaces. This is because what i am going to do is iterate over all vertices and check all faces connected to one vertex , so to say in a circular manner. And if i don't sort the array beforehand, i would compare faces, connected to the vertex that do NOT share one edge, which would be no good. As a side note, the last iteration compares the last and first face of the vertex in question. 

After sorting,  the algorithm gets  the angle between the faces and checks if it is <= the user defined angle. if it is, it will generate 'smoothing groups' . These groups are local to each vertex and do not work like in 3dsMax for example. They are just for knowing which facenormal from which face to take into account for the vertex normal calculation. 

After having calculated the groups and based on them, the vertexNormal is calculated using the helper function: '_calculateVectorSumsForSmoothingGroups'

This function is much like the "computeVertexNormal" from geometries but is always area weighted, so normals are accumulated but not normalized within there.

Finally, normalize the vertex normals and we are done. 

-----

I hope i could explain some of the stuff and maybe you like the general idea. I am just proposing some code for review because although it works, there are for sure 2-3 small issues and maybe it can be greatly optimized.
p.s. i know the code is for sure not nice to read but i hope you like the feature anyway and want to have a discussion about it. 

Thanks in Advance

**Comment by bartmcleod** [comment]
I stumbled on this issue today, as I was looking to use the creaseAngle property from a VRML IndexedFaceSet to attain a smoothed curved surface. From what I have found so far, I can only choose between smooth nothing and smooth everything, am I right @mrdoob @WestLangley ? Both solutions (everything and nothing smoothed) look horrible in this particular use case (a bent shape with holes in it).

**Comment by WestLangley** [comment]
@bartmcleod The constant `THREE.SmoothShading` was poorly-named. See the discussion in #10383.

You need to fix your geometry. Duplicate vertices on hard edges and specify proper vertex normals for each vertex.

**Comment by bartmcleod** [comment]
@WestLangley Thanks a ton for your quick reply. I found similar answers by you on Stackoverflow earlier, but I couldn't really believe it. It sounds cumbersome and smelly, as a workaround-more than solid design-to have to duplicate hard edges.

From your older answers I understood that it should be enough to duplicate the hard edges. From your current answer, I understand that we need not only duplicate the edges, but also specify vertex normals. This would imply that simply calling `computeVertexNormals()` would not be sufficient, correct?

Since in my project, I am loading legacy geometry from VRML files, I would have to compute the duplications and the normals, which should be possible once I fully understand the principles.

**Comment by bartmcleod** [comment]
For anyone who finds this with the same question: A small test shows that with duplicate edges, it works just fine when calling only `computeVertexNormals()` to generate the normals automatically. Of course this does not respect any specific creaseAngle, just some default angle. Make sure not to call `mergeVertices`, because this will get rid of any duplicate vertices you created to cater for the duplicate edges.

**Comment by bartmcleod** [comment]
@GuyGood The image you linked too no longer exists in that location.

**Comment by bartmcleod** [comment]
@WestLangley When I look at a standard ThreeJs Cylinder, rendered with computeVertexNormals(), it gets smooth sides, but the angle between the sides and top and bottom appears to be smooth too.
![image](https://cloud.githubusercontent.com/assets/1441397/22476408/9b2e0a74-e7e2-11e6-88c6-1fcea20355b2.png)

Also, the green cube is an IndexedFaceSet with duplicated edges where sharp. It is triangulated and it shows with the lighting. How can this be avoided? The diagonal edge is not duplicated, so it should appear as smooth I think.

**Comment by WestLangley** [comment]
@bartmcleod Sorry, this is not the proper forum for help. Perhaps you can try stackoverflow.

**Comment by bartmcleod** [comment]
Yeah, ok.

**Comment by GuyGood** [comment]
bart, 

What are you looking for? If you can edit the normals of your VRML object in a dedicated Digital Content Creation Software like Blender/3dsMax/Maya whatever, then you should do so. 

If you cant, you can try out the method that I wrote from my fork. Or does this not work anymore? I havn't been using ThreeJS for a long long time. Concerning the image, i don't know what it displayed. I could only guess, sorry. But it was for sure some kind of bevel on a cylinder that was correctly smoothed.

**Comment by bartmcleod** [comment]
GuyGood, how nice of you to respond on such an old issue. 

I have now picked up this thread on Stackoverflow to discuss my issue further, as it might turn out to be just a need for help: http://stackoverflow.com/questions/27055644/three-js-maintaining-creases-when-smooth-shading-custom-geometry

I think the simplest use case that describes my problem is  a Cylinder with computeVertexNormals(). It does not appear to have sharp edges. The top and bottom seem to bulge outward. I understand that it comes from averaging the vertexnormals, which makes sense. What I do not understand is that a default cylinder does not have the necessary duplicated edges to support computeVertexNormals() in a way that produces an expected result.

The same holds true for a standard cube. It also does not seem to have sharp edges and it lights up in a weird way, to say the least. I am getting even more confused, if I build a cube as an IndexedFaceSet, with duplicated edges where necessary (based on creaseAngle). It renders very similar if not identical to a default Cube. Also, a vague line is visible where the triangles are co-planar and should be completely smoothed out.

Of course, I can be totally wrong on all of theses topics, if I missed a point somewhere. I would be happy to try out your code by the way.

**Comment by bartmcleod** [comment]
👍 for the original suggestion of @GuyGood to have a way so smooth out areas based on a crease angle. I have written code now that can duplicate edges if the angle between two face normals is larger than a given crease angle, to keep that angle sharp, as @WestLangley suggested. This works well, but there is an impact on load time. I'm currently working on making this independent on how the geometry is loaded. The solution I have only works on triangulated faces currently, not on polygons.

**Comment by danidr** [comment]
Hello everyone,
I am finding myself in the same situation. @bartmcleod , can you please share such code with us? It could be a great help to those of us who don't care that much about loading time, but do care about proper rendering.
Thank you!

**Comment by bartmcleod** [comment]
Hi @danidr, the code is in the VrmlParser repository on GitHub. If I can find the time, I will lookup the exact bits for you.

**Comment by danidr** [comment]
I guess it's this whole bit?
[EdgeDuplicator](https://github.com/bartmcleod/VrmlParser/blob/master/Renderer/ThreeJs/EdgeDuplicator.js)
Will test it later and report if it works with latest ThreeJS. Thank you again in the meanwhile!

**Comment by WestLangley** [comment]
>I think the simplest use case that describes my problem is a Cylinder with computeVertexNormals(). It does not appear to have sharp edges. The top and bottom seem to bulge outward. I understand that it comes from averaging the vertexnormals, which makes sense. What I do not understand is that a default cylinder does not have the necessary duplicated edges to support computeVertexNormals() in a way that produces an expected result.

FWIW, `CylinderBufferGeometry` will do what you expect -- except on the seam where the sides wrap around, meet, and vertices are not shared. `BoxBufferGeometry` will work as you expect, too.

**Comment by bartmcleod** [comment]
@WestLangley thank you, that might prove to be a really helpful tip. Why does the `CylinderBufferGeometry` have a seam? It can't be that hard to share the vertices of the last triangle with the first... @danidr Yes, that would be EdgeDuplicator. If I recall correctly, it only works on IndexedFacedSet, not on standard geometries, such as a cylinder or a sphere, but you may find that their buffered counterparts work well for you, as West pointed out.

**Comment by danidr** [comment]
@bartmcleod Yes, in fact I have re-used your function (exported as ES6 module – Note: if anyone wants to reuse it, remove all "scope.log" references, or substitute them with "console.log", since it gets what ever scope the function is, and it might not have a log function), on a BufferGeometry, and works perfectly.
I merge vertices before calling your function, and compute vertex normals after.
Thank you again!

**Comment by WestLangley** [comment]
>Why does the CylinderBufferGeometry have a seam?

Because the UVs are not continuous there, so vertices need to be duplicated.

**Comment by Ni55aN** [comment]
Hello everyone! 
I found a solution just by modifying the exist `computeVertexNormals()`
Live example: https://codepen.io/Ni55aN/pen/zROmoe?editors=0010
Source code: https://gist.github.com/Ni55aN/90c017fafbefd3e31ef8d98ab6566cfa

**Comment by bartmcleod** [comment]
@Ni55aN Looking good! How does it behave with other shapes?

**Comment by Ni55aN** [comment]
@bartmcleod I have not tested with a lot of shapes yet. One shape after processing CSG looks correct, but small transitions between neighboring faces are visible (perhaps just because of the geometry)

**Comment by bartmcleod** [comment]
@Ni55aN I have incorporated your gist in the latest master of VrmlParser as VrmlParser/Renderer/ThreeJs/SmoothEdges.js Thank you for your contribution!
@danidr This means that EdgeDuplicator is now a thing of the past.

**Comment by Ni55aN** [comment]
@bartmcleod cool!

**Comment by danidr** [comment]
@bartmcleod Thanks, great news!
