### ISSUE TITLE
Wrong geometry buffer counting

### ISSUE THREAD

**Issue by CraigFeldspar** [mrdoob/three.js#3697]
Hi there,

I found myself believing I had a memory leak on my WebGL geometry buffers.

Indeed, my ```renderer.info.memory.geometries``` counter kept increasing, in spite of the fact that I was carefully disposing of all my geometries.

It seems like this variable increments on every geometry group in the function ```createMeshBuffers```, but is only decremented once in ```onGeometryDispose```, regardless of the number of geometry groups inside the event.

i.e if you create a ```CubeGeometry``` with a ```MeshFaceMaterial``` on it, deallocate it, and then reallocate it, you'll find yourself having ```renderer.info.memory.geometries``` set to 11.

**Comment by dubejf** [comment]
Fixed by #3703.
