### ISSUE TITLE
Sprites are flipped upside-down in envMap taken by CubeCamera

### ISSUE THREAD

**Issue by angryobject** [mrdoob/three.js#3702]
r.59, Chrome Canary 30.0.1579.0 on MacOS X 10.8.4, Intel HD Graphics 4000

Sprite reflection in envMap generated by CubeCamera is flipped upside-down, while other objects behave normally.

Scene setup as follows: a sprite tree, a cone, a cube and a cubeCamera, which is placed inside the cube. Cube material's envMap is set to cubeCamera.renderTarget.

![scenesetup](https://f.cloud.github.com/assets/2060693/874232/60c5f192-f887-11e2-88c0-616005ac86bc.png)

But the sprite tree appears upside-down in reflection.

![envmap](https://f.cloud.github.com/assets/2060693/874234/6880b6ce-f887-11e2-81cf-3bc95524df84.png)

[Demo](http://webgears.ru/public/wgdemos/spriteInEnvMap/).

**Comment by pirsplus** [comment]
In CubeCamera.js
You just need to reverse negative values in camera.up and fov, like:

```
// for all cameras with negative values

const cameraNY = new PerspectiveCamera( -fov, aspect, near, far ); // replace fov to -fov
cameraNY.layers = this.layers;
cameraNY.up.set( 0, 0, 1 ); // replace - 1 to 1 
```

then you get sprites at the right orientation :

![image](https://user-images.githubusercontent.com/20614321/192895786-f2a32c84-9074-4e7b-bd58-1c3657ee9c29.png)
