### ISSUE TITLE
NURBs Trimming?

### ISSUE THREAD

**Issue by Irishness** [mrdoob/three.js#3726]
Love the new NURBs functionality that was recently added (https://github.com/mrdoob/three.js/pull/339).

One very nice feature would be to add NURBs trimming:

![il_nurbs_surf_trim](https://f.cloud.github.com/assets/3970436/925663/1fdcc1c8-ff7c-11e2-9420-db2fc148efc5.jpg)

I'm completely new to NURBs but I'm trying to learn about them as quickly as possible. Trimming would be a really excellent feature, especially since many of the pro CAD products currently have it baked in.

Does anyone have experience with this?

**Comment by dubejf** [comment]
This would be nice a nice extension, but I don't think there is any concrete plan to implement this feature in the foreseeable future as part of the core library.
