### ISSUE TITLE
editor issue when setting MeshFaceMaterial

### ISSUE THREAD

**Issue by rastafermo** [mrdoob/three.js#3736]
Hi everybody, i'm trying to use the editor and i just found out that while setting the meshfacematerial, the editor comes up with the following error.

![schermata 2013-08-09 alle 19 43 51](https://f.cloud.github.com/assets/5080119/940126/c786fd72-0124-11e3-9928-18b2cc6ea680.png)
![schermata 2013-08-09 alle 19 43 59](https://f.cloud.github.com/assets/5080119/940127/c9281f94-0124-11e3-9f6b-55596fbb3b5e.png)
![schermata 2013-08-09 alle 19 44 05](https://f.cloud.github.com/assets/5080119/940128/cab34578-0124-11e3-9026-7040cca61710.png)

MeshFaceMaterial should be called passing an array of materials, so I think that the problem raises because there isn't an array like that and the editor can't set the mesh properly. This fact happens also using the meshes provided by the editor menubar (like Cube, Cylinder etc...)

**Comment by Mugen87** [comment]
Duplicate #4371

**Comment by rastafermo** [comment]
Sorry @Mugen87, why did you set THIS issue as duplicate? I posted it one year before the one you are targeting. Shouldn't be THAT one the duplicate? Just to understand how does it work.
Thanks

**Comment by mypuem** [comment]
Please remove me from this email list.

**Comment by Mugen87** [comment]
@mypuem You have to unsubscribe by yourself.

**Comment by Mugen87** [comment]
@rastafermo I think it does not matter which one will be the leading issue for this problem. You can still subscribe here #4371
