### ISSUE TITLE
JSON export format 3.4 - matrix tag

### ISSUE THREAD

**Issue by flyingzebra** [mrdoob/three.js#3761]
I have recently refreshed my three.js library.  My previous version was exporting a version 3.0 JSON file with clearly readable tags like position, rotation and scale.  This has been replaced in version 3.4 JSON file by a 'matrix' tag.

Honestly, I would have kept the old tag naming for the position, rotation and scale in place for clarity.  Is there a particular reason why this matrix tag is now used instead, and how does this tag work ?

Thanks

**Comment by dubejf** [comment]
`position`, `rotation` and `scale` are redundant in the new format and can be calculated from the `matrix`.
