### ISSUE TITLE
GPU memory leak on page refresh

### ISSUE THREAD

**Issue by Errvald** [mrdoob/three.js#3776]
Hi,

there seems to be some memory leak at least in this example:
http://threejs.org/examples/#webgl_panorama_equirectangular

Open Task Manager in Chrome and check GPU memory basically adding up memory every time you refresh the page.

(Chrome: Version 28.0.1500.95 m)

Is there a way to flush the memory of the page?

**Comment by dubejf** [comment]
This is the profile I'm getting with r72dev. It's similar in r71. 
![r72dev-panorama](https://cloud.githubusercontent.com/assets/8649151/8894484/196f3768-3386-11e5-9b51-425a9d3be0be.PNG)
Please reopen if you can still reproduce the leak with the panorama.
