### ISSUE TITLE
Editor wrong spatial translation

### ISSUE THREAD

**Issue by rastafermo** [mrdoob/three.js#3799]
Hi everybody, I've just noticed that in the editor it's not actually possible to translate in the space. The TransformControls.js provides translation either in every single axis or in a plane, but if you click on the OctahedronGeometry at the center of the translation helper, you can see that it is still using the XY plane, instead of XYZ. 
Any advice on how to fix it, please?

**Comment by dubejf** [comment]
Fixed by #3827.
