### ISSUE TITLE
K3D.js

### ISSUE THREAD

**Issue by kuckir** [mrdoob/three.js#3843]
Hello,

I have made a library for working with 3D triangle meshes. It is called K3D.js and I thought that some people may be interested in it. It is not a rendering engine, so it can be used with any 3D engines, or even just for processing 3D data, without rendering them. You can find it at http://k3d.ivank.net .

The most interesting part is probably the parsers. I have implemented OBJ, 3DS, MD2 and Collada.

What do you think about it? Do you have any suggestions to make it even more usable? I would like to add some advanced 3D operations, like making LODs, volumetric set operations, voxelization etc.

**Comment by dubejf** [comment]
Added a reference to the library in the main Loaders tracker.
