### ISSUE TITLE
Matrix Decomposition is Not Always a Valid Operation

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#3845]
In the three.js paradigm, the user specifies an object's `position`, `quaternion` (or `rotation`), and `scale`, and from that, the object `matrix` is computed.

Sometimes, however, we preform the inverse calculation, and _infer_ a `position`, `quaternion`, and `scale` from an object's `matrix` or `matrixWorld`.

This decomposition occurs in the following functions

    Object3D.applyMatrix()
    Matrix4.decompose()
    SceneUtils.attach()/detach()
    Gyroscope.updateMatrixWorld()

Unfortunately, such a decomposition is not always possible, but we are doing it anyway.

The problems occur when the scale is `non-uniform`.

Here is a fairly simple explanation of what is happening.

If `R` is a pure rotation matrix, and `S` is a scale matrix, and `T` is a translation matrix, then an object's matrix is of the form:

    object.matrix = T * R * S.

When applied to a vector, the order in which these transforms occur is: scale first, then rotation, then translation -- i.e., from right to left. This order is important.

If the object has a parent, and the parent's `matrixWorld` is of the same form,

    parent.matrixWorld = T2 * R2 * S2.

then the object's world matrix is

    object.matrixWorld = T2 * R2 * S2 * T * R * S.

Now, as a special case, suppose that the object's `matrix` is a pure rotation matrix (i.e., `T` and `S` are the identity).

    object.matrix = R

Also suppose that the parent's `matrixWorld` is a pure scale matrix (i.e., `T` and `R` are the identity).

    parent.matrixWorld = S

Then, the object's `matrixWorld` is

    object.matrixWorld = S * R

Notice that the order is reversed -- `S` is on the left.

This means that when the matrix is applied to a vector, the rotation is applied first, and the scale is applied second.

When the scale is _non-uniform_, a transform of this form cannot, in general, be decomposed into a scale followed by a pure rotation.

What this means is that __parents with non-uniform scale need to be avoided__. It is OK if (childless) children have non-uniform scale.

The same problem occurs in `Object3D.applyMatrix()`.

Here is a fiddle showing the issue: http://jsfiddle.net/PwSmH/

This is all a consequence of the decision to represent an object's transform with a  `position`, `quaternion/rotation`, and `scale` -- applied in the order S-R-T.

The only solution, unfortunately, is to change the paradigm. A fallback position is to just say that three.js does not support non-uniform scaling of parent objects.

**Comment by tiansijie** [comment]
should we delete the `applyMatrix ` in `Object3D` since this function is using `decompose` and will be very confusing for the user who don't know what is going on with matrix and might think their matrix is wrong. @WestLangley

**Comment by WestLangley** [comment]
@tiansijie No. We just advise users to avoid non-uniform scale factors in objects that have children.

**Comment by tiansijie** [comment]
@WestLangley where we put these advises? Since I don't see it in threejs documentation. Should we put it in the doc whenever we using the decompse function?
