### ISSUE TITLE
Could three.js include a as3 like matrix.interpolateTo function?

### ISSUE THREAD

**Issue by mokra** [mrdoob/three.js#3848]
Hey everyone,

I believe that while working with 3D, one often has to interpolate the from one transformation matrix to an other. 
In AS3 it is implemented (http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/geom/Matrix3D.html#interpolateTo%28%29) and works like this: 

``` javascript
object.matrix.interpolateTo(newMatrix, 0.2) //0.2 are 20% of interpolation
```

So be best part of this method is, that it does not interpolate the matrix in the classical sense - which would be "a cell is being interpolated from value to an other" - which results in strange behaviour when using this for animation. 

This method **interpolates the transformations** that are being projected by this matrix and it also interprets the rotation of the matrix as the quaternions. 

I haven't seen this kind of function in three.js and I believe it's an important enhancement.

Regards - Mokra

**Comment by WestLangley** [comment]
>well I don't have any specific use for now.

Closing. We can revisit later if there is a compelling use case.

**Comment by PWhiddy** [comment]
I have a question about a potential use case.
Wouldn't this be useful for keyframing animation?
The particular application I have in mind, is a multiplayer scenario where updated player transformations are sent at some interval from a server. But since this is much lower than actual frame rate, smoothing between each player transformation is required. Being able to interpolate between each transformation seems convenient. Is there a better way?

**Comment by mrdoob** [comment]
A matrix is 16 values. position, rotation, scale is 9 values (10 values if you stream quaternions instead). Wouldn't you ant to stream the least amount of data as possible?

**Comment by PWhiddy** [comment]
That's a good point. For steaming it would be more efficient to extract or serialize the matrix to those 10 values. But for the general task of interpolating between two transformations it seems reasonable that there could be a standard function, without having to pull apart the different components. 
I agree with WestLangley's argument that directly modifying a matrix is probably a bad idea. Perhaps it could be a nice feature of Object3D to have a lerp function like the others 
`THREE.Object3D.lerp( objA, objB, objTarget, t );`
