### ISSUE TITLE
SceneLoader incomplete

### ISSUE THREAD

**Issue by Michbeckable** [mrdoob/three.js#3852]
The SceneLoader doesnt consider upVector and target of cameras:

"MyCamera":{
"aspect":1.72741,
"far":2000,
"fov":45,
"near":2,
"position":[-36.0155,-51.3074,23.0647],
"target":[-14.8822,-20.7802,14.5403],
"type":"PerspectiveCamera"
},

camera.up and camera.target have to be set afterwards, manually.

**Comment by dubejf** [comment]
Furthermore, `SceneLoader` is deprecated...

If this is still an issue, it's unlikely to get fixed without a PR.
