### ISSUE TITLE
Implement LoadingManager in JSONLoader

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#3861]
As requested in #3789, would be nice to get some notification when `JSONLoader` finishes loading textures too.

**Comment by rukkusdev** [comment]
you can try this too:

```
var loader = new THREE.JSONLoader();
loader.imageLoader.manager.onLoad = function() {
        //calback
};
```

**Comment by steinbachr** [comment]
you can try this too:

```
var loader = new THREE.JSONLoader();
loader.imageLoader.manager.onLoad = function() {
        //calback
};
```

**Comment by dubejf** [comment]
#5758 was merged. `JSONLoader` uses `LoadingManager` in `r72dev`. If the loaders are wired correctly, the progress callback for textures should work.
