### ISSUE TITLE
EffectsComposer fails without MaskPass

### ISSUE THREAD

**Issue by bjornuppeke** [mrdoob/three.js#3865]
It seems like `THREE.EffectsComposer` is dependent on `THREE.MaskPass`. Should it be that way? `THREE.CopyPass` is required and when leaving it out `THREE.EffectsComposer` throws a nice warning in the console. But not when leaving out `THREE.MaskPass`. Instead it throws an 

_Unaught TypeError: Expecting a function in instanceof check, but got #<Object> EffectComposer.js:91_

**Comment by MichaelHazani** [comment]
Gah, I wish the errors were more explicit - thanks for the heads up, bjorn!
