### ISSUE TITLE
Cinema 4d exporter

### ISSUE THREAD

**Issue by jameskeane1** [mrdoob/three.js#3875]
Hi,

I'm interested to know if there has been / will be any further progress on a cinema 4d exporter?

thanks,
James

**Comment by EskelCz** [comment]
I need it badly for my project so I've decided to do something about it. :) It took me about 14 days, I've learned python and it's almost done. Complete with skeleton animations.

Here's how it looks: [Imgur](http://i.imgur.com/Nwm3fCx.jpg)

I'll try to add it to the library once I test it some more. There are a few pieces I could use some help with. (My vertex normals for triangles are acting a little weird for example.)

**Comment by mrdoob** [comment]
😮!

**Comment by jameskeane1** [comment]
Oh yes!!!! Can't wait for the release!!

**Comment by EskelCz** [comment]
I guess I'm basically done with it. It covers the things I needed, hopefully the latest three.js versions didn't broke anything. It's gona take me a few months to make a good use of it. (I'm waiting for my mocap solution first.)

If anyone wants to give it a try, here it is:
https://github.com/BlackDice/Cinema4D-Threejs-Exporter

**Comment by msimpson** [comment]
@EskelCz 
We have a C4D pipeline here using Blender as a JSON export step for THREE. We will most certainly try this asap.
