### ISSUE TITLE
AMD Support (require.js / node loader)

### ISSUE THREAD

**Issue by sonicsnes** [mrdoob/three.js#3883]
It appears that mrdoob even completed the work in the comments https://github.com/mrdoob/three.js/pull/2084 , but the pull was closed and I can't seem to find the issue anywhere.

Jquery has very good node / amd loader support nowadays and may be worth a look (see the bottom of http://code.jquery.com/jquery-1.10.2.js )

**Comment by craftfortress** [comment]
I am having some trouble with CSSRenderer.  Could someone be kind enough to cast an eye over this?

// Load modules and use them
require.config({
    baseUrl: '/js/',
    paths:{
	THREE : 'three.min', 
	CSS3DRenderer : 'CSS3DRenderer' 
		},
    shim: {
    	THREE : { exports: 'THREE' } ,
        CSS3DRenderer : { 
        deps:['THREE'],
        exports: 'CSS3DObject'} 
	}
});
 
require([ 'THREE' , 'CSS3DRenderer'] , function awesome(){return;} );


Results in : Error THREE is undefined

:/

**Comment by henriqueluz** [comment]
I am facing a problem with TrackballControls and RequireJS:

```Javascript
require.config({
    baseUrl: "",
    paths: {
    "three" : "path/to/three",
    "TrackballControls" : "path/to/TrackballControls" 
    },
    shim: {
        "three": { exports: "THREE" } ,
        "TrackballControls" : { 
           deps:['three'],
           exports: "THREE"} 
        }
});

require(['THREE' , 'TrackballControls'] , function(THREE){} );

**Comment by mrdoob** [comment]
@henriqueluz have a read at #9602
