### ISSUE TITLE
THREE fails to load in node.js

### ISSUE THREAD

**Issue by sonicsnes** [mrdoob/three.js#3884]
Node.js doesn't have a global 'self' object, which causes three to throw an exception when it tries to assign self.console. This could be cleanly fixed if three maintains its own console object, rather than using the global one.

Edit: Appears that I missed the special header / tail that's added when the npm builder runs. However, using a separate console object may still be preferable to clobbering 'self'.

**Comment by Tenari** [comment]
For those wondering v0.56.0 of the npm module is valid. until this `self` issue is resolved, people (myself included) can just use that version.

**Comment by nickjanssen** [comment]
A lot of npm versions appear to be broken. 0.69.0 works for me, latest 0.70.0 does not @bhouston

0.70.0 gives me the following error. Any ideas?
```
/Users/nickjanssen/Documents/htdocs/patroljs/nodejsdemo/node_modules/three/three.js:26612
self._typeface_js = { faces: THREE.FontUtils.faces, loadFace: THREE.FontUtils.
^
ReferenceError: self is not defined
    at Object.<anonymous> (/Users/nickjanssen/Documents/htdocs/patroljs/nodejsdemo/node_modules/three/three.js:26612:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/nickjanssen/Documents/htdocs/patroljs/nodejsdemo/demo.js:4:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by Tenari** [comment]
if you don't actually need to render stuff on the serverside, you can just write a shim that looks like this:

```
var self = {};

var ratio = 16/9.0;

var canvasWidth = 1024;
var canvasHeight = Math.round(1024 / ratio);

var window = {
innerWidth: canvasWidth,
innerHeight: canvasHeight

};
var document = {
  createElement: function(name) {
    /*if (name == "canvas") {
      return new Canvas(canvasWidth, canvasHeight);
    }*/
  }
};

/* full THREE.js lib goes here*/

module.exports = THREE;
```

**Comment by adius** [comment]
It would be great to provide general compatibility with node.js!

**Comment by bhouston** [comment]
```npm install three``` doesn't work?  Oh, I see.

I believe @ErikPeterson, who published 0.70.0 to npm, didn't use the NPM publishing script I wrote: https://github.com/mrdoob/three.js/tree/master/utils/npm that ensures that ThreeJS loads server-side.

I believe @ErikPeterson just copied the standard ThreeJS scripts into into the npm directory and pushed it to npm.

I'll have a look at  fixing this later today.

**Comment by simonThiele** [comment]
@nickjanssen got the same error here while writing tests.

**Comment by bhouston** [comment]
I've just published properly, following the [read me here](https://github.com/mrdoob/three.js/tree/master/utils/npm), 0.70.1 and 0.71.0 on npm using the r70 and r71 tags respectively.

**Comment by simonThiele** [comment]
@bhouston thanks for that, it works perfectly!

**Comment by henrytseng** [comment]
Looks like 0.79 is having issues again?  (three.js: line 24)

**Comment by bhouston** [comment]
A number of people have tried out npm three 0.76.1 and said it is working in production:

https://www.npmjs.com/package/three

Confirmation from users that the new release works well in browser and on server:

https://twitter.com/snowrpa/status/723394100402098178
https://twitter.com/andrewray/status/723247744928739328

**Comment by henrytseng** [comment]
Thanks.  I'll upgrade.
