### ISSUE TITLE
texture.repeat -> texture.scale

### ISSUE THREAD

**Issue by kishalmi** [mrdoob/three.js#3886]
since the default wrapping mode of textures is clamp anyways,
 "repeat" is rather counterintuitive.

e.g. setting tex.repeat=2 (without changing the default wrapping mode)
 actually appears as scaling the texture by 0.5

hence the suggestion of replacing texture.repeat by texture.scale (=1/repeat)

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/pull/11863#issue-246631722
