### ISSUE TITLE
multiple viewports for canvasRenderer

### ISSUE THREAD

**Issue by Saka1984** [mrdoob/three.js#3918]
Hi, I'm using three.js for a while, it helps me quite a lot, so first of all thanks mrdoob very much.

In my case I draw the objects on the webpage by using three.js, on the leftside of the page there should be an thumbnail like the effect in powerpoint, that the stuff I draw on the page should be displayed on the thumbnail synchronously.

My solution is set a new camera and viewport for the thumbnail, that I draw all the objects in one scene but render it in a different angle and viewport, I know if using webglRenderer I can do that by using the bellowing snippets which I get from "webgl_multiple_views.html":

renderer.setViewport( left, bottom, width, height );
renderer.setScissor( left, bottom, width, height );
renderer.enableScissorTest ( true );
renderer.setClearColor( view.background );

But I'm using CanvasRenderer for a good compatibility, as WebglRenderer can not be used in IE/iphone/ipad.

I check the source code of CanvasRenderer.js that there are no functions like setViewport() in it, so how can I do that , or is there another way to implement this effect.

very appreciate for your comments. :)

**Comment by dubejf** [comment]
`setViewport` for `CanvasRenderer` was implemented in #4444.
