### ISSUE TITLE
OBJMTLLoader in R61 : missing mtllibCallback

### ISSUE THREAD

**Issue by brunocndp** [mrdoob/three.js#3990]
In R61 you change the OBJMTLLoader class and now if we ommit the MTL file name in load() method, you don't use the MTLFile name witch is in the Obj file. however, in parse() method we can always find that code 
if ( mtllibCallback ) {
  var mtlfile = line.substring( 7 );
  mtlfile = mtlfile.trim();
  mtllibCallback( mtlfile );
}
is it a forgotten?

Secondary, onProgress, onError parameters seems do be unused in load method (not pass to mtlLoader.load() method

**Comment by mrdoob** [comment]
`OBJMTLLoader` is been removed in `r74`. #8085
