### ISSUE TITLE
Support pointer events for IE11 in controls

### ISSUE THREAD

**Issue by benbro** [mrdoob/three.js#4015]
IE11 added WebGL support but it uses pointer events instead of touch events so touch doesn't work in the controls.

I'm talking about mouse/touch/pen events and not the CSS pointer-events property.
There is no need to support the prefixed msPointer events, only the final spec.

http://blogs.msdn.com/b/ie/archive/2011/09/20/touch-input-for-ie10-and-metro-style-apps.aspx
http://msdn.microsoft.com/en-us/library/ie/dn304886%28v=vs.85%29.aspx

**Comment by chliebel** [comment]
@kumavis There is! Check this one out: https://github.com/CamHenlin/TouchPolyfill

It works perfectly with IE11 on desktop. Please note that IE11 for Windows Phone does support touch events.

**Comment by chliebel** [comment]
@mrdoob I suggest you to reopen this. Chrome will introduce Pointer Event support (https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/ODWmcKNQl0I), Firefox will enable them soon by default (https://groups.google.com/forum/#!topic/mozilla.dev.platform/l45DAXyLCAM).

All in all, pointer events seem to be a more accessible way for us developers to interact with several input types. At least, you should keep track of the further development and availability in browsers. Thanks!

**Comment by mrdoob** [comment]
Interesting...

**Comment by benaadams** [comment]
Are pointer events or touch events important per se? Isn't it more what they represent; e.g. Pan, Pinch,  Rotate? When it might be better to do something more like http://hammerjs.github.io/getting-started/

**Comment by chliebel** [comment]
@benaadams You’re right, we could also use a library like hammer.js that again abstracts the underlying event types. The important thing is IMHO to get rid of the touch-/mouse-only event binding we currently have (there’s at least pen input we currently miss).

In the end, hammer.js and pointer events address the same, but with hammer.js it would be cross-browser and cross-platform compatible today.

**Comment by kumavis** [comment]
Is there a strong argument for why this should be included in three.js and not optionally added by the consumer of three.js?
I'm advocating against bloat.

**Comment by benbro** [comment]
Polyfill for Pointer Events that will be supported natively by Chrome, Firefox.
IE 10 already support it.
https://github.com/jquery/PEP

**Comment by chliebel** [comment]
@kumavis It’s about the controls, not three.js’s core… The controls should work as expected cross-browser, cross-platform with any input method. Currently, the affected controls only bind to touch events, which are disabled by default on Firefox on desktop and not implemented at all in IE 11.

**Comment by kumavis** [comment]
sounds like it does not belong in this repo then

**Comment by chliebel** [comment]
@kumavis It does, the controls can be found in the examples directory: https://github.com/mrdoob/three.js/tree/master/examples/js/controls

**Comment by kumavis** [comment]
perhaps straying from the original issue topic, but is there anything stopping us from breaking off controls into a `threejs-controls` repo ?

**Comment by mrdoob** [comment]
I think the solution for this issue is to be patient until pointer events work the main browsers and then, and only then, change the controls.

Patience guys! 😉

**Comment by SBRK** [comment]
How about now?
https://caniuse.com/#feat=mdn-api_pointerevent

I ran in trouble when Edge 18 would not handle my touch inputs. After adding `-ms-touch-action: none` it kinda worked, but only with one finger input. I had to implement PointerEvent to the OrbitControls

**Comment by DefinitelyMaybe** [comment]
@SBRK would you be willing to get started on it?

**Comment by SBRK** [comment]
I might, the problem is I don't have ideal conditions to test this. Since I don't have a touchscreen Windows device, my only way to try it is through the Remote Desktop client app on an iPad...
My implementation works for my case but I don't know how different browsers would behave when listening to both touchevents and pointerevents

**Comment by DefinitelyMaybe** [comment]
ah. good point. could try do a draft and ask for feedback/testing/input from someone else with a windows touch screen device and/or whichever other devices should be tested on

**Comment by SBRK** [comment]
That's a good idea. For now all I can say is Chrome seems to be clever and triggers only the pointer events handlers.

**Comment by mrdoob** [comment]
So the idea would be to remove all the mouse events and touch events and only use pointer events. Right?

**Comment by Mugen87** [comment]
Merging into #20217.
