### ISSUE TITLE
Feature Request: >1.0 color values

### ISSUE THREAD

**Issue by willy-vvu** [mrdoob/three.js#4046]
I've been using `THREE.EffectComposer` and Blender lately.
In Blender, you can give an object an Emit of (1.0,1.0,4.0) and use a shader to divide 4 from all values, yielding a blue object.
However, doing the same in THREE.js results in a grey object: colors over 1.0 are being truncated to 1.0.
I'd like a way to store and retrieve color values that are greater than 1, so that I can apply bloom to those areas without rendering twice.

Blender screenshot:
![image](https://f.cloud.github.com/assets/3529065/1451517/256b1cf2-429d-11e3-96f8-c4db55ca541d.png)

THREE.js jsFiddle: http://jsfiddle.net/TQd9P/

**Comment by willy-vvu** [comment]
I've recently learned that having buffer values that can exceed 1 is the key to physically based shading and hdr rendering. It would certainly be nice to check out what's going on with the render targets.

**Comment by willy-vvu** [comment]
There's a lot to be said on the topic of Physically Based Shading and High Dynamic Range rendering. Perhaps that's for another issue. But for now, having HDR render buffers would certainly be nicer than LDR.

**Comment by mrdoob** [comment]
Hmm, I'm not sure we're truncating the values to 1.0 at render time, if you're rendering to a FloatType RenderTarget I think you should be getting those values?
