### ISSUE TITLE
Feature request: JSON file format including lines/points?

### ISSUE THREAD

**Issue by vibraphone** [mrdoob/three.js#4051]
Is there any chance the [JSON format](https://github.com/mrdoob/three.js/wiki/JSON-Model-format-3.1) could be modified to include line and vertex primitives? Say by adding "glyphs" and "lines" dictionary entries in addition to the "vertices" and "faces" ones?

**Comment by donmccurdy** [comment]
This is supported in `.toJSON()` and `ObjectLoader` now.

https://github.com/mrdoob/three.js/blob/a42ac0747ca15a292430b75ddd4f823fad84f70f/src/loaders/ObjectLoader.js#L855-L881
