### ISSUE TITLE
Renaming THREE.Object3D to THREE.Object

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#4064]
I've been considering lately to rename `THREE.Object3D` to `THREE.Object`. The reason I used `Object3D` back then was because the IDE I was using color coded `Object` and I had the feeling it was going to create problems.

Does anyone envision any problem with this? Maybe a better naming?

**Comment by dubejf** [comment]
This discussion appears to be over. Feel free to reopen!
