### ISSUE TITLE
Renaming THREE.ParticleSystem to THREE.Points

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#4065]
After (almost) sorting out the `Particle` vs `Sprite` situation, I'm starting to think about `ParticleSystem`. I have the feeling `Points` (or even `Sprites`?) would be a better naming for it. That would also mean renaming `ParticleSystemMaterial` to `PointsMaterial`.

Thoughts?

**Comment by dubejf** [comment]
`THREE.ParticleSystem` was ultimately renamed to `THREE.PointCloud` in e58553d (r68)!
