### ISSUE TITLE
Add GPGPU example?

### ISSUE THREAD

**Issue by zz85** [mrdoob/three.js#4069]
This was discussed in #1183 but since I was digging up some old GPGPU examples I had some time ago, I was wondering if we could add one to three.js examples?

http://jabtunes.com/labs/3d/gpuflocking/webgl_gpgpu_flocking1.html http://jabtunes.com/labs/3d/gpuflocking/webgl_gpgpu_flocking2.html

**Comment by martinleopold** [comment]
hey @zz85. thx for this awesome example. (http://threejs.org/examples/webgl_gpgpu_birds.html)
One issue though: Where do the `texturePosition` and `textureVelocity` uniforms get assigned the respective textures (which are computed in `SimulationRenderer`)? What am I missing?

**Comment by Sage-Brezinsky** [comment]
Hi, @mrdoob
