### ISSUE TITLE
Three.js editor - exponential fog density issue

### ISSUE THREAD

**Issue by rastafermo** [mrdoob/three.js#4135]
Hi everybody,
I write in order to communicate a little mistake in the editor code.
It's impossible to set the density amount of the exponential fog just using the mouse, someone should add setStep(0.00001) to this line:

var fogDensity = new UI.Number( 0.00025 ).setWidth( '60px' ).setRange( 0, 0.1 ).setPrecision( 5 ).onChange( updateFogParameters );

Goodbye!!

PS: I also think that is not very handy to set a range like that (0 - 0.1) and be forced to use a precision of 5. Why don't set a range like (0 - 100) and use just a precision of 2 ?? 
Doing like this it will be necessary to change the line 25:

var density = fogDensity.getValue();

with:

var density = fogDensity.getValue() / 1000;

and line 181:

fogDensity.setValue( scene.fog.density );

with

fogDensity.setValue( scene.fog.density \* 1000);

Hope I didn't forget anything!!

**Comment by Mugen87** [comment]
The related PR should improve the handling of `fogDensity`.
