### ISSUE TITLE
Subimaging for THREE.Texture

### ISSUE THREAD

**Issue by Doidel** [mrdoob/three.js#4155]
Just some inspiration for a subimaging approach, how I did it...

``` javascript
THREE.Texture = function... {
        ...
        this._subImages = [];
        ...
}


    addSubImage: function( offsetX, offsetY, image) {

        this._subImages.push( {
            _subOffsetX: offsetX,
            _subOffsetY: offsetY,
            image: image
        } );

        this.needsUpdate = true;
    },





//from WebGLRenderer
this.setTexture = function ( texture, slot ) {
        ...
        // the code for regular textures  with auto generated mipmaps:
        if ( texture._subImages.length == 0 ) {

        _gl.texImage2D( _gl.TEXTURE_2D, 0, glFormat, glFormat, glType, texture.image );

    } else {                

        for ( var i = 0, il = texture._subImages.length; i < il; i ++ ) {

            _gl.texSubImage2D( _gl.TEXTURE_2D, 0, texture._subImages[ i ]._subOffsetX, texture._subImages[ i ]._subOffsetY, glFormat, glType, texture._subImages[ i ].image );

        }

        texture._subImages = [];

    }
        ...
};
```

... if I find time I might code it out one day, but this would have to be done for all renderers and all cases I guess (CompressedTexture, DataTexture?, Cubestuff?, etc.)

Ah well the benefit... the benefit is performance and fancyness I guess. Replacing parts of a texture is cool :+1: And e.g. for spritesheets it's way faster than instantiating a new texture every time.

Soooo searching for volunteer! :smile:

**Comment by robhawkes** [comment]
`texSubImage2D` is something I'm going to be using quite extensively in ViziCities (for virtual textures) so I'd be keen to know what's blocking this being added – have there been any thoughts on what the API should look like?

In the meantime I'll put together a custom implementation and keep an eye on this ticket for updates.

**Comment by arcanis** [comment]
@mrdoob Not sure if it's of any use to put here, but I'd be greatly interested by this feature too. I know it's quite difficult to design a good API on this, but it would be of tremendous help for quite a few projects where multiple dynamic images need to be displayed at the same time (image galleries, ...).

@robhawkes By any chance, have you been able to put together this implementation you're talking about?

**Comment by FreakTheMighty** [comment]
This would be quite useful to our project. We're working with spherical panoramas and I've found a bottle neck loading textures with size 4096x2048 on mobile devices. `textImage2d` blocks the UI thread for a little over half a second. I may change to cubic maps, but functionality like this would be pretty useful.

@arcanis I can work on testing your implementation.

**Comment by arcanis** [comment]
@FreakTheMighty That would be great; I've just rebased my PR against the current dev branch, and fixed the few issues that I've found until now. I think the main thing that should be tested (and possibly debug) is the mipmap support - I'm still wrapping my head around it.

**Comment by mrdoob** [comment]
#13512
