### ISSUE TITLE
Bump map direction reversed on Intel cards in Linux

### ISSUE THREAD

**Issue by jbaicoianu** [mrdoob/three.js#4157]
It looks like there is some sort of difference in how Intel and Nvidia cards process bump maps (at least in Linux - I haven't verified in other operating systems yet).

The different is most obvious on the baseball stitching and the tennis ball seams - on Nvidia the stitching looks raised, but on Intel it looks recessed.

Nvidia:
![bumpmap-nvidia](https://f.cloud.github.com/assets/251610/1648079/a8ce66c0-596e-11e3-8cdc-c5c3e3b54ea6.png)

Intel:
![bumpmap-intel](https://f.cloud.github.com/assets/251610/1648078/a8ca882a-596e-11e3-9822-ca08ce234008.png)

**Comment by dubejf** [comment]
According to the mesa bug tracker, this issue with Intel drivers has been addressed.
