### ISSUE TITLE
batching of draw calls of all objects with same mesh - maintaining independent properties of objects

### ISSUE THREAD

**Issue by davidedc** [mrdoob/three.js#4160]
Would it be possible to batch the draw calls like explained here? http://youtu.be/rfQ8rKGTVlg?t=14m44s

He basically batches together in the same draw call many objects with the same mesh, sending to the shader the per-object information.

Note that this is not equivalent to a mesh merge, as all objects maintain their independent position and properties that can be still changed at will between frames.

Advantage being that, say for drawing x boxes, one would issue far less than x draw calls (and related calls for setting uniforms, etc.). In the demo of the link, this buys quite a lot of performance...

Would this make sense? Would it be possible?

**Comment by mrdoob** [comment]
Closing in favor of #17505.
