### ISSUE TITLE
Documentation Direction Help

### ISSUE THREAD

**Issue by gregtatum** [mrdoob/three.js#4175]
### Documentation linking to existing examples?

I'm slowly working on some of the documentation and I'm trying to figure out how to add some examples here and there in the docs. I'd like to not duplicate work that's already been done. I believe I will link to examples using relative links where they are pertinent in the API. I don't believe I've seen that done yet. It might be nice to also link to handy external examples.
### Embedded live examples

I'm not sure I'm going to go this next route, but I was wondering if inline examples would be completely out of the question. Specifically some tweakable examples with the various mesh materials I believe would be quite helpful.
### /src code vs /examples code

My next question is regarding the examples code base vs. the src code base. What's the reasoning behind the split between some of the code? A lot of the code in examples is quite handy and I feel like it should be documented. There's no structure in place for that as of yet.

**Comment by looeee** [comment]
@mrdoob there is now an examples section in the docs. 

Documentation of the examples is lacking, but that should be raised as a seperate issue
