### ISSUE TITLE
ColladaLoader ignores multiple texturechannels

### ISSUE THREAD

**Issue by DINmatin** [mrdoob/three.js#4179]
the colladaloader ignores multiple texture channels, like
lightmaps in the emmisive channel.
![emissive](https://f.cloud.github.com/assets/5881603/1683229/e32590fa-5dba-11e3-89c2-f6ee0cb7b0c9.png)

this would be a GREAT enhancement in the collada loader.

/martin.

**Comment by Mugen87** [comment]
> like lightmaps in the emmisive channel.

I think these are no light maps but emissive maps.

**Comment by Mugen87** [comment]
Support for emissions maps was added with #13802.

Closing since we have another issue that tracks support for bump and normal maps. #5345
