### ISSUE TITLE
Blender Exporter: Camera's Y position gets negated.

### ISSUE THREAD

**Issue by kayomarz** [mrdoob/three.js#4207]
Blender exporter seems to **negate** the value of the `y` position of the camera.

_Note: This is not related to the `Flip YZ` feature._

Apart from this, the exporter works great.

_Blender version:_ `2.69.0 (r60991)`
_Three.js revision:_ `63`

The property pane of the _default blender scene_ shows the camera position as: `7.48113, -6.50764, 5.34367`

Blender exporter exports it as: `7.48113, 6.50764, 5.34367`

Following is a snipped of the _default blender scene_ exported using blender exporter.  _(Note that `Flip YZ` is enabled.)_

``` js
    "Camera" : {
        "type"  : "PerspectiveCamera",
        "fov"   : 49.159264,
        "aspect": 1.333000,
        "near"  : 0.100000,
        "far"   : 100.000000,
        "position": [ 7.48113, 5.34367, 6.50764 ],
        "target"  : [ 0, 0, 0 ]
    }
```

After digging into the python code, [line number 2178](https://github.com/mrdoob/three.js/blob/master/utils/exporters/blender/2.65/scripts/addons/io_mesh_threejs/export_threejs.py#L2178) shows that the `y` position is explicitly negated.

Wondering if there's any reason for negating it or maybe just a typo?

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
