### ISSUE TITLE
Shadow map causes glFramebuffer error on chrome only

### ISSUE THREAD

**Issue by Pumuckl007** [mrdoob/three.js#4210]
What I did: Created a shadow map with the height and width of 8192. http://jsfiddle.net/c8VBz/

What I expected: A black square.

What I got: On Chrome Version 31.0.1650.63/Linux AMD 64 Nvida GTX 550Ti THREE.js r54, 
GL_INVALID_ENUM : glBindFramebuffer: target was GL_READ_FRAMEBUFFER_ANGLE (index):1
GL_INVALID_ENUM : glBindFramebuffer: target was GL_DRAW_FRAMEBUFFER_ANGLE (index):1
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost 

When width and height are 8191 no error.

Works fine on Firefox 26.0/linux and IE 11 on windows 7

**Comment by dubejf** [comment]
http://jsfiddle.net/KUx7L/4/ (r71)

FF and Chrome give the same result, no errors generated. If there was a limitation in Chrome, it appears to be raised.
