### ISSUE TITLE
Three.js stopped working on Windows Vista recently

### ISSUE THREAD

**Issue by ddanny** [mrdoob/three.js#4211]
I have noticed a few days ago that our Three.js based tool stopped working in Firefox 25 and 26 on the Windows Vista machines.

Opening any demo available at threejs.org/examples/ returns just the "Your graphics card does not seem to support WebGL" message.

It may be related to some updates the OS performed earlier this week as the Three.js demos used to work a few days ago.

**Comment by dubejf** [comment]
Your card/driver/OS was probably added to the black list: https://wiki.mozilla.org/Blocklisting/Blocked_Graphics_Drivers

Try: https://get.webgl.org/ for troubleshooting.
