### ISSUE TITLE
Proposal: Decoupling WebGLRenderer from ThreeJS Scene graph

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#4221]
Hey all,  I've been a bit absent from contributing recently, maybe that can change a bit...

This might seem like a radical idea and I admit that I am little worried that I am proposing that I take this one, but I think it is something that needs to be done.  Let me explain.
- First, there is this idea of shader batching, it is a means of getting the fastest performance possible from a GPU.  It involves the reordering of scene data so that you group it by shaders to minimize costly state changes in the render pipeline:

http://home.comcast.net/~tom_forsyth/blog.wiki.html#%5B%5BRenderstate%20change%20costs%5D%5D

I think ThreeJS needs this for maximum speed.
- The second issue is the high complexity of the WebGLRenderer class.  While it is easy to use, it is actually fairly complex internally.  I think that we could separate it out so that the GPU renderable Mesh, Particle and Line data isn't built and maintained in the renderer, but rather as separate classes.  Thus there is WebGLMesh, WebGLParticles and WebGLLine that are self-contained generally rather than being implicit classes withing the WebGLRenderer.
- The third issue is that I would like to separate out the traversal of the ThreeJS scene graph from WebGLRenderer.  If we are going to allow reordering of the renderable items, I think it is best to separate out the traversal of the ThreeJS Scene to be a separate class.  This we could have standard separate WebGLSceneTraverser that basically goes over the scene and converts the data to WebGLMesh, WebGLParticles and WebGLLine and submits these to the shader batching core.  This last issue would allow for people to write things that do not use the standard ThreeJS Scene graph in the standard way, the could write their own algorithm that submits WebGLMeshes, WebGLParticles and WebGLLines to the renderer in any fashion they want.

Overall, I think this could speed things up (via shader batching), reduce the complexity of the WebGLRenderer class (by separating out the WebGLMesh, WebGLParticles and WebGLLines as well as the SceneTraverser), and increase the usefulness of ThreeJS's WebGLRenderer outside of strict ThreeJS Scene rendering.

I will have some time over the Christmas break to make an attempt at implementing this if it could possibly be desired.  I think that these changes can be limited to just the WebGL components so that the other renderers can stay the same.  I think I can even keep the main interface to the new WebGLRendererX class the same as the other renderers.

I've written a shader batcher before as well as a scene traverser, just not for WebGL, rather DirectX 10.  Thus I do have a workable design that I can merge together with ThreeJS.

Let me know if I shouldn't attempt this or what other improvements I should try to work in if you think this is a good idea.

**Comment by titansoftime** [comment]
I've gotta ask.. what's up with all this? Is the current dev build working towards this?

**Comment by tschw** [comment]
#6963 discusses the separation of materials, programs and shaders.

Also, once sketched out
```javascript
/**
 * @typedef {{
 *     elementCount: !number,
 *     indexBufferOffset: !number,
 *     vertexBufferOffset: ?number,
 *     sceneGraphNode: !THREE.Object3D,
 *     geometry: !THREE.IGeometry,
 *     material: !THREE.Material
 * }}
 */
THREE.Renderable;
```
as input for the renderer. The frequency of the referenced entities (node, geometry and material) could be counted and multiplied with the time for switching the corresponding state. The results in ascending order give the optimal priorities for of the sorting criteria. 
We may want to use IDs instead of object references, another indirection for the drawcall info, and/or map (parts of) it into a typed array, in practice.
