### ISSUE TITLE
Loader Improvements

### ISSUE THREAD

**Issue by gregtatum** [mrdoob/three.js#4248]
I'm taking a crack at improving some of the loaders, making them a little more consistent in their usage, and then writing out the docs. I'll post anything I need feedback on here.

First thing:

`THREE.Loader` has an `addStatusElement` method, which creates a DOM element that says "Loading ...". It doesn't add it to the DOM, update it, or do anything with it. I was thinking about removing that method as it doesn't appear to do anything, and is not used in the examples.

It seems that if there is any DOM loading interface it should go in `THREE.LoadingManager`. In fact maybe a visual interface should be a separate class that is only in the examples.

So my proposal is to remove that functionality, and if it gets put back in, put it into the examples. Thoughts?

**Comment by SET001** [comment]
+ 100500 for using promises instead of callbacks

**Comment by benaadams** [comment]
Isn't too hard to switch to promises in the calling code, using the existing callback system.

atm we use https://github.com/taylorhakes/promise-polyfill as a promise polyfill as its tiny

Wrap our texture loads in promises, with caching and cpu-side dumping post gpu load something like this:

```javascript

var texturePromises = {};

THREE.ImageUtils.crossOrigin = "anonymous";

function SetTextureAsync( path, wrapping, uniform ) {
	var promise;
	var hashPath = path + '|' + wrapping;
	if ( texturePromises[hashPath] ) {
		promise = texturePromises[hashPath];
	} else {
		promise = LoadTextureAsync( path );
		texturePromises[hashPath] = promise;
	}
	return promise.then( updateLoadStatus )
			.then( function ( texture ) {
				texture.wrapS = texture.wrapT = wrapping;
				uniform.value = texture;
			} );
}

function SetCompressedTextureAsync( path, wrapping, uniform ) {
	var promise;
	var hashPath = path + '|' + wrapping;
	if ( texturePromises[hashPath] ) {
		promise = texturePromises[hashPath];
	} else {
		promise = LoadCompressedTextureAsync( path );
		texturePromises[hashPath] = promise;
	}
	return promise.then( updateLoadStatus )
            .then( function ( texture ) {
            texture.wrapS = texture.wrapT = wrapping;
            uniform.value = texture;
    } );
}

var LoadTextureAsync = ( function () {
	function ReleaseTexture( texture ) {
		texture.image = null;
		if ( texture.mipmaps ) {
			texture.mipmaps = null;
		}
		texture.onUpdate = undefined;
	}
	return function LoadTextureAsync( texturePath ) {
		return new Promise( function ( resolve, reject ) {
			var texture = THREE.ImageUtils.loadTexture( pathTextures + texturePath, undefined, resolve, reject );
			console.log( "* Loading " + texturePath );
			texture.onUpdate = ReleaseTexture;
		} );
	}
} )();

var LoadCompressedTextureAsync = ( function () {
	var ddsLoader = new THREE.DDSLoader();
	function ReleaseTexture( texture ) {
		if ( texture.mipmaps ) {
			texture.image = null;
			texture.mipmaps = null;
		}
		texture.onUpdate = undefined;
	}
	return function LoadCompressedTextureAsync( texturePath ) {
		return new Promise( function ( resolve, reject ) {
			var texture = ddsLoader.load( pathTextures + texturePath + '.dds' + ext, resolve, undefined, reject );
			console.log( "* Loading " + texturePath + '.dds' + ext );
			texture.onUpdate = ReleaseTexture;
		} );
	}
} )();
```
Have an item that holds all the start up promises:
```javascript
var startupResources = [];
```
Create a bunch of texture uniforms and load the promises into the ```startupResources```
```javascript
var textures = {};

function downloadTextures() {
    textures["tileTexture"] = { type: "t", value: null };
    startupResources.push( SetCompressedTextureAsync( "terrain_r", 
        THREE.ClampToEdgeWrapping, textures["tileTexture"] ) );
    ...
}
```
Have an ```animate``` function that switches to ```render``` when the ```loadStage``` is ```Running``` 

```render``` has its own call to ```requestAnimationFrame``` so essentially this function is dumped when everything is loaded.

```javascript
function animate() {
	if ( loadStage === loadStages.Running ) {
		render();
	} else if ( loadStage === loadStages.Loading ) {
		tickLoader();
		requestAnimationFrame( animate );
	}
}
```
In the ```init``` it kicks off all the downloads which add them to ```startupResources``` as per ```downloadTextures``` above.

We then use ```Promise.all( startupResources )``` to wait until they all complete before switching ```loadStage = loadStages.Running``` which triggers the animate function to move to rendering rather than an animated loading screen

```javascript
World.init = function init() {

	if ( setupRenderer() !== true ) return false;

	downloadExtraData();
	downloadShaders();
	downloadTextures();

	animate();

	startWorker();

	Promise.all( startupResources )
        .then( function () {
            needsResize = true;
            resources = texturePromises = undefined;
            document.getElementById( "loadingText" ).style.display = "none";
            document.getElementById( "progressBar" ).style.display = "none";
            document.getElementById( "logoLoading" ).classList.add( "disappear" );
            document.getElementById("topbar").classList.remove( "off" );
            setTimeout( function () {
            	document.getElementById( "logoLoading" ).style.display = "none";
            }, 3000 );
            console.info( "All loaded" );

            SetUpModels();
            SetupUIEvents();

            loadStage = loadStages.Running;
        } )
        .catch( function ( e ) {
            console.error( "Error", e );
            loadStage = loadStages.Errored;
        } );

	return true;
}
```

**Comment by lukehorvat** [comment]
If promises are too opinionated, perhaps loaders could at least use the common Node.js callback style i.e. `function(error, value) { }`? Then three.js wouldn't need to use promises, but folks could easily promisify loaders if they wanted to.

Callback example:

```js
var loader = new THREE.ImageLoader();

loader.load('texture1.png', function(error, image) {
  if (error) {
    // Do something with the error.
  } else {
    // Do something with the image.
  }
});
```

[Promisified](https://nodejs.org/api/util.html#util_util_promisify_original) example:

```js
var util = require('util');
var loader = new THREE.ImageLoader();

util.promisify(loader.load)('texture1.png')
.then(function(image) {
  // Do something with the image.
})
.catch(function(error) {
  // Do something with the error.
});
```

**Comment by mrdoob** [comment]
> If promises are too opinionated, perhaps loaders could at least use the common Node.js callback style i.e. `function(error, value) { }`?

Is there a spec for that?

**Comment by lukehorvat** [comment]
The closest I've found to a spec is [this](https://gist.github.com/CrabDude/10907185). And it is explained in the Node.js documentation [here](https://nodejs.org/api/errors.html#errors_node_js_style_callbacks).

It's just a Node.js convention, and pretty much every library that provides promisification (including ones that aren't tied to Node.js and work in the browser) follows this convention.

You can read more about it [here](http://thenodeway.io/posts/understanding-error-first-callbacks/).

**Comment by looeee** [comment]
I've been promisifying the current loaders for quite a while now without issues. I don't think that they need to be refactored for this.

**Comment by satori99** [comment]
Hi all, One thing that springs to my mind regarding Promises, is that they allow for ES6 async / await style coding, which can help to simplify highly asynchronous code in many cases.

**Comment by donmccurdy** [comment]
THREE.Loader no longer has any DOM/status management code, so I think this issue can be closed? If we want to do anything different with promises vs callbacks that could be opened in a new issue.

**Comment by Mugen87** [comment]
> If we want to do anything different with promises vs callbacks that could be opened in a new issue.

Yeah, sounds good. Let's close this one.
