### ISSUE TITLE
normalmap shader uniform parameters differ from standard names

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#4256]
In the normalmap shader here:

https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderLib.js#L572

It defines uniforms for the various standard material colors (diffuse, ambient, specular) but it does so in a way that is different from every other material because it calls them "uDiffuseColor", "uAmbientColor" and "uSpecularColor".  Every other material uses the standard set out here:

https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderChunk.js#L444

with the names being "diffuse", "ambient" and "specular."

I think there is/was some attempt to prefix uniforms with "u" but it is inconsistently done.  Probably should settle on a single standard here.

I'd suggest as going as far as creating a 'surface_colors' section in the ShaderLib.js for "diffuseColor", "ambientColor", "emissiveColor" and "specularColor" (I'd recommend including "Color" in the name to be clear what it is) as it is pretty common and making it standardized just simplifies things.

**Comment by WestLangley** [comment]
Fixed in #4263.
