### ISSUE TITLE
The  three.js editor  export bug! the export json dose't suit the three.js SceneLoader API

### ISSUE THREAD

**Issue by whose-bird** [mrdoob/three.js#4259]
three.js  provide  a easy model editor for users.
Usually,i use it to draw some model and use "Export Scene" to export my scene.
But ,there is a bug when you use this editor.
My code is as follow:

``` javascript
var loader1 = new THREE.SceneLoader();
loader1.load( 'js/obj/sphere_test.js', function( mesh ) {
    scene.add(mesh);
    mesh.position.set(0,0,0);
} );
```

the bug happen in  three.js  the line No. 12913:

``` javascript
matJSON = data.materials[ matID ];

    for ( parID in matJSON.parameters ) {

        if ( parID === "envMap" || parID === "map" || parID === "lightMap" || parID === "bumpMap" ) {
```

matJSON haven't the property name "parameters"! so it goes wrong.

**Comment by tmdeft** [comment]
i use three js editor, can't export material ?

**Comment by mrdoob** [comment]
Not yet!

**Comment by Mugen87** [comment]
`SceneLoader` is now removed from the library see #11123
