### ISSUE TITLE
THREE.Mesh NormalMap renders invisible on Internet Explorer (11)

### ISSUE THREAD

**Issue by brianushman** [mrdoob/three.js#4284]
My apologies if there is already a reported bug on this.  It seems to only happen in IE (tested with IE11) when the normalMap of a mesh is set the model does not render properly.  I created a jsfiddle with the issue (http://jsfiddle.net/g96F3/1/) and here is a small snippet of what I'm trying to do:

    var imgNormalMap = THREE.ImageUtils.loadTexture('...png', undefined, function() {
        
        loader.load('...obj', '...mtl', function (object) {
        
            object.traverse( function ( child ) {
            
                if (child instanceof THREE.Mesh && child.material instanceof THREE.MeshPhongMaterial ) {
                
                    child.material.normalMap = imgNormalMap ;
                }
            
            });
        
            scene.add(object);
            
        });
    });

Is this a known issue or am I possibly doing something wrong?  Thanks for the help!

**Comment by dubejf** [comment]
The fiddle doesn't work. Assuming that's the problem, `OES_standard_derivatives` is supported in IE since mid-2014 according to http://webglstats.com/.
