### ISSUE TITLE
Enhance TransformControls.js to center gizmo on geometry bounding box

### ISSUE THREAD

**Issue by SebastienHo** [mrdoob/three.js#4286]
Hi, 

Not sure it is the right to ask for an enhancement.

I have used transformControls.js (V64) and realised that the gizmo is centered on local position (0,0,0) of an element. This doesn't mean it is the real center of the mesh.

I have modified the update function, may be you could add it to the next release.

	this.update = function () {

		if ( scope.object === undefined ) return;

        //sho - Add 2014/01/10 - set the gizmo at object center.
        if (scope.object.geometry) {
            if (!scope.object.geometry.boundingBox)
                scope.object.geometry.computeBoundingBox();
            worldPosition.getPositionFromMatrix(scope.object.matrixWorld);
            worldPosition.add(scope.object.geometry.boundingBox.center());
        } else {
            worldPosition.getPositionFromMatrix(scope.object.matrixWorld);
        }
        /******/		
		
		/*scope.object.updateMatrixWorld();
		worldPosition.setFromMatrixPosition( scope.object.matrixWorld );
		worldRotation.setFromRotationMatrix( tempMatrix.extractRotation( scope.object.matrixWorld ) );*/

		camera.updateMatrixWorld();
		camPosition.setFromMatrixPosition( camera.matrixWorld );
		camRotation.setFromRotationMatrix( tempMatrix.extractRotation( camera.matrixWorld ) );

		scale = worldPosition.distanceTo( camPosition ) / 6 * scope.size;
		this.position.copy( worldPosition )
		this.scale.set( scale, scale, scale );

		eye.copy( camPosition ).sub( worldPosition ).normalize();

		if ( scope.space == "local" )
			this.gizmo[_mode].update( worldRotation, eye );

		else if ( scope.space == "world" )
			this.gizmo[_mode].update( new THREE.Euler(), eye );

		this.gizmo[_mode].highlight( scope.axis );

	}

**Comment by mstrater** [comment]
"If you want the conceptual origin to be somewhere other than (0, 0, 0), put your mesh in an Object3D and translate it such that the conceptual center of the mesh is at the Object3D's origin."
This advice saved me so much time. Thanks a ton eric-wieser!

**Comment by wenrenqiang** [comment]
How to make the axis at the center of these objects instead of the origin of the group, and not move the position of the object   Prerequisites do not move the location of the original object 
![image](https://user-images.githubusercontent.com/35467304/62275789-472fd080-b475-11e9-9373-901e9a2b07c2.png)
