### ISSUE TITLE
OBJMTLLoader problem

### ISSUE THREAD

**Issue by tiansijie** [mrdoob/three.js#4320]
I am using an sponza model from  http://graphics.cs.williams.edu/data/meshes.xml and objtMtl loader from your three.js. But I got some weird result shown below.  The first pic I took when using the three.js. You can see the round hole has been blocked. But when I opened this model in Maya. I got the second pic. So, I think there some problem with the mtl obj loader.

![capture](https://f.cloud.github.com/assets/3675602/1960079/525f003c-8241-11e3-9630-99f4f207e2d0.PNG)

![capture2](https://f.cloud.github.com/assets/3675602/1960084/7ef84798-8241-11e3-9014-252a20818023.PNG)

**Comment by mrdoob** [comment]
`OBJMTLLoader` is been removed in `r74`. #8085
