### ISSUE TITLE
Error in editor when assigning an object MeshFaceMaterial

### ISSUE THREAD

**Issue by drewnoakes** [mrdoob/three.js#4371]
To reproduce:
1. Open the editor at: http://threejs.org/editor/ (r65)
2. Create a new scene
3. Add a cube
4. Set the material type as `MeshFaceMaterial`.
5. Observe the screen goes blank, with error:

> Uncaught TypeError: Cannot read property 'attributes' of undefined

![image](https://f.cloud.github.com/assets/350947/2055190/a67d2fa8-8ac1-11e3-906d-f93b3bf59905.png)

**Comment by Mugen87** [comment]
This issues should be obsolete since #11835
