### ISSUE TITLE
Improving material importer / exporter for texture support

### ISSUE THREAD

**Issue by Nimanf** [mrdoob/three.js#4378]
We noticed that current version of MaterialLoader / MaterialExporter (4.2) for ThreeJS Scene format, does not support textures or CubeMaps (envMap) of materials. 

A simple addition to current format can be:
colorMap = texture_path
envMap =  [ path1, path2, path3 ,path4, path5, path6 ] 

We, at Exocortex (http://clara.io), are receiving such requests from ThreeJS users, so they can easily export their materials to ThreeJS format . 

Therefore, We need help of ThreeJS community to improve current ThreeJS Scene format, to enable others like us to export materials properly. 
Thanks

**Comment by patrickFuerst** [comment]
Is there any discussion going on about how to extend the JSON format for the material regarding maps ? 
I plan to extend the material loader as @Nimanf suggested and some of it is already implemented in the Loader.js.
