### ISSUE TITLE
svg import in SVGRenderer 

### ISSUE THREAD

**Issue by ricserje** [mrdoob/three.js#4429]
hi i´ve seen some closed post about svg support and SVGRenderer and i wonder if maybe in the future it could be possible to import an svg file, manipulate and render in a SVGRenderer in threejs?
i know there are other libs to work with svg like fabric and snapsvg that last one has good feats to work with svg files to import and manipulate them but limited to 2d svg transforms

thanks

**Comment by agnivade** [comment]
Hello, SVGLoader is not present in r71. Do I need to build master for this ? Isn't there a master minified version available somewhere ?

**Comment by christopherreay** [comment]
hey @xx85 has this question been made obvolete? I know someone who has already developed his own algorightms for 3d transforms for SVG... svg3d is the project. Nicolas Debessiat.

**Comment by mrdoob** [comment]
Closing in favour of #13478
