### ISSUE TITLE
Orbitcontrols zoom issue on android.

### ISSUE THREAD

**Issue by user972611** [mrdoob/three.js#4461]
On android device with Firefox browser, Misc_control_orbit demo or any demo with Orbitcontrols is quite hard to zoom with two finger (zoom out is too fast and zoom in is hitch).

Here the video i record compare Orbitcontrols vs Trackballcontrols on android: https://www.youtube.com/watch?v=b0oDnsvQ0lw&feature=youtu.be

**Comment by dubejf** [comment]
Tested the orbit control example on Nexus 4 and Galaxy tablet: zoom speed appears to be well calibrated for touch with the current release version (r71). Closing.
