### ISSUE TITLE
Glossiness/roughness map

### ISSUE THREAD

**Issue by bartosh44** [mrdoob/three.js#4478]
Hi, I have got object with brushed metal textures. I would like to use diffuse+specular+glossy+normal maps with three.js. Glossy map helps mi show brushing of metal. Good metal texture is mix of specular and glossy map. Is it possible to use roughness/glossy map texture in three.js?

**Comment by bbigger** [comment]
+1

**Comment by homma-ge** [comment]
+1
Gloss map is necessary for high quality rendering.

**Comment by linkedz** [comment]
+1

**Comment by mrdoob** [comment]
Happy to implement this. But, could someone provide a mesh with `roughnessMap`/`glossMap` that we can include in the library/examples?

**Comment by WestLangley** [comment]
I will file a PR in a few days to support `roughness`. A  model with a roughnessMap and metalnessMap would be appreciated.

**Comment by mrdoob** [comment]
This now comes built in in `MeshStandardMaterial`. Thanks @WestLangley!
