### ISSUE TITLE
model loader and textureloader have some timing sequence problem.

### ISSUE THREAD

**Issue by whose-bird** [mrdoob/three.js#4503]
I have a static model load use the colladaLoader.js  . But, textures   seems load always after the model load.So my model is not texturing!!!  
I konw there is one way  that randerer the scene  by requestAnimationFrame.But it's very expensive to the CPU cost.
 Is there some solutions to solve this problem after all textures have loaded, I can stop randerer the scene???

**Comment by Mugen87** [comment]
As @WestLangley said.

Besides, `ColladaLoader2` properly uses [THREE.LoadingManager](https://threejs.org/docs/index.html#api/loaders/managers/LoadingManager) which gives you even more control over the loading process.
