### ISSUE TITLE
OBJMTLLoader.js seems to fail importing 32Mb OBJ/MTL file.

### ISSUE THREAD

**Issue by iras** [mrdoob/three.js#4505]
Both Firefox 27.0.1/Chrome 33.0.1750.117 seem to choke to death when fed with a relatively medium-size OBJ/MTL file (32Mb). The Activity Monitor (Mac OS X - 10.9.2) showed a Firefox/Chrome process of more than a Gb and counting. Firefox did get to 2 and half Gb and many minutes later before I stopped it.

Firefox was good enough though to report an error occurring in threejs/js/OBJMTLLoader.js:89 which is geometry.mergeVertices();

I commented that line out and the OBJMTLLoader importer completed its job fairly quickly although I had then some problems with some normals which looked been flipped the other way.

Anyone experiencing the same ?

**Comment by huantingchen** [comment]
Just encountered the same problem.
It does work after disabling mergeVertices();
I also read issue 4973.
Is there other solution? Or Is a new version of OBJMTLLoader still in progress?

**Comment by mrdoob** [comment]
New version of `OBJMTLLoader` is still in progress :/

**Comment by mrdoob** [comment]
`OBJMTLLoader` is been removed in `r74`. #8085
