### ISSUE TITLE
THREE.ObjectExporter: exported file does not open in Blender

### ISSUE THREAD

**Issue by lapshin1988** [mrdoob/three.js#4519]
ThreeJs Importer show errors
![errors](https://f.cloud.github.com/assets/4470739/2304235/b56632bc-a20e-11e3-82fc-7a1f4d319df7.png)
Content of exported file:

**Comment by reggie3** [comment]
What happened to ObjectExporter?  The above link no longer works.

**Comment by mrdoob** [comment]
It's now built in. Try doing `object.toJSON()`.

**Comment by reggie3** [comment]
Thanks.  By the way, I'm sure you hear it a lot, but I think you and your team are doing great work with this library.

**Comment by reggie3** [comment]
Is the THREE.js JSONLoader able to load an object created using object.toJSON()?
