### ISSUE TITLE
Text Triangulation Issues

### ISSUE THREAD

**Issue by mattdesl** [mrdoob/three.js#4590]
Test case: (using r66)
https://gist.github.com/mattdesl/9634840

I exported Uni Sans Bold files using the typeface.js web exporter. Here they are, for testing only:
[Version A (Webfont)](https://gist.github.com/anonymous/f6f273113bf1a7dc9602)
[Version B (Non-Webfont)](https://gist.github.com/anonymous/bf5388acd502cedc6684)

Version A output. Notice the problematic `i` and `j`:
![img](http://i.imgur.com/VlPLWkh.png)

Version B output is much worse:
![img2](http://i.imgur.com/KE6qG9B.png)

I've narrowed it down to two issues.

One can be seen with the upper-case `J`, a glyph composed of a single path. The winding order for that path differs between the two `typeface.js` versions, and causes the problems seen in the second image. It looks like the triangulator expects all fonts to use the same initial winding order? The same glyph triangulates fine with `poly2tri`.

The second problem is that the lower-case `j` and `i` are composed of two paths each (the dot and stem). The paths have opposite winding orders, so three.js seems to consider the second path as a hole (instead of a new polygon to be triangulated). In fonts like Optimer, the dot and stem both use the same winding order.

I have briefly skimmed [glyphy](https://code.google.com/p/glyphy/) and notice they do something interesting when processing glyphs. They check winding direction and even-odd number, and if the two disagree, they reverse the contour. Can anyone provide further insight?

**Comment by uniquelau** [comment]
^ The above is a good solution, the following practice seems to work well:

Problem letters containing holes (e.g. e, o) should use the following rules:

1. Outside of shape, is wound 'Clockwise'
2. Inside of shape is wound 'Counter Clockwise'

This is found within the 'Element' menu in Font Forge.
