### ISSUE TITLE
Support custom dash patterns

### ISSUE THREAD

**Issue by bzuillsmith** [mrdoob/three.js#4632]
It would be nice to have the ability to create custom dashed patterns, maybe by changing the `LineDashedMaterial`. I'm thinking it would take an array pattern such as `[0.5, -0.5, 0.25, -0.25]`, produces `__  _  __  _` with variable length. Positive values are dashes. Negative values are gaps. This appears to be supported natively for Canvas so it would be easy to implement for `CanvasRenderer`.

The challenge will be a good implementation in WebGL. I've got a jsFiddle (http://jsfiddle.net/VyP29/2/) here that implements it for WebGL, generating a shader for the pattern given. I'm a newbie, so this shader could probably be better. Someone on StackOverflow said the jsFiddle didn't work for them, so it may need to be rewritten for compatibility with more hardware.

A last note: We could extend this further to support dots in the pattern, represented by a 0 in the array pattern. (eg. `[0.5, -0.5, 0, -0.5]`) to produce `_  .  _  .`. However, this is not natively supported by Canvas and I think it makes the shader logic much more complex.

**Comment by FishOrBear** [comment]
@mrdoob

Simple code, do you think it is feasible?

```js
import { Frustum } from 'three';

function clipLine(p1,p2)
{
    let frustom = new Frustum();//init frustom

    let nearPlan = frustom.planes[5];

    let p1InFrusum = nearPlan.distanceToPoint(p1) > 0;
    let p2InFrusum = nearPlan.distanceToPoint(p2) > 0;
    if (!p1InFrusum && !p2InFrusum)
    {
        return false;//break
    }
    else if (!p1InFrusum || !p2InFrusum)
    {
        let intersecPt = nearPlan.intersectLine(new THREE.Line3(p1, p2));
        WorldToScreenPoint(intersecPt);//Conver to Screen Point
        
        //repeat p1 or p2
        (p1InFrusum ? p2 : p1) = [intersecPt.x, intersecPt.y, 0];
    }
}

```

**Comment by FishOrBear** [comment]
Simple code, do you think it is feasible?

```js
import { Frustum } from 'three';

function clipLine(p1,p2)
{
    let frustom = new Frustum();//init frustom

    let nearPlan = frustom.planes[5];

    let p1InFrusum = nearPlan.distanceToPoint(p1) > 0;
    let p2InFrusum = nearPlan.distanceToPoint(p2) > 0;
    if (!p1InFrusum && !p2InFrusum)
    {
        return false;//break
    }
    else if (!p1InFrusum || !p2InFrusum)
    {
        let intersecPt = nearPlan.intersectLine(new THREE.Line3(p1, p2));
        WorldToScreenPoint(intersecPt);//Conver to Screen Point
        
        //repeat p1 or p2
        (p1InFrusum ? p2 : p1) = [intersecPt.x, intersecPt.y, 0];
    }
}

```

**Comment by Mugen87** [comment]
Since `CanvasRenderer` was removed quite a while ago I think this issue can be closed. I would leave an implementation of custom dash patterns in WebGL up to the user (since it's a quite specific feature request).
