### ISSUE TITLE
Documentation issues related to materials

### ISSUE THREAD

**Issue by robertf** [mrdoob/three.js#4645]
In the documentation page for MeshFaceMaterial, the link '[page:Face3 faces materialindex]' just appears as text rather than as a real link.
Also, in the migration page, in the entry for r52 → r53, it says MeshFaceMaterials in 2 places but MeshFaceMaterial in 1 place. Shouldn't they all be MeshFaceMaterial?

**Comment by Mugen87** [comment]
@mrdoob After migrating `MeshFaceMaterial` to `MultiMaterial` with this PR #7994, the problems mentioned in this issue should be solved.

Link to [MultiMaterial docs](http://threejs.org/docs/#Reference/Materials/MultiMaterial)
