### ISSUE TITLE
Transparent video texture showing previous frames

### ISSUE THREAD

**Issue by bradsimantel** [mrdoob/three.js#4656]
I'm experiencing an issue with a plane with a (transparent .webm) video texture. The video is of a cell rotating in place, and every frame is getting drawn on top of the previous one. Since the video is partially transparent, you can see the previous frames behind the current one. Any suggestions on how to make sure the last frame gets removed before drawing the next one?

Here's the pertinent bit of code:
https://gist.github.com/bradsimantel/10168393

And a screenshot:
![screenshot](http://i.imgur.com/jt2ST7A.png)

**Comment by thelucre** [comment]
Any updates to this issue? On Chrome 43, transparent webm videos are rendering the alpha channel as black and drawing all frames on top of each other. In FF 37, the video frames look right, but the alpha channel is also black.

**Comment by WestLangley** [comment]
@thelucre Transparent webm videos work fine for me on OSX Chrome 42. Post a simple example on stackoverflow if you need help and show all your code.

**Comment by thelucre** [comment]
Ah, it looks like `videoTexture.format = THREE.RGBFormat` was breaking the alpha. Confirmed working in Chrome 43. Thank you, @WestLangley

**Comment by mrdoob** [comment]
@thelucre oh, so this is fixed?

**Comment by WestLangley** [comment]
@mrdoob I am not sure it was broken.

**Comment by thelucre** [comment]
@WestLangley You're right!
@mrdoob It's working as intended in Chrome.
Thank you both.

**Comment by WestLangley** [comment]
Well, I'm not sure about the original issue of this post. I never saw a live demo using a recent version of the library.
