### ISSUE TITLE
Blender Three.js export tool giving bizarre results

### ISSUE THREAD

**Issue by viclib** [mrdoob/three.js#4660]
I've been for a time trying to export animations to Three.js, but it only produces bizarre results. Code:

	var jsonLoader = new THREE.JSONLoader();
	jsonLoader.load("walkcycle/walkingCycle.js",function(geometry,materials){
		chr = new THREE.Mesh( geometry, new THREE.MeshFaceMaterial(materials));
		/*THREE.AnimationHandler.add(geometry.animations[1]);*/
		/*for (var i=0,l=materials.length; i<l; ++i)*/
			/*materials[0].skinning = true;*/
		/*animation = new THREE.Animation( chr, "Walking" );*/
		/*animation.play(0.05);*/
		/*chr.scale.set(5,5,5);*/
		scene.add(chr);
	});

Original mesh on Blender:

![mesh](http://dl.dropboxusercontent.com/u/62862049/Screenshots/01n.png)

Result on Three.js:

![result](http://dl.dropboxusercontent.com/u/62862049/Screenshots/01o.png)

[Link for the .blend](http://www.datafilehost.com/d/33d43d3d)

I'm using Blender 2.7 and the latest exporter on Three.js's master branch. What could be going on?

**Comment by JohnHardy** [comment]
I could only get this working when I kept the Armature modifier, but disabled both vertex groups and bone envelops (then re-enabled after export).  In my case, deleting the modifier didn't help.

**Comment by JohnHardy** [comment]
To assist reproducibility, I was working with the mesh linked too from this video: https://www.youtube.com/watch?v=oLRpnS2HvTs  (direct: https://docs.google.com/file/d/0B4LfJyJoYqQXRFZSS3BpT3ZXRGs/edit?usp=sharing)

**Comment by repsac** [comment]
Just downloaded the model so I will have to get a scene setup first before I can test exports. In the meantime look over this ticket. https://github.com/mrdoob/three.js/issues/6050

There seems, tho I am not crazy about it, a need to have 2 different export options. One for `REST` and one for `POSE`. You need to ensure your armature pose position (Rest or Pose) matches the `Skeletal animations` option. Also see if the older r69 exporter works. Migrating the animation code from the old exporter to the new one has not been smooth.
