### ISSUE TITLE
Matrix4 setRotationFromQuaternion resets translation

### ISSUE THREAD

**Issue by insominx** [mrdoob/three.js#4715]
This is because it forwards to `makeRotationFromQuaternion`.  This behavior is expected when calling a "make" function but not "set".  Shouldn't setRotation only affect the 3x3 part of the matrix?

...Edit - I see that is has been deprecated anyway but being able to set the rotation independently would be useful to have in there.

**Comment by WestLangley** [comment]
We support only`makeRotationFromQuaternion()` to avoid confusion.
