### ISSUE TITLE
TRIANGLE_STRIP support back

### ISSUE THREAD

**Issue by grinner** [mrdoob/three.js#4738]
Ribbons used to do Triangle Strips.  Seems like the WebGlRenderer is pretty tied to 3 vertices per triangle though at this point.   

A path with the new BufferGeometry work to bring these back as well as potentially 2D vertex spec-ing would be great, which it looks like just a matter of getting the itemSize of the geometry attribute correct.

**Comment by ebann** [comment]
Any update on this subject ?

**Comment by Axiverse** [comment]
I've opened a pull request that creates `mode` as a third parameter for Mesh just like it exist for Lines. This seems like the cleanest and most consistent way of implementing this.

**Comment by WestLangley** [comment]
Implemented in #7515
