### ISSUE TITLE
SceneExporter doesn't handle box/sphere/plane parameters

### ISSUE THREAD

**Issue by mstrater** [mrdoob/three.js#4739]
I believe SceneLoader is going to be deprecated so this may be a non-issue, but I thought I'd log it anyway.
When the extra geometries box, sphere, and plane were changed to use a property "parameters" to hold parameters, SceneExporter.js in examples/js/exporters wasn't updated to follow this change. As such, boxes/spheres/planes in the scene get parsed with undefined parameters which breaks the export process.
See f8bd805b1c7939fc6caf22af721c4ba156b870e2 for the original change in question.

**Comment by dubejf** [comment]
Fixed by #6952.
