### ISSUE TITLE
Animation no longer respects multiple calls to `update` in the same frame

### ISSUE THREAD

**Issue by sgrif** [mrdoob/three.js#4748]
Updating to 67 has caused a lot of unexpected behavior. It appears that Animation now acts strangely if you call `update` multiple times in the same frame. From what I can tell, this bug was introduced in 8bb80a36ab6d0af4690a75b108fe6df48bf2e17b (and for the record, 55964a7153c63fca307262b5bc0989c07fc4fd05 isn't exactly a fix...)

**Comment by Mugen87** [comment]
`THREE.AnimationHandler` and `THREE.Animation` are deprecated. Please use the new animation core system. It is way more flexible and advanced than the previous one.
