### ISSUE TITLE
Incomplete serialized on various Geometry types

### ISSUE THREAD

**Issue by kumavis** [mrdoob/three.js#4762]
Certain Geometry types dont have their basic geometry details serialized,
so some properties ( like `vertexColors` ) are not stored.

Affected Geometry Types:
- PlaneGeometry
- BoxGeometry
- CircleGeometry
- CylinderGeometry
- SphereGeometry
- IcosahedronGeometry
- TorusGeometry
- TorusKnotGeometry

https://github.com/mrdoob/three.js/blob/d3cb4e7cfb6b917c1e4f60856c71775d632067d9/examples/js/exporters/ObjectExporter.js#L61-L100

**Comment by Mugen87** [comment]
see https://github.com/mrdoob/three.js/issues/9377#issuecomment-361334691

BTW: `ObjectExporter` has been removed, see f8ecbb150e15bda46d22295ca2d647e1cf2f06d4
