### ISSUE TITLE
Take advantage of WeakMap, if present

### ISSUE THREAD

**Issue by randombk** [mrdoob/three.js#4770]
The need to manually dispose() meshes, geometries, materials, and textures is quite annoying, and according to [this stackexchange comment](http://stackoverflow.com/questions/12945092/memory-leak-with-three-js-and-many-shapes#comment17554133_12945270), is a concequence of the lack of WeakMaps in javascript.

Now that WeakMap support is trickling into browsers, with chrome beta (v35) recently adding support [according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap#Browser_compatibility), and the prevalence of WeakMap shims, are there plans to add in this functionality?

If so, what is the timeframe for such a change? I'm working on a project that won't be released for another few months. Should I bother worrying about deallocating my objects, or can I expect that it will be done automatically by then?

**Comment by Mugen87** [comment]
`WeakMap` will find its way into the core, see #4770

**Comment by donmccurdy** [comment]
#13102 is merged, closing.
