### ISSUE TITLE
transformControl touch screen Cannot read property 'clientX' of undefined

### ISSUE THREAD

**Issue by gehuangyi20** [mrdoob/three.js#4771]
I got this error when the finger leave the screen
![image](https://cloud.githubusercontent.com/assets/3879058/2886017/22e573ce-d4d8-11e3-969a-a1ed139947ce.png)

The problem occurs at transformControl.js on line 727
```javascript
var pointer = event.touches ? event.touches[0] : event;
```

onPointerUp was called after finger leave the screen. Then the length of event.touches  is 0.

Here is the solution.
```javascript
/* change touches to changedTouches*/
var pointer = event.touches ? event.changedTouches[0] : event;
```

For touch screen, each touch event includes three lists of touches:

```touches```: a list of all fingers currently on the screen.
```targetTouches```: a list of fingers on the current ```DOM``` element.
```changedTouches```: a list of fingers involved in the current event. For example, in a ```touchend``` event, this will be the finger that was removed.

Therefore, ```touches``` will be empty after the finger leave the screen. But ```changedTouches``` will still contain the finger information. So, change to ````changedTouches``` will work. I have tested it on Chrome touch screen simulator and my iPad. No error throw.

The following link describe the ```touch event``` in ```HTML5```.
http://www.html5rocks.com/en/mobile/touch/

**Comment by dubejf** [comment]
Fixed by #4792.
