### ISSUE TITLE
Flexible skinning

### ISSUE THREAD

**Issue by ikerr** [mrdoob/three.js#4782]
FBX has a simple, flexible mechanism for attaching a mesh to an object hierarchy (skinning).  In contrast, the Three.js animation system seems to impose the following constraints:
- The mesh must be bound to a hierarchy consisting entirely of THREE.Bone instances rather than a mixed hierarchy of THREE.Object instances that could include bones, lights, meshes, etc.
- The mesh must be bound to an object hierarchy that is a child of the mesh (THREE.SkinnedMesh contains a THREE.Skeleton).

The FBX SDK uses FbxSkin and FbxCluster to describe the binding of objects to meshes:

http://docs.autodesk.com/FBX/2014/ENU/FBX-SDK-Documentation/index.html?url=cpp_ref/class_fbx_skin.html,topicNumber=cpp_ref_class_fbx_skin_html84fab0c8-cc9d-4c6c-87fb-e13a688d11c2

http://docs.autodesk.com/FBX/2014/ENU/FBX-SDK-Documentation/index.html?url=cpp_ref/class_fbx_cluster.html,topicNumber=cpp_ref_class_fbx_cluster_html88dfd4b9-5cc7-492e-91da-6c2ee18d6399

To illustrate the difference between FBX and Three.js, consider the following.  In FBX, I can have a hierarchy such as the following:

```
   b
 /   \
m     b
```

where 'b' represents a bone and 'm' represents a mesh.  With FBX, I can create an FbxSkin that binds the bones, which are not children of the mesh, to the mesh.  This allows me to animate the mesh with those bones.  In Three.js, I cannot find a way to do this...  Three.js (THREE.SkinnedMesh) only seems to support cases where the mesh is the root of the bone hierarchy:

```
   m
 /   \
b     b
```

Are there any plans to eliminate the constraints that I mentioned at the top of this post?  Or perhaps I am mistaken and these constraints do not exist?  If they do exist, I do not see how skinning in FBX can be properly translated to Three.js.

**Comment by looeee** [comment]
@ikerr is this issue resolved by the merged pull request?

**Comment by ikerr** [comment]
@looeee yes, this can be closed
