### ISSUE TITLE
glTFLoader Issue - when other files was loaded after .bin file will cause model loading fail

### ISSUE THREAD

**Issue by ajhsu** [mrdoob/three.js#4788]
Hello guys,
i'm working with three.js with glTF format recently.

I currently using Maya with OpenCOLLADA exporter to export DAE files,
and convert it to glTF by converter.

And I found that when three.js loading a glTF model (a model that include json, glsl, bin, image files), if there has any file was loaded AFTER .bin(ARRAY BUFFER) file, will be fail to display on three.js viewport.

For example, if there has 8 .glsl file and 1 .bin file,
when 7 .glsl file was loaded, then 1 .bin file was loaded and finally the last .glsl was loaded.
And it will cause model load fail because there has file was loaded AFTER .bin file.

Solution advice:
So im currently thinking how to make a solution, and here's mine:
1. Counts the ARRAY_BUFFER file and TEXT file seperately. (around glTFLoaderUtils.js: 80)
2. Counting down when ARRAY_BUFFER file and TEXT file was load complete, and storage its path. (around glTFLoaderUtils.js: 86)
3. When all files were loaded complete, fire the complete event at a time. Making ARRAY_BUFFER  after other TEXT files. (around glTFLoaderUtils.js: 86)
4. Cheers!

(environment: three.js v66, Chrome 34.0.1847.131, Windows 7, nvidia gtx 650)

**Comment by donmccurdy** [comment]
I think this has probably been fixed in the GLTFLoader refactors over the last few months. In any case, testing https://threejs.org/examples/?q=gltf#webgl_loader_gltf now, the network tab shows images loading after the `.bin` files and everything renders just fine.
