### ISSUE TITLE
Mr.doob's Code Style™

### ISSUE THREAD

**Issue by zz85** [mrdoob/three.js#4802]
I wrote a gist describing a little of mrdoob's code conventions (as some have referred to the **MDCS**) and included a **jscs** rules for code style enforcing. https://gist.github.com/zz85/e929503387cdc597b4f7

Not everyone is familiar or used to MDCS so @WestLangley asked if there's a script which can "mrdoobify" the rest of our codebase which has not conformed to that standard.

So some objectives I hope to archive are:
1. Have some documentation on mrdoob's code style (perhaps on the wiki pages?)
2. Add jscs rules so contributors can use it for validating code via pre-commit hook  or editor's linting (sublime / vim) or just part of the build tools.
3. Try some code transformation tools to make existing code more mrdoob style compliant.

For **2**, there are a couple more features in the JSCS I'm waiting to get implemented or merged before it could really enforce MDCS. In particular, https://github.com/mdevils/node-jscs/pull/371 https://github.com/mdevils/node-jscs/pull/333 possibly https://github.com/mdevils/node-jscs/issues/244 and https://github.com/mdevils/node-jscs/issues/126#issuecomment-42379798 too.

As for **3**, I could try out codepainter (https://github.com/jedmao/codepainter) and see how well it works for this.

**Comment by mrdoob** [comment]
I've just started using https://atom.io/packages/linter-jscs with the MDCS preset 😮 Thanks guys!

Out of curiosity... Is there any package that shows unused variables?

**Comment by zz85** [comment]
> I've just started using https://atom.io/packages/linter-jscs with the MDCS preset 😮 Thanks guys!
Nice, I guess it should have been time there's is a decent plugin integration for a popular editor ;)

> Out of curiosity... Is there any package that shows unused variables?

I don't remember JSCS doing that, the usual linters jslint/jshint/eslint etc does that. IIRC, the current project which allows you to simply check unused without enforcing all other rules would be http://eslint.org/ 

It also turns out that an an unused variable checker is something not too difficult to write. I wrote one for JS (using the esprima tokens) and then another for [glsl](https://github.com/zz85/glsl-cleaner/blob/gh-pages/lint/unused.js)).

**Comment by abelnation** [comment]
see: #8805

also, eslint is a great modern tool for js linting.  jscs seems to actually have merged w/ the eslint group, so not sure what the future of that tool is.  would be nice to be able to specify both linting rules and get a resulting auto-formatter for free
