### ISSUE TITLE
Create a clear behaviour for resizes 

### ISSUE THREAD

**Issue by tonnot** [mrdoob/three.js#4813]
Now, it is not clear.  We have two cases:
1 - The width >  height :  the scene height would have to adjust to available height.
2 - The width <  height :  the scene width  would have to adjust to available width.

By now only the case 1 works fine. 
The second case is not  processed by three. The scene keeps it size, only is centered on the screen.
If you make a Horiuzontal resize, you can observe how the scene is centered until the moment in which the width begins to be lower than the height. In this case, the scene simply goes disappearing.

I think we need a horizontal resize too.
Is this a bug ? Could be a feature ? What is your opinion? Thanks

**Comment by Mugen87** [comment]
Like @WestLangley said, the handling of resize events is part of the application layer.
