### ISSUE TITLE
Order independent transparency

### ISSUE THREAD

**Issue by arose** [mrdoob/three.js#4814]
Recently @zz85 mentioned (#4724) a technique to render transparent objects without sorting. There is a [paper](http://jcgt.org/published/0002/02/09/) and a [blog post](http://casual-effects.blogspot.de/2014/03/weighted-blended-order-independent.html) describing it. Also, it has been already implemented in webgl - in cesium ([example](http://bagnell.github.io/cesium/Apps/Sandcastle/gallery/OIT.html)).

I tried to implement the technique with three.js. Here is a [demo](http://arose.github.io/demo/oit/examples/webgl_oit.html) and the [code](https://github.com/arose/three.js/tree/oit) on github.

In the demo you can switch between the order independent rendering (oit), opaque or classical transparency requiring sorted rendering. It is quite convincing - until you start to zoom. I suspect it has something to do with how I calculate the `z` value for the accumulation and revelage shader. I'll try to figure that out, but any help is much appreciated!

**Comment by navigator117** [comment]
in your demo code, 
1. the vertex shader, if the input is already premultipliedAlpha ( like transparent png output by PS), z = ( z4.xyz / z4.w ).z is not needed?
2.  your 2D compositingMaterial with Custom parameters:                  
  blending: THREE.CustomBlending,                                                                                                                                                                                                                                                                               
  blendEquation: THREE.AddEquation,                                                                                                                                                                                                                                                                             
  blendSrc: THREE.OneMinusSrcAlphaFactor,                                                                                                                                                                                                                                                                       
  blendDst: THREE.SrcAlphaFactor 
 the src & dst blend is invert compare to 
 http://casual-effects.blogspot.com/2015/03/implemented-weighted-blended-order.html 2D Compositing Pass. why?

**Comment by looeee** [comment]
Working live example: https://raw.githack.com/arose/three.js/oit/examples/webgl_oit.html

**Comment by trusktr** [comment]
Looks like @pailhead has also made some progress on order-independent-transparency here: https://discourse.threejs.org/t/depth-peel-and-transparency/5365 (or is that something else? It seems to solve some issues that I've seen with the order-dependent transparency)

**Comment by pailhead** [comment]
The demo doesnt run on ios :(

**Comment by pailhead** [comment]
My approach unfortunately can’t work with three unless render buffers are somehow decoupled from targets. I’ve been thinking of somehow hijacking the gl state at the right time to maybe allow for that, but it seems very gnarly.

**Comment by mrdoob** [comment]
> This approach might be more modern, it seems different than what I attempted.

How is it more modern?

**Comment by pailhead** [comment]
I don't know need to dig into it, i figured it was written more recently since it does leverage shaders, the depth peel paper i worked off of i think predates shaders.

**Comment by Mugen87** [comment]
Merging into #9977.
