### ISSUE TITLE
Error in ThreeJS examples: gl.getProgramInfoLog() (66,6): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll 

### ISSUE THREAD

**Issue by ximreh** [mrdoob/three.js#4834]
After updating our project to ThreeJS ver 66 and 67 we came across the following error:
gl.getProgramInfoLog() (66,6): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll. There is no error with version 65.

The error can be reproduced also in the original threejs examples on 
http://threejs.org/examples/#webgl_geometry_colors
http://threejs.org/examples/#webgl_geometry_convex

Browser versions : FireFox 28, 29, Chrome 33, 34

**Comment by dubejf** [comment]
I think I have found the source of the error.

Steps to reproduce (Chrome 43 / Windows):

1- Clear the cache ("cached image and files" is sufficient).
2- Close and reopen the browser.
3- Visit examples on the example page.

The warning seems to be produced anytime a shader is compiled for the first time. Has you navigate between examples, new warnings are generated as you encounter new materials, but after a while, no new warnings appear. There are no warning after a page reload either.

This is a minimal example to produce the warning.
```
var camera = new THREE.PerspectiveCamera( 1, 1, 1, 100 );
camera.position.z = 10;

var scene = new THREE.Scene();
scene.add( new THREE.DirectionalLight( 0xffffff ) );

var geometry = new THREE.BoxGeometry( 1, 1, 1 );
var mat = new THREE.MeshLambertMaterial();
scene.add( new THREE.Mesh( geometry, mat ) );

var renderer = new THREE.WebGLRenderer();
renderer.render( scene, camera );
```

Note that `MeshBasicMaterial` does not produce any warning. Also, if the number of lights is different than 1, no warning is produced.

So the warning probably comes from constructs like this in the shaders:

```
#define MAX_DIR_LIGHTS 1
#if MAX_DIR_LIGHTS > 0
for( int i = 0; i < MAX_DIR_LIGHTS; i++ ) { ...
```

Is there a reason to believe that there are performance concern with this loop? Is it worth it to handle this special case without a loop in the shaders?

I propose that we simply whitelist this warning and omit reporting on warning `/X3557/`.

**Comment by dubejf** [comment]
For reference, the full text of the warning in the latest Chrome (v43) is:
> THREE.WebGLProgram: gl.getProgramInfoLog() (185,7-102): warning X3557: loop only executes for 1 iteration(s), consider removing [loop]

**Comment by mrdoob** [comment]
So the warning probably comes from constructs like this in the shaders:

> ```
#define MAX_DIR_LIGHTS 1
#if MAX_DIR_LIGHTS > 0
for( int i = 0; i < MAX_DIR_LIGHTS; i++ ) { ...
```

Instead of parsing/filtering the output of `gl.getProgramInfoLog()`, how about parsing the shader code and removing the loop if `MAX_DIR_LIGHTS` is `1`? 😊

**Comment by WestLangley** [comment]
> Is it worth it to handle this special case without a loop in the shaders?

/ping @greggman

**Comment by bhouston** [comment]
I'd suggest ignoring this warning (e.g. x3557).  It isn't that important and I do not think it has a performance penalty.  Making the code messier is sort of annoying when the compiler should be smart enough to remove the loop if it is smart enough to realize it will only be executed one.

**Comment by greggman** [comment]
I don't see that warning on OSX so it's probably coming from D3D.

It seems like a bogus warning to me. It's perfectly fine to have 1 light. I'd leave it and not worry about it.

As for the fact that the second time the shader is used the warning is missing. Chrome should cache the warnings if it's going to cache the shaders otherwise it's not acting the same from the user's pov. Actually this is already filed.

https://code.google.com/p/chromium/issues/detail?id=251920

You should star it, comment, tweet, etc if you want it fixed

**Comment by WestLangley** [comment]
Thank you @greggman and @bhouston.
