### ISSUE TITLE
Internet Explorer: WebGLRenderer broken since r67

### ISSUE THREAD

**Issue by thuron** [mrdoob/three.js#4843]
After doing some tests I noticed the WebGLRenderer does not seem to work in Internet Explorer 11 with Three.js r67. I have verified this using the following jsfiddles:

WebGLRenderer using r66: http://jsfiddle.net/38q86/1/
WebGLRenderer using r67: http://jsfiddle.net/38q86/2/

Using r66 works fine (apart from the performance issues), but using r67 I'm getting a load of shader errors. This only occurs in Internet Explorer; chrome and FF work fine.

**Comment by Ars27** [comment]
Hey, maybe I didn't Understand something right, but how do i fix this bug now?

**Comment by makc** [comment]
Came from #3600 here - that stencil message is still a problem in IE11 with r76

**Comment by makc** [comment]
Oh right, may be #4088 I do have double-sided mesh
