### ISSUE TITLE
Showcase: Demo of new Ray.intersectSphere and Vector3.reflect() methods

### ISSUE THREAD

**Issue by erichlof** [mrdoob/three.js#4849]
Hi all,
Here is a simple demo showing the capabilites of the new Ray.intersectSphere(sphere) method and also using the Vector3.reflect(normal) method to correctly bounce the projectile off of the sphere.

The demo shows you can be inside a big sphere (or dome), or you could also be outside a smaller sphere and everything will work.

Press 'M' for mouseLook, then 'LMButton' to fire, 'SPACE' to apply thrusters

http://erichlof.github.io/AsteroidPatrol3D/RaySphereReflect.html

 and here's the source to see how to use these new helpful methods:
https://github.com/erichlof/AsteroidPatrol3D/blob/gh-pages/RaySphereReflect.html

Thanks three.js team for helping me get this function ready.  And thanks for merging this @mrdoob .  Three.js is the best! :)

**Comment by Mugen87** [comment]
Closing since showcases are better placed in the [three.js forum](https://discourse.threejs.org/). There is a category `Showcase` that can be used for particular cases like this.
