### ISSUE TITLE
Output of vertex shader  'vWorldPosition' not read by fragment shader

### ISSUE THREAD

**Issue by simplicitylab** [mrdoob/three.js#4854]
When I was experimenting with a simple bumpmap is saw the following warning popping up.

```
gl.getProgramInfoLog() WARNING: Output of vertex shader 'vWorldPosition' 
not read by fragment shader
```

As I assumed it was an error from my side I looked to the example for some guidance. But it seems that the warning also appearing on the example page http://threejs.org/examples/#webgl_materials_bumpmap. 

For the rest the script seems to run fine (also in my case) Maybe it is nothing but I just want to mention it.

Using Chrome 35.0.1916.114 on OS X

**Comment by tparisi** [comment]
@mrdoob is this still in a known and ingorable issue in r73? I'm seeing it there.

**Comment by WestLangley** [comment]
@tparisi I believe the `vWorldPosition` warning has been fixed in r.74dev.

**Comment by tparisi** [comment]
good to know thx
