### ISSUE TITLE
WebglRenderer bug

### ISSUE THREAD

**Issue by Wandalen** [mrdoob/three.js#4863]
for ( var o = 0, ol = scene.__webglObjects.length; o < ol; o ++ ) {

			var object = scene.__webglObjects[ o ].object;

			// TODO: Remove this hack (WebGLRenderer refactoring)

			if ( object.__webglInit === undefined ) {

				if ( object.__webglActive !== undefined ) {

					removeObject( object, scene );

				}

				this.addObject( object, scene );

			}

			updateObject( object );

		}

Iteration order must be reversed, otherwise after removing and adding new object, some array elements will stay unchanged, but other will be handled twice.

**Comment by dubejf** [comment]
This issue was reported against r67. The highlighted portion of the renderer, and the method for removing objects from the scene, has changed significantly since then. I assume it was fixed along the way.
