### ISSUE TITLE
Extend the PDB loader to support more than atoms and bonds (feature request)

### ISSUE THREAD

**Issue by benbro** [mrdoob/three.js#4866]
Example:
http://www.rcsb.org/pdb/explore/jmol.do?structureId=1BLU&bionumber=1

![1blu](https://cloud.githubusercontent.com/assets/75841/3125631/d45f535a-e78d-11e3-8622-3e4bf92dea2a.png)

Thanks

**Comment by Mugen87** [comment]
> and what data in a PDB file must be parsed in order to render such an image?

As far as I can see, this question was never answered. An enhancement of `PDBLoader` is only possible if you can specify what additional [fields](http://www.wwpdb.org/documentation/file-format-content/format33/v3.3.html) of the PDB should be parsed and how. 

As mentioned earlier by @WestLangley, the loader itself only populates a data structure. It's up to the application to decide how the visualization should look like.

Closing for now. We can reopen if there is a more concrete description.
