### ISSUE TITLE
OrthographicCamera far, near and object stacking

### ISSUE THREAD

**Issue by kswope** [mrdoob/three.js#4880]
In the example below I use an OrthographicCamera and stack a white plane and a black plane by setting position.z.  Its my hope and understanding that the positive z axis is in the direction of the viewer.  So position.z = 2 should stack on position.z=1, and in my example this works perfectly.  But only when the frustrum near plane is set to something like -100 and the far plane is set to something like 100, which seems backwards to me, if I'm right about the z axis directions.

http://jsbin.com/iWiCInO/9/edit

**Comment by WestLangley** [comment]
This can be closed.
