### ISSUE TITLE
Skewed perspective in Chrome on huge screens

### ISSUE THREAD

**Issue by mofog** [mrdoob/three.js#4881]
Hi.

We use Three.js to create some 3D content in Chrome spanning three Full HD screens. We noticed that once the window reaches "a certain" width, the perspective becomes skewed (cf. attachment). However, showing the same 3D scene at the same width in Firefox works just fine (cf. attachment).

I skimmed the issue list, but couldn't find any related reports. As I'm not a 3D expert, I might lack the correct technical terms.

Any help I is appreciated. I'd be happy to provide additional data.

![firefox](https://cloud.githubusercontent.com/assets/6026116/3171088/a71daa30-ebc1-11e3-85bd-587e4faf814c.png)
![chrome](https://cloud.githubusercontent.com/assets/6026116/3171089/a71e7f78-ebc1-11e3-8fdf-3a24052770b7.png)

**Comment by Mugen87** [comment]
This was actually a Chrome bug and should be fixed for @mofog case.

see https://bugs.chromium.org/p/chromium/issues/detail?id=445542
