### ISSUE TITLE
Proposed New OrthographicCamera API

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#4883]
The `PerspectiveCamera` API looks like this:

```
PerspectiveCamera( fov, aspect, near, far )
```

`fov` is the vertical field-of-view in degrees, `aspect` is the aspect ratio, and `near` and `far` are the distances to the near and far clip-planes, respectively.

I propose that the `OrthographicCamera` API be changed to:

```
OrthographicCamera( height, aspect, near, far )
```

`height` is the vertical height of the orthographic frustum in world units, and the remaining parameters are the same as those for the `PerspectiveCamera`.

An alternate API is:

```
OrthographicCamera( width, height, near, far )
```

Either of these API changes imply that the orthographic frustum is symmetric around the z-axis. I do not believe this is a limiting constraint, but I am open to being convinced otherwise.

**Comment by looeee** [comment]
@mrdoob @WestLangley it's been a couple of years since this was opened, is it still being considered?

**Comment by mrdoob** [comment]
Yep. I can't think of a way of doing this change in a robust way with no breakage though...

**Comment by WestLangley** [comment]
Also, the current API supports an asymmetric orthographic frustum, and the proposal here does not, so I am going to close this.
