### ISSUE TITLE
Export animation with new Maya exporter

### ISSUE THREAD

**Issue by jhclaura** [mrdoob/three.js#4901]
Hi! I've been searching for a week but failed to find any examples or tutorials about how to export animation from Maya with new Maya Exporter. What are the steps we should do in Maya to export skeletal animation, Morph Target, Vertex Cache animation and things like that etc? Should I choose both polygon and bones?

For example, http://threejs.org/examples/webgl_animation_skinning_morph.html
How can I export a animated knight like this from Maya to js file?

Really couldn't find any documentations anywhere... any help will be appreciated!!! Thx!

**Comment by gmiv** [comment]
Is there an update for the maya three.js export, supporting morph targets?

**Comment by almeidais** [comment]
I am facing a similar problem. I have not been able to export a .json file from Maya which I could test the blendshapes using XHRLoader and UCS. I tried both the exporter plugin and the python converter script from Collada to .JSON. Nothing has worked properly so far. I was only able to load the model using JSONLoader, but I could not try the blendshapes.

**Comment by donmccurdy** [comment]
I think recently the best bet for animated models made in Maya would be FBXLoader or GLTFLoader.

Resources:

- [Maya -> Blender -> glTF 2](https://www.donmccurdy.com/2017/06/27/exporting-gltf-2-0-from-maya-lt-2/)
- [FBX2glTF](https://github.com/facebookincubator/FBX2glTF)
