### ISSUE TITLE
Fast polygon triangulation (Seidel's Trapezoidation) - reasonably small

### ISSUE THREAD

**Issue by jahting** [mrdoob/three.js#4920]
Three.js at present includes a Shape/Text triangulation which was easy to implement but also needed several add-ons, eg. to decide between contours and holes and to remove those holes, and it had quite some issues concerning:
- holes in polygons ( #3386: Holes in contours causes triangulation failure (partial solution: #4337); #2919: Triangulation fails for simple shape )
- the sequence of contour and hole polygons ( #4357: toShapes: independence of shape and hole specification order, ref. #3386 )
- the winding order of contour and hole polygons ( #4626: toShapes: Bugfix; new optional parameter: noHoles; #4590: Text Triangulation Issues )
- and finally performance issues: ( #4594, first solution step #4623 )

It seems to work correctly by now but is quite slow if there are many vertices or holes.

Instead of trying to improve the present code further, I created a new project [PnlTri.js](https://github.com/jahting/pnltri.js): **Polygon Near-Linear Triangulation in JavaScript**
- implementation of Raimund Seidel's randomised polygon trapezoidation and triangulation,
- does not rely on polygon winding order and holes following on their contour,
- reasonably **fast**: A square with 25000 square holes (~100k vertices -> ~150k triangles) takes less than 3 seconds on my old Laptop (Core 2 Duo T7200, 2 GHz) with Firefox 30.0,
- quite **small**: adds about 10k to three.min.js or about 2k to the gziped file, and it should be possible to further simplify some functions surrounding triangulation in Three.js,
- tested with all _difficult_ data available to me in the Three.js examples and issues,
- rather robust: in the presence of incompatible input it should produce "wrong" output but not crash.

I also created a branch for [Three.js with PnlTri](https://github.com/jahting/three.js/tree/withPnltri), replacing the present mechanism.
So interested users of Three.js can test their data against it. More test data would be welcome.

The main **drawback** might be that this algorithm often produces rather long, slim triangles. I'm thinking about a post-processing step to improve on this in the future.
There is still some room to refactor PnlTri and reduce the code surrounding triangulation in Three.js.
The next major step for PnlTri will be to allow polygons with intersections which would also increase robustness further.

@mrdoob: Is it small enough for integration into Three.js, or should it be left for people to combine them on their own ?

**Comment by mourner** [comment]
@mrdoob FYI in case you're still considering a better triangulation algorithm. I wrote https://github.com/mapbox/earcut, ultimately the fastest and smallest (2.3k gzipped) JS triangulation library. It's very robust and scales well with shape complexity. Check it out!

**Comment by WestLangley** [comment]
@mourner #5959  : - )
