### ISSUE TITLE
Separate loading from parsing

### ISSUE THREAD

**Issue by willdady** [mrdoob/three.js#4922]
I think JSONLoader should have it's internal parser separated into it's own class. The reason I say this is because it's not always the case that someone wants to load their model this way. The JSON may be inlined into the HTML, bundled inside some larger JSON document etc.

My particular use-case is I want to use preload.js to load my assets. The current process is I have to instantiate a JSONLoader passing my already-loaded object to it's parse method to get back valid geometry. My point is JSONLoader (as well as the other model loaders) are currently performing two very different tasks which ideally should be treated as such. Naturally, if the parser is separated the loader class can still instantiate the parser internally as needed.

Thoughts?

**Comment by donmccurdy** [comment]
It’s possible pass arbitrary objects into `jsonLoader.parse()` now, so I think this can be closed: https://threejs.org/docs/#api/loaders/JSONLoader
