### ISSUE TITLE
Editor: Export directly to file

### ISSUE THREAD

**Issue by theo-armour** [mrdoob/three.js#4952]
Hi everybody

In the Three.js Editor, when you export geometry, objects, scenes etc, the data is currently sent as text to a new window.

An alternative would be to export the data directly to file. I have such an implementation working with a demo here:

http://jaanga.github.io/three.js/editor/

To operate: Add some objects, click any of the export options in the File menu, then the 'Save As' dialog should appear and you can save the data to a file of your choice.

This enhancement uses Eli Gray's filesaver.js which I have used quite extensively elsewhere and seems to work OK.

https://github.com/eligrey/FileSaver.js/

If this is considered a good idea then I will work on a pull request or it's only four lines of code and a file copy so perhaps somebody skillful at merging could do this much faster then me.

Theo

**Comment by mrdoob** [comment]
This landed in r70 (File/Publish) ^^

**Comment by theo-armour** [comment]
Yay!
