### ISSUE TITLE
Newer version(s) not rendering on Windows Phone 8.1

### ISSUE THREAD

**Issue by Gerhman** [mrdoob/three.js#4966]
R67 does not draw anything in the Windows Phone 8.1 browser even though the r57 that I accidentally stumbled upon here http://www.html5canvastutorials.com/three/html5-canvas-webgl-cylinder-with-three-js seems to work just fine. Unfortunately I have only started developing with three.js now and there does not seem to be an archive so I cannot test to see what the last working version was. I would appreciate it if someone could look in to this, anyone can get the Windows Phone SDK for free and the emulator runs the actual OS so it should be very trustworthy for testing something like this.

PS. I noticed that desktop IE 11 shows a bunch of gl shader compilation errors in its log even though it seems to render fine. Considering the core of IE 11 on WP 8.1 is almost exactly the same as the desktop one I am guessing that it is probably experiencing the same errors but just not dealing with them as well...

**Comment by dubejf** [comment]
There's been no news, let's assume that it was resolved along with the desktop version.
