### ISSUE TITLE
OBJMTLLoader: Empty mesh created sometimes

### ISSUE THREAD

**Issue by morsen** [mrdoob/three.js#4972]
The OBJ file that has prompted this issue was exported by the Assimp C++ library, and contained, in this order: vertex definitions, texcoord definitions, a "usemtl" statement, and then face definitions.

In this case, there were already vertex definitions when the first "usemtl" statement was encountered.

The way the code is written, when that "usemtl" statement is encountered, a mesh containing the vertices, but with zero faces, is created. The test for whether or not to create a mesh is determined by whether or not there are any vertices. However, it seems that the correct test is whether or not there are any faces.

In the OBJ loader, several meshes can and sometimes do share the same vertices array.

I propose that the test for whether to create a new mesh be changed from "is vertex count positive" to "is face count positive".

**Comment by mrdoob** [comment]
`OBJMTLLoader` has been removed in `r74`. #8085
