### ISSUE TITLE
OBJMTLLoader: Geometry.mergeVertices() call can break it

### ISSUE THREAD

**Issue by morsen** [mrdoob/three.js#4973]
In the OBJMTLLoader.js function `meshN()`, the call to `geometry.mergeVertices()` is problematic. Since many meshes can share the same set of vertices, it's possible that merging the vertices for a previous mesh will corrupt the vertex indices on faces that haven't been read yet.

I propose that the set of vertices be merged only once, either when the vertex set is reset to empty as a result of parsing a 'o' statement in the OBJ file, or else at the end of parsing before the function returns.

In order to do this, the function `Geometry.mergeVertices()` could be split into `createVertexMergeMap()` and `applyVertexMergeMap()`. The merge map would contain this data, which is currently private to `mergeVertices()`: `{ verticesMap: {}, unique: [], changes: [] }`.

Then, the OBJMTLoader code would call `createVertexMergeMap()` once, and then `applyVertexMergeMap()` on every Mesh that references that vertex set.

`createVertexMergeMap()` should probably be defined somewhere other than Geometry, since the only information that it needs in order to operate is the vertex array. Also, `precision` could be a second parameter to this function, and default to 4 if it's undefined.

`Geometry.mergeVertices()` would then be rewritten as:
```
mergeVertices: function() {
	this.applyVertexMergeMap( createVertexMergeMap( this.vertices ) );
}
```

**Comment by mrdoob** [comment]
`OBJMTLLoader` has been removed in `r74`. #8085
