### ISSUE TITLE
strange behavior with FF 30.0 and antialias turned off

### ISSUE THREAD

**Issue by GoschiWoschi** [mrdoob/three.js#4996]
I am experiencing a very strange issue in firefox (30.0) with WebGLRenderer and disabled antialiasing.

My setup is a really simple scene with just one white plane in the middle, moving its x-position by 1 every frame (any other animation will do the same).

The bug only occurs while the antialiasing option of the renderer is turned off AND the clearcolor-alpha value is either 0 or 1 (e.g. renderer.setClearColor(0x00ff00, 1)). If the clearcolor alpha value is anything else (e.g. 0.5) the issue doesnt occur.

1st screenshot: renderer.setClearColor(0xff0000, 0.5)
2nd screenshot : renderer.setClearColor(0xff0000, either 1 or 0)

both scenes had antialias turned off
screenshots where taken a few seconds into the animation

![screen1](https://cloud.githubusercontent.com/assets/6164462/3417083/50523b82-fe34-11e3-80d9-ef9158dff27e.png)
![screen2](https://cloud.githubusercontent.com/assets/6164462/3417084/5054e80a-fe34-11e3-80f1-2f66ce01a32f.png)

**Comment by Mugen87** [comment]
As long as this problem does not occur with a current FF (so over 20 versions later😉) this issue can be closed.
