### ISSUE TITLE
ColladaLoader - optional custom URLizer

### ISSUE THREAD

**Issue by JeramieH** [mrdoob/three.js#4998]
Being able to provide an optional callback function to customize the URLs being requested by ColladaLoader would be very appreciated.The function would be unique per ColladaLoader instance, and would create the URL parameter of the THREE.ImageUtils.loadTexture() call  around line 3483, and possibly the DAE around 109 (I know we can already provide the exact URL there, but it might be nice to be able to provide a general filename to ColladaLoader.load() and have it wrapped through the same URLizer as well).

**Comment by Mugen87** [comment]
#11259 should solves problem.
