### ISSUE TITLE
Collada importer breaks when bonelist and joints arrays don't match 

### ISSUE THREAD

**Issue by kumavis** [mrdoob/three.js#5017]
The data looks like this:

```
bonelist
/* =>
[
  name: "joint5"
  parent: -1
  ...
,
  name: null
  parent: "joint5"
  ...
]
*/

joints
/* =>
["joint0", "joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "joint7", "joint8", "joint9", "joint10", "joint11", "joint12"]
*/
bonelist.length
//=> 2
joints.length
//=> 13
```

note: this model was purchased, I don't know how it was exported.

The line that breaks [here](https://github.com/mrdoob/three.js/blob/a083e4442732f076e85446ca42e5f7a829b7d28b/examples/js/loaders/ColladaLoader.js#L697), b/c the `sortedBones` contains undefined elements

**Comment by Mugen87** [comment]
`ColladaLoader2` should solve this problem. It handles skeletal animation more robust than its predecessor.
