### ISSUE TITLE
Binary model format doesn't support vertex color

### ISSUE THREAD

**Issue by daoshengmu** [mrdoob/three.js#5045]
I find the binary model format doesn't define the vertex color data in the bin file. In my opinion, I think vertex color is often be used in the modeling pipeline. Do you plan to support it in the model format version 3.1? If we want to support it, we must fix the converters and BinaryLoader, and the binary format field would be modified, the binary models must be reconverted.

**Comment by donmccurdy** [comment]
BinaryLoader mentions that it loads models created with converter_obj_three_slim.py... does that still exist?

**Comment by Mugen87** [comment]
I don't think the comment is correct. It should be  `convert_obj_three.py`. There was an option (`-t`) that controlled the output of the script (ASCII vs. Binary). The entire Python code was replaced with a node script some time ago, see: 89cb329fec39cd7c570752b09352b70188cac89b

However, the node script is not able to produce a binary output for `BinaryLoader`. So i guess the binary format and the respective loader are somewhat deprecated...

**Comment by mrdoob** [comment]
Time to replace `BinaryLoader` with `GLTFLoader` 💪

**Comment by donmccurdy** [comment]
Closing in favor of https://github.com/mrdoob/three.js/issues/13651
