### ISSUE TITLE
Need to call _gl.enableVertexAttribArray in every frame

### ISSUE THREAD

**Issue by judax** [mrdoob/three.js#5053]
Hello,

I am integrating a personal rendering using WebGL with ThreeJS. The two pipelines are colliding right now and found out that I need ThreeJS to re-enable vertex attrib arrays for positions, normals, texture coordinates, etc. in every frame. I have added a simple modification to ThreeJS inside the renderBuffer function inside the WebGLRenderer:

```
...
		// vertices
		if ( !material.morphTargets && attributes.position >= 0 ) {
			if ( updateBuffers ) {
				_gl.bindBuffer( _gl.ARRAY_BUFFER, geometryGroup.__webglVertexBuffer );
				enableAttribute( attributes.position );

				// MY CODE BEGIN
				_gl.enableVertexAttribArray(attributes.position);
				// MY CODE END
				
				_gl.vertexAttribPointer( attributes.position, 3, _gl.FLOAT, false, 0, 0 );
			}
		} else {
...
```
And of course, the same applies for colors, normals, texture coords, etc.

I know, it is a crappy thing to do but I do not have control over the other rendering pipeline.

My question is: 

a) How can I instrument ThreeJS to force the attributes to be re-enabled in every frame with the least performance penalty possible?

b) Is there a way in webgl/threejs to know these attributes and re-enable them manually from outside the engines code (in the application inside the render loop before calling to render)?

Thank you very much!

**Comment by dubejf** [comment]
r71/r72 has introduced `WebGLState` which encapsulates the state of the gl context.

Calling renderer.resetGLState() before - or after - your custom rendering function should be sufficient to reset the state predictably (disabling attributes, etc).

This is what the LensFlares and Sprites plugins do to maintain their independence from the main rendering pass.
