### ISSUE TITLE
Vertex normals calculation in BufferGeometry

### ISSUE THREAD

**Issue by ibachar** [mrdoob/three.js#5059]
I think I've noticed two bugs with the calculation of vertex normals in BufferGeometry in r67.

1. The face normal is calculated and added to the vertices that belong to that face but shouldn't the face normal be normalized first? Without normalization, there is an implicit weighting on the face normals.
2. At the end of the function, shouldn't the line "this.normalsNeedUpdate = true;" be replaced with "this.attributes.normal.needsUpdate = true;"?

**Comment by WestLangley** [comment]
@mrdoob This fell through the cracks. What behavior would you prefer in (1) and (2)?

**Comment by WestLangley** [comment]
bump

**Comment by mrdoob** [comment]
1. I think both should compute area-weighted by default.
 2. Yep, both should set a flag 😊

**Comment by WestLangley** [comment]
Fixed.
