### ISSUE TITLE
SceneExporter // BoxGeometry Inconsistent

### ISSUE THREAD

**Issue by ty10r** [mrdoob/three.js#5067]
three.js/blob/master/src/extras/geometries/BoxGeometry.js:19

BoxGeometry never saves width, height, depth variables into "this".

three.js/blob/master/examples/js/exporters/SceneExporter.js:387 expects BoxGeometry to hold these properties.

I can't find direct references to the SceneExporter so I'm wondering if it's been dropped?

**Comment by dubejf** [comment]
Fixed by #6952.
