### ISSUE TITLE
SceneExporter // SceneLoader Inconsistant Parameters

### ISSUE THREAD

**Issue by ty10r** [mrdoob/three.js#5069]
Example:

SceneLoader.js:851

```
geometry = new THREE.CylinderGeometry( geoJSON.topRad, geoJSON.botRad, geoJSON.height, geoJSON.radSegs, geoJSON.heightSegs );
```

Uses parameters such as radSegs, instead of the objects actual member variable name:

```
radiusSegments
```

Other geometry loads in SceneLoader use the uniform member variable names.
**I am currently adding geometries to SceneExporter.js and SceneLoader.js**, I am curious of these two classes were meant to be compatible specifically with each other.

**I would like to use the uniform parameter names for import/export, but if changing the property names in SceneLoader breaks compatibility with other intended exporters, I won't.**

**Comment by Mugen87** [comment]
`SceneLoader` is removed from the library now.
