### ISSUE TITLE
render an SVG Map or a shape file using Three.js

### ISSUE THREAD

**Issue by kevalshah90** [mrdoob/three.js#5070]
Having trouble rendering a working 2D SVG Map in Three.js. There doesn't seem to be much support out there at the moment for this functionality. 

I have a shape file for U.S States, need to render the Map in 3D and display some Geo-Spatial Data. 

Came across few examples, but most of them seem to not work. If anyone know's of any concrete example or have worked on one and would like to give me directions, that would be greatly appreciated. 

Thanks.

**Comment by Mugen87** [comment]
As @WestLangley mentioned we have an example that illustrates the workflow.
