### ISSUE TITLE
textures with the backslash path is not loading the textures in OBJMTLLoder in firefox only

### ISSUE THREAD

**Issue by jothikannan** [mrdoob/three.js#5072]
am using OBJMTLLoder to load the models am having the models with the textures inside the directory so my mtl file is as below 

newmtl 15___Default
    Ns 33.0000
    Ni 1.5000
    d 1.0000
    Tr 0.0000
    Tf 1.0000 1.0000 1.0000 
    illum 2
    Ka 1.0000 1.0000 1.0000
    Kd 1.0000 1.0000 1.0000
    Ks 0.1710 0.1710 0.1710
    Ke 0.0000 0.0000 0.0000
    map_Ka maps\ed897c40.bmp
    map_Kd maps\ed897c40.bmp

here the maps is the directory and it have the `ed897c40.bmp` textures, after  load the model with the `OBJMTLLoder` it is working fine in the chrome, in the Firefox am getting  

`"NetworkError: 404 Not Found - http://localhost/3d-viewer/documents/mrdoob-three.js-d3cb4e7/examples/files/seaknight/maps%5C5b834470.bmp"`

is it is a bug or how i deal with this ??

**Comment by Mugen87** [comment]
I was not able to reproduce this issue with the latest `MTLLoader`.
