### ISSUE TITLE
SketchUp Web Viewer uses three.js

### ISSUE THREAD

**Issue by gwink** [mrdoob/three.js#5077]
Hi,
I just wanted to let you know that the SketchUp 3D Warehouse Web Viewer is build with three.js. It's a great library; thanks for making it available.

To see it in action go to https://3dwarehouse.sketchup.com/, select a model and activate the 3D view by clicking on the 3D-spin icon.

Cheers,
georges

**Comment by Elyx0** [comment]
Any updates?

**Comment by mrdoob** [comment]
@Elyx0 What about?
