### ISSUE TITLE
Safari drawImage() for Three.js webgl canvas

### ISSUE THREAD

**Issue by bwang29** [mrdoob/three.js#5115]
Drawing a webgl canvas created by three.js onto a regular 2d canvas work well for the latest Chrome and Firefox, but not for Safari:
2d_canvas.getContext("2d").drawImage three_js_webgl_canvas,0,0

However, 2d_canvas.getContext("2d").drawImage 2d_canvas,0,0 works fine on safari. I wonder if this has been an issue in previous three.js releases?

**Comment by patrickmatte** [comment]
Did you find a workaround for this?

**Comment by Mugen87** [comment]
Unable to reproduce with Safari 11.0.2. Looks like the problem has been fixed for a while now.

Update test file: http://jsfiddle.net/3t9Ly94L/8/
