### ISSUE TITLE
material.skinning=true cause shader compilation error on windows

### ISSUE THREAD

**Issue by nn4e** [mrdoob/three.js#5129]
2 examples here:
http://test.prowebmake.ru/skinning/67.html
http://test.prowebmake.ru/skinning/68.html

first use r67 and work fine on windows and linux
the second use r68, work on linux but on windows it says "Shader couldn't compile"

tested on Windows 7, different cards nvidia and AMD, google-chrome and firefox

**Comment by aeslinger0** [comment]
I have this same problem. [This link](https://bocoup.com/weblog/counting-uniforms-in-webgl/) helped me understand the problem, but, using his debugging code, it looks like I only have a total of 15 uniforms (unless I counted wrong, I had to hack three.js to get the program exposed to that debugging function. 

Is there any update on this?
