### ISSUE TITLE
MTLLoader: Add support for TGA textures

### ISSUE THREAD

**Issue by jothikannan** [mrdoob/three.js#5141]
am loading a model with the OBJMTLLoder. and am using .tga materials, the model is loaded as black.

three.js doesn't support .tga materials, what are the materials is supported by the three.js., can anyone tell me??

**Comment by saopang** [comment]
is supported now？

**Comment by Mugen87** [comment]
You should be able to load TGA textures with `MTLLoader` like so:
```js
const manager = new THREE.LoadingManager();
manager.addHandler( /\.tga$/i, new THREE.TGALoader() );
const loader = new THREE.MTLLoader( manager );

// now load your MTL/OBJ files
```

**Comment by WestLangley** [comment]
>manager.addHandler( /\.tga$/i, new THREE.TGALoader() );

@Mugen87 I believe there is currently only one example of using `.addHandler`. Perhaps the docs can be made more descriptive -- or we can add an example of the use case you mentioned.

... or add the above line to the existing example and comment it out.

**Comment by Mugen87** [comment]
> I believe there is currently only one example of using .addHandler.

That's correct. It's the OBJ/MTL example which adds `DDSLoader` in this way.

> Perhaps the docs can be made more descriptive

TBH, I think the description is already quite good. Do you have any idea how to improve it?

https://raw.githack.com/mrdoob/three.js/dev/docs/index.html#api/en/loaders/managers/LoadingManager.addHandler

**Comment by Mugen87** [comment]
> ... or add the above line to the existing example and comment it out.

Done!

**Comment by WestLangley** [comment]
>Do you have any idea how to improve it?

Not really, but this line seems to be a bit contradictory:

>Note: The following methods are designed to be called internally by loaders. You shouldn't call them directly.

**Comment by Mugen87** [comment]
Oh, I was not aware of this note! Let's reorganize this doc page.

**Comment by WestLangley** [comment]
>Do you have any idea how to improve it?

    Registers a loader with the given regular expression. 

Without a pattern to follow, I would have no idea what that means or what the expression should look like.

If it is hard to explain, then a code snippet can be used... or a reference to an example, if we want to go that route.
