### ISSUE TITLE
Model viewer example

### ISSUE THREAD

**Issue by benbro** [mrdoob/three.js#5149]
This is a request to add a model viewer example.
I think it's a very common need to display a model, pan, rotate and zoom.

Features:
- Load models of different formats with plugable loaders. It can help unify the loaders API if needed.
- Auto zoom the model to a reasonable initial value. Allow zoom in/out.
- Use TrackballControls to rotate the model.
- Allow pan.

This example can be used as a base for many other examples.
For example, for showing different loaders and controls.

Thigiview is very nice but it uses an old version of three.js
n0r.org/thingiview.js/examples/client_side_ajax.html
https://github.com/tbuser/thingiview.js

Thanks

**Comment by jsidd** [comment]
Hi everyone,
I am not sure if this feature request would still be useful, but I started working on this and submitted a PR for my initial version. 
Thank you, 
Ben

**Comment by Mugen87** [comment]
The [editor](https://threejs.org/editor/) and projects like [gltf-viewer](https://gltf-viewer.donmccurdy.com/) should be sufficient resources for model viewer apps.

Making a separate example means we only duplicate code which [already exists in the editor](https://github.com/mrdoob/three.js/pull/10216#issuecomment-263194615). Hence, I vote to close the issue and the respective PR #10216.

**Comment by mrdoob** [comment]
Agreed 👍
