### ISSUE TITLE
Cloning Material to Target

### ISSUE THREAD

**Issue by datmorrison** [mrdoob/three.js#5152]
It would be great if derived Materials (e.g. Phong, Normal, etc.) allowed the user to pass an existing instance of a material to the Clone() method, as you can with base materials.

I think this would just require (Phong for example):

```
if ( material === undefined ) material = new THREE.MeshPhongMaterial();
```

**Comment by donmccurdy** [comment]
Closing as obsolete, derived materials have `.copy()` methods now.
