### ISSUE TITLE
BoundingBoxHelper doesn't like odd geometries

### ISSUE THREAD

**Issue by Herst** [mrdoob/three.js#5160]
Message in error console about every 16ms:

```
Matrix3.getInverse(): can't invert matrix, determinant is 0 
```

Testcase: http://jsfiddle.net/Herst/8Daqs/

**Comment by killroy42** [comment]
Getting these sporadically in a scene containing only a rotating (100x100x100) box and some arrow helpers. What else can cause this?

**Comment by killroy42** [comment]
Can we throw an exception there? It usually hits with 10s of 1000s of errors in the console quickly freezing up DevTools. I'm not using BoundingBox, which means it's not always easy to control when this error might be caused. Or perhaps have some debug flags to disable throwing those kinds of errors, etc.

**Comment by mrdoob** [comment]
> Can we throw an exception there?

As long as it doesn't affect performance, sounds good to me. But I think V8 can't optimise functions with throws on it.

**Comment by killroy42** [comment]
I think it's related to arrow head size vs arrow length. So having some checks in the ArrowHelper to scale the head down for short arrows might be much better.

**Comment by mrdoob** [comment]
Yeah, adding a check there would work.

**Comment by WestLangley** [comment]
@killroy42 I think what you need to do is debug your program and determine what you are doing to cause the bounding box of your geometry to have volume equal to zero.

**Comment by killroy42** [comment]
@WestLangely If you create an ArrowHelper 5 units long with a head size of 6, you will also get that error (every frame). If it generates a small bounding box internally I am not sure, but is doubtful.

**Comment by WestLangley** [comment]
@killroy42 How is your issue related to the topic of this thread?

**Comment by killroy42** [comment]
The first comment describes the exact symptom. It is likely they are related. Just trying to help.

**Comment by WestLangley** [comment]
@killroy42 `ArrowHelper` will throw errors if `headLength` is not strictly shorter than the arrow `length`. Ensure that requirement in your application -- or don't specify a head length and it will be set automatically -- and see if your problem goes away.

**Comment by Mugen87** [comment]
Closing since `BoundingBoxHelper` is deprecated. The error does not occur with `BoxHelper`.

http://jsfiddle.net/8Daqs/2/
