### ISSUE TITLE
glTF loader is not compatible with recent collada2gltf converter

### ISSUE THREAD

**Issue by benbro** [mrdoob/three.js#5161]
Tested with
glTF v0.8
three.js r68

Last glTF release that works with three.js master
glTF v0.6

1. The parser check for description.path but the new converter creates a json file with "uri" field instead of "path".
https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/gltf/glTF-parser.js#L113

2. The main model file has .gltf extension instead of .json
https://github.com/mrdoob/three.js/blob/dev/examples/models/gltf/duck/duck.json

3. After fixing the previous issue I'm getting an error I don't know how to fix:
```
Error: invalid arguments
return new Uint16Array(resource, 0, ctx.indices.count);
```
https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/gltf/glTFLoader.js#L143

Thanks

**Comment by vvoovv** [comment]
@tparisi
Are there chances to load the duck in the near future?

**Comment by tparisi** [comment]
Hi all

I actually have things in OK shape except skins are broken. It's all in the glTF repo on Khronos right now. I will migrate it into the Three.js tree and do a PR in the next few days :-)

**Comment by vvoovv** [comment]
Just tried the loader from the Khronos repo. It doesn't work with three.js-r69 and above. However it does work with three.js-r65

Please check it against the latest version of three.js

**Comment by vvoovv** [comment]
Also the loader fails if everything (including textures) is built into a single gltf file.
Let me know if you need my gltf file with built-in textures.

**Comment by tparisi** [comment]
Got it thanks for the heads up! Please send test files

**Comment by vvoovv** [comment]
Here is the test gltf file (6 Mb) with built-in textures and shaders:
https://www.dropbox.com/s/y0fwmp2r1aycxat/building.gltf?dl=0

**Comment by foobarbecue** [comment]
What's the status on this? Does the three.js glTF loader work with glTF 1.0? When I tried it I got "No EntryID provided, cannot store"

**Comment by foobarbecue** [comment]
I see https://github.com/mrdoob/three.js/pull/8316 and https://github.com/KhronosGroup/glTF/issues/463 . Presumably this issue should be closed.

**Comment by olabrahammar** [comment]
I still get the "No EntryID provided, cannot store" error that foobarbecue mentions. On R76 when i try to load a compressed/binary .gltf made with the very latest collada2gltf.

Data file created with c:\> collada2gltf.exe -f inpt.dae -c Open3DGC -m binary -e -o output

if i dont use the compression parameter (-c Open3DGC) then the loader works glTF-parser.js (line232)
Tracing the code i get that the _rootDescription.buffers contains a single object with en empty string "" for a name (which is later used as entryID). Child objects under all other types (images, meshes, materials and so on) they all have names and thus can be registered by setEntry(..  in glTFLoader.js

ping @tparisi   I'm not sure what to do about this one!
I still get the "No EntryID provided, cannot store" error that foobarbecue mentions. On R76 when i try to load a compressed/binary .gltf made with the very latest collada2gltf.

Data file created with c:\> collada2gltf.exe -f inpt.dae -c Open3DGC -m binary -e -o output

if i dont use the compression parameter (-c Open3DGC) then the loader works glTF-parser.js (line232)
Tracing the code i get that the _rootDescription.buffers contains a single object with en empty string "" for a name (which is later used as entryID). Child objects under all other types (images, meshes, materials and so on) they all have names and thus can be registered by setEntry(..  in glTFLoader.js

ping @tparisi   I'm not sure what to do about this one!

**Comment by windofred** [comment]
I want to use collada2gltf converters produce *.json, *.bin, *.glsl files. I'm getting files like *.gltf, *.bin, *.glsl and so on, but no json... why?

**Comment by selim-bekkar-sb** [comment]
@windofred .gltf is the json file. 
![gltf] (https://github.com/KhronosGroup/glTF/blob/master/specification/figures/files.png)

You can get more information [in glTF specification](https://github.com/KhronosGroup/glTF/blob/master/specification/README.md)

**Comment by windofred** [comment]
@selim-bekkar-sb I am reading a book--《Programming 3D Applications with HTML5 and WebGL》, it involve a Vizi framework, all the examples load the *.json file instead of *.gltf file. why? But when I load *.gltf, it doesn't any loading result... and the collada2gltf converters only produce *.gltf, *.bin, *.glsl files and so on...What should I do?

**Comment by windofred** [comment]
![picture](https://cloud.githubusercontent.com/assets/16623623/17582647/6c3b7570-5fdf-11e6-8111-9a79f9e447c6.png) how to produce this files format?

**Comment by antont** [comment]
the converter creates the glsl files when it makes also the .bin and the json for .gltf (was .json earlier, and still is a json file, just with that name to tell that it's gltf .. afaik can be a bundle too (zip with those files in it)

**Comment by windofred** [comment]
how to convert *.gltf file to *.json file?

**Comment by K1ll3rF0x** [comment]
@windofred The .gltf file is already in json format. Just change the file extension to .json if required.
PS. Three.js github is not the correct place for asking help. You should use stackoverflow instead :)

**Comment by windofred** [comment]
I have used the method(change the file extension to .json) as you said, but it failed!

**Comment by tparisi** [comment]
@windofred that book was published a few year ago, and based on very early glTF specifications. The Vizi code only works with older glTF; the framework hasn't been updated for a few years. For your glTF work you would be much better off using the frameworks and tools listed on the main page of this repo https://github.com/KhronosGroup/glTF
