### ISSUE TITLE
Possible improvement for zooming

### ISSUE THREAD

**Issue by tonnot** [mrdoob/three.js#5169]
I think I have an improvement for orbitcontrols (and I suposse it can be applied to other controls)

You can see this lines:

``` javascript
offset.copy( position ).sub( this.target );
```

and

``` javascript
var radius = offset.length() * scale;
position.copy( this.target ).add( offset );
this.object.lookAt( this.target );
```

The problem is that target is not modified. 
If you  play with mouse wheel (zoom + / zoom - ) you can see differences betwen zooms.
(because radius is not the distance between position & target, is greater or lesser)

I have applied this:

``` javascript
var dsp =  offset.length()*(scale -1);  
var desp= new THREE.Vector3();
desp.x = dsp * Math.sin( phi ) * Math.sin( theta );
desp.y = dsp * Math.cos( phi );
desp.z = dsp * Math.sin( phi ) * Math.cos( theta );
this.target.add(desp); // <<<<<<  target updated
```

and the wheel actions are now right.

I hope this was useful.

(sorry I dont know how to format the code...)

**Comment by Mugen87** [comment]
Closing. I also see no benefit of this proposal.
