### ISSUE TITLE
When THREE.js will support "WEBGL_draw_buffers"?

### ISSUE THREAD

**Issue by ghost** [mrdoob/three.js#5179]
This webgl extension very need for my path tracer, deferred lighting, etc.

**Comment by tsone** [comment]
I've been thinking about this also. I'll hijack this, and present my API proposals :)

This is difficult as we need to maintain backwards compatibility for `WebGLRenderTarget`. Particularly the material `map` parameters and uniform `type: 't'` binding need to be maintained. It's doable but just _what would be a good way?_

__Option 1__

Create a factory method `addExtraColorTexture()` to `WebGLRenderTarget` for creating the textures for us. It could return `WebGLRenderTexture` objects which could then be used like any 2D texture before. It would also receive common texture parameters as input -- just like `WebGLRenderTarget`.

Here's example how this could be used for a deferred rendertarget:

```
var deferredRT = new THREE.WebGLRenderTarget( width, height, {
    format: THREE.RGBAFormat,
    type: THREE.FloatType,
    stencilBuffer: false
} );

// To maintain backwards compatibility, first texture can be used like before.
var normalDepthTex = deferredRT;

var albedoRoughnessTex = deferredRT.addExtraColorTexture( {
    format: THREE.RGBAFormat,
    type: THREE.UnsignedByteType
} );

var intensityOcclusionTex = rtDeferred.addExtraColorTexture( {
    format: THREE.RGBFormat,
    type: THREE.FloatType
} );
```

(Note the different texture formats and types -- this is valid and should be allowed.)

Major benefit in this option is that ownership of the rendertarget textures is maintained by render target, as we're just requesting it to create new textures for us. This option would be also probably quite easy to implement. Drawback is that the API is bit different from other code in three.js as there are not many factory methods.

__Option 2__

(This is a bit similar to implemenation in #5402.) In this one the user creates `WebGLRenderTexture` objects separately and then passes these to the constructor of `WebGLRenderTarget`. And as we can have multiple textures, we need to pass an array. Say, the option for this would be `extraColorTextures`.

Here's the previous example, but with option 2:
```
var albedoRoughnessTex = new THREE.WebGLRenderTexture( {
    format: THREE.RGBAFormat,
    type: THREE.UnsignedByteType
} );

var intensityOcclusionTex = new THREE.WebGLRenderTexture( {
    format: THREE.RGBFormat,
    type: THREE.FloatType
} );

var deferredRT = new THREE.WebGLRenderTarget( width, height, {
    format: THREE.RGBAFormat,
    type: THREE.FloatType,
    extraColorTextures: [ albedoRoughnessTex, intensityOcclusionTex ],
    stencilBuffer: false
} );

// Again, first texture can be used just like before.
var normalDepthTex = deferredRT;
```
Here it would seem that `WebGLRenderTexture` can be shared with multiple render targets. This would be great, but in practice it's harder to implement as we need to manage `WebGLRenderTexture` as a new resource -- as it's then separate from `WebGLRenderTarget`. To cut corners, we could disallow ths sharing, but then there's not much benefit anymore compared to option 1.

Please comment when you have time.

**Comment by tsone** [comment]
To be more specific, I'm proposing above a method to enable `WebGLRenderTarget` to have multiple color attachment textures. I'm not proposing anything related to materials etc.

**Comment by tsone** [comment]
__Option 3__

Would introduce an `WebGLRenderTarget.extraColorTextures` array completely managed by the render target object. The textures in this array could be referred to and bound like normal, ex. `renderTarget.extraColortextures[0]`. The `WebGLRenderTarget` constructor would then receive the parameters  to create these textures in `extraColorTextureParams`. For this we could introduce a new `TextureParams` class.

Here's what the above example would look with option 3:
```
var albedoRoughnessParams = new THREE.TextureParams( {
    format: THREE.RGBAFormat,
    type: THREE.UnsignedByteType
} );

var intensityOcclusionParams = new THREE.TextureParams( {
    format: THREE.RGBFormat,
    type: THREE.FloatType
} );

var deferredRT = new THREE.WebGLRenderTarget( width, height, {
    format: THREE.RGBAFormat,
    type: THREE.FloatType,
    extraColorTextureParams: [ albedoRoughnessParams, intensityOcclusionParams ],
    stencilBuffer: false
} );

// Then we can access the textures like this:
var normalDepthTex = deferredRT;
var albedoRoughnessTex = deferredRT.extraColorTextures[ 0 ];
var intensityOcclusionParams = deferredRT.extraColorTextures[ 1 ];
```

Benefit is that all is done in the constructor and the ownership of textures is clear. It's also clear from this API that render target handles the textures internally. The constructor is however quite complicated. This could be even easier to implement than option 1.

**Comment by tsone** [comment]
I personally would opt for __option 3__ as it seems to be least work :stuck_out_tongue_closed_eyes:

**Comment by mrdoob** [comment]
How about just calling it `THREE.MultipleRenderTarget`? ;)

**Comment by tsone** [comment]
Good idea. That would be __option 4__. Benefit would be that `WebGLMultiRenderTarget` doesn't need to be backwards compatible. Drawback is that then both classes must be maintained. Also there is possibly depth texture support coming later, so I think it would be better to stick to the same class at least for now.

I already wrote one version of `setRenderTarget()` which supports multiple color textures, and noticed the code for single and multiple is mostly the same -- except for a loop for the extra textures and setting draw buffers.

**Comment by tsone** [comment]
I'm implementing __option 3__ now.

BTW. This could be used to speed up `WebGLDeferredRenderer` found in the examples by combining some of the passes (at least normal-depth and the color pass). Do you think it's okay to make changes to `WebGLDeferredRenderer`?

**Comment by mrdoob** [comment]
> Do you think it's okay to make changes to `WebGLDeferredRenderer`?

Yep!
