### ISSUE TITLE
Use renderDepth on material level

### ISSUE THREAD

**Issue by shi-314** [mrdoob/three.js#5189]
Since it is possible to set multiple materials for a single object it would be useful to use the `renderDepth` attribute for these materials. Otherwise it is not possible to fix rendering order issues when you use alpha maps for the materials.

As @mrdoob already mentioned the multi-material object is seperated into single material objects internally so we could use the `renderDepth` attribute there.

**Comment by fallenoak** [comment]
I'm currently in a situation I believe could benefit from this. I have a single BufferGeometry that has multiple materials (in a ```MultiMaterial```) covering the same faces. The materials are transparent, and must be rendered in a specific order. It would be handy if ```reversePainterSortStable``` would allow me to define and sort by a ```renderOrder``` property on the material.

My current workaround is to use multiple meshes (1 per material), and define a ```renderOrder``` on them, but I dislike the amount of overhead of the extra matrix multiplications that result from this. It seems like it'd be more optimal if I could use just one object, and control ```renderOrder``` on the material.

I'd be happy to craft a PR if someone would weigh in on this. Thanks!

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/issues/16060#issuecomment-522933870
