### ISSUE TITLE
projector.pickingRay(vector, camera) modifies input vector

### ISSUE THREAD

**Issue by marko-knoebl** [mrdoob/three.js#5214]
This took me quite some time to figure out because the behavior is surprising in my eyes:

If I call projector.pickingRay(vector, camera) the function returns a Raycaster object (as expected), but it also modifies the input argument "vector" which I found quite strange.
I think the proper solution for this issue would be not to modify the input vector (make a copy at the beginning of the algorithm and work with that). If (for whatever reason) this is not an appropriate solution, the behavior should at least be documented.

I'd be willing to help with both changing the behavior and improving documentation.

**Comment by dubejf** [comment]
`Projector.pickingRay` is now `Raycaster.setFromCamera` and doesn't mutate its inputs.
