### ISSUE TITLE
Allow for multiple sizes and and opacities for PointCloudMaterial

### ISSUE THREAD

**Issue by jamesmfriedman** [mrdoob/three.js#5231]
The ability to set vertexColors on the PointCloudMaterial is nice, and it would be great if size and opacity were handled the same.

The sizes and opacities could be stored in an array on the geometry like color is now, and the properties vertexOpacities and vertexSizes could be added to PointCloudMaterial or just Material.

My guess is this wouldn't be too hard, calculations are already being made for sizeAttenuation in the shader.

This request stems from me not wanting to write custom shaders and that PointCloudMaterial is pretty close to fully featured.

Thanks!

**Comment by WestLangley** [comment]
This can be implemented with a `ShaderMaterial`.
