### ISSUE TITLE
Rendering phong material after basic material on the same geometry causes webgl error.

### ISSUE THREAD

**Issue by wwwtyro** [mrdoob/three.js#5242]
Same geometry, different meshes.

I have a simple example here: http://wwwtyro.github.io/tests/phong-after-basic

Screenshot:

![screenshot from 2014-08-27 18 05 45](https://cloud.githubusercontent.com/assets/929443/4068971/c894d62e-2e3e-11e4-832f-587725c68a71.png)

There should be a phong-shaded sphere on the right.

The meat of it is:

``` javascript
var material1 = new THREE.MeshBasicMaterial();
var material2 = new THREE.MeshPhongMaterial();

var sphere = new THREE.IcosahedronGeometry(1, 3);

var mesh1 = new THREE.Mesh(sphere, material1);
var mesh2 = new THREE.Mesh(sphere, material2);

// Uncomment the following two lines to get rid of the error. (swaps materials)
// var mesh1 = new THREE.Mesh(sphere, material2);
// var mesh2 = new THREE.Mesh(sphere, material1);

scene.add(mesh1);
scene.add(mesh2);

renderer.render(scene, camera);
```

Results in the following error:

```
[.WebGLRenderingContext]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 1 
```

Swapping the order of the materials or using two geometries makes the issue go away.

Thanks for reading. :)

**Comment by Mugen87** [comment]
Indeed, this issue is solved see https://jsfiddle.net/f2Lommf5/1031/
