### ISSUE TITLE
simpler Projector.unprojectVector() for mouse picking?

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#5263]
Hi,

I stumbled upon [this](http://stackoverflow.com/questions/11036106/three-js-projector-and-ray-objects) after scratching my head around why we subtract camera pos from the unprojected vector if we are only looking for the direction.

Maybe this method would make more sense if it was called **unprojectPoint()**. 

If we are looking for just the direction, how about something like this?

```
unprojectDirection = (function(){
    var deg2radHalf = Math.PI/360;
    var tang = 0;
    return function ( vector, camera ) {
        tang = Math.tan(camera.fov * deg2radHalf);
        vector.x*=tang*camera.aspect; 
        vector.y*=tang; 
        vector.z = -1;
        return vector.transformDirection(camera.matrixWorld);
    };
 })();
```

it could also just take a vec2 construct so one needs only to be instructed to normalize the window into -1 1
it should also be faster for the ray shooting

i hope im not reinventing the wheel here?

**Comment by mrdoob** [comment]
Can we close this @pailhead?

**Comment by pailhead** [comment]
Oh yeah, I think this is too old
