### ISSUE TITLE
Shape3 for support of shapes defined by Vector3

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#5265]
Please consider this as an idea for future enhancement of your awesome Three.js

I am working on translating geometries from a 3D model file to ThreeJS. I ran into a problem because I have shapes described by curves and holes in 3D. I need to cut the hole from the shape and triangulate the result in order to get the right meshes. Right now the THREE.Shape utils only allow this kind of functionality in 2D.
Right now I will solve this by translating my curves and holes to 2D and later applying a Matrix to the resulting geometry to get the desired 3D result, but I think it would be great if the 3D support for this kind of functionality would be implemented.

**Comment by WestLangley** [comment]
>So to paraphrase, you are requesting support for extrusion from a shape embedded in an arbitrary 3D plane

That is not likely to be supported.
