### ISSUE TITLE
WebGLRenderer that plays nice with other renderers

### ISSUE THREAD

**Issue by joeedh** [mrdoob/three.js#5278]
Hi.  I've been modifying WebGLRenderer to play nice with other code that uses the GPU.  Does anyone want it?  Is it better as a separate renderer, or should it be a different mode within WebGLRenderer?

**Comment by dubejf** [comment]
r71/r72 has introduced `WebGLState` which encapsulates the state of the gl context.

Calling renderer.resetGLState() before - or after - your custom rendering function should be sufficient to reset the state predictably (disabling attributes, etc).

This is what the LensFlares and Sprites plugins do to maintain their independence from the main rendering pass.
