### ISSUE TITLE
How can we better allow for user-defined types that subclass Object3D? 

### ISSUE THREAD

**Issue by dmtaub** [mrdoob/three.js#5284]
It was difficult for me to subclass Object3D and use that subclass as the base type throughout the application while maintaining the platform's functionality. For example, all types of saving and loading break without forking each instance in the code. I can imagine some serialization hacks using userData, but I'd love to work on some handles to further enable subclassing high level objects.

Right now, the two places I can think of where we would want to plug this in are in the serialization and deserialization routines: 

https://github.com/mrdoob/three.js/blob/dev/src/core/Object3D.js#L562
https://github.com/mrdoob/three.js/blob/dev/src/loaders/ObjectLoader.js#L220

In the absence of requiring Object3D and subclasses to implement "toJSON" and "parse" (which may be a good idea anyway, but does not necessarily solve the general case), we could also explore creating an approved location for user-defined types. This might be a hash from classname to an object with all the functions necessary to fill out functionality available in CORE. 

What are the other barriers to a user-defined Object3D subclass that is used in place of Object3D throughout the scene graph and the rest of the platform?

**Comment by donmccurdy** [comment]
This can be merged with https://github.com/mrdoob/three.js/issues/11266, I think.
