### ISSUE TITLE
WebGLRenderer is not working in chrome only.

### ISSUE THREAD

**Issue by SammanitaP** [mrdoob/three.js#5285]
If I change the renderer to CanvasRenderer() then it is working.  I am using revision 68 of three.js and my chrome is upto date. Can any one please suggest why WebGLRenderer is not working for chrome, as it is working for all other browser.

**Comment by schroef** [comment]
I noticed this is not working on a Macbook Pro 2011, though it has latest version of Chrome. Safari works just fine. Is there some other hidden setting Chrome has which check capability of system

**Comment by schroef** [comment]
Im using osx 10.13.4 chrome is Version 65.0.3325.181 (Official Build) (64-bit). Seems like chrome issue or not?

**Comment by mrdoob** [comment]
Definitely a Chrome issue. Please report [here](https://bugs.chromium.org/p/chromium/issues/list).

**Comment by schroef** [comment]
Yep, i got a link and checked chrome://flags there where some options off there. After enabling 2 settings its working.

![screen shot 2018-04-20 at 3 27 36 am](https://user-images.githubusercontent.com/6923008/39036211-ce8cb5e4-444a-11e8-96e4-d612ce90eb15.png)
