### ISSUE TITLE
Add support to PVRTC texture (iOS)

### ISSUE THREAD

**Issue by plepers** [mrdoob/three.js#5332]
Hi guys,

iOS8 is out and enable *WEBGL_compressed_texture_pvrtc* extension. Since video memory is precious, especially on mobile, it could be nice to support PVR file as CompressedTexture input.

I'd already made a 'quick and dirty' implementation in my fork, and i'm ok to work on a clean one. 
The main question is about API. For now, ImageUtils has a method *loadCompressedTexture* which load DDS files only. Here some possibilities:

 - add a mandatory *format* argument [ "dds" | "pvr" ], to explicitly tell which parser to use.
 - same as above, but *format* is optional or default to "auto", then guess format from file extension or file headers.
 - deprecate *loadCompressedTexture*, and add *loadDDS* & *loadPVR*
 - ...

the current impl:
https://github.com/plepers/three.js/blob/marl/src/extras/ImageUtils.js#L540

I tested it with pvr compressed with texturetool (https://developer.apple.com/library/ios/documentation/3ddrawing/conceptual/opengles_programmingguide/TextureTool/TextureTool.html)

++
Pierre

**Comment by dubejf** [comment]
This has been implemented by #5337.
