### ISSUE TITLE
problem with loadAjaxJSON maybe bug.

### ISSUE THREAD

**Issue by czupakabra** [mrdoob/three.js#5334]
Hi! I show the proble on example because eng is not the best option
this is the loadModel function and its working.
```
this.loadModel = function()
	{	
		this.loader = new THREE.JSONLoader(true);
		this.loader.load(this.pathToFile, this.createMesh.bind(this)); 
		this.loader.onLoadComplete = this.createMeshComplete.bind(this);
	}
```
now i change the load method to loadAjaxJSON because i watn the callbackProgress
```
this.loadModel = function()
	{	
		this.loader = new THREE.JSONLoader(true);
		this.loader.loadAjaxJSON(this.loader, this.pathToFile, this.pathToFile, this.createMesh.bind(this), false, function( progress, result ) { console.log((progress.loaded / progress.total * 100).toFixed());}); 
		this.loader.onLoadComplete = this.createMeshComplete.bind(this);
	}
```

and the i have a problem that  callback is not a function

in the load method code we can see that this methou using loadAjaxJSON method and i have no problem with callback, what i use loadAjaxJSON manualy then is the problem

and when i edit the load method: 
from this
```
THREE.JSONLoader.prototype.load = function ( url, callback, texturePath)
```
to this
```
THREE.JSONLoader.prototype.load = function ( url, callback, texturePath, callbackProgress)
```

a change the last line of function 
from this
```
this.loadAjaxJSON( this, url, callback, texturePath );
```
 to this
```
this.loadAjaxJSON( this, url, callback, texturePath, callbackProgress);
```

the its will be working fine
this is bug or I doing something wrong?? stackoverflow no helping

**Comment by dubejf** [comment]
Related to this PR #5462. Should be fixed now.
