### ISSUE TITLE
Update DeviceOrientationController to include manual drag+zoom overrides + event bubbling + consistent FOV support?

### ISSUE THREAD

**Issue by richtr** [mrdoob/three.js#5338]
I've been trying to figure out how I could add the features of the [threeVR `DeviceOrientationController`](https://github.com/richtr/threeVR/blob/master/js/DeviceOrientationController.js) to [`THREE.DeviceOrientationController`](https://github.com/mrdoob/three.js/blob/master/examples/js/controls/DeviceOrientationControls.js). Having tried numerous times to simplify my library I think it makes the most sense to replace the current [`THREE.DeviceOrientationController`](https://github.com/mrdoob/three.js/blob/master/examples/js/controls/DeviceOrientationControls.js) with a compatible version of the [threeVR `DeviceOrientationController`](https://github.com/richtr/threeVR/blob/master/js/DeviceOrientationController.js) as is.

To summarize, the additions to `THREE.DeviceOrientationController` this will bring include:
- Manual drag override controls for mouse/touch + disable flag + interaction start/end event bubbling (`rotatestart`, `rotateend`)
- Manual zoom override controls for touch + disable flag + interaction start/end event bubbling (`zoomstart`, `zoomend`)
- General manual user override interaction start/end event bubbling (`userinteractionstart`, `userinteractionend`)
- General Screen Orientation Event bubbling (`orientationchange`)
- Additional Device Orientation Event bubbling (`compassneedscalibration`)
- Flag to enable rotation matrix-based deviceorientation computation (we use quaternions by default) 
- Constrain FOV when screen switches from portrait<->landscape. i.e. always make scene objects appear the same size whenever screen orientation changes occur.
- Default to using a 'heads-up' orientation for the camera/target object (in-line with the horizon) if/when deviceorientation is not supported on the current device. This is useful on e.g. Desktop where deviceorientation may not be supported or only partially supported like in Chrome on Mac. i.e. the scene looks good on Desktop browsers too and can be interacted with via the drag override control.

You can look at [a live VR demo that uses these proposed changes](http://richtr.github.io/threeVR/examples/vr_basic.html) to preview what these updates could bring to `THREE.DeviceOrientationController`.

Let me know if a) you think this is a good idea @mrdoob and b) whether I can issue a pull request for this library (with changes applied for it to hang-off the `THREE` object as per the current  [`THREE.DeviceOrientationController`](https://github.com/mrdoob/three.js/blob/master/examples/js/controls/DeviceOrientationControls.js) class).

**Comment by Mugen87** [comment]
Closing, see https://github.com/mrdoob/three.js/issues/5338#issuecomment-56187042
