### ISSUE TITLE
beginShape(mode) Shape / Shape3D suggestion

### ISSUE THREAD

**Issue by DBraun** [mrdoob/three.js#5339]
For custom 3d geometry, I want to pick a shape mode (QUAD_STRIP, TRIANGLES, TRIANGLE_FAN...) and then vertices. I don't want to think about faces.

I think it would be nice to have a feature similar to Processing's [beginShape(mode)](http://processing.org/reference/beginShape_.html) which is also implemented in [Processing.js](https://github.com/processing-js/processing-js/blob/master/processing.js) in Drawing3D.prototype.endShape

Should this be implemented as a function in THREE.Shape?

**Comment by Mugen87** [comment]
Since `Mesh.drawMode` was removed in `R112`, this issue can be closed.
