### ISSUE TITLE
glTFLoader Problems with skinned Meshes

### ISSUE THREAD

**Issue by digitaledge** [mrdoob/three.js#5341]
Hello,
there are a few cases where gltf models do not load with the current version of the loader.

- the model is skinned to a skeleton, but has no animation frames
- the model is skinned with influences only to a few bones, but not the complete skeleton

I did prepare a testfile with some skinned mesh that has both, no frames and its bound only to a few bones. This model was converted from opencollada using the gltf v06 converter. 

Such models do load well as collada, it would be great to have this working with gltf as well.

https://dl.dropboxusercontent.com/u/40028603/testrig.zip

**Comment by tparisi** [comment]
looking at this now
