### ISSUE TITLE
The order of OrthographicCamera constructor parameters

### ISSUE THREAD

**Issue by Mann90** [mrdoob/three.js#5355]
Three has this order: 
`OrthographicCamera( left, right, top, bottom, near, far ).`
And some other popular API is 

`void glOrtho(  GLdouble    left,
    GLdouble    right,
    GLdouble    bottom,
    GLdouble    top,
    GLdouble    nearVal,
    GLdouble    farVal);
`

Maybe we can change the order of OrthographicCamera constructor parameters? Any ideas?

**Comment by WestLangley** [comment]
This is not likely to be changed at this point.
