### ISSUE TITLE
Suggestion: the unit of precison of ray caster 

### ISSUE THREAD

**Issue by Mann90** [mrdoob/three.js#5366]
I suggest the unit of ray cast precision, including the face precision and line precision, could be in pixels. Then the API is much easier to use. (And IMHO, that is the real scenario that how most of users use picking API by specifying the picking tolerance values in terms of pixels.)

Moreover, the precision could be used as squares and circles internally. For example, if a user says the pick precision is 5, then we can use a 5 pixels X 5 pixels square to intersect the objects.

By the way, for performance reasons, we may use octree or quadtree to improve picking performance in the code. I saw the octree is already used in examples but that is an extension.

**Comment by donmccurdy** [comment]
It sounds like the Raycaster should not be dealing with screen-space units like pixels. GPU picking is an alternative here, and we have [examples for that.](https://threejs.org/examples/?q=gpu#webgl_interactive_cubes_gpu). 

So unless we hope to add a world-space precision parameter on the raycaster, perhaps this issue can be closed?
