### ISSUE TITLE
PointCloudMaterial doesn't work with CanvasRenderer?

### ISSUE THREAD

**Issue by sbuys** [mrdoob/three.js#5372]
When switching the renderer in any of the webGL particle examples, the point cloud is no longer visible. 

Since none of the canvas particle examples use a PointCloud, it's unclear whether PointCloud and PointCloudMaterial are compatible with the canvas renderer. The webgl_particles_billboards example looks like it shouldn't require any other changes besides switching the renderer.

It seems like the Point Cloud geometry is okay - in our project we can still calculate intersects with a Raycaster, the particles are just not rendered.

**Comment by grulex** [comment]
Just wondering if CanvasRenderer supports Points now? If not, any plans to make this happen in the near future? Thanks!

**Comment by mrdoob** [comment]
Implemented ✌️
