### ISSUE TITLE
Loading Morphtargets from Buffergeometry

### ISSUE THREAD

**Issue by digitaledge** [mrdoob/three.js#5393]
Hello,

i am not sure if thats an bug or feature request, but it seems that you actually cant load Morphtargets from Buffergeometry. They do just not morph after loading.

The docs are saying it should work: http://threejs.org/docs/#Reference/Core/BufferGeometry

Or is there maybe some special requirement i didnt notice?

Regards

Stefan

**Comment by mhelvens** [comment]
FYI: The [documentation](http://threejs.org/docs/api/core/BufferGeometry.html#morphTargets) still implies that `morphTargets` *is* supported. Until it has, perhaps the docs should be corrected?
