### ISSUE TITLE
When raycasting against BufferGeometry, possibly include indicesIndex

### ISSUE THREAD

**Issue by nickjer** [mrdoob/three.js#5394]
I noticed when raycasting against Geometry you give the `face` object and the `faceIndex`. But when raycasting against BufferGeometry you just give `indices` which is analogous to `face`.

Wouldn't it be beneficial as well to give `indicesIndex` and possibly the `offsetIndex` (analogous to `faceIndex`) in BufferGeometry?

This would allow the developer to find the corresponding indexed face in the indices array. Allowing him/her to change the face in some way (e.g., removing it or replacing it with other indices), or allowing easy selection of adjacent faces as well.

**Comment by makc** [comment]
Was looking for #6302 but ended up here. Thought why not link them.

**Comment by mrdoob** [comment]
#6302 implemented this.
