### ISSUE TITLE
Documentation vs. Wiki?

### ISSUE THREAD

**Issue by caseygrun** [mrdoob/three.js#5410]
Is there a principled separation between what goes in the [wiki](https://github.com/mrdoob/three.js/wiki) and what goes in the [API documentation](http://threejs.org/docs/)? Some of the stuff included or linked to in the wiki (e.g. https://github.com/mrdoob/three.js/wiki/Uniforms-types , https://github.com/mrdoob/three.js/issues/1188#issuecomment-3666286  / https://github.com/mrdoob/three.js/wiki/Using-Matrices-&-Object3Ds-in-THREE , https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/WebGLProgram.js#L104 , etc.) seems quite important and like it belongs in the API docs. If there's interest, I can try to scoop some of that information into pages in the docs as part of #5311.

**Comment by mrdoob** [comment]
Continued: #10388
