### ISSUE TITLE
LoadingManager: wrong order of events

### ISSUE THREAD

**Issue by jpcloud** [mrdoob/three.js#5438]
Hi,

Maybe I am getting this wrong, but shouldn't the loading manager first call the onLoad function and after that the onProgress function?

My Reason:
I load a json file (containing materials and a geometry) and I set the onLoad callback. In this callback I place the stuff in my scene and in some array to later modify it.

Now I wan to use the DefaultLoadingManager to start my application when everything is loaded.
I do it this way: 
THREE.DefaultLoadingManager.onProgress = function ( item, loaded, total ) {
    if (loaded == total) {
         start();
}

Since the order in which the callbacks are called is "progress" and after that "loaded" the LoadingManager starts the application before everything is setup properly and it (sometimes, depending on the load order) crashes.

If I am just using this wrong, feel free to point me in the right direction - if not, I'll be happy to switch the order of the callbacks and create a pull request.

**Comment by dubejf** [comment]
I tried running the linked example, it seems to give the correct result. Maybe the example was modified since first reported?

In any case, `JSONLoader` now implements `LoadingManager`. This should be fixed. #5758
