### ISSUE TITLE
Geometry.toJSON misses second UV layer

### ISSUE THREAD

**Issue by s9k** [mrdoob/three.js#5443]
I import model with several uv layers in editor, and after export or autosave/reopen it has only one UV layer.

Model has simple Geometry, not BufferGeometry.

PS Does BufferGeometry have second uv layer support?

**Comment by dubejf** [comment]
Attributes `uv` and `uv2` are supported with `BufferGeometry` in `r72dev` for reading (`ObjectLoader`) and writing (`toJSON`).
