### ISSUE TITLE
WARNING: Euler.setFromQuaternion() given unsupported order: 1

### ISSUE THREAD

**Issue by bwiklund** [mrdoob/three.js#5465]
I get this when calling `fooObject.quaternion.set(x,y,z,w)`

```
WARNING: Euler.setFromQuaternion() given unsupported order: 1
```

I'm fetching the library through npm, threejs version 0.66.4

**Comment by killroy42** [comment]
Please note that TransformControls in the function onQuaternionChange execute: `rotation.setFromQuaternion( quaternion, undefined, false );`, passing undefined explicitly for order, which cases the warning.

**Comment by WestLangley** [comment]
@killroy42 Can you provide a fiddle to replicate the warning?
