### ISSUE TITLE
Custom GL Draw Calls

### ISSUE THREAD

**Issue by mattdesl** [mrdoob/three.js#5469]
I'm looking to build an Object3D that can integrate into the rest of a ThreeJS scene graph, but issues its own low-level GL initialization and draw calls. The primary reason for this is so the object can be modular (published on NPM with no ties to ThreeJS) and reused on a variety of other projects. 

Right now the WebGLRenderer just checks `instanceof` to determine how to setup/render an object, which means that custom objects are out of the question. Is there any way around this? Like a `renderCustom` function or something I can override? 

I can submit a PR if there is a preferred way to add this feature.

**Comment by sc0rp1d** [comment]
@mrdoob 'RenderObject' is good idea. I need to manually batching of more geometry objects (with multiple draw types and materials), and 'RenderObject' must help me.

**Comment by sc0rp1d** [comment]
@mrdoob ping

**Comment by mrdoob** [comment]
@sc0rp1d In what order do you think these should be executed? At the moment we render objects that have `material.transparent = false` (opaque) first, then objects that have `material.transparent = true` (transparent). Do you think these objects should be included in the first group, the second, or is it fine if the render after (like currently `Sprites` and `LensFlares` do).

**Comment by sc0rp1d** [comment]
@mrdoob maybe you can add attribute (RenderObject.renderingQueue) for choosing this?
For example: THREE.RenderAsTransporent, THREE.RenderAsOpaque, THREE.RenderAfter and THREE.RenderBefore.

**Comment by mrdoob** [comment]
After some sleep, I'm thinking that the best solution for now would be to give `RenderObject` a material.

**Comment by mrdoob** [comment]
Also, as per names... `DirectObject`, `CustomObject`, `RawObject`, ...

**Comment by sc0rp1d** [comment]
Maybe `RenderObject` with material is good solution. Will be material applied for shader before execute callback?
I think `RawObject` is good, like as `RawShaderMaterial`

**Comment by snickell** [comment]
What still needs to be done for this? I'd like to integrate a large body of existing webgl code into a three.js scenegraph.

**Comment by mrdoob** [comment]
Currently you can do this:

```js
var mesh = new THREE.Mesh( new THREE.PlaneGeometry( 1, 1 ) );
mesh.onBeforeRender = function ( renderer ) {

    var gl = renderer.gl;
    gl.enable( gl.SAMPLE_ALPHA_TO_COVERAGE );

};
scene.add( mesh );
```

Note that if you mess with the `renderer.context` directly you're on your own. Try using `renderer.state` if possible.

**Comment by nopjia** [comment]
Is this issue resolved? Is the answer to use `onBeforeRender()` / `onAfterRender()`?
If so, is it possible to do only custom rendering through the callbacks, and not have the mesh itself actually render? As if it's an "empty" mesh?

**Comment by WestLangley** [comment]
@nopjia 
```javascript
geometry.setDrawRange( 0, 0 ); // to undo: geometry.setDrawRange( 0, Infinity );
```
