### ISSUE TITLE
Creating a long TubeGeometry along a long SplineCurve3 - Unexpected "kink"

### ISSUE THREAD

**Issue by JohnAnthony** [mrdoob/three.js#5503]
I can't tell if this is a bug in SplineCurve3, a bug in TubeGeometry or something I'm doing wrong. I have a long list (242) of 3d points that I'm feeding to a SplineCurve3 and creating a TubeGeometry from. There appears to be nothing unusual about the data at the point the "kink" is made, and the only difference between this and previous datasets is the number of points.

I'll endeavour to create in an example dataset and reproduce the issue on jsfiddle, but the data I'm using is sensitive and there's no way at all I can share it. Which is a bit of a bit of a ball-ache.

Switching to the latest build of dev branch, the issue persists.

![kink](https://cloud.githubusercontent.com/assets/436859/4767283/05b415a2-5b5c-11e4-8580-93be15e8bd8a.png)

**Comment by WestLangley** [comment]
@zz85 Would you be willing to implement your idea?

**Comment by zz85** [comment]
thanks for the reminder @WestLangley. i wanted to try this with more data set to compare differences, but it ended up on my back burner. let me try making some time for this in this week.

**Comment by zz85** [comment]
wrote a small example to show how the different curves (original SplineCurve, Centripetal, and Chordal) stack together here http://zz85.github.io/DragSpline/catmull_path_test.html

**Comment by WestLangley** [comment]
@zz85 Really nice demo! Would you consider adding a third dimension + `OrbitControls`?

**Comment by zz85** [comment]
@WestLangley that actually reminds me of a spline editor I worked on before. I'll try to pull that out.

meanwhile, I wonder if @mrdoob prefers a new class `THREE.CatmullRomCurve3` or prefers replacing the current `THREE.SplineCurve3` with https://github.com/zz85/DragSpline/blob/master/CatmullRomCurve3.js ?

**Comment by mrdoob** [comment]
CatmullRomCurve3 is more explicit :+1:

**Comment by zz85** [comment]
here we go @WestLangley http://zz85.github.io/ThreeLabs/spline_editor3.html

![image](https://cloud.githubusercontent.com/assets/314997/5950960/9cb9e0d6-a79b-11e4-82bc-6ab69dc84ac1.png)

**Comment by WestLangley** [comment]
@zz85 Thanks !

**Comment by WestLangley** [comment]
@zz85 What's your decision on this?

**Comment by zz85** [comment]
pending PR #5997...

**Comment by zz85** [comment]
PR 5997 has been merged, so this can be closed ;)
