### ISSUE TITLE
Feature request: It would be great to add a feature to render parts of the scene selectively.

### ISSUE THREAD

**Issue by OlexandrPopov** [mrdoob/three.js#5562]
I mean something like Camera.cullingMask in Unity http://docs.unity3d.com/ScriptReference/Camera-cullingMask.html

**Comment by tsone** [comment]
Is somebody implementing this? If not, I could give it a shot.

Personally, I'd follow [Unity's design](http://docs.unity3d.com/ScriptReference/Camera-cullingMask.html). However instad of `object.layerMask` I'd have `object.layerBits` to signify it's a [bitfield](http://en.wikipedia.org/wiki/Bit_field). A [mask](http://en.wikipedia.org/wiki/Mask_%28computing%29) is the other half of the masking operation. I think `camera.cullingMask` is a valid name and I'd use that.

Object will be culled if `(object.layerBits & camera.cullingMask) === 0`. I assume initially `object.layerBits = 0x00000001` and `camera.cullingMask = 0xFFFFFFFF` (=all layers enabled).

I'm not sure however if Unity culls the whole branch (=the object in question, its children, grandchildren etc.), but I'd rather have the behavior to cull the entire branch -- at least initially. Later we could have `material.layerBits` for material-based/object-only culling -- but I don't really want to think about this right now...

**Comment by tsone** [comment]
API-wise, I don't want the proposed utility functions or classes because I think it bloats the code. These could be added later if somebody requests them. I however do understand that artists may not know how bitmasking works, but anyway the complexity of this feature is at the level that any artist attempting to use it should know what they are doing and try to study how bitmasks really work.

**Comment by tsone** [comment]
Here you go: #5931

**Comment by mrdoob** [comment]
> I'm not sure however if Unity culls the whole branch (=the object in question, its children, grandchildren etc.), but I'd rather have the behavior to cull the entire branch -- at least initially.

I don't think we should be culling the whole branch. That's what `object.visible = false` is for.

**Comment by tsone** [comment]
@mrdoob Hmm, how about having both `Object3D.layerMask` and `Material.layerMask` just like with `visible`?

**Comment by mrdoob** [comment]
Lets first sort out object level first :)

**Comment by Mugen87** [comment]
Since `THREE.Layers` (formerly `THREE.Channels`) is part of the project since `r73`(see d36df79035978cb3f24b77f60e59404d41bbc07f), this issue can be closed.
