### ISSUE TITLE
Decouple PointerLockControls from its example?

### ISSUE THREAD

**Issue by ucarion** [mrdoob/three.js#5566]
[PointerLockControls.js](https://github.com/mrdoob/three.js/blob/master/examples/js/controls/PointerLockControls.js) is tightly coupled with its example -- there's a lot of stuff (`isOnObject`, `velocity`, `canJump`) that assumes you're making a first-person shooter or something. When I wanted PointerLockControls, that wasn't my use-case, and I found myself spending quite a bit of time getting rid of that stuff.

Maybe the FPS-specific logic could moved into `misc_controls_pointerlock.html` and PointerLockControls could be simplified to be easier to copy-paste?

If there's interest in this, I'd happily try to make a PR.

**Comment by dubejf** [comment]
Fixed by #5576.
