### ISSUE TITLE
Suggestion: spatial index for better performance when culling and sorting

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#5571]
I've been looking through the renderer code, and wondering about perofmance overhead of using a plethora of individual meshes. Looking at the code, there are 2 major improvements to be had:
 - culling
 - depth sorting

if we look at culling, we can see full traversal at work:
https://github.com/mrdoob/three.js/blob/2d59713328c421c3edfc3feda1b116af13140b94/src/renderers/WebGLRenderer.js#L3464-L3535

And similarly, if we look at sorting
https://github.com/mrdoob/three.js/blob/2d59713328c421c3edfc3feda1b116af13140b94/src/renderers/WebGLRenderer.js#L3368-L3373

if we had a spatial index such as an octree with bounding boxes - we could traverse it to get ojects in *almost* sorted order (local swaps would still be required).

For culling, we could similarly drop large amount of interation

**Comment by Doidel** [comment]
You can also find a k-d tree implementation in the three.js examples. I created an in-memory version of it. And here the theoretical values of operations on k-d trees: http://en.wikipedia.org/wiki/K-d_tree#Complexity (haven't read or tested whether it suits your needs, just happened to stumble over this issue)

**Comment by Usnul** [comment]
KD is very bad for resizing, the reason BVH seems to be the go-to solution for dynamic scenes is it's hierarchical structure. In BVH to translate 100,000 vertices that are clustered together you may simply move the volume bounding them, in KD this is not as simple. KD is a great solution for fast building times and it has better prunning performance for good trees compares to BVH, however - for dynamic scenes this means very little. There is a KD implementation for webGL that allows queries on GPU, but tree still has to be built on CPU. In the same key, using binary trees you can store BVH on GPU for querying.

Hope this help to clarify things a bit.
