### ISSUE TITLE
GridHelper produced a grid with dimensions twice the size expected

### ISSUE THREAD

**Issue by AaronMeyers** [mrdoob/three.js#5572]
The first argument of THREE.GridHelper is "size". If I pass it 10, I'd expect a 10x10 grid, but it returns a 20x20 grid.

I think it makes more sense to have size being directly related to the produced dimensions.

**Comment by Hectate** [comment]
FYI Slightly related to this, I submitted a pull request for documentation to clarify GridHelper's parameters.
https://github.com/mrdoob/three.js/pull/10145

**Comment by TristanVALCKE** [comment]
I also made this confusion about GridHelper arguments ! 
Maybe time to rework it ?

@dmtaub A rectangular grid could be very useful ! +1

And I take advantage that it talks about shape to also propose the **circle** ! In conjunction with the fog, it will give a much better effect (smoother) than a square.

Finally an other improvement could be to get an "infinite" scroll in/out like in Blender, that means who sub-cell will appear/disappear on zoom.

**Comment by Hectate** [comment]
A CircleGridHelper would be cool. Are you imagining line segments radiating out from the center, and circle shapes breaking those segments up more too?

**Comment by WestLangley** [comment]
The main issue of this post was resolved long ago. Closing.

**Comment by backspaces** [comment]
How about documenting how this works on the GridHelper doc?

**Comment by looeee** [comment]
I put off updating the docs as I think @Mugen87 was making some changes to the code here - can't remember the PR now, but did this behaviour get changed?

**Comment by Mugen87** [comment]
see #10570

**Comment by backspaces** [comment]
Thanks!
