### ISSUE TITLE
Doesn't install the newest version when doing bower install

### ISSUE THREAD

**Issue by EloB** [mrdoob/three.js#5574]
I'm getting version 68 when doing `bower install three.js`. Tried everything cleaning the cache and removed bower folder but still getting 68.

**Comment by ChiChou** [comment]
Although threejs is the official repo, I prefer using three.js because the former contains whole git repo and costs plenty of time to download. @jiyinyiyong Do you update the repo manually?

**Comment by jiyinyiyong** [comment]
@ChiChou Yes. So I just missed another update... Any ideas on fixing this?

**Comment by Akfreak** [comment]
$ git remote -v
# List the current remotes
origin  https://github.com/user/repo.git (fetch)
origin  https://github.com/user/repo.git (push)

$ git remote add upstream https://github.com/otheruser/repo.git
# Set a new remote

$ git remote -v
# Verify new remote
origin    https://github.com/user/repo.git (fetch)
origin    https://github.com/user/repo.git (push)
upstream  https://github.com/otheruser/repo.git (fetch)
upstream  https://github.com/otheruser/repo.git (push)


Syncing
There are two steps required to sync your repository with the upstream: first you must fetch from the remote, then you must merge the desired branch into your local branch.

Fetching

$ git fetch upstream
# Grab the upstream remote's branches
remote: Counting objects: 75, done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 62 (delta 27), reused 44 (delta 9)
Unpacking objects: 100% (62/62), done.
From https://github.com/otheruser/repo
 * [new branch]      master     -> upstream/master

**Comment by ChiChou** [comment]
@jiyinyiyong Maybe @mrdoob can set up a repo for package management, excludes all source files but build dist. When new commits pushed to main branch, automatically update another repo through continuous integration (like TravisCI).

**Comment by jiyinyiyong** [comment]
Just made another manual update: https://github.com/jiyinyiyong/three.js/commits/master

**Comment by mrdoob** [comment]
> @jiyinyiyong Maybe @mrdoob can set up a repo for package management, excludes all source files but build dist. 

That's what [bower.json](https://github.com/mrdoob/three.js/blob/master/bower.json) is supposed to be doing already...?

**Comment by mattdesl** [comment]
> That's what bower.json is supposed to be doing already...?

This is unfortunately a limitation of bower. It needs to fetch the entire git repo (including examples, models, etc) in order to even get to the bower.json.

**Comment by ChiChou** [comment]
@mrdoob Although files are already marked ignored, bower still clones the whole repo or download a release tarball. Both are too long to wait.

**Comment by jiyinyiyong** [comment]
In my case in this directory are the stuffs Bower downloaded:
```
/Users/chen/.cache/bower
```

**Comment by mrdoob** [comment]
> This is unfortunately a limitation of bower. It needs to fetch the entire git repo (including examples, models, etc) in order to even get to the bower.json.

Well, sounds like that's a feature request for bower then!
