### ISSUE TITLE
Loading collada from SketchUp butchers textures

### ISSUE THREAD

**Issue by ChrisBence** [mrdoob/three.js#5584]
I have not been able to successfully import a 3d collada file from SketchUp into three.js with the textures intact as they were in SketchUp.

An examples can be found here: http://chrisbence.com/lab/energySupply/

Sometimes entire assemblies are rotated 90 degrees from their location in the sketchup model...

I can't tell if this is a loader problem or a SketchUp export bug.

**Comment by Mugen87** [comment]
If you still experience the problem with `ColladaLoader2`, we can reopen this issue. This loader was enhanced in the last time and should handle texture wrapping correctly. Well, i hope so :blush:.
