### ISSUE TITLE
Custom named attributes does not work with RawShaderMaterial

### ISSUE THREAD

**Issue by mpk** [mrdoob/three.js#5589]
I have created a mesh with RawShaderMaterial with custom named attribute, but it does not work - the shader receives only zeros from the attribute (though the buffer is not empty). However, if I change the attribute name to, for example, "uv2" (or any name three.js uses internally - such as "color", "uv", "uv2", ...) everything is OK.

I have created an example to demonstrate the issue:
http://jsfiddle.net/mbsof67k/
The example should show two white rectangles next to each other. If you change the line 54 from "foo" to any internal three.js name (for example, "uv"), the second rectangle appears.

This issue occurs in every browser (Firefox, Chrome, IE, Safari), so it's probably issue with the library.

**Comment by mrdoob** [comment]
Fixed since `r72`. http://jsfiddle.net/mbsof67k/3/
