### ISSUE TITLE
Shaders inconsistently transforming positions. (Z-Fighting)

### ISSUE THREAD

**Issue by manthrax** [mrdoob/three.js#5596]
Depending on the combination of shader/material, vertices with the same world positions will render at difference screen space positions. This causes massive z fighting in places where it shouldn't, such as doubled geometry where Z_EQUALS should allow layering.

The problem is the following:

About half of the THREE.js shaders (including lambert) do a two step transformation of position to screenspace.. using this form:

```javascript
vec4 mvPosition = modelViewMatrix * vec4( position, 1.0 );
gl_Position = projectionMatrix * mvPosition;
```

The rest use:

```javascript
gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );
```

The condensed form resolves differently, presumably since the card either optimizes the transform, or uses a different numeric resolution with the condensed form.

I would propose, barring performance impact, standardizing on the split form as used in the lambert shader. This gives the most flexibility if the shader needs access to the intermediate mvPosition. Otherwise to be screen space consistent, shaders that need access to the intermediate mvPosition, will have to perform the final transformation from scratch using the condensed form, if they wish to have results consistent to other shaders.

Here's an example of the LambertMaterial, and default ShaderMaterial producing z-fighting when doubled on two cloned meshes. (in red/pink)
![img_09112014_004551](https://cloud.githubusercontent.com/assets/350247/4966937/63c9943e-67ee-11e4-81c8-fbb8eb3c812b.png)

Here is the result after I modified the ShaderMaterial to use the same split form transformation as Lambert:
![img_09112014_004532](https://cloud.githubusercontent.com/assets/350247/4966940/8e535942-67ee-11e4-9fb3-0e6aa6230528.png)

**Comment by mrdoob** [comment]
This sounds like a drivers/gpu issue...
Do you have a simpler test case we can have a look at in different configurations?

**Comment by manthrax** [comment]
I think it's just an issue with the shaders being written using a consistent method of transforming glPosition. It most likely is driver/gpu dependent but I don't think it will ever be "fixed" in drivers.. its just that the math resolves differently depending on how the expression is broken up in the shader. At the time I posted this I was running on an ATI card. I'm on an NVidia card now and haven't verified that it's still an issue. I mostly just wanted to get it on record here, in case someone comes hunting for a solution to z-fighting on identically placed geometry.
