### ISSUE TITLE
ObjLoader - Feedback (multiple materials + decals)

### ISSUE THREAD

**Issue by joeyhub** [mrdoob/three.js#5598]
I'm new to 3D so apologies for lack of basic knowledge in areas...

I'm using the ObjLoader shipped in rev 67 (I want to use a newer revision but it breaks some things).

I am using https://github.com/spite/THREE.DecalGeometry to place decals on meshes loaded from an obj. I find this much easier than UV mapping with my current toolset (opensource, wings3d, blender). I think the better way might be traditionally to apply the decals with blender3d and have it generate the UV maps but I have barely touched the surface with blender and the objects I am mapping decals to are quite repetitive geometrically requiring a high level of accuracy for decal placement which is easier to do programmatically.

In getting this to work I've bumped into a few usability quirks around ObjLoader for this:

Combining MTLLoader and ObjLoader did not appear to work without modification. The usemtl handling is a bit confusing in ObjLoader. That is, I don't understand the point of changing the name of the material. My guess is that someone though there should be one material per object and this was a good way to map loaded materials after the fact.

I tried using ObjMtlLoader. This works well and looks good until I want to do anything with the result. I get several objects/geometries out of this with a lot of repetition between them. This was not really convenient to use for applying decals.

I found the simplest approach is to modify the ObjLoader class to set the face material indexes according to the material:

Change:
		function face3( a, b, c, normals ) {
			var face = new THREE.Face3( a, b, c, normals );
			handleMtl(face);
			return face;
		}

Add:

		var mtl_idx = 0; // Index couinter.
		var materials = {}; // Maps material names to indexes.
		var mtl = null; // Current material.

		function handleMtl(face) {
			if(mtl === null)
				face.materialIndex = 0;
			else
				face.materialIndex = materials[mtl];
		}

Change:

			} else if ( /^usemtl /.test( line ) ) {
				mtl = line.substring(7);

				if(!(mtl in materials)) {
					materials[mtl] = mtl_idx++;
					console.log('Added material '+mtl+' at '+materials[mtl]);
				}
			}

The material in this case is a MeshFaceMaterial loaded first using MtlLoader and passed down in a new parameter to load->parse...

	var loader = new THREE.MTLLoader(manager);
	var mats, item;

	loader.load('item.mtl', function(object) {
		mats = object;

		var loader = new THREE.OBJLoader(manager);

		loader.load('item.obj', new THREE.MeshFaceMaterial([
			mats.create('a'),
			mats.create('b'),
			mats.create('c')
		]), function(object) {
			item = object.children[0];
			scene.add(item);

For me this works and properly creates geometry groups rather than multiple objects with a lot of repetition between them.

This is useful for me in particular as I am applying behaviours to different faces. A notable quirk of the ObjLoader is that it ignores g (group) lines for faces. I think this is something more related to the core of three.js which groups faces purely on materials/aesthetics. An easy work around for me is to clone a material and give it a special name to make faces identifiable. Another quirk is that makeGroups is not applied until render (depends on _glExtensionElementIndexUint) although this is easily fixed externally if a slightly inelegant program flow is tolerable.

My changes work with a few quirks that are likely to be user error. As far as I can see there's no benefit for loading multiple objects instead of geometry groups.

The summary of all this:
* There are some possible usage cases for grouping faces or preserving grouping so that we can easily identify faces to tag special functionality to.
* I don't know exactly why MtlObjLoader uses groups of objects rather than groups of geometry.

**Comment by thure** [comment]
Why was this closed? I found this after experiencing the same issue using r74dev. Would a PR with this fixed be considered?

**Comment by mrdoob** [comment]
@thure what issue exactly?
