### ISSUE TITLE
Dynamic Skeletal Animation

### ISSUE THREAD

**Issue by imvan32** [mrdoob/three.js#5600]
Hello everybody! I have posted my question on this site 
http://stackoverflow.com/questions/26496792/three-js-multiple-skeletal-animations, but nobody can give me some answer. Maybe I cannot fully describe my situation, so I want this question be examined there without sending me to http://stackoverflow.com/.
I have tried to change keyframes  for the definite bones in this 

``` javascript
THREE.Animation.prototype.getNextKeyWith = function ( type, h, key ) {

    var keys = this.data.hierarchy[ h ].keys;

    if ( this.interpolationType === THREE.AnimationHandler.CATMULLROM ||
         this.interpolationType === THREE.AnimationHandler.CATMULLROM_FORWARD ) {

        key = key < keys.length - 1 ? key : keys.length - 1;

    } else {

        key = key % keys.length;

    } 

    if (this.additionalAnim.currentAdditionalAnim[h] && type=='rot') {

           here the change is making

        }
```

during main animations playing, but it looks awful and I'm sure that there is another better way to make it. Thanks.

**Comment by Mugen87** [comment]
`THREE.Animation` is deprecated.
