### ISSUE TITLE
ParticleBasicMaterial in PointCloud : fog:true seems broken.

### ISSUE THREAD

**Issue by flexelektro** [mrdoob/three.js#5608]
if the scene has fog:
rendering particles with fog:true is broken:

```
        var texture = THREE.ImageUtils.loadTexture("../app/assets/sprite1.png");
        var cloud = new THREE.PointCloud(geometry, new THREE.ParticleBasicMaterial({
            map: texture,
            transparent: true,
            blending: THREE.NormalBlending,
            size: 0.5,
            fog:true
        }));
```

it will show just some rectangles ...
with fog:false its all okay, but - of course - no fog is applied.

**Comment by loraruffin** [comment]
I have the same problem. This example doesn't work on my machine: 
http://threejs.org/examples/#webgl_particles_sprites
I also have an early 2011 Mac Intel HD Graphics 3000 384 MB

**Comment by Mugen87** [comment]
Closing. If the problem still exists, it makes more sense to report this as a driver bug to Intel.
