### ISSUE TITLE
Raycaster docs should mention Backface visibility

### ISSUE THREAD

**Issue by pehrlich** [mrdoob/three.js#5613]
I had to figure this out the hard way - it would be good to have in the docs:

IIRC, for a raycaster to intersect a Mesh/Geometry, that mesh must be rendering faces towards the origin of the raycaster.  For that reason, it may be advisable to ensure that PlaneMeshes are set with `side: THREE.DoubleSide`

**Comment by caseygrun** [comment]
Closed by #5905
