### ISSUE TITLE
View sources from examples in Safari

### ISSUE THREAD

**Issue by khx42** [mrdoob/three.js#5618]
The link to view sources for examples has a prefix:
view-source:http://threejs.org/examples/webgl_buffergeometry_rawshader.html

With latest Safari (8.0) it can't reroute to the appropriate view or utility to show the values. It would be nice if the redirection just showed the source as a simple text web page instead.

**Comment by looeee** [comment]
Can somebody with Safari check whether this is still an issue?

**Comment by khx42** [comment]
Tested, clicking on the source button now opens the github page with the
source. Thx, Kent
