### ISSUE TITLE
setSize(window.innerWidth/2, window.innerHeight/2) not scaling to fill browser

### ISSUE THREAD

**Issue by jochasinga** [mrdoob/three.js#5631]
Following the getting started tutorial:

> ...give setSize smaller values, like window.innerWidth/2 and window.innerHeight/2, for half the 
> resolution. This does not mean that the game will only fill half the window, but rather look a bit blurry
> and scaled up.

`setSize(window.innerWidth/2, window.innerHeight/2)` actually scales the canvas to 50% for some reason in Chrome.
![screen shot 2014-11-14 at 6 52 53 pm](https://cloud.githubusercontent.com/assets/2445163/5055361/14a0ba68-6c30-11e4-865c-57866203cd9a.png)

**Comment by Mugen87** [comment]
The mentioned section of the "Getting started" tutorial is not valid anymore. If you want to retain a fullscreen canvas, set `width` and `height` of the canvas via CSS to `100%` and perform `.setSize()` like this:
```javascript
renderer.setSize( window.innerWidth / 2, window.innerHeight / 2, false );
```
Like mentioned in the [docs](https://threejs.org/docs/index.html#api/renderers/WebGLRenderer.setSize) setting `updateStyle` to `false` prevents any style changes to the canvas DOM element.

https://jsfiddle.net/f2Lommf5/842/

**Comment by mrdoob** [comment]
Another option would be doing this:

```js
renderer.setPixelRatio( window.devicePixelRatio / 2 );
```

**Comment by Mugen87** [comment]
That's even better 😅
