### ISSUE TITLE
Problem with normal mapping on BoxGeometry

### ISSUE THREAD

**Issue by CirilBohak** [mrdoob/three.js#5662]
I have found a problem when using normal maps with BoxGeometry.

While on some faces the effect of normal map show as expected on other does not. I guess that the problem is that normals are not transformed correctly for each individual face. How is it with others, has any other came across this problem?

The code is very simple:
```javascript
var diffuseMap = "assets/floor005_diffuse.png";
var normalMap = "assets/floor005_normal.png";
var specularMap = "assets/floor005_specular.png";

var geometry = new THREE.BoxGeometry( 2.0, 2.0, 2.0 );
var imgTexture = THREE.ImageUtils.loadTexture( diffuseMap );
imgTexture.repeat.set( 1, 1 );
imgTexture.wrapS = imgTexture.wrapT = THREE.RepeatWrapping;
imgTexture.anisotropy = 16;

var imgTexture2 = THREE.ImageUtils.loadTexture( specularMap );
imgTexture2.repeat.set( 1, 1 );
imgTexture2.wrapS = imgTexture2.wrapT = THREE.RepeatWrapping;
imgTexture2.anisotropy = 16;

var imgTexture3 = THREE.ImageUtils.loadTexture( normalMap );
imgTexture3.repeat.set( 1, 1 );
imgTexture3.wrapS = imgTexture3.wrapT = THREE.RepeatWrapping;
imgTexture3.anisotropy = 16;

var material2 = new THREE.MeshPhongMaterial(
            {
                map: imgTexture,
                ambient: 0x030303,
                color: 0xdddddd,
                specular: imgTexture2,
                shininess: 10,
                shading: THREE.SmoothShading,
                normalMap: imgTexture3,
                metal: false,
                skining: true
            }
        );

var cube = new THREE.Mesh( geometry, material2 );
scene.add( cube );
```

Bellow are the images with correctly and incorrectly mapped normal maps. First is correct and second is incorrect.
![true](https://cloud.githubusercontent.com/assets/3185466/5124137/edc71850-70b3-11e4-99eb-b33c65757476.png)
![false](https://cloud.githubusercontent.com/assets/3185466/5124141/0928e29a-70b4-11e4-8cc1-c8059f1cf107.png)

**Comment by cfhttpthreadbare** [comment]
> [@mrdoob](https://github.com/mrdoob): I'll try doing that. I'll try putting together scene in Maya to see the results.
> 
> [@WestLangley](https://github.com/WestLangley): I'll put it up tomorrow, and I'll try to make some presets to point out the problems as well as make some additional screenshots with markings where things are not as they should be.





https://stackdev.space/questions/unique-shapes-for-the-faces-of-cubes
