### ISSUE TITLE
instanceof and architecture for extension

### ISSUE THREAD

**Issue by sunag** [mrdoob/three.js#5673]
Hi @mrdoob.

Have you ever thought of changing the architecture with prototype to reduce the number of instanceof on the code? This would help to extend and optimizes the project for many instances.

Another thing also applied to shaders. At the time I used wanted to create a [Layered Texture](http://www.poonya.com/watch/5YLst7z2QqR) as I did in Flash ([SEA3D](https://github.com/sunag/sea3d)) but found no alternative to extends without change the root code. Today this is possible with the new changes in r69 from prototype class?

My benchmarking about instanceof and prototype:
```javascript
function Obj() {}
Obj.prototype = {
	constructor: Obj,
	fn : function () { }	
}

// PROTOTYPE (Naturally is dynamic)
var n = new Date().getTime();
var i = 0;
var obj = new Obj();
while(i++ < 100000000)
{
	obj.fn();
}
console.log(new Date().getTime() - n);

// SINGLE INSTANCEOF
var n = new Date().getTime();
var i = 0;
while(i++ < 100000000)
{
	if (i instanceof Date)
	{
	}
}
console.log(new Date().getTime() - n);

// MULTIPLES INSTANCEOF
var n = new Date().getTime();
var i = 0;
while(i++ < 100000000)
{
	if (i instanceof Date)
	{
	}
	else if (i instanceof Date)
	{
	}
	else if (i instanceof Date)
	{
	}
	else if (i instanceof Date)
	{
	}
	else if (i instanceof Date)
	{
	}
	else if (i instanceof Date)
	{
	}
}
console.log(new Date().getTime() - n);

// prototype: 1839
// single instanceof: 1346 
// multiples instanceof: 4980 
```

Thanks,
Cheers.

**Comment by kumavis** [comment]
I don't understand the conclusion

**Comment by sunag** [comment]
Hi @kumavis .

This technique can you use proxy functions or simply replace them by other no need to modify the source code.

A example like this http://sunag.github.io/Oimo.js-Lab/test_bvh.html where replaces the functions flatten bone matrices native for a custom, such things can be done as a plugin since it uses prototype, besides the hierarchy based on prototype or similar be father of object-oriented language.

Cheers.

**Comment by thure** [comment]
+1 – discussed in [this comment](https://github.com/mrdoob/three.js/issues/5886#issuecomment-90995873) of #5886

**Comment by kumavis** [comment]
@sunag thanks for the suggestion, I think its appropriate to fix the way this is being handled in the source.
