### ISSUE TITLE
PlaneGeometry lost separate positions/UVs for each tile since r69

### ISSUE THREAD

**Issue by elisee** [mrdoob/three.js#5686]
(Related to #5657)

There was a behavior change for PlaneGeometry (and possibly other geometry classes) in r69 not mentioned in the release notes so I believe it might have been overlooked and/or unwanted.

PlaneGeometry used to create separate a separate set of UVs for each face in r68 and earlier versions, as evidenced here: https://github.com/mrdoob/three.js/commit/fce86cbbdad7e774744cf4482a6fcc415ff9faa0#diff-53d98cf69b8d7487c6245714cec71128L74

UVs are now shared just like vertex positions, which makes creating tile maps with PlaneGeometry impossible. More importantly, it breaks existing code when upgrading to r69.

Was the change meant to happen or is it a bug? Is there some other class that provides the old behavior or should we build our own?

**Comment by dubejf** [comment]
According to the comment, this was fixed in r70 by #5567.
