### ISSUE TITLE
Raycaster performance improvement

### ISSUE THREAD

**Issue by QuaziKb** [mrdoob/three.js#5691]
Currently the raycaster seems to loop through all instances without smart broadphase to cull objects quickly if a user only really wants the first intersection (which is i'd think the most common use case). raycaster naively loops through all the objects its given if a sphere/AABB check passes and just fills up an array with all those intersections, most of which are usually not needed and lead to terrible performance if a ray hits a deep/long/tall stack of objects. ideally there would be a method to effeciently return info about the first intersection by doing an initial bounding sphere sort, removing any objects that intersect the ray but are too far to intersect it before others, and then move onto narrow-phase. for now i'm going to have to write my own but it seems like this should be part of "a class that makes raycasting easier"

**Comment by CodingFabian** [comment]
@QuaziKb can you provide what you have written? I am interested in that and maybe can work on contributing that.

**Comment by WestLangley** [comment]
As an alternate approach, we have http://threejs.org/examples/webgl_octree_raycasting.html

**Comment by CodingFabian** [comment]
Thanks @WestLangley in fact we use that already, but I am still interested to experiment with other options, shooting for 60fps :-)

**Comment by Mugen87** [comment]
Closing. #12857 is now the leading issue for this topic.

**Comment by Usnul** [comment]
related: #13909
