### ISSUE TITLE
THREE.clock.getElapsedTime has a side effect invalidating .getDelta()

### ISSUE THREAD

**Issue by AndrewRayCode** [mrdoob/three.js#5696]
https://github.com/mrdoob/three.js/blob/master/src/core/Clock.js#L40

If the user's render function calls both `getElapsedTime` and `getDelta` in a `requestAnimationFrame`, the code will not work properly and it will be impossible to debug why without the "aha" moment of looking at the source. These two functions should not conflict with each other.

It's because `getElapseTime` calls `getDelta`, so for example if your code looks like this:

```
var elapsed = clock.getElapsedTime(),
    delta = clock.getDelta();
```

the delta will actually be the time between those two var statements!

A workaround for now is to call `getDelta()` first, which will get the delta between getDelta and the last **getElapsedTime** call, which is not ideal.

**Comment by DelvarWorld** [comment]
Relevant: http://stackoverflow.com/a/34934720/743464

**Comment by spbond** [comment]
In issue #11444 I also noted this problem, along with some others, and proposed some code which would completely decouple the two functions from each other.  The changes I proposed are based on r85.

**Comment by Lowlet** [comment]
I just lost two days trying to play animation because of this. Thank god i found this thread. Can this be at least mentioned in the Clock docs?

**Comment by Redcxx** [comment]
Spent a solid hour debugging my program and finally found this...

**Comment by manake** [comment]
This issue is opened since 2014 and this is still a bug.

Most importantly: The current clock doesn't allow to `pause()` and `resume()`, so it's entirely useless in some use cases and the only solution is to create a different clock class because sometimes no workaround is possible with current `THREE.Clock`.

**Comment by Mugen87** [comment]
At this point, please use the new [Timer](https://threejs.org/docs/index.html#examples/en/misc/Timer) class if you experience issues with `Clock`.

**Comment by hichemfantar** [comment]
is the Timer class supposed to completely replace Clock?

**Comment by Mugen87** [comment]
Ideally yes, see https://github.com/mrdoob/three.js/issues/30497#issuecomment-2659170958.
