### ISSUE TITLE
Lerp Improvement Suggestion

### ISSUE THREAD

**Issue by Zob1** [mrdoob/three.js#5699]
Hola mrdoob et al, just a quick suggestion to an already amazing library:

Vector3 Lerp currently uses this format: 

    vector1.lerp( vector2, alpha )

May I suggest this format: 

    vector1.lerp( vector2, vector3, alpha, additive_boolean )

Where:
- vector1 is the vector to be modified.
- vector2 is the start vector.
- vector3 is the end vector.
- additive_boolean is whether to add result to vector1 or ignore current value. Default false.

My big issue with the current lerp is that the alpha we pass represents a fraction of the *distance left to travel*, not of the total distance. This means a static alpha ( 0.5 for example ) will always be half the distance remaining, and not reach the goal. ( Actually it does because of variable precision limits but this is undesirable behavior. ) 

The solution is to control alpha, but since the distance remaining is getting smaller, a linear set of alpha values such as [ 0.0, 0.5, 1.0 ] actually represent inconsistent distances of [ 50%, 25%, 25% ] in terms of the total distance traveled, which causes the vector to change by a large amount, then smaller amounts. So if we want our calculate our alpha so that it results in a consistent steady change, we have to store and use our start vector somewhere, which is easy, but it forces our loop to look something like this:

    while( alpha < 1 ) {
        alpha += 0.1;
        v_lerp.copy( v_start );
        v_lerp.lerp( v_end, alpha );
    }

Vector v_lerp must be reset each time to ensure linear change in alpha results in linear change in v_lerp. 

Since we have to store our start vector somewhere anyway, lets use it to make lerp more flexible and more intuitive to control. An example using the new format could look like this:

    var alpha = 0.0;
    while( alpha < 1 ) {
        alpha += 0.1;
        v_lerp.lerp( v_start, v_end, alpha );
    }

or, using additive_boolean to avoid changes in alpha value:

    var alpha = 0.1;
    while( v_lerp != v_end ) {
        v_lerp.lerp( v_start, v_end, alpha, true );
    }

Sorry for the long post. I'd love to hear what you guys think!

**Comment by mattdesl** [comment]
I use lerp on every project. It might be handy to have `lerpVectors` for consistency with `subVectors` et al, but I don't think lerp should act any differently than it does now. The `additive` boolean is confusing.

**Comment by WestLangley** [comment]
We could add to `Vector2`, `Vector3`, and `Vector4` the following method:

	lerpVectors: function ( v1, v2, alpha ) {

		this.subVectors( v2, v1 ).multiplyScalar( alpha ).add( v1 );

		return this;

	},

> but for myself I think would prefer to use vector.subVectors( end, start ).multiplyScalar( alpha ).add( start ); than to look up the api for lerp.

I do not have a strong feeling one way or the other.

> I don't think lerp() should act any differently than it does now.

Agreed.

I'll defer to whatever @mrdoob wants to do.

**Comment by mrdoob** [comment]
Sounds good to me! Any takers? ^^

**Comment by WestLangley** [comment]
I'll take care of it.
