### ISSUE TITLE
Light helpers off position when not added directly to scene

### ISSUE THREAD

**Issue by lotcz** [mrdoob/three.js#5705]
Currently light helpers must be added directly to scene to render it's position correctly. Is it possible that light helper position would be handled same way as with other objects and therefore it'd be possible to put them into wrappers?

problem demonstration:  http://jsfiddle.net/wfpxdw37/24/

**Comment by NPatel10** [comment]
Assign new matrix to helper had resolved issue for me.

`helper.matrix = new Matrix4()`
