### ISSUE TITLE
LensFlare double render at large distances with low camera.near value

### ISSUE THREAD

**Issue by Zob1** [mrdoob/three.js#5706]
Hey guys, wrestled with this for days but need some help.
( THREE.js R69, Windows8, NVIDIA GeForce GTX 760, Chrome 39.0.2171.71 m )

This JSFiddle http://jsfiddle.net/Angrypickle/mbtdxazy/24/ shows a LensFlare image appear in front of the PerspectiveCamera as the camera moves away (and is looking away) from the actual lensflare position. You may have to re-run the jsfiddle to see it appear because it happens quickly.

The lensflare should only appear at position [0,0,0] but when the camera reaches a certain distance, a duplicate lensflare appears in a location opposite the original lensflare. The distance necessary to achieve the bug seems to be related to the camera's `.near` and `.far` properties. 

I can circumvent the bug by setting a higher `camera.near` value, but I don't want to do that :) Thanks in advance for help!

**Comment by Mugen87** [comment]
Unable to reproduce the problem with the latest `Lensflare` implementation. I've seen that the demo uses extreme values ( > 10.000.000) for positioning 3D objects in the scene. This approach causes precision related problems that might explain visual artifacts or errors. Even big game engines like Unity can't handle these dimension properly.
