### ISSUE TITLE
Geometry.clone() doesn't clone morphTargets

### ISSUE THREAD

**Issue by QuaziKb** [mrdoob/three.js#5711]
Pretty self explanatory, spent a while debugging only to find out cloned geometry is completely devoid of morph targets.

EDIT, looks like a reference to the morph target array of the object being cloned is sufficient too. guess it would be more reasonable to do that than make a deep copy, though i still think the clone method should do at least this since its hard to find if you're getting weird behaviour.

**Comment by Mugen87** [comment]
Fixed with #10514
