### ISSUE TITLE
ReceiveShadow docs should mention pre-render requirement

### ISSUE THREAD

**Issue by pehrlich** [mrdoob/three.js#5716]
Empirically, setting an object to receiveShadow after a call to render causes the property not to be observer.

It would be nice if either
a) The docs mentioned this: http://threejs.org/docs/#Reference/Core/Object3D
b) The property worked after render (perhaps with a custom setter + magic)

cc @TatumCreative

Cheers,
--Peter

PS - Let me know if updates like this and #5613 are helpful - I can keep an eye out for such things as I learn them.

**Comment by looeee** [comment]
@pehrlich I'm not sure what you mean here  exactly. Is this related to the fact that the renderer.render() method needs to be called at least twice for shadows to work? 

@mrdoob is this still an issue?

**Comment by mrdoob** [comment]
This is no longer an issue.
