### ISSUE TITLE
Geometry face material support depends on object graph layout (initialization order error)

### ISSUE THREAD

**Issue by apriori** [mrdoob/three.js#5720]
Please take a look at the really simple jsfille example derived from the MeshFaceMaterial example:

http://jsfiddle.net/tq48t2ya/6/

In here, geometry sharing is used to instantiate two boxes which shall have different materials. Upon scene construction in the three.js renderer, the two boxes will be rendered and their geometries initialized. If the box which is using the geometry first (as defined by the object graph traversal order) uses a material that is no MeshFaceMaterial (same material for every face), the resulting geometry does not gain the support for such a material upon rendering of the inner box with a MeshFaceMaterial resulting in only the first material in the MeshFaceMaterial (the right side) being used on all faces.

Upon initialization the renderer should check for the most general needed material support for a geometry and not make any assumption on object definition order and their materials.

Note, this error can be worked around by preventing geometry sharing. While this might be acceptable for many applications, it is totally unacceptable when loading the scene from a JSON document via THREE.ObjectLoader, because the resulting JSON will grow a lot, and therefore loading performance will suffer significantly.

**Comment by Mugen87** [comment]
`MeshFaceMaterial` has been removed some time ago. Multiple materials are handled differently now. The issue should be solved now (at least the fiddle looks good with `R89`).
