### ISSUE TITLE
ColladaLoader can't reuse instance 

### ISSUE THREAD

**Issue by Baccanno** [mrdoob/three.js#5721]
I guess there is an issue when loading multiple collada files at a time with a single instance of the ColladaLoader 

It's could also be an issue with my own resource manager but I'd like to share the problem here so maybe somehow facing the same hurdle will have a clue on how to handle it.

I firstly used a shared instance of the ColladaLoader 

loadModel () => `loader = this.colladaLoader` and was experiencing a bug when preloading a lot of models. I guess that when several models are loading there is a shared memory issue in the object.

The code was failing at instruction (I'm using the current last version available on the repo)
`2586 : this.geometry3js.computeFaceNormals();` 

This part of computeFaceNormals was returning undefined vectors as indexes on the faces where out of bound.

			var vA = this.vertices[ face.a ];
			var vB = this.vertices[ face.b ];
			var vC = this.vertices[ face.c ];

Simply creating a new loader for each model to load fixed my issue.

loadModel () => `loader = new THREE.ColladaLoader();`

Sorry for not looking further into the loader to see what's the real issue. But I guess it's sufficient to add a warning if someone tries to load to models at a time.

**Comment by rethink-rlinsalata** [comment]
@Baccanno - Was there any more information on this issue beyond an issue with V8? What exactly was the issue? I am concerned I am seeing a reoccurrence of this issue (starting with changes made for r72) that can't be worked around with the 'new ColladaLoader()' for each.

In my case, I am seeing a near identical error in a computeFaceNormals() call with the out of bound face indexes. I also see very distorted shapes for the corrupted meshes when I display them - almost 'imploded' looking. Just trying to see if your issue was the same as the one I now face.

**Comment by Baccanno** [comment]
Well my game was updated lately with r72 and the issue didn't reappear in my case. Is it a random error or you can reproduce it ?

**Comment by rethink-rlinsalata** [comment]
Yes, every time. You can see it even if you go to the http://threejs.org/editor/ and try to import two different .dae files - the first one works, all others are distorted.

I'm surprised you don't have the issue - your 'examples/loaders' were updated to the r72 version too?

From looking in to the code, they changed the entire nature of the loader's main variables (ex: `var COLLADA;`) so they are shared for the module between every new instance of ColladaLoader - where as previously the variables were inside the `function ColladaLoader() {}` itself so `new ColladaLoader()` would create new variables.

(Thanks for responding btw! a whole year later!)

**Comment by BengtGustafsson** [comment]
So, when is it safe to reuse the loader? I'm trying to reuse it inside the callback, to sort of "chain" the next load by recursing to a function but this doesn't seem to work even if I create a new ColladaLoader in each invokation:

// This assumes an array names with a bunch of collada file names.
int i = 0
function load() {
     var loader = new ColladaLoader();
     loader.load(names[i], function(obj) {
           scene.add(obj.scene)
           i++;
           if (i < names.length)
                load();
     });
}
load();    // Get started.

The symptoms I get (these are terrain tiles) is that the vertices are not updated when the next tile is loaded, while the textures are.

I'm quite new to JS but I assume that the runtime somehow holds a reference to the load() callframe until the asynchronous load calls the callback. Well, it should actually be the callback closure that holds a reference to the outer scope, right, and the runtime just keeps a reference to the callback.

**Comment by BengtGustafsson** [comment]
Ok. I found the older version and with it everything works. Looking at the source it is obvious that the COLLADA object has been moved out of the ColladaLoader function so it is easy to imagine that problems will occur.

**Comment by mrdoob** [comment]
This should be fixed in the (now released) `r74`.

**Comment by rethink-rlinsalata** [comment]
Thanks!

**Comment by BengtGustafsson** [comment]
Hi there,

I have another question:

We load some colladas through colladaloader or colladaloader2, both seem 
to work, but none use the transparency layer of png textures referred to 
from the colladas. Is this some limitation in WebGL or in colladaloader 
or the three.js scene graph? Or is it some rendering quality flag we 
need to turn on, or do you think our material is just messed up?

Den 2016-02-08 kl. 04:59, skrev Mr.doob:
>
> Closed #5721 <https://github.com/mrdoob/three.js/issues/5721>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mrdoob/three.js/issues/5721#event-542463568>.
>

-- 
Bengt Gustafsson
CEO, Beamways AB
Westmansgatan 37
582 16 Linköping, Sweden
+46 (705) 338259
Skype: benke_g
www.beamways.com

**Comment by mrdoob** [comment]
@BengtGustafsson you need to traverse the scene, find the materials that use these transparent pngs and set `material.transparent` to `true`.
