### ISSUE TITLE
Suggestion: Caching texture buffers in WebGLRenderer

### ISSUE THREAD

**Issue by AVGP** [mrdoob/three.js#5728]
I'm working on an application with many different code paths that load textures and I've patched the WebGLRenderer to cache textures also on the GL level, so that `uploadTexture` and `onTextureDispose` use a dictionary to see if a texture has aleady been uploaded or are no longer used, which can reduce VRAM usage and does not need sweeping changes in other parts of the code.

Is that a useful thing for others, too? Or is there side-effects I'm missing / is it too specific to be useful within three.js?

**Comment by WestLangley** [comment]
@Mugen87 Can this be closed?

**Comment by Mugen87** [comment]
I think we should keep it open until its clear what will happen in context of `THREE.Image`. Duplicate texture uploads is still a problem in `three.js`.

**Comment by WestLangley** [comment]
@Mugen87 OK. Thank you for your input.

**Comment by WestLangley** [comment]
>Duplicate texture uploads are still a problem in three.js.

So, let's fix it. This is a core issue and deserves to be addressed. What is the plan? Who has the skills to propose a solution?

**Comment by Mugen87** [comment]
> What is the plan?

The original idea was to add `THREE.Image` as an additional class which is used by `THREE.Texture`. An instance of `THREE.Image` is directly mapped to an instance of `WebGLTexture` (the raw WebGL texture object). That means multiple textures can refer to the same instance of `THREE.Image` and not causing redundant texture uploads anymore. Ideally, `THREE.Image` will make the handling of image objects transparent (e.g. the difference in `HTMLImageElement`, `ImageBitmap` or the image stub in `DataTexture` is encapsulated in this new class).

**Comment by Mugen87** [comment]
One prerequisite for `THREE.Image` is to decouple the actual texture upload from the parameter setting. Everything is currently triggered in `uploadTexture()`. However, when having `THREE.Image` and `THREE.Texture`, both operations needs to be done separately. That means some serious refactoring in `WebGLTextures`. 

Related issue #14375

**Comment by WestLangley** [comment]
@Mugen87 Great answer!  Thanks!

Rather than discussing all of that in this thread, can you open a new issue(s) as a feature request with the stated goals? Then we can assign (or request) someone to have a go at it.

**Comment by Mugen87** [comment]
There you go! #17766

**Comment by Mugen87** [comment]
Closing in favor of #17766.
