### ISSUE TITLE
BufferAttribute getters

### ISSUE THREAD

**Issue by rmarques-realstatus** [mrdoob/three.js#5729]
Hi guys,

Is there a way of getting the xyz coords stored in a BufferAttribute without having to do something like:

    var myObjectIndex = 2;
    var positions = someObject.geometry.getAttribute('position');
    var myPosition =  new THREE.Vector3(positions.array[myObjectIndex*3], positions.array[myObjectIndex*3 + 1], positions.array[myObjectIndex*3 + 2],);

This is kinda verbose... =(

There's already *setXYZ(...)*, and more, that work with *itemSize*. Equivalent getters would be awesome =)

The resulting code would be something like:

    var myObjectIndex = 2;
    var positions = someObject.geometry.getAttribute('position');
    var myPosition = positions.getXYZ(myObjectIndex);

Thank you!

**Comment by dubejf** [comment]
Fixed by #5735.
