### ISSUE TITLE
STLLoader has problem loading some mesh files

### ISSUE THREAD

**Issue by phutidus** [mrdoob/three.js#5734]
I tried to display a mesh using three.js
http://www.thingiverse.com/thing:50174/#files
![Preview of mesh](http://thingiverse-production.s3.amazonaws.com/renders/d0/2c/48/04/9d/right_hand_preview_featured.jpg)

This file can be display on netfabb and meshlab (one of them gave a incorrect STL file warning), but if I use STLLoader to load it, the geometry.faces and geometry.vertices of the loaded content are both empty.

I'm pretty sure this file is in binary format as I've loaded it using a C++ mesh processing library. This file is sized 458876 bytes, but if we use the metadata at the beginning of the file to estimate the size, we get 458784 bytes. 

Looks like the software generating this file added something at the end, causing it to grows larger than expected.

The isBinary() function in STLLoader.js only checks if the actual file size is equal to the number calculated using the metadata, so this file is recognized as ASCII format because of the mismatch of sizes.

I think there's some other way to check if STL file is in binary format?

**Comment by mrdoob** [comment]
Hmm... seems like a separate problem. Could you do a PR for the fix for this issue? I can also try to merge myself if you prefer.

**Comment by Parker-Drouillard** [comment]
This appears to have been solved, I am having the exact same issue currently however. Three.js is not properly categorizing a binary stl file I am attempting to give it. The geometry is read in empty.

The exact same object exported as an ascii stl file loads in fine

**Comment by WestLangley** [comment]
@Parker-Drouillard If possible, please post a bug report and include the sample file.

**Comment by Parker-Drouillard** [comment]
Thanks for the quick response.

I'm actually having issues with all binary files in general currently.

I'll do some more investigating to see if I am doing something wrong. If it isn't the binary STL file given in the sample/example then it does not work for me.
