### ISSUE TITLE
Feature : Glow/Emissive map to MeshPhongMaterial

### ISSUE THREAD

**Issue by Baccanno** [mrdoob/three.js#5796]
What about adding an emissive map feature in the core meshPhongMaterial ? I'm pretty sure it's useful for a lot of people and it's a regular feature of 3D renderers to have an glow/emissive map.

I'm trying to create a patch and was inspired by this issue on stackoverflow :

http://stackoverflow.com/questions/23717512/three-js-emissive-material-maps

So I started modding files such as MeshPhongMaterial, ShaderChunk, UniformsLib, Planning to do a fork and a push request afterward everything was set ... However I'm stuck now, I guess I'm missing something in the WebGLREnderer for it to take into account both color and texture parameters

I initialize my material this way:

	material.glowMap = someTexture;
    material.defines = {
        USE_GLOWMAP: true
    };
    material.needsUpdate = true;

THere is no bug but everything is black on my material, glowMap and glowColor values are not set in the shader (tested with firefox shader editor, the equation is not good at all its just to test if values are here) :

        gl_FragColor.xyz = texelColor.xyz * glow * glowColor; // BLACK
        gl_FragColor.xyz = texelColor.xyz * glow ; // BLACK
        gl_FragColor.xyz = texelColor.xyz * glowColor ; // BLACK
        
        gl_FragColor.xyz = texelColor.xyz; // color

This is what I added progressively :

In MeshPhongMaterial Contructor and Clone

    this.glowMap = null;
    this.glowColor = new THREE.Color( 0xffffff );

The shader chunks and uniforms

    THREE.ShaderChunk["glowmap_fragment"] = [
        "#ifdef USE_GLOWMAP",
        "	float glow = texture2D(glowMap, vUv).x;",
        "	gl_FragColor.xyz = texelColor.xyz * glow * glowColor;",
        "#endif"
    ].join("\n");

    THREE.ShaderChunk["glowmap_pars_fragment"] = [
        "#ifdef USE_GLOWMAP",
        "   uniform sampler2D glowMap;",
        "   uniform vec3 glowColor;",
        "#endif"
    ].join("\n");

	
	THREE.UniformsLib[ "glowmap" ] = {
            "glowMap"  : { type: "t", value: null},
            "glowColor": {type: "v3", value: new THREE.Color( 0xffffff )}
    };

Did a new phong shader

    THREE.ShaderLib.phong = {

            uniforms: THREE.UniformsUtils.merge( [

                THREE.UniformsLib[ "common" ],
                THREE.UniformsLib[ "bump" ],
                THREE.UniformsLib[ "normalmap" ],
                THREE.UniformsLib[ "fog" ],
                THREE.UniformsLib[ "lights" ],
                THREE.UniformsLib[ "shadowmap" ],
                THREE.UniformsLib[ "glowmap" ],

                {
                    "ambient":   {
                        type:  "c",
                        value: new THREE.Color( 0xffffff )
                    },
                    "emissive":  {
                        type:  "c",
                        value: new THREE.Color( 0x000000 )
                    },
                    "specular":  {
                        type:  "c",
                        value: new THREE.Color( 0x111111 )
                    },
                    "shininess": {
                        type:  "f",
                        value: 30
                    },
                    "wrapRGB":   {
                        type:  "v3",
                        value: new THREE.Vector3( 1, 1, 1 )
                    }
                }

            ] ),

            vertexShader: [

                              "#define PHONG",

                              "varying vec3 vViewPosition;",
                              "varying vec3 vNormal;",

                              THREE.ShaderChunk[ "map_pars_vertex" ],
                              THREE.ShaderChunk[ "lightmap_pars_vertex" ],
                              THREE.ShaderChunk[ "envmap_pars_vertex" ],
                              THREE.ShaderChunk[ "lights_phong_pars_vertex" ],
                              THREE.ShaderChunk[ "color_pars_vertex" ],
                              THREE.ShaderChunk[ "morphtarget_pars_vertex" ],
                              THREE.ShaderChunk[ "skinning_pars_vertex" ],
                              THREE.ShaderChunk[ "shadowmap_pars_vertex" ],
                              THREE.ShaderChunk[ "logdepthbuf_pars_vertex" ],

                              "void main() {",

                              THREE.ShaderChunk[ "map_vertex" ],
                              THREE.ShaderChunk[ "lightmap_vertex" ],
                              THREE.ShaderChunk[ "color_vertex" ],

                              THREE.ShaderChunk[ "morphnormal_vertex" ],
                              THREE.ShaderChunk[ "skinbase_vertex" ],
                              THREE.ShaderChunk[ "skinnormal_vertex" ],
                              THREE.ShaderChunk[ "defaultnormal_vertex" ],

                              "	vNormal = normalize( transformedNormal );",

                              THREE.ShaderChunk[ "morphtarget_vertex" ],
                              THREE.ShaderChunk[ "skinning_vertex" ],
                              THREE.ShaderChunk[ "default_vertex" ],
                              THREE.ShaderChunk[ "logdepthbuf_vertex" ],

                              "	vViewPosition = -mvPosition.xyz;",

                              THREE.ShaderChunk[ "worldpos_vertex" ],
                              THREE.ShaderChunk[ "envmap_vertex" ],
                              THREE.ShaderChunk[ "lights_phong_vertex" ],
                              THREE.ShaderChunk[ "shadowmap_vertex" ],

                              "}"

                          ].join( "\n" ),

            fragmentShader: [

                                "uniform vec3 diffuse;",
                                "uniform float opacity;",

                                "uniform vec3 ambient;",
                                "uniform vec3 emissive;",
                                "uniform vec3 specular;",
                                "uniform float shininess;",

                                THREE.ShaderChunk[ "color_pars_fragment" ],
                                THREE.ShaderChunk[ "map_pars_fragment" ],
                                THREE.ShaderChunk[ "alphamap_pars_fragment" ],
                                THREE.ShaderChunk[ "lightmap_pars_fragment" ],
                                THREE.ShaderChunk[ "envmap_pars_fragment" ],
                                THREE.ShaderChunk[ "fog_pars_fragment" ],
                                THREE.ShaderChunk[ "lights_phong_pars_fragment" ],
                                THREE.ShaderChunk[ "shadowmap_pars_fragment" ],
                                THREE.ShaderChunk[ "bumpmap_pars_fragment" ],
                                THREE.ShaderChunk[ "normalmap_pars_fragment" ],
                                THREE.ShaderChunk[ "specularmap_pars_fragment" ],
                                THREE.ShaderChunk[ "logdepthbuf_pars_fragment" ],
                                THREE.ShaderChunk[ "glowmap_pars_fragment" ], //added this

                                "void main() {",

                                "	gl_FragColor = vec4( vec3( 1.0 ), opacity );",

                                THREE.ShaderChunk[ "logdepthbuf_fragment" ],
                                THREE.ShaderChunk[ "map_fragment" ],
                                THREE.ShaderChunk[ "alphamap_fragment" ],
                                THREE.ShaderChunk[ "alphatest_fragment" ],
                                THREE.ShaderChunk[ "specularmap_fragment" ],

                                THREE.ShaderChunk[ "lights_phong_fragment" ],

                                THREE.ShaderChunk[ "lightmap_fragment" ],
                                THREE.ShaderChunk[ "color_fragment" ],
                                THREE.ShaderChunk[ "envmap_fragment" ],
                                THREE.ShaderChunk[ "shadowmap_fragment" ],

                                THREE.ShaderChunk[ "glowmap_fragment" ], //added this in order for glow to be on top of everything, shadow, etc ..

                                THREE.ShaderChunk[ "linear_to_gamma_fragment" ],

                                THREE.ShaderChunk[ "fog_fragment" ],

                                "}"

                            ].join( "\n" )

        }

and here is the THREE.js diff for the WebGLRenderer

	diff --git a/javascripts/3d/three.js b/javascripts/3d/three.js
	index 636b15d..15bfa00 100644
	--- a/javascripts/3d/three.js
	+++ b/javascripts/3d/three.js
	@@ -21872,6 +21872,9 @@ THREE.WebGLRenderer = function ( parameters ) {
	 			specularMap: !! material.specularMap,
	 			alphaMap: !! material.alphaMap,
	 
	+			glowMap: !! material.glowMap,
	+			glowColor: !! material.glowColor,
	+
	 			vertexColors: material.vertexColors,
	 
	 			fog: fog,
	@@ -22310,6 +22313,12 @@ THREE.WebGLRenderer = function ( parameters ) {
	 
	 		}
	 
	+		if ( material.glowMap ) {
	+
	+			uniforms.glowMap.value = material.glowMap;
	+			uniforms.glowColor.value = material.glowColor;
	+
	+		}
	 		// uv repeat and offset setting priorities
	 		//  1. color map
	 		//  2. specular map

**Comment by dubejf** [comment]
Fixed by #6743.
