### ISSUE TITLE
IE11 will crash when run a specific sample.

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#5813]
If you run the following sample IE11 will crash.

Three.js parallax mapping 
http://threejs.org/examples/#webgl_materials_parallaxmap

I think the following is causing.
[js/ParallaxShader.js]
> for ( int i = 0; i == 0; i += 0 ) {

more information:
IE11 will crash when run a specific sample of the three.js. 
https://connect.microsoft.com/IE/Feedback/Details/1063833

**Comment by dubejf** [comment]
The loop header can be replaced by `for ( int i = 0; i >= 0; i += 1 ) {` to avoid crashing.

However, all the modes render a black screen, except 'basic'.

It seems like this loop never converges: https://github.com/mrdoob/three.js/blob/master/examples/js/shaders/ParallaxShader.js#L86-92. I'm not sure what's missing but IE11 is not equipped to run this shader.

There are some warnings in Chrome (Windows) too but the demo works.

**Comment by benaadams** [comment]
@dubejf https://www.khronos.org/webgl/public-mailing-list/archives/1503/msg00028.html

**Comment by dubejf** [comment]
Thanks @benaadams, very helpful! I guess that IE11 really insists on unrolling loops!

**Comment by dubejf** [comment]
Fixed by #6769.

**Comment by cx20** [comment]
Thanks!
