### ISSUE TITLE
Possible support to add more than one material while using MeshFaceMaterial

### ISSUE THREAD

**Issue by sahilshekhawat** [mrdoob/three.js#5825]
I wanted that wireframe and surfaces are displayed together. I know about WireframeHelper but I want to do that on a per-polygon basis and am using MeshFaceMaterial. So, the issue is that I can only pass one material to MeshFaceMaterial  (at a index) and thus either wireframe or surface can be displayed but not both.
I think WireframeHelper or a similar implementation can be used or an array of materials should be allowed to pass instead of a single material or there must be an option to display wirefrae and surface together on a per polygon basis. . Its a commonly required feature.
If this thing is already implemented then I am really sorry but I have tried a lot but couldn't find a way. 
Thanks

**Comment by fallenartist** [comment]
Wasn't handling of multiple materials planned in `MeshLayerMaterial`? I wonder if this useful feature is still in the roadmap?

**Comment by WestLangley** [comment]
Multiple-materials on the same triangles are supported using geometry groups:
```js
geometry.addGroup( start, count, 0 );
geometry.addGroup( start, count, 1 );
```
