### ISSUE TITLE
Morphing for Lines as well as Meshes

### ISSUE THREAD

**Issue by ajdunlap** [mrdoob/three.js#5826]
Currently there is support for using the `morphTargets` property of a `Geometry` and the `morphTargetInfluences` property of the corresponding `Mesh` to animate `Mesh`es. It would be nice if one were able to use a similar interface to animate `Line`s - I don't think this is currently possible; at least it doesn't seem to be documented.

**Comment by Mugen87** [comment]
Duplicate of #2875
