### ISSUE TITLE
Skeletal export malfunction

### ISSUE THREAD

**Issue by Soelen** [mrdoob/three.js#5829]
so I made some tests about three.js cababilities to animate a model, as far as i can see the bone skeletal animation is working like a gem and you can even export several actions

but it appeared something interesting yet unfortunate happened; either I am using the wrong three.js animation class or the export is not intended, let me explain me by showing some screenshots:

in the first screenshot you can see my blenderfile, I create a catepillar for testing purposes, you can see that I created 2 actions : walk and stayUp:

![raupe](https://cloud.githubusercontent.com/assets/1114549/5607647/93c06fcc-9463-11e4-9ef3-1ea6c06da171.png)

those are bone bases animations. In the next screenshot you will see 2 shake-key animations, one is being called blink and the other chin:

![shape-key](https://cloud.githubusercontent.com/assets/1114549/5569499/e23f95f2-8f71-11e4-8d4f-9830b806f467.jpg)

if I export this model, the three.js json exporter exports all 4 animations:

![json](https://cloud.githubusercontent.com/assets/1114549/5569508/0f2efc38-8f72-11e4-8f3d-67f20fe33dee.jpg)

as you can see the first 2 elements in this array are the shapekey animations.

So I am able to animate all bone based animations as soon as the model has been loaded with:

walk = new THREE.Animation( mesh, geometry.animations[3] );
walk.play();

but if I try to play a shape-key animation, nothing is happening:

blink = new THREE.Animation( mesh, geometry.animations[0] );
blink.play(); //nothing

At the moment I am simply assuming the animaton export is not intended to also export shape key animations. Am I correct with my assumption? And if not, is there a way to playback shapekey animations as well?

Thanks in advance!

Edit: here an example how the bone animation is looking like:

http://gearhead.noip.me/three.js/blender-bone-animation/

here the json export in case someone is interesting to take a look how this looks like:

http://gearhead.noip.me/three.js/blender-bone-animation/raupe.json

as well as the correspodent blender file:

http://gearhead.noip.me/three.js/blender-bone-animation/raupe.blend

**Comment by Soelen** [comment]
@mrdoob first off, it is a honor to talk to you mrdoob, been keeping up your amazing work for years : P

Well I did as you suggested, it took me a bit time to respond since I wasn't sure what to do with it, sorry.

So as far as I read from the readme this exporter in the development repository has been completely rewritten, I guess it had its reasons why. But as far as I can tell, at least for animation exports, the new exporter has losts its ability to export more than just one action or the development hasn't reached the point yet to make this possible : ( I really appreciated this feature in the older exporter.

Moreover, I don't see any difference for the morphtarget part, it still simply exports the whole timeline.

@repsac it certainly is not : P but on the other hand, there is also the possibility that I'm formatting my animations wrong for the export (for example, maybe I'm supposed to use the NLA editor in blender to composite animations or something).

Would it help if I would check out how to export shapekeys as morphtarget animations? I'm a bit experienced with bpy!

Thanks in advance!

**Comment by repsac** [comment]
So it sounds it like it unclear the real source of the problem (exporter, `three`, or work flow in general). The logic for extracting the animation information was copied over from the old exporter and it is possible that a line of code or two was left out in the migration process. 

I am currently working on https://github.com/mrdoob/three.js/issues/5841so have not been able to actually look at your issue yet.

Without trying anything yet, or looking at your scene, I would think that shape keys should be handled as morph targets.

**Comment by crobi** [comment]
> The logic for extracting the animation information was copied over from the old exporter

As noted in #5582, the `master` and `dev` branches diverged since work on the new exporter began, so the two exporters will likely produce different results when exporting animations.

**Comment by repsac** [comment]
@Soelen you may want to follow this thread as well https://github.com/mrdoob/three.js/issues/5582#issuecomment-70043430
