### ISSUE TITLE
Possible Bug With Normal Maps Regarding Viewing Angle

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#5839]
I'm not sure if this is intentional or not, but the effect of the normal map is inverted when looking at it from the opposite angle.

The top image is incorrect (inverted), the bottom image is viewed from a 180 camera rotation difference.

![normal_incorrect](https://cloud.githubusercontent.com/assets/6549763/5591554/bd8633d4-912d-11e4-9c61-e71e7dd82d52.jpg)
![normal_correct](https://cloud.githubusercontent.com/assets/6549763/5591555/c0ee408e-912d-11e4-814a-4e617ec73090.jpg)

**Comment by WestLangley** [comment]
If you can demonstrate a three.js bug, can you provide a (simple) test case so we can reproduce your results?

Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by titansoftime** [comment]
Sorry 'bout that.

http://www.titansoftime.com/normaltest.html

**Comment by titansoftime** [comment]
I changed the texture to jpg to rule out an issue with dds.

**Comment by WestLangley** [comment]
It is difficult for me to see what you are talking about. Perhaps you can remove the repeat settings...

...and provide an annotated image to point out the problem. See "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

Also, read https://github.com/mrdoob/three.js/issues/5662#issuecomment-64068423

**Comment by titansoftime** [comment]
I am using THREE r69 unmodified, an nvidia geforce GTX 650, windows 7 ultimate 64 bit and chrome 39.0.2171.95 m.

I chose those repeat values intentionally as they make the issue most apparent.

I tried the "solution" in #5662 of making the second parameter of the normal scale vector negative, this does not work, it only inverts the problem (where currently the camera at 0,600,600 looks fine and after at 0,600,-600 looks fine).

Here is a annotated screenshot of the example:

![detailednormalmap](https://cloud.githubusercontent.com/assets/6549763/5592911/e98d49cc-91af-11e4-804d-84642cf1fe9b.jpg)

**Comment by titansoftime** [comment]
Someone else is having the same issue: http://stackoverflow.com/questions/27734812/three-js-normals-not-correct

**Comment by WestLangley** [comment]
> Someone else seems to be having a similar issue

That SO question has nothing to do with this issue.

After spending several hours on this, I have not been able to find a problem here -- or see what you claim to see.

Perhaps your eye is tricking you?

**Comment by titansoftime** [comment]
My eyes are definitely not playing tricks on me heh.

Can you see the difference in the screenshot? To me it is very clear that the normal map protrusion is inverted. When you click the "Toggle Camera" button in my example, you really can't see the normal map effect invert?

I've tested multiple devices/browsers and I get the same results.

Regarding the SO question it was the following statement that I saw, that I must have misinterpreted:
> In front of the camera, the normal detection seems correct, but as soon as I rotate the mesh, the normal detection is not good.

Is anyone else not seeing the difference?

**Comment by mrdoob** [comment]
Can you try moving the light in the Toggle too?

**Comment by titansoftime** [comment]
http://www.titansoftime.com/normaltest.php?movelight=1

This solves the problem on paper, but in practice not so much. I can't have the directional light mimic a players rotation, that would look really wierd.

**Comment by WestLangley** [comment]
[Here](https://dl.dropboxusercontent.com/u/63997063/Three/Temp/so.normal.map.view.angle.html) is my testbed. It uses `OrbitControls`.

**Comment by titansoftime** [comment]
The only time it looks correct is with the blue line facing you. Is this the expected behavior of three.js?

**Comment by bhouston** [comment]
@titansoftime I recreated it in Clara.io and the normal map in ThreeJS works properly with directional lights: https://clara.io/view/5029a6d6-5e7d-45e1-b415-4ce129f880bf/webgl

**Comment by titansoftime** [comment]
@bhouston In your example it works perfectly. If I'm not mistaken Clara.io (which is really cool btw) uses a custom version of Three.js right?

**Comment by bhouston** [comment]
@titansoftime I didn't modify how normal mapping nor how directional lights work.

**Comment by titansoftime** [comment]
So I wonder than why @bhouston, it works fine in your example and not in mine or @WestLangley's example

**Comment by bhouston** [comment]
@titansoftime: It sort of looked like it was working in WestLangley's example to my eyes.

**Comment by WestLangley** [comment]
> My eyes are definitely not playing tricks on me

There is no way to know that. : - )

I, too, believe it is working correctly in @WestLangley's example.

**Comment by titansoftime** [comment]
> There is no way to know that. : - )
Touché...lol

West, that example is doing the same thing mine is. Not that it carries much weight with you guys but my co-workers (also programmers) also agree that when looking at your plane at default position the dirt mounds go "down" and when viewed from the opposite angle the dirt goes up like mounds.

When I get home from work I will make screenshots.

I'M NOT CRAZY!!! lol =]

**Comment by titansoftime** [comment]
As promised:

![wlexample](https://cloud.githubusercontent.com/assets/6549763/5600832/09505fc4-92aa-11e4-89f1-e0dae354205d.jpg)

**Comment by bhouston** [comment]
It looks to me as if the light is pointing in opposite directions in those two screen shots.  I don't think it is a ThreeJS bug.

**Comment by titansoftime** [comment]
The light is pointing in the same direction, the camera is at a different position. If this is the way it is supposed to work I will gladly close this. I am getting so sick of that grass texture, as i am sure you all are as well.

The way I would expect this to work is in a way where the normals would reflect light in the same direction regardless of camera position. I still don't understand why changing the camera position/rotation would effect which direction the light appears to reflect. If I'm looking at a hole in the ground it should look like a hole no matter what side of it I'm on.

So, is this the way it is supposed to work?

**Comment by WestLangley** [comment]
Do you see the same problem in [this second test](https://dl.dropboxusercontent.com/u/63997063/Three/Temp/so.normal.map.view.angle%202.html)?

**Comment by titansoftime** [comment]
He, if my eye's weren't playing tricks on me, they are now lol.

In your second test it appears to me that the normals are more consistent throughout the viewing rotation. Though now it seems to me like the dirt is a mound from all directions. I wonder if the 2nd normal scale vector was to be negative in this test?

**Comment by WestLangley** [comment]
What you are seeing is an illusion, IMHO.

The shadows appear correct, and that is the important thing.

**Comment by titansoftime** [comment]
I am beginning to agree with you. I am also feeling insane.

Closing for the sake of everyone's sanity.

**Comment by mrdoob** [comment]
Yeah. Basically, your eyes are expecting some height in the dirt. With parallax mapping the inversion illusion you see wouldn't be there because the shadow will be hidden by the height of the dirt. But the result that normal mapping is doing is correct. As correct as such technique can produce.

**Comment by titansoftime** [comment]
Well...I feel like an idiot =]
