### ISSUE TITLE
Blender exporter option to remove global transforms

### ISSUE THREAD

**Issue by Densaugeo** [mrdoob/three.js#5841]
The Blender exporter automatically bakes global transforms into meshes, but sometimes I need to export models without applying their global transform. Mostly, this is for exporting several separate models from the same Blender project.

Right now this can be done by commenting out lines 1,617 and 1,618 in export_threejs.py:

```
def extract_meshes(objects, scene, export_single_model, option_scale, flipyz):

    # Other stuff...

            if export_single_model:

                if flipyz:

                    # that's what Blender's native export_obj.py does to flip YZ

                    X_ROT = mathutils.Matrix.Rotation(-math.pi/2, 4, 'X')
                    mesh.transform(X_ROT * object.matrix_world)

                # When these next two lines are commented out, global transform is not applied:
                # else:
                    # mesh.transform(object.matrix_world)

            # More other stuff...

    return meshes
```

I'd like to have this as an option in the export script (similar to the 'flipyz' option). Is this something other people would use, and is it likely to affect other stuff? (The exporter handles a lot of bones and animations and stuff I don't know anything about).

**Comment by repsac** [comment]
That may be doable but will need to be tested against anim/morph scenes. Can't really comment if this would be easy or not. It seems to be one of those things that you just dive into and see what breaks.

fyi: flipyz was removed, I felt that should just be included to compensate for blender's Z up and three's Y up differences

**Comment by kimasendorf** [comment]
My export always ends up distorted, the mesh was modeled directly in Blender. When I remove the Armature Modifier before the export (that works well in the r69 exporter) than I get some errors.

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
