### ISSUE TITLE
UVGenerator and general documentation in Three.js

### ISSUE THREAD

**Issue by BjornMoren** [mrdoob/three.js#5845]
I'm trying to implement a UVGenerator, since shape geometries don't work together with bitmap textures in Three.js. But I keep failing, although this is should be trivial.

I think UVGenerator can stand as an example of what is wrong with the Three.js project. The source code has zero comments (the WorldUVGenerator class). Ok, it looks trivial, but trivial to who? Only to the authors of the code. Browsing the Three.js source code in general, I am shocked by how little comments there are. Since documentation is missing, then at least the source code should be heavily commented. A skilled programmer always writes comments in the code, as he types it in, right?

And nowhere can there be found a general explanation of the general design of this API. Why is it the way it is? What compromises were made? It all comes down to guess-work how it should be used, best practices etc. Lots of examples are provided, but what do they really tell about the architecture of the API?

Yes, of course, this is a free API, and non profit, etc, I get it, so maybe I should stop complaining. But is this API really USEFUL? Now I have spent two weeks coding, and hit my head so many times on missing features and poor documentation, that I wonder if it would not have been easier to start from scratch and write my own API on top of WebGL. I'd rather have a much smaller, less feature rich API that is really well documented, than this.

I hope this doesn't come off too harsh, but I really wonder about the coding practices of the core members of this team.

**Comment by mrdoob** [comment]
> A skilled programmer always writes comments in the code, as he types it in, right?

The problem is that we're not skilled programmers I guess.

> And nowhere can there be found a general explanation of the general design of this API.

Yep. Still figuring it out.

> Now I have spent two weeks coding, and hit my head so many times on missing features and poor documentation, that I wonder if it would not have been easier to start from scratch and write my own API on top of WebGL.

Sorry for wasting your time.

> I'd rather have a much smaller, less feature rich API that is really well documented, than this.

I think you just found your solution.

**Comment by BjornMoren** [comment]
From the sarcastic tone I can see that I really pissed you off, which was not my intention, so I apologize for being rude.

My bigger point is that a lot of these code libraries could get a lot more spread by being more user friendly. I have discarded many libraries in the past, because it is just too time consuming to try and follow the author's line of thought, so I end up coding my own. Which is a waste of time for both people. I think I spent about half of the coding time trying to figure out why the Three.js API didn't work like intended, which is pretty frustrating.

It seems like too many people start writing code for their super library with the attitude that documentation is something someone else can do later, or that smart coders don't need documentation because they can look directly in the code, or that "we haven't finalized the API yet, so why waste time?" I think this is a mistake, and it comes at a cost. Everyone benefits from documentation right from the start of the project: new members can get up and running quicker, existing members remember all the details better, it is easier to get an overview of the project to see if big architectural changes should be done, more people with be attracted to the project, etc.

Anyways, good luck with Three.js (in a sincere tone).

**Comment by mrdoob** [comment]
Consider the fact that too many people is already using/contributing to the library for the manpower available. Doing things in a less accessible/documented way helps with keeping all this manageable. Whenever things get more stable/clean we will be able to think about making things more accessible.

**Comment by zz85** [comment]
Code itself is documentation, so is history from commit messages, [discussions](https://github.com/mrdoob/three.js/search?q=UVGenerator&type=Issues&utf8=%E2%9C%93), etc.

Not saying what we have is perfect, but it would definitely benefit if more (like yourself) contributes constructively.

There will always be trade offs, so everyone does need to pick their poison (although it's something not that bad to reimplement things)
