### ISSUE TITLE
Loader files should be out of "example" folder

### ISSUE THREAD

**Issue by BrodaNoel** [mrdoob/three.js#5850]
Hi all!
I need to use the OBJMTLLoader.js file.
I downloaded the .zip with the "mrdoob-three.js-ca14c79" folder inside, and, when I find the OBJMTLLoader.js file, it was into the "example" folder.
Why is that?
When I download a library, the first step is "remove the example folder".

Should this files be into the src or build library?!.
I can't feel confident with this file if it is into the example folder. It sound like: "This is just an example, don't use it".

Should I use the /examples/js/loaders/OBJMTLLoader.js on my website?

See you!

**Comment by mrdoob** [comment]
If all the loaders where in src, three.min.js would end up being 2mb+.

**Comment by mrdoob** [comment]
> I can't feel confident with this file if it is into the example folder. It sound like: "This is just an example, don't use it".

That's a strange way of thinking about examples by the way.

**Comment by BrodaNoel** [comment]
Ok. So. If need yo use the OBJLoader, I should take it from the /examples/js/ folder. Isn't it?

Thanks. And Sorry for my english

See you!

Noel

Firma Automática:
Mail enviado desde mi teléfono móvil. Disculpe los errores y el formato.

**Comment by mrdoob** [comment]
Yep!
