### ISSUE TITLE
The renderer's memory info is incorrect.

### ISSUE THREAD

**Issue by Verhoef-W** [mrdoob/three.js#5852]
Hi,

I encountered the following bug.

When using the Three.js library, I think I created a memory leak. For diagnosing I tried using
`this.renderer.info['memory']['geometries']`, where `this.renderer` is a `THREE.WebGLRenderer`. `this.renderer.info['memory']['geometries']` outputted an increasingly *negative* amount of geometries. After commenting out all the `.dispose()` calls of geometries it did not indicate a negative amount of geometries anymore.

I do not know exactly how to make a minimal working example for reproducability since I'm using it in an application that is pretty big. I hope this gives enough information. If you need more information, ask me.

**Comment by WestLangley** [comment]
Can you try the development version? Can you try to create a test case so we can reproduce your results? Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by Verhoef-W** [comment]
Thank you for your reaction. It turned out the bug was already solved in the development branch. The reported number of geometries is correct now as far as I know. After looking more carefully through the submitted issues, I found that the bug was already submitted in #5680. Sorry!
