### ISSUE TITLE
cloud demo slow in IE 11. Any update to last version ?

### ISSUE THREAD

**Issue by jcorreia** [mrdoob/three.js#5853]
Hi,
I was checking and evaluating tree.js with the amazing demo of the clouds in http://mrdoob.com/#/131/clouds but it is extremely slow in IE 11. In firefox it renders fine.

I´ve noticed the version in the demo is pretty old, so I wonder if it runs better with latest version, and if there is any new version or an update. ?

thanks!

**Comment by mrdoob** [comment]
If it's slow in IE but is not in Firefox you should send this to Microsoft.

**Comment by jcorreia** [comment]
Hi,
Thanks for your answer and excellent work :)

I thought this could be related to an old version of treejs. I think that IE 11 didn´t even exist by the time.
Don't you think it could improve with the latest version of threejs, or it doesn't matter ? Is there a new demo version ?

**Comment by jcorreia** [comment]
Yeah,,Im pretty sure they will listen to me :)

I guess the answers to my question, is that the new version will not improve performance of clouds demo....

thanks

**Comment by mrdoob** [comment]
Am I wrong thinking that you're hoping to reuse a personal project of mine (which should be assumed to have copyright) and asking if I have updated it to the latest version or how to fix the performance issue on IE?

**Comment by jcorreia** [comment]
Hi mrdoob,
yes you are wrong :)
I´m evaluating treejs and other frameworks and I need it to work in IE11. 

Clouds demo is an example of it, and I thought if it has performance issues in IE I might have other problems with this framework.

I´m trying to do an organizational chart.

Anyway I didnt even know it didnt belong to the treejs demos. If I wanted to steal would I came by and ask you ? :) 

Relax man, you are too aggressive to someone to have just arrived. All I asked was to have some support from an open source project.

Keep the good work.
