### ISSUE TITLE
THREE.TrackballControls bug encountered when domElement is scrolled inside a containing element

### ISSUE THREAD

**Issue by klebba** [mrdoob/three.js#5856]
Example: http://codepen.io/klebba/pen/wBomgO?editors=001

It seems that `this.screen.left` and `this.screen.top` need to be updated if the domElement is scrolled inside a containing element. A more robust technique for determining the domElement position inside `getMouseProjectionOnBall` might be better. For what it's worth I didn't see this issue with OrthographicTrackballControls.

**Comment by mrdoob** [comment]
Why don't you pass `renderer.domElement` to `TrackballControls` instead?

**Comment by klebba** [comment]
Pen updated: http://codepen.io/klebba/pen/wBomgO?editors=001 -- the bug persists

**Comment by cwoolum** [comment]
@mrdoob , you are a genius!

**Comment by Mugen87** [comment]
I'm unable to reproduce the issue with the latest version of `three.js` and `TrackballControls`.

`getMouseProjectionOnBall()` was removed some time ago with #6123.
