### ISSUE TITLE
Blender scene export not supported

### ISSUE THREAD

**Issue by namelivia** [mrdoob/three.js#5859]
Hello, I was trying to export a whole blender scene (objects, geometries and specially the camera placement) using the json export plugin and then import everything in a three.js scene.

After some time reading and trying things I've come to the conclusion that this should be done using ObjectLoader.load, however this fails. I've started tracing the error and inspecting this function's code and it seems that is expecting something sustantially different from the output produced by the plugin. Arrays instead of Objects in some places, uuid fields, and so on. I've tried to make some quick fixes but the structure is quite different.

Am I right or I'm doing something wrong when exporting/importing?
I could try to fix the plugin myself but maybe it's too much difficult for me.

Thanks

**Comment by repsac** [comment]
It sounds like you are still using the old exporter. There is a new exporter in the dev branch that is designed to work with ObjectLoader. Please give that a try.

**Comment by namelivia** [comment]
Oh Thanks! 
You are already working on it, I'm giving it a try.

**Comment by namelivia** [comment]
The new exporter works like a charm! 
Thank you very much!
