### ISSUE TITLE
math/quaternion.js: missing calls to onChangeCallback()

### ISSUE THREAD

**Issue by ghost** [mrdoob/three.js#5860]
The `slerp` function at https://github.com/mrdoob/three.js/blob/dev/src/math/Quaternion.js#L400 has two cases where the quaternion is modified and the function returns without calling `onChangeCallback()`: 
- at https://github.com/mrdoob/three.js/blob/dev/src/math/Quaternion.js#L433
- at https://github.com/mrdoob/three.js/blob/dev/src/math/Quaternion.js#L447

The last return of this function does call `onChangeCallback()`.

I am not entirely sure if this is to be considered a bug or not. No issue reports to this effect are currently open but it feels like an inconsistency. Just pointing it out as I ran into it while reading the code.

**Comment by mrdoob** [comment]
Oh! Nicely spotted!

**Comment by WestLangley** [comment]
> Fixing this might have some unforeseen consequences for all code using this lib

Not really. The code paths with the omission are edge cases that almost never occur. Furthermore, three.js is quaternion-based, and the Euler vector is not being used by the internals of the library.

That being said, the `Quaternion.slerp()` method looks like it could use a rewrite.

Thank you for pointing out the omission.

**Comment by WestLangley** [comment]
Sorry this was overlooked. Fixed in #16899.
