### ISSUE TITLE
TriangulateShape error on specific geometry

### ISSUE THREAD

**Issue by kriffe** [mrdoob/three.js#5861]
I have found a math error in the triangulation module that causes the function triangulateShape to fail for very specific geometries.

I have created an isolated example on jsFiddle with the computed coordinates that cause the triangulation failure: http://jsfiddle.net/kriffe/m4ren2dz/

An screenshot of contours of geometry: http://www.realglitch.com/test/Contours_for_failing_geometry.PNG

Small adjustments of the nodes (round< 1e-5) resolves the issue as a workaround. Perhaps a check function with problems handling very exact 45deg lines?

Discovered on Chrome 39.0.2171.95 but repeated on firefox and both in Ubuntu 14.04 and Windows 8.1.

**Comment by mrdoob** [comment]
Have you tried with @jahting's pnltri?
http://threejs.org/examples/#webgl_geometry_text2

**Comment by kriffe** [comment]
No I wasn't aware of that extension. I tested it right away in JSfiddle
without any errors. Will make some further tests with it later in my larger
project.

Is this an intended future replacement for the old triangulate function in
THREE.js, or just an interesting alternative?

Thanks for the quick reply.

Best regards
Kristofer

2015-01-07 12:25 GMT+01:00 Mr.doob <notifications@github.com>:

**Comment by mrdoob** [comment]
We may replace the old triangulator with this :)
