### ISSUE TITLE
Skinning a MeshNormalMaterial

### ISSUE THREAD

**Issue by willy-vvu** [mrdoob/three.js#5867]
It seems that skinning does not work when using `THREE.MeshNormalMaterial` or `MeshDepthMaterial`, but it does with `THREE.MeshBasicMaterial`. Should skinning work across all these materials, or is there a reason those materials are exempt from skinning?

**Comment by mrdoob** [comment]
I think it should work.

**Comment by willy-vvu** [comment]
Here's a jsfiddle.
http://jsfiddle.net/g1nkxsq4/1/

**Comment by WestLangley** [comment]
@willy-vvu I think @mrdoob is saying that the materials should be modified to support skinning.

**Comment by mrdoob** [comment]
Hah. Yeah! Sorry, I wasn't too clear :)

**Comment by willy-vvu** [comment]
@westlangley Thanks for the clarification!
I'm not too familiar with the internals of the three.js rendering engine, but if I were, I would definitely submit a pull request with the fix. For now, I can easily use MeshBasicMaterial instead.
I'm about to draft another issue about Blender's animation exporter. It'll hit the issues section soon.

**Comment by Mugen87** [comment]
Both `MeshNormalMaterial` and `MeshDepthMaterial` support skinning and morphing now. I've update the fiddle to `R89`.

https://jsfiddle.net/g1nkxsq4/19/
