### ISSUE TITLE
What should Three.JS do when MAX_FRAGMENT_UNIFORM_VECTORS exceeded?

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#5869]
What should Three.JS do when someone creates more lights than can be supported by the current GPU's MAX_FRAGMENT_UNIFORM_VECTORS?  According to the WebGL specification, the minimum allowable value for MAX_FRAGMENT_UNIFORM_VECTORS, is 16.  That is 16 values unpacked (and I understand one should assume that these remain unpacked for most cases.)  Each of these minimum 16 values can be a float, vec2, vec3 or vec4.

Three.JS's lighting system, for example, uses [6 values for the SpotLights](https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/UniformsLib.js#L67), which means that on the minimum viable GPU's that support WebGL, they can not even support 3 spot lights (18 values, excluding everything else.)

Should we try to come up with a strategy when dealing with low capability WebGL GPUs rather than the current approach of crashing during program linking?

Here are some thoughts:

- We could limit the number of lights based on the MAX_FRAGMENT_UNIFORM_VECTORS value so that it will not crash.  We could either use the closes lights to an object, or lights closer to an object than Light.distance, or just arbitrary limit the number of lights, or we could turn off lighting all together when the limit is reached (and just to ambient.)

- We could pack together values for the lights so that we do not use a whole potential vec4 VALUE slot for a single floating point value (thus we could pack together ```spotLightDistance```,```spotLightAngleCos```, and ```spotLightExponent``` into a single value, rather than taking up 3 separate rows.)

- Switch into a multi-pass/deferred rendering mode to avoid any lighting count limits.  Modern game engines do this.  Lots of work for these low end machines to just run small scenes, but would be amazing for large complex scenes with dozens and dozens of lights.

- Use a data texture for the lighting information?  I think that might work, although it may also not be supported on these low end GPUs.

- We could alternatively do a check somewhere about the maximum number of lights desired in a scene and manually check if they are likely to fix in the GPU's capabilities, and if they don't throw a manual error message.

**Comment by mrdoob** [comment]
I think I would go with the packing idea by now.
Ideally we could also show a nice error in the console too.

**Comment by gero3** [comment]
Discussion continued in #7037
