### ISSUE TITLE
Textures not rendering on certain computers.

### ISSUE THREAD

**Issue by atebit** [mrdoob/three.js#5874]
Have a strange issue that I'm unsure how to debug. Basically, on some computers, the texture isn't making it's way to the graphic card. It's definitely loaded into memory and the mesh is there moving around, however the image isn't being rendered. Totally confusing.

Four computers I'm comparing:
Macbook Pro mid 2011 yosemite (works)
Macbook Pro mid 2014 yosemite (works)
Macbook Air mid 2014 yosemite (some images work) 
HP Chromebook ("same" some images work)

Now the images: some are created in canvas and some are loaded PNGs. It seems so arbitrary.

If you have any ideas, would love to have your help. Also, let me know your paypal email and I'll pay for any help you give.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

Help is free, but make sure you provide your code so the reader knows what you are doing.
