### ISSUE TITLE
Ray.distanceSqToSegment code update?

### ISSUE THREAD

**Issue by froh** [mrdoob/three.js#5877]
`Ray.distanceSqToSegments` was based on some c++ code.  [That code got rewritten](http://www.geometrictools.com/GTEngine/Samples/Geometrics/DistanceSegments3/DistanceSegments3.cpp) to make it numerically robust when the lines are almost parallel.  There is a [detailed rationale whitepaper](http://www.geometrictools.com/Documentation/DistanceLine3Line3.pdf) available.

I stumbled upon this because I'd love to compute the closest distance (squared) and the according points for two _infinite_ rays, not just for a ray and a segment :)  I understand this is a different albeit related issue, so I hope `Ray.distanceSqToRay(...)` might share some code with `distanceSqToSegment`.

**Comment by stephomi** [comment]
Hmmm I don't know if it's easy/good idea to share some code between DistRaySegment and DistRayRay
http://www.geometrictools.com/Source/Distance3D.html#LinearLinear

Plus, there's a lot of combination if you add lines (line/ray, line/line, line/segment)
Honestly I don't know if there is a good way to share some codes between all these methods without sacrificing code performance, maintainability and... robustness.

By the way, distanceSqToSegments cloning at least 3 objects : https://github.com/mrdoob/three.js/blob/master/src/math/Ray.js#L105-L108
If the functions is meant to be called several times, it would be best to allocate variable once and for all (like https://github.com/mrdoob/three.js/blob/master/src/math/Ray.js#L72-L76)

**Comment by froh** [comment]
For the code sharing, there is two steps:  step1:  find the nearest point of the lines.  step2: check if the point is on the ray(s) / section(s).

For the numerical robustness, I found two articles, a long article about [floating point arithmetics](http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html) and a very concise short one about [finding the roots of a quadratic](http://people.csail.mit.edu/bkph/articles/Quadratics.pdf).

For the object cloning I'm not sure I can follow --- it looks to me like the current version _does_ allocate three vector3 objects in a closure.  it could use addvectors and subvectors instead of `clone(v1).sub(v0)` though.

**Comment by stephomi** [comment]
Indeed it has been done, but it wasn't merged in master when I wrote my comment, my bad :)
https://github.com/mrdoob/three.js/commit/616952a3c7c0cfc2f6eb39ea88566cd19ffe55f1

**Comment by WestLangley** [comment]
@froh 

As you know, three.js has no method `Ray.distanceSqToRay()`. And for good reason: the distance between rays is up to interpretation. You will have to create your own method.

Regarding `Ray.distanceSqToSegment()`, do you propose changing the code to correspond to an updated reference? If so, would you be willing to implement it?

**Comment by froh** [comment]
> Regarding Ray.distanceSqToSegment(), do you propose changing the code to correspond to an updated reference? If so, would you be willing to implement it?

scary :-) but ok, I'll give it a try.

Can you have a look at the test case?   If I'm not mistaken the ray and the segment are near parallel and the end points are very close nearby (P0 close to Q0, P1 close to Q1).  The computed distance is ~2, though.

**Comment by WestLangley** [comment]
The example from the paper you implemented involves two line segments -- not a line segment and a ray. You are mis-applying the example.

**Comment by froh** [comment]
thanks for reviewing.  fixed.  (hopefully :) )

**Comment by mrdoob** [comment]
Should this one get closed then?

**Comment by froh** [comment]
no what I fixed, or hope I fixed is the test case.  sorry for the confusion.
