### ISSUE TITLE
Problem with Blender-Export and Normal Map

### ISSUE THREAD

**Issue by PawelRaskolnikow** [mrdoob/three.js#5890]
Hi experts,

i've modeled a little room in blender with two materials, which consist of a diffuse and normal map. After importing the object in my scene via THREE.JSONLoader, i've spotted a little problem with one face. As you can see at the attached picture, it looks like the mentioned face was rendered without a normal map. When i try to change the mesh, so i have additional faces, the error occurs at an other position. The object itself looks in Blender perfectly. Besides, i'm not modifying the geometry and materials in my scene. I'm just doing this:

    loader.load("../assets/object.json", function(geometry, materials) {
        var object = new THREE.Mesh(geometry, new THREE.MeshFaceMaterial( materials ));
    ...

![sample](https://cloud.githubusercontent.com/assets/10518745/5725054/1a36469c-9b50-11e4-9985-939ccd28f2d9.jpg)

THREE.js: Version 69
Browser: Chrome Version 39.0.2171.95 (64-bit)
OS: OS X Yosemite 10.10.1
Graphics: AMD Radeon R9 M295X 4096 MB

I'm currently not able to provide you a link to a live-demo. Is there something else what i can do?

Regards

**Comment by WestLangley** [comment]
It appears one face has undefined ( or zero ) vertex ( or face ) normals. That is something you can check yourself.

Also, please try the dev branch and the new blender exporter.

**Comment by PawelRaskolnikow** [comment]
The new blender exporter didn't help me further, but the dev-version of three.js seemed to fix the issue. I will test with some other models, but i think it's okay now.
