### ISSUE TITLE
renderer.shadowDebug should show shadow maps

### ISSUE THREAD

**Issue by arya-s** [mrdoob/three.js#5896]
Hey,

I poked around shadow mapping and the first thing I usually do when I implement SM myself, is to render the actual depth textures onto a HUD, just to make sure they are as intended, display correct stuff, etc. I think this is the common practice with SM.

When I set renderer.shadowDebug = true,  I expected this behaviour, but instead just the area that the shadow map covers in the scene was colored (I think this is a good feature too tho, so I'm not suggesting removing that).

Any opinions on this?

**Comment by mrdoob** [comment]
This sounds good to me. What do you think @WestLangley?

**Comment by WestLangley** [comment]
@arya-s

    renderer.shadowMapDebug = true;

was implemented for debugging cascading shadow maps -- which currently no longer appear to be working correctly.

 I find

    light.shadowCameraVisible = true;

the most useful for debugging shadow maps and setting parameters. Did you try it?

The helpers are also useful:

    var lightHelper = new THREE.SpotLightHelper( light );
    scene.add( lightHelper );

Being able to visualize the depth map can be helpful in some applications, so it would be nice to support a depth map HUD. But I am not sure it is needed in this particular case.

**Comment by arya-s** [comment]
I agree that

```light.shadowCameraVisibile = true;```

is very useful and I did try it. However, for some configurations with many lights and overlapping shadow maps it can still be hard to pinpoint issues I think. The more out of the box aids the better I think.

In general though, visualising the depth map like in the example you showed is common practice when working with any kind of SM. Is there any argument for not displaying it when having 

```renderer.shadowMapDebug = true``` ?

**Comment by chlowden** [comment]
Hello
For a longtime, I have been very interested in what you are developing but as I am being totally ignorant of java code, I have not been able to do much.
I follow your github dev mails but I have questions that are for total newbies concerning what the possibilities are for three.js particularly concerning objects and web interaction.
I presume that the github forum is not the place for these questions so I was wondering if there was another site where I could ask such questions.
Thanks
Christopher

**Comment by arya-s** [comment]
@chlowden this is indeed not the place for such questions. You can asks questions [here](http://stackoverflow.com/questions/tagged/three.js) for example, or you could join the chat channel #three.js on IRC and ask. Udacity also has a free course on getting started with 3D programming, using three.js [here](https://www.udacity.com/course/cs291).

**Comment by chlowden** [comment]
That looks good to me.  I will start learning. Thank you.

----- Mail original -----
De: "Andrei" <notifications@github.com>
À: "mrdoob/three.js" <three.js@noreply.github.com>
Cc: "chlowden" <christopher@fearlesstv.com>
Envoyé: Jeudi 15 Janvier 2015 15:04:10
Objet: Re: [three.js] renderer.shadowDebug should show shadow maps (#5896)



@chlowden this is indeed not the place for such questions. You can asks questions here for example, or you could join the chat channel #three.js on IRC and ask. Udacity also has a free course on getting started with 3D programming, using three.js here .

**Comment by WestLangley** [comment]
@arya-s 

I am trying to understand why you feel the existing utilities are inadequate.

> However, for some configurations with many lights and overlapping shadow maps it can still be hard to pinpoint issues.

1. What issues?
2. `light.shadowCameraVisibile = true;` selectively displays the SM frustum. What additional information does the shadow map provide you?
3. If there are many lights, do you expect multiple depth maps to appear on the HUD if `renderer.shadowMapDebug = true`?
4. What appears on the HUD if the shadow maps are cascading?

**Comment by arya-s** [comment]
@WestLangley 

1. At the time when I wrote that, I set up a scene with 4 spotlights and intentionally moving one light so that its frustum crops of shadows and I couldn't tell. That being said, once I turned on ```renderer.shadowMapDebug = true``` it was visible, so I retract that point.

2. Displaying the frustum is well when the shadow map is solely based on the frustum of the lights. I'm currently working on fitting shadow maps automatically to a convex body created by using the light's frustum, the camera's frustum and the scene box. In such cases, displaying the light's frustum won't give you an idea of exactly what the shadow map has in it.

3. Yes.

4. The shadow map for each cascade with labelling.

Overall, you can surely get by with what is built in right now, but if you want to improve shadow maps, the first thing is to fit the shadow map tightly as described above. In such cases, the shadow map often contains objects that aren't visible to the camera's frustum. That's when displaying the shadow map on a HUD comes in handy.

**Comment by WestLangley** [comment]
I think a `THREE.ShadowMapViewer` that displays a single shadow map would be useful as a separate utility.

I am not sure it should be part of the library. Perhaps part of the examples/js/utils.

**Comment by mrdoob** [comment]
> I think a `THREE.ShadowMapViewer` that displays a single shadow map would be useful as a separate utility.

Agreed!

**Comment by arya-s** [comment]
SGTM, I'll see what I can do over the weekend.

**Comment by arya-s** [comment]
@WestLangley 

I thought about this yesterday: Since r69, CSM doesn't seem to work anymore. Turning both ```light.shadowCameraVisibile = true``` and ```renderer.shadowMapDebug = true``` on, we still can't tell what's wrong. One possibility might be that the shadow map is actually empty, which would be another argument for showing the shadow map.

**Comment by mrdoob** [comment]
I think CSM has been broken for longer?
If no one steps in to fix them I'll probably remove the code in this cycle.

**Comment by arya-s** [comment]
@mrdoob might have been longer, not sure. I was referring to #5536.

I'm currently playing around with shadows and would like to eventually fix CSM. Not sure how long it'll take though.

**Comment by mrdoob** [comment]
Take your time. Good to know someone is looking at it :)
