### ISSUE TITLE
Group object

### ISSUE THREAD

**Issue by Wandalen** [mrdoob/three.js#5912]
Could somebody explain what new Group object for?

**Comment by mrdoob** [comment]
It's just a container object that doesn't get rendered. [Example](http://threejs.org/examples/webgl_geometry_hierarchy.html).

**Comment by Wandalen** [comment]
Thanks. But why not Object3D?

**Comment by mrdoob** [comment]
Because it's a nicer name. And it's also easier for the renderers to don't look for geometry.

**Comment by Wandalen** [comment]
I see.
