### ISSUE TITLE
Blender exports just one action

### ISSUE THREAD

**Issue by hulf** [mrdoob/three.js#5914]
Hi, perhaps someone had the same problem with exporting a model with 2 animations from Blender.
I have read that:
UPDATE 2: Currently THREE.js exports multiple actions using blender exporter, so this tutorial in not suitable for exporters for THREE.js versions r62 and higher. It should work well with versions r56 up to r61

In my model I have 2 animations: krilo1a, krilo2a.
![komar1](https://cloud.githubusercontent.com/assets/10427535/5777619/872ad2b8-9d94-11e4-861d-7629f3c37573.jpg)
Both animations work separately and each one gets exported and works
![komar2](https://cloud.githubusercontent.com/assets/10427535/5777647/de447c66-9d94-11e4-9963-96a7049dab35.jpg)
The export looks like this:
"bones"      : [{"parent":-1,"name":"krilo1a","pos":[0.217062,-0.429841,1.48519],"rotq":[0.589933,0.469901,-0.369392,0.542883],"scl":[1,1,1]},
(I posted the whole line, I thing not only the krilo4a bone data is missing, there also "]" missing at end.)

If I export them together what happens is:
- only the first one ( krilo1a<krilo4a,..) gets exported. If I rename the first one to ...lets say krilo5a, krilo4a gets exported.
- Blender model animation ( krilo1a - the one that gets exported and works ) doesn't work anymore in Blender unless I UNDO 1 step ( export ). The picture after export:
![komar4](https://cloud.githubusercontent.com/assets/10427535/5777684/2b6093d6-9d95-11e4-85fc-b2710d67c8f1.jpg)

- the JSON only has one bone ( krilo1a ).
- the JSON has 2 animations exported ...like it should, there is just one bone. 

While writing this I was thinking that I should try exporting another JSON with (krilo1a) deleated. This should give me the bone that I could add to the JSON with 2 animations. I will try that as a workaround until hopefully someone has a solution to this.

Thanks in advance.

**Comment by repsac** [comment]
Already being looked at
https://github.com/mrdoob/three.js/issues/5829
https://github.com/mrdoob/three.js/issues/5582#issuecomment-70043430

**Comment by hulf** [comment]
Thanks, i will check out the threads. 
I tried to add the missing bone manually, since the animation was already there:
			
"bones": [{"parent":-1,"name":"krilo1a","pos":[0.217062,-0.429841,1.48519],"rotq":[0.589933,0.469901,-0.369392,0.542883],"scl":[1,1,1]},
{"parent":-1,"name":"krilo4a","pos":[-0.17425,-0.472335,1.50399],"rotq":[0.533728,-0.437982,0.413822,0.593345],"scl":[1,1,1]}],

It doesn't work.

**Comment by hulf** [comment]
I tried a dev exporter mentioned in this thread: #5829,https://github.com/mrdoob/three.js/archive/dev.zip. The file is not created, output:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.72\scripts\addons\io_three\__init__.py", line 567, in execute
    exporter.export_scene(filepath, settings)
  File "C:\Program Files\Blender Foundation\Blender\2.72\scripts\addons\io_three\exporter\__init__.py", line 16, in inner
    func(filepath, options, *args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender\2.72\scripts\addons\io_three\exporter\__init__.py", line 47, in export_scene
    scene_.parse()
  File "C:\Program Files\Blender Foundation\Blender\2.72\scripts\addons\io_three\exporter\scene.py", line 65, in parse
    self.__parse_geometries()
  File "C:\Program Files\Blender Foundation\Blender\2.72\scripts\addons\io_three\exporter\scene.py", line 151, in __parse_geometries
    geo.parse()
  File "C:\Program Files\Blender Foundation\Blender\2.72\scripts\addons\io_three\exporter\geometry.py", line 128, in parse
    self.__parse_geometry()
  File "C:\Program Files\Blender Foundation\Blender\2.72\scripts\addons\io_three\exporter\geometry.py", line 325, in __parse_geometry
    self.node)
  File "C:\Program Files\Blender Foundation\Blender\2.72\scripts\addons\io_three\exporter\base_classes.py", line 20, in __setitem__
    raise exceptions.ThreeValueError(msg) 
io_three.exceptions.ThreeValueError: Value is an invalid data type: <class 'NoneType'>

location: <unknown location>:-1

**Comment by repsac** [comment]
I misread your post and thought you were using the new exporter. FYI; the multiple animations is not yet supported in the new exporter. Am working on that. 

Now on to the bones: Would need to see that scene to see how your rig/armature is setup.

Do you have a scene that you can share that recreates this error?

**Comment by hulf** [comment]
The blender file can be downloaded here:
http://s000.tinyupload.com/?file_id=72464802249188189168

**Comment by repsac** [comment]
Update: https://github.com/mrdoob/three.js/issues/5582#issuecomment-71337806

**Comment by repsac** [comment]
So I looked at your scene and after addressing what were indeed some bugs that had to be addressed. I will note that your asset is made up of multiple nodes therefore the only export that would work is a scene export. I have not submitted a PR but you can find my branch here
https://github.com/repsac/three.js/tree/io_three

**Comment by hulf** [comment]
I tried exporter v1.1.1 on the same model:

"animations": "SphereGeometry.3.animations.json"
"bones": [],
--------------------------------------------------------------
 "metadata": {
        "uvs": 1,
        "bones": 0,
        "vertices": 2061,
        "colors": 321,
        "generator": "io_three",
        "materials": 1,
        "type": "Geometry",
        "normals": 1969,
        "version": 3,
        "faces": 2218
    },

**Comment by hulf** [comment]
Just tried the "Large patch committed for testing"
https://github.com/repsac/three.js/tree/io_three

I tested it on the same file:
- animations & bones are "empty" in the json. Perhaps I am doing something wrong?
- when having on object selected before exporting results in an error ( not a valid mash object )

**Comment by hulf** [comment]
I new version:         "generator": "io_three",        "version": 4.3.
When using this options:
![1](https://cloud.githubusercontent.com/assets/10427535/6105868/593e6966-b05c-11e4-8722-5c04f045f2e3.jpg)
I get only a 400KB file, 1 material, no bones.
If I select ( SCENE: Scene: on, Materials: on), the exported file is 14MB large, and does not get loaded:
![2](https://cloud.githubusercontent.com/assets/10427535/6105937/1391ae4a-b05d-11e4-912c-9a9e9153acb8.jpg)

The animations and bones are there.

**Comment by repsac** [comment]
`POSE` animation exports (introduced in r67) are way bigger than `REST` exports. I am guessing that has something to do with the other properties like `Frame index as time` and `Frame step` were meant to reduce the amount of per-frame data being exported.

Additionally; try unchecking the new option at the bottom `Indent JSON`. That has had quite a difference.

**Comment by repsac** [comment]
Using this file https://github.com/mrdoob/three.js/issues/5914#issuecomment-70332640 I was able to export in both REST and POSE positions using the following settings.

Options
- Vertices
- Faces
- Bones
- Skinning
- Scene
- Materials
- Precision=3

Skeletal animations: REST (317.48 KB)
http://pastebin.com/5SQ9TSWY

Skeletal animations: POSE (333.60 KB)
http://pastebin.com/xax8gPWh

**Comment by repsac** [comment]
Did some tests and realized that one of the materials is a MeshBasicMaterial

```
        "type": "MeshBasicMaterial",
        "color": 0,
        "depthTest": true,
        "depthWrite": true,
        "name": "Material",
        "emissive": 0,
        "vertexColors": false,
        "blending": "NormalBlending",
        "uuid": "FC9C3C1C-87E7-3748-8148-105003E5F3D5",
        "ambient": 0
```

In three this material does not have an `ambient` or `emissive` properties but since it is set in the JSON the loader is trying to set these properties. I removed them in the JSON and the scene did load tho the asset itself seems distorted.

**Comment by hulf** [comment]
Thanks for your efforts. 

With your latest io_three:
- still JSONLoader won't load the model. Do I need to use ObjectLoader? Or Is it something I messed up with the export settings:
![1](https://cloud.githubusercontent.com/assets/10427535/6129208/d691e7a4-b13c-11e4-944c-a225f56dff6c.jpg)
- I can't see any texture files in the JSON I exported, I also tried the texture, copy texture option. Both give me a error while exporting.

**Comment by repsac** [comment]
If exporting `Scene` then you have to use ObjectLoader(). I disabled textures because none were sent with the file.

**Comment by hulf** [comment]
- excuse me, I forgot to pack the blender file. Interesting, after I packed the file, the option: Textures, Copy textures doesn't error anymore. Here is the link to the full blender file.
http://s000.tinyupload.com/?file_id=99298463661061310057
- I didn't figure out ObjectLoader() for now. I will look into it.

**Comment by repsac** [comment]
I am going to consider this issue resolved since the exporter does export multiple actions again. The asset does load correctly (as far as geometry goes). As far as automatic support of skinned meshes and textures go that is outside the scope of this issue.

![screen shot 2015-02-11 at 9 23 18 pm](https://cloud.githubusercontent.com/assets/1109289/6162234/71711f72-b234-11e4-8f7a-370991f3b3f2.png)
