### ISSUE TITLE
morphTarget regression r69->r70

### ISSUE THREAD

**Issue by jaakkor2** [mrdoob/three.js#5916]
WebGLRenderer with MeshPhongMaterial with `morphTargets: true` is showing me a regression between r69 and r70.

It looks like errors happen when I remove a mesh and add a new one based on a geometry with morphTargets.  On initial loading I do not see errors.

Firefox (Windows 7 and OS X) console is giving me
```
Error: WebGL: drawElements: bound vertex attribute buffers do not have sufficient size for given indices from the bound element array
```

Chrome (OS X) console gives me repeating errors
```
[.WebGLRenderingContext]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 2
```
where attribute can be `2` or `6`.

It has worked since r59. I narrowed it down between `threejs.min.js` history
Jan 4, 2015 `3042d4d` and Jan 5, 2015 `b51b75a`.

If I turn `morphTargets: false` I do not see the errors.

I do not yet have a simplified example that would show the problem.  All hints how to debug further are welcomed.

**Comment by mrdoob** [comment]
Yeah, there may be a regression there. If you could create a simplified example that would be super!

**Comment by jaakkor2** [comment]
Example here https://github.com/jaakkor2/debug_Threejs_morphTarget

Use number keys `1`,`2`,`3`,`4`,`5`,`6` to switch between models.

test_18986.js binded to key `6`contains 18986 vertices and triggers the bug most easily.  For me the model usually disappears from the screen in Chrome before it finishes the first round of rotation.

For this example, Three.js r69 is showing some errors as well, but the model does not disappear from the screen as with r70.

**Comment by jaakkor2** [comment]
Example is now online at http://jaakkor2.github.io/webgl_morphtargets_debug.html

**Comment by mrdoob** [comment]
Hmmm, I'm not getting objects disappearing.
Do you mind doing a screen recording and uploading to youtube or similar?

Also, what GPU do you have? OS?

**Comment by jaakkor2** [comment]
* Mac OS X 10.10.1, NVIDIA GeForce 9400M (in Firefox, Chrome, and Safari the model behind key `6` disappears before first round)
* Windows 7, NVIDIA K2200 (in Firefox the model `6`disappears similarly, in IE11 the model does not disappear but previously loaded model flashes quickly on the screen and the chosen model comes back to screen)

Sometimes switching a few times between the models helps to trigger the disappearance more quickly.   I will try to produce a screen recording..

**Comment by mrdoob** [comment]
Heh! I'm also on a 9400M! I run Fedora/Linux though.
It's surprising that the drivers NVIDIA does for Linux are more robust(?) than the ones for OSX.

**Comment by jaakkor2** [comment]
Youtube video http://youtu.be/oiiNMDMpxmk 
Ball disappears twice, at 0:17 and 2:04.

**Comment by WestLangley** [comment]
This appears to have nothing to do with switching models. I tried using @jaakkor2's simple model only, and the problem was easily reproduced. There are only 2 frames in that model.

The problem is in THREE.MorphAnimation.update():

		this.currentTime = Math.min( this.currentTime, this.duration ); // result 1000
		var interpolation = this.duration / this.frames; // result 1000 / 2 = 500
		var frame = Math.floor( this.currentTime / interpolation ); // result 1000 / 500 = 2

A value of 2 for `frame` is too big; it must be less than `this.frames`, which is 2.

Sample output:

    morph.targets.bug.html:153 [0.14, 0.86] <- mesh.morphTargetInfluences has length 2
    morph.targets.bug.html:153 [0.099, 0.9]
    morph.targets.bug.html:153 [0.060, 0.94]
    morph.targets.bug.html:153 [0.040, 0.96]
    morph.targets.bug.html:153 [0, 1, 0] < - mesh.morphTargetInfluences has length 3
    three.js:20625 WebGL: INVALID_OPERATION: vertexAttribPointer: no bound ARRAY_BUFFER
    morph.targets.bug.html:1 [.WebGLRenderingContext]GL ERROR :GL_INVALID_OPERATION :     glDrawElements: attempt to access out of range vertices in attribute 6

Perhaps someone can suggest the proper fix...

**Comment by mrdoob** [comment]
@WestLangley Wow! I take my hat off to you. That would have taken me a bit to find...

**Comment by mrdoob** [comment]
I'm unable to figure out how the code in THREE.MorphAnimation.update() should look like instead though.

**Comment by WestLangley** [comment]
My quick attempt to simplify the logic. Please have a look. Only supports time running forward. Not sure if reverse is required...

	update: function ( delta ) {

		if ( this.isPlaying === false ) return;

		this.currentTime += delta;

		if ( this.loop === true && this.currentTime >= this.duration ) { // notice the >=

			this.currentTime %= this.duration;

		} else {

			this.currentTime = Math.min( this.currentTime, this.duration );

		}

		var interpolation = this.duration / this.frames;
		var frame = Math.floor( this.currentTime / interpolation );

		if ( frame != this.currentFrame ) {

			this.mesh.morphTargetInfluences[ this.lastFrame ] = 0;

			this.lastFrame = this.currentFrame;
			this.currentFrame = frame;

		}

		this.mesh.morphTargetInfluences[ this.currentFrame ] = ( this.currentTime % interpolation ) / interpolation;
		this.mesh.morphTargetInfluences[ this.lastFrame ] = 1 - this.mesh.morphTargetInfluences[ this.currentFrame ];

	}

**Comment by mrdoob** [comment]
Reverse is required I think...

**Comment by WestLangley** [comment]
Furthermore, I think there is a problem at the start, because `currentFrame` and `lastFrame` are the same.

**Comment by mrdoob** [comment]
Well. That should serve as a workaround for now.
