### ISSUE TITLE
Blender exporter crashing

### ISSUE THREAD

**Issue by kevzettler** [mrdoob/three.js#5918]
Just started seeing this after it had been working ok. Not sure what happened.

` bpy.ops.object.mode_set.poll() failed, context is incorrect`

![screenshot 2015-01-16 20 58 28](https://cloud.githubusercontent.com/assets/126209/5787755/aa396ba6-9dc2-11e4-8038-6b0b4eda5919.png)

**Comment by repsac** [comment]
I can tell you that this exporter (`io_mesh_threejs`) is deprecated. There is a new one included in the r70 release called `io_three`.

As a side note; I wonder if this is related to possible changes in Blender 2.73 if it had recently just started happening.

**Comment by kevzettler** [comment]
When I say 'It had been working' I mean that it had been working with Blender 2.73 already. I didn't upgrade and it broke.

**Comment by SimoneGianni** [comment]
I'm hitting the same problem in 2.72b, see https://github.com/mrdoob/three.js/issues/6276 .

@kevzettler have you found out what was causing it?

**Comment by daarong** [comment]
Same as issue [6276](https://github.com/mrdoob/three.js/issues/6276), which has a likely fix (you have meshes in your scene that are set to invisible).

**Comment by daarong** [comment]
Issue [#6276](https://github.com/mrdoob/three.js/issues/6276) now has answers for this problem
