### ISSUE TITLE
event listener never executes a function on "resize"

### ISSUE THREAD

**Issue by hulf** [mrdoob/three.js#5919]
I'm using FireFox, and have a issue with the resize event that bothers me for some time now.

I added those to the event listener:
	document.addEventListener( 'mousemove', onDocumentMouseMove, false );
	document.addEventListener( 'resize', onWindowResize, false);

( mousemove works normally...I added it just to show that nothing else is wrong with the code before )
The function is:

function onWindowResize(){
console.log("resize");
}

Now when i resize the window i get:
Error in parsing value for 'height'.  Declaration dropped. meni.html
This error is dumped ONCE EVERY time i resize the window. 
The console.log message is not shown ( function is not executed ).
I'm stuck with this.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by hulf** [comment]
I thought since its 2 lines of code it could be only a bug. Where for others it works. Well thanks I will ask in stackoverflow if someone had the same problem.
