### ISSUE TITLE
Blender exporter does not export completed mesh

### ISSUE THREAD

**Issue by yomotsu** [mrdoob/three.js#5923]
I used the new Blender Exporter with r70, but it does not export completed mesh which consists of multiple parts.

The previous exporter has "Embed meshes" for full parts, but new one does not, and it only publish single part which selected in Blender before publishing.

The front left tire is selected, before publishing in blender
![screen shot 2015-01-18 at 11 51 10 pm](https://cloud.githubusercontent.com/assets/212837/5792818/8fcb5fba-9f6e-11e4-8acf-7b4997658199.png)

publish with "Embed geometry"
![screen shot 2015-01-18 at 11 49 23 pm](https://cloud.githubusercontent.com/assets/212837/5792831/d2ef0bfc-9f6e-11e4-94e0-7a2ca641b5fd.png)

The JSON file does not contain other parts
![screen shot 2015-01-19 at 12 02 22 am](https://cloud.githubusercontent.com/assets/212837/5792821/98fa2d6e-9f6e-11e4-91a9-39cac3cb491d.png)

the previous exporter has "Embed meshes" for multiple parts.
![screen shot 2015-01-18 at 11 49 17 pm](https://cloud.githubusercontent.com/assets/212837/5792828/c8d29648-9f6e-11e4-94e6-b25f13487d16.png)
![screen shot 2015-01-19 at 12 09 01 am](https://cloud.githubusercontent.com/assets/212837/5792851/718d0be2-9f6f-11e4-81a7-570ce4501067.png)

**Comment by repsac** [comment]
Multiple geometries is supported in Scene export. I can see in the screen shot provided that `Scene` is not checked, therefore it is only exports a singe mesh (the selected one).

**Comment by repsac** [comment]
And as a side note; On both the old and current exported the "Embed meshes" and "Embed geometry" applied to scene exports to include the geometry (mesh) definitions in the same JSON, otherwise geometry would be written to external files. In both screen shots `Scene` is not checked.

It is also important to note that external geometry files were supported in SceneLoader() which is now deprecated for ObjectLoader(), the new scene format. If you were to disable embedding of geometry in the scene and try loading with ObjectLoader() you would not get any geometry in the scene. The feature sets of the new exporter are not yet fully supported in ObjectLoader().

**Comment by yomotsu** [comment]
@repsac 
Thank you for the great hint,
If I would like to geometries as one mesh, I need to "join" as one geometry in Blender, before publishing, right?

join geoms,
![screen shot 2015-01-19 at 4 20 56 am](https://cloud.githubusercontent.com/assets/212837/5793758/2ede912a-9f93-11e4-8440-d97ae795750c.png)

then, remove unused material
![screen shot 2015-01-19 at 4 21 59 am](https://cloud.githubusercontent.com/assets/212837/5793759/34d43d1e-9f93-11e4-8885-099e4e8b311c.png)

and then, publish as a geometry.

Now I'm getting it. and it seems better.
![screen shot 2015-01-19 at 4 19 59 am](https://cloud.githubusercontent.com/assets/212837/5793762/5b1709f2-9f93-11e4-84eb-de810bc99c31.png)

But I'm still looking for a way to publish `transparency` into materials. It seems, `opacity` in new exporter should be `transparency`.

in the previous exporter
```
				{
					"DbgColor": 60928,
					"DbgIndex": 2,
					"DbgName": "glass",
					"blending": "NormalBlending",
					"colorAmbient": [0.4704000066280365, 0.4704000066280365, 0.4704000066280365],
					"colorDiffuse": [0.4704000066280365, 0.4704000066280365, 0.4704000066280365],
					"colorEmissive": [0.0, 0.0, 0.0],
					"colorSpecular": [0.8999999761581421, 0.8999999761581421, 0.8999999761581421],
					"depthTest": true,
					"depthWrite": true,
					"shading": "Phong",
					"specularCoef": 21,
					"transparency": 0.30000001192092896,
					"transparent": true,
					"vertexColors": false
				},
```

in the new exporter, `transparency` is not published, and but `opacity` is added instead
```
    },{
        "DbgColor": 15658734,
        "colorEmissive": [0.0,0.0,0.0],
        "doubleSided": true,
        "colorSpecular": [0.9,0.9,0.9],
        "shading": "phong",
        "opacity": -0.7,
        "wireframe": false,
        "DbgName": "glass",
        "specularCoef": 21,
        "transparent": true,
        "depthTest": true,
        "colorDiffuse": [0.47,0.47,0.47],
        "depthWrite": true,
        "blending": "NormalBlending",
        "colorAmbient": [0.47,0.47,0.47],
        "DbgIndex": 7,
        "visible": true
    },{
```

**Comment by yomotsu** [comment]
or, `opacity` should be positive number

**Comment by repsac** [comment]
> If I would like to geometries as one mesh, I need to "join" as one geometry in Blender, before publishing, right?
Correct. A non-scene export assumes you are selectively exporting a single (selected) mesh from a scene.

The `opacity` value issue is a possible bug. I never got around to making a test case for transparent materials.

**Comment by yomotsu** [comment]
I changed the opacity value,
https://github.com/mrdoob/three.js/blob/master/utils/exporters/blender/addons/io_three/exporter/api/material.py#L131

```
@_material
def opacity(material):
    logger.debug('material.opacity(%s)', material)
    return round(1.0 - material.alpha, 2);
```

then, its working correctly!
![Uploading Screen Shot 2015-01-19 at 4.53.51 AM.png . . .]()

**Comment by WestLangley** [comment]
> return round( 1.0 - material.alpha, 2 );

Are you sure? How about

    return round( material.alpha, 2 );

**Comment by yomotsu** [comment]
@WestLangley 
Sorry, it was misunderstanding...
you are right, and it seems `opacity` must be `transparency`
