### ISSUE TITLE
Can not print pointLight ?

### ISSUE THREAD

**Issue by xiulunlin** [mrdoob/three.js#5924]
Here are my codes. Do I miss something?

            var width = attrs.pointLightWidth,
			height = attrs.pointLightHeight;
			var container;

			var camera;
			var scene;
			var renderer;

			container = ele[0];

			camera = new THREE.PerspectiveCamera(75, width / height, 1, 10000);
			camera.position.z = 1000;

			scene = new THREE.Scene();
			scene.add(camera);

			renderer = new THREE.CanvasRenderer();
			renderer.setSize(width, height);

			var light = new THREE.PointLight(0xff0000, 1, 100);
			light.position.set(50, 50, 50);
			scene.add(light);

			container.appendChild(renderer.domElement);

			renderer.render(scene, camera);

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

Start with a working three.js example and slowly modify it.
