### ISSUE TITLE
Wrong shadow map rendered in examples/webgl_shadowmap

### ISSUE THREAD

**Issue by arya-s** [mrdoob/three.js#5925]
Hey,

I played around with examples/webgl_shadowmap.html (specifically displaying the shadow map) and I noticed the following:

The shadow map of ```light``` is used for the ```THREE.ShaderMaterial``` uniforms:

```
...
var shader = THREE.UnpackDepthRGBAShader;
this.uniforms = new THREE.UniformsUtils.clone( shader.uniforms );

this.uniforms.tDiffuse.value = light.shadowMap;

var hudMaterial = new THREE.ShaderMaterial( {
   uniforms: this.uniforms,
   vertexShader: shader.vertexShader,
   fragmentShader: shader.fragmentShader
} );
...
```

However, when adding a shadow casting light to the scene BEFORE adding ```light```, the HUD actually displays that light's shadow map instead of ```light.shadowMap```.

This might also be related to #5536, CSM not working.

**Comment by WestLangley** [comment]
What, exactly, is rendered incorrectly in the current `webgl_shadowmap` example?

**Comment by arya-s** [comment]
@WestLangley,

sorry the problem isn't actually in the current  webgl_shadowmap example. That's just where it's visible with modification. Should I reopen this issue under some other name?

**Comment by WestLangley** [comment]
You could modify the title.

If you can demonstrate a three.js bug, please provide a test case so we can reproduce your results. Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).
