### ISSUE TITLE
Morph weights not working correctly on software renderer

### ISSUE THREAD

**Issue by Sampoman** [mrdoob/three.js#5933]
Looks like the morph weights are not calculated correctly in the software renderer. I have a simple grid-based weighting system which works correctly on WebGL but seems to have severe distortions on software renderer.

WebGL version: http://samiarola.com/buggyrenderer/morpher.html
Software version: http://samiarola.com/buggyrenderer/morphersoft.html

If you pull the weights one by one, you can notice distortions if the values are not 0 or 1, and if you stack the weights, the whole model distorts badly. E-mail me (sami (at) ookoohko.com), I can send the test over.

**Comment by Sampoman** [comment]
My educated guess is that the morph target vertices are not transformed, and thus you're trying to blend transformed vertices (of the base model) with untransformed vertices?

**Comment by Sampoman** [comment]
Edit: updated the software rendering test, now it works for this particular case (only one material per object), but there's a fundamental problem in the vertex handling in the software renderer if morphing is used, this is not a trivial case to fix. 

The problem is that morphing only selected materials should create duplicate vertices for those faces which use the material, which currently does not work correctly, thus the vertices are transformed several times, which leads to distortions (even worse case when stacking).

**Comment by mrdoob** [comment]
Well... Fixed. I can't believe this has always been broken... Thanks for reporting!
