### ISSUE TITLE
Position with large values of coordinates x / y / z

### ISSUE THREAD

**Issue by Ni55aN** [mrdoob/three.js#5934]
http://jsfiddle.net/eho5g2go/

The variable "offset", it is used to indicate the position of the camera and mesh. If you set its value to 100000000, then get strange behavior during the animation And if you set 10000000, then everything is fine

Why so? How is it possible to specify the position of objects with coordinates more than 100000000, for example?

**Comment by mrdoob** [comment]
I think this is an issue with both JavaScript Number precision itself and the float32 used in the shader.
The only solution is to avoid having such big numbers.

**Comment by sjlynch** [comment]
I'm running into this with my current project and I'm looking at solutions. There are a lot of ways to fix this, each with different trade-offs. I'm wondering if this could become a feature request. Anyone using Threejs to render the solar system, or even just the Earth is going to run into this issue. Maybe we create a new camera for very large ranges? LogarithmicCamera? I don't know.

Some interesting reading: http://blogs.agi.com/insight3d/index.php/2008/09/03/precisions-precisions/
http://outerra.blogspot.com/2012/11/maximizing-depth-buffer-range-and.html

Index of many sources: http://www.urbanrobots.com/Blogs/WW/2006/01/solving-coordinate-precision-problems.html
