### ISSUE TITLE
Blender Exporter: JSONLoader not firing load callback for exported scene

### ISSUE THREAD

**Issue by kevzettler** [mrdoob/three.js#5936]
I am using the blender exporter to export a scene to three.json that has a few meshes.
The exporter seems to be successful and the json file has, what looks like, accurate data.

you can check the scene json here: 
https://www.dropbox.com/s/0mxzhxxwy0sv48z/pleb.json?dl=0

I am using the following code to load the scene

```javascript
var loader = new THREE.JSONLoader();
debugger;
loader.load( 'models/animated/pleb/pleb.json', function ( geometry, materials ){
    debugger;
    //...
});
```

The second `debugger` break point is never triggered.
The browser console look like the images has loaded successfully.
![screenshot 2015-01-19 14 17 28](https://cloud.githubusercontent.com/assets/126209/5808954/1335f13e-9fe8-11e4-8a3e-6dc1d483602a.png)

I am doing all this on a local filesystem with the the crhome `--allow-file-access-from-files`
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --allow-file-access-from-files ./kev_test.html`

This is a large export ~20Mb I suspect maybe theres some hidden file access limit from Chrome in this mode.

I am able to export individual selected meshes from the same blend file using the exporter. How can I validate the export data or further debug this?

**Comment by poofik** [comment]
with this new blender exporter r70 you need to use ObjectLoader()

**Comment by mrdoob** [comment]
Added a check in `JSONLoader` for this. Thanks for reporting!
