### ISSUE TITLE
Found objects in OBJMTLLoader are not converted to a BufferGeomery

### ISSUE THREAD

**Issue by doexclusive** [mrdoob/three.js#5941]
On the page http://threejs.org/docs/#Reference/Loaders/OBJMTLLoader I saw "Found objects are converted to Mesh with a BufferGeometry and materials are converted to MeshLambertMaterial." and become happy, now I can use fast BufferGeometry, but objects in this loader are not converted to BufferGeometry unfortunately. This is an loader with old Geometry..
If anyone can update OBJMTLLoader with a BufferGeometry please share it

**Comment by dubejf** [comment]
Documentation as been corrected as part of #6101 by @TatumCreative. OBJMTLLoader doesn't currently support BufferGeometry. Closing.
