### ISSUE TITLE
Text rendering issues 

### ISSUE THREAD

**Issue by pressuredesigns** [mrdoob/three.js#5943]
I am currently working on a three.js project and we are running into issues loading fonts onto our text.

We are using TextGeometry object to render our fonts and the typeface js converter to add in our fonts.

Some fonts work great but others do not perform as expected with some letters not rendering correctly such as d's and o's.

This can be seen in the fiddle below, the font is loading the interior of some letters not the exterior.

http://jsfiddle.net/264jawhe/2/

Can anyone identify why this is happening and if there is a better method to display text possibly loading an html element?

Thanks in advance!

**Comment by mrdoob** [comment]
Can you try with the code in this example?
http://threejs.org/examples/webgl_geometry_text2.html

**Comment by mikaelgramont** [comment]
Hi,

I just ran into the same issue with a font I generated through https://github.com/gero3/facetype.js
The second example, which uses pnltri.js, works much better. Not perfectly, I'm still getting an issue with the glyph for 8:

![screen shot 2015-05-09 at 20 24 34](https://cloud.githubusercontent.com/assets/580192/7552972/7520bbe8-f689-11e4-8bbc-1ef8c35d8386.png)
![screen shot 2015-05-09 at 20 24 28](https://cloud.githubusercontent.com/assets/580192/7552971/75201ad0-f689-11e4-8ca7-7a5cd250d57c.png)

Mika

**Comment by mikaelgramont** [comment]
Side note: the version embedded in the examples is 2.0.0. I tried with both that and 2.1.1 and I'm getting the same results.

**Comment by gero3** [comment]
If you see that, reverse the font direction. I still haven't figured out how to automatically detect if I need to reverse the direction of the font. So this is still a process that needs to be manually checked.  
![test](https://cloud.githubusercontent.com/assets/155535/7553448/d01904f4-f6f9-11e4-9f9f-6f17e378d91e.png)

ps: if you have other issues, use https://github.com/gero3/facetype.js/issues.

**Comment by mikaelgramont** [comment]
Ah, wonderful, that worked, thanks for mentioning that. It'd be good to mention that on the page itself, I assumed those two things were unrelated. I'm happy to send you a pull request but I'm not sure what to say, does this solve other problems or is that the only one?

**Comment by gero3** [comment]
It only solves that one. It has to do with the fact that fonts are written as paths and these paths are written in clockwise direction or counterclockwise direction. And three.js expects them to be clockwise for the shapes and counterclockwise for the holes. 

If you could send a PR, that would be great.
