### ISSUE TITLE
Doc are off with static methods

### ISSUE THREAD

**Issue by michaelbpaulson** [mrdoob/three.js#5945]
I have only reviewed the Quaternions, but i assume that this may happen in more than this one place.

This doc claims multiple static methods.
http://threejs.org/docs/#Reference/Math/Quaternion

E.G.: `fromArray` claims that it is static.  As you can see from the code, it is an instance method.
https://github.com/mrdoob/three.js/blob/master/src/math/Quaternion.js#L471

There are three fixes that i see.
* Change the code to make it accurately reflect the docs
** remove the instance methods and convert them into static methods.
** I see this making a lot of people angry
* Change the doc to accurately reflect the state of the code
** This should be good. Will break no one and make new people's first use better.
* Create static methods and keep the instance methods.
** Flag them as deprecated with a date of removal
** Update the doc to reflect that.  This way people know that the instance version will leave soon.

Thoughts?
I think that option three is the best.  `fromArray` seems like it should be a static method.  Perhaps a second arg that could be the quaternion to operate on, else generate a new quaternion.

**Comment by mrdoob** [comment]
Up for fixing it directly? ^^
https://github.com/mrdoob/three.js/edit/dev/docs/api/math/Quaternion.html

**Comment by michaelbpaulson** [comment]
I am not opposed to it, but there are three possible options that i listed.  What do you think?  I think that option 3 is the best as it migrates users over to a preferred strategy without leaving them stranded.

**Comment by WestLangley** [comment]
I'd recommend that we first decide which methods should be static. Then modify the code accordingly. Then correct the docs.

**Comment by michaelbpaulson** [comment]
@WestLangley that can cause breaking changes.  There should be a period of @deprecated to let those know to get off prototype methods when they should be static.

**Comment by WestLangley** [comment]
@michaelbpaulson That's fine.

If you would like to make a contribution now, a good place to start would be to first update the docs so they match the codebase. Then, if you feel there should be changes to the code, you can file a PR so your suggestions can be discussed.

Thank you for noticing the discrepancies.
