### ISSUE TITLE
Editor: UI panels idea

### ISSUE THREAD

**Issue by waldenn** [mrdoob/three.js#5949]
Extending on the sidebar tab proposal here: #5939 , I was thinking about improving this idea further. Feedback is welcome!

Main concepts of the mockup shown below:

 - **3 sidebar panels**, that each can be collapsed by some kind of "panel toggle" located on the menubar (ideally these toggles would be a small-scale representation of the panel shapes). The 3 panels go from higher level to lower level management:

    - **Project management panel**
      - Resource / asset management: models, textures, sounds, scripts, plugins, etc. (UI design to be done)
      - Editor configuration. There should perhaps be made a distinction between the "editor config" and the  "app config" using two distinct tabs.
      - Rendering configuration. Perhaps this should go as a sub-section under the editor configuration tab? 

    - **Scene management panel**
      - Each object in the scene tree may have clickable properties (visibility, material, scripts, etc.) that can (if that makes sense) directly open the related object-management tab. Eg. clicking on a script symbol in the scene tree may open the "scripts" tab, and perhaps even auto-show the script editor for the first script as a sane default.
     - Drag-and-drop should work for re-ordering scene objects. This will require a more sophisticated tree-widget. See also: [jsTree](http://www.jstree.com/), [Sortable](http://rubaxa.github.io/Sortable/) ... would be interesting to research if something like this could be cleanly integrated into the "libs/ui.js" system, so that we dont have to re-invent this complex widget type.

    - **Object management panel**

 - **Drag-and-drop** should work between the panels: resource --> scene, resource --> object, scene --> object, when that makes sense. This could also allow for the possibility of drag-and-drop from resource --> canvas and from scene --> canvas.

- Move the "Autosave" toggle on the menubar to the editor configuration tab.

PS:
  - At some point: Change the CSS styling to use relative units instead of pixels. Perhaps [flexbox](http://caniuse.com/#feat=flexbox) could be useful too (not used it yet).
  - I am not qualified enough with 3D modelling to say anything about the UI for "mesh modelling" operations. If you have ideas for that please propose them.

![tabs001](https://cloud.githubusercontent.com/assets/1248919/5829435/669c868c-a112-11e4-81b2-a426bbdb1c0a.jpg)

**Comment by mrdoob** [comment]
The concepts separation sounds good to me. But I would put the panels one on top of each other instead.

**Comment by mrdoob** [comment]
Thanks for the "Project" concept. It's just the kick I needed.
I'm now refactoring "Renderer" and adding a "VR" option :)

**Comment by walden-** [comment]
Thanks. The vertical stacking sounds better to me too, eventough the information density will be much higher and more care should be taken that the panels are distinct to a user (which will help the mental model when using the editor).

Vertical stacking would also be able to give better interaction with the 3D canvas (and more canvas space), such as eg. allowing the possibility of drag-and-drop from the resource --> canvas or from scene --> canvas.

I will be busy with work over the coming month or so, but its good we are brainstorming the ideas around the UI improvements.

**Comment by killroy42** [comment]
Is this UI intended to eventually stand apart from the Three.js Editor as its own component system? I'm in need of an inspector-type UI for my three.js editor project and am building my own at the moment, but would be happy to join forces.

**Comment by dmtaub** [comment]
I've used an accordion menu to help with the information density, and it
still allows dragging between panels, as drag-and-hover over a title could
expand (or set to 'fixed' and make grey--like a preview) before the drop
action is completed.
