### ISSUE TITLE
Omnidirectional shadows (Pointlight)

### ISSUE THREAD

**Issue by arya-s** [mrdoob/three.js#5951]
Hey,

I was looking through the issues but couldn't find an answer as to why pointlights don't cast shadows. For example, #1192 was closed but there are still no shadows for point lights.

We already have an example for reflections on objects using cubemaps, omnidirectional shadow mapping is quite similar.

**Comment by mrdoob** [comment]
Oh! No one every tried.
If you feel like giving it a go that would be fantastic! :D

**Comment by arya-s** [comment]
Excellent, will have a go at them tomorrow!

**Comment by Cubiverse** [comment]
@arya-s - did you get this working?

I did look at this ages ago and from what I recall it was the requirement to render the shadow map multiple times (as the shadow "camera" has a viewing frustum) in various directional to generate a 360 degree shadow map.. again cascading shadows was (or maybe still is) broken, if it works then you may not have the issue of tiling shadows maps together to avoid seams or overlaps.

**Comment by mrdoob** [comment]
#7153
