### ISSUE TITLE
Panorama Texture Incorrectly Mapping on iOS 8.1.2

### ISSUE THREAD

**Issue by jodybrewster** [mrdoob/three.js#5956]
On iOS 8.1.2 or maybe just iOS 8 in general the texture is mapping incorrectly on the current demo.

http://mrdoob.github.io/three.js/examples/webgl_panorama_equirectangular.html

**Comment by mrdoob** [comment]
Could you attach a screenshot?

**Comment by jodybrewster** [comment]
![image1](https://cloud.githubusercontent.com/assets/303701/6321134/be13f838-bac0-11e4-8e4f-2afc74fdaee1.PNG)

**Comment by WestLangley** [comment]
The environment map is too big, apparently. Reducing its size by a factor of two in each direction does appear to solve the problem.

**Comment by zachwise** [comment]
@WestLangley how do you go about changing the size of the environment map in this case?

**Comment by WestLangley** [comment]
Resize the image file.

**Comment by mrdoob** [comment]
This is actually a iOS bug. iOS reports that it supports that texture size but, as we can see, it does not...
