### ISSUE TITLE
Earcut: Interesting new polygon triangulator

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#5959]
https://github.com/mapbox/earcut

@jahting did you had a look at it?

**Comment by zz85** [comment]
interesting!

**Comment by mrdoob** [comment]
If someone has some spare time would be nice to test it out and see how it compares :)

**Comment by mourner** [comment]
Hey guys, I wrote this thing. Let me know if you need any help with it. :) A big fan of your work!

**Comment by tonnot** [comment]
@mourner . 
I have some doubts:
1.- Does earcut create a right delaunay network?
2.- Is (or would it be ) it  possible to add fill points  ?
3.- Is (or would it be) it  possible to add hard / break lines to create constrained D. ?
(as in http://www.iue.tuwien.ac.at/phd/fleischmann/node51.html)

**Comment by mourner** [comment]
@tonnot 
To answer 1 and 3 — no, it does not align with goals of the library. Here's a quote from the readme:

> The aim of this project is to create a JS triangulation library that is fast enough for real-time triangulation in the browser, sacrificing triangulation quality for raw speed and simplicity, while being robust enough to handle most practical datasets without crashing or producing garbage.

While Constrained Delaunay triangulation produces optimal quality triangulation without sliver triangles, it is pretty expensive to do. Look at the benchmarks — poly2tri which implements CDT is 6-20x slower, considering that it's also not robust — it'll fail completely on lots of conditions like duplicate vertices, vertices touching edges, any kinds of self-intersections etc. Combining it with something like Clipper.js for cleaning up complex polygons dramatically slows it down even further while adding complexity. For the use cases Earcut was created, this wasn't acceptable.

2. Yes, it'll be very easy to add fill points support. They'll be handled pretty much the same way as holes.

**Comment by tonnot** [comment]
OK, Thank you.

**Comment by mourner** [comment]
FYI just released 2.0.0 which is even faster, more robust and takes less memory than last time you've checked. :) PIXI.js is going to switch in a few days. You should too. :)

**Comment by mourner** [comment]
@mrdoob any comments? What did you decide?

**Comment by mrdoob** [comment]
I think it's great! But seems like no one is stepping in to give it a go 😕

**Comment by felixpalmer** [comment]
For reference, here is how earcut can be integrated with THREE.js (following the patching approach taken with pnltri.js):

```javascript
var toList = function ( contour, holes ) {
  var list = [];
  contour.forEach( function ( v ) { list.push( v.x, v.y ); } );
  holes.forEach( function ( hole ) {
    hole.forEach( function ( v ) { list.push( v.x, v.y ); } );
  } );
  return list;
};
var flattenShape = function ( contour, holes ) {
    var result = { vertices: toList( contour, holes ), holes: [], dimensions: 2 };
    var holeIndex = contour.length;
    holes.forEach( function ( hole ) {
      result.holes.push( holeIndex );
      holeIndex += hole.length;
    } );
    return result;
};
THREE.Shape.Utils.triangulateShape = ( function () {
  return function triangulateShape( contour, holes ) {
    var data = flattenShape( contour, holes );
    var result = earcut( data.vertices, data.holes, data.dimensions );
    var grouped = [];
    for ( var i = 0, il = result.length; i < il; i += 3 ) {
      grouped.push( [result[i], result[i+1], result[i+2]] );
    }
    return grouped;
  };
} )();
```

Generally I've found the performance and results to be great, in line with what is claimed on earcut's GH page. I've been testing on fairly difficult OSM forest outlines (which was crashing the built-in triangulation because it couldn't cut paths to the holes).

**Comment by mourner** [comment]
@felixpalmer great to hear that, thanks for looking into this! Would you be up to making a PR to THREE.js for Earcut integration?

I rewrote your code slightly to make it a bit faster and simpler (avoiding `forEach` in hot code):

```js
function addContour( vertices, contour ) {
	for ( var i = 0; i < contour.length; i++ ) {
		vertices.push( contour[i].x );
		vertices.push( contour[i].y );
	}
}

THREE.Shape.Utils.triangulateShape = function ( contour, holes ) {
	var vertices = [];

	addContour( vertices, contour );

	var holeIndices = [];
	var holeIndex = contour.length;

	for ( i = 0; i < holes.length; i++ ) {
		holeIndices.push( holeIndex );
		holeIndex += holes[i].length;
		addContour( vertices, holes[i] );
	}

	var result = earcut( vertices, holeIndices, 2 );
	
	var grouped = [];
	for ( var i = 0; i < result.length; i += 3 ) {
		grouped.push( result.slice( i, i + 3 ) );
	}
	return grouped;
};
```

@mrdoob would you only consider a THREE.js PR with the patched Earcut integration, or be up to a PR that fully replaces triangulation code with Earcut?

**Comment by mrdoob** [comment]
Lets start by doing a `webgl_geometry_text3.html` (based on `webgl_geometry_text2.html`) that uses Earcut 😊

**Comment by felixpalmer** [comment]
@mrdoob @mourner done. 

Also see http://www.piste.io/ for a larger integration, I use it to triangulate the forests

**Comment by MasterJames** [comment]
I get missing the following required extensions: OES_texture_float_linear
But on a Samsung Galaxy Note 3 
With Chrome 46.0.2490.76
It should not be not working I figured?

**Comment by Wilt** [comment]
If I am not mistaken earcut allows also for triangulation in 3rd dimension. This makes it possible to define something like a `THREE.Path3` and `THREE.Shape3` where points are all in the same 3D plane.

**Comment by mourner** [comment]
@Wilt note that Earcut triangulates 3D in the sense that z coordinate is disregarded (as if you triangulated a projection on a XY plane), but z coordinate is retained in the result. 3D triangulation is hard to define, but triangulation of a projection is one of the common approaches.

**Comment by Wilt** [comment]
So it will work as long the shape is not standing up straight? So as long as if the normal is not perpendicular to the z axis? Or am I mistaken?

**Comment by Wilt** [comment]
I made a fork from earcut and did some testing to see how it works. It can be found [here](https://github.com/Wilt/earcut/tree/threejs_develop/threejs_test) if someone is interested.

**Comment by WestLangley** [comment]
@Wilt  + 1

**Comment by Wilt** [comment]
I made an update for ThreeBSP [here](https://rawgit.com/Wilt/ThreeCSG/develop/examples.html) and it is working for indexed and non indexed buffer geometries.

**Comment by Wilt** [comment]
Here a first attempt to make some comparison of polygon tiangulation with the different libraries. For now I simply exchange the `Shape.Utils.triangulate` and `Shape.Utils.triangulateShape` methods with other ones depending on the chosen algorithm/library on runtime.
The multiple viewer is kind of nice because you can see the triangulation result of the 4 different algorithms in one overview...

When implementing this for real the code can of course be written much more efficient since now each method is adapted to the existing three.js code. 

It could also be a nice idea to allow the user to choose a triangulation library themselves. Why restrict it if it can work with several ones. Some will like the speed of earcut, others like maybe the results of poly2tri. We could just provide triangulation `adapters`. The different algorithm adapters can go in a `three.js/extras/triangulation` folder.

If we make more neutral code people can write even their own adapter to another triangulation algorithm/library and offer it in a pull request.

**Comment by WestLangley** [comment]
@Wilt Sweet! I like the [multi-viewer](https://rawgit.com/Wilt/three.js_triangulation/master/multiple.html?shape=24).

**Comment by Wilt** [comment]
@WestLangley Happy you like it :D Was that the most efficient way to get those cameras in sync?

**Comment by mrdoob** [comment]
Yeah, I like the [multi-viewer](https://rawgit.com/Wilt/three.js_triangulation/master/multiple.html) too! I think a great addition would be to show the shape that is being triangulated, and also the milliseconds that each library took.

**Comment by Wilt** [comment]
@mrdoob I will work on this as soon as I have some time. It might not be too soon, since I am also very busy with the project where I am using your awesome framework.

**Comment by WestLangley** [comment]
> was that the most efficient way to get those cameras in sync?

Probably. But I'd remove the animation loop. You don't need it. Use a modification of this pattern:
```javascript
controls.addEventListener( 'change', render );
```
