### ISSUE TITLE
Renderer clearColor Must be Specified in Premultiplied Form

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#5961]
With `renderer.premultipliedAlpha = true` (the default in three.js), the page compositor assumes the drawing buffer contains colors with premultiplied alpha.

Consequently, the clear color must be specified in premultiplied form. (At least on the browsers I have checked.)

For example, if the user wants a green background with 25% opacity, instead of this:

    renderer.setClearColor( 0x008040, 0.25 );

the user must do this:

    renderer.setClearColor( 0x002010, 0.25 ); // desired RGB is 0x008040; desired alpha is 0.25

Here is a fiddle: http://jsfiddle.net/ery6vwk2/. In the fiddle, the renderer's clear color RGB is the same as the color of the cube. The clear color alpha is 0.25.

You can see in the fiddle the bad things that can happen if you fail to premultiply properly.

I propose that the renderer be changed to handle this premultiplication behind-the-scenes, so the clear color can be specified in the more natural, non-premultiplied, form.

**Comment by mrdoob** [comment]
Sounds good to me.

**Comment by WestLangley** [comment]
OK, I'll do it.

**Comment by mrdoob** [comment]
Thanks again! ^^
