### ISSUE TITLE
THREE.SphereGeometry with Mercator projection

### ISSUE THREAD

**Issue by Ni55aN** [mrdoob/three.js#5967]
When I apply the texture of the surface of the Earth on the Mercator projection, I get the following:
![2015-01-21_232917](https://cloud.githubusercontent.com/assets/8259641/5857280/6ecf1da2-a25b-11e4-8125-59e3a1a00083.png)

How to convert coordinates of the vertices that it can be viewed properly?
IIt vertices instead Uvs, because the sphere may consist of several parts, textures are taken from Google Maps

**Comment by nojvek** [comment]
Any answers on this yet ?

I'm stuck on this too.
