### ISSUE TITLE
add Ray.distanceSqToRay?

### ISSUE THREAD

**Issue by froh** [mrdoob/three.js#5970]
@WestLangley  [stated](mrdoob/three.js/issues/5877#issuecomment-71119329) in #5877 that adding 'Ray.distanceSqToRay' is an issue on it's own, so here we go.

> As you know, three.js has no method Ray.distanceSqToRay(). And for good reason: the distance between rays is up to interpretation. You will have to create your own method.

What I don't see is how that could not be well-defined and up to interpretation?

**Comment by WestLangley** [comment]
1. How do _you_ define it?
2. What is the use case for such a method?

**Comment by froh** [comment]
**definition**: The unique minimal distance, the one that exists for any combination of line/ray/segment.  Of course the points of minimal distance might not be unique, for parallel lines only.  Just handle those like now.

**use case**: I have beams of light that come close to each other.  I want to visually highlight the closest possible connection between them, using a connecting line.  The intensity is then given by the (inverse of) the distance.  Think light sabers, or some infinite ray equivalent.  And segments won't help because I'm also interested in the rays meeting pretty far away and I'd prefer not to set arbitrary boundaries.

**Comment by WestLangley** [comment]
That is a fine mathematical definition.

However, for two back-to-back rays (sabers), pointing in opposite directions, and whose origins are arbitrarily close, but not touching, this definition results in an arbitrarily close distance value. I would not think that would be what you'd want, but that is just my opinion.

That is why I said the distance was up to interpretation, and why I asked for your use case.
