### ISSUE TITLE
THREE.Audio controls?

### ISSUE THREAD

**Issue by glennflanagan** [mrdoob/three.js#5972]
I'm looking to implement some sound effects into a game and I've been looking into the THREE.Audio object. I've got the sound effect loading into my scene but it just plays on load. 

Is there any way of controlling the playback so the sound effect plays on an event of my choosing?

**Comment by mrdoob** [comment]
Oh! Uh! Yeah, `THREE.Audio` is pretty limited right now. Shouldn't be hard to implement though! :)

**Comment by glennflanagan** [comment]
That's cool. I'm pretty novice when it comes to javascript stuff. I'll let you know if I manage to figure it out. :-)

**Comment by walden-** [comment]
Perhaps of interest:
  http://mohayonao.github.io/timbre.js/
  https://github.com/mohayonao/timbre.js/

Examples:
  http://mohayonao.github.io/timbre.js/reich.html
  http://mohayonao.github.io/timbre.js/satie.html

I found the API and docs quite confusing, but this is very powerful web audio stuff imho. It would be very cool to integrate [3D audio](http://creativejs.com/resources/web-audio-api-a-bit-more-advanced/) in that library and then use it with three.js.

mrdoob: btw: The author of that library lives in Osaka, Japan. I saw on your twitter feed that you visit that country sometimes. Perhaps you could have a chat with him :-)

**Comment by ducnguy** [comment]
mrdoob, can you give us a few pointers on where to start with the audio?  It looks like neither THREE.AudioListener nor THREE.Audio control the actual sound output.  I'm new to Three.js, too.  It's a great library, but I could use some help figuring out how the internals work.  I'm assuming some mastermind object handles output for all objects added to the scene.

Thanks in advance.

**Comment by mrdoob** [comment]
> Used from within the editor:
> http://threejs.org/editor/#app=https://gist.githubusercontent.com/walden-/98d41536d2e2e431a387/raw/7a7995623856a9d2624c1d4e1ebf942285e8c582/arkanoid.app.json

Haha! Wow! Ok, we need a way to include libraries... :)

**Comment by walden-** [comment]
Yes. I think [jspm](http://jspm.io/) & [systemjs](https://github.com/systemjs/systemjs) could be a perfect solution for that. With it we can easily include any JS package out there. When I can some time to hack for fun again...

**Comment by mrdoob** [comment]
Implemented in #6233.
