### ISSUE TITLE
Introduce modelViewProjectionMatrix

### ISSUE THREAD

**Issue by tsone** [mrdoob/three.js#5974]
Right now shaders do this to transform a vertex:
```
gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );
```

Instead we could have this, saving one matrix multiplication per transformation:
```
gl_Position = modelViewProjectionMatrix * vec4( position, 1.0 );
```

So we introduce a new premultiplied `uniform mat4 modelViewProjectionMatrix`.

Any comments?

**Comment by mrdoob** [comment]
Hmm, that sounds good to me.
/ping @bhouston @WestLangley

**Comment by bhouston** [comment]
instead of a new uniform, can we just multiple it at the beginning of the shader?  I notice a lot of issues with too many uniforms -- we need to use those sparingly.  But other than that I like it.

This really isn't much of an optimization though, it just makes the code prettier.

**Comment by bhouston** [comment]
To be clear, this isn't any real performance bottleneck compared unless you are just rendering say millions of points -- then transforming them is somewhat costly, but even then it likely isn't a huge improvement.

**Comment by mrdoob** [comment]
@tsone could you do some performance tests with/without?

**Comment by WestLangley** [comment]
> Right now shaders do this to transform a vertex:
> gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );

In the examples, yes. In the built-in shaders, this is the pattern that is used.

	#ifdef USE_SKINNING

		vec4 mvPosition = modelViewMatrix * skinned;

	#elif defined( USE_MORPHTARGETS )

		vec4 mvPosition = modelViewMatrix * vec4( morphed, 1.0 );

	#else

		vec4 mvPosition = modelViewMatrix * vec4( position, 1.0 );

	#endif

	gl_Position = projectionMatrix * mvPosition;

**Comment by tsone** [comment]
Well, traditionally this matrix has been available to developers, but I admit tradition is not a reason to have it. To summarize, _you don't appear to consider this necessary because_:

1. Built-in shader calculations are done in camera space, so anyway we need to do (at least) two matrix multiplications. @WestLangley
2. Performance benefit is only in the case vertex transformation is the bottleneck. @bhouston  
3. Would reduce the number of available uniforms. @bhouston 

Can't really defend against 1 as doing shading calculations in camera or world space is really the most intuitive way (compared to object and clip space). The points 2 & 3 however depend on the usage -- vertex transformations can be a bottleneck -- and this will cost only a few uniforms. Is it four slots?

Does anyone want it or should I close this?

**Comment by bhouston** [comment]
Four slots is huge as the minimum webgl spec only requires I think 16.
Everyday we see multiple threejs crashes on clara.io because of
insufficient uniform slots on low end webgl implementations.  I think it
sucks that the minimum spec isn't 128 or something higher.

**Comment by bhouston** [comment]
But maybe we should just give up on these 16 uniform webgl clients. So
maybe uniform pressure doesn't matter that much.

**Comment by tsone** [comment]
@bhouston Interesting. What clients are those? See http://webglstats.com/ data on max vertex shader uniforms. Also see [here](http://codeflow.org/entries/2013/feb/22/how-to-write-portable-webgl/#uniform-limits). The limits are much higher than 16.

**Comment by tsone** [comment]
Closed this due to lack of interest by community.
