### ISSUE TITLE
What happened to GeometryUtils.triangulateQuads ?

### ISSUE THREAD

**Issue by Ricket** [mrdoob/three.js#5977]
Maybe it's git ignorance on my part, but it looks like one commit it's there, and the next it's gone, though the commits never explicitly show it being removed.

You have this commit on March 1, 2014 where triangulateQuads is still there:
https://github.com/mrdoob/three.js/blob/8d71154ddd5c87ea105981a03bf75e99cc1cba9f/src/extras/GeometryUtils.js

And then this one, also (later) March 1, 2014, where it is missing:
https://github.com/mrdoob/three.js/blob/af6018ed4889ffd2a005b491970f38351505d559/src/extras/GeometryUtils.js

But the actual diff of the offending commit only shows a few lines added:
https://github.com/mrdoob/three.js/commit/af6018ed4889ffd2a005b491970f38351505d559

Is this a bug in Github? Was it removed on purpose?

**Comment by titansoftime** [comment]
This was probably done since Face4 was removed.

**Comment by mrdoob** [comment]
Yep! What @titansoftime said.
