### ISSUE TITLE
Viewport / Scissor works incorrectly with EffectComposer

### ISSUE THREAD

**Issue by mflux** [mrdoob/three.js#5979]
I wrote a "fix" for this issue, however I'm opening this as an issue in case someone runs into this identical problem.

This is the fixed version. Click to switch between renderer.render and composer.render.

https://dl.dropboxusercontent.com/u/705999/panoeffects/index.html

A bit of background: I'm trying to use multiple cameras and viewports to assemble a panoramic render. However, when I gave it to effect composer, the render seemed to be really messed up.

I discovered that I can't simply set the renderer.setViewport / scissor and call composer.render multiple times. This is because all shaderpasses will get the wrong viewport/scissor for rendering their quad.

The solve for this is to write a custom RenderPassViewports, like this:

    var RenderPassViewports = function ( scene, cameras, overrideMaterial, clearColor, clearAlpha ) {

      this.scene = scene;
      this.cameras = cameras;

      this.overrideMaterial = overrideMaterial;

      this.clearColor = clearColor;
      this.clearAlpha = ( clearAlpha !== undefined ) ? clearAlpha : 1;

      this.oldClearColor = new THREE.Color();
      this.oldClearAlpha = 1;

      this.enabled = true;
      this.clear = true;
      this.needsSwap = false;

    };

    RenderPassViewports.prototype = {

      render: function ( renderer, writeBuffer, readBuffer, delta ) {

        this.scene.overrideMaterial = this.overrideMaterial;

        if ( this.clearColor ) {

          this.oldClearColor.copy( renderer.getClearColor() );
          this.oldClearAlpha = renderer.getClearAlpha();

          renderer.setClearColor( this.clearColor, this.clearAlpha );
        }

        //  UHHHHHHHH
        //  I don't know why this is working but
        //  the first render is fucked up
        //  burn a render just so the projection matrix is ok
        //  WHAT???
        //  comment this out if you don't believe me
        renderer.render( this.scene, this.cameras[ 0 ], readBuffer, false );

        var first = 0;
        var last = this.cameras.length;

        for( var i=first; i<last; i++ ){
          var camera = this.cameras[ i ];
          var x = i * viewWidth;
          var y = 0;
          renderer.setViewport( x, y, viewWidth, viewHeight );
          renderer.setScissor( x, y, viewWidth, viewHeight );
          renderer.enableScissorTest( true );
          renderer.render( this.scene, camera, readBuffer, true );
        }

        //  restore this otherwise shaderpass will be messed up
        renderer.setViewport( 0, 0, views * viewWidth, viewHeight );
        renderer.setScissor( 0, 0, views * viewWidth, viewHeight );
        renderer.enableScissorTest( false );

        if ( this.clearColor ) {

          renderer.setClearColor( this.oldClearColor, this.oldClearAlpha );

        }

        this.scene.overrideMaterial = null;

      }

    };

For whatever reason, when rendering to a rendertarget, the first render will be completely messed up, as far as its camera / viewport projection goes.

The "fix" to this is to burn a whatever render so that the first viewport will have the correct view.

I realize that EffectComposer is not part of the main library, however I think this is a bug caused by the WebGLRenderer having invalid flags when rendering into a rendertarget. Perhaps someone smarter than me can investigate.

**Comment by bunnybones1** [comment]
Hey,
This may be related to this bug:
https://github.com/mrdoob/three.js/issues/6022
Not sure how you can test without hacking your copy of EffectComposer, but the workaround I found was to just call setViewport, setScissor, enableScissorTest and render twice. Wasteful, but I want to see what others say before trying a more involved solution.

**Comment by mflux** [comment]
The workaround was indeed to waste a render and the rest will be fine, you can even tell the renderer to render 0 pixels.

**Comment by bunnybones1** [comment]
Hey, try using `renderer.setRenderTarget` before the call to `setViewport`.

**Comment by DodekaHydra** [comment]
@mflux Does your fix work when using multiple different composers? I'm attempting to use multiple EffectComposers for different regions of my app to enable screen region restricted post-processing.

**Comment by mflux** [comment]
Yes I was able to get EffectsComposer working as well as WAGNER.

@bunnybones1 have not tried your fix yet, if I do I'll report back

**Comment by mrdoob** [comment]
> This is the fixed version. 

Do you have a link to the unfixed version? ^^

**Comment by mflux** [comment]
@mrdoob Here are the two versions for comparison

Fixed:
https://dl.dropboxusercontent.com/u/705999/panoeffects/index.html

Non-Fixed:
https://dl.dropboxusercontent.com/u/705999/panoeffectsbroken/index.html

@bunnybones1 Setting renderer.setRenderTarget does not produce the right results either. I'm confused about one thing though, is there a 'null' equivalent of setRenderTarget? Can I just pass nothing into that and have it render normally? Anyway, I've tried that as well and it does not produce a correct image.

**Comment by bunnybones1** [comment]
I've actually changed the implementation of setRenderTarget a bit to support not only viewport changes on renderTargets, but better handling of changing viewport even if you don't change the frameBuffer.

Here is an excerpt to help illustrate what I mean:
```

		var framebuffer, width, height, vx, vy, viewportChanged;

		if ( renderTarget ) {

			if ( isCube ) {

				framebuffer = renderTarget.__webglFramebuffer[ renderTarget.activeCubeFace ];

			} else {

				framebuffer = renderTarget.__webglFramebuffer;

			}

			width = renderTarget.viewportWidth;
			height = renderTarget.viewportHeight;

			vx = renderTarget.viewportX;
			vy = renderTarget.viewportY;

			//added by Tomasz Dysinski to support convenient renderTarget viewport clipping
			viewportChanged = renderTarget.viewportChanged;
			renderTarget.viewportChanged = false;

		} else {

			framebuffer = null;

			width = _viewportWidth;
			height = _viewportHeight;

			vx = _viewportX;
			vy = _viewportY;

			viewportChanged = _viewportChanged;
			_viewportChanged = false;

		}

		if ( framebuffer !== _currentFramebuffer || viewportChanged) {

			_gl.bindFramebuffer( _gl.FRAMEBUFFER, framebuffer );
			_gl.viewport( vx, vy, width, height );

			_currentFramebuffer = framebuffer;

		}

		_currentWidth = width;
		_currentHeight = height;
```
and here's a copy of three.js I'm using on a project that has this and a few other modifications.
https://gist.github.com/bunnybones1/d671d86b04787747657d

**Comment by mrdoob** [comment]
@bunnybones1 Looks good! Are you planning on doing PRs for these modifications?

**Comment by dmitriykovalev** [comment]
Hey guys! Do you have any update on this problem? It seems I have the same issue while doing stereo rendering to the texture and then to the screen. I have something like this:

```javascript
var texture = new THREE.WebGLRenderTarget(width, height, parameters);

// Left eye render to texture
renderer.setViewport( 0, 0, size.width, size.height );
renderer.setScissor( 0, 0, size.width, size.height );
renderer.render( sceneL, cameraL, texture );

// Right eye render to texture
renderer.setViewport( size.width, 0, size.width, size.height );
renderer.setScissor( size.width, 0, size.width, size.height );
renderer.render( sceneR, cameraR, texture );

// Render texture to the screen
renderToScreen(renderer, texture);
```

The problem: viewport for left eye (first render call) is ignored. The reason is inside setRenderTarget() call:

```javascript
  if (renderTarget ) {
     framebuffer = ...
			
     // !!! Previous call to setViewport() is completely ignored here !!!
     width = renderTarget.width;
     height = renderTarget.height;
     vx = 0;
     vy = 0;
  } else {
     ...
  }
  if ( framebuffer !== _currentFramebuffer ) {
     _gl.bindFramebuffer( _gl.FRAMEBUFFER, framebuffer );
     _gl.viewport( vx, vy, width, height );
     _currentFramebuffer = framebuffer;
  } 
```

As a workaround I call `setRenderTarget(texture)` before rendering image for left eye.

**Comment by YannisJ** [comment]
Hi everyone !

I also need to use EffectComposer and stereo rendering (StereoEffect or manual) on a project.

No update ?

**Comment by jeremypetrequin** [comment]
Hi,
any news about this ? For me the problem is StereoEffect + Glitch pass :)

thanks

**Comment by mrdoob** [comment]
@jeremypetrequin I just fixed a similar issue. Could you create a jsfiddle so I can take a look?

**Comment by schickling** [comment]
Having the same problem. Any update on this? :)

**Comment by mrdoob** [comment]
@schickling I need a jsfiddle. Can you help?

**Comment by drone1** [comment]
@schickling @YannisJ @mflux A jsfiddle for the doobmaster would be amazing.

**Comment by drone1** [comment]
@mrdoob BTW the jsfiddle three.js version is pretty old I believe (r54).

**Comment by drone1** [comment]
Alright, @mrdoob -- I went ahead and created the fiddle. Notes at the top of the JS buffer. Got it running on r73. https://jsfiddle.net/0brqhp70/60/

As the notes suggest, you'll want to change the global 'breakstuff' to true and the panels should render with weird, truncated viewports.

**Comment by mrdoob** [comment]
That's a bit of a complicated example to start with. It's hard to track where the issue is 😕

It'd be better to do a focused example from scratch instead.

**Comment by drone1** [comment]
Hm. I simplified it down to 3 panels, rather than 100 or whatever the example had. It's really just a core bit of code that matters here, but there is a bunch of scaffolding code needed to set things up. Hopefully this simplified version is enough -- and note that the majority of the code (past 150 lines or so) is just EffectComposer.js and RenderPass.js and so forth, since I was not able to include those files via JS tags. https://jsfiddle.net/0brqhp70/83/

**Comment by mrdoob** [comment]
Seems like it got fixed after all the viewport/scissor refactoring 😊
https://jsfiddle.net/0brqhp70/84/

**Comment by drone1** [comment]
Excellent!

So, quick question for you. I just pulled from master, built 74dev myself
(the version in the jsfiddle), via the suggested command from the github
page:

   node build.js --include common --include extras

However the version the jsfiddle is using (
https://rawgit.com/mrdoob/three.js/dev/build/three.js ) differs from my
locally built version quite massively. I could understand if it were a few
changes, but that isn't the case. Any idea why this is? Using my locally
built version vs. the jsfiddle version of 74dev rendered things quite
differently.

Also, the jsfiddle build did improve things for my app, but didn't quite
fix everything -- I may have bugs, not sure yet. Essentially my viewports
are now correctly rendering over the desired DOM elements (red clear color
rendered over the entire div), with the expected rendered content now
rendering starting at the lower-left corner of each div (before, rendered
content would have seemingly random margins) -- but the rendered content (a
quad with a fragment shader per div) is scaled down, all tiny, squished at
the bottom-left of each rect. If this rings a bell, please do let me know.
I'll investigate myself and see what I come up with.

Thanks again for looking into this!

[image: Screen Shot 2015-12-29 at 4.14.51 PM.png]

**Comment by mrdoob** [comment]
`master` is not `74dev`, you should pull from `dev` instead.

**Comment by drone1** [comment]
Sorry, new to git here. 

I originally cloned, then did 'git checkout dev' -- and now when I do 'git pull origin dev' and then build, I do have a '74dev' resultant three.js file, however it is still completely different from the '74dev' version on the jsfiddle.

**Comment by march1993** [comment]
74 & 75dev still have this issue.

**Comment by march1993** [comment]
```
renderTarget.scissorTest = true;
renderTarget.viewport.set(this.width / 2, 0, this.width / 2, this.height);
renderTarget.scissor.set(this.width / 2, 0, this.width / 2, this.height);
```


this can help
