### ISSUE TITLE
Complete Newb Needing come Help

### ISSUE THREAD

**Issue by Akfreak** [mrdoob/three.js#5980]
I am working on an OS Flight Controller software package here on Github. For our GUI, we need .json files that represent the drones our flight controller software controls. 

To make a long story short, I created all of the 3D models we need for our GUI in C4D. I can export ad an .OBJ and open them in Blender. However I have not a clue as to how to convert them with a three.js script into a .json procedural model.

I have spent hours trying to find a tutorial hon exactly what I need to do to achieve our goal. I know this isn't an issue for the three/js project.  I have looked and looked and looked through your folders to find a crumb for what I am supposed to do. Can someone help me figure out how to turn my models into a .json file.

Is there some sort of step by step tut for windows geared towards a non coding idiot like myself. I have limited git existence, but I can fork and clone a repo locally. 

If there are no tuts, would someone be wiling to help me convert the files?   I really appreciate your time and effort in response. I look forward to when this pat of the project is in the past and I know what the hell I am supposed to do. 

Here is a smale of the models that I created, and need to convert to .json https://flic.kr/p/qoUCtR and here https://flic.kr/p/qCzJqt  

Thanks, AKf

**Comment by mrdoob** [comment]
Load then into the http://threejs.org/editor/ and export from there.
