### ISSUE TITLE
Same scene in multiple WebGLRenderer instance

### ISSUE THREAD

**Issue by ron116** [mrdoob/three.js#5987]
I want to learn on account of this https://github.com/mrdoob/three.js/issues/1660. Now it is possible or nothing has changed?

To use the viewPort is very inconvenient.

**Comment by crobi** [comment]
I don't know whether that's possible or not, but note this: The [WEBGL_shared_resources](https://www.khronos.org/registry/webgl/extensions/WEBGL_shared_resources/) extension is still in draft and [apparently](http://webglstats.com/#highcharts-72) no browser supports it. This means that each webgl context needs its own copy of *all* GPU resources (geometries, textures, shaders, render targets, ...), along with whatever CPU resources browsers use to internally manage those GPU resources. There's nothing three.js can do about this.

I was working a site once which would contain several different DOM elements, each of them with a separate webgl context showing a single 3D object. We quickly realized that this is a very bad idea. The browser crashed often and/or refused to create more than around 10 contexts at a time. If possible, I would consider having one big webgl canvas with several small viewports and then use HTML controls on top of the canvas (as noted in #1660).

**Comment by mrdoob** [comment]
Fixed by #6723.
