### ISSUE TITLE
panorama preview and tiling

### ISSUE THREAD

**Issue by aboutqx** [mrdoob/three.js#5989]
Hi,i 'm just making a panorama with three.js and i made a example just like the demo in threejs.org.
  But i got a problem.I don't know how to load a preview and then attach the tiling image to the cube gemotry.It seems that threejs don't support tiling.So is there some way to have a pre-treatment to make it possiblly like the krpano,having a good experience?
  Thanks a lot.

**Comment by aboutqx** [comment]
By the way threejs is really awesome.

**Comment by mrdoob** [comment]
Tiling is supported as long as your texture sizes are are power of 2. It's a WebGL limitation.

**Comment by aboutqx** [comment]
Thanks for answering.But where can i find the documentation.

**Comment by mrdoob** [comment]
Power of 2 means that your texture needs to be one of these sizes: 64, 128, 256, 512, 1024, ... (width and height)

**Comment by aboutqx** [comment]
Thank you anway.
