### ISSUE TITLE
Is this expected behaviour for Three.Geometry and Lambert Material? (with JSFiddle)

### ISSUE THREAD

**Issue by DavidACL** [mrdoob/three.js#5998]
Hi,

Here is a JSFiddle with 3 green Three.Geometry and LambertMaterial-based meshes:   http://jsfiddle.net/DavidWaughRRRRRRRR/hoadj57w/4/light/

Is this JSFiddle showing expected behavior for cubes constructed of LambertMaterials and stored in a THREE.MeshFaceMaterial?

I have posted to Stack Exchange as well in an effort determine the cause of the lighting issue. Thanks.

Attempt 1:  http://gamedev.stackexchange.com/questions/93031/three-js-lighting-not-calculating-correctly-on-three-geometry-objects
Attempt 2: http://stackoverflow.com/questions/28215201/three-js-incorrect-light-on-three-geometry-lambertmaterial-meshes

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
