### ISSUE TITLE
STLLoader setResponseType is not defined?

### ISSUE THREAD

**Issue by jhi0417** [mrdoob/three.js#5999]
Hello,

I am trying to load up .stl file to my viewer so that I am using STLLoader.js; however, the console says that I can't load since setResponseType (on line 46) is not defined? in this case, what should I do?

Thanks!

**Comment by mrdoob** [comment]
Are you using the latest version of both the library and STLLoader?

**Comment by jhi0417** [comment]
Thanks for your message. I

**Comment by jhi0417** [comment]
Thank you. STLLoader is upto date. I will check the version of the lib.

**Comment by jhi0417** [comment]
Unfortunately, it still produces the same error. Would you take a look at the link? Thanks!
jhi0417.github.io/KIST_Algorithm_v2.0/kist_algorithm.html

**Comment by WestLangley** [comment]
You are using three.js r.64, which is more than a year old. Please update, and use stackoverflow for help if you need it.
