### ISSUE TITLE
Suggestion: Change 'object' name in JSON Scene Format

### ISSUE THREAD

**Issue by fraguada** [mrdoob/three.js#6005]
While it is easy enough to serialize JSON from different languages to the 4.3 JSON Scene format, maybe it would be a good idea to not use type names as properties for the JSON format.  While it is probably beyond the scope of this development, I would suggest to not use 'object' in the JSON Scene Format.  I am working in .NET, so its a tiny issue.  This is easily fixed by setting a specific mapping for the JSON property, but in general I am not sure it is a good idea to include language type names in there.  Just a suggestion.

**Comment by mrdoob** [comment]
What name would you suggest instead?

**Comment by fraguada** [comment]
As I understand it, these are the currently supported objects: https://github.com/mrdoob/three.js/blob/master/src/loaders/ObjectLoader.js#L220

Perhaps something like entity?

**Comment by mrdoob** [comment]
To be honest, I don't understand what this issue is about.

**Comment by fraguada** [comment]
In programing languages other than javascript 'object' is a type.  There could potentially be people writing interfaces to threejs from other programing languages, and perhaps in translation scheme, having JSON elements titled 'object' would come in direct conflict with the language typename.  It is not a huge deal, this can be worked around, it was just a suggestion.  In .net for example, this becomes an issue if building classes that map to the Scene format.  This is how I currently get around it in .Net:

public class SceneFile
{
public Metadata metadata { get; set; }
public IList<ObjectGeometry> geometries { get; set; }
public IList<Image> images { get; set; }
public IList<Texture> textures { get; set; }
public IList<ObjectMaterial> materials { get; set; }
[JsonProperty("object")]
public ObjectScene Object { get; set; }
}

Again, this is just a suggestion.

**Comment by satori99** [comment]
Can't you just prepend @ to the .NET keyword property names? Its been a while since I used .NET but I seem to remember that you could use keywords as var names with a prepended @.

**Comment by fraguada** [comment]
@satori99 Sure, that is also a possibility.

**Comment by mrdoob** [comment]
That sure sounds like a better solution than changing the file format :)
