### ISSUE TITLE
SpotLight direction not updated with target position change

### ISSUE THREAD

**Issue by Cubiverse** [mrdoob/three.js#6009]
I upgraded my game to r70 (From r63) and noticed that my torch was not moving with the camera.

I position the target for the spot light in-front of the camera, but it now appears I must manually call 

 this.flashLight.target.updateMatrix() ;

to get the light to follow the new target position.

Was this an intended change? If so please close this issue, but this did work correctly in r63 and before.

James

**Comment by WestLangley** [comment]
Duplicate of #5555.

Alternatively, you can add the target to the scene.

**Comment by Cubiverse** [comment]
Ah, my search powers were temporary disabled when I added this :S
