### ISSUE TITLE
Canvas renderer creates "overlapping triangles" at certain viewpoints

### ISSUE THREAD

**Issue by ururk** [mrdoob/three.js#6011]
I'm trying to use the canvas renderer, and it is not rendering correctly at certain angles. I've attached a series of images, and as you can see as the scene is viewed from different viewpoints, it looks like triangles from the yellow `BoxGeometry / MeshLambertMaterial` are being drawn on top of the blue boxes. 

* I tried switching to the WebGLRenderer, which renders it correctly.
* I tried both the current release (70) and dev release (71dev).
* I tried spacing the boxes a tiny bit apart form one another, at varying distances
* Safari 8.0.2 (10600.2.5), Chrome 40.0.2214.93 (64-bit)
* OS X 10.10.1
* NVIDIA GeForce GT 750M 2048 MB

The meshes are touching - but probably not overlapping.

My code is based on the voxel painter: https://github.com/mrdoob/three.js/blob/master/examples/canvas_interactive_voxelpainter.html

I get the same drawing artifacts with this example. It seems to be related to the lighting settings - if I refresh the voxelpainter sometimes I get these artifacts, other times I don't. That example randomly generates different directional light positions, so it could be bad lighting positions - but the fact that I don't get these in the WebGLRendered makes me suspect it might have to do with the CanvasRenderer.

![1](https://cloud.githubusercontent.com/assets/137989/5990833/d69a4260-a993-11e4-9875-da91ca770fb9.png)
![2](https://cloud.githubusercontent.com/assets/137989/5990834/d6a4e634-a993-11e4-95de-5778b432f3cd.png)
![3](https://cloud.githubusercontent.com/assets/137989/5990836/d6a7615c-a993-11e4-824a-026079d11a8f.png)
![4](https://cloud.githubusercontent.com/assets/137989/5990835/d6a673b4-a993-11e4-8484-3ce421016d35.png)

**Comment by WestLangley** [comment]
This is a known limitation of `CanvasRenderer`. The best you can do is to try tessellating your geometry. For example,

    THREE.BoxGeometry( 10, 10, 10, 4, 4, 4 );

**Comment by makc** [comment]
@WestLangley, 

well actually in his case he could do renderer.sortObjects = false and sort them appropriately. as far as the (bounding) boxes do not intersect, you don't need heavy guns like BSP.

in fact, I was solving very similar problem recently with webgl and transparent boxes (sucessfully). so, if you would be so kind to give me directions for the best way to create sorting 'plugin' for three.js, apart from renderer.sortObjects = false, I might do a PR to remove this limitation.

**Comment by WestLangley** [comment]
> well actually in his case he could do renderer.sortObjects = false and sort them appropriately.

For most view angles, a sort order does not exist that will render his scene correctly using `CanvasRenderer`.

**Comment by makc** [comment]
It exists for all the angles in his screenshots:
![screen shot 2015-02-23 at 1 57 10](https://cloud.githubusercontent.com/assets/242577/6321513/acd70d64-baff-11e4-8417-1e3ed4a77859.png)
and I am having troubles imagineing angles where it does not.

**Comment by WestLangley** [comment]
Yes, sorry, I overstated. I thought the boxes were intersecting...

What would be your algorithm for determining the sorting order?

**Comment by makc** [comment]
well I had linear scene.children and so I did just native .sort() with custom comparator that selected a plane between bounding boxes and sorted based on which side of the plane the camera was. obviously for tree-like hierarchy this might have to be done manually. the method still works if the boxes intersect, but of course in that case you again have artifacts. that's why I was thinking, it would be cool if we could select the sorting method, rather than completely replace the default.

**Comment by WestLangley** [comment]
Well, @mrdoob has added [`Object3D.renderOrder`](https://github.com/mrdoob/three.js/commit/052f81ab6ed877935ad4657453752e9efa8018a4). : - )

**Comment by makc** [comment]
If I just set these, wouldn't it be then sorted twice?

**Comment by mrdoob** [comment]
What do you mean twice?

**Comment by makc** [comment]
I mean 1st I sort stuf to produce indices, and then you sort stuff by those indices

**Comment by mrdoob** [comment]
Ah right. Well, considering it is `CanvasRenderer` and it's per object, it's not that bad. But yes, maybe a way of injecting your custom sorter is still needed.
