### ISSUE TITLE
Odd Issue with OBJ and Texture

### ISSUE THREAD

**Issue by robert-irribarren** [mrdoob/three.js#6015]
I have a problem I have a dds file i converted to jpg and a .obj file.
However when I render them in threeJS it looks wierd.

![problem](https://cloud.githubusercontent.com/assets/4400640/6006890/240ef80a-aacb-11e4-92bc-5761f08a5558.png)

​
I dont know what I am doing wrong with threeJS
Also on that webpage it can be viewed at
http://cutessica.com/ArchViewer/
Then click Party on the top and it will show that model.

Thank you in Advance.

P.S. I used the example code for the obj / material / texture on threejs which is shown here
http://threejs.org/examples/#webgl_loader_obj_mtl

![nu_f_sk_party001_v100_df](https://cloud.githubusercontent.com/assets/4400640/6006914/59373042-aacb-11e4-9815-3b06f732c38d.jpg)

if it helps these models were converted from .chr files and they are from the crysis engine 3 format

**Comment by titansoftime** [comment]
Have you tried flipping the texture vertically? I have to do this whenever I switch from dds to jpg/png.

**Comment by robert-irribarren** [comment]
I dont know what the code to flip the texture vertically is.
