### ISSUE TITLE
How to trouble shoot blender exporter errors?

### ISSUE THREAD

**Issue by kevzettler** [mrdoob/three.js#6016]
Is there a log or something I can look at to better understand these blender exporter errors?

I'm getting the following error when trying to export a scene. Anytime I try to included animation data in the export I hit this
![screenshot 2015-02-02 21 46 10](https://cloud.githubusercontent.com/assets/126209/6015087/04e6df4c-ab25-11e4-8fdb-a41a982731e7.png)

**Comment by repsac** [comment]
Don't rely on Blender's error dialog. Always look in a shell window, where you will find the path to the log file.

**Comment by repsac** [comment]
FYI I am considering disabling animation exports with scene exports. There is an issue with how Blender's handles its action data that appears to be difficult in a scene context. We are having enough issues right now with animation exports on single mesh nodes.

**Comment by BenediktS** [comment]
Blender is trying to enter the "EDIT" mode of an object. 
And that mode change is failing. 

I had the same error with an other script two days ago. 
In my case i had an Object that was not visible, and the script didn't check for this and crashed.  

maybe it is something similar here.

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
