### ISSUE TITLE
Ray.intersectTriangle() did not return if it hits the frontside or the backside.

### ISSUE THREAD

**Issue by BenediktS** [mrdoob/three.js#6017]
When i asked a DoubleSided Mesh if a ray is intersecting it, i get the point of the intersction or a NULL. But i didn't get the information if the intersection was on the frontside or the backside of the triangle. 

I don't know if there are many use cases for that problem, but i needed it.

So i did a quick fix for me. I know that this is not a good solution. 
(Thats why i did't put it in as a PR. )
https://github.com/BenediktS/three.js/compare/mrdoob:dev...Raycaster_intersectsFrontSide

Maybe there are more use cases and maybe u will find a better way.

**Comment by Usnul** [comment]
You could argue that there is no "front" side if it's double-sided. If back and front are important to you, perhaps it would make sense not to use 1-poly thick objects and make a convex shape instead?

**Comment by BenediktS** [comment]
One way to see it :) The other way would be: 

The shader hase gl_FrontFacing to determine on which side the texel is. So i could make different lighting and even different colors and textures on bothe sides of an mesh. Why should i use more vertices, faces, uvs and shaders then i need too?   

WebGL thinks of a mesh as a two sided object, and thats good for me :)

**Comment by Usnul** [comment]
because it adds a branch to your shader, causing every texel to take penalty for something that should be a rare case. Optimizations go both ways like that.

**Comment by Mugen87** [comment]
> I don't know if there are many use cases for that problem, but i needed it.

Closing, since this feature request is too use case specific. I've never seen that the raycast logic of a 3D engine or library reports such a result.
