### ISSUE TITLE
Format 4 Support

### ISSUE THREAD

**Issue by insominx** [mrdoob/three.js#6020]
I see a lot of great work being done with format 4 and the new Blender exporter (thanks @repsac).  However, there are many issues on the path between the export of the format and its loading.  

For **export**, as referenced in #5582 and #6016, there are many issues related to skinned meshes animations.
For **loading**, there seem to be **_2**_ options:

1) Use the `ObjectLoader` which doesn't support textures or `SkinnedMesh`
2) Load the file into a JSON object and then manually parse out the pieces you want using the old `JSONLoader` doing something like this:

``` javascript
var loader = new THREE.JSONLoader();
var json = JSON.parse(rawText);                     
loader.parse(json.geometries[0].data);
```

Neither of these options are a suitable replacement for the workflow we had with format 3.  Wouldn't it be better to wait until the feature sets and robustness of the exporter and loader mature a bit before completely replacing them?

**Comment by repsac** [comment]
Concerning the animations issues; the severe one (currently being discussed https://github.com/mrdoob/three.js/issues/5582) actually existed in the old exporter as well as we have been able to recreate with the exporter from r69 so it is accurate to state that the current exporter has indeed inherited bugs.

**Comment by repsac** [comment]
Actually I want to correct my previous comment (in respect to those who worked very hard on the now  deprecated exporter). The mislabeled "bug" with the animations is actually a result of editing the logic to utilize `pose.bone` data. This was included in the r67 release and tho it did solve issues for some users it actually broke animations for others (based on how their scenes were setup). I had released the new exporter with the pre-`pose.bone` data which would have been good news for the some pre-r67 users but was bad news for others.

Either way this issue would have come up eventually but the context would have been treated as just another bug if we were still on the old exporter, instead it was discovered in my exporter making it look like the source of the problem lay there and therefore drawing harsher criticism from users who weren't in favor of such a large change to the exporter's code base.

**Comment by insominx** [comment]
I appreciate the work you're doing with the new exporter @repsac.  I think the biggest issue is that there isn't a solid process to load format 4 files in yet.

**Comment by repsac** [comment]
I would agree with that and I do think there is some good intent behind the new scene format, but yes it is unfortunately lacking. I admit that I included features beyond the scope of the ObjectLoader (textures, non-embedded geometry files, etc) to spark a response from the community and hopefully get some momentum behind the development of the loader. Even if the momentum needs to come from myself, but first I need to own any issues in the new exporter to get it to a point (features, bugs, documentation) that users are comfortable with it.

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
