### ISSUE TITLE
EdgesHelper position broken since r67

### ISSUE THREAD

**Issue by BuildingJarl** [mrdoob/three.js#6023]
Link to codepen: http://codepen.io/anon/pen/yyzZym?editors=101

From r67 the positioning of the edgehelper object is off.

Reproduce: Open code pen link and in html change:

`src="//cdnjs.cloudflare.com/ajax/libs/three.js/r67/three.min.js"` 
to 
`src="//cdnjs.cloudflare.com/ajax/libs/three.js/r70/three.min.js"`

R67
![screen shot 2015-02-04 at 15 21 06](https://cloud.githubusercontent.com/assets/5493114/6043063/8bef35f4-ac81-11e4-9bbf-a2c18d248bd2.png)

R70
![screen shot 2015-02-04 at 15 21 25](https://cloud.githubusercontent.com/assets/5493114/6043065/935a0dbe-ac81-11e4-9e12-673eb2f1f058.png)

**Comment by WestLangley** [comment]
You need to add the helpers as children of the scene directly.

This is due to the following lines that appear in many of the helpers:

	this.matrix = object.matrixWorld;
	this.matrixAutoUpdate = false;

three.js r.70

**Comment by BuildingJarl** [comment]
@WestLangley Oh, ok thanks. I also saw your reply on stackoverflow.

Why was this changed? Can I close this issue?

The following seems to fix the problem:

```
ed.matrix = mesh.matrixWorld;
  ed.matrixAutoUpdate = true;
```

**Comment by WestLangley** [comment]
> Why was this changed?

I wasn't. If what you are doing worked before, it was by luck.

> Can I close this issue?

Yes.

> The following seems to fix the problem:

Not if you rotate the mesh. I would advise against doing that.

**Comment by BuildingJarl** [comment]
@WestLangley Rotating the mesh seems to also be working: http://codepen.io/anon/pen/ZYaEWy?editors=001

**Comment by WestLangley** [comment]
You are not rotating the mesh, you are rotating its parent object.

Also, if you add the mesh and helper in a different order, your method breaks:

      obj.add(mesh);
      obj.add(ed);

What you are doing is dangerous. I do not recommend it.

**Comment by BuildingJarl** [comment]
Alright, thanks for all your help.
