### ISSUE TITLE
SceneLoader with new format

### ISSUE THREAD

**Issue by jim3ds** [mrdoob/three.js#6024]
Hi, what is the recommended loader for this new blender exporter by Ed Caspersen?
I'm currently using threejs version 70. I tried it with sceneLoader but none of my objects showed up on the scene.

**Comment by repsac** [comment]
ObjectLoader is what you're looking for. It is important to note that many features (textures, non-embedded geometry, etc) are not yet supported by the ObjectLoader.

**Comment by jim3ds** [comment]
OK, thanks. I'll wait to use this new format and exporter when these features are supported.
