### ISSUE TITLE
Vertex Colors in OBJ Exporter

### ISSUE THREAD

**Issue by ekatzenstein** [mrdoob/three.js#6025]
I'm yet to do a pull request, so I'm going to file this as an issue for now.  I was interested in exporting OBJ files with vertex colors: https://gamedev.stackexchange.com/questions/21303/how-can-i-include-vertex-color-information-in-obj-files/66270#66270

So, I modified the OBJExporter script to include this.  This requires the user to add a list of vertexColors to the parse function (since coloration is currently saved in faces for some reason):

    /**
     * @author mrdoob / http://mrdoob.com/
     */

    THREE.OBJExporter = function () {};

    THREE.OBJExporter.prototype = {

	constructor: THREE.OBJExporter,

	parse: function ( geometry, vertexColors ) {

		var output = '';

		for ( var i = 0, l = geometry.vertices.length; i < l; i ++ ) {

			var vertex = geometry.vertices[ i ];
			output += 'v ' + vertex.x + ' ' + vertex.y + ' ' + vertex.z + ' ' + vertexColors[i].r + ' ' + vertexColors[i].g + ' ' + vertexColors[i].b + '\n';

		}

		// uvs

		for ( var i = 0, l = geometry.faceVertexUvs[ 0 ].length; i < l; i ++ ) {

			var vertexUvs = geometry.faceVertexUvs[ 0 ][ i ];

			for ( var j = 0; j < vertexUvs.length; j ++ ) {

				var uv = vertexUvs[ j ];
				output += 'vt ' + uv.x + ' ' + uv.y + '\n';

			}

		}

		// normals

		for ( var i = 0, l = geometry.faces.length; i < l; i ++ ) {

			var normals = geometry.faces[ i ].vertexNormals;

			for ( var j = 0; j < normals.length; j ++ ) {

				var normal = normals[ j ];
				output += 'vn ' + normal.x + ' ' + normal.y + ' ' + normal.z + '\n';

			}

		}

		// faces

		for ( var i = 0, j = 1, l = geometry.faces.length; i < l; i ++, j += 3 ) {

			var face = geometry.faces[ i ];

			output += 'f ';
			output += ( face.a + 1 ) + '/' + ( j ) + '/' + ( j ) + ' ';
			output += ( face.b + 1 ) + '/' + ( j + 1 ) + '/' + ( j + 1 ) + ' ';
			output += ( face.c + 1 ) + '/' + ( j + 2 ) + '/' + ( j + 2 ) + '\n';

		}

		return output;

	    }
     }

Any interest in updating the OBJExporter to have vertex coloration?

**Comment by mrdoob** [comment]
Sounds good to me, but I think you're using an old version of `OBJExporter` as base.

**Comment by NadirK** [comment]
Hi,

It's possible for someone to share the code to have vertex coloration with the last version of OBJExporter.

Thanks a lot !

**Comment by WestLangley** [comment]
@mrdoob Should this enhancement request still be open?

**Comment by mrdoob** [comment]
@WestLangley not sure... Vertex colors are not part of the OBJ format.

**Comment by WestLangley** [comment]
> Vertex colors are not part of the OBJ format.

Oh.
