### ISSUE TITLE
OBJMTLLoader no longer working! r70

### ISSUE THREAD

**Issue by Bigmacbook** [mrdoob/three.js#6026]
I'm using the example code from the example

https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_obj_mtl.html

I keep getting this error

``
Uncaught TypeError: undefined is not a function
OBJMTLLoader.js:22 THREE.OBJMTLLoader.load
``

**Comment by mrdoob** [comment]
I assume you closed it because you realized you were using mismatched versions?
