### ISSUE TITLE
Particle dissappear based upon camera angle

### ISSUE THREAD

**Issue by princemio** [mrdoob/three.js#6029]
Hey guys i have a problem. I have this problem in my code and also found it here in this example:

http://cabbi.bo/PhysicsRenderer/examples/collisions.html

If you use your mousewheel to go in the pointcloud . it dissapears ... you turn a little - it comes back...

it doesnt seem to be the clipping planes since they all dissapear at the same time.

It more seems like the renderer just stops executing this scene depending on the camera. 

Sorry if this is a noob question - or not an issue - but  i cant figure the issue out - and it looks very wrong.

thanks for your time

**Comment by WestLangley** [comment]
The bounding sphere of the `pointCloud` is computed by the CPU and is used for frustum culling.

The solution is to set

    particles.frustumCulled = false;

**Comment by princemio** [comment]
Boooom...thank you so much ...bounding box - cpu - culling -> nope i would not be able to fix it without your help...Thanks man !!!
