### ISSUE TITLE
How do I get point projection on a plane 

### ISSUE THREAD

**Issue by gezest** [mrdoob/three.js#6030]
Hi,
I have a a vector say (-22,5,0) and I want to project it on a plane. How can I do it. What I could do till now is plotting this point which is something like

particle = new THREE.Sprite( material );
particle.position.x = -22;
particle.position.y = 5;
particle.position.z =0;
and I have taken one plane as 
var planegeo = new THREE.PlaneGeometry( 1000, 1000, 10, 10 );

Now I want to have projection of this point on the planegeo. If take plane as 2d then it has some methos called .projectPoint (point, optionalTarget). Buth the problem is I am not able to plot a 2d object in 3d environment.
Can you please help?

**Comment by Usnul** [comment]
In general this is a ray casting problem. You can take a point and create a ray from it, with direction being equal to inverse of plane normal, then cast that ray onto the plane and read intersection coordinate. Here's the basic idea
``` javascript
var point = new THREE.Vector3(-22,5,0);
var normal = new THREE.Vector3(0,0,1);
var raycaster = new THREE.Raycaster(point,normal.clone().negate(), 0, Number.POSITIVE_INFINITY);
var planeMesh = new THREE.Mesh(planegeo, new THREE.MeshBasicMaterial());
var hits = raycaster.intersectObject(planegeoMesh,true);
var pointOnPlane = hits[0].point;
```
this is a sketch, read docs for more info.

If you are dealing with orthogonal projection, then perhaps you can just use plain ol' basic algebra

**Comment by gezest** [comment]
Thanks a Lot :+1:

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

Please use stackoverflow.
