### ISSUE TITLE
New Blender Exporter - dreadfully slow geometry processing

### ISSUE THREAD

**Issue by prima-meteria** [mrdoob/three.js#6031]
The new Blender Exporter looks very promising(combined with multiple UVs in particular), however there is a serious issue with its performance. Perhaps it's related to some dependencies, but on recent i7 3,7GHz it takes well over 20-60min to export 50k vertices while single core usage doesn't drop below 100%. Old exporter could do exactly the same job in a few seconds.
Perhaps there is something wrong with my software set, or dependencies, as recently there was really a lot of compilers, libraries and dependencies installed on this machine.

The exporter was hosted in Blender 2.73 x64 running on Windows 7 x64. It's definitely not hardware/performance related issue, but it resembles a lot opening large 3dsMAX project with tons of track-nodes. Test geometry was perfectly clean. Exported as OpenCollada 1.4.1, imported to clean blender scene and exported as JSON(vertices, normals, faces, UV1, materials, face materials, no scene, uncompressed geometry).

Has anybody experienced similar issues while working on real 3d models?

**Comment by repsac** [comment]
It's the normals logic. I think I already have this fixed. Using this test case (98k vertices)
![mesh info](http://i.imgur.com/pGci2P9.png)

You can see by the timestamps in the log is exports much faster.
http://pastebin.com/KUPGNfXC

This was the main culprit:
```
if vector not in vectors:
    vectors.append(vector)
```

It will be part of the next PR.

**Comment by prima-meteria** [comment]
Thank you for very swift response and pointing at source of the issue!

**Comment by repsac** [comment]
Fixed https://github.com/mrdoob/three.js/pull/6048/
