### ISSUE TITLE
Textures used in multiple scenes don't show unless needsUpdate called

### ISSUE THREAD

**Issue by DelvarWorld** [mrdoob/three.js#6033]
I ran into this issue while building a dynamic Three.js application that destroys and re-creates the renderer and canvas dynamically between route changes. Any textures used in an old scene, even if they are fully loaded, when placed into a new scene will not render until you set their `needsUpdate`

jsfiddle: http://jsfiddle.net/VsWb9/3146/ hit 'reset' which re-makes the scene (with the same texture), notice how the texture is blank until you set `needsUpdate`

While I'm not sure if this is a bug (since it's moderately edge-case behavior), it's inconvenient because all textures need to be tracked and reset in order for multiple scenes to be used.

Edit: I'm seeing this behavior in chrome, if that matters (img load events?)

**Comment by WestLangley** [comment]
Your fiddle is using a version of three.js that is more than 2 years old. Can you please replicate your issue using the most recent version?

Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by DelvarWorld** [comment]
@WestLangley ah, done. Didn't realize it was that old, that's the only option in JSFiddle default includes. I'll ping them about it.

It's even worse with r70: http://jsfiddle.net/VsWb9/3149/ setting needsUpate has no effect.

**Comment by hoschi** [comment]
I don't destroy my scene, but switch (already loaded) textures on button click. With WebGL renderer this is simple as:

```
mesh.material = new THREE.MeshLambertMaterial({
	map: texture
});
```

When I use CanvasRenderer, I need to recreate the texture:

```
mesh.material = new THREE.MeshLambertMaterial({
	map: new THREE.Texture(texture.image)
});
```

**Comment by dubejf** [comment]
This works in `r72dev` http://jsfiddle.net/VsWb9/3937/
