### ISSUE TITLE
Export-Blender: Generation of uuid is different on each export

### ISSUE THREAD

**Issue by jespa007** [mrdoob/three.js#6034]
Hi there,

Currently, the generation of uuid is different on each export. This means that if you have an object with a constant reference from imported file in a Three.js you have to change the uuid on each time you update the exported file.

Instead of generate an standard uuid on export,as I can see on [file basse_classes.py],(https://github.com/mrdoob/three.js/blob/master/utils/exporters/blender/addons/io_three/exporter/base_classes.py) line 70),

<pre><code class='haxe'>class Main
self[constants.UUID] = str(uuid.uuid4()).upper()
</code></pre>

My proposal is generate the uuid according the name of object/geometry/etc (that ensures it have to be unique in Blender),

<pre><code class='haxe'>class Main
def name2uuid(name):
    return str(uuid.uuid3(uuid.NAMESPACE_DNS, name)) 
</code></pre>

With this, we'll have the same uuid on each export (unless you change the name, of course).

**Comment by repsac** [comment]
The idea is fine tho the implementation should be something like

```
node = node or 'Scene'
self[constants.UUID] = str(uuid.uuid3(uuid.NAMESPACE_DNS, node)) .upper()
```

**Comment by Usnul** [comment]
i'm not sure uuid is intended to be a hash function of (only) name. Would generating seed for random be sufficient perhaps (based off file name/path).

**Comment by repsac** [comment]
Added https://github.com/mrdoob/three.js/pull/6048/
