### ISSUE TITLE
Export-Blender: Bad export when you have objects with childs

### ISSUE THREAD

**Issue by jespa007** [mrdoob/three.js#6035]
HI there,

I'm using blender 2.72b and I've created a basic scene like this,

![image](https://cloud.githubusercontent.com/assets/7852409/6091758/9e831a6e-aebb-11e4-97d4-7346a3e405f0.png)

In more detail, we have this scenegraph graphically,

![image](https://cloud.githubusercontent.com/assets/7852409/6091784/de98c012-aebc-11e4-80ac-29a5f1f3e74b.png)

I've exported the scene with these activated options,

![image](https://cloud.githubusercontent.com/assets/7852409/6091765/cb0f40a8-aebb-11e4-856e-e1db78fed56c.png)

I've got an exported file with this contents,
<pre><code class='haxe'>
{
    "metadata": {
        "type": "Object",
        "generator": "io_three",
        "version": 4.3
    },
    "materials": [],
    "object": {
        "type": "Scene",
        "matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
        "uuid": "8508E378-D9A7-4ABF-B1C2-B980A39A6ACE",
        "children": [{
            "type": "PerspectiveCamera",
            "name": "Camera",
            "uuid": "1A026B2A-99AC-42DF-BF2B-598A293C2E03",
            "position": [7.481131553649902,5.343664646148682,6.507639408111572],
            "rotation": [-0.6300000548362732,0.71399986743927,0.43338078260421753],
            "scale": [1.0,0.9999998807907104,0.9999999403953552],
            "visible": true,
            "far": 100.0,
            "near": 0.10000000149011612,
            "aspect": 1.7777777777777777,
            "fov": 35.0
        },{
            "type": "Mesh",
            "name": "Cube",
            "uuid": "A74C6626-F8E7-4D3C-AFCC-0B85915A94B4",
            "position": [0.0,0.0,0.0],
            "rotation": [-1.5707963705062866,0.0,0.0],
            "scale": [1.0,0.9999999403953552,0.9999999403953552],
            "visible": true,
            "castShadow": true,
            "receiveShadow": true,
            "geometry": "9E6F5BCE-D05C-4477-A13E-FD5AB36135A8"
        },{
            "type": "Mesh",
            "name": "Cube.001",
            "uuid": "748A09E4-8813-4295-AC11-37F0A4AC88F4",
            "position": [0.5430374145507812,2.4335718154907227,-4.228868007659912],
            "rotation": [-1.5707963705062866,0.0,0.0],
            "scale": [1.0,0.9999999403953552,0.9999999403953552],
            "visible": true,
            "castShadow": false,
            "receiveShadow": false,
            "geometry": "18FD6709-C8F4-4C34-A56F-7EFDE00D3C99"
        },{
            "type": "PointLight",
            "name": "Lamp",
            "uuid": "9806AC59-3766-4696-A98A-A50E1B38A6ED",
            "position": [4.076245307922363,5.9038615226745605,-1.0054535865783691],
            "rotation": [-1.8389947414398193,0.6021226644515991,1.931500792503357],
            "scale": [0.9999998807907104,0.9999998211860657,0.9999998807907104],
            "visible": true,
            "color": 16777215,
            "intensity": 1.0,
            "distance": 29.999982833862305
        }]
    },
    "geometries": [{
        "type": "Geometry",
        "uuid": "18FD6709-C8F4-4C34-A56F-7EFDE00D3C99",
        "data": {
            "name": "Cube.001Geometry.3",
            "metadata": {
                "generator": "io_three",
                "vertices": 8,
                "version": 3
            },
            "vertices": [-1.0,-1.0,-1.0,-1.0,1.0,-1.0,1.0,1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0,1.0]
        }
    },{
        "type": "Geometry",
        "uuid": "9E6F5BCE-D05C-4477-A13E-FD5AB36135A8",
        "data": {
            "name": "CubeGeometry.7",
            "metadata": {
                "generator": "io_three",
                "vertices": 8,
                "version": 3
            },
            "vertices": [1.0,0.9999999403953552,-1.0,1.0,-1.0,-1.0,-1.0000001192092896,-0.9999998211860657,-1.0,-0.9999996423721313,1.0000003576278687,-1.0,1.0000004768371582,0.999999463558197,1.0,0.9999993443489075,-1.0000005960464478,1.0,-1.0000003576278687,-0.9999996423721313,1.0,-0.9999999403953552,1.0,1.0]
        }
    },{
        "type": "Geometry",
        "uuid": "18FD6709-C8F4-4C34-A56F-7EFDE00D3C99",
        "data": {
            "name": "Cube.001Geometry.3",
            "metadata": {
                "generator": "io_three",
                "vertices": 8,
                "version": 3
            },
            "vertices": [-1.0,-1.0,-1.0,-1.0,1.0,-1.0,1.0,1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0,1.0]
        }
    },{
        "type": "Geometry",
        "uuid": "9E6F5BCE-D05C-4477-A13E-FD5AB36135A8",
        "data": {
            "name": "CubeGeometry.7",
            "metadata": {
                "generator": "io_three",
                "vertices": 8,
                "version": 3
            },
            "vertices": [1.0,0.9999999403953552,-1.0,1.0,-1.0,-1.0,-1.0000001192092896,-0.9999998211860657,-1.0,-0.9999996423721313,1.0000003576278687,-1.0,1.0000004768371582,0.999999463558197,1.0,0.9999993443489075,-1.0000005960464478,1.0,-1.0000003576278687,-0.9999996423721313,1.0,-0.9999999403953552,1.0,1.0]
        }
    }],
    "images": [],
    "textures": []
}
</code></pre>

As you can see we have a repeated geometry twice and the scene graph is not generated (all objects stays at the same level). A right json format could be the following,

<code><pre class='haxe'>
{
    "metadata": {
        "type": "Object",
        "generator": "io_three",
        "version": 4.3
    },
    "materials": [],
    "object": {
        "type": "Scene",
        "matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
        "uuid": "8508E378-D9A7-4ABF-B1C2-B980A39A6ACE",
        "children": [{
            "type": "PerspectiveCamera",
            "name": "Camera",
            "uuid": "1A026B2A-99AC-42DF-BF2B-598A293C2E03",
            "position": [7.481131553649902,5.343664646148682,6.507639408111572],
            "rotation": [-0.6300000548362732,0.71399986743927,0.43338078260421753],
            "scale": [1.0,0.9999998807907104,0.9999999403953552],
            "visible": true,
            "far": 100.0,
            "near": 0.10000000149011612,
            "aspect": 1.7777777777777777,
            "fov": 35.0
        },{
            "type": "Mesh",
            "name": "Cube",
            "uuid": "A74C6626-F8E7-4D3C-AFCC-0B85915A94B4",
            "position": [0.0,0.0,0.0],
            "rotation": [-1.5707963705062866,0.0,0.0],
            "scale": [1.0,0.9999999403953552,0.9999999403953552],
            "visible": true,
            "castShadow": true,
            "receiveShadow": true,
            "geometry": "9E6F5BCE-D05C-4477-A13E-FD5AB36135A8",
	    "children":[{
		    "type": "Mesh",
		    "name": "Cube.001",
		    "uuid": "748A09E4-8813-4295-AC11-37F0A4AC88F4",
		    "position": [0.5430374145507812,2.4335718154907227,-4.228868007659912],
		    "rotation": [-1.5707963705062866,0.0,0.0],
		    "scale": [1.0,0.9999999403953552,0.9999999403953552],
		    "visible": true,
		    "castShadow": false,
		    "receiveShadow": false,
		    "geometry": "18FD6709-C8F4-4C34-A56F-7EFDE00D3C99"
        	}]
        },{
            "type": "PointLight",
            "name": "Lamp",
            "uuid": "9806AC59-3766-4696-A98A-A50E1B38A6ED",
            "position": [4.076245307922363,5.9038615226745605,-1.0054535865783691],
            "rotation": [-1.8389947414398193,0.6021226644515991,1.931500792503357],
            "scale": [0.9999998807907104,0.9999998211860657,0.9999998807907104],
            "visible": true,
            "color": 16777215,
            "intensity": 1.0,
            "distance": 29.999982833862305
        }]
    },
    "geometries": [{
        "type": "Geometry",
        "uuid": "18FD6709-C8F4-4C34-A56F-7EFDE00D3C99",
        "data": {
            "name": "Cube.001Geometry.3",
            "metadata": {
                "generator": "io_three",
                "vertices": 8,
                "version": 3
            },
            "vertices": [-1.0,-1.0,-1.0,-1.0,1.0,-1.0,1.0,1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0,1.0]
        }
    },{
        "type": "Geometry",
        "uuid": "9E6F5BCE-D05C-4477-A13E-FD5AB36135A8",
        "data": {
            "name": "CubeGeometry.7",
            "metadata": {
                "generator": "io_three",
                "vertices": 8,
                "version": 3
            },
            "vertices": [1.0,0.9999999403953552,-1.0,1.0,-1.0,-1.0,-1.0000001192092896,-0.9999998211860657,-1.0,-0.9999996423721313,1.0000003576278687,-1.0,1.0000004768371582,0.999999463558197,1.0,0.9999993443489075,-1.0000005960464478,1.0,-1.0000003576278687,-0.9999996423721313,1.0,-0.9999999403953552,1.0,1.0]
        }
    }],
    "images": [],
    "textures": []
}
</pre></code>

Cheers,

**Comment by repsac** [comment]
It's not that I am disagreeing but have you actually tested the scenes in `three`? The first passes I worked on with this exporter did respect hierarchy however the result in `three` was not expected.

Blender scene
![blender](http://i.imgur.com/d0sQVxp.png)

JSON with no hierarchy 
http://pastebin.com/e8JZ2Fhj
![no hierarchy](http://i.imgur.com/4SE7KvN.png)

JSON with hierarchy
http://pastebin.com/Z88N0MMB
![with hierarchy](http://i.imgur.com/BsFfZSM.png)

I haven't been able to make sense on why the transformations are off and I can't isolate if its a problem with the JSON scene or in javascript land. The old exporter didn't preserve scene hierarchies as well and originally I thought this was an oversight and thought I would be cool and "fix" it, now I suspect there was a good reason for it.

Example scene from the old exporter.
http://pastebin.com/UJQV01EU

So this technically shouldn't be referred to as a "bad" export.

**Comment by jespa007** [comment]
Hi @repsac,
Thank for your response. The examples I gave is from how current [threejs editor](http://threejs.org/editor/) exports the scene. I made a simple scenegraph with two cubes as you can see on the picture below,

![image](https://cloud.githubusercontent.com/assets/7852409/6102547/ac9e3af6-b038-11e4-9990-719fd59f4c95.png)

And then I made an export to Scene

![image](https://cloud.githubusercontent.com/assets/7852409/6102552/bfe5dd12-b038-11e4-9324-e73dfd3710fe.png)

And the generated json is the following,

<pre><code>
{
	"metadata": {
		"version": 4.3,
		"type": "Object",
		"generator": "ObjectExporter"
	},
	"geometries": [
		{
			"uuid": "102DE542-3198-4708-A646-1155054FB182",
			"type": "BoxGeometry",
			"width": 100,
			"height": 100,
			"depth": 100,
			"widthSegments": 1,
			"heightSegments": 1,
			"depthSegments": 1
		},
		{
			"uuid": "9FCF7CC8-10DE-4022-B356-903843D59B31",
			"type": "BoxGeometry",
			"width": 100,
			"height": 100,
			"depth": 100,
			"widthSegments": 1,
			"heightSegments": 1,
			"depthSegments": 1
		}],
	"materials": [
		{
			"uuid": "FD516661-F293-41CB-97A2-A5DAE2C1CB49",
			"type": "MeshPhongMaterial",
			"color": 16777215,
			"ambient": 16777215,
			"emissive": 0,
			"specular": 1118481,
			"shininess": 30
		},
		{
			"uuid": "B2EB6680-873D-4DEA-AF66-802A35D43171",
			"type": "MeshPhongMaterial",
			"color": 16777215,
			"ambient": 16777215,
			"emissive": 0,
			"specular": 1118481,
			"shininess": 30
		}],
	"object": {
		"uuid": "521C7898-046C-4F29-94BA-14C54A54F767",
		"type": "Scene",
		"name": "Scene",
		"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
		"children": [
			{
				"uuid": "E8C9D5FC-0C69-433D-B087-65686A16A925",
				"type": "Mesh",
				"name": "Box 10",
				"geometry": "102DE542-3198-4708-A646-1155054FB182",
				"material": "FD516661-F293-41CB-97A2-A5DAE2C1CB49",
				"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,-85.09298706054688,-86.43683624267578,93.80416870117188,1],
				"children": [
					{
						"uuid": "AA588DB5-0F48-4FDD-82B2-F1B18867B594",
						"type": "Mesh",
						"name": "Box 11",
						"geometry": "9FCF7CC8-10DE-4022-B356-903843D59B31",
						"material": "B2EB6680-873D-4DEA-AF66-802A35D43171",
						"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,76.69000244140625,20.459999084472656,-50.9900016784668,1]
					}]
			}]
	}
}
</pre><code>


I think it shoud have the same behaviour as the exported from blender. 

Cheers,

**Comment by jespa007** [comment]
And sorry to call it "bad" export. I hope someone fix it soon :).

**Comment by repsac** [comment]
Test this branch. https://github.com/repsac/three.js/tree/io_three

I discovered that the logic had been creating Euler and not Quaternion values for rotation which caused children objects to be improperly rotated in the scene. Additionally the transforms on each had to be calculated from a local matrix in Blender to result in positional values that would work correctly in `three`.

![blender](http://i.imgur.com/WyEIhdD.png)
![three](http://i.imgur.com/NtCbjsf.png)

**Comment by repsac** [comment]
Updated https://github.com/mrdoob/three.js/pull/6048/

**Comment by repsac** [comment]
Removed this logic. There are far too many transformation issues to resolve without a lot more research and test cases to work through. For the time being the scenes will retain their flat hierarchy.

PR https://github.com/mrdoob/three.js/pull/6052

**Comment by Arioch77** [comment]
I'm experiencing the same export problem: the embedded geometry of each object in the scene is multiplied by the number of object in the scene. E.g.: I have a scene with 7 objects (no groups, no hyerarchies, all children of scene), i found 49 geometry definition... How can I solve this?

**Comment by repsac** [comment]
> How can I solve this?

By using the exporter in the `dev` branch.

https://github.com/mrdoob/three.js/issues/6045

**Comment by repsac** [comment]
Resolved https://github.com/mrdoob/three.js/pull/6172.
