### ISSUE TITLE
Vector3.applyMatrix4 inconsistencies

### ISSUE THREAD

**Issue by fta2012** [mrdoob/three.js#6039]
Currently Vector3.applyMatrix4 has a hidden assumption that the input matrix is affine. This is a very surprising and inconsistent behavior compared to Vector4.applyMatrix4.

This issue was the root cause of the bugs in https://github.com/mrdoob/three.js/pull/6038.

It seems like the change was introduced in https://github.com/mrdoob/three.js/issues/2921 for performance reasons. In that case I think the proper names should be:
  Vector3.applyMatrix4 -> Vector3.applyAffineMatrix4
  Vector3.applyProjection -> Vector3.applyMatrix4
since applyProjection is always safe and the other is an optimization you can take if you are sure the matrix is affine. It would also be great if there were some sort of debug build that has an console.assert((e[ 3 ] \* x + e[ 7 ] \* y + e[ 11 ] \* z + e[ 15 ]) == 1) to verify affineness to catch programmer errors.

Are there any benchmarks to show that this is actually a worthwhile optimization? If not I don't see why you would want to restrict parts of the library to just using affine transforms. I think it is much saner to just collapse those two back into one function.

**Comment by WestLangley** [comment]
> Currently Vector3.applyMatrix4 has a hidden assumption that the input matrix is affine.

Actually, comments in the code explicitly state the input matrix must be affine. The docs could be improved, however.

> This is a very surprising and inconsistent behavior compared to Vector4.applyMatrix4.

You cannot multiply a 3-component vector by a 4x4 matrix, so the methods must be inherently different.

> It seems like the change was introduced in #2921 for performance reasons.

It was also introduced because a perspective divide is only appropriate when applying a projection matrix, and when a further mapping from clip-space to NDC space is desired.

> Vector3.applyProjection -> Vector3.applyMatrix4 since applyProjection is always safe

`applyProjection` performs a perspective divide. It is only "safe" if that is what you want to do.

**Comment by fta2012** [comment]
Using homogeneous coordinates should be fairly common in the graphics community. Most people will probably just assume that (x, y, z) is represented by (x, y, z, 1) or equivalently, (xw, yw, zw, w) for some non-zero w, before getting multiplied by the 4 by 4 matrix. The perspective divide is just for converting back to inhomogeneous (dividing by w), and of course this is always safe to do even when dealing with affine instead of projective transforms.

This is a very nice chart stolen from this free ebook: http://szeliski.org/Book/ that summarizes the hierarchy of transforms dealing with homogeneous coordinates:
https://dl.dropboxusercontent.com/u/42955681/Screenshots/transformHierarchy.png
Note that all 3x4 transforms in this chart should have a 4th row of (0, 0, 0, 1)

**Comment by fta2012** [comment]
Discussions trailed off, but the bugs still exist: https://codepen.io/fta/pen/yVGLGB. The bug in that demo was caused by using applyMatrix4 instead of applyProjection and can be fixed in a one-off way:  https://github.com/mrdoob/three.js/pull/6038/files.

But the real fix should be to implement Vector3.applyMatrix4 the same way as Vector3.applyProjection. The two already always return the same result for affine matrices, but for non-affine applyMatrix4 is silently wrong. Why not just support the more general class of transforms? I think previous discussions got sidetracked talking about whether three.js can actually handle non-affine matrices but I think none of that really matters. This is the math sub-library and you shouldn't add a surprising special case to the well established mathematics of matrix-vector multiplication (or at least name it something less general than applyMatrix4 if you are going to do that).

I can send a PR to show what I mean more clearly but I will also understand if you guys don't care and want to keep this closed. (Even I don't have any real world use for this. I just can't get over getting burned by this unexpected behavior when I first ran into it.)

Sidenote: Current implementation of applyMatrix4 is confusing enough that whoever wrote the [documentation didn't even get it right](https://threejs.org/docs/?q=vector3#Reference/Math/Vector3.applyMatrix4). It describes it as a multiply with the first 3 columns but it should actually be a convert to homogeneous(add 1 on 4th dimension) then multiply with the first 3 rows. In other words it's the same as applyProjection but assuming affine where bottom row is [0, 0, 0, 1] so the multiply on that row and perspective divide can be omitted. If you didn't have this marginally useful optimization/distinction you wouldn't have these confusions to begin with!

**Comment by fta2012** [comment]
Example: https://github.com/fta2012/three.js/commit/643f292e9522a5031d4dcdfe6d2cfeaf0f31d008

**Comment by mrdoob** [comment]
@WestLangley Thoughts?

**Comment by WestLangley** [comment]
@fta2012 wrote

>Even I don't have any real world use for this.

Hmm.

Listen, https://github.com/fta2012/three.js/commit/643f292e9522a5031d4dcdfe6d2cfeaf0f31d008 is a reasonable change, but it is ~ 33% more ops for a highly-used method.

Our method avoids the perspective divide because we know it is 1 for affine input matrices.

Another option is to change the method name to something like `Vector3.applyAffineMatrix4()`.

Or, we could leave it as-is, and improve the documentation. Maybe @fta2012 would be willing to do that.

**Comment by fta2012** [comment]
I would be pretty surprised if it's actually 33% slower (due to instruction level parallelism, pipelining, data already in cache, etc). 

And it's premature optimization. I did a quick check with the chrome profiler and didn't find many examples where applyMatrix4 is called often enough to even show up in the profiler. The example with a bunch of [point lights](http://localhost:8000/examples/?q=light#webgl_lights_pointlights2) finally made it cost around 0.01% of total execution time:

![applymatrix4](https://cloud.githubusercontent.com/assets/575833/21291149/c93d7278-c489-11e6-8ba8-87c4ce0dc767.png)

That makes sense since you don't go transforming points individually all that often. Most of the cost is in multiplyMatrices:

![multiplymatrices](https://cloud.githubusercontent.com/assets/575833/21291116/0fe42862-c489-11e6-9841-61c14d4cb68f.png)

Anyway if you're still not convinced, I give up!

**Comment by WestLangley** [comment]
@fta2012 Your arguments are compelling, and I think your proposal has merits, in spite of my attempts to convince you otherwise. :-)

@bhouston @mrdoob The OP is proposing reverting https://github.com/mrdoob/three.js/issues/2921 and replacing it with https://github.com/fta2012/three.js/commit/643f292e9522a5031d4dcdfe6d2cfeaf0f31d008. It does result in a single method that "just works". Any thoughts/objections?

**Comment by bhouston** [comment]
From a mathematical perspective I prefer separate multiply and project
functions because they are different operations mathematically.

Best regards,
Ben Houston
http://Clara.io Online 3d modeling and rendering

**Comment by bhouston** [comment]
I have never liked the applyMatrix function name because it is ambiguous
mathematically.

Best regards,
Ben Houston
http://Clara.io Online 3d modeling and rendering

**Comment by WestLangley** [comment]
>I prefer separate multiply and project functions because they are different operations mathematically.

Actually, the OP is correc. They are not different operations mathematically. That is why, prior to #2921, when we had just one function for all  matrix types, it just worked.

The conceptual steps to apply any `Matrix4` to a `Vector3` are

1. convert Vector3 to Vector4 by adding a w-component of 1
2. call Vector4.applyMatrix4()
3. divide each component by the new w-component. (w is now 1)
4. convert the Vector4 back to Vector3 by dropping the w-component.

We only need one method to do that. It is just that we don't have to do the divide step if we know the value we would divide by is 1.

As I said in #2921, I can go either way, but I am leaning toward reverting back now.

@bhouston Given your knowledge of other math libraries, can you check if they have separate methods?

**Comment by bhouston** [comment]
IlmMath's multVecMatrix is unoptimized, it always does the divide: 

https://github.com/openexr/openexr/blob/develop/IlmBase/Imath/ImathMatrix.h#L2579

gl-matrix from the venerable toji has one function:

https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/vec3.js#L540

Unity 3D has a fast path that doesn't do the divide (MultiplyPoint3x4) and another that does (MultiplyVector):

https://docs.unity3d.com/ScriptReference/Matrix4x4.MultiplyPoint3x4.html
https://docs.unity3d.com/ScriptReference/Matrix4x4.MultiplyVector.html

**Comment by bhouston** [comment]
I would lean towards one function that always does the divide if that is what others are doing.  I think that trying to micro optimize out the divide when the divisor is 1 isn't that valuable, and no one else is doing that.  I think that is because "if" tests are themselves costly when mispredicted.

**Comment by WestLangley** [comment]
@bhouston OK, you pushed me off the fence. :)

I will collapse `applyMatrix4()` and `applyProjection()` into one method, and avoid the conditional. `applyProjection()` will be removed.

Thanks @fta2012.

**Comment by fta2012** [comment]
No problem. =)

By the way I actually already did the deprecating applyProjection in the branch I linked from 2 days ago: https://github.com/mrdoob/three.js/compare/dev...fta2012:vec3-applyMatrix4-applyProjection. It's already conflicting but if it will save you work I can clean it up (and remove the conditional) and submit a PR.

**Comment by WestLangley** [comment]
@fta2012 Sweet. Please do. The pattern now would be to add `applyProjection()` to `Three.Legacy` and remove it from `Vector3`.

Note in the PR that it fixes #6039.
