### ISSUE TITLE
ObjectLoader does not support loading SkinnedMesh

### ISSUE THREAD

**Issue by DaanBroekhof** [mrdoob/three.js#6040]
Currently only loads type 'Mesh', and I have to 'upgrade' them to SkinnedMeshes post-import.

The blender exporter unfortunately also exports meshes with skinIndices & bones to 'Mesh'.

(MorphAnimMesh also seems to be missing)

**Comment by donmccurdy** [comment]
There is some support for SkinnedMesh in ObjectLoader, and the JSON Blender exporter has been deprecated. Are MorphAnimMesh and MorphBlendMesh still needed, with the new animation system?

**Comment by Mugen87** [comment]
Solved via #20589.
