### ISSUE TITLE
Certain Chrome browser UI interactions stop or change rendering

### ISSUE THREAD

**Issue by joepie91** [mrdoob/three.js#6042]
I've run into some issues with getting three.js to correctly render the 'spinning cube' example from the documentation. I've uploaded that example here, and verified that the issue occurs for me: http://cryto.net/~joepie91/three-test/test/test.html

Initially, the cube would be rendered once, and then just remain static, no matter what I did or how many times I refreshed the page. After restarting Chrome, it works initially (displaying a spinning cube), and from then on only breaks in at least two reproducible scenarios:
1. When closing or opening the developer tools after loading the page, the animation stops.
2. When closing the 'extension overflow menu' ([image](https://cloud.githubusercontent.com/assets/1663259/6101099/586f03bc-b01e-11e4-8a2a-2fb39f1405fd.png)), whether by clicking the overflow button or clicking anywhere else in the browser UI or page, the animation stops.

Refreshing the page results in a spinning cube again.

The render loop is still taking place (I have verified this by logging to the console from within the render loop), but the view is simply no longer being updated. Frankly, I have no idea whether this is a three.js bug, but [get.webgl.org](http://get.webgl.org/) is _not_ exhibiting this issue for me, so I suspect that it may be three.js-specific.
- Operating system: openSUSE 13.1 x64 + XFCE
- Browser: Google Chrome 40.0.2214.111 (64-bit), installed from Google's repository
- GPU: XFX R7 260X 2GB, proprietary AMD Catalyst drivers 
  ([version numbers](https://cloud.githubusercontent.com/assets/1663259/6101185/d041d5f8-b01f-11e4-9965-7e55c224fa3d.png))

**Comment by joepie91** [comment]
The bug also occurs in incognito mode with all extensions disabled, and a 3rd reproducible case: opening and closing the 'main menu' of Chrome also stops the cube from spinning.

Additionally, rapidly mousing over the various menu options will noticeably slow down the spinning of the cube while the menu is open - once the mouseovers stop, the cube returns spinning at its regular speed.

It seems like the bug is triggered by a variety of Chrome browser UI interactions...

**Comment by joepie91** [comment]
A 4th reproducible case:

* Closing another tab by middle-mouse-button-clicking it, will also make the cube stop spinning.

Some other demos where I can reproduce the issue:

* http://threejs.org/examples/#webgl_geometry_minecraft
* http://threejs.org/examples/#webgl_geometry_minecraft_ao
* http://threejs.org/examples/#webgl_geometry_extrude_shapes

Some demos where I can __not__ reproduce the issue:

* http://threejs.org/examples/#webgl_gpgpu_birds
* http://threejs.org/examples/#webgl_geometries
* http://threejs.org/examples/#webgl_materials_cubemap_balls_reflection

This is a particularly interesting case - when triggering the bug, the field will stop rotating, but *the other animations continue*:

* http://threejs.org/examples/#webgl_buffergeometry_custom_attributes_particles

Another strange case - when triggering the bug, I stop being able to rotate the camera - instead, the cubemap(?) is being rotated directly on the geometry, as if it were a texture being translated and rotated, without the geometry being rotated in the view. The balls continue moving as before:

* http://threejs.org/examples/#webgl_marchingcubes

**Comment by joepie91** [comment]
Some further experimentation results:

When changing the following line in [the spinning cube demo](http://cryto.net/~joepie91/three-test/test/test.html)....

```javascript
var renderer = new THREE.WebGLRenderer();
```

... to ...

```javascript
var renderer = new THREE.WebGLRenderer({antialias: true});
```

... the bug completely and reproducibly disappears. It looks like it only manifests when `antialias` is set to `false`.

A version of the spinning cube demo with anti-aliasing enabled (ie. not manifesting the bug) can be found [here](http://cryto.net/~joepie91/three-test/test/test_aa.html).

**Comment by mrdoob** [comment]
This is definitely a bug somewhere in your setup. I would be it's the graphics drivers. Have you tried with the open source radeon drivers?

**Comment by joepie91** [comment]
Unfortunately, the open-source drivers are completely unusable with the card I have. When using them, my system can't run for more than a few minutes without locking up (a known issue with this specific card), so there's really no way for me to test that.

Do you have a testcase for me that functionally does the same as one of the problematic examples, but that uses WebGL directly instead of through three.js? That would perhaps be useful to establish whether the issue is solvable from within three.js.

I should note that I have not seen this issue in any regular OpenGL (non-WebGL) applications, and it only appears to manifest in Chrome.

**Comment by mrdoob** [comment]
Do you have issues with these lessons?
http://learningwebgl.com/blog/?page_id=1217

**Comment by joepie91** [comment]
I've tested all the WebGL versions of those lessons, and every single one of them works. I'm unable to reproduce the issue in any of them.
