### ISSUE TITLE
Help me about the TrackballControls.js rotation

### ISSUE THREAD

**Issue by sjavacat** [mrdoob/three.js#6043]
Hello , I encountered a problem now, on the TrackballControls.js file. This file can be rotated on the model, translation, scaling operation, but

When I rotate when the model, problem -- -- if it is the first time for loading model, the rotation is no problem, but if the translation operation on the model, then the model rotation,

So the effect of rotation will change, because the rotation is always the center point of the screen (center point or world coordinates) rotation, rather than to the center point of the rotation model, finally, the result I want 

When I rotate the camera (or is rotating model) appears on the screen effect is to center model as a focal point to rotate,   how to solve (had better give me a demo,my email is 1746265859@qq.com)?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

1. The controls are to be used for controlling a camera, not a model.

2. The center of rotation is `controls.target`. Try `controls.target = model.position;` or `controls.target.copy( model.position );`

If you need more help, please use stackoverflow.

**Comment by sjavacat** [comment]
sorry ,they are no use
