### ISSUE TITLE
Blender exporter module error when export with colors

### ISSUE THREAD

**Issue by s-a** [mrdoob/three.js#6044]
Exporting to JSON including Materials / Colors will result in an error.

![image](https://cloud.githubusercontent.com/assets/1270662/6116957/25f4b5b0-b0b1-11e4-8627-1df0336702e8.png)

**Comment by repsac** [comment]
Duplicate https://github.com/mrdoob/three.js/issues/6019

**Comment by repsac** [comment]
Fixed: https://github.com/mrdoob/three.js/pull/6048/
