### ISSUE TITLE
Blender Exporter: omit emissive and ambient properties from MeshBasicMaterial

### ISSUE THREAD

**Issue by repsac** [mrdoob/three.js#6046]
This results in a JSON that does not load correctly because the loader does not check that the properties exist on the material before setting them.

```
		if ( json.ambient !== undefined ) material.ambient.setHex( json.ambient );
		if ( json.emissive !== undefined ) material.emissive.setHex( json.emissive );
```

Going to make sure the JSON omits these properties when the material is a MeshBasicMaterial

**Comment by WestLangley** [comment]
The `ambient` property has been removed in #5809.

**Comment by repsac** [comment]
Ah thanks. And @mrdoob pinged me as well and I totally missed it.

**Comment by repsac** [comment]
Fixed https://github.com/mrdoob/three.js/pull/6048/
