### ISSUE TITLE
Blender Export Scene Rotation Issue

### ISSUE THREAD

**Issue by poofik** [mrdoob/three.js#6051]
The rotations with 0,0,0 are not showing Z up (SCENE Export) - Any one else experiences this?
Other objects (pillows+stool) have a slight rotations.

![screen1](https://cloud.githubusercontent.com/assets/4879613/6141613/27991490-b15d-11e4-8209-651f14afca09.png)

![screen2](https://cloud.githubusercontent.com/assets/4879613/6141644/335c7f56-b15d-11e4-94c8-435fa0e64234.png)

**Comment by repsac** [comment]
Is there a scene you can share? For this screen shots are not going to be very useful.

**Comment by repsac** [comment]
I was able to recreate the transformation discrepencies. Right now I am trying to figure out why I am getting the positional and rotation values that I am getting from Blender.

**Comment by repsac** [comment]
OK I can't really make sense of how Blender is computing is rotational values in a way that makes sense to three when trying to preserve object hierarchies. Restoring the previous logic which places every object at the same level of the scene graph. PR coming very soon.

**Comment by repsac** [comment]
PR https://github.com/mrdoob/three.js/pull/6052

**Comment by poofik** [comment]
Here is late attachment https://drive.google.com/a/iroot.ca/file/d/0Bx8oWMCrHXIaSTE1ZnZsWlZCNTQ/view?usp=sharing

**Comment by repsac** [comment]
requested access

**Comment by poofik** [comment]
I want to thank you for all your work on this. the PR #6052 works beautifully! and I really like the precision point. After setting it to 2 - my 3D models shrunk 3 times!

Thank you

**Comment by repsac** [comment]
Good to hear!
