### ISSUE TITLE
maya 2015 export plugin errorrs

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6053]
So, 1st of all it requires pymel, which [latest version from 2012](https://code.google.com/p/pymel/downloads/list) does not even install, unless you patch it [like this](http://notes.richdougherty.com/2012/07/python-setuptools-bootstrap-errors.html).

2nd, after you go all the way and try to enable it in Maya, you get this:
```
// Error: line 1: ImportError: file /Volumes/HDD/Applications/Autodesk/maya2015/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/site-packages/pymel-1.0.0-py2.7.egg/pymel/internal/parsers.py line 11: No module named BeautifulSoup // 
// Warning: line 1: Failed to run file: /Users/makc/Library/Preferences/Autodesk/maya/2015-x64/plug-ins/threeJsFileTranslator.py // 
// Error: line 1:  (threeJsFileTranslator) // 
// Error: file: /Volumes/HDD/Applications/Autodesk/maya2015/Maya.app/Contents/scripts/others/registerVectorRenderer.mel line 71: The renderer mayaVector is already registered.  To edit it, use the "-edit" flag. // 
```

**Comment by makc** [comment]
So I manually downloaded BeautifulSoup.py from 3.2.1 and placed it under /Volumes/HDD/Applications/Autodesk/maya2015/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/site-packages/ - now the error says:
```
// Error: line 1: IOError: file /Volumes/HDD/Applications/Autodesk/maya2015/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/site-packages/pymel-1.0.0-py2.7.egg/pymel/internal/parsers.py line 368: Cannot find maya documentation. Expected to find it at /Volumes/HDD/Applications/Autodesk/maya2015/docs/Maya2015/en_US // 
```

**Comment by makc** [comment]
Useless 1G download. Pymel expects API subfolder with files like /Volumes/HDD/MayaHelp2015_enu/API/class_m3d_view.html which is not there.

**Comment by makc** [comment]
:shit: :shit: :shit:
looks like [pymel moved to github](https://github.com/LumaPictures/pymel) and I was wrong to assume google code has the latest version. any way, this does not seem to be directly relevant to the exporter, so closing.

**Comment by MichaelHazani** [comment]
Did installing the most recent version of pymel solve the error? So far I've inadvertently followed in your footsteps (got pymel from google code) and received the abominable "line 71: The renderer mayaVector is already registered.  To edit it, use the "-edit" flag.". How did you get rid of it? Thanks!

**Comment by makc** [comment]
I don't remember ( Most probably I've found some way not involving using the exporter.

**Comment by mprice1** [comment]
Just ran into this today...
MichaelHazani: Did you make any headway here?

I notice that for me, an older version of the three.js maya exporter works as expected (while still depending on PyMel). But it does not support bones/animation, which I need... 
I get the same errors as above.

**Comment by Dynasty9** [comment]
We have an exporter that handles this functionality at
https://github.com/BlackTowerEntertainment/animation-tools

**Comment by MichaelHazani** [comment]
@mprice1 : fixed in Maya 2016. No idea what was wrong but upgrading Maya and reinstalling pymel and the plugins solved it. Haven't experimented with rigging yet - I'll look into @Dynasty9 's recommendation if it breaks again (but since my plugin issues started at runtime, I doubt I'll get the problem again.)
