### ISSUE TITLE
three.objectloader.js doesnt handle textures

### ISSUE THREAD

**Issue by jeromeetienne** [mrdoob/three.js#6054]
Hi

in [three.objectloader.js](https://github.com/mrdoob/three.js/blob/dev/src/loaders/ObjectLoader.js#L35) i dont see the texture handling, is that normal ?

I try to export model from blenders, and the exported .json file is marked as ```metadata.type === 'object'; metadata.version === '4.3' ```. This file includes fields for ```.textures``` and ```.images```.

How to load them ?

**Comment by poofik** [comment]
Not yet - but this mod handles it OK https://github.com/denzp/three.js/commit/c069ec1b26014b55bc961846feaf7f7554fc2bb2

**Comment by jeromeetienne** [comment]
Interesting! I will look

Is that the recommended way to handle it? Or just a way which works well
for you?

**Comment by poofik** [comment]
Just my way - it works nicely with zipped models http://stuartk.com/jszip, I read zip file using AJAX than JASON.Parse the data and pipe it to ObjectLoader2

**Comment by AlexRablau** [comment]
Hi poofik, I am trying to get ObjectLoader2 to load a basic cube but it never calls my onComplete function when I call load. If I switch back to ObjectLoader, the onComplete is called and the object is added to the scene. Should the onComplete be different in any way? Why might this be happening?

**Comment by mrdoob** [comment]
#5502

**Comment by casanueva** [comment]
is this resolved? cant get a scene in blender with animations to work with three.js. I figured that i couldnt use the JSONloader and tried the ObjectLoader. I even tried the SceneLoader. Either i get the undefined materials error or i get the undefined textures error. Cant get this to work and i dont really see how i can debug this error.
