### ISSUE TITLE
new THREE.ShadowMesh and Demos

### ISSUE THREAD

**Issue by erichlof** [mrdoob/three.js#6060]
Hi everyone,
I have been looking for an easy way to add simple planar shadows to my Mesh objects without resorting to ShadowMaps (which run slowly even on my latest Samsung smartphone).  Since there weren't any pre-existing methods, I decided to create one!  Here's a demo: 
[ShadowMesh-Demo](http://erichlof.github.io/ShadowMesh-Demo/webgl_shadowmesh.html) <br>
A demo showing use of ShadowMeshes for groups of objects (which are not children of the Scene, but children of a THREE.Group parent):
[ShadowMeshGroup-Demo](http://erichlof.github.io/ShadowMesh-Demo/ShadowMeshGroup-Demo.html)  <br>
And here is a more advanced demo showing the capability of multiple shadow instances tracking their parent objects,  which can be used for multiple wall planes in a small room:
[ShadowMesh-MultipleInstancesDemo](http://erichlof.github.io/ShadowMesh-Demo/ShadowMesh-MultipleInstancesDemo.html) <br>

The proposed new ShadowMesh's constructor looks like this:
```javascript
var shadow = new THREE.ShadowMesh( parentMesh );
```
There are about 20 lines of setup before you can call this method, but most of those lines should already be in any three.js app anyway - such as creating a scene, a light source, and a Mesh object.  The new method's additional setup requires creating a ShadowMesh that will act as the shadow to its parent.  Also a THREE.Plane() object and a THREE.Vector4D() object must be created to be passed into the ShadowMesh's 'update' method.  Detailed, step-by-step instructions can be found here:
https://github.com/erichlof/ShadowMesh-Demo

Once these setup steps are complete, the actual usage is just 1 line of code!  For instance: <br>
```javascript
shadow.update( groundPlane, lightPosition4D );
```

The above line of code is called once every animation frame to continually update the shadow to match its parent.  This update method is where the magic happens: the shadowMesh 's geometry is essentially skewed and squashed down flat onto the specified plane.  It is then rotated, translated, and scaled to match its parent.  The result is a simple, fast-performing, correct planar shadow.

As with any shadowing method, there are limitations: <br>
 1. These planar shadows are confined to the plane that you specify.  They will not 'crawl' up the walls or darken other meshes, unless you create multiple instances like in the advanced demo above.  If you need ultimate robustness, three.js ShadowMaps may be your best choice.  Three.js used to also have support for volumetric stencil shadows, but they are no longer found in the codebase.
 2. Since these shadows are confined to the plane, they might run off the edge of the plane into space.  Some ways of getting around this are to have the background the same color as the shadow, or have a very large ground plane, or cover the edges with another plane as in room corners.
 3. A separate 'ShadowMesh' must be created for every Mesh that you want shadowed in the scene.  This should perform fine, but if the number of objects gets into the 1000's, again ShadowMaps are probably the way to go.
 4. If the parent Mesh has holes in it, such as the purple ring-shaped torus in the above demo, its shadowMesh will darken in the overlapping areas of outside-facing triangles and inside-facing triangles.  Not a deal-breaker, but an artifact non-the-less.
 5. Also if a planar shadow overlaps another planar shadow, the resulting shadow will darken.
 6. All shadows of this type are hard-edged shadows, with no possibility of soft-shadows.  In the real-world, shadows are rarely this sharp and defined.

If you can live with the above limitations, planar shadows can be an effective alternative to ShadowMaps.  Despite their limitations, Planar shadows perform extremely well, even on my mobile devices.  And they are mathematically correct, giving a sense of real depth to your scene.  Let me know if you think a feature like this would be useful to three.js users.

Thanks, :-)
-Erich
(edited on 2/13/15 to reflect the new naming)

**Comment by Usnul** [comment]
Why not advance stencil shadows instead? I'm not sure if im missing something, but effect should be the same, except you don't have the mentioned limitations. What is the value of a shadowing mechanism that only projects onto a plane? Outside of a scene with planar floor representation - i struggle to see it, too specialized. Nice looking demo though!

**Comment by erichlof** [comment]
Hi @Usnul ,

   Yes I would prefer stencil shadows to be reinstated in the three.js core, but support was dropped back in 2011 I believe, in favor of shadow maps.  Shadow maps are nice, but on mobile, even on a simple 4-object demo scene, my framerate drops significantly.  On the other hand, Stencil shadows run at 60fps even on my older smartphones.  Here's an example that runs fast on all my devices:
http://playtankworld.com/demo/stencil_shadows

    But I wouldn't know how to maintain that code or re-introduce it back into three.js, especially if the library is moving towards BufferGeometry for everything (as you know, shadow volumes must be calculated from the geometry's silhouettes which is not trivial).

   So in the meantime, I came up with the planar ShadowMesh solution, which despite its limitations, look correct to me and run at 60fps on small devices!  Most webpages I've seen that use three.js in a casual manner, such as 3d navigation menu items and floating geometry, would benefit greatly from this approach IMO because it gives the sense of depth without drop in frame rate for mobile.

If you understand the inner-workings of stencil shadows, please start a PR.  I would love to help with that project and contribute! :)

**Comment by kishore25kumar** [comment]
@erichlof can I use it for Object3D also instead of mesh

**Comment by erichlof** [comment]
Hi @kishore25kumar ,
Unfortunately it has to be a mesh.  Look at these lines from my source code:
https://github.com/erichlof/ShadowMesh-Demo/blob/gh-pages/ShadowMesh.js#L9-L20

The function takes a Mesh as an argument and then calls THREE.Mesh with the geometry parameters for that particular mesh.  Object3d is more of a higher-level mathematical structure that is extremely useful for 3d representation and manipulation.  But it does not have a real geometry associated with it, which the ShadowMesh constructor needs. 

It doesn't matter what the material is for the original Mesh that you pass into the constructor.  As you can see from the source code, it gets overwritten with a dark transparent shadow-like basic material anyway.  But it absolutely needs the original Mesh geometry, otherwise the shadow shape will be undefined.

Hope this answers your question :)
