### ISSUE TITLE
Inaccurate calculation of vertex positions in the projection

### ISSUE THREAD

**Issue by Ni55aN** [mrdoob/three.js#6066]
There is a sphere of radius 7000 that is wrapped in Object3D with the position (0,0,0)
When the zoom camera as close as possible to the heights (eg 0.2 from vertices), we get the following: 

![2015-02-13_120123](https://cloud.githubusercontent.com/assets/8259641/6184909/c5539aa8-b378-11e4-811e-9f8e78f2360f.png)

That is, the larger the value of the vertices, the worse the approximation accuracy in the camera thereto. And if the node is in the center Object3D, then there is no such problem. How to fix it?

Changing near and far does not give any result, works only if remove Object3D and set the vertices of the geometry closer to the center of the scene

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by Ni55aN** [comment]
Why is this not a bug?
A few tips for dealing with this proobemy not help

**Comment by mrdoob** [comment]
A working example (rather than a screenshot) would be helpful in this case.

**Comment by Ni55aN** [comment]
mrdoob, http://jsfiddle.net/eho5g2go/4/ please

**Comment by WestLangley** [comment]
http://stackoverflow.com/questions/28504272/inaccurate-calculation-of-vertex-positions-in-the-projection
