### ISSUE TITLE
Raycaster only intersect when near

### ISSUE THREAD

**Issue by Elzean** [mrdoob/three.js#6068]
Hi,

i'm trying to use the Raycaster and it works fine but only when i am near the object. The distance value from the Raycaster result is always less than 5, most of the time it's around 3 any futher than that and i have no result even though the object is not that small on screen.

I tried the example with the dragable cubes and everything works even from ffar where the cube a tiny.

I can't figure what is wrong with my setup, i tried several ways (with and without setFromCamera) they all work but always when i'm close to the object.

here is my current code : 

```javascript
var directionVector = new THREE.Vector3(mouse.x, mouse.y, 1);
var raycaster = new THREE.Raycaster();
raycaster.setFromCamera(directionVector, camera);
var intersects = raycaster.intersectObjects(scene.children, true);

for (var i = 0; i < intersects.length; i++)
{
       var selected = intersects[i].object;
       console.log(selected.material.name);
       if(selected.material.name=='Screen')
       {
             console.log(intersects[i]);
       }
}
```

When i test i only zoom in until i am near enough the Mesh with the material named 'Screen' and then it works.

What could cause this problem ?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
