### ISSUE TITLE
Trackball/Orbit don't work through iframe in Mac Safari

### ISSUE THREAD

**Issue by mstrater** [mrdoob/three.js#6074]
Open http://threejs.org/examples/#misc_controls_trackball (or the orbit example) in Mac Safari (I'm running Version 8.0.3). Mouse wheel zoom does not work. It works fine when loading without the iframe: http://threejs.org/examples/misc_controls_trackball. This issue affects the product I work on, so I will be looking into it, and I'll report back with information and hopefully a solution.

**Comment by mstrater** [comment]
http://kb.tableau.com/articles/issue/scroll-bars-in-embedded-views-do-not-work-in-safari On first look this seems to be the solution.

**Comment by mstrater** [comment]
Not a pretty solution, but here's a pull request #6075

**Comment by mstrater** [comment]
New pull request targeting the dev branch: #6099

**Comment by mrdoob** [comment]
Merged! ^^
