### ISSUE TITLE
Bug in Subdivision Modifier with three.js R_69

### ISSUE THREAD

**Issue by Ice101781** [mrdoob/three.js#6076]
Whenever I attempt to modify BoxGeometry with the Subdivision Modifier, I get a "can't read property 'x' of undefined" error in three.js. The error originates in the THREE.Vector3() function of the code; more specifically, the error is inside the .addvector() method, although that may only be because it's the first function that references 'x' inside THREE.Vector3(). Is anyone else experiencing this same issue?

**Comment by WestLangley** [comment]
The current version is r.70.

http://threejs.org/examples/webgl_modifier_subdivision.html

**Comment by Ice101781** [comment]
Okay, thanks for that example. I seem to be able to modify the geometry correctly; however, only bits and pieces of the normal map I applied to the BoxGeometry are visible. The rest is black. What could be causing that?

**Comment by Ice101781** [comment]
Actually, now that I'm looking at it - the geometry is also incorrect. It looks more like a smooth boulder than a rounded cube.

**Comment by Ice101781** [comment]
Okay, the geometry issue was fixed by specifying the number of segments to include on the BoxGeometry - these seem to be important parameters for the modifier.

**Comment by WestLangley** [comment]
> The rest is black. What could be causing that?

As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
