### ISSUE TITLE
Blender Exporting Animations - Normalizing Quaternions

### ISSUE THREAD

**Issue by willy-vvu** [mrdoob/three.js#6082]
This is more of a quick fix, though I'm not sure where to delve into the exporter source just yet.

In blender, it's easy to get quaternions that are not normalized, especially when using *Push Pose* (`Ctrl+E`). For example:

![image](https://cloud.githubusercontent.com/assets/3529065/6206790/f88f748a-b55f-11e4-9344-d0c0ad38744b.png)

However, these get exported without being normalized.
```json
{
  "keys": [{
    "time": 0.283333,
    "pos": [-0.104213,-0.116123,-0.0],
    "rot": [-0.500419,0.0,-0.0,1.178179]
  }]
}
```

When imported, it causes `THREE.SkinnedMesh` to scale strangely, as non-normalized quaternions usually do.

This can be fixed by normalizing them in the exporter.

**Comment by mrdoob** [comment]
Kind of off-topic but... I would suggest to save the matrix instead of `pos`, `rot`, ...

**Comment by titansoftime** [comment]
> Kind of off-topic but... I would suggest to save the matrix instead of pos, rot, ...

I believe this was done this way for the quaternions smooth rotation interpolation, also file size.

**Comment by repsac** [comment]
So I tried inserting a single line right after https://github.com/mrdoob/three.js/blob/dev/utils/exporters/blender/addons/io_three/exporter/api/animation.py#L276

with `rot.normalize()`

help according to Blender:
```
>>> help(rot.normalize)
Help on built-in function normalize:

normalize(...) method of builtins.Quaternion instance
    .. function:: normalize()
    
    Normalize the quaternion.
```

I don't have a scene that has the exact problem that you have with quaternions. In fact the animation scenes I do have that I tested exploded when I added this. You will want to test this on your end and if it solves your problem then it may have to be an option (off by default) that is available for users trouble shooting their exports. If that doesn't work then at the moment I am a bit clueless as I would expect a `normalize` method to have resolved this.

**Comment by repsac** [comment]
Note: It exploded on `Rest` animations. Hard to tell how it works with `Pose` with the test asset I have because that asset requires `Rest` exports.... :confused:

**Comment by willy-vvu** [comment]
I tried it, and it exploded for me too - the results were quite hilarious!

**Comment by repsac** [comment]
@willy-vvu Try out my dev branch
https://github.com/repsac/three.js/tree/io_three

I wrote my own normalization function using the same logic that `three` uses. It is only applied to `Rest` animations but I am guess we want this on both animation types.

**Comment by repsac** [comment]
https://www.youtube.com/watch?v=NP0mQeLWCCo

If this is a fix we would like to get this one merged before r71.

**Comment by willy-vvu** [comment]
Sorry, I've been relatively busy in the past week. I'll get to it by Friday.

**Comment by repsac** [comment]
No worries, just trying to tighten up as much as we can before the next release.

**Comment by willy-vvu** [comment]
Hmm... Something's up. I installed the forked exporter and exported, and the quaternions still aren't normalized.
```json
"keys": [{
                "time": 0.0,
                "rot": [0.0,0.0,-0.0,1.0],
                "scl": [1,1,1],
                "pos": [0.0,0.373804,-0.0]
            },{
                "time": 0.133333,
                "rot": [-0.211373,0.0,-0.0,0.977406],
                "pos": [0.0,0.373804,-0.0]
            },{
                "time": 0.283333,
                "rot": [-0.211373,0.0,-0.0,1.268785],
                "pos": [0.0,0.373804,-0.0]
            },{
                "time": 0.483333,
                "rot": [0.0,0.0,-0.0,1.0],
                "scl": [1,1,1],
                "pos": [0.0,0.373804,-0.0]
            }]
```

**Comment by repsac** [comment]
Ugh. Well thanks for taking a moment to look at this. Going to have to try and make a test case scene I guess. 

Oh I just thought of something. Which type of animation export did you do? This was only applied to `Rest` exports and not `Pose`. Anyways will try and get a test case and get this merged by the weekend.

**Comment by repsac** [comment]
OK I messed up. I had added the normalization to `Pose` exports and not `Rest`. It is now added `Rest` as well. Through together a test case scene which seemed to work.

**Comment by willy-vvu** [comment]
Alright - thanks for all the improvement! I'll be sure to check it out, and
let you know how it goes.

**Comment by WestLangley** [comment]
@repsac Here a reminder of a few blender/three.js quaternion-related issues that haunted us several years ago -- just in case you were not aware:  #2250 and #2803.

**Comment by repsac** [comment]
Thanks. Looks like some real headaches. I ran into tons of rotation issues when trying to preserve parent/child hierarchies. I am currently normalizing ALL quaternions. Wondering if I should first test a quaternion before normalizing.

**Comment by WestLangley** [comment]
> Wondering if I should first test a quaternion before normalizing.

Sorry, test it for what?

Certainly, quaternions imported into three.js must have unit length.

**Comment by repsac** [comment]
> Sorry, test it for what?

Test that each quaternion value is unit length before normalizing. Sorry I was thinking out loud and replied while still at work so my head wasn't with it. It should be fine to just normalize all of them, but rotational value conversions to `three` from Blender has been an ongoing headache so I felt the need to just openly state what was on my mind (even if it was a bit dumb sounding). Thanks again for those links. Lots of insight there.

**Comment by willy-vvu** [comment]
AMAZING! The new exporter works like a charm. Thanks so much for putting in the time and effort.
Just in case you were wondering what I was working on that had quaternion issues, check out http://idea-lab.github.io/SmashLab

**Comment by titansoftime** [comment]
Just an observation: Is position also supposed to be normalized?

Here is an example animation key

```
            {
                "rot": [0.0,0.0,-0.0,1.0],
                "scl": [1,1,1],
                "time": 0.0,
                "pos": [0.759082,1.55705,-1e-06]
            },{
                "rot": [-0.206951,0.0,-0.0,0.978351],
                "time": 0.791667,
                "pos": [0.759079,1.464897,-0.642367]
            },{
                "rot": [-0.583715,-0.0,-0.0,0.811959],
                "time": 1.333333,
                "pos": [0.759082,0.496004,-1.896819]
            },{
                "rot": [-0.583715,-0.0,-0.0,0.811959],
                "time": 1.708333,
                "pos": [0.759082,0.496004,-2.146836]
            },{
                "rot": [-0.583715,-0.0,-0.0,0.811959],
                "scl": [1,1,1],
                "time": 2.041667,
                "pos": [0.759082,0.496004,-2.146836]
            }
```

Also even with precision enabled I see values in scientific notation. Is this intended/ok ?

**Comment by willy-vvu** [comment]
I don't believe positions need normalization. The only reason why rotations need normalization is that they cause strange scaling issues if they aren't - It's just the way the 4d quaternion math works.

**Comment by titansoftime** [comment]
>I don't believe positions need normalization. The only reason why rotations need normalization is that they cause strange scaling issues if they aren't - It's just the way the 4d quaternion math works.

Ah, cool.

**Comment by repsac** [comment]
> Also even with precision enabled I see values in scientific notation. Is this intended/ok ?

JSON serialization does that. 
```
>>> json.dumps(-0.000001)
'-1e-06'
````

I really wouldn't worry about it

**Comment by repsac** [comment]
Resolved https://github.com/mrdoob/three.js/pull/6158
