### ISSUE TITLE
initMaterial depreciated?

### ISSUE THREAD

**Issue by lmcd** [mrdoob/three.js#6089]
We're building a three.js app that has lots of offscreen meshes with `ShaderMaterial`s. When these meshes are eventually revealed onscreen, there is a huge delay in having their shaders compiled for the first time.

A fix would be to run `initMaterial` on each of the `ShaderMaterial`s during a pass when the app first loads, but this method is depreciated. Is there no other way to have shaders preloaded to avoid the enormous lag in loading them at runtime?

**Comment by mrdoob** [comment]
That approach didn't feel right. It may come back in a different way. A workaround by now is to render those objects at load time with opacity 0 maybe?

**Comment by wothke** [comment]
Any updates on this? 

I also have a list (between 10-20) of ShaderMaterials that I am using - one after the other - on the same Mesh during the course of an animation. I want to make sure that all the respective shader programs have been compiled and cached before I start the animation (I want to avoid that any on-demand shader program compilation might add a lag in the midst of my animation).

Do I still have to create phantom meshes for all those materials just to get those shader programs compiled in advance or is there a better way by now?

**Comment by looeee** [comment]
#10960 looks to be related.

**Comment by wothke** [comment]
related yes, but the suggested solution is useless in my scenario, unless I create a separate Mesh for each of my ShaderMaterials and then make them all visible at the same time.. before I do that, I'll just patch my local three.js to directly expose initMaterial()...
