### ISSUE TITLE
OBJMTLLoader should call computeVertexNormals

### ISSUE THREAD

**Issue by SebastianBaltesObjectCode** [mrdoob/three.js#6094]
**Three.js Version:** 0.0.70
**Plattform:** all

**Description:** Objects imported with OBJMTLLoader are not rendered with smooth shading, even if the material settings should (THREE.MeshPhongMaterial is used in MTLLoader and the 'shading' - parameter is not set, so the default THREE.SmoothShading should be used).

**Bugfix:** In OBJMTLLoader.js, add before line 96 

				geometry.mergeVertices();
				geometry.computeFaceNormals();

                // add following line to fix smooth shading
				geometry.computeVertexNormals();	
			
				geometry.computeBoundingSphere();

**Comment by WestLangley** [comment]
> Objects imported with OBJMTLLoader are not rendered with smooth shading

That does not appear to be a problem here: http://threejs.org/examples/webgl_loader_obj_mtl.html.

If you still believe there is a three.js bug, can you provide a test case so we can reproduce your results? Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by SebastianBaltesObjectCode** [comment]
**Lifedemo:** [http://preview.objectcode.de/carbug](http://preview.objectcode.de/carbug) 
**with fix:** [http://preview.objectcode.de/car](http://preview.objectcode.de/car)

**Comment by WestLangley** [comment]
The problem is with your model. Your model does not have vertex normals.

Also, your model has quad faces. three.js does not support quads. The loader is triangulating the quads for you.

**Comment by mrdoob** [comment]
What @WestLangley said. If your model doesn't have vertex normals the loader won't compute them for you as this can be wasteful if someone doesn't need them.

**Comment by SebastianBaltesObjectCode** [comment]
Thanks for spotting the root cause. Maybe an option in the OBJ-Loader for beeing more permissive in those cases would be a nice idea.

**Comment by WestLangley** [comment]
It is the responsibility of the loader to load the model, not to modify it. You can modify the model in the loader's `onLoad` callback if you want.
