### ISSUE TITLE
Sprites don't respond to scene.overrideMaterial

### ISSUE THREAD

**Issue by scisci** [mrdoob/three.js#6098]
I'm trying to render a depth material, but sprites just render as normal, I think due to the SpritePlugin.

**Comment by looeee** [comment]
Came across this issue today - however  sprites don't render at all with most materials, so it applying the override material to sprites is probably not desired in most cases. 

I'll add a note to the docs that sprites are not affected by scene.override material.

**Comment by looeee** [comment]
@scisci due to the way sprites are implemented, it would not be at all easy to make this work - they must use a SpriteMaterial, so unless the override material is a SpriteMaterial then they will just become invisible when it is applied to them, Do you think that this being documented is sufficient?

**Comment by scisci** [comment]
Hi, I @looeee. I forget exactly why I wanted a depth material on a sprite as it was a while ago. I think I was doing a depth of field effect and the sprites were messing up because they weren't registering the right depth. But I ended up finding a workaround (don't remember what it was). As long as its documented.
