### ISSUE TITLE
How to create 3D objects like this

### ISSUE THREAD

**Issue by somerussian** [mrdoob/three.js#6107]
I need a script to create objects like this (see pictures), using coordinates of objects.
Sometimes I need to create custom objects, sometimes it's required to use transparency (like it is on pictures).
This example is very primitive:
****
polyhedronShape = new THREE.Shape(polyhedronPts);
geometry = new THREE.ExtrudeGeometry(polyhedronShape, extrudeSettings);
mesh = new THREE.Mesh(geometry, new THREE.MeshLambertMaterial({color:0xff0000}));
****
I require some more - better quality (like on pictures).
Who can help me? Teach me or do some work for me.

![01](https://cloud.githubusercontent.com/assets/1025024/6283614/bd22a316-b908-11e4-9b6c-6a8231533959.png)
![02](https://cloud.githubusercontent.com/assets/1025024/6283617/bd31d0a2-b908-11e4-84d6-6d3a3ba77d9d.png)
![03](https://cloud.githubusercontent.com/assets/1025024/6283616/bd2c03de-b908-11e4-8cf7-2c89e7138d7a.png)
![04](https://cloud.githubusercontent.com/assets/1025024/6283613/bd1d7e04-b908-11e4-8873-fb20a716c038.png)
![05](https://cloud.githubusercontent.com/assets/1025024/6283615/bd298758-b908-11e4-8332-19c7951a7d63.png)
![06](https://cloud.githubusercontent.com/assets/1025024/6283612/bd0adc90-b908-11e4-9890-2e3b9cf526d4.png)

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
