### ISSUE TITLE
why does uv2 have to be on every shader regardless of USE_LIGHTMAP?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6109]
I mean this:
https://github.com/mrdoob/three.js/blob/dev/src/materials/ShaderMaterial.js#L67
https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLProgram.js#L221

vs
https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/lightmap_vertex.glsl

**Comment by mrdoob** [comment]
Nice catch. Do you want to do a PR for it?

**Comment by makc** [comment]
what would I do about defaultAttributeValues? if you remove it from there, lightmaps will fail on all the geometry with no 2nd uvs. not sure if having a single pixel of lightmap used is any better.

**Comment by makc** [comment]
also it is all over WebGLRenderer... sigh

**Comment by mrdoob** [comment]
Yep... `WebGLRenderer` still needs a ton of love...

**Comment by makc** [comment]
чтобы два раза не вставать, since this is already labeled 'suggestion':

wwhy on earth custom vertex attributes are on materials, and not on geometry? now that you have BufferGeometry, and upload all of their data in [updateObject](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L3918). but they are inaccessible from shaders because... hum?

**Comment by mrdoob** [comment]
Yep! That's something else I want to fix.

**Comment by makc** [comment]
however I don't have to duplicate data on material.attributes! is it by design, or by lucky coincidence? I will never know, right?

**Comment by bhouston** [comment]
I fixed this issue in this commit on the ambientOcclusion PR, because I refactored how UV and UV2 are handled in the glsl fragments: 

https://github.com/bhouston/three.js/commit/dd679cbcfdc85092c29f249ca1cd86c423c1b887

**Comment by dubejf** [comment]
This appears to have been pulled in the `dev` branch with #6263
