### ISSUE TITLE
model rotation of Editor 

### ISSUE THREAD

**Issue by yutopp** [mrdoob/three.js#6111]
Hello, I'm using Editor of three.js.
When I change the value of Rotation in the right pane, the rotation of the model is different from what I expected. It seems correct when changing only Z axis. (I took a movie → [movie - YouTube](http://youtu.be/ljVg5Aq2pQE) )
It happens even when I manipulate the model with 'local' rotate Transform controls. Then values of Rotation shows unexpected results, for example, values of X and Z axis are changed when I manipulates only Y axis.
Is it a spec? I think it is difficult to convert between Quaternion and Euler. So, I will understand this issue if it is spec.

Thanks!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

You need to understand Euler angles and how they are implemented in three.js. See, for example, [this stackoverflow post](http://stackoverflow.com/questions/17517937/three-js-camera-tilt-up-or-down-and-keep-horizon-level/17518092#17518092).

@mrdoob Maybe we should add `rotation.order` to the editor. For example, setting `order = "YXZ"` is very intuitive. Too bad we didn't default to "YXZ" in the first place...

**Comment by yutopp** [comment]
@WestLangley Thank you very much for your quick response.
I'm sorry to not follow the guidelines... I will try to learn Euler angles and use stackoverflow.
