### ISSUE TITLE
Parts of BufferGeometry with different textures

### ISSUE THREAD

**Issue by Zerod159** [mrdoob/three.js#6112]
Is there an easy way to render index/face 0 to 288 with Texture A and index/face 289 to 606 with Texture B of a Mesh with BufferGeometry?

**Comment by makc** [comment]
yes, do two geometries with same vertex buffers and separate index buffers

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

http://stackoverflow.com/questions/28631414/threejs-buffergeometry-render-some-faces-with-other-texture

**Comment by Zerod159** [comment]
@WestLangley Ok, i understand that.
@makc how do is make two geometries with same vertex buffers? do you have an example? I am very desperate :)

**Comment by WestLangley** [comment]
Please use stackoverflow.

**Comment by makc** [comment]
@Zerod159 I have answered to stackoverflow question above (I assume it's yours).
