### ISSUE TITLE
Output of vertex shader 'webgl_b441c1760964dbca' not read by fragment shader

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6113]
I assume the 'webgl_b441c1760964dbca' part refers to shader output, is it possible to get readable name there? as in 'varying this_name'

This is traced by following code:
```javascript
		if ( _gl.getProgramInfoLog( program ) !== '' ) {

			console.warn( 'THREE.WebGLProgram: gl.getProgramInfoLog()', _gl.getProgramInfoLog( program ) );
			// console.warn( _gl.getExtension( 'WEBGL_debug_shaders' ).getTranslatedShaderSource( glVertexShader ) );
			// console.warn( _gl.getExtension( 'WEBGL_debug_shaders' ).getTranslatedShaderSource( glFragmentShader ) );

		}
```
Where are these IDs coming from? Is it something three.js generates?

**Comment by gero3** [comment]
Nope, these are created by the browser. The best way for you to find this is to get  http://benvanik.github.io/WebGL-Inspector/ and check it out with this.
