### ISSUE TITLE
New ObjectLoader and normal map issue

### ISSUE THREAD

**Issue by mese79** [mrdoob/three.js#6114]
Hi
I have an exported json file from a blender scene with simple plane which has a normal map.(i'v got samples from [**repsac** repository](https://github.com/repsac/three.js/tree/io_three/utils/exporters/blender/tests))
With new ObjectLoader normal map has loaded but it has no effect on object. i mean like the plane object has no normal map.
But if i export only the plane object not the whole scene with blender exporter and by using JSONLoader everything seems good.

Here is JSONLoader view:
![objectexport](https://cloud.githubusercontent.com/assets/1878378/6316034/e5844698-ba2a-11e4-8ede-cebbbdfdb58e.png)

And this is ObjectLoader view:
![sceneexport](https://cloud.githubusercontent.com/assets/1878378/6316038/054805a0-ba2b-11e4-8284-3ecebf3cc569.png)

So what's the problem here?
Thanks.

**Comment by mrdoob** [comment]
Did you try using the latest in the `dev` branch?

**Comment by mese79** [comment]
Nope, i was trying with r70.
Let me check it with **dev** branch.

**Comment by mese79** [comment]
I guess this is a bug with loading normal map. because i've tested new ObjectLoader with diffuse map and light map which they are ok.
In ObjectLoader i've noticed that the **WebGLRenderer.uploadTexture** doesn't get called for normal map, but for diffuse/light map it gets called. also the JSONLoader doesn't call WebGLRenderer.uploadTexture until first user interaction or window resize.

**Comment by fraguada** [comment]
In the dev branch, we never added support for normal materials in the [ObjectLoader.js](https://github.com/mrdoob/three.js/blob/dev/src/loaders/ObjectLoader.js#L226), though I do not think it would be too difficult to do.

**Comment by mese79** [comment]
But I think it is there @line 259:
```
if ( data.normalMap !== undefined ) {
    material.normalMap = getTexture( data.normalMap );
}
```

**Comment by fraguada** [comment]
@mese79 apologies, I missed this.  You are correct, this is what I was suggesting.  As you mention, the build was updated to v71dev, and if we look in the Three.js file, it is indeed included.

**Comment by mese79** [comment]
@fraguada Thanks for your example [here](https://github.com/mrdoob/three.js/commit/e5ae7d153be11a97618259bbb787290bea94e590).
I could add normal map to your example successfully :) . it seems that the repsac example setup to work with JSONLoader.

**Comment by WestLangley** [comment]
> Unfortunately, Same result with THREE.WebGLRenderer 71dev.
> Here is my test files: geometry_normal_map.tar.gz

You need to add a light to your scene.

**Comment by mese79** [comment]
> You need to add a light to your scene.
D'oh!! i was relied on ambient light only.

**Comment by WestLangley** [comment]
This is why we prefer you to use stackoverflow for help. Try to avoid blaming the library when your code is not working. : - )
