### ISSUE TITLE
sampler arrays indexed with non-constant expressions...

### ISSUE THREAD

**Issue by MichaelThompson32214** [mrdoob/three.js#6115]
What causes this warning? And what is the general recommened solution?

THREE.WebGLShader: gl.getShaderInfoLog()
0:38(139): warning: sampler arrays indexed with non-constant expressions will be forbidden in GLSL 1.30 and later

**Comment by mrdoob** [comment]
I've never seen that. What are you getting that with?

**Comment by beobes** [comment]
Hi,

I'm a very beginner with three.js and I found this post looking for information.

I've (almost) the same log : THREE.WebGLShader: gl.getShaderInfoLog() 0:106(145) ...

When I comment the above line, I don't get it anymore...
    directionalLight.castShadow = true;

I've a basic scene with : 
- one HemiLight 
- one DirectionalLight
- a sky (like in the ligtmap material example of three.js)
- an objetc loaded with ObjLoader.

I use traverse on the loaded object to set castShadow to true to each "child".

Beobes

**Comment by mrdoob** [comment]
Can you post the test online so we can try it out?

**Comment by beobes** [comment]
Here is a repository with a simpler scene which produce the same console log : https://github.com/beobes/threejs-test.

```
THREE.WebGLShader: gl.getShaderInfoLog()

0:107(145): warning: sampler arrays indexed with non-constant expressions will be forbidden in GLSL 1.30 and later
0:108(145): warning: sampler arrays indexed with non-constant expressions will be forbidden in GLSL 1.30 and later
0:109(145): warning: sampler arrays indexed with non-constant expressions will be forbidden in GLSL 1.30 and later
0:110(145): warning: sampler arrays indexed with non-constant expressions will be forbidden in GLSL 1.30 and later
0:111(145): warning: sampler arrays indexed with non-constant expressions will be forbidden in GLSL 1.30 and later
0:112(145): warning: sampler arrays indexed with non-constant expressions will be forbidden in GLSL 1.30 and later
0:113(145): warning: sampler arrays indexed with non-constant expressions will be forbidden in GLSL 1.30 and later
0:114(145): warning: sampler arrays indexed with non-constant expressions will be forbidden in GLSL 1.30 and later
0:115(145): warning: sampler arrays indexed with non-constant expressions will be forbidden in GLSL 1.30 and later

```

**Comment by mrdoob** [comment]
![screen shot 2015-03-12 at 9 47 41 am](https://cloud.githubusercontent.com/assets/97088/6615565/ea973eb2-c89c-11e4-8164-ef8a9e73fa7b.png)

I'm not getting those messages myself... What's your config? (OS, GPU, etc)

**Comment by gouvion** [comment]
That's right ! 
On a Windows machine I don't get it.

I get the message on Linux (Ubuntu 14.04) and I've a Radeon HD 6770 (driver AMD/ATI Juniper XT).

**Comment by mrdoob** [comment]
Hmmm, not getting that in Firefox 36 for OSX either...

**Comment by gouvion** [comment]
Actually it doesn't make my scene buggy... and I've not the knwoledge (nor the time I should say) to go further on this "problem".

As I found this post looking for where this log could come from, I just wanted to contribute as Michael did not answer you.

I just have tested it a little but three.js is a great job !!

**Comment by jaamo** [comment]
I'm having the same issue with my Lenovo n20p Chromebook. Any ideas how to fix it?

**Comment by drcmda** [comment]
The same happens on the Chromebook Pixel. No example featuring shadows will work. He'll not even compile the shader. Some applications fail completely.

I found this on stackoverflow: http://stackoverflow.com/questions/15214604/constant-for-that-access-sampler

    The fact that the compiler could unroll the loop and this resolve i at compile time 
    does not change the fact that i is not an integral constant expression.\
    And therefore, it is not allowed to be used as an index in GLSL 1.20.
    So no, there's nothing you can do outside of unrolling the loop manually.

**Comment by tommytee** [comment]
i get it on Firefox 39 (latest) on Arch Linux, Gnome.  I do not get it with Firefox on OSX or Windows 10, nor on any other browser on Linux.

**Comment by jhylands** [comment]
Would it be possible to manually unpack the loops for three.js?

**Comment by mrdoob** [comment]
Yeah, seems like we'll have to do it eventually.

**Comment by Mugen87** [comment]
I have done the following test with this three.js example: [webgl_materials_bumpmap](http://threejs.org/examples/#webgl_materials_bumpmap)

Ubuntu 15.10, Intel Ivybridge Mobile, Chromium 48.0.2564.82: The shader does not compile, i'm just getting a black screen and the error message "_sampler arrays indexed with non-constant expressions are forbidden in GLSL 1.30 and later_"

Ubuntu 15.10, Intel Ivybridge Mobile, Firefox 44: In this case, i'm still getting the mentioned warning, but at least the shader compiles and the example works.

It's interesting to see that Chromium and Firefox handle the situation differently.

**Comment by mrdoob** [comment]
I think this has been addressed in Chrome Dev.

**Comment by Mugen87** [comment]
You're right, here's the issue: [WebGL shader fails to initialize](https://code.google.com/p/chromium/issues/detail?id=550487). 

The bug will be fixed with Chrome 49. I've tested some three.js examples with the dev-build of Chrome. Everything looks good, all shaders compile correctly now.

**Comment by mrdoob** [comment]
Starting today, three should no longer rely on these, so `dev` should work properly on Chrome 48 too?

**Comment by Mugen87** [comment]
Cool! `dev` actually works with Chrome 48 :+1: 

Ubuntu 15.10, Intel Ivybridge Mobile, Chromium 48.0.2564.82
