### ISSUE TITLE
BufferGeometry face normals

### ISSUE THREAD

**Issue by pavelvasev** [mrdoob/three.js#6117]
Dear community!

I have some BufferGeometry which holds indexed triangles.
I want it to have a face normals. But it seems I can add only per-vertex normals. 

When I compute normals in per-triangle basis, and then add normals of length of (indices.length), via
`geometry.addAttribute( 'normal', new THREE.BufferAttribute( new Float32Array(normals), 3 ) );`

I get `glDrawElements: attempt to access out of range vertices in attribute 1`

The geometry I work with contains tetrahedrons, so I need those face normals.
And I do not want to split it to non-indexed geometry, because my original tetrohedron mesh already tooo big.

So my question is. Where can I digg into ThreeJS source and implement face normals to BufferGeometry?

**Comment by mrdoob** [comment]
Unfortunately this is a limitation of WebGL itself.

**Comment by pavelvasev** [comment]
But Geometry class has face normals?...
22.02.2015 14:17 пользователь "Mr.doob" <notifications@github.com> написал:

**Comment by mrdoob** [comment]
Yes. And at render time it creates non-indexed buffers.

**Comment by makc** [comment]
Well, you still have [this](http://stackoverflow.com/questions/20272272/standard-derivatives-from-fragment-shader-dfdx-dfdy-dont-run-correctly-in-a):
```glsl
    vec3 fdx = vec3(dFdx(vPos.x),dFdx(vPos.y),dFdx(vPos.z));
    vec3 fdy = vec3(dFdy(vPos.x),dFdy(vPos.y),dFdy(vPos.z));
    vec3 N = normalize(cross(fdx,fdy));
```

**Comment by mrdoob** [comment]
Oh! Interesting...
I bet people will still want custom face normals though, but this could be what `THREE.FlatShaded` do...

**Comment by pavelvasev** [comment]
I hoped that `THREE.FlatShading` is brilliand idea and will work. Hovewer shading property does not work at all in r70 and in dev... ;-(
Seems "shading" property of materials is broken somehow.

Maybe I misunderstand and there is a difference betweeen `THREE.FlatShaded` and `THREE.FlatShading` ?

Please look at example, scroll down in navigation to "Spheres->Trimesh", I set shading to "flat-shading" and there is still smooth shading visually:

http://threejs.org/editor/#app=http://svn.lact.ru:4567/files/visual/2015-02-24/2015-02-24-at-21-21-05.jpg.json

**Comment by pavelvasev** [comment]
Another example, with part of tetrahedron mesh: http://threejs.org/editor/#app=http://svn.lact.ru:4567/files/visual/2015-02-24/2015-02-24-at-22-03-25.jpg.json

**Comment by makc** [comment]
@pavelvasev what @mrdoob is saying is that he could make THREE.FlatShaded work with BufferGeometry in the future, but right now you need to write your own shader, via ShaderMaterial.

**Comment by pavelvasev** [comment]
Ehh!.. Makc, thanks for clarification!

**Comment by makc** [comment]
Should be easy to patch, really. I have no idea how this shader building business works, so can't do meaningful PR on this, but look:

![before](https://cloud.githubusercontent.com/assets/242577/6433133/c842a092-c066-11e4-9bed-f60894153ad3.png)
(before)

![after](https://cloud.githubusercontent.com/assets/242577/6433137/db4ab8d2-c066-11e4-8461-9bb9fc11c67c.png)
(after - 4 lines added)

What I can do is maybe example PR. But we sure would like to see this in core lib.

**Comment by pavelvasev** [comment]
That's look like what I need ;-) Is that behavior can be enabled for BufferGeometry by THREE.FlatShaded, theoretically?

**Comment by makc** [comment]
why not, see this extension [support stats](http://webglstats.com/):
![standard derivatives support](https://cloud.githubusercontent.com/assets/242577/6446139/289a91d2-c109-11e4-8426-299c03f62244.png)

in fact, I see it already used in three.js [here](https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderChunk/normalmap_pars_fragment.glsl#L11), for example.

**Comment by mrdoob** [comment]
Working on it ^^

**Comment by mrdoob** [comment]
Implemented!
`MeshLambertMaterial` is a problem though... (because the shading is computed in the vertex shader)

**Comment by mrdoob** [comment]
Also, many thanks @makc!

**Comment by WestLangley** [comment]
@mrdoob Unfortunately, with this screen-space derivatives approach, lighting is not correct with double-sided materials. You can test with two lights of different colors on opposite sides to see that the normals are not correct. I do not have a solution as of yet.

	var geometry = new THREE.PlaneBufferGeometry( 10, 10, 4, 4 );

	var material = new THREE.MeshPhongMaterial( {
		shading: THREE.FlatShading,
		side: THREE.DoubleSide
	} );

The shader code is very fragile, unfortunately. You have to be careful with your `ifdefs`.

There may be further issues if skinning or morphs are active.

**Comment by makc** [comment]
I bet you can use gl_FrontFacing to fix double-sided issues. Go on, I trust in you :stuck_out_tongue:

**Comment by makc** [comment]
I have this shader here that says
```glsl
			if(!gl_FrontFacing) {
				normalVec = -normalVec;
			}
```
if that helps.

**Comment by makc** [comment]
ps @WestLangley did you notice how your github avatar looks like the war plane shooting missiles?

**Comment by WestLangley** [comment]
hehe. I do now.

**Comment by pavelvasev** [comment]
Hi guys! Many thanks to you for your efforts. I checked and now all works good!

But as WestLangley noted, some lights stop working on back-sides. However, it seems not a problem for me now.. ;-)

**Comment by mrdoob** [comment]
Hmmm, there is some code to address that but doesn't seem to be working...
https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderChunk/lights_phong_fragment.glsl#L4-L8

**Comment by makc** [comment]
maybe #ifdef DOUBLE_SIDED && !FLAT_SHADED then?

**Comment by arose** [comment]
Based experimentation...

```glsl
#ifndef FLAT_SHADED
    #ifdef DOUBLE_SIDED
        ...
    #endif
    #ifdef FLIP_SIDED
        ...
    #endif
#endif
```

**Comment by mrdoob** [comment]
@arose thanks!
