### ISSUE TITLE
AnimationBlending example doesn't work with new blender meshes

### ISSUE THREAD

**Issue by Sempran** [mrdoob/three.js#6120]
The AnimationBlending example doesn't work with meshes exported with the new Blender importer.

I get this error:

Uncaught TypeError: Cannot read property 'multiplyMatrices' of undefined

It works, however, with models exporter with a very old version of the importer and blender (2.65).

**Comment by repsac** [comment]
Are you using the exporter from `dev`? If not you should be as there have been lots of big fixes since the r70 release.
