### ISSUE TITLE
incorrect texture gets assigned to unrelated shader material

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6121]
not sure if I can offer easily reproducible exmple, but the crux is this: if I have a shader 1 with undefined value for texture uniform, and then load another shader 2 with all textures set, one of these is suddenly used in shader 1 then. I had to create dummy datatexture where I had no texture set because of this, because debugging wrong texture and debugging missing texture are different things.

**Comment by makc** [comment]
Ookay, I've double-checked this, and here is reproduction [fiddle](http://jsfiddle.net/XGWGn/71/)

**Comment by brunosimon** [comment]
I have the same problem. I'm not even using custom shaders. 
The texture on a MeshBasicMaterial get replaced by other textures I used on the scene.
Have you found a solution ?

**Comment by makc** [comment]
Sure,
> I had to create dummy datatexture where I had no texture set

**Comment by brunosimon** [comment]
Do you mean that you put a map with empty texture on every material not having one ? :/

**Comment by makc** [comment]
Yes, basically,
```javascript
// before
textures[ ... ]
// after
textures[ ... ] || THREE.ImageUtils.generateDataTexture(4, 4, new THREE.Color(0xafafaf))
```

**Comment by Mugen87** [comment]
@makc Can you please have a look if the bug is still present in `R91`: https://jsfiddle.net/XGWGn/133/

I think i could not reproduce.

**Comment by makc** [comment]
@Mugen87 this has been fixed between [r77](http://jsfiddle.net/XGWGn/136/) and [r78](http://jsfiddle.net/XGWGn/137/).

**Comment by Mugen87** [comment]
Great 😊 🎉
