### ISSUE TITLE
Equilateral Panorama  dragging is buggy when distortion on [camera.target ).negate()]

### ISSUE THREAD

**Issue by ulumi** [mrdoob/three.js#6122]
hello, looking at solutions for custom embedding of the panoramas, i came across a few leads id like to share, i hope anyone who feels like sharing and or doing tests can join in.

I've had ok results as for image quality with the http://threejs.org/ library to render the panorama as a circular 3d object. i've started from examples http://blog.thematicmapping.org/2014/01/photo-spheres-with-threejs.html, 
and https://github.com/mrdoob/three.js/blob/master/examples/webgl_panorama_equirectangular.html
and got an acceptable result, but it seems the dragging of the panorama is buggy when the distortion [camera.position.copy( camera.target ).negate();] is active in the javascript.

you can see result here: http://www.huguesbp.com/partage/360/three-js/github_mod1.html

if anyone feels like digging into this it would seem like a fixable issue, but I cannot get it to work as expected. im on mac OS X yosemite using safari and chrome.

thanks in advance for sharing your experiences!

**Comment by makc** [comment]
just passing by, 1st you might want to read [this](https://guides.github.com/features/mastering-markdown/) and 2nd lgtm, except the mouse sensitivity is huge

**Comment by mrdoob** [comment]
I don't see anything buggy myself...?

**Comment by WestLangley** [comment]
This line

    camera.position.copy( target ).negate();

is in three of the examples. It is commented out in two of them.

That line makes no sense to me. What is the purpose?

**Comment by makc** [comment]
maybe someone wanted to increase fov?

**Comment by mrdoob** [comment]
> That line makes no sense to me. What is the purpose?

I think I wrote that originaly. It creates a fish eye lens effect.
