### ISSUE TITLE
toFixed in geometry exporter, please

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6132]
I mean, just look at this:

![screen shot 2015-02-24 at 21 39 20](https://cloud.githubusercontent.com/assets/242577/6358699/d52a42bc-bc6d-11e4-8c93-f20e226ed083.png)

Do people really need all those digits.

**Comment by WestLangley** [comment]
A post written as a constructive suggestion would be more helpful.

What changes do you recommend in the code?

**Comment by makc** [comment]
I am suggesting that if, instead of 24.888220000000583 we could output 24.88822, resulting json would be twice less than it's now.

In the code, you have:
```javascript
		var output = geometry.toJSON();
		output = JSON.stringify( output, null, '\t' );
```
that null could be put into good use, see [this fiddle](http://jsfiddle.net/gazas8dp/), for example.

**Comment by makc** [comment]
Oh, and by the way... The editor says it uses r70 in console. However, in the screenshot you see data.vertices? If I do geometry.toJSON() in my project, it has data.attributes instead (which matches current source). Why neither threejs revision nor metadata.version was bumped despite breaking changes there?

**Comment by WestLangley** [comment]
Here is @makc's idea -- with the help of [mrdoobapproves](http://zz85.github.io/mrdoobapproves/) : - )

```javascript
var a = {

	b: [ 22.34500006, 7.8917777654e21, -1.999001122e-15 ]

};

var output = JSON.stringify( a, replacer );

alert( output );

function replacer( key, value ) {

	if ( value instanceof Array ) {

		var i, n = value.length, result = new Array( n );

		for ( i = 0; i < n; i ++ ) {

			result[ i ] = parseFloat( value[ i ].toPrecision( 5 ) )

		}

		return result;

	}

	return value;

}
```

fiddle: http://jsfiddle.net/gazas8dp/1/

**Comment by makc** [comment]
Either this, or your own flavour of stringify() based on something like [this](https://github.com/bestiejs/json3).

**Comment by makc** [comment]
Just noticed your regexp idea... that could actually work [too](http://jsfiddle.net/gazas8dp/3/).

**Comment by mrdoob** [comment]
I like the regexp idea, but I suspect it will break other parts of the output. `toPrecision()` doesn't really do what we want I think...

**Comment by makc** [comment]
I am trying regexp now on 28MB file with almost 1.5M matches, if the text editor unfreezes, I will see if it broke anything.

**Comment by makc** [comment]
Damn text editors. It would be faster to write node program.

**Comment by makc** [comment]
Any way, I have managed to replace this fast with
```
sed -E 's/(\.[0-9]{3})[0-9]+/\1/g;' a.json > b.json
```
on mac. Could not check with geometries, but scenes seem to be imported back in the editor just fine.

**Comment by makc** [comment]
(closing in favor of #6206)
