### ISSUE TITLE
Clickable hotspots in panorama based on CSS3D renderer

### ISSUE THREAD

**Issue by adeolafabola** [mrdoob/three.js#6134]
I created a cubemap panorama based on the examples provided and I am trying to add hotspots that can be clicked (and interacted with). I added a simple CSS3DObject (made from an icon) to the scene and I want to be able to click on it. I have looked up several examples using Raycaster, Projector etc but nothing seems to work for me. 
Please help!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

See http://threejs.org/examples/css3d_youtube.html#cats.
