### ISSUE TITLE
What about applyMatrix(matrix) method in Object3D?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6137]
Right now I am doing
```javascript
matrix.decompose(object.position, object.quaternion, object.scale);
```
Which is not too verbose, but it took me some time to figure out that I could do that, as most google results point to discussions on how I need to use autoUpdate=false. Not obvious or newbie-friendly at all.

**Comment by WestLangley** [comment]
What you are requesting or proposing?

**Comment by makc** [comment]
I propose to add this kind of method. If noone has any objections, I could make PR.

**Comment by WestLangley** [comment]
> I propose to add this kind of method.

What method are you proposing?

**Comment by makc** [comment]
A method with self-documenting name that would take a matrix and set position / quaternion / scale, along with visible documentation.

**Comment by WestLangley** [comment]
`Object3D.applyMatrix( matrix )`?

**Comment by makc** [comment]
Waaait, there is exactly this method, that does exactly this thing.

![](https://images.encyclopediadramatica.se/8/8e/Picard_Facepalm.jpg)

I don't know where was I looking.
