### ISSUE TITLE
Where is geometry.fromJSON()?

### ISSUE THREAD

**Issue by mhelvens** [mrdoob/three.js#6139]
I'm trying to offload some geometry loading and processing into a web worker. To do this, the geometry needs to be translated into a serializable form, and it seems that `Geometry.prototype.toJSON()` was meant for exactly this type of thing.

But I can't for the life of me figure out how to turn that object back into a Geometry inside the main thread. Some help? Thanks!

**Comment by mhelvens** [comment]
Yes, I suppose this took the form of a question. But as a library designer you could also choose to take it as an request to improve the docs and/or API. :-)

**Comment by sjlynch** [comment]
Seconded. This would be really helpful.
