### ISSUE TITLE
Incorrect texture output on a SkinnedMesh

### ISSUE THREAD

**Issue by dimanux** [mrdoob/three.js#6146]
Hi,
I have results from QA team for the game (Three.js v70): http://gemioli.com/thesaloon/html5/gemioli/

They sent me a couple of game screenshots with a texture bug:

![screenshot_2015-01-29-14-52-51](https://cloud.githubusercontent.com/assets/2279914/6394193/e4d722ce-bde0-11e4-9346-475b43887da9.png)
![screenshot_2015-01-29-14-53-58](https://cloud.githubusercontent.com/assets/2279914/6394194/e5da3044-bde0-11e4-94bc-243e7f78930a.png)

Characters are SkinnedMeshes with MeshBasicMaterial (one map, skinning is true). Windows are SkinnedMeshes too, but they have correct visualization of texture.

It appears only on devices:
- S4 (Android 4.4.2, Chrome 40.0)
- Nexus 5 (Android 4.4.4, Chrome 40.0)
- Xperia A (Android 4.2.2, Chrome 40.0)
- Xperia Z (Android 4.1.2, Chrome 40.0)
- Sharp Mini (Android 4.2.2, Chrome 40.0)

On all other mobile devices the game seems to be working great.
I have not these devices right now. So any help or suggestion how to fix it will be appreciated.
Thanks

**Comment by dimanux** [comment]
Hm, It seems like a BoneTexture sometimes replace a Map texture. I made an output of a BoneTexture to a Map channel:
![screen](https://cloud.githubusercontent.com/assets/2279914/6410332/898016ca-be7f-11e4-93c0-916627a903ab.png)

But I have no idea why it is happen on some devices :(

**Comment by mrdoob** [comment]
I have a Nexus 5, if you send me the source files I can take a look.

**Comment by dimanux** [comment]
Thanks, I have sent you an email.

**Comment by mrdoob** [comment]
Can you try with this build?

https://github.com/mrdoob/three.js/raw/dev/build/three.min.js

We found some texture handling bugs. Maybe that helps...

**Comment by dimanux** [comment]
Unfortunately I haven't any device from the list above at the moment. But I have uploaded a debug version with 72dev here: http://www.gemioli.com/thesaloon/debug/debug.html

Please could you test it on your Nexus 5? I will send a message to QA team as soon as possible.

Also QA have added the Moto X phone to the list above :(

I have seen commits. And I have to mention that we pre-upload textures while game loading at TextureLoader class:
```javascript
		GEMIOLI.ImageLoader.load(url, function(image) {
			texture.image = image;
			texture.generateMipmaps = false;
			texture.magFilter = THREE.LinearFilter;
			texture.minFilter = THREE.LinearFilter;
			texture.needsUpdate = true;
			that.loading.remove(url);
			that.loaded.add(url, texture);
			GEMIOLI.Renderer.uploadTexture(texture, 0); // Pre-upload
			texture.dispatchEvent({type: 'load'});
		}, function(event) {
			that.loading.remove(url);
			texture.dispatchEvent(event);
		});
```
It's guaranteed that image catches the 'load' event before entering to uploadTexture function. But we don't check the 'complete' property of an input image.

**Comment by mrdoob** [comment]
Hmmm, I can't reproduce the issue on my Nexus 5 with the link in the first post anymore...?

**Comment by dimanux** [comment]
Thanks. We haven't changed it since it was posted here :( Maybe firmware/browser update fixed the issue?

And what about last link? Does it have the issue?

**Comment by mrdoob** [comment]
None of them have the issue. Nice game by the way!

**Comment by dimanux** [comment]
@mrdoob Thanks!

So I have no idea how to fix the issue without real device with it. As a temporary fix to pass QA tests of some portals we disable bone textures on Android devices at the moment...
