### ISSUE TITLE
Change Controls to use a fixed delta and use the standardized wheel event

### ISSUE THREAD

**Issue by arose** [mrdoob/three.js#6147]
Currently the `Controls` use some delta value from the event to determine how much to zoom. As it seems to be hardly possible to get a cross-browser consistent value (http://stackoverflow.com/questions/20110224/what-is-the-height-of-a-line-in-a-wheel-event-deltamode-dom-delta-line) a fixed delta value could be use instead.

Also, the `Controls` currently use the non-standard `mousewheel` and `DOMMouseScroll` events. There is, however, a standardized `wheel` event (https://developer.mozilla.org/en-US/docs/Web/Events/wheel).

My main goal is to get consistent zoom speed across browsers, so I am open for other suggestions!

Anyway, my suggestion is to replace

```javascript
if ( event.wheelDelta ) { // WebKit / Opera / Explorer 9

	delta = event.wheelDelta / 40;

} else if ( event.detail ) { // Firefox

	delta = - event.detail / 3;

}
```

with

```javascript
if( event.deltaY !== undefined ){

	delta = - Math.sign( event.deltaY ) * 6;

}
```

and to replace

```javascript
this.domElement.addEventListener( 'mousewheel', mousewheel, false );
this.domElement.addEventListener( 'DOMMouseScroll', mousewheel, false ); // firefox
```

with

```javascript
this.domElement.addEventListener( 'wheel', mousewheel, false );
```

**Comment by mrdoob** [comment]
Sounds good to me!

**Comment by arose** [comment]
Ok, I will prepare a PR for further testing.

**Comment by Baccanno** [comment]
The standard might not be cross-browser. Check http://www.sitepoint.com/html5-javascript-mouse-wheel/

**Comment by mrdoob** [comment]
#9526
