### ISSUE TITLE
ShaderMaterial bug on iOS8: iPad 3, iPhone 5

### ISSUE THREAD

**Issue by iRomano** [mrdoob/three.js#6148]
Hello
I'm using simple shader material. And i found bug on iOS8: iPad 3, iPhone 5 and iPhone 5c

I have merge geometry and custom shader material:
![bug](https://cloud.githubusercontent.com/assets/9501621/6398297/7532fc00-be0c-11e4-99d2-008140e8bbdb.jpg)

    for (i = 0; i < 10; i++) {       
            object = new THREE.Mesh(new THREE.CubeGeometry(10,10,10,10,10));
            object.position.z = Math.random() * 300;
            object.position.x = Math.random() * 300;
            object.position.y = Math.random() * 300;
            object.updateMatrix();
            mergeObject.merge(object.geometry, object.matrix);
        }

    mergeObject.computeFaceNormals();
    group = new THREE.Mesh(mergeObject, customShaderMaterial());
    group.matrixAutoUpdate = false;
    group.updateMatrix();
    scene.add(group);

How fix it?

**Comment by mrdoob** [comment]
Can you share a live example?

**Comment by iRomano** [comment]
@mrdoob 
Of course
Look on ipad3 or iphone5:
http://uperm.ru/sample_bug.html

**Comment by mrdoob** [comment]
Hmmm, I only have a iPad Air and it works fine there. Seems like it's a issue with those devices. Maybe you should report to Apple directly?

**Comment by iRomano** [comment]
@mrdoob 
If you use MeshPhongMaterial the result is the same.
If MeshPhongMaterial.vertexColor = THREE.FaceColors then all is well. bug disappears
How do I apply it to my shader?

**Comment by iRomano** [comment]
http://stackoverflow.com/questions/28664127/three-js-merge-geometry-and-custom-shader-bug-ios8
