### ISSUE TITLE
TrackballControl with animation on reset

### ISSUE THREAD

**Issue by nkint** [mrdoob/three.js#6149]
Hi!
I'd like to improve TrackballControl (and try to make a pull merge request) with an animation on the `reset` function with tween.js library. What I'm trying to do is to use a secondary `requestAnimationFrame` animation thing inside the TrackballControl.js so it is kind of self-contained and autonomous. I'm failing on it. If `TWEEN.update();` is called in the main loop everything works ok but if I'm trying to call only the Tween instance update with a secondary requestAnimationFrame in the control.. thing goes wrong. Right now my improvement is not usable because who use it must remember call the tween update outside.

The improved TrackballControl.js is here:
https://gist.github.com/anonymous/0d649528aa7b815ba4d4
and I have added things from line 342 to line 427

Example on how to use it:
```
// set up everything as usual, the scene, renderer, lights, etc
// set up TrackballControl as controls as usual

controls.reset(); // normal behaviour
controls.reset(true); // animate to position0
controls.reset(true, new THREE.Vector3(0,0,650)); // animate to a custom position
controls.reset(true, new THREE.Vector3(0,0,650), function() {console.log('end');}); // animate to a custom position and callback on animation end

// MUST BE 
function animate(time) {
    requestAnimationFrame(animate);
    TWEEN.update();
    renderer.render(scene, camera);
}

```

Please help me to find a clean way to resolve it and sorry for my poor coding skills.

**Comment by mrdoob** [comment]
I'm not a fan of complicating the controls. I would try putting something on a layer on top instead.

**Comment by newemka** [comment]
How can i reset the camera position trackballcontrols.js with a link (button) on the same page?

**Comment by WestLangley** [comment]
@newemka  As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by newemka** [comment]
ho i'm so sorry... here is a feature request, please make a proper example with a button that use the trackballcontrols.js reset function ....
