### ISSUE TITLE
SkinnedMesh shader places vertices inaccurately?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6151]
Not sure if bug or feature, or stupid question again :) Take a look at this screenshot:
![screen shot 1](http://i.gyazo.com/357ba021276d4801f38fddd04fcea900.png)
This is the model in binding pose, software bones, checked against 3dmax. Now this:
![screen shot 2](https://cloud.githubusercontent.com/assets/242577/6406268/afd379f8-be2e-11e4-99d0-a0741844bb56.png)
is the same skin (+ hair) and bones in three.js - note that arm bones end up largely outside of arms. Is this known limitation of your animation system? How can I get better match? It is essential for the app.

**Comment by mrdoob** [comment]
Hmmm, have you tried with other models? It seems as there is some scaling going on.

**Comment by makc** [comment]
This falls under stupid questions category :( I was parsing skeletal data incorrectly. Now the match is pretty good:
![screen shot 2015-02-27 at 16 09 28](https://cloud.githubusercontent.com/assets/242577/6414905/6406579e-be9b-11e4-80cf-d0ae85070edc.png)

**Comment by makc** [comment]
( but now you have a bug in wireframe material :smile: )

**Comment by mrdoob** [comment]
> This falls under stupid questions category :(

I should create one just for you... ;)

> ( but now you have a bug in wireframe material :smile: )

Not really a bug, wireframe in `BufferGeometry` is like that by now... Need to find a nice solution.
