### ISSUE TITLE
No shadows when using latest standard version of three.js

### ISSUE THREAD

**Issue by michelkogan** [mrdoob/three.js#6155]
I'm using deferred rendering with correct lighting to show a text with its shadows but just can't make shadows appear on the floor. I just attached a simple & small test to show you the problem. 

The funny thing is when I use http://alteredqualia.com/three/examples/js/three.max.pointshadows.js instead of latest standard libraries (r70 version), I get the correct result.

My question is what's wrong with my code and why it works when I use older version of threejs. (I don't know, but It seems [three.max.pointshadows.js](http://alteredqualia.com/three/examples/js/three.max.pointshadows.js) contains some kind of older version of three.js plus some more libraries, its also being used in [this example](http://alteredqualia.com/three/examples/webgl_deferred_shadowmap_point.html))  

Any help will be appreciated.

```html
<!DOCTYPE html>
<html>
<body>
<script src="js/threejs/three.js"></script>
<script src="js/threejs/shaders/UnpackDepthRGBAShader.js"></script>
<script src="js/threejs/renderers/WebGLDeferredRenderer.js"></script>
<script src="js/threejs/ShaderDeferred.js"></script>
<script src="js/threejs/shaders/CopyShader.js"></script>
<script src="js/threejs/shaders/FXAAShader.js"></script>
<script src="js/threejs/shaders/SSAOShader.js"></script>
<script src="js/threejs/postprocessing/EffectComposer.js"></script>
<script src="js/threejs/postprocessing/RenderPass.js"></script>
<script src="js/threejs/postprocessing/ShaderPass.js"></script>
<script src="js/threejs/postprocessing/MaskPass.js"></script>
<script src="js/threejs/Detector.js"></script>

<!--In example 2, I just used http://alteredqualia.com/three/examples/js/three.max.pointshadows.js instead of above libraries and everything fixed and shadowing appears -->
<script src="js/helvetiker_bold.typeface.js"></script>


<script>
var SHADOW_MAP_WIDTH = 1024, SHADOW_MAP_HEIGHT = 1024;

var MARGIN = 100;
var SCALE = 0.75;

var SCREEN_WIDTH = window.innerWidth;
var SCREEN_HEIGHT = window.innerHeight - 2 * MARGIN;
var FLOOR = -250;

var camera, controls, scene, renderer;
var container, stats;

var NEAR = 5, FAR = 10000;

var morph, morphs = [];

var light1, light2;

init();
animate();

function init()
{
    container = document.createElement('div');
    document.body.appendChild(container);

    camera = new THREE.PerspectiveCamera(23, SCREEN_WIDTH / SCREEN_HEIGHT, NEAR, FAR);
    camera.position.set(0, 0, 1900);

    scene = new THREE.Scene();

    var angle = Math.PI * 0.25;
    var intensity = 1;
    var shadowCameraFov = 50;

    light2 = new THREE.SpotLight(0xff6633, intensity, 0, angle, 1);
    light2.position.set(0, 500, -1000);
    scene.add(light2.target);

    light2.castShadow = true;
    light2.shadowCameraNear = 500;
    light2.shadowCameraFar = camera.far;
    light2.shadowCameraFov = shadowCameraFov;
    light2.shadowBias = 0.005;
    light2.shadowDarkness = 0.75;
    light2.shadowMapWidth = SHADOW_MAP_WIDTH;
    light2.shadowMapHeight = SHADOW_MAP_HEIGHT;
    scene.add(light2);

    createScene();

    renderer = new THREE.WebGLDeferredRenderer({ width: SCREEN_WIDTH, height: SCREEN_HEIGHT, scale: SCALE, antialias: true, tonemapping: THREE.UnchartedOperator, brightness: 8 });

    container.appendChild(renderer.domElement);
    renderer.shadowMapEnabled = true;
    renderer.shadowMapType = THREE.PCFSoftShadowMap;
}

function createScene()
{
    var geometry = new THREE.PlaneGeometry(10000, 10000);
    var planeMaterial = new THREE.MeshPhongMaterial({ color: 0xffdd99 });

    planeMaterial.ambient = planeMaterial.color;

    var ground = new THREE.Mesh(geometry, planeMaterial);
    ground.position.set(0, FLOOR, 0);
    ground.rotation.x = -Math.PI / 2;
    scene.add(ground);

    var textGeo = new THREE.TextGeometry("MrDOOB", {
        size: 200,
        height: 50,
        curveSegments: 12,
        font: "helvetiker",
        weight: "bold",
        style: "normal",
        bevelThickness: 2,
        bevelSize: 5,
        bevelEnabled: true
    });

    textGeo.computeBoundingBox();
    var centerOffset = -0.5 * ( textGeo.boundingBox.max.x - textGeo.boundingBox.min.x );
    var textMaterial = new THREE.MeshPhongMaterial({ color: 0xaaaaaa, specular: 0xaaaaaa, shininess: 100, ambient: 0x000000, wrapAround: false });

    var mesh = new THREE.Mesh(textGeo, textMaterial);
    mesh.position.x = centerOffset;
    mesh.position.y = FLOOR+10;
    mesh.castShadow = true;
    mesh.receiveShadow = true;
    scene.add(mesh);
}

function animate()
{
    requestAnimationFrame(animate);
    renderer.render(scene, camera);
}
</script>

</body>
</html>
```
Result of above code (no shadows on the floor):

![screen shot 2015-02-28 at 18 39 52](https://cloud.githubusercontent.com/assets/280553/6426605/488d8a9e-bf79-11e4-8b3f-340f7be1e2ae.png)

Result of literally exact same code when using http://alteredqualia.com/three/examples/js/three.max.pointshadows.js instead of latest version of three.js:

![screen shot 2015-02-28 at 18 39 45](https://cloud.githubusercontent.com/assets/280553/6426608/6a5468dc-bf79-11e4-9e0c-27b3e133191c.png)

I'm not sure if this question is an issue with threejs library or not. that's why I'm asking it here.
I've also asked it in [SO](http://stackoverflow.com/questions/28784004/no-shadows-on-deferred-rendering-mode-when-using-latest-standard-version-of-thre), but got no chance to get answers.
Any help will be appreciated.

**Comment by michelkogan** [comment]
I saw similar post closed, I just moved this question to stackoverflow:
http://stackoverflow.com/questions/28784004/no-shadows-on-deferred-rendering-mode-when-using-latest-standard-version-of-thre

**Comment by michelkogan** [comment]
I'm not sure if this question is an issue with threejs library or not. that's why I'm asking it here.

**Comment by titansoftime** [comment]
I don't see a ```ground.receiveShadow = true;```

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by michelkogan** [comment]
@titansoftime ground.receiveShadow has no effect at all. 
@WestLangley The problem is it works with older version of threejs, doesn't it consider as a bug in newer version ?

**Comment by mrdoob** [comment]
`three.max.pointshadows.js` was a custom version of the library that alteredqualia did for that experiment.

**Comment by michelkogan** [comment]
@mrdoob Ok then, that explains everything. The code was obfuscated but had a confusing `REVISION:"55dev"` tag at the first line, that's why I considered its really revision 55 of three.js. So I should implement my own code to get it work and its not yet implemented, right ?
