### ISSUE TITLE
Google CDN for Three.js r69  has a problem with THREE.CanvasRenderer

### ISSUE THREAD

**Issue by otuk** [mrdoob/three.js#6156]
I switched to using the google CDN for Three.js , the latest version they serve is r69 and it has a problem with the fallback renderer constructor.  I get the following error on the call to construct the fallback renderer (  renderer = new THREE.CanvasRenderer();    )

TypeError: undefined is not a constructor (evaluating 'new THREE.CanvasRenderer')

The earlier versions they serve (r68 or r67) do not seem to gave the issue and canvas renderer is created.  Not sure how to get this corrected at 

https://developers.google.com/speed/libraries/devguide

, but in case you have the same issue, use a different version.

**Comment by Baccanno** [comment]
Be aware that canvasRenderer moved from the lib to the example folder js/renderers, although it has only really happens in r70 not in r69 (but a warning was already there)

Sure about the version you use ?
