### ISSUE TITLE
r69 -> r70 sprite scale

### ISSUE THREAD

**Issue by Baccanno** [mrdoob/three.js#6157]
I have a weird behaviour with sprites passing from r69 to r70.

I need to increase some sprite scales 10 times. 

Some others need to be reduced by 2.

Some sprites have the same size ...

There are some z-fighting situations that behaves differently so we have to update some positions also. Although it seems more that it was a bug fix because it now act perfectly well. In r69 sometimes setting position so an element would be under didn't work well, especially with mixed transparent and custom blended elements. Now it seems fixed !

**Comment by Baccanno** [comment]
seems to be possibly related to https://github.com/mrdoob/three.js/commit/4fc7c4ea689ba0112fe9bed793da8e5bc06057bb

**Comment by mrdoob** [comment]
Done! Thanks!
