### ISSUE TITLE
Does raycaster.setFromCamera()  work for the model that loader from outside?

### ISSUE THREAD

**Issue by hjk61314** [mrdoob/three.js#6162]
Please see the example in the source of Threejs   (examples/webgl_loader_obj_mtl.html)
I want to reach the effect:
When using mouse to click the model,console will print the corresponding 3D coordinates of the model.

I once refered to (examples/canvas_interactive_cubes.html) ,but doesnot work

document.addEventListener( 'mousedown', onDocumentMouseDown, false );
function onDocumentMouseDown( event ) {

	event.preventDefault();

	mouse.x = ( event.clientX / renderer.domElement.width ) * 2 - 1;
	mouse.y = -( event.clientY / renderer.domElement.height ) * 2 + 1;
	console.log("Mouse1 X " + mouse.x  + "          Mouse1 Y " + mouse.y);
				
	raycaster.setFromCamera( mouse, camera );

	var intersects = raycaster.intersectObjects( objects );
	console.log("After intersectObjects--------" + intersects.length);
				
	if ( intersects.length > 0 ) {

		intersects[ 0 ].object.material.color.setHex( Math.random() * 0xffffff );

		var particle = new THREE.Sprite( particleMaterial );
		particle.position.copy( intersects[ 0 ].point );
		console.log("Mouse3 X " + intersects[ 0 ].point.x  + "          Mouse3 Y "                            +  intersects[ 0 ].point.y + "        Mouse3 Z " + intersects[ 0 ].point.z);
		particle.scale.x = particle.scale.y = 16;
		scene.add( particle );		
        }
}

The firefox prints:
"After intersectObjects--------0"

Does raycaster.setFromCamera()  work for the model that loader from outside?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

Do this:

    var intersects = raycaster.intersectObjects( objects, true );

**Comment by hjk61314** [comment]
It works!
Thank you.
