### ISSUE TITLE
Blender json export missing geometries ( 71dev )

### ISSUE THREAD

**Issue by hulf** [mrdoob/three.js#6165]
The blender file can be downloaded here:
http://s000.tinyupload.com/?file_id=28438285579402667958

Other models export and work, just this one that was generated in Arbaro exports with empty geometries ( "geometries": [], )  :

![drevo](https://cloud.githubusercontent.com/assets/10427535/6472320/ccbe0c6a-c1f1-11e4-8fb7-d72bb9bcb1a2.jpg)

Exporter settings include: scene, materials, vertices, faces, normals, uv.
The material for the model gets exported. 

Other models work:
![drevo2](https://cloud.githubusercontent.com/assets/10427535/6472378/489aeb28-c1f2-11e4-9cdc-4fe47a48a200.jpg)

**Comment by repsac** [comment]
Downloaded the file. Didn't get to this last night but will try and look at it today.

**Comment by repsac** [comment]
hmm can't recreate this, I got geometries in this JSON
http://pastebin.com/a8E3a1Wt

and the log
http://pastebin.com/qq0zXwxt

this is with version `(1, 3, 1)` of the exporter

**Comment by hulf** [comment]
Excuse me repsac for the late reply, you got it fixed...somewhere on the way. Thanks for the great work you provide, together with all others. You are my heroes.
