### ISSUE TITLE
Either BufferGeometryLoader.parse or BufferGeometry.toJSON is broken :S

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6166]
[here](https://github.com/mrdoob/three.js/blob/dev/src/loaders/BufferGeometryLoader.js#L39) it expects "attributes" in json, but it can't find any, because [here](https://github.com/mrdoob/three.js/blob/dev/src/core/BufferGeometry.js#L875) attributes are nested under "data".

nice quest to fix json files before three can load them and all, but what about making it just work :wink:

**Comment by mrdoob** [comment]
Uh oh... Weird...

**Comment by brentrockwood** [comment]
Any progress on this?  Shall I fork and try and fix?

**Comment by makc** [comment]
Tbh there are older bugs than this ) It is not big deal to fix, though. You could just put something like
```javascript
var attributes = json.attributes || json.data.attributes;
```
etc, so that things like ObjectLoader would not break. or, you could fix it there as well.

**Comment by makc** [comment]
Oh and btw, I have not tested - but I suspect similar issue exists with old Geometry, since ObjectLoader passes data.data to JSONLoader's parse() too
