### ISSUE TITLE
Either "Flatten" or "Convert to BufferGeometry" in the editor is buggy as hell :S

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6167]
Or BufferGeometry.toJSON. Or BufferGeometryLoader.parse.

I have loaded perfectly normal obj Eiffel tower model into the editor, rotated it, flatten it, converted to buffer geometry and exported. Then stripped json header because [reasons](https://github.com/mrdoob/three.js/issues/6166), then loaded into r70. And what do I see there? This:

![screen shot 2015-03-04 at 0 44 17](https://cloud.githubusercontent.com/assets/242577/6475164/a427778a-c207-11e4-8e3c-4cd67ddfa76d.png)

I am kind of upset with the result.

**Comment by mrdoob** [comment]
`master` editor or `dev` editor? Also, can you share the eiffel mode so I can reproduce?

**Comment by makc** [comment]
online editor. must be master. the model is 700K, I will find your email.

**Comment by mrdoob** [comment]
Can you give `71dev` a try?

**Comment by makc** [comment]
Maybe let's just close this issue since the bug is not pinned any way, and I have so little idea what happened. The other day I took more or less the same steps with another model and it all worked just fine. My prime suspect would be conversion to buffer geometry, so keep an eye on it.

**Comment by WestLangley** [comment]
> My prime suspect would be conversion to buffer geometry, so keep an eye on it.

Keep an eye on what?

Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by makc** [comment]
> Keep an eye on what?

bug reports involving this convertor, obviously
