### ISSUE TITLE
NearestFilter sampling ignored when anisotropy > 1

### ISSUE THREAD

**Issue by andyhall** [mrdoob/three.js#6170]
I noticed that on Windows, nearest neighbor sampling seems not to work when a texture's anisotropy is set greater than 1. 

Demo: http://jsfiddle.net/j8tkousg/1/
Texture shows up blurry on windows, but setting `texture.anisotropy = 1` fixes it. 
Tested with: R70, all windows browsers. On my Mac the issue doesn't occur in any browser.

Is this an OpenGL fact of life, or something else? I found the same issue in Babylon.js, but I can't find any discussion of it being a known issue.

**Comment by andyhall** [comment]
Ok, it seems that this is a D3D limitation - apparently D3D allows only one kind of filtering at a time, so if anisotropic filtering is set then texture filtering is ignored.

So FOL I guess. Not sure if it warrants a warning or a note in the docs or whatever.

**Comment by Mugen87** [comment]
I would say this is something for the D3D docs.
