### ISSUE TITLE
THREE.Line.mode serialize/deserialize

### ISSUE THREAD

**Issue by bGute** [mrdoob/three.js#6171]
I serialized a THREE.Line object with .toJSON (mode = 1).
When i deserialze it with ObjectLoader.parse the mode is 0 (default value).
Why is the mode not considered [here](https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L700) and [here](https://github.com/mrdoob/three.js/blob/master/src/loaders/ObjectLoader.js#L308)?

**Comment by mrdoob** [comment]
Forgot about it O:)
Could you do a PR to fix it?

**Comment by bGute** [comment]
sure!
