### ISSUE TITLE
THREE.Material.toJSON LineBasicMaterial is missing

### ISSUE THREAD

**Issue by bGute** [mrdoob/three.js#6173]
When i deserialize a THREE.Line object it has alway the default color.
Maybe [here](https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L180) is the case for LineBasicMaterial  missing?

**Comment by mrdoob** [comment]
Yep! Also missing... For this one you could just edit the file directly for creating a PR.
https://github.com/mrdoob/three.js/edit/dev/src/materials/Material.js#L161
