### ISSUE TITLE
Persist Blender Export settings between sessions

### ISSUE THREAD

**Issue by rkusa** [mrdoob/three.js#6177]
I use different export settings for different blender files. These settings are currently saved into the `/tmp` of the current blender session, i.e., they are only persisted for the current blender session.

I was thinking about persisting them permanently for each blender file.

Possible solutions:

1. save a config file next to the `.blend` file
2. save settings as custom properties added to the scene
3. save settings in an embedded text file (usually used for py scripts)

Opinions? @repsac?

Sorry for the exporter spam today ;-)

**Comment by repsac** [comment]
I have seen this before and it is annoying (especially how new Blender sessions reset the prefs file). In fact on animation test export scenes I do have an embedded py script, with the custom options set, that I use so I don't have to mess with anything. 

I think 1 and 2 could be part of an enum option to give the user some choice in the matter.

**Comment by titansoftime** [comment]
This would be nice. Having to set the params on each export is a pain. This I know did work in the previous exporter.

**Comment by repsac** [comment]
This may have been a change in Blender's behavior because I just tested with the old exporter and the problem is still there. Blender seems to blow away its temp path when it closes. This may be resolved by not using Blender's temp dir and just the system temp dir.

**Comment by rkusa** [comment]
To get more clear on (3). I was thinking about utilizing the py scripts embedding feature to save JSON instead of a py script. Would be easier to implement than (2), because the saving and loading from JSON is already there.

**Comment by satori99** [comment]
Isnt there already a mechanism do this for blender addons? Or am i misunderstanding this thread?

I have used  `bl_options = {'PRESET'}` in my addon Operator code to enable preset options before.

This automatically adds a dropdown control to allow to save and restore preset files . They are saved as py scripts  in `scripts/presets/`. And control value that is not the default will be saved to the preset file.

**Comment by rkusa** [comment]
I have added a PR if someone wants play around with @satori99 suggestion. Thanks for the suggestion. I've asked for possible solutions in the #blendercoders channel yesterday - and this one was not mentioned ;-)

![screen shot 2015-03-05 at 07 23 17](https://cloud.githubusercontent.com/assets/409021/6500208/c672336e-c308-11e4-97fd-35c3f0afd7e6.png)

What do you guys think, if we consider to merge this PR, should we still consider (1), (2) or (3)? Because after opening Blender it is still required to chose the wanted preset.

**Comment by satori99** [comment]
One-liners are nearly always a good solution :P

**Comment by repsac** [comment]
I think this will be fine for starters. Go with the simplest solution and if it works and nobody complains just leave it.

**Comment by rkusa** [comment]
Solution *(2)* just got merged. Saving is done using a button at the bottom of the settings panel:

![screen shot 2015-03-11 at 17 41 05](https://cloud.githubusercontent.com/assets/409021/6601435/f865449e-c815-11e4-909f-73205c1f397d.png)
