### ISSUE TITLE
Cannot create new mesh after importing a 3D model into Three.js

### ISSUE THREAD

**Issue by tinapi** [mrdoob/three.js#6181]
I used OBJMTLLoader to import a 3D model from maya to three.js, however, as I tried to add a new mesh to my scene, the output went black and my 3D model was gone too! So I wonder if there is a way to create additional meshes in my code after imported a 3D model into the scene?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

Yes, you should be able to do that.
