### ISSUE TITLE
THREE.ColladaLoader, kinematicsModels is not defined

### ISSUE THREAD

**Issue by cub** [mrdoob/three.js#6182]
Hi,

Small problem (and easy fix), if we uglify the THREE.ColladaLoader "js/loaders/ColladaLoader.js" the kinematicsModels throw an error (undefined). The var kinematicsModels is never declared. But the kinematicsModel is declared twice :

https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/ColladaLoader.js#L11&L28
Line 11 >> var kinematicsModel;
Line 28 >> var kinematicsModel;

Added an "s" to the last one var fixed the problem.

**Comment by mrdoob** [comment]
This has already been fixed in the `dev` branch. 7b0022e7d6468bdd32f6b715cad0e8a9c40df686
