### ISSUE TITLE
Blender export includes material from previous opened projects ( 71dev ) 

### ISSUE THREAD

**Issue by hulf** [mrdoob/three.js#6183]
Perhaps this is more a Blender issue then the exporters, in this case excuse me to bother with it.

I had issues loading models, that had not a "fresh" opened Blender before the export. Everything loads without error or warning and nothing is displayed. 

The issue can't sometimes be reconstructed that easy ( so that the object is not displayed ). I could see that there were defined images from the "old" project in the exported json ( the images were not missing, that was not the issue for not displaying things ).

If you require solid json examples let me know.

Thanks.

**Comment by repsac** [comment]
When was the last time you pulled the `dev` (r71 dev)? There was a recent PR that had a bug fix to only include used materials https://github.com/mrdoob/three.js/pull/6131

**Comment by hulf** [comment]
I'm sorry for the late reply. You got it right. I will have things more tested before I bother again. 

Thanks.
