### ISSUE TITLE
webGL renderer not raytracing/displaying properly for 27" retina display

### ISSUE THREAD

**Issue by o1sound** [mrdoob/three.js#6186]
Hello,

If I expand the size of the webGL renderer window on a 27" retina iMac, the raytracing breaks down and the perspective becomes too wide for the following three.js demos (for screenwidths larger than ~80% the width of the iMac's screen):

interactive / raycasting / pointcloud
http://threejs.org/examples/#webgl_interactive_raycasting_pointcloud

octree / raycasting
http://threejs.org/examples/#webgl_octree_raycasting

Both of the above demos work fine for smaller dimensions thanks to `window.devicePixelRatio`. However, as the window width expands through 80% of the iMac's screen width, the demos become progressively more horizontally stretched and the raytracing breaks down.

UPDATE: the demos actually work in Firefox 36.0.1 but do NOT work in
Chrome Version 41.0.2272.76 (64-bit)
Safari Version 8.0.3
Opera 27.0.1689.76

**Comment by mrdoob** [comment]
I think Chrome had a hardcoded canvas size limit. I think that code was removed recently.

**Comment by Mugen87** [comment]
Because i had the same problem with my iMac 5K last year, i've reported the bug on the chromium issue tracker. The following [link](https://bugs.chromium.org/p/chromium/issues/detail?id=445542) recorded the entire problem and the corresponding fix. I think we can close this issue here.
