### ISSUE TITLE
Opacity/Alpha at certain camera angles

### ISSUE THREAD

**Issue by nosh247** [mrdoob/three.js#6190]
Hey MrDoob, just want to say your three.js is the best thing that has happened to me lol.
Ok the issue:
Im prototyping a project and if you look here:
http://franciscochong.com/THREE/

at first it looks fine, alpha are transparent (see through) as they are supposed to, but if you yaw the camera to look at "the floor" you will see that the alpha/opacity disappears.

Would greatly appreciate any help

Thanks,
Fch

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

In your skybox, set `material.transparent` to `false`. You should take the time to understand why this solves the problem.

Please use stackoverflow if you need help.
