### ISSUE TITLE
BufferGeometry's fromGeometry could generate indexed geometry

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6191]
Sometimes? Most of the times? In fact, it could be done even in case with face normals - if the model has enough neighbour faces with the same normal, it could even make sense :) File it under suggestions.

**Comment by makc** [comment]
in fact, both this and issue #6188 could be solved using the same code, that would accept a set of vertex data, identify it in existing vertices and point the index there, or add new vertex if not found.

**Comment by makc** [comment]
In fact, this code could be better placed in separate 'class'. Let me come back with the example...

**Comment by WestLangley** [comment]
> BufferGeometry's fromGeometry() could generate indexed geometry

You have to be careful. A cube, for example, has hard edges, and needs to retain duplicate vertices so vertex normals can be unique. I certainly would not merge vertices when converting to `BufferGeometry`.

If you still want to create _indexed_ `BufferGeometry`, that is up to you, but I would not change the `Geometry`'s geometry in the process of conversion.

**Comment by makc** [comment]
Yes, when I said 'identify it in existing vertices', I meant using all of attributes, not just the position.

**Comment by mrdoob** [comment]
Yes, this could be a "weld" method of sorts...

**Comment by benaadams** [comment]
I did this PR #6324 it doesn't get the uvs right at one point, not sure why, also don't like the name of the function. Could have fromGeometry check whether there are indexes and switch paths if so...

**Comment by Wilt** [comment]
@WestLangley wrote:

> You have to be careful. A cube, for example, has hard edges, and needs to retain duplicate vertices so vertex normals can be unique

But can we not totally skip the normals for boxes or cubes and use flat-shading as a default for rendering them? It would make the `BufferGeometry` for those geometries much more compact (no repetition of points so only 8 vertices and no normals at all). Check an example [here](https://jsfiddle.net/wilt/17tzmbqn/1/)

**Comment by mrdoob** [comment]
@Wilt It's better if the materials doesn't know what the geometry is...

**Comment by WestLangley** [comment]
@Wilt `MeshLambertMaterial` requires normals. So does `MeshNormalMaterial`, for example.

**Comment by Wilt** [comment]
I understand, that material and geometry should be independent. But I was thinking of something like mentioned in [this comment here](https://github.com/mrdoob/three.js/issues/6117#issuecomment-75461347). I hope I understood it correctly... 

For buffer geometries without a normal array this could be default behavior (dFdy dFdx functions are used for calculating normals) independently from what shading method was set in the material instance.

Or is that not possible?

**Comment by makc** [comment]
@Wilt I thought they have implemented it, but TBH I have lost tracks of what happened then

**Comment by mrdoob** [comment]
Yes, it has been implemented. But, again, the material shouldn't need to know anything about the geometry. The simpler things are and the less the user should be aware of, the better.

**Comment by jee7** [comment]
With #15514 this seems to be important. Wouldn't the fix just be to add `BufferGeometryUtils.mergeVertices(geometry)` to the end of the `BufferGeometry.fromGeometry()` code?

Or to create a method `BufferGeometry.toIndexed()`, (just like there is `.toNonIndexed()`) which would do what `BufferGeometryUtils.mergeVertices(geometry)` currently does?

**Comment by Mugen87** [comment]
> Wouldn't the fix just be adding BufferGeometryUtils.mergeVertices(geometry) to the end of the BufferGeometry.fromGeometry() code?

No, since you don't want to merge vertices at hard edges. Vertices could be identical but normal and/or uv data different.

**Comment by jee7** [comment]
@Mugen87, but `BufferGeometryUtils.mergeVertices(geometry)` checks the attributes and merges only those verts, where all the attributes (incl normal, uv etc) are the same.

**Comment by Mugen87** [comment]
Ups, totally forgot that (once again 😅).

**Comment by Mugen87** [comment]
@jee7 Can you please elaborate a bit why `BufferGeometry.fromGeometry()` should return an indexed geometry? In which way would this be beneficial for you?

**Comment by jee7** [comment]
It just seems to make sense. The regular geometry is indexed (it has `Face3` objects that have the indices). So why would a generated `BufferGeometry` from that be non-indexed? 
I described the example with a sphere in #16990. The regular geometry had 121 verts, but the generated `BufferGeometry` had 540 verts. After merging them (could be done with `BufferGeometryUtils`, the vert count went down to 119, which is closer to the original geometry, the pole verts were also merged).

The benefit comes not having to include the additional `BufferGeometryUtils` file and calling the merge function manually to cover for the inefficient functionality in core.

**Comment by jee7** [comment]
To elaborate more on the example from #16990. I describe there that I want to do this:
```javascript
var geometry1 = new THREE.SphereBufferGeometry( 0.7, 10, 10 );
var geometry2 = new THREE.Geometry().fromBufferGeometry(geometry1);
var geometry3 = new THREE.BufferGeometry().fromGeometry(geometry2);
```
In reality I want to do some parsing of the vertices. So in the middle there would be something like:
```javascript
for (var i = 0; i < geometry2.vertices.length; i++) {
   some Vector3 ops on geometry2.vertices[i]
}
```
Of course I could go loop through the `geometry1.attributes.position.array`, create the `Vector3` objects explicitly, do some vector ops with them, then explicitly flatten them back into an array... But that is a lot more code then just asking the lib for a regular `Geometry` to modify the verts.

**Comment by Mugen87** [comment]
> The regular geometry had 121 verts, but the generated BufferGeometry had 540 verts.

But you will need an additional index which will also allocates some memory. So I don't think that memory efficiency is a big matter here.

The thing is that the visual output will be identical, no matter if you render an indexed or non-indexed geometry. There is only a difference if you are going to post-process the resulted geometry in some way (e.g. methods like `computeVertexNormals()` will behave differently).

> Of course I could go loop through the geometry1.attributes.position.array, create the Vector3 objects explicitly, do some vector ops with them, then explicitly flatten them back into an array... But that is a lot more code then just asking the lib for a regular Geometry to modify the verts.

TBH, I do not understand this argument here. The project is going to deprecate `Geometry` since working with it is extremely inefficient. It's true that the docs are a bit outdated because they somewhat promote `Geometry` for beginners. I think we should not do this anymore. Working with `BufferGeometry` and methods like `Vector3.fromBufferAttribute()` should not produce significant more code than `Geometry`. And it is much faster.

**Comment by jee7** [comment]
> But you will need an additional index which will also allocates some memory. 

| verts | floats (32 bits) | index | ints (16 bits) | total bits |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 540 | 540 * 3 * 32 = 51840  | 0 | 0 | 51840 + 0 = 51840 |
| 119 | 119 * 3 * 32 = 11424 | 540 | 540 * 16 = 8640 | 11424 + 8640 = 20064 |

About 2x less memory usage.

> Besides, there are certainly scenarios where no vertices are shared at all so you produce an index for no reasons. 

There can be a check for that.

> So I don't think that memory efficiency is a big argument here (besides I've heard some GPU drivers produce a triangle soup anyway).

That is up to the GPU drivers.

The main argument is that there should be a logical conversion between `Geometry` and `BufferGeometry`. Converting from one to another and then back again should ideally produce the initial result. Currently converting to `BufferGeometry` just blows up the number of verts without any reason.

> The project is going to deprecate `Geometry` since working with it is extremely inefficient. It's true that the docs are a bit outdated because they somewhat promote `Geometry` for beginners. I think we should not doing this anymore. 

Well, my take on this is that the `Geometry` is still quite useful for beginners for learning purposes. And this threat of removing it has been going around for several years. But, sure, removing `Geometry` altogether will also remove the conversion issue described.

**Comment by Mugen87** [comment]
> But, sure, removing Geometry altogether will also remove the conversion issue described.

Indeed. And I think we should do this better sooner than later. To be more precise: Stop rendering `Geometry`, rename the class to `LegacyGeometry` and then move it out of the core (see #15387). After some time, the class can be removed completely.

**Comment by Mugen87** [comment]
With the removal of `THREE.Geometry` from core, this issue can be closed now.
