### ISSUE TITLE
OBJ Loader doesn't work online.

### ISSUE THREAD

**Issue by KhaledElAnsari** [mrdoob/three.js#6193]
Hey,

I'm using the OBJLoader in my website, it works fine locally but when upload the website online the loader stops working! it keep telling me that the .obj file is not found
"Failed to load resource: the server responded with a status of 404 (Not Found) http://atomkit.com/hijazy/necklace.obj"

I tried to use the JSON converter but the converter doesn't work, and to be honest using .obj files is easier for me so please if you how to solve this problem tell me.

**Comment by mrdoob** [comment]
I'm afraid this has nothing to do with three.js. This is a server configuration issue.
