### ISSUE TITLE
THREE.Material: 'transparent' parameter is undefined

### ISSUE THREAD

**Issue by redsolarmoon** [mrdoob/three.js#6197]
Possibly related to https://github.com/mrdoob/three.js/issues/4383

Hey guys. I was looking at the parallax demo it generates a warning that I looked into further. Seems to be related to how transparent/opacity parameter is getting set when creating the Lambert material through the Loader.

Starting at...
https://github.com/mrdoob/three.js/blob/dev/examples/webgl_effects_parallaxbarrier.html#L490

I then came across the following line in Loader.js...
https://github.com/mrdoob/three.js/blob/dev/src/loaders/Loader.js#L229

Here's the logic...
```javascript
if ( m.transparent !== undefined || m.opacity < 1.0 ) {
	mpars.transparent = m.transparent;
}
```
Findings...
First condition is false (**m.transparent** is **undefined**)
Second condition is true (**m.opacity** values seen were less than 1)

Since **m.transparent** equates to **undefined**, **mpars.transparent** becomes **undefined**. Thus, the console is generating warnings of **undefined** on every material meeting the condition.

I'm not sure how I would go about fixing this seeing as you guys were discussing the matter and the suggestion is still open. Plus, I don't fully understand the whole Three.js library to add an expert opinion. But, I thought I would make a mention of what I found.

**Comment by WestLangley** [comment]
Nice find. How about something like this?

    if ( m.transparent !== undefined ) {

        mpars.transparent = m.transparent;

    }

    if ( m.opacity !== undefined && m.opacity < 1.0 ) {

        mpars.transparent = true;

    }

Later in the file there are several instances of this pattern:

	if ( m.opacity ) {

		mpars.opacity = m.opacity;

	}

What if `m.opacity` is zero? It should be:

	if ( m.opacity !== undefined ) {

		mpars.opacity = m.opacity;

	}

**Comment by mrdoob** [comment]
Maybe just this?

    if ( m.transparent !== undefined ) {

        mpars.transparent = m.transparent;

    } else if ( m.opacity < 1.0 ) {

        mpars.transparent = true;

    }

**Comment by WestLangley** [comment]
What if `m.transparent` is false and `m.opacity` is 0.5?

My solution auto-corrects, which was the original intention, I believe.

**Comment by mrdoob** [comment]
I think you're right. I'll amend.

**Comment by dubejf** [comment]
Looks like it was fixed in r71 by
6f70fc1c66483c92a4502f29ec199953f34de9b5
5f009a9c49a2c9b5f1c14956a981ddb4edcb1416
