### ISSUE TITLE
programmatically rotating sphere using orbit controls

### ISSUE THREAD

**Issue by rohanbhangui** [mrdoob/three.js#6202]
Hi I was wondering if I could get some help. I have a sphere which behaves like a globe. I have points on this sphere that are programmatically placed on this sphere by converting latitude and longitude values to 3d points relative to the center of the sphere. Now orbit controls plugin allow me to rotate said sphere but I am having trouble programmatically rotating the sphere using orbit controls such that when i click on a point it should rotate the sphere so that said point is in the center of the screen aka facing the center of the camera. Any ideas?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

`OrbitControls`is designed to rotate a camera only.

**Comment by rohanbhangui** [comment]
@WestLangley sorry 1 last question, (i didnt get much support help on stackoverflow thats why i asked here, sorry) i know orbit controls is meant for the camera, im wondering if there is a way to rotate the camera to a given point on a the sphere programmatically

**Comment by rohanbhangui** [comment]
http://stackoverflow.com/questions/28710308/three-js-rotating-objects-around-a-sphere
