### ISSUE TITLE
THREE.ObjectLoader PlaneBufferGeometry is missing

### ISSUE THREAD

**Issue by bGute** [mrdoob/three.js#6203]
In [ths](https://github.com/mrdoob/three.js/blob/dev/src/loaders/ObjectLoader.js#L85) switch case the **PlaneBufferGeometry** is missing. This result in an error because geometry.uuid is not defined, when loading a plain buffer geometry from json.

**Comment by mrdoob** [comment]
Implemented. Thanks!
