### ISSUE TITLE
Cannot create PolyhedronGeometry or associated geometries

### ISSUE THREAD

**Issue by kylestew** [mrdoob/three.js#6215]
Started seeing some issues when trying to create a basic Tetrahedron. The following will throw an issue on execution:

    THREE.TetrahedronGeometry(1);

Debugging in console points to this line: https://github.com/mrdoob/three.js/blob/master/src/extras/geometries/PolyhedronGeometry.js#L89

I tried also to create PolyhedronGeometry using the technique in some of the other geometries. No luck there either. https://github.com/mrdoob/three.js/blob/master/src/extras/geometries/IcosahedronGeometry.js

Am I missing a needed include outside the core library?

**Comment by WestLangley** [comment]
Include the `new` keyword.

	var geometry = new THREE.TetrahedronGeometry( 1 );

**Comment by kylestew** [comment]
Thanks
Well I feel dumb, sorry to waste time.
