### ISSUE TITLE
Euler prototype

### ISSUE THREAD

**Issue by nebeleh** [mrdoob/three.js#6222]
What does `get x` and `set x` mean in Euler.js? e.g.

https://github.com/mrdoob/three.js/blob/master/src/math/Euler.js#L32

Shouldn't it be `getX: function(value)`?

I do have some problems changing the rotation values in the camera, as sometimes calling up the `camera.rotation.set(0, 0, 0)` doesn't change the actual values.

**Comment by mrdoob** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

**Comment by nebeleh** [comment]
The issue is related to controllers. When you assign a controller to a camera, it constantly updates the `lookAt` function, e.g:

https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TrackballControls.js#L329

hence it won't be possible to update the camera rotation values manually. I guess it is possible to define a new camera, assign the desired rotation values to it, and then bind a new controller to it, but is there a better solution?
