### ISSUE TITLE
Why use obj file split function in split_obj.py, the material information has been lost.

### ISSUE THREAD

**Issue by omni360** [mrdoob/three.js#6227]
@mrdoob @alteredq 

when I use obj file split function , the material information has been lost in the prefex_xxx.obj.

Thanks.

**Comment by mrdoob** [comment]
Sorry, these scripts are unmaintained and about to be deprecated...

**Comment by donmccurdy** [comment]
split_obj.py no longer exists, so closing this issue. Assuming this was for splitting multi-material meshes, GLTFExporter should be able to support that soon-ish hopefully.
