### ISSUE TITLE
Matrix4.prototype.decompose() fails when not given parameters

### ISSUE THREAD

**Issue by Densaugeo** [mrdoob/three.js#6229]
```
var mat = new THREE.Matrix4();
mat.decompose();
// Returns 'TypeError: c is undefined'
```

According to documentation at http://threejs.org/docs/#Reference/Math/Matrix4 'If parameters are not passed, new instances will be created.', but that doesn't seem to be happening.

**Comment by mrdoob** [comment]
I think you should have a quick read at [the code itself](https://github.com/mrdoob/three.js/blob/master/src/math/Matrix4.js#L855-L908) to understand how to `decompose()` works.

**Comment by WestLangley** [comment]
The docs do say

 > If parameters are not passed, new instances will be created

That is not true.

**Comment by mrdoob** [comment]
Fixed. Thanks!
