### ISSUE TITLE
respect THREE.RepeatWrapping in ShaderMaterial please

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6234]
ok, so far this did not cause much inconvenience, I just used fract(uv). but today I have runned into [this issue](http://stackoverflow.com/a/13448369/2207790) with mipmaps and had to disable them because of artifacts. is there anything in particular preventing ShaderMaterial-s from respecting textures' wrapS/wrapT, apart from it being not implemented?

**Comment by makc** [comment]
waaait, I think I know why it did not work, it was probably because of [this](https://github.com/mrdoob/three.js/blob/a72347515fa34e892f7a9bfa66a34fdc0df55954/src/renderers/WebGLRenderer.js#L5672) check :shit:

**Comment by mrdoob** [comment]
You should consider waiting 10 minutes after writing a new issue before sending it ;)

**Comment by makc** [comment]
I do not remember the [warnings](https://github.com/mrdoob/three.js/blob/a72347515fa34e892f7a9bfa66a34fdc0df55954/src/renderers/WebGLRenderer.js#L5687) that must have been there. If I remembered them, I would not create the issue. All I remember is that I use fract because wrapS/T did not work. So that means I should consider working on my memory.
