### ISSUE TITLE
WebGLRenderer warns with an 'undefined' when texture has no sourceFile

### ISSUE THREAD

**Issue by redsolarmoon** [mrdoob/three.js#6236]
This happens with webgl_interactive_cubes_gpu example...
https://github.com/mrdoob/three.js/blob/dev/examples/webgl_interactive_cubes_gpu.html

Warning is triggered at...
https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L5456

When a texture.sourceFile is not specified, this returns an undefined to the console. Suggestion...

```javascript
THREE.warn( 'THREE.WebGLRenderer: Texture is not power of two. Texture.minFilter should be set to THREE.NearestFilter or THREE.LinearFilter.' +
	( texture.sourceFile !== undefined ? ' ( ' + texture.sourceFile + ' )' : '' ) );
```
An alternative to shortening it up?
```javascript
THREE.warn( 'THREE.WebGLRenderer: Texture is not power of two. Texture.minFilter should be set to THREE.NearestFilter or THREE.LinearFilter. ( ' + ( texture.sourceFile || '' ) + ' )' );
```

This also applies to line...
https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L5447

Any suggestions on what message to show otherwise (when 'undefined'), or is leaving it blank fine as shown?

**Comment by mrdoob** [comment]
Maybe `THREE.Texture` should have a `sourceFile` property set to `''` by default.

**Comment by redsolarmoon** [comment]
Your suggestion is good. Some thoughts on it...

Source folder wise, there is very little referring to sourceFile. So, I don't see an issue there in double-checking the code to make sure the change is ok.

There's also may be some code outside of the source folder that will need to be verified. This is just a matter of running the code to make sure. This such as the editor, examples, etc.

Finally, there's no way to tell how other people are handling this property in their own custom code. If they're checking for undefined, setting it to '' by default would invalidate their conditional check. My guess is that this may not be a huge concern and could be little impact?

**Comment by mrdoob** [comment]
The fact that the property is added to the object dynamically is not good practice anyway...

**Comment by redsolarmoon** [comment]
Even if it weren't added dynamically, the warning message would still report undefined since the property was never added. Maybe just leave out the reporting of the sourceFile from the warning message altogether?

**Comment by mrdoob** [comment]
> Even if it weren't added dynamically, the warning message would still report undefined since the property was never added.

It should have been! ;)

**Comment by mrdoob** [comment]
Should be fixed now. Thanks!
