### ISSUE TITLE
Three.js crash when used in desktop OpenGL env

### ISSUE THREAD

**Issue by kabbi** [mrdoob/three.js#6239]
Hello,

I'm using three.js to build a desktop 3D app. The technology stack is node.js + node-webgl + modified three.js.

The problem is that node-webgl wraps ordinary opengl, and three.js is implemented to use webgl (OGL ES 2.0?), and so there were some problems. Here is the document, describing differences: https://www.khronos.org/webgl/wiki_1_15/index.php/WebGL_and_OpenGL_Differences. I've got the basic rendering ok, and when I try to render some simple triangle mesh (128 triangles and vertices) that I've parsed myself, it renders ok. And when I try to add a color map with MeshBasicMaterial, it crashes in opengl code at gleRunVertexSubmitImmediate with null pointer deref. This place corresponds to this line in three js source: https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L3009.

I will be very grateful if anyone has any idea about how to fix that.
Sorry for possible off-topic.

**Comment by mrdoob** [comment]
Sounds like it is more of an issue with node-webgl itself?

**Comment by kabbi** [comment]
Don't think so. Node-webgl is just a wrapper around opengl calls (through glut, see [this](https://github.com/mikeseven/node-webgl/blob/master/src/webgl.cc#L858)). I think the reason is of the differents of desktop ogl and webgl.
And googling says null pointer crash can be because of bad format of data in the buffers to draw, or due to absence of some state-specific flags or data.

**Comment by mrdoob** [comment]
Ah, I see... Unfortunately I can't guess what could be happening and there is no easy way to reproduce...

**Comment by Baccanno** [comment]
May be try https://github.com/nwjs/nw.js/

I managed to build a functional desktop app thks to that.

**Comment by kabbi** [comment]
Node-webkit is cool, but I want to have a 3D app without all the webkit overhead. I think it's too bad, to drag all these dependencies just to make a surface to draw onto.
Plus node-webgl adds full desktop OpenGL support, with any level of programmer control. I think it may be pretty useful.
Anyway, thank you for suggestion.

**Comment by Baccanno** [comment]
Yeah you're probably right, I'm using it because my UI layer is HTML5 based and I want to access other websites sometimes like social login for instance. Anyway for your issue I can't help : /

**Comment by kabbi** [comment]
Sorry, fixed that myself. The issue was in absence of UVs - when the geometry object has no UVs assigned, and material has any texture map, the engine crashes.

**Comment by mrdoob** [comment]
> I will publish my changes when I'll fix everything out, so that you can also try to run three.js as a desktop app.
Thanks!
