### ISSUE TITLE
Same code has memory leaks on r71

### ISSUE THREAD

**Issue by ageblade** [mrdoob/three.js#6250]
Hi all,

I have just upgraded from r70 to r71 and I'm experiencing some serious memory leaks.

I cannot post my exact code here but in my case I load thousands of textures using ImageUtils and render them using render-to-texture method with a new scene and a new camera to an existing texture. after rendering I remove the used mesh from the scene and dispose the temporary geometry, material and texture.

The code worked great on r70 but after upgrading to r71 my chrome instance memory goes crazy high and crash.

Worth checking this out. Until then I'm staying with r70.

**Comment by titansoftime** [comment]
@ageblade They are going to ask you for an example.

**Comment by WestLangley** [comment]
Can you provide a minimal test case, along with the information requested in "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md)?

**Comment by mrdoob** [comment]
Yeah, unless you can share a test case where we can reproduce the issue locally is hard for us to know what may be happening. Hope you can find some spare time to set something up.

**Comment by ageblade** [comment]
I'm working on a jsfiddle so we can try to reproduce it

**Comment by dubejf** [comment]
I bet that's the cache issue. #6834
