### ISSUE TITLE
r71 seemed to mess with trackballcontrols

### ISSUE THREAD

**Issue by johnlauer** [mrdoob/three.js#6256]
I've been using threejs as the core for chilipeppr.com for about 9 months now. It's hugely popular and amazing, so thank you. On Monday the r71 seemed to change the way the trackballcontrols allow for a rotation in the viewer but this seems to only effect Windows, not Mac? What do I need to do to get the display to be able to rotate nicely again? A full swipe of the mouse across the screen seems to only rotate a few degrees whereas before r71 a full swipe would maybe give you 360 degrees or more.

**Comment by WestLangley** [comment]
See if the discussion in #6123 sheds any light on the matter.

/ping @daron1337

**Comment by daron1337** [comment]
I tested it on OSX 10.0 and under windows7 and I can't feel any difference. 
I would be surprised if opposite, there's no difference between the two OS which can interact with the trackballControls.
Regarding the difference of rotation speed, as suggested see #6123

**Comment by johnlauer** [comment]
I somewhat fixed it by doing what was suggested in #6123 but the old behavior really was smoother and more consistent.

`document.addEventListener( 'mousemove', controls.update.bind( controls ), false );
document.addEventListener( 'touchmove', controls.update.bind( controls ), false );`

I'm seeing that the touchmove is still slow even with the addition above. The mousemove is back to a decent speed but its no longer smooth like before and the damping seems to not really work anymore.

Maybe the reason I'm seeing a difference on Windows vs Mac is that I'm on a retina-like display on a Windows 8.1 laptop? The mac is a normal resolution.

**Comment by daron1337** [comment]
> the old behavior really was smoother and more consistent.
As we discussed previously, it is subjective and driven by the habit of the user.
More consistent? With what? please explain yourself.

>Maybe the reason I'm seeing a difference on Windows vs Mac is that I'm on a retina-like display on a Windows 8.1 laptop? The mac is a normal resolution.

I noticed some problems on retina-like displays under windows because windows it is not able to adapt resolution as OSX does, not only in threejs but also sometimes on css temolates etc. For example, try to run a windows virtual machine under an OSX with retina, everything will be doubled with pixels.
each user interface widget is doubled in width and height to compensate for the smaller pixels (  HiDPI ).

**Comment by WestLangley** [comment]
@johnlauer Can you provide a link to a simple test case so we can see exactly what you are doing, along with the information requested in "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md)?

**Comment by pailhead** [comment]
Heya, i've had some issues with this on windows 8 with a gaming mouse. The mousemove handler fires many times before the update and seems to feed the wrong mouse values. The orbit would happen by only a fraction.

Forcing update on every mouse tick seems to fix the behaviour.

**Comment by MasterJames** [comment]
I wondered if your using Chrome vs say Firefox. My (limited) experience is Firefox doesn't fire mouse events as quickly as chrome. Anyway I thought it might be worth noting or checking this issue against different browsers.
