### ISSUE TITLE
strange behavior ThreeJS 71

### ISSUE THREAD

**Issue by Maslik78** [mrdoob/three.js#6258]
Hi, I upgraded from version 69 to 71, and in my render ceased to draw all geometry, while there are no errors in the render. I videotaped the strange behavior of the render.
http://youtu.be/eAemyHOCiWM.
Please tell me what to do? Maybe I'm missing something?

**Comment by bhouston** [comment]
Could you share the scene so we can reproduce?

**Comment by Maslik78** [comment]
All I've found the cause. The fact that I used the object identifiers for their own purposes, and recorded the information I needed. A new version identifier 71 all become read-only. Of course I broke all the logic operation. The question is solved, thank you all for your attention.
