### ISSUE TITLE
Point to point measurement?

### ISSUE THREAD

**Issue by anagpuyol** [mrdoob/three.js#6265]
Hi! 

I'm trying to create an interface where you can measure from point to point in a three.js model. Has anyone done this before?

Thanks!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
