### ISSUE TITLE
depthFunc per material

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#6266]
I've searched the whole repository for "depthFunc" and all i could find is that it's set once as the default state by the renderer, to LEQUAL. 

I would like to change the depthFunc when certain things are being drawn. Materials allow for the blending function to be changed, and toggle both depth writes and depth tests. It would be useful if the depthFunc could be set here as well. 

It doesn't seem like it's too hard to implement this.

Any thoughts?

**Comment by bhouston** [comment]
Sounds like a decent idea.  I'd suggest creating a PR.

**Comment by pailhead** [comment]
We should have something like THREE.SomeDepthFunction map to gl.SOMECONST, along the lines blending is being handled right now?

I can take a stab at this.

**Comment by bhouston** [comment]
This makes sense.  It seems like a straight forward extension.

**Comment by pailhead** [comment]
ok i think i got it, it didnt break anything just need to come up with a sensible example other than why not to use gl.EQUAL and how nasty floating point precision can be :)

**Comment by mrdoob** [comment]
All this sounds good to me ^^

**Comment by pailhead** [comment]
i'm not sure what happened here, i think i accidentally made a pull with no examples, is this the same thing now?

**Comment by mrdoob** [comment]
@pailhead I may have missed/forgotten about it... what was the PR number?

**Comment by pailhead** [comment]
not sure, lol, i forked, and tried to make a pull a couple of weeks ago, i'm new to source control, this seems different i did a chain of if else ifs instead of the switch, but basically the same thing.

**Comment by mrdoob** [comment]
Yeah, after you fork and do the commits you have to do a PR.
Anyway, it got implemented in the end. Thanks!
