### ISSUE TITLE
editor 'camera' examples and the camera helper

### ISSUE THREAD

**Issue by jeromeetienne** [mrdoob/three.js#6268]
in the editor, when i load the 'camera' example i obtain this screenshot. I was thinking the camera helper should be the other way around no ?
![screen shot 2015-03-20 at 12 33 00](https://cloud.githubusercontent.com/assets/252962/6750705/728c37e4-cefd-11e4-9843-5f2cf7b965ac.png)

**Comment by mrdoob** [comment]
Hmmm... Yeah, it used to be like that, but after adding VR support to the editor I had to do some hacks. I'll take a look at it ASAP.
