### ISSUE TITLE
Not well-formed message in the Firefox console by using the OBJMTLLoader

### ISSUE THREAD

**Issue by mmatthies** [mrdoob/three.js#6272]
Hi,

in Firefox I have these annoying messages in the console 'not well-formed' if the OBJMTLLoader loads some mtl files. After some research I found out that the reason for this message the missing responseType by invoking the XHR is. Mtl files are simple text files. Right? If in the XHRLoader the responseType is not set (undefined) the error message appears.

Please change the MTLLoader, the OBJMTLLoader so that the responseType can be passed as parameter and can be honoured from the XHRLoader.

Thanks a lot.

**Comment by mrdoob** [comment]
Do you mind doing a PR with the fix?

**Comment by mmatthies** [comment]
Hi, 
sorry for the late answer.
I don't  understand what do you mean....should I create a PR?

**Comment by mrdoob** [comment]
Yes please :)
