### ISSUE TITLE
Blender exporter: "Operator bpy.ops.object.mode_set.poll() failed, context is incorrect"

### ISSUE THREAD

**Issue by SimoneGianni** [mrdoob/three.js#6276]
I'm using the exporter (version 1 4 0) from Blender (OSX, Version 2.72b, 2014-Oct-21, Blender), and this model (1312 vertices 1086 faces) always exported correctly. I'm exporting as a scene, without lights or materials. There is no animation.

Then I added four simple planes, and suddenly the exporter stopped working, and started giving this error:

Traceback (most recent call last):
  File "/Applications/blender.app/Contents/Resources/2.72/scripts/addons/io_three/**init**.py", line 724, in execute
    exporter.export_scene(filepath, settings)
  File "/Applications/blender.app/Contents/Resources/2.72/scripts/addons/io_three/exporter/**init**.py", line 19, in inner
    func(filepath, options, _args, *_kwargs)
  File "/Applications/blender.app/Contents/Resources/2.72/scripts/addons/io_three/exporter/**init**.py", line 50, in export_scene
    scene_.parse()
  File "/Applications/blender.app/Contents/Resources/2.72/scripts/addons/io_three/exporter/scene.py", line 97, in parse
    self._parse_geometries()
  File "/Applications/blender.app/Contents/Resources/2.72/scripts/addons/io_three/exporter/scene.py", line 176, in _parse_geometries
    api.object.prep_meshes(self.options)
  File "/Applications/blender.app/Contents/Resources/2.72/scripts/addons/io_three/exporter/api/object.py", line 455, in prep_meshes
    mesh_node = extract_mesh(obj, options, recalculate=True)
  File "/Applications/blender.app/Contents/Resources/2.72/scripts/addons/io_three/exporter/api/object.py", line 370, in extract_mesh
    bpy.ops.object.mode_set(mode='EDIT')
  File "/Applications/blender.app/Contents/MacOS/../Resources/2.72/scripts/modules/bpy/ops.py", line 188, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect

I closed and reopened blender, I tried removing those planes and re-exporting, but still the same error, so i'm stuck.

In the model there are some modifiers, namely 3 meshes have "mirror" modifier and other 2 have "solidify" modifier, if this can help. I checked all the objects in the model for spurious "Triangulate" modifiers left-off by previous exports, but none.

What can I do?

**Comment by repsac** [comment]
This happens for one of 2 reasons:
1. the object is not visible in the scene
2. the object is in a different scene

The export tries to ignore visible objects so it seems doubtful that there is a hidden object getting picked up. It does seem more likely that you have a second scene in your Blender session that objects are getting picked up from.

The modifiers should not be an issue. These are applied at export time. Where the error is occurring is in the code block that recalculates normals, which is needed especially for those using mirror modifiers.

You can test this branch and see if it works https://github.com/repsac/three.js/tree/6276

If it is indeed an object in a different scene there will be more work needed to filter objects based on scene context.

**Comment by SimoneGianni** [comment]
Hi @repsac , thanks for having a look to this.

I don't have other scenes in my file, it's only one scene.

However, you mentioned the export is doing something with invisible objects when it get to this error, so I checked the various meshes and in fact I had put one to invisible and forgot about it. I flipped it back to visible, and it worked.

So your diagnosis was right : it has some problems trying to ignore invisible objects. 

I mentioned the modifiers because it already happened a few times that I received error because of them. If for example you launch the export when you are in edit mode instead than in object mode, and you have modifiers, it will give error saying that it can't apply the modifier while in edit mode. In this case, some times I found the "triangulate" modifier set on a number of meshes. I suppose, but have no knowledge of the code and I'm not a blender expert, that the triangulate modifier is used during export to reduce all the faces into triangles, and should be then cleaned-up when the export is done, but if it goes in error in that part it does not cleanup.

Thanks for pointing me in the right direction!

**Comment by repsac** [comment]
I will have to double check because invisible objects should be skipped so this shouldn't have been an issue.

The exporter only goes into EDIT mode to recalculate normals and this is only on a temporary mesh. Each object has its mesh flattened out to a temporary mesh node (with modifiers applied). This temporary mesh node is what has the normals recalculated on and that is the node that is parsed for the JSON. 

The exporter will [forcefully triangulate](https://github.com/mrdoob/three.js/blob/master/utils/exporters/blender/addons/io_three/exporter/api/object.py#L344) your mesh if exporting to BufferGeometry format. I did not do this for Geometry format, but considering how the JSONLoader triangulates a quad anyways then I am considering just apply the triangulate to all mesh nodes.

**Comment by erno** [comment]
I am also seeing this crash.

**Comment by mixaster** [comment]
Can confirm, this error is showing up when object visibility is off. I turn on all objects, and the error went away. Doesn't seem to matter what object I toggle, it only exports if all objects are visible.

**Comment by daarong** [comment]
I am experiencing this problem with Blender 2.76b and latest exporter v1.5.0.

Luckily it seems strictly related to whether I have any meshes set to invisible.

**Comment by kevinw** [comment]
Experiencing this problem as well with invisible objects.

**Comment by evbarnett** [comment]
I too am experiencing a similar problem with Blender 2.77a. Making the object visible fixed it.

**Comment by wouldntsavezion** [comment]
Same here, this is a 2015 issue. 

Using blender 2.78a and exporter 1.5.0.

**Comment by mese79** [comment]
I guess i've found the solution. see [PR#11645](https://github.com/mrdoob/three.js/pull/11645)
