### ISSUE TITLE
4 sided polygon loaded incorrectly

### ISSUE THREAD

**Issue by aliweed** [mrdoob/three.js#6277]
I have  a model in Blender with a 4 sided polygon. When I export to JSON and load it in threejs, a Face3 object is created instead of a Face4.

I know I can split my polygon into 3 3-sided polygons. This isn't ideal though.

Any ideas on how I can change from Face3 to Face4?

**Comment by makc** [comment]
By switching to three.js version from before July 2013, when Face4 was basically [removed](https://github.com/mrdoob/three.js/commit/a356e4dc8d36c5f5579c4653c2ddde3a80359882).

**Comment by aliweed** [comment]
Oh, so my fallback was adding that face by hand ie. creating a Face4 object myself. Now I guess I can't even do that.

I don't like the sound of changing to an older version. Won't I lose some other functionality?

**Comment by makc** [comment]
Oh no, not at all. Removing Face4 is the only thing that happened since 2013.

**Comment by QuaziKb** [comment]
in case you didn't get that as sarcasm, you'll likely lose a lot of subtle things. What's the reason you need quads so badly?

**Comment by aliweed** [comment]
No, I just thought that was his opinion. I looked through the commits and thought... nah, I'm not comfortable throwing all that stuff away.

Anyway, I have some models which someone built a long time ago which have 4-sided polygons. When I import them into threejs, it totally screws them up. I've tried splitting them up in blender and re-importing and that just makes things even worse. threejs ends up creating faces from apparently random vertices.

Not quite sure what I'm going to do next. I don't want to spend money on having new models created - Is it not normal to have 4-sided polygons?

In another situation, I require a simple 4 sided polygon, which the user can click on to change the color. In threejs, I have to split it into 3 triangular faces and group them all to behave as one. But theres some sort of bug, I think in the Blender export to JSON. When I split the faces, while they look fine in Blender (and I am NO expert), threejs ends up making faces out of the wrong vertices.

**Comment by mrdoob** [comment]
> Anyway, I have some models which someone built a long time ago which have 4-sided polygons. When I import them into threejs, it totally screws them up. 

Can you share those files? Maybe screenshots? What exporting are you using? How are you loading them? etc
