### ISSUE TITLE
question about the future of the renderer and its plugins

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6280]
Rant

> This week I needed to add animated 2d circles to one project, and I thought - okay, I will just write ShaderMaterial with some sine wave = f(time). But then it turned out I could not apply it to sprites. I came up with this [patch](http://jsdo.it/makc/cozIcan) but, what if I ever need two+ sprite materials? I can no longer do that without repeating all the steps that are locked in webgl renderer atm. Well, maybe I could switch to planes and rotate them to face the camera manually, ok. But ideally, I should have the sprites that only differ from planes in that they use different vertex shader, no?
> 
> If there to be these renderer plugin things, there should be one for every object there is in 3js, and they all should have some common means to work with materials, track (un)used uniforms, etc. Either way, don't you think webgl renderer could use some surgery to split the guts? Remember, in #6117 we could not change 2 lines in the shader without breaking other stuff? For no other reason that it is all so tightly coupled.
> 
> Finally, the main reason  for this rant is basically that I can't swallow and digest a piece of code that big.

/Rant

So the question is, does anyone has a plan for the future. Or, the strategy is to tackle one issue at a time, and let the renderer grow indefinitely?

**Comment by QuaziKb** [comment]
instead of making planes rotate to face the camera, you could make the vertex shader perhaps not transform the planes except for their position in the first place?

**Comment by makc** [comment]
Yes, that is an option, but then how come sprites are not implemented like that

**Comment by mrdoob** [comment]
> So the question is, does anyone has a plan for the future. Or, the strategy is to tackle one issue at a time, and let the renderer grow indefinitely?

I've been slowly modularising the renderer over the last few months: [WebGLExtensions](https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/WebGLExtensions.js), [WebGLProgram](https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/WebGLProgram.js), [WebGLShader](https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/WebGLShader.js), [WebGLState](https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/WebGLState.js), ... All that code used to be inside `WebGLRenderer`.

The hope is that end up with something more manageable and easy to tweak.
