### ISSUE TITLE
Skinned animation "fps" and "length" have vague relationship

### ISSUE THREAD

**Issue by QuaziKb** [mrdoob/three.js#6281]
It's unclear how the exported "fps" and "length" properties in animation data are related. from what i can tell the "fps" setting is completely ignored so I can't figure out if length is referring to the exported "number of frames", or the "length the animation is supposed to last" in seconds. If it is the "number of frames" then of course fps has a meaning, however, if it is the length in seconds, fps is redundant.

It'd be nice if the documentation explained this somewhere, since it's a bit vague, and from my tests with the packaged models, using the fps value assuming length refers to frames gives an animation that's far too fast.

having both seems kind of redundant but the exporter is creating them for some good reason im sure

**Comment by mrdoob** [comment]
It may be dead code too...

**Comment by Mugen87** [comment]
This issue relates to the previous animation system and can be closed now.
