### ISSUE TITLE
BufferGeometry.computeBoundingSphere does not respect itemSize

### ISSUE THREAD

**Issue by mattdesl** [mrdoob/three.js#6288]
For geometries with vec2 positions, the computeBoundingSphere will not work correctly since it always assumes vec3s.

https://github.com/mrdoob/three.js/blob/f73593b00e3b2c927bb1a3236240cea5597166ec/src/core/BufferGeometry.js#L327-L332

**Comment by httpdigest** [comment]
I second this. And I would flag this as "Bug" instead of "Enhancement."
When only using 2D positions, the implicitly called THREE.Frustum.intersectsObject and its called THREE.BufferGeometry.computeBoundingSphere fails/crashes.
It should of course be possible for THREE.Frustum.intersectsObject to check whether a 2D object intersects a frustum or not to still support frustum culling for 2D objects.
Currently, I have a 2D application with an isometric/orthographic view.

**Comment by mrdoob** [comment]
Sounds good to me! Anyone want to prepare a PR?

**Comment by rock7-dan** [comment]
PR #8510

**Comment by WestLangley** [comment]
>For geometries with vec2 positions

I believe there is a fundamental assumption in the library that geometry positions are `Vector3`. I do not think we want to assume otherwise.

`two.js` maybe.

**Comment by bicubic** [comment]
@WestLangley what about vec4 positions containing 3d coords representing a valid bounding sphere? I don't think its desirable to have computeBoundingSphere assuming that `position` has a stride of 3 while the library permits users to create geometries where `position` can be arbitrary. I'm happy to do a PR for this if you guys have ideas for how to handle it.

**Comment by WestLangley** [comment]
@bicubic If @mrdoob wants to support the creation of geometries or position arrays in other dimensions, it should be supported for every method in the library. As I said, I do not think we should go down that path, but I will defer to @mrdoob.

**Comment by mrdoob** [comment]
Yeah... At this point, I think it's better to let the user compute the boundingSphere on their own in these cases...

**Comment by LeviPesin** [comment]
I think the user should just create another attribute, like `position2` or `position4`, if they want to use non-vec3 positions.

**Comment by ooatom** [comment]
> I think the user should just create another attribute, like `position2` or `position4`, if they want to use non-vec3 positions.

but then frustum culling would not work unless creating a new type extends Mesh or sth with a new computeXXX method... not quite handy

**Comment by Mugen87** [comment]
Sorry, but fully support of two-dimensional vertex values in the engine is out of scope.
