### ISSUE TITLE
Blender exporter UV mapping fault

### ISSUE THREAD

**Issue by snovak** [mrdoob/three.js#6292]
I'm experiencing an issue where it appears as if the UVs are offset using the Blender exporter.  Is anyone else experiencing this?

Things I've tried to remedy the issue:
* I've downloaded dev and I'm using the exporter from there.  
* I've updated Blender as well, and I'm experiencing the same issue.  
* I've also exported the same object in OBJ format, imported that, and see I have the CORRECT UVs, where the normal map looks fine. 
* the same offset occurs if I apply the same image to Color channel.
* I've applied all modifiers in Blender before exporting. 

I'm only working in the browser editor in this case.  I'm not sure if it would help to try writing a script to load the model that way.  But, I can't readily see how that would make a difference.  

I'm on a MacBook Pro (Retina, Mid 2012)

![uvmappingoffset](https://cloud.githubusercontent.com/assets/317561/6831448/b34bc5cc-d2f6-11e4-8342-f8800859c0b6.jpg)

**Comment by snovak** [comment]
Here is the same model, exported as OBJ.  Then, imported into the editor. 
![uvmappingoffsetobj](https://cloud.githubusercontent.com/assets/317561/6832211/63e4b502-d2fb-11e4-8a26-14705c7a1bca.jpg)

**Comment by snovak** [comment]
Let me know if you need anything..

**Comment by snovak** [comment]
Here's the model I'm using. https://drive.google.com/file/d/0BylWSQgB6Sw0cGEwUE5GU1NtNU0/view?usp=sharing

**Comment by repsac** [comment]
Downloaded the file. I am also going to create some simpler tests to recreate it.

**Comment by repsac** [comment]
OK. So I took a look at your file. The UVs are indeed cleanly laid out.
![screen shot 2015-03-26 at 7 19 59 pm](https://cloud.githubusercontent.com/assets/1109289/6861137/7fdaa2be-d3ee-11e4-8112-30bee1731ddb.png)

Looking a bit further I see that the active UV layer is the second UV layer.
![screen shot 2015-03-26 at 7 20 14 pm](https://cloud.githubusercontent.com/assets/1109289/6861139/89aee98a-d3ee-11e4-91f8-2c886f982e83.png)

So I took at look at layer 1 and:
![screen shot 2015-03-26 at 7 20 40 pm](https://cloud.githubusercontent.com/assets/1109289/6861146/9a74a124-d3ee-11e4-8689-f05b24cc2aaf.png)

It seems the maps are getting assigned to this. The exporter will pickup all layers but I think your maps are supposed to be linked to the first layer (I believe the second was for light maps). I think... will need another guru to weigh in here.

When I deleted that bad layer and exported I got UVs that matched in both Blender and the Editor.
![screen shot 2015-03-26 at 7 18 28 pm](https://cloud.githubusercontent.com/assets/1109289/6861151/bef534d2-d3ee-11e4-9d65-410de7f1954d.png)
![screen shot 2015-03-26 at 7 18 40 pm](https://cloud.githubusercontent.com/assets/1109289/6861152/c24f311e-d3ee-11e4-851d-010fadf8ad74.png)

And I seem to recall that Blender's OBJ exporter uses the active UV layer which would explain why your UVs are fine with the OBJ.

**Comment by WestLangley** [comment]
> I believe the second was for light maps

Correct. The second set of UVs is for a lightMap.

**Comment by repsac** [comment]
@WestLangley thanks for the clarification. This seems like a scene setup/cleanup issue to me.

**Comment by snovak** [comment]
WAD. User error!  Thanks for putting up with me guys.
