### ISSUE TITLE
Forbidding incorrect mesh creations.

### ISSUE THREAD

**Issue by stavenko** [mrdoob/three.js#6293]
Originally my problem begins when I tryed to put to scene mesh with `THREE.BoxGeometry` and `THREE.MeshFaceMaterial` with two materials.

`THREE.BoxGeometry` creates 6 planes. Each of then has it's own `materialIndex`. Here's the code:

``` javascript
    buildPlane( 'z', 'y', - 1, - 1, depth, height, width_half, 0 ); // px
    buildPlane( 'z', 'y',   1, - 1, depth, height, - width_half, 1 ); // nx
    buildPlane( 'x', 'z',   1,   1, width, depth, height_half, 2 ); // py
    buildPlane( 'x', 'z',   1, - 1, width, depth, - height_half, 3 ); // ny
    buildPlane( 'x', 'y',   1, - 1, width, height, depth_half, 4 ); // pz
    buildPlane( 'x', 'y', - 1, - 1, width, height, - depth_half, 5 ); // nz

    function buildPlane( u, v, udir, vdir, width, height, depth, materialIndex ) {
           //stuff
        }
```

Then, during preparations for rendering, we have function like 

``` javascript
    function bufferGuessUVType( material ) {

        // material must use some texture to require uvs

        if ( material.map ||
                 material.lightMap ||
                 material.bumpMap ||
                 material.normalMap ||
                 material.specularMap ||
                 material instanceof THREE.ShaderMaterial ) {

            return true;

        }

        return false;

    };
```

Here's material is `undefined`, just because in my case there was only one material in `THREE.MeshFaceMaterial`. But, the mesh was created without any warnings. And this happend to kill whole animation loop, instead of silent console message. Furthermore, this problem is very hard to determine, because it needs to be debugged, but `bufferGuessUVType` is called very often.

So, my suggestion is to add some field to the `THREE.Geometry` objects like `expectedMaterials`. This field in the constructor of `THREE.Mesh` (or any other mesh type) will help to determine, is it available or not to create new Mesh. It would be nice, if mesh is not created with incorrect numbers of materials with appropriate error message in browser console.

Or, maybe, there's a function 

``` javascript
function getBufferMaterial( object, geometryGroup ) {

        return object.material instanceof THREE.MeshFaceMaterial
            ? object.material.materials[ geometryGroup.materialIndex ]
            : object.material;

    };

```

It could be better to decide here, which material to choose (with accordingly warnings in console).
What would you say?

**Comment by mrdoob** [comment]
I really really really want to get rid of `MeshFaceMaterial` O:)

**Comment by stavenko** [comment]
Well. I suppose you know the problem better. I'd like to see if there's some discussions on this topic to make it clear how to replace multimaterial meshes?

I can see, that there's a lot of `instanceof`'s in `WebGLRenderer` class,  so the replacement could be a painful thing. Maybe there's some branches, that remastering things somehow?

**Comment by Mugen87** [comment]
`MultiMaterial` (successor of `MeshFaceMaterial`) has been deprecated, see #10931.
Use this pattern instead:
```js
if ( Array.isArray( object.material ) ) {

   // multiple materials

} else {

   // single material

}
```
