### ISSUE TITLE
BohekPass renders to pass specific depth buffer, it should allow for a shared depth buffer

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#6294]
BohekPass renderes to its own depth buffer here:

https://github.com/mrdoob/three.js/blob/master/examples/js/postprocessing/BokehPass.js#L42
https://github.com/mrdoob/three.js/blob/master/examples/js/postprocessing/BokehPass.js#L79

I would suggest that we allow for it to share depth buffers across multiple shaders, like SSAO does:

https://github.com/mrdoob/three.js/blob/master/examples/js/shaders/SSAOShader.js#L19

**Comment by mrdoob** [comment]
:+1:

**Comment by Mugen87** [comment]
Merging into #7668.
