### ISSUE TITLE
Filmic tone mapping

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#6296]
Right now we are only supporting the standard Reinhard tone mapping operator.  This operator is known for reducing the color gammat unnecessarily compared to the Filmic tone mapping operator:

http://filmicgames.com/archives/75

I'd like to add an option to AdaptiveToneMappingPass/ToneMapShader to switch between Reinhard and Filmic (as defined in the above blog post) and potentially others in the future...

/ping @MiiBond - PS. Did you have other changes to integrate before I start refactoring?

**Comment by bhouston** [comment]
I think we also need to add an option to determine whether nor not integrated Gamma correction is done.  Because sometimes people want it and other times people don't.

**Comment by MiiBond** [comment]
Yes, absolutely.
I changed our local version a while ago to use the same filmic tone-mapping method that you linked to but I also have a ton of other messy changes and I don't think I have time to clean up and merge. So, by all means, please go ahead and refactor as much as you'd like.

I was playing around with doing some automatic white-level balancing a few months ago (detecting the brightest luminosity on the screen and feeding that back into the tone-mapping) but didn't really get it to a point that I was happy with. I also played around with manual downsampling of the luminance texture when only OES_texture_float and not OES_texture_float_linear is supported. However, all of this code was messy and should be refactored anyway if it is ever going to make its way back into Three.js so I can do that on top of your refactor.

**Comment by MiiBond** [comment]
Oh, and while you're refactoring...
The version of `AdaptiveToneMappingPass` in Three.js right now still has a line in the adaptive shader that squares the luminance after sampling it. I had found that this gave me better results originally but I've since removed it. You'll probably want to consider removing it as well since it really shouldn't be necessary.

**Comment by bhouston** [comment]
Just noticed that there are a ton of tone mapping operators defined in the deferred renderer:

https://github.com/mrdoob/three.js/blob/master/examples/js/ShaderDeferred.js#L484

**Comment by WestLangley** [comment]
Filmic tone mapping is now supported.
