### ISSUE TITLE
RawShaderMaterial Clone

### ISSUE THREAD

**Issue by jonathanhooker** [mrdoob/three.js#6309]
Hey, I was cloning a RawShaderMaterial and noticed that the clone wasn't working properly. I think that function just needs a quick tweak:

**Current:**

`THREE.RawShaderMaterial.prototype.clone = function () {`
`	var material = new THREE.RawShaderMaterial();`
`	THREE.ShaderMaterial.prototype.clone.call( this, material );`
`	return material;`
`};`

**Updated:**

`THREE.RawShaderMaterial.prototype.clone = function () {`
`	var material = THREE.ShaderMaterial.prototype.clone.call( this );`
`	material.type = 'RawShaderMaterial';`
`	return material;`
`};`

**Comment by jonathanhooker** [comment]
I posted this a bit hastily... there are some issues with my updated code...

**Comment by jonathanhooker** [comment]
Okay, so after looking into this further I think that the issue really isn't with the RawShaderMaterial clone function, but with ShaderMaterial's Clone function. It should be probably be updated to accept a material variable so that it matches THREE.Material's Clone function. So the opening of that function could be updated to:

`THREE.ShaderMaterial.prototype.clone = function ( material ) {`
`	if ( material === undefined ) material = new THREE.ShaderMaterial();`

On a side note I noticed that THREE.UniformsUtils doesn't clone a Matrix3 object, which I was using so I also added that to my local build.

**Comment by mrdoob** [comment]
Fixed. Thanks!

**Comment by WestLangley** [comment]
@mrdoob Don't forget

> On a side note I noticed that THREE.UniformsUtils doesn't clone a Matrix3 object

**Comment by mrdoob** [comment]
Uops!
