### ISSUE TITLE
CSS Renderer issues on blink engine?

### ISSUE THREAD

**Issue by wzr1337** [mrdoob/three.js#6310]
The CSS Renderer does not seem to work properly in all browsers.

In Chrome 41.0.2272.104 (64-bit) the HTML containers positionedwith the cssRenderer are not accepting any styling:
![image](https://cloud.githubusercontent.com/assets/3704301/6905694/1f0ba480-d72a-11e4-8508-4e14e2c31e00.png)

In Safari Version 8.0.4 (10600.4.10.7) the faces of HTML containers are rendered properly (colored)
![image](https://cloud.githubusercontent.com/assets/3704301/6905589/3ed47766-d729-11e4-8735-761ee688645f.png)

You find a code sample here:
http://jsfiddle.net/8r7upLek/1/

**Comment by WestLangley** [comment]
The problem is with your `zIndex` setting.

http://jsfiddle.net/8r7upLek/2/

**Comment by wzr1337** [comment]
ok, got it.. Thanks!
