### ISSUE TITLE
THREE.Triangle Barycentric Coords

### ISSUE THREAD

**Issue by bGute** [mrdoob/three.js#6313]
Why are you using [here](https://github.com/mrdoob/three.js/blob/dev/src/math/Triangle.js#L89) 1-u-v (result.x) instead of u? 
The given equation from [here](http://www.blackpawn.com/texts/pointinpoly/) is using u.

**Comment by mrdoob** [comment]
Uh... /ping @WestLangley ?

**Comment by WestLangley** [comment]
I believe it is an equivalent test. The alternate would be as follows, but I do not believe it is necessary.

	return ( result.y >= 0 ) && ( result.z >= 0 ) && ( ( result.y + result.z ) <= 1 );

/ping @bhouston https://github.com/mrdoob/three.js/pull/2751/files

**Comment by bhouston** [comment]
I'm fairly sure the existing code is right...

**Comment by WestLangley** [comment]
@bGute Can you demonstrate that the current test is equivalent to the test in the original source?

**Comment by bGute** [comment]
I figured it out, it is the same:
Lets say t = 1-u-v, then we have the current test with:
t>=0 && v>=0 && t+v <=1 (eqn:1) and the original with:
u>=0 && v>=0 && u+v<=1 (eqn:2).

To show that they are equivalent we need to insert t in eqn:1 and we get:
1-u-v>=0 && v>=0 && 1-u-v+v<=1
After some simplifications we have:
u+v<=1 && v>=0 && u>=0

So you are right both tests are equivalent.
Well i shoul have done that before asking, but thanks anyway!
