### ISSUE TITLE
EdgesHelper animation issue

### ISSUE THREAD

**Issue by anonym19876** [mrdoob/three.js#6314]
Lines generated by EdgesHelper are rotated as geometry pivot rotates, but the geometry is always a step ahead. So the output is something like this.

goes up:
![img1](https://cloud.githubusercontent.com/assets/11733395/6914485/5c5f3340-d78b-11e4-9812-951127a2d177.png)
![img11](https://cloud.githubusercontent.com/assets/11733395/6914484/5c5f0e9c-d78b-11e4-86bd-1572c0428fd8.png)

goes down:
![img22](https://cloud.githubusercontent.com/assets/11733395/6914491/6d9e9556-d78b-11e4-94d7-36f3ae71870f.png)
![img2](https://cloud.githubusercontent.com/assets/11733395/6914490/6d9a8fa6-d78b-11e4-8d97-efb57a73c85d.png)

Any suggestions? Thank you.
three.js, revision 71
tested on Firefox 35.0.1 and Google Chrome 41.0.2272.101 m

**Comment by mrdoob** [comment]
Make sure you do something like `car.updateMatrixWorld( true )` before creating `EdgesHelper`.
