### ISSUE TITLE
THREE.BackSide make texture inverse

### ISSUE THREAD

**Issue by sapjax** [mrdoob/three.js#6315]
I created a SphereGeometry，and set the camera's position in the center of the sphere.
Then use an image as texture, and set `side : THREE.BackSide`.

The problem is that the texture is  inverse of the origin picture.
for example: the door in the origin picture is at right, but at left look from the camera.
How can i set texture look same as the origin picture and camera is in the center of sphere? 
![3830f005-8ac2-4fc5-a709-9dd43a4f53de](https://cloud.githubusercontent.com/assets/990255/6915451/b4e70f0c-d7c6-11e4-8f7c-d870fc1e70d1.png)

**Comment by mrdoob** [comment]
That's the correct behaviour as the UVs stay the same.

**Comment by sapjax** [comment]
Thanks!
This code works for me:
`ball.geometry.applyMatrix( new THREE.Matrix4().makeScale( -1, 1, 1 ) );`
