### ISSUE TITLE
RenderTarget.generateMipmaps=false is ignored when a render target is initialized.

### ISSUE THREAD

**Issue by wrr** [mrdoob/three.js#6316]
These two lines:
https://github.com/mrdoob/three.js/blob/a14f4b2c578efad3a066638f3be03db2f3f5e7db/src/renderers/WebGLRenderer.js#L4386
https://github.com/mrdoob/three.js/blob/a14f4b2c578efad3a066638f3be03db2f3f5e7db/src/renderers/WebGLRenderer.js#L4427
Generate mipmaps for render targets that have `generateMipmaps` set to `false`. 

The `generateMipmaps` flag is checked only when render targets are updated: 
https://github.com/mrdoob/three.js/blob/a14f4b2c578efad3a066638f3be03db2f3f5e7db/src/renderers/WebGLRenderer.js#L1957

Is this intended or an oversight? It seems that this can unnecessarily increase memory usage. I can send a PR that adds such checks to the `setRenderTarget` function.

**Comment by mrdoob** [comment]
Hmmm... `WebGLRenderer` has been updated quite a bit since your post and your line highlights don't match. Do you mind updating your post with matching line highlights?

**Comment by wrr** [comment]
I changed the links to refer to a specific commit (latest one), so the links will stay valid.

**Comment by mrdoob** [comment]
I think it is an oversight. A PR would be great! 😊
