### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by PaulineStich** [mrdoob/three.js#6317]
Hello, 
I started learning Three.js three months ago.
Everything is ok and works correctly on my local browsers.
So here's the problem: I've got a strange bug I can't solve yet. I hosted the files (who are working nice and smooth on chrome) online on my server, and they are not working anymore. Of course I checked the console and I found out there is a problem with the Projector.js file: " Unexpected end of input". The file hasn't completely loaded.. Seems not normal. What can I do?

(console):
![sans titre-1](https://cloud.githubusercontent.com/assets/11509544/6921860/a5bf74e6-d7c7-11e4-9746-5e8a3bd7b658.jpg)
![problem2](https://cloud.githubusercontent.com/assets/11509544/6921891/d0d03e90-d7c7-11e4-9fc0-a37d0b03c4d0.jpg)

The file I worked on is this one: http://threejs.org/examples/canvas_lines_sphere.html 
!

**Comment by mrdoob** [comment]
Sounds like an issue with your server. Try uploading Projector.js again.
