### ISSUE TITLE
Geometry in Sprite.js is not used

### ISSUE THREAD

**Issue by arodic** [mrdoob/three.js#6319]
I've been trying to use custom geometry for sprites and noticed that it is completely ignored by the renderer. It turns out geometry in [Sprite.js](https://github.com/mrdoob/three.js/blob/dev/src/objects/Sprite.js) is not even used. Instead, [SpritePlugin.js](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/plugins/SpritePlugin.js) geometry is used.

**Comment by mrdoob** [comment]
As far as I can remember it was a hack to get them to play nice in the frustum check.
