### ISSUE TITLE
EdgeHelper position and matrix.

### ISSUE THREAD

**Issue by alphamax** [mrdoob/three.js#6321]
Hello,

It is an humble ticket and i hope i don't loose your precious time.

This ticket is about positioning Edges in the class **THREE.EdgesHelper**. I just ported a previous version of my app to r71 and i was positioning issues. After comparing the two classes, i saw that the last lines of the class setting matrix and not matrixworld. It may be normal:
Actual code :
```javascript
    this.matrix = object.matrixWorld;
    this.matrixAutoUpdate = false;
```
My humble fix :
```javascript
    this.matrixWorld = object.matrixWorld;
    this.matrixAutoUpdate = false;
```

Problem is on an object 3D **O**, previously moved, and containing a mesh **M** and an edge **E**.
If i properly understand, the matrixWorld of **M** is having the position of **M** combined with the position of **O** so the actual code is putting the **E** on a fixed position and if **O** is moved, it will not be properly composed. Am i right ?

**Comment by WestLangley** [comment]
Helpers are designed to be added directly as children of the scene -- not as children of the target object, or any other object.

If you can demonstrate a solution that works in all cases, that would be great.

**Comment by alphamax** [comment]
Ok, that's why it is an helper. In my particular case, i am making a CAD application and the Edge is part of a mobile piece of the app. That's why i don't use it as expected.

As it clearly depend the way you want to use it, i prefer closing the ticket.

**Comment by mrdoob** [comment]
Actually, it probably makes more sense to turn `EdgesHelper` into `EdgesGeometry` like I did with `WireframeHelper` in https://github.com/mrdoob/three.js/commit/b93fe656746dd7a93853a70e9f0cd79e4c17a0d6.

**Comment by alphamax** [comment]
Should be better if everyone use it as a component and not as an helper. I may try to create a request but i am not confident with git (for now...)

**Comment by mrdoob** [comment]
What's a component?

**Comment by alphamax** [comment]
Well, i am from a pure object development world before trying to do JS/3D development. In that point of view, i'm trying to avoid helper phylosophy because it breaks all the lines. On the other side, i have composed a hierarchy in my project where each part of the software (and also each part of the visual tree) has a given role. It is more like a "component" phylosophy.

Kind of :
http://en.wikipedia.org/wiki/Component-based_software_engineering

It is part of my humble rules for organizing my rubbish code :o !

**Comment by WestLangley** [comment]
> It probably makes sense to turn EdgesHelper into EdgesGeometry like I did with WireframeHelper

I like it!

	var geometry = new THREE.EdgesGeometry( mesh.geometry );
	var material = new THREE.LineBasicMaterial( { color: 0xff8000, linewidth: 4 } );
	var edges = new THREE.Line( geometry, material, THREE.LinePieces );
	scene.add( edges );

**Comment by alphamax** [comment]
Thanks :)
