### ISSUE TITLE
AnimationHandler.update() for keyframes

### ISSUE THREAD

**Issue by tmunz** [mrdoob/three.js#6322]
I wanted to use both keyframe animation and bone/skinnedMesh animation in one scene. But when I tryed to use THREE.AnimationHandler.update() in animate, I got an error. But by extending the resetBlendWeights-call with the following if-condition it works fine

``` javascript
if (this.animations[i] instanceof THREE.Animation) {
    this.animations[ i ].resetBlendWeights( );
}
```

Setup: Blender 2.72b Collada exported file; Windows 8.1 Intel HD Graphics 3000 in "all" browsers; Three.js 70 and 71

**Comment by Mugen87** [comment]
`AnimationHandler` is deprecated. Use the latest animation system instead.
