### ISSUE TITLE
Converting large buffer geometry to geometry hangs browser. 

### ISSUE THREAD

**Issue by cmisura** [mrdoob/three.js#6327]
I'm using the `OBJLoader` to load a fairly large `.obj` (~194mb).  Post load I'm attempting to convert the buffer geomtery to geometry, and add it to the scene in a new mesh (coffeescript below):

            onComplete = ( group )  ->
                geometry  = new THREE.Geometry().fromBufferGeometry( group.children[0].geometry )
                material  = new THREE.MeshBasicMaterial( { wireframe: true, color: 0xFFFFFF } )
                mesh = new THREE.Mesh( geometry, material )
                scene.add( mesh )

Not sure if this is an issue or the  `.obj` is just too large to translate back to geometry? If I just load the model without using `fromBufferGeometry` it works fine. 

    onComplete = ( group )  ->
        group.position.set( 0, -window.innerHeight, 1000 )
        scene.add( group )

**Comment by makc** [comment]
why not just use buffer geometry?

**Comment by m1ga** [comment]
I have a 108MB DAE and it loads fine but as soon as I reload the browser I run into memory problems (or the mesh doesn't appear). Closing the browser and reopen it helps. Perhaps it somehow related.

**Comment by mrdoob** [comment]
Why do you need to convert it to `Geometry`?

**Comment by titansoftime** [comment]
>I have a 108MB DAE and it loads fine but as soon as I reload the browser I run into memory problems (or the mesh doesn't appear). Closing the browser and reopen it helps. Perhaps it somehow related.

@m1ga 

I have been complaining to chromium about this for over a year now. For some reason when you refresh, the gpu memory is not released. Sometimes even the tab process memory is not released. I believe this is a browser bug. A super annoying one.

**Comment by cmisura** [comment]
Honestly, I'm not sure I need to convert it. It's an architectural visualization of a condominium - exported from 3D Max - and I'm investigating methods for selecting individual floors. I thought that by converting it to `Geometry` it would simplify the process.

**Comment by cmisura** [comment]
@m1ga I'm also running into memory problems or reload - even when the model loads and is rendered.

**Comment by mrdoob** [comment]
Basically... if you're dealing with big/complex geometries you should avoid using `Geometry` 😊

**Comment by cmisura** [comment]
@mrdoob ok, good to know - thanks for your help.
