### ISSUE TITLE
PointerLockControls

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#6338]
I've rewrite this piece of code in order to get a very smooth motion.
You can see the result here:
http://necromanthus.com/Test/html5/test8.html 
See the "MouseLook" routine.
The approach is tricky, but it gives the best results.
Feel free to update PointerLockControls.js if you like.

cheers

**Comment by mrdoob** [comment]
```javascript
MouseLook = function () {
	var scope = this;
	var pitObj = new THREE.Object3D();
	var yawObj = new THREE.Object3D();
	yawObj.add( pitObj );
	var maxPit = 75*(Math.PI / 180);
	var oldmovX = 0;
	var oldmovY = 0;
	var onMouseMove = function ( event ) {
		if ( scope.enabled === false ) return;
		var movementX = event.movementX || event.mozMovementX || event.webkitMovementX || 0;
		var movementY = event.movementY || event.mozMovementY || event.webkitMovementY || 0;
		event.preventDefault();
		event.stopPropagation();
		oldmovX = (oldmovX + movementX) / 2;
		oldmovY = (oldmovY + movementY) / 2;
	};
	document.addEventListener( 'mousemove', onMouseMove, false );
	this.enabled = false;
	this.rotCam = function() {
		yawObj.rotation.y -= oldmovX * 0.0025;
		pitObj.rotation.x -= oldmovY * 0.0025;
		pitObj.rotation.x = Math.max( - maxPit, Math.min( maxPit, pitObj.rotation.x ) );
		oldmovX = 0.75 * oldmovX;
		oldmovY = 0.75 * oldmovY;
	};
	this.getObject = function () {
		return yawObj;
	};
	this.getObject2 = function () {
		return pitObj;
	};
};
```

**Comment by RemusMar** [comment]
Yes, that's the MousLook routine.
And here is the access to taht routine:

function animate() {
			requestAnimationFrame( animate );
			var delta = clock.getDelta();
 // ...
			mslook.rotCam();
			camera.position.copy( mslook.getObject().position );
			camera.rotation.x = mslook.getObject2().rotation.x;
			camera.rotation.y = mslook.getObject().rotation.y;
 // ...
			THREE.AnimationHandler.update( delta );
			renderer.render( scene, camera );
}

So the camera is not a child oblect anymore
