### ISSUE TITLE
Document removal of .sortParticles field from PointCloud

### ISSUE THREAD

**Issue by randombk** [mrdoob/three.js#6341]
PointCloud.sortParticles was removed between r69 and r70, but the change is not documented in the tag description or the migration guide.

**Comment by antont** [comment]
in a previous case i was encouraged to just add a note to the migration wiki page myself .. so if you know what that is about, AFAIK you could add the info there.

**Comment by looeee** [comment]
@mrdoob PointCloud has been removed, can this be closed? Or should a reference to this removal be added to the deprecated list?
