### ISSUE TITLE
floor reflection

### ISSUE THREAD

**Issue by mese79** [mrdoob/three.js#6351]
Hi
I know this is a question, but it seems stackoverflow closed my question [there](http://stackoverflow.com/questions/29085708/looking-for-reflection-effect)
So please tell me if this kind of reflection possible in Three.js and how?
![ref](https://cloud.githubusercontent.com/assets/1878378/7025887/bc5d85be-dd5b-11e4-86a0-f77d9fb8581d.png)
Cause cubemap doesn't work like this and i don't want a complete mirror.
Thanks.

**Comment by mrdoob** [comment]
Use [mirror](http://threejs.org/examples/#webgl_mirror) and add a plane on top of it with half opacity wood texture.

**Comment by mese79** [comment]
Great tip, thanks.
