### ISSUE TITLE
Removal of MeshFaceMaterial

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#6353]
@mrdoob I see that you have finally done it... MeshFaceMaterial is gone as you have been wanting for some time now.

If you or someone could at least point me in the right direction with:
http://stackoverflow.com/questions/29133137/three-js-looking-for-an-alternative-to-meshfacematerial

I would BIG TIME appreciate it. I don't want to be stuck at r71, there is way too much cool stuff happening in r72 =[

I know this is like "App specific", but I cannot imagine I am the only three.js user who will run into this or a similar issue from this update.

Please oh please help.

**Comment by erichlof** [comment]
Hi @titansoftime ,
I gave an answer over on StackOverflow.  You helped me out a while back via email about mesh culling so I'd like to return the favor with my humble solution.  :)

**Comment by titansoftime** [comment]
@erichlof Cool man, this is the direction I will go with this. Now to get the heightmap to work in this type of setup. Will be some work for sure =]

**Comment by mrdoob** [comment]
@titansoftime I have to get the examples working again before the new release, so I'll update loaders to "emulate" `MeshFaceMaterial`.

**Comment by titansoftime** [comment]
Ah cool. In the meantime I think what I'm going to do is manually build the terrain as raw buffer geometry. Probably going to use my "materialmap" as something of a "geometrymap". Will be interesting no doubt =]

Now if only I could merge those geometries and maintain unique materials per "section" (in the interest of making terrain collision {necessary as I use a heightmap} as simple as it was).

Don't get me wrong I like being pushed to use buffer geometry, I've been wanting to do this for some time. My terrain is by FAR the biggest consumer of memory.

**Comment by mrdoob** [comment]
I think that simpleness will come back eventually. Just need to wrap my mind around BufferGeometry.drawcalls.
