### ISSUE TITLE
Colors, Lights behave differently in r71

### ISSUE THREAD

**Issue by hellopath** [mrdoob/three.js#6357]
Hi everybody,

I switched to r71 recently and all the materials that make use of lights like MeshLambertMaterial behave differently. The colors are more bright. Also I noticed that the ambient color removed from MeshLambertMaterial, I don't know if the issue coming from there.
![after](https://cloud.githubusercontent.com/assets/550356/7043667/8250ca94-ddeb-11e4-9ae7-230694eacaa3.jpg)
![before](https://cloud.githubusercontent.com/assets/550356/7043669/86806dea-ddeb-11e4-8b17-f900a121ba13.jpg)

**Comment by bhouston** [comment]
Can you share code?

I believe it could be related to gamma correction -- that was a important change.  Previously, we were gamma correcting color and intensity inputs into the shaders and this was incorrect.  Only images in sRGB space should be color corrected going into the shading process.

**Comment by WestLangley** [comment]
It is likely gamma-related. Can you please provide a live link so we can see exactly what you are doing?

> ambient color was removed from MeshLambertMaterial

`material.ambient` was the ambient reflectance of the material. It should normally match `material.color`, the diffuse reflectance of the material.

We chose to simplify the API, and hardwire `material.ambient` to match `material.color.`

Consequently, `Material.ambient` has been removed.

**Comment by hellopath** [comment]
So I prepared 2 identical versions. The only thing that change between them is just the version of the library.
*r70* http://codepen.io/hellopath/pen/ZYdJmO 
*r71* http://codepen.io/hellopath/pen/jEjLwj

@WestLangley thanks for the explanation about the merge `material.ambient` and `material.color`

**Comment by hellopath** [comment]
@WestLangley @bhouston indeed I use `gammaInput` `gammaOutput` so maybe is coming from there

**Comment by bhouston** [comment]
When I turn off both gammaInput/gammaOutput, they look basically the same.  Thus I think what happened is that you were compensating for the gammaInput adjustments to the shader color variables -- which makes sense, but you were compensating for a bug. :)  I guess it sucks, but you now have to fix that compensation.

**Comment by hellopath** [comment]
When I turn off gamma in/out indeed looks more close than before in term of color but still in light absorption they have big differences. I added a screenshot with both cases without gamma in/out.

> I guess it sucks, but you now have to fix that compensation.
No problem about that I just wanted to know if is an actual version bug or a fix.

![nogamma](https://cloud.githubusercontent.com/assets/550356/7088571/0b02c2c0-df95-11e4-9f21-cb468b4d02fb.jpg)

**Comment by bhouston** [comment]
When I turn off gamma in and out for both r70 and r71 in your examples, they look much more similar when I do it than in your screenshot.

**Comment by hellopath** [comment]
@bhouston ah yeah sorry. I closed the gamma in/out only in the r71 version before. You are totally right.
Thanks for your time guys @bhouston @WestLangley
