### ISSUE TITLE
TubeGeometry acute spline bug

### ISSUE THREAD

**Issue by Varus** [mrdoob/three.js#6358]
As a workaround for windows not being able to display the 'lineWidth' property in the LineBasicMaterial, I have opted to use a TubeGeometry which takes in a SplineCurve3 composed of several Vector3. The issue that I have noticed, is that when there is a point in the spline that goes to another and it forms an angle that is approximately 90 degrees or less, it does not render the tube correctly. Instead, it typically creates something that resembles a plane.

An example of this issue is best demonstrated here:

http://jabtunes.com/labs/3d/webgl_geometry_extrude_splines.html

If you select the closed HelixCurve, there is an incredibly flat 'tube' going from one end of the curve to the other. I would expect that the radius of the TubeGeometry is maintained in this scenario.

Are there any other workarounds for either using the TubeGeometry or a better way of constructing thick 3D lines?

**Comment by Varus** [comment]
Hi @mrdoob. I apologise for phrasing my issue as a help question because that was not my intention. To clarify, is it a feature of TubeGeometry to render the tube as a relatively flat surface at these angles? This appears as a bug to me.

**Comment by WestLangley** [comment]
@Varus In the example you referenced, you need to uncheck the "closed" checkbox. The helix is clearly not a closed loop.

> Are there any other workarounds?

See http://codeflow.org/entries/2012/aug/02/easy-wireframe-display-with-barycentric-coordinates/.

http://threejs.org/examples/webgl_materials_wireframe.html implements a similar technique, although the demo probably should be improved.
