### ISSUE TITLE
ShaderMaterial with Deferred Rendering

### ISSUE THREAD

**Issue by kyma** [mrdoob/three.js#6359]
ShaderMaterials don't seem to work with the deferred renderer. I get an error in createDeferredMaterials where it tries to copy the color: var diffuse = originalMaterial.color;

If the original material is already a ShaderMaterial, could we just clone it and avoid copying the properties across maybe?

Also the first render wipes out the uniforms on the mesh's material, but maybe these can be accessed elsewhere by that point?

I'm using the shaders from here: http://stemkoski.github.io/Three.js/Shader-Glow.html

**Comment by Mugen87** [comment]
`WebGLDeferredRenderer` has been removed. #18284
