### ISSUE TITLE
Sprite with texture interfered with by Mesh

### ISSUE THREAD

**Issue by dubejf** [mrdoob/three.js#6361]
1. Create a sprite with a texture.
2. Create a mesh with a texture.
3. Render the sprite and the mesh with a WebGL renderer.
4. Delete the mesh, dispose of the geometry.
5. Render the sprite. => Error!

In Chrome, the error message is
> [.WebGLRenderingContext]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to render with no buffer attached to enabled attribute 2

Firefox:
> drawElements: no VBO bound to enabled vertex attrib index 2!

If you remove the mesh but don't dispose of its geometry (step 4), the error doesn't appear.

The error is triggered by the call to `gl.drawElements` in `SpritePlugin`. I don't really understand what's going on, but it seems to me like one buffer required by the sprite is not bound.

You can see the bug here (un-comment line 71): http://jsfiddle.net/dubejf/vqyr0z6v/

It's not a new behavior, I've been able to reproduce it with r60.

**Comment by dubejf** [comment]
A more minimal test case (single scene, single camera)

http://jsfiddle.net/dubejf/kxugu4he/1/

**Comment by mrdoob** [comment]
Many thanks for the repro!

**Comment by dubejf** [comment]
The sprite doesn't actually need a texture to trigger the error:  http://jsfiddle.net/dubejf/kxugu4he/3/
