### ISSUE TITLE
logarithmic depth buffer for CSS3DRenderer

### ISSUE THREAD

**Issue by trokster** [mrdoob/three.js#6363]
Hi,
I strictly have no clue if this question actually makes sense. I currently have a CSS3DRenderer scene where I need to zoom in quite a bit. Starting with say 40000px wide Matryoshka doll ( higher dimensions produce bugs in some browsers ) I can zoom about ten times before hitting the 1pixel limit where a click on screen is a pixel 400px wide, and items are all over the place.

Would logarithmic depth buffer solve my problem ?

**Comment by mrdoob** [comment]
Is there a test you can share? I suspect this is a browser issue though...
