### ISSUE TITLE
Blender Exporter not being picked up by Blender 2.74

### ISSUE THREAD

**Issue by jayfield1979** [mrdoob/three.js#6366]
The Blender exporter addon shipped with r71 does not appear to be picked up by Blender 2.74. I have placed the io_three folder in the correct location (C:\Program Files\Blender Foundation\Blender\2.74\scripts\addons) yet I can not see the addon when in User Preferences.

**Comment by jayfield1979** [comment]
Also tried it on OSX as per instructions and still not being picked up.

**Comment by RemusMar** [comment]
![blender](https://cloud.githubusercontent.com/assets/11772787/7066100/aa7d7544-dec7-11e4-9ae2-a34888c9547f.jpg)

**Comment by jayfield1979** [comment]
![1](https://cloud.githubusercontent.com/assets/1374462/7066178/e9831574-deb7-11e4-9427-677cbb55aea2.PNG)
![2](https://cloud.githubusercontent.com/assets/1374462/7066180/ec924a8c-deb7-11e4-99dd-241ab63f5f10.PNG)

**Comment by jayfield1979** [comment]
Is there something I need to do to enable the exporter to be picked up? I followed the instructions on the md file.

**Comment by RemusMar** [comment]
Your Blender installation is messed up.
By deafult, you should see a bunch of disabled addons.
If you need my advice: uninstall/remove anything Blender related, create a "Blender" folder and unpack the ZIP Blender package in that folder.
After that just copy the needed addons in /2.74/scripts/addons/ folder.

cheers

**Comment by antont** [comment]
no he's doing a search for 'three' and that doesn't find anything.

i'm having the same problem on osx now -- fresh install of the latest Blender release (2.74) and three.js master.

**Comment by jayfield1979** [comment]
I installed Blender this morning on a clean OS (both PC and Mac).... what mistake did you make when copying the DIR, I might have done the same?

**Comment by RemusMar** [comment]
Just follow the above steps and you won't face any issue.
![blender_three](https://cloud.githubusercontent.com/assets/11772787/7066825/f4b863d8-dece-11e4-8a57-194328feb09d.jpg)

**Comment by antont** [comment]
@jayfield1979 - My mistake was really stupid, due to having Finder in tree mode instead of the 3 column one I normally use .. I had just copied the dir to the Blender.app/ root, not in this dir inside the. app/ .. Contents/Resources/2.74/scripts/addons/

**Comment by jayfield1979** [comment]
On OSX I did that and still not displaying.... it's weird it's not working for me in both OS's.

**Comment by RemusMar** [comment]
On Windows, delete this folder and try again:
C:\Documents and Settings\_username_\Application Data\Blender Foundation\

**Comment by jayfield1979** [comment]
I don't have that folder so I deleted the C:\Users\James\AppData\Roaming folder instead and still it is not showing. I am really not sure what else I can do.
