### ISSUE TITLE
Bundle VREffect / VRControls in threejs build

### ISSUE THREAD

**Issue by dmarcos** [mrdoob/three.js#6379]
@mrdoob Do you think it makes sense to bundle VREfffect / VRControls in the threejs build so people just have to drop threejs to start creating VR content?

**Comment by mrdoob** [comment]
Hmm... Not sure...

**Comment by brianchirls** [comment]
I don't love this idea, at least not for right now. The build is already quite big, and most people are still using it for non-VR. Also, `VREffect` is still very much in flux, so it's best to leave people with the option of using their own versions of those scripts. And a-frame now exists as an easy turnkey option.

**Comment by gero3** [comment]
Maybe we should add a seperate build. The build system allows it anyways. As long as we don't add the minified version, It wouldn't be much longer to create it. 
maybe calling it ThreeVR.js.

**Comment by Mugen87** [comment]
In the meantime, [WebVRManager](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webvr/WebVRManager.js) is part of the core. I think that should solve the issue.
