### ISSUE TITLE
Is there a function exposed that I can search val z by (x,y) in 3D model ?

### ISSUE THREAD

**Issue by hjk61314** [mrdoob/three.js#6386]
I have two models,which one is below another.Now I can get one model's coordinates (x,y,z) by clicking screen ,
then what can I get another model's coordinate(x,y,z)  ?
I think they have the same (x,y),I don't know whether a function can support it.
It's really important for 3D model interaction.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

Study the examples using `Raycaster`.
