### ISSUE TITLE
export/import PlaneBufferGeometry

### ISSUE THREAD

**Issue by rfm1201** [mrdoob/three.js#6391]
Reading different sources on the web, I found that exporting a scene could be done with a code like

    localStorage.setItem("scene", JSON.stringify(scene.toJSON()));

where scene is my THREE.Scene instance.

Importing this saved scene is done with a code like:

    var json = localStorage.getItem("scene");
    if (json) {
        var loadedGeometry = JSON.parse(json);
        var loader = new THREE.ObjectLoader();

        loadedScene = loader.parse(loadedGeometry);
        scene = loadedScene;
    }

It works great with my simple scene as long as I used Geometry objects and no BufferGeometry objects. In my case, I used a PlaneGeometry or a PlaneBufferGeometry.

The issue is that the toJSON function serialize what it found in memory (nothing unusual), but the ObjectLoader function call the PlaneGeometry or PlaneBufferGeometry constructor with the same parameters in both case.
The call to the PlaneBufferGeometry’s constructor fails because data.width, data.height, data.widthSegments and data.heightSegments are undefined.
The real values needed by the constructor are in the internal buffer (data data attributes position).

Did I miss a function to be used for the export (the editor seems to use the same type of code), or should toJSON or ObjectLoader be modified for BufferGeometry objects?

**Comment by mrdoob** [comment]
Can you create a jsfiddle that reproduces the issue?

**Comment by rfm1201** [comment]
http://jsfiddle.net/3hmqe7f4/
If you use the line with the PlaneGeometry constructor it works.
The problem is in the parseGeometries function when the PlaneBufferGeometry constructor is called with data not defined in the json.

**Comment by mrdoob** [comment]
I think that should fix it. Thanks! ^^
