### ISSUE TITLE
SpotLight & PointLight not working correctly when visible attributes of them are initialized to false

### ISSUE THREAD

**Issue by Nandiin** [mrdoob/three.js#6397]
Initialization code:

``` javascript
var lightTrig = false;
var pointLight = new THREE.PointLight(0xffffff, 1, 10);
pointLight.position.copy(initialPos);
pointLight.visible = false;  // THIS LINE

scene.add(pointLight);
```

and in my event handler, I toggle the visible attribute 

``` javascript
function keyDown(e) {
    switch(e.keyCode) {
        // some code...
        case 76: // l
            lightTrig = !lightTrig;
            pointLight.visible = lightTrig;
            break;
        // some other code...
    }
}
```

If I comment "THIS LINE" everything goes as expected (in fact, I need to tap L key on keyboard twice to synchronize pointLight.visible with lightTrig since the lightTrig is initialized to false. )
But if "THIS LINE" is not commented i.e. pointLight.visible is initialized to false, pointLight will never illuminate the scene no matter how many times I tap the L key.

I assume that other part of my code is correct because it will work as long as "THIS LINE" is commented. However, I need the pointLight.visible to be false in the begining state so the user can turn on the light (by tapping L key). Is there anybody who knows what happened when I set visible attribute of pointLight to false before rendering ? 

PS: same thing happens when I use SpotLight.
PPS: Sorry for my bad English!

**Comment by mrdoob** [comment]
Could you create a jsfiddle that reproduces the issue?

**Comment by WestLangley** [comment]
Please see [this stackoverflow post](http://stackoverflow.com/questions/25497541/cannot-add-to-scene-after-rendering-three-js/25497681#25497681) for an related issue.

Instead of setting `light.visible = false`, set `light.intensity = 0` at the start.

**Comment by zwcloud** [comment]
Has this issue been solved?

**Comment by WestLangley** [comment]
@zwcloud The issue was addressed by https://github.com/mrdoob/three.js/commit/1cdc0957319dfd203f314b132fd8ea2178c478bd, so apparently, it has.
