### ISSUE TITLE
Decouple CubeCamera from scene

### ISSUE THREAD

**Issue by J-Zeitler** [mrdoob/three.js#6400]
A (very minor) suggestion on architecture:

I had some trouble setting up a `THREE.CubeCamera` in one of my projects. The thing I found unintuitive was that (in contrast to regular `THREE.Camera`s) the CubeCamera *has* to be added to the scene. The option to add it to the scene is of course a good thing because, just like with regular cameras, you might want to attach it to things in the scene etc.

However, not adding the CubeCamera to the scene gives some strange results. It took me a while to figure out that it was indeed that all of the six cameras in the CubeCamera was getting the same transform.

Wouldn't it be better if, in `CubeCamera::updateCubeMap`, there was a `this.updateMatrixWorld()`?

**Comment by mrdoob** [comment]
Done! Thanks!

**Comment by WestLangley** [comment]
@J-Zeitler Nice find and a good suggestion.

This does look right, meaning `scene.add( cubeCamera )` can be removed from the examples. And, for that matter, `scene.add( camera )` when the camera has no children.

**Comment by mrdoob** [comment]
It's still good practice to add it to the scene though.

**Comment by WestLangley** [comment]
> It's still good practice to add it to the scene though.

I don't think so. It serves no purpose to do so, unless there are children of the camera.

Problems occur when there is more than one scene.

**Comment by mrdoob** [comment]
If we forced the user to add the camera to the scene (as we used to) then we could forget about all these scenarios. Sometimes is tempting...

**Comment by WestLangley** [comment]
You mean, one of the scenes?

**Comment by mrdoob** [comment]
I think we used to do something like this...

```javascript
if ( camera.parent === undefined ) {
	console.log( 'let user know' );
	scene.add( camera );
}
```

**Comment by WestLangley** [comment]
What is the purpose of forcing the user to add the camera to the scene?

What if there are two scenes, and the user is rendering one scene or the other (not both)? Which scene should the user add the camera to?

**Comment by mrdoob** [comment]
Yeah. This is complicated. I don't think I can solve it.

**Comment by MasterJames** [comment]
Maybe you could have a default behavior, which you can always override?
