### ISSUE TITLE
three.js Render 3D VRML Geometry adding into mesh issue.

### ISSUE THREAD

**Issue by dev1intellial** [mrdoob/three.js#6406]
I'm attempting to use the three.js 3D library to properly render a 3D VRML model. In this case using vrml loader its working fine but when I attempting to add  geometry into mesh which returned by the vrml loader then I am getting this error --

TypeError: geometry.morphTargets is undefined var numMorphTargets = geometry.morphTargets.length;

My code is look like :

            var loader = new THREE.VRMLLoader();
            loader.addEventListener( 'load', function ( event ) {
                var geometry = event.content;
                var material = new THREE.MeshPhongMaterial( { color: 0x75D3DC, ambient: 0x75D3DC, specular: 0x75D3DC, shininess: 200} );
                var mesh = new THREE.Mesh( geometry, material  );

                mesh.position.y = 0 ;

                scene.add(mesh);
            } );
            loader.load( "./stl/lemo2.wrl" );

Any suggestion how to solve this issue?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
