### ISSUE TITLE
Typeface.js, THREE.TextGeometry and offline service

### ISSUE THREAD

**Issue by MagistrAVSH** [mrdoob/three.js#6410]
Hello all! I have problem with using http://typeface.neocracy.org. It service not working at all. Offline. But how convert fonts to use with three.js, without typeface.neocracy.org? What solution? On stackoverflow not found solution (http://stackoverflow.com/questions/29347873/three-js-typeface-js-offline?noredirect=1#comment46909999_29347873), offline perl verison working very bad.

**Comment by gero3** [comment]
I made a new converter that outputs the same format.

http://gero3.github.io/facetype.js/

**Comment by zz85** [comment]
cool @gero3

**Comment by mrdoob** [comment]
Nice! Are there any docs we should update?

**Comment by ajvincent** [comment]
I could not get this to work with Mozilla Firefox, but it worked instantly with Google Chrome.

**Comment by gero3** [comment]
@ajvincent 
Is this about the facetype.js or in three.js itself??

**Comment by ajvincent** [comment]
On the facetype website itself.  I haven't started tinkering with three.js yet.  Basically, clicking on the Convert button was a no-op.

**Comment by gero3** [comment]
I fixed the website, so firefox can also convert typefaces.
