### ISSUE TITLE
Image texture from 2d canvas or image element not working

### ISSUE THREAD

**Issue by podelo** [mrdoob/three.js#6413]
Hello,

I m trying to apply an image texture on a plane. This texture is from a 2d canvas I dynamically create in my code. I also tried to create it from an image element but it's still the same.

    var img = document.createElement("img");

    img.src = "myImage.png";    //same with an url from the web

    var t = new THREE.Texture(img);

    t.needsUpdate = true;

	var xm = new THREE.MeshBasicMaterial({ map: t, side: THREE.DoubleSide, transparent: false });	

	var myMesh2 = new THREE.Mesh(new THREE.PlaneBufferGeometry(5, 5, 32), xm);

	scene.add(myMesh2);

I also tried adding the image element to the DOM but it still doesn't work. I also tried to bind to image.onload event but the firefox's console give me the following error: "The operation is insecure".

Any idea please ?

Thanks a lot !

**Comment by benaadams** [comment]
Are you loading any image from a different domain to the one that the page is running on; if so you will likely be running into cross domain issues: http://stackoverflow.com/questions/24087757/three-js-and-loading-a-cross-domain-image

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by podelo** [comment]
The image I m trying to load is stored on the same web server than the running page.
