### ISSUE TITLE
adding quadsphere support to three.js

### ISSUE THREAD

**Issue by tomasparks** [mrdoob/three.js#6414]
I would like to see three.js have quadsphere support
I have found a [quadsphere library](https://github.com/merpnderp/webglquadtreeplanet/) using an old version of three.js
I have attempted to contact the author but he has not got back to me :(

**Comment by tomasparks** [comment]
I've updated the quadsphere library to v71 from v66 :)
I am looking at contribute it to three, but it needs to bit of refactoring

**Comment by mrdoob** [comment]
That'd be awesome! 😄

**Comment by tomasparks** [comment]
I've uploaded the pre-refactored version to https://github.com/tomasparks/three.js looking the addon/demo folder

**Comment by mrdoob** [comment]
Looking good so far!

**Comment by Mugen87** [comment]
I think it's better to keep the code presented in #6438/#6452 out of the repository for complexity reasons. `quadsphere` can still be promoted at the [forum](https://discourse.threejs.org/) in the `resource` category.
