### ISSUE TITLE
Samsung Tab4 - DeviceControls not working

### ISSUE THREAD

**Issue by bogdanfer** [mrdoob/three.js#6416]
Samsung Tab4, Chrome 41.0, Android 4.4.2
threejs controls demo - DeviceOrientation
I am getting the following console logs and controls are not responding.

`THREE.WebGLRenderer 71`
`THREE.WebGLRenderer: OES_texture_float_linear extension not supported.`

any suggestions/ideas? thanks

**Comment by benaadams** [comment]
Those logs are just informational

**Comment by bogdanfer** [comment]
@benaadams yes sure, just trying to describe my case in the best way.

**Comment by mrdoob** [comment]
This is definitely a hardware/system bug. Not a bug in the lib.

**Comment by tbalouet** [comment]
Just in case somebody fall here like I did, I had the same problem on r73 when loading a cubemap of 2048x2048 textures (6 times). It didn't work on Moto X 2nd gen and Nexus 5 but did on Galaxy s6 and iphone 6.
By resizing the images to 256x256 each, it works fine now. So it might be a problem of texture size loaded at once
