### ISSUE TITLE
Migration and changelogs for >r69

### ISSUE THREAD

**Issue by jonnenauha** [mrdoob/three.js#6417]
I can't be the only one wondering that there has been two releases that have basically no changelog or migration docs. Both of these are very valuable when updating three.js in a big project.

Is the case that there has not been time to write them or simply that there are no breaking changes to note for migration? Changelog is empty for r71 and r70 says "Still writing...". If the case is that there are no migration considerations I think the page should clearly state "No breaking changes" or similar.

I've been waiting a long time now for the docs to appear so I could update our application to the latest.

Pages in question for completeness
* https://github.com/mrdoob/three.js/wiki/Migration
* https://github.com/mrdoob/three.js/releases

**Comment by Dynasty9** [comment]
:+1: hoping for a high level summary of the features of r70/71

**Comment by vakorol** [comment]
Two thumbs up for this issue. 
I already discovered Raycaster.setFromCamera() new method, so this is definitely not a "No breaking changes" case.

**Comment by jonnenauha** [comment]
@vakorol Yeah, exactly. I tend to pop in and follow the issues for anything interesting, but cant say this would give me a in depth knowledge of all the changes that might catch me when upgrading. For example there has been a lot of issues/discussion about the pixel ratio stuff in the renderer, but I'm not certain if this change is already out or still in the works.

Well, good to know that I'm not the only one missing the docs.

**Comment by QuaziKb** [comment]
there are some breaking changes with the way the renderer works, however i forgot what they were :< My project was a black screen till i figured it out.

**Comment by mrdoob** [comment]
Hey guys!

This year I found myself doing 5 talks in 4 months in 4 different countries. It's been a bit hectic. It was hard enough to get the releases in time 😇

I'm now done with all that and catching up on things.

Sorry about that!

**Comment by jonnenauha** [comment]
Yeah, I've noticed you've been busy. It's good you are doing PR for the project too, not that anyone in the field would not know what this library was :)

Good to hear its coming. I've been happy running r68/9 and been patiently waiting. Feel free to close this issue when you feel like it.

**Comment by remoe** [comment]
I have a lot of issues with porting r68 to newer one. Particularly a lot of custom stock shader issues. Are the shader code completely rewritten? It would be cool when some one can update https://github.com/mrdoob/three.js/wiki/Migration with shader updates. Thanks.

**Comment by mrdoob** [comment]
Almost there! Almost there!

**Comment by remoe** [comment]
Here are some shader compile errors (0.68 > 0.71):

```
THREE.WebGLShader: gl.getShaderInfoLog() ERROR: 0:181: 'transformDirection' : no matching overloaded function found 
ERROR: 0:181: '=' :  cannot convert from 'const float' to 'highp 3-component vector of float'
```

```
THREE.WebGLShader: gl.getShaderInfoLog() ERROR: 0:78: 'diffuseColor' : undeclared identifier 
ERROR: 0:78: 'a' :  field selection requires structure, vector, or matrix on left hand side 
```

**Comment by mrdoob** [comment]
Done!
https://github.com/mrdoob/three.js/releases

**Comment by remoe** [comment]
@mrdoob, but no migration guide. Is this document deprecated ( https://github.com/mrdoob/three.js/wiki/Migration ) ?

**Comment by vakorol** [comment]
Great job, @mrdoob !
But +100 to @remoe's comment about the migration guide. It would be perfect to have that also!

**Comment by remoe** [comment]
It's done since a month:
https://github.com/mrdoob/three.js/wiki/Migration
Thanks @mrdoob !
