### ISSUE TITLE
Geometry.center is missing in the documentation

### ISSUE THREAD

**Issue by nkint** [mrdoob/three.js#6421]
http://threejs.org/docs/#Reference/Core/Geometry is missing `center` method, in the github there is.
Am I wrong?

**Comment by erichlof** [comment]
Hi @nkint ,
It now appears to be here: http://threejs.org/docs/#Reference/Extras/GeometryUtils

**Comment by jonnenauha** [comment]
Related #6417

**Comment by gero3** [comment]
This seems to be solved now in dev
