### ISSUE TITLE
How to export Blender boleean modifier to a program using three.js ?

### ISSUE THREAD

**Issue by Ouaps** [mrdoob/three.js#6423]
Hello !

I try to export an animation from Blender to a programm using Three.js. The animation is a boleean modifier. He display the drawing gradually. I don't know how to export it from Blender correctly and how insert it after, correctly too, in my three's program. Is it a solution to do this ? 
For the drawing, i use a collada format but it's not possible, for this, isn't it ? What can i do ?
(Sorry for my bad english !)

Thanks !

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
