### ISSUE TITLE
THREE.Group() add child

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#6424]
There is something wrong with adding a child to a THREE Group() or Object3D():
when you add a child object, the position, rotation and scale of that child object are changed.
And that's wrong!
In all the other 3D apps I work with, the world position, rotation and scale of the child object are the same, no matter what parent you set for that child.
This should be fixed asap, otherwise you need to waste processing power at runtime to "recover" those lost parameters.

I'm not talking about the LOCAL position, rotation and scale of the child object (they will change according to the new parent).
I'm talking about the WORLD position, rotation and scale of the child object (they must be the same).

cheers

**Comment by mrdoob** [comment]
I don't think you know what you're saying. The WORLD position can't be the same if the LOCAL position doesn't changing a translated parent.

Play with the [editor](http://threejs.org/editor/) and change the parent objects to see how it behaves.
