### ISSUE TITLE
ShaderMaterial and WebGLRenderer option logarithmicDepthBuffer set to true

### ISSUE THREAD

**Issue by arnaldof** [mrdoob/three.js#6427]
Here's my original question in StackOverflow: http://stackoverflow.com/questions/29217468/three-js-objects-intersected-and-shader-material

In short, meshes using ShaderMaterial are always like "in background" when logarithmicDepthBuffer=true (http://jsfiddle.net/Arnaldof/h7s6mv15/1/)
When the option is false, it works as expected.

Not sure if it is a bug, but took me so much time to figure it out. I rather use logarithmic buffer because I need to put many objects very close together.

**Comment by benaadams** [comment]
Answered on SO

**Comment by arnaldof** [comment]
Thanks!
