### ISSUE TITLE
Coordinate system presets

### ISSUE THREAD

**Issue by meefox** [mrdoob/three.js#6430]
It would be useful to have changeable coordinate system. Similar to blender, maya, max... etc.
And have property like coordinateSyste = 'Blender' in Scene class
and the same for FOV in Camera class. It would make life significantly easer.

**Comment by mrdoob** [comment]
Not sure if changeable coordinate system is doable though...

**Comment by Mugen87** [comment]
I think we can close this issue. AFAIK, even big game engines like unity have a fixed coordinate system.
