### ISSUE TITLE
Wireframe example broken

### ISSUE THREAD

**Issue by brason** [mrdoob/three.js#6431]
I noticed that the webgl_materials_wireframe example doesn't show correctly anymore. Just wanted to give a heads up.

![wireframe](https://cloud.githubusercontent.com/assets/11060019/7220433/e6cdef5e-e6c6-11e4-927c-d39c516b806d.png)

**Comment by Wizarth** [comment]
Wireframe mode on Three.Mesh (with BufferGeometry with unindexed position buffer) is broken for me. It looks like the wireframe mode connects every vertex in order in the position buffer, versus connecting 3, then 3, then 3 (etc) to do triangles.

**Comment by Wizarth** [comment]
At some point, the geometry for doing a wireframe changed from tri's (three points making a triangle) to edges (two points, defining an edge). See WireframeHelper for constructing this data structure.

**Comment by mrdoob** [comment]
It still looks ok here...? http://threejs.org/examples/index.html#webgl_materials_wireframe

You mean on the `dev` branch? If so, yes... stuff is broken over there at the moment.

**Comment by mrdoob** [comment]
> I'm using release 70, for reference. This used to work in release 63.

`BufferGeometry` and wireframe has never worked 😉

**Comment by mrdoob** [comment]
Fixed! 0048009f4d2b4bf837b6c2fb4b108295c58484ce Even with `BufferGeometry` 😊

**Comment by Wizarth** [comment]
Thank you, I expect I'll use this in the near future.

**Comment by brason** [comment]
Hooray! Great job :)
