### ISSUE TITLE
Transform a plane onto a half cylinder

### ISSUE THREAD

**Issue by rogeriothessal** [mrdoob/three.js#6435]
I am trying to transform a plane onto a half cylinder. How can I do an animation of this transformation?

![doub](https://cloud.githubusercontent.com/assets/12039026/7238673/6f6b0532-e77a-11e4-8729-060efaa23437.png)

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
