### ISSUE TITLE
Model changes rotation when adding a animation

### ISSUE THREAD

**Issue by hulf** [mrdoob/three.js#6436]
I'm using the latest build 72dev. 

I have a object with a bone parented and a simple animation.
When I'm loading a model with objectloader the rotation, scale and position are fine.
![1a](https://cloud.githubusercontent.com/assets/10427535/7249465/d9a3fa44-e81a-11e4-97fb-d602c9a29c24.jpg)

when I add a bone, parent it to the object and load it with objectloader, the object gets rotated ( .x = .y = Math.PI ).
![1b](https://cloud.githubusercontent.com/assets/10427535/7249503/0358de0e-e81b-11e4-9672-087988b669b5.jpg)

In Blender I tried out some different combinations like suggested in different posts:
- CTRL +A location + rotation on mesh and bone,
- Keep transform - location, rotation 
- reset the origin.

Thanks in advance, I hope its not something silly in Blender I forgot.
PS.: Thanks for the great work with three.js, didn't have so much fun in years :).

**Comment by sunnydrake** [comment]
same issue :) according To Axis Helper axes is messed up
Xbone - bone along acis (Scale etc toggled)  All other stuff unboned mesh
here is illustrated example:
blender 
![2015-10-07 18 46 07](https://cloud.githubusercontent.com/assets/15017432/10342845/b4b47216-6d23-11e5-8538-9687767bc92d.png)

render
![2015-10-07 18 42 28](https://cloud.githubusercontent.com/assets/15017432/10342778/6d240c22-6d23-11e5-9083-f68bd434ef54.png)

**Comment by sunnydrake** [comment]
last git pull after r72

**Comment by sunnydrake** [comment]
checked bone export, position of Y coord  pos[2] somehow have - sign.

**Comment by sunnydrake** [comment]
bone param fix
io_three/exporter/api/mesh.py
1018        z_axis = -bone_world_pos.y
change to          z_axis = bone_world_pos.y

**Comment by sunnydrake** [comment]
still mesh flipped

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
