### ISSUE TITLE
Is there a better way to render an 3D stereoscopic image for VR than create two scenes?

### ISSUE THREAD

**Issue by arturitu** [mrdoob/three.js#6437]
I'm reviewing the http://threejs.org/examples/#vr_video and there are two scenes to render a different part of the video corresponding to the left and right eye shot. But I thought if I will need to add some HUD elements, this option would make me hard to include 3D elements over this stereoscopic background. 
**In this case, the right way would be included in a third scene? or duplicate in both scenes?**

What I did (with an image instead a video) is to create 2 meshes (one for each eye) and changed StereoEffect and VREffect to make visible or hide each mesh on every render before "paint" every part of the scene.
**Makes sense? or will have a worse performance?**

![image](https://cloud.githubusercontent.com/assets/5744112/7254440/5e595676-e843-11e4-9141-e18413a6e3d4.png)

Example working > www.unboring.net/lab/image3DPano (Cardboard & Oculus)
Source code > www.unboring.net/lab/image3DPano/image3DPano.zip

**Comment by sigmaxipi** [comment]
What about adding a "root" Object3D to both scenes and then adding all your common objects to that root? Any eye specific objects can be directly added to the pair of scenes but everything else would be added to the common root.

**Comment by mrdoob** [comment]
I think the masking idea in #5562 could solve this. We will then have a single scene with everything and two cameras with different layerMasks. How does this sound?

**Comment by arturitu** [comment]
It sounds the best solution but I'll wait for more progress in the implementation of that because I've been trying to understand the #5562 but I do not know if I would be able to help a lot now :(

**Comment by tbalouet** [comment]
I just came accross the same problem, and was about to duplicate each of my meshes. Have you found a better way to solve this problem?

**Comment by mrdoob** [comment]
We can now use `layers` to select if the object should be visible for the left or right eye. 

Take a look at the VR video example for reference:
https://github.com/mrdoob/three.js/blob/dev/examples/vr_video.html

**Comment by tbalouet** [comment]
Looks great, but I can't see where you developed the object.layers functions. Is it still work in progress?

**Comment by mrdoob** [comment]
Yes, I added it last cycle as `THREE.Channels` but renamed it to `THREE.Layers` this cycle.

https://github.com/mrdoob/three.js/blob/dev/src/core/Layers.js

The code is definitely not very easy to understand, but it basically allows us to control what objects a camera is able to see.

**Comment by tbalouet** [comment]
OK thanks, I think I got it working with Channels (for now, will update to Layers with next build). Seems to work fine, thanks for the good job, it'll simplify things!

**Comment by curti55** [comment]
I cant get this to work. With 74dev, the example only shows one half (i think the last added -> right eye)
When i dont add the right mesh, nothing is shown, when bot meshes are added i get the same texture on both eyes. Trying to use THREE.StereoCamera results in "THREE.WebGLRenderer.render: camera is not an instance of THREE.Camera"

**Comment by mrdoob** [comment]
@curti55 I reverted the `THREE.StereoCamera` thing. `THREE.PerspectiveCamera` works just fine, check the examples.

**Comment by curti55** [comment]
I'm using the webvrmanager to enter vr mode (debug in this case). When i enter VRMode only layer 1 Meshes are displayed.

**Comment by curti55** [comment]
ok, i think i found the problem: https://github.com/mrdoob/three.js/issues/7732
