### ISSUE TITLE
Blender Exporter Error

### ISSUE THREAD

**Issue by KTM450SXF** [mrdoob/three.js#6439]
I've updated the Blender exporter in the Blender addon directory from here: https://github.com/mrdoob/three.js/tree/master/utils/exporters/blender
using the directions found on that page.  

I then try to export in Blender and I'm getting an error, the text of which is as follows:

File "C:\Program Files\Blender Foundation\Blender\2.74\scripts\addons\io_mesh_threejs\__init__.py" line 722, in execute
from io_three import exporter
ImportError: No module named 'io_three'

Unfortunately, I don't code in Python so hunting down this issue's proven to be a bit rough.  Does anyone have any thoughts or ideas?

**Comment by repsac** [comment]
Not really sure what is going on here but the file path should _not*\_ look like this:
`C:\Program Files\Blender Foundation\Blender\2.74\scripts\addons\io_mesh_threejs__init__.py`

The root folder itself is called `io_three` and I don't see that in your path. There should be a `addons\io_three\__init__.py` in the suffix of your path but there isn't. You must have copied and renamed files incorrectly. This is what a correct `addons` structure looks like with `io_three`
```
$ tree $BLENDER_USER_SCRIPTS/addons/io_three
├── __init__.py
├── constants.py
├── dialogs.py
├── exceptions.py
├── exporter
│   ├── __init__.py
│   ├── _json.py
│   ├── api
│   │   ├── __init__.py
│   │   ├── animation.py
│   │   ├── camera.py
│   │   ├── constants.py
│   │   ├── image.py
│   │   ├── light.py
│   │   ├── material.py
│   │   ├── mesh.py
│   │   ├── object.py
│   │   └── texture.py
│   ├── base_classes.py
│   ├── geometry.py
│   ├── image.py
│   ├── io.py
│   ├── material.py
│   ├── object.py
│   ├── scene.py
│   ├── texture.py
│   └── utilities.py
└── logger.py
```

**Comment by KTM450SXF** [comment]
Thanks you, repsac.  That answered my question.  First, I missed a / typing the error so the path should have looked like this:
C:\Program Files\Blender Foundation\Blender\2.74\scripts\addons\io_mesh_threejs/__init__.py

But your answer told me that the line in question in __init__.py was expecting its containing folder to be named io_three.  And to be honest, I should've guessed that.  I changed the directory name and it worked like a charm.

Again, thank you very much.
