### ISSUE TITLE
THREE.SkinnedMesh.prototype.raycast is missing

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6440]
:'(

**Comment by single-entity** [comment]
Do we have an ETA on this at all chaps?  Raycasting for SkinnedMeshes would be very useful.

**Comment by makc** [comment]
my PR can no longer be merged, but if you could go with the older 3js version, it will work :)

**Comment by single-entity** [comment]
So there's a version of 3js with THREE.SkinnedMesh.prototype.raycast?  Which version?

**Comment by makc** [comment]
@single-entity [this version](https://github.com/makc/three.js.fork/tree/skin-raycast) :eyeglasses:

**Comment by henryJack** [comment]
@makc, are you planning on making this compatible with later versions of three.js? It would be extremely useful!

**Comment by makc** [comment]
@henryJack I seem to recall someone else added raycast to skins already. no?

**Comment by henryJack** [comment]
Nope, as of r85, raycasting for skins seems to be missing!

**Comment by makc** [comment]
you know what could work?
1 make new THREE.Mesh (skinnedMesh.geometry.clone (), skinnedMesh.material) and save,
2 set skinnedMesh.raycast = mesh.raycast.bind(mesh),
3 before casting rays, transform mesh.geometry.vertices (or position attribute) according to the code above

**Comment by Soj123** [comment]
You would need to constantly update the vertices whilst the skin is animating. That would cause massive frame rate drops surely?

**Comment by Soj123** [comment]
Really, what you want is some sort of raycaster which operates on the gpu. This is where the skin animation objects are stored. I do not have the skills required to do this but agree that it would be an extremely useful feature. Maybe @mrdoob or @WestLangley would have a better idea of how to move forward with this?

**Comment by makc** [comment]
if you do that on gpu, you still need to read the pixel back, which might introduce another pause on cpu side if it has to wait for gpu data, in effect also making things slower

**Comment by henryJack** [comment]
So is it impossible to have real time ray casting for skins whilst they are animating using skeletons?

**Comment by makc** [comment]
not ootb, but possible

**Comment by henryJack** [comment]
Is this the same for morph target animations?

Have any of the big guns on here sketched out an idea for making raycasting work for skins? I wouldn't mind giving it a go if I knew where to start!

**Comment by donmccurdy** [comment]
I’m assuming we want a feature request open for SkinnedMesh raycaster support, several issues have been dup’d to this one.

**Comment by makc** [comment]
Yeah but the code here is 5 years old and longer merge-able, so why not
just point to #19178 from here

**Comment by Mugen87** [comment]
This here is the issue, not the PR.

**Comment by donmccurdy** [comment]
Fixed by https://github.com/mrdoob/three.js/pull/19178, thanks to @cpollard1001 for the original implementation.
