### ISSUE TITLE
gltf loader doesn't check complete after shader loaded 

### ISSUE THREAD

**Issue by tiagocardoso** [mrdoob/three.js#6442]
Hi,

Using:

Chrome: Version 41.0.2272.3 dev (64-bit) - Ubuntu
Threejs: r71

I'm doing a polymer element to load GLTF models.
I've came across a possible bug.

Some times the loader would do any error, but wouldn't call the callback function.
After investigating for a bit I've notice that only after a mesh (.bin) is loaded does the loader checks if it's complete and runs our callback.
I my case, although the XHR call for the shader (two of them) was been made before the .bin request, one of the shaders would be loaded after the .bin. 
This just happens some times on the local machine, but still when getting the shaders (or another stream) the loader should again check if everything is completed to apply the callback.

Does this makes sense or am I doing something wrong ?

Thank you in advance.
I'll be happy to send more info if requested.

**Comment by tparisi** [comment]
alive, looking
