### ISSUE TITLE
ColladaLoader bug

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#6443]
I'm talking about skinned meshes controlled by bones.
Everything is (almost) fine as long there is a single material per mesh.
In case of meshes with 2 or more materials, the animation (for that model only) does not work at all.

cheers

**Comment by mrdoob** [comment]
Please, follow the guidelines on how to report bugs.
https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md

**Comment by RemusMar** [comment]
Ricardo, what other details do you need?
Did anyone try this loader for an animated model with multiple materials?
If no one, do you want me to upload a DAE somewhere?

**Comment by RemusMar** [comment]
A single mesh with a single material:
http://necromanthus.com/Test/html5/girl.html 
Everything is ok.

The same mesh, same bones, same animation, but 2 materials:
http://necromanthus.com/Test/html5/girl2.html 
The animation does not work!

Both DAE files run just fine in any other environment (except THREE).

**Comment by mrdoob** [comment]
Many many thanks for the examples!

**Comment by RemusMar** [comment]
See the fix here:
https://github.com/mrdoob/three.js/issues/6489

**Comment by Mugen87** [comment]
This problem is solved `ColladaLoader2` that handles skeletal animation and multi materials better than its predecessor.
