### ISSUE TITLE
FogExp2 doesn't affect Sprites

### ISSUE THREAD

**Issue by mstrater** [mrdoob/three.js#6444]
FogExp2 is not affecting Sprites even when the SpriteMaterial has "fog: true".
To reproduce, add this snippet to the "misc_controls_orbit" example and zoom out until the sprite disappears. It won't fade with the fog.

	var mapB = THREE.ImageUtils.loadTexture( "textures/sprite1.png" );
	var materialB = new THREE.SpriteMaterial( { map: mapB, color: 0xffffff, fog: true } );
	var sprite = new THREE.Sprite( materialB );
	sprite.scale.set(50, 50, 50);
	scene.add(sprite);

I'm running Windows 7, Chrome  42.0.2311.90 m
I reproduced in r71 and r72dev.

Is this a bug? I didn't see any reference that it's not supposed to work. If this is intentional, maybe there should be a note in the documentation.

Thanks,
Max

**Comment by WestLangley** [comment]
Thanks.

I believe the bug is [here](https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/plugins/SpritePlugin.js#L325)

    'float fogFactor = exp2( - fogDensity * fogDensity * depth * depth * LOG2 );',

`fogFactor` is declared a `float` for a second time.

**Comment by mstrater** [comment]
Good catch! That seems to fix it.

**Comment by mstrater** [comment]
I made a pull request for the fix. #6445
Feel free to make the pull yourself if you prefer, though.
Thanks,
Max

**Comment by WestLangley** [comment]
Yes, the second declaration of `float fogFactor` has scope only within the if-statement.

**Comment by WestLangley** [comment]
Thanks for the PR.

**Comment by mrdoob** [comment]
Thanks guys!
