### ISSUE TITLE
Anomalies with transparent object overlapping itself

### ISSUE THREAD

**Issue by mikaat** [mrdoob/three.js#6447]
It seems that that both MeshPhong and MeshLambertMaterials are not working correctly with a transparent object when object faces are overlapping. It's like every other face is more transparent than the other. See an image below. I have tried everything, setting depthWrite: false, depthTest: false but without much success. Could it be that the depthtest works only with the whole objects but faces are not sorted individually?

![transparent-object-face-anomalies](https://cloud.githubusercontent.com/assets/12079556/7291517/05a0c96c-e99a-11e4-9ee2-937ead1a07b8.png)

**Comment by Usnul** [comment]
this is a question. Questions are to be directed to stackoverflow. Answer is: no, faces aren't sorted. This is not possible to do in the shader, and WebGL doesn't do it for you, so only option would be sorting on CPU, which is okay for small meshes but gets impractical as number of polygons increases. I would suggest avoiding transparency if at all possible. Three.js does object sorting for you based on depth, but not polygons as that would essentially involve re-ordering geometry and not just draw order.

**Comment by benaadams** [comment]
@mikaat to get transparency to work for overlapping triangles within a mesh you have to do something like [Weighted, Blended Order-Independent Transparency](http://casual-effects.blogspot.co.uk/2015/03/colored-blended-order-independent.html) and use 2x RGBA16F float screen sized render targets, which is quite GPU memory bandwidth hungry.

**Comment by mikaat** [comment]
Ok, thanks for the information. I found this WebGL example that actually has fully functional transparency but I am not sure how they have implemented it. The skin, bones and organs seems to be separate objects and you can reveal them by moving the slider. So, it should be possible.  http://open-3d-viewer.googlecode.com/svn/trunk/web/index.html#nav=1.26,5.67,250

**Comment by mrdoob** [comment]
The guys that did that example know very well how WebGL and graphic cards work so they knew very well how to prepare the geometry. If you look carefully you can see glitches.

Things you can do are to split your object in different parts. One object per leg, even one object per finger. That will help the renderer to sort things.

In short, we can't sort triangles at render time (neither the graphics card). But we do sort objects at render time, so if you have glitchy transparent objects try breaking them apart.

**Comment by WestLangley** [comment]
> I found this WebGL example that actually has fully functional transparency but I am not sure how they have implemented it.

@mikaat Look at the source code. Only one layer is partially transparent. Every layer inside that layer is opaque. Every layer outside that layer is invisible.
