### ISSUE TITLE
error loading obj file

### ISSUE THREAD

**Issue by catdsnny** [mrdoob/three.js#6463]
current version, loading using the sample code, gets an error "cannot read property x" in minified code

chrome 42

win 7, 64 bit, high end nvidia card

just load up main.html and it gets the error

files can be found here:
http://96.56.225.196:8090/

main.html
obj and jpg

**Comment by WestLangley** [comment]
For one thing, this line is not correct:

    child.material.map = material;

**Comment by catdsnny** [comment]
If so, then someone might want to fix the obj loader example, because
that's where I got it from.

http://threejs.org/examples/#webgl_loader_obj

var loader = new THREE.OBJLoader( manager ); loader.load(
'obj/male02/male02.obj', function ( object ) {
object.traverse( function ( child ) {
if ( child instanceof THREE.Mesh ) {
child.material.map = texture;
}
} );
object.position.y = - 80; scene.add( object );
}, onProgress, onError );

**Comment by catdsnny** [comment]
And it might be helpful to explain why this is not correct and provide a correct example of how to load an obj - although the example does seem to work, so now the topic is pretty confused.

**Comment by benaadams** [comment]
> child.material.map = texture;
is setting the texture map of the material to a texture
> child.material.map = material;
is setting the texture map of the material to a material, which will cause an error
> child.material = material;
might work

**Comment by mrdoob** [comment]
> And it might be helpful 

Please, use [stackoverflow](http://stackoverflow.com/questions/tagged/three.js) for help.

**Comment by catdsnny** [comment]
cross posted to SO last night - no responses

**Comment by catdsnny** [comment]
Curious that I copied the example on how to load an obj file directly and
that example works.  That's the code straight off the three.js example
website.

**Comment by mrdoob** [comment]
> http://96.56.225.196:8090/

That doesn't load for me. Maybe that's why SO has no responses.

**Comment by catdsnny** [comment]
I deleted the NAT this morning after the question was closed on this
forum.  I think you can just close the question - it doesnt appear that
three.js is really appropriate for my project.

**Comment by mrdoob** [comment]
I agree 😉
