### ISSUE TITLE
Morph targets interpolation problem

### ISSUE THREAD

**Issue by jspdown** [mrdoob/three.js#6465]
Hi!

I have a strange effect when I use 9 morph targets on my mesh: vertex's interpolation is not always working.

I initialize all my morph targets influences to 0. If I put a value between 0 and 0.5, vertices position doesn't change But if put a value between 0.5 and 1, vertices are updated. 

An example with one target influence = 0.49:
![screen shot 2015-04-28 at 11 52 48 am](https://cloud.githubusercontent.com/assets/2843268/7367076/3d0f8486-ed9d-11e4-95c3-30400b2acd57.png)

With the same target but with influence = 0.5:
![screen shot 2015-04-28 at 11 53 00 am](https://cloud.githubusercontent.com/assets/2843268/7367079/4058f172-ed9d-11e4-85d1-143196cb8273.png)

With the same target but with influence = 0.8:
![screen shot 2015-04-28 at 11 53 18 am](https://cloud.githubusercontent.com/assets/2843268/7367084/46c24f2c-ed9d-11e4-8028-e8e79ada281e.png)

You can notice between the first and the second, vertices position change suddenly.

I noticed in the `morphtarget_vertex.glsl` file that THREE.js can handle only 8 target influences but I think this is not the only problem.

**Comment by jspdown** [comment]
I found something strange in `WebGLProgram.js` and `morphtarget_vertex.glsl`. The number of morphTargets attributes declared in this first file is not the same if as number used in the vertex shader.

Line 231 in `WebGLProgram.js`:
```
				'#ifdef USE_MORPHTARGETS',

				'	attribute vec3 morphTarget0;',
				'	attribute vec3 morphTarget1;',
				'	attribute vec3 morphTarget2;',
				'	attribute vec3 morphTarget3;',

				'	#ifdef USE_MORPHNORMALS',

				'		attribute vec3 morphNormal0;',
				'		attribute vec3 morphNormal1;',
				'		attribute vec3 morphNormal2;',
				'		attribute vec3 morphNormal3;',

				'	#else',

				'		attribute vec3 morphTarget4;',
				'		attribute vec3 morphTarget5;',
				'		attribute vec3 morphTarget6;',
				'		attribute vec3 morphTarget7;',

				'	#endif',

				'#endif',
```

And the shader:

```
#ifdef USE_MORPHTARGETS

	vec3 morphed = vec3( 0.0 );
	morphed += ( morphTarget0 - position ) * morphTargetInfluences[ 0 ];
	morphed += ( morphTarget1 - position ) * morphTargetInfluences[ 1 ];
	morphed += ( morphTarget2 - position ) * morphTargetInfluences[ 2 ];
	morphed += ( morphTarget3 - position ) * morphTargetInfluences[ 3 ];

	#ifndef USE_MORPHNORMALS

	morphed += ( morphTarget4 - position ) * morphTargetInfluences[ 4 ];
	morphed += ( morphTarget5 - position ) * morphTargetInfluences[ 5 ];
	morphed += ( morphTarget6 - position ) * morphTargetInfluences[ 6 ];
	morphed += ( morphTarget7 - position ) * morphTargetInfluences[ 7 ];

	#endif

	morphed += position;

#endif

```

By the way, I use THEE.js r71

**Comment by WestLangley** [comment]
three.js supports 8 morph targets, or alternatively, 4 morph targets combined with 4 morph normals.

**Comment by jspdown** [comment]
Ok, but There're too many morphTarget attributes created, isn't it? If I want to only want to use morph targets, no morph normals, 8 morphTarget attributes  are declared.

Do you have an idea how I could increase those numbers?

**Comment by WestLangley** [comment]
three.js supports a maximum of 8 morph targets.

**Comment by mrdoob** [comment]
Also, this is a limitation of WebGL itself and graphic cards. A morph target is an attribute and most graphic cards support only 16 at a time ([MAX_VERTEX_ATTRIBS](http://webglstats.com/))

**Comment by almeidais** [comment]
I currently have an avatar model with 25 morph targets and I am also facing the same interpolation problem, aside from interference between morphtargets (changing one would undesirably change others). Although there is a limitation from WebGL, theoretically, would three.js allow more than 8 morph targets to be used? Is there any way to expand this number?

**Comment by jspdown** [comment]
@almeidais You can't use more than 8 morph targets. This limitation is due to the GPU (more info on http://webglstats.com/). But, you can still compute some of them on your CPU. 
I got the same problem as you but in my case, it wasn't for animation purpose, so my solution may not be relevant for you. 

I split my morph targets in two groups:
- Morph targets that need to be updated frequently (max 8)
- Those that are mostly used for the initial configuration of the model and that aren't supposed to be updated. 

The first group runs on the GPU and the second on the CPU. I created a function that computes morphtargets on the CPU and then freezes the model and updates the number of available morphtargets to 8 (really heavy process).
I used this tricks to configure a human body that had ~32 morphtargets. Only 6 of them needed real-time updates, others were only used to pre-configure the model.

Here is an ugly example of how you can compute morph targets on the CPU. It's a pretty old code, I'm not sure it still work (I didn't try it since a year). It's just an example, you shouldn't use it:

```javascript
THREE.MorphTargetMesh.prototype.computeMorphTargets = function () {
  if (this.useGPUMorphTarget) {
    return;
  }

  var vertices = this.geometry.vertices;
  var morphTargets = this.geometry.morphTargets;

  var refVertice;
  var vertice;
  var targetVertices;
  for (var v = 0, vl = vertices.length; v < vl; v++) {
    refVertice = this.verticesReference[v];
    vertice = vertices[v];
    vertice.copy(refVertice);

    for (var t = 0, tl = morphTargets.length; t < tl; t++) {
      targetVertices = morphTargets[t].vertices;

      vertice.x += (targetVertices[v].x - refVertice.x) * this.morphTargetInfluences[t];
      vertice.y += (targetVertices[v].y - refVertice.y) * this.morphTargetInfluences[t];
      vertice.z += (targetVertices[v].z - refVertice.z) * this.morphTargetInfluences[t];
    }
  }
  this.geometry.verticesNeedUpdate = true;
};
```

`verticesReference` is a copy of all the vertices of the model

**Comment by s5g** [comment]
Any possibility of increasing the number of morph targets?

http://webglstats.com/webgl/parameter/MAX_VERTEX_ATTRIBS
http://webglstats.com/webgl2/parameter/MAX_VERTEX_ATTRIBS

Looks like 16 would have nearly 100% coverage.
