### ISSUE TITLE
blender json exporter exports wrong material index

### ISSUE THREAD

**Issue by jpcloud** [mrdoob/three.js#6468]
With a blender file containing 3 objects and 6 materials.
If you export object a, which uses the materials 0, 3, 4 and 5, you get a json file with:
4 materials (only the ones used by the object) but the exported faces (with their material index) go from 0 to 5.

This results in the following error:
THREE.WebGLRenderer 71
Uncaught TypeError: Cannot read property 'attributes' of undefined (three.js:17834)
  initMeshBuffers	
  initGeometryGroups	
  initObject	
  projectObject	
  projectObject	
  render	

(Upon trying to render with the exported and then loaded materials as the input to THREE.MeshFaceMaterials).

I have both tried the master and the dev exporter with the same result.
It's fine, that only the used materials are exported, but the material indexes for the faces need to reflect the skipping of unused materials.

Fixing the materialIndex properties of all faces before creating the mesh fixes the problem, but is of course impossible when it gets more complicated than just skipping materials 1,2 and 3.

Blend file: http://jppresents.net/static/blender/exportBug/trees.blend
resulting json (upon exporting the voilet tree, done with the dev exporter - notice the materialIndex values for the faces): http://jppresents.net/static/blender/exportBug/tree.json

**Comment by jpcloud** [comment]
I did notice now, that you can prevent that from happening, if you delete the unused materials from the blender object. (they will still be available for the other objects)

**Comment by repsac** [comment]
blend file is downloaded

**Comment by repsac** [comment]
Try this branch https://github.com/repsac/three.js/tree/6468

**Comment by jpcloud** [comment]
hi @repsac, I have downloaded the exporter from the linked branch, and can confirm: 
it fixes the problem.
Now the material indexes match the exported materials.
