### ISSUE TITLE
Geometry.fromBufferGeometry( ) does not support BufferGeometry with interleaved buffers

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#6471]
Example

    var bufferGeometry = new THREE.SphereBufferGeometry( 10, 16, 8 );

    var geometry = new THREE.Geometry().fromBufferGeometry(  bufferGeometry );

**Comment by benaadams** [comment]
Needs to use the [buffer getters](https://github.com/mrdoob/three.js/blob/dev/src/core/BufferAttribute.js#L175) rather than accessing the [array directly](https://github.com/mrdoob/three.js/blob/dev/src/core/Geometry.js#L103) want to assign to me?

**Comment by WestLangley** [comment]
You are on a roll, so why not? : - )

**Comment by benaadams** [comment]
A question though... is it an observation or an actual use? As converting it to geomerty will mean it actually goes Indexed InterleavedGeometry -> Geometry -> Non-Indexed Buffered Geometry

**Comment by WestLangley** [comment]
I was modifying `UVsDebug()` to support `BufferGeometry` (see #6470) like so:

    var geo = ( geometry instanceof THREE.BufferGeometry ) ? new THREE.Geometry().fromBufferGeometry( geometry ) : geometry;

I found that this approach does not work with `SphereBufferGeometry`.

**Comment by mrdoob** [comment]
Instead of over complicating `THREE.Geometry.fromBufferGeometry()` in #6475 I was suggesting to make sure the primitives output basic `THREE.BufferGeometry` by now.
