### ISSUE TITLE
examples/#vr_cubes no longer works on 72dev

### ISSUE THREAD

**Issue by sigmaxipi** [mrdoob/three.js#6479]
http://threejs.org/examples/#vr_cubes works properly for me (Chrome 42.0.2311.90 on Win7) but the dev72 version (95b8d491a17603f0c7c2f94746d4b53696866db5) doesn't work. It renders a single frame and then fails to update. The stats.js FPS meter continues to run and VREffect.render is called but the screen doesn't update.

**Comment by mrdoob** [comment]
Weird, it works fine here...

**Comment by mrdoob** [comment]
Wait... Should you be trying with Firefox Nightly or the Chromium VR build?

**Comment by sigmaxipi** [comment]
I was testing in the released version of Chrome to rule out instability in the VR versions of FF or Chromium. Now I understand the issue. The dev72 version doesn't have mouselook support like the public 71 version. That lack of idle animation and mouse hitdetection made me think it was nonresponsive. 

With FF Nightly 40.0a1 4-29, and the 43.0.2349.0 Chromium VR build, HMD tracking and HMD related hit detection work as expected. If there is no plan for mouselook, then this can be closed as user error.

**Comment by mrdoob** [comment]
Ah, I see. Well, that example doesn't really need mouselook. We probably removed the code to focus on what the example was about.
