### ISSUE TITLE
JSON loader bug

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#6489]
The bug is similar with the ColladaLoader one ( https://github.com/mrdoob/three.js/issues/6443 ),
but this time the animation works and the materials are messsed up:
http://necromanthus.com/Test/html5/girl2_JS.html 

The bottom line:

ColladaLoader
- a single material per skinned mesh (bones) ---> OK
- two materials per skinned mesh (bones) ---> mesh OK, animation does not work

JSONLoader
- a single material per skinned mesh (bones) ---> OK
- two materials per skinned mesh (bones) ---> animation OK, materials messed up

**Comment by getzelone** [comment]
Thank you for the code of json loader with skeleton animation (it's not in the documentation).
I'm looking also how to load the texture with the json model please ?

**Comment by RemusMar** [comment]
> Thank you for the code of json loader with skeleton animation (it's not in the documentation).
> I'm looking also how to load the texture with the json model please ?

http://necromanthus.com/Test/html5/girl_JS.html 
(a single material per mesh).
cheers

**Comment by getzelone** [comment]
thx :)

**Comment by RemusMar** [comment]
To the dev team:

I'm not the author of the ColladaLoader, But I found the fix for skinned mesh (bones) with multiple materials.

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/ColladaLoader.js 

replace line 1197: material.skinning = true;

with

						if ( num_materials > 1 ) {
							for ( j = 0; j < num_materials; j ++ ) {
								material.materials[j].skinning = true;
							}
						} else {
							material.skinning = true;
						}

You can see the working example now:
http://necromanthus.com/Test/html5/girl2.html 
cheers

**Comment by RemusMar** [comment]
Is seems the bug is not inside of the JSONLoader.
It's inside of the ThreeJSAnimationExporter.ms
The exported UVs are messed up in case of 2 or more materials per skinned mesh.

**Comment by AlexeyGapon** [comment]
JSONLoader exports mesh correctly only if your UV coordinates in UV quad.  Please chek this.

**Comment by RemusMar** [comment]
> JSONLoader exports mesh correctly only if your UV coordinates in UV quad. Please chek this.

Indeed.
Fixed: http://necromanthus.com/Test/html5/girl2_JS.html 
So the JSONLoader is ok.
The ThreeJSAnimationExporter.ms is buggy (limited).

cheers

**Comment by AlexeyGapon** [comment]
But sometimes it is importing animation with some broken skin weights. Or may be the exporter is wrong.
Model streches all over the screen.  
How did you fix that?

**Comment by RemusMar** [comment]
I use only the 3DS Max Biped and I didn't have any exporting issue (JSON or DAE).

**Comment by AlexeyGapon** [comment]
Me too. i have very similar problem like you with sea 3d exporter.
http://necromanthus.com/Test/html5/Lara_sea3d_bug1.html

But with all character. I am using Biped too.

**Comment by donmccurdy** [comment]
The 3DS Max JSON exporter has been removed (https://github.com/mrdoob/three.js/commit/61672d3f176477bd394102f72b73013e127de411#diff-3d338945e7435e7b2e3346c215cc2ed4) — it's best to use other workflows now.
