### ISSUE TITLE
Non-indexed triangle drawing doesn't support offsets/drawcalls

### ISSUE THREAD

**Issue by edankwan** [mrdoob/three.js#6490]
https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L2574

Please add the support like in other drawing methods.

**Comment by mrdoob** [comment]
I think this has already been added in the `dev` branch?

**Comment by edankwan** [comment]
Not yet, it is still hardcoded.
https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1136-L1185

**Comment by WestLangley** [comment]
@benaadams Is there any reason in principle why we can't implement this -- support `drawcalls` for non-indexed `BufferGeometry`?

Or do you think it is reasonable to require an `index` if a user wants to use `drawcalls`.

**Comment by WestLangley** [comment]
If we are only going to support `drawcalls` for indexed `BufferGeometry`, then I think we should create a separate `IndexedBufferGeometry` class.

**Comment by benaadams** [comment]
For non Instanced Geometries this should work: #6497 hopefully

I think that function needs some refactoring

**Comment by WestLangley** [comment]
OK, it looks like @benaadams has come to the rescue on this one. Thanks!

@edankwan And thanks for the suggestion!

**Comment by benaadams** [comment]
Also fixes #3857
