### ISSUE TITLE
#extension directives should be before any non-preprocessor tokens (standard derivatives)

### ISSUE THREAD

**Issue by jamiemadill** [mrdoob/three.js#6493]
ANGLE has a long standing bug where we would allow bad shaders with #extension directives after non-preprocessor tokens. After fixing this, we noticed it would break some three.js samples, for example, http://threejs.org/examples/webgl_materials_bumpmap_skin.html. This extends to other forks of three.js like xg.

I noticed in WebGLProgram.js, in the prefix_fragment section, you could place the #extension directive before the precision statements. If you fix this, and update the sample above, maybe that would fix this one particular instance.

For reference, the relevant section of the spec:

"[ESSL 1.0.17 pg 15]
Each extension can define its allowed granularity of scope. If nothing is said, the granularity is a single
compilation unit, and the extension directives must occur before any non-preprocessor tokens. If
necessary, the linker can enforce granularities larger than a single compilation unit, in which case each
involved compilation unit will have to contain the necessary extension directive."

The Chromium bug tracking these breaks: http://crbug.com/483252.

It would be nice if someone could take this up. Even if we can't make this change in Chrome very soon, it would be good to stop new demos and forks of the code from having the issue if we do get to the point where we can switch the validation on, to pass WebGL Conformance.

**Comment by mrdoob** [comment]
Should be now fixed.

**Comment by makc** [comment]
Is not. Ok, you could use `derivatives` property, but for any other extension that user would like to use, it would go after this chunk:
```glsl
uniform mat4 viewMatrix;
uniform vec3 cameraPosition;
```

**Comment by mrdoob** [comment]
Uhmm... can you elaborate?

**Comment by benaadams** [comment]
@makc you can always use ```THREE.RawShaderMaterial```

@mrdoob ```#extension GL_EXT_frag_depth : enable```? https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/logdepthbuf_pars_fragment.glsl

**Comment by makc** [comment]
@mrdoob 
>  can you elaborate

well they say we're not allowed to place any actual code before #extension things, but even if we put it on top of ShaderMaterial shaders, it still prepends a lot of stuff, so your way you would need to add separate flag for each and every possible extension that user might want to use.

@benaadams thanks for pointer.

**Comment by jamiemadill** [comment]
For what it's worth, ANGLE isn't likely going to enforce this validation. It would break too many apps, and on the desktop this particular rule isn't enforced either. Appreciate the fix to the existing extension code, but no need to do any more work for now from ANGLE's perspective.

**Comment by mrdoob** [comment]
> @mrdoob ```#extension GL_EXT_frag_depth : enable```? https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/logdepthbuf_pars_fragment.glsl

Oh! Interesting... Could you do a PR for that at some point? Otherwise I'll put it on my list.

> well they say we're not allowed to place any actual code before #extension things, but even if we put it on top of ShaderMaterial shaders, it still prepends a lot of stuff, so your way you would need to add separate flag for each and every possible extension that user might want to use.

@makc yep, use `RawShaderMaterial` while we keep adding more `derivatives` like properties.

**Comment by mrdoob** [comment]
> @mrdoob ```#extension GL_EXT_frag_depth : enable```? https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/logdepthbuf_pars_fragment.glsl

@benaadams Oh! Interesting... Could you do a PR for that at some point? Otherwise I'll put it on my list.

> well they say we're not allowed to place any actual code before #extension things, but even if we put it on top of ShaderMaterial shaders, it still prepends a lot of stuff, so your way you would need to add separate flag for each and every possible extension that user might want to use.

@makc yep, as @benaadams said, use `RawShaderMaterial` while we keep adding more `derivatives` like properties.

**Comment by titansoftime** [comment]
@mrdoob After updating to chrome 44, I am getting this

```
THREE.WebGLShader: gl.getShaderInfoLog() WARNING: 0:3: '
' : extension directive must occur before any non-preprocessor tokens 
 1: precision highp float;
2: precision highp int;
3: #extension GL_OES_standard_derivatives : enable
4: 
5: #define MAX_DIR_LIGHTS 1
6: #define MAX_POINT_LIGHTS 0
7: #define MAX_SPOT_LIGHTS 0
8: #define MAX_HEMI_LIGHTS 0
9: #define MAX_SHADOWS 1

....

```

Though nothing seems broken. Just a giant warning message (dump of phong shader) in console.

This can be seen in for example: http://threejs.org/examples/#webgl_materials_normaldisplacementmap

**Comment by WestLangley** [comment]
Yep. If you hack the shader in @spite's Chrome ShaderEditor like so, the warning is resolved:

    #extension GL_OES_standard_derivatives : enable

    precision highp float;
    precision highp int;

    #define MAX_DIR_LIGHTS 0
    ...

**Comment by mrdoob** [comment]
> @mrdoob After updating to chrome 44, I am getting this (in r71 and r72dev at least)

In r72dev too? Weird, it should be fixed already...
https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLProgram.js#L296-L299

**Comment by titansoftime** [comment]
Ok, my dev copy was a out of date. Looks fine in today's build.

**Comment by dderiso** [comment]
Updating fixed it for me!
