### ISSUE TITLE
OrbitControls right click problems.

### ISSUE THREAD

**Issue by Cruzzoide** [mrdoob/three.js#6499]
Hey everyone,
I'm new to Three.js and i'm trying to draw a scene in which i'm supposed to place multiple objects at different levels in the space. Objects must be clickable and some other stuff must be done. 

The problem I'm actually having is this one: I've implemented OrbitControls for the camera, but mouse's right click acts like left click. Instead of being draggable, camera keeps rotating like it's a left click. I've been searching around for a while and i haven't found much. 
Here's the code:

    if ( ! Detector.webgl ) Detector.addGetWebGLMessage();
	var container, stats; 
	var camera, scene, renderer, controls; 
	var raycaster, vector;
	var width = window.innerWidth;
	var height = window.innerHeight;	

	init();
	animate();

	function init() {
		camera = new THREE.PerspectiveCamera(45, width / height, 1, 10000);
		camera.position.set(0,160,400);
		
		scene = new THREE.Scene();
		scene.add(camera);

		/* RENDERER */
		if ( Detector.webgl )
			renderer = new THREE.WebGLRenderer( {antialias:true} );
		else
			renderer = new THREE.CanvasRenderer();
	
		renderer.setPixelRatio( window.devicePixelRatio );
		renderer.setSize( width, height );
		
		container = document.getElementById( 'container' );
		container.appendChild( renderer.domElement );

		/* CAMERA CONTROLS */
		controls = new THREE.OrbitControls(camera, renderer.domElement);
		
		/* BACKGROUND */
		var skyboxGeometry = new THREE.BoxGeometry(10000, 10000, 10000);
		var skyboxMaterial = new THREE.MeshBasicMaterial({ color: "white", side: THREE.BackSide });
		var skybox = new THREE.Mesh(skyboxGeometry, skyboxMaterial);
	 	scene.add(skybox);
		
		/* STATS */
		stats = new Stats();
		stats.domElement.style.position = 'absolute';
		stats.domElement.style.top = '0px';
		stats.domElement.style.zIndex = 100;
		container.appendChild( stats.domElement );
			
		/* WEB PAGE TITLE */
		var info = document.createElement('div');
		info.style.position = 'absolute';
		info.style.top = '10px';
		info.style.width = '100%';
		info.style.textAlign = 'center';
		info.innerHTML = '<a href="http://mininet.org/">Mininet</a> - SDN Emulation';
		container.appendChild (info);

		/* OBJECT PICKERS */	
		raycaster = new THREE.Raycaster();
		vector = new THREE.Vector2();
	
                /* some cubes creations */
		
		/* FLOOR */
		var faceMat = new THREE.MeshBasicMaterial({color: 0x888888,side: THREE.DoubleSide});
		var wireMat = new THREE.MeshBasicMaterial({color:0xaaaaaa,wireframe:true,transparent:true});
		var multiMat = [faceMat ,wireMat];

		var floor= THREE.SceneUtils.createMultiMaterialObject(new THREE.PlaneGeometry(1000, 1000, 10, 10),multiMat);
		floor.position.y = -3.125;
		floor.rotation.x = Math.PI / 2;
		scene.add(floor);		
		

		/* EVENT CATCHERS */
		// Catches a click on the scene
		document.addEventListener('mousedown', onDocumentMouseDown, true);
		document.addEventListener('touchstart', onDocumentTouchStart, false);	
		// Scene adapts to browsers' window size
		window.addEventListener('resize', onWindowResize, false);
	
	}

	/* On window resize */
	/* Scene's dimensions are adapted to browser's ones */
	function onWindowResize ( event ) {
		camera.aspect = window.innerWidth / window.innerHeight;
		camera.updateProjectionMatrix();
	
		renderer.setSize(window.innerWidth, window.innerHeight);
	}
	

	function onDocumentTouchStart (event) {
		event.preventDefault();
		event.clientX = event.touches[0].clientX;
		event.clientY = event.touches[0].clientY;

		onDocumentMouseDown(event);
	} 

	function onDocumentMouseDown (event) {
		event.preventDefault();				
		/* Here i tried to disable right mouse click to see if something happened
                if (event.button==2) {
			controls.rotate = false;
			controls.enabled = false;
		} */	

		vector.x = 2*(event.clientX / renderer.domElement.width)-1;
		vector.y = -2*(event.clientY / renderer.domElement.height)+1;
			
		raycaster.setFromCamera(vector,camera);
		var intersects = raycaster.intersectObjects(shapes);
	
		if (intersects.length > 0) {
			controls.enabled = false;
			/* other stuff happens when i click on an object: that actually works */
		}
	}
	function render() {	
		camera.lookAt(scene.position);
		renderer.render(scene,camera);
	}	
	
	function animate() {
		requestAnimationFrame(animate);
		render();
		if (controls.enabled===false)
			controls.enabled=true;
		controls.update();
		stats.update();
	}	

Does someone have any suggestion? I'm going crazy.
Thanks in advance. Greets! :D

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
