### ISSUE TITLE
Material ambient color

### ISSUE THREAD

**Issue by Virtual3D** [mrdoob/three.js#6501]
I use AssimpJSONLoader and can't find model's ambient color of materials in r71. Everything looks dark. In r68 it was ok.
Sorry 4 my English.

![1](https://cloud.githubusercontent.com/assets/12213617/7442706/eaf70a8c-f12c-11e4-83e0-38ce6f44c3c4.jpg)

**Comment by WestLangley** [comment]
`MeshPhongMaterial.ambient` has been removed. It was the "ambient reflectance of the material" -- that is, how the material reflects ambient light.

We now assume the material reflects ambient light the same way it reflects direct light, and that is specified by `MeshPhongMaterial.diffuse.`

**Comment by Virtual3D** [comment]
I have set in 3dsmax ambient for my models everywhere... If I change it to diffuse it will appear in js object? Now I can't see .diffuse property too. Maybe I'ts of online converter?... Ok I'll try.

**Comment by RemusMar** [comment]
> I have set in 3dsmax ambient for my models everywhere.

No need to do that.
By default, in 3DS Max "ambient" and "diffuse" are linked (locked).
"ambient" is needed only for self-illumination objects.
Otherwise, the ambient light will have the same effect for all the objects in scene.
If you need self-illumination in THREE, use something like:

object.material.emissive = new THREE.Color( 0.2, 0.2, 0.2 );

cheers

**Comment by DzzD** [comment]
**It seems to me a strange assumption that ambient == diffuse for two reasons :** 
 - ambient is part of the phong shading illumination model
 - it may be hard without ambient to correcly lighting some 3d scene 

For exampe : if you were looking Inside a building with spots light Inside it from the exterior, it may be necessary to tune ambient material color for interior and exterior

**Comment by Virtual3D** [comment]
object.material.emissive = new THREE.Color( 0.2, 0.2, 0.2 );

Ок, ".emissive", not ".diffuse". 
I have different ambient color values for all my models and their parts. And "emissive" is not exported from 3DS Max (or I can't find where to set it in 3DS Max). So now I have to set all ".emissive" values to all parts of models manualy :(

**Comment by RemusMar** [comment]
In 3DS Max always set diffuse to (255,255,255) for all the materials.
That will be exported as (1,1,1) in THREE.
The "ambient" color is ignored, so don't waste your time with that value ("locked" anyway).
In THREE you need to set manually the emissive value if you need self-illuminating model:
object.material.emissive = new THREE.Color( 0.2, 0.2, 0.2 );

Now for all those who don't understand the "ambient" value in 3DS Max.
These are from the 3DS max docs:

The ambient color map is not visible in viewports or renderings unless the level of ambient light is greater than default value of black. 
By default, in a Standard material the Diffuse Color map is applied to the Ambient Color as well.

I hope it's cristal clear now.
cheers

**Comment by Virtual3D** [comment]
Seems I have understood about 3DS Max. I have to set one value for all "ambient" colors in Max and not to change it for any model. :) And in THREE to find according value for global AmbientLight.
I just wanted models to look the same color and brightness in Max and in THREE scene.

**Comment by RemusMar** [comment]
To understand better the "ambient" value in THREE:

http://necromanthus.com/Test/html5/girl_JS.html 
var ambient = new THREE.AmbientLight( 0x606060 ); 

http://necromanthus.com/Test/html5/girl_JS_emissive.html 
var ambient = new THREE.AmbientLight( 0x000000 );
"colorEmissive"  : [0.2, 0.15, 0.10]

Clear enough isn't it?
cheers

**Comment by DzzD** [comment]
>The ambient color map is not visible in viewports or renderings unless the level of ambient light is greater than default value of black.

Yes inded, which is totally logical but you dont always want ambient light to be black, usually it will often be greater than 0

I only wanted to point out that : IMHO, a material named "phong" without ambient sounds really strange for me.

Also emissive and ambient color are not really related, emissive is more used to display modelised light (light emitter object), ambient to simulate special material that react differently on direct and indirect lighting

Below a simple sample showing how using differents ambient and diffuse color may help to produce specials effects/material : 

![ambienttest](https://cloud.githubusercontent.com/assets/12198339/7445011/1eac9de2-f1a0-11e4-85e1-2a0a2897b73d.png)

**Comment by RemusMar** [comment]
> IMHO, a material named "phong" without ambient sounds really strange for me.

You need "ambient" for a "Phong" material.
You need "normal" and "specular":
http://necromanthus.com/Test/html5/claire.html 

cheers

**Comment by DzzD** [comment]
pretty women :) (as a side note the background is blinking in IE11)

>You need "ambient" for a "Phong" material.
>You need "normal" and "specular"

Sorry, but I can't see the point, (indeed normal and specular are requiered too as for gouraud shading, only difference is perpixel normals or not). But finally does this mean you agree ?

Or did you think ambient is useless in phong material ?

NB.: I am really sorry to disturb, but as I use ThreeJS more and more (and I like it), it make me a little worry, because as far I can remember (3D studios or 3D engines Ambient have always been availables in materials)

**Comment by benaadams** [comment]
> Or did you think ambient is useless in phong material ?

That ambient is the effect of ```.color``` with ```THREE.AmbientLight```

**Comment by RemusMar** [comment]
> Or did you think ambient is useless in phong material ?

For now "ambient" and "diffuse" is the same thing in THREE.
Why do you argue with me if WestLangley said "MeshPhongMaterial.ambient has been removed."?
As I told the dev team several times before, "there is always room for better".
;)

**Comment by RemusMar** [comment]
> (as a side note the background is blinking in IE11)

It doesn't in Chrome, Firefox and Opera.
I don't use IE11 anyway ...
;)

**Comment by DzzD** [comment]
>Why do you argue with me if WestLangley said "MeshPhongMaterial.ambient has been removed."?

Sorry, but as I use ThreeJS I just want to help using my experience, and this requiere I give my opinion good or not, but yes It may not be the right thread ...  :/, 

I subscribed just few days ago to GitHuB... at some time we are all newbies ...

**Comment by RemusMar** [comment]
> (For the blinking it is related to render clear color I think,
> I got this problem, cant remember exacly but setting 0 to alpha clearcolor may help)

You should contact the Microsoft IE dev team to report the issue.
They are well know for not following the "global rules" in their products.
;)

**Comment by DzzD** [comment]
<trolling start> 10 years ago IE was 95% of users... at this time they was the rules.... in the 2000s it was even possible to embed directX (3D) in web browser(IE) ... so who have not follow the "global rules", this is a too loooong question that have been debated too much, but if someone sell 10 cars a year, do they are legitimate to explain to a company that sell 1000000 cars how they should do ?</trolling end>

**Comment by RemusMar** [comment]
> 10 years ago IE was 95% of users..

At this moment IE11 represents 1-2% of the market ...

**Comment by benaadams** [comment]
> At this moment IE11 represents 1-2% of the market ...

Depends on your market, IE11 on desktop its 25% (http://www.netmarketshare.com/) [58% for IE generally]

![capture](https://cloud.githubusercontent.com/assets/1142958/7445438/0e1b667e-f1ab-11e4-9b78-a1f794cb3eb9.PNG)

**Comment by RemusMar** [comment]
> Depends on your market, IE11 on desktop its 25% 

Ben,

It has nothing to do with MY market.
The internet is full of "sponsored and fake" statistics.
Let's forget about them.
Try to get the medium value of 100 more or less trusted statistics.
You may start with this one:
http://www.w3schools.com/browsers/browsers_stats.asp 

Less than 8% for ALL the Internet Explorer versions.
In any case (to close this subject), from the WebGL point of view, IE11 represents about 1-2%.

cheers

**Comment by DzzD** [comment]
>Depends on your market
Thanks as I did not dare to post this :)


But to be back to the topic there is no confusion for me between ambient, diffuse, specular and emissive color, they have different usage in 3D. If you only want to display a simple model this may work fine, you can by some workaround get fair results by tuning  emissive, lights or whatever but, IMO in lot of cases the lack of ambient color and or level will limit the possibilities of the 3d engine..

Something with en emissive color should always be visible even with no light on (ambient + spot + etc... == 0)

If you have a scene when you can turn off the light every object with emissive color will stay visible wich is wrong is they are not light source.

**Comment by WestLangley** [comment]
@DzzD 

`material.ambient` was the ambient reflectance of the material. For real-world objects, it should normally match `material.color`, the diffuse reflectance of the material. (Objects, after all, do not know where the photons came from.)

We chose to simplify the API, and hardwire `material.ambient` to match `material.color`. Consequently, `material.ambient` has been removed.

I understand you may want to implement special effects. Your work-around is to create a `ShaderMaterial` that replicates the `MeshPhongMaterial` (Blinn-Phong) illumination model, and then modify it to your liking.

Extending materials in this way is a bit tedious, but you can find [examples on stackoverflow](http://stackoverflow.com/questions/21928178/replicating-meshlambertmaterial-using-shadermaterial-ignores-textures).

**Comment by DzzD** [comment]
@WestLangley 
Thanks for this interresting replie, I did not want to achieve special effect for now, this was just a general meaning for ThreeJS

**Comment by DzzD** [comment]
Let me just conclude with the following and I will leave you quiet (for some time) :) sorry

**IMHO :**
Diffuse color/level : is when the light come from a straight line (known sources) and go back diffused
Ambient color/level : is when the light come from infinities sources (unknown locations) and go back diffused
Specular color/level : ligth come from a straight line and go back in straight line

Some real world materials may react differently when lightened with a direct or indirect light (ambient), but the main probleme I can see in this simplification is that people will have to take care or tune their materials outside of their 3d editor

**Comment by benaadams** [comment]
> Some real world materials may react differently when lightened with a direct or indirect light (ambient), but the main probleme I can see in this simplification is that people will have to take care or tune their materials outside of their 3d editor

If you are doing texturing however you probably want the colors of the texture * ambient light to be returned rather than a flat color? Also if you just want a flat color use ```.emissive``` and this will achieve that effect.

**Comment by RemusMar** [comment]
> the main probleme I can see in this simplification is that people will have to take care or tune their materials outside of their 3d editor

At this moment you need to edit every JS, DAE or OBJ file if you want the best results.
Not to mention that you need to create certain materials or to modify parameters at runtime.
Again: "there is always room for better".

cheers

**Comment by DzzD** [comment]
>At this moment you need to edit every JS, DAE or OBJ file if you want the best results.
> Not to mention that you need to create certain materials or to modify parameters at runtime.
> Again: "there is always room for better".

Yes that's what I do for now, manualy modifying the material, but it is possible to get the same render than you get in 3d studio (I managed to get exact same render result in 3DzzD than the 3DS scene model I exported from 3D Max in case nb.: only using blin material not special one), removing ambient component will just make it harder to do this in the futur.

**Comment by DzzD** [comment]
One good example could be skin :
You have nearly a flat pink ambient and when you put a direct light some other things may appears like blood vessel.

That may be the same for many translucent objects like banknotes.

**Comment by benaadams** [comment]
> You have nearly a flat pink ambient and when you put a direct light some other things may appears like blood vessel.

> That may be the same for many translucent objects like banknotes.

I think you have moved out of scope of the ```MeshPhongMaterial``` :)

**Comment by DzzD** [comment]
>The above "cute" girl is using normal maps (loaded with the OBJ container).
>Can you do that with the standard OBJ container?
>LOL

Hehe this a modification I needed and I've done too ^^ by adding "map_bump" pattern but using it as a normal map (not a bump)

NB.: note that it would be possible to make it automatic by detecting normal map (most blue) VS bump (grayscale)

**Comment by mrdoob** [comment]
> Below a simple sample showing how using differents ambient and diffuse color may help to produce specials effects/material : 

> ![ambienttest](https://cloud.githubusercontent.com/assets/12198339/7445011/1eac9de2-f1a0-11e4-85e1-2a0a2897b73d.png)

I'm aware of those special effects you can achieve (I used to use 3DSMAX in the past). But that's not how material behave in the real world, so we opted for simplifying the API so people have less things to "learn" and, at the same time, there are less thing for us to maintain.

**Comment by DzzD** [comment]
I understand the desire to make the API as simple as possible (I really had the same goal in the past), but this may cause unwanted sides effects that will requiere more works for ThreeJS users, like need to rework materials after export from a 3D modeler, 

Maybe a middle solution is possible as keeping ambient but using diffuse if it is not defined.?

**Comment by tistatos** [comment]
I must say I also find this to be a very weird decision to remove ambient coefficients seeing they are part of many illuminations models. Especially since it was implemented previously?

And I understand what you mean with how materials behave in the real world, but isn't that part of the beauty of computer graphics? It doesn't have to be real life! :smile:

**Comment by Wilt** [comment]
As @WestLangley said they tied `material.ambient` by default to match `material.color`. So if a middle way is chosen I'd say it would be easy right?

````
THREE.MeshBasicMaterial = function ( parameters ) {
    //...
    this.color = new THREE.Color( 0xffffff ); // emissive
    this.ambient = this.color;
    //...
}

Or would that not have the same optimizing effect?

**Comment by Wilt** [comment]
In openGL materials also have different ambient, diffuse, and specular colors ([link](http://www.glprogramming.com/red/chapter05.html)). As I understood from others also 3DMax allows different ambient and diffuse colors. And like I said also my model definition also holds different ambient and diffuse color definitions. 

It seems sad that something which was working well for lots of people is removed from the library because of the sake of simplifying the API.

Can the API not be simplified without losing the possibility to set ambient for those who use it?

**Comment by mrdoob** [comment]
> Can the API not be simplified without losing the possibility to set ambient for those who use it?

We tried. It confused people more people than actual people used it. Doesn't follow the real physical world. Ultimately people want to have realistic renders. Eventually, I think `MeshLambertMaterial` and `MeshPhongMaterial` will move out of core so we can focus on `MeshStandardMaterial`. Maybe then we can add `ambient` back for people that want to continue using old lighting models.

I understand it's sad that things get removed. A way to make sure things don't get removed is by helping with user support. If I see there is something problematic that new users are struggling for and no one helping them then I have two options, put the library development on hold so I can help these users, or remove what they're struggling with. Putting the library on hold is dangerous (I could get burned out), so I give priority to not doing that.

**Comment by mrdoob** [comment]
> I would really like to be able to set ambient again in my materials so I can set the materials exactly as defined in my model.

Maybe you can just build the `ShaderMaterial` that goes with your model.

**Comment by Wilt** [comment]
@mrdoob I will look into that...

But is doing `this.ambient = this.color` no option at all?

**Comment by mrdoob** [comment]
> Hope you won't remove `MeshLambertMaterial` and `MeshPhongMaterial` though!

In the future they most likely be moved to the `examples` folder. `MeshStandardMaterial` follows more closely how materials look in the real world and it'll be more easy for people to learn and achieve convincing results.

**Comment by Wilt** [comment]
@mrdoob I try where I can to help [with user support](http://stackoverflow.com/search?q=user%3A1697459+%5Bthree.js%5D). But to be honest I am no expert either and I actually have no clue [how to fix my broken `ambient` effect](http://stackoverflow.com/questions/34773168/three-js-r71-ambient-removed-how-configure-to-get-same-rendering-results).
