### ISSUE TITLE
shadowmap practical usage

### ISSUE THREAD

**Issue by j3zusla** [mrdoob/three.js#6506]
hello,

I have been working with three.js shadows lately and it came to my attention when an object uses both 
castShadow = true and receiveShadow = true, the object becomes shaded with its own shadow. It is the expected behavior, but the object shadow gets out of control and the object does not appear natural! Would it be clever to add a third Shadow property on the object such as receiveOwnShadow=true||false that would get the expected behavior without tempering the object itself nor the performance?

Cordially,
J3zusla

**Comment by RemusMar** [comment]
Indeed, self-shadowing does not work properly in THREE.
It should be disabled by default.

**Comment by RemusMar** [comment]
In THREE self-shadowing gives decent results only in some particular cases:
- spot light centered on object
- non-animated object
- static lighting
- high-res shadowMap

Example: http://necromanthus.com/Test/html5/claire_self-shadowing.html 

Unfortunately, in the "real world" this is a rare case ...

**Comment by titansoftime** [comment]
Check this out: #6420

**Comment by j3zusla** [comment]
I have experienced poor results on low polys meshs that uses imagemap for rendering object details:

object OK -- receiveShadow = false
http://multivers3d.fr/constructor/users/51184/site/bug/Thumbz/1.png

object NOT OK  -- receiveShadow = true
http://multivers3d.fr/constructor/users/51184/site/bug/Thumbz/2.png
(you can see the object(flower) is darker and the low poly mesh pattern is revealed )

**Comment by rgupta1983** [comment]
hi Guys Kevin / j3zusla,

i need some help about a project of mine,in practical approach of three.js .


could i contact you guys,

Rahul
rgupta1983@gmail.com

**Comment by mrdoob** [comment]
Unfortunately, with the current technique used for shadow mapping (nor any other technique I'm aware of), there is no way for an object to know if the shadow is from itself or from another object.
