### ISSUE TITLE
Can't compile three.js

### ISSUE THREAD

**Issue by playerro** [mrdoob/three.js#6513]
Hi! I used this: https://github.com/mrdoob/three.js/wiki/build.py,-or-how-to-generate-a-compressed-Three.js-file but I can't compile it at my Windows 8.
I don't understand what options need to include and how - wrote at notepad C:\html\threejs\utils\build\build.py --all it wrotes error:
C:\html\threejs\utils\build>C:\html\threejs\utils\build\build.py --all
usage: build.py [-h] --include INCLUDE [--externs EXTERNS] [--amd] [--minify]
                [--output OUTPUT] [--sourcemaps]
build.py: error: the following arguments are required: --include

When I write C:\html\threejs\utils\build\build.py --include common it wrote :
C:\html\threejs\utils\build>build_threejs_all.bat
C:\html\threejs\utils\build>C:\html\threejs\utils\build\build.py --include commo
n
 * Building ../../build/three.js
Traceback (most recent call last):
  File "C:\html\threejs\utils\build\build.py", line 107, in <module>
    main()
  File "C:\html\threejs\utils\build\build.py", line 60, in main
    with open(filename, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../src/Three.js'

but this file is in directory threejs. How to compile three.js? Maybe I can download full, minified with canvas version with all components, without compiling?

**Comment by dubejf** [comment]
I haven't tried the python version, but I'm able to build `three.js` on Windows 8 using the javascript version of the build tool:
1. Install `node.js`
2. `node build.js ... (same arguments) ... `

**Comment by mrdoob** [comment]
What version of Java do you have?

**Comment by WestLangley** [comment]
> Maybe I can download full, minified with canvas version with all components, without compiling?

You can.

https://github.com/mrdoob/three.js/tree/master/build // library
https://github.com/mrdoob/three.js/tree/master/examples/js/renderers // CanvasRenderer

**Comment by playerro** [comment]
"What version of Java do you have?"
Downloaded last version.
"1. Install node.js
2. node build.js ... (same arguments) ..."
Can u write more information? I didnt work with node.js and don't know how to use it.

**Comment by dubejf** [comment]
The arguments are listed in the `build.bat` file and on the wiki.

You only need Java if you build the minified version (`three.min.js`, using the --minify command line option).

There are two equivalent (as far as I know) scripts that can compile `three.js`. From the `utils/build` directory, you can compile `three.js` using `python`

```
python build.py --include common --include extras --output ../../build/three.js
```

or `node`

```
node build.js --include common --include extras --output ../../build/three.js
```

If you go the `node` route, you will need to first install additional dependencies by calling `npm install` in `utils/build`. This step was not listed in the wiki - I just added it.

**Comment by playerro** [comment]
C:\Users\Володя>cd C:\html\threejs\utils\build
C:\html\threejs\utils\build>build_threejs_all.bat
C:\html\threejs\utils\build>C:\html\threejs\utils\build\build.py --include --ext
ras --include canvas --include webgl --include svg --include dom
usage: build.py [-h] --include INCLUDE [--externs EXTERNS] [--amd] [--minify]
                [--output OUTPUT] [--sourcemaps]
build.py: error: argument --include: expected one argument

C:\html\threejs\utils\build>build_threejs_all.bat

C:\html\threejs\utils\build>C:\html\threejs\utils\build\build.py --include extra
s --include canvas --include webgl --include svg --include dom
 * Building ../../build/three.js
Traceback (most recent call last):
  File "C:\html\threejs\utils\build\build.py", line 107, in <module>
    main()
  File "C:\html\threejs\utils\build\build.py", line 60, in main
    with open(filename, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../src/extras/Geomet
ryUtils.js'

I understood that he can't find directory, but all directories of three.js(downloaded from github) are here.

**Comment by playerro** [comment]
"https://github.com/mrdoob/three.js/tree/master/build // library
https://github.com/mrdoob/three.js/tree/master/examples/js/renderers // CanvasRenderer"
Its not a full three.js - only 200 kb main part, I need it all.
And I really can't compile it - there are no good step instructios, and there are no example for parametres in .bat document - to use  "--include canvas" or "--canvas"?

**Comment by dubejf** [comment]
Look at the source for any example in the canvas section: http://threejs.org/examples

There is no need to compile anything if you don't plan on modifying the core library. If you just want to use the library as-is, simply drop the pre-compiled file (`three.js` or `three.min.js`) on your server. The `canvasRenderer` is not included in the core library. You need to add this file separately to your `index.html`.

1. Download the pre-compiled "core" library: `build/tree.js`.
2. Download the additional file(s): `examples/js/renderers/CanvasRenderer.js`.
3. Edit your `index.html`:
```
		<script src="path/to/three.js"></script>
		<script src="path/to/CanvasRenderer.js"></script>
```

**Comment by playerro** [comment]
"   <script src="path/to/three.js"></script>
        <script src="path/to/CanvasRenderer.js"></script>"

Seriously? But if I need to include 20 files from examples I need to write 20 <script tags>?

**Comment by dubejf** [comment]
You don't have to - that's up to you. There are plenty of tools (gulp, grunt, ...) to bundle and minify your javascript files into a single script.

**Comment by dubejf** [comment]
This Issue can be closed. The build tools work as expected.
