### ISSUE TITLE
Guide of Blender Export Script

### ISSUE THREAD

**Issue by Rubiyooo** [mrdoob/three.js#6514]
Hi i´ve been using Blender for during 4 weeks (Blender 2.73 and Exporter v71) and i´m confused with several things of this Blender´s exporters. I´m looking and reading a lot of tutorials, documents and videos but is difficult.

Sometimes i read that is recommended to export selecting the bones and the mesh or only the mesh.

Other times that is requiered to do reset transform, rotation and scale or export the Armature in Pose Position or Rest Position. 

And in the official F.Q.A about How to use Blender export script in Blender is break-down https://github.com/mrdoob/three.js/issues/closed#issue/143

I don´t know what is the best way to export and i would like several recommendations.

I would like to exports mocaps, morph targets and progress with Three.js
But is hard when you don´t see any skinning in Threejs.org/editor or see a big pink triangle.

Or maybe when select Embed Animation or  what is Frame index as time.

Sorry by my english and thanks in advance.

**Comment by mrdoob** [comment]
I think they're still trying to figure out what's the best workflow.

**Comment by Rubiyooo** [comment]
Thanks by your fast respond mrdoob. Then do you know any example that works with the last exporter?
And do you meet any community or persons that are testing the last exporter with Blender 2.73?

Thanks and regards from Spain.

**Comment by repsac** [comment]
> Sometimes i read that is recommended to export selecting the bones and the mesh or only the mesh.

This applied to the old exporter, for the time being (with the current one) you have to select the mesh.

> or export the Armature in Pose Position or Rest Position.

This is a necessary evil for the time being. As @mrdoob said there still isn't an understanding of what the preferred workflow should be. 

> community or persons that are testing the last exporter with Blender 2.73?

Come again? We are beyond testing as lots of people are actively using the exporter (except for some corner cases concerning animation scenes). Not sure what the concern is over version 2.73 specifically is but all the initial development was done with 2.73 and I haven't seen any issues yet with 2.74, tho I haven't been exporting much with it either.
