### ISSUE TITLE
Uncaught TypeError: Cannot read property '1965' of undefined

### ISSUE THREAD

**Issue by estock** [mrdoob/three.js#6515]
I am trying to use the Maya exporter to export a model with animation. I've tried a number of differnt times to export the model to a js file and then load it into Three. Does anyone have any idea why I might be getting this error 

Uncaught TypeError: Cannot read property '1965' of undefined

Is there a guide to exporting maya files and getting them to work inside three.js

**Comment by charleserious** [comment]
same issue
Uncaught TypeError: Cannot read property '0' of undefined

**Comment by WestLangley** [comment]
If you are not certain it is a three.js bug, we prefer you first seek help on stackoverflow.
