### ISSUE TITLE
Loading Texture with encoded Data retains previous pixels (in Chrome)

### ISSUE THREAD

**Issue by saadfaisal** [mrdoob/three.js#6520]
Hi , this issue is in reference to suggestion made by @mrdoob on #3430.

Hi Everyone , I am doing an svg designer that generates 3D Preview of the design using JSModeler and ofcourse Three.js. I am generating the preview of my design from a standard SVGToPNG solution available all over the web , that uses <canvas> to generate & render the image. The image data comes in as base64 encoded. 

In order to generate the relevant texture out of my image, i use the approach suggest by @mrdoob which is 

```
var image = document.createElement( 'img' );
var texture = new THREE.Texture( image );
image.onload = function()  {
    texture.needsUpdate = true;
        ...
};
image.src = 'data:image/png;base64,XXXXX';
```

however as the svg designer, user is free to move around the components on the screen so when the user attempts to preview their changes , they are seeing components that were moved not only on the new location but they also see them on their previous location.Please refer to the image below

![preview_overlap_issue](https://cloud.githubusercontent.com/assets/2168025/7514900/6257a170-f4db-11e4-9d11-bbf8714a3a69.jpg)

Here you can see that when the user attempts to move around the image , they are seeing a ghosting effect , how can i stop this behavior ?? any ideas ? Here is code that i have written

```
        var prev_img = $('#preview-img')[0];
        var image = document.createElement( 'img' );
        var mapSprite = new THREE.Texture( image );

        image.onload = function() {
            mapSprite.needsUpdate = true;
            var material = new THREE.MeshBasicMaterial( { map: mapSprite, transparent: true } );

            var bbox_head = head.geometry.boundingBox;

            var w = bbox_head.max.x - bbox_head.min.x;
            var h = bbox_head.max.z - bbox_head.min.z;

            var geo1 = new THREE.PlaneGeometry( w, h, 10 , 10 );
            var mesh = new THREE.Mesh( geo1, material);
            mesh.rotateZ(DegToRad(180));
            mesh.rotateX(DegToRad(90));
        }

        image.src = $(prev_img).attr('src');
```

**Comment by bhouston** [comment]
I believe you are just not deleting the previous geometry, rather you are adding more geometry every time the image.onload is called.

**Comment by saadfaisal** [comment]
No that is not the case , actually i am using JSModeler for all the Three.js related initialization , and JSModeler's Viewer object is being used to manage all the Three.js meshes

````
viewer.RemoveMeshes
````

has been invoked at the relevant section of the code. However i am just trying to understand whether is there any chance that 
````
mapSprite.needsUpdate = true;
`````
could this be the case that is keeping this texture or memory area alive for some reason and somehow getting reused on every attempt, just curious ?

**Comment by mrdoob** [comment]
Can you create a [jsfiddle](http://jsfiddle.net/) that shows the issue?

**Comment by saadfaisal** [comment]
Sorry for the delay , however i am still unable to create the fiddle as i am knee deep in the live project. However i have noticed that this happends only with chrome and Firefox doesnt show any such behavior , i will try to create a fiddle as soon as i get sometime.

**Comment by benaadams** [comment]
Are you loading the image from a different domain than the page?

**Comment by saadfaisal** [comment]
nope , the image is a simple conversion of a an SVG node to a PNG using the base64 encoding method. something like this

````
var svg = document.querySelector( "svg" );
var svg_clone = $(svg).clone();
var svg_clean = SVGCleanup(svg_clone);
var svgData = new XMLSerializer().serializeToString( svg_clean );
var img = $('#preview')[0];

img.load = function() {
            var canvas = document.createElement( "canvas" );
            var ctx = canvas.getContext( "2d" );

            console.log('img.onload::> '+ img.width+'::'+img.height);

            canvas.width = img.width;
            canvas.height = img.height;    

           ctx.drawImage( img, 0, 0 );
        };
        
$(img).attr('src','data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent( svgData ))));
`````

hope this helps.

**Comment by WestLangley** [comment]
Please provide a test case, along with the information requested in "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by Mugen87** [comment]
Closing. We can reopen the issue when a test case is provided.
