### ISSUE TITLE
How to use 3d object as slider ?

### ISSUE THREAD

**Issue by mtconcepts** [mrdoob/three.js#6525]
Hello,

I want to use sphere as slider.Want to use its y position to rotate value of bone.

Any reference awailable?

Plz share..
Thank you

**Comment by cjonasw** [comment]
Could you give a bit more detail?

**Comment by mtconcepts** [comment]
Thank you,

I have human tounge model and attach with 6 bones.I have put a small sphere on toung tip and drag sphere in 3d space.I have give sphere y position to Bone 4,5,6 to set rotation values.it works ..according to sphere y position tounge tip move up and down but my problem is that toung tip not move along with sphere.means sphere not stay on toung tip..
Thank you

**Comment by mtconcepts** [comment]
Thank you,

I have human tounge model and attach with 6 bones.I have put a small sphere on toung tip and drag sphere in 3d space.I have give sphere y position to Bone 4,5,6 to set rotation values.it works ..according to sphere y position tounge tip move up and down but my problem is that toung tip not move along with sphere.means sphere not stay on toung tip..
Thank you

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
