### ISSUE TITLE
Blender exporter, enhancements and bugs

### ISSUE THREAD

**Issue by inkfood** [mrdoob/three.js#6529]
I recently played a lot with the current r71 Blender exporter, there are a few things I stumbled across. 
- Exporting buffer geometry dosent't compile a correct json file, it misses a "data" attribute. Which later in the loading process cause an error.  
  ![screenshot](https://cloud.githubusercontent.com/assets/8083536/7549625/fc7c71b4-f63d-11e4-9b4f-1be71eaf60cb.png)
- If you are in Blender and in edit mode while exporting, the script throws an error -> Can't apply the Triangulate modifier in edit mode. The exporter has to make sure that Blender is in Object mode, if not switch to Object mode.
- I can not export a scene which contains animations, the scene will be exported except for the animations. It doesn't matter if it's a bone or keyframe animation. 
  Might be cool to export a scene with animation data.
  It seems there are a lot of things which not work correctly with the scene exporter, like vertex colors or multi material objects. 
- there is a shadeless material button in the Blender material panel, would be nice if it exports that material value as well
- export Flat and Smooth shading type as well

I :heart: three JS, great work

**Comment by repsac** [comment]
> Exporting buffer geometry dosent't compile a correct json file

This is with geometry exports only and had been working so it seems a  recent commit broke this.

**Comment by repsac** [comment]
Buffer geometry fix will be included when this branch is merged
https://github.com/repsac/three.js/tree/uv_optimization

Awaiting some potential feedback on this thread https://github.com/mrdoob/three.js/issues/6556

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
