### ISSUE TITLE
Incorrect calculation BoundingBox

### ISSUE THREAD

**Issue by Ni55aN** [mrdoob/three.js#6534]
If any of the second triple of parameters BoxGeometry is defined as a string, then the BoundingBox is wrong but the geometry is correct

http://jsfiddle.net/VsWb9/3507/

**Comment by mrdoob** [comment]
Uh... Why are you defining it as a string?

**Comment by Ni55aN** [comment]
I got the value from <input type="number"> using jQuery, but did not realize that it returns a string, even though the geometry is generated correctly. I of course use parseFloat / parseInt (after a two-hour search of the reason) but others in the future in such a situation may have difficulty

**Comment by mrdoob** [comment]
This is just a problem of JavaScript itself. If we went down this route we'll have to type-check EVERYTHING in the library and that'll slow down things and make the code less readable :(
