### ISSUE TITLE
canvas panorama : next image 

### ISSUE THREAD

**Issue by vbx** [mrdoob/three.js#6542]
Hello, what is the best practice for display next panorama ? (change images) 
like this ? 

Event click button ->
var materials = [

                        loadTexture( 'PANO_NEXT0001.jpg' ), // right
                        loadTexture( 'PANO_NEXT0003.jpg' ), // left
                        loadTexture( 'PANO_NEXT0004.jpg' ), // top
                        loadTexture( 'PANO_NEXT0005.jpg' ), // bottom
                        loadTexture( 'PANO_NEXT0000.jpg' ), // back
                        loadTexture( 'PANO_NEXT0002.jpg' )  // front

                    ];

scene.remove(scene.children[0]);
mesh = new THREE.Mesh( new THREE.BoxGeometry( 300, 300, 300, 7, 7, 7 ), new THREE.MeshFaceMaterial( materials ));
                    mesh.scale.x = - 1;
                    scene.add( mesh );

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
