### ISSUE TITLE
Raycaster intersection.point sometimes off

### ISSUE THREAD

**Issue by hulf** [mrdoob/three.js#6547]
What I'm trying to do is to make a random generated terrain flora. 
When trying to get the intersection point, it gets off when going farther away from 0,0,0.

considering that I don't temper with scale, I can't figure out what is wrong. 
![a1](https://cloud.githubusercontent.com/assets/10427535/7581098/f2ec0b12-f87e-11e4-875d-6f54211eb0b9.jpg)

I tried to to change the terrain resoluton ( subdivide),
updating scene world matrix,
I didn't temper with scale, since it gives me wrong results even if I update world matrix or run the renderer few times before checking intersections.

Thanks.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
