### ISSUE TITLE
How add scales to GridHelper

### ISSUE THREAD

**Issue by jperezmedina** [mrdoob/three.js#6549]
I modified the GridHelper file to permit different size of axis X and Y.
I'm interested in add text scales without reduce the performance in create a lot of text.

Thanks for the ideas !

Jorge

``` javascript
/**
 * @author Jorge Luis PEREZ MEDINA / http://jperezmedina.eu/
 */

THREE.GridHelper = function ( sizeX, sizeY, step) {

    var x = Math.round(sizeX/step);
    var y = Math.round(sizeY/step);

    sizeX = x*step;
    sizeY = y*step;

    var geometry = new THREE.Geometry();
    var material = new THREE.LineBasicMaterial( { vertexColors: THREE.VertexColors } );

    this.color1 = new THREE.Color( 0x444444 );
    this.color2 = new THREE.Color( 0x888888 );

    for ( var i = 0; i <= sizeX; i += step ) {

        geometry.vertices.push(
            new THREE.Vector3( i, 0, 0 ), 
            new THREE.Vector3( i, 0, sizeY )
        );

        var color = i === 0 ? this.color1 : this.color2;

        geometry.colors.push( color, color, color, color );

    }

    for ( var i = 0; i <= sizeY; i += step ) {

        geometry.vertices.push(
            new THREE.Vector3( 0, 0, i ), 
            new THREE.Vector3( sizeX, 0, i )
        );

        var color = i === 0 ? this.color1 : this.color2;

        geometry.colors.push( color, color, color, color );

    }

    THREE.Line.call( this, geometry, material, THREE.LinePieces );

};

THREE.GridHelper.prototype = Object.create( THREE.Line.prototype );

THREE.GridHelper.prototype.setColors = function( colorCenterLine, colorGrid ) {

    this.color1.set( colorCenterLine );
    this.color2.set( colorGrid );

    this.geometry.colorsNeedUpdate = true;

}
```

**Comment by mrdoob** [comment]
I'm not sure what it is that you changed here...

**Comment by jperezmedina** [comment]
Hi, 

I only changed the way how the grid is displayed. Currently I can display the grid as a rectangle. Before it was considered only a coordinate to make only squares. Here the old code: https://github.com/mrdoob/three.js/blob/master/src/extras/helpers/GridHelper.js

Mi question is how add text scales for the new GridHelper that considers the grid as rectangles.

**Comment by Usnul** [comment]
I would suggest having stepX and stepY.

**Comment by ths126** [comment]
Great Idea, i think its sizeX and sizeZ not Y and i support Usual's idea as well.

**Comment by ths126** [comment]
code suggestion:
THREE.GridHelper = function (sizeX, stepX, sizeZ, stepZ) {
    var x = Math.round(sizeX / stepX);
    var y = Math.round(sizeZ / stepZ);

	sizeX = x * stepX;
	sizeZ = y * stepZ;

	console.log("Grid sizeX: " + sizeX * 2);
	console.log("Grid sizeZ: " + sizeZ * 2);

	var geometry = new THREE.Geometry();
	var material = new THREE.LineBasicMaterial({ vertexColors: THREE.VertexColors });

	this.color1 = new THREE.Color(0x444444);
	this.color2 = new THREE.Color(0x888888);

	for (var i = -1 * sizeX; i <= sizeX; i += stepX) {
	    geometry.vertices.push(
            new THREE.Vector3(i, 0, -1 * sizeZ), //x Y z
            new THREE.Vector3(i, 0, sizeZ) //x Y z
        );

	    var color = i === 0 ? this.color1 : this.color2;

	    geometry.colors.push(color, color, color, color);
	}

	for (var i = -1 * sizeZ; i <= sizeZ; i += stepZ) {
	    geometry.vertices.push(
            new THREE.Vector3(-1 * sizeX, 0, i), //x Y z
            new THREE.Vector3(sizeX, 0, i) //x Y z
        );

	    var color = i === 0 ? this.color1 : this.color2;

	    geometry.colors.push(color, color, color, color);
	}

	THREE.Line.call(this, geometry, material, THREE.LinePieces);
};

THREE.GridHelper.prototype = Object.create( THREE.Line.prototype );
THREE.GridHelper.prototype.constructor = THREE.GridHelper;

THREE.GridHelper.prototype.setColors = function( colorCenterLine, colorGrid ) {

	this.color1.set( colorCenterLine );
	this.color2.set( colorGrid );

	this.geometry.colorsNeedUpdate = true;

}
