### ISSUE TITLE
NPM landing page needs to be updated

### ISSUE THREAD

**Issue by deathbearbrown** [mrdoob/three.js#6550]
I was just installing Three through npm and noticed that the code snippet and the JS fiddle at the end of the page is using THREE.CanvasRenderer. https://www.npmjs.com/package/three

You'll see this warning in the console: 
`"THREE.CanvasRenderer has been moved to /examples/js/renderers/CanvasRenderer.js"`

It should probably be updated to use:  `renderer = new THREE.WebGLRenderer();`
Fixed fiddle: https://jsfiddle.net/9sp1hqvb/

The script on the page should also have that fix:
```
<script>
 
    var camera, scene, renderer;
    var geometry, material, mesh;
 
    init();
    animate();
 
    function init() {
 
        camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 1, 10000 );
        camera.position.z = 1000;
 
        scene = new THREE.Scene();
 
        geometry = new THREE.BoxGeometry( 200, 200, 200 );
        material = new THREE.MeshBasicMaterial( { color: 0xff0000, wireframe: true } );
 
        mesh = new THREE.Mesh( geometry, material );
        scene.add( mesh );
 
        renderer = new THREE.WebGLRenderer();
        renderer.setSize( window.innerWidth, window.innerHeight );
 
        document.body.appendChild( renderer.domElement );
 
    }
 
    function animate() {
 
        // note: three.js includes requestAnimationFrame shim 
        requestAnimationFrame( animate );
 
        mesh.rotation.x += 0.01;
        mesh.rotation.y += 0.02;
 
        renderer.render( scene, camera );
 
    }
 
</script> 
```

If you're installing for the first time, this would be super confusing. 

Sorry if this issue is a duplicate. I searched but didn't find anything about this.

**Comment by MusicalCreeper01** [comment]
3 months and this still hasn't been fixed? This was just causing issues for me. Please update @mrdoob

**Comment by fractma** [comment]
@bhouston how I can help you with this?

**Comment by bhouston** [comment]
Can someone just do a PR fix for the template in the utils/npm directory?
All the code for npm piblsihjng is in this repo.

Best regards,
Ben Houston
http://Clara.io Online 3d modeling and rendering

**Comment by mrdoob** [comment]
I searched for `CanvasRenderer` in [utils/npm](https://github.com/mrdoob/three.js/tree/dev/utils/npm) and didn't find any result...?

**Comment by bhouston** [comment]
Everything with the npm is auto-generated as much as possible.  What the npm build.js script does it grab the current Three.js readme from here:
https://github.com/mrdoob/three.js/blob/dev/utils/npm/build.js#L16

And copy it into the NPM directory:
https://github.com/mrdoob/three.js/blob/dev/utils/npm/build.js#L84

So basically this isn't working.  I'll have a look this evening.

**Comment by bhouston** [comment]
It should all be updated now:

https://www.npmjs.com/package/three

**Comment by mrdoob** [comment]
Yay! Thanks!
