### ISSUE TITLE
FirstPersonControls default lookAt issue

### ISSUE THREAD

**Issue by podelo** [mrdoob/three.js#6551]
Hello guys,

I m using FirstPersonControls.js inside my project, and I just want to set a default lookAt position to my camera.

For example, I set the camera's position which is located at 10,5,10 and I look at a cube which is located at others x, y, z.
When I do this, when I make the first move with my mouse to look around my position, the problem is that the camera doesn't start looking around from the exact position I m looking at. 

To make you guys understand better, I've looked at webgl_shadow_performance's source code (http://threejs.org/examples/#webgl_shadowmap_performance) and I noticed that longitude and latitude are hardcoded, respectively set to 250 and 30. 
So, on this example, if I change the camera's position, the hardcoded lontiude and latitude dont match the scene's center any more. Is this a bug or the normal behavior ?

Finally, my ultimate goal is to get longitude and latitude values dynamically based on camera's default lookAt posiiton.

Thanks

**Comment by Mugen87** [comment]
Please have a look at #15650 in order to solve this issue.
