### ISSUE TITLE
Blender export to Three js (Critically slow and CPU consuming)

### ISSUE THREAD

**Issue by maloguertin** [mrdoob/three.js#6556]
I was trying to export a large file to the .json format with the new exporter (r71) and the process would simply hang. The mesh had 600k faces but even when decimating it to around 200k faces nothing it would be immensely slow and take 100% CPU.

I found this issue : https://github.com/mrdoob/three.js/issues/6031 which seems to be the same problem but it says it would be fixed in the latest release yet it doesn't seem to be.

I tried the old exporter (r69) and it managed export the mesh to .json in <20 seconds.

**Comment by maloguertin** [comment]
I just tried it with the exporter from the dev branch with my reduced mesh (250k faces) and it took >2 mins (maybe thats normal)

**Comment by repsac** [comment]
UV indexing is not yet optimized. Are you exporting UVs? If so turn off the option and try again and see if it is still slow. The new exporter actually utilizes JSON to serialize, a big chuck of the performance hit that I have seen is from the JSON serialization libraries.

**Comment by maloguertin** [comment]
I don't think I was exporting UVs unless it's checked by default, which I don't think is. I'm still trying things out with the exporter form the dev branch and when reducing the precision it seems better. Is there any other settings you suggest turning off?

Also is the scene export supposed to be usable right out of the box by the JSON loader?

Thanks

**Comment by repsac** [comment]
> I don't think I was exporting UVs unless it's checked by default

They are

> reducing the precision it seems better

Managing floating point precision is recommended for quite a few reasons. If it helps then use it.

> Also is the scene export supposed to be

Use ObjectLoader for scenes.

**Comment by maloguertin** [comment]
UPDATE: Yes without the UVs options it is super fast now. Maybe it should be unchecked by default because it can literally make blender hang.

Thank you very much for the quick responses.

**Comment by repsac** [comment]
> Maybe it should be unchecked by default because it can literally make blender hang.

That's like kicking your dirty clothes under the bed when your parents tell you to clean your room. I need to actually find the time and improve the indexing logic for UVs. That is the only actual solution here.

**Comment by maloguertin** [comment]
I meant until it's fixed make it unchecked by default.

**Comment by repsac** [comment]
Would you mind trying UV exports with his branch and tell me if it is still insanely slow?
https://github.com/repsac/three.js/tree/uv_optimization

I applied similar optimization ton the indexing of UVs that was applied to the other components

**Comment by inkfood** [comment]
**Blender exporter, enhancements and bugs #6529**

Tested the new exporter, exporting a single geometry as buffer geometry now creates a correct json file.

Solved, thank you.....

**Comment by repsac** [comment]
Going to consider this resolved. I took a cube, mapped UVs, subdivided it to 393,216 faces (UVs subdivide as well) and exported. Below is a snippet from the log with timestamps.
```
2015-05-17 22:42:56,342 - Three.Export - INFO: Parsing uvs
INFO:THREE:Parsing uvs
2015-05-17 22:42:56,342 - Three.Export - DEBUG: mesh.uvs(<bpy_struct, Mesh("Cube.001Geometry")>)
DEBUG:THREE:mesh.uvs(<bpy_struct, Mesh("Cube.001Geometry")>)
2015-05-17 22:43:02,313 - Three.Export - INFO: Parsing UV layer 1
INFO:THREE:Parsing UV layer 1
INFO:THREE:Parsing faces
2015-05-17 22:43:02,379 - Three.Export - INFO: Parsing faces
2015-05-17 22:43:16,708 - Three.Export - INFO: Parsing 393216 faces
INFO:THREE:Parsing 393216 faces
2015-05-17 22:43:32,072 - Three.Export - DEBUG: Geometry().write(filepath=None)
DEBUG:THREE:Geometry().write(filepath=None)
```

Am testing with the r72 dev version but it has been hung up on `Three.Export - DEBUG: mesh.uvs` for 10 minutes now. Safe to say that it is indeed optimized.

**Comment by repsac** [comment]
And as a side note; here is a size comparison between the source .blend file and the resulting .json file
```
-rw-r--r--  1 ed  staff  60241984 May 17 22:42 sphere.blend
-rw-r--r--  1 ed  staff  61981395 May 17 22:43 sphere.json
```

Granted this is just geometry and not a whole scene I have to say that it isn't too bad for being just an ascii file.

**Comment by repsac** [comment]
Merged https://github.com/mrdoob/three.js/pull/6570

**Comment by saddam3d** [comment]
I've tried recent version of your JSON exporter and I must admit it works very well now. Great job and thank you for sharing it!

Exporting times are very good after recent update. 100k - 500k vertices, organic-type geometry with 2 UV channels and full set of attributes takes ~10-20s. Quite an improvement in comparison to 30-50min. I owe you a beer!

**Comment by saddam3d** [comment]
BTW, for testing exporters it's better to add a bit of randomness by applying displacement on subdivided primitive geometry. This makes it very close to types geometry used in real projects.

In any case if you need any 3d assets for your work I'd be glad to help.

**Comment by repsac** [comment]
:+1: 

> In any case if you need any 3d assets for your work I'd be glad to help.

We are having less and less issues with geometry exports. Now the challenge is addressing animation exports. I don't do any animations myself so any test scenes I get are from other people and those have a tendency to be all over the place when it comes to setups. The only downside is that it becomes quite difficult understanding what the spec should be for rigging assets for `three` exports.
