### ISSUE TITLE
Raycaster.setFromCamera for cameras which are attached to an object

### ISSUE THREAD

**Issue by Misiur** [mrdoob/three.js#6559]
[Currently `setFromCamera` uses `camera.position`](https://github.com/mrdoob/three.js/blob/master/src/core/Raycaster.js#L74). However when the camera is a child of an object, [first we need to determine `localToWorld` value](http://stackoverflow.com/a/28873205/309240). 

Would you consider adding/allowing optional third argument to `setFromCamera` which if true, first got global position? I used only `PerspectiveCamera` so far, not sure if it affects other types.

I think situation like that happens quite often, so adding it to API would be beneficial for everyone.

**Comment by WestLangley** [comment]
This has already been [fixed](https://github.com/mrdoob/three.js/blob/dev/src/core/Raycaster.js#L72) in the `dev` branch.

**Comment by Misiur** [comment]
Wonderful! :+1:
