### ISSUE TITLE
Runtime SVG images and Internet Explorer Security Error

### ISSUE THREAD

**Issue by saadfaisal** [mrdoob/three.js#6560]
Hi , I am converting SVG nodes to PNG images at runtime and generating textures out of it. Although this runs perfectly fine on Firefox and Chrome , Internet Explorer(11.0.9600.17801) seems to be causing a Security Error. Here is the JSFiddle for the example

http://jsfiddle.net/o7o7uf52/3/

In the example , i have directly embed the SVG image however these are generated at runtime so i dont think that should be an issue for IE.

any ideas or suggestions.

**Comment by mrdoob** [comment]
If it works in Firefox and Chrome, then you should report this to Microsoft...
