### ISSUE TITLE
Load inline/hardcoded JSON model?

### ISSUE THREAD

**Issue by antoniobrandao** [mrdoob/three.js#6561]
Hello,

Is it possible to use an inline/hardcoded JSON model? 

I making client-side app (Cordova project) that can't load the file from the disk. It would just work if I could just place the code inline and parse it somehow. Is this possible?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

http://stackoverflow.com/questions/27992147/three-js-include-mesh-data-in-code/27996338#27996338
