### ISSUE TITLE
Two meshes sharing geometry

### ISSUE THREAD

**Issue by xizhonghua** [mrdoob/three.js#6562]
I created two meshes (plain model + wireframe) that share a single geometry object since I will change the geometry on the fly and want to apply the changes to both meshes. It works fine initially, however, after I reset the geometry using the following code. The wireframe just disappeared.

```Javascript
// create meshes, same geometry object
var mesh = new THREE.Mesh( object.geometry, material );
var wireframe = new THREE.Mesh( object.geometry, wireframeMaterial);

// do some operation on the geometry
// update the position of vertices, etc
// both mesh change accordingly

// reset geometry
mesh.geometry.dispose(); //without this line, the wireframe will neither disappear nor reset
mesh.geometry = org_geometry.clone();
wire.geometry = mesh.geometry;  // wireframe disappeared... 
```

You can try this: http://masc.cs.gmu.edu/origami/inflation.html
1. press space to inflate
2. wait for 2 sec
3. press r to reset the meshes

**Comment by mrdoob** [comment]
Sharing geometry is still a bit tricky... Using `.clone()`, even if definitely more wasteful, may do the trick.
