### ISSUE TITLE
3D file from bender can run on window

### ISSUE THREAD

**Issue by stlee0722** [mrdoob/three.js#6566]
HI Mr Doob, Can you please help me for the question
I had export a 3D model from blender and I tried to run it on browser by the HTML code get from internet but cant run. Anyone knw the problem? Thankyou very much

<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Heart Testing</title>
		
    </head>  
    <body>  
  
          <meta charset="utf-8">
		<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
		<style>
		
			body {  
                color: #808080;  
                font-family:Monospace;  
                font-size:13px;  
                text-align:center;  
  
                background-color: #ffffff;  
                margin: 0px;  
                overflow: hidden;  
            }  
 
            #info {  
                position: absolute;  
                top: 0px; width: 100%;  
                padding: 5px;  
            }  
  
            a {  
  
                color: #0080ff;  
            }  
  
        </style>  
           
        <script src="Three.js"></script>    
        
		<script>
 
			var width = window.innerWidth,
			    height = window.innerHeight,
			    clock = new THREE.Clock(),
				scene,
				camera,
				renderer,
				ambientLight,
				directionalLight,
				loader,
				alfaromeo = new THREE.Object3D();
				
			
			scene = new THREE.Scene();
			
			camera = new THREE.PerspectiveCamera ( 40,width / height, 1,1000);
			camera.position.set (0,1,5);
			
			renderer = new THREE.WebGLRenderer( { antialias:true });
			renderer.setSize(width,height);
			document.body.appendChild(renderer.domElement);
			
			ambientLight = new THREE.AmbientLight (0xffffff)
			scene.add (ambientLight);
			
			directionalLight = new THREE.DirectionalLight (0xffffff);
			directionalLight.position.set(0,1,0);
			
			scene.add(directionalLight);
			
			scene.add( new THREE.GridHelper(10,1));
			
			loader = new THREE.JSONLoader;
			
			loader.load('jstesting3.json',function(geometry,materials)
			{
			    jstesting3 = new THREE.Mesh(geometry,new THREE.MeshFaceMaterial(materials));
				scene.add( jstesting3 
						);
				
			});
			
			( function renderLoop (){
				
				requestAnimationFrame(renderLoop);
				var elapsed = clock.getElapsedTime();
				alforomeo.rotation.y = elapsed/2;
				render.render(scene,camera);
				
			})();
			
		</script>  
  
    </body>  
</html>

**Comment by yomotsu** [comment]
As stated in the guidelines, help requests should be directed to stackoverflow. This board is for bugs and feature requests.

http://stackoverflow.com/questions/27992147/three-js-include-mesh-data-in-code/27996338#27996338

Anyway, the JSON file might not be published correctly.
this should be helpful, just follow settings in my slide.
https://speakerdeck.com/yomotsu/webgl-plus-3d-models-by-using-three-dot-js-blender-exporter

**Comment by stlee0722** [comment]
HI, sorry because of stackoverflow nobody answer me

ya, most of my code copy from ur slide, but still cant run
I had tried to put the json file and html file on desktop, it that need any extra settings?
the "materials" and "geometry" need to edit or not since I only had 2 file which are json and html?

"
loader.load('jstesting3.json',function(geometry,materials)
			{
			    jstesting3 = new THREE.Mesh(geometry,new THREE.MeshFaceMaterial(materials));
				scene.add( jstesting3 );				
			});
"





My full code:


<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Heart Testing</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
        <script src="http://mrdoob.github.com/three.js/build/three.min.js"></script>
    </head>  
    <body> 
        
		<script>
 
			var width = window.innerWidth,
			    height = window.innerHeight,
			    clock = new THREE.Clock(),
				scene,
				camera,
				renderer,
				ambientLight,
				directionalLight,
				loader,
				alfaromeo = new THREE.Object3D();
				
			
			scene = new THREE.Scene();
			
			camera = new THREE.PerspectiveCamera ( 40,width / height, 1,1000);
			camera.position.set (0,1,5);
			
			renderer = new THREE.WebGLRenderer( { antialias:true });
			renderer.setSize(width,height);
			document.body.appendChild(renderer.domElement);
			
			ambientLight = new THREE.AmbientLight (0xffffff)
			scene.add (ambientLight);
			
			directionalLight = new THREE.DirectionalLight (0xffffff);
			directionalLight.position.set(0,1,0);
			
			scene.add(directionalLight);
			
			scene.add( new THREE.GridHelper(10,1));
			
			loader = new THREE.JSONLoader;
			
			loader.load('jstesting3.json',function(geometry,materials)
			{
			    jstesting3 = new THREE.Mesh(geometry,new THREE.MeshFaceMaterial(materials));
				scene.add( jstesting3 );
				
			});
			
			( function renderLoop (){
				
				requestAnimationFrame(renderLoop);
				var elapsed = clock.getElapsedTime();
				alforomeo.rotation.y = elapsed/2;
				render.render(scene,camera);
				
			})();
			
		</script>  
  
    </body>  
</html>

**Comment by dmtaub** [comment]
Depending on your browser, local asset serving may not work. (chrome has
trouble with this, I know). Post your SO link here and to #threejs on
freenode, to continue the conversation there.

Also if you create a JS fiddle, people are more able to help you debug, but
you'll need to host your Json file

-m(obile)Dan
