### ISSUE TITLE
3d Max to JSON "ThreeJSAnimationExporter.ms" bug. Wrong skin weights

### ISSUE THREAD

**Issue by AlexeyGapon** [mrdoob/three.js#6569]
I noticed that sometimes this exporter creates file with wrong skin weights. I am allways using biped. 
Sometimes it wiroks fine sometimes not.
Who is the author of this script?

PS: I want to write exporter for BlendCharacter with multiple animations.

**Comment by Mugen87** [comment]
The exporter has been removed, see #12930
