### ISSUE TITLE
materailIndex always set to 0 by geometry constructor

### ISSUE THREAD

**Issue by rfm1201** [mrdoob/three.js#6571]
I’m using different standard geometry of three.js and there is one little change that will make a big difference for me: may all geometries with geometrical faces could have a different materialIndex for each face.

Actually (r71) BoxGeometry does, but CylinderGeometry and PolyhedronGeometry don’t. As PolyhedronGeometry doesn’t, all geometries using it don’t.

Of course writing my own geometry with a materialIndex by geometrical faces for the one I really need was not a big challenge, but I think it could be in the standard three.js geometries.

**Comment by mrdoob** [comment]
You're talking about built in primitives?

**Comment by rfm1201** [comment]
Hi,

Yes, as BoxGeometry generate a geometry with a specific materialIndex for each face, why CylinderGeometry and PolyhedronGeometry don’t.

What I suggest, is to modify CylinderGeometry and PolyhedronGeometry constructor just to set a different materialIndex on each face. 

In CylinderGeometry.js, just change line 133 and 160 from
this.faces.push( new THREE.Face3( v1, v2, v3, [ n1, n2, n3 ] ) );
to
this.faces.push( new THREE.Face3( v1, v2, v3, [ n1, n2, n3 ], undefined, 1 ) ); for line 133, and replace 1 by 2 for line 160.

In PolyhedronGeometry it’s a three steps change.
First, line 41 of PolyhedronGeometry.js go for something like
faces[ j ] = new THREE.Face3( v1.index, v2.index, v3.index, [ v1.clone(), v2.clone(), v3.clone() ], undefined, j );
Next function subdivide must be change to use the current materialIndex of the face it process. As the face building is in the make method, both need to be updated. My solution was to add a fourth parameter to make (as it is only used by subdivide).
So, to the calls to make (line 180 and 188), I add a fourth parameter face.materialIndex (in my code, a local copy of face.materialIndex).
Only the beginning of the make method (line 116) need to be updated and becomes:
function make( v1, v2, v3, materialIndex ) {
  var face = new THREE.Face3( v1.index, v2.index, v3.index, [ v1.clone(), v2.clone(), v3.clone() ], undefined, materialIndex );

Now if I build a new mesh with these geometries and MeshFaceMaterial it works as expected, as BoxGeometry does.

I think it's more logical that BoxGeometry , CylinderGeometry and PolyhedronGeometry generate geometry with the same behavior for materialIndex.
