### ISSUE TITLE
THREE.ImageLoader fails when the same url is being used twice.

### ISSUE THREAD

**Issue by Fabrice3D** [mrdoob/three.js#6572]
Just got 2 projects broken after moving from r69 to r71.

the code being used in a method that receives the material as param.

```javascript
var imageLoader = new THREE.ImageLoader();
var bitmap = imageLoader.load( url, imageLoaded );
 
function imageLoaded(){
		var texture = material.map;
		texture.image = bitmap;
		texture.needsUpdate = true;
}
```

r69 and r71 will load and update the texture with newly loaded image.
If the same url is used again, r69 works as expected, r71 crashes.
The caching mechanism seems to be the bad guy.

commenting this bit fixes my 2 projects….

```javascript
THREE.ImageLoader.prototype = {

	constructor: THREE.ImageLoader,

	load: function ( url, onLoad, onProgress, onError ) {

		var scope = this;

		/*var cached = THREE.Cache.get( url );

		if ( cached !== undefined ) {

			onLoad( cached );
			return;

		}*/
```

**Comment by mrdoob** [comment]
Yes. I noticed it in this `dev` cycle :(
This is the proper fix: https://github.com/mrdoob/three.js/commit/8d267bb086d54c2e979a2c22af1e7c239a8b175f

**Comment by Fabrice3D** [comment]
Hey Ricardo, probably me doing wrong... applied the fixes and it still crash because of null image.

**Comment by mrdoob** [comment]
Oh, that's strange... Do you have a link I can test with?

**Comment by Fabrice3D** [comment]
k, I'll try make some "with and without" small case asap.

**Comment by mrdoob** [comment]
Thanks!

**Comment by Fabrice3D** [comment]
k, I've found the bad guy i think.
The cached info is checked on handle key and the texture object,
not the image data.
Using a material.map.dispose(); for instance and loading same url later.
will lead to image null error in "clampToMaxSize" method.

**Comment by mrdoob** [comment]
Oh! Right, because texture replaces the image... I should add a example/test for that.

**Comment by Fabrice3D** [comment]
Letting the cache be validated on texture and image should not be a biggy to implement...
