### ISSUE TITLE
Support Request: How to how to integrate EffectComposer with OculusRiftEffect, VREffect or VRRenderer?

### ISSUE THREAD

**Issue by jmredfern** [mrdoob/three.js#6577]
Hello!

I hope it's ok to raise this question here, if not perhaps you could direct me to a better place.	

Using three.js, the classes OculusRiftEffect, VREffect or VRRenderer allow a programmer to render their scene to an Oculus Rift. VRRenderer seems to be the best option at the moment for Rift DK2, is this correct?

EffectComposer is another three.js class that lets the programmer compose multiple different scenes to be displayed by single renderer (e.g. for skybox).

My question is, how can I display the composed output of EffectComposer with the Rift?

The problem is as follows:

The OculusRiftEffect, VREffect or VRRenderer class must be initialised with a renderer such as WebGLRenderer. In the render loop, the class must be called as follows, causing the scene to be displayed on the Rift:

this.vrrenderer.render(this.threeScene, this.camera);

The EffectComposer must also be initialised with a renderer such as WebGLRenderer. In the render loop, the EffectComposer must be called as follows, causing the composed scene to be displayed by the renderer:

this.composer.render();

However, the EffectComposer can't be initialised with an OculusRiftEffect, VREffect or VRRenderer in place of the WebGLRenderer.

The question is how to connect the EffectComposer to one of the Rift classes for rendering? I guess this isn't supported directly, but perhaps you could give a clue to changes I should make in the three.js codebase to do this?

Many thanks!
Jim

**Comment by WestLangley** [comment]
Please see http://stackoverflow.com/questions/30289774/using-three-js-how-to-integrate-effectcomposer-with-oculusrifteffect-vreffect

**Comment by jmredfern** [comment]
Hi WestLangley,

Thanks for the link! 

Actually this was my post on StackOverflow. I wonder if maybe it's a feature request rather than a support request - because it seems to me that without hacking the three.js library itself, it's not possible to use EffectComposer with one of the VR libraries. 

Without EffectComposer I think there's no skybox on a VR headset, which is a key element. So the feature request would be to support this. 

Best wishes,
Jim

**Comment by MasterJames** [comment]
Is this link relevant my apologizes if it's not.
https://www.npmjs.com/package/three-effectcomposer

**Comment by jmredfern** [comment]
Hi MasterJames,

Thanks for the link, but I don't think it doesn't provide anything useful for this scenario - it provides a way to use EffectComposer via Browserify, but the underlying EffectComposer is the exactly the same.

**Comment by MasterJames** [comment]
Have you tried the other route...
https://answers.oculus.com/

BTW: This does concern me deeply, I intend this comment as a solution not a run-around.

**Comment by skezo** [comment]
@jmredfern 

Did you find a solution for this?

**Comment by jmredfern** [comment]
Hi Skezo, unfortunately not so I just didn't use composition on the Rift scene for the moment
