### ISSUE TITLE
Problems w/ Ajax loading

### ISSUE THREAD

**Issue by mattpolicastro** [mrdoob/three.js#6580]
I'm honestly quite stumped. I'm doing on-demand Ajax script loading from within a Meteor application (an array of string paths to specified libraries), which are loaded through jQuery's `$.getScript()`.
````
Template.postPage.onRendered(function(){

    var post = Template.currentData();

	//post.libs = [ //the contents of post.libs, for reference
	//	'/libs/test.js',
	//	'/bower_components/threejs/build/three.min.js', 
	//	'https://cdnjs.cloudflare.com/ajax/libs/three.js/r71/three.min.js',
	//	'/bower_components/chartist/dist/chartist.min.js', 
	//	'/bower_components/Chart.js/Chart.min.js',
	//	'/bower_components/d3/d3.min.js'
	//]

    if(post.libs) post.libs.forEach(function(e){ //Iterates over the array of paths
        console.log(e);
        $.getScript(e, function(data, text, code){
            console.log(text);
        }).done(threejs); //Obviously this throws errors on the other libraries, but 
				  // was trying to keep the sample small.

        function threejs(){
            var scene = new THREE.Scene();
        };

    });
});
````
 Three.js is one of the libraries I'm trying to load. This pattern has worked for several other visualisation libraries (d3, Chartist, Chart.js), but won't work with Three.js: when it's hosted from my own server (copy-pasted from source, installed via Bower, etc.), it breaks (reference error, cannot find var `THREE`). When it's loaded from a CDN, it works perfectly. 

It's entirely possible I'm seeing some kind of error somewhere up the chain in Meteor or jQuery, but since I've only seen the problem with Three, I figured I'd start here. Any help is appreciated.

**Comment by WestLangley** [comment]
http://stackoverflow.com/search?q=%5Bthree.js%5D+Meteor
