### ISSUE TITLE
Shadow mapping - Different handling of visibility between WebGLRenderer.js and WebGLShadowMap.js

### ISSUE THREAD

**Issue by neverhood311** [mrdoob/three.js#6582]
I broke shadow mapping while trying to render scenes that contain objects with extremely deep, complex hierarchies. I discovered that the fault was mine, but I uncovered an interesting difference in behavior between WebGLRenderer and WebGLShadowMap.

I accidentally set the visibility of one of the hierarchy Object3Ds to `undefined`. It was supposed to default to `true` and only rarely would it be set to `false`. When the WebGLRenderer sees this, it basically ignores it and the object renders just fine ([https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1644](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1644)):

    if ( object.visible === false ) return;

However, when the WebGLShadowMap comes around to render the object with undefined visibility, it behaves differently ([https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLShadowMap.js#L353](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLShadowMap.js#L353))

    if ( object.visible ) {

and it doesn't render to the shadow map.

The shadows in my project are subtle-ish and I was preoccupied with other things when I made the change that broke them, so I didn't notice that some shadows (but not all of them) had stopped rendering. I would expect the renderer and the shadow renderer to behave the same in this situation.

**Comment by neverhood311** [comment]
In this question I posted a screenshot of the problem: [http://stackoverflow.com/questions/30312534/why-arent-shadows-showing-up](http://stackoverflow.com/questions/30312534/why-arent-shadows-showing-up)

**Comment by WestLangley** [comment]
Well, I'm glad you were able to successfully debug your program. : - )

Thanks for pointing out the subtle difference in visibility-testing.

**Comment by mrdoob** [comment]
Oh... Nice catch!

**Comment by mrdoob** [comment]
Fixed. Thanks!

**Comment by WestLangley** [comment]
@mrdoob  In `WebGLRenderer`, should you not also change it to

    if ( object.visible !== true ) return;

so that both rendering and shadows only occur if `visible === true`?

**Comment by mrdoob** [comment]
Nope. Otherwise it will happen the same again when `object.visible` is `undefined`.

**Comment by neverhood311** [comment]
@mrdoob I think @WestLangley is right. Is `object.visible` is `undefined`, it will not evaluate to `true` in WebGLRenderer `if ( object.visible === false ) return;` and NOT return; it WILL render. However, when it gets to the test in WebGLShadowMap `if ( object.visible === true) {` it will not evaluate to `true` and will NOT render.

**Comment by mrdoob** [comment]
Oh! True... Sorry @WestLangley! 😅

**Comment by mrdoob** [comment]
Ok. I think it should be fixed now.

**Comment by WestLangley** [comment]
That looks better! : - )
