### ISSUE TITLE
Editor: Implement tern-threejs in script editor.

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#6585]
In case anyone wants to give it a go before I do...

http://codemirror.net/demo/tern.html
https://github.com/tylerwbell/tern-threejs

**Comment by zz85** [comment]
wah interesting! :+1: 

have you started on this?

**Comment by zz85** [comment]
I also find this an interesting read http://marijnhaverbeke.nl/blog/tern.html

Also looks like all these work have been done even before I heard about Flow, Typescript,  Soundscript..

**Comment by zz85** [comment]
Some initial mashup tests...

**Auto complete**

![screenshot 2015-06-05 00 48 04](https://cloud.githubusercontent.com/assets/314997/7992709/d6ddb4d0-0b33-11e5-9dc3-fcb35c1d7628.png)

![screenshot 2015-06-05 03 24 06](https://cloud.githubusercontent.com/assets/314997/7992773/2c9ee362-0b34-11e5-8ef8-0f400c8c25e4.png)

**Function definitions**

![screenshot 2015-06-05 00 49 31](https://cloud.githubusercontent.com/assets/314997/7992806/6aec017c-0b34-11e5-9d2c-e18d61ca0bee.png)

![screenshot 2015-06-05 03 33 02](https://cloud.githubusercontent.com/assets/314997/7992820/7f42e2da-0b34-11e5-9a7c-ce189922898e.png)

![screenshot 2015-06-05 03 27 00](https://cloud.githubusercontent.com/assets/314997/7992821/7f456c6c-0b34-11e5-9056-966f7ef397d1.png)

![screenshot 2015-06-05 03 29 19](https://cloud.githubusercontent.com/assets/314997/7992819/7f42b3f0-0b34-11e5-9b8d-c386384f0941.png)

**Comment by zz85** [comment]
works pretty well. maybe the autocomplete could get some sort of intellisense improvements..
  
![ternthree](https://cloud.githubusercontent.com/assets/314997/7998381/d0a28cfa-0b6d-11e5-8dc1-fbfe1f47a0df.gif)

**Comment by mrdoob** [comment]
YESSS!

**Comment by angelozerr** [comment]
Just for you rinformation:

 * you have an online demo at http://demo-angelozerr.rhcloud.com/CodeMirror-Java/threejs.html 
 * this tern-threejs was integrated inside Eclipse https://github.com/angelozerr/tern.java/wiki/Tern-&-Threejs-support

**Comment by zz85** [comment]
@angelozerr great stuff, thanks for linking here. If I have noticed your demo earlier, I might not have to do some of the stuff you already did :)
