### ISSUE TITLE
MeshLambertMaterial -> MeshGouraudMaterial

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#6586]
Doesn't need to be done during this cycle, but I think we should move the current `MeshLambertMaterial` out of core.

What I mean with that is that we'll still have `MeshLambertMaterial` which will pretty much be the same as `MeshPhongMaterial` but without specular. `MeshLambertMaterial` currently creates a per-vertex shader. I think we can move the "compiled" shader to examples under the name of `MeshGouraudMaterial` or so... That way all the material/shaders in core will be per-pixel and things will be simpler to maintain.

Thoughts?

**Comment by bhouston** [comment]
I support this. :)

**Comment by WestLangley** [comment]
I agree that we no longer need `MeshLambertMaterial` -- unless someone can demonstrate that it has significantly better performance due to its per-vertex shading. If that is the case, it can be moved to the examples, where it will still have to be maintained. Otherwise, it can be removed completely, which would be my preference.

**Comment by mrdoob** [comment]
@WestLangley It definitely is better performant, but I think is not the common use case. Happy to keep it in the examples and maintain it myself. If only it's a good example of doing per vertex lighting. Next cycle!

**Comment by RemusMar** [comment]
>  I think we should move the current MeshLambertMaterial out of core.

+1
Phong leads the championship
:sunglasses:

**Comment by titansoftime** [comment]
I use ```MeshLambertMaterial``` as an optional setting for users with slower machines and as a default for users on mobile devices.

The absence of this would be yet another feature I would miss.

**Comment by bhouston** [comment]
I think keeping around MeshGouraudMaterial for games on mobile is likely useful to a lot of people.  We do not use it, but I find WebGL to be painfully slow on mobile and this is one solution.

**Comment by bhouston** [comment]
I wonder if MeshGouraudMaterial could be integrated into MeshPhongMaterial except with a flag for lighting to be per vertex.  Might be possible.

**Comment by Mugen87** [comment]
Fixed via #24467 and #24452.

**Comment by mrdoob** [comment]
I have zero recollection of having written that but I'm glad we ended up doing just as proposed 😅

**Comment by bhouston** [comment]
More old context - https://github.com/mrdoob/three.js/issues/5784
