### ISSUE TITLE
#webgl_panorama_equirectangular not wirking in ios

### ISSUE THREAD

**Issue by Maxmaxmaximus** [mrdoob/three.js#6591]
http://threejs.org/examples/#webgl_panorama_equirectangular

texture muar like carpet
![img_0371](https://cloud.githubusercontent.com/assets/3730167/7766007/6321f19e-006d-11e5-9c6c-c63337eddd53.PNG)
![img_0372](https://cloud.githubusercontent.com/assets/3730167/7766006/632168b4-006d-11e5-948d-518d7754b2b9.PNG)
![img_0373](https://cloud.githubusercontent.com/assets/3730167/7766005/631f6d2a-006d-11e5-83c7-0dd510f61f9d.PNG)

**Comment by MasterJames** [comment]
I wondering if that's a Chrome browser on iPad?
https://itunes.apple.com/ca/app/chrome-web-browser-by-google/id535886823?mt=8
Does that work there?

**Comment by mrdoob** [comment]
#5956

**Comment by Maxmaxmaximus** [comment]
So what to do then? It is clear that this is their bug. To do what? Fix write or who will not I understand?

**Comment by mrdoob** [comment]
Apple should address this. However, you could make sure you don't use textures bigger than 2048 on iOS.

**Comment by Maxmaxmaximus** [comment]
bigger than 2048 ? you mean 2048x2048 px?

**Comment by makc** [comment]
That pretty much looks like 4096 texture. In one project, I downscaled it to 2048 before it worked on ios.
