### ISSUE TITLE
Point light source doesn't work if distance = 0

### ISSUE THREAD

**Issue by neilweinstock** [mrdoob/three.js#6592]
Using three.js v71, Windows 7 service pack 1.  Having a hard time divining my GPU details: it's Intel HD Graphics driver v.8.15.10.2418 (the processor is an i5-2540M).

When the distance of a point source is zero (or left to default), the light doesn't work, stays black.  Setting the distance to anything other than 0 makes it work.

As an example, the demo embedded in the doc page for MeshLambertMaterial appears black for me (http://threejs.org/docs/#Reference/Materials/MeshLambertMaterial)

**Comment by WestLangley** [comment]
Yes, setting distance to zero should result in non-attenuated light.

Thanks for the report. Originally posted on [stackoverflow](http://stackoverflow.com/questions/20723040/three-js-lambert-material-color-not-showing/30378557#30378557).

**Comment by mrdoob** [comment]
Hmm... Should `distance` be set to `Infinity` if `undefined` in the constructor?

**Comment by mrdoob** [comment]
I think this has been discussed before. Maybe the problem was that glsl doesn't have `Infinity`...

**Comment by WestLangley** [comment]
Perhaps this is the culprit: division by zero if `cutoffDistance` is zero.

    float calcLightAttenuation( float lightDistance, float cutoffDistance, float decayExponent ) {

	    if ( decayExponent > 0.0 ) {

	      return pow( saturate( - lightDistance / cutoffDistance + 1.0 ), decayExponent );

	    }

	   return 1.0;

    }

Maybe a better test would be

	    if ( cutoffDistance > 0.0 && decayExponent > 0.0 ) {

/ping bhouston

**Comment by Mugen87** [comment]
In the meanwhile, this issue is solved.
