### ISSUE TITLE
threejs.org/editor does not save stuff in ff (nightly)

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6594]
works in chrome, but nothing happens in ff. no errors in console or anything.

**Comment by RemusMar** [comment]
I don't use three.js editor, but I did notice the same issue with opentype.js (typeface.js):
The file is saved with Chrome, but not with Firefox (38).
For me it looks like a Firefox bug.

**Comment by makc** [comment]
well, I use [filesaver](https://github.com/eligrey/FileSaver.js) in some of my pages, and it saves the stuff, so... they can fix it.

**Comment by RemusMar** [comment]
> well, I use filesaver in some of my pages, and it saves the stuff, so... they can fix it.

The main question is why Chrome doesn't need workarounds?

**Comment by makc** [comment]
> why Chrome doesn't need workarounds?

seems like ff does not fire clicks for orphan elements.

**Comment by RemusMar** [comment]
> seems like ff does not fire clicks for orphan elements.

> For me it looks like a Firefox bug.

**Comment by makc** [comment]
but ff and 3js are two different projects. if we want 3js editor to save stuff in ff, we could work around ff issue in 14 minutes, or wait for ff to fix their shit for [14 years](https://bugzilla.mozilla.org/show_bug.cgi?id=77790), if we aren't lucky. that said, you're free to report the issue there as well.

**Comment by mrdoob** [comment]
@makc could you double check that my workaround also works?

**Comment by makc** [comment]
It does. Btw, 'export object' throws TypeError: a is undefined somewhere in three.min.js

**Comment by mrdoob** [comment]
@makc yeah, I noticed... that one will be tricky to fix...
