### ISSUE TITLE
Simple panorama 360 player with deepzoom (multires)

### ISSUE THREAD

**Issue by husky83** [mrdoob/three.js#6597]
I try to make simple panorama player, like in this example:  http://threejs.org/examples/#canvas_geometry_panorama
But I need to make multires - when I zoom in, i want to load better texture for visible plane (different file for different zoom). 
It is possible? How can I make this?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
