### ISSUE TITLE
Using Three with Babel via Browserify and Babelify throws an error

### ISSUE THREAD

**Issue by karlas** [mrdoob/three.js#6599]
Using this simple code, and bundling it with Browserify (with no transform) works fine:

```
var THREE = require('three');

var camera = new THREE.PerspectiveCamera(35, 1, 1, 10000);
camera.position.set(3, 0.5, 3);

var directionalLight = new THREE.DirectionalLight(0xffffff, 1);
directionalLight.position = camera.position;

console.log("Ok!");
```

But, applying babelify tranform:

```
browserify script.js -t babelify --outfile bundle.js
```

executing it on browser gives following error on console: 

```
Uncaught TypeError: Cannot assign to read only property 'position' of [object Object]
```

If you inspect the bundle.js with this transform, you can get following transform:

```
var directionalLight = new THREE.DirectionalLight(16777215, 1);
````
so, hex value has been converted to decimal.

Any idea? I'm not pretty sure if it's an issue with Three or with Babel.

I created a repo with the code I used: https://github.com/karlas/error-babelify-three

Regards

**Comment by karlas** [comment]
I created an issue on Babelify issue tracker as well : https://github.com/babel/babelify/issues/87

**Comment by mrdoob** [comment]
I have no idea what you're talking about...

**Comment by karlas** [comment]
Wow friendly comment. What exactly do you don't understand?

**Comment by benaadams** [comment]
hex is same as decimal, your issue is this line:
```directionalLight.position = camera.position;```

**Comment by karlas** [comment]
Yes, but passing an hex works fine, it's with the transform (which passes a decimal) when it fails. Could it be related to another part of code being transformed as well?

**Comment by benaadams** [comment]
```directionalLight.position``` is read only so you can't assign it to ```camera.position```

**Comment by karlas** [comment]
Sorry guys, I repeat: without the transfom, it works

**Comment by karlas** [comment]
http://www.diale.org/javascript3knot.html

This is the code which inspired me. As you can see, it's working

**Comment by benaadams** [comment]
In r68 ```position```, ```rotation```, ```quaternion``` and ```scale``` properties were made immutable so you can't do this assignment after that version.

**Comment by karlas** [comment]
Well, did you try the code on my repo? As you can see, version is 0.71.0. I'm sorry to say it again : IT'S WORKING

**Comment by benaadams** [comment]
Your repo has no context as to what Three.js code you are including other than ```var THREE = require('three');``` which could be any version.

The error you get is:

```Uncaught TypeError: Cannot assign to read only property 'position' of [object Object]```

Which suggests its this line:

```directionalLight.position = camera.position;```

As that is what you are doing there.

**Comment by karlas** [comment]
Ben:

1) My package.json file in repo tells you it's version 0.71.0, being downloaded from npm
2) I really really swear, and I say for 4th time: it works. Try it please please plase, that's why i created the repo

**Comment by karlas** [comment]
If you want i close the issue, I wouldn't like to make people lose it's time. Just wanting to help

**Comment by RemusMar** [comment]
WRONG: directionalLight.position = camera.position;
CORRECT: directionalLight.position.copy( camera.position );

**Comment by karlas** [comment]
Thx RemusMar! i will try

**Comment by zertosh** [comment]
Cross-posting my answer from https://github.com/babel/babelify/issues/87#issuecomment-105326049:

> What you're seeing is a strict mode violation. three.js is [making](https://github.com/mrdoob/three.js/blob/5c7e0df9b100ba40cdcaaf530196290e16c34858/src/core/Object3D.js#L39-L42) `position` non-writable and non-configurable. So it's not the hex to dec conversion but rather the `"use strict"`. You can turn off that transform and your code will work:

> ```sh
browserify script.js -t [ babelify --blacklist strict ] --outfile bundle.js
```

**Comment by karlas** [comment]
Nice! Thx zertosh

**Comment by mrdoob** [comment]
> Wow friendly comment. What exactly do you don't understand? Did you try the code?

Haha, I don't know what Babel is and I've never used Browserify. There was way too many things I didn't know in your original post that I just had no idea what you were talking about.
