### ISSUE TITLE
Android + DeviceOrientationControls.js = NO

### ISSUE THREAD

**Issue by Villmer** [mrdoob/three.js#6607]
Gyroscope and Accelerometer vales are wrong on Android when using the DeviceOrientationControls.js class. 

You can see the issue here: http://www.villmer.com/tools (use Head Mounted Display mode)
The DeviceOrientationControls.js class does, however, just fine on iOS. So, the issue appears to be Android.

**Comment by mrdoob** [comment]
Could you do a video showing the issue? I seem unable to reproduce.

**Comment by fraguada** [comment]
@Villmer which browser are you using on Android.  I had a situation where Firefox on Android gave me everything inverted with regards to the screen orientation, but Chrome worked just fine.  Have you tried different browsers on Android?

**Comment by Villmer** [comment]
@ doob
If you view www.villmer.com/tools/test.html, you can see a photo and video. If you enter the photo (double tap) the orientation is not working properly. (also the video is not showing) Does this work properly for you? If so, which Android browser are you using? This works fine on an iPad - the issue is just related to Android browsers.

@fraguada 
The issue with the inverted video in Firefox android was reported to Mozilla and can be seen here: https://bugzilla.mozilla.org/show_bug.cgi?id=1127336
After this bug was reported the video stopped rending entirely in Firefox.

**Comment by Villmer** [comment]
@ doob
I will go ahead and change the default viewing method to "gyro" at www.villmer.com/tools/test.html so the page opens immediately using the DeviceOrientationControls.js  class. Currently, you have to select "gyro" from the settings to turn on DeviceOrientationControls.js.

**Comment by Villmer** [comment]
@mrdoob 
I've changed http://www.villmer.com/tools/test.html site so it automatically opens using the DeviceOrientationControls.js class.....

**Comment by Villmer** [comment]
@fraguada 
Are you able to view www.villmer.com/tools on any android browser? (can you see the videos)

**Comment by fraguada** [comment]
If by video you mean what the red arrow is pointing to, no, I do not see it playing.  Trying on Chrome/Firefox Samsung Galaxy S4 Android 5.0.1 and Samsung Galaxy Tab 4 Android 4.4.2

**Comment by Villmer** [comment]
No, I don't mean what the arrow is pointing too. Each sphere is a 360 video file. I'm attaching a screenshot of what you should see. I ask only because there appears to be a bug preventing the video from showing. Bug report here: https://github.com/mrdoob/three.js/issues/6606

![screen shot 2015-05-29 at 3 06 10 pm](https://cloud.githubusercontent.com/assets/5082470/7883133/64645b80-0614-11e5-8ebf-188237c42f0e.png)

**Comment by mrdoob** [comment]
> @mrdoob
View www.villmer.com/tools/test.html with an Android browser. This small demo has a 360° photo and video. If you enter the photo (double tap) the orientation is not working properly. Does this work properly for you? If so, which Android browser are you using?

Yes. It seems to work properly. I'm using Chrome 43, Android 5.1.1, Nexus 5.

Btw, you should use [screen.orientation.lock()](https://twitter.com/mrdoob/status/540147861326139392).

**Comment by Villmer** [comment]
@mrdoob 
I'm glad to hear it's working on the Nexus 5. That should at least indicate it can work under the right conditions. I suppose the question is what conditions?

All of the tests I have conducted (on Chrome and Firefox) do not work:
  - Tested on Galaxy S3 Edge running Android 5.0
  - Tested on Galaxy Tab 2 running Android 5.1.1

**Comment by fraguada** [comment]
If this is what I should be seeing, then yes on Firefox on Galaxy Tab 4. Not in Chrome.

**Comment by Villmer** [comment]
I’m surprised to hear you can view this on Firefox Android. The videos actually render? Could you please post a screenshot?

**Comment by fraguada** [comment]
![screenshot_2015-05-29-17-22-51](https://cloud.githubusercontent.com/assets/1014562/7886042/88db9ef2-0627-11e5-901f-bca1c3eabd16.png)

**Comment by MasterJames** [comment]
Page not found

**Comment by Villmer** [comment]
@fraguada 
Thanks for sending me the screen shot. Firefox folks say the bug inverting the video files will be released at Firefox v40. All we need now is for Chrome to get it working.
