### ISSUE TITLE
Geometry.fromBufferGeometry() is having error when converting an EdgeHelper buffer geometry. 

### ISSUE THREAD

**Issue by tiansijie** [mrdoob/three.js#6610]
I tried to convert an BufferGeometry to Geometry. This BufferGeometry is creating from EdgeHelper. It gave me this error `Uncaught TypeError: Cannot read property 'x' of undefined` . This error is coming from 

``` javascript
subVectors: function ( a, b ) {

        this.x = a.x - b.x;
        this.y = a.y - b.y;
        this.z = a.z - b.z;

        return this;

},
```

 I tried to track down this issue. The EdgeHelper usually creates an BufferGeometry which the last index is 0 to connect the start vertex and end vertex. 

However, in `fromBufferGeometry()` , this piece of code doesn't handle this very well. 

``` javascript
for ( var i = 0; i < indices.length; i += 3 ) {

       addFace( indices[ i ], indices[ i + 1 ], indices[ i + 2 ] );

}
```

Therefore, when calling the `computeFaceNormals()` inside `fromBufferGeometry()`, it always trying to access the last index which is not exist in the vertices array.

**Comment by WestLangley** [comment]
> The EdgeHelper usually creates an BufferGeometry which the last index is 0 to connect the start vertex and end vertex.

It does?

Can you provide a test case, along with the information requested in "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md)?

**Comment by Usnul** [comment]
not sure if this would be a good way to go:
```js
for ( var i = 0,l=indices.length-2; i < l; i += 3 ) {

       addFace( indices[ i ], indices[ i + 1 ], indices[ i + 2 ] );

}
```

**Comment by tiansijie** [comment]
```javascript
<html>
	<head>
		<title>My first Three.js app</title>
		<style>
			body { margin: 0; }
			canvas { width: 100%; height: 100% }
		</style>
	</head>
	<body>
		<script src="libs/three.js"></script>
		<script>
			var scene = new THREE.Scene();
            var camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );

            var renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );


            document.body.appendChild( renderer.domElement );
            var material = new THREE.MeshBasicMaterial({
                            	color: 0x0000ff
                            });

            var radius = 5;
            var segments = 32;

            var circleGeometry = new THREE.CircleGeometry( radius, segments );				
            var circle = new THREE.Mesh( circleGeometry, material );
           /*CREATE EDGES*/
            var edges = new THREE.EdgesHelper( circle, 0x00ff0f );
            /*IT NEEDS TO CONVERT FROM BUFFER GEOMETRY TO GEOMETRY TO USE GEOMETRY MERGE FUNCTION*/
            var edgeGeometry = new THREE.Geometry().fromBufferGeometry(edges.geometry);
           /*HERE IS THE PROBLEM*/
            circleGeometry.merge(edgeGeometry);

            scene.add( circle );

            camera.position.z = 15;

            function render() {
            	requestAnimationFrame( render );
            	renderer.render( scene, camera );
            }
            render();
            
        </script>
	</body>
</html>
```


THREEJS Version: 71
ERROR: Uncaught TypeError: Cannot read property 'x' of undefined       three.js:1783
Chrome 43.0.2357.81, OS X, Intel Iris Pro

@WestLangley @Usnul Here is the test case and bug report

Thanks

**Comment by antont** [comment]
the call stack seems to be:

in `THREE.CylinderGeometry`:
```
this.computeFaceNormals();
```

and in there, in `computeFaceNormals` in `THREE.Geometry`:
```
cb.subVectors( vC, vB );
```

where:

```
subVectors: function ( a, b ) {
	this.x = a.x - b.x;
```

made a jsfiddle for running this, with master / prev release there now:
https://jsfiddle.net/b39100np/

could test with current dev too i figure, dunno if that has been touched.

ah i think there actually was a fix to this recently .. couldn't find it immediately now though but saw an issue just a couple of days discussing this i think, with a fix proposal or so.

**Comment by antont** [comment]
i made a jsfiddle for running this: https://jsfiddle.net/b39100np/

am not sure of the proposed fix above .. will try to think too but figure others who knows this better can judge. hopefully the ready made jsfiddle is convenient for someone.

**Comment by WestLangley** [comment]
Thank you, @antont .

>  circleGeometry.merge( edgeGeometry );

@tiansijie Why are you trying to do that? You can't merge faces and line-segments.

> var edgeGeometry = new THREE.Geometry().fromBufferGeometry( edges.geometry );

@mrdoob Well, it happened. See the discussion in https://github.com/mrdoob/three.js/commit/eda6cd1e0eb4efd1aebfe4205d453993eb2f48b9.

**Comment by tiansijie** [comment]
@WestLangley I tried to combine the geometry to reduce number of drawcalls to have a better performance.

**Comment by benaadams** [comment]
> I tried to combine the geometry to reduce number of drawcalls to have a better performance.

Lines and faces use different signature drawcalls so cannot be combined.

**Comment by Mugen87** [comment]
To sum this up: `Geometry.fromBufferGeometry()` does not support line geometries. 

IMO this conversion does not make sense anyway. And as @benaadams mentioned a combination of line and mesh geometries is not possible.

@WestLangley @mrdoob If you don't mind, i would like to close this issue.

**Comment by WestLangley** [comment]
Yes, `Geometry.fromBufferGeometry( bufferGeometry )` assumes `bufferGeometry` is the geometry of a mesh.

**Comment by suryakumara** [comment]
![image](https://user-images.githubusercontent.com/51102773/131478994-59cee357-90ef-4135-a563-c3b07be17964.png)
Hi Iam facing same problem while combining Text Geometry and Sphere. But the requirements ask me to use BufferGeometry. Any suggestions ?
