### ISSUE TITLE
Suggestion: point out a Maya hiccup in export workflow in the plugin readme file

### ISSUE THREAD

**Issue by MichaelHazani** [mrdoob/three.js#6613]
Hi! As a newcomer to this lovely library, it took me a long, long time to realize that my objects weren't exporting well from maya, and showing up as not well formed, simply because I didn't _delete object history_ before exporting (I believe that's the case for .obj export/import from maya although I haven't tested it thoroughly). Once I made sure I deleted object history everything worked out. 

I think a clarification in the readme about the need to do so would prove extremely helpful for others in my situation. Thanks!

**Comment by mrdoob** [comment]
Feel free to change the file 😊
https://github.com/mrdoob/three.js/edit/dev/utils/exporters/maya/README.md

**Comment by Lu-Do** [comment]
ehm, deleting history means that the mesh cannot be a skinned one... or am i wrong?

**Comment by MichaelHazani** [comment]
I could be wrong, but it's my understanding that the JSON exporter is
intended exclusively for static models anyway, so skinning isn't an issue.
Any model that includes rigging/animation/skinning etc. is best exported
using Collada DAE files (for example, see
http://stackoverflow.com/questions/14736090/maya-to-three-js-with-animation
).

Re. file update - haven't had a chance to properly test the workflow (and
I'd need to in order to justify a doc change;), but I hope to get to it
soon!

**Comment by MichaelHazani** [comment]
I could be wrong, but it's my understanding that the JSON exporter is intended exclusively for static models anyway, so skinning isn't an issue. 
Any model that includes rigging/animation/skinning etc. is best exported using Collada DAE files (for example, see http://stackoverflow.com/questions/14736090/maya-to-three-js-with-animation).

Re. file update - haven't had a chance to properly test the workflow (and I'd need to in order to justify a doc change;), but I hope to get to it soon!

**Comment by Lu-Do** [comment]
thnks for the reply Michael! well, the exporter's dialog actually lets you choose to include skinning info and animation... i'm just a 3d artist, but i've send a bunch of animated .js to a programmer to put the stuff in his code. it seems to work, although not every time! not sure about what's happening at the moment (the "not well formed" problem), but the problem could be exactly the same you pointed out. before binding the skin in maya all object should have no history and freezed transformation... not sure anyway, i need the programmer feedback on this. i will anyway try to work with .dae too.
cheers!

**Comment by MichaelHazani** [comment]
Interesting, didn't know those translated well to JSON! Very impressive. 
I'll dig into it further and update if I learn anything new in the matter. Thanks for the tip!
