### ISSUE TITLE
three.js : unresponsive script on firefox and chrome

### ISSUE THREAD

**Issue by hemantchhabra** [mrdoob/three.js#6614]
Hello people.
We are working on a OBJMT loader inside three.js, where we are trying to load the OBJ model and MTL file with textures in JPEG/TGA/JPG. We successfully tested the code with a 3mb model, but as soon as we shifted to a 20+mb model, the browsers(chrome, firefox) started crashing with the following error of unresponsive script : 
Now we are not quite sure of what it suggests us to do, and being a newbie. Can any advance user of three.js here suggest us a better way to do it? Maybe model size wouldn't be the problem either, but I really can't understand the problem here as of now.
![error](https://cloud.githubusercontent.com/assets/5680977/7854870/cd47a4ca-053a-11e5-8ac9-92f3018a4e17.PNG)
PS: we have tested it on Mac and Windows both

**Comment by mrdoob** [comment]
`OBJMTLLoader` is currently not very optimised. Try using `OBJLoader` instead.

**Comment by hhanifkhan** [comment]
i tried OBJLoader its working fine, but now how to load materials .mtl file with object. can you share any example. please check code snippet http://stackoverflow.com/questions/30553277/three-js-unable-to-load-mtl-file-using-mtlloader

**Comment by hemantchhabra** [comment]
I'll wait for mrDoob to reply.

Hemant Chhabra <http://brhetoric.tumblr.com/>,
Student Of Industrial Design (TGD),
National Institute of Design,
09711847771
07874194234
