### ISSUE TITLE
SkinnedMesh documentation is out of date

### ISSUE THREAD

**Issue by erbridge** [mrdoob/three.js#6620]

**Comment by VinaySingh035** [comment]
Is there anything needed to be done regarding this issue?

or this has been done.

**Comment by mrdoob** [comment]
I don't know. I think I'll close it as it wasn't very clear.

**Comment by erbridge** [comment]
Yes, sorry for not being clear. The docs were describing a (very) old version of the API, but they appear to have been updated.

**Comment by VinaySingh035** [comment]
Thanks for the updated information @erbridge .
