### ISSUE TITLE
ThreeJs Canvas Element Order in DOM

### ISSUE THREAD

**Issue by isaachinman** [mrdoob/three.js#6622]
I am using ThreeJs in conjunction with AngularJs to build a data visualisation web app. Through Angular, I have built a SPA that uses routing to compile pages.

My ThreeJs script is in one of these partials. I have ThreeJs rendering into an existing canvas element, which is inside the main page partial. However, when ThreeJs actually runs, it moves the canvas element to the very end (directly above the body closing tag).

Because ThreeJs is moving the existing canvas element out of place, the Angular routing isn't working correctly. Is it possible to prevent ThreeJs from doing this? I've seen examples in which ThreeJs animates to an existing element and remains in place - strange.

**Comment by isaachinman** [comment]
I was able to get around this by appending the renderer to a container div:

    document.getElementById("canvas-container").appendChild(renderer.domElement);

Strange that the default behaviour is to put the canvas at the very end of the body.

**Comment by Usnul** [comment]
I would find it hard to imagine that "three.js" would move its renderer's dom element. It's much more likely that angular rebuilds dom and happens to throw everything that's not "it" to the end of the container as an afterthought. Three.js doesn't care where that domElement is going to live.

**Comment by isaachinman** [comment]
That would make sense, and was my first thought, but I don't think it's entirely right.

[Take a look at this jsfiddle](https://jsfiddle.net/fek9ddg5/74/). Just vanilla js, but DOM elements are still being reordered.

**Comment by Usnul** [comment]
also, try css:
```css
z-index:2;
position:absolute;
```
just may be enough for your problem to be solved.

**Comment by isaachinman** [comment]
@Usnul I solved the problem by appending to a DOM element, like this:

    document.getElementById("canvas-container").appendChild(renderer.domElement);

Raising the z-index and setting position to absolute is a ridiculous hack-fix.

**Comment by Usnul** [comment]
i'm trully inspired:
```js
container = document.getElementById( 'canvas' );
document.body.appendChild( container );

renderer = new THREE.WebGLRenderer();
renderer.setSize( CANVAS_WIDTH, CANVAS_HEIGHT );
container.appendChild( renderer.domElement );
```
please see:
https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild
to understand what happened in your code.
