### ISSUE TITLE
Uniform

### ISSUE THREAD

**Issue by AliHammoud** [mrdoob/three.js#6626]
Hello guys!

I'm trying to pass a float array as a uniform for my shader in r71 (`userDef: {type: "vf1", value: unifs}`). Where `unifs` is an array of 9 floats. A 3x3 kernel specifically. (Now, I'm better off using `v3v` anyways, but I'd like to know if there's anything wrong)

The window then spits out the following alert:
>"TypeError: Failed to execute 'uniform1fv' on 'WebGLRenderingContext': No function was found that matched the signature provided."

__Object+material:__
```
      var
        imgGeo = new THREE.PlaneBufferGeometry(WINASPECT, 1, 1, 1),
        imgMat = new THREE.ShaderMaterial({
          uniforms: {editImg: {type: "t", value: texture},
                     imgWidth: {type: "f", value: IMGWIDTH},
                     imgHeight: {type: "f", value: IMGHEIGHT},
                     userDef: {type: "vf1", value: unifs}
                    },
          vertexShader: vS,
          fragmentShader: fS
        }),
        imgObj = new THREE.Mesh(imgGeo, imgMat);
```

__Shader:__
```
<script name="custom3x3"
          id="fragmentShader_10"
          type="x-shader/x-fragment" >

    varying vec2 vUv;
    uniform sampler2D editImg;
    uniform float imgWidth;
    uniform float imgHeight;
    uniform vec3 userDef[3];

    void main(){

      vec4 img = texture2D(editImg, vUv);
      vec4 clr = vec4 (0.0, 0.0, userDef[0], 1.0);
      gl_FragColor = clr;

    }

  </script>
```

Please let me know how I could pass a float array as a uniform in r71.

Thanks!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
