### ISSUE TITLE
Rotate Geometry with THREE.ShaderMaterial on it 

### ISSUE THREAD

**Issue by Prieston** [mrdoob/three.js#6627]
My problem is that when i try to apply [this example] (http://threejs.org/examples/#webgl_shaders_ocean) at my project where i need the "skyBox and the "mirrorMesh" to be rotated at the x axis the texture is distorted. How can i rotate the skyBox or the planebufferGeometry with the material rotated with the Geometry? I am new to Three js so if this is a silly question my apologies .!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by Prieston** [comment]
oke :) sorry for not reading the guidelines
