### ISSUE TITLE
CanvasRenderer not working in IE 10

### ISSUE THREAD

**Issue by hoschi** [mrdoob/three.js#6628]
As far as I got it from stackoverflow and other (outdated/closed) issues, CanvasRenderer should work in IE 10, because it supports at least normal canvas. But the only example of 'threejs.org's example site which works is the ASCII renderer. No error in web console, just blank white. When I start the profiler I see methods of three.js which do stuff but there is no image/animation. I use a VM to test this, perhaps it causes this problems?

![2015-06-01-201043_1714x1409_scrot](https://cloud.githubusercontent.com/assets/163128/7919678/4afb081e-089a-11e5-8517-f2bbe506bea0.png)

**Comment by titansoftime** [comment]
Same problem on my machine.

**Comment by mrdoob** [comment]
I don't have a windows machine. If someone could help with this would be great 😄

**Comment by hoschi** [comment]
@titansoftime do you also run it in a VM or on bare metal?

**Comment by dubejf** [comment]
I was able to reproduce in IE 11 with in compatibility mode (IE 11 in normal mode is okay).

window.devicePixelRatio is undefined in IE 10, which lead to a canvas with width = 0 and height = 0.

The code for dpr should be changed to: window.devicePixelRatio || 1;

**Comment by hoschi** [comment]
here are VMs for all they need it for testing: http://dev.modern.ie/tools/vms/

@dubejf I'll check this out, thanks!

**Comment by dubejf** [comment]
As a workaround, the device dpr can also be calculated as:  window.screen.deviceXDPI / window.screen.logicalXDPI;

**Comment by titansoftime** [comment]
Nah standard PC setup.

**Comment by hoschi** [comment]
@dubejf it works, thanks!
