### ISSUE TITLE
Exporting blender animation

### ISSUE THREAD

**Issue by Eurydicee** [mrdoob/three.js#6630]
Hey guys,

yes, again someone who has problems with blender and exporting some meshes.
i'm not a pro in blender, but i have tried everything and now i'm on the point, where i need the help of the three.js community.

all i want is only a simple walking men animation in my 3d world. but somehow, blender don't want to make me happy :<

i hope someone can help me, its really important for my university project. how can i solve this problem?
many thanks in advance.

here a screenshot of the blender error message:
![error_screenshot_blender](https://cloud.githubusercontent.com/assets/4707411/7924168/4b7ac508-08b9-11e5-9bb3-3c9104afe911.png)

here the blender file:
http://www.filedropper.com/walking_1

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
