### ISSUE TITLE
OBJLoader breaks normals of mesh with CanvasRenderer

### ISSUE THREAD

**Issue by hoschi** [mrdoob/three.js#6631]
The latest version of OBJLoader doesn't assign normals right, I think. I had do switch to a version which uses `Geometry` instead of `BufferGeometry` to get the expected result.

current loader: https://github.com/mrdoob/three.js/blob/de657cc6053c9abd1d3fb434895fc6a62376d3f9/examples/js/loaders/OBJLoader.js
old loader (which works): https://github.com/mrdoob/three.js/blob/a321ba05/examples/js/loaders/OBJLoader.js

All other files are fetched from tag 'r71'. I made screenshots which shows the result with `MeshNormalMaterial` assigned to the loaded meshes.

current loader - webgl renderer:
![current loader - webgl renderer](https://cloud.githubusercontent.com/assets/163128/7930839/2e89e034-090c-11e5-9423-2f1a2ba93eaf.png)

current loader - canvas renderer (not expected)
![current loader - canvas renderer (not expected)](https://cloud.githubusercontent.com/assets/163128/7930842/336a5778-090c-11e5-8a55-904ffb4ed396.png)

old loader - webgl renderer
![old loader - webgl renderer](https://cloud.githubusercontent.com/assets/163128/7930847/3c992a72-090c-11e5-92cc-bf2bf481b39c.png)

old loader - canvas renderer
![old loader - canvas renderer](https://cloud.githubusercontent.com/assets/163128/7930848/41ca5d90-090c-11e5-910c-a02a54c7862b.png)

**Comment by mrdoob** [comment]
Fixed: 60e08de98462fb7823d37d07c7397a65bbb08a0d Thanks!
