### ISSUE TITLE
Example - Loader Collada on iOS

### ISSUE THREAD

**Issue by leonardook** [mrdoob/three.js#6633]
Hello,
I'm trying to run the collada loader example from the website http://threejs.org/examples/#webgl_loader_collada on iOS and not being able to.
 
This is what i get:

![img_0001](https://cloud.githubusercontent.com/assets/1542218/7937560/13ffeb5e-0917-11e5-9dce-07c9e8757895.PNG)

I tried on Safari, Chrome and my own webview (with the files local to the iPad), all with the same result. The other examples with collada seem to be working fine on the browsers.

On my webview I used Three JS rev71. 
The ipad I'm using is an iPad 2 with iOS 8.1.2.
The Chrome app used was version 43.0.2357.51

Using Safari's debugger I was able to retrieve these two errors:

[Error] THREE.WebGLShader: Shader couldn't compile.
	error (three.min.js, line 2)
	(função anônima) (three.min.js, line 591)
	(função anônima) (three.min.js, line 587)
	v (three.min.js, line 487)
	renderBuffer (three.min.js, line 549)
	k (three.min.js, line 450)
	render (three.min.js, line 561)
	render (webgl_loader_collada.html, line 182)
	animate (webgl_loader_collada.html, line 159)
	(função anônima) (webgl_loader_collada.html, line 73)
	parse (ColladaLoader.js, line 204)
	onreadystatechange (ColladaLoader.js, line 77)

[Error] THREE.WebGLProgram: shader error: 0 gl.VALIDATE_STATUS false gl.getPRogramInfoLog 
	error (three.min.js, line 2)
	(função anônima) (three.min.js, line 588)
	v (three.min.js, line 487)
	renderBuffer (three.min.js, line 549)
	k (three.min.js, line 450)
	render (three.min.js, line 561)
	render (webgl_loader_collada.html, line 182)
	animate (webgl_loader_collada.html, line 159)
	(função anônima) (webgl_loader_collada.html, line 73)
	parse (ColladaLoader.js, line 204)
	onreadystatechange (ColladaLoader.js, line 77)

**Comment by leonardook** [comment]
I also tried with the latest dev revision 72dev and got these errors:

[Error] THREE.Line: THREE.LinePieces mode has been removed. Use THREE.LineSegments instead.
	Line (72devthree.min.js, line 369)
	init (webgl_loader_collada.html, line 104)
	(função anônima) (webgl_loader_collada.html, line 72)
	parse (ColladaLoader.js, line 204)
	onreadystatechange (ColladaLoader.js, line 77)

[Error] THREE.WebGLShader: Shader couldn't compile.
	(função anônima) (72devthree.min.js, line 592)
	(função anônima) (72devthree.min.js, line 589)
	k (72devthree.min.js, line 488)
	renderBufferDirect (72devthree.min.js, line 540)
	f (72devthree.min.js, line 481)
	render (72devthree.min.js, line 551)
	render (webgl_loader_collada.html, line 182)
	animate (webgl_loader_collada.html, line 159)
	(função anônima) (webgl_loader_collada.html, line 73)
	parse (ColladaLoader.js, line 204)
	onreadystatechange (ColladaLoader.js, line 77)

[Error] THREE.WebGLProgram: shader error:  0 gl.VALIDATE_STATUS false gl.getProgramInfoLog  ERROR: too many uniforms 
	(função anônima) (72devthree.min.js, line 589)
	k (72devthree.min.js, line 488)
	renderBufferDirect (72devthree.min.js, line 540)
	f (72devthree.min.js, line 481)
	render (72devthree.min.js, line 551)
	render (webgl_loader_collada.html, line 182)
	animate (webgl_loader_collada.html, line 159)
	(função anônima) (webgl_loader_collada.html, line 73)
	parse (ColladaLoader.js, line 204)
	onreadystatechange (ColladaLoader.js, line 77)

**Comment by mrdoob** [comment]
I'm seeing this error...

![screen shot 2015-06-06 at 00 18 12](https://cloud.githubusercontent.com/assets/97088/8016872/8b28ef2e-0be1-11e5-9fe2-7b2d110292c2.png)
