### ISSUE TITLE
Editor: Dynamic change to MeshFaceMaterial

### ISSUE THREAD

**Issue by rfm1201** [mrdoob/three.js#6636]
I’m trying to expend the three.js editor to allow a switch from any material to MeshFaceMaterial.
I have almost done the thing but have a problem when I change the material of the mesh to a MeshFaceMaterial.
It doesn’t work. The first material of the materials array (of the MeshFaceMaterial instance) is used as if it was the material. I thought I was missing a needsUpdate in the MeshFaceMaterial, but there is no needsUpdate for this material.
If I close my browser and reopen it with the saved scene in localStorage, everything works as expected.

I made a jsfiddle to show my problem, it’s http://jsfiddle.net/bc7hndwg/
If you use the Lambert or Normal button it works. The Face button failed set the material as it should.

What must be changed in the setFace function code to set correctly the MeshFaceMaterial (each face with a specific color, not all yellow)?

Thanks for any tip.

**Comment by poofik** [comment]
MeshFaceMaterial looks like will be gone from next version 72 :(

**Comment by rfm1201** [comment]
Bad news for me.
Thanks

**Comment by titansoftime** [comment]
There is light at the end of the tunnel.

> "When I started the WebGLRenderer refactoring I decided to remove MeshFaceMaterial to keep things simple. But while refactoring I realised that we could add materials to BufferGeometry.drawcalls and bring back MeshFaceMaterial." MrDoob #6618

**Comment by WestLangley** [comment]
This is now outdated. Please file a new issue if needed.

**Comment by Mugen87** [comment]
The reason why I left this issue open last year was the fact that the editor does not support choosing multiple materials per mesh. E.g. if you add an instance of `BoxGeometry` to the scene, you can only select a single material although it's possible to add a material per side.

The editor could inspect the geometry and provide a material slot per `BufferGeometry.group`.

**Comment by WestLangley** [comment]
@Mugen87 It is better to create a new issue in that case that is relevant to the current three.js revision.
