### ISSUE TITLE
Documentation. Quaternion. Dot function

### ISSUE THREAD

**Issue by AlexeyGapon** [mrdoob/three.js#6640]
Hello. Didn`t find descripton of  "dot" function http://threejs.org/docs/#Reference/Math/Quaternion 
what should i pass to this function as an argument?

**Comment by erichlof** [comment]
Hi, judging from the underscore notation of the argument's members (_x, _y, etc.) in the dot method's body , the dot method must take another quaternion as its argument. I haven't seen many dotted quaternions in code examples though. I'm curious, what are you needing this for?

**Comment by AlexeyGapon** [comment]
I want to understand how it works.
