### ISSUE TITLE
Cancel loader method?

### ISSUE THREAD

**Issue by SirNeuman** [mrdoob/three.js#6641]
Hi I recently asked this question essentially, but it was a rather long post and got tagged as "Help (use StackOverflow)" and was closed without any other response. I did ask this on stackoverflow but got no response there. so I'll ask in a way that hopefully makes more sense to be asked here and hopefully I get an actual response this time, and I'll keep it short.

Is there any way to cancel a "loader" from loading an object?  and if not I would like to make a request for such a method in the loader object. For example, 
```
var loader = new THREE.STLLoader();

function loadMyObj(url){
    loader.load(url, function(object){
        scene.add(object);
    }
}

function cancelLoad(){
    loader.cancel();
}
```

**Comment by antont** [comment]
at least the underlying xmlhttprequest biz seems to have an abort() method: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#abort()

could you try doing this yourself using that, perhaps send a pull request if manage to make it nicely?

**Comment by SirNeuman** [comment]
I will try

**Comment by SirNeuman** [comment]
yes. Ok so i essentially followed the suggestion as posted here: http://stackoverflow.com/questions/24982978/cancel-download-jsonloader-imageutils-loadtexture

Anyway, I'm not sure if a pull request is necessary since I didn't add any functions, but rather just ended up returning the original xmlhttprequest object. This is how I handled it:

In THREE.XHRLoader.prototype (in Three.js) i just added return request to the end of the load function:
```
THREE.XHRLoader.prototype = {

    constructor: THREE.XHRLoader,
    load: function ( url, onLoad, onProgress, onError ) {

    }
        
```

**Comment by SirNeuman** [comment]
Actually, for when I do download a new version of ThreeJS I'll want this functionality for the loader object (so I don't break the code i just wrote). So this is only my temporary solution. What i'm going to do isork and implement this functionality for the loader object (ill call it loader.cancel() or loader.abort(), which sounds better?), reimpliment those changes into my project, and then make a pull request.

**Comment by poofik** [comment]
You can try getting the data directly with AJAX.

```javascript
$.ajax(js,{
    {          contentType: "application/zip",
      beforeSend: function (req) {
        req.overrideMimeType('text/plain; charset=x-user-defined'); //important - set for binary!
      },
      success: function(data){
          try {
              data = JSON.parse(data);

              var loader = new THREE.ObjectLoader(manager);
              //loader.setTexturePath(textures); //v71
              //loader.parse(data,callbackObject); //v71
              //=======================================
              callbackObject(loader.parse(data)); //v72
          } catch (e) { //zip file was probably not found, load regular json
              console.log("error catch " + e + " " + js.slice(0, -4) + ".json");
          }
      },
      error: function(xhr, textStatus, errorThrown){
          alertify.alert("3D Model (" + js + ") Loading Error");
      }
    });}
```

**Comment by antont** [comment]
@SirNeuman yes I think even just adding that return might be a nice pull request -- useful changes to code can be just (even tiny) modifications to existing functions, new functions are not a requirement for pull reqs..

I don't know whether just having that return and doing the cancel in your app, or indeed having it a part of the loader, would be better .. I guess can be nice in the loader if everyone always wants it the same way, but don't know whether that's the case.

**Comment by SirNeuman** [comment]
Ok I submitted a pull request. I only altered the STLLoader object and the XHRLoader. Though any Loader that uses the XHRLoader can be pretty easily manipulated to return the XMLHttpRequest object in its load function. I could go through all the loaders and include them in another pull request if my pull gets accepted or if that seems useful to other people.

**Comment by antont** [comment]
yep seemed good to me with a quick look at least, thanks. i figure i'll sit back and listen what the guys who've actually worked on this here think. and let it sink and ponder a bit myself too while waiting views from others.

**Comment by mrdoob** [comment]
Conversation continuing in the PR: #6649.
