### ISSUE TITLE
Raycaster not working when PointCloud scaling is negative.

### ISSUE THREAD

**Issue by HappyOli** [mrdoob/three.js#6642]
When a PointCloud object have a negative value for any of the scale axis, whatever threshold value is set, not points gets picked as the localThreshold value become negative and the following test is always false:

if ( rayPointDistance < localThreshold ) {

I can make things work by making localThreshold an absolute value:

var localThreshold = Math.abs(threshold / ( ( this.scale.x + this.scale.y + this.scale.z ) / 3 ));

**Comment by mrdoob** [comment]
@WestLangley what do you think?

**Comment by WestLangley** [comment]
three.js does not support reflections in the object matrix -- it only supports pure rotations and positive scale factors.

**Comment by HappyOli** [comment]
Since rayCasting deals with distance and not coordinates, I thought it makes sense to  add the Math.abs since it doesn't make sense for a distance to be negative. 

Apart from raycasting, negative scale factors (on PointCloud) works pretty well for me. I'm using the reflection to convert data points from left hand <-> right hand depending on the asset currently loaded. 

Thanks for the response and good job with three.js!

**Comment by WestLangley** [comment]
Your `abs` is in the wrong place, anyway.

    var localThreshold = threshold / ( ( Math.abs( this.scale.x ) + Math.abs( this.scale.y ) + Math.abs( this.scale.z ) ) / 3 );

But given that the formula is somewhat of a hack, and three.js does not support negative scale factors in general, I am not sure we should do it.

**Comment by Usnul** [comment]
What is a negative scale in physical space? What is a negative distance between two points in space (i mean length of separation vector)?

**Comment by WestLangley** [comment]
(1) a reflection in object space, (2) a signed distance -- not applicable in this case.
