### ISSUE TITLE
WebVR APIs need to be updated in VREffect

### ISSUE THREAD

**Issue by daoshengmu** [mrdoob/three.js#6650]
Hi @dmarcos @mrdoob ,

I notice that WebVR APIs have been changed. We can refer the new APIs here, https://developer.mozilla.org/en-US/docs/Web/API/HMDVRDevice/getEyeParameters .

I don't know if there is any browser that still uses the older one. I didn't try the WebVR demo on Chrome yet. And on Firefox nightly, it works well.
```
var leftEyeParams = vrHMD.getEyeParameters("left");
var rightEyeParams = vrHMD.getEyeParameters("right");
this.leftEyeTranslation = leftEyeParams.eyeTranslation;//vrHMD.getEyeTranslation( "left" );
this.rightEyeTranslation = rightEyeParams.eyeTranslation;//vrHMD.getEyeTranslation( "right" );
this.leftEyeFOV = leftEyeParams.recommendedFieldOfView;//vrHMD.getRecommendedEyeFieldOfView( "left" );
this.rightEyeFOV = rightEyeParams.recommendedFieldOfView;//vrHMD.getRecommendedEyeFieldOfView( "right" );
```

We also can refer the new version VREffect.js here, https://github.com/MozVR/vr-web-examples/blob/master/threejs-vr-boilerplate/js/VREffect.js

**Comment by dmarcos** [comment]
@daoshengmu  The updated version of VREffect has not made it yet to master but it's properly updated on the dev branch: 

https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/VREffect.js

You should be using that one.

**Comment by daoshengmu** [comment]
@dmarcos. Thanks for your reply.
