### ISSUE TITLE
[R71] transparency/opacity warning

### ISSUE THREAD

**Issue by ilanusse** [mrdoob/three.js#6651]
I have a simple scene (a plane with a mesh placed on it) and for some reason I can't get rid of a warning that reads ```THREE.Loader: transparency has been renamed to opacity```.

I believe it has something to do with Three.js's source code since it's my only Bower dependency.

**Comment by ilanusse** [comment]
Bower dependencies:

```json
 "dependencies": {
    "threejs": "r71"
  }

**Comment by poofik** [comment]
It means inside your 3D model json file you are using 
```javascript
...
transparency: 0.5,
```
it should read
```javascript
...
transparency: true,
opacity: 0.5
```

**Comment by ilanusse** [comment]
This fixed the problem, thanks!
