### ISSUE TITLE
Documentation enhancement.

### ISSUE THREAD

**Issue by sukhwant** [mrdoob/three.js#6652]
I think documentation needs to be worked on. My suggestions:

a.Many things are not in the documentation itself like THREE.audio etc.
b. The parameters or methods available for each module need more explanation so that it is easier to understand even to beginners fulfilling the goal of three.js.
c. Proper documentation of examples - how and why things are done this way.

If no one is currently working in this direction or need help I would do it, making things easier for others.

**Comment by mrdoob** [comment]
Have a look at issue #5411.
