### ISSUE TITLE
Artifacts outside shadows

### ISSUE THREAD

**Issue by SkaceKamen** [mrdoob/three.js#6657]
I'm trying to add dynamic shadows to my game using DirectionLight that follows the character (so it renders shadows only around character) but I got stuck with weird issue.
Space outside shadows is either full of artifacts, for PCFSoftShadowMap, or slightly darker for PCFShadowMap.
At the beginning, there is no issue, but it sometimes (for one specific objects always) switches between ok and weird, when object is added or removed.

**Tested:**
Threejs 71, 72dev
FF 38.0.5, Chrome 43.0
Windows 7
Nvidia GeForce 960 (Drivers 353.06)

**DirectionalLight settings:**
light.castShadow = true;
light.shadowCameraLeft = -75;
light.shadowCameraRight = 75;
light.shadowCameraTop = 75;
light.shadowCameraBottom = -75;
light.target = player;
light.shadowBias = 0.00001;
light.shadowDarkness = 0.5;
light.shadowCameraNear = 1;
light.shadowCameraFar = 500;
light.shadowMapWidth = 2\*1024;
light.shadowMapHeight = 2\*1024;
*(and it moves with the player)*

Issue with PCFSoftShadowMap: 
![shadow-issue](https://cloud.githubusercontent.com/assets/2076742/8025689/31419e14-0d5f-11e5-97d9-338baf77aefe.png)
Issue with PCFShadowMap:
![shadow-issue-2](https://cloud.githubusercontent.com/assets/2076742/8025692/4ff6ea3a-0d5f-11e5-9bbb-ca2d958d217a.png)
How it should look:
![shadow-normal](https://cloud.githubusercontent.com/assets/2076742/8025693/5898f534-0d5f-11e5-905c-4657195cb22c.png)

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

If you are not sure if it is a three.js bug, we prefer you first seek help on stackoverflow.

If you can demonstrate a three.js bug, can you provide a test case so we can reproduce your results? Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by SkaceKamen** [comment]
I finally found it's issue caused by materials having THREE.DoubleSide. I'll try to reproduce it

**Comment by SkaceKamen** [comment]
Here is the bug reproduced: http://jsfiddle.net/7wbwob11/
You can see the artifacts on both objects, when you set side to Front, issue dissapears

**Comment by mrdoob** [comment]
So the floor is using `THREE.BoxGeometry`? Try using `THREE.PlaneGeometry` instead.

**Comment by SkaceKamen** [comment]
I changed i to plane in example. Also, tried to set castShadow for the ground to true, which actually started the issue for the ground as well, leading me to beliveve, that it's caused by combination of DoubleSide and castShadow

**Comment by WestLangley** [comment]
The first fiddle does not show the problem for me. The second one does. It can be fixed on my machine by setting

    dirLight.shadowBias = - 0.0001

**Comment by SkaceKamen** [comment]
(In first fiddle, it appears only on the shapes, not ground.)
Negative shadowBias fixed it, didn't know it even accepts negative values. I was so sure it's a bug ...
Sorry for wasting your time and thanks for help.
