### ISSUE TITLE
Three.js demos crashing Chrome on Nexus 6

### ISSUE THREAD

**Issue by dragozov** [mrdoob/three.js#6658]
Device: Nexus 6
OS: Android 5.1
Chrome version:  43.0.2357.92 (same was happening in 40.0)
Other devices tested and working fine: Nexus 5 with Chrome 43.0.2357.92 and Nexus 7 with 42.0.2311.111

Description: Opening pretty much any demo from the ThreeJS.org website (like http://carvisualizer.plus360degrees.com/threejs/) causes Chrome to crash with "Unfortunately Chrome has stopped".

**Comment by toji** [comment]
I can repro on a Nexus 6 we have in office. I'll dig some more to try and find out what the problem is.

**Comment by toji** [comment]
Looks like the GPU driver is crashing during glLinkProgram. I've created a Chrome ticket for the issue (https://code.google.com/p/chromium/issues/detail?id=498947) and recommend closing this bug since it's not really three.js specific.

**Comment by mrdoob** [comment]
Thanks!
