### ISSUE TITLE
Could I publish a featured project

### ISSUE THREAD

**Issue by threepark** [mrdoob/three.js#6659]
Hello Mr.doob. I have a three.js based project([ThreePark](http://threepark.net/English)) and I want to publish it as a featured project. I have searched several places and could not find the instructions on how to publish it. [ThreePark](http://threepark.net/English) is an online 3d model design website, which using subdivision modeling technology, and its vision is to make everyone could do 3d designs. This is a personal website, and modeling service is free forever.

**Comment by makc** [comment]
Unless @mrdoob started taking money for placement, this was answered in #4821

**Comment by threepark** [comment]
Thanks for your guidance. I believe my website will be a new star in 3D design field.

**Comment by mrdoob** [comment]
It's actually pretty cool! 😃

**Comment by mrdoob** [comment]
Shared it on the g+ page by now:
https://plus.google.com/+ThreejsOrg/posts/WsVZjD5JDAY

**Comment by threepark** [comment]
Thanks for your sharing, the website will continue move on, and give more real useful things: Make virtual world real.

**Comment by mrdoob** [comment]
Keep going!
