### ISSUE TITLE
LOD created with clone() do not work

### ISSUE THREAD

**Issue by Astrak** [mrdoob/three.js#6661]
Hello,

It seems like clone() method applied to a LOD object do not applies correctly. 

![sans titre](https://cloud.githubusercontent.com/assets/10037511/8036602/2d6196e2-0df9-11e5-80de-ff2301365d85.png)

Here is a picture : the left LOD shows a green transparent box, lowest level mesh. At farther distances it should show a red transparent sphere then a blue transparent box. It behaves correctly. On the right is a clone of this LOD. It shows all meshes at once plus the mesh of the distance level.

As WestLangley pointed on stackoverflow, the cloned LOD named LOD2, has twice the children it should : 
![sans titre](https://cloud.githubusercontent.com/assets/10037511/8037106/2dca9d1a-0dfc-11e5-9f08-10254a884c81.png)

Link to the example : http://codepen.io/Astrak/pen/RPVjje
SO question : http://stackoverflow.com/questions/30702588/threejs-lod-clone
Im equiped with i5 (no GPU) and windows 7 here, the issue appears on all browsers.

I use R71

Your job is great and i follow it with care :)

**Comment by sukhwant** [comment]
In .clone() I think 
THREE.Object3D.prototype.clone.call( this, object );

**Comment by Astrak** [comment]
That was it

**Comment by prafullit** [comment]
@WestLangley I think we have to make children NULL after THREE.Object3D.prototype.clone.call(this,object);
And then let individual objects be added .

**Comment by WestLangley** [comment]
@prafullit Yes, that looks right. Thanks.

**Comment by mrdoob** [comment]
How about just this?

```javascript
	THREE.Object3D.prototype.clone.call( this, object );

	for ( var i = 0, l = this.objects.length; i < l; i ++ ) {

		object.objects.push( { object: this.objects[ i ].object.clone(), distance: this.objects[ i ].distance );

	}
```

We should also consider renaming `.objects` to `.levels`...

**Comment by prafullit** [comment]
This is simpler and straight-forward. We should have this.
And also .level makes more sense.

**Comment by mrdoob** [comment]
> This is simpler and straight-forward.

Actually, wouldn't work because `levels` would have wrong object clones...

**Comment by mrdoob** [comment]
Should be fixed now...
