### ISSUE TITLE
BoxGeometry says width and height are accessible as properties. They are not.

### ISSUE THREAD

**Issue by abritinthebay** [mrdoob/three.js#6662]
http://threejs.org/docs/#Reference/Extras.Geometries/BoxGeometry

Running that example then trying `cube.width` or, more likely, `cube.geometry.width` gets undefined. They aren't available as properties at all.

this is because that while `this.widthSegments` etc is [set in BoxGeometry.js](https://github.com/mrdoob/three.js/blob/master/src/extras/geometries/BoxGeometry.js#L21) the `this.width` and `this.height` are not.

They should be (and god would it make many things easier)

**Comment by mrdoob** [comment]
Try with `cube.geometry.parameters.width `

**Comment by abritinthebay** [comment]
Documentation should really be updated then. It currently reads:

> Each of the constructor parameters is accessible as a property of the same name.

This is outright false.

**Comment by mrdoob** [comment]
Indeed indeed. Would you be up for doing a PR fixing the copy?

**Comment by abritinthebay** [comment]
Sure, of course. Just the docs folder in this repo I assume?
