### ISSUE TITLE
Controls are not smooth due to lots of models

### ISSUE THREAD

**Issue by tarun29061990** [mrdoob/three.js#6663]
I am developing a room in threejs and there are lot of models like sofa, walls, floor, curtain, rug, table, wall-panel, etc. (all are 3ds max models). So my problem is the controls are not smooth, I have tried orbital as well firstPersonControls but all are getting janked while operating. Please help?
http://stackoverflow.com/questions/30724760/three-controls-are-not-smooth-due-to-lots-of-models

**Comment by makc** [comment]
merging materials (aka using texture atlases), and then maybe geometry too, might help. but if you simply have too much for your hardware to handle, there will be no magic trick.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
