### ISSUE TITLE
Texture (canvas) serialization

### ISSUE THREAD

**Issue by rfm1201** [mrdoob/three.js#6665]
There is an issue in Texture.js with the current dev version (r72dev) of the toJSON method.

The code make the assumption that this.image is an image.
It can be a canvas.

If it’s a canvas, the serialization can be easy with two options, do nothing or canvas.toDataURL() of the current image in the canvas.

As the serialization of the canvas (as a meaningful object) should be done by the code which introduce the canvas, I think the best option is do nothing and let the owner of the canvas (like me) do the job.

I also have a question about the way the image is serialized when it's on a web server at https://github.com/mrdoob/three.js/issues/6618 8th comment.
I don't find a way to make a direct link to it

**Comment by mrdoob** [comment]
Texture.toJSON() now handles canvas too 😊

**Comment by rfm1201** [comment]
Yes and no, because after restoration it’s an image no more a canvas.

I know it’s the best you can do without external code to be executed (the code that manage the canvas) but I think that it could be useful to be able to save/restore a three.js scene with a canvas and the restored scene to still have a working canvas.

I made a jsfiddle to illustrate my proposition it’s http://jsfiddle.net/oc49a813/3/

You can change the canvas color with the edit. Save clear and restore the scene with the buttons.

If you look at the JavaScript it’s quite traditional. The only change is line 16 where a new member of the THREE.Texture is set. I call it userCanvas but it could be userData as in THREE.Object3D.

There are two external dependencies, one is a modified version of the dev branch of three.js, the other one is the class that makes the canvas alive.

The principle is very simple:
1. THREE.Texture toJSON method serialize the new userCanvas member using its toObject method (it could be his toJSON method but I choose to be consistent with the rest of that method work);
2. THREE.ObjectLoader method parseTextures look for the serialization of the userCanvas member. If the json have a type member, it call the revive method of the class named as type tell. The revive method has 2 parameters, the json and the current texture (for the canvas to know what it’s liked with).
For that part to work I add a stringToFunction method to Texture. I put it in the Texture class to modify just 2 three.js class, it should be at another place.

So the class that manages the canvas need to:
1. Implement a serialization method, toObject (could be toJSON if a string is ok). The toObject method must add a type member to the json with the full name of the class as a string;
2. Implement a revive method that create a new instance of the class, initialize it according to the json it received as first parameter and link it to the texture received as second parameter;
3. Maybe, implement a clone method. I was never called on that method and don’t know if it should bind the cloned instance to the same canvas or to a copy of the canvas. I guess you wil know if that method is needed and what it should do.

I know it means execute external code inside three.js but I think it something usefull at least for people using a canvas in a texture.

**Comment by Mugen87** [comment]
Since this feature request has not come up in all these years, it's okay to close the issue. Serialization/deserialization should ensure to retain image data. If users need a canvas after the deserialization, they can change the image source on app level by manually create a canvas from the image element.
