### ISSUE TITLE
SpritePlugin & Blending

### ISSUE THREAD

**Issue by ebann** [mrdoob/three.js#6666]
The renderer.state.setBlending() tries to optimize calls made to it by remembering the current blending state

However the Sprite plugin do the following during render:
[...]
	gl.enable( gl.BLEND );
[...]
renderer.state.setBlending( material.blending, material.blendEquation, material.blendSrc, material.blendDst );

> It enables the blending without notifying the renderer.
> Which leads to an inconsistent state where the renderer.state thinks that blending is disabled but it's not.

For example:
A Mesh sets the current blending state to THREE.NoBlending.
Then a Sprite with a material.blending=THREE.NoBlending is rendered.
The glBlending is set to true (gl.enable( gl.BLEND );) by the SpritePlugin
And when the SpritePlugins calls renderer.state.setBlending(THREE.NoBlending), the glBlending is not changed to false. As the current blending state is already THREE.NoBlending

**Comment by mrdoob** [comment]
Yeah, this is definitely a bug. Would you be up for doing a PR with the fix?

**Comment by ebann** [comment]
Actually the bug seems to be more present at different places.
- Flares
- Sprites

Not sure about the ShadowMap plugin.


The quickfix is to get rid of those calls, but maybe they were there for some purpose ?
The other way to fix it would be to add a enable/disable blending on the renderer.state.

What do you prefer ?

**Comment by mrdoob** [comment]
> The other way to fix it would be to add a enable/disable blending on the renderer.state.

That sounds good :+1:

**Comment by ebann** [comment]
I would suggest a little bit of testing before merging, I can't do that myself for now.
