### ISSUE TITLE
texture On Geometry

### ISSUE THREAD

**Issue by FahdEnnasri** [mrdoob/three.js#6672]
I'm trying to create geometries with textures, but it doesn't work i don't know why!!!
this is part of my code,  : 
var squareGeometry = new THREE.Geometry();
        squareGeometry.vertices.push(new THREE.Vector3(-0.5,  0.5, 0.0));
        squareGeometry.vertices.push(new THREE.Vector3( 0.5,  0.5, 0.0));
        squareGeometry.vertices.push(new THREE.Vector3( 0.5, -0.5, 0.0));
        squareGeometry.vertices.push(new THREE.Vector3(-0.5, -0.5, 0.0));
        squareGeometry.faces.push(new THREE.Face3(0, 1, 2));
        squareGeometry.faces.push(new THREE.Face3(0, 2, 3));

        var UVS = [
           new THREE.Vector2(0.0, 1.0),
           new THREE.Vector2(0.0, 0.0),
           new THREE.Vector2(1.0, 0.0),
           new THREE.Vector2(1.0, 1.0)
                  ];

          squareGeometry.faceVertexUvs[0][0] = [UVS[0],UVS[1],UVS[2]];
          squareGeometry.faceVertexUvs[0][1] = [UVS[0],UVS[2],UVS[3]];

         var texture = THREE.ImageUtils.loadTexture('textures/img12.jpg');

        var squareMaterial = new THREE.MeshBasicMaterial({
                        map: texture,
                        side:THREE.DoubleSide
                      });

        var squareMesh = new THREE.Mesh(squareGeometry, squareMaterial);
        squareMesh.position.set(1.5, 0.0, 4.0);
        parent.add(squareMesh);
        //scene.add(squareMesh);

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
