### ISSUE TITLE
Import mtl file in threejs Editor

### ISSUE THREAD

**Issue by wizztjh** [mrdoob/three.js#6680]
I am trying to import OBJ's MTL file in threejs editor for material and texture of the obj 3d model.
I want to help out with this if this is not implemented.

I believe it need to follow [JSON Material format](https://github.com/mrdoob/three.js/wiki/JSON-Material-format-4). Can anyone tell the the implementation plan for this?

``` mtl
newmtl material_0
Ka 1.000000 0.000000 0.000000
Kd 1.000000 1.000000 1.000000
Ks 0.000000 0.000000 0.000000
Tr 1.000000
illum 0
Ns 0.000000
map_Kd model_texture.jpg
```

**Comment by makc** [comment]
I was just having fun with obj loaders today. There are two loaders, [one](http://threejs.org/examples/js/loaders/OBJLoader.js) creates single material per object even if there are many, and [another one](http://threejs.org/examples/js/loaders/OBJMTLLoader.js) creates separate mesh per every group of faces that has material assigned (thus potentially creating hundreds or thousands of them). These loaders needs a lot of love.

**Comment by mrdoob** [comment]
Yep. We need to do a new `MTLLoader` and make `OBJLoader` be able to handle the output...

**Comment by wizztjh** [comment]
Found a few documentation of mtl file.

http://web.cse.ohio-state.edu/~hwshen/581/Site/Lab3_files/Labhelp_Obj_parser.htm
http://people.cs.clemson.edu/~dhouse/courses/405/docs/brief-mtl-file-format.html

**Comment by Mugen87** [comment]
@mrdoob I think this issue can be closed. Your commit 6cfda9b71b3456ff095233a70785fa30a7080526 from 2017 added the possibility to load `OBJ/MTL` files if they are organized in a zip file.
