### ISSUE TITLE
Three.js apps on Note 4

### ISSUE THREAD

**Issue by dan-morton-youvisit** [mrdoob/three.js#6683]
I have noticed that when attempting to run Three.js apps on Note 4, tested using chrome, WebGL often crashes. When it doesn't crash it is just all white.

**Comment by mrdoob** [comment]
Do you know what GPU does your Note 4 have?

**Comment by MasterJames** [comment]
I got this info...
Adreno 420 (SM-N910S)
Mali-T760 (SM-N910C)
from...
http://www.gsmarena.com/samsung_galaxy_note_4-6434.php&ved=0CBsQFjAA&usg=AFQjCNGGz7Ba8MGPPgYRXxvsKpOgx9KKNg&sig2=CMhCPjLgGk-JInlEiVfPgA

There is an App at Google Play called...
CPU / RAM / DEVICE Identifier
that might be best to double check this?

is there any pending OS update to your phone available?

**Comment by Mugen87** [comment]
Closing. We can reopen the issue if the problem still exists.
