### ISSUE TITLE
BufferGeometry could use removeAttribute method

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6684]
I mean, I could remove it by hand from .attributes(Keys), but this makes incapsulation gods angry.

**Comment by WestLangley** [comment]
What would be your use case for this feature?

**Comment by makc** [comment]
well, in this case I needed to remove normals and uvs from obj loader output. I agree that eventually I would convert to json and do not load useless data.

**Comment by RemusMar** [comment]
> well, in this case I needed to remove normals and uvs from obj loader output.

You're looking for all kind of "useful" features ...

**Comment by makc** [comment]
Yes, well because I had a code already that merges geometries taking into account all of the attributes, so two vertices with different UVs would be left as two different vertices. Where I needed them to merged to build connected graph out of triangle edges, so I had to remove UVs. And normals. Sorry if this is not useful to you personally.

**Comment by RemusMar** [comment]
> Sorry if this is not useful to you personally.

All these operations should be performed in the 3D modeler (before exporting the file).
It's faster and with much better results.
If we continue to bloat THREE with all kind of "amazing" features, we'll end up with an "amazing" result.

cheers

**Comment by makc** [comment]
that's why there were like 5 issues asking for broserify/amd support. so you don't have to worry about somebody else feature request taking extra 100 bytes from your build.

**Comment by RemusMar** [comment]
> so you don't have to worry about somebody else feature request taking extra 100 bytes from your build.

Ask Ricardo (mrdoob) why UTF8Loader (the best one except SEA3D) is not included into the main package.

**Comment by donmccurdy** [comment]
BufferGeometry now has a [`.removeAttribute` method](https://threejs.org/docs/#api/core/BufferGeometry.removeAttribute).

**Comment by jocabola** [comment]
I don't think it exists a removeAttribute method as above but you can create your own method and do as follows:

```
let attr = geo.getAttribute(name);
delete attr.array;
delete geo.attributes[name];
```

**Comment by makc** [comment]
@jocabola it is because they renamed it to deleteAttribute [rcently](https://github.com/mrdoob/three.js/commit/764bc3dbbc57b696277b77e648be3857ca3e4b25#diff-81bbb61e0536473b678e50afe25d29b9)

**Comment by jocabola** [comment]
Thanks @makc it looks like this method is not supported on primitives like `PlaneBufferGeometry`, at least as for v109 which I am using in my current project.. Either way, I solved it manually as posted before.

**Comment by jocabola** [comment]
Thanks!
