### ISSUE TITLE
Cannot display obj mtl captured with structure scanner

### ISSUE THREAD

**Issue by gooodguy** [mrdoob/three.js#6686]
Hi, 

I have 3d scanned an object with an iPad and structure's scanner (http://structure.io). It produces a obj, mtl and a jpg file. I want to display it in the browser. So I came across three.js and the obj/mtl example, where I removed the DDSLoader and adjusted the file paths. I tried to load my model, but it fails. It seems that the files do not conform the standard or at least not the way Three.js expects it. Could someone give me a hint how I could fix this? 

Here is the original model: http://www.mediafire.com/download/5olw7ie89yewd8k/ModelKaktus.zip

**Comment by RemusMar** [comment]
That OBJ file is messed up.
You need a 3D modeler (3DS Max) to import, rebuild and re-export that model.
Example: http://necromanthus.com/Test/html5/cactus.html 

cheers

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
