### ISSUE TITLE
setting linewidth on LineBasicMaterial affects MeshBasicMaterial with wireframe=true

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6687]
![screen shot 2015-06-13 at 15 57 10](https://cloud.githubusercontent.com/assets/242577/8144588/91e28d02-11e5-11e5-8f6c-72d9a6a8d6fb.png)
in this case, setting white line to 4px affects unrelated mesh. if it matters, the mesh is added later than line.

**Comment by mrdoob** [comment]
Could you create a jsfiddle?

**Comment by makc** [comment]
[Here](http://jsfiddle.net/z0ocg83c/1/). Apparently happens only with buffer geometry.

**Comment by WestLangley** [comment]
Removed everything from the fiddle that was unrelated to the issue. http://jsfiddle.net/z0ocg83c/3/

`BufferGeometry` and `wireframe: true` do not go well together because edges are missing. Instead use this pattern:

    helper = new THREE.WireframeHelper( mesh );

updated fiddle: http://jsfiddle.net/z0ocg83c/4/

**Comment by mrdoob** [comment]
Fixed.
