### ISSUE TITLE
why does raycast require material?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6688]
there is this code in mesh:

![screen shot 2015-06-13 at 19 59 46](https://cloud.githubusercontent.com/assets/242577/8145395/cef3ba1a-1206-11e5-981d-ca62271c5a78.png)

why? just asking about the reasoning.

**Comment by mrdoob** [comment]
Good question. Because the `material.side` [check](https://github.com/mrdoob/three.js/blob/dev/src/objects/Mesh.js#L139-L147) (which can probably be simplified).

**Comment by WestLangley** [comment]
> which can probably be simplified

Notice the winding order is different in the two cases.

**Comment by makc** [comment]
>  Because the material.side check 

but why can't you assume default value without material?

**Comment by WestLangley** [comment]
@makc Please be more specific.

**Comment by makc** [comment]
well imagine a sphere and a ray piercing it - regardless of material.side setting, there must be at least one intersection.

so what I am saying, why can't mesh without material behave as if it had front side setting (default in any material, right ?)

**Comment by WestLangley** [comment]
> otherwise you end up in situations when there is intersection either way, but you report none.

@makc We do? Please be more specific.

> well imagine a sphere and a ray piercing it - regardless of material.side setting, there must be at least one intersection.

Not true if the ray origin is inside the sphere.

**Comment by makc** [comment]
> Not true if the ray origin is inside the sphere.

true if it is outside. and it is not touching it. but who cares? I mean, if you do not find this code
```
mesh.material = { side: 0 }; // this is here so that raycast would work
```
ugly, just keep it the way it is, I do not mind

**Comment by WestLangley** [comment]
@makc There is no place for condescending remarks, here.
