### ISSUE TITLE
Animating Cameras along a path using Blender

### ISSUE THREAD

**Issue by scotmos** [mrdoob/three.js#6689]
I would like to move a camera along a path in threejs. Is it possible to import the spline path from Blender to threejs to use for for the animated camera?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
