### ISSUE TITLE
Changing data buffers runtime

### ISSUE THREAD

**Issue by Ni55aN** [mrdoob/three.js#6694]
I try to add new elements to different arrays of geometry. But it's not working. They simply do not appear when rendering.

It turned out to remove the mesh screen and add it again solves the problem, since the buffer is filled with new data, but it is too resource intensive.

Please take the opportunity to update at any time buffers vertex, face, normals and other

**Comment by dubejf** [comment]
Not a bug.

You need to set `needsUpdate = true` on your `BufferAttribute` (or `verticesNeedUpdate`, etc, if you are using plain `Geometry`.)

**Comment by Ni55aN** [comment]
http://jsfiddle.net/VsWb9/3771/

For CanvasRenderer works, but not for WebGLRenderer

**Comment by dubejf** [comment]
You are right. The documentation and wiki (https://github.com/mrdoob/three.js/wiki/Updates) appear to be out of date. (#6417)

All documented `*NeedUpdate` parameters appear to have no effect. However, I found that setting `geometry.groupsNeedUpdate = true;` works with r71: http://jsfiddle.net/eheqyy09/1/

However, that trick doesn't work with the current r72dev version: http://jsfiddle.net/eheqyy09/2/ as `groupsNeedUpdate` is not taken into account by the renderer.

**Comment by WestLangley** [comment]
http://stackoverflow.com/questions/17842521/adding-geometry-to-a-three-js-mesh-after-render/17842935#17842935

**Comment by Ni55aN** [comment]
The documentation has not been updated for a long time?

https://github.com/mrdoob/three.js/wiki/Updates
