### ISSUE TITLE
exporter not working

### ISSUE THREAD

**Issue by ge53** [mrdoob/three.js#6695]
![screen shot 2015-06-15 at 12 50 33 pm](https://cloud.githubusercontent.com/assets/12898784/8165349/b76830a8-135d-11e5-8ed0-2a79d8313d1f.png)
Using blender 2.72, installed exporter as per usual from Three.js R70/ getting this error message (see attached)..

**Comment by repsac** [comment]
> as per usual from Three.js R70/ 

probably should upgrade to r71 or dev, I seem to recall patching this bug already

**Comment by ge53** [comment]
Thanks! R71 it is!..
