### ISSUE TITLE
leap motion and rigged hand

### ISSUE THREAD

**Issue by ge53** [mrdoob/three.js#6700]
I am trying to use my LeapMotion in Three.js but want to substitute the rigged hands included in the leapjs plugin/riggedhand/ with my own models exported from Blender. After much trial + tribulation in Unity I am almost there, but in Three.js the bone orientations after exporting from Blender to Three.js are incorrect/and I have tried many, many variations...(using Blender 2.72 + Three.js exporter R71/though also experimented with earlier exporter versions)
Does anyone have any experience with this? the Blender coordinates are Z-up but I tried as Mathew Tytel suggested ("There's one main requirement of our hand rigs, that when you zero out the rotation of all the joints, the fingers need to point in the positive z direction and that pads need to face in the negative y direction" )(he is referring to Unity coordinates, i believe, which is Y-up)  to no avail--this is quite frustrating/any advice would be APPRECIATED! (tried the many various models from both the Unity + Leap.js examples/imports as .dae + .fbx in Blender)---I would like to understand how the 'original' in the Leap plugins/rigged hands were exported, but there is no ability to "import" to three.js to examine...Thanks.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
