### ISSUE TITLE
Collada model hide meshes

### ISSUE THREAD

**Issue by gandarez** [mrdoob/three.js#6701]
Hi all! Firstly congratulation to this project!

I'm loading a model that was exported from SketchUp (dae format) into my code. I'm trying to figure out how to hide/show specific meshes. Imagine a room where I want to toggle the whole TV object, it could include the TV, cables and a furniture. Is it possible to hide specific meshes? Into sketchup I made layers to do it, however it's not exported to the xml. Any ideas?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
