### ISSUE TITLE
Obj converter doesn't retain groups

### ISSUE THREAD

**Issue by anath2** [mrdoob/three.js#6707]
Hi I am trying to make a model customizable at run time. My Idea was to assign names to groups in model I created in 3d max. Then somehow be able 'replace' those groups at runtime.  But when I converted my .obj file to js I found that .js file hadn't retained group names. Instead I found that groups were being represented as materials.

**Comment by mrdoob** [comment]
Is there a way to export using `o` (objects) instead? I think the loader does retain those.

**Comment by anath2** [comment]
Yeah that's what I ended up doing, thanks.
