### ISSUE TITLE
ObjectLoader loads material with bumpScale improperly

### ISSUE THREAD

**Issue by thmxv** [mrdoob/three.js#6708]
Object loader import bumpScale incorectly causing shading to fail.

At line 251:
https://github.com/mrdoob/three.js/blob/master/src/loaders/ObjectLoader.js#L251
It assign a Vector2 to bumpScale which must be a single value.

**Comment by RemusMar** [comment]
> Object loader import bumpScale incorectly causing shading to fail.

bumpScale and normalScale require two coords: X & Y.
That's a Vector2.
Example: http://necromanthus.com/Test/html5/Lara_JS.html

**Comment by WestLangley** [comment]
@thmxv Thanks. This was previously fixed in the dev branch.

@RemusMar `bumpScale` is a float.

**Comment by RemusMar** [comment]
> bumpScale is a float.

That's strange.
Both normalMap and bumpMap are exported in the same way using the same texture slots.
And normalScale requires two coords: X & Y.
It's true that in most of the cases you have the same value for both coords, but that's not a rule!

**Comment by WestLangley** [comment]
@RemusMar `bumpScale` is a float. `normalScale` is a `Vector2`.

**Comment by RemusMar** [comment]
> bumpScale is a float. normalScale is a Vector2.

As I said before, both normalMap and bumpMap are exported in the same way.
The only difference is the texture content.
So bumpScale is a float ONLY if bumpScaleX = bumpScaleY.

Take care because you might break some exporters!
cheers

**Comment by mrdoob** [comment]
> So bumpScale is a float ONLY if bumpScaleX = bumpScaleY.

Hmmm, sounds like a "premature optimisation". What exporter are you talking about?

**Comment by RemusMar** [comment]
> Hmmm, sounds like a "premature optimisation". What exporter are you talking about?

Ricardo,
I'm talking about the 3DS Max exporters (the best exporters by far).
Most of the exporters use a single parameter (float) for normalMap and bumpMap.
So that Vector2 is not a must (even for normalMap).
The tricky part is that both normalMap and bumpMap use the same texture slot and the same "Scale" value.
The same exporting algorithm, the only difference is the texture content (in fact the texture colors).
So be sure if a Vector2 is passed for normal or bump scale, the V2.x value is used for bumpScale and V2.x & V2.y values are used for normalScale.

cheers

**Comment by mrdoob** [comment]
> Most of the exporters use a single parameter (float) for normalMap and bumpMap.

Oh, we should change that... We should still support it in the loader but better to standardise to `[x,y]`.

**Comment by RemusMar** [comment]
> We should still support it in the loader but better to standardise to [x,y]

That's a very good idea.
Fine-tuning is always welcome (especially for normal & bump maps).

**Comment by WestLangley** [comment]
> So be sure if a Vector2 is passed for normal or bump scale, the V2.x value is used for bumpScale and V2.x & V2.y values are used for normalScale.

Passed where? In what code?

> We should still support it in the loader but better to standardise to [x,y].

Support what in the loader? Standardize what to [x,y]?

**Comment by mrdoob** [comment]
Hmm, I can't find any reference to `bumpScale` in any of the exporters here:

https://github.com/mrdoob/three.js/tree/master/utils/exporters/max

**Comment by RemusMar** [comment]
> Passed where? In what code?

I just realized that bumpScale and normalScale are NOT parsed.
They are always 1 and [1,1] for the imported models.
So we're wasting our time with this topic ...

Anyway, here is a useful "enhancement" for future:

"materials": [
{
"DbgIndex" : 0,
"DbgName"  : "test",
"shading" : "phong",
"colorDiffuse"  : [1.00, 1.00, 1.00],
"colorAmbient"  : [1.00, 1.00, 1.00],
"colorSpecular"  : [0.50, 0.40, 0.30],
"opacity"  : 1.0,
"specularCoef" : 35.0,
"mapDiffuse"   : "test_D.jpg",
"mapSpecular"  : "test_S.jpg",
"mapNormal"    : "test_N.jpg",
"normalScale"  : [1.00, 1.00],
"vertexColors" : false
}
],

**Comment by WestLangley** [comment]
@RemusMar 

> This was previously fixed in the dev branch.
>> In fact "data.bumpScale" does not exist, so you didn't fix anything.

The issuse mentioned by the OP was corrected in the dev branch. See https://github.com/mrdoob/three.js/pull/6262.
