### ISSUE TITLE
TextGeometry font argument must always be lowercase (r71)

### ISSUE THREAD

**Issue by rustinlee** [mrdoob/three.js#6709]
When initializing a new instance of TextGeometry, it will always throw ``Uncaught The font FONT_NAME with normal weight and normal style is missing.`` if the string passed as ``font`` contains any uppercase characters. Special characters and punctuation within font names do not cause an issue, only uppercase letters.

This quirk is not mentioned in the [documentation](http://threejs.org/docs/#Reference/Extras.Geometries/TextGeometry) and had me running around for the better part of 30 minutes before I found out about it.

**Comment by WestLangley** [comment]
Do these three.js examples work for you? (type something)

http://threejs.org/examples/webgl_geometry_text.html
http://threejs.org/examples/webgl_geometry_text2.html

**Comment by gero3** [comment]
He means the familyName in the typeface file. I've run into the same problem as him. 

https://github.com/mrdoob/three.js/blob/master/src/extras/FontUtils.js#L50

**Comment by WestLangley** [comment]
Ah, yes. Thanks, @gero3. I misread the post.

This has come up before: http://stackoverflow.com/questions/25042767/threejs-font-not-loading/25078604#25078604

The documentation and inline comments should be made clear in `TextGeometry` and `FontUtils`, at least.

/ping @TatumCreative 

Or, perhaps, a code fix is possible?

/ping @mrdoob

**Comment by gero3** [comment]
#6711 should fix this issue.

**Comment by WestLangley** [comment]
Thanks, @gero3 !
