### ISSUE TITLE
PointCouldMaterial texture not working with Google Chrome 43

### ISSUE THREAD

**Issue by donlzx** [mrdoob/three.js#6714]
Texture for PointCloudMaterial does not showing up in Google Chrome 43 stable release (Linux x86_64).  It is working with previous Chrome 42 releases. All the examples with texture for PointCloudMaterial not working. 

* http://threejs.org/examples/#webgl_particles_billboards
* http://threejs.org/examples/#webgl_particles_billboards_colors
* http://threejs.org/examples/#webgl_particles_random
* http://threejs.org/examples/#webgl_particles_shapes
* http://threejs.org/examples/#webgl_particles_sprites
* http://threejs.org/examples/#webgl_interactive_particles

Does it has anything to do with the following changes in Chrome 43?

[Remove all traces of synchronous GPU rasterization](https://chromium.googlesource.com/chromium/src/+/59d4494849b405682265ed5d3f5164573b9a939b)

**Comment by scottross8** [comment]
All of these are working for me in Linux with Chrome Version 43.0.2357.125 (64-bit).  I believe that this is the stable version.   I am using Fedora with the NVidia drivers.   There are no errors in the console (just "THREE.WebGLRenderer 71").

**Comment by donlzx** [comment]
Same Chrome version for me, but with Intel graphic card. Not errors in the console, but textures not showed.

**Comment by titansoftime** [comment]
Works fine for me, Windows 7, Intel Graphics.

**Comment by mrdoob** [comment]
@donlzx errors in the console? does it work on firefox?

**Comment by donlzx** [comment]
All these examples are working with Firefox (37.0.2) on my system (Linux Mint 17.1 Cinnamon 64-bit).

**Comment by mrdoob** [comment]
On Linux it's usually a drivers issue. But if it works the same way in Firefox and Chrome then sounds like a Chrome issue...

**Comment by donlzx** [comment]
I think it is related to the Intel graphics driver and Chrome.  Chrome seems to have removed some old interfaces/API and driver support, while Intel refuse to support previous Linux releases.  The latest Chromium release (43.0.2357) even says that my graphics card are not supported!

Anyway, it is sad that Ubuntu LTS releases just one-year-old are regarded outdated and not supported. Sometimes getting WebGL working on Linux is frustrating.

**Comment by erno** [comment]
@donlzx, Ubuntu LTS releases receive new graphics drivers as backports from newer Ubuntu releases. See https://wiki.ubuntu.com/Kernel/LTSEnablementStack

Sounds like it would be good to file a Chrome bug for this issue

**Comment by donlzx** [comment]
Update: It is now working with Latest Chrome version 44.0.2403.125 (64-bit).  Chrome version 43 seems to be the one off.
