### ISSUE TITLE
Textgeometry objects intersection

### ISSUE THREAD

**Issue by iamajaymakwana** [mrdoob/three.js#6715]
I would like to do the intersection between two TextGeometry objects. How it is possible?
Please help on it

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
