### ISSUE TITLE
collada animations

### ISSUE THREAD

**Issue by boolean25** [mrdoob/three.js#6726]
Hi
recently I'm working collada model width Skeletal animation, but somehow I use the code in "webgl_loader_collada_keyframe" cannot recognize skeletal animations and I don't understand how to control the loop with animations.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
