### ISSUE TITLE
rotate on axis not working proper

### ISSUE THREAD

**Issue by Prieston** [mrdoob/three.js#6744]
I have perceived that when you use this code to rotate an object around a certain axis at the render function:
 
    function render(){
      var vectorX = new THREE.Vector3( 1, 0, 0 );
      THREE.object3D.rotateOnAxis(vectorX,0.1);

      var vectorZ = new THREE.Vector3( 0, 0, 1 );
       THREE.object3D.rotateOnAxis(vectorZ,0.1);
    }

the object also rotates at the y axis. When i use one of these rotations it rotates as expected but when combine it also rotates at the y axes. This happens also when using 

      THREE.object3D.rotateX(0.1);
      THREE.object3D.rotateZ(0.1);

is this supposed to be happening and how can someone rotate at two axes without changing the third?

**Comment by WestLangley** [comment]
The library is working as expected.

As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by makc** [comment]
> how can someone rotate at two axes

good question 😜 attempting this in real world would break the object apart.

**Comment by Prieston** [comment]
No it would not.. Imagine a sphere rotating at its center axis and also rotating in one more axis..It is possible

**Comment by makc** [comment]
Any rotation in 3D does always happen around one single axis. So when you have two non-zero rotation components (x and y, or x and z), it means you _first_ rotate around one axis, and _then_ rotate around another one. But _never_ around two at the same time.

**Comment by Prieston** [comment]
At the code i posted i first rotate the objext at the x axis and then at the z. I actulally have created some code to animate a moving object on a plane surface. After setting its velocity in km/h the object can move to the surface correctly. Also i have created a code that changes the objects rotation to be perpedicular to the surface and oriented to the selected path ending point. The problem is after some rotations the orientation changes so that means that the Y rotation is changing without me changing it. If as *WestLangley* says this is the way the library works, does the library have some code applyable to my needs?

**Comment by WestLangley** [comment]
@Prieston 

As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). Post a simple, live example on SO and ask a specific question if you are having trouble.
