### ISSUE TITLE
r72dev avoid forced convertion to BufferGeometry

### ISSUE THREAD

**Issue by poofik** [mrdoob/three.js#6749]
I do not know the complexity of three.js re-structuring for v72, but it seems to force  convert all geometries "THREE.BufferGeometry.setFromObject(). Converting"

Can we include some option to avoid conversion for some meshes?

Example:
```javascript
 var sides = [
            new THREE.MeshBasicMaterial({
                map: new THREE.ImageUtils.loadTexture('panoramas/' + files + '/_right.jpg'),
                side: THREE.BackSide
            }),
            new THREE.MeshBasicMaterial({
                map: new THREE.ImageUtils.loadTexture('panoramas/' + files + '/_left.jpg'),
                side: THREE.BackSide
            }),
            new THREE.MeshBasicMaterial({
                map: new THREE.ImageUtils.loadTexture('panoramas/' + files + '/_top.jpg'),
                side: THREE.BackSide
            }),
            new THREE.MeshBasicMaterial({
              map: new THREE.ImageUtils.loadTexture('panoramas/' + files + '/_bottom.jpg'),
              side: THREE.BackSide
            }),
            new THREE.MeshBasicMaterial({
               map: new THREE.ImageUtils.loadTexture('panoramas/' + files + '/_front.jpg'),
               side: THREE.BackSide
            }),
            new THREE.MeshBasicMaterial({
               map: new THREE.ImageUtils.loadTexture('panoramas/' + files + '/_back.jpg'),
               side: THREE.BackSide
            }),
        ];
        var geometry = new THREE.BoxGeometry(50,50,50);
        var mesh = new THREE.Mesh(geometry, new THREE.MeshFaceMaterial(sides));
```

**Comment by titansoftime** [comment]
They have removed ``MeshFaceMaterial`` from 72dev. They mentioned they are working on bringing it back here: #6618.

I am looking forward to when this is complete.

**Comment by user972611** [comment]
Yes, this will be sweet.

Because BufferGeometry doesn't support ```mergeVertices``` yet, without this function all mesh with normalMap will display very hard seams... 

Didn't see any workaround replace for the ```mergeVertices```...

**Comment by WestLangley** [comment]
> Because BufferGeometry doesn't support mergeVertices yet, without this function all mesh with normalMap will display very hard seams at UV border...

@user972611 Would you mind posting an enhancement request with a simple live example showing your use case?

**Comment by titansoftime** [comment]
An issue with this I've noticed is that converted objects still contain their ``Geometry`` resulting in higher than normal memory usage. When I inspect the ``Mesh`` (``SkinnedMesh`` in my case) it has both ``__BufferGeometry`` and ``Geometry`` properties. I'm not sure which one is actually being pushed to render. I'm assuming the ``Geometry`` since ``BufferGeometry`` doesn't (as far as I know) support skeletal animations.

Is this intentional?

I'll post an example of this when I get home from work if necessary.

**Comment by mrdoob** [comment]
>  since ``BufferGeometry`` doesn't (as far as I know) support skeletal animations yet.

```BufferGeometry`` does support skeletal animations now 😊

**Comment by mrdoob** [comment]
The reason we're converting to `BufferGeometry` is because `WebGLRenderer` was doing so internally already. However, it wasn't `BufferGeometry` exactly, `WebGLRenderer` was producing its custom geometry structure. This structure was very similar to `BufferGeometry` so the idea is to move that code out of the renderer and port it to `BufferGeometry`.

**Comment by titansoftime** [comment]
>BufferGeometry does support skeletal animations now. Basically, whatever you see being rendered in the dev branch now, BufferGeometry supports it :blush:

That is super awesome!

That being said, shouldn't the convert operation then unlink the original ``Geometry`` from the ``Mesh``?

I'm guessing that it is still used as my terrain intersect function (keeps players feet on the heightmap displaced terrain) still works which is dependent on ``Geometry.faces``. No idea here.

Also is there a way to convert the geometry directly? Would ``fromGeometry`` work (skinning and all)? 

Thing is, I cache geometry for when another ``Mesh`` is needed of the same geometry. I would rather just cache the converted ``BufferGeometry`` and use that for the new ``Mesh`` as opposed to caching ``Geometry`` and having to do a convert operation every time a new ``Mesh`` is loaded. 

Memory efficiency is what I'm after. If everything is ultimately converted to ``BufferGeometry`` I would like to unlink and dispose the then obsolete ``Geometry`` after the initial conversion.

Sorry for rambling on, I'm just trying to wrap my head around this. I'm sure anybody else who caches their geometries would want to know as well. I hope any of this makes sense lol.

**Comment by mrdoob** [comment]
> I still think it's weird that a ``Mesh`` can have both ``Geometry`` and ``_BufferGeometry``. Seems kinda wasteful. Am I wrong in saying so?

Yep... But remember that `WebGLRenderer` was creating `BufferGeometry`-like internally anyway. Eventually you should be able to just deal with `BufferGeometry`.
