### ISSUE TITLE
TubeGeometry not coloring properly

### ISSUE THREAD

**Issue by jfoxworth** [mrdoob/three.js#6750]
Revision number 69

Browser : Chrome 43.0.2357.130 (64-bit)
Firefox

I am using the SplineCurve3 routine to create a path for the tubeGeometry routine. When I do this with sinusoidal data, the coloring of the tube correctly reflects the z axis value. However, whenever I use data that is not sinusoidal, the coloring is off. The proper coloring is shifted ahead of the z axis value. This error diminishes if I interpolate the data and increase the total number of points. The rate of error reduction is linearly dependent upon the increased data resolution.

You can see the code I am using along with a sample of the data <a href="http://stackoverflow.com/questions/31064165/three-js-tubegeometry-and-and-splinecurve">here</a>. You can also see the error along with a properly displayed sinusoidal tube <a href="http://www.cadwolf.com/Documents/Documentation/Examples/The_bungee_jumper_problem">here</a>.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by jfoxworth** [comment]
I have looked at this for quite a while and asked for help to find any problems with my approach. I don't think that I have an error. I don't want to be a stick in the mud, but are you sure that this is not a bug? How can it be the intent of the software to miscolor the data?
