### ISSUE TITLE
Spring cleanup

### ISSUE THREAD

**Issue by dubejf** [mrdoob/three.js#6756]
I did a random walk through the backlog and found a lot of resolved issues waiting to be closed.

@mrdoob please have look! Most of these open issues/PR can be closed trivially.

#### Documentation 

~~#3203 -> Not a library issue. 'getting started' example shows a correct implementation.~~
~~#3732 -> DOMRenderer has been removed (ParticleDOMMaterial).~~
~~#5941 -> Documented in #6101 (OBJMTLLoader).~~

#### Simple issues with merged PR attached

~~#1124 -> Fixed by #6755 (LensFlare rotation initialization).~~
~~#2694 -> Fixed by #4530 (epsilon for change detection in trackball control)~~
~~#3360 -> Fixed by #3376 (PolyhedronGeometry face normals).~~
~~#3539 -> Fixed by #3588 (mtlloader).~~
~~#3547 -> Fixed by #3550 (Torus simplification).~~
~~#3697 -> Fixed by #3703 (renderer.info counts).~~
~~#3778 -> Fixed by #3791 (orbit control not working).~~
~~#3799 -> Fixed by #3827 (editor transform control).~~
~~#4771 -> Fixed by #4792 (transform control touch).~~
~~#5729 -> Fixed by #5735 (add vector fromAttribute).~~
~~#5922 -> Fixed by #6513 (canvas build).~~
~~#6615 -> Fixed by #6625 (raycaster precision with PointCloud)~~
~~#6716 -> Fixed by #6727 (incomplete clones).~~

#### Complex issues that appear to be solved by PR

~~#3404 -> Anything left to do with this (euler)?~~
~~#3417 -> Conflict between Object3D.rotation (Vector3) and Sprite.rotation (float) => There is no Sprite.rotation, only SpriteMaterial.rotation~~. 
~~#5796 -> Fixed by #6743 (emissive maps).~~

#### Fixed bugs

~~#4157 -> Intel driver issue. Not a library issue. Reportedly fixed upsteam (bump mapping).~~
~~#4461 -> Tested on Nexus 4 and Galaxy tab (orbit control example). Zoom speed appears to be well calibrated.~~
~~#4889 -> I am not reproducing this bug. ~~
~~#6116 -> Help / need more info?~~

#### Questions, comments and help

~~#1885 -> Help - Use sprite http://stemkoski.github.io/Three.js/Labeled-Geometry.html~~
~~#2145 -> Question answered (face picking / highlight object).~~
~~#2167 -> Question (expose TrackballControls internal). Controls are for user interaction. Move/tween camera directly to follow a programmatic path.~~
~~#3122 -> Question (vertex color). Need custom shader?~~
~~#3162 -> Help / THREE.Ribbon are removed (merge ribbons) / SO link is dead.~~
~~#3324 -> Question answered (lookAt math / convention).~~
#3684 -> Suggestion about labels (rejected).
~~#3761 -> Question answered (json exports matrix; position, quaternion and scale are redundant).~~
~~#4122 -> Not a problem :)~~
#4857 -> Question answered, this is already supported (use 'change' callback to track control update).

#### Cleanup

~~#2013 -> Loader request for nrrd format => Close this one and just add a bullet to #5524.~~
~~#3843 -> Showcase MIT library for loading. If the library is of interest, close and add link this resource in a comment to #5524.~~

#### Not sure, but probably done

~~#1152 -> THREE.REVISION was added.~~
~~#3624 -> Instancing implemented in #6242.~~
Also, is #5171 still relevant?
~~#3726 -> Feature request (NURBs Trimming). Seems out of scope for three.js core.~~
~~#3852 -> SceneLoader is deprecated.~~
#4627 -> Currently solved with WireframeHelper. Anything more to do?
~~#5053 -> (glcontext sharing with custom renderer). We have WebGLState now. Calling renderer.resetGLState() should be sufficient - just like plugins do. There is nothing specific left to do.~~
~~#5278 -> Ditto.~~
~~#5686 -> #5567 claims to fix it. Confirmed?~~

#### Unmerged pull requests to cancel - already fixed independently

~~#2970 -> Trackball controls use domElement size. https://github.com/mrdoob/three.js/blob/5c7e0df9b100ba40cdcaaf530196290e16c34858/examples/js/controls/TrackballControls.js#L81~~
~~#4203 -> Combined camera fov calculation. https://github.com/mrdoob/three.js/blob/5c7e0df9b100ba40cdcaaf530196290e16c34858/examples/js/cameras/CombinedCamera.js#L70~~
~~#4206 -> Original issued (window scrolling in FF) fixed in #4229. I don't see the need to implement the 'wheel' callback if it does not solve a specific issue.~~

---

**Suggestion**: would you consider adding a few more tags to help classify the remaining issues?

- *Loaders* (maybe even one for each of the main formats: *Collada*, *Blender*...)
- *Editor*
- *Need more info*
- *Hardware* (for Hardware/driver issues).
- *Architecture* (for high-level design discussion)
- *Documentation* (documentation improvement)

**Comment by WestLangley** [comment]
Wow. Thanks for doing this!

Only 800 more to go. : - )

**Comment by dubejf** [comment]
A few more:

#3357 -> Question answered (vector means point in this context),
#3385 -> Fixed by #6757 (ray square distance).
#3647 -> Fixed by #6757 (raycaster invisible objects).
#3755 -> Bug fixed (buffer geometry reuse).

**Comment by mrdoob** [comment]
Oh wow! Many thanks!

**Comment by mrdoob** [comment]
Actually, do you mind if I add you as a collaborator so you can directly close the issues?

**Comment by dubejf** [comment]
Sure

**Comment by mrdoob** [comment]
Done!

**Comment by dubejf** [comment]
Still thinking about #4857. Otherwise, triage is done.

**Comment by mrdoob** [comment]
Many thanks!
