### ISSUE TITLE
ThreeJS support?

### ISSUE THREAD

**Issue by NicolasRannou** [mrdoob/three.js#6760]
Hello,

I can not find the right place to ask so here my question:

Is there any company supporting ThreeJS main developers or is it something you just do on the side as a fun project?

I really like it and consider using to build my application  and hope to get a good picture of who is supporting the project, if there is some kind of organization or if it just depends all on Mr Doob?

**Comment by antont** [comment]
officially AFAIK it is just mrdoob's personal project or so, and of course all the other contributes here on github doing all kinds of things.

there are companies and people who do support and jobs .. there might not be a listing available but at least our company and OTOH jetienne and some other people do it.

we here (in some Oulu based companies) have EU funding too for doing basic support as three.js is a part of the offering in the FIWARE programme too (as are many open source things, has openstack for cloud servers etc .. mongodb for something else etc).
