### ISSUE TITLE
Sprite transparency error

### ISSUE THREAD

**Issue by Cy-Bo-Rg** [mrdoob/three.js#6763]
I've just downloaded the latest Three.js master "mrdoob-three.js-d6384d2" , I've modified the "webgl_nearestneighbour.html" to show a transparent .png (the same happens with transparent .gif too) and this is the result (see image http://share.pho.to/9XjdE ).
I can't understand if it's by design , if it's a webgl error or if it's a three.js error but, as you can see in the bigger ball, near sprites are clipped while far sprites aren't.
Any help is much appreciated.

**Comment by Cy-Bo-Rg** [comment]
I've noticed that the effect is reduced by navigating the demo from different directions. It looks like transparency works fine if the camera is facing a certain axis while it doesn't with some other.

**Comment by Cy-Bo-Rg** [comment]
Since stackoverflow is filled with answers, may you please say a few words with some reliable information before closing ? Thanx!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

If you are not sure if it is a three.js bug, we prefer you first seek help on stackoverflow. Please respect the policy of this board.

I will be glad to help you on stackoverflow if you are unable to find a solution. But first, please try to solve it yourself.

**Comment by Cy-Bo-Rg** [comment]
Thanx , I didn't want to be boring , I 'm sorry :P
