### ISSUE TITLE
webgl_animation_skinning_blending design error

### ISSUE THREAD

**Issue by Cy-Bo-Rg** [mrdoob/three.js#6764]
If you press "show skeleton" , the skeleton is facing toward a wrong direction (most noticeable if watched from above).

**Comment by Cy-Bo-Rg** [comment]
Dunno if it's a bug though...

**Comment by WestLangley** [comment]
Yes. That certainly does not look correct.

three.js r.71.

**Comment by Cy-Bo-Rg** [comment]
@WestLangley Thanx!

**Comment by WestLangley** [comment]
@Cy-Bo-Rg You need to thank @sirxemic. : - )

**Comment by Cy-Bo-Rg** [comment]
Well thanx @sirxemic and everybody else, you're all awesome ! :)
