### ISSUE TITLE
Intersects on mobile/touch devices

### ISSUE THREAD

**Issue by nopor** [mrdoob/three.js#6770]
I think it's a bug on mobile/touch devices which doesn't let you move/interact with objects you touch/select.
I've tried intersects on mobile/touch devices (systems: android and wp).
Chromes 'device mode' doesn't let you move selected objects either.

Any ideas?

**Comment by dubejf** [comment]
If you are talking about the editor, I confirm.

**Comment by nopor** [comment]
Forgot to mention, that there's already an example for it: http://threejs.org/examples/webgl_interactive_draggablecubes.html
This doesn't work (for me) on any touch device (yes, they can't handle the shadows, but even without, you can't drag anything).

**Comment by WestLangley** [comment]
This is not a bug. Your app needs to handle touch events. The particular demo you rereferenced does not do that.

As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by nopor** [comment]
Oh, sorry then - will add it then. Thanks.
