### ISSUE TITLE
enchncmnt: add vector premultiplied by scalar

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6781]
I find myself calculating sums like number1 * vector1 + number2 * vector2 + .... quite often (mostly for averaging or interpolating). Far more often than I had to use addScalar method (which was never). But in order to do so I need to create temporary vector, set this vector for every addend, multiplyScalar it and then finally add it. Or, I could just inline everything and not use Vector3 methods.

Would it not be nice to have something like
```
	addScaledVector: function ( v, s ) {

		this.x += v.x * s;
		this.y += v.y * s;
		this.z += v.z * s;

		return this;

	},
```
instead?

Vector3 already has lerp, which is fine for two vectors, but it can be 3 vectors (think vertex normals) or more.

Same applies to Vector2 (uv and stuff).

**Comment by WestLangley** [comment]
Sounds like a good idea to me.

**Comment by makc** [comment]
To compare the code, before:
```
var local_normal = new THREE.Vector3 (
	bc.x * f.vertexNormals[0].x + bc.y * f.vertexNormals[1].x + bc.z * f.vertexNormals[2].x,
	bc.x * f.vertexNormals[0].y + bc.y * f.vertexNormals[1].y + bc.z * f.vertexNormals[2].y,
	bc.x * f.vertexNormals[0].z + bc.y * f.vertexNormals[1].z + bc.z * f.vertexNormals[2].z
);
```
after:
```
var local_normal = (new THREE.Vector3 ()).
	addScaledVector (f.vertexNormals[0], bc.x).
	addScaledVector (f.vertexNormals[1], bc.y).
	addScaledVector (f.vertexNormals[2], bc.z);
```
(apply your favorite formatting, but it still shorter).

Just minutes ago used it to add scaled normal to the point for line.geometry 2nd point:
```
line.geometry.vertices[0].copy (p);
line.geometry.vertices[1].copy (p).addScaledVector (n, 0.1);
```
originally I modified n, now I am keeping it intact for further use 😋😋

**Comment by mrdoob** [comment]
Sounds good to me! I think MorphTargets will benefit of this internally too.

**Comment by makc** [comment]
Yay \m/
