### ISSUE TITLE
How to check faceIndex of all object?

### ISSUE THREAD

**Issue by GlebDolzhikov** [mrdoob/three.js#6785]
Hi, thanks for three.js!

I have some child project http://kinosura.kiev.ua/sova/ and i need to check faceIndex of all cubes.

Now i use intersections array from mouse, but is working only when user pointer at the cube.

How to make ray or rays from camera to all object to check faceIndex ?

I try to make four rays to cubes but if i set cube.position as origin of like this:
raycaster.setFromCamera( cube1.positoin , camera )

I get empty array of intersections.

I also try to set static 2d vector as origin (get coordinate from mouse) but i have relative renderer size and this coordinate all time change... its not work(

Thanks for answer anyway.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
