### ISSUE TITLE
many demos not rendering properly both on mobile and pc

### ISSUE THREAD

**Issue by Cy-Bo-Rg** [mrdoob/three.js#6788]
Something has been broken from rev71 master to rev72 dev.
Many problems,from loader problems to texture coordinates problems.

rev71 master on android
![screenshot_2015-07-04-08-09-45](https://cloud.githubusercontent.com/assets/5455606/8506764/7b1f9cf4-2225-11e5-9b22-9928ec1a8825.png)
rev72 dev on android
![screenshot_2015-07-04-08-13-50](https://cloud.githubusercontent.com/assets/5455606/8506765/7f8013f0-2225-11e5-9898-051ac8c09810.png)
rev71 master on pc
![bugrev72_1](https://cloud.githubusercontent.com/assets/5455606/8506788/d236cde0-2226-11e5-8d97-01bf63436409.jpg)
rev72 dev on pc
![bugrev72_2](https://cloud.githubusercontent.com/assets/5455606/8506789/d66be2ce-2226-11e5-96c8-beb2e71dfdfb.jpg)
rev71 master on pc (same on android)
![bug2](https://cloud.githubusercontent.com/assets/5455606/8506828/700e8c82-2228-11e5-9a89-86b28f70fe4b.jpg)
rev72 dev on pc (same on android)
![bug1](https://cloud.githubusercontent.com/assets/5455606/8506830/7daf46c4-2228-11e5-897a-ac3024c0e158.jpg)
rev71 master on pc (same on android)
![bug1](https://cloud.githubusercontent.com/assets/5455606/8506842/3bc79e68-2229-11e5-9c77-1e6f3506e343.jpg)
rev72 dev on pc (same on android)
![bug2](https://cloud.githubusercontent.com/assets/5455606/8506845/46f790ea-2229-11e5-8796-8a9890a6fde0.jpg)

I don't want to make a slideshow of images here,but you get the point... :P
other demos not working with rev72 dev (in a webserver,don't consider the pictures above) are : 
webgl_effects_parallaxbarrier (firefox,chrome)
webgl_geometry_convex (chrome)
webgl_geometry_cube(chrome)
webgl_geometry_dynamic(chrome)
webgl_interactive_particles(firefox,chrome)
webgl_loader_json_objconverter(firefox,chrome)
webgl_loader_scene(firefox,chrome)
webgl_loader_stl(working but with slightly different colors)(firefox,chrome)
webgl_materials(firefox,chrome)
webgl_materials_cars(firefox,chrome)
webgl_materials_cars_camaro(firefox,chrome)
webgl_materials_cubemap_dynamic(firefox,chrome)
webgl_materials_texture_pvrtc (firefox,chrome) **(doesn't work in rev71 too)**
webgl_materials_wireframe(firefox,chrome)
webgl_morphnormals (firefox,chrome)
webgl_morphtargets_md2(firefox,chrome)
webgl_morphtargets_md2_control(firefox,chrome) **(doesn't work in rev71 too)**
wevgl_nearestneighbour(firefox,chrome)
webgl_particles_shapes(firefox,chrome)
webgl_postprocessing_dof (fine,but the spheres are different from rev71,both browsers)
webgl_postprocessing_crossfade(same as above,different shape of the spheres,both browsers)
webgl_shading_physical(puppet doesn't move anymore,like morphnormals,firefox,chrome)
webgl_shaders_vector(wrong triangulation compared to rev71,firefox,chrome)
webgl_terrain_dynamic(firefox,chrome)
webgl_custom_attributes_particles(firefox,chrome)
webgl_custom_attributes_particles2(firefox,chrome)
webgl_custom_attributes_particles3(firefox,chrome)
webgldeferred_animation(firefox,chrome)
webgldeferred_pointlights(firefox,chrome)
misc_animation_keys(not working both on **rev71master** and rev72dev,both browsers)
canvas_geometry_panorama(black screen,firefox,chrome)
canvas_geometry_panorama_fisheye(black screen,firefox,chrome)
canvas_materials(missing materials,firefox,chrome)

(all other demos tested and working fine)

Tested on Chrome Version 43.0.2357.130 m , Firefox 39.0 on AMD Radeon 8210 HD and Android Stock Browser 4.1.2 on Power VR SGX-540.

**Comment by Cy-Bo-Rg** [comment]
I've spent 4 hours to do so :P
I hope you'll accept my highly tested pull request as a compliment... :P

**Comment by mrdoob** [comment]
Yes yes. Those are mainly due to `MeshFaceMaterial` re-implementation not being done yet.

**Comment by Cy-Bo-Rg** [comment]
At least there's a list now ^_^"

**Comment by Mugen87** [comment]
@Cy-Bo-Rg Many thanks for your tests! Indeed, it requires much time to test all three.js examples with different browsers and devices.

Because the mentioned problems are solved now, i think we can safely close this issue.
