### ISSUE TITLE
raycast from camera center

### ISSUE THREAD

**Issue by andrewxaim** [mrdoob/three.js#6791]
hello everybody,

i try since weeks to raycast from the centre of a perspectivecamera. without event.client.x and y, because i use the device orientation:

var raycaster  = new THREE.Raycaster();
var vector = new THREE.Vector3( 0, 0, 0 ); // instead of event.client.x and event.client.y
var direction = new THREE.Vector3( 0, 0, -1 ).transformDirection( camera.matrixWorld );
raycaster.set( vector, direction );
var intersects = raycaster.intersectObjects(objects); 

i have a perspectivecamera on (0,0,0) … i use the device orientation instead  keyboard and mouse to obtain the rotation … and want to hit a cube with a raycast sent from the center of my cam. i try a lot of examples for a three.js raycast, but no success.

what the hell is wrong with my raycast????

**Comment by Cy-Bo-Rg** [comment]
You won't receive help here,go to stackoverflow.
https://github.com/mrdoob/three.js/issues?q=is%3Aissue+is%3Aclosed
