### ISSUE TITLE
rotations

### ISSUE THREAD

**Issue by stephane78** [mrdoob/three.js#6793]
Hi,
I have two lines : y=sin(x)+1, z=5 and y =sin(x)-1,z=5 and I want to make 2 rotations of each around the axis y=1,z=5 and y=-1,z=5.I use three.line for each line
I use three.js r71.I have tryed several functions but each times my two lines rotate around y=0 ,z=0 instead of y=1,z=5 and y=-1,z=5..is it possible to make such rotations with three.js?

**Comment by frankLeo123** [comment]
I get it,But I learned it for few days.Sorry, I can't help you

**Comment by frankLeo123** [comment]
You should show me all your code...Just two line, I can't get you.

**Comment by stephane78** [comment]
I have my two lines sin(x)-1 and sin(x)+1
var sinline = new THREE.Line(geometry,material);
var sinline2 = new THREE.Line(geometry2,material2);
in the render function I have tryed sinline.rotateX(0.1);  and I have tryed sinline.rotation.x +=0.1; but each time it rotates around the x axis y=0 and z=0 instead of y=-1 and z=5
 Ihave tryed too with this function
var rotObjectMatrix;
function rotateAroundObjectAxis(object, axis, axe, radians) {
    rotObjectMatrix = new THREE.Matrix4();
    rotObjectMatrix.makeRotationAxis(axis.normalize(), radians);

    axe.matrix.multiply(rotObjectMatrix);

    object.rotation.setFromRotationMatrix(axe.matrix);
};
and in the render function,
rotateAroundObjectAxis(sinline,new THREE.Vector3( 1, 0, 0),line5, 0.1);
where line5 is a line on y=-1 and z=5
the rotations are always around the x axis y=0 and z=0 instead of my two axis y=-1 z=5 and y=1 z=5

**Comment by frankLeo123** [comment]
Eh.....I'm trouble too. And waiting the really great professor

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by stephane78** [comment]
I have just asked if three.js is able to do this kind of rotation? I didn't ask for help and I won't go on stackoverflow . your library is perhaps not able to do what I want to do (such rotations) and I Will use Webgl if it isn't worth.....

**Comment by WestLangley** [comment]
> is it possible to make such rotations with three.js

Yes.

> I didn't ask for help and I won't go on stackoverflow.

If you change your mind, I'll be glad to help you on stackoverflow.
