### ISSUE TITLE
Sector of SphereBufferGeometry has missing faces

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#6799]
When rendering just a sector of a sphere, the edges are jagged due to missing faces.

    var geometry = new THREE.SphereBufferGeometry( 10, 6, 4, Math.PI / 2, Math.PI / 2, Math.PI / 4, Math.PI / 4 );

three.js r.72dev

**Comment by gero3** [comment]
isn't this fixed??

**Comment by WestLangley** [comment]
Yes.
