### ISSUE TITLE
Scene updates with multiple renderers

### ISSUE THREAD

**Issue by dubejf** [mrdoob/three.js#6800]
Following #6723.

This fiddle is a modified version of the "webgl_multiple_renderers" example, using r72dev: http://jsfiddle.net/ybz0p1wd/ showing a scene with single mesh with two renderers.

In the animation loop:
- the material color is changed.
- the coordinates of the geometry are changed.
- for each renderer, `renderer.render` is called.

As you can see, the **material is updated in both renderers**, but the **geometry is only updated in the first renderer**.

The problem is that `BufferAttribute.needsUpdate` is a boolean flag:
1. `needsUpdate` is set to `true`.
2. The first renderer sees `needsUpdate === true` and updates its WebGL buffer.
3. `needsUpdate` is set to `false`.
4. The second renderer sees `needsUpdate === false` and misses the update.

##### 1) Do nothing (not supported) #####

As a workaround, users can reset `needsUpdate` between each render.

##### 2) Change the update tracking mechanism from a boolean flag to an integer version number #####

This approach described here https://github.com/mrdoob/three.js/pull/6723#issuecomment-117297948 and here https://github.com/mrdoob/three.js/pull/6723#issuecomment-117314289.

##### 3) `BufferAttribute` could inherit from `THREE.EventDispatcher` #####

The material is updated in both renderers because they subscribe to the `update` event of the `Material`. `BufferAttribute` could use a similar approach. I have not wrapper my head around all the consequences of this design.

What do you think?

**Comment by mrdoob** [comment]
This is how I fixed this is issue with `Texture` long time ago:

https://github.com/mrdoob/three.js/blob/master/src/textures/Texture.js#L52-L64

When a renderer first sees a texture it adds listeners and `.needsUpdate = true` dispatches the `update` event. Maybe we can implement the same with geometry buffers?

**Comment by dubejf** [comment]
Yep. That's solution 3, the most ambitious! It could help with `dispose` too. With reference counting, it could allow single a buffer to be shared by multiple geometries (maybe).

**Comment by gero3** [comment]
I like solution 2 tough. 

This is what i used in my solution of https://github.com/mrdoob/three.js/pull/6062

**Comment by mrdoob** [comment]
Yeah. I actually suggested solution 2 to @alteredq years ago. But at the time of implementing solution 3 seemed cleaner.

**Comment by dubejf** [comment]
Fixed in #6827
