### ISSUE TITLE
Intersection of TransformControls handles always returns false

### ISSUE THREAD

**Issue by tistatos** [mrdoob/three.js#6804]
The `intersectObjects( pointer, objects )` in TransformControls [always returns false](https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/TransformControls.js#L1012) when its testing if user is hovering the mouse over the handles or trying to click.

The handles doesn't highlight and the transform tool can't be used at all. 

![transformbug](https://cloud.githubusercontent.com/assets/2827554/8518021/8fbbac28-23c6-11e5-8307-8c50defdef97.png)
*The YZ-plane indicator should be highlighted on the picture*

**Comment by tschw** [comment]
See #6795

**Comment by dubejf** [comment]
Fixed by #6795.
