### ISSUE TITLE
Geometry parameters

### ISSUE THREAD

**Issue by dubejf** [mrdoob/three.js#6809]
1. In `BoxGeometry`, is there a reason to keep two copies of `widthSegments`, one in `.parameters` and one as property of the object itself? Same with `heightSegments` and `depthSegments`.

2. `BoxGeometry` and the other geometries in `extras` support default values for some of their parameters. Currently, if the input value is not specified, an `undefined` value is stored in `.parameters`. Why not store the default value? Like this:

```
THREE.BoxGeometry = function ( ..., widthSegments, ... ) {

	// Apply defaults first
	widthSegments = widthSegments || 1;

	this.parameters = {
		...
		widthSegments: widthSegments,
		...
	};
```

Is it to avoid serializing default values in the exporter?

**Comment by mrdoob** [comment]
> Is it to avoid serializing default values in the exporter?

Yep!
