### ISSUE TITLE
Type property for GridHelper

### ISSUE THREAD

**Issue by tonnot** [mrdoob/three.js#6810]
As gridhelper is created as a 'line' , one don't know if an object is a gridhelper or not. 
Having a type = "gridhelper" could be useful.
And maybe this can be happening with other helpers or objects that extend from line ?
Thanks.

**Comment by mrdoob** [comment]
Yep. This should be implemented. Do you want to do a PR for it?

**Comment by tonnot** [comment]
I'dont know what happen... I commented that I need some three.js/github instructions to avoid break something ....(and the coment dissapeared...)

**Comment by WestLangley** [comment]
@tonnot See the Wiki article [How to Contribute to three.js](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js).

Don't worry about breaking anyting. If you prefer not to implement the PR yourself, that is OK, too.

**Comment by Mugen87** [comment]
Closing, since the `type` property is only necessary for serialization/deserialization. #15714 tracks this in context of helpers.
