### ISSUE TITLE
THREE.js renderer renders over css defined border radius in safari (desktop and mobile)

### ISSUE THREAD

**Issue by madwed** [mrdoob/three.js#6811]
When I set a curved border on the canvas using css the THREE.js renderer draws over the rounded borders.  This isn't an issue in Chrome or Firefox.  Is there a workaround for Safari?

![chrome firefox](https://cloud.githubusercontent.com/assets/11039058/8557522/e116d452-24cb-11e5-8849-b7e300daab23.jpg)
![safari](https://cloud.githubusercontent.com/assets/11039058/8557523/e11c4b9e-24cb-11e5-8d9f-b576648effdb.jpg)

**Comment by benaadams** [comment]
Put it in a ```div``` set the border on the div, give it overflow:hidden and a z-Index?

Probably raise a webkit bug also :)

**Comment by madwed** [comment]
Interestingly enough that solution causes the issue in Chrome as well.  Firefox is still immune.

**Comment by madwed** [comment]
Update: I found a solution that fits my case.  Setting alpha to true in the renderer and leaving the clearColor as the default clears things up.
