### ISSUE TITLE
Scope THREE object

### ISSUE THREAD

**Issue by bwlewis** [mrdoob/three.js#6812]
We encountered a subtle issue in our use of three.js in R that stems from the definition of THREE:
```javascript
'use strict';var THREE={REVISION:"70"};...
```
that we fix manually now by editing to:
```javascript
'use strict';var THREE=window.THREE={REVISION:"70"};...
```
See this issue for more details: https://github.com/bwlewis/rthreejs/issues/15#issuecomment-104391327

We can live with this simple edit, it's not a big deal. But I wonder if this subtle issue may also affect others? If so, is this a change that could be incorporated into three.js?  If not, just close this. Thanks!

**Comment by mrdoob** [comment]
I suspect this may have side effects...

**Comment by bwlewis** [comment]
Yes, probably so. As I said it's no big deal for us to handle. If this comes up for someone else, you can refer them this. Cheers!
