### ISSUE TITLE
activation/deactivation of controls

### ISSUE THREAD

**Issue by rfm1201** [mrdoob/three.js#6813]
In my program I’m using more than one control depending of what the user wants. So I need to activate/deactivate controls for the events to be managed by the right control.

Most of the controls have an "enabled" property. Some of them let the caller manipulate it directly, some manage it internally. BUT some of them don’t have this kind of property (TransformControls is the one I had to modify).

Would it be possible to "standardize” the activation/deactivation of controls?

I know that controls are not part of the three.js core, but I think they are used by most programs build on three.js. To my opinion some kind of standardization could help, and I think that  activation/deactivation is one of those feature.

The other point is that when somebody modifies a control, it's better done when done by someone that really understands how the control works. Adding "enabled" to TransformControls was not a big challenge but I miss one or two things in my first attempt (and had to do it again when TransformControls was modified).

**Comment by arodic** [comment]
+1

In addition, I think there should be a standardized way of attaching/detaching controls to different objects as well. One issue I ran into was when I wanted to change cameras in an interactive viewport with OrbitControls (or EditorControls) it was difficult to reuse the the same controls on a different camera. 

Moreover, sometimes controls need to be disposed and event listeners removed. With some controls that is currently impossible.

**Comment by mrdoob** [comment]
+1

**Comment by rfm1201** [comment]
May I suggest the following methods:
- enable, without parameter, to activate the control;
- disable, without parameter, to deactivate the control;
- dispose, without parameter, for the control to do all the cleanup it can to become collectible (by the garbage collector). Some controls may have nothing to do to be collectible.

Add/remove the methods you think ANY control should implement.

**Comment by arodic** [comment]
I just submitter a PR #14170 with new version of TransformControls. However, I haven't implemented `enabled` property. Is that a requirement?

**Comment by arodic** [comment]
Way overdue, but done!

**Comment by arodic** [comment]
@mrdoob this one should be closed,
