### ISSUE TITLE
Less shadowmap rendering

### ISSUE THREAD

**Issue by Astrak** [mrdoob/three.js#6814]
In different situations shadowmaps can be used for static objects that do not move often : 
- a procedural city (big shadow maps), 
- objects that move only when dragged.... 

In those situations we need shadowmap rendering, but not each frame. For example, once a part of a procedural city has been created, the buildings don't move but the shadow rendering still uses a lot of computational power. 

Here is the suggestion of a `shadowMapNeedsUpdate = true` parameter to the WebGLRenderer the way `verticesNeedUpdate` work. 

Its value is checked in the ShadowMapPlugin and set to false just after :

    if( _renderer.shadowMapEnabled === false || _renderer.shadowMapNeedsUpdate === false ) return;

    _renderer.shadowMapNeedsUpdate = false;

This way the shadowmap is rendered once at the first render call, and if the scene requires the realtime shadowmap it has to be precised in the render loop. Otherwise it has to be precised in the functions that move/create/delete objects.

**Comment by RemusMar** [comment]
> In different situations shadowmaps can be used for static objects that do not move often :
>
>    a procedural city (big shadow maps),
>    objects that move only when dragged.... 

To use dynamic shadows for static objects is a VERY bad idea.
In those cases you need **static lightMaps**
Example: http://necromanthus.com/Test/html5/SMC.html 

cheers

**Comment by Astrak** [comment]
Thanks.

I use that way as much as i can too, also for moving objects when possible (car shadow in [helloracer](http://helloracer.com/racer-s/)..).

But sometimes you cannot pre-draw even pre-bake shadows. In a procedural city you can't draw the casted shadow of one building on another, because you don't know what position they will have. 
Other situations : a skinnedmesh that stops moving, an interactive scene where static objects can be dragged and need shadow casting....

I just hope it can help free computational power

**Comment by RemusMar** [comment]
> But sometimes you cannot pre-draw even pre-bake shadows. 

I think you're looking for something like **mesh.shadowMapNeedsUpdate = true (or false);**
In other words, that particular shadowMap needs to be computed only once (after mesh creation or movement).
And yes, that would be a very useful feature.

cheers

**Comment by arodic** [comment]
> To use dynamic shadows for static objects is a VERY bad idea.

There are scenarios where you might want a static shadow on dynamic objects. In that case lighmaps are insufficient.

**Comment by Astrak** [comment]
I might have overestimated the gain : i just applied the idea to [draggable cubes](http://mrdoob.github.com/three.js/examples/webgl_interactive_draggablecubes.html) (a simple scene that gives headaches to my 2012/intel5 laptop ) but see no difference in CPU usage (integrated GPU intel HD Graphics).

 


> mesh.shadowMapNeedsUpdate

@RemusMar Wouldn't that be equivalent to renderer.shadowMapNeedsUpdate since there is one shadowmap per light source ?

@arodic what about a scene like draggable cubes ? How do you cast shadows *on buildings* in a procedural city ? etc

**Comment by RemusMar** [comment]
> Wouldn't that be equivalent to renderer.shadowMapNeedsUpdate since there is one shadowmap per light source ? 

You need to disable the shadows computing for all the static objects.
So to spare processing power and to keep the best results (shadows) for the other dynamic objects,
you need something enabled/disabled "per mesh".

**Comment by Astrak** [comment]
It would ask the webglrendertarget to remember each mesh'projection on the shadowmap and update the new projection and the old one am i right ? Hey wouldn't that be easy to code ? ^^ However drawing the new projected part only is something beyond my skills.

Also as i wrote i see no difference at all on my GPU-CPU, in the examples i've changed with a not-updating shadowmap. I test it elsewhere tonight and report if i see a real improvement.

**Comment by RemusMar** [comment]
You need "shadowMapNeedsUpdate = true (or false)" per mesh to make the difference between static and dynamic objects.
On the other hand keep in mind: the shadows are STLL drawn for ALL the meshes!
So you will see a performances boost only in case of hundreds/thousands of meshes.
Otherwise the boost is close to zero.

cheers

**Comment by Astrak** [comment]
@RemusMar I did not precise the different situations i encounter are *only* scenes with static meshes, like draggablecubes (i quote this example again as it matches those different situations). I mean, when nothing move both ideas behave the same, so completely preventing the shadowmap rendering is yet a first step.

Anyway, if ever the result is really ok for static cases, i see no decrease in CPU-GPU usage in the examples i'm testing.

What is STLL ? no google result at all.

**Comment by RemusMar** [comment]
>  i see no decrease in CPU-GPU usage in the examples i'm testing.

You need to perform a test with hundreds of objects and using the "per mesh" approach.

> What is STLL ?

You STLL cast/receive shadows for all the models.
So that shadowMapNeedsUpdate is almost irrelevant for a few models.
You won't gain anything.

I have to go now.
cheers

**Comment by mrdoob** [comment]
Thanks for the suggestion! It was pretty easy to implement 😊

You can now do this:

```javascript
renderer.shadowMap.autoUpdate = false;
renderer.shadowMap.needsUpdate = true; // when your scene changes
```

**Comment by rohan-deshpande** [comment]
Hey so happy I found this. This feature is totally undocumented! https://threejs.org/docs/#api/renderers/WebGLRenderer I was already doing something like this but it wasn't as performant as this and this has massively increased performance in my app. Will open PR to get it into the docs.

**Comment by WestLangley** [comment]
@rohan-deshpande Can you please explain your use case? Are you re-rendering even if your scene hasn't changed? How is `renderer.shadowMap.autoUpdate = false` "massively" improving performance your use case?

**Comment by mrdoob** [comment]
@WestLangley It basically allows computing the shadowmap just once.

**Comment by WestLangley** [comment]
I understand that. But if the scene is static, I was wondering if the user was using an animation loop unnecessarily.

**Comment by rohan-deshpande** [comment]
Basically what @mrdoob said. It's a very similar situation to what @Astrak was describing

 ![image](https://i.imgur.com/AgZqtql.jpg)

The building is static, but the camera can move, rotate etc., the game loop is constantly rendering and waiting for jobs from the animation queue. In this use case, I only need the shadows to be rendered once. After that, they never need to be updated. Except in the case of editing lights (which is what I'm doing here).

**Comment by rohan-deshpande** [comment]
PR for docs update is here https://github.com/mrdoob/three.js/pull/12417
