### ISSUE TITLE
Assigning the animation name to import it to three.js 

### ISSUE THREAD

**Issue by ericaokamura** [mrdoob/three.js#6816]
I was wondering...if a Blender file contains many animations, how will the three.js library know which animation you want to open on the browser? Because since the THREE.AnimationHandler.add() was deprecated, you should use the THREE.Animation (mesh, geometry.animation) function, which does not require the animation name. Does someone know how three.js does it?

**Comment by WestLangley** [comment]
SO post and answer: http://stackoverflow.com/questions/31306004/three-js-r71-assigning-the-animation-name-to-import-it-to-three-js
