### ISSUE TITLE
WebGL particle demos are broken

### ISSUE THREAD

**Issue by daoshengmu** [mrdoob/three.js#6821]
I find  ```webgl_particles_shapes.html``` and ```webgl_particles_dynamic.html``` are broken at ```dev``` branch.

**Comment by mrdoob** [comment]
Yeah. Quite a lot of things are broken at the moment 😇

**Comment by Mugen87** [comment]
This issue can be closed since `webgl_particles_shapes.html` was deleted with d3b3b6f00f5797c3249ce977f51570238a2f521f and `webgl_particles_dynamic.html` (now `webgl_points_dynamic.html` see 9366cfc891c1fc26d32d087cb81d2c399ef0dd95) works properly.
