### ISSUE TITLE
.Obj Shadow Issues

### ISSUE THREAD

**Issue by joe-gh** [mrdoob/three.js#6822]
I've spent a lot of time reviewing docs and examples and other issues related to shadows being cast / received by files loaded with ObjLoader, but am still having issues getting things to work properly in my environment.  I'm using three.js r71, latest chrome / FF, MBP 2012 w / AMD Radeon HD 6750M 1024 MB.

My lighting system is set up with ambient lighting (0x444444) and a spotlight as that is able to cast shadows : 

	spotlight = new THREE.SpotLight( 0xffffff, 1, 0, Math.PI / 2, 1 );
	spotlight.position.set(-150, 500, 180);
	spotlight.target.position.set(0, 0, 0);
	
	spotlight.castShadow = true;
	
	spotlight.shadowCameraNear = 10;
	spotlight.shadowCameraFar = 3500;
	spotlight.shadowCameraFOV = 50;
	
	spotlight.shadowBias = 0.0001;
	spotlight.shadowDarkness = 0.5;
	
	spotlight.shadowMapWidth = 2048;
	spotlight.shadowMapHeight = 2048;
	
	spotlight.shadowCameraVisible = true;	

	scene.add(spotlight);

I have been able to verify that the items and environment themselves are lit by the spotlight, and the shadow camera appears to be over everything correctly.

The renderer is created with : 

	renderer.shadowMapEnabled = true;
	renderer.shadowMapType = THREE.PCFShadowMap;

The base .Obj file I wish to have receive shadows is created with : 

	var bump_texture = THREE.ImageUtils.loadTexture('/images/main_new_n.png', {}, function() {
		var texture = THREE.ImageUtils.loadTexture('/images/main_new.png', {}, function() {
			texture.minFilter = THREE.LinearFilter;
			var storefront_mat = new THREE.MeshPhongMaterial({
				ambient     : 0x444444,
		                color       : 0xcccccc,
		                shininess   : 20, 
		                specular    : 0x111111,
		                shading     : THREE.SmoothShading,
		                map     : texture,
		                bumpMap: bump_texture, 
		                bumpScale: 0.5
			});
								
			objLoader.load( '/models/main_new.obj', function ( object ) {
				object.traverse( function ( child ) {
					if ( child instanceof THREE.Mesh ) {		
						child.material = storefront_mat;
						child.castShadow = true;
						child.receiveShadow = true;
						child.geometry.computeFaceNormals();
			                        child.geometry.computeVertexNormals();
					}
				});
				//object.castShadow = true;
				//object.receiveShadow = true;
				scene.add( object );
		
			}, onProgress, onError );
		});
	});

I have played with various combinations of object / child cast and receive shadows after reviewing other help requests, but had no luck.

The objects that are casting shadows onto that base object are created with : 

	var model_mat = new THREE.MeshPhongMaterial({
		ambient     : 0x444444,
        	color       : 0x33da87,
        	shininess   : 50, 
        	specular    : 0x33da87,
        	shading     : THREE.SmoothShading
	});	

	object.traverse(function (child) {
        if (child instanceof THREE.Mesh) {
            child.material = model_mat;
            child.castShadow = true;
            child.receiveShadow = true;
        }
    });   
	
    //object.castShadow = true;
    //object.receiveShadow = true;

Again, I've played with various combinations of object vs mesh casting / receiving shadow with no luck.  It does seem like the models are trying to do something, but it just comes out as a weird artifact as seen here

![screen shot 2015-07-10 at 11 44 42 am](https://cloud.githubusercontent.com/assets/13276402/8622467/b6ee581e-26f9-11e5-9552-d88066d7db2b.png)

It looks like the model has is casting a shadow on itself perhaps, but doesn't look right and it's not casting to any other surface.  Is there anything obvious I'm missing?

**Comment by WestLangley** [comment]
I expect it is https://github.com/mrdoob/three.js/issues/5232.

Try removing the map and the bumpmap from the materials receiving shadows.

**Comment by joe-gh** [comment]
I'm testing it out shortly.  My concern is I'm having the same issues in Firefox, which that issue claims isn't a problem.

**Comment by joe-gh** [comment]
Okay! Hopefully good news - removing texture and bump map get everything working.  Has there been any progress in figuring out a solution to this?  I'll read through the linked material and see if any work around is posted there for the mean while.

**Comment by mrdoob** [comment]
It'll be great if you could upload the files somewhere so we can debug it.
