### ISSUE TITLE
Global scene to store global lights

### ISSUE THREAD

**Issue by tonnot** [mrdoob/three.js#6823]
Hi: 
I have a suggestion. 

I have a custom scene-layers system. Depending of situation I render ones or another scenes.
Also I have more ideas to this system. One of them is some kind of custom hierarchical store and custom data links.  OK. now I render my scenes without problem. I have a loop code I use to render and / make some other actions with the scenes

The problem I have is when I use lights.
Lights are used at scene level, so my multi-scene-layers approach  need one of the next two solutions:
1.- Create a 'parent' scene where I place the lights and then add all the scenes you want to render. Render that parent scene and THREE will navigate over the scene-childrens.
2.-Clone  the  lights to apply to all the scenes you want to render....(worst approach...)

My idea. Create a 'global' scene  and a local 'useglobal_light' variable for scene so when render a scene  the renderer would check this variable and if true use these lights in addition to the 'locals' lights.  That variable should be true by default. 

If nobody adds lights to the global scene and set 'useglobal_light' nobody are going to note any change.  So there is not danger to break nothing, and the render performance would nto be affected.

This 'global scene' shouldn't have geometry only some 'global' elements. (lights, 
Maybe this 'global' scene could have another 'global' properties (and every scene a variable to let use or not the global set ). 

The global scene would be a unique object. Something like this could be used:
    Myglobalscene = THREE.getGlobalScene();
    THREE.setGlobalScene(myGlobalSene); // to use one global or another..
    THREE.GlobalScene.someProperty = 'x''.
    THREE.GlobalScene.add ( light) ;
    etc ..

I hope my idea had been good explained.  I think that can be useful, isn't it ?

Thanks (sorry for my english)

**Comment by mrdoob** [comment]
I think you should be able to achieve this by using groups:

```javascript
// global scene
var globalscene = new THREE.Scene();

// add lights
globalscene.add( new THREE.PointLight() ); 

// create scenes
var scene1 = new THREE.Group();
globalscene.add( subscene1 );

var scene2 = new THREE.Group();
globalscene.add( scene2 );

// render
scene2.visible = false; // hide sene2
renderer.render( globalscene, camera );
```

**Comment by tonnot** [comment]
Sorry for late answer. 
Yes I know I can work as you suggests but the idea I have proposed is more automatic&autonomous, ins't it ? Using a methafor, it would be like you have a street or world (my global scene) with some street lamps and a room inside a house (the scenes ) with their own lights. By default my room would receive the street lamps. The other long way would be to do something like you have explained... 

I know there are now things more important to do but please consider to create the way I have suggested. Thanks.

**Comment by WestLangley** [comment]
We have discussed similar features in the past:  See https://github.com/mrdoob/three.js/pull/5931 and referenced links.

**Comment by mrdoob** [comment]
@tonnot You can always do an API that sits on top of three.js that behaves as you suggest. I think the fact that you can do that means that the current design is good.

**Comment by tonnot** [comment]
@mrdoob Yes, of course I can do it but IMHO a think that it would be a good default behaviour for THREE. It would be an improvement.
@WestLangley I think my idea is simpler. 

   I could write : 

    renderer.globalSceneClear();
    renderer.globalSceneAdd(light1);
    renderer.globalSceneAdd(light2);
 
 And inside  inside WeGLRrenderer  we'd have:

    var globalScene =  new THREE.Object3D(); // To store lights and maybe more things.
    globalSceneClear      = function () {} // clear globalscene childrens
    globalSceneAdd        = function (object) { globalScene.add (object);  } // add lights
    globalSceneRemove = function (object) { globalScene.remove (object);  } // remove light

    Inside render function now you have 
    projectObject (scene)  
    this function detect the scene lights, and add them to the render lights array. (previously cleared every render call ) 

   So only 1 more line would be need (placed before projectObject(scene))
   projectObject (globalScene)  ;

   Only 5 new lines of code would be need to support global lights. 
   In addition this code would be 100% unobstrusive with current THREE behaviour, ins't it ?

What is your opinion ?
I think my approach is 100% clean and have common sense.

Thanks

**Comment by WestLangley** [comment]
@tonnot I agree with @mrdoob. Your suggestion is appropriate for your specific use case, and it can already be implemented within the current three.js framework.

**Comment by tonnot** [comment]
Even in this unobstrusive and clean approach ? Or maybe I have simplified a lot the projectObject function  where the lights are added to the renderer ? Sorry for being so insistent....
