### ISSUE TITLE
Object Position in three.js

### ISSUE THREAD

**Issue by carloscarniel** [mrdoob/three.js#6828]
Hi,
I'm sorry if this is not the right place to post questions related to learning three.js.
I have an issue with the position of cubes in my application. When I set them all with the same size they are rendered properly on the same Y position as I defined: 
Example: 

geometry = new THREE.BoxGeometry(50, 50, 50); 
material = new THREE.MeshBasicMaterial({ color: 0xff0000 })
mesh = new THREE.Mesh(geometry, material);
mesh.position.set(100, 0, 400); // I always set y as 0 because I want the cubes to be on the same level like buildings in a city

And I do the same for the next cubes, only changing the X and Z positions. 
However, when I create cubes with different sizes, which is my objective, as follows,

geometry = new THREE.BoxGeometry(50, 100, 50); 
they appear on a different level in the final visualisation on the browser, as shows the image:

![screenshot 2015-07-13 15 09 12](https://cloud.githubusercontent.com/assets/3678443/8651664/35574c18-2972-11e5-8c75-2612733ea595.png)

The positions are kept the same as before, with Y set to 0.

Any ideas on how to solve this problem? What am I doing wrong?

Thank You,
Carlos

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
