### ISSUE TITLE
3dsMax Animation exporter

### ISSUE THREAD

**Issue by tormozok** [mrdoob/three.js#6829]
When I rescale my animation to start from 55 frame and try to export this animation, then my exported animation stopped about 2 seconds from start. I dig the exporter code and found solution. You need replace expressions "(slidertime / FPS)" with "((slidertime - animationrange.start) / FPS)"

https://github.com/mrdoob/three.js/blob/master/utils/exporters/max/ThreeJSAnimationExporter.ms#L1294

https://github.com/mrdoob/three.js/blob/master/utils/exporters/max/ThreeJSAnimationExporter.ms#L1346

**Comment by mrdoob** [comment]
Do you mind doing the change directly?
https://github.com/mrdoob/three.js/edit/dev/utils/exporters/max/ThreeJSAnimationExporter.ms

**Comment by tormozok** [comment]
Nice built-in editor! =)

**Comment by Mugen87** [comment]
The exporter has been removed, see #12930
