### ISSUE TITLE
ShaderPass extra textures are black

### ISSUE THREAD

**Issue by mlepage** [mrdoob/three.js#6830]
I came across this issue using EffectComposer and ShaderPass:

http://stackoverflow.com/questions/14323970/cant-send-a-texture-to-a-custom-shader-shaderpass-effectcomposer

Briefly, we both had a problem where input texture was getting to the first shader pass, and subsequent shader passes were getting the output from the previous passes, but subsequent shaders were not getting an extra texture we were trying to set (it was just sampling black).

I debugged it and found that the texture ID was changed when accessed from within the shader pass, compared to outside the effect composer.

Looking in the constructor for ShaderPass, I could see it clones the uniforms passed in. By sidestepping this code, I was able to keep the passed in texture object, which had the expected texture ID, and sampled correctly in my shader.

So the problem seems to involve the cloning of the texture uniform, something there has to change, I'll leave it to you to figure out the proper fix.

The problem is reproducible, just make a second pass shader with an extra texture (that isn't its input from the previous pass) and sample it.

**Comment by mrdoob** [comment]
> The problem is reproducible, just make a second pass shader with an extra texture (that isn't its input from the previous pass) and sample it.

Could you do a jsfiddle that reproduces the issue?

**Comment by WestLangley** [comment]
Hopefully you are referring to the current three.js version. Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by mlepage** [comment]
This is using the latest version mrdoob-three.js-r71-5-gd6384d2.zip. It is apparently a bug.

**Comment by WestLangley** [comment]
See the discussion in https://github.com/mrdoob/three.js/pull/5672.
