### ISSUE TITLE
How to solve the mesh distance is too close, the calculation of the depth of the accuracy of the problem can not cause color。

### ISSUE THREAD

**Issue by mirro187** [mrdoob/three.js#6833]
![img_1](https://cloud.githubusercontent.com/assets/12796811/8677921/5e3f2d86-2a84-11e5-99ed-7d63f48bb994.PNG)

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

If you post on stackoverflow, you must show your code, too.
