### ISSUE TITLE
View Frustum culling of children does not work

### ISSUE THREAD

**Issue by simon-heinen** [mrdoob/three.js#6834]
It seems to us that the frustum culling does not work for children of an object in the scene. Here is a simplified problem description:
- We have 1 parent object3d which is set to visible=false and frustumCulled=true
- We add to this parent 100 textured child-object with 512x512 textures each
- We switch visible to true in the parent object
- the renderer crashes because it tries to load all children objects into memory (i guess?) even if they are not in the field of view (is there a way to avoid this?)
- If we only show x children at once and hide children again it still crashes because the memory is not freed again when a child is not visible anymore (is that correct? how do we free this memory again?)

Our testing devices are mobile devices (the fastest it crashes on an samsung s3 but the same problems seem to occur on desktop machines after the memory limits are reached)

JSFiddle to reproduce the problem: http://jsfiddle.net/vao125wx/13

**Comment by mrdoob** [comment]
I'm having a hard time to follow your issue description. Can you create a jsfiddle that reproduces the issue?

**Comment by simon-heinen** [comment]
Sorry I upated my original text and tried to make it a little bit more clear how our tests look like currently. we will provide the example as code in the next hours

**Comment by simon-heinen** [comment]
Ok here is the jsfiddle to reproduce the problem: http://jsfiddle.net/vao125wx/9/
We now show only one image at a time.
On a Samsung S3 it can load about 30-40 images before it crashes
On a Samsung S5 it can load about 110 images before it crashes

**Comment by antont** [comment]
AFAIK `visible=false` is not even meant to free memory, just to configure whether to render or not. So you can for example quickly temporarily hide it and then show again, with not delay for the reloading in the meantime.

To free memory you need to actually remove the object from the scene and dispose the meshes, textures or both.

http://stackoverflow.com/questions/21851349/freeing-memory-in-three-js is a bit old but gives you the idea.

**Comment by simon-heinen** [comment]
To release the memory we do exactly what is posted in your stackoverflow link, the visible flag we dont use in the simplified example ( http://jsfiddle.net/vao125wx/13/ ) now, but it still crashes on the mobile devices, because the graphics memory is not freed for some reason

**Comment by antont** [comment]
I recall seeing an issue recently about memory not being freed, might be a bug in current version. It did work earlier. My flight is leaving now so can't check more - will search for that issue later unless others have provided info already.

**Comment by WestLangley** [comment]
Removed errors/warnings from fiddle: http://jsfiddle.net/vao125wx/17/

`renderer.info.memory.textures` is increasing for some reason...

**Comment by mrdoob** [comment]
Using the `dev` version in case we indirectly fixed it already...? http://jsfiddle.net/vao125wx/19/

**Comment by WestLangley** [comment]
> Using the dev version in case we indirectly fixed it already...?

`renderer.info.memory.textures` is increasing using the `dev` version, too.

**Comment by gero3** [comment]
You need to dispose of textures manually because they can be used by multiple materials.

http://jsfiddle.net/vao125wx/21/

**Comment by WestLangley** [comment]
Thanks, @gero3. Here is an equivalent way:

    mesh.geometry.dispose();
    mesh.material.map.dispose();
    mesh.material.dispose();
    scene.remove( mesh );

http://jsfiddle.net/vao125wx/23/

**Comment by simon-heinen** [comment]
Uh nice, so only this line "mesh.material.map.dispose();" was missing, but I don't get why material.dispose() does not not trigger material.map.dispose() as well, why is that so?

**Comment by mrdoob** [comment]
> but I don't get why material.dispose() does not not trigger material.map.dispose() as well, why is that so?

As @gero3 said, because the texture could be used in another material.

**Comment by simon-heinen** [comment]
But couldn't the material/texture figure this out itself? Something like a TextureManager which checks such references and releases memory automatically?

**Comment by gero3** [comment]
What if you just want to  create a new material with the same texture while disposing of the material?? 
It is pretty hard to predict what the need for textures is.

**Comment by mrdoob** [comment]
Yes and no. I can easily imagine a use case were someone is changing materials but using the same texture and we're disposing and uploading the texture wastefully.

**Comment by mrdoob** [comment]
Yep, same as @gero3 said.

**Comment by mrdoob** [comment]
We should, however, add a note about this in `Material.dispose` in the docs.

**Comment by simon-heinen** [comment]
If I run now the latest http://jsfiddle.net/vao125wx/25/ with renderer.info.memory.textures constantly staying at 1 on the Samsung S3 it works much longer (it makes it to 100-120 loaded textures but then still crashes) so there must be another object we do not release :/ Maybe its now not the graphics memory but the normal browser memory?

**Comment by Usnul** [comment]
Reference counting for textures could be a useful thing to consider?

**Comment by dubejf** [comment]
http://jsfiddle.net/vao125wx/27/ Convert `BoxGeometry` to `BufferGeometry` manually. There is probably a memory leak when letting the renderer take care of the conversion. See #6729. Not a big problem here.

![timeline27](https://cloud.githubusercontent.com/assets/8649151/8749642/e5473c86-2c70-11e5-9886-bc3015a84a1f.PNG)


http://jsfiddle.net/vao125wx/28/ Clear the `THREE.Cache`!

![timeline28](https://cloud.githubusercontent.com/assets/8649151/8749644/e9185462-2c70-11e5-91b9-11c1e095f549.PNG)

Also, if you use Chrome, you can monitor the GPU memory usage in chrome://memory

**Comment by mrdoob** [comment]
> http://jsfiddle.net/vao125wx/28/ Clear the `THREE.Cache`!

> ![timeline28](https://cloud.githubusercontent.com/assets/8649151/8749644/e9185462-2c70-11e5-91b9-11c1e095f549.PNG)

Good catch!

**Comment by simon-heinen** [comment]
Oh ok thanks for the tip with chrome://memory :+1: 
Do I break something in a normal scene with many objects if I frequently clear the cache after removing one of the objects?

**Comment by dubejf** [comment]
You can clear the cache in your `onLoad` callback, or in the render loop if you want. You could also monkey patch it if you don't want to use it at all: `THREE.Cache.add = function () {}`.

**Comment by gero3** [comment]
You should be able to enable or disable the cache don't you think so @dubejf

**Comment by dubejf** [comment]
@gero3 Overwriting `THREE.Cache.add` does just that, but you could also add `.enabled` and maybe `.maxBytes` and `.maxItems` to remove LRU item, or maybe just shout a warning that that hey three.js has a cache and it's getting huge.

Also, maybe the cache should not be global and be per-loader instance instead, to limit growth to the lifetime of the loader. Previous discussion #5650

**Comment by WestLangley** [comment]
@simon-heinen How about changing the title and content of your original post so it is descriptive of the issue.

**Comment by titansoftime** [comment]
This bit me as well. Could not for the life of me figure out where 40MB of ``ArrayBuffer`` data was coming from. ``THREE.Cache`` had a copy of my ``CompressedTexture.image`` data!

Having the ability to enable or disable the cache would be nice (I just replaced the ``THREE.Cache.add`` function), but you would have to know about this situation to begin with.

**Comment by MasterJames** [comment]
How about an argument to cache or not when loading?

**Comment by dubejf** [comment]
`Cache` is now opt-in, #6876.
