### ISSUE TITLE
transparent = false and then needsUpdate won't update transparency.

### ISSUE THREAD

**Issue by prominentdetail** [mrdoob/three.js#6836]
If I have a multimaterial that has transparency enabled on one texture, if I set that transparency to false and then needsUpdate = true. It won't update the change to the transparency, so it continues being transparent.

					material[i].texture.transparent = false;
					material[i].texture.needsUpdate = true;

edit: actually, I think it might be related to being updated too soon.. If I delay the update, it seems to work. Not sure what is causing it in my code. Maybe it is loading the images, and having to wait until they're loaded, and it tried to update it before then, and those changes might be getting overridden.

**Comment by WestLangley** [comment]
You need to do that in the loader callback.
