### ISSUE TITLE
Are non-affine transforms handled correctly?

### ISSUE THREAD

**Issue by disolovyov** [mrdoob/three.js#684]
The non-affine transforms part of geometry matrix (n41, n42, n43) works not as expected, on geometries with low polygon count.

For example, here's two pictures of Charles Petzold's face:

![](http://i.imgur.com/PQoYl.png)
1. With piecewise affine transform
2. With actual non-affine transform

The first one is what we would get with one Face4 (two triangles, right?). The second one is the result of adding much more faces. The thing is, it should be possible to do the second one even with two faces.

So my question is: why are non-affine transforms approximated with piecewise affine transforms? Is there a way to do a pretty non-affine transform on something like `THREE.PlaneGeometry(1, 1, 1, 1)`?

**Comment by yousefamar** [comment]
Just out of interest, was this issue closed due to age, or has it been solved somewhere?

**Comment by Mugen87** [comment]
@yousefamar Because of its age, this issue is totally out of scope. If this problem is still relevant to you, please open a new issue.
