### ISSUE TITLE
Use of UniformsUtils.merge prevents the update of uniforms's variables

### ISSUE THREAD

**Issue by lateek35** [mrdoob/three.js#6841]
UniformsUtils.merge use the clone method that does not seem to clone by reference. So uniforms variables are not update into the shader

So this, is not working:

``` javascript
uniforms = {
     time: { type: "f", value: 1.0 },
};

var material = new THREE.ShaderMaterial( {
     uniforms: THREE.UniformsUtils.merge( [
         THREE.UniformsLib[ "common" ],
         uniforms
     ] ),
     ...
     ...

uniforms.time.value ++;
```

Here my workaround

``` javascript
uniforms = THREE.UniformsUtils.merge([
    THREE.UniformsLib[ "common" ],
    myuniforms
]);

uniforms.time={ type: "f", value: 1.0 };

var groundMaterial = new THREE.ShaderMaterial( {
     uniforms: uniforms,
     ...
     ...

uniforms.time.value ++;
```

[r71]

**Comment by WestLangley** [comment]
Yes. You should set the uniform values _after_ merging and/or cloning. This is a feature.

I do not think your example demonstrates the issue, however.

**Comment by tschw** [comment]
`UniformsUtils.merge` uses deep-copy and can't be used to reference an external entry, e.g. for broadcasting the value to multiple materials. Can't do it in general - Imagine `time` was `color`, and the user should be in control.
```javascript
var broadcast = {

    time: { type: "f", value: 1.0 },
    // [...]

]};

// [...]

function customizedUniforms( shared, opt_unique ) {

    var result = THREE.UniformsUtils.merge(
            THREE.UniformsLib[ "common" ], opt_unique );

    for (var key in shared) result[ key ] = shared[ key ];

    return result;
}

var groundMaterial = new THREE.ShaderMaterial( {

    uniforms: customizedUniforms(broadcast
            /*, optionally special stuff for the ground */)
    // [...] 
} );

// [...]

boadcast.time.value += deltaTime;

```

**Comment by pailhead** [comment]
ping @WestLangley

**Comment by WestLangley** [comment]
@pailhead 

I am stating what the user must do to accommodate the `merge()` method as it is written.

My understanding is you are arguing that the `merge()` method should be rewritten. I do not think our statements are in conflict.

**Comment by pailhead** [comment]
@WestLangley 

Definitely not, i just didnt know where to start this discussion :)

**Comment by Mugen87** [comment]
Closing. Since `R114`, `UniformsUtils` is documented and the deep-copy of `.clone()` highlighted.
