### ISSUE TITLE
WebGLRenderer.loadUniformsGeneric()

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#6854]
This method needs to be looked at by someone familiar with the code.

	case 'Matrix3fv':
		_gl.uniformMatrix3fv( location, false, value );
		break;
	case 'm3':
		// single THREE.Matrix3
		_gl.uniformMatrix3fv( location, false, value.elements );
		break;

Similarly for `Matrix4`. There may be other issues.

**Comment by mrdoob** [comment]
This should be fine. Initially @alteredq made the `m3` case, but at some point I thought that it would be nice to have "native" `Matrix3fv` case were you could pass a `Float32Array` instead of a `THREE.Matrix3`.

**Comment by WestLangley** [comment]
I see. Do you think clearer string names would be appropriate?

**Comment by mrdoob** [comment]
The thing is that this is for advanced users, so that's why I thought `Matrix3fv` was more intuitive.

**Comment by WestLangley** [comment]
I find this confusing, however.

```javascript
case '1fv':
	_gl.uniform1fv( location, value );
	break;

case 'fv1':

	// flat array of floats (JS or typed array)
	_gl.uniform1fv( location, value );

	break;
```

There are other examples:

```javascript
case '3iv':
	_gl.uniform3iv( location, value );
	break;

case 'iv':

	// flat array of integers with 3 x N size (JS or typed array)
	_gl.uniform3iv( location, value );

	break;
```

I think there should be an inline comment with each case for clarity.

I would offer to clean this up a bit, but I do not know how you would prever to handle each of these use cases... And there are a lot of them. : - )
