### ISSUE TITLE
ThreeJS 3DS Max Export error ''ambient'' VrayMtl

### ISSUE THREAD

**Issue by hemantchhabra** [mrdoob/three.js#6856]
@mrdoob we have a set of models with have materials configured in vray. While using threeJS export for 3DS max, this is the kind of error we are encountering and are not able to find a workaround. Please help us. 
MAXScript rollout handler exception : --Unknown property: ''ambient'' in NameOfEntinty:VRayMtl

NameOfEntity is the name of the object on which the material is applied.
Can you help us find a workaround?
Thank you for reading.

**Comment by WestLangley** [comment]
In three.js, the material property `ambient` has been removed. It was the ambient reflectance of the material -- how the material reflects ambient light.

We now assume that a material reflects ambient light in exactly the same way it reflects light from direct light sources. In other words, the material property `color` describes how all light is reflected.

It sounds like the Max exporter needs to be updated.

**Comment by hemantchhabra** [comment]
@westlangley Thank you for your comment and understanding. Maybe if any developer is willing, he/she could modify the existing code to just suit the requirement so that even if the ambient is not exported in the way threeJs understands it, but atleast the model is exported? So that we don't have to sit and remove all the materials with ambient. Ready to apply exporter that would be, just like Blender's exporter. Hope am making sense.
Thanks for your time :)

**Comment by WestLangley** [comment]
@hemantchhabra If I were you, I would not wait. I would do whatever it takes to get something working. Try editing the exporter file. Try to find the offending code.
