### ISSUE TITLE
Closure function naming

### ISSUE THREAD

**Issue by benaadams** [mrdoob/three.js#6857]
Currently returned closures in functions that require temp variables are unnanmed e.g.:

````javascript
THREE.Vector4.prototype = {

      clampScalar: ( function () {

		var min, max;

		return function ( minVal, maxVal ) {
		...
````
This means when debugging or outputting a stack trace on an error this is an anonymous function and will be reported as ```(anonymous function)```

Would it be worth naming these functions so they do get properly output? e.g.
````javascript
THREE.Vector4.prototype = {

      clampScalar: ( function () {

		var min, max;

		return function clampScalar( minVal, maxVal ) {
		...
````
Which will then be shown in the stack trace as ```clampScalar```

**Comment by gero3** [comment]
Keep in mind that closure compiler could remove those

**Comment by benaadams** [comment]
> Keep in mind that closure compiler could remove those

If you are debugging minified nothing makes sense anyway so not worried about that :)

**Comment by mrdoob** [comment]
This sounds good to me.

**Comment by benaadams** [comment]
Done #6859
