### ISSUE TITLE
Setting needsUpdate on broken texture crashes renderer "Cannot read property 'width' of undefined"

### ISSUE THREAD

**Issue by DelvarWorld** [mrdoob/three.js#6861]
If you do something like this in your code:

    let texture = THREE.ImageUtils.loadTexture( 'not_real_texture.jpg' );

and then before a render call:

    texture.needsUpdate = true;

then the render call will crash:

    renderer.render( scene, camera );

    // throws error:
    // Uncaught TypeError: Cannot read property 'width' of undefined

It happens at this line: https://github.com/mrdoob/three.js/blob/5c7e0df9b100ba40cdcaaf530196290e16c34858/src/renderers/WebGLRenderer.js#L5608

I imagine this is as undefined corner case of the image logic. However, it's not ideal that the render call itself crashes. A warning would be more appropriate. The crashing render call does not have an obvious call, since simply loading a failed texture and assiging it does *not* cause a crash. Only when setting `needsUpdate` does it crash. It makes debugging hard.

I'm not sure if this is a bug or not, but hopefully at least this ticket helps someone identify their error.

**Comment by benaadams** [comment]
Why do you set ```needsUpdate = true``` the loader will do this when the texture has loaded.

**Comment by DelvarWorld** [comment]
Oh nice, this was already fixed! 

https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L3344

It's just not in master yet. Looks like the next release of Three has lots of goodes :)

**Comment by WestLangley** [comment]
`THREE.ImageUtils.loadTexture( );` sets the `needsUpdate` flag for you after the image loads.

Do not set it yourself. The loading is asynchronous.

**Comment by DelvarWorld** [comment]
@benaadams @WestLangley I'm aware that `loadTexture` sets `needsUpdate` after load. I have a specific case where I switch scenes. I clone textures and put them in the new scene. Without setting `needsUpdate` on the cloned texture, I get a black texture. I also have some legacy data that has broken texture paths, so I will try to clone a texture that hasn't loaded and set `needsUpdate` on the clone, which is a broken image, causing this bug. Either way, it was fixed.

**Comment by benaadams** [comment]
> I have a specific case where I switch scenes. I clone textures and put them in the new scene.

Any reason you need to clone the texture rather than just reusing it? Multiple meshes/materials can use the same material. 

Cloning the texture and setting ```needsUpdate = true``` is essentally saying copy this data from the cpu to gpu multiple times and have multiple identical copies of the data on the gpu.

**Comment by DelvarWorld** [comment]
@benaadams I wrap the texture class in a higher data class to pass around with my objects. Reusing textures would require the class to read from some sort of texture cache, which is not ideal for my use case. It's easier if my higher order Texture class is entirely self contained

**Comment by agnivade** [comment]
@WestLangley - So I had tried loading the texture without setting the `needsUpdate` flag. But there is a momentary flicker of a black surface between the time the texture is not loaded to when its completely loaded. But this flicker is not there when I set the flag manually.

Reference - https://github.com/mrdoob/three.js/issues/432#issuecomment-1823888

**Comment by WestLangley** [comment]
@agnivade Add the mesh to the scene in the loader callback -- not before. See if that solves the flicker problem.

**Comment by agnivade** [comment]
@WestLangley  - Adding the mesh later was very difficult with the way the code was arranged. I solved it in another cool trick. I intially set the the meshes to be `visible=false`. And then in the callback, I set the visibility to true. And it works !

P.S. - Simply upgrading to R72 does not solve the flickering problem. The error turns to a warning but you have to handle the flickering case in your code.

**Comment by mrdoob** [comment]
@agnivade Do you have a live link that shows that flickering?

**Comment by agnivade** [comment]
Umm sorry, its running locally on my laptop :stuck_out_tongue_winking_eye: . But its exactly like I mentioned, momentarily the surface on which the texture is gonna load is black, and when the texture loads, it shows up properly.

For what its worth, I would recommend having an `async` flag in the loadTexture call which will pass the param to the underlying ajax call. Thereby giving power to the user to control the way he/she wants the texture to be loaded. Just my two cents.

**Comment by WestLangley** [comment]
> Umm sorry, its running locally on my laptop

@agnivade Would you please provide a live link to demonstrate the flickering?

**Comment by agnivade** [comment]
Sorry, I dont have anywhere to upload and show you. Also this is a professional work, so I dont think I can send any screenshot or video of any kind. But let me know if I can help in some other way.

**Comment by WestLangley** [comment]
@agnivade I am glad I was able to help you. I bet if you wanted to, you could figure out a way to create a simple example that is unrelated to your work and upload it to dropbox. : - )
