### ISSUE TITLE
THREE.CTMLoader wrong mesh

### ISSUE THREAD

**Issue by tartavull** [mrdoob/three.js#6864]
Hello,
  I'm not sure how to describe this issue so I included some pictures.

I'm using this code to import a mesh:

```
 var ctm = new THREE.CTMLoader(true);
    ctm.load( url , function(geometry){

      var material = new THREE.MeshLambertMaterial( { color:cell.color , wireframe:false } );
      cell.mesh = new THREE.Mesh( geometry, material );
      cell.mesh.scale.set(0.05,0.05,0.05)
      Scene.scene.add( cell.mesh );

      cell.mesh.visible = cell.visible;      
    }, { 'useWorker': true} );
```

While the mesh looks fine in mesh lab.
![meshlab](https://cloud.githubusercontent.com/assets/4648166/8737940/6e193256-2bf6-11e5-9b98-cc5f5718e63b.png)

When imported into the browser a tiny part of the mesh is moved apart.
![webgl](https://cloud.githubusercontent.com/assets/4648166/8737945/742b6e2a-2bf6-11e5-83f4-59c895098aaa.png)

Does anybody has any ideas of what might be causing this?

**Comment by WestLangley** [comment]
If you can demonstrate a three.js bug, can you provide a test case so we can reproduce your results? Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by heltonitba** [comment]
I'm not expert in OpenCTM and mesh Lab, but, I imagine the far vertex was referenced in other type of coordinates (cylindrical, spherical) instead of rectangular.

Sorry if I spoke sheet

**Comment by tartavull** [comment]
I found some new clues,  when I export the meshes as lossless it work just fine, but sometimes when exported with 
![image](https://cloud.githubusercontent.com/assets/4648166/10169928/43a27182-66a1-11e5-83b8-9cb1727612d0.png)
it fails.

based on http://openctm.sourceforge.net/media/DevelopersManual.pdf 
openctm MG1 implements lossless compresion, but mg2 does not.

The MG2 method divides the mesh into small sub-spaces, sorts the data
geometrically, and applies delta-prediction to the data, which effectively lowers
the data entropy. The re-coded vertex data is then compressed with LZMA.

I'm wondering if threejs importer was design to handle both files formats.

**Comment by tartavull** [comment]
here is a link to the file https://drive.google.com/file/d/0B7TY5Ptd55vQNjJwOEN2Y203Rjg/view?usp=sharing

**Comment by Mugen87** [comment]
Closing. `CTMLoader` has been removed #16949
