### ISSUE TITLE
Register three.js on GitFund

### ISSUE THREAD

**Issue by tooksy** [mrdoob/three.js#6865]
I think you can register three.js on <a href="http://www.gitfund.org">GitFund</a>. It will help attract money for project development and as result faster feature implementation.

**Comment by mrdoob** [comment]
How does this work? How do the contributors get paid?

**Comment by Cy-Bo-Rg** [comment]
@mrdoob
don't trust that person!!
He's deliberately spamming that website on many github projects ; it all goes down to some ArtWired Inc. (I'm posting the google webcache result as I don't trust this domain)"http://webcache.googleusercontent.com/search?q=cache:dTozl8sc95IJ:www.artwired.com/+&cd=1&hl=en&ct=clnk&gl=us"
I've tried a website lookup and the domain looked like registered years ago but modified only a few days ago; I've just made a record on the archive.org on which there wasn't a single trace of this; not only that, but after making those lookups , the registar infos are now lost and almost all whois website aren't showing anything about it...
Definitely dangerous.

**Comment by mrdoob** [comment]
Oh, I see... Thanks for the background check @Cy-Bo-Rg!

**Comment by Cy-Bo-Rg** [comment]
Put a donation button on Threejs.org , I would definitely be happy to donate, as would many others :)
And it's safe :P

**Comment by liammagee** [comment]
As an interested user of three.js (and lurker), I'd certainly donate.

**Comment by mrdoob** [comment]
Very much appreciated! But I wouldn't know how to split the money with the contributors...

**Comment by dubejf** [comment]
There are other micropayment services like flattr and gittip that you sometime see on github project pages. I don't know much about them.
