### ISSUE TITLE
r72 release

### ISSUE THREAD

**Issue by Usnul** [mrdoob/three.js#6866]
Is there any idea about when r72 is coming out? It's quite an unusually long release cycle this time around.

It didn't seem like a help question, more of a development of tree.js concern.

**Comment by mrdoob** [comment]
https://twitter.com/mrdoob/status/621369897185054720 😅

**Comment by Usnul** [comment]
Thanks, this clears up a lot.

**Comment by makc** [comment]
Is there a way to see what was changed with buffer geometry ( I  heared there are now many of them, and  buffer attributes changed ) other than just looking in the code? Maybe issue ids where the changes were discussed?

**Comment by mrdoob** [comment]
I plan on writing the change log. Pointing to issue ids is more difficult though. Maybe it's something that I can start from r73...
