### ISSUE TITLE
SkinnedMesh with BufferGeometry r72 

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#6869]
This started here #6749.

Since r72 now supports skeletal animations with ``BufferGeometry`` I thought i could get rid of ``Geometry`` which accounts for roughly 75% of the browser memory consumption in my app.

This is not as straight forward (currently) as I had hoped.

The auto conversion to ``BufferGeometry`` via ``BufferGeometry.setFromObject`` is nice, but it does leave the original ``Geometry`` object attached to the ``Mesh`` or ``SkinnedMesh``. Though there now is additional consumed memory from having the ``Mesh._bufferGeometry`` in addition to ``Mesh.Geometry``, everything works and renders just fine.

What I am trying to do hear is eliminate the ``Mesh.Geometry`` entirely. So instead of letting the auto convert happen, I tried essentially this...

```
var geo = jsonLoader.parse(mygeojson).geometry;

geo = new THREE.BufferGeometry().fromGeometry(geo);

var mesh = new THREE.SkinnedMesh(geo,skinmat);

```

No luck. My guess is that ``Geometry`` needs to be passed to ``SkinnedMesh`` to properly parse the skeleton. I noticed that ``BufferGeometry`` does not have a ``Bones`` attribute, only ``SkinIndices`` and ``SkinWeights`` So this makes sense why the auto convert works. The ``Geometry`` with it's bones are passed to ``SkinnedMesh``, properly attaching the skeleton to the mesh. The auto convert then happens, attaching the ``_bufferGeometry`` to the mesh and all is rendered well.

Is there a way to do what I want and pass ``BufferGeometry`` directly to ``SkinnedMesh``, or is this not implemented yet? The memory overhead reduction would be massive.

PS. I considered posting this on SO, but since r72 is not released, I figured contributors would be pretty much the only people to know the answer.

EDIT

I also saw this in ``THREE.SkinnedMesh``:

```
	// init bones

	// TODO: remove bone creation as there is no reason (other than
	// convenience) for THREE.SkinnedMesh to do this.
```

Will we still be able to attach objects to the ``SkinnedMesh``? For example I currently attach weapons to the models handR bone. What would happen to ``THREE.Skeleton`` along with it's ``useVertexTexture`` property?

**Comment by mrdoob** [comment]
Hmm, I'm surprised that that doesn't work. Could you setup a jsfiddle somehow?

**Comment by titansoftime** [comment]
No problem.

http://jsfiddle.net/nkzqL38m/

Uncomment line 52.

Look at this again, I really don't see how this could work considering ``BufferGeometry.fromGeometry`` does not copy over the ``Geometry.animations``. I could also be going about this all wrong.

I've also shown (though it is useless in this example) how i cache the geometry. Which is another issue I see with not having the ``Geometry.animations`` copied over to ``BufferGeometry``. I would have to cache the animations separately (tried that, no luck), or keep the original ``Geometry`` around (exactly what I'm trying to avoid).

**Comment by MasterJames** [comment]
I'm not really understanding this issue well.
I thought I'd post this anyway..
geoCache[json.name] = new THREE.BufferGeometry().fromGeometry(geo);

**Comment by titansoftime** [comment]
@MasterJames 

The issue is not being able to pass ``BufferGeometry`` directly to ``SkinnedMesh``. If you uncomment line 52 of the posted fiddle (which is basically what you posted here) you will see the problem.

**Comment by MasterJames** [comment]
Oh okay thanks. When I uncomment the model disappears but without stomping on geo my line or geo2  it's back. It just looked to me like maybe there was something wrong in the way you stomped over geo.

**Comment by mrdoob** [comment]
Seems like `JSONLoader` is adding the property `animations` to the returned `Geometry`. `BufferGeometry` doesn't support that.

I have tweaked the code so now it goes a bit further:

http://jsfiddle.net/2k3g2g5j/1/

Now I'm getting a trickier error...

```
[.WebGLRenderingContext-0x7ff12b156460]RENDER WARNING: there is no texture bound to the unit 1
[.WebGLRenderingContext-0x7ff12b156460]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```

**Comment by titansoftime** [comment]
I believe that was the same error I got when I was forcing a copy of ``Geometry.animations`` onto the ``BufferGeometry`` object. Didn't think it would work but gave it a shot anyway.

**Comment by mrdoob** [comment]
> Oh and in http://jsfiddle.net/2k3g2g5j/1/ I am getting this error:

> ```Uncaught TypeError: Cannot read property 'length' of undefined```

Ops! Sorry, I meant http://jsfiddle.net/2k3g2g5j/2/

**Comment by titansoftime** [comment]
Ah, yea that's what it was that caused that error.

**Comment by mrdoob** [comment]
Ok. Figured out the issue.

The bones are not being copied:

```javascript
geo.bones = geo2.bones;
```

http://jsfiddle.net/2k3g2g5j/3/

**Comment by mrdoob** [comment]
Need to clean this up somehow, it's pretty messy...

**Comment by MasterJames** [comment]
Well done!

**Comment by titansoftime** [comment]
Woooooooooo! Very nice =]

Thanks for helping out. Maybe ``animations`` and ``bones`` should be copied by ``fromGeometry``? Is there a downside to having these additional properties on the ``BufferGeometry`` object?

**Comment by mrdoob** [comment]
> Thanks for helping out. Maybe ``animations`` and ``bones`` should be copied by ``fromGeometry``? Is there a downside to having these additional properties on the ``BufferGeometry`` object?

Well, I would prefer not to add properties to `BufferGeometry` arbitrarily. That's exactly the reason this issue was created.

Also, `BufferGeometry` does not need `bones`, it's `SkinnedMesh` the one that looks for `geometry.bones` to [transform that array](https://github.com/mrdoob/three.js/blob/dev/src/objects/SkinnedMesh.js#L24-L58), so that code needs to be refactored somehow.

**Comment by titansoftime** [comment]
Ah Gotcha.

**Comment by makc** [comment]
just clicked through to this issue, have to say skins were working perfectly with buffer geometry in r70 (and r71), all I had to do is put skin indices and weights as attributes (and - yes - put bones on geometry - where threejs code was expecting them). not sure why everyone thought it was not working, or anything had to be done about it at all.
