### ISSUE TITLE
the max export can not get the vertex alpha?

### ISSUE THREAD

**Issue by matrix3d** [mrdoob/three.js#6870]
but the vertex alpha it is useful

**Comment by mrdoob** [comment]
The engine doesn't support vertex alpha yet.

**Comment by matrix3d** [comment]
@mrdoob but how ms get the alpha,i use meshop.getVAphla,and can not get the alpha

**Comment by matrix3d** [comment]
make a option get the alpha will good.the vertex alpha are useful for particle uv scroll map effect.

**Comment by Mugen87** [comment]
The 3DS max exporter has been removed: #12930
