### ISSUE TITLE
Strange behaviour with skinned meshes and some loaders.

### ISSUE THREAD

**Issue by Cy-Bo-Rg** [mrdoob/three.js#6871]
I perfectly recognize that the mobile browser and the chipset that I'm using aren't fully supported, but this is curious. For example, the collada loaders should have behaved the same in my opinion, but the monster is somewhat destroyed (maybe a false index messed up the vertices) ?
Do you think that's a problem with the geometries or a problem with the loaders ?

Messed up (this is perfect with crosswalk and firefox)
![screenshot_2015-07-15-12-48-19](https://cloud.githubusercontent.com/assets/5455606/8761130/afebc928-2d40-11e5-8410-11d6602e99a4.png)

Messed up ( This doesn't even show up with crosswalk's webview 15 canary nor with firefox 40 )
(webgl_loader_json_blender has the same problem,obviously)
![screenshot_2015-07-15-12-49-11](https://cloud.githubusercontent.com/assets/5455606/8761131/b50b0720-2d40-11e5-811d-7e0c6f1640ea.png)

Perfect
![screenshot_2015-07-15-12-50-14](https://cloud.githubusercontent.com/assets/5455606/8761132/b8fac56e-2d40-11e5-9ef9-a6568b50f196.png)

Perfect ( notice : I have a maximum of 24- 30 frames per second on firefox 40)
![screenshot_2015-07-15-12-50-41](https://cloud.githubusercontent.com/assets/5455606/8761134/bcb07c58-2d40-11e5-94e8-26ed33681af9.png)

All the other loaders are working perfectly (apart from those relating to the MeshFaceMaterial re-implementation).

**Comment by Cy-Bo-Rg** [comment]
Any clue?

**Comment by MasterJames** [comment]
Can you post a fiddle or something to reproduce this?

**Comment by Cy-Bo-Rg** [comment]
a fiddle? for three.js demos ?

**Comment by MasterJames** [comment]
I was thinking it's the model and the import process that needs looking at to even begin to understand your particular problem. The fact is you say it's an unsupported chipset so that seems like it's not reproducible either.
You're going to have to discover via the process of elimination (editing the model file being imported) to isolate when there is a problem. Maybe there is a workflow through a 3d party tool to change the model from quads or what have you. Good Luck.

**Comment by mrdoob** [comment]
What @MasterJames said. We can't do much as we can't reproduce the issue (at least I can't install stock browser). So if you can try to reproduce when it happens that'll be super helpful.

**Comment by Cy-Bo-Rg** [comment]
I'll try my best, thanx for the suggestions.
