### ISSUE TITLE
Floating Point Error for Object3d.RotateOnAxis()

### ISSUE THREAD

**Issue by dexwiz** [mrdoob/three.js#6879]
RotateOnAxis appears to accumulate floating point errors causing the object's size to "pulse" overtime, where each pulse is greater that than last. In the below example Shape1's size changes over time, while Shape2 remains constant.

```javascript
var renderer = new THREE.WebGLRenderer()
renderer.setSize(1200, 800)
renderer.setClearColor( 0xdddddd, 1);

var scene = new THREE.Scene();

var camera = new THREE.PerspectiveCamera(45, 1200/800, .1, 1000)
camera.position.set(0,0,35)
camera.lookAt(scene.position)

renderer.render( scene, camera );

var light = new THREE.PointLight( 0xFFFF00 );
light.position.set( 10, 0, 10 );
scene.add( light );


var geometry  = new THREE.OctahedronGeometry(10, 0)
geometry = new THREE.BoxGeometry(1,1,1)

var material = new THREE.MeshLambertMaterial( { color: 0xFF0000 } );
var shape1 = new THREE.Mesh(geometry, material)
shape1.position.x = -5
scene.add(shape1)

var shape2 = new THREE.Mesh(geometry, material)
shape2.position.x = 5
shape2.matrixAutoUpdate = false
scene.add(shape2)


var rotationMatrix = new THREE.Matrix4();
var rotationAxis = new THREE.Vector3(1,1,1);
rotationMatrix.makeRotationAxis(rotationAxis.normalize(), Math.PI/120)

var render = function () {
	shape1.rotateOnAxis(new THREE.Vector3(1,1,1), Math.PI/120)

	shape2.matrix.multiply(rotationMatrix)

	requestAnimationFrame( render );
	renderer.render(scene, camera);
};

$(function() {
	$('body').append(renderer.domElement)
	render();
})
```

**Comment by WestLangley** [comment]
Direction vectors in three.js are assumed to be of unit length. You need to modify your code:

    var rotationAxis = new THREE.Vector3( 1, 1, 1 ).normalize();

Also, avoid `new` in tight loops:

    shape1.rotateOnAxis( rotationAxis, Math.PI / 120 );

If you can demonstrate a three.js bug, can you provide a live test case? Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by dexwiz** [comment]
Looks like the normalize() did it. Side note. I was directly rotating shape1 using:
```javascript
shape1.rotateOnAxis(new THREE.Vector3(1,1,1), Math.PI/120)
```

Adding a normalize fixed the issue:
```javascript
shape1.rotateOnAxis(new THREE.Vector3(1,1,1).normalize(), Math.PI/120)
```

Shape2 use the rotationMatrix and rotationAxis. When setting up the matrix, I normalized the axis in the function parameters. That is why it worked:

```javascript
var rotationAxis = new THREE.Vector3(1,1,1);
rotationMatrix.makeRotationAxis(rotationAxis.normalize(), Math.PI/120)
```

Thank you for your help. This can be closed.
