### ISSUE TITLE
A replacement for cascading shadow maps, raytraced shaders

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#6886]
A cool blog post from Imagination Technologies, the results are really nice:

http://blog.imgtec.com/multimedia/implementing-fast-ray-traced-soft-shadows-in-a-game-engine

Would be great to have implemented in ThreeJS.  Cascading shadow maps are just problematic.

**Comment by mrdoob** [comment]
I haven't had a proper read, but I assume you need to get the oultine per object per frame to do this?

**Comment by bhouston** [comment]
It is interesting, but I probably should have held off on suggesting it for ThreeJS.  I misread the article -- I thought it was possible to do the ray casting in standard glsl, but it appears that it uses a dedicated Real-Time Ray Tracing silicon on this new PowerVR Wizard GPU.

I heard that likely similar results (and more) can be achieved via NVIDIA's Voxel Cone technology --- https://www.youtube.com/watch?v=Z1o_CCHhBTQ

Sorry for the noise.

**Comment by tschw** [comment]
The article targets custom raytracing GPUs.

To do realtime raytracing on an ordinary GPU we'd need some kind of acelleration structure to cut the complexity to O(log N), in other words, we can't test every triangle in the scene for every pixel and thus will have to arrange them into a spatial hierarchy. The GLSL version of WebGL is rather limited when it comes to the traversal of such tree structures. There are stackless techniques (basically using parent pointers and an FSM) but those impose quite a bit of overhead.

The acceleration structure needs to be updated when objects move. Optix (a raytracing SDK from NVIDIA) uses a layered approach, so the objects (that may move around) can use a different strategy than the triangles inside (that do not move in respect to each other).

A first prototype may build the hierarchy in JavaScript and do the traversal in GLSL. However, I guess it will be quite a journey to come up with something really usable in practice. WebCL (OpenCL for the web) may be an option, but I have never used it.

It would be a very interesting project - not at all limited to shadows but allow for a GPU-based realtime raytracing renderer!

**Comment by bhouston** [comment]
> WebCL (OpenCL for the web) may be an option, but I have never used it.

WebCL is dead I understand.  In part because WebGL 2.0 will have compute shaders support from OpenGL ES 3.1 included.

**Comment by tschw** [comment]
> WebCL is dead I understand. In part because WebGL 2.0 will have compute shaders support from OpenGL ES 3.1 > included.

Ah, thanks!

With an updated GLSL version stacks may just be implementable in the fragment shader for the raytracer. Compute shaders will be useful to move the hierarchy build / refitting to the GPU.

**Comment by Usnul** [comment]
link: #4434
