### ISSUE TITLE
SVGRenderer error in determining hidden surfaces

### ISSUE THREAD

**Issue by nitaku** [mrdoob/three.js#6887]
I'm trying to render a collada file of a complex building in SVG, in order to build an interactive isometric map working on most browsers.

I ran into what it seems to be an issue with hidden surface determination. If I have an elongated box in front of another box, I get the following error, in which a triangle from the box behind is not correctly occluded by the ones forming the one in front:
![image](https://cloud.githubusercontent.com/assets/1604569/8810030/72532c6a-2fec-11e5-94ed-943771b3dd34.png)

If I use a WebGLRenderer instead, I obtain the correct result. Is this a known limitation of SVGRenderer? If so, do you have any suggestions on how to help fix or work around this?

Thanks a lot in advance!

**Comment by dubejf** [comment]
I'm not familiar with the `SVGRenderer`, but the `CanvasRenderer` produces similar artifacts. That's because Z-ordering is done at the face level, not per pixel. The solution is to subdivide the elongated face.

Past discussion http://stackoverflow.com/questions/29020613/three-js-issue-to-render-objects-using-canvasrenderer

**Comment by nitaku** [comment]
Thanks @dubejf ! I also noticed the same artifacts in canvas.
Any advice on how to subdivide elongated faces if I have a complex object like the one I import from collada? The link you provided covers the simple case of boxes (as in the picture I posted), but I have to make it work for a building.

**Comment by dubejf** [comment]
A quick search lead me to http://stackoverflow.com/questions/27422549/three-js-split-faces-with-long-edges-into-two-faces, which seems to do what you want. You can also preprocess your models in a 3rd party tool of your choice.

**Comment by nitaku** [comment]
Ok, thank you for your help with my noob issue :) I will use Stackoverflow next time, I posted it as an issue because it seemed to me that there was a problem with the renderer.
