### ISSUE TITLE
Confusing practices in Quaternion implementation

### ISSUE THREAD

**Issue by lucasdealmeidasm** [mrdoob/three.js#6891]
In the current implementation of `THREE.Quaternion`, there are two different `.slerp` methods.
See http://threejs.org/docs/#Reference/Math/Quaternion.slerp

The former, `.slerp ( qa, qb, qm, t )` occurs when referencing the global `THREE.Quaternion` directly.
The latter, `.slerp (qb, t)` occurs in instances of `THREE.Quaternion`.

The latter is defined in (src/math/Quaternion.js#L400)
As it is in the prototype, instances of `THREE.Quaternion` will have it.
The former is defined in (src/math/Quaternion.js#L518)
As it is a write to the global `THREE.Quaternion`, only that will have it.

From the web console:
```
>THREE.Quaternion.slerp
function THREE.Quaternion.slerp(a, b, c, d)
>var q = new THREE.Quaternion();
T…E.Quaternion {_x: 0, _y: 0, _z: 0, _w: 1}
>q.slerp
function THREE.Quaternion.slerp(a, b)
>q.slerp==THREE.Quaternion.slerp
false
```

While not wrong, this is quite confusing, as the documentation does not tell which one is where.
Therefore, one must look in the code to figure this out, and even then it remains confusing, specially as one of the functions is in the very end of the file.
Further, the current formatting of the documentation is presented as if all methods present occur in instances.
Further, it is easy to, reading the docs, misinterpret it as stating that there is only one function and it will check the type of the arguments to figure if you are passing `qa,qb,qm,t` or `qb,t`.
Further, I believe this is not that great of a code practice at all, to have `Foo.bar != Foo.prototype.bar`.
I believe easiest solution is to rename one of those, to reflect behavior.

**Comment by WestLangley** [comment]
We can't remove one of the methods. Maybe the documentation could be improved, however.

/ping @TatumCreative Would you be willing to have a look?

Here are a few use cases that may clarify the difference between the static and prototypical methods.

	var startQuaternion = new THREE.Quaternion().set( 0, 0, 0, 1 ).normalize();
	var endQuaternion = new THREE.Quaternion().set( 1, 1, 1, 1 ).normalize();
	var t = 0;

Add to render loop:

	// ease-in toward target
	mesh.quaternion.slerp( endQuaternion, 0.01 );

Alternatively, add this:

	// constant angular momentum
	t = ( t + 0.01 ) % 1;
	THREE.Quaternion.slerp( startQuaternion, endQuaternion, mesh.quaternion, t );

**Comment by TatumCreative** [comment]
Yup, I'll take a look this weekend.

**Comment by lucasdealmeidasm** [comment]
Well I did understand their difference in behavior, but the documentation is lacking.

Though my suggestion wasn't removing either of the methods. It is clear both are useful. My suggestion was to call one of them by another name.

**Comment by WestLangley** [comment]
The use cases were for the benefit of those improving the docs. : - )

The name of the method is `slerp`. The name of the static function is `THREE.Quaternion.slerp`.

Will you explain again why that is a problem for you?

**Comment by lucasdealmeidasm** [comment]
It is not a problem to me. I just think it would be more clear if for example the one in instances would be `slerpMe`. As long as the documentation is fixed it is fine.

**Comment by TatumCreative** [comment]
I ended up having some time to look at it tonight. Hopefully that clarifies it a bit. Someone had added non-static methods below the static <h2> and I think that added to the confusion.

**Comment by mrdoob** [comment]
Maybe the static one could be renamed to `slerpQuaternions`?

**Comment by WestLangley** [comment]
> Maybe the static one could be renamed to slerpQuaternions?

Only one quaternion is being "slerped" -- at least the way I think of it. I think the names are fine.

Thank you to everyone.
