### ISSUE TITLE
Wrong shadow projection in webgl_animation_cloth.html on a Mac

### ISSUE THREAD

**Issue by Cy-Bo-Rg** [mrdoob/three.js#6892]
I've seen the same error happening on a Mali400 on Android.
It's probably a problem with this particular GPU, but I can't be sure.
Looks like a wrong shader projection.

Chrome on the left, Safari on the right.
![schermata 2015-07-22 alle 15 12 33](https://cloud.githubusercontent.com/assets/5455606/8826513/4be7dcd8-3087-11e5-8ee6-2bcf7009f620.png)

Tested with rev. 71 master
Chrome Version 44.0.2403.89 (64-bit)
Safari Version 8.0.5 (10600.5.17)
OS X Yosemite
2,93 GHz Intel Core i7
ATI Radeon HD 5750 1024 MB

**Comment by mrdoob** [comment]
Do you get the same with the `dev` branch?

**Comment by Cy-Bo-Rg** [comment]
I'm going to try.

**Comment by makc** [comment]
I'm on mac, but I never use safari. It is buggy beyond the limits when it comes to webgl.
![screen shot 2015-07-25 at 19 32 49](https://cloud.githubusercontent.com/assets/242577/8890527/235bd86c-3304-11e5-907b-87212f089f20.png)
I get this + rainbow cursor in that demo with safari.

**Comment by Cy-Bo-Rg** [comment]
@mrdoob I've testedd it right now. It's perfect with rev. 72 dev.
Thanx.

@makc  It's not buggy. You should activate the developer menu from "edit - Preferences - Show developer menu" and "disable file restrictions".

**Comment by makc** [comment]
>  "Disable Local File Restrictions".
the screenshot was from threejs.org (

**Comment by Cy-Bo-Rg** [comment]
@makc   ,  Ouch ! :P
That's strange though , it was fine on my Mac.
Have you updated everything?

**Comment by makc** [comment]
joe cartoon made me download and learn flash 5

**Comment by Cy-Bo-Rg** [comment]
@makc same over here back in the days.. :P
