### ISSUE TITLE
Collada Loader in Three.js does not load a DAE scene with a few DAEs linked

### ISSUE THREAD

**Issue by sergiota** [mrdoob/three.js#6894]
I have a Collada scene in DAE format, which in fact contains links to another DAE-files. It looks like this inside of this "parent" file:

![part dae](https://cloud.githubusercontent.com/assets/13456445/8834100/ffd943fc-30ba-11e5-9371-b804c62aa180.png)

This scene can be opened with desktop software without any problems. But when I try to load this Collada with Three.js Collada Loader it displays nothing. The same code works nice for ordinary Collada files, which do not have links to another DAE-files.

Also tried to open such DAE-scenes in on-line three.js editor.
1. Opened child DAE-files separately in three.js editor - they opened normally 2. Opened the parent object and left realtive links in parent DAE to the child DAEs - did not work 3. Saved child DAEs to a web-server and changed the links to absolute ones in the parent DAE - did not work The editor opens the scene and shows two "DesignTransform" childs with parent Scene. I can see the placeholders with transform arrows for each child, but there is nothing in them .

**Comment by dubejf** [comment]
External references don't seem to be supported by the loader. Lookup is only within the document.

https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/ColladaLoader.js#L2323-L2324
https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/ColladaLoader.js#L1353-L1357

You'll need to combine your models, use a different format, or enhance the loader.
