### ISSUE TITLE
Morph Target dead code in Mesh

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#6902]
These are not used by any code in the ThreeJS repository (/src or /examples):

- Mesh.morphTargetBase
- Mesh.morphTargetDictionary
- Mesh.morphTargetForcedOrder
- Mesh.updateMorphTargets()
- Mesh.getMorphTargetIndexByName()

https://github.com/mrdoob/three.js/blob/master/src/objects/Mesh.js#L28

I can submit a PR that removes them.

Maybe have to lead the initialization of the morphTargetInfluences array to zero though in the constructor or Mesh though.

**Comment by mrdoob** [comment]
Sounds good!

**Comment by mrdoob** [comment]
Done! Seems like `SEA3DLoader` and `MMDLoader` now rely on `morphTargetDictionary` though.
