### ISSUE TITLE
MeshPhongMaterial doesn't render "metal" materials properly

### ISSUE THREAD

**Issue by chandlerprall** [mrdoob/three.js#6910]
[example of bug](http://www.chandlerprall.com/metalbug/) - materials on spheres is identical except for `metal: true` on the right

Looks like [a merge on March 9th](https://github.com/mrdoob/three.js/commit/e83bf8a30d48291ad3d978ef533da632c5f9701e#diff-9d1b6b314b32f4de992810d205b5be65L431) rewrote how `MeshPhongMaterial` handled metal materials.

**Comment by WestLangley** [comment]
It is not a bug. It is a feature. : - )

The metal model needs work. Improvements are in the pipeline.

**Comment by WestLangley** [comment]
You need to have an environment map for metals so they have something to reflect. Add one.

Then you can do something like the following:

	var material1 = new THREE.MeshPhongMaterial( {

		color: 0xffb54a, // ( use 0xffffff if you do not want gold )
		specular: 0x111111, // non-metals do not have high specularity
		map: THREE.ImageUtils.loadTexture( '173_diffuse.png' ),
		specularMap: THREE.ImageUtils.loadTexture( '173_specular.png' ),
		normalMap: THREE.ImageUtils.loadTexture( '173_normal.png' ),
		envMap: envMap,
		combine: THREE.AddOperation,
		reflectivity: 0.1,
		metal: false

	} );

	var material2 = new THREE.MeshPhongMaterial( {

		color: 0x000000, // metals have (almost) no diffuse component
		specular: 0xffb54a, // ( use 0xffffff if you do not want gold )
		map: null, // there is no diffuse component, so there in no need for a diffuse map
		specularMap: THREE.ImageUtils.loadTexture( '173_diffuse.png' ), // for metals, use the diffuse map here
		normalMap: THREE.ImageUtils.loadTexture( '173_normal.png' ),
		envMap: envMap,
		combine: THREE.AddOperation,
		reflectivity: 0.5,
		metal: true

	} );

So the answer to your question is you can do a reasonable job of getting the look you want if you understand how the parameters need to be modified to accommodate metals. We are going to make this easier for users.

**Comment by makc** [comment]
> metals have (almost) no diffuse component

what about rusty metals?

**Comment by WestLangley** [comment]
Oxidized metals have a diffuse component.

**Comment by chandlerprall** [comment]
Thanks for the responses, @WestLangley
