### ISSUE TITLE
Blender export contains orphaned images

### ISSUE THREAD

**Issue by flow-c** [mrdoob/three.js#6913]
FILES:
------
[This folder](https://myshare.box.com/s/ukq686gzsp1wq8dl95m7vv5c4ltf08qb) contains two blender projects, their respective THREE.js JSON exports, two JPEG images, and this document:

* rubix.blend	--> rubix.json (base model)
* rubix1.blend	--> rubix1_*.json (same model with new texture)
* Rubiks_cube_by_keqs.jpg (texture from commons.wikimedia.org, courtesy Lars Karlsson)
* Rubiks_cube_by_keqs1.jpg (same texture but converted to gray scale)
* README.txt

DATA DESCRIPTION:
-----------------
* The base model rubix.blend uses Rubiks_cube_by_keqs.jpg as single texture. The exported rubix.json looks alright.
* In rubix1.blend, the texture is replaced with Rubiks_cube_by_keqs1.jpg. Unless Blender is quit and reopened first, the export fails in that rubix1_nok.json has a spurious entry with type "Geometry" in the "images" array.

STEPS TO REPRODUCE THE ISSUE:
-----------------------------
1) Start up Blender
2) Open rubix.blend
3) Export it with the Three.js exporter --> rubix.json
4) Open rubix1.blend
5) Export it with the Three.js exporter --> rubix1_nok.json
6) Quit and reopen Blender
7) Open rubix1.blend
8) Export it with the Three.js exporter --> rubix1_ok.json

ENABLED EXPORT SETTINGS:
------------------------
* GEOMETRY:
	* Vertices
	* Faces
	* Normals
	* UVs
* SCENE:
	* Scene
	* Materials
* SETTINGS:
	* Textures
	* Copy Textures
* Enable Precision
* Indent JSON

USED VERSIONS: 
--------------

* Blender v2.74
* THREE.js exporter 4.3 (r71)

**Comment by repsac** [comment]
Files are downloaded

**Comment by repsac** [comment]
Try out this branch and see if it works for you. The extra texture and `Geometry` type seem to be gone now.
https://github.com/repsac/three.js/tree/6913

**Comment by flow-c** [comment]
Awesome! That fixed it.
Thanks very much!
