### ISSUE TITLE
Orbit camera redirection

### ISSUE THREAD

**Issue by mingcen** [mrdoob/three.js#6917]
Hi all,

I have a problem about camera redirection, unsovled for a long time. Briefly, I have a camera whose up vector is always (0,1,0). I want to move camera's position while keeping a certain 3D point appearing in the same position of the screen. 

For example, let P be the camera's position, T be the camera's lookat, and F be the point appearing in (x,y) of the screen. Now P is changed to P' (camera's new position); in order to make F still appear in (x,y) of the screen, T must be changed. 

Question is, what is the new value of T?

I believe the problem needs a lot of math. Tell me if you have any idea. Thanks greatly!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
