### ISSUE TITLE
Shadows on PlaneGeometry broken in r71

### ISSUE THREAD

**Issue by juzzlin** [mrdoob/three.js#6923]
My shadows stopped working on the other triangle of a textured PlaneGeometry in r71. Worked before at least in r67. I didn't change anything in my code.

**Comment by juzzlin** [comment]
So it's not a bug when shadows are working only partly?

**Comment by AlexeyGapon** [comment]
It looks like you are using spot or directional light. Check the size of the area of the light. You might need to increase the size of it.
