### ISSUE TITLE
Objects Loaders do not work in the local "examples" folder.

### ISSUE THREAD

**Issue by eriadel** [mrdoob/three.js#6925]
That means all tests regarding import of the obj files (OBJ loaders) do not work locally and I'm having a problem with starting to import the objs + mtl.

var loader = new THREE.OBJMTLLoader();
loader.load("/Content/3DObjects/Mech.obj", "/Content/3DObjects/Mech.mtl", onLoad, onProgress, onError);

mrdoob-three.js-r71-5-gd6384d2

Getting completed callback while object is not visible at all...

Reportend on Win7 - all browsers. (IE, Firefox, Chrome, Opera, etc.)

**Comment by dubejf** [comment]
I don't think there is a problem.

I'm able to launch the `webgl_loader_obj_mtl` example from the filesystem on Windows if I start Chrome with `--allow-file-access-from-files`.

You can also run a local http server as describe in the ![wiki](https://github.com/mrdoob/three.js/wiki/How-to-run-things-locally).
