### ISSUE TITLE
DirectGeometry.fromGeometry does not create indices

### ISSUE THREAD

**Issue by brianchirls** [mrdoob/three.js#6926]
`BufferGeometry.fromDirectGeometry` will import indices from `DirectGeometry` if they exist, and `BufferGeometry.fromGeometry` passes through `DirectGeometry.fromGeometry` first (as of r72 dev). But the indices get lost in the middle because `DirectGeometry.fromGeometry` does not create indices from faces in `THREE.Geometry`.

In #6377 @mrdoob [asked](https://github.com/mrdoob/three.js/pull/6377#issuecomment-91962875):
> Any reason you want indexed buffers out of `THREE.Geometry`? If it's for performance reasons I would, instead, focus on converting the primitives and loaders to `BufferGeometry` (or `DynamicGeometry`).

`THREE.Geometry` is easier to manipulate, so sometimes it's useful to start there and then convert it to `BufferGeometry` for rendering.

Related to #6191

**Comment by mrdoob** [comment]
Yes. And, unfortunately, I think it will stay like this...

I'm thinking of adding `indices` to `DirectGeometry` (which maps directly to `BufferGeometry`) and port `Geometry` generators to `DirectGeometry` instead. `DirectGeometry` is kind of what `Geometry` should have been if I had known better...

**Comment by brianchirls** [comment]
Does that mean that `DirectGeometry` will be as easy to manipulate as `Geometry`? If that's the case, then that would be a sufficient solution.

Do you mean you're thinking of deprecating `Geometry`?

Forgive me for not fully understanding the purpose of `DirectGeometry`. I'm trying to piece together what I can from commit messages and issue comments.

Thanks!

**Comment by mrdoob** [comment]
Yeah... I still don't know what the right thing to do is. That's why `DirectGeometry` isn't documented yet (I'm just experimenting).

`DirectGeometry` was a internal geometry structure that `WebGLRenderer` used to create. In `r72` I "moved it out" of the renderer.

What's your use case? The more use cases I see/hear, the better I'll know what the right approach should be.

**Comment by brianchirls** [comment]
Ah, okay. Great...

One example use case is similar to [vizicities](https://github.com/vizicities/vizicities/tree/0.2.0). I want to generate a geometry representing a block of buildings. I will receive building data as a polygon representing the outline, a height and minHeight* for each building. I create a `THREE.Shape` based on the polygon and extrude it. Then, I remove any faces that are facing down at height=0 (i.e. on the ground). I may also do a pass to quantize vertices and remove duplicates. Finally, multiple buildings get merged into a single geometry, and the result is converted to a `BufferGeometry`.

Incidentally, all this heavy work is done in a Web Worker, and the typed array data from the buffer attributes are transferred back to the main thread, where they are placed into a new `BufferGeometry` and rendered. It makes a huge difference in keeping the frame rate up while the geometry is being created.

(*minHeight is for parts of buildings that are floating, so buildings can be composed of multiple pieces. For things like bridges.)

**Comment by mrdoob** [comment]
Ah, I see I see...

**Comment by benaadams** [comment]
> Incidentally, all this heavy work is done in a Web Worker, and the typed array data from the buffer attributes are transferred back to the main thread

Do you not just create all the required buffers in the worker and use transferable objects to get them back to main thread? If so aren't they already in the BufferGeomerty format [indexes+positions+etc] and you can just load them directly to GPU?

**Comment by brianchirls** [comment]
@benaadams Yes, exactly. But I use three.js inside the worker to build the geometry.

Here's the code that builds the geometry model inside the worker:
https://github.com/vizicities/vizicities/blob/0.2.0/src/Blueprint/BlueprintOutputBuildingTiles.js#L212

Here's where we convert it into a `BufferGeometry` and transfer the buffers back to the main thread:
https://github.com/vizicities/vizicities/blob/0.2.0/src/Blueprint/BlueprintOutputBuildingTiles.js#L345

And here's the callback where the main thread receives the buffers and puts them in a new `BufferGeometry` to go into the GPU:
https://github.com/vizicities/vizicities/blob/0.2.0/src/Blueprint/BlueprintOutputBuildingTiles.js#L186

**Comment by brianchirls** [comment]
Any particular reason this was closed?

**Comment by mrdoob** [comment]
I thought the question was already answered...?

**Comment by brianchirls** [comment]
I thought this was still under discussion since you'd asked for a use case.

So no, then? Or is there another issue or commit somewhere that addresses this?  Thanks.

**Comment by mrdoob** [comment]
Well... The issue is that the data structure of `Geometry` can't be directly converted to `BufferGeometry` with indices. Mainly because when using indices you can only have 1 `normal`, `color` and `uv` per vertex. `Geometry` can have many per vertex (because the normals, colors and uvs are stored in the face itself). The only way to end up with a sane conversion code (unlike what we had before) is to explode into non-indexed geometry.

In the future we may want to output `DirectGeometry` from `Shape`. Or we could just output `BufferGeometry` and have a `toDirectGeometry()` method if someone needs a easier way to handle vertices.

**Comment by WestLangley** [comment]
> DirectGeometry.fromGeometry does not create indices

What is it that you ultimately want? An indexed `BufferGeometry`? And why?

**Comment by mrdoob** [comment]
I spoke with my brother about this yesteday. He said that, nowadays, drivers convert indexed geometries to triangle soups when they send it to the GPU anyway. 

So, if your concern was a performance one, I don't think you should be concerned anymore.

**Comment by brianchirls** [comment]
Fascinating. Is there an article about it or something? Does this apply on mobile too?

**Comment by nraynaud** [comment]
there might be an interesting perf difference between re-hydrating the triangle soup in JS + keeping it in memory vs doing it in C in the driver and forgetting it afterwards tho.

**Comment by sohale** [comment]
Another use case for this question. My question below is related to this topic:
http://stackoverflow.com/questions/37927031/how-to-update-the-topology-of-a-geometry-efficiently-in-threejs
