### ISSUE TITLE
I found a bug.  review my solution it.

### ISSUE THREAD

**Issue by ZifRoot** [mrdoob/three.js#6927]
when added into the vertices PointCloud new vertices,
adding occurs,
because: in function setParticleBuffers
When copying in vertexArray of vertices, 
not all vertices are copied,
because:
vertexArray declared as Float32Array and Float32Array does not resize 
so I suggest:
in function setParticleBuffers when length of vertices not equal number of vertices in PointCloud
re-create all the necessary Float32Array
, and to make such changes

function setParticleBuffers(geometry, hint, object) {
"+" if (geometry.__webglParticleCount !== geometry.vertices.length) 
"+"     initParticleBuffers(geometry, object);
        var v, c, vertex, offset, color,

**Comment by WestLangley** [comment]
See the Wiki article [How to Update Things with WebGLRenderer](https://github.com/mrdoob/three.js/wiki/Updates).

If you need to add vertices to your point cloud, consider using `BufferGeometry`, allocate sufficiently-sized buffers,  and use `drawcalls` to control the number of particles rendered.

**Comment by mrdoob** [comment]
> If you need to add vertices to your point cloud, consider using `BufferGeometry`, allocate sufficiently-sized buffers,  and use `drawcalls` to control the number of particles rendered.

That's probably a little bit too advanced. Now that this code is a bit more under control we can probably add the check @ZifRoot suggested. I would, however, `console.warn` and advise to create a geometry big enough to start with.

**Comment by WestLangley** [comment]
> That's probably a little bit too advanced. 

Using `BufferGeometry` is too advanced?

> and advise to create a geometry big enough to start with.

And how would you prevent the rendering of the unused portion?

**Comment by ZifRoot** [comment]
Use BufferGeometry for me too hard and amusing. And still need to recreate array

**Comment by mrdoob** [comment]
>> That's probably a little bit too advanced. 

> Using `BufferGeometry` is too advanced?

Yeah...

> > and advise to create a geometry big enough to start with.

> And how would you prevent the rendering of the unused portion?

We should add a `count` property somewhere.

**Comment by WestLangley** [comment]
Here is a related [stackoverflow post](http://stackoverflow.com/a/31411794) using `BufferGeometry` and `drawcalls`. The core of the associated [fiddle](http://jsfiddle.net/s9fsds19/) is a few lines of code.

If `BufferGeometry` is too advanced, then perhaps we are heading down the wrong path.

**Comment by mrdoob** [comment]
> If `BufferGeometry` is too advanced, then perhaps we are heading down the wrong path.

I don't think so. We need a geometry structure that is ready to be uploaded. That's what `BufferGeometry` is. We can try make `BufferGeometry` easier to use for people starting, but I suspect a structure like `Geometry` (or `DirectGeometry`) is simpler for them.

**Comment by makc** [comment]
while on subject on buffer geometry being too advanced, let me say the major (and the only) inconvenience I hadso far - zero help from the engine to create faces. the core problem being that vertices must be duplicated when at least one attribute differs. I tried many times to come up with my own code to figure out what vertices could be reused (in indexed geometry), but in the end none of it turned out to be performant and stable, so I had to just duplicate everything, massively bloating my buffers. having any kind of reliable/well-tested method like "addFace" or whatever would, imho, quite helpful.

**Comment by dubejf** [comment]
I started working on a `GeometryBuilder` class. My main goal was to simplify redundant work that needs to be done in the importers, but it could also be helpful to create programmatic geometries.
```
var builder = new GeometryBuilder();
builder.addVertex( x, y, z ); ...
builder.addFace(...); ...
builder.addFaceNormal(...); ...
builder.useIndexed( true );
builder.useBuffer( true );
var geometry = builder.create();
```
I don't know if that's something that would be welcome in the core library.

**Comment by makc** [comment]
> builder.addVertex( x, y, z );

keep in mind custom vertex attributes, please ) also, skin index/weights - they are basically a special case of attribute with buffer geometry.
