### ISSUE TITLE
Making an invalid RawShaderMaterial on a BufferGeometry crashes the render because attributes are erroneously updated

### ISSUE THREAD

**Issue by DelvarWorld** [mrdoob/three.js#6928]
**JSFiddle**: https://jsfiddle.net/VsWb9/3977/ Open the console, click the top button (expected warnings), then click the bottom button (unexpected crash).

**What's going on:**

When you update a `RawShaderMaterial` with an invalid source (in this case, an empty fragment shader), and set `.needsUpdate`, if it's rendered on a `BufferGeometry` it will crash the renderer on [this line](https://github.com/mrdoob/three.js/blob/5c7e0df9b100ba40cdcaaf530196290e16c34858/src/renderers/WebGLRenderer.js#L2441):

    if ( material.defaultAttributeValues[ key ].length === 2 ) {

This **does not occur** for a non-buffer-geometry mesh.

Upon inspection of the generated shader, as far as I can tell, when a `RawShaderMaterial` is created, it [adds a bunch of attributes](https://github.com/mrdoob/three.js/blob/5c7e0df9b100ba40cdcaaf530196290e16c34858/src/renderers/webgl/WebGLProgram.js#L411) like `skinIndex` that probably shouldn't be there, but this isn't the actual problem.

In a normal `RawShaderMaterial`, if you inspect the object in memory, and look at `material.program.attributes.skinIndex` you will see it is set to **`-1`**. That means when the scene is rendered, it will correctly bypass [this check](https://github.com/mrdoob/three.js/blob/5c7e0df9b100ba40cdcaaf530196290e16c34858/src/renderers/WebGLRenderer.js#L2425):

    if ( programAttribute >= 0 ) {

Where `programAttribute` is `attributes.skinIndex` for example. I cannot find where in the source of Three.js the value is set to `-1`.

**For some reason** when updating the material on a `PlaneBufferGeometry`, that attribute gets set to **`0`**.
![screen shot 2015-07-30 at 1 11 26 pm](https://cloud.githubusercontent.com/assets/79215/8993855/846640dc-36bc-11e5-9a1a-087de0f5ba51.png)
So now when the above loop executes, it bypasses the 0 check, and starts looking in `material.defaultAttributeValues` for each of the keys (like `skinIndex`). However, those keys aren't set, and the value of `material.defaultAttributeValues` is only `{ color: Array[3], uv: Array[2], uv2: Array[2] }`, so the `.length` check is on `undefined` and errors.

Which one of these is the source of the problem? Is it something specific to `BufferGeometry` attributes? Is it specific to `RawShaderMaterial` updating? Is it that `RawShaderMaterial` shouldn't have attributes like `skinIndex` and `morphNormal0` on it? Is it that something unrelated is erroneously setting attributes to `0` instead of `-1`? Is this even a bug? I have no idea, so I can't yet submit a PR, but it crashes the renderer. I hope the above steps are clear enough to make the problem obvious.

**Comment by benaadams** [comment]
Might be fixed in r72?

**Comment by WestLangley** [comment]
Your fiddle has console errors prior to clicking buttons.

**Comment by DelvarWorld** [comment]
@WestLangley whoops, updated the fiddle, it was a minor error. I had double checked the fiddle was working before posting, but JSFiddle's wonky save structure + spotty wifi = unpredictable code saved.

**Comment by mrdoob** [comment]
`r72dev` https://jsfiddle.net/VsWb9/3978/

**Comment by DelvarWorld** [comment]
As far as I can tell this fixes the bug within my parameters! :)
