### ISSUE TITLE
THREE.WebGLShader: Shader couldn't compile - Chrome Version 44.0.2403.125

### ISSUE THREAD

**Issue by vilhelmjosander** [mrdoob/three.js#6929]
Hi,

This week I started getting the following error when using Three.js:
 three.min.js:592 THREE.WebGLShader: Shader couldn't compile.

I am using revision 68 and keep getting this error on Chrome Version 44.0.2403.125 (64-bit). I am not getting these errors in Safari or Firefox.

This is on a Mac OS X Yosemite 10.10.4.

Just wanted to know if this is something that other users are experiencing or some thing that has been fixed in the latest revision?

**Comment by mrdoob** [comment]
Could you share the code you're having the error with?

**Comment by vilhelmjosander** [comment]
I am using the https://github.com/spite/Wagner library. Seems to be something going on when using their composer.

`var renderer = new THREE.WebGLRenderer({preserveDrawingBuffer:this.props.preserveDrawingBuffer, canvas:canvas});`
`composer: 	new WAGNER.Composer( renderer, { useRGBA: false }),`

Then it breaks when passing the fxaa to the composer:

`fxaa: 	new WAGNER.FXAAPass()`

`composer.reset();`
`composer.render( scene, camera );`
`composer.pass( fxaa ); // breaks here`
`composer.toScreen();`

If I just use the renderer it works fine:

`renderer.render( scene, camera );`

Don't know if this helps, let me know!

**Comment by WestLangley** [comment]
If you need help, please use stackoverflow. We can't help you with Wagner.

I would suggest that you avoid old versions of three.js, use the non-minified version of three.js for development,  and at a minimum, make sure the version you use is compatible with Wagner.

If you choose to use stackoverflow, provide sufficient information for your issue to be reproduced. It is impossible to help you, otherwise.

**Comment by spite** [comment]
I would need some code to review. The only thing I can think it seems off is: have you set the size of the composer?

```composer.setSize( window.innerWidth, window.innerHeight );```

If still doesn't work, open an issue in the repo and I'll take a look.
