### ISSUE TITLE
RequireJs native support

### ISSUE THREAD

**Issue by missingdays** [mrdoob/three.js#6930]
Libraries like C3 or Riot have native RequireJs support, so you don't have to use shim.
It's an easy hack, yet it will be very helpful if you want to include library as AMD module but can't use shim for some reason (in Node, for example).

**Comment by bhouston** [comment]
I use ThreeJS in node all the time using this build script:

https://github.com/mrdoob/three.js/tree/master/utils/npm

Using this header (required for fonts to work properly):

https://github.com/mrdoob/three.js/blob/master/utils/npm/header.js

And this footer (which supports a few different module systems):

https://github.com/mrdoob/three.js/tree/master/utils/npm

I notice your footer/header in #6931 is slightly different:

https://github.com/mrdoob/three.js/pull/6931/files

can you explain the differences to me?

**Comment by Usnul** [comment]
One of the goals of the library is small size, another is simplicity of use. RequireJS would be considered advanced enough by me that anyone who sees that as an issue can fix it. Adding support for node, for requireJS and others would help integrating library, but would ultimately be a bloat in some environments.

**Comment by missingdays** [comment]
@usnul it takes like 5 lines of code to achieve it. This wouldn't suddenly make library big.
Libraries like c3, d3, riot and many more have this, and they don't feel heavy just because of this.

**Comment by Usnul** [comment]
I mean no disrespect but that's an argument from anecdotal evidence. My understanding is that you wish for this to be included in the library; from my perspective - this is a relatively small thing which, nevertheless, goes somewhat contrary to library's philosophy the way I understand it. My personal opinion is indifferent on the matter. Good day.

**Comment by antont** [comment]
just for the record - those 5 lines of code are no anecdotal evidence but simple, clear enough, well working solution that does no harm to anyone .. and merged in too, so everyone should be happy :)
