### ISSUE TITLE
BufferGeometryLoader crashes on typed array creation

### ISSUE THREAD

**Issue by Michbeckable** [mrdoob/three.js#6932]
I am using ThreeJS r71 and try to load a scene from a JSON file using the `ObjectLoader`. The scene was exported by the ThreeJS editor and contains some `BufferGeometry` like this:

	"geometries": [
		{
			"uuid": "96C9766F-AE06-4720-AA0F-60A12D7BAAB8",
			"type": "BufferGeometry",
			"data": {
				"attributes": {
					"position": {
						"itemSize": 3,
						"type": "Float32Array",
						"array": [ // some vertices here ]
					}
				}
			}
		}
	]

The `ObjectLoader` uses the `BufferGeometryLoader` to load this sort of geometry, but `BufferGeometryLoader` cannot instantiate the typed `Float32Array` in its parse function. The line causing the issue is this:

		var typedArray = new self[ attribute.type ]( attribute.array );
`self` does not contain the `Float32Array` type to be instantiated! `self` only contains some attributes for *typeface.js*. I had to substitute `self`by `window` temporarily in my code to make it work.
So this might be an issue or my setup does prevent `self` from being correctly initialized to `window`. 

I work on a windows 7 system in chrome browser 44.0. I am using requireJS to put ThreeJS into my project. Maybe this is the problem?

**Comment by antont** [comment]
could you try easily without require?

**Comment by Michbeckable** [comment]
Actually no, it is a quite integrated system and I am just a newbie with require, nodejs, gulp etc. I guess this problem is related to ThreeJS needing the global `self` object and we are using nodejs which seems to NOT have the self object: https://github.com/mrdoob/three.js/issues/3884

**Comment by Michbeckable** [comment]
Another problem with `self` and gulp and require setup breaking the `self` reference: http://stackoverflow.com/questions/24595634/using-gulp-jasmine-testcase-with-threejs-library-leads-to-problems-with-self-r

**Comment by antont** [comment]
err nodejs is for server side, but in the original description you say that are using chrome.

so are you running this code in nodejs or chrome?

**Comment by Michbeckable** [comment]
Actually it is client side - I run it in chrome yes.

**Comment by mrdoob** [comment]
> `self` does not contain the `Float32Array` type to be instantiated! `self` only contains some attributes for *typeface.js*.

That sounds weird. Is typeface.js messing with the context?

**Comment by Michbeckable** [comment]
OK, I found the error. The very first line in my three.js was: 

    var self = self || {};
This caused the self object to be empty (except the typeface.js stuff, but this is added by ThreeJS). I took the current r71 files from your repository, where this line is missing and everything works as expected. I have no idea where this line is coming from. I also had it in the three.min.js. As I never minified ThreeJS myself it is unlikely that it was an edit by me. Maybe there was a commit (within r71) adding this line? 

Further this line should actually keep the self object and its contents if it is defined, but it seem to does not?!

**Comment by antont** [comment]
It seems to be there in the three.js repo: https://github.com/mrdoob/three.js/blob/dev/utils/npm/header.js

**Comment by Michbeckable** [comment]
Yes, and I see that every `npm install` brings this line back again. Is it actually needed in the npm header?

**Comment by xoryouyou** [comment]
the `header.js` seems to only exist for the `npm/build.js`  where it gets  concatenated with the actual build file and some `footer.js` https://github.com/mrdoob/three.js/blob/5c7e0df9b100ba40cdcaaf530196290e16c34858/utils/npm/build.js#L69

I just checked out the repo  and build  the npm package with a commented out `header.js`  seems to build fine  maybe @bhouston  knows something about this `header.js`

**Comment by bhouston** [comment]
The header.js self was used for the font system but likely from a long time ago, but we can remove it.  Unfortunately, I am heading out on vacation as we speak so I can not fix it right now.

**Comment by bhouston** [comment]
Here is the reasoning, but unfortunately, I do not have time to validate this right now: https://github.com/mrdoob/three.js/pull/3306

**Comment by xoryouyou** [comment]
@bhouston would there be a way that we can fix and test this while you are on vacation ?

**Comment by bhouston** [comment]
You can modify anything you want. :)

**Comment by bhouston** [comment]
If you want npm three write access share your account name with me.

**Comment by xoryouyou** [comment]
Hehe ,yeah but I do not want to break some part of the Typeface system. My npm name is my github name ;)

**Comment by bhouston** [comment]
If you are concerned @xoryouyou, just temporarily make a new npm repository called three-xoryouou or something like that and use it for the time being.

**Comment by xoryouyou** [comment]
Ugly workaround but hey ..why not  :+1:

**Comment by bhouston** [comment]
@xoryouyou can you add me to LinkedIn so I know who you are?  https://www.linkedin.com/in/benhouston  I figure we should have some security on the npm repository.

**Comment by xoryouyou** [comment]
For sure will do.

**Comment by xoryouyou** [comment]
Ok i've tried to build the npm package with the `header.js` commented out.
But then after running `node test.js` it fails.

`
/tmp/three.js/utils/npm/node_modules/three/three.js:27147
self._typeface_js = { faces: THREE.FontUtils.faces, loadFace: THREE.FontUtils.
^
ReferenceErroWrite r: self is not defined
    at Object.<anonymous> (/tmp/three.js/utils/npm/node_modules/three/three.js:27147:1)
`

So it seems like there is no simple quickfix.  

Can anybody explain why the `_typeface_js` object gets appended to `self` ?

**Comment by xoryouyou** [comment]
Hey Guys, after a bit of fiddling around and looking into the Issue i've  found the line which causes the trouble.

It's https://github.com/mrdoob/three.js/blob/master/src/loaders/BufferGeometryLoader.js#L44 

When you compile the npm package of three.js via Browserify / Webpack it works for 99% of the cases. But it seems that this `BufferGeometryLoader` which  gets invoked when loading a JSON Scene tries to dynamically generate a `attribute.type` array which could be for example `Float32Array`.

The problem now is that while running under NodeJS there is no `self` object and fixing it with using window wouldnt work either.

So in the Browser  a self is defined which simply points to `Window`  but both offer the plain functionality to just invoke `attribute.type()`  to get a new Array.

So I've made this little change and would like some of you guys to review it.

```
    @@ -41,7 +41,7 @@ THREE.BufferGeometryLoader.prototype = {
     		for ( var key in attributes ) {
 
 			var attribute = attributes[ key ];
-			var typedArray = new self[ attribute.type ]( attribute.array );
+			var typedArray = new attribute.type( attribute.array );
 
 			geometry.addAttribute( key, new THREE.BufferAttribute( typedArray, attribute.itemSize ) );
```
What do you guys think @mrdoob , @bhouston, @antont  ?

**Comment by mrdoob** [comment]
If that works, looks good to me :+1:

**Comment by xoryouyou** [comment]
@mrdoob  I've made a second npm repo for test purposes here: https://www.npmjs.com/package/three-xoryouyou

I'm waiting for @Michbeckable  to confirm if it works.

And then I'll  make a PR for this issue in the next days.

**Comment by brianxu** [comment]
I ran into the same issue. I am using webpack, so that ```var self = self || {};// File:src/Three.js``` is actually within a function created by webpack. It looks like if the variable is defined within a function, it's treated as a local variable and never reach to the window.self. You can try the following example to see what's going on:
```
var abc = "test"
var x = function(){var abc = abc || {};console.log(abc);};
x();
print Object {}
var x = function(){var abcd = abc || {};console.log(abcd);};
print "test"
```

**Comment by brianxu** [comment]
I think maybe the simple solution is to replace self with something else like:
```var myself = self || {};``` :)

**Comment by mrdoob** [comment]
@brianxu see #7787
