### ISSUE TITLE
Interact/rotate object

### ISSUE THREAD

**Issue by krusk** [mrdoob/three.js#6933]
I am using the example as follows, but can't interact with the object to rotate via mouse click. Is this feasible, if so, what would I need to add. It can rotate by default... but the desired behavior is to be able to freely interact with the object by rotating it left,right,up,down, etc. with a mouse click (or fingers on a mobile device):

    <!DOCTYPE html>
    <script src="scripts/three.min.js"></script>
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <title>My first Three.js app</title>
    <style>
        body {
            margin: 0;
        }

        canvas {
            width: 100%;
            height: 100%;
        }
    </style>
    </head>
    <body>
    <script src="scripts/three.min.js"></script>
    <script>
			var scene = new THREE.Scene();
			var camera = new THREE.PerspectiveCamera( 75, window.innerWidth/window.innerHeight, 0.1, 1000 );

			var renderer = new THREE.WebGLRenderer();
			renderer.setSize( window.innerWidth, window.innerHeight );
			document.body.appendChild( renderer.domElement );

			var geometry = new THREE.BoxGeometry( 1, 1, 1 );
			var material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
			var cube = new THREE.Mesh( geometry, material );
			scene.add( cube );

			camera.position.z = 5;

			var render = function () {
				requestAnimationFrame( render );

				cube.rotation.x += 0.01;
				cube.rotation.y += 0.01;

				renderer.render(scene, camera);
			};

			render();
    </script>
    </body>
    </html>

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
