### ISSUE TITLE
Stemkoski's ParticleEngine not working after r69

### ISSUE THREAD

**Issue by Astrak** [mrdoob/three.js#6937]
I was willing to use Stemkoski's ParticleEngine on r71 but found it broken above r69 (i found out that the WebGLRenderer part was the compatibility problem). Until r69 the page works great, while the original code uses r60. There is nothing to note on the console once few migration is done (ParticleSystem>PointCloud, PlaneGeometry>PlaneBufferGeometry). 

His code is 400lines-length and uses basic vectors operations, THREE.PointCloud, THREE.ShaderMaterial, THREE.Color, THREE.Geometry. So i have no idea where the compatibility issue is. Any idea ?

This question may be good for stackoverflow since ParticleEngine is not in this repository, but given Stemkoski contribution i thought this could also be a good place to ask.

**Comment by titansoftime** [comment]
I use this: https://github.com/squarefeet/ShaderParticleEngine which is based on Stemkoski's Particle Engine. Works up to 71 (72 breaks it, but waiting for it to rollout before bothering him).

**Comment by Astrak** [comment]
Thanks it is great ! Also i had not even though to visit stemkoski's repository that leads to it too .. ^^
