### ISSUE TITLE
Raycast with non indexed BufferGeometry and drawcalls

### ISSUE THREAD

**Issue by mortalV** [mrdoob/three.js#6939]
I'm using r72dev and non indexed BufferGeometry. 
Sometimes I need hide some faces and I use drawcalls for exclude part of geometry.
All works fine except raycast.
As I see in sources only indexed BufferGeometry uses drawcalls but non indexed no.

Is it by design, not yet implemented or just bug?

Thanks.

**Comment by WestLangley** [comment]
Not yet implemented -- likely because coders followed previous coding patterns, and it was not implemented at the start.

Non-indexed `BufferGeometry` supports `drawcallls`, but the `Mesh`,`Line`, and `PointCoud` `raycast` method omits that case.

**Comment by Mugen87** [comment]
To clarify, `drawcalls` is now `groups` and those are supported in context of `BufferGeometry` and `Mesh.raycast()` via #14227.

Let's use #8479 to track a possible enhancement for `Line.raycast()` and `Points.raycast()`.
