### ISSUE TITLE
Material/Shader Problem

### ISSUE THREAD

**Issue by Rouzzy** [mrdoob/three.js#6945]
Creating a simple bump map material results in a shader faliure 
THREE.WebGLShader: gl.getShaderInfoLog() WARNING: 0:3: '
' : extension directive must occur before any non-preprocessor tokens 
 1: precision highp float;
2: precision highp int;
3: #extension GL_OES_standard_derivatives : enable

should put #extentions GL_OES_standard_derivatives: enable on top to remove that problem.
problem is also seen in http://threejs.org/examples/#webgl_materials_bumpmap.
The example works fine, but for any other material/shader use it causes problems.

**Comment by WestLangley** [comment]
Thanks, but this has been fixed in the `dev` branch. See #6493.
