### ISSUE TITLE
THREE.Material does not set visible

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6949]
this pattern
```javascript
new THREE.Material ({ visible: false })
```
does not work, visible remains true.

not sure if it is expected to work, seems setting material to null is fine.

**Comment by makc** [comment]
> seems setting material to null is fine.

correction: is not for skins :shit: will have to manually set .visible = false then.

**Comment by mrdoob** [comment]
Uh?

**Comment by makc** [comment]
I have this scene where I have to replace some materials and hide the others. Rather than setting visible on existing materials to turn some of them off, I am trying to set this no-op material and later restore all materials in the scene by setting them back to unchanged original materials.

not setting visible to false on new THREE.Material gets you shader can't be compiled error because there is no shader (but manually setting visible to false is ok). setting materials to just null is also ok for mesh, but for skin it gets you error where threejs still expects some object to be present - that's why I have to stick with

```
foo = new THREE.Material ();
foo.visible = false;
```

instead of the code above.

**Comment by mrdoob** [comment]
Hmm, I've just tried with `dev` and seems to work fine...? Do you mind creating a jsfiddle?

**Comment by dubejf** [comment]
@mrdoob I think that what @makc  is saying is that `THREE.Material` constructor does not accept a `parameters` argument.

**Comment by makc** [comment]
@dubejf ah yes, that explains it. and another problem that you can't set the skin material to null.

**Comment by makc** [comment]
the problem with skin, btw, is caused by this line (r70, r71) in three.js:
```javascript
useSkinning = object instanceof THREE.SkinnedMesh && objectMaterial.skinning;
```
but somehow it is not triggered in http://threejs.org/examples/webgl_animation_skinning_blending.html if I do 
```javascript
scene.getObjectByProperty('type', 'SkinnedMesh').material = null
```
there, so not all code paths hit that line.

**Comment by makc** [comment]
> not all code paths hit that line

apparently that was because I had shadows

**Comment by makc** [comment]
ok, I think I will close this, as a
> THREE.Material constructor does not accept a parameters argument

is pretty much valid explanation. The skin thing will go in separate issue.
