### ISSUE TITLE
skin cant have null material when shadows are used

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6959]
Setting skin.material to null causes this line to throw errors when rendering the scene:

```javascript
useSkinning = object instanceof THREE.SkinnedMesh && objectMaterial.skinning;
```

(because objectMaterial is now null).

**Comment by WestLangley** [comment]
Why don't you propose a solution in the form of a PR if you feel the library should support renderable objects with `null` materials?

**Comment by makc** [comment]
Basically because I am sitting on pre-r72 version. I guess I could make a patch against that and throw that at dev branch regardless... I'm pretty sure that
```javascript
if (!objectMaterial) continue;
```
just above this line will solve it.

>  if you feel the library should support renderable objects with null materials?

I guess I do because it works fine with mesh. If the idea is that it should not, I can live with that.

**Comment by WestLangley** [comment]
Being fault-tolerant is reasonable. Do you think that `null` material and `undefined` material should behave the same as `material.visible = false`? What about `undefined`/`null` geometry?

I do not care what the behavior is. As long as it is consistent throughout the library.

**Comment by makc** [comment]
>  Do you think that null material and undefined material should behave the same as material.visible = false? What about undefined/null geometry?

you might expect that the lib will not draw anything when it does not have enough to draw something. or throw errors randomly. or throw errors consistently ) it is simply the decision you can make.

**Comment by WestLangley** [comment]
> you might expect that the lib will not draw anything when it does not have enough to draw something. or throw errors randomly. or throw errors consistently ) it is simply the decision you can make.

I had hoped you'd provide a constructive answer. :/

**Comment by makc** [comment]
I don't have enough reasons to insist on some particular resolution. Any course of action is more or less ok. I do prefer 1st one, personally, which is indicated by creating this tickket, but it is weak preference.

**Comment by WestLangley** [comment]
OK. Unfortunately, the renderer references `material.xxxxx` frequently, without first checking to see if the material is well-defined -- perhaps it is checked earlier in the logic...

Let's see what behavior @mrdoob -- and others -- prefer.

**Comment by mrdoob** [comment]
@makc why are you setting `material` to `null`?

Also, likely related... While studying your previous issue #6949 I realised that `WebGLShadowMap` wasn't checking for `material.visible`. Fixed it in 829ee3dc6740b2a66eb36009d49740eeb475e36a.

**Comment by makc** [comment]
> why are you setting material to null?

because it saves me two lines )
```javascript
mesh.material = null;
// vs
var mat = new THREE.Material ();
mat.visible = false;
mesh.material = mat;
```
before you ask why don't I just
```javascript
mesh.visible = false;
// or
mesh.material.visible = false;
```
that was covered in #6949:
> Rather than setting visible on existing materials to turn some of them off, I am trying to set this no-op material and later restore all materials in the scene by setting them back to unchanged original materials.

**Comment by mrdoob** [comment]
I see... I guess we can support `material === null`...

**Comment by mrdoob** [comment]
@makc do you min trying the `dev` version?

**Comment by WestLangley** [comment]
Wait. We have been using `undefined`, not `null. Furthermore, we exclude `null` because we have swiched to this pattern:

    if ( material !== undefined )

from

    if ( material != undefined );

What is the pattern we want to support? What about `undefined/null` geometry?

**Comment by makc** [comment]
why not just `if (material)` ? it's not like you want the code to work if someone sets material to NaN or "".

**Comment by antont** [comment]
regardless or whether supporting null material there is good or not (i have no idea yet), just wondering of another point:

what about

```
mesh.material = my_invisible_noop_material; //or even THREE.Material.Invisible / Noop, eh?
```

instead of either of those:

```
mesh.material = null;
// vs
var mat = new THREE.Material ();
mat.visible = false;
mesh.material = mat;
```

**Comment by makc** [comment]
@antont sure I do have my `mat` (aka `my_invisible_noop_material`) variable just outside the loop, to save poor gc some work, but those are still same two lines of code. to ask for THREE.Material.Invisible would be an overkill, I mean how many people would use it vs dot visible? But using null is free.

**Comment by makc** [comment]
btw if you decide to support nulls, there is #6688 to reopen

**Comment by makc** [comment]
Or if using undefined would universally work, I'm happy too

**Comment by mrdoob** [comment]
> why not just `if (material)` ? it's not like you want the code to work if someone sets material to NaN or "".

I just don't like that type of coding. Makes things uncertain. If we are helping someone with their code it creates many more possibilities to have to consider.

> btw if you decide to support nulls, there is #6688 to reopen

Hmm, I'm thinking we should not support neither `null` nor `undefined`. Instead of adding checks in all the renderers for `material`, maybe we should add a getter/setter to `Mesh.material` itself that ignores the `set` if the value is not an instance of `THREE.Material` (or `THREE.MeshFaceMaterial`).

**Comment by makc** [comment]
> ignores

that is bad idea. you should throw error or at least show the warning in the console then.

**Comment by mrdoob** [comment]
>> ignores

> that is bad idea. you should throw error or at least show the warning in the console then.

Yep yep, I meant that 😅

**Comment by makc** [comment]
I am going to retract this statement,
> it works fine with mesh

it did not work in 71.
