### ISSUE TITLE
ThreeJSAnimationExporter.ms not work

### ISSUE THREAD

**Issue by matrix3d** [mrdoob/three.js#6960]

**Comment by antont** [comment]
BTW there is an open pullrequest which may be related, or not: https://github.com/mrdoob/three.js/pull/6776

**Comment by matrix3d** [comment]
@mrdoob @antont https://www.dropbox.com/s/9sqda5z0wr2mr52/%E5%A5%B3_%E5%8A%A8%E4%BD%9C_%E6%96%B0-2010.max?dl=0
this is my 3dmax file,can not export
