### ISSUE TITLE
Can't use CTMWorker when loading ctm model with CTMLoader

### ISSUE THREAD

**Issue by polyclick** [mrdoob/three.js#6966]
I'm including threejs via bower into my project

```
    <script src="/bower_components/threejs/examples/js/loaders/ctm/lzma.js"></script>
    <script src="/bower_components/threejs/examples/js/loaders/ctm/ctm.js"></script>
    <script src="/bower_components/threejs/examples/js/loaders/ctm/CTMLoader.js"></script>
```

Then, when I try to use the worker option on the CTMLoader:
```
    var loader = new THREE.CTMLoader();
    loader.load( 'models/manta.ctm',   function( geometry ) {
        // do stuff with geometry
    }, { useWorker: true } );
```

An error appears in console: `GET http://localhost:9000/js/loaders/ctm/CTMWorker.js 404 (Not Found)`
This is because the path to load the worker in CTMLoader is incorrect.

I tried to include CTMWorker.js myself by putting it before the CTMLoader include:

```
    <script src="/bower_components/threejs/examples/js/loaders/ctm/lzma.js"></script>
    <script src="/bower_components/threejs/examples/js/loaders/ctm/ctm.js"></script>
    <script src="/bower_components/threejs/examples/js/loaders/ctm/CTMWorker.js"></script>
    <script src="/bower_components/threejs/examples/js/loaders/ctm/CTMLoader.js"></script>
```

In the hope that the CTMLoader sees that the script is already loaded. But this throws an other error: `Uncaught ReferenceError: importScripts is not defined`.

Setting the useWorker to false temporary fixes the problem and loads the model.
Can this be fixed? ;)

**Comment by polyclick** [comment]
Checked this in r72. This issue is still open (imho).

Judging by the label added, I think my initial description wasn't clear enough. This isn't me asking for help but reporting an issue :p

`CTMLoader.js` has a relative path to `CTMWorker.js` starting from the `/examples` folder in its source code: `js/loaders/ctm/CTMWorker.js` (line 132 in CTMLoader.js)
This results in the `CTMWorker.js` not getting loaded by the browser when the whole threejs library has been included via a package manager like bower.

The path should be configurable or even better: we should be able to include `CTMWorker.js` manually before `CTMLoader.js` so that `CTMLoader.js` can use the already loaded script and shouldn't try to load it by itself.

**Comment by WestLangley** [comment]
In `CTMLoader.load( url, callback, parameters )`
```javascript
var worker = parameters.worker || new Worker( "js/loaders/ctm/CTMWorker.js" );
```

Why can't you define `parameters.worker`?

**Comment by polyclick** [comment]
til: I need to look further than the line where the error is happening. 
Thanks a lot, problem solved by passing my own created worker instance to the loader.
