### ISSUE TITLE
disposing geometry sometimes causes empty screen

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#6968]
one of poor bug reports, I have this weird bug where calling geometry.dispose() on the mesh previsously removed from the scene results in empty screen (r70, r71). there are no other symptoms, Firefox is silent, Chrome says
> GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to render with no buffer attached to enabled attribute 3

now, they will likely go with the workaround (using different model) and since this error happens somewhere deep in threejs, I don't get to investigate much, nor create jsfiddle. this bug may still exist through the weekend, so if you have any recomendations how to probe for possible cause from console (can't change the code) - I might get some data.

**Comment by mrdoob** [comment]
Does it happen in `r72dev` too?

**Comment by makc** [comment]
I have no way to check :(

**Comment by makc** [comment]
This bug is now lost.
