### ISSUE TITLE
Vector3 cross & dot returns NAN

### ISSUE THREAD

**Issue by jtwebguy** [mrdoob/three.js#6969]
i was getting the cross product of a vector and UP(0,0,1) and it always returns NAN so i used this:

```javascript
function vCross(a, b) {
    var ax = a.x, ay = a.y, az = a.z,
        bx = b.x, by = b.y, bz = b.z;

    var x = ay * bz - az * by;
    var y = az * bx - ax * bz;
    var z = ax * by - ay * bx;
    return new THREE.Vector3(x,y,z);
}
```

**Comment by WestLangley** [comment]
@jtwebguy Sorry, I do not understand your post.

If you believe there is a three.js bug, can you provide an example so we can reproduce it?

Are you referring to three.js r.71?
