### ISSUE TITLE
Issue with (counter)clockwise THREE.EllipseCurve.

### ISSUE THREAD

**Issue by neko1235** [mrdoob/three.js#6972]
The `EllipseCurve` documentation says:

> When going clockwise it's best to set the start angle to (Math.PI \* 2) and then work towards lower numbers.

@WestLangley said:

> This has caused a lot of confusion. Would it be correct to say this, instead?
> 
> > If `clockwise` is false (the default), set `0 < startAngle < endAngle < 2 * Math.PI`.
> > If `clockwise` is true, set `2 * Math.PI > startAngle > endAngle > 0`.
> > If that is not correct, we need to modify the code so the behavior is understandable.

`startAngle < endAngle` makes the ellipse counterclockwise. `startAngle > endAngle` makes the ellipse clockwise. The `clockwise` parameter just changes that direction to the opposite.

An ellipse should be always counterclockwise by default, regardless of `startAngle` and `endAngle`, and clockwise only when the `clockwise` parameter is `true`.

**Comment by neko1235** [comment]
@WestLangley Please let me know if I missed anything.

**Comment by neko1235** [comment]
This needs to be fixed in `THREE.EllipseCurve`, `THREE.Path.ellipse` and `THREE.Path.absellipse`.

**Comment by neko1235** [comment]
In particular, this needs to be also fixed:
```javascript
if ( deltaAngle < 0 ) deltaAngle += Math.PI * 2;
if ( deltaAngle > Math.PI * 2 ) deltaAngle -= Math.PI * 2;
```
`EllipseCurve` should accept any numbers for `startAngle` and `endAngle`.

**Comment by WestLangley** [comment]
> startAngle < endAngle makes the ellipse counterclockwise. startAngle > endAngle makes the ellipse clockwise. The clockwise parameter just changes that direction to the opposite.

Ugh. If that is correct, and I have no reason to doubt you, we have to fix this -- in spite of the breakage it will cause.

> An ellipse should be always counterclockwise by default, regardless of startAngle and endAngle, and clockwise only when the clockwise parameter is true.

Yes.

> EllipseCurve should accept any numbers for startAngle and endAngle.

Yes.

Drawing should always start at `startAngle` and end at `endAngle`. The angles can take any values -- positive, negative, or greater than `2 PI`. The `clockwise` parameter determines the direction around the curve.

**Comment by WestLangley** [comment]
>Drawing should always start at startAngle and end at endAngle. The angles can take any values -- positive, negative, or greater than 2 PI. The clockwise parameter determines the direction around the curve.

This works as expected.
