### ISSUE TITLE
change visibility of objects not applied to children objects

### ISSUE THREAD

**Issue by yanongena** [mrdoob/three.js#6973]
using THREE.WebGLRenderer 71
I have a mesh with several children like this:
```javascript
parentObject.visible = false;
child1.visible = true;
child2.visible = true;
parentObject.add(child1);
parentObject.add(child2);
```
When the scene is rendered, I don't see my child objects which is as expected. 

Later on when I change my parentObject to
```javascript
parentObject.visible = true; 
```
I see all my object which is also as expected. 

When I change the visibility of my parentObject:
```javascript
parentObject.visible = false;
console.dir(parentObject);
```
I notice that all my children also get visible = false which is fine however when I do this:
```javascript
parentObject.visible = true;
console.dir(parentObject);
```
I notice only the parentObject.visible is set to true while the child objects are stll hidden. 

Currently I solved it by writing a loop that traverses the children and set them manually to visible.

**Comment by WestLangley** [comment]
Can you provide a test case to demonstrate the issue? See "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by yanongena** [comment]
I found the issue, it was a problem in my code. 
I basically pulled a list of all object visible for the camera and set those to visible = false; 
I forgot that that list didn't contain the same hierarchy of objects but instead delivered all the objects in a flat array. 
Problem is solved.

**Comment by tschw** [comment]
Wait a sec...

> When the scene is rendered, I don't see my child objects which is as expected. 

Maybe if `! visible` we should always skip all child nodes and promote `material.visible` for this case as we do for raycasting on `dev`. Do we already?

/ping @mrdoob

**Comment by mrdoob** [comment]
> Maybe if `! visible` we should always skip all child nodes and promote `material.visible` for this case as we do for raycasting on `dev`. Do we already?

Yep yep!

**Comment by yanongena** [comment]
What's the difference between mesh.visible and material.visible? How to properly use them?

**Comment by tschw** [comment]
Sounds like the difference is your code will keep working with future versions of Three.js :-)

`mesh.invisible=false` effectively makes the object nonexistent. For efficiency reasons it makes much sense to disable all recursive processing in that case. `mesh.material.invisible=false` OTOH keeps the object alive and only makes it *appear* invisible; it will continue being processed.

For greater control you can still flatten your object into a `THREE.Group`.

**Comment by WestLangley** [comment]
@yanongena 

If `mesh.visible` is `false`, the mesh and the mesh's children will not render.

If `mesh.material.visible` is `false`, the mesh will not render, but its children will.

**Comment by mrdoob** [comment]
So happy that we finally the solution for this...!
