### ISSUE TITLE
Large Geometry extremely slowdown ray casting performance

### ISSUE THREAD

**Issue by tormozok** [mrdoob/three.js#6978]
When I load large geometry(vertices - 53642, faces 90748), I have fps about 14. 
I wrote simple method for split geometry to pieces and fps grows over 30. 
(Chrome, GPU Intel HD4600)

This code maybe usable for another users and cases?...

``` javascript
 function splitGeometry(geometry, subBoxSize) {
    geometry = geometry.clone();
    subBoxSize = +subBoxSize || 300;

    var boxes = geometry.faces.map(function(f){
        var a = geometry.vertices[f.a];
        var b = geometry.vertices[f.b];
        var c = geometry.vertices[f.c];
        var triMin = new THREE.Vector3(
            Math.min(a.x, b.x, c.x),
            Math.min(a.y, b.y, c.y),
            Math.min(a.z, b.z, c.z)
        );
        var triMax = new THREE.Vector3(
            Math.max(a.x, b.x, c.x),
            Math.max(a.y, b.y, c.y),
            Math.max(a.z, b.z, c.z)
        );
        return new THREE.Box3(triMin, triMax);
    });
    geometry.computeBoundingBox();
    var currentFaces = [{
        box: new THREE.Box3(geometry.boundingBox.min, geometry.boundingBox.max),
        faceIndexes: geometry.faces.map(function (v, k) { return k; })
    }];
    var boxSize = geometry.boundingBox.max.clone().sub(geometry.boundingBox.min);
    for (var split = true; split;) {
        split = false;
        var mxs = Math.max(boxSize.x, boxSize.y, boxSize.z);
        var coord = mxs === boxSize.x ? 'x' : mxs === boxSize.y ? 'y' : 'z';
        boxSize[coord] /= 2;
        var nextFaces = [];
        for (var k = 0; k < currentFaces.length; k++) {
            var fs = currentFaces[k];
            if (fs.faceIndexes.length > subBoxSize) {
                var box1 = fs.box.clone(), box2 = fs.box.clone();
                var faceIndexes1 = [], faceIndexes2 = [];
                box1.max[coord] -= boxSize[coord];
                box2.min[coord] += boxSize[coord];
                for (var j = 0; j < fs.faceIndexes.length; j++) {
                    var fi = fs.faceIndexes[j];
                    if (boxes[fi].isIntersectionBox(box1)) {
                        faceIndexes1.push(fi);
                    } else {
                        faceIndexes2.push(fi);
                    }
                }
                if (faceIndexes1.length) {
                    nextFaces.push({box: box1, faceIndexes: faceIndexes1});
                }
                if (faceIndexes2.length) {
                    nextFaces.push({box: box2, faceIndexes: faceIndexes2});
                }
                split = true;
            } else {
                nextFaces.push(fs);
            }
        }
        currentFaces = nextFaces;
    }
    return currentFaces.map(function (f) {
        var vi = {};
        var newGeometry = new THREE.Geometry();
        newGeometry.faces = [];
        f.faceIndexes.forEach(function (fi) {
            var face = geometry.faces[fi];
            ['a', 'b', 'c'].forEach(function (comp) {
                var vertex = face[comp];
                if (vi[vertex] === undefined) {
                    vi[vertex] = newGeometry.vertices.push(geometry.vertices[vertex]) - 1;
                }
                face[comp] = vi[face[comp]];
            });
            newGeometry.faceVertexUvs[0].push(geometry.faceVertexUvs[0][fi]);
            newGeometry.faces.push(face);
        });
        newGeometry.computeBoundingSphere();
        return newGeometry;
    });
}
```

**Comment by RemusMar** [comment]
> When I load large geometry(vertices - 53642, faces 90748), I have fps about 14.
> I wrote simple method for split geometry to pieces and fps grows over 30. 

Well, this is not a general rule.
Depending on your model structure & shaders, sometimes you get better performances with a single model of 100K polys compared to 1000 models of 100 polys.

cheers

**Comment by tormozok** [comment]
And what is the rule to split or not to split geometry? This was Lambert material and landscape geometry.

**Comment by tormozok** [comment]
Maybe this is a clipping?

**Comment by RemusMar** [comment]
> And what is the rule to split or not to split geometry? 

As I said before, it depends on the model structure & shaders.
Simply put: it depends on geometry culling.
Example:
You have a 100K pollys statue inside of a 100K polys castle.
To split the statue into several pieces is a BAD MOVE: you'll get a performances drop!
But if you split the castle into several sectors you'll get a performances boost.
I hope you got the main picture.

cheers

**Comment by mrdoob** [comment]
> Maybe this is a clipping?

Likely...?

**Comment by tormozok** [comment]
I try to change meshes frustumCulled (This field changes mesh clipping?..), but it's not affect fps (+-1).

**Comment by tormozok** [comment]
I modify split function (max triangles limit) and experiment with examples/webgl_loader_ctm.html 
without split, fps - 29
max tris = 100, fps - 8
max tris = 1000, fps - 31
max tris = 10000, fps - 31.5
max tris = 20000, fps - 31
max tris = 100000, fps - 30
...
https://gist.github.com/tormozok/91292b57927c8deb53e9

But on my geometry I get boost (with max tris = 300 )from 14 to 42 fps (3 times)... 

I will attach example soon...

**Comment by dubejf** [comment]
For reference, http://threejs.org/examples/#webgl_modifier_subdivision Suzanne / level 5 (~1M faces) I get at worst 35 FPS (facing the monkey) at 1920x1080. FPS improves if I shrink the canvas, face the back/side or zoom-in on the model. Five year old GeForce 460.

**Comment by tormozok** [comment]
Fix. Large geometry slow down ray casting. 

I found few time and profile this again and found huge CPU load on ray casting. Splitting speed up only ray casting, not rendering.

**Comment by tormozok** [comment]
https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/190277/1385424/D1J0ok7iYISCyae/raycast.tar.gz

**Comment by EliasHasle** [comment]
@tormozok 
> Splitting speed up only ray casting, not rendering.

That makes sense, as a lots of polygon-level checks are eliminated early in the step of checking intersections of the ray with the bounding volumes of each of the parts. See the raycast method in Mesh [here](https://github.com/mrdoob/three.js/blob/dev/src/objects/Mesh.js). It first checks against the bounding sphere, then against the bounding box, then if there is an intersection with both, it just loops through all the triangles and checks them one by one.

You can subclass Mesh for your use case and write a custom raycast method that uses any type of spatial subdivisioning.
