### ISSUE TITLE
three.js Truck Factor

### ISSUE THREAD

**Issue by gavelino** [mrdoob/three.js#6980]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **three.js** and obtained a value of **2**.

The developers responsible for this TF are:

Mr.doob - author of 44% of the files
Ed Caspersen (repsac) - author of 20% of the files

To validate our results, we would like to ask **three.js** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **three.js**?

(b) Do you agree that **three.js** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **three.js** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by mrdoob** [comment]
😑

**Comment by makc** [comment]
@gavelino 
> if they win in the lottery

I'm affraid this would cause them be even more involved :) in order for them to leave, you need them to face severe debts.
