### ISSUE TITLE
SceneExporter should export version 4 scene

### ISSUE THREAD

**Issue by jimblackler** [mrdoob/three.js#6985]
Current formatVersion is 3.2.

Happy to take a crack at this myself. Is there a list of changes between versions.

**Comment by dubejf** [comment]
`SceneExporter` is being deprecated. You should use `toJson()`.

**Comment by jimblackler** [comment]
Excellent, thank you.

Perhaps the bug should be that SceneExporter be marked as deprecated.

**Comment by mrdoob** [comment]
Fixed 😛

**Comment by dubejf** [comment]
@mrdoob 

1. `SceneExporter` was for v3, `toJSON()` is v4. Correct?
2. Do you know if there is any feature of `SceneExporter` that is missing from `toJSON()`? 
3. There are a handful of `SceneExporter` issues still open. I suppose they can be closed.
4. Wiki update?

**Comment by mrdoob** [comment]
1. Correct
2. I had a look and seemed that `.toJSON()` supports everything already
3. Yep!
4. That'd be great! 😊
