### ISSUE TITLE
issue with THREE.Mesh.prototype.raycast

### ISSUE THREAD

**Issue by BramVM** [mrdoob/three.js#6986]
I am new to three.js and open source in general so i don't know how this works and hope i provide  enough information. I found following issue:

In function "THREE.Mesh.prototype.raycast"  at line 15387 ("var geometry = this.geometry;") of three.js, somehow "this" holds the window element. Since "window" has no property "geometry" this equals "undefined".

Therefore i get an error at line 15391 "if ( geometry.boundingSphere === null ) geometry.computeBoundingSphere();" (trying to read property 'boundingSphere' of "undefined")

error:
Uncaught TypeError: Cannot read property 'boundingSphere' of undefined
stacktrace:
(anonymous function) @ three.js:15391intersectObject @ three.js:7339intersectObject @ three.js:7347THREE.Raycaster.intersectObjects @ three.js:7419_checkCollission @ bundle.js:494_checkCollissionRecursive @ bundle.js:505render @ bundle.js:454animate @ bundle.js:447

my function:
_checkCollission = function (MovingCube){
	if (MovingCube.geometry){
		var globalPosition = new THREE.Vector3();
		globalPosition.setFromMatrixPosition( MovingCube.matrixWorld );
		var originPoint = globalPosition.clone();
		for (var vertexIndex = 0; vertexIndex < MovingCube.geometry.vertices.length; vertexIndex++)
		{		
			var localVertex = MovingCube.geometry.vertices[vertexIndex].clone();
			var globalVertex = localVertex.applyMatrix4( MovingCube.matrixWorld );
			var directionVector = globalVertex.sub( globalPosition);
			var ray = new THREE.Raycaster( originPoint, directionVector.clone().normalize() );
			var collisionResults = ray.intersectObjects( physic.collidableMeshList , true);
			if ( collisionResults.length > 0 && collisionResults[0].distance < directionVector.length() && collisionResults[0].object ) 
				return collisionResults[0].object;
		}
	}
	return false
}

fix:
I fixed this localy for now by checking if the property "geometry" exsists.

**Comment by WestLangley** [comment]
If you can demonstrate a three.js bug, can you provide a test case so we can reproduce your results? Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

You can fork [this fiddle](http://jsfiddle.net/uh7xf0sL/) if you want.

**Comment by makc** [comment]
@WestLangley 
> I fixed this localy for now by checking if the property "geometry" exsists.

this is relevant to your question in #6959
> What about undefined/null geometry?

here is someone who is using it.

**Comment by makc** [comment]
ah wait,
> somehow "this" holds the window element.

I missed this :(

**Comment by BramVM** [comment]
Thanks for your reply, i read the guidelines and tried using the dev file.

I use Chrome Version 44.0.2403.125 (64-bit) on Windows7 as well as on OSX 10.9.5

I would use your fiddle if would know how to reproduce the error but i am afraid it's rather complicated. I can however link you my project. 

http://helios-projecthelios.rhcloud.com/

The error occurs when you fly around (using wasd or up,left, right,down), or just wait a minute and meet another spacecraft. When it starts shooting at you, hit left mouse button and there it is. 

I certainly hope it will make more sense when you debug it yourself, i'm not that good with words.

It's probably rather something I did wrong then an actual bug in three.js (I am still debugging to understand what exactly happens). Never the less, I do think the extra check i suggested doesn't hurt and improves code quality.

**Comment by makc** [comment]
it's not window. it is actual mesh without geometry.
![screen shot 2015-08-11 at 19 44 49](https://cloud.githubusercontent.com/assets/242577/9205298/94037470-4061-11e5-8ec6-1f6c031d89c9.png)

**Comment by BramVM** [comment]
I am very sorry guys. My previous test with the dev version was invalid (I just noticed I was still linking the normal minified version of three.js). It seems fixed on dev, no error's there.

**Comment by makc** [comment]
if there is no error now, how are they supposed to reproduce it :wink:

**Comment by BramVM** [comment]
You are right sir, as I stated earlier, I am rather new to open source and love three.js. So was eager to contribute by pointing out that checking if "geometry" is a property of "this" before checking out it's own property "boundingSphere", in code below, might actually improve it. (This is also where my personal error originated from).

Now I know I should search for "report guidelines" and try out the "dev branch" first. Anyway, thanks for your patience and sorry for wasting your time. 

THREE.Mesh.prototype.raycast = ( function () {

	var inverseMatrix = new THREE.Matrix4();
	var ray = new THREE.Ray();
	var sphere = new THREE.Sphere();

	var vA = new THREE.Vector3();
	var vB = new THREE.Vector3();
	var vC = new THREE.Vector3();

	return function ( raycaster, intersects ) {

		var geometry = this.geometry;

		// Checking boundingSphere distance to ray

		if ( geometry.boundingSphere === null ) geometry.computeBoundingSphere();

		...
