### ISSUE TITLE
Certain letters rendering incorrectly in webgl_custom_attributes_lines example

### ISSUE THREAD

**Issue by preziotte** [mrdoob/three.js#6988]
Hi there.

Certain letters consistently render incorrectly (or at least unexpectedly) in the following example: http://threejs.org/examples/#webgl_custom_attributes_lines

<img width="896" alt="screen shot 2015-08-11 at 3 27 33 pm" src="https://cloud.githubusercontent.com/assets/470264/9212938/26d98f2a-4042-11e5-8b31-aa2d3e816e34.png">

It seems to specifically effect letters with holes in them (e, p, d, etc).  My guess is that the last vertex of the letter is trying to form a closed loop with the first?  Something along those lines.  I'm not familiar enough with webgl to speculate further.  Please close if this is expected behavior, but an explanation of what's going on would be most helpful :)

I similarly attempted to load in an .obj file of 3d text and I'm seeing a very similar thing happen.

FYI I have a 2015 Macbook Pro running OSX 10.9.5 w/ a NVIDIA GeForce GT 750M.  Looks identical in both Chrome and FireFox.

**Comment by WestLangley** [comment]
Thanks for the heads-up.

This demo broke when it was modified to use `BufferGeometry`.

You can't simply use the vertices from `THREE.TextGeometry` in a `THREE.Line`. You have to use `THREE.LineSegments` and create vertex pairs.

Notice the letters are connected by a single (thin) line.

**Comment by WestLangley** [comment]
Something like could work -- although the visuals may need improvement...

```javascript
var buffergeometry = new THREE.EdgesGeometry( geometry );

var numVertices = buffergeometry.attributes.position.count;

var displacement = new THREE.Float32Attribute( numVertices * 3, 3 );
buffergeometry.addAttribute( 'displacement', displacement );

var customColor = new THREE.Float32Attribute( numVertices * 3, 3 );
buffergeometry.addAttribute( 'customColor', customColor );

...

object = new THREE.LineSegments( buffergeometry, shaderMaterial );
```

**Comment by mrdoob** [comment]
Uhm... the live link isn't using `BufferGeometry`, is it?

**Comment by WestLangley** [comment]
> Uhm... the live link isn't using BufferGeometry, is it?

You are right. `BufferGeometry` has nothing to do with it. It was previously broken.

My other comments are correct, I believe.

**Comment by preziotte** [comment]
Thanks for the prompt replies!  I'm seeing a similar issue crop up when loading in an .obj file that involves text:

```
				var manager = new THREE.LoadingManager();
				var loader = new THREE.OBJLoader( manager );
				loader.load( 'obj/file.obj', function ( object ) {
					scene.add( object );
				}, onProgress, onError );

```
<img width="375" alt="screen shot 2015-08-14 at 12 06 25 pm" src="https://cloud.githubusercontent.com/assets/470264/9281838/f8f45d46-427c-11e5-84bf-91dd44807de6.png">

When I load the same .obj file into blender, I do not see the same issue:

<img width="713" alt="screen shot 2015-08-14 at 12 10 25 pm" src="https://cloud.githubusercontent.com/assets/470264/9281924/976069e8-427d-11e5-8e58-987e7720cb52.png">

Do you feel this is related?

**Comment by mrdoob** [comment]
Not likely... But do you mind sharing that obj?

**Comment by WestLangley** [comment]
Looks like a winding order issue with the geometry. 

In three.js, try `material.side = THREE.DoubleSide`.

**Comment by preziotte** [comment]
As far as I can tell, that didn't help.  Here's the .obj https://dl.dropboxusercontent.com/u/8898714/supreme.obj

**Comment by mrdoob** [comment]
It's a different issue... `OBJLoader` doesn't support faces with more than 4 vertices.

**Comment by yomboprime** [comment]
Regarding the text, I had the same problem, some characters were consistently wrong. I was creating the text very small (it was a HUD) The solution was to create the text bigger, and after creating the mesh, adjusting its scale. It seems that some vertices were too close and they were merging.
Perhaps you have the same problem.

**Comment by preziotte** [comment]
Interesting.  I was actually able to get the .obj file to render correctly by applying a triangulate modifier to it in blender.  I figured this would reduce the number of vertices for a given face to 3 if it had too many.  It appeared to do just that.  Thanks for steering me in the right direction @mrdoob.
