### ISSUE TITLE
Problem with using transparent objects

### ISSUE THREAD

**Issue by MrMaksymov** [mrdoob/three.js#6990]
Hello, 
I am using r71. Renderer.sortObjects is setted TRUE.
How you can see on images, i can escape some objects in vision, when i am using transparent material. 
Sorry, i don't know how to explain my problem better. 

![default](https://cloud.githubusercontent.com/assets/10225367/9223965/87bd8448-4107-11e5-8a53-5ea4cbf7450b.PNG)
![1](https://cloud.githubusercontent.com/assets/10225367/9223964/87bca514-4107-11e5-9101-e5d9d595f17b.PNG)
![2](https://cloud.githubusercontent.com/assets/10225367/9223966/87c05fd8-4107-11e5-8781-f70693dd60d2.PNG)
![3](https://cloud.githubusercontent.com/assets/10225367/9223968/87c44e90-4107-11e5-8ba1-491872fe0184.PNG)
![4](https://cloud.githubusercontent.com/assets/10225367/9223967/87c0d986-4107-11e5-8d8e-3d1f8a8a52c6.PNG)

**Comment by nn4e** [comment]
Make a grid separate objects

**Comment by nn4e** [comment]
or try alphaTest: 0.05 material option

**Comment by MrMaksymov** [comment]
every detal is separeted object. I have setted alphatest, but nothing(
