### ISSUE TITLE
flycontrols + oculus rift sensitivity

### ISSUE THREAD

**Issue by tomcon25** [mrdoob/three.js#6991]
I am using fly controls to navigate a 3d three.js environment with the oculus rift. 

the oculus moves the camera with the slightest movement of the headset and wondering how i could decrease the sensitivity when the oculus controls are applied. code below:
    
setup of controls:

     `controls = new THREE.FlyControls( camera, div_globes);

    controls = new THREE.FlyControls( camera);
    controls.movementSpeed = 3;
    controls.domElement = viewport;
    controls.rollSpeed = 0.00001;
    controls.autoForward = false;
    controls.dragToLook = true;`

animation section:

`controls.update(1);
    //flyControls.update();

    
    if(oculusOn){
    ///////////////////////Occulus Specific animate code start///////////////////////
                  //controls.update();
                  vrControls.update();

                  // Temporarily save the orbited camera position
                  var orbitPos = camera.position.clone();
                    //console.log("camera pos: " + camera.position.x +" "+ camera.position.y+" "+camera.position.z);

                  // Apply the VR HMD camera position and rotation
                  // on top of the orbited camera.
                  var rotatedPosition = fakeCamera.position.applyQuaternion(
                    camera.quaternion);
                  camera.position.add(rotatedPosition);
                  camera.quaternion.multiply(fakeCamera.quaternion);
        
        
                    var rotatedPosition = orbitCamera.position.applyQuaternion(
                    camera.quaternion);
                  orbitCamera.position.add(rotatedPosition);
                  orbitCamera.quaternion.multiply(fakeCamera.quaternion);
                    //console.log("fakeCamera pos: " + fakeCamera.position.x +" "+ fakeCamera.position.y+" "+fakeCamera.position.z);
                    //render double display effect
                  vrManager.render(scene, camera);

                  // Restore the orbit position, so that the OrbitControls can
                  // pickup where it left off.
                  camera.position.copy(orbitPos);
    ///////////////////////Occulus Specific code end///////////////////////
    }`

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
