### ISSUE TITLE
Nothing is rendered in Firefox 40

### ISSUE THREAD

**Issue by Tanbouz** [mrdoob/three.js#6993]
It appears that most if not all three.js apps are broken on the newly released Firefox 40.

Examples (Working fine on Chrome 44)
Realtime Bitcoin Globe http://blocks.wizb.it/
http://globe.chromeexperiments.com/
https://dl.dropboxusercontent.com/u/6213850/WebGL/nyanCat/nyan.html
http://cabbi.bo/

**Comment by dubejf** [comment]
FF 40.0 works as expected on Windows.

**Comment by mrdoob** [comment]
![screen shot 2015-08-12 at 11 32 06](https://cloud.githubusercontent.com/assets/97088/9233053/c7ecbbbe-40e5-11e5-9e13-ba2db636b155.png)

FF 40.0 OSX

**Comment by Tanbouz** [comment]
Thanks. I was a bit confused. Guess this is not related to Three.js. Cleared Firefox cache and restarted Firefox, same problem while Chrome worked fine. Restarted my PC after I saw your posts and it is working fine now.

Probably related to nvidia driver/firefox breaking after the computer came out of sleep state. But not sure.

Windows 10 Pro 64 bit. Nvidia 353.62 driver.
