### ISSUE TITLE
Instructions for Blender JSON exporter installation on Mac OS need to be updated

### ISSUE THREAD

**Issue by Programmer-D** [mrdoob/three.js#6994]
Versions of everything I'm using:
Mac OS X Yosemite 10.10.4
Blender version 2.75a
Three.js blender exporter, version 1.4.0

The instructions say that I only need to place the io_three folder in some subfolders where blender.app is. For example: /Applications/blender.app/Contents/Resources/2.7X/scripts/addons.

This does not work. The only thing that worked for me was zipping that directory up and using Blender's Install From File... menu (**File->User Preferences->Install From File...**). Using that menu, I had to select the zipped up io_three file.

NOTE: This ended up installing the addon in the following directory: **/Users/myUser/Library/Application Support/Blender/2.75/scripts/addons**

**Comment by antont** [comment]
confirmed - putting inside the .app doesn't work anymore.

i had the addon there earlier on a mac for 2.74. now tried by installing 2.75a and adding the current addon from dev there.

got a complaint from macos that the app is damaged and it didn't even start blender. perhaps osx (or blender on it?) has some checksums or something to test app container integrity nowadays or something?

anyways also on #blendercoders recommendation was to use the /Users dir for user installed addons and blender.app/ only for those bundled in Blender distro itself.

**Comment by antont** [comment]
thinking of nice fixes to this (besides just updating the doc which is good to do immediately) checked if could easily make the blender side support installing the addon directory (python package) directly -- without needing the zipping in between.

seems pretty easy in https://developer.blender.org/diffusion/B/browse/master/release/scripts/startup/bl_operators/wm.py;487d2cb4f321d9847fb18bd57fbe7ccc3528461f$1871

if folks figure that'd be nice i can give it a shot.

**Comment by Programmer-D** [comment]
I think adding support to Blender for using the GUI so that the folder doesn't need to be zipped would be cool. Either way, thanks!
