### ISSUE TITLE
ShadowMap render causes "INVALID_OPERATION: vertexAttribPointer: no bound ARRAY_BUFFER"

### ISSUE THREAD

**Issue by nn4e** [mrdoob/three.js#6996]
r72dev
DirectLight Shadows
It occurs in setupVertexAttributes on position attribute

It does not always happen, there is some dependence on the position of the camera or shadow camera in the scene  on the first render.
not sure that I can reproduce it in the demo

perhaps a similar problem from the past: http://stackoverflow.com/questions/27116852/three-js-vertexattributepointer-no-bound-array-buffer-after-migration-to-r69

**Comment by mrdoob** [comment]
http://jsfiddle.net/jjhh6zh8/18/ Seems like I broke it again 😇

**Comment by mrdoob** [comment]
Fixed. Thanks!
