### ISSUE TITLE
three.js not working with Firefox 40.0

### ISSUE THREAD

**Issue by sirozzy** [mrdoob/three.js#7001]
Hi guys,

it seems that three.js is currently not working with the latest Firefox 40.0.

Does anyone maybe have a workaround (fix) for this?

Thank you very much

**Comment by WestLangley** [comment]
What does "not working" mean?

Related: #6993

**Comment by sirozzy** [comment]
yes.. this is what i mean. do you have any fix / workaround for it? or do i have to wait for FF 40.0.1

**Comment by sirozzy** [comment]
ok it seems that there is some issue with nvidia in combination with windows 10 and ff 40.0+ and web gl.
I just tried it on another computer with the same settings except a AMD GPU, and it workds fine
