### ISSUE TITLE
drawcall.index?

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#7003]
I was just refactoring `WebGLRenderer`'s `renderBufferDirect` a bit. In the process I lost `drawcall.index` support. https://github.com/mrdoob/three.js/commit/2e091a5429655af38481965eb93381a82af868d5

As far as I can see only http://threejs.org/examples/#webgl_buffergeometry uses it...?
Does anyone use this feature?

**Comment by WestLangley** [comment]
It was my understanding that is it required when the 65K limit is in effect, and there are more than 65K position elements.

	geometry.addDrawCall( start, count, indexOffset );

`indexOffset` is added to the value of 'index' array value before indexing into the`'position', and other attribute, arrays.

**Comment by mrdoob** [comment]
Right... Hmm...

**Comment by WestLangley** [comment]
Yeah. You are going to have to bring back `drawcall.indexOffset`.

**Comment by mrdoob** [comment]
Hmm...

But, if you look at http://threejs.org/examples/#webgl_buffergeometry source code... it's a bad example.

There is no benefit on using a index in this case, as the indices are just an incrementing number. One could as well remove the index and it will just work.

So I basically need a compelling use case...

Oh! And no, the previous code didn't use this for the 65K limit, the previous code split the index array in many.

**Comment by benaadams** [comment]
do you mean the offset for: ```void drawElements(enum mode, long count, enum type, long offset)```?

**Comment by WestLangley** [comment]
> the indices are just an incrementing number

Not so. Notice the indices reset to zero when they get too big.

```javascript
indices[ i ] = i % ( 3 * chunkSize );
```

The index offset accommodates for that.

```javascript
indexOffset = i * chunkSize * 3;
```

**Comment by WestLangley** [comment]
> And no, the previous code didn't use this for the 65K limit,

According to the comments in the code, that is precisely why it was done.

**Comment by benaadams** [comment]
Its used in ```BufferGeometry``` ```computeOffsets``` which calls ```reorderBuffers``` then adds the offsets here: https://github.com/mrdoob/three.js/blob/dev/src/core/BufferGeometry.js#L1049

**Comment by WestLangley** [comment]
Yes. `CTMLoader` calls

    geometry.computeOffsets();

Related: https://github.com/mrdoob/three.js/issues/5605

**Comment by mrdoob** [comment]
>> the indices are just an incrementing number

> Not so. Notice the indices reset to zero when they get too big.

> ```javascript
indices[ i ] = i % ( 3 * chunkSize );
```

> The index offset accommodates for that.

> ```javascript
indexOffset = i * chunkSize * 3;
```

Ah. True... Sorry, I misunderstood.

**Comment by mrdoob** [comment]
>> And no, the previous code didn't use this for the 65K limit,

> According to the comments in the code, that is precisely why it was done.

That example did. But `WebGLRenderer` internally didn't use this. `WebGLRenderer` split the geometry in different sub-geometries.

**Comment by mrdoob** [comment]
As I said in #5605, I'll remove this code by now and re-implement when someone complains with a reasonable use case. If I got to re-implement I think I would add the `offset` as a property of the index buffer and not per drawcall...

You know... This drawcalls thing is a difficult design... `morphTargets` is similar...

```javascript
var geometry = new THREE.BufferGeometry();
geometry.morphTargets = [
    new THREE.BufferGeometry(), // frame 1
    new THREE.BufferGeometry(), // frame 2
    new THREE.BufferGeometry(), // frame 3
    new THREE.BufferGeometry() // frame 4
];
var mesh = new THREE.MorphMesh( geometry, material );
```

I think in next releases I'll refactor `morphTargets into something like this:

```javascript
var geometries = [
    new THREE.BufferGeometry(), // frame 1
    new THREE.BufferGeometry(), // frame 2
    new THREE.BufferGeometry(), // frame 3
    new THREE.BufferGeometry() // frame 4
];
var mesh = new THREE.MorphMesh( geometries, material );
```

Similarly... for drawcalls, instead of adding sub-logic to a geometry type, it's simpler to add parameters to the geometry type.

```javascript
var positions = new THREE.BufferAttribute();
var geometries = [
    new THREE.BufferGeometry().addAttribute( positions ).setRange( 0, 100 ),
    new THREE.BufferGeometry().addAttribute( positions ).setRange( 100, 400 ),
    new THREE.BufferGeometry().addAttribute( positions ).setRange( 500, 100 ),
    new THREE.BufferGeometry().addAttribute( positions ).setRange( 600, 10 )
];
var mesh = new THREE.Mesh( geometries, material );
```

Something like this would replicate the `drawcalls` functionality but without adding sub-logic to the geometry type.

**Comment by mrdoob** [comment]
However, having multiple geometries do affect the `.raycast` code for instance. So it still needs more explorations.

**Comment by benaadams** [comment]
> new THREE.BufferGeometry().addAttribute( positions ).setRange( 0, 100 )

Sorta touches on InterleavedBuffers; might be a way to unify them?

````javascript
var buffer = new THREE.InterleavedBuffer( new Float32Array( ( 3 + 2 + 3 ) * 1000 ), ( 3 + 2 + 3 ) );

var positions = new THREE.InterleavedBufferAttribute( buffer, 3, 0 );
var uvs = new THREE.InterleavedBufferAttribute( buffer, 2, 3 );
var normals = new THREE.InterleavedBufferAttribute( buffer, 3, 5 );

var geo = new THREE.BufferGeometry();
geo.addAttribute( 'position', positions );
geo.addAttribute( 'uv', uvs );
geo.addAttribute( 'normal', normals );

````

**Comment by benaadams** [comment]
Though might be orthogonal concepts :-/

**Comment by mrdoob** [comment]
Hmmm, the fact that I had to remove `drawcall.index` code from `.raycast()` reassures me that it was the right thing to do... (GPU limitation managed to get into CPU raycasting code)
