### ISSUE TITLE
OBJLoader does not handle N-gons, just quads

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#7005]
Here's the screenshot from 3js.org/editor:
![screen shot 2015-08-16 at 16 25 43](https://cloud.githubusercontent.com/assets/242577/9293662/aafc2b56-4433-11e5-91d5-aa07059f8cae.png)

**Comment by WestLangley** [comment]
Yes, this is a feature. `OBJLoader` does not handle polygonal faces having more than 4 sides.

The work-around is to triangulate the model with a third-party app prior to loading.

**Comment by makc** [comment]
> this is a feature

what exactly does this mean? does not having holes in your model break some existing functionality?

**Comment by WestLangley** [comment]
There is no place for condescending remarks on this board.

The title of your post is a statement of fact. I confirmed your statement, and suggested a work-around for the benefit of anyone else who may read this post.

**Comment by makc** [comment]
sometimes people say "this is a feature" in response to bug reports when they have some other code relying on the bug. so I thought this was the case here, but I see this is just your way of confirmation, sorry I made wrong conclusion.

**Comment by WestLangley** [comment]
Well, in fairness to you, what I was thinking when I wrote "this is a feature" was that, IMO, it is not a bug, in the sense that it is not likely to be fixed. That is my opinion, and @mrdoob may have a different view, of course.

I should have been more explicit. My apologies.

**Comment by mrdoob** [comment]
Supporting n-gons is tricky. I'd complicate the loader much more (we'll need triangulation code). Unless me make the shapes/path triangulation code a bit more abstract/reusable...

**Comment by makc** [comment]
Maybe convex n-gons could be good trade-off? Just a bit better than N < 5.

**Comment by makc** [comment]
Actually, when I split the edge in blender, I expected it to be quad + triangle, or 3 triangles, but instead it created pentagon. I thought to myself, oh well it is going to triangulate prior to export then. But no, it just left pentagons there. I did not even know blender could do pentagons :D

**Comment by benaadams** [comment]
Blender has triangulate built into it

**Comment by makc** [comment]
I know, I just did not know I would need to do it manually.

Looking at #6988 I see that convex assumption is not for everyone :)

**Comment by fractma** [comment]
Handling N-gons open as well the possibility of accepting dirty geometry, IMO a clean geometry based on quads or triangles is better planed topology that suddenly handling with poles and a more complex object.

**Comment by makc** [comment]
do you think there is anything in blender that stops you from making quads non-coplanar? I don't think so. the only "clean" geometry would be triangles.
