### ISSUE TITLE
3js.org/editor is better than me in designing spaceships

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#7006]
[Proof](https://www.youtube.com/watch?v=wBoN6VwpnXQ).

I vaguely recall someone from team saying that using wireframe helper is preferred pattern, so maybe editor should follow that advice?

**Comment by mrdoob** [comment]
Yeah. Wireframe and Multimaterial are the two main thing left to release r72 😅

**Comment by mrdoob** [comment]
Fixed! 0048009f4d2b4bf837b6c2fb4b108295c58484ce
