### ISSUE TITLE
Rotation only applies on last axis used

### ISSUE THREAD

**Issue by jtwebguy** [mrdoob/three.js#7008]
Fist of all great project! congrats to mrdoob and the team.
I just have a question. I'm just a noob in 3d and I can't seem to apply the proper rotation on my balls.

this is my modified function:

 function rotateAroundWorldAxis2(object, radians1, radians2) {

        object.rotWorldMatrix.makeRotationX(radians1).makeRotationZ(radians2);
       // object.rotWorldMatrix;

        // old code for Three.JS pre r54:
        //  rotWorldMatrix.multiply(object.matrix);
        // new code for Three.JS r55+:
        object.rotWorldMatrix.multiply(object.matrix);                // pre-multiply

        object.matrix.copy( object.rotWorldMatrix );

        // old code for Three.js pre r49:
        // object.rotation.getRotationFromMatrix(object.matrix, object.scale);
        // old code for Three.js pre r59:
        // object.rotation.setEulerFromRotationMatrix(object.matrix);
        // code for r59+:
        object.rotation.setFromRotationMatrix(object.matrix);

    }

object is initialized as object.rotWorldMatrix = new THREE.Matrix4();

do you have a solution mrdoob?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

http://stackoverflow.com/questions/31953608/rotate-object-on-specific-axis-anywhere-in-three-js-including-outside-of-mesh/32038265#32038265
