### ISSUE TITLE
Particle size attenutation stops when particle reaches 1px?

### ISSUE THREAD

**Issue by josephrocca** [mrdoob/three.js#7011]
Hi, I'm not sure if this is a bug, or is expected behavior, but I noticed that my particles won't go smaller than 1px not matter how far the camera is away from them. Here's some screen shots to show what I mean:
1. Zoomed in close
   ![particle size 1](https://cloud.githubusercontent.com/assets/1167575/9325220/3c94e09a-45c3-11e5-90b1-ddcd91036792.png)
2. Zoomed out a bit
   ![particle size 2](https://cloud.githubusercontent.com/assets/1167575/9325222/3c97c6c0-45c3-11e5-9992-8814a981a178.png)
3. Zoomed out a lot
   ![particle size 3](https://cloud.githubusercontent.com/assets/1167575/9325221/3c95fade-45c3-11e5-9445-3ee1d0bc7a40.png)

Notice that in the final image, the particles are 1 pixel - basically the same as the medium zoom screen shot.

I guess I would have expected the particles to anti-alias away into nothing at some distance. If I didn't have fog, my whole terrain map would be one big yellow blob at some point.

Cheers :)

EDIT: hmm, the last two screens aren't as clear as on my computer, but hopefully you trust me - the particles are about 1px.

**Comment by mrdoob** [comment]
What OS are you on?

**Comment by josephrocca** [comment]
Ah, sorry:
Windows 10 Pro 64 Bit
Chrome 44.0.2403.155 m
Three.js r71

**Comment by Mugen87** [comment]
> Hi, I'm not sure if this is a bug, or is expected behavior, but I noticed that my particles won't go smaller than 1px not matter how far the camera is away from them.

As I understand it, this is the expected behavior. Drawing points with `gl_PointSize` < 1px does not work, it's the same like drawing lines < 1px. I suggest some kind of LOD mechanism to hide particles at a certain distance.

@WestLangley What do you think about this issue?

**Comment by WestLangley** [comment]
I think this can be closed.
