### ISSUE TITLE
r71: CanvasRenderer not working in IE 10 (compatibility mode)

### ISSUE THREAD

**Issue by IvanTisnyi** [mrdoob/three.js#7014]
Hi there.
I use three.js r71 and experience troubles with CanvasRenderer in IE 10 (compatibility mode).
The issue is exactly the same as #6628
"No error in web console, just blank white". In debugger all three.js methods are executed but there is no image/animation.
In CanvasRenderer.js pixelRation property is 1 by default, so it seems to me is not a problem even if window.devicePixelRatio is undefined, but I still tried to set pixelRatio manually:
var dpr = window.devicePixelRatio || window.screen.deviceXDPI / window.screen.logicalXDPI;
renderer.setPixelRatio(dpr);
It doesn't help.

**Comment by benaadams** [comment]
canvas doesn't work in compatibility mode; add the meta tag to the head:

    <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>

**Comment by IvanTisnyi** [comment]
Thanks. Issue is closed.
