### ISSUE TITLE
Simple but deep object hierarchy - performance recommendations?

### ISSUE THREAD

**Issue by Richard004** [mrdoob/three.js#7015]
Hi Guys,

We are developing an engineering application which can greatly benefit from the ThreeJs library. The 3D model is hierarchical and generated based on some rules and with a lot of reuse. 

E.g. [SteelHall / Frame / Beam / Flange / Bolt], [Roof / Purlin / Spacer] and so on.

The definition of the scene resembles an OOP way of representation, where you can have a "class" geometry called e.g. "Purlin" and that gets realized through "object" which is a placement of the class in specific local coordinate system. And the whole thing is hierarchical tree, so that class is defined via its own mesh + other internal objects based other classes. 

The goal is to be able to display the scene based on user defined parameters (definition is generated on server) and to be able to "regenerate/update" the scene as quickly as possible based on new definition which comes from the server after update of the parameters.

In some scenarios we want to let the user enter a "Selection Mode" where he can select individual instances of the model graphically.

All works with merging/cloning of objects and generation of Object3D children, but we are experiencing some performance issues once the hierarchy becomes deep. (Say 8-10 levels)

I know that I still have a space for optimizations in how the model is generated from the scene definition, but still I have a feeling that the performance is poor and that I am doing something fundamentally naively wrong.

If someone was really interested in what we are doing and would be willing to contribute by a good advice or consultation I will be happy to explain a much more about our project.

Here are my so far observations:

1) merging of children works good, but takes surprisingly long time on the client (e.g. 5 seconds) and obviously eliminates the "selection mode" possibility. Or am I wrong?

2) cloning of children works better, but the final scene is surprisingly slow.

3) I also observe a large consumption of memory on the client side after the whole regeneration happens several times in a row. Though I may be doing some mistake in scene "cleaning" and regeneration.

4) Because the whole thing is more an engineering schema rather than fotorealistic we use the 3D Lines a lot which does not much help the performance.

5) On our model, the Chrome performance is somehow ok but all others are far behind and almost unusable. That leads me to hypothesis that we do something really inefficient in JavaScript.

6) I was careful about using matrixAutoUpdate = false as much as possible. 

7) To my surprise there was a lot of some "updateShadows" on the call stack during profiling, but would swear that I explicitly disabled shadow casting where it was possible.

ThreeJs is a great library and I am convinced that the potential is limitless while I am able to use a humble sub-fraction in a sub-optimal way so far, thanks to my so-far-short-experience with JavaScript. 

And man, still, our clients say that the effect is impressive already now. 

Do you want to see a link with an example?
But promise that you shall not laugh. 

Richard

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

It is great that you are using three.js, but this is not a help site. You can try stackoverflow if you want, but you are going to have to ask more specific questions and show code. Your post likely will not get a response on SO -- at least as it is currently written. Good luck.
