### ISSUE TITLE
After upgrade r69 to r71 emissive color don't use texture map 

### ISSUE THREAD

**Issue by tormozok** [mrdoob/three.js#7017]
in lambert material frag shader:

```
	#ifdef DOUBLE_SIDED
		if ( gl_FrontFacing )
			outgoingLight += diffuseColor.rgb * vLightFront + emissive;
		else
			outgoingLight += diffuseColor.rgb * vLightBack + emissive;
	#else
		outgoingLight += diffuseColor.rgb * vLightFront + emissive;
	#endif
```
diffuseColor - is already multiplied with texel color, but emissive is not. 

It is BUG? It broke some my models...

r69:
![r69](https://cloud.githubusercontent.com/assets/3148089/9358912/27dc6392-4697-11e5-9fbc-cb2b2a2e0b15.jpg)

r71:
![r71](https://cloud.githubusercontent.com/assets/3148089/9358917/2c5ecfe0-4697-11e5-9461-6310a9baca6a.jpg)

**Comment by WestLangley** [comment]
In three.js r.71, `MeshPhongMaterial` has an `emissive` property and an `emissiveMap` property. 

`emissive` modulates `emissiveMap`, and the result is additive to the total emitted radiance.

`MeshLambertMaterial` has only an `emissive` property.

**Comment by tormozok** [comment]
And MeshLambertMaterial MUST HAVE emissiveMap?...

**Comment by WestLangley** [comment]
Oh, sorry. `emissiveMap` was added in r.72dev. See https://github.com/mrdoob/three.js/commit/db23097853b7b7f82d45d4b0550e4f5b789ac00c.

**Comment by tormozok** [comment]
Will MeshLambertMaterial be contains emissive map?

**Comment by WestLangley** [comment]
> Will MeshLambertMaterial contain an emissive map?

No. It is our intention to keep `MeshLambertMaterial` simple.

> diffuseColor - is already multiplied with texel color, but emissive is not.

In `MeshLambertMaterial`, the texel color is modulated by the ambient light color. Do you have a `THREE.AmbientLight` in your scene?

**Comment by tormozok** [comment]
I wil use Phong material now... Ambient not match for me.
