### ISSUE TITLE
bring collada model to a given size

### ISSUE THREAD

**Issue by nofear87** [mrdoob/three.js#7034]
i will bring a collada model to a user given size...

Maybe with patterns, maybe with scalling only. Are there good solutions to do this?

My actual idea is to implement a bounding box with the given sizes. And then scale the collada until it hits one side of the bounding box.

But maybe there are better solutions.

Hope you can help.

Robert

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
