### ISSUE TITLE
THREE.WebGLProgram: shader error

### ISSUE THREAD

**Issue by mangust404** [mrdoob/three.js#7035]
Three.js revision: 71
Firefox: 39.0, Firefox 40.0, Ubuntu 12.04 LTS x86_64, NVIDIA GeForce 7300 GT

So the error is:
THREE.WebGLProgram: shader error: 0 gl.VALIDATE_STATUS false gl.getPRogramInfoLog Statically used varyings do not fit within packing limits. (see GLSL ES Specification 1.0.17, p111)
(see screenshot)

The problem occurs with MeshPhongMaterial, the MeshBasicMaterial is working fine.

The previous version of firefox worked fine, the last version of Chrome is also works. 
Looks like only Firefox of the versions 39+ are affected.
![screenshot 2015-08-23 01 04 29](https://cloud.githubusercontent.com/assets/7485714/9425559/578e7656-4936-11e5-8d1a-ad1d926535df.png)

**Comment by benaadams** [comment]
What does the output of this say? http://webglreport.com/?v=1

**Comment by mangust404** [comment]
Wow. Incredibly fast :-)
Here we go:
http://awesomescreenshot.com/04956avhf5
http://awesomescreenshot.com/08556avia3

**Comment by mangust404** [comment]
Hooray!
With the webgl.bypass-shader-validation=true in about:config I can see the broken scene now.
But there is a really HUGE message in the console:
http://paste2.org/VCkh27dk

**Comment by benaadams** [comment]
Its reporting a Max Varying Vectors of 0; which means the vertex shader won't be able to pass any data to the fragment shader; which is definitely a problem. 

Its a firefox bug; but I can't see anything in the bug tracker for it.

Could you raise a bug in the Firefox bug tacker? https://bugzilla.mozilla.org/ Include the detail here with  screenshot and screenshot for WebGL 1 that you have from the webglreport?

**Comment by mangust404** [comment]
Ok, here it is: https://bugzilla.mozilla.org/show_bug.cgi?id=1197525
Can I leave this issue until guys from mozilla will handle the problem?
