### ISSUE TITLE
meshFaceMaterial and creating BufferGeometry with fromGeometry()

### ISSUE THREAD

**Issue by vincent-courtalon** [mrdoob/three.js#7038]
I am not sure if it is a bug or intended, but it seems fromGeometry() does not keep materials index from the orignial geometry.

i wanted to create a complex static geometry with merge, and i need a meshFaceMaterial to correctly assign materials to different merged geometry. I saw the issue opened with merge from BufferGeometry, so i opted to create/merge the geometry "normally", and then at the end converting it with fromGeometry() to a bufferGeometry.
If i create a mesh with the original merged geometry, materials are correctly assigned/rendered, but once i convert with formGeometry(), only the first material remains and is affected to all faces...

so, is it normal/expected, or is this not the correct way to do it? it seems a logical way to do it to me.

**Comment by titansoftime** [comment]
I'm in the same boat. They are working on it. #6982

**Comment by poofik** [comment]
If you are looking for simple cube "skybox" panorama effect with r72dev you can achieve it using THREE.ShaderLib['cube']

```javascript
var sides = [
        'panoramas/' + files + '/right.jpg',
        'panoramas/' + files + '/left.jpg',
        'panoramas/' + files + '/top.jpg',
        'panoramas/' + files + '/bottom.jpg',
        'panoramas/' + files + '/front.jpg',
        'panoramas/' + files + '/back.jpg'
];
var cubemap = THREE.ImageUtils.loadTextureCube(sides);
cubemap.minFilter = THREE.LinearFilter;
var shader = THREE.ShaderLib['cube'];
var skyBoxMaterial = new THREE.ShaderMaterial( {
    fragmentShader: shader.fragmentShader,
    vertexShader: shader.vertexShader,
    uniforms: {
        "tCube": { type: "t", value: cubemap },
        "tFlip": { type: "f", value: -1 }
    },
    depthWrite: false,
    side: THREE.BackSide
});
var skybox = new THREE.Mesh(
    new THREE.CubeGeometry(X, Y, Z),
    skyBoxMaterial
);
container.add(skybox);
```

**Comment by vincent-courtalon** [comment]
titansoftime: good news! if multi-material wasn't implemented in bufferGeometry and will be in the future, that explains and will solve my problem later. In the mean time, i will use geometry for my "static" meshes (walls, floor, etc.). converting to bufferGeometry will be easy later for performance gain.
I am afraid i don't understant yet enough the rendering code to try and tinker with bufferGeometry internals myself.

poofik: thanks for the tip, but in my case, it is not a skybox, but a lot for rooms/wall/floor (procedular generation), wich would be more efficient (i suppose) as a merged geometry instead of multiples meshs

**Comment by titansoftime** [comment]
@vincent-courtalon  better news: It works! Current dev build.

Awesome guys =]

**Comment by mrdoob** [comment]
Sorry it took so long to bring this back! 😇

**Comment by vincent-courtalon** [comment]
thank you, this is great news, i will test it soon
