### ISSUE TITLE
Raycaster error using SphereBufferGeometry

### ISSUE THREAD

**Issue by arturitu** [mrdoob/three.js#7040]
If I try to detect the intersection of a SphereBufferGeometry with the raycaster in the new 72dev build appears this error and alert:

THREE.BufferGeometry: .drawcalls has been renamed to .groups.
THREE.BufferGeometry: .addDrawCall() is now .addGroup().

**Comment by kylegmaxwell** [comment]
I fixed this and created a pull request on Friday, but have heard no
response.
https://github.com/mrdoob/three.js/pull/7030
