### ISSUE TITLE
GlobalCompositeOperation (destination-out) is it supported by three js (WEBGL)?

### ISSUE THREAD

**Issue by dev1intellial** [mrdoob/three.js#7042]
I am looking for support destination-out property in three js WEBGL similar as HTML5.

(http://www.w3resource.com/html5-canvas/javascript-solution.php?q=http%3A%2F%2Fjsbin.com%2FaZisula%2F2%2Fembed%3Fhtml%2Cjs%2Coutput&r=Example%20-1%20:%20globalCompositeOperation%20property%20value%20-%20destination-out) 

This example develop in HTML5 canvas but I want to develop the same which define in the link in three js (WEBGL).

How can I achieve this in threejs (WEBGL)? Please help me.

**Comment by WestLangley** [comment]
This question has been posted on SO, if anyone wants to help.

http://stackoverflow.com/questions/32004277/issue-with-set-blending-property-in-threejs
http://stackoverflow.com/questions/32154300/global-composite-operation-using-three-js
http://stackoverflow.com/questions/32180586/globalcompositeoperation-destination-out-is-it-supported-by-three-js-webgl
