### ISSUE TITLE
Multiple uv sets for 1 geometry? 

### ISSUE THREAD

**Issue by laetitiakami** [mrdoob/three.js#7044]
Hello,

I would like to build a vertex shader with 1 texture map but  multiple uv sets.
So far, I stored the differents UV sets in FaceVertexUvs[0] and FaceVertexUvs[1]. 

However, in the vertex shader, I can access only the first uv set using "vUv".

varying float vUv;
void main() {
(...)
  vUv = uv;
(...)
}

It seems like 'uv' is something magical from threejs. Does something like uv2, uv3 exists? I need something to access the uv mapping in FaceVertexUvs[1].

My goal is to build a house with wall using part of a texture, and windows in another part of the same texture, and blend both.

Is it the correct way to do it? In which part of three.js source code is that magical 'uv' set?

Thank you in advance for your answer!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
