### ISSUE TITLE
mesh contain buffergeometry do not show the material which contain canvas

### ISSUE THREAD

**Issue by YingshanDeng** [mrdoob/three.js#7051]
I want to use buffergeometry to reduce memory. But finally, the mesh not show anything. the mesh material contain a canvas. How to solve, thanks :)   (r71)

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
