### ISSUE TITLE
Games from Gemioli

### ISSUE THREAD

**Issue by dimanux** [mrdoob/three.js#7052]
Hi,

I'm glad to present our new games made with awesome Three.js engine!

### Rats Cooking
Play at http://gemioli.com/ratscooking/html5/gemioli/
Video at http://www.youtube.com/watch?v=jRk1RxQd4I0

### Top Shootout: The Pirate Ship
Play at http://gemioli.com/thepirateship/html5/gemioli/
Video at http://www.youtube.com/watch?v=2f7qIqdPxHQ

### Top Shootout: The Saloon
Play at http://gemioli.com/thesaloon/html5/gemioli/
Video at http://www.youtube.com/watch?v=CkH4LiNsEo0

Thanks to all contributors!
Dmitriy

**Comment by mrdoob** [comment]
Super nice! Starting to get pretty polished 😀
