### ISSUE TITLE
CubeCamera not rendering correctly in very dynamic situations.

### ISSUE THREAD

**Issue by sjpt** [mrdoob/three.js#7056]
Under some situations where 
1) CubeCamera.updateCubeMap() is called dynamically
2) the cube scene uses a MeshFaceMaterial
3) the underlying materials are MeshBasicMaterial, using the map feature
4) the maps are reassigned dynamically
then the individual maps are not properly rendered but all faces are rendered with the same map (the last map of the array).

This is demonstrated by the program at
http://programbits.co.uk/feedcube/feedcube.html

That includes a patched version of CubeCamera.js.
The patch is not a general solution, but demonstrates code behaviour with and without the bug.  It may fail if there is more than one object in the cube scene, especially if the first is not the 'main' object but some other object (such as the CubeCamera itself).

I don't have enough working knowledge of three.js internals to suggest a proper fix right now. I am looking a bit deeper to see if I have anything to suggest.

**Comment by WestLangley** [comment]
Sorry, I have no idea what I am looking at in your demo. Can you create a simple example that demonstrates your issue?

Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by sjpt** [comment]
Sorry, I had simplified the code almost as much as I could, but still left in confusing content.
I have another version at http://programbits.co.uk/feedcube/feedcubeSimple.html
The code is only marginally simpler, but the visual effect is much easier to follow.

(It is the intentionally confusing content that is the motivation for our interest.)

**Comment by WestLangley** [comment]
We appreciate your bug report, but you are going to have to provide a simpler example.

**Comment by sjpt** [comment]
I'm working on simplifying it, and I think I've found the issue.  I'll report back soonish.

**Comment by sjpt** [comment]
You will find a new (I hope clearer) version at  at http://programbits.co.uk/feedcube/feedcubeSimple.html

The issue was that CubeCamera internal camera matrices somehow escaped proper initialization so all were pointing at the same face.  My patch can easily be inserted into the main CubeCamera initialization code, or it may be worth tracking down WHY the initialization was not happening.

~~~
On a related issue:
I also suggest a clear function as clearing is quite awkward.
Generally cubeCamera.renderTarget is automatically cleared (face at a time) by autoClear,
but as renderer.autoClear is quite global clearing does NOT happen automatically as part of updateCubeMap() in an application where autoClear is set to false.

Or alternatively extra control on the updateCubeMap() call, maybe with clearing on unless explicitly turned off.

Clearing it is actually quite difficult from the external UI as it must be cleared face at a time.
    renderer.setRenderTarget(cubeCamera.renderTarget);
    cubeCamera.clear(renderer);
does not work as I had expected.

**Comment by WestLangley** [comment]
1. Can you please try the dev branch?

2. Yes, as a separate issue, `CubeCamera` should force-clear each face.

    ` renderer.render( scene, cameraNZ, renderTarget, true );`

**Comment by sjpt** [comment]
Yes, it works with the dev branch.
Apologies for not having tried the dev branch before submitting the bug; I will know better in future.

As an aside, part of the reason for my issues is that we are not using three.js in a wholehearted scenegraph style, but rather at a lower level that is still considerably higher than raw WebGL.  Hence not assigning camera to scenes, and needing to run without autoClear.  As this is not the primary focus of three.js, I suspect that is why we are more likely to see issues.

Thank you for the excellent work in creating and maintaining three.js.

**Comment by WestLangley** [comment]
> Yes, as a separate issue, CubeCamera should force-clear each face.
>>renderer.render( scene, cameraNZ, renderTarget, true );

After further thought, I believe that constraining the `CubeCamera` in this way is too restrictive.

I know this is a trade-off, but users who who choose to use the same renderer for rendering the scene and the environment map will have to understand the ramifications of setting the properties `renderer.autoClear`, `renderer.autoClearColor`, etc.

The coding pattern used in the examples is the following:

```javascript
renderer.autoClear = true;
cubeCamera.updateCubeMap( renderer, scene );
renderer.autoClear = false;
```

**Comment by sjpt** [comment]
Yes, not sure which would be best there, especially as I am not a 'typical' scenegraph user.

It might be (have been?) clearer to have a scene.autoClear flag,  though its interaction with renderer.autoClear could be confusing, and almost certainly not worth deprecating renderer.autoClear at this point.

In my 'real' application I knew that the scene used by the CubeCamera was a simple cube, and so prevented depth testing.  Maybe overkill:
'''
cubeCamera.renderTarget.depthBuffer = false
material.depthTest = false;  // for all the 6 materials
material.depthWrite = false;
'''
