### ISSUE TITLE
OrbitControls & Input Range

### ISSUE THREAD

**Issue by Faust2638** [mrdoob/three.js#7058]
Hi,
I am such a new user on Three.js. I am building a webpage with a three.js container with OrbitControls for auto-rotation + trackball of my scene.

I want to add an input range above the Three.js container, a floating div; without any link to the three.js.

I noticed that the input range slider does not move (but clickable), but the scene does; even if I box the renderer in a small part of my webpage.

I tried on the OrbitControls example files, to add an <input range> in the <div id="info"> element and it still doesn't move.

I think it's a conflict with the eventListener on mouse event of OrbitControls, but not sure, as I am a selfmade "devlopper". Is there a way to "debbug" this ?

Thanks

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
