### ISSUE TITLE
Why ColladaLoader.js isn't in the r71 release ?

### ISSUE THREAD

**Issue by boulabiar** [mrdoob/three.js#7059]
I have downloaded the r71 release and haven't found the ColladaLoader inside.
Does this mean it is no more part of the supported importers ?

**Comment by WestLangley** [comment]
Source
https://github.com/mrdoob/three.js/tree/master/examples/js/loaders

Example
https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_collada.html

**Comment by boulabiar** [comment]
Hello?
Have you read my question?
I was asking why it's not in the r71 release when you download the .zip from the website.
I already know and have used the importer.

So, download the .zip from here and show me where is the Colladaloader inside it
http://github.com/mrdoob/three.js/zipball/master

**Comment by WestLangley** [comment]
`/examples/js/loaders/ColladaLoader.js`

**Comment by boulabiar** [comment]
Oh, my bad ! I was searching here
/src/loaders/

I am sorry (-.-)"
