### ISSUE TITLE
how to change colour of only a certain part of an imported 3D object

### ISSUE THREAD

**Issue by Bastcri** [mrdoob/three.js#7061]
hello! I am asking this on behalf of a friend whose English is not so good. He is very technical so please feel free to be as technical as you want in your answer. The question is how to change colour in a portion of an imported 3D object. For example if we have an imported object that is a 3D car how can we change the colour of only the windows? Thanks for your help!

**Comment by tschw** [comment]
This forum is for bug reports and feature requests. Please use use stackoverflow for help.

**Comment by Bastcri** [comment]
ok sorry thanks!

**Comment by Bastcri** [comment]
where can I find stackoverflow? thanks!

**Comment by titansoftime** [comment]
http://stackoverflow.com/questions/tagged/three.js

As a developer, this site will be your best friend.
