### ISSUE TITLE
Let DataTexture default to Nearest filtering

### ISSUE THREAD

**Issue by tschw** [mrdoob/three.js#7062]
Using `DataTexture` with `FloatType` and default filters silently requires yet another extension for the linear filtering.

For that reason, and also as a general matter of clarity, the default should be Nearest filtering. If linear filtering is actually desired, it better be explicit.

Almost a bug, subtle and inconvenient: I once got bitten by it and reading #7060 found that it actually deserves a fix. Don't you want to agree?

The documentation should be updated accordingly and while we're at it could also fix the currently broken markup.

**Comment by tschw** [comment]
Defaulting `.flipY` to `false` could also be a good idea to make this class easier to use....

**Comment by mrdoob** [comment]
Sounds good to me 😊

**Comment by WestLangley** [comment]
And have `generateMipmaps` default to `false`.

**Comment by tschw** [comment]
I would have taken care of it and created this ticket to see whether there are any objections, but @gero3 seems to be on a killing spree these days, so I just did the docs :-).
