### ISSUE TITLE
MeshFaceMaterial and transparency

### ISSUE THREAD

**Issue by MiiBond** [mrdoob/three.js#7066]
This is most likely something that is already known but I thought I'd open an issue anyway, just to make sure.

MeshFaceMaterial currently aren't considered when sorting objects into 'opaque' and 'transparent' and there isn't a simple fix for this since we sort by objects and not by mesh part (i.e. a multi-part mesh with a MeshFaceMaterial might have only one transparent part). I'm sure that there are many related issues as well.

I know that @mrdoob is working on a MultiMaterial solution and I hope that this is considered in the final design.

**Comment by mrdoob** [comment]
Yeah, I thought about this...
Do you think we should add a `boundingSphere` per `group`?

**Comment by MiiBond** [comment]
To be honest, I was actually referring to a problem that no longer exists. I hadn't updated my code and seen your new handling of drawcalls/groups. Before, transparency was only determined for regular materials and not MeshFaceMaterials. Now, it looks like you're handling and rendering things correctly.

However, the issue that you thought I was talking about is valid :) Yes, a boundingSphere should be enough to determine the correct order for sorting the individual transparent groups.
