### ISSUE TITLE
[idea] Official package on NPM.

### ISSUE THREAD

**Issue by trusktr** [mrdoob/three.js#7068]
Once you've [switched to semver](https://github.com/mrdoob/three.js/issues/7067), take advantage of the widely adopted NPM package registry (essentially the defacto standard nowadays from where people get JavaScript packages in a modular way).

There already exists http://npmjs.org/three and http://npmjs.org/three.js. I'm not sure if you're a contributor to either of those (I don't see any usernames that would resemble your real name or mrdoob). It'd be super nice to see an official publication on NPM with semver versioning.

Suggestion, you could bump from 0.71.0 (r71) to 1.0.0 on NPM, signifying the first official release on NPM.

By both switching to semver and publishing semver versions on NPM you'll make Three.js more consumable, you'll help users be able to pick proper versions that won't break their apps, and you'll make it easier for automatic tooling to pick out the proper versions of plugins based on the semver version of Three.js.

**Comment by GGAlanSmithee** [comment]
The three (without .js) npm is published by one of the more frequent contributors to this repo if im not misstanken. Not sure how official it is though. I agree that it makes sense to have an official npm from this repo/mrdoob. Really no reason not to.

**Comment by mrdoob** [comment]
Hmmm, I guess we should try to reach the guy behind https://www.npmjs.com/package/three.js?

**Comment by benaadams** [comment]
Seems to be @nulltask

**Comment by bhouston** [comment]
If @mrdoob makes an npm account, I'll add him as an admin on the npm three package.  I've added others whenever they asked.

The npm three package publishing mechanism is completely within this repo here:

https://github.com/mrdoob/three.js/tree/master/utils/npm

The three npm package is already fairly official with tons of other projects relying on it.  We might as well just keep it going.

I have in the past suggested we adopt semver: https://github.com/mrdoob/three.js/issues/3102

**Comment by bhouston** [comment]
If we wanted to solidy the officialness of the https://www.npmjs.com/package/three repository, we could link to it from the main ThreeJS readme and link to it from the threejs.org page.  This would ensure that it gets even more visibility.

**Comment by GGAlanSmithee** [comment]
@bhouston I'm all for that, I am using the `three` npm package myself

**Comment by mrdoob** [comment]
I think we are in the process of gaining access to the `three.js` package. More news in two weeks max 😊

**Comment by bhouston** [comment]
I'd actually recommend taking over the "three" one rather than getting the "three.js" one because most people on NPM leave out the JS because every project is technically a JS project on NPM.

For example, some of the most popular *.js packages leave out *.js in their NPM package names:

express.js: http://expressjs.com/ --> https://www.npmjs.com/package/express
underscore.js: http://underscorejs.org/ --> https://www.npmjs.com/package/underscore

**Comment by GGAlanSmithee** [comment]
I kind of agree, sine `import three from 'three'` is nicer than 'import three from 'three.js'`

**Comment by mrdoob** [comment]
Hmm... that is a good point...

**Comment by mrdoob** [comment]
However, it's also true that they are also matching the github name:

https://github.com/strongloop/express
https://github.com/jashkenas/underscore

**Comment by trusktr** [comment]
Speaking of matching names across the interwebs, @mrdoob check out [js.org](http://js.org). Maybe you can get the `three` subdomain there. :)

**Comment by mrdoob** [comment]
Hehe! That'd be one more dot than the current url 😉
