### ISSUE TITLE
Suggestion. Descibe all objects.

### ISSUE THREAD

**Issue by AlexeyGapon** [mrdoob/three.js#7078]
It is hard to deal with code without descibing some classes (objects).
For example in renderer there are some objects, webGlObjects, meshGroups and so on but there are no class described for them.
May be it is better to add
THREE.MeshGroup  = { ... }
Ad so on.
What do you think?

**Comment by mrdoob** [comment]
Yes, we're in the process of doing this.

**Comment by AlexeyGapon** [comment]
Great! Thanks!
