### ISSUE TITLE
ambiguity of property 'visible'  - how to keep child lights shining in an invisible parent object

### ISSUE THREAD

**Issue by josefK128** [mrdoob/three.js#7083]
Briefly, it seems the resolution of issue #1524 was that properties set on a
parent node ripple down the branch of children - that is generally good.

A problem is the 'visible' property because when applied to lights and objects
it is ambiguous - a light is never 'visible' in the sense of 'reflecting
photons'. The visible property of lights is overloaded to mean 'does it emit
photons'.

The problem: consider a light made a child of a geometric camera apparatus such
as a sphere, a very common methodology in virtual cinematography - even 
canonical. If the sphere is made 'viewable' for the same diagnostic reason as 
putting axes on objects, then when the apparatus is hidden for 
aesthetic/production reasons, that is: visible=false, the children lights 
'turn off'. It seems that they are no longer considered in the light 
calculation traversal of the scene, as if the rendering traversal and light 
calculation traversal were considered equivalent, just as visible is incorrectly
applied to two different meanings.

In the abstract ideal world lights should have a distinct boolean property like
'on' instead of 'visible'.

However I would never suggest the abstract ideal should inform pre-existing 
code.

What I wonder is if the light calculation tree traversal could step over 
objects which have visible=false to discover possible light children.

Please forgive me if I have misunderstood the underlying implementation 
(which I have not studied), but the lights on my camera apparatus are being 
turned off when the parent apparatus geometry is made visible=false, no matter 
how I simultaneously set the lights with regard to 'visible' or 'intensity'.

Thank you.

By the way - three.js is great step forward for web3d.

**Comment by WestLangley** [comment]
Those are good points. Here are some workarounds:

You can set `light.intensity = 0`, instead of `light.visible = false`.

You can set `mesh.material.visible = false` instead of `mesh.visible = false`.

**Comment by josefK128** [comment]
Thanks for the quick reply:

The first proposed solution necessitates remembering the 
previous light.intensity value since intensity is obviously not boolean.
I think it would work of course - but I am certain you would agree that
it is inelegant. Whatever is done should preferably be boolean - no memory.
Also making an object visible/invisible should have nothing to do
with making its child lights on/off, and vice-versa. Of course, again,
I would never propose interface change.

The second solution seems better - I will look into it. It just seems a
shame to have to descend into a modifying an object material to take the 
place of simply avoiding descending a rendering branch with respect to objects. 
These are two different meanings I think. I also fear that modifying a material 
may cost more than a branch statement - but I may be wrong. If I am wrong then 
it seems that o.material.visible is redundant to o.visible - but at least 
abstractly these should be different.

If it is true that the rendering traversal and the light calculation traversal
passes are incorrectly identified, then maybe this is a more serious problem
than just an inelegant workaround for virtual cinematography.


Thanks again

**Comment by WestLangley** [comment]
Actually, I do not agree with your characterization of what I think.

`object.visible` is inherited in three.js. `material.visible` is not.

If you would like to propose a solution to what you feel is a problem, we will certainly consider it.

**Comment by mrdoob** [comment]
Sounds like what he is suggesting is renaming `.visible` to `.enabled` or something like that.

**Comment by josefK128** [comment]
I wasn't trying to characterize what you thought, or at least that was not
my intention.

My thought was that making an apparatus with light children visible=false
should not turn off the lights.

After a test just now your second solution works very well - thanks. 

Your statement about o.visible being inherited and o.material.visible
not being inherited explains the situation and solution very clearly. 

Using o.material.visible in the apparatus-lights case provides a kind of
inverse way of disambiguating the 'visible' property of being
'seen' (reflecting photons) and the light property of being 'on' (emitting
photons). However I think unknowing developers or artists will be surprised
in future (as I was) when toggling object.visible turns child lights on and off.

Again, I would never suggest an interface change, and I am not suggesting
any changes, but in my opinion 'visible' seems like a property of objects, 
and should be inherited. Something like 'on' (not inherited) would be better 
for lights since they have no material object, and a second distinct property 
would remove them from being affected by inherited object visibility.

However, I am very happy with the present solution and really appreciate
your quick insight to produce a simple workaround.
