### ISSUE TITLE
Removal of WebGLDeferredRenderer?

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#7095]
`WebGLDeferredRenderer` is currently unmaintained and broken. Unless someone steps in and manages to fix it I think I'll have to remove it...

Any takers?

**Comment by bhouston** [comment]
I think we can add WebGLDeferredRenderer features to WebGLRenderer via multiple passes and with WebGL 2.0's ability to have multiple outputs per render.  Thus I won't miss it.  I'd rather focus on just one WebGL renderer than splitting effort across multiple.

**Comment by mrdoob** [comment]
Agreed! Considering that you were the only person that was trying to maintain it, I think I'll go for it.

**Comment by GGAlanSmithee** [comment]
I see this issue got closed, but out of interest is there any ETA on WebGL 2.0? Hard to find any concrete info about it.

**Comment by mrdoob** [comment]
I think they're aiming for end of the year.

**Comment by GGAlanSmithee** [comment]
Cool, not so long, thanks.

**Comment by titansoftime** [comment]
With WebGL 2.0 comes the possibility for occlusion culling yes? Super looking forward to that, though I have no idea about the complexity of implementation.

**Comment by takahirox** [comment]
I've been trying to fix and clean up `WebGLDeferredRenderer` lately.

http://takahirox.github.io/three.js.deferredrendering/examples/webgldeferred_animation.html

https://github.com/takahirox/three.js/blob/WebGLDeferredRenderer/examples/js/renderers/WebGLDeferredRenderer.js

Are you still interested to recover `WebGLDeferredRenderer`?
I think it's not too bad to recover it so far even if we rewrite with WebGL 2.0.
I'll send PR once I'll have done if it's good to you guys.

**Comment by mrdoob** [comment]
Recovering it sounds good to me!
The reason it got removed was because no one was maintaining it.

**Comment by takahirox** [comment]
I see. I'll try to make PR soon! :D

**Comment by bhouston** [comment]
@takahirox very nice.  BTW try to reuse the existing packing.glsl functions and add your additional ones to this file: https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/packing.glsl  Less duplication of code will make WebGLDeferredRenderer easier to maintain.

**Comment by bhouston** [comment]
We should probably also try to unify the lighting calculations between deferred and the forward renderer, like pulling stuff out of here: https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/lights_pars.glsl  And you can probably directly re-use the brdfs: https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/bsdfs.glsl

**Comment by takahirox** [comment]
Agreed!

**Comment by jhm-ciberman** [comment]
Does the WwebGLDeferredRenderer actually works? I'm trying to use it for a game with a lot of lights but it doesn't seems to work. It still deprecated/unmantained?

**Comment by Mugen87** [comment]
The renderer is used in the following official example (which seems to work without any issues):

https://threejs.org/examples/webgldeferred_animation

**Comment by jhm-ciberman** [comment]
I want to move the discusion here. It seems that is a bug with the WebGLDeferredRenderer: https://discourse.threejs.org/t/performance-when-handling-large-number-of-lights-in-a-city-game/

**Comment by Mugen87** [comment]
Sorry , but you have not proven a bug yet. Please do not post in this thread anymore.

If there is actually a problem with the renderer, we can open a new issue.
