### ISSUE TITLE
How to change particle system geometry on fly (after removal of sortParticles ) ?

### ISSUE THREAD

**Issue by sarathsaleem** [mrdoob/three.js#7097]
So before r70 
```javascript
particleSystem = new THREE.PointCloud(geometry, shaderMaterial);
particleSystem.sortParticles = true;
```     
and after we update the geometry of the particle , it used to reflect in the particle system.

So after removing `sortParticles`  [commit](https://github.com/mrdoob/three.js/commit/e65e086d49c1b1b0574a1017a9040868b63b9cff), how its going to support this feature ?

**Comment by WestLangley** [comment]
When `PointCloud.sortParticles` was supported, the renderer would automatically push the newly-sorted position buffer to the GPU.

Now, if you update particle positions at the application level, you need to do one of the following:

```javascript
pointCloud.geometry.needsUpdate = true; // THREE.Geometry
```
or

```javascript
pointCloud.geometry.attributes.position.needsUpdate = true; // THREE.BufferGeometry
```

**Comment by sarathsaleem** [comment]
So in an example I am trying to update the position of particle system every second.

Using r69
http://jsfiddle.net/sarathsaleem/qb6960Lx/21/   it works fine as expected. Its using `particleSystem.sortParticles = true; `

 using r71
http://jsfiddle.net/sarathsaleem/qb6960Lx/22/ , it doesn't work even with `particleSystem.geometry.needsUpdate = true;` as @WestLangley told


What else I should do to make it working as expected in r69 ?

**Comment by WestLangley** [comment]
http://jsfiddle.net/qb6960Lx/24/

Please use stackoverflow if you need further help.

**Comment by sarathsaleem** [comment]
Thanks @WestLangley
