### ISSUE TITLE
Bug in InterleavedBuffer render

### ISSUE THREAD

**Issue by MyCADDev** [mrdoob/three.js#7098]
This line in function renderBufferDirect in THREE.WebGLRenderer has a typo

				renderer.render( 0, position.data.count );

should be

				renderer.render( 0, count );

Could you make the fix? 
thanks

**Comment by benaadams** [comment]
Actually is handled a few lines up in the group prep so the if test isn't needed? #7099

**Comment by MyCADDev** [comment]
Thanks for the quick fix!!
