### ISSUE TITLE
OBJLoader strips vertices without faces

### ISSUE THREAD

**Issue by vidstige** [mrdoob/three.js#7102]
The `OBJLoader` strips vertices without any face while loading. I want to load a point cloud without any faces whatsoever, but this obviously does not work. I do realize stripping make perfect sense in most cases. I think a solution where the vertices & faces are loaded naively at first, and then vertices are stripped in a separate step would be helpful. Then it would be fairly easy to make an option to the load function that disables that step.

Mostly unrelated, but from glancing at the code it seems that vertices are duplicated once for each triangle. Any reason for this? Or am I mistaken?

**Comment by mrdoob** [comment]
That's because the OBJ format can store multiple normals and uvs per vertex, WebGL doesn't support that, you can only have 1 normal and 1 uv per vertex. That's why we end up creating a triangle soup.

Not being able to just load the points sucks though... I'll have to study this.

**Comment by vidstige** [comment]
You can, yes. But is it that common? The obj-files I've come across usually have one normal per face and nothing more. Even so, wouldn't it be possible to only duplicate the vertices when you come across per-normal uv or normal? This would make the parsing very easy, fast and reduce the number of vertices by 66% for a typical mesh...

**Comment by mrdoob** [comment]
Try to find files that are only 1/1/1, 2/2/2, 3/3/3 etc

**Comment by WestLangley** [comment]
Regarding the enhancement request, `ObjectLoader` could be modified to support a geometry of points only.

Regarding the secondary issue, `ObjectLoader` could be modified to output indexed `BufferGeometry`, which would reuse vertices whenever the v/t/n triple was repeated.

**Comment by vidstige** [comment]
That would be awesome I think. Making the code only slightly more complicated a lot of people would benefit from the latter improvement, while I and others loading point clouds would benefit from the former.

Should I make a second issue for the second issue?

**Comment by WestLangley** [comment]
> Should I make a second issue for the second issue?

That is not necessary.

Also, I restated the enhancement request for clarification. I do not know if (or when) the requested features will be implemented.

**Comment by mrdoob** [comment]
> Regarding the enhancement request, `ObjectLoader` could be modified to support a geometry of points only.

> Regarding the secondary issue, `ObjectLoader` could be modified to output indexed `BufferGeometry`, which would reuse vertices whenever the v/t/n triple was repeated.

You mean `OBJLoader`, right?

**Comment by WestLangley** [comment]
> You mean OBJLoader, right?

Yes.

**Comment by mrdoob** [comment]
> I want to load a point cloud without any faces whatsoever, but this obviously does not work.

You know, maybe it would be better to just use PCD instead.

http://threejs.org/examples/#webgl_loader_pcd

**Comment by vidstige** [comment]
I could, but it puts three.js to shame that it cannot handle something that would be possible with a proper implementation. Oh, well.

**Comment by mrdoob** [comment]
The community has provided a (imho better) solution for your use case, but your response is to ridiculise the community/library for not providing the solution as you *requested* it.
