### ISSUE TITLE
maxLights does not work

### ISSUE THREAD

**Issue by tormozok** [mrdoob/three.js#7104]
WebGL renderer ignores maxLights parameter. Is it deprecated or spoiled? r71

**Comment by mrdoob** [comment]
How are you using it?

**Comment by tormozok** [comment]
... = new THREE.WebGLRenderer({ maxLights: 1});

**Comment by mrdoob** [comment]
I don't think that was ever a thing...?

**Comment by WestLangley** [comment]
The r.71 documentation is incorrect. `maxLights` is not a constructor parameter. The documentation has been fixed in the dev branch.

**Comment by tormozok** [comment]
@WestLangley How can I restrict lights count now?

**Comment by WestLangley** [comment]
You manage lights at the application level. If you need help, please use stackoverflow.
