### ISSUE TITLE
PointCloud blending : where is the black coming from?

### ISSUE THREAD

**Issue by MarkCaswellSapient** [mrdoob/three.js#7105]
I'm looking at using PointCloud to create a mass of particles that swarm around several points on the screen. I've got this going with the latest version of THREEjs (tested in chrome and firefox on my Mac, chrome and android phone) with a consistent result across all platforms.

The issue I'm getting relates to how the alpha'd PNGs combine: I'm using an additiveAlphaBlending but some (Not all) of the particles appear to have a black circle around them which isn't present in the image file, which is all white with some alpha  (have tried other blending modes with similar results). Here's the code I'm using for the particle material:
```javascript
new THREE.PointCloudMaterial({size:128, opacity:1, sizeAttenuation: true, map:imgMap, alphaTest: 0.05, transparent: true, blending:THREE.AdditiveAlphaBlending  });
```
And here is the end result:
<img width="281" alt="screen shot 2015-09-04 at 09 59 03" src="https://cloud.githubusercontent.com/assets/5758695/9680419/bdbfe894-52ee-11e5-887b-4bc948b27a1e.png">

I've turned off Fog etc which I thought might be tinting the particles but it seems theres still this matte being applied.. Apologies if this is a known issue, or if it's down to my usage of threeJS (fairly new to JS), I couldn't find mention of this bug anywhere. 

Would be grateful for any help.. this project would look so great with the particles making up an undulating white haze. Thanks!

**Comment by tormozok** [comment]
add  depthWrite:false

**Comment by MarkCaswellSapient** [comment]
Wow. Thank you so much tormozok. in three words you have made all my worries disappear!
