### ISSUE TITLE
ThreeJS rc45 How to get mouse position in three.js along z axis

### ISSUE THREAD

**Issue by 631768417** [mrdoob/three.js#7113]
function getXY(cX, cY) {
        var projector = new THREE.Projector();
        var planeZ = new THREE.Plane(new THREE.Vector3(0, 0, 1), 0);
        var mv = new THREE.Vector3(
                (cX / window.innerWidth) * 2 - 1,
                -(cY / window.innerHeight) * 2 + 1,
                0.5);
        var raycaster = projector.pickingRay(mv, camera);
        var pos = raycaster.ray.intersectPlane(planeZ);
        return pos;
    }

was wrong !!!!

**Comment by 631768417** [comment]
Wait for a response 。 thanks!!!!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

Also, update to the current three.js version first.

**Comment by 631768417** [comment]
..................I thought you know
