### ISSUE TITLE
Purpose of THREE.NoShading? Is it vestigial?

### ISSUE THREAD

**Issue by josephrocca** [mrdoob/three.js#7115]
Hey,
I just tried to use `THREE.NoShading` on a `MeshLambertMaterial`, but it just shades it smoothly. I know you can get no-shading using `MeshBasicMaterial`, but I'm just wondering why `THREE.NoShading` exists if it can't be used on other materials?

Here's ean example illustrating an attempt to use `THREE.NoShading` on a lambert material:
http://jsbin.com/depazopuqa/3/edit?html,output
As you can see, it definitely has shading.

I suppose it has some other use? Or is vestigial?

Just curious. Thanks!

**Comment by mrdoob** [comment]
Hmm... Maybe it no longer has a purpose...

**Comment by WestLangley** [comment]
I believe it was added as a constant, but never used.

**Comment by mrdoob** [comment]
Removed. Thanks!

**Comment by tustin2121** [comment]
Heads up: [the documentation for MeshLambertMaterial](http://threejs.org/docs/#Reference/Materials/MeshLambertMaterial) is now broken due to this change. The preview canvas on the page is broken with the following error:

    Error: Object [object Object] has no property "shading"

**Comment by TatumCreative** [comment]
Still need anything from me? It looks like the latest commits cleaned this all up. It's all working as expected on my end on Firefox and Chrome on my mac.

**Comment by mrdoob** [comment]
@TatumCreative all good! 😊
