### ISSUE TITLE
minor texture load break in r72dev

### ISSUE THREAD

**Issue by qwertzui11** [mrdoob/three.js#7118]
at
https://github.com/mrdoob/three.js/blob/dev/src/loaders/ObjectLoader.js#L333
"scope.texturePath" gets ALWAYS added to "url".
url may be a base64 "data:" url. Always adding texture path breaks that feature.
A solution would be checking if "url" starts with "data:" or check if a colon is inside.

**Comment by mrdoob** [comment]
Oh! That solution sounds good to me. Do you mind doing a PR?

**Comment by qwertzui11** [comment]
will do :+1:

**Comment by mrdoob** [comment]
Fixed! 139b39e4a78f7b6ee18f23d48b2f7ef5bc04b8ae
