### ISSUE TITLE
Canvas texture serialization (dev branch)

### ISSUE THREAD

**Issue by rfm1201** [mrdoob/three.js#7120]
If the class CanvasTexture had been added to allow specific canvas stuff to take place, without changing anything for the other kind of texture, you may be interested by a new version of what I suggested in issue #6665.

Here are the modifications and their purpose.

Texture.js need to be modified because, actually, when a scene is restored there is no way to know what kind of texture needs to be restored.
As for geometries, a type property is added to the output object returned by the toJSON method.
At restore time, it is now possible to know if a Texture is a native one or a "derived" one.

All the modifications needed at save time are in CanvasTexture.js.
If there is an object that manages the canvas shown by the CanvasTexture, CanvasTexture has to know it. A new property, called canvasManager, is added to the CanvasTexture class to store the pointer to that object.
The methods copy and toJSON of the CanvasTexture class are modified to manage this new property.

All the modifications needed at restore time are in ObjectLoader.js, in the parseTextures method.
The parseTextures method uses the new type property of the Texture class to create the right kind of Texture. If the type property is undefined, it will create a Texture.
Next, if the texture is a CanvasTexture, parseTextures will try to recreate the canvas as it was at save time.

Of course an adapted canvas management class is needed for the functionality to work. The class MUST implement:
- A toObject method for the serialization. This method is called by the toJSON method of CanvasTexture class. toObject must add two properties to the object it returns:
  - A "type" with its fully qualified name. It’s this type property that will be used at restore time to know what class needs to be instantiate;
  - A "uuid" to uniquely identify the instance serialized;
- A bindToTexture method to allow more than one texture to use the same "canvas". This method is called by the copy method of CanvasTexture and the parseTextures method of the ObjectLoader class;
- A revive method called by the parseTextures method of the ObjectLoader class when a new instance of the canvas management class is needed. This method receives the JSON generated by the toObject method. It must instantiate and initialize a new instance of the class;
- Optionally, a clone method if a copy of the texture should not be bound to the same "canvas". This method is called, when available, by the copy method of CanvasTexture;

So to be able to restore a scene with a still functional canvas you should:
- Create your own canvas management class that does what you need and must implement at least toObject, bindToTexture and revive;
- Instantiate your class;
- Use a CanvasTexture instead of a Texture. Fill its canvasManager property with the instance of your class;
- Bind your instance with the CanvasTexture (use bindToTexture for example), as your instance needs to manage the needsUpdate property of the CanvasTexture.

Now when you save the scene, the CanvasTexture ask your class to serialize its data.

When you restore the scene, the ObjectLoader recreates instances of your class and initializes them with the data serialized by your class.

In this version of the code, many textures may be bound to the same instance of the canvas manipulation class, as shown in the demonstration page added to the pull request bound to this issue.

The code doesn’t manage the change of "canvas" binding for a given texture.
As JavaScript doesn’t have private properties, a change of the canvasManager property can be made without any control. With private property, an accessor will manage the binding with the "canvas" and call bindToTexture and unbindTexture when needed
Here, if some code modifies the canvasManager property, it has to manage the binding of the texture and the "canvas".

Has the code is now in CanvasTexture, it doesn’t work for a regular Texture bind to a canvas. CanvasTexture must be used for this kind of texture.

I know that the names of the properties and methods are not necessary the good ones, but I take any comment on the principle.

**Comment by mrdoob** [comment]
I have the feeling this is a bit over-engineered.

Shouldn't saving `texture.type` and using  `canvas.toDataURL()` be enough?

**Comment by rfm1201** [comment]
canvas.toDataURL() gives you an image not a "working" canvas. To have a working canvas you need a way to "reactivate" the code.

This is a way to do it "inside" three.js and I think it is simpler to do it "inside" three.js, because if it is done "outside" (by the application that uses the library) it is necessary to browse the scene to find the textures and bind them to the "working" canvas. It is also necessary to store more information in the JSON to achieve the same goal, if you don’t modify what three.js writes.

**Comment by Mugen87** [comment]
I think there was no reason to create a new issue but continue the discussion in #6665.
