### ISSUE TITLE
BufferAttribute may not be properly deleted

### ISSUE THREAD

**Issue by arose** [mrdoob/three.js#7123]
BufferAttributes added to a `BufferGeometry` and allocated on GPU upon first render may never be released from WebGLProperties nor from GPU memory. This happens when a `BufferAttribute` is allocated on the GPU but then removed (or overwritten) from the `BufferGeometry`.

``` javascript
var geometry = new THREE.BufferGeometry();
var firstAttribute = new THREE.BufferAttribute( array, 1 );
geometry.addAttribute( "size", firstAttribute );
// render scene including the geometry to allocate memory for the attribute
geometry.removeAttribute( "size" );
// or overwrite it to, for example, grow the buffer
geometry.addAttribute( "size", largerAttribute );
// get rid of geometry
geometry.dispose();
```

The `BufferGeometry.dispose` method correctly cleans up all attributes that are in `BufferGeometry.attributes`. However, `firstAttribute` is not in there anymore when removed or overwritten.

A solution would be to have `BufferGeometry` delete removed/overwritten attributes immediately (this might be a case for requestIdleCallback) or remember them until geometry disposal. Access to the `BufferGeometry.attributes` property should only be allowed via object methods to ensure this. The same holds for the `index` property as a special attribute.

**Comment by larsmoa** [comment]
I was about to report this as well, and made a JSFiddle that demonstrates this issue. See https://jsfiddle.net/ff5zfe1k/9/. On desktop one seems to get away with this, but on mobile (at least IPhone 6S) this crashes after about 600 frames.

**Comment by mrdoob** [comment]
#9512

**Comment by larsmoa** [comment]
Thank you - #9512 is very interesting as I also have an issue with JS holding unnecessary memory. As for this issue (at least the GPU memory part of it) it doesn't really solve anything - does it? Currently I get around this problem by freeing GPU memory for unused `BufferAttributes` manually, but I feel that this should be handled in ThreeJS since resources are allocated here.

**Comment by mrdoob** [comment]
Yeah, I guess we'll have to add a attributes manager in case the user adds an attribute with the same name twice. Whether that's a good practice or not, that I don't know...

**Comment by Mugen87** [comment]
It seems #15308 would also solve this issue.

**Comment by aardgoose** [comment]
@mrdoob @Mugen87 

Is this issue now redundant with weak references to gl buffers and etc as discussed at length recently?

**Comment by Mugen87** [comment]
Not sure. It's still not possible to explicitly dispose individual attributes which is recommended here: https://github.com/mrdoob/three.js/pull/17242#issuecomment-521845876. Hence, I still vote to merge #17063.

**Comment by Mugen87** [comment]
@aardgoose Changed my mind! Even if it's not possible to explicitly release a buffer attribute, the original issue of the OP should be solved because the usage of `WeakMap`.
