### ISSUE TITLE
OpenGL error trying to render custom texture with custom geometry

### ISSUE THREAD

**Issue by devchakraborty** [mrdoob/three.js#7129]
I have a custom geometry from a Blender import using Collada, and a custom texture using a jpeg.

- The custom geometry renders fine with any simple material (no map set).
- The custom texture renders fine when applied to built-in geometries (e.g. SphereGeometry).
- However, when I try to use the custom texture with the custom geometry to create a mesh, I get the following JS warning:

```
[.WebGLRenderingContext-0x7f993aad7e70]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 1
```

And the mesh ends up transparent.

I have a feeling this might be something really obvious like the mesh not being closed (which I'm not sure about, did a little bit of freehand in Blender). Happy to provide a test case if this isn't simple.

(r0.71.1 imported from npm, ColladaLoader added using three-loaders-collada npm package, running on Chrome 45.0.2454.85 on OS X 10.10.5 with AMD Radeon HD 6490M.)

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
