### ISSUE TITLE
STLLoader faces and vertices not assigned for Binary file

### ISSUE THREAD

**Issue by jgrizou** [mrdoob/three.js#7134]
Is there a reason why when loading a binary stl (using [STLLoader](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/STLLoader.js)) the geometry.vertices and geometry.faces fields (and probably others) are not assigned? It works fine with ascii files.

The mesh displays fine in both cases, but vertices and faces are needed for other libraries, like [Physijs](http://chandlerprall.github.io/Physijs/).

I don't know much about all this, but from the code it seems that at least the vertices are available in the binaryparser: https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/STLLoader.js#L181
```geometry.addAttribute( 'position', new THREE.BufferAttribute( vertices, 3 ) );```.

As it works with ascii file, it is not that much important. It is just a matter of improving loading time using binary files.

**Comment by mrdoob** [comment]
`STLLoader` produces a `BufferGeometry` when parsing a binary file. Try doing:

```javascript
var geometry = new THREE.Geometry().fromBufferGeometry( bufferGeometry );
```

**Comment by jgrizou** [comment]
Oops, my bad.. Works perfectly fine, thanks!
