### ISSUE TITLE
SkinnedMesh clone() method breaks unskinned faces

### ISSUE THREAD

**Issue by Astrak** [mrdoob/three.js#7135]
Cloning `SkinnedMesh`-es breaks faces with unskinned vertices. 

![sans3](https://cloud.githubusercontent.com/assets/10037511/9736044/3f37d28a-563f-11e5-8893-1568ef130c64.png)

I have no idea where it comes from, I have been struggling with it few hours. 

[JSFiddle](http://jsfiddle.net/73368dmm/4/) experiments : 
- comment/uncomment `mesh.clone()` to watch the issue. 
- clue1 ? Triggering the cloning on a `click` event or a `setTimeout` makes it work !! However this is not even a good hack since it doesn't work in bigger scenes, even after seconds. 
- clue2 ? I don't think this hacky solution comes from the thread change : setting the timeout to 0 works in the fiddle but not on my laptop, it needs 2-3ms and more.

**Comment by mrdoob** [comment]
How do I know if it works or not? Commenting `mesh.clone()` as instructed produces the same output...?

**Comment by Astrak** [comment]
Wow, there seems to be something else. I went to the example via smartphone when i saw your message and as you described it is also broken without cloning. What i wrote happened on my laptop 100% of the times. 

The normal result should be this body
![sans3](https://cloud.githubusercontent.com/assets/10037511/9741487/eb24c7a4-565a-11e5-8c41-cbb880b011b8.png)

I'll experiment with it more and edit my post if I have more details.

**Comment by Astrak** [comment]
I finally found ! Wouh. Worked on side projects for 2 weeks because of that. I found that many people also block on what can be called the "Blender JSON exporter's checklist" : https://github.com/mrdoob/three.js/issues/6050, two more that I remember but cannot find now, the present one, and on stackoverflow : [here](http://stackoverflow.com/questions/32685987/getting-animation-to-render-correctly-with-three-js-objectloader?noredirect=1#comment53243030_32685987), [here](http://stackoverflow.com/questions/18752146/blender-exports-a-three-js-animation-bones-rotate-strangely?rq=1), [here](http://stackoverflow.com/questions/24930115/after-loading-a-model-exported-from-blender-in-three-js-skeleton-animations-are?rq=1), [here](http://stackoverflow.com/questions/29678123/trouble-with-blender-exporter-for-three-js) with a quick search.

- Use the last version of the exporter,
- Make sure all vertices are attached to a bone (that solves the present issue), 
- Select the mesh ! (one of the SO question was me stuck because of that, I did not think it would change anything !)
- Set the exporter option `Skeletal Animation` to `Rest`
- Reseting the bones' location/rotation/scale **in pose mode**.

While the four first rules can be randomly found in few moments (for more clever people than me), most of the issues and questions are caused by the position not being reseted, or people not doing it in the pose mode. 

This is a short version of what was first written at https://devmatrix.wordpress.com/2013/02/27/creating-skeletal-animation-in-blender-and-exporting-it-to-three-js/

It am not sure that all those rules are exactly the same right now, someone more experienced than me could confirm.

Since the solutions are duplicated in at least three github issues with this one (still can't find the other posts), three SO answers and this website, I suggest to precise them in the exporter readme and in the docs, in the skinned mesh part, where people may be going on first place.
Or any better place I did not consider.

**Comment by maciek134** [comment]
Seems like this was caused by the Blender JSON exporter and could be closed here?

**Comment by Astrak** [comment]
Definitely. i should have closed the issue long ago
