### ISSUE TITLE
General bugs in dev stream InterleavedBuffer

### ISSUE THREAD

**Issue by MyCADDev** [mrdoob/three.js#7138]
Please consider this as a "place holder" bug.

I noticed a bunch of places which need to be fixed for InterleavedBuffer. For example
1. Intersect / raycast
2. BoundingSphere / BoundingBox calculation
3. In general any place in the code which assumes a position / normal / uv specified by a plain buffer and instead finds an InterleavedBufferAttribute.

I'm aware than @benaadams is working on this stuff. 

Should we contribute fixes to @benaadams fork or directly to this fork?
Wont it be simpler in future to just support InterleavedBuffer and InterleavedBufferAttribute so that we don't have to check everywhere in the code.

**Comment by benaadams** [comment]
> Should we contribute fixes to @benaadams fork or directly to this fork?

to dev branch in @mrdoob fork

**Comment by MyCADDev** [comment]
OK will do.

thanks

**Comment by WestLangley** [comment]
This may be helpful: [How to Contribute to three.js](https://github.com/mrdoob/three.js/wiki/How-to-contribute-to-three.js).
