### ISSUE TITLE
Blender Exporter: Attribute error on scene export

### ISSUE THREAD

**Issue by Materix** [mrdoob/three.js#7141]
Blender 2.75a. Hash: c27589e
Three.js: #7137 (commit: 47e05f8ecc741d194bc295f9a1749aa37bca5753)

1. Open blender 2.75a 
2. Export Start-up file as Three.js (.json)
3. Add to default export settings Scene, Lights, Hierarchy, Materials, Cameras
4. Export

![bug](https://cloud.githubusercontent.com/assets/6151485/9759111/13306b0a-56eb-11e5-8e09-28f05fa3f731.png)

**Comment by antont** [comment]
ah missed that `api/` directory yesterday when fixed that enough to work for me. I guess the options I used didn't make the code to use code from that dir, whatever it is.

can fix that too later today but feel free you or anyone to just remove the ref there, that seems to be the correct way.

**Comment by mrdoob** [comment]
Should be fixe now?

**Comment by antont** [comment]
seems good to me at least and based on search was the only place remaining there.

**Comment by Materix** [comment]
It works good
