### ISSUE TITLE
drap and drop selected objects

### ISSUE THREAD

**Issue by jerrina** [mrdoob/three.js#7142]
hii i want to drag and drop a group of selected objects  in three js. this is my code jsfiddle.net/jerrina/mLdet3c3  after selecting and moving a group last object is coming back to its original location.something is wrong regarding parent-children relation. or updation of all object relatively

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by jerrina** [comment]
i posted in stackoverflow as well .but i didnt get a good response
