### ISSUE TITLE
Add CORS Support for Collada Loader Textures

### ISSUE THREAD

**Issue by krusk** [mrdoob/three.js#7144]
If I load my Collada file from a cross origin location, such as a Web Service, the Collada file comes down but the textures referenced in the Collada file produce the following error:

Uncaught SecurityError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at https://mywebservice.net/blob/Texture_0.png may not be loaded.

In fact, the Collada file briefly loads before disappearing and showing looping through the aforementioned error in the console

I tried loader.setCrossOrigin(''); but it doesn't support this function. Can we add CORS support to the Collada loader so it can pull in the textures? The actual textures (image files) are showing as a GET 200 so they must be getting pulled in, but just not being allowed by three.js.

Here is my stack post if it helps to view current code and Update 1 referencing the setCrossOrigin function not working: http://stackoverflow.com/questions/32469104/three-js-cross-origin-error-loading-related-collada-file-texture

**Comment by erichlof** [comment]
Hi @krusk , I answered on StackOverflow.  Hope that helps!

**Comment by krusk** [comment]
That works! Thanks @erichlof. Should this be added by default to future releases? Or documented in a special CORS section related to Three.JS?

To be clear, here is what I added to the ColladaLoader.js file:

Before the following on line 3717: 

    texture = loader.load( url );

Added:

    loader.crossOrigin = '';

And before the following on line 5203: 

    loader.load( url, function ( image ) {

Added:

    loader.setCrossOrigin('');

**Comment by erichlof** [comment]
Glad that worked!  This situation sounds like it might crop up more often than not, and the fix on StackOverflow is a little tricky.  About updating ColladaLoader.js, let's ping @mrdoob and @gero3 who have recently maintained this file and see what they think.

**Comment by krusk** [comment]
Re-opened and agreed. Thanks for pushing this along.

**Comment by Mugen87** [comment]
`ColladaLoader2` has a public method `.setCrossOrigin()` that solves this issue. Try to use the new loader and open an issue if a feature is missing in the new loader.
