### ISSUE TITLE
if you use BufferGeometry.addIndex() the mesh fails to render

### ISSUE THREAD

**Issue by BenediktS** [mrdoob/three.js#7150]
If i use addIndex instead of addAttribute the resulting mesh doesn't render.

If you use "addAttribute('index', someIndexAttribute) "    it is linked as both:
BufferGeometry.index  and  BufferGeometry.attributes['index'] 

If you use "addIndex (someIndexAttribute)" it is only linked as BufferGeometry.index.

It still looks for this.attributes['index'] in some places. 
If you want it to be linked as BufferGeometry.index and BufferGeometry.attributes.index then you need to add the extra line in addIndex:

```javascript
	addIndex: function ( attribute ) {

		this.index = attribute;
		this.attributes[ 'index' ] = attribute;

	},
```

**Comment by mrdoob** [comment]
> It still looks for this.attributes['index'] in some places. 

Oh! Where?

**Comment by BenediktS** [comment]
Wrong bug report.  
I searched a long time now.  ".addIndex" didn't break three.js it broke some extern code. 

sorry, for the wrong report.
