### ISSUE TITLE
r72  '.addIndex' warnings in console

### ISSUE THREAD

**Issue by erichlof** [mrdoob/three.js#7164]
Hi @mrdoob ,
I'm getting several of these warnings in the console now that I upgraded to r72:
THREE.BufferGeometry: .addIndex() has been renamed to .setIndex().

I don't have any references to that method in my app's code, so I was wondering, could these .addIndex calls have been left inside r72 in multiple places?

btw Thank you (and other big contributors) for your major work and re-factoring done for r72.  Looking forward to what the future brings!

**Comment by mrdoob** [comment]
Ohp! Could you create a jsfiddle for it?

**Comment by mrdoob** [comment]
Ops, reproduced... Fixing!
