### ISSUE TITLE
Blender Exporter not exporting multiple animations in Pose mode

### ISSUE THREAD

**Issue by MattTarquin** [mrdoob/three.js#7165]
Currently the Blender Exporter doesn't seem to be exporting multiple animations in Pose mode.

I have created a simple blend showing a cube with two basic animations, rest and walk.

When I set the armature to rest mode and export, with rest mode selected in the exporter, I get both animations in the exported file and can play either of them. However they are distorted and do not play correctly.

When I export in pose mode the animations play correctly (whichever one I had active at the time of export) but playing the other one simply plays the first again. The exported data for both animations is identical.

here is the exported blend when exported in Pose mode with the walk animation active at the time of export:
http://pastebin.com/ss3dmzwP

Here is the exported blend when exported in Rest mode with the walk animation active at the time of export:
http://pastebin.com/QeeZcCGx

The blend can be found here:
http://www.filedropper.com/jelly

I am using blender 2.75 with the latest version of the exporter.

I am fairly new to blender so while I am fairly sure this is a bug, as I have spent the whole day Googling and playing around, I cannot be 100% sure.

**Comment by MattTarquin** [comment]
Just a quick update to this, I did some further playing around and downloaded some models from blenderswap to test the exporting. I had the same results and also noticed that on export the process would occasionally deform the armature within blender resulting in the model being quite messed up within the pose/object views.

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/6050#issuecomment-140938833

**Comment by MattTarquin** [comment]
Closing this as a duplicate of https://github.com/mrdoob/three.js/issues/6050
