### ISSUE TITLE
r72 No GLSL errors in the editor

### ISSUE THREAD

**Issue by tschw** [mrdoob/three.js#7168]
* Visit http://threejs.org/editor
* Create a box
* Change material to ShaderMaterial
* Edit a shader and type something non-GLSL

No error is visible.

Fixed by #7159.

**Comment by mrdoob** [comment]
I was getting errors...

![screen shot 2015-09-16 at 00 00 05](https://cloud.githubusercontent.com/assets/97088/9891347/f659a27e-5c05-11e5-85b5-55d9f6727e81.png)

But merged your patches anyway 😊

**Comment by mrdoob** [comment]
Thanks!

**Comment by tschw** [comment]
Oh yes, oh no :-). The offline syntax check done by glslprep.js was still working, of course. I should have said "change `vec4` to `vec3`", since it doesn't check types or anything but plain syntax...

**Comment by mrdoob** [comment]
Ah! I see 😊
