### ISSUE TITLE
Out of range vertices with InterleavedBuffer

### ISSUE THREAD

**Issue by rclancey** [mrdoob/three.js#7169]
Version: r72 (163f3ac1c08432d13cdb33bb9ef943f30aa1a54c)
Browser: Chrome 44.0.2403.125 / MacOS 10.9
Description:

When attempting to render with a ShaderMaterial and an InterleavedBuffer, I get the following error in the JS console, with nothing rendered: "glDrawArrays: attempt to access out of range vertices in attribute 0"

This appears to be the result of lines 842-844 in WebGLRenderer.js, which could likely just be removed.

**Comment by maciek134** [comment]
Is this still a problem?

**Comment by mrdoob** [comment]
I guess it's not? Closing...
