### ISSUE TITLE
problem with pyramid threejs geometry

### ISSUE THREAD

**Issue by VadimKalinin** [mrdoob/three.js#7172]
I tried this lesson: http://math.hws.edu/eck/cs424/notes2013/threejs/pyramidIFS.html. Its working fine with three.min.js r59, but with older versions (for example, r71) I see, that pyramids bottom is broken.
For some reason I need to use r71 only. Is this possible to resolve this problem in next three.js relise? 
Thanks, Vadim

**Comment by WestLangley** [comment]
three.js no longer supports quad faces -- only triangles. You have to modify the demo.

**Comment by VadimKalinin** [comment]
Thank you, WestLangley, for your answer. When I replaced in demo "new THREE.Face4( 3, 2, 1, 0)" on "new THREE.Face3( 3, 2, 1),
new THREE.Face3( 1, 0, 3)," all working fine
