### ISSUE TITLE
THREE.StereoEffect (at WebVRManager) and THREE.CubeCamera/THREE.Mirror 

### ISSUE THREAD

**Issue by RuiOrey** [mrdoob/three.js#7173]
This issue is a replicate from borismus/webvr-boilerplate#36

I'm trying to get a mirror effect working correctly in a project that is using  [webvr-boilerplate][1].

I tried two ways (using r72dev and r72):

1. use THREE.Mirror:

        verticalMirror = new THREE.Mirror( renderer, camera, { clipBias: 0.03, textureWidth: 256, textureHeight: 256, color:0x889999 } );

        verticalMirrorMesh = new THREE.Mesh( new THREE.PlaneBufferGeometry( 10, 10 ), verticalMirror.material );
        verticalMirrorMesh.add( verticalMirror );
        verticalMirrorMesh.position.y = 0;
        verticalMirrorMesh.position.z = 10;
        verticalMirrorMesh.rotation.y = 60;
        scene.add( verticalMirrorMesh );

        // Request animation frame loop function
        function animate( timestamp ) {

          verticalMirror.render();

          // Update VR headset position and apply to camera.
          controls.update();
          
          // Render the scene through the manager.
          manager.render( scene, camera, timestamp );

          requestAnimationFrame( animate );

        }

2. use THREE.CubeCamera (based on [Stemkoski's example][2]):

      var cubeGeom = new THREE.CubeGeometry(10, 10, 10, 1, 1, 1);
      mirrorCubeCamera = new THREE.CubeCamera( 0.1, 5000, 1024 );
      // mirrorCubeCamera.renderTarget.minFilter = THREE.LinearMipMapLinearFilter;
      scene.add( mirrorCubeCamera );
      var mirrorCubeMaterial = new THREE.MeshBasicMaterial( { envMap: mirrorCubeCamera.renderTarget } );
      mirrorCube = new THREE.Mesh( cubeGeom, mirrorCubeMaterial );
      mirrorCube.position.set(0,0,10);
          mirrorCube.rotation.y = 60;
      mirrorCubeCamera.position = mirrorCube.position;
      mirrorCubeCamera.rotation = mirrorCube.rotation;
      scene.add(mirrorCube);       

    // Request animation frame loop function
            function animate( timestamp ) {

              mirrorCube.visible = false;
              mirrorCubeCamera.updateCubeMap( renderer, scene );
              mirrorCube.visible = true;

              // Update VR headset position and apply to camera.
              controls.update();
              
              // Render the scene through the manager.
              manager.render( scene, camera, timestamp );

              requestAnimationFrame( animate );

            }

In both cases, the render targets stops updating when activating VR Mode and stereo viewing is active.

The mirror is behind the camera and I set a model spinning to observe the mirror behaviour.

Any thoughts of why this happens and possible way to fix it?

 [example][3] (messy code, sorry for that)

Thanks in advance.

EDIT: Seems the problem is with StereoEffect.js and Mirror.js as I setup a scene using only it  [here][4] based on [this example][5] and the result is the same.

  [1]: https://github.com/borismus/webvr-boilerplate
  [2]: http://stemkoski.github.io/Three.js/Reflection.html
  [3]: http://ruidorey.webfactional.com/
  [4]:http://ruidorey.webfactional.com/stereo_test.html
  [5]:http://threejs.org/examples/webgl_effects_stereo.html

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by RuiOrey** [comment]
isn't this a bug ? stereo effect breaks the mirror

**Comment by mrdoob** [comment]
@RuiOrey it'll be easier to help you if you can provide a test with non-messy code 😉

**Comment by WestLangley** [comment]
If you are not certain it is a three.js bug, we prefer you first seek help on stackoverflow.

If you can demonstrate a three.js bug, please provide a test case so we can reproduce your results. Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by RuiOrey** [comment]
@WestLangley  @mrdoob Sure, I understand and thank you for feedback. I'm new to this things -> github, issues and stuff ... will look to do better interventions.

Cleaned up the code a bit of the example I gave..
  
Also tried adding a mirror to your stereo effect example and still same problem..

![No Stereo](http://ruidorey.webfactional.com/nostereo.png)
[mirror WITHOUT stereo effect ](http://ruidorey.webfactional.com/mirror-test-stereo.html )  
 
![Stereo](http://ruidorey.webfactional.com/stereo.png)
[mirror WITH stereo effect ](http://ruidorey.webfactional.com/mirror-test-stereo.html )  


However I'll insist on stackoverflow!

**Comment by stmaccarelli** [comment]
@RuiOrey  Same problem here, just solved.

@mrdoob Maybe Mirror doesn't like scissor test in StereoEffect.js? or maybe it's because StereoEffects doesn't render using the "main" camera, but using its own StereoCamera, that's not linked to Mirror anyhow?

Anyway, i solved editing the render function of StereoEffects.js, by simply adding `renderer.render( scene, camera );` before scissor test and rendering of the L and R cameras.
BUT, I don't know if it's the best solution

	this.render = function ( scene, camera ) {
		scene.updateMatrixWorld();
		if ( camera.parent === null ) camera.updateMatrixWorld();
		_stereo.update( camera );
		renderer.render( scene, camera ); 

		var size = renderer.getSize();
		renderer.setScissorTest( true );
		renderer.clear();

		renderer.setScissor( 0, 0, size.width / 2, size.height );
		renderer.setViewport( 0, 0, size.width / 2, size.height );
		renderer.render( scene, _stereo.cameraL );

		renderer.setScissor( size.width / 2, 0, size.width / 2, size.height );
		renderer.setViewport( size.width / 2, 0, size.width / 2, size.height );
		renderer.render( scene, _stereo.cameraR );

		renderer.setScissorTest( false );
	};

**Comment by mrdoob** [comment]
@stmaccarelli I thought I fixed this already. Are you using `r75`?

**Comment by stmaccarelli** [comment]
@mrdoob yes, r75

**Comment by mrdoob** [comment]
@stmaccarelli do you mind doing a jsfiddle?

**Comment by stmaccarelli** [comment]
Here it is.
As you'll see this is not a bug, just a confusing behaviour.
http://jsfiddle.net/stmaccarelli/rcmhkbmc/


PS: Note that StereoEffect.js throws a warning: 
THREE.WebGLRenderTarget: .generateMipmaps is now .texture.generateMipmaps.

**Comment by RuiOrey** [comment]
Not sure if this still helps but the way I got it to work was with the tip from @brianpeiris [on so](http://stackoverflow.com/a/32549777/1852032)

**Comment by mrdoob** [comment]
> As you'll see this is not a bug, just a confusing behaviour.

Uh? Maybe I misunderstood... I thought it was broken? What's the confused behaviour?

**Comment by stmaccarelli** [comment]
Using mirror + stereoeffects drives to a confusing behaviour, but once you understand how mirror and stereoeffect work it looks clearer.


A
In a non-stereo setup, if you want a mirror in scene you'll need to
render scene
render mirror
render scene again to have the final result.

In a typical RAF loop, you'll most probably write something like
function draw(){
requestAnimationFrame(draw);
mirror.render();
renderer.render() // because you'll just miss the first render pass for mirror to work)
}
(as seen in the Mirror example)

--
B
in a non-mirror setup, if you want stereoeffect you simply replace
renderer.render() with stereoEffect.render()
as seen in StereoEffect example.

so, putting together the two setups one would normally just mix the two and write
function draw(){
requestAnimationFrame(draw);
mirror.render();
stereoEffect.render()
}

and this will not work, because Mirror needs a rendering pass from the main WebGLRenderer (passed to the Mirror init function), so you'll have to

function draw(){
requestAnimationFrame(draw);
renderer.render()
mirror.render();
stereoEffect.render()
}

**Comment by stmaccarelli** [comment]
this is another, cleaner, solution http://stackoverflow.com/a/32622951/6205171
