### ISSUE TITLE
Blender 2.74 export to three.js json multi animations

### ISSUE THREAD

**Issue by derivou** [mrdoob/three.js#7175]
Hi, I'm trying to export a "cat" to a json file with two animations : walk and jump (like the three.js marine example with lead and squat) . The resulting file is including two animations with the right names "wallk" and "jump" but the animations in the two are the same and actually the one just playing in blender before export. In addition the single exported animation is slightly deformed and not exactly as in Blender. 
I already browsed through similar issues but could not find a solution. Would some one have an idea of what can happen ?  Of course, I ticked all the selections (bones, skinning...) and used the "pose" skeletal animation. Any help would be appreciated.

**Comment by titansoftime** [comment]
You'll need to the rig mode to "rest" and also set the skeletal export option in the export ui to "rest".

This is what works for me.

**Comment by derivou** [comment]
Thanks for this very fast feedback. I tried your proposal and there is some change. It seems now it plays the two animations  but the cat is heavily distorded (I nevertheless can recognize them when played) like what was discussed in issue 6050. So many thanks for your comment which definetely puts me on a right track. I'll go back to issue 6050 to understand why the object is distorded.

**Comment by titansoftime** [comment]
@mrdoob There is some issue here. I too have experienced models that will export ok in pose but distorted in rest (which is required for multiple animations).

**Comment by mrdoob** [comment]
Oh...

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/6050#issuecomment-140938833

**Comment by derivou** [comment]
solved in #6050.
