### ISSUE TITLE
webgl_lights_hemisphere: shadow freezes instead of going away

### ISSUE THREAD

**Issue by BionicRabbit3** [mrdoob/three.js#7177]
http://threejs.org/examples/#webgl_lights_hemisphere
When pressing [D] in this example, the shadow is supposed to be invisible as far as I understand, am I right?
Anyawy, instead, it just freezes...

**Comment by WestLangley** [comment]
A workaround is to set `dirLight.shadowDarkness = 0`.

But it seems reasonable that a light should not cast a shadow if `light.visible` is `false`.

Now that cascading shadows have been removed, perhaps we can maintain a 1-to-1 relationship between shadows and lights.

**Comment by BionicRabbit3** [comment]
I think a 1-to-1 relationship would be best. I would love to see shadows
being the color of the remaining light instead of simply being dark.

**Comment by mrdoob** [comment]
> When pressing [D] in this example, the shadow is supposed to be invisible as far as I understand, am I right?

Yes. This is happening because `THREE.ShadowMap` when looking for light ends up with 0 lights and is not updating/clearing the shadow. We need to fix that 😊

**Comment by mrdoob** [comment]
As per the remaining color issue...
There was some talk about it some months ago: #6420

**Comment by BionicRabbit3** [comment]
From #6420 :
>Regarding implementation, I would replace the current code altogether 😀

Did that happen already? If not, when is it planned for?
I'm kinda excited for that shadow color feature! =)

Anyway, keep up the good work, and just FYI r72 is AMAZING! :D

**Comment by mrdoob** [comment]
> Anyway, keep up the good work, and just FYI r72 is AMAZING! :D

Thanks!

**Comment by mrdoob** [comment]
Fixed in #7321.
