### ISSUE TITLE
lightmap on MeshLambertMaterial

### ISSUE THREAD

**Issue by Astrak** [mrdoob/three.js#7178]
I just read `lightMap` has been removed from `MeshLambertMaterial` in r72. I have a medium-size scene which can render with lightmaps at 60 fps on low devices thanks to r71-`MeshLambertMaterial`. Isn't the use of `MeshPhongMaterial` heavier for that ? Why remove it from that material ? I don't get the point. Anyway thanks for your huge work in r72.

**Comment by MasterJames** [comment]
Do you know how many fps you get with the alternative?

**Comment by Astrak** [comment]
I face an issue with my lightmaps so i can't answer now. However just turning `MeshLambertMaterial` to `MeshPhongMaterial` can make the fps drop on my laptop after few minutes of rendering on certain scenes. While it could render indefinitely initially. 

I loved r71-`MeshLambertMaterial` because more people seem to experience a smooth rendering with it. It is not hard to re-add it on a private version but I don't understand why `lightmap` would not fit it anymore.

**Comment by WestLangley** [comment]
> can make the fps drop on my laptop after few minutes of rendering on certain scenes

I think you should figure out what is causing that.

**Comment by mrdoob** [comment]
I do agree. I'll have a look at bringing `lightMap` back during this cycle. I think it was removed for simplicity, I'll try to understand the problem better.

**Comment by Astrak** [comment]
Fixed in https://github.com/mrdoob/three.js/pull/7821
