### ISSUE TITLE
ShaderMaterial docs out of date

### ISSUE THREAD

**Issue by squarefeet** [mrdoob/three.js#7184]
Hey all,

I'm in the process of updating my particle lib to support r72 and noticed that the [ShaderMaterial docs](http://threejs.org/docs/#Reference/Materials/ShaderMaterial) still have mention of the `attributes` parameter. From what I can gather from the r72 changelog and testing this latest release on my little library, attributes are now removed from ShaderMaterial and should be defined via `BufferGeometry` (well, `BufferAttribute`, anyway). 

Cheers.

**Comment by mrdoob** [comment]
Do you want to give it a go?
https://github.com/mrdoob/three.js/blob/dev/docs/api/materials/ShaderMaterial.html

**Comment by squarefeet** [comment]
Sure, I'll give it a shot! Got my hands a bit full converting from Geometry -> BufferGeometry, but would make a nice break.

**Comment by squarefeet** [comment]
PS. It's only the `attributes` prop that has been removed? Varyings are still okay?

**Comment by mrdoob** [comment]
> PS. It's only the `attributes` prop that has been removed? Varyings are still okay?

Yep!

**Comment by pailhead** [comment]
How is this supposed to be used now? I never actually set any attributes in the material, i just defined the name and type (value:null). 72/3 seem to have broken something.

**Comment by mrdoob** [comment]
> How is this supposed to be used now?

Just define the attributes in the `BufferGeometry`, the renderer will take care of the rest.

> ShaderMaterial.prototype.copy() still has 

>      this.attributes = source.attributes;

Oh, good catch!
