### ISSUE TITLE
Update npm package version

### ISSUE THREAD

**Issue by MusicalCreeper01** [mrdoob/three.js#7191]
@bhouston Can we get r72 added to the npm package? I'm upgrading my project to r72 as I need some of the features it adds.

For now I'm just going to change my references to the mode module, to point to a copy of r72 somewhere else in my project, and I'll switch it back once to npm package is updated :)

**Comment by toxicFork** [comment]
:+1:

**Comment by bhouston** [comment]
done: https://twitter.com/exocortexcom/status/645958150609338369
