### ISSUE TITLE
How to retrieve BufferGeometry or Geometry vertex position after a shader processing?

### ISSUE THREAD

**Issue by ash0080** [mrdoob/three.js#7192]
Sorry for asking this question here, I didn't find a clear answer online.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
