### ISSUE TITLE
Animations exported from Blender only sort-of work

### ISSUE THREAD

**Issue by sent1nel** [mrdoob/three.js#7193]
I exported an object from Blender using the plugin, and imported it into my framework running Three.JS. I found that the object's position will update, but I don't think the rot or scl of the animations are happening properly. The model moves, but only positionally. I apologize for my lack of knowledge, I'm new to 3d / graphics programming.

I've tried using both R72 and R71, but no dice.

Live example: http://sandbox.sent1nel.me/
Code: https://github.com/sent1nel/gamework-es6

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

If you are not certain it is a three.js bug, we prefer you first seek help on stackoverflow.

**Comment by sent1nel** [comment]
For the record, I did.

http://stackoverflow.com/questions/32665180/threejs-animation-geometry-doesnt-update-but-position-does

**Comment by sent1nel** [comment]
But also [#6060]

**Comment by FloydERoberts3** [comment]
Are you bringing over a mesh or an animation ? The group I work with
recently imported a large number of meshes and had no problem with
rotations or translations? You are not trying to bring animation over from
blender correct? Jus the mesh?

**Comment by sent1nel** [comment]
Both the animations and the mesh. Actually, I sorted out my issue. I hadn't realized you have to set a material's skinning mode (`material.skinning = true;`). Now my issue is actually that some of the animations cause some weird mesh distortion.

**Comment by mrdoob** [comment]
I wonder if we should remove the `material.skinning = true` and `material.morphTargets = true`. And just produce the shaders if we find a skeleton in the geometry and morphTargets...
