### ISSUE TITLE
Odd Texture Issue in r72

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#7197]
I'm not really sure what's going on here, but you can see in this fiddle:

http://jsfiddle.net/titansoftime/pawthzr8/

that the texture is a little distorted. This is the only one (that I know of) out of several hundred of our models that has been affected.

This started in r72, it was fine previously.

You can get the model here: http://www.titansoftime.com/utils.php?task=getModel&id=71
And the texture: http://www.titansoftime.com/textures/71_1024.dds

**Comment by mrdoob** [comment]
Is it a problem with the model or the texture? Have you tried with a non-dds texture instead?

**Comment by titansoftime** [comment]
I will give it a shot when I get home from work. Interesting to test, though in production not using a compressed texture is not really an option.

**Comment by mrdoob** [comment]
Something I've just tried... I've tried loading the model in the [editor](http://threejs.org/editor/) and use a random texture in the `map` slot. Then, in the project panel, I switched the renderer to `CanvasRenderer`.

`CanvasRenderer` doesn't do the `new THREE.BufferGeometry().fromGeometry()` so I was double checking if there was a bug there...

So seems like that part is fine.

Did you updated the `DDSLoader`?

**Comment by titansoftime** [comment]
I am using this loader in the fiddle: https://rawgit.com/mrdoob/three.js/dev/examples/js/loaders/DDSLoader.js

**Comment by mrdoob** [comment]
Ah, true.

**Comment by titansoftime** [comment]
This issue does not exist with skinning disabled.

http://jsfiddle.net/titansoftime/53rqpdfv/

Just like #7111. Hmm...

**Comment by mrdoob** [comment]
Updated links to use `r72` instead of `r73dev`:

http://jsfiddle.net/pawthzr8/2/
http://jsfiddle.net/53rqpdfv/2/

**Comment by titansoftime** [comment]
@mrdoob Do you have any idea what caused this bug?

 All I know (thanks to the observation of @arose) is that this issue only affects a material with skinning enabled. Please whoever broke this, take a look at it. I don't even know where to begin, not to mention r72 has a billion commits.

Can we at least get a bug label on this?

**Comment by mrdoob** [comment]
@titansoftime have you tried updating the code to the new animation system?

**Comment by titansoftime** [comment]
I have and unfortunately the issue remains (74dev).

**Comment by mrdoob** [comment]
Do you mind updating the jsfiddles to r74dev? 😇

**Comment by titansoftime** [comment]
Here you are: http://jsfiddle.net/eo0hpjk5/

Old expected behaviour (r71): http://jsfiddle.net/fnanr01f/

I updated the fiddles for #7111 as well.

**Comment by WestLangley** [comment]
Can you reduce your model to just the flag? Or better yet, reproduce the issue with a single quad?

**Comment by titansoftime** [comment]
> Can you reduce your model to just the flag? Or better yet, reproduce the issue with a single quad?

Unfortunately no. I am not an animator or a modeler. I paid for all my models / animations.

**Comment by mrdoob** [comment]
If you don't convert to `BufferGeometry` it seems to render just fine:

http://jsfiddle.net/eo0hpjk5/1/

**Comment by mrdoob** [comment]
My bet is that `SkinnedMesh.normalizeSkinWeights()` expects `skinWeights` to be normalized when using `BufferGeometry`.

**Comment by WestLangley** [comment]
Looks much better if weights are normalized prior to converting to `BufferGeometry`.

r.74dev: http://jsfiddle.net/eo0hpjk5/2/
r.71: http://jsfiddle.net/fnanr01f/

However, now notice that there are slight differences in the animations between versions.

**Comment by titansoftime** [comment]
Closing due to cause of issue being on track to be fixed in #7111.
