### ISSUE TITLE
AMFLoader for three.js

### ISSUE THREAD

**Issue by tamarintech** [mrdoob/three.js#7198]
AMF (Additive Manufacturing File, aka "STL 2.0") is an open standard for storing models and assets for manufacturing.  This format is particularly useful for 3D printing as it is the oldest and most supported format that supports multiple materials.  3D print hosts like Cura and Slic3r support AMF to limited capacity.

AMF is based on a zipped XML document.  More information available here: http://amf.wikispaces.com/

I would like to contribute a loader for the AMF format to three.js so that it can join other formats used in manufacturing tasks such as STL.

Work has been completed on an early AMF loader here - https://github.com/tamarintech/model-viewer/blob/develop/loaders/amfloader.js

The example does not yet meet the standards for mrdoob's coding style and I would very much appreciate a review of my current implementation.  Currently, the AMFLoader function returns two Arrays: geometry[] and materials[].  There is also code that builds an Object3D with child objects.  I am not clear which way to proceed.  This is one of many reasons I would very much appreciate an early review. :)  The code is working and has been used successfully to load the "Drill Parts" complex example from the AMF wikispaces site's demo files.

![drillparts](https://cloud.githubusercontent.com/assets/3681218/9984822/deab4b04-5fe4-11e5-9928-5b63e84ddd1a.png)

**Comment by mrdoob** [comment]
Looks great! I think I would just return `sceneobject`.

**Comment by yomboprime** [comment]
Hello, I have trouble loading some AMF models.

These models simply don't include the xml `color` node into the `material` one. (It is not needed since only the material name is sufficient for manufacturing) This seems a common practice in cad software that supports AMF format (the color tag is optional in the AMF specs)

Since the `color` node is not defined, the parser crashes when parsing the material (when creating a new `THREE.Colour`).

I can propose a PR. Minimal change, just define a default value for the color.

**Comment by tamarintech** [comment]
Thanks!
You're right - the code assumes materials would have colors and that is incorrect.

https://github.com/mrdoob/three.js/pull/7334

**Comment by yomboprime** [comment]
Thank you.

By the way, have you considered supporting per-face colour and material index with `MeshFaceMaterial`?

**Comment by tamarintech** [comment]
Definitely, but the current implementation is slightly tricky.  As I understand it, the current implementation of BufferGeometry doesn't have a color/material/etc index so each individual face would need to be created as new geometry with its own material.  When I get a chance, I'll follow up with someone who knows better than I do to see if that's correct. :)

**Comment by yomboprime** [comment]
I've found a bug. The `volume.materialId` is defined with upper case I, bue then it is used with lower case later, resulting in no materials assigned.

**Comment by tamarintech** [comment]
Indeed.  Thanks for spotting it!
:+1:

**Comment by verybigelephants** [comment]
would it be possible to provide an exporter as well? the format seems to be very useful indeed

**Comment by tamarintech** [comment]
AMF is great.  You may also be interested in 3MF.

An exporter is an awesome idea! :+1:

**Comment by jgphilpott** [comment]
Yes, I would like to see an exporter also!
