### ISSUE TITLE
Warning for BufferGeometry and addGroup

### ISSUE THREAD

**Issue by tamarintech** [mrdoob/three.js#7200]
This error appears when I use BufferGeometry with an index:
Warning: THREE.BufferGeometry: .addDrawCall() is now .addGroup()

**Comment by WestLangley** [comment]
Can you provide the information requested in "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md)?

**Comment by tamarintech** [comment]
The initial report is also somewhat incorrect - that error only appears if you create a wireframe from BufferGeometry in three.js r72.

Line 34,345 of three.js includes a call to geometry.addDrawCall.as part of THREE.WireFrameGeometry.

Does this warrant the extra information from the guidelines?

**Comment by mrdoob** [comment]
Fixed. Thanks!
