### ISSUE TITLE
SmoothShading broken when using BufferGeometry

### ISSUE THREAD

**Issue by dhritzkiv** [mrdoob/three.js#7201]
While working on the code to merge the functionality of `OBJMTLLoader` to `OBJLoader` (related to #7195), I noticed that shading of materials was always flat, even when using `MeshPhongMaterial`, and even when explicitly setting a material's `shading` property (although, by default the materials should use `SmoothShading`).

I believe a live example of this can be seen [here in this three.js example,](http://threejs.org/examples/#webgl_buffergeometry_constructed_from_geometry) which uses `BufferGeometry`, `MeshPhongMaterial`, and explicitly states the use of `SmoothShading`. Note the distinct/non-smoothed faces on the hearts.

Can this be confirmed? I've checked issues and recent commits to dev, but can't find anything relating to this.

**Comment by WestLangley** [comment]
> I believe a live example of this can be seen here in this three.js example,

No. Extruded geometries do not have smooth normals.

You will have to provide another example to demonstrate your point.

**Comment by mrdoob** [comment]
Everything now gets converted to `BufferGeometry` internally, so there are tons of examples showing that `SmoothShading` works. 

In fact, `OBJLoader` produces `BufferGeometry` and, as you can see, `SmoothShading` works:
http://threejs.org/examples/#webgl_loader_obj

**Comment by dhritzkiv** [comment]
Hmm. I must be do something wrong then. Thanks for confirming that it does work!

**Comment by dhritzkiv** [comment]
I believe I've tracked down what was causing my issue: I was calling `geometry.computeVertexNormals()` in my own code, which in r72 causes normals to be (re)calculated. When the geometry is not indexed, this results in unconnected triangles ([as per code comment here](https://github.com/mrdoob/three.js/blob/r72/src/core/BufferGeometry.js#L768)). I'm guessing the unconnected triangles means smoothing can't be achieved, correct?

**Comment by WestLangley** [comment]
Correct, if you use that function to compute the normals.
