### ISSUE TITLE
How to set the light exclude some mesh?

### ISSUE THREAD

**Issue by easyfrog** [mrdoob/three.js#7204]
How to set the light exclude some mesh?

just like: 
```
var light = new THEE.Light(0xffffff);
light.exclude = [mesh1, mesh2, mesh3...];
or
light.include = [mesh1, mesh2 mesh3...]
```

**Comment by weiserhei** [comment]
See https://github.com/mrdoob/three.js/issues/5180 for ideas and current workarounds. I would also prefer some built-in feature for this :+1:
