### ISSUE TITLE
iOS9 Content Blockers prevent TrackBallControls from loading.

### ISSUE THREAD

**Issue by nexflo** [mrdoob/three.js#7213]
Not directly a bug...i will report it anyways as more and more users will be using ios9 content blockers - and this basically breaks pages without the user knowing....

Adding trackball controls brings up:

[undefined] Content blocker prevented frame displaying xxx from loading a resource from xxx/assets/js/lib/controls/TrackballControls.js (require.js, line 34)

Tested on an iPhone6 with iOS9 and crystal content content blocker (nr1. app right now)

**Comment by mrdoob** [comment]
I can see you are using require.js there... Just to make sure, can you try this example?

http://threejs.org/examples/misc_controls_trackball.html

**Comment by nexflo** [comment]
Hey Ricardo,

Yup getting something similar:

[undefined] Content blocker prevented frame displaying http://threejs.org/examples/misc_controls_trackball.html from loading a resource from http://threejs.org/examples/js/controls/TrackballControls.js (misc_controls_trackball.html, line 41)
[undefined] Content blocker prevented frame displaying http://threejs.org/examples/misc_controls_trackball.html from loading a resource from http://threejs.org/examples/js/controls/TrackballControls.js
[Error] TypeError: undefined is not a constructor (evaluating 'new THREE.TrackballControls( camera )')
	init (misc_controls_trackball.html, line 66)
	global code (misc_controls_trackball.html, line 58)

**Comment by nexflo** [comment]
funny...was just thinking if its as simple as the content blocker looking for "tracking" variable....
Might just be the name "track" as its a contentblocker....just tried itand renamed Trackballcontroler to TballController and it works....doh.

Will file a "bug" report on their side..guess that makes more sense....

**Comment by moesphemie** [comment]
stupid content-blocker 😠I wouldn't change anything just because their app isn't intelligent enough to separate tracking from tracking

**Comment by nexflo** [comment]
yup....agree (unless we see its a majority of users using it...and the content blockers arent changing their algorithms)

People might just hit up the glitch...thats why i reported it...so its documented for others and have a fix for it - or at least know where its coming from.

**Comment by Mugen87** [comment]
If similar problems occur with other content or ad blockers in the future, always report a bug to the respective developer site (as @nexflo suggested).

Closing since this is not a `three.js` issue.
