### ISSUE TITLE
Editor, Export Scene generates buggy file

### ISSUE THREAD

**Issue by elephantatwork** [mrdoob/three.js#7214]
The current version of the editor generates on File/Export Scene a buggy .json file that can't be reimported to the editor. 
The error shows up in the JSONLoader.parse where it can't find any vertices.
<img width="997" alt="screen shot 2015-09-22 at 17 48 37" src="https://cloud.githubusercontent.com/assets/1109692/10023407/50a20054-6152-11e5-8727-12d433c25c9b.png">

**Comment by mrdoob** [comment]
#7212
