### ISSUE TITLE
Orient Cube texture according to up vector

### ISSUE THREAD

**Issue by Arlen22** [mrdoob/three.js#7215]
Currently when I import a cube texture into ThreeJS, it expects it's up direction to be Y. In certain cases, the files I have will be Z-up, and I need a way to flip the rest of ThreeJS to be Z-up as well. Currently I do it case by case, and the next case is the cube textures. When I import them as Y-up and then try to map them to Z-up, they will be rotated in different directions.

I was working with the SkyShader from http://localhost/3d/three.js-master/examples/webgl_shaders_sky.html, and thankfully it had an up direction already built into the shader which I was able to change very easily. It would be really useful if THREE.JS core had a Global up direction which everything would default to. 

So this is kind of 2 requests in one.

**Comment by WestLangley** [comment]
There is a default up:

```javascript
THREE.Object3D.DefaultUp = new THREE.Vector3( 0, 1, 0 );
```
