### ISSUE TITLE
Instanced Geometry Documentation

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#7231]
I am interested in using Instanced Geometry to help with things like grass and trees etc.

I see no documentation on this in: http://threejs.org/docs/

Also I've seen InterleavedGeometry as well. I have no idea what this is but would like to know. Again, no mention of it in the docs.

**Comment by mrdoob** [comment]
That part of the API is a bit in the works at the moment.

**Comment by titansoftime** [comment]
Ah, gotcha.

**Comment by Usnul** [comment]
I've looked at the current implementation exactly for foliage implementation and it doesn't seem to work in a straight forward way that would allow you to replace a group of meshes without a writing a custom shader. Looking forward to when it works with standard materials though.

**Comment by titansoftime** [comment]
> I've looked at the current implementation exactly for foliage implementation and it doesn't seem to work in a straight forward way that would allow you to replace a group of meshes without a writing a custom shader.

Ah, bummer.

> Looking forward to when it works with standard materials though.

As am I =]

**Comment by titansoftime** [comment]
I'm going to close this for now as this is all beta stuff.
