### ISSUE TITLE
r72 - JSONLoader and recent changes to custom attributes

### ISSUE THREAD

**Issue by MallorLoU** [mrdoob/three.js#7238]
I was relying heavily on JSONLoader to load meshes exported from blender up until now. Although now I am forced to use BufferGeometry, if I want to use custom attributes. How is this supposed to work together now?

Thanks in advance,
Denis.

**Comment by mrdoob** [comment]
These examples should show how to create custom attributes in r72:

http://threejs.org/examples/#webgl_custom_attributes
http://threejs.org/examples/#webgl_custom_attributes_lines
http://threejs.org/examples/#webgl_custom_attributes_points
http://threejs.org/examples/#webgl_custom_attributes_points2
http://threejs.org/examples/#webgl_custom_attributes_points3

**Comment by MallorLoU** [comment]
Thanks for answering so short noticed.

Perhaps I didn't define my question correctly. What I meant is how do I load .json files now, if I want to use custom attributes. I have a custom made geometry I export to .json and then load with JSONLoader. Then I fill custom attributes, send them to ShaderMaterial and create a Mesh with the geometry JSONLoader built for me and my material.

As I understand in r72 JSONLoader still returns instance of Geometry, but I need BufferGeometry to use custom attributes. So do I need to parse the json myself now and fill it into BufferGeometry?
