### ISSUE TITLE
Self executing method: Matrix4.prototype.decompose

### ISSUE THREAD

**Issue by positlabs** [mrdoob/three.js#7240]
Is there a reason this method is self-executing? 

https://github.com/mrdoob/three.js/blob/master/src/math/Matrix4.js#L947

Not a huge issue, but it's causing IE9 to bork due to lack of support for TypedArray. It runs before I get a chance to do any feature detection.

**Comment by mrdoob** [comment]
It's for creating the internal variables `vector` and `matrix`. For IE9 one should probably add TypedArray shims before loading three.js.

**Comment by positlabs** [comment]
I was trying to avoid the polyfills since we won't actually need them in production. A workaround is to noop.

			if(typeof Float32Array === 'undefined') Float32Array = function(){};
			if(typeof Uint16Array === 'undefined') Uint16Array = function(){};
