### ISSUE TITLE
LensFlare glCopyTexImage2D Error

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#7241]
I am getting the following warning when the lensflare is in view:

``[.WebGLRenderingContext-04B6E2F0]GL ERROR :GL_INVALID_OPERATION : glCopyTexImage2D: ``

http://threejs.org/examples/#webgl_lensflares

EDIT* Neglected to mention that everything still works fine, just a lot of console spam.

**Comment by mrdoob** [comment]
Uh! Weird... I'm not.

**Comment by titansoftime** [comment]
Hmm, it happens on my desktop (GeForce GTX 650), but not on my laptop( Radeon R6).

**Comment by mrdoob** [comment]
Latest drivers and all that?

**Comment by titansoftime** [comment]
> Latest drivers and all that?

You know it.

**Comment by titansoftime** [comment]
In the new chrome version 46.0.2490.71 m the error has been updated to: ``[GroupMarkerNotSet(crbug.com/242999)!:DC450A0C]GL ERROR :GL_INVALID_OPERATION : glCopyTexImage2D:``.

Chrome bug?

**Comment by leitzler** [comment]
No spam in Chrome 45.0.2454.101 (64-bit) OSX 10.11 MBPr late 2013, Intel Iris.

**Comment by titansoftime** [comment]
I'm thinking it's an nvidia/chrome combo thing under win7.

**Comment by titansoftime** [comment]
This issue no longer exists.
