### ISSUE TITLE
The Dynamic Property

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#7247]
`BufferAttribute` and `InterleavedBuffer` have a `dynamic` property, and the method `setDynamic( true )` is called in the examples. However, the setting does not appear to have any effect -- in the examples, at least -- unless something is going on behind-the-scenes.

From the source code, the `dynamic` property must be set to `true` if `updateRange.count` is set. But that property only appears to be used in `http://threejs.org/examples/webgl_gpu_particle_system.html`.

Perhaps this is still under development. What is the purpose of the `dynamic` property in the current implementation?

/ping @benaadams 

(Unrelated: `Geometry.dynamic` is also set in the examples, but that property no longer exits.)

**Comment by benaadams** [comment]
Is used in ```WebGLObjects.js``` when [creating the gpu buffer](https://github.com/mrdoob/three.js/blob/17df4c44c2365ad7649f53e99734ae48848ab646/src/renderers/webgl/WebGLObjects.js#L81) as a hint to whether you will be updating the data

````javascript
var usage = data.dynamic ? gl.DYNAMIC_DRAW : gl.STATIC_DRAW;
````

**Comment by WestLangley** [comment]
Thanks. These hints have always been somewhat mysterious to me.

I am still having a difficult time understanding the logic behind `WebGLObjects.updateBuffer()`... Working on it. : - )
