### ISSUE TITLE
r72: messed up JSON loader

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#7249]
r71: perfect
http://necromanthus.com/Test/html5/Lara_JS.html 

r72: general failure
http://necromanthus.com/Test/html5/Lara_JS_r72.html 

Ricardo, my dear.
In r72 the backward compatibility DOES NOT EXIST !!!

**Comment by leitzler** [comment]
I'd suggest you use the load-function instead in r72.

**Comment by leitzler** [comment]
As in:

    loader.setTexturePath('lara/');
    loader.load('lara/Lara.js', onComplete, onProgress, onError);

**Comment by RemusMar** [comment]
> I'd suggest you use the load-function instead in r72. 

I'm talking about BACKWARD COMPATIBILITY here.

**Comment by leitzler** [comment]
It's a new release, with new features. Don't upgrade unless you have a process to make sure you don't break anything in your code. The only issue here is that the documentation still refers to the removed function.

**Comment by RemusMar** [comment]
> It's a new release, with new features.
> Don't upgrade unless you have a process to make sure you don't break anything in your code.

You continue to miss the main point: 
the BACKWARD COMPATIBILITY is a must in any "new release".

**Comment by leitzler** [comment]
Actually not, I haven't found any documentation that promises 100% backwards compatibility.

In this particular case the interface has been cleaned up. It would have been wrong to keep the old function names. You still find the same functionality, you just have to adapt to the new interface.

No one forces you to use the new release, however if you do, you have to adapt to the changes. That's how software development works.

**Comment by mrdoob** [comment]
@leitzler are you planning on creating a pull request with the docs fixes?

**Comment by leitzler** [comment]
Oh, sorry. Created #7264 and #7265 for master / dev.

**Comment by mrdoob** [comment]
Sweet! The `dev` one is enough.

**Comment by mrdoob** [comment]
Thanks!
