### ISSUE TITLE
r72: ColladaLoader problem

### ISSUE THREAD

**Issue by martynas-b** [mrdoob/three.js#7256]
Hi,

Seems that r72 ColladaLoader.js does't work correctly when you try to load several different collada objects in the same scene. Here are two example pages. One using r71 and another r72 ColladaLoader.js. That's the only difference. r71 looks good and r72 seems messes up between those two collada models even though new loader instances are being created each time.
r71:
http://hafnium.euman.net/lpilot/WebGL/collada_r71.html
r72:
http://hafnium.euman.net/lpilot/WebGL/collada_r72.html

Thanks and sorry If I'm missing something obvious.

**Comment by mrdoob** [comment]
Thanks for reporting this. The current `ColladaLoader` is out of control.
I've started a new `ColladaLoader2` from scratch in the `dev` branch. Will let you know whenever the new loader is able to load these files properly.

**Comment by martynas-b** [comment]
Cool, thanks a lot !
