### ISSUE TITLE
dev (73) PointLight shadows work properly only if shadow is applied to first light added to the scene

### ISSUE THREAD

**Issue by Scharnvirk** [mrdoob/three.js#7260]
I think the new (and awesome!) feature of point lights with shadows has an issue.

I've been playing with the feature using this example: 
three.js-dev/examples/webgl_shadowmap_pointlight.html

and the only thing I did was adding disabling a shadow on existing light and adding a new light (in a most straightforward way):

```javascript
//(...)
pointLight.castShadow = false; //that is the original light, shadow disabled
//(...)

//literally copypasted and added '2' everywhere
pointLight2 = new THREE.PointLight( 0xff0000 );
pointLight2.castShadow = true;
pointLight2.shadowCameraNear = 1;
pointLight2.shadowCameraFar = 30;
pointLight2.shadowDarkness = 0.5;
pointLight2.shadowMapWidth = 2048;
pointLight2.shadowMapHeight = 1024;
pointLight2.shadowBias = 0.01;
scene.add( pointLight2 );
				
var geometry2 = new THREE.SphereGeometry( 0.3, 32, 32 );
var material2 = new THREE.MeshBasicMaterial( { color: 0xff0000 } );
var sphere2 = new THREE.Mesh( geometry2, material2 );
sphere2.castShadow = false;
sphere2.receiveShadow = false;
pointLight2.add( sphere2 );
```

It seems, however, that if the shadow is added on any light which is not the first added to the scene, shadows kind of mess up:

![shadows](https://cloud.githubusercontent.com/assets/11149454/10148404/89a08052-6633-11e5-980c-8a8d82b13cbd.png)

The top example has

```javascript
pointLight.castShadow = false;
pointLight2.castShadow = true;
```

and the bottom one has it inverted (and works okay):

```javascript
pointLight.castShadow = true;
pointLight2.castShadow = false;
```

And if both lights have shadow, then even weirder thing happens:

![shadows2](https://cloud.githubusercontent.com/assets/11149454/10148442/d196966c-6633-11e5-8026-cd56da9eca3d.png)

Local environment: *Chrome 45.0.2454.101 m*, Windows 7 64bit, ASUS Radeon HD 6950 2GB
Behaves the same way on *Firefox 40.0.3* and on *Internet Explorer 11 (11.0.9600.18015)*

**Comment by mkkellogg** [comment]
@Scharnvirk

This is very strange, I will look into this.

**Comment by mrdoob** [comment]
I've updated the builds in the `dev` branch and the small viewport issue is gone (fixed by #7255).

However, I've tried adding 2 lights at the same time, and the shadows in one of them are a little bit off.

![screen shot 2015-09-28 at 19 35 45](https://cloud.githubusercontent.com/assets/97088/10151717/6fc7f162-6618-11e5-8462-2a6677950242.png)

**Comment by mkkellogg** [comment]
@mrdoob @Scharnvirk 

So it looks like these are actually 2 different problems due to 2 different causes:


**1.** The first problem, mentioned by @Scharnvirk,  is due to this line in ```shadowmap_vertex.glsl``` :

```     vec3 fromLight = mvPosition.xyz - pointLightPosition[ i ];```

This line assumes (incorrectly) a 1:1 correspondence between elements in **```pointLightPosition```** and point lights with shadows ( it was assuming MAX_SHADOWS = number of lights in the scene). When the number of lights in the scene does not match the number of lights casting shadows, it looks like **```pointLightPosition```** cannot be used to get the light's position in view space because we don't know the light's index in that array.

I can fix this by resorting to a solution that was previously deemed sub-optimal: repurposing the **```shadowMatrix```** uniform. Using **```shadowMatrix```** to pass the local-to-world transformation matrix of the light to the vertex shader will allow me to calculate the world-space position of the point light without relying on **```pointLightPosition```**.

@tschw @WestLangley I know we agreed that it was not ideal to re-purpose uniforms, but I'm not sure how to get around this one.


**2.** The second problem, mentioned by @mrdoob,  is due to the fact that I'm not sure how to force a uniform update on a material. In ```WebGLShadowMap.js```, when the shadows for multiple point lights are rendered, the position for each is sent to the 'distanceRGBA' shader. When it's time to render the shadows for lights 2, 3, etc.., the renderer ( ```WebGLRenderer.js``` ) does not detect a change in material and so the material's uniforms do not seem to get sent to the GPU again, even thought the uniform **```lightPos```** is updated for each light. How can I force this to happen?

**Comment by tschw** [comment]
@mkkellogg 
1. If a view -> world transform allows you to calculate the world position of the light (from which vector, exactly?), without using `pointLightPosition`, why can't you do the same pre-multiplying with the world -> view transform? I might be missing something...

2.  I guess, `renderer.resetGLState()` would do. However, why/how does it work without for shadows cast by other light sources? Does it really? If so, by controlled mechanics or just by coincidence? In either case, and while you're at it, it might be a good idea to make whatever happens more obvious in the code.

**Comment by mkkellogg** [comment]
@tschw 


1. My thinking was to pass in the light's local-to-world transformation (not the view -> world transform) and multiply it by the origin vector ( 0.0, 0.0, 0.0, 1.0 ). Or I could simply extract components 12, 13, and 14 from the local-to-world matrix. In each case the result would be the world-space position of the light. 

    >  why can't you do the same pre-multiplying with the world -> view transform? 

  Without ```pointLightPosition```, I don't have a source vector to multiply by the world -> view transform.

2.  
   >  However, why/how does it work without for shadows cast by other light sources? Does it really? If so, by controlled mechanics or just by coincidence?

  I am not sure about this. I was hoping you guys could clarify this for me :). I can investigate further.

**Comment by mkkellogg** [comment]
@tschw 

> However, why/how does it work without for shadows cast by other light sources? Does it really? If so, by controlled mechanics or just by coincidence?

So it looks like the function ```setProgram()``` in ```WebGLRenderer.js``` will always execute this line:

``` loadUniformsMatrices( p_uniforms, object ); ```

So it looks like matrix uniforms will always get updated correctly, and I think that is why other light sources don't have this problem that is exhibited by point lights (they don't depend on a custom uniform). Many other uniforms, however, are updated only if the ```refreshMaterial``` flag is set to ```true```. This will only happen if the material being set is different from the existing material, or if the program attached to the material is different from the current program.

So from what I can see, it doesn't look like there is a straight-forward way to force the update. But I am not as familiar with this code as you guys are, so I wanted to double-check.

**Comment by tschw** [comment]
@mkkellogg 
> So from what I can see, it doesn't look like there is a straight-forward way to force the update.

`renderer.resetGLState()` will clear `currentMaterialId` and result in `refreshMaterial` being set and
 a call to `refreshUniformsGeneric` (citing the names from memory).

> My thinking was to pass in the light's local-to-world transformation (not the view -> world transform) and multiply it by the origin vector ( 0.0, 0.0, 0.0, 1.0 ). Or I could simply extract components 12, 13, and 14 from the local-to-world matrix. In each case the result would be the world-space position of the light. 

Plucking the negated position into the fourth column of an identity matrix should give you the vector you need when multiplying with `worldPosition`, so there would be no need for custom code in the vertex shader, correct?

**Comment by mkkellogg** [comment]
@tschw 
>renderer.resetGLState() will clear currentMaterialId and result in refreshMaterial being set and
a call to refreshUniformsGeneric (citing the names from memory).

This indeed seems to work. I needed to move all the GL state code inside the light loop in ```WebGLShadowMap.js``` since I am calling ```_renderer.resetGLState()``` at the end of each iteration.
>Plucking the negated position into the fourth column of an identity matrix should give you the vector you need when multiplying with worldPosition, so there would be no need for custom code in the vertex shader, correct?

This is correct, I tried it out myself and it works fine.

**Comment by tschw** [comment]
@mkkellogg 
Problems all solved?

**Comment by tschw** [comment]
@mkkellogg 

Something else I noticed:
```glsl
// if ( something && something ) breaks ATI OpenGL shader compiler
```
so probably
```glsl
if ( frustumTest || isPointLight )
```
does so too. The built-in GLSL function `any` could be used for a similar workaround, but it's not even necessary restructuring
```glsl
// [ ... checking frustum ]
if ( frustumTest || isPointLight ) {
    if ( isPointLight ) {
        // [...]
    } else {
        // [...]
    }
}
```
into
```glsl
if ( isPointLight ) {
    // [...]
} else {
    // <- check frustum here
    // [...]
}
```
.

**Comment by tschw** [comment]
@mkkellogg 
More incidentals:

The structure suggested in my previous message allows the `#ifdef` stuff to become much more readable and eliminate the large redundant block of code. 

Reading `worldpos_vertex.glsl` and `skinning_vertex.glsl`, `lightToPosition` should probably be the same as `shadowCoord` (that is, also get divided by `.w`). 

The structure suggested in my previous message would also allow to tidy up *all* the code before the conditional without repeating it (which, I guess, is the reason why it's currently where it is):
It's fine to use a variable name for documenting the different meaning of `shadowCoord` in the context of point lights, but I guess the `lightToPosition` variable better lives inside the `if ( isPointLight )` block. Similarly, `texelSizeX` is only needed in the `else` path.

`shadow /= 21.0` could become `shadow *= 1. / 21.` (arithmetic is taken literally).

**Comment by mkkellogg** [comment]
@tschw 

Restructuring is a great idea, and I have a preliminary version [here](https://gist.github.com/mkkellogg/63f11559a9b03fe0d267) if you want to look it over. Like you mentioned, the code becomes more readable, and the duplicated PCF code for point lights is eliminated.

**Comment by tschw** [comment]
@mkkellogg 
> Restructuring is a great idea, and I have a preliminary version here if you want to look it over.

Yep, much better. But while we're at it:

I'd really move all variables to the innermost scope possible and use the invariants we established: Why test for a point light when `! defined POINT_LIGHT_SHADOWS` tells us there can be none? Why calculate the absolute value of `shadowDarkness[ i ]` when we in fact know the sign in the context we use it?

We also don't actually calculate a `shadowColor` but a `shadowMask` (three times). One calculation would do.

The debug code is better implemented using three `if`s or nested `?` ... `:`, instead of an array - the behavior in case `i >= 3` is undefined. Also allows for more compact code and avoids the problems with arrays. I wouldn't be afraid of hard-wired constants in this case and figure having it all in one spot is best.

We don't really have a separate style guide for GLSL, but starting constants with an uppercase character would be consistent.

Finally, I'd try to keep the indentation down, not indenting so much on preprocessor conditionals. When changing indentation it's a good idea to do so in a separate commit. This way, the changes are easy to follow when merging the code.

```glsl
#ifdef USE_SHADOWMAP

	//- float fDepth; (--> if ( inFrustum ) scope)
	float shadowMask = 1.0; // was shadowColor

	for( int i = 0; i < MAX_SHADOWS; i ++ ) {

		float texelSizeY = 1.0 / shadowMapSize[ i ].y;

#ifdef POINT_LIGHT_SHADOWS

		bool isPointLight = shadowDarkness[ i ] < 0.0;

		//- float realShadowDarkness = abs( shadowDarkness[ i ] ); (not really needed)
		//- float shadow = 0.0; (--> inner scopes)

		if( isPointLight ) {

			float negatedShadowDarkness = shadowDarkness[ i ]; // we know it's negative, here

	#if defined( SHADOWMAP_TYPE_PCF ) || defined( SHADOWMAP_TYPE_PCF_SOFT )

			// [...]

	#else // no percentage-closer filtering:

			// [...]

	#endif

		} else {

#endif // POINT_LIGHT_SHADOWS

			// Note: This branch can just use shadowDarkness[ i ] directly 
			// because we know it's positive

			// [ ... frustumTest ... ]

			if ( inFrustum ) {

	#if defined( SHADOWMAP_TYPE_PCF )

				// [...]

	#elif defined( SHADOWMAP_TYPE_PCF_SOFT )

				// [...]

	#else // no percentage-closer filtering:

				// [...]

	#endif

			} // inFrustum

#ifdef POINT_LIGHT_SHADOWS

		}

#endif

...
```

**Comment by mkkellogg** [comment]
@tschw 

Ok, I think I have all your most recent suggestions reflected in the code. The updated gist is [here](https://gist.github.com/mkkellogg/63f11559a9b03fe0d267). Let me know what you think.

One thing I was thinking about doing is getting rid of the gsdXX constants and putting the literal vec3 values directly into the PCF code ( now that the redundant code is gone ). However this would make the unrolled lines even longer, so I'm not sure it's a good idea in terms of readability.

**Comment by WestLangley** [comment]
@mkkellogg 

>We don't really have a separate style guide for GLSL

True, but you can follow the current style

    #if defined(POINT_LIGHT_SHADOWS) -> #if defined( POINT_LIGHT_SHADOWS )

    float dx0 = -1.0 * xPixelOffset; -> float dx0 = - 1.0 * xPixelOffset; // unary operator space

    depthKernel[0][0] -> depthKernel[ 0 ][ 0 ]

    shadowKernel[0] = vec3(lessThan(depthKernel[0], shadowZ )); -> shadowKernel[ 0 ] = vec3( lessThan( depthKernel[ 0 ], shadowZ ) );

And so on.

**Comment by mkkellogg** [comment]
@WestLangley 

> True, but you can follow the current style

I will do my best to update the code to conform to the current style (I wish there were a tool similar to http://zz85.github.io/mrdoobapproves/ to check GLSL code).

**Comment by tschw** [comment]
@mkkellogg 
> The updated gist is here. Let me know what you think.

Reads awesome now! I'd also un-indent the `#if` around the radius, so all preprocessor action is obvious.

> putting the literal vec3 values directly into the PCF code. However this would make the unrolled lines even longer...

Not sure. I think it's fine as-is.

@WestLangley 
75% of the code you cite is actually old code (from before this PR), which doesn't mean it's a bad idea to format it.

**Comment by WestLangley** [comment]
@mkkellogg @tschw OK. Sorry, looking at the gist alone, I didn't separate the new from the old.

**Comment by mkkellogg** [comment]
@tschw @WestLangley 

Ok, I think it's all ready. I did my best to update the formatting to the current style (by eyeballing the code), but it's certainly possible I overlooked something. [Gist](https://gist.github.com/mkkellogg/63f11559a9b03fe0d267) is updated.

**Comment by mrdoob** [comment]
I wouldn't worry too much about formatting. We can fix these things later 😊

**Comment by WestLangley** [comment]
> We can fix these things later

Later never happens. : - )

And who is "we"?

**Comment by mrdoob** [comment]
> And who is "we"?

Me 😁

**Comment by mkkellogg** [comment]
@mrdoob 

Shall I submit the PR with the fixes?

**Comment by mrdoob** [comment]
Yes please!

**Comment by Scharnvirk** [comment]
The company I work in could learn a lot from your approach to solving the issue. Most of our devs complain loudly when someone asks them to clean up and refactor the code around the issue being fixed. 

Big, big thanks guys! 
/me off to check the fix!
