### ISSUE TITLE
r72: ThreeJs Editor can't export object

### ISSUE THREAD

**Issue by Harken91** [mrdoob/three.js#7262]
Hi,
I have been working for a while with the library and the online editor to export 3D objects to json file.
Since the release of the new version I can't seem to find a way to export any kind of models from the command Export Object. I keep getting the error "Cannot read property 'geometries' of undefined" with all the models I used to be able to export.Do you have any suggestions?

thanks

**Comment by mrdoob** [comment]
Could you share any of the models you're getting the error with?

**Comment by Harken91** [comment]
sure, it's a simple sphere created with blender.
https://www.dropbox.com/s/asmzd802omydnyy/SphereCentralPIvot.json?dl=0
using the old editor with r71 works.

**Comment by mrdoob** [comment]
Reproduced. Fixing...

**Comment by Harken91** [comment]
thanks

**Comment by mrdoob** [comment]
Fixed! Thanks for reporting the bug!

**Comment by Harken91** [comment]
you are welcome, thx for all the job you have done.
