### ISSUE TITLE
r72 in node.js - self is not defined

### ISSUE THREAD

**Issue by missingdays** [mrdoob/three.js#7268]
Thanks for adding native amd support! 
But now there is another problem in node.js.
I see this line https://github.com/mrdoob/three.js/blob/a93be86575a9e6ab0a67a0e167af2ea9496d4e49/src/Three.js#L22
in which there is reference to **self**.
In node.js this causes error 
```
Error: Evaluating ./node_modules/three.js/build/three.js as module "three" failed with error: ReferenceError: /srv/missingdays/Projects/ed3/node_modules/three.js/build/three.js:24
if ( self.requestAnimationFrame === undefined || self.cancelAnimationFrame ===
     ^
self is not defined
```
I guess **self** is just safe way of refering to this, but I don't see where **self** is declared.

**Comment by mrdoob** [comment]
As far as I remember is an alternative to `window.` but for situations where there is no `window.` (like in a worker).

**Comment by antont** [comment]
Yep that's it. Quoting MDN:

The Window.self read-only property returns the window itself, as a WindowProxy. It can be used with dot notation on a window object (that is, window.self) or standalone (self). The advantage of the standalone notation is that a similar notation exists for non-window contexts, such as in Web Workers. By using self, you can refer to the global scope in a way that will work not only in a window context (self will resolve to window.self) but also in a worker context (self will then resolve to WorkerGlobalScope.self).

```
var w = window.self;  // w === window
```

from https://developer.mozilla.org/en-US/docs/Web/API/Window/self

**Comment by missingdays** [comment]
So I guess it doesn't make sense to always keep main repository in node-compatibility mode, since it can uglify library pretty fast, but very few people actually need using three.js in node.
So I will fork it and continue patching for node support there.
