### ISSUE TITLE
Collada loader texture update causing Uncaught RangeError: Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by krusk** [mrdoob/three.js#7270]
HI all,

I had posted regarding this issue on StackOverflow here:

http://stackoverflow.com/questions/32750463/angular-or-three-js-not-pulling-image-from-server-but-rather-browser-cache/32766069?noredirect=1#comment53577554_32766069

and received some insights from @mrdoob here:

https://github.com/mrdoob/three.js/issues/7207

However, I tried the patch method recommended and it is still failing. I am not sure if this is something in the Collada loader/three.js that needs to be addressed, and that is why I am reposting here. I put together a plunk where you can see that on the second or so open of the Modal using the patch by @mrdoob , I get a Maximum call stack size exceeded error.

http://plnkr.co/edit/DGZA9LUBZWsLWrmXaaKD

Is this something on my end, and if so, can someone take a look at the plunk/StackOverflow to resolve it, or is there something that should be added/remediated in the Collada loader so box textures refresh without page reload?

Thanks and apologies if this is the wrong place to post this. Unsure if this is a underlying opportunity to improve three.js or how I am implementing it.

K.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

Please respect the policy of this board.

**Comment by krusk** [comment]
I am questioning whether this is a bug, or should be incorporated as a feature. Please re-open until determined it is not either.

**Comment by WestLangley** [comment]
Sorry, it doesn't work that way.

**Comment by krusk** [comment]
That's fair, I will continue working on this issue and follow the guidelines. Any continued assistance through my stack post is greatly appreciated.
