### ISSUE TITLE
emit warning for missing vertex normals when smooth shading is specified?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#7274]
I had to dig in [ExtrudedGeometry source](https://github.com/mrdoob/three.js/blob/master/src/extras/geometries/ExtrudeGeometry.js#L44-L48) to realize what was missing. If there is an opportunity to output this kind of warning once (and not every frame), please consider doing it.

**Comment by mrdoob** [comment]
Are you doing a `ExtrudeGeometry` every frame?

**Comment by makc** [comment]
The warning is not there at all. I was saying that, if you can only show this warning once, do it, and if every frame - don't.

**Comment by mrdoob** [comment]
Sorry, I don't understand what you're referring to. Add a warning in `ExtrudeGeometry`? Or somewhere else?

**Comment by makc** [comment]
somewhere where you have access to both material and geometry. as there is nothing to warn about if flat shading is selected

**Comment by Mugen87** [comment]
I do not vote add this kind of consistency check to renderer. There are similar scenarios in context of invalid/incomplete geometry data (like using a light map without `uv2`) where no warning is logged. If the engine starts to honor this particular issue, other use cases needs to be verified, too.

**Comment by mrdoob** [comment]
Since this was proposed we're now `flatShading` to define the shading.

If anything... we could render the geometry flat shaded when normals are missing and using a lit material?

But I've not heard anyone else mention this issue in all these years...

**Comment by Mugen87** [comment]
> But I've not heard anyone else mention this issue in all these years...

Exactly. I would evaluate this issue differently if more users would have complained about it.

**Comment by mrdoob** [comment]
Yes, I think we can close this one for now.
We can revisit it after the multiple-programs-per-material PR lands and things feel robust.
