### ISSUE TITLE
add union function to BufferAttribute.updateRange

### ISSUE THREAD

**Issue by nraynaud** [mrdoob/three.js#7279]
in between 2 renderings, there might be more than one updates to a BufferAttribute, so we have to either records them in an array and replay them in WebGLObjects.updateBuffer(), or simply do an union of the current updateRange and the new one, but the current API forces the developers to do some accounting on the app side:

``` javascript
var updateRange = this.bufferedGeometry.attributes.position.updateRange;
if(updateRange.count <= 0) {//we could find either -1 or 0 here
    updateRange.offset = startIndex * 3;  // units are risky, the remainder of the BufferAttribute interface talks in steps, not in base element
    updateRange.count = choppedPointAdded * 3;
} else {
    var min  = Math.min(updateRange.offset, startIndex * 3);
    var max = Math.max(updateRange.offset + updateRange.count, startIndex * 3 + choppedPointAdded * 3);
    updateRange.offset = min;
    updateRange.count = max - min;
}
```

**Comment by larsmoa** [comment]
I created a JSFiddle that exposes this issue (https://jsfiddle.net/ff5zfe1k/11/). For desktop one seems to kinda get away with this (as in, it leaks a massive amount of GPU memory, but does not seem to crash). On mobile (tested on iPhone 6S) it crashes quite quickly, i.e. after about 600-700 frames.

I have an application that frequently modifies geometries run time and this issue seems to be the footprint of many instabilities on mobile devices.

**Comment by mrdoob** [comment]
I had to do this yesterday... Maybe we should make `updateRange` a list of ranges instead...

**Comment by larsmoa** [comment]
I guess calling `addAttribute` twice for the same name could be an error, but it should definitely be allowed (and handled) if `deleteAttribute` is called first).

**Comment by mrdoob** [comment]
> I guess calling `addAttribute` twice for the same name could be an error, but it should definitely be allowed (and handled) if `deleteAttribute` is called first.

I do not think this is related to this issue?

**Comment by Mugen87** [comment]
@mrdoob Did you ever encounter another situation where having `updateRange` range as a list was preferable?

If not, I would prefer to close this issue in order to keep `WebGLAttributes` (and `WebGPUAttributes`) simple.
