### ISSUE TITLE
r72: Sphere Geometry > 65536 vertices issues

### ISSUE THREAD

**Issue by theo-armour** [mrdoob/three.js#7288]
I am discovering that with R72 you may include ***many*** more vertices in a mesh than in previous releases and still maintain reasonable performance. (Yay!)

While updating some of my older demos, I have come across a behavior I did not expect.

See this fiddle:

http://jsfiddle.net/theo/gfhyvou3/

It seems that, in r72, when there are over 65,536 vertices in a sphere that a hole is created in the underside of the sphere and the extra vertices position themselves up that hole. This behavior does not seem to occur in previous releases.

Is this an issue with the move to BufferGeometry? If so, should the 65,536 limit be documented? Or is this something that could be fixed?

In any case, thanks for this release that took its time just to be faster.

**Comment by mrdoob** [comment]
Thanks for the heads up Theo! Should be now fixed in the `dev` branch 😁

**Comment by mrdoob** [comment]
By the way, if you want it to generate and perform even faster, use `SphereBufferGeometry` instead 😉

**Comment by theo-armour** [comment]
That was quick! Very R72...

**Comment by theo-armour** [comment]
Cool. I will explore. Assuming I can use what I'm learning with
PlaneBufferGeometry, then my spheres will take on a fast new spin...

**Comment by theo-armour** [comment]
Fix confirmed.
