### ISSUE TITLE
Proposal: de-anonymize constructor names

### ISSUE THREAD

**Issue by arodic** [mrdoob/three.js#7291]
Since all three.js constructors are derived from anonymous functions, the constructor names are represented as empty strings. This makes it difficult to guess what "class" of object we are dealing with in javascript. Before [type property was added to all objects](https://github.com/mrdoob/three.js/commit/2efc87a00d5945bc9158b0474f9b5f4674ace0e3), the only way to find the class was to manually run numerous `if (x instanceof THREE.*)` checks. Type property makes this easier, but it is specific to three.js and might not work with general-purpose tools.

I propose to de-anonymize the constructors by defining them like this:
```
THREE.PerspectiveCamera = function PerspectiveCamera ( fov, aspect, near, far ) {
```
This is a minimal change to three.js. In this case, `myPerspCamera.constructor.name` would return `"PerspectiveCamera"`.

Alternatively, you could add a custom constructor name like this:
```
Object.defineProperty( THREE.PerspectiveCamera, 'name', { value: 'THREE.PerspectiveCamera' } );
```
In this case, `myPerspCamera.constructor.name` would return `"THREE.PerspectiveCamera"`.

**Comment by WestLangley** [comment]
Also, adding function names to closured functions #6859 needs to be completed.

**Comment by mrdoob** [comment]
I like it! Yeah, this is probably how `type` should have been implemented.

I hope not too many people rely on `type`, I wouldn't want to add backwards compatibility code fit this one.

**Comment by arodic** [comment]
Cool. I have something in the works. I will send a PR shortly.

**Comment by arodic** [comment]
Here is a PR with constructor names added #7293

removing `type` will be a bit more tricky since there are some internal dependencies but it shouldn't take much time.

**Comment by mrdoob** [comment]
We have a problem. Closure compiler removes the name from the functions.

**Comment by mrdoob** [comment]
http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250ATHREE%2520%253D%2520%257B%257D%253B%250ATHREE.Test%2520%253D%2520function%2520Test()%2520%257B%250A%257D%253B

**Comment by arodic** [comment]
Oh no! That is a big problem.

**Comment by arodic** [comment]
Unfortunately, it seems like there is no way around this problem according to [this discussion](https://github.com/google/closure-compiler/issues/942).

While it is possible to compile `Object.defineProperty( THREE.Test, 'name', { value: 'Test' } );`, it is ugly code and I wouldn't recommend it. Perhaps it is best to revert #7293?

**Comment by mrdoob** [comment]
Another option would be to change the code to use this pattern instead:

```javascript
THREE = {};

function Test() {
}

Test.prototype = {
    constructor: Test
};

THREE.Test = Test;
```

http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250ATHREE%2520%253D%2520%257B%257D%253B%250A%250Afunction%2520Test()%2520%257B%250A%257D%250A%250ATest.prototype%2520%253D%2520%257B%250A%2520%2520%2520%2520constructor%253A%2520Test%250A%257D%253B%250A%250ATHREE.Test%2520%253D%2520Test%253B

**Comment by arodic** [comment]
In that case, the problem is that we are polluting the global namespace with the function names. Of course, we can wrap everything in another scope... but thats so much code.

**Comment by mrdoob** [comment]
> In that case, the problem is that we are polluting the global namespace with the function names.

Aren't we polluting the global namespace with `THREE.Vector3 = function Vector3(){}` already?

**Comment by mrdoob** [comment]
I guess we're not...

![screen shot 2015-10-06 at 12 38 54](https://cloud.githubusercontent.com/assets/97088/10315277/4f6cb6ae-6c27-11e5-8d78-cb13596c2adf.png)

**Comment by mrdoob** [comment]
UglifyJS seems to be more customisable, but I can't find the right settings:

http://lisperator.net/uglifyjs/#demo

In the settings there is a "Discard unused variable/functions" option. That produces something like `THREE.Vector3 = function E(){}`. Then we have to disable `mangle` and we get `THREE.Vector3 = function Vector3(){}`. But, I think we'll lose quite a bit by disabling mangling.

I wonder if there is a way to disable mangling for function names.

/ping @gero3

**Comment by mrdoob** [comment]
> Perhaps it is best to revert #7293?

Reverted by now...
