### ISSUE TITLE
r72 essentially kills Geometry and harnessing of GPU through GLSL

### ISSUE THREAD

**Issue by jeanlescure** [mrdoob/three.js#7292]
I'm getting the error `THREE.ShaderMaterial: attributes should now be defined in THREE.BufferGeometry instead.` because my shader material is trying to access attributes.

I decide to try and change code to use `BufferGeometry` but then, as per documentation:

>
This class is an efficient alternative to Geometry, because it stores all data, including vertex positions, face indices, normals, colors, UVs, and custom attributes within buffers; this reduces the cost of passing all this data to the GPU. This also makes BufferGeometry harder to work with than Geometry...
>
>
...This makes BufferGeometry best-suited for static objects where you don't need to manipulate the geometry much after instantiating it.
>

This change in r72 does not play well with the usage we've been giving Three.js at the projects I'm overseeing! 

The projects I use Three.js in are built for mobile app environments, we want to **force** GPU usage, **NOT** `reduce the cost of passing all this data to the GPU`.

I've even been focusing on writing articles about this sort of usage in the past months and advocating using Three.js because it allowed (up to r71) to force GPU usage. 

Also countless guides on how to use shaders in Three.js are adamant about using as much GPU as possible to handle geometry transformations, and now all this content is invalidated.

Why you would want to take vertex positions and color data away from GPU is beyond comprehension, _that's_ what the GPU is there for.

Please, bring back the power of the GPU.

**Comment by mrdoob** [comment]
I think you misunderstood the quoted text. Both `Geometry` and `BufferGeometry` use the GPU. The difference is that `BufferGeometry` structure is ready to be uploaded to the GPU.

The cost of passing the data to the GPU refer to using less CPU and Memory, which is what happens when we render `Geometry`.
