### ISSUE TITLE
svg projection of 3d scene

### ISSUE THREAD

**Issue by gedw99** [mrdoob/three.js#7296]
I need to render to a webgl canvas, but then capture the view as SVG.

I was thinking that some sort of combination of raycasting and projection.

there used to be a SVG Rendered, that could take a threejs scene and make it SVG, but that is no longer supported

Any ideas here ?

**Comment by mrdoob** [comment]
Uh? `SVGRenderer` is still alive and kicking!

http://threejs.org/examples/#svg_sandbox

**Comment by gedw99** [comment]
@mrdoob  great - i was not sure it was still supported.

I will give it a shot.

i want to take threejs 3D scenes and re-project them to 2D.  This is only for static, not for anything animated or moving, just to be clear. 
Do you know if there are any restrictions i need to be aware of in terms of what the 3D scene should not do ?

**Comment by mrdoob** [comment]
The main restriction is: no texture support.

**Comment by gedw99** [comment]
of course. They are raster and so very hard to get to vector format.

Phong shading works though ? No texture maps or shaders.

I am doing this serverside, so i wonder if i can hack to get the textures. 
There is code that converts bitmap to SVG around. You can see it used in various tools.
It works when its a restricted problem domain. The SVG ends up being Huge of course.

**Comment by makc** [comment]
[You could have textures](http://jsfiddle.net/2hxxjbty/), but every triangle would need its own because of unique transform. Or, you would need to use projected UV maps + orthographic camera only.

**Comment by gedw99** [comment]
@makc
Thanks.
That's certainly viable restriction.
Do you know where some sample code is showing off that trick.

**Comment by mrdoob** [comment]
> [You could have textures](http://jsfiddle.net/2hxxjbty/), but every triangle would need its own because of unique transform. Or, you would need to use projected UV maps + orthographic camera only.

Yeah. Maybe I did try it at the time (like... 5 years ago) and it was horribly slow (compared to `CanvasRenderer`).

**Comment by makc** [comment]
@gedw99 no, you will have to find someone to write that.

**Comment by gedw99** [comment]
all, thanks for the tips, and @makc the jsbin example.
i see what you mean by the texture as part of the svg.

I will try out a few tests, and see how i go.
