### ISSUE TITLE
TubeGeometry.clone() fails

### ISSUE THREAD

**Issue by jesperll** [mrdoob/three.js#7301]
TubeGeometry.clone() calls TubeGeometry.constructor() with default parameters (path is undefined)
constructor calls FrenetFrames which fails at path.getTangetAt()

var tube = new THREE.TubeGeometry(path, 2, 1, 3, false);
var tubeClone = tube.clone();

**Comment by AVGP** [comment]
I could reproduce the issue and submitted a patch in #7303 to fix it

**Comment by mrdoob** [comment]
Thanks guys!
