### ISSUE TITLE
materials depth example is broken

### ISSUE THREAD

**Issue by kylegmaxwell** [mrdoob/three.js#7311]
I noticed a problem with depth materials in the three.js examples. It is faceted in a strange way.

Broken r72: http://threejs.org/examples/#canvas_materials_depth
![depth-broken-r72](https://cloud.githubusercontent.com/assets/11025081/10372889/06f5afb0-6d9f-11e5-9706-d509e48378e0.png)

Working r71: https://web.archive.org/web/20150630203949/http://threejs.org/examples/#canvas_materials_depth
![depth-working-r71](https://cloud.githubusercontent.com/assets/11025081/10372882/fdadc528-6d9e-11e5-93e2-81cae4d4a643.png)

**Comment by kylegmaxwell** [comment]
I also just tested on dev and the issue is still there.

**Comment by WestLangley** [comment]
Your second example is using r.59?

**Comment by mrdoob** [comment]
Yeah... `MeshDepthMaterial` support was removed long time ago from `CanvasRenderer`. I wonder if anyone every used it for anything.

**Comment by kylegmaxwell** [comment]
@mrdoob Oh, I was looking for examples of depth buffer and missed the fact that this was in the canvas section. 
@WestLangley You might be right, I just grabbed an old version since I knew the current one looks bad. Are the old versions of 3.js hosted anywhere for comparison? I guess I could check out and build off the release tags locally.

Anyways, this is probably low priority then, but is technically broken, so could eventually be fixed or removed. Thanks for the quick response.

**Comment by mrdoob** [comment]
Removed. Thanks!

**Comment by erichlof** [comment]
Hi @kylegmaxwell ,
As for your question about older versions of Three.js being hosted, yes they are - at cdnjs.com
Here's a link:
http://cdnjs.com/libraries/three.js/
Just click on the 'Version' drop-down menu and you can go back all the way to r2! :)

**Comment by kylegmaxwell** [comment]
Thanks!
