### ISSUE TITLE
How do I extract the intersect point (Vector3) of the intersectObjects? 

### ISSUE THREAD

**Issue by ericaokamura** [mrdoob/three.js#7314]
I am trying to find the intersect point between a ray from 'child' and a mesh (child2), using Raycaster:

var raycaster = new THREE.Raycaster();
var meshList = [];
meshList.push(child2);
for (var i = 0; i < child.geometry.vertices.length; i++) {
    var diff = new THREE.Vector3();
    diff.subVectors (child.geometry.vertices[i],child2.position);
    raycaster.set(child.geometry.vertices[i],diff.normalize());
    var intersects = raycaster.intersectObjects( meshList );
    console.log(intersects[0].point);
}

But the above code is giving me error in the last line (console.log(intersects[0].distance)): "TypeError: undefined is not an object (evaluating 'intersects[0].point')".

How can I extract the intersect point between the ray and the 'child2' mesh?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
