### ISSUE TITLE
High poly maya exported geometry with 2d canvas text

### ISSUE THREAD

**Issue by eudorias** [mrdoob/three.js#7315]
Hello ,
Firstly , I love been using three js. But i need little help about what i am trying. 
I have high poly model on maya and i exported it to js and loaded via THREE.JSONLoader() 
its ok so far.

But i need a solution :S 
i want to add text over that model . I tried to 2d canvas filltext and use as texture bla bla. it only fillcolor i cant see my text . I guess the problem is high poly model not a ordinary cube station :)

what must i do ? i dont wanna a solution which use 2d canvas text mapping because i need  colored model over text not just text. also i need to move that text somehow ofc it must be use model geometry while moving.

any solution or ideas about that?

thanks all

sry for english, its not my primary language.

**Comment by makc** [comment]
> I guess the problem is high poly model not a ordinary cube station

why? I mean, how did you arrive to this conclusion
