### ISSUE TITLE
Remove .shadowDarkness?

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#7321]
@MasterJames points out this issue in #7319:

![screen shot 2015-10-09 at 11 56 05](https://cloud.githubusercontent.com/assets/97088/10398782/e3407508-6e7c-11e5-95d3-59bdd6d1b4ab.png)
http://jsfiddle.net/xsgebh0b/5/

Of course, this is a matter of setting `shadowDarkness` to `1` (instead of `0.5`).

![screen shot 2015-10-09 at 11 56 45](https://cloud.githubusercontent.com/assets/97088/10398787/e71e849e-6e7c-11e5-9013-c0c3bd0ee743.png)

Which makes me think that we probably should remove `shadowDarkness` and simplify things. However, I notice that the shadow is 100% black even if the scene has an `AmbientLight` of `0x404040` and makes me think that the shadow step is in the wrong step.

**Comment by Usnul** [comment]
I'm not sure i agree. I use fairly light shadows in my work (0.6 or less) because they are pretty wrong to begin with and when you set darkness to high it stands out too much.

**Comment by WestLangley** [comment]
What @Usnul said.

At least until the time at which the shadowing methodology is replaced.

For now, I prefer this pattern:

    light.shadowDarkness = 0.5 * light.intensity;

**Comment by mrdoob** [comment]
How about we move...

```glsl
#ifdef METAL

	outgoingLight += diffuseColor.rgb * ( totalDiffuseLight + totalAmbientLight ) * specular + totalSpecularLight + totalEmissiveLight;

#else

	outgoingLight += diffuseColor.rgb * ( totalDiffuseLight + totalAmbientLight ) + totalSpecularLight + totalEmissiveLight;

#endif
```

out of `lights_phong_fragment`?

Then, we make `shadowmap_fragment` output only `shadowMask`.

And we create a new `compose_phong_fragment` with this:

```glsl
#ifdef METAL

	outgoingLight += diffuseColor.rgb * ( totalDiffuseLight * shadowMask + totalAmbientLight ) * specular + totalSpecularLight + totalEmissiveLight;

#else

	outgoingLight += diffuseColor.rgb * ( totalDiffuseLight * shadowMask + totalAmbientLight ) + totalSpecularLight + totalEmissiveLight;

#endif
```

And we put this chunk after `shadowmap_fragment`.

I know this isn't the final solution but I think it could be a step in the right direction? At least we solve ambient light and emissive... I think specular wouldn't be correct though, that formula doesn't make sense...

Maybe it should be...

```glsl
#ifdef METAL

	outgoingLight += ( diffuseColor.rgb * ( totalDiffuseLight + totalAmbientLight ) * specular + totalSpecularLight ) * shadowMask + totalEmissiveLight;

#else

	outgoingLight += ( diffuseColor.rgb * ( totalDiffuseLight + totalAmbientLight ) + totalSpecularLight ) * shadowMask + totalEmissiveLight;

#endif
```

But then we lose ambient light again...

**Comment by mrdoob** [comment]
Also... Maybe we should remove shadowmap out of `MeshBasicMaterial`?

**Comment by mrdoob** [comment]
> I'm not sure i agree. I use fairly light shadows in my work (0.6 or less) because they are pretty wrong to begin with and when you set darkness to high it stands out too much.

The idea is to replace `shadowDarkness` with `THREE.AmbientLight`.

**Comment by Usnul** [comment]
do you think it will work with this example?
http://threejs.org/examples/#webgl_shadowmap_viewer

other than that, i think sometimes you may want to have stark contrast in shading of a material because of direct light but still want to tone down the shadows, in which case ambient light will be pretty low while desiring shadowDarkness to be low also.

**Comment by mrdoob** [comment]
> other than that, i think sometimes you may want to have stark contrast in shading of a material because due to direct light but still want to tone down the shadows, in which case ambient light will be pretty low while desiring shadowDarkness to be low also.

But this is hacky and not like light works...

**Comment by mrdoob** [comment]
Ok. So, as far as I understand the proper solution would be to merge shadowmap_fragment into lights_phong_fragment. The reason `shadowmap_fragment` was done like that probably was so we can reuse the same code with `MeshLambertMaterial` and `MeshBasicMaterial`. The compromise is that we get shadows that work in all materials but are just black masks...

/cc @tschw @mkkellogg

**Comment by Usnul** [comment]
it is hacky and not like the light works, but it is a good way to cover up hacks like shadow maps :D
If we want a true representation of how light works, we need better shadows that you'd not be ashamed to bring home and introduce to your parents or we need path tracing. Low-res shadows and various artifacts differ in their impact case-by-case, and impact is subjective in each instance, so as much as I agree that it's a hack - i don't think there's a one right solution here. Just one opinion of a bow tie wearing cat.

**Comment by mrdoob** [comment]
@Usnul I'm trying to achieve #6420.

**Comment by RemusMar** [comment]
> @Usnul I'm trying to achieve #6420.

Ricardo, that's probably the best way to go on.
cheers

**Comment by mrdoob** [comment]
Hmm... If we want to have nice shadows, I think we may need to remove shadow support in `MeshLambertMaterial` and `MeshBasicMaterial`...

**Comment by RemusMar** [comment]
>  If we want to have nice shadows, I think we may need to remove shadow support in MeshLambertMaterial and MeshBasicMaterial... 

In the real world the shadows have nothing to do with materials.
They depend on geometry (meshes) only.
A cube of stone / wood / metal will cast the same shadow.
cheers

**Comment by Usnul** [comment]
@RemusMar 
I'm not sure we're thinking in the same key. A cube of wood would have softer shadows than a cube of metal because of how light will interact with edge of each material. If we take into account light penetration it gets even more tricky. I'm sure you're aware of that, just wanted to make sure materials aren't dismissed out of hand.

**Comment by RemusMar** [comment]
> A cube of wood would have softer shadows than a cube of metal because of how light will interact with edge for each material.

Don't mix them up.
They will have the same shadow.
Same geometry does not mean different edges.
cheers

**Comment by Usnul** [comment]
@RemusMar light warps around the edges of geometry in real life depending on material. Beyond this, both umbra and penumbra will have different brightness based on glossiness of back surface.

**Comment by RemusMar** [comment]
>  light warps around the edges of geometry in real life depending on material.

Come on ...
I'm not talking about reflections, refractions and other "goodies".
An opaque mesh will cast the same shadow independent to its material.
Just test by yourself in a shiny day ... LOL 

On the top of that: we don't need a THREE.js bloated with all kind of worthless features.
cheers

**Comment by mrdoob** [comment]
> In the real world the shadows have nothing to do with materials.
They depend on geometry (meshes) only.
A cube of stone / wood / metal will cast the same shadow.

`MeshBasicMaterial` and `MeshLambertMaterial` can't be compared to real world materials.

**Comment by RemusMar** [comment]
> MeshBasicMaterial and MeshLambertMaterial can't be compared to real world materials.

In fact I was trying to help you in the above posts.

> I think we may need to remove shadow support in MeshLambertMaterial and MeshBasicMaterial 

Yes.
Make the shadows independent on material.

**Comment by mrdoob** [comment]
Fixed!

![screen shot 2015-10-12 at 13 29 58](https://cloud.githubusercontent.com/assets/97088/10434094/65ff13b8-70e5-11e5-8965-e0c04a12c08e.png)
http://jsfiddle.net/6rpjjh5r/

Sorry guys, but `shadowDarkness` is gone, use `AmbientLight` instead. `shadowDarkness` at `0.5` is actually the one making the shadow acne more obvious than it should.

It's still not as good as #6420 but should be a step in the right direction (and it works in all materials).

**Comment by mrdoob** [comment]
Before and after:

![screen shot 2015-10-12 at 14 06 43](https://cloud.githubusercontent.com/assets/97088/10435385/b4c6524c-70ed-11e5-9be1-b65bded5b98f.png)

![screen shot 2015-10-12 at 14 06 32](https://cloud.githubusercontent.com/assets/97088/10435388/baa672c8-70ed-11e5-9774-9a56c1cdfc06.png)

**Comment by WestLangley** [comment]
How about showing the three.js revision on the Editor GUI?

**Comment by mrdoob** [comment]
More before and after.

![screen shot 2015-10-12 at 14 35 46](https://cloud.githubusercontent.com/assets/97088/10435593/f50ae98e-70ee-11e5-9698-ea7cc4898a38.png)

![screen shot 2015-10-12 at 14 36 05](https://cloud.githubusercontent.com/assets/97088/10435596/fbda660e-70ee-11e5-96c1-6a8c23ed3d13.png)

**Comment by mrdoob** [comment]
> How about showing the three.js revision on the Editor GUI?

Good idea!

**Comment by mrdoob** [comment]
Hmm... I guess this also solves the backside shadow bug!

![screen shot 2015-10-12 at 15 30 08](https://cloud.githubusercontent.com/assets/97088/10436768/7665277c-70f6-11e5-9539-064b06fc854a.png)

![screen shot 2015-10-12 at 15 30 43](https://cloud.githubusercontent.com/assets/97088/10436771/7e990d14-70f6-11e5-8512-0fd61e638bad.png)

**Comment by mrdoob** [comment]
Before...

![screen shot 2015-10-12 at 15 53 24](https://cloud.githubusercontent.com/assets/97088/10437230/bb5457c4-70f9-11e5-8bc0-b5ca9e037a12.png)

After...

![screen shot 2015-10-12 at 15 53 36](https://cloud.githubusercontent.com/assets/97088/10437236/bfc251da-70f9-11e5-8d16-053ec3619657.png)

Adding another light source still shows the backface issue though.

![screen shot 2015-10-12 at 15 56 16](https://cloud.githubusercontent.com/assets/97088/10437252/da494f5e-70f9-11e5-8c27-677090de6d52.png)

@WestLangley I wonder if instead of `shadowMask` we can compute a color to be negated. Would that be too nightmare-ish? I guess the only benefit of doing thins would be that we would still support `MeshLambertMaterial`.

**Comment by WestLangley** [comment]
@mrdoob 

I also wonder if something like this would be beneficial?

    shadowMask *= vec3( 1.0 - shadow * shadowDarkness );

**Comment by tschw** [comment]
OT: Wow! Editor with shadows :+1:

**Comment by mrdoob** [comment]
> I also wonder if something like this would be beneficial?

>     shadowMask *= vec3( 1.0 - shadow * shadowDarkness );

I guess we can still keep shadowDarkness until the final solution.

**Comment by mrdoob** [comment]
> OT: Wow! Editor with shadows :+1: 

😊

**Comment by MasterJames** [comment]
≡ praise ≈ ∃Ƨ☤@я¶ {
    dɹɐᴉƨǝ(Ɩ);

**Comment by autotel** [comment]
Hi! sorry for waking up the death.

I just wanted to suggest that many lights emiting shadows will render unrealistic results in a scene that has an ambient light:
When there are two light sources and two shadows overlap, you will get a darker shadow than when a shadow is not overlapping.
I think the mixture is not additive, nor sustractive, but rather a weighted average according to each light's intensity. ShadowDarkness is a misleading variable...

![img_20170327_173010](https://cloud.githubusercontent.com/assets/15053243/24361774/75ae23fe-1313-11e7-8d53-9d59a392c8fe.jpg)

**Comment by mrdoob** [comment]
@autotel probably better to do a render with Blender or something :)

**Comment by autotel** [comment]
Yup. I understand. Is like after that we will start thinking about caustic effects and stuff; a bit out of browser's scope. Often this place is used for feature requests, but in this case I just wanted to point out that possibility.
Thanks for keeping up with three btw. Awesome lib!
