### ISSUE TITLE
Cloning tubeGeometry gives error

### ISSUE THREAD

**Issue by bingomanatee** [mrdoob/three.js#7322]
![image](https://cloud.githubusercontent.com/assets/684016/10400209/3cb99af8-6e6c-11e5-9a12-b76e7b2f7a21.png)

            var tubeGeometry = this.tube(width, height);

            var tube = new THREE.Mesh(tubeGeometry, material);
            tube.position.z = -width / 2;
            tube.rotation.y = Math.PI / 2;
            tube.scale.multiply({x: 0.1, y: 0.1, z: 0.1});
            scene.add(tube);

            edges = new THREE.EdgesHelper( tube, 0x00ff00 );

[tube creates a tubeGeometry, and inverts its normals.]
        tube: function (width, height) {
            var CustomSinCurve = THREE.Curve.create(
                function (scale) { //custom curve constructor
                    this.scale = (scale === undefined) ? 1 : scale;
                },

                function (t) { //getPoint: t is between 0-1
                    var tx = t * 3 - 1.5,
                        ty = Math.sin(2 * Math.PI * t) * t,
                        tz = 0;

                    return new THREE.Vector3(tx, ty, tz).multiplyScalar(this.scale);
                }
            );

            var path = new CustomSinCurve(Math.max(width, height) * 2);

            var tubeGeometry = new THREE.TubeGeometry(
                path,  //path
                40,    //segments
                Math.max(width, height) / 2,     //radius
                24,     //radiusSegments
                false  //closed
            );

            for (var f = 0; f < tubeGeometry.faces.length; ++f) {
                tubeGeometry.faces[f].normal.multiplyScalar(-1);
            }
            for (var n = 0; n < tubeGeometry.normals.length; ++n) {
                tubeGeometry.normals[n].multiplyScalar(-1);
            }

            tubeGeometry.normalsNeedUpdate = true;
            return tubeGeometry;
        },

**Comment by mrdoob** [comment]
Already fixed in the `dev` branch. #7303
