### ISSUE TITLE
MeshNormalMaterial don't work with skinnedMesh

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#7330]
The skinning parameters for the material is not recognise at the creation of the material:

new THREE.MeshNormalMaterial({skinning:true}) //error

And if sneaky added after, then the shader can't compile : skinned is missing..

new THREE.MeshNormalMaterial({})
material.skinning = true
//error when the shader is compile

If the skinning option is not add, then the material show the normal but the skeleton is not apply.

**Comment by Mugen87** [comment]
Should be solved via #10343
