### ISSUE TITLE
Extrude material no longer an option in three.js r72

### ISSUE THREAD

**Issue by elifer5000** [mrdoob/three.js#7332]
Up until r71, TextGeometry (itself based on ExtrudeGeometry) had the option to select different materials for the front and the extruded faces. The code below would be able to produce: 
<img width="538" alt="screen shot 2015-10-11 at 16 02 28" src="https://cloud.githubusercontent.com/assets/4311278/10427554/494b0c96-70f3-11e5-90ba-ce6b406916b9.png">

```javascript
var materialFront = new THREE.MeshBasicMaterial( { color: 0xE94042  } );
var materialSide = new THREE.MeshBasicMaterial( { color: 0x000000 } );
var materialArray = [ materialFront, materialSide ];
var textMaterial = new THREE.MeshFaceMaterial(materialArray);

var textProperties = {
        size: 5, height: 1.0, curveSegments: 3,
        font: "helvetiker", weight: "normal", style: "normal",
        bevelEnabled: true, bevelThickness: 0, bevelSize: 0,
        material: 0, extrudeMaterial: 1
    };

var textGeom = new THREE.TextGeometry( "100.0", textProperties);
var textMesh = new THREE.Mesh(textGeom, textMaterial );
```
I found this [commit](https://github.com/mrdoob/three.js/commit/03b8391b2f57abcfeb3c65e195556a25dd9227aa#diff-ea441605829c446bcc04d024ba2d19ef) in the project's github where the option to set the material and extrudeMaterial was removed, with no apparent alternative way to achieve the same result. Now in r72 all the faces have the same color (the one from materialFront), like this: 
<img width="538" alt="screen shot 2015-10-11 at 16 06 16" src="https://cloud.githubusercontent.com/assets/4311278/10427627/ce911a76-70f3-11e5-9075-7cfc5fcab691.png">

Samples:
[JSFiddle with r72 - side color is missing](http://jsfiddle.net/ma3wtuLx/6/)
[JSFiddle with r71 - works ok](http://jsfiddle.net/o5qm7mfz/3/)

**Comment by WestLangley** [comment]
It appears the changes implemented  [here](https://github.com/mrdoob/three.js/commit/03b8391b2f57abcfeb3c65e195556a25dd9227aa) need to be reverted -- if possible.

**Comment by mrdoob** [comment]
Reverted/Fixed. http://jsfiddle.net/ma3wtuLx/7/

**Comment by WestLangley** [comment]
@mrdoob many thanks!

**Comment by mrdoob** [comment]
😊

**Comment by elifer5000** [comment]
Thanks for the quick response! And fix!

**Comment by SenninSensei** [comment]
i don't understand how to use a a diferent material for the extrudeMaterial this doesn't work anymore http://jsfiddle.net/ma3wtuLx/7/

**Comment by WestLangley** [comment]
@SenninSensei It seems to work: http://jsfiddle.net/ma3wtuLx/9/. r.74dev

**Comment by MasterJames** [comment]
It seems these are not working though.

    material: 0, extrudeMaterial: 0

**Comment by WestLangley** [comment]
>It seems these are not working though.
>>material: 0, extrudeMaterial: 0

Yes. It appears to be hardwired, now. The first material is for the front, and the second material is for the side.

**Comment by GrzegorzAndrys** [comment]
Hello, looks like broken again?
