### ISSUE TITLE
editor failure on extremely big json

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#7335]
Not really big deal, I guess. However, importing 30-something MB STL / exporting geometry fails with
![screen shot 2015-10-13 at 12 31 57](https://cloud.githubusercontent.com/assets/242577/10453133/418b2fce-71aa-11e5-98dc-3835c1393b55.png)
If I comment out
```javascript
output = output.replace( /[\n\t]+([\d\.e\-\[\]]+)/g, '$1' );
```
it works, I mean I get 200-something MB JSON ) Maybe it could be good idea to try-catch this line, and proceed with un-replaced string, if it fails?

**Comment by mrdoob** [comment]
Yeah, that sounds good. Do you mind doing a PR for that?

**Comment by makc** [comment]
btw, before I forget - I was wrong in the description. the error was not in replace, but in stringify with '\t'

**Comment by mrdoob** [comment]
Good to know!
