### ISSUE TITLE
Color.setStyle() wrong hsl(a) parsing

### ISSUE THREAD

**Issue by magnitudoOrg** [mrdoob/three.js#7336]
https://github.com/mrdoob/three.js/blob/master/src/math/Color.js Line 194 and Line 209
var h = parseFloat( color[ 1 ] ); 
should be:
var h = parseFloat( color[ 1 ] ) / 360; 
cause range for the hue in CSS hsl(a) is 0 to 360 (degrees, red to red again), not 0 to 1.0

(anyways, parseFloat is still right, cause spec says that hue a number (and no integer like rgb-component) https://developer.mozilla.org/en-US/docs/Web/CSS/color#hue)

Detected: All my (blue, yellow, ...) objects were red after i used Color.setStyle(someHslaString). After patch with division by 360 the colors are as expected. ;)

**Comment by mrdoob** [comment]
Fixed. Thanks!

**Comment by dubejf** [comment]
Oops I shouldn't have used just red for the unit tests! Thanks!!
