### ISSUE TITLE
wireframe material display is wrong when used with a BufferGeometry

### ISSUE THREAD

**Issue by makemeunsee** [mrdoob/three.js#7338]
HTML/js code reproducing the problem:
http://pastebin.com/EAjYFEGw
Left tetrahedron is badly drawn, right tetrahedron is properly drawn but required using the workaround, middle tetrahedron is just here for reference.

Details:
If a BufferGeometry is provided with correct indices, adapted to a wireframe Material (meaning the Geometry will be rendered with mode GL_LINES), the indices of the BufferGeometry are recomputed incorrectly /tampered with ([here](https://github.com/mrdoob/three.js/blob/17df4c44c2365ad7649f53e99734ae48848ab646/src/renderers/webgl/WebGLObjects.js#L128)).

Workaround:
Make the indices as if to draw 'flattened' triangles. This way, the indices are not recomputed.

**Comment by WestLangley** [comment]
Try this with your geometry:

    var material = new THREE.MeshBasicMaterial( { wireframe: true } );
    var mesh = new THREE.Mesh( geometry, material );

Or, try this with your geometry

    var geometry = new THREE.WireframeGeometry( geometry );
    var material = new THREE.LineBasicMaterial( { color: 0xffffff } );
    var line = new THREE.LineSegments( geometry, material );

**Comment by makemeunsee** [comment]
I actually need a ShaderMaterial instance. Or a Shader 
The example I provided here is dumbed down a lot for exposing the issue, but where I run into the issue (btw it is a r72 issue, r71 was fine), is in a mix of lines and triangles rendering combined with shaders.

**Comment by WestLangley** [comment]
Or, try this with your geometry

	var material = new THREE.ShaderMaterial( {
		uniforms: {},
		vertexShader: document.getElementById( 'vertexShader' ).textContent,
		fragmentShader: document.getElementById( 'fragmentShader' ).textContent,
	} );

	var line = new THREE.LineSegments( geometry, material );
