### ISSUE TITLE
SpriteCanvasMaterial removed?

### ISSUE THREAD

**Issue by magnitudoOrg** [mrdoob/three.js#7341]
SpriteCanvasMaterial is described the docs, but its not available in r72? I didn't find it in master or dev src.

http://threejs.org/docs/#Reference/Materials/SpriteCanvasMaterial

Maybe doc needs an update if it was removed. ;)
(Seems it was mentioned in r70 in the change log at last...doesn't say it was removed: https://github.com/mrdoob/three.js/releases)

**Comment by mrdoob** [comment]
Should be inside `examples/js/renderers/CanvasRenderer.js`.

**Comment by magnitudoOrg** [comment]
Thank you, it is there. Now I see the purpose of SpriteCanvasMaterial is different than I expected. (Source link in docs maybe updated)

**Comment by mrdoob** [comment]
> Source link in docs maybe updated

Feel free! 😊

**Comment by magnitudoOrg** [comment]
I would like to contribute (, but if the file is edited direclty on github -> preview changes will profess that every single line will be removed and added in the html file - even if I don't change anything. Looks like whitespace problem, but there are no whitespace changes!? So a commit would be useless for the maintainer. If I find some time, I will test, if I can do it on Windows with SourceTree...)

**Comment by mrdoob** [comment]
> I would like to contribute (, but if the file is edited direclty on github -> preview changes will profess that every single line will be removed and added in the html file - even if I don't change anything. Looks like whitespace problem, but there are no whitespace changes!? So a commit would be useless for the maintainer.

Oh, don't worry about that. With `?w=1` in the PR url I can filter whitespace changes out.

**Comment by magnitudoOrg** [comment]
Ty, I created a pull request "Moved SpriteCanvasMaterial.html to examples (docs), Fixed src link #7358"
I never done this before with Git(hub), hope it is right to commit from dev -> dev branch (maybe gh-pages branch is better for doc changes?)

BTW: If you know a way how to quick-test the html (like docs) on gh, pls let me know ;)
http://htmlpreview.github.io has problems with frames and some mime-types...
