### ISSUE TITLE
Vector Equals with Tolerance

### ISSUE THREAD

**Issue by WestLangley** [mrdoob/three.js#7346]
Is there any interest in modifying the `Vector*.equals( v )` methods to something like the following?

```javascript
equals: function ( v, tolerance ) {

	if ( tolerance === undefined ) {

		return ( ( v.x === this.x ) && ( v.y === this.y ) && ( v.z === this.z ) );

	} else {

		return ( ( Math.abs( v.x - this.x ) < tolerance ) && ( Math.abs( v.y - this.y ) < tolerance ) && ( Math.abs( v.z - this.z ) < tolerance ) );

	}

},
```

**Comment by makc** [comment]
I use .distanceTo but this would be faster

**Comment by Usnul** [comment]
This is essentially a manhattan distance. Agree with @makc , I think conditional here is not desired. How about a new method like "similar"? or just "manhattanDistanceTo"?
```javascript
function manhattanDistanceTo(v){
   return Math.abs(this.x - v.x) + Math.abs(this.y - v.y) + Math.abs(this.z - v.z);
}
```

so then it's just:
```javascript
var isCloseEnough = v1.manhattanDistanceTo(v0) < tolerance;
```

**Comment by liammagee** [comment]
I find myself doing this quite often, and agree it would be useful to bake
it into the framework.

**Comment by Usnul** [comment]
@liammagee & @WestLangley 
could you guys describe use-cases a little bit? I only ever do this when checking proximity, not really equivalence (which typically means true equality, not subjective equality, i.e. "to me these two things are same enough"). For proximity i see the use of "distanceTo" and it's faster counterpart "manhattanDistanceTo". Maybe vector comparison operations like "lessThan" with logic of component-size comparison. (x0 < x1 && y0 < y1 && z0 < z1).
I'm quite curious to know your thoughts and motives :)

**Comment by sohale** [comment]
I am surprised you haven't had this already in Three.js. It is a known programming rule that you should "Never use == to compare two floating point numbers." (Except for really rare situations). 
 http://floating-point-gui.de/errors/comparison/  https://isocpp.org/wiki/faq/newbie#floating-pt-errs
 
Same is true for ineuqalities: `a<b`, `a<=b`, `a==b`, where you need to: `a < b-tol`, `a < b + tol`, `Math.abs(a-b) < tol`

A suggestions is that you have an equals method that forces the called to provide the tolerance (with no default):
```javascript
  v1.equals(v0, tolerance)
  v1.equals(v0) // ---> error 
```
The only reason for not doing this comparison can be performance.

**Comment by Usnul** [comment]
@sohale 
so, you're saying that if i do exactly the same sequence of operations on two floating point variables starting wit exactly the same values on the same hardware with the same environment  - i will get two different answers?
But you are right, it is a known to beginner programmers that when doing floating point operations you may get rounding errors which result in things that mathematically produce the same results to produce binary representations which are not the same, due to said rounding error. Thanks for pointing that out.

what about those usecases? :)

**Comment by makc** [comment]
@Usnul 
> exactly the same values

I ran into situations where I did console.log(floatValue), copy-pasted that value into the code and it ended up being different value.

**Comment by Usnul** [comment]
@makc 
console.log does Number.toString under the hood, which makes sense. When this conversion happens, number of digits is cropped, so some very long fractions when expressed in decimal (or indeed recurring ones) get their last digit rounded. So for instance 3.(3) would turn into something like 3.33333333333333 or 3.33333333333334, which is a reasonable representation, but is ultimately not the true value that is being represented. This is more to do with a representation for humans and less to do with rounding error.

Nice frog by the way, but question is: will it blend?

**Comment by WestLangley** [comment]
@Usnul 

> could you guys describe use-cases a little bit?

I was _eliciting_ use-cases, actually. But two cases that entered my mind were (1) merging vertices, and (2) unit testing -- comparing a computed answer with a known answer. The latter one would apply to `Euler`, `Quaternion`, also.

**Comment by liammagee** [comment]
I misunderstood the initial rationale re: floating point comparisons.

My use case uses manhattan distance as form of collision detection. In 2D
space as an example I would use the proposed equals method to test whether
the point *v* lies within a particular cell of a gridded plan, where the *this
*is the centre of the cell and *tolerance *is the width of the cell / 2.

**Comment by WestLangley** [comment]
Given the preferred distance metric can vary with the use case, and the concept of "close to" is not uniquely-defined, I am closing this.

**Comment by sohale** [comment]
Note that `0.1+0.2==0.3` is `false` in javascript.

**Comment by makc** [comment]
Can't you put 0.30000000000000004 in unit tests?

**Comment by sohale** [comment]
no

**Comment by makc** [comment]
y?

**Comment by zz85** [comment]
👍  for using some tolerance in `Vector.equals()`. While working on #9079 I think it a little neater and accurate to use this function than do `.distanceTo() < Number.EPSILON`. I would suggest Number.EPSILON as the tolerance, which is almost close to strict equalities.

```js
equals: function ( v )  {
  return Math.abs( v.x - this.x ) < Number.EPSILON && Math.abs( v.y - this.y ) < Number.EPSILON;
}
```

This means

```js
new THREE.Vector2(0, 0.3).equals( new THREE.Vector2(0, 0.2 + 0.1) ) // true
```

would be more accurate.
