### ISSUE TITLE
Point Cloud and Motion Blur

### ISSUE THREAD

**Issue by mattlockyer** [mrdoob/three.js#7352]
I've been at this for a couple of days and wondering if the PointCloud material can be rendered in this way some how to apply a motion blur to the particles: http://mrdoob.github.io/three.js/examples/webgl_materials_cubemap_dynamic.html

I know the whole scene is being processed in the example above, but when I applied this to my scene I don't see the blur effect.

My particles are travelling very fast (ex: the whole screen width in 10 frames), how can I blend the frames and interpolate so it appears like a streak vs. stamped out 10 times?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
