### ISSUE TITLE
THREE.Loader.prototype.extractUrlBase

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#7354]
Just noticed this method exists. I have been doing

``` javascript
url.substr (0, url.lastIndexOf ('/') + 1);
```

This `extractUrlBase` has this:

``` javascript
function ( url ) {
    var parts = url.split( '/' );
    if ( parts.length === 1 ) return './';
    parts.pop();
    return parts.join( '/' ) + '/';
}
```

Apart from './' thing it is equivalent and does not create array.

**Comment by mrdoob** [comment]
That's much more readable indeed!

**Comment by Cucak** [comment]
> ```js
> url.substr (0, url.lastIndexOf ('/') + 1);
> ```

Hey bro, how I can edit this code at npm modules, I am getting errors about the url.lastIndex and I am not sure how to fix it? Thank you

**Comment by makc** [comment]
@Cucak I think you could just do THREE.Loader.prototype.extractUrlBase = your_implementation in your own code, and leave npm code be
