### ISSUE TITLE
Shadowing still gives shadow acne

### ISSUE THREAD

**Issue by throni3git** [mrdoob/three.js#7359]
Hello und a big ThankYouAll for three.js :)

I'm trying to achieve beautiful shadowed render graphics und i have followed the recent changes in shadowmapping ( https://github.com/mrdoob/three.js/issues/7321 and https://github.com/mrdoob/three.js/issues/6420 ). Anyway, using the current master build, i still get shininess through shadow and shadow acne artifacts. This seems to be an issue with multiple lights (of type Spot / Directional)

I've forked a jsfiddle from mrdoob with a spotlight and a directional light. Have a look at http://jsfiddle.net/wgwoqncy/4/

Spotlights shining through shadows:

![issue_shininess_throug_shadow](https://cloud.githubusercontent.com/assets/14586717/10541328/687088ec-7410-11e5-96a0-19b311aeda7d.jpg)

Shadow Acne with two SpotLights:

![issue_shadow_acne_spotlights](https://cloud.githubusercontent.com/assets/14586717/10541345/960805c8-7410-11e5-85b7-8a926e892949.jpg)

Shadow Acne with a SpotLight and a DirectionalLight:

![issue_shadow_acne_spot_and_dir](https://cloud.githubusercontent.com/assets/14586717/10541353/a6e631da-7410-11e5-9a66-531a080204f6.jpg)

Greetings,
Thomas

**Comment by mrdoob** [comment]
Yes. We still haven't solved this...

**Comment by mrdoob** [comment]
Using a single light (`DirectionalLight`, `SpotLight` or `PointLight`) with `shadowDarkness` set to `1` and an ambient light (`AmbientLight` or `HemisphereLight`) gives the best results at the moment.

**Comment by throni3git** [comment]
Yes, this is my solution so far. Good to know, you're on it :) Thanks

**Comment by WestLangley** [comment]
@throni3git The shadow acne is caused by self-shadowing. That is what `shadowBias` helps correct. Adjust the spotlight bias. The trade-off is peter-panning.

**Comment by makc** [comment]
that https://cloud.githubusercontent.com/assets/14586717/10541353/a6e631da-7410-11e5-9a66-531a080204f6.jpg looks like minibrot

**Comment by bhouston** [comment]
There must be more advanced ways to solve our shadow acne problem.  Most modern game development systems do not show the degree of shadow acne ThreeJS currently has.  There must be an automated solution.  It is on my list of things to get to.

**Comment by mrdoob** [comment]
@bhouston I think it's just a matter of moving away from the `shadowMask` concept. Storing whether is shadow or not in the light per fragment sounds like a better approach.

**Comment by mrdoob** [comment]
Fixed! http://jsfiddle.net/wgwoqncy/5/

**Comment by bhouston** [comment]
Dude!

**Comment by mrdoob** [comment]
Things look a lot better now.

![screen shot 2015-11-06 at 08 32 49](https://cloud.githubusercontent.com/assets/97088/11000273/b91fd84c-846e-11e5-9980-db158a140ec9.png)

`webgl_shadowmap_pointlight` is now extra sexy 😊

![screen shot 2015-11-06 at 09 10 30](https://cloud.githubusercontent.com/assets/97088/11000281/c0042488-846e-11e5-937e-9be7938f2f1b.png)

**Comment by bhouston** [comment]
It fails on Linux Intel drivers:
```
THREE.WebGLShader: gl.getShaderInfoLog() fragment 0:158(63): error: sampler arrays indexed with non-constant expressions is forbidden in GLSL 1.30 and later
0:159(63): error: sampler arrays indexed with non-constant expressions is forbidden in GLSL 1.30 and later
0:160(63): error: sampler arrays indexed with non-constant expressions is forbidden in GLSL 1.30 and later
0:161(63): error: sampler arrays indexed with non-constant expressions is forbidden in GLSL 1.30 and later
0:162(63): error: sampler arrays indexed with non-constant expressions is forbidden in GLSL 1.30 and later
0:163(63): error: sampler arrays indexed with non-constant expressions is forbidden in GLSL 1.30 and later
0:164(63): error: sampler arrays indexed with non-constant expressions is forbidden in GLSL 1.30 and later
0:165(63): error: sampler arrays indexed with non-constant expressions is forbidden in GLSL 1.30 and later
0:166(63): error: sampler arrays indexed with non-constant expressions is forbidden in GLSL 1.30 and later
```

Interesting, I'm pretty sure @tschw figured out how to address that in this comment:

https://github.com/mrdoob/three.js/pull/7426#issuecomment-152285901

**Comment by makc** [comment]
@mrdoob 
> Fixed! http://jsfiddle.net/wgwoqncy/5/

are you sure? it looks like this over here:

![screen shot 2015-11-06 at 17 43 50](https://cloud.githubusercontent.com/assets/242577/11002589/05159950-84ae-11e5-85e6-455a32470d8e.png)

**Comment by bhouston** [comment]
I think it may be possible to not cast shadows on faces facing away from the light that is shadowing them.  Or at least extend the bias in those cases.  That should help with this situation.

**Comment by mrdoob** [comment]
@makc what your os/hardware?

**Comment by bhouston** [comment]
I have shadow acne on the back side as well with Windows 10, Chrome latest and GeForce 660:

![image](https://cloud.githubusercontent.com/assets/588541/11003416/5cfa2e66-8480-11e5-9980-782c24395057.png)

**Comment by makc** [comment]
@mrdoob 
![screen shot 2015-11-06 at 18 19 50](https://cloud.githubusercontent.com/assets/242577/11003480/0558bf32-84b3-11e5-9b4e-2a9f7c5ce80d.png)

**Comment by mrdoob** [comment]
@makc no errors in the console?

**Comment by mrdoob** [comment]
@bhouston well, yes, I guess saying that I fixed the shadow acne was not correct. however, it's WAY less noticeable 😇

**Comment by makc** [comment]
@mrdoob total silence after `THREE.WebGLRenderer 74dev`. maybe some undefined behavior?

**Comment by MasterJames** [comment]
On mobile Android chrome it's just flat and dark no lights?

**Comment by mrdoob** [comment]
> On mobile Android chrome it's just flat and dark no lights?

Any example? Or only the ones with shadows?

**Comment by MasterJames** [comment]
![screenshot_2015-11-07-01-58-18](https://cloud.githubusercontent.com/assets/1840183/11014617/f043b958-84f3-11e5-8f1d-520327a91ad0.png)
This is from your link http://jsfiddle.net/wgwoqncy/5/
I'm pondering it has something to do with the rawgit or what I don't know. I'm not clear on how to get debug or log from it (Android 5.0.0 Galaxy Note3 ~ Chrome 46.0.2490.76) without using something like "weinre", etc.

**Comment by bhouston** [comment]
To debug Chrome on an Android device you have to follow these instructions:

https://developer.chrome.com/devtools/docs/remote-debugging

**Comment by MasterJames** [comment]
Thanks for that. It needed redoing more then a few timed before it showed up under chrome://inspect

**Comment by MasterJames** [comment]
And here is the console errors.

    Uncaught TypeError: Cannot read property 'getOption' of undefined
    THREE.WebGLRenderer 74dev
    THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
    Uncaught TypeError: Cannot read property 'setOption' of undefined

**Comment by mrdoob** [comment]
@makc @MasterJames can you guys try again with the latest in `dev`?

**Comment by MasterJames** [comment]
Yes that's got it!
New confidence in "one for all" phylosophy.

**Comment by mrdoob** [comment]
Good to know. My `Nexus 5` still crashes. I think I'll have to move a few things around...
