### ISSUE TITLE
r73 : nothing works !?!

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#7360]
Ricardo,

Did you ever test any of the previous projects on the latest r73 release?
All kind of errors, nothing works!
Why did you release something like that?

**Comment by mrdoob** [comment]
What doesn't work? What errors are you getting? I always make sure all the examples still work. If something broke we should add a example that tests that.

**Comment by RemusMar** [comment]
> What doesn't work?

Nothing works !!!
Just an example (for you):
http://necromanthus.com/Test/html5/dog_r72.html 
http://necromanthus.com/Test/html5/dog_r73.html 
Errors:
- THREE.MorphAnimMesh is undefined 
- loader.load is not a function 

Why did you release something like that ???

**Comment by jostschmithals** [comment]
Since backwards compatibility has never been a programming principle of three.js, it is always important to link to the same threejs version your project is built with. 

You are free to change your code to use the new functions if you want.

**Comment by mrdoob** [comment]
Ah! I see.

We have completely replaced the animation system and SEA3D still relies in the old one (@sunag is working on an update I think).

In the meantime you need to include the old animation system in your project:

```html
<script src="js/MorphAnimMesh.js"></script>
<script src="js/loaders/collada/Animation.js"></script>
<script src="js/loaders/collada/AnimationHandler.js"></script>
<script src="js/loaders/collada/KeyFrameAnimation.js"></script>
```

You'll find the files in the `examples` folder.

**Comment by RemusMar** [comment]
> We have completely replaced the animation system 

And again, you messed up the backward compatibility ... OMG
Anyway, here is something else (without animation and loader):
http://necromanthus.com/Test/html5/koolmoves_r72.html 
http://necromanthus.com/Test/html5/koolmoves_r73.html
Errors:
- _typeface_js is not defined
- THREE.TextGeometry is not a constructor 

Honestly, r73 is a complete mess and it should be removed.
cheers

**Comment by chilipeppr** [comment]
I've been relying on Three.js for ChiliPeppr for about 1.5 years now. This morning it appears THREE.FontUtils is undefined so all font rendering is broken in ChiliPeppr. I'm guessing it's the same r73 issue as @RemusMar is referring to as well.

**Comment by mrdoob** [comment]
`FontUtils` and `TextGeometry` utils have also been removed from core.

You now have to include the files separately:

```javascript
<script src="js/geometries/TextGeometry.js"></script>
<script src="js/utils/FontUtils.js"></script>
<script src="fonts/helvetiker_regular.typeface.js"></script>
```

I decided to move it out of core because the user had to include the `*.typeface.js` anyway.

**Comment by mrdoob** [comment]
@RemusMar We don't guarantee backwards compatibility between versions. But we do add [transition code](https://github.com/mrdoob/three.js/blob/master/src/lights/Light.js#L21-L87) that notifies the user and keeps the code working when/where we can.

**Comment by RemusMar** [comment]
> FontUtils and TextGeometry utils have also been removed from core.

Why don't you remove everything from the core?
A core with ZERO bytes does not need to be downloaded at all.


>  We don't guarantee backwards compatibility between versions. 

That's a bad move Ricardo.
As I said from the very beginning:

The backward compatibility is a MUST in any serious project.
Otherwise less and less people will be interested in that project.

cheers

**Comment by mrdoob** [comment]
> Why don't you remove everything from the core?
> A core with ZERO bytes does not need to be downloaded at all.

I gather you're an emotional guy. However, you stay around so I also gather that at the end of the day you find the project useful 😉

> The backward compatibility is a MUST in any serious project.

Maybe this is not as serious of a project as you think it is? I'm not Adobe you know?

> Otherwise less and less people will be interested in that project.

People losing interest is not something I worry about. Instead, I focus on creating a beautiful API that abstract the annoyances of computer graphics and, at the same time, I want the library to fit in 100kb gzipped. It's impossible to forever include all the features that get included.

**Comment by simonThiele** [comment]
@RemusMar Backward compatibility, if you use js libs like that you should be able to repair issue by yourself if something is not supported anymore. If not, ask in a more co-operative way, everybody is pleased to help. If examples are broken, feel free to repair it...

**Comment by jostschmithals** [comment]
@RemusMar   One of the very first things I learned about three.js, when I started 3D programming in JavaScript, was the fact that it is not backwards compatible. 

I think, in general that is absolutely no problem, because I only have to make sure, that in my project I link to the same version of three.js I have built my code with.

The policy not to take backwards compability into account was certainly the basis for the chance to develop three.js in such a dynamic manner, with such very fantastic possibilities, up to now.

**Comment by makc** [comment]
> That's a bad move Ricardo

amazing how people notice this after 70+ revisions )

But to add to the point, someone was recently writing to me "the latest stable three.js is r72", lol. there is no stable three.js. they do not update old revisions with bug fixes, instead there comes new version with bugfixes *and* breaking changes or new bugs.

**Comment by makc** [comment]
Then again, some things magically work through versions even if underlying code was turned upside down. Like skins using buffer geometry )

**Comment by makc** [comment]
While we're on subject of breaking changes, what is pissing me off the most are json changes. Someone has old exporting plugin in his 3dmax, and I spend ages editing json by hand to make animations work.

**Comment by mrdoob** [comment]
> Then again, some things magically work through versions even if underlying code was turned upside down. Like skins using buffer geometry )

That took some effort! 😅

> While we're on subject of breaking changes, what is pissing me off the most are json changes. Someone has old exporting plugin in his 3dmax, and I spend ages editing json by hand to make animations work.

Yes. Animation needs to get stable ASAP. I think the new animation system is a great step in the right direction.

**Comment by chilipeppr** [comment]
It looks like this sample is broken given your r73 changes. http://threejs.org/docs/scenes/geometry-browser.html#TextGeometry

![image](https://cloud.githubusercontent.com/assets/7904621/10553786/6aa6635a-7412-11e5-9921-d7730553ebe5.png)

**Comment by mrdoob** [comment]
Oh! Always forget about the samples in docs...

**Comment by tiagopadua** [comment]
@mrdoob 
What should I use to replace the "old" THREE.Animation class?
Are there any examples that use the new animation system?  It's not so clear what is new on the examples page.

**Comment by titansoftime** [comment]
> While we're on subject of breaking changes, what is pissing me off the most are json changes. Someone has old exporting plugin in his 3dmax, and I spend ages editing json by hand to make animations work.

This has been a concern of mine as well. I really don't want to ever have to re-export hundreds of models.

**Comment by RemusMar** [comment]
> @jostschmithals 
> The policy not to take backwards compability into account was certainly the basis for the chance to develop three.js in such a dynamic manner, with such very fantastic possibilities, up to now. 

That's a false statement.
In fact, breaking the backward compatibility all the time makes the 3rd party developers to give up on  THREE.js
On the other hand, new features and bug fixes does not mean to break the compatibility with the older projects. 
If Ricardo will continue on this path, time will tell if I'm right or not.
cheers

**Comment by zz85** [comment]
![](http://www.userfriendly.org/cartoons/archives/98may/uf980506.gif)

**Comment by mrdoob** [comment]
> This has been a concern of mine as well. I really don't want to ever have to re-export hundreds of models.

Agreed! The json format is something where I think backwards compatibility is super important. Is not hard to do anyway.

**Comment by titansoftime** [comment]
> Agreed! The json format is something where I think backwards compatibility is super important. Is not hard to do anyway.

Big sigh of relief =]

**Comment by titansoftime** [comment]
It does seem a bit premature to release a build without updateing the migration guide when breaking changes are involved. Fortunately for me since I follow these boards, I was aware of the Animation Change. I wouldn't bet that all users were equally prepared.

**Comment by mrdoob** [comment]
> It does seem a bit premature to release a build without updateing the migration guide when breaking changes are involved.

Doing a release involves quite a few steps. Sometimes my patience/dedication runs out... 😕
Anyone can update the migration page. I would love to get some help there.

**Comment by mrdoob** [comment]
> It looks like this sample is broken given your r73 changes. http://threejs.org/docs/scenes/geometry-browser.html#TextGeometry

Fixed!

**Comment by rk48** [comment]
Hello,

When I add <script src="js/utils/FontUtils.js"></script>
I got an error:
Uncaught TypeError: object.raycaster is not a function

Why?
And when I remove <script src="js/utils/FontUtils.js"></script>
There is no any errors.
Version 73

Thank you in advance for any help!

**Comment by pjanik** [comment]
Where can I find FontUtils in r74? Seems to be removed in r74...

**Comment by mrdoob** [comment]
@pjanik 

Yeah, sorry about that, the `TextGeometry` API changed again. It's back in core though! 

Please use http://threejs.org/examples/webgl_shadowmap.html as reference.

```javascript
var loader = new THREE.FontLoader();
loader.load( 'fonts/helvetiker_bold.typeface.js', function ( font ) {

	var textGeo = new THREE.TextGeometry( "THREE.JS", {

		font: font,

		size: 200,
		height: 50,
		curveSegments: 12,

		bevelThickness: 2,
		bevelSize: 5,
		bevelEnabled: true

	});

	textGeo.computeBoundingBox();
	var centerOffset = -0.5 * ( textGeo.boundingBox.max.x - textGeo.boundingBox.min.x );

	var textMaterial = new THREE.MeshPhongMaterial( { color: 0xff0000, specular: 0xffffff } );

	var mesh = new THREE.Mesh( textGeo, textMaterial );
	mesh.position.x = centerOffset;
	mesh.position.y = FLOOR + 67;

	mesh.castShadow = true;
	mesh.receiveShadow = true;

	scene.add( mesh );

} );
```

**Comment by pjanik** [comment]
If anyone is interested, this is how I loaded font without async request, using NPM `three@0.74.0` module and webpack: https://gist.github.com/pjanik/49c03c02c66341a26904
If you're using any other build tool, the key thing is to load font file as a string. Maybe this funny parsing could be extracted to some helper method in the future?

On a side note, it's cool that r74 includes `/examples` dir (r73 didn't), please continue to do that. :wink: Finally, I can use only `three` package, no externals script files anymore (I'm also using `examples/js/controls/OrbitControls`). It would be even more cool if examples were published using UMD format, so I could directly require OrbitControls without shimming global THREE dependency (not a big deal, as most of the build tools can handle it, but still).

Thanks!

**Comment by makc** [comment]
or you could just define _typeface_js.loadFace locally and eval it?

**Comment by RemusMar** [comment]
> Yeah, sorry about that, the TextGeometry API changed again. It's back in core though! 

That was a wise decision Ricardo.
A minor syntax change for the loader is needed, but it is backward compatible.
r71: http://necromanthus.com/Test/html5/koolmoves.html 
r74: http://necromanthus.com/Test/html5/koolmoves_r74.html 
cheers

**Comment by fraguada** [comment]
Should we add back loading of text geometry in the ObjectLoader?

**Comment by mrdoob** [comment]
@fraguada well, is not that easy, we should also handle the font file...

**Comment by ben-burlingham** [comment]
@mrdoob 
I admire the way you handled that emotional situation; I learned something from your actions.  Thanks for a great library and keep up the good work.

**Comment by DarrenCook** [comment]
FontUtil is not defined in the version of r74 I've been getting: https://github.com/mrdoob/three.js/blob/master/build/three.js

That appears to be the same as the one being used by http://threejs.org/examples/webgl_shadowmap.html  (except minified) but I also don't see it explicitly including FontUtils or typeface... yet that example page works. (Whereas I still get "_typeface_js is not defined")  Are you doing something in addition to what is shown in your comment (the code sample 6 comments above this one)?

**Comment by ajhalls** [comment]
The documentation needs to get updated as the API changed, this no longer applies: http://threejs.org/docs/index.html#Reference/Extras.Geometries/TextGeometry

It would have been super useful to have a very basic example without all the keystroke recording switching fonts, weights and bevels. Not that those aren't also great to have, but a simple basic one in your examples would have saved me a ton of time.

This example could have helped a lot: http://threejs.org/docs/scenes/geometry-browser.html#TextGeometry, but when you look at the source, it only ends up drawing a torus as it pulls in external resources to actually do the work.

I put together this simple example on JSFiddle for anyone that finds this thread.
https://jsfiddle.net/287rumst/1/

**Comment by RemusMar** [comment]
> It would have been super useful to have a very basic example 

r75 and r76dev:
http://necromanthus.com/Test/html5/koolmoves.html

**Comment by q2apro** [comment]
Just two my cents because I am also a fan of backwards compatibility: 

If compatibility cannot be guaranteed, it would be nice to have a `solution` folder in github that shows the old version and the new handling. A reference. 

This way it would be easy for programmers to catch up with the changes.

**Comment by derivou** [comment]
Hi all, I just moved from r71 to r76 and discovered the new animation.mixer. So to keep my older json 3D objects librairies working I copied MorphAnimMesh.js Animation.js  AnimationHandler.js and KeyFrameAnimation.js into my javascript lib. But now I get "data hierarchy undefined" error. Does this mean I have to RE-export all my former 3D json objects from Blender or is there a way the keep these working ?

**Comment by derivou** [comment]
Hello, Nobody to help with "undefined data.hierarchy" ?

**Comment by mrdoob** [comment]
Please, use StackOverflow for help.

**Comment by akoskm** [comment]
> Doing a release involves quite a few steps. Sometimes my patience/dedication runs out... :confused:
Anyone can update the migration page. I would love to get some help there.

I recently run into this problem using an older version of three.js.

But after reading through the comments and seeing the insults you received, instead of asking for help, I just wanted to thank you for maintaining three.js.

You're a super dedicated and patient guy! :+1:

**Comment by q2apro** [comment]
The update was a bunch of work (~3 hours for one project). 

Helpful: 
- For the font issue: see source code of http://necromanthus.com/Test/html5/koolmoves.html (you do not load the font in HTML anymore, but instead in JS, assign a var and this goes into the parameters. Watch out to only assign the font AFTER it has been loaded)
- see the error messages in the dev console, they help a lot, because they even tell you what to do (good work @mrdoob )
- also take a look at https://github.com/mrdoob/three.js/wiki/Migration-Guide
