### ISSUE TITLE
Remove Unnecessary console.log

### ISSUE THREAD

**Issue by francoislaberge** [mrdoob/three.js#7362]
[This console.log should be stripped out IMHO](https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L10). Many devs, myself obviously included like to have a clean console output. Every library that is chatty adds up to a messy console:

**Comment by francoislaberge** [comment]
I made a PR, if it matters for such a small change:
https://github.com/mrdoob/three.js/pull/7363

**Comment by francoislaberge** [comment]
Oh and for more context, if I was just downloading three.js to use regularly on a website I could just customize my own distribution, but I'm using npm as it's a nicer workflow and then this isn't feasible without some hacky postinstall script.

**Comment by mrdoob** [comment]
#5835
