### ISSUE TITLE
json scene look wrong on ipad

### ISSUE THREAD

**Issue by spinacius** [mrdoob/three.js#7364]
Hi, i am using ObjectLoader to load a json file exported from Unity3d in a threejs scene. It looks right on desktop, but on an ipad air (ios9) it looks wrong, as you can see in these scrennshots:

![schermata 2015-10-16 alle 22 08 23](https://cloud.githubusercontent.com/assets/8000509/10553425/e9c06a8a-745a-11e5-8fff-2fb5a45bac6d.png)

![img_0145](https://cloud.githubusercontent.com/assets/8000509/10553466/4076d1e8-745b-11e5-975e-5aab272f7d2b.png)

Any idea on which could be the problem and how to solve?

Thanks in advance!

**Comment by mrdoob** [comment]
Can you share a live link so we can debug it?

**Comment by spinacius** [comment]
Hi! Yes, here i've upload the test project: https://test-ipad.herokuapp.com

**Comment by liammagee** [comment]
It looks like the offending line is actually in style.css:

styles/style.css:11
background-color: blue;

If you comment that out, the rendering on Safari/Chrome on the iPad matches
the desktop rendering.

**Comment by WestLangley** [comment]
A similar bug can be created using any three.js example if the CSS body background-color is set to some non-black color.

The renderer drawing buffer is blended with the CSS background color even if `alpha` is `false` in the renderer constructor.

Be aware that

    renderer.setClearColor( 0x000000, 0 );

will produce different results than

    renderer.setClearColor( 0x000000, 1 );

I see this on iPhone IOS 9.0.2.

**Comment by spinacius** [comment]
Thank you guys! Just changed background color to black and now works perfectly

**Comment by mrdoob** [comment]
Yeah, I remember iOS ignoring the `alpha` property. It's annoying that they haven't fixed it yet...
