### ISSUE TITLE
r73 - refreshUniformsShadow - shadow.matrix null runtime error

### ISSUE THREAD

**Issue by jarethgk** [mrdoob/three.js#7365]
In function: refreshUniformsShadow (about line 23232 in three.js on my version)

On line 23253 under:
shadow.matrix.identity().setPosition( _vector3 );

I am getting a trigger of:
Paused on exception: 'TypeError: Cannot read property 'identity' of null'.

I can get the code to go an process correctly by adding:
if (shadow.matric != null) 
in front of the offending statement.

In complete the line now reads:
if (shadow.matric != null) shadow.matrix.identity().setPosition( _vector3 );

When I do this the code works fine. (it seems)  I am not sure if this could break things down the road with other moving parts, and so I decided to mention it here so that other eyes more experienced can look over this and determine if this is the best fix, or if something better can be done.

Please let me know what the best fix for the problem I am experiencing would be, and/or if this may fix a larger bug.  My first time posting to a github project ever, and so I apologize if I may have done this incorrectly.  Let me know if I can provide better information to help update this issue.

Thank you,

x Jeremy M.

**Comment by mrdoob** [comment]
Hmm... Can you share the code that is producing that?

**Comment by jarethgk** [comment]
The 3d object being loaded is made in Maya, and is exported as an FBX which is then loaded into Clara.IO, and then exported out as the "ThreeJS (.json)".

I think it is getting into the "$scope.bodyLoader_onComplete()" and during the processing of putting it in the scene it is stumbling on the three.js code I mentioned above.


$scope.skeletal_Loader = new THREE.ObjectLoader();
        $scope.skeletal_Loader.load("models/skeleton/male-skeleton-ao.json",
        //$scope.skeletal_Loader.load("models/altTextures/skeletal/skeleton-landmarks.json",
            function(obj){ $scope.bodyLoader_onComplete(obj, $rootScope.SYSTEM_NAME.SKELETAL.WORD); },
            function(xhr){ $scope.bodyLoader_onProgress(xhr, $rootScope.SYSTEM_NAME.SKELETAL.WORD); },
            function(xhr){ $scope.bodyLoader_onError   (xhr, $rootScope.SYSTEM_NAME.SKELETAL.WORD); }
        );


$scope.bodyLoader_onComplete = function(obj, objLoadedName) { // onComplete
        //console.log("Starting onComplete function for: " + objLoadedName);
        //console.log(obj);
        $scope.bodySystem[objLoadedName] = obj;

        if (objLoadedName == $rootScope.SYSTEM_NAME.SKELETAL.WORD ||
            objLoadedName == $rootScope.SYSTEM_NAME.NERVOUS.WORD ||
            objLoadedName == $rootScope.SYSTEM_NAME.ENDOCRINE.WORD
        ) $scope.bodySystem[objLoadedName].rotation.y = Math.PI;

        $scope.bodySystem[objLoadedName].traverse(function(child) {
            child.name = child.name.toLowerCase();
            child.visible = true;
            child.frustumCulled = false;
            if (typeof child.material != "undefined") if (child.material != null) {
                child.material.transparent = false;
                child.material.opacity = 1;
                if (objLoadedName == $rootScope.REGION_2_NAME.SKIN_MALE.WORD) {
                    child.material.transparent = true;
                    child.material.opacity = $scope.model_transparent;
                }
                child.material.shininess = 15;
                //child.material.bumpScale = 0.12; // Uncomment and alter if default level of bumpiness is inappropriate. Save in case it needs to be changed.
                child.material_original = child.material; // Always clone the material last.
            }
        });

        //console.log("About to add to scene: " + objLoadedName);
        $scope.scene.add($scope.bodySystem[objLoadedName]);
        //console.log($scope.bodySystem[objLoadedName]);
        console.log("Done loading. Adding to scene. (" + objLoadedName + ") ");

        if (objLoadedName == $rootScope.SYSTEM_NAME.SKELETAL.WORD) $scope.spriteLoader();
        if (typeof $scope.bodySystem[$rootScope.SYSTEM_NAME.SKELETAL.WORD] != "undefined") $scope.addedToScene = true;

        $rootScope.changeSystemState($rootScope.systemState); // Must be after "addedToScene = true" or it won't properly fire off.
        $scope.$apply();
    };

**Comment by mkkellogg** [comment]
@jarethgk

It sounds like your instance of ```THREE.WebGLRenderer``` does not have shadows enabled, but you have them enabled on a point light in your scene. When shadowing is disabled in ```THREE.WebGLRenderer```, ```shadow.matrix``` will be null. Admittedly, the code in ```refreshUniformsShadow()``` should do a proper check either for enabled shadows or at the very least should check if ```shadow.matrix``` is null. 

I am not familiar with how Clara.io works - how easy would it be to verify that your renderer has shadowing enabled?

**Comment by mrdoob** [comment]
Fixed. Thanks!
