### ISSUE TITLE
static uniforms, UniformsUtils clone deep copy

### ISSUE THREAD

**Issue by pailhead** [mrdoob/three.js#7367]
Lets say i have shader material, and some property that makes the same shader appear as either plastic, metal, or wood...

```javascript

//magic parameter 
var _staticUniform = {
  type:'f',
  value: 1
};

var myPlasticRecipe = new THREE.ShaderMaterial({
  uniforms:{
    uniqueColor:{type:'c', value: new THREE.Color()},
    staticMaterialProperty: _staticUniform
  },
  vertexShader: someVShader,
  fragmentShader: someFShader
}

var redPlasticMaterial = myPlasticRecipe.clone();
redPlasticMaterial.uniforms.uniqueColor.value.setRGB(1,0,0);

var bluePlasticMaterial = myPlasticRecipe.clone();
bluePlasticMaterial.uniforms.uniqueColor.value.setRGB(0,0,1);
```
I'd like to change the magic parameter and affect all the materials without manually keeping track of everything, but since material.clone() calls uniformsUtils.clone() and does a deep copy the reference to the static uniform is lost. 

Not sure if this would be useful to anyone else, but having uniformsUtil look up a (optional) type and then decide wether to copy or make a reference could be helpful. Sometimes textures can be shared etc. Any thoughts?

**Comment by arose** [comment]
You should be able to assign the `_staticUniform` after cloning to get a shared uniform.

```javascript
//magic parameter 
var _staticUniform = {
  type:'f',
  value: 1
};

var myPlasticRecipe = new THREE.ShaderMaterial({
  uniforms:{
    uniqueColor:{type:'c', value: new THREE.Color()},
  },
  vertexShader: someVShader,
  fragmentShader: someFShader
}

var redPlasticMaterial = myPlasticRecipe.clone();
redPlasticMaterial.uniforms.uniqueColor.value.setRGB(1,0,0);

var bluePlasticMaterial = myPlasticRecipe.clone();
bluePlasticMaterial.uniforms.uniqueColor.value.setRGB(0,0,1);

redPlasticMaterial.uniforms.staticMaterialProperty = _staticUniform;
bluePlasticMaterial.uniforms.staticMaterialProperty = _staticUniform;
```

Now setting `_staticUniform.value` should be reflected in the red and the blue material.

**Comment by arose** [comment]
However, note that the above uniform sharing will not carry over in a `.toJSON`/`.fromJSON` cycle.

**Comment by pailhead** [comment]
i know that anything can be written and wrapped around this, pass a few parameters and get everything back hooked and configured.

But lets assume that this pattern up there is valid at least for some rough prototyping purposes. You can see where this can get quite complicated, if say i only want to change the color, share N textures over M materials, and have a dozen of these static parameters.

**Comment by arose** [comment]
Hmm, a helper function for cloning does not look too complicated:

```javascript
function myMaterialClone( material ){
    var newMaterial = material.clone();
    var uniforms = material.uniforms;
    if( uniforms ){
        for( var name in uniforms ){
            var u = uniforms[ name ];
            // share uniform when (custom) 'shared' property is set
            if( u.shared ){
                newMaterial.uniforms[ name ] = u;
            }
        }
    }
    return newMaterial;
}
```

I get your suggestion that it would be more convenient if the library has support for it built in; properly supporting it is likely more work then just changing `uniformsUtils.clone()`, e.g. serialization.

This behavior has been noted previously #6841, including the duplication of identical textures on the GPU #7223.

**Comment by mrdoob** [comment]
I guess we can start by doing `THREE.Uniform`?

```javascript

THREE.Uniform = funciton ( type, value ) {
    this.type = type;
    this.value = value;
};

THREE.Uniform.prototype = {
    constructor: THREE.Uniform,
    copy: function ( source ) {
        this.type = source.type;
        this.value = source.value;
    },
    clone: function () {
        return new this.constructor().copy( this );
    },
    toJSON: function () {
        return {
            type: this.type,
            value: this.value
        }
    }
}
```

**Comment by pailhead** [comment]
that doesnt really help this issue

```javascript
THREE.Uniform = funciton ( type, value , static ) {
    this.type = type;
    this.value = value;
    this.static = static || false;
};

THREE.Uniform.prototype = {
    constructor: THREE.Uniform,
    copy: function ( source ) {
        this.type = source.type;
        this.value = source.value;
    },
    clone: function () {
       
        return this.static ? this : new this.constructor().copy( this );
    },
    toJSON: function () {
        return {
            type: this.type,
            value: this.value
        }
    }
}
```

**Comment by mrdoob** [comment]
Would `reusable` be more intuitive?

**Comment by pailhead** [comment]
or "shared"?
