### ISSUE TITLE
Performance: Multiple tiny sprites 

### ISSUE THREAD

**Issue by magnitudoOrg** [mrdoob/three.js#7371]
There is a scene with some 3D objects and 200 - 300 small text labels (< 10% are visible to the camera at one perspective). Adding the text sprites decreases the FPS from 60 to 30 - 40. A bit too much FPS drop for some little text labels - for my taste.

Are there any plans to improve the performance for many small textures/sprites (or is there sth. wrong with the example)?
Test/Fiddle: https://jsfiddle.net/h9sub275/4/ 
**UPDATED**: https://jsfiddle.net/h9sub275/7/
(Click on the scene to see the difference between removeInvisible true/false! You can change SPRITE_COUNT to see an FPS drop on your machine/cpu/gpu)
http://stackoverflow.com/questions/33178177/three-js-sprite-text-label-performance

Thank you very much!

**Comment by Need4Speed402** [comment]
The problem here is most likely all the draw calls. Unfortunately, WebGL is not great at performing many draw calls like native OpenGL. You will need to consolidate everything into a single draw call. It sounds like with your situation you might be able to use geometry instancing. I don't think Three.js has great support for that though.

I would suggest using a special Scene object that you can add and remove from and having a setInterval set to 50ms to make sure that off screen elements are removed and therefore not rendered. You later add them back later when they are on screen again.

Looking at the amount of CPU the GPU process is using confirms my draw call suspicion:
![image](https://cloud.githubusercontent.com/assets/3621017/10569314/52af140e-75f2-11e5-9628-08af3947f05c.png) 6% is a nasty number on a Intel i7.

**Comment by magnitudoOrg** [comment]
Thank you @Need4Speed402! I created `THREE.RemoveInvisibleGroup` for dynamically removing objects depending on their camera frustrum visibility and it now the same scene is way faster with many sprites. :)

Improved FPS from 25 to 60 for 1500 sprites on this laptop+chrome here. You can try it out here:
https://jsfiddle.net/h9sub275/6/  (change `Test.SPRITE_COUNT` to see an FPS drop on your machine/cpu/gpu; just **click on the scene** to see the difference between removeInvisible true/false!)

If @mrdoob considers this to be useful, the fiddle can be refined and maybe added to examples or so. Further suggestions for improving are welcome.

```javascript
    /**
     * Automatically adds/removes all children which are (in)visible to the camera to a temporary group 
     * if the removeInvisible flag is true.
     * 
     * This code is just the raw idea and not optimized or refined yet.
     * 
     * @author Oliver G. / http://magnitudo.org/
     */    
    THREE.RemoveInvisibleGroup = function (camera) {
    
        THREE.Object3D.call( this );
                
        this.camera = camera;
        this.removeInvisible = true;
        this.removedObjGroup = new THREE.Object3D(); 
    };
    
    THREE.RemoveInvisibleGroup.prototype = Object.create( THREE.Object3D.prototype );
    THREE.RemoveInvisibleGroup.prototype.constructor = THREE.RemoveInvisibleGroup;  
    THREE.RemoveInvisibleGroup.prototype.update = function() {

    	var i, obj;
    	if ( this.removeInvisible ) {

    		for ( i = 0; i < this.children.length; i ++ ) {

    			obj = this.children[ i ];
    			if ( ! this.checkFrustrum( obj ) ) {

    				this.removedObjGroup.add( obj );
    				this.remove( obj );

    			}

    		}
    		for ( i = 0; i < this.removedObjGroup.children.length; i ++ ) {

    			obj = this.removedObjGroup.children[ i ];
    			if ( this.checkFrustrum( obj ) ) {

    				this.add( obj );
    				this.removedObjGroup.remove( obj );

    			}

    		}

    	} else {

    		// ensure removedObjGroup is empty after removeInvisible flag changed
    		for ( i = 0; i < this.removedObjGroup.children.length; i ++ ) {

    			obj = this.removedObjGroup.children[ i ];
    			this.add( obj );
    			this.removedObjGroup.remove( obj );

    		}

    	}

    	//console.log('visible: ' + this.children.length, ' invisble: ',this.removedObjGroup.children.length);
    };
 
    // from http://stackoverflow.com/questions/29992594/three-js-conversion-from-3d-perspective-scene-to-2d-orthographic-hud-scene
    THREE.RemoveInvisibleGroup.prototype.checkFrustrum = function ( obj ) {
        var frustum = new THREE.Frustum();
        var projScreenMatrix = new THREE.Matrix4();
    
        this.camera.updateMatrix();
        this.camera.updateMatrixWorld();
    
        projScreenMatrix.multiplyMatrices( this.camera.projectionMatrix, this.camera.matrixWorldInverse );
    
        frustum.setFromMatrix( new THREE.Matrix4().multiplyMatrices( this.camera.projectionMatrix,
                                                         this.camera.matrixWorldInverse ) );
        return frustum.containsPoint ( obj.position );
    };
```

**Comment by Need4Speed402** [comment]
I would recommend adding some kind of buffer space as some text labels are prematurely endearing at the edges.

**Comment by mrdoob** [comment]
Strange.... Sptires not in frustum shouldn't be producing any drawcalls. Is the frustum check the problem?

**Comment by magnitudoOrg** [comment]
@mrdoob It looks like there is a problem with the frustum check for sprites. Else there wouldn't be such a big performance difference between manually removing objects not in the frustrum and not removing them (if you try the same with other geometry like a cube, there is no performance difference).

Updated Test: https://jsfiddle.net/h9sub275/7/ (Click to see the difference.)

I don't know the WebGLRenderer internals, maybe someone of the authors can debug this quicker. If I find some time, I ll try it too.

@Need4Speed402 I updated the fiddle - top left and bottom right will be checked with checkBounds=true, it could be further refined to check all bounds. But maybe we don't need this work-around any more when it is fixed in the three.js renderer.

**Comment by mrdoob** [comment]
Well, turns out `WebGLRenderer` was not frustum culling Sprites!
I guess I must have remembered implementing that in `CanvasRenderer` instead...

**Comment by mrdoob** [comment]
Fixed. Thanks! 😅

**Comment by mrdoob** [comment]
https://jsfiddle.net/h9sub275/9/

**Comment by magnitudoOrg** [comment]
Thank you for fixing! :-)
