### ISSUE TITLE
Converting FBX file using convert_to_threejs.py

### ISSUE THREAD

**Issue by oculushut** [mrdoob/three.js#7372]
I am trying to use the python utility included with Three.js to convert a FBX file into the Three.js format.

Specifically, I am trying to execute the following:

```
convert_to_threejs.py
```

I have Python 2.7.3 installed.  I know that the recommended version is 2.6 or 3.1 according to some Autodesk documentation and in the Three.js README file.  However, the latest copy of the Autodesk SDK included files for 2.7... so I gave it a go.  This also worked on my Windows dev box.

I have tried the same thing on my production box.  This is a Linux box.  However, even after copying the SDK files to the Python site-packages directory (3 files) I still get the following message:

```
Could not locate the python FBX SDK!
You need to copy the FBX SDK into your python install folder such as "/usr/local/lib/python2.6/site-packages" folder.
```

For information, I used the following Python output to determine where I should copy my SDK files:

```
>>> import site; site.getsitepackages()
['/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages', '/usr/lib/site-python']
```

I copied the SDK files into '/usr/lib64/python2.7/site-packages'.

Any tips?

**Comment by oculushut** [comment]
OK... looks like it was my issue - sorry!

I am on a CentOS box.  The versions that Autodesk now provide for Linux are as follows:

Directory name|	Python version, machine type
---------------------|------------------------------------------------
Python27_x64|	2.7, 64-bit, 2-byte Unicode characters
Python33_x64|	3.3, 64-bit, 2-byte Unicode characters
Python27_ucs4_x64|	2.7, 64-bit, 4-byte Unicode characters
Python33_ucs4_x64|	3.3, 64-bit, 4-byte Unicode characters

Reference: http://help.autodesk.com/view/FBX/2016/ENU/?guid=__files_GUID_CBF90ED2_798D_42E8_91DA_2AD0D3E82739_htm

I created a file with the following only:

```
import FbxCommon
```

I then copied over the Python27_x64 files that I thought I needed into the same folder.

I ran the following:

```
python [name of my python file]
```

And it generated the following error:

```
ImportError: [MY PATH]/fbx.so: undefined symbol: PyUnicodeUCS2_DecodeASCII
```

So, apparently this means that my OS interprets unicode with 4 bytes instead of 2... who knew!

Anyway, I deleted the files from Python27_64 and used the ones from Python27_ucs4_x64.

... and then everything looks happy again now!

**Comment by oculushut** [comment]
I will report back if there are any issues... not closing this yet as I guess there is an argument to say that the README.md should be updated to say that some users should look at using Python 2.7 and [FBX 2016](http://help.autodesk.com/view/FBX/2016/ENU/?guid=__files_GUID_105ED19A_9A5A_425E_BFD7_C1BBADA67AAB_htm)?

I don't know enough about this topic to know if the above is the right recommendation...

**Comment by looeee** [comment]
@oculushut can we close this issue now?

**Comment by oculushut** [comment]
Please do - thanks!
