### ISSUE TITLE
FlatShading on custom ShaderMaterial

### ISSUE THREAD

**Issue by andrevenancio** [mrdoob/three.js#7373]
I've writtent [this](http://stackoverflow.com/questions/33094496/three-js-shadermaterial-flatshading?noredirect=1#comment54049117_33094496) stackoverflow question a couple of days ago, and I've been struggling to find an answer to it online and I've been trying for the past few days.
I need to write a custom ShaderMaterial that integrates with Threejs light and fog. I manage to get it done, but I can't seem to have the FlatShading to work.
The vertices are being changed with a noise function on the vertexShader, so I assume the normals would have to be calculated also in the vertexShader? Maybe someone went through this already and could point me out in the right direction..?

Thank you

**Comment by WestLangley** [comment]
[Answer](http://stackoverflow.com/a/33205655/1461008) posted on SO.
