### ISSUE TITLE
Cloned rotation is incorrect after 180 degree rotation

### ISSUE THREAD

**Issue by sunjay** [mrdoob/three.js#7375]
Here's a quick test program that demonstrates the issue: http://jsfiddle.net/sunjay03/bn2ukae6/

I think the relevant source code is here (though you'll know better than I do): https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L736

This is with the latest r73.

The problem is that for certain rotations, most notably 180 degree rotations, the cloned rotation is not the same as the original rotation. 

So you'll start with a simple 180 degree rotation like this (Euler angles):

    Euler: [0, 3.141592653589793, 0 ,"XYZ"]

And after cloning it'll be like this: (usually that zero is actually just a value very close to zero)

    Euler: [3.141592653589793, 0 ,3.141592653589793,"XYZ"]

This is equivalent, but not the same. Programs relying on that Y rotation stop working because the rotation has instead been transferred to the other two components.

**Comment by WestLangley** [comment]
> Programs relying on that Y rotation stop working because the rotation has instead been transferred to the other two components.

Euler rotations are not unique. Do not assume they are in your code.

**Comment by sunjay** [comment]
@WestLangley @mrdoob 

> Euler rotations are not unique. Do not assume they are in your code.

That's fair, and I understand that mathematically, but contract-wise it isn't right.

The `clone()` method's documentation says 

> Creates a new clone of this object and all descendants.

Which means that the new object's properties should be the same as the source object's properties. The `clone()` method should not result in a different rotation value, even if the two are equivalent.

Is there some way to easily set the rotation to the source object's rotation? Since the rotations are equivalent anyway, why not just have the same one exist for the cloned object?

----
If for some reason that's not feasible? How can someone go about accounting for equivalent euler rotations? Is there a way to convert from one equivalent rotation to another?

Thanks

**Comment by WestLangley** [comment]
> Is there some way to easily set the rotation to the source object's rotation?

object.rotation.copy( source.rotation );

three.js is quaternion-based. The cloned object should have the same quaternion as the original object.

Do not rely anywhere in you code on two object with the same orientation having the same Euler representation.

The quaternions of two objects with the same orientation will either be identical, or they will be the negation of one another.

---

If you are rotating around the Y-axis only, then set `object.rotation.order = 'YXZ';` That may solve your problem for that particular case. If not, post details of your use case on [stackoverflow](http://stackoverflow.com/questions/tagged/three.js) to get help.

**Comment by sunjay** [comment]
> `object.rotation.copy( source.rotation );`

Would it work to just add that to the `copy()` method so that the rotation is the same? If not, maybe a note in the documentation might help. That way at least people will know that there's no guarantee their Euler rotations will be the same after a `clone()`.

> If you are rotating around the Y-axis only, then set `object.rotation.order = 'YXZ';`

Thanks! That seems to work. I'll try to use quaternions next time.
