### ISSUE TITLE
OrbitControls pinch to zoom moves camera only to center of screen

### ISSUE THREAD

**Issue by agnivade** [mrdoob/three.js#7384]
Hi there,

I have been testing with OrbitControls on a touchscreen. And when using zoom with pinch to zoom, the camera always moves to the center of the screen regardless of where you are zooming. That is not the expected behavior of a normal pinch-to-zoom interface. The area where it is pinched should zoom i.e. - the center of the pinched area should remain at the center after zooming.

I have been trying to implement this feature. But it is not working as perfectly as I would like it to be. I was wondering whether you guys have any thoughts on this ?

**Comment by blahmonkey** [comment]
To clarify (Im working with the OP here) - it is always 'zoom from the origin'. Unlike a mobile device where pinching on a point to zoom zooms from that point. 

e.g if you have a point e.g 100,100 in screen co-ordinates, pinching around that point to zoom takes it out of the screen, which it shouldnt - the point should stay fixed.

**Comment by WestLangley** [comment]
You are not simply zooming an image here.

`OrbitControls` has a `target` around which it rotates, and the camera always looks at the target.

What you are seeing is the camera zooming along its line-of-sight.

To pinch-and-zoom to another point in screen-space would require that the camera `target` to be moved. That would affect not only the point at which the camera is looking, but the rotational center, too.

It is not clear to me that adding such behavior would be advisable.

Your current work-around is to zoom and pan.

**Comment by blahmonkey** [comment]
WestLangley - kind of expected you to chime in, but didn't expect it to be so quick!

I agree with you, there is no point making this behaviour intrinsically part of the dolly motion (i.e manipulating the camera target etc.)

What seems to make more sense for us (and perhaps others as well) is to have the dolly (optionally?) operate in zoom-and-pan mode.

We've been trying to do that, pre-pan, but its a little hard figuring out the logic to do so precisely (we're using the dolly scale i.e ratio of distance at the first touch and the next touch, in the touchmove function. And then applying the scale to the relative screen co-ordinates of the pinched point.

This unfortunately results in very imprecise and uncontrollable pans at times when zooming.

Do you have any references for such a work-around in action so we can examine what we are missing?

**Comment by WestLangley** [comment]
Sorry, I do not have any such references.

**Comment by mrdoob** [comment]
I've seen that behaviour in https://lmv.rocks/
No idea how they do it, but I also don't it tricky to deal with.

**Comment by mrdoob** [comment]
I've seen that behaviour in https://lmv.rocks/
No idea how they do it, but I also find it tricky to deal with.

**Comment by arodic** [comment]
I have the image-like pinch to zoom behavior implemented in editorControls [here](https://github.com/arodic/three.js/blob/EditorControls/examples/js/controls/EditorControls.js) but only for orthographic cameras (which do not orbit).

As @westlangley pointed out, doing this with orbiting cameras would require orbit target to move (sometimes drastically) which might feel unintuitive for most users.

**Comment by arodic** [comment]
Ping @nopjia how did you do it?

**Comment by nopjia** [comment]
Yes, we are always repositioning the target with every pinch action. The target is set to be the geometry under the pinch location. That is, at the start of every pinch action, we ray cast from the location of the pinch, and take the first intersection as the target. If there is no intersection, we set the target as a point along the ray at the same distance as the last target. This heuristic seems to work pretty well for us.

**Comment by agnivade** [comment]
Thanks @nopjia  - this was very helpful.

**Comment by blahmonkey** [comment]
nopjia - agree with @agnivade that sounds like it may work as a general solution! 

Do you have code where we can examine this in more detail? I've looked at lmv-gallery/lmv-viewer, and even the autodesk firefly.js. But there is quite a lot of ground to cover there so a more precise pointer would help.

**Comment by mrdoob** [comment]
Thanks for the explanation @nopjia! Sounds pretty simple to implement 😊

**Comment by blahmonkey** [comment]
We got this working (tried nopjia's solution, but I think thats a bit beyond my level of expertise)

We basically changed zoom to zoompan, doing both zoom + pan in touchmove, using the value of the scale variable post computation by dollyIn/dollyOut. The calculations and continuity across multiple touchmove calls needed a little work, but its now working very nicely :)
