### ISSUE TITLE
r72 Collada Loader

### ISSUE THREAD

**Issue by hdesouky** [mrdoob/three.js#7385]
After upgrading from r68 to r72 i faced many issues for moving my old code to the new release since many methods a re removed and many prototypes are modified.

However every thing went very well until i faced weird problem with my model when loading it from collada loader.

I attached to the issue to images showing how r72 collada loader distorted the models.

Note this model is exported from blender to collada format. The distorted model elements are models imported to blender, then mirrored and recalculated its normal's.

Am i missing something or my model is defective?
![r68](https://cloud.githubusercontent.com/assets/2395913/10612361/b4d7b834-7750-11e5-8f80-a6263ca0051d.png)
![r72](https://cloud.githubusercontent.com/assets/2395913/10612360/b4d686c6-7750-11e5-8940-5604705884ed.png)

**Comment by WestLangley** [comment]
If you can demonstrate a three.js bug, can you provide a test case so we can reproduce your results? Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

If you do provide a test case, please make it a single-tooth model for simplicity.

**Comment by mrdoob** [comment]
@hdesouky can you try with this ColladaLoader r71 but maintaining three.js r72?
https://github.com/mrdoob/three.js/blob/r71/examples/js/loaders/ColladaLoader.js

**Comment by hdesouky** [comment]
@mrdoob you are right, this fixed the problem. Thanks for your support.

@WestLangley i will do so next time. If you want i can share the tooth model.
