### ISSUE TITLE
Smooth Derivative Bump/Normal Maps.

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#7386]
I found this article which explains how to solve the pixelating artefacts in derivative maps. In all honesty, it goes a bit over my head and I'm not sure if it can be implemented in glsl but I'm sharing here in case someone wants to give it a go.

http://www.rorydriscoll.com/2012/01/11/derivative-maps/

Current code:
https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderChunk/bumpmap_pars_fragment.glsl
https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderChunk/normalmap_pars_fragment.glsl

**Comment by makc** [comment]
TL;DR, the article discusses the effects of replacing
```glsl
// Calculate the surface normal using screen-space partial derivatives of the height field
float3 CalculateSurfaceNormal(float3 position, float3 normal, float height)
{
    float3 dpdx = ddx(position);
    float3 dpdy = ddy(position);
 
    float dhdx = ddx(height);
    float dhdy = ddy(height);
 
    return PerturbNormal(normal, dpdx, dpdy, dhdx, dhdy);
}
```
with
```glsl
float ApplyChainRule(float dhdu, float dhdv, float dud_, float dvd_)
{
    return dhdu * dud_ + dhdv * dvd_;
}

// Calculate the surface normal using the uv-space gradient (dhdu, dhdv)
float3 CalculateSurfaceNormal(float3 position, float3 normal, float2 gradient)
{
    float3 dpdx = ddx(position);
    float3 dpdy = ddy(position);
 
    float dhdx = ApplyChainRule(gradient.x, gradient.y, ddx(uv.x), ddx(uv.y));
    float dhdy = ApplyChainRule(gradient.x, gradient.y, ddy(uv.x), ddy(uv.y));
 
    return PerturbNormal(normal, dpdx, dpdy, dhdx, dhdy);
}
```
Your code has 
```glsl
vec3 perturbNormalArb( vec3 surf_pos, vec3 surf_norm, vec2 dHdxy ) {
```
the difference here is that you calculate dHdxy outside - so this is not the chunk you are looking for.

**Comment by mrdoob** [comment]
Look at the `bumpmap_pars_fragment.glsl` one.

**Comment by makc** [comment]
> Your code has

that was from bumpmap_pars_fragment.glsl

**Comment by makc** [comment]
ah, you mean that other function dHdxy_fwd() is where that is calculated.

**Comment by makc** [comment]
went to [3js demo](http://threejs.org/examples/webgl_materials_bumpmap.html) to see how it looks like here, `camera.position.z = 300` in console gives this:
![screen shot 2015-10-22 at 18 31 24](https://cloud.githubusercontent.com/assets/242577/10671531/4c617b68-78eb-11e5-9b86-7f4a7a94db27.png)

**Comment by mrdoob** [comment]
Yep. Get closer...

![screen shot 2015-10-22 at 12 34 42](https://cloud.githubusercontent.com/assets/97088/10671574/538dc194-78b9-11e5-91ad-7c997494c8bd.png)

**Comment by makc** [comment]
Well, what I did right now:
```glsl
	vec2 dHdxy_fwd() {

		float Hll = bumpScale * texture2D( bumpMap, vUv ).x;
		float dBx = bumpScale * texture2D( bumpMap, vUv + vec2 (1.0/4096.0, 0.0) ).x - Hll;
		float dBy = bumpScale * texture2D( bumpMap, vUv + vec2 (0.0, 1.0/4096.0) ).x - Hll;

		return vec2( dBx, dBy ) * 4096.0;

	}

float ApplyChainRule(float dhdu, float dhdv, float dud_, float dvd_)
{
    return dhdu * dud_ + dhdv * dvd_;
}

	vec3 perturbNormalArb( vec3 surf_pos, vec3 surf_norm, vec2 gradient ) {
		
    vec3 dpdx = dFdx(surf_pos);
    vec3 dpdy = dFdy(surf_pos);

    float dhdx = ApplyChainRule(gradient.x, gradient.y, dFdx(vUv.x), dFdx(vUv.y));
    float dhdy = ApplyChainRule(gradient.x, gradient.y, dFdy(vUv.x), dFdy(vUv.y));
		
		vec2 dHdxy = vec2 ( dhdx, dhdy );

		// no change from this point
		vec3 vSigmaX = dFdx( surf_pos );
```
resulted in the image no different from what you have:
![screen shot 2015-10-22 at 18 50 37](https://cloud.githubusercontent.com/assets/242577/10672074/152f627e-78ee-11e5-9a21-5d3c31a7824d.png)

**Comment by makc** [comment]
here it is at z = 230 - you can see pixels are kind of smoothed out, but not exactly enough to make a difference:
![screen shot 2015-10-22 at 18 56 48](https://cloud.githubusercontent.com/assets/242577/10672191/c67ff07a-78ee-11e5-83a9-e448e51af306.png)

**Comment by makc** [comment]
2048 instead of 4096 kind of looks better at z=300
![screen shot 2015-10-22 at 18 59 53](https://cloud.githubusercontent.com/assets/242577/10672263/2abaf170-78ef-11e5-838a-16f3a5b1b4a1.png)

**Comment by makc** [comment]
dpdx is not needed, it is vSigmaX in your original code (same for y)

**Comment by makc** [comment]
> 2048 instead of 4096

that does not mean using half the resolution, that's just texture(uv + 2 * delta) / 2 * delta instead of texture(uv + delta) / delta, sort of large step gradient.
