### ISSUE TITLE
onGeometryDispose is not deleting BufferGeometry index attribute

### ISSUE THREAD

**Issue by nihowjipa** [mrdoob/three.js#7389]
onGeometryDispose method in WebGLGeometries is not deleting BufferGeometry "index" attribute causing memory leak on GPU side if geometries are using indexed triangles. Reproducible at (open chrome task manager and observe GPU process):

http://threejs.org/examples/webgl_test_memory.html

I was able to fix it locally by adding following to the method:

if ( buffergeometry.index ) deleteAttribute( buffergeometry.index );

r73

**Comment by mrdoob** [comment]
Well, this is embarrassing...

**Comment by mrdoob** [comment]
Fixed. Thanks!
