### ISSUE TITLE
Texture sourceFile is always empty and not setted in r73

### ISSUE THREAD

**Issue by markcell** [mrdoob/three.js#7390]
The attribute "sourceFile" in texture is not defined in both "THREE.ImageUtils.loadTexture" and "THREE.TextureLoader", so it is always empty.

Thanks

**Comment by mrdoob** [comment]
Yeah. I thought that was a bit of a hack. `Texture` doesn't have such property so I removed it.
What's your use case?

**Comment by markcell** [comment]
I use this attribute to apply the same texture on adjacent objects. I do not know if it's the best approach.

**Comment by mrdoob** [comment]
Because every `Texture` has it's own image, right? If `Texture`s could share images your patch wouldn't be needed. Right?

**Comment by Leeft** [comment]
Not sure if it helps: I've found that (thanks to `WebGLProperties` and how `WebGLRenderer` uses that in `uploadTexture()`) that after a `.clone()` of a `Texture` setting its `.uuid` identically to the source of the clone, it'll happily share the memory. There may be side effects to doing this (I'm not sure yet what'll happen on a `.dispose()` on one of these clones) but so far so good for me. I just published a library which makes use of this "undocumented feature" ... https://github.com/Leeft/three-sprite-texture-atlas-manager/blob/v0.0.4/src/knapsack-node.js#L33

**Comment by Mugen87** [comment]
Closing in favor of #17766.
