### ISSUE TITLE
Threejs garbage collection behaviour

### ISSUE THREAD

**Issue by rmarques-realstatus** [mrdoob/three.js#7391]
Hi,

I noticed something when trying to remove everything from a threejs scene. I'd like to know if it's a bug, or an expected behaviour.

Consider the following examples (that I quickly scribbled):

http://jsfiddle.net/tmbkw2wy/3/
http://jsfiddle.net/tmbkw2wy/4/

The first example releases resources as it's expected, while the second has the threejs' structures remain in heap memory even after they're disposed of. One can check this by taking heap snapshots (with chrome's dev tools for instance) after adding and removing the "tubes" once.

Is this behaviour valid? Do I always have to render 1 more time after removing meshes from a scene, and disposing of their geometries+materials?

Cheers

**Comment by mrdoob** [comment]
I'm comparing both jsfiddles and the `removeTubes()` function looks identical...?

**Comment by rmarques-realstatus** [comment]
The difference is in the `animate`function.

The first jsfiddle has an extra *render* which results in the tubes being garbage collected. The second fiddle has that render commented out, which results in the tubes staying in heap memory

**Comment by mrdoob** [comment]
Right, so you're saying that the renderer needs to render in order to clean up.

I think I know why that's happening. @tschw we probably should set empty `opaqueObjects` at the end of `render()`. However, the browser won't be able to remove the references with the `opaqueObjects.length = opaqueObjectsLastIndex + 1` optimisation. In fact, I wonder if even doing `opaqueObjects.length = 0` would hint the browser to remove the references, probably not 😕

**Comment by tschw** [comment]
@mrdoob 
> I wonder if even doing opaqueObjects.length = 0 would hint the browser to remove the references, probably not 

Pretty sure it would and the entries above the write index are actually properly disposed. Setting `.length` to zero would ruin the optimization and require us to allocate all the objects every frame again.

The automatic approach would be to set all references on the entries to `null` at the end of each frame, but that's another iteration. Another option is to add a `.purgeCache` method for the rare case that someone really wants to both keep the site running and stop rendering for good ;-).

In either case you can never get rid of all the objects. Static temps will still be kept unless you `THREE = null;`:
```javascript
THREE.Class.prototype.method = ( function() { 

    var staticTemp = new THREE.Vector3();

    return function actualMethod( args ) {
        // [...]
    };

} )();
```

**Comment by mrdoob** [comment]
Yeah, maybe we could just add `renderer.dispose()`.

**Comment by tschw** [comment]
And tear it down destructively? Emptying that array would keep the renderer functioning, but there might be more one could throw away, but you may as well just do `renderer = null`, no?

**Comment by mrdoob** [comment]
Yeah... I guess is not so much of a bug... If the idea is to do only one render and be done, `renderer = null` is a good solution.

So the reported issue is a price we have to pay for performance.

**Comment by tschw** [comment]
> I guess is not so much of a bug...

No. Actually just the renderer caching stuff between frames.

> So the reported issue is a price we have to pay for performance.

A method to explicitly empty that cache could be useful when loading multiple large scenes (e.g. levels of a game), so you can ensure that one gets thrown away before the next is loaded into memory, though.

```javascript
this.purgeCache = function() {
    whateverRenderItems.length = 0;
    moreRenderItems.length = 0; // don't remember the exact names
};
```

**Comment by rmarques-realstatus** [comment]
Right now doing `render=null` is not enough, as you still need that extra `render()` call: http://jsfiddle.net/tmbkw2wy/5/

What should be the appropriate approach if one wants to completely empty the scene, and stop the rendering, while leaving other parts of the page (non threejs/webgl ones) still functional?

**Comment by tschw** [comment]
> doing renderer=null is not enough

Heap snapshot shows the renderer is still there.

```javascript
var domParent = renderer.domElement.parentElement;
domParent.removeChild( renderer.domElement );
renderer = null;
```
seems to do the trick. But I'm not really sure why it's needed.

**Comment by rmarques-realstatus** [comment]
Cool, thanks =)

**Comment by tschw** [comment]
> But I'm not really sure why it's needed.

At some point it occurred to me that is must be the event handlers, of course ;-)
