### ISSUE TITLE
Further improvements to MeshPhysicalMaterial

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#7397]
So here are the thigns that I noticed that can be improved on MeshPhysicalMaterial:
- **(UPDATE: addressed in PR #7419)** The "reflectivity" parameter should control the created specularColor within the range of 0 to 0.08 or so (I'd prefer we use the upper bound of 0.18 that UE4 uses.)  If we did this we would not need to use it separately than specularColor in the SpecularLightProbe.  Remember that specularColor is F0, frontal reflectivity.
- **(UPDATE: addressed in PR #7417)** Metalness = 1 should result in the tinting of the fresnel environment reflection to the base color -- the grazing angles should be the baseColor rather than white.  Right now we are not taking into awareness of Metalness in the BRDF_Specular_GGX_Environment.  This means that metals are reflected white on grazing angles, which is not physically correct. 
- Add the ability to be energy conserving.  The standard approach is to scale down the diffuseColor by ( 1 - average( specularColor ) ), where specularColor is after frenel modification.
- **(UPDATE: addressed in PR #7421)** Need to add support for "irradiance", e.g. DiffuseLightProbe.
- **(UPDATE: addressed in PR #7420)** When roughness is 0, the surface is not rough enough.  There is most likely a scaling bug in the code somewhere.
- Create a SpecularLightProbe and DiffuseLightProbe structure that includes position -- this will allow for multiple to be situated in a level.
- **(UPDATE: addressed in PR #7414)** We probably need to use a different approach than this for the querying of the different LOD levels of the cube map as it doesn't work on a lot of devices:

```
float bias = pow( roughness, 0.5 ) * 7.0; // from bhouston - there are other models for this calculation (roughness; not roughnesFactor)
vec4 envMapColor = textureCubeLodEXT( envMap, flipNormal * vec3( flipEnvMap * reflectVec.x, reflectVec.yz ), bias );
```

I understand the best way is to encode into the alpha channel the LOD level and then use that to bias up or down as necessary.  It requires two queries but it should work on all devices that use cube maps.
- We are relying upon seamless cubemaps, but actually that is against the WebGL 1.0 spec.  We should probably figure out a way to filter the cubemaps.  I know @WestLangley was looking into this.  could be a solution for the irradiance cubeMaps as well.  I created a bug for the PMREM generator here: https://github.com/mrdoob/three.js/issues/7402

**Comment by mrdoob** [comment]
> We are relying upon seamless cubemaps, but actually that is against the WebGL 1.0 spec. 

Would it be a good idea to use @tschw cubeToUV() method instead of cube maps?

https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderChunk/shadowmap_pars_fragment.glsl#L33-L102

**Comment by bhouston** [comment]
I should have been more specific, the issue is with the automatically generated CubeMap LOD levels.  WebGL 2.x and OpenGL ES 3.x require them to be generated seamlessly, but in WebGL 2.0 and OpenGL EX 2.x the spec says that they are not seamless.  But strangely, ANGLE does seamless CubeMap LOD generation, so I wrote the above code that relies on this, but it is out of spec behavior.  We should use a spec-based method.  More details:  https://code.google.com/p/chromium/issues/detail?id=479753

**Comment by tschw** [comment]
> Would it be a good idea to use @tschw's cubeToUV() that PointLight shadows use?

No problem to filter seamlessly when filtering in software... Single-image cubemaps may also give better performance when generating the LOD levels.

> WebGL 2.x and OpenGL ES 3.x require them to be generated seamlessly [ ... ] We should use a spec-based method.

Still there are no guaranteed filters for automatic mipmap generation which can be a problem when using them for roughness. There is a recommendation to use box filters, IIRC, but Gaussians happened to look much nicer for me. So even with WebGL 2 we may want to generate the LOD levels manually.

![materials_metals](https://cloud.githubusercontent.com/assets/3916357/10654456/e63e99d6-786a-11e5-98d2-cfb885c1f332.jpg)

**Comment by bhouston** [comment]
We should always generate the LOD levels manually if possible using proper filters, the auto-generated stuff actually looks pretty horrible and we need a filter for irradiance mapping anyhow. :)

I've seen people also only generate 4 LOD levels as well, rather than a full set.  I'm not attached to cubemaps or single image textures.

The only complication is if you want to use a live specular light probe.  UE4 does this.  This requires fast filtering and maybe necessary to use HW cube map generation or we can just not do LOD and use it only for sharp specular reflections.

**Comment by bhouston** [comment]
@tschw I've outlined what I view as the design requirements for the PMREM generator here along with a link to sample code: https://github.com/mrdoob/three.js/issues/7402

**Comment by mattdesl** [comment]
Hey @bhouston I'm looking to use irradiance maps for rough surfaces in WebGL2, is there a particular branch or issue I should be poking through for some of this stuff? I've noticed lots of mentions of PhysicalMaterial, but now it seems to be StandardMaterial?

**Comment by WestLangley** [comment]
@mattdesl `MeshStandardMaterial` is the three.js PBR material. It has room for enhancement.

For experiments prior to implementing `MeshStandardMaterial` see https://github.com/mrdoob/three.js/pull/7421#issuecomment-152748071.

**Comment by bhouston** [comment]
@mattdesl We (myself and @spidersharma03) should have a PR in the next few days that has correct irradiance maps, along with a tool for generating them in real-time.  It is based on the work here, but taken further: https://github.com/mrdoob/three.js/pull/7902  So give it a few days and you'll get something good.

**Comment by mattdesl** [comment]
Amazing!

If you run into any road blocks or need help please ping me.

Also once it's all merged maybe we could see about a 3rd party node module that uses Electron to automate file processing en masse. 😁

**Comment by bhouston** [comment]
> Also once it's all merged maybe we could see about a 3rd party node module that uses Electron to automate file processing en masse.

Sure.  I'm of the opinion we should try to avoid requiring any pre-processing steps though - I hate pipelines, they just make things inflexible.  When I meant a tool I meant one that could generate them in real-time in milliseconds.  The best pipeline is no pipeline. :)

**Comment by mrdoob** [comment]
> The best pipeline is no pipeline. :)

👍!
