### ISSUE TITLE
r74dev missing FontUtils.js

### ISSUE THREAD

**Issue by poofik** [mrdoob/three.js#7398]
Where did you guys merge this too? Breaks all 3D fonts. Missing files.

/extras/FontUtils.js
/extras/geometries/TextGeometry.js

**Comment by mrdoob** [comment]
They were moved out of core. You can find them in the `examples` folder now.

```html
<script src="js/geometries/TextGeometry.js"></script>
<script src="js/utils/FontUtils.js"></script>
```

**Comment by mrdoob** [comment]
`TextGeometry` has been added back to core in `r74` (currently in `dev`).

**Comment by DarrenCook** [comment]
Where is FontUtils.js now?? It is not where you mention it above (https://github.com/mrdoob/three.js/tree/master/examples/js/utils ), but it is also not in core (i.e. not inside the r74 three.js file).

**Comment by DarrenCook** [comment]
OK, got it working! The things not being said explicitly enough here, and on #7360, are:

1. FontUtils is not there, as it is not needed any more.
2. Using FontLoader means you no longer need the `<script>` tag that was bringing in your font, so you must delete those `<script>` tags (unless you want to waste bandwidth *and* get a confusing error message).

**Comment by mrdoob** [comment]
@DarrenCook Glad that you figured it out. `TextGeometry` and `Font` shouldn't change much from now on. I just haven't been able to "design" that part until now. Sorry for the confusion!

**Comment by shelbeniskb** [comment]
@mrdoob  I know we now use FontLoader to load the font， and create Text in the callback function at loader, How can we create Text Dynamically ? I mean I need add Text in different time, should we load font multi-times?

**Comment by mrdoob** [comment]
No, you can just keep a reference to the loaded font and pass it to the `TextGeometry` when needed.
