### ISSUE TITLE
Compute shadow maps before beauty render, so that lights can use shadow maps to occlude light

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#7423]
This was discussed here:

> What we should do is have all shadow maps calculated first and their indices stored with the light structs that are passed to the renderer. Then as one is calculating each light contribution you check its shadow map to see if it is occluded, and that determines if you accumulate the lighting result or not. This is significantly more accurate and realistic than the darkening post-accumulation effect we currently do.

https://github.com/mrdoob/three.js/issues/7377#issuecomment-149380501

**Comment by mrdoob** [comment]
48d8c5a9112f2171faf7a6949ca2eb0ba17a88e1
