### ISSUE TITLE
Compute SSAO/SAO pass before beauty render and use result to dim "indirect diffuse"

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#7424]
SSAO/SAO can be viewed as an equivalent to AOmaps and can be used to dim the indirect diffuse.  In order for this to work, we need to compute the SSAO pass before the beauty render and then pass in the SSAO map to each material so the material shaders can access it and dim their "indirect diffuse" contributions.

This should greatly increase realism without the need to precompute aoMaps on a per mesh basis -- which is just a lot of prep work.

**Comment by bhouston** [comment]
It is likely that we could use this to also dim indirect specular but I am not sure the correct calculation because the specular is directional and the SSAO/SAO result in not directional, rather it is roughly a hemispherical occlusion ratio (which maps perfectly to indirect diffus.).

**Comment by mrdoob** [comment]
I know SSAO is mainly comparing pixel depths at render time. But how do you go from that to computing the ao uvmap?

**Comment by bhouston** [comment]
It wouldn't be an AO UVMap, rather you would figure out where the final pixel is on screen and get it directly from the SS AO.  It is basically the same quality, hemispheric visibility ratio per pixel, just that an SSAO/SAO is in screenspace, rather than UV-mapped.  It would require us to compute a normalized screen UV coordinate to get it from the SSAO map.  But it would look nearly as good as aoMaps without the effort.

**Comment by mrdoob** [comment]
Hmm, is it more like Deferred rendering?

**Comment by bhouston** [comment]
Everyone does sort of a hybrid solution.  It isn't that different than the post effects, it is just moving them before the beauty pass to increase accuracy of the final results.

**Comment by wizgrav** [comment]
you'd need a zprepass for this approach to work in a forward renderer, you need the depth to calculate ssao. So you'll have to bear the cost of submitting geometry twice but on the other hand you'll gain from minimizing overdraw in the final render + proper ssao which indeed should only be applied to ambient for accuracy. I personally don't think that ssao looks as good as prebaked ao though. it tends to be unstable under motion especially at low sample counts. On a related note, someone was working on adding depth texture support, I think this would be helpful for alot of things. How are things going with that?
