### ISSUE TITLE
Can I use THREE js ExtrudeGeometry to extrude a shape over a sharp path?

### ISSUE THREAD

**Issue by coolfeature** [mrdoob/three.js#7429]
Not  sure if this is the right place, I asked the question on StackOverflow:

http://stackoverflow.com/questions/33312263/can-i-use-three-js-extrudegeometry-to-extrude-a-shape-over-a-sharp-path

I have used CatmullRomCurve3 to extrude over a curved line. Is it possible to extrude over a sharp line to create e.g. steps?

**Comment by liammagee** [comment]
StackOverflow is the right place to ask. I've replied to your question
there.
