### ISSUE TITLE
Renderer: Strange "refresh" of lighting uniforms.

### ISSUE THREAD

**Issue by tschw** [mrdoob/three.js#7440]
Not quite figured out what's going wrong. Hints are welcome.

**Comment by tschw** [comment]
Apparently `refreshLights` is not set as needed.

**Comment by mrdoob** [comment]
Hmmm... You mean the `lights.glsl` change?

**Comment by tschw** [comment]
No. The GLSL looks awesome, BTW (except maybe the fragment-specific stuff in the vertex shader, but much tidier than before).

Just yet another messy (excuse my bluntness) updating logic in the renderer making assumptions over a huge number of code lines without wasting single one of them on comment about it. Pretty much

https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1527-L1683

**Comment by tschw** [comment]
Since the lighting uniform values are sitting on each material, by which logic can a material change *not* imply an update of the lighting uniforms?

Since the lighting uniforms depend on the camera, by which logic can a camera change (or even just a state change) not imply an update?

By which logic can the desired effect be achieved by checking global variables not remembering *which material* already got updated?

Quite clearly we're looking at premature optimization, but what is much worse is that it's not working and there is no easy way to make it work, because it's impossible to reproduce the thoughts behind the code in any way.

**Comment by tschw** [comment]
OK, got it all figured out, after all. It's hacky - but it happens to actually work. Cleaning up made have made it slower, so I went for documenting the hack and tightening the obvious pitfalls.

**Comment by mrdoob** [comment]
Indeed... The renderer is plagued with premature optimisations. Things are getting better though!

**Comment by tschw** [comment]
Not so sure it's really premature anymore. I figure it really *is* some overhead to copy the lighting values onto each material. At the point of my complaint, I hadn't gotten on top of the code yet. Although not as misguided as it appeared to me at first, there's an "evil hack" in place for optimization. I think it (at the very least) deserves to be documented :-).

**Comment by mrdoob** [comment]
What do you think about 3861491bfdeb038c78a02efd7b07c8d64701c8be, c1c62995f793db4db8bdc94aa79c7a77935760af, d3958d0624bed4fdd02952ceacbae4a3db9963e5 and 37bbc2e3274a4fcc7277089f5c83c45100209b3f? 😊

**Comment by mrdoob** [comment]
Meh... Need to refactor again. Getting there!

**Comment by mrdoob** [comment]
Hmm... That's better 😀

**Comment by tschw** [comment]
> [... comments ...]

Wow! That cleared up quite a bit.

Forget my suggestion about shadows in the other thread - I see you had the same idea already.

**Comment by tschw** [comment]
I guess this case one is more than solved.
