### ISSUE TITLE
Suggestion: Group built-in uniforms by material aspect.

### ISSUE THREAD

**Issue by tschw** [mrdoob/three.js#7442]
Looking at [this code](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1672-L1675), I've been wondering why we don't just define `.lights` - optionally renamed to something like `.SupportsLighting` on the prototypes of the materials instead of adding a bucketful of inflexibility.

Similiarly, [`.SupportsCommonShading`](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1698-L1701), [`.SupportsAdvancedTexturing`](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1722), [`.SupportsPhysicalShading`](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1726).

[`.SupportsTransparency`](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1736), [`.SupportsColor`](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1709), [`.SupportsDashedLines`](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1713), [`.SupportsTextureMapping`](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1713) and [`.SupportsSprites`](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1872-L1873).

**Comment by mrdoob** [comment]
Hmm... I wouldn't add that to materials directly. I would, instead, do something like internally converting to `ShaderMaterial`.

**Comment by tschw** [comment]
> Hmm... I wouldn't add that to materials directly. I would, instead, do something like internally converting to ShaderMaterial.

Sounds a good idea.

Then what? Have properties of this kind on ShaderMaterial? Or is there a different plan?

**Comment by tschw** [comment]
Actually these all belong into a `THREE.Shader` factorization, no?

**Comment by mrdoob** [comment]
> Actually these all belong into a `THREE.Shader` factorization, no?

Yeah. That sounds good.

I haven't been able to figure this part yet. So far, I was planning to start moving the materials code out of `WebGLRenderer` (to `WebGLMaterial` I guess).

**Comment by tschw** [comment]
We are currently missing an indirection in the data model: When we serialize 100 `ShaderMaterial`s with the same shader we get 100 copies of the code.

Then, a program *specification* (code and meta information what that code can potentially do) must be kept separate from a program *instance* (that code compiled for specific requirements which boil down to defines in the WebGL case).

Many different instances can be created from one specification. In case of e.g. MeshPhong, we get different programs depending on the number of lights, maps and other features used. 

For every built-in material *class* there would be an associated program specification object. 
For `ShaderMaterial` this relationship would apply per instance. A `ShaderMaterial` (object) knows a specification - multiple `ShaderMaterial`s can share the same shader specification.

For every material *object* there must be a program instance object. In the WebGL renderer we call it `WebGLProgram`.

These would be the participants. Next step is to puzzle out, what belongs where :-).

**Comment by tschw** [comment]
This thread is partly superseded by #8552. It discusses multiple issues that can (and should) be addressed separately.

> Group built-in uniforms by material aspect.

Will no longer be necessary.

> For every material object there must be a program instance object.

Will be taken care of in the renderer.

> When we serialize 100 ShaderMaterials with the same shader we get 100 copies of the code.

Scene graph extension should be another PR. `Technique` might be the appropriate name for the rendering recipe in an abstract form. We should look at existing content pipelines / ask @bhouston for help to get these data structures right. 

I'm closing this thread to focus on one step at a time. It's more fun to make a new mess when the old one's properly cleaned up :).
