### ISSUE TITLE
transparent & renderOrder

### ISSUE THREAD

**Issue by hotcookie** [mrdoob/three.js#7446]
// texture - transparent canvastexture with text
var xm = new THREE.MeshBasicMaterial( { map: texture, transparent: true } );
var back = new THREE.Mesh(new THREE.PlaneBufferGeometry(100,100),xm);
back.renderOrder = 1;

var xm = new THREE.MeshBasicMaterial( { color: 0xFF0000, transparent: true } );
var front = new THREE.Mesh(new THREE.PlaneBufferGeometry(100,100),xm);
front.renderOrder = 2;

scene.add(back);
scene.add(front);

...

And back object rendered over front object.
Please fix it.

**Comment by WestLangley** [comment]
`renderOrder` does not control what is "in front". Objects closest to the camera are in front.

If you need help understanding this concept, and the effects of the depth buffer, please see stackoverflow.

As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
