### ISSUE TITLE
Three.js memory leak

### ISSUE THREAD

**Issue by VasilyPolyakov** [mrdoob/three.js#7449]
I have noticed strange memory leak in three.js (r73). Steps to reproduce:

1)Open following link in Google Chrome ( 46.0.2490.80 m)

http://threejs.org/examples/#webgl_test_memory

2) Open DevTools -> Profiles - > Take Heap Snapshot. See my screenshot below:

![image](https://cloud.githubusercontent.com/assets/12031915/10725014/ec6f2e3e-7bd9-11e5-83ef-1e8277f0f2df.png)

3) Take another heap snapshot after 10 seconds. As you can see the size of heap increased.

![image](https://cloud.githubusercontent.com/assets/12031915/10725019/fe901e0c-7bd9-11e5-8413-ba41dd9b0585.png)

But if open this page locally on the computer without any server than heap size will be within the bounds of 4-6 Mb.

![image](https://cloud.githubusercontent.com/assets/12031915/10725044/22ca5896-7bda-11e5-8948-e3ab96a3dc43.png)

Why used memory size permanently increased in example and constant in case of locally page opening?

Thanks in advance!

Best regards, Vasily.

**Comment by mrdoob** [comment]
We fixed a indices memory leak recently. Do you mind checking the `dev` branch?

**Comment by VasilyPolyakov** [comment]
I checked dev branch, but unfortunately faced the same problem.
![image](https://cloud.githubusercontent.com/assets/12031915/10731784/0b9c4d7c-7c08-11e5-9e8c-07f254a6cda6.png)

I have noticed that size of  `system/JsArrayBufferData` in Chrome profiler constantly increase. 
May be it will give you the clue.

![2015-10-26 17 36 32](https://cloud.githubusercontent.com/assets/12031915/10731974/f1fff39a-7c08-11e5-9347-27a0898c4bf4.png)
![2015-10-26 17 36 42](https://cloud.githubusercontent.com/assets/12031915/10731980/f6fefc9c-7c08-11e5-9580-f2012b70b3c8.png)

**Comment by LadyMery** [comment]
Dear Mrdoob,

The interesting fact of this issue is that the experiment (webgl_test_memory) being run locally i.e. through the file://...  has the following heap snapshots and objects are correctly destroyed:

![test memory threejs local](https://cloud.githubusercontent.com/assets/15358602/10784117/42487f24-7d6d-11e5-887d-f7f929396ea5.png)

But under the server (localhost:8080 as Vasily's screenshots demonstrate) I have the same behavior as Vasily described above.

Could you please clarify this situation? Thank you in advance!

**Comment by mrdoob** [comment]
You guys know as much as I do...

**Comment by tschw** [comment]
Do we put stuff on the DOM somehow? Maybe related: https://github.com/mrdoob/three.js/issues/7391#issuecomment-150591378

**Comment by leitzler** [comment]
I ran this through the profiler in Chrome and found that Geometries didn't remove properties.

There is a PR, #7504, that I've tested using Chrome where I added cleanup in onGeometryDispose. Note that I haven't looked at the memory handling in Three.js enough to be sure where you want the clean-up. It worked when I tested it in this specific example, and I hope it will at least lead you in the right direction.

**Comment by asyukri** [comment]
I have experienced memory leak in three.js (r73 & r74dev). Used sprite for text label. Every time need to update the label text, drop existing and create a new one. Maybe I'm missing something or there's better way to do this. Or maybe I didn't clear memory properly. Testing code as below,

```javascript
<!doctype html>
<html lang="en">
<head>
    <title>Text Update</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
</head>
<body>


<script src="js/three.min.js"></script>
<script src="js/Detector.js"></script>
<script src="js/OrbitControls.js"></script>
<script src="js/THREEx.KeyboardState.js"></script>
<script src="js/THREEx.FullScreen.js"></script>
<script src="js/THREEx.WindowResize.js"></script>

<div id="ThreeJS" style="position: absolute; left:0px; top:0px"></div>
<script>

var container, scene, camera, renderer, controls;
var mytimer;

init();
animate();
    
function init() {
	scene = new THREE.Scene();
	var SCREEN_WIDTH = window.innerWidth;
    var SCREEN_HEIGHT = window.innerHeight;
	var VIEW_ANGLE = 45;
    var ASPECT = SCREEN_WIDTH / SCREEN_HEIGHT;
    var NEAR = 0.1;
    var FAR = 20000;
	camera = new THREE.PerspectiveCamera( VIEW_ANGLE, ASPECT, NEAR, FAR);
	scene.add(camera);
	camera.position.set(0, 150, 400);
	camera.lookAt(scene.position);	
    
	if (Detector.webgl)
		renderer = new THREE.WebGLRenderer({antialias: true});
	else
		renderer = new THREE.CanvasRenderer(); 
        
	renderer.setSize(SCREEN_WIDTH, SCREEN_HEIGHT);
	container = document.getElementById('ThreeJS');
	container.appendChild(renderer.domElement);
	THREEx.WindowResize(renderer, camera);
	THREEx.FullScreen.bindKey({charCode : 'm'.charCodeAt(0)});
	controls = new THREE.OrbitControls(camera, renderer.domElement);
    
    drawObjects();
    mytimer = setInterval(timerFunc, 200);
}

function timerFunc() {
    var id = 0;
    var value = getRandomArbitrary(1000, 9999);
    updateText(id, value);
}
        
function getRandomArbitrary(min, max) {
    return Math.round(Math.random() * (max - min) + min);
}

function updateText(id, text) {
    var name = 'text-' + id;
    var obj = scene.getObjectByName(name);
    if (obj == undefined) {
        console.log('obj undefined!');
        return;
    }

    var x = obj.position.x;
    var y = obj.position.y;
    var z = obj.position.z;            
    
    scene.remove(obj);

    obj.material.map.dispose();
    obj.geometry.dispose();
    obj.material.dispose();
    
    obj.indices = [];
	obj.vertices = [];
	obj.uvs = [];
    
    obj = null;
    
    var spritey = makeTextSprite("" + text);
    spritey.name = name;
    spritey.position.x = x;
    spritey.position.y = y;
    spritey.position.z = z;        
    scene.add(spritey);
}
        
function drawObjects() {
    var spritey = makeTextSprite("9999");
    spritey.name = 'text-' + 0;
    spritey.position.set(50, 50, 50);
    scene.add(spritey);
}

function makeTextSprite(message) {
	var fontface = "Georgia";
	var fontsize = 64;
	var borderThickness = 4;
	var fontColor = {r:255, g:253, b:0, a:1.0};
	var borderColor = {r:255, g:253, b:0, a:1.0};
	var backgroundColor = { r:255, g:255, b:255, a:0.0 };
    var canvas = document.createElement('canvas');
	var context = canvas.getContext('2d');
	context.font = "Bold " + fontsize + "px " + fontface;
    
	// get size data (height depends only on font size)
	var metrics = context.measureText( message );
	var textWidth = metrics.width;
	
	// background color
	context.fillStyle   = "rgba(" + backgroundColor.r + "," + backgroundColor.g + ","
								  + backgroundColor.b + "," + backgroundColor.a + ")";
	// border color
	context.strokeStyle = "rgba(" + borderColor.r + "," + borderColor.g + ","
								  + borderColor.b + "," + borderColor.a + ")";

    context.fillStyle = "rgba(" + fontColor.r + "," + fontColor.g + ","
								+ fontColor.b + "," + fontColor.a + ")";    

	context.fillText( message, borderThickness, fontsize + borderThickness);
	
	// canvas contents will be used for a texture
	var texture = new THREE.Texture(canvas) 
	texture.needsUpdate = true;

	var spriteMaterial = new THREE.SpriteMaterial({ map: texture, color: 0xffffff });        
	var sprite = new THREE.Sprite(spriteMaterial);
	sprite.scale.set(100, 50, 1.0);
	return sprite;	
}

function animate() {
    requestAnimationFrame(animate);
	renderer.render(scene, camera);
}

</script>
</body>
</html>
```

**Comment by mrdoob** [comment]
@asyukri can you create a jsfiddle?

**Comment by asyukri** [comment]
Thanks for fast reply, @mrdoob 
The jsfiddle link is [http://jsfiddle.net/7j6n5gty/](http://jsfiddle.net/7j6n5gty/)

Memory drastically increases, maybe I did this part wrongly
```javascript
scene.remove(obj);
obj.material.map.dispose();
obj.geometry.dispose();
obj.material.dispose();

obj.indices = [];
obj.vertices = [];
obj.uvs = [];

obj = null;
```

**Comment by mrdoob** [comment]
>     obj.indices = [];
    obj.vertices = [];
    obj.uvs = [];

What's that for?

**Comment by asyukri** [comment]
Someone told me to do this to clear the memory leak. Not sure if it's correct way or not :)

**Comment by leitzler** [comment]
Tried out your jsfiddle in Chrome 46.0.2490.86 m (Win7) and can't say that there aren't any big leaks after a minute, how did you see that it do? (I'll keep it running for a few minutes).

**Comment by asyukri** [comment]
Base on Task Manager of Chrome 46.0.2490.86 m (Win 8 & 10), memory column. After 1 hour, the page will dead...

**Comment by leitzler** [comment]
Oh, the page crashed after approx 9 minutes runtime, but not due to insufficient memory. I don't have time to look at it right now but will give it some more time if no one else solves it :)

**Comment by leitzler** [comment]
@asyukri I think that the mem usage/crash is because the console fills upp with warnings:
"THREE.WebGLRenderer: image is not power of two (300x150). Resized to 256x128".

**Comment by asyukri** [comment]
Strange, keep running for one night and page still alive, memory OK. Original source code produce big memory leak. The leak maybe comes from other part of my code. Sorry for your time. Thanks for the help! :)

**Comment by meirela** [comment]
Hey, have someone found a way to solve the JS/ArrayBufferData memory problem?
I am having really difficult time dealing with it...

Also, as other people suggested - the memory test in the official Examples page is showing the same results - memory usage increases as a Sawtooth wave, from a maximum value of around 50K when it starts, to ~200K in less then a minute.
It keeps on growing, even when GC is invoked using Google Dev-tool

**Comment by mrdoob** [comment]
@meirela Can you share a screenshot?

**Comment by meirela** [comment]
@mrdoob Which one did you want? the test memory or mine?

**Comment by meirela** [comment]
@mrdoob First thing - sorry.
I didn't get that __dispose() __ method up until 5 minutes ago. It is shown in a very clear way in the [http://threejs.org/examples/#webgl_test_memory](url) example.

When following this example, I could easily see that the dispose() method deals perfectly with the GPU memory, while marking the mesh as __undefined__ (when making sure there are no additional references to the mesh)  is good enough for the GC to do its job.

In this chance, I'd like to thank you, @mrdoob , for a great open source library, along with your dedication in dealing with issues, which made my life much easier. I just love it!

**Comment by marsalRBX** [comment]
I did some test with webgl_test_memory and i can see that WebGLTexture objects are constantly creating but not removing. THREE.Texture,THREE.Material and THREE.Geometry work property and ins't incrementing but WebGLTexture yes, anybody know's how to solve the problem? Thanks

![captura de pantalla 2016-06-15 a las 13 35 55](https://cloud.githubusercontent.com/assets/3823272/16078261/2b950f58-32fe-11e6-929a-8d37f92a7b51.png)
![captura de pantalla 2016-06-15 a las 13 35 49](https://cloud.githubusercontent.com/assets/3823272/16078266/30e22afe-32fe-11e6-9d38-b7a1deb7a2ca.png)
![captura de pantalla 2016-06-15 a las 13 35 40](https://cloud.githubusercontent.com/assets/3823272/16078268/353e77ce-32fe-11e6-85c5-c5bcfd4a1d85.png)

**Comment by meirela** [comment]
@marsalRBX Did you try using the '__dispose()__' method?
I never tried it on 'THREE.Texture', but it did a great job on 'THREE.Geometry' and 'THREE.Material'.

btw - I've also used it on 'THREE.Mesh', just in case...

**Comment by marsalRBX** [comment]
I used the example of three.js package i didn't touch anything

**Comment by meirela** [comment]
Try adding 'THREE.Texture.dispose()' to whenever you are trying to completely remove a texture off the scene, that should do the trick.

Please notice that THREE.JS is a wonderful open-source library, which keeps on updating on a daily basis, but its documentation (along with its examples) are not updating so often... So try and "fix" the examples, most of them still are good practice but a few lines of code.

**Comment by zedee** [comment]
I'd like to point that this behavior is not happening in a Linux box.

**WebGLTexture** values keep stable along time, instead of the constant growing @marsalRBX shows in his heap captures.

My heap captures:
![Heap Capture #1](http://i.imgur.com/LnvYGqV.png)
![Heap Capture #2](http://i.imgur.com/0UMeHz5.png)

Doesn't seem this is an issue from three.js itself but something deeper between WebGL handling in different operative systems.

@marsalRBX is on a MacOS X, and I'm on an Ubuntu 16.04 using the radeon driver.

**Comment by marsalRBX** [comment]
It seems that is a problem with my computer. I tested the example in other 4 machines and works fine. Thanks for the attention :D
