### ISSUE TITLE
Canvas Background color always Black in chrome (your solution doesn't work).

### ISSUE THREAD

**Issue by Hazarapet** [mrdoob/three.js#7450]
Hi guys.I'm using Three.js and can't solve the problem.The canvas background is Always Black.Whatever I do, change alpha, (even in the CanvasRender file I made some changes), but background is black.What can you say?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
