### ISSUE TITLE
Compressed textures (Eg DDS/crunch) not supported by ObjectLoader

### ISSUE THREAD

**Issue by erno** [mrdoob/three.js#7452]
There is also no obvious place make this happen in your own code, short of
modifying ObjectLoader.

Currently the code uses ImageLoader which doesn't handle compressed textures.
A possible approach could be a new autodetecting image loader that could use
ImageLoader or DDSLoader (or PVR or ...) depending on type of image data encountered,
and a corresponding change in parseTextures
where it calls into the new loader for the Texture or CompressedTexture instance.

**Comment by antont** [comment]
any ideas here? am reading ObjectLoader and it's use of ImageLoader to see how it goes now and perhaps find some way to add support for compressed ones

**Comment by antont** [comment]
tested by hacking ObjectLoader in a separate test copy ('ObjectLoaderDDS') back then.

happened to see this niceness in obj & mtl loading example now:

``
THREE.Loader.Handlers.add( /\.dds$/i, new THREE.DDSLoader() );
``

https://github.com/mrdoob/three.js/blob/dev/examples/webgl_loader_obj_mtl.html#L88

**Comment by Mugen87** [comment]
Merged into #17974.
