### ISSUE TITLE
Serialization / Editor / App Player: What's wrong with normal mapping?

### ISSUE THREAD

**Issue by tschw** [mrdoob/three.js#7454]
After importing a model with a normal map (`MeshPhongMaterial`), hitting Play yields a black screen.

What's [this strange comment](https://github.com/mrdoob/three.js/blob/dev/src/materials/Material.js#L159) all about? Just changes in the data model?

`.normalScale` apparently is a 2D vector: https://github.com/mrdoob/three.js/blob/dev/src/loaders/MaterialLoader.js#L100

**Comment by mrdoob** [comment]
Fixed?

**Comment by tschw** [comment]
Fixed.

**Comment by tschw** [comment]
Fixed for `MeshPhongMaterial` - not fixed for `ShaderMaterial` with a normal map - see #7461.
