### ISSUE TITLE
stereoEffect and CSS3DStereoEffect

### ISSUE THREAD

**Issue by SenninSensei** [mrdoob/three.js#7456]
hello i'm making a VR application, so far i'm done the desktop version, for mobiles devices i plan to use google cardboard with a stereoEffect, but i'm using a cssRenderer and a webglRenderer together. my question is how i use stereoEffect and CSS3DStereoEffect together? 

oikoscrm.com/threejs/demo/

**Comment by mrdoob** [comment]
You should be able to compose two divs with HTML and CSS.
