### ISSUE TITLE
Light attenuation?

### ISSUE THREAD

**Issue by tschw** [mrdoob/three.js#7463]
Maybe I'm just not getting it, but any setting with `light.distance !== 0 && light.decay !== 0` seems to result in no light at all. Also with r73.

**Comment by mrdoob** [comment]
`PointLight` with distance set to `100.0`, decay to `1.0` and intensity set to `5.0`. Seems to work fine?

![screen shot 2015-10-27 at 10 11 22](https://cloud.githubusercontent.com/assets/97088/10760484/27c00f1c-7c93-11e5-8a18-1dba7f7f83d5.png)

**Comment by tschw** [comment]
> Maybe I'm just not getting it

OK. Sorry for the noise.
