### ISSUE TITLE
Wireframe property for Materials within MultiMaterial

### ISSUE THREAD

**Issue by real-jamesbrown** [mrdoob/three.js#7467]
Hi,
I want to use the wireframe property for a Material within a MultiMaterial to switch between the Mesh and Wireframe mode. With an old version of Three.js this worked fine (actually I dont know which version it was, I used the three.min.js file only, but I downloaded it arround March 2015). But I recently updated to a more recent version (0.72) and now not all vertices are shown anymore and some vertices are connected, which does not build any face.
Here is a screenshot of the Mesh:
![colored_mesh](https://cloud.githubusercontent.com/assets/1218265/10753305/7035f02a-7c90-11e5-8b70-08484fb24fd4.png)

Here is a screenshot of the "old" working version:
![old_revision](https://cloud.githubusercontent.com/assets/1218265/10753307/76a3829c-7c90-11e5-99c1-0921f7719e4f.png)

At least a screenshot of the current version, which does not work anymore:
![current_revision](https://cloud.githubusercontent.com/assets/1218265/10753306/7685aa74-7c90-11e5-966a-4dafd5bd53b1.png)

As you can see, the upper part of the Wireframe is missing, as well as a small rectangular part on the right side.

I used the following code to show the wireframe for all Materials for the MuliMaterial. The `object` Object is simply the Object which was added to the scene.

``` javascript
var mtls = object.children[0].material.materials;
for (var i = 0; i < mtls.length; i++) {
  var mtl = mtls[i];
  mtl.wireframe = true;
  mtl.vertexColors =  THREE.FaceColors;
  mtl.wireframeLinewidth = 1;
  mtl.map_orig = mtl.map;
  mtl.normalMap = null;
  mtl.bumpMap = null;
  mtl.map = null;
  mtl.needsUpdate = true;
  mtl.color = new THREE.Color (0x123456); 
  console.log (mtl); 
}
```

Note: I really want to use the simple wireframe property and no Wireframe-Helper workarround. Hope anyone has an Idea. 

Thanks in advance!

**Comment by xXCrystalXx** [comment]
Hey real-jamesbrown,
it is a new Version of THREE.js available (Version r73).
But I have tested your problem in a own simple example code and it does not work.

My full example code:
```javascript

<!DOCTYPE html>
<html lang="en">
<head>
	<title>three.js webgl - geometry - cube</title>
	<meta charset="utf-8">
	<style>
		body {
			margin: 0px;
			background-color: #000000;
			overflow: hidden;
		}
	</style>
</head>
<body>

<!--<script src="three.min_r71.js"></script>-->
<script src="three.min_r73.js"></script>
<!--<script src="OrbitControls.js"></script>-->

<script>

	var camera, controls, scene, renderer;
	var mesh;

	init();
	animate();

	function init() {

		camera = new THREE.PerspectiveCamera( 70, window.innerWidth / window.innerHeight, 1, 1000 );
		camera.position.z = 300;

		scene = new THREE.Scene();

		var materials = [
			new THREE.MeshBasicMaterial( {color:0xffe4b5} ),
			new THREE.MeshBasicMaterial( {color:0xffe4b5} ),
			new THREE.MeshBasicMaterial( {color:0xffe4b5} ),
			new THREE.MeshBasicMaterial( {color:0xffe4b5} ),
			new THREE.MeshBasicMaterial( {color:0xffe4b5} ),
			new THREE.MeshBasicMaterial( {color:0xffe4b5} )
		];

		var geometry = new THREE.BoxGeometry( 100, 100, 100, 1, 1, 1 );
		mesh = new THREE.Mesh( geometry, new THREE.MeshFaceMaterial(materials) );
		scene.add(mesh);

		var mtls = mesh.material.materials;
		for (var i = 0; i < mtls.length; i++) {
			var mtl = mtls[i];
			mtl.wireframe = true;
			mtl.vertexColors =  THREE.FaceColors;
			mtl.wireframeLinewidth = 1;
			mtl.map_orig = mtl.map;
			mtl.normalMap = null;
			mtl.bumpMap = null;
			mtl.map = null;
			mtl.needsUpdate = true;
			mtl.color = new THREE.Color (0x123456);
			console.log (mtl);
		}



		renderer = new THREE.WebGLRenderer();
		renderer.setPixelRatio( window.devicePixelRatio );
		renderer.setSize( window.innerWidth, window.innerHeight );
		document.body.appendChild( renderer.domElement );

		window.addEventListener( 'resize', onWindowResize, false );

	}

	function onWindowResize() {

		camera.aspect = window.innerWidth / window.innerHeight;
		camera.updateProjectionMatrix();

		renderer.setSize( window.innerWidth, window.innerHeight );

	}

	function animate() {

		requestAnimationFrame( animate );

		//controls.update(); // required if controls.enableDamping = true, or if controls.autoRotate = true

		mesh.rotation.x += 0.005;
		mesh.rotation.y += 0.01;

		renderer.render( scene, camera );

	}

</script>

</body>
</html>

```

In my opinion it is a Bug by THREE and we must wait for a fix.
@mrdoob can you look at please for this problem, thanks in advance.

**Comment by mrdoob** [comment]
This one is tricky because of the way wireframe works now. I almost even removed `wireframe` in r72...

**Comment by real-jamesbrown** [comment]
Hi,
thanks @xXCrystalXx that you verified my issue.
@mrdoob what do you mean by "I almost even removed `wireframe` in r72..."? Does it either mean, that you do not want to support wireframe anymore or you had so much trouble with it, that you want to remove the property temporarily?

**Comment by mrdoob** [comment]
It's quite a lot is trouble. I didn't know how to make it work for a while. And, as you found out, it doesn't work in all the cases yet.

**Comment by WestLangley** [comment]
This issue is specific to a very old three.js revision, so closing.
