### ISSUE TITLE
Suggestion: Using require.js for loading resources and resolving dependencies 

### ISSUE THREAD

**Issue by wavesoft** [mrdoob/three.js#7471]
For a recent project of mine, I needed to load arbitrary resources with their own dependencies in a clean and structured way. Since I was already using require.js in my project, the three.js pipeline for loading resources was a bit messy for my case.

Therefore I came up with a solution that benefits from the require.js dependency resolution and caching mechanism. I wrote custom require.js plugins for every resource type, effectively simplifying the loading pipeline to something like this:

``` javascript
define(["mesh!some.bundle/gameobject.obj"], function(gameobject) {
   ...
   scene.add( gameobject );
   ...
});
```

(dependant materials, textures, shaders and geometries are loaded automatically)

This mechanism makes it also simple to create reusable resource bundles that can be used in various projects.

If you are interested, you can find the project here: https://github.com/wavesoft/three-bundles (An example using this library will be available soon)

In the future I am planning to include an optimisation phase in these plug-ins in order to allow the require.js optimiser to compile the resources into an even more compact format.

**Comment by Mugen87** [comment]
Showcases should be posted right here now: https://discourse.threejs.org/

There is a category `Showcase` you can use for these kind of topics.
