### ISSUE TITLE
Mesh Phong Material documentation needs updating with displacement properties

### ISSUE THREAD

**Issue by ghost** [mrdoob/three.js#7478]
As per issue [#7107](https://github.com/mrdoob/three.js/pull/7107) and [#7094](https://github.com/mrdoob/three.js/issues/7094), as of r73, the MeshPhongMaterial has displacementMap (default: null), displacementScale (default: 1), and displacementBias (default: 0), properties which need to be added to the [Mesh Phong Material documentation](http://threejs.org/docs/#Reference/Materials/MeshPhongMaterial).

I am happy to update these myself if I can be pointed to some reasonable definitions for these properties?

**Comment by WestLangley** [comment]
The source is your best bet: https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderChunk/displacementmap_vertex.glsl.

Thanks for offering to help.

**Comment by mrdoob** [comment]
Do you want to update the file directly?
https://github.com/mrdoob/three.js/blob/dev/docs/api/materials/MeshPhongMaterial.html

**Comment by pathogen-** [comment]
Thanks for that! I will get onto it and send a PR when done.

**Comment by looeee** [comment]
It's been added now :)
