### ISSUE TITLE
Concusion in use of _this and this in TrackballControls.js

### ISSUE THREAD

**Issue by jellevlassenbroeck** [mrdoob/three.js#7479]
In the trackball control files, var_this = this is set on the first line to make sure the event handlers can access the correct variables. 

However, in functions such as "function rotateCamera()", both 'this' and '_this' are used. 

It seems to me that one of both can be used, but to prevent confusion a clear choice would be preferred. In that case, I assume we could use 'this' since it makes it clear that the use '_this' is not required here. I tested the replacement and everything runs fine.

**Comment by tschw** [comment]
> in functions such as "function rotateCamera()", both 'this' and '_this' are used. 
> [...]
> I assume we could use 'this' since it makes it clear that the use '_this' is not required here. I tested the replacement and everything runs fine.

So you have a cleaner version on your disk. Assuming you're actually sure that your cleanup is legal (`this` and `_this` refer to the same object), you could avoid the bureaucracy of creating an Issue and send a Pull Request right away.

From my experience, submissions that simplify stuff are generally welcome around here.

**Comment by jellevlassenbroeck** [comment]
Thanks for the comment. I wasn't too sure about the correctness since I am not a Javascript developer, but the code seems to run properly. I will close the issue and send a Pull request

**Comment by tschw** [comment]
> I wasn't too sure about the correctness

Stating this in the PR description tells the reviewer to take a closer look Still becomes easier when the code is just one click away :-)
