### ISSUE TITLE
How to access r73 WebGL properties?

### ISSUE THREAD

**Issue by mattdesl** [mrdoob/three.js#7483]
I have various applications that need low-level handling of ThreeJS textures, render targets, etc. For example, blitting images into a region of a texture with `gl.texSubImage2D`, using `__webglTexture`.

How can I access these in the latest version of ThreeJS? All the properties are now managed by `THREE.WebGLProperties`, which is private in the renderer, and hides the property names under UUIDs.

**Comment by mrdoob** [comment]
So you mainly want to access `__webglTexture`? Maybe we could expose `properties`.

**Comment by mattdesl** [comment]
Yeah, `__webglTexture`, `__webglInit`, `__webglFramebuffer`, and similar.

Here is an example use case which only works on previous versions of ThreeJS:
https://github.com/Jam3/three-png-stream/blob/56cdbdbd82cd24f2f292c0a8b2e38cc476d48b0f/index.js#L22

**Comment by mrdoob** [comment]
That whole `__webgl*` thing was hacky though.

Ideally we would do something like:

```javascript
var framebuffer = renderer.properties.get( target );
```

**Comment by mrdoob** [comment]
Ok, just added it. Do you mind giving it a go?

**Comment by mattdesl** [comment]
Cool! I'm now using this: 

```js
    var props = renderer.properties.get(renderTarget);
    if (!props) return;
    var glFramebuffer = props.__webglFramebuffer;
```

Works well. :smile: Do you think the property should be named properly to signify that it is not "private"? Or will you just keep it as `__webglFramebuffer` for the foreseeable future?

**Comment by mrdoob** [comment]
Nice! I think `__webgl` will be gone in the future yeah...

**Comment by gre** [comment]
**a bit around this same subject, I was looking for a way to be able to draw a scene on an arbitrary user's framebuffer, not necessarily one handled by Three.js.**

My use-case is: I have my custom effect pipeline lib, and at some point I want it to be interoperable with any other lib, like Three.js, and if it would expose a draw() function that would render Three.js into the current framebuffer I have bound (with bindFramebuffer). (The same way WebGL is interoperable with <canvas>, <video>, .. it would be great if our libs are interoperable each other, so you can compose effects.)

I have no idea if it's easy and if Three.js would have some other side effects that my lib wouldn't like. (e.g. if it do stateful things like bindBuffer, I don't know how I should unset these)

Cheers
