### ISSUE TITLE
SkinnedMesh model exported with Blender => Huge deformations issue

### ISSUE THREAD

**Issue by BTVincent** [mrdoob/three.js#7495]
Hello everybody :) 
I was creating a character model for a demo and I have rigged it and animated it with Blender.
The model :

![dabb911c5964be77a62333a11c35ba5c](https://cloud.githubusercontent.com/assets/1362505/10864690/be3e0348-7ff6-11e5-997b-db156735bffe.gif)

When I tried to export it with the r73 blender exporter I had a huge surprise :

![7c52652303b164d72b95d68048cf156b](https://cloud.githubusercontent.com/assets/1362505/10864688/96c398fa-7ff6-11e5-8850-a892090d14fe.gif)

First the armature are very buggy and even the SkeletonHelper says everything goes wrong :(

Then the material colors arent the same as in Blender and I have got these messages in the log : 

![03f3bccf286c099ec2b320cb9a97bc38](https://cloud.githubusercontent.com/assets/1362505/10864695/fcb9c3fa-7ff6-11e5-9529-c901456aa1f4.png)

I don't know what to do I tried a lot of things and it doesnt work please help it has been a week that I am stuck with this issue. :(

Thanks.

**Comment by nn4e** [comment]
Try to set default pose before exporting.

**Comment by BTVincent** [comment]
When I export I set the armature in REST position and my exportation settings are : 
![f00e70a5ef8107f42f76951d6571ec0b](https://cloud.githubusercontent.com/assets/1362505/10864852/ffab40f8-7ffa-11e5-88c3-07fe94b6b9b7.png)

**Comment by nn4e** [comment]
Maybe need to increase bone Influence option.

**Comment by yomotsu** [comment]
I just posted a blog about the new skinned mesh animation, see [the post
](http://yomotsu.net/blog/2014/02/19/convert-mmd-for-threejs.html). I hope it would be helpful...

Also colorAmbient problem has been fixed at #7374, you can use the expoter of r74 dev version instead, or just remove colorAmbient properties in the JSON file

**Comment by BTVincent** [comment]
Thank you so much @yomotsu !
The Ctrl + A then check Rotation + Location + Scale Technique solved a big problem.
I had also another problem which I solved by reacalculating bone normals with Ctrl + N in Edit Mode
Where can I find the r74 exporter ?

**Comment by yomotsu** [comment]
see these for a workaround. It will be fixed r74 anyway
https://github.com/mrdoob/three.js/issues/7368
https://github.com/mrdoob/three.js/issues/7486

Also you can find r74 dev version here https://github.com/mrdoob/three.js/branches

**Comment by mrdoob** [comment]
Yomotsu to the rescue! Thanks! 😊
