### ISSUE TITLE
Sprite attached to model alignment

### ISSUE THREAD

**Issue by BTVincent** [mrdoob/three.js#7499]
Hello everyone :)

I am currently making a game and I want players to have their names centered on top of their character but it displays like this : 

![0de3a9885b8e0f034b766c3ebf4ccf00](https://cloud.githubusercontent.com/assets/1362505/10868601/aeea56fc-8092-11e5-916c-44e171aae613.gif)

I would like the name to be centered compared to the character :(

I know that before there had some SpriteAlignment techniques but now they are deprecated.

I have tried the following tutorial : http://threejs.org/examples/webgl_sprites.html
But it is not what I expect as the result is only good from a certain point of view : 

![fcf3133a5f03bf3dc87ae0fd35ac10de](https://cloud.githubusercontent.com/assets/1362505/10868616/1a283fec-8093-11e5-91e2-0839163cc91b.gif)

Thanks in advance for any help you are able to provide.
Have a good day :)

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
