### ISSUE TITLE
Geometry editor (similar to webgl_interactive_voxelpainter)

### ISSUE THREAD

**Issue by VinnyVicious** [mrdoob/three.js#7501]
I'm trying to create a very small geometry drawing application, similar to the voxelpainter example included in three.js. Does anyone know any examples or articles that cover this topic? I have no idea where to start when it comes to using the mouse to draw geometry primitives. 

Here's an example of what i'm looking for: https://www.youtube.com/watch?v=F-1pM55k4WM

Obviously, with 1/10 of the features. I just want to know how to draw the boxes. :D

**Comment by tschw** [comment]
This forum is for bugs reports, feature requests and contribution, so the right place for general help is [stackoverflow.com](http://stackoverflow.com/questions/tagged/three.js), unless in case you're planning to make it a Three.js example component. 

> Here's an example of what i'm looking for: https://www.youtube.com/watch?v=F-1pM55k4WM

Wow! This editor looks very nice. I guess it would be worthy - even with a reduced feature set.

> I have no idea where to start when it comes to using the mouse to draw geometry primitives.

Mouse / 3D interaction means shooting a ray (from your eye) through the pixel and see what gets hit - `THREE.Raycaster` lets you do this and there are several examples that show its use.

The modeling operator shown a lot in the video is "Extrude" and there is some code that deals with it in the extras package, although it may not be designed for editing.

**Comment by VinnyVicious** [comment]
Thanks for the help! :+1:

ps.: Do you know any example of vertex manipulation using a raycast?

**Comment by tschw** [comment]
> Do you know any example of vertex manipulation using a raycast?

For drag operations in space you may want to take a look at `THREE.TransformControls` (this one produces an object transform, in other words a matrix that you could apply to one or more vertices).

Vertex manipulation itself is very simple: Just change the arrays or their contents in a `BufferGeometry` and set `.needsUpdate = true`.
