### ISSUE TITLE
Deficient documentation on TextGeometry usage

### ISSUE THREAD

**Issue by justshiv** [mrdoob/three.js#7503]
It was not clear to me as a user how to use  [TextGeometry](http://threejs.org/docs/#Reference/Extras.Geometries/TextGeometry). After some research I found that this was due to it longer being part of the core three.js library. I suggest 2 edits to prevent other users from facing this issue too: 

1. Make it very clear that TextGeometry is no longer part of the core library at the top of the documentation page. 

2. The documentation page doesn't clarify how to use TextGeometry now that it is not core. To make use of TextGeometry, the order of the file imports is important.This code block below is the correct order of imports. If you import the font js file first it does not work. I suggest augmenting the documentation to show a usage example like this.
    ```javascript
    <script src="js/geometries/TextGeometry.js"></script>
    <script src="js/utils/FontUtils.js"></script>
    <script src="fonts/helvetiker_bold.typeface.js"></script>
    ```

**Comment by mrdoob** [comment]
I've added a error message in the library itself so people has basic guidance.

**Comment by justshiv** [comment]
Awesome. That's really cool. I think that will help a lot. Thanks so much for being so responsive. I am going make a pull-request to clarify this in the documentation once I have some time on my hands.

**Comment by yangpu** [comment]
Threejs bower repository doesn't include example/js/utils folder, and it's helpful to sync all related components to bower/npm.

**Comment by mrdoob** [comment]
`TextGeometry` has been added back to core in `r74` (currently in `dev`).
