### ISSUE TITLE
Access the camera in an editor generator page

### ISSUE THREAD

**Issue by CarbonMan** [mrdoob/three.js#7510]
I wish to detect when an object has been clicked. I am generating a page from the three.js editor. It is a brilliant environment.

Following the advice from this post (https://mandemeskel.wordpress.com/2013/08/19/mouse-events-raycasting-with-three-js/)  I ended up with the following code. I have placed a comment where I am having a problem. 

    function mousedown( event ) {
        var scene = this.parent;
        var projector = new THREE.Projector();
        var mouse_vector = new THREE.Vector3(),
        mouse = { x: 0, y: 0, z: 1 },
        ray = new THREE.Raycaster( new THREE.Vector3(0,0,0), new THREE.Vector3(0,0,0) ),
        intersects = []; 
        mouse.x = ( event.clientX / window.innerWidth ) * 2 - 1;
        mouse.y = - ( event.clientY / window.innerHeight ) * 2 + 1;
        mouse_vector.set( mouse.x, mouse.y, mouse.z );
        
        // How do I get the camera?
        projector.unprojectVector( mouse_vector, camera );
        
        var direction = mouse_vector.sub( camera.position ).normalize();
        
        ray.set( camera.position, direction );
        
        var object =  scene.getObjectByProperty( 'uuid', this.uuid, true );
        
        intersects = ray.intersectObject( object );
        
        if( intersects.length ) {
                alert( "hit" );
                event.preventDefault();  
        }
     }

I have temporarily fixed the problem by modifying app.js in the published page. By moving the camera variable to be global I got around it, but it is obviously a fudge. Is there any way to access the camera generated by the editor without modifying app.js?

    var camera;
    var APP = {
	Player: function () {
....

**Comment by mrdoob** [comment]
Glad you like the environment! I'll add a `getCamera()` to App.js 😊

**Comment by mrdoob** [comment]
Just so you know, I've removed `player.getCamera()` as I'm now passing `camera` to the script directly.
