### ISSUE TITLE
documentation on Geometry.skinIndices not clear

### ISSUE THREAD

**Issue by nylki** [mrdoob/three.js#7516]
The documents on *Skeleton*, *skinnedMesh* and related structures are not really clear to me.

I am only starting to experiment with skinned meshes, but was confused when reading the [doc entry to `Geometry.skinIndices`](http://threejs.org/docs/#Reference/Core/Geometry.skinIndices):
```.js
geometry.skinIndices[15] = new THREE.Vector4(   0,   5,   9, 0 );
geometry.skinWeights[15] = new THREE.Vector4( 0.2, 0.5, 0.3, 0 );

// corresponds with the following vertex
geometry.vertices[15];

// these bones will be used like so:
skeleton.bones[0]; // weight of 0.2
skeleton.bones[5]; // weight of 0.5
skeleton.bones[9]; // weight of 0.3
skeleton.bones[0]; // weight of 0
```

Although I don't quite get how the `skinIndices` are used, those two lines seem a bit strange to me. Why How can the weight differ on the same bone, without doing modifications?

```.js
/* this one: */skeleton.bones[0]; // weight of 0.2 
//skeleton.bones[5]; commented out
//skeleton.bones[9]; commented out
/* and this one: */skeleton.bones[0]; // weight of 0
```

Was the document supposed to say something like the following? : 
```.js
geometry.skinIndices[15] = new THREE.Vector4(   0,   5,   9, 10 /* !!!replaced 0 with 10 here!!! */ );
geometry.skinWeights[15] = new THREE.Vector4( 0.2, 0.5, 0.3, 0 );

// and
// these bones will be used like so:
skeleton.bones[0]; // weight of 0.2
skeleton.bones[5]; // weight of 0.5
skeleton.bones[9]; // weight of 0.3
skeleton.bones[10]; // !!!replaced 0 with 10 here!!!

```

Or am I missing something?

Even with the changes made above, I don't understand the relation between the inidividial bones (0, 5, 9) to the weights. Why is index `15` used in the beginning? Is that the supposed to be the last index of the geometry?
What happens when I then do the same thing with `geometry.skinIndices[14]` etc., with a different `Vector4`. Will the same bones weights be different then?

**Comment by TatumCreative** [comment]
Yes, I messed up the 4th line there. I'll do another read through sometime next week and see if I can clear up some of your confusion on it. I remember it being difficult to explain clearly without writing a novel. The relationship between the various parts are a little abstract.

**Comment by coolfeature** [comment]
+1

**Comment by nylki** [comment]
@TatumCreative have you found some time to take a look at it? :)
No pressure though!

**Comment by TatumCreative** [comment]
Ok, check out #7719 and let me know if that makes more sense. It's pretty tough to explain since a lot of stuff is happening in lots of different places.

**Comment by nylki** [comment]
Much better! :)
Thank you @TatumCreative
