### ISSUE TITLE
Add support for loading PBR parameters from MTL via proposed extension

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#7519]
So about a 6 months ago I proposed extending the OBJ/MTL format to include PBR parameters here -- it was partially encouraged by @meshula (Nick Porcino) who is part of the Apple 3D tools team:

http://exocortex.com/blog/extending_wavefront_mtl_to_support_pbr

I proposed this as a new quasi-standard to the guys at Allegorithmic who create Substance Painter, which is arguably the best material creation tool around.  One of their core devs just tweeted in support of it:

https://twitter.com/JBouny/status/660392712177348608

It would be great if I could add this to ThreeJS's MTL loader to encourage further adoption of this extension.  This way ThreeJS can import PBR defined materials from any source that supports the MTL extension, rather than just those that support the specialized ThreeJS ObjectLoader format.

**Comment by mrdoob** [comment]
Sounds good to me.

**Comment by donmccurdy** [comment]
@bhouston do you think supporting the PBR MTL extension is still useful, or do glTF PBR materials address this need now? I do expect that some of the missing properties (clearcoat, anisotropy) will make their way into glTF over time.

**Comment by mrdoob** [comment]
Closing for now.
