### ISSUE TITLE
r73 OBJ converter has alpha backwards? and colorAmbient, mapAmbient still generated

### ISSUE THREAD

**Issue by tparisi** [mrdoob/three.js#7520]
Hey there - I ran the OBJ converter on a model and it's coming out full transparent (opacity 0.0) when the MTL file defines Ka as 1.0 1.0 1.0

The MTL

```
newmtl Textured
Ka 1.000 1.000 1.000
Kd 1.000 1.000 1.000
Ks 0.000 0.000 0.000
d 1.0
illum 2
map_Ka texture.jpg
map_Kd texture.jpg
```

The JSON. Also note the obsolete `colorAmbient` and `mapAmbient` properties
```
{

    "metadata" :
    {
        "formatVersion" : 3.1,
        "sourceFile"    : "model.obj",
        "generatedBy"   : "OBJConverter",
        "vertices"      : 7818,
        "faces"         : 5196,
        "normals"       : 7818,
        "colors"        : 0,
        "uvs"           : 15588,
        "materials"     : 1
    },

    "scale" : 1.000000,

    "materials": [	{
	"DbgColor" : 15658734,
	"DbgIndex" : 0,
	"DbgName" : "Textured",
	"colorAmbient" : [1.0, 1.0, 1.0],
	"colorDiffuse" : [1.0, 1.0, 1.0],
	"colorSpecular" : [0.0, 0.0, 0.0],
	"illumination" : 2,
	"mapAmbient" : "texture.jpg",
	"mapDiffuse" : "texture.jpg",
	"opacity" : 0.0,
	"transparent" : true
	}],
```

**Comment by mrdoob** [comment]
Yeah, that obj converter would benefit of some love 😊

**Comment by tparisi** [comment]
I wish I knew Python better!

**Comment by mrdoob** [comment]
[Ka seems to stand for ambient reflectivity though](http://www.fileformat.info/format/material/), not opacity nor alpha.

**Comment by mrdoob** [comment]
What we're after here is `d 1.0` (as in dissolved).

**Comment by mrdoob** [comment]
And, [as far as I understand](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Material_template_library), `d 1.0` means fully transpaent (dissolved). So I think the current code is correct?

**Comment by tparisi** [comment]
You mean Kd? that would be diffuse

**Comment by tparisi** [comment]
No Kd is diffuse
http://paulbourke.net/dataformats/mtl/

**Comment by tparisi** [comment]
Oh wait you mean just d?

**Comment by mrdoob** [comment]
😉

**Comment by tparisi** [comment]
OK well based on the explanation of the examples, `d` goes from 0 to 1, fully transparent to fully opaque. Have another read and tell me what you think.

**Comment by tparisi** [comment]
Yeah it's right here:

```
d factor
 
 Specifies the dissolve for the current material.
 
 "factor" is the amount this material dissolves into the background.  A 
factor of 1.0 is fully opaque.  This is the default when a new material 
is created.  A factor of 0.0 is fully dissolved (completely 
transparent).
 
 Unlike a real transparent material, the dissolve does not depend upon 
material thickness nor does it have any spectral character.  Dissolve 
works on all illumination models.
```

**Comment by mrdoob** [comment]
There seems to be confusion about this. Some references say `d` and `Tr` are the same and it's `opacity - 1.0`, but some exporters only invert `Tr.

Lets follow tinyobjloader on this one.... https://github.com/syoyo/tinyobjloader/issues/43

**Comment by tparisi** [comment]
They're saying the same thing, `d = Tr - 1.0` So the current converter is backwards, right?

And I'm pretty sure that the `d` value in this sample model is intended to be fully opaque. It's one mesh and without it you won't see anything. :-)

**Comment by mrdoob** [comment]
Yep! Fixing...

**Comment by tparisi** [comment]
great, while you're at it please ditch the ambient props. BTW what is up with that? Ambient color always assumed white now?

**Comment by mrdoob** [comment]
Removed that already. And yes, ambient color is gone.

**Comment by mrdoob** [comment]
Ok, updated. Do you mind testing it with your file?

**Comment by tparisi** [comment]
in dev?

**Comment by tparisi** [comment]
Yeah man - grabbed the latest from dev, looked good. I can see my fish.

**Comment by mrdoob** [comment]
Yay! Thanks!
