### ISSUE TITLE
No support for mat2 uniforms

### ISSUE THREAD

**Issue by MallorLoU** [mrdoob/three.js#7528]
Hey, guys.

Are you planning to add support for mat2 uniforms? Basically I need to pass rotation matrix to fragment shader, and I don't want to pass the angle and do the calculations per pixel.

**Comment by WestLangley** [comment]
Good idea.

```javascript
case 'Matrix2fv':
	_gl.uniformMatrix2fv( location, false, value );
	break;

case 'm2':
	// single THREE.Matrix2
	_gl.uniformMatrix2fv( location, false, value.elements );
	break;
```

**Comment by mrdoob** [comment]
Added. Thanks guys!
