### ISSUE TITLE
Clone on EdgeHelper failed

### ISSUE THREAD

**Issue by tiansijie** [mrdoob/three.js#7533]
here is an example. 

https://jsfiddle.net/b39100np/3/

`Uncaught TypeError: Cannot read property 'clone' of undefined`

I believe is this [clone method](https://github.com/mrdoob/three.js/blob/317d6f66542ab63323c5dab6c7a4e9d08c07ca05/src/objects/Line.js#L180) call the [EdgesHelper](https://github.com/mrdoob/three.js/blob/master/src/extras/helpers/EdgesHelper.js#L11) which takes `object` not `geometry` and `material` as input. We may need to fix the EdgesHelper to adjust this problem. Please correct me if I am wrong.

**Comment by xXCrystalXx** [comment]
Hey tiansijie,
I can not see what is the reason that you want to use the clone method in your code, can you explain that to me? If you want to use an EdgesHelper for your Circle you must add the EdgesHelper in the Scene.

Change this part of your code to this then the Edge Helper can be seen in the scene:
```javascript
var edges = new THREE.EdgesHelper( circle, 0x00ff0f );
/*HERE IS THE PROBLEM*/
//edges.clone();

scene.add( circle );
scene.add( edges );
```

And as an explanation for the behavior of the EdgesHelper, EdgesHelper clone always the geometry of an object.

**Comment by tiansijie** [comment]
@xXCrystalXx you are right, in the example there is no reason to use clone. But I just want to show this bug. Yes, it's also working in r71.

**Comment by xXCrystalXx** [comment]
Alright :+1: 
But I think I've expressed it wrong, I meant that I have tested the problem in version r71 and it does not exist there (in version r71 the clone method works).

**Comment by mrdoob** [comment]
Hmm, the problem is that `EdgesHelper` expects a `object` even if it's extending `LineSegment` which expects a `geometry`.

This was a design mistake. I think the solution will be to complete the deprecation of `EdgesHelper` and promote `EdgesGeometry` instead.

**Comment by Wilkopolis** [comment]
Hey just chiming in on r80. I ran into this issue as well working on my own project. It looks like clone expected an object and not a geometry.

[here is a screenshot of me stepping through it in chrome](http://i.imgur.com/zGHHXKA.jpg)

**Comment by WestLangley** [comment]
> I think the solution will be to complete the deprecation of EdgesHelper and promote EdgesGeometry instead.

Agreed. And in doing so, we eliminate one more instance of the dreadful pattern:
```javascript
this.matrix = object.matrixWorld;
this.matrixAutoUpdate = false;
```
So, for reference, instead of this pattern:
```javascript
// edges helper
var eh = new THREE.EdgesHelper( mesh );
scene.add( eh ); // must be a child of the scene
```
use this pattern:
```javascript
// edges geometry
var geometry = new THREE.EdgesGeometry( mesh.geometry ); // or WireframeGeometry
var material = new THREE.LineBasicMaterial( { color: 0xffff00, linewidth: 2 } );
var edges = new THREE.LineSegments( geometry, material );
mesh.add( edges ); // add wireframe as a child of the parent mesh
```

**Comment by mrdoob** [comment]
Deprecated EdgesHelper and WireframeHelper 😛
