### ISSUE TITLE
Geometry rotate

### ISSUE THREAD

**Issue by kyma** [mrdoob/three.js#7535]
Geometry rotations are not cloned with geometry.clone since v0.73.0. Not sure if this is intended or not. It seems counterintuitive to me. 
Seen with IcosahedronGeometry in three v0.73.0 pulled from NPM

**Comment by mrdoob** [comment]
Can you share the code you are referring to?

**Comment by kyma** [comment]
So I'm creating a primitive:

const geometry = new THREE.IcosahedronGeometry(this.itemRadius);
geometry.rotateX(this.rotateVector.x);
geometry.rotateZ(this.rotateVector.z);

Then if I clone:

const faceGeom = geometry.clone();

and create mesh:

this.frontMesh = new THREE.Mesh(faceGeom, frontMat);

The rotation is gone.  Its rotated if I use the original geometry.  I believe in v72 the rotations were preserved in the clone

**Comment by makc** [comment]
Interested to know how this is possible, when these things are baked into the vertices. Subscribed )

**Comment by kyma** [comment]
Slightly more succinct example:

https://jsfiddle.net/y0fs5o1j/5/

**Comment by makc** [comment]
Ah, right. The clone does this:
```javascript
	return new THREE.IcosahedronGeometry(
		parameters.radius,
		parameters.detail
	);
```

So you eould need [`THREE.Geometry.prototype.clone.apply (geometry)`](https://jsfiddle.net/y0fs5o1j/7/)

**Comment by kyma** [comment]
Ok, but what's the reason for the override here then? It seems to break the expected functionality

**Comment by mrdoob** [comment]
This is related to `.toJSON()`...

There are 2 situations:

1. Ideal situation
```javascript
var geometry = new THREE.IcosahedronGeometry(radius);
geometry.toJSON(); // we only need to export the parameters.
```

2. Not ideal situation
```javascript
var geometry = new THREE.IcosahedronGeometry(radius);
geometry.rotateX( x );
geometry.toJSON(); // we lose the rotation
```

If we cloned the vertices, then case 1 would export too much data. So the problem right now is that we don't know if the user has modified the geometry or not. We can't detect `geometry.vertices[ 1 ].x = 2` and, at the same time, we don't want to always export all the vertices just in case.

We can start adding `isDirty` all around, but I was hoping to find a prettier solution.

**Comment by kyma** [comment]
Thanks for explaining. Perhaps we could pass a boolean in when we call clone?

    clone(true/false);

that would switch between the default optimised route and preserving the mods. Then at least it we could make it clear in the docs that the behaviour differs between geometry and it's subclasses

**Comment by mrdoob** [comment]
What would the `boolean` name be?

**Comment by kyma** [comment]
I guess it would be preserveModification or similar?

**Comment by makc** [comment]
> prettier solution

what about cloning the geometry using THREE.Geometry.prototype.clone, and then replacing the prototype of resulting object? then you might want to have private method to store parameters passed to constructor and call that, too.

**Comment by MasterJames** [comment]
toJSON (dup.transforms=7)? Maybe some bitwise operators dup.transform=1 dup.rotation=2  dup.scale=4
Or in the clone ()
Could be an array for per object or optional attribute in the objects/geo.

**Comment by mrdoob** [comment]
It should be fixed in the `dev` branch. Now clone() `flattens` the cloned geometry. We'll see if someone complains...
