### ISSUE TITLE
DirectionalLight problem with the target

### ISSUE THREAD

**Issue by Kaivomania** [mrdoob/three.js#7536]
Hello,
I have the problem with the DirectionalLight, especially with the target object.
 I created a DirectionalLight:

```javascript
var light = new THREE.DirectionalLight(0xffffff, 1); 
 /*
 *light Settings  
 */
light.position.set(  100, 100,  100  ); 
var t = new THREE.Object3D();
t.position.x = 100;
t.position.y = 0;
t.position.z = 100;
light.target = t;
var dirlightHelper =  new THREE.DirectionalLightHelper(light, 1);
dirlightHelper.update();
scene.add(light);
scene.add(dirlightHelper);
```

the light and the helper are rendered at the scene. 
But the problem is the light target is at (0,0,0) the origin and not the position set (100,0,100), the helper is looking at the same. 
I use Firebug to see what is wrong. 
The targets position is placed on the right position, but only in firebug. On the scene it goes to (0,0,0).

![directproblem](https://cloud.githubusercontent.com/assets/11575586/10938487/f0fbba30-82fa-11e5-8999-3f71702b45a8.png)
 This screen shows the light.target.position. the values are correct, but I have no effect from it.

i updatet to 'THREE.WebGLRenderer 73' so this Problem the first time appeared.

**Comment by WestLangley** [comment]
For an explanation of the issue, and what to do about it, see https://github.com/mrdoob/three.js/issues/5555.

**Comment by Kaivomania** [comment]
thx@ WestLangley
updating the World Matrix solved my Problem.

```javascript
...
light.target = t;
light.target.updateMatrixWorld();
var dirlightHelper =  new THREE.DirectionalLightHelper(light, 1);
...
```
