### ISSUE TITLE
getNormalMatrix(), getInverse() aren't getters

### ISSUE THREAD

**Issue by MajorBreakfast** [mrdoob/three.js#7538]
This confuses me a lot. `copyNormalMatrix()` and `copyNormalMatrixInverse()` would be better names because they clearly convey that the method will mutate the matrix.

**Comment by mrdoob** [comment]
@WestLangley what do you think about the names?

**Comment by WestLangley** [comment]
I think the existing method names are fine, actually.

**Comment by MajorBreakfast** [comment]
@WestLangley The expectation is for `get` to read and the word `set` to write. Using `get` for setting worries me.

**Comment by erichlof** [comment]
@MajorBreakfast , @mrdoob and @WestLangley ,
How about calcNormalMatrix() and calcNormalMatrixInverse() ?  Docs could also be updated to read "mutates the matrix that is passed in to this method", or something similar.

**Comment by MajorBreakfast** [comment]
@erichlof Calc sounds to me more like computing something on the object, like `Geometry#computeBoundingBox()`. `setTo...Of()` would be an alternative, e.g. `setToNormalMatrixOf()`.

**Comment by erichlof** [comment]
The problem with set and To and From is that the camel-case camel has too many humps! :)
Another idea, the verb 'make' is used elsewhere in the library and would be consistent:
makeNormalMatrix() and makeInverse()
Or if we wanted to be verbose, and in the process requiring more keystrokes from the end-user:
makeNormalMatrixOf() and makeInverseOf() , but I prefer the former.

**Comment by WestLangley** [comment]
OK. When the method contains `this.x = foo`, we should probably use `set` or `setFrom` to conform with the rest of the library. `set` is less verbose. Personally, I am not a fan of the `make` nomenclature.

So here is an option.

```javascript
Matrix3.setNormalMatrix( matrix ); // rename
Matrix3.setInverse( matrix ); // rename

Matrix4.setInverse( matrix ); // rename
Matrix4.inverse(); // new
```

Even still, `get` sounds better to me in these cases for some reason.

/ping @bhouston Do you have an opinion on this?

**Comment by bhouston** [comment]
For normal matrix and inverse, I would just have a ```this.inverse()``` and ```this.normalMatrix()``` function and you have to pair that with a ```this.copy()``` or ```this.clone()``` if you want to convert another matrix.  I prefer to have simplier functions rather than functions that combine an operation and a copy/clone.

**Comment by WestLangley** [comment]
@bhouston Thing is, the normal matrix is a `Matrix3`, and it is computed from a `Matrix4`. Similarly for the `inverse` method of `Matrix3`, which inverts just the rotation part of the 4x4 matrix.

In the case of `Matrix4`, however, are you suggesting removing `getInverse()` and replacing with the in-place method `inverse()` only?

**Comment by bhouston** [comment]
You can always extract the inner 3x3 from a Matrix4 into a Matrix3.  And the results for these functions would be the same, as both of these functions do not take into account the other elements anyhow.  This decomposition would still work.

**Comment by bhouston** [comment]
This decomposition would have the added benefit that one could take the inverse of a Matrix3 directly.  I've run into this limitation before.

**Comment by WestLangley** [comment]
Good point. So the usage would be:

```javascript
mat3.setFromMatrix4( mat4 );
mat3.normalMatrix();

mat3.setFromRotationMatrix( mat4 );
mat3.inverse();

mat4.copy( matrix4 );
mat4.inverse();
```

**Comment by bhouston** [comment]
That works.  In the refactor please let the option to throw exceptions when matrices are not invertable. :)

**Comment by MajorBreakfast** [comment]
> camel-case camel has too many humps

@erichlof I agree. Let's use `copy...()` instead of `setTo...Of()`

> Matrix3.setNormalMatrix( matrix )

@WestLangley Just `set...()` is commonly used for setting properties which is here not the case.

> makeNormalMatrix() and makeInverse()

@erichlof Suggests the wrong directionality.

@WestLangley. @bhouston `inverse()` -> `invert()` (verb)

What about this:
```JS
// Matrix3
mat3.set(1, 0, 0,
         0, 1, 0,
         0, 0, 1)

mat3.copy(mat3).invert()
mat3.copyInverse(mat3) // Better performance

mat3.copyNormalMatrix(mat4).invert()
mat3.copyInverseNormalMatrix(mat4) // Better performance

// Matrix4
mat4.set(1, 0, 0, 0,
         0, 1, 0, 0,
         0, 0, 1, 0,
         0, 0, 0, 1)

mat4.copy(mat4).invert()
mat4.copyInverse(mat4) // Better performance
```
Note: No overloading for performance (good for v8 JIT).

**Comment by WestLangley** [comment]
There appears to be satisfaction with the current nomenclature. Thank you for your suggestions.
