### ISSUE TITLE
TextGeometry.js is missing

### ISSUE THREAD

**Issue by maymayw** [mrdoob/three.js#7545]
Followed the source link from this page:
http://threejs.org/docs/#Reference/Extras.Geometries/TextGeometry

and get a page not found error. 

Source

src/extras/geometries/TextGeometry.js

this file is not in the given directory.

**Comment by xXCrystalXx** [comment]
Hey maymayw, I get the same error message when I try to load the source link.
But when you need a example code for a TextGeometry you can show the source from this link:
http://threejs.org/examples/#webgl_geometry_text

greetings Crystal

**Comment by Gassepouille** [comment]
TextGeometry has been moved in the example folder since the r73 : 
https://github.com/mrdoob/three.js/releases   
https://github.com/mrdoob/three.js/tree/master/examples/js/geometries

**Comment by mrdoob** [comment]
`TextGeometry` has been added back to core in `r74` (currently in `dev`).
