### ISSUE TITLE
JSONloader r73 texture path issue

### ISSUE THREAD

**Issue by lennyraposo** [mrdoob/three.js#7548]
JSONloader setTexturepath not working/ignored.

**Comment by lennyraposo** [comment]
hierarchy

json model located in subdir "/models" (under root directory)
textures located in subdir "/textures/mymodel/"  (under root directory)

code example:

var ObjectLoader = new THREE.JSONLoader();

ObjectLoader.load('./models/mymodel.js', function(geometry,materials) { some code },'./textures/mymodel/');

**Comment by lennyraposo** [comment]
same code worked in  r68 - r72

**Comment by mrdoob** [comment]
have you tried `../textures/mymodel/`?

**Comment by lennyraposo** [comment]
No success with that. It's weird cause it's being ignored entirely and instead trying to load the textures from the models directory.

**Comment by OskinElocater** [comment]
I have sort of a similar issue trying to update from r69 to r72. For our project we have 3 LODs for our textures, kept in "high", "medium" and "low" directories inside a folder with models. This way, we determine LOD needed and add directory name to the textures path, so in my screenshot, "models/garage_white/garage_white_tex.jpg" should be "models/garage_white/low/garage_white_tex.jpg", and so on.
![texissue](https://cloud.githubusercontent.com/assets/9026306/11019512/3d7f9a28-8604-11e5-8322-18efd7c7f8e6.jpg)

**Comment by yomotsu** [comment]
seems the argument for texture path has been removed in this change

https://github.com/mrdoob/three.js/commit/a82e43d7f83ee73949a049d0cfac6fa9efc3e92a#diff-768f2ad18cf1f30f3f3637b3f4743845L17
```
-THREE.JSONLoader.prototype.load = function ( url, callback, texturePath ) {
+	load: function( url, onLoad, onProgress, onError ) {
```

Use `setTexturePath` method to set the path.

e.g.
```
var loader = new THREE.JSONLoader();
loader.setTexturePath( 'path/to/texture/' );
loader.load( function ( g, m ) {
  ...
} ) 
```
