### ISSUE TITLE
remove and add new plane on scene

### ISSUE THREAD

**Issue by hungpq3si** [mrdoob/three.js#7549]
Hi mrdoob,
I have a problem, i can't remove or add new plane with new size and new geometry with this function:

function setPlane(sW, sH) {

	var planeSizeW = sW * 2;
	var planeSizeH = sH * 2;
	console.log(plane);
	var geometry = new THREE.PlaneBufferGeometry(planeSizeW, planeSizeH);
	geometry.applyMatrix(new THREE.Matrix4().makeRotationX( - Math.PI / 2));
	plane = new THREE.Mesh(geometry);
	plane.visible = false;
	scene.add(plane);
	objects.push(plane);
	var geometry = new THREE.Geometry();
	for (var i =  - sH; i <= sH; i += 50) {
		geometry.vertices.push(new THREE.Vector3( - sW, 0, i));
		geometry.vertices.push(new THREE.Vector3(sW, 0, i));
	}
	for (var i =  - sW; i <= sW; i += 50) {
		geometry.vertices.push(new THREE.Vector3(i, 0,  - sH));
		geometry.vertices.push(new THREE.Vector3(i, 0, sH));
	}
	geometry.verticesNeedUpdate = true;
	geometry.elementsNeedUpdate = true;
	geometry.normalsNeedUpdate = true;
	var material = new THREE.LineBasicMaterial({
			color : 0x000000,
			opacity : 0.2,
			transparent : false
		});
	var line = new THREE.Line(geometry, material, THREE.LinePieces);
	scene.add(line);

}

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
