### ISSUE TITLE
SVG as texture gets blended in some way

### ISSUE THREAD

**Issue by simonThiele** [mrdoob/three.js#7550]
Hi!

I've got a strange behaviour when using SVG files as textures.

When loading the first texture all is fine but the second one contains the first one when used as a texture (they share the same viewBox in the SVG but that shouldn't be an issue normally). Stuff is working when using PNGs or other image files.

Here is a minimal example: http://jsbin.com/xeyigahata/1/edit?html,js,output

Any remarks on that? Thanks!

The SVGs are:

`<svg version="1.0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">
  <rect fill="#fff" x="0" y="0" width="128" height="64"/>
</svg>`

`<svg version="1.0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">
  <rect fill="#fff" x="64" y="0" width="64" height="128"/>
</svg>`

**Comment by mrdoob** [comment]
I'm trying to access the .svg files but they show up white (obviously).

https://dl.dropboxusercontent.com/s/5qyful99v3vwyxf/1.svg
https://dl.dropboxusercontent.com/s/5qyful99v3vwyxf/3.svg

Could you use red and blue so it's easy to see what's happening?

**Comment by mrdoob** [comment]
Also, I didn't know one could use a svg as texture...

**Comment by simonThiele** [comment]
done... should see a blue and a red rectangle.
We use SVGs in our project for 2D icons and don't want to create a specific png files for the 3D part so we want to reuse what we have. If it can't be solved we have to do, but I thought I inform you that there is something going on.

**Comment by mrdoob** [comment]
A workaround would be to create an intermediate canvas. Have you tried that?

**Comment by makc** [comment]
> I didn't know one could use a svg as texture

they use svg as "src" for Image, so it is still normal texture

**Comment by mrdoob** [comment]
Right, but it's webgl itself the one converting the svg to a texture so it can be uploaded.

**Comment by makc** [comment]
nope, THREE.ImageUtils.loadTexture does create an image, and sets src.

**Comment by makc** [comment]
and at that point it's just pixels.

**Comment by makc** [comment]
Or maybe I am indeed wrong... these images scale up with no aliasing http://jsfiddle.net/7a9w5mjL/

**Comment by mrdoob** [comment]
> and at that point it's just pixels.

Oh, I never knew that. I thought it was still treated as vectors.

**Comment by WestLangley** [comment]
See http://stackoverflow.com/questions/30951739/texture-repeats-and-overlaps-in-three-js

**Comment by makc** [comment]
@WestLangley I tried http://jsfiddle.net/1okpmzsw/ from stackoverflow in both ff and chrome, and it looks like this:
![screen shot 2015-11-07 at 2 28 31](https://cloud.githubusercontent.com/assets/242577/11012646/6d30a036-84f7-11e5-9f4e-cf260849ee72.png)
which seems fine?

**Comment by WestLangley** [comment]
@makc This is what I see on OX X 10.11.1 Chrome 46.0.2490.80 : http://jsfiddle.net/1okpmzsw/

![screen shot 2015-11-06 at 10 16 35 pm](https://cloud.githubusercontent.com/assets/1000017/11013275/5f5d8a1e-84d4-11e5-909a-4d4ff7777584.png)

**Comment by simonThiele** [comment]
Yeah, that is what I meant

**Comment by makc** [comment]
So then can we say it is browser/os bug?

**Comment by simonThiele** [comment]
Canvas workaround works for me so I'm fine with that.

**Comment by simonThiele** [comment]
I created a minimal working example with plain webgl and it's "broken" there too, so issue can be closed thx!

**Comment by mrdoob** [comment]
@simonThiele did you report the bug to the relevant browsers?

**Comment by simonThiele** [comment]
Will do and post the "tickets" here okay?

**Comment by mrdoob** [comment]
Yays!

**Comment by simonThiele** [comment]
first start with chrome: https://code.google.com/p/chromium/issues/detail?id=553885

**Comment by simonThiele** [comment]
Reported on apple too but they keep the ticket inside they bug reporter system without public url.

**Comment by leitzler** [comment]
As a side note, it works in Chrome Canary so they have already fixed it.

**Comment by makc** [comment]
> it works in Chrome Canary

that explains why I could not reproduce it :) but if this is not my os/drivers, then firefox nightly has it fixed, too

**Comment by leitzler** [comment]
I started to dig into the webgl code of Chromium the other day (out of curiosity) to see why this happened but didn't have time enough to find the exact cause. The workaround with canvas works since canvases are handled in a different way than imgs.

**Comment by vorg** [comment]
Just for log this still happens on Safari 11.1 but is fixed in 11.2 https://bugs.webkit.org/show_bug.cgi?id=158527. I ended up with "render to canvas first" workaround as well.
