### ISSUE TITLE
Errors on Internet explorer 11 and edge when texture.needsUpdate

### ISSUE THREAD

**Issue by wouter140** [mrdoob/three.js#7560]
I am making a 360 video player. Now I am testing the player on Internet explorer 11 and edge but it seems to give me some errors I don't get on chrome or firefox.
Errors:
* WEBGL11072: INVALID_VALUE: texImage2D: This texture source is not supported
three.min.js (674,297)
* WEBGL11098: drawArrays: The texture is a non-power-of-two texture or not mipmap complete
three.min.js (621,105)

It shows the errors only every time I call 
```renderer.render(scene, camera);```
and ```texture.needsUpdate = true;```

The texture is a video element.
texture is made like this. ```_videoobj``` is the video.
```javascript
_videoobj = document.getElementById("video");

texture = new THREE.Texture(_videoobj);
```
I get the same error when I make the texture like this:
```javascript
texture = new THREE.VideoTexture(_videoobj);
```

The result is that the renderer will not render anything in the canvas.

**Comment by mrdoob** [comment]
Is the video format WebM?

**Comment by wouter140** [comment]
No, the video is in mp4 format

**Comment by mrdoob** [comment]
I see... What's are the dimensions of the video?

**Comment by wouter140** [comment]
The video width is 1920p and height is 960p

**Comment by leitzler** [comment]
Isn't this just a browser issue? Looks like it has been problems before:
https://connect.microsoft.com/IE/feedback/details/927217/webgl-video-texture-support-is-broken-possible-regression

**Comment by mrdoob** [comment]
Yeah. If it works in Chrome and Firefox, sounds like you should report the bug to Microsoft instead.

**Comment by MasterJames** [comment]
+1 to punishing (if not banishing) Microsoft for decades of insubordination.
Sent to you from 8.1 :cold_sweat:

**Comment by diacoco** [comment]
i just made a little workaround based on the idea of Brian Chirls.
The idea is to create a canvas for the video texture, draw the video in the canvas and use this canvas for the texture... it will use more CPU/Memory but it will work on IE.
For me it's a workaround not a real fix.

// add this to the THREE vars
THREE.noVideoTextureSupport = false;

// replace the videoTexture function
THREE.VideoTexture = function ( video, mapping, wrapS, wrapT, magFilter, minFilter, format, type, anisotropy ) {
	if (THREE.noVideoTextureSupport)
	{
		this.video = video;
		this.ctx2d = document.createElement('canvas').getContext('2d');
		var canvas = this.ctx2d.canvas;
		canvas.width = video.width;
		canvas.height = video.height;
		this.ctx2d.drawImage(this.video, 0, 0, this.width, this.height);
		THREE.Texture.call( this, this.canvas, mapping, wrapS, wrapT, magFilter, minFilter, format, type, anisotropy );
	} else {
		THREE.Texture.call( this, video, mapping, wrapS, wrapT, magFilter, minFilter, format, type, anisotropy );
	}
	this.generateMipmaps = false;
	var scope = this;
	if (THREE.noVideoTextureSupport) {
		function update() {
			requestAnimationFrame( update );
			if ( video.readyState >= video.HAVE_CURRENT_DATA ) {
				scope.ctx2d.drawImage(scope.video, 0, 0, scope.video.width, scope.video.height);
				scope.needsUpdate = true;
			}
		}
	} else {
		function update() {
			requestAnimationFrame( update );
			if ( video.readyState >= video.HAVE_CURRENT_DATA ) {
				scope.needsUpdate = true;
			}
		}
	}
	update();
};

then you just have to set THREE.noVideoTextureSupport to true if it's IE, and the VideoTexture will work.

**Comment by keeganbrown** [comment]
I ran into the same issue and Diacoco's solution had to be modified slightly to work in my circumstances.

```javascript

(function () {

  // add this to the THREE vars
  THREE.noVideoTextureSupport = false; //SET THIS VALUE TO TRUE FOR IE

  // replace the videoTexture function
  THREE.VideoTexture = (function () {
    var _videoTexture = THREE.VideoTexture;
    var _ieVideoTexture = function ( video, mapping, wrapS, wrapT, magFilter, minFilter, format, type, anisotropy ) {
      if (THREE.noVideoTextureSupport) {
        var scope = this;

        scope.video = video;
        scope.ctx2d = document.createElement('canvas').getContext('2d');
        var canvas = scope.ctx2d.canvas;
        canvas.width = video.width;
        canvas.height = video.height;

        scope.ctx2d.drawImage(scope.video, 0, 0, scope.width, scope.height);
        THREE.Texture.call( scope, scope.ctx2d.canvas, mapping, wrapS, wrapT, magFilter, minFilter, format, type, anisotropy );

        scope.generateMipmaps = false;

        function update() {
          requestAnimationFrame( update );
          if ( video.readyState >= video.HAVE_CURRENT_DATA ) {
            scope.ctx2d.drawImage(scope.video, 0, 0, scope.video.width, scope.video.height);
            scope.needsUpdate = true;
          }
        }

        update();
      }
      var args = [];
      for (var i = 0; i < arguments.length; i++) {
        args.push(arguments[i]);
      }
    };
    return (THREE.noVideoTextureSupport ? _ieVideoTexture : _videoTexture);
  })();

  THREE.VideoTexture.prototype = Object.create( THREE.Texture.prototype );
  THREE.VideoTexture.prototype.constructor = THREE.VideoTexture;

})();

```

**Comment by bknill** [comment]
Hi I'm having the same issue on Win7/IE11 (pesky government departments) and this fix has taken the error away, but video is black.  

If I try and render it in Chrome with the flag set to true, I get millons of these errors:

`WebGL: INVALID_VALUE: texImage2D: no canvas
/g362/s1832:1 [.Offscreen-For-WebGL-0D396118]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.`

This is because of the video size right!?

**Comment by keeganbrown** [comment]
My memory is a bit hazy on this ATM, but I think that could be a video encoding issue. Try re-encoding the video & make sure the video plays naturally (aka in a video tag) in in IE.

**Comment by marklundin** [comment]
For reference, the IE documentation on `textImage2D` specifies that 'ImageData array, ArrayBufferView, HTMLCanvasElement, HTMLImageElement to use as a data source for the texture', but seems to leave out the HTMLVideoElement or HTMLMediaElement. I'm not sure if this is just an oversight in the documentation or actually how they've implemented it.

https://msdn.microsoft.com/en-us/library/dn302435(v=vs.85).aspx
