### ISSUE TITLE
This uniform location is obsolete because its program has been successfully relinked.

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#7561]
this often happens (in uniformXxx calls) after I edit the shader in firefox shader editor. can 3js be made to have the flag to not cache uniforms or something, specifically for debugging the shaders?

**Comment by makc** [comment]
maybe if this error could be caught then setting needsUpdate on material might solve the problem in the next render call? I do not use shader editor as much these days, mostly because it almost always breaks the program, it is again way easier to edit-reload. we just can't have good things, because noone cares tomake sure they work after the changes

**Comment by Mugen87** [comment]
> maybe if this error could be caught then setting needsUpdate on material might solve the problem in the next render call?

I'm not sure why this should be the case. Is this message actually an error or a just warning? TBH, I've never seen it before. Any chances to reproduce the message with a fiddle?

**Comment by Mugen87** [comment]
> then again maybe not because the shader would be restored from original
source, not the edited one.

In this case, I don't think it makes sense to change the library just avoid this message. In "normal" use cases of `three.js`, the message does not pop up anyway. Live-editing shaders with a third party tool is not a "normal" usage form my point of view.
