### ISSUE TITLE
Loaders and redirects

### ISSUE THREAD

**Issue by Benjamin-Dobell** [mrdoob/three.js#7563]
If for example an `ObjectLoader` is given the URL of a scene to download but receives a redirect (302 etc.), XMLHttpRequest silently follows the redirect. This is good, but issues arise when it comes time to load the textures, which are supposed to be relative to the scene.

At the moment `ObjectLoader` tries to load the textures relative to the non-redirected URL, which is incorrect behaviour. `XMLHttpRequest` has a `responseURL` which is the final URL the response (in this case the scene) was loaded from. Instead of just returning the response body on success, `Loader`s should be returning more information, in this case in particular, we care about the `responseURL`. `ObjectLoader` would then be able access `responseURL` and resolve texture URLs correctly, relative to this URL.

**Comment by Benjamin-Dobell** [comment]
I did put together a rather quick and dirty solution my end. However, I think there is some discussion to be had about what a desirable solution might look like. Then I'd be happy to submit a pull request.

**Comment by Benjamin-Dobell** [comment]
Related to this, caching is also incorrect, but I'm not sure whether that issue is worth fixing. Namely the response is cached against the original URL, rather than the responseURL. That would be fine in the case of 301 (Moved Permanently) or 308 (Permanent Redirect) status codes, however 302 (Found) and 307 (Temporary Redirect) should not be cached, as each time you hit URL you may be sent to a different URL.

**Comment by Benjamin-Dobell** [comment]
I'm closing this issue because I don't think there is a sane solution.

In order to load resources relative to a redirected response, we need to know where the response was served from. Hence the `responseURL` property I mentioned on `XMLHttpRequest`. However, it looks like there is all sorts of nonsense going on trying to ratify a sane JS fetch specification (https://fetch.spec.whatwg.org/#atomic-http-redirect-handling), and this has had implications on existing `XMLHttpRequest` implementations in browsers.

Basically somebody somewhere seems to be complaining that redirects should remain transparent to both the `fetch` and `XMLHttpRequest` APIs, because exposing the redirected URL is supposedly a cross-site scripting vulnerability. It sounds like nonsense to me, but browsers seem to have been maimed nonetheless.

**Comment by leitzler** [comment]
Also, the responseURL is a rather new property in the browsers so it would be unwise to rely on it :)

**Comment by MasterJames** [comment]
Maybe in cases of perminent redirect a popup/alert is best. Maybe one that let's you choose to accept the change, if not just a warning.
