### ISSUE TITLE
Flatten 3d Object into 2 object

### ISSUE THREAD

**Issue by jonnyfinlay99** [mrdoob/three.js#7565]
Only started working with three and its great so far and i'm now creating models in blender and messing around with them and i've run into a problem thats stumped me so far how would I flatten a 3d object such a cube or cuboid into its 2d planes like in this image.

![Image of Flattened Cube]
(http://www.bbc.co.uk/staticarchive/c12123282eea462b8a35ba781a69abd361c021e5.gif)

Any help would be greatly appreciated.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by Mardonis** [comment]
I found this if it helps.
http://stackoverflow.com/questions/963084/decomposing-a-3d-mesh-into-a-2d-net
