### ISSUE TITLE
XHRLoader line 70 make no sense

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#7568]
https://github.com/mrdoob/three.js/blob/master/src/loaders/XHRLoader.js#L70-L71

```javascript
if ( this.crossOrigin !== undefined ) request.crossOrigin = this.crossOrigin;
if ( this.responseType !== undefined ) request.responseType = this.responseType;
```

1st, line 70 does not seem to make any sense since neither [FireFox](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest), nor [IE](https://msdn.microsoft.com/en-us/library/ms535874%28v=vs.85%29.aspx#properties) or [Safari](https://developer.apple.com/library/prerelease/mac/documentation/AppleApplications/Conceptual/SafariJSProgTopics/XHR.html) does not even mention crossOrigin property. From Safari doc and from jsfiddle test I did it seems XMLHttpRequest sets origin header for different domains automatically (and it makes sense, or else the result would have to be 100% error).

~~2nd, line 71 seems to write into the property that is set by the browser after response is received.~~

**Comment by mrdoob** [comment]
> 1st, line 70 does not seem to make any sense since neither FireFox, nor IE or Safari does not even mention crossOrigin property. From Safari doc and from jsfiddle test I did it seems XMLHttpRequest sets origin header for different domains automatically (and it makes sense, or else the result would have to be 100% error).

No idea about this one...

> 2nd, line 71 seems to write into the property that is set by the browser after response is received. You probably want to call overrideMimeType(), as in #7554 

No... `request.send( null );` has not been executed yet at that point. `responseType` is used to load `arraybuffer`.

**Comment by makc** [comment]
Okay, I dont know what was I thinking about responseType. With three docs open. Good thing I did not edit the file then )

**Comment by mrdoob** [comment]
Indeed... crossOrigin must have been me bling copy/pasting when doing XHRLoader.

**Comment by mrdoob** [comment]
Fixed. Thanks!
