### ISSUE TITLE
Shader Problem 

### ISSUE THREAD

**Issue by PaulSos** [mrdoob/three.js#7569]
We got a Problem with the Shadowmap... The Shadow the Building throw on itself, isnt like we expacted it, or how it should be (much darker)... but we cant figure out what's the Problem

http://viodesign.de/Itaricon/index.html

May someone got an Idea?

**Comment by Mardonis** [comment]
I am finding these errors in the console of Chrome Version 46.0.2490.80 m for your site.

THREE.WebGLRenderer 72
THREE.WebGLRenderer: .shadowMapEnabled is now .shadowMap.enabled.
THREE.WebGLRenderer: .shadowMapType is now .shadowMap.type.
THREE.BufferGeometry.addAttribute: Use .setIndex() for index attribute.
GET http://viodesign.de/Itaricon/models/Fenster_gr%C3%BCn.png 404 (Not Found)

Try changing the shadowMapEnabled and shadowMapType to what they need to be first. Also look at the addAttribute under BufferGeometry and us setIndex as its describing. Looks like a problem with one of your png pictures couldn't be found. If you can try using the latest version available of 73. The dev version of 74 might be able to help as well.

**Comment by PaulSos** [comment]
we fixed the warnings and solved the problem with the mising texture.png.

But The Problem with the Thrown Shading still exists, any Idea?!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

**Comment by mrdoob** [comment]
@PaulSos Trying to fix this in this current cycle. `r74dev` may already give you better results.
