### ISSUE TITLE
Need an image on a hexagonal plane

### ISSUE THREAD

**Issue by SudheendraSingh** [mrdoob/three.js#7570]
Hi,
   I am new to three.js and am having trouble rendering an hexogon with an image on it. Any pointers will be helpful. Tried ShapeGeometry but it doesnt seem to render image though the hexagon comes up fine.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
