### ISSUE TITLE
Required files missing from bower distribution

### ISSUE THREAD

**Issue by dazwin** [mrdoob/three.js#7571]
I'm trying to add some text to my scene...

- The bower distribution is missing FontUtils.js, needed by TextGeometry.js. Neither of these are in three.(.min).js
- It seems strange that I need to pull in files from the examples/ directory to call documented functions.

Is there major transition going on? It looks like features are being moved out of the core (compiled) package, but there is no sanctioned way (e.g. a three.js-addons package?) to use what seems to be a lot of valuable code.

Thanks!

**Comment by GGAlanSmithee** [comment]
I think the aim is to keep the file under 100kb, which requires a bit of priorization. There is a build system that you can use to make [custom builds](https://github.com/mrdoob/three.js/wiki/build.py,-or-how-to-generate-a-compressed-three.js-file)

**Comment by GGAlanSmithee** [comment]
Hmm. I see that the page I linked has a notice about it being outdated. Not sure in what way though.

**Comment by mrdoob** [comment]
`TextGeometry` has been added back to core in `r74` (currently in `dev`).
