### ISSUE TITLE
transparent map issue

### ISSUE THREAD

**Issue by cnwander** [mrdoob/three.js#7572]
I'm import geometry  and I have set a transparent map, though, not all parts are transparent.

I'm using a transparent PNG image as the material map, though it shows a black background as seen here:
![image](https://cloud.githubusercontent.com/assets/1005746/11109405/0115d762-892b-11e5-8686-11ef5519da79.png)
![image](https://cloud.githubusercontent.com/assets/1005746/11109574/e1d99cb0-892c-11e5-8672-ef70ee397f49.png)

material:
```
new THREE.MeshLambertMaterial({ map: texture, transparent: true, alphaTest: 0})
```
renderer
```
renderer = new THREE.WebGLRenderer({antialias: true, alpha: true});
renderer.preserveDrawingBuffer   = true;
renderer.premultipliedAlpha = false;
```

thanks

**Comment by cnwander** [comment]
material map:
![image](https://cloud.githubusercontent.com/assets/1005746/11109610/38b51906-892d-11e5-9559-15911e9066e9.png)

**Comment by mrdoob** [comment]
`alphaTest: 0.5` may help, but transparency is still a difficult topic in realtime 3d.
