### ISSUE TITLE
What happened to the WebGLRenderer's makeGroup() functionality?

### ISSUE THREAD

**Issue by TomSlezakowski** [mrdoob/three.js#7573]
It seems to be in r71, but not in r72 but I don't see anything in the release notes. 

Many thanks

**Comment by mrdoob** [comment]
It got removed. The whole `WebGLRenderer` was refactored.

**Comment by TomSlezakowski** [comment]
Ah I see. Is there anything that takes it's place? I've been using it in a project I'm developing, but moving back to a release that has it means I lose other newer functionality I also require.

**Comment by mrdoob** [comment]
What were you using it for? As far as I remember it was only used internally.

**Comment by TomSlezakowski** [comment]
I was using it for calculating the vertex normals in some generative geometry. However after some digging it seems like I no longer need it. 

Thanks for the clarification on it being removed. I'll close this out now :)
