### ISSUE TITLE
Load camera from scene file

### ISSUE THREAD

**Issue by sergejey** [mrdoob/three.js#7574]
Hello,

I'm trying to load scene from the file exported from Editor. I'm parsing the file myself and when going through cameras I have to add the using json matrix property like that:
camera.matrix.fromArray(objJSON.matrix);

It works correct but the problem is that rotation is not set correct. I got camera added to the scene at correct position and with the right "lookat" vector, but rotation is not correct. Maybe I have to add camera some other way? Please suggest.

Thank you!

**Comment by mrdoob** [comment]
Can you share a .json file wen can test with?

**Comment by makc** [comment]
you need to camera.matrix.decompose (camera.position, camera.quaternion, camera.scale); after that.

**Comment by sergejey** [comment]
matrix.decompose worked great.
Thanks a lot!

**Comment by mrdoob** [comment]
Oh man, you're on a roll @makc! 😀

**Comment by makc** [comment]
@mrdoob I have developed strange habit of checking your issues trackcer time to time. like 4chan or twitter. Idky.
