### ISSUE TITLE
Webview in 3D Scene

### ISSUE THREAD

**Issue by marklinmao** [mrdoob/three.js#7575]
I am doing a project which provides a 3D scene(implemented with three.js), but not only limited to a 3D scene. I want to integrate the UI of other application(web-based) into this 3D scene.

for example: Let's say we have a cube, I 'd like to integrate the existing UI of another application into one of the 6 faces of the cube.

The solution could be that we have webview component in WebGL/three.js which can behave like a browser(inside the 3D scene), so that the embedded browser can access any web applications.

Benefit: I think this webview should be an revolutionary component to really make WebGL and even 3D user interface or 3D visualizations popular, instead of being used as just graphic now.

Does anyone have any comments or do you have any plan on this?

BR
Lin

**Comment by MasterJames** [comment]
Unfortunately this is for bugs and feature requests only. Let's pretent you are feature requesting.
This article from 2013 is probably what you're asking about, and so not you want THREE.CSS3DObject 

http://learningthreejs.com/blog/2013/04/30/closing-the-gap-between-html-and-webgl/

**Comment by marklinmao** [comment]
Hi, James
Yes what I posted is a feature request, and THANKS for your comments. That is exactly what I need! 
THANK YOU!!
