### ISSUE TITLE
Get axis of the 3D object

### ISSUE THREAD

**Issue by ArvindhS** [mrdoob/three.js#7576]
mrdoob
       I couldn't get the x-axis value from the 3d-object.Is there any way to get axis value of the object.
As per your suggestions,I used stackoverflow also,But i couldn't figure out the solution for my problem.Kindly Help me.

**Comment by MasterJames** [comment]
Can you post the link to your stackoverflow here, please?

**Comment by ArvindhS** [comment]
Sorry @MasterJames .I dont know how to ask question in stackoverflow.Each  and every time while i raising a question in stackoverflow,it show some error.

**Comment by ArvindhS** [comment]
@MasterJames My stackoverflow link is http://stackoverflow.com/questions/33669685/get-axis-of-the-3d-object-by-using-three-js

**Comment by mrdoob** [comment]
#7543

**Comment by MasterJames** [comment]
It seems he was looking for the newer boundingBox Helper

        var helper = new THREE.BoundingBoxHelper(mesh, 0xff0000);
        helper.update();
        scene.add(helper);
        console.log(helper.box.min);
		console.log(helper.box.max);

**Comment by MasterJames** [comment]
Also changed to BoxHelper since days gone by.
