### ISSUE TITLE
line width on windows issue

### ISSUE THREAD

**Issue by jjcc1421** [mrdoob/three.js#7579]
Hello, I know about issue about line widht (http://threejs.org/docs/#Reference/Materials/LineBasicMaterial) in windows, but all examples work good in local and remote host,
In specific case http://threejs.org/examples/#canvas_lines_colors works it.
See images:
In Firefox:
![12250215_10153296174301819_593403814_o](https://cloud.githubusercontent.com/assets/4220107/11130201/c158e9f8-8951-11e5-88a6-9d0e3845815e.jpg)
In Chrome
![captura](https://cloud.githubusercontent.com/assets/4220107/11130342/81f21d56-8952-11e5-8f7d-85c80a145228.PNG)
Anyone know why work this? or how could I add other kind of line that I can add widh?

**Comment by mrdoob** [comment]
That only applies to `WebGLRenderer`. Will clarify the documentation.

**Comment by George35mk** [comment]
https://threejs.org/examples/?q=line#webgl_lines_fat
