### ISSUE TITLE
CatmullRomCurve3 replace SplineCurve3 but ClosedSplineCurve3 isnt renamed

### ISSUE THREAD

**Issue by JordanDelcros** [mrdoob/three.js#7587]
`SplineCurve3` is replaced by `CatmullRomCurve3`
So, `ClosedCurve3` should be replaced by `ClosedCatmullRomCurve3` no?

**Comment by WestLangley** [comment]
I think you mean `ClosedSplineCurve3` should be replaced by `ClosedCatmullRomCurve3`.

/ping @zz85

**Comment by JordanDelcros** [comment]
Oups, sorry, yes, thats what I meant.

**Comment by zz85** [comment]
Actually I am thinking of combining `ClosedSplineCurve3 ` back into `CatmullRomCurve3`.

The CatmullRomCurve3 has become such a utility class that if we were to split it up, would become

`CentripetalCurve`, `ChordalCurve`, `CatmullromCurve` and their closed counterparts `ClosedCentripetalCurve`, `ClosedChordalCurve`, `ClosedCatmullromCurve`....

**Comment by WestLangley** [comment]
@zz85 +1

**Comment by JordanDelcros** [comment]
@zz85 +1

So "closed" will become an option for `CatmullRomCurve3`?
