### ISSUE TITLE
Ray collision fails when origin in a face 

### ISSUE THREAD

**Issue by danielribeiro** [mrdoob/three.js#759]
Hi,

When I cast a ray with origin point inside the face of a Mesh, it won't detect a collision. Quick example (a modified version of examples/canvas_interactive_cubes.html from r45): https://gist.github.com/1366114

Noting that,

``` javascript
var V = THREE.Vector3;
```

changing the line 159 of the gist, from

``` javascript
var origin = new V(20, 20, 20);
```

to

``` javascript
var origin = new V(19.5, 19.5, 19.5);
```

shows that the collision will work fine.

**Comment by kevanstannard** [comment]
@mrdoob do you think this might be resolved now? I created a simple test and it seems to be working correctly, but not sure if I understood the original problem properly.

https://jsfiddle.net/sveom5ay/1/

**Comment by mrdoob** [comment]
@kevanstannard Seems to be. Thanks!
