### ISSUE TITLE
TGALoader seems not work

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#7596]
TGALoader and its example seem not work now.

http://threejs.org/examples/#webgl_materials_texture_tga just shows two black cubes with this error message:

WebGL: drawArrays: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering or is not 'texture complete'. Or the texture is Float or Half Float type with linear filtering while OES_float_linear or OES_half_float_linear extension is not enabled.

**Comment by mrdoob** [comment]
Yep. I noticed. Its been broken for a while already. Haven't had a chance to look a it...

**Comment by takahirox** [comment]
I figured out how to fix and sent PR #7598 

Since this commit 5cee8deca61c42b4ad90d7ec21828c05fafe8600, texture.magFilter and texture.minFilter are defined as THREE.LinearFilter and THREE.LinearMipMapLinearFilter respectively by BinaryTextireLoader if they're undefined while they're defined as THREE.NearestFilter by DataTexture before that commit.

So explicitly defining them as THREE.NearestFilter in TGALoader is an easy way to fix.

**Comment by mrdoob** [comment]
Thanks!
