### ISSUE TITLE
How to JUDGE the obj model size?

### ISSUE THREAD

**Issue by likexoo** [mrdoob/three.js#7600]
The model will be upload by:

loader.load( '../models/Liit.obj','../models/Liit.mtl', function ( object ) {
                         ................
                    scene.add( object );
                }
        );

But there is a problem that it is hard to view the model if the model is too large.So is there a way to judge model size?and then i can resize model by:

object.scale.set( 0.1, 0.1, 0.1 ); 

Hope to get your advice!!!!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

    Box3.setfromObject( object )
