### ISSUE TITLE
Physically-based falloff for Spot and Point Lights

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#7608]
Our spot and point lights were not physically-based.  The main issue is our falloff calculation.  This issue attempts to provide a firm physically-based foundation for changing our lights.

Our spot and point lights currently are specified in terms of [radiant intensity](https://en.wikipedia.org/wiki/Radiant_intensity), I.  Which is a measure of Power / Solid Angle (Candela).  We can also think of light strengths in terms of power, Phi, directly.  Determining the power of a point or spot light (making a simplification that Frostbite does, see note 1) is simple, just integrate across the solid angle sphere: Power(I) = 4 * PI * I.

To do shading calculations, we require the irradiance at a specific point in space, usually a surface.  To calculate irradiance from a spherically emitting light (e.g. spot or point), we just need to figure out the amount of power received per area, .e.g irradiance.  This can be calculated by taking the power of the light and dividing by the spherical area at the distance desired: SphereArea( R ) = 4 * PI * R^2.

```
= Power(I) / SphereArea( R )
= 4*PI*I / 4*PI*R^2
= I / R^2
```

This gives us the quadratic falloff for point and spherical lights, E = I / distance^2, where E is the irradiance at the surface, I is the light radiant intensity and distance is the distance from the light to the surface.

(One change to the above falloff equation would be to allow one to specify the falloff decay.  Thus instead of a fixed "2" one could vary it to be linear, constant or cubic or whatever.  The resulting equation would be ```= I / R^decay```.)

Both UE4 and Frostbite 3 suggest a further modification to the falloff to enable one to limit the range of a light's effectiveness for optimization purposes.  They both suggest multiplying the falloff above with this:

```distanceLimit = saturate( 1 - ( distance / maxDistance )^4 )^2```

This equation, which is extensive discussed in the linked to references provides the best mix of limiting the range nicely, while not affecting the light in regions not close to the distance limit.

The resulting falloff equation, excluding the I, intensity variable, becomes this:

```falloff(distance, maxDistance, decay) = saturate( 1 - ( distance / maxDistance )^4 )^2 / (distance^decay)```

Frostbite makes an assumption that lights can not be smaller than epsilon (in their case 1cm, 0.01m) when calculating falloff to avoid divide by zero issues when calculating light intensities very close to a light.  This modifies the falloff to be:

```falloff(distance, maxDistance, decay) = saturate( 1 - ( distance / maxDistance )^4 )^2 / ( max( distance, epsilon )^decay)```

I would like to make a PR that makes this change to our falloff, and also adds the ability to set light power on both point and spot via a ```power``` getter and setter.

The only question is how to handle backwards compatibility given that our current light falloff is non-physical?

/ping @WestLangley @mrdoob @tschw @gero3 

Sources:

Frostbite 3: http://www.frostbite.com/wp-content/uploads/2014/11/course_notes_moving_frostbite_to_pbr.pdf

UE4: http://blog.selfshadow.com/publications/s2013-shading-course/karis/s2013_pbs_epic_notes_v2.pdf

Notes:

1. Frostbite assumes that a spot light does not focus its light power but rather it just lets some of the light power escape.  This means that changing the spot angle on a spot light does not change its intensity.

**Comment by bhouston** [comment]
I've made the PR for this suggested change here: #7609

**Comment by WestLangley** [comment]
I support adding physically-based lighting.

>The only question is how to handle backwards compatibility given that our current light falloff is non-physical?

In the Frostbite notes, they said they support _both_ punctual lights (which we currently implement) and photometric lights. (How they make the two light types "consistent" seems like a miracle to me, but it all explained in the paper.) Maybe we can create new "physical" light types and do the same?

Also, we have been thinking in terms of "radiance", but in Frostbite, they use photometric units: luminance rather than radiance -- or so they say in the paper.

**Comment by bhouston** [comment]
> In the Frostbite notes, they said they support both punctual lights (which we currently implement) and photometric lights.

Photometric and punctual are not opposites as you appear to be discussing them.  Photometric is a measure of light intensity based on the visible spectrum, where as punctual just means that lights that is emitted from a point source.  Both terms have to do with lighting but the distinction between the two is not relevant to the proposed changes.

> Also, we have been thinking in terms of "radiance", but in Frostbite, they use photometric units: luminance rather than radiance -- or so they say in the paper.

Technically we are already in luminance for all of our quantities, because we focus exclusively on what can be perceived by humans, but we use the terminology of radiance/irradiance, etc.  I have stuck with our terminology.  I would like to keep this PR focused, so I would prefer not discussing switch terminology at this point between luminance/radiance as it is generally immaterial.

**Comment by bhouston** [comment]
> Maybe we can create new "physical" light types and do the same?

We should just fix out lights while maintaining a degree of backwards compatibility.  Otherwise we will have a set of default broken lights.  @mrdoob has stated that he is okay with a breaking set of changes to the lights.  If we just fix our lights in this fashion, point and spot will be physically correct and it is one breaking change that is badly needed.  This PR also clarifies our units in our lighting code in a way that is badly needed.

You can see clearly in this PR that if we do not implement falloff correctly, it breaks our otherwise correct handling of units.

**Comment by bhouston** [comment]
Completed.
