### ISSUE TITLE
Matrix3.getInverse() second parameter `throwOnInvertible` is incorrectly named.

### ISSUE THREAD

**Issue by brentwalther** [mrdoob/three.js#7612]
The second parameter implies that an error will be thrown if the matrix __is__ inverted when it's intended use is to have an error thrown when the matrix is __degenerate__.

Proposed solution: Rename the variable to `throwOnDegenerate` and update the documentation.

**Comment by mrdoob** [comment]
Sounds good to me.
/ping @WestLangley

**Comment by WestLangley** [comment]
OK with me, too.

**Comment by mrdoob** [comment]
Thanks!
