### ISSUE TITLE
MeshStandardMaterial doesn't work with double sided

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#7613]
Just noticed this.  It appears that only one side renders.

**Comment by mrdoob** [comment]
Seems to work fine here...?

![screen shot 2015-11-16 at 21 47 00](https://cloud.githubusercontent.com/assets/97088/11201376/a1106aba-8cab-11e5-9485-7f9b5dcf204d.png)

**Comment by WestLangley** [comment]
It has been working correctly for me, too.

**Comment by bhouston** [comment]
Sorry about the mistake.  Must have screwed up on my end.
