### ISSUE TITLE
Shadow problems with THREE.DirectionalLight and THREE.MeshBasicMaterial

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#7617]
Hi everybody!

i want to upgrade three.js to R73 in my current project. Unfortunately, i'm getting strange shadows casted by a `THREE.DirectionalLight` on a `THREE.MeshBasicMaterial`. Check out the following screenshots:

three.js R72 :+1: 
![shadow_r72](https://cloud.githubusercontent.com/assets/12612165/11208015/ecc2393a-8d18-11e5-94b7-13255dc5deae.jpg)

three.js R73 :-1: 
![shadow_r73](https://cloud.githubusercontent.com/assets/12612165/11208038/0c5f949a-8d19-11e5-905f-67b9b02d54c2.jpg)

As you can see, the shadow in R73 is totally black.

OS: OS X Yosemite 10.10.5
GPU: AMD Radeon R9 M295X 4096 MB
Browser: Chrome 46.0.2490.86 (64-bit)

**Comment by GGAlanSmithee** [comment]
was removed? #7321

**Comment by GGAlanSmithee** [comment]
I do think shadows are still being worked on though #6420 not sure if this landed in r73?

**Comment by Mugen87** [comment]
I have an `THREE.AmbientLight` in this scene but it actually has no effect on the shadow...

**Comment by Mardonis** [comment]
Try and use the development version r74 and see what you get. Lots of things have been fixed.

**Comment by mrdoob** [comment]
I changed the `shadowDarkness` default to `1` (to start discouraging its use). You can still do `light.shadowDarkness = 0.5`; But I would suggest to add an `new THREE.AmbientLight( 0x808080 )` to your scene instead.

**Comment by WestLangley** [comment]
>I would suggest adding new THREE.AmbientLight( 0x808080 ) to your scene instead.

@Mugen87 is using `MeshBasicMaterial`, which does not respond to light sources. Switching to another material is required in that case.

**Comment by mrdoob** [comment]
Ah! True.

**Comment by Mugen87** [comment]
Thanks for your feedback! Using `AmbientLight` with an other material like `MeshLambertMaterial` worked for me. But because i want to use `MeshBasicMaterial`, i adjusted `shadowDarkness ` to `0.5`. 

@mrdoob and @WestLangley : Is using `shadowDarkness ` in combination with `MeshBasicMaterial` still a valid way for tweaking shadows? Or is this approach deprecated? 

Besides, maybe it's a good idea to include the different shadow handling to the [migration guide](https://github.com/mrdoob/three.js/wiki/Migration). I can image, that other users run in the same issue...

**Comment by mrdoob** [comment]
> @mrdoob and @WestLangley : Is using light.shadow.darkness = 0.5 in combination with MeshBasicMaterial still a valid way for tweaking shadows? Or is this approach deprecated?

For the time being it's ok. However `MeshBasicMaterial` is supposed to be unlit. So it shouldn't support shadows. However, http://threejs.org/examples/#webgl_geometry_spline_editor is a good use case where one can control the color of the surface and add shadow. This example is why `MeshBasicMaterial` still supports shadows and `shadow.darkness` is still available. Once I figure out how to do it in a different way the current approach may get deprecated.

For your use case, you may want to use case... Any reason you're using `MeshBasicMaterial` and not `MeshLambertMaterial` or `MeshPhongMaterial`?

> Besides, maybe it's a good idea to include the new shadow handling to the [migration guide](https://github.com/mrdoob/three.js/wiki/Migration). I can image, that other users run in the same issue...

Done.

**Comment by makc** [comment]
@mrdoob 
> This example

just fyi this example looks like this over here:

![screen shot 2015-11-18 at 23 02 39](https://cloud.githubusercontent.com/assets/242577/11255818/a437d338-8e48-11e5-9056-d051f29e6aa0.png)

**Comment by Mugen87** [comment]
> For your use case, you may want to use case... Any reason you're using MeshBasicMaterial and not MeshLambertMaterial or MeshPhongMaterial? 
>

I want a consistent color over the entire surface of a 3D object. `MeshBasicMaterial` is perfect for this, because i don't need any lights to get this effect. If there are alternate ways to do same, well, i always have an open mind for other solutions :wink: 

Thanks again for your answers!

**Comment by Mugen87** [comment]
By the way, i close this issue because my original problems is solved!

**Comment by mrdoob** [comment]
> just fyi this example looks like this over here

Looks correct to me...?

**Comment by makc** [comment]
> Looks correct to me...?

so the shadow is supposed to look dashed?

**Comment by mrdoob** [comment]
Yeah, I guess these are the expected artifacts when convining `THREE.PCFShadowMap` and lines...

**Comment by douglascross** [comment]
Was trying to get softer shadows and then discovered a trick of using emissive color on the object receiving the shadow. This might help someone.
