### ISSUE TITLE
Wildly different results from Vector3.unproject(PerspectiveCamera) - r72

### ISSUE THREAD

**Issue by justinvh** [mrdoob/three.js#7619]
r72
----

I am trying to get a handle on a bug I observe in the projection from mouse coordinates to worldspace coordinates.

I am rendering a map of earth. The map is projected into the world and we end up with a view that looks like:

![The world](http://i.imgur.com/0wY9x87.jpg)

The camera can be created from the following:

```"{"object":{"metadata":     {"version":4.4,"type":"Object","generator":"Object3D.toJSON"},"uuid":"0AFA4786-04BB-4CCF-9D50-320F2BFAB3E1","type":"PerspectiveCamera","matrix":[1,0,0,0,0,1,-6.123234262925839e-17,0,0,6.123234262925839e-17,1,0,2.842170943040401e-14,1.4210854715202004e-14,107.59237670898438,1],"zoom":1,"fov":80,"aspect":1.993781094527363,"near":0.0001,"far":10000}}"```

The renderer size is:
    {width: 1603, height: 804}

Here are two projection methods.

    var project1 = function (camera, mouse) {
        var that = this,
             origin = mouse.clone();
          origin.project(camera);
          var dir = origin.sub(camera.position).normalize();
          var distance = -camera.position.z / dir.z;
          return camera.position.clone().add(dir.multiplyScalar(distance));
    };

Here is an alternative implementation that I wrote not taking into account the camera's world matrix.

      var project2 = function (camera, mouse) {
         var origin = camera.position.clone();
         var ipv = new THREE.Matrix4().getInverse(camera.projectionMatrix);
         var vec4 = new THREE.Vector4(mouse.x, mouse.y, that.near, 1.0);
         var direction = vec4.applyMatrix4(ipv).normalize();
         var distance = -origin.z / direction.z;
         return origin.add(direction.multiplyScalar(distance));
      },

Here is the output from each project method:

    >> project1(new THREE.Vector3(-1, -1, 0.5))
    T…E.Vector3 {x: -177.89627226325572, y: -89.2255657900433, z: 0}

And

    >> project2(new THREE.Vector3(-1, -1, 0.5))
    T…E.Vector3 {x: -180.0000144290432, y: -90.28071766383289, z: -1.4210854715202004e-14}

I expect `project2` -- The y-axis will be slightly off because the initial placement of the camera uses the FOV and such to figure out how to best fit the *width* of the plane to the renderer window.

Is the aspect ratio and FOV playing a significant enough role in the world matrix to cause this much of an issue? I'd like to understand if this is a bug on my part or just a precision error exacerbated.

More notes
---------------

The error in the calculation does get smaller as I get closer to the z=0.

    project1(new THREE.Vector3(-1, -1, 0.5))
    T…E.Vector3 {x: -179.9978608098813, y: 88.0747075114069, z: 0}

and

    project2(new THREE.Vector3(-1, -1, 0.5))
    T…E.Vector3 {x: -180.00086447931378, y: 88.07331474524638, z: 0}

![Closer](http://i.imgur.com/TzA61SR.png)

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Try setting  your camera near plane to 1. It is dangerously small. Otherwise, please use stackoverflow.
