### ISSUE TITLE
CanvasRenderer and texture.onUpdate

### ISSUE THREAD

**Issue by coolfeature** [mrdoob/three.js#7628]
I might be wrong but from what I have seen CanvasRenderer does not call texture onUpdate callback. 

I am using a canvas element as a texture and I would like to fire a callback once the texture has been loaded, any pointers?

**Comment by mrdoob** [comment]
Can you create a jsfiddle?

**Comment by WestLangley** [comment]
@coolfeature 

Here is [a fiddle](http://jsfiddle.net/akmcv7Lh/) you can edit that runs the current version.

Here is [a fiddle](http://jsfiddle.net/hw9rcLL8/) that uses the dev branch.

**Comment by makc** [comment]
@WestLangley why not add these links to https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md

**Comment by WestLangley** [comment]
@makc done!

**Comment by coolfeature** [comment]
Is this not as simple as adding texture.onUpdate() in the right place in CanvasRenderer.js ?

I have tested locally with WebGLRenderer and everything works as expected. I pass a reference to a canvas in the constructor to Texture, set the onUpdate callback, do texture.needsUpdate = true in the callback and my renderer renders the results as soon as the canvas has been drawn on the texture.

BTW I am running r72.

**Comment by WestLangley** [comment]
Simplified your example: http://jsfiddle.net/ecxom0b5/3/

If you have further issues, please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by coolfeature** [comment]
Sorry but you have removed the lines which show where the error is, the whole point of this fiddle was to highlight where the error is:


 // this seems to have not effect
    texture.onUpdate = function() {alert("texture updated")};

Why did you do that?

**Comment by WestLangley** [comment]
Oh, sorry. I misread your issue. :/

You are saying that `WebGLRenderer `has this line

    if ( texture.onUpdate ) texture.onUpdate( texture );

and `CanvasRenderer` does not.

**Comment by makc** [comment]
and likely none of other renderers

**Comment by coolfeature** [comment]
yeah

**Comment by mrdoob** [comment]
Fixed. Thanks!

**Comment by makc** [comment]
What about SoftwareRenderer :)

**Comment by coolfeature** [comment]
emm, I do not think this works well... 

1) I can get the mesh to reflect the update only when I do texture.needsUpdate = true; from setTimeout() in the callback

2) And if I use the above method I end up in a callback loop ( but the textures on the mesh do update)

**Comment by mrdoob** [comment]
Updated fiddle: http://jsfiddle.net/ecxom0b5/4/

**Comment by coolfeature** [comment]
Why without the rotation the callback does not fire?

**Comment by coolfeature** [comment]
Right, I resolved my issues with:

                if ( texture.onUpdate ) {
                  texture.needsUpdate = false;
                  texture.onUpdate( texture );
                }

**Comment by mrdoob** [comment]
> Why without the rotation the callback does not fire? I mean, can we do sth about it?

The renderer doesn't update the texture unless it's needed (a visible polygon is using it).
