### ISSUE TITLE
createMaterial doesn't pass Reflectivity

### ISSUE THREAD

**Issue by evantron3000** [mrdoob/three.js#7632]
The Loader currently ignores any values listed for "reflectivity" in materials that would be loaded (from a JSON file for instance). With the most current build, the presence of a reflectivity value results in an error. I'm not sure if this is intentional or not as the current exporters don't seem to pass that info either. 

However, I know that it is possible to pass that value via python from Maya (pyMel has a getReflectivity() function built in). I don't use Blender, so I don't know if it's possible that way, but it doesn't seem too outrageous.

**Comment by mrdoob** [comment]
What's reflectivity? envMap intensity?
