### ISSUE TITLE
Feature Request: Get reflectivity from Phong Material. 

### ISSUE THREAD

**Issue by evantron3000** [mrdoob/three.js#7634]
would it be ok for the The Maya exporter (threeJsFileTranslator.py) to pass the reflectivity of a phong material?  There is a pymel function for it (getReflectivity) and I've tested that it works. 

    if isinstance(mat, nodetypes.Phong):
            result["reflectivity"] = mat.getReflectivity()
            result["colorSpecular"] = mat.getSpecularColor().rgb
            result["specularCoef"] = mat.getCosPower()
            if self.options["specularMaps"]:
                self._exportSpecularMap(result, mat)

The current Loader.createMaterial() doesn't look for reflectivity, but it also easily could. https://github.com/mrdoob/three.js/issues/7632

**Comment by mrdoob** [comment]
Sounds good to me. Do you mind doing a PR for it?

**Comment by mrdoob** [comment]
Thanks!
