### ISSUE TITLE
examples unit adjustment

### ISSUE THREAD

**Issue by GGAlanSmithee** [mrdoob/three.js#7636]
This issue is for tracking the conversion of sizes used in the examples (as discussed in #7609) and for me to ask questions about it :)

The work is going on here https://github.com/GGAlanSmithee/three.js/tree/examples-unit-adjustment. You can see how it's going in `track.txt` in the root.

I am trying to get the sizes of the geometries in the examples as close to reality as possible where 1 three.js unit = 1 meter (without breaking anything). In cases where the example does not map to reality (for example displays an arbitary cube), I try to get as close to 1 three.js unit as possible for consistency and to get users looking at the examples used to use three.js with those kind of scales.

I am a bit unsure about the cases where a model is loaded. Some of them are somewhat large (canvas_lights_pointlights for example) and not close to reality, should I scale them down then to try to get it as close to reality as possible or leave size as is when loaded?

I am only changing size / scale atm. I do not know if there needs to be further changes done to textures or renderer to take advantage of the new shader model? if so please tell me what (maybe should be another PR though). I would also appreciate if someone would give a quick look at the examples I've converted so far just to see that I'm not doing something crazy.

**Comment by GGAlanSmithee** [comment]
Btw, I'm just going through the examples top to bottom as they appear in the examples folder, since it's the easist way to do it and all example should be updated anyway (right?). I realize that it is the webgl example that actually needs to change, tell me if you want me to prioratize them for an initial PR.

**Comment by WestLangley** [comment]
It is not clear to me what this is all about. Can you explain?

You seem to be changing the size of the geometry in examples that have no real distance units to begin with.

**Comment by GGAlanSmithee** [comment]
My understanding was that we should use as close to real world sizes as possible for objects that has a real world representation (a car, a head etc) as talked about in #7609.

I also understood it that we should lower sizes used in general even for objects with no real world representation (a cube, lines etc) in order to stay consistent. 

I also understood it as larger geometries won't be lit properly with incomming changes. This is only true for webgl scenes using the affected lights, but there should be consistency in the examples to promote use of realistic scales?

ATM large sized geometry is used in all of the examples for no apperant reason. So I'm attempting to change it.

Maybe I missunderstood?

Ping @bhouston

**Comment by bhouston** [comment]
I support this.  Yeah, most examples should be made to have sizes less than a large room -- something is measured in meters, rather than 100s of meters.

I should clarify that things will be lit regardless of their sizes, but moving towards real-world units will lead to easier setups.  So this is more about convenience and consistency than correctness.

**Comment by mrdoob** [comment]
> I am a bit unsure about the cases where a model is loaded. Some of them are somewhat large (canvas_lights_pointlights for example) and not close to reality, should I scale them down then to try to get it as close to reality as possible or leave size as is when loaded?

I would scale the models down.

**Comment by GGAlanSmithee** [comment]
Is http://threejs.org/examples/#misc_animation_keys broken?

**Comment by mrdoob** [comment]
Yep...

**Comment by GGAlanSmithee** [comment]
OK.

I want to focus on converting the units in this issue / PR to be. Might be better if someone with a bit of insight in the animation API fixed this. If not, I can try when done with this.

**Comment by GGAlanSmithee** [comment]
examples/webgl_animation_blend.html also seems to be broken.. Lots of errors / warnings in the console and from what I can tell, the example isn't linked in index.html. has this example been made redundant or should it be fixed?

**Comment by bhouston** [comment]
You can just remove it. :)  I think I didn't mean to commit it...

https://github.com/mrdoob/three.js/commits/dev/examples/webgl_animation_blend.html

**Comment by bhouston** [comment]
> Is http://threejs.org/examples/#misc_animation_keys broken?

It is my fault I suspect because it is broken with my animation PR:

http://exocortex.github.io/three.js/examples/misc_animation_keys.html

  I'll have a look in the next 24 hrs.

**Comment by GGAlanSmithee** [comment]
@bhouston thanks, will do

**Comment by Mugen87** [comment]
When we have migrated to the new default (physically correct) lighting mode, the scale of certain examples was updated so SI units could be used for spot and point light intensity values. When I remember correctly, we did not state to migrate _all_ examples to the 1 world unit = 1 meter policy though. But it does make sense for demos with physically correct workflows.
