### ISSUE TITLE
un, reath, alk ! (this is not Klingon)

### ISSUE THREAD

**Issue by Fabrice3D** [mrdoob/three.js#7639]
THREE.MorphBlendMesh.prototype.autoCreateAnimations

porting working code from r71 to r73, I couldn't get MorphBlendMesh to work.
no error, no update.

and then found out that the patern eats up the anim key 

in my test case, anims keys are "Walk", "Run", Breath"

a simple trace in code:
var morph = geometry.morphTargets[ i ];
var chunks = morph.name.match( pattern );
console.log("--> morph: "+morph.name); --> Walk_001
console.log("--> chunks: "+chunks);  --> alk_001, alk,001

so if i do myMorphBlendMesh.playAnimation( "Walk" , 6);  --> fails
but if i do myMorphBlendMesh.playAnimation( "alk" , 6);  --> works...

Because the patern doesn't support caps.
var pattern = /([a-z]+)_?(\d+)/; <--- booo!
var pattern = /([a-z A-Z]+)_?(\d+)/; ---> yay!

**Comment by leitzler** [comment]
I'd suggest using /i instead if the match shouldn't be case sensitive. See #7641.
