### ISSUE TITLE
JSON : write and then read

### ISSUE THREAD

**Issue by sRcBh** [mrdoob/three.js#7640]
I have a database with my objects in JSON in order to load and save them. Th problem is that when I'm using the generated JSON code from blender I get:
```json
{
    "metadata": {
        "type": "Geometry",
        "version": 3,
        "generator": "io_three",
        "faces": 6,
        "normals": 8,
        "uvs": 0,
        "vertices": 8
    },
    "name": "CubeGeometry.1",
    "faces": [33,0,1,2,3,0,1,2,3,33,4,7,6,5,4,5,6,7,33,0,4,5,1,0,4,7,1,33,1,5,6,2,1,7,6,2,33,2,6,7,3,2,6,5,3,33,4,0,3,7,4,0,3,5],
    "normals": [0.577349,-0.577349,-0.577349,0.577349,-0.577349,0.577349,-0.577349,-0.577349,0.577349,-0.577349,-0.577349,-0.577349,0.577349,0.577349,-0.577349,-0.577349,0.577349,-0.577349,-0.577349,0.577349,0.577349,0.577349,0.577349,0.577349],
    "uvs": [],
    "vertices": [1,-1,-1,1,-1,1,-1,-1,1,-1,-1,-1,1,1,-1,0.999999,1,1,-1,1,1,-1,1,-1]
}
```

Which is good with JSONLoader.
But when I'm inserting my object in the database the JSON isn't good formatted:
```json
{
	"metadata": {
		"version": 4.4,
		"type": "Object",
		"generator": "Object3D.toJSON"
	},
	"geometries": [
		{
			"uuid": "0CAEDBFC-6AA1-476B-A4D0-CA5943A0267E",
			"type": "BoxGeometry",
			"width": 20,
			"height": 20,
			"depth": 20
		}],
	"materials": [
		{
			"uuid": "8B7F82C0-35D7-41F7-A277-629DE741C289",
			"type": "MeshStandardMaterial",
			"color": 16777215,
			"emissive": 0
		}],
	"object": {
		"uuid": "A1D195D4-E431-46CF-AC75-B1E0EE2439F3",
		"type": "Mesh",
		"name": "Cube",
		"castShadow": true,
		"receiveShadow": true,
		"matrix": [1,0,0,0,0,1,0,0,0,0,1,0,30.45830726623535,10,0,1],
		"geometry": "0CAEDBFC-6AA1-476B-A4D0-CA5943A0267E",
		"material": "8B7F82C0-35D7-41F7-A277-629DE741C289"
	}
}
```
So I'm able to insert them in the database, but not to add them to my scene.
Which gives me an error : 
**TypeError: vertices is undefined**
```zLength = vertices.length;	```
*JSONLoader.js (ligne 155, col. 4)*

**Comment by mrdoob** [comment]
What? Can you try explaining the issue again?

**Comment by sRcBh** [comment]
Yes, sorry if it isn't clear.
1. In my scene I'm creating an object (i.e. a red cube)
2. I'm inserting my object's JSON in my database 
3. Then I want to add this created object in my scene (i.e. by calling the JSON in my database).

But the problem is that I get an error "vertices is undefined". 
But when I'm calling JSON created by Blender, the object is correctly added to scene. And the JSON Format isn't the same (see above).
I hope it's more understandable for you :)

**Comment by mrdoob** [comment]
Can you provide a jsfiddle?
