### ISSUE TITLE
Publishing problem with editor using 73/dev latest code in chrome

### ISSUE THREAD

**Issue by Druidhawk** [mrdoob/three.js#7645]
[EDIT: the following may be due to using the dev editor, setting back to master seems to work better]

I have been attempting to use the editor for my game dev.  The dispatch mechanism in app is very useful.  

My problem is, over time, i lose the ability to publish, and extract the scene file to my game.  At one point the publish was creating an empty zip and I think a (cpzp <spelling ?> in the downloads folder.)  Now when i select publish, the menu entry highlights blue, but nothing is downloaded/generated.  Even File=>New empty scenes fail to publish.  This is under OSX.

Some diagnostic dialog when publishing problems occur would be nice.

Possibly relevant, is i periodically lose texture references and see this kind of output in the console

Navigated to http://localhost:8000/three73.js/editor/
three.min.js:632 THREE.WebGLRenderer 74dev
three.min.js:656 THREE.WebGLRenderer: Texture marked for update but image is incomplete T…E.Texture {uuid: "13190B54-0F99-456C-AB07-19E41B453811", name: "", sourceFile: "", image: img, mipmaps: Array[0]…}
Config.js:63 [12:55:06] Saved config to LocalStorage.
three.min.js:656 THREE.WebGLRenderer: Texture marked for update but image is incomplete T…E.Texture {uuid: "13190B54-0F99-456C-AB07-19E41B453811", name: "", sourceFile: "", image: img, mipmaps: Array[0]…}
Storage.js:73 [12:55:08] Saved state to IndexedDB. 275.36ms
Storage.js:73 [12:55:24] Saved state to IndexedDB. 364.03ms
Navigated to http://localhost:8000/three73.js/editor/
three.min.js:632 THREE.WebGLRenderer 74dev
Config.js:63 [12:55:38] Saved config to LocalStorage.
Storage.js:73 [12:55:40] Saved state to IndexedDB. 297.48ms

**Comment by mrdoob** [comment]
I updated the publish code just yesterday. Maybe you want to give r74dev a try?

**Comment by Druidhawk** [comment]
Excellent!!!  I will pl;ay with it this weekend.

On a side note, the editor dispatch system, with its init/start/update etc., is a really clever way to integrate editor with external source.  I threw out blocks of code in favor of this approach.

**Comment by mrdoob** [comment]
You mean the app.js stuff?

**Comment by Druidhawk** [comment]
yup, i embed an app.js in my game to handle scene loading and dispatching and place game specific calls in script entries in the editor.  

For example my game uses goblin physics,
I can edit an init() script entry for each mesh in editor for setting mass/initial velocities in game
I can edit a start() script entry for scene to run my physics webworker because all initialization has occurred
I can edit an update() script entry for scene to sync repositioning shapes based on physics results

**Comment by mrdoob** [comment]
Nice! Glad that others find it useful 😊
