### ISSUE TITLE
self in three.js is bound to the wrong Variable if "var self = this;" is used in the calling context

### ISSUE THREAD

**Issue by WulfP** [mrdoob/three.js#7648]
The call 
```
   var self = this;
   var delta = self.clock.getDelta();
```
fails.

`self` ist never declared in three.js.
Thus `self` in THREE.Clock.prototype.getDelta() is bound to the Variable `self` in the calling function instead of `window`. So `getDelta()` fails, because `self.performance` is not defined.

If I replace every occurance of `self.XXX` with `window.XXX` in three.js, everything works fine.

But besides of that thanks for the very good work in three.js!!!

**Comment by mrdoob** [comment]
Can you provide a jsfiddle?

**Comment by WulfP** [comment]
It took some time to find the right place...

In

    http://jsfiddle.net/suroorwijdan/kdeo4zd6/3/light/

add in Line 8

    self = {};

hit "Run" and the world stops turning.

Greetings from Berlin & have a nice weekend!



Am 20.11.2015 um 17:48 schrieb Mr.doob:
>
> Can you provide a jsfiddle?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrdoob/three.js/issues/7648#issuecomment-158456218>.
>

-- 
dangp dangling-pointer UG (haftungsbeschränkt) & Co. KG mit Sitz in Berlin
Registergericht: Amtsgericht Berlin-Charlottenburg, HRA 49956 B
Geschäftsführung: Carla Gabriel
USt-IdNr.: DE296554867

Persönlich haftender Gesellschafter: CWFC UG (haftungsbeschränkt) mit
Sitz in Berlin
Registergericht: Amtsgericht Berlin-Charlottenburg, HRB 160986 B
Geschäftsführung: Carla Gabriel

Anschrift:
Dunckerstraße 59B
10439 Berlin

E-Mail 	info@dangp.de
Tel. 	+49 (0)30 67962697
Fax 	+49 (0)30 67962698

**Comment by WulfP** [comment]
Ok, I found one place in my program, where I forgot the "var" to declare
self and thus changed window.self accidentally.
Maybe it´s not the best idea in JavaScript to use "var self = this;" to
expose the current context to sub-functions, but it´s very common.

So it´s not a bug in three.js, but it might be dangerous to rely on self
== window.self == window.

Regards

Wulf

Am 20.11.2015 um 17:48 schrieb Mr.doob:
>
> Can you provide a jsfiddle?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrdoob/three.js/issues/7648#issuecomment-158456218>.
>

-- 
dangp dangling-pointer UG (haftungsbeschränkt) & Co. KG mit Sitz in Berlin
Registergericht: Amtsgericht Berlin-Charlottenburg, HRA 49956 B
Geschäftsführung: Carla Gabriel
USt-IdNr.: DE296554867

Persönlich haftender Gesellschafter: CWFC UG (haftungsbeschränkt) mit
Sitz in Berlin
Registergericht: Amtsgericht Berlin-Charlottenburg, HRB 160986 B
Geschäftsführung: Carla Gabriel

Anschrift:
Dunckerstraße 59B
10439 Berlin

E-Mail 	info@dangp.de
Tel. 	+49 (0)30 67962697
Fax 	+49 (0)30 67962698

**Comment by mrdoob** [comment]
As far as I remember... we use self so the code can run on web workers.

**Comment by WulfP** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/self says
> The Window.self read-only property returns the window itself, 
But in fact, window.self ist NOT readonly. Maybe that´s the problem.

In WebWorkers `self`resolves to `WorkerGlobalScope.self`. Maybe it ist better to use `_this` instead of `self` to provide scope, because `self`ist ambigous.

In three.js I think, everything would (more safe..) work without `self` (including `requestAnimationFrame =  vendors[ x ] + 'RequestAnimationFrame'` `self.requestAnimationFrame = self[ vendors[ x ] + 'RequestAnimationFrame' ]`)

**Comment by mrdoob** [comment]
What parts of the code will need to be changed?

**Comment by WulfP** [comment]
All occurances of `self.` can be deleted cause they resolve to the appropriate context automatically.

The occurences of self[] can´t be replaced easily.
`eval("xxx")` works as a replacement for `self["xxx"]` but throws an exception if undefined.
So only
`try{var caf=eval(vendors[ x ] + 'CancelAnimationFrame' ] );} catch(e){var caf=null};
try{var craf=eval( vendors[ x ] + 'CancelRequestAnimationFrame');} catch(e){var craf=null};
cancelAnimationFrame = car||craf`
would work as a replacement for 
`cancelAnimationFrame = self[ vendors[ x ] + 'CancelAnimationFrame' ] || self[ vendors[ x ] + 'CancelRequestAnimationFrame' ];`

Line 15499 in function parse() works similar, but I think, 
`var typedArray = new eval( index.type )( index.array );`
...
var typedArray = new eval( attribute.type )( attribute.array );`
works here. 

But again: Your Code ist correct, MDN recommends to use `self` for Webworkers.
The only problem ist, that it´s in fact not read-only and can accidentially be overwritten.

Maybe it would be sufficant to throw an Exception if `self.THREE` ist undefined at the places where `self`is invoked to tell the programmer, that self is overwritten and thus three.js can´t work properly.

What do you think?

**Comment by mrdoob** [comment]
#7787
