### ISSUE TITLE
Request for contributors for creating 3D engine for Freeciv-web

### ISSUE THREAD

**Issue by andreasrosdal** [mrdoob/three.js#7654]
In order to create an open source 3D engine for [Freeciv](https://play.freeciv.org), we have created a [WebGL 3D engine competition](https://github.com/freeciv/freeciv-webgl-competition). So if you know WebGL and Three.js well, why not show off your skills and contribute your proposal for a technology prototype of a 3D engine for Freeciv. This involves rendering units, terrain and cities in a 3D world using WebGL. I would be interested in ideas about how an open source project like Freeciv could succeed in creating a nice 3D engine. Thanks in advance for helping this development effort for the Freeciv-web project!

**Comment by GGAlanSmithee** [comment]
I respect your wish to drive your game forward, but how is this a bug report or feature request? Also a competition need a prize, and besides that, nobody will be able to create a game engine capable of doing anything in three months.

**Comment by GGAlanSmithee** [comment]
To be a bit more construcrive: try www.html5gamedevs.com or www.gamedev.net.

**Comment by andreasrosdal** [comment]
Hi @GGAlanSmithee and thanks for the reply.

>I respect your wish to drive your game forward, but how is this a bug report or feature request? 

This isn't a bugreport, but this issue-tracker on Github was the closest thing to a forum for Three.js users that I could find. Feel free to close this issue after some time if you think it is inappropriate. 

>Also a competition need a prize, 

Possibly. Please note that the end-goal is to create an open source 3D engine for Freeciv. There are no resources to purchase physical prizes for. Do you have any suggestions?

> besides that, nobody will be able to create a game engine capable of doing anything in three months.

You might be right about that. How do you suggest it could be done otherwise? We don't need a complete solution, just a prototype to work more on later.

**Comment by mrdoob** [comment]
> This isn't a bugreport, but this issue-tracker on Github was the closest thing to a forum for Three.js users that I could find.

That's a good point... Maybe we should have a forum. I wouldn't want to maintain/admin myself though... 

I wonder if there is a forum service that uses github/twitter/facebook/google accounts to login?

**Comment by andreasrosdal** [comment]
Hi @mrdoob - yes, three.js should have a forum for the users.

Perhaps you want to collaborate on a 3D engine for Freeciv-web? You at the #1 person with knowledge of Three.js after all. :)

**Comment by mrdoob** [comment]
I probably should deal with the 78 pull requests and 449 open issues in this project before putting more food on my plate.

**Comment by GGAlanSmithee** [comment]
> You might be right about that. How do you suggest it could be done otherwise? We don't need a complete solution, just a prototype to work more on later.

I would start my own engine and try to get contributors. Focus the effort.

**Comment by GGAlanSmithee** [comment]
Or rather, I'd use an existing engine unless the engines itself was the end goal. You'd still be able to implement the ruleset of your game in a general purpose engine.

http://www.gamepix.com/blog/the-big-list-of-html5-3d-games-engines/

**Comment by GGAlanSmithee** [comment]
> I wonder if there is a forum service that uses github/twitter/facebook/google accounts to login?

I know of [slack](www.slack.com) which is more of a chat service, and [Discourse](https://github.com/discourse/discourse). I don't think either allows for authentication with your github account, but they are both used with success in other popular repos.

**Comment by mrdoob** [comment]
Discourse looks nice. But $100/month not so much...

**Comment by GGAlanSmithee** [comment]
Yeah.. It's free when selfhosted though.. Maybe could be embedded in threejs.org, but it seems some people have had problems embedding discourse on a gh-pages site. Slack is free even when they host it, might be a good start?

**Comment by mrdoob** [comment]
Slack is more like IRC and [we have IRC already](http://webchat.freenode.net/?channels=three.js).

**Comment by MasterJames** [comment]
I thought slack was an invite only system. Or is that just an option?

**Comment by GGAlanSmithee** [comment]
Yeah, if you have irc, slack is pretty redundant.

@MasterJames I haven't hosted a slack channel myself, but joined a few without being invited so I guess you can make them open.

**Comment by satori99** [comment]
@mrdoob 
>I wonder if there is a forum service that uses github/twitter/facebook/google accounts to login?

Google groups? 

Someone tried to get that happening a few years ago but it didn't fly.
https://groups.google.com/forum/#!forum/threejs

**Comment by zz85** [comment]
https://gitter.im integrates with github, but again it's more like IRC except that old messages when you were offline gets saved. It can sometimes get very noisy though.

Google groups could work though if more adopts it (perhaps by redirecting people to it)

**Comment by jiyinyiyong** [comment]
Thought you were talking about a forum, I would vote for Discourse since I [have run one](http://react-china.org/) for more than a year, the price is the Ubuntu server on DigitalOcean or Aliyun. And a forum helps a lot in gathering topics.
