### ISSUE TITLE
ColladaLoader2 hierarchy bug

### ISSUE THREAD

**Issue by revillo** [mrdoob/three.js#7656]
First of all, thanks for rewriting the Collada Loader, (examples/js/loaders/ColladaLoader2.js) but there's a problem with how it parses scenes. I've traced it to the use of xml.getElementsByTagName which searches recursively instead of only returning the top level child nodes. This means that all child nodes appear in to the top level under scene->children.

In my copy of ColladaLoader2, I've added the following fix to parseVisualScene
```javascript
for ( var i = 0; i < elements.length; i ++ ) {
      if (elements[i].parentElement.id != "Scene") continue;
	  data.children.push( parseNode( elements[ i ] ) )
}
```

But perhaps there are better solutions.

**Comment by mrdoob** [comment]
`getElementsByTagName()` is recursive? 😨

**Comment by mrdoob** [comment]
Fixed. Thanks!
