### ISSUE TITLE
When normalized vectors are almost parallel, their dot product may be greater than 1

### ISSUE THREAD

**Issue by blackslate** [mrdoob/three.js#7677]
# Steps to reproduce

var a = new THREE.Vector3(0.0015689768662075654, 0, -0.9999987691550393).normalize()
var b = new THREE.Vector3(0.0015689768538490866, 0, -0.9999987691550586).normalize()
a.dot(b)
1.0000000000000002

**Comment by leitzler** [comment]
This isn't a three.js issue, it's how Javascript works. Try out `0.1 + 0.2` and you will see that it gives you `0.30000000000000004`.

Short explanation: http://floating-point-gui.de/basic/
<b>Long</b> explanation: http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html :smile:

**Comment by blackslate** [comment]
It could be dealt with by using Math.max(1, a.dot(b)) in the three.js code

**Comment by leitzler** [comment]
Yes, that's probably what you want in your solution, but not in three.js since dot product isn't limited to be 0..1. It's just in your use case. Adding that to three.js would prevent this for example:
```javascript
var a = new THREE.Vector3(1,2,3);
var b = new THREE.Vector3(1,2,3);
a.dot(b); // 12
```

**Comment by WestLangley** [comment]
@blackslate How does this issue affect your application? What is your three.js use case?

**Comment by mrdoob** [comment]
> It could be dealt with by using Math.max(1, a.dot(b)) in the three.js code

It could be dealt in your code too...

**Comment by WestLangley** [comment]
>It could be dealt with by using Math.max(1, a.dot(b)) in the three.js code

YIkes. Then the zero-vector dotted with itself will be 1.

**Comment by blackslate** [comment]
@WestLangley - If you do `Math.acos(a.dot(b))`, where `a` and `b` are normalized vectors, and almost parallel, the result is `NaN`. To work around this, you can do `Math.acos(Math.max(-1, Math.min(1,  a.dot(b)))`

**Comment by WestLangley** [comment]
@blackslate Yes. That is why I inquired about your use case.

See, for example, the source code of `Vector3.angleTo( v )`.
