### ISSUE TITLE
Change in WebGLRenderTarget behavior?

### ISSUE THREAD

**Issue by DelvarWorld** [mrdoob/three.js#7680]
In r71, I was doing something like this:

    let target = new THREE.WebGLRenderTarget( 400, 400 );
    ...
    renderer.render( scene, camera, target );
    ...
    let frameBuffer = target.__webglFramebuffer;
    gl.bindFramebuffer( gl.FRAMEBUFFER, frameBuffer );
    gl.viewport( 0, 0, 400, 400 );
    gl.readPixels( 0, 0, 400, 400, gl.RGBA, gl.UNSIGNED_BYTE, array );

This let me capture a 400x400 screenshot of a canvas without upsetting the main render loop. However, it no longer seems like the height and width are being respected with r73. When I read the pixel data, the output of the render target has the old renderer size. This happens even if I do `render.setSize( 400, 400 )` before the render.

It also doesn't seem to be respecting my moving the camera before and after render. If I do something like:

    renderer.setSize( 400, 400 );
    renderer.render( scene, camera, target );
    renderer.setSize( oldWidth, oldHeight );

it renders the screenshot using oldWidth and oldHeight, not 400x400. I think something changed with the renderer or the render target but i'm having a hard time figuring out what based on the logs. Did something change with rendering from synchronous to asynchronous?

**Comment by DelvarWorld** [comment]
Also, calling `.render( scene, camera, target )` is visually updating my canvas with the image buffer. Is this expected? This behavior was also happening in r71

**Comment by WestLangley** [comment]
You are going behind the back of the renderer. Check out these methods.

    renderer.readRenderTargetPixels( ... );

    renderer.setRenderTarget( renderTarget ); // this method will accept null as an argument

**Comment by DelvarWorld** [comment]
@WestLangley you're a life saver
