### ISSUE TITLE
Duplicated Points

### ISSUE THREAD

**Issue by Milewski** [mrdoob/three.js#7683]
Hello guys, im facing a problem which im not sure if it`s a Bug on THREE.js or it`s really how Points works.. consider the following code:

```
var maxPoints = 10;
var group = new THREE.Group();

for (var i = 0; i < maxPoints; i++) {
  
  var x = Math.random();
  var y = Math.random();
  var z = Math.random();

  var geometry: new THREE.BufferGeometry(),
  var vertices: new Float32Array(maxPoints * 3),

  vertices[i * 3 + 0] = x;
  vertices[i * 3 + 1] = y;
  vertices[i * 3 + 2] = z;

  var attribute = new THREE.BufferAttribute(vertices, 3).setDynamic(true);
  geometry.addAttribute('position', attribute);

  geometry.setDrawRange(i, 1); 
// i only want to display one point if i dont set this i end up with 2 points, 
// 1 at a random position and one at the center (0,0,0) for all objects in the group

  group.add(new THREE.Points(geometry));

}

...
scene.add(group);

```

The Problem im facing is that by creating a Point using BufferGeometry i always end up with 2 points, one always at the center and another randomly positioned. so if i am to create 1000 points i end up with 2000, been 2000 centered at the coordinates (0,0,0). It`s not 2000 Instance of Points but 1000 instance with 2 dots each, which i dont know how to make it only draw one, 

i temporarily fixed it by setting drawRange, but i surely think it`s not the right way, as i end up with a array with lots and lots of 0 values for the bufferposition for each point..

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

If you are not certain it is a three.js bug, we prefer you first seek help on stackoverflow.
