### ISSUE TITLE
Feature request: Half-Space

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#7685]
Is a [Half-Space](https://en.wikipedia.org/wiki/Half-space_(geometry)) a useful addition to the three.js library?
It would not more then a `Three.Plane` (a point and a normal) with an additional flag (boolean) that tells us whether the space is in the direction or opposite direction of the normal.

It is common to use half spaces in boolean operations. For example to cut a sphere in half.

Or is an alternative already available?

**Comment by mrdoob** [comment]
We do have [THREE.Plane](https://github.com/mrdoob/three.js/blob/master/src/math/Plane.js) already.

**Comment by bhouston** [comment]
@Wilt, just use the plane's normal and always point it in the direction you want to keep.  That is generally the standard convention. :)

**Comment by Wilt** [comment]
@bhouston Thanks. I might do that.
