### ISSUE TITLE
BUG: Memory leak since r72+

### ISSUE THREAD

**Issue by NicolasRannou** [mrdoob/three.js#7688]
To reproduce, add a mesh to a scene, render the scene then remove the mesh from the scene.

There is an object not being garbage collected and also a string with the id of the mesh.

There might be more issues if you change the color of the mesh.

You can just check the test_memory which is leaking quite a bit:
http://threejs.org/examples/#webgl_test_memory

I'll submit a codepen to showcase a minimal example.

It only happens since r72

**Comment by NicolasRannou** [comment]
Here a demo (test_memory simplified)

// r73 - leaking
http://codepen.io/nicolasrannou/pen/bVPQqp/

**Comment by mrdoob** [comment]
Updated codepen using r74dev.
http://codepen.io/anon/pen/ojrmPq

Is the leak still there?

**Comment by leitzler** [comment]
Yep, it's the BufferGeomerty added when using `wireframe` that leaks.

I created a pull request that fixes the problem, but I'm not sure that this is the best way of doing this.
I left the check for .wireframe, but will the geometry ever have a wireframe attribute set?
Maybe that should be removed?

See #7700

**Comment by NicolasRannou** [comment]
Good catch! Thanks for looking into it!

**Comment by NicolasRannou** [comment]
Awesome - the codepen with r74dev doesn't leak anymore!
