### ISSUE TITLE
SpotLight should automatically update LightShadow camera in response to SpotLight parameter changes

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#7690]
The spotlight has a perspective camera-based shadow map that is setup here:

https://github.com/mrdoob/three.js/blob/master/src/lights/SpotLight.js#L22

Right now the camera for the LightShadow is not updated in response to the spot light properly from what I can tell.

- When the SpotLight.angle changes, we should adjust the FOV of the perspective camera appropriately.  This is the most obvious issue.
- When the SpotLight.distance of the camera changes to a non-zero value, we could adjust the far clipping plane of the perspective camera to match.  (PointLight also has this issue.)  I am not sure if this is as necessary as the SpotLight.angle misalignment with the PerspectiveCamera FOV.

It would be cool to automatically adjust the near clipping plane of the perspective camera as well, but I do not know what would be a good value -- lightRadius or some fraction of the distance?

**Comment by bhouston** [comment]
Example in the ThreeJS editor - wide angle spot light with a cut off shadow of a cube on the ground plane (I've highlighted the missing shadow in orange scribbles using my awesome art skills):

![image](https://cloud.githubusercontent.com/assets/588541/11446489/a30b2d98-9505-11e5-8c8c-ab1ad4bab99c.png)

**Comment by WestLangley** [comment]
Yes. The user has to do this to change the shadow camera FOV:

```javascript
spotLight.shadow.camera.fov = new_value;
spotLight.shadow.camera.updateProjectionMatrix();
```

So you make a good point. Should there be a relationship between `spotLight.angle` and `spotLight.shadow.camera.fov`?

I am not sure there should be since users may want the shadow map to be tight around the target, while the spotLight illuminates the larger scene.

**Comment by bhouston** [comment]
> I am not sure there should be since users may want the shadow map to be tight around the target, while the spotLight illuminates the larger scene.

Other tools just do it automatically, like Unity3D -- there shadows are incredibly automated and easy to use.  I think also ThreeJS's focus on making things easy fits with doing this automatically.

**Comment by bhouston** [comment]
I do not believe UE4 allows you to set the shadow map angle either...

https://docs.unrealengine.com/latest/INT/Engine/Rendering/LightingAndShadows/LightTypes/Spot/index.html

**Comment by WestLangley** [comment]
>  I think also ThreeJS's focus on making things easy fits with doing this automatically.

Another good point. : - )

**Comment by mrdoob** [comment]
Agreed!

**Comment by WestLangley** [comment]
The hardwired coupling of spotLight and shadow camera would look like this:
```javascript
spotLight.shadow.camera.fov = THREE.Math.radToDeg( 2 * spotLight.angle );
spotLight.shadow.camera.far = spotLight.distance; // but only if distance is non-zero
```
I am not sure how one would handle `spotLight.shadow.camera.near`. The shadow frustum should be tight around the target  in width and depth.

This may result is pixelated shadows if the spotlight is not focused (has a larger angle). Pesonally, I am inclined to think this change is overly restrictive, but the trade-off is up to you.

For `DirectionalLight`, there is no `fov`; instead, `dirLight.shadow.camera.left/right/top/bottom` must be set by the user.

**Comment by MasterJames** [comment]
How about this kind of solution to this.
https://github.com/mrdoob/three.js/compare/dev...MasterJames:patch-5

**Comment by WestLangley** [comment]
As I said above, I think a common user requirement is to have the shadow frustum tight around the target for better-quality shadows at lower cost. So I think decoupling `spotLight.angle` and `spotLight.shadow.camera.fov`, as we do now, is the preferable option. But I understand the counter-argument.

**Comment by bhouston** [comment]
> As I said above, I think a common user requirement is to have the shadow frustum tight around the target for better-quality shadows at lower cost.

That isn't the typical case.  Generally users do not want to tweak a lot of parameters, they just want it to work right.  Unity and Unreal Engine do not fit their shadow maps to the objects in their frustrums, in part because it is hard to do automatically and annoying to do it manually unless you have a single light - single target and a single scene.  Generally the case is lots of lights, lots of targets and lots of scenes -- and you just want it to work once you've set up your lights.

This is why we have cascading shadow maps and what not, because they look good up close and fast away, otherwise one could just do a ton of tweaking, but that is tedious and not realistic as one scales up production.

**Comment by MasterJames** [comment]
Its confusing without it and makes it look broken as I initially thought stumbling upon the issue, but if you want to turn automatic coupling off simple set the control flag to false. [Note: Using the "not equal false" approach avoids the need to set a default to true.

I definitely like the pre-baking effects of radianToDegreesFactor in the existing radToDeg function (state wrapped function call or whatever it's technically called) and will change it to use that as requested but you're doing all kinds of math repeatedly (more so without backing it). It simple isn't needed to multiply by 2 first and fetching through a call stack. Just to divide by 114.6 seems visually intuitive and explicit for human comprehension by from an execution call stack performance perspective? not so smart. It's a minor preference. My feelings are the API user needs to know about how to turn it off (good & verbose docs explaining it) but don't need to worry about how comprehensible the conversion math is. Once you know what 114 .6 does your good going forward forever, a comment saying //radToDeg is probably enough of a hint/reminder (at least for me). So I just wanted to voice the opinion no real reason to enforce my preference I just want the idea mentioned and maybe acknowledged really.

**Comment by MasterJames** [comment]
Recommend fixes patches updated
THREE.Math.radToDeg and autoShadow for disable flag

Should we do one for distance and far (as your comment above suggests) and/or anything else like 'near' too?

**Comment by bhouston** [comment]
> Should we do one for distance and far (as your comment above suggests) and/or anything else like 'near' too?

Do them as separate commits to make it easier to get accepted.  I am not the one that decides what is accepted as a PR or not.

> I definitely like the pre-baking effects of radianToDegreesFactor in the existing radToDeg function (state wrapped function call or whatever it's technically called)

Closure.  The compiler should inline the functions anyhow though, so it shouldn't be that slow, it should just be a multiply.  If we wanted we could replace those computed variables (stored in the closure) with hard coded numbers and remove the closures.  I think that is an easy win. :)  I'd do that as a separate PR.  Not sure that matters for large scale performance though, I think it isn't a hot spot.

**Comment by MasterJames** [comment]
@WestLangley do you thinking adding a way to say what items need coverage and a function for computing tight shadows is desirable and worth doing? 
@bhouston thanks for the words of wisdom I will follow up on those thoughts shortly. My thought is its not important but as much as i appreciate the closure style there its worth creating the separate PR/patch for it anyway.

**Comment by MasterJames** [comment]
How about autoFov instead of autoShadow and I guess autoDistance ? I'll try that instead.

**Comment by MasterJames** [comment]
distance doesn't need to be re-calculated, so maybe autoShadow is fine.

**Comment by WestLangley** [comment]
>@WestLangley do you thinking adding a way to say what items need coverage and a function for computing tight shadows is desirable and worth doing? 

I don't think so -- sounds like application layer to me.

**Comment by mrdoob** [comment]
How about we build new objects on top of `THREE.LightShadow`?

Say...

`THREE.DirectionalLightShadow` and `THREE.SpotLightShadow`. If these objects are being used, then the renderer will build the shadow matrices using the light information. One could override that by replacing it with a `THREE.LightShadow` and create their custom matrix.

How does that sound?

**Comment by MasterJames** [comment]
It's a good idea to suggest. 
I also considered a special setter getter for angle maybe...
autoAngle = radNumber
Then it would do the compute of Shadows etc too. Instead of a flag to disable it.
For now it's a minor change so the added complexity new LightShadow classes adds seems more then needed.
I'll think some more on this and try to draw up a patch as you say to see and explore. 
More feedback from others would be good. If you're confidence on making that call less of a suggestion changes let me know, thanks.

**Comment by mrdoob** [comment]
Yeah. I guess it's less of a suggestion. I see it as a way of moving forward while leaving the option for people to create their custom shadow.

**Comment by MasterJames** [comment]
Okay I think I'm following. I'll make an attempt at it.

**Comment by MasterJames** [comment]
Initially I thought this was not possible because you really have to monitor the SpotLight's angle and then change the shadow's camera's fov. This version uses a SubClass of LightShadow to inject the changes to the owner's (aka SpotLight) 'angle' property.

https://github.com/MasterJames/three.js/pull/1/files

**Comment by mrdoob** [comment]
Hmm, I don't think you need to pass the lightShadow to the light. I think I'll give it a go 😁

**Comment by mrdoob** [comment]
There you go! 😊

**Comment by MasterJames** [comment]
Ya okay I thought to allow override or customization of the LightShadow you could pass the class in with the constructor.
Defering to the render function was an awesome way to get the light back into the shadow unlike my 'owner' hack.
So in the render function might not be the most performant place to update, so it is maybe a good suggestion to only update when needed somehow or only when adjusting the angle? 
I can see its also easy to customize if needed this way.

**Comment by mrdoob** [comment]
Right now update only computes the projectionMatrix if the values are different.

https://github.com/mrdoob/three.js/blob/dev/src/lights/SpotLightShadow.js#L23

**Comment by MasterJames** [comment]
Ya okay I see that now, thanks for pointing that line out.
All said and done it's a clean way, with future expansion possible.
Even if just setting fov when 'angle' is changed would have made things a few cycles faster.

So much better now it's pre-computed thanks for seeing a solution through!
