### ISSUE TITLE
Chrome marks published zip in editor as malicious

### ISSUE THREAD

**Issue by konsumer** [mrdoob/three.js#7696]
When I click "Publish" in the editor, the link is marked malicious, so I have to go into downloads and allow it. I think this is caused by it being a data-url. On the JSZip website, they use [something else](https://github.com/Stuk/jszip/blob/master/vendor/FileSaver.js) to save the file, and it doesn't cause a warning.

**Comment by mrdoob** [comment]
Yes. This has been fixed in the `dev` branch already 😊

**Comment by konsumer** [comment]
sweet! thanks.
