### ISSUE TITLE
Pretending this works for mobile

### ISSUE THREAD

**Issue by jimmykrinkles** [mrdoob/three.js#7697]
It would be super helpful if you guys stopped pretending that three.js works well for mobile, you javascript junkies are morons and don't have a clue just how bad this three.js stuff is for mobile. Fix the docs, stop promoting this bs for mobile, learn to code in C or GTFO. Thanks for playing.

**Comment by MasterJames** [comment]
I heard the same feedback when I said Javascript via phonegap/Cordova wold one day be able to perform as well as native. People laughed. Now? It's accepted.
I have more optimism but it would be great to sort out a stable version 1.0 where the broken examples don't tell a different story. I might we adaption of WebGL 2.0 in mobile browsers (Firefox is the first). It's not for everyone but it will be used by many in my future. I think maybe you should help. Where would you suggest we/you start to make it better for you?
Everybody here knows or has known C varients for 10-30 years and still they prefer JS. 
Anyway please stick to the forum guidlines and point to problems/suggestions or preferably solutions or this will be closed. Thanks for your feedback just the same. 
Really you'really saying you'd like a stable version where all the examples work on mobile?

**Comment by titansoftime** [comment]
It works pretty well on my tablet.
