### ISSUE TITLE
unexpected materialIndex offset in PolyhedronGeometry

### ISSUE THREAD

**Issue by kishalmi** [mrdoob/three.js#7698]
resulting in problems when creating multimaterial meshes from primitives
e.g. a geometry with faces having materialindices of 1-Nfaces

 also affected are all geometries that extend Polyhedron:
- DodecahedronGeometry
- IcosahedronGeometry
- OctahedronGeometry
- TetrahedronGeometry

PolyhedronGeometry.js:41

``` javascript
 faces[ j ] = new THREE.Face3( v1.index, v2.index, v3.index, [ v1.clone(), v2.clone(), v3.clone() ], undefined, j );
```

^ face index (j) as material offset.. that is rather suspicious =)

**Comment by kishalmi** [comment]
```diff
diff --git a/src/extras/geometries/PolyhedronGeometry.js b/src/extras/geometries/PolyhedronGeometry.js
index 209ac9d..9c32799 100644
--- a/src/extras/geometries/PolyhedronGeometry.js
+++ b/src/extras/geometries/PolyhedronGeometry.js
@@ -38,7 +38,7 @@ THREE.PolyhedronGeometry = function ( vertices, indices, radius, detail ) {
                var v2 = p[ indices[ i + 1 ] ];
                var v3 = p[ indices[ i + 2 ] ];
 
-               faces[ j ] = new THREE.Face3( v1.index, v2.index, v3.index, [ v1.clone(), v2.clone(), v3.clone() ], undefined, j );
+               faces[ j ] = new THREE.Face3( v1.index, v2.index, v3.index, [ v1.clone(), v2.clone(), v3.clone() ] );
 
        }
```

**Comment by mrdoob** [comment]
I think the idea was to have a unique material per face. Whether that's a good idea or not...

**Comment by kishalmi** [comment]
I get the idea and would suggest that - unless it's intentionally done by the user - it's a bad one.

```javascript
	var geo = new THREE.BoxGeometry(1, 1, 1);
	geo.merge(new THREE.BoxGeometry(2, 2, 2), undefined, 1);
	scene.add(new THREE.Mesh(
		geo,
		new THREE.MeshFaceMaterial([
			new THREE.MeshBasicMaterial({color: 0xFFFF00}),
			new THREE.MeshBasicMaterial({color: 0xFF00FF})
		])
	));
```
don't agree with this merely being an enhancement 
as long as the above code produces errors
while this one doesn't
```javascript
	var geo = new THREE.SphereGeometry(1);
	geo.merge(new THREE.SphereGeometry(2),undefined,1);
	scene.add(new THREE.Mesh(
		geo,
		new THREE.MeshFaceMaterial([
			new THREE.MeshBasicMaterial({color: 0xFFFF00}),
			new THREE.MeshBasicMaterial({color: 0xFF00FF})
		])
	));
```
that's just confusing and inconsistent at least.

**Comment by kishalmi** [comment]
after reading issue #6571 which lead to commit https://github.com/mrdoob/three.js/commit/1eebaf255d90fa75d84891261eb3062355f50465
I understand that the reason for this (one materialIndex / face) is that BoxGeometry has it now.
but why, and even default?

**Comment by Mugen87** [comment]
Material indices have been removed from `PolyhedronGeometry`/`PolyhedronBufferGeometry`, see https://github.com/mrdoob/three.js/pull/9111#issuecomment-225068280
