### ISSUE TITLE
Dev branch examples

### ISSUE THREAD

**Issue by benaadams** [mrdoob/three.js#7699]
Examples are master/release at http://threejs.org/examples/ which is good.

However it would also be useful to have the current dev build available in the same way; perhaps at dev.threejs.org? 

Maybe I'm just being lazy...

**Comment by GGAlanSmithee** [comment]
This would be awesome for #7636

**Comment by leitzler** [comment]
Good idea

**Comment by gero3** [comment]
Sorry It took me a long time to refactor some parts of cI.threejs.org  I'll release a version that also contains the dev branch.

**Comment by benaadams** [comment]
@gero3 yes, http://ci.threejs.org/pullrequests.html is excellent too :+1: had a feeling there was something related; but couldn't find any links..

**Comment by gero3** [comment]
Threejsworker now adds support for the dev branch:
http://ci.threejs.org/api/branch/dev/examples/index.html

**Comment by benaadams** [comment]
Excellent :+1: 

Perhaps a link on the front page?

Examples — Documentation — Migrating — Help — (Dev branch [Examples](http://ci.threejs.org/api/branch/dev/examples/index.html))

Or too confusing?

**Comment by GGAlanSmithee** [comment]
@benaadams if you were to add that, I would suggest something less "git-ish" like:

Examples — Documentation — Migrating — Help — (\<Next version\> Examples)

where \<Next version\> is the version the dev branch points too (captain obvious strikes again :) )

**Comment by benaadams** [comment]
@GGAlanSmithee something like https://github.com/mrdoob/three.js/pull/7763

[Examples (Release r73)](http://threejs.org/examples/) — [Documentation](http://threejs.org/docs/) — [Migrating](https://github.com/mrdoob/three.js/wiki/Migration) — [Help](http://stackoverflow.com/questions/tagged/three.js) — [Examples (Dev r74)](http://ci.threejs.org/api/branch/dev/examples/index.html)

**Comment by GGAlanSmithee** [comment]
@benaadams :+1:

**Comment by benaadams** [comment]
Updated to that.

**Comment by paulmasson** [comment]
How often are the dev branch examples updated? This one in particular is not:

http://ci.threejs.org/api/branch/dev/examples/index.html#webgl_multiple_elements

Thanks!

**Comment by WestLangley** [comment]
@paulmasson  Threejsworker does not appear to be auto-updating the pull requests or the dev examples.

/ping @gero3

**Comment by gero3** [comment]
Sorry I need to rework it to make it more stable

**Comment by paulmasson** [comment]
@benaadams FYI all of the dev examples are available here:
https://rawgit.com/mrdoob/three.js/dev/examples/

**Comment by WestLangley** [comment]
@paulmasson Do the rawgit examples work for you?

**Comment by paulmasson** [comment]
@WestLangley yes they do!

**Comment by MasterJames** [comment]
On my note 3 (Android version 5) the obj with material is black but with spec and looks the same as loader with just obj 
https://rawgit.com/mrdoob/three.js/dev/examples/#webgl_loader_obj_mtl

**Comment by looeee** [comment]
@mrdoob this is solved by the https://rawgit.com/mrdoob/three.js/dev/examples/ link

Do you still think a link to that needs to be added somewhere? I think that adding it to the main site without explanation would just confuse the majority of non-developer users, but maybe a link in the wiki?

**Comment by mrdoob** [comment]
@looeee sounds good!
