### ISSUE TITLE
Mesh with vertexShader doesn't cast shadows

### ISSUE THREAD

**Issue by sasha240100** [mrdoob/three.js#7701]
I have terrain generated by vertexShader .
And the problem is that it only recieve shadow, but can't cast it.
Version of three.js is latest (r74)
Example: http://192.241.128.187/current/examples/fps.html
I tried everything but it still doesn't work.

Shader: https://github.com/sasha240100/WhitestormJS/blob/master/src/Shaders/ShaderTerrain.js
<img width="960" alt="example" src="https://cloud.githubusercontent.com/assets/7657429/11459652/23731e7a-96e4-11e5-88c7-6ef222922a12.png">

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
