### ISSUE TITLE
Missing parameters in Json import for materials

### ISSUE THREAD

**Issue by linkedz** [mrdoob/three.js#7704]
Those parameters are missing in json parse:
-roughness
-metalness
-envMapIntensity
-roughnessMap
-metalnessMap
-shading type handling for MeshStandardMaterial

probably envMap also can be included in some way.

**Comment by mrdoob** [comment]
How are you exporting that? I would like to get rid of the `JSONLoader` soon (and use `ObjectLoader`/`MaterialLoader` instead).

**Comment by linkedz** [comment]
1. I used "ThreeJSAnimationExporter.ms" script for 3dMax with some custom edits after.
2. There is no field 'envMapIntensity' in 'MaterialLoader.parse()' 
3. As I've checked - there is no option to add custom image loader/parse (ex. DDSLoader) to ObjectLoader flow. Or maybe I'm wrong?

**Comment by mrdoob** [comment]
> There is no field 'envMapIntensity' in 'MaterialLoader.parse()'

Seems like we have a conflict... `material.reflectivity` (`MeshPhongMaterial`) and `material.envMapIntensity` (`MeshStandardMaterial`)...

@WestLangley should I rename `materialreflectivity` to `material.envMapIntensity`?

> As I've checked - there is no option to add custom image loader/parse (ex. DDSLoader) to ObjectLoader flow. Or maybe I'm wrong?

Yes, I need to figure out how to add that.

> ObjectLoader is using JSONLoader to parse custom geometry. Will it be merged into ObjectLoader after removal?

Yep! `LegacyGeometryLoader` or something...

**Comment by WestLangley** [comment]
>@WestLangley should I rename material.reflectivity to material.envMapIntensity?

To review, when we created `MeshStandardMaterial` we treated the environment map as a source of light, so the light's effect is purely _additive_, and `envMapIntensity` was created to modulate the intensity of the light source.

Also, in the original `MeshStandardMaterial` there was a `reflectivity` parameter that was subsequently removed for simplicity. That parameter modulated the specular reflectance of the material for non-metals only -- in other words, how reflective non-metals are. I expect @bhouston wants to reintroduce `reflectivity` into the future `MeshPhysicalMaterial`.

Now regarding `MeshPhongMaterial`, the way we handle environment maps in that case is quite different, and was not changed. We have a `combine` parameter that specifies how the color of the material and the color of the envMap are to be blended. This is not physical. 

```glsl
#ifdef ENVMAP_BLENDING_MULTIPLY

	outgoingLight = mix( outgoingLight, outgoingLight * envColor.xyz, specularStrength * reflectivity );

#elif defined( ENVMAP_BLENDING_MIX )

	outgoingLight = mix( outgoingLight, envColor.xyz, specularStrength * reflectivity );

#elif defined( ENVMAP_BLENDING_ADD )

	outgoingLight += envColor.xyz * specularStrength * reflectivity;

#endif
```

`specularStrength ` is 1 if there is no `specularMap`.

`reflectivity` should be a quantity between 0 and 1 in the first 2 cases. Plus, it is a property of the material.

`envMapIntenstiy` is any positive number, and is really a property of the map -- not the material.

---

All that being said, I am thinking that some changes are in order...

1. `envMapIntenstiy` should be a property of the environment map. So all materials that use the same environment map are illuminated the same.
2. `reflectivity` should remain a property of Phong, Lambert, Basic.
3. Eventually, `envMap` should be removed from at least `MeshStandardMaterial` in favor of a new `LightProbe` light source. In that case, what we would call a "distant light probe" replaces the environment map, and "light probe intensity" replaces `envMapIntensity`.
4. And in a related issue, whether a material is reflective or refractive should be decoupled from the format of the environment map.

/ping @bhouston

**Comment by bhouston** [comment]
Environment should be turned into the type LightProbe as I've already sort of designed it to be that way in the shaders.  Anything else is an intermediate solution and it is sort of hackish so it is very debatable on what is right.

I do not believe we need it to be a "distant light probe", just have it be a single light probe situated at 0,0,0.  If there is only one light probe, it acts as a distant light probe in effect with no changes if we do not interpolation on it.

**Comment by WestLangley** [comment]
@bhouston So to clarify, do you agree that `material.envMap` and `material.envMapIntensity` should be removed from `MeshStandardMaterial` at some point in favor of adding a `lightProbe` to the scene as a new light type? Light probes would have a `map` property and an `intensity` property.

If so, we could leave Phong, Lambert, and Basic as is -- or change them, too.

@mrdoob No, I would not rename `reflectivity` to `envMapIntensity`.

**Comment by mrdoob** [comment]
> @mrdoob No, I would not rename `reflectivity` to `envMapIntensity`.

Oks!

**Comment by Mugen87** [comment]
Closing. `JSONLoader` has been removed with #15310 and `ObjectLoader` should correctly parse now the mentioned material properties.

BTW: `ThreeJSAnimationExporter.ms` has been removed for a while now. For 3dMax users it might be best to export to `FBX` and then possibly convert to `glTF`.
