### ISSUE TITLE
CSS3DStereoRenderer doesn't support Z rotation

### ISSUE THREAD

**Issue by grantbi** [mrdoob/three.js#7705]
I was using CSS3DStereoRenderer to match VRControl's camera control for VR with WebGL. It doesn't seem to match when you rotate the camera axis like the WebGL (StereoEffect.js class) does.

It would be nice if someone could implement this rotation so they can be in sync.

**Comment by mrdoob** [comment]
Could you provide a jsfiddle?

**Comment by grantbi** [comment]
I couldn't get jsfiddle to work right with the viewports. An example can be found here:
http://jeo-ex.on.14four.com/

It looks like the WebGL renderer supports 3DOF vs the CSS one that is only 1DOF
https://www.google.com/design/spec-vr/designing-for-google-cardboard/physiological-considerations.html#physiological-considerations-head-tracking

It may just be a controls thing and I'm doing it wrong. :)

**Comment by mrdoob** [comment]
Hmm... Confirmed.

**Comment by WestLangley** [comment]
Sorry, I have no idea what this issue is about.

**Comment by mrdoob** [comment]
Actually, is my fault 😜

**Comment by mrdoob** [comment]
Fixed!

**Comment by jeromeetienne** [comment]
thanks!
