### ISSUE TITLE
Update all light APIs to accept THREE.Color, not hex

### ISSUE THREAD

**Issue by AndrewRayCode** [mrdoob/three.js#7707]
The current light API takes a hex for the light's constructor:

http://threejs.org/docs/#Reference/Lights/AmbientLight

```
AmbientLight( hex )
hex — Numeric value of the RGB component of the color.
```

This is confusing. [Internally, the value is cast to a `THREE.Color` anyway](https://github.com/mrdoob/three.js/blob/master/src/lights/Light.js#L12). It's inconsistent to have a `Color` data type but then only accept `hex` for things that actually use `Color`. It also means that if a user already has a `THREE.Color`, they have to convert it to a hex to create a light, which will then get converted back to a `Color`.

Also, by coincidence, if you pass a `Color` to the `new THREE.Color()` constructor, [it's auto-copied anyway](https://github.com/mrdoob/three.js/blob/master/src/math/Color.js#L27), so you can pass `Color`s to lights and it looks like it will work accidentally, which also seems bad.

I think that the documentation and API should be changed for all lights to accept a `Color`. For backwards compatibility, a simple `if( !( arg instanceof THREE.Color ) )` then convert to color and log a warning about deprecation. One point of concern might be the to/from json API. `toJSON` looks fine [since it calls `.toHex`](https://github.com/mrdoob/three.js/blob/master/src/lights/Light.js#L99) but I don't know how things like the three editor de-serialize lights.

I'm happy to work on this change if it would be accepted.

**Comment by WestLangley** [comment]
This pattern is already supported:
```javascript
scene.add( new THREE.AmbientLight( new THREE.Color( 0x222222 ), 1 ) );
```
As are other color formats.

Perhaps just the docs need to be corrected.

**Comment by DelvarWorld** [comment]
@WestLangley as mentioned this only works by coincidence. The source code argument is still named `hex` and the code path behaves as if it's a hex value.

**Comment by WestLangley** [comment]
Could you identify the source code you are referring to?

**Comment by bhouston** [comment]
I support renaming hex to color in the light classes/docs and ensuring colors are the primary parameter to specifying light color.

**Comment by DelvarWorld** [comment]
@WestLangley whoops I confused the docs with source in my head. It used to be hex also: https://github.com/mrdoob/three.js/commit/1e47bb43b5b7382cf06e982cd3fe41d79d7ec595

so maybe it is just a doc thing. I don't know if it's intentional that the light color is copied into a new color (which is why a hex value would still accidentally work).

**Comment by WestLangley** [comment]
All color formats are currently acceptable -- including a `THREE.Color` instance. Only the docs are out-of-date.

I do not think we want to _require_ the user to instantiate a `Three.Color` object just to specify a color arg to a constructor.

**Comment by looeee** [comment]
@WestLangley the docs now consistently say to use hex colors for lights. Only the main Color page explains the other possibilities - and I added a note there that the standard method of specifying color in Three is a hex triplet.
