### ISSUE TITLE
Docs in dev: Links to examples: Many ( All? ) deadlinks

### ISSUE THREAD

**Issue by theo-armour** [mrdoob/three.js#7715]
A number of the doc API references have links to the Three.js examples.

All the ones I have tested have been broken. Example to shapes:

http://mrdoob.github.io/examples/#webgl_geometry_shapes

You will note that the link is missing 'three.js/'.

I would like to fix this myself but it would take me a number of hours to get up to speed with the docs script.

If somebody can fix this issue easily then please so.

Sorry if this has been posted elsewhere. I did try searching but did not find anything similar.

**Comment by mrdoob** [comment]
Oh, it's because the links expect to be sitting in `http://threejs.org/docs/` and not `http://mrdoob.github.io/three.js/docs/`.

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/blob/dev/docs/page.js#L38

Maybe we should remove `[example:]` and use `[link:]` instead:

https://github.com/mrdoob/three.js/blob/dev/docs/api/cameras/Camera.html#L64

**Comment by theo-armour** [comment]
> Maybe we should remove [example:] and use [link:] instead:

I tried that, but then all the links in the API files that use [example:] are broken.

What about changing https://github.com/mrdoob/three.js/blob/dev/docs/page.js#L38 over to

    	text = text.replace(/\[example:([\w\_]+) ([\w\:\/\.\-\_ \s]+)\]/gi, "<a href=\"../../three.js/examples/#$1\"  target=\"_blank\">$2</a>" ); // [example:name title]

Unfortunately, I can't test this on my Windows machine, because without an `index.html` the link just display a directory listing.

**Comment by mrdoob** [comment]
Wait, maybe the reason this doesn't work is because the recently added `<base href="../../" />`? https://github.com/mrdoob/three.js/blob/dev/docs/api/cameras/Camera.html#L5

**Comment by mrdoob** [comment]
Fixed! Thanks!
