### ISSUE TITLE
Geometry.computeFaceNormals() using a different geometry

### ISSUE THREAD

**Issue by laurasubias** [mrdoob/three.js#7720]
I call: geometry.computeFaceNormals(), where geometry is an instance o THREE.Geometry and has 4900 faces, and it throws the following error:

![image](https://cloud.githubusercontent.com/assets/7937143/11538580/d9144be2-9922-11e5-81bf-68658d2b602a.png)

I've put a break point in computeFaceNormals and the strange thing is that inside this function "this" is a CylinderGeometry with 15 faces, instead of my geometry (Geometry with 4900 faces).

![image](https://cloud.githubusercontent.com/assets/7937143/11538630/1d2ab6b8-9923-11e5-9b0e-5a6f35f1f57c.png)

I am using r73 in Chrome.

Any help is welcome.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
