### ISSUE TITLE
lines demo is broken

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#7722]
firefox, el capitan, http://threejs.org/examples/webgl_lines_colors.html is broken, whilst http://threejs.org/examples/webgl_lines_dashed.html works fine.
![screen shot 2015-12-03 at 1 33 51](https://cloud.githubusercontent.com/assets/242577/11548570/23a0010c-995e-11e5-8825-aa713f7065ba.png)

**Comment by mrdoob** [comment]
Firefox/Yosemite works fine here...

**Comment by makc** [comment]
Maybe it's nightly thing. Chrome is fine.

**Comment by mrdoob** [comment]
Oh! Firefox Nightly?

**Comment by leitzler** [comment]
FF42.0 / El Capitan is ok
Safari 9.0.1 too.

**Comment by mrdoob** [comment]
Sounds like you should report to Mozilla instead...
