### ISSUE TITLE
Versioning !

### ISSUE THREAD

**Issue by verteAzur** [mrdoob/three.js#7726]
Hello,

I have been integrating THREE.js for now 3 years. I must let you know of an important issue. The library is a great success from all aspects except one : it is a versioning hell !  To give you an example, on v71, I have spend countless hours migrating to the new skinning library. Today, I've thrown away all that hard work and spent more time to re-integrate the new skinning (animation) libs  with v73 . The lib seems a little heavy for I need to do, but it is working for now and I look forward to use the new weight functionality. Anyways, the heavy code is not the issue. The issue is now that I have completed the skinning migration, i am entering the loader issue... The loader issue is done, now I have the shader issue with the Buffer geometry issue. What? No documentation, no help online? What can we do from a developer stand point to overcome that migration problem? I am sure it is very difficult for you to integrate the changes into the numerous examples and the provided docs.   But, think about the people that try to migrate to the latest code on a whole application ! After the shaders, I have the particule library and so on... I have days worth of code that become garbage overnight, because of an interface change. I understand that this problem should happen at start, but now the lib is 5 years old. Can we do something about it?

Thanx,
JFSG

**Comment by makc** [comment]
> What can we do from a developer stand point to overcome that migration problem?

you can do the PR with unit tests :)

**Comment by makc** [comment]
ha, somebody already started this in #7708

**Comment by GGAlanSmithee** [comment]
One way to make versioning easier on develops would be to commit to using [semantic versioning](http://semver.org/) and at the same time make a final (as in final for the first major release) draft of the public API.

In PR #7131 @mrdoob said

> Yep! Once API gets more stable and all relevant browsers catch up with ES6 we'll start moving stuff around.

If this means the API is about to get more stable, I don't know.

**Comment by verteAzur** [comment]
>  semantic versioning 

Certainly... 

Backward compatibility is an important lib feature! I believe to be the up most one. Otherwise any work, that has a mid/long term life cycle, could quickly become counterproductive...

**Comment by verteAzur** [comment]
20H for a transition of 2 versions, not bad ! Thx THREE.js

**Comment by mrdoob** [comment]
Out of curiosity, do you mind sharing your findings? 
We can add those to the migration page if needed, or maybe others can benefit.

**Comment by verteAzur** [comment]
Sure, I'll keep you posted.

**Comment by verteAzur** [comment]
Re: I was able to complete the migration findings just today, not sure if it is still of actuality. Anyways, happy new years to all of you ! 

**THREE.ShaderMaterial: attributes should now be defined in THREE.BufferGeometry instead.**
Shader custom attribute is not supported in a static way anymore. Certainly you will have to change your js code and your shaders to remove that error; this is why it is an advanced topic! In the previous versions of three.js, we were able to create custom attributes like custom uniforms. For performance and standardization sake that option is not supported anymore. You will have to use the custom attribute properties from the bufferGeometry object. In order to fully understand how to resolve that migration issue, the best thing is to look at that simple bufferGeomtry example : http://threejs.org/examples/webgl_buffergeometry_custom_attributes_particles.html and learn how to use bufferGeometry. Once you dive in and understand how buffergeometry works, you will feel the real power of THREE.js, I will advise taking your time while grasping that topic, it really worth it ! Furthermore, if I have to make a prediction, THREE.js will be using bufferGeometry for everything soon! 

In a nutshell, you will have to do the following new steps (note the sample uses the position attribute only):

```javascript
//create your buffergeometry object
var geometry = new THREE.BufferGeometry();

//temporary create a position buffer variable
var positions = new Float32Array( particles * 3 );

var particles=1000;

//store random initial position values
for ( var i = 0, i3 = 0; i < particles; i ++, i3 += 3 ) {
	positions[ i3 + 0 ] = ( Math.random() * 2 - 1 ) * radius;
	positions[ i3 + 1 ] = ( Math.random() * 2 - 1 ) * radius;
	positions[ i3 + 2 ] = ( Math.random() * 2 - 1 ) * radius;
}

//pass the position attribute to the geometrybuffer object
geometry.addAttribute( 'position', new THREE.BufferAttribute( positions, 3 ) );
```
That's all you have to do for the position attributes, knowing that the position attribute is intrinsic to the shader (no need to create a variable). For non intrinsic custom attribute, please see the full example in the link shared above.


**New animation support**
THREE.js release v. 73 introduces a new way to handle your animations. For the first time, the skinning and morphing animations are unified in the same class. The particularity of the new class is to give you an interface for mixing/blending multiple animations. The new class attribute weight needs to be set properly in order to achieve the animation mix. Let’s look at an example (for sake of simplicity the example shows only skinning animation). 

```javascript
var meshobj;
var mixer;
var animations={};
var actions={};
var loader = new THREE.JSONLoader();
loader.load( ‘filepath.json’, function( geometry, materials ) {
	
	//init skinning material (same as before)
	var originalMaterial = materials[ 0 ];
	originalMaterial.skinning = true;
	
	//init skinning object
	meshobj = new THREE.SkinnedMesh.call( geometry, originalMaterial );
	
	//create mixer object
	mixer = new THREE.AnimationMixer( meshobj  );
	
	//loop and store animations names	
	for ( var i = 0; i < geometry.animations.length; ++ i ) {

		var animName = geometry.animations[ i ].name;
		animations[ animName ] = geometry.animations[ i ];
		
	}

	// Loading and init is finished, add mixer actions
	actions[animations[0]]  =new THREE.AnimationAction( animations[0] ) ;
	actions[animations[0]].weight = 1; //this actions has priority in the mixer
	
	actions[animations[1]]  =new THREE.AnimationAction( animations[1] ) ;
	actions[animations[1]].weight = 0; 

	//add actions to mixer
	mixer.addAction( actions[animations[0]]);
	mixer.addAction( actions[animations[1]]);


} );

//create a function to mix one animation to another
//factor is the a decimal number from 1 to 0 to indicate the blending speed
//note this function needs to be called when all is loaded (after loader.load)!
var fadefromto = function (fromname,toname,factor) {
	
	//now we can blend actions
	mixer.crossFade( actions[ fromname ], actions[ toname ], factor );

};

//Finally, let’s add the mixer update function into the loop runner
function update () {

	requestAnimationFrame( update );

	var delta = clock.getDelta();
	mixer.update( delta );

	renderer.render( scene, camera );

} )();
```


**Loader.createMaterial: Unsupported color Ambient**
This error is a gracious error (will not break your code) and it is easily fixable. You just have to remove the colorAmbient attribute from your json object file. Here are the detailed steps to fix the problem: https://github.com/mrdoob/three.js/issues/7368


**pesky warnings**
THREE.MeshLambertMaterial: ‘bumpMap’ is not a property of this material
THREE.MeshLambertMaterial: ‘bumpScale’ is not a property of this material
THREE.MeshLambertMaterial: ‘depthwrite’ is not a property of this material
THREE.MeshLambertMaterial: ‘shading’ is not a property of this material.
For the previous warning you have 2 options to fix it : 
	remove the property from the file object
	change your material type to THREE.MeshPhongMaterial
