### ISSUE TITLE
StereoEffect.js: 37mm lens in VR makes our panoramic images unfocused

### ISSUE THREAD

**Issue by Inframatic** [mrdoob/three.js#7730]
The black virtual reality glasses are the upcoming version of the vjubox with a wider lens (37mm). Unfortunately this wider lense is causing our panoramic images to become unfocused.

![2015-10-29-14 37 04](https://cloud.githubusercontent.com/assets/4029062/10819981/612843b4-7e4b-11e5-9e80-563bb2684913.jpg)

---Through Testing----
We found that the pano images looks clear with the iPhone 6 but unfocused with the iPhone 6 Plus.

The theory to why this works for the iPhone 6 and not for the 6 Plus lies in the alignment of the center of each pano image with the center of the 37mm lens. 
![2015-11-05 09 34 42](https://cloud.githubusercontent.com/assets/4029062/10963467/f4105036-83a0-11e5-97e7-034580cca0aa.jpg)
The center of the lens lines up with the center of pano image in the iPhone 6, but not for the 6 Plus, which is slightly misaligned. 

This means that the pano images must be calibrated when it detects that the view size is over a certain width or with certain phones.

---- My work-around. What's next? ----

in threejs/StereoEffect.js, setting _innerFactor = ( _halfFocalWidth + this.separation / 2.0 ) / ( _halfFocalWidth * 2.0 ); to _innerFactor = ( _halfFocalWidth + this.separation / 2.0 ) / ( _halfFocalWidth * 2.4 ); will adjust the focus of the panoramic images to fit on larger phones like the 6 Plus.

The next steps are adding a conditional that toggles this value between 2.0 and 2.4 depending on the size of the phone, **but this seems like a work-around.**

**Any idea about how to fix this problem? We ship 1000's of these 37mm lens vr goggles quite soon.**

Best,
Ian Steffy,
meventi

**Comment by mrdoob** [comment]
I thought https://github.com/borismus/webvr-polyfill covered this already?

**Comment by Inframatic** [comment]
Just saw this. Thanks for the prompt response! I will implement this and let you know the results.
