### ISSUE TITLE
TextureLoader download progress function not called

### ISSUE THREAD

**Issue by chriscar** [mrdoob/three.js#7734]
TextureLoader does not call function for download progress as shown in http://threejs.org/docs/#Reference/Loaders/TextureLoader

Three.js 73

**Comment by mrdoob** [comment]
Can you please provide a jsfiddle?

**Comment by leitzler** [comment]
TextureLoader uses ImageLoader that creates the image using:
```javascript
var image = document.createElement( 'img' );
```
Those elements doesn't support `progress` events, see http://www.w3schools.com/jsref/dom_obj_event.asp

Should textures be loaded with (our old friend) `XMLHttpRequest` instead? :wink:

**Comment by mrdoob** [comment]
Hmm... and convert to dataurl?

**Comment by makc** [comment]
What I did in #7749 :)

**Comment by bpetar** [comment]
Can someone write workaround here?

**Comment by makc** [comment]
You discard the code [from line 47 to the end of load method](https://github.com/mrdoob/three.js/blob/master/src/loaders/ImageLoader.js#L47-L81) and replace with:
```javascript
			// https://twitter.com/sonnypiers/status/187513545397776384
			var xhr = new XMLHttpRequest();
			xhr.open('GET', url, true);

			xhr.responseType = 'arraybuffer';

			xhr.onload = function(e) {
				if (this.status == 200) {
					var uInt8Array = new Uint8Array(this.response);
					var i = uInt8Array.length;
					var binaryString = new Array(i);
					while (i--) {
						binaryString[i] = String.fromCharCode(uInt8Array[i]);
					}
					var data = binaryString.join('');

					var base64 = window.btoa(data);

					image.onload = function() {

						THREE.Cache.add( url, this );

						if ( onLoad ) onLoad( this );

						scope.manager.itemEnd( url );

					};

					var type = this.getResponseHeader('Content-Type');
					if (type.indexOf (';') > 0) {
						type = type.substr (0, type.indexOf (';'));
					}

					image.src = 'data:' + type + ';base64,' + base64;
				} else {

					if ( onError ) onError( event );

					scope.manager.itemError( url );

				}
			};

			xhr.onerror = function () {

				if ( onError ) onError( event );

				scope.manager.itemError( url );

			};

			xhr.send();

			return image;

```

**Comment by makc** [comment]
ha wait, I did not put progress listener there XD

**Comment by mrdoob** [comment]
@kschzt did you have any luck with this?

**Comment by bpetar** [comment]
Who is kschzt? I didnt want to rebuild three.js, so I use this piece of code to load the texture separately and it seems json models are then using cached version.

function loadImage(imageURI)
{
	request = new XMLHttpRequest();
	request.onprogress = updateProgressBar;
	request.onload = loadedImage;
	request.open("GET", imageURI, true);
	request.overrideMimeType('text/plain; charset=x-user-defined'); 
	request.send(null);
}

**Comment by kschzt** [comment]
@mrdoob yes - we are using our own Image loader for the time being:

https://github.com/vizorvr/vizor/blob/develop/browser/scripts/loaders/imageLoader.js#L24

More experimentation has shown that the time spent parsing the Arraybuffer into a usable Image is around 500ms for a 60mb stereo cubemap texture. But for Vizor.io, the benefit of being able to wait and show progress to the user before autoplaying really trumps everything :)

**Comment by mrdoob** [comment]
> More experimentation has shown that the time spent parsing the Arraybuffer into a usable Image is around 500ms for a 60mb stereo cubemap texture.

How many ms does the browser take?

**Comment by kschzt** [comment]
That is browser time. https://github.com/vizorvr/vizor/blob/develop/browser/scripts/loaders/imageLoader.js#L18-L26

**Comment by mrdoob** [comment]
I know I know. I meant... in comparison `new Image()`.

**Comment by makc** [comment]
0? by the time image.onload is called, the image is ready.

**Comment by mrdoob** [comment]
Well, imagine we change `ImageLoader` so it uses this approach. I'm wondering if the browser does something internally when using `Image` that it's faster.

Otherwise, a PR would be more than welcome! 😊

**Comment by makc** [comment]
it may be faster or not, but unlike xhr thing it does not block js thread. maybe it should use xhr if there are any progress listeners?

**Comment by mpaccione** [comment]
Hello, I very much appreciate what  you have done in creating D3 and would love to see this resolved to a working implementation described in the official documentation.

**Comment by mrdoob** [comment]
@mpaccione I think you got the wrong project: https://github.com/mbostock/d3

**Comment by mpaccione** [comment]
Ah so much on my mind, I meant Three.js. I'm using Three.js and have an issue where sometimes the webserver doesn't load serve the textures needed and the loader progress and error callback would  be most useful....typos sheesh i need more coffee...at least there was a three in it hehe.

**Comment by mrdoob** [comment]
@mpaccione Is that on Chrome 50? If so... #8670

**Comment by makc** [comment]
@mpaccione also error handler should be called, this issue was about progress only

**Comment by mpaccione** [comment]
@mrdoob Ah Yes, 8670 would explain the reason why I put in a texture loader progress in the first place. I was expecting the issue to trigger the error handler. It appears it doesn't as makc says the error handler works. I look forward to the texture loader progress event being worked out as it will be relevant in my data visualization. Thank you for developing this excellent technology, it has changed my technical interests for sure.

**Comment by mrdoob** [comment]
#7734

**Comment by Claod44** [comment]
Hi,
I found this :

**Comment by makc** [comment]
> I also found this, but I don't want use "module.exports" and I need a bit of help

sure, change this
```javascript
module.exports = AjaxTextureLoader;
```

to this:
```javascript
//module.exports = AjaxTextureLoader;
```

hope it helps!

**Comment by Claod44** [comment]
Hi x) thanks for the joke, I know how to comment x) hahaha. But seriously I mean this : 


I don't know if the onProgress callback will launch for an TextureLoader instance.

(the reason why I think the onProgress will not callback after the onStart finished).
If it's not launching I want to create a TextureLoader instance, override the default load methode to launch the onProgress as callback after the onStart finished.

"a" is the texture path, "b" is the onStart(), "c" should be the onProgress - But refering to the TextureLoader doc : "onProgress not supported => undefined" 

It doesn't work but as an exampe, I'm trying something like this :

`var machin = new THREE.TextureLoader(manager);
                        machin.load= function(a,b,c,d) {
// launch the base load Function (default one) [create Image instance, use the manager etc...]
                         THREE.TextureLoader.prototype.load.call(this,a,function a() { //??? },  function b() { //default function b actions; //launch the c callback c();}, c,d); 
                        }`

I don't know if i'm clear ^^'

**Comment by makc** [comment]
> I want to create a TextureLoader instance

no, what you want is to create AjaxTextureLoader instance. no further voodoo is required.

**Comment by Claod44** [comment]
Hi,

Sorry to say that, but what do you mean when you say "AjaxTextureLoader's load() won't return the texture immediately, **you will have to pick it up from onLoad**"

Is that the problem ?

function load(url, onLoad, onProgress, onError) {
        fileLoader.load(url, cacheImage, onProgress, onError);

        /**
         * The cache is currently storing a Blob, but we need to cast it to an Image
         * or else it won't work as a texture. TextureLoader won't do this automatically.
         */
        function cacheImage(blob) {
            // ObjectURLs should be released as soon as is safe, to free memory
            const objUrl = URL.createObjectURL(blob);
            const image = document.createElementNS('http://www.w3.org/1999/xhtml', 'img');

            image.onload = ()=> {
                cache.add(url, image);
                URL.revokeObjectURL(objUrl);
                document.body.removeChild(image);
                loadImageAsTexture();
            };

            image.src = objUrl;
            image.style.visibility = 'hidden';
            document.body.appendChild(image);
        }

        function loadImageAsTexture() {
            textureLoader.load(url, onLoad, ()=> {}, onError); **// Texture 404 nout found**
        }

**//texture return 404 not found**
    }


    **return Object.assign({}, textureLoader, {load}); // ???**

When I replace my TextureLoader instance by the AjaxTextureLoader one, I want to store that texture on my material.map. When I use it I got this result : 

My material.map : undefined
My onProgress callback : is executed twice.

I do not use to give up, but... I do not understand where is the problem here.
In my head (only) that's simple, I just need to enable a "onProgress callback" in the TextureLoader / AjaxTextureLoader, using a FileLoader for xhr abilities, and the load still needs to return my texture.

W3C sucks, image onProgress events : nope, watching salty devs is better.

I've found and tried many things... no success-

**Comment by makc** [comment]
> what do you mean when you say "AjaxTextureLoader's load() won't return the texture immediately, you will have to pick it up from onLoad"

I mean it literally. TextureLoader returns texture, and then sends it to you again as an argument to onLoad, iirc. AjaxTextureLoader above only does 2nd half, because it is lazy and does not create the texture itself.

> Is that the problem ?

Not really.

> When I use it I got this result :
> My material.map : undefined

Quite possible. So just set material.map to new THREE.Texture, and then later set it again to whatever you receive in onLoad.

> My onProgress callback : is executed twice.

More than 0 then, yay!

> I do not understand where is the problem here.

Me neither.

**Comment by makc** [comment]
[Here is a fiddle](https://jsfiddle.net/f2Lommf5/585/) for you, @Claod44 - if this does not help, I give up 😘

**Comment by Claod44** [comment]
Hi makc,
Thank you for your example,
In your last post when I was not understanding : "you will have to pick it up from onLoad"
I had to set my material.map inside the AjaxTextureLoader.load using its onoad(texture) parameter function.
Whouhouuu !

This part is fixed, I got a working on progress with my xhr parameter [OK]
The onProgress callback trigger once [OK]
And we can see the texture on the scene [OK]
I updated the code to use the manager [OK]

Part 1 : 
`
function AjaxTextureLoader(themanager) {
    this.manager = themanager;
    const cache = THREE.Cache;

    // Turn on shared caching for FileLoader, ImageLoader and TextureLoader
    cache.enabled = true;

    const textureLoader = new THREE.TextureLoader(manager);
    const fileLoader = new THREE.FileLoader();
    fileLoader.setResponseType('blob');

    function load(url, onLoad, onProgress, onError) {
        const cached = cache.get(url);
        if (cached) {
            return cached;
        } else {
            fileLoader.load(url, cacheImage, onProgress, onError);
        }
        
        /**
         * The cache is currently storing a Blob, but we need to cast it to an
         * Image or else it won't work as a texture. TextureLoader won't do this
         * automatically.
         */
        function cacheImage(blob) {
            // ObjectURLs should be released as soon as is safe, to free memory
            const objUrl = URL.createObjectURL(blob);
            const image = document.createElementNS('http://www.w3.org/1999/xhtml', 'img');

            image.onload = ()=> {
                cache.add(url, image);
                URL.revokeObjectURL(objUrl);
                document.body.removeChild(image);
                loadImageAsTexture();
            };

            image.src = objUrl;
            image.style.visibility = 'hidden';
            document.body.appendChild(image);
        }

        function loadImageAsTexture() {
            textureLoader.load(url, onLoad, ()=> {}, onError);
        }
    }

    return Object.assign({}, textureLoader, {load});
}
` 
And, as you suggested, in my code : 

`var textureLoader = new AjaxTextureLoader(manager);
                        textureLoader.load( jsonArrayMaterialsOptions[index].texture, function( texture ) {
                                material.map = texture;
                                material.needsUpdate = true;
                        }, function(xhr) {
//here updating the percent
                            console.log((xhr.loaded +'/'+ xhr.total + ' = ' + xhr.loaded/xhr.total));

                            // requestAnimationFrame(render);
                        } );`

For now and after some testing : 
New problem, when I reach 100% I see my model without its texture, then the texture is added. 
I'll post if I can fix this, but if you know why, feel free to comment :) thanks a lot for helping me ^^.
