### ISSUE TITLE
this.THREE = THREE;

### ISSUE THREAD

**Issue by MasterJames** [mrdoob/three.js#7739]
I'd like to suggest to include

```
this.THREE = THREE;
```

 at the end or wherever so if you run eval or Function

```
(new Function(data)).call(this);
```

where data is the three.min.js text loaded (uniquely),
so you can still use THREE globally.
 I'm not sure that's the best solution, but it seems like a good idea. 
I'm not able to imagine where that would become problematic.

**Comment by Mugen87** [comment]
I've read this issue multiple times but i still don't understood the benefit of this suggestion. Can somebody enlighten me? 😊

**Comment by mrdoob** [comment]
I don't understand it either... It sure would benefit of some context.

**Comment by donmccurdy** [comment]
I think this amounts to having three.js automatically add itself to the global namespace... we probably want to avoid that; rollup or other tools can do it for users if needed.
