### ISSUE TITLE
No effect — line.geometry.vertices.length = 0;line.geometry.verticesNeedUpdate = true;

### ISSUE THREAD

**Issue by blackslate** [mrdoob/three.js#7741]
## Steps to reproduce

- Visit [http://lexogram.com/issues/lineVertices/index.html](http://lexogram.com/issues/lineVertices/index.html) or run the HTML file below locally.
- Click anywhere on the window, to execute the lines

    line.geometry.vertices.length = 0;
    line.geometry.verticesNeedUpdate = true;

## Result

Nothing happens.

- Click again to set the line to a random length. When the position of the vertices is changed, the line is updated.

## Expected

Setting the number of vertices of a line to 0 should make the line disappear.

    <!DOCTYPE html>
    <html>

    <head>
      <title>Line.geometry.vertices = [] issue</title>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r73/three.js"></script>
      <style>
        body {
          margin: 0;
          overflow: hidden;
        }
        p {
          position: absolute;
          left: 0;
          top: 0;
        }
      </style>
    </head>
    <body>

    <div id="WebGL-output"></div>
    <p >Click to toggle line.geometry.vertices to [] and back.<br>The line should disappear on every second click.</p>

    <script>
    function init() {
      var WIDTH = window.innerWidth
      var HEIGHT = window.innerHeight
      var scene = new THREE.Scene()
      var camera
      var cube
      var line
      var vertices

      ;(function createCubeAndLine() {     
        var lineGeometry = new THREE.Geometry();
        vertices = lineGeometry.vertices
        var lineMaterial = new THREE.LineBasicMaterial({
          color: 0x000000
        })
        var cubeGeometry = new THREE.BoxGeometry(10, 10, 10)
        var cubeMaterial = new THREE.MeshBasicMaterial({
          color: 0x006699
        })
        cube = new THREE.Mesh(cubeGeometry, cubeMaterial)

        lineGeometry.vertices.push(new THREE.Vector3(100, 0, 0))
        lineGeometry.vertices.push(new THREE.Vector3(-100, 0, 0))
        line = new THREE.Line(lineGeometry, lineMaterial) 

        cube.add(line)
        scene.add(cube)
      })()

      ;(function createPerspectiveCamera(){
        var FOV = 45
        var ASPECT = WIDTH / HEIGHT
        var NEAR = 1
        var FAR = 3000
        camera = new THREE.PerspectiveCamera(FOV, ASPECT, NEAR, FAR)

        camera.position.x = 100
        camera.position.y = 100
        camera.position.z = 100
        camera.lookAt(scene.position)
      })()

      ;(function initializeRenderer(){
        var renderer = new THREE.WebGLRenderer()
        renderer.setClearColor(new THREE.Color(0xEEEEFF))
        renderer.setSize(WIDTH, HEIGHT)

        document.getElementById("WebGL-output").appendChild(renderer.domElement)

        ;(function render() {
          cube.rotation.x += 0.01
          renderer.render(scene, camera)
          requestAnimationFrame(render)
        })()
      })()

      window.addEventListener("mouseup", toggleLine, false)

      function toggleLine() {
        if (vertices.length) {
          vertices.length = 0
        } else {
          var length = Math.random() * 90 + 10
          vertices.push(new THREE.Vector3(length, 0, 0))
          vertices.push(new THREE.Vector3(-length, 0, 0))
        }

        line.geometry.verticesNeedUpdate = true

        console.log(line.geometry.vertices)
      }
    }

    window.onload = init
    </script>
    </body>
    </html>

**Comment by WestLangley** [comment]
http://stackoverflow.com/questions/14840026/dynamically-adding-vertices-to-a-line-in-three-js/14841010#14841010
