### ISSUE TITLE
Negative morph influences are clamped to 0 if number of morphTargets is > 8

### ISSUE THREAD

**Issue by jaakkor2** [mrdoob/three.js#7742]
If I take

http://threejs.org/examples/#webgl_morphtargets_horse

and disable the mixer, but add a line

mesh.morphTargetInfluences[ 1 ] = Math.cos( 0.005*Date.now()  );
                
then I only see the positive half-cycle of morphing (where Math.cos > 0).  However, if I edit horse.js, and have only 8 morphtargets, then I do see the whole cycle of morphing.

If I change [this line](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L742)

```javascript
activeInfluences.sort( numericalSort );
```

to

```javascript
activeInfluences.sort( function(a,b) { return Math.abs( b[0] ) - Math.abs( a[0] ) } );
```

then it works for me.  In other words, sort the influences according to the absolute values.

I wish I could do a proper pull request and perhaps define a function `numericalAbsoluteSort`, but my drive is so full that I cannot even clone threejs.

**Comment by satori99** [comment]
@jaakkor2 You can easily edit a cloned repo using the github in-browser editor, and submit a PR, without pulling it to your local machine. (Especially as it's a one-liner)

**Comment by mrdoob** [comment]
Oh, interesting!

**Comment by mrdoob** [comment]
Done. Thanks!
