### ISSUE TITLE
Can I use the matrix of the object detected from Raycaster to calculate its vector in the face I intersected with? If so, how do I do it?

### ISSUE THREAD

**Issue by BeeShall** [mrdoob/three.js#7744]
I'm trying to calculate the angle between my direction of displacement and the wall(which is a THREE.Mesh), but I have no idea how to find the vector of the wall. Is there an easy way to do this?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
