### ISSUE TITLE
Spotlight casting shadow without an object

### ISSUE THREAD

**Issue by weiserhei** [mrdoob/three.js#7750]
I am facing a problem where a THREE.SpotLight is casting a Shadow without an object beeing in its frustum. I have tested with r73 and r74 dev, this is the link to stackoverflow containing the same information: http://stackoverflow.com/questions/34135581/three-js-spotlight-casting-shadow-without-an-object

I have setup a simple scene containing a THREE.SpotLight and a plane-mesh. The SpotLight is set to cast Shadows and the plane to receive Shadows. There is a square Shadow visible on the ground plane, which is the size of the SpotLights shadowCamera. This scene is the right hand side of the image below.

A cube-mesh is now added and positioned outside the initial camera viewspace. By zooming out, a bit before the cube-mesh becomes visible to the camera, the Spotlight Shadow disappears. This is pictured in the left hand side of the image.

http://jsfiddle.net/L0rdzbej/157/

This happens in Firefox, from what I heared it is not the case in Chrome. What is happening here and how to avoid it?

![shadow2](https://cloud.githubusercontent.com/assets/7581732/11634445/da418e02-9d10-11e5-9fad-36465d06d2ea.png)

**Comment by makc** [comment]
FWIW, my nightly ff on mac does not look like that if I comment the box out.

**Comment by mrdoob** [comment]
The cube doesn't have a `.castShadow = true` so it may be something to do with the frustum of the shadowMap. I can't reproduce on my system (neither Firefox nor Chrome).

**Comment by weiserhei** [comment]
I am not quite sure what to do now, I will rephrase my question in case its not clear. What I want to achieve is a simple plane with a SpotLight shining on and illuminating it. Right now there is a Shadow coming from nowhere and I want to get rid of it. 

I´ve tested this on Windows 7+10 in Firefox, IE11 and Edge. This only happens in Firefox, both on Win7 and 10.

**Comment by WestLangley** [comment]
Does the "shadow" change with `light.shadowDarkness`? Is it the same size/shape as the shadow frustum?

**Comment by weiserhei** [comment]
- 1 ShadowDarkness = 0.1
- 2 Shadow Camera Helper added
- 3 Shadow Darkness = 1

![shadow](https://cloud.githubusercontent.com/assets/7581732/11642409/fac62c46-9d3d-11e5-903f-212b3406a09a.jpg)

**Comment by weiserhei** [comment]
This shadow does not show up anymore :ghost:
