### ISSUE TITLE
ThreeJS Docs Spelling Error

### ISSUE THREAD

**Issue by harbhub** [mrdoob/three.js#7754]
You spelled the word radius wrong (raidus).

Go here:
http://threejs.org/docs/#Reference/Core/Geometry.normalize

.normalize ()
Normalize the geometry. 
Make the geometry centered and has a bounding sphere whose raidus equals to 1.0.

**Comment by VinaySingh035** [comment]
@harbhub  done that.

**Comment by mrdoob** [comment]
Thanks guys!
