### ISSUE TITLE
SphereBufferGeometry creates multiple vertices ontop of each other for first row

### ISSUE THREAD

**Issue by RebelMoogle** [mrdoob/three.js#7756]
Library Version: THREE.WebGLRenderer 74dev (also occured in current master branch)
Firefox 42.0, Windows 10, NVIDIA GeForce GTX 560 Ti

The code for creating a sphere in SphereBufferGeometry.js (https://github.com/mrdoob/three.js/blob/master/src/extras/geometries/SphereBufferGeometry.js) creates multiple vertices ontop of each other. 
(see lines 53-55):
```javascript
for ( var y = 0; y <= heightSegments; y ++ ) {

		var verticesRow = [];

		var v = y / heightSegments;

		for ( var x = 0; x <= widthSegments; x ++ ) {

			var u = x / widthSegments;

			var px = - radius * Math.cos( phiStart + u * phiLength ) * Math.sin( thetaStart + v * thetaLength );
			var py = radius * Math.cos( thetaStart + v * thetaLength );
			var pz = radius * Math.sin( phiStart + u * phiLength ) * Math.sin( thetaStart + v * thetaLength );
```

Since v is always 0 for the first row of vertices, and the sin(0) is also 0, x and z of the first vertices will always be zero. 
y will always be 1, since cos(0) == 1
So unless thetaStart is chosen != 0, it will create multiple vertices ontop of each other.

See fiddle and screenshot. 
Repro:
Create a sphere with default values (let phiStart and thetaStart be 0)
Check vertices (print them to console, for example.

http://jsfiddle.net/hw9rcLL8/

![threejssphere](https://cloud.githubusercontent.com/assets/636083/11654033/f9f9a5c6-9da2-11e5-840a-bd188fa5e78b.PNG)

**Comment by WestLangley** [comment]
Why is your example about `SphereGeometry` when your post is about `SphereBufferGeometry`?

In addition, `SphereBufferGeometry` is _indexed_, so it is not as simple as inspecting the `position` attribute only; you need to inspect the `index` property, too.

Note also there are duplicated vertices on a seam that runs from the north pole to the south pole. 

Faces that are joined physically can have very different tangent vectors if the faces are disjoint on the UV map, so it is not uncommon for vertices to be duplicated on seams (i.e., wherever the UVs are discontinuous).

**Comment by mrdoob** [comment]
I guess the issue here is that `SphereGeometry` used to merge duplicated vertices(?) but now `SphereGeometry` uses `SphereBufferGeometry` internally.

In that case, one can still do:

```javascript
var geometry = new THREE.SphereGeometry( 5, 8, 8 );
geometry.mergeVertices();
```

**Comment by WestLangley** [comment]
I see. `SphereGeometry` is now created from `SphereBufferGeometry`. So, yes, @mrdoob's solution should clean it up.

Maybe we should add `mergeVertices` to the `SphereGeometry ` constructor -- or restore the old code.
