### ISSUE TITLE
Rotating along X/Z axes skews mesh instead of rotating

### ISSUE THREAD

**Issue by ezekg** [mrdoob/three.js#7759]
I'm not sure if I'm just doing something wrong, but rotating a child mesh along it's Z axis with

```coffee
mesh.rotate.z = ...
```

just ends up skewing the mesh. Here is an image of what I mean:

![image](https://cloud.githubusercontent.com/assets/6979737/11671900/1c387ab2-9dd1-11e5-8535-ae158e170b9d.png)

And here's the relevant code (ignore all of the numbers; just kept to show that I am also doing scaling and translations on the mesh):

```coffee
geo = new THREE.BoxGeometry parent.size.x / 2, 1, 1
mesh = new THREE.Mesh geo, new THREE.MeshNormalMaterial()
mesh.position.x = (parent.size.x * parent.scale.x) / 4
mesh.position.y = (parent.pitch * parent.scale.y) / 2
mesh.position.z = (parent.size.z * parent.scale.z) / 2
mesh.scale.y = 1 / parent.scale.y
mesh.scale.z = 1 / parent.scale.z
mesh.rotation.z = Math.atan2((parent.pitch * parent.scale.y), (parent.size.z * parent.scale.z))

parent.add mesh
```

Do I need to do these in a different order, or use a matrix transform instead? It might also be worth noting that the parent mesh is also scaled and translated. I feel like I'm missing something really basic here.

**Comment by WestLangley** [comment]
The skewing of child meshes that have been rotated is to be expected if a parent object has non-uniform scale.

Please note that three.js does not in general support non-uniformly scaled parent objects, so I suggest you consider another approach. Scale the geometry directly, for example.

[stackoverflow](http://stackoverflow.com/questions/tagged/three.js) is your best bet if you need further help.
