### ISSUE TITLE
OBJExporter.js / OBJLoader.js incompatibility

### ISSUE THREAD

**Issue by radio412** [mrdoob/three.js#7761]
**The problem**: I needed to save OBJ files to the server. I used OBJExporter. When I then used OBJLoader to the load the file, I got  a "property vertices of undefined" error.

**The "fix":**
When I modified line 29 of OBJExporter.js  ( https://github.com/mrdoob/three.js/blob/master/examples/js/exporters/OBJExporter.js ) I was able to open the OBJ file.

The line of code is:
output += 'o ' + mesh.name + '\n';

Note the trailing space behind the o.

I modified the line to remove the trailing space, and got rid of the name:
output += 'o' + '\n';

**How this affected OBJLoader.js:**
This allowed line 162 in ( https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/OBJLoader.js ) to function normally and my mesh was loaded.
Line 162 is: if ( /^o /gm.test( text ) === false ) {...

The test at line 162 triggers the creation of the geometry object, thus the vertices array, and the mesh loads.

**The question**
Is this a byte encoding issue on my part? I don't understand how this regex returns false: /^o /gm.test( text ) ?

Thanks

**Comment by mrdoob** [comment]
I think this has been fixed in the `dev` branch already. I just tried exporting a unnamed cube from the editor and imported it again and it worked fine.
