### ISSUE TITLE
Export to .dwg and .revit

### ISSUE THREAD

**Issue by Stracx** [mrdoob/three.js#7764]
Hello,

I'm trying to export objects i created with three to .dwg and .revit files. I found nothing on the internet explaining how to do it in that direction. The only way to accomplish it i found, is exporting the objects into .stl then convert the file to .dwg and .revit, but i'm losing colors and textures.
Is there a way to do it without losing colors/textures?

Thanks and sorry for my approximative english.

**Comment by bhouston** [comment]
DWG and Revit are complex formats that are not open source.  I think they are a huge challenge to export to directly with just JAvaScript in ThreeJS.

Also I believe STL export from ThreeJS does not contain color information (although it could be added as there is a semi-standard for it) I believe at this time, and it is not possible to have textures in STL at all as it isn't a supported feature (I believe, I could be werong.)

**Comment by Stracx** [comment]
Ok thx,

I will try to put colors into my stl objects now, it will be a huge challenge for me already ^^

**Comment by donmccurdy** [comment]
Revit can import OBJ, so I think the best bet would be OBJExporter here. GLTFExporter may also work, but you’d need to use something like Assimp or the glTF blender importer to convert to another format Revit supports.

**Comment by Itee** [comment]
@bhouston I wrote an threejs exporter that is not so diffuclut in fact. But it is not release under opensource. 

Perhaps, there is an other (lighter, and little buggy three json export that can do the job: [https://github.com/va3c/RvtVa3c](https://github.com/va3c/RvtVa3c) )

**Comment by bhouston** [comment]
BTW there is this new format - STL like https://3mf.io/

**Comment by mrdoob** [comment]
https://threejs.org/examples/#webgl_loader_3mf 😊

**Comment by bhouston** [comment]
@mrdoob hehe.  Very nice.  Basically STL is a brutally bad format - it just wrecks geometry when you convert to it.  If you @Stracx can use the 3MF format instead things will be better for you and given that ThreeJS already supports it, it should be easy to do. :)

**Comment by bhouston** [comment]
@Stracx vertex color extension for 3MF is here: https://3mf.io/3mf-materials-and-properties-extension/#_Toc417309091
