### ISSUE TITLE
Question: manipulating camera position/orientation programmatically with TrackballControls

### ISSUE THREAD

**Issue by KoenT-IM** [mrdoob/three.js#7765]
We have a setup here where we want to be able to control a 3D scene manually using the mouse, but also programmatically from code.
For example: a (master) client app is being controlled with the mouse and sends new scene positioning info to a server, which relays this to other (listening) clients. The other (slave) client apps then need to update themselves so that they show the same configuration as the initiating client.

The issue we have is the following:

When using the mouse to control the scene, TrackballControls will dispatch a change event from its update function whenever a position change was detected. This is fine for the (master) client app, because it can then grab the current positioning info, package it up and send it over o the server.

However, when we adjust the positioning info in the TrackballControls of another (slave) client app from code, this will in itself also generate a new "positioning changed" event in update() (which is called in the animate loop).

So: is there a way the block the TrackballControls from dispatching change events when we set the new info programmatically from code?

Or perhaps more generally: what is the best way to set new positioning info in TrackballControls from code without user interaction, without it triggering change events? It should just passively apply the new settings, so that it becomes visible, but without triggering any new change events.

Thanks for any insights!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
