### ISSUE TITLE
AdditiveAlphaBlending in examples

### ISSUE THREAD

**Issue by leonsal** [mrdoob/three.js#7766]
The examples:
- examples/webgl_materials_blending.html 
- examples/webgl_materials_blending_custom.html 

Use THREE.AdditiveAlphaBlending which doesn't seem to exist anymore.

**Comment by mrdoob** [comment]
Do you mind doing a PR with the fix?

**Comment by leonsal** [comment]
Done.

**Comment by mrdoob** [comment]
Thanks!
