### ISSUE TITLE
Improper Ordering of Menu Options

### ISSUE THREAD

**Issue by harbhub** [mrdoob/three.js#7767]
Go here and check menu on the lefthand side of your screen:
http://threejs.org/docs/#Reference

Current ordering of the Textures section:
CubeTextures
CompressedTextures
DataTexture
Texture

CompressedTexture should come before CubeTexture for alphabetizing.

**Comment by VinaySingh035** [comment]
only this much to change?
or something else too is needed to be done?

**Comment by VinaySingh035** [comment]
@harbhub  but here i guess the application is taking the files alphabetically.
so what can be done to handle that? as i have no idea how to deal with this.

**Comment by harbhub** [comment]
I looked here:
http://threejs.org/docs/list.js

If that list file is manually generated, then change it by hand.

If that list file is automatically generated, then fix the generation method so that it works for the Textures section.

I looked here to see how Three JS is being built:
https://github.com/mrdoob/three.js/tree/master/utils/build

I've never used Python, so I'm not sure what exactly needs to be fixed.

**Comment by VinaySingh035** [comment]
I guess here the listing is generated manually, because if it was generated automatically then `CopmressedTexture` must have came before `CubeTexture` as per the lexicographical ordering.
Hence I'm going to edit it manually.

**Comment by harbhub** [comment]
That sounds reasonable.

If the list messes up during the next build, then we know that the list was automatically generated.

**Comment by VinaySingh035** [comment]
yeah was thinking of the same to test this.

**Comment by VinaySingh035** [comment]
@mrdoob  as you mentioned in my previous PR that I should change on `dev` branch.
review the new PR, I think this is all you meant.
