### ISSUE TITLE
Current dev build does not work with webpack

### ISSUE THREAD

**Issue by brianchirls** [mrdoob/three.js#7783]
`self` is undefined. Perhaps consider UMD or something like that?

I built a minimal test case here:
https://github.com/brianchirls/webpack-test/tree/three.js

Make sure you use the 'three.js' branch of that repo. Run `npm test` to install everything and build the output file. You'll see the error with stack trace in the console. You can then open index.html to see the same problem in a browser.

**Comment by mrdoob** [comment]
Maybe #7747 broke this too?

**Comment by simonThiele** [comment]
fine by me...
<img width="453" alt="screen shot 2015-12-14 at 07 06 28" src="https://cloud.githubusercontent.com/assets/10807661/11774016/4a60d38a-a231-11e5-83a1-839ed391fde2.png">

**Comment by simonThiele** [comment]
Nope, it should fix that but done it a little wrong. Please check PR #7787. If it's merged your example works again. The initial PR #7747 was created by the same issue, that self is not defined under node environments but it's now fixed I hope :).

**Comment by brianchirls** [comment]
Any potential fix should be tested in a browser as well as on the command line. The browser doesn't have `global`.

**Comment by simonThiele** [comment]
That's why the code checks if node is running the code (so not in the browser) and therefore self will not be set to global

**Comment by mrdoob** [comment]
I think 60ca652d7a215b3038dca0703e251e3534726412 should fix this?

**Comment by brianchirls** [comment]
Yes, it does. And I'm glad to see that code go. Declaring a `var` like that inside of a block is sloppy and misleading anyway. We can do better.

For some reason, I didn't even know `self` was a thing outside of workers. Weird. But not in node.
https://developer.mozilla.org/en-US/docs/Web/API/Window/self

Thanks, @mrdoob

**Comment by simonThiele** [comment]
This should do the trick too:
https://github.com/simonThiele/three.js/blob/dev/src/Three.js#L20-L38

**Comment by brianchirls** [comment]
That looks like it might work, but it could probably stand to be cleaned up a bit. Like, maybe instead of `} else if ( typeof self !== 'undefined' ) {` with an empty block, it should just be: `} else if ( typeof self === 'undefined' ) {` followed by the actual action, and so on.
