### ISSUE TITLE
three.js and stencil buffer

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#7785]
Hi everyone,

i'm working on a mirror surface that uses the stencil buffer for correct rendering. Everything works as expected and the code looks like this:

```javascript
// get a reference to the internal WebGL rendering context
var gl = renderer.context;

// enable stencil test
gl.enable( gl.STENCIL_TEST );
gl.stencilFunc( gl.ALWAYS, 1, 0xff );
gl.stencilOp( gl.REPLACE, gl.REPLACE, gl.REPLACE );

...
// render mirror
...

// change stencil function and operation for testing
gl.stencilFunc( gl.EQUAL, 1, 0xff );
gl.stencilOp( gl.KEEP, gl.KEEP, gl.KEEP );

...
// render objects
...

// disable stencil test
gl.disable(gl.STENCIL_TEST);
````

What bothers me is that three.js provides no API for working with the stencil buffer. As a result, users have to work with the native WebGL interface. What do you think about an enhancement so users can control the stencil buffer like the depth or color buffer?  

Besides, is it okay when users work directly with `THREE.WebGLState` (over `renderer.state`)? Or is this an internal entity for `THREE.WebGLRenderer`?

If `THREE.WebGLState` is a user level interface, maybe it's one solution to create some methods for stencil buffer handling (e.g. `setStencilWrite`, `setStencilFunc`).

```javascript
// like this
renderer.state.setStencilWrite( true );
````

Using three.js R73

**Comment by WestLangley** [comment]
Related: #7758
