### ISSUE TITLE
r73 : geometry.uvsneedupdate is not working correctly

### ISSUE THREAD

**Issue by kait85** [mrdoob/three.js#7788]
This was brought up by someone previously here (https://github.com/mrdoob/three.js/issues/7179#issuecomment-144122968), but I am not convinced the fix discussed in that ticket has worked.

I wrote a js fiddle showing uvsNeedUpdate doing nothing.  It seems that if I dispose of the directGeometry object that is created during the conversion process into bufferGeometry, then it properly sees the value change as it forces a fresh copy to occur.

http://jsfiddle.net/bc6dgrk2/1/

I have temporary resorted to this solution to ensure the update occurs, so I can continue developing..

//added for r73, uvsNeedUpdate will not work!!!
if(mesh.geometry.__directGeometry !== undefined) {
    mesh.geometry.__directGeometry.dispose();
    mesh.geometry.__directGeometry = undefined;
}

I also tried updating the directGeometry object myself but it had no effect

**Comment by WestLangley** [comment]
You are reassigning UVs -- Use `copy()` or `set()` instead.

fiddle: http://jsfiddle.net/bc6dgrk2/2/

Related: http://stackoverflow.com/questions/34403807/threejs-geometry-colorsneedupdate-true-broken-since-r72
