### ISSUE TITLE
Scroll breaks when losing focus in Internet Explorer

### ISSUE THREAD

**Issue by rensvolkel** [mrdoob/three.js#7789]
I'm using the OrbitControls. With Chrome / Firefox i haven't problems. When i run with Internet Explorer, everything is ok. But when i lose the focus (open a other program or something else) and go back, i can't scroll anymore.

The onMouseWheel function will not called anymore...

**Comment by mrdoob** [comment]
Maybe you should report to Microsoft instead?

**Comment by rensvolkel** [comment]
Is there nobody else with this same problem?

**Comment by rensvolkel** [comment]
I have found a work around. It's look like a bug in IE 11.

When i click back on the window, i set the focus back on the body of the DOM with a mousedown listener.

    window.addEventListener('mousedown', function(e) {
        e.preventDefault();

        // Work around for IE 11 scroll bug
        $("body").focus();
    });

This works for me.
