### ISSUE TITLE
load a dynamic generated stl

### ISSUE THREAD

**Issue by imssimi** [mrdoob/three.js#7791]
I generate a stl with a picture a user have uploaded.
The text of the stl is written in a string. 
Now I have trouble to show this in three.js.
I tried it like this:

loader.load( my_stl_string, function ( geometry ) { ....

and get this:
414 (Request-URI Too Long)

Does somebody know a better way? Or is able to explain what's the problem?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
