### ISSUE TITLE
Raycasting inaccurate / no longer working (r72)

### ISSUE THREAD

**Issue by Eta92** [mrdoob/three.js#7794]
Hello, I am currently developping a game with THREE.js r72 and my raycasting don't want to works well any longer.
Before to realize my raycast was no working I was using : 
----var vector = new THREE.Vector3( mouse.x, mouse.y, 1 );
----vector.unproject( camera );
----var ray = new THREE.Raycaster( camera.position, vector.sub( camera.position ).normalize() );
For a reason I can not explain "( mouse.x, mouse.y, 1 )" have become invalid in my code (not intersecting anything).
Then I tried to fix it and I found that "( mouse.x, mouse.y, 0.5 )" bring my raycast back to life ... But it is now inaccurate as you can see on this screenshot : 
![raycastissue](https://cloud.githubusercontent.com/assets/13470863/11811945/f1ab06da-a338-11e5-9d37-79c6265de075.jpg)

So I would need some help to solve one part or the other of this problem.
Maybe there is a known conflict with "( mouse.x, mouse.y, 1 )" or maybe you have ideas to solve the inaccuracy ?

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

**Comment by Eta92** [comment]
Ok, but as far as I understand the probleme, there is still the issue with the raycasting inaccuracy.
By default if you use Raycaster.setFromCamera it will use the "( mouse.x, mouse.y, 0.5 )".
So this seems to be a miss functioning in the core of THREE.js, no ?
