### ISSUE TITLE
npm build broken

### ISSUE THREAD

**Issue by DelvarWorld** [mrdoob/three.js#7800]
https://github.com/mrdoob/three.js/blob/master/build/three.js#L24

Line 24 has this:

    if ( self.requestAnimationFrame === undefined || self.cancelAnimationFrame === undefined ) {

However, `self` is not defined, causing builds to fail with things like:

    error given was: ReferenceError: self is not defined
        at Object.<anonymous> (node_modules/three.js/build/three.js:24:6)

An older version of three I have installed has this line at the top of the file:

    var self = self || {};// File:src/Three.js

However it's not present in this build.

**Comment by DelvarWorld** [comment]
Dupe of https://github.com/mrdoob/three.js/issues/7783

**Comment by mrdoob** [comment]
I think 60ca652d7a215b3038dca0703e251e3534726412 should fix this?

**Comment by DelvarWorld** [comment]
It won't fix it if the built file still references the var `self` before it's created

**Comment by mrdoob** [comment]
Not sure what the fix that. I don't use npm...

**Comment by DelvarWorld** [comment]
You can just manually look at the built three.js file and see if `self` is created before use. It's a javascript error, not an npm error.

**Comment by mrdoob** [comment]
Uhm... I've found this...

https://github.com/mrdoob/three.js/blob/master/utils/npm/header.js

**Comment by DelvarWorld** [comment]
Whenever you run the task that generates `build/three.js`, inspect that file source (source of `build/three.js`) to make sure `self` is declared. As linked in the original ticket, [this line](https://github.com/mrdoob/three.js/blob/master/build/three.js#L24) in `build/three.js`is the first reference to the variable `self`. There's no declaration of `self` above that line. It's invalid Javascript, and only in the browser will it accidentally work because it automatically makes `self` a global variable.

**Comment by bhouston** [comment]
I will not have time to look at this until Friday at the earliest, sorry.  If you are desparate, just go back to the way it was in the last official release in the mean time?

**Comment by mrdoob** [comment]
I don't know what changed 😐

**Comment by DelvarWorld** [comment]
I don't either, I searched the git history for both header.js and self and didn't find anything conclusive. :confused:

**Comment by DelvarWorld** [comment]
Ok, the plot thickens, but I still don't know what the answer is. Part of this was a mistake by me. There are **two** Three.js npm packages, one maintained by @bhouston, called [**three**](https://www.npmjs.com/package/three), the other by @mrdoob called [**three.js**](https://www.npmjs.com/package/three.js) Can we remove the one that's not canonical? I've seen **both** referenced in tutorials and I don't know which is the main one.

Now, @bhouston's version *appears* to be the same version as the canonical Three repo (**r73**), and there's no indication it's any different. However, we can see in the source code, @bhouston's version contains the line that fixes the npm build:

<img width="385" alt="screen shot 2015-12-17 at 8 14 58 pm" src="https://cloud.githubusercontent.com/assets/79215/11886687/f0f418c6-a4fa-11e5-98e6-fd314d7e452b.png">

My mistake was that I was using @bhouston's version in an old project, but then used @mrdoob's version in a new project, and confused the two for the same thing. So it's possible that the `header.js` file is only used in @bhouston's npm version. Keep in mind this is even more confusing because the github link for @bhouston's repo still points to **this** repository. Also @bhouston's version has 100+ releases, while @mrdoob's version only has 5 releases, making @bhouston's seem more legit despite the author not being @mrdoob.

Anyway, this isn't accusing anyone of wrongdoing, just an information dump and letting you know as and end consumer of Three.js, I'm confused and don't know which version I should be using in the wild.

**Comment by GGAlanSmithee** [comment]
I think @mrdoob took over `three.js` just recently, because IIRC, it used to be an outdated package not maintained by any core contributor. Is this now the official package? I know you talked about taken it over, but never saw anything official. I've been using the `three` package that's published by @bhouston

**Comment by mrdoob** [comment]
I see where the confusion comes from.
I wonder if it's possible to do aliases in npm? So `three.js` is an alias of `three`?

**Comment by mattdesl** [comment]
There is no real way to do aliases. It's probably worth [deprecating](https://docs.npmjs.com/cli/deprecate) one of them and changing the readme to point to the "official" one.

IMHO the `three` module is worth keeping; it has a longer history. In many cases I've used it to test the same code on a variety of ThreeJS versions, just by doing `npm install three@0.69 && npm test` and so forth for each version.

**Comment by mrdoob** [comment]
Stephanie Snopek @ npm said:

> At this time we don't support aliasing one package to another. However, we're exploring this feature, so you may see it in the future!

**Comment by DelvarWorld** [comment]
Also this still needs to be fixed in the main `three.js` repo, it still causes any build to fail using a modern JS build system. I took a look but as far as I can tell the [scripts use for npm building should in theory include the header](https://github.com/mrdoob/three.js/blob/master/utils/npm/build.js#L18) and I don't know how they're used in the deploy process.

**Comment by toxicFork** [comment]
Regarding this I think it may be best if the `three` package was handed over to you, and in `three.js` npm package, you place a deprecation message and require('three').

**Comment by toxicFork** [comment]
Any news re: this, @mrdoob ? 

@bhouston what do you think? If you don't mind updating your `three` package every time @mrdoob makes a new release then I am considering switching to npm `three` rather than `three.js` myself.

**Comment by toxicFork** [comment]
that may be a while... I guess we'll need to wait for bhouston's reply :)

**Comment by bhouston** [comment]
sorry guys, crazy deadline at Exocortex that has taken be away from ThreeJS for the last 6 weeks. have not really had any time to look at this.  I think we are hitting our deadline today so I can resume helping out here.  I really do not do anything special when creating builds btw, I just run the npm script I checked into NodeJS.  There is no magic.

I have no preference at all about three and the three.js modules.  We had a dependence in Clara.io on the three module, but we got rid of that a few months ago.  So whatever we choose I can do.

What is a situation that allows me to reproduce the error that we are seeing?  @DelvarWorld do you or does @toxicFork have a test case or even a couple?  I'll run both modules through it as well as testing out our standard ThreeJS npm usage.

**Comment by DelvarWorld** [comment]
It's pretty simple, and breaks at require time, stopping any project dead in its tracks. But it only happens in @mrdoob's `three.js` version:

    ~ $ mkdir three-test

    ~ $ cd three-test/

    ~/three-test $ npm install three.js
        three.js@0.73.0 node_modules/three.js

    ~/three-test $ node
        > var THREE = require('three.js')
        ReferenceError: self is not defined
            at Object.<anonymous> (/Users/andrewray/three-test/node_modules/three.js/build/three.js:24:6)
            at Module._compile (module.js:456:26)
            at Object.Module._extensions..js (module.js:474:10)
            at Module.load (module.js:356:32)
            at Function.Module._load (module.js:312:12)
            at Module.require (module.js:364:17)
            at require (module.js:380:17)
            at repl:1:13
            at REPLServer.self.eval (repl.js:110:21)
            at repl.js:249:20
        >

@mrdoob I'm still also confused about your involvement in either npm package. Can you explicitly state what your plan is for the two packages, and why you made your own?

**Comment by mrdoob** [comment]
@DelvarWorld I didn't made my own. Someone else did the `three.js` npm package. It got unmaintained for years and then it was transferred to me.

To be honest, npm is a thing I would rather not have to think about...

**Comment by toxicFork** [comment]
Then I vote for keeping `three`, and deprecating three.js to point to `three` on npm. Then we can poke bhouston when new releases are out or automate it somehow :)

E.g.

```bash
npm deprecate three.js "Please use the 'three' package as this one is deprecated"
``` 

Or something similar.

**Comment by DelvarWorld** [comment]
@mrdoob with all due respect to your incredible work of making the webgl api accessible, it's still a javascript package, and npm is the community accepted standard for javascript package management. Usually the core maintainers are the responsible parties for releasing npm packages...

However, this may not be an issue. I don't think many projects are using `three.js`, and the simplest solution might just be to delete it / deprecate it as @toxicFork suggested. [This Google search](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%22npm%20install%20three.js%22) is less than one page of results which is encouraging. It looks like the only way someone would find the `three.js` repo is by complete accident.

**Comment by GGAlanSmithee** [comment]
It's also considered standard to leave out '.js' from npm packages, as mentioned in a previous issue touching on this.

**Comment by mattdesl** [comment]
> the simplest solution might just be to delete it

Please never delete a module from npm. It will cause people's applications to stop working. 

However, deprecating is very easy and happens often in npm. It will not break existing modules that have come to depend on three.js.

**Comment by mrdoob** [comment]
So... as far as I understand, the main issue was `self`. As you can read in #7787, `self` is now gone, so now either `three` and/or `three.js` should work.

**Comment by bhouston** [comment]
Hmm... I think the fix is incredibly simple.  I believe that the npm "three.js" module wasn't created by using the build.js script that I put in the NPM directory here:

https://github.com/mrdoob/three.js/tree/master/utils/npm

It doesn't have the header.js or the footer.js, thus it will not work on NodeJS.

I checked out both main branches (dev and master) and ra the command:

   node build.js 0.73.1-dev

And then I tested it using the included test script:

   node test.js

And it worked.  So basically the three module just has to be rebuilt using the build.js script I created and all should be well. :)  There may be additional issues, but at minimum it needs to have the header.js and footer.js included.

**Comment by bhouston** [comment]
And to be clear, I also did ran:
   npm install three.js

And I looked at the three.js file and it didn't have the header/footer.  Thus this is the first issue that is causing problems.

If @mrdoob wants to add me to the npm three.js module I can update it or he can do it himself.  I do not mind either way.

**Comment by bhouston** [comment]
I can deprecate the "three" module by adding some debug messages to it and direct them to use "three.js" or we can do vice versa.  I do agree that we should probably only have a single NPM module.

**Comment by bhouston** [comment]
If @mrdoob adds me as an admin to three.js npm package I can handle deprecating one or the other package (either three or three.js -- let me know which) in the proper manner and ensuring the other works.  I do not mind helping maintain one of these packages but I'd prefer not to have to maintain two -- it just splits the community.

**Comment by toxicFork** [comment]
Yep, voting for keeping three and deprecating three.js for many reasons

**Comment by mrdoob** [comment]
> If @mrdoob adds me as an admin to three.js npm package I can handle deprecating one or the other package 

Done! 😊

**Comment by bhouston** [comment]
@mrdoob, cool.  Which package would you like to deprecate?

**Comment by mrdoob** [comment]
@bhouston considering that `three` have more dependents I would deprecate `three.js` by now. Hopefully in the near future we'll be able to turn it into an alias.

**Comment by MasterJames** [comment]
Would using  "threejs" without the dot be a bad suggestion? I'd go with "three" otherwise then.

**Comment by DelvarWorld** [comment]
$ cd test

    $ npm install three.js
        three.js@0.73.2 node_modules/three.js
        └── three@0.73.0

    $ node
        > var three = require('three.js');
        WARNING: The 'three.js' npm package is deprecated in favor of the 'three' npm package, please upgrade.

This is the best day of my life

**Comment by mrdoob** [comment]
@bhouston 

> It doesn't have the ```header.js``` or the ```footer.js```, thus it will not work on NodeJS.

I guess, starting from `r74`, the library no longer references `self`, so `header.js` is not needed, and `Three.js` has had the module code for a while, so `footer.js` is neither needed?

https://github.com/mrdoob/three.js/blob/dev/src/Three.js#L9-L17
