### ISSUE TITLE
WebGL GPU particle system example renders wrong on Intel HD 4600

### ISSUE THREAD

**Issue by deejbee** [mrdoob/three.js#7804]
I've been using the GPUParticleSystem class in a similar way to the example http://threejs.org/examples/webgl_gpu_particle_system.html

It looks correct on one card (happens to be a Radeon HD 6470M) but then I run the same code on a mini-pc with Intel HD 4600 and it looks like this:

![image](https://cloud.githubusercontent.com/assets/1560398/11847926/a7b5d660-a417-11e5-8913-2d7075819ec5.png)

The particles appear are completely different.  They have gravity, always green (instead of the default purple) and appear in kind of 2 jets rather than the random snaking with wind it should be.

I'm at a loss why it could be that different. Anyone?  

Sorry if this is the wrong place to post an issue like this.  I'm not sure if it's  a threed issue, or the vertex shader code or the particle generator.  You may guess I'm a bit new at this.

**Comment by flimshaw** [comment]
interesting!  i have a few suspicions, I'll take a look over the weekend, I have a feeling it has to do with floating point precision on the shader on lower end cards, but I haven't seen this particular behavior even on mobile platforms I've tried.

**Comment by asalga** [comment]
I have a somewhat similar issue on a mac with an AMD Radeon HD 6970M (1024 MB)
Any ideas what could be causing this?

![screen shot 2016-02-01 at 2 31 42 pm 1](https://cloud.githubusercontent.com/assets/137723/12728593/92577fa0-c8f0-11e5-8189-158d8f6f392e.png)

**Comment by mrdoob** [comment]
Can you guys try this one?

https://dl.dropboxusercontent.com/u/7508542/three.js/r74dev/examples/webgl_gpu_particle_system.html

**Comment by kapaboo** [comment]
Any chance you guys can have another look at this issue? The fix did not solve it for me
and i have no more idea on how to debug this...
Two machines in front of me: 
Surface Pro 1 & Surface Pro 4,
All the Software used is the same. 
chrome://gpu outputs the same information&error for both.
But one renders it correctly and the other like in asalga's picture.

Ps. Great work!

**Comment by tildebyte** [comment]
@kapaboo Which is which? I would expect that the issue would be with the older hardware (Surface Pro 1).

**Comment by kapaboo** [comment]
Sry, my mistake but you guessed right.
Surface Pro 1 is rendering wrong.
