### ISSUE TITLE
iOS shader error: Too many uniforms

### ISSUE THREAD

**Issue by dmarcos** [mrdoob/three.js#7807]
Since I updated to iOS 9.2 on my iphone6 the [collada example](http://threejs.org/examples/#webgl_loader_collada) doesn't load anymore on Safari. I get the following error on console `THREE.WebGLProgram: shader error:`

<img width="1271" alt="erroruniforms" src="https://cloud.githubusercontent.com/assets/39342/11857327/0f718ba2-a40c-11e5-9f57-a17e1d1f7943.png">

**Comment by WestLangley** [comment]
On iPhone iOS 9.2, I get this for r.73 and r.74dev:

>ColladaLoader: – "Bip01_Pelvis-node-transform has 36 bones."
>WebGLRenderer: too many bones - 36, this GPU supports just 27 (try OpenGL instead of ANGLE)

**Comment by mrdoob** [comment]
They reduced the amount of supported uniforms?

**Comment by dmarcos** [comment]
I've been using the ColladaLoader everyday for 3 months and it broke after updating to iOS 9.2. Same code base, three.js (r74dev) and collada versions.

**Comment by mrdoob** [comment]
Yes, I understand. It would be good to know how many uniforms does webgl on iOS 9.1 support versus 9.2.

**Comment by makc** [comment]
ios 8.3 ipad3 says 128 uniforms per vertex shader, 64 per fragment (webglreport.com)

**Comment by leitzler** [comment]
iPhone 6s plus - iOS 9.2 - Same error message as OP, no model visible.
iPhone 6 plus - iOS 9.1 - Still same error message, no model visible.

webglreport.com is identical for both (128 per vertex, 64 per fragment).

Must be related to something else.

**Comment by mrdoob** [comment]
@dmarcos Are you able to verify that this worked in iOS 9.1? It'll save us time trying to figure out where the problem is.

**Comment by dmarcos** [comment]
@mrdoob I don't have a device with iOS 9.1. I will fish around to see if
someone has one.

**Comment by makc** [comment]
pretty much same :shit: under ios 8.3
![screen shot 2015-12-21 at 1 09 20](https://cloud.githubusercontent.com/assets/242577/11921050/b67c8606-a77f-11e5-995a-23a4baa2dba5.png)
are you sure ios version has anything to do with it?

**Comment by ayamflow** [comment]
Hey,

I've been running into the same issue lately.

> WebGLRenderer: too many bones - 33, this GPU supports just 27 (try OpenGL instead of ANGLE).

We tried lowering the number of bones to 26, and then the WebGLRenderer error disappears but the "Too many uniforms" stays there. In the shader displayed by the error, I can see:
> #define MAX_BONES 26

I then used a model with 25 bones and I could see
> #define MAX_BONES 25

Not sure what's happening there but I haven't been able to find the actual maximum bones/uniforms number.

Btw, we tested and reproduced this on iphone6, ipad mini and ipad pro.

**Comment by alexolotl** [comment]
I'm getting this error on iOS Safari as well.  The gltf loader and collada loader examples on the Three.js site don't work on my iPhone either, they also give the "too many uniforms, too many bones" error.

I tried manually editing the max bones in my three.min.js file  to 24 to test it out- the animation then loads, but in a glitchy way.  Did anybody else figure out a solution for this?  Is there a way to force the phone to use OpenGL directly rather than ANGLE, if that is what's causing it?

**Comment by Mugen87** [comment]
Is this issue still a problem with a current iOS version? Besides, does the shader error occur only in Safari or in all browser?

**Comment by donmccurdy** [comment]
The glTF 2.0 Monster example is working for me. iPhone SE, iOS 11.
