### ISSUE TITLE
TextGeometry moved out of src directory

### ISSUE THREAD

**Issue by ianhbell** [mrdoob/three.js#7817]
Why?  Now we have to link to files in the examples tree in order to use TextGeometry...  Or is there a better way for doing 3D text now?

**Comment by ianhbell** [comment]
See ded588f4711c23d22f07ffc7eed22ece29b2617d

I still think that this shouldn't have been removed from the library.

**Comment by mrdoob** [comment]
`TextGeometry` has been added back to core in `r74` (currently in `dev`).
