### ISSUE TITLE
BufferAttribute doesn't actually accept Arrays

### ISSUE THREAD

**Issue by omgitsraven** [mrdoob/three.js#7820]
The docs for BufferAttribute's constructor say "The array can either be a regular Array or a Typed Array". However, if I try using a regular Array, I get "Error: WebGL: drawArrays: bound vertex attribute buffers do not have sufficient size for given first and count" (in Firefox; Chrome gives a different but similar error.)

This is happening in r73 and in dev. All you have to do to see it is replace Float32Array with Array in the webgl_buffergeometry_points.html example. (Here's a fiddle of the change: http://jsfiddle.net/385pnphs/ note lines 28+29.)

This is relatively easy to work around once you know about it by just doing Float32Array.from(regularArray) right before constructing the BufferAttribute, of course; so even if it isn't a priority for fixing, the docs should at least be updated not to suggest that a normal array would work, to save people my headache in the future. ;)

**Comment by mrdoob** [comment]
Ah... The docs are the one that need to be fixed. `BufferAttribute` no longer supports basic arrays.

**Comment by mrdoob** [comment]
Fixed. Thanks!
