### ISSUE TITLE
should itemEnd be called after itemError in ImageLoader?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#7822]
my situation is that I use model loader that automatically loads textures, and I watch the progress using loading manager. by the model design there is sometimes one absent texture, so I currently consider the loading complete when the manager reports either completion or error. I am affraid that this is not accurate since texture failure may come before the rest of the model is loaded, I think it makes more sense to call itemEnd after itemError, so that I can receive overall completion event even if some of stuff failed along the way.

**Comment by makc** [comment]
I can see I can do it by overriding default manager methods, too, but which is better way?

**Comment by mrdoob** [comment]
#7801 proposes a `LoadingManager` tweak.

**Comment by makc** [comment]
ok I trust you will work it out eventually. for now going with the hack above.
