### ISSUE TITLE
computeBoundingBox not called in mesh.raycast

### ISSUE THREAD

**Issue by leonsal** [mrdoob/three.js#7823]
1. Reading the source of the `raycast()` method of THREE.Mesh (from Master, Dev
is similar) I noticed that `computeBoundingSphere()` is called if the geometry has a null boundingSphere, but the same is not true for the boundingBox.
If it is null `raycast()` does not call `computeBoundBox()` and proceeds
with calculating the intersection with the geometry itself.
Is there any reason for that ?

2. Case positive, the calculation of the inverse of the geometry's MatrixWorld
should probably be moved inside the `if (geometry.boundingBox !== null)`
as this is an expensive operation.

Not an issue, just a question:
For calculating the intersection of the raycaster ray with the bounding sphere,
a copy of the bounding sphere is made and converted to world coordinates
and the intersection is checked with this transformed sphere.

For calculating the intersection with the bounding box the raycaster ray
is transformed to model coordinates (by multiplying by the inverse of
the MatrixWorld) and then the intersection was checked using the transformed
raycaster ray and the bounding box in model coordinates.
This method was used instead of the one used for the bounding sphere
for performance reasons ?

**Comment by WestLangley** [comment]
1. FWIW, all the other primitives test only against the bounding sphere. Maybe for some models, the bounding box test increases overall performance. What we are doing now seems reasonable. Maybe someone else can provide a compelling argument one way or the other. I do not have a strong opinion on this.

2. You can't do that. `ray` is used elsewhere.

3. It is typically less expensive to transform one ray into model space than to transform all vertices into world space. But in the case of the bounding sphere test, it seems reasonable to do that test in world space to avoid the matrix inverse.

**Comment by leonsal** [comment]
Thanks. I noticed later that `ray` in model coordinates was used to check for intersect with the geometry.
Sorry by the noise.
