### ISSUE TITLE
Chrome 47 reports "Your graphics card does not seem to support WebGL" on OSX

### ISSUE THREAD

**Issue by DanielBaird** [mrdoob/three.js#7835]
Three.js examples in Chrome 47 on my macbook all report "Your graphics card does not seem to support WebGL".

I've previously worked on three.js in Chrome on this machine -- don't know if it was an OS update or a Chrome update that borked it. 

**Machine:** 2011 MacBook Air
**OS:** OSX 10.10.5
**Still working:** Firefox 42, Safari 9

Anyone else seeing this?  Similar problems in the past seem to be attributed to video drivers.. not much you can do about that in OSX.

**Comment by mrdoob** [comment]
You should report this to Chrome instead. https://code.google.com/p/chromium/issues/list
