### ISSUE TITLE
How to move THREE.Sprite freely in 3D scene which is the child of THREE.Object3D ?

### ISSUE THREAD

**Issue by stu-sam** [mrdoob/three.js#7838]
We have a requirement like to move THREE.Sprite freely in 3D space. The THREE.Sprite is child of THREE.Object3D . 

The movement of THREE.Sprite must be accruate with mouse move on the 3D space and must not affect other child position of THREE.Object3D.
The movement of THREE.Sprite must be also possible on ROTATION / PAN of  THREE.Object3D.

We are able to match the above requirement for initial rendered THREE.Object3D angle.
Below is the logic for the same :

      // Vector to get the difference of Sprite movement
     var panTextAlongCamera = new THREE.Vector3();

        panAnnotationLeft = function(distance) {
        var panOffset = new THREE.Vector3();
        var te = camera.matrix.elements;
        // get X column of matrix
        panOffset.set(te[0], te[1], te[2]);
        panOffset.multiplyScalar(distance);
        panTextAlongCamera.add(panOffset);

    };

    // pass in distance in world space to move up
	panAnnotationUp = function(distance) {
        var panOffset = new THREE.Vector3();
        var te = camera.matrix.elements;
        // get Y column of matrix
        panOffset.set(te[4], te[5], te[6]);
        panOffset.multiplyScalar(-distance);
        panTextAlongCamera.add(panOffset);
    };

	// Move selected SPRITE to move moved position
	panAnnotation = function(delta,divName) {
        var element = Ext.get(divName).dom;
		if (camera.top !== undefined) {
			scope.panAnnotationLeft(delta.x * (camera.right - camera.left) / element.clientWidth);
			scope.panAnnotationUp(delta.y * (camera.top - camera.bottom) / element.clientHeight);
			SELECTED.position.add(panTextAlongCamera);
        } else {
            console.warn('WARNING: Unknown camera type - pan disabled.');
        }
    };
	
	Ext.get(divisonId).dom.onmousemove = function(event){
			if(SELECTED){
			// Set 2D End vector 
			panTextEnd.set(event.clientX, event.clientY);
			
			// Get the difference of movement of 2D vectors
			panTextDelta.subVectors(panTextEnd, panTextStart);
			panTextAlongCamera.set(0,0,0);
            // Call the function to move sprite to appropriate mouse move positions 
			panAnnotation(panTextDelta,'3D_DIV');
			
			// Set to end to start for further move reference
			panTextStart.copy(panTextEnd);
			}
		};

However the logic becomes inaccurate and sometimes THREE.Sprite starts moving in opposite direction when the THREE.Object3D is rotated and are in different angles.

The THREE.Sprite movement is different for different THREE.Object3D angles.

We are expecting a generic logic which will agree upon every angles of THREE.Object3D.

Any suggestions/solution will be greatly appreciated. 
Thanks in Advance.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.
