### ISSUE TITLE
Three.js with Dreamoc Devices

### ISSUE THREAD

**Issue by sRcBh** [mrdoob/three.js#7839]
I saw that this site is using three.js to render for the Dreamoc Devices.
Is it implemented in the library ?

http://b2b.partcommunity.com/community/partcloud/index#!part?name=R2D2+-+Configurator&model_id=26525&varsettransfer=

**Comment by mrdoob** [comment]
Yes. If you look in the console it displays `THREE.WebGLRenderer 69`.
