### ISSUE TITLE
The new version firefox r43 is not good at supporting three.js

### ISSUE THREAD

**Issue by ChengZX66** [mrdoob/three.js#7851]
![qq 20151224160918](https://cloud.githubusercontent.com/assets/16424073/11992059/2bb9a5d2-aa5c-11e5-8479-b2c49fc9de68.png)
ep:
http://threejs.org/examples/#webgl_animation_skinning_blending
http://threejs.org/examples/#webgl_animation_skinning_blending
...

**Comment by mrdoob** [comment]
You should report to Mozilla instead.
