### ISSUE TITLE
VREffect.js.filterInvalidDevices should check for .deviceName before lowercasing

### ISSUE THREAD

**Issue by pindiespace** [mrdoob/three.js#7855]
Minor, but annoying  error: 
Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined(…)

Also, adding a Promise polyfill lets VREffect run in IE 11, already OK in Edge.

```js
function filterInvalidDevices( devices ) {
...
return device.deviceName.toLowerCase().indexOf( 'oculus' ) !== - 1;
}
```

**Comment by borismus** [comment]
Yes definitely need to integrate the promise polyfill. Ie11 support is broken in boilerplate too.

**Comment by mrdoob** [comment]
@pindiespace would you like to do a PR?

**Comment by pindiespace** [comment]
This promise polyfill worked for me in IE 11

https://github.com/taylorhakes/promise-polyfill

**Comment by pindiespace** [comment]
OK, will PR what I am using.

**Comment by pindiespace** [comment]
Promise polyfill I used for IE11:
https://github.com/taylorhakes/promise-polyfill

Also Array.filter polyfill (I used the one from MDN)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Comment by borismus** [comment]
Ok, added this to boilerplate, but haven't tested since I don't have ready access to an IE11 device.

**Comment by mrdoob** [comment]
@borismus oh? are there 2 versions of `VRControls`/`VREffect`?

**Comment by pindiespace** [comment]
IE11 works ok with WebVR Boilerplate and webvr-polyfill -- but I added a Promise polyfill. IE10 doesn't work (no WebGL) but the canvas renderer does work on IE 9 and 10 - too slow for animation, but it could be used to do a single screen draw of a VR scene when WebGL isn't supported. That way, a VR scene can do its own fallback image. 

Windows Mobile 10 (at least in the Edge emulator) works for VR with the webvr-polyfill. It's working with the stock version of Edge (no dev version required). I don't have a Windows phone, so I can't test if orientation works.

**Comment by pindiespace** [comment]
Checked the return value. Both MDN and MSDN show the return value of Array.filter as an empty array if no matches are found, so this edit is consistent.

**Comment by mrdoob** [comment]
`filterInvalidDevices` is not gone.  #7862
