### ISSUE TITLE
Material

### ISSUE THREAD

**Issue by whatisor** [mrdoob/three.js#7858]
As I know, in 3D graphic, to simulate material color, we have something like this:
http://devernay.free.fr/cours/opengl/materials.html
However, it requires threejs support full mode of shading:
1. Ambient (no exist for material)
2. Diffuse (color)
3. Specular (with Phong shader)
4. Shininess (with Phong shader)

So, I wonder why you do not also support Ambient for each material.
Thank you

**Comment by mrdoob** [comment]
The material spec you are referring is from 94-97, those materials tried to simulate what `THREE.AmbientLight` does in three.js.

**Comment by WestLangley** [comment]
@whatisor The _ambient reflectance_ of the material is assumed to be the same as the _diffuse reflectance_ of the material. In other words, the material does not respond any differently to a photon from an indirect light source than it does from a photon from a direct light source. Consequently, `material.ambient` was removed, and `material.color` is used in its place in the lighting equation.

Some artists find this restrictive, but they can always create a custom material if they need artistic freedom. Creating custom materials is getting easier in three.js. : - )

**Comment by whatisor** [comment]
@WestLangley : material.color is calculated as Diffuse, not ambient.
Example I have 2 objects with same Diffuse, Spec and Shininess, but I want one is a bit lighter. Then, I will need Ambient in material, right?

**Comment by WestLangley** [comment]
You are going to have to experiment with the three.js material settings until you get the effect you want.
