### ISSUE TITLE
Raycaster in r73 not working correctly with MultiMaterial objects

### ISSUE THREAD

**Issue by Chaky74** [mrdoob/three.js#7865]
I have a doublesided object that needs to be "clicked on" on the back side (which being rendered), and all of the materials in my objects are of MultiMaterial type. Raycaster only works with single material objects.

P.S.
I've changed line 18817
<code>var material = object.material;</code>
to
<code>if (object.material.materials!==undefined){
 var material = object.material.materials[0]
}else{
 var material = object.material
};</code>
to patch it up temporarly (all of my multimaterial objects have only one material.. courtesy of max export script)

**Comment by mrdoob** [comment]
Yes, for simplicity and performance reasons, `Raycaster` no longer takes multi materials into account. You should split your geometry, or fix the max exporter so it doesn't export multi material when not needed.
