### ISSUE TITLE
LightMap Specular lighting?

### ISSUE THREAD

**Issue by ilanusse** [mrdoob/three.js#7870]
Hey guys, I've been toying around with the dev version of Three.js and it seems lightMaps are now adding a specular lighting component to materials.

This didn't happen in Revision 67.

How does this work? I can't seem to find documentation on it.

Cheers and happy holidays!

**Comment by WestLangley** [comment]
> it seems lightMaps are now adding a specular lighting component to materials.

Why do you believe that? Can you provide a live example to demonstrate it?

`lightMaps` in three.js are a source of indirect, diffusely-reflected light.

**Comment by ilanusse** [comment]
![old-lightmap](https://cloud.githubusercontent.com/assets/5209518/12022650/87dbec64-ad70-11e5-89b8-ea7f4683c084.png)
This first image is how the render looks before updating three.js. The revision used is R67, and the board is using the polka dot texture seen as a light map. It works fine.

![new-lightmap](https://cloud.githubusercontent.com/assets/5209518/12022672/be41c738-ad70-11e5-971e-f65da6520ce5.png)

Here, however, the lightmap appears to be adding a ton of extra light. Nothing was changed besides the three.js version to 74dev.

![new-lightmap-angle](https://cloud.githubusercontent.com/assets/5209518/12022696/0ff6da82-ad71-11e5-9c87-c555b47d0668.png)

As you can see here, at an angle, the light that hits the board appears to be less. That is why I wonder if there isn't a specular component (I'm rotating the camera, not the board).

**Comment by WestLangley** [comment]
Lightmaps are handled differently than they were before. They are now treated as an additional light source. Try dialing down `material.lightMapIntensity`.

If you are trying to replicate former behavior, you can try `MeshBasicMaterial` and set `material.aoMap` to be your light map.
