### ISSUE TITLE
texture.needsUpdate does not work (r73)

### ISSUE THREAD

**Issue by neszt** [mrdoob/three.js#7874]
http://codepen.io/anon/pen/adBwQG?editors=001

In the following example, the

hudTexture.needsUpdate = true;

does not work with three.js r73, so the text drawn to the texture is not refreshing. It worked in version r71.

**Comment by neszt** [comment]
With bisect, i found the following commit cause the problem:

[ff3465c7f0adae2918d4362131d5edba72ff4dca] WebGLRenderer: Convert to power of two textures that require it instead of giving wrap/minFilter warnings.

**Comment by WestLangley** [comment]
@mrdoob Here is a r.74dev [fiddle](http://jsfiddle.net/6e4weqew/) that reproduces the problem.

If the HUD is not a power-of-two, the text does not update.

**Comment by mrdoob** [comment]
> @mrdoob Here is a r.74dev [fiddle](http://jsfiddle.net/6e4weqew/) that reproduces the problem.

Thanks!

**Comment by mrdoob** [comment]
Fixed! http://jsfiddle.net/6e4weqew/2/
