### ISSUE TITLE
Add function getMode() in TransformControls.js

### ISSUE THREAD

**Issue by neeravbm** [mrdoob/three.js#7878]
Instead of having three separate buttons for translation, rotation and scaling, I would like to iterate between nothing, translate, rotate and scale operations by clicking on the object. function getMode() is necessary for this to work. It's as simple as return _mode.

**Comment by mrdoob** [comment]
Seems like this has been implemented already. https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TransformControls.js#L740-L744
