### ISSUE TITLE
MeshFaceMaterial doesn't support materials with and without texture together

### ISSUE THREAD

**Issue by neeravbm** [mrdoob/three.js#7880]
I would like to create a mesh with MeshFaceMaterial. Some materials have texture with UV mapping while some have plain color and no texture. It seems threejs is merging vertices and vertexUvs from different materials into two common arrays. As a result, the number of vertexUvs don't always match the number of vertices although each material is correctly specified. I am getting the following warning:
THREE.DirectGeometry.fromGeometry(): Undefined vertexUv  2

Can this even be solved using MeshFaceMaterial or is creating different meshes and grouping them using THREE.Group a better approach?

**Comment by neeravbm** [comment]
I couldn't find any example of Stackoverflow which uses MeshFaceMaterial with multiple materials, some with texture and some without. If you know of any, can you provide me with a link?

**Comment by doitonlinemedia** [comment]
Have you found a solution? 
I'm just getting started with threejs and 3D models and getting this error.

**Comment by mrdoob** [comment]
Hmm, this shouldn't be an issue any more... @doitonlinemedia do you have a example?

**Comment by doitonlinemedia** [comment]
I have a quite large object from a 3th party company that I have converted to a json file with `convert_obj_three.py`. The file is about 86MB. 

The code I use to generate the object.
```
 var scene = new THREE.Scene();
    var camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 1, 10000 );
    camera.position.z = 1000;

    var loader = new THREE.JSONLoader();
    loader.load('object_low.json', function ( geometry, materials ) {
        var geometry = new THREE.BufferGeometry().fromGeometry( geometry );
        var mesh = new THREE.Mesh( geometry, materials );
        scene.add( mesh );
        renderer.render( scene, camera );
    });

    var renderer = new THREE.WebGLRenderer({antialias: true, logarithmicDepthBuffer: true});
    renderer.setSize(window.innerWidth, window.innerHeight);
    document.body.appendChild(renderer.domElement);
```

This gives the warning: `three.js:13433 THREE.DirectGeometry.fromGeometry(): Undefined vertexUv  374292`

This warning is given about a few hundred times before the browser tab fully crashes and comes with the chrome message: "Aw, snap".

**Comment by mrdoob** [comment]
That's an old converter. Can you try with the `obj2three.js`?

https://github.com/mrdoob/three.js/tree/dev/utils/converters
