### ISSUE TITLE
Android 5.0 threejs crash

### ISSUE THREAD

**Issue by Critical-Li** [mrdoob/three.js#7881]
Hi, 
I firstly open this official sample http://threejs.org/examples/canvas_geometry_birds.html, it OK. but when I switch to other apps and switch back,  it show only black screen.  it does not every times. it seems the more apps I opened the more it happened. 

This does not appear before.  this happened when I upgrade my system to Android 5.0. IOS is OK. and Android 4.x is OK

Any idea?

**Comment by Critical-Li** [comment]
this happened when I upgrade my system to Android 5.0. IOS is OK. and Android 4.x is OK

**Comment by mrdoob** [comment]
Not really. `CanvasRenderer` is kind of deprecated though. The more WebGL is supported the more `CanvasrRenderer` is no longer relevant.

**Comment by Critical-Li** [comment]
Thanks Mr. Doob, 

We find some Android system cannot use WebGLRenderer. for example http://threejs.org/examples/webgl_geometry_cube.html. 
So we have to use CavasRenderer instead.  As we tested in many phones. it seems version of WebGL GL 1.0 (ES 3.x  xxx)  has this issue and version of WebGL 1.0( ES 2.x xxx) is OK.

What's the problem?

**Comment by mrdoob** [comment]
What phones are those?

**Comment by vinjn** [comment]
Can you view webgl content from https://get.webgl.org/ on these problematic phones?
