### ISSUE TITLE
Uncaught TypeError: THREE.Vertex is not a function

### ISSUE THREAD

**Issue by p4ulolol** [mrdoob/three.js#7884]
Hi,

I'm currently following this tutorial : https://aerotwist.com/tutorials/creating-particles-with-three-js/

But just with the first code (in a well setup Three.js environment), I just get this error : Uncaught TypeError: THREE.Vertex is not a function.

Can you tell me why ?

**Comment by WestLangley** [comment]
Avoid outdated books and tutorials, and avoid examples from the net that link to old versions of the library.

**Comment by makc** [comment]
@WestLangley 

> avoid examples from the net that link to old versions of the library.

which is like... 90% of them? only those in the repo are up to date. maybe.

**Comment by mrdoob** [comment]
Well, `Vertex` has been gone for a really long time. Maybe 4 years? However, I'll add to Three.Legacy.js.
