### ISSUE TITLE
OBJMTLLoader imported Obj issue

### ISSUE THREAD

**Issue by IRog** [mrdoob/three.js#7894]
An exported item (obj/mtl) which uses a node created from maya isn't being imported into three.js correctly. The final rendered object doesn't show the fill I put into it via the mesh fill tool (I compared this with other obj viewers, where it does show). I have included this example (https://github.com/IRog/obj_three_displayer/blob/threeIssue/client/obj/boots_filled.obj). This issue occurs when using the OBJMTLLoader (everything else seems to work and display correctly.)

see https://github.com/IRog/obj_three_displayer/tree/threeIssue for a working example

**Comment by makc** [comment]
they killed OBJMTLLoader in dev branch

**Comment by IRog** [comment]
Is there an alternative?

**Comment by makc** [comment]
also, your file has [polys with > 4 vertices, that will be ignored](https://github.com/mrdoob/three.js/issues/7890).

**Comment by IRog** [comment]
I triangulated my model, before export, and it fixed the issue. Thanks!
