### ISSUE TITLE
dev/editor camera settings are bad

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#7898]
Not a huge problem, I guess, but did you notice?

![screen shot 2016-01-03 at 1 40 03](https://cloud.githubusercontent.com/assets/242577/12076834/f230895c-b1bd-11e5-8859-ef6ad9677b38.png)

**Comment by mrdoob** [comment]
Hmm, what steps reproduce this? The scale of the default scene (thus camera) has changed.

**Comment by makc** [comment]
I just open the editor and see this.

**Comment by mrdoob** [comment]
Does it still happen after doing `File/New`?

**Comment by makc** [comment]
I can no longer reproduce this :ghost:
