### ISSUE TITLE
KeyframeTrack.trim() specification

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#7900]
@mrdoob 

Just curious to know about KeyframeTrack.trim() specification in r74 dev.
The following two behaviors are what you expected?
As of me, it looks weird that the result if time=0 element is trimmed or not depends on times.elements num.

	var times = [0];
	var values = [1];
	var key = new THREE.KeyframeTrack('name', times, values);
	key.trim(0, 1);
	>>> key.times: [0], key.values: [1]

	var times = [0, 0];
	var values = [1, 1];
	var key = new THREE.KeyframeTrack('name', times, values);
	key.trim(0, 1);
	>>> key.times: [], key.values: []

Or it isn't trim() issue but KeyframeTrack.optimize() (which is called in KeyframeTrack constructor) issue that it should let times, values = [0,0], [1,1] be times, values = [0], [1] but it doesn't ?

**Comment by tschw** [comment]
Somehow this routine has a tradition of being broken. Fixed `master` in #7930, rewritten `dev` version in #7931.

**Comment by mrdoob** [comment]
Thanks guys!
