### ISSUE TITLE
PLY loader example does not work on Chromium Browser

### ISSUE THREAD

**Issue by MalikKeio** [mrdoob/three.js#7904]
The PLY loader example does not work on my version of Chromium: `Chromium 47.0.2526.73 Ubuntu 15.10`, however it works on the same laptop on `Mozilla Firefox 43.0`. My graphic card is an integrated `Haswell-ULT Integrated Graphics Controller`.

http://threejs.org/examples/webgl_loader_ply.html

The following error is thrown:

    THREE.WebGLShader: gl.getShaderInfoLog() fragment 0:89(62): error: sampler arrays indexed with non-constant expressions are forbidden in GLSL 1.30 and later

**Comment by MalikKeio** [comment]
After some investigation, it seems that when `receiveShadow = true`, shader compilation crashes on Chromium. It works well after I commented these lines out as below:
https://github.com/MalikKeio/three.js/commit/8aa66dda9dee2c60c83b50bdadb572a011fb0210

**Comment by mrdoob** [comment]
Hmmm, are you sure that's not with the `dev` version?

**Comment by MalikKeio** [comment]
I tried with the latest `master` and the latest `dev` version on my own PC and for both I see the same bug on Chromium browser.

This commit https://github.com/MalikKeio/three.js/commit/8aa66dda9dee2c60c83b50bdadb572a011fb0210 is on top of the latest `master`.

As for this link: http://threejs.org/examples/webgl_loader_ply.html , I do not know which version it is but it does not work on my PC anyway.

**Comment by mrdoob** [comment]
Hmm... I can reproduce on my linux machine.

**Comment by mrdoob** [comment]
Seems like this is a bug in Chrome itself, which has already been fixed in Dev. Hopefully they'll backport to Beta.

http://crbug.com/550487
