### ISSUE TITLE
 collada that works with .73 collada loader, fails with collada2, dec31 dev branch, and json too

### ISSUE THREAD

**Issue by izatar** [mrdoob/three.js#7908]
I have attached a .dae model that loads and renders correctly with the latest (73) collada loader, but which seems to have its textures garbled in the collada2 loader, and also loader from the dev tree on dec31.
Also, the JSON file created from the .dae file at clara.io today (jan 3) (also attached) renders incorrectly with the 73 json loader in a similar way, which might be some kind of clue?

I think this is important because the 73 collada loader scambles objects that are loaded with matching mesh names; this is fixed in the later loaders, but then they don't render this file correctly, so at this time there is no single version of collada loader that works 100% correctly. (I might note that with my searches about the collada issue I have see, it just may be that these issues may go back to day one)

[thewell.zip](https://github.com/mrdoob/three.js/files/77040/thewell.zip)

**Comment by mrdoob** [comment]
`ColladaLoader2` now loads the file properly.

![screen shot 2016-01-10 at 13 48 02](https://cloud.githubusercontent.com/assets/97088/12221791/1cebb5e8-b7a1-11e5-993e-e38f61b5d504.png)

Thanks for the model!

**Comment by izatar** [comment]
wow now that's what i call service! sweet!
