### ISSUE TITLE
VTK loader silently fails on binary files

### ISSUE THREAD

**Issue by mhelvens** [mrdoob/three.js#7909]
Hi there,

I tried to load a VTK file with [VTKLoader](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/VTKLoader.js). As it turns out, my file is *binary* encoded VTK, and the loader expects *ascii*. It accepts my file without error and spits out an empty geometry.

Unfortunately I cannot publicly share this file. But I can tell you that your example file starts with:
```
# vtk DataFile Version 3.0
vtk output
ASCII
```
and my file starts with:
```
# vtk DataFile Version 3.0
VTK File Generated by Insight Segmentation and Registration Toolkit (ITK)
BINARY
```
So it shouldn't be too difficult to at least check and throw an error. If you could implement a binary loader, though, even better!

**Comment by mrdoob** [comment]
Do you have any other sample file we can use as reference? Maybe create one?

**Comment by mhelvens** [comment]
I did a quick search. A bunch of sample files can be found on [earthmodels.org](http://www.earthmodels.org/software/vtk-and-paraview/vtk-file-formats). The binary samples can be found a bit down the page. (In any case, it looks like a very useful page for anyone who wants to implement this loader.)

It also occurs to me that the fact that my file is binary is not necessarily the reason it doesn't render. There appear to be many different vtk formats.

**Comment by NicolasRannou** [comment]
For reference about the VTK file format:
http://www.vtk.org/wp-content/uploads/2015/04/file-formats.pdf

It would be great to see it supported, especially for the researchers community.

**Comment by stity** [comment]
I would like to back up the feature request : binary files are twice lighter and parsing using xhr binary data is lot faster than parsing a string.
All in all it would result in a great speed improvement

**Comment by dvenkatsagar** [comment]
+1

**Comment by stity** [comment]
See https://github.com/mrdoob/three.js/pull/8208
