### ISSUE TITLE
OBJLoader does not load OBJ files with multiple meshes.  Suggested fix is here:

### ISSUE THREAD

**Issue by schubboy** [mrdoob/three.js#7910]
the OBJLoader does not correctly load OBJ files with multiple meshes due to broken parser for the OBJ file.  Essentially, the OBJLoader checks for the character literal "o" to denote an object, but an OBJ file can also have the entire word "object" as well.  Additionally, the code that checks for an empty comment line "#", incorrectly identifies "# object " as a comment line, instead of recognizing it as a object definition line.

This is the suggested code fix which is working well for our company: 

Line 227of OBJLoader.js: change from:
     if ( line.length === 0 || line.charAt( 0 ) === '#' ) {
to: 
     if ( line.length === 0 || /^#\r?\n?$/.test(line)) {

Line 297 of OBJLoader.js: change from :
     } else if ( /^o /.test( line ) {
to: 
    } else if ( /^o /.test( line ) || /# object /.test(line) ) {

**Comment by makc** [comment]
> /# object /.test(line)

Looks like #6682

**Comment by schubboy** [comment]
You are correct, it is indeed that issue. I disagree completely with RemusMar.  The THREE loader is written to create multiple meshes, so regardless of the opinion on whether or not it SHOULD do so, the actual loader code is incorrect, and should be updated to do what it was written to do.

Oh, and we are using 3DSMax's exporter to create this OBJ file.
