### ISSUE TITLE
Non Linear Animation 

### ISSUE THREAD

**Issue by derivou** [mrdoob/three.js#7913]
Hi, I tried to start this issue in #6050 but as there is no assignee I guess it's stopped. My proposal is to discuss means to make NLA editing using the three.js api and with object exported from Blender. My understanding of the siituation so far is that the point has not yet been adressed and after looking into the blender exported json files and into Animation.play (and Animationhandler.update) I guess NLA is currently not possible as there is nothing to differentiate bones which are animated from those which are not. Could there be an initial disucssion between "blender export" and "Animation functions" to identify how this could implemented  ?

**Comment by tschw** [comment]
In https://github.com/mrdoob/three.js/issues/6050#issuecomment-210905743 @derivou wrote:
> I would be happy to help developping but I think it requires first some discussions to share ideas and discuss on how to implement it.

This sounds great! 

I have good news for you too, well partly: `AnimationHandler` is pretty much dead. 

The new class is called [`AnimationMixer`](https://github.com/mrdoob/three.js/blob/master/src/animation/AnimationMixer.js). It has been introduced in `r73` and was further extended in `r74`. 

The following examples are the ones to look at

http://threejs.org/examples/#webgl_animation_scene
http://threejs.org/examples/#webgl_animation_skinning_blending
http://threejs.org/examples/#webgl_animation_skinning_morph (*)
http://threejs.org/examples/#misc_animation_authoring

(*) contains a GUI to play with the scheduling API.

It should already be fit to handle the case you describe in https://github.com/mrdoob/three.js/issues/6050#issuecomment-180258285 when making the exporter omit the non-moving bones. However, although the current version provides several scheduling features, `AnimationMixer` does not implement a full sequencer, as I guess might be needed for handling the general case (see https://github.com/mrdoob/three.js/pull/7312#issuecomment-209473262).

**Comment by derivou** [comment]
Thank you for these good news. I will follow what's going on with AnimationMixer, see how much I can take benefit from it and make comments when enough progress on my side. 
Thanks !!

**Comment by tschw** [comment]
Cool! Let me know when you know what you're up to. In particular let me know when you intent on extending the file format, in that case I'll invite Ben to this discussion, who knows most authoring tools out there at a level of intimacy (I myself don't).

**Comment by donmccurdy** [comment]
Is there more to do on this issue? I'm not sure of the state of Blender Exporter NLA exports, but interpolation with the new animation system is working nicely.

For GLTFLoader we've implemented a custom interpolant with control points, which should match Blender's bezier curves. The [glTF-Blender-Exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter/) supports exporting a single action with nonlinear interpolation, but ignores NLA tracks. If anyone is familiar with Blender enough to contribute that NLA support and/or multiple actions, that would be a _very_ welcome addition. 🙂

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
