### ISSUE TITLE
Problem in WebGLRenderer on Chrome (dev branch)

### ISSUE THREAD

**Issue by rfm1201** [mrdoob/three.js#7914]
Hi, I have an issue with the current dev version of WebGLRenderer on Chrome (47.0.2526.106 m) but not on Firefox or IE 11. I know that the problem is liked with the current WebGLRenderer version because if I build a three.js version with the last WebGLRenderer I have (December 17, changing THREE.Rectangle to THREE.Vector4 on the _viewport definition), it works.

I get the following error :
[GroupMarkerNotSet(crbug.com/242999)!:84DFD405]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: <- error from previous GL command

I have a JSfiddle that shows the problem https://jsfiddle.net/fuvuxkvr/1/.
The middle mesh uses its own canvas in its texture.
The two other use the same canvas in their texture, with different mapping.
Try to draw a line in the different meshes using your mouse, it won't work on the one to the left.
The problem is always on the first mesh added to the scene, the plane on the left with this code.

I don't know if the problem is in my code or in WebGLRenderer but I think it may be in WebGLRenderer.

**Comment by makc** [comment]
no error in chrome 49.0.2606.0 canary (64-bit)

**Comment by rfm1201** [comment]
I tested with the 47.0.2526.106 m (64-bit) and have the same problem, but you are right it works on 49.0.2613.0 canary (64-bit).
Hope it will work on the 48 because my main users use chrome released version.

**Comment by rfm1201** [comment]
It works on 48.0.2564.48 beta-m (64-bit).
I just have to wait for the 48 to be released.
