### ISSUE TITLE
.visible = true render delay

### ISSUE THREAD

**Issue by poof86** [mrdoob/three.js#7915]
There seems to be a delay (seconds or less) after setting the **.visible** property of an object to **true** and the object actually being rendered. This delay is shortened after changing the property more than once.

What is the cause of this delay? Is there a way to know when the object is ready for rendering? it doesn't seem like update events are being fired after setting the .visible property to true, so listening for those won't help.

I appreciate any help with this issue.

**Comment by poof86** [comment]
But this is not just my issue but an issue/bug in three.js engine is it not?

**Comment by WestLangley** [comment]
Let's first determine what you are actually doing.

http://stackoverflow.com/questions/34616054/three-js-object-visible-true-not-showing-up-right-away
