### ISSUE TITLE
WebGLRenderer version in console

### ISSUE THREAD

**Issue by SET001** [mrdoob/three.js#7923]
Why it is so necessary to have WebGLRender version printed to the console?

```
THREE.WebGLRenderer = function ( parameters ) {

	console.log( 'THREE.WebGLRenderer', THREE.REVISION );
```

I'm writing a unit-tests for my engine and this output just make a lot of noise.

**Comment by fraguada** [comment]
You can comment it out no?

**Comment by SET001** [comment]
Sure I can and now it is commented here. But modifying vendor files is a pretty bed idea. Also I have threejs installed from bower in few places and I now should track all this changes.
From the other side - why should vendor library make any console output?
There may be `console.log` in dev version which may be automatically removed while deploying to master or something like that.

**Comment by WestLangley** [comment]
This issue has been discussed in #5835 and possibly elsewhere.
