### ISSUE TITLE
Stream three.js large geometry

### ISSUE THREAD

**Issue by guptasagar** [mrdoob/three.js#7924]
Hi,

I have large model of more than 2 million vertices. I want to stream it using three.js from remote url.
Currently I am using BufferGeometry for loading it which loads it in one shot.

Is there any loader in three.js which can progressive load model. Any other approach will also work.

I am able to load any type of data(obj, stl or json triangles).

Regards
Sagar

**Comment by makc** [comment]
why don't you just do 2-3 models of the same thing and load one by one from lowest lod to highest.

**Comment by WestLangley** [comment]
http://stackoverflow.com/questions/34659765/stream-large-models-in-three-js
