### ISSUE TITLE
Feature request - getAngle method inside THREE.Vector2

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#7925]
I use `THREE.Vector2` for direction vectors. It would be great to make a simple method to get the angle in radians. 

![image](https://cloud.githubusercontent.com/assets/2419627/12177832/795ff8d2-b56e-11e5-9400-e3faf71340bf.png)

This method could look like this:
````
/**
 * Get angle from Vector2
 *
 * @return {number}
 */
THREE.Vector2.getAngle = function() {

    return Math.atan2( this.y, this.x );

};
````

Maybe it would be also cool to add an `angleTo` method like in `THREE.Vector3` for consistency in the Vector2 and Vector3 API .

**Comment by WestLangley** [comment]
`Math.atan2( - 1, 1 )` is negative, so the behavior of `getAngle()` may be unexpected to users.

**Comment by mrdoob** [comment]
@WestLangley is there a workaround for that?

**Comment by WestLangley** [comment]
The angle _between_ 2D vectors is well-defined if you define it to be the smaller of two options -- and define it to be positive. (It could be signed, actually.)

But `getAngle()` when providing only one vector is not, necessarily. What should the other vector be? The positive-x axis or, as in heading, the positive-y axis? Measured clockwise, or counter-clockwise? Radians or degrees? The correct answer to me seems to be application-specific.

**Comment by Wilt** [comment]
normally the angle is 0 for direction `direction = THREE.Vector2( 1,0 );`

Meaning -1,0 should give Math.PI  (- Math.PI or even 3 * Math.PI it is all the same angle).

**Comment by Wilt** [comment]
In `angleTo` to the user could provide another direction (`THREE.Vector2`) as an argument. If not provided the default `(1, 0)` is used...

**Comment by WestLangley** [comment]
We could define `getAngle()` to return the angle in radians with respect to the positive x-axis.

```javascript
THREE.Vector2.prototype.getAngle = function() {

	var angle = Math.atan2( this.y, this.x );

	if ( angle < 0 ) angle += 2 * Math.PI;

    return angle;

};
```

Users who are interested in heading will want a different definition, however.

@wilt What is your use-case for this method?

**Comment by Wilt** [comment]
My user case... I am drawing a curve with: 

`new THREE.ArcCurve( position.x, position.y, radius, startAngle, endAngle, clockwise );`

The curve definition comes with a placement (position and direction), radius and an angle.
The direction is the starting angle for the curve. So if the placement direction is for example `( 1, 0 )` it means the `startAngle` is `0`. So a curve with `angle = 1` would look like this:

![image](https://cloud.githubusercontent.com/assets/2419627/12177832/795ff8d2-b56e-11e5-9400-e3faf71340bf.png)

But if the placement direction is for example `( 0, 1 )` it means the startAngle is `Math.PI / 2`. So a curve with `angle = 1` would look like this:

![image](https://cloud.githubusercontent.com/assets/2419627/12290466/389a0702-b9e2-11e5-9672-c6d7dbea1168.png)

**Comment by WestLangley** [comment]
@Wilt How about `getAngle()` as I proposed above?

**Comment by Wilt** [comment]
@WestLangley Awesome. You won't hear me complaining if you implement that :+1:

**Comment by WestLangley** [comment]
Done. Named new method `angle()`.

**Comment by Wilt** [comment]
Thanks @WestLangley cool that we can use this feature now, very nice.

**Comment by luisgurmendezMLabs** [comment]
@Wilt why this wasn't implemented as angleTo?

**Comment by WestLangley** [comment]
@luisgurmendezMLabs So as not to confuse it with `Vector3.AngleTo( v )`
