### ISSUE TITLE
STL-model transparency: disappearing of model parts

### ISSUE THREAD

**Issue by SimPru** [mrdoob/three.js#7929]
We have found a strange behaviour trying to enable transparency on a loaded .stl file.
The model we try to show consists many different components, some of them are visible when transparency is enabled, some are not.
Screenshot 1 shows the outside parts of the model, screenshot 2 shows that most of them disappear when hidden by a transparent part.

Transparency itself obviously works, but some parts somehow just disappear.
Our loader is based on the provided STL-loader but with some extensions regarding coloring.

Any suggestions on what could be wrong / what we are doing wrong or is this an issue with three.js itself?

Thank you for all your feedback!

![transparency_1](https://cloud.githubusercontent.com/assets/13440670/12173566/c9de0c48-b557-11e5-8232-2ccb53670673.jpg)
![transparency_2](https://cloud.githubusercontent.com/assets/13440670/12173567/c9de9ae6-b557-11e5-9368-bbbcc642522c.jpg)

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
