### ISSUE TITLE
Make videos work on mobile

### ISSUE THREAD

**Issue by joshkpeterson** [mrdoob/three.js#7932]
http://threejs.org/examples/#canvas_materials_video

When viewing the example on mobile devices, all I see is a black rectangle where the video should be.

Chrome 47.0.2526.83 on Android 5.1.1 Samsung Note 5
Safari on iOS 9.0.2 on iPhone 6

There are no javascript errors when running this on Android Chrome.

A quick look at http://threejs.org/examples/webgl_materials_video.html gives similar results.

**Comment by MasterJames** [comment]
I can confirm that. Note 3 chrome. It seems similar to the time this has come up before and I was involved in the discussion. It was something to do with changes to simple materials I recall. ?

**Comment by joshkpeterson** [comment]
There's this issue open onew the vr library aframe, which is built on top of three.js:

https://github.com/aframevr/aframe/issues/316

Suggests it may just be that user action is required to make the video play on mobile. If so, the example could be updated to include this. Will report back for sure if I get some resolution from that end.

**Comment by mrdoob** [comment]
> Suggests it may just be that user action is required to make the video play on mobile.

That is correct.

> If so, the example could be updated to include this.

PRs more than welcome! 😊
