### ISSUE TITLE
clearColor doesn't work. Background is always black

### ISSUE THREAD

**Issue by arpo** [mrdoob/three.js#7933]
For hours I've been trying to set the background color of the render to anything different that black but without success. 
Is this an issue or am I doing something wrong?
See my codepe: 
http://codepen.io/arpo/pen/NxjBmJ
It uses r73

It's a copy of this JSFidle using r54 that works.
http://jsfiddle.net/arpo/0g3p4uoj/1/

**Comment by WestLangley** [comment]
renderer.setClearColor( 0x33Fc25, 1 );
