### ISSUE TITLE
WebGLRenderer setClearColor not functioning in dev branch with multiple cameras

### ISSUE THREAD

**Issue by paulmasson** [mrdoob/three.js#7935]
Compare the two examples:

https://rawgit.com/mrdoob/three.js/dev/examples/#webgl_multiple_elements
https://rawgit.com/mrdoob/three.js/r73/examples/#webgl_multiple_elements

The version in the dev branch has individual cameras per scenes and the clearColor is not getting set to white. Is this intentional or a bug?

**Comment by WestLangley** [comment]
The clear color is reset in the render loop.

    renderer.setClearColor( 0xe0e0e0 );

**Comment by paulmasson** [comment]
I should have been more specific. Setting the gray color inside the individual scenes works. Setting the white color outside the scenes does not, but remains the default black. This is not how r73 behaves.

**Comment by paulmasson** [comment]
Answered my own question. Need another global camera to set the page background. Sorry for the bother.

**Comment by WestLangley** [comment]
The clear color has nothing to do with the camera.

**Comment by paulmasson** [comment]
In the dev version of the example, how would you set the black background to white without having another camera to pass to the renderer? I have already verified that adding one more camera allows that change. Is there a better way to set the page background to white?

**Comment by MasterJames** [comment]
No shading on mobile in the first one?

**Comment by mrdoob** [comment]
As @WestLangley said, the issue is somewhere else. It has to do with the recent `scissor`/`viewport` refactoring. Looking into it...

**Comment by mrdoob** [comment]
Fixed! The `scissor`/`viewport` code is still a bit messy, but it's getting there...

**Comment by paulmasson** [comment]
@mrdoob Thank you sir!
