### ISSUE TITLE
Is there any ways to show shadow on transparent background (material)?

### ISSUE THREAD

**Issue by shellka** [mrdoob/three.js#7942]
Before r72 it works like in this example:
http://jsfiddle.net/shellka/fb81kpz5/1/
but now it doesn't work
http://jsfiddle.net/shellka/gg9nwas1/59/

Maybe im looking something wrong and now we have easier solution to do it ?

**Comment by WestLangley** [comment]
You are likely on the right track by hacking your own shader. I expect others would be interested in your solution on stackoverflow.
