### ISSUE TITLE
MTLLoader bump texture filename option(s) parsing Issue

### ISSUE THREAD

**Issue by kiraLinden** [mrdoob/three.js#7943]
I'm using the MTLLoader via the OBJMTLLoader and in my .mtl file I have a bump texture file. When the loader parses the definition (the line in the .mtl) it doesn't seem to drop the options from the filename that it is looking for i.e. the line `bump Thing_Norm.png -bm 1` in my .mtl has the filename parsed as `Thing_Norm.png -bm 1` The `-bm 1` isn't correctly dropped from the string, so the path isn't correct when it looks for the file. The output filename the MTLLoader looks for should be read as `Thing_Norm.png` with all options and args dropped. Could someone please look into this? (I could also look into the parser, if no one can look at this)

**Comment by mrdoob** [comment]
Just so you know, `OBJMTLLoader` has been removed in `dev`. We'll focus on `OBJLoader` and `MTLLoader`. 

Having said that, if you share the files you're working with I'll make sure they load correctly.
