### ISSUE TITLE
Broken link to an example on threejs.org

### ISSUE THREAD

**Issue by sasha240100** [mrdoob/three.js#7944]
Brokin link to an example on project's site.

![three js javascript 3d library](https://cloud.githubusercontent.com/assets/7657429/12246450/37094c94-b8b7-11e5-9cd1-c899343c6192.png)
**Link on site**: http://gisele.underarmour.com/
**Working link**: http://willbeatsnoise.com/

**Comment by mrdoob** [comment]
Feel free to fix the link directly 😊
https://github.com/mrdoob/three.js/edit/gh-pages/index.html

**Comment by sasha240100** [comment]
@mrdoob  Yep. Of course:) https://github.com/mrdoob/three.js/pull/7945
