### ISSUE TITLE
Unable to access documentation at threejs.org/docs/#....

### ISSUE THREAD

**Issue by atj1979** [mrdoob/three.js#7955]
I keep getting the following error in the console when I try to click anything in the menu bar on the left.

Refused to display 'http://threejs.org/docs/manual/introduction/Creating-a-scene.html' in a frame because it set 'X-Frame-Options' to 'DENY'.

This was not a problem earlier today for me.  

Thanks - I love the library, I didn't know where else to put this where it might get seen.

**Comment by bnjm** [comment]
I'm also receiving this error across browsers on OSX. http://threejs.org/docs/ loads without error but all the embedded content is blocked.
![screen shot 2016-01-13 at 5 05 06 pm](https://cloud.githubusercontent.com/assets/1694288/12284833/360562da-ba18-11e5-9a7c-668e39454fe9.png)

**Comment by jshuadvd** [comment]
Same issue for me!

**Comment by Stallion12** [comment]
Hey getting the same issue.....not working

**Comment by killerkaze** [comment]
http://threejs.org/docs/#Reference same issue here.

**Comment by xeolabs** [comment]
Yeah GitHub added the X-Frame-Options=DENY last night without warning. Breaks SceneJS and [xeoEngine](http://xeoengine.org/examples/#importing_gltf_buggy) examples browsers as well (those examples browsers are based off the code used in the THREE examples/docs browser). 

So we're [tracking the issue for xeoEngine](https://github.com/xeolabs/xeoengine/issues/31) as well. 

Might need to redesign the examples browsers to not rely on iframes (though not sure how we'd do that exactly). We'll let you know if we come up with anything.

**Comment by bnjm** [comment]
wow...can't believe they did that without warning. Almost worth moving the entire gh-pages branch to another host.

**Comment by xeolabs** [comment]
Probably a server update where that was set to default. Don't flame them just yet :)

**Comment by leitzler** [comment]
Yeah, it isn't the first time either :) https://twitter.com/mbostock/status/257933324406882304

**Comment by lazka** [comment]
I just got a response

```
Hi Christoph!

I am sorry about that. We are going to revert the change that affected GitHub Pages.

Cheers,
Petros
```

**Comment by vmg** [comment]
This was a misconfiguration as part of an ongoing security mitigation. We've rolled back the change and the Three.js documentation should be working again (as soon as the Fastly cache expires). Apologies for the inconvenience.

**Comment by bnjm** [comment]
Great news, thanks @vmg! Apologies for the pitchfork

**Comment by mrdoob** [comment]
Thanks @vmg!
