### ISSUE TITLE
[Blender exporter] incorrect material colors

### ISSUE THREAD

**Issue by alexus85** [mrdoob/three.js#7962]
Not sure why it's happening , but when I export the same model, with exactly the same materials using old and new blender exporter , I get different material colors. 

version of old blender exporter : **1, 4, 0**
version of new blender exporter : **1, 5, 0**

version of blender **2.76b**

I'm not going to put the whole exported object here , just two material examples each exported by different blender exporter, so you can see the difference.

exported by **new** blender exporter:
```
{
        "DbgIndex": 0,
        "colorSpecular": [0.247368,0.247368,0.247368],
        "depthTest": true,
        "visible": true,
        "wireframe": false,
        "colorDiffuse": [0.83531,0.911393,0.853969],
        "colorEmissive": [0,0,0],
        "specularCoef": 50,
        "opacity": 1,
        "colorAmbient": [0.83531,0.911393,0.853969],
        "shading": "phong",
        "depthWrite": true,
        "DbgColor": 15658734,
        "transparent": false,
        "blending": "NormalBlending",
        "DbgName": "base"
    }
```

exported by **old** blender exporter:
```
{
		"DbgColor" : 15658734,
		"DbgIndex" : 0,
		"DbgName" : "base",
		"blending" : "NormalBlending",
		"colorDiffuse" : [0.8353104591369629, 0.9113926887512207, 0.8539685010910034],
		"colorSpecular" : [0.24736842513084412, 0.24736842513084412, 0.24736842513084412],
		"depthTest" : true,
		"depthWrite" : true,
		"shading" : "Lambert",
		"specularCoef" : 50,
		"opacity" : 1.0,
		"transparent" : false,
		"vertexColors" : false
	}
```

With regards to the new exporter settings , everything is set to default except for the Face Materials option, in Shading section.

**Comment by alexus85** [comment]
I have investigated the both results and it turned out that the **new** exporters os implicitly setting the shading to "Phong", even though it's explicitly defined in the object's material, that the shading should be  Lambert.

**Comment by alexus85** [comment]
I have ntoiced that for some reason the exporter implicitly changes the shading to "Phong" ,even though it's explicitly defined in object materials as "Lambert". But changing the option didn't make any difference.

**Comment by alexus85** [comment]
well it turns out that the solution itself is very simple and weird at the same time... when I placed the **DbgColor** at the first position everything was fine.  Now the question is, does the option order really matter? If so why does the exporter not place the options in right order then?

**Comment by mrdoob** [comment]
#7401

**Comment by alexus85** [comment]
yeah just realized that there are missing break points in **createMaterial** method in Loader the object. Adding the break points fixed the problem .
