### ISSUE TITLE
directional light pointing doesn't seem to be working

### ISSUE THREAD

**Issue by JamesLawrenceGSI** [mrdoob/three.js#7965]
I've posted on SO but for the last 2 weeks haven't had a response so I'm trying here instead. 

I can't seem to get directional lights to point at anything other than 0,0,0 in r73:

    var directionalLight = new THREE.DirectionalLight( 0xffffff );
	directionalLight.position.set( 10, 10, 10 );
	directionalLight.target.position.set(100, 100, 100);
	directionalLight.intensity = 0.5;
	directionalLight.castShadow = true;
	directionalLight.shadowCameraLeft = -30;
	directionalLight.shadowCameraRight = 30;
	directionalLight.shadowCameraTop = 30;
	directionalLight.shadowCameraBottom = -30;
	directionalLight.shadowCameraNear = 0;
	directionalLight.shadowCameraFar = 100;
	scene.add(directionalLight);

	var helper = new THREE.DirectionalLightHelper( directionalLight );
	scene.add(helper);

The helper shows the light is still pointing at 0,0,0, despite the call to target.position.set().

To create a shadow rendering range system, I wanted the directional light to follow the user camera, I can't do this and keep the angle constant if the target function isn't working.  Any ideas?

**Comment by WestLangley** [comment]
Improve your SO question if you are not getting a response.

**Comment by JamesLawrenceGSI** [comment]
Thanks for the insulting response.  However I put it here not because I wasn't getting a response on SO per say, but because I assume the problem could be an actual issue with r73.  Thanks for further disillusioning me with three.js.

**Comment by WestLangley** [comment]
@JamesLawrenceGSI Sorry. I did not mean to be insulting. I could have worded that better. I did go to SO to try to find your original post so I could help you. If you post on SO, I'll be glad to help you there.

**Comment by WestLangley** [comment]
@JamesLawrenceGSI Also, https://github.com/mrdoob/three.js/issues/5555#issuecomment-61390208 may be related to your issue.

**Comment by JamesLawrenceGSI** [comment]
Ok no problem, water under the bridge! :)  Though just in case you do have an insight into this, my SO post is here:  http://stackoverflow.com/questions/34571289/shadow-range-for-directional-lights-in-three-js.

**Comment by WestLangley** [comment]
Answered on SO.
