### ISSUE TITLE
Ability to change microfacet model in Standard material: GGX, Blinn, Ward, Phong

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#7966]
With the standard material it is now possible to match UE4's materials pretty closely.  But some other tools and renderers use Blinn-based microfacet models, rather than GGX-based microfacet models.  I've experimented a bit trying to convert between the two via parameters, e.g. blinnGlossinessExponent -> ggxRoughness, but these conversions are always pretty poor and do not modify the texture input at all.

Thus I was wondering if we wanted to make the microfacet distribution model a parameter on the Standard material.  The default would be GGX as it is now, but we could switch it to Bliin or Phong or Ward.

I understand this may be esoteric for most people but I'm trying to achieve perfect matches between renderers, and this is necessary for that sort of thing.

**Comment by WestLangley** [comment]
I believe there was general agreement to add a new, more advanced, material tentatively called `MeshPhysicalMaterial`. We could add your feature there if @mrdoob wants to keep `MeshStandardMaterial` simple. Just a thought...

Also, the other illumination models you referenced have different parameters, so the material API would need the additional parameters, too. That's unfortunate...

**Comment by bhouston** [comment]
@WestLangley, you are probably right, I should just build this into the node material system.

**Comment by WestLangley** [comment]
`NodeMaterial` needs a nice GUI. : - )

**Comment by bhouston** [comment]
Also, I do not think we need a ```MeshPhysicalMaterial``` at this point, as ```NodeMaterial``` basically fulfills that need.

**Comment by WestLangley** [comment]
OK with me.

**Comment by WestLangley** [comment]
Can this issue be closed, then?

**Comment by mrdoob** [comment]
> `NodeMaterial` needs a nice GUI. : - )

+1

> Also, I do not think we need a ```MeshPhysicalMaterial``` at this point, as ```NodeMaterial``` basically fulfills that need.

Yay!
