### ISSUE TITLE
TrackballControls experience

### ISSUE THREAD

**Issue by f4bsch** [mrdoob/three.js#7970]
The TrackballControls rotation is brocken with non-linear behavior, leading to unnatural experience. See this short video 

[![Vid](http://f4bsch.github.io/trackball-testing/video/1.jpg)](http://f4bsch.github.io/trackball-testing/video/1.mp4)

As you can see, when moving the mouse cursor slowly, it makes the objects move bumpy, but still that the top of the pyramid stays close to the cursor. When moving faster, the control is much slower and smoother.
This is because the implementation integrates over integer values, summing up the rounding errors.

Try out these 3 trackball demos, they all use different versions of the three.js TrackballControls. Guess which one is the current version:
http://f4bsch.github.io/trackball-testing/
(Note: works on a desktop, not mobile yet because of missing implementation. You cannot leave the iframes while dragging. Compare rotation only, panning/tzoom is nearly the same)

I think that the first one feels not good. The second example is the TrackballControls from [almost a year ago](https://github.com/mrdoob/three.js/blob/fe8493157ef764bb4ca10e3f48dfbec4881acf8a/examples/js/controls/TrackballControls.js).

The trackball class can be considered as broken. While features were added other control method suffered, because the input model was changed in favor of the new input method. The worst thing is that these new intput methods were finally removed. Now we have a control that behaves completly unexpected and far from natural experience. I see all the three.js examples where the dynamic damping was disabled, because it is broken, and a static control gives a better experience. (Might be a little critic to contributors because of the degradation.)

I spend some time on this code, and spotted a few issues. Before joining the pull request line, I'd like to share want I found out:
- There is a single damping model, but there should be 2: one while holding/tapping and one if the control is released
- Integration over the mouse path is not a good idea (integer rouding errors). In the video you can see non-linear behavior.
- the control implementation strongly depends on input update rate of the current browser, hardware or OS. This can lead to completly different behavior on mobile devices compared to desktops for example
- Minor: 
  - some unnecessary vector operations like `norm(cross(norm(A), norm(B)))` or `norm(A).setLength(l)`
  - implict conversion of floats to a boolean value (should use epsilon)

The 3. demo is my new implementation. I reverted to the previous input model with modifications, where we store the start vector on mousedown in lets say `S`, then calculate the difference while updating `S` so it follows the cursos (damped). The difference is assumed to be our angle, which we use for object rotation. Damping also depends on the state, wether the trackball is hold or released.

Still, this is not an exact implementation of a real control that behaves equally on all devices. A more exact implementation would normalize the mouse movement with the input sample rate (wich is something about 125Hz on Chrome&Windows) to get a velocity samples/second. This can then be used in the update function, mulitplied by frame time. We can ignore this because there is no frame time passed to the update function and this is not a first person shooter ;-).

Some things I'd just like to mention for the sake of completeness:
- The angle in rotateCamera is not actually an angle. Its a distance, and if this is very small it is an aproximation to an angle. This is a usal approach, but can prevent a control from behaving linear.
- The term damping is not 100% correct regarding the implementation. There should be a coupling between the mouse position and the "trackball" (like a spring). While moving the trackball we like to have a [critical damping situation](https://en.wikipedia.org/wiki/Damping#Critical_damping_.28.CE.B6_.3D_1.29) like a car suspension should be. A critical damped system is 2nd order and requires at least 2 parameters.

So before spending more time on this to create a PR, I'd like to get some input.

**Comment by mrdoob** [comment]
Sounds good to me! 👍

**Comment by jwdunn1** [comment]
@f4bsch: Your three trackball tests do not share equal initialization parameters: e.g. the "current" version of elegans.js sets rotateSpeed = 10 at line 462, while the "prev" and "mine" versions use a much lower value. The larger value amplifies the jitters. I've not had any problems with the present version of TrackballControls...it moves much like the PeasyCam library for Processing. The term "damping" in both of these libraries simply means friction applied to 'ease' the rotation when the mouse is released.

**Comment by Mugen87** [comment]
@f4bsch Closing. If you like to improve `TrackballControls`, just create a PR and the community can discuss the changes there.
