### ISSUE TITLE
Is there an archive of the featured projects?

### ISSUE THREAD

**Issue by danielalam** [mrdoob/three.js#7981]
Hi,

I saw this absolutely stunning graph visualization under the featured projects section a few months ago. It's not there anymore and unfortunately I didn't bookmark it. I could not find it on https://plus.google.com/+ThreejsOrg/posts either.

Is there an archive of the featured projects where I could find it? 

Thank you

**Comment by theo-armour** [comment]
Go to the gh-pages branch, click on the releases icon and scroll through to see if you find what you are looking for. Or edit the release number as follows

https://github.com/mrdoob/three.js/tree/r70

The names of featured projects are in index.html
