### ISSUE TITLE
Bug in audio class

### ISSUE THREAD

**Issue by Roam-Cooper** [mrdoob/three.js#7983]
For Audio.Stop it does:

this.source.stop();
this.startTime = 0;

It should do:
this.source.stop();
this.startTime = 0;
this.isPlaying = false;

**Comment by vincent-courtalon** [comment]
doesn't  'onEnded' function is called when we call Stop?
i assumed it was (maybe it is called only when we reach the end of the buffer without ourselves calling stop...)
[mozilla doc on onEnded](https://developer.mozilla.org/fr/docs/Web/API/AudioBufferSourceNode/onended)
it is not absolutely clear in the documentation. If needed, i can quickly test it this coming week-end (but if you have a fiddle illustrating the problem it would be great...)

**Comment by vincent-courtalon** [comment]
I just tested it on chrome and firefox (both on linux), and it worked, it called onEnded as expected.
It just work for me. Without any more info or an example, i can't say more (i have not tested on IE).

**Comment by vincent-courtalon** [comment]
wait a minute, i thnik i found the problem
```javscript

THREE.Audio.prototype.onEnded = function() {
	this.isPlaying = false;
};
```
is a callback called from the navigator....maybe "this" isn't set correctly
let me check it

**Comment by Mugen87** [comment]
I think we can close this issue. Placing `this.isPlaying = false;` in the `stop` method is not a good idea , because the `onended` event handler is executed in both cases, when user call `stop` **or** if the audio track has just finished its playback.

**Comment by vincent-courtalon** [comment]
I agree. I don't think there actually is a bug in this case, unless someone has an exemple.
