### ISSUE TITLE
Feature Request - Get points (corners) of Box3 with public method

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#7985]
It would be great if it would be possible to get the points/corners from a `THEE.Box3` using a single method. The thing is that [the code is actually already inside the `THREE.Box3` object prototype inside the `applyMatrix4` method](https://github.com/mrdoob/three.js/blob/master/src/math/Box3.js#L305). So in my opinion it would be easy to move this to a public method `getPoints` resulting in an extra feature without adding too many additional lines of code to the library since the method can then be reused in the `applyMatrix4` method. Something like this:

    getPoints: function () {
        var points = [
            new THREE.Vector3(),
            new THREE.Vector3(),
            new THREE.Vector3(),
            new THREE.Vector3(),
            new THREE.Vector3(),
            new THREE.Vector3(),
            new THREE.Vector3(),
            new THREE.Vector3()
        ];

        points[ 0 ].set( this.min.x, this.min.y, this.min.z ); // 000
        points[ 1 ].set( this.min.x, this.min.y, this.max.z ); // 001
        points[ 2 ].set( this.min.x, this.max.y, this.min.z ); // 010
        points[ 3 ].set( this.min.x, this.max.y, this.max.z ); // 011
        points[ 4 ].set( this.max.x, this.min.y, this.min.z ); // 100
        points[ 5 ].set( this.max.x, this.min.y, this.max.z ); // 101
        points[ 6 ].set( this.max.x, this.max.y, this.min.z ); // 110
        points[ 7 ].set( this.max.x, this.max.y, this.max.z ); // 111

        return points;

    }

    applyMatrix4: function ( matrix ) {

        var points = this.getPoints();

        for( var i = 0; i < 8; i++ ){

            points[ i ] = points[ i ].applyMatrix4( matrix );

        }

        this.makeEmpty();
        this.setFromPoints( points );
        
        return this;

    }

**Comment by Wilt** [comment]
If I am not mistaken the first part can also easily be written like:

    return [
        new THREE.Vector3().set( this.min.x, this.min.y, this.min.z ), // 000
        new THREE.Vector3().set( this.min.x, this.min.y, this.max.z ), // 001
        new THREE.Vector3().set( this.min.x, this.max.y, this.min.z ), // 010
        new THREE.Vector3().set( this.min.x, this.max.y, this.max.z ), // 011
        new THREE.Vector3().set( this.max.x, this.min.y, this.min.z ), // 100
        new THREE.Vector3().set( this.max.x, this.min.y, this.max.z ), // 101
        new THREE.Vector3().set( this.max.x, this.max.y, this.min.z ), // 110
        new THREE.Vector3().set( this.max.x, this.max.y, this.max.z )  // 111
    ];

I can of course make a PR on request...

**Comment by Wilt** [comment]
Others ([like Microsoft :P](https://msdn.microsoft.com/en-us/library/bb197066.aspx) ) call the method `getCorners`. Apparently the order of the points can also be important:

> The points returned correspond to the corners of the BoundingBox faces that are perpendicular to the z-axis. The near face is the face with the larger z value, and the far face is the face with the smaller z value. Points 0 to 3 correspond to the near face in a clockwise order starting at its upper-left corner when looking toward the origin from the positive z direction. Points 4 to 7 correspond to the far face in a clockwise order starting at its upper-left corner when looking toward the origin from the positive z direction.

**Comment by WestLangley** [comment]
I think the `Box3` object is sufficient, as is.

Users should really be allocating their own `Vector3()` arrays.

**Comment by Wilt** [comment]
That is a pity... I think it would be a useful addition.

**Comment by Wilt** [comment]
I again run into the case where I need the corners of the a bounding box as vertices. I also see other people having similar need for example here in this **[clipping-with-caps](https://github.com/daign/clipping-with-caps/blob/master/js/selection.js#L56)** repository. But also [here in the `THREE.Box3` class itself](https://github.com/mrdoob/three.js/blob/master/src/math/Box3.js#L415) these points are needed.

I will provide a PR for this...
