### ISSUE TITLE
three@0.73.1 on npm is using three r72

### ISSUE THREAD

**Issue by toxicFork** [mrdoob/three.js#7986]
@bhouston 

see https://travis-ci.org/toxicFork/react-three-renderer/builds/103075937

Also just installed three@0.73.1, three.js line 7: 
```
var THREE = { REVISION: '72' };
```

**Comment by luruke** [comment]
Same problem here :+1:

**Comment by bhouston** [comment]
Argh.  Fixed.  

https://www.npmjs.com/package/three

**Comment by toxicFork** [comment]
Will be able to confirm this evening :) or if someone else confirms I can close

**Comment by toxicFork** [comment]
Confirmed fixed
