### ISSUE TITLE
WebGLRenderer.getSize returns fractional results on certain devices

### ISSUE THREAD

**Issue by brianchirls** [mrdoob/three.js#7995]
`WebGLRenderer.getSize` now calculates the return value by multiplying the canvas dimensions by the device pixel ratio, as of r74dev, in this commit:
https://github.com/mrdoob/three.js/commit/a17ea05be87ec68b08a68ebead09043f8d92cd5e#diff-c0e88b98497597a015ecf238e91ac3a0L352

Since [many devices](http://mydevice.io/devices/) have fractional pixel ratios, the results are often fractional, which is wrong since both canvases and render targets must have integer values.

`getSize` should round these values.

Refer to: https://github.com/borismus/webvr-boilerplate/issues/104

**Comment by mrdoob** [comment]
Good catch. Probably better to store the `width` and `height` in a separate object though...

**Comment by brianchirls** [comment]
Cool. I was gonna do a PR with rounding, but if you want to store those values elsewhere, it's probably better if you do it.

**Comment by mrdoob** [comment]
Fixed. Thanks!

**Comment by brianchirls** [comment]
:+1: Thank you!
