### ISSUE TITLE
Runtime Error in Example "software_sandbox.html"

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#7997]
When i've cleaned up some of the examples, i've noticed a runtime error in "software_sandbox.html". The problem seemed to be caused in the render method of the `THREE.SoftwareRenderer`.

Message: "Uncaught TypeError: Cannot read property 'r' of undefined"

```javascript
(function(buffer, depthBuf, offset, depth, u, v, n, face, material
/**/) {
var colorOffset = offset * 4;
buffer[ colorOffset ] = face.color.r * 255; // ERROR
buffer[ colorOffset + 1 ] = face.color.g * 255;
buffer[ colorOffset + 2 ] = face.color.b * 255;
buffer[ colorOffset + 3 ] = material.opacity * 255;
depthBuf[ offset ] = depth;
})
```
THREE 74(dev), Mac OSX 10.10.5, Chrome 48.0.2564.82 (64-bit)

**Comment by daoshengmu** [comment]
Thanks for your notice. I will take this bug. Investigating!

**Comment by makc** [comment]
That could be me, in #7901 I make new faces and do not create colors there. because I have only tested with textured stuff.

**Comment by daoshengmu** [comment]
makc, don't mind. I have resolved it at #8036.

**Comment by WestLangley** [comment]
@Mugen87 Can this be closed?

**Comment by Mugen87** [comment]
@WestLangley Yep, bug is fixed.
