### ISSUE TITLE
Building/Loading a light using JSON object from  THREE.Light.toJson()

### ISSUE THREAD

**Issue by JamesHagerman** [mrdoob/three.js#8002]
We can use THREE.Light.toJSON() to get the JSON representation of a light, but as far as I can tell, there's no way to build a new light using the returned JSON object.

I'm not actually trying to "clone" an existing light as is available via THREE.Light.copy(). In this case, I'd like to be able to store the JSON object defining the light then rebuild the light using that JSON object at a later time.

There doesn't seem to be a loader/builder for lights using JSON objects currently. Would this be a useful thing to build and contribute?

Is there some trick to doing this that I'm missing?

**Comment by satori99** [comment]
You can use THREE.ObjectLoader to parse the JSON;
    
    json = new THREE.DirectionalLight().toJSON();
    light = new THREE.ObjectLoader().parse( json  );

**Comment by JamesHagerman** [comment]
Ah! Right! I'll close this...
