### ISSUE TITLE
"THREE.BufferGeometry: .addDrawCall() no longer supports indexOffset"

### ISSUE THREAD

**Issue by stephentt** [mrdoob/three.js#8005]
Hello, I am currently using three.js v70 and am trying to upgrade to that latest v73, but all the rendering of my large models that use BufferGeometry with index offsets are now broken.  I saw the message in the code "THREE.BufferGeometry: .addDrawCall() no longer supports indexOffset" so how am I supposed to support indexing over 65536 vertices with the latest code?  This seems like a serious regression.  Any help would be appreciated, thank you.

**Comment by stephentt** [comment]
I just noticed in the BufferGeometry code that there is a check to see if index > 65536  then assume the index array is Uint32Array.  Is that why indexOffset was removed?  For now I can stop dividing my geometry into chunks of 65536 indices, but what about browsers that do not support Uint32Array?

**Comment by mrdoob** [comment]
> But what about browsers that do not support Uint32Array?

Which ones are those? http://webglstats.com/ says, on October 2015, `OES_element_index_uint` already had 97.3% support.

**Comment by stephentt** [comment]
Ok that's good to know.  But there is still a hard limit baked in now of 2^32 indexable vertices.  That sounds like a lot at this point in time but those are famous last words in software development.

I also didn't see anything about this change of taking out offsets listed in migration notes which might have saved me some fumbling around: https://github.com/mrdoob/three.js/wiki/Migration

Anyway thanks for the quick reply and feel free to close this after your next response.

**Comment by mrdoob** [comment]
Added to the migration page. Sorry about that.
