### ISSUE TITLE
objectloader with shapegeometry

### ISSUE THREAD

**Issue by Jordumus** [mrdoob/three.js#8007]
I have exported an object I made on the scene with javascript (as a shapegeometry) using the `toJSON()`function. Now I try to reload the object on the scene with an `objectLoader`, but it fails because the objectloader doesn't support geometry type `ShapeGeometry`.

Except if I'm missing something, that means that I can't reload exported models in the scene?

**Comment by MasterJames** [comment]
In my mind what needs to be duplicated should run through a map to select what's important. 
What happens to deep functions with this Json way? 
Anyway an automated filter for it like maybe don't copy _ underscored values like _id (use name to find a unique ref id record instead) but that's not been considered ahead of time (not underscored where needed) and I personally hate underscore as private indicator except in this case where you want to automate archiving without an optimized mapping indicated of what's truly needed, which could change for different purposes. modification Date might be another example that's modified on the server apon archiving and doesn't need including in the json. Same with a userId. For security reasons that should be overwritten with servers knowledge of the user session and/or immutable on the server side and again it's a waste to transmit that in the json back to the server too and should be potentially filtered out.

**Comment by mrdoob** [comment]
Indeed... `ObjectLoader` doesn't support `ShapeGeometry` yet.

**Comment by blahmonkey** [comment]
Same with ExtrudeGeometry.

Is there a reason these are hard to load using ObjectLoader? Or just that nobody has got around to upgrading ObjectLoader yet...?

Thanks,

**Comment by blahmonkey** [comment]
Just hacked the code to follow the 'Geometry' case, treat ExtrudeGeometry as the same - it does work to an extent.

The issue seems to be with the instantiation of ExtrudeGeometry from shapes, we're obviously unable to instantiate it just using faces/vertices/uv data.

**Comment by mrdoob** [comment]
I think the main issue to tackle is the serialisation of the `ExtrudeGeometry`/`ShapePeometry` data.

**Comment by blahmonkey** [comment]
Would a possible solution be instantiating an empty ExtrudeGeometry/ShapeGeometry, then deserializing the faces, vertices, uvs?

**Comment by NicolaiMogensen** [comment]
Has this been addressed lately? I am currently working on saving projects and geometries as JSON on a node server, and i'm using mostly `ExtrudeGeometry`. It would be really cool if this could be solved in some way, hacked or not.l

**Comment by blahmonkey** [comment]
@NicolaiMogensen - I found an older thread somewhere else on this board dealing with the same issue. The commenter spoke about making a new Geometry object and copying faces, vertices over (he didnt mention UVs but that would obviously be done as well). And then exporting to JSON

**Comment by NicolaiMogensen** [comment]
I found issue #5863 and essentially ended up doing what he did (omitting UV's as they are not important to me). It works, and it will have to do for now, but it would be great if support was added for `ExtrudeGeometry` aswell

**Comment by blahmonkey** [comment]
@NicolaiMogensen Totally agree with you +1 on support for ExtrudeGeometry and ShapeGeometry when doing toJSON.

**Comment by impcyber** [comment]
I had the same problem too, but this work for me:
here: https://github.com/mrdoob/three.js/blob/dev/src/loaders/ObjectLoader.js#L285
```
case 'ShapeGeometry':

	geometry = geometryLoader.parse( data.data ).geometry;

	break;
```
r79

**Comment by ByDenis** [comment]
For my projects, this tool is very necessary. I can help?

**Comment by ByDenis** [comment]
Thank you, good news. A very necessary tool.

**Comment by Mugen87** [comment]
Closing. Adding serialization/ deserialization for `ExtrudeGeometry ` is tracked via #5863
