### ISSUE TITLE
Exporters in separate repos with submodules?

### ISSUE THREAD

**Issue by ZelimDamian** [mrdoob/three.js#8009]
Github doesn't allows downloading subfolders. I would rather not wait for a 120Mb download to just get the Blender exporter. Putting them each in separate repos and including as submodules would allow people to download specific exporters when needed.

**Comment by mrdoob** [comment]
GitHub doesn't include submodules in the download either 😕

**Comment by jkarbows** [comment]
You could do a sparse checkout via cli? It doesn't seem like there's any other way without downloading the full repo.

**Comment by makc** [comment]
> I would rather not wait for a 120Mb download to just get the Blender exporter

woah, someboy out there is actually using megabits

**Comment by makc** [comment]
@mrdoob I think that's the idea.

**Comment by donmccurdy** [comment]
FWIW I use https://kinolien.github.io/gitzip/ to grab subfolders from GitHub. Never managed to do a partial clone with Git.

Based on that code, if someone wanted to set up a feature for exporters' docs pages to download the latest zip that would be a nice feature I think.

**Comment by mrdoob** [comment]
> Github doesn't allows downloading subfolders. 

Actually... this is actually a feature request for Github itself.

**Comment by makc** [comment]
[Here is an interesting email from git ml](https://public-inbox.org/git/xmqqtx3npu6e.fsf@gitster.dls.corp.google.com/):
```plaintext
> i am thinking about developing an app and I want to integrate it with
> git but I only want to store a portion of the file on disk. It is
> going to be in a mobile enviornment and I want to just get one file or
> a small group of files.
>
> I read that you can clone and then only look at one peice but is it
> possible just to clone one peice? And if not what would it take? Maybe
> this is a feature people would like to have. Just hypothetically, what
> would need to happen?
>
> Either
> git clonepartial /repo /file/or/folder/in/repo
> Or
> Git clone -partial /repo /file/or/folder/in/repo

You keep saying "file", but the thing is, Git does not track file.
It tracks history of collection of files.

What are you trying to achieve, exactly?  What does your "app" need
out of that operation?  Does it need these selected files with their
history?  Or does it only care about the contents of the selected
files at the tip of the 'master' branch of that repository?

I'd imagine that your answer would be the latter, and suspect that
you may want to run "git archive --remote" with a pathspec to limit
what gets grabbed.
```

so, it looks like it can be done with some command line fu using bare git, after all ?
