### ISSUE TITLE
Object moves in opposite direction after its parent plane rotate by 180 or more 

### ISSUE THREAD

**Issue by neerajSharma001** [mrdoob/three.js#8014]
Hello Mr. Doob 
i am working on a project using three js .
and i found there is issue regarding child rotation issue after its parents is rotated ..
for example 
when i try to move a object it moves perfectly with mouse . 
but when i rotate my plane on which these objects are added ....objects movement in different direction as mouse move ...

i am raising the same question over stack-overflow but there is no one replied 

 http://stackoverflow.com/questions/34946735/object-moving-in-different-direction-after-rotating-the-plane-three-jsv73

you can also check js-fiddle linked in question

**Comment by izatar** [comment]
I put an answer in stackoverflow.  I think you should not bother MrDoob with bugs you make, but only ones that are in the three.js code.

**Comment by neerajSharma001** [comment]
Hello @izatar  firstly i wanna thanks to you to replied my post 
and secound thing i wanna bring to your attention  is : your answer is only 50% correct .
Case 1 : when i rotate my plane by 180 ...good 
case 2 : rotate plane by 90 ....mesh did not move in x direction ...

and yeah  that's right , not to bother @mrdoob

**Comment by erichlof** [comment]
Hi @neerajSharma001 ,
I answered on stackoverflow and updated your JSFiddle to work correctly.  Good luck to you!

**Comment by neerajSharma001** [comment]
Thanks you for all for helping ... BTW i am Newbie in three js .
Thanks a Lot :) :+1:

**Comment by erichlof** [comment]
Hi again @neerajSharma001 ,
I'm not sure how you expect the whole system to behave.  I thought you wanted to rotate the plane and cube mesh at the same time by selecting and dragging the plane (floor) around, and then be able to independently pick and move the cube mesh, relative to the camera.  So, if I drag the mouse to the right, the cube mesh correctly goes to the right side of the screen (in my JSFiddle).  Were you expecting something else from the cube mesh upon selecting and dragging it, after rotating the floor plane beneath it?  Do you not want it to rotate with the floor plane at all?  

p.s. maybe answer me on your StackOverflow post, as I do not want to clutter up the Three.js message board with our discussion.  I'll be happy to explore with you further over on SO.  Thanks!

**Comment by erichlof** [comment]
@neerajSharma001 , sorry to ping you here, but did you see my updated comment with new JSFiddle?  How does that work for you?  Please answer on stackoverflow - see you over there!

**Comment by neerajSharma001** [comment]
yes @erichlof
