### ISSUE TITLE
THREE.UniformsUtils.merge shoudnt clone the texture

### ISSUE THREAD

**Issue by Makio64** [mrdoob/three.js#8016]
Merging should use the existing texture, not cloning it ( same for others parameters ), its counter intuitive and memory expensive. I find myself in the case I wanted to just add some fog uniforms & other common to my rawShader and it take me time to figure out my texture was cloning and thats why my shader wasnt working and my texture share between all my instance not updated..

If the user want to clone the texture then he should use UniformsUtils.clone(myUniforms) and then merging it, trying to hide this step can lead to some serious bugs.

**Comment by mrdoob** [comment]
Hmm, the problem is not the `Texture` but the `Image`.

**Comment by Zob1** [comment]
I ran into this issue with a Color uniform.

**Comment by mrdoob** [comment]
@Zob1 do you mind elaborating?

**Comment by Makio64** [comment]
@mrdoob Hmm, what do you mean the problem is the Image.?

Maybe i wasnt clear, for exemple : 
a = { type:'t', value:mytexture } 
b = { type:'f', value:0 }
uniforms = THREE.UniformsUtils.merge( [a,b] )

Expectation : 
uniforms = {
   { type:'t', value:mytexture }
   {  type:'f', value:0 }
}

Currently : 
uniforms = {
    { type:'t', value:mytextureCloned } // mytextureCloned !== mytexture
    { type:'f', value:0 }
}

same for other object ( including color ) as @Zob1 said.

And the problem is after if the original color/texture/vector/etc.. is changed, it will note change into the merged uniforms.

It come from here : 
https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/UniformsUtils.js#L39

I feel this "if" should be removed cause cloning looks like out of range of a merge utils function

Cheers!

**Comment by WestLangley** [comment]
The intention is for you to merge the uniforms data structures and assign values afterward.

```javascript
var a = { texture: { type: 't', value: null } };
var b = { opacity: { type: 'f', value: 0 } };
var uniforms = THREE.UniformsUtils.merge( [ a, b ] );

uniforms.texture.value = myTexture;
uniforms.opacity.value = 0.5;
```

This is how it is done in the examples.

If you assign the texture a value prior to merging, the texture will be cloned and the `needsUpdate` flag will be set to `false`. Obviously, that is not what you want.

**Comment by Makio64** [comment]
Yeah, solving the problem is easy but when I use a merge function on 2 objects who have reference values, I expect reference values to be merge too, not replaced by reference to a clone. I really don't understand the point of the current behavior of this function.

by default it shoudnt clone and if i want to clone then:
 
var a = { texture: { type: 't', value: myTexture } };
var b = { opacity: { type: 'f', value: 0 } };
var uniforms = THREE.UniformsUtils.merge( [ a, b ] );
uniforms.texture.value = uniforms.texture.value.clone();

**Comment by WestLangley** [comment]
>Yeah, solving the problem is easy

Good. So you now have a workaround. : - )

>I really don't understand the point of the current behavior of this function.

It is so uniforms will be unique, and the uniforms for one material (color, for example) will not be shared with another.
```javascript
var uniforms1 = THREE.UniformsUtils.merge( [ a, b ] );
var uniforms2 = THREE.UniformsUtils.merge( [ a, b ] );
```

**Comment by Makio64** [comment]
if you want this behavior the user should do this : 

var uniforms1 = THREE.UniformsUtils.merge( [ a, b ] );
var uniforms2 = THREE.UniformsUtils.clone( uniforms1 );
uniforms1.texture === uniforms2.texture // false

&
var uniforms1 = THREE.UniformsUtils.merge( [ a, b ] );
var uniforms2 = THREE.UniformsUtils.merge( [ a, b ] );
uniforms1.texture === uniforms2.texture // true

**Comment by mrdoob** [comment]
One can't instantiate JavaScipt Numbers. So Unifoms that use a Number as value will get "cloned" anyway. This behaviour of cloning then follows this limitation.

**Comment by pailhead** [comment]
possibly related?
https://github.com/mrdoob/three.js/issues/7367

**Comment by sjlynch** [comment]
Changing
			var tmp = this.clone( uniforms[ u ] );
to
			var tmp = uniforms[ u ];

in the library fixes the issue for me. So I created a personal patch file with that code which replaces the merge function in threejs. 

I'm still not sure why it isn't like that by default, since this works fine with my shaders. I'm not seeing any issues. @mrdoob cloning a number is fine because a number is a number. Cloning an object is different since you lose references that way. So I guess I don't understand your comment.

**Comment by zEh-** [comment]
I debugged the hell out of my ShaderMaterial's fragment shader.
Everytime I tried to use fog I ended up with black fragments due to missing image references.

Would be nice to have this solved. Until then I merge all required UniformsLibs and then append my custom ones, because UniformsUtils.merge can't handle them.

**Comment by zEh-** [comment]
May be of interest. This works: (Don't forget the potentially required polyfill and yeah, this isn't recursive.)
`const uniforms = THREE.UniformsUtils.merge([
    THREE.UniformsLib['common'],
    THREE.UniformsLib['fog']
]);
Object.assign(uniforms, {
    bumpFactor: {value: bumpFactor},
    // ...
});`

**Comment by mrdoob** [comment]
@Makio64 Sounds like one can use `Object.assign` (which is already polyfilled in the library)

```js
var a ={ texture: { type:'t', value:mytexture }  }
var b ={ opacity: { type:'f', value:0 }  }
var uniforms = Object.assign( a, b )
```

Knowing this, we could start deprecating `UniformsUtils.merge()` in favour of `Obect.assign()`. I think this is better than changing the current behaviour of `UniformsUtils.merge()`.

**Comment by Makio64** [comment]
@mrdoob Totally agree on this change, it will be more intuitive and clean 👍

**Comment by mrdoob** [comment]
UniformUtils is now gone! ✌️

**Comment by Makio64** [comment]
Just run into this stuff again...

I discover the change get reverse..
Everytime I go in advanced case and some old code use this function I get trap, maybe its just me, but I feel its an un-natural approach. 

A solution can be a rename more explicit about what the function is actually doing
merge(uniforms) => cloneAndMerge(uniforms)
