### ISSUE TITLE
Why does aoMap only use the red channel?

### ISSUE THREAD

**Issue by throni3git** [mrdoob/three.js#8018]
I wondered why the aoMap property is reduced to the red channel, when instead it could use the whole rgb values?

Implementation: 
totalAmbientLight *= ( texture2D( aoMap, vUv2 ).r - 1.0 ) * aoMapIntensity + 1.0;

in https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderChunk/aomap_fragment.glsl

**Comment by WestLangley** [comment]
Because an ambient occlusion map is a greyscale image.

**Comment by mrdoob** [comment]
It's true that it could use rgb though. People could create interesting effects with that while it will still work with grey scale textures...

**Comment by throni3git** [comment]
Yeah, mrdoob, this is the spirit! :)

**Comment by mrdoob** [comment]
@throni3git do you want to do a PR with the change? 😊

**Comment by WestLangley** [comment]
I am not in favor of this suggestion.

@mrdoob Do you want to change the `alphaMap`, `metalnessMap`, and `displacementMap` to use all three channels, too?

@throni3git What is your use case?

**Comment by MasterJames** [comment]
Sometimes in photography when you make a picture black and white it can be a very different result depending on what channel or the strengths thereof you use.
If it's just a mask there should be only one channel given. If r g b are passed it makes sense to use all three unless there is a provable performance issue.
This is not however a proper use case and just some reasoning and personal opinion/vote pro usage of all available/provided color planes.

**Comment by mrdoob** [comment]
> @throni3git What is your use case?

I'm curious too.

**Comment by throni3git** [comment]
In first place, i just wondered about the restriction. Then i think of ambient occlusion in a colored way: e.g., a blue box will reflect some blue light towards a white box next to it. With only-greyscale aoMap, we take away an important part of the ambient occlusion, i think.

On the other hand, maybe i confuse lightMap and aoMap with the example given... Anyway, it may be nice to have lightMap as an additive operation and aoMap as a multiplicative operation :)

**Comment by WestLangley** [comment]
>Anyway, it may be nice to have lightMap as an additive operation

It is; it is additive to total indirect ( ambient ) light.

> and aoMap as a multiplicative operation

It is; it attenuates indirect (ambient ) light sources.

**Comment by mrdoob** [comment]
Interestingly, `lightMap` uses all channels, but `aoMap` only uses the red channel.

**Comment by WestLangley** [comment]
`lightMap` is a source of light, and is RGB-valued.

`aoMap` is ambient occlusion, a percentage, and is scalar-valued.

**Comment by throni3git** [comment]
> Interestingly, lightMap uses all channels, but aoMap only uses the red channel.

that was my point

> lightMap is a source of light, and is RGB-valued.
> aoMap is ambient occlusion, a percentage, and is scalar-valued.

so if one wants to apply color bleeding, how to do it? use aoMap to reduce overall light intensity and then use lightMap to fill up the bleeding color? (color bleeding might be the use case i was thinking of :) )

**Comment by mrdoob** [comment]
@throni3git if you can create an image of what it's that you're trying to achieve, that may be able to convince us to bend the rules 😊

**Comment by throni3git** [comment]
There we go: http://s614.photobucket.com/user/ElektraGlide/media/cornell_lightup-1.jpg.html

**Comment by mrdoob** [comment]
Oh, baking radiosity. Interesting...

**Comment by WestLangley** [comment]
>Oh, baking radiosity. Interesting...

Yes, a `lightMap` can be used to model global illumination.

>The occlusion map is used to provide information about which areas of the model should receive high or low indirect lighting. Indirect lighting comes from ambient lighting and reflections, and so steep concave parts of your model such as a crack or fold would not realistically receive much indirect light... An occlusion map is a greyscale image.

ref: http://docs.unity3d.com/Manual/StandardShaderMaterialParameterOcclusionMap.html

**Comment by throni3git** [comment]
Thanks for the nice overview :)
So on the whole topic, you decide.

**Comment by WestLangley** [comment]
I think it is best to leave things as they are for all the reasons stated.

@throni3git Thank you for your understanding.
