### ISSUE TITLE
toJSON document wrong place

### ISSUE THREAD

**Issue by MasterJames** [mrdoob/three.js#8019]
toJSON is in Light.js but the documentation places it in AmbientLight.
Not a big deal just seemed like a simple thing to overlook and so I thought I'd post it.

**Comment by mrdoob** [comment]
I'm confused...

**Comment by bioship** [comment]
he's saying 'toJSON' is not documented for the classes that implement the method.  it is only documented for classes that inherit it.  this is actually true for all documented methods - the documentation only sees methods defined in super classes ( with respect to the documented class ).

**Comment by MasterJames** [comment]
Right thank you.
