### ISSUE TITLE
Using MeshBasicMaterial + side=BackSide + wireframe=true

### ISSUE THREAD

**Issue by handegar** [mrdoob/three.js#8020]
It seems like the side=THREE.BackSide gets ignored when switching on the wireframe. Is this a bug or as intended? I'm using r73.

This can easily be reproduced by going to the MeshBasicMaterial doc and switch on side=BackSide and then toggle the wireframe setting;

http://threejs.org/docs/#Reference/Materials/MeshBasicMaterial

**Comment by mrdoob** [comment]
It's a limitation of WebGL itself...
