### ISSUE TITLE
Geometry.verticesNeedUpdate seems doesn't work correctly

### ISSUE THREAD

**Issue by RUSSCITY** [mrdoob/three.js#8021]
Hello,

I considered the example http://jabtunes.com/labs/3d/bunny/ 
from http://www.lab4games.net/zz85/blog/

It works fine on threejs 70dev.

I just cloned this to my test and replaced threejs lib with r73. The geometry will no more be updated. If you export and import the object, then it is simplified. Is it a bug? I couldn't find any information about these changes from r70 to r73.

Thanks in advance!

**Comment by RUSSCITY** [comment]
Sorry, here is the copy of this on my server with r73:

http://dev2.russcity.de

**Comment by Rinkana** [comment]
+1 i have the same issue on my own geometry too. 

I did notice that the .verticesNeedUpdate value does reset back to false but there is no visible change.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

If you are not certain it is a three.js bug, we prefer you first seek help on stackoverflow.

**Comment by Rinkana** [comment]
It seems to have something to do with the directGeometry. Here is an earlyer type of issue:
https://github.com/mrdoob/three.js/issues/7179

When i added `delete tile.geometry.__directGeometry;` the geometry did update

**Comment by WestLangley** [comment]
@Rinkana If you can demonstrate a three.js bug, can you provide a simple jsfiddle as explained in the guidelines?

**Comment by Rinkana** [comment]
@WestLangley i just wanted to help RUSSCITY. However, i've made a jsfiddle for you:
http://jsfiddle.net/95e6v30e/

When you comment rule 161 out you'll notice that the geometry does not go flat after 1s

**Comment by WestLangley** [comment]
@Rinkana As discussed in #7179, you can't reassign the vertices array. Use `copy()` instead.

**Comment by RUSSCITY** [comment]
Thanks to all, and especially to Rinkana!

**Comment by Tzikas** [comment]
I'm having a hard time finding geometry.__directGeometry;  What directory is it in? http://stackoverflow.com/questions/35186330/why-doesnt-geometry-verticesneedupdate-true-allow-me-to-change-the-vertice/35187422#35187422

**Comment by airycanon** [comment]
@Rinkana When I deleted `geometry.__directGeometry`,the geometry did update,but the `rendering performance` dropped down,is there a better way to make the geometry update?
