### ISSUE TITLE
test / memory example memory consumption

### ISSUE THREAD

**Issue by astrolabio** [mrdoob/three.js#8022]
![memory](https://cloud.githubusercontent.com/assets/4153350/12582881/08b36e76-c440-11e5-91fb-56bf1d155a93.JPG)
Although the memory stands constant when using the profile tools in Google Chrome, the memory assigned to the process in the task manager grows continuously in an ascending saw graph.

**Comment by mrdoob** [comment]
Does that also happen with the `dev` branch?

**Comment by astrolabio** [comment]
It happens too, but the graph is not an ascending saw but something more like 70MB-80MB-70MB-100MB-70MB-120MB-70MB-140MB-70MB-160MB ... 70MB-500MB-70MB-520MB ... in both versions

**Comment by NicolasRannou** [comment]
Did you try on Firefox/Edge to see if you see the same behavior?

**Comment by astrolabio** [comment]
I have also tested it in my mac and there is a similar behavior in Chrome and Firefox when checking the memory in the activity monitor.

**Comment by zz85** [comment]
Have you tried hitting the Garbage Collection button (trash can) to see if the memory goes down after? ![image](https://cloud.githubusercontent.com/assets/314997/12690193/b8e980ee-c71c-11e5-83c1-1f4a274af514.png)

**Comment by leitzler** [comment]
And it doesn't have to do with console logging? (see comments in the end of #7449)

**Comment by astrolabio** [comment]
Memory profiling is Ok inside the navigator, and garbage collection works.
The problem is when you check the memory with the task manager or the activity manager that does not match with the memory when profiling with the navigator.
can you check it in your computers opening the memory example and the task manger or activity manager and waiting for a while too see how ram memory behaves?

**Comment by astrolabio** [comment]
maybe this can affect
http://stackoverflow.com/questions/23120851/webgl-deletebuffer-leaking-memory

**Comment by meirela** [comment]
Hey, have someone found a way to solve the JS/ArrayBufferData memory problem?
I am having really difficult time dealing with it...

Also, as other people suggested - the memory test in the official Examples page is showing the same results - memory usage increases as a Sawtooth wave, from a maximum value of around 50K when it starts, to ~200K in less then a minute.
It keeps on growing, even when GC is invoked using Google Dev-tool

**Comment by astrolabio** [comment]
I don’t have a formal answer, but i have noticed that the memory is freed if you give the process time to free it, but if the buffer creation pace is too high and continuous, the memory used continuously grows.
