### ISSUE TITLE
THREE.Line from THREE.ShapeGeometry is missing a line segment

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#8024]
Not sure but I think this is a bug or I at least expected something else...

I made a fiddle [here](http://jsfiddle.net/wilt/w67tzfhx/70/) to demonstrate...

```
// definition of a shape ( a 40x40 square)
shape = new THREE.Shape();
shape.moveTo( 0, 0 );
shape.lineTo( 40, 0 );
shape.lineTo( 40, 40 );
shape.lineTo( 0, 40 );
shape.lineTo( 0, 0 );

// convert the shape to geometry
var geometry = shape.makeGeometry();

// material
var material = new THREE.LineBasicMaterial( { color: 0xff0000, linewidth: 2 } );

// line
line = new THREE.Line( geometry,  material );
scene.add( line );
```

The last segment seems to be missing...

**Comment by makc** [comment]
probably somewhere along the way the last vertex gets optimized out. [here](http://jsfiddle.net/w67tzfhx/71/) is a workaround for you.

**Comment by MasterJames** [comment]
I would call that a bug (with a work around).

**Comment by makc** [comment]
not really, it's just that shape does not have to be convertible to line. e g you do not [try to convert SphereGeometry to line](http://jsfiddle.net/w67tzfhx/72/), do you?

**Comment by Wilt** [comment]
@MasterJames Your work around actually shows the real problem (or bug if so). The last point in `geometry.vertices` should be ( 0, 0, 0 ) and should close the shape, but that goes wrong. By changing it to something just off like you did works, I will end up with an unclosed shape/line and it feels like a dirty hack...

**Comment by Wilt** [comment]
@MasterJames  I understand your point of view with converting a `SphereGeometry` to a Line. Like I said in my question, not sure if it is a bug, but I expected to get my shape drawn when using Line.

But you have a good point, maybe it should have another method something like `makeLineGeometry`. But I think in this specific case the geometry can easily contain all information for both (line and surface geometry) there is simply one point missing in the vertices array...

**Comment by Wilt** [comment]
The discussion becomes more interesting if we will look at a `THREE.CircleGeometry` instead of `THREE.SphereGeometry`
It would be fair to say that people will be interested in Line representations of 2D (plane) geometries rather then 3D geometries. So checking out `THREE.CircleGeometry` would make more sense.

I made [a fiddle here](http://jsfiddle.net/wilt/w67tzfhx/74/)

As you see the `THREE.Line` made from a `THREE.CircleGeometry` looks very nice. 
What is interesting that the `THREE.Line` that is drawn looks differently for a geometry that was also used for rendering a mesh. 
Apparently there is some internal logic that turns the `THREE.Line` into a pie like representation when it is also used inside a Mesh. If the geometry is never used as a mesh, but only for creating a THREE.Line then a single line starting at the center of the circle is drawn.

On the right I drew a custom sphere `Geometry`. It is defined with minimal amount of points in counterclockwise order starting on the right. I also added the faces so the mesh (rendered at top right) looks exactly the same as the mesh made from the `SphereGeomtry`. With `THREE.Line` this geometry simply draws the outline of the circle. In general this is what I think could be intersting. Some means to get the outline (THREE.Line or THREE.LineSegments) of the 2D geometries.

The only thing is the middle point 

I made

**Comment by MasterJames** [comment]
BTW It was not my work around. It must be a hardware GL level where duplicate points get deleted or some kind of problem like that. 
Still I imagine a bit of code could patch that micro offset automatically even if the hardware demanded no duplicate points? Just speculation, which makes no sense/argument really. I also imagined there may be some simple way to "close" it. Maybe if it is beyond addressing in three js a complaint to Kronos might be warranted. 
I've not found myself using it but it seems expected behaviour and I'd imagined easily addressable.

**Comment by Wilt** [comment]
@MasterJames sorry I swapped you two. I updated my messages...

**Comment by makc** [comment]
@Wilt 

> The discussion becomes more interesting if we will look at a THREE.CircleGeometry instead of THREE.SphereGeometry

the point was that THREE.Line accepts any geometry at all, and there is no guarantee that it will make nice line out of it. So, maybe you don't have much reason to expect shape's geometry to be useable for THREE.Line? It does not make any claims about vertices order, nor promises to not reuse vertices, right? Nowhere in [ShapeGeometry docs](http://threejs.org/docs/#Reference/Extras.Geometries/ShapeGeometry).

That said, your use case could still be reasonable, and you could very well submit PR adding and option to ShapeGeometry that makes it Line-compatible?

**Comment by WestLangley** [comment]
Use the dev branch and set

    shape.autoClose = true;

**Comment by MasterJames** [comment]
I wondered if there is currently a way to view the most current under development version 74dev docs?

**Comment by MasterJames** [comment]
Actually then there is a bug in that. autoClose = true
http://jsfiddle.net/MasterJames/w67tzfhx/77/
Well at least I couldn't get it to close with a duplicate zero or not.

**Comment by makc** [comment]
You are not using dev version

**Comment by MasterJames** [comment]
Right I tried this and it didn't like it?
http://jsfiddle.net/MasterJames/w67tzfhx/78/
Script src?
https://raw.githubusercontent.com/mrdoob/three.js/dev/build/three.min.js

**Comment by makc** [comment]
Use rawgit.com maybe http://jsfiddle.net/w67tzfhx/80/

**Comment by MasterJames** [comment]
Thanks I keep forgetting that.

**Comment by MasterJames** [comment]
If your sorted @Wilt, please close this issue.
The newest version and using "close" is better then micro offsets, right?

**Comment by Wilt** [comment]
@MasterJames  Definately :) Done...

**Comment by Mugen87** [comment]
Why is this issue open again?

http://jsfiddle.net/w67tzfhx/1470/

**Comment by Wilt** [comment]
I reopened since I started working further with this kind of line geometries  again and this issue seems to persist or it reoccurred since I closed this issue last time (in 2016).

    // shape
    shape = new THREE.Shape();
    shape.moveTo( 0, 0 );
    shape.lineTo( 40, 0 );
    shape.lineTo( 40, 40 );
    shape.lineTo( 0, 40 );
  
    shape.autoClose = true;
  
    // geometry
    var geometry = shape.makeGeometry();

    // material
    var material = new THREE.LineBasicMaterial( { color: 0xff0000, linewidth: 2 } );

    // line
    line = new THREE.Line( geometry,  material );
    scene.add( line );

I tried also with `autoClose = true`, but cannot seem to draw a continuous line when making a ShapeGeometry from a continuous shape and using it with THREE.Line and THREE.LineBasicMaterial :

http://jsfiddle.net/wilt/w67tzfhx/1471/

Did this change that was in Dev branch not end up in the master? Or is there something else that goes wrong here?

**Comment by Wilt** [comment]
@Murgen87, was some delay in posting my message, but apparently it works for ShapeBufferGeometry but it doesn't work for ShapeGeometry:

http://jsfiddle.net/wilt/w67tzfhx/1472/

**Comment by Wilt** [comment]
Thanks for your response.

If I am not mistaken it used to work correctly in earlier versions and it is a pity that it doesn't work any longer. Of course I can build the geometry like that, but it means I have to create two different geometries one for the line and one for the mesh representation of the same object. 

I will close this issue and use the solution as you proposed.
