### ISSUE TITLE
docs: CanvasRenderer

### ISSUE THREAD

**Issue by hiaselhans** [mrdoob/three.js#8033]
At http://threejs.org/docs/index.html#Reference/Renderers/CanvasRenderer

The docs say CanvasRenderer is "a nice fallback" for webglrenderer, but it is not included in three.js core. A little reminder in the docs would be nice to have. (like: "CanvasRenderer moved out of core to 
[examples/renderers](http://mrdoob.github.io/three.js/examples/js/renderers/CanvasRenderer.js)" )

**Comment by Mugen87** [comment]
@hiaselhans Do you mind closing the issue?

**Comment by hiaselhans** [comment]
thanks! (sorry for the delay)
