### ISSUE TITLE
Loader.createMaterial: Unsupported colorAmbient and mapAmbient errors

### ISSUE THREAD

**Issue by BrodaNoel** [mrdoob/three.js#8034]
Version: THREE.WebGLRenderer 73
Windows 7, Firefox 44.0

I'm getting those errors in console log:

```
THREE.WebGLRenderer 73
scripts.js (línea 1047)
GET http://local.xxx.com/files/escena.json
Loader.createMaterial: Unsupported colorAmbient [0.7, 0.7, 0.7]
Loader.createMaterial: Unsupported mapAmbient da01f132.dds
Loader.createMaterial: Unsupported colorAmbient [0.7, 0.7, 0.7]
Loader.createMaterial: Unsupported mapAmbient 3fc5e191.dds
Loader.createMaterial: Unsupported colorAmbient [0.7, 0.7, 0.7]
Loader.createMaterial: Unsupported mapAmbient e71c68d2.dds
Loader.createMaterial: Unsupported colorAmbient [0.7, 0.7, 0.7]
Loader.createMaterial: Unsupported mapAmbient f71d20d6.dds
Loader.createMaterial: Unsupported colorAmbient [0.7, 0.7, 0.7]
Loader.createMaterial: Unsupported mapAmbient 0e3bf8b2.dds
```

The zip file (http://warriots.com/allinfo.zip) contain:
folder `Chamber Of Secrets` (file to be transformed to .json file)
`obj2json.py`: transformer downloaded from this repo a few hours ago
`index.html`: file with the html and js content
`escena.json`: JSON file to be rendered. Output of the `chamber of secret.obj` file.

Why Chamber of secret? Well... I just downloaded an example from the web...
Probably that is the issue... Some old 3dMax version. I really don't know.
Here the file: http://tf3dm.com/3d-model/chamber-of-secrets-scene-45247.html

If you don't feel confident opening that .zip file, let me know and I could send you all files with no .zip file

Error:
![sin titulo](https://cloud.githubusercontent.com/assets/1837969/12668056/aa97c550-c631-11e5-9d3c-31eec3075ed6.png)

**Comment by Wilt** [comment]
It might happen because ambient was removed from material from r71. 
You can read that [in the release notes here](https://github.com/mrdoob/three.js/releases/tag/r71)

**Comment by Mugen87** [comment]
Like @Wilt said, `colorAmbient` and `mapAmbient` are no longer supported. You can avoid such errors in two ways:

* You can try to manually remove these properties from your export file.
* You export the object from your 3D graphics software with one of the latest three.js exporter (see utils/exporter).

**Comment by Mugen87** [comment]
@mrdoob I've seen in `dev`, that `THREE.Loader.createMaterial` produces a warning for `colorAmbient`(see below), but not for `mapAmbient`. Do you think, we should add `mapAmbient` in the same way like `colorAmbient` (so users get a warning and not an error)?

```javascript
case 'colorAmbient':
    console.warn( 'THREE.Loader.createMaterial: colorAmbient is no longer supported' );
    break;
```

**Comment by mrdoob** [comment]
@Mugen87 nice catch!
