### ISSUE TITLE
Recommendation: Constructors taking JSON

### ISSUE THREAD

**Issue by MasterJames** [mrdoob/three.js#8035]
I opened this thread at StackOverflow and had my worst suspicions enforced that this is not idea for my personal private vision (aka use case) for THREE in general.
http://stackoverflow.com/questions/35075432/how-to-change-a-boxs-dimensions-size-after-creation

I think it would be nice that if in any new THREE\[type\]\(\) declaration you could simple pass it an Object aka JSON with standard format for values and have it create and/or assign them that way is idea for a more transparent implementation (I aspire to achieve).

So for BoxGeometry passing an object to the constructor like {dim:{width:1, height:1, depth:1}}  (and castShadow etc. would work as well as passing the 3 arguments (+ any others, a benefit). I think it actually exists in "parameters:" and not dim.
This reminds me of what might be another change request where object merging got an error when setting position (in that case doing it per key works [x, y, z] but I still have to check every key for "position" and handle it differently) of a light with this way of constructing the object.

I think they should all be callable with nothing THREE\[type\]\(\) and just have defaults. For box it would be 1, 1, 1 and I guess you could scale to size and have that become potentially animated too.
So the question is would the scaling effect children (but I guess that's suppose to go back to StackOverflow where there's a special way to turn that off or something I am recalling), except I'm asking about a better solution for constructors and wondering what superior alternative I'm missing otherwise.

Anyway I'm thinking one bit of code can generate all object types from an \<alternative source\> like so.

```
let item  = {type:"BoxGemoetry", size:{w:2, h:1, d:5}};
let thing = new THREE[item.type](item);
```

and have it skip things it doesn't know like type, maybe a second array of skipKeys, which is self explanatory.

Also I feel ideally you should be able to adjust them later, call it reuse. One case might be to pool created objects and then be able to re-purpose and reuse them. Sounds like that's impossible in cases with Geometry without blotting code but would be a nice idea. Geometry like a box should be able to change it's dimensions, no? I'd argue animate, but I'm sensing the confines of GL say otherwise.

**Comment by MasterJames** [comment]
Something untested like this would do it...

```
THREE.BoxGeometry = function ( width, height, depth, widthSegments, heightSegments, depthSegments ) {

	THREE.Geometry.call(this);

	this.type = 'BoxGeometry';

	this.parameters = {
		width: width || width.width || 1,
		height: height || width.height || 1,
		depth: depth || width.depth || 1,
		widthSegments: widthSegments || width.widthSegments || 1,
		heightSegments: heightSegments || width.heightSegments || 1,
		depthSegments: depthSegments || width.depthSegments || 1
	};
	this.widthSegments = this.parameters.widthSegments;
	this.heightSegments = this.parameters.heightSegments;
	this.depthSegments = this.parameters.depthSegments;

	var scope = this;

```

I'd use "let tp = this.parameters;" (probably not using 'let' yet here though so 'var'? I opt'd out.) to try and save a couple cycles, or better yet I'd probably not put *Segments on 'this' and instead reference them directly since there are only a few (only once or twice references to the child parameters needed) but I imagine that would break something somewhere.
Next I'm thinking one could put the actual build code in a function called 'build', so you could rebuild it. and then you separate the entire constructor so you can recall it anytime too.

Question: Would the idea of reuse or re-purposing Geo like this actually save enough cycles to care. [Ans: If any, time's a million, I guess so, but it depends on your implementation of pooling vs traditional I suppose.] This I'm less concerned about compared to just sending an object as the first argument when geometry is permanently pre-generated in the constructor phase.

_[Love the ActionScript reference to cube.as! I'm still a fan. Flash and papervision had come to a point where they needed to punch a hole through to GL, and then the hammer fell. Has it been about 3 years now?]_

**Comment by MasterJames** [comment]
EDIT: This actually makes more sense to my personal style.
```

	if(width === undefined) {
		width = {dims:{width:1,height:1, depth:1}};
		width.segs = width.dims;
	}
	var wd = width.dim;
	var ws = width.segs;
	this.parameters = {
		width: width || wd.width || 1,
		height: height || wd.height || 1,
		depth: depth || wd.depth || 1,
		widthSegments: widthSegments || ws.width || 1,
		heightSegments: heightSegments || ws.height || 1,
		depthSegments: depthSegments || ws.depth || 1
	};
	this.widthSegments = this.parameters.widthSegments;
	this.heightSegments = this.parameters.heightSegments;
	this.depthSegments = this.parameters.depthSegments;

```

The duplicate reference back to dimensions (dims) from segments (segs) is okay because it's not expected to change. I'm guessing if enabling 'reuse' (aka separation of actions from the constructor), to not do that would then be better.
```

	if(width === undefined) {
		width = {dims:{width:1,height:1, depth:1}, segs:{width:1,height:1, depth:1}};
		//width.segs = width.dims;
	}

```

**Comment by mrdoob** [comment]
I'm not a big fan of that kind of API to be honest.

**Comment by MasterJames** [comment]
Okay well that's unfortunate for me. It might be wiser for me to maybe have a helper or something that has either a replacement wrapper or inject a secondary caller like BoxGeometryWithObj otherwise I'll be stuck modifying the dev branch every time there's an improvement added I'll need.
Maybe that would integrate into the THREEjs somehow too, for those who see how it can be an the advantage in some situations.
Does any of that sound feasible? Can you suggest a best or better solution for my kind of situation?

**Comment by MasterJames** [comment]
Looks like the ObjectLoader is probably what I'm looking for.
I wondered if there are more examples of the structure or documentation to help with that other then this?
https://github.com/mrdoob/three.js/issues/3488

**Comment by satori99** [comment]
The wiki has some details on the the object format
https://github.com/mrdoob/three.js/wiki

**Comment by MasterJames** [comment]
Okay great thanks for that it brings some clarity. It's also in flux of course.
For now I'm going to try the harder route and so I'm looking at rebasing for eternity. Just because it would be less efficient or compressed to make a helper that adds a wrapper or overwrite the Geo Constructors to take objects. The main reason for now is I'm experimenting with a different system for referencing across multiple users so that's part of my uniqueness the names are the keys and an array of NameSpaces (that solve the multiple parent problem), so it's an experimental different rare use-case.
A send a special thanks for the help in my orientation (past, present, future) and to the excellent people of the THREE.js community for all they have achieved. I hope to do my part to help make THREE the future of computing (and not be felt as disruptive). I suspect THREEjs will continue to become more and more a powerful fully functioning competitor in the 3D/VR/AR (via JavaScript) space, by staying on it's currently flexible course, for the sake of the hardware changes that are sure to come.
