### ISSUE TITLE
The JsFiddle main example does not work

### ISSUE THREAD

**Issue by Nektro** [mrdoob/three.js#8039]
http://jsfiddle.net/f17Lz5ux/

The link where it says, "If everything went well you should see this." Does not display anything because  the version of three.js the fiddle contains is being served over http whereas jsfiddle is over https

**Comment by mrdoob** [comment]
Hmm, what browser is that with?

**Comment by Nektro** [comment]
Google Chrome 50.0.2635.0 canary (64-bit)

**Comment by mrdoob** [comment]
Oh...

**Comment by Mugen87** [comment]
@Nektro But the link in the README is not using https. When i click on the link, i get the http version with the working example.

Can you check in your browser console your network tab? Maybe you are getting a HTTP 302 with a redirect to https://jsfiddle.net/...

**Comment by makc** [comment]
the fiddle works fine in canary 50.0.2636.0 canary (64-bit) on mac

**Comment by makc** [comment]
ah wait, your link was http

**Comment by makc** [comment]
changing fiddle to
```
<script src="//mrdoob.github.io/three.js//build/three.min.js"></script>
```
makes it happy again

**Comment by Nektro** [comment]
Going to the plain http version of jsfiddle works just as expected. Thank you guys!

**Comment by Mugen87** [comment]
Everything works fine as long as users don't change the protocol. Not sure if there is a need to change something....

**Comment by Nektro** [comment]
Would it be possible to use a https version of three.js in the future, such as from [cdnJS](https://cdnjs.cloudflare.com/ajax/libs/three.js/r73/three.min.js)?
