### ISSUE TITLE
Any interest for a PR for clipping functionality inside THREE.Shape?

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#8046]
Would there be interest in a pull request for shape clipping using a [Sutherland–Hodgman algorithm](https://en.wikipedia.org/wiki/Sutherland%E2%80%93Hodgman_algorithm).

I made a fiddle [here](http://jsfiddle.net/wilt/w67tzfhx/122/) to demonstrate the working.

If there is interest I could make a pull request for this.

**Comment by MasterJames** [comment]
Very nice )! does it work to perform boolean operations? in 3D too? {Wishful thinking!}

**Comment by Wilt** [comment]
@MasterJames Yes you can extrude the shape after the clipping. The `THREE.Shape` class has the extrude method in the API. Check [my updated fiddle](http://jsfiddle.net/wilt/w67tzfhx/123/)

**Comment by MasterJames** [comment]
Right of course there's that. I really do not know if there's any 3D boolean in three js yet but alas there are other ways to achieve that when modelling. Trimming a 3D model is slightly different again I suppose you'd extrude the trimmer before performing the trim on another already 3D object.
It seems from historical observation to be very difficult to do well without numerous unknown edge cases. So ya experience suggests it was wishful thinking.
Your reminder of extruding afterward was also welcome.

**Comment by Wilt** [comment]
@MasterJames Sorry to disappoint you, but I am not able to change a 2D clipping algorithm into 3D boolean operations by snapping my fingers... :)

**Comment by MasterJames** [comment]
Sorry I should have looked closer. Please pardon my overstep. I agreed. It is apparently almost impossible especially with triangulation. I think you'd need procedural shapes or something at that point.

**Comment by Wilt** [comment]
After reading [here](https://github.com/mrdoob/three.js/issues/5959) I realized this my attempt to add a clipping method in Shape is not worth your time...

Would be useful though if such ear-cut algorithm would be tied to the `THREE.Shape` API for clipping shapes though.

**Comment by jhlee4** [comment]
dang it would have been nice to have some 2d boolean operations in shape class.
