### ISSUE TITLE
WebGL: INVALID_VALUE: texImage2D: bad image data 

### ISSUE THREAD

**Issue by fredrik955** [mrdoob/three.js#8051]
I am having a problem on the Android's native browser when loading a texture file bigger than 2047x2047 (yes not 2048). When I am loading a 2047x2047 image then three.js resizes the image to 2048x2048 and everything turns out fine, but when I am using a 2048 texture image I get this error message:
WebGL: INVALID_VALUE: texImage2D: bad image data 
and the texture turns out black.

Is there anyway that I can load a 1024 texture, and then update the texture to an 4096 texture if and only if the device supports it?

I am using the newest version of three.js

**Comment by parth-gudhka** [comment]
@fredrik955 Did you get the solution?

**Comment by fredrik955** [comment]
@parth-gudhka No, I am sorry. Never figured it out, and I tried to search after a answer on Stackoverflow.

**Comment by mrdoob** [comment]
@fredrik955 could you create a jsfiddle?
