### ISSUE TITLE
XHRLoader not handle 404 return status as error

### ISSUE THREAD

**Issue by sbarex** [mrdoob/three.js#8053]
When a file is loaded with `XHRLoader.load` the callback `onLoad` is also called when the file was not found. 
To the `onLoad` function is passed the html formatted error message for the not found file (depending of the webserver configuration) and not the expected data, and not know that the load process if failed. 
I suggest to pass to the `onLoad` function also the event or call `onError` if the status code is not 200.
The same change on XHRLoader must be appied to all loader that use XHRLoader inside the code.

**Comment by SilentFlame** [comment]
@sbarex  can you please be a bit more elaborate about the isuue,
as I would like to work on this.

**Comment by sbarex** [comment]
I use this code:

```JAVASCRIPT

var loader = new THREE.XHRLoader();
loader.load( 
	url, 
	
	// onload
	function ( data ) {
		console.info('data loaded, start parsing…');
		parse( data );
		// ...
	}, 
	
	// onprogress
	undefined,
	 
	// onerror
	function(event) {
		console.error('error loading data', event);
	}
);

```

I suppose to fetch data in a specific format that will be parsed inside the onload function.

When I try to load an url that not exists on the webserver, `THREE.XHRLoader` call always `onload` function and never the `onerror`.  The `onload` get in the `data` param the code returned by the webserver (typically an html with the "not found" error message) but I cant know that this data is an error message and it's not in the format required for my parser.

`THREE.XHRLoader` use the standard javascript `XMLHttpRequest` class to fetch the url.

Searching on [StackOverflow](http://stackoverflow.com/questions/10584318/when-should-xmlhttprequests-onerror-handler-fire), i found that `XMLHttpRequest` fire onerror event only when there is an error on the _network level_. The 404 response is considered as a data successful fetched.

If I debug the `THREE.XHRLoader`, inside the `onload` event of the `XMLHttpRequest` object, I see that the `event.target.status` is correctly filled with the 404 value (file not found).

I look inside jQuery to see how handle `XMLHttpRequest`.
It's consider the load successful if
`status >= 200 && status < 300 || status === 304`.

So, I suggest to pass the status to the callback onload or the full response event.

Remember that `THREE.XHRLoader` is used inside the others loaders, so you need to update also they code to check the status value.

I'm using threejs ver. 73, google chrome, nginx.

**Comment by leitzler** [comment]
@sbarex give it a try with ver 74 (see #7497).
