### ISSUE TITLE
vrml loader loads model with extra holes

### ISSUE THREAD

**Issue by verybigelephants** [mrdoob/three.js#8054]
i have this simple model of a vase 
[vase.txt](https://github.com/mrdoob/three.js/files/114381/vase.txt)

however, when i try to load it with the THREE.VRMLLoader i see some strange holes, while the model looks normal in vrml viewers (i have taken [this sample vrml loader](http://threejs.org/examples/webgl_loader_vrml.html) and just replaced the file path on my local server )

![vase](https://cloud.githubusercontent.com/assets/3118985/12758560/21ec1ca6-c9dd-11e5-8efc-02531edcd3cd.png)

**Comment by makc** [comment]
Oh man, did I break things again? Try [this revision](https://github.com/mrdoob/three.js/blob/760252a56043ef0031f08d4e56b6582c9224b6a2/examples/js/loaders/VRMLLoader.js).

**Comment by verybigelephants** [comment]
nope, same thing happens with that revision 
here's an example http://testing.vomit.me/vrml/

**Comment by verybigelephants** [comment]
@mrdoob i just wanted to let you know that you're a god for all that you do

**Comment by verybigelephants** [comment]
you guys are awesome!
