### ISSUE TITLE
Support for non-curve path in Extrude Geometry

### ISSUE THREAD

**Issue by JetStarBlues** [mrdoob/three.js#8056]
According to the [docs][1], `Extrude Geometry` only accepts an `extrudePath` that is a `THREE.CurvePath`.

Why only a curve path? Why not any type of path?

Example use case:
I wish to extrude a geometry along a path but retain the sharp, precise corners of the path. The path is a grid-like/circuit-like pattern that does not look good with smoothed corners.

[1]: http://threejs.org/docs/#Reference/Extras.Geometries/ExtrudeGeometry

**Comment by Wilt** [comment]
According to [the documentiation](http://threejs.org/docs/index.html#Reference/Extras.Core/CurvePath) a `THREE.CurvePath` is:

> A CurvePath is simply an array of connected curves, but retains the api of a curve.

So an array of curves can also be an array of [`THREE.LineCurve3`](http://threejs.org/docs/index.html#Reference/Extras.Curves/LineCurve3). And a `THREE.LineCurve` is a simple straight line between a start and an end point.

Did you try adding several line segments (several instances of `THREE.Line3`) to your path and use that for extruding?

**Comment by JetStarBlues** [comment]
Oh, I see! Thank you. Using it that way works!
