### ISSUE TITLE
Custom UVs on standard Geometry

### ISSUE THREAD

**Issue by rfm1201** [mrdoob/three.js#8058]
I'm writing an editor with three.js. It means that I need to save a scene and be able to restore it with all features. I fact, I would prefer the standard three.js save/restore process to do the job.
My current problem is to map a user's picture on a standard geometry in a flat style (like putting a sticker). To do that, I may have to modify UV. My problem is that three.js doesn't have anything to save/restore UVs on a standard geometry?
I don't want to go for a Geometry or a BufferGeometry because I need to be able to change the geometrical properties of the object and need to stay with the actual standard geometry save/restore process.
So I need to modify the toJSON method of Geometry.js and the matching parseGeometries method of ObjectLoader.js.
Before I do my own thing, is there something currently in progress to address this problem?
In a previous pull request (https://github.com/mrdoob/three.js/pull/7991), mrdoob spoke of a UVMapper class. I couldn't find anything in the code that looks like a UVMapper class. Does someone know what it is?

**Comment by makc** [comment]
> To do that, I may have to modify UV.

sorry, but to do that you will have to modify whole geometry, not just UV. also, there is DecalGeometry in examples

**Comment by mrdoob** [comment]
Maybe we could add custom geometries to `ObjectLoader` so the user could have a callback when one of these are found and build their own custom one?

**Comment by rfm1201** [comment]
I'm writing a simple editor for non 3D aware people.

DecalGeometry was not chosen when I started because the user may want to move or resize the picture added. I choose to use a canvas as a texture because it seems softer on CPU and much more flexible. Right now I have no performance issue with that solution. I just have problems with UVs not suitable for my users (for example LatheGeometry, top and bottom side of CylinderGeometry).

In a near future I may have problem with simple deformations (à la SketchUp) of a standard geometry. So a solution not focused on UV is welcome.

**Comment by Mugen87** [comment]
I vote to close this issue. Custom uv generation needs to be solved on application level.
