### ISSUE TITLE
[FR] Add a Disc (Annulus) Geometry (2D Torus)

### ISSUE THREAD

**Issue by mgreter** [mrdoob/three.js#8060]
Please excuse if this was already proposed/asked, but I wasn't able to find any related issues either on github or by google. My use case is to draw the rings of saturn, but I guess there are many others (like drawing a CD). Had to google the mathematical term myself and after I found it I'm not sure if I really like to call it `AnnulusGeometry` for obvious reasons :laughing:. Btw. to be clear, I'm talking about a 2D Torus.

I already made an implementation and it seems to work quite well. I just took off from `CircleGeometry` and changed it accordingly as far as my knowledge goes. Had to guess a little with the `uv` and `normal` vectors and I haven't yet tested it with more advanced materials (specially with textures). At first I thought it could be implemented with an additional option for `CircleGeometry`, but I don't think that is really worth the hassle, since it would probably need a lot of if statements.

Is there a chance that this would be added to THREE.js? I'm unsure since there are probably hundreds of different geometries that could be usefull. But if it is, I would create a PR for this after any open questions and obvious issues would be addressed. Maybe some of the three.js gurus already see some? I'm really not too sure about how I create the indices, as I had to do some trials to get them right with lighting.

So for future reference, here the interessting part of implementation:
```js
THREE.DiscBufferGeometry = function ( inner, outer, segments, thetaStart, thetaLength ) {

	THREE.BufferGeometry.call( this );

	this.type = 'DiscBufferGeometry';

	this.parameters = {
		inner: inner,
		outer: outer,
		segments: segments,
		thetaStart: thetaStart,
		thetaLength: thetaLength
	};

	inner = inner || 20;
	outer = outer || 50;
	segments = segments !== undefined ? Math.max( 6, segments ) : 16;

	// segments must be even
	if (segments % 2) segments ++;

	thetaStart = thetaStart !== undefined ? thetaStart : 0;
	thetaLength = thetaLength !== undefined ? thetaLength : Math.PI * 2;

	var vertices = segments + 2;

	var positions = new Float32Array( vertices * 3 );
	var normals = new Float32Array( vertices * 3 );
	var uvs = new Float32Array( vertices * 2 );

	// center data is already zero, but need to set a few extras

	for ( var s = 0, i = 0, ii = 0 ; s <= segments / 2; s ++, i += 6, ii += 2 ) {

		var segment = thetaStart + s / segments * thetaLength * 2;

		positions[ i + 0 ] = inner * Math.cos( segment );
		positions[ i + 1 ] = inner * Math.sin( segment );

		positions[ i + 3 ] = outer * Math.cos( segment );
		positions[ i + 4 ] = outer * Math.sin( segment );

		normals[ i + 2 ] = 1; // normal z
		normals[ i + 5 ] = 1; // normal z

		uvs[ ii + 0 ] = ( positions[ i + 0 ] / inner + 1 ) / 2;
		uvs[ ii + 1 ] = ( positions[ i + 1 ] / inner + 1 ) / 2;
		uvs[ ii + 2 ] = ( positions[ i + 3 ] / outer + 1 ) / 2;
		uvs[ ii + 3 ] = ( positions[ i + 4 ] / outer + 1 ) / 2;

	}

	var indices = [];

	for ( var i = 1; i <= segments; i += 2 ) {

		indices.push( i - 1, i, i + 1 );
		indices.push( i + 1, i, i + 2 );

	}

	this.setIndex( new THREE.BufferAttribute( new Uint16Array( indices ), 1 ) );
	this.addAttribute( 'position', new THREE.BufferAttribute( positions, 3 ) );
	this.addAttribute( 'normal', new THREE.BufferAttribute( normals, 3 ) );
	this.addAttribute( 'uv', new THREE.BufferAttribute( uvs, 2 ) );

	this.boundingSphere = new THREE.Sphere( new THREE.Vector3(), outer );

};
```

Thank you very much for consideration and for creating this awesome framework!

**Comment by mgreter** [comment]
I'm sorry, please forget this, no idea why I didn't find this before *sigh*
http://threejs.org/docs/#Reference/Extras.Geometries/RingGeometry

:facepunch:

**Comment by WestLangley** [comment]
@mrdoob Would you like `RingBufferGeometry` and `CircleBufferGeometry`?

If so, maybe @mgreter would be interested in contributing that?  ; - )

**Comment by mrdoob** [comment]
@WestLangley that'd be great! 😀

**Comment by mgreter** [comment]
@mrdoob @WestLangley opened PR https://github.com/mrdoob/three.js/pull/8062
