### ISSUE TITLE
Bones local scale update

### ISSUE THREAD

**Issue by lo-th** [mrdoob/three.js#8070]
hello juste a idea 

That can be cool to add one variable to bone
this.scalling = null;

and on THREE.Skeleton.prototype.update add after matrix
if( this.bones[ b ].scalling !== null ) matrix.scale( this.bones[ b ].scalling );

now we can adjuste scale of each bone as you like 
bone.scalling = new THREE.Vector3( 1, 0.5, 1 );
i use this in my avatar lab: http://lo-th.github.io/Avatar.lab/

that's usefull for change morphology or face animation

**Comment by mrdoob** [comment]
Maybe `Bone` could set `scale` to `null` in the constructor. And then we can override with your code?

**Comment by lo-th** [comment]
no scale in bone can be usefull, it's better to keep

**Comment by mrdoob** [comment]
You mean an additional scale then?

**Comment by lo-th** [comment]
yes, only for local scale

**Comment by lo-th** [comment]
on avatar lab i use same skeleton for woman and man
but i need to change some value for example shoulder, size of arms ...

next step is to add a full controle on each bone
for any type of morphology. giant, dwarf ...

**Comment by mrdoob** [comment]
Hmm... Isn't it a matter of cloning the skeleton?

**Comment by lo-th** [comment]
is better to export only one skeleton with animation and same vertex assign 
i have to add full morphing bone to my demo
something like https://www.youtube.com/watch?v=ZvALq8G48Fk

**Comment by mrdoob** [comment]
But, isn't the skeleton separated from the animation? As long as the skeleton has the same structure and bones, it could reuse one animation or another, no?

**Comment by lo-th** [comment]
yes is juste more simple for export and the file size is reduced

**Comment by lo-th** [comment]
here a concret exemple of what can do local bone scalling 
http://lo-th.github.io/root/morph/

**Comment by mrdoob** [comment]
I think this will be easier to understand if you did a PR.

**Comment by Mugen87** [comment]
> I think this will be easier to understand if you did a PR.

Indeed. In any event, I'm not sure we want to support such a specific use case. Especially since no other dev requested such a feature so far (at least to my knowledge).

**Comment by lo-th** [comment]
yes i find another method far better than add scalling to bones and calculate on time
for a skeleton i just have to recalculate invers and scale at start 
i make demo soon

**Comment by mrdoob** [comment]
@lo-th should be close this one then?

**Comment by lo-th** [comment]
yes is easy to add externaly
