### ISSUE TITLE
Three.js Examples Viewers

### ISSUE THREAD

**Issue by theo-armour** [mrdoob/three.js#8072]
There are currently two sets of Three.js example files:
1. [http://threejs.org](http://threejs.org/) home page
2. [http://mrdoob.github.io/three.js/examples/](http://mrdoob.github.io/three.js/examples/)

I visit these pages - particularly the latter - almost on a daily basis - looking for solutions and inspiration - and I don't think I am the only person doing this.

Some of the issues are: You want to view the examples faster. You want more information about them. And you want to see more examples - both old and new.

The recent addition of the scripts for generating multiple views by @greggman and @paulmasson caused me to wonder if their ideas could be applied to the examples viewers.

I like the viewport/scissoring techniques they use, but for the moment I am exploring the idea of instancing and discarding renderers in rapid succession.

The following URLs link to scripts that explore a variety of presentation scenarios for viewing  large numbers of examples in a speedy manner:

[Three.js Basic Viewer](http://jaanga.github.io/documents/threejs-viewers/threejs-viewer-basic/) - the template used to start things rolling. Uses GitHib API to source file names 
[Three.js Viewer Gallery](http://jaanga.github.io/documents/threejs-viewers/threejs-viewer-gallery/) - three views per row in ninety rows. 
[Three.js Viewer Mobile](http://jaanga.github.io/documents/threejs-viewers/threejs-viewer-mobile/) - sliding menu + slide show
[Three.js Viewer One-Pager](http://jaanga.github.io/documents/threejs-viewers/threejs-viewer-one-pager/) - all ~270 Three.js examples displayed on a single page
[Three.js Viewer Three.js](http://jaanga.github.io/documents/threejs-viewers/threejs-viewer-threejs/) - Menu with same file order and categories as Three.js
[Three.js Viewer Timeline](http://jaanga.github.io/documents/threejs-viewers/threejs-viewer-timeline/threejs-viewer-timeline-r1-@.html) - Most example files of releases from near the beginning all the way to 'dev'

And for viewing all the Featured Projects:

[Three.js Viewer Featured Gallery](http://jaanga.github.io/documents/threejs-viewers-featured/threejs-viewer-featured-gallery/) - Needs some patience but not much. Makes noise.

Sorry for the quantity of links. It's easier to write a bunch of small scripts rather than one big one. And there's more scripts up there including [6 on 1 page](http://jaanga.github.io/documents/threejs-viewers/). But it's enough for you to get the picture.

The mission includes:
- Eat your own dog food: Use 3D to show 3D. This is covered in much more detail in a [blog post](http://jaanga.github.io/request-jaanga-blog-posts.html#2016-01-29_threejs-examples-viewer-use-3d-to-show-3d-not-2d_threejs.md)
- The aim is that the code should be no more complicated than the typical Three.js example "— in other words, for dummies". It should be just as easy for you as a Three.js beginner user to create a viewer for your examples as it is for you to create new examples.
- Additions and deletions of scripts to the examples folders should be handled automatically. You should not need to edit a script when new files are added. Especially when you can use the GitHub API to track the files.
- The viewers should add value. You should be able to view slide shows, statistics, source code, revisions and more.
- The viewer should be fast, obey standards and use the latest, best tech. And you should be able to access lots of sister viewers adapted for different tasks and agendas.

All of this is a work-in-progress at an early stage - especially on mobile devices. 

My question is whether any of you would be interested in discussing or collaborating in an effort to take the viewing of Three.js example files to the next level?

**Comment by mrdoob** [comment]
Wow. r25 examples... Blast from the past!

I like the stress test this approach enforces. Initially I used this viewer because the code was not optimised enough so many examples could run at the same time.

Things may start to be different now.

**Comment by theo-armour** [comment]
@mrdoob 

>> Things may start to be different now.

Bingo!

And that's what's good about Three.js. It always looks to what's coming up in the future with as much care as what was created in the past. And - at the same time - many of the old demos keep getting up dated. Everything move forward together.

>> I like the stress test this approach enforces.

Yup. Scrolling down the gallery or one-page viewers with the console open shows you what what examples need work

***

Sorry just babbling. I am delighted you welcome these experiments. Therefore I will continue playing around. I want to do things such as adding @spite's rStats and @zz85's Three.js Inspector to the viewers. And getting the interaction to work on mobile devices needs work.

I will also be seeking permission to view other examples. For example, I already permission from Professor Lawlor: 

http://jaanga.github.io/documents/cs482/viewer/cs482-viewer-r1.html

The main thing is that this project makes viewing the examples even more fun. For example, the sounds that come out when you scroll the the Featured Projects is a lot of fun.

**Comment by greggman** [comment]
They aren't good enough now on my machine. Those samples all crash the tab for me

**Comment by theo-armour** [comment]
@greggman 

Yes, the viewers that load multiple renderers such as the Gallery and the One Pager are highly like to have issues

Some examples have more issues than others. It's worth having the console open as you scroll. ;-)
The Featured Projects Gallery viewer is highly problematic, because many of these are huge consumers of resources.

On the other hand the [Basic Viewer](http://jaanga.github.io/documents/threejs-viewers/threejs-viewer-basic/threejs-viewer-basic-r1-@.html) should pose few problems as it loads only one example at a time. It's only real benefit is that it uses the GitHub API to obtain a list of file names.  

Also the [Timeline](http://jaanga.github.io/documents/threejs-viewers/threejs-viewer-timeline/threejs-viewer-timeline-r1-@.html#canvas_geometry_text) and Three.js style menus versions load only one at a time.

I would be interested in learning if these viewers have more issues than the current viewer. And, in particular, on what machines and browsers.

I have tested on Chrome and FF on Windows withe Core i7 and Nvidia GPU and Chrome on a Chromebook Pixel, Nexus phone and Nexus Tablet. 

I would be even more interested in hearing from you in particular about where the viewing of examples can go. The reason I started this project was because I saw your wonderful webgl_multiple_elements example. This made me think about viewing multiple stand-alone files. 

The issue is that there are now many hundred of Three.js examples on GitHub. I'm thinking of Joe Dirksen's examples:

* [80 Recipes from Three.js Cookbook]( http://www.smartjava.org/content/all-80-recipes-threejs-cookbook-online )
* [109 Examples from Learning Three.js]( http://www.smartjava.org/content/all-109-examples-my-book-threejs-threejs-version-r63 )
* [Examples from Essential Three.js]( https://github.com/josdirksen/essential-threejs )
 
There's also Tony Parisi's examples from his book, Professor Stemkoski's example and more. It would be really nice to have a speedy way of scanning through all the files. @mrdoob is an excellent history at making files viewable. Just look at http://mrdoob.com/ - which dates back to the Flash era.

But the way we will view files tomorrow is not likely to be the way we viewed files yesterday.  Or put it in a more reasonable way. There will be yesterday's ways and there will be new ways. And both can live happily together. There are many examples. There can be many viewers.

In any case, I'd be delighted to hear some thoughts from you - or anybody else - about ways of making viewing Three.js files faster, easier and more fun.

**Comment by greggman** [comment]
Why is using the github API a plus? If clone the repo and want to run everything locally I'll have no github API running.

**Comment by makc** [comment]
why not do this the way shadertoy does? things do not run unless you hover them. this way, of course, all the examples must be rewritten into the modules with the same api to live in the same page happily.

**Comment by theo-armour** [comment]
@greggman 

> Why is using the github API a plus? If I clone the repo and want to run everything locally I'll have no github API running.

Two really interesting comments. Thank you.

### GitHub API

The issue with most APIs is that they are written for full-stack developers and are oriented towards server-side processes.

On the other hand, with Three.js: 

> The aim of the project is to create a lightweight 3D library with a very low level of complexity — in other words, for dummies. <people like me>

And, given the static hosting on GitHub Pages, the interesting stuff has to happen client-side.

But, unlike most APIs, the GitHub API is intriguing because of this URL:

https://api.github.com/repos/mrdoob/three.js

Select any link in the page that appears. In Chrome, bring up the context menu and click the 'Go to' item/ And, presto, useful data appears.

Once you get the basic hang of it, The GitHub API docs and StackOverflow answer most of the rest of the questions.

In my opinion this helps the GitHub API become readily accessible to dummies like me. 

In turn, access to the full GIT history should enable a number of new features to be added to viewers.

For example, the following GitHub API call brings up the date, author and message of every commit for a particular example.

https://api.github.com/repos/mrdoob/three.js/commits?path=examples/webgl_geometry_colors_lookuptable.html

Using this call it would be easy, for example, to build a viewer lists only the examples that have been modified in the past month.

### Running Locally

Let's say you are riding the train from Barcelona to Granada in a third class carriage with no Internet and your WinPhone has just died. And you need to look at the Three.js examples.

You want to look at one of the Feature Projects, but you are out of luck for they are only accessible when online.

So you go to the Three.js examples folder and start clicking on file names. Thank goodness all the scripts appear and operate just like normal. Did you need to use the viewer? Of course not, all the files are just there ready to be clicked on.

***

So, I do not see many issues with new viewers adding online access. Loading files.js could always be a fall-back option built into scripts. What's more fun to consider are the new possibilities that online access to the GitHub API might offer.

**Comment by theo-armour** [comment]
@greggman 

> They aren't good enough now on my machine. Those samples all crash the tab for me or run at incredibly low frame rates

See also my previous response

My bad. 

What I frequently forget to consider is the Internet connection speed. My data seems to be coming in at 25 mbs. People running on, say, 5 mbs are likely to have trouble running the scripts that try to load 15 renderers at a time.

So the easy fix would be to have a switch that reduces the maximum number of running renderers down to one or two. This could be enable as part of a permalink maybe.

The other aspect to consider is that gigabit speeds are on the way. For the past few weeks I have walked by ATT trucks in my neighborhood laying down fiber-optic cables.

How should viewers behave when all the scripts are loaded before you know it?

**Comment by theo-armour** [comment]
@makc 

Thank you for joining the conversation

> why not do this the way shadertoy does? things do not run unless you hover them. this way, of course, all the examples must be rewritten into the modules with the same api to live in the same page happily.

Really good observation about Shadertoy not running unless you hover. Thanks

I had sort of been thinking about this but had only thought about pr0n sites as an example. ;-)

Two thoughts regarding your suggestion

1. I really like seeing everything moving all at once. Use 3d to show 3D. And the next generation of CPUs and Internet should be able to handle the processing fairly easily. Yes, we have to deal with the old timey stuff, but the priority has to be 'will we be useful tomorrow?'. Build for the past. Design for the future.

2. Actually there may not need to be any re-writing. Using the `<iframe srcdoc=variableName ></iframe>` you can load highly regexed code. So one could disable and enable render() and animate() functions in non-hovered views. This would be useful with galleries that wanted to show more than sixteen views on screen at once. 

For example, say, you have a hundred thumbnails visible at once. Only the 16 thumbnails closest to the cursor would be wiggling while the others were static. And, come to think of it, this might be a useful application of @greggman's view and scissoring technique

**Comment by theo-armour** [comment]
Here's two new Three.js Examples Viewers

[Three.js Viewer Info R1](http://jaanga.github.io/documents/threejs-viewers/threejs-viewer-info/ )

Click on the file name in the menu to view the example as well as the date, author and message of every commit to each of the Three.js example files.

Note: this would the type of viewer that would be hard to create - let alone maintain - without access to the GitHub API.

[Three.js Viewer Canvas R1]( http://jaanga.github.io/documents/threejs-viewers/threejs-viewer-canvas/ )

View only Three.js example files that do not support WebGL. Includes slide show capability and full screen mode. This script may be used to display 'art shows' on old computers. Tested on a 2008 eee PC with Atom 270 processor running Firefox from Ubuntu 15 on a USB stick.

**Comment by MasterJames** [comment]
Just noting this is unviewable on mobile. The menu occupies the entire screen space mostly.

**Comment by theo-armour** [comment]
@MasterJames 
Can you see the 'hamburger' button? The three bars. Click on it and the menu should slide out of the way.

**Comment by MasterJames** [comment]
Sideways is okay. No Hamburger  found. Red Square character doesn't hide the menu.

**Comment by theo-armour** [comment]
Will do a screen capture. Back in a few minutes

**Comment by MasterJames** [comment]
![screenshot_2016-02-06-20-31-14](https://cloud.githubusercontent.com/assets/1840183/12870947/c1e39832-cd12-11e5-9330-110d92568d6c.png)

**Comment by theo-armour** [comment]
@MasterJames 

Thanks for the screenshot.

Yup. There's no hamburger on the 'Info' viewer.

And should there be? The Info script shows the menu, the script and all the commits text - which can run to several hundred lines. 

To try to get an app like this to work on a mobile might not be worth the effort.  It would be like trying to get Eclipse or Visual Studio happy on a mobile.

Both the 'Mobile' and 'Canvas' viewers are much better choices for mobile.

But if you say "I can has cheezburger?" I will add one to 'Info'. ;-)

**Comment by MasterJames** [comment]
I see the one you call canvas has the burger so that looks usable on mobile. The other one is okay turned sideways too. Keep up the good work.

**Comment by theo-armour** [comment]
@MasterJames 

Thanks for the follow-up.

Watch this space for more viewers on Sunday...

**Comment by theo-armour** [comment]
Here are two more Three.js Viewers

[NASA Viewer Basic R1](http://jaanga.github.io/documents/threejs-viewers/nasa-viewer-basic/ )

This viewer ebables you to viewe the 331 STL models from the [NASA GitHub](https://github.com/nasa/NASA-3D-Resources) web presence. Some models - especially the one with lunar landing sites or entire asteroids - take a long time to load. Some are over 10 MB. Getting a progress indicator for the STL Loader is a wishlist item.

The interesting thing about this loader is that it tries to follow the typical rule of Three.js examples that there should be no external dependencies other than Three.js and a few other libraries. This caused an issue with the current series of viewers.

The current series normally uses an iframe load to external files that load Three.js and do all the heavy lifting. But STL files are data and need a full Three.js HTML  file to load them. The usual easy thing is to create a small file that just loads STL files and call that file every time an STL file is needed. But that external file would creates a dependency that would break the examples rule.

It turns out that iframes have this wonderful feature. They can load external files. But also they can load and display any variable by using `srcdoc=` instead of 'src='. <[Except for IE and Edge](http://caniuse.com/#feat=iframe-srcdoc)> 

And with the ES6 template strings turning text into variables is easy. <except for Safari>

Anyway, it's all in one file of just 200+ lines of fairly basic code

[Three.js viewer rStats]( http://jaanga.github.io/documents/threejs-viewers/threejs-viewer-rstats/ )

This example also uses `iframe srcdoc=` but for a different reason. @spite has built an amazing WebGL stats app: [rStats]( https://github.com/spite/rstats ). The idea in this viewer is to inject  the rStats code into all the Three.js examples client-side. Of course, this doesn't work because I don't really know what I am doing. But sometimes - when there aren't cross-origin issues loading textures and it needs a WebGL renderer and etc - you will see some stats almost being displayed properly.

So now there are ten viewers ( plus the featured projects viewers). But perhaps the most fun one is the home page for the folder:

[Three.js Viewers]( http://jaanga.github.io/documents/threejs-viewers/ )  

Every time viewer viewer loads it requests the URLs of all the viewers in the subfolders and loads them. If you don't have good Internet bandwidth it's no fun. But if you have, say, a 100 mbs then welcome to the future.

**Comment by theo-armour** [comment]
>> Things may start to be different now.

And you have to start somewhere.

As @greggman pointed out, the viewer examples posted here may not be everyone's cup of tea. 

On the other hand they mostly appear to be working and do offer new visualization paradigms.

I would like to continue working on the scripts and would especially like to collaborate with people who need viewers.

So my suggestion is that two or three of the viewers be added to the Three.js examples folder - perhaps in a sub-folder titled 'viewers'

Having said that, the viewers in their current state are not yet ready for production.

* The coding style needs to be brought into line with the Three.js style
* Testing needs to be carried on on a greater variety of browsers and hardware
* Effort needs to be made to get the viewers work satisfactorily on mobile devices

If you think this is a good idea, then I will start the upgrade process and create a fork with a demo folder with what I think are suitable example viewer contents.

I should also point out that I do my day-to-day coding based on the current dev version of Three.js. So it should be a fairly straightforward process for me to keep the viewer scripts up to date.

Do you think adding new types of viewers will help Three.js continue to be different?

**Comment by theo-armour** [comment]
@mrdoob any thoughts on my previous post?

**Comment by Mugen87** [comment]
With the design refresh, the example viewer looks good on desktop and mobile. I think we can close the issue and refer to #14140 instead.
