### ISSUE TITLE
Exporting to consoles

### ISSUE THREAD

**Issue by iamdriz** [mrdoob/three.js#8075]
Apologies if this has been asked before, but I couldn't find anything on this when Googling.

But has anyone exported a Three.js based game to any consoles? We can get a game built in Three.js to work on Windows, Mac, and Linux by packaging it inside something like http://electron.atom.io/ and onto iOS, Android and Windows Phone with PhoneGap but what about consoles like PS4 and Xbox One?

**Comment by MasterJames** [comment]
If the console has a modern Web browser it could certainly support webGL I imagine.

**Comment by theo-armour** [comment]
@iamdriz 

### Three.js on OS4

Don Olmstead wrote the PS4 OS based on WebGL

https://plus.google.com/+DonOlmstead/posts/Mzy6VEAwHaa

See also his presentation:

[Optimizing WebGL Applications](https://docs.google.com/presentation/d/1iJH3N8U7i4MZRDlsO1VBtMVb90ULVmro5SsFXuzRGOQ/pub?start=false&loop=false&delayms=3000&slide=id.p )

So my guess is that you can run Three.js on the PS4 - even though Don Olmstead seems to have a love/hate relationship with Three.js.

### Xbox One

I'm not so sure, but the Three.js [webgl_kinect]( http://mrdoob.github.io/three.js/examples/#webgl_kinect ) example shows some connection.

And Babylon.js is running on the xBox:

http://www.html5gamedevs.com/topic/18582-xbox-one-supporting-webgl-and-babylonjs/

**Comment by Mugen87** [comment]
The [three.js forum](https://discourse.threejs.org/) is the preferred place for such topics now.
