### ISSUE TITLE
Raycaster.intersectObjects() not returning anything?

### ISSUE THREAD

**Issue by JohnnyDevNull** [mrdoob/three.js#8081]
I have similar problems to this ones: 

http://stackoverflow.com/questions/31072742/raycaster-intersectobjects-not-returning-anything
http://stackoverflow.com/questions/29688618/raycaster-intersectobjects-does-not-work-gives-the-empty-array-using-three-js

so i took a watch at the examples and researche every line of code:

http://threejs.org/examples/#webgl_interactive_cubes
http://threejs.org/examples/#canvas_interactive_cubes

but nothing will work. Here comes my code:

```
    //controls = new THREE.OrbitControls( camera, renderer.domElement );

	raycaster = new THREE.Raycaster();

	mouse = new THREE.Vector2();
	clickMaterial = new THREE.SpriteMaterial({
		color: 'red',
		size: 5
	});

[...]

	for(var i = 0; i < system.length; i++) {

		var object = system[i];

		if(object.type == 'star') {

			scene.add( SPACELIB.createStar( object ) );

		} else if (object.type == 'planet') {

			scene.add( SPACELIB.createPlanet( object ) );

			if(SPACELIB.pathHelper) {

				scene.add( SPACELIB.createPathHelper({
					radius: object.orbit.radius,
					visible: {from: 50, to: 10000}
				}));
			}
		}
	}

[...]

function onDocumentMouseMove( event ) {

	event.preventDefault();

	mouse.x = ( event.clientX / window.innerWidth ) * 2 - 1;
	mouse.y = - ( event.clientY / window.innerHeight ) * 2 + 1;

}

function onMouseDown( event ) {

	event.preventDefault();

	raycaster.setFromCamera( mouse, camera );

	var intersects = raycaster.intersectObjects( scene.children );

console.log(intersects); // < --------------- is every Time a empty []

	if ( intersects.length > 0 ) {

		intersects[ 0 ].object.material.color.setHex( Math.random() * 0xffffff );

		var particle = new THREE.Sprite( clickMaterial );
		particle.position.copy( intersects[ 0 ].point );
		particle.scale.x = particle.scale.y = 16;
		scene.add( particle );

	}
}

```

I can't find the problem. Do i something wrong? Also the onMouseOver effect from the example doesn't work.

Please Help me.

**Comment by JohnnyDevNull** [comment]
I think i have found the problem. I have to add the meshes to an extra array. An intersectObjects over the scene.children don't work, because there are other objects in there with the meshes.

So when i give the intersectObjects( mesh[] ) an mesh array than it works.

**Comment by MasterJames** [comment]
If the function itself internally did this you can wrap it before or not.

    if (Array.isArray (mesh) === false) mesh = [mesh];

I'm wishing for A mesh.on function to 3DObject like THREEx did but that's broken now. (4y old.)

**Comment by JohnnyDevNull** [comment]
Yes! mesh.on would be amazing...

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

**Comment by MasterJames** [comment]
I guess i'll ask if Mesh.on could be considered and discussed on pros and cons as a feature request.

**Comment by JohnnyDevNull** [comment]
@WestLangley if you read my post above there were two unanswered similar questions on stackoverflow. that was the reason i asked here.

@MasterJames that would be very nice
