### ISSUE TITLE
An option to prevent preventDefault in OrbitControls

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#8084]
The use case is 3D view having 100% width of the page, normally we would not want the dragging in 3D view to scroll the page, but in thin mobile windows there is no much else to be done. Either leave padding, or transparent div-s on top of 3D that block touches, both of these methods suck. If in my app I only need controls to rotate horizontally, I'm fine with vertical drag scrolling the page.

**Comment by makc** [comment]
Ended up doing this hack:

![screen shot 2016-02-07 at 11 15 28](https://cloud.githubusercontent.com/assets/242577/12871819/e664a78a-cd8c-11e5-9271-1850b381cb9e.png)

**Comment by theo-armour** [comment]
Hi @makc 

> The use case is 3D view having 100% width of the page, normally we would not want the dragging in 3D view to scroll the page, but in thin mobile windows there is no much else to be done.

This is a really good point and long term solutions need to be worked out. We want both scrolling and we want rotation on a mobile - all with an intuitive user experience. 

Your hack is a nice start. Thanks.

**Comment by vin-ni** [comment]
any updates on this?

**Comment by Mugen87** [comment]
According to https://github.com/mrdoob/three.js/pull/18612#issuecomment-585607781, always using `preventDefault()` is a good default. Adding an option to disable this behavior or a hack like demonstrated in this issue seems not appropriate and too use case specific. If users require special scrolling logic, it's better to modify a copy of `OrbitControls`.

**Comment by aksperiod** [comment]
+1 this. I have the same use-case where I want to use Orbital Controls on mobile to rotate left and right, while also allowing scroll. Instead I will have to make my own orbital controls now.

**Comment by kzka90** [comment]
+1 this. Has anyone come with a better solution?

**Comment by mrdoob** [comment]
I have. Try this:

```css
canvas {
  touch-action: pan-y;
}
```
