### ISSUE TITLE
OBJMTLLOADER gone!

### ISSUE THREAD

**Issue by DomHey** [mrdoob/three.js#8085]
seems like OBJMTLLoader.js, form http://threejs.org/examples/js/loaders/OBJMTLLoader.js is gone. Would be good if your reupload or provide the source.

**Comment by makc** [comment]
bro, do you even git ) [nothing is gone](https://github.com/mrdoob/three.js/commits/master/examples/js/loaders/OBJMTLLoader.js)

**Comment by mrdoob** [comment]
It sure is!

You should use `OBJLoader` and `MTLLoader` in combination.
Use this example as reference:

http://threejs.org/examples/webgl_loader_obj_mtl.html

**Comment by MasterJames** [comment]
Just wanted to point out rhat the link's model appears only black on mobile Samsung Note 3 but maybe that's a known issue still?

**Comment by mrdoob** [comment]
Oh... The example uses dds textures. Maybe this example should use dds textures...

**Comment by void42** [comment]
Is there a reason this is still in the documentation?

http://threejs.org/docs/index.html#Reference/Loaders/OBJMTLLoader

**Comment by mrdoob** [comment]
@void42 Fixed. Thanks!
