### ISSUE TITLE
Suggestion: Javascript Binary Bundles for faster loading and distribution

### ISSUE THREAD

**Issue by wavesoft** [mrdoob/three.js#8086]
Hello guys, I have been working on something that I wanted to share with you...

Trying to balance loading time, size and reusability of resources, while in the same time getting lost with the dozen different resource loaders, I decided to invest some time in a new bundling format for Javascript. The result is called [Javascript Binary Bundles (JBB)](https://github.com/wavesoft/jbb) and so far [it looks promising on the loading time](http://cdn.rawgit.com/wavesoft/jbb-tests/bf678cfe78a6f037744cee76ff41acde202e500e/jbb_test_timing.html). With my crappy ISP I get the following reading (clean cache):

<img width="658" alt="screen shot 2016-02-07 at 22 34 15" src="https://cloud.githubusercontent.com/assets/883486/12875538/677eea64-cded-11e5-8837-325eb221b88a.png">

It's mainly a data serialisation format for Javascript, for optimally encoding native javascript structures (ex. TypedArrays), and having the ability to embed arbitrary data blobs in the bundle. It also supports cross-referencing, making it possible to isolate common resources in separate bundles.

The idea behind it is simple:
1. At build time, use whichever loader you want in order to load your scene, geometries, textures, images, etc. in memory (in node.js)
2. Use JBB to encode the loaded structures (`THREE.Geometry`, `THREE.Texture`, `THREE.Image` etc). into a binary bundle.
3. At run-time just load the bundle and you are ready to go. All the structures are available for use!

While generic, JBB format requires a particular _Table of Known Objects_, or `profile` for short, in order to optimally encode each individual object. Since THREE.js was my first experiment, I created [jbb-profile-three](https://github.com/wavesoft/jbb-profile-three) that can be used with the compiler.

Be aware that this is still under development, but I thought it might be of interest to all of you! I am looking forward for your positive/negative feedback :smile:

**Comment by MasterJames** [comment]
It's very good as your performance stats show. I thought to say in Meteor we get BSON or it transports behind the scene Binary JSON. (It's actually I think binary EJSON which adds better handling for types like dates.
https://github.com/meteor/js-bson/blob/master/README.md
Maybe this gives the challanged mind some further thoughts on the subject, or not.
I wondered if the synergistic combo is more efficient or if one supersedes the other or which is better or what? Bit of a Blackbox/NDA issue to say or clarify anything more then just that hint, but  your efforts deserve some hopefully useful feedback.
Also noted is the testable wisdom, does packing and unpacking save much if your connection is even faster in the future, as in G5 or whatever you want to call it. Textures for sure, code maybe not so.

**Comment by theo-armour** [comment]
Hi @wavesoft 

Here are my results Chrome latest/Win 10/~25mbs download speeds/cache emptied. I also ran the test om a Google Pixel Chromebook and obtained similar results.

![image](https://cloud.githubusercontent.com/assets/547626/12879224/e2923462-cde4-11e5-8973-dee15642a4e3.png)

I ran the test with the console open and note that several Three.js errors appeared:

```
compact[vrml]: 73.226ms
three.min.js:344 THREE.JSONLoader: "morphColors" no longer supported. Using them as face colors.
three.min.js:331 Loader.createMaterial: Unsupported colorAmbient Array[3](anonymous function) @ three.min.js:331
three.min.js:344 THREE.JSONLoader: "morphColors" no longer supported. Using them as face colors.
three.min.js:331 Loader.createMaterial: Unsupported colorAmbient Array[3](anonymous function) @ three.min.js:331
jbb_test_timing.html:78 source[animated]: 144.895ms
jbb_test_timing.html:88 compact[animated]: 169.987ms
9three.min.js:381 THREE.MeshPhongMaterial: 'diffuse' is not a property of this material.
jbb_test_timing.html:78 source[heavy]: 602.863ms
jbb_test_timing.html:88 compact[heavy]: 543.567ms
6three.min.js:695 THREE.ImageUtils.loadTexture is being deprecated. Use THREE.TextureLoader() instead.
```

Maybe these affected the testing. I did run the test a number of time.

I think that wahat @MasterJames suggested may be relevant: packing and unpacking may not give much of a speed up when you have a fast connection.

**Comment by wavesoft** [comment]
@MasterJames: I had a look on BSON, however the problem there is that it is not aware of object types and it tries to serialize everything, without knowing what's important and what's not. For instance, if you try to encode a `THREE.SphereGeometry` you will end-up with dozens of faces/vertices/indices, while you could just encode the constructor parameters (optimising for size). This was the idea behind the compile `profiles`.. keeping only the important properties on each parameter. 

Also, you raised a very valid point! I didn't include date objects in the protocol! I got a bit carried away trying to optimise `TypedArrays`.

> I wondered if the synergistic combo is more efficient or if one supersedes the other or which is better or what?

That might actually be true, as @theo-armour  reported on fast networks. And that's why I also tried to define a format for the raw resources (`.jbbsrc` used in the tests).  However I still think that just casting a binary blob to a `TypedArray` is faster than parsing it's JSON representation, but with the speed Javascript gets optimised I am not sure for the future :laughing: 

@theo-armour: Thanks for your test numbers! I was actually looking to find the weakest points of this format. Can you check in the `Network` tab of the developer's console and see if just the loading of the `.jbb`/`.jbbp` takes longer? At least for the first 3 tests, I am positive that you can get a measurable benefit from TypedArrays. I bet that on fast networks you can load in parallel many more resources.

Perhaps a good  test is to try and load a bundle of many files rather than just a couple..

**Comment by wavesoft** [comment]
Ah, @theo-armour can you also check if the `.jbb` and `.jbbp` files are served with `Content-Encoding: gzip`? The JBB format is quite sparse and it greatly benefits from GZIP compression. I relied on rawgit doing the gzip compression for me, but they might skip this on fast networks. can you confirm?

**Comment by theo-armour** [comment]
@wavesoft 

I will look into these things this evening ( San Francisco time ) - but please not that I am one of the Thjree.js 'dummies' and not a techie - so I may not understand what this all means. ;-)

**Comment by wavesoft** [comment]
@theo-armour open the Developer Tools, go to `Network` tab, and having the developer tools open, click on _Start Tests_. You will see all the resources being downloaded... click on the `vrml.jbb`, select the `Headers` tab on the right, and look for a `Content-Encoding: gzip` header on the Response Headers. Check if this is missing in your case.

You can also click on `Timing` tab to see were your browser spends more time while downloading.

**Comment by theo-armour** [comment]
for vrml.jbb

```
HTTP/1.1 200 OK
Date: Mon, 08 Feb 2016 23:47:57 GMT
Content-Type: application/octet-stream
Transfer-Encoding: chunked
Connection: keep-alive
X-Content-Type-Options: nosniff
X-Robots-Tag: none
Access-Control-Allow-Origin: *
Cache-Control: max-age=315569000
ETag: W/"7f259ba2c77bf142181e8815455ac53def20fef9"
Vary: Accept-Encoding
RawGit-Cache-Status: HIT
Server: NetDNA-cache/2.2
X-Cache: HIT
Content-Encoding: gzip
```

![image](https://cloud.githubusercontent.com/assets/547626/12903401/3dad54fc-ce7c-11e5-9ccc-88e6de753f48.png)

**Comment by wavesoft** [comment]
Hello guys! I worked a bit further on the jbb format, making sure that it's parsing time is always faster than the loader that I use. Even though I still see some corner cases, I observe an average loading time improvement of about **30%**.

You can run the [benchmarks of the latest version here](https://cdn.rawgit.com/wavesoft/jbb-tests/7d71eb26378860d4059097f3ee6d41fb0940299b/jbb_test_timing.html), and please let me know if you still see bad results. 

I also wrote a quick guide for [how `.jbb` can be used with three.js](https://github.com/wavesoft/jbb/blob/master/doc/Tutorial%201%20-%20THREEjs/Using%20with%20THREEjs.md). Note that I tested it with three.js r73.

If I am correct there have been some API changes since r73 and I need to update the [jbb-profile-three](https://github.com/wavesoft/jbb-profile-three) accordingly in order to make it compatible with the latest release.

**Comment by donmccurdy** [comment]
This looks great, nice work! 🎉 

I'm going to close the issue unless there are any specific ways three.js should accommodate this use case better, but for discussion/benchmarks/updates feel free to start a new thread in the [three.js forums](https://discourse.threejs.org/) as well.
