### ISSUE TITLE
make loaders' load() to return stuff.

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#8091]
For example, if XHRLoader's load() returns XMLHttpRequest, but VRMLLoader's load() does not return it (swallows it), so there is no easy way to call .abort() on underlying XMLHttpRequest, for example.

Same goes for OBJLoader, ColladaLoader(1 and 2), STLLoader, I am bored to check more loader, etc

**Comment by mrdoob** [comment]
Returning the request sounds good to me.

**Comment by makc** [comment]
My original idea stems from, as you guessed it, the need to abort loading. But if the model is multi-part (such as geometry + textures) it might not be enough (or too late) to abort XMLHttpRequest. Maybe there is better way to address this? Maybe via THREE.LoadingManager? It does not manage much now beyond tracking loading progress.

**Comment by 0merta** [comment]
You may find this PR interesting. #9600 
It allows you to abort all active requests using the LoadingManager.
To abort a single request we may store the current request inside every Loader.

**Comment by makc** [comment]
closing in favor of #9600 if it does what it says
> It allows you to abort all active requests using the LoadingManager
