### ISSUE TITLE
SEA3D updated for THREE r74

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#8092]
For those interested I've updated the SEA3D Loader to work with the latest r74 THREE release.
Samples:
http://necromanthus.com/Test/html5/dog_r74.html 
( press 1,2,3 to change the dog animations )
http://necromanthus.com/Test/html5/SMC_r74.html 
( use mouse wheel for zoom in/out )

You can grab the latest minified library from here:
http://necromanthus.com/Test/html5/JS/sea3d.min_74.js 
All the required files are included so no additional downloads are needed.

cheers

**Comment by makc** [comment]
why not PR to [this](https://github.com/mrdoob/three.js/tree/master/examples/js/loaders/sea3d)?

**Comment by mrdoob** [comment]
Doesn't the SEA3DLoader already work?
http://threejs.org/examples/#webgl_loader_sea3d

**Comment by RemusMar** [comment]
> Doesn't the SEA3DLoader already work?
> http://threejs.org/examples/#webgl_loader_sea3d 

Do you provide any minified and 100% backward compatible loader?

**Comment by mrdoob** [comment]
Oh, I see. Sorry, I misunderstood.
