### ISSUE TITLE
Scene.clone() is always recursive

### ISSUE THREAD

**Issue by yar3333** [mrdoob/three.js#8094]
Why `Scene.clone()` is always recursive? Is this correct? I think next code
```js
THREE.Scene.prototype.copy = function ( source ) {

	THREE.Object3D.prototype.copy.call( this, source ); 
```

must be
```js
THREE.Scene.prototype.copy = function ( source, recursive ) {

	THREE.Object3D.prototype.copy.call( this, source, recursive ); 
```

Can I do a PR?

**Comment by mrdoob** [comment]
I think you're right. Do you want to do a PR with the fix?

**Comment by yar3333** [comment]
https://github.com/mrdoob/three.js/pull/8095

**Comment by yar3333** [comment]
PR: https://github.com/mrdoob/three.js/pull/8096
