### ISSUE TITLE
loader.setPath is not a function

### ISSUE THREAD

**Issue by RPBruiser** [mrdoob/three.js#8100]
When I try using MTLLoader in r74, I continue to receive a console error insiting the `loader.setPath` within `MTLLoader.js` is not a function along with an empty scene. I am running Firefox 40.0.3 also Chrome Version 48.0.2564.109 m

**Comment by mrdoob** [comment]
Have you updated `OBJLoader` and `MTLLoader` with the ones in `r74`?

**Comment by RPBruiser** [comment]
I have. I downloaded the master branch which is r74, this is the only release I get this issue with. When using `OBJMTLLoader` which calls `MTLLoader` in r73 (r73 version of `MTLLoader`) I do not receive this error message and all works fine.

**Comment by mrdoob** [comment]
Can you upload your test somewhere? I don't see that error here:
http://threejs.org/examples/webgl_loader_obj_mtl.html

**Comment by RPBruiser** [comment]
`function init() {	
	// container
	container = document.createElement( 'div' );
	document.body.appendChild( container );
	
	// camera
	camera = new THREE.PerspectiveCamera(75,window.innerWidth / window.innerHeight, 1, 1000);
	camera.position.set(0,-25,25);
	
	// controls
	controls = new THREE.OrbitControls(camera);
	
	// scene
	scene = new THREE.Scene();
	scene.fog = new THREE.FogExp2( 0x4C4C33, 0.0095 );
	
	// renderer
	renderer = new THREE.WebGLRenderer();
	renderer.setPixelRatio(window.devicePixelRatio);
	renderer.setSize(window.innerWidth, window.innerHeight);
	renderer.shadowMapType = THREE.PCFSoftShadowMap;
	container.appendChild(renderer.domElement);
	
	// set ambient light
	var ambient = new THREE.AmbientLight(0xF4E0C2);
	scene.add(ambient);
	
	// set a spotlight
	var spotLight = new THREE.SpotLight(0xF4E0C2);
	spotLight.position.set(100,-100,100);
	spotLight.castShadow = true;
	spotLight.shadowMapWidth = 1024;
	spotLight.shadowMapHeight = 1024;
	spotLight.shadowCameraNear = 500;
	spotLight.shadowCameraFar = 4000;
	spotLight.shadowCameraFov = 30;
	camera.add(spotLight);
	scene.add(camera);
	
	// plane for the ground
	var planeGeometry = new THREE.PlaneBufferGeometry(0,0,0);
	var planeMaterial = new THREE.MeshBasicMaterial(0xFFFFFF);
	var plane = new THREE.Mesh(planeGeometry, planeMaterial);
	plane.position.set(0,0,-1);
	scene.add(plane);
	
	// obj file
	var mtlLoader = new THREE.MTLLoader();
	mtlLoader.setBaseUrl( 'objs/Femur/' );
	mtlLoader.setPath( 'objs/Femur/' );
	mtlLoader.load( 'OBJ_Croc_Femur.mtl', function( materials ) {
		
		materials.preload();

		var objLoader = new THREE.OBJLoader();
		objLoader.setMaterials( materials );
		objLoader.setPath( 'objs/Femur/' );
		objLoader.load( 'OBJ_Croc_Femur.obj', function ( object ) {
			object.scale.set(.25,.25,.25);
			scene.add(object);
			targetList.push(object);
			scene.updateMatrixWorld(true);
		}, onProgress, onError );
	});
}`
 I will link to Fidlle shortly

**Comment by mrdoob** [comment]
That jsfiddle doesn't work. Please, provide a working example.

**Comment by RPBruiser** [comment]
[This fiddle](https://jsfiddle.net/qx0f4uL7/5/) shows what I see when attempting to use `OBJLoader` and `MTLLoader`. It just renders a pitch black scene.

**Comment by mrdoob** [comment]
![screen shot 2016-02-11 at 13 20 14](https://cloud.githubusercontent.com/assets/97088/12969327/3d8e8318-d0c2-11e5-826c-a59db8b1f48d.png)

**Comment by RPBruiser** [comment]
![error](https://cloud.githubusercontent.com/assets/6766714/12969405/ff780ffa-d04d-11e5-84b6-431df4305d50.png)

**Comment by RPBruiser** [comment]
![error](https://cloud.githubusercontent.com/assets/6766714/12969414/2a9e389e-d04e-11e5-95ab-f1e6bfc54639.png)

**Comment by mrdoob** [comment]
Your screenshot shows that you're not using `three.min.js` `r74`.

**Comment by humam-nameer-10p** [comment]
Im getting the same error. If I try to use the older version I get fileloader is not a constructor. I believe this is related to version of Three.js I am using but on that part I am dependent on forge-viewer model derivative Three.js version. otherwise forgeviewer doesnt work.

**Comment by mrdoob** [comment]
What version of three.js does forge-viewer use?

**Comment by L3rchal** [comment]
I had same problem with r73 version. Here is awesome example http://jsdo.it/cx20/OQ5X importing object using mtl and obj loaders. Plus, there is example for r73,r76 and r79. Helped me a lot. 
PS for 73 example is using OBJMTLLoader which works.
