### ISSUE TITLE
Three js editor throwing JS Error

### ISSUE THREAD

**Issue by tarun29061990** [mrdoob/three.js#8101]
<img width="1278" alt="screen shot 2016-02-10 at 12 39 01 pm" src="https://cloud.githubusercontent.com/assets/1535607/12940749/537c8f10-cff2-11e5-86e9-e26141931156.png">

**Comment by mrdoob** [comment]
Could you share the obj file?

**Comment by tarun29061990** [comment]
[Poliform-Bolton_Bed_01.al2.js.zip](https://github.com/mrdoob/three.js/files/234141/Poliform-Bolton_Bed_01.al2.js.zip)

**Comment by tarun29061990** [comment]
New Error : cannot read property length of undefined

**Comment by mrdoob** [comment]
With the same model?

**Comment by tarun29061990** [comment]
No this is a different model

**Comment by mrdoob** [comment]
Hmm, the editor doesn't support [Archilogic](https://about.archilogic.com/) files.

**Comment by tarun29061990** [comment]
Can you please tell me whats the difference between normal file and Archilogic file and how are they consuming it?

**Comment by mrdoob** [comment]
It's their own format. If they had a definition of the format somewhere we could try to do a loader, but without that we can't load them.

**Comment by tarun29061990** [comment]
Ok thanks
