### ISSUE TITLE
Group seems not work correctly in editor

### ISSUE THREAD

**Issue by slavielle** [mrdoob/three.js#8104]
I maybe missing something but i can't figure out how to use groups in editor. I've tried to drag a shape into a group in the scene graph but it seems not working this way. Can anyone tell me about this ?

**Comment by bioship** [comment]
the r72 editor had a 'parent' select box in the Object3D sidebar that could be used to change the parent of the currently selected object, but it was removed in subsequent versions for performance reasons.  the relevant code is in Sidebar.Object3D.js

**Comment by mrdoob** [comment]
#7532
