### ISSUE TITLE
OBJMTLLoader.js missing?

### ISSUE THREAD

**Issue by zettix** [mrdoob/three.js#8105]
It looks like the best blender exporter that supports textures.  Anyway I use it.  I have it from here:
mrdoob-three.js-d49bb0e/examples/js/loaders/OBJMTLLoader.js
But it is gone from the current git directory:
https://github.com/mrdoob/three.js/tree/master/examples/js/loaders
And not present anywhere when I did a git clone and searched for it.  It does not appear to be present in three.min.js or anywhere.  I'll try to fix the old version, it gives this error:
Uncaught TypeError: loader.setCrossOrigin is not a function

Also, if it was depreciated, it is still documented here:
http://threejs.org/docs/#Reference/Loaders/OBJMTLLoader

**Comment by doambroa** [comment]
OBJMTLLoader is out since r74, you should use OBJLoader + MTLLoader

**Comment by makc** [comment]
> not present anywhere when I did a git clone and searched for it

[yeah, right, you sure did](https://github.com/mrdoob/three.js/commits/master/examples/js/loaders/OBJMTLLoader.js)

**Comment by zettix** [comment]
Thanks everyone, I'll take a closer look at
http://threejs.org/examples/#webgl_loader_obj_mtl

**Comment by mrdoob** [comment]
#8085

**Comment by DarrenCook** [comment]
+1 This needs more explanation/documentation. 

Might I suggest you add a 2nd example to http://threejs.org/docs/#Reference/Loaders/OBJMTLLoader  to show how you are supposed to change the code, shown there, to use the new classes.  (That same code is being used in published books and online tutorials, so I'm sure there will be lots more people coming along with this same question.)

**Comment by makc** [comment]
May I suggest
```
function OBJMTLLoader () {
    location = 'https://github.com/mrdoob/three.js/issues/8105'; // :)
}
```
