### ISSUE TITLE
Spotlight clone dropping shadow parameter in v74 colladaloader2?

### ISSUE THREAD

**Issue by izatar** [mrdoob/three.js#8106]
I load a .dae scene with the new colladaloader2.  The scene has lights and they do light the scene when renderered.  However, the spotlights aren't marked for shadows.  So in the loader function I figure I will traverse the scene and set castShadow (et al) on the spotlights.  When render comes it gets an error because the spotlight.shadow parameter is undefined.  
So I trace into the colladaloader2, where it creates the spotlights.  The initial object for the spotlight it creates does in fact have a valid .shadow parameter.  However, later in the loader the spotlight is .cloned(), and that is where *i think* the .shadow field gets lost.

The end result is that turning on shadows for a .dae doesnt work like I would expect.

**Comment by izatar** [comment]
Im not sure how stackoverflow is going to fix a bug in colladaloader2/spotlights?

**Comment by mrdoob** [comment]
Sorry, you didn't provide a example showing that this is a bug. So sounds like you need help to figure out if it's a bug or not.

**Comment by izatar** [comment]
[colladaspotlightshadow.zip](https://github.com/mrdoob/three.js/files/126123/colladaspotlightshadow.zip)
Attached is a zip file containing a .DAE file with a spotlight, and some modified examples from the examples.
I think there is a bug happening in line 1297 of ColladaLoader2.js when it makes a clone of a spotlight, the spotlight gets corrupted when the .shadow property becomes undefined.  

More details below.
==============================================
This test is using the colladaloader2 74 dev version on v73.

Put colladaloader2.js over the v73 version in the examples/js/loaders
Place atest_webgl_loader_collada.html in the examples directory.  
Put taurus.dae in examples/models/collada/taurus.dae

put breakpoints at:
line  807 ColladaLoader2.js "light = new THREE.SpotLight();"
line 1297 ColladaLoader2.js "objects.push( getLight( instanceLights[ i ] ).clone() );"
line 62 atest_webgl_loader_collada.html "var test = 1;"

and run.
Notice after tracing over line 807 of ColladaLoader.js, "light" has a valid value for .shadow.

Trace over 1297 until it hits the spotlight.  Then look at the object pushed.  The .shadow value of the clone() SpotLight object is undefined.

Run to line 62 of atest_webgl_loader_collada.html. Examine the child parameter.  Notice it is a spotlight with its .shadow propery undefined. 

Thus, any attempt to turn on shadows for the spotlight will cause a crash in the renderer.

**Comment by WestLangley** [comment]
>This test is using the colladaloader2 74 dev version on v73.

Don't do that.

>I think there is a bug happening

If you are not sure there is a three.js bug, we prefer you use stackoverflow first.

**Comment by izatar** [comment]
I am sure there is a bug. _ I gave you the line number.  _

**Comment by WestLangley** [comment]
As I said, do not use `ColladaLoader2` 74 dev version on v73. Please use three.js r.74.

Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by izatar** [comment]
R 74. Lolwut. When did that happen. haha!  Im on it.

**Comment by izatar** [comment]
Yes! This problem is not happening in R74.

**Comment by mrdoob** [comment]
😑
