### ISSUE TITLE
TrackballControls is much slower than its older version

### ISSUE THREAD

**Issue by MarcoSulla** [mrdoob/three.js#8113]
See http://stackoverflow.com/a/35364842/1763602 . Shortly, it seems that the performance of this old version is much better: https://stemkoski.github.io/Three.js/js/TrackballControls.js

I tested it with Firefox 41.0.2. No benchmarks, the performance degradation is quite evident, since when you start the rotation using the mouse, sometimes the image update lags. It happens also with the old version, but a lot less frequently. Not surprisingly, performance seems quite the same in Chrome 48.0.2564.82.

Furthermore mouse sensitivity is much lower. You have to move it a lot to get an appreciable effect on the image. This happens on both Firefox and Chrome.

Steps to reproduce:
1. Download the source code of https://stemkoski.github.io/Three.js/Graphulus-Function.html
2. open it in Firefox and play with it a little
3. replace TrackballControls.js with its newer version
4. reopen

Three.js version: r74
OS: Linux (Lubuntu 14.04)
Graphic card: Intel HD Graphics 4400 (integrated in cpu Intel i5-4210U)

Fiddle with new code: https://jsfiddle.net/vt8n6dcs/1/
Fiddle with old code: https://jsfiddle.net/vt8n6dcs/

**Comment by WestLangley** [comment]
What exactly are you referring to by "performance". A side-by-side comparison would be helpful.

Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by MarcoSulla** [comment]
I updated the first post.

**Comment by MarcoSulla** [comment]
Added fiddles.

**Comment by Mugen87** [comment]
@MarcoSulla I can't see any error in `THREE.TrackballControls`. Can you try to set the property `rotateSpeed` to a higher value than `1`? Something like this:

```javascript
controls.rotateSpeed = 2;
```
Other properties for speed controlling are `zoomSpeed` and `panSpeed`. I've provide a more clear example for you right [here](https://jsfiddle.net/22q9133v/). Is your problem solved with this approach?

**Comment by MarcoSulla** [comment]
Can' reproduce anymore. Maybe since it moved slower before, redraw was more accurate and lags happened more often.
