### ISSUE TITLE
Handling of "MeshBasicMaterial" and "receiveShadow" property

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#8116]
When upgrading my project to R74, i've discovered the following warning.

_THREE.WebGLProgram: gl.getProgramInfoLog() WARNING: Output of vertex shader 'vDirectionalShadowCoord' not read by fragment shader_

This message occurs if you have a mesh with a `MeshBasicMaterial` and set the `receiveShadow` to `true`. You can check this out with this [example](https://jsfiddle.net/3hyyzd3c/). 

It looks like three.js R74 drops the support of shadows for *BasicMaterials. From my point of view, it's a little bit inconsistent that the `receiveShadow` property is not working with all materials.

I bet you had good reason for this new behavior, but maybe there is a way to prevent the mentioned warning and log a more meaningful, user-friendly message (something like _"MeshBasicMaterial doesn't support shadows"_).

Chrome 48.0.2564.109 (64-bit), Mac OSX 10.10.5

**Comment by WestLangley** [comment]
>From my point of view, it's a little bit inconsistent that the receiveShadow property is not working with all materials.

I'm not so sure about that. `MeshBasicMaterial` does not respond to lights.

For what it is worth, in r.74, `MeshBasicMaterial` will cast shadows, but it will not receive shadows.

**Comment by mrdoob** [comment]
> I bet you had good reason for this new behavior, but maybe there is a way to prevent the mentioned warning and log a more meaningful, user-friendly message (something like "MeshBasicMaterial doesn't support shadows").

Yeah, the reason was that if we kept shadows in `MeshBasicMaterial` people would need `shadowDarkness` in order to modulate the shadow color. As @WestLangley said, `MeshBasicMaterial` doesn't respond to light, so people can't use `AmbientLight` for modulating the shadow color just like they can do with the other materials. So ended up deciding to remove the support and added `ShadowMaterial` (in examples for now) for the uses cases people were using `MeshBasicMaterial` with shadow.

**Comment by mrdoob** [comment]
Having said that, the warning you're getting it's a thing I overlooked, will fix!

**Comment by mrdoob** [comment]
Thanks!

**Comment by Mugen87** [comment]
Thanks for your explanations!

**Comment by bnolan** [comment]
I used shadow maps on basic materials quite a lot. Is the correct way to do it to use the lightMap attribute of a texture to make the material unaffected by lights but still by shadows?

**Comment by bnolan** [comment]
Ok sweet, I used emissiveItensity and sorted it out :)
