### ISSUE TITLE
[Discussion] WebGL2 Support

### ISSUE THREAD

**Issue by mattdesl** [mrdoob/three.js#8125]
Hello! :wave: 

I've been patching ThreeJS to work with WebGL2 over the last couple days. Expect a bunch of PRs in the next couple weeks.

I've started with the easy ones:
- [3D textures](https://github.com/mrdoob/three.js/pull/8124)
- [Multisample renderbuffers](https://github.com/mrdoob/three.js/pull/8120)
- [Fixing WebGL2 context warnings in Chrome](https://github.com/mrdoob/three.js/pull/8121)

WebGL2 is pretty backwards-compatible, so most things should work, but extensions presents a big problem. To fix this, I'm monkey-patching some `gl` methods to make it more backward-compatible, and passing that context to the WebGLRenderer. Ideally, we could come up with a solve so users don't need to do this.

In WebGL2, a lot of extensions have been promoted to core (see [here](https://github.com/Jam3/webgl2-core-extensions) for a list). When you call `gl.getExtension` on one of these, it will return null, meaning a lot of ThreeJS code will break or not work as expected.

Another problem is with extensions in v100 GLSL shaders, like standard derivatives. In a WebGL2 context, you can only get standard derivatives by re-writing the shader in 300es syntax. Fixing this correctly would involve a lot of overhead for ThreeJS, and also a second code path for fallback shaders (WebGL1).

Next week I will put up a repo with a basic WebGL2 test-bed, monkey-patching the `gl` context to fix the extension problems. Until then, you can check out these for details:
- [gl-extension](https://github.com/Jam3/gl-extension) - a backwards-compatible `getExtension` method
- [glsl-100-to-300](https://github.com/Jam3/glsl-100-to-300) - transpiles v100 to v300es GLSL on the fly to support extensions like standard derivatives in WebGL2

**Comment by mattdesl** [comment]
Ok, the internal format thing is a part of spec.

https://www.khronos.org/opengles/sdk/docs/man3/html/glTexImage2D.xhtml

If the type is `gl.FLOAT`, we need to specify a sized *internalFormat*. 

It may also affect `gl.texImage2D` when WebGL2 is fully implemented by browser vendors

**Comment by mrdoob** [comment]
Great stuff Matt!

**Comment by backspaces** [comment]
Just noticed webgl2 is alive and well in chrome & canary w/ flags.

Is there a discussion on changes in GLSL? A comparison of some sort? I've heard its not backwards compatible with webgl1.

**Comment by GuillaumeLeclerc** [comment]
Is webgl2 supported now ?

**Comment by mrdoob** [comment]
#9965

**Comment by Mugen87** [comment]
Let's continue the discussion in #9965
