### ISSUE TITLE
webgl_shadowmap_performance.html halves FPS r74 vs r73

### ISSUE THREAD

**Issue by izatar** [mrdoob/three.js#8127]
When I run the r73 webgl_shadowmap_performance.html test fullscreen, I get 25-30 fps on chrome and 20-22 fps on firefox.
But with r74 I'm seeing 8-10 Fps on chrome and 6-8 on firefox.  Card is nvidia 770m. *Windows

This is a significant performance regression that I first noticed in my own scripts.

**Comment by RemusMar** [comment]
I don't know about r73 because I didn't like it and never use it.
But here is a better benchmark:
r71: http://necromanthus.com/Test/html5/testA.html 
r74: http://necromanthus.com/Test/html5/testA_r74.html 
Press "F" for full screen.
I didn't notice any performances drop on various hardware configs.
cheers

**Comment by izatar** [comment]
Why do you say that is a better benchmark? There are only a couple shadows in there, the shadowmap performance test has many more.  I wonder how r71 compares to r74 on the actual benchmark?

**Comment by RemusMar** [comment]
> Why do you say that is a better benchmark? 

For many reasons.
A few of them:
1) it's a GLOBAL benchmark, so most of the three.js features get into count
2) it's a higher poly benchmark (with a 2048x2048 shadow map)
3) it used dynamic lighting
I hope you got the main picture.
cheers

**Comment by theo-armour** [comment]
@RemusMar 

>> r74: http://necromanthus.com/Test/html5/testA_r74.html 

Looks like a nice test. I also did not see much of a change between the two tests.

@izatar 

I tried webgl_shadowmap_performance.html  on both R74 and r73. The performance drop in r74 I see is very similar to yours.

BTW, it looks like Mr.doob is working on shadows a lot these days: [GitHub search src/lightd](https://github.com/search?utf8=%E2%9C%93&q=user%3Amrdoob%26repo%3Athree.js+user%3Amrdoob+repo%3Athree.js+user%3Amrdoob+repo%3Athree.js+path%3Asrc%2Flights&type=Code&ref=advsearch&l=&l=)

So you can probably expect more changes.

**Comment by mrdoob** [comment]
https://rawgit.com/mrdoob/three.js/r73/examples/webgl_shadowmap_performance.html 22fps
https://rawgit.com/mrdoob/three.js/r74/examples/webgl_shadowmap_performance.html 26fps

**Comment by mrdoob** [comment]
> I don't know about r73 because I didn't like it and never use it.

I'm glad that you like r74! 😊

**Comment by theo-armour** [comment]
Google Pixel Chromebook Core i7 & Intell 5500 GPU

* R73 ( and all previous releases) - shadows totally broken/not visible/cause error messages
* R74 ~ shadows work with 7-10 fps. Yay!

 Win 10 Core i7 Nvidia GT 750 M
* R73 21-22 fps
* R74 16-18 fps

Android Pixel C tablet
* R73 6-8 fps
* R74 9-10 fps

**Comment by WestLangley** [comment]
AMD Radeon HD 6750M OSX 10.11.3 - Safari 9.0.3
webgl_shadowmap_performance.html
R73 30 fps
R74 22 fps

AMD Radeon HD 6750M OSX 10.11.3 - Chrome 48.0.2564
webgl_shadowmap_performance.html
R73 19 fps
R74 23 fps

**Comment by mrdoob** [comment]
Interesting... Something to note is that the performance example has other things going on (animation system changes, morphtargets, etc).

So we should do a simpler test. Probably just a ton of cubes and 2 or 3 lights would be a better performance test.

**Comment by mrdoob** [comment]
R73 http://jsfiddle.net/ovfuco55/
R74 http://jsfiddle.net/jb5cq1mL/

MacBook Air, 1.6 GHz Intel Core i5, Intel HD Graphics 6000

* R73 17fps
* R74 21fps

**Comment by theo-armour** [comment]
Here is a very shadowy test:

[webgl_shadow_transit.html](http://jaanga.github.io/demo/three.js/webgl_shadow_transit/webgl_shadow_transit.html)

If you zoom way out you can see what is happening:

* The point light is moving about the the sphere of objects
* The directional light is moving about outside the sphere

The interesting thing is that even if you drop the number of objects down to near zero, the fps is still well below 60. The just the lights and the big sphere seems to be enough to slow things down.

Next revision to will always make the same collection of objects in order to ensue the number of vertices/faces is constant for each run.

**Comment by RemusMar** [comment]
> Interesting... Something to note is that the performance example has other things going on (animation system changes, morphtargets, etc). 

As I said befoe, this "webgl_shadowmap_performance.html" is not very relevant.
A bunch of animated low poly models is something suitable for a CPU test ... 
For a "shadowmap_performance" test you need a few high-poly models and a 2048x2048 or a 4096x4096 shadowMap.
In any case, http://necromanthus.com/Test/html5/testA_r74.html proves that there is NO performance drop in r74.

**Comment by izatar** [comment]
On Theo's webgl_shadow_transit.html test my nvidia770m with i7 is getting 14 fps full screen 1920x1080.  My sister is getting 20fps on a radeon 5800 and i5 at fps 1920x1080.  Normally her fps is lower than mine since her machine is quite old.
One other note that might be relevant: my chrome is 64-bit.  But my firefox isnt and it is also slower.

**Comment by theo-armour** [comment]
[webgl_shadow_transit_r74.html](jaanga.github.io/demo/three.js/webgl_shadow_transit/webgl_shadow_transit_r74.html)
[webgl_shadow_transit_r73.html](jaanga.github.io/demo/three.js/webgl_shadow_transit/webgl_shadow_transit_r73.html)

The fps varies a lot while running while the scripts are running - this is an indication that the scripts by more than just shadows. For example if there is a large area with few objects, the fps jumps 

Win10/Chrome48
* R74 26-28 fps
* R73 27-30 fps

On Mr.doob's jsFiddle scripts:

* R73 15/16 fps
* R74 16 fps

So I'm not seeing a big diff - but the fact that shadows are working in R74 on an Intel GPU is a huge boost.

**Comment by mrdoob** [comment]
webgl_shadow_transit

MacBook Air, 1.6 GHz Intel Core i5, Intel HD Graphics 6000, Chrome 48.0.2564.109

* R73 10 fps
* R74 25 fps

**Comment by Fabrice3D** [comment]
NVIDIA GeForce GT 750M 2048 MB - MPB 2,6 GHz Intel Core i7
chrome 48.0.2564.109 (64-bit)
safari 9.0.3 (11601.4.4)

webgl_shadow_transit_r73.html -->  1-5 fps safari (viewed at >1024) - 12fps <1024
chrome 11 fps <1024

webgl_shadow_transit_r74.html-->  30-44 fps safari (viewed at >1024) - 30-50 (viewed at <1024) 
chrome 50-55 fps > 1024,  60fps <1024

**Comment by izatar** [comment]
I have discovered that removing the line:
`renderer.shadowMap.type = THREE.PCFSoftShadowMap;`
addresses the problem ,and my framerate shoots up to 55-60.

I took a look at the logs, and I see that the SoftShadowMap was recently re-written to simplify the code. Is it reasonable to assume this simplification is the culprit?

**Comment by mrdoob** [comment]
Yes, that makes sense. `PCFSoftShadowMap` has more quality now.
Glad that we figured it out!
