### ISSUE TITLE
Making node.js module loading more straightforward

### ISSUE THREAD

**Issue by Gray1989** [mrdoob/three.js#8130]
In node, when a module is loaded, it is run in a separate context than the module that loaded it. For this reason loading three into node becomes additionally complicated. I was thinking of making a completely separate module using the following code to simplify installation and usage on node js. However I think it will probably be of more use to actually post the code I have for it here instead.

``` javascript
var vm = require('vm'), fs = require('fs'), Canvas = require('canvas');

var context = new vm.createContext(module.exports = {
    document: {
        createElement: function(type) {
            var ret;
            switch(type) {
                case 'canvas':
                    ret = new Canvas();
                    break;
                default:
                    ret = {};
                    break;
                };
            ret.style = {};
            return ret;
            }
        },
    console: {
        log: function() { void(0); },
        error: function() { void(0); }
        },
    load: function(path) {
        return new vm.Script(fs.readFileSync(
            __dirname
        +   '/node_modules/three'
        +   (path[0] === '/' ? path : '/' + path )
            )).runInContext(context);
        },
    Canvas: Canvas
    });

module.exports.load('three.min.js');
module.exports.load('examples/js/renderers/CanvasRenderer.js');
module.exports.load('examples/js/renderers/Projector.js');
```

To use this script, run the NPM installation commands for the dependencies, both three and canvas (canvas has additional installation dependency instructions, so do that first). Once the dependencies are in the node_modules folder, and assuming you saved the above script as loader.js, use the following JS code:

``` javascript
var THREE_Loader = require('./loader.js');
var THREE = THREE_Loader.THREE;
```

At this point additional script files may be loaded into the three module's context using the `THREE_Loader.load` command. I hope this helps somebody out. I think it would be even better if it inspired an addition to the official project though. :)

**Comment by bhouston** [comment]
You are correct that all modules in npm are loaded into separate contexts.  This is problematic when you want to include additional example files into the same namespace.  I think this could be helped by expanding the THREE interface on node in this fashion:

```
var THREE = require('three');
var CanvasRenderer = THREE.require( './examples/js/renders/CanvasRenderer' );
```

What do you think?

**Comment by Gray1989** [comment]
If you're asking me what I think, I think that's a great idea. I'm not sure how to get ahold of the context object used to run scripts in a module's namespace and I really don't like using eval so this is what I've come up with, if it helps at all...

`````javascript
exports = module.exports = (function(vm, fs){
	var sandbox = { THREE: THREE, console: console };
	var context = new vm.createContext(sandbox);
	THREE.require = function(path, isFromTHREEModuleDirectory) {
		if(isFromTHREEModuleDirectory)
			path = __dirname + ( path[0] === '/' ? path : '/' + path );
		new vm.Script(
			fs.readFileSync(path)
			).runInContext(context);
		return sandbox;
		};
	return THREE;
	}(require('vm'), require('fs')));
`````

**Comment by bhouston** [comment]
Sweet stuff @Gray1989 Why not submit this as a PR (I would just add your code to the footer.js code if possible) and expand the utils/npm/test.js script to test that it works?  I think this is great.

**Comment by bhouston** [comment]
I would just add your code here:

https://github.com/mrdoob/three.js/blob/master/utils/npm/footer.js

And the test script (which really should not reference three-math as it is obsolete) I am referring to is here:

https://github.com/mrdoob/three.js/blob/master/utils/npm/test.js

**Comment by MasterJames** [comment]
To the point about eval being evil. 
You can alternativly wrap code in a function and use 
new Function (codeString) and then use apply() or call() with a context.
I think your wrapped code can connect itself to a global THREE internally as well. (Depending on your requirements.)
So maybe this helps you or someone else with simpler needs. I'm still wrapping my head around your no doubt better solution.

**Comment by Mugen87** [comment]
@donmccurdy I don't think this issue is still relevant. The project advices to load examples files in CommonJS style like so:
```js
var THREE = window.THREE = require('three');
require('three/examples/js/loaders/GLTFLoader');
```
For the unit tests, the project uses rollup for a while now.

**Comment by donmccurdy** [comment]
Proper CommonJS style would be:

```js
var THREE = require('three');
var GLTFLoader = require('three/examples/js/loaders/GLTFLoader');
```

Our requirement of patching global scope is not really straightforward... but, I don't think we're really likely to change the `examples/js` folder wholesale at this point, since we're planning to support only `examples/jsm` going forward. NodeJS users should begin using ES modules at this point, so this issue can be closed.
