### ISSUE TITLE
r74 (bis) lighting issue

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#8132]
In the first r74 the lighting was ok.
In the today update the lighting is wrong.
Now all the objects using PHONG materials look like they have "specular.color" set to max value.
But they don't ...

**Comment by mrdoob** [comment]
That's strange, I don't see that here. Could you provide a jsfiddle?

**Comment by RemusMar** [comment]
> That's strange, I don't see that here. Could you provide a jsfiddle/screenshot? 

With dynamic lighting the difference is huge:
r71: http://necromanthus.com/Test/html5/testA.html 
r74: http://necromanthus.com/Test/html5/testA_r74.html 
r74-bis: http://necromanthus.com/Test/html5/testA_r74bis.html 
Tested on DX9 and DX11, Firefox and Chrome on various hardware config.
In r71 and r74 the lighting is ok.
In r74-bis the lighting is wrong.

**Comment by mrdoob** [comment]
Ah, ok. You scared me...

Yeah, r74-bis also has a change in `SpotLight`. `SpotLight`'s `exponent` is gone, and we now have `penumbra`. You should be able to achieve similar results by setting `spotLight.penumbra` to `0.5`.

Unfortunately we can't make it backwards compatible. However, `penumbra` produces much nicer results than `exponent` was able to!

https://twitter.com/mrdoob/status/696546975185895424

**Comment by RemusMar** [comment]
> Yeah, r74-bis also has a change in SpotLight. SpotLight's exponent is gone, and we now have penumbra. You should be able to achieve similar results by setting spotLight.penumbra to 0.5 

spotLight.penumbra = 0.5; does not make any difference.
The same wrong lighting in 74-bis.

**Comment by RemusMar** [comment]
I get "some" results with spotLight.penumbra = 1.5; 
But the lighting was WAY BETTER in the first r74.

**Comment by mrdoob** [comment]
The problem is that, before, `exponent` was `10` by default, which means that the light was never as bright as a `DirectionalLight` or `PointLight`. That's probably why you had to set the `intensity` to `1.5`. 

Try setting `intensity` to `1.0` and `penumbra` to `0.7`.

**Comment by RemusMar** [comment]
> The problem is that, before, exponent was 10 by default, which means that SpotLight was never as bright as a DirectionalLight or PointLight. That's probably why you had to set intensity to 1.5. 

With intensity set to 1.5 you can "boost" the specular/normal maps.


> Try setting intensity to 1.0 and penumbra to 0.7.

Some improvement, but still wrong.
http://necromanthus.com/Test/html5/testA_r74bis.html 
Please take a look at the "lighting line" at the middle of the walls.
You won't see that in the previous releases:
http://necromanthus.com/Test/html5/testA_r74.html 
As I said before, this "penumbra" is not properly implemented (issue with the smoothing groups).

**Comment by RemusMar** [comment]
With r74-bis I get acceptable results with these settings: 

		var spotLight = new THREE.SpotLight( 0xffffcc, 1.5 );
		spotLight.angle = (50/180 * Math.PI);
		spotLight.penumbra = 0.7; 
So I keep the same 1.5 for intensity, but 50 for angle (instead of 60)

**Comment by RemusMar** [comment]
Ricardo,

You should set 0.66 the default value for penumbra.
It provides the best backward compatibility.
In any case, the default zero value is wrong for sure.

cheers

**Comment by mrdoob** [comment]
Ah yes! I forgot that, because of the new penumbra, angle can now be reduced (thus computing *many* less pixels, thus being much faster).
