### ISSUE TITLE
Cube (Voxel project)

### ISSUE THREAD

**Issue by mireniers** [mrdoob/three.js#8133]
I'm trying to change the voxel (from voxel painter) from a 50x50x50 size to a 100x50x50 rectangular parallelepiped. 
Unfortunately when the brush intersects another bloc, it overlaps it instead of being blocked or piling up. 

<img width="1280" alt="capture d ecran 2016-02-13 a 19 40 03" src="https://cloud.githubusercontent.com/assets/4532676/13029353/6e561d16-d28a-11e5-8d74-e2d1303d5052.png">
<img width="535" alt="capture d ecran 2016-02-13 a 19 45 32" src="https://cloud.githubusercontent.com/assets/4532676/13029355/6e7aea88-d28a-11e5-8e30-5f052162af65.png">
<img width="251" alt="capture d ecran 2016-02-13 a 19 45 40" src="https://cloud.githubusercontent.com/assets/4532676/13029354/6e77bf34-d28a-11e5-9500-cd9dc23648e5.png">

One brush block is blocked on the right side but on the left side it is free to intermingle with the existing block. 

Any clue how I should deal with this matter?

Thank you for your advice,

Milan

**Comment by WENKz** [comment]
Hi,
Have you found the solution?

**Comment by mireniers** [comment]
No sorry. I dropped the project though.
So thanks anyway.

Kind regards,

Milan Reniers

On 22 Nov 2016 10:55 p.m., "Quentin Grisard" <notifications@github.com>
wrote:

Hi,
Have you found the solution?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrdoob/three.js/issues/8133#issuecomment-262233442>,
or mute
the thread
