### ISSUE TITLE
Buffergeometry with morphAttributes doesnt get animated shadows

### ISSUE THREAD

**Issue by izatar** [mrdoob/three.js#8137]
I have a geometry with morphTargets that I converted to a buffergeometry using .fromGeometry.  This reduces them memory overhead of the animated model by _a very large amount._

It appears that the .morphTargets information has been moved to the .morphAttributes field, and the .morphTargets field has been removed. **note: I have seen no documentation on this at all!**
So I modified the MorphBlendMesh code that makes animations to use the .morphAttributes instead of .morphTargets, and it works great!  

_Except for one little hitch._  The **WebGLShadowMap.js** doesn't know about .morphAttributes, it only knows about  .morphTargets, and on **line 324** it uses the length of .morphTargets to decide whether or not to set the _MorphingFlag which makes the shadows animated.

My workaround is to add a fake 1 entry .morphTargets fieldto my BufferGeometry so this test passes and the _MorphingFlag gets set, and then the shadows get animated.

I think WebGLShadowMap.js could check for the existence of the .morphAttributes as well, and set the _MorphingFlag, because the work-around is pretty silly. On the other hand, I am in over my head here and I'm sure someone will will come chop it off shortly.

**Comment by mrdoob** [comment]
> It appears that the .morphTargets information has been moved to the .morphAttributes field, and the .morphTargets field has been removed. **note: I have seen no documentation on this at all!**

BufferGeometry never had a `.morphTargets` so there is no change to document.

> _Except for one little hitch._  The **WebGLShadowMap.js** doesn't know about .morphAttributes, it only knows about  .morphTargets, and on **line 324** it uses the length of .morphTargets to decide whether or not to set the _MorphingFlag which makes the shadows animated.

Good catch! I guess we don't have any example/test that covers that.

**Comment by mrdoob** [comment]
@tschw do you have time to take a look at this?

**Comment by izatar** [comment]
> BufferGeometry never had a .morphTargets so there is no change to document.

Indeed. No _change _to document.  What I meant was the information in .morphTargets in the Geometry are translated to the .morphAttributes in the BufferGeometry when .fromGeometry is used.
But .morphAttributes is not document under BufferGeometry,..or is it?

**Comment by mrdoob** [comment]
> But .morphAttributes is not documented under BufferGeometry,..or is it?

That is correct.

**Comment by tschw** [comment]
> @tschw do you have time to take a look at this? while trying to get this to work (adding new THREE.BufferGeometry().fromGeometry() in webgl_shadowmap) I'm getting errors in the animation system.

I did not change any of the animation code that builds the property paths and don't know around with those all too well. @bhouston is probably the better candidate. However, I would read into it when he's currently not around.

In either case, I guess it'd be good to see the code / errors. Right now I wouldn't know what to look for and where.

**Comment by Astrak** [comment]
Seems the solution is to check also `bufferGeometry.morphAttributes.position` in addition to `geometry.morphTargets` in `getDepthMaterial()` : 

`var useMorphing = ( ( geometry.morphTargets !== undefined && geometry.morphTargets.length > 0 ) || ( geometry.morphAttributes.position !== undefined && geometry.morphAttributes.position.length > 0 ) ) && material.morphTargets;`

This solved it for me. I don't dare pulling that to the dev branch, I need to learn Git usage a bit more :)
