### ISSUE TITLE
render targets small resolution on postprocessing

### ISSUE THREAD

**Issue by aurelmm** [mrdoob/three.js#8139]
Hello guys. First of all this is my first day trying out programming( I am a tech and shader artist).
I am having an issue using any postprocessing as the resolution of the rendertaget seem way off compared to rendering directly. Even the samples seem to have this issue and I am unable to figure it out.
Is there a way to set the resolution of the rendertargets or maybe filtering to set it to nearest neighbor ? On a mobile phone it seems maybe 4 times lower than the device native resolution. Like I mentioned the examples also suffer from the same issue. If I were to guess from previous issues in other circumstances it has something to do with the device DPI or windows scaling in my case (I have a 4k TV as a monitor and have to set it to 150% );

I am using the simple method described in the examples
`
composer = new THREE.EffectComposer( renderer );
				composer.addPass( new THREE.RenderPass( scene, camera ) );

				

				var effect = new THREE.ShaderPass( FernwehPostEffect );
				effect.uniforms[ 'amount' ].value = 0.0015;
				effect.uniforms[ 'tMask'].value= TextureMask ;
				effect.renderToScreen = true;
				composer.addPass( effect );`

Thank you

**Comment by aurelmm** [comment]
Here is the issue on a galaxy s5 for example but on my pc is exactly the same. Like I said, all non postprocessing samples work pixel perfect.

![screenshot](https://cloud.githubusercontent.com/assets/6399406/13034060/914f403c-d333-11e5-88a7-172c3dce0451.jpg)

**Comment by Mugen87** [comment]
You can set the resolution of the effect composer manually with the `setSize` method. But be aware, that the method does not automatically consider the `devicePixelRatio`. If you want a 1:1 resolution on your device, you can set the size like this:

```javascript
composer.setSize( 
	window.innerWidth * renderer.getPixelRatio(),
	window.innerHeigth * renderer.getPixelRatio()
);
```

Also keep in mind that post-procssing can't use the built-in anti-aliasing provided by WebGL. If you want smooth edges, your can try an additional `ShaderPass` with an anti-aliasing shader (see [FXAA](https://github.com/mrdoob/three.js/blob/master/examples/js/shaders/FXAAShader.js) or [SMAA](https://github.com/mrdoob/three.js/blob/master/examples/js/shaders/SMAAShader.js)).

@mrdoob Is there a reason, why the `devicePixelRatio` is not regarded by the `EffectComposer`?

**Comment by aurelmm** [comment]
Thank you very much, it works like a charm and everything is crisp as butter at only half the FPS :)
I'm guessing those HDPI things are a bit of a headache.

As a side note, setting this made some lens flares in the scene (very similar to the ones in the example) a lot smaller. It's not an issue really but maybe you ind it interesting.

**Comment by Mugen87** [comment]
It would be great if you can provide a screenshot of the mentioned smaller rays. Besides, please close the issue if your original problem was solved...

**Comment by aurelmm** [comment]
It's not godrays, it's lensflares.
Here is an after/before the HDPI fix.
Once again thanks
![screen2](https://cloud.githubusercontent.com/assets/6399406/13034903/ba636450-d34a-11e5-9cfb-6f67c4c1bb1d.jpg)

**Comment by Mugen87** [comment]
Thanks for the screenshot. Um, it's hard to perceive a difference. At least in my eyes :wink:

**Comment by aurelmm** [comment]
There is a subtle set of 2 color stains in the left bottom and also around the sun there is a lens flare that contains "lens dirt".
I just noticed now that probably the visual size of a lens flare is based on render window size so it relates to a core function of the system.
