### ISSUE TITLE
Chromatic Aberration effect pass to compensate for Variable Dispersion in VR lenses?

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8144]
I was trying out some Three.JS VR using my Nexus 5 with Google Cardboard.  One thing that I noticed was colored fringes on the far left and far right sides.  This is because of the lenses refractive index varies on a wavelength basis -- it has a low Abbe number / has high variable dispersion:

https://en.wikipedia.org/wiki/Abbe_number

The solution everyone uses to this problem is to introduce a Chromatic Abberration effect that pre-separates the colors on the fringes of the VR effect to compensate for the dispersion of the Google Cardboard lenses.

So this means we need a Chromatic Abberration effect that has some parameters that determine the degree of dispersion as well as its pattern.  I guess it is different for different devices?  Google Cardboard would have a different pattern of Oculus VR?

I'd like to figure out the fully correct solution for this if possible.  Sketchfab has a Chromatic Aberration shader that they can enable, ThreeJS should probably be competitive with that.

Links:

https://developer.oculus.com/documentation/pcsdk/latest/concepts/dg-chromatic-aberration/
https://forums.oculus.com/viewtopic.php?t=32
https://github.com/googlesamples/cardboard-unity/issues/65

**Comment by mrdoob** [comment]
We actually just moved out of the fragment shader distortion approach to just a mesh distortion approach because it was too slow on mobile devices.
https://github.com/borismus/webvr-boilerplate/issues/73

**Comment by mrdoob** [comment]
This is now being handled by the browser itself.
