### ISSUE TITLE
Is sharing webgl context not supported?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#8147]
[Here](https://jsfiddle.net/psgvteg0/) is a demo of pixi spinning bunny + creating three.js renderer. If you uncomment a single line of three.js code, the bunny dies.

**Comment by makc** [comment]
Additionally, [passing 3js context to pixi instead](https://jsfiddle.net/psgvteg0/1/) leaves it in good shape, as it seems, so the problem must be on 3js side?

**Comment by makc** [comment]
The problem seems to be in WebGLRenderer's setDefaultGLState() that I can't opt out of... If I [disable WebGLState init](https://jsfiddle.net/psgvteg0/2/), the bunny lives.

**Comment by makc** [comment]
Ok, so it looks like [the best workaround](https://jsfiddle.net/psgvteg0/3/) is to manually set proper context state before each lib's render call. However, this is not all there is to the story, I will be spamming this issue with uniform location errors soon, stay tuned :wink:

**Comment by makc** [comment]
Here goes:

https://jsfiddle.net/psgvteg0/5/

As you see, pixi's bunny rotation actually mangles 3D cube, and you have a bunch of errors in the console:
![screen shot 2016-02-16 at 0 11 22](https://cloud.githubusercontent.com/assets/242577/13062838/e5e11242-d441-11e5-97a8-7b6a0987c235.png)

**Comment by makc** [comment]
Ok, after rtfm-ing in #5278 I have used this advice:
> Calling renderer.resetGLState() before - or after - your custom rendering function should be sufficient to reset the state predictably

https://jsfiddle.net/psgvteg0/6/

there is now only one invalid location: WebGL: INVALID_OPERATION: uniformMatrix3fv: location is not from current program

**Comment by makc** [comment]
Oh wait, this one is in pixi, I guess three.js is cleared.

**Comment by mrdoob** [comment]
✌

**Comment by makc** [comment]
Yeah 🎉Leaving [working combo link](https://jsfiddle.net/psgvteg0/10/) in case someone will end up reading here.
