### ISSUE TITLE
Proposal: Format Pass interface: init( renderTarget ), setSize( width, height ), dispose()

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8148]
I would like to be able to call on Pass the following functions - which may do nothing if an individual Pass doesn't want to implement them to manage its own resources:
- init( renderTarget ) - allocates internal buffers possibly based on the format and size of the given renderTarget.
- setSize( width, height ) - resize the internal buffers if there are any, and then need resizing.
- dispose() - deallocate internal buffers.

EffectCompositor could be modified such as it automatically calls "init" on passes as they are added/inserted.  It could call "setSize" on passes when one calls "EffectCompositor.setSize" - thus it passes along the resize event to its owned passes.  And "EffectCompositor.dispose()" could also pass along the "dispose" even to its owned passes.

EffectCompositor currently has a "reset" event.  This could be passed to its owned passes as a "Pass.dispose()" and then a "Pass.init()".

This would allow for a lot easier self-management of Passes within an EffectCompositor and I think it is a clear design.

**Comment by Mugen87** [comment]
@bhouston I think it would be good to define a base class `Pass` that all concrete passes needs to implement. Properties like `enabled`, `needsSwap` or `renderToScreen` could be defined in this entity and of course your mentioned methods. This approach would be more robust and clear than the current implementation.

**Comment by mrdoob** [comment]
> @bhouston I think it would be good to define a base class Pass that all concrete passes needs to implement.

+1

**Comment by Mugen87** [comment]
An exemplary implementation of `THREE.Pass`.

@bhouston I'm not understanding the `renderTarget` parameter (init) in your comment. Isn't `writeBuffer` already the render target of a pass?

```javascript
THREE.Pass = function () {

  // if set to true, the pass is processed by its composer
  this.enabled = true;

  // if set to true, the pass indicates to swap read and write buffer after rendering
  this.needsSwap = true;

  // if set to true, the pass clears its buffer before rendering
  this.clear = false;

  // if set to true, the pass outputs its result to screen
  this.renderToScreen = false;

  // a reference to the renderer
  this._renderer = null;

  // a reference to the writeBuffer( the actual render target )
  this._writeBuffer = null;

  // a reference to the readBuffer( the source buffer )
  this._readBuffer = null;

};

THREE.Pass.prototype = {

  constructor: THREE.Pass,

  init: function( renderer, writeBuffer, readBuffer ) {

    this._renderer = renderer;
    this._writeBuffer = writeBuffer;
    this._readBuffer = readBuffer;

  },

  render: function ( delta, maskActive ) {

  },

  setSize: function ( width, height ) {

  },

  dispose: function () {

  }

};
```

**Comment by bhouston** [comment]
> @bhouston I'm not understanding the renderTarget parameter (init method) in your comment. Isn't writeBuffer already the render target of a pass?

The EffectComposer has to often resize or recreate its buffers (RGBA versus RGB, versus float versus half) in order stay in sync with WebGLRenderer's render target.  I figured instead of passing in the parameters I could just pass in the render target it should stay in sync with.  Not sure the best design though.

**Comment by bhouston** [comment]
BTW the write buffer and read buffer "ping pong" (e.g. swap) thus they are not constant and thus should not be saved in init().

**Comment by Mugen87** [comment]
> BTW the write buffer and read buffer "ping pong" (e.g. swap) thus they are not constant and thus should not be saved in init().

Yeah, that make sense! 

> I figured instead of passing in the parameters I could just pass in the render target it should stay in sync with.

But don't we need to pass two render targets (write AND read buffer)? Most passes need one buffer as a data source and a second buffer as a render target...

**Comment by bhouston** [comment]
> But don't we need to pass two render targets (write AND read buffer)? Most passes need one buffer as a data source and a second buffer as a render target...

It is the final render target of the renderer, or what the output is intended to be.  But really it should be the same size and format of both read and write buffers.

**Comment by Mugen87** [comment]
Merging into #12115.
