### ISSUE TITLE
SVGRenderer "_projector.projectScene" is not a function

### ISSUE THREAD

**Issue by andrewvarga** [mrdoob/three.js#8156]
the latest SVGRenderer is not compatible any more with the latest three.js, I think this is due to the refactoring around projectors.

**Comment by andrewvarga** [comment]
Actually, maybe it was something as simple as adding the Projector.js file separately.

**Comment by mrdoob** [comment]
Yes, `SVGRenderer.js` still depends on `Projector.js`.
