### ISSUE TITLE
OrbitControls stops to work when mouse moves out the renderer

### ISSUE THREAD

**Issue by MarcoSulla** [mrdoob/three.js#8157]
With TrackballControls, even if you move the mouse out of the 3d scene, camera continues to be updated. With OrbitControls, if do that, camera stops to be controlled. Furthermore if you return to the render area, camera will not restart to be controlled (you have to release mouse and click again). Is this intended?

**Comment by izatar** [comment]
You can use THREE.PointerLockControls to lock the mouse in the center of the screen so this doesn't happen.  Unfortunately you will get a message from the browser about this, and it cannot be overridden. This is a security feature of the browser so malicious web sites cant lock you out of the browser.

**Comment by MasterJames** [comment]
I would have thought if you addEventListener to document for mousemove events you would still get tracking outside of the browser?  Can it be added or overridden to see?

**Comment by izatar** [comment]
The problem isn't just that the mouse goes outside the browser, its that when the mouse hits the edge of the desktop/screen, it stops moving.  Using the PointerLockControls fixes this problem.  If there is another way to  fix this problem I am unaware of it.

**Comment by arodic** [comment]
No, you can track mousemove outside of the window. The listeners need to be attached to window object. You also need to listen to mouseup on window to make everything work properly. This however does not work from inside an iframe. Locking controls is not what you need for orbit controls.

It would be nice if all of the redundant logic was expressed in a shared Controls.js class in such way that all controls don't have to reimplement this stuff. Handling touch also adds a lot of complexity (especially multitouch).

**Comment by MasterJames** [comment]
Also note mouseleave and mouseenter

**Comment by MasterJames** [comment]
What I discovered could be related to issues arising here is if you are foolish enough to disable the OrbitControls while attempting some form of your own dragging. And continue dragging outside the window and release the mouse button the OrbitControls loose the mouseUp and the mouseOut=mouseUp so when the mouse enters the window again it spins the orbits even though no mouse down exists anymore. As a simple hack/fix I commented out line 761 to allow onMouseUp even if the scope is disabled and then I get the desired effect.
I was thinking maybe there is a need for a setEnabled function or something to cleanup by triggering a mouseUp if it's had a mouseLeave but the mouse is still down tracking, or what is that people do in this situation? 
Alternative thinking further for a good solution, I figure maybe OrbitControls should monitor for a mouseLeave and trigger another mouseUp **even if it's scope has been disabled mid-tracking**.

**Comment by MasterJames** [comment]
Okay final word from me here. I'll move it to StackOverflow or a PR if I have more to add.
Basically mouseLeave and mouseOut don't function properly so I recommend testing the mouseUp with an eventOutside function whenever whereever needed.
In the case of OrbitControls.js I also commented out all mouseout event listeners and added the function and call to it in onMouseUp for allowing it to run even when it's an event occurring 'outside' even if the scope (aka OrbitControls object) has been disabled for the purposes of dragging.
I'm sure there's a nicer way of handling odd edge cases with a dragging mode setter/getter funcs etc.

```
	function eventOutside( event ) {

		if(event.clientX < 0 || event.clientY < 0) return true;

		if(event.clientX > event.target.clientWidth || event.clientY < event.target.clientHeight) return true;

		return false;
	}

	function onMouseUp( event ) {

		if ( eventOutside( event ) === false && scope.enabled === false ) return;

		handleMouseUp( event );

         . . . 

    }

```

**Comment by unconed** [comment]
It seems the mouseout handler was added here: https://github.com/mrdoob/three.js/pull/7434

It makes no sense at all, because it disables all the built-in mouse capturing behavior in OrbitControls, thus creating a lot of dead code. If I comment out the mouseout handlers, I can't reproduce any sticky mouse behavior in OS X Chrome, Safari or Firefox.

http://acko.net/files/dump/orbitcontrols/error.html
http://acko.net/files/dump/orbitcontrols/fixed.html

This is particularly bad when you have elements overlapping the renderer, because they also trigger mouseout, e.g. http://acko.net/files/dump/orbitcontrols/overlay.html

So either the original request was due to another browser/OS failing to fire the mouseup event, or they were indeed doing something funky with the controls.
