### ISSUE TITLE
Rotating a sphere to a specific point. Not the camera!

### ISSUE THREAD

**Issue by andreb07** [mrdoob/three.js#8158]
Hello guys, i need some help on this one.

I have search and couldn't find solutions for this, because all the solutions were about rotating a camera around a sphere.

In my case, the camera is still. I have a webgl globe with points around using latitude an longitude. I just want to click a point and rotate the globe mesh so that it centers that point.

I have the point Vector3, it's latitude and longitude but i can't figure how to do this.

Is someone around that can help me? Or know any example like this?

Thank you in advance

**Comment by bioship** [comment]
ask for help [here](http://stackoverflow.com/questions/tagged/three.js); this place is for bugs and stuff
