### ISSUE TITLE
Clickable objects not clickable?

### ISSUE THREAD

**Issue by nlogax2** [mrdoob/three.js#8163]
Hello,

I am attempting to turn 3D objects into clickable elements by using an array called objects[]; and a switch statement which accesses the userData of the object. Right now, the script runs with no errors yet the objects still aren't clickable. What am I missing?

      var container, stats;
            var camera, scene, raycaster, renderer;
    
            var mouse = new THREE.Vector2(),
                INTERSECTED;
            var radius = 100,
                theta = 0;

    
    
    
    
            function createMesh(name, geometry, material) {
    
                var object = new THREE.Mesh(geometry, material);
                object.position.x = Math.random() * 800 - 400;
                object.position.y = Math.random() * 800 - 400;
                object.position.z = Math.random() * 800 - 400;
    
                object.scale.x = Math.random() * 2 + 1;
                object.scale.y = Math.random() * 2 + 1;
                object.scale.z = Math.random() * 2 + 1;
    
                object.rotation.x = Math.random() * 2 * Math.PI;
                object.rotation.y = Math.random() * 2 * Math.PI;
                object.rotation.z = Math.random() * 2 * Math.PI;
    
                object.userData = {
                    URL: "http://www.google.com"
                };
                var objects = [];
    
                for (i = 0; i > objects.length; i++) {
                    objects += i;
                    objects.push(object);
                }
                scene.add(object);
    
    
    
                switch (i) {
                    case 1:
                        objects[i].userData = {
                            URL: "http://www.google.com"
                        };
                        break;
                    case 2:
                        objects[i].userData = {
                            URL: "https://www.yahoo.com"
                        };
                        break;
                }
    
    
                object.name = name;
            }
    
        </script>

**Comment by oak415** [comment]
If you found the solution can you post it here?

**Comment by nlogax2** [comment]
oak, email me at nlogax2@gmail.com
