### ISSUE TITLE
why not make webglproperties accessible?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#8164]
they are currently defined as
```
var properties
```
why not do
```
this.properties
```
instead?

I understand that normally users should not mess with them, but sometimes there is no way around it. For example, recently I had to use THREE.WebGLRenderTarget as a texture in pixi. I saw you have setTexture method in renderer that could allow me to do this without accessing __webglTexture, but the problem was that pixi just does not give you a chance to call it - without accessing __webglTexture directly I would have to implement whole pixi rendering plugin, and accessing it allowed to create fake texture and use with their sprite system. For another example, [this SO thread](http://stackoverflow.com/questions/6171932/webgl-reading-pixel-data-from-render-buffer) is dealing with reading pixels from WebGLRenderTarget, but now when  __webglFramebuffer is no longer accessible, this is not possible in the clean way.

But there are workarounds, yes? Yes. We could override WebGLProperties prior to creating WebGLRenderer. In fact, I just did this:
```
var hack = 'THREE.WebGLProperties = ' + THREE.WebGLProperties;
hack = hack.substr (0, hack.length -1) + '; THREE.WebGLProperties.lastInstance = this; }';
eval (hack);
```

but obviously having properties available as renderer.properties is a bit better.

**Comment by mattdesl** [comment]
Seems like this is already possible:
https://github.com/mrdoob/three.js/blob/e68e36cb40cadecd46ddc7013bd70861c3ed9843/src/renderers/WebGLRenderer.js#L285

```js
renderer.properties.get(...)
```

**Comment by mrdoob** [comment]
Ah yeah, forgot about that 😅
