### ISSUE TITLE
WebGLShader can't compile, worldPosition undeclared identifier

### ISSUE THREAD

**Issue by izatar** [mrdoob/three.js#8166]
I just triggered an error from WebGLShader where "worldPosition" is an undeclared identifier. 
This is happening because of this code:
```
176: #if defined( USE_ENVMAP ) || defined( PHONG ) || defined( STANDARD ) || defined( LAMBERT ) || defined ( USE_SHADOWMAP )
177: 	#ifdef USE_SKINNING
178: 		vec4 worldPosition = modelMatrix * skinned;
179: 	#else
180: 		vec4 worldPosition = modelMatrix * vec4( transformed, 1.0 );
181: 	#endif
182: #endif
183: 
184: vWorldPosition = worldPosition;
```

has a path that does not define worldPosition.  While it could be this is considered intentional or acceptable, it surely seems like an error to have code use an undefined variable in any code path. You gotta ask why the code even has the outside test if its only purpose is to cause a crash.

As an aside, I triggered this by attempting to add shadow parameters to a point light created by the collada2 loader .  This being the maybe 'wrong thing to do' may or not be relevant.

**Comment by WestLangley** [comment]
> You gotta ask why the code even has the outside test if its only purpose is to cause a crash.

There is no need for condescending remarks here.

Can you provide a test case so we can reproduce your results? Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by izatar** [comment]
I was not intending to be condescending.  It is just a comment about some curious code I am trying to understand.  I really don't know what the if this code is working as intended or not.   

I don't know if I will be able to give a reproduction.  The code base I have is large, complicated, uses some proprietary components and is server dependent.   And I dont actually know what is causing the issue.

**Comment by makc** [comment]
@WestLangley you are always denying us the fun of condescending remarks, but I don't see you shutting up people when they praise you for the good work ) I demand all off-topic remarks to be treated equally.

**Comment by mrdoob** [comment]
@makc It's not about off-topic, it's about respect. Also, I don't think enough people is praising @WestLangley for his good work as he deserves.

**Comment by makc** [comment]
![lol](http://cdn.meme.am/instances/500x/62621550.jpg)

**Comment by izatar** [comment]
[shadercrash.zip](https://github.com/mrdoob/three.js/files/137454/shadercrash.zip)

attached should be a repro-case.   run examples/atest_webgl_loader_collada.html and you should see some errors.  Chrome prints them out with nice handy source code.

**Comment by mrdoob** [comment]
@izatar Thanks! Also happens here. Not sure what's causing it though, I think it's the `PointLight`'s shadow code.

**Comment by mrdoob** [comment]
Ok, seems like this happens when `mesh.castShadow` is set to `true` but `mesh.receiveShadow` is set to `false`.

**Comment by mrdoob** [comment]
Fixed. Thanks!

**Comment by izatar** [comment]
I see your fix, and I'm sure it addresses the problem.
But still the code in the shader is sort of weird because it has path with an undefined variable.
Its like "undefined variable" is being used as an assert.  Is this intended?

**Comment by mrdoob** [comment]
What's the path that has the undefined variable?

**Comment by mrdoob** [comment]
Unfortunately we made the decision of going with the "Uber shader" approach at some point and it produces shaders that aren't easy to read.

Hopefully we'll change the way we assemble these shaders in the near future.

**Comment by izatar** [comment]
well if this fails:
#if defined( USE_ENVMAP ) || defined( PHONG ) || defined( STANDARD ) || defined( LAMBERT ) || defined ( USE_SHADOWMAP )

then worldPosition  is not defined and you get error this bug reproduces.

**Comment by mrdoob** [comment]
That's why my fix is making `distancesMaterial` define `USE_SHADOWMAP` to make sure that the check never fails for that shader.

**Comment by mrdoob** [comment]
The next step is to move all these ifdefs to javascript and replace with `#ifdef USE_WORLDPOS`

**Comment by alecmce** [comment]
FYI - I got here because I got exactly this error, so it's still reproducible in some contexts :/. The code to recreate is too complex to paste in, so I'm going to have to dig myself.
