### ISSUE TITLE
THREE.Math.generateUUID 15th character always 4

### ISSUE THREAD

**Issue by jkarbows** [mrdoob/three.js#8168]
When browsing the THREE library functions I noticed that after inserting the dashes there is another condition which makes the 15th character of the id produced by THREE.Math.generateUUID always 4.
Is there a reason for this?

```javascript
if ( i === 8 || i === 13 || i === 18 || i === 23 ) {

	uuid[ i ] = '-';

} else if ( i === 14 ) {

	uuid[ i ] = '4';

} else {

	if ( rnd <= 0x02 ) rnd = 0x2000000 + ( Math.random() * 0x1000000 ) | 0;
	r = rnd & 0xf;
	rnd = rnd >> 4;
	uuid[ i ] = chars[ ( i === 19 ) ? ( r & 0x3 ) | 0x8 : r ];

}
````

[https://github.com/mrdoob/three.js/blob/master/src/math/Math.js](https://github.com/mrdoob/three.js/blob/master/src/math/Math.js)

**Comment by mrdoob** [comment]
[UUID Version 4](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29)
