### ISSUE TITLE
view-source links will have to go

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#8170]
They no longer work in nightly FF:

![screen shot 2016-02-19 at 3 36 07](https://cloud.githubusercontent.com/assets/242577/13165129/93c44cb0-d6ba-11e5-912f-432052c5543a.png)

Maybe show the link in the input box for copy-paste or check what pixi does [here](https://github.com/pixijs/examples/blob/gh-pages/_site/js/viewer.js#L59-L99).

**Comment by mrdoob** [comment]
Oh my...

**Comment by Mugen87** [comment]
As far as i know, Firefox and Chrome are the only browser which support the URL protocol "view-source:". AFAIK Safari, Opera and Edge try to find a local application to open the URL. Maybe it's worth to develop a solution that works in all browsers...

**Comment by Mugen87** [comment]
I think i've found a very simple solution. Instead of 

```javascript
window.open( 'view-source:' + array.join( '/' ) + '/' + selected + '.html' );
```
we can do this...
```javascript
window.open( 'https://github.com/mrdoob/three.js/blob/master/examples/' + selected + '.html' );
```

This approach works in all browser...

**Comment by makc** [comment]
+1 @Mugen87 also has pretty colors

**Comment by verteAzur** [comment]
Can't we keep the useful "view-source" call that give us access to the proper version based on the example, it also links other files within the source code and works while not online. Why not add a catch and try statement if  "view-source" is not available. Plus, I would recommend to use relative URLs while using view:source. It is certainly why you are getting a security error on nightly FF.

```
try{
    window.open( 'view-source:' + selected + '.html' );
}catch(err){
    window.open( 'https://github.com/mrdoob/three.js/blob/master/examples/' + selected + '.html' );
    console.log(err);
}
```

**Comment by mrdoob** [comment]
@verteAzur That sounds good to me. Would you like to do a PR?

**Comment by verteAzur** [comment]
view source support https://github.com/mrdoob/three.js/pull/9225

**Comment by Frazer** [comment]
what about 
document.querySelector('.codePopup').innerHTML =  "<pre>" + document.querySelector('.codeToDisplay').outerHTML + "</pre>";
