### ISSUE TITLE
THREE.Audio does not expose web audio api events

### ISSUE THREAD

**Issue by m4chinations** [mrdoob/three.js#8176]
[This question on SO](https://stackoverflow.com/questions/35323062/detect-sound-is-ended-in-three-positionalaudio/35497371#35497371) asks about listening for events generated by THREE.Audio objects, specifically `loaded` and `ended`. The user is loading a sound file from a URL, so THREE is using an `AudioBuffer` object to play the file. However, when using `THREE.Audio`, the underlying `AudioBuffer` is never exposed until the `loaded` event has already fired. Because of this, the only way I could see to detect the `loaded` event was overriding  [`THREE.Audio.prototype.setBuffer`](https://github.com/mrdoob/three.js/blob/ddab1fda4fd1e21babf65aa454fc0fe15bfabc33/src/audio/Audio.js#L61) and adding a listener there. `ended` was easier, but still involves overriding functions defined in `THREE.Audio`. 

Perhaps the `THREE.Audio` class can be improved to provide easy access to all the html5 audio events, including `ended`, `complete`, and `loaded`. I would be happy to work on a PR, if this is something worthwhile.

**Comment by Mugen87** [comment]
@mrdoob What do you think about implementing `THREE.EventDispatcher` in `THREE.Audio`.

```javascript
THREE.EventDispatcher.prototype.apply( THREE.Audio.prototype );
```
We can then dispatch events from certain audio methods and users can set event listeners. Besides, we can achieve this with a minimum amount of changes.

New `onEnded` method:
```javascript
THREE.Audio.prototype.onEnded = function() {

	this.isPlaying = false;
	this.dispatchEvent( { type: 'ended' } ); // ended
};
```

Usercode:
```javascript
sound.addEventListener( 'ended', function(){
	console.log( 'ended' );
})
```

**Comment by mrdoob** [comment]
Sounds good, but I realise that this API style is different than the other loaders.

**Comment by Mugen87** [comment]
With `THREE.AudioLoader`  it should be easier to apply an `onLoad` callback now. But `THREE.Audio` still provides no hooks for other `AudioBufferSourceNode` events like `complete` or `ended`. Could `THREE.EventDispatcher` not be a solution for these cases?

**Comment by Mugen87** [comment]
> provide easy access to all the html5 audio events,

Since `THREE.Audio` can work with audio buffers and audio streams (HTML5 audio), it would introduce a certain amount of complexity to dispatch all relevant events. If users really needs these events, it's probably better to monkey-patch the code.

Also notice that `AudioLoader` has been introduced which makes it easier to track the loading process of audio files.

**Comment by kylebakerio** [comment]
I'm looking for how to handle this scenario now in 2020; did this ever change? Is the answer in that SO question / monkeypatching still the best way to handle this? I'm confused especially because I do see an 'onEnded' method, it just doesn't seem to do anything.

**Comment by Mugen87** [comment]
> did this ever change?

No. There is no API for registering custom event listener,

> I'm confused especially because I do see an 'onEnded' method, it just doesn't seem to do anything.

The `onEnded` method is internally used and assigned to an audio buffer source node:

https://github.com/mrdoob/three.js/blob/bd3da04442f4ab4133ad65ab6672064ec8b7c1e5/src/audio/Audio.js#L113

**Comment by kylebakerio** [comment]
Confisingly, there seems to be a solution in the docs, I just didn't read it right at first. Maybe I'm missing something, but it works well for me... I responded [here](https://stackoverflow.com/a/65415736/4526479) on SO showing the solution.

```js
var sound1 = new THREE.PositionalAudio( listener );
sound1.onEnded = () => console.log("track ended")
```

Docs [here](https://threejs.org/docs/#api/en/audio/Audio.onEnded).

It's not every event of course, but it does cover this very common, very basic one. From there, a synthetic event can be generated if desired, or a promise resolve, etc.
