### ISSUE TITLE
README.md example on jsfiddle doesn't work in firefox

### ISSUE THREAD

**Issue by anfelor** [mrdoob/three.js#8185]
The jsfiddle document doesn't render in (latest) firefox due to mixed content policy:
The url _http://threejs.org/build/three.min.js_ used in the html document 
is loaded over http, not https.

Unfortunately, simply replacing http with https doesn't work as
_https://threejs.org/build/three.min.js_ doesn't exists.

**Comment by mrdoob** [comment]
Fixed. Thanks!
