### ISSUE TITLE
nevermind

### ISSUE THREAD

**Issue by tistatos** [mrdoob/three.js#8196]
Currently, the order is:
1. Normalized Device Coordinates 
2, The camera.

I very often write this in the opposite order since the constructor of the ray caster wants origin then direction. I interpret the NDC as the direction and the camera as the origin, and it feel kinda non-intuitive in the current order.

**Comment by serj-by** [comment]
It will break backward compatibility. Isn't it?

**Comment by tistatos** [comment]
yes it would, but incredible easy fix for the end-user

**Comment by serj-by** [comment]
For let's say 50 projects. Handy. Yeah.

**Comment by tistatos** [comment]
need help?
in sublime search and replace with:
find: "setFromCamera\((\w+), (\w+)\)"
replace with: "setFromCamera\((\w+), (\w+)\)"

Refactor done

**Comment by izatar** [comment]
worst idea ever.  selfish bastards changing stuff for no reason causing other people thousands of man-hours of work

**Comment by mrdoob** [comment]
@tistatos sorry about that... @izatar tone was unnecessarily unrespectful indeed.
