### ISSUE TITLE
Need some way to roll the edge of a CylinderGeometry

### ISSUE THREAD

**Issue by MyTek** [mrdoob/three.js#8198]
I have this code which works great:

`var newplastic = new THREE.TextureLoader();
var newplasticimage = newplastic.load( "./models/collada/2q/clear.png" );
var cupbottomsidesmaterial = new THREE.MeshPhongMaterial( { transparent:true, color:0xffffff, depthWrite: true, side: THREE.BackSide, map: newplasticimage } );
var cupgeometry = new THREE.CylinderGeometry( cuptopradius, cupbottomradius, cupheight, cupradiussegments, cupheightsegments,0 );`

My issue is I need to "roll" the edge of the larger part of the cylinder and have the material roll with it.  I'm trying to make a cup like one you would get from fast food or a plastic solo cup.  I'm not sure if this is where I could post a question about this so if my in the wrong place I apologize!!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

Maybe `THREE.LatheGeometry` would work better for you, but please use stackoverflow for help

**Comment by MyTek** [comment]
Ok Thank you.
