### ISSUE TITLE
threejs.org/examples/webgl_loader_collada_keyframe.html doesn't work in Chrome (Win10)

### ISSUE THREAD

**Issue by StarPlugins** [mrdoob/three.js#8200]
This example: [http://threejs.org/examples/webgl_loader_collada_keyframe.html](http://threejs.org/examples/webgl_loader_collada_keyframe.html) no longer works in Chrome (running under Windows 10).

Using r74.

Seems to work fine on IE11/Edge, FireFox, Chrome Android and Safari iOS

These errors show in console:

THREE.WebGLProgram: shader error:  0 gl.VALIDATE_STATUS false gl.getProgramInfoLog C:\fakepath(254,9-30): error X3004: undeclared identifier 'IncidentLight'

Warning: D3D shader compilation failed with default flags. (vs_3_0)
 Retrying with avoid flow control
C:\fakepath(254,9-30): error X3004: undeclared identifier 'webgl_45daf4aa877f103d'

Warning: D3D shader compilation failed with avoid flow control flags. (vs_3_0)
 Retrying with prefer flow control
C:\fakepath(254,9-30): error X3004: undeclared identifier 'webgl_45daf4aa877f103d'

Warning: D3D shader compilation failed with prefer flow control flags. (vs_3_0)
Failed to create D3D shaders.

**Comment by mrdoob** [comment]
#8161
