### ISSUE TITLE
OBJLoader + MTLLoader != OBJMTLLoader

### ISSUE THREAD

**Issue by veleek** [mrdoob/three.js#8203]
A few people have commented about the fact that OBJMTLLoader has been removed (#8085, #8105) since it's recent removal.  I was wondering if there is more information on why this was removed given that OBJLoader + MTLLoader is missing a bunch of functionality that OBJMTLLoader provided.

1. OBJMTLLoader uses the `mtllib` tag to associate a specific OBJ file with an arbitrary MTL file.  With OBJ+MTL I need to manually map my OBJ files to MTL files which may not have a 1 to 1 name mapping if I have an MTL file that I'm sharing with multiple OBJ files (in my case I have a few MTL files, and many different object files each use a small number of MTL files).

2. OBJ+MTL does not properly parse OBJ files with multiple materials on a single mesh.  For example, I have created a model of a pot and I use a different material for the inside of the pot than I do for the outside.  This OBJ file defines two objects.  The first object uses a single material and loads properly.  The second object uses two different materials for different parts and only loads one material when rendering.  Here is the trimmed OBJ file:

```
# Blender v2.76 (sub 0) OBJ File: 'pot.blend'
# www.blender.org
mtllib pot4.mtl
o Pedastel 
v -35.000000 -38.500000 35.000000
...
vn 0.000000 0.632100 -0.774900
usemtl Pedastel
s off
f 27/1/1 29/2/1 31/3/1 25/4/1
...

o PotMesh_Mesh
v -0.000016 0.000000 0.000000
...
vn -0.000300 1.000000 -0.002400
usemtl PotOutside
s 1
f 84/25/12 148/26/13 3295/27/14 83/28/15
...
usemtl PotInside
f 3182/1250/1164 3289/1251/1164 145/1252/1164 81/1253/1164
...
```

**Actual Behavior:**
OBJLoader reads the usemtl statement and sets the material name of the current object, creating the mesh and assigning the actual material after the entire file has been parsed resulting in a single object using whatever material the last usemtl statement referred to.

**Expected Behavior:**
OBJMTLLoader creates a mesh using whatever the current face data is saves it using the current material and then starts a second mesh using the newly identified material.

Note: This OBJ was generated by a relatively recent version of Blender, so my assumption is that the format is valid and this is a reasonable thing to have in an OBJ file.

**Comment by veleek** [comment]
I've committed an example of what could be a reasonable fix for loading an object with multiple materials to my fork here: b6ae515a7a935a9bd09f40ae43f3dd95c4a1914c.  Probably still reasonable to look into getting it to use the mtllib option, but this would be a good start for now and isn't very disruptive to the current code.  Let me know if it's worth submitting a pull request.

**Comment by mrdoob** [comment]
Maybe we add a `setMTLLoader` method to `OBJLoader` so we can bring back the lost functionality?

**Comment by veleek** [comment]
I'll give that a shot and get back to you.

**Comment by birgersp** [comment]
Thanks @veleek for the fix, we cannot use our Blender models (.obj + .mtl) in our threejs application without it

**Comment by jonnenauha** [comment]
Talking about practical steps it looks like what you want is a single geometry using different material for a set of faces. Looking at the code base is looks like `THREE.MultiMaterial` is designed for this.

The renderer iterates `geometry.groups`, picking the right material from `group.materialIndex` from the `THREE.MultiMaterial.materials` array: 
https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1358-L1374

@veleek code here https://github.com/mrdoob/three.js/commit/b6ae515a7a935a9bd09f40ae43f3dd95c4a1914c takes the approach of splitting a new submesh/object when it encounters a `usemtl`. Btw. that fork will be out of sync badly when/if my PR is merged :I

I'm not confident starting a new child when a material is encountered is the right approach? Can this break rendering? I suppose the overhead of more draw calls is the same if splitting to a unique geometry or splitting into geometry.groups?

Starting a new child on material declaration would also produce more submeshes than what the .obj file declared, so I guess it would be "wrong" in that sense? As said both probably upload as many geometries to the GPU and executes as many draw calls but the child count would be correct in `THREE.MultiMaterial` approach.

It looks to me that when a material declaration is encountered mid face declarations, it should at that point split the geometry into groups and assign the material index.

If someone can tell me if I missed something about `THREE.MultiMaterial` or if it has some performance drawbacks why splitting to multiple children would be preferable?

@birgersp could you upload the example obj and related mtl/texture files so I could take a look at this?

**Comment by jonnenauha** [comment]
To the original topic it looks like `dev` head has `ObjLoader.materials and ObjLoader.setMaterials()` which is used later in parsing.

```js
if ( this.materials !== null ) {
	material = this.materials.create( object.material.name );
```

The `.create()` call there indicates that `this.materials` should be a instance of `THREE.MTLLoader.MaterialCreator` that is produces by `THREE.MTLLoader.parse()`.

Btw. This does not seem to be documented at this point, if not that should be fixed.

However this kind of creates a ass backwards situation if you wish to use the `mtllib` declared in the .obj itself. You need to parse the obj to know what material it needs (eg. you need to load it from network), but at the same time its already too late to give the material as parsing and setting the materials is done. So `setMaterials` is only useful if you have pre existing knowledge about the material it needs. In this case you also need to load and parse the mtl file before you load/parse the obj file.

`ObjLoader.parse` does mark the material name into `container.children[index].material.name` so it can be applied to later. What I could wish to see is for two utilities to make this a bit more sane and easier to use.

**ObjLoader can auto load referenced materials**

This might get a bit tricky as the loader would need to know the base url/ref of the obj being loaded. If you use `.load` it could be resolved, but if you use `parse` with data you fetched yourself, you'd need to provide it.

Anyways, if `THREE.MtlLoader` can be found (included in the app) it should auto load it and set the materials automatically when load + parse succeeds. The parse function can already return its results and asynchronously set the materials.

**MtlLoader should have a way to apply itself to a set of children**

I have made a addition to ObjLoader that it stores all the referenced `mtllib` lines so you can load materials post parse. Making some kind of apply logic would remove a lot of boiler plate code you have to copy paste.

```js
var baseUrl = "/assets/obj/";
objLoader.load(baseUrl + "my.obj", function(container) {
	for (var i=0; i<container.materialLibraries.length; i++) {
		mtlLoader.load(baseUrl + container.materialLibraries[i], function(mtlCreator) {
			mtlCreator.apply(container);
		}):
	}
});

// THREE.MTLLoader.MaterialCreator.apply could look something like this

apply : function(object) {
	object.traverse(function(child) {
		if (child && child.material && child.material.name && this.materialInfos[child.material.name])
			child.material = this.create(child.material.name);
	}.bind(this));
}
```

I know that apply would be trivial to write in app code, but it has to know internals like `mtrCreator.materialInfos` which might be renamed at some point etc.

This same `apply` could then be used by the auto loading feature of `ObjLoader` if that is implemented.

**Comment by jonnenauha** [comment]
To clarify auto loading materials in `ObjLoader` would be a opt in feature. If it would be on by default it would break all kinds of apps that set custom materials after `parse` completes.

My PR already adds support for per loader options and per parse call options object.

**Comment by MrPollux** [comment]
The two small changes have led me to success.
OBJLoader.js
...
318: var materialName = object.material.name; //INSERTED
319: addObject( name );
320: if ( materialName !== undefined ) { object.material.name = materialName; } //INSERTED
...

**Comment by veleek** [comment]
@jonnenauha Using `MultiMaterial` seems like a perfectly reasonable solution, I didn't actually know about it before.  Looking through the code a bit, `OBJLoader` currently doesn't set the `materialIndex` of the faces, which is used by `DirectGeometry.computeGroups()` to actually create the groups that are used by MultiMaterial.  

So, we would need to make sure that's all setup during the parsing and make sure that the computeGroups stuff actually happens, but it seems doable.

**Comment by jonnenauha** [comment]
Oh, I did not catch that it automatically creates the groups if that `materialIndex` is set, that is fairly nice. I guess we should not mark the index except when multiple materials are encountered, to not put any overhead or make all obj loading create groups and user multimaterial when not needed. Ill have to take a peek at the code you pointed out. If its just marking the indexes it should be fairly trivial to implement.

Not sure what code you looked at but for buffer geometry I dont think there is a way to mark this index for each face. You might have been looking at the `THREE.Geometry` code? Buffer geometry just has arrays of stuff, I would suspect the group split needs to be done by hand or via draw calls or something. I'll have to read up on this a bit more before implementing it.

**Comment by mrdoob** [comment]
> Buffer geometry just has arrays of stuff, I would suspect the group split needs to be done by hand or via draw calls or something. 

Yes, `BufferGeometry` supports groups (similar to `g` in `.obj` afaik). All the groups share the same buffers but you basically set the start and end of the group and the material index (requires `THREE.MultiMaterial`).

https://github.com/mrdoob/three.js/blob/master/src/core/BufferGeometry.js#L86-L96

This is the relevant code inside `WebGLRenderer`:

https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L855-L864

**Comment by jonnenauha** [comment]
Alright, so I suppose this groups has replaced the old "draw calls" you could also configure, afaik it similarly referenced the same geometry.

It would seem using the groups is the best approach here as you can parse the geometry and after it just set the groups you want without tweaking the parsed geom. Seems a lot less hassle for the impl. These groups just need to be marked to the parser object state and set to the created buffer geom at the end. Should be fairly trivial.

Anyone have a reference file that whoever implements this could use? I might tackle this after my current PR is sorted out.

**Comment by jonnenauha** [comment]
@veleek The #8691 is now merged. Could you test your assets with latest `dev` and verify it fixes your issues.

There are a few remaining points in this issue that I discussed a bit in https://github.com/mrdoob/three.js/issues/8203#issuecomment-200571242.

I would at minimum want to see `mtlLoader|mtlCreator.apply(objLoaderCreatedObject);` for post loading the materials into a OBJLoader parsed object. This would be a nicer API rather than the current where you would loop all your objects, check if the material name can be created by the creator etc.

**Comment by makc** [comment]
just runned into situation where I need to parse the obj file and then move its vertices. guess what, it desintegrates because of non-indexed BufferGeometry. so now I need to go to git history and find old loader 👎 thanks obama

**Comment by mrdoob** [comment]
@makc Yeah, that's a difficult one. If only WebGL allowed multiple indices...

**Comment by makc** [comment]
ok, for the reference, found it [here](https://github.com/mrdoob/three.js/blob/db23db0bc11fb058224a3a4f896cf675351536e1/examples/js/loaders/OBJLoader.js) (changed to buffer geometry by 681685f) oh boy, looks like I am missing lots of fixes now

**Comment by carlosanunes** [comment]
Just to recap then. The current OBJLoader does not support multiple materials, correct ?

**Comment by makc** [comment]
#8691 says it does

**Comment by carlosanunes** [comment]
Oops, missed that.

So basically the object is break down in multiple meshes albeit children of the same group.

**Comment by jonnenauha** [comment]
What is not intuitive? Its using three.js primitives to represent the parsed file the best we can without hacks.

If you change materials mid geometry declaration, the best analog I could find for it is multi-material. There is a single geometry, there is no break down or splitting. Just multiple materials with group indexing that will produce multiple draw calls.

This approach is not visible the to user. You'll find the right amount of objects in the parsed container as the file represents, as it should.

Could you point me to this documentation that I could fill in for this loader. This is pretty much what I can find, there is no apparent "official" docs for this "example loader" and is not part of the "core" https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/OBJLoader.js#L1-L3

**Comment by carlosanunes** [comment]
Oh, I am not questioning the solution, only pointing out that it is not intuitive in the sense that the behaviour is not obvious.

It is not obvious that multiple Meshes will be created. And it is fairly likely that some dev or other will use logic that makes the assumption that the imported single object will have a single mesh.

> Could you point me to this documentation that I could fill in for this loader. 

Don't know the source for it, but the available page is [](http://threejs.org/docs/#Reference/Loaders/OBJLoader) .

It actually states this:

> Parse an obj text structure and return an Object3D.
> Found objects are converted to Mesh with a BufferGeometry and a default MeshPhongMaterial.

And although this is not strictly wrong it is very misleading considering current behaviour.

**Comment by jonnenauha** [comment]
> It is not obvious that multiple Meshes will be created. And it is fairly likely that some dev or other will use logic that makes the assumption that the imported single object will have a single mesh.

Right, this is the confusion then. It **does not** create multiple meshes. As I said earlier, MultiMaterial is actually the only way that I know of that preserves the .obj file structure, so that you have the same number or returned objects (as children in the returned root) as you have `o/g` in the file.

To clarify I'm now talking about files that change objects material while in the middle of declaring faces. This will produce a single mesh, geometry and MultiMaterial. The material obviously has multiple materials in it, that during the rendering of the object produces multiple draw calls.

But you as the developer should see a single mesh. If you want to manipulate the mesh material, you'll have to take into account the possibility of there being multi-material.

Do you have a obj file that does something different? Please link or attach it.

> Parse an obj text structure and return an Object3D.
Found objects are converted to Mesh with a BufferGeometry and a default MeshPhongMaterial.

I suppose this should be tweaked to: Found objects are converted to Mesh using BufferGeometry. Materials can be provided with a MTL loader or default MeshPhongMaterials/MultiMaterials are created.

**Comment by carlosanunes** [comment]
> Do you have a obj file that does something different? Please link or attach it.

I just looked at the three.js example - http://threejs.org/examples/webgl_loader_obj_mtl.html, and did a 'console.log(scene)'.

The imported .obj is translated to the three.js scene as a THREE.Group object with 14 THREE.Mesh children objects.

**Comment by jonnenauha** [comment]
Right, and the obj file used in it http://threejs.org/examples/obj/male02/male02.obj declares 14 objects with `g <name>` and similarly there are 14 `usemtl <name>`. It does not change materials mid face declarations, hence it does not even use the MultiMaterial code path (of which inconsistencies you tried to demonstrate with this file). All 14 materials in the children are MeshPhongMaterials.

I think we might be talking about different things here.

**Comment by mrdoob** [comment]
> Oh, I am not questioning the solution, only pointing out that it is not intuitive in the sense that the behaviour is not obvious.

It depends on whether the obj is using `o` or `g` internally. We con't do much about that.

**Comment by mrdoob** [comment]
I'm going to close this one so it doesn't get hijacked again.
