### ISSUE TITLE
remove axis helper from cube.

### ISSUE THREAD

**Issue by hadi1709** [mrdoob/three.js#8204]
How do I remove axis helper from the cube?

I added : cube1.add(axisHelper);
I used cube1.remove(axisHelper); , but it doesn't work.
I also tried  cube1.removeObject(axisHelper); &  cube1.removeChild(axisHelper); but still nothing happened.

Thanks in advance!

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
