### ISSUE TITLE
AMBIENT constant missing from exporter

### ISSUE THREAD

**Issue by zydecode** [mrdoob/three.js#8205]
AMBIENT = 'ambient' is missing from line 276 of the python constants file in the exporter, which caused an error on export from Blender. Adding the constant back in solved the issue for me.

**Comment by mrdoob** [comment]
I can't find where `AMBIENT` is being referenced in the Blender exporter...
https://github.com/mrdoob/three.js/tree/master/utils/exporters/blender

**Comment by zydecode** [comment]
sorry, must have been an issue my end. I deleted the exporter, re-installed it and deactivated/reactivated it and it worked without error this time.
