### ISSUE TITLE
Move unrollLoop into WebGLShaderPreProcessor

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8206]
Right now there is a cool preprocessor step in WebGLProgram that unrolls loops:

https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/WebGLProgram.js#L164

I would like to move that eventually into the new WebGLShaderPreProcessor I am proposing in PR #8117:

https://github.com/bhouston/three.js/blob/texture_encoding/src/renderers/webgl/WebGLShaderPreProcessor.js

**Comment by mrdoob** [comment]
Sounds good!

I've been thinking of moving things to the same #include * approach and simplify ShaderLib but I wanted to do some timming tests first.

However, I think that compile function could be simpler? How about using the unroolLoop function approach?

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/commit/ca6128d703096f4bc38604759e8d8430f6e13dca

**Comment by bhouston** [comment]
Sweet.
