### ISSUE TITLE
MeshPhongMaterial bug with bones animation

### ISSUE THREAD

**Issue by iRomano** [mrdoob/three.js#8210]
Hello!

This bug on iPhone 6 or higher and iPad Air 2 or higher
But on iPhone5s or lower and iPad3 or lower - bug is ubsent.

In our game we use custom MatCap shader with bones animation, and we have problem with shader:
If lamb had fly, he was doubles

Video:
https://goo.gl/SEYSUJ

You can play from mobile:
http://goo.gl/CVy9pq

After that we changed MatCap shader => MeshPhongMaterial.
And we have same problems with MeshPhongMaterial:

Video:
https://goo.gl/xAlrcm

You can play from mobile:
http://goo.gl/uzAbQs

If we take off bones animation - bug is absent:
Current version game:
http://goo.gl/O6038S

We use r73, because webvr-boilerplate work with this version

That wrong with shaders?
How fix it?

**Comment by iRomano** [comment]
ping @mrdoob

**Comment by mrdoob** [comment]
Is difficult to work with that, if you could reproduce the issue in a jsfiddle it would help a lot.

**Comment by Mugen87** [comment]
@iRomano Closing. We can reopen the issue if you can reproduce the problem with a [live demo](https://jsfiddle.net/f2Lommf5/) and the latest `three.js` version.
