### ISSUE TITLE
editor crashes when planeGeomerty.segments set as 1100

### ISSUE THREAD

**Issue by RoeePeleg** [mrdoob/three.js#8211]
im using three.js r73 in pc with chrome (windows 7), and the editor crashes when in thhis line of the 
code : 

``var geometry = new THREE.PlaneGeometry(1100, 1100, 1100, 1100);``

is there a limitation on the segments i dont know of ? 
how can i fix it ? 
thx in advance

**Comment by mrdoob** [comment]
1100 * 1100? That produces a plane of 2,420,000 polygons. Why so many polygons?

**Comment by RoeePeleg** [comment]
im trying to load texture, map it on a plane in the texture's original size, and leave the rest of the plane in white color. 

so i use this : 

``	option.onClick(function () {
        
	    var obj = editor.selected;
	    var material = obj.material;
	    var tex = material.map.mapsArray[0];
	    var objHeight = obj.geometry.parameters.height;
	    var objWidth = obj.geometry.parameters.width;
	    var texHeight = tex.image.height;
	    var texWidth = tex.image.width;
	    
	    tex.repeat.x = objHeight / texHeight;
	    tex.repeat.y = objWidth / texWidth;
	    tex.offset.y = 1 - (objHeight / texHeight); //try change the x

            var geometry = new THREE.PlaneGeometry(objWidth, objHeight, objWidth, objHeight);    
	    
            var facesNum = objHeight * objWidth * 2;
	    var facesX = objWidth * 2;
	    var facesY = objHeight * 2;
	    var facesInX = texWidth * 2;
	    var facesInY = texHeight * 2;

	    var materials = [];
	    materials.push(material);
	    materials.push(new THREE.MeshMultiMaterial({}));

	    for (var i = 0; i < facesNum; i++) {
	        if ((i % facesX <= facesInX) && (i <= texHeight * objWidth * 2)) {
	            geometry.faces[i].materialIndex = 0;
	        }
	        else {
	            geometry.faces[i].materialIndex = 1;
	        }
	    }
	    obj.geometry = geometry;
	    obj.material = new THREE.MeshFaceMaterial(materials);
	    
            editor.signals.materialChanged.dispatch(obj);
	});

thats a little complicated, but do the job for small planes.
when i tried this on big size ( 1000 * 1000 ) plane, the editor crashed.

**Comment by RoeePeleg** [comment]
forget the code. is there a way to fix the crash ?

**Comment by mrdoob** [comment]
If you really need 2,420,000 polygons, use `PlaneBufferGeometry` instead.

**Comment by RoeePeleg** [comment]
thx for the answer. 
cant use PlaneBufferGeometry , cause it not has faces attribute

**Comment by mrdoob** [comment]
Unfortunately there is no solution then.

**Comment by RoeePeleg** [comment]
ok thank you very much anyway
ill keep tryin

**Comment by RoeePeleg** [comment]
in the same issue : 
is there a way to split the plane to non-equal parts , with the segments ? 
like : 
`new THREE.PlaneGeometry(objWidth, objHeight, 2.5, 1.5);`
