### ISSUE TITLE
Lensflare Issue

### ISSUE THREAD

**Issue by aurelmm** [mrdoob/three.js#8219]
Hello.
Is it any way I could set the render order of lensflares ? I want to have them in a scene but also have 2 black bars to simulate cinema screen. The material on the black bars is set to transparent, no depth read, no depth write and no matter what render order I give them the lensflares show on top.
Is there anything I can do about this or do I have to do the black bars in post processing ? I really want to avoid this.
ps: I know that it is intended behavior but sometimes objects in the scene have to be part of an interface.

Thanks.
-Aurel

**Comment by WestLangley** [comment]
Lensflares are rendered last and do not support render order.

A workaround in your case is to have a second render pass containing the overlay scene. See [this stackoverflow post](http://stackoverflow.com/questions/12666570/how-to-change-the-zorder-of-object-with-threejs/12666937#12666937).
