### ISSUE TITLE
Should THREE.BoundingBoxHelper not consider non visible object or at least have a options to choose?

### ISSUE THREAD

**Issue by tiansijie** [mrdoob/three.js#8222]

**Comment by WestLangley** [comment]
`BoundingBoxHelper` calls `Box3.setFromObject()`.

By implication, you are requesting that `Box3.setFromObject()` have the option of ignoring invisible child objects -- and their children.

What is your use case?

**Comment by tiansijie** [comment]
I might be wrong, but I don't see an option inside `Box3.setFromObject()` to ignore invisible objects.

My case is to display a bounding box around an object, but this object has some invisible children which i don't want the bounding box to warp around these invisible children.

**Comment by WestLangley** [comment]
Would you be willing to create your own `BoundingBoxHelper2` class that has the behavior you desire for use in your application only? You can make use of the method `Object3D.traverseVisible()`.

**Comment by tiansijie** [comment]
ya, I already have that. I just thinking this might be a good option to put in the `setFromObject`

**Comment by WestLangley** [comment]
What is the behavior if `object.material.visible = false`? I just think this opens up a can of worms, which will get even more complicated when we implement visible "layers".

IMHO, the best course of action is to keep it simple, and provide the user with tools to create app-specific methods if need be.

**Comment by mrdoob** [comment]
Yeah, we have been there many times. Specially in the `Raycaster`. Tends to be better to keep things simple so there is less to understand.

**Comment by hichemfantar** [comment]
I just came across a similar case and it would have been nice to have an option to ignore invisible objects
