### ISSUE TITLE
DDS texture using loading manager

### ISSUE THREAD

**Issue by aurelmm** [mrdoob/three.js#8229]
Hello again. Sorry to flood the forum, but I am having yet another issue.
The DDS texture loader does not seem to support loading managers. So I cannot control how the scene is loaded properly and after the loading screen textures are missing and the scene only gets populated in time. Is there a workaround for this ?

Thanks

**Comment by Woor** [comment]
Have you tried adding a DDS handler?
Like:

THREE.Loader.Handlers.add( /\.dds$/i, new THREE.DDSLoader() );

Seems to work for me.

**Comment by aurelmm** [comment]
Hi.
Thank you. I am not sure I understand how the loader system works. The dds files don't show up in the console when printing the objects loaded. I did this:

THREE.Loader.Handlers.add( /\.dds$/i, new THREE.DDSLoader() );
var manager = new THREE.LoadingManager();
var ddsloader = new THREE.DDSLoader(manager);
manager.onProgress = function ( item, loaded, total ) {
console.log( item, loaded, total );		
};

Thanks again.
