### ISSUE TITLE
cube example broken?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#8233]
I was going to look at different examples for the sawtooth pattern from #8220 and found black screen and this:

![screen shot 2016-02-26 at 16 23 48](https://cloud.githubusercontent.com/assets/242577/13356406/5f99543a-dca5-11e5-834b-d7222d783a4e.png)

at http://threejs.org/examples/#webgl_geometry_cube :shit:

At the same time, network tab says [texture](http://threejs.org/examples/textures/crate.gif) was loaded ok.

**Comment by makc** [comment]
same issue in http://threejs.org/examples/#webgl_geometry_dynamic

**Comment by makc** [comment]
and http://threejs.org/examples/#webgl_geometry_convex

**Comment by makc** [comment]
once the crate texture is in cache, the errors stop early and the cube is visible:

![screen shot 2016-02-26 at 16 28 33](https://cloud.githubusercontent.com/assets/242577/13356552/1e1f2fce-dca6-11e5-91d3-2cf12a024c7e.png)

**Comment by makc** [comment]
...this is canary, osx capitan

**Comment by bhouston** [comment]
I am on Windows 10, Chrome 49.0.2623.64 beta-m (64-bit) and have no errors.  Try older version of ThreeJS and if it continues to happen it is an emerging Chrome bug????  Maybe?

**Comment by makc** [comment]
Yep, the bug is there with [r66](http://jsfiddle.net/hfj7gm6t/58/), closing...
