### ISSUE TITLE
Problem accessing items loaded by OBJLoader

### ISSUE THREAD

**Issue by doambroa** [mrdoob/three.js#8234]
I can't identify the reason, this happens to me with a mesh created in 3DS Max, but I think the problem is not related with #6682 because I tried with some really simple examples, and I also tried changing the OBJ `# object ` to `o` and the result is the same.

If OBJLoader is used to load the model, when you try to **access the meshes separately** to do something with them, for example, coloring them or setting their material to wireframe, although the DOM tree is well-generated (since r74), the whole model is modified instead of the requested mesh.

Look at some really simple examples I did trying to make it clear:

3 cubes done **mannually,** creating them by `THREE.boxGeometry()`
[No Loader](http://91.117.221.45/pruebas/manual.html)
The one you check the one that changes its material to wireframe.

Now done in 3DS Max and loaded with **OBJLoader**:
[Yes Loader](http://91.117.221.45/pruebas/cubos.html)

When objects are created manually and added to the scene, yo can correctly access them by traversing the scene and using methods like scene.`getObjectByName()` and **editing materials**.
But when OBJLoader is used, **the whole model** is marked as the submesh and there is no way to reach every object separately.

r74

**Comment by WestLangley** [comment]
See #8203

**Comment by doambroa** [comment]
Yes, I've already seen it, it's pretty confusing, OBJMTLLoader and OBJs from 3DS Max were not really good friends and when you tried to do this, it was a mess... 
But for example, If you just want to use the geometry from the OBJ with no material library (using OBJLoader only), you will have the same problem, you won't be able to pick submeshes even if you leave them with the standard material set by THREE.
 
If you have many items on your scene, why wouldn't you be able to manipulate them separately?

**Comment by WestLangley** [comment]
Look at the `OBJLoader` source code. It does not honor the `mtllib` tag. But it does return a `THREE.Group` with separate child meshes.

**Comment by doambroa** [comment]
True, but when you try to access them, it behaves like if the last concrete mesh  of the Group were the complete model. Once you access the group and modify some child at runtime, the whole model is modified (like in the examples I wrote) Is this the desired behaviour? Seriously, I don't get it, This only happens when using the loader.

If you try to modify the material color, wireframe or visible property of the last child, the whole model is modified. And if it is not the last child, nothing happens. On the other hand, if you do it creating the Mesh instances manually by code, without loaders, everything works fine.

**Comment by WestLangley** [comment]
>Seriously, I don't get it

The boxes are all sharing the same material in your `OBJLoader` example.

Try stackoverflow if you need help understanding the fundamentals.

You should also read and understand the `OBJLoader` code so you understand its capabilities and limitations.
