### ISSUE TITLE
Ninja Head model has overly compressed normal map - lots of artifacts

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8235]
So this Ninja head has lots of artifacts:

![image](https://cloud.githubusercontent.com/assets/588541/13357025/667e6f1c-dc76-11e5-9ff8-d23e841571eb.png)

The reason is not because of ThreeJS but because the Ninja head normal map is compressed at a high level with Jpeg and thus you see compression artifacts of the 8x8 DCT blocks in the normal map.  Replacing the normal map with a *.png version from the original source (assuming the original source isn't screwed up as well) will fix these brutal artifacts.

This is easily seen by setting normalScale to 0 and then all artifacts go away:

![image](https://cloud.githubusercontent.com/assets/588541/13357094/c6bd3386-dc76-11e5-9149-9072f002ac43.png)

**Comment by WestLangley** [comment]
>The reason is not because of ThreeJS but because the Ninja head normal map is compressed at a high level with Jpeg and thus you see compression artifacts of the 8x8 DCT blocks in the normal map. 

Nice find, @bhouston !

**Comment by linkedz** [comment]
you cann't scale/compress normal map like common image, cause it's not an image, but data stored in pixels. 
Try to use bicubic (simple) algorithm for scale and DDS formal for compress.

**Comment by mrdoob** [comment]
Can someone regenerate the texture? I don't have Windows...
http://developer.amd.com/tools-and-sdks/archive/legacy-cpu-gpu-tools/amd-gpu-meshmapper/#download

**Comment by ninerdelta** [comment]
I have regenerated the map using MeshMapper which generates the normal map as a *.dds, and found that saving as *.png produces a blank image. For *.jpg, the only option is 24 bit rgb. I am not sure if there other steps to solving this issue (at least using the maps generated by MeshMapper) but I am open to trying other suggestions.

**Comment by mrdoob** [comment]
@ninerdelta we can use the dds directly?

**Comment by bhouston** [comment]
> For *.jpg, the only option is 24 bit rgb. I am not sure if there other steps to solving this issue (at least using the maps generated by MeshMapper) but I am open to trying other suggestions.

All jpegs are 24 rgb.  The issue is that there are compresison artifacts in the jpeg that we currently use.

We can load up the dds in photoshop and then resave it as a jpeg.  Can you pass me the dds and jpeg you have?  I can see if they have compression artifacts or not.  I think we are one step away from fixing the issue.

**Comment by WestLangley** [comment]
@bhouston See https://gpuopen.com/archive/gamescgi/amd-gpu-meshmapper/#download and locate the sub-directory `Cabs.installFiles1.cab` to find the ninja files.

**Comment by ninerdelta** [comment]
> @ninerdelta we can use the dds directly?

> > For *.jpg, the only option is 24 bit rgb. I am not sure if there other steps to solving this issue (at least using the maps generated by MeshMapper) but I am open to trying other suggestions.
> 
> All jpegs are 24 rgb. The issue is that there are compresison artifacts in the jpeg that we currently use.
> 
> We can load up the dds in photoshop and then resave it as a jpeg. Can you pass me the dds and jpeg you have? I can see if they have compression artifacts or not. I think we are one step away from fixing the issue.

Yeah I will send it. I saved the normal map from GPU MeshMapper as *.jpg and then tested in the example and saw the same artifacts, so that's why it didn't seem like a fix. Last night I was testing with just loading the .dds into the example. I was going to finish that up tonight, while I do that I can send you the *.dds and *.jpg.

**Comment by WestLangley** [comment]
```text
//-------------------------------------
// Script file for NormalMapper
//-------------------------------------


// Set Output Names and formats
//-------------------------------------
Set Height     = 1024
Set Width      = 1024

Set NormalMapFileName = "..\textures\ninja_head_NM.dds"
Set NormalMapFormat   = A32B32G32R32F

Set DisplacementMapFileName = "..\textures\ninja_head_DM.dds"
Set DisplacementMapFormat   = L8

Set AmbientOcclusionMapFileName = "..\textures\ninja_head_AO.dds"
Set AmbientOcclusionMapFormat   = L16



// Set Mesh Data
//-------------------------------------
Set LowResMesh  = "..\mesh\ninjaHead_Low.obj"
Set HighResMesh  = "..\mesh\ninjaHead_High.obj"


// Set Generation Options
//-------------------------------------
Set NormalSelectionRule      = 1
Set MaxRayCastDistance       = 0.000000
Set MaxAngle                 = 180.000000
Set Epsilon                  = 0.000100
Set FavorLowResNormal        = True

Set SuperSamplingQuality     = 1
Set AddTexelCorner           = False

Set ExpandTexels                   = 5
Set InterpolateAcrossEmptyRegions  = True

Set NormalInWorldSpace       = False
Set BentNormal               = False
Set ApplyDetailMap = False

Set GenerateDisplacementMap = True
Set DisplacementMapScale    = 0.000000
Set DisplacementMapBias     = 0.000000

Set GenerateAmbientOcclusionMap   = True
Set OcclusionSamplingRate     = 300
Set MaxOcclusionDistance      = 0.000000
Set UseGPU                    = True


// Trigger Computation
//-------------------------------------
Compute
```

The low-poly and high-poly .obj model can be found the data set, so perhaps someone can recreate the maps if all else fails.

**Comment by ninerdelta** [comment]
To recap what I have done...

* 1 Downloaded AMD GPU MeshMapper, and ran the `ninja_script.nms` which generates the ambient occlusion, displacement, and normal maps from the low and high poly *.obj ninja head models

* 2 Used DDS Utilities from NVidia to compress the maps to dxt1 and also flip them (see 2a)

    * 2a In `examples/webgl_material_displacementmap.html` I replaced the maps in *.jpg format with *.dds maps (compressed to dxt1). DDS textures have to be flipped otherwise they render upside down, this has been noted in other tickets and isn't that surprising. Visually, the result of this test was much worse than what you have right now. I can post some screen shots if you want to see.

* 3 In MeshMapper, opened the newly generated, *.dds maps from step 1 (these are not compressed to dxt, see the script posted for the format), and did "save as" to *.jpg

    * 3a In `examples/webgl_material_displacementmap.html` I replaced the current *.jpg maps (as is from the repo) with the maps from step 3. The result of this looked visually no different than the original at the beginning of this issue.

[Here is a link](https://1drv.ms/f/s!ArAmdMiHmLO65XJAu_kPNU3J7WsC) to the *.dds maps generated in step 1 using the script @WestLangley posted (it is included with the MeshMapper download for reference).
