### ISSUE TITLE
EdgesHelper / WireframeHelper rotation out of sync when nested

### ISSUE THREAD

**Issue by Tolmark12** [mrdoob/three.js#8236]
When nesting an ```EdgesHelper``` item and a ```mesh``` item within an ```Object3D``` parent item, and then applying a rotation to the ```Object3D```, the ```EdgesHelper``` item rotates exactly twice as fast as the ```mesh``` item. I've confirmed that this also occurs with the wireframe helper.

Example: 
http://jsfiddle.net/tolmark12/b0zz3Lu8/5/

**Comment by WestLangley** [comment]
You need to add the helper to the scene directly.

http://jsfiddle.net/b0zz3Lu8/6/
