### ISSUE TITLE
Texture memory leak on iOS with Ionic framework 1.2

### ISSUE THREAD

**Issue by designzoo-peter** [mrdoob/three.js#8249]
Whenever I load a large texture on iOS and try to unload it, XCode instruments reports that the memory is not released.

![screen shot 2016-02-29 at 16 19 12](https://cloud.githubusercontent.com/assets/2188024/13400698/e2f78dbc-df00-11e5-815f-426ad3535e87.png)

I load the texture when entering a view and unload it whenever I leave. When I enter the and exit multiple times the app crashes due to running out of memory. Leaving the device for a period of time and switching to different views does not alleviate the issue.

I have tested this on; iPhone 6 (9.1), iPhone 6+ (8.0), and iPhone 6S (9.2).

I have tried every combination I can think of to try to solve this. I can confirm the init and destroyScene functions are being called equally and on exit/entrance. The relevant parts of my code are:

```javascript
function init() 
  {
    container = document.getElementById( 'container' );
    toggleControl = document.querySelector( '#controllertype' );

    camera = new THREE.PerspectiveCamera( 60, window.innerWidth / window.innerHeight, 1, 1100 );
    camera.target = new THREE.Vector3( 0, 0, 0 );

    scene = new THREE.Scene();

    geometry = new THREE.SphereGeometry( 500, 60, 40 );
    geometry.scale( -1, 1, 1 );

    texture = new THREE.TextureLoader().load( "img/panorama/ni/"+selectedPano+"/"+selectedPano+".jpg" );

    material = new THREE.MeshBasicMaterial( {
      map: texture
    } );

    mesh = new THREE.Mesh( geometry, material );
    
    scene.add( mesh );

    //note that kitkat does not support webview webGL since the chromium version is locked
    //cssrenderer might help this
    renderer = new THREE.WebGLRenderer();
    renderer.setPixelRatio( window.devicePixelRatio );
    renderer.setSize( window.innerWidth, window.innerHeight );
    container.appendChild( renderer.domElement );
  }
```

```javascript
  function destroyScene()
  {
    scene.remove(mesh);
    geometry.dispose();
    material.dispose();
    material.map.dispose();
    texture.dispose();

    scene = undefined;
    geometry = undefined;
    material = undefined;
    texture = undefined;
  }
```

**Comment by bhouston** [comment]
You should delete the dom element as that will release the canvas and WebGL context.
