### ISSUE TITLE
NRRD Loader

### ISSUE THREAD

**Issue by stity** [mrdoob/three.js#8254]
@mrdoob I saw that three.js does not have yet a NRRD loader.
I am willing to create one but I face an issue : 
There is no geometry in NRRD, it is just a volume of values (basically it is just an typed array).
So here is my question : What should the loader returns ?
I see that the existing loaders return a geometry object but the only geometry I can think of is a set a plans and this would only involves the NRRD data in the texture.

Here is an XTK demo that uses NRRD files (turn on volume rendering)
http://lessons.goxtk.com/10/
It is close to the demo you wrote a few years ago : 
https://dl.dropboxusercontent.com/u/7508542/three.js/body/index.html
except that, instead of loading a set of images, all the slices are in a single file.

Am I missing an existing class in three.js that would allow that ? How should we tackle this issue ?
Thanks

**Comment by mrdoob** [comment]
Hmm, so NRRD basically has images inside? Maybe the loader could just return the images and the example would show ho to place them in 3D planes?

How is the volume mesh being generated? Marching cubes?

**Comment by stity** [comment]
In the NRRD file you have two parts : a header with information about the
type and size of the data and then the data.
The data are the values of all the voxels in a parallelepiped whose size is
given in a header.
I believe we can return a typed array with all the values and a header
object.
From this volume of data, the user can easily extract slices in any of the
three perpendicular directions.
(If you rotate the xtk demo after turning on volume rendering, you will see
that the direction of the plans is changing according to the camera)

Marching cube can be used to extract a mesh. But I work in the medical
field and most of the time we just want to display the three perpendicular
slices (like in the xtk demo when you turn off volume rendering)

**Comment by mrdoob** [comment]
Ah. I understand now... Maybe we can create a `THREE.Volume` object that holds the data and has a bunch of methods for easy access? Like... `.getDataXY( 0.5 )`

**Comment by stity** [comment]
OK I can do that.

Here is the first draft of `TREE.Volume` API : 
Attributes : 
- xLength (Integer)
- yLength (Integer)
- zLength (Integer)
- spacing (Array (3) : use to match the coordinate system, it corresponds to the size a voxel)
- offset (Array (3) : position of the first voxel)
- rotationMatrix
- data (typed array)

Methods :
- access(integer x, integer y, integer z) : get the data from the voxel at coordinate (x,y,z)
- reverseAccess(integer index) : return the corresponding [x,y,z]
- extractPlan({'x','y','z'} axis, integer index) : returns the typed array corresponding to a slice perpendicular to the given axis at the given index
- map(function) map a given function to every value of this.data

Let me know if you see anything else, especially anything that can help displaying the content later

**Comment by mrdoob** [comment]
Looks go to me!

**Comment by stity** [comment]
@mrdoob So far, I have the `NRRDLoader` working and returning a `THREE.Volume` object.
I think that I should write another object to handle a plan extracted from a volume.
See the attached image for the result and to have an idea of the plans I mentioned : 
![perpendicular slices](https://cloud.githubusercontent.com/assets/11036145/13516362/739b2666-e187-11e5-91cc-d6273fb160b4.png)

Creating a `THREE.VolumeSlice` object would allow the user to handle the creation of the slices easilier.
Here is an example of all the code necessary to create one slice right now : 
``` javascript
                    geometry = new THREE.PlaneGeometry( volume.yLength, volume.zLength );
                    canvas = volume.extractPlan('x',Math.floor(volume.xLength/2));
                    canvasMap = new THREE.Texture(canvas);
                    canvasMap.wrapS = canvasMap.wrapT = THREE.RepeatWrapping; 
                    canvasMap.repeat.set( 1, 1 );
                    material = new THREE.MeshBasicMaterial( { map: canvasMap, side: THREE.DoubleSide } );
                    plane = new THREE.Mesh( geometry, material );
                    plane.material.map.needsUpdate = true;
                    rotateAroundWorldAxis(plane, new THREE.Vector3(0,1,0), Math.PI/2);
                    rotateAroundWorldAxis(plane, new THREE.Vector3(1,0,0), Math.PI/2);
                    document.body.appendChild(canvas);
                    scene.add( plane );
```
Here is an example of what could be an use of `THREE.VolumeSlice` : 
``` javascript
var slice = volume.extractPlan('x',Math.floor(volume.xLength/2);
scene.add(slice.mesh);
```

Moreover this would allow the user to do this kind of update : 
```javascript 
slice.setIndex(newIndex);
slice.repaint();
```

Instead of creating a new canvas, and refreshing the texture and updating the position.

So my question is : Where should I put this new object ? 
So far the `THREE.Volume` is in `src/core` but I don't know if it is the right place either.

**Comment by mrdoob** [comment]
`THREE.VolumeSlice` sounds good!

> So far the THREE.Volume is in src/core but I don't know if it is the right place either.

I would put it on `examples/js/Volume.js` by now.

**Comment by stity** [comment]
See https://github.com/mrdoob/three.js/pull/8344
