### ISSUE TITLE
Font loading isn't robust and crashes with some fonts

### ISSUE THREAD

**Issue by DelvarWorld** [mrdoob/three.js#8262]
I'm not sure what the full history here is with typeface.js (which seems to be a dead project?), but there is some suspicious manipulation going on when a font is loaded:  on [this line](https://github.com/mrdoob/three.js/blob/master/src/loaders/FontLoader.js#L20):

```js
onLoad( new THREE.Font( JSON.parse( text.substring( 65, text.length - 2 ) ) ) );
```

It was introduced in this change: https://github.com/mrdoob/three.js/commit/fffe45c78a040ef3a5e12d8391c591bfaaa6bae1#diff-7aee17098254e4ee4f70bf5c94fe11e4

This was introduced for me because a build script is injecting `"use strict"` at the top of my JS files. While this is easy to fix in the build script, there's no reason why this change should crash the font loader.

The ideal solution here would be to have font files actually be JSON. I'm unsure about the history of typeface.js so it seems that some (all?) (legacy?) font files are js scripts when they should be JSON to load like other assets.

**Comment by mrdoob** [comment]
> The ideal solution here would be to have font files actually be JSON. I'm unsure about the history of typeface.js so it seems that some (all?) (legacy?) font files are js scripts when they should be JSON to load like other assets.

I actually did the json change at some point, but reverted to keep backwards compatibility.

https://github.com/mrdoob/three.js/commit/fffe45c78a040ef3a5e12d8391c591bfaaa6bae1

Now I'm thinking that we could support both, if the file has a .json extension then we run JSON.parse directly.

We should also add a `.json`/`.js` checkbox to @gero3's http://gero3.github.io/facetype.js/.

Would you want to give it a go?

**Comment by DelvarWorld** [comment]
:) https://github.com/gero3/facetype.js/pull/8

Just a close cousin of https://github.com/gero3/facetype.js/pull/7

**Comment by gero3** [comment]
Merged into the site.

**Comment by mrdoob** [comment]
Done!
