### ISSUE TITLE
Object #<WebGLRenderingContext> has no method 'getShaderPrecisionFormat' on Android4

### ISSUE THREAD

**Issue by takahirox** [mrdoob/three.js#8264]
According to this article,

http://qiita.com/tonkotsuboy_com/items/cdffcdd7bdccac371292

Android 4 devices WebGL doesn't seem to support getShaderPrecisionFormat
and runs into "no getShaderPrecisionFormat" error.

    Uncaught TypeError: Object #<WebGLRenderingContext> has no method 'getShaderPrecisionFormat'

I don't have Android 4. Can anyone check if that's true?

http://threejs.org/examples/#webgl_animation_cloth

And, if I'm right, this issue seemed to be solved once by #3000 before
but the changes looks removed, why?
Can we put it back if it was removed by misoperation or something?

**Comment by makc** [comment]
> I don't have Android 4. Can anyone check if that's true?

tried a couple of "physical" android 4.4 devices on browserstack, most of them just failed to create context, but this one seems filne with http://threejs.org/examples/#webgl_animation_cloth
![screen shot 2016-03-02 at 20 39 34](https://cloud.githubusercontent.com/assets/242577/13472881/1a3ab062-e0b7-11e5-8aa6-9566f5b19044.png)

**Comment by takahirox** [comment]
Thanks for the trial.

I read the article again.
It mentions that his Android 4.1.2 faces the error.
And some Android 4.4 updated from 4.03 runs into the same error.

It's supposed that not all Android 4 but some of them (depends on version? or device?)
could face the error.

**Comment by tonkotsuboy** [comment]
In Android 4.1.2

```
var canvas = document.createElement( 'canvas' ); 
!!canvas.getContext( 'webgl' ); // false
!!canvas.getContext( 'experimental-webgl' ); // true
```

I think that we need no support for `experimental-webgl`.

**Comment by takahirox** [comment]
So, I think to recover #3000 is the easiest way to solve
unless it's been removed because of some special reasons.

What do you guys think?
If it's fine I'll make PR.

**Comment by mrdoob** [comment]
@takahirox sounds good to me!

**Comment by takahirox** [comment]
Thanks! I'll send PR after I confirm this change solves the issue on Android just in case.

BTW the code seems to have been removed without any special reasons.

c261b9b8ada30414a3220730aedba3942e124434

So I think to recover it won't cause any problems.
