### ISSUE TITLE
addGroup does not work in wireframe mode?

### ISSUE THREAD

**Issue by qdnguyen** [mrdoob/three.js#8267]
Hi,
I create a mesh with bufferGeometry and MultiMaterial of MeshBasicMaterial array, then i use addGroup to see some triangle sets of my Mesh.

When i set wireframe = false, i can see my mesh like this

![sans titre1](https://cloud.githubusercontent.com/assets/3224540/13457372/24823a76-e068-11e5-8f9a-57ce2204dfd8.png)

but if i set wireframe = true, it does not work

![sans titre](https://cloud.githubusercontent.com/assets/3224540/13457379/31555e4a-e068-11e5-90fa-0e58dc80c9ce.png)

**Comment by mrdoob** [comment]
Yeah... I didn't figured out how to do that yet.

**Comment by qdnguyen** [comment]
i found error, it come from my side, i copy position and normals in the same buffer then send them to buffergeometry.

![wireframe](https://cloud.githubusercontent.com/assets/3224540/13919967/b2abd7e6-ef70-11e5-857a-d2a5b6900299.png)
