### ISSUE TITLE
CylinderBufferGeometry: Alternative implementation of  end-caps

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#8270]
I've created this issue so @WestLangley 's suggestion in #8239 does not get lost.

> Well, perhaps the end-caps should have a different material index, and UVs to match CircleGeometry? Just a thought...

Well then? Is there really a need to change the implementation? What about backwards compatibility? If users rely on the current UV coordinates, a change in this area could break things, right?

**Comment by WestLangley** [comment]
Improvements are allowed.

**Comment by abelnation** [comment]
I'll take a look at this, with the goal being to have cylinder end caps match the behavior of CircleGeometry
