### ISSUE TITLE
Update Model

### ISSUE THREAD

**Issue by alexbogd** [mrdoob/three.js#8271]
Hey guys,

In my model I am setting the camera to a new position with a click on a button.

When I click, the values change, but not the scene. 
If I click in to the scene again it updates and the camera jumps to the new location.

Any suggenstions on how I can solve this problem?

I already tried: 
- renderer.render(scene,camera) -> in my render loop
- camera.needsUpdate

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
