### ISSUE TITLE
Suggestion: Validate GLSL with Reference Compiler

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#8277]
I'm editing my shader files with Atom and a package called [linter-glsl](https://atom.io/packages/linter-glsl) now. The mentioned package internally uses the [OpenGL / OpenGL ES Reference Compiler](https://www.khronos.org/opengles/sdk/tools/Reference-Compiler/) to validate the shader code and check its portability.

You can also use this feature without Atom. The [glslang project](https://github.com/KhronosGroup/glslang) provides the standalone wrapper `glslangValidator` that can be used as a handy shader validation CLI tool.

Now i wonder if we could use this tool in our tests. A typical use case could look like this.

Let's say i want to refactor several shader chunks. To verify that all vertex and fragment shaders are still working, i would run a special task of our build that creates all shaders from our shader lib and validates them with `glslangValidator`. If the validation is correct, the chances are very high that a WebGL implementation accepts the shader without errors.

Well, it's just an idea and maybe something for a future build. But i think an integration of `glslangValidator` in a node.js build system like grunt or gulp should not be too difficult...

**Comment by zz85** [comment]
I wanted to work on a glsl linter and minifier myself too but http://evanw.github.io/glslx/ is one tool which seems to be able to do this.
