### ISSUE TITLE
SVGRenderer with OrbitControls sometimes hangs

### ISSUE THREAD

**Issue by moynob** [mrdoob/three.js#8280]
If I use the mouse to rotate the camera for a long time, after a while the camera will hang.
[https://jsfiddle.net/cqhwc11c/1/](https://jsfiddle.net/cqhwc11c/1/)

In an older version, SVGRenderer with OrbitControls will never hang.
[https://jsfiddle.net/cqhwc11c/](https://jsfiddle.net/cqhwc11c/)

**Comment by Mugen87** [comment]
I've tested this today with Chrome and Firefox but i'm unable to reproduce. 

@alexgarces @moynob Do you still experience the issue on your machines? These fiddles are jusing the latest version of `three.js`.

https://jsfiddle.net/cqhwc11c/1/
https://jsfiddle.net/alexgrcs/5dg2n3zd/

**Comment by mrdoob** [comment]
I can no longer reproduce... 🎉
