### ISSUE TITLE
OBJLoader does not recognize a "line element option"

### ISSUE THREAD

**Issue by birgersp** [mrdoob/three.js#8283]
I'm not sure if "element option" is the correct term for this, but what I mean is a line in an .obj file as for instance:

`l 1164 1469`

This text specifies that the mesh contains a line between vertex 1164 and 1469.
OBJLoader throws "Unexpected line: l 1164 1469" on such occasion.

From what my teams modeler tells me, the "l" element option is a pretty common thing to use. If that's the case, perhaps the OBJLoader should recognize it?

[Here](https://www.opengl.org/discussion_boards/showthread.php/171130-Storing-Lines-in-Obj-File) is and example of someone using the line element option.

**Comment by mrdoob** [comment]
Could you share one of those obj files?

**Comment by birgersp** [comment]
Here's an example of such a model
[Blender .obj export](http://pastebin.com/raw/B4BHStaE)

**Comment by jonnenauha** [comment]
@birgersp This will be supported/fixed once my PR #8443 is merged.

**Comment by hamogu** [comment]
May I ask why this issue was closed? Even after merging #8443 there is nothing the regex of the OBJ loader to parse lines that start with "l", like `l 1164 1469`. 
I suggest to reopen this issue.

**Comment by hamogu** [comment]
I got fooled. Lines are defined, but unlike other structures not in the regexp at the top of the file, but hardcoded later on. I'll have to go back to my OBJ file and continue to search why it does not load properly.

**Comment by jonnenauha** [comment]
I tried it with just one file that was provided. Maybe it does not handle just defining two vertices correcrly (?!), the test file had a long list of vertices in just a single `l` line. If your file does not load I can take a look if you provide the file.
