### ISSUE TITLE
Use PannerNode instead of AudioContext Panner to allow for many positional audio sources

### ISSUE THREAD

**Issue by meta-meta** [mrdoob/three.js#8287]
The current PositionalAudio implementation uses AudioContext.createPanner(). This limits the number of audio sources to whatever the max hardware contexts is. It's encouraged to have only one AudioContext on the page at a time.

**Comment by mrdoob** [comment]
I don't think I'm following you...

**Comment by meta-meta** [comment]
Whoops nevermind, I misunderstood the code.
