### ISSUE TITLE
Script for converting multiple obj files to js files

### ISSUE THREAD

**Issue by BretMishler** [mrdoob/three.js#8293]
As I understand it, convert_obj_three.py seems to only convert one item at a time.

Does there exist a method, flag. or other included script (that I can't find) that will take all obj files in the folder of execution and convert them to the JSON format necessary for three.js?

If not, would it be helpful if I made one? I'm thinking just an '-a' flag that will take all obj's in the directory and convert them to the js files needed. I have 100's of objects, so this would be useful for me; especially because the graphic editors I'm using do not convert very well, if at all.

**Comment by mrdoob** [comment]
`convert_obj_three.py` is kind of deprecated though...

**Comment by positivecharge8** [comment]
What's the alternative? And why is it deprecated?

**Comment by donmccurdy** [comment]
Closing this issue as `convert_obj_three.py` no longer exists. There is a [node.js script](https://github.com/mrdoob/three.js/tree/dev/utils/converters) that fills the same role. See https://github.com/mrdoob/three.js/issues/12903 for some background on why some exporters and converters are deprecated.
