### ISSUE TITLE
WebGLRenderer.resetGLState does not reset all the necessary state

### ISSUE THREAD

**Issue by jkieboom** [mrdoob/three.js#8294]
I'm trying to integrate threejs with another rendering engine, and to do so properly I need to reset the GL state when switching between threejs and the other engine. I noticed that not all the state is being reset by the call to `renderer.resetGLState()`. Most notably (although there might be others):

- `currentTextureSlot`
- `currentBoundTextures`

Would it be possible to add these (and potential other missing states) to `state.reset` ?

**Comment by mrdoob** [comment]
Sounds good. Do you want to do a PR with the improvement?

**Comment by makc** [comment]
@jkieboom 3js can not really 'restore' gl state, because it has no way of knowing what it was. the resetGLState is to reset gl state before 3js render, not after it. I had to manually do thing after 3js exits, too.

**Comment by jkieboom** [comment]
@makc: indeed. What I meant was to restore/reset the internal threejs cached state, which we do just before calling into threejs. We then do the same resetting on our side, just after coming back from threejs and before we do our own rendering.

**Comment by makc** [comment]
@jkieboom,
> just before calling into threejs

sorry I thought you mean the other way around when you wrote
> when switching between threejs and the other engine

in my case this
```
	this.renderer3d.resetGLState ();
	this.renderer3d.setRenderTarget (null);
```

was all I had to do.

**Comment by jkieboom** [comment]
PR for resetting the texture state: https://github.com/mrdoob/three.js/pull/8350

There is probably other state that needs to be reset to make this complete? Also, should `resetGLState` be documented?
