### ISSUE TITLE
ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by mrdoob** [mrdoob/three.js#8304]
https://github.com/blog/2111-issue-and-pull-request-templates

I don't think we need a `PULL_REQUEST_TEMPLATE` yet, but a `ISSUE_TEMPLATE` should be able to help with the issue of people asking questions or looking for help here.

Anyone would like to give it a go? I guess `CONTRIBUTING` could also benefit of some clean up.

**Comment by gero3** [comment]
>If you're worried about the added clutter in the root directory of your project, we also added support for a .github/ folder. You can put CONTRIBUTING.md, ISSUE_TEMPLATE.md, and PULL_REQUEST_TEMPLATE.md files in .github/ and everything will work as expected.

Maybe not a bad idea to also add all those files in a seperate github folder

**Comment by mrdoob** [comment]
Indeed!

**Comment by Mugen87** [comment]
I really like the new `ISSUE_TEMPLATE` :+1: . That will give the issues a more standardised appearance...

**Comment by mrdoob** [comment]
Yup! Thanks @gero3!
