### ISSUE TITLE
A gap in Three.ShaderLib[ 'equirect' ] wrapping

### ISSUE THREAD

**Issue by pchen66** [mrdoob/three.js#8305]
A thin gap is flickering between the wrapping equirectangular image. Reproducible in r74 and r75dev with Chrome 48.0.2564, Firefox 44.0.2, and Safari 9.0.3 on Mac Book Pro 2012 as well as iOS Safari, Chrome and Chrome for Android . Not sure it's a bug or precision issue. 
<img width="576" alt="screen shot 2016-03-05 at 11 42 13" src="https://cloud.githubusercontent.com/assets/2421225/13552967/196d4d9e-e32c-11e5-8317-f95a3db72eb0.png">

To reproduce: 
(1) go to [webgl_materials_envmaps example](http://threejs.org/examples/webgl_materials_envmaps)
(2) click on Equirectangular
(3) see the grey thin line

Here's another [Jsfiddle](http://jsfiddle.net/hw9rcLL8/14/) example

**Comment by mrdoob** [comment]
Yeah, that's a known issue. Unfortunately there isn't much that can be done about it. That line happens when the UV jumps from 1.0 to 0.0. The GPU samples the whole texture and that's the resulting pixel/s.

**Comment by MasterJames** [comment]
Maybe an option to copy one pixel over, ontop of a seam is a possible workaround?

**Comment by mrdoob** [comment]
How would you do that?
