### ISSUE TITLE
TrackballControls: Zoom to cursor

### ISSUE THREAD

**Issue by 50Wliu** [mrdoob/three.js#8307]
At least for `TrackballControls`, I think that users would expect that when zooming, the focus would be set to the cursor location and not the center of the viewarea.  This allows for more fine-grained zooming, and the previous functionality is easily obtained by simply placing your cursor near the center of the screen.

I've read over #2255 and #4864 already, which are the only related issues that I could find.  #2255 was a bit ambitious in asking for a separate controls object to be created, and #4864 seems to just have asked for help instead of asking for a feature request :smile:.

**Comment by WestLangley** [comment]
>I think that users would expect that when zooming, the focus would be set to the cursor location and not the center of the view area.

This is why `TrackballControls` is part of the examples, and not the library. You are free to modify it to your liking.

In your proposal, what happens to `controls.target` as soon as you start zooming? What is `target` set to?

**Comment by MasterJames** [comment]
One might like to lock the target to a distance always front and center of course. Then you can still rotate/translate around things but one could also pivot around the camera location. Putting the pivot behind the camera is a case I don't see being used as much or logical with a target but locking the pivot to a distance from the camera might be. 
Mainly i'vé noted that can get all messed up and then to sort it out more awkward like your to close to the pivot/target, so zooming could just translate target distance maybe.

**Comment by 50Wliu** [comment]
Looks like my previous comment didn't save, whoops.

I don't have much experience with `controls.target`, and so this is probably completely wrong, but couldn't it just be set to where the mouse cursor is when zooming starts?

**Comment by WestLangley** [comment]
>I don't have much experience with controls.target, and so this is probably completely wrong, but couldn't it just be set to where the mouse cursor is when zooming starts?

Spend some time understanding how `TrackballControls` works, and then see if you can rephrase your suggestion.

**Comment by MrMaksymov** [comment]
Here is my example for that:
https://github.com/MrMaksymov/three/blob/master/OrbitControls.js

**Comment by ilCosmico** [comment]
> I don't have much experience with controls.target, and so this is probably completely wrong, but couldn't it just be set to where the mouse cursor is when zooming starts?

Hi @WestLangley, I think @50Wliu means something like this: http://www.tectractys.com/market_globe.html

@MrMaksymov I'm not able to use your script, I get the following error:
![image](https://cloud.githubusercontent.com/assets/8678145/16484065/9aa57f08-3eb7-11e6-85c6-48b83ae81562.png)
Have you some ready-to-use html example, please?

**Comment by ilCosmico** [comment]
@MrMaksymov never mind my last comment, I found an example [here](https://github.com/mrdoob/three.js/blob/master/examples/misc_controls_orbit.html) and it works like a charm.

**Comment by Mugen87** [comment]
"Zoom To Cursor" is a very application specific use case. If we change/extend the zoom behavior for `TrackballControls`, we also have to do this for other controls like `OrbitControls` for consistency reasons. Closing since we want to focus the controls on the most important logic.

**Comment by MattFerraro** [comment]
Now that `OrbitControls` _does_ support `zoomToCursor`, would the team be open to incorporating `zoomToCursor` in `TrackballControls`?

**Comment by mrdoob** [comment]
Yeah! Would you like to give it a go?
