### ISSUE TITLE
Problem on shaders with r74 on nw.js current stable version (0.12.3)

### ISSUE THREAD

**Issue by slavielle** [mrdoob/three.js#8310]
I'm working with three.js on NW.js, and I noticed shaders seem not working correctly specifically on the r74 release :

I'm using PointLight lights and meshes with phong material on my scene: I had my meshes nicely shaded so far (prior to r74).

So I made several browsers vs three.js versions tests to run my project, and here's the results :

NW.js (0.12.3) + three.js (r73) : Shaders work
NW.js (0.12.3) + three.js (r74) : Shaders don't work
FireFox (44.0.2) + three.js (r73) : Shaders work
FireFox (44.0.2) + three.js (r74) : Shaders work
Chrome (48.0.2564.116 m) + three.js (r73) : Shaders work
Chrome (48.0.2564.116 m) + three.js (r74) : Shaders work

So the problem seems to be only with the three.js r74 and the latest NW.js stable version (0.12.3).

**Comment by bhouston** [comment]
One needs more information.  Do you have any log output from ThreeJS about why the shaders failed to compile?  That would really nail down the issue.

**Comment by slavielle** [comment]
Sorry, nothing relevant in the javascript console. I would have mentioned it if so.

**Comment by mrdoob** [comment]
Unfortunately we can't do much if there are no errors in the console.

**Comment by slavielle** [comment]
Ok it's not a critical issue for me, let's see if one have the problem too. If I can figure out something else about the problem, I'll post here.

**Comment by mrdoob** [comment]
Closing for now...
