### ISSUE TITLE
three.clock uses window.performance and does not work on IOS 8

### ISSUE THREAD

**Issue by aurelmm** [mrdoob/three.js#8311]
Hello. I struggled a bit to figure out why my project did not work on certain IOS devices until I managed to do some debugging on a mac. Is it necessary to use this instead of date-based clock that I ended up using instead ?

"The Navigation Timing API has been disabled only on iOS due to performance issues." [1]
https://github.com/addyosmani/timing.js/issues/9

**Comment by mrdoob** [comment]
> Is it necessary to use this instead of date-based clock that I ended up using instead ?

It is not. You can use whatever works for your project. Hopefully Apple will fix this on iOS 8 at some point.

**Comment by cindyloo** [comment]
ah, having same problem

**Comment by mrdoob** [comment]
Fixed in `dev`.
