### ISSUE TITLE
Scaling mesh changes UV coordinates (for specularmap)

### ISSUE THREAD

**Issue by Kjos** [mrdoob/three.js#8312]
Hi,
I'm not sure if this is a feature or a bug, but if I scale a model (downloaded from clara.io exported to JSON) using the latest Three.js, I notice the UV coordinates of the specular map changing.
This is using the standard phong shader.
Kind regards,
Kjos

**Comment by Kjos** [comment]
I found out that changing the bumpScale according to the mesh scale change, fixes the problem.

**Comment by mrdoob** [comment]
Can you provide an example?

**Comment by Kjos** [comment]
1) Download this model (I figure the other models use the same export settings, but I tried with this one): https://clara.io/view/6397c255-2fc4-43c1-969c-59ec58504fe5
- You can use sharklasers throwaway as emailaddress (even though it doesn't verify) (I'm sorry but I don't think I'm at liberty to distribute) (also NSFW model - she's naked)
- Download as new Three.js JSON format, new conversion type.

```
		var modelMesh; // global var
		
		function init() {
			// 
			// Model loader
			//
			var loader = new THREE.ObjectLoader();

			// load model resource
			loader.load(
				// resource URL
				'models/hot-chick.json',
				// Function when resource is loaded
				function ( obj ) {
					var scale = 1.0;
					
					obj.position.set( -scale / 4.0, -scale, 0 );
					
					// var sound1 = new THREE.PositionalAudio( listener );
					// sound1.load( 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Example.ogg' );
					// sound1.setRefDistance( 20 );
					// sound1.autoplay = true;
					// sound1.setLoop(true);
					//object.add( sound1 );
					
					obj.scale.x = scale;
					obj.scale.y = scale;
					obj.scale.z = scale;
					scene.add( obj );
					modelMesh = obj;
				}
			);
		}
		
		var scale = 0.1;
		function testScale() { // call this in animate
			if (modelMesh) {
				scale += 0.03;
				scale %= 9.0;
				modelMesh.position.set( -scale / 4.0, -scale * 1.25, 0 );
				modelMesh.scale.x = scale;
				modelMesh.scale.y = scale;
				modelMesh.scale.z = scale;
			}
		}
```

Result: the bumpmap is changing even though the model stays the same otherwise. Model is otherwise displaying correctly.

**Comment by makc** [comment]
naked? she has boots on )

also, when you simply zoom in on it at clara.io, bump map goes really bad.

**Comment by mrdoob** [comment]
@Kjos There are more chances that we'll take a look at this if you can provide an example (maybe jsfiddle) where the issue is directly apparent (instead of having to follow a series of instructions)?

**Comment by makc** [comment]
@mrdoob I think it's pretty simple to reproduce, just go to http://threejs.org/examples/webgl_materials_bumpmap.html and paste following in the console as a single line:
```
mesh.scale.multiplyScalar(.2);camera.position.multiplyScalar(.2)
```

**Comment by mrdoob** [comment]
I see... Thanks @makc!
/ping @WestLangley

**Comment by WestLangley** [comment]
```javascript
mesh.scale.multiplyScalar( .2 ); camera.position.multiplyScalar( .2 ); mesh.material.bumpScale *= 0.2;
```

This has nothing to do with UV coordinates. When you scale a mesh, the normals remain unit-length. So `bumpScale` must be scaled accordingly. This is to be expected. I do not see a problem here.

**Comment by makc** [comment]
that's what @Kjos said,
> I found out that changing the bumpScale according to the mesh scale change, fixes the problem.
