### ISSUE TITLE
SkinnedMesh Export and Loading via ObjectLoader

### ISSUE THREAD

**Issue by insominx** [mrdoob/three.js#8317]
##### Description of the problem 
I have so far been unable to successfully animate the marine character from my original example (webgl_animation_skinning_blending) using the new exporter.  Is this still in transition?  It looks like all of the examples that use SkinnedMesh still rely on JsonLoader rather than ObjectLoader which is all the newish exporter produces (right?).
 
I'm mostly looking for verification here in case I'm given time to do something to fix it.  Thanks!

##### Three.js version

- [x] Dev
- [ ] r74
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Yeah, I don't think anyone is working on making the Blender exporter output files using the new format 😕

**Comment by insominx** [comment]
Ok, I've made some progress in tracking this down.  There are a couple of issues:

1) The new exporter doesn't transform the vertices to flip YZ axes like the old one used to.  Instead it relies on a matrix to patch things up.  It generally looks like this: ' "matrix":[-1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1], '

2) Because bones are no longer bound to an identity matrix on load they will calculate the wrong bone inverses which in turn result in the wrong offset matrices because it doesn't know about the matrix mentioned in (1).  This can be worked around by doing the following after load:

skinnedMesh.updateMatrixWorld();
skinnedMesh.skeleton.calculateInverses();

Unfortunately this solution seems to undo the YZ flip so meshes that used to stand upright now lay on their side.  On the brighter side, the mesh is no longer deformed and animates correctly (albeit sideways).

Here's a SkinnedMesh (with bone render) by default:

![image](https://cloud.githubusercontent.com/assets/180210/13650435/8604e818-e5f7-11e5-8547-e9907a76ef72.png)

Here's the same mesh with a single keyframe animation applied:

![image](https://cloud.githubusercontent.com/assets/180210/13650485/bf444704-e5f7-11e5-882b-31d8ddd0c146.png)

This is how the animation is supposed to look (from blender):

![image](https://cloud.githubusercontent.com/assets/180210/13650506/da2fa2e8-e5f7-11e5-85d4-063e8c9b0c60.png)

If I apply the fix mentioned in (2), I get this (with no animation):

![image](https://cloud.githubusercontent.com/assets/180210/13650544/0ac8bc1e-e5f8-11e5-906e-d5c842221948.png)

The nice thing here is that the bones now appear to be aligned with the mesh (as they are in blender).  Unfortunately, it is now sideways.

Finally, here it is with the fix and the animation:

![image](https://cloud.githubusercontent.com/assets/180210/13650584/3eaba640-e5f8-11e5-849e-3e40037c877e.png)

It's no longer distorted and basically looks correct other than being sideways rather than upright.

Is there a good reason that a matrix was used rather than transforming the vertices at export?
Should @phfatmonkey and I work on changing the exporter to make this work?

**Comment by mrdoob** [comment]
Have you tried using GitHub's "Blame" on that file to see who wrote that code?

**Comment by insominx** [comment]
Fixed by #8412
