### ISSUE TITLE
Lens Flares and Firefox 45

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#8321]
They still work (in both r74 and r75dev), but the console is bloated with error messages like this one:

Error: WebGL: CopyTexImage2D: This operation requires zeroing texture data. This is slow. three.min.js:744:407

**Comment by titansoftime** [comment]
I have a similar error in chrome.

**Comment by Mugen87** [comment]
@RemusMar So you are getting the mentioned messages with this [example](http://threejs.org/examples/webgl_lensflares), right? What OS and graphics card do you use? I'm not getting the error messages with OS X 10.10.5. Tested with AMD Radeon R9 M295X and latest Chrome, Firefox, Safari.

**Comment by mrdoob** [comment]
I can't reproduce but I've added a blind fix for this in the `dev` branch. Do you mind testing it?

**Comment by Mugen87** [comment]
I'm still getting the error messages in FF45 and OS X 10.10.5. According to the [source code](https://hg.mozilla.org/releases/mozilla-aurora/file/f5b4bfb33ab4/dom/canvas/WebGLContext.cpp#l1974) zeroing texture data seems to be evil since FF45.

> Zero subrects from out-of-bounds blits. (CopyTex(Sub)Image)

Maybe the parameters of `gl.copyTexImage2D` in `LensFlarePlugin` are not 100% correct...

**Comment by RemusMar** [comment]
> I can't reproduce but I've added a blind fix for this in the dev branch. Do you mind testing it? 

Now I get the second error:

THREE.WebGLRenderer 76dev three.min.js:631:1
Error: WebGL: texImage2D: Uploading ArrayBuffers with FLIP_Y or PREMULTIPLY_ALPHA is slow. three.min_76.js:737:163
Error: WebGL: texImage2D: Uploading ArrayBuffers with FLIP_Y or PREMULTIPLY_ALPHA is slow. three.min_76.js:738:4
Error: WebGL: CopyTexImage2D: This operation requires zeroing texture data. This is slow. three.min_76.js:743:407
Error: WebGL: CopyTexImage2D: This operation requires zeroing texture data. This is slow. three.min_76.js:744:186
Error: WebGL: CopyTexImage2D: This operation requires zeroing texture data. This is slow. three.min_76.js:743:407
Error: WebGL: CopyTexImage2D: This operation requires zeroing texture data. This is slow. three.min_76.js:744:186
...
...

**Comment by mrdoob** [comment]
Oh man... I give up. Hopefully someone else has a go at this.

**Comment by RemusMar** [comment]
> Oh man... I give up. Hopefully someone else has a go at this. 

They still work properly on the latest Firefox and Chrome ... so this "enhancement" can wait.
cheers

**Comment by Mugen87** [comment]
Maybe i found the problem. @RemusMar Can you please test the following [example](https://s3.eu-central-1.amazonaws.com/yume.human-interactive.org/examples/temp/webgl_lensflares.html) and check the error messages?

**Comment by RemusMar** [comment]
> Maybe i found the problem. @RemusMar Can you please test the following example and check the error messages? 

No more console error messages.
Well done!

**Comment by Mugen87** [comment]
`copyTexImage2D` copies pixels from the current FBO to a texture. If the area of the copy is not defined correctly, FF will produce the mentioned messages.

The `LensFlarePlugin` plugin in three.js had some out-of-bound copies. The upcoming PR will prevent this behavior.

**Comment by Mugen87** [comment]
PR is merged. I think we can close this issue...

**Comment by RemusMar** [comment]
good work!
