### ISSUE TITLE
r74 Box3.setFromObject() will not properly compute the bounding box if the object contains an empty children

### ISSUE THREAD

**Issue by cheton** [mrdoob/three.js#8322]
##### Description of the problem 

I created an THREE.Object3D() to group a list of THREE.Line(), but some of them may have empty vertices. After calling `geometry.computeBoundingBox()`, all values in `geometry.boundingBox` will be `Infinity` or `-Infinity` while parsing empty nodes:
```js
{
    min: { x: Infinity, y: Infinity: z: Infinity },
    max: { x: -Infinity, y: -Infinity: z: -Infinity }
}
```

Just checked the code in Box3.js, I think it needs to validate `geometry.boundingBox` with its min/max values before calling `box.copy()` to prevent from generating `NaN` result.

Here is the relevant code:
https://github.com/mrdoob/three.js/blob/master/src/math/Box3.js#L119
```js
if ( geometry.boundingBox === null ) {
    geometry.computeBoundingBox();
}

box.copy( geometry.boundingBox );
box.applyMatrix4( node.matrixWorld );
scope.union( box );
```

Note. It happened only in r74.

##### Three.js version

- [ ] Dev
- [x] r74
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Have you tried with `dev`?

**Comment by WestLangley** [comment]
See if this change works
```javascript
setFromObject: function () {

	// Computes the world-axis-aligned bounding box of an object (including its children),
	// accounting for both the object's, and children's, world transforms

	var box;

	return function ( object ) {

		if ( box === undefined ) box = new THREE.Box3();

		var scope = this;

		this.makeEmpty();

		object.updateMatrixWorld( true );

		object.traverse( function ( node ) {

			var geometry = node.geometry;

			if ( geometry !== undefined ) {

				if ( geometry.boundingBox === null ) {

					geometry.computeBoundingBox();

				}

				if ( ! geometry.boundingBox.isEmpty() ) {

					box.copy( geometry.boundingBox );
					box.applyMatrix4( node.matrixWorld );
					scope.union( box );

				}

			}

		} );

		return this;

	};

}(),
```

**Comment by WestLangley** [comment]
Yes. This used to work. Apparently https://github.com/mrdoob/three.js/commit/02a36a8fa6dc5afd9134355d0f23b6f5dc7f7ff9 has a side effect?

**Comment by cheton** [comment]
@WestLangley It works for me. Adding the check can resolve this issue:
```js
if ( ! geometry.boundingBox.isEmpty() ) {
    box.copy( geometry.boundingBox );
    box.applyMatrix4( node.matrixWorld );
    scope.union( box );
}
```

It might be related to the code change of https://github.com/mrdoob/three.js/commit/278fdbdffd96384b9aaed8f2060ab2fbe97aed95.

**Comment by mrdoob** [comment]
Thanks guys!
