### ISSUE TITLE
WaterShader.js should maybe give error when camera is undefined.

### ISSUE THREAD

**Issue by EliasHasle** [mrdoob/three.js#8327]
##### Description of the problem 
Doing a modified version of the ocean demo (the one with the bouncing ball), I encountered a weird problem. The ocean was divided sharply in the middle. On one side it was almost white, and on the other just a little too bright. Rectangular shadows were floating around. I have seen the same symptoms reported by someone else, who seemed to believe they were caused by Microsoft Edge.

I completely stripped down my code to the part that was failing, and then only did I see the warning message that the camera was undefined, or rather that "the camera is not a perspectiveCamera". Maybe I should pay more attention to warnings, of course, but I can't help but wonder why it is allowed to pass an undefined camera at all. (It turned out that I had defined water before camera.)
...

##### Three.js version

- [ ] Dev
- [x] r74
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
>but I can't help but wonder why it is allowed to pass an undefined camera at all.

Because it is an example.

**Comment by EliasHasle** [comment]
@WestLangley OK, that explains why it has not been prioritized, but not why it is that way.

**Comment by mrdoob** [comment]
@EliasHasle In JavaScript type checking is done by hand, and it we type checked everything the code would be much less readable.
