### ISSUE TITLE
VREffect's stereo rendering broken on iOS

### ISSUE THREAD

**Issue by cvan** [mrdoob/three.js#8329]
##### Problem

With the introduction of [this line in `VREffect`'s `render` method](https://github.com/mrdoob/three.js/blob/ecc10c4/examples/js/effects/VREffect.js#L169), Safari/Edge cannot enter stereo projection because [the `isPresenting` variable never gets set](https://github.com/mrdoob/three.js/blob/ecc10c4/examples/js/effects/VREffect.js#L77-L91).

This is because the Fullscreen API (which was used by the old WebVR API) is not supported in Safari/IE10 - nor is the `vrdisplaypresentchange` event fired (which is specific to the new WebVR API, and it's not polyfilled by the webvr-polyfill; filed borismus/webvr-polyfill#40).

##### Three.js version

- r74/master
- dev

##### Browser

- Safari on iOS

##### OS

- iOS

##### Hardware requirements

Reproducible on Safari on an iPhone 6 w/ iOS 9.

**Comment by mrdoob** [comment]
#8330

**Comment by cvan** [comment]
fixed by webvr-polyfill changes :+1:
