### ISSUE TITLE
VR buttons obscured by "View Source" button in WebVR Cubes example

### ISSUE THREAD

**Issue by cvan** [mrdoob/three.js#8331]
http://threejs.org/examples/#webvr_cubes

<img width="1440" alt="screenshot 2016-03-09 22 18 40" src="https://cloud.githubusercontent.com/assets/203725/13661360/d7ec8b64-e646-11e5-8961-27f7a05060ae.png">
<img width="1440" alt="screenshot 2016-03-09 22 18 59" src="https://cloud.githubusercontent.com/assets/203725/13661359/d7ec6ba2-e646-11e5-9fd4-057d53feece6.png">

**Comment by mrdoob** [comment]
#8332
