### ISSUE TITLE
depth sorting implement for CanvasRenderer

### ISSUE THREAD

**Issue by liuyuanpeng** [mrdoob/three.js#8333]
##### Description of the problem 

Not all browsers support WebGL any way.
Depth sorting is strange, and can't use **_depthTest : fasle_** property of Material when using CanvasRenderer.

And it has bad z-fighting problem.
...

##### Three.js version

- [ ] Dev
- [x] r74

##### Browser

Browser that not supports WebGL.

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by makc** [comment]
They do not support CanvasRenderer, it is now sitting in the examples. Also, relevant discussion in #6011
