### ISSUE TITLE
Is Geometry.elementsNeedUpdate deprecated in r74

### ISSUE THREAD

**Issue by airycanon** [mrdoob/three.js#8338]
I found only [one line](https://github.com/mrdoob/three.js/blob/master/src/core/Geometry.js#L38) using elementsNeedUpdate in src.
I want to know If this flag is deprecated,and If  I add faces dynamically,how to update them?

**Comment by revillo** [comment]
I doubt this is condoned officially, but in my case I hacked it with

geometry._bufferGeometry.fromGeometry(geometry);

**Comment by airycanon** [comment]
@revillo Thanks for your reply, I am new to three.js,and my English is not so good,could you show me a sample,please?

**Comment by airycanon** [comment]
@mrdoob [This document](http://threejs.org/docs/index.html#Reference/Core/Geometry) says Geometry.elementsNeedUpdate needs to be set to true when I update faces,but it does not work since r72,the same code works fine with r71.
Could you please tell me if this flag is still usable?
Thanks for any help,sorry for my English.

**Comment by herzig** [comment]
@mrdoob this is still an issue in r78.
Geometry.elementsNeedUpdate doesn't work (and as far as I can tell is not used anywhere in the current source). 

If the flag really is deprecated maybe it should be removed from the documentation?

**Comment by mrdoob** [comment]
Fixed! 😊

**Comment by sylvain-abadie** [comment]
@mrdoob geometry.elementsNeedUpdate is never set back to false.  This leads to a massive performance and memory issue :  DirectGeometries keep getting instantiated. 
[http://jsfiddle.net/buxv7g9u/6/](url)

**Comment by DVLP** [comment]
https://github.com/mrdoob/three.js/pull/9359
