### ISSUE TITLE
OrthographicCamera with OrbitControls does not pan properly when zoomed

### ISSUE THREAD

**Issue by russplaysguitar** [mrdoob/three.js#8340]
##### Description of the problem 

When using OrthographicCamera with OrbitControls, the distance that is panned is affected by the zoom level. Zooming in very far causes the pan to move "too quickly", and the further out you zoom the "slower" the pan. 

Current version Fiddle: http://jsfiddle.net/akmcv7Lh/30/
Dev version Fiddle: http://jsfiddle.net/hw9rcLL8/15/

##### Three.js version

- [ ] Dev
- [x] r74
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

Not sure

**Comment by russplaysguitar** [comment]
Not sure if that's the perfect fix, but it worked out OK for me. Let me know if I'm missing something.

**Comment by WestLangley** [comment]
Nice find. What you proposed is the correct solution.

>Let me know if I'm missing something.

Just a tip. See [this SO answer](http://stackoverflow.com/questions/17558085/three-js-orthographic-camera/17567292#17567292) for info regarding the `OrthographicCamera` constructor parameters.

**Comment by russplaysguitar** [comment]
Great, thanks!
