### ISSUE TITLE
Suggestion: Using Grunt to simplify Build

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#8351]
Why should we use a task runner like [Grunt](http://gruntjs.com/)?

_In one word: automation. The less work you have to do when performing repetitive tasks like minification, compilation, unit testing, linting, etc, the easier your job becomes. After you've configured it through a Gruntfile, a task runner can do most of that mundane work for you—and your team—with basically zero effort._ (from [official website](http://gruntjs.com/))

Because i'm using Grunt in all my projects, i've created the following configuration file (called `Gruntfile.js`) in order to implement the build of three.js. (I'm not quite sure if all former functionalities of the build are considered. It's just a first prototype.).

If you check out the `Gruntfile.js`, you will see that most of the JavaScript is **configuration**. That simplifies maintenance and provides a good foundation for further expansion stages. I've only needed to implement a single custom function for GLSL parsing and some comment placing. 

**[Gruntfile.js.zip](https://github.com/mrdoob/three.js/files/170986/Gruntfile.js.zip)**

## Getting started

If you want to check out the Grunt build for three.js, you need to do the following:

- Ensure node.js is installed
- Install Grunt CLI (This will put the grunt command in your system path, allowing it to be run from any directory.)
```
npm install -g grunt-cli
```
- Change to the three.js's root directory
- Place the attached `Gruntfile.js` into the root directory
- Expand the `package.json`by these entires
```javascript
"devDependencies": {
    "argparse": "^1.0.3",
    "jscs": "^1.13.1",
    "uglify-js": "^2.6.0",
    // new
    "google-closure-compiler": "^20160208.5.0",
    "grunt": "^0.4.5",
    "grunt-contrib-concat": "^1.0.0",
    "grunt-contrib-watch": "^0.6.1"
  }
```
- Remove  `var AudioContext;` from `utils/build/externs/common.js`. The used closure-compiler does not need this definition any more.
- Now install project dependencies with
```
npm install
```
* Run Grunt. This will execute the default task that builds `three.js`/`three.min.js`(with the includes `common` and `extras`).
```
grunt
```

#### Main Tasks

```
grunt default
```
Same as 'grunt'. As mentioned before, this task builds `three.js`/`three.min.js` with the includes `common` and `extras`.

```
grunt canvas
```
This task builds `three.js`/`three.min.js` with the include `canvas`.

```
grunt css3d
```
This task builds `three.js`/`three.min.js` with the include `css3d`.

```
grunt math
```
This task builds `three.js`/`three.min.js` with the include `math`.

```
grunt watch
```
When this task is active and detects any of the source files have changed, it will run the default task.

#### Other Tasks

```
grunt closure-compiler
```
The target `prod` creates the minified and optimized version `three.min.js` ( call `grunt closure-compiler:prod`). The target `sourcemap` generates the sourcemap `three.min.js.map` and an adjusted `three.min.js` ( call `grunt closure-compiler:sourcemap`).

```
grunt concat
```
This task concatenates source files to `three.js`. There are different targets for all type of builds. You use them like this `grunt concat:core` or `grunt concat:canvas`.

## Parameters

You can apply two parameters to each grunt task.

```
grunt --dest
```
This parameter allows you to change the destination directory. Default is `build`.

```
grunt --name
```
This parameter allows you to change the name of the build files. Default is `three`.

**Comment by ashconnell** [comment]
I'm not sure this is needed, but if it was, gulp would be a better option. Gulp is a lot more performant, has better plugins and allows you to write plain old javascript in your tasks.

**Comment by Komsomol** [comment]
Would prefer not to be tied to any automation system (grunt yesterday, gulp today, xxx tomorrow). 

Rather this should be left to the user to implement on their own projects.

**Comment by Mugen87** [comment]
Well, it was just a suggestion. If anyone needs a Grunt script for its custom three.js build, this issue maybe help further.
