### ISSUE TITLE
computeFaceNormals fails when using Geometry fromBufferGeometry with Line buff Geometry

### ISSUE THREAD

**Issue by cindyloo** [mrdoob/three.js#8352]
##### Description of the problem 
in fromBufferGeometry, on line 10077
computation of face normals breaks if the number of vertices is not equally divisible by 3

var vA = this.vertices[ face.a ];
var vB = this.vertices[ face.b ];  //may be undefined
var vC = this.vertices[ face.c ]; //may be undefined

I think this is because at line 10006 addFace() adds irregardless of the size of the vertices array.
eg addFace( i, i + 1, i + 2 );

I am converting the line buffer geo to a standard geometry so I can export using the OBJExporter..

##### Three.js version

- [ ] Dev
- [x] r74
- [ ] ...

##### Browser

- [ x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

mac osx 10.8.5

**Comment by mrdoob** [comment]
Can you provide a jsfiddle?

**Comment by cindyloo** [comment]
sure, here is a slimmed-down version.  only thing is the event listener is behaving strangely in the fiddle, but it should be clear how the line is getting created...

http://jsfiddle.net/cindy/pj9yt7ox/37/

**Comment by WestLangley** [comment]
@cindyloo I expect @mrdoob is expecting a simple fiddle.

http://jsfiddle.net/7xz9x7tf/

**Comment by cindyloo** [comment]
ah yes, less is more

**Comment by mrdoob** [comment]
I think we should, instead, change `OBJExporter` so it handles `BufferGeometry` instead.

@Mugen87 is this something you would like to tackle?

**Comment by Mugen87** [comment]
I will have a look at it...

**Comment by Mugen87** [comment]
I've tested some things with `OBJExporter` and `BufferGeometry` and i've discovered a problem. Let's say i have the following simple geometry.

```javascript
var geometry = new THREE.Geometry();

geometry.vertices.push( new THREE.Vector3( -50, -50, 0 ) );
geometry.vertices.push( new THREE.Vector3(  50, -50, 0 ) );
geometry.vertices.push( new THREE.Vector3(  50,  50, 0 ) );
```
If i use this to create a `Line` object, exporting with the current implementation works fine. But if convert the geometry to `BufferGeometry` (via `BufferGeometry.fromGeometry`), i have an empty `position` attribute. It looks like that `DirectGeometry.fromGeometry` does not provide good results if **no faces** are defined.

Because of this, `OBJExporter` can't exclusively work with `BufferGeometry` right now. Actually i wanted to do this when parsing a mesh or line.

```javascript
var parseLine = function( line ) {

    // ...

    if ( geometry instanceof THREE.Geometry ) {

        geometry = new THREE.BufferGeometry().fromGeometry( geometry );

    }

    // now start parsing with BufferGeometry...

}
```

But i looks like that does not work with geometries of  `Line` objects. Any ideas how to convert a `Geometry` that has only vertices (no faces) to `BufferGeometry`?

**Comment by WestLangley** [comment]
>Any ideas how to convert a Geometry that has only vertices (no faces) to BufferGeometry?

That is the root of the problem. See 2nd fiddle posted above.

**Comment by Mugen87** [comment]
> That is the root of the problem. See 2nd fiddle posted above.

I see. It looks like `Geometry.fromBufferGeometry` has problems to distinguish, if the current `BufferGeometry` is a non-indexed geometry for meshes or a geometry for lines. Your example perfectly illustrates that case. 

Um... `Geometry .fromBufferGeometry` always tries to create faces even if it's not necessary. Maybe we need an additional method in `Geometry`?

An enhancement for `DirectGeometry.fromGeometry` is easier think. The following logic should enable a correct conversion from `Geometry` to `BufferGeometry`:

- If no faces are defined in parameter `geometry`, `DirectGeometry.fromGeometry` just transfers vertices from `geometry.vertices` to `this.vertices` and colors from `geometry.colors` to `this.colors`.

**Comment by Mugen87** [comment]
Why not doing this in `Geometry.fromBufferGeometry`?

```javascript
if( ( geometry.attributes.position.count % 3 ) === 0 ) {

// non-indexed mesh geometry

} else {

// non-indexed line geometry. don't create faces...

}

```

**Comment by WestLangley** [comment]
```javascript
if ( geometry.index === null ) {
   if ( ( geometry.attributes.position.count % 3 ) === 0 ) {
        // non-indexed mesh geometry
```
I do not think you can draw that conclusion.

**Comment by Mugen87** [comment]
Well, maybe i am off the track :wink:. What's the problem with the statement?

**Comment by WestLangley** [comment]
Sorry. I meant to add a reason. A line can have 3 vertices.

**Comment by Mugen87** [comment]
Oops! Good point! So the modulo operation does not work....

**Comment by mrdoob** [comment]
What I was poposing was to change `OBJExporter` so it handles `BufferGeometry` directly instead. And if the input is a `Geometry`, convert it to `BufferGeometry`.

**Comment by Mugen87** [comment]
> And if the input is a Geometry, convert it to BufferGeometry.

Doing this is problematic if the 3DObject is a `Line`. I need to change `DirectGeometry.fromGeometry` to get things work. 

I always thought, that a `Geometry` object for a `Line` just hast vertices and maybe colors. If i try to convert this to `BufferGeometry`, `DirectGeometry.fromGeometry` does not fill the vertices array because of [this](https://github.com/mrdoob/three.js/blob/dev/src/core/DirectGeometry.js#L166).

**Comment by Mugen87** [comment]
I discovered, that i can do the conversion with `BufferGeometry.setFromObject`.

**Comment by mrdoob** [comment]
> I discovered that i can do the conversion with `BufferGeometry.setFromObject`.

😁

**Comment by mrdoob** [comment]
#8427 should fix OP's use case.

**Comment by cindyloo** [comment]
not sure what you mean by 'can do the conversion' from BuffGeo... I'm going the other way- from BufferGeo to something that is exportable... I noted at #8427 the problem with the resulting OBJ file...
