### ISSUE TITLE
Adopt Burley 2012 Diffuse model for improved accuracy

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8354]
##### Description of the problem

From Frostbite 3 paper on page 9:

"Burley [Bur12] has presented another diffuse model built on real world surface observations, see Equation 5. While this model is empirical, it allows us to reproduce the main features of the MERL
database’s materials. For this reason and because of its simplicity, we have chosen to use this model
in Frostbite. This diffuse term takes into account the roughness of the material and creates some
retro-reflection at grazing angles."

https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32.pdf

For improved accuracy, we should likely replace the simple Lambertian diffuse model with Burley 2012 in our Standard material.
##### Three.js version
- [x] Dev
- [ ] r74
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
I agree it is worth a try.

**Comment by mrdoob** [comment]
That paper looks great!
/me adds AreaLight and SphereLight to wish list 😁

**Comment by erichlof** [comment]
+1 here too!  Those sample diffuse spheres in the Frostbite paper look very realistic!
