### ISSUE TITLE
Upgrade G_GGX_Smith to SmithCorrelated

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8355]
##### Description of the problem 

We are using a less accurate version of the Smith GGX visibility function.  Both Frostbite 3 and Unreal Engine 4 use a different version.  See page 12, listing 2, line 20 - notice the equation has multiplications instead of additions as well as a coefficient of 0.5:

http://www.frostbite.com/wp-content/uploads/2014/11/course_notes_moving_frostbite_to_pbr_v2.pdf

We should use this function instead of the simple Smith GGX visibility function to be current with the state of the art.

Further discussion of why we should use this function is given on pages 7-8 of the Frostbite paper and they refer to this paper as backup: https://hal.inria.fr/hal-00942452v1/document

Probably something for @WestLangley to review.

##### Three.js version

- [x] Dev
- [ ] r74
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
@bhouston Agreed.

**Comment by bhouston** [comment]
This was merged.  CLosing.
