### ISSUE TITLE
BufferGeometry and BufferAttribute don't support Uint8Array

### ISSUE THREAD

**Issue by huningxin** [mrdoob/three.js#8358]
##### Description of the problem 

My mesh data has `colors` in `Uint8Array`. I'd like to use `BufferGeometry` and `BufferAttribute` to upload it.
```
  var geometry = new THREE.BufferGeometry();
  ...
  var colors = new Uint8Array(triangles * 3 * 4);

  for (var i = 0, l = triangles * 3 * 4; i < l; i += 4) {

    colors[i] = Math.random() * 255;
    colors[i + 1] = Math.random() * 255;
    colors[i + 2] = Math.random() * 255;
    colors[i + 3] = Math.random() * 255;

  }

  geometry.addAttribute('color', new THREE.BufferAttribute(colors, 4));
  ...
```

However, browser (Chrome under my test) reports
```
[GroupMarkerNotSet(crbug.com/242999)!:DC810B0A]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 1
(index):1 WebGL: too many errors, no more errors will be reported to the console for this context.
```

I created a fiddle (fork from http://threejs.org/examples/webgl_buffergeometry_rawshader.html) for your reference:
https://jsfiddle.net/huningxin/594jjzb9/3/

##### Three.js version

- [x] Dev
- [x] r74

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Hmm, I think this is a limitation in `WebGL` itself? Meaning that `gl.bufferData()` only accepts `Float32Array`.

**Comment by huningxin** [comment]
I can upload the `colors` in `Uint8Array`  with raw WebGL by following code:
```
var colors = new Uint8Array(triangles * 3 * 4);

for (var i = 0, l = triangles * 3 * 4; i < l; i += 4) {

  colors[i] = Math.random() * 255;
  colors[i + 1] = Math.random() * 255;
  colors[i + 2] = Math.random() * 255;
  colors[i + 3] = Math.random() * 255;

}
...
var vertexColorBuffer = gl.createBuffer();
var vertexColorAttribute = gl.getAttribLocation(program, 'color');
gl.enableVertexAttribArray(vertexColorAttribute);
gl.bindBuffer(gl.ARRAY_BUFFER, vertexColorBuffer);
gl.bufferData(gl.ARRAY_BUFFER, colors, gl.STATIC_DRAW);
gl.bindBuffer(gl.ARRAY_BUFFER, vertexColorBuffer);
gl.vertexAttribPointer(vertexColorAttribute, 4, gl.UNSIGNED_BYTE, true, 0, 0);

```

As my understanding, the `setupVertexAttributes` (https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L994) only handles `_gl.FLOAT` type.

**Comment by mrdoob** [comment]
Oh, I see I see!

So it's just a matter of adding:

```javascript
var type = _gl.FLOAt;
if ( array instanceof Uint8Array ) type = _gl.UNSIGNED_BYTE;
```

Any other TypedArrays that WebGL can handle?

**Comment by huningxin** [comment]
As WebGL spec (https://www.khronos.org/registry/webgl/specs/latest/1.0/) and corresponding `vertexAttribPointer` manual page (https://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttribPointer.xml) the "GL_BYTE, GL_UNSIGNED_BYTE, GL_SHORT, GL_UNSIGNED_SHORT, GL_FIXED, or GL_FLOAT are accepted.". But I didn't try other types expect `gl.FLOAT` and `gl.UNSIGNED_BYTE`.

And for `gl.UNSIGNED_BYTE`, it should set `normalized` parameter to `true`.
```javascript
var type = _gl.FLOAT;
var normalized = false;
if ( array instanceof Uint8Array ) {
  type = _gl.UNSIGNED_BYTE;
  normalized = true;
}
```

WDYT?

**Comment by mrdoob** [comment]
Sounds good to me! Would you like to do a PR?

**Comment by huningxin** [comment]
Sure. I like to do one. Any tests to run before send a PR?

**Comment by mrdoob** [comment]
Nope. No tests needed.

**Comment by filipsladek** [comment]
InstancedBufferAttribute does not have constructor with param normalized. It could be set directly, but it is not nice and user then does not know why it does not work if he fills it with Uint8Array.
