### ISSUE TITLE
TGALoader is loading a mirrored image in vertical axis

### ISSUE THREAD

**Issue by bglima** [mrdoob/three.js#8359]
##### Description of the problem 

Loading a .obj model with a .mtl material using a Targa image as texture, the image is loaded mirrored. It can be noticed in the following [image](https://cloud.githubusercontent.com/assets/6970036/13797790/f9ddf832-eaee-11e5-8300-a25606973c62.png) where the left one is .tga and the right one is .png.

Opening both images (.tga and .png) in an image editor, they show to be the same. And, as long the .png image is loaded correctly, I think the problem might be on TGALoader class. 

I know I could flip the texture with `texture.flipY = true; `. The problem is that I am trying to load different image formats to use as texture, like .jpg and .png, and only the .tga texture is loaded flipped. 

Making some tests I realized that the problem might be in getTgaRGBA function, from TGALoader. The switch is getting 0x00 as parameter. If I hardcode it to 0x02, the .tga is loaded correctly.

```
        TGA_ORIGIN_MASK = 0x30,
        TGA_ORIGIN_SHIFT = 0x04,
        TGA_ORIGIN_BL = 0x00,
        TGA_ORIGIN_BR = 0x01,
        TGA_ORIGIN_UL = 0x02,
        TGA_ORIGIN_UR = 0x03;

    function getTgaRGBA( width, height, image, palette ) {
        var x_start,
            y_start,
            x_step,
            y_step,
            x_end,
            y_end,
            data = new Uint8Array( width * height * 4 );
         //switch ( 0x02 ) {
        switch ( ( header.flags & TGA_ORIGIN_MASK ) >> TGA_ORIGIN_SHIFT  ) {
        default:
        case TGA_ORIGIN_UL:
            x_start = 0;
            x_step = 1;
            x_end = width;
            y_start = 0;
            y_step = 1;
            y_end = height;
            break;

        case TGA_ORIGIN_BL:
            x_start = 0;
            x_step = 1;
            x_end = width;
            y_start = height - 1;
            y_step = - 1;
            y_end = - 1;
            break;

        case TGA_ORIGIN_UR:
            x_start = width - 1;
            x_step = - 1;
            x_end = - 1;
            y_start = 0;
            y_step = 1;
            y_end = height;
            break;

        case TGA_ORIGIN_BR:
            x_start = width - 1;
            x_step = - 1;
            x_end = - 1;
            y_start = height - 1;
            y_step = - 1;
            y_end = - 1;
            break;

    }
```

##### Three.js version

- [ ] Dev
- [x] r74
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
For reference, this question was previously [posted](http://stackoverflow.com/questions/35868761/tgaloader-is-loading-image-mirrored-in-vertical-axis) on stackoverflow.

Do you mean the image is flipped -- mirrored in the `horizontal` axis?

**Comment by mrdoob** [comment]
> Loading a .obj model with a .mtl material using a Targa image as texture, the image is loaded mirrored. It can be noticed in the following [image](url) where the left one is .tga and the right one is .png.

You forgot to add the link.

**Comment by bglima** [comment]
Oh, I'm sorry! Here is the [image](https://cloud.githubusercontent.com/assets/6970036/13797790/f9ddf832-eaee-11e5-8300-a25606973c62.png) I talked about.

I've downloaded this model from [here](http://tf3dm.com/download-page.php?url=cat-95027).

And that's right! Thanks for referencing, @WestLangley!

**Comment by bglima** [comment]
Here is the result when I hardcode the switch parameter to 0x02: 
[image](https://cloud.githubusercontent.com/assets/6970036/13798018/c3400b6a-eaf0-11e5-8ed9-cdcf315da6e7.png)

**Comment by daoshengmu** [comment]
@bglima . Sorry for this bug. I think this is my mistake for handling TGA parsing origin, and I am working on it. Could you provide me your tga file to have a proof test?

Thanks.

**Comment by bglima** [comment]
@daoshengmu Sure! Github does not allow me to send .tga files, but I saved two of them [here](https://drive.google.com/folderview?id=0B5EvTvCZyAi1cmRDNHZ5bVVCcFk&usp=sharing).

**Comment by daoshengmu** [comment]
I have tested them with my changes. That looks good! Your art work is really awesome! Look forward for your new game release.
