### ISSUE TITLE
OBJMTLLoader.js is missing

### ISSUE THREAD

**Issue by minkcv** [mrdoob/three.js#8362]
##### Description of the problem 
The page at http://threejs.org/docs/#Reference/Loaders/OBJMTLLoader has a source link at the bottom that does not work. The OBJMTLLoader.js file is not in the repository. 

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
See #8085. The docs need to be updated.

**Comment by minkcv** [comment]
Thanks
