### ISSUE TITLE
THREE.Audio is missing a callback

### ISSUE THREAD

**Issue by EvilPeanut** [mrdoob/three.js#8367]
##### Description of the problem 
https://github.com/mrdoob/three.js/blob/master/src/audio/Audio.js 's load() function is missing a callback.

The callback is needed if you want to load audio and play it as soon as it is loaded, without it you get an error because the file isn't loaded and you are attempting to play it. However there is no callback so it is not known exactly when it is loaded.

I am temporarily using the below method to get around this problem, but it isn't clean:

```
function loadSound(url, audioObject, onSuccess) {
	var audioBuffer = new THREE.AudioBuffer(audioObject.context);

	audioBuffer.load(url);

	audioBuffer.readyCallbacks[0] = function() {
		audioObject.setBuffer(audioBuffer);
		
		onSuccess();
	}
}
```

##### Three.js version

- [x] Dev
- [x] r74

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by EvilPeanut** [comment]
I've just found #8176 which is heavily related.

I hope to start helping with the project in the near future, perhaps I could look into resolving this issue and making a pull request?

**Comment by EvilPeanut** [comment]
I have just forked the project and I'm trying to make an AudioLoader class which functions in the same way as the other loaders.

My below code returns an empty ArrayBuffer for the audio variable, any idea why?

```
/**
 * @author Reece Aaron Lecrivain / http://reecenotes.com/
 */

THREE.AudioLoader = function ( context, manager ) {

	this.context = ( context !== undefined ) ? context : new ( window.AudioContext || window.webkitAudioContext )();

	this.manager = ( manager !== undefined ) ? manager : THREE.DefaultLoadingManager;

};

THREE.AudioLoader.prototype = {

	constructor: THREE.AudioLoader,

	load: function( url, onLoad, onProgress, onError ) {

		var scope = this;

		var loader = new THREE.XHRLoader( this.manager );
		loader.setResponseType( 'arraybuffer' );
		loader.load( url, function ( audio ) {

			scope.context.decodeAudioData( this.audio, function ( buffer ) {

				onLoad(buffer);

			} );

		}, onProgress, onError );

	}

};
```

**Comment by mrdoob** [comment]
I see that both `THREE.Audio` and `THREE.AudioBuffer` have loading logic. Maybe we should do a `THREE.AudioLoader` so it follows the rest of the API?

**Comment by EvilPeanut** [comment]
I've just coded THREE.AudioLoader and got it working, I have also removed THREE.AudioBuffer as there is no need for it with the THREE.AudioLoader. I'm just working out how to build three.js from my fork now to test it more in-depth.

**Comment by EvilPeanut** [comment]
I have got it to work with the following code, it could probably still have some work done to look nicer though

```
var audioListener = new THREE.AudioListener();
camera.add(audioListener);

var sound1 = new THREE.Audio( audioListener );
scene.add( sound1 );

var audioLoader = new THREE.AudioLoader();
audioLoader.load('resources/audio/engine_car_acceleration.ogg', function(buffer) {
   sound1.setBuffer(buffer);
});
```

After the above code you can then call `sound1.play()`

Note: The `THREE.AudioLoader()` load function accepts arguments as shown
`function( url, onLoad, onProgress, onError )`

**Comment by EvilPeanut** [comment]
I have committed my changes to my 'audio-dev' branch of three.js, it can be found at
https://github.com/EvilPeanut/three.js/commit/ccbccc52843a5967b7e81f0450e2943b59de6685

It still needs touching up but it does work! :)
