### ISSUE TITLE
Missing documentation for clampLength()

### ISSUE THREAD

**Issue by DelvarWorld** [mrdoob/three.js#8371]
There is no documentation for the `clampLength` method (see below comment)

**Comment by Mugen87** [comment]
What about `.clampLength` (see [here](https://github.com/mrdoob/three.js/blob/master/src/math/Vector3.js#L473))? The method offers a `min` and `max` parameter.

**Comment by DelvarWorld** [comment]
Ah, that function isn't documented :( renaming ticket to add docs for it

**Comment by Mugen87** [comment]
@DelvarWorld Do you mind if you close the issue? The methods are documented now.

**Comment by DelvarWorld** [comment]
Thanks! Is there any way we can automatically require features added to core to be documented before the next release?

**Comment by Mugen87** [comment]
Um, that's not really my area. Maybe with more discipline? :wink:
