### ISSUE TITLE
object3d rotation point (pivot)

### ISSUE THREAD

**Issue by RoeePeleg** [mrdoob/three.js#8374]
object3d rotation point (pivot) would be useful.
im trying to group some objects and rotate them together around specific point (dynamic).
thx in advance

NOTE : the original position of group object and its children cannot be changed
...
r73, chrome, windows

**Comment by mrdoob** [comment]
This has been discussed before many times. The solution is to group the objects twice and offset the second group.

**Comment by RoeePeleg** [comment]
in case of group objects twice - their position would be relative to the first group or to the second? 
for my issue, i need the position to be relative to the first one and only to it,
