### ISSUE TITLE
glTF Loader issue - duck is dark

### ISSUE THREAD

**Issue by cx20** [mrdoob/three.js#8381]
##### Description of the problem 

1. Show glTF loader example (http://threejs.org/examples/webgl_loader_gltf.html)
2. Model: [Duck] 
3. Shaders: [ ] Use built-in (checked is off)

##### Result

duck.gltf (http://threejs.org/examples/models/gltf/duck/glTF/duck.gltf) is dark.

![image](https://cloud.githubusercontent.com/assets/1833979/13818527/767421ba-ebd9-11e5-88a9-5596323b3e4f.png)

...

##### Three.js version

- [X] r75

##### Browser

- [X] Chrome 49.0.2623.87 m
- [X] Firefox 44.0.2
- [X] Internet Explorer 11.162.10586.0
- [X] Edge 25.10586.0.0 (EdgeHTML 13.10586)

##### OS

- [X] Windows 10

##### Hardware Requirements (graphics card, VR Device, ...)

ThinkPad X201 + Intel HD Graphics

**Comment by RemusMar** [comment]
![nvidia](https://cloud.githubusercontent.com/assets/11772787/13819704/1b1f95aa-eba3-11e5-855c-cdcf961ac85d.png) 
No problems on Firefox 45 + Nvidia graphics card

**Comment by WestLangley** [comment]
Try the dev branch.

http://threejsworker.com/api/branch/dev/examples/webgl_loader_gltf.html

Although, the models in this link do not render for me using Safari 9.0.3 on OS X 10.11.3.

**Comment by cx20** [comment]
![duck](https://cloud.githubusercontent.com/assets/1833979/13820256/d7448876-ebdf-11e5-8682-3902e8e8bb2f.gif)

Windows 10 + Chrome 49 + GeForce GTX 660

**Comment by mrdoob** [comment]
It seems to work fine here...

![screenshot from 2016-03-16 16-38-42](https://cloud.githubusercontent.com/assets/97088/13820520/96255b6c-eb95-11e5-9af8-19c263d43f38.png)

Fedora 23 + Chrome 49 + Intel Iris Graphics 540

/ping @tparisi

**Comment by tparisi** [comment]
yeah I'm not seeing that

**Comment by cx20** [comment]
I made a simple example.

http://jsdo.it/cx20/GLug

and, I tried to change the variables in the Firefox Shader Editor.

````glsl
specularIntensity = max(0., pow(max(dot(normal, h), 0.), u_shininess)) * attenuation;
//specularIntensity = max(0., pow(max(dot(normal, h), 0.), 1.0)) * attenuation;
````
![image](https://cloud.githubusercontent.com/assets/1833979/13844047/995b5198-ec7a-11e5-93c1-192bd5625e4d.png)

````glsl
//specularIntensity = max(0., pow(max(dot(normal, h), 0.), u_shininess)) * attenuation;
specularIntensity = max(0., pow(max(dot(normal, h), 0.), 1.0)) * attenuation;
````

![image](https://cloud.githubusercontent.com/assets/1833979/13844077/d120cd56-ec7a-11e5-8db5-26e8eb85a528.png)

![image](https://cloud.githubusercontent.com/assets/1833979/13843990/5772f0f6-ec7a-11e5-8424-7305df80e3a4.png)
------------
ThinkPad X201 + Intel HD Graphics + Windows 10 + Firefox 45.0

**Comment by mrdoob** [comment]
Ah yeah, we fixed these issues in the past in the built-in shaders.

@tparisi welcome to the lovely world of gpu discrepancies support 😉

**Comment by emadurandal** [comment]
Hello everyone.

I have the same problem with him example ( http://jsdo.it/cx20/GLug ).

My environment is Windows10, Chrome 49.0.2623.87 m, Quadro K2000D.

But, I'm not seeing this problem using MacBook Pro (Retina, 15-inch, Mid 2015, Radeon R9 M370X).

mysterious... anyway, I guess this problem happens in Windows.
(It's cause by a difference between ANGLE webgl implementation and others?)

**Comment by mrdoob** [comment]
@tpaisi Check #7252

**Comment by mrdoob** [comment]
@tparisi Check #7252.

**Comment by tparisi** [comment]
@pjcozzi looks like we some issues w the GLSL being generated by the converter

**Comment by pjcozzi** [comment]
@tparisi can you try putting this workaround in JavaScript for the `SHININESS` semantic: https://github.com/mrdoob/three.js/issues/7252#issuecomment-146239802?

@cx20 can you try to drag and drop the duck model (original COLLADA and textures or glTF with embedded resources) into the Cesium viewer so we can isolate if this is the shaders: http://cesiumjs.org/convertmodel.html?

**Comment by tparisi** [comment]
@pjcozzi will do

**Comment by WestLangley** [comment]
Yes. I expect `u_shininess` has been set to zero. And that is causing the problem.

**Comment by mrdoob** [comment]
#8429 should fix this.

**Comment by cx20** [comment]
I tried fixed glTFLoader.js. But, I failed.

https://github.com/tparisi/three.js/blob/6663990f65b593c925979f5d291dbed6d5c07166/examples/js/loaders/gltf/glTFLoader.js#L167

However, after changing following undefined to 1.0 with a debugger, it was colored..

![image](https://cloud.githubusercontent.com/assets/1833979/13957623/6958315e-f090-11e5-91ea-1ebc848a716d.png)

![image](https://cloud.githubusercontent.com/assets/1833979/13957645/7a643f42-f090-11e5-8f0c-64a789c62cc4.png)

**Comment by tparisi** [comment]
@mrdoob how to proceed? I guess I can scare up a Windows box to test this on...

**Comment by emadurandal** [comment]
Hi.

I'd like to add additional infomation to @cx20's comment.

@cx20 and I tried latest dev:branch (pullrequest #8381 included), but the same problem still happend.

@cx20 set breakpoint at glTFLoader.js#L167. Then, u_shininess's value was undefined in all browsers.

Yes. the value is undefined. But...

My Windows's firefox:  works fine. 
My Windows's chrome:  blinking.
My Windows's Edge:  black out.
@cx20's Windows's firefox: black out.
@cx20's Windows's chrome: blinking.
@cx20's Windows's Edge: black out. 

According to this results, When a uniform value is set to `undefined`, the behavior is very undefined! (depend on WebGL implementation).

**Comment by cx20** [comment]
I found the cause that shininess became undefined.

After making the following modifications, a value came to be set in shininess variable.

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/gltf/glTFLoader.js#L824

- before
```javascript
    case WebGLRenderingContext.FLOAT :
        utype = "f";
        uvalue = shaderParam.value;
        if (pname == "transparency") {
            var USE_A_ONE = true; // for now, hack because file format isn't telling us
            var opacity =  USE_A_ONE ? value : (1.0 - value);
            uvalue = opacity;
            params.transparent = true;                                    
        } // Case, uvalue except "transparency" are not set pname.
        break;
    case WebGLRenderingContext.FLOAT_VEC2 :
```

- after
```javascript
    case WebGLRenderingContext.FLOAT :
        utype = "f";
        uvalue = shaderParam.value;
        if (pname == "transparency") {
            var USE_A_ONE = true; // for now, hack because file format isn't telling us
            var opacity =  USE_A_ONE ? value : (1.0 - value);
            uvalue = opacity;
            params.transparent = true;
        } else if (value) {
            uvalue = value;
        }
        break;
    case WebGLRenderingContext.FLOAT_VEC2 :
```

WebGL Inspector

- before
![image](https://cloud.githubusercontent.com/assets/1833979/17836888/14426738-67dd-11e6-9b68-2ecc65501b40.png)

- after
![image](https://cloud.githubusercontent.com/assets/1833979/17836890/1cefcb96-67dd-11e6-98a2-ddc6906e5487.png)

**Comment by richtr** [comment]
Could you check if this https://github.com/mrdoob/three.js/pull/9726 fixes these issues?

**Comment by richtr** [comment]
ping @cx20

**Comment by richtr** [comment]
Sorry, wrong thread :/

**Comment by cx20** [comment]
Duck is now bright. Thank you everyone. 👍 

https://cdn.rawgit.com/mrdoob/three.js/dev/examples/webgl_loader_gltf.html

![image](https://cloud.githubusercontent.com/assets/1833979/19194633/36b76314-8ce9-11e6-96c1-cad938f64166.png)

ThinkPad X201 + Intel HD Graphics
