### ISSUE TITLE
Sky Shader does not render on Android/S6

### ISSUE THREAD

**Issue by brianchirls** [mrdoob/three.js#8382]
##### Description of the problem 

The SkyShader does not render at all on my Samsung Galaxy S6. You can see this with the sky example. I am unfortunately not able to see the console, because USB debugging just doesn't work with this device.

It's *possible* that it might be related to this warning on the sky shader, which I see in the console in Firefox on Windows.

```
THREE.WebGLProgram: gl.getProgramInfoLog() C:\fakepath(110,89-162): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(111,88-161): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(78,68-182): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(118,34-232): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(137,34-116): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
```

##### Three.js version

- [x] Dev
- [x] r75
- [x] r74

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

- Android
- Samsung Galaxy S6
- Chrome and Firefox

**Comment by brianchirls** [comment]
Update:
I tried patching the `pow` problem, and while it did make the warnings go away, it did not fix the problem.

I was briefly able to debug this, and I'm not seeing any shader errors or anything else super helpful in the console. The following extensions are not supported in this device:
- `OES_texture_float`
- `OES_texture_float_linear`
- `OES_texture_half_float`
- `OES_texture_half_float_linear`
- `EXT_texture_filter_anisotropic`

But I don't think the sky shader uses any of those.

**Comment by mrdoob** [comment]
@zz85 any ideas?

**Comment by brianchirls** [comment]
I was finally able to isolate the problem. For some reason I can't figure out, the `exp` function in `sunIntensity` is returning the wrong value. It appears to be returning `0` instead of roughly `0.22`. Maybe it has something to do with float precision, or maybe it's just a bug in the GPU driver.

But replacing `exp(n)` with `pow(e, n)` works, since `e` is already defined as a constant in that shader. I'll submit a pull request.

**Comment by zz85** [comment]
nice job tracing the problem! @brianchirls

**Comment by brianchirls** [comment]
Looks like this was fixed months ago and nobody remembered to close it, so I'll do that.
