### ISSUE TITLE
OBJLoader does not distinguish between `o` and `g` tags.

### ISSUE THREAD

**Issue by andreykaipov** [mrdoob/three.js#8383]
This causes OBJLoader to create superfluous meshes whose geometries are empty, which can be seen in the OBJLoader example [here](http://threejs.org/examples/webgl_loader_obj).

Open up the dev-tools console and copy-paste in the following snippet.

```
var object;
scene.traverse( function( child ) {
    if ( child instanceof THREE.Group ) {
        object = child;
    }
});

object.traverse( function( child ) {
    if ( child instanceof THREE.Mesh ) {
        var geometry = new THREE.Geometry().fromBufferGeometry(child.geometry);
        console.log("Mesh name: " + child.name);
        console.log("Mesh's geometry has " + geometry.vertices.length + " vertices.");
        console.log("Mesh's geometry has " + geometry.faces.length + " faces.");
        console.log("");
    }
});
```

These empty meshes are due to treating `o` and `g` as the same tag, seen from this line [here](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/OBJLoader.js#L303).

Specifically, the offending meshes are those created by the OBJLoader whenever it parses an `o` tag. Looking inside the `.obj` file, we find that an `o` tag is always followed by a series of vertices, and before its scope can reach any faces, a `g` tag is encountered!

I believe part of the problem is that the [`.obj` file specification](http://www.martinreddy.net/gfx/3d/OBJ.spec) is very scarce when it comes to grouping, but here are the two sections for both `o` and `g` tags.

> g group_name1 group_name2 . . .
> 
>     Polygonal and free-form geometry statement.
> 
>     Specifies the group name for the elements that follow it. You can
>     have multiple group names. If there are multiple groups on one
>     line, the data that follows belong to all groups. Group information
>     is optional.
> 
>     group_name is the name for the group. Letters, numbers, and
>     combinations of letters and numbers are accepted for group names.
>     The default group name is default.
> 
> o object_name
> 
>     Polygonal and free-form geometry statement.
> 
>     Optional statement; it is not processed by any Wavefront programs.
>     It specifies a user-defined object name for the elements defined
>     after this statement.
> 
>     object_name is the user-defined object name. There is no default.

The sentence I find interesting is that `o` tags are "not processed by any Wavefront programs". Interestingly enough, this sentence is not present for the groups! So, since the `o` tag is not processed by any Wavefront programs, perhaps Three.js shouldn't process it either?

The name is rather strange too. If the `o` tag is for object names, one would think there can be at most one in an **object** file, but it seems like Blender exports always have several `o` tags.

---

##### Three.js version

- [x] Dev
- [x] r75

**Comment by jonnenauha** [comment]
I believe in earlier releases all `g` were ignored. If there were not `o` in the whole file, a single submesh was created and everything parsed to that. Otherwise each `o` encountered started a new submesh.

I suppose most exporters like Blender let's you define if it exports as `g` or `o` or even both. Blender itself seems to parse each `g` as a new mesh when you import.

Treating both as the same thing now looks like a breaking change. This is a bit worrying as code is easy to change when migrating but re-running your assets might be out of your control (e.g. distributed systems, user uploaded content). That might now break or create a lot more submeshes than earlier, which will impact rendering perf.

Maybe this should be a option in the parse function that default to what the behavior has been earlier. 

```
// defaults to this is options is passed
objLoader.parse(text, { ignoreGroups : true });
```

**Comment by jonnenauha** [comment]
Looking at this problem more closely in my PR work I think I understand this case a bit better.

The passing in of option to ignore `g` that I suggested above is not the best approach. The parser treats both `o/g` as a start of a new object. The vertex/normal/uv lines are parsed into a global state.

Vertex/normal/uv declarations are added as the parser progresses. Faces reference either absolute (positive numbers) or relative (negative numbers) from where the parser is at that point.

If there are `g/o` declarations that is not followed by any faces before a new `o/g` is declared, then its geometry is empty.

The parser now attaches also these empty geometry children to the returned container (THREE.Group). This is a bug and produces WebGL errors later on when rendering the scene. I have fixed this in my PR, empty geometry children are silently ignored.

In my opinion the new logic of treating both `o/g` should be kept (even if `g` was not handled in earlier releases). This will just increase the success rate of parsing the obj successfully as many exporters use groups or both objects and groups.

**Comment by pinkwerks** [comment]
> Most obj files afaik use o. 

Maya (via Autodesk via Wavefront, arguably is the reference implementation of OBJ as they created it) as well as Houdini are writing out 'g'. In the default case, loading OBJ's with and re-saving in either of these packages are writing out 'g'. Mentioned above if anything 'o' was optional. Regardless, missing support for 'g' (one or more) statements in a file is sorely missing.

**Comment by jonnenauha** [comment]
@pinkwerks well, as I just said both o/g are supported with the current loader. If you are on old three.js version youll need to upgrade. I'm not sure if the current loader is incompatible with older versions, but it might work just by throwing in the new ObjLoader.

I think this o/g stuff is a non issue now, both are supported. If you find bugs (in the latest version) please report them :)

**Comment by andreykaipov** [comment]
@jonnenauha I tried out your PR and it works great with my current project. After looking at several more `.obj` files, it does seem like `o` tags are used interchangeably with `g` tags. While confusing, I agree that it's best to support both. Thanks for improving the OBJLoader!

**Comment by pinkwerks** [comment]
@jonnenauha Turns out I ran across this using an older version and the real problem was unnamed groups which has been fixed. Thanks.
