### ISSUE TITLE
Shadow Clipped

### ISSUE THREAD

**Issue by MasterJames** [mrdoob/three.js#8384]
While on the topic of shadow glitches, I've noticed after I think adding physically based shadows this clipping occurring. As you move the object towards the spot light's falloff the shadow meets an abrupt end, which I think is square in shape.

![shadowclipped-01](https://cloud.githubusercontent.com/assets/1840183/13838545/2e01d730-ebd2-11e5-9bdf-e444f7b638c0.jpg)

I noticed it saying you need decay 2 for physically correct lights.
```
            castShadow: true,
            angle: 0.8,
            penumbra: 0.2,
            decay: 2,

```
Render settings are...

```
            type: "WebGLRenderer",
            shadowMap: {enabled: true, type: "PCFSoftShadowMap"},
            gammaInput: true,
            gammaOutput: true,
            antialias: true

```

and camera nothing odd there..
```
            type: "PerspectiveCamera",
            fov: 34, near: 0.1, far: 20000,

```

There's also a default ambient in the scene. The materials are not shared.

I'll try to conjure a simple fiddle it demonstrate as well, but maybe what's happened here will become obvious or easy to confirm without one.

##### Three.js version
I've just rebased yesterday to confirm. Well I'm just syncing without forking so I don't think it's technically rebasing at this point but it's merged with my minor insignificant tweaks.
- [x] Dev
- [x] r75
- [ ] ...

##### Browser

- [?] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

None.
NVIDIA GeForce GTX 780 Ti
Driver: 9.18.13.4709

**Comment by mrdoob** [comment]
Can you create a jsfiddle for this?

**Comment by bhouston** [comment]
When you say "physically-based shadows" are you referred to the "physicallyCorrectLights" option (which shouldn't have affected shadows unless I screwed up) or the penumbra changes, or something else?

**Comment by MasterJames** [comment]
Yes I'll try to do a fiddle. 
Yes I thought it might be since then ( physically correct lights - dacay is set to 2).
I also have the ground as a box with castShadows false and receiveShadows true.

**Comment by MasterJames** [comment]
Okay I finally banged out a fiddle for this sorry for the delay.
https://jsfiddle.net/MasterJames/gqwv4az9/

**Comment by WestLangley** [comment]
Ugh. The box is on the edge of the shadow camera's frustum. Make sure you set all the parameters, and do not rely on defaults.

https://jsfiddle.net/gqwv4az9/1/

**Comment by MasterJames** [comment]
Wow okay sorry still learning I guess. I noticed the documentation is now dated. It's still like this spotLight.shadowCameraFov as well which might have something to do with my confusion.

Shouldn't this be calculated as angle is set automatically by default? 
Is this the right way to calculate the value?

 `spt.shadow.camera.fov = (spt.angle * (360 / Math.PI));`

https://jsfiddle.net/MasterJames/gqwv4az9/4/

**Comment by bhouston** [comment]
We did talk about setting this automatically a few months ago.

Best regards,
Ben Houston
http://Clara.io Online 3d modeling and rendering

**Comment by MasterJames** [comment]
Thanks again for the help should have been for SO maybe? 
Would one prefer setter getter style of angle and as well as fov or is there some return a function trick?

**Comment by bhouston** [comment]
@MasterJames we did discuss having both controlled from a single parameter here: https://github.com/mrdoob/three.js/issues/7690
