### ISSUE TITLE
v75 [.CommandBufferContext]RENDER WARNING: Render count or primcount is 0

### ISSUE THREAD

**Issue by sashok1337** [mrdoob/three.js#8395]
Sorry, it was glitch on my side after ObjLoader update. After my code fixing everything works fine.
...

##### Three.js version

- [ ] Dev
- [x] r74
- [x] r75
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

**Comment by sashok1337** [comment]
Sorry, it was glitch on my side after ObjLoader update. After my code fixing everything works fine.

**Comment by rethink-rlinsalata** [comment]
As someone who also saw this error message, what was the problem you had / solution discovered?
It is likely something in my own code, but I also noticed it *appeared* to correlate to a Chrome update (running on Linux).

**Comment by sashok1337** [comment]
@rethink-rlinsalata Hi! 
I noticed, that in few situations my code creates a lot of Object3D instances with meshes, that are actually empty (without any geometry), and adds them to scene.
I've added additional validation in creating proccess - and fix this issue in this way :)

**Comment by mrdoob** [comment]
@sashok1337 you shouldn't have modified the original post, now we don't know what the issue was.

**Comment by cheton** [comment]
I ran into the same issue with this code while zooming in/out a 3D group that contains an empty THREE.Line object (i.e. vertexIndex is equal to 0).

```js
let geometry = new THREE.Geometry();
let material = new THREE.LineBasicMaterial({
    color: new THREE.Color(colornames('red')),
    linewidth: 1,
    opacity: 0.5,
    transparent: true
});
geometry.vertices = this.geometry.vertices.slice(0, vertexIndex);
this.group.add(new THREE.Line(geometry, material));
```

It works well after doing this check:
```js
if (vertexIndex > 0) {
    let geometry = new THREE.Geometry();
    let material = new THREE.LineBasicMaterial({
        color: new THREE.Color(colornames('red')),
        linewidth: 1,
        opacity: 0.5,
        transparent: true
    });
    geometry.vertices = this.geometry.vertices.slice(0, vertexIndex);
    this.group.add(new THREE.Line(geometry, material));
}
```

**Comment by DelvarWorld** [comment]
Found this question by Googling, I got this error from a mesh exported from blender. Two things I did which seemed to help, in Blender:

1. Select your object, go into edit mode, press `a` to select all faces, then press `w` and from the menu choose **Remove Doubles**. This will remove duplicate vertices.

2. Select your object, go into edit mode, press `a` to select all faces, then press `space`, and type "Select Loose Geometry", hit enter, then press `x` to delete anything selected, then click `vertices`. Press `x` again and select `edges`. Press `x` again and select `faces`. I don't know if its necessary to do all of these.

**Comment by ZachSaucier** [comment]
I got this issue when reusing an old geometry variable. Once I changed the name of the second use, it was fixed

**Comment by mrdoob** [comment]
@ZachSaucier Could you elaborate a bit?

**Comment by ZachSaucier** [comment]
When I faced this issue, my problem was reusing a variable name. 

I originally had:

```
var geometry	= new THREE.CylinderGeometry( 1, 1, 100, 32, 1, true );
var textureLoader = new THREE.TextureLoader();
var material;
textureLoader.load(
    "images/lines.jpg", 
    function(text) {
        // ...
        mesh = new THREE.Mesh( geometry, material );
        scene.add( mesh );
    } 
);

// ...

// This part caused the issue. Changing the variable name from here on fixed the issue
geometry = new THREE.Geometry(); 
geometry.vertices.push( /* Some points */ );
var lineMaterial = new THREE.LineBasicMaterial({ color: 0xff0000 });
plane = new THREE.Line(geo, lineMaterial);
scene.add( plane );
```

And changing the second geometry to another variable name fixed the issue

**Comment by bfanger** [comment]
Not sure if it's related to this issue but the [misc - controls / transform](http://threejs.org/examples/misc_controls_transform.html) example is also generating:
`RENDER WARNING: Render count or primcount is 0` .
when you switch to rotate mode (press <kbd>E</kbd>)

Macintosh OS X 10.11.6  /  Chrome 52.0.2743.82  /  THREE.WebGLRenderer 79

**Comment by mrdoob** [comment]
@bfanger thanks! I'll investigate.

**Comment by mrdoob** [comment]
Figured it out 😊
