### ISSUE TITLE
Document CanvasTexture

### ISSUE THREAD

**Issue by stevenvergenz** [mrdoob/three.js#8397]
##### Description of the problem

The class `THREE.CanvasTexture` exists as of r73, but is completely absent from the documentation. Please add at least a stub prototype function definition in there.
##### Three.js version
- [x] r73
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by aardgoose** [comment]
@mrdoob 
Documented by #10015 by @looeee
