### ISSUE TITLE
I created a RoundedRectagle geometry in case you find it useful

### ISSUE THREAD

**Issue by Jaredmmx** [mrdoob/three.js#8402]
It really is a 'COLISO', maybe you'd better call it as such.

```
THREE.RoundedRectGeometry = function (radius, length) {

    THREE.Geometry.call(this);

    this.type = 'RoundedRectGeometry';

    this.parameters = {
        radius: radius,
        length: length,
    };

    radius = radius !== undefined ? radius : 10;
    length = length !== undefined ? length : 60;

    circleGeometry = new THREE.CircleGeometry(radius, 32);
    rectangleGeometry = new THREE.PlaneGeometry(2 * radius, length - 2 * (radius), 32);

    var rectangle = new THREE.Mesh(rectangleGeometry);
    x = rectangle.position.x;
    y = rectangle.position.y;
    z = rectangle.position.z;

    var circle1 = new THREE.Mesh(circleGeometry);
    circle1.position.x = x;
    circle1.position.y = y - (length / 2) + radius;
    circle1.position.z = z;

    var circle2 = new THREE.Mesh(circleGeometry);
    circle2.position.x = x;
    circle2.position.y = y + (length / 2) - radius;
    circle2.position.z = z;

    THREE.GeometryUtils.merge(this, circle1);
    THREE.GeometryUtils.merge(this, rectangle);
    THREE.GeometryUtils.merge(this, circle2);
};

THREE.RoundedRectGeometry.prototype = Object.create(THREE.Geometry.prototype);
THREE.RoundedRectGeometry.prototype.constructor = THREE.RoundedRectGeometry;
```

**Comment by EvilPeanut** [comment]
Hi @Jaredmmx!

I haven't tested you're code, but I think i'm fairly clear with what you have added here and it looks okay :smile:. Creating a rounded rectangle geometry may be a fairly uncommon task in Three.js so we will have to ask @mrdoob and the community whether they want it added.

I would suggest that you:
1. Format your code properly, see http://zz85.github.io/mrdoobapproves/
2. Fork Three.js and create a pull request with this code

Happy coding!

**Comment by WestLangley** [comment]
There is an example of a rounded rectangle in http://threejs.org/examples/webgl_geometry_shapes.html

**Comment by Mugen87** [comment]
@mrdoob I think we can close this issue. Our [webgl_geometry_shapes](http://threejs.org/examples/webgl_geometry_shapes.html) example shows that it's straightforward to create a rounded rectangle with existing functionality (`THREE.Shape`).
