### ISSUE TITLE
ObjLoader low hanging fruit optimizations

### ISSUE THREAD

**Issue by jonnenauha** [mrdoob/three.js#8404]
##### Description of the problem 

I was suprised to see some of the implementation details of `ObjLoader.parse`.

- Creating [9 regex's](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/OBJLoader.js#L198-L220) per call. Granted this wont give big impact, but why pay this cost of each parse invocation with no benefit?
 - These could be simply moved to be created once in a closure and reused (like three.js uses [all around the codebase](https://github.com/mrdoob/three.js/blob/master/src/math/Vector3.js#L239-L259)).
- Creating some regex again for [each line in the file](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/OBJLoader.js#L322-L328). Granted these might be executed quite rarely as the most common lines are handled first.
 - Simply define once and move to the same place above item mentions.

Running 3-4 regex when a simple single character check would eliminate the group.

```js
if ( ( result = vertex_pattern.exec( line ) ) !== null )
    // ["v 1.0 2.0 3.0", "1.0", "2.0", "3.0"]
else if ( ( result = normal_pattern.exec( line ) ) !== null )
    // ["vn 1.0 2.0 3.0", "1.0", "2.0", "3.0"]
else if ( ( result = uv_pattern.exec( line ) ) !== null )
    // ["vt 0.1 0.2", "0.1", "0.2"]
```

where you could simply do `v` and `f` check to skip a lot of redundant checking. Note that the regexps are already checking `^` start of line anchor and the line is trimmed, so there should be no downside to this.

```js
var line = lines[ i ].trim();
var lineFirstChar = line.charAt( 0 );
...
if (lineFirstChar === "v") {
  // 3x v prefixed regex
} else if (lineFirstChar === "f") {
  // 4x f prefixed regex
}
```

I'm just wondering why haven't these simple gains been implemented? I understand the code lives in "examples" but it is probably the defacto way for most apps out there to just include it in their project and use it as is.

I actually made these changes to an old three.js version and did get some speedups for large files in especially.

##### V8

There is also a bigger issue in general for V8. If you run just a few large files through the parse function, it gets optimized and deoptimized too many times and chrome profiler tells you "Not optimized: Optimized too many times" and links to [this issue](https://github.com/GoogleChrome/devtools-docs/issues/53). It looks like it has something to do with constant opt/deopt cycles and finally V8 gives up on the optimizations. This is when parsing files gets a lot slower (even with my proposed tweaks).

There is that hydra tool that might help to debug what the underlying cause it, it seems V8 loses the actual reason somewhere and cant display it (why it got deopted multiple times).

Looking at the code it might be those functions that get created for each invocation. My hunch is that `addFace` can be called with various number of parameters. The function then internally handles this fact and does the right thing. But afaik V8 gets confused due to this, sometimes `na, nb, nc, nd` are numbers and something they are undefined.

As said the hydra tool might give more info, but might be just quicker to create specialized functions for each parameter set and see if it improves.

Additionally these functions could also be reused, just by passing the needed object etc. info into them, but that would be a bigger change. I'm not sure if the deopt reason might also be that they are modifying closure params e.g. `object.geometry.uvs.push`.

##### Three.js version

- [x] Dev

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by jonnenauha** [comment]
Also if these look ok I can try to implement the changes myself as a PR.

**Comment by mrdoob** [comment]
> Also if these look ok I can try to implement the changes myself as a PR.

That would be great! 😊

**Comment by jonnenauha** [comment]
Fixed with https://github.com/mrdoob/three.js/pull/8443
