### ISSUE TITLE
Example "webgl_terrain_dynamic" not working correctly

### ISSUE THREAD

**Issue by Mugen87** [mrdoob/three.js#8405]
##### Description of the problem 

[webgl_terrain_dynamic](http://threejs.org/examples/webgl_terrain_dynamic) has some serious issues. The corresponding shader in [examples/js/ShaderTerrain.js](https://github.com/mrdoob/three.js/blob/master/examples/js/ShaderTerrain.js) is not compiling, the code is outdated and requires refactoring.

Besides, i think the example itself is way too complex. The code should concentrate on dynamic terrain generation and ignore post-processing, animation and complex lighting. 

##### Three.js version

- [x] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
> Besides, i think the example itself is way too complex. The code should concentrate on dynamic terrain generation and ignore post-processing, animation and complex lighting.

Agreed!
