### ISSUE TITLE
LensFlare documentation quick update please

### ISSUE THREAD

**Issue by that-ben** [mrdoob/three.js#8407]
##### Description of the problem 

Hi, I searched for nearly 1 hour why my integration of LensFlare example code AS IS to my existing app was not displaying any lens flares (at all, nothing).  This module requires the WebGLRenderer construction to have the "alpha" parameter set to TRUE or else no lens flare is visible.

`renderer = new THREE.WebGLRenderer( { alpha: true } );`

Please add this requirement to the LensFlare documentation page at least! Thanks :-)

**Comment by mrdoob** [comment]
> Please add this requirement to the LensFlare documentation page at least!

Would you be up for helping out with that?

https://github.com/mrdoob/three.js/edit/dev/docs/api/objects/LensFlare.html

**Comment by that-ben** [comment]
Problem is: I have never forked or edited anything, so I don't know how.  That's why since it's just a simple sentence to put in the documentation, maybe anybody having access to it could quickly edit the page and be done with it? :P

**Comment by mrdoob** [comment]
It's easy!

1. Click on the link I gave you
2. Make the text modification.
3. Click [Commit changes]
4. Make people happier 😊

**Comment by that-ben** [comment]
Done... altough I'm unsure why (tried 2 times) it removes 80 lines and creates 85... WTF? I only added 5 lines :P

https://github.com/mrdoob/three.js/pull/8411

**Comment by that-ben** [comment]
...and the final result of that LensFlare on a solid real time dynamic terrain with physics running +60fps on desktop and +40fps on iPhone5 :)

![dat-lens-flare](https://cloud.githubusercontent.com/assets/13210399/13895944/dab6d0a4-ed51-11e5-9e36-0d4c94607905.png)
