### ISSUE TITLE
THREE.Object3D traverse method recursive argument.

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#8408]
Three.js version r75

##### Description of the problem 

There is no option for a recursive param in the traverse method inside `THREE.Object3D`. I remember that there was a recursive argument before (if I am not mistaken). What happened to this parameter? Can it be reintroduced?

Something like this:

	traverse: function ( callback, recursive ) {
		callback( this );
		if ( recursive === true ) {
			var children = this.children;
			for ( var i = 0, l = children.length; i < l; i ++ ) {
				children[ i ].traverse( callback );
			}
		}
	},

**Comment by Wilt** [comment]
I tried to find in which version it was still used, but I am unable to find it...

**Comment by WestLangley** [comment]
Why would you call a `traverse()` method if you do not want to traverse?

**Comment by Wilt** [comment]
Oops. I want to traverse only first children... But I see this won't work. My bad.
