### ISSUE TITLE
MeshDepthMaterial on CanvasRenderer, rendering white.

### ISSUE THREAD

**Issue by zettam** [mrdoob/three.js#8418]
##### Description of the problem 
MeshDepthMaterial is not rendering with CanvasRenderer.js

##### Three.js version

- [ ] Dev
- [X] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
`MeshDepthMaterial` is supported by `WebGLRenderer` only.

**Comment by zettam** [comment]
Oh, okay,.
