### ISSUE TITLE
Optimization of EventDispatcher

### ISSUE THREAD

**Issue by MasterJames** [mrdoob/three.js#8419]
##### Description of the problem 

I've highlighted a secondary notion from my revised PR for Object3D index referencing, about the EventDispatcher.
https://github.com/mrdoob/three.js/compare/dev...MasterJames:patch-4

The second loop was redundant as well as function local storage array and other listener variable.
It's really no addition just deletions. Should be smaller, faster, cleaner, better.

Otherwise I was wondering why that would be better to have the two loops?

...

##### Three.js version

- [x] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Hmm, PRs for `EventDispatcher` should go to its own repo...
https://github.com/mrdoob/eventdispatcher.js/

**Comment by gero3** [comment]
There is a reason why the array needs to be cloned. This allows the events to be removed while in handling the event itself. Otherwise it will skip a method.
