### ISSUE TITLE
THREE.js r74 to r75 migration findings

### ISSUE THREAD

**Issue by verteAzur** [mrdoob/three.js#8425]
No problem nor warning encountered, the migration went very smooth. We will continue the testing throughout this week, but thus far the migration was 100% backward compatible.

Yes, this is a first, knowing there were thousands of contributions. Hopefully we will have the same behaviour with the coming migrations ;)

Thanx for the stability and the hard work. Much love and respect goes to all of you out there!

##### Three.js version
- [x] r75

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
> Hopefully we will have the same behaviour with the coming migrations ;)

We'll try! 😊

**Comment by makc** [comment]
Sigh... and here I have to migrate from r71.

**Comment by verteAzur** [comment]
All is fine after 1 week, time to close this post... Thank you for all!

makc: you should be able to migrate directly from r71 to r75, the following doc will help you out: https://github.com/mrdoob/three.js/wiki/Migration

**Comment by makc** [comment]
@verteAzur however, no migration guide helps with removed features. like shadow only flag on the light, for example (setting light color to 0 is having similar effect still, so I'm fine)

**Comment by makc** [comment]
...in fact, that is probably a bug ) shadow should not be any darker than its surrounding in this case, yet it is.

**Comment by mrdoob** [comment]
@makc do you have a jsfiddle for that?

**Comment by makc** [comment]
@mrdoob ah, but I like this bug, and [my project relies on it](https://xkcd.com/1172/).... ok, ok, [here it goes](http://jsfiddle.net/akmcv7Lh/41/)

**Comment by WestLangley** [comment]
@makc Shadows for `MeshLambertMaterial` are not correct. This is known. Use `MeshPhongMaterial` for your plane.

http://jsfiddle.net/akmcv7Lh/42/

**Comment by makc** [comment]
@WestLangley ah good to know it will stay there for some time :stuck_out_tongue_closed_eyes:
