### ISSUE TITLE
Collada MultiMaterial is Broken in r75 (r73 is OK)

### ISSUE THREAD

**Issue by DmitryFX** [mrdoob/three.js#8426]
##### Description of the problem

Hello.
I'm using ColladaLoader for loading .DAE's.
I have an object with 2 materials applied.
Since the version r75 (and r76 DEV) three.js simply fills the object with the single material, which has index = 0.
But three.js knows, that this object has more than one material and knows their indices. More of that - it still stores the appropriate materials for the according faces.

Also tried Software and Canvas renderers with the same result.

I made a simple test, look at the console there. Or look at the screenshot below.
Can't upload ZIP, so here is the link: https://yadi.sk/d/TNwJ0GpjqMwDm
And yes - the cube is fully red (that wasn't a good idea to use the cube for the screenshot:))
![scr](https://cloud.githubusercontent.com/assets/17983905/13922255/86ed2508-ef8c-11e5-8963-420ae839aa76.PNG)

Thanks!

...
##### Three.js version
- [ +] Dev
- [+ ] r75
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
##### Hardware Requirements (graphics card, VR Device, ...)

Different.

**Comment by WestLangley** [comment]
In your test example, `obj.geometry.faces[ i ].materialIndex` is zero for all faces of the cube.

Related: #778

**Comment by DmitryFX** [comment]
Yes. Different daeMaterials and 0 indices. And what is the solution? The scene was working properly on r73. And if I import this. dae back into Blender, everything works as it should.

**Comment by schubboy** [comment]
I can confirm that Dmitry is correct.  All faces imported by the current Collada loader have their material Index set to 0, despite the information being correctly inside the dae file.  I created a simple box in 3DsMax, assigned a simple red and green material to several different faces, and exported it out to dae.  ThreeJS sees only the material in the 0 slot, but opening the file in Blender, or Max, correctly shows the faces as different colors.

**Comment by schubboy** [comment]
and this seems to be the fix, (but don't quote me on it):

In the "ColladaLoader.js" file:
Take the for loop on line 4656 from version r73 and paste it under line 1173 in version r75

Multi-Materials appear to work (at cursory glance) with that line in there.

**Comment by Mugen87** [comment]
Multi-Materials should work correctly in `ColladaLoader2`.
