### ISSUE TITLE
Raycaster not working properly with scaled Sprites

### ISSUE THREAD

**Issue by mauriciomassaia** [mrdoob/three.js#8430]
##### Description of the problem 

I am trying to use THREE.Raycaster to show an html label when the user hover an object. It works fine if I use THREE.Mesh but with THREE.Sprite it looks like that there is a space that increases with the scale of the object.

Please check the [StackOverflow question](http://stackoverflow.com/questions/36123458/three-raycaster-not-working-properly-with-scaled-three-sprite) for full explanation and [demo](https://plnkr.co/edit/J0HHFMpDB5INYLSCTWHG?p=preview).

As @WestLangley [would consider this a bug](http://stackoverflow.com/a/36124239/2909645) I am reporting it here.

Thanks 
...

##### Three.js version
- [x] r75

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
- [x] OS X

**Comment by WestLangley** [comment]
See #8424

**Comment by mauriciomassaia** [comment]
Im sorry for the dup. Cheers
