### ISSUE TITLE
Some glTF scenes slow performance significantly when used with VREffect

### ISSUE THREAD

**Issue by xirvr** [mrdoob/three.js#8431]
##### Description of the problem

When using VREffect and the glTF loader, calling glTFShaders.update() on the update loop, frame rate drops to around 2fps.  This is only seems to be an issue with large glTF files (the one I'm using is 2.4mb not including shaders, which are small / simple).  Not loading the glTF shows the skybox correctly, and the OrbitControls are smooth (nothing else is being included / loaded).

Removing scene.updateMatrixWorld() from glTFShaders update resolves the issue with no apparent side effects: https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/gltf/glTFShaders.js#L95 

I also noticed VREffect's render calls scene.updateMatrixWorld() as well, but removing this one doesn't solve the issue.

NOTE: I have not tried (this bug) with a HMD hooked up, nor have I looked at the WebVR 1.0 updates -- I'm only using the VREffect as a renderer passthrough (VR mode was working as expected on simple models when testing several weeks ago).

If the updateMatrixWold isn't needed in the glTFShaders update I can make a PR, but I don't know enough about this level of the library to say for sure this isn't my app code or glTF.
##### Three.js version
- [ ] Dev
- [x] r75
- [ ] ...
##### Browser
- [x] All of them
- [x] Chrome
- [x] Firefox
- [?] Internet Explorer
##### OS
- [x] OS X
- [?] All of them
- [?] Windows
- [?] Linux
- [?] Android
- [?] IOS
##### Hardware Requirements (graphics card, VR Device, ...)

MacBook Pro (Retina, 15-inch, Mid 2015)
2.8 GHz Intel Core i7
16 GB 1600 MHz DDR3
AMD Radeon R9 M370X 2048 MB

**Comment by mrdoob** [comment]
Why do you need to call `glTFShaders.update()` every frame?

/ping @tparisi

**Comment by xirvr** [comment]
I'm mostly running from: https://github.com/KhronosGroup/glTF/blob/master/loaders/threejs/index.html#L368

I did try to move that call from the animation loop to the init, but then the glTF scene is stuck at it's initial view / position / look / etc (while the rest of the app works as expected).

**Comment by tparisi** [comment]
`glTFShaders.update()` is how the uniform values are updated. They need to be kept up to date with the simulation's current values, which may have changed e.g if the scene is animating, or based on changes from user input.

I'm not keeping track of whether or not values have changed since the last frame, which would be an important optimization.

**Comment by donmccurdy** [comment]
Is `scene.updateMatrixWorld()` the bottleneck? It's invoked once per shader. There shouldn't be any need for that with a global `update()` hook:

```js
THREE.GLTFLoader.Shaders.update( scene, camera );
```

If that's the recommended way to invoke a shader update, let's move `scene.updateMatrixWorld()` out of the per-shader loop.
