### ISSUE TITLE
Firefox shows only a quarter of the canvas area on large sizes

### ISSUE THREAD

**Issue by rustedwolf** [mrdoob/three.js#8435]
##### Description of the problem 

I'm having trouble with panoramic image display. It worked fine earlier. The library shows up only quarter of the view when in full screen. Thus on smaller screens it's okay.
The console logs are:
```
Error: WebGL: drawArrays: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once) ....three.min.js:671:105
THREE.WebGLRenderer: image is too big (4096x2048). Resized to 1024x512 <img src="textures/2294472375_24a3b8ef46_o.jpg"> ....three.min.js:620:1
Error: WebGL: Requested size 1280x703 was too large, but resize to 640x351 succeeded. .... three.min.js:638:421
```
![screenshot at 2016-03-22 11 58 28](https://cloud.githubusercontent.com/assets/1105392/13949626/63537698-f026-11e5-9a18-f8337782e493.png)

##### Three.js version

- [ ] Dev
- [x] r75

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

##### Hardware 
Intel GMA 900 graphics card

**Comment by RemusMar** [comment]
> Intel GMA 900 graphics card 

Use a decent GPU and try again.
I don't have any issue with the latest Firefox and 4096x2048 spherical maps on 3 different computers (Nvidia GPUs).

**Comment by rustedwolf** [comment]
> Use a decent GPU and try again.
Well it would be very generous of you, if you could provide me and other website visitors with one. But still we couldn't do anything with it, because many of them have an integrated GPU in their laptops.

**Comment by Mardonis** [comment]
Do you have the latest drivers installed for your graphics card?

**Comment by RemusMar** [comment]
> many of us have an integrated GPU's in our laptops.

Sorry but that GMA 900 is an 11 years old DirectX 9 piece of crap ...
Anyway, the example on threejs.org is quite messed up.
Try this one:
http://necromanthus.com/Test/html5/park.html 
It runs much better (including the mouse wheels).
If you get the same 1/4 view, you need to escape from Jurasic. :laughing: 
cheers

**Comment by rustedwolf** [comment]
> Do you have the latest drivers installed for your graphics card?

Everything Linux Mint 17.3 repositories can provide. 
As I've mentioned, it was running **fine** on Firefox last month, it runs fine in Chromium now.
What am I concerned is I don't know how many of low-budget users has the same problem.

**Comment by Mugen87** [comment]
@rustedwolf Can you please post the WebGL capabilities of your system (see: https://www.browserleaks.com/webgl)? Besides, i've found the places where FF logs the mentioned warnings (see [here](https://hg.mozilla.org/releases/mozilla-aurora/file/tip/dom/canvas/WebGLContextDraw.cpp#l521) and [here](https://hg.mozilla.org/releases/mozilla-aurora/file/tip/dom/canvas/WebGLContext.cpp#l713)). Maybe the information about your WebGL capabilities help to explain logging. I'm especially interested in your framebuffer stats...

**Comment by rustedwolf** [comment]
@Mugen87 sure thing:

WebGL Support Detection:
- WebGL support: **Yes**
- WebGL enabled: **Yes**
- WebGL 2.0 support: **No**

WebGL Context Info:
- Supported Context Name(s): webgl, experimental-webgl
- GL Version: WebGL 1.0
- Shading Language Version: WebGL GLSL ES 1.0
- Vendor: Mozilla
- Renderer: Mozilla

Fragment Shader:
- Max Fragment Uniform Vector: 4096
- Max Texture Image Units: 8
- Float/Int Precision:	 highp/highp
- Best Float Precision: \[-2^127, 2^127\] (23)

**Comment by Mugen87** [comment]
Thank you @rustedwolf

I think this value causes your problem: **Max Render Buffer Size: 1024**

In WebGL the size of the viewport (or the associated WebGL canvas) can differ from the maximum size of your render/drawing buffer. I assume that the latest FF handles this situation different than earlier version. FF 45 resizes the dimensions of the buffer until width/height are less than or equal to the maximum size of the render buffer (in your case 1024). This explains the following warnings:

> Error: WebGL: drawArrays: Drawing to a destination rect smaller than the viewport rect.
> Error: WebGL: Requested size 1280x703 was too large, but resize to 640x351 succeeded.

To avoid these warnings you must do the resize in your application. So before you set the size of the renderer, you check if the values of width and height are greater than `MAX_RENDERBUFFER_SIZE`. If so, you need to cap width and height. Be aware to preserve the original aspect ratio. After setting the size to the renderer, you can scale the canvas via CSS to fullscreen (but this step is optional).

Maybe something like this...

```javascript
// some defaults
var width = window.innerWidth;
var height = window.innerHeight;
var pixelRatio = window.devicePixelRatio;

// get access to WebGL context
var gl = renderer.context; 

// retrieve size
var maxRenderBufferSize = gl.getParameter( MAX_RENDERBUFFER_SIZE ); 

// check if resize is needed. unfortunately you must regard the devicePixelRatio
if( ( width * pixelRatio ) > maxRenderBufferSize || ( height * pixelRatio ) > maxRenderBufferSize ) {

    // do resizing. i think this must be done recursively

} 
 
renderer.setSize( width, height );
```

Besides, i'm not sure if maybe three.js should do some work here. What's your opinion?

**Comment by RemusMar** [comment]
> I think this value causes your problem: Max Render Buffer Size: 1024 

Any decent GPU is capable of 8192.
On the other hand, if you use1024x512 textures for Spherical Maps you'll get bad results.
The bottom line: Intel GMA 900 is not suitable for WebGL.
cheers

**Comment by rustedwolf** [comment]
@Mugen87 Well, I think you're right. That's not the three.js's problem. I'm closing this issue.

**Comment by kdamar3** [comment]
I have similar problem in Mozilla Firefox with half of the canvas size being truncated where as chrome/opera browsers are rendering the whole scene fine. 

My hardware details:
Graphics card : NVIDIA GeForce-GT-730m
Processor: Intel Core i5-4300M CPU with 2.60GHz

If it is because of graphics card, why other browsers are rendering fine ?

**Comment by Mugen87** [comment]
It has to do with your graphics card and the way, how browsers handle the mentioned situation (limited render buffer size). If you get the same warnings like @rustedwolf, read this comment for more information https://github.com/mrdoob/three.js/issues/8435#issuecomment-200282852

**Comment by kdamar3** [comment]
Hi, Thank you. Unfortunately, i cannot resize the canvas. i am increasing the width of canvas depending on user input. My scene looks squeezed missing clarity of text dom content mixed within the scene if i do that.

**Comment by mrdoob** [comment]
@kdamar3 you should report this to Mozilla directly.

**Comment by GitHubDragonFly** [comment]
Even though this issue was closed long time ago, the very first error from the 1st post has resurfaced with r162:

Error: WebGL: drawArrays: Drawing to a destination rect smaller than the viewport rect.

It is sufficient to just load the three.js editor in Firefox and the error shows, at least for me.

r161 does not produce this error.

**Comment by Mugen87** [comment]
I don't see the error on my system (macOS 14.3.1, Firefox 123).

This is not something than we can fix in `three.js`. Please redirect the report to Mozilla.

**Comment by GitHubDragonFly** [comment]
@Mugen87 my post was more of an FYI in case somebody else reports it.

It is not really an error so I did edit my previous post to show the actual warning, which does not appear to affect the overall functionality of the library.

This warning is tripped by some code changes in r162 since it does not appear with r161.

I have no concern over this but Mozilla should consider fixing their browser since Chrome does not seem to have an issue with r162.

**Comment by GitHubDragonFly** [comment]
@Mugen87 just as another FYI, there is no warning in Firefox on Debian Linux so it could just be a combination of hardware and Windows on my end that is getting tripped with r162 (in spite of r161 working fine).

If you do get anyone else report the same warning then at least you have this topic to direct them to.

**Comment by Mugen87** [comment]
Thanks for sharing this information. But even when devs encounter this topic it eventually leads to nowhere to continue the discussion here. 

Since you are able to reproduce the issue on your system, please report at https://bugzilla.mozilla.org/home and then share the link here.
