### ISSUE TITLE
JSONLoader: onLoad is not a function

### ISSUE THREAD

**Issue by Peregrine2976** [mrdoob/three.js#8440]
##### Description of the problem 

Attempting to load an external JSON mesh using the JSONLoader returns a console TypeError: 

TypeError: onLoad is not a function                three.js:18294:4
    THREE.JSONLoader.prototype.load/<()            three.js:18294
    THREE.XHRLoader.prototype.load/<()             three.js:18010

Issue encountered using Three.js's own example for how to use the JSONLoader (http://mrdoob.github.io/three.js/docs/#Reference/Loaders/JSONLoader).

##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

**Comment by onepopcorn** [comment]
Hi.

I still having the same problem with **r81**. If I try to use the **JSONLoader** with a **LoadingManager** console throws `Uncaught TypeError: onLoad is not a function`.

`onLoad` method only works when passed as a param to the **JSONLoader**'s `load` method. Curiosly `onProgress` & `onStart` works as expected. 

Am I missing something? Is this a known bug?

Thanks!

Tested on Chrome with Windows 10.
