### ISSUE TITLE
Texture UV with THREE.Points

### ISSUE THREAD

**Issue by rock7-dan** [mrdoob/three.js#8441]
##### Description of the problem 
I was hoping to use a single large "sprite sheet" texture with THREE.Points to be able to show different sprites against each point (by varying the UV coordinates). As a performant way of showing lots of fixed sized icons (i.e. markers being shown on Google maps).

However, it's not working as I'd assumed (hoped!). The snippet below is functional, however the UV coordinates are not being adhered to. I've scanned over the points shaders and AFAIK its not implemented in this way - which explains the issue!

Are these assumptions correct, if so, would there an appetite for this kind of capability to be added?

```
var iconSheet = new THREE.TextureLoader().load("icons.png");

var mat = new THREE.PointsMaterial({
	size: 16,
	transparent: true,
	sizeAttenuation: false,
	map: iconSheet
});

var g = new THREE.BufferGeometry();

//Populate positions/uv here

g.addAttribute('position', new THREE.BufferAttribute(positions, 3) );
g.addAttribute('uv', new THREE.BufferAttribute(uv, 2) );

var mesh = new THREE.Points(g, mat);
```
##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
I think the best solution in your case is to use a custom `ShaderMaterial`, replacing `PointsMaterial`.

**Comment by simonThiele** [comment]
Hey @rock7-dan I done the same a few weeks ago with much success. Let me prepare an example for you

**Comment by simonThiele** [comment]
here it is: http://jsbin.com/voxuxijosi/ If you use this texture https://www.dropbox.com/home?preview=glyphTexture.jpg the result should look like this:
![screen shot 2016-03-23 at 09 22 30](https://cloud.githubusercontent.com/assets/10807661/13979451/e5de9338-f0d8-11e5-97d5-60943b969e00.png)

**Comment by simonThiele** [comment]
btw: https://www.eventbrite.com/engineering/its-2015-and-drawing-text-is-still-hard-webgl-threejs/

**Comment by rock7-dan** [comment]
Many thanks @WestLangley @simonThiele for the pointers this approach worked perfectly!

**Comment by backspaces** [comment]
@simonThiele  This didn't work for me, sent me to my own DB account!
> https://www.dropbox.com/home?preview=glyphTexture.jpg

.. and the jsbin for some reason fails. Do I just need to get your jpg and put it somewhere the jsbin can find it? I.e. replace `image.src = 'YOUR_TEXTURE_HERE';` with glyphTexture.jpg?

I found this: 
> http://stackoverflow.com/questions/29526855/how-to-do-uv-mapping-on-a-threejs-sprite-r71

Is it the method you are using? Looks really sweet!

**Comment by looeee** [comment]
Well I just tried to look at the jpeg and got a 'you need to be signed in to Dropbox to view this' error. Could that be the problem?

**Comment by backspaces** [comment]
​Yeah, its a url that only works for the owner of the dropbox account
unless its made universally accessible,  And even then I think they use
"public" urls.

**Comment by simonThiele** [comment]
Hey @backspaces. Yeah, this link doesn't work anymore, since I deleted the resources (because this issue is closed)
