### ISSUE TITLE
Matrix3 getInverse affecting qunit tests for Three.js

### ISSUE THREAD

**Issue by MasterJames** [mrdoob/three.js#8449]
##### Description of the problem 
When running this unit test
http://127.0.0.1:8080/test/unit/unittests_three.html?hidepassed
I see
```
Matrix3: getInverse (13, 22, 35) Rerun                              @17 ms

Passed!                       @ 7 ms
Expected: 	
Source: 	
    at http://127.0.0.1:8080/test/unit/qunit-1.18.0.js:1908:13
    at Object.<anonymous> (http://127.0.0.1:8080/test/unit/math/Matrix3.js:185:3)
    at Object.Test.run (http://127.0.0.1:8080/test/unit/qunit-1.18.0.js:895:28)
    at http://127.0.0.1:8080/test/unit/qunit-1.18.0.js:1024:11
    at process (http://127.0.0.1:8080/test/unit/qunit-1.18.0.js:583:24)
    at begin (http://127.0.0.1:8080/test/unit/qunit-1.18.0.js:628:2)

```

And in the console the warnings show the issue. "Determinant is Zero!"

```
THREE.Matrix3.getInverse no longer takes a Matrix4 argument.
three.js:4667 THREE.Matrix3.getInverse(): can't invert matrix, determinant is 0
```
...

##### Three.js version

- [x] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by MasterJames** [comment]
I later recalled thinking this was noted in the PR by the creator at the time, but said nothing to worry about. There just Passed as warnings caused by the depreciation warning and expected, but maybe there's a switch for that in the QUnit spec. ?

https://api.qunitjs.com/QUnit.config/

`QUnit.config.hidepassed = true;
`
should do it, no?

**Comment by MasterJames** [comment]
I think I recall noting it was mentioned before when the original poster of the PR making the tests said it was unavoidable. ?

**Comment by MasterJames** [comment]
Tracing... the problem seems to be?
This doesn't return anything...

```
THREE.Matrix3 = function () {

	this.elements = new Float32Array( [

		1, 0, 0,
		0, 1, 0,
		0, 0, 1

	] );

	if ( arguments.length > 0 ) {

		console.error( 'THREE.Matrix3: the constructor no longer reads arguments. use .set() instead.' );

	}

};

```
while the test does expect something to be equal to 1

```
test( "constructor", function() {
	var a = new THREE.Matrix3();
	ok( a.constructor() == 1, "constructor 1 Passed!" );

```
I've added some more definitive labels on the ok() functions to track this down as well.

Anyway I didn't understand it thought maybe this was intended instead

`	ok( a.constructor != undefined, "constructor 1 Passed!" );`

Anyway that's just the first one.

**Comment by MasterJames** [comment]
All these determinate is zero tests seem maybe bogus now and should be fixed or deleted! No?

**Comment by tschw** [comment]
> `THREE.Matrix3.getInverse no longer takes a Matrix4 argument.`

^^^ That's the relevant one. The unit test needs an update (PR #8477).

> `three.js:4667 THREE.Matrix3.getInverse(): can't invert matrix, determinant is 0`

@MasterJames 
> All these determinate is zero tests seem maybe bogus now and should be fixed or deleted! No?

No. The matrix is read with the wrong element stride (the method expects a `Matrix3` now, but the unit test pases a `Matrix4`) and under this interpretation turns out to be singular. After the first message we're in the land of undefined behavior - and maybe we should turn the warning into an error to emphasize that.

**Comment by MasterJames** [comment]
So I just meant we switch those "tests" that currently fail to their opposite equality, so "yes it's a good fail"? That shouldn't happen anymore and it's good now?".
I also wondered about how the labels all say "passed" when they fail, but thought maybe they should be descriptive of the test no? Initially I had trouble tracking down which test was failing.

**Comment by MasterJames** [comment]
Thanks it's merged.

**Comment by tschw** [comment]
> I also wondered about how the labels all say "passed" when they fail, but thought maybe they should be descriptive of the test no? Initially I had trouble tracking down which test was failing.

I think that's supposed to mean the test failed to pass. If you want it to say something else you have to pass a message to `ok` or use one of the `equals` functions, IIRC.

**Comment by MasterJames** [comment]
I see thank you for the explanation.

**Comment by MasterJames** [comment]
Ya tests are actually new for me. In the community it makes more sense to me to use them.

Quinit test for ok
https://api.qunitjs.com/ok/

second argument  'message' is a String with "A short description of the assertion".

"Passed" is not the right thing to put there. You really only see it when it fails.
