### ISSUE TITLE
feature: expose GridHelper arguments

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#8451]
like this.getSize = function () { return side; } etc

so we do not have to store them on app side?

**Comment by Mugen87** [comment]
There are other helper classes (e.g. `AxisHelper`), who don't expose their parameters, too. If we change `GridHelper`, we should adjust all helpers to ensure consistency.

**Comment by makc** [comment]
Alternatively you could just not overwrite `.constructor`
