### ISSUE TITLE
GridHelper clone is broken

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#8452]
it has constructor = THREE.GridHelper but inherited clone method expects constructor property to be LineSegments

**Comment by makc** [comment]
btw, this can be fixed by adding GridHelper's own clone if my other request #8451 is granted ) or by having clone on instance, not the prototype

**Comment by Mugen87** [comment]
Because #15981 was reverted, cloning a `GridHelper` applies wrong arguments to the ctor again.

**Comment by Mugen87** [comment]
`GridHelper` should maybe look more like in this fiddle so it's easier to copy/clone and serialize/deserialize it: https://jsfiddle.net/kjb46s8y/
