### ISSUE TITLE
Status of THREE and suitability for browser interactivity

### ISSUE THREAD

**Issue by mwpowellhtx** [mrdoob/three.js#8453]
Not a problem description, per se, more like a couple of introductory questions. It's been asked before, but there is interest in a Google Group. It's easy to setup, and is a helpful way to engage, and to keep issue clutter down.

That said, I've got a configuration for which I've built a series of wizard steps that walk a user through configuration progressively, step by step. I'd like to connect that detail with a 3D model representing that configuration.

The trick will be, listening for changes during the user input and responding to sensible changes by updating corresponding 3D objects, while ignoring non-sensible changes.

Currently, the web site is based around _ASP.NET MVC_ and post backs to a _Controller_ while stepping through the wizard. That much is basically working but for unrelated CSS issues. I could change that up a bit, but it's basically working and am happy with it.

I am considering connecting something like a _Knockout_, or even _React_, in order to respond to input changes. Presumably I should have captured some sort of _Json_ object in the page's script that represents enough state that the model can be calculated, and rendered.

I gather it should be simple enough to connect some event handlers on the controls, perhaps via the _Html_ helper _htmlAttributes_ parameter.

The key here is how I might go about bridging the gap between change in configuration and change in 3D visualization in a more or less interactive manner.

I don't know if that makes sense, or if it's even been thought of before; I assume someone has entertained the concept and learned something.

Thank you...

**Comment by mrdoob** [comment]
Anyone is free to create/maintain the Google Group. Sorry, but this section is for bug reports or feature requests.

**Comment by mwpowellhtx** [comment]
You have a discussion area somewhere?

**Comment by mrdoob** [comment]
I focus on the development, I leave the discussions boards to the community but IRC is the closest thing I'm aware of...
