### ISSUE TITLE
Which models are supported

### ISSUE THREAD

**Issue by mwpowellhtx** [mrdoob/three.js#8454]
Wanting to gain an idea what sort of models are supported.

My analog frame of reference is [Helix Toolkit 3D](http://github.com/helix-toolkit/helix-toolkit), which is a 3D graphics engine built for WPF. Things I use there are along the lines of rectangles, cuboids, and even some pipes, solid and "hollowed out".

Then, of course, also cameras, light sources, materials such as metal, iron, grass, "near-plastic" like padding-ish, etc, etc.

After that, I'd like to interact with the models I configure, perhaps run transforms on them, etc, along these lines; I realize frameworks like MVC are likely beyond the scope of this API, but the models I create should be accessible in whatever framework I choose.

Thank you...

**Comment by mrdoob** [comment]
Please, take a look at the documentation:
