### ISSUE TITLE
NuGet packaging

### ISSUE THREAD

**Issue by mwpowellhtx** [mrdoob/three.js#8455]
Hello,

Next stupid question is, are you maintaining any NuGet packaging?

The obvious answer is no you are not currently. But would you be interested to?

One of the forked [repositories](http://github.com/Rangoric/three.js) is referenced, but I think the maintainer is no longer active and is lagging behind.

I may pick it up from there, but I hate to muddy the waters if it isn't necessary for me to do so.

**Comment by mrdoob** [comment]
This section is for feature requests and bug features only.

**Comment by mwpowellhtx** [comment]
Hey, I consider a NuGet package to be a potential feature request.
