### ISSUE TITLE
DirectGeometry.fromGeometry creates duplicate vertices

### ISSUE THREAD

**Issue by wassname** [mrdoob/three.js#8458]
##### Description of the problem 

I seems that DirectGeometry.fromGeometry creates duplicate vertices. In [this](https://github.com/mrdoob/three.js/blob/dev/src/core/DirectGeometry.js#L170) line of code vertices are created when looping through faces, not vertices. This result in duplicate vertices.

I think this is unintended, or am I missing something?. 

This problem effects BufferGeometry (via fromGeometry) and means the WebGL renderer needs to do ~6x as much work. 

Working example:
- [JSFiddle](http://jsfiddle.net/wassname/rvg3gv8o/1/)

To replicate this, convert a geometry to buffer geometry and back again. Then compare the vertices as below:
```javascript
// extract from jsfiddle
var bufferGeom = new THREE.BufferGeometry()
bufferGeom.fromGeometry(geometry)

var newGeom = geometry.clone()
newGeom.fromBufferGeometry(bufferGeom)

if (newGeom.vertices.length != geometry.vertices.length) {
  console.error('The new geometry has ', newGeom.vertices.length, 'vertices while the geometry only had ', geometry.vertices.length)
}
```

##### Three.js version

- [x] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

NA

**Comment by centerionware** [comment]
This is because buffer geometries operate un-index'd. I personally couldn't ever get an index'd buffer geometry to render anything to the screen. It may be a bug that it won't render, it may be intentional, hopefully someone who knows more about it can comment.

**Comment by wassname** [comment]
Oh that makes sense thanks. So this is intended behaviour for non-indexed geometry. More discussion [here](https://github.com/mrdoob/three.js/issues/6191)
