### ISSUE TITLE
Camera wont lookAt vector if its child of an object

### ISSUE THREAD

**Issue by GiorgioMartini** [mrdoob/three.js#8480]
##### Description of the problem 

So I want to have a camera with a perlin noise that also looks at a specific point.

Here is my scene in codepen: http://codepen.io/giorgiomartini/pen/ZWLWgX?editors=0010

The camera is a child of  an object that has a slower, wider perlin noise, then the camera has another,  faster perlin noise:

parent ---> has one slow and wide perlin noise
-child(which in the end will be a camera) ---> has a faster shorter perlin noise

But when I try to make the child lookAt a  specific vector which is at the center of the scene(called origen). Somehow instead of it looking at the specified vector called 'origen' it looks at its parent(the red object)

How can I make the child(the green object) lookAt the specified vector(origen) ? and for the same matter change the child for the camera and that camera looksAt the vector origen.

Right now i just use the child so i can see whats going on but in the end the child will be a camera.

this is the code: 

```
function centeredNoise(min, max, offset) {
		return PerlinNoise.noise( offset, offset,  0)* (max - min) + min;
}

var scene = new THREE.Scene();
var gridHelper = new THREE.GridHelper( 10, 1 );
var xOffset=0,
	  zOffset=0,
		yOffset=0,
		xOffsetParent=0,
		yOffsetParent=0,
		zOffsetParent=0,
		camXPos,
		camYPos,
		camZPos,
		camParentXPos,
		camParentYPos,
		camParentZPos;

var camera = new THREE.PerspectiveCamera( 75, window.innerWidth/window.innerHeight, 0.1, 1000 );

var renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );
document.body.appendChild( renderer.domElement );

var geometry = new THREE.CircleGeometry( 1, 12 );
var cameraParent = new THREE.BoxGeometry( 1, 1, 1 );
var material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
var materialParent = new THREE.MeshBasicMaterial( { color: 0xff0000 } );
var materialCenter = new THREE.MeshBasicMaterial( { color: 0x0000ff } );
var child = new THREE.Mesh( geometry, material );
var parent = new THREE.Mesh( geometry, materialParent );
var centerOfScene = new THREE.Mesh( geometry, materialCenter );


scene.add( child,parent, centerOfScene,gridHelper );


camera.position.z = 15;
camera.position.y = 6;
camera.rotation.x = 251;

THREE.SceneUtils.detach( child, parent, scene );
THREE.SceneUtils.attach( child, scene, parent );

var origen = new THREE.Vector3( 0, 0, 0 );


var render = function () {
	child.lookAt(origen);
	requestAnimationFrame( render );


	xOffset += 0.01;
	yOffset += 0.011;
	zOffset += 0.012;

	xOffsetParent += 0.0011;
	yOffsetParent += 0.0013;
	zOffsetParent += 0.0012;

	camXPos = centeredNoise(-1,1,xOffset);
	camYPos = centeredNoise(-1,1,yOffset);
	camZPos = centeredNoise(-1,1,zOffset);
	child.position.x = camXPos*4;
	child.position.y = camYPos*4;
	child.position.z = camZPos*4;

	camParentXPos = centeredNoise(-1,1,xOffsetParent);
	camParentYPos = centeredNoise(-1,1,yOffsetParent);
	camParentZPos = centeredNoise(-1,1,zOffsetParent);
	parent.position.x = camParentXPos*30;
	parent.position.y = camParentYPos*30;
	parent.position.z = camParentZPos*30;


	renderer.render(scene, camera);


};
```

##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
This question has been [answered](http://stackoverflow.com/questions/36156460/why-is-lookat-not-looking-at-specified-vector/36160110#36160110) on stackoverflow.

**Comment by GiorgioMartini** [comment]
Oh WestLangley im so sorry :( im a bit lost in your answer and i thought i would get a different phrasing on your answer.

Could you please try to re-answer the question here in a little different way? I tried what you suggested but I guess i didnt do it right because the renderer stops working, this is the codepen with the fixes as i understood them:  http://codepen.io/giorgiomartini/pen/ONjxGv?editors=0010

But im guessing i didnt do exactly what you said...could you please help me out :)

**Comment by erichlof** [comment]
@GiorgioMartini I answered on SO:
http://stackoverflow.com/questions/36156460/why-is-lookat-not-looking-at-specified-vector/36160110#36160110
  Hope that helps! :)

**Comment by erichlof** [comment]
sorry for bumping this issue, but @GiorgioMartini have you checked out my corrected/updated answer on SO? 
http://stackoverflow.com/questions/36156460/why-is-lookat-not-looking-at-specified-vector/36160110#36160110

Thanks

**Comment by CVex2150J** [comment]
@GiorgioMartini and all future person who seek a quick solution, I had the same problem and I solve it by adding THREE.Object3D.prototype.**lookAtWorld** function or redefining the original one.

I know that this is more complexe to compute and that this is not optimal. I just wanted a quick solution for a few world lookat that doesn't require a tone of call. There will be problems with the up vector. All objects in my scenes have the default one, so I don't care about it. ( ͡° ͜ʖ ͡°)

I also check the solution with the dummy object. This is cool and simple but this takes much more memory, and objects in the scene to achieve the same result. I'm use to use Linear algebra so matrix transformation was the quick solution for me.
````
THREE.Object3D.prototype.lookAtWorld = function () {

	// This routine DOES support objects with rotated and/or translated parent(s), but not up vector
	var pos = new THREE.Vector3();
	var m1 = new THREE.Matrix4();
	var inv = new THREE.Matrix4();

	return function ( vector ) { 

		// this.position is replace by the world position of the object.
		pos.setFromMatrixPosition( this.matrixWorld );
		m1.lookAt( vector, pos, this.up );
		if( this.parent ){
			// If there is a parent, the matrixWorld inverse must by added to the world lookAt
			inv.getInverse( this.parent.matrixWorld );
			m1.multiply(inv);
		}
		this.quaternion.setFromRotationMatrix( m1 );

	};

}();
````
