### ISSUE TITLE
Texture in Sphere is not smooth in the back on some devices

### ISSUE THREAD

**Issue by curti55** [mrdoob/three.js#8481]
##### Description of the problem 
I have a sphere and a camera in it.
The Texture of the sphere is in the "front" 180 degrees as smooth as could be, but in the back there are "stitching errors". Im using several devices and all work great, but one device (Galaxy s5) produces this problem. Maybe the log 
"THREE.WebGLRenderer: OES_texture_float_linear extension not supported." is the hint in this case.
...

##### Three.js version

- [ ] r73
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Samsung Galaxy s5

**Comment by mrdoob** [comment]
A screenshot would help...

**Comment by curti55** [comment]
will add them tomorrow! Read something about near / far camera configurations wich can produce unwanted texture behaviour? Mine is running with values copied from a demo : 
`this.camera = new THREE.PerspectiveCamera(75, width / height, 0.1, 10000);`

this is the sphere:
`var sphereSegments = 48;
this.videoTexture = new THREE.VideoTexture(video);
this.videoTexture.name = 'videoTexture';
this.videoTexture.minFilter = THREE.LinearFilter;
this.videoTexture.magFilter = THREE.LinearFilter;
this.videoTexture.format = THREE.RGBFormat;
this.videoTexture.generateMipmaps = false;

this.movieMaterial = new THREE.MeshBasicMaterial( { map: this.videoTexture,
						overdraw: false,
						side: THREE.FrontSide} );
geometry = new THREE.SphereGeometry(50, sphereSegments, sphereSegments,0,Math.PI*2,0,Math.PI);

this.mesh= new THREE.Mesh( geometry, this.movieMaterial );
this.mesh.position.set(0, 0, this.posZ);
this.scene.add(this.mesh);
this.mesh.scale.x = -1;`
