### ISSUE TITLE
Does OrthographicCamera not work with WebGLRenderTarget?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#8487]
[teh fiddle](http://jsfiddle.net/akmcv7Lh/45/). I don't see why should it not work? the 2nd camera is looking right at the blue plane. if you use PerspectiveCamera instead, the thing works. so, what's wrong there?

**Comment by mrdoob** [comment]
```javascript
new THREE.OrthographicCamera(-128, 128, 128, -128, 1, 1000);
```

**Comment by makc** [comment]
fffuuuuuuuuu
