### ISSUE TITLE
Use HTML5 Canvas to Draw 3D Models

### ISSUE THREAD

**Issue by shahge** [mrdoob/three.js#8489]
Hello i am student of final year of Software Engineering, our final year project is to draw 3d models of building on canvas.User can draw its home in 3d. but i dont get any type of help on internet regarding this issue. i found your article. kindly set a path for me how this project can be done. please help us. it is big issue for us how to draw?

...

##### Three.js version

- [ ] Dev
- [ ] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by thedjpetersen** [comment]
@shahge hey a good place to start is the documentation and the examples. [This](http://threejs.org/docs/#Reference/Renderers/CanvasRenderer) section details how to render to a canvas and take a look at the [examples](https://github.com/mrdoob/three.js/tree/master/examples)(specifically any of them prefixed with canvas_).
