### ISSUE TITLE
where is the PathControl.js,I can't find it

### ISSUE THREAD

**Issue by ZhengGuibing** [mrdoob/three.js#8492]
##### Description of the problem 

...

##### Three.js version

- [ ] Dev
- [ ] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
See #5690
