### ISSUE TITLE
Geometry.fromBufferGeometry ignores index, LineDashedMaterial does not work with BufferGeometry

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#8494]
so I figured LineDashedMaterial does not work with BufferGeometry, so I would convert it via Geometry.fromBufferGeometry, but no cigar:

![screen shot 2016-03-31 at 20 25 06](https://cloud.githubusercontent.com/assets/242577/14186512/05e057f0-f77f-11e5-9b54-b9d586b9e4bc.png)

fiddle: https://jsfiddle.net/bqovLnes/

**Comment by makc** [comment]
ok, it seems it just ignores index

**Comment by makc** [comment]
workaround fiddle: https://jsfiddle.net/bqovLnes/1/

**Comment by Mugen87** [comment]
You can now do this in your code:
```js
line.computeLineDistances();
```
This works with both `Geometry` and `BufferGeometry` based line geometries. (Or in other words: `LineDashedMaterial` works now with `BufferGeometry`).
