### ISSUE TITLE
Matrix* should have a preMultiply function

### ISSUE THREAD

**Issue by mikebolt** [mrdoob/three.js#8496]
##### Description of the problem

In my application it makes much more sense to deal with an Object3D's matrix directly, rather than using the position and rotation properties. When rotating an object about its parent's origin, I have to write this code:

    object.matrix.multiplyMatrices(rotation, object.matrix);

Which is somewhat verbose. My suggested alternative is to write this:

    object.matrix.preMultiply(rotation);

This would require the addition of a very simple function. Of course, I could add this to my own code, but I think that this would be nice for everyone to have.

I would be glad to add this and submit a pull request, but only if it's OK with the project maintainers.

**Comment by WestLangley** [comment]
First of all, I would caution against manipulating an object's matrix directly. If you know what you are doing, that is fine. But three.js was not designed to be used that way.

I assume you are setting `matrixAutoUpdate = false`. That usage is designed for objects known to be _static_ -- to avoid recomputing the object's matrix unnecessarily.

There are many three.js methods that do not work correctly when `matrixAutoUpdate = false`, so be careful. three.js uses the object's `position`, `quaternion`, and `scale` to infer, or change, the object's transform. The `matrix` is ancillary.

To your issue, `Matrix3` does not even have a `multiply()` method, so I do not think a `preMultiply()` method is warranted in that case.

Methods are added if the library needs them, or if a user provides a compelling use case for which the methods are advantageous.

`Matrix4.preMultiply( matrix )` seems reasonable to me.

**Comment by makc** [comment]
> I assume you are setting matrixAutoUpdate = false.

or he could be [decomposing the matrix](https://makc3d.wordpress.com/2015/11/15/how-to-set-object-matrix-in-three-js/) after all his voodoo, and then it magically works again

**Comment by mrdoob** [comment]
> `Matrix4.preMultiply( matrix )` seems reasonable to me.

Sounds good to me too.

**Comment by WestLangley** [comment]
Implemented. Thanks for the suggestion, @mikebolt.
