### ISSUE TITLE
Clipping planes

### ISSUE THREAD

**Issue by Need4Speed402** [mrdoob/three.js#8497]
Why is there no built in support for clipping planes (at least that I know of)? I was screwing around with another WebGL api and that defines a nifty function: ```model.setClippingPlane(0, -1, 0, -1)``` and it does all the rest for you. I was trying to re-implement this graphic in threejs:
![](http://i.prntscr.com/3072f98743e04250bd72b92861bfee49.png)
[Youtube video of the animation](https://www.youtube.com/watch?v=6ZMZWVQcnAM&feature=youtu.be)
I really don't want to go through the trouble of making my own shader and screwing around with the math
to make the animation work. Perhaps it should be time to implement some kind of clipping plane system. It would be nice to even add the planes to the frustum culler too. Squeeze some extra performance out of that.

**Comment by WestLangley** [comment]
Perfect timing. See #8465.

**Comment by Need4Speed402** [comment]
What would really impress me is if these user defined clipping planes would be added to the frustum culler just like it is in the api I used. One issue I really don't like about your implementation is I still need to fiddle around with the math for the planes to that they clip what I want. For instance with the api I was using you can do this:
```
//translate scene 6 units away from the camera
model.translate(0, 0, -6);
//I can do some funky rotations
model.rotate(/*rotation angle*/, /*rotation axis*/)

//add the clipping plane and object I want to render.
model.setClippingPlane(/*normal vector of plane*/, /*translation from origin*/);
model.fillCuboid(0, 0, 0, 1);
```
The api will automatically apply the model matrix to the clipping plane so that the plane will be 'in-synch' with the cube and one half of it will aways be culled. Perhaps adding some .clippingPlanes list on a ```THREE.Object3D``` would add clipping planes that follow the model matrix? At this point though, what I need is in three.js, but it would be really cool if you guys would be able to figure out something for that.

**Comment by makc** [comment]
> I was trying to re-implement this graphic in threejs

should be simple enough to do in the shader, too

**Comment by tschw** [comment]
@Need4Speed402
> What would really impress me is if these user defined clipping planes would be added to the frustum culler just like it is in the api I used.

The global clipping state *is* considered during frustum culling. The local one is seen as a modeling operation and thus is not.

> One issue I really don't like about your implementation is...

...driven by how WebGL programs are currently being managed in the renderer.

> Perhaps adding some .clippingPlanes list on a THREE.Object3D would add clipping planes that follow the model matrix? [...] At this point though, what I need is in three.js, but it would be really cool if you guys would be able to figure out something for that.

As you can read up on the PR, that's actually what I would have liked, but it needs us to tackle some internal issues first.

@makc 
> should be simple enough to do in the shader, too

Yes, the code hooked into the shaders is very simple. Managing the state in the renderer was a lot more work. Note that the planes are transformed to view space. This way, the ones you can see closely are always encoded near the center and won't artefact even when running on hardware with limited precision.

**Comment by mrdoob** [comment]
http://threejs.org/examples/#webgl_clipping
http://threejs.org/examples/#webgl_clipping_advanced
