### ISSUE TITLE
Should spotlight shadows be blurred by the penumbra?

### ISSUE THREAD

**Issue by MasterJames** [mrdoob/three.js#8501]
Just a general question for discussion. It might have been mentioned after adding proper colored shadows if I recall as something for the wishlist, or maybe that was transparent shadows.
I thought to ask quickly about the thought though.
Should the Shadow from a Spot Light be blurred based on the penumbra settings and the distance to shadow forming edge. Seems like there's a new PR for a triangle to point distance thingy that might be used that way.

**Comment by bhouston** [comment]
@MasterJames, we really need to implement PCSS as you recommend, it is the way to implement this correctly and on the GPU.  The Triangle closestPointToPoint is too slow for blurring shadows. :/

**Comment by MasterJames** [comment]
Right thanks for the reminder. It just seemed at first it could be blurred some to match the penumbra. I then noted that would look more believable but the example of a board or stick reaching up from the floor would look odd without distance scaling so I tried to suggest maybe there's a simple shortcut to a better more realistic physically based look but yes PCSS one day is better. It's fine for now without a blur to match the penumbra.

**Comment by MasterJames** [comment]
And "Closed", with this useful knowledge link, to inspire.
http://developer.download.nvidia.com/shaderlibrary/docs/shadow_PCSS.pdf
