### ISSUE TITLE
THREE.Mesh.prototype.clone breaks extended classes

### ISSUE THREAD

**Issue by Galiaf47** [mrdoob/three.js#8507]
##### Description of the problem 
Current version of `THREE.Mesh.prototype.clone` calls constructor with fixed parameters (geometry, material). If you extend THREE.Mesh and specify constructor with different parameters, as an example:
```js
class MyMesh extends THREE.Mesh {
    constructor(dto, geometry, material) {
        super(geometry, material);
        this.dto = dto;
    }
}

var myMesh = new MyMesh({}, new THREE.Geometry(), null);
var clonedMesh = myMesh.clone();
```
`myMesh.clone()` will call `new MyMesh(geometry, material, undefined)` and it will break clonedMesh.
An older implementation of clone (r71) is not the best solution, because it calls THREE.Mesh constructor, but at least it puts parameters to the right places.
...

##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
Hi Siarhei! Maybe this [jsfiddle](https://jsfiddle.net/ngx0o6pq/4/) helps you further...

**Comment by Mugen87** [comment]
And this [fiddle](https://jsfiddle.net/7m039o7a/) is for the case, that you don't change the signature of the mesh constructor. The example overwrites the `copy` method to transfer the property data to the new object.

**Comment by Mugen87** [comment]
And this [fiddle](https://jsfiddle.net/7m039o7a/3/) is for the case, that you don't change the signature of the mesh constructor. The example overwrites the `copy` method to transfer the data of your property to the new object.

**Comment by Galiaf47** [comment]
Hello Michael.
Thank you for the examples, but I don't need it.
I just upgraded from r71 to r75 and decided to let developers know about this unexpected behavior.
