### ISSUE TITLE
THREE.Audio: .load has been deprecated. Please use THREE.AudioLoader.

### ISSUE THREAD

**Issue by RemusMar** [mrdoob/three.js#8509]
THREE.WebGLRenderer 76dev 

Everything seems to be ok in r76dev, but that error message is not present in the current r75

**Comment by mrdoob** [comment]
Hmmm?

**Comment by RemusMar** [comment]
> Hmmm? 

The error was introduced with that "Added THREE.AudioContext"

**Comment by RemusMar** [comment]
THREE.Audio.prototype.load = function ( file ) {
	console.warn( 'THREE.Audio: .load has been deprecated. Please use THREE.AudioLoader.' );
	var scope = this;
	var audioLoader = new THREE.AudioLoader();
	audioLoader.load( file, function ( buffer ) {
		scope.setBuffer( buffer );
	} );
	return this;
};

**Comment by Mugen87** [comment]
PR #8370 recently changed the Audio API. `examples/misc_sound.html` shows how to use the new system.

**Comment by RemusMar** [comment]
> PR #8370 recently changed the Audio API. examples/misc_sound.html shows how to use the new system 

In my opinion that's a bad idea.
**audio / video . src** and **audio / video .load()** should remain untouched.

**Comment by Mugen87** [comment]
One motivation of the PR was to align the loading process of `THREE.Audio` entities to the rest of the library. Therefore `THREE.AudioLoader` was introduced ( in addition to `THREE.FontLoader` or `THREE.ImageLoader`) and `THREE.Audio.load` marked as deprecated.

To be honest, i don't understand your objection. `THREE.Audio` is a wrapper for HTML5 Web Audio objects. Your mentioned HTML5 DOM method `load` and property `src` are something different.

**Comment by RemusMar** [comment]
> To be honest, i don't understand your objection

In most of the cases you don't need the onLoad, onProgress, onError callbacks.
So you don't need THREE.AudioLoader ...
On the other hand, messing up the API all day long won't bring anything good.
Instead of one library for 1000 users, we'll end up with 1000 libraries for 1000 users.
I hope you got the main point.

**Comment by RemusMar** [comment]
> Your mentioned HTML5 DOM method load and property src are something different.

No, it's not.
Keep the syntax for **WHATEVER.sound.src** and **WHATEVER.sound.load()** untouched.

**Comment by Mugen87** [comment]
@EvilPeanut What's your opinion?

**Comment by RemusMar** [comment]
To **@EvilPeanut**

I totally agree that  the onLoad, onProgress and onError callbacks should be available for ANY loaded file (including sounds).
If they cannot be implemented for THREE.Audio.load, I don't have any problem with THREE.AudioLoader 
But don't depreciate THREE.Audio.load !

**Comment by mrdoob** [comment]
@RemusMar The reason we deprecate things is to focus our energies in fewer code paths. The fewer code paths the less things we have to maintain. The less things we have to maintain the more progress we can do (WebGL2 features, WebVR support, etc).

**Comment by EvilPeanut** [comment]
@Mugen87 @RemusMar I agree with @mrdoob. The `THREE.AudioLoader` follows the format of the rest of the loaders in the library and provides the onLoad, onProgress and onError callbacks. The loader should be easier to use than the deprecated methods and provides this additional functionality. I don't see a need to keep and support `THREE.Audio.load`. If the `THREE.AudioLoader` is missing some functionality that you require then I'm sure we can have a look at adding it.

**Comment by RemusMar** [comment]
> The reason we deprecate things is to focus our energies in fewer code paths.
> The fewer code paths the less things we have to maintain.

If so, why don't you create a single loader for any kind of file (3D model, texture, sound)?
Why do you need TextureLoader, AudioLoader, etc ?

**Comment by mrdoob** [comment]
I feel like explicit code is less prone to user errors.

**Comment by RemusMar** [comment]
> Because I feel like explicit code is less prone to user errors.

In most of the cases:
explicit code = more wasted resources
good looking code = bad performances
hardcoded = best performances

**Comment by mrdoob** [comment]
Ok.

**Comment by EvilPeanut** [comment]
![image](https://cloud.githubusercontent.com/assets/820781/14249456/b939f640-fa71-11e5-92f6-ac039552377e.png)
Sorry, I couldn't resist :')

**Comment by RemusMar** [comment]
> Sorry, I couldn't resist :')

I'm not sure about your workflow, but be prepared for this change in a future update:

		THREE.EvilPeanut = FOUR.mrdoob

cheers
