### ISSUE TITLE
I'm getting the error THREE.ShaderMaterial: attributes should now be defined in THREE.BufferGeometry instead

### ISSUE THREAD

**Issue by dlinstedt** [mrdoob/three.js#8512]
##### Description of the problem 
Seeing the error, upgrading from r62 to r75, everything was going great until I hit this error.  The problem is:  there is no example of HOW to convert from the old style assigning attributes to the new style of using BufferGeometry.

What I really need: is a full example
<old code>
changes to:
<new code>

so I can complete the conversion.

##### Three.js version

- [ ] Dev
- [ ] r75

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
All the [examples](http://threejs.org/examples/#webgl_custom_attributes) under `webgl / advanced` use the new approach. Please, study them.

**Comment by dlinstedt** [comment]
Your code is brilliant, your applications are brilliant, of that, I have no doubt.  Your new examples are also brilliant - but again, there are NO guides, no help, no demonstrations that show HOW to convert an "old code component" to a "new format" for use.  I am not the only one stuck on upgrading the functionality to use the new Three.JS libraries the proper way.  Simply pointing me to new code, does NOT tell me how to convert the old pieces that I have.   for example: the old library renders the graphic PNG just fine, but in the new library - nothing.  It's ALL BLACK, there are no lines, no points, nothing but the text sprites render.  Simply studying the new code will not / does not teach me how to convert the old calls.

**Comment by mrdoob** [comment]
@dlinstedt I'm sorry, we don't have enough resources to write guides at this point. You may want to take a look at other solutions that offer user support.

**Comment by dlinstedt** [comment]
Thank-you, I completely understand.  Can I pay you to convert an old example to the new library?

**Comment by tschw** [comment]
@dlinstedt 
> Can I pay you to convert an old example to the new library?

I can offer paid support for Three.js / do a fully documented port of an old example. Let me know your email address or contact me (mine is all over the changelog throughout the last year - `git log` will show it), in case you are interested.

**Comment by dlinstedt** [comment]
@tschw  - my email is: dan@learndatavault.com
