### ISSUE TITLE
MeshLambertMaterial causes threejs to crash on certain hardware

### ISSUE THREAD

**Issue by gvr37leo** [mrdoob/three.js#8516]
##### Description of the problem 
using MeshLambertMaterial causes threejs to crash
[screenshot on imgur](http://imgur.com/oVdKCUB)

Also i have been on sites that use three.js and MeshLambertmaterials that do work, like on this udacity course [here](https://classroom.udacity.com/courses/cs291/lessons/91073092/concepts/1183049610923). (click on "go to quiz" and run it) maybe this has something to do with them using an older version.
Other materials work fine.

THREE.WebGLProgram: shader error:  0 gl.VALIDATE_STATUS false gl.getProgramInfoLog C:\fakepath(250,9-30): error X3004: undeclared identifier 'IncidentLight'

Warning: D3D shader compilation failed with default flags. (vs_3_0)
 Retrying with avoid flow control
C:\fakepath(250,9-30): error X3004: undeclared identifier 'webgl_45daf4aa877f103d'

Warning: D3D shader compilation failed with avoid flow control flags. (vs_3_0)
 Retrying with prefer flow control
C:\fakepath(250,9-30): error X3004: undeclared identifier 'webgl_45daf4aa877f103d'

Warning: D3D shader compilation failed with prefer flow control flags. (vs_3_0)
Failed to create D3D shaders.
  (anonymous function) @ three.min.js:704
three.min.js:600 WebGL: INVALID_OPERATION: useProgram: program not valid
255three.min.js:671 WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
three.min.js:671 WebGL: too many errors, no more errors will be reported to the console for this context.

##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

only tested the latest 1

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
this is probably graphics card specific because other people i know are not having this issue

AdapterType:    Intel(R) HD Graphics 4000
DAC Type:        Internal

**Comment by mrdoob** [comment]
https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=how%20to%20check%20graphics%20card%20windows

**Comment by gvr37leo** [comment]
thanks for reply updated it to Intel(R) HD Graphics 4000

**Comment by mrdoob** [comment]
Do you have the latest drivers?

**Comment by gvr37leo** [comment]
Windows device manager says i'm using the latest driver but i dont know if there is some place where i can get a more up to date one.

**Comment by gvr37leo** [comment]
just downloaded installed and restarted using  [latest driver from intel site](https://downloadcenter.intel.com/download/25698/Intel-Graphics-Driver-for-Windows-7-8-1-10-15-33-), no succes.

**Comment by mrdoob** [comment]
Ah wait, this is a known issue already... #8161
A fix already landed in the `dev` branch.

**Comment by gvr37leo** [comment]
just tried the dev version and it still crashes i also tried version 68 and that one **does** work (:

**Comment by mrdoob** [comment]
Do you mind trying again (just pushed a new build).

**Comment by mrdoob** [comment]
http://rawgit.com/mrdoob/three.js/dev/docs/#Reference/Materials/MeshLambertMaterial

**Comment by gvr37leo** [comment]
yes that one works

**Comment by gvr37leo** [comment]
Thanks lot  a i don't know if many people were having this issue but it sure helped me.I hope other things dont start crashing because of this and that it reaches the master branch soonish in the meantime i'll be using the dev branch.

**Comment by mrdoob** [comment]
I will reach the `master` branch on the 15th. Hopefully!

**Comment by quanyue** [comment]
Thanks lot.This helped me too.
