### ISSUE TITLE
Documented defaults of shadow.camera.near and far

### ISSUE THREAD

**Issue by stilllife00** [mrdoob/three.js#8521]
Sorry if I post in thre wrong place but I am not sure this is a bug.

##### Description of the problem 
http://threejs.org/docs/#Reference/Lights/SpotLight here the defaults for shadow.camera.near and shadow.camera.far are set to 50 and 5000 but doing a console log I've actually got 0.5 and 500

Old documentation or do I miss something ?

**Comment by Mugen87** [comment]
Just old documentation. The entire `SpotLight` doc is currently not up to date (e.g. parameters like `shadowMapWidth` or `shadowMapHeight` are deprecated).

For now please have a look at the spotlight examples at `dev` branch, which were recently added by @MasterJames. :+1: 

see [webgl_lights_spotlight.html](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_lights_spotlight.html) and [webgl_lights_spotlights.html](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_lights_spotlights.html)

**Comment by MasterJames** [comment]
I'm just updating for mobile issues I've also noted the need for updates in the docs.

**Comment by Mugen87** [comment]
@MasterJames I've started to clean up the light docs with this PR #8526. Reviews and additions are very welcome :wink: (There are some `TODO` placeholders where we need to put a good text)

**Comment by Mugen87** [comment]
@stilllife00 Is it okay for you to close the issue? The mentioned PR cleaned up the docs and provided new files for all `LightShadow` entities.
