### ISSUE TITLE
Clone cylinderGeometry Creates Geometry

### ISSUE THREAD

**Issue by kpetrow** [mrdoob/three.js#8522]
##### Description of the problem

When cloning a cylinderGeometry the clone is a geometry not a cylinderGeometry.
simple fiddle,check the console:  http://jsfiddle.net/momve8hk/

Tested in r72 and i get a cylinderGeometry.
...
##### Three.js version
- [x] r75

**Comment by kpetrow** [comment]
I ended up just making new cylinder geometries from the parameters object.  Seems to work pretty well.

**Comment by Mugen87** [comment]
I think this [line of code](https://github.com/mrdoob/three.js/blob/master/src/core/Geometry.js#L1141) causes the behavior. The implementation of the `Geometry .clone`  will always return an object with type `Geometry`.

@mrdoob Um, what do you think about this approach? Maybe it's better to implement a `clone` method that preserves the type of the object.

**Comment by mrdoob** [comment]
So it used to behave like that already... 

https://github.com/mrdoob/three.js/commit/ae4c5198fdbaafb747e5c3739d4506c5b622c282

**Comment by Mugen87** [comment]
I see. So the current implementation avoids other problems in context of cloning geometries...

**Comment by kpetrow** [comment]
Given that cylinder geometries are so small is there any benefit in cloning a cylindergeometry vs creating a new cylinder geometry?  It seems like cloning is useful when the geometries are large and need to be loaded from external files.

**Comment by mrdoob** [comment]
Yeah, in this case there is no benefit. But the code behaved unexpectedly...
