### ISSUE TITLE
VideoTexture needs a teardown dispose

### ISSUE THREAD

**Issue by blq** [mrdoob/three.js#8525]
##### Description of the problem

VideoTexture doesn't seem to handle teardown correctly. 
After dispose the requestAnimationFrame loop continues to spin forever.
I.e cancelAnimationFrame should be called in (a listener to) Texture's dispose method.
Might also have an option to stop the input <video> on dispose, here YMMV though (deep vs shallow teardown).

Regards
/Fredrik Blomqvist
##### Three.js version
- [ ] Dev
- [x] r75
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

**Comment by dokydok** [comment]
Any news about this issue? 
It doesn't seem like a feature request to me, if the Video Texture inits an infinite unstoppable loop it's kind of a bug... :)

**Comment by pailhead** [comment]
Video textures may really need to be visited soon.

**Comment by mrdoob** [comment]
`VideoTextures` no longer use a internal `requestAnimationFrame`.
https://github.com/mrdoob/three.js/pull/13053#issuecomment-355763509
