### ISSUE TITLE
Feature Wish list

### ISSUE THREAD

**Issue by ajhalls** [mrdoob/three.js#8527]
##### Description of the problem

While building an interactive panoramic program, I found a few things that I was surprised didn't exist for a program as amazing as Three.js. Here is a few things that I think would be easy to add which would also make development nice. Here is a fiddle to give you a frame of reference of why I think these would be great.
https://jsfiddle.net/ajhalls/h05v48wd/5/

**Debug Mode:**
It would be great if we could add an object to the scene and set `object.debug=true;` which would show a wireframe bounding box around the object which was ALWAYS visible, clicking on it could even give you some additional details, or just console.log it. Sometimes when I am adding things to the scene, I can't figure out why it isn't showing up, then I finally find out it is being added just outside the sphere. It would be great if the wireframe visibility penetrated all objects between the camera and it.

**LookAway():**
The camera.lookAt is great, but sometimes you want things to lookAway. 

**Position.set(camera.position.closer(20));**
When I add some TextGeometry at position camera.target, short strings are OK, but any longer than say 2 characters and they start to get clipped by the outer sphere. Trying to set the location to be a little closer, or a little farther away from the camera position of 0,0,0 is more complicated than it needs to be as I have to first identify whether the value of `object.position.x` is positive or negative, then add or subtract based off that, it would just be awesome if I could pull my object a little closer to the camera to avoid it ending up in outer space. When dragging the object around, it is easy to set it's distance with `point.setLength(450);`, something like that would be great when adding an object doing something like:

```
    var origin = camera.position;
    object.position.x = camera.target.x;
    object.position.y = camera.target.y;
    object.position.z = camera.target.z;
    object.setLength(origin, 450);
    scene.add(object);
```

**TextGeometry();**
It would be awesome if the TextGeometry supported wrapping by default, I have a fairly robust example working now that supports dragging as a group, but it was a tricky thing for me to put together. I know the API is under development, so it would be cool if that was added as you are working on it. 

Threejs.org Documentation
Improved search, it would be great if the search looked at more than just the titles, many times I am looking for something, for example - maybe the "debug" feature is already there, but I don't know because when I type debug into the search box, nothing shows up. I realize that the results could get messy, but they could be tabbed with one that is titles only, and another that shows everything.

Just a few ideas that would help, if there is anything I can do to help, let me know.
...
##### Three.js version
- [x] r75
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
Wishlists with multiple feature requests at once are really hard to track. I hope you are not angry when I close the issue. Please always report a single feature request per issue in the future.

Some comments to your suggestions:

Methods like `lookAway()` or `closer()` very use case specific. IMO, features like that do not belong into a library. Same for the mentioned characteristics of a debug mode.

We also want to keep the geometry generators simple. [threejs-text-wrapper](https://github.com/jamesaburnell/threejs-text-wrapper) should be sufficient if you need automatic text wrapping.
