### ISSUE TITLE
Sprite map can not be used with RenderTarget texture

### ISSUE THREAD

**Issue by dimarudol** [mrdoob/three.js#8532]
SpritePlugin does not work correctly with textures created by RenderTarget.
https://jsfiddle.net/fppt8d1o/

##### Three.js version

- [x] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
#8619
