### ISSUE TITLE
What's wrong in my json file?

### ISSUE THREAD

**Issue by anhkhoi** [mrdoob/three.js#8536]
##### Description of the problem 
I have a json file export from Unity3D by a tool. But I cannot load it by THREE.ObjectLoader. It throw an error in console while loading `Uncaught TypeError: Cannot read property 'type' of undefined`

Error line 19564 
```
switch ( data.type ) {
}
```

My json file
http://sametext.com/view/576ce1fb

My script code
http://sametext.com/view/8749384b

Please take a look and help me point to my mistake. Thanks.
...

##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
- [x] MacOS

**Comment by mrdoob** [comment]
That file is now using out format. https://github.com/mrdoob/three.js/wiki/JSON-Object-Scene-format-4
