### ISSUE TITLE
Window resize functionality should be included

### ISSUE THREAD

**Issue by FreeFrags** [mrdoob/three.js#8540]
I believe window resize should be included as an example and be included in threejs as this is something every one will benifit from. 

Id like to point out that jeromeetienne already did something like this:
https://github.com/jeromeetienne/threex.windowresize

##### Three.js version

- [x] Dev
- [ ] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Every example has the code needed for handling window resize...
