### ISSUE TITLE
MeshDepthMaterial doesn't seem correct

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8550]
##### Description of the problem 

This PR here allows one to test the MeshDepthMaterial:

https://github.com/mrdoob/three.js/pull/8549  Example link: http://ci.threejs.org/api/pullrequests/8549/examples/webgl_materials_channels.html

One will notice that it is always white if one switches to the 'depth' material.  The issue seems to be the logic in the fragment shader starting here:

https://github.com/mrdoob/three.js/blob/master/src/renderers/shaders/ShaderLib/depth_frag.glsl#L18

The variable ```gl_FragCoord.z``` is already in the range of 0 to 1 based on the camera frustum.  Thus it shouldn't be divided by ```gl_FragCoord.w```.

And because ```gl_FragCoord.z```, trying to adjust it by ```mNear``` and ```mFar``` makes no sense.

So I am unsure what this material is trying to achieve?  Maybe one could just replace it with code like this so it is a grayscale depth shader based on the camera's near/far clip range?

```
	#ifdef USE_LOGDEPTHBUF_EXT

		float depth = gl_FragDepthEXT;

	#else

		float depth = gl_FragCoord.z;

	#endif

	gl_FragColor = vec4( vec3( depth ), opacity );
```

##### Three.js version

- [x] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
The important requirement is `depth` must have the same units as `mNear` and `mFar`.

    float color = 1.0 - smoothstep( mNear, mFar, depth );

I think this explains the tricky part.

https://www.opengl.org/discussion_boards/showthread.php/179953-(gl_FragCoord-z-gl_FragCoord-w)-for-quick-depth-calculation-camera-to-fragment

So, according to the link, the code, as written, is reasonable.

Perhaps we can do better by mapping `depth` to NDC space and setting `mNear = - 1` and `mFar = 1`.

**Comment by bhouston** [comment]
@WestLangley Ah, so the result is comparable z distances.  But I still do not understand this line:

```
float color = 1.0 - smoothstep( mNear, mFar, depth );
```

Specifically the ```1.0 - ``` part just seems weird, and then writing this to a buffer is generally going to result in out of range parameters. because buffers, unless Float or Half, can not handle out of [0,1] values.  Maybe we could call it MeshDepthFloatMaterial?  That is sort of suggestive that you need to use it with a floating point buffer.

I'd also suggest we reconstruct zDepth in world space as the output of this shader without the constants if possible.  I believe the math for that is half-way done this page:

http://www.songho.ca/opengl/gl_projectionmatrix.html

(BTW I want to contribute a really high quality SAO shader, but to do so, I need to have really accurate depth and normal values -- there is a higher level purpose to these recent PRs and issues.)

**Comment by WestLangley** [comment]
`smoothstep()` returns a value in [ 0, 1 ]. So ` float color` is 1 for close objects, and 0 for far objects.

I do not see a problem with it...

**Comment by bhouston** [comment]
Ah, yeah for some reason I thought smoothstep(a,b, c) interpolated differently.

I guess the reason why I do not think this works is because in the new example I linked to doesn't work when using the "depth" material.  So I know it doesn't work, but I am not completely sure why.

When I switch to "depth" material it is all white in the new example.  This is even after I ensured that the new/far limits to the camera are fairly tight.  'depth' should actually look nearly equivalent to 'depthRGBAUnpacked" as it also does a black-to-white depth.  But the 'depth' material is perfectly white - try it.

I think the issue is the smoothstep makes the assumption that depth is true depth and not a depth' = (A*depth + B) where A and B are constants that may move depth out of the rate of near, far, thus resulting in clamping again far or near.

**Comment by WestLangley** [comment]
>I think the issue is the smoothstep makes the assumption that depth is true depth and not a depth' = (A*depth + B) where A and B are constants that may move depth out of the rate of near, far, thus resulting in clamping again far or near.

Yes. `depth`, as it is calculated in the shader, is not an absolute measure of depth.

**Comment by tschw** [comment]
@bhouston 
> I need to have really accurate depth and normal values

Keep in mind that `mediump` is all that's guaranteed in the fragment shader and that even `highp` is not that high when it comes to minimum limits (10/14 bits of mantissa, only). Consequently, you may want to map `near` to zero, `far` to 16383, and set a custom varying in that range in the vertex shader where `highp` is guaranteed.

**Comment by bhouston** [comment]
> Yes. depth, as it is calculated in the shader, is not an absolute measure of depth.

From my reading of the frustum projection matrix:

https://github.com/mrdoob/three.js/blob/master/src/math/Matrix4.js#L883

It seems that the resulting w coordinate, which I believe is formally called clipspace W (assuming the input to the project matrix is an eyespace coordinate), is actually the negated z eyespace coordinate, e.g. depth.

In the fragment shader, according to this page: https://www.opengl.org/wiki/Built-in_Variable_(GLSL)#Fragment_shader_inputs, it seems that gl_FragCoord.w in the fragment shader is actually 1 / clipW.

Putting these two facts together it appears that if we wanted true world space depth in the fragment shader we could just do this:

```
float depth = -  1.0 / gl_FragCoord.w;
```

I'll test it out now.

**Comment by bhouston** [comment]
Hmmm.... even if the above theory is right it only works for perspective matrices.  Orthogonal matrices do not easily allow for reconstruction of the original eye.z from the clip coordinate.  Thus @tschw's suggestion of utilizing a vertex varying, e.g. ```vViewPosition``` in ThreeJS convention or something more specific to just this application (although I am not yet sure we actually need more bit precision, rather just actually having a correct depth is what I meant by accuracy), is the most robust solution solution.

**Comment by bhouston** [comment]
Fixed!
