### ISSUE TITLE
Problem with merge #8553 on Dev

### ISSUE THREAD

**Issue by rfm1201** [mrdoob/three.js#8556]
When a PerspectiveCamera is serialized, Object3D.js in the toJSON function does :
object.matrix = this.matrix.toArray();

When the parseObject function  of ObjectLoader does :
object = Object.assign(new THREE.PerspectiveCamera(), data );
the matrix element is an array and not a Matrix4.
This will be a problem when the matrix element will be used as a Matrix4 object, for example in the Three.js editor (just launch it to see the problem)

**Comment by mrdoob** [comment]
Yeah, I thought the `object = Object.assign(new THREE.PerspectiveCamera(), data )` approach was too aggressive. The object has other properties that may not work with that.

/ping @tschw

**Comment by tschw** [comment]
OK, I'll fix that.

Independent from that makes me rise the question why redundantly serialize matrices?

**Comment by tschw** [comment]
#8561

**Comment by mrdoob** [comment]
> Independent from that, makes me raise the question why redundantly serialize matrices?

Where?

**Comment by tschw** [comment]
@tschw 
> > Independent from that, makes me raise the question why redundantly serialize matrices?

@mrdoob 
> Where?

Hidden in the Camera base, in this particular case. There might be others. I guess all matrices should actually be reconstructible from other values?!

**Comment by Mugen87** [comment]
Should be solved via #8561
