### ISSUE TITLE
Figure out a way to remove 1.0/1000.0 hack from PointLight shadow maps

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8559]
##### Description of the problem

In the point light shadow map code we apply a scale factor of 1 / 1000 in both the distanceRGBA shader here:

https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderLib/distanceRGBA_frag.glsl#L12

And we also apply a similar scale when we do the comparisons in the shadow map code:

https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/shadowmap_pars_fragment.glsl#L205

It is a little tricky.  And also it is not optimal for quality - it basically is a fixed spotLight range of 1000.0, thus low precision for near distances, and it will not work for large distances greater than 1000.0.

This shouldn't be necessary if we could just scale the shadow map range by the range of the point light shadow.

Possible solutions: 
- Use pointLight.distance or 500 if not set - this is how SpotLight works.  (This is my preferred solution.)
- Or we should make the stored distance value non-linear to have a large range of accuracy but biased towards close things (logarithmic, etc.)
##### Three.js version
- [x] Dev
- [x] r75
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mkkellogg** [comment]
I like the first solution as well since it is consistent with SpotLight. If we go that route, maybe it makes sense to rename the `distanceRGBA` shader to something else since it will explicitly depend on a lighting-related uniform?

**Comment by tailsu** [comment]
People get bitten by this hack :confused: 

http://stackoverflow.com/questions/41840778/threejs-point-light-shadow-acting-like-a-spot-light

**Comment by bhouston** [comment]
@tailsu Did you want to try your hand at fixing it? :)
