### ISSUE TITLE
WebVR examples: Show "Exit VR" buttons when VR mode is entered

### ISSUE THREAD

**Issue by cvan** [mrdoob/three.js#8565]
##### Description of the problem 

1. Load https://rawgit.com/mrdoob/three.js/master/examples/webvr_cubes.html in [the Chromium WebVR builds](https://webvr.info/get-chrome/)
2. Click "Enter VR"
3. Notice VR stereo mode is entered, but the button still says "Enter VR"

The buttons should say "Exit VR" and upon clicking exit VR presentation.

##### Three.js version

- [x] Dev
- [x] r75

**Comment by mrdoob** [comment]
Hmmm, I assume this is in mirrored mode or something? What's your setup?

**Comment by mrdoob** [comment]
Done! (Requires WebVR 1.0 though)
