### ISSUE TITLE
Consider hiding WebVR API disclaimer message in Firefox Nightly

### ISSUE THREAD

**Issue by cvan** [mrdoob/three.js#8567]
##### Description of the problem 

1. Load any WebVR example in Firefox Nightly
2. Notice this message appears at the top of the page: `Your browser supports WebVR but not the latest version. See webvr.info for more info.`

Would it be kosher if this message were to be removed for folks using Firefox Nightly (which is on the old API; support is coming but we're behind)? Folks using the Chromium builds are already using the new builds with experimental WebVR v1.0 support, so this message affects only Firefox users.

##### Three.js version

- [x] Dev

##### Browser

- [x] Firefox Nightly

**Comment by mrdoob** [comment]
Yes. The purpose of that message is to "encourage" browsers to move their implementations to 1.0 😉

**Comment by db10101** [comment]
I am now receiving this message in any browser that I try to load WebVR

**Comment by mrdoob** [comment]
Which are...?

**Comment by LuccoJ** [comment]
I receive it on the latest Firefox and Chromium builds I could access (which are F-Droid's built called IceCatMobile and the one it gets using the getChromium app, respectively: IceCatMobile version 38.8.0, and Chromium just says "version Developer Build", so no idea).
