### ISSUE TITLE
Use unprefixed Fullscreen API in `VREffect`

### ISSUE THREAD

**Issue by cvan** [mrdoob/three.js#8568]
##### Description of the problem 

The vendor prefixes were dropped in Firefox Nightly for the Fullscreen API. And deprecation warnings are now thrown when using `mozRequestFullScreen` instead of `requestFullScreen`.

##### Three.js version

- [x] Dev
- [x] r75
- [x] ...

##### Browser

- [x] Firefox Nightly
- [x] Microsoft Edge (v13)

##### OS

- [x] All of them

**Comment by brianchirls** [comment]
I wanna give this a bump, because now there's a further complication. It seems that if you use `requestFullscreen` (not the lower case 's'), the `"mozfullscreenchange"` event does not fire. Only the un-prefixed event does.

I think we need to listen for the standard, un-prefixed event **and** at least one vendor prefixed event, since people may want to initiate full screen in other code. So you can't guarantee which one they'll use.

**Comment by cvan** [comment]
I opened #8570 to fix this but it wasn't accepted

**Comment by brianchirls** [comment]
It looks like that commit did a lot of other stuff too. I could maybe take a shot at it.

**Comment by cvan** [comment]
it was mostly to make the code DRY, but yeah it's just a little conditional logic in like three places and you should be good

**Comment by brianchirls** [comment]
@cvan Upon further testing, all the events fire regardless of which method you use to request full screen. I could have sworn that was not the case when I was testing it 3 days ago. Is this something that might have been fixed in Nightly since then?

**Comment by cvan** [comment]
> @cvan Upon further testing, all the events fire regardless of which method you use to request full screen. I could have sworn that was not the case when I was testing it 3 days ago. Is this something that might have been fixed in Nightly since then?

sounds strange to me. I've always seen `mozfullscreenchange` fire, since the vendor-prefixed API is deprecated not removed yet. if that was happening, it was certainly a bug - but I don't see anything in Bugzilla though. in any event, I think there should be code to handle the unprefixed `fullscreenchange` event and the `requestFullScreen` in addition to `mozRequestFullScreen`. I realise the WebVR v1.0 API is coming, but it might be for a while. it'd be best to just add the additional logic now.

**Comment by brianchirls** [comment]
Over the weekend, with my Mac, `mozfullscreenchange` was firing just fine, even if I started with unprefixed `requestFullscreen`. But now that I'm back in the office with my Windows machine, it's not happening, even on the latest Nightly.

So I'm gonna go ahead and submit a PR for this and #8776, and I'll double up the event listener.

**Comment by cvan** [comment]
@brianchirls have you filed a Firefox Bugzilla bug for it? if not, we can do that

**Comment by brianchirls** [comment]
@cvan No, I have not. I'm out of the office all week and away from my Windows machine, so unable to test a standalone case. Are you able to replicate? Can you post the bugzilla link here once you've done it?
