### ISSUE TITLE
typo in sample in Shape documentation page 

### ISSUE THREAD

**Issue by panlina** [mrdoob/three.js#8571]
##### Description of the problem 

The page:
[http://threejs.org/docs/#Reference/Extras.Core/Shape](http://threejs.org/docs/#Reference/Extras.Core/Shape)
The line:
```
var geometry = new THREE.ExtrudeGeometry( shape, extrudeSettings );
```
It should be `heartShape` instead of `shape`.

##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

**Comment by mrdoob** [comment]
You can fix the typo directly 😊
https://github.com/mrdoob/three.js/edit/dev/docs/api/extras/core/Shape.html
