### ISSUE TITLE
SSAO example is broken, just darkening based on normal direction

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8576]
##### Description of the problem

The SSAO shader should produce darker output in areas that are more enclosed.  The current SSAO example actually is just using the normal derived from the depth buffer and making it darker the more they are not facing the camera.

Not sure what it is trying to do but the current implementation is just broken - it is more like a directional light facing in the same direction as the camera:

![image](https://cloud.githubusercontent.com/assets/588541/14391177/88beb11c-fd88-11e5-9892-86373f32b2c4.png)

Link: http://threejs.org/examples/#webgl_postprocessing_ssao

Here is what an SSAO/SAO implementation should look like - enclosed regions are darkened, everything else (including non-camera facing normals) should be left alone:

![ao comparison 1](https://cloud.githubusercontent.com/assets/588541/14391126/3d4ec1d6-fd88-11e5-880f-9f83febc5705.png)

Link: https://clara.io/view/76f2e700-042d-4c80-bf0b-19e18d262513
...
##### Three.js version
- [x] Dev
- [x] r75
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by bhouston** [comment]
I'm going to be working on this as well.

**Comment by daoshengmu** [comment]
@bhouston I think you are right. If you need any assist, please feel free to tell me.

**Comment by monsterkodi** [comment]
hello. any news on this?

**Comment by leiamac** [comment]
Any news on this?
