### ISSUE TITLE
Can't convert a Texture to json without passing in an empty object

### ISSUE THREAD

**Issue by AndrewRayCode** [mrdoob/three.js#8581]
##### Description of the problem

[This commit](https://github.com/mrdoob/three.js/commit/25ffb41e6467468d26a9dc317926f9832f17da35) introduced a parameter to the Texture.toJSON API [on line 102](https://github.com/mrdoob/three.js/blob/bc0d71431e9a979926bd01d57cfee8ec28c6b59f/src/textures/Texture.js#L102):

```
toJSON: function ( meta ) {
```

If this parameter is not passed in, anyone calling `toJSON()` will get a hard crash.

```
$ node
    > var three = require('three');
    > new three.Texture().toJSON();

TypeError: Cannot read property 'textures' of undefined
at THREE.Texture.toJSON (node_modules/three/three.js:21524:12)
```

One solution here is to pass in an empty object. That doesn't really make sense, though, because it would be a confusing and undocumented API. Also consider the `JSON.stringify()` case:

```
$ node
    > var three = require('three');
    > JSON.stringify(new three.Texture());

TypeError: Cannot read property '8D889934-01AE-4074-BDC9-9CA926CF1270' of undefined
at THREE.Texture.toJSON (node_modules/three/three.js:21524:21)
```

**If a `Texture` is ever converted to JSON, it will crash.** `JSON.stringify` recursively calls `.toJSON()` on each nested object (if that method is defined), which also means that there's no easy way to convert an object containing a `Texture` to JSON without manually walking each key recursively and passing in an empty object myself. The following would crash, for example:

```
    > JSON.stringify({ a: ''cow', b: new three.Texture() });
```

[The commit in question](https://github.com/mrdoob/three.js/commit/25ffb41e6467468d26a9dc317926f9832f17da35) by @mrdoob references [this pull request](https://github.com/mrdoob/three.js/pull/6509) by @elephantatwork. I've looked at it briefly but can't figure out what's actually happening in this change.

This affects people who need to serialize Three.js data to save on a server. I ran in to it trying to export shaders that have textures from [ShaderFrog](http://shaderfrog.com/app).

**A quick solution** is just to check for if `meta` is passed in to the `toJSON` function in the source before using. I'm happy to make this change, however because of the confusing nature of the commits and API, I don't know if that's the correct change in this case.
##### Three.js version
- :white_check_mark: Dev
- :white_check_mark: r75

**Comment by mrdoob** [comment]
I guess it's a matter of turning this line:

https://github.com/mrdoob/three.js/blob/dev/src/textures/Texture.js#L104

Into this?

```js
if ( meta !== undefined && meta.textures[ this.uuid ] !== undefined ) {
```

**Comment by mchlr** [comment]
Hi,

I've ran into the same problem using THREE.js r84. The meta 'object' is/contains nothing more than an empty string ("").

@mrdoob: The suggested change did nothing for me. I'm still getting the same errors as Andrew. (Cannot read property 'E45DD103-BB6F-4289-A040-7561F4A3AA9B' of undefined at DataTexture.toJSON (three.js:1072))

<br>
Regards,
Michael

**Comment by autra** [comment]
I have a similar problem, but not because `meta` was undefined. It's due to `toJSON` behaviour. By default, it is called by `JSON.stringify` with the property name as first arguments.

Example, if I call:
```js
JSON.stringify({ foo: 'bar', group: someThreeGroup });
```
when trying to serialize group, it will call Object3D.prototype.toJSON with `group` as first argument. so meta will be the string `group` which is not handled at all by the current code. I have edited the documentation on MDN to reflect the [ECMAScript6 specs about toJSON](https://www.ecma-international.org/ecma-262/6.0/#sec-serializejsonproperty).

I'll try to see if I can write a patch quickly.

**Comment by autra** [comment]
The edited [mdn doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior).
