### ISSUE TITLE
Incorrect normal export using Blender JSON exporter

### ISSUE THREAD

**Issue by AndrewRayCode** [mrdoob/three.js#8592]
##### Description of the problem

Today I've been struggling with exporting a model from Blender to Three.js using the JSON exporter. I don't think the normals are getting exported correctly.

This error seems to happen with _any_ Blender export to .json, but I've included a very simple .blend file containing only a sphere.

[![screen shot 2016-04-10 at 11 09 09 pm](https://cloud.githubusercontent.com/assets/79215/14418198/6c7cc22e-ff71-11e5-909f-12e4b618358e.png)
**Download sphere.blend**](http://andrewray.me/stuff/sphere.blend)

I'm using [a simple glow shader](http://shaderfrog.com/app/view/5) from ShaderFrog. If you click "edit" you can see the source. Here's how it looks applied to a vanilla `Three.SphereGeometry`:

![screen shot 2016-04-10 at 11 11 27 pm](https://cloud.githubusercontent.com/assets/79215/14418215/9757f98c-ff71-11e5-9acc-5d8ecb92f0c4.png)
_The shader correctly applied to a vanilla Three sphere_

And here's how it looks when applied to the sphere exported from Blender to JSON:

![sphere-normals](https://cloud.githubusercontent.com/assets/79215/14418262/e7227b36-ff71-11e5-8254-5ae053aeca0c.gif)
_The shader incorrectly applied to a vanilla sphere exported from Blender_

You can see that the shader only appears correct from one angle, but distorted from other angles. The shader is not correctly "sticking" to the edge of the object, as it should based on the normal calculation in the shader source code.

If, in Three.js, if I call `mesh.geometry.computeVertexNormals()`, which clobbers the normals exported from Blender, then the shader is correct again:

![recalc-normals](https://cloud.githubusercontent.com/assets/79215/14418303/373a0e36-ff72-11e5-92cf-210b18015423.gif)
_The same Blender exported sphere with normals recalculated by Three_

Since normals are corrected and the shader works after calling `computeVertexNormals()`, I suspect there's a bug in the Blender exporter.

[Issue #3221, "Blender Scene Exporter normals wrong"](https://github.com/mrdoob/three.js/issues/3221) was opened 3 years ago by @willy-vvu. In the issue, he shows an older version(?) of the exporter that includes a "Flip YZ" option:

![flip](https://camo.githubusercontent.com/e7e387a99c70842cfaa134841c9c73b44a21a2c5/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333532393036352f3332323635312f36366235653737342d396136382d313165322d393564302d3735303963323233363363382e706e67)

Not only is this option not available in the current Blender to Three python script ([found here](https://github.com/mrdoob/three.js/tree/master/utils/exporters/blender/addons/io_three)), but I can't find any history of the text "Flip YZ" in the git history for the folder containing those scripts. I'm not sure what happened here.

**When exporting using Blender's native .obj exporter, and loaded into Three.js the normals are *fine.**\* Exporting to .obj and importing using the ObjLoader shows correct behavior with the above shader. Exporting the same object using the JSON exporter causes the normal error. Also note that Blender's default .obj exporter gives you an option for "forward" and "up" vectors:

![screen shot 2016-04-10 at 11 23 08 pm](https://cloud.githubusercontent.com/assets/79215/14418411/385c327a-ff73-11e5-882e-7230677eafea.png)

I'm not sure if these are the reason that the .obj export works correctly, but it seems suspicious that flipping vectors was mentioned in an older ticket.

I do **not** currently have a live running version of the json export using the shader, but I can provide one if it's required for debugging.
##### Three.js version
- :white_check_mark:  Dev
- :white_check_mark:  r75
  ##### Browser
- :white_check_mark: All of them
  ##### OS
- :white_check_mark: All of them

**Comment by makc** [comment]
maybe try to split into tris before exporting, might help? although I don't see why would it suddenly start rotate along with the model.

**Comment by Scharnvirk** [comment]
I have a similar issue:

![check](http://i.imgur.com/gUk4K3v.png)

The left one is exported from Blender using JSON exporter and right one is a basic three BoxGeometry.

I've tried this approach:

    mesh.geometry.computeVertexNormals();
    mesh.geometry.normalsNeedUpdate = true;


...but it doesn't help with the left cube, instead, if applied to right one, it messes up its normals too. I start to think that it is in fact blender export which got it right and BoxGeometry wrong? I am at total loss here :(

**Comment by DelvarWorld** [comment]
@Scharnvirk that's not related. In Blender you need to set up the normals correctly. Try selecting all faces and on the toolbar on the left, go to shading tab > "faces > flat"

**Comment by Scharnvirk** [comment]
Thanks. I'll look into that.

A quick test, however, tells me that changing that property in blender doesn't alter exported normals at all though, and I had it at "flat" anyway. And I've recalculated normals after changing the setting. We're talking about "Shading/UVs" tab in the menu available after pressing "T" in Edit Mode, right?

Also, I can show face normals vectors in Blender (they appear as little blue lines coming from the middle of faces) and they don't change at all when changing smooth/flat setting. Isn't it just a display setting in Blender which does not alter normals themselves?

Anyway yeah, "smooth" face setting in blender looks exactly like the exported cube as seen in Three.js. Almost as if blender was always exporting in Smooth mode?

**Comment by tschw** [comment]
> And here's how it looks when applied to the sphere exported from Blender to JSON

Looks like a transform gone wrong, vertices got rotated but not the normals or the other way around...

**Comment by michaelitvin** [comment]
I'm seeing the normals issue again with Three.js r79 blender exporter with Blender 2.77. Reverting commit bb0ff5d5856a3f226ff41edc5e58e7b14927a3dc solved the problem for me.

**Comment by tschw** [comment]
@michaelitvin 
IIRC https://github.com/mrdoob/three.js/commit/bb0ff5d5856a3f226ff41edc5e58e7b14927a3dc was about solving the issue in other cases. It appears the required transform depends on the export settings. Could you share yours, please?

**Comment by dherben** [comment]
I've been seeing this issue with the blender exporter since r76. Reverting commit bb0ff5d does indeed fix it. It seems like such an obvious issue that I wonder how not more people are running into this. 

I replicated the problem with a simple cube+light setup in blender, exported the scene with different versions of the blender exporter, and loaded with ObjectLoader in the simplest possible configuration.

Below is a screenshot of the result. Left is r74, Right r77. The light (with blue helper) is behind and on top of the cube. The client side version does not matter, only exporter version. Left is ok, right is fubar.
![normals_error](https://cloud.githubusercontent.com/assets/4228100/17015864/ac20ee86-4f2c-11e6-9943-7055e14ee250.png)

Export settings were the following:
![export settings](https://cloud.githubusercontent.com/assets/4228100/17015970/2401ebd0-4f2d-11e6-9236-2367237893b1.png)

Here are the generated jsons: 
[jsons.zip](https://github.com/mrdoob/three.js/files/375445/jsons.zip)

And here is the blend file:
[blendfile.zip](https://github.com/mrdoob/three.js/files/375448/blendfile.zip)

I put up a jsbin with the different versions available. 

https://jsbin.com/kawaten/edit?html,output

Hope this is useful to someone. I have simply reverted the commit in my fork, and it seems to do everything right. I don't have any animations or bones/armatures stuff in my scenes, which is what prompted this commit in the first place.

**Comment by DelvarWorld** [comment]
Blender r80 currently exports all normals with Y and Z flipped. I'm not sure normals have ever been exporting correctly. Here's a script to fix the geometry after importing in Three.js:

                geometry.faces.forEach( face => {
                    face.normal = new Vector3(
                        face.normal.x, face.normal.z, -face.normal.y
                    );
                    face.vertexNormals = face.vertexNormals.map(
                        vn => new Vector3( vn.x, vn.z, -vn.y )
                    );
                });
                geometry.normalsNeedUpdate = true;
                geometry.verticesNeedUpdate = true;

**Comment by postolka** [comment]
JS & jQuery:
<pre>
function fixNormal(vector) {
	var t = vector.y;
	vector.y = -vector.z;
	vector.z = t;
}

$.each(mesh.faces, function (i, face) {
	fixNormal(face.normal);
	$.each(face.vertexNormals, function (i, vertex) {
		if (!vertex.hasOwnProperty('fixed')) {
			fixNormal(vertex);
			vertex.fixed = true;
		}
	});
});
mesh.normalsNeedUpdate = true;
mesh.verticesNeedUpdate = true;
</pre>

**Comment by feiss** [comment]
What I see is differences whether the **scene** checkbox is activated or not. Here is the default blender plane:

**SCENE ON**
```
{
    "materials":[],
    "images":[],
    "geometries":[{
        "type":"Geometry",
        "data":{
            "faces":[33,0,1,3,2,0,0,0,0],
            "uvs":[],
            "normals":[0,1,-0],
            "metadata":{
                "uvs":0,
                "generator":"io_three",
                "normals":1,
                "version":3,
                "faces":1,
                "vertices":4
            },
            "name":"PlaneGeometry.1",
            "vertices":[-1,-1,0,1,-1,0,-1,1,0,1,1,0]
        },
        "uuid":"AFF5F7EC-488A-44E8-BDD6-33C078E71AEE"
    }],
    "metadata":{
        "type":"Object",
        "generator":"io_three",
        "version":4.4
    },
    "textures":[],
    "object":{
        "type":"Scene",
        "children":[{
            "name":"Plane",
            "uuid":"BF37A9AA-BEC3-46CA-A82C-647FAD63807F",
            "matrix":[-1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1],
            "visible":true,
            "type":"Mesh",
            "castShadow":false,
            "receiveShadow":false,
            "geometry":"AFF5F7EC-488A-44E8-BDD6-33C078E71AEE"
        }],
        "uuid":"D0BD86CC-9DE4-4265-9464-7F47E5900083",
        "matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]
    },
    "animations":[{
        "tracks":[],
        "name":"default",
        "fps":24
    }]
}
```

**SCENE OFF**
```
{
    "faces":[33,0,1,3,2,0,0,0,0],
    "uvs":[],
    "normals":[0,-0,-1],
    "metadata":{
        "type":"Geometry",
        "uvs":0,
        "generator":"io_three",
        "normals":1,
        "version":3,
        "faces":1,
        "vertices":4
    },
    "name":"PlaneGeometry.2",
    "vertices":[-1,0,1,1,0,1,-1,-0,-1,1,-0,-1]
}
```

in the scene mode, vertices coordinates are not flipped, but normals are ok (0,1,-0). If scene is not checked, vertices coords are flipped, but normals are not. Is his the expected behaviour?

**Comment by mrdoob** [comment]
> Is his the expected behaviour?

It definitely is not the expected behavior. It's now a long standing bug...
This observation probably makes it closer to be finally fixed though!

**Comment by mrdoob** [comment]
Can you see the same behaviour when exporting as `BufferGeometry` instead of `Geometry` though?

**Comment by feiss** [comment]
With Buffer geometries. Something similar

**SCENE OFF**
```
{
    "metadata":{
        "version":3,
        "position":4,
        "normal":4,
        "generator":"io_three",
        "type":"BufferGeometry"
    },
    "data":{
        "attributes":{
            "position":{
                "array":[1,0,1,-1,-0,-1,-1,0,1,1,-0,-1],
                "itemSize":3,
                "type":"Float32Array"
            },
            "normal":{
                "array":[0,1,-0,0,1,-0,0,1,-0,0,1,-0],
                "itemSize":3,
                "type":"Float32Array"
            }
        }
    }
}
```

**SCENE ON**
```
{
    "images":[],
    "object":{
        "uuid":"6B4A3B3F-11EB-4086-9831-B6E282A3BC3B",
        "children":[{
            "name":"Plane",
            "uuid":"E8966D80-8C5F-419C-91ED-32BDADE1C5A7",
            "matrix":[-1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1],
            "visible":true,
            "type":"Mesh",
            "castShadow":false,
            "receiveShadow":false,
            "geometry":"D8830624-3B68-46E8-96FC-9906BC39E527"
        }],
        "matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
        "type":"Scene"
    },
    "textures":[],
    "materials":[],
    "metadata":{
        "type":"Object",
        "generator":"io_three",
        "version":4.4
    },
    "geometries":[{
        "uuid":"D8830624-3B68-46E8-96FC-9906BC39E527",
        "name":"PlaneGeometry.1",
        "metadata":{
            "position":4,
            "normal":4,
            "generator":"io_three",
            "version":3
        },
        "data":{
            "index":{
                "array":[0,1,2,0,3,1],
                "itemSize":1,
                "type":"Uint16Array"
            },
            "attributes":{
                "position":{
                    "array":[1,-1,0,-1,1,0,-1,-1,0,1,1,0],
                    "itemSize":3,
                    "type":"Float32Array"
                },
                "normal":{
                    "array":[-0,0,1,-0,0,1,-0,0,1,-0,0,1],
                    "itemSize":3,
                    "type":"Float32Array"
                }
            }
        },
        "type":"BufferGeometry"
    }],
    "animations":[{
        "name":"default",
        "tracks":[],
        "fps":24
    }]
}
```

**Comment by mrdoob** [comment]
We're getting closer! 😊

**Comment by jonoasan** [comment]
I found three places where normals where flipped in exporter/api/geometry.py
these occured at lines 127, 311 & 910
changing these back to following fixes the issues for me.
`vector = (normal.x, normal.y, normal.z) if face.use_smooth else (face.normal.x, face.normal.y, face.normal.z)`
`normal = (normal[0], normal[1], normal[2])`
`vector = (normal.x, normal.y, normal.z) if face.use_smooth else (face.normal.x, face.normal.y, face.normal.z)`

**Comment by zydecode** [comment]
@jonoasan - in the current version of the exporter, there is no geometry.py in the api directory, however the lines you refer to are in the mesh.py file.. are you working with an old version of the exporter, or was that a typo?

Also - of the three lines you posted, the first and last are identical to the lines in mesh.py, no changes are needed. I tried your fix just changing the center line, normal = (normal[0], normal[1], normal[2]), however this results in a script error on export.

**Comment by zydecode** [comment]
following up on changes to the blender exporter - I was able to resolve the exporter issue by changing  line 619 of exporter/api/mesh.py to:

 vector = (vector[0], vector[1], vector[2])

**Comment by feiss** [comment]
@postolka fix works for me, with a change: when exporting in scene mode, face normals don't need to be fixed. 
```
function fixNormal(vector) {
    var t = vector.y;
    vector.y = -vector.z;
    vector.z = t;
}

$.each(mesh.faces, function (i, face) {

    /// fixNormal(face.normal);  <--- NOT NEEDED

    $.each(face.vertexNormals, function (i, vertex) {
        if (!vertex.hasOwnProperty('fixed')) {
            fixNormal(vertex);
            vertex.fixed = true;
        }
    });
});
mesh.normalsNeedUpdate = true;
mesh.verticesNeedUpdate = true;
```

**Comment by oomarsmanoo** [comment]
@zydecode your fix has worked for me too, thank you :)

**Comment by imm3lman** [comment]
Also got it working with @feiss's code and @zydecode's mesh.py modification.
Thanks a lot guys!

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
