### ISSUE TITLE
Depth Texture extension breaks Stencil buffers

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8596]
##### Description of the problem

@kintel wrote:

> It looks like this breaks stencil buffers; rendering to depth textures requires stencil buffers to have a compatible format, if that's enabled (using a DEPTH_STENCIL_ATTACHMENT).
> See my code from #5402 which sets this up correctly: https://github.com/mrdoob/three.js/pull/5402/files#diff-c0e88b98497597a015ecf238e91ac3a0R3300
> 
> Using stencil buffers might not be the most common operation for a rendering framework, but for my use-case (CSG rendering), that was a key requirement when I first implemented depth texture support.

[Source](https://github.com/mrdoob/three.js/pull/8577#issuecomment-208172201)
##### Three.js version
- [x] Dev
- [ ] r75
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
Should be fixed via #9368.
