### ISSUE TITLE
Default Box3 multiplied by Matrix4 is not empty()

### ISSUE THREAD

**Issue by nk327** [mrdoob/three.js#8620]
##### Description of the problem 

If all of the coordinates in `Box3` are set to `NaN`, then `empty()` returns false. This is troublesome for cases where we use `applyMatrix4()` transformations to empty boxes and expect them to remain empty.

##### Three.js version

- [ ] Dev
- [x] r75
- [x] r73

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by tschw** [comment]
A box of `NaN`s really shouldn't be anything, so your title reads like "please direct me to Stackoverflow".

> This is troublesome for cases where we use applyMatrix4() transformations to empty boxes and expect them to remain empty.

This *is* an interesting case, however. 

I think it should be fixed by documentation: `if ( ! box.empty() ) box.applyMatrix4( m )` is not too hard to write and in most typical uses there won't be empty boxes around.

**Comment by nk327** [comment]
Thanks for the heads up @tschw, changed the title to be more informative. On your point of it not being anything, then empty() should throw an error, otherwise we have a silent failure and several hours spent figuring it out. Also, the behavior is inconsistent; if we only change one `min` number to `NaN`, then empty returns true. 

Alternatively, the `applyMatrix4()` to a default `Box3`should not create `NaN`s.

As far as use cases go, I don't know what other people's code does, but logically the emptiness property of a bounding box should not change no matter what transformation you apply to it. Otherwise are duplicating code for every time we use a function that might return an empty bounding box

**Comment by tschw** [comment]
> Alternatively, the applyMatrix4() to a default Box3should not create NaNs.

I prefer to keep it lean. It may affect rendering time in case we want to use it for culling.

> As far as use cases go, I don't know what other people's code does

Me not either. The math subset, primarily serves the rest of Three.js :).

**Comment by WestLangley** [comment]
Code
```javascript
var m = new THREE.Matrix4().identity();

var box = new THREE.Box3();
console.log( box.isEmpty() ); // true

box.applyMatrix4( m );
console.log( box.isEmpty() ); // false

```

**Comment by bhouston** [comment]
This is also fixed in this PR here: https://github.com/mrdoob/three.js/pull/8627

**Comment by bhouston** [comment]
This should be closed now.
