### ISSUE TITLE
Bug with Text Geometry on Samsung S7

### ISSUE THREAD

**Issue by iRomano** [mrdoob/three.js#8623]
Hi

I found bug with Text Geometry on Samsung S7. Text not showing.
Sample: threejs.org/examples/webgl_geometry_text
Console: Unexpected token y
(anonymous function) @ three.js:18315
(anonymous function) @ three.js:18220

Three.js 76 dev

In firefox or default browser - all working.

...
##### Three.js version
- [x] Dev r76
##### Browser
- [x] Chrome
##### OS
- [x] Android
##### Hardware Requirements (graphics card, VR Device, ...)

Samsung S7
Android 6.0.1

**Comment by iRomano** [comment]
Hi @mrdoob 
We have same problem on Samsung Note 3, Android 5.0.

But, if you are using incognito mode or If you disabled safe mode, you will see this example with text.

**Comment by Mugen87** [comment]
Closing. If the problem still exists with the latest `three.js` release, we can reopen the issue.
