### ISSUE TITLE
Exporting mesh from blender to three.js, "doubleSided" property not exporting even if checked

### ISSUE THREAD

**Issue by dxshindeo** [mrdoob/three.js#8624]
Made a mesh in blender (2.77). Under the "Materials->THREE" I checked "Double-sided" option, but once exported, that option under "materials" is not showing up at all. Exporting materials and face materials are both enabled on three.js exporter plugin.

**Fragment of JSON currently:**

```js
    "materials":[{
        xxx
        xxx
        xxx
    }],
```

**Should be:**

```js
    "materials":[{
        xxx
        xxx
        xxx
        "doubleSided":true // or false of course
    }],
```

**Comment by tschw** [comment]
It should read `"side": 2`...

**Comment by dxshindeo** [comment]
There is no "side": 2 after export, and typing it manually doesn't make the material double sided. But "doubleSided":true does.

**Comment by tschw** [comment]
> There is no "side": 2 after export, and typing it manually doesn't make the material double sided. But "doubleSided":true does.

Thanks for checking, and for enlightening me on that irregularity :).

Is your report against `r75` or `dev` or both?
Can the problem be reproduced with the default cube? If not, please provide a minimal `.blend` file.

**Comment by dxshindeo** [comment]
Yes, the exporter is from `r75` and the problem can be reproduced with the default cube.
