### ISSUE TITLE
Rigged collada model crashes three

### ISSUE THREAD

**Issue by DelvarWorld** [mrdoob/three.js#8636]
##### Description of the problem 

I'm trying to import a rigged Collada mesh from Blender. I'm using the latest [ColladaLoader.js](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/ColladaLoader.js) file.

It crashes on [this line in SkinnedMesh](https://github.com/mrdoob/three.js/blob/cf584a60bdfd24c42eaa81d484533364742bda44/src/objects/SkinnedMesh.js#L48) with the error

> Uncaught TypeError: Cannot read property 'add' of undefined

The line in question:

```js
bones[ gbone.parent ].add( bones[ b ] );
```

You can download my test mesh: [test-export.dae.zip](https://github.com/mrdoob/three.js/files/220121/test-export.dae.zip)

That happens because it tries to look up `bones[ gbone.parent ]`, but `gbone.parent` is a string, and `bones` is an array. So it returns undefined and crashes

##### Three.js version

- :white_check_mark:  Dev
- :white_check_mark:  r75

**Comment by mrdoob** [comment]
Fixed crash. Thanks!
