### ISSUE TITLE
OBJ + MTL -  Materail not loading

### ISSUE THREAD

**Issue by ksabariraj** [mrdoob/three.js#8640]
##### Description of the problem 
After I update to r75 (OBJ + MTL loader) the material is not loading. It's working good in OBJMTLLoader.
 
```javascript
var mtlLoader = new THREE.MTLLoader();
mtlLoader.setBaseUrl( "new/ABC_blocks/" );
mtlLoader.setPath(  "new/ABC_blocks/"  );
mtlLoader.load( "abc.mtl", function( materials ) {
    materials.preload();
    var objLoader = new THREE.OBJLoader();
    objLoader.setMaterials( materials );
    objLoader.setPath(  "new/ABC_blocks/"  );
    objLoader.load("abc.obj", function ( object ) {
        scene.add(object);
    }, onProgress, onError );
});
```
##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by jonnenauha** [comment]
Any way you could provide the files? Is it not loading textures or anything at all?

I just noticed there is `mtlLoader.setBaseUrl` that seems to be used for resolving texture refs. https://github.com/mrdoob/three.js/blob/r75/examples/js/loaders/MTLLoader.js#L37-L43 

Looks like without that it will just fetch textures as a relative ref, not relative to the .mtl if you are using the path system. By the comment in the code looks like these two should be merged, or this.path used instead if this.baseUrl is not set. One might still want to override where textures are fetches, I suppose.

**Comment by ksabariraj** [comment]
Hi,

Sorry for the delay

Please find the obj and mtl in the below url.
https://drive.google.com/open?id=0B8RHl2n48gDWVlR1QXQwVVFmeVk

Thanks.

**Comment by jonnenauha** [comment]
Alright, I looked into this. Its not a failure in the MTLLoader but in ObjLoader. Same issue as #8681 and #8203.

Should get fixed once that is taken care of. Its only finding one submesh from the lamp .obj. It is assigning the last encountered material into it, which is almost black. Looking at Blenders rendering of it, looks like that black one is for light bulb base inside. Your obj is defining one object but changing material mid face declaration, which is not yet supported by ObjLoader.

I'll get back to you when there is progress. What version of three.js are you using? r76 (released today) has the latest ObjLoader code which I will be modifying. If you have r76 you can pick the new loader when fixes are in the `dev` branch.

**Comment by jonnenauha** [comment]
I've fixed loading of your asset in my above PR, lets see when it gets merged.

![objloader_lamp](https://cloud.githubusercontent.com/assets/157519/14692030/40b5a144-075d-11e6-8156-e731645f0174.png)

**Comment by jonnenauha** [comment]
Oh btw. I made another PR that touches your code example. Setting all those paths looked like repetitive work and something that can be automated.

If PR https://github.com/mrdoob/three.js/pull/8689 gets merged you can do this

```js
var mtlLoader = new THREE.MTLLoader();
mtlLoader.load( "new/ABC_blocks/abc.mtl", function( materials ) {
    materials.preload();
    var objLoader = new THREE.OBJLoader();
    objLoader.setMaterials( materials );
    objLoader.load("new/ABC_blocks/abc.obj", function ( object ) {
        scene.add(object);
    }, onProgress, onError );
});
```

If your mtl and textures are in the same directory. This will also work if they are in a subfolder next to the mtl.

**Comment by ksabariraj** [comment]
It's working now 👍 Thanks.

**Comment by tedyhabtegebrial** [comment]
Hi, @ksabariraj @jonnenauha 
It seems I couldn't load an OBJ file. I used the script given under the examples folder.
I have tested different camera positions and texture files.  

For reference, I am putting a link to the OBJ model and code snnippet.
Model:  https://www.dropbox.com/s/qlhpyi3w5vt1uz5/model.obj?dl=0

				THREE.Loader.Handlers.add( /\.dds$/i, new THREE.DDSLoader() );

				var mtlLoader = new THREE.MTLLoader();
				mtlLoader.setPath( 'obj/shapenet/' );
				mtlLoader.load( 'model.mtl', function( materials ) {

					materials.preload();

					var objLoader = new THREE.OBJLoader();
					objLoader.setMaterials( materials );
					objLoader.setPath( 'obj/shapenet/' );
					objLoader.load( 'model.obj', function ( object ) {

						object.position.x = 0;
						object.position.y = 0;
						object.position.z = 0;
						scene.add( object );

					}, onProgress, onError );

				});

ps: I can load the model in VTK and Blender.

Any reply is  appreciated.

Teddy

**Comment by ksabariraj** [comment]
Hi Teddy,

I hope the below code sample will help you.

Note: After adding the `mtlLoader.setBaseUrl(path);`, the material is working.
```
var path = 'obj/shapenet';
var filename = 'model.mtl';
var mtlLoader = new THREE.MTLLoader();
mtlLoader.setBaseUrl(path);
mtlLoader.setPath(path);
mtlLoader.load(filename, function(materials) {
  materials.preload();
  var objLoader = new THREE.OBJLoader();
  objLoader.setMaterials(materials);
  objLoader.setPath(path);
  objLoader.load(filename.replace('.mtl', '.obj'), function(object) {

  }, null, null);
});
```

Thanks,
Sabari.

**Comment by jonnenauha** [comment]
@tedyhabtegebrial what three.js version are you using? `setBaseUrl` should not be needed in your case with >= r76. If older, then its needed for textures to resolve correctly. 

I can take a look what the bug is if you are using >= r76.

**Comment by tedyhabtegebrial** [comment]
Thanks for helping out @ksabariraj 
@jonnenauha, I am using three.js r77. I can't still load it.
