### ISSUE TITLE
THREE.BoxGeometry is not a constructor

### ISSUE THREAD

**Issue by pyenthu** [mrdoob/three.js#8642]
##### Description of the problem 
Just trying to create a cube and get this error.
THREE.BoxGeometry is not a constructor
...

##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [X] Linux
- [ ] Android
- [ ] IOS

**Comment by pyenthu** [comment]
Latest release

**Comment by Mugen87** [comment]
Can you provide an example at jsfiddle? Our [starter example](http://jsfiddle.net/hfj7gm6t/) uses `BoxGeometry` without errors.

**Comment by pyenthu** [comment]
Thanks it works fine.  I believe there was an issue with my version retrieval.
