### ISSUE TITLE
ThreeJS r75 bindTexture: textures can not be used with multiple targets

### ISSUE THREAD

**Issue by fallingC0de** [mrdoob/three.js#8644]
##### Description of the problem 
My code is triggering this warning in ThreeJS r75:

In Chrome and Firefox, the warning is:
bindTexture: textures can not be used with multiple targets.

In Microsoft Edge, the warning is:
WEBGL11120: INVALID_OPERATION: bindTexture: Passed in texture target and format must match the one originally used to define the texture

I have a basic understanding of the error.  

If I remove the 2 cubeCameras I create for reflection purposes, the warning isn't triggered.

My questions are:  Is the warning a bug?  Should the cubeCameras be triggering this warning?  Am I creating the cubeCameras in way that isn't correct for r75?

This is how I create them:

    gongRef = new THREE.CubeCamera(1, 32000, 1024);

This is how I add them to the scene:

    scene.add(gongRef );

This is how I apply them:

    gongMat = new THREE.MeshPhongMaterial({
			color:"rgb(240,240,240)",
			specular:"rgb(240,240,240)",
			shininess:200,
			emissive:"rgb(140,140,140)",
			visible:true,
			wireframe:false,
			envMap:gongRef.renderTarget,
			reflectivity: 0.8,
			emissiveIntensity: 1.0
			});

This is how I update them:

    gongRef.position.copy(theGong.position);
    theGong.visible = false;				
    gongRef.updateCubeMap( renderer, scene );
    theGong.visible = true;

...

##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Hardware isn't relevant.

**Comment by mrdoob** [comment]
I think this has already been fixed in the `dev` branch.
Wubba lubba dub dub!

**Comment by fallingC0de** [comment]
@mrdoob I appreciate the response.  Time to get schwifty!

**Comment by carstenschwede** [comment]
@fallingC0de can you provide a fiddle and confirm it's been fixed in `dev`?

**Comment by fallingC0de** [comment]
<a href="http://jsfiddle.net/ne7gjdnq/76/" target="_blank">Fiddle</a>

**Comment by fallingC0de** [comment]
@mrdoob should i close this?  or are you the only one who should close issues?

**Comment by mrdoob** [comment]
BURGERTIME!!
