### ISSUE TITLE
PlaneGeometry constructor parameters are not accessible

### ISSUE THREAD

**Issue by SET001** [mrdoob/three.js#8645]
##### Description of the problem 

According to [PlaneGeometry documentation](http://threejs.org/docs/#Reference/Extras.Geometries/PlaneGeometry) 

> Each of the contructor parameters is accessible as a property of the same name. Any modification of these properties after instantiation does not change the geometry.

However they are not accessible - https://jsfiddle.net/zuv4rwq6/

##### Three.js version

- [X] r75

**Comment by SET001** [comment]
Just notices all this parameters accessible trough `parameters` property of geometry. Documentation should be updated.

**Comment by Mugen87** [comment]
@ezekeal has already done this in `dev`, see aac0d399457a31ca101552ec2fe33f1fef87144b
