### ISSUE TITLE
mipmaps array empty

### ISSUE THREAD

**Issue by aferriss** [mrdoob/three.js#8646]
##### Description of the problem 
After loading a texture, nothing appears in the mipmaps array. The image is a pot texture (1024x1024). I was under the assumption that the mipmaps were generated at the time the image is loaded?

````
function test(){
	var loader = new THREE.TextureLoader();
	var im = loader.load('img.jpg', function(tex){
		console.log(tex);
	});
}
test();
````

![screen shot 2016-04-15 at 12 06 49 pm](https://cloud.githubusercontent.com/assets/3698659/14572267/b09ee1be-0302-11e6-84b2-05ece3449461.png)
...

##### Three.js version

- [ ] Dev
- [x] r75
- [x] r71

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
- [x] OSX

**Comment by WestLangley** [comment]
The mipmaps array is only used to pass in your own mipmaps. The documentation is incorrect. Auto-generated mipmaps reside on the GPU.

http://threejs.org/examples/webgl_materials_texture_manualmipmap.html

**Comment by aferriss** [comment]
@WestLangley Ah I see, the docs are sort of confusing about this. I realize now I can access the mipmap textures in the shader by
````
float mipBias = 3.0;
vec4 mip = texture2D(src, vUv, mipBias);
````

**Comment by WestLangley** [comment]
@mrdoob In the `Texture` docs, we need to correct the mipmaps array definition.

Replace

    Array of mipmaps generated.

with

    Array of user-specified mipmaps (optional).

For some reason, when I try to edit the file online, every line of the file is replaced. Go figure.

**Comment by mrdoob** [comment]
> For some reason, when I try to edit the file online, every line of the file is replaced. Go figure.

That's ok. That's just github editor changing the line breaks mode.

**Comment by WestLangley** [comment]
OK. Docs updated.

**Comment by mrdoob** [comment]
Thanks!
