### ISSUE TITLE
Include ShadowMaterial in three.js

### ISSUE THREAD

**Issue by nikkimoreaux** [mrdoob/three.js#8659]
##### Description of the problem 

Hi! I've upgraded one of my app from r70 to r75, and I've seen that MeshBasicMaterial don't support shadows anymore. It's fairly embarrassing, as MeshBasicMaterial was the only material usable for compositing on a webpage (ie. on a flat colored background). 
Still, [ShadowMaterial](https://github.com/mrdoob/three.js/blob/master/examples/js/materials/ShadowMaterial.js) look like a great alternative for this use case. I think it should be included within three.js :)

##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by makc** [comment]
not at all, it conflates the shadows from multiple sources, so I had to alter it. and altering is sort of more natural with the code that is in separate file all along.

**Comment by mrdoob** [comment]
conflates?

**Comment by makc** [comment]
yes? I had to replace THREE.ShaderChunk["shadowmask_pars_fragment"] with
```glsl
            "float getShadowMask() {\n\
                float shadow = 0.0;\n\
                #ifdef USE_SHADOWMAP\n\
                #if NUM_DIR_LIGHTS > 0\n\
                DirectionalLight directionalLight;\n\
                for ( int i = 0; i < NUM_DIR_LIGHTS; i ++ ) {\n\
                    directionalLight = directionalLights[ i ];\n\
                    shadow += bool( directionalLight.shadow ) ? getShadow( directionalShadowMap[ i ], directionalLight.shadowMapSize, directionalLight.shadowBias, directionalLight.shadowRadius, vDirectionalShadowCoord[ i ] ) / float(NUM_DIR_LIGHTS) : 0.0;\n\
                }\n\
                #endif\n\
                #endif\n\
                return shadow;\n\
            }",
```
in there.

**Comment by mrdoob** [comment]
Ah! I see...

**Comment by fallenartist** [comment]
A similar [use case](https://youtu.be/0dRM2FFhNq0) I've been struggling to achieve in r76 – to render only shadows and hide everything else. With `MeshBasicMaterial` having shadows enabled it was possible... Any ideas?

**Comment by makc** [comment]
@fallenartist shadow material should be exactly what you need

**Comment by mrdoob** [comment]
Yeah... I think `ShadowMaterial` will have to get moved to core. I'll do it later today.

**Comment by fallenartist** [comment]
@makc yes, [almost](http://codepen.io/znak/pen/bpxXrV?editors=0010)! I need the material to be opaque, not transparent. Would that be possible? Also, while the self shadow on the Collada model is visible (albeit with some artifacts), it's not on the box geometry...

**Comment by makc** [comment]
@fallenartist as long as ShadowMaterial is not in core yet, you can edit the shader, but - why dont you just make the background white?

**Comment by makc** [comment]
@fallenartist ah, sorry, did not check your link (

**Comment by makc** [comment]
@fallenartist back from watching the movie ) here goes opaque version: http://codepen.io/anon/pen/vGVwvK?editors=0010 but I think you might need shadow bias there

**Comment by fallenartist** [comment]
Thanks @makc 
BTW did something change in the library? I see only a white page now.
BTW2 @mrdoob have you considered implementing [Sample Distribution Shadow Maps](https://software.intel.com/en-us/articles/sample-distribution-shadow-maps)? I've read somewhere it greatly improves results...

**Comment by mrdoob** [comment]
> BTW did something change in the library? I see only a white page now.

I promoted ShadowMaterial to core 😊 468a86c15b17f5c6c5d8eac1f5d244a58bb52c6b

> BTW2 @mrdoob have you considered implementing [Sample Distribution Shadow Maps](https://software.intel.com/en-us/articles/sample-distribution-shadow-maps)? I've read somewhere it greatly improves results...

That looks great! Some day, some day...
