### ISSUE TITLE
Migration guide: add info about LineSegments in r72

### ISSUE THREAD

**Issue by vakorol** [mrdoob/three.js#8664]
I recently upgraded from r71 to r75 following the migration guide (https://github.com/mrdoob/three.js/wiki/Migration) and noticed the warnings:

    LinePieces mode is now a LineSegments class.

This has been introduced in r72. Maybe this should be added to the migration guide for r71->r72 ?

**Comment by mrdoob** [comment]
The Migration page is a public wiki. Feel free to help by adding the missing bits.

**Comment by vakorol** [comment]
updated wiki, see section "r71 -> r72":
https://github.com/mrdoob/three.js/wiki/Migration

**Comment by mrdoob** [comment]
Thanks!
