### ISSUE TITLE
Blender exporter flips some faces

### ISSUE THREAD

**Issue by DelvarWorld** [mrdoob/three.js#8673]
##### Description of the problem 

Here's a close up of the mouth in Blender:

![screen shot 2016-04-18 at 8 51 34 pm](https://cloud.githubusercontent.com/assets/79215/14627237/6214b51c-05a7-11e6-8176-f42710378f6e.png)

It's a little difficult to see but the blue lines are the normals of each face. You can see the normals inside the mouth are pointing the correct direction.

When exported to Three, the faces inside the mouth are flipped. Here's two screenshots from the editor showing the flipped faces:

![screen shot 2016-04-18 at 8 52 55 pm](https://cloud.githubusercontent.com/assets/79215/14627269/940adf6a-05a7-11e6-8c3b-6553c6273da0.png)

![screen shot 2016-04-18 at 8 53 41 pm](https://cloud.githubusercontent.com/assets/79215/14627280/a6dba07a-05a7-11e6-91fd-62c3f06412cc.png)

You can see through the empty eye socket that the faces for the mouth are pointing the wrong way, into the head. This happens even if the normals are flipped inside the mouth. It also happens even I call `geometry.computeVertexNormals()`.

The only fix I've found so far is to set the object's material to `DoubleSide` after import.

[You can download the mesh illustrating the problem here](https://github.com/mrdoob/three.js/files/225206/ghost-head.json.zip)

##### Three.js version

- ☑️  Dev
- ☑️  r75

**Comment by yrns** [comment]
@DelvarWorld The exporter will run "make normals consistent" on the mesh if it has modifiers. This step can flip already correct normals. It's intended to correct problems with normals after modifiers are applied by the exporter. You can avoid this step by applying modifiers before you export.

The fix is probably to make this step an option in the exporter.
