### ISSUE TITLE
bounding box wrongly includes (0,0,0)

### ISSUE THREAD

**Issue by grzegorzborowiak** [mrdoob/three.js#8674]
##### Description of the problem 

I observed that bounding boxes are computed such way as point (0, 0, 0) belonged to the object even if it doesn't.
For example, if the object is a sphere centered at (2, 2, 2) with radius 1, its bounding box should be ((1, 1, 1), (3, 3, 3)), but is computed as ((0, 0, 0), (3, 3, 3)).
I believe this is because of computeBoundingBox function in src/core/BufferGeometry.js:

			if ( positions === undefined || positions.length === 0 ) {
				this.boundingBox.min.set( 0, 0, 0 );
				this.boundingBox.max.set( 0, 0, 0 );
			}

I believe it should be something like:

			if ( positions === undefined || positions.length === 0 ) {
				this.makeEmpty();
			}

because bounding box of an empty set of points is certainly not ((0, 0, 0), (0, 0, 0)); its something uncomputable, like 1/0, 0^0 or log(-1) and should be represented as some NaN or null-like entity.

In version 68 it worked well (IIRC).

##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
I think you're correct.

**Comment by mrdoob** [comment]
Should be fixed now. Thanks!
