### ISSUE TITLE
r76 - Creating an audioListener crashes Internet Explorer

### ISSUE THREAD

**Issue by dandandan9** [mrdoob/three.js#8683]
**Description of the problem**
I just updated to the new version, and using Internet Explorer, it crashes with the error "Object doesn't support this action" on line 16680 
`"context = new ( window.AudioContext || window.webkitAudioContext )();"`
This only seems to occur when trying to create a new audioListener.

It doesn't crash on the other browsers, but as I haven't got audio working yet, it may stop the use of audio on those.

**Three.js version**
r76

**Browser**

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer

**Comment by RemusMar** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/AudioContext 
Internet Explorer ---> No support

**Comment by dandandan9** [comment]
That... would probably be why. My bad. What's the way around this?

**Comment by RemusMar** [comment]
> What's the way around this?

1) Try to update IE.
https://msdn.microsoft.com/en-us/library/dn954795%28v=vs.85%29.aspx 

2) use SoundManager 2

**Comment by dandandan9** [comment]
I'm off the computer for a little; I'll try updating IE later. If that doesn't work, what should I do with this version if it's unrunnable on IE? Revert back to r75?
