### ISSUE TITLE
User callback in OrbitControls.js

### ISSUE THREAD

**Issue by grzegorzborowiak** [mrdoob/three.js#8684]
##### Description of the problem 

I needed user callbacks in OrbitControls.js, so I implemented it:

http://gnu.univ.gda.pl/~grzes/three.js/OrbitControls.js
http://gnu.univ.gda.pl/~grzes/three.js/OrbitControls.js.diff

Example usage:

controls = new THREE.OrbitControls( camera, renderer.domElement );
controls.onUpdate = function( changed ) {
    if ( changed ) {
        render();
    }
}

In my project, CPU usage dropped rapidly after application of this trick (and disabling animate()).

Maybe somebody else would find this useful.

##### Three.js version

- [x] Dev
- [ ] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
Did this pattern not work for you?

    controls.addEventListener( 'change', render ); // use if there is no animation loop

**Comment by grzegorzborowiak** [comment]
I did not know this pattern, thank you.
I will try it.
