### ISSUE TITLE
Bug in ImageLoader (Chrome version >= 50.)

### ISSUE THREAD

**Issue by felistrs** [mrdoob/three.js#8688]
**LoadingManager** sometimes doesn't call **onProgress**. (In Chrome v 50.)
Because event 'load' in image doesn't triger. (In THREE.ImageLoader)

> 		var image = document.createElement( 'img' );
> 		image.addEventListener( 'load', function ( event ) {
> 		...

The reason is described here:
https://bugs.chromium.org/p/chromium/issues/detail?id=7731#c12

> This is not a bug. WebKit is just more strict. You must instantiate a new Image() object before the replacement, like this: 
> 
> var photo = document.getElementById('image_id');
> var img = new Image();
> img.addEventListener('load', myFunction, false);
> img.src = 'http://newimgsource.jpg';
> photo.src = img.src;

I've patched THREE.ImageLoader's function load by passing Image's instance as argument. Now it works for me.

##### Three.js version

- [x] r75

##### Browser

- [ ] All of them
- [x] Chrome ( version >= 50. )
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
#8670
