### ISSUE TITLE
Replace THREE.Cache by localForage for mobile support

### ISSUE THREAD

**Issue by fleduc** [mrdoob/three.js#8693]
From what I see in release 75, when I enable cache (enabled: true,) in THREE.Cache definition, I obtain the caching of certain files, which is good if I need these files elsewhere in the current page.  But when I refresh the page, I loose everything and it reload all objects.

When using a mobile equipment (phone or tablet) it tends to reload the pages once in a while, and if you have many objects on your page, it will use a lot of your expensive bandwidth...

Would it be possible to ask for a more "permanent" storage feature, like localforage to save objects in in the browser resources.

I've been working on modifying revision 75 for a few days now without much success (I'm not as good as you are... ;-) and I'm kindly asking for your help.

Thanks.

**Comment by mrdoob** [comment]
`LocalStorage` is too limited for this. `IndexedDB` could help, but I think it's out of the scope of the library. Maybe it could be nice as a utility int he `examples` folder though. In fact, the editor uses `IndexedDB` to save the state already.

**Comment by fleduc** [comment]
I totally agree that localStorage is of no use for that purpose, but I'm talking about localForage which let you store around 50MB per store which could speed up the reload of a page with multiple objects, when store locally.
**Localforage:**
https://github.com/mozilla/localForage
https://mozilla.github.io/localForage/

**Comment by jonnenauha** [comment]
I think you are better off setting longer Cache-Control max-age times, utilizing 304 responses, gzip and maybe using service worker than pushing parsed geometry etc. to local storage/indexdb.

I once tried caching (not even that big) BufferGeometry blobs with localForage and it was slooow to save and load back. Was much faster to load from browser cache and load/parse to geom.

This caching can also be done outside of three.js in your own app. You just check your own localForage cache with the ref before going to three.js network/loading.

I do undertand caching eg. geometry or http requests into memory. This is good if you happen to call loader.load(sameURL) N times.

**Comment by mrdoob** [comment]
Oh sorry, I thought it was a typo. I had never heard of localForage.

**Comment by mrdoob** [comment]
Yeah, I agree with @jonnenauha. This may be a bit out of scope of the library.

**Comment by jonnenauha** [comment]
Yeah, imo this is certainly a app side decision how this stuff should be handled and with what tech choices.

For example we have our own asset system that goes to network only if it has not been fetched before, and caches the text/binary responses. If you use that asset in multiple places, you only go to network once (if not in cache) and respond with it to multiple callbacks. There is also a built in mechanism that knows what assets need to be cloned per requester response or what data can be shared. We almost never use three.js to go to network (exception would be png/jpeg loading, but we cache those internally too and not call load multiple times).

Back in the day three.js did not have the Cache stuff discussed here so we built it on top of it. This cache layer is where I tried localForage about 6 months ago and the perf was not there for binary blobs, dunno if it has gotten better.

**Comment by mrdoob** [comment]
> For example we have our own asset system that goes to network only if it has not been fetched before, and caches the text/binary responses. If you use that asset in multiple places, you only go to network once (if not in mem cache) and respond with it to multiple callbacks. 

You can actually do that by setting `THREE.Cache.enabled = true;`

**Comment by fleduc** [comment]
Thank you very much to both of you for your fast answers.

Has mention by Jonnenauha, I will try to work on Cache-Control, for the moment to at least have a faster ready to market product. I may give an other try on localforage later to experience its performance.  It would be nice Jonnenauha, if you could share your experience with LF, to have something to start with, and maybe I could produce a new addon to Three.js...

**Comment by jonnenauha** [comment]
There is really not that much to say :) It will automatically select the best underlying storage API for you depending on the browser/platform its running on. You basically have two functions, write and read (cant remember the function names). I think the API was asynchronous in nature, so you provide callback functions when the data is available. I think due to the different underlying APIs it cannot provide a synchronous API.

It did afaik support array buffers at least of the modern browsers, but at least when I tried it it was quite slow. I tried storing `THREE.BufferGeometry` attributes and loading them back, probably similar use case you have for mobile. You should check it out and see what the perf is like, browser implementation have probably improved since then.
