### ISSUE TITLE
webglRenderer.js  getPixelRatio() and setPixelRatio() missing from doc

### ISSUE THREAD

**Issue by yjcxy12** [mrdoob/three.js#8697]
##### Description of the problem 
getPixelRatio() and setPixelRatio() methods in webglRenderer is missing from the doc. If they are meant to be private methods, setPixelRatio() is never called and pixelRatio is always 1 regardless of device.
...

##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Feel free to complete the missing bits 😊
https://github.com/mrdoob/three.js/edit/dev/docs/api/renderers/WebGLRenderer.html

**Comment by Mugen87** [comment]
@yjcxy12 Do you mind closing the issue? Thanks!
