### ISSUE TITLE
Object3D toJSON with ObjectLoader

### ISSUE THREAD

**Issue by D-soldier** [mrdoob/three.js#8698]
##### Description of the problem

...When use Object3D.toJSON include MultiMaterial create json file, and use ObjectLoader to load this json file, the material will show part of MultiMaterial .
  I check them data is same of them.
##### Three.js version
- [ ] Dev
- [x] r73
- [ ] ...
##### OS
- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/10931#issuecomment-290734264
