### ISSUE TITLE
OrbitControls#getPolarAngle() and OrbitControls#getAzimuthalAngle() are broken

### ISSUE THREAD

**Issue by pjanik** [mrdoob/three.js#8701]
##### Description of the problem 
`OrbitControls#getPolarAngle()` and `OrbitControls#getAzimuthalAngle()` are broken.
Steps to replicate:
1. Open: http://threejs.org/examples/misc_controls_orbit.html
2. Open console, call: `controls.getPolarAngle()`
3. Result: `OrbitControls.js:89 Uncaught ReferenceError: phi is not defined(…)`
4. Call: `controls.getAzimuthalAngle()`
5. Result: `OrbitControls.js:95 Uncaught ReferenceError: theta is not defined(…)`

##### Three.js version

I've tested:

- [x] r76
- [x] r75

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by mlknz** [comment]
It seems to work properly after changing **return phi;** and **return theta;** to **return spherical.phi;** and **return spherical.theta;** in these functions in OrbitControls.js
