### ISSUE TITLE
Vertex Array Objects (VAO) usage in THREE.

### ISSUE THREAD

**Issue by mlknz** [mrdoob/three.js#8705]
What is the current position of THREE.renderer concerning the usage of VAO's?

[OES_vertex_array_object](https://www.khronos.org/registry/webgl/extensions/OES_vertex_array_object) extension is supported on majority of devices and is going to be in core of WebGL 2.0 (According to [WebGL Stats](http://webglstats.com) and [WebGL 2.0 Spec](https://www.khronos.org/registry/webgl/specs/latest/2.0/#3.6)).

I've found [#5849 issue](https://github.com/mrdoob/three.js/pull/5849) on that topic, but it seems to have no continuation. 

Could it be something like mentioned in that issue emulation level? (renderer acts like VAO is always available and interacting with it through THREE.VertexArrayObjectSomething which handles cases). Or should it be done by a separate renderer somehow? Or if the case is THREE doesn't need it, why it is so?

Thanks in advance.

**Comment by mrdoob** [comment]
Yeah, I think we are at a point that we could try implementing it.

**Comment by mattdesl** [comment]
They can add a fair bit of complexity and might not provide much of a benefit. I think it would be good to get some real-world-ish benchmarks proving their worth before adding them to ThreeJS.

Relevant tweet by Aras Pranckevičius (Unity graphics engineer).
https://twitter.com/aras_p/status/609471507731976194

**Comment by Mugen87** [comment]
@Oletus mentioned in [WebGL Insights](http://www.webglinsights.com/)

_For binding resources, there are a few distinct ways to reduce API calls. Often the simplest way is to use vertex array objects, or VAOs, that can significantly improve performance on mobile devices. They are an API construct developed specifically to enable optimization, and are not to be confused with vertex buffer objects, or VOBs. **In our CPU-bound drawing test, FPS increase from using VAOs was 10%-13%**._

Besides, other 3D engines like [babylon.js](http://doc.babylonjs.com/overviews/webgl2#vertex-array-objects) or Turbulenz make use of VAOs. It think we should put this issue on our ToDo list 😉

**Comment by pailhead** [comment]
I agree that the complexity should be weighted against the benefits.  I think its safe to assume that three.js is cpu bound, all the calls need to be validated and such, reducing them should provide a performance benefit. 

Three does little in terms of optimizing for draw calls, my understanding is that it primarily deals with overdraw when doing the sorting. With this approach, bundling everything in a VAO would probably make sense. It's been a while since i tried using it, i forgot how user friendly they are :)

**Comment by takahirox** [comment]
I'm making VAO support PR and gonna send soon. We can test and discuss the performance benefit on it.

**Comment by takahirox** [comment]
I made the PR #14600, you can test. And feedback is welcome.

**Comment by Mugen87** [comment]
Fixed via #16287.
