### ISSUE TITLE
Shadowmap regression in r76?

### ISSUE THREAD

**Issue by sasha240100** [mrdoob/three.js#8707]
##### Description of the problem 

It seems like there is a regression in shadowmap. (Or i do something wrong.)

Demo on r75: http://192.241.128.187/current/examples/fps.html 
Terrain shader: https://github.com/WhitestormJS/whs.terrain/blob/master/src/ShaderTerrain.js

**r75**:
![image](https://cloud.githubusercontent.com/assets/7657429/14718815/85e87544-0801-11e6-96e1-0456ba5cd378.png)

**r76**:
![image](https://cloud.githubusercontent.com/assets/7657429/14718917/f4250130-0801-11e6-9261-365c1bd904dd.png)

**r75**:
![image](https://cloud.githubusercontent.com/assets/7657429/14718974/494dc606-0802-11e6-9e8e-3e6694b1de72.png)

**r76**:
![image](https://cloud.githubusercontent.com/assets/7657429/14718939/0de59918-0802-11e6-8a7e-2f2919630909.png)

##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Default desktop computer or notebook

##### Tested on win10 (intel graphics 4000, core i5)

**Comment by WestLangley** [comment]
See if #8692 is the issue.

**Comment by sasha240100** [comment]
@WestLangley Thanks! That was the problem. Solved now. But fps is lower than usually. I had 59-60 frames per second, but now it's only 40-49. Is there anything i should take into account?

**Comment by WestLangley** [comment]
You changed the `bias` and performance decreased?

**Comment by sasha240100** [comment]
@WestLangley Ah, sorry. That's okay now. That's because now i use [Chrome canary](https://www.google.com/chrome/browser/canary.html). r75 works similarly on that version of chrome. Is there any news in #8666 and #8670 ? My demo doesn't work on new chrome:( It shows the same error as there.

**Comment by WestLangley** [comment]
I expect news will be posted as soon as it is available.

**Comment by sasha240100** [comment]
Works well on chrome dev-channel
