### ISSUE TITLE
need publish r76 on npm :)

### ISSUE THREAD

**Issue by stephanedemotte** [mrdoob/three.js#8708]
https://www.npmjs.com/package/three 
0.75.0 is the latest of 143 releases

Thanks a lot !

**Comment by bhouston** [comment]
I've just updated the npm package, can you try it out for me to ensure it is fully correct?

**Comment by stephanedemotte** [comment]
three@0.76.1
done !
Thanks !

**Comment by drcmda** [comment]
@bhouston @mrdoob would it be possible reconsider npm publishing? I think this should be in the hands of the original author, as it's a simple 'npm publish' anyway. 

If you use es6 or bundles, html includes and bower are out. Everything is going through npm now. But delayed publishing is really making it difficult sometimes, especially when waiting for a bugfix.

**Comment by mrdoob** [comment]
Just `npm publish`ed 😇

**Comment by bhouston** [comment]
There may be an issue with the npm update.  I do not see a new version published.  I'll give it a few minutes, sometimes npm doesn't update right away (caches?), but I can push an update as well.

**Comment by bhouston** [comment]
Oh, we are publishing at three.js again:

https://www.npmjs.com/package/three.js

k.

**Comment by bhouston** [comment]
I can deprecate npm three then?  And refer it to three.js on npm?

https://www.npmjs.com/package/three

We discussed this before and we went with three instead of three.js but I can switch the deprecation message to three.

BTW both myself and @mrdoob had access to the npm three and three.js repositories and I do defer to mrdoob on this.  I do not consider myself the "controller" of any npm module for three.js, just a helper.

**Comment by mrdoob** [comment]
Oh no! Sorry, my mistake (npm noob). I'll see what I need to change so when I do `npm publish` it goes to `three` and not `three.js`.

Could you revert `three.js in the meantime? Sorry about that :/

**Comment by mrdoob** [comment]
Hmmm, I can't figure out what I need to do so when I do `npm publish` it goes to https://www.npmjs.com/package/three and not https://www.npmjs.com/package/three.js 😕

**Comment by bhouston** [comment]
The trick is navigate to the /utils/npm directory, then run:

node build.js 0.77.0

I then update the /src and /examples directories manually as I haven't added them to the build.js script yet.

Then I run:
 
npm publish node_modules/three

All done.

**Comment by bhouston** [comment]
I think if you run npm publish in the root of three.js it publishes the root and I think the issue is that the name of the package in the root package.json is "three.js", thus it publishes as that.

In the utils/npm directory I created a package.json template a long time ago (before the package.json in the root directory existed), and it's name is "three".  That probably explains the difference.

**Comment by mrdoob** [comment]
Ah, thanks for the instructions. I wasn't aware.

> I then update the /src and /examples directories manually as I haven't added them to the build.js script yet.

What do you update in /src and /examples?

**Comment by bhouston** [comment]
I think we can move towards publishing from root as you were doing. :)

First I think what we need to do is change the name field from "three.js" to "three".

Second, I think we need to specify which files are to be included in the published package via configuring the "files" part of the package.json properly.  This will have the same effect as my copying the files to upload to /utils/npm/node_modules/three

https://docs.npmjs.com/files/package.json#files

I think the files part should be:
```
files: [
  "package.json",
  "LICENSE",
  "README.md",
  "bower.json",
  "build",
  "examples/js",
  "src"
]
```

I can try to work through this later today if you want me to try to get this (e.g. easy root publishing) right.  Then you will be able to do "npm publish" in the root.

**Comment by bhouston** [comment]
And "examples/fonts", people have asked for that before as well to be included.

**Comment by mrdoob** [comment]
> I can try to work through this later today if you want me to try to get this (e.g. easy root publishing) right. Then you will be able to do "npm publish" in the root.

That would be great! 😊

**Comment by bhouston** [comment]
Here you go:

https://github.com/mrdoob/three.js/pull/8991
https://github.com/mrdoob/three.js/pull/8990

Made two prs since I didn't know if you wanted master targeted or not. :)
