### ISSUE TITLE
Announcement: New Wiki page on Gittery for contributors

### ISSUE THREAD

**Issue by tschw** [mrdoob/three.js#8709]
https://github.com/mrdoob/three.js/wiki/A-Contributor's-Guide-to-the-Git-Galaxy

**Comment by WestLangley** [comment]
Well, that's handy. : - )

How about this pattern, instead of `:<branch>`?

    git push origin --delete <branch>

**Comment by tschw** [comment]
Oh cool! I didn't know there was a nicer way of expressing that.

**Comment by tschw** [comment]
Redirect whoever is obviously having a hard time, refine, whatever... Closing the announcement - one "bug" less for free :)
