### ISSUE TITLE
VREffect renders nothing with webvr-polyfill

### ISSUE THREAD

**Issue by brianchirls** [mrdoob/three.js#8712]
##### Description of the problem 
As of r76, stereo/cardboard mode shows a blank screen, when using webvr-polyfill. The problem seems to be [here](https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/VREffect.js#L103-L105), in the `fullscreenchange` event handler:
```javascript
isPresenting = isDeprecatedAPI && vrHMD && ( document.mozFullScreenElement || document.webkitFullscreenElement ) !== undefined;
```

If WebVR is supported natively, this works fine; `vrdisplaypresentchange` fires but full screen does not. However, the polyfill uses full screen, so both events fire, and `isPresenting` gets set to `false` when it should be `true`. This was not a problem in r75 before 63fb23cef8de599074c6b007e65780467b6fc8a3.

##### Three.js version

- [x] Dev
- [x] r76
- [ ] r75

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Android using webvr-polyfill for Google Cardboard. Shouldn't be a problem in iOS, since it doesn't currently support full screen.

**Comment by mrdoob** [comment]
Isn't this a polyfill issue?

**Comment by brianchirls** [comment]
In theory, yes. But, to fix it, the polyfill would have to do one of two things:
1. Stop using full screen. This is what happens on the iPhone, since full screen is not supported, and it's a pretty bad experience.
2. Block the full screen event by calling `addEventListener` with `useCapture` set to `true` and then calling `preventDefault`. Even if this works, I'm not sure it's a good idea. @borismus, what do you think?

Also, under WebVR 1.0 (no polyfill), it's conceivable that you'd want to present to VR and set the main window to full screen at the same time. So you'd have a legitimate full screen event, and `isPresenting` would still evaluate to `false` because `isDepracatedAPI` would be false.

**Comment by borismus** [comment]
There's also a problem with r76 when exiting fullscreen mode. Not sure what's up there yet.

<img width="1005" alt="screen shot 2016-04-23 at 12 51 23 pm" src="https://cloud.githubusercontent.com/assets/277632/14763698/206dfdfe-0952-11e6-8253-1c535a6ce131.png">

**Comment by mrdoob** [comment]
Make sure you use the latest VREffect in master. A maybe-related bug got fixed this week.

**Comment by brianchirls** [comment]
@mrdoob:
With the latest version, I'm seeing what @borismus is seeing in fullscreen mode.

And it doesn't address the problem I originally described above. If you don't mind explaining what you were trying to do in 63fb23cef8de599074c6b007e65780467b6fc8a3, I could take a crack at a pull request.

**Comment by brianchirls** [comment]
I've tracked down @borismus's bug, and it is a different one. I'll file it separately.

**Comment by brianchirls** [comment]
Actually, never mind. npm wasn't updating for some reason. a9c64beaf3b745de8cb4f3bb961b95e6e4cabb25 does seem to fix the full screen size problem. But not the original problem in this issue.

**Comment by mrdoob** [comment]
I was trying to simplify the code...

Yeah, a PR would be nice, easier to understand what the problem is that way.

**Comment by borismus** [comment]
Hi Brian, any updates here? Have you investigated further?

**Comment by brianchirls** [comment]
@borismus yeah this is fixed in #8748. Guess I can close it now. Do you wanna confirm?

**Comment by scottgarner** [comment]
How are you handling resizes? I'm ending up with a squashed canvas now because `renderer.setSize` is called with `updateStyle` set to false when presenting, but the last resize had included the address bar because we weren't in fullscreen mode yet.

**Comment by brianchirls** [comment]
@scottgarner This particular issue didn't address resizes, but let's see if we can work it out anyway. What device are you using? Are you using the latest dev version, post #8748 and a9c64be?

**Comment by brianchirls** [comment]
I'm not sure if I prematurely closed this or if it's another issue, but with the deprecated webvr API, VREffect has no way to distinguish between presenting in VR and regular full screen.

Any ideas how we should handle this?

B

**Comment by scottgarner** [comment]
@brianchirls Sorry, didn't mean to piggyback on a closed issue, I just thought I might be missing something. I think I have the newest of everything, but I should test with the plain polyfill and boilerplate examples in case something else is weird in my code. I'm testing with a Galaxy S6 in Chrome.

**Comment by brianchirls** [comment]
@scottgarner I think this is the issue you're talking about:  https://github.com/borismus/webvr-polyfill/issues/98

**Comment by scottgarner** [comment]
@brianchirls That definitely seems like the problem. Thanks for narrowing it down.

**Comment by judax** [comment]
Hello,

How about this as a possible solution?

```
	document.addEventListener( fullscreenchange, function () {

		isPresenting = (isDeprecatedAPI && vrHMD) || (vrHMD && ( document.mozFullScreenElement || document.webkitFullscreenElement ) !== undefined);

		if ( isPresenting ) {

			if (isDeprecatedAPI) {
				rendererPixelRatio = renderer.getPixelRatio();
				rendererSize = renderer.getSize();

				var eyeParamsL = vrHMD.getEyeParameters( 'left' );
				renderer.setPixelRatio( 1 );
				renderer.setSize( eyeParamsL.renderRect.width * 2, eyeParamsL.renderRect.height, false );

			} 
			else {

				renderer.setPixelRatio( rendererPixelRatio );
				renderer.setSize( rendererSize.width, rendererSize.height );
			}

		}

	}, false );

```

**Comment by borismus** [comment]
There seems to be some confusion about which of the widths we should be using.

https://github.com/borismus/webvr-polyfill/issues/98#issuecomment-216630957

**Comment by borismus** [comment]
Tried to explain here: https://github.com/mrdoob/three.js/pull/8800. Does this make sense? @dmarcos
