### ISSUE TITLE
Blender Exporter : The exporter fails to export if there are no mesh materials

### ISSUE THREAD

**Issue by carlosanunes** [mrdoob/three.js#8717]
##### Description of the problem 

The exporter assumes there are mesh materials to export if the "Face Materials" checkbox is filled and 
crashes when exporting a model with no materials.

Trace:

> Traceback (most recent call last):
>   File "/Users/<username>/Library/Application Support/Blender/2.76/scripts/addons/io_three/__init__.py", line 813, in execute
>     exporter.export_geometry(filepath, settings)
>   File "/Users/<username>/Library/Application Support/Blender/2.76/scripts/addons/io_three/exporter/__init__.py", line 20, in inner
>     func(filepath, options, *args, **kwargs)
>   File "/Users/<username>/Library/Application Support/Blender/2.76/scripts/addons/io_three/exporter/__init__.py", line 85, in export_geometry
>     geo.parse()
>   File "/Users/<username>/Library/Application Support/Blender/2.76/scripts/addons/io_three/exporter/geometry.py", line 165, in parse
>     self._parse_geometry()
>   File "/Users/<username>/Library/Application Support/Blender/2.76/scripts/addons/io_three/exporter/geometry.py", line 530, in _parse_geometry
>     self.node, self.options) or []
>   File "/Users/<username>/Library/Application Support/Blender/2.76/scripts/addons/io_three/exporter/api/mesh.py", line 36, in inner
>     return func(mesh, *args, **kwargs)
>   File "/Users/<username>/Library/Application Support/Blender/2.76/scripts/addons/io_three/exporter/api/mesh.py", line 517, in materials
>     material_sets = [(mesh.materials[index], index) for index in indices]
>   File "/Users/<username>/Library/Application Support/Blender/2.76/scripts/addons/io_three/exporter/api/mesh.py", line 517, in <listcomp>
>     material_sets = [(mesh.materials[index], index) for index in indices]
> IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

Maybe more of an usability issue, but the addon should still export even if no materials are present.

Possible patch below:

```

diff --git a/utils/exporters/blender/addons/io_three/exporter/api/mesh.py b/utils/exporters/blender/addons/io_three/exporter/api/mesh.py
index 8c69c45..bf90b97 100644
--- a/utils/exporters/blender/addons/io_three/exporter/api/mesh.py
+++ b/utils/exporters/blender/addons/io_three/exporter/api/mesh.py
@@ -507,6 +507,10 @@ def materials(mesh, options):
     """
     logger.debug("mesh.materials(%s, %s)", mesh, options)
 
+    # sanity check
+    if not mesh.materials:
+        return []
+
     indices = []
     for face in mesh.tessfaces:
         if face.material_index not in indices:


```

##### Three.js version

- [x] Dev
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by tschw** [comment]
Since you have a Github account, how about turning this issue into a pull request?

**Comment by carlosanunes** [comment]
Seemed a bit overkill for 3 lines of code... but ok. Pull request created.

**Comment by tschw** [comment]
> Seemed a bit overkill for 3 lines of code... but ok. 

*Actually* filing the issue is the overhead when you already know how to fix it :).

> Pull request created.

Thanks!
