### ISSUE TITLE
MarchingCubes + colorArray

### ISSUE THREAD

**Issue by nhalloran** [mrdoob/three.js#8721]
##### Description of the problem 

I was interested in using colors with the MarchingCubes effect. There is evidence that colors have been implemented, but it looks like it was never finished.

For example, I'm not sure why the colorArray is being populated with position values:
https://github.com/mrdoob/three.js/blob/master/examples/js/MarchingCubes.js#L376-L387

If I am correct that colors is half baked, I'm happy to get working on it. I just wanted to make sure that I'm not misunderstanding how it works before I start digging in.

c.c.  @alteredq @spite

##### Three.js version

- [ ] Dev
- [x ] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by spite** [comment]
What makes you think it's not finished? I think the colors are populated with positions to have some value, to illustrate how to populate them. It could be random, or it could be a gradient. That's up to the developer: set your colors, set enableColors to true, you're cooking.

**Comment by nhalloran** [comment]
Thanks spite! You saved me from going down the wrong path. I'm making progress.

I am thinking of adding a colorField and extending the `addBall` and `addPlane` so that they can include a colors as well.
