### ISSUE TITLE
Option for THREE.Geometry derivative to supply their own BufferGeometry for use during rendering.

### ISSUE THREAD

**Issue by SuberFu** [mrdoob/three.js#8722]
This is related to my [MeshLineAlt](https://github.com/SuberFu/THREE.MeshLineAlt) (note, by sheer accident/oversight, it was named exactly the same as [Spite's](https://github.com/spite/THREE.MeshLine), which was pointed out to me before).

In my implementation, I pre-set the _bufferGeometry with a custom BufferGeometry, depending on the THREE.WebGLGeometries get() function behavior of constructing checking for a _bufferGeometry on a THREE.Geometry before constructing a default one to be used.
```
			if ( geometry._bufferGeometry === undefined ) {

				geometry._bufferGeometry = new THREE.BufferGeometry().setFromObject( object );
			}
			buffergeometry = geometry._bufferGeometry;
```
However, I think it may be pretty fragile, considering that I'm depending on something that's not part of the API.
Therefore, I want to ask if it's logical/possible to either.
1. Have THREE.Geometry contain a method like "getBufferGeometry" that returns a THREE.BufferGeometry (or objects derived from it). So the call becomes like...
```
geometry._bufferGeometry = geometry.getBufferGeometry().setFromObject( object );
```
2. Have objects (THREE.Mesh related, not THREE.Object3D) contains a method to return the getBufferGeometry. So the call becomes...
```
geometry._bufferGeometry = object.getBufferGeometry().setFromObject( object );
```

Personally, I think the second one is potentially more flexible, as it make more logically sense as geometry itself should not care how the end result is achieved, but the object itself will have the ability, by return a derived THREE.BufferGeometry, to retransform the THREE.Geometry object into ones it can use.

**Comment by mrdoob** [comment]
Hmmm, why don't you create a `BufferGeometry` directly?

**Comment by SuberFu** [comment]
I could. My thought is as followed.
1. Right now, almost all THREE.js object can take a THREE.Geometry object directly and render it with the supplied Material.
2. Updating the THREE.Geometry itself can be automatically propagated to rendered object.

Now, given the typical implementation of mesh-based line, the following step needs to happen.
1. Setup a geometry with a desired line.
2. Create a buffer geometry that duplicate the vertices of the line several times in order to generate the desired mesh, plus additional attributes for vertex shader to reposition the vertices.
3. Render said buffer geometry.
And every time a line needs to be updated, 
I'm hoping to create a THREE.Geometry/THREE.Mesh derived class that can automatically handle step 2, without the user having to explicitly call some form of conversion function every time they update the line.

**Comment by mrdoob** [comment]
I'm planning to deprecate THREE.Geometry soon 😉

**Comment by SuberFu** [comment]
Ah, okay. Looking forward to see the new plan.
