### ISSUE TITLE
WebGLRenderer readRenderTargetPixels with zero x,y

### ISSUE THREAD

**Issue by josendf** [mrdoob/three.js#8728]
##### Description of the problem

In r76 a check was added to WebGLRenderer#readRenderTargetPixels that prevents reading the buffer when either x or y are zero:

if ( ( x > 0 && x <= ( renderTarget.width - width ) ) && ( y > 0 && y <= ( renderTarget.height - height ) ) ) { ...
##### Three.js version
- [ x] Dev
- [ x] r76
##### Browser
- [x] All of them
##### OS
- [x] All of them

**Comment by Mugen87** [comment]
see #8604. Do you think we can avoid this problem by changing the if-statement to:

```javascript
if ( ( x >= 0 && x <= ( renderTarget.width - width ) ) && ( y >= 0 && y <= ( renderTarget.height - height ) ) ) 
```
That should allow zero values of x,y.

**Comment by josendf** [comment]
I understand that 0,0 is a valid coordinate, i.e. x=0, y=0, width=1, height=1 should be accepted.

See [WebGLRenderingContext.readPixels()](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/readPixels#Examples).

Furthermore, if the box lies outside the frame buffer, the function fails silently, maybe this situation should be logged.

Another option can be clipping the requested box:

    var
    targetWidth = renderTarget.width,
    targetHeight = renderTarget.height; 
   
    x = Math.min( Math.max( x, 0 ), targetWidth );
      
    y = Math.min( Math.max( y, 0 ), targetHeight );
    
    width = Math.min( Math.max( width, 0 ), targetWidth - x );
    
    height = Math.min( Math.max( height, 0 ), targetHeight - y );
   
    if( width && height ) {
      _gl.readPixels( x, y, width, height, paramThreeToGL( texture.format ), paramThreeToGL( texture.type ), buffer );
   
    }
    else {
      console.error( 'THREE.WebGLRenderer.readRenderTargetPixels: out of bounds.' );
    }

**Comment by Mugen87** [comment]
The above commit should solve the actual problem. I'm not sure if we should implement the other proposals (logging, clipping).

ping @mrdoob

**Comment by mrdoob** [comment]
Hmm... Not sure about logging/clipping...

**Comment by Mugen87** [comment]
Closing. As long as no further problems are reported in this context, there is no need for additional logging or clipping.
