### ISSUE TITLE
buffergeometry w/ wireframe material only draws 1/2 of triangles when drawrange used

### ISSUE THREAD

**Issue by jimmyland** [mrdoob/three.js#8729]
##### Description of the problem 

What happens: If I set up a scene w/ a buffergeometry w/ 5 triangles, and setDrawRange(0, 5*3), and toggle the material to wireframe, I only 2 + 1/3 triangles.  I see all 5 w/ non-wireframe material.

jsfiddle demo: http://jsfiddle.net/gh41g1ej/

I expected to see all 5 triangles in wireframe.  I can work around this by changing the drawrange indices by a factor of 2.  Not sure if this is intended behavior but I was surprised by it.

##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
Thanks for the nice, simple example. : - )

Yes, if `drawRange` is _not_ specified, then `WebGLRenderer` will render `BufferGeometry` correctly if `wireframe` is `true`.

If `drawRange` is specified, then wireframes are rendered incompletely.

This is an unfortunate consequence of the renderer trying to be helpful by creating a line-based geometry on-the-fly; that geometry has twice the vertices of the original geometry in this example.

The workaround is to use either of the following patterns:
```javascript
var wh = new THREE.WireframeHelper( mesh );
```

```javascript
var geometry = new THREE.WireframeGeometry( mesh.geometry );
var material = new THREE.LineBasicMaterial( { color: 0xffff00, linewidth: 2 } );
var wf = new THREE.LineSegments( geometry, material );
```
/ping @mrdoob

**Comment by mrdoob** [comment]
Yeah. At this point I can't think of a better solution.

**Comment by WestLangley** [comment]
Presumably this could be fixed, but I'm afraid of the renderer trying to be too clever.

In fact, one option is to deprecate `material.wireframe` in favor of `WireframeGeometry`.

I think the work-around should be to use the above patterns for now.

**Comment by mrdoob** [comment]
> In fact, one option is to deprecate `material.wireframe` in favor of `WireframeGeometry`.

Yeah, I kind of suggested that some years ago. People seemed pretty unsupportive 😄

**Comment by WestLangley** [comment]
>In fact, one option is to deprecate material.wireframe in favor of WireframeGeometry.
>>Yeah, I kind of suggested that some years ago. People seemed pretty unsupportive 😄

You did. I would support such a change.
