### ISSUE TITLE
Three.js 3d model not appearing on mobile browser

### ISSUE THREAD

**Issue by wowde** [mrdoob/three.js#8730]
I am using objloader to load .obj file and its working fine on my desktop browser but when same page i am loading to mobile browser its not loading nothing appears

...

THREE.WebGLRenderer 66

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] Android
- [x] IOS

**Comment by makc** [comment]
> WebGLRenderer 66

are you aware that you are 10 revisions behind current version? fwiw, upgrading r71 to r75 did solve some ios issues for me, so you might want to.
