### ISSUE TITLE
vertex cache optimisation

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#8731]
just leaving this here in case someone will be inspired to create geometry util for this:

> When rendering each triangle, the vertices it uses must be processed (for example, transformed to screen space and lit in various ways) before rendering. Indexed rendering hardware typically uses a small cache of vertices to avoid re-processing vertices that are shared between recently-rendered triangles. Using a moderately-sized cache (anywhere between 12 and 24 vertices is common) reduces the load on the vertex processing pipeline far more than the older non-indexed strips and fans model – often halving the amount of work required per triangle.
> However, the vertex cache relies on the ordering of the triangles to be optimised for its characteristics. If the triangles are sent in a random order, the vertices almost always miss the cache and there is no benefit obtained. If triangles are sent in clusters so that each triangle is close to previously-rendered triangles, it is more likely that more of its vertices are still in the cache.

[text](http://web.archive.org/web/20150325073745/http://home.comcast.net/~tom_forsyth/papers/fast_vert_cache_opt.html)
[code](https://github.com/bkaradzic/bgfx/blob/master/3rdparty/forsyth-too/forsythtriangleorderoptimizer.cpp)

**Comment by bhouston** [comment]
ThreeJS does not generally used indexed vertices.  I haven't found ThreeJS to be vertex limited, it is nearly always fragment shader limited, especially on mobile.  The reason why ThreeJS isn't generally vertex limited is that no one wants to download large meshes that have a lot of vertices and also because WebGL doesn't have a geometry shader yet that can increase the number of vertices.

So I haven't seen this as an issue yet.

**Comment by mrdoob** [comment]
I heard that nowadays drivers convert indexed geometries to non-indexed geometries anyway. That article is from 2006...

**Comment by SuberFu** [comment]
@mrdoob I think it's now called [Post Transform Cache](https://www.opengl.org/wiki/Post_Transform_Cache).
It does look like there may be some benefit. However, as @bhouston said, the bottleneck is likely in the fragment shader. Furthermore, the additional processing needed to "optimize" the vertices in javascript may outweigh whatever performance gain you get through vertex caching.

Although it would be an interesting exercise for those inclined. Creating a new THREE.BufferGeometry derived object that convert it's internal indices to optimize cache.

**Comment by makc** [comment]
> Furthermore, the additional processing needed to "optimize" the vertices in javascript may outweigh whatever performance gain you get through vertex caching.

not saying this should be done to everything that goes throuhg three.js, but an utility method to run over the output of parsers / loaders would be nice

**Comment by bhouston** [comment]
> Creating a new THREE.BufferGeometry derived object that convert it's internal indices to optimize cache.

Many game engines do this.  Although generally you want to optimize prior while saving your assets, not during run-time loading.  Indexed geometry is generally smaller to download too, especially if it is in OpenCTM-like formats.

**Comment by pailhead** [comment]
This could definitely reduce the size of the meshes. Instead of going from indexed to triangle soup, you just use indexed. Should be pre-processed.

**Comment by brianchirls** [comment]
According to the [OpenGL ES Programming Guide for iOS](https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html), updated in December 2015, this is still a thing.

> Where possible, sort vertex and index data so triangles that share common vertices are drawn reasonably close to each other in the triangle strip. Graphics hardware often caches recent vertex calculations to avoid recalculating a vertex.

But I'd love to see a real benchmark if someone feels motivated to put one together...especially on mobile.

**Comment by donmccurdy** [comment]
Note that gltfpack (https://github.com/zeux/meshoptimizer) is available to do vertex cache optimization and other improvements offline, if you can get your models into glTF format.
