### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by wzhsunn** [mrdoob/three.js#8735]
##### Description of the problem 

sometimes, when I open http://threejs.org/examples/#webgl_loader_collada_keyframe,
I got a black screen .

:)

##### Three.js version

on line example
http://threejs.org/examples/#webgl_loader_collada_keyframe

some t
##### Browser

- [] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
![1](https://cloud.githubusercontent.com/assets/528348/14799512/711af09e-0b6f-11e6-950a-c12a09b67e80.png)

**Comment by insominx** [comment]
I believe this is related to the shenanigans in Chrome 50.  Everything appears kosher in Chrome Canary (52).

**Comment by mrdoob** [comment]
#8670
