### ISSUE TITLE
clickable objects in pointerlock controls

### ISSUE THREAD

**Issue by stevecsvihinka** [mrdoob/three.js#8736]
I am trying to make an event listener for when objects are clicked in a three.js application that uses pointerlock controls. According to research, the best way to do this is to use a raycaster and its `setFromCamera` function. 

In [this](http://mrdoob.github.io/three.js/examples/canvas_interactive_cubes.html) example you can find the line

    raycaster.setFromCamera( mouse, camera ); 

When using the pointerlock controls in a three.js application (or at least in the ones i've seen) the camera object's position doesn't update to reflect where the it is in space. After moving around the camera with the controls, the camera's `position` will stay static, but `controls.getObject().position` will give me the coordinates of where the camera is in space. 

I noticed there is a `getDirection` function in pointerlock (that I can use for setting the vector) but I get an error when calling it:

    PointerLockControls.js:61 Uncaught TypeError: Cannot read property 'copy' of undefined(…)

Here is a **[codepen](http://codepen.io/tembling/pen/reZjEw)**. How can I detect which box the user clicks on?

**Comment by Mugen87** [comment]
When using `PointerLockControls.getDirection` you must provide a result vector as a parameter. Something like this:

```javascript
controls.getDirection( direction ); // direction is a Vector3
```

Then you can use this direction in your raycaster object.
