### ISSUE TITLE
Flat Color Shading

### ISSUE THREAD

**Issue by timgrossmann** [mrdoob/three.js#8741]
##### Description of the problem 

Well i found two ways, first using MeshBasicMaterial.... Which doesn't support shadows anymore.
Then i tried ShadowMaterial just to find out that it has also been removed.

Is there any existing way to get Flat Color on a Mesh with Shadows ?! 
I just want to make a floor which has the same color as the background but with my mesh throwing a shadow on the floor, like this example: http://codepen.io/Yakudoo/pen/YXxmYR

Thank you for the help!
Greetings
...

##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
`ShadowMaterial` hasn't been removed, it's in the `examples` folder. It hasn't been promoted to core yet.

This example uses it:
http://threejs.org/examples/webgl_geometry_spline_editor.html
