### ISSUE TITLE
Request to make THREE.AnimationAction its own file

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8749]
##### Description of the problem 

Currently THREE.AnimationAction is in the file AnimationMixer.js because it is a private class.  It would be easier to manage the code if we had it as its own separate class/file.  Even though it isn't intended to be created by users, it is nice to have it as its own file as you can find it and document it properly.  We have separate files for a lot of internal WebGL classes stuff like WebGLProgram, WebGLState, etc.  I would just like to follow that pattern with the animation stuff.

##### Three.js version

- [ ] Dev
- [ ] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Sounds good to me.
