### ISSUE TITLE
Can't export from blender to json file

### ISSUE THREAD

**Issue by lolotoobo** [mrdoob/three.js#8752]
Hello

I'm using the r76 and I try to add  three.js exporter to Blender  2.77. I've put the io_three in `C:\Program Files\Blender Foundation\Blender\2.7X\scripts\addons`  and msgpack in `C:\Program Files\Blender Foundation\Blender\2.77\scripts\modules`.

I configured Blender as you can see in the picture [blenderbug](https://cloud.githubusercontent.com/assets/1102727/14844766/0fb92f1e-0c5a-11e6-9ec5-48372dece0b2.PNG)
 and when I try to export a model I have basic datas :

    {
    "faces":[33,0,1,2,3,0,0,0,0,33,4,7,6,5,1,1,1,1,33,0,4,5,1,2,2,2,2,33,1,5,6,2,3,3,3,3,33,2,6,7,3,4,4,4,4,33,4,0,3,7,5,5,5,5],
    "uvs":[],
    "normals":[-0,0,1,0,-0,-1,1,0,-0,-0,1,0,-1,-0,0,0,-1,-0],
    "vertices":[1,-1,1,1,1,1,-1,1,1,-1,-1,1,1,-1,-1,0.999999,1,-1,-1,1,-1,-1,-1,-1],
    "name":"CubeGeometry",
    "metadata":{
        "uvs":0,
        "faces":6,
        "generator":"io_three",
        "normals":6,
        "type":"Geometry",
        "vertices":8,
        "version":3
    }
    } 

Sometimes lines order is changed but the content is always the same

**Comment by antont** [comment]
So basically it seems to be working correctly because it exports a JSON for you, no?

The warning about import is irrelevant (importing three.js jsons to blender is just not implemented), because you are exporting.

This tracker is for bug reports and feature requests, usage help requests should go to stackoverflow.

**Comment by lolotoobo** [comment]
Yes it's exporting something but as I said  if I export a cube, a sphere or a complex scene I always have the same basic json file
