### ISSUE TITLE
Weird console error and no shadow maps

### ISSUE THREAD

**Issue by fallenartist** [mrdoob/three.js#8753]
##### Description of the problem 

While [trying to get shadow maps working in r76](http://codepen.io/znak/pen/bpxXrV?editors=0011), I'm seeing "THREE.MeshLambertMaterial: 'shading' is not a property of this material." error in console but no such material is in the scene? [It was working in r73](http://codepen.io/znak/pen/raqBLM?editors=0010) and I believe I migrated everything correctly.

##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser

- [ ] All of them
- [x] Safari

##### OS

- [ ] All of them
- [x] OS X 10.11.4

**Comment by mrdoob** [comment]
Both examples show up white here...

**Comment by fallenartist** [comment]
That's what I see in Safari:

![screen shot 2016-04-28 at 14 12 08](https://cloud.githubusercontent.com/assets/661820/14886938/6376f932-0d4b-11e6-88e6-3d2a3cc4363b.png)


![screen shot 2016-04-28 at 14 05 36](https://cloud.githubusercontent.com/assets/661820/14886777/77975598-0d4a-11e6-81fb-a84c061fd991.png)

In second example (r76) I've changed material to `THREE.MeshLambertMaterial` since `THREE.MeshBasicMaterial` doesn't support shadows anymore, right?

Still, no shadows produced. The console error disappears when I delete the Collada loader/code.

**Comment by WestLangley** [comment]
I think you need to use stackoverflow for help.
