### ISSUE TITLE
raycaster.setFromCamera weird behavior

### ISSUE THREAD

**Issue by flacohenao** [mrdoob/three.js#8755]
##### Description of the problem 

Hi, I've been trying to solve a problem that is hardly related to the raycast.
Im going to put some images here:

**image1**
![image1](https://cloud.githubusercontent.com/assets/10132006/14873839/1a6f5292-0cc0-11e6-8a8e-bad670fe8a3a.png)

**image2**
![image2](https://cloud.githubusercontent.com/assets/10132006/14873850/37a0132e-0cc0-11e6-8a31-05882d9650af.png)

AS you can see.. the canvas is not full screen, im using angular and bootsrap.

First of all, in the SRC code of this version the function is defined as follows:

> setFromCamera: function ( coords, camera ) {
> 
> 			if ( camera instanceof THREE.PerspectiveCamera ) {
> 
> 				this.ray.origin.setFromMatrixPosition( camera.matrixWorld );
> 				this.ray.direction.set( coords.x, coords.y, 0.5 ).unproject( camera ).sub( this.ray.origin ).normalize();
> 
> 			} else if ( camera instanceof THREE.OrthographicCamera ) {
> 
> 				this.ray.origin.set( coords.x, coords.y, - 1 ).unproject( camera );
> 				this.ray.direction.set( 0, 0, - 1 ).transformDirection( camera.matrixWorld );
> 
> 			} else {
> 
> 				console.error( 'THREE.Raycaster: Unsupported camera type.' );
> 
> 			}
> 
> 		}

so, the observations:
the code that I have is:

**HTML**

```
<div class="col-md-11">
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Title</h3>
      </div>
      <div class="panel-body" style="padding: 0px">
        <div class="canvas-zonas" ng-click="zonas.click($event)">
        </div>
      </div>
    </div>
  </div>
</div>
```

**Css (using stylus)**
```
.canvas-zonas
  height 67vh

body
  margin 0
  font-size 15px
```

**CONTROLLER**
```
var  mouse = new THREE.Vector3();
var  raycaster = new THREE.Raycaster();
var  canvas = document.querySelector(".canvas-zonas");

function clickObject(event) {
      event.preventDefault();
      mouse.x= ((event.clientX - canvas.offsetLeft)/canvas.clientWidth) * 2 - 1;
      mouse.y=-((event.clientY - canvas.offsetTop)/canvas.clientHeight) * 2 + 1;
      mouse.z = 0.5;
      raycaster.setFromCamera( mouse, camera );
      var intersects = vm.raycaster.intersectObjects(scene.children);
      console.info(intersects);
    }

```

So when I click my canvass and print the `Intersects` variable, sometimes I get [] an empty array even if a click the object and sometimes I get [object] even if I click outside the object.

I would like to show you guys a little bit of my camera config:

**camera config**
```
var camera = new THREE.PerspectiveCamera(30, canvas.clientWidth / canvas.clientHeight, 0.10, 1000)
camera.position.y = 20;
camera.position.z = 50;
camera.lookAt(scene.position);
camera.updateProjectionMatrix();
```

That's my camera config, and also, have in mind that I use a WEBGL as renderer

`var renderer = new THREE.WebGLRenderer({antialias: true});`

Also, have in mind that I have a resize event going on:

```
function listenResize() {
  window.bind('resize', function () {
    canvas = document.querySelector(".canvas-zonas");
    renderer.setSize(canvas.clientWidth, canvas.clientHeight);
    camera.aspect = (canvas.clientWidth / canvas.clientHeight);
    camera.updateProjectionMatrix();
  });
}
```

So based on that, and having in mind that my raycaster formula in the vector is ok, **WHAT AM I DOING WRONG** because the objective of that function **raycaster.setFromCamera** in this version is try to simplify the things and dont use projector and other stuffs..

am i correct? or just the raycaster is not being interpretated correctly??

THANK YOU!

##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/.github/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).

**Comment by jyprksh001** [comment]
@flacohenao  did  u find any solution for this ....i am facing the same issue

**Comment by flacohenao** [comment]
@jyprksh001 yes, this post in stakoverflow helped me:

http://stackoverflow.com/questions/13542175/three-js-ray-intersect-fails-by-adding-div/13544277#13544277

I was doing everything ok, but my css was creating a conflict in the canvas! checkout your styles!
