### ISSUE TITLE
Wrong Label: 2 Height Segments in Editor

### ISSUE THREAD

**Issue by formalin14** [mrdoob/three.js#8765]
##### Description of the problem 

There are 2 "Height Segments" in the editor's properties pane. I think one of them should be "Depth Segments".

##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
Looks like a copy-paste error...
