### ISSUE TITLE
Object3D.traverseAncestors documentation differs from actual behavior.

### ISSUE THREAD

**Issue by martikaljuve** [mrdoob/three.js#8766]
The documentation for [.traverseAncestors(callback)](http://threejs.org/docs/#Reference/Core/Object3D) states:
"Executes the callback on this object and all ancestors."

The callback is not called for "this object", as can be seen here: https://github.com/mrdoob/three.js/blob/r76/src/core/Object3D.js#L493-505

Expected behavior would be to have `callback( this )` as in [traverse(callback)](https://github.com/mrdoob/three.js/blob/r76/src/core/Object3D.js#L465), but a safer option is to change the documentation. 

##### Three.js version

- [x] r76

**Comment by Mugen87** [comment]
I assume this is a copy-paste error in the documentation. The above PR should solve the problem...
