### ISSUE TITLE
THREE.TextureLoading Will Not Fire onLoad Sometimes

### ISSUE THREAD

**Issue by sophypal** [mrdoob/three.js#8773]
I'm running into an issue where sometimes the `THREE.TextureLoader`'s `onLoad` hook won't fire.  It's unpredictable when it happens.  In fact the same problem happens with the [cube example](http://threejs.org/examples/#webgl_geometry_cube).  I'd say 1 out of 10 times, the textures won't load.

I did some digging and although I'm not entirely sure this is the cause, I believe the underlying `Image` is being reclaimed by the garbage collector before it could notify.  My scene is much more complex and results in multiple textures being loaded at once.  It might have been enough to kick the GC into reclaiming locals and short lived objects.

In https://github.com/mrdoob/three.js/blob/master/src/loaders/ImageLoader.js#L47-L83, the returned image is never referenced directly `TextureLoader` but instead rely on the local's event being fired.  So there's actually a period of time between the time the image is created to the time the image is loaded that the image isn't being referenced anywhere.  That sure sounds like a candidate for garbage collection but I'm not an expert.

Oddly enough, replacing the passing of `this` at https://github.com/mrdoob/three.js/blob/master/src/loaders/ImageLoader.js#L53 with `image` makes the problem go away for me.  It made a closure and kept the `image` reference alive.

I'm testing with  `r75` no Chrome 50.0.2661.86 (64-bit).

**Comment by aardgoose** [comment]
This looks like you are hitting a known Chrome v50 bug. see #8670.

Fixed in .94 released recently.

**Comment by sophypal** [comment]
Thanks for the info.  Seems to be resolved on the latest Chrome.
