### ISSUE TITLE
VREffect sets incorrect resolution when exiting from VR with polyfill

### ISSUE THREAD

**Issue by brianchirls** [mrdoob/three.js#8776]
##### Description of the problem 
When entering VR mode, `VREffect` sets the pixel ratio to 1. It saves a backup of the original value as `rendererPixelRatio` so it can set it back to what it was when exiting VR presentation. However, with the webvr-polyfill, both the full screen event handler and `vrdisplaypresentchange` fire, so whichever one runs second will overwrite `rendererPixelRatio` with 1.

Since there's a lot of repeated code in the two event handlers, I propose unifying them into a single function. At the top of that function, we'll check if the value of `isPresenting` is the same as it was before and abort if the values match. That way, we avoid running the same code twice.

##### Three.js version

- [x] Dev
- [x] r76

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

webvr-polyfill and a mobile browser

**Comment by mrdoob** [comment]
I think Firefox will soon implement WebVR 1.0, which will allow us to clean up the code duplication, right?

**Comment by brianchirls** [comment]
[Quoth](https://github.com/mrdoob/three.js/issues/8568#issuecomment-216097792) @cvan:
> I realise the WebVR v1.0 API is coming, but it might be for a while. it'd be best to just add the additional logic now.

To clarify, I mean make a single function and have attached to both `vrdisplaypresentchange` and `fullscreenchange` events...or maybe just one, depending on which API is in place. I can try to put something together this week.

**Comment by mrdoob** [comment]
Thanks!
