### ISSUE TITLE
Issue with uploading normal map

### ISSUE THREAD

**Issue by gerdsattler** [mrdoob/three.js#8786]
##### Description of the problem 
![normalmap](https://cloud.githubusercontent.com/assets/18900835/14954845/d6169d4e-1075-11e6-9cdf-0d8e9a49ee10.PNG)

Hello together,
I tried to upload my first 3D-Model which texture and normal map in my three.js viewer.
Somehow the mapping of the normal map is wrong (see attach screenshot).
Does anyone know the reason for this issue? The Model works properly in other viewers like sketchfab and i wonder if my three.js settings are wrong, or if i need to modify one or more of the 4 files (obj, mtl, texture jpg, normal map jpg).
I am looking forward to feedback and advice.
Best Wishes
Gerd
...

##### Three.js version

- [ ] Dev
- [ ] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/.github/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
