### ISSUE TITLE
Allow for selection between multiple VRDevices

### ISSUE THREAD

**Issue by caseyyee** [mrdoob/three.js#8790]
##### Description of the problem

Currently sets to first device found.  
##### Three.js version
- [x] Dev
- [ ] r76
- [ ] ...
##### Browser
- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Chromium VR (webvr.info)
##### OS
- [] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
##### Hardware Requirements (graphics card, VR Device, ...)

With both Oculus CV1 and HTC Vive connected, both enumerate as devices, but we should present some kind of UI to select between the devices.

**Comment by cvan** [comment]
The WebVR Polyfill needs to change to support this too.

**Comment by cvan** [comment]
This affects both `VREffect` and `VRControls`. FWIW, `VRControls` used to support multiple devices but for WebVR v1.0 support, `VRControls` was changed to allow only the first one.

**Comment by zz85** [comment]
> and look who's contributed! 😄

![image](https://user-images.githubusercontent.com/314997/37742294-05c1022a-2da0-11e8-879d-333d05081763.png)
Took me awhile to spot what the exactly the change was but indeed the contribution is legit 😂
