### ISSUE TITLE
Toggle between Enter and Exit VR.

### ISSUE THREAD

**Issue by caseyyee** [mrdoob/three.js#8791]
##### Description of the problem 

The Enter VR button should toggle between Enter and Exit VR.   Currently once you Enter VR using `vrDisplay.requestPresent()`, there is no way to cancel VR display using `vrDisplay.exitPresent()`.

##### Three.js version

- [x] Dev
- [ ] r76
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Experimental WebVR Chromium builds (webvr.info)

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

Compatible VR hardware.   Vive or Oculus CV1.

**Comment by cvan** [comment]
I filed this already as #8565

**Comment by caseyyee** [comment]
Ah good thanks @cvan
