### ISSUE TITLE
Idea on allowing scene.overrideMaterial to be a function.

### ISSUE THREAD

**Issue by SuberFu** [mrdoob/three.js#8794]
Currently, if we have a scene that contains objects each requiring complex shaders (for example, a scene containing a simple geometry, a mesh line where vertex positions are calculated in the vertex shader, and a point cloud that has special fragment shader to support different sized points), it may be difficult and/or impossible to define a single material for use with scene's "overrideMaterial" when one, for example, want to perform a depth pass render.

Therefore, I want to ask if it would be possible to allow overrideMaterial to potentially be a function (or on a separate property, like overrideMaterialFactory). If it's a function, when the renderer is trying to get the material, it will call the function with the renderItem itself as the argument.

The goal is to provide more flexibility to the rendering engine. So that, for example, a user want to render a shadowMap for object requiring special shaders, the user can provide a function that returns a specialized version of the shadow map shader.

So potentially the following changes.
WebGLRenderer.renderObjects
`var material = overrideMaterial === undefined ? renderItem.material : overrideMaterial;`
to

```
var material = renderItem.material;
if (overideMaterial !== undefined ){
    if (overrideMaterial instanceof THREE.Material) {
        material = overrideMaterial;
    }else{
        // Assume function
        material = overrideMaterial(renderItem);
    }
}
```

...
##### Three.js version
- [ ] Dev
- [ X] r76
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by makc** [comment]
...or you could just swap the materials on your objects?

**Comment by SuberFu** [comment]
@makc 
Come to think about it. You're right, I could use the traverse() before each rendering (or traverseVisible) and replace the materials and save the existing material to the userData field.
A bit of a question on userData, is it safe to "save" a reference to material inside a userData field?

**Comment by Mugen87** [comment]
This needs to be realized in user code. The suggestion of @makc sounds reasonable.

> A bit of a question on userData, is it safe to "save" a reference to material inside a userData field?

I would say yes. As long as you don't serialize/deserialize your objects.
