### ISSUE TITLE
BufferGeometry.computeBoundingSphere assumes attribute stride of 3

### ISSUE THREAD

**Issue by bicubic** [mrdoob/three.js#8798]
##### Description of the problem 
Given the following:
```
var bufferGeometry = new THREE.BufferGeometry();
var position = new Float32Array();
//populate position with xyzw components
bufferGeometry.addAttribute('position', new THREE.BufferAttribute(position, 4));
```
The following error is raised:
`three.js:12031 THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values. `

Reason being that computeBoundingSphere assumes a 3-stride position attribute:
https://github.com/mrdoob/three.js/blob/master/src/core/BufferGeometry.js#L608

Which also means that bounding spheres are wrong for any geometries of stride other than 3?

I think the solution is to swap that stride to `attribute.itemSize`

Happy to do a PR for this if the above is correct.
...

##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
N/A

**Comment by mrdoob** [comment]
We don't know how to solve this one...

**Comment by mrdoob** [comment]
#6288
