### ISSUE TITLE
morphTargets : true does not work on THREE.ShaderMaterial

### ISSUE THREAD

**Issue by tw3eX** [mrdoob/three.js#8799]
Hi. I am tried to show exported morph animation and see something strange.

Its worked well, animation is showed.
`var clip = THREE.AnimationClip.CreateFromMorphTargetSequence( null, geometry.morphTargets, 25 );`

But something strange with materials.

Phong material is well:
`new THREE.MeshPhongMaterial({ morphTargets: true, morphNormals: true, color: 0xd3d3d3}); `

Shader material doesnt work:
```
var  xRayMaterial = new THREE.ShaderMaterial({
  	morphTargets: true,
  	morphNormals: true,
  	uniforms: {
  		p: {
  			type: "f",
  			value: 2
  		},
  		glowColor: {
  			type: "c",
  			value: new THREE.Color(0x84ccff)
  		},
  	},
  	vertexShader: document.getElementById('vertexShaderXRay').textContent,
  	fragmentShader: document.getElementById('fragmentShaderXRay').textContent,
  	side: THREE.DoubleSide,
  	blending: THREE.AdditiveBlending,
  	transparent: true,
  	depthWrite: false,
  });
```
On documentation i see that morphTargets argument on shadermaterial here.

**Comment by tschw** [comment]
You must tell the skinned mesh that you want vertex shader uniforms, otherwise you get a data texture when your graphics card supports it.

**Comment by tw3eX** [comment]
> You must tell the skinned mesh that you want vertex shader uniforms, otherwise you get a data texture when your graphics card supports it.

I am sorry, i am newbie in webgl/shaders. How can i say to mesh this one?

**Comment by tschw** [comment]
Please note that we usually don't do end user support around here, due to limited resources.

As a quick hint: Take a look at the constructor of `SkinnedMesh` or the GLSL code used for skinning within Three.js, depending on whether you want to disable or support the preferred data handoff.

For further help, please ask on stackoverflow.com.

**Comment by makc** [comment]
@tschw I like how this says "ask on stackoverflow.com", then [someone does exactly that](https://stackoverflow.com/questions/47136489/access-morph-targets-through-shadermaterial) and it goes unanswered. you guys have to understand that people end up here when doing google search.

said search also reveals https://github.com/mrdoob/three.js/issues/1900#issuecomment-5672975 from 2012, and I have no idea is that code still works in 2019 or I have to do something else.

🤔

it is trial and error time.

**Comment by makc** [comment]
looks like I have been running into this [before](https://github.com/mrdoob/three.js/issues/11028#issuecomment-290471701) but forgot by now
