### ISSUE TITLE
vNormal required in r72?

### ISSUE THREAD

**Issue by chrisj** [mrdoob/three.js#8801]
##### Description of the problem 
After upgrading r71 to r72 it seems that in shaders that do not use the normal, it is still required to set vNormal to some value such as ```vNormal = vec3(0.0, 0.0, 0.0);```. Is this the proper way to deal with the issue? Also I wanted to report it if it was not known.
...

##### Three.js version

- [ ] Dev
- [x] r72
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Mac
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Are you dealing with custom shaders?

**Comment by chrisj** [comment]
Yes, actually I should have done more testing because I believe it is also related to my continued use of immediateRenderObject. I'll re-open when I know more.
