### ISSUE TITLE
Strange geometry.vertices.y values of polyhedron

### ISSUE THREAD

**Issue by whoem** [mrdoob/three.js#8807]
##### Description of the problem 
The bottom face of this body should be even, because its vertices all have common y-coordinate: -1
In result the rendered y-coordinates of vertices [-1, -1, 1] and [1, -1, -1] differ from the others and the face is broken.

Code:
```
var geometryVertices = [
  -1, -1, 1,
  .75, -1, 1,
  1, -1, .75,
  1, -1, -1,
  -.75, -1, -1,
  -1, -1, -.75,
  -1, .75, 1,
  1, .75, -1
];
geometryFaces = [
  0,2,1,
  0,3,2,
  0,4,3,
  0,5,4,
  0,1,6,
  6,5,0,
  3,4,7,
  7,2,3,
  6,1,7,
  1,2,7,
  4,5,6,
  6,7,4
];
var geometry = new THREE.PolyhedronGeometry (geometryVertices, geometryFaces, 1, 0);
var material = new THREE.MeshPhongMaterial ();
material.shading = THREE.FlatShading;
var body = new THREE.Mesh (geometry, material);
scene.add (body);
```

##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Lenovo ThinkPad

**Comment by mrdoob** [comment]
Hmm, do you mind creating a jsfiddle for this?

**Comment by WestLangley** [comment]
Is `ConvexGeometry` what you really want?

```javascript
var vertices = [
	new THREE.Vector3( - 1, - 1, 1 ),
	new THREE.Vector3( .75, - 1, 1 ),
	new THREE.Vector3( 1, - 1, .75 ),
	new THREE.Vector3( 1, - 1, - 1 ),
	new THREE.Vector3( - .75, - 1, - 1 ),
	new THREE.Vector3( - 1, - 1, - .75 ),
	new THREE.Vector3( - 1, .75, 1 ),
	new THREE.Vector3( 1, .75, - 1 )
];

var geometry = new THREE.ConvexGeometry( vertices );

var material = new THREE.MeshPhongMaterial( { shading: THREE.FlatShading } );

mesh = new THREE.Mesh( geometry, material );

scene.add( mesh );
```

**Comment by whoem** [comment]
@mrdoob I'd like to, but unfortunately jsfiddle doesn't render polyhedron. I uploaded a sample project to http://whoem.bootes.uberspace.de/threejs/test/ - rotate by mouse drag. Vertices 0 to 5 are initialized with same y-coordinate = -1. However, the rendered ones differ:
![test_screen](https://cloud.githubusercontent.com/assets/6699384/15041929/12306e80-12c0-11e6-9ab5-df81f43f2b77.png)
@WestLangley Thanks for suggestion, but when I use it, the console throughs an error - the class "ConvexGeometry" is not defined. I can't find it in the docs, too. How can I test it? Did you remember it wrong maybe?

**Comment by WestLangley** [comment]
You must include `ConvexGeometry.js` explicitly. It is in the `examples/js` folder.
```html
<script src="js/geometries/ConvexGeometry.js"></script>
```

**Comment by whoem** [comment]
@WestLangley Man, this is just what I needed! Thank you _so_ much! :)
Could you also - briefly maybe - reveal the reason why `THREE.PolyhedronGeometry` was behaving that weird? So I won't use it for the wrong purpose ever again?

**Comment by WestLangley** [comment]
>Could you also - briefly maybe - reveal the reason why THREE.PolyhedronGeometry was behaving that weird?

Your use case would take some investigation... According to the [docs](http://threejs.org/docs/api/extras/geometries/PolyhedronGeometry.html), the vertices are projected onto a sphere.
