### ISSUE TITLE
sourceFile is no longer used in 76, no?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#8813]
it used to generate looooong console messages, so I went to do something about it, only to discover this:
![screen shot 2016-05-05 at 19 36 36](https://cloud.githubusercontent.com/assets/242577/15051488/291d21ae-12f9-11e6-9ba2-c531bf7a53d9.png)

**Comment by mrdoob** [comment]
Hmm... No, I've been removing these for a while. Wasn't aware that there was some left still.

**Comment by Mugen87** [comment]
@makc Can we close this or are there still some open issues?

**Comment by makc** [comment]
@Mugen87 I have no longer any idea what was this ticket about.
