### ISSUE TITLE
With antialias === false mirroring does not work on WebVR Chromium builds

### ISSUE THREAD

**Issue by dmarcos** [mrdoob/three.js#8815]
##### Description of the problem

If the WebGLRenderer is instantiated with antialias === false when entering VR mode the content is not mirrored in the display and only the headset shows the scene.

Tested with: https://rawgit.com/mrdoob/three.js/dev/examples/webvr_vive.html
##### Three.js version
- [ ] Dev
##### Browser

Chromium WebVR Build from April 24th 2016 (
Version 52.0.2715.0)
##### OS
- [ ] Windows
##### Hardware Requirements (graphics card, VR Device, ...)

HTC Vive

CC\ @toji @fernandojsg

**Comment by dmarcos** [comment]
Is this a Chromium bug?

**Comment by fernandojsg** [comment]
I've tried the @toji webvr-samples (https://github.com/toji/webvr-samples/blob/gh-pages/05-room-scale.html#L96-L97), and if both `antialias` and `preserveDrawingBuffer` are `false` it doesn't works, any other combination works.

**Comment by mrdoob** [comment]
Yeah. I would be surprised if this had something to do with three.

**Comment by mrdoob** [comment]
WebVR Chromium builds are now deprecated.
