### ISSUE TITLE
Loading 3-D models specifying file content rather than path.

### ISSUE THREAD

**Issue by vikasTmz** [mrdoob/three.js#8816]
I want to create an online viewer where a user can upload models and view them, rather than having to edit the path in the source code. 
Since browsers don't allow to retrieve file path but I can read the contents of the file, how do I load a model (obj, ply, mtl etc) given the contents of the file?

**Comment by antont** [comment]
perhaps you can use the three.js editor that already does this, or at least learn from there how it does it .. it's online at http://threejs.org/editor and the code is in /editor in this repo
