### ISSUE TITLE
Parse method in FontLoader and File Reading

### ISSUE THREAD

**Issue by tentone** [mrdoob/three.js#8817]
##### Description of the problem 

In the project im currently woking on, sometimes i had the necessity to parse typeface fonts. Since we do have access to node.js "file system" its nicer to use it.
Here is the code that i'm currently using, it might be of help to other people in the future, and it 
would be nice it could be added to the FontLoader.

```js
function parse(data) {
	return new THREE.Font(JSON.parse(data.substring(65, data.length - 2)));
}
```

Almost all loaders right now use XHRLoader for "plain text" file reading, it would nicer to have this modular so altenative file reading methods could be used instead.  (I can spend some time to take a look as this and propose a solution.)

##### Three.js version

- [x] Dev
- [ ] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Oh yes, we could add a `parse()` to `FontLoader`. Just like `ObjectLoader` has.

**Comment by tentone** [comment]
Thanks a lot! What about the modular file reading? should i open a separate issue to discuss it?

**Comment by mrdoob** [comment]
I didn't quite understand that part.

**Comment by tentone** [comment]
Sorry for my bad explanation.
Currently every loader that needs access to text files (JSONLoader, FontLoader, etc) uses XHRLoader to load the desired file. In platforms like NWJS, Cordova, etc usually there are alternative (sometimes faster) methods to read these text files.
Since XHRLoader is hardcoded into these other loader there is no other way that rewriting the loaders to take advantage of faster file reading when provided by the platforms mentioned above.
My sugestion here is to receive as an argument which "file loader" to use in those cases, and if none received use XHRLoader by default.
Sometimes it may come handy to accelerate application loading when using alternative platforms.

Here as an example in JSONLoader.

```

THREE.JSONLoader = function ( manager, fileLoader ) {

	if ( typeof manager === 'boolean' ) {

		console.warn( 'THREE.JSONLoader: showStatus parameter has been removed from constructor.' );
		manager = undefined;

	}

	this.manager = ( manager !== undefined ) ? manager : THREE.DefaultLoadingManager;

	if ( fileLoader !== undefined )
	{
		this.fileLoader = fileLoader;
		this.fileLoader.setManager(manager);
	}:
	else
	{
		this.fileLoader = new THREE.XHRLoader(this.manager);
	}

	this.withCredentials = false;
};

(...)

	load: function( url, onLoad, onProgress, onError ) {

		var scope = this;

		var texturePath = this.texturePath && ( typeof this.texturePath === "string" ) ? this.texturePath : THREE.Loader.prototype.extractUrlBase( url );

		var loader = this.fileLoader; //instead of new THREE.XHRLoader( this.manager );
		loader.setWithCredentials( this.withCredentials );
		loader.load( url, function ( text ) {

```

**Comment by mrdoob** [comment]
> Since XHRLoader is hardcoded into these other loader there is no other way that rewriting the loaders to take advantage of faster file reading when provided by the platforms mentioned above.

Why not just redefine `XHRLoader` in that environment instead?

**Comment by tentone** [comment]
Well that's actually what i'm currently doing to solve the problem right now and for me it's completely fine. Was just asking about this, cause it might be of use for other people.
(Im actually not a big fan of people using web technology as a way to get support for multiple platforms anyway, but thats another completly different discussion).
