### ISSUE TITLE
utils/build/build.js sourcemaps are not correct

### ISSUE THREAD

**Issue by abelnation** [mrdoob/three.js#8819]
##### Description of the problem 

The sourcemaps that result from build.js do not appear correct.  I think there are a couple of contributing problems:

- some source files are preprocessed before being concatenated together into the final source.  This means that the line numbers referenced by the sourcemap will not match up correctly with the source files on the filesystem.
- no real sourcemap is generated at all for the non-minified version of the build
- mangled variable names don't seem to get mapped back properly (at least in chrome)

I think a tool like [concat-with-sourcemaps](https://www.npmjs.com/package/concat-with-sourcemaps) might be a nice approach for the non-minified version (working on a branch for that).

The uglified sourcemap is a trickier problem.  I can't get the sourcemap to quite line up right w/ the src files.  

I think the primary goal is to make source mapping work for the non-minified version, as that is the version that people will develop/debug with, making the sourcemap a more critical working element.  

...

##### Three.js version

- [x] Dev
- [ ] r76
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Mac
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by bhouston** [comment]
I did try to get them fixed in this PR: https://github.com/mrdoob/three.js/pull/8366

**Comment by abelnation** [comment]
closing this issue, as the conversation seems to be going in #8366
