### ISSUE TITLE
Build via utils/build/build.js broken

### ISSUE THREAD

**Issue by tschw** [mrdoob/three.js#8822]
##### Description of the problem 

After running
```shell
node build.js --include common
```
a `../../build/three.js` is generated, but none of the examples run with it. The output file looks normal, but console messages indicate that classes may be missing.

The `geometry / cube` example logs
```verbatim
TypeError: THREE.BoxBufferGeometry is not a constructor
```
for instance.

What's the status of this approach to building? Is it "officially supported" at all?

##### Three.js version

- [x] Dev
- [ ] r76 ?? probably
- [ ] ?? probably more

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by gero3** [comment]
node build.js --include common --include extras --output ../../build/three.js

is the standard command to build three.js. All examples use parts from extras.

**Comment by tschw** [comment]
Ah.... Thanks!

So this is false alarm? Will check...

**Comment by tschw** [comment]
Yep. I guess I'll add a comment with the invocation syntax to that file :).

**Comment by tschw** [comment]
> Yep. I guess I'll add a comment with the invocation syntax to that file :).

@gero3 
Or is `.scripts` in `package.json` the more appropriate place, maybe?

**Comment by bhouston** [comment]
BTW I rewrote that script a bit a while back to fix a number of issues, never got merged, but it was auto-detecting changes and auto-ran an http-server, it was pretty sweet: 

https://github.com/mrdoob/three.js/pull/8366

**Comment by tschw** [comment]
@bhouston 
> never got merged

Because of the dependency on Java? Closure in basic mode vs. uglify shouldn't be too huge of a difference. The continuous integration part still would have been useful.

Even without a merge the PR was worth something; seems it was the one that brought us the debug builds in the examples :).

**Comment by bhouston** [comment]
Closure is actually much better than uglify:

https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016

@mrdoob wants closure used in the build.js:

https://github.com/mrdoob/three.js/pull/8119#issuecomment-183580419

So if you had time to clean that up, that would be great.  Just under a few client deadlines right now.

**Comment by bhouston** [comment]
Another thing you may notice is that closure supports es transpiling, that is a newish feature it didn't have before.  This means we could technically start adopting newer JS features while maintaining backwards compatibility.

**Comment by tschw** [comment]
> Another thing you may notice is that closure supports es transpiling, that is a newish feature it didn't have before. This means we could technically start adopting newer JS features while maintaining backwards compatibility.

I like closure a lot and recently used it to transpile the ES 2015 library code in https://github.com/tschw/angler.js/ . 

Yes, it's a newish experience with classes and all that :)... I must say it's still a little rough around the edges: ES modules don't work as smooth as `goog.require` / `.provide` yet (didn't want to eat an entry point so couldn't get "strict" dependency mode to work, for instance), so it's been a bit of a fight to get the build up and running...

**Comment by tschw** [comment]
@bhouston 
> So if you had time to clean that up, that would be great. Just under a few client deadlines right now.

What exactly is "wrong" with it / needs to be done / did it not get merged if not because of Java?

**Comment by bhouston** [comment]
Feel free to grab the PR and address any concerns.  One issue was @mrdoob wanted the closure compiler to be still be local in the github repo for python backwards compatibility.  After addressing that, I think that one should probably kill the package.json that is in the /utils/build directory and move its functionality into the root package.json - as that is standard for npm packages.

Thus one can do this at the root from the command line:

```
npm run build // build three.js
npm run serve // run webserver
npm run build-serve-watch // auto-build and serve three.js, this is beautiful. :)
```

**Comment by tschw** [comment]
Nice! 

I'll pull it up once the "constifier" is in place.

**Comment by bhouston** [comment]
If you wanted to make uglify.js versus closure configuration parameter somehow, that would reduce the need to install java.  Just ensure that source maps still work in both cases.

Something along the lines of:

```
npm run build -- --toolset=uglify
npm run build-serve-watch -- --toolset=closure
```

I'd suggest having "build" create the production version and "build-debug" create the non-minified version.  Thus maybe:

```
npm run build-debug // build three.js only
npm run build // build three.js and three.min.js (slower)
npm run serve // run webserver
npm run auto-debug // auto-build and serve three.js only, this is beautiful. :)
npm run auto // auto-build and serve three.js/three.min.js (slower)
```

I guess one could use "auto" or "dev" instead of "build-serve-watch"?  Not sure it is descriptive enough.

**Comment by bhouston** [comment]
One other suggestion, build-debug should produce either a non-minified three.min.js or it should delete  three.min.js -- otherwise one will encourage situations were someone is using a non-updated three.min.js and they'll likely lose a lot of time trying to figure out why things are not working.

"build" should always produce both three.js and three.min.js as three.js is needed for the source map functionality.

**Comment by tschw** [comment]
@bhouston 
> If you wanted to make uglify.js versus closure configuration parameter somehow, that would reduce the need to install java

Yep, I was thinking of simply trying uglify as a fallback when closure is not available.

> "build" should always produce both three.js and three.min.js as three.js is needed for the source map functionality.

Yes, maybe there should be only one build. Knowing you like these kinds of abbreviations just KISS :).
