### ISSUE TITLE
Color and Texture parameters do not align because of gamma

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8827]
##### Description of the problem 

This is likely my fault.  A while back I was trying to ensure that Three.JS would be properly in a linear color space.  As part of this I advocated that the color parameters on materials should be considered to be in linear space and excluded from gamma correction when moving into the linear rendering space.

This has started to cause issues for us.  What is happening is that if someone creates an image that has is composed of a solid color like (0.5, 0.5, 0.5) and sets that as a diffuse texture, and then they want to match that on another object with just a diffuse color of (0.5, 0.5, 0.5 ), the renders of the two objects will not match because we apply a gamma correction to the texture but not the diffuse color.

This discrepancy is problematic to explain.  The gamma correction of the image into linear render space is correct, the results are right, and thus it is likely necessary to also gamma correct the colors into render linear space to match.

We are making this change today -- it is a bug.

I'd prefer to just make the change within glsl as a few small functions rather than adding it back to WebGLRenderer's setting of material uniforms (as it used to be) if possible.

/ping @WestLangley 

##### Three.js version

- [x] Dev
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
@bhouston  wrote:
>This is likely my fault.

There is no fault here. : - )

I will support whatever convention you and the artist community feel is most appropriate.

It is true that this decision has lead us down a long path, and changing it will have some significant ramifications -- both in the examples, and to users.

[This post](https://github.com/mrdoob/three.js/issues/5838#issuecomment-68454839) summarizes what we implemented at one point, but there have been changes since. For example, we now have both:

```javascript
renderer.gammaInput
material.texture.encoding
```

So what would you like (1) the color conventions and (2) the API to be?

**Comment by bhouston** [comment]
I actually did a bunch of checks in Blender, 3DS Max and MAya.  It turns out that that Blender, 3DS Max, and Maya all convert texture inputs from gamma to linear, but assume colors specified directly on materials are in linear space.  Thus by default texture colors do not align with specified material colors in other programs -- thus I guess ThreeJS should stay the way it is because it is standard.

Unity is even weirder, they do not gamma correct textures or colors to linear -- they assume both are linear.  So textures and colors match when rendered, but they are brighter than one would expect.  The equivalent to gammaInput = false.

I think we should probably leave it the way it is.

**Comment by WestLangley** [comment]
@bhouston OK.

But could you please comment on:
```javascript
renderer.gammaInput
material.texture.encoding
```

Was it your intention to remove `gammaInput` at some point? (I assume it remains now for backward compatibility.)

**Comment by bhouston** [comment]
I think it is appropriate to remove ```renderer.gammaInput``` at some point because we offer finer control via ```material.texture.encoding```.  I am okay when ever you want to remove it. :)
