### ISSUE TITLE
Synchronous mouse and keyboard access

### ISSUE THREAD

**Issue by tentone** [mrdoob/three.js#8828]
##### Description of the problem 

   For the project i am currently working on, i wrote some synchronous Mouse and Keyboard access libraries. Since almost every 3D application require input events to be in sync with the render phase and since i had already some people asking me how to it, i will post them down bellow for you to check them and see is there is any chance to include them in the project.
   The idea of these libs is synchronous access to keyboard and mouse events live key presses, mouse movement etc.
   Here is an example of how to use them.

```
//Initialize
Keyboard.initialize();
Mouse.initialize();

//Render/logic loop
(...)
Keyboard.update();
Mouse.update();
(...)

//Keyboard events
if(Keyboard.isKeyPressed(Keyboard.W))
{
	console.log("W is currently pressed");
}
if(Keyboard.isKeyJustPressed(Keyboard.W))
{
	console.log("W was just pressed");
}
if(Keyboard.isKeyJustReleased(Keyboard.W))
{
	console.log("W was just released");
}

//Mouse events
Mouse.buttonPressed(Mouse.LEFT || Mouse.MIDDLE || Mouse.RIGHT);
Mouse.buttonJustPressed(Mouse.LEFT || Mouse.MIDDLE || Mouse.RIGHT);
Mouse.buttonJustReleased(Mouse.LEFT || Mouse.MIDDLE || Mouse.RIGHT);

//Mouse movement
Mouse.pos //Actual mouse position
Mouse.pos_diff //Acumulated mouse movement between update calls
Mouse.wheel //Mouse wheel value
```

[Sync IO.zip](https://github.com/mrdoob/three.js/files/252467/Sync.IO.zip)

##### Three.js version

- [x] Dev
- [ ] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

**Comment by tschw** [comment]
I think a proper solution would have to be higher level and keep track of the time when the events occur: For example, you may want to integrate a constant forward acceleration to a velocity over the precise time the 'W' key is held. This way, control remain accurate when the frame rate drops.

**Comment by tentone** [comment]
The problem here is not detecting continous key presses, those are actually possible using keypress event already provided by the browser, the problem comes when u need to detect diferencial event (Key UP/ Key DOWN) and keep that in sync with app logic, or another example keep the mouse move difference in sync (remember that with mouse locked you cant get absolute mouse position).

**Comment by tschw** [comment]
> The problem here is not detecting continous key presses, those are actually possible using keypress event already provided by the browser, the problem comes when u need to detect diferencial event (Key UP/ Key DOWN) and keep that in sync with app logic, or another example keep the mouse move difference in sync (remember that with mouse locked you cant get absolute mouse position).

OK, isn't that part of the same story, actually?

You also need state, keep track of things and talking about a well-designed library component, it should be just another handler within the same architecture, which BTW could also allow key mappings, like very common in gaming applications, to let the user choose which keys to use for each action...

**Comment by tentone** [comment]
Yes it is all around the same thing, but still, knowing that almost every app needs keyboard / mouse input wouldn't it be easier if there was a solution like this already inside threejs?

**Comment by tschw** [comment]
Not sure. I think a component that handles all the stuff I described above would be awesome to ship with three.js.

However, just deferring events to a render loop seems too special purpose IMO, but my opinion might not be representative or matter all that much. Let's see what others say about it :).

**Comment by tentone** [comment]
I completely agree with you, the files i posted above were just an example. Fot this to be integrated inside threejs those "update" and "initialize" call have to be moved elsewhere and not be called manually in the render loop like the example i posted above. If there is somebody interested in this, i can work on it and try to propose a solution lets see what other people think.
