### ISSUE TITLE
ColladaLoader requires both <transparent> and <transparency> tags

### ISSUE THREAD

**Issue by theshanergy** [mrdoob/three.js#8835]
##### Description of the problem

Line 3659 of ColladaLoader.js requires both `<transparent>` and `<transparency>` tags as defined by the switch on 3597. I don't know about other editors but in Blender at least, only the `<transparency>` tag is produced, which prevents any opacity changes.

As a workaround one may manually add the following in the material effect:

```
        <transparent>
           <color>1 1 1 1</color>
        </transparent>
```

However it would be nice if the loader checked for the existence of a lone `<transparency>` tag and used that value if it exists.

Also to note, the actual transparency value seems to be reversed as a result of the `1 -` on 3667. An alpha of 70% in Blender becomes 0.3 opacity in three.

For reference, blender produces the following for an alpha setting of 70%:

```
        <transparency>
          <float sid="transparency">0.7</float>
        </transparency>
```
##### Three.js version
- [x ] r76

**Comment by tschw** [comment]
Since you already analyzed the problem and seem to have a solution for it, why don't you make it a PR?

**Comment by Mugen87** [comment]
The new `ColladaLoader` implements this differently. Both tags `<transparent>` and `<transparency>` are more decoupled now.
