### ISSUE TITLE
Co

### ISSUE THREAD

**Issue by crecord** [mrdoob/three.js#8837]
##### Description of the problem 

I am loading a collada file with a texture. This was working in my code up till recently, so I think it might be connected to the new update to chrome. The texture loads sometimes, but other times it appears black and will not load no matter how long I wait. 

I've noticed this problem in all the three.js collada examples as well. There are no errors in the console or in terminal. It will just randomly load or not. I tested it in firefox and the textures loaded fine. 

<img width="634" alt="screen shot 2016-05-07 at 12 44 01 pm" src="https://cloud.githubusercontent.com/assets/3160465/15093329/99b7eb74-1452-11e6-9a3d-8e04fd4df69c.png">

<img width="901" alt="screen shot 2016-05-07 at 12 47 13 pm" src="https://cloud.githubusercontent.com/assets/3160465/15093330/a32db440-1452-11e6-9476-c2f1142249ee.png">

 
 
...

##### Three.js version

- [x] Dev
- [ ] r76
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by crecord** [comment]
Since this problem appears in the examples as well as my own code I assumed it was appropriate to post it here... Was I mistaken?

**Comment by mrdoob** [comment]
I bet is related to this:
https://github.com/mrdoob/three.js/wiki/How-to-run-things-locally

**Comment by crecord** [comment]
Fixed it! Thank you. Sorry for posting in the wrong location.
