### ISSUE TITLE
Move clear color/alpha/auto to scene rather than as global state on WebGLRenderer?

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#8842]
##### Description of the problem 

I've been thinking about the clearColor and clearAlpha on WebGLRenderer.  I've come to the conclusion that this shouldn't be WebGLRenderer state, rather it should be Scene state (or Pass state, which is like an override clear color/alpha.)  The reason is if you are rendering many scenes, you will often have different background colors for each one, also when you are rendering various passes, there are different pass clear color/alpha.

Right now having it as global state on WebGLRenderer seems to be just mirroring the global state of WebGL, but for the most part Three.JS usually tries to put the state on the appropriate object.  This seems like one of the last remaining places were we do not make WebGL objected oriented in its state.

I am not completely sure of the right solution, but putting clearColor and clearAlpha and autoClear on Scene makes the most sense.  We have already moved fog to Scene, which has a very similar purpose to clear Color/Alpha (and often has to be synchronized with it):

https://github.com/mrdoob/three.js/blob/master/src/scenes/Scene.js#L11

I guess one issue that arises is that one often needs to render a scene a few different ways, such as a depth pass (via depth override) or a normal pass.  Not sure the best solution to handle that - although my preference would be for the override material to have a clear color/alpha to be used in that case.

/ping @tschw @WestLangley 

##### Three.js version

- [x] Dev
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by tschw** [comment]
I like the idea to control as much render state as possible by means of the data model.

In some cases the camera might be another option: Fog settings are typically related to the `near` / `far` values of the camera rendering it, for example.

**Comment by WestLangley** [comment]
@bhouston Rather than removing `clearColor/clearAlpha` from the renderer's state, how about adding it also as a property of `WebGLRenderTarget`? The renderer's `clearColor` would then be reserved for the default drawing buffer.

I think that approach would satisfy your use cases. I am not sure moving it to the scene or the material is the right approach.

**Comment by mrdoob** [comment]
I guess `Scene.background` solved this?

**Comment by bhouston** [comment]
Yes, thank you!
