### ISSUE TITLE
In CSS3DRenderer setting a number with e describe, will make the matrix3d not working

### ISSUE THREAD

**Issue by Lukeisme** [mrdoob/three.js#8845]
##### Description of the problem

In CSS3DRenderer setting a number with e describe, will make the matrix3d not working.

For example,if there is a number '-3.5084e-11' in the css matrix3d.It will make the transform property not working.

I'm testing in android 4.3. 
##### Three.js version
- [x] Dev
- [x] r76
- [ ] ...
##### Browser
- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android4.x
- [ ] IOS

**Comment by Lukeisme** [comment]
I fixed this bug by fixing the value of the number. And I works for me.

**Comment by mrdoob** [comment]
Oh. I thought this was an issue only in Safari.

**Comment by Lukeisme** [comment]
I thought the CSS3DRenderer is for a better compatibility.So if it can work on more browsers, it will be fine.I'm using Number.toFixed(6) to format the number in CSS3DRenderer.It seems work fine.

**Comment by mrdoob** [comment]
Wait. Is this on Android's stock browser?

**Comment by Lukeisme** [comment]
yes.I'm testing on Android4.3 UCBrowser and some app's web view

**Comment by Mugen87** [comment]
Closing. If a browser has still problems with scientific notations for numbers in 2018, please file an issue at the respective bug tracker.
