### ISSUE TITLE
mapTexelToLinear - no matching overloaded function found 

### ISSUE THREAD

**Issue by JordanDelcros** [mrdoob/three.js#8846]
##### Description of the problem 

When I try to create a complete copy/clone of the `MeshPhongMaterial` with `ShaderMaterial` and the `chunks` it work correctly but if I switch `material.map = true` I get this error:
'THREE.WebGLShader: gl.getShaderInfoLog() fragment ERROR: 0:1210: 'mapTexelToLinear' : no matching overloaded function found'

I searched into the chunks folder for this GLSL function but found nothing.

##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
`material.map = true `?

**Comment by JordanDelcros** [comment]
Yes, it is the flag to set #define USE_MAP to true in the shader no ?

Cause when I don't put `material.map = true` the `vUv`varying is not defined.

And when I put it to `true` I got the error: `THREE.WebGLShader: gl.getShaderInfoLog() fragment ERROR: 0:1210: 'mapTexelToLinear' : no matching overloaded function found`

So, I tried to find the method `mapTexelToLinear` GLSL method into the chunks and dont found anything.

**Comment by WestLangley** [comment]
You should be setting defines like so:

	var defines = {};
	defines[ "USE_MAP" ] = "";

	var material = new THREE.ShaderMaterial( {
		defines        : defines,
		uniforms       : uniforms,
		vertexShader   : shader.vertexShader,
		fragmentShader : shader.fragmentShader
	} );

I am not sure what is going on with your `mapTexelToLinear` issue.

**Comment by mrdoob** [comment]
`material.map` can be either `THREE.Texture` or `null`.
