### ISSUE TITLE
Can only rotate camera around one axis at a time on Safari

### ISSUE THREAD

**Issue by andrewb273** [mrdoob/three.js#8856]
##### Description of the problem 

I can only rotate the camera around a single axis at a time on Safari for desktop, mobile, and Safari Technology Preview for desktop.

A JSFiddle - https://jsfiddle.net/3zb5yapp/ - I've used for testing. Tweak the options at the top of the JS, and see how it freezes if more than two axes of rotation are selected. However this works fine on Firefox and Chrome.

I suspect that this may be related to #8839.

##### Three.js version

- [ ] Dev
- [X] r76
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] IOS
- [x] OS X

##### Hardware Requirements (graphics card, VR Device, ...)

OS X: 2014 MacBook Pro Retina, dGPU
iOS: iPhone 6

... given it's prevalent on Safari across desktop and mobile, I suspect it's not a specific hardware issue.

**Comment by andrewb273** [comment]
var epsilon = function ( value ) {
        return Math.abs( value ) < Number.EPSILON ? 0 : value.toFixed( 6 );
    };

as described in #8839 does seem to fix this issue, though there are warnings about potential inaccuracies by @WestLangley.

**Comment by mrdoob** [comment]
#7802
