### ISSUE TITLE
I am not able to remove objects from Scene properly...  causes lag, can you help?

### ISSUE THREAD

**Issue by RudyAramayo** [mrdoob/three.js#8864]
##### Description of the problem 

How do you properly delete objects from the scene? I use the dat.gui slider and it calls rebuildParticles. This slider will only control number of particles to make, but when we go back and forth there is a lag from all the particles we added, even when the scene has only a few particles showing.

Can you please take a look at my code:
http://orbitusbiomedical.github.io/BioPen/tornado3.html

function rebuildParticles() {
	console.log('rebuildParticles' + scene.children);
	

	//-----
	//create particles

	//Crate
	//THREE.TextureLoader.crossOrigin = '';
	//THREE.ImageUtils.crossOrigin = '';
	texture = new THREE.TextureLoader().load( 'img/crate.gif' );
	geometry = new THREE.BoxGeometry( 10, 10, 10 );

	//------
	//We can't uyse the cross origin image file on the file:/// during development... 
	if (document.location.href.startsWith("file:///"))
	{
		material = new THREE.MeshLambertMaterial( { color:0xffff00 } );
	}	
	else
	{
		material = new THREE.MeshLambertMaterial( { map:texture, color:0xffff00 } );
	}
	//------

	
	//Sphere
	//geometry = new THREE.SphereGeometry( 1, 32, 16 );
	//material = new THREE.MeshLambertMaterial( { color: 0x000088 } );

	//remove all particles meshes from the scene
	
	var children = scene.children;
    for(var i = children.length-1;i>=0;i--){
        var child = children[i];
        if (child.isParticle)
        {
        	scene.remove(child);	
        }
        
    };   

	particles = [];

	for (var i = 0; i < particleOptions.particleCount; i++)
	{

		mesh = new THREE.Mesh( geometry, material );//THREEx.Crates.createCrate1();   //
		mesh.position.set(-500 + Math.floor((Math.random() * 1000) + 1), 5,  -500 + Math.floor((Math.random() * 1000) + 1));
		scene.add(mesh);
		mesh.S = new THREE.Vector3(mesh.position.x,mesh.position.y,mesh.position.z);	//position
		mesh.V = new THREE.Vector3(0.0,0.1,0.1);//Math.floor((Math.random() * 1))-0.5,Math.floor((Math.random() * 1))-0.5); //velocity
		mesh.M = 1;								//mass
		mesh.mesh_falling = true;
		mesh.mesh_raising = false;
		mesh.isParticle = true;
		mesh.topCutOff = 750 + Math.floor((Math.random() * 250) + 1)
		//G is the raising velocity and makes a great tornado when its randomness is varied
		//tempG just holds individual values for each particle
		mesh.tempG = new THREE.Vector3(G.x,G.y - Math.floor((Math.random()*10) - 5) * .0001, G.z); -.001
		particles.push(mesh);
	}

	//-----
}

##### Three.js version

- [ ] Dev
- [ ] r76
- [X] r65

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by RudyAramayo** [comment]
r76 has fixed this issue.. the deleted objects are now not lagging when I delete them over and over... never mind!

**Comment by TingYinHelen** [comment]
@RudyAramayo Umm...I encounter the same problem. Can you tell me some detail? I can't remove the object in the scene. Why....

**Comment by Mugen87** [comment]
@TingYinHelen Please use stackoverflow or the [forum](https://discourse.threejs.org/) for help question.

**Comment by TingYinHelen** [comment]
@Mugen87 Ok, I got it. Thanks

**Comment by TingYinHelen** [comment]
@Lynxgsm Umm...I don't think so....cause three.js is not a data driven frame. If you just remove the element in array, it will not work...

**Comment by Lynxgsm** [comment]
I don't know if we have the same goal but it worked for me.
