### ISSUE TITLE
Editor CSS3Renderer

### ISSUE THREAD

**Issue by kornellvarga** [mrdoob/three.js#8866]
##### Description of the problem 
I am using the THREE.js awsome Editor, but the CSSRenderer constructor seems to be missing from it. Is there a workaround? Do I have to include embedded websited after all the design is done? Would be great if I could work with them from the editor too!

"var cssRenderer = new THREE.CSS3DRenderer();"
On an Init Script within the THREE.js Editor.
...

##### Three.js version

- [ ] Dev
- [x ] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
The `CSS3DRenderer` is a special case, compared to the other renderers. It can only render `CSS3DObjects`. So I don't know exactly how that would work... It kind of would require it's own version of the editor.

**Comment by kornellvarga** [comment]
I appreciate the answer! To be frank I am not an expert in web programming, only my basic understanding of JS brought me till here.
So... I might not even need CSS3D because what I want to display on top of the WebGL part does not need to be seen in 3D. Basically I have a button in THREE.js that should open an overlay .html, that anyway blocks all THREE.js scene controls until closing the html gives the control back.
Do you have any suggestions?

**Comment by kornellvarga** [comment]
Hmm, I understand that its annoying when a noob floods your issues section...., im gonna open a case on Stackoverflow, thanks for the .... "tip".. . Im just afraid that ppl will refer me back to you, when I ask how to open a canvas from THREE.js on top of the WebGL surface.... :(
well... either way THREE.js is awsome, and so is the editor! thx.
