### ISSUE TITLE
glTF models cannot be copied or cloned

### ISSUE THREAD

**Issue by kkananen** [mrdoob/three.js#8869]
##### Description of the problem

The current glTF loader works in a slightly unexpected manner: shaders and animations point to a specific instance of a loaded glTF hierarchy, so .clone() or .copy() operations on that hierarchy will drop the links, resulting in the copy not rendering nor animating.

I am intending to patch this in vizor.io initially by providing a deepCopyglTF() function which also goes off and clones the animations and shaders and rebinds them to the new copy. 

However as a long-term-solution for three.js it would be preferable to be able to copy and clone these things via the standard three.js way - i.e. calling .copy() or .clone(). This would require the glTF loader to be refactored so that the loaded mesh hierarchy is entirely self contained with no extra external resources pointing to it (this would also remove the need to update glTFAnimator and glTFShaders explicitly). I'm unlikely to get to that anytime soon but would be interested in hearing if anyone else has given thought to this or is working on a similar issue?

ping @tparisi

**Comment by tparisi** [comment]
Yes that sounds like something useful... when you say it "works in a slightly unexpected manner" what would you expect? How would you refactor the data structures? Happy to take a look though I'm not sure when I can get to it.

**Comment by kkananen** [comment]
In other words, 'slightly unexpected manner' = the object3d hierarchy loaded from a glTF depends on external components (assets and animations) in a manner which makes it not comply with the .clone() and .copy() semantics. I would have expected that copy&clone on the root object3d loaded from a glTF would have given me an object that renders.

To refactor this, either the shader/animation(s) would need to be contained within the loaded hierarchy  OR if it is more desirable that they are owned by an external container (glTFShaders/glTFAnimator), the direction of referencing would need to be reversed: instead of the shader/animation pointing to a mesh, the mesh would have a reference to the shader/animation. The latter approach might not work for animations unless all copies would animate at the same pace, which might need further refactoring.

**Comment by easyfrog** [comment]
so. How to clone a gltf model now ???

**Comment by donmccurdy** [comment]
Partial update on this: As of r83, THREE.GLTFLoader now uses the core threejs animation libraries. Because `new THREE.AnimationMixer( root )` is instantiated with a reference to the object, you can create a new mixer for the clone/copied model without any conflicts.

I don't know where things are at for shaders, however.

**Comment by easyfrog** [comment]
Is the gltfloader could clone now ?
If don't solve this problem this loader is useless. because is It is very common to clone a model.

**Comment by donmccurdy** [comment]
@easyfrog There are situations in which cloning a GLTF model will still fail. Specifically, custom GLSL shaders. If you run into further cases, please do file an issue.

**Comment by donmccurdy** [comment]
The original loader for glTF 1.0 has been replaced with the loader for glTF2.0. There are fewer edge cases for cloning, but still a few (specifically skinned animation). 

Closing this issue: the glTF2-specific issues are tracked by #11573.
