### ISSUE TITLE
update lib at google cdn :)

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#8870]
the latest version over there is https://ajax.googleapis.com/ajax/libs/threejs/r73/three.min.js what happened?

**Comment by mrdoob** [comment]
This is something that @maxhawkins pushed for while at google but seems like no one continued after he left...

**Comment by maxhawkins** [comment]
Hm, I'm not sure the best way to update this. @philwo do you have any ideas?

**Comment by philwo** [comment]
Thanks for letting me know! I'll upload the missing versions to the CDN today.

I'll make sure to regularly check the three.js website for updates, but please feel free to also ping me via e-mail or GitHub when you release a new version, so that I can grab and upload it asap. :)

**Comment by WestLangley** [comment]
@philwo Thanks! Can you update https://developers.google.com/speed/libraries/#threejs, too?

**Comment by philwo** [comment]
@WestLangley Yep - done now! :)

**Comment by WestLangley** [comment]
@philwo Sweet. Thanks!
