### ISSUE TITLE
Maya's JSONExporter doesn't export MorphTargets

### ISSUE THREAD

**Issue by markskelton** [mrdoob/three.js#8874]
##### Description of the problem

I have an issue when I export a JSON file from Maya using the JSONExporter. I have been trying to export a character with morph targets, but can see no option for this on export and no field for 'Morph Targets' in the JSON file after export.

I have searched all over for an answer to this and posted a question to StackOverflow, still with no solution (http://stackoverflow.com/questions/36773360/how-do-i-export-a-json-file-with-morph-targets-from-maya) leading me to believe that this is an issue.

Another issue with the JSON export from Maya is that when I import my character into my Three.js scene and move a bone, there seems to be a duplicate mesh underneath that doesn't move. This does not occur when I export from Blender. I'm not sure if this issue is related to the one I am posting about.
##### Three.js version
- [ ] Dev
- [x] r76
- [ ] ...
##### Browser
- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] IOS

**Comment by markskelton** [comment]
I see now that I should have had 'Bake Animations' checked. I have no checked this box, but morph targets still don't export. I have tried placing each target object at a different frame and it still does not export morph targets.

**Comment by donmccurdy** [comment]
Per https://github.com/mrdoob/three.js/issues/12903, the most reliable way to get animations from Maya would probably be FBXLoader or GLTFLoader these days. If you're able to share an example file (preferably something I can open in Maya LT) I can take a look.
