### ISSUE TITLE
Problem with ShaderMaterial and "position" attribute

### ISSUE THREAD

**Issue by tlecoz** [mrdoob/three.js#8880]
##### Description of the problem 

Hello !
I'm working on a library based on Three.js to be able to write GLSL-Shader with a OOP logic. 
It's a bit like "ShaderLib" but it's easier to use because you can target a specific bunch of code and you can "unshift" / "push" some line of code (or you can enable/disable/replace it). 

I also made a class based on Mesh & ShaderMaterial to be able to manage uniforms & attributes from a single object to be able to easily write shader based on custom attributes. 

Every definition of uniform/attributes/constants is written automaticly in the GLSL code, then only the content of the "main" function of vertexShader / fragmentShader must be defined.

The GLSL code creation works as expected : 
I made a quad-color-particle-shader, then I extend it to create a quad-texture-particle-shader, then I extend it to create to quad-spritesheet-particle-shader, then I extend it to create a quad-movieclip-shader and a bitmapText-quad-particle-shader (supporting several "textformat" and several "bitmapFonts" with the same shader)
Each time I extend a class, the glsl become a bit more complex but the class in itself stay easy to read. 

Everything works well but I have now an issue, and my issue come from Three.js, not from my tool...

I'm trying to build a textfield-shader based on my bitmapText-shader but something goes wrong when I try to use "position" attribute to NOT store triangle-vertices. I want to use "position" attribute to store the center of my textfields ; the position of the text-characters in the textfield use a vec4-attribute that store the XYZ-vertex and the "spritesheet-frame-index" corresponding to the textchar I want to draw. 

It's better to store these 4 informations in the same buffer because the XYZ position of a char depends on the width of the textchar I need to draw (when I will update the text of a textfield, every XYZ-frameIndex will be updated). 

Here is my issue : 

When my position-attribute (representing the center of my textfieds-object) is full of zero, everything works as expected, but if I set- for example - every z-position on 1000, in order to change the z of every-textfield, the code works but I have what look like a camera-issue (it's like, at a particular rotation, my triangle were farest / closest from the camera and nothing is drawn - and it's not the case - ) 

I'm sure the problem come from how I use the position attribute because if I try to store the vertices of the textChar in the position-attribute, and the position of the textfield in the buffer I originally used to store the textChar position, everything works as expected.

It works, but as I said earlier, the code should be more optimized if the textChar-position and the "spritesheet-frame-index" share the same buffer. 

I think, but I'm not 100% sure, that when I update the position-attribute, Three try to compute a bounding-box from it and then update some values in the camera and because my position-attributes is not consistent to create a bounding-box, I have an isssue. 

So I have 2 questions : 
- can I disable the boundingBox management of the position-attribute ? (I searched a lot but didn't find it) 
- Can I use a vec4 position attributes instead of a vec3 ?
  -I got an error-message when I tryed to define a "position" attribute as a vec4, then I suppose it's not possible... -
 

I thought about using RawShaderMaterial instead of ShaderMaterial but I think it's not a good idea because I don't want to rewrite every part of Three.js just to be able to define correctly the position-buffer. In a perfect world, RawShaderMaterial should contains every stuff contained in ShaderMaterial without any attributes but it's not how it works ... 

Just to be sure you understand what my problem is, here is 2 demos  :  

The first one with a position-attribute full of zero : 
http://beginfill.com/gpuText/testShader.html

The exact same code with a position-attribute with every "z" set on -1000
http://beginfill.com/gpuText/withProblem/testShader.html

In the second code, you can show the issue if you mousepress and move to the right of the screen ; when the mouse position is too much at right, the whole mesh disapear...

Sorry for this very long message, and sorry for my approximative english, it's not my native language.

Any help is welcome !

(You can see the GLSL code of the shader if you press F12)

...

##### Three.js version

- [ ] Dev
- [X ] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/.github/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js).
