### ISSUE TITLE
Position Issue with Geometry

### ISSUE THREAD

**Issue by alf007mx** [mrdoob/three.js#8881]
##### Description of the problem 
Hi!

I'm using the following example of outline geometry. But there is a problem in the line 
   **outlineMesh1.position = sphere.position;** it doesn't set the position of the sphere to the outlineMesh1. Does the r76 version have a different way to assign the position?

    var material3 = new THREE.MeshNormalMaterial();

    var sphereGeometry = new THREE.SphereGeometry(50, 32, 16);
    var sphere = new THREE.Mesh( sphereGeometry, material3 );
    sphere.position.set(-60, 55, 0);
    sphere.name = "Esfera";
    scene.add( sphere );
    
    var outlineMaterial1 = new THREE.MeshBasicMaterial( { color: 0xff0000, side: THREE.BackSide } );
    var outlineMesh1 = new THREE.Mesh( sphereGeometry, outlineMaterial1 );
    outlineMesh1.name = "Contorno";
    outlineMesh1.position = sphere.position;
    outlineMesh1.scale.multiplyScalar(1.05);
    scene.add( outlineMesh1 );

It works under the r60 version of Three js.
...

##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by aardgoose** [comment]
Hi,

Try mesh.position.copy ( sphere.position );  (the position property is read only, presumably it wasn't a while ago, but it's methods can be used to modify it.

(I imagine this is really a stackoverflow question FWIW)

**Comment by WestLangley** [comment]
http://stackoverflow.com/questions/26905929/three-js-2xmeshes-using-same-vector-as-position/26916159#26916159
