### ISSUE TITLE
Blender cycles doesn't exporter lambert materials

### ISSUE THREAD

**Issue by shanadeshana** [mrdoob/three.js#8887]
##### Description of the problem 

...

##### Three.js version

- [ ] Dev
- [ ] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

I've been trying all different ways of exporting my object's materials as lambert materials but it seems there's a problem.
Just add a cube to your scene add a BSDF material to it. I tried putting the specular color to black to no avail. the exporter exports the material as a phong material

I read the exporter python files and it seems that indeed it's possible:
```
`logger.debug("material.type(%s)", material)
    if material.diffuse_shader != 'LAMBERT':
        material_type = constants.BASIC
    elif material.specular_intensity > 0:
        material_type = constants.PHONG
    else:
        material_type = constants.LAMBERT

    return material_type`
```

But I just tested some ways of doing it to no avail

**Comment by mrdoob** [comment]
Why does it have to be using Cycles?

**Comment by shanadeshana** [comment]
It can't be done in cycles? I wasn't sure so I thought it was a bug.

How has to be set to export in blender internal render as lambert materials?

**Comment by Mugen87** [comment]
> How has to be set to export in blender internal render as lambert materials?

I think you have to set the specular intensity of the respected material in Blender to zero (see [here](https://github.com/yomotsu/three.js/blob/dev/utils/exporters/blender/addons/io_three/exporter/api/material.py#L327)).

![image](https://cloud.githubusercontent.com/assets/12612165/15364907/821308ee-1d1e-11e6-9f64-4aa7684dd737.png)

**Comment by Mugen87** [comment]
Do you really set the specular intensity of the respected material to zero? I thought this should force a lambert material...

![image](https://cloud.githubusercontent.com/assets/12612165/15364978/c9271ba8-1d1e-11e6-98f9-d63a10d93809.png)

**Comment by Mugen87** [comment]
Oh i see! You have this option only with the Blender Renderer. Cycles shows you a total different menu. Well, i think you need to work with the Blender Renderer and apply the mentioned specular intensity value...
