### ISSUE TITLE
Face colors can't be updated properly & colorsNeedUpdate property can't be changed

### ISSUE THREAD

**Issue by bwilytsch** [mrdoob/three.js#8888]
Hi there,
I am not sure if this is my fault, but following advices so far on stackoverflow updating the face colors OR setting the colorsNeedUpdate property to true doesn't seem to work for me.

```
var cubeGeometry = new THREE.BoxGeometry(2,0.01,2);
var cubeMaterial = new THREE.MeshBasicMaterial({ color: 0x0000FF, vertexColors: THREE.FaceColors })

var cube = new THREE.Mesh( cubeGeometry, cubeMaterial );

cube.geometry.faces[4].color.setHex( 0xFF0000 );
cube.geometry.faces[5].color.setHex( 0xFF0000 ); 
cube.geometry.colorsNeedUpdate = true;
```

In my example it seems that both the face color and material color are blending together. Here is a codepen — http://codepen.io/bwilytsch/pen/GZLmLe

##### Three.js version
- [x] r76

##### Browser
- [x] All of them

##### OS
- [x] OSX

**Comment by WestLangley** [comment]
http://stackoverflow.com/questions/27506997/superimposing-of-color/27737708#27737708
