### ISSUE TITLE
Video panorama has "cross origin" issue?

### ISSUE THREAD

**Issue by greenSnot** [mrdoob/three.js#8889]
##### Description of the problem 

http://threejs.org/examples/#webgl_video_panorama_equirectangular
According to this example, I modify the videoUrl to CDN address instead of local path.And use a mp4 video file instead of webm so that I can run in Safari.
Chrome(v50 Mac OSX) work well but safari(v9.02 in Mac & iOS 9.3.1 mobile safari) can't play it and throw the error:

> [Error] Error: SecurityError: DOM Exception 18 

I'm sure that I have set the crossOrigin to '*' or 'anonymous'
```
  var cross='anonymous';
  video.crossOrigin=cross;
  THREE.ImageUtils.crossOrigin =cross;
  THREE.Loader.crossOrigin =cross;
  THREE.ObjectLoader.crossOrigin=cross;
  THREE.TextureLoader.crossOrigin= cross;
```
 
If I use local path,Both Chrome and Safari work well.

##### Three.js version

- [ ] Dev
- [*] r76
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [*] Safari v9.02 in Mac & iOS 9.3.1 mobile safari
##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [*] IOS
- [*] Max OSX

**Comment by makc** [comment]
I dont see anything in safari, I think it is because that pos browser cant handle webm

**Comment by makc** [comment]
here http://caniuse.com/#feat=webm

**Comment by greenSnot** [comment]
I know that, so I use mp4 file instead of webm. Problem is the videoUrl, when I use local path both Safari and Chrome work well.

`video.src='./test/test.mp4';`

If I use remote address Chrome works well but Safari throws the error (See above)

**Comment by mrdoob** [comment]
If it works in Chrome, shouldn't this be reported to Safari/Apple?

**Comment by greenSnot** [comment]
Sorry,I'm not sure that is a Safari bug. 
The bug still not fixed in iOS9.

http://krpano.com/ios/bugs/ios8-webgl-video-cors/

**Comment by NongDeng** [comment]
same error. Is anyway to solve it?
