### ISSUE TITLE
Are there advantages or disadvantages to using JSON?

### ISSUE THREAD

**Issue by bonecast** [mrdoob/three.js#8890]
##### Description of the problem 
I am not sure if i can ask such beginner questions here...
but i tried both the IRC chatroom and Stackexchange. and in both i get no response at all.

I am trying to replace example models with my JSON model.
And i just cant get it to work proper. everytime its either not there.
Or i get a black cube in the left corner.

I am starting to wonder if it has to do with the fact that i am exporting from blender
to Json. Because even the blender example in threejs.org does not seem to use json?

What i am trying to achieve is a decent looking turntable style page.
Where i can showcase my models. preferably with normals etc.
Kinda like the marmoset viewer. But it does not have to be as 'flashy' as that.

some examples i am trying to add the JSON model in:
http://threejs.org/examples/#webgl_geometry_teapot
http://threejs.org/examples/#webgl_loader_ctm_materials

##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
GTX 970

**Comment by makc** [comment]
> I am starting to wonder if it has to do with the fact that i am exporting from blender
to Json. 

I did that just yesterday and it worked with r76, so it's just you :) 

> I am not sure if i can ask such beginner questions here.

Indeed you can, they send everyone to stackoverflow.

**Comment by bonecast** [comment]
> Indeed you cant, they send everyone to stackoverflow.

Oh ok. nobody is responding on stackoverflow though :P
And yet here i get a straight answer right away ^^
On the website they do bundle github together with stackoverflow and irc though.
Making it look as if this is a source to ask questions ^^ thats why i tried.

Still have not managed to swap a model with mine though. even simple cube in json format.

**Comment by bonecast** [comment]
Btw i tried checking out your wordpress makc ^^ but it gives me a offline page.

**Comment by makc** [comment]
That's what you get for free blog host, it goes up and down when it feels like, serves ads and so on. Not posting much any way.

**Comment by makc** [comment]
here is random code to load blender exported json:
```javascript
		var objectLoader = new THREE.ObjectLoader ();
		objectLoader.load ('assets/truck.json', function (truck) {
			// do some stuff with it (or dont)
			truck.rotation.y = 0.5 * Math.PI;
			truck.traverse (function (object) {
				if (object.geometry) {
					object.material = truckMaterial;
				}
			});
			scene.add (truck);
		});
```

**Comment by bonecast** [comment]
Man confusion.

This is my old code which gives me a green model from the first tutorial on the website.

> 			// Placing model
			var loader = new THREE.JSONLoader();
			loader.load ( 'models/jesus.json',
				// Function when resource is loaded
				function ( geometry, materials ) {
					//var material = new THREE.MultiMaterial( materials );
					var material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } ); //green color
					var object   = new THREE.Mesh( geometry, material );
					scene.add( object );
				}
			);
			
			camera.position.z = 7;


			// you cant see the mesh yet we need to render it in a loop, this loops.
			function render()
			{
				requestAnimationFrame( render );
				//object.rotation.x += 0.1; // does not work
				renderer.render( scene, camera );
			}
			render();

then i tried your to rotate
but i just get black canvas :(



> 			// setting up scene
			var scene    = new THREE.Scene();
			var camera   = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 ); // PerspectiveCamera( fov , aspect , near , far )
			var renderer = new THREE.WebGLRenderer();
			
			renderer.setSize( window.innerWidth, window.innerHeight );
			document.body.appendChild( renderer.domElement );
			
			
			
			
			var objectLoader = new THREE.ObjectLoader ();
			objectLoader.load ('models/jesus.json', function (truck) {
            // do some stuff with it (or dont)
            truck.rotation.y = 0.5 * Math.PI;
			var material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } ); //green color
            truck.traverse (function (object) {
                if (object.geometry) {
                    object.material = truckMaterial;
                }
            });
            scene.add (truck);
        });
			
			
			camera.position.z = 7;

			
			
			
			
			// you cant see the mesh yet we need to render it in a loop, this loops.
			function render()
			{
				requestAnimationFrame( render );
				//object.rotation.x += 0.1;
				renderer.render( scene, camera );
			}
			render();
