### ISSUE TITLE
How an ellipse in a path should work (dev)

### ISSUE THREAD

**Issue by rfm1201** [mrdoob/three.js#8897]
I don’t understand the way an ellipse works in the THREE.Path class. I think it is buggy but maybe it’s not and I want to be sure before changing anything in the code.
I made a [JSFiddle](https://jsfiddle.net/wdsmy9k3/) to show my concerns. This JSFiddle point on the current dev version of three.js, it can be used to check any evolution in the ellipse code.
The scene is quite simple, just a path with an ellipse, closed or not, and optionally a first point before the ellipse. The code is:

```
  if (pointBefore) {
    if (onRight)
      path.moveTo(20, 0);
    else
      path.moveTo(-20, 0);
  }
  path.absellipse(0, 0, 20, 10, 0, endAngle, clockwise, 0);
  path.autoClose = autoClose;
```

Depending of the five checkboxes available in the page, autoClose value can be true (checked) or false, clockwise true (checked) or false, endAngle 2*Math.PI (checked) or Math.PI, pointBefore true (checked) or false and onRight true (checked) or false.
The ellipse is shown in blue with the help of createPointsGeometry, in red with the help of createSpacedPointsGeometry. So in blue we see the result of getPoints and in red the result of getSpacedPoints. The points returned are shown by sphere to help read the result.

Here are my concerns.
-   When nothing is checked, the ellipse is from 0 to PI reverse clockwise (positive y). Why none of the 2 curves finish on the (-20, 0) point?
-   Why getPoints (blue curve) multiply by 2 the number it receives? I ask for 5 points not 10. The multiplication is line 375 of Path.js for the ellipse and in line 336 for an arc.
-   Check "Add point before ellipse". It adds a first point in the path in (-20, 0). It change the blue curve, not the red one. Why both curves aren’t the same?
-   Why does getPoints need a first point on the left when the ellipse is reverse clockwise? To be shure check "On the right", the first point is now in (20, 0), the blue line clearly shows that getPoints rotate clockwise. Need another proof, check clockwise, the blue line is now reverse clockwise.
-   Why adding a first point change the result of getPoints and have no effect on getSpacedPoints? Part of the answer is that getSpacedPoints as a problem with the last point not the first as getPoints do.
-   When you check clockwise, getSpacedPoints (red line) change the way it rotate on the ellipse from the starting angle to the ending one. getPoints doesn’t do the same thing. It always stays on the same part of the ellipse and change the order of the points. Which one is right?
-   Check "Full ellipse" and "clockwise". getSpacedPoints return an array of (0, 0) points. Here I think it’s clearly a bug. The code in THREE.EllipseCurve.prototype.getPoint should take care of the value of deltaAngle before doing ( Math.PI \* 2 - deltaAngle ) (line 36). DeltaAngle can be 2*PI and in that case it should be used directly.

For me the part of the ellipse used and the way it is run should be the same for both getPoints and getSpacedPoints. Am I rigth or wrong?
If I’m right, which one is ok? I vote for getSpacedPoints, but I can be wrong.
If I’m wrong, the documentation should explain in more details what those functions do.
I can be ok with the fact that a moveTo should be added before adding the ellipse, it’s a path not a curve, but I disagree with the fact that getPoints and getSpacedPoints don’t react the same way to that first point. Here getPoints is better that getSpacedPoints but it rotate the wrong way to my opinion.

Can someone, who is part of the specification team, tells me what is going on and if things must be checked?
I can check them myself, I just need a clear specification of the way things should work.

**Comment by WestLangley** [comment]
@rfm1201 Thank you for looking into this. It is tedious, and there may, in fact, be inconsistencies. Your example is very helpful.

You may have to step through the codebase to answer your own questions. It would be great if you would do that, and propose needed changes.

Consider setting `endAngle = Math.PI / 2;` in your fiddle.

Consider setting the sphere color to correspond to the order the point is rendered.

Have a look at https://github.com/mrdoob/three.js/issues/5641.

**Comment by rfm1201** [comment]
I have updated my fiddle but, as I wasn't logged when I created it, the URL change with the update. The new one is [https://jsfiddle.net/wdsmy9k3/1/](https://jsfiddle.net/wdsmy9k3/1/).
The starting and ending angle can be set to any value between 0 and 360°.
The color of the sphere change with their order.

I look at [#5641](https://github.com/mrdoob/three.js/issues/5641) and you are right it's the same thing, but it doesn't give me any clue on the way ellipse should be processed in a path.

If I change the code the way I want, I'm going to use a pure geometrical interpretation of the ellipse parameters. I wil go from the point defined by aStartAngle to the point defined by aEndAngle walking on the ellipse as defined by aClockwise. The result will work the way getSpacedPoints does, but with the last point of the ellipse as ending point of the path.

My problem is that I never worked with graphical software, so I don't know if there is a usual way to process ellipse that could be different from the geometrical interpretation.

**Comment by WestLangley** [comment]
@rfm1201 Don't worry. The conventions were established by the original author @zz85. I expect common sense prevails. If you find too many cases that seem incorrect, then that would be a sign that you have different conceptions about what is correct.

I really like your fiddle testbed. Be sure to call `dispose()` properly. Type `renderer.info` into the console.

**Comment by rfm1201** [comment]
I have updated my [fiddle](https://jsfiddle.net/wdsmy9k3/2/) (so its URL change), it now diposes meshes (it was clearly a bug not to do it).
I started modifying the ellipse code but it's not done.

**Comment by rfm1201** [comment]
I have new version of ellipseCurve.getPoint and Path.getPoints (only the ellipse case is updated). For me it works as expected so I might pull my changes, but while testing the ellipse in path with other elements two things seems weird to me.

The first one is at the end of Path.getPoints function code (Path.js line 423 of the current dev). It’s something commented as "Normalize to remove the closing point by default".
The last point of the path calculated so far is removed if it is too close (Number.EPSILON used for the test) to the first point of the path.
The problem is that it is really hard to understand why the last point is removed "sometimes". I say sometimes, because it happens in my test only once, and all my tests try to close the path without the help of autoClose. But only once was I too close of the first point, so the last point of my path was removed.
If removing the last point when too close of the first is required for some reason, I think the doc should say that a closed path can be only build with autoClose at true.
Of course getSpacedPoints never removes the last point.

The second appears when you add a point before the ellipse with a moveTo. So it’s visible in my fiddle from the start.
With getPoints this first point is in the path. With getSpacedPoints it is not. Why?
Because with getSpacedPoints the geometrical lenth of all the elements of the path is calculated, and a moveTo as no length. No length means "doesn’t exist" for getSpacedPoints. For getPoints, it’s a point, so it exists.
Adding a lineTo to the first point of the ellipse is required for getSpacedPoints to have a length to consider in its calculation.
I think Path.absellipse should automatically add a lineTo when a previous point is defined in the path. It’s more the way the other methods do. For exemple, splineThru uses the previous point.
If you want a pure ellipse, simple, don't add anything before.

I will keep testing tomorrow morning (I'm in France) and if things seems ok to me, I will push. If you want me to change something related to the 2 points I described, tell me. If you want separate pull, tell it too.

**Comment by mrdoob** [comment]
> The last point of the path calculated so far is removed if it is too close (Number.EPSILON used for the test) to the first point of the path.

Hmm, that's not good. Shouldn't we be setting that explicitly?

**Comment by zz85** [comment]
Thanks @WestLangley for pinging me and @rfm1201 for reporting this. I'll try to see what's wrong with this..

**Comment by zz85** [comment]
I've just verified that there's something wonky in `Path`. I've made a simpler test case to understand what's happening. https://jsfiddle.net/do6tu50o/1/

What I can see for now is getSpacedPoints uses `.curves` while getPoints() uses `.actions`.

 1. Path isn't that robust right now. If you do a `path.moveTo(x, y)` followed by a ellipse, there is a missing line in `.curves` (and therefore missing points), so for now you may need to manually do a `path.lineTo()` if you wish to ensure that the path stays connected and for getSpacedPoints to return more accurately.

2. getPoints() is currently slightly more verbose, except for the arc clockwise/anticlockwise behaviour. I see you've some somewhat looked into at #8952. I'll try to go into that next.

**Comment by killroy42** [comment]
I just moved from r78 to r79dev, and my absellipse that I use with my extrusion code completely disappeared. It has vertices, but the mesh no longer renders with a line material, and my extrusion code cannot see it. I will investigate to see what has changed. @zz85

**Comment by Mugen87** [comment]
It seems #9079 did address this issue.
