### ISSUE TITLE
Raycaster doesn't catch intersections correctly, r73+

### ISSUE THREAD

**Issue by dxshindeo** [mrdoob/three.js#8898]
Hi,
r72: https://www.dropbox.com/s/b01ypg5gugfrgd7/r72.wmv?dl=0
r76: https://www.dropbox.com/s/mnhxtkdrvdcqb9z/r76.wmv?dl=0

in r72 video you can see a player and 7 rays totally. All of those rays represent raycasters. All intersections are cought correctly (altough I'm still unsure why at 00:50s the y_negative rays intersection is not being caught, perhaps it's something to do with the walls thickness, y_negative does show intersections when colliding with floor ). But this is in r72, it's working as it should.

**Problem**: In r73+, intersections that have their origin point **behind** the wall are not being caught (origin point is the one from which all 7 rays come out).

My hunch is that it has to do something with core raycasters code interacting with _doubleSided_ property of the whole map mesh (walls and floors is one giant mesh). If I remove that property from map.json, the r72 test will act the same way as r73+ does - not catching all intersections.

Using production builds, seen on firefox and chrome on windows, I recon its the same everywhere else.

**Comment by mrdoob** [comment]
I'm having a hard time to understand what's going on on these videos. Could you create a simpler reproduction in a jsfiddle?

**Comment by mrdumb** [comment]
Another severe issue: the raycaster doesn't work at all for meshes with multiple materials.

**Comment by dxshindeo** [comment]
Ok, I hope this is more viewable: https://jsfiddle.net/dfLd8a8r/3/
I am drawing raycast along the z_positive axis (blue). It's logical in this case for collision not to happen, because looking from origin point we see no plane, I get that. If we uncomment `side: THREE.DoubleSide,` we can see in console.log that our plane has a collision.

But here's the thing - if we have a json mesh instead of a Three plane and mesh has a property `"doubleSided":true` , even then the collision is not caught, as seen in my videos as well. This happens on r73+.
I have also placed myself behind the wall to check if I can actually still see it, and yes I can, the doubleSided property does work, visually at least.

**Comment by mrdoob** [comment]
Ah, I see... Yeah, `Raycaster` no longer supports `material.side`...

**Comment by WestLangley** [comment]
>Raycaster no longer supports material.side...

I think, it does, actually. And the fiddle looks OK to me, too.

>But here's the thing - if we have a json mesh instead of a Three plane and mesh has a property "doubleSided":true , even then the collision is not caught,

@dxshindeo Can you provide a fiddle to demonstrate that?

Unrelated: As Remus pointed out, it may be true that `Raycaster` does not correctly handle `MultiMaterial` objects.

**Comment by dxshindeo** [comment]
Ok, this is shedding more light.
r72, collision found: https://jsfiddle.net/Starwave/zxcq0fju/5/ 
r76: collision not found: https://jsfiddle.net/Starwave/ptrLztv4/1/

I commented out a Three.plane and added json plane, it has "doubleSided":true in it. It's worth mentioning, that it's a skinned mesh.

**Comment by WestLangley** [comment]
Your r76 fiddle is using `MultiMaterial`.

[This commit](https://github.com/mrdoob/three.js/commit/2e128d82668a02b5f39b53bb8d1f4198a40ac07c) may have broken `Mesh.raycast()` with `MultiMaterial`.

I do not know what the status is on `SkinnedMesh` and raycasting.

**Comment by dxshindeo** [comment]
Why do you think its `MultiMaterial` ?
In json's `materials` array only one material object is defined.

**Comment by WestLangley** [comment]
Because that is what is coded in the fiddle you wrote.

    var mesh = new THREE.SkinnedMesh( geometry, new THREE.MeshFaceMaterial( materials ) );

and

    THREE.MeshFaceMaterial = THREE.MultiMaterial;

**Comment by dxshindeo** [comment]
Thank you for clarifying.

**Comment by titansoftime** [comment]
Has this been resolved? I am experiencing this in 83dev.

**Comment by mrdoob** [comment]
@titansoftime can you provide an example?

**Comment by titansoftime** [comment]
In the process of making the example I have discovered that... and maybe this was obvious but..

 ```
var mat1 = new THREE.MeshBasicMaterial({color:0x00ff00,side:THREE.DoubleSide}); // side affects render

var mat2 = new THREE.MeshBasicMaterial({color:0xff0000,side:THREE.DoubleSide}); // side affects render
    
var mat = new THREE.MeshFaceMaterial([mat1,mat2]);
mat.side = THREE.DoubleSide; // affects intersection, has no effect on render.  this was missing.
```

Good to go.
