### ISSUE TITLE
Normalmapping for errourneous UV coordinates

### ISSUE THREAD

**Issue by throni3git** [mrdoob/three.js#8901]
##### Description of the problem 

Hello,

i've got customer models of furniture objects that are buggy in their uv coordinates. This is of course less an issue of threejs, more an issue of the models. Anyway, i'd like to check out if there is a way to handle it with the shader. The Material is MeshPhongMaterial and the problem occurs only **if a normalmap is activated and the uv coordinates don't represent triangles** but lines.

The code responsible for the normalmapping is found in perturbNormal2Arb. I think the problem might be the dFdy/dFdy of vUv, where the errourneous uv coodrinates deliver vec2(0, 0). However, if i add 

st0.xy += 0.0000001;

the artifacts are gone.

I don't know if it really is an issue of threejs, but maybe it is a solution for others to come...

```
#ifdef USE_NORMALMAP
	uniform sampler2D normalMap;
	uniform vec2 normalScale;
	vec3 perturbNormal2Arb( vec3 eye_pos, vec3 surf_norm ) {
		vec3 q0 = dFdx( eye_pos.xyz );
		vec3 q1 = dFdy( eye_pos.xyz );
		vec2 st0 = dFdx( vUv.st );
		vec2 st1 = dFdy( vUv.st );
		vec3 S = normalize( q0 * st1.t - q1 * st0.t );
		vec3 T = normalize( -q0 * st1.s + q1 * st0.s );
		vec3 N = normalize( surf_norm );
		vec3 mapN = texture2D( normalMap, vUv ).xyz * 2.0 - 1.0;
		mapN.xy = normalScale * mapN.xy;
		mat3 tsn = mat3( S, T, N );
		return normalize( tsn * mapN );
	}
#endif
```

![uv_fail](https://cloud.githubusercontent.com/assets/14586717/15322862/66b40b14-1c3f-11e6-8b3b-e9e9f005ce44.png)

##### Three.js version
- [ ] r75

##### Browser
- [x] Chrome
- [x] Firefox

##### OS
- [x] Windows

**Comment by mrdoob** [comment]
Maybe @tschw knows something about this.

**Comment by tschw** [comment]
More of a stackoverflow question, actually:

The tangential space is derived at run time from the UV map. When there is a zero gradient (one value is always the same), the resulting space collapses into singularity. If you can't use a proper UV map, you can use a custom shader that only considers `.s` ("U") or `.t` ("V") which then results in missing `S` or `T` in the above code. You can set it to an axis orthogonal to the other and `N` using a normalized cross product.
