### ISSUE TITLE
Variable name typos in r76 AnimationMixer

### ISSUE THREAD

**Issue by TheManWhoWas** [mrdoob/three.js#8902]
##### Description of the problem 

AnimationMixer has a couple of variable name typos:

Line 705 & 763: this.pause should be this.pause**d**

Line 746: this.loopCount should be this.**_**loopCount

But appears it has all changed in dev so only applies to r76
...

##### Three.js version

- [ ] Dev
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Fixed in `dev` 😊
