### ISSUE TITLE
OrbitControls - Expose pan, dolly and rotate functions

### ISSUE THREAD

**Issue by carlosanunes** [mrdoob/three.js#8906]
##### Description of the problem

OrbitControls can only be used through dom events. That is, the only way to programmatically call the the pan, dolly and rotate functions of OrbitControls would be to fire the DOM events through code.

I suggest that these pan, dolly and rotate functions should be exposed.

Just wanted to start discussion on the need and/or desirability of this change. I am probably able to implement the change myself.
##### Three.js version
- [x] Dev
- [x] r76
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
You are suggesting exposing the following?

```javascript
this.rotateLeft()
this.rotateUp()
this.pan()
this.dollyIn()
this.dollyOut()
````

You have to be careful, as an animation loop is not required with `OrbitControls`, so programmatically calling these methods may require that `controls.update()` be manually called, too. You would also have to test the behavior if `enableDamping` is `true`.

In principle, I would not have a problem with the change proposed here.

**Comment by carlosanunes** [comment]
Yes, exactly.

My intent is allowing the use of OrbitControls outside of DOM events.

**Comment by WestLangley** [comment]
If this change turns out to be problematic for some reason, it is trivial for you to add the feature to your own copy, as noted above.

**Comment by carlosanunes** [comment]
Yes, but if the 'feature' is included in the upstream it is more value for me (less worry in future releases) and more value for others that might have use for it. :)

**Comment by JanWaller** [comment]
Any progress on this PR?
I would actually prefer if the public methods would provide parameters (for dolly amount), too...

**Comment by Mugen87** [comment]
Closing. See discussion in #9005
