### ISSUE TITLE
Lightning issues with buffergeometry

### ISSUE THREAD

**Issue by Lallassu** [mrdoob/three.js#8922]
##### Description of the problem 
I'm drawing buffer geometries with Lambert material but the lightning is not reflected until I rebuild the geometries more than once.

    // build geometry (add position attr) and add colors to it (color attr)
    geometry.computeVertexNormals();
    this.mesh = new THREE.Mesh( geometry, new THREE.MeshLambertMaterial({vertexColors: THREE.VertexColors, wireframe: this.wireframe})); // this.wireframe is toggled with the button on page
    this.mesh.receiveShadow = true;
    this.mesh.castShadow = true;
    game.scene.add( this.mesh );

I'm using ambient, hemisphere and directional-lights. The "missile" in the demo below is using a spotlight.

When adding the meshes to the world they don't reflect lights. But when I rebuild them with wireframe = true and then back to wireframe = false again they start to reflect lightning.

Example here: http://qake.se/demo 
(press 1, shoot (mouse1), then click "wireframe" button two times so it goes back to normal and shoot again, this time the lights works as expected). The source is obfuscated so nothing to see there. But I can hand over any code that might be of interest for this issue.

The same code is executed both times.

Not sure if this is a bug with lightning and buffergeometries since I haven't had this issue with using regular geometries before.

##### Three.js version

- [ ] Dev
- [x] r76
- [x] earlier versions as well.

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Tested on OSX 10.11.3 on Macbook Pro i7 (2x3GHz), 16GB RAM, Intel Iris 1536MB

**Comment by makc** [comment]
> when I rebuild them with wireframe = true and then back to wireframe = false again they start to reflect lightning

and then
> The source is obfuscated so nothing to see there

how can anyone be sure it is not just another bug of your own? I mean...

![screen shot 2016-05-20 at 20 37 38](https://cloud.githubusercontent.com/assets/242577/15438126/efa65a8e-1eca-11e6-81b1-3ea9783708f2.png)
