### ISSUE TITLE
fbx import from rhinoceros 4.0 not working

### ISSUE THREAD

**Issue by ThomasPahler** [mrdoob/three.js#8929]
##### Description of the problem

fbx files created with rhinoceros (4.0) cant be imported;

```
Error:
TypeError: objects is undefined
Bones.prototype.parseHierarchy()
 FBXLoader.js:1295
THREE.FBXLoader.prototype.parse()
 FBXLoader.js:120
Loader/this.loadFile/<()
 Loader.js:149
FBXLoader.js:1295:7
```

i'll provide an example file if it helps
##### Three.js version
- [ ] Dev
- [x] r76
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Yes. It's still very early days for the FBXLoader...

There are more chances for this to get fixed if you share the file you're trying to load though. Hopefully @amahigashi could then take a look.

**Comment by looeee** [comment]
@ThomasPahler is this still an issue? Can you provide an example file so that we can test? 

If not then this should be closed.

**Comment by mrdoob** [comment]
Closing it for now. We can open it again if needed.
