### ISSUE TITLE
How to play reverse animation with negative timeScale with r76

### ISSUE THREAD

**Issue by easyfrog** [mrdoob/three.js#8931]
##### Description of the problem 
In r72 verstion I can play reverse animation with negative timeScale, is very helpful to me,
But now I update to r76 it not work. So how can I play reverse animation in r76? Thanks.

##### Three.js version

- [ ] r76

##### Browser

- [ ] Chrome

##### OS

- [ ] Windows

**Comment by tschw** [comment]
?! Works in [`webgl_animation_skinning_morph`](http://threejs.org/examples/#webgl_animation_skinning_morph)...

**Comment by jnordberg** [comment]
Seems negative timescales seems not to work when the loop mode is LoopOnce, can be demonstrated in the demo linked by @tschw

**Comment by arturitu** [comment]
I used setLoop(THREE.LoopRepeat, 1); to deal with it.

**Comment by rtpHarry** [comment]
To people of the future landing here like I did: I found a way to do this!

https://gist.github.com/rtpHarry/2d41811d04825935039dfc075116d0ad

**Comment by Cobertos** [comment]
In my case, I just needed to set  `.paused = false; ` after it's bound with `clipAction()`
