### ISSUE TITLE
Question about MarchingCubes demo

### ISSUE THREAD

**Issue by tiborsaas** [mrdoob/three.js#8937]
Hello,

I have a question about the [MarchingCubes demo](http://threejs.org/examples/#webgl_marchingcubes). It works great with balls, but what should I do to add other shapes like a cube or a more complex shape? 

[In the source](http://threejs.org/examples/js/MarchingCubes.js) I see three plane creation methods which got me thinking that it might not that hard to add other shapes. Is it similar to drawing with distance field functions?

Sorry if my question is dumb, I'm trying to make sense of it. :)

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/.github/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

**Comment by tiborsaas** [comment]
Sorry I missed that page.
