### ISSUE TITLE
TransformControls mobile/tablet Clicking detection

### ISSUE THREAD

**Issue by rhairston** [mrdoob/three.js#8955]
##### Description of the problem 

Screen touches do not read end of touch correctly for TransformControls (Axes, planes, and orbits stay selected until another part of the screen is touched)

This can cause errors when you include OrbitalControls and forget to tap off the screen to 'unclick' the controls.

I added a function to detect mobile devices locally which works, but it would seem like this idea should be done for all versions.

##### Three.js version

- [ ] Dev
- [x] r77
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [x] IOS

##### Hardware Requirements 
All mobile and tablet devices

**Comment by rhairston** [comment]
I switched back to orbital controls and made my own gizmo in a separate renderer then linked their camera positions.

**Comment by mrdoob** [comment]
Fixed 938d587dd141a3585324848fa15d4d4e9b62773e.
