### ISSUE TITLE
Cannot configure touch event behavior of OrbitControls

### ISSUE THREAD

**Issue by russplaysguitar** [mrdoob/three.js#8956]
##### Description of the problem 

I want to pan on single-touch (instead of rotate), but the behavior is hard-coded into OrbitControls (see: `onTouchMove()` https://github.com/mrdoob/three.js/blob/69079243426506ed86d0d0ea71b4fdda9dbb2f88/examples/js/controls/OrbitControls.js#L829).

##### Three.js version

- [x] Dev
- [ ] r77
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
The files in the example folder are meant to be used as reference. You can change the code of the file so it suits your needs.

**Comment by russplaysguitar** [comment]
The problem with customizing the examples is that it makes it harder to pull in upstream changes. If you don't want issues with examples cluttering-up the list of three.js issues, it might makes sense to split them into a separate repository or maybe just use a label?
