### ISSUE TITLE
Bug w/ editor: THREE.VRControls is not a constructor

### ISSUE THREAD

**Issue by babakness** [mrdoob/three.js#8957]
##### Description of the problem 

Using the EDITOR and choosing VR from the PROJECT SETTINGS page doesn't work because the packaged ThreeJS file seems to be missing the related constructor:

THREE.VRControls is not a constructor

##### Three.js version

Download published file using editor

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

Any

---

**Comment by kbjz** [comment]
Same issue , did you find a solution ?

**Comment by Mugen87** [comment]
The `VRControls` are not part of the three.js bundle. The file is separately included in `/editor/index.html` see [here](https://github.com/mrdoob/three.js/blob/master/editor/index.html#L84).

@babakness @kbjz Can you check the index.html page of the editor on your local PC and look for the mentioned include?

I don't get the mentioned error message. Neither on the [three.js](threejs.org/editor/) homepage, nor when i open the editor from my local repository.

**Comment by kbjz** [comment]
Problem solved ,  Thank you !

*Kévin Bernajuzan*
*Ingésup Y-nov Paris*
*Développeur applications mobiles - **EWO*

2016-05-25 11:27 GMT+02:00 Michael Herzog <notifications@github.com>:

**Comment by Mugen87** [comment]
I've misunderstood this problem. Manually including the missing files in the index.html is just a workaround. A real fix can only provide a PR.

**Comment by Mugen87** [comment]
f8e0e542d4fd05fffb534bb26b086ae5eb7f136c solved the problem. This issue can be closed...

**Comment by babakness** [comment]
Right on. Yeah I got it working too, I just thought it should Just Work™ when you export.

**Comment by babakness** [comment]
Thanks.
