### ISSUE TITLE
Syntax Errors on Line 388 and line 2066

### ISSUE THREAD

**Issue by pandakub** [mrdoob/three.js#8958]
Edit: (I am referring to convert_to_threejs.py)

##### Description of the problem 

String syntax errors on line 388 and line 2066.

**Line 388:**
print "Unknown type of Material", getMaterialName(material)
**Should be:**
print ("Unknown type of Material"), getMaterialName(material)

**Line 2066:**
print "I/O error({0}): {1} {2}".format(e.errno, e.strerror, url)
**Should be:**
print ("I/O error({0}): {1} {2}").format(e.errno, e.strerror, url)

##### Three.js version

- [ ] Dev
- [x] r77
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
What file are you talking about?

**Comment by Mugen87** [comment]
I think the issue refers to these two lines in `utils/converters/fbx/convert_to_threejs.py`

[Line 388](https://github.com/mrdoob/three.js/blob/master/utils/converters/fbx/convert_to_threejs.py#L388)
[Line 2066](https://github.com/mrdoob/three.js/blob/master/utils/converters/fbx/convert_to_threejs.py#L2066)

**Comment by pandakub** [comment]
Yes, sorry, forgot to specifically mention that I was talking about convert_to_threejs.py, my bad!

**Comment by mrdoob** [comment]
@pandakub would you like to do a Pull Request with the fix?

**Comment by pandakub** [comment]
done! :)

**Comment by mrdoob** [comment]
@pandakub Thanks!
