### ISSUE TITLE
this.updateMorphTargets is not a function

### ISSUE THREAD

**Issue by yqrashawn** [mrdoob/three.js#8967]
##### Description of the problem 

(This is NOT a help site. Please read the guidelines above before posting.)
```
    var ThreeJSObject = function(x, y, z, udp, img) {
            var texture, material, geometry, geom;

            texture = THREE.ImageUtils.loadTexture(img);
        
            material = new THREE.MeshBasicMaterial({
                map: texture
            });

            geometry = new THREE.PlaneBufferGeometry(8, 8);

            THREE.Mesh.call(this, geometry, material);

            this.prototype.foo = ...
            ...
}
```
I try to use `THREE.MESH.call(this,geometry,material)` to creat a object in my viewer, and chrome gives me this.

> this.updateMorphTargets is not a function  

##### Three.js version

- [ ] Dev
- [x] r71
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by makc** [comment]
because [it is on Mesh prototype](https://github.com/mrdoob/three.js/blob/master/src/objects/Mesh.js#L33)?

**Comment by makc** [comment]
see [here](https://github.com/mrdoob/three.js/blob/master/src/objects/SkinnedMesh.js#L69) for how-to

**Comment by yqrashawn** [comment]
@makc Thx!
