### ISSUE TITLE
Safari error when using the glTF loader.

### ISSUE THREAD

**Issue by xirvr** [mrdoob/three.js#8973]
##### Description of the problem 
- Error in Safari when using the glTF loader for models built with Cinema4D.  
- See example at: https://github.com/xirvr/threejs-scaffold/tree/master/www
<img width="985" alt="screen shot 2016-05-23 at 4 12 48 pm" src="https://cloud.githubusercontent.com/assets/10131838/15487341/64cacb32-2101-11e6-9895-572031140b10.png">
<img width="679" alt="screen shot 2016-05-23 at 4 13 17 pm" src="https://cloud.githubusercontent.com/assets/10131838/15487340/64ca7d12-2101-11e6-8286-f8d3cc1f4b1a.png">

##### Three.js version

- [x] Dev
- [x ] r77
- [ ] ...

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari (Desktop)
- [x] Safari (iOS)

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [x] OS X
- [x] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
- AMD Radeon R9 M370X 2048 MB (MacBook Pro), iPhone 6 Plus, iPad Air 2.

**Comment by tparisi** [comment]
@xirvr where is the non A-frame test case? thx

**Comment by xirvr** [comment]
@tparisi https://github.com/xirvr/threejs-scaffold/tree/master/www

**Comment by tparisi** [comment]
Ah thanks - got it. I'll have a look

**Comment by xirvr** [comment]
With the (much appreciated!) help from @wizgrav I stripped down / simplified the shader examples to rule these out as a contributing factor.  With these, the demo is flat green in Chrome (as expected), and same error in Safari.

attribute vec3 a_position;
uniform mat4 u_modelViewMatrix;
uniform mat4 u_projectionMatrix;
void main(void) {
  vec4 pos = u_modelViewMatrix * vec4(a_position,1.0);
  gl_Position = u_projectionMatrix * pos;
}

void main(void) {
  gl_FragColor = vec4(0., 1., 0., 0.5);
}

**Comment by tparisi** [comment]
Great that is going to be super helpful... I'm slammed with day job stuff today will try to get to it though

**Comment by xirvr** [comment]
I also did a diff on desktop.gltf and a couple of the demo glTF files, as far as I can see the types are the same (SCALAR, VEC2, VEC3, VEC4, and in shaders 65632, 35633, 35666, 35676, 5126... several of these but they, I think correspond to material properties such as shininess, specular, position, normal, diffuse, etc).  

If in this process I can wrap my head around how all this works, would like to try and add the ability for the loader to parse these property types -- the more that can be done in Cinema / Maya / etc instead of the application, the better.

**Comment by xirvr** [comment]
@tparisi did you ever get a chance to take a look at this?  Or any ideas what I could look for?

**Comment by tparisi** [comment]
Just looked, this seems like a crazy Safari JS bug. If you inspect the WebGLRenderingContext object, it doesn't have any constants. ! e.g. `WebGLRenderingContext.FLOAT` is undefined in the console. If you look at the initialization code, it does the following to map the integers to their constant names:

    `for (n in WebGLRenderingContext) { z = WebGLRenderingContext[n]; this.idx[z] = n; }`

where n is the name and z is the value; after that initialization statement is run in Safari, the `idx` array is nearly empty and doesn't have any of those constant names in there.

So I guess this is a serious Safari issue... not sure how to fix this without fixing what I would guess is a Safari bug OR manually defining our own versions of those constants, which I don't want to do. Someone clever could write a loop to go through this in Chrome or FF and dump the names into a new array, then copy that into some new JS code... but then if those constants ever change that would suck. They probably never would, but... In any case, maybe use that hacked array for Safari only.

I don't have time to do this now but I think that's the ticket, so go for it.

**Comment by xirvr** [comment]
@tparisi Thanks for looking into it, I know this kind of bug is super annoying :)  I fully confess I don't know enough about OpenGL (yet) to be as helpful as I'd like to be, but trying to push through.

I was looking at it with fresh eyes yesterday and was on a similar path, but I was thinking maybe not all of the constants were implemented in the loader?  Otherwise, if Safari was missing part of the actual WebGL spec, wouldn't it break often/severely in a lot of other ways (I'm not asking rhetorically, trying to understand :)

A few guesses I had:

Cinema4D outputs a Collada that has extra/doesn't have expected properties that the Collada to glTF converter isn't expecting, and it's trying handle them gracefully (see below, shininess and specular are missing semantic properties -- and maybe Chrome/Firefox pass over these, but Safari requires them, and those properties would need semantics added or to be removed (I tried this path but got stuck on a data type error down the debug chain).

Or

The Collada to glTF converter isn't writing all of the types / semantics for the Collada that Cinema4D outputs.  I've tried Maya as well, but not extensively by any means because it seemed to have the same results (it's something to test further, though).  Fix would be to get into the converter and add the rest of the types from:

https://github.com/KhronosGroup/glTF/blob/master/specification/README.md#techniques

which are missing from Safari.

Or

Some of the constant strings don't map to types properly on Safari, though I would still think that would mean Safari isn't WebGL compliant -- but if this is true, then hacking a if Safari,  if TEXCOORD_0 use TEXCOORD instead (psuedo).  I think this is what you are suggesting, though I thought the fix would be adding the missing types / semantics to the loader:

Using (same as solving it in the converter, maybe):

https://github.com/KhronosGroup/glTF/blob/master/specification/README.md#techniques

to add more parameter types to 

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/gltf/glTFLoader.js#L820

For reference:
``
    "techniques": {
        "technique1": {
            "attributes": {
                "a_normal": "normal",
                "a_position": "position",
                "a_texcoord0": "texcoord0"
            },
            "parameters": {
                "diffuse": {
                    "type": 35678
                },
                "modelViewMatrix": {
                    "semantic": "MODELVIEW",
                    "type": 35676
                },
                "normal": {
                    "semantic": "NORMAL",
                    "type": 35665
                },
                "normalMatrix": {
                    "semantic": "MODELVIEWINVERSETRANSPOSE",
                    "type": 35675
                },
                "position": {
                    "semantic": "POSITION",
                    "type": 35665
                },
                "projectionMatrix": {
                    "semantic": "PROJECTION",
                    "type": 35676
                },
                "shininess": { // No semantic -- problem?
                    "type": 5126
                },
                "specular": { // No semantic
                    "type": 35666
                },
                "texcoord0": {
                    "semantic": "TEXCOORD_0",
                    "type": 35664
                }
            },
            "program": "program_0",
            "states": {
                "enable": [
                    2929,
                    2884
                ]
            },
            "uniforms": {
                "u_diffuse": "diffuse",
                "u_modelViewMatrix": "modelViewMatrix",
                "u_normalMatrix": "normalMatrix",
                "u_projectionMatrix": "projectionMatrix",
                "u_shininess": "shininess",
                "u_specular": "specular"
            }
        }
    }
``

PS -- @mrdoob I would think this issue would come up in the loader you're writing as well, so if there's anyone you know that might be interested in solving this, some more help would be awesome :)  And if we can really pinpoint that it's for sure a Safari bug, I'm happy to find the means to complain to them -- gotta find a way to get this working one way or another.

**Comment by tparisi** [comment]
It's a safari and WebKit bug I would bet anything

**Comment by richtr** [comment]
I've created a PR that fixes this issue @ https://github.com/mrdoob/three.js/pull/9721.

**Comment by tparisi** [comment]
@richtr thanks - instead of always hard-coding can you do it conditionally based on whether or not the enum is there? something like the following (which won't work for the zero value but zero is zero....

` FLOAT: WebGLRenderingContext.FLOAT ? WebGLRenderingContext.FLOAT : 5126,`

**Comment by richtr** [comment]
We can do this @tparisi but I don't expect the constant values will ever change. Should we go ahead and add this anyway?

**Comment by tparisi** [comment]
Either that, or perhaps put in a comment to this effect, with that link to the header file... ? I just want to make sure someone coming along later knows what these values are based on. I agree that the likelihood of these constants changing in the future is next to nil. So I'll leave this up to you!

**Comment by xirvr** [comment]
I've thrown several test models from Cinema4D and everything seems to be working the same in Safari as it does in Chrome and Firefox now.

**Comment by richtr** [comment]
I've added a link to the URL defining the constants here: https://github.com/mrdoob/three.js/pull/9721/files#diff-80c498563410078e90e7281b9601bdc0R13. Of course, happy to change how we do this but I think this should be sufficient.

**Comment by tparisi** [comment]
nice @mrdoob this PR Is good to go! Please merge.
