### ISSUE TITLE
Repo Seems a bit large

### ISSUE THREAD

**Issue by jmunsch** [mrdoob/three.js#8977]
##### The repository is gigantic

Just to do even a sparse checkout, the download size of the commit history / tree is something like 148MB? 

```
bob@bobsan:~/Desktop/threejs$ git init
Initialized empty Git repository in /home/bob/Desktop/threejs/.git/
bob@bobsan:~/Desktop/threejs$ git remote add -f origin https://github.com/mrdoob/three.js
Updating origin
remote: Counting objects: 117511, done.
remote: Compressing objects: 100% (38/38), done.
^Cceiving objects:  14% (17072/117511), 20.78 MiB | 1.63 MiB/s     
```

The entire repository is 583MB?

```
bob@bobsan:~/Desktop$ curl https://api.github.com/repos/mrdoob/three.js
{
  "id": 576201,
  "name": "three.js",
  "size": 583648,
  "stargazers_count": 25196,
  "watchers_count": 25196,
  "default_branch": "master",
  "network_count": 8384,
  "subscribers_count": 1671
}
```

Is it possible to reduce the size of this repo at all? It's pretty much a non-critical issue, but it seems pretty far out that a javascript library would be half a gig just to get the source to build it out.

##### Three.js version

- [ ] Dev
- [x] Master

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

An internet connection with a fast connection, and unlimited bandwidth.

**Comment by makc** [comment]
they do not care #6922

**Comment by makc** [comment]
btw if you create package.json like this
```javascript
{
  "name": "whatever",
  "version": "1.0.0",
  "dependencies": {
    "three": "0.76.1"
  }
}
```
and run `npm install` you will get 11.6 MB copy of the repository with prebuilt 3js, examples js (probably for things like canvas renderer and orbit controls) and, surprisingly, source files. now if @bhouston could explain how to build from that.....

**Comment by bhouston** [comment]
The reason the project is so big is the example files.  The core project is pretty efficient.

> now if @bhouston could explain how to build from that.....

NPM packages are a packaging format for using one project in another, but not developing the project in the NPM package itself.  Thus if you are just using ThreeJS, NPM is a great choice.  But if you want to contribute to ThreeJS or modify it, you need to check out its git repository.

**Comment by jmunsch** [comment]
Thanks for the link to the previous thread. And the responses.

I see. Closing this issue.
