### ISSUE TITLE
Shallow clone of userData

### ISSUE THREAD

**Issue by SuberFu** [mrdoob/three.js#8982]
Currently, userData is essentially a deep clone copy. 
Is it Ok for me to add another field like "referenceData" that is copied by a shallow copy (just assign referenceData's object directly)?
Pull Request #8981 

I currently have a use case like this.
1. I have several large, complex javascript objects.
2. Each of the object generates a set of overlays in the 3D scene.
3. Those overlays may need to have their visibility and colors changed depending on the object that create them.

Currently, the following two strategies will break if the overlay (an Object3D) is ever cloned or copied.
1. Store reference back to the source object. On update (during render), walk the tree and check if the overlay themselves need to change. If overlay is cloned or copied, the reference back to the original source object is broken, and changes to source object can't be seen by overlay (in addition to incurring a memory cost of having a clone of a large javascript object).
2. Store reference to the overlay in the source object. On update, iterate through each source object's overlay and update them. Again, the issue arise when overlay objects are cloned, and the source object no longer "see" the cloned object.

Currently I use the following work around.
1. Whenever the complex object is created, it adds itself to a dictionary with a unique key (simple string).
2. When said object creates an overlay, add that unique key to the userData.
3. Every time I traverse the scene graph, grab the unique key in the userData, look it up in the dictionary, grab the object, and check if I need to update the overlay.

The above workaround contains the following issues.
1. The dictionary must always be "reference-able" by the logic walking the scene graph. The logic may be moved, or new logic may be created, in the future that would then require passing the dictionary + scene around.
2. Need to maintain a system of generating a unique id for the dictionary to prevent conflicts.
3. Difficult to help garbage collection to determine if said object can be deleted once all the overlays it generated are destroyed.

As such, I propose in my pull request adding a new referenceData field that's always copied by reference. That would allow the object references to survive the copy operation and at least allow the "Update by Scene Traversal" function correctly.
##### Three.js version
- [X] Dev
- [X] r77
##### Browser
- [x] All of them
##### OS
- [x] All of them

**Comment by mrdoob** [comment]
I think this should go in the app layer. I'm not sure what the best way to extend should be though...
