### ISSUE TITLE
potential leak while disposing WebGLRenderer

### ISSUE THREAD

**Issue by olivierchatry** [mrdoob/three.js#8987]
##### Description of the problem

Hello,

My software is switch between two renderer (threejs / own SVG renderer ), removing the gl context while swapping renderer. While profiling for leaks, I noticed that two arrays in Three WebGLRenderer are not cleared when I call dispose on the context, namely opaquesObject and transparentsObject. 

https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L27

My workaround is to render an empty scene, so that they get cleared by the rendering, but it would be better if "dispose" actually clear them.

Hope I am clear enough, but if you need more information, do not hesitate
##### Three.js version
- [x] Dev
- [x] r77
- [ x] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Sounds good. Would you like to do a Pull Request?

**Comment by olivierchatry** [comment]
Sure !

**Comment by Mugen87** [comment]
This PR should solve the issue: #13122
