### ISSUE TITLE
THREE.SceneLoader problem

### ISSUE THREAD

**Issue by df257** [mrdoob/three.js#9000]
//export scene
var result=scene.toJSON();
localStorage.dfb=JSON.stringify(result);

//load scene
var json=JSON.parse(localStorage.dfb);
var loader=new THREE.SceneLoader();
loader.parse(json,function(e){
	scene=e.scene;
}, '.');

Uncaught TypeError: Cannot read property 'opacity' of undefined;
GET http://localhost/1three/undefined 404 (Not Found);

**Comment by mrdoob** [comment]
You should be using `THREE.ObjectLoader` instead.

**Comment by df257** [comment]
@mrdoob thanks, and I have somequestion, please help me
