### ISSUE TITLE
Unexpected pointlight behaviour with scaled-down camera

### ISSUE THREAD

**Issue by Chaky74** [mrdoob/three.js#9002]
##### Description of the problem 

If one adds (in my case) pointlights to the scene and set the distance property to some value other than zero, and then adds an object that is scaled down, and then adds camera to that object, the light's distance will be scaled down by camera's indirect scale.

##### Three.js version

- [ ] Dev
- [x] r77?
- [x] r76
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
Related: https://github.com/mrdoob/three.js/pull/7028

**Comment by Chaky74** [comment]
This should be documented, then.

**Comment by WestLangley** [comment]
@Chaky74 What happens if you set the camera's scale to counteract the scaling of the parent mesh?

    camera.scale.divideScalar( meshScale );

Does that solve the issue, or does it lead to a host of other problems? I expect that latter, unfortunately.

**Comment by Chaky74** [comment]
I haven't tried that, since it would affect the local space (creating camera motion, so the coordinates are all preset). I've countered it with dividing the distance value with camera scale value.

**Comment by WestLangley** [comment]
@Chaky74 OK. So the answer is that the camera should not be scaled. And that means its parents should not be, either.

Another thing you can consider is scaling the camera's parent's geometry, instead of the camera's parent.

    geometry.scale( s, s, s );

**Comment by Chaky74** [comment]
The point of scaling down camera was to scale down the animated moves it made in the local space. Anyway, point taken on geometry scale. Cheers.
