### ISSUE TITLE
Trackballcontrols not working on OS X trackpad (but fix inside)

### ISSUE THREAD

**Issue by izaid** [mrdoob/three.js#9003]
##### Description of the problem

So, I've been trying to use the Trackballcontrols from THREE.js on my OS X laptop with just the trackpad. In particular, I'm trying to get this working in the Jupyter notebook -- see http://jupyter.org.

While I've found that the Trackballcontrols work in general, in the Jupyter notebook they have an issue on the OS X trackpad (and under all browsers I tried). Basically, the simulation of middle-click and right-click using ctrl and command don't work. We can make this work quite easily by simply checking the flags `hasMeta`, `hasCtrl`, and `hasAlt` in the mousedown callback.

Can I make a PR for this? I'd rather fix this upstream than have to patch the code -- and it took me a while to figure out what was going on.
##### Three.js version
- [ ] Dev
- [x ] r77
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
- [x] OS X

**Comment by mrdoob** [comment]
> Can I make a PR for this?

Yes please!

**Comment by maciek134** [comment]
I see that the PR was never filed, is the issue still present (I don't have any OSX machines to test)?

**Comment by izaid** [comment]
Sorry about that. I definitely remember this issue, but I forgot to file the PR. I haven't used the particular combination of Jupyter, THREE, and OS X on a bit, but when I will I'll reopen if necessary.
