### ISSUE TITLE
Scene Import - Spotlights with incorrect direction

### ISSUE THREAD

**Issue by carlosanunes** [mrdoob/three.js#9006]
##### Description of the problem

Exported scenes from blender to collada and json. After importing, both from collada and/or json files the spotlights have incorrect directions.

Screenshots below for json test. The cone represents what the real direction of the spotlight should be (as defined in Blender).

<img width="533" alt="screen_shot_1" src="https://cloud.githubusercontent.com/assets/7937319/15578390/2ff1ee82-2358-11e6-96df-9f9074370ddb.png">
<img width="584" alt="screen_shot_2" src="https://cloud.githubusercontent.com/assets/7937319/15578391/2ffbc236-2358-11e6-84d9-f3105d6b3f20.png">
##### Three.js version
- [x] Dev
- [ ] r77
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Can you share a .blend file?

**Comment by carlosanunes** [comment]
Hi,

Sorry for the delay.

Made a new blender file with the same problem (I can't share the original .blend).


[spotlight_example.blend.zip](https://github.com/mrdoob/three.js/files/294204/spotlight_example.blend.zip)

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
