### ISSUE TITLE
r77 turned my camera sideways

### ISSUE THREAD

**Issue by AndrewRayCode** [mrdoob/three.js#9012]
##### Description of the problem

r75, r76:

![screen shot 2016-05-26 at 1 24 12 pm](https://cloud.githubusercontent.com/assets/79215/15588939/504d33b6-2345-11e6-9675-42468a72458b.png)

r77:

![screen shot 2016-05-26 at 1 23 49 pm](https://cloud.githubusercontent.com/assets/79215/15588942/530aae58-2345-11e6-9a85-13d8e9002a19.png)

The camera for this scene does not have a rotation explicitly set. Possibly related?

I looked through [the history of PerspectiveCamera.js](https://github.com/tschw/three.js/commits/7b832b91dcec5fc02a673b231238808eaad96c75/src/cameras/PerspectiveCamera.js) but couldn't find anything obvious.

There's no release notes for r77 so not sure what the culprit is. 
##### Three.js version
- ✅  Dev
- ✅  r77
##### Browser
- ✅  All of them
##### OS
- ✅  All of them

**Comment by mrdoob** [comment]
Are you doing a `lookAt()`?

**Comment by DelvarWorld** [comment]
Yes, I'm doing lookAt Vector3(0,0,0) - did something around that change?

**Comment by mrdoob** [comment]
I can only think of this @WestLangley change https://github.com/mrdoob/three.js/commit/6075b47257a2239bc4c9214d62c5124556832e71

**Comment by WestLangley** [comment]
I expect @mrdoob is correct.

@DelvarWorld Are you looking in the direction of the up-vector?

**Comment by AndrewRayCode** [comment]
@WestLangley My camera is at `0,1,0` and I'm looking at `0,0,0`. Is this the direction of the up-vector? 

I haven't modified `DefaultUp`.

Trying to rotate my camera but not having luck undoing this rotation.

**Comment by AndrewRayCode** [comment]
A workaround for me is to make a quaternion that specifically rotates the camera instead of using lookAt

```
export function lookAtVector( sourcePoint:Vector3, destPoint:Vector3 ):Quaternion {

    return new Quaternion().setFromRotationMatrix(
        new Matrix4().lookAt( sourcePoint, destPoint, Cardinality.UP )
    );

}
```

And setting camera quaternion instead of using lookat. This is all I need. If you don't think this is a bug I'm happy for this ticket to close.

**Comment by mrdoob** [comment]
Is not a bug...
For your use-case, instead of using `lookAt()` you should do `camera.rotation.x = - Math.PI / 2;`
