### ISSUE TITLE
Moving the mouse always fires a change event with TransformControls

### ISSUE THREAD

**Issue by DelvarWorld** [mrdoob/three.js#9015]
##### Description of the problem 

https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TransformControls.js#L1097

	function onPointerDown( event ) {
		...
		scope.dispatchEvent( changeEvent );
		scope.dispatchEvent( objectChangeEvent );

I don't think this is desired behavior? Simply moving the mouse around the scene, even without mousedown, triggers a change event on every frame. I looked into changing it briefly but there doesn't seem to be any straightforward code that says "I changed". Hopefully I can revisit.

Context: I'm creating an editor using Three, and having the onchange event fire even when nothing changes makes my code a bit trickier.

##### Three.js version

- ✅  Dev
- ✅  r77

**Comment by mrdoob** [comment]
What about this line?

https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TransformControls.js#L899

**Comment by DelvarWorld** [comment]
Ah I see, the controls in my scene were just very big, meaning anywhere I moved the mouse in my scene was a hover event. The issue is that moving the mouse when hovered over the transform controls (not engaged) fires the event:

https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TransformControls.js#L841

seems like that line should be removed?

**Comment by WestLangley** [comment]
@DelvarWorld `OrbitControls` and `TrackballControls` dispatch a `changeEvent` only from within the `reset()` and `update()` methods. Perhaps `TransformControls` could benefit from a similar code simplification. I haven't studied it though...
