### ISSUE TITLE
I use OBJLoader,  the object does not have the shadow

### ISSUE THREAD

**Issue by df257** [mrdoob/three.js#9017]
var mtlLoader = new THREE.MTLLoader();
mtlLoader.load( 'chahu.mtl', function( materials ) {	
	var objLoader = new THREE.OBJLoader();
	objLoader.setMaterials( materials );
	objLoader.load( 'chahu.obj', function ( object ) {
		object.castShadow=true;
                console.log(object);
		scene.add( object );
	});
});

While I console.log(object), in console, this object castShadow=true;

**Comment by BrianCraig** [comment]
Think of this. The object is making a shadow, to where ? its like a lamp or like a sun shadow ? 

The shadow needs a light. See the examples for usage, search shadow http://threejs.org/examples/

And this is not a QA site for THREEJS.

**Comment by df257** [comment]
@BrianCraig   I use JSONLoader to load a monster model, this monster model has shadow

**Comment by BrianCraig** [comment]
Yeah but, look this http://threejs.org/examples/#webgl_shadowmesh

**Comment by df257** [comment]
@BrianCraig  I use this:
