### ISSUE TITLE
question about animated 3d objects

### ISSUE THREAD

**Issue by johnhu84** [mrdoob/three.js#9020]
##### Description of the problem 

I'm trying to design a plugin that uses animated 3d objects like the horse object (horse.js) in the three.js examples, I would like to be able to create an animated 3d object like the horse object using 3d max, but the DAE and JS files I export do not have any morphTargets, there is animation data, but I don't know how to use three.js to handle that data.  Any help or ideas?

Thanks!

##### Three.js version

- [ ] Dev
- [ ] r77
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Those models were created with this script:
https://github.com/mrdoob/three.js/blob/master/utils/converters/obj/convert_obj_three.py

**Comment by johnhu84** [comment]
Hi Mr. Doob,

Can you tell me how you got those obj files, it looks like there's an obj file for the 3d object itself, and two for the morphs, were these files generated using 3D max, were there any plugins?  Also, can you tell me if using morphTarget animations is the best way to play an animation forwards and backwards?  If I have an animation file with no morph targets but just a bunch of time/position/rot/scale properties, is there currently an easy way to make that play forwards and backwards?

Thanks a lot!
-Chunlin
