### ISSUE TITLE
Reverse play animation

### ISSUE THREAD

**Issue by johnhu84** [mrdoob/three.js#9024]
##### Description of the problem 

Hi Mr. Doob,

I want to play an animation like the pump.dae backwards, is there any code out there that does this or do I have to write it myself, I believe I have to make modifications to the Animation.js, AnimationHandler.js, and the KeyFrameAnimation.js to do this.  Please help me as I would like to be able to do this as quick as possible and would like some good advice.

Thanks!
-Chunlin

##### Three.js version

- [ ] Dev
- [ ] r77
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by GGAlanSmithee** [comment]
duplicate of #8931 ?

**Comment by rtpHarry** [comment]
To people of the future landing here like I did: I found a way to do this!

https://gist.github.com/rtpHarry/2d41811d04825935039dfc075116d0ad
