### ISSUE TITLE
Object3D new viewable property

### ISSUE THREAD

**Issue by verteAzur** [mrdoob/three.js#9029]
##### Description of the ehancement 
Add a new member variable called "viewable" that is used to notify user if the object is in the camera frustum viewing planes. The variable is set automatically in the WebGLRenderer frustum culling process via the isObjectViewable function. The frustum culling is an expensive process, this new variable saves us time in not redoing the process. This small  property addition brings very valuable info to complement and personalize the  frustum culling functions.

Object proposed change: https://github.com/verteAzur/three.js/commit/cf362721aed08ad718338b40cb182ed0c2232e35

Renderer proposed change: https://github.com/verteAzur/three.js/commit/08baac0c29533dac73a6b5e2c2d1909bd35f16c0

##### Three.js version
- [x ] Dev
- [x] All of them

**Comment by mrdoob** [comment]
What happens in stereo rendering situations? An object may be viewable in one eye but not the other.

**Comment by WestLangley** [comment]
What if there is more than one camera, in general?

**Comment by verteAzur** [comment]
The proposed change allows for multiple cameras.  usage: camera.isviewable(object);

https://github.com/mrdoob/three.js/commit/d9792d3dc855120f96c3dd39a38407553e459ffc

https://github.com/mrdoob/three.js/commit/6421c1bb543b4c1ef2acce5eb18732ec3d2be015

**Comment by mrdoob** [comment]
I could just do...

```js
camera.isInView = ( function () {

	var frustum, matrix;

	return function ( object ) {

		if ( frustum === undefined ) {

			frustum = new THREE.Frustum();
			matrix = new THREE.Matrix4();
		
		}

		this.matrixWorldInverse.getInverse( this.matrixWorld );

		matrix.multiplyMatrices( this.projectionMatrix, this.matrixWorldInverse );
		frustum.setFromMatrix( matrix );

		return frustum.intersectsObject( object );

	}

} )();
```

**Comment by verteAzur** [comment]
Yes, your logic make sense and it is more elegant because the code is confined via 1 single function. I've proposed to use an "inline buffer array" to take advantage of the Frustum Culling process and maximize performance.

**Comment by mrdoob** [comment]
> I've proposed to use an "inline buffer array" to take advantage of the Frustum Culling process and maximize performance.

Yeah, the side effect is that it makes things messy though. Also, it could also be a premature optimisation.

**Comment by verteAzur** [comment]
I understand. The good news is the multiple options to pick from;)

**Comment by verteAzur** [comment]
I am going to try your new function on multiple objects and benchmark it. It will at least give us an idea if performance is really an issue. I anticipate to call the function on a maximum of 40 objects at once. Again this is just my setup. I will try a few case scenarios (1,10,50,100,1000,etc) and let you know the outcome.

**Comment by mrdoob** [comment]
Well, if you want to do that for multiple objects, it would be better to do something like this:

camera.isInView = ( function () {

	var frustum, matrix;

	return function ( objects ) {

		if ( frustum === undefined ) {

			frustum = new THREE.Frustum();
			matrix = new THREE.Matrix4();
		
		}

		this.matrixWorldInverse.getInverse( this.matrixWorld );

		matrix.multiplyMatrices( this.projectionMatrix, this.matrixWorldInverse );
		frustum.setFromMatrix( matrix );

		for ( var i = 0, l = objects.length; i < l; i ++ ) {

			var object = objects[ i ];
			object.userData.visible = frustum.intersectsObject( object );

		}

	}

} )();
```

**Comment by verteAzur** [comment]
Ok, I did some benchmarking... I have used the first function you have proposed though. I will have to do some more testing with the latest code... Here are the results thus far:
![chart](https://cloud.githubusercontent.com/assets/3125827/15689689/77132a98-2780-11e6-8759-8e5989ea4c87.gif)

**Comment by mrdoob** [comment]
Yeah, would be curious to see the results with the second function.

**Comment by verteAzur** [comment]
Voilà the latest benchmarking results:
![chart2](https://cloud.githubusercontent.com/assets/3125827/15700851/d5afd320-27d6-11e6-99b1-d8ab54b8d0ab.gif)
We can see a true performance gain with your latest function. Note, I have optimized the inline function and re-run the test with the same case scenario to make sure it was comparable on all criteria.

updated inline function:

```
isviewable: function(object){
		for(var i=0,l=this.viewable.length;i<l;i++){
			if(this.viewable[i]===object.id){return true;}
		}
		return false;
 	}
```

**Comment by verteAzur** [comment]
Re everyone, we've had time digest the info and we will be using at most 50 objects with that functionality. Plus, we are not using the function via the rendering process @ 120-60 fps. We are integrating it via a 1s. out of process heartbeat, which sum up to a 0,00028 sec. delta instead of a 0,0336 sec. delta (@ 120fps). In other words, the "non-inline process function" performance will be satisfying for our particular case scenario. Maybe there will be needs for greater speed and the rendering process with a 0,0336 sec. delta could become a bottleneck. I guess when that time comes the in-line option will be available... Thanks you for your help and hard work! ++ verteAzur
