### ISSUE TITLE
Faulty deprecation warning in 78dev might point to deeper problems

### ISSUE THREAD

**Issue by killroy42** [mrdoob/three.js#9033]
##### Description of the problem 

Getting this warning:
`THREE.JSONLoader: .statusDomElement has been removed.`
in line 18475 of THREE.js

Following code outputs the error:

```js
var o = {};
Object.assign(o, {
	get statusDomElement () {
		console.error('statusDomElement');
	}
});
```

Indicating that the Object.assign source is executed somehow, which is likely not the intention.

##### Three.js version

- [x ] Dev (r78dev)
- [ ] r77
- [ ] ...

##### Browser

- [] All of them
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [x ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by killroy42** [comment]
I just realized that likely Object.assign will retrieve the property values of the source objects and therefore execute the getters.

**Comment by killroy42** [comment]
This is broken:
`var o = {};
Object.assign(o, {
	get getterFunc () {
		console.error('This should not execute');
		return 'value';
	}
});`
This would work:
`var o = {};
Object.defineProperties(o, {
	getterFunc: {
		get: function () {
			console.error('This should not execute');
			return 'value';
		}
	}
});`

**Comment by mrdoob** [comment]
Wops! Fixing...

**Comment by mrdoob** [comment]
Fixed!

**Comment by killroy42** [comment]
Thanks!

That's what happens if you break your own style guides :P
