### ISSUE TITLE
Emissive map in Loader.js createMaterial?

### ISSUE THREAD

**Issue by Scharnvirk** [mrdoob/three.js#9034]
##### Description of the problem 

I've noticed that Loader.js is missing few case statements for emissiveMap in the big for loop around line 120 where material parmeters are being read and added to final json.

https://github.com/mrdoob/three.js/blob/master/src/loaders/Loader.js

All that is needed to be added is 

 ```
case 'mapEmissive':
	json.emissiveMap = loadTexture( value, m.mapEmissiveRepeat, m.mapEmissiveOffset, m.mapEmissiveWrap, m.mapEmissiveAnisotropy );
	break;
case 'mapEmissiveRepeat':
case 'mapEmissiveOffset':
case 'mapEmissiveWrap':
case 'mapEmissiveAnisotropy':
	break;
```
After adding this to the built threejs file, it seems to work just fine; emissive maps work nicely.

Was this left out on purpose? Is it deprecated or soon-to-be-deprecated?

##### Three.js version

- [ ] Dev
- [x] r77
- [x] r76
- [x] r75

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
> Is it deprecated or soon-to-be-deprecated?

It is, but I'll add it anyway 👍

**Comment by mrdoob** [comment]
Done. Thanks!

**Comment by Scharnvirk** [comment]
Thanks too, I won't have to add it manually next time ^^

If it is going to be deprecated, what should I use, btw?

**Comment by mrdoob** [comment]
Hmm... this is because you are using `JSONLoader`, right?

**Comment by Scharnvirk** [comment]
Yeah, indeed. It is not that I HAVE to use JSONLoader though, I just... use it because well, it works :)

**Comment by mrdoob** [comment]
Yep yep! How do you produce the json files?
