### ISSUE TITLE
Light shadow warning and chrome

### ISSUE THREAD

**Issue by lo-th** [mrdoob/three.js#9037]
One Spot with shadow and some point light without shadow give many gl warning in chrome.
i find solution by adding fake WebGLRenderTarget to there shadow.map.

var fake = new THREE.WebGLRenderTarget( 16, 16, {} );

pointLight1.shadow.map = fake;
pointLight2.shadow.map = fake;
pointLight3.shadow.map = fake;

##### Three.js version

- [ ] Dev
- [x] r77
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

**Comment by Mugen87** [comment]
Can you please post the warnings here? And maybe provide a jsfiddle with an appropriate test case? That would be great :wink:

**Comment by lo-th** [comment]
warning is for one directional with shadow and 3 points light without

Offscreen-For-WebGL-0000015B01608A90]RENDER WARNING: there is no texture bound to the unit 2
.Offscreen-For-WebGL-0000015B01608A90]RENDER WARNING: there is no texture bound to the unit 3
Offscreen-For-WebGL-0000015B01608A90]RENDER WARNING: there is no texture bound to the unit 4
...

**Comment by mrdoob** [comment]
Do you mind creating a jsfiddle?

**Comment by lo-th** [comment]
yep here the jsfiddle
http://jsfiddle.net/lo_th/8kvh63tf/17/

**Comment by Mugen87** [comment]
Um. One spotlight and one point light are not a problem. But as soon as i add an additional point light i get the mentioned warnings...

**Comment by mrdoob** [comment]
Fixed! 😊

**Comment by lo-th** [comment]
cool :)
