### ISSUE TITLE
Model texture not rendering correctly in Three.js

### ISSUE THREAD

**Issue by vbguyny** [mrdoob/three.js#9039]
I am trying to get a DAE model file to render in Three.js (location of model is here: http://tf3dm.com/3d-model/scotty-89815.html). When I try to render the model directly, Chrome locks up. When I import and export the model from Blender, the browser works but the textures are not appearing correctly in the model. I both exporting to DAE and JSON and the results are the same. As a side note, I exported all of the TGA texture files to PNG because Chrome wouldn't display any of the textures otherwise.

I am using Blender 2.77 and Three.js r77. Below is the script that I am using on my web page:

```
var loader = new THREE.ColladaLoader();
loader.options.convertUpAxis = true;
loader.load('Scotty/Scotty1.dae', function (collada)
{
    var dae = collada.scene;
    var skin = collada.skins[0];
    dae.position.set(0, 0, 0); //x,z,y- if you think in blender dimensions ;)
    dae.scale.set(.5, .5, .5);
    scene.add(dae);
});

// Load JSON file
var loader = new THREE.JSONLoader();
loader.load('Scotty/Scotty.json', function (geometry, materials)
{
    var mesh = new THREE.Mesh(geometry, new THREE.MeshFaceMaterial(materials));

    mesh.scale.set(0.25, 0.25, 0.25);
    mesh.position = new THREE.Vector3(0, -1000000, 0);
    scene.add(mesh);
});
```
##### Three.js version
- [ ] Dev
- [x] r77
- [ ] ...
##### Browser
- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
##### Hardware Requirements (graphics card, VR Device, ...)

Appears to be hardware independent.

**Comment by mrdoob** [comment]
`ColladaLoader` is kind of deprecated. `ColladaLoader2` doesn't handle Armatures yet. `OBJLoader` seems to be able to load it just fine.

**Comment by daoshengmu** [comment]
@mrdoob I can help this. Do you think we should make this work in ColladaLoader or ColladaLoader2? Btw, what is Armatures? Do you mean skeletal animation?

**Comment by mrdoob** [comment]
@daoshengmu Yeah, I think Collada refers to them as Armatures. `ColladaLoader2` at the moment mainly lacks Armatures and Animations. Implementing Armatures would be a great step forward in order to be able to replace `ColladaLoader`.

**Comment by Mugen87** [comment]
`ColladaLoader2` can handle skeletal animations now, see https://threejs.org/examples/#webgl_loader_collada_skinning

The loader should be able to load and parse the mentioned model and its animations.

**Comment by Callstackarchaeological** [comment]
I explored various avenues and finally found the answer https://okta-api9.github.io/digby16/ I sought
