### ISSUE TITLE
Placement of CylinderGeometry incorrect when scripts loaded dynamically

### ISSUE THREAD

**Issue by mbourne** [mrdoob/three.js#9046]
##### Description of the problem 

This intermittent problem occurs when Three.js scripts are loaded dynamically, and/or when other unrelated scripts are loaded dynamically with or without async.

This page demonstrates and explains the issue: http://www.intmath.com/cg3/threejs-with-script-loader.php

It doesn't appear to affect any other geometry.

##### Three.js version

- [x] r77

##### Browser

- [x] Chrome (more commonly than FF)
- [x] Firefox
- [x] Safari

##### OS

- [x] All of them
- [ ] Windows (more with Win7 than Win10)
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

May not be relevant...

**Comment by mrdoob** [comment]
Difficult to know. But it may be a something like a `lookAt()` done before the model loads?

**Comment by Mugen87** [comment]
I've debugged your code in `threejs-with-script-loader.php`with and without my adblocker.

If adblocker is active, the variable `length` in the following statement is `0`.
```javascript
upperGeom.applyMatrix( new THREE.Matrix4().makeTranslation( 0, length / 2, 0 ) );
```

If i disable my adblocker `length` has the value `2`. That means you are making a translation of (0,1,0) with the geometry. 

For some reasons, it looks like the value of the global variable `length` depends on the existence of ads on your website. Maybe you just change your code for geometry translation.

**Comment by makc** [comment]
Maybe you just change the code you copied and pasted from that website?

(and maybe page author did that intentionally to punish adblock users)

**Comment by makc** [comment]
Damn, @Mugen87, I am an idiot. I did not notice you were not the one who posted the issue.

**Comment by mbourne** [comment]
Thank you Mugen87 - removing that makeTranslation line fixed it. It was some leftover from a previous experiment that I probably assumed was essential and didn't test it properly. Doh.

I've updated the demonstration page in case it's useful for anyone.
