### ISSUE TITLE
Three.js with HtmlUnit giving error

### ISSUE THREAD

**Issue by sgrg93** [mrdoob/three.js#9048]
##### Description of the problem 

While using htmlunit (headless browser in java) to render 3D canvas with three.js, I got this error com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot call method "getExtension" of null in three.js

Is three.js compatible with htmlunit to create animated 3D computer graphics in java?

##### Three.js version

- [ ] Dev
- [x] r77
- [ ] ...

##### Browser

- [x] HtmlUnit

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
Are you sure htmlunit supports `WebGLRenderingContext`? See https://sourceforge.net/p/htmlunit/feature-requests/211/

**Comment by sgrg93** [comment]
No, I'm not sure about it. Is three.js supported by any other headless browser in java?

**Comment by Mugen87** [comment]
>Is three.js supported by any other headless browser in java?

Sry, that's not really my area. Maybe it's better to ask this question at stackoverflow (see [here](https://github.com/mrdoob/three.js/blob/master/.github/CONTRIBUTING.md)).

**Comment by mrdoob** [comment]
Sounds like htmlunit doesn't support webgl. Make sure the headless browser you user supports webgl.
