### ISSUE TITLE
Incorrect test for property existence in property binding

### ISSUE THREAD

**Issue by anthonybriand** [mrdoob/three.js#9057]
##### Description of the problem 
I am creating an animation authoring system, I need to hide or show an object during the animation.

To do that I use the THREE.PropertyBinding to handle the changes, but when I create a track on the visible property of an object and I call the getValue function of PropertyBinding, it throw the error " trying to update property for track: XXXX.visible but it wasn't found"

The test for property existence in the bind function of PropertyBinding is incorrect in the case of the type of the property is a boolean and it's equal to false or it's a number and it's equal to 0.

cf : [https://github.com/mrdoob/three.js/blob/master/src/animation/PropertyBinding.js#L166](https://github.com/mrdoob/three.js/blob/master/src/animation/PropertyBinding.js#L166)

I purpose to change the test : 
`if ( ! nodeProperty ) {`
by
`if ( nodeProperty === undefined ) {`

In this way we don't have false negative existence.

##### Three.js version

- [x] Dev
- [x] r77
- [x] 76

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Mac
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Nothing

**Comment by mrdoob** [comment]
That change sounds good to me. Would you like to do a PR with it?

**Comment by anthonybriand** [comment]
I have created the PR
