### ISSUE TITLE
VREffect setFullScreen does not work with the last version of Chromium with Vive

### ISSUE THREAD

**Issue by arturitu** [mrdoob/three.js#9060]
##### Description of the problem 

With the last @toji Chromium version the effect.setFullScreen(true); method does not work.
Now, is necessary to use instead: effect.requestPresent();

##### Three.js version

- [ ] Dev
- [x] r77
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [X] Chromium (WebVR)
##### OS

- [] All of them
- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)

HTC Vive

**Comment by mrdoob** [comment]
That's strange because, currently, `requestPresent()` uses `setFullScreen( true )` internally...

https://github.com/mrdoob/three.js/blob/master/examples/js/effects/VREffect.js#L222-L226
