### ISSUE TITLE
floor of panorama looks bad 

### ISSUE THREAD

**Issue by webfalcon** [mrdoob/three.js#9061]
##### Description of the problem 

Hi. I using three.js created a panoramic script: http://web.edenstudio.am/demo/test-3/2/
But there is 2 issues. 
1). Logo in the bottom of panoramic image don't show right. Also I see it in three.js demo site: http://threejs.org/examples/webgl_panorama_equirectangular.html There bottom too looks bad! 

2). The image is very round! 

Please help to remove that issues. Thank you.

##### Three.js version

- [ ] Dev
- [x] r75
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by bhouston** [comment]
DO not use a single latlong image, rather use 6 sided cubemaps.  Then you will not have the polar issues.

**Comment by mrdumb** [comment]
Spherical mapping generates polar distortions and there is no fix for that.
As Ben already mentioned, use Cube mapping for better results.
