### ISSUE TITLE
SkeletonHelper is not rendered without mesh.bind() being called

### ISSUE THREAD

**Issue by matteorr** [mrdoob/three.js#9063]
It is not possible to render a `THREE.SkeletonHelper`without binding it to a `THREE.SkinnedMesh`.
I believe this should be possible, since the `THREE.SkeletonHelper` class defines internally its own geometry and material. If it is not possible, how could this feature be added?

```
THREE.SkeletonHelper = function ( object ) {
    this.bones = this.getBoneList( object );
    
    var geometry = new THREE.Geometry();
    
    for ( var i = 0; i < this.bones.length; i ++ ) {
    
    	var bone = this.bones[ i ];
    
    	if ( bone.parent instanceof THREE.Bone ) {
    
    		geometry.vertices.push( new THREE.Vector3() );
    		geometry.vertices.push( new THREE.Vector3() );
    		geometry.colors.push( new THREE.Color( 0, 0, 1 ) );
    		geometry.colors.push( new THREE.Color( 0, 1, 0 ) );
    
    	}
    
    }
    
    geometry.dynamic = true;
    
    var material = new THREE.LineBasicMaterial( { vertexColors: THREE.VertexColors, depthTest: false, depthWrite: false, transparent: true } );
    
    THREE.LineSegments.call( this, geometry, material );
    
    this.root = object;
    
    this.matrix = object.matrixWorld;
    this.matrixAutoUpdate = false;
    
    this.update();
    
};
```

Note that `THREE.SkeletonHelper` does not give an error if you try constructing it from a bones array instead of a skinned mesh:
```
// both of the below work
skeletonHelper = new THREE.SkeletonHelper( bones[0] );
skeletonHelper = new THREE.SkeletonHelper( mesh );
```

I recreated the problem in the following [JSFiddle](http://jsfiddle.net/akmcv7Lh/67/): if you remove the comments from the mesh construction (but specifically the mesh.bind() lines 58, 63) the skeleton helper becomes visible, even if the mesh is not added to the scene.

##### Three.js version

- [ ] Dev
- [x] r77
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [x] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Is the code that you shared a proposed fix?

**Comment by matteorr** [comment]
The code shows that a SkeletonHelper can be rendered only if you bind it with a SkinnedMesh.
I'm not sure if this is a bug or a wanted behavior and this is why I posted.

Do you have any suggestion on how to render the helper without creating a skinned mesh?
Thanks for any help on this!

**Comment by mrdoob** [comment]
Ah, I wasn't sure why you shared the `SkeletonHelper` code. Unfortunately, I don't have a full understanding of this issue at the moment.

**Comment by matteorr** [comment]
@mrdoob - I shared it to show the fact that a material and a geometry is created in the object constructor. I though it was relevant for explaining why I believe a `SkeletonHelper` should be rendered even if not binded to a `SkinnedMesh`.

Do you think that any other of the [`SkeletonHelper`](https://github.com/mrdoob/three.js/blob/master/src/extras/helpers/SkeletonHelper.js) contributors of authors  would be able to give some insights? Is it ok to just mention them using `@`?

**Comment by takahirox** [comment]
Try to call updateMatrixWorld(true) of root object.
In your example, mesh.updateMatrixWorld(true)

**Comment by matteorr** [comment]
@takahirox - This works, thanks! sorry for the late reply. Could be please explain to me what's happening under the hood, and why does updating the world matrix make the bones visible?

**Comment by takahirox** [comment]
First of all, this wasn't a visible/invisible issue,
but just objects were out of camera view.

You're required to set world matrix to place an object correctly.
`position` that you set in your code is local position.
To only update `position` won't affect world matrix.
(If you aren't familiar with these words,
 google them or refer to 3D CG programming text)

updateMatrixWorld() is called in bind() so
you didn't need to call it in user code if you call bind()

You can see what happened if you run the following command
before/after updateMatrixWorld() or bind().
> console.log(bones[0].matrixWorld.elements);
