### ISSUE TITLE
Rendering large json  objects using webGLRenderer 

### ISSUE THREAD

**Issue by mayur5478** [mrdoob/three.js#9065]
##### Description of the problem 
I am trying to render more than 1000 json files by firstly loading them through JSONLoader and then rendering them using WebGLRenderer . The browser crashes after a certain number of files have been loaded and rendered (upto 500 or 600 jsons approx.) Is there any way to achieve rendering large files using threejs or do I have to choose some other method?
(This is NOT a help site. Please read the guidelines above before posting.)

##### Three.js version

- [X] Dev
- [X] r77
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by makc** [comment]
```javascript
function disposeObject (obj)
{
	if (obj)
	{
		for (var i = 0; i < obj.children.length; i++)
		{
			disposeObject(obj.children[i]);
		}
		if (obj.geometry)
		{
			obj.geometry.dispose();
			obj.geometry = undefined;
		}
		if (obj.material)
		{
			if (obj.material.materials)
			{
				for (i = 0; i < obj.material.materials.length; i++)
				{
					obj.material.materials[i].dispose();
				}
			}
			obj.material.dispose();
			obj.material = undefined;
		}
		if (obj.texture)
		{
			obj.texture.dispose();
			obj.texture = undefined;
		}
	}
}
```

**Comment by tribe84** [comment]
@makc - Can you give a litte context as to how your code addresses the question?

**Comment by makc** [comment]
@tribe84 - If 1000 objects do not fit in memory, then you have to release that memory after you render them. That will probably also involve turning auto-clearing off in renderer and sorting transparent stuff (if any) yourself.

**Comment by tribe84** [comment]
@makc  - awesome, thanks!

**Comment by mayur5478** [comment]
@makc - What about if I have to select an object which is rendered and change its color ? I store an id on every object which I get on it being selected and then change its color. Isn't the object now removed from memory ?

**Comment by makc** [comment]
@mayur5478 I don't know, think of something :)

if you can waste more time and render it twice, you can render solid color version of the scene into texture for picking / highlighting objects later.

**Comment by mayur5478** [comment]
I am not able to figure out how I will be able to rotate or zoom the scene which is rendered after I remove all the objects from memory. Using preserveDrawingBuffer:true attribute in the renderer and dispose object I was able to render the 1000 objects and browser did not crash .But my use case is also to rotate or zoom the rendered scene which I am unable to do. Is there something I can do?

**Comment by mayur5478** [comment]
I tried using trackballControl.js and I update the trackballControl object by calling it repetitively inside requestAnimationFrame but that doesnt seem to update the rendered scene

**Comment by makc** [comment]
> I am not able to figure out how I will be able to rotate or zoom the scene which is rendered after I remove all the objects from memory.

this is, of course, impossible. and loading them into memory again will give you 0.00001 frames per second, most likely.

**Comment by makc** [comment]
well, actually, you could zoom if you render in like 4096x4096 texture

**Comment by mayur5478** [comment]
could you please elaborate on what you are saying?

**Comment by makc** [comment]
for example, this mac has 1920x1280 resolution, so if I render something to 4096x4096 texture, I can then potentially zoom 4096/max(1920,1280) by x2.1 in fullscreen; this would be even more for smaller screens/windows.

I do not know any way of doing significant rotation. if you could also render depth with [multiple targets](https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_draw_buffers), you will be able to emulate very slight rotations, like 1 - 2 degrees maybe, but nothing like trackball controls.

**Comment by mayur5478** [comment]
Are you saying that by my current approach it is impossible to rotate the 1000 json objects if memory is  being made free by disposing objects . Then is there no other way in which I can render such large number of objects and rotate/zoom or animate them using threejs?

**Comment by makc** [comment]
Pretty much, you need them all in memory again to re-render from different angle

**Comment by makc** [comment]
maybe try something like https://github.com/mozilla/localForage to store objects on hard drive between renders, to avoid raping the network?

**Comment by mayur5478** [comment]
will try it . Lets see. Will post within few days

**Comment by mayur5478** [comment]
Did try it . These are the steps I followed (1000 jsons example):-
1:Loading  250 jsons and storing json in localForage so that subsequent loads wont require ajax request.
2:creating mesh using geometry from loader callback and material and adding  it to scene
4: rendering these objects (setting preserveDrawingBuffer to true for WebGLRenderer)
5: disposing them 

Repeat these process for other jsons

The speed for zooming or animation was relatively lower than trackballcontrols.js  but it is better than not able to animate at all without browser crashing. Hopefully in future will be able to do such a case cause its relatively frequent .
