### ISSUE TITLE
Audio stop() function should set 'isPlaying' to false.

### ISSUE THREAD

**Issue by smatthews1999** [mrdoob/three.js#9067]
##### Description of the problem 

Re: Audio.js

I was trying to get a loaded audio sound to stop and restart each time an event was triggered.  

The audio play time is longer than the time between events.

The function 'play()' reported back 'THREE.Audio: Audio is already playing.', even though I called 'stop()' on the audio.

I solved this by setting 'isPlaying' to false, and then calling 'play()'.  

The sound restarted and worked fine.

So I am suggesting that stop() function should probably set 'isPlaying' to false.
 
##### Three.js version

- [ ] Dev
- [x] r77
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Sounds good to me. Would you like to do a PR with the patch?

**Comment by smatthews1999** [comment]
Yes sir,

will do.

Sam

**Comment by mrdoob** [comment]
#9072
