### ISSUE TITLE
VREffect and glTFLoader don't work properly together

### ISSUE THREAD

**Issue by harrio** [mrdoob/three.js#9073]
##### Description of the problem

If a glTF model is viewed in VR it doesn't render correctly but seems to move when head is turned. The effect can be seen in this video: http://bit.ly/1XX7HFA

Here's an example scene: http://bit.ly/24nipoG

The problem seems to stem from having to call

``` javascript
THREE.glTFShaders.update(scene, camera);
```

when rendering as that doesn't take into account the left and right cameras created by VREffect.
##### Three.js version
- [x] Dev
- [x] r77
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by harrio** [comment]
A workaround to this can be hacked together by accessing both of VREffect's cameras and calling THREE.glTFShaders.update for both when rendering. The object then displays correctly. 
Thanks to @vehvis for coming up with this.

**Comment by mkeblx** [comment]
Ideally wouldn't have to modify `VREffect` to call `THREE.glTFShaders.update` before each eye renders. Also need this for certain eye-specific post-processing stuff. What would be the best approach? Could do like below, or emit events. Events might be better.

```javascript
// main

effect = new THREE.VREffect( renderer );
effect.preRenderL = function( camera ){ THREE.glTFShaders.update( scene, camera ) };
effect.preRenderR = function( camera ){ THREE.glTFShaders.update( scene, camera ) };


// VREffect.js
var preRenderL = null;
var preRenderR = null;

// render (...) {

  if ( preRenderL )
    preRenderL( cameraL );

  renderer.render( scene, cameraL, renderTarget, forceClear );

  if ( preRenderR )
    preRenderR( cameraR );

  renderer.render( scene, cameraR, renderTarget, forceClear );

}

```

**Comment by donmccurdy** [comment]
After #10851, this issue appears to be fixed.
