### ISSUE TITLE
Ocean (WaterShader from jbouny) Example Broken

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#9077]
##### Description of the problem 

http://threejs.org/examples/#webgl_shaders_ocean

This example is fairly broken. For me it works just fine in app (minus fog support for some reason since r75).

The shader file is here: https://github.com/mrdoob/three.js/blob/master/examples/js/WaterShader.js

##### Three.js version

- [ ] Dev
- [x] r77
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome (51.0.2704.79 m)
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

GeForce GTX650 - driver: 10.18.13.6822 (latest whql)

Windows 7 64bit

The example looks fine in Firefox.

**Comment by Mugen87** [comment]
On my ThinkPad with Ubuntu 15.10 and Chromium 50.0.2661.102 / Firefox 46.0.1 everything works fine. Do you get any console errors or warnings?

**Comment by titansoftime** [comment]
>On my ThinkPad with Ubuntu 15.10 and Chromium 50.0.2661.102 / Firefox 46.0.1 everything works fine. Do you get any console errors or warnings?

Scene: 
![ocean](https://cloud.githubusercontent.com/assets/6549763/15801019/48ac281e-2a4e-11e6-8415-79c1fe931bf7.jpg)

Console:
![oceanconsole](https://cloud.githubusercontent.com/assets/6549763/15801021/54729df4-2a4e-11e6-8af2-13a9b90af75e.jpg)

It works (almost) fine on the same machine in my app (minus fog support).

**Comment by Mugen87** [comment]
Do you still have this problem with the latest chrome and three.js R81?

**Comment by titansoftime** [comment]
It works now (except fog). Closing.
