### ISSUE TITLE
Instanced geometry material lighting

### ISSUE THREAD

**Issue by DVLP** [mrdoob/three.js#9081]
##### Description of the problem

Rendering instanced geometry with textures requires writing custom shaders. Additionally getting lighting to work is even more difficult. Eventually instanced geometry materials should be part of Three.js so using this type of meshes would be as natural as using regular meshes. Unfortunately my beginner's knowledge of GLSL will not allow to develop that.
##### Three.js version
- [x] Dev
- [x] r77
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Closing in favor of #17505.
