### ISSUE TITLE
shadow.Bias has no effect

### ISSUE THREAD

**Issue by weiserhei** [mrdoob/three.js#9086]
##### Description of the problem 
`shadowBias` is now `shadow.Bias`.
But using `shadow.Bias` has no effect, while `shadowBias` still works.

##### Three.js version

- [x] Dev
- [x] r77

##### Browser

- [ ] All of them
- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
`shadowBias` is now `shadow.bias`.

**Comment by weiserhei** [comment]
The problem here was me using a capitalized `B` in `shadow.Bias`.
