### ISSUE TITLE
Android Chrome - Not all point lights render

### ISSUE THREAD

**Issue by mzlock** [mrdoob/three.js#9100]
##### Description of the problem 
When viewing Three.js scenes on the newest version of Android Chrome (4.2), only the first PointLight in a list of Point Lights will work.

Replicated in this experiment (http://threejs.org/examples/#webgl_lights_pointlights2) as well as on a project I'm working on (sorry, I can't share the link at the moment).

##### Three.js version
version 76.0.2

##### Browser
Chrome

##### OS
Android

##### Hardware Requirements (graphics card, VR Device, ...)
Replicated on a Nexus 5 and a Samsung Galaxy S5

**Comment by mzlock** [comment]
Note:
This bug is reproducible on the actual devices listed.  The issue does not appear when testing with BrowserStack.

**Comment by mrdoob** [comment]
> Android Chrome (4.2)

4.2? Current Chrome Stable for Android is 50.0.

**Comment by mzlock** [comment]
Sorry, 4.2 by the app store's versioning.  `chrome://version` says 51.0.2704.81

**Comment by mrdoob** [comment]
![screenshot_20160608-135916](https://cloud.githubusercontent.com/assets/97088/15910778/60a86e74-2d81-11e6-9a3d-895450ae8987.png)

Nexus 5x, Chromw 50, Android 6.0.1

**Comment by mzlock** [comment]
Did you try this example: http://threejs.org/examples/#webgl_lights_pointlights2 ?

When testing that one, only the pink light would produce light and otherwise I just saw colored balls floating around.

**Comment by mzlock** [comment]
Here is a screenshot from my testing device with the same point light example:

![dcbfb687-e2db-48ca-8481-c9cbf60698aa](https://cloud.githubusercontent.com/assets/1087001/15911478/45896fec-2d8d-11e6-829a-8c6e2359ab27.png)

**Comment by mrdoob** [comment]
What version of Android are you on?

**Comment by mzlock** [comment]
Android 6.0.1  Are you testing on a physical device or an emulator of some kind?  I was unable to reproduce in BrowserStack, but both hardware phones I tested had this issue.

**Comment by mrdoob** [comment]
Ok, so @spite was able to reproduce and noticed that this broke between 73 and 74.

**Comment by mrdoob** [comment]
Investigating...

**Comment by bhouston** [comment]
I can reproduce this as well on my Nexus 5.

**Comment by jimshell** [comment]
Still there in r81. When using several pointlights on a scene, only the first added one actually works as expected, any subsequent pointlight seems ignored.

Any clue?

Chrome 53.0.2785.124 // Android 6.0.0 // Moto G 2

**Comment by mrdoob** [comment]
Haven't been able to access my Nexus 5 yet.

**Comment by spite** [comment]
Confirmed not working on Chrome 53.0.2785.124 // Android 6.0.1 // Nexus 5

**Comment by bhouston** [comment]
I've identified the problematic commit via manual binary search:

https://github.com/mrdoob/three.js/commit/3adb436bad83f879592b299b6155f3c9dc3a746f

**Comment by bhouston** [comment]
I'm working through the commit now to find out exact problematic line.

**Comment by bhouston** [comment]
I fixed this via this PR #9948
