### ISSUE TITLE
Problem with fromBufferGeometry in minified version

### ISSUE THREAD

**Issue by mhoebinger** [mrdoob/three.js#9102]
##### Description of the problem

In "Geometry.fromBufferGeometry", the variable "tempNormals" is declared as an empty array which is then subsequently filled in a for loop. The function "addFace" within "fromBufferGeometry" then reads from this locally defined array. In the minified version the "tempNormals" variable, then obviously renamed to a one letter name, is only defined in the for loop statement. This leads then to a runtime error in the "addFace" function, where the variable corresponding to "tempNormals" is not defined.

Specifically the for loop definition

"for ( var i = 0, j = 0; i < positions.length; i += 3, j += 2 )"     in line 10057 of three.js

becomes

"for(var p=[],n=[],m=[],q=e=0;e<f.length;e+=3,q+=2)" in line 212 of thee.min.js

I think this can be fixed easily by adding "tempNormals" as an argument to "addFace", but I am not experienced enough with JS to know for sure.
##### Three.js version
- [ ] Dev
- [ ] r77
- [x ] r76
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
> I think this can be fixed easily by adding "tempNormals" as an argument to "addFace", but I am not experienced enough with JS to know for sure.

Interesting... Do you mind giving it a try?

**Comment by makc** [comment]
is this minifier bug?

**Comment by mhoebinger** [comment]
Hi,

I will try once I get home later this week!

**Comment by Mugen87** [comment]
Closing. We can reopen if this is still an issue in the latest `three.min.js` build.
