### ISSUE TITLE
Paint on model example

### ISSUE THREAD

**Issue by VinnyVicious** [mrdoob/three.js#9103]
A very helpful addition to the list of examples would be an example that allowed you to paint on the texture of a mesh by clicking on a part of the mesh. It's a good example on how to transfer coordinates from screen and world view into texture projection.

**Comment by WestLangley** [comment]
See http://threejs.org/examples/webgl_raycast_texture.html.

**Comment by makc** [comment]
Btw http://jsdo.it/makc/zXNX

**Comment by VinnyVicious** [comment]
Amazing! Thank you.

**Comment by AbhinavPelapudi** [comment]
How to do free-hand painting(i Can choose any color to paint except white) and erasing(i want to use white color to erase the painting on rendered scene) on three js scene. i also want to extract the coordinates. can I know how to do this? are there any examples ?

**Comment by WestLangley** [comment]
@AbhinavPelapudi Sorry, this is not a help site. Please use the three.js [forum](https://discourse.threejs.org), and show what you have tried.

**Comment by sciecode** [comment]
I noticed issue has been pushed over and over again. So I decided to give it try.
I've used a technique similar to what you can find Blender's Texture Painter.
Here is a ['working' example](https://rawcdn.githack.com/sciecode/three.js/f4e363a8e0cf6c496f4191192d7eb15110442a7c/examples/webgl_paint_texture.html).

This is, by no means, finished. I would still need to implement/fix the following things:
- face clipping artifacts
- normal opacity falloff
- geometry occlusion
- BufferGeometry support
- public interface and variables

I just wanted to receive some feedback if this is inline with what's expected from this example, and if I should continue working on it.

**Comment by sciecode** [comment]
Updated [example](https://rawcdn.githack.com/sciecode/three.js/392661079fce6413e2e7ff6b35d0700ceee209e7/examples/webgl_paint_texture.html).

This is still missing Occlusion Culling, you can check that by switching to the 'Torus' mesh and painting it sideways. I believe that sorting a high number of intersecting faces would slow this to a crawl. 

Changing the texture update procedure from canvas-based to gpu-based would probably allow for Occlusion Culling within 16ms constraint, but that would require a great deal of time. Time that I probably don't have, at the moment.

 [THREE.TexturePainter](https://github.com/sciecode/three.js/blob/dev8/examples/js/TexturePainter.js)
I don't know, if this is good enough for example, I can prepare this for PR. I don't believe there's too much to be done. Also considered switching name to MeshPainter, open to suggestions.

**Comment by Mugen87** [comment]
From https://github.com/mrdoob/three.js/pull/16498#issuecomment-494255143

> But to be honest, the purpose of the examples is to demonstrate three.js features. This demo appears to be more of a three.js-based application -- a bit too complicated to be useful as an example, IMO.

Correct. Such application-like demos are better placed in the `Showcase` category of the [forum](https://discourse.threejs.org/).
