### ISSUE TITLE
Efficient way of loading big OBJ files?

### ISSUE THREAD

**Issue by lance2611** [mrdoob/three.js#9105]
I'm trying to load an extremely big OBJ file using OBJLoader but it takes too long for it to render (like 20 - 30 seconds). Is there a more efficient way of doing this? Is there a function that cuts the obj piece by piece and load them separately? 

Thanks in advance!

**Comment by mrdoob** [comment]
We don't have a function for that. You'll have to use a 3d package to do the piecing...
