### ISSUE TITLE
CubeTextureLoader doesn't use onProgress callback

### ISSUE THREAD

**Issue by ayng** [mrdoob/three.js#9110]
##### Description of the problem

The CubeTextureLoader has a load method with the following signature:

``` javascript
.load(urls, onLoad, onProgress, onError)
```

As with other loaders, anyone would expect that the `onProgress` callback will be called while the loading progresses. However, any callback passed in as `onProgress` will never be called. [This line in the source file](https://github.com/mrdoob/three.js/blob/cf584a60bdfd24c42eaa81d484533364742bda44/src/loaders/CubeTextureLoader.js#L41) is rather telling.

**Comment by Mugen87** [comment]
> As with other loaders, anyone would expect that the onProgress callback will be called while the loading progresses.

`CubeTextureLoader` as well as `TextureLoader` depend on `ImageLoader` which does not support progress events. And it's unlikely this will change in the future, see #10439

**Comment by ayng** [comment]
Ah, yeah. Thanks for linking that issue. In light of the work documented over there, and since I see that other issues like this one have been closed, I'll go ahead and close this one.
