### ISSUE TITLE
Rollercoaster example alternative track without crossovers

### ISSUE THREAD

**Issue by tentone** [mrdoob/three.js#9114]
##### Description of the problem 

Hi there in the current rollercoaster there are a lot of crossovers and the rollercoaster is kinda of boring, for a VR rollercoaster that i created inside a platform that im developing, i used diferent parametric function for a smaller rollercoaster without any crossovers that could be used in the threejs example as well. Probably a lot of people are using it as a webvr example.

```
function getPointAt(t)
{
	t *= Math.PI;
	
	var x = Math.sin(t * 4) * Math.cos(t * 6) * 1000;
	var y = Math.cos(t * 8) * 80 + Math.cos(t * 20 * Math.sin(t)) * 40 + 200;
	var z = Math.sin(t * 5) * Math.sin(t * 3) * 1000;

	return new THREE.Vector3(x, y, z);
}
```

Here's a video (the original threejs rollercoaster structure generator was used here kudos to mrdoob for creating it)
https://www.youtube.com/watch?v=yUnMzOTbaxI

##### Three.js version

- [x ] Dev
- [ ] r77
- [ ] ...

**Comment by makc** [comment]
@tentone why not pull request?

**Comment by tentone** [comment]
@makc As nobody gave opinion about it I thought this was irrelevant (its a small change to an example anyway).

**Comment by tentone** [comment]
Lol thanks a lot ;)
