### ISSUE TITLE
RawShaderMaterial doesn't support custom defines

### ISSUE THREAD

**Issue by fallenoak** [mrdoob/three.js#9119]
##### Description of the problem 

It appears that ```RawShaderMaterial``` skips all custom defines. While this looks intentional, I'd argue that, at the minimum, user-provided ```defines``` should propagate through to the shader code.

Is this something folks would be willing to entertain?

##### Three.js version

- [ ] Dev
- [x] r77
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
I guess it is intentional. What's your use case?

**Comment by fallenoak** [comment]
The project I'm working on can't really take advantage of much of Three's built-in shaders, but happily works with the rest of Three's rendering logic.

I've been interested in moving away from ```ShaderMaterial``` in favor of ```RawShaderMaterial```, but doing so means I lose the ability to use ```#define``` and have to resort to branching in various places. I guess I'm expected to write my own shader framework if I'm going to ditch ```ShaderMaterial```-- is that right?

**Comment by WestLangley** [comment]
Personally, I would like to add `SHADER_NAME` also to `prefixVertex/Fragment`, which is useful when using @spite's Chrome shader editor extension.

`RawShaderMaterial` is used for instanced `BufferGeometry`, too, which I expect will get more use in time.

I support this suggestion.
