### ISSUE TITLE
Editor: Why are you using blob url to save json?

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#9129]
I mean, can't you just do [this](https://jsfiddle.net/mqrfqLdL/)?

This line

``` javascript
        // URL.revokeObjectURL( url ); breaks Firefox...
```

seems to agree )

**Comment by mrdoob** [comment]
Oh, that looks simpler indeed! Would you like to do a PR?

**Comment by makc** [comment]
Actually, now that I looked deeper, function save( blob, filename ) is not only used for json, there is also this:
```javascript

		var manager = new THREE.LoadingManager( function () {

			save( zip.generate( { type: 'blob' } ), 'download.zip' );

		} );
```
so changing the way json is saved means this call has to be inlined (and still use blob url)

**Comment by makc** [comment]
so we'd end up with this:
![screen shot 2016-06-14 at 22 21 25](https://cloud.githubusercontent.com/assets/242577/16058368/6d217e00-327e-11e6-9aa0-b3a7018fd499.png)

not sure if this is better

**Comment by mrdoob** [comment]
I think you can pass something other than `blob` to `zip.generate()`.

**Comment by mrdoob** [comment]
Also, this is something that needs to be tested in all browsers...
