### ISSUE TITLE
iPad 3/4 - Nothing Visible in Scene

### ISSUE THREAD

**Issue by mzlock** [mrdoob/three.js#9131]
##### Description of the problem

On iPad gen 3 and gen 4, nothing appears to render; I just get a black scene.  In http://threejs.org/examples/#webgl_lights_pointlights2 the lights are rendering, but some geometry is missing.  In my scene, if I remove the point lights and use an ambient light instead, it works.
##### Three.js version

greater than 0.74.0
##### Browser

All of them - Chrome, Safari, Firefox on iOS
##### OS

iOS - 9.3.2
##### Hardware Requirements (graphics card, VR Device, ...)

Shows on gen 3 and 4 iPads, but not a iPad Air 2

May be related to #9100 

My code:

```
addPointLight: function(x, y, z, intensity, distance, decay, color) {
    intensity = intensity ? intensity : 1
    distance = distance ? distance : 100
    decay     = decay ? decay : 1
    color       = color ? color : 0xffffff

    var light = new THREE.PointLight(color, intensity, distance, decay)
    light.position.set( x, y, z )
    scene.add(light)

    return light
}

// can see things with this ambient light present
var light = new THREE.AmbientLight( 0x404040 ); // soft white light
this.scene.add( light );

// forward lights
addPointLight(40, -10, 10, 3, 80, 2.2, 0xff0000)  // bottom right
addPointLight(-40, 20, 40, 3.5, 180, 3.3) // top left - primary light

// bounce lights
addPointLight(15, -20, 3, 0, 30, 2, 0xff0000) // bottom right
addPointLight(-20, 40, 0, 28, 20, 2) // top left
```

**Comment by mrdoob** [comment]
![image](https://cloud.githubusercontent.com/assets/97088/16060078/d9b5ba98-323a-11e6-87c9-a9e57213bad4.png)

iPad Air 1st Gen

**Comment by mrdoob** [comment]
Are there any errors in the console? (If you connect the ipad to your computer you should be able to check the console: http://moduscreate.com/enable-remote-web-inspector-in-ios-6/)

**Comment by mzlock** [comment]
![img_0056](https://cloud.githubusercontent.com/assets/1087001/16060250/0fa22f66-3244-11e6-943c-392ddd01869d.PNG)

From my iPad third gen Model FC705LL/A

I'll check for console errors

**Comment by mzlock** [comment]
Nope, no errors logged for http://threejs.org/examples/#webgl_lights_pointlights2 

![screen shot 2016-06-14 at 3 34 53 pm](https://cloud.githubusercontent.com/assets/1087001/16060571/a246a44a-3245-11e6-9de5-b52bb3fe8e20.png)

**Comment by mrdoob** [comment]
@bhouston sounds like MeshStandardMaterial doesn't work on some iPads. You won't happen to have one around?

**Comment by mzlock** [comment]
I'm using Phongs in my scene where things aren't rendering without an Ambient light.  I'm assuming that the example and my code are related, but they may not be.  I am adding my geometry to the scene right after adding lights (or possibly concurrently, because JavaScript).

```
loader.load('../assets/static/three/object.json', function(geometry) {
  var material = new THREE.MeshPhongMaterial({
     map: 'texture.jpg',
     bumpMap: 'texture-bump.jpg',
     bumpScale: 0.1,
     shininess: 100,
     specularMap: 'texture-specular.jpg'
  })
  var obj = new THREE.Mesh(geometry, material)
  obj.scale.set(2, 2, 2)
  obj.position.set(0, 10, 0)
  scene.add(obj)
```

**Comment by mrdoob** [comment]
Lets focus on `webgl_lights_pointlights2` 😁

**Comment by bhouston** [comment]
I have an iPad Air 2 and it works with threejs.org/examples/#webgl_lights_pointlights2 unfortunately:

![img_0019](https://cloud.githubusercontent.com/assets/588541/16081238/b143bd26-32da-11e6-9fdb-b8967a8d77f4.PNG)

**Comment by javiermorawski** [comment]
I noticed the same problem on iPod 5. I... know it's an older device.
Using threejs v79. 
example lights / pointlights2 doesn't work for me either. It looks like mzlock's screen.
I tried getting rid of a few lights, and it seemed to make a difference.

On the same device, I also noticed that textured phong materials didn't seem to work with point lights. The mesh would only render if it didn't have a texture, or if directional lights were used instead.

**Comment by JavanLee** [comment]
- iphone 5c
- ios 8.3
- ME679CH/A

iphone 5c meet the same problem.
It seems that iphone 5 and some 5s also have the problem.
And if set side: THREE.DoubleSide, it will work well. But FPS become too low.

example webgl_lights_pointlights2:
![bad](https://cloud.githubusercontent.com/assets/15244665/19921847/b8d44d18-a11a-11e6-8594-21efc027651f.png)

set doubleSide:
```
var groundMaterial = new THREE.MeshPhongMaterial( { color: 0xffffff, map: texture,side:THREE.DoubleSide } );
var objectMaterial = new THREE.MeshStandardMaterial( { color: 0xffffff, roughness: 0.5, metalness: 1.0,side:THREE.DoubleSide } );
```
or
```
material.defines['DOUBLE_SIDED']=true;
```
it will work well:
![well](https://cloud.githubusercontent.com/assets/15244665/19921868/d664dc08-a11a-11e6-8130-36414dd5944c.jpg)

Hope this can be useful.

**Comment by EerikKivistik** [comment]
If anyone else happens on this issue, here's what worked for me:
I added a hemisphere light in addition to pointlights and the textures started rendering. 
The devices I tested were iPhone 5s and iPad 2.

**Comment by mrdoob** [comment]
@mzlock is this still an issue?

**Comment by Mugen87** [comment]
Closing. We can reopen if the mentioned rendering problems still occur with latest iOS.

**Comment by EerikKivistik** [comment]
I don't think it occurs on latest iOS versions, but people supporting legacy versions can use the workaround I described above.
