### ISSUE TITLE
Materials with same definitions should not result in separate programs in renderer...

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#9132]
This issue is a spin off from [issue 9123](https://github.com/mrdoob/three.js/issues/9123)

##### Description of the problem 

Materials with the same definition result in different renderer programs, where this should not happen. This leads to performance decrease. Example from [issue 9123](https://github.com/mrdoob/three.js/issues/9123) according to @WestLangley :

This may result in two programs because the material definitions are different:

````
var material1 = new THREE.MeshBasicMaterial( { map: null } );
var material2 = new THREE.MeshBasicMaterial( { map: texture } );
````

But this should not result in two programs because the definitions are the same:

````
var material1 = new THREE.MeshBasicMaterial( { map: texture } );
var material2 = new THREE.MeshBasicMaterial( { map: texture } );
````

I tried to reproduce this issue [in a fiddle here](https://jsfiddle.net/wilt/nhkv2qtk/) but I am not able to reproduce the above. Maybe @WestLangley could have a look and close the issue if all is fine.

**Comment by WestLangley** [comment]
@Wilt I was using this pattern:
```javascript
var loader = new THREE.TextureLoader();

var texture = loader.load( 'texture.jpg', function ( texture ) {

	texture.encoding = THREE.sRGBEncoding;

	if ( mesh1 ) mesh1.material.needsUpdate = true; // required. code added to prefixFragment
	if ( mesh2 ) mesh2.material.needsUpdate = true;

	render();

} );
```
and I only called `needsUpdate` on one of the materials. Hence, one shader had the extra prefix, and the other did not.

Apologies to you and @mrdoob for the noise. I now see no evidence of a bug. Closing.

**Comment by mrdoob** [comment]
Oh! So it's because the encoding gets added to prefixFragment?

**Comment by WestLangley** [comment]
You got it ! : - )
