### ISSUE TITLE
Possible Bug: Raycaster, and OrthographicCamera not correctly returning intersectObjects

### ISSUE THREAD

**Issue by karimbeyrouti** [mrdoob/three.js#9135]
##### Description of the problem 

Possible bug with Raycaster, and OrthographicCamera not correctly returning intersectObjects in some instances.

https://jsfiddle.net/karimbeyrouti/n4zdva5c/6/

1) In above JS fiddle, the plane turns green when a collision is detected (it is red otherwise)
2) Moving mouse on the plane detects a collision only on the top half of the plane.
3) Clicking on above JS fiddle changes the camera position (top down), no collisions are detected if camera Z position is negative.

##### Three.js version

- [?] Dev
- [ ] r77 <--- works
- [x] r78 <--- this is where there is a bug

##### Browser

- [ ] All of them
- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Internet Explorer (not tested)

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

(only tested on OSX - so not sure about the others)

**Comment by WestLangley** [comment]
Please use stackoverflow. For example http://stackoverflow.com/questions/17558085/three-js-orthographic-camera/17567292#17567292.

**Comment by karimbeyrouti** [comment]
Yes - however I am reporting what I think is a hug with the RayCaster. It works in all versions up to 0.78.0.

**Comment by WestLangley** [comment]
OK. Please see if you can remove obvious bugs in your example and simplify it by removing toggling. Thanks.

**Comment by karimbeyrouti** [comment]
Thank you - here is an updated fiddle: https://jsfiddle.net/n4zdva5c/9/ . 
Cleaned up - and could not spot any obvious bugs. 

`raycast.intersectObjects` fails when mouse is over the lower half of the plane - this works in every version of THREE.JS apart from 0.78.0.

**Comment by WestLangley** [comment]
>could not spot any obvious bugs.

Your orthographic camera is upside down. See the SO link above.

The near plane of your orthographic camera is behind the camera. See link.

Your orthographic camera has pixel units instead of world units. See link, but not related.

Study the SO post and try a non-negative near plane value.

**Comment by karimbeyrouti** [comment]
Interestingly enough - this is the issue:

When the camera has a negative near plane, it is not clipped by the frustum - however the `raycast` clips it which is why it fails. This demonstrates the issue: https://jsfiddle.net/karimbeyrouti/n4zdva5c/12/

as opposed to this: https://jsfiddle.net/n4zdva5c/9/ 
which has the bug - but does get frustum culled because of the negative near plane. 

In short: 

I am not sure whether this is a bug or not (it works in previous version 4 version of THREE.JS ). However I will update my code not have have a negative near plane - and move the camera back. Which should fix it. 

Thank you for your time.

**Comment by WestLangley** [comment]
>I am not sure whether this is a bug or not

It is not a three.js bug. `Raycaster` does not cast behind the camera, and your near plane should be in front of the camera.
