### ISSUE TITLE
THREE.Box3 intersectsBox not usable for testing Boolean operations

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#9137]
*This should be considered a feature request or enhancement*

##### Description of the problem (Three.js r78)

Te determine whether I have to perform boolean operations on two objects I use the `intersectsBox` method of the `THREE.Box3` class as follows:

````
// make bounding-box for mesh1
var box1 = new THREE.Box3().setFromObject(mesh1);

// make bounding-box for mesh2
var box2 = new THREE.Box3().setFromObject(mesh2);

var intersects = box1.intersectsBox(box2);

if( intersects ){
    //Perform boolean operation
}

````

The sad thing is that the `intersectsBox` method also returns `true` when the boxes are only touching eachother, but when the objects are only touching there is no need to perform any boolean operations. Would it be a possibility to change the `intersectsBox` method so it only returns `true` when one of the corners of the other box is actually inside the box (so not only when they are touching eachother).

Or would this break code on other places in the three.js library?

If such change is not possible would it be possible to add a second method for such functionality, or perhaps add an optional argument to the existing method so the user can choose what behavior is expected of the method.

##### Proposal

My proposal would be to change the method to:

	intersectsBox: function ( box ) {

		// using 6 splitting planes to rule out intersections.

		if ( box.max.x <= this.min.x || box.min.x >= this.max.x ||
				 box.max.y <= this.min.y || box.min.y >= this.max.y ||
				 box.max.z <= this.min.z || box.min.z >= this.max.z ) {

			return false;

		}

		return true;

	},

So with is equal `=` signs in the condition...

[Here a fiddle with an example and proposed code change](https://jsfiddle.net/wilt/secvpthh/)

**Comment by carstenschwede** [comment]
`THREE.Box3::intersectsBox` looks right to me. It should return true if both boxes overlap on at least one point in space.

Your options:
- use `THREE.Box3::expandByScalar` and shrink the boxes a little
- use `THREE.Box3::intersect` and check if `size.x * size.y * size.z > 0`

**Comment by Mugen87** [comment]
In terms of Computational Geometry: A touch is a so called "improper intersection" (see "Computational Geometry in C" by J O'Rourke Chapter 1.5.4. Boolean Intersection) and should be considered in `Box3. intersectsBox`. So IMHO it would be wrong to change the code in the suggested way. Besides, the behavior of other libraries is identical to three.js implementation (see https://github.com/juj/MathGeoLib/blob/master/src/Geometry/AABB.cpp#L942)

**Comment by Wilt** [comment]
@Mugen87 Okay, so changing this method is clearly not an option.
@carstenschwede Shrinking boxes is a terrible proposal, but I like your second idea. Thanks! :D 

Thanks for the feedback so far.

**Comment by Wilt** [comment]
Will close this issue... I will use `intersect` method and check for `result > 0` as @carstenschwede proposed...

**Comment by mrdoob** [comment]
https://github.com/mrdoob/three.js/issues/9146#issuecomment-226575250
