### ISSUE TITLE
Material Node Example Standard (PBR) on Safari

### ISSUE THREAD

**Issue by UX3D-kress** [mrdoob/three.js#9145]
##### Three.js version
- [ ] Dev
- [x] r78
- [ ] ...
##### Browser
- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [x] Safari
##### OS
- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
- [x] OSX
##### Hardware Requirements (graphics card, VR Device, ...)

iMac with Cuda enabled Nvidia Card

**Comment by projekthelden** [comment]
It seems that the problem appears when the environment cubemap is active. When I comment this line out the teapot is at least visible again:

					mtl.metalness = metalness;
					//mtl.environment = new THREE.CubeTextureNode( cubemap );
					mtl.normal = new THREE.TextureNode( grassNormal );

**Comment by sunag** [comment]
@projekthelden I see.. Here also is giving errors. I'll check it now.

**Comment by sunag** [comment]
https://github.com/mrdoob/three.js/pull/9180
