### ISSUE TITLE
Material shine through

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#9148]
##### Material shines through when zooming out (three.js r78)

When zooming out to a certain extend the material of objects behind other objects starts to shine through. It looks very similar to the effect when faces are overlapping (faces are in the same plane).

To demonstrate this I made [a fiddle](https://jsfiddle.net/wilt/8rv8cguL/).

In this example I draw two thin boxes (thickness 1 and there is a empty space between the boxes of 
also 1) so the boxes are not touching eachother but the material shines through anyway.

This screenshot demonstrates the effect:
![image](https://cloud.githubusercontent.com/assets/2419627/16113854/950b99a0-33be-11e6-97c6-0615908332ba.png)

This screenshot shows there is a space between the two geometries.
![image](https://cloud.githubusercontent.com/assets/2419627/16113917/f75d6c00-33be-11e6-98ab-d9e1d1dfbfb3.png)

When zooming the effect sometimes appears and sometimes disappears (it is also depending on zoom distance and the size of the screen).

I tried to play around with different material properties, but I seem to be unable to find any material setting that prevents this from happening. 

Is this a bug? Or a WebGL limitation? Or a general limitation in 3D graphics?
Or am I missing something and is this actually a material or renderer configuration mistake?

In my models this effect is really disturbing and ugly. Can I somehow prevent this from happening?

**Comment by WestLangley** [comment]
Increase you near plane value for better depth precision. And please use stackoverflow for help.

**Comment by Wilt** [comment]
@WestLangley Sorry, already thought that might happen after I posted. [here](http://stackoverflow.com/questions/37858464/material-shines-through-when-zooming-out-three-js-r78) it is. Thanks anyway. Maybe you can post the answer there then I'll accept it.
