### ISSUE TITLE
clearDepth options

### ISSUE THREAD

**Issue by jyunming-chen** [mrdoob/three.js#9161]
In order to estimate the thickness of a mesh, I set up two renderTargets for frontface and backface depth data. Convert the values in depth buffer to linear depths, and subtract back from front to get thickness.

In order to get the depth textures right, these should be set:
1. front depth texture: 
    material.side = THREE.FrontSide, 
    material.depthFunc = THREE.LessEqualDepth;
    clearDepth (1)  ... clear to far plane ... saw this in the code, but don't know how to set it
2. back depth texture: 
    material.side = THREE.BackSide, 
    material.depthFunc = THREE.GreaterEqualDepth;
    clearDepth (0)  ... clear to NEAR plane ... never see this in the code!!

Is this not supported in three.js?

a "working" jsfiddle is here: http://jsfiddle.net/jmcjc5u/n3yLfk8L/14/
here the test model is a convex ellipsoid. Thus, I don't need to change the settings of depthFunc and clearDepth. But for general concave models, I believe they should be changed.

##### Three.js version

- [x ] Dev
- [ ] r77
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by WestLangley** [comment]
Is `renderer.state.buffers.depth.setClear( value );` what  you want?

**Comment by jyunming-chen** [comment]
http://jsfiddle.net/jmcjc5u/dwbdkuyw/

contains two versions in animate()
1. uses gl = renderer.context, and openGL commands (glDepthFunc, glClearDepth)
2. three.js version: uses
  sphere.material.depthFunc = THREE.LessEqualDepth;  
  renderer.state.buffers.depth.setClear( 1 );

1. does work as I expected.
2. does not work and has weird consequence: 
  setClear(0) of backface cause the frontDepthTex to give wrong result ?!
  (comment off this line gives the correct result). 
   I wonder why...

**Comment by WestLangley** [comment]
I do not think either of your programs are correct. These seems to work.

```javascript
var gl = renderer.context;

sphere.material.side = THREE.FrontSide;
sphere.material.depthFunc = THREE.LessEqualDepth;  // default
renderer.state.buffers.depth.setClear( 1 );
renderer.render( sceneRTT, cameraRTT, frontDepthTex, true );
	
sphere.material.side = THREE.BackSide;
sphere.material.depthFunc = THREE.GreaterEqualDepth;
renderer.state.buffers.depth.setClear( 0 );
renderer.render( sceneRTT, cameraRTT, backDepthTex, true );

renderer.state.buffers.depth.setClear( 1 );
renderer.render( scene, camera );
```
And in your other program:
```javascript
gl.clearDepth( 1.0 );
gl.depthFunc( gl.LEQUAL );
renderer.render( scene, camera );
```

**Comment by jyunming-chen** [comment]
Thanks for pointing out this critical mistake

WestLangley <notifications@github.com> 於 2016年6月19日 星期日寫道：

> I do not think either of your programs are correct. These seems to work.
>
> var gl = renderer.context;
> sphere.material.side = THREE.FrontSide;sphere.material.depthFunc = THREE.LessEqualDepth;  // defaultrenderer.state.buffers.depth.setClear( 1 );renderer.render( sceneRTT, cameraRTT, frontDepthTex, true );
> sphere.material.side = THREE.BackSide;sphere.material.depthFunc = THREE.GreaterEqualDepth;renderer.state.buffers.depth.setClear( 0 );renderer.render( sceneRTT, cameraRTT, backDepthTex, true );
> renderer.state.buffers.depth.setClear( 1 );renderer.render( scene, camera );
>
> And in your other program:
>
> gl.clearDepth( 1.0 );gl.depthFunc( gl.LEQUAL );renderer.render( scene, camera );
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mrdoob/three.js/issues/9161#issuecomment-226975400>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHoXSJsADQPRrCX8aazxUF_Q4zij_s7Zks5qNKapgaJpZM4I4Ldg>
> .
>


-- 
俊銘- 從 Gmail 行動版傳送
