### ISSUE TITLE
multiplyQuaternions method

### ISSUE THREAD

**Issue by jspkiel** [mrdoob/three.js#9166]
I was trying random things in a code I have and I noticed that the .multiplyQuaternions ( a, b )  method allows for 3 arguments. I have the below statement:

    quat[1] = new THREE.Quaternion().multiplyQuaternions (quat[0], quat[1], quat[0].conjugate()).normalize();

and for some reason it produces results that seem to be meaningful for what I am trying to do, but I got no idea what it does since it is not the same as: 

    quat[1] = new THREE.Quaternion().multiplyQuaternions (quat[0], quat[1]).normalize();
    quat[1] = new THREE.Quaternion().multiplyQuaternions (quat[1], quat[0].conjugate()).normalize();

So, my question is, what is the .multiplyQuaternions(a,b,c) does?

**Comment by WestLangley** [comment]
>I was trying random things in a code I have and I noticed that the .multiplyQuaternions ( a, b ) method allows for 3 arguments.

It takes only 2 arguments.

If SO is not helpful to you, maybe you can try a math board.
