### ISSUE TITLE
Small problems with InterleavedBufferAttribute and non float array.

### ISSUE THREAD

**Issue by Dvad** [mrdoob/three.js#9177]
Hi,

First, thanks for this wonderful lib!

I just tried to use an interleaved buffer of the form.
... [3 float][4 uint8] ...
... [ x,y,z ] [r,b,g,_] ...
To display a raw pointcloud.
But I noticed some problem with the handling of InterleavedBufferAttribute in WebGLRenderers.

(1) The InterleavedBufferAttribute has no 'normalized' member: it is difficult to use non float array for - for instance - color attribute. 

(2) As the InterleavedBufferAttribute doesn't provide access to an 'array' member. (Which is a member of InterleavedBuffer though), the type of the array is always detected as gl_float in the function SetupVertexAttribute in WebGLRenderer. It breaks things, if it the BufferArray was defined with another type.

I tried with the r78 version. And didn't see changes related to this problem in the dev branch.

With small hacks fixing these two things on my local setup, I can use my interleaved buffer correctly without any copy in JS side. =)
Could you fix these things? I can provide a minimal patch. But I am not sure if it can break things, as I just started to look into the library.

David

**Comment by mrdoob** [comment]
> I can provide a minimal patch. But I am not sure if it can break things, as I just started to look into the library.

That would be very helpful! We can use it as reference.

**Comment by mrdoob** [comment]
> I can provide a minimal patch. But I am not sure if it can break things, as I just started to look into the library.

That would be very helpful! We can use it as reference.

**Comment by Dvad** [comment]
Done. I also provided a minimal example.

**Comment by mrdoob** [comment]
Thanks!
