### ISSUE TITLE
MTL textures not rendered on Android

### ISSUE THREAD

**Issue by Kelsopher** [mrdoob/three.js#9186]
##### Description of the problem

When I try to load OBJ+MTL model, both file are loaded according to js console but the mapping does not seems to happen. The model remains black on my Samsung Galaxy Tab4, an other android device  (I did not try on iOS because I don't have access to it)

The same reaction occurs with the example code provided at : http://threejs.org/examples/#webgl_loader_obj_mtl

here's the code of the loader, same as the previous link:

```
// load model obj + mtl
THREE.Loader.Handlers.add( /\.dds$/i, new THREE.DDSLoader() );
var mtlLoader = new THREE.MTLLoader();
mtlLoader.setPath( path );
mtlLoader.load( model.mtl, function( materials ) {
    materials.preload();
    var objLoader = new THREE.OBJLoader();
    objLoader.setMaterials( materials );
    objLoader.setPath( path );
    objLoader.load( model.obj, function ( body ) {
        scene.add( body );
    });
});
```
##### Three.js version
- [ ] Dev
- [x] r78
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [ ] IOS

**Comment by rhairston** [comment]
This also happens on my Samsung galaxy s6.

However, in a program that I have written that displays .obj and .mtl, It works.

I use r77 for that project and I also do NOT use:

THREE.Loader.Handlers.add( /\.dds$/i, new THREE.DDSLoader() );
nor do I use the setpath() function

since I do not have DDS files to accompany the MTL or OBJ, so my best guess is that the error is in one of those functions, or with dev (or r78)

**Comment by Kelsopher** [comment]
I removed THREE.Loader.Handlers.add( /.dds$/i, new THREE.DDSLoader() ); but the result is the same.

However I have to use the setpath() function because the files are on a server and if I removed this function, the load() function search in my local folder

I'll try with a previous version to see if it works

**Comment by rhairston** [comment]
My files are also grabbed from a server, but what I pass to MTLLoader and OBJL is the location with http: on front because at the core, all loaders call HTTP request if they need to
`
  var loader;

  if (this.texture.indexOf('.mtl') !== -1) {
    loader = new THREE.MTLLoader(manager);

    var obj = this.model;
    loader.load(this.texture, function (materials) {
      pointLight = new THREE.PointLight(0x00ff00, 1);
      controls.autoRotate = false;
      var textGeo;
      var material = new THREE.MultiMaterial([
        new THREE.MeshPhongMaterial({ color: 0xffffff, shading: THREE.FlatShading }), // front
        new THREE.MeshPhongMaterial({ color: 0xffffff, shading: THREE.SmoothShading }), // side
      ]);
      var text = 'Your model is loading';
      var height = 20;
      var size = 70;
      var hover = 30;
      var curveSegments = 4;
      var bevelThickness = 2;
      var bevelSize = 1.5;
      var bevelSegments = 3;
      var bevelEnabled = true;
      var font;
      var fontName = 'Open'; // helvetiker, optimer, gentilis, droid sans, droid serif
      var fontWeight = 'Regular'; // normal bold

      var loader = new THREE.FontLoader();
      loader.load('fonts/' + fontName + '_' + fontWeight + '.typeface.json', function (response) {
          font = response;
          textGeo = new THREE.TextGeometry(text, {
            font: font,
            size: size,
            height: height,
            curveSegments: curveSegments,
            bevelThickness: bevelThickness,
            bevelSize: bevelSize,
            bevelEnabled: bevelEnabled,
            material: 0,
            extrudeMaterial: 1,
          });
          textGeo.computeBoundingBox();
          var centerOffset = -0.5 * (textGeo.boundingBox.max.x - textGeo.boundingBox.min.x);
          camera.position.set(centerOffset * -1, 0, 0);
          pointLight.position.set(-75 * centerOffset, -4000, 0);

          textMesh = new THREE.Mesh(textGeo, material);
          textMesh.position.set(0, 0, -1 * centerOffset);
          textMesh.rotation.y = Math.PI / 2;
          scene.add(pointLight);
          scene.add(textMesh);
        });

      materials.preload();
      var objLoader = new THREE.OBJLoader(manager);
      objLoader.setMaterials(materials);
      objLoader.load(obj, function (object) {
          object.traverse(function (child) {
            if (child instanceof THREE.Mesh) {
              child.material.clippingPlanes = [];
            }
          });

          var bbox = new THREE.Box3().setFromObject(object);

          object.name = 'building';

          object.position.x -= Math.abs(bbox.min.x + bbox.max.x) / 2;
          object.position.z += (Math.abs(bbox.min.z) + Math.abs(bbox.max.z)) / 2;

          scene.add(object);
         //more code augmenting object
        }, onProgress, onError);
    }, onProgress, onError);
`

**Comment by Kelsopher** [comment]
I tried with your code but now even the web onPC isn't working
I get this error from the JS console : 
```
> three.min.js:386 GET http://localhost/project/texture.png 404 (Not Found)
load	@	three.min.js:386
load	@	three.min.js:389
load	@	three.min.js:425
loadTexture	@	MTLLoader.js:468
createMaterial_	@	MTLLoader.js:393
create	@	MTLLoader.js:329
preload	  @	MTLLoader.js:297
(anonymous function) @ loaderOBJMTL.html:122
(anonymous function)	@	MTLLoader.js:36
(anonymous function)	@	three.min.js:385
OBJLoader: 275.029ms
```
the line 122 is : materials.preload();
the path passing into the loader looks like : https://myservername.com/folder1/folder2/folder3/filename.obj /.mtl

**Comment by rhairston** [comment]
I think the localhost web address needs the port number after it, i.e http://localhost:9000/project

Cool thing about local host, you can forget the web address part to begin and set

`this.material = '/projects/texture.png'`

and the server will get that. The only reason I'm saying this is because the top of your console has the GET error, but if that's not the issue, then I'd have re-look at my code to see what I'm doing

**Comment by Kelsopher** [comment]
Yes I know that but there's no line of code which use a localhost url path. That's why it's weird.
The texture png is located at the same folder as the mtl and obj files on the server but it's search in the localhost folder

**Comment by rhairston** [comment]
What are you using for the path? Could you post demo code so I can see how you're doing it?

**Comment by jonnenauha** [comment]
Have you resolved if this is and actual bug in three.js? Looks like you are having problems with the actual GET request for the asset prior to loading?

Also are you sure the Android device supports DDS textures, afaik not all mobile devices do. Also note the `setTexturePath` function if your textures are not located next to the .mtl https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/MTLLoader.js#L59-L76

**Comment by Mugen87** [comment]
Please post a question at the [forum](https://discourse.threejs.org/) if you still have problems with the loading process.
