### ISSUE TITLE
Touch Controls

### ISSUE THREAD

**Issue by mese79** [mrdoob/three.js#9189]
Hi
I just want to share my **Touch Controls** with you guys:
[http://mese79.github.io/TouchControls/](http://mese79.github.io/TouchControls/)
Beside mouse and keyboard events it works with touch events too, and also it has hit-testing and collusion detection.
Feel free to use it!

**Comment by rhairston** [comment]
These are great!

For some reason the raycasting is messed up, but I don't think that doesn't have to deal with the touch controls.

**Comment by mrdoob** [comment]
Nice!

**Comment by makc** [comment]
I left it loading in inactive tab and returned to TypeError: camera is undefined

Seconds after the scene appeared

**Comment by mese79** [comment]
Sorry it was demo hosting problem. i fixed it.
try it here: [touchcontrols](http://touchcontrols.kissr.com/)

**Comment by iqbalbalte** [comment]
@mrdoob Hi doob i am facing a problem during integrate a json array with canvas_geometry_terrain.html
I want to map my own data with terrain but its not working well. I want to make this object but its not working well.
![diffuser](https://cloud.githubusercontent.com/assets/7027162/19162686/570d8e9a-8c12-11e6-9384-497fbecda8e1.jpg)

I am using this array

![image](https://cloud.githubusercontent.com/assets/7027162/19162905/328da860-8c13-11e6-8ac4-d01dad58b25a.png)

Please give any suggestion how i can integrate this array 
Thanks

**Comment by makc** [comment]
what if you alter it to work a little better, and then repeat it again, few times? it should then work well. I sometimes do that, and it tends to help.

**Comment by Mugen87** [comment]
@mese79 The [three.js forum](https://discourse.threejs.org/) is a good place for posting your `Touch Controls`. There is a category `Showcase` you can use when you create a new `Topic`.

**Comment by MasterJames** [comment]
I notice the editor generated pages do nothing (are dysfunctional) in regards to touch. It would be great to see something like this properly integrated into the editor. In my mind if it doesn't work on mobile it's not usable. I guess I could post this in the forum as a separate issue and see what's up official today with this issue, maybe my version is dated etc. 'Force' is in a new spec for multi touch so that should be noted as well.

**Comment by mrdoob** [comment]
@MasterJames Don't you think that's a little bit off-topic..? Maybe create a new issue/feature request?

**Comment by MasterJames** [comment]
Yes sorry. Recalculating.On Nov 22, 2017 12:01 AM, "Mr.doob" <notifications@github.com> wrote:@MasterJames Don't you think that's a little bit off-topic..? Maybe create a new issue/feature request?
