### ISSUE TITLE
fbx import problem 

### ISSUE THREAD

**Issue by picacure** [mrdoob/three.js#9191]
##### Description of the problem 

(This is NOT a help site. Please read the guidelines above before posting.)

Do u guys have plan to support binary fbx ??

##### Three.js version

- [ ] Dev
- [x ] r77
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by rhairston** [comment]
#5524

**Comment by picacure** [comment]
cool
