### ISSUE TITLE
EnvMap TexelToLinear Issue

### ISSUE THREAD

**Issue by EvanDElia** [mrdoob/three.js#9194]
I am currently using r78 and am trying to use refraction. The problem seems to be in setting the envMap for my MeshBasicMaterial. I had the following code working fine on my local machine but when I use local host to run the code all of a sudden I am getting this weird error that says "fragment ERROR: 0:309: 'envMapTexelToLinear' : no matching overloaded function found 
ERROR: 0:309: 'assign' :  cannot convert from 'const float' to 'highp 4-component vector of float'"

This is all of my code:

`if ( ! Detector.webgl ) Detector.addGetWebGLMessage();

            var container;

            var camera, scene, renderer;

            var mesh, lightMesh, geometry;

            var mouseX = 0, mouseY = 0;
            var glass;

            var windowHalfX = window.innerWidth / 2;
            var windowHalfY = window.innerHeight / 2;

            document.addEventListener( 'mousemove', onDocumentMouseMove, false );

            var loader = new THREE.OBJLoader( ).load('media/warped_glass_3.obj', function( object ){
                glass = object;
                init();
                animate();
            });
            

            function init() {

                container = document.createElement( 'div' );
                document.body.appendChild( container );

                camera = new THREE.PerspectiveCamera( 60, window.innerWidth / window.innerHeight, 1, 100000 );
                camera.position.z = 1300;

                scene = new THREE.Scene();
                scene.background = new THREE.TextureLoader()
                    .load( 'media/brule-background.png' );

                var geometry = new THREE.SphereBufferGeometry( 100, 32, 16 );

                var textureCube = new THREE.CubeTextureLoader();
                textureCube.load( [ 'media/brule-background.png', 'media/brule-background.png', 'media/brule-background.png', 'media/brule-background.png', 'media/brule-background.png', 'media/brule-background.png' ] );
                textureCube.mapping = THREE.CubeRefractionMapping;

                var material = new THREE.MeshBasicMaterial( { color: 0xffffff, envMap: textureCube, refractionRatio: 0.95 } );

                glass.traverse( function ( child ) {
                if ( child instanceof THREE.Mesh ) {
                    child.material = material;
                }
                } );
                scene.add(glass);
                glass.scale.x = glass.scale.y = glass.scale.z = 2000;
                glass.z = 0;

                //

                renderer = new THREE.WebGLRenderer();
                renderer.setPixelRatio( window.devicePixelRatio );
                renderer.setSize( window.innerWidth, window.innerHeight );
                container.appendChild( renderer.domElement );

                //

                window.addEventListener( 'resize', onWindowResize, false );

            }

            function onWindowResize() {

                windowHalfX = window.innerWidth / 2,
                windowHalfY = window.innerHeight / 2,

                camera.aspect = window.innerWidth / window.innerHeight;
                camera.updateProjectionMatrix();

                renderer.setSize( window.innerWidth, window.innerHeight );

            }

            function onDocumentMouseMove(event) {

                glass.rotation.y += 0.004;
                glass.rotation.x += 0.002;
                glass.rotation.z += 0.002;
                camera.rotation.z += 0.002;

            }

            //

            function animate() {

                requestAnimationFrame( animate );

                render();

            }

            function render() {
                glass.rotation.y += 0.001;

                camera.lookAt( scene.position );

                renderer.render( scene, camera );

            }
`

**Comment by EvanDElia** [comment]
The problem ended up being that I needed to load the texture before calling init because the textures weren't loading fast enough across the network before renderer.render() was called. On my local machine the texture were loading fast enough which is what led to my confusion. Lesson learned, always preload textures and obj files

**Comment by WestLangley** [comment]
You are assigning a `CubeTextureLoader` as the environment map.

    var textureCube = new THREE.CubeTextureLoader();

Consequently, your code should not work under any conditions.

**Comment by pailhead** [comment]
i searched and cant find the definition of this function. @WestLangley can you please post a link?

**Comment by WestLangley** [comment]
@pailhead If you think there is a three.js bug, see if you can file a bug report with a simple live example that demonstrates the issue.

**Comment by pailhead** [comment]
If i thought that there was a bug, i would file a bug report with a simple live example :)

this is different, i think it's not documented enough. I'm not entirely sure if i understand what is going on here. These functions wont get injected until a material actually has a map that needs this?
