### ISSUE TITLE
Manual frame submission for VREffect.render()

### ISSUE THREAD

**Issue by wizgrav** [mrdoob/three.js#9197]
##### Description of the problem 

In VREffect.render() the canvas is always submitted to the hmd after drawing. This is problematic if post processing is desired and thus a renderTarget used for the rendering instead of the default framebuffer. The canvas will be submitted but it will be empty. An option is needed to instruct render() not to submit.

##### Three.js version

- [x] Dev
- [ ] r77
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
#9198

**Comment by mkeblx** [comment]
This can be closed with #9198 now merged.
