### ISSUE TITLE
Blender exporter does not honor Export: false when custom props export not selected

### ISSUE THREAD

**Issue by dherben** [mrdoob/three.js#9201]
The ThreeJS exporter adds an Export checkbox for each object. Unchecking this has no effect if 'Custom props' is not selected in the exporter.

I realize that this is because the checkbox really translates to a THREE_export custom prop, but the two functionalities should not necessarily be linked.
##### Three.js version
- [X] Dev
- [X] r77
- [X] r76

Blender version 2.77
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
