### ISSUE TITLE
glTFLoader issues with models that contain over 60k vertices

### ISSUE THREAD

**Issue by lyaunzbe** [mrdoob/three.js#9205]
r77

I'm trying to use the glTFLoader to load in a glTF files (converted from obj) that can be around ~100k vertices, or more, where the indices need to be stored as integers instead of shorts. It seems however that the way in which the loader is build only supports a limited amount of vertices (https://github.com/AnalyticalGraphicsInc/OBJ2GLTF/issues/12#issuecomment-228239008).

<img width="772" alt="screen shot 2016-06-23 at 5 55 07 pm" src="https://cloud.githubusercontent.com/assets/28675/16326731/04b0dc38-397e-11e6-926b-0d30d6f7d8fd.png">
<img width="548" alt="screen shot 2016-06-23 at 5 51 41 pm" src="https://cloud.githubusercontent.com/assets/28675/16326856/34be8668-397f-11e6-97a3-d73369e5a42a.png">
line 237 in glTFLoaderUtils.js

The `componentType` in this case is an `UNSIGNED_INT`, which isn't being handled at the moment.

Any guidance or help would be much appreciated if possible! Thank you!

cc @tparisi

**Comment by mrdoob** [comment]
Have you tried with the new `GLTFLoader`?
https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/GLTFLoader.js

**Comment by lyaunzbe** [comment]
@mrdoob thank you for pointing me to that. after adding int to component types, `5125: Uint32Array` (https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/GLTFLoader.js#L100), my model loaded successfully!

**Comment by mrdoob** [comment]
@lyaunzbe Thank you for patch!
