### ISSUE TITLE
UV mapping on convex geometry skewed on z-axis

### ISSUE THREAD

**Issue by verteAzur** [mrdoob/three.js#9209]
When a simple 4 vertices plane is created with the convex geometry modifier, the UVs mapping are not working while using the z axis. If you look at the cube in the example http://threejs.org/examples/webgl_geometry_convex.html, you will see only 2 sides have the proper UVs mapping rendering, the other sides have skewed UVs.

![convexgeo](https://cloud.githubusercontent.com/assets/3125827/16336949/03d68dbe-3a12-11e6-855d-6bb993c8e596.gif)

latest r77 Three.js version
Browser All of them

**Comment by WestLangley** [comment]
I think the UVs should be removed from `ConvexGeometry`.

See the discussion in #1841.

**Comment by mrdoob** [comment]
@WestLangley Sounds good to me.

**Comment by WestLangley** [comment]
@verteAzur Thanks for the motivation!

**Comment by ipbebnev** [comment]
How to add texture to one edge of convex geometry mesh? Can somebody write code example? 
For base we can get that: http://jsfiddle.net/cwoodall22/bk3qx8ys/
