### ISSUE TITLE
View source button on examples while not online

### ISSUE THREAD

**Issue by verteAzur** [mrdoob/three.js#9210]
The view source button on the examples works fine if you are online. We are developing via a closed network for security purpose and all the "View Source" buttons are not working. We have to manually change the url and access the example without the side navigation and apply a browser view source to look at the example. It used to work on versions prior r75.

#### Three.js version
r75, r76, r77
##### Browser
- [x] All of them
##### OS
- [x] All of them

**Comment by WestLangley** [comment]
Ref: https://github.com/mrdoob/three.js/issues/8170

**Comment by mrdoob** [comment]
Yep, #8170 explains why...
However... You can middle click in the example name so it opens in a new tab and view source there...
