### ISSUE TITLE
Showcase: Three.js based voxel editor

### ISSUE THREAD

**Issue by pawsong** [mrdoob/three.js#9211]
Hi there! Let me introduce [Buffy](https://buffy.run/model/edit?files=576ba0896810bc00001fa1f7), my work based on three.js. This is a fun voxel editor and actually a serious fork of three.js example [http://threejs.org/examples/#webgl_interactive_voxelpainter](http://threejs.org/examples/#webgl_interactive_voxelpainter). If you like cute 3D things, please feel free to enjoy ;)

Without the efforts of you three.js guys to this great library, I couldn't have done this job. Thank you so much!

<a target="_blank" href="https://buffy.run/model/edit?files=576ba0896810bc00001fa1f7">
![screen shot 2016-06-24 at 9 00 00 pm](https://cloud.githubusercontent.com/assets/2945463/16337315/76712ca2-3a4f-11e6-8131-6c95b5666dfb.png)
</a>

**Comment by tentone** [comment]
Pretty cool =D i love to see tools that allow creative minds, congratz

**Comment by thmasn** [comment]
really neat tool. completely smooth. although the possible size is quite small imo

**Comment by pawsong** [comment]
@tentone Your kind words helps me a lot! Thanks :)

**Comment by pawsong** [comment]
@thmasn Good point. I've added shortcut for switching tools like pen and eraser.
