### ISSUE TITLE
github.io links no longer work in fiddles

### ISSUE THREAD

**Issue by makc** [mrdoob/three.js#9218]
just heads up, urls like https://mrdoob.github.io/three.js/build/three.min.js now redirect to http(no s)://threejs.org/build/three.min.js so you either need to put some fork url there, or cdn

**Comment by mrdoob** [comment]
Uh...

**Comment by mrdoob** [comment]
`//cdn.rawgit.com/mrdoob/three.js/master/build/three.min.js` FTW

**Comment by makc** [comment]
ok, just in case you come across broken fiddles

**Comment by mrdoob** [comment]
Yep. Thanks for pointing it out!
