### ISSUE TITLE
editor transparecy sorting issues / alpha blends to clear color

### ISSUE THREAD

**Issue by thmasn** [mrdoob/three.js#9226]
##### Description of the problem 

im using a plane with a Gradient texture which is directed to the camera via script
in some view angles, the transarency blends to the Background instead of the underlying objects.

Looks to me like a sorting issue, or do i Need to update sth to have this work correctly?
[https://youtu.be/1cbhtVFC4wo](https://youtu.be/1cbhtVFC4wo)

##### Three.js version

- [ ] Dev
- [x] r78
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Nice looking scene!

Until we add `renderOrder` to the Object properties panel, you could hack it by adding this via script:

```js
floor.renderOrder = 1; // or -1
```

**Comment by thmasn** [comment]
thank you, that fixes the floor problem

as the different smoke planes still dont clip correctly, do i need to recalculate the order each frame? is there a way to do this automatically based on the distance to the camera?

**Comment by WestLangley** [comment]
@thmasn Do not sort. Try setting `material.alphaTest = 0.5`. Actually, if you want help, use stackoverflow and link to a live example to demonstrate the issue. Nice video, though!

**Comment by thmasn** [comment]
> use stackoverflow and link to a live example to demonstrate the issue.

thanks ill do that. i thought it was some kind of bug, but if it works as youd expect, i guess the problem is on my side

**Comment by mrdoob** [comment]
You may want to read on transparency and depth buffers some day. It will help to understand why this behaves like this.
