### ISSUE TITLE
Benchmark of different use cases 

### ISSUE THREAD

**Issue by sjfricke** [mrdoob/three.js#9233]
##### Description of the suggestion 

I have been using Three.js for a while now and when I start working on projects with other people I start to question if doing it "this way or that way" is something that could save me a few extra FPS or if I am over micromanaging... My question is if there is already a set of benchmarks of taking normal operations and running them thousands of times and see which way is truly more optimized. If there isn't I would love to be part in creating this database of information.

##### Three.js version

- [x] r78

##### Browser

- [x] All of them

##### OS

- [x] All of them

**Comment by mrdoob** [comment]
I think what you are describing is part of the experience of learning. There are many different benchmarks that would be needed.

However, would be great to see the ones you put together and the results you get.
