### ISSUE TITLE
ExtrudeGeometry. Hole does not appears when its center x<0 and y<0.

### ISSUE THREAD

**Issue by v22884** [mrdoob/three.js#9239]
##### Description of the problem 

ExtrudeGeometry. Hole does not appears when its center x<0 and y<0.

##### Three.js version

- [ ] Dev
- [ x] r78
- [ ] ...

##### Browser

- [x] All of them
- [x ] Chrome
- [ x] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [x ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Do you mind creating a jsfiddle/test case that shows the issue?

**Comment by v22884** [comment]
['jsfiddle/test case that shows the issue'](http://ателье-уют.рф/three.js-master/3dissue.html)

Right ExtrudeGeometry must have hole:

Hole0.absarc( -123.11901504787967, -175.64979480164158, 92.40257240838781, 0, Math.PI*2, false );
Shape0.holes.push( Hole0 );

But....

**Comment by v22884** [comment]
it was necessary to INVERT DIRECTION of hole elements!!!
