### ISSUE TITLE
Curve/CurvePath inconsistency in getPoints vs getSpacedPoints

### ISSUE THREAD

**Issue by killroy42** [mrdoob/three.js#9240]
##### Description of the problem

It appears that the APIs are currently inconsistent. A shape with two curves in it will return 5 points with .getPoints(2), 2 segments for each sub-curve, but will only return 3 points with .getSpacedPoints(2).

Further, getPoints(2) will return the end-points of the sub-curves, plus an additional point in the middle, while .getSpacedPoints(5). will only return the endpoints of the whole curve (plus 3 points inbetween), but not the edge-point between the sub-curves. This creates in-consistent shapes that should be mirrored left-right, for example from this code:

```
var shieldShape = new THREE.Shape();
shieldShape.moveTo( 0, 20);
shieldShape.bezierCurveTo(  5,  15,  15,  16,  20,  16);
shieldShape.bezierCurveTo( 20,  10,  15, -16,   0, -20);
shieldShape.bezierCurveTo( -5, -16, -15, -16, -20,  16);
shieldShape.bezierCurveTo(-15,  16,  -5,  15,   0,  20);
```

I am not sure if this is by design. Perhaps we could add a flag, as I am not sure what the preferred API is. I will work around by iterating over the sub-curves and calling getSpacedPoints on each and re-joining the resultant paths.
##### Three.js version
- [ ] Dev
- [x ] r78
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by killroy42** [comment]
My beziers were off, so that's nothing. I've created a method that hits the corner points and then distributes the remaining segments equally. This could be added to the existing methods with a boolean argument, or as a separate method.

**Comment by zz85** [comment]
Some what relates to https://github.com/mrdoob/three.js/pull/9168#issuecomment-227818150

@killroy42 would that answer your question?

**Comment by killroy42** [comment]
Close enough. I basically came to the same conclusion. For example I would like to use the CurvePath properties to assign "smoothing groups" via vertex normals, to smooth the curves but create sharp edges between them. Or use a tangent threshold to determine when something should appear smoothed, and when sharp. As you can see, for my extrusion application, I want the outer edge to appear round, but the bevel edges to appear sharp.
