### ISSUE TITLE
Could we get a THREE.Sprite billboard axes parameter?

### ISSUE THREAD

**Issue by OtterFamily** [mrdoob/three.js#9241]
Sorry if this is the wrong spot/format for a request, but I was just wondering if it would be possible to get some parameter that could be passed along to THREE.Sprite to specify along which axis an image will turn to face the camera?

There are certain cases where you might want only Y axis alignment, but no Z or X axis alignment for example.

Something like:

```

var axes = new THREE.Vector3(0,1,0);

var mySprite = new THREE.Sprite(material);
mySprite.billboardAxes = axes;
```

or

```
var mySprite = new THREE.Sprite(material);
mySprite.billboard.x = false;
mySprite.billboard.y = true;
mySprite.billboard.z = false;
```

Sorry if this is something that has been/is being implemented already, I just couldn't find it in the documentation, and I thought it could be helpful.

Thanks!

**Comment by Mugen87** [comment]
I vote to not add this feature to `Sprite`. A sprite in computer graphics is normally a billboard parallel to the screen (a so called _screen-aligned billboard_). It's surface normal is the negation of the view plane's normal.

There are other types of billboards like _axial billboards_ which rotate around some fixed world space axis. I would not mix such functionality with `Sprite`.
