### ISSUE TITLE
Chainable path methods (suggestion)

### ISSUE THREAD

**Issue by killroy42** [mrdoob/three.js#9245]
If this isn't the right place to discuss suggestions, please delete.

I think a lot of path/shape code will like something like:

```
 shape.moveTo(x0, y0);
 shape.lineTo(x1, y1);
 shape.lineTo(x2, y2);
...
```

with a chainable interface (i.e. return this) we could get:

```
shape
  .moveTo(x0, y0)
  .lineTo(x1, y1)
  .lineTo(x2, y2);
...
```

It's a matter of taste, but it's easy to support both.

I'm happy to prepare a PR.

**Comment by mrdoob** [comment]
Sounds good to me!
