### ISSUE TITLE
add scaling to CSS2DRenderer

### ISSUE THREAD

**Issue by gpolyn** [mrdoob/three.js#9246]
Per [stackoverflow.com/questions/38064275/how-to-express-pixel-width-in-three-js-world-space](http://stackoverflow.com/questions/38064275/how-to-express-pixel-width-in-three-js-world-space), I request enhancement at [examples/js/renderers/CSS2DRenderer](https://github.com/mrdoob/three.js/blob/master/examples/js/renderers/CSS2DRenderer.js) to include scaling for any CSS2DObject. 

Relatedly, some facility for accomodating the CSS dimensions of a CSS2DObject in world space would be useful.

**Comment by mrdoob** [comment]
I guess the real issue is that currently we don't have a way to define the alignment of the element? We're currently doing `translate(-50%,-50%)`.

**Comment by gpolyn** [comment]
@mrdoob as is already likely evident from my linked SO post, I'm at a loss here, though I'll keep hacking at my example. 

I think, ideally, the CSS2DRenderer would deliver much of the same kind of behavior as sprites offer.

If anyone can think of useful references in `src` or `examples`, I'm eager to review, post back with a tentative strategy, and, depending, attempt the enhancement.

**Comment by mrdoob** [comment]
If I'm not misunderstanding your SO post, the issue is that the left side of your tags are not aligned to the cells, right?

**Comment by gpolyn** [comment]
I'm happy to keep the CSS alignment (center), or modify it with other settings for `CSS2DObject`. 

If my goal were to work from given world geometry, then I might use CSS `scale()` to fit my html to the world, likely, as a function of the projection matrix. 

Instead, I'm after a way to relate some given screen width, in CSS, to its corresponding world width. 

(I suspect this is too niche to merit general attention, now, so I'm prepared to close.)

**Comment by gpolyn** [comment]
Closing this, as I do not think it will have wide interest. 

Appreciate any helpful comments (including at stackoverflow.com/questions/38064275/how-to-express-pixel-width-in-three-js-world-space.)

**Comment by mrdoob** [comment]
> Instead, I'm after a way to relate some given screen width, in CSS, to its corresponding world width.

I'm afraid I still don't understand the use case...

**Comment by gpolyn** [comment]
@mrdoob use case was 'Given the height and width of a `CSS2DObject` in NDC screen space, condition the world to fit the object, depending on its position in world space'. As few are likely to need to relate any other HTML element, the key application is positioning of CSS2D text labels in contexts where their size has meaning for their position in world space.

**Comment by roccapl** [comment]
I know this is old but,

I modified line 66:
`var style = 'translate(-50%,-50%) translate(' + ( vector.x * _widthHalf + _widthHalf ) + 'px,' + ( - vector.y * _heightHalf + _heightHalf ) + 'px)';
`
in

`var style = 'translate(-50%,-50%) translate(' + ( vector.x * _widthHalf + _widthHalf ) + 'px,' + ( - vector.y * _heightHalf + _heightHalf ) + 'px)  scale(' + camera.zoom + ', ' + camera.zoom + ')';`

effectively adding scaling to the CSS2DRenderer
