### ISSUE TITLE
Background/Explanation of MeshStandardMaterial is lacking

### ISSUE THREAD

**Issue by abelnation** [mrdoob/three.js#9247]
##### Description of the problem

Currently, MeshStandardMaterial does not refer to any background material nor contain any description of how it's shading functions differently from the other Material models.  `Standard` is not descriptive at all.  My understanding is that it is trying to move move in the direction of Physically Based Rendering, but it's not totally clear what the nuances of that shift might be.  

I'm happy to help update the docs, as I am working to integrate the Rect light work with the Standard Material, but either some background info, or pointers to good background materials would be helpful for me to do that.  
##### Three.js version
- [X] Dev

**Comment by abelnation** [comment]
e.g. I see a lot of concepts in common with UE4's description of their material model: http://blog.selfshadow.com/publications/s2013-shading-course/karis/s2013_pbs_epic_slides.pdf

**Comment by looeee** [comment]
@abelnation I've added a good bit of information to the MeshStandardMaterial, could you have a look at see if it is sufficient?

**Comment by Mugen87** [comment]
It seems to me that the documentation of [MeshStandardMaterial](https://threejs.org/docs/index.html#api/en/materials/MeshStandardMaterial) is good now. If devs looking for more technical insights, there are many links to external documentation/papers in the respective shader chunks.
