### ISSUE TITLE
Physically-based real-time subsurface scattering

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#9249]
##### Description of the problem

We should implement some type of standard sub-surface scattering algorithm.  I hacked somethig into Clara.io that does this but it is just a hack that doesn't have a true physical basis:

![happy buddha webgl sub-surface scattering](https://cloud.githubusercontent.com/assets/588541/16437672/d870cd20-3d76-11e6-8aae-b7e35c14ee9c.png)

https://clara.io/view/5c7d28c0-91d7-4432-a131-3e6fd657a042

My technique is a customization of this technique here, but it fairly unphysical or requires a lot of precomputation:

https://colinbarrebrisebois.com/2011/03/07/gdc-2011-approximating-translucency-for-a-fast-cheap-and-convincing-subsurface-scattering-look/
##### Three.js version
- [x] Dev
- [x] r78
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by bruno-quintela** [comment]
I think Matt DesLauriers has already extended the current MeshStandardMaterial in order to support fast subsurface scattering. 

More info on his technique and source code can be found here:

https://twitter.com/mattdesl/status/805784465725419520
https://gist.github.com/mattdesl/2ee82157a86962347dedb6572142df7c

**Comment by bhouston** [comment]
@mattdesl Sweet!  We should get this into a PR!

**Comment by bhouston** [comment]
@bruno-quintela The technique @mattdesl implemented is the same one I linked to above. :)  So this is perfect and fast.

**Comment by daoshengmu** [comment]
<img width="300" alt="screen shot 2018-03-02 at 1 54 49 pm" src="https://user-images.githubusercontent.com/1263177/36885787-0b9c4488-1e24-11e8-9666-e99328f95069.png">
Follow the approach from @@mattdesl. It looks like using a thickness map to define the translucent in surfaces for computing the diffuse reflectance. Is there any progress for now?

If we decide to adopt this approach, should we have a separate material from StandardMaterial?

**Comment by WestLangley** [comment]
>should we have a separate material from StandardMaterial?

I think so. You could start with adding an example using a `ShaderMaterial`. Or alternatively, extend `StandardMaterial` similar to `ToonMaterial`.

**Comment by daoshengmu** [comment]
<img width="300" alt="screen shot 2018-03-07 at 3 09 11 am" src="https://user-images.githubusercontent.com/1263177/37052671-f163ecb2-21b4-11e8-8065-8a3e832299f4.png">


Updating the progress of point lights support. It is very close to send a PR.  Currently, I decide to create a MeshTranslucentMaterial extends MeshStandardMaterial.

**Comment by mrdoob** [comment]
Nice!
