### ISSUE TITLE
Anisotropic (and rotated anisotropic) reflections that work with IBL / PMREM

### ISSUE THREAD

**Issue by bhouston** [mrdoob/three.js#9250]
##### Description of the problem

We should probably implement in the core of ThreeJS anisotropic reflections and anisotropy rotation.  I've implemented this in Clara.io but only for direct lights, not the PMREM filtered IBL indirect lights.

It would be cool to have anisotropy that works with IBL PMREM results -- although I understand that this may require pre-calculated anisotropic PMREM which we currently do not have, or PMREM filtering is only isotropic.

My implementation produces results that looks like this:

![cooking pot ggx anisotropic metallic](https://cloud.githubusercontent.com/assets/588541/16437735/4a64d804-3d77-11e6-8f02-ebe2cb0ff7e0.png)

https://clara.io/view/a8b929e6-c703-47ff-a85d-44bc44e5a132
##### Three.js version
- [x] Dev
- [x] r78
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by bhouston** [comment]
The solution to this is "bend normals."

**Comment by bhouston** [comment]
Myself and https://github.com/Threekit are pleased to put a bounty of $250 USD on an accepted PR of a full implementation of bent normals for anisotropy with environment maps.  A really good reference implementation and explanation is in the Filament code base: https://google.github.io/filament/Materials.html#materialmodels/litmodel/bentnormal

**Comment by danyjf** [comment]
Hey, I was looking at this problem and I have some questions on how it is supposed to be implemented. 
Is this supposed to be an option on a material to add an anisotropic map or is it supposed to be a new material like "anisotropic material"?

**Comment by Mugen87** [comment]
Ideally, it is added to `MeshPhysicalMaterial` similar to clear coat, sheen or transmission.

**Comment by Mugen87** [comment]
This is fixed since `r153` :tada:!
