### ISSUE TITLE
Support for the gltf .glb file loading via the new GLTFLoader

### ISSUE THREAD

**Issue by SrinivasPrabhu794** [mrdoob/three.js#9255]
##### Description of the problem

We are converting our collada models to gltf .glb files but there does not seem to be a support for them in the current r78 version.
Currently the GLTFLoader only supports embedded uris. Can this feature be added?
##### Three.js version
- [ ] Dev
- [x] r78
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by cx20** [comment]
I also hope that the .glb file will be supported.

I tried some other glTF Loader and it seems that Babylon.js, Cesium.js, GLBoost correspond to the .glb format.
See: https://cx20.github.io/gltf-test/

**Comment by donmccurdy** [comment]
This will need some more testing and cleanup, but I have `.glb` support in progress now:

https://github.com/mrdoob/three.js/compare/dev...donmccurdy:feat-binary-gltf?w=1
