### ISSUE TITLE
THREE.SpriteMaterial visible false not working

### ISSUE THREAD

**Issue by Wilt** [mrdoob/three.js#9257]
##### Description of the problem (three.js r78)

I can set `visible = false` for the material on objects (meshes/lines), so that these objects are hidden, but they will still work for raycasting. I wanted to do the same for sprites, but the `visible` property for `THREE.SpriteMaterial` does not work as expected; when setting it to false the sprite is still visible.

[Here is a fiddle to demonstrate this](https://jsfiddle.net/wilt/8psb5y92/)

**Comment by mrdoob** [comment]
Fixed. Thanks!

**Comment by Timon0305** [comment]
thanks, this is working fine, 

So how can we make round particles in vue three.js?
