### ISSUE TITLE
#9192 Breaks all Skeletal Animations

### ISSUE THREAD

**Issue by titansoftime** [mrdoob/three.js#9258]
This issue is related to the recent push to 79dev.

Prior to #9192: http://jsfiddle.net/titansoftime/n6apnj3z/ (still has unrelated bug from #9056)

With #9192: http://jsfiddle.net/titansoftime/bux59dw9/

##### Three.js version

- [x] Dev
- [ ] r78
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by bhouston** [comment]
I think we have to un-merge the PR that is causing this.

**Comment by mrdumb** [comment]
> This issue is related to the recent push to 79dev. 

THREE.WebGLRenderer 79dev
TypeError: b[a[h].parent] is undefined
.parseAnimation()

**Comment by mrdoob** [comment]
#9263
