### ISSUE TITLE
Can mesh  add eventListener?

### ISSUE THREAD

**Issue by df257** [mrdoob/three.js#9260]
like this:

```js
var sphere=new THREE.Mesh(geo,mat);
sphere.addEventListener('click',function(){
	alert(1);	
},false);
```

**Comment by indif** [comment]
Yes, Mesh is inherite from EventDispatcher. But you should call dispatchEvent somewhere to fire that event.

**Comment by Jassem** [comment]
> Yes, Mesh is inherite from EventDispatcher. But you should call dispatchEvent somewhere to fire that event.

Thanks for your reply, but where to call dispatchEvent ?

**Comment by Mugen87** [comment]
You would do it like so:
```js
sphere.dispatchEvent( { type: 'click' } );
```
However, the initial code of the OP does not do what beginners might expect. You don't make a mesh clickable that way.
