### ISSUE TITLE
Pixeldeviceratio on Postprocessing examples

### ISSUE THREAD

**Issue by throni3git** [mrdoob/three.js#9266]
##### Description of the problem

While in chrome using the possibility to emulate mobile devices with pixelDeviceRatio != 1 everything works, i'm getting coarse image quality for the postprocessing examples like 

http://threejs.org/examples/#webgl_postprocessing_taa
http://threejs.org/examples/#webgl_postprocessing_msaa_unbiased

I played with setPixelRatio and stuff, but none helped to get an appropriate rendering. Since a project of mine is heavily relying on these antialiasing processes, i'd like to figure out why this is rendering strange...

![screenshot_20160701-154742](https://cloud.githubusercontent.com/assets/14586717/16527279/29003b9a-3fb6-11e6-824d-a3c31ecbd2ce.png)
##### Three.js version
- [ ] Dev
- [ x ] r78
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ x ] Android
- [ x ] IOS

**Comment by mrdoob** [comment]
`WebGLRenderTarget` doesn't support `pixelRatio`.

There is been some talks about implementing that recently...

https://github.com/mrdoob/three.js/commit/7e47e4163b0af042d746f212f873a350211badff

**Comment by Mugen87** [comment]
Solved via #16404
