### ISSUE TITLE
r78 findings and "three.webglrenderer.setTexture2D: don't use render targets as textures. Use their .texture property instead." warning

### ISSUE THREAD

**Issue by verteAzur** [mrdoob/three.js#9267]
##### enhancements/findings

> warning: three.webglrenderer.setTexture2D: don't use render targets as textures. Use their .texture property instead.

I have found the line that needed the "renderTarget.texture" update. It was located in the render member function of the THREE.ShaderPass.prototype. I did make the change, but the warning was still triggering. Then, I've decided to update all postprocessing classes and shaders (Convolution, Copy,Effectcomposer, Shaderpass, Maskpass, RenderPass, Bloompass, FilmPass) and it did work like a charm. Everything is working without any warning nor error. 

We did notice a few things while going through the update process that might help others:

When there is an if statement with a 1 liner, it is common to not use brackets for ease of reading and faster coding. It is in fact ok, if one don't use an optimizer or/and a security obfuscator. e.i. the following line: 
```javascript
if(false) dothis1();
dothis2();

becomes:
if(false)dothis1();dothis2();
```
and dothis2(); never gets called

Another important note are double quotes versus single quotes in code examples, classes, and libs. I have seen the usage of both single & double quotes for string in examples. It is working in both situation, but I would recommend to use a standard way to apply them for strings and hash key names. If a choice needs to be made, the single quote is the preferred choice, because when javascript is used with server side scripting/coding like JAVA for example, the double quote makes it more difficult to read and debug and the server side does not have the flexibility javascript has with strings writing and allows solely for double quotes. That way, when one uses single quotes on a server side string, it is very quick and easy to identify which part is ran on which side (server vs client side).

For last, while updating the blooming shader, I have noticed the removal of 2 powerful shaders: the THREE.HorizontalTiltShiftShader and the THREE.VerticalTiltShiftShader. Is there a particular reason for these removals? 

Note: we have both of them working via version r78 on our dev sandbox, if you need an example that uses them we can help you with that...

This is it, thank you for all!

##### Three.js version
- [x] r78

##### Browser
- [x] All of them

##### OS
- [x] All of them

**Comment by mrdoob** [comment]
> For last, while updating the blooming shader, I have noticed the removal of 2 powerful shaders: the THREE.HorizontalTiltShiftShader and the THREE.VerticalTiltShiftShader. Is there a particular reason for these removals?

Uh? I still see them there...

https://github.com/mrdoob/three.js/blob/master/examples/js/shaders/HorizontalTiltShiftShader.js
https://github.com/mrdoob/three.js/blob/master/examples/js/shaders/VerticalTiltShiftShader.js

**Comment by mrdoob** [comment]
> When there is an if statement with a 1 liner, it is common to not use brackets for ease of reading and faster coding.

Is this something we added to the code base?

**Comment by verteAzur** [comment]
>      
> 
> Uh? I still see them there...
> 
> https://github.com/mrdoob/three.js/blob/master/examples/js/shaders/HorizontalTiltShiftShader.js
> https://github.com/mrdoob/three.js/blob/master/examples/js/shaders/VerticalTiltShiftShader.js

Yes, you are right. Sorry, I was looking at the "Dynamic Terrain" example, which used to use it. Sorry, I have generalize the thing a little prematurely. It is in fact used in 2 other examples (marching cube, and material cube map).

**Comment by verteAzur** [comment]
> When there is an if statement with a 1 liner, it is common to not use brackets for ease of reading and faster coding.
> 
> Is this something we added to the code base?

It has always been this way as far as I can remember. We have a routine now when we import  classes, that checks for no brackets on if statements.  It is more a suggestion to keep in mind for future development/update.

**Comment by makc** [comment]
> if(false)dothis1();dothis2();
> and dothis2(); never gets called

wtf. [that is not how it works.](https://jsfiddle.net/3nd5xe3o/)

**Comment by mrdumb** [comment]
> When there is an if statement with a 1 liner, it is common to not use brackets for ease of reading and faster coding.

In fact that's lazy (read "bad") programming that works thanks to a buggy compiler.

**Comment by makc** [comment]
are you all on drugs here

**Comment by verteAzur** [comment]
> that is not how it works.

I should have mentioned, the code syntax is checked on the server side with mozilla.javascript.parser

**Comment by verteAzur** [comment]
Re: the bracket suggestion was by no mean there to open up a can of warms and make anyone angry. It was just an FYI. This post explains the suggestion better than I can: http://stackoverflow.com/questions/2125066/is-it-bad-practice-to-use-an-if-statement-without-brackets

**Comment by makc** [comment]
@verteAzur 
> if you go back and add a second statement to the if or else clauses without remembering to add the curly braces, your code will break in unexpected and amusing ways.

finally something that makes sense, thanks :)
