### ISSUE TITLE
Matrix3/Matrix4 constructor or setter taking JS array

### ISSUE THREAD

**Issue by unphased** [mrdoob/three.js#9281]
##### Description of the problem

It's often the case that for purposes of clarity or convenience or data ingestion, values for Vectors and Matrices originate in JS array of numbers form, e.g. `[0, 1, 2]`.

We currently have to do some bending over backwards to do something like initialize e.g. a Matrix3 using the API... The constructor sets it to identity and then we have to call a setter with 9 arguments to set it!

Since the constructor allocates a `[1, 0, 0, 0, 1, 0, 0, 0, 1]` JS array just to pass it to the Float32Array anyway why can't we have the constructor take an optional array here? Is it written this way for maximum efficiency so we want to avoid checking the length of the array or something?

I would say at least provide a SetFromArray method that we can use. For the time being perhaps I might write this: 

```
var mat = new THREE.Matrix3();
mat.elements = new Float32Array(myVectorOf9Numbers);
```

This is quite wasteful, allocating and cleaning up JS array of numbers (identity matrix in the ctor)! 

(caveat: I'm not actually terribly familiar with Typed Arrays so I suppose I can do something smarter by calling set with mat.elements and then it's mostly performant.)
##### Three.js version
- [ ] Dev
- [ ] r78
- [x] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Linux
- [ ] Windows
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Sounds good to me.

**Comment by mrdoob** [comment]
Would something like this work?

```js
THREE.Matrix4 = function ( array ) {

	if ( array === undefined ) array = [ 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 ];

	this.elements = new Float32Array( array );

};
```

Or do you want to pass the TypedArray directly?

**Comment by unphased** [comment]
Yes, your code sample you posted I think is a clear and simple way to do this. Now we can set the contents with the constructor in one step.

**Comment by WestLangley** [comment]
We have to be careful, here. `Matrix4.set()` takes elements in row-major order. It is done that way so the code is human-readable.
```javascript
matrix.set( 1.0, 0.0, 0.0, 0.5,
            0.0, 1.0, 0.0, 0.6,
            0.0, 0.0, 1.0, 0.7,
            0.0, 0.0, 0.0, 1.0 );
```
What you are proposing here involves specifying array elements in column-major order.

```javascript
var matrix = new THREE.Matrix4( array );
```

It may be OK, as long as the docs and code are _very_ clear... but personally, I am not liking it due to the potential for user confusion.

**Comment by gvsro** [comment]
@WestLangley Hey, I am sorry to intrude on this topic, but you have no contact info on git or stack (even tho you said on twitter that you left stack). Can you please post your email on your git so I can contact you? I`ll delete this after. Sorry again @unphased @mrdoob

**Comment by unphased** [comment]
@WestLangley Very important distinction to make here for the Matrix types, thanks for clarifying!

I have no preference (w.r.t. row- or column-major) but indeed the docs need to clearly specify this, or we risk doing everybody a disservice

**Comment by GGAlanSmithee** [comment]
Another thing to consider is that [this](https://github.com/mrdoob/three.js/commit/141ad4f896e9e2004c6c0930137780993a05f858#diff-ec68f22f36a17164468f6175039b8dd8) commit removed previous constructor parameters and added a warning. Removing the warning will make it so that anyone upgrading from a (very) old version will not be informed that they are potentially passing the wrong arguments.

One way to make it a bit safer would be to keep the warning but instead have it warn on more than one arguments:

```javascript
if ( arguments.length > 1 ) {

    console.error( 'THREE.Matrix4: the constructor only reads one argument (matrix array). use .set() instead.' );

}
```

Or some other error message. This is a corner case though.

**Comment by mrdoob** [comment]
@unphased 

Something to note is that we already have `fromArray()`. So your code could look like this:

```js
var mat = new THREE.Matrix3().fromArray(myVectorOf9Numbers);
```

But I guess your point is that we're creating an intermediate unused array.

I wonder if there are use cases in the library itself where something like the constructor proposed would be hugely beneficial memory wise.

**Comment by unphased** [comment]
I'll have to check the source but seems like reaching in to `.elements` and calling `set` would avoid reallocation at least. But yeah that's sort of handy I guess.

**Comment by abelnation** [comment]
I'd advocate for the constructor assuming the same major-format of matrices assumed elsewhere, i.e. row-major.  If providing an api call that deviates from that, would be nice to provide a method that specifically calls that deviation out, e.g. `Matrix4.fromColMajorArray` or something similar.  Even if the docs specify it, the API should strive for consistency to help the developer out.

**Comment by looeee** [comment]
I've added information on row-major versus column major to the Matrix3 and Matrix4 docs pages :)

**Comment by WestLangley** [comment]
>Something to note is that we already have `.fromArray()`

It appears that has proven to be adequate.
