### ISSUE TITLE
Issue with loading .dae object faces exported by autodesk max or blender

### ISSUE THREAD

**Issue by wallflips** [mrdoob/three.js#9285]
##### Description of the problem

Hey mr. Doob!

I'm currently having a problem when loading .dae object into scene. First the object had some of the meshes with inverted sides, for not known to me reasons, of course after a google research I found out that I can set the renderer to display both sides of each mesh, okay visibility problem fixed, but there appeared a shadow problem on the mesh children who's faces were inverted, please take a look at this image.

![bug](https://cloud.githubusercontent.com/assets/68115/16569693/dda5a8e0-4241-11e6-8661-01a38ee0872e.jpg)

Here is a sample of the code i'm using:

this.LoadObjectCollada = function(callback)
    {
        const loader = new THREE.ColladaLoader();

```
    loader.options.convertUpAxis = true;
    loader.load("files/models/" + extract.code + "/" + extract.model, function (collada) {
        object = collada.scene;
        object.scale.x = object.scale.y = object.scale.z = 40;

        object.traverse(function (child) {
            child.traverse(function (e) {
                //if (e instanceof THREE.Mesh)
                //{
                    e.castShadow = true;
                    e.receiveShadow = true;

                    if (e.material instanceof THREE.MeshPhongMaterial)
                    {
                        //const geometry = new THREE.Geometry().fromBufferGeometry(e.geometry);
                        //geometry.computeFaceNormals();
                        //geometry.mergeVertices();
                        //geometry.computeVertexNormals();

                        //e.geometry = new THREE.BufferGeometry().fromGeometry(geometry);

                        e.material.needsUpdate = true;
                        e.material.side = THREE.DoubleSide;

                        //e.material.transparent = true;
                    }
                //}
            });
        });

        object.objectID = objectIndex++;

        object.updateMatrix();

        loading = false;

        callback(object);
    });
};
```

And here is the model.
https://drive.google.com/file/d/0ByfFp07H3yCbeXJjRElZaml3ZHc/view?usp=sharing

I would also like to mention that this is happening to almost any random object I get online or make with several tools like Blender and Aurodesk Max.
##### Three.js version
- [ ] Dev
- [x] r78
- [ ] ...
##### Browser
- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by mrdoob** [comment]
Shadows need objects to be solid.
