### ISSUE TITLE
Image loader issue

### ISSUE THREAD

**Issue by rayros** [mrdoob/three.js#9288]
https://github.com/mrdoob/three.js/blob/master/src/loaders/ObjectLoader.js#L333

Manager never return callback onLoad, because loadImage use another manager from scope

**Comment by mrdoob** [comment]
Do you mind explaining the issue a bit more?

**Comment by makc** [comment]
Probably means scope.manager needs to be used

**Comment by rayros** [comment]
Yup,  something like this https://github.com/rayros/three.js/commit/1cc6e49b3e3c2a3f2d823a78bf9a6653c2cb5561

**Comment by mrdoob** [comment]
Is this the same as https://github.com/mrdoob/three.js/pull/9176 and https://github.com/mrdoob/three.js/pull/9287?

**Comment by Mugen87** [comment]
The actual issue is described in the referenced issue in more detail.
